### ISSUE TITLE
Web - Profile settings - Timezone drop down opens after using Enter Key twice

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#10034] opened 2022-07-20 14:11 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Go to URL https://staging.new.expensify.com/
2. Login with any account
3. Go to Settings/Profile settings
4. Use the "Tab" key to go to the timezone selection (the time zone should not be selected for automatic selection)
5. Press Enter key 

## Expected Result:
Timezone drop down opens after using Enter Key once

## Actual Result:
Timezone drop down opens after using Enter Key twice

## Workaround:
Unknown

## Platform:

Where is this issue occurring?

- Web
- iOS
- Android
- Desktop App
- Mobile Web

**Version Number:** 1.1.85.5

**Reproducible in staging?:** Yes

**Reproducible in production?:** Yes

**Email or phone of affected tester (no customers):** any

**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Notes/Photos/Videos:** Any additional supporting documentation

https://user-images.githubusercontent.com/93399543/180003455-3b5dee4e-5777-4abf-b947-068b06661af6.mp4

**Expensify/Expensify Issue URL:** 

**Issue reported by:** Applause - Internal Team

**Slack conversation:** 

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by jasperhuangg** [comment] 2022-07-20 19:29
I am unable to press `Enter` to open the dropdowns on my Mac at all, so I'm unable to reproduce the issue. However after looking at the code I think this is happening because [this button has `pressOnEnter` passed to it](https://github.com/Expensify/App/blob/025dcf7c61f084da1f625b3aee66ef73b3e0060e/src/pages/settings/Profile/ProfilePage.js#L309). This is what's happening in the video:

1. You're able to first open the pronouns dropdown with `Enter` because the button is disabled (since no changes to the form have been made yet). 
2. After you change your pronouns, the button detects a change in the form, becomes enabled and starts listening for `Enter` presses. 
3. When you go to open the timezone dropdown with `Enter`, the now-enabled button picks up this `Enter` press and stops it from propagating to the dropdown. 
4. Then, the button becomes disabled again, and the next time you hit `Enter` it's picked up by the timezone dropdown and opens it.

This isn't necessarily a bug, since it's expected that the button behaves this way, and it doesn't necessarily make the form unusable in regards to accessibility. The user just has to change and save each field one-at-a-time if they're navigating with the keyboard. Therefore I'm electing to close this out.

**Closed** 2022-07-20 19:32 UTC
Labels: Engineering, Daily
