### ISSUE TITLE
[$1000] Web - Split Bill - Until the user clicks on the chat, the LHN shows “This is the beginning of . . .” message and does not update

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#20059] opened 2023-06-02 14:52 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. From account A, split a bill with multiple accounts
2. Settle the money request from account B
3. Go to account A and observe the chat with account B on LHN
4. Click on the chat with account B
5. Notice the change of the chat with account B on LHN

## Expected Result:
When account B settles the money request the LHN on account A should update regardless of the user clicking on the chat to open it.

## Actual Result:
The LHN shows "This is the beginning of . . ." until user clicks on the chat, then the LHN message updates to show "settled up ..." message.

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [x] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 1.3.22.0

**Reproducible in staging?:** Yes

**Reproducible in production?:** Yes

**If this was caught during regression testing, add the test name, ID and link from TestRail:**

**Email or phone of affected tester (no customers):**

**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/93399543/8bdd673f-826a-4dc3-85e2-20c83d983648

https://github.com/Expensify/App/assets/93399543/3cf82e26-2cc1-4835-9096-c28c8b2c0d0f

**Expensify/Expensify Issue URL:**

**Issue reported by:** @Nathan-Mulugeta

**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1685517506405399

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01b72ee9991469d4ae</li>
        <li>Upwork Job ID: 1665960451336925184</li>
        <li>Last Price Increase: 2023-06-06</li>
    </ul>
</details>

**Comment by kadiealexander** [comment] 2023-06-06 05:52
Reproduced in web (chrome).

**Comment by JavSFDev** [comment] 2023-06-06 11:22
I can fix bug. How to do join this project?

**Comment by Nathan-Mulugeta** [comment] 2023-06-06 12:26
Start by reading the contributors guidelines

**Comment by s77rt** [comment] 2023-06-06 15:08
@JavSFDev Thanks for the interest. We have a proposal template to follow please checkout the [contributing guide](https://github.com/Expensify/App/blob/main/contributingGuides/CONTRIBUTING.md).

**Comment by Haysam-Bin-Tahir** [comment] 2023-06-06 22:14
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
We are trying to solve the problem of out-of-sync settlement status. When user A splits the bill with user B, we have a new report that only contains the info regarding the split, and this info is updated within the main chat thread b/w the two users. When user B pays the bill, user A sees settled text on the new report in real-time but the main chat thread keeps showing the previous status whether it is 'This is just the beginning...' or 'user b owes 10$', etc. User A needs to manually open the report to see the latest settlement text.

<img width="372" alt="Screenshot 2023-06-07 at 2 49 48 AM" src="https://github.com/Expensify/App/assets/60313334/8a37e7cc-02a6-40c5-978c-8b92f3932a22">

_The new report above can be seen with the updated settled text whereas the main chat still shows the old text_

### What is the root cause of that problem?
We are not receiving complete data updates through the onyxApiUpdate event after the user pays the bill. For the new report (which only includes a single message regarding the split bill), we receive a complete data update that also includes the updated lastMessageText value. But for the main chat thread, we do not receive the updated lastMessageText and hence the UI does not display the expected settlement text.

<img width="390" alt="Screenshot 2023-06-07 at 2 36 14 AM" src="https://github.com/Expensify/App/assets/60313334/00d168e1-0037-4d1d-ae27-b321b83f00b0">

_onyx update for the new report created after splitting the bill(Includes lastMessageText)_

<img width="241" alt="Screenshot 2023-06-07 at 2 41 15 AM" src="https://github.com/Expensify/App/assets/60313334/cf05ca4d-cdeb-4060-bc65-b5d631a27808">

_onyx update for the main chat thread where the issue occurs(Does not include lastMessageText)_

So, the issue is that we are not getting complete updated data from the backend/Pusher after paying the split bill.

### What changes do you think we should make in order to solve the problem?


While updating the server/Pusher to send the updated lastMessageText for the main chat thread as well  after paying the split bill is the optimal solution here, if we were to solve it on the frontend, I would suggest the following.

1. Wait for the 'pay elsewhere' call to be successful
2. Broadcast a ReportUpdateIntimation event to the other user along with the chat ID
3. The other user listens for this event and updates only the out-of-sync report through `openReport(reportID)`

In this way, we can get the latest settlement text on the report without having to manually open it. Since we are directly getting the chat ID, we do not have to bear any overhead of figuring out which chat needs a refresh call.

### What alternative solutions did you explore? (Optional)

I noticed that even if the settlement text does not update in real-time, we still get a tick mark within the report preview in real-time. It means that we are getting the correct paid status just not the correct text to display

<img width="412" alt="Screenshot 2023-06-07 at 3 03 11 AM" src="https://github.com/Expensify/App/assets/60313334/6585abc6-ad1e-4d56-a383-c115e44fb107">

_we see the tick mark next to the out-of-sync text_

I think we can make use of that information (hasOutstandingIOU from the onyx update) to call `openReport(reportID)`. This seems like a simpler and more straightforward fix but I would not prefer this. The reason is that, we can get several onyx merge updates where hasOutstandingIOU is false but do not need to be refreshed. This would cause a lot of unnecessary refreshes of the reports whereas in the solution above, we always only update the correctly needed report once.

**Alternatively**

If we have the option to do it on the backend, we can ensure to send the lastMessageText in the onyx update for currently out-of-sync report.

**Reminder:** Please use plain English, be brief and avoid jargon. Feel free to use images, charts or pseudo-code if necessary. Do not post large multi-line diffs or write walls of text. Do not create PRs unless you have been hired for this job.

**Comment by Haysam-Bin-Tahir** [comment] 2023-06-06 22:18
Contributor details
Your Expensify account email: haysam.bin.tahir@gmail.com
Upwork Profile Link: https://www.upwork.com/freelancers/~011796a46dbdbe059e

**Comment by s77rt** [comment] 2023-06-07 19:23
@Haysam-Bin-Tahir Thanks for the proposal. This seems internal.

@luacmartins Can you please take a look into this? This also happen if you request money from a user and that user paid you - the iou report is updated but not the chat.

**Comment by s77rt** [comment] 2023-06-08 16:32
I'm not sure it's external. You as the payee are not performing any action, there is no optimistic message to set. The payee is standing still. Once the payer pay. The payee will see that they did so but only in the iou report.

**Comment by luacmartins** [comment] 2023-06-08 17:09
Oh lol you're right. The whole time I thought those were two screens logged in as the same user 🤦

**Comment by luacmartins** [comment] 2023-06-12 17:06
I'm focused on finishing the delete functionality for Manual Request. I'll try to get to this later this week.

**Comment by luacmartins** [comment] 2023-06-15 21:16
I'm still focused on Manual Requests. I'll try to work on this next week.

**Comment by kadiealexander** [comment] 2023-06-19 05:39
Hey team! I'm just adding a note that I'll be OOO until June 26th. I don't think any bug0 team actions will come up this week but if you need a bug0 teammate while I'm gone, please reapply the label! Thanks.

**Comment by luacmartins** [comment] 2023-06-21 20:26
I haven't been able to prioritize this yet. I'll try to get to this next week.

**Comment by luacmartins** [comment] 2023-06-21 22:11
I just went over the issue again and this is expected for the chat report (we can see that the iou report gets updated). We're working on sending updates for the report preview that is seen in the chat report in [this PR](https://github.com/Expensify/Web-Expensify/pull/37525). Gonna close this issue since it's known and being addressed elsewhere.

**Closed by luacmartins** 2023-06-21 22:11 UTC
Labels: Daily, Internal, Bug
