### ISSUE TITLE
[HOLD for payment 2024-04-05] HIGH: [Video] [$500] Can not pause or play video on full screen mode

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#37803] opened 2024-03-05 23:11 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.47-6
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**  vdargentotest+web030424@gmail.comhttps://expensify.testrail.io/index.php?/tests/view/4378376
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** Applause - Internal Team
**Slack conversation:**

## Action Performed:
Pre-requisite: the user must be logged in
1. Go to any chat
2. Send a video
3. Open it on full screen mode (important step)
4. Click on the video to play or pause
5. Verify the video is not played or paused

## Expected Result:
The video should be played or paused when clicked on it

## Actual Result:
The video does not play or pause when the user clicks on it

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details> 

https://github.com/Expensify/App/assets/78819774/56ffd6b9-a69d-40a5-a8e6-e8249fd052a3

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~013d32a95574e162d0</li>
        <li>Upwork Job ID: 1767124547020718080</li>
        <li>Last Price Increase: 2024-03-18</li>
<li>Automatic offers: </li>
<ul>
<li>ShridharGoel | Contributor | 0</li>
</ul></li>
    </ul>
</details>

**Comment by lanitochka17** [comment] 2024-03-05 23:11
We think that this bug might be related to #vip-vsp
CC @quinthar

**Comment by lanitochka17** [comment] 2024-03-05 23:12
@dylanexpensify  FYI I haven't added the External label as I wasn't 100% sure about this issue. Please take a look and add the label if you agree it's a bug and can be handled by external contributors

**Comment by ShridharGoel** [comment] 2024-03-06 07:59
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
Can not pause or play video on full screen mode.

### What is the root cause of that problem?
For full screen mode, play and pause methods are being called from two places - `togglePlayCurrentVideo` and `handleFullscreenUpdate`.

### What changes do you think we should make in order to solve the problem?
In `togglePlayCurrentVideo`, there should be a check for full screen mode. If video is playing in full screen mode, then play and pause should not be called from that method.

A state called `fullScreenMode` can be created (actual code can be more polished): 

```
const togglePlayCurrentVideo = useCallback(() => {
        videoResumeTryNumber.current = 0;
        if (!isCurrentlyURLSet) {
            updateCurrentlyPlayingURL(url);
        } else if (isPlaying && !fullScreenMode) {
            pauseVideo();
        } else if (!fullScreenMode) {
            playVideo();
        }
    }, [isCurrentlyURLSet, isPlaying, pauseVideo, playVideo, updateCurrentlyPlayingURL, url]);
```

**Comment by dylanexpensify** [comment] 2024-03-06 10:45
Apologies, I've been OOO sick, but getting to this today!

**Comment by ShridharGoel** [comment] 2024-03-07 07:09
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
Can not pause or play video on full screen mode.

### What is the root cause of that problem?
For full screen mode, play and pause methods are being called from two places - `togglePlayCurrentVideo` and `handleFullscreenUpdate`.

### What changes do you think we should make in order to solve the problem?
In `togglePlayCurrentVideo`, there should be a check for full screen mode. If video is playing in full screen mode, then play and pause should not be called from that method.

A state called `isFullscreen` can be created (actual code can be more polished): 

```
const [isFullscreen, setIsFullscreen] = useState(false)

const togglePlayCurrentVideo = useCallback(() => {
    videoResumeTryNumber.current = 0;
    if (!isCurrentlyURLSet) {
        updateCurrentlyPlayingURL(url);
    } else if (isPlaying && !isFullscreen) {
        pauseVideo();
    } else if (!isFullscreen) {
        playVideo();
    }
}, [isCurrentlyURLSet, isPlaying, pauseVideo, playVideo, updateCurrentlyPlayingURL, url, isFullscreen]);
```

**Comment by dylanexpensify** [comment] 2024-03-11 09:44
Agreed, HIGH!

**Comment by sobitneupane** [comment] 2024-03-13 10:05
Thanks for the proposal @ShridharGoel. 

> For full screen mode, play and pause methods are being called from two places - togglePlayCurrentVideo and handleFullscreenUpdate.


I don't think I can agree with your RCA. If I am not wrong, `handleFullscreenUpdate` is called only once on opening the video on fullscreen mode and once on closing the fullscreen mode. So, I don't think `handleFullscreenUpdate` is called on each play and pause.

More elaborative RCA is appreciated.

**Comment by dylanexpensify** [comment] 2024-03-13 10:06
Nice, @ShridharGoel to update if he can

**Comment by brunovjk** [comment] 2024-03-18 18:53
@sobitneupane Could you please confirm a behavior for me? In the `Video Preview`, a single click currently plays/pauses the video, which is expected. However a double-click should trigger fullscreen mode? Currently, it only plays/pauses again. Additionally, when already in fullscreen mode, a single click doesn't play/pause (as reported), while a double-click closes fullscreen. Could you verify if this is the intended behavior? Thank you!

**Comment by dylanexpensify** [comment] 2024-03-18 20:29
@sobitneupane can we get reviews on updated proposal and @brunovjk's question!

**Comment by sobitneupane** [comment] 2024-03-19 07:29
> Could you please confirm a behavior for me? In the Video Preview, a single click currently plays/pauses the video, which is expected. However a double-click should trigger fullscreen mode? Currently, it only plays/pauses again. Additionally, when already in fullscreen mode, a single click doesn't play/pause (as reported), while a double-click closes fullscreen. Could you verify if this is the intended behavior? Thank you!

@brunovjk We are mainly trying to deal with the later in this issue ,i.e., When already in fullscreen mode, a single click should play or pause the video. The triggering fullscreen mode on double click is also a nice feature to have. You can add it in your proposal.

**Comment by sobitneupane** [comment] 2024-03-19 07:32
Thanks for the update @ShridharGoel. 

> For full screen mode, play and pause methods are being called from two places - togglePlayCurrentVideo and the internal implementation of full screen video player in av-expo.

In that case, can we prevent default behavior of expo-av instead?

**Comment by mvtglobally** [comment] 2024-03-20 03:42
Issue not reproducible during KI retests. (First week)

**Comment by sobitneupane** [comment] 2024-03-20 08:25
Thanks for the proposal @ShridharGoel 

[Proposal](https://github.com/Expensify/App/issues/37803#issuecomment-1982669048) from @ShridharGoel looks good to me.

🎀 👀 🎀 C+ reviewed

**Comment by grgia** [comment] 2024-03-20 11:11
All yours @ShridharGoel!

**Comment by dylanexpensify** [comment] 2024-03-20 11:43
nice!

**Comment by quinthar** [comment] 2024-03-23 00:31
Hi @ShridharGoel  what's the ETA for completing this?

**Comment by dylanexpensify** [comment] 2024-03-27 08:17
PRs merged, waiting for regression period then paying out!

**Comment by dylanexpensify** [comment] 2024-04-09 13:34
Payment summary:
- Contributor: @ShridharGoel $500
- Contributor+: @sobitneupane $500

Please apply/request!

**Comment by dylanexpensify** [comment] 2024-04-09 13:36
Done!

**Closed by dylanexpensify** 2024-04-09 13:36 UTC
Labels: External, Weekly, Awaiting Payment, Bug

**Comment by JmillsExpensify** [comment] 2024-04-11 20:48
$500 approved for @sobitneupane
