### ISSUE TITLE
[PAID] [$500] Chat - Single line code block is hidden if user insert an emoji into it

### ISSUE THREAD

**Issue by izarutskaya** [Expensify/App#37738] opened 2024-03-05 12:30 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.47-0
**Reproducible in staging?:** Y
**Reproducible in production?:** N
**Email or phone of affected tester (no customers):** fischer9966@gmail.com
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** Applause-Internal Team

## Action Performed:
1. Open App or go to staging.new.expensify.com
2. Login with any account
3. Open any chat
4. Post message with single line code block with any text
5. Edit the block by adding emoji to it
6. Save message

## Expected Result:
Edited single line code block appears in the chat with all content including the added emoji

## Actual Result:
Edited single line code block is hidden if user insert an emoji into it. But this block is still editable.

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [ ] Android: mWeb Chrome
- [x] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

https://github.com/Expensify/App/assets/115492554/440f08b6-cd80-4ea0-99ff-5f791e1b4d73

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~016316c465e62d2eab</li>
        <li>Upwork Job ID: 1764992662563991552</li>
        <li>Last Price Increase: 2024-03-05</li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @strepanier03</details>

**Comment by izarutskaya** [comment] 2024-03-05 12:30
@nkuoch I haven't added the External label as I wasn't 100% sure about this issue. Please take a look and add the label if you agree it's a bug and can be handled by external contributors.

**Comment by nkuoch** [comment] 2024-03-05 12:33
I think it can be external yes.

**Comment by roryabraham** [comment] 2024-03-05 19:06
should be fixed by https://github.com/Expensify/App/pull/37778 in [1.4.47-3](https://github.com/Expensify/App/actions/runs/8161606247)

**Comment by kavimuru** [comment] 2024-03-05 19:52
Issue is not reproducible anymore. 

https://github.com/Expensify/App/assets/43996225/0447ad78-47e1-41bc-93da-223b114a5c80

**Comment by Akintunde102** [comment] 2024-03-05 19:52
I figured out what the issue is.

It's here:[InlineCodeBlock ](https://github.com/Expensify/App/blob/main/src/components/InlineCodeBlock/index.tsx)

The InlineCodeBlock component treats all incoming code as though it will always be text and nothing else, thereby making it impossible for `react-native-render-html` to make use of the EmojiRenderer and possibly any other tag-based HTML renderer.

My approach is to remove the strict approach and allow the InlineCodeBlock process more than just text. It works.

**Comment by Akintunde102** [comment] 2024-03-05 19:57
Contributor details
Your Expensify account email: jegedeakintunde@gmail.com
Upwork Profile Link: https://www.upwork.com/freelancers/~01be6c6597c392c7ce

**Comment by roryabraham** [comment] 2024-03-05 20:55
great, I think we would be ready to close this out, @strepanier03 just need to pay @mkhutornyi for their review of the revert. Because it was a revert, I don't think it makes sense to wait the 7 days for the regression period. We should just pay it out today

**Comment by strepanier03** [comment] 2024-03-11 03:36
Missed this comment, sorry about that. Working on payment now.

**Comment by strepanier03** [comment] 2024-03-11 03:48
@mkhutornyi - I sent you an offer for a job, I'll check to try to pay it tomorrow.

**Comment by strepanier03** [comment] 2024-03-13 04:46
All paid, closing.

**Closed by strepanier03** 2024-03-13 04:46 UTC
Labels: External, Engineering, Daily, Overdue, Bug
