### ISSUE TITLE
[$1000] mweb - Request Money - Date is being chopped off in Request payment detail screen

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#22548] opened 2023-07-10 11:42 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Request payment from someone
2. Go to Request payment detail screen

## Expected Result:
 Date should be shown full

## Actual Result:
Date is being chopped off

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [x] iOS / Safari
- [ ] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 1.3.38.3
**Reproducible in staging?:** n/a
**Reproducible in production?:** n/a
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/93399543/e9a4c402-3e9d-4b66-a687-113387fcd529

![Image from iOS](https://github.com/Expensify/App/assets/93399543/508a3e1c-9d87-47d7-938c-aad7ee9390b3)

**Expensify/Expensify Issue URL:**
**Issue reported by:** @DinalJivani
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1688936914645879

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01513701e8cee8dc92</li>
        <li>Upwork Job ID: 1679381942222696448</li>
        <li>Last Price Increase: 2023-07-13</li>
    </ul>
</details>

**Comment by greg-schroeder** [comment] 2023-07-11 03:17
Reviewing

**Comment by greg-schroeder** [comment] 2023-07-11 03:24
Can't repro - asked in Slack for more specific steps/pre-reqs: https://expensify.slack.com/archives/C049HHMV9SM/p1689045848555629?thread_ts=1688936914.645879&cid=C049HHMV9SM

**Comment by narefyev91** [comment] 2023-07-13 07:07
@greg-schroeder Could not reproduce on latest main

https://github.com/Expensify/App/assets/28352309/33cc6ef8-1e42-4f60-9180-9fc823813049

**Comment by akinwale** [comment] 2023-07-14 06:32
@greg-schroeder I think this issue might be reproducible on iOS 14 (you'll notice that the Safari address bar is at the top in the original video). However, the app wouldn't even load for me in the iOS 14.5 simulator (I get stuck on the splash logo) due to some issues with pdfjs not being supported.

**Comment by narefyev91** [comment] 2023-07-14 07:33
I think we can close this based on discussion in slack https://expensify.slack.com/archives/C01GTK53T8Q/p1689316565802669
<img width="388" alt="Screenshot 2023-07-14 at 10 31 41" src="https://github.com/Expensify/App/assets/28352309/90f6bb3a-ddb7-449b-aa4a-a8c302d9cb1f">

**Comment by greg-schroeder** [comment] 2023-07-17 16:15
Closing per above, then

**Closed by greg-schroeder** 2023-07-17 16:15 UTC
Labels: External, Daily, Needs Reproduction, Help Wanted, Overdue, Bug
