### ISSUE TITLE
[HOLD for payment 2024-06-06] [$250] Chat - Emojis auto-selected after sending a message with a space before choosing from composer

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#41433] opened 2024-05-01 17:49 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.69-0
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**If this was caught during regression testing, add the test name, ID and link from TestRail:** N/A
**Email or phone of affected tester (no customers):** abebemiherat@gmail.com
**Issue reported by:** Applause - Internal Team

## Action Performed:
1. Open any chat
2. Add a space, type, and send a message
3. Select emojis from the composer

## Expected Result:
Emojis should not auto-select

## Actual Result:
Emojis auto-selected after sending a message with a space before choosing from the composer

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details> 

https://github.com/Expensify/App/assets/78819774/d39a85c3-5e7b-4992-bfae-0b1277687ed0

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~012e8ae36539563c3f</li>
        <li>Upwork Job ID: 1786441339870445568</li>
        <li>Last Price Increase: 2024-05-10</li>
<li>Automatic offers: </li>
<ul>
<li>ishpaul777 | Reviewer | 0</li>
</ul></li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @StaniMilko</details>

**Comment by lschurr** [comment] 2024-05-03 17:03
Hi @ishpaul777 - when you get a chance can you try reproducing and confirm this bug is still happening?

**Comment by StaniMilko** [comment] 2024-05-06 14:55
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
Chat - Emojis auto-selected after sending a message with a space before choosing from composer.
**_This issue is reproducible when sending message with send button, not with enter key._**

### What is the root cause of that problem?
When we type in composer, [`selection`](https://github.com/Expensify/App/blob/3540f6360cccabb0000e3a0956903dbf20323f9a/src/pages/home/report/ReportActionCompose/ComposerWithSuggestions/ComposerWithSuggestions.tsx#L289C5-L289C76) is updated.
If we send message with send button, composer is cleared but the value of `selection` is not reset(it remains as something like `{start: 3, end: 3, positionX: 33, positionY: 2}`).
So if we add emoji after that, emoji is auto-selected.

### What changes do you think we should make in order to solve the problem?
We can reset `selection` when sending message.
Set `selection` with [initial value](https://github.com/Expensify/App/blob/c496ce653943934f6a47bae2fcf520ae08c69743/src/pages/home/report/ReportActionCompose/ComposerWithSuggestions/ComposerWithSuggestions.tsx#L289C55-L289C73) in [this function](https://github.com/Expensify/App/blob/c496ce653943934f6a47bae2fcf520ae08c69743/src/pages/home/report/ReportActionCompose/ReportActionCompose.tsx#L284).

### What alternative solutions did you explore? (Optional)

**Comment by lschurr** [comment] 2024-05-06 16:02
Hi @ishpaul777 - Could you check the proposal here?

**Comment by lschurr** [comment] 2024-05-06 22:28
Not overdue. I'm not sure why Melvin keeps adding that.

**Comment by lschurr** [comment] 2024-05-09 19:18
Bump on this @ishpaul777

**Comment by brunovjk** [comment] 2024-05-09 21:19
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
Inconsistent behavior exists between sending chat messages with the `Enter key` versus the `Send button`.
After sending a message with the Enter key, we correctly clears the composer selection, preventing auto-selection of emojis. The Send button doesn't perform this action, leading to the unexpected auto-selection of an emoji when the composer is re-focused.

### What is the root cause of that problem?
Lack of selection clearing when using the Send button to submit a message:
- Enter Key Behavior
    -  The `RNMarkdownTextInput` component's `onSelectionChange` event is triggered.
    -  The `addCursorPositionToSelectionChange` function resets the composer selection, preventing the auto-select issue.
- Send Button Behavior
    -  Currently, no event explicitly resets the composer selection, leading to the auto-select issue.

### What changes do you think we should make in order to solve the problem?
To address this, we need to introduce a mechanism to reset the composer selection after the Send button is used.
Add code within the `handleSendMessage` function to explicitly reset the text input selection after the message is sent. This might involve using refs to access the underlying input element and manipulate its selection.

### What alternative solutions did you explore? (Optional)
Find a way to utilize the `onSelectionChange` event or a similar event handler in conjunction with the Send button. This might involve adding a hidden input element that can trigger the selection reset logic.

**Comment by StaniMilko** [comment] 2024-05-10 02:43
@ishpaul777 
Currently, I can't create branch due to problem on my side.
I've updated [proposal](https://github.com/Expensify/App/issues/41433#issuecomment-2096232376) with details. Sorry for inconvenience.

**Comment by brunovjk** [comment] 2024-05-10 16:54
I think the `SendButton` could emit some event. Still working on it.

**Comment by StaniMilko** [comment] 2024-05-11 23:35
@ishpaul777 
Thank you for your check.
I've update [proposal](https://github.com/Expensify/App/issues/41433#issuecomment-2096232376) covering your suggestion.

**Comment by StaniMilko** [comment] 2024-05-13 15:00
@ishpaul777 
Thank you for your review.
I will create PR in 2 or 3 days.

**Comment by techievivek** [comment] 2024-05-14 08:43
@StaniMilko You can work on the PR now, thanks.

**Comment by StaniMilko** [comment] 2024-05-14 23:28
Hi, @ishpaul777 
I've created [PR](https://github.com/Expensify/App/pull/42180).

**Comment by StaniMilko** [comment] 2024-05-28 12:51
@techievivek cc: @lschurr
I can't sure if merge freeze is over. I can see some other commits merged recently.

**Comment by lschurr** [comment] 2024-06-06 16:24
Payment summary:

- Contributor: $250 @StaniMilko (need Upwork profile to send offer)
- Contributor+: $250 @ishpaul777 (paid in Upwork)

**Comment by lschurr** [comment] 2024-06-06 16:25
@StaniMilko - Can you link your Upwork profile here so that I can send an offer for payment?

**Comment by lschurr** [comment] 2024-06-07 16:19
Bump on this @StaniMilko

**Comment by lschurr** [comment] 2024-06-10 15:52
This is done - I'm just waiting @StaniMilko's Upwork profile so that I can send an offer and pay.

**Comment by lschurr** [comment] 2024-06-11 22:37
I'm closing this since the bug is fixed. @StaniMilko - please comment with your Upwork profile for payment.

**Closed by lschurr** 2024-06-11 22:37 UTC
Labels: External, Weekly, Awaiting Payment, Bug

**Comment by StaniMilko** [comment] 2024-08-17 15:48
@lschurr 
Sorry for delay. Can I get payment now?

Contributor details
Your Expensify account email: stanimilko@outlook.com
Upwork Profile Link: https://www.upwork.com/freelancers/~01e245e9acd9e0797a

**Comment by KMichel1030** [comment] 2024-08-19 13:24
Friendly bump @lschurr

**Comment by lschurr** [comment] 2024-08-19 19:06
Paid in Upwork :)

**Comment by StaniMilko** [comment] 2024-08-19 19:07
@lschurr 
Thank you very much.
