### ISSUE TITLE
[$500] Request money - Scan - Unexpected error editing the money request, please try again later when trying to change the long description of the Request money

### ISSUE THREAD

**Issue by izarutskaya** [Expensify/App#28630] opened 2023-10-02 15:58 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Click on available chat
2. Click on the Plus sign -> Request money -> Scan -> Input any image ->Request button
3. Click on Request money which has just been successfully created
4. Add a new Amount and Merchant, and add a long description
5. Change the description to any numbers (1234456979669)

## Expected Result:
The description can be changed at any time

## Actual Result:
Unable to change the description and receive messages " Unexpected error editing the money request, please try again later"

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [x] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [x] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** v1.3.75-8

**Reproducible in staging?:** Y

**Reproducible in production?:** Y

**If this was caught during regression testing, add the test name, ID and link from TestRail:**

**Email or phone of affected tester (no customers):**

**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Notes/Photos/Videos:** Any additional supporting documentation

[Screencast from 09-29-2023 12_24_02 AM.webm](https://github.com/Expensify/App/assets/115492554/aa205d8d-3294-4230-9fac-550cfae570e1)

https://github.com/Expensify/App/assets/115492554/70afc6fa-e248-43e4-8d12-0af0aca08316

**Expensify/Expensify Issue URL:**

**Issue reported by:** @thuyle04

**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1696171141362759

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01a3dbfa84dda22d80</li>
        <li>Upwork Job ID: 1708874133252222976</li>
        <li>Last Price Increase: 2023-10-23</li>
    </ul>
</details>

**Comment by soro-kuraima** [comment] 2023-10-03 00:56
this error occurs when there are only digits in the description and this error is actually occuring on the server side.
when trying to change description to a number this is the server response:
```javascript
{
    "jsonCode": 500,
    "message": "500 Unhandled Exception",
    "onyxData": [],
    "requestID": "8101259c3fbcf446-BOM"
}
```

contrary to when the input contains even one character other than numeric digit
```javascript
{
    "jsonCode": 200,
    "requestID": "8101288f8d7a3cac-BOM",
    "onyxData": [
        {
            "onyxMethod": "merge",
            "key": "transactions_7578916569909825283",
            "value": {
                "amount": 50000,
                "billable": false,
                "category": "",
                "comment": {
                    "comment": "7 c"
                },
                "created": "2023-10-03",
                "currency": "INR",
                "filename": "",
                "merchant": "Request",
                "modifiedAmount": 50000,
                "modifiedCreated": "",
                "modifiedCurrency": "INR",
                "modifiedMerchant": "",
                "receipt": [],
                "reportID": "2563776644134920",
                "tag": "",
                "transactionID": "7578916569909825283"
            }
        },
        {
            "onyxMethod": "merge",
            "key": "report_7261175981021192",
            "value": {
                "reportID": "7261175981021192",
                "maxSequenceNumber": 7,
                "lastVisibleActionCreated": "2023-10-03 00:44:45.601",
                "lastReadTime": "2023-10-02 23:57:20.312",
                "lastMentionedTime": null,
                "lastMessageText": "You",
                "lastActorAccountID": 15752432
            }
        },
        {
            "onyxMethod": "merge",
            "key": "reportActions_7261175981021192",
            "value": {
                "8525941034341482920": {
                    "person": [
                        {
                            "type": "TEXT",
                            "style": "strong",
                            "text": "Abhishek Sharma"
                        }
                    ],
                    "actorAccountID": 15752432,
                    "message": [
                        {
                            "type": "TEXT",
                            "style": "strong",
                            "text": "You"
                        },
                        {
                            "type": "TEXT",
                            "style": "normal",
                            "text": " modified expense 'Request'. "
                        },
                        {
                            "type": "TEXT",
                            "style": "normal",
                            "text": "New merchant is '' (previously 'Request'). "
                        },
                        {
                            "type": "TEXT",
                            "style": "normal",
                            "text": "New description is '7 c' (previously '7 b'). "
                        }
                    ],
                    "originalMessage": {
                        "created": "2023-10-03",
                        "lastModified": "2023-10-03 00:44:45.601",
                        "merchant": "",
                        "newComment": "7 c",
                        "oldComment": "7 b",
                        "oldCreated": "2023-10-03",
                        "oldMerchant": "Request"
                    },
                    "avatar": "https://d1wpcgnaa73g0y.cloudfront.net/633d0d5fba4ebd5d34feff5f5a6dbb59f642b53c_128.jpeg",
                    "created": "2023-10-03 00:44:45.601",
                    "timestamp": 1696293885,
                    "reportActionTimestamp": 1696293885601,
                    "automatic": false,
                    "actionName": "MODIFIEDEXPENSE",
                    "shouldShow": true,
                    "reportActionID": "8525941034341482920",
                    "previousReportActionID": "2143568970301401613",
                    "lastModified": "2023-10-03 00:44:45.601",
                    "actorEmail": "abhi.asno1@gmail.com",
                    "whisperedToAccountIDs": [],
                    "sequenceNumber": 7,
                    "isAttachment": false
                }
            },
            "shouldNotify": true
        },
        {
            "onyxMethod": "merge",
            "key": "report_2563776644134920",
            "value": {
                "reportID": "2563776644134920",
                "reportName": "IOU",
                "type": "iou",
                "chatType": "",
                "ownerEmail": "abhi.asno1@gmail.com",
                "ownerAccountID": 15752432,
                "managerEmail": "shivam15@gmail.com",
                "managerID": 15761286,
                "policyID": "14E60807433B07DB",
                "participants": [
                    "shivam15@gmail.com"
                ],
                "participantAccountIDs": [
                    15761286
                ],
                "isPinned": false,
                "lastReadTime": "2023-10-02 22:59:53.632",
                "lastMentionedTime": null,
                "lastReadSequenceNumber": 0,
                "lastVisibleActionCreated": "2023-10-02 22:59:53.632",
                "lastVisibleActionLastModified": "2023-10-02 22:59:53.632",
                "lastMessageText": "requested ₹500.00",
                "lastActorAccountID": 15752432,
                "notificationPreference": "always",
                "welcomeMessage": "",
                "stateNum": 1,
                "statusNum": 1,
                "oldPolicyName": "",
                "visibility": null,
                "isOwnPolicyExpenseChat": false,
                "lastMessageHtml": "requested ₹500.00",
                "iouReportID": null,
                "hasOutstandingIOU": true,
                "policyName": null,
                "hasParentAccess": true,
                "parentReportID": "1825420021194336",
                "parentReportActionID": "4099226988917344091",
                "writeCapability": "all",
                "description": null,
                "isDeletedParentAction": null,
                "total": 50000,
                "currency": "INR",
                "submitterPayPalMeAddress": "",
                "chatReportID": "1825420021194336",
                "isWaitingOnBankAccount": false
            }
        },
        {
            "onyxMethod": "merge",
            "key": "report_1825420021194336",
            "value": {
                "reportID": "1825420021194336",
                "maxSequenceNumber": 1,
                "lastVisibleActionCreated": "2023-10-03 00:44:45.602",
                "lastReadTime": "2023-10-02 23:34:50.525",
                "lastMentionedTime": null,
                "lastMessageText": "shivam15@gmail.com owes ₹500.00",
                "lastActorAccountID": 15752432
            }
        },
        {
            "onyxMethod": "merge",
            "key": "reportActions_1825420021194336",
            "value": {
                "4099226988917344091": {
                    "person": [
                        {
                            "type": "TEXT",
                            "style": "strong",
                            "text": "Abhishek Sharma"
                        }
                    ],
                    "actorAccountID": 15752432,
                    "message": [
                        {
                            "type": "COMMENT",
                            "html": "shivam15@gmail.com owes ₹500.00",
                            "text": "shivam15@gmail.com owes ₹500.00",
                            "isEdited": false,
                            "whisperedTo": [],
                            "isDeletedParentAction": false,
                            "reactions": []
                        }
                    ],
                    "originalMessage": {
                        "lastModified": "2023-10-02 22:59:53.633",
                        "linkedReportID": "2563776644134920"
                    },
                    "avatar": "https://d1wpcgnaa73g0y.cloudfront.net/633d0d5fba4ebd5d34feff5f5a6dbb59f642b53c_128.jpeg",
                    "created": "2023-10-03 00:44:45.602",
                    "timestamp": 1696293885,
                    "reportActionTimestamp": 1696293885602,
                    "automatic": false,
                    "actionName": "REPORTPREVIEW",
                    "shouldShow": true,
                    "reportActionID": "4099226988917344091",
                    "previousReportActionID": "3803800476565195048",
                    "lastModified": "2023-10-02 22:59:53.633",
                    "childReportID": 2563776644134920,
                    "childType": "iou",
                    "childStatusNum": 1,
                    "childStateNum": 1,
                    "childMoneyRequestCount": 1,
                    "whisperedToAccountIDs": [],
                    "sequenceNumber": 1,
                    "isAttachment": false
                }
            },
            "shouldNotify": true
        }
    ]
}
``` 
 
 i think, this error has to be handled on the server side.

**Comment by mallenexpensify** [comment] 2023-10-04 23:26
Thanks @soro-kuraima , @mollfpr , do you agree? And, if so, should this be `Internal`?

**Comment by mollfpr** [comment] 2023-10-05 19:33
![Screenshot 2023-10-06 at 02 30 47](https://github.com/Expensify/App/assets/25520267/85ce3f3f-2ec2-4ce5-bc3d-576e61681d67)

I can't reproduce the issue. Maybe because the long description I use is different from the video?

@thuyle04 Could you confirm if the issue is still reproduced? If yes, please attach the text you use in the step.

**Comment by mollfpr** [comment] 2023-10-09 10:17
@soro-kuraima Are you able to repro this in the latest `main`?

**Comment by mallenexpensify** [comment] 2023-10-13 22:17
Testing but it's taking a while to smartscan

**Comment by mollfpr** [comment] 2023-10-17 17:40
> Could you confirm if the issue is still reproduced? If yes, please attach the text you use in the step.

@thuyle04 Could you help with the above? Thanks!

**Comment by mallenexpensify** [comment] 2023-10-17 23:39
Unable to reproduce. 

https://github.com/Expensify/App/assets/22508304/2389c1bd-a9a4-423c-abcc-51b3511994fb

**Comment by mollfpr** [comment] 2023-10-20 15:35
I think we can close this issue.

**Closed** 2023-10-23 18:16 UTC
Labels: External, Engineering, Daily, Help Wanted, Overdue, Bug
