### ISSUE TITLE
[HOLD for payment 2024-04-25] [$500] Task - Task got created with VOIP number and not removed from LHN until error dismissed

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#37846] opened 2024-03-06 22:57 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.48.0
**Reproducible in staging?:** y
**Reproducible in production?:** y
**PR tested in Olddotl:** https://github.com/Expensify/Web-Expensify/pull/41156
**GH conversation:** https://github.com/Expensify/Web-Expensify/pull/41156#issuecomment-1981980971

## Action Performed:
1. Go to https://staging.new.expensify.com/
and log in
2. Click on FAB > Assign task
3. Enter title and continue to the next page
4. Assign task to +18183305299 and finish creating task

## Expected Result:
The task does not get created, the error message is displayed

## Actual Result:
The task was created and can be seen in LHN. The task is not removed from LHN until the error is dismissed

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

https://github.com/Expensify/App/assets/93399543/83af5689-3547-47a3-b42c-c7646fcc3d36

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~0139a3cb3807461275</li>
        <li>Upwork Job ID: 1767136585905844224</li>
        <li>Last Price Increase: 2024-03-11</li>
<li>Automatic offers: </li>
<ul>
<li>bernhardoj | Contributor | 0</li>
</ul></li>
    </ul>
</details>

**Comment by kbecciv** [comment] 2024-03-06 22:57
We think that this bug might be related to  #vip-vsb
CC @quinthar

**Comment by kbecciv** [comment] 2024-03-06 22:58
@laurenreidexpensify I haven't added the External label as I wasn't 100% sure about this issue. Please take a look and add the label if you agree it's a bug and can be handled by external contributors,

**Comment by bernhardoj** [comment] 2024-03-07 04:03
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
The task report stays in the LHN even though that assignee chat is removed when fails.

### What is the root cause of that problem?
When we create a task, there are 3 reports that are updated/created, task report, assignee, and share destination. For the assignee report, if it's a new optimistic report and fails, we clear/delete the report.
https://github.com/Expensify/App/blob/ffa731a28a2d1402148eef54e51d86fbb64321fe/src/libs/ReportUtils.ts#L4653-L4658

_NOTE: even if we remove the failure data above code, the task report will still be deleted because OpenReport API is called (even though it shouldn't happen because it's an optimistic report) that will delete the report._

But for the task report, we never delete it.
https://github.com/Expensify/App/blob/ffa731a28a2d1402148eef54e51d86fbb64321fe/src/libs/actions/Task.ts#L173-L182

For share destination report, we can only select an existing report, so there is no need to delete it when creating the task fails.

### What changes do you think we should make in order to solve the problem?

Clear the task report when fails so it has a **CONSISTENT** behavior with the assignee report.
```
const failureData: OnyxUpdate[] = [
    {
        onyxMethod: Onyx.METHOD.SET,
        key: `${ONYXKEYS.COLLECTION.REPORT}${optimisticTaskReport.reportID}`,
        value: null,
    },
```

_or don't clear both report, but this would lead to even weirder behavior_

**Comment by laurenreidexpensify** [comment] 2024-03-11 10:33
Adding external label, but this feels low priority / edge case if this is specifically caused cos of a VOIP number being used

**Comment by andrey010** [comment] 2024-03-12 13:20
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
Task got created with VOIP number and not removed from LHN until error dismissed
### What is the root cause of that problem?
In the ```NewTaskPage.js``` we have function ```onSubmit``` which validate task data before send request 

https://github.com/Expensify/App/blob/c042950982603dae990063d9c7d338f8bca7215c/src/pages/tasks/NewTaskPage.js#L113-L117

this function has no validation for email and phone numbers, so in order to prevent the creation task with invalid data should add additional validation

### What changes do you think we should make in order to solve the problem?
 Should add write command ```VALIDATE_NUMBER``` and backend API for number validation
and add additional validation before call
https://github.com/Expensify/App/blob/c042950982603dae990063d9c7d338f8bca7215c/src/pages/tasks/NewTaskPage.js#L113-L117

for example
```javascript
Task.validateNumber(props.assignee)
setErrorMessage('newTaskPage.invalidNumber');
```
function ```validateNumber``` will look like
```javascript

function validateNumber(number: string) {
     // some code here for generating optimisticData, successData, failureData
    API.write(WRITE_COMMANDS.VALIDATE_NUMBER, parameters, {optimisticData, successData, failureData});
}
```

the main idea is to add form validation and set error message here  https://github.com/Expensify/App/blob/c042950982603dae990063d9c7d338f8bca7215c/src/pages/tasks/NewTaskPage.js#L70
and prevent API call with invalid number

**Comment by andrey010** [comment] 2024-03-14 08:10
## Proposal
[Updated](https://github.com/Expensify/App/issues/37846#issuecomment-1991638610)

**Comment by laurenreidexpensify** [comment] 2024-03-14 10:40
@allroundexperts do any of these solutions fit?

**Comment by allroundexperts** [comment] 2024-03-14 11:07
Hi @laurenreidexpensify!
I don't think the proposed solution would work. We don't have any such pattern where we are making backend call to validate something before the actual submission.

**Comment by bernhardoj** [comment] 2024-03-14 11:09
Please check my proposal

**Comment by allroundexperts** [comment] 2024-03-14 11:17
@bernhardoj I missed your proposal 😄. Looking at it now, Your RCA is correct and the solution given works as well. Thanks for the nudge.

🎀 👀 🎀 C+ reviewed

**Comment by andrey010** [comment] 2024-03-14 12:21
@allroundexperts but expected result is , show error message and no create task. Solution which you  choose will create optimistic data and then if api response has error will set optimistic data to null. I tested this solution and here any error message displayed. For UX any data why task not created

**Comment by allroundexperts** [comment] 2024-03-14 12:30
> @allroundexperts but expected result is , show error message and no create task. Solution which you choose will create optimistic data and then if api response has error will set optimistic data to null. I tested this solution and here any error message displayed. For UX any data why task not created

I think the best we can do here is to ensure consistency. I don't think we've ever used backend to validate stuff.

**Comment by andrey010** [comment] 2024-03-14 12:51
> > @allroundexperts but expected result is , show error message and no create task. Solution which you choose will create optimistic data and then if api response has error will set optimistic data to null. I tested this solution and here any error message displayed. For UX any data why task not created
> 
> 
> 
> I think the best we can do here is to ensure consistency. I don't think we've ever used backend to validate stuff, so your proposal doesn't make a lot of sense. I'd leave the final decision to the assigned internal engineer.

I said about offline rule. And about validation we have some command for validation like validation magic code

**Comment by allroundexperts** [comment] 2024-03-14 13:03
> And about validation we have some command for validation like validation magic code

That is something very different IMO.

**Comment by andrey010** [comment] 2024-03-14 13:28
> > And about validation we have some command for validation like validation magic code
> 
> That is something very different IMO.

what about this pattern (https://github.com/Expensify/App/blob/main/contributingGuides/OFFLINE_UX.md#c---blocking-form-ui-pattern).  I think it what we need for this issue

**Comment by bernhardoj** [comment] 2024-03-21 07:12
PR is ready

cc: @allroundexperts

**Comment by laurenreidexpensify** [comment] 2024-04-15 13:27
Deployed to prod on 10 April, so eligible for payment on 17 April

**Comment by laurenreidexpensify** [comment] 2024-04-17 11:38
Payment Summary:

- C+ @allroundexperts $500 please request in newdot
- Contributor @bernhardoj $500 payment issued in upwork

**Comment by laurenreidexpensify** [comment] 2024-04-17 11:38
@allroundexperts pls confirm if we need any checklist / regression steps before closing thanks

**Comment by allroundexperts** [comment] 2024-04-29 07:12
## Checklist

1. This was never implemented correctly since the feature was released.
2. N/A
3. N/A
4. A regression test would be helpful. The test steps given in the OP look clear enough to me.

**Closed** 2024-04-29 10:46 UTC
Labels: External, Daily, Awaiting Payment, Bug

**Comment by JmillsExpensify** [comment] 2024-06-17 19:54
$500 approved for @allroundexperts
