### ISSUE TITLE
[HOLD for payment 2024-01-26] [$250] [MEDIUM] IOU - IOU preview shows (none) in the main chat for request with receipt and no merchant

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#33874] opened 2024-01-03 16:06 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.21-1
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** Applause - Internal Team
**Slack conversation:**

## Action Performed:
1. Go to FAB > Request money > Manual.
2. Enter amount and select a user.
3. On the confirmation page, click 3-dot menu > Add a receipt.
4. Create the request after adding a receipt.

## Expected Result:
IOU preview will not show (none) in the main chat. It won't show anything in that row, ie. now `1 request`, 
<img width="525" alt="image" src="https://github.com/Expensify/App/assets/22508304/f53fc88a-e2f4-4500-b792-ffa85dbe9c4f">

## Actual Result:
IOU preview shows (none) in the main chat.

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [x] Android: mWeb Chrome
- [x] iOS: Native
- [x] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

https://github.com/Expensify/App/assets/93399543/6398b2c7-ccc3-463f-9d34-35bee109dddf

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~0122c75a36981f1098</li>
        <li>Upwork Job ID: 1742578112847630336</li>
        <li>Last Price Increase: 2024-01-05</li>
<li>Automatic offers: </li>
<ul>
<li>rojiphil | Contributor | 28092684</li>
</ul></li>
    </ul>
</details>

**Comment by lindseydortch** [comment] 2024-01-03 16:31
# Proposal

## Please re-state the problem that we are trying to solve in this issue.
When entering in an IOU manually and then going to upload the receipt, the chat is showing none as the recipient.


## What is the root cause of that problem?
The variable `PARTIAL_TRANSACTION_MERCHANT` which is set to "(none)" is being loaded here instead of `receiptMissingDetails` which is set to "Receipt missing details"

## What changes do you think we should make in order to solve the problem?
We need to change out the variable from `PARTIAL_TRANSACTION_MERCHANT` to `receiptMissingDetails` or the other options listed below.

We need to set the variable being loaded to something else besides `PARTIAL_TRANSACTION_MERCHANT` if we want text there, but not sure receipt is missing details is what we want in replace of that. If we want to recipient or the person sending it, then we need to put that variable in instead. 

Another option instead of "(none)" as the `PARTIAL_TRANSACTION_MERCHANT` we set it to "Receipt missing details" or something like "Not able to read merchant". Additionally maybe adding in a field to put the merchant name in if it can't read the receipt would be a good idea here.

**Comment by lindseydortch** [comment] 2024-01-03 16:33
Contributor details
Your Expensify account email: lindsey@alorscreative.com
Upwork Profile Link: https://www.upwork.com/freelancers/~01071c3a14964af0bb

**Comment by rojiphil** [comment] 2024-01-03 18:50
## Proposal

### Please re-state the problem that we are trying to solve in this issue.

(None) is displayed in report preview while we show empty value for merchant during money request generation.

### What is the root cause of that problem?

[Here](https://github.com/Expensify/App/blob/4a860664935d37f89e96abbe8ea535715b0172b8/src/components/ReportActionItem/ReportPreview.js#L160), we format the `merchant` value for display. However, since `(none)` is a default text which do not display, we are not skipping here. This is the root cause.

### What changes do you think we should make in order to solve the problem?

We can reset the `formattedMerchant` like this [here](https://github.com/Expensify/App/blob/4a860664935d37f89e96abbe8ea535715b0172b8/src/components/ReportActionItem/ReportPreview.js#L160) to solve this problem

    if(formattedMerchant === CONST.TRANSACTION.PARTIAL_TRANSACTION_MERCHANT) {
        formattedMerchant = null;
    }

### What alternative solutions did you explore? (Optional)

**Comment by mallenexpensify** [comment] 2024-01-05 01:03
Was able to reproduce and updated the Expected Behaviour in the OP. 
@rushatgabhane plz review the proposals above. 
Thx

**Comment by DylanDylann** [comment] 2024-01-05 07:39
@mountiny This has the same root cause with https://github.com/Expensify/App/issues/33818 and https://github.com/Expensify/App/issues/33798 . So I think we should hold this issue

**Comment by rojiphil** [comment] 2024-01-05 07:51
> This has the same root cause with #33818 and #33798 . So I think we should hold this issue

@DylanDylann 
I am not sure if I understand the correlation (i.e. same root cause) between this issue and the mentioned ones.
Can you please explain?

**Comment by mountiny** [comment] 2024-01-05 18:27
We can fix this now.

I think we want to create a helper method if it does not exist, which will check for partial merchant so `isPartialMerchant` that will be true if the merchant is `(none)` or `Unknown Merchant`.

I think this is super simple fix which I could otherwise give back to @waterim as PR author, but I will export it and make it $250 to reflect the scope of this issue.

@rushatgabhane can you please review the proposals?

**Comment by rojiphil** [comment] 2024-01-06 04:40
## Proposal

[Updated proposal ](https://github.com/Expensify/App/issues/33874#issuecomment-1875815133)to include the helper function as per feedback [here](https://github.com/Expensify/App/issues/33874#issuecomment-1879093264)

**Comment by mountiny** [comment] 2024-01-09 00:31
@rushatgabhane can you have a look please?

**Comment by rushatgabhane** [comment] 2024-01-10 04:46
@rojiphil's [proposal](https://github.com/Expensify/App/issues/33874#issuecomment-1875815133) LGTM
🎀 👀 🎀

**Comment by mountiny** [comment] 2024-01-10 14:26
@rojiphil can you please raise a PR? thanks!

**Comment by rushatgabhane** [comment] 2024-01-30 01:41
WIP ⚠️ 

1. The PR that introduced the bug has been identified. Link to the PR:

2. The offending PR has been commented on, pointing out the bug it caused and why, so the author and reviewers can learn from the mistake. Link to comment:

3. A discussion in #expensify-bugs has been started about whether any other steps should be taken (e.g. updating the PR review checklist) in order to catch this type of bug sooner. Link to discussion:

4. Determine if we should create a regression test for this bug.

5. If we decide to create a [regression test](https://github.com/Expensify/App/blob/main/contributingGuides/REGRESSION_TEST_BEST_PRACTICES.md) for the bug, please propose the regression test steps to ensure the same bug will not reach production again

**Comment by rojiphil** [comment] 2024-02-03 10:43
> If no regressions arise, payment will be issued on 2024-01-26

@mallenexpensify 
Overdue on payment for almost a week now.
Gentle bump on this.

**Comment by mallenexpensify** [comment] 2024-02-06 22:17
Contributor: @rojiphil paid $250 via Upwork
Contributor+: @rushatgabhane due $250 via NewDot

@rojiphil apologies for the delay

@rushatgabhane , can you please finish the checklist above so we can get this closed?

**Comment by JmillsExpensify** [comment] 2024-02-07 04:31
$250 approved for @rushatgabhane based on summary above.

**Comment by rushatgabhane** [comment] 2024-02-16 03:30
sorry, didn't get time yet to complete the checklist

**Comment by mallenexpensify** [comment] 2024-02-18 19:47
Please prioritize @rushatgabhane since it's been a month and we wanna get this closed.

**Comment by rushatgabhane** [comment] 2024-02-20 04:08
@mallenexpensify all done https://github.com/Expensify/App/issues/33874#issuecomment-1915907523

**Comment by mallenexpensify** [comment] 2024-02-23 22:45
Tahnks @rushatgabhane , closing
- https://github.com/Expensify/Expensify/issues/372509

**Closed by mallenexpensify** 2024-02-23 22:45 UTC
Labels: External, Weekly, Awaiting Payment, Bug
