### ISSUE TITLE
[HOLD App issue #13555] Avatar preview is blurry

### ISSUE THREAD

**Issue by kavimuru** [Expensify/App#14349] opened 2023-01-17 00:36 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:

1. Open the app
2. Go to Settings => Profile => Change the Avatar with any images that doesn’t look blurry.
3. Kill the app and wait for a while, open the app again and try to preview your avatar inside any report.
4. Notice that your avatar preview looks so blurry.

## Expected Result:
Avatar preview shouldn’t look blurry

## Actual Result:
Avatar preview looks blurry.

## Workaround:
unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [ ] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 1.2.54-2
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** 

https://user-images.githubusercontent.com/43996225/212785025-f9675070-d034-4f6c-8cd3-dc0397a6e59e.mp4

https://user-images.githubusercontent.com/43996225/213020562-e0459204-6437-4814-b15f-727e3e5c6c97.MP4

https://user-images.githubusercontent.com/43996225/213020947-6648537f-5527-43ef-98f7-3a7267530a33.mp4

**Expensify/Expensify Issue URL:**
**Issue reported by:** @hungvu193 
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1673615491816959

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by lschurr** [comment] 2023-01-17 17:06
I don't think the second video in the OP is relevant right @kavimuru?

**Comment by lschurr** [comment] 2023-01-17 17:26
Hm, I wasn't able to reproduce this. I changed my avatar image, killed the app, went back later and it still looks clear. Adding Eng for more eyes.

**Comment by kavimuru** [comment] 2023-01-17 21:56
@lschurr Updated video. Sorry about that.

**Comment by cristipaval** [comment] 2023-01-19 20:07
@Beamanator I think this should be fixed by the fix for [your issue](https://github.com/Expensify/App/issues/13555). Do you agree?

**Comment by Beamanator** [comment] 2023-01-20 11:05
Aah yes most likely, because we're full-screening a thumbnail picture :D

**Comment by cristipaval** [comment] 2023-01-20 12:55
Thanks for the confirmation. I'll set this on hold for now.

**Comment by cristipaval** [comment] 2023-01-23 11:39
`Weekly` - same as the issue that is held on.

**Comment by lschurr** [comment] 2023-02-09 20:53
Still on hold.

**Comment by lschurr** [comment] 2023-02-20 17:33
Believe this is still on hold.. is that right @cristipaval?

**Comment by cristipaval** [comment] 2023-02-20 18:26
Hmm.. it looks like the fix for the other one was merged. I'll test this one today and keep you posted here.

**Comment by cristipaval** [comment] 2023-02-20 19:12
yeah, it looks like this one is fixed now by [this PR](https://github.com/Expensify/App/pull/15185)

**Comment by lschurr** [comment] 2023-02-21 15:09
Reopening so that we can issue a reporting bonus - https://expensify.slack.com/archives/C01GTK53T8Q/p1676940741190779

**Comment by lschurr** [comment] 2023-02-21 16:49
@hungvu193 - Could you apply for the job in Upwork? https://www.upwork.com/jobs/~01903124f5eb7845ca

**Comment by lschurr** [comment] 2023-02-21 16:55
All set - payment has been issued.

**Closed by lschurr** 2023-02-21 16:55 UTC
Labels: Engineering, Weekly, Bug
