### ISSUE TITLE
[MEDIUM] Admin “force submit” throws a RBR red dot in the LHN and double messaging

### ISSUE THREAD

**Issue by Christinadobrzyn** [Expensify/App#33448] opened 2023-12-21 20:40 UTC
**Slack conversation:** https://expensify.slack.com/archives/C02MW39LT9N/p1703190155736439?thread_ts=1703187017.215259&cid=C02MW39LT9N

## Action Performed:

Pre-testing requirement: Collect workspace type with the isPolicyExpenseChatEnabled NVP set ([SO](https://stackoverflowteams.com/c/expensify/questions/17518)).

1. As the admin, go to OldDot and change the scheduled submit frequency to `manually` for a workspace
2. Log back into NewDot as the member (or refresh if you already are in another window)
• Verify that the LHN row for the workspace chat includes a GBR green dot for the draft report awaiting submission :white_check_mark:
4. Tap the workspace chat row to navigate to the workspace chat view
• Verify that the draft report preview component appears in the workspace chat  :white_check_mark:
• Verify that the draft report preview component in the chat:
5. Includes a green `Submit` button :white_check_mark:
6. Sign-in as the collect policy admin account, and navigate to the member’s workspace chat in NewDot
7. Tap the report preview component of the `draft` report to navigate to the expense report view
8. Tap the `Submit` button :x:
• Verify the text in the next steps banner updates to reflect the report has been submitted and is awaiting approval: “Waiting for %approverName% to review these requests” :white_check_mark:
• Verify a system message is added to the expense report from the admin that reads: “submitted %reportTotal%” :white_check_mark:
• Verify a green `Approve`/`Pay` button appears to approve the report :white_check_mark:

## Expected Result:

If an admin "force submits" an expense there's a GBR and one message about the expense submitted 

## Actual Result:

If an admin "force submits" an expense there's a RBR and multiple messages about the expense submitted 

## Screenshots/Videos

<img width="911" alt="image" src="https://github.com/Expensify/App/assets/51066321/cef23ff4-6a51-42a6-a51e-1319b51252cc">

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by greg-schroeder** [comment] 2023-12-31 10:34
Added to `High` will call out in next Weekly Update

**Comment by greg-schroeder** [comment] 2024-01-03 20:23
Will go in the next update

**Comment by greg-schroeder** [comment] 2024-01-08 21:28
Still trying to get our priorities in line

**Comment by greg-schroeder** [comment] 2024-01-11 20:00
Weekly update tomorrow 1.12

**Comment by greg-schroeder** [comment] 2024-01-18 00:31
Holding on higher prio items

**Comment by greg-schroeder** [comment] 2024-01-18 00:43
Melvin please relax

**Comment by greg-schroeder** [comment] 2024-01-22 16:52
Adjusting priority of wave issues to focus on migration

**Comment by trjExpensify** [comment] 2024-01-23 18:47
This a bug with a feature of drafts, why did we close it? 😕

**Comment by JmillsExpensify** [comment] 2024-01-25 23:49
Randomly came across this one and I'm curious about the same?

**Comment by trjExpensify** [comment] 2024-01-25 23:51
Going to reopen until we have an answer so it's not lost.

**Comment by greg-schroeder** [comment] 2024-01-26 18:51
Yeah, sorry about that. I was going through and closing a group of issues in my queue that weren't relevant to our roadmap - I had about ~15 or so open in tabs and closed them all at once. This one and another one were both open from doing the weekly update in the room, so I closed them by mistake alongside the rest

**Comment by trjExpensify** [comment] 2024-01-29 19:03
Cool, sounds good! 👍

**Comment by greg-schroeder** [comment] 2024-01-29 22:10
Setting as a `Hot Pick`

**Comment by rlinoz** [comment] 2024-01-31 18:48
I believe this has been fixed, but it would be good if someone could try to reproduce in staging/prod to make sure we can close this one.

https://github.com/Expensify/App/assets/5201282/898df060-c2c8-48af-a67b-691e847ef8ee


There seems to have another bug where the next step is not automatically updated for the submitter though.

**Comment by mountiny** [comment] 2024-01-31 19:43
@rlinoz I believe @JmillsExpensify had this issue today.

is your testing account and admin? The problem happens when the approver is not admin since we did not support this case in OldDot and currently the submit report command does not allow this for the approver

We were discussing it a bit [here](https://expensify.slack.com/archives/C02MW39LT9N/p1706711097428889)

**Comment by JmillsExpensify** [comment] 2024-02-01 03:21
Yeah I'm able to reliably reproduce this as an approver.

**Comment by mountiny** [comment] 2024-02-02 19:00
Keeping this on my radar if nobody picks it up, been focused on ideal nav these days!

**Comment by greg-schroeder** [comment] 2024-02-06 01:15
This will continue to be in the update until someone grabs it, hopefully soon!

**Comment by blimpich** [comment] 2024-02-06 02:28
Picking this up. Will start work on it tomorrow.

**Comment by blimpich** [comment] 2024-02-07 01:26
Started looking into this day, ran into some dev environment issues while trying to reproduce, so didn't get far. Will continue work on it tomorrow.

One question: I made a collect policy on old dot, and when I try to switch scheduled submit to manual I can't actually find where to do that. I followed this [help doc](https://community.expensify.com/discussion/4476/how-to-enable-scheduled-submit-for-a-group-policy/p1?new=1) but when I go to the reports page there is no scheduled submit option configuration modal, just this:

![Screenshot 2024-02-06 at 5 25 28 PM](https://github.com/Expensify/App/assets/17171674/ecfb80a2-62b8-4d56-94dd-e32149cdefa7)

Did this option get moved somewhere?

**Comment by trjExpensify** [comment] 2024-02-07 02:05
Oh, interesting! I can see the setting on staging:

<img width="1509" alt="image" src="https://github.com/Expensify/App/assets/16232057/0fc4959f-4bc3-4cf0-a0e8-100e067d9116">

**Comment by blimpich** [comment] 2024-02-07 19:23
Update: okay I was able to get it to switch to manually submit. Restarted my VM and it started working for some reason.

**Comment by blimpich** [comment] 2024-02-07 19:29
> is your testing account also an admin? The problem happens when the approver is not an admin since we did not support this case in OldDot and currently the submit report command does not allow this for a mere approver.

Huh, this is confusing because the issue description says in step 5 `Sign-in as the collect policy admin account`. Also I feel silly but how do I even make an approver that isn't an admin? Looking at stackoverflow [this](https://stackoverflowteams.com/c/expensify/questions/4438) appears sometime enlightening, but its not clear for the issue description that there is more setup required here.

**Comment by blimpich** [comment] 2024-02-07 19:42
Alright I think I was able to figure out how to reproduce this locally. Though my screen isn't exactly what is described in the issue description. I have three users, one admin, two normal workspace members, but in Old Dot under `Members > Approval Mode` I put one of my non-admin members as the person to submit reports to instead of the admin.

![Screenshot 2024-02-07 at 11 40 37 AM](https://github.com/Expensify/App/assets/17171674/7eede36d-978d-45d3-89f9-ac8599314e2e)

**Comment by blimpich** [comment] 2024-02-07 22:45
Alright, I think I've figured out a fix for this. The only question I have I think is whether or not its important for the approver's new privileges to be conditional on being in new dot.

In other words. In old dot approvers who aren't admins can't force submit expense reports. In new dot they are suppose to be able to, but this issue exists because they can't. I can change the code to make it so that approvers can force submit expense reports, but is it _important_ that approvers can't force submit in Old Dot still? Or can we just make it so that they can force submit in both worlds? 🌎

**Comment by blimpich** [comment] 2024-02-08 00:04
Waiting to hear back on [this slack](https://expensify.slack.com/archives/C03TQ48KC/p1707349670368319) thread before turning PR from draft to regular PR

**Comment by blimpich** [comment] 2024-02-08 20:38
PRs for Web and Auth are up, waiting on review and merge for both, and then this will be done.

**Comment by blimpich** [comment] 2024-02-16 17:00
This was deployed to production, closing as this is done.

**Comment by iwiznia** [comment] 2024-02-29 16:01
Auth PR was reverted https://github.com/Expensify/Auth/pull/9865

**Comment by blimpich** [comment] 2024-02-29 18:44
Oh, looks like we were quick on the trigger. Haven't reverted yet and looking to see if [this](https://github.com/Expensify/Auth/pull/10056#pullrequestreview-1909605931) fixes the issue. Will close this for now until we are sure that the PR for this issue is reverted [here](https://github.com/Expensify/Auth/pull/10055)

**Closed by blimpich** 2024-02-29 18:44 UTC
Labels: Reviewing, Engineering, Daily, Internal, Bug
