### ISSUE TITLE
[HOLD for payment 2023-10-23] [$500] Request money - On last day of month, going back to previous month disables forward button in request money date field

### ISSUE THREAD

**Issue by izarutskaya** [Expensify/App#28622] opened 2023-10-02 15:29 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
Precondition: It only happens when date is last day of month, if needed, same can be mimicked by changing device date
1. Open the app
2. Click on plus and click request money
3. Click on manual, enter any amount and continue
4. Select any user
5. Click on show more and click date
6. Click back arrow besides month and observe that now app disables next arrow making it impossible for user to get back to current month

## Expected Result:
App should not disable next button of month if next month in value is current month

## Actual Result:
App disables next button of month even if next month in value is current month in date field of request money on last day of month

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android / native
- [x] Android / Chrome
- [x] iOS / native
- [x] iOS / Safari
- [x] MacOS / Chrome / Safari
- [x] MacOS / Desktop

**Version Number:** v1.3.75-8

**Reproducible in staging?:** Y

**Reproducible in production?:** Y

**If this was caught during regression testing, add the test name, ID and link from TestRail:**

**Email or phone of affected tester (no customers):**

**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/115492554/19282643-7f38-4cfc-9826-7130e9a5ba3d

https://github.com/Expensify/App/assets/115492554/a3b79cab-c134-4a17-a50a-8a936ccd8999

https://github.com/Expensify/App/assets/115492554/c5d27e0c-b193-427d-aec4-fb6a158f2533

https://github.com/Expensify/App/assets/115492554/ada0ca27-39cb-44d9-a9be-a5d15c4a2810

https://github.com/Expensify/App/assets/115492554/ac77e1bf-6f5b-4b3a-ba21-881a095ea33a

https://github.com/Expensify/App/assets/115492554/c40792f8-e140-4b8e-8689-c1d8f7e7ee6e

**Expensify/Expensify Issue URL:**

**Issue reported by:** @dhanashree-sawant

**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1696091411087619

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01439bf07509667c9f</li>
        <li>Upwork Job ID: 1708866759324012544</li>
        <li>Last Price Increase: 2023-10-09</li>
<li>Automatic offers: </li>
<ul>
<li>situchan | Reviewer | 27107395</li>
<li>c3024 | Contributor | 27107397</li>
<li>dhanashree-sawant | Reporter | 27107398</li>
</ul></li>
    </ul>
</details>

**Comment by c3024** [comment] 2023-10-02 15:29
## Proposal
### Please re-state the problem that we are trying to solve in this issue.
For the last day of month after moving back to previous month, next arrow is disabled.
### What is the root cause of that problem?
`this.props.maxDate` is present day and when the present day is last day of month, the `moment(this.props.maxDate).endOf('month').startOf('day')` is last of month 00:00. Say if the date is Sep 30, this value is Sep 30 00:00
and when we move to the previous month, `this.state.currentView` is the current date of previous month. In case of Sep 30, the previous month date is Aug 30 00:00 and adding 1 month gives Sep 30 00:00
and this here
https://github.com/Expensify/App/blob/00933e121f0952b7d1c2a3d577a04d2acc208de8/src/components/NewDatePicker/CalendarPicker/index.js#L128
is false being both sides equal and next arrow is disabled.
### What changes do you think we should make in order to solve the problem?
We should change the `>` to `>=`
```js
const hasAvailableDatesNextMonth = moment(this.props.maxDate).endOf('month').startOf('day') >= moment(this.state.currentDateView).add(1, 'months');
```
### What alternative solutions did you explore? (Optional)
<details>
<summary>Result</summary>

https://github.com/Expensify/App/assets/102477862/e4502da9-3554-4bbd-846e-3c800486450f





</details>

**Comment by saranshbalyan-1234** [comment] 2023-10-02 15:33
## Proposal
### Please re-state the problem that we are trying to solve in this issue.
While going back to the previous month from last day of the month, Arrow forward button is disabled in request money date field.
### What is the root cause of that problem?
In the below code we check whether to disable Arrow forward button for next month or not.
https://github.com/Expensify/App/blob/4ebeea00ebf1470bbf085a51cb9b9ec0735cf511/src/components/NewDatePicker/CalendarPicker/index.js#L128
We have to check the end of day to include the complete month, but in the above code we are only considering the start of day, not the end
### What changes do you think we should make in order to solve the problem?
We just need to check end of day instead of start of day to get the correct conditional result.
```javascript
const hasAvailableDatesNextMonth = moment(this.props.maxDate).endOf('month').endOf('day') > moment(this.state.currentDateView).add(1, 'months');
``` 
### What alternative solutions did you explore? (Optional)
N/A

**Comment by abzokhattab** [comment] 2023-10-03 00:14
## Proposal
### Please re-state the problem that we are trying to solve in this issue.
If the user is on the last day of the month and then goes back to the previous month in the request money date field, it causes the forward button to become disabled.
### What is the root cause of that problem?
The problem stems from the date comparison logic, which doesn't handle the last day of the month scenario properly in the following line:
https://github.com/Expensify/App/blob/4ebeea00ebf1470bbf085a51cb9b9ec0735cf511/src/components/NewDatePicker/CalendarPicker/index.js#L128
### What changes do you think we should make in order to solve the problem?
To solve this problem, we should modify the calculation for `hasAvailableDatesNextMonth` to consider the start of the next month, as in our case the current date plus one month may be greater than the max date's month time.
```javascript
const hasAvailableDatesNextMonth = moment(this.props.maxDate).endOf('month').startOf('day') > moment(this.state.currentDateView).add(1, 'months').startOf('month');
```
By adding `.startOf('month')` to the comparison, we are comparing the start of the next month with the start of the user's selected month, regardless of whether the current date is the last day of the month or not.

### POC:

<video src="https://github.com/Expensify/App/assets/59809993/aa273bdd-d338-4c6b-b23d-b3e763b582d8
" controls="controls" style="max-width: 730px;">
</video>

**Comment by abzokhattab** [comment] 2023-10-03 00:16
Please notice that my proposal was the first proposal posted on Slack in this thread @situchan https://expensify.slack.com/archives/C049HHMV9SM/p1696096241828129?thread_ts=1696091411.087619&cid=C049HHMV9SM 

Thanks

**Comment by situchan** [comment] 2023-10-09 16:41
Thanks for the proposals everyone.
I think we should assign @c3024 as they first [proposed](https://github.com/Expensify/App/issues/28622#issuecomment-1743236069) correct root cause and working solution. Changes for perfect condition will be done in PR.

@abzokhattab we don't allow posting proposals in slack unless bug reporter.

🎀 👀 🎀 C+ reviewed

**Comment by cristipaval** [comment] 2023-10-25 14:35
@situchan could you please do the checklist?

**Comment by cristipaval** [comment] 2023-10-30 17:14
friendly bump @situchan

**Comment by cristipaval** [comment] 2023-11-02 14:36
> friendly bump @situchan

@situchan

**Comment by situchan** [comment] 2023-11-02 14:41
- [x] The PR that introduced the bug has been identified. Link to the PR: https://github.com/Expensify/App/pull/15343
- [x] The offending PR has been commented on, pointing out the bug it caused and why, so the author and reviewers can learn from the mistake. Link to comment: https://github.com/Expensify/App/pull/15343/files#r1380256579
- [x] A discussion in #expensify-bugs has been started about whether any other steps should be taken (e.g. updating the PR review checklist) in order to catch this type of bug sooner. Link to discussion: N/A
- [x] Determine if we should create a regression test for this bug.
- [x] If we decide to create a [regression test](https://github.com/Expensify/App/blob/main/contributingGuides/REGRESSION_TEST_BEST_PRACTICES.md) for the bug, please propose the regression test steps to ensure the same bug will not reach production again.

This is edge case and not worth adding regression test.
Do you agree? 👍 or 👎

**Comment by c3024** [comment] 2023-11-06 17:02
@anmurali 

[This is eligible for bonus](https://github.com/Expensify/App/issues/28622#issuecomment-1761915160). Could you complete the payment?

**Comment by cristipaval** [comment] 2023-11-09 16:26
@anmurali, what's the payment status of this one?

**Comment by situchan** [comment] 2023-11-10 19:47
Just to note that this is eligible for bonus. PR was C+ approved within bonus period and merged without any changes

**Comment by anmurali** [comment] 2023-11-10 19:57
Paid with bonus

**Closed by anmurali** 2023-11-10 19:57 UTC
Labels: External, Daily, Awaiting Payment, Bug
