### ISSUE TITLE
[HOLD for payment 2023-09-20] [$500] Log in -  Unable to login after Closing an account

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#25793] opened 2023-08-23 17:57 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Login to Account A.
2. Navigate to account settings and close the account.
3. After being redirected back to the login page, log in to other account - Account B.
4. Access Account B's email inbox and open the email containing the "magic sign-in link."
5. Click on the sign-in link > This action should open the app.
(we must login via attached link in the email)
6. Observer: Unable to login to account B, the app gets stuck loading

## Expected Result:
The user should be able to log in without any issue

## Actual Result:
Unable to log in after closing an account. Users have to un-install and re-install app to login again

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [x] iOS / native
- [ ] iOS / Safari
- [ ] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 1.3.56-19

**Reproducible in staging?:** Yes

**Reproducible in production?:** Yes

**If this was caught during regression testing, add the test name, ID and link from TestRail:**

**Email or phone of affected tester (no customers):**

**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/78819774/0716ff63-a4de-4060-b523-24cb7d053ebd

https://github.com/Expensify/App/assets/78819774/1f3419bb-6b4b-408e-8d5f-4c088d6865ac

**Expensify/Expensify Issue URL:**

**Issue reported by:**@tranvantoan-qn

**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1691850473918269

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~012f681206489deb34</li>
        <li>Upwork Job ID: 1695137778067378176</li>
        <li>Last Price Increase: 2023-08-25</li>
<li>Automatic offers: </li>
<ul>
<li>jjcoffee | Reviewer | 26375721</li>
<li>b4s36t4 | Contributor | 26375723</li>
</ul></li>
    </ul>
</details>

**Comment by tranvantoan-qn** [comment] 2023-08-23 18:06
Please note that the **steps 4 and 5 are key**. The issue won't happen if we login again by entering the Magic Code

**Comment by NicMendonca** [comment] 2023-08-23 18:54
>  The issue won't happen if we login again by entering the Magic Code

@tranvantoan-qn as opposed to?

**Comment by tranvantoan-qn** [comment] 2023-08-23 18:57
@NicMendonca ah, it is just a note to make sure you are not reproducing by that way

**Comment by b4s36t4** [comment] 2023-08-24 17:06
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
Log in - Unable to login after Closing an account
### What is the root cause of that problem?
The infinite login is because of this line 
https://github.com/Expensify/App/blob/aa98b6bcd1d71f47afee043673c7c18a337b8959/src/libs/Navigation/AppNavigator/AuthScreens.js#L129

Here we listen for application state weather it is inactive or active or in background, because of this line when ever we leave the application for magic code app becomes inactive, when we visit the app again via deeplink this callback will get called.

And since the we use persisted network and the way we designed it always calling the `reconnectApp` because `reconnectApp` is the first in the queue. And because we're not authenticated this request will give `407` code which causes infinite network request which made `SigninUserWithLink` command to not execute which causing the loader to be shown here.

And the reason the above `onReconnect` callback would execute is the main RCA here which involves the issue above I said.

We've added this listener in `AuthScreens` component which will only render if we're authenticated once we're logged in and signout we removed the listener here in this line https://github.com/Expensify/App/blob/01fc9285e5eeff2ac79173d799fad75f9d624d99/src/libs/actions/SignInRedirect.js#L88 which will be called when we click on signout.

But this won't happen in case of `Closing` the account, because of the listener still active because we're loggedin this listener will be active when we click on close account even though we're not part of `AuthScreens` component anymore listener is still active this causing the issue when we leave the app to call `reconnectApp` command to go on top of the queue. 

> It doesn't have to be Magic code page, after close account action once you make the app background (do 2-3 times to be effective) and this time you can't even go next step from Email page.

### What changes do you think we should make in order to solve the problem?
We can solve this two ways

1. Call `Network.clearReconnectionCallbacks` in `User.js` at `closeAccount` function

2. Call `Network.clearReconnectionCallbacks` function here https://github.com/Expensify/App/blob/aa98b6bcd1d71f47afee043673c7c18a337b8959/src/libs/Navigation/AppNavigator/AuthScreens.js#L201 in `componentWillUnmount` function


### What alternative solutions did you explore? (Optional)
NA

**Comment by b4s36t4** [comment] 2023-08-24 17:16
## Result for https://github.com/Expensify/App/issues/25793#issuecomment-1692105260
https://github.com/Expensify/App/assets/59088937/fc56f39d-7794-4335-8596-ae6874c6ebd6

> Sorry for the long video.

**Comment by b4s36t4** [comment] 2023-08-24 17:53
@NicMendonca it doesn't have to be different accounts and I don't feel this can be closed.

You can follow these below steps to re-produce this.

1. Login with any account, from secrity settings close the account.
2. From login screen don't do anything, move the app to background (do this 2-3) times.
3. Now try to login with any email.. you won't be able to move forward even for OTP screen.

Once we close the account and after re-directing to signin page again after that if we move app to the background user won't be able to login anymore. Doesn't have to be different account.

If you want I can make a clear video on how to re-produce this.

**Comment by tranvantoan-qn** [comment] 2023-08-24 23:39
@NicMendonca 
This one is critical and should not be close:

1. it happens for all accounts, not ony different one (I mention `other account ` in the step because there might be the case you was using .**expensifal**, after closing it, you wont be able to re-login with error `can not get account details`
2. Once the issue happens, there is no way to use app again, user must re-install app

**Comment by b4s36t4** [comment] 2023-08-24 23:50
Yes, I agree with @tranvantoan-qn I have witnessed it.

**Comment by aldo-expensify** [comment] 2023-08-25 00:05
hmm... I feel like it could happen in a real case if a user sign-in with an email address A (personal for example), but then decides they wanted to use B (business for example). I know that they could try to fix it by adding a secondary login and the switching primaries, but a user that doesn't know that functionality may  try to close the account and get stuck.

**Comment by aldo-expensify** [comment] 2023-08-25 00:07
It makes sense for me to fix it, but I also see it as unlikely case. I'm not sure about where we draw the line to fix or not to fix an edge case.

**Comment by b4s36t4** [comment] 2023-08-25 00:08
@aldo-expensify It doesn't have to be new email.. even with the same mail this happens.

The key point here to re-produce the bug is user should move the app to background just right after closing the account.

**Comment by tranvantoan-qn** [comment] 2023-08-25 02:02
This will completely block users from using the app again. So it must be fixed. Furthermore, as @b4s36t4 figured out in the RCA (will need to be reviewed by C+, of cource), it can be a bigger/more general issues with deep link and callback that may happen in other cases too (there were many times, our members reported that they got stuck in enter Magic Code page on Desktop browser as well )
I hope we will take a look in this issue want more time and bring it up to the team for discussion if needed. If most of the team agree to not fixing it, I will have no more concern 😀

**Comment by jjcoffee** [comment] 2023-08-28 13:15
Reproduced on Android native too!

**Comment by b4s36t4** [comment] 2023-08-28 13:33
Yes @jjcoffee when ever we move the app into background it's the issue. I have a proposal please take a look at that.

**Comment by jjcoffee** [comment] 2023-08-28 13:38
@b4s36t4's [proposal](https://github.com/Expensify/App/issues/25793#issuecomment-1692105260) seems to have the correct RCA. If you look at the logs when reproducing this, you can see that we try to `ReconnectApp` with a null value for `updateIDFrom`:

```
[info] Making API request - {"command":"SigninUserWithLink"}
[...]
[info] [NetworkConnection] Firing reconnection callbacks because app became active
[OnyxUpdates] App reconnecting with updateIDFrom: null
[info] Called API write - {"command":"ReconnectApp"}
[...]
[info] Finished API request - {"command":"SigninUserWithLink","jsonCode":200}
[info] Finished API request - {"command":"ReconnectApp","jsonCode":407}
```
Only tweak I'm thinking of is to just call `redirectToSignIn` as it performs a bunch of other cleanup calls that could be useful?

https://github.com/Expensify/App/blob/01fc9285e5eeff2ac79173d799fad75f9d624d99/src/libs/actions/SignInRedirect.js#L84-L92

Otherwise all good with @b4s36t4's [proposal](https://github.com/Expensify/App/issues/25793#issuecomment-1692105260)!

:ribbon::eyes::ribbon: C+ reviewed

**Comment by jasperhuangg** [comment] 2023-08-28 19:02
I agree with everything that @jjcoffee is saying! Seems @b4s36t4's proposal should be effective–the correct way to fix this should be to clean up any callbacks that aren't needed anymore. I also think that calling `redirectToSignIn` could be effective cleanup as well. Let's do that!

**Comment by b4s36t4** [comment] 2023-08-28 19:55
@jjcoffee @jasperhuangg Raised PR here #26119

**Comment by tranvantoan-qn** [comment] 2023-09-13 08:43
I'm waiting the offer for Reporter Role

**Comment by jjcoffee** [comment] 2023-09-18 12:42
- [x] The PR that introduced the bug has been identified. Link to the PR: **N/A** - missed case in `closeAccount`
- [x] The offending PR has been commented on, pointing out the bug it caused and why, so the author and reviewers can learn from the mistake. Link to comment: **N/A**
- [x] A discussion in #expensify-bugs has been started about whether any other steps should be taken (e.g. updating the PR review checklist) in order to catch this type of bug sooner. Link to discussion: **N/A**
- [x] Determine if we should create a regression test for this bug. **No - not impactful enough**
- [x] If we decide to create a [regression test](https://github.com/Expensify/App/blob/main/contributingGuides/REGRESSION_TEST_BEST_PRACTICES.md) for the bug, please propose the regression test steps to ensure the same bug will not reach production again. **N/A**

**Comment by NicMendonca** [comment] 2023-09-20 13:37
@tranvantoan-qn Please apply to the job: https://www.upwork.com/jobs/~012f681206489deb34

**Comment by tranvantoan-qn** [comment] 2023-09-20 13:41
Thank you! I've applied for the job

**Comment by NicMendonca** [comment] 2023-09-20 13:44
- reporter: @tranvantoan-qn = $250 
- contributor: @b4s36t4 = $1,000 
- contributor +: @jjcoffee = $1,000

**Comment by jjcoffee** [comment] 2023-09-20 13:52
@NicMendonca I think you've miscalculated the timeliness bonus? Should be $250 now :smile:

**Comment by b4s36t4** [comment] 2023-09-20 13:55
I have received in amount in my account 😄.

**Comment by NicMendonca** [comment] 2023-09-20 13:56
😬 Opps. I added a $500 (50%) bonus, forgetting this was changed to $500 (down from $1000). 

I will make note of this for next time 🙇‍♀️

**Closed by NicMendonca** 2023-09-20 13:56 UTC
Labels: External, Daily, Awaiting Payment, Bug

**Comment by NicMendonca** [comment] 2023-09-20 14:01
@b4s36t4 unfortunately no! But appreciate your honestly lol
