### ISSUE TITLE
[HOLD for payment 2024-08-29] [$125] Start chat - Add to group button has same color as background

### ISSUE THREAD

**Issue by m-natarajan** [Expensify/App#44796] opened 2024-07-04 03:04 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 9.0.4.0
**Reproducible in staging?:** y
**Reproducible in production?:** n
**If this was caught during regression testing, add the test name, ID and link from TestRail:** n/a
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** Applause internal team
**Slack conversation:**

## Action Performed:
1. Go to staging.new.expensify.com
2. Go to FAB > Start chat.
3. Search for a user.

## Expected Result:
Add to group button will have distinctive color than the background when highlighted and not hovered.

## Actual Result:
Add to group button has the same color as the background when highlighted and not hovered.

## Workaround:
Can the user still use Expensify without this being fixed? Have you informed them of the workaround?

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [x] Android: mWeb Chrome
- [x] iOS: Native
- [x] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

https://github.com/Expensify/App/assets/38435837/82f2f906-18db-4ee4-8a86-2857956b4a46

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01252a470389048ef6</li>
        <li>Upwork Job ID: 1809050228518754499</li>
        <li>Last Price Increase: 2024-07-05</li>
<li>Automatic offers: </li>
<ul>
<li>c3024 | Reviewer | 103042565</li>
</ul></li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @miljakljajic</details>

**Comment by m-natarajan** [comment] 2024-07-04 03:05
@miljakljajic FYI I haven't added the External label as I wasn't 100% sure about this issue. Please take a look and add the label if you agree it's a bug and can be handled by external contributors

**Comment by m-natarajan** [comment] 2024-07-04 03:05
We think that this bug might be related to  #vip-vsb

**Comment by Sparth19** [comment] 2024-07-04 05:12
## Proposal

### Please re-state the problem that we are trying to solve in this issue.

- Start chat --> add to group button has same color as background color when highlighted not hovered

### What is the root cause of that problem?

- The given style for the highlighted (focused) state has a different color than required.

### What changes do you think we should make in order to solve the problem?

- We need to change the background color in the highlight state (i.e isFocused )
https://github.com/Expensify/App/blob/83eb7e6ee5f8a86c4500deda3454763680dcd5cf/src/components/SelectionList/UserListItem.tsx#L54


 ```
wrapperStyle={[
               //other styles
                isFocused && [styles.sidebarLink, styles.buttonHoveredBG],
            ]}
```

- With these changes, it will show the background color as specified in ND

### Result

https://github.com/Expensify/App/assets/30714258/61b7aac6-b537-455d-a780-fec3367c9b63


### What alternative solutions did you explore? (Optional)

**Comment by c3024** [comment] 2024-07-05 05:33
Is this reproducible on `main`?

I don't see it.

https://github.com/Expensify/App/assets/102477862/a257c8a0-7eb4-4b77-9e8e-1e3aab8a0a7a

**Comment by Sparth19** [comment] 2024-07-05 05:39
@c3024 i think you are checking on hover. the issue is when highlighted and not hovered.
Thanks!

**Comment by c3024** [comment] 2024-07-05 05:40
@Sparth19 

My bad, thanks!

**Comment by c3024** [comment] 2024-07-05 06:04
#39950 broke #40992 and this was fixed with #43077 and now this PR caused the present issue.

@Santhosh-Sellavel @grgia might better take this issue over given that they have better context.

**Comment by robertjchen** [comment] 2024-07-09 07:07
Thanks, assigning for next steps 🙏

**Comment by grgia** [comment] 2024-07-15 16:13
Waiting on C+ approval

**Comment by grgia** [comment] 2024-07-24 09:41
@Santhosh-Sellavel bump

**Comment by miljakljajic** [comment] 2024-07-31 10:40
Should we reassign this to a new C+? We've been waiting on @Santhosh-Sellavel for a long time now

**Comment by miljakljajic** [comment] 2024-08-08 07:45
Assigning @dukenv0307 as the new C+

**Comment by shawnborton** [comment] 2024-08-08 11:05
I think we should take a similar approach as we do on the Search page when a row is selected:
![CleanShot 2024-08-08 at 07 03 45@2x](https://github.com/user-attachments/assets/8902e7b3-3d9f-4e76-ab3b-901790198547)

We give the button a slightly darkerBG color and we remove the hover color. Thoughts @Expensify/design?

We could find some more colors that truly never collide, but I think we're starting to split some hairs here with our product shades where we'll barely have any contrast with some of these values.

**Comment by dannymcclain** [comment] 2024-08-08 14:31
Big agree with the approach Shawn suggested.

**Comment by dubielzyk-expensify** [comment] 2024-08-09 02:05
Same

**Comment by miljakljajic** [comment] 2024-08-29 08:46
issued @dukenv0307 an offer, and pinged @dominictb for their profile

**Comment by miljakljajic** [comment] 2024-08-29 11:16
@dominictb has been paid - @dukenv0307 give me heads up when you've accepted and we'll wrap this one up.

**Comment by miljakljajic** [comment] 2024-09-03 13:11
All contributors paid - closing out

**Closed by miljakljajic** 2024-09-03 13:11 UTC
Labels: Engineering, Daily, Overdue, Awaiting Payment, Bug
