### ISSUE TITLE
[HOLD for payment 2024-01-25] IOU - Page flashes when adding or replacing receipt in details page

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#34379] opened 2024-01-11 16:22 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.24-4
**Reproducible in staging?:** Y
**Reproducible in production?:** N
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** Applause - Internal Team
**Slack conversation:**

## Action Performed:
1. Go to 1:1 DM
2. Create a manual request
3. Go to request details page
4. Add a receipt
5. Replace the receipt

## Expected Result:
When adding or replacing receipt, the thread view will not flash

## Actual Result:
When adding or replacing receipt, the thread view flashes briefly

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [x] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details> 

https://github.com/Expensify/App/assets/78819774/81e6981c-b64b-40bd-a4ee-93c142241240

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by situchan** [comment] 2024-01-11 16:28
This happens on production for me

**Comment by bernhardoj** [comment] 2024-01-11 16:33
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
Report screen flashes after replacing a receipt.

### What is the root cause of that problem?
This happens after https://github.com/Expensify/App/pull/32764. When we press replace receipt, it will go to the receipt page and pass a `backTo` param of the current report screen path.

After we select a new receipt, it will call `goBack` with the `backTo` params.
https://github.com/Expensify/App/blob/46f011f4c616fe4c177bdc22fa0c4ab3c41f4af5/src/pages/iou/request/step/IOURequestStepScan/index.js#L135-L142

Because receipt selector is the only RHP page, it will PUSH the same report screen to the stack, thus the flash.

### What changes do you think we should make in order to solve the problem?

I think we don't need the `backTo` params for edit case, so we can just dismiss it.

**Comment by situchan** [comment] 2024-01-11 16:34
I am not sure what the bug is here.
@bernhardoj can you share 2 videos? one for staging (bug), one for production (not bug)?

**Comment by situchan** [comment] 2024-01-11 16:34
cc: @tgolen

**Comment by bernhardoj** [comment] 2024-01-11 16:37
Here is on prod, the report screen doesn't flash.

https://github.com/Expensify/App/assets/50919443/c2fe762f-9de6-44db-bae6-a07d3d20475a


You can see the issue between 0:15-0:17

**Comment by situchan** [comment] 2024-01-11 16:38
Gotcha. I see 00:23-00:24 is the bug from the video.

**Comment by rlinoz** [comment] 2024-01-11 16:48
I am still not sure if I get it, but not a blocker, removing the label.

**Comment by tgolen** [comment] 2024-01-11 17:56
Skipping the `goBack()` and just calling `dismissModal()` for the edit case makes sense 👍

**Comment by rlinoz** [comment] 2024-01-11 18:04
@situchan do you agree with the proposal [here](https://github.com/Expensify/App/issues/34379#issuecomment-1887536525)?

**Comment by situchan** [comment] 2024-01-11 18:04
> @situchan do you agree with the proposal [here](https://github.com/Expensify/App/issues/34379#issuecomment-1887536525)?

yes agree

**Comment by situchan** [comment] 2024-01-11 18:32
Please assign me here too

**Comment by bernhardoj** [comment] 2024-01-12 03:09
PR is ready

cc: @situchan

**Comment by rlinoz** [comment] 2024-01-29 12:53
I forgot to add the bug label before.

@trjExpensify could you please handle the payment?

**Comment by trjExpensify** [comment] 2024-01-30 11:33
Sure thing! Confirming payments as follows: 

$500 - @situchan for C+ 
$500 - @bernhardoj for the fix

Let me know if that's correct and I'll ship the offers.

**Comment by rlinoz** [comment] 2024-01-30 14:09
That does seem correct!

**Comment by trjExpensify** [comment] 2024-01-30 15:42
@bernhardoj - paid!

**Comment by trjExpensify** [comment] 2024-01-30 15:43
@situchan - paid. Closing!

**Closed by trjExpensify** 2024-01-30 15:43 UTC
Labels: Engineering, Daily, Awaiting Payment, Bug
