### ISSUE TITLE
[$250] Android - Room - Nothing happens when tapping on the options in room creation page

### ISSUE THREAD

**Issue by IuliiaHerets** [Expensify/App#47878] opened 2024-08-22 19:08 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 9.0.24-0
**Reproducible in staging?:** Y
**Reproducible in production?:** N
**Issue reported by:** Applause Internal Team

## Action Performed:
1. Launch New Expensify app.
2. Go to FAB > Start chat > Room.
3. Tap on any option.

## Expected Result:
The app should be responsive.

## Actual Result:
Nothing happens when tapping on the options in room creation page.

## Workaround:
Unknown

## Platforms:

- [x] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [ ] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

https://github.com/user-attachments/assets/cc1530e5-a358-4096-8984-748b8f8edb15

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~0165da8222db5f4f39</li>
        <li>Upwork Job ID: 1827060577009026261</li>
        <li>Last Price Increase: 2024-08-23</li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @fedirjh</details>

**Comment by neil-marcellini** [comment] 2024-08-23 19:10
Looking now, sorry for the delay

**Comment by cristipaval** [comment] 2024-08-26 12:07
I think this is due to [this PR](https://github.com/Expensify/App/pull/47418), which introduced multiple regressions in Android Native App.

**Comment by alexpensify** [comment] 2024-08-26 15:04
## Next Steps

@puneetlath I've reassigned the `Bug` label to ensure that a BZ team member is watching over this one while I'm OOO. Since it's an `Hourly` / `Deploy Blocker`, I'm reassigning it to ensure this one doesn't go stale. Thanks!  

## Heads up, I will be offline until Tuesday, September 3, 2024, and will not actively watch over this GitHub during that period. 

If anything urgent is needed here, please ask for help in the #expensify-open-source Slack Room-- thanks!

**Comment by cristipaval** [comment] 2024-08-26 15:45
We just reverted [the offending PR](https://github.com/Expensify/App/pull/47418) and @puneetlath kicked off the CP. We'll need to retest this when `staging v. 9.0.24-2` is up.

**Comment by puneetlath** [comment] 2024-08-26 19:05
QA has confirmed this is passing now. Demoting and closing.

**Closed by puneetlath** 2024-08-26 19:05 UTC
Labels: DeployBlockerCash, External, Engineering, Hourly, Help Wanted, Bug
