### ISSUE TITLE
[HOLD for payment 2024-10-07] [$250] Track - Loading spinner appears on a Track your expenses video modal

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#48650] opened 2024-09-05 14:19 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 9.0.29-0
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**If this was caught during regression testing, add the test name, ID and link from TestRail:** N/A
**Email or phone of affected tester (no customers):** gocemate+a2069@gmail.com
**Issue reported by:** Applause - Internal Team

## Action Performed:
1. Go to FAB> Track
2. Verify that video modal appears

## Expected Result:
There should be no loading spinner over the video modal

## Actual Result:
Loading spinner appears on a Track your expenses video modal and remains to the end of the video

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [ ] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details> 

https://github.com/user-attachments/assets/2c306d07-ddb3-47d3-91d9-a6e53ed40a90

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~021832057700758749301</li>
        <li>Upwork Job ID: 1832057700758749301</li>
        <li>Last Price Increase: 2024-09-20</li>
<li>Automatic offers: </li>
<ul>
<li>HezekielT | Contributor | 104122623</li>
</ul></li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @hungvu193</details>

**Comment by lanitochka17** [comment] 2024-09-05 14:19
@bfitzexpensify  FYI I haven't added the External label as I wasn't 100% sure about this issue. Please take a look and add the label if you agree it's a bug and can be handled by external contributors

**Comment by hungvu193** [comment] 2024-09-07 14:23
@nyomanjyotisa Are you sure?
If you used nullish coalescing operator, it's only return the right-hand side operand if the left-hand side is null or undefined.
```javascript
setIsLoading(Number.isNaN(status.durationMillis) ?? status.positionMillis > 0);
```
is the same with
```javacript
setIsLoading(Number.isNaN(status.durationMillis) )
```

Beacuse `Number.isNaN` return bool.

**Comment by hungvu193** [comment] 2024-09-10 04:25
I'll take closer look today.

**Comment by hungvu193** [comment] 2024-09-12 02:58
Can't reproduce on latest main:

https://github.com/user-attachments/assets/db4b8f44-0b06-46e9-b449-7cf045c3e04c

**Comment by hungvu193** [comment] 2024-09-16 04:01
Can you retest this one @lanitochka17 ?

**Comment by hungvu193** [comment] 2024-09-20 01:36
little bump @bfitzexpensify

**Comment by hungvu193** [comment] 2024-09-24 02:14
> little bump @bfitzexpensify

Same

**Comment by bfitzexpensify** [comment] 2024-09-24 08:23
Apologies, just coming back from ooo

Have asked QA to retest

**Comment by m-natarajan** [comment] 2024-09-24 11:13
Able to reproduce


https://github.com/user-attachments/assets/c79a4d33-5533-46c7-9501-bc6b861ac074

**Comment by hungvu193** [comment] 2024-09-24 11:15
Interesting, I'll have another look today

**Comment by hungvu193** [comment] 2024-09-25 01:37
I managed to reproduce on my Pixel 4a. I'll review proposals today

**Comment by hungvu193** [comment] 2024-09-25 07:23
Thanks for the proposals, everyone.  It looks like on Android, sometimes the `isBuffering` is set incorrectly
<details><summary>Android buffering</summary>
https://github.com/user-attachments/assets/0789dff3-4a63-4d7c-8851-c0088f4b4e60
</details>

I'd go with @HezekielT 's proposal that it has the correct RCA and I agree we shouldn't show the loading indicator while it's playing.

🎀 👀 🎀  C+ reviewed.

**Comment by mvtglobally** [comment] 2024-10-05 03:08
Issue not reproducible during KI retests. (First week)

**Comment by bfitzexpensify** [comment] 2024-10-08 09:40
Payment summary:

@HezekielT to be paid $250 for contributor work - @HezekielT, can you confirm the payment via Upwork went through? They've been having some issues processing payments 
@hungvu193 to be paid $250 via manual request

**Comment by garrettmknight** [comment] 2024-10-08 18:20
$250 approved for @hungvu193

**Comment by MarioExpensify** [comment] 2024-10-15 18:08
Hey @bfitzexpensify can we close this one?

**Closed** 2024-10-15 23:17 UTC
Labels: External, Daily, Overdue, Awaiting Payment, Bug
