### ISSUE TITLE
[HOLD for payment 2024-05-02] [$250] Group chat - Removed member can be clicked on when removed offline

### ISSUE THREAD

**Issue by m-natarajan** [Expensify/App#40442] opened 2024-04-18 13:48 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.63-0
**Reproducible in staging?:** y
**Reproducible in production?:** No  newfeature
**If this was caught during regression testing, add the test name, ID and link from TestRail:** N/A
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** applause internal team
**Slack conversation:** 

## Action Performed:
1. Go to staging.new.expensify.com
2. Go to FAB > Start chat.
3. Create a group chat.
4. Click on the header > Members.
5. Go offline.
6. Remove a member.
7. Click on the removed member.

## Expected Result:
Removed member should not be accessible when removed offline.

## Actual Result:
Removed member can be clicked on when removed offline.

## Workaround:
unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [x] Android: mWeb Chrome
- [x] iOS: Native
- [x] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

https://github.com/Expensify/App/assets/38435837/0d57c6d0-07bf-4497-86d0-f1854b9f9d6b

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01d0778275dfed7122</li>
        <li>Upwork Job ID: 1782605006753902592</li>
        <li>Last Price Increase: 2024-04-23</li>
<li>Automatic offers: </li>
<ul>
<li>jjcoffee | Reviewer | 0</li>
<li>ZhenjaHorbach | Contributor | 0</li>
</ul></li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @kevinksullivan</details>

**Comment by m-natarajan** [comment] 2024-04-18 13:49
We think this bug might be related to #vip-vsb

**Comment by marcaaron** [comment] 2024-04-18 18:40
Not a blocker IMO. I'll add this to the polish pile for Group Chats. @grgia let me know if you'd like me to take this off your hands.

**Comment by grgia** [comment] 2024-04-19 08:06
@marcaaron thanks for offering, all yours!

**Comment by marcaaron** [comment] 2024-04-23 02:58
@ZhenjaHorbach I think the proposed solution makes sense so happy to roll with that. I can't imagine a situation where we'd want to give the user the ability to "cancel" the offline action. Or at least - it doesn't feel like a priority right now.

**Comment by kevinksullivan** [comment] 2024-05-03 22:24
all set on payments. @jjcoffee please complete the steps above. Thanks!

**Comment by jjcoffee** [comment] 2024-05-06 08:37
- The PR that introduced the bug has been identified. Link to the PR: https://github.com/Expensify/App/pull/39639
- The offending PR has been commented on, pointing out the bug it caused and why, so the author and reviewers can learn from the mistake. Link to comment: https://github.com/Expensify/App/pull/39639/files#r1590702410
- A discussion in #expensify-bugs has been started about whether any other steps should be taken (e.g. updating the PR review checklist) in order to catch this type of bug sooner. Link to discussion: **N/A**
- Determine if we should create a regression test for this bug. **Yes**
- If we decide to create a [regression test](https://github.com/Expensify/App/blob/main/contributingGuides/REGRESSION_TEST_BEST_PRACTICES.md) for the bug, please propose the regression test steps to ensure the same bug will not reach production again.

**Regression Test Proposal**

1. Go to FAB > Start chat
2. Create a group chat
3. Click on the chat header > Members
4. Go offline
5. Remove a member
6. Verify that removed member is not clickable

Do we agree 👍 or 👎

**Comment by marcaaron** [comment] 2024-05-09 01:41
That sounds great to me @jjcoffee

**Comment by marcaaron** [comment] 2024-05-13 19:11
Looks like we maybe just need to create the regression test here?

**Comment by marcaaron** [comment] 2024-05-15 21:30
Gonna create the issue now and close this one so it stops going overdue.

**Closed by marcaaron** 2024-05-15 21:30 UTC
Labels: External, Engineering, Daily, Overdue, Awaiting Payment, Bug
