### ISSUE TITLE
[$750] Android - Split bill - _fake_ notification is received from the same user who creates the split bill

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#29217] opened 2023-10-10 17:46 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.3.80-0
**Reproducible in staging?:** Yes
**Reproducible in production?:** Yes
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** Applause - Internal Team
**Slack conversation:**

**Issue found when executing PR** https://github.com/Expensify/App/pull/27936
## Action Performed:
1. As admin, create a workspace and invite a member
2. Log in as the same member on both Android app and another device
3. On another device (not Android), go to FAB > Request money
4. Click Split on the Workspace Chat in Step 1 and complete the split bill request

## Expected Result:
User will not receive notification for split bill request when logged in on Android app as the same user

## Actual Result:
User receives __fake__ notification for split bill request when logged in on Android app as the same user

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [ ] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos
<details>
<summary>Android: Native</summary> 

https://github.com/Expensify/App/assets/78819774/d5c33b61-7f1c-4a7b-b8f5-aca06408fb4f

</details>

<details>
<summary>Android: mWeb Chrome</summary>

</details>

<details>
<summary>iOS: Native</summary>

</details>

<details>
<summary>iOS: mWeb Safari</summary>

</details>

<details>
<summary>MacOS: Chrome / Safari</summary>

</details>

<details>
<summary>MacOS: Desktop</summary>

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01340929a43c2c3aa6</li>
        <li>Upwork Job ID: 1712908072063881216</li>
        <li>Last Price Increase: 2023-11-02</li>
    </ul>
</details>

**Comment by NicMendonca** [comment] 2023-10-13 19:08
Sorry, missed this!

**Comment by NicMendonca** [comment] 2023-10-16 14:37
waiting for proposals

**Comment by NicMendonca** [comment] 2023-10-24 13:38
@lanitochka17 - is this still reproducible?

**Comment by lanitochka17** [comment] 2023-10-26 15:51
Issue reproducible on build 1.3.91-6


https://github.com/Expensify/App/assets/78819774/edf9e1fc-3e82-4328-b605-ee76b451b3af

**Comment by NicMendonca** [comment] 2023-10-26 20:54
upped the bounty $$

**Comment by b4s36t4** [comment] 2023-10-30 14:56
Aren't the notifications are coming from backend? Maybe it's internal?

**Comment by nebiyuelias1** [comment] 2023-10-30 16:17
> Posted on Slack to get more eyes https://expensify.slack.com/archives/C01GTK53T8Q/p1698677359603939

Yes, @hoangzinh it seems this is a backend issue.

**Comment by NicMendonca** [comment] 2023-11-02 19:24
^ made this internal on purpose (cc @johnmlee101)

**Comment by mvtglobally** [comment] 2023-11-09 20:59
Issue not reproducible during KI retests. (First week)

**Comment by NicMendonca** [comment] 2023-11-13 13:55
Waiting for this weeks KI retest

**Comment by NicMendonca** [comment] 2023-11-24 14:44
@mvtglobally - bump on latest test?

**Comment by mvtglobally** [comment] 2023-12-04 12:25
We are not able to reproduce https://github.com/Expensify/App/assets/43995119/e5b82b08-8b75-48ab-a61f-07f4d75cee8b

**Comment by NicMendonca** [comment] 2023-12-04 16:55
closing!

**Closed by NicMendonca** 2023-12-04 16:55 UTC
Labels: Engineering, Daily, Internal, Overdue, Bug
