### ISSUE TITLE
[HOLD for payment 2024-12-19] [$250] Web - Search - Empty state page skeleton is cut off from the right

### ISSUE THREAD

**Issue by IuliiaHerets** [Expensify/App#53251] opened 2024-11-28 15:23 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 9.0.68-0
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**Issue was found when executing this PR:** https://github.com/Expensify/App/pull/51913
**Email or phone of affected tester (no customers):** nathanmulugetatesting+2201@gmail.com
**Issue reported by:** Applause Internal Team

## Action Performed:
1. Navigate to staging.new.expensify.com
2. Navigate to Search
3. Observe the background skeleton empty state on the right side

## Expected Result:
The oval skeleton doesn't get cut off from the right

## Actual Result:
The oval skeleton gets cut off from the right when there is a scroll bar on the right

## Workaround:
Unknown

## Platforms:

- [ ] Android: Standalone
- [ ] Android: HybridApp
- [ ] Android: mWeb Chrome
- [ ] iOS: Standalone
- [ ] iOS: HybridApp
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos
![Bug6679181_1732806399096!image](https://github.com/user-attachments/assets/e45cb9f2-0794-40fe-abd4-427b1bfd14f7)

  
</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~021865178692528155887</li>
        <li>Upwork Job ID: 1865178692528155887</li>
        <li>Last Price Increase: 2024-12-06</li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @jliexpensify</details>

**Comment by bernhardoj** [comment] 2024-11-28 16:45
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
The search page skeleton right side is cut off when there is a scrollbar.

### What is the root cause of that problem?
This is how the calculation looks to decide the position of the right-most skeleton. We want to right-aligned the skeleton.
https://github.com/Expensify/App/blob/64eaf2fdd357bd06008adfb9c0c049e09cd375b9/src/components/Skeletons/SearchRowSkeleton.tsx#L178-L180

The problem here is that when there is a scrollbar, the width of the search central pane is reduced, but since we used the `windowWidth - lhn width` to get the central pane width, the value is the same because windowWidth isn't reduced when there is a scrollbar. So, the skeleton position doesn't change either, thus getting cut off.

### What changes do you think we should make in order to solve the problem?

To solve it, first, we can get the width of the skeleton container from onLayout
https://github.com/Expensify/App/blob/64eaf2fdd357bd06008adfb9c0c049e09cd375b9/src/components/Skeletons/SearchRowSkeleton.tsx#L124

```
const [containerWidth, setContainerWidth] = useState(0);

<View style={[styles.flex1, containerStyle]} onLayout={(e) => setContainerWidth(e.nativeEvent.layout.width)}>
```

Then, use the `containerWidth` on the calculation like this:
```
x={containerWidth - rightSideElementWidth - gapWidth - centralPanePadding}
```

We need to do the same for this skeleton
https://github.com/Expensify/App/blob/64eaf2fdd357bd06008adfb9c0c049e09cd375b9/src/components/Skeletons/SearchRowSkeleton.tsx#L170-L172
```
x={containerWidth - rightButtonWidth - gapWidth - centralPanePadding - gapWidth - rightSideElementWidth}
```

### What alternative solutions did you explore? (Optional)
Since we don't show scroll indicator for scroll page,
https://github.com/Expensify/App/blob/64eaf2fdd357bd06008adfb9c0c049e09cd375b9/src/components/Search/index.tsx#L491

we can just hide it for the skeleton too by passing the `showsVerticalScrollIndicator` to `EmptyStateComponent`.

https://github.com/Expensify/App/blob/64eaf2fdd357bd06008adfb9c0c049e09cd375b9/src/pages/Search/EmptySearchView.tsx#L200-L211

and then use it here.
https://github.com/Expensify/App/blob/64eaf2fdd357bd06008adfb9c0c049e09cd375b9/src/components/EmptyStateComponent/index.tsx#L85-L88

**Comment by jliexpensify** [comment] 2024-11-28 22:43
Hi @deetergp and @Pujan92 - this is related to https://github.com/Expensify/App/pull/51913, so assigning you to review.

**Comment by jliexpensify** [comment] 2024-12-02 23:13
Waiting on @deetergp and @Pujan92 to weigh in

**Comment by deetergp** [comment] 2024-12-04 07:04
@bernhardoj's proposal sounds reasonable to me. What do you think @Pujan92?

**Comment by Pujan92** [comment] 2024-12-05 12:28
Yes @deetergp but I am not able to reproduce it in my system.

https://github.com/user-attachments/assets/259acb8a-39b2-4b0a-a7ac-d527b416f874

**Comment by bernhardoj** [comment] 2024-12-05 14:43
@Pujan92 please try to always show the scrollbar 
<img width="707" alt="image" src="https://github.com/user-attachments/assets/feaa1a26-6890-4186-96da-0f756ffbf8f6">

**Comment by Pujan92** [comment] 2024-12-06 11:57
I am 👍 with the @bernhardoj's alternative solution of passing `showsVerticalScrollIndicator` prop to the ScrollView.

🎀👀🎀 C+ reviewed

**Comment by deetergp** [comment] 2024-12-06 23:37
Please disregard @shawnborton — I accidentally clicked the wrong tag `:ohnothing:`

**Comment by bernhardoj** [comment] 2024-12-07 09:27
PR is ready
cc: @Pujan92

**Comment by shawnborton** [comment] 2024-12-09 13:15
Is this some kind of regression or was it always set up this way? cc @filip-solecki

**Comment by filip-solecki** [comment] 2024-12-09 13:27
Tbh it's hard to say, maybe there were some changes that broke up the calculations or it is uncovered scenario.

**Comment by jliexpensify** [comment] 2024-12-12 02:22
@kadiealexander the payment date for this falls for when I am OOO, but before I go, I'll prep the summary - can you pay it please?

**Comment by jliexpensify** [comment] 2024-12-16 03:04
Payment Summary

- C: @bernhardoj $250 (to be paid via ND)

@deetergp @Pujan92 this is the only payment, correct?

**Comment by Pujan92** [comment] 2024-12-16 03:08
@jliexpensify this isn't a regression of the [mentioned](https://github.com/Expensify/App/issues/53251#issuecomment-2506828606) PR, and it is a new fresh issue. So I am also eligible for the payment.

**Comment by jliexpensify** [comment] 2024-12-16 03:25
Cool, thanks for letting me know - will add you in.

**Comment by jliexpensify** [comment] 2024-12-17 04:20
Hi @deetergp - I'm headed OOO from the 18th - 29th, do you mind closing this GH when the payment date passes?

[Payment Summary is here.](https://github.com/Expensify/App/issues/53251#issuecomment-2544443842) 

@Pujan92 - is there a need for a checklist?

**Comment by deetergp** [comment] 2024-12-17 16:41
> Hi @deetergp - I'm headed OOO from the 18th - 29th, do you mind closing this GH when the payment date passes?

Will do @jliexpensify! Enjoy our OOO time 🎉

**Comment by jliexpensify** [comment] 2024-12-17 20:02
Thanks Scott, have a great Holiday Break!

@Pujan92 since it's my last day today, I want to confirm that there's no checklist?

**Comment by Pujan92** [comment] 2024-12-18 08:41
@jliexpensify I think checklist isn't needed here.

**Comment by jliexpensify** [comment] 2024-12-18 09:02
Great, thanks - in that case, Scott can simply close this on the 19th if there are no regressions.

**Closed** 2024-12-20 00:50 UTC
Labels: External, Daily, Awaiting Payment, Bug

**Comment by garrettmknight** [comment] 2024-12-21 14:01
$250 approved for @Pujan92

**Comment by bernhardoj** [comment] 2024-12-22 10:27
Requested in ND.

**Comment by JmillsExpensify** [comment] 2024-12-23 12:17
$250 approved for @bernhardoj based on [this summary](https://github.com/Expensify/App/issues/53251#issuecomment-2544443842).
