### ISSUE TITLE
Web - Search - Dropdown and Filters button have no spacing between each other

### ISSUE THREAD

**Issue by IuliiaHerets** [Expensify/App#48069] opened 2024-08-27 10:32 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___
 
**Version Number:** v9.0.25-0
**Reproducible in staging?:** Y
**Reproducible in production?:** N
**Email or phone of affected tester (no customers):** applausetester+kh050806@applause.expensifail.com
**Issue reported by:** Applause Internal Team

## Action Performed:
1. Go to staging.new.expensify.com
2. Go to Search.
3. Select expense via checkbox.

## Expected Result:
Dropdown and Filters button will have some spacing between each other.

## Actual Result:
Dropdown and Filters button have no spacing between each other

## Workaround:
Unknown

## Platforms:

- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

https://github.com/user-attachments/assets/6f8e8965-add7-46cf-9762-a4013f06c10a

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by IuliiaHerets** [comment] 2024-08-27 10:32
We think that this bug might be related to #wave-control

**Comment by etCoderDysto** [comment] 2024-08-27 10:35
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
Dropdown and Filters button have no spacing between each other
### What is the root cause of that problem?
We are not providing margin left for filter button component here
https://github.com/Expensify/App/blob/d5cfecfc53a2abf926a1dd9be8bc72c0b373ff81/src/components/Search/SearchPageHeader.tsx#L315-L319
### What changes do you think we should make in order to solve the problem?
We should pass a margin left to the styles prop of the button 
```
style={[styles.ml2]}
```

### What alternative solutions did you explore? (Optional)

**Comment by etCoderDysto** [comment] 2024-08-27 10:38
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
Dropdown and Filters button have no spacing between each other
### What is the root cause of that problem?
We are not providing margin left for filter button component here
https://github.com/Expensify/App/blob/d5cfecfc53a2abf926a1dd9be8bc72c0b373ff81/src/components/Search/SearchPageHeader.tsx#L315-L319
### What changes do you think we should make in order to solve the problem?
We should pass a margin left to the styles prop of the button 
```javascript
style={[styles.ml2]}
```

### What alternative solutions did you explore? (Optional)

We can add margin right to the dropdown button 
```
style={ {styles.ml2, styles.mr2} 
```
https://github.com/Expensify/App/blob/d5cfecfc53a2abf926a1dd9be8bc72c0b373ff81/src/components/Search/SearchPageHeader.tsx#L304-L312

**Comment by Kicu** [comment] 2024-08-27 10:38
@etCoderDysto could you try to use gap (`styles.gap4`) on a parent component of buttons instead of left margin on a button?

I think it would be a bit cleaner

**Comment by etCoderDysto** [comment] 2024-08-27 10:39
> @etCoderDysto could you try to use gap (`styles.gap4`) on a parent component of buttons instead of left margin on a button?
> 
> I think it would be a bit cleaner

Checking @Kicu

**Comment by etCoderDysto** [comment] 2024-08-27 10:51
We can also do that as @Nodebrute suggested in his [proposal](https://github.com/Expensify/App/issues/48069#issuecomment-2312168821), and we should also remove margin left from the dropdown button

**Comment by etCoderDysto** [comment] 2024-08-27 11:20
[Proposal updated](https://github.com/Expensify/App/issues/48069#issuecomment-2312167860)

@Kicu I have updated my alternative solution according to your suggestion

**Comment by Kicu** [comment] 2024-08-27 11:41
Thanks for the updates.
I think the solution of removing margin from button and using `gapX` in a parent component is a good solution 👍 

However I work as a consultant and I'm not a Contributor+ so I cannot officially assign you to this task. Calling @lakchote could you take a look at this?

**Comment by 289Adam289** [comment] 2024-08-27 12:09
Hey! fixed this in a pr I am working on

**Comment by lakchote** [comment] 2024-08-27 14:16
> Calling @lakchote could you take a look at this?

@289Adam289 has a PR under review that fixes it that is already approved, using the `gap` property to properly space, same as the approach you were envisioning @Kicu.

Thanks for having taken the time to review the proposal even if you're not a C+.

Sorry @etCoderDysto but since the other PR is already approved, and a C+ is currently going through the reviewer checklist, I'm assigning @289Adam289 to the issue.

**Comment by etCoderDysto** [comment] 2024-08-27 14:27
No worries @lakchote 👍

**Comment by luacmartins** [comment] 2024-08-27 18:32
This is fixed in staging after the CP. Closing.

**Closed by luacmartins** 2024-08-27 18:32 UTC
Labels: Reviewing, Engineering, Weekly, Bug
