### ISSUE TITLE
[$250] #admins and  workspace  channels show as archived / unavailable upon reopening an account

### ISSUE THREAD

**Issue by m-natarajan** [Expensify/App#47371] opened 2024-08-14 01:39 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 9.0.20-0
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** @maddylewis 
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1723565037289829

## Action Performed:

1. Head to [Expensify.com](http://expensify.com/)
2. Click Contact Sales
3. Enter email address (public domain)
4. Click Next
5. Taken to NewDot
6. Click “Switch to Exfy Classic”
7. Close account in Exfy Classic
8. Head to [new.expensify.com](http://new.expensify.com/)
9. Enter email address (public domain)
10. Enter magic code
11. Log in to NewDot

## Expected Result:
If an account is reopened the workspace  and #admin channels should show as active (not archived) and the workspace tied to the first account shouldn't be visible at all or it should be shown as available
## Actual Result:
I see an unavailable, archived workspace and the announce/admin rooms are unavailable
## Workaround:
unknown
## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos
![image (6)](https://github.com/user-attachments/assets/c043326c-8ac5-455f-879b-9c8928a48ebd)
![image (5)](https://github.com/user-attachments/assets/206ee400-68b1-49fc-9b09-6565dbffdfce)
![image (4)](https://github.com/user-attachments/assets/74b8270c-5cb4-464f-92d6-4866a4616855)
![image (3)](https://github.com/user-attachments/assets/b4174866-732c-47b2-b9b4-c7d8881bce4d)

https://github.com/user-attachments/assets/b1d390a8-ca6b-4f23-ae84-08992016695d

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01813d8e9f760615ea</li>
        <li>Upwork Job ID: 1824061981613128117</li>
        <li>Last Price Increase: 2024-08-29</li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @aimane-chnaif</details>

**Comment by klajdipaja** [comment] 2024-08-23 10:41
The root cause of the issue is `private_isArchived` property of the report which the backend returns as true for all preexisting chat rooms. We can modify this logic  on the frontend to "Room is archived if private_isArchived is before account creation date" but then we will receive an error from the backend when we use the chat and I think the whole concept should be fixed in the backend properly.

Screenshot attached for the error in case we send a message to archived chat:
![image](https://github.com/user-attachments/assets/4d87618d-7988-44ff-9b65-b46a6de34c7e)

**Comment by klajdipaja** [comment] 2024-08-27 13:33
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
After an account is deleted previously created workspaces and reports show as archived when the should be hidden from the view.
### What is the root cause of that problem?
At the moment we are not considering the fact that archived reports can come from an account that is previously closed and reopened. 
### What changes do you think we should make in order to solve the problem?
In the front end we can solve this by filtering the existing report that have the archived flag and latest action is Closed with reasons Policy Deleted or Account Closed.


We need to replace the following query of Onyx reports:
https://github.com/Expensify/App/blob/492b884ffb0950e703147e31d5898acc25fff6ef/src/hooks/useReportIDs.tsx#L83

By using a selector in useOnyx we can filter out the reports that come from a deleted account using the following changes 

``` javascript
    const reportSelector = (report: OnyxEntry<Report>): OnyxEntry<Report> => {
        const isArchivedReport = report && !report?.private_isArchived;
        if (isArchivedReport) {
            return report;
        }

        const currentReportActions = allReportActions ? allReportActions[`${ONYXKEYS.COLLECTION.REPORT_ACTIONS}${report.reportID}`] ?? {} : {};

        if (!currentReportActions) {
            return report;
        }

        const sortedReportActions = ReportActionsUtils.getSortedReportActions(currentReportActions, true);
        const lastReportAction = sortedReportActions[0];

        const lastOriginalReportAction = lastReportAction ?? null;
        const archiveReason =
            // eslint-disable-next-line @typescript-eslint/prefer-nullish-coalescing
            (ReportActionsUtils.isClosedAction(lastOriginalReportAction) && ReportActionsUtils.getOriginalMessage(lastOriginalReportAction)?.reason) || CONST.REPORT.ARCHIVE_REASON.DEFAULT;

        if (archiveReason !== CONST.REPORT.ARCHIVE_REASON.POLICY_DELETED || archiveReason !== CONST.REPORT.ARCHIVE_REASON.ACCOUNT_CLOSED) {
            return report;
        }
    };

    const [chatReports] = useOnyx(ONYXKEYS.COLLECTION.REPORT, {selector: reportSelector});

```
The part of the code to get the latest action for a report can be refactored to a central function because there are other places with the same logic.

### What alternative solutions did you explore? (Optional)

**Comment by johnmlee101** [comment] 2024-08-29 20:33
What is the reason we expect the workspace to be reopened?

**Comment by johnmlee101** [comment] 2024-08-29 20:33
I also agree this is a backend change

**Comment by trjExpensify** [comment] 2024-09-02 23:28
>What is the reason we expect the workspace to be reopened?

+1 to John's question. The OP isn't clear what scenario we're talking about for archived rooms and the workspace chat. For example, this screenshot is showing an `archivedReason` of workspace deleted. Closing/opening an account isn't going to bring that workspace back. 

![Image](https://github.com/user-attachments/assets/4c2dd342-5895-4b09-ab5e-7fa578237911)

**Comment by bfitzexpensify** [comment] 2024-09-03 13:07
>For example, this screenshot is showing an archivedReason of workspace deleted. Closing/opening an account isn't going to bring that workspace back.

Hm, that's a good point. If I've intentionally closed an account, I wouldn't find it unexpected to not see the old workspace active. Even though the `archivedReason` doesn't explicitly say why it's no longer active, I don't know that it's particularly confusing given what the user has done. 

@maddylewis is your expectation that we should reopen all workspaces when reopening an account, or that we should be clearer in explaining why it's no longer active, or something else?

**Comment by maddylewis** [comment] 2024-09-03 13:38
@bfitzexpensify - yeah, i think having the rooms showing but archived without a clear reason why was confusing. 

so maybe something that explains how to access those channels upon reopening an account would suffice. 
> To regain access to admin and announce rooms, create a new workspace! 

or, permanently delete them upon closing an account. so once the account is reopened, the archived channels don't clutter up the LHN 
<img width="785" alt="image" src="https://github.com/user-attachments/assets/f754c9b0-12fd-41c9-a7bc-9648d8759d2c">

**Comment by trjExpensify** [comment] 2024-09-03 16:03
You can't bring a workspace back after being deleted (in product, yes, maybe possible with eng from a backup), so we don't unarchive those rooms on the workspace. The #announce and #admins rooms remain shared but archived with the workspace owner though for historical reference. The workspace chat is retained by the submitter it belongs to as well, as a historical reference to their financial activity on the workspace - it should retain the chat title though and not **Unavailable workspace** if that's what you're seeing.

>or, permanently delete them upon closing an account. so once the account is reopened, the archived channels don't clutter up the LHN

As for this, it has been somewhat discussed previously (bit of a proposal [here](https://expensify.slack.com/archives/C066HJM2CAZ/p1705892706866269)), but it didn't go anywhere to being prioritised. It'll be quite a bit of work to change this flow, certainly wouldn't all be `External` either.

**Comment by bfitzexpensify** [comment] 2024-09-04 15:01
I tend to agree.  Reading that post @trjExpensify linked to in Slack, I don't think the work required to change this behaviour is warranted, and that a) most end-users would be able to understand why something was no longer available given they closed/re-opened account and b) even if they didn't, that's an easy thing for support to explain to them

**Closed by bfitzexpensify** 2024-09-04 15:01 UTC
Labels: External, Daily, Help Wanted, Bug
