### ISSUE TITLE
[HOLD for payment 2023-07-06] [$1000] Login - Page freezes when navigating to secondary login verification link

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#21258] opened 2023-06-21 19:57 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Log in to staging.new.expensify.com
2. Log in to staging.expensify.com with the same account as Step 1
3. Add a secondary login via Settings > Account details > Secondary logins
4. Go to verification email and copy the link
5. Change the URL to staging.new.expensify.com/.....
6. Navigate to the link

## Expected Result:
Page does not freeze

## Actual Result:
Page is freezing

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [x] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 1.3.30.0
 
**Reproducible in staging?:** Yes

**Reproducible in production?:** Yes

**If this was caught during regression testing, add the test name, ID and link from TestRail:**

**Email or phone of affected tester (no customers):**

**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/78819774/6b5835f6-4040-4234-b712-1b884ad91274

**Expensify/Expensify Issue URL:**

**Issue reported by:** Applause - Internal Team

**Slack conversation:**

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~017f461734f63ec998</li>
        <li>Upwork Job ID: 1672271611349622784</li>
        <li>Last Price Increase: 2023-06-23</li>
    </ul>
</details>

**Comment by johncschuster** [comment] 2023-06-22 13:43
@lanitochka17 is this test meant to be part of the `Add Secondary Login` flow? I don't see a flow in new.expensify.com to add a Secondary Login, so I'm wondering why this was tested in this way.

**Comment by lanitochka17** [comment] 2023-06-22 15:06
@johncschuster According to the steps with Test Rail https://expensify.testrail.io/index.php?/tests/view/3501015

**Comment by ddrzaic** [comment] 2023-06-23 22:49
### Proposal
ThreePaneView.js file, line 72
` return (
                    <View
                        key={route.key}
                        style={[styles.pAbsolute, styles.t0, styles.l0, styles.w100, styles.h100]}
                    >
                        {props.descriptors[route.key].render()}
                    </View>
                );`

this returns a div which overlays the whole page, and that looks like the page is frozen, but in fact, there is a div which is above the page, and if you delete that div, the page is responsive.

###  Solution

Add ValidateLogin screen to SCREENS constant, and add that case into ThreePaneView.js

**Comment by ddrzaic** [comment] 2023-06-23 22:54
Contributor details
Your Expensify account email: dino.drzaic.zg.14@gmail.com
Upwork Profile Link: https://www.upwork.com/freelancers/~01fd9f4fb7e646df10

**Comment by s77rt** [comment] 2023-06-24 13:00
@ddrzaic Thanks for the proposal. I don't think your RCA is correct/complete. I think this issue is more about `ValidateLoginPage`.

I see you are new here, so welcome! :tada: I recommand that you read our [contributing guide](https://github.com/Expensify/App/blob/main/contributingGuides/CONTRIBUTING.md) and to follow the proposal template. 

_BTW The expected behaviour here is not clear (asking for clarification in next comment)._

**Comment by s77rt** [comment] 2023-06-24 13:06
@johncschuster This issue can be easily reproducible if you just navigate to a link in this format: http://localhost:8080/v/123/123. This will render `<ValidateLoginPage />`but apparently it returns nothing if you are already signed in. It usually returns the magic code (see screenshot below). Can we get a clarification on the expected behaviour when navigating to this page while logged in?

![Screenshot from 2023-06-24 14-02-55](https://github.com/Expensify/App/assets/16493223/eb5c9655-82c8-4912-9a55-8680729265cf)

**Comment by s77rt** [comment] 2023-06-25 21:56
@hoangzinh Thanks for the proposal. Your RCA makes sense but I'm not sure about the solution (in terms of the final outcome). I think it's better to align on a clearer expected results first. https://github.com/Expensify/App/issues/21258#issuecomment-1605471863

**Comment by s77rt** [comment] 2023-06-26 14:07
I have asked on Slack https://expensify.slack.com/archives/C01GTK53T8Q/p1687788368985859

**Comment by s77rt** [comment] 2023-06-26 14:36
As per the Slack discussion we should still show the magic code even if logged in but without the `sign in here` link (this is already handled by `<ValidateCodeModal />`).

@hoangzinh Provided the correct fix but it may re-introduce bugs that were caught on this PR https://github.com/Expensify/App/pull/19260. I have asked here https://github.com/Expensify/App/pull/19260#discussion_r1242295392 for confirmation. @hoangzinh It would be great if you investigate that as well.

**Comment by s77rt** [comment] 2023-06-26 15:23
We got a clarification. It's safe to remove the extra condition now. Let's go with @hoangzinh's [proposal](https://github.com/Expensify/App/issues/21258#issuecomment-1606109777).

:ribbon: :eyes: :ribbon: C+ reviewed

**Comment by s77rt** [comment] 2023-06-26 16:11
@HezekielT I don't think it's a dupe yet they are similar

**Comment by Li357** [comment] 2023-06-26 16:53
Proposal looks good! 🚀

**Comment by johncschuster** [comment] 2023-06-28 11:56
@s77rt / @hoangzinh I've sent invites to you both on Upwork. Please let me know when you've accepted!

**Comment by s77rt** [comment] 2023-06-28 13:45
@johncschuster Accepted!

**Comment by johncschuster** [comment] 2023-07-06 14:25
Payments have been issued! I think we're good to close this out! 💃

**Closed by johncschuster** 2023-07-06 14:25 UTC
Labels: External, Daily, Awaiting Payment, Bug
