### ISSUE TITLE
[$500]  Task - User B accesses a task link sent by User A before opening task, no access displayed

### ISSUE THREAD

**Issue by kavimuru** [Expensify/App#34414] opened 2024-01-12 09:33 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** v1.4.24-7
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** Applause internal team
**Slack conversation:**

## Action Performed:
1. Log in with User A and open User B's chat
2. Log in with User B from another browser and open User A's chat
3. From User A go to the task and complete the flow
4. Click on the created task
5. Click on "Title" and copy the URL
6. Go back to the chat send the URL and open the task again
7. Click on "Description" and copy the URL
8. Go back to the chat send the URL and open the task again.
9. Click on "Assignee" and copy the URL
10. Go back to the chat send the URL and open the task again.
11. Now go to User B's account and click on the URLs one by one

## Expected Result:
Task "Title" and "Description" model should be opened before opening task

## Actual Result:
"Hmm... it's not here" is displayed when User B accesses the task link before opening task

## Workaround:
unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [x] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

https://github.com/Expensify/App/assets/43996225/c7eef167-3082-493a-b9c0-f24a317e0d96

https://github.com/Expensify/App/assets/43996225/6967ccb1-cfc3-45ae-bf7e-31a99d697418

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01d8cb0d70429a8316</li>
        <li>Upwork Job ID: 1745740699002007552</li>
        <li>Last Price Increase: 2024-01-12</li>
<li>Automatic offers: </li>
<ul>
<li>paultsimura | Contributor | 28102014</li>
</ul></li>
    </ul>
</details>

**Comment by paultsimura** [comment] 2024-01-12 09:49
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
Without opening the Task report first, the User cannot access the Task Details pages.

### What is the root cause of that problem?
This is happening because if we don't open the Task report first, the OpenReport API call is not executed, and the Task Report is absent from Onyx.

### What changes do you think we should make in order to solve the problem?
There are 2 options:

1. Fix Pusher to send the Task Report to the User B when User A shares a task with them.
2. In the `withReportOrNotFound` wrapper, add a logic to try to fetch Report only once if it's absent in Onyx. SImilar to how we do in the `ReportScreen`:
https://github.com/Expensify/App/blob/8a559fd7d092ce6baea06b1f47a377643415c151/src/pages/home/ReportScreen.js#L262-L279

### What alternative solutions did you explore? (Optional)

**Comment by paultsimura** [comment] 2024-01-12 15:07
## Proposal
Updated proposal https://github.com/Expensify/App/issues/34414#issuecomment-1888769280 to add more code details.

**Comment by allroundexperts** [comment] 2024-01-13 21:44
@paultsimura's [proposal](https://github.com/Expensify/App/issues/34414#issuecomment-1888769280) looks good to me. Especially, since it follows the already established convention in `withReportAndReportActionOrNotFound` hoc.

🎀 👀 🎀 C+ reviewed

**Comment by paultsimura** [comment] 2024-01-16 19:18
Thanks. The PR is ready for review: https://github.com/Expensify/App/pull/34599

**Comment by NicMendonca** [comment] 2024-01-31 16:39
Going on leave so re-assigning to issue payment when ready!

**Comment by paultsimura** [comment] 2024-02-15 09:16
Deployed to prod: https://github.com/Expensify/App/pull/36014#issuecomment-1945393108

**Comment by allroundexperts** [comment] 2024-02-17 00:57
## Checklist
1. I was not able to pinpoint any particular PR which caused this issue. I think we just missed to include the hook when this component was first created.
2. N/A
3. N/A
4. A regression test would be useful here. The test steps given in the OP seem clear enough to me.

**Comment by paultsimura** [comment] 2024-02-22 15:37
Hey @sakluger – the automation didn't work here, but the issue is due payment today: https://github.com/Expensify/App/issues/34414#issuecomment-1945668103

**Comment by sakluger** [comment] 2024-02-24 00:33
Summarizing payment on this issue:

Contributor: @paultsimura $500, paid via Upwork
Contributor+: @allroundexperts $500, please request on Newdot

**Closed by sakluger** 2024-02-24 00:33 UTC
Labels: Reviewing, External, Daily, Bug

**Comment by JmillsExpensify** [comment] 2024-03-02 03:15
$500 approved for @allroundexperts based on summary above.
