### ISSUE TITLE
[HOLD for payment 2023-11-17] Desktop - App redirection - Logged in with different accounts App crashed

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#31027] opened 2023-11-07 20:19 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.3.96-4
**Reproducible in staging?:** Y
**Reproducible in production?:** N
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** Applause - Internal Team
**Slack conversation:**

## Action Performed:
1. Login with account A in the desktop app
2. Login with account B in the web app
3. Navigate to the user profile page in the web app
4. Refresh the browser
5. A prompt should appear asking to 'Open the link in New Expensify'
6. Click on it and wait for the desktop app to open

## Expected Result:
Verify the user profile page for account B is displayed in the desktop app

## Actual Result:
Logged in with different accounts App crashed
Issue reproduced when try to sign in with Apple Id/ Chrome

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details> 

https://github.com/Expensify/App/assets/78819774/83ea862d-c64c-40a7-9d2e-9403cc5b9901

https://github.com/Expensify/App/assets/78819774/06a3a9a5-1c98-4673-94ae-089446560fb1

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Issue Owner</summary>Current Issue Owner: @aimane-chnaif</details>

**Comment by pecanoro** [comment] 2023-11-07 21:26
Managed to reproduce:

![image](https://github.com/Expensify/App/assets/6474442/de8036bf-8880-41a6-a603-c31a0ce2ec7c)

**Comment by pecanoro** [comment] 2023-11-07 21:48
Double checking in the [PR](https://github.com/Expensify/App/pull/30502) to see if that's the cause.

**Comment by pecanoro** [comment] 2023-11-08 01:29
Posted [here](https://expensify.slack.com/archives/C07J32337/p1699406737575319), if I don't get a reply from Margelo tomorrow morning I will probably revert the PR.

**Comment by hannojg** [comment] 2023-11-08 07:16
Hey, I am checking! Could you explain why do you think it caused the regression?

**Comment by hannojg** [comment] 2023-11-08 07:26
I believe its more likely a regression from this PR:

- https://github.com/Expensify/App/pull/24482#issuecomment-1798440156

**Comment by hannojg** [comment] 2023-11-08 07:51
Hey, the offending PR is this one:

https://github.com/Expensify/App/pull/28927

It introduced this line without adding proper null checking

https://github.com/Expensify/App/blob/24184e4a987aba011b5231680da66dcef11f6a24/src/pages/home/report/ReportActionCompose/Suggestions.js#L49

Reverting this PR (this change) fixes the crash

**Comment by shubham1206agra** [comment] 2023-11-08 07:54
> Hey, the offending PR is this one:
> 
> #28927
> 
> It introduced this line without adding proper null checking
> 
> https://github.com/Expensify/App/blob/24184e4a987aba011b5231680da66dcef11f6a24/src/pages/home/report/ReportActionCompose/Suggestions.js#L49
> 
> Reverting this PR (this change) fixes the crash

But this PR is in production.

**Comment by pecanoro** [comment] 2023-11-08 20:27
Tested, it's working well now!

**Comment by pecanoro** [comment] 2023-11-20 18:02
@bfitzexpensify Time to pay this one 😄

**Comment by bfitzexpensify** [comment] 2023-11-20 19:45
Missed it as a Weekly, sorry all! 

Payment summary: 

**Contributor:** @allroundexperts to be paid $500 via manual request
**C+:** @aimane-chnaif to be paid $500 via Upwork - offer sent

**Comment by bfitzexpensify** [comment] 2023-11-20 21:29
Upwork payment complete, @aimane-chnaif please complete the BZ checklist when you get a chance - thanks!

**Comment by bfitzexpensify** [comment] 2023-11-20 21:33
Great, thanks! Let's close this out.

**Closed by bfitzexpensify** 2023-11-20 21:33 UTC
Labels: Engineering, Daily, Awaiting Payment, Bug

**Comment by JmillsExpensify** [comment] 2023-11-22 18:49
$500 payment approved for @allroundexperts based on [this comment](https://github.com/Expensify/App/issues/31027#issuecomment-1819693036).
