### ISSUE TITLE
[$250] QBO-If "Export company card expenses as" is set to "Vendor bill", Locations toggle is locked

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#50112] opened 2024-10-02 20:21 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 9.0.43-1
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**If this was caught during regression testing, add the test name, ID and link from TestRail:** https://expensify.testrail.io/index.php?/tests/view/5027294
**Issue reported by:** Applause - Internal Team

## Action Performed:
1. Launch app
2. Go to workspace settings
3. Connect QBO
4. Tap export
4. Set export company card expense to "vendor bills"
5. Set export out of pocket expense to "journal entry"
6. Navite to import
7. Tap locations -- import

## Expected Result:
If "Export company card expenses as" is set to "Vendor bill", the Locations toggle must not be locked

## Actual Result:
If "Export company card expenses as" is set to "Vendor bill", the Locations toggle is locked

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [ ] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details> 

https://github.com/user-attachments/assets/66d9415a-b335-434d-aa29-c0c683ce039e

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~021843661642289072627</li>
        <li>Upwork Job ID: 1843661642289072627</li>
        <li>Last Price Increase: 2024-10-15</li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @shubham1206agra</details>

**Comment by lanitochka17** [comment] 2024-10-02 20:21
@sonialiap  FYI I haven't added the External label as I wasn't 100% sure about this issue. Please take a look and add the label if you agree it's a bug and can be handled by external contributors

**Comment by mkzie2** [comment] 2024-10-02 22:51
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
If "Export company card expenses as" is set to "Vendor bill", the Locations toggle is locked

### What is the root cause of that problem?
- The condition canImportLocation is incorrect:

https://github.com/Expensify/App/blob/f475642a182c37e95a9d271119d4ca6290d8da11/src/pages/workspace/accounting/qbo/import/QuickbooksLocationsPage.tsx#L25-L27

### What changes do you think we should make in order to solve the problem?
- It should be:

```
    const canImportLocation =
        qboConfig?.reimbursableExpensesExportDestination === CONST.QUICKBOOKS_REIMBURSABLE_ACCOUNT_TYPE.JOURNAL_ENTRY &&
        qboConfig?.nonReimbursableExpensesExportDestination === CONST.QUICKBOOKS_NON_REIMBURSABLE_EXPORT_ACCOUNT_TYPE.VENDOR_BILL;
```

### What alternative solutions did you explore? (Optional)

**Comment by hungvu193** [comment] 2024-10-09 10:12
This seems not an issue according to this [docs](https://docs.google.com/document/d/1LLrOYRGEb_k_Z6dttcS99zlbCNNdpD1QlXAbFJYbR7g/edit?tab=t.0#heading=h.qh8snsb5ihw5).

cc @hayata-suenaga since I think you implemented this feature (https://github.com/Expensify/App/pull/41638).

**Comment by garrettmknight** [comment] 2024-10-15 00:35
@zanyrenney might be able to help out!

**Comment by JmillsExpensify** [comment] 2024-10-15 10:07
Pretty sure that vendor bills support locations, so would love to hear from @zanyrenney on which is right.

**Comment by zanyrenney** [comment] 2024-10-15 14:01
Hi! This is working as expected and is not a bug for QBO on Collect Workspaces.

Vendor Bills only support importing `Locations` as a Report Field on QBO and seeing as we did not build report fields for Collect (we said this was a control feature) Locations on Vendor Bills should be locked.

I could have sworn someone was taking on Report Fields as a project for QBO/Xero. I saw a pre-design about it in Control.

**Comment by zanyrenney** [comment] 2024-10-15 14:02
Let me get a bit more info from the doc and have a look in Slack for that pre-design.  cc @JmillsExpensify @garrettmknight 

Hope the answer above helps @shubham1206agra @hungvu193 !

**Comment by zanyrenney** [comment] 2024-10-15 14:03
![2024-10-15_15-03-20](https://github.com/user-attachments/assets/8984189c-b2cb-4e28-9547-a27b4c8f7419)

From the Design Doc!

**Comment by zanyrenney** [comment] 2024-10-15 14:10
[Here](https://expensify.slack.com/archives/C06ML6X0W9L/p1724939325346999) is the pre-design on Report Fields support for QBO / Xero that I thought would build this added "Control" functionality atop this QBO project. 

Happy to help get this added if not though! cc @dylanexpensify

**Comment by zanyrenney** [comment] 2024-10-15 16:02
We can close this cc @sonialiap

**Closed** 2024-10-16 10:19 UTC
Labels: External, Daily, Help Wanted, Overdue, Bug
