### ISSUE TITLE
[$500] Web - Single Level Tags - System message doesn't come in the #admins chat

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#33952] opened 2024-01-04 12:56 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** v1.4.21-4
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** Applause - Internal Team
**Slack conversation:**

## Action Performed:
1. Log in to OldDot with a Expensifail account
2. If needed, create a control policy
3.Navigate to tags
4. Add a few tags
5. Click on edit budget next to a tag
6. Enable the option
7. Edit the personal budget to 50
8. Edit the workspace budget to 100
9. Edit the notification threshold to 50%
10. Create a report in the control policy
11. Add a 30$ expense with the tag that has a budget selected, mark the report as approved, create another report
12. Add some expenses with the same tag, submit the report but don't approve, create another report
13. Add some expenses with the same tag, and leave the report in open status
14. Navigate to the #admins chat
15. Verify there's a message posted related to the report and/or budget

## Expected Result:
There's a message posted related to the report and/or budget

## Actual Result:
System message doesn't come in the #admins chat

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [x] Android: mWeb Chrome
- [x] iOS: Native
- [x] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

https://github.com/Expensify/App/assets/93399543/ec928764-949c-4d80-b0c0-2b5dc585d36f

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~018727c3e01cd23aa1</li>
        <li>Upwork Job ID: 1742892749914841088</li>
        <li>Last Price Increase: 2024-01-11</li>
    </ul>
</details>

**Comment by kbecciv** [comment] 2024-01-08 18:48
@muttmuure Checking with QA team, will back to you shortly. Thank you

**Comment by kbecciv** [comment] 2024-01-08 18:56
@muttmuure Yes,  the Workspace default currency is UAH

![image (45)](https://github.com/Expensify/App/assets/93399543/156bba90-b6ee-4fda-ab2c-a8cb8b8fa363)

**Comment by muttmuure** [comment] 2024-01-12 11:44
@dangrous is this something that you would want to fix post budgets go live?

**Comment by dangrous** [comment] 2024-01-12 14:53
yeah i can take a look. Certainly feels internal not external, at least

**Comment by dangrous** [comment] 2024-01-12 19:52
I think this actually may have been fixed by a [PR](https://github.com/Expensify/Auth/pull/9600) that got deployed 2 days ago. going to re-test to make sure. If not, will continue to look into it!

**Comment by dangrous** [comment] 2024-01-12 20:13
Okay yeah I just tested this and it looks like we're good now - one clarification on the testing steps though - the notification appears in #admins after step 10; there should not be any additional notification after step 10. Does that make sense? 

Let me know if you can double check my testing @muttmuure and if you get the expected behavior too, we can close.

**Comment by muttmuure** [comment] 2024-01-15 17:36
<img width="1110" alt="image" src="https://github.com/Expensify/App/assets/46995600/104e05eb-8a73-42f8-8f8d-2f7c88f0f2d8">

**Closed by muttmuure** 2024-01-15 17:36 UTC
Labels: External, Daily, Internal, Help Wanted, Bug
