### ISSUE TITLE
[$1000] Web - Chat - Message appears in two lines after using option copy to clipboard

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#12951] opened 2022-11-23 01:39 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Go to staging.new.expensify.com
2. Log in with any account and select any chat
3. Send a message containing a word followed by a space followed by a URL.
4. Triple click the first word.
5. Verify both the word and the URL are selected.
6. Right click on your keypad and select Copy to clipboard
7. Paste into composed box and send it

## Expected Result:
Message appears in one line after using option copy to clipboard

## Actual Result:
Message appears in two lines after using option copy to clipboard

## Workaround:
Unknown

## Platform:

Where is this issue occurring?

- Web

**Version Number:** 1.2.30.0

**Reproducible in staging?:** Yes

**Reproducible in production?:** Yes

**Email or phone of affected tester (no customers):** 

**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Notes/Photos/Videos:** Any additional supporting documentation

**Expensify/Expensify Issue URL:** 

**Issue reported by:** Applause - Internal Team

**Slack conversation:** 

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

## Upwork Automation - Do Not Edit
- Upwork Job URL: https://www.upwork.com/jobs/~0112e7ce1cc51739ef
- Upwork Job ID: 1597649855752056832

**Comment by Gonals** [comment] 2022-11-23 10:18
Taking a look!

**Comment by Gonals** [comment] 2022-11-23 10:24
I can't seem to reproduce the issue, so closing for now. @kbecciv, any step I missed? 

https://user-images.githubusercontent.com/19366280/203523319-7f142248-0512-4d3a-9870-67a96bf3ab18.mp4

**Comment by kbecciv** [comment] 2022-11-24 02:15
I can reproduce it with current build 1.2.31.1, steps are updated.

https://user-images.githubusercontent.com/93399543/203679053-86002b09-44e3-4014-aea6-56fb7f1c735e.mp4

**Comment by JmillsExpensify** [comment] 2022-11-26 21:25
Hmm, yeah that's odd. I can reproduce it as well. 

https://user-images.githubusercontent.com/1127863/204109545-da4eff0c-d4ca-46a0-8fd6-1161ab25002a.mov

**Comment by Pujan92** [comment] 2022-11-28 10:37
**Proposal**

Seems the issue occurs when we do the selection of text from rendered DOM, it contains the div tags <div> which might be causing this. 1 option to resolve this, we can take out the `<div></div>` tags by replacing them with empty strings.

https://github.com/Expensify/App/blob/b4f1be977bb4d628ab4b55e4732b2158488dbc82/src/pages/home/report/ContextMenu/ContextMenuActions.js#L112

```
const finalContent = content.replaceAll('<div>', '').replaceAll('</div>', '');
Clipboard.setHtml(finalContent, parser.htmlToText(finalContent));
```

**Comment by Gonals** [comment] 2022-11-29 15:07
@JmillsExpensify, should we get a C+ in here?

**Comment by JmillsExpensify** [comment] 2022-11-29 17:52
Ah yeah, sorry about that.

**Comment by JmillsExpensify** [comment] 2022-11-29 17:53
@mananjadhav We have a proposal above for your review. Thanks!

**Comment by mananjadhav** [comment] 2022-11-29 19:21
Thanks for the proposal @Pujan92. You might be right about the issue about div but I am not convinced of the solution. If you observe the `htmlToText` function, it has `htmlToTextRules` defined `ExpensiMark.js`, where we have a `stripTags` rule, with a regex to remove all tags.

---

Still open for better proposals.

**Comment by Delgee** [comment] 2022-11-30 17:04
### Proposal

## Root cause
https://github.com/Expensify/App/blob/2881f18300a1b31a2047f1f61f2cdf93d2f7b79e/src/libs/SelectionScraper/index.js#L86
When an element is copied we remove extra attributes with the above function. And when we render a link we are rendering it wrapped with multiple `display: inline;` `div` elements.

![Screenshot 2022-12-01 at 00 50 35](https://user-images.githubusercontent.com/6459339/204858704-f765c6a3-0114-4794-a659-06be350c43ae.png)
After we strip extra attributes we will have an anchor element wrapped around with multiple empty `div` elements.
This will result in an extra line being rendered after the paste.

## Solution 1
On `replaceNodes` function we can replace `div` elements with `display: inline;` style to `span` elements so it will not render extra line.
```diff
--- a/src/libs/SelectionScraper/index.js
+++ b/src/libs/SelectionScraper/index.js
@@ -112,6 +112,11 @@ const replaceNodes = (dom) => {
         domAttribs.href = dom.attribs.href;
     }

+    if (dom.attribs && dom.attribs.style && dom.name === 'div') {
+        dom.attribs.style.indexOf('display: inline;');
+        domName = 'span';
+    }
```
## Solution 2 
We can preserve style attribute on `replaceNodes` function. I don't think this is good idea to approve every style.
## Solution 3
We can just remove `div` elements with `display: inline;`. I also think this is not so good idea to remove whole element with `replaceNodes` function.

## Working example

https://user-images.githubusercontent.com/6459339/204861267-fa72478d-7ac6-431a-816c-533d4acca96e.mov

**Comment by Pujan92** [comment] 2022-11-30 17:17
> stripTags

@mananjadhav Then to copy the text only we can use the setString function for html selection too.

https://github.com/Expensify/App/blob/2881f18300a1b31a2047f1f61f2cdf93d2f7b79e/src/pages/home/report/ContextMenu/ContextMenuActions.js#L113

`Clipboard.setString(Str.htmlDecode(parser.htmlToText(content)));`

**Comment by JmillsExpensify** [comment] 2022-12-01 05:41
Still working through proposals.

**Comment by mananjadhav** [comment] 2022-12-01 07:58
It's not about the text. I could be wrong here, but can you please confirm `setString` doesn't remove all the styling?

**Comment by Pujan92** [comment] 2022-12-01 08:43
As with the direct context menu CopyToClipboard we are generating the text only, I assume we need to do the same when the selection of text is applied for CopyToClipboard. 
Considering that I thought it is fine to use `setString` which copies the plain text without any html tags & style.

https://github.com/Expensify/App/blob/820e876d5e4a8cbffe272220c1182c8942ed93cf/src/pages/home/report/ContextMenu/ContextMenuActions.js#L110-L114

```
if (!Clipboard.canSetHtml()) {
    Clipboard.setString(parser.htmlToMarkdown(content));
} else {
    Clipboard.setString(Str.htmlDecode(parser.htmlToText(content)));
}
```

**Comment by mananjadhav** [comment] 2022-12-01 18:46
@bernhardoj's proposal looks to be in the correct direction. But quick question here, does it only happen with links and not the other formatted rich text?

**Comment by Delgee** [comment] 2022-12-01 19:26
@mananjadhav It seems wrong to fix this issue during the paste phase. The issue occurs because we lose styling when we copy. If we fix this in paste, it will only affect contents that are copied from our chat, not contents that are copied from other sites.

**Comment by mananjadhav** [comment] 2022-12-01 19:32
> proposal looks to be in the correct direction.

@Delgee Sorry should've been more clear here. I meant it is about modifying the parsing rules/config to ensure that we get the correct text. Haven't finalized if it is going to be Clipboard or Paste phase.

**Comment by bernhardoj** [comment] 2022-12-03 07:51
The issue is the `div` tag will be replaced by `[block]` which will be replaced into newline by `replaceBlockWithNewLine`. 

> @bernhardoj's proposal looks to be in the correct direction. But quick question here, does it only happen with links and not the other formatted rich text?

I tried some other styling (bold, italic) and it does not have `div` wrapped around the tag (except for other tags that need to be shown on the next line, e.g., `<pre>`), but after @Delgee mentioned about copying from another web, it's very possible any tag would have a `div` tags around them. We can easily create a new .html file with this text:

```
abcd <div style="display: inline-block;"><b>test</b></div>
```

So, it all depends on how a web html is structured. The reason why the anchor tag has around 3 `div` is because of our `AnchorRenderer` component. 2 of the divs come from `Tooltip`, and the other div comes from `PressableWithSecondaryInteraction`.

https://github.com/Expensify/App/blob/bcdb1413fab510ee97c38928aba053b37b1d46d9/src/components/AnchorForCommentsOnly/BaseAnchorForCommentsOnly.js#L36-L66

If we are okay ignoring the copying from another website case, I think removing `div` tag around anchor tag is a decent solution.

And here is the video where I tested with other tag that have custom HTML renderer.


https://user-images.githubusercontent.com/50919443/205331701-a2703fd0-93e1-4375-b86c-6e1a8b9b22d6.mp4


But if we care about copying from another web, then the only solution I could think of is to remove all `div` tag that has `display` style with one of the values from:
```
inline (and all its variants, e.g., inline-block, etc.)
contents
initial
unset
table-caption
table-row
table-row-group
table-header-group
table-footer-group
```

```
    htmlToMarkdown(htmlString) {
        ....
        generatedMarkdown = removeInlineDiv(generatedMarkdown);
        ....
    }
    removeInlineDiv(htmlString) {
        const r = /<div[^><]*style=['"][^><]*display: (?:[\w-]*inline[\w-]*|contents|initial|unset|table-(?:caption|cell|row[-\w]*|(?:header|footer)-group))[^><]*['"][^><]*>(.*)<\/div>/gi
        let html = htmlString;
        while (html.match(r)) {
            html = html.replace(r, '$1');
        }
        return html;
    }
```

This will work when we copy from another web. However, when we copy from our web, all attributes are stripped away by `replaceNodes`. We can preserve the `style` attribute for `div` tag only like this:

```
const replaceNodes = (dom) => {
...
    if (dom.attribs && dom.attribs.style && dom.name === 'div') {
        domAttribs.style = dom.attribs.style
    }
...
```
But there are still many edge cases that does not get covered here, so I don't think doing this is good. Actually, when we copy the text (abcd https://google.com) from Expensify to Slack, it will also have a new line
```
abcd
https://google.com
```

The best solution I think is to flatten all div around anchor tag into one span, but I don't have idea how to achieve that.

**Comment by JmillsExpensify** [comment] 2022-12-05 14:03
Still working through proposals.

**Comment by mananjadhav** [comment] 2022-12-05 22:31
@Gonals @JmillsExpensify Can you confirm if we're trying to resolve this for internal copy to clipboard only.

**Comment by Gonals** [comment] 2022-12-07 15:04
@mananjadhav, I'm not sure I follow your question, but the issue only occurs when copying to the clipboard through the button, right?

**Comment by Delgee** [comment] 2022-12-07 15:08
@Gonals this issue also occurs using the hotkey.

**Closed** 2022-12-07 22:03 UTC
Labels: External, Engineering, Daily, Improvement, Help Wanted, Bug
