### ISSUE TITLE
[HOLD for payment 2024-10-14] [HOLD for payment 2024-10-11] Categories - Settings RHP shows spinner briefly when it is opened

### ISSUE THREAD

**Issue by IuliiaHerets** [Expensify/App#50212] opened 2024-10-04 08:43 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 9.0.44-3 
**Reproducible in staging?:** Y
**Reproducible in production?:** N
**If this was caught during regression testing, add the test name, ID and link from TestRail:** applausetester+pso@applause.expensifail.com
**Issue reported by:** Applause Internal Team
 
## Action Performed:
1. Go to staging.new.expensify.com
2. Go to workspace settings > Categories.
3. Click Settings.

## Expected Result:
Settings RHP will open smoothly without loading (production behavior).

## Actual Result:
Settings RHP shows spinner briefly when it is opened.

## Workaround:
Unknown

## Platforms:

- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

https://github.com/user-attachments/assets/74aec7a4-901c-40ea-810f-be79fa4e8f9b

  
</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Issue Owner</summary>Current Issue Owner: @trjExpensify</details>

**Comment by IuliiaHerets** [comment] 2024-10-04 08:43
We think that this bug might be related to #wave-control

**Comment by iwiznia** [comment] 2024-10-04 10:35
Proposal looks good.

**Comment by bernhardoj** [comment] 2024-10-04 10:52
PR is ready

**Comment by isagoico** [comment] 2024-10-04 18:38
Unable to reproduce on latest build v9.0.44-10. RHP opens and displays content right away 🎉

**Comment by trjExpensify** [comment] 2024-10-04 18:52
Great! Adding @fedirjh for the review.

**Comment by bernhardoj** [comment] 2024-10-15 03:28
Requested in ND.

**Comment by trjExpensify** [comment] 2024-10-15 12:15
Confirming payment summary as follows: 

- $250 to @fedirjh for the C+ review
- $250 to @bernhardoj for the fix 

Both to be paid via ND!

**Comment by bernhardoj** [comment] 2024-10-15 12:29
Requested in ND.

**Comment by trjExpensify** [comment] 2024-10-15 12:30
As for the regression test, we have [this one](https://expensify.testrail.io/index.php?/cases/view/2990309&group_by=cases:section_id&group_id=296764&group_order=asc&display_deleted_cases=0) in TestRail. Instead of a brand new test, I think we can just add the [4th point from above](https://github.com/Expensify/App/issues/50212#issuecomment-2413343044) to that test.

**Comment by trjExpensify** [comment] 2024-10-15 12:33
^^ created an issue for that, closing!

**Closed by trjExpensify** 2024-10-15 12:33 UTC
Labels: Engineering, Daily, Awaiting Payment, Bug

**Comment by JmillsExpensify** [comment] 2024-10-21 09:08
$250 approved for @bernhardoj

**Comment by garrettmknight** [comment] 2024-10-23 10:22
$250 approved for @fedirjh
