### ISSUE TITLE
 Payments - Default tag is not given to newly selected default payment after deleting previous

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#24103] opened 2023-08-03 12:27 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Log in to expensifail account that has 2 bank accounts and Pay.me listed in payment methods
2. Delete bank account with "default" tag
3. Select 2nd bank account and select "Make default payment method"

## Expected Result:
"Default" tag is given to 2nd bank account

## Actual Result:
No default tag is given to 2nd bank account after selecting "Make default payment method"

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android / native
- [x] Android / Chrome
- [x] iOS / native
- [x] iOS / Safari
- [x] MacOS / Chrome / Safari
- [x] MacOS / Desktop

**Version Number:** 1.3.49.0

**Reproducible in staging?:** Yes

**Reproducible in production?:** Ys

**If this was caught during regression testing, add the test name, ID and link from TestRail:**

**Email or phone of affected tester (no customers):**

**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/78819774/96129efb-94c1-408f-b6ba-66811497b28f

**Expensify/Expensify Issue URL:**

**Issue reported by:** Applause - Internal Team

**Slack conversation:**

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by akinwale** [comment] 2023-08-03 13:35
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
Deleting a payment method with the default tag leaves the remaining payment methods without a default.

### What is the root cause of that problem?
Users are allowed to delete the default payment method.

### What changes do you think we should make in order to solve the problem?
Ideally, when dealing with payment methods, users should be prevented from deleting their default payment method. This behaviour can be observed on several platforms like Amazon Shopping, Google Payments, the Apple App Store among others. For Expensify, if a user has two or more payment methods, we can add code to prevent the user from deleting the default payment method, and allow deletion only after the default has been reassigned.

### What alternative solutions did you explore? (Optional)
None.

**Closed** 2023-08-07 17:09 UTC
Labels: Daily, Needs Reproduction, Overdue, Bug
