### ISSUE TITLE
[$250] Web/Desktop - Chat - Unable to go to search bar using arrow keys

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#10705] opened 2022-08-30 22:00 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Navigate to https://staging.new.expensify.com/
2. Log in with valid account
3. Сlick on the plus button on the left side of the screen
4. Choose an option "New chat" or "New group"
5. Remove cursor from "Search bar"
6. And using arrow keys

## Expected Result:
Able to go to search bar using arrow keys

## Actual Result:
Unable to go to search bar using arrow keys

## Workaround:
Unknown

## Platform:

Where is this issue occurring?

- Web
- Desktop

**Version Number:** 1.1.96.5 

**Reproducible in staging?:** Yes

**Reproducible in production?:** Yes

**Email or phone of affected tester (no customers):** any

**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Notes/Photos/Videos:** Any additional supporting documentation

https://user-images.githubusercontent.com/93399543/187551298-e912787b-7204-45c5-850f-fd62fec0b8de.mp4

**Upwork job URL:**  https://www.upwork.com/jobs/~01dc046bd601c8a48a

**Issue reported by:** Applause - Internal Team

**Slack conversation:** 

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by stephanieelliott** [comment] 2022-09-01 08:35
Hey @kbecciv, I'm unable to reproduce. Can you confirm which browsers this is happening on?

**Comment by kbecciv** [comment] 2022-09-02 18:56
@stephanieelliott Checking with QA team

**Comment by tgolen** [comment] 2022-09-05 13:23
@kbecciv did you have any luck trying to reproduce this?

**Comment by trjExpensify** [comment] 2022-09-05 13:44
I can reproduce this on Desktop `v1.1.96-3`. 

When you're on the first result and press the up arrow key it loops to the last participant in the search list. 
If you're on the last result and press the down arrow key it loops to the first participant in the search list. 

![search](https://user-images.githubusercontent.com/16232057/188463441-6986fc87-d510-4c2d-a001-cdf7c9199070.gif)

**Comment by trjExpensify** [comment] 2022-09-05 13:48
Confirmed the reproduction on Web `v1.1.96-5` as well.

**Comment by trjExpensify** [comment] 2022-09-05 13:50
Upwork job here: https://www.upwork.com/jobs/~01dc046bd601c8a48a

**Comment by mananjadhav** [comment] 2022-09-05 21:41
We have a conflicting issue. In the current issue we're saying it should go to the search bar using arrow keys, but in this issue https://github.com/Expensify/App/issues/10127, we're saying it should rotate back to the first/last item in the list?

**Comment by vladnobenladen** [comment] 2022-09-06 07:16
> We have a conflicting issue. In the current issue we're saying it should go to the search bar using arrow keys, but in this issue #10127, we're saying it should rotate back to the first/last item in the list?

I don't think this is issue.
To reproduce it, user manually needs to blur input by clicking somewhere.
By default, input is focused. And pressing arrow up/down keys doesn't affect input focused status.
While pressing arrows and middle item is highlighted, input is still focused and user is still able to type keyword.

This is how it looks after https://github.com/Expensify/App/issues/10127 is fixed by this [PR](https://github.com/Expensify/App/pull/10477)

https://user-images.githubusercontent.com/97473779/188570625-322d6eb0-d3fa-437b-a984-059ccb0967f6.mov

**Comment by mananjadhav** [comment] 2022-09-08 17:51
> We have a conflicting issue. In the current issue we're saying it should go to the search bar using arrow keys, but in this issue #10127, we're saying it should rotate back to the first/last item in the list?

@tgolen @trjExpensify  Did you get a chance to look my and @vladnobenladen's comment? 

I don't think anything needs to be done here, unless there's some other issue such as input not being able to focus.

**Comment by tgolen** [comment] 2022-09-09 08:46
Yeah, I think taking a more critical look at the behavior that is "expected" in the issue description:

> Able to go to search bar using arrow keys

I don't actually think that's something that we want. I think that's a strange UX that I wouldn't expect as a user. I expect that the tab key would get me to the next input (or shift+tab for the previous). I don't think the arrow keys should do that.

I'll go ahead and close this out, but if anyone has a strong desire to reopen it, feel free!

**Closed by tgolen** 2022-09-09 08:46 UTC
Labels: Exported, External, Engineering, Weekly, Help Wanted
