### ISSUE TITLE
[HOLD for payment 2023-01-16] [$2000] Workspace - Checkmark is not marked after Connect Bank Account modal reopened

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#13616] opened 2022-12-15 11:28 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Go to https://staging.new.expensify.com/
and login
2. Open workspace settings
3. Click Connect bank account > Connect manually
4. Input routing number, account number
5. Checkmark the "I accept the Expensify Terms of Service"
6. Close the add bank account modal
7. Navigate back to the Add bank account modal > Manual option

## Expected Result:
Checkmark should still be marked

## Actual Result:
Checkmark is not marked after Connect Bank Account modal reopened 

## Workaround:
Unknown

## Platform:

Where is this issue occurring?

- Web
- iOS
- Android
- Desktop App
- Mobile Web

**Version Number:** 1.2.39.0

**Reproducible in staging?:** Yes

**Reproducible in production?:** Yes

**Email or phone of affected tester (no customers):** 

**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Notes/Photos/Videos:** Any additional supporting documentation

https://user-images.githubusercontent.com/93399543/207848021-b0b451e9-2bb4-4718-8a7d-1a7615680ec8.mp4

**Expensify/Expensify Issue URL:** 

**Issue reported by:** Applause - Internal Team

**Slack conversation:** 

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~013d357cb12b2ba1aa</li>
        <li>Upwork Job ID: 1607888031920570368</li>
        <li>Last Price Increase: 2023-01-03</li>
    </ul>
</details>

**Comment by arielgreen** [comment] 2022-12-19 23:35
### Bug0 Triage Checklist
_Note: see [this SO](https://stackoverflow.com/c/expensify/questions/14418) for more information._
- [ ] The "bug" is actually a bug 
- [ ] The bug is not a duplicate report of an existing GH.
  - If it is, close the GH and add any novel details to the original GH instead 
- [ ] The bug is reproducible, following the reproduction steps.
  - [ ] If the GH doesn’t have steps to reliably reproduce the bug and you figure it out, then please add them.
  - [ ] If you’re unable to reproduce the bug, add the `Needs reproduction` label. 
  - [ ] Comment on the issue outlining the steps you took to try to reproduce the bug, your results and tag the issue reporter and the Applause QA member who created the issue. Ask them to clarify reproduction steps and/or to check the reproduction steps again. Close issue. 
- [ ] The GH template is filled out as fully as possible
  - The GH body and title are clear (ie. could an external contributor understand it and work on it?) 
- [ ] The GH was created by an Expensify employee or a QA tester 
- [ ] If the bug is an OldDot issue, you should decide whether it is widespread enough to justify fixing or it is better to wait for reunification. If it’s better to wait, close the GH & provide this justification 
- [ ] If there's a link to Slack, check the discussion to see if we decided not to fix it 
- [ ] Decide if the GH should be resolved by an External contributor or Internal engineer, add the appropriate label

**Comment by arielgreen** [comment] 2022-12-19 23:38
Opening discussion [here](https://expensify.slack.com/archives/C049HHMV9SM/p1671493070462859); not sure this is really a bug/worth fixing.

**Comment by arielgreen** [comment] 2022-12-27 23:55
Per GH discussion, we want to:
1. Update copy of the confirmation button to say "Continue" 
2. Save the value if the checkbox is filled in

**Comment by tienifr** [comment] 2022-12-28 00:00
# Proposal

## Problem
We don't save state of this button as draft

## Solution
In App/src/pages/ReimbursementAccount/BankAccountManualStep.js
add `shouldSaveDraft` props in `CheckboxWithLable` component like the below
```diff
                   <CheckboxWithLabel
                        style={styles.mt4}
                        inputID="acceptedTerms"
                        LabelComponent={() => (
                            <View style={[styles.flexRow, styles.alignItemsCenter]}>
                                <Text>
                                    {this.props.translate('common.iAcceptThe')}
                                </Text>
                                <TextLink
                                    href="https://use.expensify.com/terms"

                                    // to call the onPress in the TextLink before the input blur is fired and shift the link element
                                    onMouseDown={e => e.preventDefault()}
                                >
                                    {`Expensify ${this.props.translate('common.termsOfService')}`}
                                </TextLink>
                            </View>
                        )}
                        defaultValue={ReimbursementAccountUtils.getDefaultStateForField(this.props, 'acceptTerms', false)}
+                        shouldSaveDraft
                    />


```

## Result

https://user-images.githubusercontent.com/113963320/208041516-367faf26-e97a-4bdb-8c2e-237999f7c461.mp4

**Comment by wildan-m** [comment] 2022-12-28 00:09
### Proposal
### Root cause
No `shouldSaveDraft` props in checkbox and `this.props.translate('common.continue')`

### Solution
add `shouldSaveDraft` and change the copy of button to 
```diff
diff --git a/src/pages/ReimbursementAccount/BankAccountManualStep.js b/src/pages/ReimbursementAccount/BankAccountManualStep.js
index 25e767d248..1a0679b3fe 100644
--- a/src/pages/ReimbursementAccount/BankAccountManualStep.js
+++ b/src/pages/ReimbursementAccount/BankAccountManualStep.js
@@ -87,7 +87,7 @@ class BankAccountManualStep extends React.Component {
                     formID={ONYXKEYS.FORMS.REIMBURSEMENT_ACCOUNT_FORM}
                     onSubmit={this.submit}
                     validate={this.validate}
-                    submitButtonText={this.props.translate('common.saveAndContinue')}
+                    submitButtonText={this.props.translate('common.continue')}
                     style={[styles.mh5, styles.flexGrow1]}
                 >
                     <Text style={[styles.mb5]}>
@@ -136,6 +136,7 @@ class BankAccountManualStep extends React.Component {
                             </View>
                         )}
                         defaultValue={ReimbursementAccountUtils.getDefaultStateForField(this.props, 'acceptTerms', false)}
+                        shouldSaveDraft
                     />
```

**Comment by Pujan92** [comment] 2022-12-28 02:18
**Proposal**

1. Add `shouldSaveDraft` to the checkbox field for saving that data to draft.
2. Update button text to `Continue` for first 3 steps where we are saving the details in the draft.

```diff
diff --git a/src/pages/ReimbursementAccount/BankAccountManualStep.js b/src/pages/ReimbursementAccount/BankAccountManualStep.js
index 25e767d24..1a0679b3f 100644
--- a/src/pages/ReimbursementAccount/BankAccountManualStep.js
+++ b/src/pages/ReimbursementAccount/BankAccountManualStep.js
@@ -87,7 +87,7 @@ class BankAccountManualStep extends React.Component {
                     formID={ONYXKEYS.FORMS.REIMBURSEMENT_ACCOUNT_FORM}
                     onSubmit={this.submit}
                     validate={this.validate}
-                    submitButtonText={this.props.translate('common.saveAndContinue')}
+                    submitButtonText={this.props.translate('common.continue')}
                     style={[styles.mh5, styles.flexGrow1]}
                 >
                     <Text style={[styles.mb5]}>
@@ -136,6 +136,7 @@ class BankAccountManualStep extends React.Component {
                             </View>
                         )}
                         defaultValue={ReimbursementAccountUtils.getDefaultStateForField(this.props, 'acceptTerms', false)}
+                        shouldSaveDraft
                     />
                 </Form>
             </>
diff --git a/src/pages/ReimbursementAccount/CompanyStep.js b/src/pages/ReimbursementAccount/CompanyStep.js
index 6dcce7a95..dba775ae6 100644
--- a/src/pages/ReimbursementAccount/CompanyStep.js
+++ b/src/pages/ReimbursementAccount/CompanyStep.js
@@ -151,7 +151,7 @@ class CompanyStep extends React.Component {
                     formID={ONYXKEYS.FORMS.REIMBURSEMENT_ACCOUNT_FORM}
                     validate={this.validate}
                     onSubmit={this.submit}
-                    submitButtonText={this.props.translate('common.saveAndContinue')}
+                    submitButtonText={this.props.translate('common.continue')}
                     style={[styles.ph5, styles.flexGrow1]}
                 >
                     <Text>{this.props.translate('companyStep.subtitle')}</Text>
diff --git a/src/pages/ReimbursementAccount/RequestorStep.js b/src/pages/ReimbursementAccount/RequestorStep.js
index 474ed78b4..2b0850861 100644
--- a/src/pages/ReimbursementAccount/RequestorStep.js
+++ b/src/pages/ReimbursementAccount/RequestorStep.js
@@ -159,7 +159,7 @@ class RequestorStep extends React.Component {
                 ) : (
                     <Form
                         formID={ONYXKEYS.FORMS.REIMBURSEMENT_ACCOUNT_FORM}
-                        submitButtonText={this.props.translate('common.saveAndContinue')}
+                        submitButtonText={this.props.translate('common.continue')}
                         validate={this.validate}
                         onSubmit={this.submit}
                         style={[styles.mh5, styles.flexGrow1]}
```

**Comment by Pujan92** [comment] 2022-12-28 02:21
> **Proposal**
> 
> 1. Add `shouldSaveDraft` to the checkbox field for saving that data to draft.
> 2. Update button text to `Continue` for first 3 steps where we are saving the details in the draft.

<img width="380" alt="Screenshot 2022-12-28 at 7 50 13 AM" src="https://user-images.githubusercontent.com/14358475/209747127-1948e1eb-6eba-4dd7-9079-d4a90ecf0701.png">
<img width="378" alt="Screenshot 2022-12-28 at 7 50 04 AM" src="https://user-images.githubusercontent.com/14358475/209747143-b08f36ab-5ef6-4683-88e4-1192de7a616d.png">
<img width="373" alt="Screenshot 2022-12-28 at 7 49 55 AM" src="https://user-images.githubusercontent.com/14358475/209747157-cd31337b-4003-47cf-a807-b7317f7f7e90.png">

**Comment by tienifr** [comment] 2022-12-28 02:34
# Additional

As per the decided button text suggestion in https://github.com/Expensify/App/issues/13616#issuecomment-1366266465, here's the minor change:
In https://github.com/Expensify/App/blob/780dd7ead8fce7f7608cea8a743e82125fce8cd0/src/pages/ReimbursementAccount/BankAccountManualStep.js#L90
```diff
- submitButtonText={this.props.translate('common.saveAndContinue')}
+ submitButtonText={this.props.translate('common.continue')}
```

**Comment by tienifr** [comment] 2023-01-03 04:11
@sobitneupane hi, just checking if you consider your selected proposal to be `substantively different` from my first proposal [here](https://github.com/Expensify/App/issues/13616#issuecomment-1366267587)?

To me, it only adds the minor text update, which could be easily missed out since it's not mentioned in the issue description and only in the issue comments. The bug fix mentioned in the issue description is the majority of the effort, which is already addressed in my [original proposal](https://github.com/Expensify/App/issues/13616#issuecomment-1366267587).

According to the contribution guideline, a proposal should only be selected if it's `substantively different` from previous proposals so just wanna double check.

**Comment by wildan-m** [comment] 2023-01-03 05:36
@tienifr not sure, but I agree with @sobitneupane. Since the solution to this problem is straightforward, there will be not many alternative solutions, so the proposal that fulfills all requirements earliest should be selected. I think @Pujan92's proposal deserves to be selected.

Maybe there should be a clear explanation and example of `substantive difference` in the contributing guideline.

**Comment by sobitneupane** [comment] 2023-01-03 08:49
@tienifr [Here](https://github.com/Expensify/App/issues/13616#issuecomment-1366266465) two changes were requested and your proposal handled only one of them. So, I went with the first proposal which covers both the requested changes.

**Comment by Pujan92** [comment] 2023-01-03 18:00
@sobitneupane Do I need to wait to raise a PR till it gets assigned to me or approved by @francoisl?

**Comment by francoisl** [comment] 2023-01-03 22:02
Sorry for the slow review, I was partially out of the office last week. I agree with @sobitneupane - we want to encourage proposals that address the entire problem. Let's go with @Pujan92's proposal.

**Comment by Pujan92** [comment] 2023-01-04 04:21
PR is ready for review.

**Comment by arielgreen** [comment] 2023-01-13 16:41
Jan 9:
<img width="957" alt="image" src="https://user-images.githubusercontent.com/37308300/212372683-5c206b1b-d5aa-48ab-b1c6-83dda34a9548.png">

**Comment by Pujan92** [comment] 2023-01-17 16:11
did this pass the regression period?

**Comment by arielgreen** [comment] 2023-01-19 22:40
**BugZero Checklist:** The PR fixing this issue has been merged! The following checklist ([instructions](https://stackoverflow.com/c/expensify/questions/14574)) will need to be completed before the issue can be closed:
https://github.com/Expensify/App/pull/13965

- [ ] @Pujan92 / @sobitneupane  A [regression test](https://expensify.testrail.io/index.php?/dashboard) has been added or updated so that the same bug will not reach production again. Link to the GH issue for creating the test here:
- [ ] @sobitneupane / @francoisl  The PR that introduced the bug has been identified. Link to the PR: https://github.com/Expensify/App/pull/12301
- [ ] @sobitneupane / @francoisl The offending PR has been commented on, pointing out the bug it caused and why, so the author and reviewers can learn from the mistake. Link to comment: N/A - @Beamanator the author is aware and part of the discussion when this regression was caught. 
- [ ] @sobitneupane / @francoisl A discussion in #contributor-plus has been started about whether any other steps should be taken (e.g. updating the PR review checklist) in order to catch this type of bug sooner. Link to discussion:
- [ ] ~@arielgreen Payment has been made to the issue reporter (if applicable)~
- [ ] @arielgreen Payment has been made to the contributor that fixed the issue @Pujan92 
- [ ] @arielgreen  Payment has been made to the contributor+ that helped on the issue @sobitneupane

**Comment by arielgreen** [comment] 2023-01-19 22:45
Timeline: 
1/3 @Pujan92 assigned to issue
1/5 PR merged, 50% bonus applies.

$2000+50% = $3000 to @Pujan92 
$3000 to @sobitneupane 

Issuing payment now (@sobitneupane please accept offer in Upwork).

**Comment by Pujan92** [comment] 2023-01-20 01:45
Thanks, applied!

**Comment by sobitneupane** [comment] 2023-01-20 03:43
@arielgreen Thanks. 
Accepted the offer.

**Comment by arielgreen** [comment] 2023-01-20 21:17
Both payments have been issued.

**Comment by arielgreen** [comment] 2023-01-20 21:17
@Pujan92 @sobitneupane @francoisl please see and complete checklist [here](https://github.com/Expensify/App/issues/13616#issuecomment-1397705517) so we can close this issue out.

**Comment by francoisl** [comment] 2023-01-25 00:54
Updated the checklist above, closing the issue since all payments have been issued.

**Closed by francoisl** 2023-01-25 00:54 UTC
Labels: Reviewing, External, Weekly, Bug
