### ISSUE TITLE
[HOLD for payment 2024-06-28] [$250] Get rid of MISSING TRANSLATION errors once and for all

### ISSUE THREAD

**Issue by iwiznia** [Expensify/App#42539] opened 2024-05-23 16:46 UTC
Context https://expensify.slack.com/archives/C01GTK53T8Q/p1702316632335369

# Problem

We've had [lots](https://github.com/Expensify/App/issues?q=is%3Aissue+%22missing+translation%22+) (also search `in:#expensify-bugs "missing translation"` in slack) of `MISSING TRANSLATION`bugs.

These bugs should really not exist ever, they solely exist because we've added a method [translateIfPhraseKey](https://github.com/Expensify/App/blob/f5cf3fb200df2b1be41700b2204c88ba385d97c0/src/libs/Localize/index.ts#L192-L213) that really should never exist, because at every point in our code, we should know if what we have is a translation key or a text to show to the user as is.

# Solution

Remove the method.
Change all its usages to:
- Show the text directly, if the text we have is a text ready to show to the user
- Call the regular translate method if we have a translation key

cc @StevenKKC @fedirjh 

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~013d70ff8202e9ba0e</li>
        <li>Upwork Job ID: 1793684887920951296</li>
        <li>Last Price Increase: 2024-05-23</li>
<li>Automatic offers: </li>
<ul>
<li>fedirjh | Contributor | 102487870</li>
<li>nkdengineer | Contributor | 102497969</li>
</ul></li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @nkdengineer</details>

**Comment by hunxjunedo** [comment] 2024-05-23 16:57
Requesting assignment.

**Comment by abzokhattab** [comment] 2024-05-23 17:06
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
Remove MISSING TRANSLATION ERROR
### What is the root cause of that problem?
We've had of MISSING TRANSLATION bugs.

 they exist because we've added a method [translateIfPhraseKey](https://github.com/Expensify/App/blob/f5cf3fb200df2b1be41700b2204c88ba385d97c0/src/libs/Localize/index.ts#L192-L213) that really should never exist, because at every point in our code, we should know if what we have is a translation key or a text to show to the user as is.

### What changes do you think we should make in order to solve the problem?

1. the [translateIfPhraseKey](https://github.com/Expensify/App/blob/f5cf3fb200df2b1be41700b2204c88ba385d97c0/src/libs/Localize/index.ts#L192-L213)  function 
2. Call the regular translate method if we have a translation key, for this we need to define a new function inside localize util that would return true if the key exist in the translation file and false otherwise
3.  show the text as its if we dont have the key in the translation file.

**Comment by hungvu193** [comment] 2024-05-24 01:53
@iwiznia I saw you tagged @fedirjh, let me know if @fedirjh will handle this one, if yes please unassign me 😄

**Comment by iwiznia** [comment] 2024-05-24 02:01
I tagged him because IIRC he added that method so he can have context on all this, but I don't think he necessarily has to handle this one.

**Comment by iwiznia** [comment] 2024-05-24 02:05
> Call the regular [translate](https://github.com/Expensify/App/blob/e7ebebbd569989712d5aa9311fc07f2d710e1325/src/libs/Localize/index.ts#L148) method if we have a translation key, for this we need to define a new function inside localize util that would return true if the key exist in the translation file and false otherwise

I don't think this is good, its improving on what we have, but still does not resolve the main problem which is: whoever is adding a call to translate should know if what they are passing is a text or a key.

> Currently, we utilize "translateIfPhraseKey" in three places. I propose using the message directly in these three places; there's no need for translation. Then we can identify which cases require translation and update them to use the message directly. This will help maintain consistency across these common components.

This is not saying much about the solution, since those 3 places are used in line 100 different places.

**Comment by nkdengineer** [comment] 2024-05-24 05:19
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
We want to remove the `translateIfPhraseKey` method

### What is the root cause of that problem?
The reason `translateIfPhraseKey` was added is that for components like [FormHelpMessage](https://github.com/Expensify/App/blob/8375abea3a377e7416404addde255b6ac8530a9b/src/components/FormHelpMessage.tsx#L29), [DotIndicatorMessage](https://github.com/Expensify/App/blob/8375abea3a377e7416404addde255b6ac8530a9b/src/components/DotIndicatorMessage.tsx#L38) and when [adding form errors](https://github.com/Expensify/App/blob/8375abea3a377e7416404addde255b6ac8530a9b/src/libs/ErrorUtils.ts#L159), we wanted it to support both the use cases of front-end errors and back-end errors.

The idea was to have a data structure `MaybePhraseKey` for that use case.

However this is not a good pattern, as agreed to in the OP. The components should receive only **translated error**, whether it's back-end error or not will be controlled by whichever parent components/forms that use those components.

### What changes do you think we should make in order to solve the problem?

Already-translated errors will always be a pure string.

1. We need to update `DotIndicatorMessage`, `FormHelpMessage`, `addErrorMessage` so that they will only receive already-translated errors as props/params

That means for `DotIndicatorMessage`, `messages` [here](https://github.com/Expensify/App/blob/8375abea3a377e7416404addde255b6ac8530a9b/src/components/DotIndicatorMessage.tsx#L26) will be a map of string and string only

For `FormHelpMessage`, `message` [here](https://github.com/Expensify/App/blob/8375abea3a377e7416404addde255b6ac8530a9b/src/components/FormHelpMessage.tsx#L14) will strictly be a string

For `addErrorMessage`, `message` [here](https://github.com/Expensify/App/blob/8375abea3a377e7416404addde255b6ac8530a9b/src/libs/ErrorUtils.ts#L152) will strictly be a string

The `Localize.MaybePhraseKey` should no longer be used in those places.

2. Most of the places that use `DotIndicatorMessage`, `FormHelpMessage`, and 100% of the cases with `addErrorMessage`, we're dealing with client-side-only errors.

In this case, instead of constructing a `MaybePhraseKey` and delegate the responsibility of translating it to the lower level components, we should handle the translation in the parent components and just pass the results to those lower level components/methods.

For example, in [this case](https://github.com/Expensify/App/blob/8375abea3a377e7416404addde255b6ac8530a9b/src/pages/iou/request/MoneyRequestParticipantsSelector.tsx#L312), update to
```
message={translate("iou.error.splitExpenseMultipleParticipantsErrorMessage")}
```

3. There're a few places that use back-end errors/[composite client-side errors](https://github.com/Expensify/App/blob/8375abea3a377e7416404addde255b6ac8530a9b/src/pages/ChatFinderPage/index.tsx#L61) for those components, in this case, we pass those user-ready errors as is to those components. For example, in [this case](https://github.com/Expensify/App/blob/8375abea3a377e7416404addde255b6ac8530a9b/src/pages/workspace/WorkspaceInvitePage.tsx#L277) update to
```
message={policy?.alertMessage ?? ''}
```

We'll do so across the app, all cases to be updated are mostly of the above 2 categories.

### What alternative solutions did you explore? (Optional)
NA

**Comment by hungvu193** [comment] 2024-05-24 11:44
I'll review proposals this weekend.

**Comment by hungvu193** [comment] 2024-05-27 23:33
Hmm not sure what should I do in this case.
Cc @iwiznia

**Comment by iwiznia** [comment] 2024-05-27 23:46
Ah sorry, going to assign @fedirjh as C+ if you don't mind, since he has more context on this.
@fedirjh make sure to add the comment of the review so it assigns an engineer.

**Comment by puneetlath** [comment] 2024-05-29 13:57
@nkdengineer do you have an ETA for the PR on this one? I'm eager to be rid of these MISSING TRANSLATION errors once and for all.

**Comment by nkdengineer** [comment] 2024-05-29 17:26
@puneetlath This is a big refactor and it requires changes in a lot of files, so I think it will take around 3-4 days to have PR ready.

**Comment by puneetlath** [comment] 2024-05-29 17:42
Ok great. Thanks for the estimate. 😄

**Comment by nkdengineer** [comment] 2024-06-03 17:41
@fedirjh this [PR](https://github.com/Expensify/App/pull/42970) is ready for preview

**Comment by JmillsExpensify** [comment] 2024-06-05 15:16
@fedirjh The PR is ready for your re-review when you get a chance. This bug is hitting a bunch of us, so motivated to get it resolved once and for all.

**Comment by kadiealexander** [comment] 2024-07-02 09:05
Payouts due:

- [ ] Contributor: $250 @fedirjh (offer)
- [ ] Contributor+: $250 @nkdengineer (offer)

Upwork job is [here](https://www.upwork.com/jobs/~013d70ff8202e9ba0e).

**Comment by kadiealexander** [comment] 2024-07-02 09:08
@fedirjh please complete the checklist!

**Comment by JmillsExpensify** [comment] 2024-07-02 18:36
$250 approved for @fedirjh

**Comment by kadiealexander** [comment] 2024-07-04 05:43
@dukenv0307 please let me know when you've accepted the Upwork offer, thanks!

**Comment by kadiealexander** [comment] 2024-07-04 06:02
Whoops, you're totally right! Sorry, been a long day. @nkdengineer please let me know when you've accepted the Upwork offer, thanks!

**Comment by nkdengineer** [comment] 2024-07-09 08:12
> @nkdengineer please let me know when you've accepted the Upwork offer, thanks!
 
 @kadiealexander I've done that, thanks

**Comment by francoisl** [comment] 2024-07-16 00:40
@kadiealexander can you confirm all payments have been issued and we can close this please? Thanks!

**Comment by kadiealexander** [comment] 2024-07-16 00:50
Yup! All done.

**Closed by kadiealexander** 2024-07-16 00:50 UTC
Labels: External, Daily, Overdue, Awaiting Payment, Bug
