### ISSUE TITLE
[Awaiting Payment 7th March] MEDIUM: [$500] Room visibility can’t be changed after a room is created.

### ISSUE THREAD

**Issue by m-natarajan** [Expensify/App#33992] opened 2024-01-05 01:26 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** v1.4.22-0
**Reproducible in staging?:** Yes
**Reproducible in production?:** Yes
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** @puneetlath 
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1704300040652649

## Action Performed:
1.Create a room by Selecting any visibility option
2.Click room details > settings

## Expected Result:
Option to change room visibility
## Actual Result:
Room visibility can't be changed and no option

## Workaround:
Unknown
## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [x] Android: mWeb Chrome
- [x] iOS: Native
- [x] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos
![image](https://github.com/Expensify/App/assets/38435837/a9900fb6-2a80-43e3-8946-582b82754240)

https://github.com/Expensify/App/assets/38435837/17f718e2-6005-42ed-b065-1517086c61a0

Add any screenshot/video evidence

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01e677bbd00cd30d54</li>
        <li>Upwork Job ID: 1743081450320183296</li>
        <li>Last Price Increase: 2024-01-05</li>
<li>Automatic offers: </li>
<ul>
<li>tienifr | Contributor | 28103839</li>
</ul></li>
    </ul>
</details>

**Comment by unicorndev-727** [comment] 2024-01-05 01:33
## Proposal
from: @unicorndev-727
### Please re-state the problem that we are trying to solve in this issue.
Request with empty distance can be created by changing the link to participant link
### What is the root cause of that problem?
The root cause is that we didn't add visibility options here.
https://github.com/Expensify/App/blob/dc3e19bdcc95023d74cd7fdd433f6208707eaaf8/src/pages/settings/Report/ReportSettingsPage.js#L177-L190
### What changes do you think we should make in order to solve the problem?
We need to add options here like this
### What alternative solutions did you explore?
N/A

**Comment by trjExpensify** [comment] 2024-01-05 01:47
I think this is a `New Feature` as it never worked. I suspect we'll also need accommodate backend changes for this. CC: @jasperhuangg @MitchExpensify

**Comment by jasperhuangg** [comment] 2024-01-05 02:03
I'll write the backend for this and then we can look for a contributor to help out with the front end!

**Comment by trjExpensify** [comment] 2024-01-05 12:13
Nice, thanks @jasperhuangg.

**Comment by jasperhuangg** [comment] 2024-01-08 07:27
Back-end PRs have been submitted for review

**Comment by jasperhuangg** [comment] 2024-01-08 07:29
@sobitneupane FWIW I like @tienifr's proposal, they go in depth and also include the edge cases where we aren't able to modify the room visibility in their solution.

**Comment by sobitneupane** [comment] 2024-01-09 12:57
I agree with @jasperhuangg. [Proposal](https://github.com/Expensify/App/issues/33992#issuecomment-1877991770) from @tienifr has included all the facets required. 

🎀 👀 🎀 C+ reviewed

**Comment by MitchExpensify** [comment] 2024-01-09 21:34
> I think this is a New Feature as it never worked. I suspect we'll also need accommodate backend changes for this. CC: @jasperhuangg @MitchExpensify

Correct! Are we worried at all about a `workspace` room being made `public` after the fact? That seems troublesome and why we avoided this in the first place iirc

**Comment by trjExpensify** [comment] 2024-01-10 23:04
>That seems troublesome and why we avoided this in the first place iirc

Oh, why is it troublesome?

**Comment by MitchExpensify** [comment] 2024-01-10 23:14
I was worried about private content being made public but others don't seem to share that concern and prefer to solve for it if we encounter it which is fair! https://expensify.slack.com/archives/C049HHMV9SM/p1704843300213439?thread_ts=1704300040.652649&cid=C049HHMV9SM

That said, don't block anything on me here!

**Comment by trjExpensify** [comment] 2024-01-10 23:29
Ah, nice. So to summarise: 

1. You can edit the visibility of the room post creation from and to all three visibility types
2. If you change the visibility of the room to `public`, we should show the "Are you sure?" alert modal dialogue to confirm as an additional measure? 

>**Are you sure?**
>Anyone can find public rooms.

@MitchExpensify you good with the copy? 
@tienifr can you make sure to add the alert modal to your proposal, please? Thanks!

**Comment by MitchExpensify** [comment] 2024-01-10 23:33
LGTM! Thanks

**Comment by trjExpensify** [comment] 2024-01-12 00:05
Excellent, thanks!

**Comment by trjExpensify** [comment] 2024-01-16 11:10
Seems like you both agree on @tienifr's proposal, so I'm going to assign the issue out so it doesn't appear as we're still soliciting proposals here. I think we're still awaiting the backend changes to get going on this App PR though:

https://github.com/Expensify/Auth/pull/9605
https://github.com/Expensify/Web-Expensify/pull/40420

**Comment by jasperhuangg** [comment] 2024-01-17 14:56
I'm back from OOO! Going to push those back-end PRs forward today and get them ready to merge. Thank you @trjExpensify for pushing this along in my absence.

**Comment by jasperhuangg** [comment] 2024-01-19 20:54
Both linked back-end PRs have been approved, we're waiting for the Auth deploy, once that's done we can merge the Web PR too.

**Comment by jasperhuangg** [comment] 2024-01-22 21:19
Auth is deployed, I'll ping once the Web PR is on staging

**Comment by trjExpensify** [comment] 2024-02-01 11:03
Web is on production. @tienifr you can proceed!

**Comment by trjExpensify** [comment] 2024-02-05 21:04
I'll wait for @jasperhuangg to confirm on those :)

**Comment by jasperhuangg** [comment] 2024-02-09 01:29
Command name: `UpdateRoomVisibility`
Params:
- authToken (string)
- reportID (int)
- visibility (string), one of the available room visibilities

**Comment by jasperhuangg** [comment] 2024-02-09 01:29
@tienifr

**Comment by quinthar** [comment] 2024-02-09 21:59
What's the ETA for this, and who's doing it?

**Comment by sobitneupane** [comment] 2024-02-12 08:27
We are expecting PR from @tienifr. @tienifr Any update?

**Comment by trjExpensify** [comment] 2024-02-12 10:41
Yeah, @tienifr please confirm you have everything you need from @jasperhuangg [here](https://github.com/Expensify/App/issues/33992#issuecomment-1935200794) now, and when we can expect the [draft PR](https://github.com/Expensify/App/pull/35830) to be ready for review.

**Comment by sobitneupane** [comment] 2024-02-15 08:32
@jasperhuangg, @trjExpensify Should we show an alert when user selects Public visibility? I personally don't think it is necessary.


https://github.com/Expensify/App/assets/25876548/5bad561b-c034-46c1-b082-ba73508a9f1e

**Comment by trjExpensify** [comment] 2024-02-15 12:32
@sobitneupane yeah, we should. That was the [outcome of the Slack thread](https://expensify.slack.com/archives/C049HHMV9SM/p1704300040652649).

**Comment by quinthar** [comment] 2024-02-16 05:13
Yo!  What's the latest ETA for merging this PR?

**Comment by jasperhuangg** [comment] 2024-02-16 19:35
@quinthar C+ is reviewing it right now, it's a pretty simple change so I estimate it'll be merged early next week.

**Comment by sobitneupane** [comment] 2024-02-19 04:24
There are some minor issues in the PR. @tienifr Can you please prioritize the PR.

**Comment by jasperhuangg** [comment] 2024-02-20 22:51
bump @tienifr on above 🙇

**Comment by trjExpensify** [comment] 2024-02-27 12:28
PR hit staging 15 hours ago.

**Comment by trjExpensify** [comment] 2024-03-07 12:02
👋 checklist time, @sobitneupane!

**Comment by trjExpensify** [comment] 2024-03-14 19:28
Bump! :)

**Comment by trjExpensify** [comment] 2024-03-18 11:39
Waiting on the checklist from @sobitneupane to proceed with payments. :)

**Comment by sobitneupane** [comment] 2024-03-20 14:21
**Regression Test Proposal:**

- Create a room by selecting any one of the visibility options.
- Click room details > settings
- Verify that admin can change the visibility and other members can only see the visibility
- If visibility option "Public" is selected, verify that the confirmation dialog is displayed.

Do we agree 👍 or 👎

**Comment by trjExpensify** [comment] 2024-03-22 14:02
@MitchExpensify @jasperhuangg I was just looking for regression tests related to user-created rooms and things like testing all the visibility types etc. I can't seem to find much at all in [TestRail](https://expensify.testrail.io/index.php?/suites/view/7722&group_by=cases:section_id&group_order=asc&display_deleted_cases=0&group_id=296763). Why is that? With UCR's now released, I think it would be good for you guys to audit what exists for rooms in TestRail and supply Applause with the missing regression test cases for the mainline flows. Discoverability/visibility settings seem like staples we should have included.

**Comment by trjExpensify** [comment] 2024-03-22 15:19
**Payment summary as follows:** 

- $500 to @tienifr for the fix (paid via Upwork)
- $500 to @sobitneupane for the C+ review (to be paid via NewDot)

**Comment by trjExpensify** [comment] 2024-03-22 15:20
Settled up. Reached out to @MitchExpensify about https://github.com/Expensify/App/issues/33992#issuecomment-2015175096 we can progress it elsewhere.

**Closed by trjExpensify** 2024-03-22 15:20 UTC
Labels: Reviewing, External, Daily, NewFeature, Awaiting Payment

**Comment by MitchExpensify** [comment] 2024-03-25 00:09
That's a good call @trjExpensify, will tackle that audit here https://github.com/Expensify/Expensify/issues/381804

**Comment by trjExpensify** [comment] 2024-03-25 12:29
Perfect, thanks!

**Comment by JmillsExpensify** [comment] 2024-04-11 20:49
$500 approved for @sobitneupane
