### ISSUE TITLE
Android/iOS - Chat - Not here page in 1:1 DM after connecting online

### ISSUE THREAD

**Issue by IuliiaHerets** [Expensify/App#51292] opened 2024-10-22 19:47 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** v9.0.52-2
**Reproducible in staging?:** Y
**Reproducible in production?:** N
**If this was caught on HybridApp, is this reproducible on New Expensify Standalone?:** Y
**Email or phone of affected tester (no customers):** applausetester+ck1022@applause.expensifail.com
**Issue reported by:** Applause Internal Team

## Action Performed:
1. Launch NewDot or Hybrid app
2. Tap on FAB >> Start chat option
3. Disable internet connection
4. Scroll down & select any 1:1 chat
5. Enable internet connection

## Expected Result:
1:1 DM page should load after connecting online

## Actual Result:
Not here page in 1:1 DM after connecting online

## Workaround:
Unknown

## Platforms:

- [x] Android: Standalone
- [x] Android: HybridApp
- [ ] Android: mWeb Chrome
- [ ] iOS: Standalone
- [x] iOS: HybridApp
- [x] iOS: mWeb Safari
- [ ] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos
  
https://github.com/user-attachments/assets/92efde8c-726c-4b1c-9175-abecd7c28e6f

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by yuwenmemon** [comment] 2024-10-23 06:41
Not able to reproduce on the latest version (v9.0.52-5) I think this was fixed by one of our CPs (my guess is https://github.com/Expensify/App/pull/51283)

**Closed by yuwenmemon** 2024-10-23 06:41 UTC
Labels: DeployBlockerCash, Engineering, Hourly, Bug
