### ISSUE TITLE
[HOLD for payment 2023-08-02] [$1000] Request Money input is not getting focus when navigating back

### ISSUE THREAD

**Issue by kavimuru** [Expensify/App#22610] opened 2023-07-11 03:14 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Request Money
2. Enter Amount & Click Next
3. See focus getting applied to input
4. Click on any User contact
5. Come back and see Input is not getting focus.
## Expected Result: 
Input should get focused in any case of navigation.
## Actual Result: 
Not getting in case of navigating back.

## Workaround:
Can the user still use Expensify without this being fixed? Have you informed them of the workaround?

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [x] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 1.3.39-5
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/43996225/5246bfd9-9348-4cee-b5f1-4728eb4b900f

https://github.com/Expensify/App/assets/43996225/234b2b53-c0b9-4383-a169-ae8ca4c2caf7

**Expensify/Expensify Issue URL:**
**Issue reported by:** @Mahesh-Vagicherla

**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1689016031128029

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01612a76428b498945</li>
        <li>Upwork Job ID: 1679156782678679552</li>
        <li>Last Price Increase: 2023-07-12</li>
    </ul>
</details>

**Comment by multijump** [comment] 2023-07-13 20:33
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
Request Money input is not getting focus when navigating back

### What is the root cause of that problem?
When `HeaderWithBackButton` click, it just go back like browser history back.
https://github.com/Expensify/App/blob/777415e3b6a30d40df4bb3c0cfae27860ae3e561/src/libs/Navigation/Navigation.js#L122
Then `MoneyRequestParticipantsSelector` component didn't rerendered and focus lost in input.

### What changes do you think we should make in order to solve the problem?

In the `MoneyRequestConfirm` component,  fallback url is generated in navigateBack function but it is not used.
We can update to use this fallback url forcely to rerender `MoneyRequestParticipantsSelector`.
```
    const navigateBack = () => {
        let fallback;
        if (reportID.current) {
            fallback = ROUTES.getMoneyRequestRoute(iouType.current, reportID.current);
        } else {
            fallback = ROUTES.getMoneyRequestParticipantsRoute(iouType.current);
        }
        Navigation.goBack(fallback, true);
    };
``` 
We don't need to use setTimeout or change other components.

### Result

https://github.com/Expensify/App/assets/35476479/73ee8b95-6c37-4720-8c65-d3718a48c4b9


### What alternative solutions did you explore? (Optional)
N/A
**Reminder:** Please use plain English, be brief and avoid jargon. Feel free to use images, charts or pseudo-code if necessary. Do not post large multi-line diffs or write walls of text. Do not create PRs unless you have been hired for this job.

**Comment by maddylewis** [comment] 2023-07-14 20:26
@eVoloshchak - bump on proposal reviews - thx!

**Comment by eVoloshchak** [comment] 2023-07-16 23:19
@tienifr's [proposal](https://github.com/Expensify/App/issues/22610#issuecomment-1630079904) looks good to me
I think we should use InteractionManager.runAfterInteractions, the same approach is used on MoneyRequestAmountPage [here](https://github.com/Expensify/App/blob/6e5b07cf45944f28373e188d6f02620a12d6da29/src/pages/iou/steps/MoneyRequestAmountPage.js#L222) (except it's relying on `useFocusEffect` to determine when screen is focused)

🎀👀🎀 C+ reviewed!

**Comment by b4s36t4** [comment] 2023-07-17 19:31
This bug has been reported by me @cead22 .

**Comment by cead22** [comment] 2023-07-18 15:10
> This bug has been reported by me @cead22 .

Thanks for highlighting this @b4s36t4, I think the automation script pulled `@mahesh` from here. FYI @maddylewis 

> **Issue reported by:** @Mahesh-Vagicherla

**Comment by maddylewis** [comment] 2023-07-18 15:31
noted! i will manually hire @b4s36t4 as the reporter in Upwork.

**Comment by luacmartins** [comment] 2023-07-19 17:55
FYI [this issue](https://github.com/Expensify/App/issues/23096) seems to have the same root cause. Can we fix that as part of the PR linked to this issue?

**Comment by eVoloshchak** [comment] 2023-07-20 17:52
@luacmartins, it already is resolved by the PR since the root cause is the same 🎉

**Comment by maddylewis** [comment] 2023-07-29 14:06
moving to daily since payments are due early next week

**Comment by maddylewis** [comment] 2023-07-31 20:44
Payment due on Aug 2

**Comment by eVoloshchak** [comment] 2023-08-02 15:21
- The PR that introduced the bug has been identified. Link to the PR: there isn't a PR that caused this regression, but rather something that wasn't implemented initially when creating `BaseOptionsSelector`
- The offending PR has been commented on, pointing out the bug it caused and why, so the author and reviewers can learn from the mistake. Link to comment: N/A
- A discussion in #expensify-bugs has been started about whether any other steps should be taken (e.g. updating the PR review checklist) in order to catch this type of bug sooner. Link to discussion: this is a visual bug, I don't think an additional discussion is needed
- Determine if we should create a regression test for this bug.
_Is it easy to test for this bug? Yes
Is the bug related to an important user flow? Yes
Is it an impactful bug? No_
While not very impactful, the bug is annoying, and since it's also very easy to test, I think a small regression test would be suitable here.

**Comment by eVoloshchak** [comment] 2023-08-02 15:24
**Regression Test Proposal**

1. Click FAB -> Request Money
2. Enter an amount and click Next
3. Verify that `name & phone number` input is focused
4. Select any of the contacts
5. Click Back
6. Verify that `name & phone number` input is focused

**Do we agree 👍 or 👎**

**Comment by maddylewis** [comment] 2023-08-02 18:11
### Payments
- [ ] @eVoloshchak ($1000 - paid via NewDot)
- [ ] @tienifr ($1000 - paid view Upwork)
- [ ] @b4s36t4 ($250 - reporting bonus paid via Upwork)
____
- Contributor hired on July 16
- PR merged on July 24

**Comment by b4s36t4** [comment] 2023-08-02 19:44
@maddylewis Accepted the offer in upwork. Thanks.

**Comment by eVoloshchak** [comment] 2023-08-03 16:22
Requested the payment via NewDot

**Comment by JmillsExpensify** [comment] 2023-08-03 22:09
Reviewed details for @eVoloshchak. These details are accurate based on summary from Business Reviewer and are now approved for payment in NewDot.

**Comment by maddylewis** [comment] 2023-08-06 18:19
all payments sent - closing!

**Closed by maddylewis** 2023-08-06 18:19 UTC
Labels: External, Daily, Overdue, Awaiting Payment, Bug
