### ISSUE TITLE
[$1000] Web - The deleted attachment is not gone immediately and opens up in a new tab with old expensify 404 error

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#20853] opened 2023-06-15 20:15 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Go to staging dot on web chrome and login with user A
2. Go to a chat with User B and send an attachment
3. Login with User B on another web chrome and go to the same chat
4. From both A and B , click on reply thread icon of the attachment message
5. From B, flag the message as assault
6. From A, delete the attachment and wait until it shows ''deleted message"
7. On User B, notice that even the attachment has already been deleted on User's A account, User B is still able to see it. 

It seems like user B needs to exit the thread in order for the attachment image to truly be deleted.

## Expected Result:
The deleted attachment should be gone immediately after it's deleted, so that it doesn't show for any users.

## Actual Result:
The deleted attachment is not deleted immediately, and seems to persist in User B's thread until they exit the thread. 

## Workaround:
Exit the thread and re-enter the thread, see it's deleted at that point.

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [x] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 1.3.27.7

**Reproducible in staging?:** yes

**Reproducible in production?:** yes

**If this was caught during regression testing, add the test name, ID and link from TestRail:**

https://github.com/Expensify/App/assets/93399543/9fcacfa8-fa48-4286-8338-8bd471cb1dd5

https://github.com/Expensify/App/assets/93399543/0ab5ecc2-87d3-4a66-a0e0-5444b2820ac2

**Expensify/Expensify Issue URL:**

**Issue reported by:** @priya-zha

**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1686224036040209

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~010dd35f91d11f7f88</li>
        <li>Upwork Job ID: 1671234239978795008</li>
        <li>Last Price Increase: 2023-06-27</li>
    </ul>
</details>

**Comment by michaelhaxhiu** [comment] 2023-06-20 18:23
testing

**Comment by michaelhaxhiu** [comment] 2023-06-20 18:41
I just tried to reproduce this one! I didn't get a 404 error or the ability to download the attachment afterwards.

It seems like it takes a few seconds for the deleted attachment to stop showing the image for userB. But it does successfully delete if you exit the thread (by returning to the corresponding #admin channel). 

If userB reports the attachment as assault, and then userA deletes it, I am noticing the attachment doesn't actually delete from the UI until userA and userB exit the thread. So we should likely focus on that part and figure out why there's a lag in the actual deletion.

![lvmeal](https://github.com/Expensify/App/assets/13206896/aa92ae14-e5bf-4d19-8bd4-7fa07b466f95)
https://recordit.co/5CF4MZsol5

**Comment by michaelhaxhiu** [comment] 2023-06-20 18:42
I updated the bug report a little from what @priya-zha originally reported.

Can you try to reproduce this again and let me know if you get the same behavior as me Priay (or @kbecciv)?

**Comment by priya-zha** [comment] 2023-06-20 19:04
@michaelhaxhiu I'm still able to reproduce the same old behavior. However, yes you're correct. Even for User A, for a [deleted message] to appear, we need to exit from the thread or need to refresh the page as shown in the 0:35 seconds in the bug recording. The same goes for the User B side. So yeah, your modifications will solve both the bugs: first bug- lag in the deletion and second: if the first big is solved, we will not get a download option that throws a 404 error on the old dot.

**Comment by michaelhaxhiu** [comment] 2023-06-20 19:10
>So yeah, your modifications will solve both the bugs: 

Excellent :) I'll still give you this bug report as you caught the root issue. Just needed the sanity check here 🧠

**Comment by abdulrahuman5196** [comment] 2023-06-23 14:58
Not overdue. There hasn't been any proposals yet.

**Comment by ShogunFire** [comment] 2023-06-25 15:43
I think it is related to this issue https://github.com/Expensify/App/issues/19363 and will be corrected soon

**Comment by abdulrahuman5196** [comment] 2023-06-26 15:38
Yes. We can wait on the PR. Seems its possible for this issue to be solved as well.

**Comment by abdulrahuman5196** [comment] 2023-06-29 14:47
The PR is merged need to retest this issue

**Comment by abdulrahuman5196** [comment] 2023-06-29 15:46
@michaelhaxhiu I tested and this seems to be fixed. Could you kindly check at your end as well and close this issue if its fixed.

**Comment by michaelhaxhiu** [comment] 2023-06-29 17:18
Great, I will hire Priya and pay bug bonus. Then close.

**Comment by michaelhaxhiu** [comment] 2023-06-29 17:18
@priya-zha can you comment here after you accept the job offer?

**Comment by priya-zha** [comment] 2023-06-29 17:21
@michaelhaxhiu accepted.thanks.

**Closed** 2023-06-29 21:21 UTC
Labels: External, Daily, Help Wanted, Bug
