### ISSUE TITLE
[$250] Chat - Green line and 'New' label disappear after clicking 'New Messages' and scrolling down

### ISSUE THREAD

**Issue by kavimuru** [Expensify/App#34419] opened 2024-01-12 09:49 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.24-5
**Reproducible in staging?:** y
**Reproducible in production?:** n
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** Applause internal team
**Slack conversation:**

## Action Performed:
1. Open App or go to staging.new.expensify.com
2. Login with any account
3. Go to any chat
4. Mark the latest message as unread
5. Scroll up the chat history
6. Click on 'New Messages' button

## Expected Result:
Chat scrolls to the bottom. New message marked with green line and label 'New'.

## Actual Result:
Green line and 'New' label disappear after clicking 'New Messages' and scrolling down

## Workaround:
unknown
## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [ ] Android: mWeb Chrome
- [x ] iOS: Native
- [x] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

https://github.com/Expensify/App/assets/43996225/788388a4-294f-4021-be11-ef43d0430800

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01583c5a710f37ccec</li>
        <li>Upwork Job ID: 1802797330742937527</li>
        <li>Last Price Increase: 2024-07-01</li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @shubham1206agra</details>

**Comment by youssef-lr** [comment] 2024-01-12 20:12
Checking. Not sure if this is a bug or a new fix.

**Comment by situchan** [comment] 2024-01-14 18:50
reproduced in production as well.
Btw this is recent regression. Used to work before.
cc: @MonilBhavsar

**Comment by youssef-lr** [comment] 2024-01-14 20:45
I'm not really sure this is a bug. It seems to also fix the 'New Messages' marker remaining even after we read the last unread message. @MonilBhavsar can you confirm please?

**Comment by youssef-lr** [comment] 2024-01-14 20:46
I'm also able to reproduce this in production, removing blocker.

**Comment by zanyrenney** [comment] 2024-01-17 12:59
also can reproduce!

**Comment by zanyrenney** [comment] 2024-01-17 13:00
@MonilBhavsar are you able to take this one if its a regression from a previous release?

**Comment by MonilBhavsar** [comment] 2024-01-17 13:18
Not sure if this is regression from https://github.com/Expensify/App/pull/33162
@youssef-lr is this issue not reproducible without that code?

I have commented in other issue also https://github.com/Expensify/App/issues/33118#issuecomment-1895793581

**Comment by situchan** [comment] 2024-01-17 13:33
I can take this as C+

**Comment by zanyrenney** [comment] 2024-01-19 12:01
thanks @situchan just waiting for a response @youssef-lr on if reproducbible without the code. thanks for the work looking into that @monil

**Comment by youssef-lr** [comment] 2024-01-23 03:30
On it today @zanyrenney, sorry for the delay! I was OOO sick on Friday.

**Comment by youssef-lr** [comment] 2024-01-23 18:45
I reverted the PR locally and I can still reproduce the issue. Should we fix this though? I'm not sure this is a bug really, shouldn't the marker disappear if we click on "New messages"? One added benefit is that scrolling up again does not resurface the "New messages" marker.

**Comment by zanyrenney** [comment] 2024-01-26 12:51
yeah I see your point when you frame it like that, I think we can close. Doing so! cc @youssef-lr

**Comment by situchan** [comment] 2024-01-26 13:41
> @zanyrenney @youssef-lr, I think we should discuss about this because this behaviour was for a long time and it has changed recently unintentionally. What do you think @situchan?

I am fine either fixing or closing as minor. I will defer to @MonilBhavsar who is managing unread marker issues

**Comment by kbecciv** [comment] 2024-05-27 12:32
@zanyrenney @youssef-lr We have TR steps where according to the steps the new message line is display on top of the new messages https://expensify.testrail.io/index.php?/tests/view/4549003, please create TR update issue if it's expected behavior. Thank you!

**Comment by youssef-lr** [comment] 2024-06-05 18:08
Will take a look tomorrow @kbecciv

**Comment by zanyrenney** [comment] 2024-06-17 20:15
Looking for new proposals here because it seems like it’s not behaving as it should based on the TestRail steps we have.

**Comment by youssef-lr** [comment] 2024-06-21 22:12
Waiting for proposals.

**Comment by zanyrenney** [comment] 2024-06-24 16:37
@shubham1206agra @youssef-lr I think we should up the bounty for this one. What do you think?

**Comment by muttmuure** [comment] 2024-06-27 09:37
This does not seem like a bug, so can we update Test Rail and move on please?

**Comment by youssef-lr** [comment] 2024-07-02 05:03
It seems like this is no longer reproducible.

https://github.com/Expensify/App/assets/9680864/565ed804-030b-43a1-8cd1-328ad5287842

**Comment by mvtglobally** [comment] 2024-07-03 14:42
Issue not reproducible during KI retests. (First week)

**Comment by zanyrenney** [comment] 2024-07-04 17:53
have asked to update testrail - closing!

**Closed by zanyrenney** 2024-07-04 17:53 UTC
Labels: External, Engineering, Daily, Help Wanted, Overdue, Bug
