### ISSUE TITLE
Netsuite-App crashes when connecting to Netsuite with incorrect credentials

### ISSUE THREAD

**Issue by IuliiaHerets** [Expensify/App#48682] opened 2024-09-06 08:03 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** v9.0.30-7
**Reproducible in staging?:** Y
**Reproducible in production?:** N
**Email or phone of affected tester (no customers):** applausetester+shsb223455@applause.expensifail.com
**Issue reported by:** Applause Internal Team

## Action Performed:
1. Log in to new dot with a new account and create a new workspace
2. Navigate to settings > workspace > More features > Enable accounting
3. Go to Accounting > Connect to Netsuite > Upgrade to Control > Got it
4. When the Netsuite Setup RHP opens proceed with the setup
5. Enter incorrect credentials when prompted and connect

## Expected Result:
"Can't connect to NetSuite." error appears and app does not crash

## Actual Result:
App crashes

## Workaround:
Unknown

## Platforms:

- [ ] Android: Native
- [x] Android: mWeb Chrome
- [x] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos
[0609.log](https://github.com/user-attachments/files/16904730/0609.log)

https://github.com/user-attachments/assets/2a41fc0b-e551-4402-a550-5d3f6a6d35ea

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by IuliiaHerets** [comment] 2024-09-06 08:03
We think that this bug might be related to #wave-control

**Comment by etCoderDysto** [comment] 2024-09-06 08:06
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
Netsuite-App crashes when connecting to Netsuite with incorrect credentials
### What is the root cause of that problem?
We are not applying optional chaining on `options`
https://github.com/Expensify/App/blob/da8370fd434594a2ade67a81035a6caec0d0118c/src/pages/workspace/accounting/utils.tsx#L51
### What changes do you think we should make in order to solve the problem?
Use optional chaining on `options`
```
const netsuiteConfig = policy?.connections?.netsuite?.options?.config;
```
### What alternative solutions did you explore? (Optional)

**Comment by etCoderDysto** [comment] 2024-09-06 08:09
## Proposal
Offending PR: https://github.com/Expensify/App/pull/46667

I can raise a quick PR if the author is not available at the time 
### Please re-state the problem that we are trying to solve in this issue.
Netsuite-App crashes when connecting to Netsuite with incorrect credentials
### What is the root cause of that problem?
We are not applying optional chaining on `options`
https://github.com/Expensify/App/blob/da8370fd434594a2ade67a81035a6caec0d0118c/src/pages/workspace/accounting/utils.tsx#L51
### What changes do you think we should make in order to solve the problem?
Use optional chaining on `options`
```javascript
const netsuiteConfig = policy?.connections?.netsuite?.options?.config;
```
### What alternative solutions did you explore? (Optional)

**Comment by war-in** [comment] 2024-09-06 08:36
Ah sorry for this one 🙈 
@etCoderDysto thanks for the proposal, I checked it and it's working correctly!
I can create a PR in a moment or you can do this if you want. Please let me know 🙏

**Comment by etCoderDysto** [comment] 2024-09-06 08:56
@war-in You are welcome! I think you can raise a PR since you are available.

**Comment by Julesssss** [comment] 2024-09-06 12:11
[PR](https://github.com/Expensify/App/pull/48688) fix merged. I'm not going to CP to staging to resolve the blocker.

**Comment by Julesssss** [comment] 2024-09-06 14:17
CP successful, I marked it off the checklist

**Closed by Julesssss** 2024-09-06 14:17 UTC
Labels: Reviewing, Engineering, Weekly, Bug

**Comment by Pujan92** [comment] 2024-09-26 12:06
@war-in I am seeing the crash while connecting Netsuite.

<img width="1437" alt="Screenshot 2024-09-26 at 17 33 34" src="https://github.com/user-attachments/assets/b84b8f72-6ccf-4d43-9a3b-2446ecc278a9">

**Comment by war-in** [comment] 2024-09-30 10:39
> @war-in I am seeing the crash while connecting Netsuite.

@Pujan92 is there an issue for this bug? Or could you create one and add some reproduction steps?
