### ISSUE TITLE
[Awaiting Checklist Completion] [$500] Unable to create a Distance request from an Expense Report

### ISSUE THREAD

**Issue by kavimuru** [Expensify/App#30407] opened 2023-10-26 02:27 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.3.91-1
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** @paultsimura
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1698185015146149

## Action Performed:
1. Create a chat
2. Click the '+' button > Request money
3. Notice the Distance option is available

VS

1. Create a chat
2. Click the '+' button > Request money > add an Amount
3. Send the request to someone
4. Click on an IOU
5. Then click on the '+' of the IOU chat > Request Money
8. Notice the distance is missing

## Expected Result: 
The "Distance" tab should be present
## Actual Result: 
The "Distance" tab is absent, only "Manual" and "Scan" are present.

## Workaround:
unknown
## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [x] Android: mWeb Chrome
- [x] iOS: Native
- [x] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos
<details>
<summary>Android: Native</summary>

https://github.com/Expensify/App/assets/43996225/90f4f0b8-279b-4f40-a793-4598215af947

</details>

<details>
<summary>Android: mWeb Chrome</summary>

https://github.com/Expensify/App/assets/43996225/6717816e-02f2-4e44-856e-b939bc67a5dd

</details>

<details>
<summary>iOS: Native</summary>

https://github.com/Expensify/App/assets/43996225/e5fccd5a-1277-4b80-9ae1-ad55aa228df0

</details>

<details>
<summary>iOS: mWeb Safari</summary>

https://github.com/Expensify/App/assets/43996225/b62f70bf-a35f-4d37-8b2d-9347272ed3ba

</details>

<details>
<summary>MacOS: Chrome / Safari</summary>

https://github.com/Expensify/App/assets/43996225/04765d95-d6e6-4681-bba8-c23bde36cb39

https://github.com/Expensify/App/assets/43996225/80642c1c-9b59-4f29-9ed6-f14104ab741f

</details>

<details>
<summary>MacOS: Desktop</summary>

https://github.com/Expensify/App/assets/43996225/886dc32e-ec17-46d4-833e-142cbfb7c892

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~018ee1716b83450d28</li>
        <li>Upwork Job ID: 1717367371596656640</li>
        <li>Last Price Increase: 2023-11-02</li>
<li>Automatic offers: </li>
<ul>
<li>paultsimura | Contributor | 27511292</li>
<li>paultsimura | Reporter | 27511294</li>
</ul></li>
    </ul>
</details>

**Comment by kavimuru** [comment] 2023-10-26 02:28
## Proposal from @paultsimura
### Please re-state the problem that we are trying to solve in this issue.
The Distance request cannot be created from an expense report
### What is the root cause of that problem?
We have a clear check whether to show the distance tab here:
https://github.com/Expensify/App/blob/fe3e8bc3118816086bde2e28009a9018c41eba71/src/pages/iou/MoneyRequestSelectorPage.js#L70-L72
It's currently configured to show only on FAB and Expense Chats.
### What changes do you think we should make in order to solve the problem?
**First,** We should modify the code above to show the distance tab on the expense reports as well:
```js
    const isFromGlobalCreate = !reportID;
    const isExpenseChat = ReportUtils.isPolicyExpenseChat(props.report)
    const isExpenseReport = ReportUtils.isExpenseReport(props.report);
    const shouldDisplayDistanceRequest = isExpenseChat || isExpenseReport || isFromGlobalCreate;
```
**Second,** we should adapt the flow for creation of such requests on the expense reports. For this, in `IOU.createDistanceRequest`, check if the report is an expense report: if it is, we should use its root parent report (it'll be an expense chat) for all the calculations, but use this expense report's ID for final redirection, so we are not redirected to parent chat on creation:
```diff
function createDistanceRequest(report, participant, comment, created, transactionID, category, tag, amount, currency, merchant, billable) {
+    const isExpenseReport = ReportUtils.isExpenseReport(report);
+    const targetChat = isExpenseReport ? ReportUtils.getRootParentReport(report) : report;
    const optimisticReceipt = {
        source: ReceiptGeneric,
        state: CONST.IOU.RECEIPT_STATE.OPEN,
    };
    const {iouReport, chatReport, transaction, iouAction, createdChatReportActionID, createdIOUReportActionID, reportPreviewAction, onyxData} = getMoneyRequestInformation(
+        targetChat,
-        report,
        participant,
```
Also, use this report here, because in some cases we allow creating money requests in already settled expense reports proof: https://github.com/Expensify/App/blob/950f37a31154aef422fadc194c3791cd84354675/src/libs/ReportUtils.js#L3565C4-L3577), and the `getMoneyRequestInformation`, which we use to retrieve `iouReport.reportID`,  always returns the non-settled report:
```js
iouReportID: isExpenseReport ? report.reportID : iouReport.reportID,
```
https://github.com/Expensify/App/blob/f6a9dde37803302b3b1a1dd2b5c5f720ab309f6d/src/libs/actions/IOU.js#L642
And here for the final navigation so we get redirected directly to the expense report:
```js
    Navigation.dismissModal(isExpenseReport ? report.reportID : chatReport.reportID);
```
https://github.com/Expensify/App/blob/f6a9dde37803302b3b1a1dd2b5c5f720ab309f6d/src/libs/actions/IOU.js#L657
#### Result:
https://github.com/Expensify/App/assets/12595293/3b39c5df-d92a-4547-864d-736ab3064b48

### What alternative solutions did you explore? (Optional)

**Comment by paultsimura** [comment] 2023-10-26 08:16
## Proposal
### Please re-state the problem that we are trying to solve in this issue.
The Distance request cannot be created from an expense report
### What is the root cause of that problem?
We have a clear check whether to show the distance tab here:
https://github.com/Expensify/App/blob/fe3e8bc3118816086bde2e28009a9018c41eba71/src/pages/iou/MoneyRequestSelectorPage.js#L70-L72
It's currently configured to show only on FAB and Expense Chats.
### What changes do you think we should make in order to solve the problem?
**First,** We should modify the code above to show the distance tab on the expense reports as well:
```js
    const isFromGlobalCreate = !reportID;
    const isExpenseChat = ReportUtils.isPolicyExpenseChat(props.report)
    const isExpenseReport = ReportUtils.isExpenseReport(props.report);
    const shouldDisplayDistanceRequest = isExpenseChat || isExpenseReport || isFromGlobalCreate;
```


**Second,** we should adapt the flow for the creation of such requests on the expense reports. For this, in `IOU.createDistanceRequest`, check if the report is an expense report: if it is, we should use its root parent report (it'll be an expense chat) for all the calculations, but use this expense report's ID for final redirection, so we are not redirected to parent chat on creation:

```diff
function createDistanceRequest(report, participant, comment, created, transactionID, category, tag, amount, currency, merchant, billable) {
+ // If the report is iou or expense report, we should get the linked chat report to be passed to the getMoneyRequestInformation function
+    const isMoneyRequestReport = ReportUtils.isMoneyRequestReport(report);
+    const currentChatReport = isMoneyRequestReport ? ReportUtils.getReport(report.chatReportID) : report;
    const optimisticReceipt = {
        source: ReceiptGeneric,
        state: CONST.IOU.RECEIPT_STATE.OPEN,
    };
    const {iouReport, chatReport, transaction, iouAction, createdChatReportActionID, createdIOUReportActionID, reportPreviewAction, onyxData} = getMoneyRequestInformation(
+        currentChatReport,
-        report,
        participant,
```

And here for the final navigation so we get redirected directly to the expense report:
```js
    Navigation.dismissModal(isExpenseReport ? report.reportID : chatReport.reportID);
```
https://github.com/Expensify/App/blob/f6a9dde37803302b3b1a1dd2b5c5f720ab309f6d/src/libs/actions/IOU.js#L657

#### Result:
https://github.com/Expensify/App/assets/12595293/3b39c5df-d92a-4547-864d-736ab3064b48

### What alternative solutions did you explore? (Optional)

**Comment by Christinadobrzyn** [comment] 2023-10-26 19:43
I think based on our change announced here - https://expensify.slack.com/archives/C01GTK53T8Q/p1698191269281379

We can close this since it was reported by a contributor.

**Comment by paultsimura** [comment] 2023-10-26 19:49
@Christinadobrzyn this was reported before the announcement.
And in the announcement, it's clearly stated:
> Please note that any bugs reported prior to this announcement will be accepted and treated as they normally would. 

Why would you close it then?

**Comment by paultsimura** [comment] 2023-10-26 19:51
It also was discussed in Slack with the engineers and the reporting was approved before the announcement: https://expensify.slack.com/archives/C01GTK53T8Q/p1698182060752669

@Christinadobrzyn

**Comment by greg-schroeder** [comment] 2023-10-26 20:18
@Christinadobrzyn we can take bug reports that were sent to #expensify-bugs prior to the announcement

**Comment by Christinadobrzyn** [comment] 2023-10-27 18:07
Ah thanks, I didn't realise it was the Slack date not the GH creation date. Sorry about that! This is a good find so I'm glad we're doing it. 

I can reproduce and I don't see any other GHs about this issue.

**Comment by Christinadobrzyn** [comment] 2023-10-30 19:04
@thesahindia can you review the provided proposals to see if they will work? Thanks!

**Comment by Christinadobrzyn** [comment] 2023-11-02 16:17
@thesahindia could you review these proposals and let me know if you want to see others?

**Comment by flodnv** [comment] 2023-11-03 14:09
Hmmm @neil-marcellini what are your thoughts on this please?

**Comment by paultsimura** [comment] 2023-11-03 14:24
@flodnv please check this thread, where @neil-marcellini was involved as well:

https://expensify.slack.com/archives/C01GTK53T8Q/p1698182060752669

**Comment by flodnv** [comment] 2023-11-03 14:27
Alright thanks, letting you handle this one then @neil-marcellini as this is a recent feature

**Comment by neil-marcellini** [comment] 2023-11-03 17:23
Ok cool I will review the proposal soon.

**Comment by neil-marcellini** [comment] 2023-11-03 20:47
> @paultsimura's [proposal](https://github.com/Expensify/App/issues/30407#issuecomment-1780632583) looks good to me!
> 
> 🎀 👀 🎀 C+ reviewed

I agree. Hired 🚀

**Comment by paultsimura** [comment] 2023-11-04 05:42
Thanks. The PR is ready for review: https://github.com/Expensify/App/pull/30881

**Comment by Christinadobrzyn** [comment] 2023-11-18 00:44
Looks like the PR went to production 3 days ago so payment would be Nov 21st. 

I'm going ooo until Monday Nov 27th so going to assign another BZ teammate to monitor this until I'm back. Thanks!

Status: waiting for payment & regression test propsoal

Payouts due:

Issue Reporter: $50 @paultsimura - reporter bonus (in Upwork)
Contributor: $500 @paultsimura (in Upwork)
Contributor+: $500 @thesahindia (though NewExpensify)

Eligible for 50% #urgency bonus? N

Upwork job is [here](https://www.upwork.com/jobs/~018ee1716b83450d28).

**Comment by twisterdotcom** [comment] 2023-11-20 10:49
Payment due tomorrow.

**Comment by twisterdotcom** [comment] 2023-11-21 15:24
Payment Summary:
@paultsimura paid $550 via Upwork (https://www.upwork.com/nx/wm/workroom/35345726/overview / https://www.upwork.com/nx/wm/workroom/35345722/overview
@thesahindia $500 (through NewDot)

Waiting on @thesahindia to complete [the checklist](https://github.com/Expensify/App/issues/30407#issuecomment-1805950409) now.

**Closed** 2023-11-27 10:25 UTC
Labels: Daily, Internal, Bug
