### ISSUE TITLE
Web - Chat - Avatar turns solid grey instead of lightly grey out 

### ISSUE THREAD

**Issue by kavimuru** [Expensify/App#11144] opened 2022-09-20 17:50 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___
Issue found when executing #10706
## Action Performed:
1. Go to staging.new.expensify.com
2. Log in with the HT expensifail account
3. Go to Profile - Settings
4. Click on the avatar picker and upload an avatar.
5. Turn off your device Wi-Fi very quickly

## Expected Result:
Avatar should be greyed out

## Actual Result:
Avatar terns solid grey instead of lightly grey out for HT account

## Workaround:
Unknown

## Platform:

Where is this issue occurring?

- Web

**Version Number:** 1.2.3.0
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**Email or phone of affected tester (no customers):** applausetester+0901abb@applause.expensifail.com / Feya86Katya
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** 
https://user-images.githubusercontent.com/43996225/191328657-b598739d-ff3a-4b71-8e64-894483071147.mp4
**Expensify/Expensify Issue URL:** 
**Issue reported by:** Applause internal team
**Slack conversation:** 

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by varshamb** [comment] 2022-09-20 18:02
### Proposal 

Change `spinner: colors.gray4` to `spinner: colors.gray3`

**Comment by sobitneupane** [comment] 2022-09-21 02:43
Looks like we have intentionally made offline avatar's solid gray. If we want to make it light gray, we need to change
https://github.com/Expensify/App/blob/2b6124e1b833bcfe1a4b6e8e982f2b1c36b5417d/src/styles/themes/default.js#L34
```diff
-    offline: colors.gray3
+    offline: colors.gray2,
```

**Comment by luacmartins** [comment] 2022-09-21 16:50
@kavimuru can you add a video for this bug? I tested this on staging and it seems to be working correctly.

**Comment by kavimuru** [comment] 2022-09-23 14:05
@luacmartins This is the video and already attached to the bug.
https://user-images.githubusercontent.com/43996225/191328657-b598739d-ff3a-4b71-8e64-894483071147.mp4

**Comment by kavimuru** [comment] 2022-09-23 14:58
@luacmartins We are not able to reproduce with the new build 

https://user-images.githubusercontent.com/43996225/191990755-b7d51352-f9f8-4b37-a91f-c94bce0bb3c7.mp4

**Comment by luacmartins** [comment] 2022-09-23 16:24
I wasn't able to reproduce this either. Gonna close this issue. Feel free to reopen it if it shows up again!

**Closed by luacmartins** 2022-09-23 16:24 UTC
Labels: Engineering, Daily, Overdue
