### ISSUE TITLE
[$250] BUG: DEV - Console error on web app load react-dom.development.js?.. - reported by @aneequeahmad

### ISSUE THREAD

**Issue by mvtglobally** [Expensify/App#11904] opened 2022-10-17 09:41 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:

1. Launch web app
2. See the error in console.

## Expected Result:
No Errors should display 

## Actual Result:
Console error on web app load react-dom.development.js?61bb:86 Warning: ReactDOM.render is no longer supported in React 18. Use createRoot instead. Until you switch to the new API, your app will behave as if it's running React 17.

## Workaround:
unknown 

## Platform:

Where is this issue occurring?

- Web

**Version Number:** 1.2.12-3
**Reproducible in staging?:** N
**Reproducible in production?:** N
**Email or phone of affected tester (no customers):** 
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation 

https://user-images.githubusercontent.com/43995119/196144874-c4565c78-b77f-47be-9bd1-330cc0e9581e.mov

<img width="1440" alt="Screenshot 2022-09-08 at 8 48 37 AM" src="https://user-images.githubusercontent.com/43995119/196144895-d1519049-1373-47cc-8449-c543051e5589.png">

**Expensify/Expensify Issue URL:** 
**Issue reported by:** @aneequeahmad
**Slack conversation:** https://expensify.slack.com/archives/C01GTK53T8Q/p1661251204472079

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by parasharrajat** [comment] 2022-10-18 18:36
There is an internal issue #11680 which is going to fix it. Thus this is kind of duplicate.

**Comment by sakluger** [comment] 2022-10-18 18:40
Thanks @parasharrajat - if this is a duplicate, do you recommend closing this one?

**Comment by michaelhaxhiu** [comment] 2022-10-18 18:47
@parasharrajat do you think we ought to pay a reporting bonus for this when the internal issue is resolved? cc @roryabraham since you are assigned to the internal issues.

IMO this doesn't get paid and closed until we decide if (1) it's a tue duplicate or not and (2) the problem is actually fixed.

**Comment by parasharrajat** [comment] 2022-10-18 18:52
So this was reported on Aug 23 and we created an internal issue on https://github.com/Expensify/App/issues/8503#issuecomment-1261334274. 

Seems like eligible for reporting bonus.

**Comment by roryabraham** [comment] 2022-10-18 20:26
Fair's fair – @aneequeahmad beat me to reporting this so I agree with @parasharrajat's last message.

**Comment by sakluger** [comment] 2022-10-21 23:41
Cool, closing in favor of https://github.com/Expensify/App/issues/11680. I left a comment on that issue that @aneequeahmad should be paid the reporting bonus once it's completed.

**Closed by sakluger** 2022-10-21 23:41 UTC
Labels: External, Daily, Needs Reproduction, Help Wanted, Overdue, Bug
