### ISSUE TITLE
[Held requests] [$250] OD - Held status in the expense modal is unclickable

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#42933] opened 2024-05-31 15:09 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.78-2
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**If this was caught during regression testing, add the test name, ID and link from TestRail:** https://expensify.testrail.io/index.php?/cases/view/2990380
**Issue reported by:** Applause - Internal Team

## Action Performed:
Precondition: workspace member has 2 submitted expenses: 1 expense is on Hold and 1 is in pending.
1. Navigate from ND to OD (ND: Settings > Subscriptions)
2. OD: Go to Reports > Processing report with hold expense
3. Open Hold expense modal
4. Click the status

## Expected Result:
Clicking the status is navigating user to the expense in ND

## Actual Result:
Status is unclickable

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details> 

https://github.com/Expensify/App/assets/78819774/66e3d4f5-f11c-4dcd-b08d-67e8e56084f2

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01debee67374ff8741</li>
        <li>Upwork Job ID: 1797609350729863168</li>
        <li>Last Price Increase: 2024-06-10</li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @robertjchen</details>

**Comment by lanitochka17** [comment] 2024-05-31 15:10
@laurenreidexpensify FYI I haven't added the External label as I wasn't 100% sure about this issue. Please take a look and add the label if you agree it's a bug and can be handled by external contributors

**Comment by lanitochka17** [comment] 2024-05-31 15:10
We think that this bug might be related to #wave-collect - Release 1

**Comment by laurenreidexpensify** [comment] 2024-06-05 10:40
@trjExpensify do you reckon we need to address this in Expensify/App or Expensify/Expensify?

**Comment by trjExpensify** [comment] 2024-06-05 10:53
The issue can stay here in the App repo, but I think the fix will be required in Web-E. CC: @robertjchen 

It would be good to confirm though:

1. Did a user hold this expense in NewDot and add a comment? If so, why isn't it showing in the OD banner? The comment is null `""` and that's what should be hyperlinked.  

<img width="1164" alt="image" src="https://github.com/Expensify/App/assets/16232057/48bf2a07-117d-4e94-9bdf-7c41fd62cfe4">

2. Why is there a "Mark as cash" button? Does this test account have a managed card assigned to them? If so, is there a different (and expected) result for a user that does not have a card assigned to them. This could be the root cause of the problem.

CC: @JmillsExpensify

**Comment by JmillsExpensify** [comment] 2024-06-07 03:54
Huh, yeah that's odd. I agree we should fix this as part of the Summer release.

**Comment by laurenreidexpensify** [comment] 2024-06-07 12:29
@lanitochka17 pls confirm the test account used to replicate this report so we can investigate further thanks!

**Comment by laurenreidexpensify** [comment] 2024-06-07 12:30
@lanitochka17 pls confirm the test account used to replicate this report so we can investigate further thanks!

**Comment by lanitochka17** [comment] 2024-06-07 19:00
tester used applausetester+bp3005e@applause.expensifail.com
TestRail: https://expensify.testrail.io/index.php?/cases/view/2990380

**Comment by robertjchen** [comment] 2024-06-10 06:45
Yes, this is going to have to be a Web-E fix. Looking into this

**Comment by robertjchen** [comment] 2024-06-14 06:51
Working on reproducing this in local dev

**Comment by robertjchen** [comment] 2024-06-17 10:10
Working on reproducing this in local dev for a backend fix

**Comment by robertjchen** [comment] 2024-06-21 09:45
Just getting to this one

**Comment by robertjchen** [comment] 2024-06-24 16:02
Testing in local dev, aiming for PR by EOW

**Comment by robertjchen** [comment] 2024-06-27 12:01
PR under review!

**Comment by robertjchen** [comment] 2024-07-01 23:05
This is complete

**Closed by robertjchen** 2024-07-01 23:05 UTC
Labels: Reviewing, Daily, Bug
