### ISSUE TITLE
[HOLD for payment 2023-11-16] [$500] public room as anonymous user can able to edit profile

### ISSUE THREAD

**Issue by m-natarajan** [Expensify/App#28925] opened 2023-10-05 14:53 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:

1. Go to a public room as an anonymous user like https://staging.new.expensify.com/r/207591744844000
2. Click on the search icon.
3. Close the login menu.
4. enter url in chrome /settings/profile, /settings/profile/display-name

## Expected Result: 
we should show login modal
## Actual Result: 
able to edit the profile

## Workaround:
Can the user still use Expensify without this being fixed? Have you informed them of the workaround?

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [x] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 1.3.78-1
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/38435837/1d90d310-5e57-4df5-b216-891aac1afed0

![Screenshot 2023-10-04 at 10 12 56 PM](https://github.com/Expensify/App/assets/38435837/6b72a368-39a7-4de2-a38b-d26e6f4cbd90)

**Expensify/Expensify Issue URL:**
**Issue reported by:** @pradeepmdk
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1696437761564489

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~017b639bc83b99b494</li>
        <li>Upwork Job ID: 1709944966242185216</li>
        <li>Last Price Increase: 2023-10-05</li>
<li>Automatic offers: </li>
<ul>
<li>DylanDylann | Contributor | 27121862</li>
<li>pradeepmdk | Reporter | 27121865</li>
</ul></li>
    </ul>
</details>

**Comment by DylanDylann** [comment] 2023-10-05 15:22
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
- public room as anonymous user can able to edit profile

### What is the root cause of that problem?
- Currently, when users open the public room as anonymous users, the openReport API will set the ONYX.SESSION with the below value: 
```
authToken: ****
authTokenType: "anonymousAccount"

```
- Then, if the user goes to /settings/profile/display-name, it will run the below logic:
https://github.com/Expensify/App/blob/035ee44762e656874c764f1efb1b85cd14958506/src/libs/actions/Report.js#L1889-L1898
- But in here, the Session.waitForUserSignIn() is always resolved because the ```sessionAuthToken``` is not null:
https://github.com/Expensify/App/blob/567c32e56a449100cebb83af560aa1fcb07daf09/src/libs/actions/Session/index.js#L29-L40
- So it will navigate user to  /settings/profile/display-name screen, which leads to the bug "public room as anonymous user can able to edit profile"
### What changes do you think we should make in order to solve the problem?
- When the route does not contain reportID , for example /settings/profile/display-name screen, we need to wrap the https://github.com/Expensify/App/blob/035ee44762e656874c764f1efb1b85cd14958506/src/libs/actions/Report.js#L1895
by the ```Session.checkIfActionIsAllowed``` like below:
```
 // Navigate to the report after sign-in/sign-up.
    InteractionManager.runAfterInteractions(() => {
        Session.waitForUserSignIn().then(() => {
            if (route === ROUTES.CONCIERGE) {
                navigateToConciergeChat();
                return;
            }
            if (Session.isAnonymousUser() && reportID) {
                Navigation.navigate(route, CONST.NAVIGATION.TYPE.PUSH);
                return;
            }
            Session.checkIfActionIsAllowed(() => {
                Navigation.navigate(route, CONST.NAVIGATION.TYPE.PUSH);
            });
        });
    });
```

### What alternative solutions did you explore? (Optional)
- NA

**Comment by redpanda-bit** [comment] 2023-10-08 04:14
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
Unauthorized access to screens after manual input of url.
### What is the root cause of that problem?
When visiting a public chat room, user is being logged in as anonymous user and because of this the user is granted access to **all** AuthScreens as shown in this `if` condition (line # 10):

https://github.com/Expensify/App/blob/389d7b0c4b96c6f2a2295055c685791d35b65252/src/libs/Navigation/AppNavigator/index.js#L10-L17

**All** AuthScreens are accessible by anonymous users until the function `checkIfActionIsAllowed` is called by onPress handlers in pressable items such as the search icon e.g. (line # 159):

https://github.com/Expensify/App/blob/389d7b0c4b96c6f2a2295055c685791d35b65252/src/pages/home/sidebar/SidebarLinks.js#L155-L160

The `props.authenticated` above comes all the way from [Expensify.js](https://github.com/Expensify/App/blob/main/src/Expensify.js#L108) and it is a boolean value based on the presence of `props.session.authToken`. – `authToken` is a valid string for anonymous users.

This `checkIfActionIsAllowed` pretty much checks if the user is allowed to execute a function based on anonymous or not.

### What changes do you think we should make in order to solve the problem?

Add a new function to [Session/index.js](https://github.com/Expensify/App/blob/main/src/libs/actions/Session/index.js#L789C1-L789C1) that will redirect user to sign in if the user is anonymous e.g.,

```javascript
// src/libs/actions/Session/index.js

function redirectToSignInIfAnonymous() {
    if (isAnonymousUser()) {
        signOutAndRedirectToSignIn();
    }
}
```

And make use of it within [RightModalNavigator.js](https://github.com/Expensify/App/blob/main/src/libs/Navigation/AppNavigator/Navigators/RightModalNavigator.js#L21) like so:


```javascript
// src/libs/Navigation/AppNavigator/Navigators/RightModalNavigator.js
import * as Session from '../../../../libs/actions/Session';

function RightModalNavigator(props) {
    const {isSmallScreenWidth} = useWindowDimensions();
    useEffect(() => Session.redirectToSignInIfAnonymous(), []);
// ...
```
This will ensure that the user is redirected upon initial mounting of the screen.

### What alternative solutions did you explore? (Optional)
1. Change the `Stack.Screen`s in RightModalNavigator.js to return the sign in component instead of the expected screen when the user is an anonymous user:
```js
<Stack.Screen
  name="Settings"
  component={isAnonymousUser ? ModalStackNavigators.SignInModalStackNavigator : ModalStackNavigators.SettingsModalStackNavigator}
/>
```

**Comment by burczu** [comment] 2023-10-09 08:04
not overdue - I'll review proposals soon

**Comment by stitesExpensify** [comment] 2023-10-10 14:55
So to confirm, is this only a front end problem? You can't actually change any settings right?

**Comment by DylanDylann** [comment] 2023-10-11 09:53
@burczu  PR https://github.com/Expensify/App/pull/29248 is ready for review

**Comment by DylanDylann** [comment] 2023-11-07 03:52
The PR is merged

**Comment by mountiny** [comment] 2023-11-14 11:24
This was deployed and should be ready for payment in two days, the automation misbehaved.

**Comment by alexpensify** [comment] 2023-11-14 16:08
@mountiny - is there an agreed to payment amount here or is it the standard rate of $500? Thanks for the update!

**Comment by mountiny** [comment] 2023-11-15 10:46
I think standard

**Comment by alexpensify** [comment] 2023-11-17 01:27
Here is the payment summary: 

-  External issue reporter  @pradeepmdk $50 
-  Contributor that fixed the issue  @DylanDylann $500 
-  Contributor+ that helped on the issue and/or PR @burczu payment for contractor 

Upwork Job: [Upwork job](https://www.upwork.com/jobs/~017b639bc83b99b494)

*If applicable, the bonuses will be applied on the final payment 

Extra Notes regarding payment: N/A

**Comment by alexpensify** [comment] 2023-11-17 01:27
Closing - everyone has been paid via Upwork

**Closed by alexpensify** 2023-11-17 01:27 UTC
Labels: External, Daily, Awaiting Payment, Bug
