### ISSUE TITLE
Workspace - Android: Upon opening an invited user's individual workspace chat, the workspace disappears

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#37978] opened 2024-03-08 15:03 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.49.0
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:** https://expensify.testrail.io/index.php?/tests/view/4408718
**Issue reported by:** Applause - Internal Team

## Action Performed:
1. Go to https://staging.new.expensify.com/ on Android
2. Tap the Expensify icon in the upper left corner of the page > click the gray '+' to create a new workspace
3. Create a new workspace
5. Tap members
6. Tap Invite Member > enter a test email address > tap Next > click Invite
7. Click the chat icon in the lower left corner to go back to all chats for the new workspace
9. Tap on the chat thread with the invited member 
10. Navigate back to LHN
11. Tap Expensify icon on top left (to view Everything)
12. Tap settings---Workspaces at bottom

## Expected Result:

Notice the new workspace has disappeared 

## Actual Result:

After opening an invited user's individual workspace chat and then going back to all workspace - the workspace disappears

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [x] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [ ] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

https://github.com/Expensify/App/assets/93399543/f294fa96-6f06-49d5-8052-dbbf6d39f740

https://github.com/Expensify/App/assets/51066321/0f1a553c-b332-4671-9de5-f5da46a4da9c

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~014bfff6a67be55913</li>
        <li>Upwork Job ID: 1767024388081385472</li>
        <li>Last Price Increase: 2024-03-11</li>
    </ul>
</details>

**Comment by kbecciv** [comment] 2024-03-08 15:04
@Christinadobrzyn I haven't added the External label as I wasn't 100% sure about this issue. Please take a look and add the label if you agree it's a bug and can be handled by external contributors.

**Comment by Christinadobrzyn** [comment] 2024-03-11 03:06
Ah good catch - I think this can be external and could be part of vip-vsb.

**Comment by Christinadobrzyn** [comment] 2024-03-13 03:36
looking for proposals!

**Comment by KMichel1030** [comment] 2024-03-13 07:40
Hi, @Christinadobrzyn 
I'm afraid I can't reproduce on my end. Could you please confirm the issue?

**Comment by Christinadobrzyn** [comment] 2024-03-13 07:50
Ah thanks for testing @KMichel1030 - I just tested again and I can't reproduce the issue either! 

I'll reach out to our QA team to confirm this issue is resolved. I'll follow up here with the revised steps if they can reproduce this issue.

**Comment by kbecciv** [comment] 2024-03-13 12:20
Issue is no loner reproduced! 

https://github.com/Expensify/App/assets/93399543/8492ea7c-ab86-497a-8b53-634272d51440

**Comment by Christinadobrzyn** [comment] 2024-03-14 02:21
awesome! going to close this!

**Closed by Christinadobrzyn** 2024-03-14 02:21 UTC
Labels: External, Daily, Help Wanted, Bug
