### ISSUE TITLE
[HOLD for payment 2024-01-24] [$500] Profile - No profile image displayed for specific users in header&profile page

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#33452] opened 2023-12-21 21:00 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.15-4
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** Applause - Internal Team
**Slack conversation:**

## Action Performed:
1. Go to https://staging.new.expensify.com/
2. Tap search
3. Scroll ,find and select user with green avatar as shown in below image
4. Note in header, profile image is not displayed
5. Tap on header
6. In profile page also, note profile image is not displayed

## Expected Result: 
Profile image must be displayed for specific users in both header and profile page. If no custom image set, default profile image must be displayed

## Actual Result:
No profile image displayed for specific user in both header and profile page

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [x] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details> 

https://github.com/Expensify/App/assets/78819774/2e497401-41ee-4b92-84a0-cc485e2e7535

![Bug6323045_1703182419900!Screenshot_2023-12-21-23-06-10-503_com Slack-edit](https://github.com/Expensify/App/assets/78819774/8569b5c6-df45-47a4-85a1-a4cd05845b87)

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01df3f6538112432f6</li>
        <li>Upwork Job ID: 1737941070550650880</li>
        <li>Last Price Increase: 2023-12-21</li>
<li>Automatic offers: </li>
<ul>
<li>gijoe0295 | Contributor | 28088902</li>
</ul></li>
    </ul>
</details>

**Comment by ahsanfarooq3423** [comment] 2023-12-21 23:02
The users are not listing for me. Am I missing something?
<img width="1421" alt="image" src="https://github.com/Expensify/App/assets/31133118/8fc2a874-5d23-4d38-9073-393df65678f7">

**Comment by ahsanfarooq3423** [comment] 2023-12-21 23:05
Contributor details
Your Expensify account email: im.amir107@gmail.com
Upwork Profile Link: https://www.upwork.com/freelancers/~0193e5107b52171fab

**Comment by Santhosh-Sellavel** [comment] 2023-12-25 19:08
@gijoe0295's [proposal](https://github.com/Expensify/App/issues/33452#issuecomment-1867016966) looks good to me.
Need some clarification on other possible prefixes waiting for CME's input on that! 

C+ Reviewed
🎀 👀 🎀

**Comment by Santhosh-Sellavel** [comment] 2023-12-25 19:09
@hayata-suenaga let me know your thoughts on [it](https://github.com/Expensify/App/issues/33548)

**Comment by Santhosh-Sellavel** [comment] 2023-12-25 19:10
@hayata-suenaga let me know your thoughts on https://github.com/Expensify/App/issues/33452#issuecomment-1869088973

**Comment by trjExpensify** [comment] 2024-01-03 10:47
@hayata-suenaga this one is waiting on your secondary review please!

**Comment by trjExpensify** [comment] 2024-01-05 01:04
Same Melv, awaiting @hayata-suenaga's secondary review!

**Comment by trjExpensify** [comment] 2024-01-08 11:29
Hayata is back today!

**Comment by hayata-suenaga** [comment] 2024-01-08 16:10
I'm back 👋 sorry for the wait everyone 🙇 

Let's go with @gijoe0295's proposal 👍

**Comment by hayata-suenaga** [comment] 2024-01-08 17:20
I'm not super familiar with the avatar URL prefixes. Whenever you have a question about a specific part of the App, the best place to ask is open-soource-channel of Slack 🙇

**Comment by Santhosh-Sellavel** [comment] 2024-01-25 18:02
**BugZero Checklist:** The PR fixing this issue has been merged! The following checklist ([instructions](https://stackoverflow.com/c/expensify/questions/14574)) will need to be completed before the issue can be closed:

* [x]  [@Santhosh-Sellavel] The PR that introduced the bug has been identified. Link to the PR: https://github.com/Expensify/App/pull/32090
* [x]  [@Santhosh-Sellavel] The offending PR has been commented on, pointing out the bug it caused and why, so the author and reviewers can learn from the mistake. Link to comment: https://github.com/Expensify/App/pull/32090/files#r1466714675
* [x]  [@Santhosh-Sellavel] A discussion in #expensify-bugs has been started about whether any other steps should be taken (e.g. updating the PR review checklist) in order to catch this type of bug sooner. Link to discussion: We can skip this, as this should have been while proposal/PR review.
* [x]  [@Santhosh-Sellavel] Determine if we should create a regression test for this bug. We can skip this 
* [x]  [@Santhosh-Sellavel] If we decide to create a regression test for the bug, please propose the [regression test](https://github.com/Expensify/App/blob/main/contributingGuides/REGRESSION_TEST_BEST_PRACTICES.md) steps to ensure the same bug will not reach production again. N/A
* [x]  [@trjExpensify] Link the GH issue for creating/updating the regression test once above steps have been agreed upon:

**Comment by trjExpensify** [comment] 2024-01-25 21:26
Yo! When you answer N/A can you provide reasoning?

**Comment by trjExpensify** [comment] 2024-01-25 21:39
In the meantime, confirming payments are as follows: 

- $500 to @gijoe0295 for the fix
- $500 to @Santhosh-Sellavel for the review

**Comment by Santhosh-Sellavel** [comment] 2024-01-25 22:12
> Yo! When you answer N/A can you provide reasoning? 
> 
> 

We are skipping Regression so N/A for the 5th iten. Added more reasoning why we can skip it.

**Comment by trjExpensify** [comment] 2024-01-25 23:36
Nice one, thanks for expanding on the reasoning. Makes sense! 

Feel free to request. @gijoe0295 you've been paid!

**Closed by trjExpensify** 2024-01-25 23:36 UTC
Labels: External, Weekly, Awaiting Payment, Bug

**Comment by Santhosh-Sellavel** [comment] 2024-02-10 20:38
Requested on ND

**Comment by JmillsExpensify** [comment] 2024-02-11 13:06
$500 approved for @Santhosh-Sellavel based on summary above.
