### ISSUE TITLE
[HOLD #11768] [$8000]  The Back ⌘[ and Forward ⌘] shortcuts keys are not working as expected when navigating via RHN (Right Hand Navigation)

### ISSUE THREAD

**Issue by mallenexpensify** [Expensify/App#8657] opened 2022-04-16 00:31 UTC
[BELOW IS THE PROCESS OF BEING EDITED/UPDATED AND IS ON HOLD]

If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___
Breaking this off from https://github.com/Expensify/App/issues/4612, that issue will be focused solely on LeftHandNav (LHN) and this one is for the navigation in RHN (or RHP - Pane)

## Action Performed:
- Open the app on the Web or desktop.
- Open Search/Chat Switch (⌘+k shortcut)
- Navigate to some chat P.
- Open the Search Page again and navigate to some chat Q.
- Open the Search Page again and navigate to some chat R.
- Open the Search Page again and navigate to some chat Q.
- Use the back ⌘[ and Forward ⌘] shortcuts to go to previous and forwards chats respectively.
- You can navigate to any number to chats.

## Expected Result:
When we open reports from RHN, Back ⌘[ and Forward ⌘] shortcuts should work and navigate through the previously navigated conversations in the main/focused chat view. ie. if I visit chats with Joanie, Alex then Daniel, I expect ⌘[ to take me from my chat with Daniel back to Alex then ⌘[ again back to Joanie. Most-everywhere else the back/forward actions follow a standard flow.

RHN contains navigating via Search Page, New Chat Page, or any other modal.

Back `⌘[` and Forward `⌘]` shortcuts should work and navigate through the previously navigated conversations **in the main/focused chat view.** ie. if I visit chats with Joanie, Alex then Daniel, I expect `⌘[` to take me from my chat with Daniel back to Alex then `⌘[` again back to Joanie. Most-everywhere else the back/forward actions follow a standard flow. 

## Actual Result:
Shortcuts are not working as expected. 

## Workaround:
User has to manually navigate through the conversations. ie. If using keyboard navigation you always have to `⌘k`, start typing a name, then `return` to navigate

## Platform:

Where is this issue occurring?

- Desktop App

**Version Number:** Version 1.1.57-0 

**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Notes/Photos/Videos:** Any additional supporting documentation
Unable to get a video atm. Will update with video later. 
Other job for LHN navigation issue https://github.com/Expensify/App/issues/4612

**Expensify/Expensify Issue URL:**

[View all open jobs on Upwork](https://www.upwork.com/ab/jobs/search/?q=Expensify%20React%20Native&sort=recency&user_location_match=2)

___ 
From @mallenexpensify https://expensify.slack.com/archives/C01GTK53T8Q/p1628722621224600
> The Back ⌘[ and Forward ⌘] shortcuts keys don't work properly on Desktop Version 1.0.82-7

**Comment by mallenexpensify** [comment] 2022-04-16 00:38
Job posted https://www.upwork.com/jobs/~0173c88d53b4915da6

**Comment by Salehmrcp** [comment] 2022-04-16 00:53
It is js coding issue
i can fix it easy

**Comment by parasharrajat** [comment] 2022-04-18 07:30
@Salehmrcp Can you post a proposal? Please look at CONTRIBUTING.md for me.

**Comment by Salehmrcp** [comment] 2022-04-18 07:34
I have submitted a proposal in upwork- under name hwaida mohamed
I looked also at the file

**Comment by NikkiWines** [comment] 2022-04-18 16:35
@Salehmrcp, per the guidelines [here](https://github.com/Expensify/App/blob/main/CONTRIBUTING.md#propose-a-solution-for-the-job) you need to do the following: 

> After you reproduce the issue, make a proposal for your solution and post it as a comment in the corresponding GitHub issue (linked in the Upwork job). Your solution proposal should include a brief technical explanation of the changes you will make.

**Comment by Salehmrcp** [comment] 2022-04-18 17:41
Thanks nikki
But I can not even write the solution before I am hired
My upwork link is here
https://www.upwork.com/freelancers/~010501fb0f15f0e713?viewMode=1
Kindly hire me first to start

**Comment by mdneyazahmad** [comment] 2022-04-24 09:34
## Proposal

`DrawerNavigtor` has `history` prop that is used to store the routes visited and it also stores the drawer status `(open or closed)`. There is a catch here `history` can contain drawer status object or not. It is based on the `defaultStatus` of the `DrawerNavigator`. 
1. It does not contain this object if the current status of the drawer is same as `defaultStatus`.
2. It contains an object `{ type: 'drawer, status: 'open' | 'closed' }` if current status is not same as `defaultStatus`.

https://github.com/Expensify/App/blob/ad637d3dd7dbb03cfdc6ebcb9196944c4f6165bb/src/libs/Navigation/AppNavigator/BaseDrawerNavigator.js#L63

`StyleUtils .getNavigationDrawerType` returns either `slide` or `permanent`. When `drawerType` is set to `permanent` it always displays the drawer irrespective of the status of drawer in state object.

We can safely provide `defaultStatus = "open"` as this is the value for small screen and it does not have any effects on large screen. In this case `history` will contain `{ type: 'drawer, status:  'closed' }` for `closed` state of the drawer and it will be removed from history if the status is `open`.

https://github.com/Expensify/App/blob/ad637d3dd7dbb03cfdc6ebcb9196944c4f6165bb/src/libs/Navigation/AppNavigator/BaseDrawerNavigator.js#L57

```diff
-                defaultStatus={this.state.defaultStatus}
+                defaultStatus="open"
```

`pushDrawerRoute` is only called when the path is `r/:reportId`. We are sure at this point that we should close the drawer as it goes to the report. As the default status of the drawer is `open`, history must contain an object `{type: 'drawer', status: 'closed'}`. Again it does not have any effects on large screen that will always be opened as the `drawerType` is set to permanent on large screen.

https://github.com/Expensify/App/blob/ad637d3dd7dbb03cfdc6ebcb9196944c4f6165bb/src/libs/Navigation/CustomActions.js#L106-L113


 ```diff

-        const hasDrawerhistory = _.find(state.history || [], h => h.type === 'drawer');
+        const isDrawerInHistory = _.some(history || [], h => h.type === 'drawer');

+        if (!isDrawerInHistory) {
+            history.push({
+                type: 'drawer',
+                status: 'closed',
+            });
+         }
 
```

### Result:

https://user-images.githubusercontent.com/77761491/164969923-86b2e915-f48d-433a-a8b6-3671bf425072.mp4

**Comment by mdneyazahmad** [comment] 2022-04-24 10:02
@parasharrajat I may not be correct here but the original issue has problem with shortcut key when we navigate with search page. But later on @rushatgabhane has identified another bug (this one) that was working previously https://github.com/Expensify/App/issues/4612#issuecomment-1077024583

If you are not satisfied with my proposal let me know I will add more context to it and explain the root cause. Thank you

**Comment by metehanozyurt** [comment] 2022-04-24 10:17
### Proposal 
We mapping history state this line but not use it for drawer check. So it can be skip 1 person when click from list and not push to history list.

https://github.com/Expensify/App/blob/ad637d3dd7dbb03cfdc6ebcb9196944c4f6165bb/src/libs/Navigation/CustomActions.js#L101

we don't use the mapping we did before

###Solution
if we change like this this can be fix problem

https://github.com/Expensify/App/blob/ad637d3dd7dbb03cfdc6ebcb9196944c4f6165bb/src/libs/Navigation/CustomActions.js#L105

```JS
     const hasDrawerhistory = _.find(history || [], h => h.type === 'drawer');
```

**Comment by mdneyazahmad** [comment] 2022-04-24 10:28
## Root cause:

Let's add `console.log('hsitory', history)` here and navigate to multiple reports.

https://github.com/Expensify/App/blob/ad637d3dd7dbb03cfdc6ebcb9196944c4f6165bb/src/libs/Navigation/CustomActions.js#L114

<img width="504" alt="Screenshot 2022-04-24 at 3 18 29 PM" src="https://user-images.githubusercontent.com/77761491/164971527-de97ed6a-c3c0-4943-9ea1-25978a7976ee.png">

As we can see that drawer object is alternatively added and hence `history.length` does not change for every two navigation. 

`react-navigation` calculates history delta here which comes out to be `0` for every two navigation and hence it does not push to to browser history.
https://github.com/react-navigation/react-navigation/blob/4c2b69f2e339e21714a841f4e8e9e3d5c7120269/packages/native/src/useLinking.tsx#L569


The  drawer status does not change in these navigation. It should check against `history` and not `state.history`

https://github.com/Expensify/App/blob/ad637d3dd7dbb03cfdc6ebcb9196944c4f6165bb/src/libs/Navigation/CustomActions.js#L105

**Comment by mdneyazahmad** [comment] 2022-04-24 10:53
@metehanozyurt Could you please not edit? You can create a new comment or else it won't be fair for other contributer you keep editing and claim to be the first to propose a better solution. Thanks

**Comment by metehanozyurt** [comment] 2022-04-24 11:18
ofcourse @mdneyazahmad it can be visible first proposal and edited version("video upload"). both version before your last message. When i see your commit after upload image i didnt touch anything. Sorry for the time conflict. I was also looking. Thank you

**Comment by mdneyazahmad** [comment] 2022-04-24 11:20
I am sorry @mallenexpensify I was unaware about the this feature (we can see edited history).

**Comment by mdneyazahmad** [comment] 2022-04-24 12:02
The reason I added a static `defaultState`:
1. It does not matter for large screen as drawerType is permanent.
2. When user starts with browser resized it has default status of `closed` on large screen and when user starts with full width it has `defaultStatus` of `open` on large screen. It has two different value on web for the same drawer on large screen.


https://user-images.githubusercontent.com/77761491/164975288-e5a2e9e8-ddc6-4fa6-bc0f-874372f98057.mp4

**Comment by parasharrajat** [comment] 2022-04-24 18:09
I am confused by the description of this issue. I will confirm the expected behavior here and get back to you guys.

**Comment by parasharrajat** [comment] 2022-04-26 15:03
Discussing now..

**Comment by mallenexpensify** [comment] 2022-04-26 21:33
Updated these in OP

## Expected Result:
Back `⌘[` and Forward `⌘]` shortcuts should work and navigate through the previously navigated conversations **in the main/focused chat view.** ie. if I visit chats with Joanie, Alex then Daniel, I expect `⌘[` to take me from my chat with Daniel back to Alex then `⌘[` again back to Joanie. Most-everywhere else the back/forward actions follow a standard flow. 

## Workaround:
User has to manually navigate through the conversations. ie. If using keyboard navigation you always have to `⌘k`, start typing a name, then `return` to navigate

To oversimplify, `⌘[` and `⌘]` should work the same for back/forward and any/everywhere else (ie. browser, Slack)

**Comment by mallenexpensify** [comment] 2022-04-27 21:50
I'm confused.  I think I see what you're saying @parasharrajat. Few items I'd like to get confirmation on. 

1. I broke the two up to be LHN and main chat window but those should always be synced when navigating, is that correct?
2. If so, I think the https://github.com/Expensify/App/issues/4612 should be the main issue for LHN/Main navigating as expected.  do you agree?
3. And... for this issue, I don't think there's a specific example for navigating via search/chat switcher that wouldn't be addressed and fixed in #4612 (since it shouldn't/wouldn't matter if the actions performed for selecting chats to cycle through is done via clicking a name in LHN or using the chat switcher). Agreed.
4. For this specific issue, do you think it should focus on when/how the RHN is surfaced and how back/forward navigation works with RHN? And... should we take into account both Search/Chat switcher and Settings? 
Also... for #4, we could put/keep this on hold til #4612 is finished then revisit?

**Comment by parasharrajat** [comment] 2022-04-28 15:39
1. Yes. There is no issue with the main chat. Instead, there are issues with navigating via LHN and RHN.
2. Yes
3. No, root cause behind not working shortcuts needs to be fixed for both LHN and RHN. 
4. Yes.

**Comment by mallenexpensify** [comment] 2022-04-28 21:22
Thanks @parasharrajat. I'm going to leave this on hold for now (and not update the OP yet, in case the fix in #4612 magically fixes RHN too.  )

**Comment by mallenexpensify** [comment] 2022-05-11 19:15
On hold, pinged [other ](https://github.com/Expensify/App/issues/4612) issue to get proposal reviewed

**Comment by parasharrajat** [comment] 2022-05-17 17:02
@mallenexpensify we can remove the hold from this. I am reviewing the previous proposals. Based on the new expected behavior, the old proposal applies to the other issue, not this one but it seems that they are fixing both issues. @mdneyazahmad your proposal is best suited for https://github.com/Expensify/App/issues/4612. 

Could you please run the steps from https://github.com/Expensify/App/issues/8657#issuecomment-1111015235 and let me know what is outcome? 

@metehanozyurt your proposal has an [problem](https://github.com/Expensify/App/issues/4612#issuecomment-1129094159). 

Also, I would like to know why did we use the dynamic default status in the first place. What difference does that make? Will this change affect the selected proposal on https://github.com/Expensify/App/issues/8126? 

Is there any effect of your proposal on https://github.com/Expensify/App/issues/7618?

**Comment by mallenexpensify** [comment] 2022-05-17 22:49
Thanks @parasharrajat , took off hold, added `Help Wanted` label and created a new Upwork job.  Let's leave at $8k for a bit while you continue to review proposals Rajat .
https://www.upwork.com/jobs/~018d0820ec4f3aaef7

**Comment by mdneyazahmad** [comment] 2022-05-18 10:13
I think the title is changed after my proposal is posted. So now, this will be a proposal for the other issue (#4612).

---

> Could you please run the steps from https://github.com/Expensify/App/issues/8657#issuecomment-1111015235 and let me know what is outcome?

This only fixes one of the issues which is when we navigate with LHN and it does not fix the other issue (with the search page navigation).

---

> Also, I would like to know why did we use the dynamic default status in the first place. What difference does that make?

Not sure, why but it makes much sense to have it dynamic (default open for the small screen and default closed for the large screen). But, in the end, it does not matter for a large screen because of the permanent drawer.

---

> Will this change affect the selected proposal on https://github.com/Expensify/App/issues/8126?

I will test and let you know in a few hours but it seems like it does not affect that proposal and have to refactor some of the code on the selected proposal to accept the incoming changes from my proposal.

---

> Is there any effect of your proposal on https://github.com/Expensify/App/issues/7618?

I think it does not affect that.

cc: @parasharrajat

**Comment by parasharrajat** [comment] 2022-05-18 13:26
> Also, I would like to know why did we use the dynamic default status in the first place. What difference does that make?

Please do some research on this. I would not proceed to change it until we know what we are changing. It must have some effect as it is present in the code. 

Also, your proposal is forcing us to use fixed `defaultStatus`. Could you try to find a way so that it can be dynamic? Then we don't have to worry about changing it to open. If you notice that old code is dynamic in nature.

**Comment by marcaaron** [comment] 2022-05-18 21:01
Can we please fix all of these issues in `react-navigation`?

**Comment by marcaaron** [comment] 2022-05-18 21:05
Pretty concerned by this issue and others related to navigation. It seems like a colossal waste to invest this much time, energy and money on temporary hacks. I'm not sure we should invest in our custom actions anymore without taking a more serious look at all the navigation issues we are experiencing and coming up with a holistic plan to solve them.

**Comment by mallenexpensify** [comment] 2022-05-25 17:57
Want to put this on hold for now then @marcaaron , @NikkiWines , @parasharrajat ?  
I think we want navigation to work correctly, it makes since to come up with a holistic plan. Having he [Navigation project](https://github.com/Expensify/App/projects/2#card-82119210) will be helpful for organizing

**Comment by marcaaron** [comment] 2022-05-25 20:38
That sounds good to me. I have a lot of thoughts regarding:

- How the current navigation works (very messy in spots)
- Whether it is something that can be proposed as a feature to `react-navigation` or not
- If not, whether we can develop a solid custom navigator to get around issues and design it with a particular wish list in mind - hopefully with some insight and feedback from the maintainers
- Which direction is right for us in the long term?

It's a good time to step back and reflect on these I think.

**Comment by NikkiWines** [comment] 2022-06-27 16:11
on hold

**Comment by NikkiWines** [comment] 2022-09-05 08:14
still on hold

**Comment by NikkiWines** [comment] 2022-10-10 08:26
Unassigning myself while these are on hold since there's nothing actionable at this time

**Comment by JmillsExpensify** [comment] 2022-11-03 18:37
Snagging this now that I'm in the tracking issue.

**Comment by JmillsExpensify** [comment] 2022-11-06 20:51
See the tracking issue for the latest.

**Comment by JmillsExpensify** [comment] 2022-11-17 04:33
Still holding.

**Comment by JmillsExpensify** [comment] 2022-11-22 07:15
Still held as this initiative goes through the design process.

**Comment by JmillsExpensify** [comment] 2022-11-27 06:39
Still holding on the larger react navigation project.

**Comment by JmillsExpensify** [comment] 2022-12-05 13:51
Still on hold for the larger navigation re-write.

**Comment by JmillsExpensify** [comment] 2022-12-27 21:30
Same as above.

**Comment by JmillsExpensify** [comment] 2023-01-11 05:53
Still on hold for navigation. No ETA.

**Comment by JmillsExpensify** [comment] 2023-02-14 06:21
Same same

**Comment by JmillsExpensify** [comment] 2023-03-29 07:32
Still on hold.

**Comment by JmillsExpensify** [comment] 2023-05-03 05:02
Still on hold

**Comment by JmillsExpensify** [comment] 2023-06-07 05:03
Coming off hold very soon!

**Comment by JmillsExpensify** [comment] 2023-07-12 13:28
Ok I'm coming back to this one now but we don't officially support this type of keyboard navigation so I'm closing. Keyboard navigation is a new feature and one day will be an initiative.

**Closed by JmillsExpensify** 2023-07-12 13:28 UTC
Labels: Engineering, Monthly, Planning, Overdue, Bug

**Comment by JmillsExpensify** [comment] 2023-07-27 05:15
Quick clarification: Based on the Contributor+ work @parasharrajat did to review and manage this issue, he's eligible for a 25% payment as a result.

**Comment by JmillsExpensify** [comment] 2023-07-27 05:16
Additionally, this issue is eligible and approved and payment on NewDot.
