### ISSUE TITLE
[HOLD for payment 2022-12-08] [$1000] Text select cursor is not appearing when selecting text in the messages

### ISSUE THREAD

**Issue by kavimuru** [Expensify/App#12961] opened 2022-11-23 17:16 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:

1. Go to https://staging.new.expensify.com/
2. Select a report
3. Send some messages
4. Hover the cursor on the text, and try to select

## Expected Result: 
There should be text select cursor

## Actual Result: 
There is a normal cursor

## Workaround:
unknown

## Platform:

Where is this issue occurring?

- Web
- Desktop App

**Version Number:** 1.2.30-0
**Reproducible in staging?:** y
**Reproducible in production?:** y
**Email or phone of affected tester (no customers):** 
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** 

https://user-images.githubusercontent.com/43996225/203608743-f29d9a8e-13d9-435a-802b-172e13d853c7.mov
https://user-images.githubusercontent.com/43996225/203608747-ae20b022-94fb-4b21-9b27-ff5d82e91405.mov
https://user-images.githubusercontent.com/43996225/203608784-dd006742-29a4-49c6-9fa4-d3f8e1adc1c0.mp4

**Expensify/Expensify Issue URL:** 
**Issue reported by:** @mdneyazahmad 
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1669180673869489

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

## Upwork Automation - Do Not Edit
- Upwork Job URL: https://www.upwork.com/jobs/~01ffa8602538b38e84
- Upwork Job ID: 1597308530847031296

**Comment by s77rt** [comment] 2022-11-25 19:42
### Proposal
```diff
diff --git a/src/styles/styles.js b/src/styles/styles.js
index a7642d64ad..fec3271003 100644
--- a/src/styles/styles.js
+++ b/src/styles/styles.js
@@ -1334,6 +1334,7 @@ const styles = {
         marginTop: -2,
         marginBottom: -2,
         maxWidth: '100%',
+        cursor: 'text',
         ...whiteSpace.preWrap,
         ...wordBreak.breakWord,
     },
```

### Details
Add `cursor` style prop and set it to `text` on `chatItemMessage` class.

**Comment by tjferriss** [comment] 2022-11-28 19:18
@sobitneupane looks like we have an initial proposal to review. Can you take a look?

**Comment by roryabraham** [comment] 2022-11-29 06:08
Tested it out and @s77rt's proposal works great.

**Comment by sobitneupane** [comment] 2022-11-29 06:33
[Proposal](https://github.com/Expensify/App/issues/12961#issuecomment-1327836490) from @s77rt looks good to me as well.

🎀👀🎀 C+ reviewed

**Comment by s77rt** [comment] 2022-11-29 06:36
Applied in [Upwork](https://www.upwork.com/jobs/~016a93b6c4cd78cf62) (+50% bonus)
[PR](https://github.com/Expensify/App/pull/13120) is ready

**Comment by tjferriss** [comment] 2022-11-29 18:40
@s77rt I've just hired you in Upworks. @sobitneupane I've invited you to apply to the posting in Upworks. Please let me know here once you've applied.

**Comment by roryabraham** [comment] 2022-11-29 20:36
PR merged

**Comment by sobitneupane** [comment] 2022-11-30 02:40
> Please let me know here once you've applied.

@tjferriss Applied.

**Comment by mdneyazahmad** [comment] 2022-11-30 07:11
@tjferriss I see there are two jobs created for this issue https://github.com/Expensify/App/issues/12961#issue-1462127880. Which one should I apply as a reporter? Thanks!

**Comment by tjferriss** [comment] 2022-11-30 21:05
Weird. I don't know how we ended up with a duplicate. Please use this posting: 

- Upwork Job URL: https://www.upwork.com/jobs/~01ffa8602538b38e84
- Upwork Job ID: 1597308530847031296

**Comment by tjferriss** [comment] 2022-12-01 19:49
Ok everyone has been hired in Upworks. Payments will be made after the 7-day regression period. @s77rt is eligible for a 50% bonus.

**Comment by sobitneupane** [comment] 2022-12-02 04:22
@tjferriss I am also eligible for 50% bonus as C+.

**Comment by tjferriss** [comment] 2022-12-05 19:50
Yes, thank you. I'll pay out your bonus once we're out of the hold period.

**Comment by tjferriss** [comment] 2022-12-08 22:10
Payments have been sent. @sobitneupane / @roryabraham can you please complete the remaining tasks [here](https://github.com/Expensify/App/issues/12961#issuecomment-1333985405)? Then we should be ready to close this out.

**Comment by sobitneupane** [comment] 2022-12-09 03:40
> **BugZero Checklist:** The PR fixing this issue has been merged! The following checklist ([instructions](https://stackoverflow.com/c/expensify/questions/14574)) will need to be completed before the issue can be closed:
> 
> * [ ]  [@sobitneupane / @roryabraham] The PR that introduced the bug has been identified. Link to the PR:

This was probably present from very beginning. 

> * [ ]  [@sobitneupane / @roryabraham] The offending PR has been commented on, pointing out the bug it caused and why, so the author and reviewers can learn from the mistake. Link to comment:

I don't think this was a mistake.

> * [ ]  [@sobitneupane / @roryabraham] A discussion in #expensify-bugs has been started about whether any other steps should be taken (e.g. updating the PR review checklist) in order to catch this type of bug sooner. Link to discussion:

No action needed here. We were probably missing this feature from very beginning. I see very less chance of this issue resurfacing again.

**Closed** 2022-12-12 18:12 UTC
Labels: External, Weekly, Awaiting Payment, Bug
