### ISSUE TITLE
[HOLD for payment 2023-07-12] [HOLD for payment 2023-07-10] [$1000] Date is not being displayed correctly when single digit day is entered

### ISSUE THREAD

**Issue by kavimuru** [Expensify/App#21404] opened 2023-06-23 13:48 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Login to ND
2. Open Settings
3. Open Profile
4. Open Personal Details
5. Click on Date of Birth
6. Choose the date 1 June, 2023 > Save Changes
## Expected Result: 
The date is fully visible
## Actual Result: 
The date is not fully visible
## Workaround:
Can the user still use Expensify without this being fixed? Have you informed them of the workaround?

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [x] iOS / Safari
- [ ] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 1.3.31-2
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/43996225/e1634fff-adeb-4ca7-8f0e-bcc607991bcf

https://github.com/Expensify/App/assets/43996225/0ad19c55-d1d7-43dc-99b1-741d3826b7c2

**Expensify/Expensify Issue URL:**
**Issue reported by:** @aman-atg 
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1686991387615589

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01046c3f7c49b615ed</li>
        <li>Upwork Job ID: 1673481863409926144</li>
        <li>Last Price Increase: 2023-06-27</li>
    </ul>
</details>

**Comment by kevinksullivan** [comment] 2023-06-23 14:14
taking to slack thread since I cannot reproduce

![IMG_F971FD29952A-1](https://github.com/Expensify/App/assets/22508290/a1a57042-3852-4dc1-9a62-2633ed59e6e9)

**Comment by Pujan92** [comment] 2023-06-26 13:35
@kevinksullivan It gets truncated when you select a date between 1 to 9.

**Comment by kevinksullivan** [comment] 2023-06-27 00:02
ha, got it. I updated the steps to make that a bit clearer.

**Comment by kevinksullivan** [comment] 2023-06-27 00:02
Reproduced and sending to the pool

**Comment by mananjadhav** [comment] 2023-06-27 03:29
@dukenv0307's proposal [here](https://github.com/Expensify/App/issues/21404#issuecomment-1608574056) looks good. I think we should focus on `MenuItem` because this itself will require testing across the app where we're using the component.

🎀 👀 🎀  C+ reviewed

**Comment by manjesh-yadav** [comment] 2023-06-27 06:38
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
Date is not being displayed correctly when single digit day is entered
### What is the root cause of that problem?
The actual problem with our `ExpensifyNeue and ExpensifyMono` font, In our font whitespace is not handled for the IOS Safari browser. When you change the font which is supported like `14px -apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, Helvetica, Arial, sans-serif` it's works fine

**We do not set `Text` component with full width or flex as proposed above it causes another problem when we use this with the icon, we already used it in 'src/components/MoneyRequestHeader.js:187'**

![WhatsApp Image 2023-06-27 at 11 43 05 AM](https://github.com/Expensify/App/assets/70934016/73cf6aaa-27bc-4f6c-a38c-1298fc0829a3)

### What changes do you think we should make in order to solve the problem?

When we set `white-space: pre` whitespace is preserved by the browser and the browser handled itself and it course problem

We can remove this style or replace a property `nowrap` then it's work normally and `Text` will wrap when necessary
[App/src/components/MenuItem.js](https://github.com/Expensify/App/blob/48d418784a599496205b237adf05088c78f3ee35/src/components/MenuItem.js#L83)
```diff
-  styles.pre
```
or 
```diff
-  styles.pre
+ styles.noWrap
```

It always works fine in a single line because we already use `numberOfLines={1}`

<details>

<summary> Result</summary>

![WhatsApp Image 2023-06-27 at 11 59 30 AM](https://github.com/Expensify/App/assets/70934016/30a9386d-18a4-4d4e-8a80-da38bca1b169)

![WhatsApp Image 2023-06-27 at 11 59 40 AM](https://github.com/Expensify/App/assets/70934016/2e12a2c7-c561-4101-a809-c372cc4668c8)

![IMG_CA4152CF997C-1](https://github.com/Expensify/App/assets/70934016/9b1648ef-e608-45b0-baf4-8f90ed581a01)


</details>

### What alternative solutions did you explore? (Optional)

1. Change our font family
2. Correct whitespace of our `ExpensifyNeue and ExpensifyMono` font

**Comment by kevinksullivan** [comment] 2023-06-27 15:04
Hi @dukenv0307 , what melvin said ^ 😄 . Please apply for the job in upwork as I'm not sure what your name would be for searching it. Thanks!

**Comment by kevinksullivan** [comment] 2023-06-27 15:05
Offer sent for C+ @mananjadhav

**Comment by kevinksullivan** [comment] 2023-06-28 22:14
Offer accepted @dukenv0307

**Comment by kevinksullivan** [comment] 2023-06-28 22:15
Offer sent for reporting @aman-atg

**Comment by manjesh-yadav** [comment] 2023-06-29 20:04
it seems to have regression after merging this PR https://github.com/Expensify/App/pull/21769 see screenshots
Before this PR
<img width="408" alt="IMG_C0C9A383A245-1" src="https://github.com/Expensify/App/assets/70934016/606520a0-0016-4adc-92d8-69ab1a912465">

After this PR
![IMG_0512](https://github.com/Expensify/App/assets/70934016/f18b34ba-e40d-4e08-bf2d-55f17e6996f9)


I already mentioned in my proposal https://github.com/Expensify/App/issues/21404#issuecomment-1608883983 about this issue and tagged C +, I wonder why even did not notice and assign to first proposal May be fastest finger first is the game :smiley: 

CC @mananjadhav @kevinksullivan @dukenv0307

**Comment by mananjadhav** [comment] 2023-06-29 21:34
@manjesh-yadav That's on me, I won't say I missed your comment, I was assuming flex basis would cover it. Thanks for reporting the issue.

@dukenv0307 can we please take a look at the regression?

**Comment by kevinksullivan** [comment] 2023-07-06 21:07
@mananjadhav please complete the steps above so we can pay this on time. Thanks!

**Comment by kevinksullivan** [comment] 2023-07-10 16:58
Bumping this @mananjadhav

**Comment by mananjadhav** [comment] 2023-07-10 17:05
@kevinksullivan I was just on the checklist. Here's the offending [PR](https://github.com/Expensify/App/pull/19524/files). I think there isn't any need for adding a regression test here. But I've posted a comment on the [PR](https://github.com/Expensify/App/pull/19524/files#r1258605054).

Also I want to confirm if there would be a paycut for this issue, as we tried to fix it before it hit the staging. But we didn't merge it sooner and intentionally didn't apply CP:Staging.

**Comment by kevinksullivan** [comment] 2023-07-10 17:55
>Also I want to confirm if there would be a paycut for this issue, as we tried to fix it before it hit the staging. But we didn't merge it sooner and intentionally didn't apply CP:Staging.

Can you elaborate on this @mananjadhav ? So the PR was opened, and then intentionally not merged within the 3 days, even though it was done? Or what happened exactly?

**Comment by mananjadhav** [comment] 2023-07-15 03:42
@kevinksullivan did you get a chance to look at the previous comment?

**Comment by mananjadhav** [comment] 2023-07-17 16:49
@kevinksullivan Yes the standard 1000$.

**Comment by mananjadhav** [comment] 2023-07-18 14:39
@kevinsullivan did you get a chance to look at my previous comment? This is pending for payout.

**Comment by kevinsullivan** [comment] 2023-07-18 16:09
> @kevinsullivan did you get a chance to look at my previous comment? This is pending for payout.

Please let know what I need to do
 Thank you. Kevin

**Comment by mananjadhav** [comment] 2023-07-18 16:44
Apologies for the issue. Yes I meant to tag @kevinksullivan

**Comment by kevinksullivan** [comment] 2023-07-19 13:08
Paid out

**Closed by kevinksullivan** 2023-07-19 13:08 UTC
Labels: External, Daily, Awaiting Payment, Bug

**Comment by mananjadhav** [comment] 2023-07-19 13:15
Thanks the payout @kevinksullivan.  Is it possible to do a refund without additional charges? I am currently raising requests from NewDot.

**Comment by kevinksullivan** [comment] 2023-07-19 13:19
So you already got paid for this in newdot @mananjadhav ?

**Comment by mananjadhav** [comment] 2023-07-19 14:00
DMed you @kevinksullivan.

**Comment by kevinksullivan** [comment] 2023-07-20 17:51
just sent a refund request @mananjadhav

**Comment by mananjadhav** [comment] 2023-07-20 17:53
Thanks @kevinksullivan.

**Comment by anmurali** [comment] 2023-07-21 19:07
Approved 1000 to Manan based on https://github.com/Expensify/App/issues/21404#issuecomment-1642052875, which has been refunded on Upwork!

**Comment by mananjadhav** [comment] 2023-07-29 08:35
@dukenv0307 We missed a case here, hence this isn't eligible for the timeline bonus.
