### ISSUE TITLE
[HOLD for #19298][$1000] Android/Desktop/Web - The checkbox doesn't revert to empty when reopening a task

### ISSUE THREAD

**Issue by mvtglobally** [Expensify/App#19157] opened 2023-05-17 23:11 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Create a task
2. Mark it as complete
3. Mark it as incomplete from the three dots
4. Mark it as complete
5. Back to main report chat
6. Click on :white_check_mark: twice or 3 times
7. Check LHN ( red dot will be present)

## Expected Result:
The red dot does not appear in LHN if the user reopened the task from main report

## Actual Result:
The red dot appears in LHN if the user reopened the task from main report, and the checkbox remains checked as if the task is complete. 

## Workaround:
unknown 

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [X] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [x] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 1.3.15.6
**Reproducible in staging?:** Y 
**Reproducible in production?:** N ( New feature )
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation 
Found when executing PR #18986

https://github.com/Expensify/App/assets/43995119/16f4677b-5b8c-41d2-929f-b07aabcc4ae4

https://github.com/Expensify/App/assets/59587260/1953605d-75ab-4209-9911-567de0ab9449

**Expensify/Expensify Issue URL:**
**Issue reported by:** Applause - Internal Team
**Slack conversation:**

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01cf66c70b8a76778c</li>
        <li>Upwork Job ID: 1659086518053605376</li>
        <li>Last Price Increase: 2023-06-01</li>
    </ul>
</details>

**Comment by kadiealexander** [comment] 2023-05-18 06:39
Reproduced on web chrome too, but not on desktop:

![image](https://github.com/Expensify/App/assets/59587260/9358b315-f6e8-4639-b5f8-05ea3a114857)

**Comment by Thanos30** [comment] 2023-05-18 12:26
## Proposal

### Please re-state the problem that we are trying to solve in this issue.

Marking a task as incomplete from the 3-dots menu leads to not being able to disable the task from the checkbox later on.

### What is the root cause of that problem?

The root cause of this problem is our logic to determine if a task is completed:
```
const isTaskCompleted =
        (props.taskReport.stateNum === CONST.REPORT.STATE_NUM.SUBMITTED && props.taskReport.statusNum === CONST.REPORT.STATUS.APPROVED) ||
        (props.action.childStateNum === CONST.REPORT.STATE_NUM.SUBMITTED && props.action.childStatusNum === CONST.REPORT.STATUS.APPROVED);
```
After marking the task as incomplete from the 3-dots menu, the taskReport does indeed show the task to be open again, but the childStateNum and childStatusNum mark the task as Completed.



### What changes do you think we should make in order to solve the problem?

In order to solve this problem, we should check the child state only if the taskReport data is not available.
```
const isTaskCompleted =
        props.taskReport ? (props.taskReport.stateNum === CONST.REPORT.STATE_NUM.SUBMITTED && props.taskReport.statusNum === CONST.REPORT.STATUS.APPROVED) :
        (props.action.childStateNum === CONST.REPORT.STATE_NUM.SUBMITTED && props.action.childStatusNum === CONST.REPORT.STATUS.APPROVED);
```

**Comment by jjcoffee** [comment] 2023-05-19 18:07
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
We want to avoid errors from the BE, which will show as the red dot in LHN.

### What is the root cause of that problem?
The FE is getting out of sync with the BE when it comes to the task's completion state, which results in the BE returning this error (`403 Incorrect report state`):

![image](https://github.com/Expensify/App/assets/27287420/367637a6-eae8-417b-8a2a-f53df62fb565)

This ultimately happens because pusher events (which update the completion state) are resolving in reverse order. You can actually reproduce this without switching to the main report chat, just by starting with a completed task, marking incomplete and then complete (quickly).

We are handling pusher updates here by attaching them to the `SequentialQueue`'s `currentRequest` promise:

https://github.com/Expensify/App/blob/fe8f91c9bf6b4cd604a6e8390fb1a8131aa4add7/src/libs/actions/User.js#L596-L602

This intention is to run those pusher updates in the order in which they arrive. However, when there are multiple push events happening in close succession, the promises we attach to get resolved in reverse. 

This only happens for multiple requests, as there are different `currentRequest` promises that we're attaching to, which don't get resolved until the whole batch completes. This is because `currentRequest` only returns `process()` when the request completes here:

https://github.com/Expensify/App/blob/2182d0cb6eee479fa1c4d6f3fd9dd9cc9e97adbf/src/libs/Network/SequentialQueue.js#L40-L45

And we only resolve once all `persistedRequests` are dealt with:

https://github.com/Expensify/App/blob/2182d0cb6eee479fa1c4d6f3fd9dd9cc9e97adbf/src/libs/Network/SequentialQueue.js#L34-L36

### What changes do you think we should make in order to solve the problem?
Since we actually want to wait for the current sequence of `persistedRequests` to complete (otherwise we'd be triggering in-between UI states), we actually want to wait until `process()` itself resolves the promise until we run our pusher callback.

So we can add a variable, say `let currentBatch = null;` at the top here:

https://github.com/Expensify/App/blob/2182d0cb6eee479fa1c4d6f3fd9dd9cc9e97adbf/src/libs/Network/SequentialQueue.js#L21

Then where we're actually calling `process()` we want to assign it to `currentBatch` here:

https://github.com/Expensify/App/blob/2182d0cb6eee479fa1c4d6f3fd9dd9cc9e97adbf/src/libs/Network/SequentialQueue.js#L82-L88

```
currentBatch = process().finally(() => {
```

And add a function we can hook into:

```
/**
 * @returns {Promise}
 */
function getCurrentBatch() {
	return currentBatch;
}
```

Which we then use here:

https://github.com/Expensify/App/blob/fe8f91c9bf6b4cd604a6e8390fb1a8131aa4add7/src/libs/actions/User.js#L598

to become `SequentialQueue.getCurrentBatch()`.

### What alternative solutions did you explore? (Optional)
I also looked at just queueing the pusher events using `QueuedOnyxUpdates.queueOnyxUpdates(pushJSON);` which would replace this whole block:

https://github.com/Expensify/App/blob/fe8f91c9bf6b4cd604a6e8390fb1a8131aa4add7/src/libs/actions/User.js#L598-L601

This tested well, but I was unsure how we'd then handle the `triggerNotifications` call there (maybe it could be moved to `SeqentialQueue`?).  This is also the same method we use here, for example:

https://github.com/Expensify/App/blob/2182d0cb6eee479fa1c4d6f3fd9dd9cc9e97adbf/src/libs/Middleware/SaveResponseInOnyx.js#L17-L19

**Comment by kadiealexander** [comment] 2023-05-23 03:55
@0xmiroslav any thoughts on the proposal above?

**Comment by kadiealexander** [comment] 2023-05-25 04:12
Updated the post after discussing the issue and expected behaviour [here](https://expensify.slack.com/archives/C02NK2DQWUX/p1684986067871389).

**Comment by jjcoffee** [comment] 2023-05-25 09:10
Yes, see the video below:

https://github.com/Expensify/App/assets/27287420/0cdac985-e790-4ab4-82b2-934705acd89e

**Comment by jjcoffee** [comment] 2023-05-25 09:18
@0xmiroslav My proposal would also fix the FE aspect of #16506 where they're dealing with emoji reactions disappearing/reappearing (see [this comment](https://github.com/Expensify/App/issues/16506#issuecomment-1562031532) where they're still having issues after BE changes). It has the same root cause (pusher events resolving in reverse order).

**Comment by tgolen** [comment] 2023-05-25 10:04
@jjcoffee I read through your proposal and this part is something I don't fully understand:

> when there are multiple push events happening in close succession, the promises we attach to get resolved in reverse.

I could see how they might resolve in random order (eg. since they are async requests), but reverse order doesn't make sense. Your solution doesn't appear to address this assumption at all, but merely work around it (or if it does, I am failing to see how it does).

It would be great if you could add a unit test to your solution which proves the bug and that the fix correctly resolves it.

**Comment by jjcoffee** [comment] 2023-05-25 14:56
@tgolen Sorry I realise now the wording in my proposal is a bit iffy! The main point is that even though the requests are async, if we're processing them together in a batch in `SequentialQueue`, promises attached to each request only resolve when the last request completes (because of the line `return process()`). This means a promise attached to the last request in the queue will always resolve first. If we remove the return and just `process()` instead the promises resolve in order and so push events also run in order, but this causes replay effects so didn't seem like the right solution.

I don't think it's a workaround to wait until the `SequentialQueue` is finished processing if that's what we actually want to do (to avoid replay effects). Otherwise the alt solution in my proposal is decent, I think! 

I have a jsfiddle that I used to help me wrap my head around this: https://codepen.io/Joel-Davies/pen/PoyLmmy?editors=0012 (includes both current behaviour and the fix). Hope that clears things up a bit more!

**Comment by tgolen** [comment] 2023-05-25 15:20
Thank you, I think that helps clear it up for me. I think if you just
reworded the root cause to explain it like you just did now would be a nice
improvement. I think I get that the solution is more inline with what was
originally intended.

**Comment by jjcoffee** [comment] 2023-05-26 08:49
@tgolen Thanks for the feedback, I've updated my [proposal](https://github.com/Expensify/App/issues/19157#issuecomment-1555046815) now. cc @0xmiroslav

**Comment by kadiealexander** [comment] 2023-05-30 01:51
@0xmiroslav any thoughts on the updated [proposal](https://github.com/Expensify/App/issues/19157#issuecomment-1555046815) here?

**Comment by kadiealexander** [comment] 2023-06-13 06:28
Still on hold! @0xmiroslav any thoughts on the above?

**Comment by sophiepintoraetz** [comment] 2023-06-22 04:25
@0xmiroslav - are you able to get to this please?

**Comment by jjcoffee** [comment] 2023-06-28 09:25
BE has [hit production](https://github.com/Expensify/App/issues/19298#issuecomment-1610981681) and I can no longer replicate any of the steps.

**Comment by kadiealexander** [comment] 2023-06-28 23:07
I also can't reproduce this anymore, going to close it as resolved. Please comment/reopen if you disagree!

**Closed by kadiealexander** 2023-06-28 23:07 UTC
Labels: External, Weekly, Bug
