### ISSUE TITLE
Workflow - No page found on approval workflow edit after approver delete

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#51101] opened 2024-10-18 17:14 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 9.0.50-7
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**If this was caught on HybridApp, is this reproducible on New Expensify Standalone?:**N/A
**If this was caught during regression testing, add the test name, ID and link from TestRail:** https://github.com/Expensify/App/issues/49954
**Issue reported by:** Applause - Internal Team

## Action Performed:
Precondition: create new workspace.
1. Go to Workspace > Members > Add two members
2. Enable workflow and add an approval workflow
3. Assign one member as a submitter and the other as an approver
4. Go to members and remove the approver from the workspace
5. Navigate to workflow and try to edit the approval workflow by clicking on it

## Expected Result:
The approval workflow doesn't respond to clicks or allow editing, and a console error appears when clicked

## Actual Result:
Hm.. it's not here page opens. Submitter is still visible in separate approval workflow field which make no sense as it's not editable

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Standalone
- [ ] Android: HybridApp
- [ ] Android: mWeb Chrome
- [ ] iOS: Standalone
- [ ] iOS: HybridApp
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

<details>
  <summary>Add any screenshot/video evidence</summary>

  
</details> 

https://github.com/user-attachments/assets/c770ab71-2ba2-48a3-a6ae-db228bc4b630

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by lanitochka17** [comment] 2024-10-18 17:15
@strepanier03  FYI I haven't added the External label as I wasn't 100% sure about this issue. Please take a look and add the label if you agree it's a bug and can be handled by external contributors

**Comment by Shahidullah-Muffakir** [comment] 2024-10-18 20:10
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
The problem happens when an approver is removed from a workspace. Even though they are no longer part of the workspace, the workflow still tries to reference them. This causes the approval workflow to not respond and show an error when we try to edit it.
### What is the root cause of that problem?
The root cause is that when we delete a member from a workspace, they are taken out of the list of employees. However, their role as someone who receives submissions (the submitsTo field) is still stored in the workflow.
this is the employee object:
`{role: 'user', email: 'user4@gmail.com', submitsTo: 'shahidmuffakir+8888@gmail.com'}
`email
: 
"user4@gmail.com"
role
: 
"user"
submitsTo
: 
"shahidmuffakir+8888@gmail.com"
[[Prototype]]
: 
Object
### What changes do you think we should make in order to solve the problem?
To fix this issue, we should add a check  while creating approval workflows.  
we need to see if the person listed in submitsTo is still in the employeesList of the policy.
here:
https://github.com/Expensify/App/blob/6d29c1cf0dc64166ce4b12329f4bd6c5fff0b6b4/src/libs/WorkflowUtils.ts#L120-L122

create this list:
`    const employeesEmails = Object.values(employees).map(emp => emp.email);
`
and add this condition  `!employeesEmails.includes(submitsTo) `as:
```
 if (!email || !submitsTo  || !employeesEmails.includes(submitsTo)) {
            return;
        }
```

**Comment by truph01** [comment] 2024-10-18 23:59
Maybe dupe of https://github.com/Expensify/App/issues/49954

**Comment by strepanier03** [comment] 2024-10-22 23:21
Thank you @truph01, I agree this is a duplicate of #49954 which was created 3 weeks ago. Closing this out.

**Closed by strepanier03** 2024-10-22 23:21 UTC
Labels: Daily, Overdue, Bug
