### ISSUE TITLE
Thread - Unable to invite user to thread when the thread originates from group chat

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#39332] opened 2024-03-31 17:55 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.58-4
**Reproducible in staging?:** Y
**Reproducible in production?:** N
**If this was caught during regression testing, add the test name, ID and link from TestRail:** N/A
**Issue reported by:** Applause - Internal Team

## Action Performed:
1. Go to staging.new.expensify.com
2. Go to FAB > Start chat
3. Create a group chat with two users
4. Send a message in group chat
5. Right click on message > Reply in thread
6. Click on the thread header > Members
7. Invite any user

## Expected Result:
User is invited successfully

## Actual Result:
User is not invited to the thread when the thread originates from group chat. The member count changes from 2 back to 1.

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [x] Android: mWeb Chrome
- [x] iOS: Native
- [x] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence
 
</details> 

https://github.com/Expensify/App/assets/78819774/1b9be08a-2fe7-4665-8bfd-780b53102567

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by lanitochka17** [comment] 2024-03-31 17:56
We think that this bug might be related to #vip-vsp

**Comment by lanitochka17** [comment] 2024-03-31 17:56
@arosiclair  FYI I haven't added the External label as I wasn't 100% sure about this issue. Please take a look and add the label if you agree it's a bug and can be handled by external contributors

**Comment by abzokhattab** [comment] 2024-04-01 01:37
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
Unable to invite user to thread when the thread originates from group chat
### What is the root cause of that problem?
 The backend returns `401 Group Chats should use InviteToGroupChat command ` when inviting members in a thread that originates from a group chat.
### What changes do you think we should make in order to solve the problem?

we need to make the invite room command conditional on whether the parent report is a group chat or not, if its a group chat then we need to send `InviteToGroupChat` instead of `InviteToRoom`.

to achieve that we need to add a new write command `InviteToGroupChat` [here](https://github.com/Expensify/App/blob/e2bff569d49b8a740721f007a8ef441b3d82767b/src/libs/API/types.ts#L105):

```js
    INVITE_TO_GROUP_CHAT: 'InviteToGroupChat',
```

then inside the `inviteToRoom` function in the Report.ts file, we need to change [this](https://github.com/Expensify/App/blob/be315d6cf336a448e330ccc752e395ccf2695629/src/libs/actions/Report.ts#L2524) to:
```js
    const parentReport = currentReportData?.[report.parentReportID];
    const isParentReportGroupChat = ReportUtils.isGroupChat(parentReport);
    API.write(isParentReportGroupChat ? WRITE_COMMANDS.INVITE_TO_GROUP_CHAT : WRITE_COMMANDS.INVITE_TO_ROOM, parameters, {optimisticData, successData, failureData});
```

**Comment by arosiclair** [comment] 2024-04-01 13:09
I reproduced on staging and prod **v1.4.57-5** so this is not a blocker

**Comment by arosiclair** [comment] 2024-04-01 13:18
I think this probably should be internal but I'm not sure. @marcaaron I saw your name on `InviteToRoom` and `InviteToGroupChat`. What do you think? Not sure if those can be used for threads too.

**Comment by marcaaron** [comment] 2024-04-01 21:34
This depends on the outcome of https://expensify.slack.com/archives/C066HJM2CAZ/p1712005980413999

I'm not sure if we intentionally designed this feature to work any kind of way, but proposed a couple of paths forward in that thread.

Gonna stay assigned here so I don't lose the context here. But maybe let's remove the `Bug` label for now as well until we have chosen a direction.

**Comment by marcaaron** [comment] 2024-04-24 22:05
I'm gonna close this one in favor of https://github.com/Expensify/Expensify/issues/384761

That lays out in clearer terms how this feature should work.

**Closed by marcaaron** 2024-04-24 22:05 UTC
Labels: Weekly, Planning, Overdue
