### ISSUE TITLE
[HOLD for payment 2023-07-14] [$1000] App refocuses on compose box even when RHN is open if we right click on emoji reaction and click on user

### ISSUE THREAD

**Issue by kavimuru** [Expensify/App#21526] opened 2023-06-25 15:43 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Open the app
2. Open any report
3. React on any message with any emoji
4. Focus on compose box
5. Right click on emoji reaction and click on user in popup to open details page
6. Observe that now app refocuses on compose box allowing us to write anything and send even when RHN is open
## Expected Result:
App should not allow user to focus on compose box and send any message when RHN is open
## Actual Result:
App focues on compose box when we right click on reaction and click on user, opening details in RHN
## Workaround:
Can the user still use Expensify without this being fixed? Have you informed them of the workaround?

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [x] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 1.3.32-5
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/43996225/637b5571-79fb-4fda-9750-250ba14981f9

https://github.com/Expensify/App/assets/43996225/260c3b0b-7769-4e26-bad6-71134a37faa1

**Expensify/Expensify Issue URL:**
**Issue reported by:** @dhanashree-sawant
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1687255339255179

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~014a6d1f40ffc8aaf0</li>
        <li>Upwork Job ID: 1674410645481107456</li>
        <li>Last Price Increase: 2023-06-29</li>
    </ul>
</details>

**Comment by muttmuure** [comment] 2023-06-28 22:16
Handling tomorrow

**Comment by jeet-dhandha** [comment] 2023-06-29 05:34
### Proposal
### Please re-state the problem that we are trying to solve in this issue.
- The app re-focuses on composer when the user clicks on the profile from BaseReactionList.

### What is the root cause of that problem?
- The `onSelectRow` does not have implementation to remove focus from composer.

### What changes do you think we should make in order to solve the problem?
- We can create a `setFocus` function in `ReportActionComposeFocusManager` using ReportActionComposeFocusManager's `composerRef` in `ReportActionCompose`.
- Then we can use that function in `BaseReactionList` to remove focus from composer.

<details>
<summary> Code Changes </summary>

File `ReportActionComposeFocusManager.js`
```diff

+ /**
+ * Function to set focus on the report action composer.
+ * @param {Boolean} focusState
+ */
+ function setFocus(focusState) {
+     if (!composerRef.current || !_.isFunction(composerRef.current.focus)) {
+         return;
+     }
+     composerRef.current.focus(focusState);
+ }

export default {
    composerRef,
    onComposerFocus,
    focus,
    clear,
    isFocused,
+    setFocus,
};
```

File `ReportActionCompose.js`
```diff
setTextInputRef(el) {
    ReportActionComposeFocusManager.composerRef.current = el;
+   ReportActionComposeFocusManager.composerRef.current.focus = this.focus;
    this.textInput = el;
}
```

File `BaseReactionList.js`
```diff
...rest code

        onSelectRow={() => {
            props.onClose();
+           ReportActionComposeFocusManager.setFocus(false);
            Navigation.navigate(ROUTES.getProfileRoute(item.accountID));
        }}

...rest code
```

</details>

### What alternative solutions did you explore? (Optional)
- N/A

**Comment by jeet-dhandha** [comment] 2023-07-01 06:07
Yup looks good. I was hung on fixing the problem instead of looking to find the underlying issue, which @hoangzinh analysed and suggested fix gracefully. 👍  +1 from me.

**Comment by madmax330** [comment] 2023-07-03 11:17
LGTM thanks @allroundexperts

**Comment by muttmuure** [comment] 2023-07-17 14:18
@dhanashree-sawant I've invited you to the upwork job

**Comment by dhanashree-sawant** [comment] 2023-07-18 03:26
Thanks @muttmuure , I have accepted the invite.

**Comment by muttmuure** [comment] 2023-07-27 11:27
Sorry for the delay. Paying out urgency bonuses and Dhanashree

**Comment by muttmuure** [comment] 2023-07-27 12:00
Bonuses paid. Offer sent to @dhanashree-sawant

**Comment by muttmuure** [comment] 2023-07-31 13:18
@dhanashree-sawant paid. Closing out

**Closed by muttmuure** 2023-07-31 13:18 UTC
Labels: External, Daily, Overdue, Awaiting Payment, Bug
