### ISSUE TITLE
[$500] Chat - New message line persists if message marked as unread > marked as read from LHN

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#37303] opened 2024-02-27 14:32 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** v1.4.44-1
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:** https://expensify.testrail.io/index.php?/tests/view/4344117
**Issue reported by:** Applause - Internal Team

## Action Performed:
1. Log in to New Expensify
2. Navigate to any chat with existing chat history
3. Mark any message as unread
4. Navigate back to LHN > mark the chat as read
5. Navigate to the chat

## Expected Result:
New message horizontal line indicator should disappear from chat history when it is marked as read.

## Actual Result:
New message indicator persists.

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [x] iOS: Native
- [x] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

https://github.com/Expensify/App/assets/93399543/bbf12e3a-33a4-4422-82f8-6a42204fd541

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01920ca88c149a51d3</li>
        <li>Upwork Job ID: 1763428799144546304</li>
        <li>Last Price Increase: 2024-03-01</li>
<li>Automatic offers: </li>
<ul>
<li>abdulrahuman5196 | Reviewer | 0</li>
<li>Victor-Nyagudi | Contributor | 0</li>
</ul></li>
    </ul>
</details>

**Comment by kbecciv** [comment] 2024-02-27 14:33
@kevinksullivan I haven't added the External label as I wasn't 100% sure about this issue. Please take a look and add the label if you agree it's a bug and can be handled by external contributors.

**Comment by kbecciv** [comment] 2024-02-27 14:33
We think that this bug might be related to #vip-vsb
CC @quinthar

**Comment by kevinksullivan** [comment] 2024-03-01 04:59
Not sure about the external aspect, but this is a reproducible bug on iOS. So I'll label and we can go from there.

**Comment by dragnoir** [comment] 2024-03-01 13:53
## Proposal

### Please re-state the problem that we are trying to solve in this issue.

Read/unread wrong when small screen and navigation throw report/LHN

### What is the root cause of that problem?

The issue is mentioned here
https://github.com/Expensify/App/blob/39a257d1aa850e875bcf604f6c7b039527234952/src/pages/home/report/ReportActionsList.js#L399

    // Iterate through the report actions and set appropriate unread marker.
    // This is to avoid a warning of:
    // Cannot update a component (ReportActionsList) while rendering a different component (CellRenderer).

Tracing `currentUnreadMarker` show that the value coming from another useEffect is wrong.

This condition wish almost always true, is blocking the nullish of the `currentUnreadMarker`
https://github.com/Expensify/App/blob/39a257d1aa850e875bcf604f6c7b039527234952/src/pages/home/report/ReportActionsList.js#L224-L226


### What changes do you think we should make in order to solve the problem?

Remove [this part](https://github.com/Expensify/App/blob/39a257d1aa850e875bcf604f6c7b039527234952/src/pages/home/report/ReportActionsList.js#L224-L226) from the useEffect
```diff
- if (currentUnreadMarker || lastVisibleActionCreatedRef.current === report.lastVisibleActionCreated) {
-   return;
- }
```

POC:

### What alternative solutions did you explore? (Optional)

**Comment by Victor-Nyagudi** [comment] 2024-03-02 11:13
## Proposal

### Please re-state the problem that we are trying to solve in this issue.

Chat - New message line persists if the message is marked as read from the LHN.

### What is the root cause of that problem?

When we navigate to the report after marking it as unread from the LHN, we return early from this `useEffect` because `currentUnreadMarker` is still `true`. 

This prevents the deletion of the report's unread marker from the cache (line 228 - 230), therefore, the unread marker persists in the report. 

https://github.com/Expensify/App/blob/af68510ad375bc99679908ce26dafead3a8b3dc1/src/pages/home/report/ReportActionsList.js#L224-L230

### What changes do you think we should make in order to solve the problem?

I propose adding another check for whether the report is unread before returning from the above `if` statement in addition to what's already there. 

This way, if the report is read, we don't return early from the `useEffect` and instead,  delete the current report's unread marker from the cache thus not rendering it. 

This is what the `if` statement on line 224 will look like after the changes. 

```javascript
if ((currentUnreadMarker || lastVisibleActionCreatedRef.current === report.lastVisibleActionCreated) && ReportUtils.isUnread(report)) {
    return;
}
```

<details>

<summary>Short demo after changes</summary>

https://github.com/Expensify/App/assets/79470910/96d51963-36d1-4c31-ada4-cb74d18dbfcb

</details>

### What alternative solutions did you explore? (Optional)

I initially considered removing the entire `if` statement (I know it's already been proposed, but it's something I thought about before the proposal was posted), but I noticed this affected the current behavior negatively.

Here's what I mean. 

1. The user marks a message as unread and navigates to the LHN. 
2. The chat is in bold, meaning there's an unread message. 
3. The user navigates to a different chat, does their business, and then later on (maybe another day), comes back to the report with the unread message.
4. When they open the chat with the unread message, they don't see the unread marker, so they have no way of knowing which message they marked as unread (it's quite possible they marked it unread for a reason and intended on addressing it later). This is the negative impact removing the `if` statement entirely will cause. 

Here's a short clip of the current behavior in production I believe is working as intended and is what I aimed to preserve when I made my changes.

<details> 

<summary>Video of current behavior in production</summary>

https://github.com/Expensify/App/assets/79470910/57046dc4-9f68-4811-9c2e-c773fb5c1583

This video was taken with my changes in place, but you can compare it to the current behavior in production to see if there's a difference. 
</details>  

I also thought about making a change inside the [`shouldDisplayNewMarker`](https://github.com/Expensify/App/blob/af68510ad375bc99679908ce26dafead3a8b3dc1/src/pages/home/report/ReportActionsList.js#L370) method, but I reasoned that the unread marker is still shown because `currentUnreadMarker` is still `true`, which is why we even get to this point where `shouldDisplay`  ends up also being `true` when we shouldn't have made it to the `else` block in the first place. 

https://github.com/Expensify/App/blob/af68510ad375bc99679908ce26dafead3a8b3dc1/src/pages/home/report/ReportActionsList.js#L388

**Comment by abdulrahuman5196** [comment] 2024-03-04 09:18
Reviewing now

**Comment by abdulrahuman5196** [comment] 2024-03-04 13:34
@dukenv0307 's proposal seems to be causing side effects where i could see inconsistently new message line shows up or sometimes doesn't show.

@dragnoir 's proposal to remove the check doesn't seem to be future safe(not that I found any currently), but if by chance the useEffect gets executed, it will always remove the unread marker.

@Victor-Nyagudi 's proposal here https://github.com/Expensify/App/issues/37303#issuecomment-1974767396 looks good and works well. Just to note its an updated version of other proposals.

So going ahead and approving @Victor-Nyagudi 's proposal here https://github.com/Expensify/App/issues/37303#issuecomment-1974767396

🎀 👀 🎀
C+ Reviewed

**Comment by abdulrahuman5196** [comment] 2024-03-05 10:49
> @abdulrahuman5196 Can you share an example case inconsistently in my proposal? Tks.
> 
> > @dukenv0307 's proposal seems to be causing side effects where i could see inconsistently new message line shows up or sometimes doesn't show.

Seems the mark as unread doesn't work for first time after opening chat and works afterwards.

https://github.com/Expensify/App/assets/46707890/82adaadd-f367-4e57-a7bb-cf0aa6d680b3

**Comment by abdulrahuman5196** [comment] 2024-03-05 11:43
> > We should check if report isn't unread, we will update currentUnreadMarker to null before this block
> 
> ```
> if (ReportUtils.isUnread(report)) {
>     setCurrentUnreadMarker(null);
>     return;
> }
> ```
> 
> @abdulrahuman5196 sorry a mistake typo as I proposed we should update `currentUnreadMarker` to null if the report isn't unread but I missed `!` in `ReportUtils.isUnread(report)` when I added pseudo code. I tested and it doesn't face this bug above can you please check again.
> 
> > Seems the mark as unread doesn't work for first time after opening chat and works afterwards.

I noticed the typo before as well @dukenv0307 and I did test with ! as well. And still faced issues. 

But anyways I am not seeing the current issue in latest main.

**Comment by abdulrahuman5196** [comment] 2024-03-05 12:06
@dukenv0307 this was the issue. Unread was automatically removed.


https://github.com/Expensify/App/assets/46707890/65f6b7f2-5101-4701-a99a-b5022f370303

**Comment by abdulrahuman5196** [comment] 2024-03-05 12:07
FYI For reference: C+ approved comment is here https://github.com/Expensify/App/issues/37303#issuecomment-1976594341

**Comment by ikevin127** [comment] 2024-03-13 13:35
# Proposal

### Please re-state the problem that we are trying to solve in this issue

New message line persists if message marked as unread > marked as read from LHN.

### What is the root cause of that problem?

👋 Just wanted to chime in with a possible different RCA for this issue -> regarding the following useEffect [here](https://github.com/Expensify/App/blob/f52bb0239f4f9aa6666a95d7140937e439760f35/src/pages/home/report/ReportActionsList.tsx#L241-L271).

Could it be possible that when the `MarkAsRead` call is made [here](https://github.com/Expensify/App/blob/f52bb0239f4f9aa6666a95d7140937e439760f35/src/libs/actions/Report.ts#L1011) and we emit the `readNewestAction` event, the mentioned useEffect's `DeviceEventEmitter` readNewestAction listener functionality does not actually work since on small screen devices the component is not mounted hence the listeners don't do what they're supposed to do (mark message as read from via `ReportActionsList`'s event listener) ?

While working on https://github.com/Expensify/App/issues/36399, I remember I looked into why this works on large screen devices where we see both the LHN and the right side of the report when opened, but doesn't work on small screen devices (like mweb / native) where the LHN is visible when performing `MarkAsRead` but the report is not opened on the right side (ReportActionsList not mounted / listeners not working) until clicked on it which opens the report screen on small screen devices.

Here's a video of large screen device vs small screen device console logging within the `DeviceEventEmitter` readNewestAction listener:

<details>
<summary>Videos</summary>

| Large screen | Small screen | Small screen (iOS) |
| ------------- | ------------- | ------------- |
| <video src="https://github.com/Expensify/App/assets/56457735/abe0f70e-f833-49ca-aa59-923faca1a240"> | <video src="https://github.com/Expensify/App/assets/56457735/5a83bfc1-c8bd-4432-92a9-a2d9228dd76e"> | <video src="https://github.com/Expensify/App/assets/56457735/27090517-2ed1-4627-909c-05d5ae2ba0f2"> |

</details>

### What changes do you think we should make in order to solve the problem?

A holistic solution to this would be to pull the `DeviceEventEmitter` listeners outside of `ReportActionsList` component lifecycle, creating a **global event listener** which is independent of any component lifecycle. This way, events can be listened for even when the relevant components are not mounted and call the current ReportActionsList logic on mount with the stored Context listener data in order to set the message as unread.

The main idea is to create a context provider that sets up the event listeners and allows nested components to interact with these listeners through the context.

This way we can solve this issue for small screen devices from the root cause instead of diverse workarounds which can mess with the complex existing logic in ways we might not understand until we get regressions.

**Comment by ikevin127** [comment] 2024-03-14 16:28
## Updated [proposal](https://github.com/Expensify/App/issues/37303#issuecomment-1994421680)
- added test branch for proposed solution + videos of the result

cc @abdulrahuman5196 @tylerkaraszewski

**Comment by tylerkaraszewski** [comment] 2024-03-14 21:26
Waiting on @abdulrahuman5196 to review the updated proposal.

**Comment by abdulrahuman5196** [comment] 2024-03-18 20:20
@tylerkaraszewski  i already have a C+ approved comment here https://github.com/Expensify/App/issues/37303#issuecomment-1976594341

Is there something else to review?

**Comment by ikevin127** [comment] 2024-03-18 20:43
@abdulrahuman5196 I posted a bew proposal here https://github.com/Expensify/App/issues/37303#issuecomment-1994421680 which has a different take on the issue. That's what @tylerkaraszewski was referring to.

**Comment by tylerkaraszewski** [comment] 2024-03-18 21:49
@abdulrahuman5196 - sorry, there have been a lot of proposals and updates here. If you still think @Victor-Nyagudi has the best proposal we can go with that one.

**Comment by abdulrahuman5196** [comment] 2024-03-19 15:30
> @abdulrahuman5196 I posted a new proposal here [#37303 (comment)](https://github.com/Expensify/App/issues/37303#issuecomment-1994421680) which has a different take on the issue's RCA and solution.
> 
> Would appreciate your take on it regardless!

>A more holistic solution would be to move all DeviceEventEmitter listeners (unreadAction, readNewestAction, deletedReportAction) out of the ReportActionsList component and set them up globally. This setup will ensure events are captured even when components are not mounted.

Hi, I am not sure if the RCA is correct or not. But regardless, I am not aligned in moving the listeners out so that they would have information even when they are unmounted.

**Comment by abdulrahuman5196** [comment] 2024-03-19 15:31
> @abdulrahuman5196 - sorry, there have been a lot of proposals and updates here. If you still think @Victor-Nyagudi has the best proposal we can go with that one.

Hi @tylerkaraszewski , I still think its the best proposal we got. 
FYI: Approval comment - https://github.com/Expensify/App/issues/37303#issuecomment-1976594341

**Comment by ikevin127** [comment] 2024-03-19 15:51
> Hi, I am not sure if the RCA is correct or not.

Is the proposal RCA not clear enough or how come you're not sure ? 👀
Also how can you make a strong decision regarding assignment on an issue if the RCA is not clear ? 👀

> But regardless, I am not aligned in moving the listeners out so that they would have information even when they are unmounted.

Regardless of the outcome with this issue, I created a slack thread to ask for engineering's take on the `DeviceEventEmitter` logic. Slack thread: https://expensify.slack.com/archives/C01GTK53T8Q/p1710863011324649

**Comment by Victor-Nyagudi** [comment] 2024-03-19 18:32
Thank you for the assignment. 

Let's shoot for the PR being ready for review within the next 48 hours, latest 72 hours in case more testing is needed. 

I'll get to work right away.

**Comment by kevinksullivan** [comment] 2024-03-19 21:54
moving to VIP-VSB as this is chat related.

**Comment by Victor-Nyagudi** [comment] 2024-03-21 08:20
PR was ready for review 14 hours ago, but I didn't mention it here since I didn't want to ping the C+ twice. 

Just sharing the message here now so it's easier to track the progress on the issue for anyone not mentioned in the PR.

**Comment by abdulrahuman5196** [comment] 2024-04-09 19:42
We will be checking for other proposals here again. The contributor mentioned they won't be able to continue with the PR.

**Comment by Victor-Nyagudi** [comment] 2024-04-11 08:10
I'm un-assigning myself based on [the above comment](https://github.com/Expensify/App/issues/37303#issuecomment-2045934785).

Good luck to whoever picks this up.

**Comment by ikevin127** [comment] 2024-04-11 09:22
👋 I'd love to take on this issue with the [proposed solution](https://github.com/Expensify/App/issues/37303#issuecomment-1994421680) if everyone agrees based on this [Slack :thread:](https://expensify.slack.com/archives/C01GTK53T8Q/p1710863011324649).

**Comment by abdulrahuman5196** [comment] 2024-04-11 15:15
> 👋 I'd love to take on this issue with the [proposed solution](https://github.com/Expensify/App/issues/37303#issuecomment-1994421680) if everyone agrees based on this [Slack 🧵](https://expensify.slack.com/archives/C01GTK53T8Q/p1710863011324649).

I will be re-evaluating all the existing proposals. Anyways I see you had added a test branch. I will check on the test branch and respond here.

**Comment by abdulrahuman5196** [comment] 2024-05-05 08:01
Hi, I think this issue slipped off my radar, given the issue is weekly for PR review, but contributor unassigned themselves. 
Anyways, I am not having bandwidth to take on this issue. Unassigning myself.

@kevinksullivan  Kindly reassign External and Help Wanted Labels for new C+ review.

**Closed** 2024-07-24 18:27 UTC
Labels: Reviewing, External, Engineering, Monthly, Bug
