### ISSUE TITLE
[$1000] Phone number is displayed incorrect in mention list

### ISSUE THREAD

**Issue by kavimuru** [Expensify/App#19331] opened 2023-05-19 23:29 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:

1. Open any chat
2. Make sure that you just had a chat with an account is created by phone
3. Enter @expensify.sms
4. See that the phone number is displayed in mention list. But there are no highlight

## Expected Result: 
Should display highlight if It matchs
## Actual Result: 
there are no highlight

## Workaround:
Can the user still use Expensify without this being fixed? Have you informed them of the workaround?

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [ ] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 1.3.16.5
**Reproducible in staging?:**
**Reproducible in production?:**
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation
![Screenshot 2023-05-17 at 17 13 27](https://github.com/Expensify/App/assets/43996225/7a7e8447-77ef-4847-a0ee-111549ae9f6e)
<img width="958" alt="Untitled" src="https://github.com/Expensify/App/assets/43996225/f4154341-7f73-423d-8755-d872c7d3648b">

**Expensify/Expensify Issue URL:**
**Issue reported by:** @dukenv0307 
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1684318419304349

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01873d11c7bbaa826a</li>
        <li>Upwork Job ID: 1659905410838413312</li>
        <li>Last Price Increase: 2023-05-27</li>
    </ul>
</details>

**Comment by kavimuru** [comment] 2023-05-19 23:29
Proposal by @dukenv0307 
## Proposal
### Please re-state the problem that we are trying to solve in this issue.
Phone number is displayed incorrect in mention list
### What is the root cause of that problem?
https://github.com/Expensify/App/blob/811c0f36fba4953af008e6643349d95c949627e4/src/components/MentionSuggestions.js#L66
We combine text and alternateText to display in mentioned list. But with a phone number the text and alternate text are the same
<img width=“338” alt=“Screenshot 2023-05-17 at 17 20 03" src=“https://github.com/Expensify/App/assets/129500732/0eb59b98-907a-4ad7-aa17-4a39b66e02f6”>
### What changes do you think we should make in order  to solve the problem?
We should use login field instead of alternateText. With my solution, It still works well with email
### Results
<img width=“873" alt=“Screenshot 2023-05-17 at 17 23 43” src=“https://github.com/Expensify/App/assets/129500732/65e171c2-67a9-4ad7-98a9-deb7d15e804a”>

**Comment by dukenv0307** [comment] 2023-05-20 06:43
I post again because photo not showing in the above proposal from @kavimuru 

## Proposal
### Please re-state the problem that we are trying to solve in this issue.
Phone number is displayed incorrect in mention list
### What is the root cause of that problem?
https://github.com/Expensify/App/blob/811c0f36fba4953af008e6643349d95c949627e4/src/components/MentionSuggestions.js#L66
We combine text and alternateText to display in mentioned list. But with a phone number the text and alternate text are the same
https://github-production-user-asset-6210df.s3.amazonaws.com/129500732/238914433-0eb59b98-907a-4ad7-aa17-4a39b66e02f6.png
### What changes do you think we should make in order  to solve the problem?
We should use login field instead of alternateText. With my solution, It still works well with email
### Results 
[<img width=“873" alt=“Screenshot 2023-05-17 at 17 23 43” src=“https://github.com/Expensify/App/assets/129500732/65e171c2-67a9-4ad7-98a9-deb7d15e804a”>](https://github-production-user-asset-6210df.s3.amazonaws.com/129500732/238915088-65e171c2-67a9-4ad7-98a9-deb7d15e804a.png)

**Comment by hightop0924** [comment] 2023-05-21 09:04
I want to apply this job.

**Comment by jayeshmangwani** [comment] 2023-05-22 10:07
IMO this is not a bug, we do not display the phone number domain `@expensify.sms` but we use it in the matching the search string as we do in the search page

cc: @aimane-chnaif @chiragsalian

**Comment by dukenv0307** [comment] 2023-05-22 10:28
[<img width=“873" alt=“Screenshot 2023-05-17 at 17 23 43” src=“https://github.com/Expensify/App/assets/129500732/65e171c2-67a9-4ad7-98a9-deb7d15e804a”>](https://github-production-user-asset-6210df.s3.amazonaws.com/129500732/238915088-65e171c2-67a9-4ad7-98a9-deb7d15e804a.png)

I think the expected should be the above video. It makes sense to me

**Comment by jayeshmangwani** [comment] 2023-05-22 10:30
@puneetlath tagging you here for a mentions functionality doubt, do we have to display the SMS domain beside the phone number in mentions?

**Comment by puneetlath** [comment] 2023-05-22 15:31
So we had a discussion about this here: https://expensify.slack.com/archives/C01GTK53T8Q/p1683834057386839

And the conclusion of that thread is that we should update the regex to recognize the phone number as a mention, even though it has spaces in it. Like this: 
![image](https://github.com/Expensify/App/assets/1371996/4dc558d8-7da1-44bc-b8f8-58585f42c3e7)

**Comment by dukenv0307** [comment] 2023-05-22 15:34
@puneetlath What about this issue? Do you think we should fix it?

**Comment by puneetlath** [comment] 2023-05-22 15:35
Ah sorry. I did not read clearly. Yes, I think we should. Typing `@expensify.sms` shouldn't actually show anything in the list.

**Comment by jayeshmangwani** [comment] 2023-05-22 15:39
Then we should update OP, it shows the different expected result
> Should display highlight if It matchs

**Comment by NicMendonca** [comment] 2023-05-23 08:29
Going OOO until June 5th so assigning a buddy to this GH to watch over the issue. I'll pick it back up when I am back from OOO/ if this is still open.

**Comment by dukenv0307** [comment] 2023-05-25 16:19
> Typing @expensify.sms shouldn't actually show anything in the list.

It fixed by https://github.com/Expensify/App/pull/19221

**Comment by dukenv0307** [comment] 2023-05-25 16:57
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
Phone number is displayed incorrect in mention list
### What is the root cause of that problem?
https://github.com/Expensify/App/blob/0f33e2c22bb3670e7c47d78f2f3c604f3af29ca3/src/pages/home/report/ReportActionCompose.js#L479
We are finding search value in both `login` field and `displayName` field 
This is data of an account that is created by phone number
<img width="450" alt="Screenshot 2023-05-25 at 23 43 54" src="https://github.com/Expensify/App/assets/129500732/3c9f6998-60b3-4a3f-b5b2-2d97e53f28c5">
see that: login field contains `@expensify.sms ` So that the phone number account will display when searching  `@expensify.sms`
### What changes do you think we should make in order to solve the problem?
We should check whether this account is created by phone number 
`const isSMSLogin = detail.login ? Str.isSMSLogin(detail.login) : false;`
or `const isSMSLogin = detail.login.endsWith("@expensify.sms")` 

and then replace 
https://github.com/Expensify/App/blob/0f33e2c22bb3670e7c47d78f2f3c604f3af29ca3/src/pages/home/report/ReportActionCompose.js#L479
to 
```
if (searchValue && !`${detail.displayName} ${isSMSLogin ? detail.login.removeSMSDomain() : detail.login}`. .......
```


 
### What alternative solutions did you explore? (Optional)

**Comment by zanyrenney** [comment] 2023-05-25 16:57
hey @NicMendonca assigning ya as the new process is to stay assigned!

**Comment by dukenv0307** [comment] 2023-05-25 17:04
@aimane-chnaif Sorry about my mistake. I also reproduce on the lastest main. So I just created new proposal again

**Comment by zanyrenney** [comment] 2023-05-25 17:06
Going OOO and this is pretty active so needs management by bug0 team member, please can you keep a watch of this as I am OOO until 8th June. Thanks!

**Comment by zanyrenney** [comment] 2023-05-25 17:07
As @NicMendonca was the initial assignee and should have stayed assigned, assigning her (and me!) as well in case there is more to do when return from OOO.

**Comment by johncschuster** [comment] 2023-05-30 17:39
@aimane-chnaif / @puneetlath, I'm just catching up here and [in Slack](https://expensify.slack.com/archives/C01GTK53T8Q/p1683834057386839) and want to make sure I understand where we've landed. It sounds like we believe the following:

• @expensify.sms should not return anything in the mention list, while `@` mentioning a phone number _should_ return that phone number to be auto-completed.

• The phone number returned in the auto-complete list will be dependent on the country you are in. So if I am in the US and the number I am mentioning is in the US (ex: 123-456-7890), I would expect to see `@123-456-7890` returned, but if I am outside the US and mentioning the same user, I would expect to see `@+1-123-456-7890`

Am I right?

@aimane-chnaif, have the proposals above met the issue as I understood it?

**Comment by mvtglobally** [comment] 2023-05-31 04:08
Issue not reproducible during KI retests. (First week)

**Comment by chiragsalian** [comment] 2023-06-01 22:06
Is the issue description still correct? Cause the issue description says it does not show any highlight when entering `@expensify.sms` but i see a highlight when i test.
In @dukenv0307 comment above also i see `@ex` being highlighted in the options so it looks correct to me. 

If there is a different concern can someone restate the problem so that we can update the issue description accordingly (or explain it to me if I'm missing something obvious)

**Comment by puneetlath** [comment] 2023-06-02 21:23
My recommendation would be that we go ahead and close this. We'll be updating mentions to use "handles" soon, so there's no need to change anything for now.

**Comment by chiragsalian** [comment] 2023-06-02 22:23
Sure i'm fine with closing this for now and revisiting once we're implemented handles.

**Closed by chiragsalian** 2023-06-02 22:23 UTC
Labels: External, Daily, Help Wanted, Bug

**Comment by hightop0924** [comment] 2023-06-10 16:23
I want to participate in your team

**Comment by puneetlath** [comment] 2023-07-10 16:46
@c3024 there's this one: https://github.com/Expensify/App/issues/18729
