### ISSUE TITLE
[$500] Compose -Copy URL to clipboard shows url link and markdown text.

### ISSUE THREAD

**Issue by izarutskaya** [Expensify/App#31422] opened 2023-11-16 08:37 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.0-0
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** Applause-Internal Team
**Slack conversation:** @

## Action Performed:
1. Go to https://staging.new.expensify.com
2. Open any report
3. Paste `*text https://expensify.com#abc*`
4. Send the message
5. Observe that * bolding doesn't work. 

## Expected Result:
Link should be bolded

## Actual Result:
Link is not bolded, markdown * are showing

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [x] Android: mWeb Chrome
- [x] iOS: Native
- [x] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

https://github.com/Expensify/App/assets/115492554/8070dd8f-7ee6-417f-add6-d5f93867165c

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01b6ad7e1bea3c914c</li>
        <li>Upwork Job ID: 1725070533592285184</li>
        <li>Last Price Increase: 2024-02-16</li>
    </ul>
</details>

**Comment by s-alves10** [comment] 2023-11-16 08:56
@izarutskaya 

Will you let me know what the original text is?

**Comment by peterdbarkerUK** [comment] 2023-11-21 14:05
repro'd and updated OP

**Comment by css1022** [comment] 2023-11-22 11:56
# Proposal
### Please re-state the problem that we are trying to solve in this issue.
URL with hash inside bold markdown does not apply the bold markdown

`*text https://expensify.com#abc*`

### What is the root cause of that problem?
The bold rule is after the auto link rule, 
The auto link markdown parses url with ending * before bold rule is applied, thus the bold rule does not apply.

### What changes do you think we should make in order to solve the problem?
If Url with ending asterisk is part of string which is likely to be parsed as bold (e.g. `*text https://expensify.com#abc*`), 
we should not contain ending * as part of url.
To do that, we can add following process in modifyTextForUrlLinks function.
The process is to exclude ending asterisk if there is string with asterisk leading to url . 

```
                if (numberOfCharsToRemove) {
                    match[0] = match[0].substring(0, match[0].length - numberOfCharsToRemove);
                    url = url.substring(0, url.length - numberOfCharsToRemove);
                }
            }
--------->
            if (match.index !== 0) {
                const stringBeforeUrl = textToCheck.substring(startIndex, match.index);
                const lastChar = url.charAt(url.length - 1);
                if (lastChar === '*' && stringBeforeUrl.includes(lastChar)) {
                    match[0] = match[0].substring(0, match[0].length - 1);
                    url = url.substring(0, url.length - 1);
                }
            }
<-----------
            replacedText = replacedText.concat(textToCheck.substr(startIndex, (match.index - startIndex)));
```

we can add relevant test case

This approach does not make other test cases failed.

**Comment by peterdbarkerUK** [comment] 2023-11-24 14:14
@css1022 Could you follow the instructions [here](https://github.com/Expensify/App/issues/31422#issuecomment-1822634494)? Thank you!

**Comment by peterdbarkerUK** [comment] 2023-11-28 21:09
I would agree it seems to be the same root cause of where * fits int he regex pattern. @r3770 could you clarify why you disagree?

**Comment by r3770** [comment] 2023-11-29 09:19
Here issue's root cause is that first autolink rule has been parsed and ending * has been contained into url, after then bold rule applied, so bold is not applied because of missed ending * . Likely Italic and strikethrough are not working as well

https://github.com/Expensify/App/issues/30823's root cause is that bold regex pattern is not behaved as italic and strikethrough, so test string is not parsed like italic and strikethrough.

**Comment by r3770** [comment] 2023-11-29 23:42
@peterdbarkerUK 
I can see that amendment of bold regex pattern can't cover this issue.
Looks like @css1022 's solution does

**Comment by getusha** [comment] 2023-11-30 14:00
yeah, I think we should hold this for https://github.com/Expensify/App/issues/30823

**Comment by peterdbarkerUK** [comment] 2023-12-12 20:47
Apoologies folks, I got hit with a tsunami of work in another team and this slipped off my radar. On hold for https://github.com/Expensify/App/issues/30823

**Comment by peterdbarkerUK** [comment] 2023-12-27 11:39
Still on hold

**Comment by peterdbarkerUK** [comment] 2024-01-02 21:13
still holding

**Comment by peterdbarkerUK** [comment] 2024-01-22 21:34
Still holding for https://github.com/Expensify/App/issues/30823

**Comment by conorpendergrast** [comment] 2024-02-02 11:32
Alright, it actually looks like the PR for https://github.com/Expensify/App/issues/30823 is merged (not deployed, because it seems like the repo doesn't have a deploy process). 

So this is off hold now.

@ntdiary what's the next step now this is off hold? Re-test the reproduction steps?

**Comment by conorpendergrast** [comment] 2024-02-05 10:19
Fantastic, thanks for that @ntdiary - I'm coming to this late, so that's really helpful. I'll take another pass through, reproduce it too, and then will recommend fixing or closing.

**Comment by conorpendergrast** [comment] 2024-02-06 12:59
Ok, I've reproduced this again too. 

> So, personally, I don't have strong feeling about fixing this issue (it's okay to just close this issue).

Thinking with my customer support hat on, I think I can imagine myself sending a message like:
```
*Please go to https://help.expensify.com/articles/expensify-classic/bank-accounts-and-credit-cards/business-bank-accounts/Business-Bank-Accounts-AUD#bank-specific-batch-payment-support*
```

which doesn't work: 
![image](https://github.com/Expensify/App/assets/5802477/5ac22b6b-6f2d-490c-bb8b-3e673bf92c68)

Whereas the workaround is: 
```
*Please go to* *[https://help.expensify.com/articles/expensify-classic/bank-accounts-and-credit-cards/business-bank-accounts/Business-Bank-Accounts-AUD#bank-specific-batch-payment-support](https://help.expensify.com/articles/expensify-classic/bank-accounts-and-credit-cards/business-bank-accounts/Business-Bank-Accounts-AUD#bank-specific-batch-payment-support)*
```

Which does work: 

![image](https://github.com/Expensify/App/assets/5802477/47454bd9-b34d-45d0-b08a-eaca1fb36321)

**Comment by conorpendergrast** [comment] 2024-02-06 13:07
I've [posted to #expensify-open-source in Slack](https://expensify.slack.com/archives/C01GTK53T8Q/p1707224549892459?thread_ts=1707184864.796129&cid=C01GTK53T8Q) to get discussion on closing this out

**Comment by sakluger** [comment] 2024-02-13 20:54
Hi @ntdiary, I'd like to fix this issue, and I think that Conor's proposed fix in [his comment here](https://github.com/Expensify/App/issues/31422#issuecomment-1929474970) is a good solution.

**Comment by sakluger** [comment] 2024-02-19 23:56
Hi @ntdiary - I misunderstood Conor's comment before, sorry about that! I thought his "workaround" was a proposed solution when it's actually what the user would have to do to make the whole text line bold.

I did a bit more research and found that it's possible for URLs to have `*`'s. For that reason, I think we should leave the current edge-case bug as is.

In the future, after we add live markdown previews, we'll also add keyboard shortcuts (i.e. `Command+b`) at some point, which will make this less of an issue.

**Closed by sakluger** 2024-02-19 23:56 UTC
Labels: External, Engineering, Daily, Help Wanted, Overdue, Bug
