### ISSUE TITLE
[$500] Web - Chat-Mouse scroll and slide functions reversely if pressed on mouse wheel

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#33299] opened 2023-12-19 16:08 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.14.0
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** Applause - Internal Team
**Slack conversation:**

## Action Performed:
1. Login to ND Expensify
2. Navigate to a chat that has a lot of messages in the conversation history
3. Scroll to the top of the conversation via scroll bar
4. Press on the mouse wheel and try to slide down to the bottom of the conversation
5. Slide to the bottom of the conversation
6. Press on the mouse wheel and try to slide up to the top of the conversation

## Expected Result:
While pressing on the mouse wheel, sliding should be harmonious with the scroll bar

## Actual Result:
While pressing on the mouse wheel, if user tries to slide down or up, sliding functions reversely. Mouse cursor works opposite with the scroll bar.

## Workaround:
Unknown 

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

https://github.com/Expensify/App/assets/93399543/fcf89850-0b59-41c3-bc41-d2e8fc1da7af

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01ece60315a26cd5ed</li>
        <li>Upwork Job ID: 1737142924592078848</li>
        <li>Last Price Increase: 2024-01-02</li>
<li>Automatic offers: </li>
<ul>
<li>situchan | Contributor | 28077572</li>
</ul></li>
    </ul>
</details>

**Comment by yh-0218** [comment] 2023-12-19 18:36
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
Web - Chat-Mouse scroll and slide functions reversely if pressed on mouse wheel
### What is the root cause of that problem?
Mouse wheel direction is reversed.
### What changes do you think we should make in order to solve the problem?
We can custom mouse wheel direction.
```js
export function useHorizontalScroll() {
  const elRef = useRef();
  useEffect(() => {
    const el = elRef.current;
    if (el) {
      const onWheel = e => {
        if (e.deltaY == 0) return;
        e.preventDefault();
        el.scrollTo({
          left: el.scrollLeft + e.deltaY,
          behavior: "smooth"
        });
      };
      el.addEventListener("wheel", onWheel);
      return () => el.removeEventListener("wheel", onWheel);
    }
  }, []);
  return elRef;
}
```
### What alternative solutions did you explore? (Optional)

**Comment by KevinBlakeLopez** [comment] 2023-12-20 23:12
I am considering presenting a proposal in the near future, and I want to verify if this is an issue worth fixing or not or whether it would be included in a wave latter on or if it will be paid out if we are able to present a solution.  thanks.

**Comment by KevinBlakeLopez** [comment] 2023-12-20 23:13
Contributor details
Your Expensify account email: kevinblakelopez@gmail.com
Upwork Profile Link: https://www.upwork.com/freelancers/~01a4b93f700f1a3a06?viewMode=1

**Comment by cartersteinhoff** [comment] 2023-12-21 19:26
@kbecciv Hi, I'm also interested in presenting a proposal. Is this issue available to take on?

**Comment by NicMendonca** [comment] 2023-12-22 17:23
@thesahindia a proposal for you here!

**Comment by situchan** [comment] 2023-12-22 23:35
@NicMendonca I can take over

**Comment by NicMendonca** [comment] 2024-01-02 17:43
@situchan sorry - just saw this now! assigned you

**Comment by Nathan-Mulugeta** [comment] 2024-01-02 17:47
Hey @NicMendonca , I remembered reporting this issue way back [here](https://github.com/Expensify/App/issues/18233). Can we consider this to be originally reported by me? Thanks

**Comment by NicMendonca** [comment] 2024-01-04 20:58
I am going to close this as per this update - https://expensify.slack.com/archives/C01GTK53T8Q/p1702496349813859

This isn't directly related to a roadmap issue

**Closed by NicMendonca** 2024-01-04 20:58 UTC
Labels: External, Daily, Overdue, Bug
