### ISSUE TITLE
[HOLD for payment 2023-06-29] [$1000] Real-time workspace name update not functioning in announcement page

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#20776] opened 2023-06-14 20:48 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
Action Performed:
1. Open the app settings.
2. Navigate to the workspace.
3. Create a workspace and go to the announcement page by clicking on the three dots in the upper right corner.
4. Go back to settings and update the workspace name. The announcement page does not update in real-time.

## Expected Result:
The announcement page should update in real-time when the workspace name is updated.

## Actual Result:
The announcement page does not update in real-time until the app is reloaded.

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [x] MacOS / Chrome / Safari
- [x] MacOS / Desktop

**Version Number:** 1.3.27.2

**Reproducible in staging?:** yes

**Reproducible in production?:** n/a

**If this was caught during regression testing, add the test name, ID and link from TestRail:**

**Email or phone of affected tester (no customers):**

**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Notes/Photos/Videos:** Any additional supporting documentation

[screen-capture (66) (1).webm](https://github.com/Expensify/App/assets/93399543/91e9b3ca-df80-44a4-98ed-e5ad1f1cb484)

https://github.com/Expensify/App/assets/93399543/8051bd94-63e1-43f9-9fd7-08e3b1091a6f

**Expensify/Expensify Issue URL:**

**Issue reported by:** @tewodrosGirmaA

**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1686212520355699

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01c58fa396a63a4bbb</li>
        <li>Upwork Job ID: 1669391510928707584</li>
        <li>Last Price Increase: 2023-06-15</li>
    </ul>
</details>

**Comment by namhihi237** [comment] 2023-06-14 21:01
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
The announcement page should update in real time when the workspace name is updated.
### What is the root cause of that problem?
The root cause here is when name workspaces are updated it does not trigger to re-render the component  `ReportWelcomeText` 
https://github.com/Expensify/App/blob/23978e4142bcaed94162e94159c61d946f3467dd/src/components/ReportWelcomeText.js#L60
### What changes do you think we should make in order to solve the problem?
We will add props `policy` to trigger when workspaces update so `ReportWelcomeText` will re-render and get `roomWelcomeMessage` to show.
```
const propTypes = {
  ...
  policy: PropTypes.shape({
   name: PropTypes.string,
 }),
};
```
Add default pros:
```
const  defaultProps  = {
 ...
 policy: {}
};
```
Subscribe to changes of the data:
```
export default compose(
 withLocalize,
 withOnyx({
  ...
  policy: {
   key: (props) =>  `${ONYXKEYS.COLLECTION.POLICY}${props.report.policyID}`
  }
 }),
)(ReportWelcomeText);
```
### What alternative solutions did you explore? (Optional)
N/A

**Comment by twisterdotcom** [comment] 2023-06-15 16:21
Closing as a dupe of https://github.com/Expensify/App/issues/19847

**Comment by abdulrahuman5196** [comment] 2023-06-15 16:42
The real time update is not working for workspace picture as well

**Comment by zanyrenney** [comment] 2023-06-15 17:08
Yep, reproducible, tested with my accountex workspace: 
![2023-06-15_18-07-55](https://github.com/Expensify/App/assets/56830058/2cfd7951-80b6-48d0-b605-f18e14cd2755)

**Comment by securitybeautystar** [comment] 2023-06-15 17:27
Solution:

Persistent State Management: The application should keep track of the last accessed room and store this information in a persistent state. When the application is reloaded, this state should be read and the user should be taken back to their last accessed room. This could be implemented using LocalStorage on the web or Shared Preferences on native platforms. For example, when a user opens a room, the app can save the room ID in the local storage. On app reload, it can check if there is a room ID saved in the local storage, if there is, the app can navigate to that room.

URL Parameters: If the app is a web application, another possible solution could be to use the URL to maintain the state of the last accessed room. This means, when a user opens a room, the URL should reflect that room. This way, even if the page is reloaded, the user would stay on the same page.

**Comment by securitybeautystar** [comment] 2023-06-15 17:32
Contributor details
Your Expensify account email: bentonprohaskas@gmail.com
Upwork Profile Link:  https://www.upwork.com/freelancers/~018c2f66922e4ea34d

### **Solution:**
Persistent State Management: The application should keep track of the last accessed room and store this information in a persistent state. When the application is reloaded, this state should be read and the user should be taken back to their last accessed room. This could be implemented using LocalStorage on the web or Shared Preferences on native platforms. For example, when a user opens a room, the app can save the room ID in the local storage. On app reload, it can check if there is a room ID saved in the local storage, if there is, the app can navigate to that room.

URL Parameters: If the app is a web application, another possible solution could be to use the URL to maintain the state of the last accessed room. This means, when a user opens a room, the URL should reflect that room. This way, even if the page is reloaded, the user would stay on the same page.

**Comment by sobitneupane** [comment] 2023-06-16 11:41
@hungvu193 Overall [your proposal](https://github.com/Expensify/App/issues/20776#issuecomment-1592152236) looks good to me. But won't it be more efficient to add policy in `ReportActionItemCreated` rather than `ReportActionItem`? If we add it in `ReportActionItem`, all the report action items will be re-rendered.

**Comment by sobitneupane** [comment] 2023-06-16 11:57
@hungvu193 I think we can add it separately in IOUPreview if required.

Overall, [proposal](https://github.com/Expensify/App/issues/20776#issuecomment-1592152236) from @hungvu193 looks good to me. But I will prefer the change in `ReportActionItemCreated` rather than `ReportActionItem`.

:ribbon: :eyes: :ribbon:  C+ reviewed
cc: @roryabraham

**Comment by zanyrenney** [comment] 2023-06-22 14:06
Hey, I am heading OOO shortly, so assigning another bug0 team member to help watch over this issue whilst I am OOO.

**Comment by sobitneupane** [comment] 2023-07-03 08:46
> **BugZero Checklist:** The PR fixing this issue has been merged! The following checklist ([instructions](https://stackoverflow.com/c/expensify/questions/14574)) will need to be completed before the issue can be closed:
> 
> * [ ]  [@sobitneupane] The PR that introduced the bug has been identified. Link to the PR:

Could not identify the exact PR. It was present since long time.

> * [ ]  [@sobitneupane] The offending PR has been commented on, pointing out the bug it caused and why, so the author and reviewers can learn from the mistake. Link to comment: 

N/A
> * [ ]  [@sobitneupane] A discussion in #expensify-bugs has been started about whether any other steps should be taken (e.g. updating the PR review checklist) in order to catch this type of bug sooner. Link to discussion:

https://expensify.slack.com/archives/C049HHMV9SM/p1688373959026059
> * [ ]  [@sobitneupane] Determine if we should create a regression test for this bug. 

Yes:
> * [ ]  [@sobitneupane] If we decide to create a regression test for the bug, please propose the [regression test](https://github.com/Expensify/App/blob/main/contributingGuides/REGRESSION_TEST_BEST_PRACTICES.md) steps to ensure the same bug will not reach production again.

**Comment by sobitneupane** [comment] 2023-07-03 08:47
**Regression Test Proposal**

1. Open the app settings.
2. Navigate to the workspace.
3. Create a workspace and go to the announcement page by clicking on the three dots in the upper right corner.
4. Go back to settings and update the workspace name
5. Verify that the announcement page name updated in real-time.

Do we agree 👍 or 👎

**Comment by zanyrenney** [comment] 2023-07-03 09:03
https://github.com/Expensify/Expensify/issues/296727

**Comment by zanyrenney** [comment] 2023-07-03 09:04
Regression test: https://github.com/Expensify/Expensify/issues/296727

**Comment by zanyrenney** [comment] 2023-07-04 16:38
Offers sent @hungvu193 @tewodrosGirmaA 

still waiting on @sobitneupane to accept invite.

**Comment by tewodrosGirmaA** [comment] 2023-07-04 16:43
> Offers sent @hungvu193 @tewodrosGirmaA 
> 
> still waiting on @sobitneupane to accept invite.

Thank you , I accept the offer

**Comment by sobitneupane** [comment] 2023-07-05 04:05
Thanks @zanyrenney. Accepted the invitation.

**Comment by zanyrenney** [comment] 2023-07-05 12:22
All paid out, closing.

**Comment by zanyrenney** [comment] 2023-07-10 10:47
Bonuses paid to @hungvu193 and @sobitneupane

**Closed by zanyrenney** 2023-07-10 10:47 UTC
Labels: External, Daily, Awaiting Payment, Bug
