### ISSUE TITLE
[$250] BUG: when flipping between chats, the composer box is gone and only the skeleton UI shows.

### ISSUE THREAD

**Issue by kavimuru** [Expensify/App#11962] opened 2022-10-18 15:33 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Go to ND and login
2. Open any chat
3. Switch between chats

## Expected Result:
Composer window should not disappear 

## Actual Result:
composer window disappears between chats and the UI jumping around.

## Workaround:
Unknown

## Platform:

Where is this issue occurring?

- Web
- iOS
- Android

**Version Number:** 1.2.17-1
**Reproducible in staging?:** y
**Reproducible in production?:** y
**Email or phone of affected tester (no customers):** 
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** 
<img width="1066" alt="image" src="https://user-images.githubusercontent.com/43996225/196475544-3b3e8ad7-3f04-42b7-a9d8-d283a0e69a4b.png">

https://user-images.githubusercontent.com/43996225/196475566-a2412dff-88f2-46d1-b710-02bcca90d454.mp4

**Expensify/Expensify Issue URL:** 
**Issue reported by:** @shawnborton 
**Slack conversation:** https://expensify.slack.com/archives/C01GTK53T8Q/p1666030320048069

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by mountiny** [comment] 2022-10-19 19:03
This can definitely be external issue, the UI jumps are not great, lets make sure it is spotless

**Comment by MitchExpensify** [comment] 2022-10-19 22:52
[Upwork Job](https://www.upwork.com/jobs/~017c35805f24784310)

**Comment by chauchausoup** [comment] 2022-10-20 03:48
Is this issue related to removing the react-content-loader module ?
If that is the case then we can remove the implementation from here: https://github.com/Expensify/App/blob/fbf0334713e7e8d73507e30a8b12c941d9b46670/src/components/ReportHeaderSkeletonView.js#L4
But personally I don't think that it is a good idea to remove the skeleton view as it is the industry practice to keep such UX implementations ([ref](https://blog.logrocket.com/improve-react-ux-skeleton-ui/))

**Comment by chauchausoup** [comment] 2022-10-20 04:23
Issue:
Issue is caused due to ReportFooter component being wrapped along with the ReportActionsView here at:
https://github.com/Expensify/App/blob/fbf0334713e7e8d73507e30a8b12c941d9b46670/src/pages/home/ReportScreen.js#L297
that is rendered by a conditional logic to check the Loading effect in the app.

Solution:
We can simple take the ReportFooter component and keep it outside the conditional wrapper as: 
```
{this.shouldShowLoader()
                                ? (
                                    <ReportActionsSkeletonView
                                        containerHeight={this.state.skeletonViewContainerHeight}
                                    />
                                )
                                : (
                                    <>
                                        <ReportActionsView
                                            reportActions={this.props.reportActions}
                                            report={this.props.report}
                                            session={this.props.session}
                                            isComposerFullSize={this.props.isComposerFullSize}
                                            isDrawerOpen={this.props.isDrawerOpen}
                                        />

                                    </>
                                )}
                            <ReportFooter
                                addWorkspaceRoomErrors={addWorkspaceRoomErrors}
                                addWorkspaceRoomPendingAction={addWorkspaceRoomPendingAction}
                                isOffline={this.props.network.isOffline}
                                reportActions={this.props.reportActions}
                                report={this.props.report}
                                isComposerFullSize={this.props.isComposerFullSize}
                                onSubmitComment={this.onSubmitComment}
                            />
                            ```

**Comment by mountiny** [comment] 2022-10-20 16:44
Thank you for the review @rushatgabhane, can you please raise a PR @chauchausoup ?

**Comment by chauchausoup** [comment] 2022-10-20 16:51
Sure @mountiny will spin it in few hours.

**Comment by mountiny** [comment] 2022-10-31 11:20
PR is in a review.

**Comment by mountiny** [comment] 2022-10-31 16:47
@rushatgabhane Can you confirm if the regression would be avoided in here? Thank you for looking into this 🙇

**Comment by mountiny** [comment] 2022-11-04 14:43
😬 Thank you for confirming @rushatgabhane  and thanks for pointing this out @0xmiroslav 

@chauchausoup can you think of a way how to prevent the regression from happening and solving this issue? Otherwise I am afraid we will have to open this for new proposals.

**Comment by mountiny** [comment] 2022-11-04 15:09
Oh perfect, @rushatgabhane, thanks!

I think we can close this one then, since it is duplicate and the other issue has higher reward.

I am sorry @chauchausoup this did not work out, thank you so much for your efforts but we cannot proceed with that proposal given it would introduce regression.

**Closed by mountiny** 2022-11-04 15:09 UTC
Labels: Reviewing, External, Engineering, Weekly, Bug

**Comment by chauchausoup** [comment] 2022-11-05 03:25
I dint understand whats happening. How do it cause regression when my proposal is not even deployed?

**Comment by chauchausoup** [comment] 2022-11-05 03:27
My proposal was posted earlier than @0xmiroslav 's right?

**Comment by mountiny** [comment] 2022-11-05 13:56
@chauchausoup sorry for the confusion. You can read [this comment](https://github.com/Expensify/App/issues/11962#issuecomment-1297304687), the solution you have proposed is a revert of a PR which fixed a regression.

Rushat has confirmed that your PR is experiencing the issue so it would cause a regression unfortunately. I realize you have proposed solution earlier however, since this solution has a bug, the next proposal which avoids it goes forward.

Apologies for this.
