### ISSUE TITLE
Bug: New chats in LHN aren't loading at launch or reopening of app when authToken expires

### ISSUE THREAD

**Issue by mvtglobally** [Expensify/App#11081] opened 2022-09-19 04:13 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Quit desktop app
2. Have messages sent to you
3. Open desktop app
4. Observe new chats sent aren't showing in LHN

## Expected Result:
New chats to show in LHN

## Actual Result:
New chats aren't showing. 

## Workaround:
Refresh or sign out/in

## Platform:

Where is this issue occurring?

- iOS
- Desktop App

**Version Number:** 1.2.0-0
**Reproducible in staging?:** Y 
**Reproducible in production?:** Y
**Email or phone of affected tester (no customers):** 
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation 

**Expensify/Expensify Issue URL:** 
**Issue reported by:** @marcaaron 
**Slack conversation:** https://expensify.slack.com/archives/C01GTK53T8Q/p1663347298893329

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by davidcardoza** [comment] 2022-09-19 07:19
I was able to reproduce this issue. Chats I read on desktop still appearing as unread on mobile happens to me often actually. I have to sign out and sign back in on mobile to clear the messages. Assigning to engineering

**Comment by pecanoro** [comment] 2022-09-19 10:14
I am marking this as a bug and not a feature request since from the user's perspective and oh well common sense, marking something as read should sync between platforms and it's pretty annoying when this happens.

**Comment by danieldoglas** [comment] 2022-09-19 15:08
Adding more context:

I feel like every time I open my app on iOS, it is not updating the current LHN data. Feels like it's not calling `OpenApp`. Old messages appear there as not read, though I've already read them on the web (I don't think this is an Unread indicator issue since it also shows old messages). It doesn't matter if it was in the background for 10min or 12 hours.

**Comment by marcaaron** [comment] 2022-09-19 15:16
Ah sorry I did not catch this sooner but meant to throw it in my list of "unread indicators" bugs. Maybe not a great candidate for an `External` issue as it most likely has to do with either Pusher or the web API - both of which are tricky to gain insight in as a contributor.

**Comment by marcaaron** [comment] 2022-09-19 15:17
>Issue 1: It makes sense that the chat counter indicator on the app icon would possibly not update (as I’m unsure if we have background updates working for this or not at this point).

>Issue 2: Separately, opening the app should sync things up and mark these chats as “read”. So either we are failing to mark them as read in the first place or OpenApp/ReconnectApp is miscalculating.

Also meant for these to be investigated as two separate issues 😄  I'll just create the issue myself next time :ohnothing:

**Comment by marcaaron** [comment] 2022-09-19 15:19
>I feel like every time I open my app on iOS, it is not updating the current LHN data. Feels like it's not calling OpenApp. Old messages appear there as not read, though I've already read them on the web (I don't think this is an Unread indicator issue since it also shows old messages). It doesn't matter if it was in the background for 10min or 12 hours.

@danieldoglas interesting. It should be possible to tell this by looking at logs. I'd expect the behavior to also be the same when running the local app or simulator. Have you tested out this theory?

**Comment by marcaaron** [comment] 2022-09-19 21:04
I just reproduced and checked logs... seems like what happened is that my `authToken` expired and the request was not retried.

https://www.expensify.com/_devportal/tools/logSearch/#query=request_id:(%2274d535d408d4bc75-SJC%22)+AND+timestamp:[2022-09-19T19:53:20.709Z+TO+2022-09-19T21:53:20.709Z]&index=logs_expensify-018634

`OpenApp` is a `API.read()` request which means it goes through `makeRequestWithSideEffects()` 

https://github.com/Expensify/App/blob/e093383f62a77fea3592f738416d72fdd0c33e46/src/libs/actions/App.js#L104

I'll do some testing locally. But IIRC `read()` requests are not retried when they fail.

**Comment by marcaaron** [comment] 2022-09-19 21:17
Yep that is what is happening. @luacmartins curious if this aligns with your expectations or if you can double check me on this. I'm feeling like if a "READ" request fails because we could not authenticate then we should always retry the request at least once.

**Comment by luacmartins** [comment] 2022-09-19 21:47
@marcaaron that makes sense. Expired authTokens are fairly common and we should retry the request once. Do we have logic for that anywhere in App?

**Comment by mallenexpensify** [comment] 2022-09-20 00:42
I've been experiencing a version of "LHN isn't updating when I open iOS app" but haven't captured reliable reproduction steps (it's happened, at least, a few times the past week. v1.2.1-0.  Let me know if I can help with testing or if you want me to try to repro and drop steps in here. Also... I think the issue I'm having is different than the title of this issue, let me know if I can/should start a new issue

**Comment by marcaaron** [comment] 2022-09-20 16:56
>Do we have logic for that anywhere in App?

It would be here:
 https://github.com/Expensify/App/blob/4110cf23cd1a858217c86b4872f32005de0a204f/src/libs/Middleware/Reauthentication.js#L33-L47

We pass `shouldRetry: true` for writes only so assuming any `read()` or `makeRequestWithSideEffects()` would not be retried at all in the case of a `jsonCode: 407`.

Writes:

https://github.com/Expensify/App/blob/4110cf23cd1a858217c86b4872f32005de0a204f/src/libs/API.js#L20-L47

Reads:

https://github.com/Expensify/App/blob/4110cf23cd1a858217c86b4872f32005de0a204f/src/libs/API.js#L67-L88

**Comment by marcaaron** [comment] 2022-09-20 17:09
It seems like we could reauthenticate in these cases, but I think we would be unable to "replay" the request due to how `read()` and `makeRequestWithSideEffects()` works.

Here’s an alternative solution and way to think about this problem:

- It’s correct that READ requests should not be retried
- However, if the authToken is expired when doing a READ we should
    - Reauthenticate
    - Call `ReconnectApp` (which is what we call when the user has been offline for a while and has regained connectivity

Thoughts?

**Comment by marcaaron** [comment] 2022-09-20 17:38
>However, we would still have edge cases where ReconnectApp does not return the data requested by the failing READ request, e.g. in OpenEnablePaymentsPage.

Yeah that's a good point. Hmm maybe in those cases we should be hooking those into the reconnection callbacks here:

https://github.com/Expensify/App/blob/e093383f62a77fea3592f738416d72fdd0c33e46/src/libs/NetworkConnection.js#L19-L25

The reauthenticate scenario should also trigger a "reconnect" event and then individual pages should be responsible for defining their update logic. But instead of tracking the offline status they should be using `onReconnect()`

So this:

https://github.com/Expensify/App/blob/e093383f62a77fea3592f738416d72fdd0c33e46/src/pages/EnablePayments/EnablePaymentsPage.js#L44-L50

Should become:

```js
componentDidMount() {
    NetworkConnection.onReconnect(Wallet.openEnablePaymentsPage)
}
```

And this could cover the case of network status change and reauthentication?

**Comment by marcaaron** [comment] 2022-09-20 17:40
>could we just re-authenticate on the server and continue with the request as usual + return an updated authToken?

I'm not entirely sure how this would work but really like the idea of getting rid of the reauthentication logic entirely. Seems like there is a conversation [here](https://expensify.slack.com/archives/C03TQ48KC/p1663093361547109) about this but it feels like we need someone to lead up the investigation.

**Comment by luacmartins** [comment] 2022-09-20 18:33
Oooh I like the [reconnect](https://github.com/Expensify/App/issues/11081#issuecomment-1252690279) solution. That's much cleaner than what we have now and would solve the issue 🧠

**Comment by mallenexpensify** [comment] 2022-09-20 18:52
I updated the title and OP to better represent the bug we're trying to fix.  @marcaaron and @luacmartins , can you review to see if it's accurate and edit/update if needed?

**Comment by marcaaron** [comment] 2022-09-20 19:51
@luacmartins Gonna put up a proposed change without the improvements to the other components like `EnablePaymentsPage`, but will add some logic to enabled unsubscribing from `NetworkConnection.onReconnect()` since I think we will need it.

**Closed** 2022-09-21 23:03 UTC
Labels: Reviewing, Engineering, Daily, Improvement, Internal
