### ISSUE TITLE
[$500] Scan - Manually entered merchant is replaced with Unknown Merchant with failed scanning message

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#30540] opened 2023-10-27 20:55 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.3.92-2
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** Applause - Internal Team
**Slack conversation:**

## Action Performed:
1. Go to staging.new.expensify.com
2. As employee, send a Scan request to the workspace
3. Go to expense details page
4. Manually enter the Merchant while the smartscanning is ongoing

## Expected Result:
- No system message about failed scanning because user stops the scanning by manully entering the merchant name
- The merchant name is saved and will not disappear

## Actual Result:
- After a few minutes, the system message about failed scanning shows up
- The manually entered merchant disappears. It is replaced with "Unknown Merchant" and a prompt to enter a merchant name shows up

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [x] Android: mWeb Chrome
- [x] iOS: Native
- [x] iOS: mWeb Safari
- [x] Windows: Chrome 
- [x] MacOS: Desktop

## Screenshots/Videos
<details>
<summary>Android: Native</summary>

</details>

<details>
<summary>Android: mWeb Chrome</summary>

</details>

<details>
<summary>iOS: Native</summary>

</details>

<details>
<summary>iOS: mWeb Safari</summary>

</details>

<details>
<summary>Windows: Chrome </summary>

 

https://github.com/Expensify/App/assets/78819774/f540de2f-827a-4286-9062-cfd578ea52c9

</details>

<details>
<summary>MacOS: Desktop</summary>

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~0123880782034ca8c3</li>
        <li>Upwork Job ID: 1718008539756597248</li>
        <li>Last Price Increase: 2023-11-17</li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @marcochavezf</details>

**Comment by erquhart** [comment] 2023-10-27 21:24
@lanitochka17 I've tried following your steps but a few are missing 😅, and I'm not able to reproduce the issue. I can upload a receipt and manually set the merchant name, and it stops scanning immediately. No failed scan occurs.

<img width="1087" alt="Screenshot 2023-10-27 at 5 22 41 PM" src="https://github.com/Expensify/App/assets/2112202/993a5f9b-457b-4fab-88c1-ae8a3169beed">


Can you provide complete reproduction steps in case I'm missing something?

**Comment by lanitochka17** [comment] 2023-10-30 13:16
@erquhart Hello
Sorry for the confusion
Correct steps to reproduce:
1. Go to staging.new.expensify.com
2. As employee, send a Scan request to the workspace.
3. Go to expense details page.
4. Manually enter the Merchant while the smartscanning is ongoing

**Comment by isabelastisser** [comment] 2023-10-30 16:27
@allroundexperts, can you please review and let me know if you can reproduce this? Should we close?

**Comment by isabelastisser** [comment] 2023-10-31 14:09
Thanks, @allroundexperts! Let's wait for proposals then.

**Comment by barros001** [comment] 2023-10-31 21:21
@allroundexperts @isabelastisser this looks like a BE issue. When the scan fails, it overrides the Merchant name with `Unknown Merchant` without checking if it has been updated. There's nothing on the FE that makes this change.

BE should check if merchant has been manually updated (or simply check if it's different than `(none)`) and not set it to `Unknown Merchant` if it has been updated.

**Comment by barros001** [comment] 2023-11-01 03:49
@allroundexperts when I was looking around I was watching network requests and when you edit the merchant, it posts the update back to the backend and then nothing else really happens. I was expecting the BE to push the data to the client once the scan fails but it didn’t really. Navigating away and back forces FE to pull the data again from the BE and at that point the merchant is changed to Unknown (it comes from the BE like that). That’s what made me believe it’s a backend issue, it didn’t look like the FE had much saying. But I could be missing something.

Do you have any thoughts on how this could be solved on the FE?

**Comment by isabelastisser** [comment] 2023-11-03 18:31
Hey @allroundexperts can you please follow up on the comment above? Thanks!

**Comment by isabelastisser** [comment] 2023-11-06 16:43
Bump @allroundexperts

**Comment by isabelastisser** [comment] 2023-11-06 21:27
Hey @marcochavezf, can you please help clarify @allroundexperts comment above? Thanks!

**Comment by marcochavezf** [comment] 2023-11-09 02:19
Sorry I have my plate full atm, I am aiming to check it out tomorrow.

**Comment by marcochavezf** [comment] 2023-11-11 16:48
No update

**Comment by marcochavezf** [comment] 2023-11-14 15:42
No update, still addressing other daily items

**Comment by marcochavezf** [comment] 2023-11-14 15:46
> No update, still addressing other daily items

**Comment by marcochavezf** [comment] 2023-11-20 03:44
No update

**Comment by marcochavezf** [comment] 2023-11-21 22:45
Moving it to weekly to focus on wave7

**Comment by isabelastisser** [comment] 2023-12-14 17:55
No updates.

**Comment by isabelastisser** [comment] 2023-12-14 18:15
Not overdue.

**Comment by marcochavezf** [comment] 2023-12-14 19:55
No updated

**Comment by marcochavezf** [comment] 2023-12-26 21:06
No update

**Comment by marcochavezf** [comment] 2024-01-04 19:13
I am still working on other higher-priority items, then I will continue with this one

**Comment by marcochavezf** [comment] 2024-01-15 19:29
No update

**Comment by isabelastisser** [comment] 2024-01-25 14:25
No updates. Changing to monthly.

**Comment by marcochavezf** [comment] 2024-02-09 17:07
I think this issue was already fixed by latest changes, I'm going to apply the `retest-weekly` label

**Comment by mvtglobally** [comment] 2024-03-05 04:46
Issue not reproducible during KI retests. (First week)

**Comment by marcochavezf** [comment] 2024-03-05 17:19
Cool, I'm going to close it out

**Closed by marcochavezf** 2024-03-05 17:19 UTC
Labels: Engineering, Monthly, Internal, Bug, retest-weekly
