### ISSUE TITLE
[$500] Assign task - the Task shifts position in the LHN if we delete the only message in it

### ISSUE THREAD

**Issue by izarutskaya** [Expensify/App#26479] opened 2023-09-01 13:33 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Open the app
2. Click on plus and click on assign task
3. Provide any title, select any user for share somewhere and Confirm task
4. Observe position in LHN
5. Send any text message
6. Delete sent message and observe change of position in LHN to bottom
7. Visit any other chat and revisit task chat, it will again jump to its original postion

## Expected Result:
Task position should not change in LHN on deleting any message

## Actual Result:
Task moves to bottom of LHN on deleting the only message in the task / it jumps position

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [x] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** v1.3.61-1

**Reproducible in staging?:** Y

**Reproducible in production?:** Y

**If this was caught during regression testing, add the test name, ID and link from TestRail:**

**Email or phone of affected tester (no customers):**

**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/115492554/f624e767-33b1-408a-8fe1-424a41d581c9

https://github.com/Expensify/App/assets/115492554/80e1af2a-b883-46c0-9b4f-7e428e9bd983

**Expensify/Expensify Issue URL:**

**Issue reported by:** @Dhanashree-Sawant

**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1692033299162729

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01fe04ae2863eac337</li>
        <li>Upwork Job ID: 1698487838846078976</li>
        <li>Last Price Increase: 2023-09-04</li>
    </ul>
</details>

**Comment by jliexpensify** [comment] 2023-09-04 00:04
Still seems to be occurring on v1.3.62-3 (staging) - I've noticed it jumps 1-2 positions when the message is deleted.

**Comment by mananjadhav** [comment] 2023-09-04 16:39
I think this should be fixed from the backend.

🎀 👀 🎀 C+ Reviewed.

**Comment by Li357** [comment] 2023-09-11 18:26
Hmm. I don't know if I agree @mananjadhav, just because this contradicts what `lastVisibleActionCreated` means. The CREATED report action isn't supposed to be visible, so there are no visible actions. Could we handle this in the frontend optimistically?

**Comment by Li357** [comment] 2023-09-13 18:54
@mananjadhav Bump on this!

**Comment by jliexpensify** [comment] 2023-09-16 00:39
Bump @mananjadhav to address Andrew's comments.

**Comment by mananjadhav** [comment] 2023-09-17 17:36
@jliexpensify Can you please reassign another C+? I don't have the bandwidth to investigate this.

**Comment by jliexpensify** [comment] 2023-09-17 23:27
Hi @robertKozik - re-assigning another C+, could you review this [comment](https://github.com/Expensify/App/issues/26479#issuecomment-1714377626) from Andrew and see if you agree/any past proposals fit? Thanks in advance!

**Comment by Li357** [comment] 2023-09-21 04:57
@0xmiroslav Do you think removing `lastVisibleActionCreated` in the Onyx response to keep it in the LHN is a valid solution here? IMO it's not the best but probably easily solution here without rethinking what `lastVisibleActionCreated` means.

**Comment by jliexpensify** [comment] 2023-09-25 00:40
Bumping @Li357 to address this [comment](https://github.com/Expensify/App/issues/26479#issuecomment-1728979864), thanks!

**Comment by jliexpensify** [comment] 2023-09-28 02:58
Bumping @Li357 again!

**Comment by Li357** [comment] 2023-09-28 03:37
Looking into this now!

**Comment by Li357** [comment] 2023-09-28 05:04
@0xmiroslav Can confirm this. When we delete the last action, we're setting `lastVisibleActionCreated` to an empty string, and when we call OpenReport `lastVisibleActionCreated` defaults to the current time if not present. Interestingly, I observed the same behavior with offline optimistic data as well.

I guess the solution is to set the lastVisibleActionCreated time to the current time on deleting messages, because technically deletion is an action?

**Comment by Li357** [comment] 2023-09-28 06:52
Checking internally now!

**Comment by Li357** [comment] 2023-09-28 08:20
Seems like we should keep the chat [where it is](https://expensify.slack.com/archives/C03U7DCU4/p1695883789626039) before and after the delete. So this translates to leaving `lastVisibleActionCreated` unchanged in the backend. I'll handle this.

**Comment by jliexpensify** [comment] 2023-09-28 09:15
@Li357 should this be `internal` then?

**Comment by Li357** [comment] 2023-09-29 05:24
Working on this now!

**Comment by Li357** [comment] 2023-10-02 19:28
Not overdue, this is being worked on in https://github.com/Expensify/Web-Expensify/pull/39028

**Comment by jliexpensify** [comment] 2023-10-06 03:58
Deployed to web.

**Comment by jliexpensify** [comment] 2023-10-06 04:00
@Li357 since this was marked as `Internal` are there any contributors to pay? Here's what I have so far:

Payment Summary:

- Reporter: @dhanashree-sawant $50

**Comment by Li357** [comment] 2023-10-06 04:18
@jliexpensify That seems to be it!

**Comment by jliexpensify** [comment] 2023-10-06 05:15
Paid and job closed.

@Li357 - feel free to close off this GH when you're ready! Nothing else on my end to do.

**Comment by jliexpensify** [comment] 2023-10-09 23:07
Not overdue, waiting on @Li357 to close this when ready.

**Comment by jliexpensify** [comment] 2023-10-11 21:34
@Li357 https://github.com/Expensify/Web-Expensify/pull/39028 is deployed now, can we close this issue? Cheers!

**Comment by Li357** [comment] 2023-10-12 03:29
@jliexpensify Almost! We've just to the corresponding App PR to merge: https://github.com/Expensify/App/pull/28431

**Comment by jliexpensify** [comment] 2023-10-12 09:41
Sorry for not properly communicating why - my thinking at the time was probably because you were undergoing those tax/Upworks issues so I assumed you were looking to take a step back (this was probably before you indicated you were still looking to work). Either way, this turned into an `Internal `issue so we're only paying the Bug Reporter.

**Comment by jliexpensify** [comment] 2023-10-24 00:34
Moved to weekly while we wait for Andrew to close this issue

**Comment by jliexpensify** [comment] 2023-11-12 21:14
Bump @Li357 @robertKozik [was there a regression](https://github.com/Expensify/App/issues/26479#issuecomment-1791671079)?

**Comment by robertKozik** [comment] 2023-11-13 08:42
Corresponding PR is not merged yet, so there would be no linked regression imo

**Comment by Li357** [comment] 2023-11-13 15:59
@jliexpensify @robertKozik really apologize for the delay here, this fell through the cracks. The reason why the PR hasn't gone thru yet is that for some reason the backend change that the App change depended on was reverted before I personally verified it passed QA.

**Comment by Li357** [comment] 2023-11-13 16:15
Reintroduced the backend change that was reverted. Hoping to get this done ASAP!

**Comment by jliexpensify** [comment] 2023-11-30 21:01
Deployed to prod today!

**Comment by situchan** [comment] 2023-12-18 20:25
@jliexpensify there's still app [PR](https://github.com/Expensify/App/pull/28431) in review.
As @Li357 is no longer working on Expensify, how should we proceed?

**Comment by jliexpensify** [comment] 2023-12-18 21:34
Ah, thanks for letting me know - I will reassign this one out.

**Comment by jliexpensify** [comment] 2023-12-18 21:35
Hi @blimpich - this was Andrew's PR but he's now left. Re-assigning the `Engineering` label to get it across the finish line. Please see @situchan's comment [here](https://github.com/Expensify/App/issues/26479#issuecomment-1861551172).

**Comment by blimpich** [comment] 2023-12-20 21:34
@situchan to confirm this fix still requires both a backend and a frontend fix it seems?

**Comment by situchan** [comment] 2023-12-20 21:35
yes both

**Comment by blimpich** [comment] 2023-12-20 22:11
Sounds good. @jliexpensify I'm not able to work on this at a daily cadence. I'm swamped with chore work and other commitments that have to be done by EOY, and considering its the holidays (I'm currently writing this from an airport terminal) I doubt I'll be able to get to this this week or next. I'm going to demote to weekly for now. You might be able to get someone else to work on it if you want this to move quicker.

**Comment by jliexpensify** [comment] 2023-12-27 22:12
All good @blimpich , thanks for the update! I think every Engineer is swamped so lets keep this one at `Weekly` for now.

**Comment by robertKozik** [comment] 2024-01-16 22:47
@situchan can you get assigned to this one, as youwere lastly assigned to review connected PR?

**Comment by jliexpensify** [comment] 2024-01-16 22:51
Assigned! LMK if anything else needs to be done @robertKozik

**Comment by robertKozik** [comment] 2024-01-16 22:59
Thanks 🙇🏼 , I think it would me all from me as I was not working on that issue for a long time and @situchan take the PR review over.

**Comment by jliexpensify** [comment] 2024-03-17 23:32
@situchan @blimpich how are we going here? This issue is a couple of months old, anything we need to do to push it along/resolve it?

**Comment by blimpich** [comment] 2024-03-26 01:25
@jliexpensify Can we categorize this under a wave and try to get it prioritized there? That would help. I don't have the time to pick this up as I'm working on p2p receipts which is higher priority.

I'm going to unassign myself as I won't be able to get to this anytime in the near future.

**Comment by jliexpensify** [comment] 2024-03-31 23:34
Sure thing @blimpich (sorry was OOO)

**Comment by blimpich** [comment] 2024-05-27 22:56
Added hot pick and removed reviewing label to help get this picked up

**Comment by jliexpensify** [comment] 2024-06-06 03:03
Thanks Ben! Not overdue

**Comment by mvtglobally** [comment] 2024-07-03 14:33
Issue not reproducible during KI retests. (First week)

**Comment by jliexpensify** [comment] 2024-07-18 04:25
Cool lets see if this pops up again. @mvtglobally can you re-test?

**Comment by mvtglobally** [comment] 2024-08-09 04:24
Issue not reproducible during KI retests. (Second week)

**Comment by jliexpensify** [comment] 2024-08-09 04:27
Sweet, lets close this. We are deprioritising VSB anyway.

**Closed by jliexpensify** 2024-08-09 04:27 UTC
Labels: Engineering, Weekly, Internal, Overdue, Bug, Hot Pick

**Comment by situchan** [comment] 2024-08-12 04:33
@jliexpensify can I get compensation for reviewing [PR](https://github.com/Expensify/App/pull/28431)?

**Comment by jliexpensify** [comment] 2024-08-12 04:46
@situchan hmm my first thought is that you wouldn't be eligible, as the PR was never deployed. It looks like @Li357 gave context and then you had the last [comment](https://github.com/Expensify/App/pull/28431#issuecomment-1836553519), but then nothing after that.

Was this PR actually merged or deployed?

**Comment by situchan** [comment] 2024-08-12 04:56
I had commented with test result [here](https://github.com/Expensify/App/pull/28431#pullrequestreview-1758220453).

PR was not merged.
Maybe this is the case in C+ doc: 
https://docs.google.com/document/d/1BvohU05MTaHnjOD_vwJv_aqDAirv-ChkyRnKCAvOVyQ/edit?pli=1#heading=h.4qk1t4qmcejy (17. b.)

**Comment by jliexpensify** [comment] 2024-08-12 05:04
@situchan If I am understanding correctly, you might qualify for this?

>If a C+ invested time in the issue or PR and they feel they are due compensation they should wait until any dupe, held or >related issues are closed.  They should then post in #contributor-plus and:
>1. Tag the BZ and internal engineer
>Link to the GH issue and/or PR.
>Provide brief, yet detailed, reasoning for compensation
>State the amount they feel they’re due.   Standard percentages are 25, 50 and 100% of the job price. 

Are you able to share a post and tag me?
