### ISSUE TITLE
Chat - +Emoji reaction button is not responding after creating thread to message - iOS

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#21731] opened 2023-06-27 19:02 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Open any chat
2. Send a message
3. Add an emoji reaction to the message
4. Press "Reply in thread" on the message
5. Go back
6. Long press/right-click the emoji reaction

## Expected Result:
Emoji reaction picker should appear

## Actual Result:
Button is not responding

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [x] iOS / native
- [ ] iOS / Safari
- [ ] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 1.3.33.3

**Reproducible in staging?:** Yes

**Reproducible in production?:** Yes

**If this was caught during regression testing, add the test name, ID and link from TestRail:**

**Email or phone of affected tester (no customers):**

**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/78819774/8d2f84be-3fbc-4b62-b731-ffc1382273bb

**Expensify/Expensify Issue URL:**

**Issue reported by:** Applause - Internal Team

**Slack conversation:**

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by alexpensify** [comment] 2023-06-29 22:36
Reassigning another `bug` team member, I'm going OOO until Monday, July 10, and will take it back if it's still open by my return date. 

Required action from the 🐛 team: I've run out of time and haven't tested this one yet. This needs testing to confirm if it's a bug and then assign the applicable labels. Thank you!

**Comment by CortneyOfstad** [comment] 2023-06-30 19:32
Hahahahaha I'm also OoO for the week (back July 10) so re-assigning this in the meantime 😂

**Comment by puneetlath** [comment] 2023-07-03 19:18
I'm not able to reproduce this. Just tried on iOS and long-pressing the emoji reaction worked fine after creating the thread.

**Closed by puneetlath** 2023-07-03 19:18 UTC
Labels: Daily, Overdue, Bug

**Comment by alexpensify** [comment] 2023-07-10 21:14
I appreciate your help!
