### ISSUE TITLE
[HOLD #43783][$250] Accounting - Submit button flickers in and out for non-admin submitter immediately after clicking Submit

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#45624] opened 2024-07-17 17:41 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 9.0.8-0
**Reproducible in staging?:** Y
**Reproducible in production?:** N
**If this was caught during regression testing, add the test name, ID and link from TestRail:** N/A
**Issue reported by:** Applause - Internal Team

**Issue found when executing PR** https://github.com/Expensify/App/pull/44170
## Action Performed:
Pre-requisite:
- Have a collect workspace
- Enable delayed submission for the workspace
- Create either a QBO or Xero connection
1. Navigate to staging.new.expensify.com
2. Sign in as the admin of the workspace
3. Create an expense in the workspace chat
4. Navigate to the combined expense report page and click on submit
5. Wait for a few seconds and observe the header button
6. Navigate back to the workspace chat page
7. Navigate back to the combined expense report page

## Expected Result:
Right after a non-admin submitter clicks submit, the Submit button should disappear and no other button should show up.

## Actual Result:
After a non-admin submits the expense, a Pay button shows up where the Submit button was before.

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [x] Android: mWeb Chrome
- [x] iOS: Native
- [x] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details> 

https://github.com/user-attachments/assets/a11a832f-89ee-4b3d-94f7-6728d83897d8

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~011ac532d9ba102642</li>
        <li>Upwork Job ID: 1813660172360646886</li>
        <li>Last Price Increase: 2024-08-07</li>
    </ul>
</details>

**Comment by francoisl** [comment] 2024-07-17 18:02
Going to look at that previous PR to see if anything stands out.

In the meantime, /cc @kosmydel @hungvu193 if you have any idea

**Comment by francoisl** [comment] 2024-07-17 21:45
In the meantime, [here's a draft revert](https://github.com/Expensify/App/pull/45641) if we can't figure out a fix.

**Comment by kosmydel** [comment] 2024-07-18 06:33
This problem must have been present before, but instead of displaying the "Export" button, no button was shown at all.

```typescript
const shouldShowExportIntegrationButton = !shouldShowPayButton && !shouldShowSubmitButton && connectedIntegration && !!policy;
```
As we can see, the `Pay` button has higher priority, and if it is displayed, the export integration button must be hidden.

**Comment by trjExpensify** [comment] 2024-07-18 09:53
Okay, I did two tests on production to corroborate that theory a bit, @kosmydel. 

Workflows config: 

- Delayed submission: Enabled
- Approvals: Disabled 
- Payments: Enabled

Result: The pay button appears immediately after clicking `Submit`. 

https://github.com/user-attachments/assets/bb5b5d21-1154-4601-8a46-12eb5b5238e5

Workflows config:

- Delayed submission: Enabled
- Approvals: Disabled 
- Payments: Disabled

Result: There's a brief flash of the `Submit` button after clicking submit, and then no button. 

https://github.com/user-attachments/assets/b9545d30-4d8e-4e97-a714-00ef52b11b7e

**Comment by mountiny** [comment] 2024-07-18 10:01
We are going to demote this one as it is specific to the admin submitting on a policy with a specific setup so it is not very common case, additionally, it can be fixed by revisiting the report.

Looking for a proposal to fix this flicker of the incorrect button

**Comment by lakchote** [comment] 2024-07-18 11:31
With [this](https://github.com/Expensify/App/pull/45577) PR that fixes the `Export` option showing wrongfully for workspace members (it should only be for admins), there's still a glitch.

Now, it's the `Submit` button that is showing briefly before changing back to the `Pay` button.

https://github.com/user-attachments/assets/868d6428-c276-477f-a037-a6cd2d2916d4

**Comment by mountiny** [comment] 2024-07-18 11:35
Nice, thanks for testing again. This just supports the theory the optimistic data is somewhat incorrect probably for this specific submit and close setting

**Comment by sakluger** [comment] 2024-07-23 22:58
Still looking for proposals.

**Comment by sakluger** [comment] 2024-07-23 22:59
Still looking for proposals.

**Comment by sakluger** [comment] 2024-07-29 21:15
Still no new proposals.

**Comment by sakluger** [comment] 2024-08-05 16:09
No new proposals.

**Comment by war-in** [comment] 2024-08-08 11:42
Hi 👋 I'm Marcin from Software Mansion, an expert agency, and I started investigating this issue.

I found out that after clicking the submit button `SubmitReport` API call is performed and it returns correct `stateNum` and `statusNum` values (both different than `0`).

But immediately after this call, there is another one `GetMissingOnyxMessages` and it sets `statusNum` and `stateNum` to 0 again (which is wrong after a successful submit call).

From [another issue](https://github.com/Expensify/App/pull/46671#issuecomment-2263523690), I know that `GetMissingOnycMessages` is used when there are some gaps detected in the onyx update. Does anyone have some context and maybe ideas on what is happening here?

**Comment by war-in** [comment] 2024-08-08 13:21
What's even more interesting is that it's not always reproducible. It happens often after creating a new workspace but not always 🤷

**Comment by trjExpensify** [comment] 2024-08-08 14:55
Trying to think who would have the most context on this flow, @mountiny probably for manual `Submit` from the drafts project?

**Comment by trjExpensify** [comment] 2024-08-08 15:00
Also, @sakluger, I think the OP and title of this issue are outdated. The export to Pay problem is solved, it's not the Pay/Submit scenarios when re-reading the history. 

Non-admin submitter gets a brief flicker of the submit button: https://github.com/Expensify/App/issues/45624#issuecomment-2236098279
Admin submitter gets a brief flicker of pay button, submit button, pay button again: https://github.com/Expensify/App/issues/45624#issuecomment-2236273958

Can you update to reflect the current state of the problems left to solve? Thanks!

**Comment by trjExpensify** [comment] 2024-08-08 20:05
Ah, I think we can close this and progress the `Approve` and `Submit` button flickers [here](https://github.com/Expensify/App/issues/43783#issuecomment-2276563214).

**Comment by mountiny** [comment] 2024-08-08 23:59
It seems like some race condition, and later, we sent the missed onyx updates, which reverted the state of the report. 

What is confusing is that its not reliably reproducible with drafts/ submit flow based on the comments so it does not seem like an issue in the Submit flow purely

**Comment by francoisl** [comment] 2024-08-12 16:31
Sounds good. Hopefully the fix for https://github.com/Expensify/App/issues/43783 will also fix this, let's revisit when it's sorted out.

**Comment by sakluger** [comment] 2024-08-13 16:09
Sorry guys, catching up on this one. Thanks for putting this on hold for https://github.com/Expensify/App/issues/43783!

Regarding the correct expected behavior vs actual behavior, a non-admin submitter should see no button after clicking submit, right?

**Comment by trjExpensify** [comment] 2024-08-13 16:14
Correct that non-admin submitter case what happens is that it flickers. I.e the submit button disappears, comes back briefly, goes away again.

**Comment by sakluger** [comment] 2024-08-24 02:03
Still on hold

**Comment by sakluger** [comment] 2024-09-11 23:56
Still on hold for https://github.com/Expensify/App/issues/43783

**Comment by francoisl** [comment] 2024-09-24 00:56
still on hold for the above ^

**Comment by francoisl** [comment] 2024-10-02 19:54
Still on hold

**Comment by sakluger** [comment] 2024-10-21 16:10
Still on hold.

**Comment by sakluger** [comment] 2024-10-31 02:14
Looks like the hold issue (https://github.com/Expensify/App/issues/43783) has been closed because it's no longer reproduceable, and a new, similar issue is being worked on here: https://github.com/Expensify/App/issues/43783#issuecomment-2434525091. @francoisl what do you think we should do for this one?

**Comment by sakluger** [comment] 2024-11-11 19:33
Let's close since Francois can't reproduce.

**Closed by sakluger** 2024-11-11 19:33 UTC
Labels: External, Engineering, Weekly, Help Wanted, Overdue, Bug
