### ISSUE TITLE
[$500] Workspace - Opening whisper message for member in thread as admin returns "Auth OpenReport" error

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#32687] opened 2023-12-07 16:59 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.9-2
**Reproducible in staging?:** Y
**Reproducible in production?:** Y 
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** Applause - Internal Team
**Slack conversation:**

## Action Performed:
1. [Member] Create an expense request in the workspace chat
2. [Admin] Open the workspace chat with employee
3. [Admin] Right click on the whisper message that is meant for workspace member
4. [Admin] Click Reply in thread

## Expected Result:
There should be no error when opening the welcome message in thread

## Actual Result:
"Auth OpenReport returned an error" when opening whisper message for workspace member as admin

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [x] Android: mWeb Chrome
- [x] iOS: Native
- [x] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details> 

https://github.com/Expensify/App/assets/78819774/f3e284ff-0a33-42b9-97fa-4690e2f03b35

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~015e12a0f66eba12a3</li>
        <li>Upwork Job ID: 1732807094997897216</li>
        <li>Last Price Increase: 2023-12-07</li>
    </ul>
</details>

**Comment by abeebridwan** [comment] 2023-12-07 22:23
@lanitochka17 couldn't reproduce the error

**Comment by Balogh08** [comment] 2023-12-10 17:58
## Proposal

### Please re-state the problem that we are trying to solve in this issue.

Opening whisper message for member in thread as admin returns "Auth OpenReport" error.

### What is the root cause of that problem?

`Admin` user can see messages that are `Only visible to XY user.` In this case, the admin user also has the option to choose the `Reply in thread` option. However, the admin user has only a read option for those messages and no write option.

### What changes do you think we should make in order to solve the problem?

The `Reply in thread` option should not be visible or clickable in case of having only a read option for a message like an admin has in case of a workspace created by himself.

### What alternative solutions did you explore? (Optional)

The admin should have a write option for whisper messages if it is a goal to allow the admin to reply to such messages which are supposed to be visible only to certain users.

![image](https://github.com/Expensify/App/assets/44845895/59dbb006-0147-4579-87d6-402b54b49ebc)

**Comment by anmurali** [comment] 2023-12-12 16:35
The reproduction steps do not make sense. If there is a message shown only to employees (members), then how can the admin thread up on this? It isn't even shown to the admin

Employee view
<img width="1446" alt="image" src="https://github.com/Expensify/App/assets/14225673/62ed5caa-7fdf-41b3-8c76-033fdde3d2ad">

Manager view
<img width="1070" alt="image" src="https://github.com/Expensify/App/assets/14225673/2939e2ae-3800-47c5-b5af-99890ad8a187">

I am closing this. Please reopen with clear reproduction steps.

**Closed by anmurali** 2023-12-12 16:35 UTC
Labels: External, Daily, Help Wanted, Overdue, Bug
