### ISSUE TITLE
[HOLD][$250] Search - Suggestion still shows the report when it is already selected as search query

### ISSUE THREAD

**Issue by IuliiaHerets** [Expensify/App#52213] opened 2024-11-07 18:56 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 9.0.59-0
**Reproducible in staging?:** Y
**Reproducible in production?:** N
**Email or phone of affected tester (no customers):** applausetester+khcategory18@applause.expensifail.com
**Issue reported by:** Applause Internal Team

## Action Performed:
1. Go to staging.new.expensify.com
2. Open any report.
3. Open search router.
4. Enter in: followed by report name.
5. Select the report from the suggestion.

## Expected Result:
The suggestion will not show the selected report because the report is already selected (production behavior).

## Actual Result:
The suggestion shows the selected report when the report is already selected.
This issue only happens with in: search query and does not happen with from, to, category, tag etc

## Workaround:
Unknown

## Platforms:

- [x] Android: Standalone
- [x] Android: HybridApp
- [x] Android: mWeb Chrome
- [x] iOS: Standalone
- [ ] iOS: HybridApp
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

https://github.com/user-attachments/assets/ccf71737-2285-4522-8c5d-63cb97c6d89c
 
</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~021854651066569405634</li>
        <li>Upwork Job ID: 1854651066569405634</li>
        <li>Last Price Increase: 2024-11-14</li>
    </ul>
</details>

**Comment by nkdengineer** [comment] 2024-11-07 20:05
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
The suggestion shows the selected report when the report is already selected.
This issue only happens with in: search query and does not happen with from, to, category, tag etc

### What is the root cause of that problem?

We are missing the filter in type in with `alreadyAutocompletedKeys` value similar to what we did with other types

https://github.com/Expensify/App/blob/e3e4e53497f2f61d81e07b484f876512a3634598/src/components/Search/SearchRouter/SearchRouter.tsx#L251-L254

### What changes do you think we should make in order to solve the problem?


We should add condition with `alreadyAutocompletedKeys` value in filter function [here](https://github.com/Expensify/App/blob/e3e4e53497f2f61d81e07b484f876512a3634598/src/components/Search/SearchRouter/SearchRouter.tsx#L251-L254)

```
const filteredChats = searchOptions.recentReports
      .filter((chat) => chat.text?.toLowerCase()?.includes(autocompleteValue.toLowerCase()) && !alreadyAutocompletedKeys.includes(chat.text?.toLowerCase()))
      .sort((chatA, chatB) => (chatA > chatB ? 1 : -1))
      .slice(0, 10);
```

### What alternative solutions did you explore? (Optional)
NA

**Comment by MarioExpensify** [comment] 2024-11-07 22:22
I was able to reproduce here, but hardly a deploy blocker. Let's make this External and move forward with the deploy.

**Comment by mohit6789** [comment] 2024-11-08 06:36
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
Selected search item does not disappear from the suggestions list when using "in:" search query. Expected behavior works correctly for other types of queries.

### What is the root cause of that problem?
In case of "in:" search query, we have missed to filter the suggestion list(``!alreadyAutocompletedKeys.includes(chat.text.toLowerCase())``) if it is already selected which already done for other types of search queries. 

```
 const filteredChats = searchOptions.recentReports
       .filter((chat) => chat.text?.toLowerCase()?.includes(autocompleteValue.toLowerCase()))
```

### What changes do you think we should make in order to solve the problem?
The simplest fix would be to filter the autocomplete list by adding `!alreadyAutocompletedKeys.includes(chat.text.toLowerCase())`, as we’ve done in other places. However, I suggest an alternative, more scalable solution that will be beneficial in the long term.

```
const filteredChats = searchOptions.recentReports
       .filter((chat) => chat.text?.toLowerCase()?.includes(autocompleteValue.toLowerCase()))
```

### What alternative solutions did you explore? (Optional)

The filtering logic for all search query types is currently the same. I suggest extracting this logic into a reusable function. This way, if a new query type is added or the filtering logic changes in the future, updates can be made in a single place, applying uniformly to all search types (e.g., "in:", "to:", "from:"). This will help prevent bugs like the current issue, where conditions may be missed.

```
function getFilteredAutoCompleteList(value: string) {
       return value?.includes(autocompleteValue.toLowerCase()) && !alreadyAutocompletedKeys.includes(value);
}
```

**Comment by mohit6789** [comment] 2024-11-08 06:39
Contributor details
Your Expensify account email: mohitraichura2000@gmail.com
Upwork Profile Link: [Upwork](https://www.upwork.com/freelancers/~010d1a48aa44cfc1f5)

**Comment by MarioExpensify** [comment] 2024-11-11 17:56
I'm sorry @ntdiary, not sure I got that, are we handling this in the other issue already?

**Comment by johncschuster** [comment] 2024-11-11 22:17
@ntdiary bump on the question above!

**Comment by MarioExpensify** [comment] 2024-11-12 11:22
Thank you @ntdiary for the details!! Yes, sounds like we could hold onto this then. CC: @johncschuster

**Comment by johncschuster** [comment] 2024-11-15 22:53
Thanks, @ntdiary! Is there an open issue I can reference that we're holding this on?

**Comment by nkdengineer** [comment] 2024-11-19 03:11
@ntdiary This issue has been marked as `External` so I think the contributor's solution should be prioritized here. Could you please take a look at the contributors' proposals?

**Comment by johncschuster** [comment] 2024-11-25 21:53
This is on hold

**Comment by MarioExpensify** [comment] 2024-11-28 11:08
On hold, not overdue! Moving this to Weekly so it stop being tagged as overdue CC @johncschuster

**Comment by johncschuster** [comment] 2024-12-11 22:46
Thanks for your patience on this one! I've reviewed the internal payment docs, and it looks like @nkdengineer should be compensated for the solution that we wound up using.

I'll create an Upwork job for that now.

**Comment by johncschuster** [comment] 2024-12-11 22:55
Job is [here](https://www.upwork.com/ab/applicants/1866978450904602315/job-details)

**Comment by johncschuster** [comment] 2024-12-12 15:11
Great question, @ntdiary! I was so focused on the "solution" that I didn't check for that in our docs. Let me check and come back to you on that.

**Comment by johncschuster** [comment] 2024-12-13 23:18
@ntdiary thanks for your patience! Yes, I will issue the same 50% to you as I would to @nkdengineer for their work on this issue. I've sent you an [invite](https://www.upwork.com/nx/wm/offer/105329731) to the job. Please ping me when you've accepted that so I can pay this out!

**Comment by JmillsExpensify** [comment] 2024-12-16 11:40
Yes, I only need he payment summary to approve the ND payment.

**Comment by johncschuster** [comment] 2024-12-16 15:37
Oh darn it. Thanks for calling that out, @ntdiary! Summary incoming.

**Comment by johncschuster** [comment] 2024-12-16 15:38
# Payment Summary:

Contributor: @nkdengineer paid $125 via Upwork

Contributor+: @ntdiary due $125 via NewDot

Upwork job [here](https://www.upwork.com/ab/applicants/1866978450904602315/job-details)! Please apply

**Comment by johncschuster** [comment] 2024-12-18 20:25
@nkdengineer can you please accept the Upwork offer above so I can pay this out before I head out on holiday OOO?

**Comment by nkdengineer** [comment] 2024-12-19 04:32
@johncschuster I did. Enjoy your break! 🍷

**Comment by JmillsExpensify** [comment] 2024-12-19 09:44
$125 approved for @ntdiary

**Comment by johncschuster** [comment] 2024-12-19 15:53
Payment has been issued. Thanks, everyone!

**Closed by johncschuster** 2024-12-19 15:53 UTC
Labels: External, Engineering, Weekly, Help Wanted, Bug
