### ISSUE TITLE
[HOLD for payment 2024-12-09] [$250] Search - Workspace switcher resets to Expensify after manually searching via search input

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#51416] opened 2024-10-24 14:03 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 9.0.53-0
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**If this was caught on HybridApp, is this reproducible on New Expensify Standalone?:** N/A
**If this was caught during regression testing, add the test name, ID and link from TestRail:** N/A
**Email or phone of affected tester (no customers):** applausetester+kh1610015@applause.expensifail.com
**Issue reported by:** Applause - Internal Team

## Action Performed:
1. Go to staging.new.expensify.com
2. Go to Search
3. Click Filters
4. Apply any filter and click Save
5. Click View results
6. Open workspace switcher and select a workspace
8. Click on the search input field
9. Type any query and hit Enter

## Expected Result:
The workspace switcher will not change after manually typing on the search field and hitting Enter

## Actual Result:
The workspace switcher changes to Expensify after manually typing on the search field and hitting Enter

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Standalone
- [ ] Android: HybridApp
- [ ] Android: mWeb Chrome
- [ ] iOS: Standalone
- [ ] iOS: HybridApp
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

<details>
  <summary>Add any screenshot/video evidence</summary>

  
</details> 

https://github.com/user-attachments/assets/ebaf0fe8-4f29-4cd9-b509-c10f696baf62

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~021851453987704756817</li>
        <li>Upwork Job ID: 1851453987704756817</li>
        <li>Last Price Increase: 2024-11-06</li>
<li>Automatic offers: </li>
<ul>
<li>Krishna2323 | Contributor | 104839473</li>
</ul></li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @eVoloshchak</details>

**Comment by lanitochka17** [comment] 2024-10-24 14:03
@RachCHopkins  FYI I haven't added the External label as I wasn't 100% sure about this issue. Please take a look and add the label if you agree it's a bug and can be handled by external contributors

**Comment by lanitochka17** [comment] 2024-10-24 14:04
We think that this bug might be related to #wave-control

**Comment by shahinyan11** [comment] 2024-10-24 14:49
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
Search - Workspace switcher resets to Expensify after manually searching via search input
### What is the root cause of that problem?
[Here](https://github.com/Expensify/App/blob/642fd97e9a078495176e01b3ac17d01262bf1fa4/src/components/Search/SearchPageHeader.tsx#L342C32-L342C69) we  build search query from `inputValue` which does not contain `policyId`
### What changes do you think we should make in order to solve the problem?
Update [inputQueryJSON](https://github.com/Expensify/App/blob/642fd97e9a078495176e01b3ac17d01262bf1fa4/src/components/Search/SearchPageHeader.tsx#L344C77-L344C91) parameter  to `{...queryJSON, ...inputQueryJSON}`


### What alternative solutions did you explore? (Optional)

**Comment by RachCHopkins** [comment] 2024-10-29 05:01
Will triage tomorrow.

**Comment by RachCHopkins** [comment] 2024-10-30 02:39
Easy to Repro. I did not know the workspace switcher was a thing!

**Comment by RachCHopkins** [comment] 2024-11-05 05:19
@eVoloshchak how do you feel about the proposals so far?

**Comment by eVoloshchak** [comment] 2024-11-10 22:49
@Krishna2323's [proposal](https://github.com/Expensify/App/issues/51416#issuecomment-2435472317) looks good to me!

> We should also look for the same bug in other places.

The same bug occurs with a simple search (without selecting a category), this does seem to resolve this issue for any search query

🎀👀🎀 C+ reviewed!

**Comment by lakchote** [comment] 2024-11-11 09:12
@Krishna2323's proposal LGTM.

**Comment by lakchote** [comment] 2024-11-13 09:16
@Krishna2323 in your test you switch to another workspace, then you search for something and select a result corresponding to yet another workspace.

In my opinion, we should switch to the workspace of the search's result selected in the search router.

What's your opinion @luacmartins?

**Comment by luacmartins** [comment] 2024-11-13 19:28
I think this issue is similar to https://github.com/Expensify/App/issues/49637, where we want to keep the workspace switcher and not clear it when the user makes a search either typed in the router or via the UI filters. cc @Kicu

**Comment by Kicu** [comment] 2024-11-14 08:31
I agree, in fact this feels like a regression. I swear that I seem to remember working on this, and the scenario shown in the video from @Krishna2323 used to work 🤔 

I believe when submitting the search query that the user typed in, we should check if there is a workspace selected, and if yes then add `policyID` to final query. 
The mechanism that correctly sets workspace switcher when `policyID` is in search query is already in the code and works (I verified on stage).

**Comment by RachCHopkins** [comment] 2024-12-02 06:16
@lakchote @luacmartins @eVoloshchak forgive my ignorance here - what is the next step for this issue? We need to make it work how @Kicu describes above?

**Comment by lakchote** [comment] 2024-12-02 07:40
> @lakchote @luacmartins @eVoloshchak forgive my ignorance here - what is the next step for this issue? We need to make it work how @Kicu describes above?

Yes, we'll make it work like @Kicu described above

@Krishna2323 raised a [PR](https://github.com/Expensify/App/pull/52374) that was merged to fix the issue

**Comment by RachCHopkins** [comment] 2024-12-10 01:55
@eVoloshchak can you please do the checklist so that I can pay people? Thanks!

**Comment by lakchote** [comment] 2024-12-13 09:28
@eVoloshchak friendly bump!

**Comment by eVoloshchak** [comment] 2024-12-16 21:28
- The PR that introduced the bug has been identified. Link to the PR: there isn't a PR that has introduced this bug, this is a functionality that was missed initially
- The offending PR has been commented on, pointing out the bug it caused and why, so the author and reviewers can learn from the mistake. Link to comment: N/A
- A discussion in #expensify-bugs has been started about whether any other steps should be taken (e.g. updating the PR review checklist) in order to catch this type of bug sooner. Link to discussion: Don't think an additional discussion is needed

Regression Test Proposal

1. Go to Search
2. Click Filters
3. Apply any filter and click Save
4. Click View results
5. Open the workspace switcher and select a workspace
6. Click on the search input field
7. Type any query and hit Enter
8. Verify that the active workspace is not changed in the workspace switcher

Do we agree 👍 or 👎

**Comment by RachCHopkins** [comment] 2024-12-18 04:30
Payment Summary:

- Contributor: @Krishna2323 paid $250 via Upwork
- Contributor+: @eVoloshchak to be paid $250 via newdot manual request

Upwork job [here](https://www.upwork.com/jobs/~021851453987704756817)

**Comment by RachCHopkins** [comment] 2024-12-18 04:31
Contributor has been paid, the contract has been completed, and the Upwork post has been closed.

**Closed by RachCHopkins** 2024-12-18 04:31 UTC
Labels: External, Daily, Awaiting Payment, Bug
