### ISSUE TITLE
[PAID] [HOLD for payment 2023-10-13] [$250] Distance - App crashes when clicking "Replace" while replacing images in IOU.

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#28909] opened 2023-10-05 12:17 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Open FAB and select "Request Money" in Distance Mode.
2. Add start and end points, create a workspace, and split the bill.
3. Go to IOU, click on the map image, and select the three dots in the top right corner. From the dropdown, select "Replace".
4. The app crashes.

## Expected Result:
The app should not crash when replacing images in IOU.

## Actual Result:
App crashes when clicking "Replace" while replacing images in IOU.

## Workaround:
Unknown 

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android / native
- [x] Android / Chrome
- [x] iOS / native
- [x] iOS / Safari
- [x] MacOS / Chrome / Safari
- [x] MacOS / Desktop

**Version Number:** 1.3.78.0
**Reproducible in staging?:** y
**Reproducible in production?:** n
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/93399543/4f45fd3e-1287-40c8-8183-594d0451f49b

https://github.com/Expensify/App/assets/93399543/c9803c07-4e03-48cd-bd96-2c79fb08187b

https://github.com/Expensify/App/assets/93399543/8100571e-04e2-4fa2-add3-565ed19d89b1

https://github.com/Expensify/App/assets/93399543/9014e5df-b55d-4c56-ae96-20b273ada4c4

https://github.com/Expensify/App/assets/93399543/6ac9f646-5682-4a92-9cea-bb07f1390d2c

https://github.com/Expensify/App/assets/93399543/44ae3d32-4208-433e-82b7-023b240305e8

**Expensify/Expensify Issue URL:**
**Issue reported by:** @tewodrosGirmaA
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1696478163356909

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01324cd349c7f43f8b</li>
        <li>Upwork Job ID: 1709905823974797312</li>
        <li>Last Price Increase: 2023-10-05</li>
    </ul>
</details>

**Comment by gadhiyamanan** [comment] 2023-10-05 12:17
## Proposal  

### Please re-state the problem that we are trying to solve in this issue.
 App crashes on click of  "Replace" 
### What is the root cause of that problem?
We caring wrong route [here]([https://github.com/Expensify/App/blob/1eae8007bb79e7913b039182224c1ac3efc04e8c/src/components/AttachmentModal.js#L351](https://github.com/Expensify/App/blob/56eda28adc69f0a851d29f70427cf38c4bebfc89/src/pages/home/report/ContextMenu/ContextMenuActions.js#L375))
### What changes do you think we should make in order to solve the problem? 

use ROUTES.EDIT_REQUEST.getRoute instead of ROUTES.getEditRequestRoute  

https://github.com/Expensify/App/blob/1eae8007bb79e7913b039182224c1ac3efc04e8c/src/components/AttachmentModal.js#L351

**Comment by mountiny** [comment] 2023-10-05 12:19
@gadhiyamanan thanks! What PR in staging deploy is this coming from please?

**Comment by gadhiyamanan** [comment] 2023-10-05 12:21
might be related to [this](https://github.com/Expensify/App/pull/28890)

**Comment by mountiny** [comment] 2023-10-05 14:50
This is fixed 

@strepanier03 Can you please pay $50 to @tewodrosGirmaA for reporting. Then we can close this

**Comment by mountiny** [comment] 2023-10-09 22:28
No regression test required here, this offending PR was identified and fixed promptly as this was a deploy blocker.

@strepanier03 only pending item on this issue is to pay $50 to @tewodrosGirmaA thank you

**Comment by strepanier03** [comment] 2023-10-16 20:13
@tewodrosGirmaA - I have hired you in Upwork and will check for payout later today.

**Comment by tewodrosGirmaA** [comment] 2023-10-16 23:30
@strepanier03 , I accepted the  offer , Thank you

**Comment by strepanier03** [comment] 2023-10-17 00:21
Thank you @tewodrosGirmaA - I've paid you via Upwork and closed the contract. Thanks for being part of the community!

**Closed by strepanier03** 2023-10-17 00:21 UTC
Labels: External, Engineering, Daily, Awaiting Payment, Bug
