### ISSUE TITLE
[$500] iOS - Chat - When zooming out, the view moves to the center of the image and then zooms out

### ISSUE THREAD

**Issue by izarutskaya** [Expensify/App#37881] opened 2024-03-07 10:26 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** v1.4.48-0
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**If this was caught during regression testing, add the test name, ID and link from TestRail:** https://expensify.testrail.io/index.php?/tests/view/4398231
**Email or phone of affected tester (no customers):** vdargentotest+ios030624@gmail.com
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Issue reported by:** Applause-Internal Team

## Action Performed:
Pre-requisite: the user must be logged in.

1. Go to any chat.
2. Send an image.
3. Tap in the image preview.
4. Zoom in to any part of the image that is not the center of the image (zoom in until you can not zoom in more).
5. Double tap to zoom out.
6. Verify the zoomed view moves to the center of the image and then zooms out.

## Expected Result:
The image should be zoomed out from where it is being viewed.

## Actual Result:
The zoomed view moves to the center of the image and then zooms out

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [x] iOS: Native
- [ ] iOS: mWeb Safari
- [ ] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

https://github.com/Expensify/App/assets/115492554/b8ee39dd-48a2-4887-adb5-2a6c3b0478bd

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01a650e676617043f0</li>
        <li>Upwork Job ID: 1769684946328784896</li>
        <li>Last Price Increase: 2024-03-25</li>
    </ul>
</details>

**Comment by izarutskaya** [comment] 2024-03-07 10:27
@sonialiap I haven't added the External label as I wasn't 100% sure about this issue. Please take a look and add the label if you agree it's a bug and can be handled by external contributors.


We think that this bug might be related to #vip-vsb
CC @quinthar

**Comment by bernhardoj** [comment] 2024-03-08 15:19
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
When zooming out with a double click, the scale animation starts from the center of the image instead of the current position.

### What is the root cause of that problem?
Zooming out with a double click will call `reset` which resets each value to its initial value. For the offset value, we reset it immediately without doing an animation.
https://github.com/Expensify/App/blob/2c5d6c54d4c216746325754211af43ceeae14102/src/components/MultiGestureCanvas/index.tsx#L119-L134

That's why the scaling animation starts from the center because the offset is already 0. Previously, we set an animation for the offset value, but changed in this [PR](https://www.github.com/Expensify/App/pull/35931) to solve this [issue](https://www.github.com/Expensify/App/issues/35383).

### What changes do you think we should make in order to solve the problem?

Animate the offset back as we did before. (ofc when `animated` is true)

```
offsetX.value = withSpring(0, SPRING_CONFIG);
offsetY.value = withSpring(0, SPRING_CONFIG);
```

Then, we need to refix this [issue](https://www.github.com/Expensify/App/issues/35383). The issue is that the image "disappears" when triple-clicking a zoomed image. The root cause in short is that the first 2 clicks zooms out the image animating the scale and the offset, but the 3rd click triggers the single tap gesture which stops the offset animation. So, basically, the image is out of the boundary.

If we look at the comment on the stop animation code, it mentions that it's to stop the decay animation of the pan gesture. (it's when you drag the image horizontally/vertically and then do a tap to stop the scroll/the decay effect to continue)
https://github.com/Expensify/App/blob/2c5d6c54d4c216746325754211af43ceeae14102/src/components/MultiGestureCanvas/index.tsx#L108-L114

But in our case, it's a zoom animation which I believe we shouldn't reset the ongoing offset animation. To solve this issue, we will reset the animation only if the pan decay animation is happening. We can have 2 new shared values (`useSharedValue`) called `shouldStopOffsetX` and `shouldStopOffsetY` and we pass them to `usePanGesture`. `usePanGesture` will set the value to true when the animation starts and to false when the animation is done.

For example,
https://github.com/Expensify/App/blob/69b2c8797a0022e60b1938ed75aacbe529c69cd9/src/components/MultiGestureCanvas/usePanGesture.ts#L114-L122

```
shouldStopOffsetX.value = true;
offsetX.value = withDecay({...}, () => shouldStopOffsetX.value = false)
```

Then, in the stop animation code, we will stop it only if `shouldStopOffsetX` or `shouldStopOffsetY` is true.
```
if (shouldStopOffsetX.value) cancelAnimation(offsetX);
if (shouldStopOffsetY.value) cancelAnimation(offsetY);
```

_FYI, the offset animation is started only by pan and double tap gesture and basically we want to stop the animation only if the pan is within the boundary (it will use the decay animation)_

This will also fix an issue where the offset doesn't animate back to the boundary because the animation is stopped by the single tap gesture.
https://github.com/Expensify/App/blob/69b2c8797a0022e60b1938ed75aacbe529c69cd9/src/components/MultiGestureCanvas/usePanGesture.ts#L124-L125

https://github.com/Expensify/App/assets/50919443/c7b39f97-bbbb-4d38-b487-21c063c47e9d

(to reproduce it, drag the image out of boundary. while animation do a single tap)

**Comment by sonialiap** [comment] 2024-03-11 12:50
This seems very minor. I'm closing in favor of bugs that have a more disruptive effect on users

**Comment by bernhardoj** [comment] 2024-03-11 14:05
@sonialiap I think we should solve this as this works fine before this [PR](https://www.github.com/Expensify/App/pull/35931)

**Comment by sonialiap** [comment] 2024-03-18 11:18
@bernhardoj fair, reopening and adding the external label

**Comment by DylanDylann** [comment] 2024-03-25 08:42
Reviewing

**Comment by DylanDylann** [comment] 2024-03-25 10:39
I agree with @sonialiap at this point. Let's close this one

> This seems very minor. I'm closing in favor of bugs that have a more disruptive effect on users

IMO, Let's close this one

**Comment by DylanDylann** [comment] 2024-03-27 09:49
I suggest closing this issue as the comment here https://github.com/Expensify/App/issues/37881#issuecomment-2017698722. If the internal engineer wants to process it, I am happy to review the above proposal

🎀 👀 🎀 C+ reviewed

**Comment by marcochavezf** [comment] 2024-03-28 18:47
Yeah, I agree with the other opinions. Let's close it for now

**Closed by marcochavezf** 2024-03-28 18:47 UTC
Labels: External, Daily, Help Wanted, Bug
