### ISSUE TITLE
[HOLD for payment 2023-11-30][$500][ECARD] CRITICAL: Settings - Add “Get physical card” button and necessary routes

### ISSUE THREAD

**Issue by grgia** [Expensify/App#22877] opened 2023-07-14 09:53 UTC
HOLD ON https://github.com/Expensify/App/issues/22873

## Design Doc Section
https://docs.google.com/document/d/1rFxJ78vz5On6zSWzYa51B9v-tyLdC5pUsBeLOLig0t4/edit#bookmark=id.rl1asurfa7yq
<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~013b675735e78d2be9</li>
        <li>Upwork Job ID: 1679791341527105536</li>
        <li>Last Price Increase: 2023-12-13</li>
    </ul>
</details>

**Comment by grgia** [comment] 2023-08-31 13:49
cc @pac-guerreiro

**Comment by pac-guerreiro** [comment] 2023-08-31 14:46
Could you assign me to this @grgia ? 😄

**Comment by marcaaron** [comment] 2023-08-31 19:44
Similar to the issue for adding the Expensify Card page. I think we can get started on this, but ultimately HOLD merging the PR on having the Expensify Card page itself ready.

One way to rollout and get some early benefit from these changes would probably be something like:

- Set up the routes and form with test data (but leave off the button and no need to call any API yet) - this way they are ready to go in the future
- Have the Expensify Card page displaying the virtual card
- Wait for API changes to get deployed (not sure if anyone has started on them)
- Add the button to the Expensify Card page so the user can now navigate <- at this point we would also hook up the API and test the whole card request flow from E2E.

**Comment by sobitneupane** [comment] 2023-09-18 12:31
@pac-guerreiro Is this issue on hold?

**Comment by pac-guerreiro** [comment] 2023-09-21 18:29
@sobitneupane 

Yes it is, but I'm working on it 😄

**Comment by joekaufmanexpensify** [comment] 2023-10-30 13:02
@allroundexperts checking in to see if you'll be able to review this one again today? We're eager to get this out asap. TY!

**Comment by joekaufmanexpensify** [comment] 2023-10-30 13:13
Great, thanks!

**Comment by pac-guerreiro** [comment] 2023-11-23 12:59
https://github.com/Expensify/App/pull/28453 is merged, this issue can be closed

**Comment by allroundexperts** [comment] 2023-11-26 14:44
I would like to clarify here that the two deploy blockers linked here are not truly regressions whose penalty should apply. 

The first [blocker](https://github.com/Expensify/App/issues/31688) was not directly caused by the PR and we decided to dig into it in a follow up PR before merging this. More context [here](https://expensify.slack.com/archives/C01GTK53T8Q/p1700662787762839?thread_ts=1700654205.643899&cid=C01GTK53T8Q). 

The second [blocker](https://github.com/Expensify/App/issues/31704) was a very minor design in-consistency which went through the design review as well. 

Given the above along with the size of the PR, I would like to request for penalty waiver if there is any. Let me know what you think @grgia!

**Comment by situchan** [comment] 2023-11-26 14:56
I also suggest no penalty. But you could review follow-up PRs caused by this PR, instead of letting other C+ review.
-https://github.com/Expensify/App/pull/31702
-https://github.com/Expensify/App/pull/31759

Before, we had discussion that if C+ also tasks responsible for regression issues, no penalty applies sometimes.
But if another C+ handle them, penalty applies because had to pay them for their review as well and that feels like throwing money out of window.
There's no official guideline of course.
cc: @mountiny

**Comment by grgia** [comment] 2023-11-27 12:45
@situchan @allroundexperts I agree that the original C+ should handle follow-up issues from this PR. Sometimes, with the number of new issues created, especially deploy blockers that have an urgency applied, the auto assigner might be part of the confusion. 

@allroundexperts I agree that the padding issue is not a serious regression and that any blockers related to the follow-up should be handled in the follow-up we decided on before merging. 

For this specific issue, I think it's alright to waive the penalty- but for next time, I agree that any follow-ups should be reviewed by the original C+. Does that sound fair to everyone?

**Comment by allroundexperts** [comment] 2023-12-09 02:13
Ho @grgia!
I think my payment for the review is still pending here. Can you please write a payment summary?

Thanks

**Comment by mallenexpensify** [comment] 2023-12-13 21:26
Contributor+: @allroundexperts owed $500 via NewDot

**Comment by mallenexpensify** [comment] 2023-12-13 21:27
d;oh, sorry so messy here, should be all set/done @abekkala

**Closed by mallenexpensify** 2023-12-13 21:26 UTC
Labels: Reviewing, Daily, Internal, Awaiting Payment, Bug, ECard

**Comment by JmillsExpensify** [comment] 2023-12-14 03:51
$500 payment approved for @allroundexperts based on comment above.
