### ISSUE TITLE
[LOW] [Splits] [$500] Split Bill - Unable to deselect workspace when splitting a bill in the workspace chat.

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#36511] opened 2024-02-14 15:22 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** v1.4.40-5
**Reproducible in staging?:** y
**Reproducible in production?:** y
**Issue reported by:** Applause - Internal Team

## Action Performed:
1. Break down in numbered step1, Create workspace > Navigate to Workspace Chat in LHN.
2. Click the plus sign > Split bill > Add amount > Try to click on the workspace. Observe that it is not clickable.s

## Expected Result:
The icon should change to the unselected state or the workspace should be deselected upon clicking on it.

## Actual Result:
Unable to deselect participants when splitting a bill in the workspace chat

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [x] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

https://github.com/Expensify/App/assets/93399543/c43de6eb-7a59-427c-8b79-4a462717e948

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01d3dceefaa28418cd</li>
        <li>Upwork Job ID: 1757787519489777664</li>
        <li>Last Price Increase: 2024-02-28</li>
    </ul>
</details>

**Comment by kbecciv** [comment] 2024-02-14 15:24
We think that this bug might be related #wave6-collect-submitters
CC @greg-schroeder

**Comment by bernhardoj** [comment] 2024-02-14 15:30
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
Unable to deselect workspace from split bill participants.

### What is the root cause of that problem?
Currently, the selected state will be changed only if the pressed/selected `accountID` matches the participant `accountID`.
https://github.com/Expensify/App/blob/fc37aebb20a8d649297f5a2873f98496fa9c1537/src/pages/iou/request/step/IOURequestStepConfirmation.js#L378-L380

But workspace/policy doesn't have `accountID`, but have `reportID`. So, the selected state can't be updated.

### What changes do you think we should make in order to solve the problem?

Add another condition to check for `reportID`.
```
if (participant.accountID === option.accountID || participant.reportID === option.reportID) {
```

**Comment by abdulrahuman5196** [comment] 2024-02-16 08:33
Reviewing now

**Comment by abdulrahuman5196** [comment] 2024-02-16 08:42
@CortneyOfstad I am not sure if this is expected? If we disable the workspace who are we expected to split bill in this case?
I think the current way is expected.
Could you kindly confirm this?

If we the current way is correct. I saw a different issue while testing this, where the workspace row is not disabled but shows as actionable. we can target to fix that as part of this issue.


https://github.com/Expensify/App/assets/46707890/f63f9b43-446e-4c79-aa7b-932977ef534f

**Comment by CortneyOfstad** [comment] 2024-02-16 15:34
> I am not sure if this is expected? If we disable the workspace who are we expected to split bill in this case? I think the current way is expected. Could you kindly confirm this?

@abdulrahuman5196 I agree with your thinking here. When creating the workspace, the account is defaulted the workspace settings automatically, so actions like requesting money is going to be under those settings without the option to change. 

@greg-schroeder if decided to change this logging, it would go under #VIP-Split, but I don't see us changing that action — correct? Just want to get a second pair of eyes to confirm.

**Comment by greg-schroeder** [comment] 2024-02-17 01:55
Looking

**Comment by greg-schroeder** [comment] 2024-02-17 02:00
Hmm. I would still take the conversation to #vip-split to confirm what they want to to do - I'm not across the functionality of split itself so much as how it fits into the submitter flow

**Comment by greg-schroeder** [comment] 2024-02-19 23:03
I still think this is within the purview of VIP-split

**Comment by CortneyOfstad** [comment] 2024-02-20 18:05
Thanks @greg-schroeder! I reached out in VIP-Split [here](https://expensify.slack.com/archives/C05RECHFBEW/p1708452271306179) with my reasoning. Will update as soon as I hear back from the team 👍

**Comment by CortneyOfstad** [comment] 2024-02-23 16:00
@abdulrahuman5196 @Krishna2323 is there any updates on the default workspace process in the proposals?

**Comment by abdulrahuman5196** [comment] 2024-02-23 16:09
@CortneyOfstad Actually we are waiting for you to return here https://github.com/Expensify/App/issues/36511#issuecomment-1954784387.


Do let me know if i missed something?

**Comment by CortneyOfstad** [comment] 2024-02-23 17:47
@abdulrahuman5196 Sorry! I just realized my comment didn't send! I did apply this to VIP Split, so it is set for that wave 👍 

Again, sorry about that!

**Comment by abdulrahuman5196** [comment] 2024-02-26 10:39
@CortneyOfstad I think you where checking on the expected behaviour as per here https://github.com/Expensify/App/issues/36511#issuecomment-1948636987

Was the expectation confirmed? If so, could you kindly share the expectation?

**Comment by CortneyOfstad** [comment] 2024-02-28 16:34
Sorry @abdulrahuman5196! I bumped the thread again in VIP Split to see if anyone has a preference on whether or not the default workspace should be essentially "locked in" during the bill split process. Hopefully I will hear back soon and will share any feedback in response 👍

**Comment by youssef-lr** [comment] 2024-02-28 19:37
I don't see this as a bug. The split bill was created from the workspace chat, what would we display if we deselect it? I'm gonna go ahead and close this one @CortneyOfstad.

**Closed by youssef-lr** 2024-02-28 19:37 UTC
Labels: External, Daily, Help Wanted, Bug

**Comment by abdulrahuman5196** [comment] 2024-02-28 19:43
> CortneyOfstad I am not sure if this is expected? If we disable the workspace who are we expected to split bill in this case? I think the current way is expected. Could you kindly confirm this?
> 
> If we the current way is correct. I saw a different issue while testing this, where the workspace row is not disabled but shows as actionable. we can target to fix that as part of this issue.
> Screen.Recording.2024-02-16.at.2.08.35.PM.mov

https://github.com/Expensify/App/issues/36511#issuecomment-1947969350
@youssef-lr Should we try to solve this here instead? Can the workspace be shown as disabled? I think its the one which is misleading.
