### ISSUE TITLE
[HOLD for payment 2022-09-26] [$2000] Some links are not formatted as markdown links

### ISSUE THREAD

**Issue by mvtglobally** [Expensify/App#9662] opened 2022-07-01 05:51 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Navigate to app
2. Send a message with a link such as `https://mail.google.com`
3. Tap edit and verify that the link does not have markdown syntax around it

## Expected Result:
Link should have markdown syntax

## Actual Result:
Link does not have markdown syntax

## Workaround:
Manually add markdown

## Platform:

Where is this issue occurring?

- Web
- iOS
- Android
- Desktop App
- Mobile Web

**Version Number:** 1.1.79-2
**Reproducible in staging?:** Y 
**Reproducible in production?:** Y 
**Email or phone of affected tester (no customers):** 
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation 

https://user-images.githubusercontent.com/43995119/176832053-ac88936a-9b90-4893-ab43-be606abdebd7.mov

**Expensify/Expensify Issue URL:** 
**Issue reported by:** @NikkiWines 
**Slack conversation:** https://expensify.slack.com/archives/C01GTK53T8Q/p1656458072949539

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by TomatoToaster** [comment] 2022-07-01 15:54
I think this will make a great external issue.

**Comment by mdneyazahmad** [comment] 2022-07-06 11:41
Seems like a regression from this PR https://github.com/Expensify/App/pull/9405

**Comment by JmillsExpensify** [comment] 2022-07-06 22:55
Looks like we're outside of the regression period hold. I'll go ahead and create a new Upwork issue.

**Comment by JmillsExpensify** [comment] 2022-07-06 22:56
Upwork issue is here: https://www.upwork.com/jobs/~01a0c7621378808a22

**Comment by luacmartins** [comment] 2022-07-07 00:11
@allroundexperts since you worked on the [last PR](https://github.com/Expensify/App/pull/9405).

**Comment by Santhosh-Sellavel** [comment] 2022-07-07 15:06
@JmillsExpensify We are still on regression period only. The PR is not yet deployed on production

**Comment by JmillsExpensify** [comment] 2022-07-07 18:37
Oh great! Closing out the Upwork job in that case.

**Comment by JmillsExpensify** [comment] 2022-07-12 16:45
Commented in the original issue/PR regarding this regression.

**Comment by mananjadhav** [comment] 2022-07-12 18:50
> Are we saying we allow autolink for create message but not for edit message?

@luacmartins I am not sure how we would call it a regression. I explicitly asked the same test case in this https://github.com/Expensify/App/issues/9090#issuecomment-1145298738. The PR does the same effect, that the autoLink works when inserting but doesn't when editing. 

We could tag this as a new issue - If the user is posting link with the protocol, then it should be transformed into the markdown format.

**Comment by luacmartins** [comment] 2022-07-12 21:39
>@luacmartins I am not sure how we would call it a regression. I explicitly asked the same test case in this https://github.com/Expensify/App/issues/9090#issuecomment-1145298738. The PR does the same effect, that the autoLink works when inserting but doesn't when editing.

Maybe I misunderstood your question, but the expected behavior is described in the issue and was clarified [here](https://github.com/Expensify/App/issues/9090#issuecomment-1133148976). If the user intentionally removed the link markdown from `[example](link.com)` to `link.com` while editing, we shouldn't make it `[example](link.com)` again and re-add the hyperlink. If the user edits a message but doesn't change the link markdown, we should do nothing and let the hyperlink as is. This is a regression because we are removing the hyperlink even when the user doesn't edit the hyperlink markdown in the message.

**Comment by luacmartins** [comment] 2022-07-13 17:13
This issue is not a regression, but a new bug we discovered by removing the autolink when editing a message - see [this comment](https://github.com/Expensify/App/issues/9090#issuecomment-1183459903).

**Comment by luacmartins** [comment] 2022-07-13 17:16
Updated issue title and reproduction steps! Thanks @mananjadhav for clarifying this!

**Comment by mdneyazahmad** [comment] 2022-07-15 06:52
## Proposal

1. When a user does not enter protocol it will be `https` by default.

https://github.com/Expensify/expensify-common/blob/46b8533e44dbf9d0c20263687d34c6cdb51e0682/lib/ExpensiMark.js#L121-L123

```
                replacement: (match, g1, g2, g3) => (
                    `${g1}<a href="${g3 && g3.includes('http') ? '' : 'https://'}${g2}" target="_blank" rel="noreferrer noopener">${g2}</a>${g1}`
                ),
```

2. When text and url are different HTML to markdown will use `[text](url)` or else just url

https://github.com/Expensify/expensify-common/blob/46b8533e44dbf9d0c20263687d34c6cdb51e0682/lib/ExpensiMark.js#L259-L269

```
            {
                name: 'anchor',
                regex: /<(a)[^><]*href\s*=\s*(['"])(.*?)\2(?:".*?"|'.*?'|[^'"><])*>(.*?)<\/\1>(?![^<]*(<\/pre>|<\/code>))/gi,
                replacement: (match, g1, g2, g3, g4) => {
                    const link = g3.startsWith('mailto:') ? g3.slice(7) : g3;
                    if (link !== g4) {
                        return `[${g4}](${link})`;
                    }
                    return link;
                },
            },
```

Example:
1. `google.com -  (text: google.com, url: https://google.com)`
2. `[Google](google.com) - (text: Google, url: https://google.com)`
3. `[https://google.com](google.com) - (text: https://google.com, url: https://google.com)`
4. `https://google.com - (text: https://google.com, url: https://google.com)`

You can conclude from point 1 and 2, example 3, 4 does not display markdown syntax links.

If we do always want to show links

```diff
            {
                name: 'anchor',
                regex: /<(a)[^><]*href\s*=\s*(['"])(.*?)\2(?:".*?"|'.*?'|[^'"><])*>(.*?)<\/\1>(?![^<]*(<\/pre>|<\/code>))/gi,
                replacement: (match, g1, g2, g3, g4) => {
                    const link = g3.startsWith('mailto:') ? g3.slice(7) : g3;
-                   if (link !== g4) {
                        return `[${g4}](${link})`;
-                   }
-                   return link;
                },
            },
```


### Result:
<img width="579" alt="Screenshot 2022-07-15 at 12 21 13 PM" src="https://user-images.githubusercontent.com/77761491/179167972-688a025f-6573-4952-8a9e-baea6b6c037a.png">

**Comment by Santhosh-Sellavel** [comment] 2022-07-15 18:39
@mdneyazahmad 
This would break the email case.
<img width="865" alt="Screenshot 2022-07-16 at 12 03 02 AM" src="https://user-images.githubusercontent.com/85645967/179289717-04d0c12c-8370-46c6-acfe-0155496cfe68.png">


cc: @luacmartins

**Comment by mdneyazahmad** [comment] 2022-07-16 09:34
@Santhosh-Sellavel Nice catch! We can do markdown formatting only when link starts with http(s)

```diff
-                   if (link !== g4) {
+                   if (link.includes('http')) {
                        return `[${g4}](${link})`;
                    }
                    return link;
```

**Comment by mdneyazahmad** [comment] 2022-07-19 09:32
Maybe, this will be better `if ((link !== g4) || /^https?/.test(link))`. I will throughly test this and let you know about it.

**Comment by luacmartins** [comment] 2022-07-20 20:36
Bumping this to a weekly while we wait for more proposals.

**Comment by JmillsExpensify** [comment] 2022-07-26 03:46
I'm a little behind, but I'm bumping up to $500 nonetheless. Still waiting for proposals.

**Comment by JmillsExpensify** [comment] 2022-07-28 13:38
Going to be out for the next three business days, though we're still waiting for proposals.

**Comment by JmillsExpensify** [comment] 2022-08-03 16:24
I'm back and we still lack proposals so I'm going to raise the price of this issue.

**Comment by Santhosh-Sellavel** [comment] 2022-08-04 03:30
Let's cap the price for this issue. @JmillsExpensify @luacmartins

**Comment by luacmartins** [comment] 2022-08-04 15:22
@Santhosh-Sellavel what's the reasoning for the cap and what is your price cap suggestion?

**Comment by Santhosh-Sellavel** [comment] 2022-08-04 18:18
It looks relatively simple, not sure believe $1000 should be more than reasonable.

**Comment by JalalMitali** [comment] 2022-08-06 00:14
I can't reproduce this issue on iOS is it already resolved ?

**Comment by JalalMitali** [comment] 2022-08-06 21:52
<img width="1792" alt="Expensify Solution for Markdown Links" src="https://user-images.githubusercontent.com/88791252/183267187-ca866646-08bc-4e01-8bf9-c658af575f75.png">
this should do the trick ? can we depend on it ?

**Comment by Santhosh-Sellavel** [comment] 2022-08-07 16:30
@JalalMitali Can you elaborate your proposal with little more explanation. Thanks!

**Comment by JalalMitali** [comment] 2022-08-07 17:22
@Santhosh-Sellavel hello, what I did was using the modifyTextForUrlLinks method to generate markdown for links before processing them with the other rules

**Comment by Santhosh-Sellavel** [comment] 2022-08-08 17:11
No @JalalMitali we should not do it like that, this is some kind of hacky solution.

**Comment by JalalMitali** [comment] 2022-08-08 17:12
okay no problem :)

**Comment by JmillsExpensify** [comment] 2022-08-10 03:15
> Let's cap the price for this issue. @JmillsExpensify @luacmartins

I'm fine with that given the low priority of this. @luacmartins any pushback?

**Comment by Santhosh-Sellavel** [comment] 2022-08-10 07:43
@JmillsExpensify We had a discussion Lets double this up & Make it Monthly.

cc: @luacmartins

**Comment by luacmartins** [comment] 2022-08-10 19:55
I'd say we keep doubling, but make it monthly after $2k.

**Comment by luacmartins** [comment] 2022-08-15 15:46
Still looking for contributors

**Comment by JmillsExpensify** [comment] 2022-08-15 16:51
Ok thanks for the heads up. It's effectively been a week at this point, so I'll double and then make this issue a monthly.

**Comment by JmillsExpensify** [comment] 2022-08-16 17:34
Moving back to weekly per internal discussion.

**Comment by b1tjoy** [comment] 2022-08-19 09:02
### PROPOSAL
### Problem

### Solution
Update code in this file will fix our current issue.
https://github.com/Expensify/expensify-common/blob/e0ec0b9abca4d7b417ba0b016f8725856cfeeece/lib/ExpensiMark.js#L259-L269
```JSX
           {
                name: 'anchor',
                regex: /<(a)[^><]*href\s*=\s*(['"])(.*?)\2(?:".*?"|'.*?'|[^'"><])*>(.*?)<\/\1>(?![^<]*(<\/pre>|<\/code>))/gi,
                replacement: (match, g1, g2, g3, g4) => {
-                   const link = g3.startsWith('mailto:') ? g3.slice(7) : g3;
-                   if (link !== g4) {
-                       return `[${g4}](${link})`;
-                   }
-                   return link;
+                   if (g3.startsWith('mailto:')) {
+                     return g3.slice(7);
+                   }
+                   return `[${g4}](${g3})`;
                },
            },
```

**Comment by mdneyazahmad** [comment] 2022-08-20 14:39
https://github.com/Expensify/App/issues/9662#issuecomment-1185235177 https://github.com/Expensify/App/issues/9662#issuecomment-1188824219

I updated the test cases as per the result, it passes all tests and it does not produce any side effects. But I highly doubt that we need this feature. I would suggest to reevaluate the issue and my alternate proposal is to revert https://github.com/Expensify/App/pull/9405 as auto link does not work in edit mode. If this was indeed the desired output, please ignore my alternate proposal.

commit: https://github.com/mdneyazahmad/expensify-common/commit/8fc9673dec5db97a47ba8889d286efdc53eb5651

cc: @luacmartins @Santhosh-Sellavel

**Comment by Santhosh-Sellavel** [comment] 2022-08-22 17:08
@luacmartins 
@b1tjoy Proposal looks good to me! 
In the final PR need to add/update the unit tests!
🎀 👀 🎀 
C+ Reviewed.

Also @luacmartins there is a proposal from @mdneyazahmad [here](https://github.com/Expensify/App/issues/9662#issuecomment-1221326535) to revert  https://github.com/Expensify/App/pull/9405. I'm not sure that is expected here. So I'll leave it to you to decide on that, thanks!

**Comment by b1tjoy** [comment] 2022-08-23 09:59
Nice catch! I think update to the following code would fix this issue.

```JSX
if (g3.startsWith('mailto:')) {
    const email = g3.slice(7);
    if (email !== g4) {
        return `[${g4}](${email})`;
    }
    return email;
}
return `[${g4}](${g3})`;
```

**Comment by Santhosh-Sellavel** [comment] 2022-08-23 14:32
> @Santhosh-Sellavel @b1tjoy proposal is failing this this case, send `[Expensify](concierge@expensify.com)` it will parse it back to `concierge@expensify.com` and not `[Expensify](concierge@expensify.com)`

@luacmartins Is this considered as a valid failure case?  I'm confused here, can you share your thoughts here.

**Comment by Santhosh-Sellavel** [comment] 2022-08-25 21:59
> #10530

This helps thanks!

Now we have two proposals, I'll re-evaluate again!

**Comment by Santhosh-Sellavel** [comment] 2022-08-29 18:44
@luacmartins 

We have two proposals,
@b1tjoy proposal [here](https://github.com/Expensify/App/issues/9662#issuecomment-1223842594)
@mdneyazahmad proposal [here](https://github.com/Expensify/App/issues/9662#issuecomment-1223852728)

@b1tjoy's proposal
We should refactor it because the code is not DRY, but it solves the issue. I like the idea computing of `email` instead of `link` here. Only email linking that doesn't follow markdown link syntax, we have to return email as it is. In all other cases, we have to format it in markdown link syntax. That's clear here.

@mdneyazahmad's proposal also solves the issue. Their proposal does the quite opposite testing `link` against another regex `/^https/` this might fail for `http:// ` links. I find it odd and unnecessary.  

So I prefer @b1tjoy's proposal, but I'll let you make the final call.
Thanks!

🎀 👀 🎀
C+ Reviewed.

**Comment by luacmartins** [comment] 2022-08-30 07:19
I agree, thanks for the nice summary @Santhosh-Sellavel! @b1tjoy your proposal looks good! Assigning you to this issue!

**Comment by JmillsExpensify** [comment] 2022-08-30 11:15
Great, I'm going to create a fresh job in Upwork now that we're ready to hire. It's here: https://www.upwork.com/jobs/~0111e0f1a39910edf7. @Santhosh-Sellavel I've gone ahead and invited you. @b1tjoy can you please apply and I'll make sure you are hired? Thanks all!

**Comment by JmillsExpensify** [comment] 2022-09-05 09:20
I've extended offers to both contributors via Upwork.

**Comment by Santhosh-Sellavel** [comment] 2022-09-07 20:24
@JmillsExpensify  My offer is not acceptable, it's been withdrawn. Can you send again please thanks!

<img width="1107" alt="Screenshot 2022-09-08 at 1 53 38 AM" src="https://user-images.githubusercontent.com/85645967/188970274-4e7f0b72-b127-4050-a2b5-4c39c68b63a9.png">

**Comment by JmillsExpensify** [comment] 2022-09-12 08:51
@Santhosh-Sellavel I created another offer for you and invited here: https://www.upwork.com/jobs/~012cd72d809c0e7808

**Comment by Santhosh-Sellavel** [comment] 2022-09-12 18:24
> @Santhosh-Sellavel I created another offer for you and invited you here: https://www.upwork.com/jobs/~012cd72d809c0e7808

Thanks, applied! @JmillsExpensify

**Comment by mvtglobally** [comment] 2022-09-20 05:03
Issue not reproducible during KI retests. (First week)

**Comment by JmillsExpensify** [comment] 2022-09-26 13:44
We've reached the end of the 7-day regression period. I'm going to jump in and check that everything is fine with the linked PR, and then issue payments.

**Comment by JmillsExpensify** [comment] 2022-09-26 13:47
Interestingly, I'm not seeing a production deploy linked to that PR, though I know we've been deploying daily during the week. That said, no regressions on staging and issue isn't reproducible, so I'm going to close out this issue with payments.

**Comment by JmillsExpensify** [comment] 2022-09-26 13:53
@Santhosh-Sellavel @b1tjoy Payments issued via Upwork. I'm closing the issue, though please let me know if I can help with anything else!

**Comment by luacmartins** [comment] 2022-09-26 16:18
@JmillsExpensify FYI production deploy comments were [broken](https://expensify.slack.com/archives/C07J32337/p1663607918854289) from Aug 11 to Sep 19. So any PRs deployed to prod during those dates won't have the prod deploy comment.

**Comment by luacmartins** [comment] 2022-09-26 16:20
@mdneyazahmad that issue is also closed. What makes you say that it's still reproducible?

**Comment by mallenexpensify** [comment] 2022-10-26 18:41
I'm experiencing this issue, or something similar, so reopening to get 👀, then will proceed from there. 
Repro steps
- Send message in NewDot
- Edit message that was sent and add link to it
- Observe that the link that was added is not hyperlinked, it's not a clickable link once sent. 

Same issue here? Regression? New issue? Somehow related to what was considered a dupe issue https://github.com/Expensify/App/issues/10530?

**Comment by Santhosh-Sellavel** [comment] 2022-10-26 19:02
@mallenexpensify 
https://github.com/Expensify/App/issues/9662#issuecomment-1292449936 It seems like a different issue to me.

#9662 This issue is all about how should we show link markdown syntax while editing, except email we should show other links in the below pattern

<img width="631" alt="Screenshot 2022-10-27 at 12 23 56 AM" src="https://user-images.githubusercontent.com/85645967/198112149-a2d1386f-ebc0-499b-a3f8-e78ce7eec679.png">

#10530 This is related to #9662 because,

The actual issue in #10530, is when a link is sent ex: `https://www.google.com`, after click editing just doing nothing saving changes will make the hyperlink go away. 

but after this issue's PR, we would show the link the URL markdown pattern `[]()`. So saving without even doing anything will still keep the link which is expected behavior. So that's why they are linked as duplicates.


But what you are reporting [here](https://github.com/Expensify/App/issues/9662#issuecomment-1292449936)

Adding a link while editing seems like a completely different issue.

cc: @luacmartins

**Comment by mallenexpensify** [comment] 2022-10-26 21:26
ooof, lotta different pieces here, thanks for the breakdown @Santhosh-Sellavel , it was especially helpful. 
So.. this fix is working as expected and should be re-closed, right? Pretty sure, so closing. 
<img width="805" alt="image" src="https://user-images.githubusercontent.com/22508304/198141100-c2590296-b094-473d-8ce9-f03a4c8f5afe.png">

For my issue... it sounds like it should be a new issue, is it a bug or a new feature?!?!

**Closed by mallenexpensify** 2022-10-26 21:26 UTC
Labels: External, Engineering, Daily, Awaiting Payment
