### ISSUE TITLE
Split bill - IOU message removed after send normal text message in newly created workspace’s announce room

### ISSUE THREAD

**Issue by kavimuru** [Expensify/App#14348] opened 2023-01-17 00:29 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:

1. Go to setting => Workspaces.
2. Create new workspace.
3. Once workspace created go to announce room of newly created workspace.
4. Press on composer plus button => split bill.
5. Choose amount => choose persons and confirm.
6. Once split bill completed send normal text message.
7. Observe IOU message removed after send normal text message.

## Expected Result:
 There should be only one IOU message and message shouldn’t remove from chat.

## Actual Result:
There are 2 IOU messages one of the message removed after send normal text message in specific condition.

## Workaround:
unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [ ] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 1.2.55-0
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** https://user-images.githubusercontent.com/43996225/212784316-bd396dde-a43b-4588-be9b-e6bdc93cceeb.mp4
https://user-images.githubusercontent.com/43996225/212784296-13f35924-0f02-449f-824e-eea01c463887.mov

**Expensify/Expensify Issue URL:**
**Issue reported by:** @jatinsonijs 
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1673700409380059

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

https://user-images.githubusercontent.com/43996225/212784296-13f35924-0f02-449f-824e-eea01c463887.mov

**Comment by tjferriss** [comment] 2023-01-18 06:14
I was not able to reproduce. I got one message as expected.

<img width="312" alt="Screen Shot 2023-01-17 at 10 13 54 PM" src="https://user-images.githubusercontent.com/8292562/213098134-d56a0ee0-43e2-46c1-a01f-bc5553b58f23.png">

**Comment by tjferriss** [comment] 2023-01-20 18:48
@jatinsonijs are you still able to reproduce this bug? If not, let's close the issue.

**Comment by tjferriss** [comment] 2023-01-23 19:58
@jatinsonijs I'm going to close this out. Please re-open if you can still reproduce the bug.

**Closed by tjferriss** 2023-01-23 19:58 UTC
Labels: Daily, Needs Reproduction, Overdue, Bug
