### ISSUE TITLE
Expenses - Submit button appears and immediately disappears after expense is posted

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#46872] opened 2024-08-06 11:55 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 9.0.17-0
**Reproducible in staging?:** Y
**Reproducible in production?:** N
**If this was caught during regression testing, add the test name, ID and link from TestRail:** https://expensify.testrail.io/index.php?/tests/view/4818052
**Email or phone of affected tester (no customers):** fischer9966+080524aemp@gmail.com
**Issue reported by:** Applause - Internal Team

## Action Performed:
Precondition:
1. Login as the admin and create Collect workspace
2. Navigate to the collect workspace settings > More features > Enable workflows
3. Navigate to workflows > Enable Approvals
4. Enable delay submissions and set it to Manually
5. Invite a new user with Gmail account as an employee
Steps:
1. Login as the employee account in ND
2. Navigate to the workspace chat
3. Submit expense to the workspace for >100$
4. Verify a "Submit" button is displayed

## Expected Result:
"Submit" button is displayed for expense after the employee posted it

## Actual Result:
"Submit" button appears and immediately disappears after the employee posted expense

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [x] Android: mWeb Chrome
- [x] iOS: Native
- [x] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details> 

https://github.com/user-attachments/assets/5e10a4cb-183d-4672-a05f-7aaf77409420

https://github.com/user-attachments/assets/31a62cc8-cd6d-4346-8a3b-9bdeec3a947f

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by lanitochka17** [comment] 2024-08-06 11:58
We think that this bug might be related to #wave-collect - Release 1

**Comment by rlinoz** [comment] 2024-08-06 14:02
This is caused by this PR: https://github.com/Expensify/Web-Expensify/pull/42976/files#diff-7e2d65062b3d1b62158a39b82faabb6666d1fc9a64abe64404c94c374208fb56 which is now sending `reimbursable` to Auth, but we don't always send `reimbursable` from the App.

**Comment by rlinoz** [comment] 2024-08-06 14:26
Fixing on Web-E, so removing the App deploy blocker.

**Comment by rlinoz** [comment] 2024-08-06 14:59
Asked for CP here https://expensify.slack.com/archives/C07J32337/p1722955790047509

**Comment by kavimuru** [comment] 2024-08-06 20:21
Now `Submit` button appears. After tap it blinks, but there are no errors.

https://github.com/user-attachments/assets/eb5dba47-4757-4c86-b091-253b6aae3941

**Comment by rlinoz** [comment] 2024-08-07 12:17
The PR is deployed to prod, so closing.

**Closed by rlinoz** 2024-08-07 12:17 UTC
Labels: Engineering, Daily
