### ISSUE TITLE
[$250] QBO Desktop – Missing message in admins room after a failed connection

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#50824] opened 2024-10-15 18:06 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 9.0.49-0
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**If this was caught during regression testing, add the test name, ID and link from TestRail:** N/A
**Email or phone of affected tester (no customers):** ponikarchuks+11151024@gmail.com
**Issue reported by:** Applause - Internal Team

**Issue found when executing PR** https://github.com/Expensify/App/pull/50045
## Action Performed:
1. ND: Navigate to https://staging.new.expensify.com/
2. ND: Log in with a new Gmail account
3. ND: Create a workspace
4. ND: Navigate to OD by clicking on Account settings - Domains
5. OD: Navigate to Settings - Workspaces - "Created workspace name" - Connections
6. OD: Upgrade the WS to Collect with the lock icon next to "QuickBooks Desktop"
7. OD: Click on QuickBooks Desktop - Connect to QuickBooks Desktop - Connect to QuickBooks Desktop
8. OD: Attempt to connect to QuickBooks Desktop (the connection will fail)
9. ND: Navigate to the #admins room

## Expected Result:
"Failed to sync with QuickBooks Desktop" message shows

## Actual Result:
Missing message in #admins room

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

<details>
  <summary>Add any screenshot/video evidence</summary>

  
</details> 

https://github.com/user-attachments/assets/e8809e9b-cdf0-416a-bd45-dc1d52384bad

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~021846685325712658805</li>
        <li>Upwork Job ID: 1846685325712658805</li>
        <li>Last Price Increase: 2024-10-16</li>
<li>Automatic offers: </li>
<ul>
<li>rojiphil | Reviewer | 104486913</li>
</ul></li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @rojiphil</details>

**Comment by lanitochka17** [comment] 2024-10-15 18:07
@slafortune  FYI I haven't added the External label as I wasn't 100% sure about this issue. Please take a look and add the label if you agree it's a bug and can be handled by external contributors

**Comment by lanitochka17** [comment] 2024-10-15 18:07
We think that this bug might be related to #wave-collect - Release 1

**Comment by Anaslancer** [comment] 2024-10-17 16:52
It works fine on my side.
![Uploading Screenshot_3.png…]()

**Comment by waterim** [comment] 2024-10-18 12:31
Hello, Im Artem from Callstack and would like to help with this issue!

**Comment by waterim** [comment] 2024-10-21 19:59
Tried to reproduce it with different accounts, new accounts, but not luck to reproduce.

https://github.com/user-attachments/assets/17eed4d1-d249-4b83-8ad4-47857919b3c4

https://github.com/user-attachments/assets/4ea3f211-d604-47a5-b9b3-068006e649dd

@lanitochka17 Can you please check these recordings, maybe I missed something, but from my side everything works fine

And can you retest please if everything is correct with my recordings

**Comment by slafortune** [comment] 2024-10-23 18:06
Added the retest tag too

**Comment by mvtglobally** [comment] 2024-10-30 09:44
Issue not reproducible during KI retests. (First week)

**Comment by slafortune** [comment] 2024-10-31 16:32
Updated to weekly - one more test and we'll close

**Comment by rojiphil** [comment] 2024-11-08 06:50
> Updated to weekly - one more test and we'll close

@slafortune We are at the end of the second week now and I think we can close this issue as it is not reproducible as mentioned [here](https://github.com/Expensify/App/issues/50824#issuecomment-2446359616).

**Comment by mvtglobally** [comment] 2024-11-08 15:26
Issue not reproducible during KI retests. (Second week)

**Comment by rojiphil** [comment] 2024-11-12 04:51
@garrettmknight @slafortune Let us close this issue as it is not reproducible for the [second week](https://github.com/Expensify/App/issues/50824#issuecomment-2465037436) and also as mentioned [here](https://github.com/Expensify/App/issues/50824#issuecomment-2450318668).

**Comment by mvtglobally** [comment] 2024-11-16 01:54
Issue not reproducible during KI retests. (Third week)

**Comment by rojiphil** [comment] 2024-11-21 02:49
@garrettmknight,  looks like @slafortune is on leave. Can you please close this issue as it is not reproducible for the third consecutive week? Thanks.

**Closed** 2024-11-21 15:55 UTC
Labels: External, Weekly, Bug, retest-weekly
