### ISSUE TITLE
[HOLD for payment 2023-08-21] [$1000] Contact Method – Input dashes remain red, instead turning to grey upon deletion of any number.

### ISSUE THREAD

**Issue by kavimuru** [Expensify/App#23756] opened 2023-07-27 19:31 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1.	Open your profile.
2.	Click on "Contact methods".
3.	Click on "New contact method".
4.	Add a new contact and proceed to the next step.
5.	Enter an invalid magic code to trigger an error, causing the dashes to turn red.
6.	Delete any number.
7.	Notice that the dashes remain red, while in other sections, they turn to grey upon deleting any number.
## Expected Result: 
The dashes should turn to grey upon deletion of a number, similar to how it works in other sections.
## Actual Result: 
The dashes remain red upon deleting any number, while in other sections, they turn to grey

## Workaround:
Can the user still use Expensify without this being fixed? Have you informed them of the workaround?

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [x] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 1.3.46-2
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/43996225/315c360d-e0ef-4764-bbb5-b872785deaca

https://github.com/Expensify/App/assets/43996225/0bfd39e1-b457-4ea3-824b-18f7df9ac8d6

**Expensify/Expensify Issue URL:**
**Issue reported by:** @usmantariq96
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1690438628680299

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~016c5402df1f6143e0</li>
        <li>Upwork Job ID: 1684857239303507968</li>
        <li>Last Price Increase: 2023-08-04</li>
<li>Automatic offers: </li>
<ul>
<li>fedirjh | Reviewer | 26031002</li>
<li>hoangzinh | Contributor | 26031005</li>
</ul></li>
    </ul>
</details>

**Comment by ygshbht** [comment] 2023-07-28 03:20
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
When deleting a number from an invalid magic code in the 'Contact methods' section, the input dashes remain red instead of turning grey as is the behavior in other sections.

### What is the root cause of that problem?
The root cause of the problem is that the current implementation does not clear the error once the input is changed. The error state is retained, and therefore the dashes remain red.

`onChangeText={onTextInput}
`

https://github.com/Expensify/App/blob/975146fa30bc65a19df8e0cca525af32ce2ceda5/src/pages/settings/Profile/Contacts/ValidateCodeForm/BaseValidateCodeForm.js#L131-L143

### What changes do you think we should make in order to solve the problem?
To solve this issue, we need to introduce functionality to clear the error when the input changes. This can be done by modifying the `onChangeText `function in the following way:

```
onChangeText={(...args) => {
    User.clearContactMethodErrors(props.contactMethod, 'validateLogin');
    onTextInput(...args);
}}

```
By doing so, we ensure the error state is cleared whenever the input changes, making the behavior consistent with other sections.

**Comment by alphaboss1104** [comment] 2023-07-28 08:31
## Proposal
### Please re-state the problem that we are trying to solve in this issue.
Error is shown as soon as app is put in background when creating a task.
### What is the root cause of that problem?

The root cause of this problem is that after once `errorFields` of `loginList[contactMethod]` in Onyx Data is set, we didn't clear the `errorFields`  when the `invalid magic code` is updated or any number is deleted.

In the original code, the `hasError` property of the `MagicCodeInput` component is `true` even if we update the `invalid magic code` or delete the any number after once `errorFields` is set.

Below code snippets shows how the `hasError` property is set as `true`:

https://github.com/Expensify/App/blob/975146fa30bc65a19df8e0cca525af32ce2ceda5/src/pages/settings/Profile/Contacts/ValidateCodeForm/BaseValidateCodeForm.js#L75
https://github.com/Expensify/App/blob/975146fa30bc65a19df8e0cca525af32ce2ceda5/src/libs/ErrorUtils.js#L97-L109
https://github.com/Expensify/App/blob/975146fa30bc65a19df8e0cca525af32ce2ceda5/src/pages/settings/Profile/Contacts/ValidateCodeForm/BaseValidateCodeForm.js#L139

And in the original code there is no code snippet that clear the `errorFields` when the `invalid magic code` is updated or any number is deleted. Because of this the `hasError` property keep the value(`true`) even `invalid magic code` is updated or any number is deleted.

And then if `hasError` property of the `MagicCodeInput` component is set as `true`, dash's color set as red cause of below code snippet:
https://github.com/Expensify/App/blob/975146fa30bc65a19df8e0cca525af32ce2ceda5/src/components/MagicCodeInput.js#L320

### What changes do you think we should make in order to solve the problem?

In my little opinion, we should add the code that clear the `errorFields` of `loginList[contactMethod]` in Onyx Data when the `invalid magic code` is updated or any number is deleted.

When the magic code is changed `onTextInput` function invoked. 
So We can add the `User.clearContactMethodErrors(props.contactMethod, 'validateLogin')` in the `onTextInput` function.

We can modify the [onTextInput](https://github.com/Expensify/App/blob/main/src/pages/settings/Profile/Contacts/ValidateCodeForm/BaseValidateCodeForm.js#L99) like this:

```js
const onTextInput = useCallback(
        (text) => {
            setValidateCode(text);
            setFormError({});

+           User.clearContactMethodErrors(props.contactMethod, 'validateLogin')

            if (props.account.errors) {
                Session.clearAccountMessages();
            }
        },
        [props.account.errors],
    );
```

### What alternative solutions did you explore? (Optional)

None

**Comment by conorpendergrast** [comment] 2023-07-28 09:25
Nice, thanks. I saw that this issue reached production two days ago: https://github.com/Expensify/App/issues/22187

@fedirjh @flodnv @twisterdotcom @bernhardoj @aimane-chnaif can any of you see if this was a regression caused by https://github.com/Expensify/App/issues/22187?

**Comment by saalimzafar** [comment] 2023-07-28 13:01
## Proposal

**Please re-state the problem that we are trying to solve in this issue.**

Input dashes remain red, instead turning to grey upon deletion of any number

**What is the root cause of that problem?**

The root cause of this problem is that the color change logic of the "MagicCodeInput" component is primarily based on the `focusedIndex` state, which tracks the currently focused input field. However, when the user deletes a number and the input becomes an empty string, the `focusedIndex` is not updated to reflect this empty input state, leading to the dashes remaining red.

**What changes do you think we should make in order to solve the problem?**

To address the issue, I propose modifying the "MagicCodeInput" component's color change logic using the `useEffect` hook. By adding a `useEffect` that observes changes to the `input` state, we can detect when the input is cleared (i.e., becomes an empty string). When the input is cleared, we will update the `focusedIndex` to 0, ensuring that the dashes turn grey as desired.

**What alternative solutions did you explore? (Optional)**

NA

**Comment by conorpendergrast** [comment] 2023-07-31 10:14
Looks like we're still getting proposals here

**Comment by conorpendergrast** [comment] 2023-08-03 12:00
@fedirjh Any promising proposals here that we can move forward with?

**Comment by evappdev** [comment] 2023-08-04 13:18
**Proposal** 
**Please re-state the problem that we are trying to solve in this issue.**
Contact Method – Input dashes remain red when user clear the textbox, it should turn to grey when user clear the number.

**What is the root cause of that problem?**
"hasError" is maintaining error even after started editing the verification code

const loginData = props.loginList[props.contactMethod];
const validateLoginError = ErrorUtils.getEarliestErrorField(loginData, 'validateLogin');
<MagicCodeInput
....
hasError={!_.isEmpty(validateLoginError)}
....
/>

**What changes do you think we should make in order to solve the problem?**

Login list is a onyx state which maintaining error, which providing value login data.
By removing the error state in from onyx, state clears the data and change the textbox to grey

**Comment by sourcecodedeveloper** [comment] 2023-08-06 14:22
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
Secondary Contact method - magic code input dashes remain red after clearing magic code when they should turn grey like in other area.
### What is the root cause of that problem?
Checking account.errors and clearing account messages in session is not going to clear 'validateLogin' key of props.loginList[props.contactMethod]

```
            if (props.account.errors) {
                Session.clearAccountMessages();
            }
```

the validateLoginError is also being set outside of onTextInput so it does not update onTextInput
 
```
            const validateLoginError = ErrorUtils.getEarliestErrorField(loginData, 'validateLogin'); 
```


### What changes do you think we should make in order to solve the problem?
In the proposed solution I have used useState and useEffect to observe any changes to the props.loginList[props.contactMethod] key instead of calling User.clearContactMethodErrors in onTextInput, which also clears the validation error below the magic code input. I found using useState a better solution which only clears the red on the magic code input and matches UI with the 2FA screen and keeps things aligned with the original issue.

I am also attaching a screen recording of the functional solution below


https://github.com/Expensify/App/assets/141340971/4c927068-e70e-49bd-847c-cd9a9062b596

**Comment by stitesExpensify** [comment] 2023-08-09 15:10
Agreed!

**Comment by conorpendergrast** [comment] 2023-08-21 19:21
@usmantariq96 Hello! Please [apply to the Upwork job](https://www.upwork.com/jobs/~016c5402df1f6143e0) for your role as reporter ($250)
@fedirjh Please accept [the offer](https://www.upwork.com/offer/26031002)!

**Comment by conorpendergrast** [comment] 2023-08-21 19:22
Payouts due:

- [ ] Issue Reporter: $250 @usmantariq96
- [ ] Contributor: $1000 + 50% urgency = $1500 @hoangzinh 
- [ ] Contributor+: $1000 + 50% urgency = $1500 @fedirjh 

Eligible for 50% #urgency bonus? Yes

Upwork job is [here](https://www.upwork.com/ab/applicants/1684857239303507968/job-details).

**Comment by usmantariq96** [comment] 2023-08-22 03:22
@conorpendergrast applied
Thanks

**Comment by stitesExpensify** [comment] 2023-08-24 19:29
Are we all good here @conorpendergrast?

**Comment by conorpendergrast** [comment] 2023-08-25 08:26
Sorry folks, I have a few things left - this week has gotten away from me. 

- Offer sent to @usmantariq96
- Paid and ended contract for @fedirjh 
- regression test created: https://github.com/Expensify/Expensify/issues/311279

Once @usmantariq96 has accepted the offer and been paid, I will close this 👍

**Comment by usmantariq96** [comment] 2023-08-25 09:36
@conorpendergrast accepted with thanks

**Comment by conorpendergrast** [comment] 2023-08-25 11:46
And we are done, thank you everyone!

**Closed by conorpendergrast** 2023-08-25 11:46 UTC
Labels: External, Daily, Awaiting Payment, Bug
