### ISSUE TITLE
Chat - RHN and 'Keyboard shortcuts' modal are simultaneously opened

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#26017] opened 2023-08-26 23:02 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Open an existing chat
2. Send an image
3. Open the image
4. Press Ctrl + J
5. Press Ctrl + K

## Expected Result:
'Keyboard shortcuts' modal should close when RHN is opened

## Actual Result:
 'Keyboard shortcuts' modal & RHN are simultaneously opened

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [x] Windows / Chrome 
- [ ] MacOS / Desktop

**Version Number:** 1.3.57-5

**Reproducible in staging?:** Yes

**Reproducible in production?:** Yes

**If this was caught during regression testing, add the test name, ID and link from TestRail:**

**Email or phone of affected tester (no customers):**

**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/78819774/e6a60418-f83c-4bbc-b4fd-88eac38387a8

https://github.com/Expensify/App/assets/78819774/a491748f-1fce-4bfa-838f-544f631be451

**Expensify/Expensify Issue URL:**

**Issue reported by:** @Natnael-Guchima

**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1692339194846039

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by akinwale** [comment] 2023-08-27 03:56
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
RHN and the "keyboard shortcuts" modal are open at the same time if the keyboard shortcuts modal was open while viewing an attachment.

### What is the root cause of that problem?
There appears to be a conflict with the modal open state, with the Modal.close action not able to close the keyboard shortcut modal after the attachment modal is closed by the user. 

### What changes do you think we should make in order to solve the problem?
**Solution 1**
Add code to explicitly hide the keyboard shortcut modal in the subscription for the Ctrl/CMD+K shortcut in the `AuthScreen` component.
```
KeyboardShortcutsActions.hideKeyboardShortcutModal();
```

**Solution 2**
Automatically hide the attachment modal when a user presses Ctrl/CMD+J to show the keyboard shortcuts modal.

### What alternative solutions did you explore? (Optional)
None.

**Comment by sophiepintoraetz** [comment] 2023-08-28 05:23
Noted in the original issue but 
>I am inclined to agree with @stephanieelliott - I don't think this is worth fixing and is intended by design.

**Closed by sophiepintoraetz** 2023-08-28 05:23 UTC
Labels: Daily, Bug
