### ISSUE TITLE
[$500] IOS - iOS app crashes when switching chats (and sometimes when launching)

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#28066] opened 2023-09-23 14:38 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Launch app
2. Tap into 1 or more chats
3. It crashes

## Expected Result:
 App should not crash

## Actual Result:
App is crashing consistently the past few days when I’m simply chat switching, or launching the app.

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [x] iOS / native
- [ ] iOS / Safari
- [ ] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 1.3.73.0
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/93399543/ff79e30e-581a-47f5-9f2a-e6ff80ebc24f

**Expensify/Expensify Issue URL:**
**Issue reported by:** @michaelhaxhiu 
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1695250716424909

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01884be58254438c7f</li>
        <li>Upwork Job ID: 1706502088914329600</li>
        <li>Last Price Increase: 2023-09-26</li>
    </ul>
</details>

**Comment by lschurr** [comment] 2023-09-25 07:42
Bumped the Slack thread to see if this is still happening for Hax.

**Comment by michaelhaxhiu** [comment] 2023-09-25 11:41
Yes it's still happening. I reproduced last week, yesterday, and again this morning.

**Comment by lschurr** [comment] 2023-09-26 02:53
@burczu would you double check this and see if it's reproducible? Not sure if this is widespread or just specific to Hax's device/account.

**Comment by spectusAkashIOS** [comment] 2023-09-26 06:39
**Proposal**

Contributor details
Akash Patel [akashpatel116@gmail.com]
Upwork Profile Link: https://www.upwork.com/freelancers/~01481520e615cc06af

Checked the Video Recording attached with the issue.

To find the exact cause of the issue, need to debug the app and find the line of code or object which is causing the app to crash.

**Proposed Solution:**
Most of the time, crash caused by unwraping a NULL value from a varibale or an object. This can be handled by using
```
guard let <statement> else {
return
} 
```

Or can be handled via
```
if let abc = NullableVariable {
//handle value of abc here
}
```

If the crash is caused by any other reason, it can be identified via debug.

**Comment by burczu** [comment] 2023-09-26 09:49
@spectusAkashIOS Your proposal does not follow our [Proposal Template](https://github.com/Expensify/App/blob/main/contributingGuides/PROPOSAL_TEMPLATE.md) - please update it accordingly.

**Comment by spectusAkashIOS** [comment] 2023-09-26 10:03
Comment updated @burczu

**Comment by burczu** [comment] 2023-09-26 10:08
@spectusAkashIOS Ok, it follows the template now, but it's still not a proposal. What we expect is instead saying "we have to debug and check what is wrong" we need something like "I debugged, did some research, found an issue here and there and to fix it we need to change this file this way, and that file this way etc.".

**Comment by spectusAkashIOS** [comment] 2023-09-26 10:14
ok @burczu , I will update comment after debug.

**Comment by burczu** [comment] 2023-09-26 10:33
@lschurr I wasn't able to reproduce it (checked on the simulator).

**Comment by sonialiap** [comment] 2023-09-27 04:15
I wonder if this issue is the same as one Applause found https://github.com/Expensify/App/issues/28068

**Comment by burczu** [comment] 2023-09-27 08:38
@sonialiap I rather think it may not be the same cause here and in the bug you've mentioned. Here the app crashes completely, and there the issue is handled by the app itself showing the error message (but it happens in the web version of the app so it may be the reason). In fact it's hard to say without deeper investigation.

**Comment by michaelhaxhiu** [comment] 2023-09-28 12:02
Wowie this is not reproducible anymore, which tbh I'm happy about (the app was 100% unusable for over 1 week for me!). I tried to tap into a bunch of unreads in the LHN and chat switching to new/existing users with the 🔎  search.

Let's close it! Something fixed it. I made sure to update to latest version and ensure it's working.

**Closed by michaelhaxhiu** 2023-09-28 12:02 UTC
Labels: External, Daily, Help Wanted, Bug
