### ISSUE TITLE
[$500] Request Money - [Scan receipt] Compose box is not focused when visiting requested money details chat after deleting another one

### ISSUE THREAD

**Issue by izarutskaya** [Expensify/App#27249] opened 2023-09-12 12:37 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Open website
2. Click on + icon
3. Request Money
4. Choose Scan, file and user
5. Click on Request btn
6. Reach "Receipt scan in progress" chat and delete it
7. Visit another "Receipt scan in progress" chat

## Expected Result:
Compose box should be focused when visiting requested money details chat after deleting another one

## Actual Result:
Compose box is not focused when visiting requested money details chat after deleting another one

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [x] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** v1.3.68-12

**Reproducible in staging?:** Y

**Reproducible in production?:**  Y

**If this was caught during regression testing, add the test name, ID and link from TestRail:**

**Email or phone of affected tester (no customers):**

**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/115492554/d448c51b-92bb-49dc-9411-db77af715b31

https://github.com/Expensify/App/assets/115492554/118da6fe-1578-4c1a-899f-66ac33c9c1bc

**Expensify/Expensify Issue URL:**

**Issue reported by:** @mahmudjontoraqulov

**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1693323530864789

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

Actual Result: 
<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01a4ca96d5c6ee6b8d</li>
        <li>Upwork Job ID: 1702371901400743936</li>
        <li>Last Price Increase: 2023-09-21</li>
    </ul>
</details>

**Comment by DylanDylann** [comment] 2023-09-12 12:37
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
- Compose box is not focused when visiting requested money details chat after deleting another one

### What is the root cause of that problem?
- This bug occurs with the case manual request as well. 
- Below are the main steps occurs when deleting request money and visit another one:

1. When opening the TransactionThread and clicking on the "Delete Request" button, it will open the confirm modal and set the modal.isVisible to true. (ONYXKEYS.MODAL)
3. After clicking the "Delete" button in the confirm modal, it will navigate the user to the previous report screen without setting the modal.isVisible to true because the modal is unmounted before the onModalHide function (which will set the modal.isVisible to false) is called:
https://github.com/Expensify/App/blob/a2d71a37e4668775d7740e7665220ea0d1fbb6a8/src/components/MoneyRequestHeader.js#L70-L73
5. The modal.isVisible is used to check whether we should run the focus function or not:
https://github.com/Expensify/App/blob/7f5c14a6385bf19a05d51622f11338d4a1b2f487/src/pages/home/report/ReportActionCompose/ComposerWithSuggestions.js#L422-L435
6. Because the modal.isVisible is still true, visiting another one will not auto focus on the composer

### What changes do you think we should make in order to solve the problem?

- We should set the Modal.isvisible to false before navigation actions like below:
```
function deleteMoneyRequest(transactionID, reportAction, isSingleTransactionView = false) {
...
 Modal.setModalVisibility(false);
    if (isSingleTransactionView && shouldDeleteTransactionThread && !shouldDeleteIOUReport) {
        // Pop the deleted report screen before navigating. This prevents navigating to the Concierge chat due to the missing report.
        Navigation.goBack();
        Navigation.navigate(ROUTES.getReportRoute(iouReport.reportID));
        return;
    }

    if (shouldDeleteIOUReport) {
        // Pop the deleted report screen before navigating. This prevents navigating to the Concierge chat due to the missing report.
        Navigation.goBack();
        Navigation.navigate(ROUTES.getReportRoute(iouReport.chatReportID));
    }
}
```
### What alternative solutions did you explore? (Optional)
- NA

### Result
[Screencast from 11-09-2023 22:41:13.webm](https://github.com/Expensify/App/assets/141406735/abf59f29-8e30-4996-8880-290af4638e6c)

**Comment by sakluger** [comment] 2023-09-14 17:20
I reproduced this and do think it's a bug. Here's what I notice:

- When I click into the `User a owes $X` thread from a DM chat, the compose box is focused/highlighted by default
- When I click into an IOU or manual request (I.e. receipt scan in progress) from the `User a owes $X` thread, the compose box is unfocused by default (this is expected)
- When I click back out to the `User a owes $X` thread via the "From" link at the top of the page, the compose box is focused (expected)
- When I click back into the `User a owes $X` thread, then click into an IOU or manual request and delete that IOU/manual request, it brings me back to the `User a owes $X` thread with the compose box unfocused (not expected behavior).

**Comment by sakluger** [comment] 2023-09-18 07:34
@0xmiroslav could you please have a look at the proposal we got last week? Thanks!

**Comment by DylanDylann** [comment] 2023-09-18 07:44
@0xmiroslav why not? Please give me more details. Thanks

**Comment by DylanDylann** [comment] 2023-09-18 08:24
@0xmiroslav currently we have cleanup function when the modal is unmount:
```    useEffect(
        () => () => {
            // Only trigger onClose and setModalVisibility if the modal is unmounting while visible.
            if (isVisible) {
                hideModal(true);
                Modal.willAlertModalBecomeVisible(false);
            }

            // To prevent closing any modal already unmounted when this modal still remains as visible state
            Modal.setCloseModal(null);
        },
        // eslint-disable-next-line react-hooks/exhaustive-deps
        [],
    );
```
- After clicking on the confirm button and navigating to previous report, this cleanup function is called but the isVisible is always false so the hideModal is not called. So we can fix this by adding the ```isVisible``` to the dependences

**Comment by DylanDylann** [comment] 2023-09-21 16:55
@0xmiroslav Please help check this video

[Screencast from 21-09-2023 23:54:26.webm](https://github.com/Expensify/App/assets/141406735/d379ac6f-7d73-47c6-9bd4-0dc0f046e6e8)

**Comment by sakluger** [comment] 2023-09-22 03:26
Chill out Melvin, we're working on this one.

**Comment by DylanDylann** [comment] 2023-09-22 06:36
@0xmiroslav Maybe this issue has been fixed. Can not reproduce this now

**Comment by sakluger** [comment] 2023-09-25 15:38
Okay, thanks you two. Closing.

**Closed by sakluger** 2023-09-25 15:38 UTC
Labels: External, Daily, Help Wanted, Overdue, Bug
