### ISSUE TITLE
[$250] Book travel - Report screen changes to profile view when clicking Country field

### ISSUE THREAD

**Issue by izarutskaya** [Expensify/App#47069] opened 2024-08-08 13:07 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 9.0.18.1
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**Email or phone of affected tester (no customers):** applausetester+kh050806@applause.expensifail.com
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Issue reported by:** Applause-Internal team

## Action Performed:
1. Go to staging.new.expensify.com
2. Go to FAB > Book travel.
3. Click Book travel.
4. Click Country.

## Expected Result:
The report screen in the background will not change to profile page.

## Actual Result:
The report screen in the background changes to profile page while LHN remains the same after opening Country RHP.

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

https://github.com/user-attachments/assets/e82cb612-2a8a-44c4-8885-c7244c90ebd4

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~011952935e51b38f07</li>
        <li>Upwork Job ID: 1826610853854953560</li>
        <li>Last Price Increase: 2024-08-22</li>
<li>Automatic offers: </li>
<ul>
<li>rojiphil | Reviewer | 103684843</li>
</ul></li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @rojiphil</details>

**Comment by izarutskaya** [comment] 2024-08-08 13:08
We think this issue might be related to the #vip-travel

**Comment by abekkala** [comment] 2024-08-13 17:07
@izarutskaya is it _only_ when clicking `Country` that the pages changes or is it any of them?

**Comment by abekkala** [comment] 2024-08-19 14:29
@izarutskaya bumping my question above from last week

**Comment by bernhardoj** [comment] 2024-08-21 17:26
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
The background screen changes to workspace profile view when open address page from travel page.

### What is the root cause of that problem?
The behavior is a bit different now than the video. When we press Book travel, it will open the profile address page and based on the mapping, the workspace address RHP maps to the workspace profile full screen page.
https://github.com/Expensify/App/blob/3559aed60e43c9c179a66fbd5c9dd178cac73324/src/libs/Navigation/linkingConfig/FULL_SCREEN_TO_RHP_MAPPING.ts#L5

So, the workspace profile page is shown. It's the same case with the country selection page where the `backTo` param is the workspace address page which we recursively find the matching root for the `backTo` params page.
https://github.com/Expensify/App/blob/3559aed60e43c9c179a66fbd5c9dd178cac73324/src/libs/Navigation/linkingConfig/getAdaptedStateFromPath.ts#L112-L135

### What changes do you think we should make in order to solve the problem?

We need to add a `backTo` params to the workspace address page that points to the travel page so `getMatchingRootRouteForRHPRoute` will return the matching root for the travel page, which is nothing.

https://github.com/Expensify/App/blob/3559aed60e43c9c179a66fbd5c9dd178cac73324/src/ROUTES.ts#L546-L549

```
getRoute: (policyID: string, backTo?: string) => getUrlWithBackToParam(`settings/workspaces/${policyID}/profile/address` as const, backTo),
```

Then, pass the active route as the `backTo`.
https://github.com/Expensify/App/blob/3559aed60e43c9c179a66fbd5c9dd178cac73324/src/pages/Travel/ManageTrips.tsx#L64
```
Navigation.navigate(ROUTES.WORKSPACE_PROFILE_ADDRESS.getRoute(activePolicyID ?? '-1', Navigation.getActiveRoute()));
```

Next, we need to do the same thing for the address sub-page, that is country and state selection page. Both pages already have a `backTo`, but for the country selection page, we pass the active route without params, so the nested `backTo` is removed.
https://github.com/Expensify/App/blob/3559aed60e43c9c179a66fbd5c9dd178cac73324/src/components/CountrySelector.tsx#L78-L80

So, the matching root will still be the workspace profile page. We need to replace it with `Navigation.getActiveRoute()`.

Last, we need to update the route here so it appends the param correctly because the `backTo` contains a nested `backTo` (`?backTo={...?backTo=...}`).
https://github.com/Expensify/App/blob/3559aed60e43c9c179a66fbd5c9dd178cac73324/src/pages/settings/Profile/PersonalDetails/CountrySelectionPage.tsx#L50-L56

```
} else if (!!backTo && navigation.getState().routes.length === 1) {
    // If "backTo" is not empty and there is only one route, go back to the specific route defined in "backTo" with a country parameter
    Navigation.goBack(appendParam(backTo, 'country', option.value) as Route);
} else {
    // Otherwise, navigate to the specific route defined in "backTo" with a country parameter
    Navigation.navigate(appendParam(backTo, 'country', option.value) as Route);
}
```

**Comment by rojiphil** [comment] 2024-08-23 02:29
Thanks for the proposal. 
The RCA is correct i.e. RHP pages of `Address` and `Country` selection map to the workspace `profile` page in central pane due to which the central pane switches to profile page.
And it makes sense to fix this using `backTo` 
@bernhardoj [proposal](https://github.com/Expensify/App/issues/47069#issuecomment-2302605093) LGTM
🎀👀🎀 C+ reviewed

**Comment by bernhardoj** [comment] 2024-08-26 14:08
PR is ready

cc: @rojiphil

**Comment by abekkala** [comment] 2024-08-29 13:28
note: not yet merged

**Comment by rojiphil** [comment] 2024-09-06 02:14
Oh! The automation did not get triggered here.
Note: Reached production on [06 Sep](https://github.com/Expensify/App/pull/48002#issuecomment-2332465198)

**Comment by rojiphil** [comment] 2024-09-26 03:54
* [x]  [@rojiphil] The PR that introduced the bug has been identified. Link to the PR: [Offending PR](https://github.com/Expensify/App/pull/46333)
* [x]  [@rojiphil] The offending PR has been commented on, pointing out the bug it caused and why, so the author and reviewers can learn from the mistake. Link to comment: [Added comment](https://github.com/Expensify/App/pull/46333/files#r1776318364)
* [x]  [@rojiphil] A discussion in #expensify-bugs has been started about whether any other steps should be taken (e.g. updating the PR review checklist) in order to catch this type of bug sooner. Link to discussion: Not Required. Existing checklist is good enough to capture such issues.
* [x]  [@rojiphil] Determine if we should create a regression test for this bug. : Yes. We can
* [x]  [@rojiphil] If we decide to create a regression test for the bug, please propose the [regression test](https://github.com/Expensify/App/blob/main/contributingGuides/REGRESSION_TEST_BEST_PRACTICES.md) steps to ensure the same bug will not reach production again. 

Steps:
	1	Press FAB > Book travel
	2	Press the Book travel button
	3	(Web/Desktop) Verify that the screen behind the RHP overlay doesn't change
	4	Press Country
	5	(Web/Desktop) Verify that the screen behind the RHP overlay doesn't change
	6	(Android/mWeb/iOS) Close the address and book travel page and verify you are still in LHN. After that, go back to the address page
	7	Change the country to the United States
	8	Press State
	9	(Web/Desktop) Verify that the screen behind the RHP overlay doesn't change
	10	(Android/mWeb/iOS) Close the address and book travel page and verify you are still in LHN.

**Comment by rojiphil** [comment] 2024-09-26 03:56
@abekkala Please help with payment summary here as this reached production 3 weeks ago. I have also added BZ checklist for the issue. Thanks.

**Comment by abekkala** [comment] 2024-09-27 17:54
### PAYMENT SUMMARY: 

- Fix: @rushatgabhane [$250] paid via NewDot
- PR Review: @rojiphil [$250] [Offer ](https://www.upwork.com/nx/wm/offer/104162892)(previous expired)

**Comment by rojiphil** [comment] 2024-09-28 01:26
> * PR Review: @rojiphil [$250] [Offer ](https://www.upwork.com/nx/wm/offer/104162892)(previous expired

@abekkala Accepted offer. Thanks.

**Comment by bernhardoj** [comment] 2024-09-28 03:50
@abekkala I think you paid the wrong Contributor

**Comment by bernhardoj** [comment] 2024-09-28 04:03
Requested in ND.

**Comment by abekkala** [comment] 2024-09-30 12:45
@rojiphil payment sent and contract ended - thank you! 🎉

**Comment by abekkala** [comment] 2024-09-30 12:47
@bernhardoj 
> @abekkala I think you paid the wrong Contributor

yes, I apolize that I tagged the other cont. - I was viewing PR 46333 that Rojiphil linked rather than yours #48002 . I'ved edited.

**Comment by abekkala** [comment] 2024-09-30 12:47
### PAYMENT SUMMARY:

- Fix: @bernhardoj [$250] paid via NewDot https://github.com/Expensify/App/pull/48002
- PR Review: @rojiphil [$250] [Offer ](https://www.upwork.com/nx/wm/offer/104162892)(previous expired) (paid ✅ )

**Closed by abekkala** 2024-09-30 12:47 UTC
Labels: Reviewing, External, Weekly, Bug

**Comment by JmillsExpensify** [comment] 2024-09-30 19:40
$250 approved for @bernhardoj
