### ISSUE TITLE
[$500] Request money - There is no 'From' link in IOU thread report header when creating an IOU in offline mode

### ISSUE THREAD

**Issue by izarutskaya** [Expensify/App#26825] opened 2023-09-05 20:26 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Open an existing chat
2. Apply offline mode from dev tools
3. Click on '+' icon > click on 'Request money' > Enter amount & click on 'Next' button > Click on 'Request' button
4. Click on IOU preview component

## Expected Result:
From link should be displayed on IOU thread report header

## Actual Result:
From link is not displayed on IOU thread report header

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [x] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** v1.3.64-0

**Reproducible in staging?:** Y

**Reproducible in production?:** Y

**If this was caught during regression testing, add the test name, ID and link from TestRail:**

**Email or phone of affected tester (no customers):**

**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/115492554/5c585b17-2477-44ad-a821-01a55ae3b5b5

https://github.com/Expensify/App/assets/115492554/fba788ce-0d09-45b0-a18e-31d536e9c2bc

**Expensify/Expensify Issue URL:**

**Issue reported by:** @Natnael-Guchima

**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1693298415722589

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~0169720c33691dbb43</li>
        <li>Upwork Job ID: 1699835372101046272</li>
        <li>Last Price Increase: 2023-09-14</li>
    </ul>
</details>

**Comment by slafortune** [comment] 2023-09-07 17:21
report looks good!

**Comment by slafortune** [comment] 2023-09-07 17:23
Removing my assignment and leaving @strepanier03  since I'll be going on sabbatical tomorrow.

**Comment by burczu** [comment] 2023-09-11 11:59
not overdue - I'll review it soon

**Comment by strepanier03** [comment] 2023-09-11 12:33
Thanks for the update @burczu!

**Comment by burczu** [comment] 2023-09-12 10:57
@Nodebrute I think you've identified the root cause of the issue correctly, but I'm not sure about the solution. I guess setting `parentReportId` and `parentReportActionId` should be set in `OpenReport` action, am I right? How would you set these values and where exactly?

**Comment by burczu** [comment] 2023-09-14 11:52
@Nodebrute Just checked and you are right, I'm also wasn't able to reproduce it with the newest main. 

cc @strepanier03

**Comment by strepanier03** [comment] 2023-09-14 20:51
@Natnael-Guchima  - As the OG reporter, can you confirm if you can still repro this?

**Comment by strepanier03** [comment] 2023-09-14 20:51
If not, then I am thinking we should close it.

**Comment by Natnael-Guchima** [comment] 2023-09-15 04:06
@strepanier03 It is no longer reproducible. It works fine on staging & prod.

**Comment by strepanier03** [comment] 2023-09-18 20:36
@Natnael-Guchima - Thank you for confirming. I'm going to close this out and if we see a return of the behavior we can reopen.

**Closed by strepanier03** 2023-09-18 20:36 UTC
Labels: External, Daily, Help Wanted, Overdue, Bug
