### ISSUE TITLE
[Awaiting Payment] [$250] Multi tags - Main tag shows "Required" status when all the subtags are disabled

### ISSUE THREAD

**Issue by izarutskaya** [Expensify/App#48683] opened 2024-09-06 08:12 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 9.0.30-4
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**Found when validation PR:** https://github.com/Expensify/App/pull/48381
**Email or phone of affected tester (no customers):** applausetester+kh010901@applause.expensifail.com
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Issue reported by:** Applause-Internal team

## Action Performed:
Precondition:
- Workspace is connected to QBO.

1. Go to staging.new.expensify.com
2. Go to workspace settings > Tags.
3. Click on any main tag.
4. Enable "Required" switch.
5. Select all the subtags > Disable.
6. Disable all the subtags.
7. Return to main tag page.

## Expected Result:
The main tag will not show "Required" status when all the subtags are disabled.

## Actual Result:
The main tag shows "Required" status when all the subtags are disabled.
The "Required" status is gone after reopening the subtag list.

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [x] Android: mWeb Chrome
- [x] iOS: Native
- [x] iOS: mWeb Safari
- [ ] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

https://github.com/user-attachments/assets/fbe6d22f-a91e-451d-8bf0-7e7d16874ad5

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~021833824644157847399</li>
        <li>Upwork Job ID: 1833824644157847399</li>
        <li>Last Price Increase: 2024-09-11</li>
<li>Automatic offers: </li>
<ul>
<li>ikevin127 | Reviewer | 103912305</li>
</ul></li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @ikevin127</details>

**Comment by FitseTLT** [comment] 2024-09-06 09:57
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
Multi tags - Main tag shows "Required" status when all the subtags are disabled
### What is the root cause of that problem?
We are not checking if it has one enabled tag when displaying required tag here
https://github.com/Expensify/App/blob/2ee0bfc29d9be252501e300f7dac794f5f9dd5c1/src/pages/workspace/tags/WorkspaceTagsPage.tsx#L100
### What changes do you think we should make in order to solve the problem?

We should add `&& OptionsListUtils.hasEnabledOptions(tags)` to check if it has an enabled option
### What alternative solutions did you explore? (Optional)

**Comment by garrettmknight** [comment] 2024-09-06 17:22
Checking for a regression on the linked PR

**Comment by Shahidullah-Muffakir** [comment] 2024-09-06 18:23
@garrettmknight 

To hide the "**Required**" label when all tags are disabled, we should implement a similar check to what we applied for the **Required** toggle. The current check only verifies if the policyTagList is required, but it doesn't account for the scenario where all subtags are disabled

in this :
https://github.com/Expensify/App/blob/7dc25152d1595b7e58013de679fe26a7aa1634bd/src/pages/workspace/tags/WorkspaceTagsPage.tsx#L103
We can update the logic as follows:
`labelText={policyTagList.required && !!Object.values(policyTagList?.tags ?? {}).some((tag) => tag.enabled) ? translate('common.required') : undefined}
`
This way, the label will only appear if the main tag is required and at least one subtag is enabled.


Additionally, I'm not sure if this issue is a regression—it seems more like a separate bug that was overlooked in the previous implementation.

**Comment by Shahidullah-Muffakir** [comment] 2024-09-06 18:59
@garrettmknight I’ve opened a PR to address this issue. It’s now ready for review. Thank you.

**Comment by ikevin127** [comment] 2024-09-06 19:30
- ⛔ I'm currently blocked from testing and completing the reviewer checklist by deploy blocker issue https://github.com/Expensify/App/issues/48675, will await until the fix is merged in order to resume testing!

**Comment by ikevin127** [comment] 2024-09-07 05:29
♻️ Will start reviewing the PR in ~12h as a fix for the blocker issue was CPed to main / staging.

**Comment by ikevin127** [comment] 2024-09-08 00:37
Just 🟢 **Approved** the PR for this 🚀

##

FYI we determined that the other issue didn't cause this as in regression but moreso revealed some incomplete logic, therefore this should not be treated as a regression coming from the other issue's PR - more context in https://github.com/Expensify/App/issues/47818#issuecomment-2334710716 (see comment above for proof).

Given the context above, I guess payment should be treated separately for this issue as I noticed automation already created payment issue https://github.com/Expensify/App/issues/48766 once I approved the PR.

cc @garrettmknight

**Comment by sonialiap** [comment] 2024-09-09 08:35
@garrettmknight I think melvin got too excited and created a payment issue, maybe because this hadn't been moved to "external" before the PRs were approved? I'm going to close https://github.com/Expensify/App/issues/48766 in favor of processing payment here, on the main issue

**Comment by garrettmknight** [comment] 2024-09-11 11:09
@FitseTLT appreciate that you put forward a proposal for this. Can you take a look at the PR raised and confirm if your proposal matches it?

**Comment by garrettmknight** [comment] 2024-09-11 11:09
@ikevin127 @Shahidullah-Muffakir I'll pay you both out for this issue since it's a diff one than the other we highlighted.

**Comment by garrettmknight** [comment] 2024-09-11 11:11
@ikevin127 can your review [this proposal](https://github.com/Expensify/App/issues/48683#issuecomment-2333704829) and let me know if it was significantly similar to the [PR](https://github.com/Expensify/App/pull/48738) that solves this bug?

**Comment by FitseTLT** [comment] 2024-09-11 12:48
> @FitseTLT appreciate that you put forward a proposal for this, I'll pay you half if your proposal matches what was implemented.

No it doesn't match @garrettmknight

**Comment by Shahidullah-Muffakir** [comment] 2024-09-11 16:16
> 📣 @Shahidullah-Muffakir You have been assigned to this job! Please apply to the [Upwork job](https://www.upwork.com/jobs/~021833824644157847399) and leave a comment on the Github issue letting us know when we can expect a PR to be ready for review 🧑‍💻 Once you apply to this job, your Upwork ID will be stored and you will be automatically hired for future jobs! Keep in mind: [Code of Conduct](https://github.com/Expensify/App/blob/main/CODE_OF_CONDUCT.md) | [Contributing](https://github.com/Expensify/App/blob/main/contributingGuides/CONTRIBUTING.md) 📖
 
@garrettmknight,
I see I've been assigned to this task, but since the PR is already merged, can you explain the procedure? Do I still need to apply directly on Upwork? Thank you!

**Comment by ikevin127** [comment] 2024-09-12 21:36
> @ikevin127 can your review https://github.com/Expensify/App/issues/48683#issuecomment-2333704829 and let me know if it was significantly similar to the https://github.com/Expensify/App/pull/48738 that solves this bug?

I confirm that the proposed solution and the one applied in the PR completely different.

**Comment by garrettmknight** [comment] 2024-09-17 13:05
@Shahidullah-Muffakir just sent you an offer.

**Comment by Shahidullah-Muffakir** [comment] 2024-09-17 13:09
> @Shahidullah-Muffakir just sent you an offer.

@garrettmknight Thank you, accepted.

**Comment by ikevin127** [comment] 2024-09-18 23:13
⚠️ Automation failed here -> this should have been paid out on **2024-09-17** according to production deploy checklist [Deploy Checklist: New Expensify 2024-09-09](https://github.com/Expensify/App/issues/48791#top) which was shipped to production on **2024-09-10**.

I did not receive the payment yet, here's the contract: https://www.upwork.com/nx/wm/workroom/38345594. In case I'm mistaking and I did receive the payment already - please dismiss 👍 

cc @garrettmknight

**Comment by garrettmknight** [comment] 2024-09-19 19:20
All paid out, sorry for the wait! @ikevin127 can you complete the checklist when you get a chance?

**Comment by ikevin127** [comment] 2024-09-19 19:34
* [x]  [@ikevin127] The PR that introduced the bug has been identified. Link to the PR: https://github.com/Expensify/App/pull/48381
* [x]  [@ikevin127] The offending PR has been commented on, pointing out the bug it caused and why, so the author and reviewers can learn from the mistake. Link to comment: https://github.com/Expensify/App/pull/48381#issuecomment-2362020883
* [x]  [@ikevin127] A discussion in #expensify-bugs has been started about whether any other steps should be taken (e.g. updating the PR review checklist) in order to catch this type of bug sooner. Link to discussion: **N/A**.
* [x]  [@ikevin127] Determine if we should create a regression test for this bug.
* [x]  [@ikevin127] If we decide to create a regression test for the bug, please propose the [regression test](https://github.com/Expensify/App/blob/main/contributingGuides/REGRESSION_TEST_BEST_PRACTICES.md) steps to ensure the same bug will not reach production again.

### Regression Test Proposal

1. Go to staging.new.expensify.com .
2. Go to workspace settings > Tags.
3. Click on any main tag.
4. Enable "Required" switch.
5. Select all the subtags > Disable all subtags.
6. Return to main tag page.
7. Verify that the main tag will not show "Required" label.

Do we agree 👍 or 👎.

**Closed** 2024-09-20 14:16 UTC
Labels: Reviewing, External, Daily, Bug
