### ISSUE TITLE
Android - NetSuite - App freezes then crashes when connecting to NetSuite

### ISSUE THREAD

**Issue by IuliiaHerets** [Expensify/App#52122] opened 2024-11-06 16:09 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 9.0.58-0
**Reproducible in staging?:** Y
**Reproducible in production?:** N
**If this was caught on HybridApp, is this reproducible on New Expensify Standalone?:** Y
**If this was caught during regression testing, add the test name, ID and link from TestRail:** https://expensify.testrail.io/index.php?/tests/view/5188341 
**Email or phone of affected tester (no customers):** htad26+yuiy3ew@gmail.com
**Issue reported by:** Applause Internal Team

## Action Performed:
1. Login to the hybrid app with an account
2. Create a new workspace
3. Go to workspace settings > More features > Enable accounting
4. In the accountings page connect to NetSuite > Upgrade to control > Finish
5. Go through the flow of entering the credentials for connecting to NetSuite

## Expected Result:
The workspace connects to NetSuite

## Actual Result:
App freezes then crashes

## Workaround:
Unknown

## Platforms:

- [x] Android: Standalone
- [x] Android: HybridApp
- [ ] Android: mWeb Chrome
- [ ] iOS: Standalone
- [ ] iOS: HybridApp
- [ ] iOS: mWeb Safari
- [ ] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos
[0611_7.txt](https://github.com/user-attachments/files/17649829/0611_7.txt)

https://github.com/user-attachments/assets/45b5419b-99db-43d9-8abc-9afb026edc80

  
</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Issue Owner</summary>Current Issue Owner: @srikarparsi</details>

**Comment by adelekennedy** [comment] 2024-11-06 18:32
@srikarparsi do you think this is a deployblocker? I Definitely think it's high priority but wonder if we can downgrade as it's only affecting Android users setting up an NS connection?

**Comment by srikarparsi** [comment] 2024-11-06 20:17
Hey! Taking a look

**Comment by srikarparsi** [comment] 2024-11-06 20:26
Checking if this is still reproducible since a lot of the crash errors got fixed by this [revert](https://github.com/Expensify/App/pull/52112)

**Comment by srikarparsi** [comment] 2024-11-06 20:40
Yeah, I think this was also fixed by this [CP](https://github.com/Expensify/App/pull/52112). I'm going to close this out since it's not reproducible on staging anymore.

<img width="362" alt="image" src="https://github.com/user-attachments/assets/e6b44bc7-8d58-45c1-8911-2adb52c18ab7">

**Closed** 2024-11-06 20:47 UTC
Labels: DeployBlockerCash, Engineering, Hourly, Bug
