### ISSUE TITLE
[$500] Modal not closing when clicking "Add Payment Method" the 2nd time

### ISSUE THREAD

**Issue by m-natarajan** [Expensify/App#29770] opened 2023-10-17 13:25 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.3.85-0
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** @aman-atg 
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1697272716485759

## Action Performed:
1. Login to ND
2. Go to Settings > Wallet
3. Click "Add Payment Method" twice
## Expected Result: 
On the second click, the modal should close, similar to other buttons with modals.
## Actual Result: 
The modal does not close, and it flickers after the second click.
## Workaround:
unknown
## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos
<details>
<summary>Android: Native</summary>

https://github.com/Expensify/App/assets/38435837/9703d0d9-d5ff-44c4-8d7a-9415b0eca57b

</details>

<details>
<summary>Android: mWeb Chrome</summary>

https://github.com/Expensify/App/assets/38435837/402df5e8-60d6-4765-b1b1-62088c54c153

</details>

<details>
<summary>iOS: Native</summary>

</details>

<details>
<summary>iOS: mWeb Safari</summary>

https://github.com/Expensify/App/assets/38435837/7cafcb92-8925-481f-9207-193ddab6dd24

</details>

<details>
<summary>MacOS: Chrome / Safari</summary>

https://github.com/Expensify/App/assets/38435837/37f891fe-42f1-4998-979a-b3946075b955

https://github.com/Expensify/App/assets/38435837/2bb90874-2412-4aa9-a19e-4cfc97a58240

</details>

<details>
<summary>MacOS: Desktop</summary>

https://github.com/Expensify/App/assets/38435837/6bd5d5d3-542e-47a7-ba70-dc4d733930bb

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~0183671305ca51e785</li>
        <li>Upwork Job ID: 1714271554879623168</li>
        <li>Last Price Increase: 2023-10-17</li>
    </ul>
</details>

**Comment by m-natarajan** [comment] 2023-10-17 13:26
## Proposal by @aman-atg 

### Please re-state the problem that we are trying to solve in this issue.
Modal not closing when clicking "Add Payment Method" the 2nd time

### What is the root cause of that problem?
We're not passing the ref here like we have in other places which is resulting in this behaviour.

### What changes do you think we should make in order to solve the problem?

We need to pass ref to `Button` in [here](https://github.com/Expensify/App/blob/fe282b45cb13e01519282ccc023e5bfbd7714158/src/pages/settings/Wallet/WalletEmptyState.js#L42) after passing it as prop to `WalletEmptyState` like we're doing for `PaymentMethodList` [here](https://github.com/Expensify/App/blob/fe282b45cb13e01519282ccc023e5bfbd7714158/src/pages/settings/Wallet/WalletPage/WalletPage.js#L409)

**Comment by chiragkcodes** [comment] 2023-10-18 14:43
## Proposal

### Please re-state the problem that we are trying to solve in this issue.

Modal not closing when clicking "Add Payment Method" when Modal is already open.
Instead, it is closing and re-opening Modal (instantly).

### What is the root cause of that problem?

```Button``` used in ```WalletEmptyState``` is not registered as ref for ```AddPaymentMethodMenu``` [here](https://github.com/Expensify/App/blob/fe282b45cb13e01519282ccc023e5bfbd7714158/src/pages/settings/Wallet/WalletEmptyState.js#L42C18-L42C24)
Hence, click on ```Button``` is being considered as a click outside of Modal.
This is closing the Modal and calling ```hideAddPaymentMenu``` with onClose event which updates state - ```shouldShowAddPaymentMenu=false``` [here](https://github.com/Expensify/App/blob/fe282b45cb13e01519282ccc023e5bfbd7714158/src/pages/settings/Wallet/WalletPage/WalletPage.js#L180)
Hence, ```paymentMethodPressed``` updates ```shouldShowAddPaymentMenu=true``` and **re-opens** the menu. [here](https://github.com/Expensify/App/blob/fe282b45cb13e01519282ccc023e5bfbd7714158/src/pages/settings/Wallet/WalletPage/WalletPage.js#L172C43-L172C43)

### What changes do you think we should make in order to solve the problem?

We need to pass the ```addPaymentMethodAnchorRef``` to ```WalletEmptyState``` -> ```Button``` -> ```ref``` (prop)
This way, menu will not call ```onClose``` event when clicked on ```Button``` and ```shouldShowAddPaymentMenu``` stays ```true```.
Eventually, menu gets closed once ```paymentMethodPressed``` is executed. [here](https://github.com/Expensify/App/blob/fe282b45cb13e01519282ccc023e5bfbd7714158/src/pages/settings/Wallet/WalletPage/WalletPage.js#L132C48-L132C48)

### What alternative solutions did you explore? (Optional)
NA

**Comment by chiragkcodes** [comment] 2023-10-18 14:47
Contributor details
Your Expensify account email: chiragkhatri.work@gmail.com
Upwork Profile Link: https://www.upwork.com/freelancers/~010f077fc9022093f1

**Comment by jasperhuangg** [comment] 2023-10-30 21:32
<img width="322" alt="Screenshot 2023-10-30 at 2 32 02 PM" src="https://github.com/Expensify/App/assets/31285285/053a2c54-9c9b-4822-aa23-ee622474bc84">

That is so strange, when I try to assign @aman-atg to this issue, it doesn't let me. Feel free to get started on a PR though!

**Comment by jasperhuangg** [comment] 2023-10-30 23:22
ah, @aman-atg it looks like you need to comment on this issue first in order for me to assign you, do you mind doing that?

**Comment by mvtglobally** [comment] 2023-11-02 03:30
Issue not reproducible during KI retests. (First week)

**Comment by jasperhuangg** [comment] 2023-11-08 23:06
I think we can close this out. The flow has changed which means this specific bug shouldn't be reproducible anymore

**Closed by jasperhuangg** 2023-11-08 23:06 UTC
Labels: External, Engineering, Daily, Help Wanted, Overdue, Bug
