### ISSUE TITLE
[$250] [HOLD for payment 2024-07-22] Expense - Blank area below report header in the expense report

### ISSUE THREAD

**Issue by izarutskaya** [Expensify/App#44434] opened 2024-06-26 09:27 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 9.0.2-0
**Reproducible in staging?:** Y
**Reproducible in production?:** N
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Issue reported by:** Applause-Internal team

## Action Performed:
1. Go to staging.new.expensify.com
2. Go to FAB > Submit expense > Manual.
3. Submit expense to any user that has no unsettled expense.
4. Go to transaction thread.

## Expected Result:
There will be no blank area below the report header.

## Actual Result:
There is small blank area below the report header.
This issue only happens in expense report.

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [x] Android: mWeb Chrome
- [x] iOS: Native
- [x] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

<img width="1188" alt="Bug6524811_1719378867394!Screenshot_2024-06-26_at_13 10 56" src="https://github.com/Expensify/App/assets/115492554/32fab153-ebbc-4e65-ae5a-6f043c280430">

https://github.com/Expensify/App/assets/115492554/6b969160-24c1-4d0c-883f-a28f3c1c824d

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Issue Owner</summary>Current Issue Owner: @</details>
<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~012b0cf135dfea0be9</li>
        <li>Upwork Job ID: 1815882500753303517</li>
        <li>Last Price Increase: 2024-07-23</li>
    </ul>
</details>

**Comment by izarutskaya** [comment] 2024-06-26 09:28
@alexpensify I haven't added the External label as I wasn't 100% sure about this issue. Please take a look and add the label if you agree it's a bug and can be handled by external contributors.

**Comment by izarutskaya** [comment] 2024-06-26 09:28
We think this issue might be related to the #collect project.

**Comment by etCoderDysto** [comment] 2024-06-26 09:29
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
Blank area below report header in the expense report
### What is the root cause of that problem?
We are adding padding of `styles.pb3` in MoneyReportHeader here
https://github.com/Expensify/App/blob/57e5d0e7197a9c21e6f221389bed87870c90ef0a/src/components/MoneyReportHeader.tsx#L378
### What changes do you think we should make in order to solve the problem?
Remove `styles.pb3` from `View` style
### What alternative solutions did you explore? (Optional)

**Comment by etCoderDysto** [comment] 2024-06-26 09:58
The issue is introduced by this [PR](https://github.com/Expensify/App/pull/43618). I can raise a quick pr if the auther are not available at the time.

**Comment by MariaHCD** [comment] 2024-06-26 11:05
Thanks, @tienifr. This is a minor UI bug so I don't necessarily think this should block the deploy. Do you think otherwise, @tienifr?

**Comment by alexpensify** [comment] 2024-06-26 21:15
@tienifr any update here? Thanks!

**Comment by alexpensify** [comment] 2024-06-28 17:59
Update: Awesome a PR is going through the review process!

**Comment by alexpensify** [comment] 2024-07-08 17:51
Catching up from being OOO, it looks like we are waiting for this one to go to prod.

**Comment by alexpensify** [comment] 2024-07-16 22:09
I believe the payment date has been moved to 7/22, and will prepare accordingly.

**Comment by alexpensify** [comment] 2024-07-19 21:34
To prepare for the payment process, I believe that this UI update is a dupe of https://github.com/Expensify/App/issues/39989. I asked the BZ team assigned to that GH for feedback.

**Comment by alexpensify** [comment] 2024-07-22 22:40
I'll work on the payment process tomorrow.

**Comment by alexpensify** [comment] 2024-07-23 22:58
Payouts due: 2024-07-22

- [ ] Contributor: $250 @tienifr 
- [ ] Contributor+: $250 @dukenv0307 

The Upwork job is [here](https://www.upwork.com/jobs/012b0cf135dfea0be9). I noticed @dukenv0307 was part of the review process for this GH. Please accept, and I can proceed with the next steps. Thanks!

**Comment by AirTechWick** [comment] 2024-07-24 03:33
Is this job done?

**Comment by alexpensify** [comment] 2024-07-24 14:34
@AirTechWick - yes, sorry for the confusion, the recent tag updates were to address payment.

**Comment by alexpensify** [comment] 2024-07-25 23:11
@dukenv0307 - please accept the invite in Upwork. After, I can complete the payment process. Thanks!

**Comment by alexpensify** [comment] 2024-07-26 21:27
No update yet in Upwork.

**Comment by alexpensify** [comment] 2024-07-29 18:29
Thank you! I've completed the payment process in Upwork and updated the payment summary - 

https://github.com/Expensify/App/issues/44434#issuecomment-2246441919

@tienifr, please submit a request in Chat; thanks!

**Closed by alexpensify** 2024-07-29 18:29 UTC
Labels: External, Engineering, Daily, Overdue, Awaiting Payment, Bug

**Comment by JmillsExpensify** [comment] 2024-08-14 18:40
$250 approved for @tienifr
