### ISSUE TITLE
[$500]  Task – “Task description is too long” not disappears when delete description

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#33782] opened 2023-12-29 21:12 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.20-0
**Reproducible in staging?:** Y 
**Reproducible in production?:** Y 
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** Applause - Internal Team
**Slack conversation:**

## Action Performed:
1. Go to https://staging.new.expensify.com/
2. Log in with any account.
3. Create a task and open task details
4. Add a long description
5. Delete description when verify error message “Task description is too long”

## Expected Result:
“Task description is too long” message disappears when delete description

## Actual Result:
“Task description is too long” not disappears when delete description

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [x] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details> 

https://github.com/Expensify/App/assets/78819774/f41c0357-ea11-43b9-abc8-b6c1e45fd9bf

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01792a2125359f6406</li>
        <li>Upwork Job ID: 1740843249453105152</li>
        <li>Last Price Increase: 2023-12-29</li>
<li>Automatic offers: </li>
<ul>
<li>hoangzinh | Reviewer | 28077375</li>
<li>dukenv0307 | Contributor | 28077376</li>
</ul></li>
    </ul>
</details>

**Comment by Tony-MK** [comment] 2023-12-29 21:24
## Proposal

### Please re-state the problem that we are trying to solve in this issue.

### What is the root cause of that problem?

We are not clearing the task error sent by the backend.

### What changes do you think we should make in order to solve the problem?


If this occurs, we can call `clearTaskErrors` function when the user is editing the task or after editing to clear the error. 

To be precise we can clear the 'description is too long' error from the onyx after the description has changed successfully.

### What alternative solutions did you explore? (Optional)

We can validate the length of the description on the front end before the form is submitted to the backend.

**Comment by unicorndev-727** [comment] 2023-12-29 21:32
## Proposal
from: @unicorndev-727
### Please re-state the problem that we are trying to solve in this issue.
We are not clearing the task error sent by the backend.
### What is the root cause of that problem?
The root cause is that we don't send errorFields update request when creating onyx data here.
https://github.com/Expensify/App/blob/595bf4075988c0b64cb0db1e37694284637fbea2/src/libs/actions/Task.js#L378-L396

### What changes do you think we should make in order to solve the problem?
We need to update this part 
https://github.com/Expensify/App/blob/595bf4075988c0b64cb0db1e37694284637fbea2/src/libs/actions/Task.js#L380-L400
to
```
const optimisticData = [
        {
            onyxMethod: Onyx.METHOD.MERGE,
            key: `${ONYXKEYS.COLLECTION.REPORT_ACTIONS}${report.reportID}`,
            value: {[editTaskReportAction.reportActionID]: editTaskReportAction},
        },
        {
            onyxMethod: Onyx.METHOD.MERGE,
            key: `${ONYXKEYS.COLLECTION.REPORT}${report.reportID}`,
            value: {
                reportName,
                description: reportDescription,
                pendingFields: {
                    ...(title && {reportName: CONST.RED_BRICK_ROAD_PENDING_ACTION.UPDATE}),
                    ...(description && {description: CONST.RED_BRICK_ROAD_PENDING_ACTION.UPDATE}),
                    ...(errors && {errorFields: CONST.RED_BRICK_ROAD_PENDING_ACTION.UPDATE}),
                },
            },
        },
    ];
    const successData = [
        {
            onyxMethod: Onyx.METHOD.MERGE,
            key: `${ONYXKEYS.COLLECTION.REPORT}${report.reportID}`,
            value: {
                pendingFields: {
                    ...(title && {reportName: null}),
                    ...(description && {description: null}),
                    ...(errors && {errorFields: null}),
                },
            },
        },
    ];
    ```

### What alternative solutions did you explore? (Optional)
  N/A

**Comment by sonialiap** [comment] 2024-02-20 14:47
Not adding a regression test. Closing

**Closed by sonialiap** 2024-02-20 14:47 UTC
Labels: Reviewing, External, Weekly, Bug
