### ISSUE TITLE
Markdown text in report comment is handling short mentions and long mentions wrong

### ISSUE THREAD

**Issue by SzymczakJ** [Expensify/App#38305] opened 2024-03-14 13:38 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.52-0
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):** jakub.szymczak+test2@swmansion.com
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** Jakub Szymczak - Software Mansion external agency
**Slack conversation:**

## Action Performed:
1. Have somebody(eg. jakub.szymczak) in your "proposed mention list" just like in video and this user has to have the same email domain as you do. To add smb to your proposed mention list just write a message to him.
2. Try to mention him with his whole email address.
## Expected Result:
When you want to "long mention" anyone, then the whole email address should be contained in mention body.
## Actual Result:
The email domain is not contained in mention body, it's just a plain text
## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [x] Android: mWeb Chrome
- [x] iOS: Native
- [x] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

https://github.com/Expensify/App/assets/88395093/2fbfdef8-9d77-4c4d-a6ee-fb20cada74c6

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by garrettmknight** [comment] 2024-03-15 13:03
I think this is potentially a dupe of https://github.com/Expensify/App/issues/38303 - fixing that should fix this one.

**Closed by garrettmknight** 2024-03-15 13:03 UTC
Labels: Daily, Bug
