### ISSUE TITLE
Payment due - 30 May [$250] Typing `@useraccount` and sending it sends `@useraccount@domain.com

### ISSUE THREAD

**Issue by m-natarajan** [Expensify/App#40205] opened 2024-04-13 14:04 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.62-5
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** @cead22 
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1712874830762349

## Action Performed:
1. Open any chat
2. Type ` @applausetester ` and hit send (Make sure to use "`" to make it a codeblock)

## Expected Result:
Appears ` @applausetester ` after sending

## Actual Result:
Appears as `@applausetester@applause.expensifail.com`
## Workaround:
unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

https://github.com/Expensify/App/assets/38435837/b26927cc-37a4-44e0-adb1-86dcf1c170dc

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~0115db0ab43f78ece5</li>
        <li>Upwork Job ID: 1779954988168179712</li>
        <li>Last Price Increase: 2024-04-22</li>
<li>Automatic offers: </li>
<ul>
<li>shubham1206agra | Reviewer | 0</li>
<li>tienifr | Contributor | 0</li>
</ul></li>
    </ul>
</details>

**Comment by MitchExpensify** [comment] 2024-04-15 19:27
Reproduced

**Comment by MitchExpensify** [comment] 2024-04-15 19:28
Assigning to VSB as low as this is a chat-centric bug that reveals emails

**Comment by sufyan-siddiqui** [comment] 2024-04-17 05:22
I'm not able to reproduce. Any help would be appreciated.


https://github.com/Expensify/App/assets/54620116/ae8e80ee-7ef8-42a5-8045-871b7f174181

**Comment by cead22** [comment] 2024-04-17 16:32
> So even the short-hand mention inside codeblock is still appended with the private domain. And subsequently it will not be considered in the mention detection logic in `expensify-common`

@tienifr to clarify, it should not be considered a mention if it's inside backticks, right?



> We'll need to:
> * Modify the Regex for short mentions (similar to for full mention, but do not that for short mention we need to check markdown signs instead of html elements)

Where/how?

> * Add logic to check `isValidMention` similar to [here](https://github.com/Expensify/expensify-common/blob/c0f7f3b6558fbeda0527c80d68460d418afef219/lib/str.js#L963C5-L963C19)

Where/how?

**Comment by MitchExpensify** [comment] 2024-04-22 21:42
Not overdue, @tienifr is going to have a look soon

**Comment by laurenreidexpensify** [comment] 2024-04-28 10:03
@shubham1206agra bump for review thanks

**Comment by robertjchen** [comment] 2024-04-29 08:41
👍 to updated proposal

**Comment by laurenreidexpensify** [comment] 2024-05-28 09:22
@MitchExpensify looks like the payment job on this failed but it's on prod now so should be good to pay on Thurs. Handing back over to you!

**Comment by MitchExpensify** [comment] 2024-05-30 04:00
Reminder set to pay tomorrow!

**Comment by MitchExpensify** [comment] 2024-06-04 16:44
Paid and contract ended!

**Closed by MitchExpensify** 2024-06-04 16:44 UTC
Labels: Reviewing, External, Daily, Bug
