### ISSUE TITLE
mWeb - Chat - In offline, emojis are not striked out when deleted with markdown

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#42212] opened 2024-05-15 19:59 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.74
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**If this was caught during regression testing, add the test name, ID and link from TestRail:** https://expensify.testrail.io/index.php?/tests/view/4562779
**Issue reported by:** Applause - Internal Team

## Action Performed:
Pre-condition: Be in offline
1. Go to https://staging.new.expensify.com/home
2. Tap on a report
3. Enter >😁
4. Select the message
5. Copy and paste the message twice
6. Send the message
7. Long press the sent message and delete it

## Expected Result:
In offline, emojis must be strike out when deleted with markdown

## Actual Result:
In offline, emojis are not striked out when deleted with markdown

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [x] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [ ] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details> 

https://github.com/Expensify/App/assets/78819774/183c9081-fad8-4b22-9505-ea6ca8327715

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by lanitochka17** [comment] 2024-05-15 19:59
@laurenreidexpensify  FYI I haven't added the External label as I wasn't 100% sure about this issue. Please take a look and add the label if you agree it's a bug and can be handled by external contributors

**Comment by lanitochka17** [comment] 2024-05-15 20:00
We think that this bug might be related to #vip-vsp

**Comment by laurenreidexpensify** [comment] 2024-05-16 09:11
@Expensify/design curious for your thoughts here - this doesn't seem like a bug worth addressing ?

**Comment by bernhardoj** [comment] 2024-05-16 09:14
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
The deleted message with emoji inside a markdown doesn't get strikethrough.

### What is the root cause of that problem?
In https://github.com/Expensify/App/pull/40617, we prevent the emoji to be formatted (bold, italic, strikethrough), so if we type `~😄~`, the strikethrough won't apply.

https://github.com/Expensify/App/blob/4499fa244a209bfe709b803864b23e6eae65f56c/src/styles/utils/emojiDefaultStyles/index.ts#L8
https://github.com/Expensify/App/blob/4499fa244a209bfe709b803864b23e6eae65f56c/src/styles/utils/emojiDefaultStyles/index.native.ts#L6

### What changes do you think we should make in order to solve the problem?

If we want to show the strikethrough only when the message is deleted, first, convert `emojiDefaultStyles` to a function that acceps whether the message is deleted or not. If it's deleted, then don't apply the `display: inline-flex` (web) and `textDecorationLine: none` style (native).

https://github.com/Expensify/App/blob/4499fa244a209bfe709b803864b23e6eae65f56c/src/styles/utils/emojiDefaultStyles/index.native.ts#L3

To know whether it's deleted or not, we can add `deleted` attribute to the emoji tag.
https://github.com/Expensify/App/blob/4499fa244a209bfe709b803864b23e6eae65f56c/src/pages/home/report/comment/TextCommentFragment.tsx#L57

```
const htmlWithDeletedTag = styleAsDeleted ? `<del>${html.replaceAll('<emoji>', '<emoji deleted>')}</del>` : html;
```

Then, check whether `deleted` exists on the `attributes` and pass it to the `emojiDefaultStyles` style.
https://github.com/Expensify/App/blob/4499fa244a209bfe709b803864b23e6eae65f56c/src/components/HTMLEngineProvider/HTMLRenderers/EmojiRenderer.tsx#L6-L11

```
styles.emojiDefaultStyles('deleted' in tnode.attributes)
```

We need to apply it to InlineCodeBlock and WrappedText too.

### What alternative solutions did you explore? (Optional)
Create a new context to hold the deleted message value, wrap the context here,
https://github.com/Expensify/App/blob/4499fa244a209bfe709b803864b23e6eae65f56c/src/pages/home/report/comment/TextCommentFragment.tsx#L66-L71

and access the context (useContext) in EmojiRenderer, InlineCodeBlock, and WrappedText.

**Comment by trjExpensify** [comment] 2024-05-16 11:22
> @Expensify/design curious for your thoughts here - this doesn't seem like a bug worth addressing ?

Yeah, interesting one. It is "breaking the pattern" insofar as not providing feedback that it's pending to be deleted with strikethrough, but being greyed out is signalling there's a change pending to happen. I think it's fine to not apply strikethrough to the emoji in the offline case, the same as we don't allow it via markdown. We do something similar with a custom avatar you delete when offline, we don't put strikethrough through your profile pic while it's pending to be deleted - it's just greyed out because it looks weird otherwise. So I think we can close this personally 👍

**Comment by shawnborton** [comment] 2024-05-16 12:21
Yeah, I'm cool with that too. Feels pretty edge case as well.

**Comment by dannymcclain** [comment] 2024-05-16 13:55
Same here. I'm good with closing.

**Comment by bernhardoj** [comment] 2024-05-16 13:58
But the emoji gets strikethrough if it's plain text (not a markdown), I think it's inconsistent.

<img width="240" alt="image" src="https://github.com/Expensify/App/assets/50919443/79895d1a-ab2a-4779-abc7-539f6fd4b967">

**Comment by trjExpensify** [comment] 2024-05-16 14:52
Oh cool, so it even works in the mainline case! So yeah, I still think it's fine to not worry about this. We don't strikethrough emojis in markdown, whether that's a user's input or due to a pending offline action. Equally though, in a more standard case of words with emojis in quoted markdown, I think this looks fine for the case we're talking about:

<img width="569" alt="image" src="https://github.com/Expensify/App/assets/16232057/611047d2-772f-4c7d-8641-d24ef59fafc9">

**Closed** 2024-05-17 07:21 UTC
Labels: Daily, Bug
