### ISSUE TITLE
[HOLD for payment 2023-01-11] Concierge chat : Phone icon at the top right is by default activated/highlighted.

### ISSUE THREAD

**Issue by kavimuru** [Expensify/App#13829] opened 2022-12-26 16:18 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:

1. Open Concierge chat
2. Observe the header Phone icon

## Expected Result:
Phone icon should not be highlighted by default

## Actual Result:
Phone icon is by default highlighted

## Workaround:
unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [ ] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 1.2.43-1
**Reproducible in staging?:** y
**Reproducible in production?:** y
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** 
<img width="1439" alt="Screenshot 2022-12-23 at 6 34 18 PM" src="https://user-images.githubusercontent.com/43996225/209567026-a5002fc3-09bd-419b-a461-796e82ddb939.png">
<img width="960" alt="IMG_3161" src="https://user-images.githubusercontent.com/43996225/209567037-71a68437-e72f-4a35-8387-5f47b81f46da.PNG">

**Expensify/Expensify Issue URL:**
**Issue reported by:** @Pujan92 
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1671801157278869

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~0131b4db70e8abd4a3</li>
        <li>Upwork Job ID: 1607705873222352896</li>
        <li>Last Price Increase: 2022-12-27</li>
    </ul>
</details>

**Comment by JmillsExpensify** [comment] 2022-12-27 04:28
@Pujan92 @kavimuru I'm unable to reproduce this bug using the steps in the issue description. What else do we need to add to get the same issue?

**Comment by Gonals** [comment] 2022-12-27 11:32
I can reproduce it:

Concierge:
<img width="832" alt="Screenshot 2022-12-27 at 12 30 33 PM" src="https://user-images.githubusercontent.com/19366280/209660541-a1241c6b-386a-4239-8de5-b8cedc296ebb.png">

Other chats:
<img width="833" alt="Screenshot 2022-12-27 at 12 30 41 PM" src="https://user-images.githubusercontent.com/19366280/209660556-08746c3e-1fc9-4543-bbff-ee26dd9579ab.png">

**Comment by Gonals** [comment] 2022-12-27 11:37
Happens on mobile too:
<img width="447" alt="Screenshot 2022-12-27 at 12 36 45 PM" src="https://user-images.githubusercontent.com/19366280/209661008-9d212960-4e2f-4575-9691-ccf32da8a9d1.png">

**Comment by Gonals** [comment] 2022-12-27 11:48
This has clearly been done on purpose on [this commit](https://github.com/Expensify/App/pull/3697/commits/fb5c2c305bfb72894fa0d78ef17b996af69a2077).

@jasperhuangg, do you recall why that decision was made? (I know it has been a while)

**Comment by Gonals** [comment] 2022-12-27 11:53
Ah, @jasperhuangg is OOO until next year! 
Well, we can decide whether we want it to remain as-is or we can just change it. It is a 1 line change :)

**Comment by JmillsExpensify** [comment] 2022-12-27 16:29
Ah thanks for chiming in @Gonals! I just misunderstood what "activated" meant. I can consistently reproduce as you show above. 

That said, I agree that it's confusing to treat the phone icon in the Concierge DM different than all the other phones in other DMs. In general, I'm pretty against creating all this special logic for Concierge that ends up creating a confusing experience everywhere else that you interact with the phone/pin icons.

**Comment by JmillsExpensify** [comment] 2022-12-27 16:30
Regardless, given that this is not a bug, I've removed the `Bug` label. Heads up @Pujan92 as we are not compensating for new features and changes to explicit design decisions (even if I happen to agree with you on this one and feel the current behavior is inconsistent).

**Comment by Gonals** [comment] 2022-12-28 11:01
Sounds good! PR in place!

**Comment by JmillsExpensify** [comment] 2023-01-11 05:06
This was purely internal and the PR hit production last week, so I'm going to go ahead and close.

**Comment by JmillsExpensify** [comment] 2023-01-12 03:14
Whoops. Not sure what I was referring to above, as we do need to compensate @Pujan92 $250 for his report. Looks like my option of automatically creating an Upwork job isn't possible, so I'll create one manually now.

**Comment by JmillsExpensify** [comment] 2023-01-12 03:29
Upwork job is here: https://www.upwork.com/jobs/~017ddb098501a67952. Please apply and we'll get you settled up. Thanks!

**Comment by Pujan92** [comment] 2023-01-12 03:34
> Upwork job is here: https://www.upwork.com/jobs/~017ddb098501a67952. Please apply and we'll get you settled up. Thanks!

Applied @JmillsExpensify . Please adjust extra paid in this [issue](https://github.com/Expensify/App/issues/12804#issuecomment-1333169255) within this job.

**Comment by netprince1210-dev** [comment] 2023-01-12 03:36
> Upwork job is here: https://www.upwork.com/jobs/~017ddb098501a67952. Please apply and we'll get you settled up. Thanks!

I have applied please adjust extra paid in this issue within this job

**Comment by JmillsExpensify** [comment] 2023-01-12 04:13
@Pujan92 I'm impressed you remembered and appreciate that! However, it's really not necessary. It's great to have you part of the community.

**Comment by netprince1210-dev** [comment] 2023-01-12 04:15
Thanks for your email.

What do you want me to do?

I am a full stack web & mobile developer.

**Comment by JmillsExpensify** [comment] 2023-01-12 04:28
Thanks @Pujan92! You're all paid out now. I'm closing the issue.

**Closed by JmillsExpensify** 2023-01-12 04:28 UTC
Labels: Reviewing, External, Engineering, Daily, Improvement, Internal, Awaiting Payment, Bug

**Comment by netprince1210-dev** [comment] 2023-01-12 04:30
Thank you!
