### ISSUE TITLE
Web - There is still error even uploading image successfully on another window

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#26254] opened 2023-08-29 20:10 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Open website on 2 windows > Settings > Workspaces > Any workspace > settings of it
2. On first window, Upload image smaller than 80x80 pixels so that you can get an error.
3. On second window, Upload acceptable image

## Expected Result:
There should not be error even uploading image successfully on another window

## Actual Result:
 There is still error even uploading image successfully on another window

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [x] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 1.3.58.0
**Reproducible in staging?:** n/a
**Reproducible in production?:** n/a
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation

[screen-capture (32) (2).webm](https://github.com/Expensify/App/assets/93399543/708b1da9-cb8c-4328-bc2d-c472d2e719ac)

**Expensify/Expensify Issue URL:**
**Issue reported by:** @mahmudjontoraqulov
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1692249298519699

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by StevenKKC** [comment] 2023-08-30 13:45
## Proposal

### Please state again the problem we are trying to solve in this issue.
There is still error even uploading image successfully on another window.

### What is the cause of this issue?
The root cause is that we does not empty error message when avatar source is changed in `AvatarWithImagePicker`.

### What changes do you think we should make to solve the problem?
We can add check whether avatar source is changed or not in `AvatarWithImagePicker`'s `componentDidUpdate`.
```js
    componentDidUpdate(prevProps) {
        ...
        if (prevProps.source !== this.props.source) {
            this.setState({validationError: null, phraseParam: {}});
        }
    }
```
### What alternative solutions have you investigated? (Optional)
None.

**Comment by puneetlath** [comment] 2023-09-05 20:55
In general, I think we should ignore "two windows open at the same time on the same page" type bugs for now. They don't feel like a real use-case that users will hit and it's causing us to add bloat to the codebase to support. I'm going to close this, but feel free to comment if you disagree.

**Closed by puneetlath** 2023-09-05 20:55 UTC
Labels: Daily, Needs Reproduction, Overdue, Bug
