### ISSUE TITLE
[$500] mWeb/Chrome - Login - Left half of the text selector is visible

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#32496] opened 2023-12-05 17:47 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.8.0
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** Applause - Internal Team
**Slack conversation:**

## Action Performed:
1. Navigate to https://staging.new.expensify.com/
2. Type in any email address
3. Long tap on any magic code bracket

## Expected Result:
The right one should be also visible
Or it shouldn't be visible at all if it's not needed on the magic code

## Actual Result:
Left half of the text selector is visible

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [x] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [ ] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details> 

![Bug6302044_1701794379837!1](https://github.com/Expensify/App/assets/78819774/1c3e7479-1a13-41db-9f1f-60cd8fcc8a66)

https://github.com/Expensify/App/assets/78819774/8f898a08-3e5e-4e27-9282-26f6f6df749f

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~011bbe3ca6ae771280</li>
        <li>Upwork Job ID: 1732094325192740864</li>
        <li>Last Price Increase: 2023-12-12</li>
<li>Automatic offers: </li>
<ul>
<li>DylanDylann | Contributor | 28061766</li>
<li>situchan | Contributor | 28073052</li>
</ul></li>
    </ul>
</details>

**Comment by Tony-MK** [comment] 2023-12-07 02:33
I don't think this is a bug. This should be the default behavior on Andriod when text input is empty. There is only one text selector because there is no text to select and that is where the location of the cursor. So the left and right selectors combine into one. 

The native application of Android also displays one text selector. Currently, it is not possible to remove it on the web platform. However, it should be possible to change or remove it on the native application. Could you look into the default Android "blue bubble" behaviors?

**Comment by DylanDylann** [comment] 2023-12-08 11:44
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
- mWeb/Chrome - Login - Left half of the text selector is visible
### What is the root cause of that problem?

### What changes do you think we should make in order to solve the problem?
- We can set props ```caretHidden:true```

### What alternative solutions did you explore? (Optional)

**Reminder:** Please use plain English, be brief and avoid jargon. Feel free to use images, charts or pseudo-code if necessary. Do not post large multi-line diffs or write walls of text. Do not create PRs unless you have been hired for this job.

**Comment by johncschuster** [comment] 2023-12-08 21:37
Not overdue. We're still getting proposals in

**Comment by ArekChr** [comment] 2023-12-12 10:12
@DylanDylann After setting the `carretHidden` prop to true, the issue still exists when long pressing on MagicCodeInput

<img width="380" alt="Zrzut ekranu 2023-12-12 o 11 06 47" src="https://github.com/Expensify/App/assets/24796318/ad172694-ea05-4a8b-bb22-50f9f55ef88b">

**Comment by DylanDylann** [comment] 2023-12-12 10:13
@ArekChr How do you set it?

**Comment by ArekChr** [comment] 2023-12-12 10:16
@DylanDylann Like in your proposal, [App/src/components/MagicCodeInput.js](https://github.com/Expensify/App/blob/18d4b9b661e77ff1d3e5d0c335df5c838c405345/src/components/MagicCodeInput.js#L370) added `carretHidden` in line 371

**Comment by DylanDylann** [comment] 2023-12-12 10:28
@ArekChr We need to somehow pass the ```caretHidden``` to this:
https://github.com/Expensify/App/blob/2165e74853e491fedf9152bdee2b291269496b88/src/components/RNTextInput.tsx#L10-L25

- When creating the proposal, I am just write the general idea

**Comment by johncschuster** [comment] 2023-12-18 15:24
I'm OOO starting Monday, December 18, and will return Tuesday, January 2.

Current status:
The issue has been assigned to @DylanDylann. We're waiting on a PR (Thanks, @DylanDylann!)

If this issue is open when I'm back from OOO, I'll take it back over. Thank you!

**Comment by DylanDylann** [comment] 2023-12-18 15:29
@johncschuster I am working on it

**Comment by joekaufmanexpensify** [comment] 2023-12-20 14:34
PR in progress

**Comment by joekaufmanexpensify** [comment] 2023-12-21 15:54
Going to change this to weekly, since I'm OOO next week.

**Comment by joelbettner** [comment] 2023-12-29 20:43
@DylanDylann any word on this?

**Comment by situchan** [comment] 2023-12-29 20:46
@joelbettner if you check discussion in https://github.com/Expensify/App/pull/33267, the bug is not fixed on android chrome.

Btw, I can take over C+ since @ArekChr is now not in C+ team

**Comment by joekaufmanexpensify** [comment] 2024-01-02 15:33
@johncschuster I've been a bit slammed with assignments coming back from OOO, so going to let you take this one back. LMK if there's anything else I can help with though!

**Comment by situchan** [comment] 2024-01-04 08:02
@joelbettner I think we should open this back to proposals. Accepted solution doesn't work on android chrome, which is OP

**Comment by johncschuster** [comment] 2024-01-05 01:38
@situchan I'm fine with opening this back up for proposals, but I would also be interested to see if @DylanDylann can resolve the Android Chrome issue.

**Comment by joelbettner** [comment] 2024-01-08 18:54
Does this need to be a daily?

**Comment by DylanDylann** [comment] 2024-01-08 19:50
@johncschuster From my side, I do not have any idea how to fix the issue in Android Chrome, just can fix it in Android Native (the issue also appears in Android native). Anyway feel free to back up  for proposals

**Comment by situchan** [comment] 2024-01-12 15:11
> I found that setting the fontSize to a value between '.2px' to '.5px' hides the remaining part of the text selector.

@Krishna2323 can you please share permalink where to apply this change?
I am not sure this issue is important enough to apply such workaround.

**Comment by situchan** [comment] 2024-01-15 17:12
@Krishna2323 can you please share test branch?

**Comment by joelbettner** [comment] 2024-01-17 20:00
I'm going to unassign myself from this so I can increase my focus on other issues. Feel free to use the auto-assigner to re-assign another engineer.

**Comment by situchan** [comment] 2024-01-18 03:38
yes open for more proposals

**Comment by situchan** [comment] 2024-01-23 10:47
@Krishna2323 yes, thanks for demo. I will take decision if we don't get any proposals until end of this week.

**Comment by situchan** [comment] 2024-01-29 06:05
@Krishna2323 there's side effect unfortunately. You can see wrong position of Paste menu. So that workaround is not acceptable.

Before:
<img width="377" alt="Screenshot 2024-01-29 at 12 03 11 PM" src="https://github.com/Expensify/App/assets/108292595/a6abb79f-f8f5-4a7a-a171-c26f82e8f7b7">

After:
<img width="377" alt="Screenshot 2024-01-29 at 12 05 09 PM" src="https://github.com/Expensify/App/assets/108292595/83dc1553-2501-47db-91e6-e9051f95e70e">

**Comment by situchan** [comment] 2024-01-29 06:17
Why is .5 the most reasonable value?

**Comment by johncschuster** [comment] 2024-02-01 22:48
Just bumping to keep Melvin happy and to voice that I'm also curious why 0.5 works.

**Comment by johncschuster** [comment] 2024-02-05 23:38
@Krishna2323 have you been able to find a reason why 0.5 works?

**Comment by situchan** [comment] 2024-02-08 21:16
Not overdue

**Comment by johncschuster** [comment] 2024-02-14 16:25
No overdue. We're waiting on further investigation from @Krishna2323

**Comment by situchan** [comment] 2024-02-19 15:27
Still looking for better solution

**Comment by situchan** [comment] 2024-02-21 21:24
Not overdue

**Comment by situchan** [comment] 2024-02-26 15:03
Same

**Comment by johncschuster** [comment] 2024-02-28 16:02
@situchan I think we should move on to find a different solution rather than wait on @Krishna2323.

**Comment by johncschuster** [comment] 2024-03-01 22:38
Raised this in [Slack](https://expensify.slack.com/archives/C01GTK53T8Q/p1709332683880169)

**Comment by CalobHumble** [comment] 2024-03-01 23:39
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
A text selection caret appears when you long-press the input of the MagicCodeInput component, this should not appear.

### What is the root cause of that problem?
Standard text input pointer events are being processed by android, and because of the android workaround, manifests a text selection caret when we long-press any of the inputs.

### What changes do you think we should make in order to solve the problem?
Add `pointerEvents='box-none'` to the props for the TextInput as part of the android work around.  This also returns the default long-press behavior to dismissing the soft keyboard, which may need to be addressed by tweaking the gesture handler on the component, should this not be desired.

### What alternative solutions did you explore? (Optional)
Tried disabling the caret with 'caretHidden`, this did not provide the desired outcome.

**Comment by CalobHumble** [comment] 2024-03-01 23:40
Contributor details
Your Expensify account email: humble@calob.dev
Upwork Profile Link: https://www.upwork.com/freelancers/~0164488c5a59ce614e

**Comment by CalobHumble** [comment] 2024-03-02 02:20
Updated proposed for clarity.

**Comment by Victor-Nyagudi** [comment] 2024-03-02 19:44
Not sure what the expected behavior is here.

When you long-press a magic code input, the Android cursor appears, which is normal behavior when you long-press an empty section of an input (unless I'm missing something).

![Screenshot_20240302_223636_Chrome.jpg](https://github.com/Expensify/App/assets/79470910/598c4dfb-8745-4492-810e-1a572f786991)

When you long press text in an input, two selectors appear. Notice how these are angled. 

![Screenshot_20240302_223732_Chrome.jpg](https://github.com/Expensify/App/assets/79470910/7d22134b-8968-4eea-89b6-08b5b291c17b)

The icon that appears is neither a right nor left text selector, just a regular cursor.

Unless maybe, the bug is the cursor not moving?

**Comment by situchan** [comment] 2024-03-04 14:24
@Victor-Nyagudi did you check OP? this is bug to fix

![288150673-1c3e7479-1a13-41db-9f1f-60cd8fcc8a66](https://github.com/Expensify/App/assets/108292595/530328eb-fbc3-4614-929d-c6af51e11be3)

**Comment by Victor-Nyagudi** [comment] 2024-03-04 18:19
@situchan I did. The wording is what I needed clarity on.

The picture you shared is of a regular Android cursor icon, but the OP talks about a text selector, which isn't exactly the same thing.

I presume the bug is the cursor icon showing when a magic code input is pressed, and we want to not show it, correct?

**Comment by johncschuster** [comment] 2024-03-06 23:03
@situchan bump on the above!

**Comment by johncschuster** [comment] 2024-03-11 21:14
[Bumped in Slack](https://expensify.slack.com/archives/C02NK2DQWUX/p1710191632484219)

**Comment by situchan** [comment] 2024-03-11 21:16
@Victor-Nyagudi I am not sure what is not understandable. Issue title and OP clearly stated it.
text selector in OP means android cursor

> I presume the bug is the cursor icon showing when a magic code input is pressed, and we want to not show it, correct?

correct

**Comment by johncschuster** [comment] 2024-03-14 21:08
@situchan can you review the proposal, [here](https://github.com/Expensify/App/issues/32496#issuecomment-1974079510)? Thanks!

**Comment by situchan** [comment] 2024-03-14 21:24
@CalobHumble thanks for the proposal. Have you tested your solution? It doesn't work for me.

**Comment by CalobHumble** [comment] 2024-03-14 21:58
@situchan I tested on android emulator using chrome mWeb.  I don't remember if any details were left out, and I'm busy at the moment, but I will verify tonight and update you here if any details were left out.

**Comment by situchan** [comment] 2024-03-18 19:13
Meanwhile, we're still waiting for proposals

**Comment by situchan** [comment] 2024-03-22 15:28
@johncschuster I suggest to close this for now and focus on more priority bugs.
We can reopen after wave is gone.

**Comment by situchan** [comment] 2024-03-22 15:31
@jasperhuangg can you please check https://github.com/Expensify/App/issues/32496#issuecomment-2015345029?
We can do more research if we should prioritize fixing this. Otherwise, it will be time wasting.

**Comment by johncschuster** [comment] 2024-03-25 20:43
@jasperhuangg bump!

**Comment by jasperhuangg** [comment] 2024-03-26 23:41
Yeah I agree, we can go ahead and close this out, it's super minor and honestly shouldn't be prioritized

**Closed by jasperhuangg** 2024-03-26 23:41 UTC
Labels: Engineering, Daily, Internal, Help Wanted, Bug
