### ISSUE TITLE
[INTERNAL] Web - Public room - When the user click the link under Concierge message, it opens in a different tab

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#21744] opened 2023-06-27 20:08 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Log in with user without a display name
2. Open public room https://staging.new.expensify.com/r/5593084223054221
3. User gets a whisper like this: Hi there! If you just want to lurk in this room, others won't know you're here. However, if you post, others in the room will see your display name as '[dbarrett+snhtest2@quinthar.com](mailto:dbarrett+snhtest2@quinthar.com)'
If you'd like to add a different display name, open the Display Name page here.
4. Click the 'here" link

## Expected Result:
1. Update the message onto a single line:
Hi there! If you just want to lurk in this room, others won't know you're here. However, since you have no display name set, your posts will be shown as coming from '[dbarrett+snhtest2@quinthar.com](mailto:dbarrett+snhtest2@quinthar.com)'. If you'd like something different, please [change your display name](https://staging.new.expensify.com/settings/profile/display-name).
2. Don't open the display name editor in a new tab; just navigate to it.

## Actual Result:
When the user click the link under Concierge message, it opens in a different tab

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [x] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 1.3.33.0
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/93399543/db8db9f0-33a2-4890-a0b1-9597e5bc5541

**Expensify/Expensify Issue URL:**
**Issue reported by:** David Barrett
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1687158046829019

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01a834d9d49621c762</li>
        <li>Upwork Job ID: 1673831761013301248</li>
        <li>Last Price Increase: 2023-06-27</li>
    </ul>
</details>

**Comment by jliexpensify** [comment] 2023-06-27 23:10
Yep, I can repro on v. 32-5:

https://github.com/Expensify/App/assets/30815269/d59fb892-dddc-45b7-916a-ecf4a906d9f3

Agree with the expected outcome that it shouldn't open a new tab - that feels unnecessary.

**Comment by jliexpensify** [comment] 2023-06-27 23:13
btw @sobitneupane - this one is marked as HIGH PRIORITY, if we can get a fix in ASAP, that'd be great!

**Comment by Thanos30** [comment] 2023-06-28 00:03
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
Concierge automated message for users with no display name when entering a public room doesn't appear in one paragraph, and the link opens in a new tab instead of navigating to the path.

### What is the root cause of that problem?

The root cause of the problem seems to lay on the backend, as I didn't manage to pinpoint that message on the code base.

The originalMessage value of that message is this:

```
"Hi there! If you just want to lurk in this room, others won't know you're here. However, if you post, others in the room will see your display name as 'resev11029@extemer.com'.<br /><br />If you'd like to add a different display name, open the Display Name page <a href=\"/settings/profile/display-name\" rel=\"noreferrer noopener\">here</a>."

```
As you can see, there is a double `<br />` element that creates the newlines, and therefore the message is not in one paragraph.

For the link now, the reason it opens in a new link is the `rel=noopener` value.  From the MDN web docs : 
```
when noopener is used, nonempty target names other than _top, _self, and _parent are all treated like _blank in terms of deciding whether to open a new window/tab.
```
The final `<a>` element that holds the link is having a `target="_blank"` prop, that's why the link opens in a new tab.


### What changes do you think we should make in order to solve the problem?

If we want to keep it in one paragraph, we should remove the `<br />` elements. 
As for the link, I think `noopener` is used for unknown links in most cases, which isn't the case here. In any case, stating a `target="_self"` should fix the opening in new tab problem, regardless of the `noopener` rel value.

**Comment by sobitneupane** [comment] 2023-06-28 10:14
I agree with @Thanos30. It is something to be handled in backend. 

I believe the message sent from Concierge are generated in backend.
```json
        "3433734439840177804": {
          "person": [
            {
              "type": "TEXT",
              "style": "strong",
              "text": "concierge@expensify.com"
            }
          ],
          "actorEmail": "concierge@expensify.com",
          "actorAccountID": 8392101,
          "message": [
            {
              "type": "COMMENT",
              "html": "Hi there! If you just want to lurk in this room, others won't know you're here. However, if you post, others in the room will see your display name as 'dev.sobitneupane+1@gmail.com'.<br /><br />If you'd like to add a different display name, open the Display Name page <a href=\"/settings/profile/display-name\" rel=\"noreferrer noopener\">here</a>.",
              "text": "Hi there! If you just want to lurk in this room, others won't know you're here. However, if you post, others in the room will see your display name as 'dev.sobitneupane+1@gmail.com'.\n\nIf you'd like to add a different display name, open the Display Name page here.",
              "isEdited": false,
              "whisperedTo": [
                14713055
              ],
              "isDeletedParentAction": false,
              "reactions": []
            }
          ],
          "originalMessage": {
            "html": "Hi there! If you just want to lurk in this room, others won't know you're here. However, if you post, others in the room will see your display name as 'dev.sobitneupane+1@gmail.com'.<br /><br />If you'd like to add a different display name, open the Display Name page <a href=\"/settings/profile/display-name\" rel=\"noreferrer noopener\">here</a>.",
            "lastModified": "2023-06-28 09:43:42.626",
            "whisperedTo": [
              14713055
            ]
          },
          "avatar": "https://d2k5nsl2zxldvw.cloudfront.net/images/icons/concierge_2021.png",
          "created": "2023-06-28 09:43:42.626",
          "timestamp": 1687945422,
          "reportActionTimestamp": 1687945422626,
          "automatic": false,
          "actionName": "ADDCOMMENT",
          "shouldShow": true,
          "reportActionID": "3433734439840177804",
          "lastModified": "2023-06-28 09:43:42.626",
          "whisperedTo": [
            "dev.sobitneupane+1@gmail.com"
          ],
          "whisperedToAccountIDs": [
            14713055
          ]
        },
```
cc: @jliexpensify

**Comment by lazar-stamenkovic** [comment] 2023-06-28 19:59
**Please re-state the problem that we are trying to solve in this issue.**
Concierge automated message for users with no display name when entering a public room doesn't appear in one paragraph, and the link opens in a new tab instead of navigating to the path.

**What is the root cause of that problem?**
The root cause of the problem seems to lay on the backend, as I didn't manage to pinpoint that message on the code base.

The originalMessage value of that message is this:

"Hi there! If you just want to lurk in this room, others won't know you're here. However, if you post, others in the room will see your display name as 'resev11029@extemer.com'.<br /><br />If you'd like to add a different display name, open the Display Name page <a href=\"/settings/profile/display-name\" rel=\"noreferrer noopener\">here</a>."

As you can see, there is a double <br /> element that creates the newlines, and therefore the message is not in one paragraph.

For the link now, the reason it opens in a new link is the rel=noopener value. From the MDN web docs :

when noopener is used, nonempty target names other than _top, _self, and _parent are all treated like _blank in terms of deciding whether to open a new window/tab.
The final <a> element that holds the link is having a target="_blank" prop, that's why the link opens in a new tab.

**What changes do you think we should make in order to solve the problem?**

**Comment by jliexpensify** [comment] 2023-06-29 00:57
Hi @robertjchen - @sobitneupane has identified this should be an [Internal fix](https://github.com/Expensify/App/issues/21744#issuecomment-1611141501). Are you able to review and confirm? 

If so, I'll remove the Upworks job.

**Comment by Thanos30** [comment] 2023-06-29 01:04
Since this was labeled with `Help Wanted`, is there any chance for a compensation for the help provided by my proposal? @jliexpensify @sobitneupane ?

Thank you in advance

**Comment by lazar-stamenkovic** [comment] 2023-06-29 01:33
this issue is caused in 96 line in AnchorRenderer.js
![Screenshot 2023-06-28 at 20 29 28 1](https://github.com/Expensify/App/assets/114150992/076aeecd-b1b8-4261-ac59-bbbe0e7d7dfa)

we can simply fix this bug to remove default value `_blank` for target attribute.  But it will refresh the page when clicking the link.

To fix this perfectly, we need to add a function to route into the page if the anchor tag has internal link for href attribute.

can I have the chance to fix this issue?

**Comment by lazar-stamenkovic** [comment] 2023-06-29 01:49
I will create a PR for this bug today

**Comment by lazar-stamenkovic** [comment] 2023-06-29 02:46
checked the code base in detail. the project already had the function that i mentioned above comments in `AnchorRenderer` function. 
But it didn't check the case that the href value doesn't have `http` or `https` string when checking internalExpensifyPath.
I already fixed this bug on my end and it's perfectly working.
Please review.

Here is my fix.
![image](https://github.com/Expensify/App/assets/114150992/974cbb4d-51c1-41e2-a774-b6d8d91d57f5)

**Comment by lazar-stamenkovic** [comment] 2023-06-29 14:58
i already fixed it.  will create a PR if you agree.
https://github.com/Expensify/App/assets/114150992/73950966-d752-487c-ae4c-e4e0114b4fcc

**Comment by robertjchen** [comment] 2023-06-29 16:24
> Hi @robertjchen - @sobitneupane has identified this should be an https://github.com/Expensify/App/issues/21744#issuecomment-1611141501. Are you able to review and confirm?

Agreed, it should be an internal fix. However, let me first verify the issue on the backend and see why we have these tags in place, perhaps they're important and used elsewhere (e.g. in the corresponding email notification) 🤔

**Comment by jliexpensify** [comment] 2023-07-01 07:52
@Thanos30 - unfortunately if an Internal fix occurs, generally the only compensation we pay is to the bug reported (and C+ if they reviewed the PR).

@lazar-stamenkovic - we have deemed this Internal, so no PR is needed from you. If we are using your solution, you will be assigned the GH issue. Thanks!

**Comment by Thanos30** [comment] 2023-07-03 00:02
> @Thanos30 - unfortunately if an Internal fix occurs, generally the only compensation we pay is to the bug reported (and C+ if they reviewed the PR).

I understand. I contributed on an issue a while ago, where the issue turned out to be handled internally. I was told I would be compensated a certain amount for helping with the issue and pointing to the right direction, that's why I asked. Totally fair though!

**Comment by jliexpensify** [comment] 2023-07-03 00:30
Hmm, I have heard of cases like that but the reality is, I'm not an engineer - I just do payouts and initial bug reproduction. If you feel strongly that you should be compensated, maybe @sobitneupane and @robertjchen can weigh in?

**Comment by Thanos30** [comment] 2023-07-03 00:34
No @jliexpensify , it's okay, thanks for your interest. I was just wondering if this is like a policy when working on external issues that turn to internal. I do not want to disturb if this is not the way things work.

Thanks again 🙏

**Comment by robertjchen** [comment] 2023-07-06 11:11
>  I was just wondering if this is like a policy when working on external issues that turn to internal.

Great question! My understanding is that in these cases it's up to the discretion of the assigned internal engineer.

In this case, both @Thanos30 and @sobitneupane have been really helpful in analyzing the issue, testing, and pointing out what needs to be changed, so I recommend a payout of $250 each upon resolution of this issue. cc: @jliexpensify

**Comment by Thanos30** [comment] 2023-07-06 11:15
Much appreciated @robertjchen , thank you! 🙏

**Comment by lazar-stamenkovic** [comment] 2023-07-06 13:27
@robertjchen @jliexpensify this issue isn't occurred by `rel=noopener`.  as i mentioned,  this issue is occurred because target = 'blank' attribute is added into anchor tag after checking  `hasExpensifyOrigin` and `internalExpensifyPath` variable in 27 and 28 line within AnchorRenderer.js.
https://github.com/Expensify/App/blob/6f5b149437f941c23ae9b1fc84d34aa7ff6869fd/src/components/HTMLEngineProvider/HTMLRenderers/AnchorRenderer.js#L28C11-L28C29

actually i already fixed this issue by updates of AnchorRenderer.js on my end. I attached the video for it.

I understand that this can be internal issue. because it's a good way to fix this on the backend, too.
But I am not sure how this issue is occurred by `rel=noopener`.  please advise.

cc: @Thanos30 @sobitneupane

**Comment by Thanos30** [comment] 2023-07-06 13:44
@lazar-stamenkovic You are kinda right, `rel=noopener` isn't directly affecting this, but without a specified `target` it will be handled as `_blank`, but so does the code you found for links with not specified target.

I do think your solution is a good catch , but I believe that instead of making multiple checks for every link, it's better to handle special links like this one immediately from the backend, since if a link has a `target` specified, it won't be made into `_blank` and open in a new tab.  We are talking about an automated message that will appear many many times, so a backend change seems much better to me. The `rel=noopener` should be kept, as it helps with security, we just need to specify the `target`. The paragraphs syntax can also only be addressed from the backend.

Therefore, I believe it's better to send this link with a target being `_parent` from the backend.

**Comment by lazar-stamenkovic** [comment] 2023-07-06 13:54
@robertjchen @jliexpensify Again, To resolve this issue on the backend,  think it has to get host of the current testing site and then add it into href attributes of anchor tag.

I believe it remains a viable approach to resolve the issue on the frontend, especially if host of the current testing site in the backend only needs for this issue on localhost or dev site.   please let me know if you decide using my solution. thanks.

**Comment by jliexpensify** [comment] 2023-07-09 23:34
Hi @lazar-stamenkovic - I'm going to defer to @robertjchen and @sobitneupane here for their thoughts on your comments! I'm not an engineer myself, so I can't judge what's the best approach here.

**Comment by jliexpensify** [comment] 2023-07-12 06:43
Hi @robertjchen and @sobitneupane - before I send out $250 payments, can you check out this [comment](https://github.com/Expensify/App/issues/21744#issuecomment-1623683763)? Thanks!

**Comment by jliexpensify** [comment] 2023-07-14 07:05
@Thanos30 can you add your name in Upworks to your Gh profile? @sobitneupane I assume you'll ask Anu to pay you via the C+ payments scheme?

@lazar-stamenkovic I have asked Robert to review your comments, and he should respond shortly.

**Comment by Thanos30** [comment] 2023-07-14 12:07
@jliexpensify I added the info on my profile, also, this is my Upwork profile link in case you prefer it https://www.upwork.com/freelancers/~01db0383e77efb1881

Thank you 🙏

**Comment by jliexpensify** [comment] 2023-07-17 00:53
Invited @Thanos30 - cheers! Bumping @robertjchen to address @lazar-stamenkovic 's comment please :)

**Comment by Thanos30** [comment] 2023-07-17 01:09
Thank you @jliexpensify , much appreciated 🙏

**Comment by robertjchen** [comment] 2023-07-18 06:45
Still testing things out locally, please standby.

**Comment by lazar-stamenkovic** [comment] 2023-07-18 20:16
@robertjchen please review my proposal. i confirmed it correctly addresses the bug for this ticket.
https://github.com/Expensify/App/issues/21744#issuecomment-1612359530

**Comment by robertjchen** [comment] 2023-07-20 15:06
@lazar-stamenkovic I have reviewed your proposal and have determined that this is ultimately a backend fix.

I've also considered your reasoning here https://github.com/Expensify/App/issues/21744#issuecomment-1623723744 but have ultimately decided that the issues specifically for this bug report (such as the newline formatting) are more appropriately handled in the backend.

I appreciate your proposal- if there's another bug/issue where your proposal can also apply, then we can re-consider it there.

**Comment by jliexpensify** [comment] 2023-07-21 03:47
Upworks job closed, @sobitneupane please request payment via New.Dot. @robertjchen please feel free to close this job once the Internal fix is complete.

**Comment by robertjchen** [comment] 2023-07-24 11:59
BE fix under review

**Comment by sobitneupane** [comment] 2023-07-24 16:43
> https://github.com/Expensify/App/issues/21744#issuecomment-1623486084

Payment Requested on newDot.

**Comment by jliexpensify** [comment] 2023-07-25 23:45
Not overdue

**Comment by robertjchen** [comment] 2023-07-26 11:24
BE fix awaiting review and deployment (two parts to it).

**Comment by JmillsExpensify** [comment] 2023-07-27 23:55
@jliexpensify Can you please summarize the appropriate individual payments for all parties involved in this issue? This is holding up @sobitneupane's NewDot payments. More information on this compliance process [in Slack](https://expensify.slack.com/archives/C01SKUP7QR0/p1690321157273869).

**Comment by jliexpensify** [comment] 2023-07-28 00:46
Payment summary:

- Contributor: @Thanos30 $250 (special payment approved by @robertjchen )
- C+: @sobitneupane  $250 (special payment approved by @robertjchen )

Upworks job [here](https://www.upwork.com/jobs/~01a834d9d49621c762)

**Comment by JmillsExpensify** [comment] 2023-07-29 15:39
Reviewed details for @sobitneupane. These details are accurate based on summary from Business Reviewer and are now approved for payment in NewDot.

**Comment by jliexpensify** [comment] 2023-08-07 06:59
This is Internal, everyone has been paid.

**Comment by robertjchen** [comment] 2023-08-10 15:06
Final piece went out two weeks ago: https://github.com/Expensify/Auth/pull/8240 👍

**Closed by robertjchen** 2023-08-10 15:06 UTC
Labels: Reviewing, Engineering, Daily, Internal, Bug
