### ISSUE TITLE
[$500] IOU - After merging concurrently sent IOU, a broken IOU appears with TBD

### ISSUE THREAD

**Issue by izarutskaya** [Expensify/App#33704] opened 2023-12-28 11:47 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.18-1
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** Applause-Internal Team
**Slack conversation:** @

## Action Performed:
1. Open New Expensify app
2. Log in to any A account
3. On the Web, open https://staging.new.expensify.com/
and log in under account B
4. From each user, send one manual IOU between users (A->B and A<-B) at the same time.

## Expected Result:
No additional broken IOU should appear after combining parallel sent IOU

## Actual Result:
After merging concurrently sent IOU, a broken IOU appears with TBD

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [x] Android: mWeb Chrome
- [x] iOS: Native
- [x] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

https://github.com/Expensify/App/assets/115492554/daeeb584-c9b4-49af-b5fd-3dbfbd7844c9

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~0133f0bcd0bded97df</li>
        <li>Upwork Job ID: 1740338764912402432</li>
        <li>Last Price Increase: 2024-01-04</li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @youssef-lr</details>

**Comment by mollfpr** [comment] 2024-01-02 14:13
No proposal

**Comment by brunovjk** [comment] 2024-01-03 20:48
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
Upon submitting two IOUs using two accounts, A and B, simultaneously, a broken IOU appears with TBD.

### What is the root cause of that problem?
The issue is traced back to backend processing.

- When we trigger a `requestMoney/getMoneyRequestInformation`, the system checks for an existing IOU report.
If found, use it, otherwise, it builds a new optimistic one. 
https://github.com/Expensify/App/blob/6dcbd1e52aad67749165de6f779f4b566a8b8fba/src/libs/actions/IOU.js#L643-L644

- If account A submits a request and account B waits for a response before making another request, there's no issue. The request from account B won't be marked as `isNewIOUReport` and will use the previous reportID from account A's request to link both requests.
![success_reportID_created](https://github.com/Expensify/App/assets/95647348/c143424d-cd27-4521-8a7c-c3373bbc85c5)

- However, if account B doesn't wait and submits the request at the same time as account A, both will have `isNewIOUReport`, creating a new report ID for each.
![two_reportID_created](https://github.com/Expensify/App/assets/95647348/9d3b752a-385c-4ef7-8c70-3335df6210fb)

- The backend processes account A's request normally, 
![acc_A_request_response](https://github.com/Expensify/App/assets/95647348/e4c2281d-7c73-4cf9-b35e-fea476bb5605)

- But when it comes to account B's request, I believe the backend checks `isNewIOUReport` again. Although it's not new anymore, the backend response links the new 'account B request' to the earlier created 'account A request'. However, there's an unusual aspect: the first newly created 'account B request' reportID is also in the backend response but with a null value, leading to the TBD render.
![acc_B_request_response](https://github.com/Expensify/App/assets/95647348/fb2fd3c3-e8dc-416a-adab-13923562e5cc)

### What changes do you think we should make in order to solve the problem?
As a frontend developer without access to the backend code, investigating and fixing the specific backend issue is challenging. However, a potential solution to mitigate the problem could be implementing a client-side check.

### What alternative solutions did you explore? (Optional)

**Comment by sonialiap** [comment] 2024-01-04 17:29
@mollfpr what do you think of the above proposal?

**Comment by mollfpr** [comment] 2024-01-08 15:42
@sonialiap Sorry for the delay. I think this issue is related to the backend, and it's better to handle it internally.

**Comment by youssef-lr** [comment] 2024-01-08 21:05
I'm working on a backend fix.

**Comment by youssef-lr** [comment] 2024-01-11 19:51
The backend solution for this is really simple, just a matter of deleting the stale report preview action, but for some reason sending the Onyx update deleting does not work. I'm still investigating.

**Comment by youssef-lr** [comment] 2024-01-17 07:03
I haven't figured out yet, reaching out for help today on Slack to figure out why the Onyx update doesn't get applied.

**Comment by youssef-lr** [comment] 2024-01-22 07:55
Posted [here](https://expensify.slack.com/archives/C03TQ48KC/p1705910118373169) for help

**Comment by youssef-lr** [comment] 2024-01-23 07:25
PR is now ready for review

**Comment by youssef-lr** [comment] 2024-01-29 15:52
We're good here.

**Closed by youssef-lr** 2024-01-29 15:52 UTC
Labels: Engineering, Daily, Internal, Overdue, Bug
