### ISSUE TITLE
[$500] Android – Settings - App flickering when enter an authenticator code in 2FA creation page

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#34140] opened 2024-01-09 14:01 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.23-0
**Reproducible in staging?:** y
**Reproducible in production?:** n
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** Applause - Internal Team
**Slack conversation:**

## Action Performed:
1. Go to https://staging.new.expensify.com/
2. Log in
3. Tap on Settings/ Security/ Two-factor authentication
4. Tap on Copy and Next
5. Then enter any six digits in a code field.

## Expected Result:
App is not flickering when enter an authenticator code in 2FA creation page

## Actual Result:
App flickering when enter an authenticator code in 2FA creation page

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [ ] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

https://github.com/Expensify/App/assets/93399543/79e9a3e5-08a6-4ec9-9a1d-8a4022ec4a70

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~0178f42913610b69a7</li>
        <li>Upwork Job ID: 1767217663958515712</li>
        <li>Last Price Increase: 2024-03-11</li>
    </ul>
</details>

**Comment by situchan** [comment] 2024-01-09 15:38
I am not able to reproduce on main. Tested on both android phone and emulator

**Comment by amyevans** [comment] 2024-01-15 17:46
Verified it's no longer reproducible:

https://github.com/Expensify/App/assets/7277067/38e4eb96-ba68-4f89-bc1f-bfb5b553d66c

Closing this out!

**Comment by lanitochka17** [comment] 2024-03-06 23:48
Issue is still reproducible on the latest build 1.4.48-0
Repro on Pixel (stg and prod), not repro on Samsung


https://github.com/Expensify/App/assets/78819774/16ffdd45-1bcf-4b2f-a1eb-90b7adaa687e

**Comment by amyevans** [comment] 2024-03-08 15:58
Hmm I just retested on a Pixel 3a and am still unable to repro. I'll assign BZ to attempt to repro/take triage from here.

**Comment by sonialiap** [comment] 2024-03-11 12:03
@amyevans I do not see any flickering. Here is my test (pixel 3):

https://github.com/Expensify/App/assets/17131195/ceaa64a1-11db-4c14-adec-ba905e413a5c

**Comment by sonialiap** [comment] 2024-03-11 12:33
@lanitochka17 @kbecciv I cannot reproduce the flickering but I noticed that in both videos where it is reproducible, there's an auto-fill suggestion which neither Amy nor I have. I'm not sure how to reproduce this. Do you guys know where that suggestion is coming from? Katya I see yours says autofill but I can't quite see from where, maybe "з почты"? Sveta, your video shows "from messages". So both of your apps are trying to auto-fill from SMS messages? Did you recently receive a code by SMS that might be affecting the test? 

I tried logging into an app that sends me a SMS code and didn't read it. Then tried the test and I did not get the "auto fill from messages". Not sure how to repo the behavior you're seeing.

<img width="329" alt="image" src="https://github.com/Expensify/App/assets/17131195/862aeda0-d8fd-4ffc-b431-66c5689b46ff">

<img width="331" alt="image" src="https://github.com/Expensify/App/assets/17131195/15b782b1-63f1-421c-8124-9e1c8cd37462">

My test, no auto-fill suggstion

<img width="377" alt="image" src="https://github.com/Expensify/App/assets/17131195/af5d2017-0d9c-43cc-b45d-93272c6f8eb2">

**Comment by amyevans** [comment] 2024-03-11 14:49
Asked in #qa: https://expensify.slack.com/archives/C9YU7BX5M/p1710168520121459

**Comment by amyevans** [comment] 2024-03-11 15:54
I guess we can go external with it and see if we get any traction, but if not I could also see us closing after a week or two.

**Comment by amyevans** [comment] 2024-03-13 21:16
Awaiting proposals

**Comment by amyevans** [comment] 2024-03-18 14:45
Alright it's been a week and we don't have any proposals, it's also not assigned to a wave or VIP so not a priority. I'm going to close, but feel free to reopen if you disagree @sonialiap!

**Closed by amyevans** 2024-03-18 14:45 UTC
Labels: External, Engineering, Daily, Help Wanted, Overdue, Bug
