### ISSUE TITLE
[HOLD #22699] Workspace custom room members list is not updated dynamically

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#20761] opened 2023-06-14 17:18 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Open the app
2. Click on plus
3. Click on new room
4. Write any name, select any workspace and select any visibility
5. Click on Create room
6. Open settings
7. Open Workspaces
8. Open workspace used in step 4
9. Click on members
10. Invite any member
11. Close the menu after invite and click on room name
12. Click on Members and observe that member invited in step 10 is not displayed in room
13. Reload the page and observe that now member is displayed

## Expected Result:
App should dynamically update room member list if new member is added

## Actual Result:
App does not dynamically update room member list and needs reload to display updated list

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android / native
- [x] Android / Chrome
- [x] iOS / native
- [x] iOS / Safari
- [x] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 1.3.27.4

**Reproducible in staging?:** yes

**Reproducible in production?:** yes

**If this was caught during regression testing, add the test name, ID and link from TestRail:**

**Email or phone of affected tester (no customers):**

**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/93399543/b7b07bfb-d28d-4b02-b94d-de8a2efdebd2

**Expensify/Expensify Issue URL:**

**Issue reported by:** @dhanashree-sawant

**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1686211623219509

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01502d61faff3465e2</li>
        <li>Upwork Job ID: 1669451236729647104</li>
        <li>Last Price Increase: 2023-07-07</li>
    </ul>
</details>

**Comment by namhihi237** [comment] 2023-06-14 17:20
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
App should dynamically update room member list if new member is added
### What is the root cause of that problem?
The problem here is that after inviting new members to workspaces, the app has not updated optimisticData member for the rooms of workspaces `addMembersToWorkspace` so we have to reopen the room to have new data.
### What changes do you think we should make in order to solve the problem?
We will find the rooms of workspaces that have chatTypes of “#policyRoom" and “#policyAnnounce" and will update `participants ` for them with optimisticData:

First we need to create get policyRoom and policyAnnounce function in [here](https://github.com/Expensify/App/blob/main/src/libs/ReportUtils.js):
```
function  getAllPolicyRoomsAndAnnounce(policyID) {
 return  _.filter(allReports, (report) =>  report  &&  report.policyID  ===  policyID  && [CONST.REPORT.CHAT_TYPE.POLICY_ROOM, CONST.REPORT.CHAT_TYPE.POLICY_ANNOUNCE].includes(report.chatType));
}
```
Then we need to add a function to build onyxOptimisticData for the room:
```
function addMembersToRoom(rooms, memberLogins) {
	const roomMembersChats = {
		onyxOptimisticData: [],
		onyxFailureData: [],
	};
	  
	_.each(rooms, (room) => {
		roomMembersChats.onyxOptimisticData.push({
			onyxMethod: Onyx.METHOD.MERGE,
			key: `${ONYXKEYS.COLLECTION.REPORT}${room.reportID}`,
			value: {
				participants: [...room.participants, ...memberLogins]
			}
		})
		roomMembersChats.onyxFailureData.push({
			onyxMethod: Onyx.METHOD.MERGE,
			key: `${ONYXKEYS.COLLECTION.REPORT}${room.reportID}`,
			value: {
				participants: room.participants
			}
		})
	});

	return roomMembersChats;
}
```
Update `onyxOptimisticData` in `addMembersToWorkspace`
```
const policyReport = ReportUtils.getAllPolicyRoomsAndAnnounce(policyID);
const membersToRoom = addMembersToRoom(policyReport, memberLogins);

const optimisticData = [
	{
		onyxMethod: Onyx.METHOD.MERGE,
		key: membersListKey,
		// Convert to object with each key containing {pendingAction: ‘add’}
		value: _.object(logins, Array(logins.length).fill({ pendingAction: CONST.RED_BRICK_ROAD_PENDING_ACTION.ADD })),
	},
	...membersChats.onyxOptimisticData,
	...membersToRoom.onyxOptimisticData 
];
```

### What alternative solutions did you explore? (Optional)
N/A

**Comment by mallenexpensify** [comment] 2023-06-19 23:07
@aimane-chnaif , please review the above proposals.  Thx

**Comment by abekkala** [comment] 2023-06-20 14:17
@mallenexpensify @aimane-chnaif curious if the fix for this issue would also resolve https://github.com/Expensify/App/issues/21059 that was just reported?

**Comment by mallenexpensify** [comment] 2023-06-21 22:42
Unsure @abekkala but, since we have two proposals here already, it might be good to put that one on hold. 
@aimane-chnaif please review the proposals above, thx

**Comment by mallenexpensify** [comment] 2023-06-24 00:08
Good question @aimane-chnaif , did you copy/paste the above from somewhere? I'm asking internally about expected behavior, it seems like something we should have documented _somewhere_.

**Comment by mallenexpensify** [comment] 2023-06-26 20:47
I'm checking internally [here](https://stackoverflowteams.com/c/expensify/questions/16858) 

I think room functionality is still in beta, or nor launched.  I tried to test creating rooms on workspaces with multiple accounts and nothing seemed to _work_, the rooms don't show other people in the workspace. 
<img width="771" alt="image" src="https://github.com/Expensify/App/assets/22508304/089a00ff-eb06-458f-ba59-ae6fffa9408e">

I think we might want to put this on hold or I/we need to dig more

**Comment by mallenexpensify** [comment] 2023-06-30 03:51
Was able to reproduce. We have quite a few "not updating dynamically" bugs but they don't seem to be related so treating this one independently, bumped price to $2000 to get more 👀

**Comment by mallenexpensify** [comment] 2023-07-05 23:31
Sorry for the delay @dukenv0307 , it's been 👻 in the Slack post and also in StackOverflow.  I followed up again and shared with the room to get more 👀 
https://expensify.slack.com/archives/C01GTK53T8Q/p1688599842980999?thread_ts=1687019472.887419&cid=C01GTK53T8Q

**Comment by mallenexpensify** [comment] 2023-07-11 04:46
I got the answer we needed
> Public: Anyone with the room URL can access the room
Restricted: Can be discovered and commented in by users that are members of the Workspace the room is tied to.
Private: Can only be discovered and commented in by users that are explicitly invited to the room.

But... we're not planning to treat 'dynamically updating' issues as bugs, [per this discussion](https://expensify.slack.com/archives/C01GTK53T8Q/p1689009972403289?thread_ts=1688646398.596839&cid=C01GTK53T8Q),  

Checking on next steps [here](https://expensify.slack.com/archives/C01GTK53T8Q/p1689050735417059?thread_ts=1687471385.852519&cid=C01GTK53T8Q)

**Comment by mallenexpensify** [comment] 2023-07-11 21:33
Removing you @shawnborton since this is on hold. 
Checking here about the single device/platform
https://expensify.slack.com/archives/C01GTK53T8Q/p1689111199121799?thread_ts=1688646398.596839&cid=C01GTK53T8Q

**Comment by mallenexpensify** [comment] 2023-07-11 22:06
Closing based on this
> https://expensify.slack.com/archives/C01GTK53T8Q/p1689112054991499?thread_ts=1688646398.596839&cid=C01GTK53T8Q 

> On that one, I think we can close it actually. The workspace rooms will be discoverable by everyone, but the workspace members wont be members of all the rooms when added to the workspace, they can join them but admin adding them to the workspace wont add them to all the rooms I think thats the latest on what we want to do so you can probably close that isse

**Closed by mallenexpensify** 2023-07-11 22:06 UTC
Labels: External, Engineering, Weekly, NewFeature
