### ISSUE TITLE
[Pay 4/29][$250] Remove NewDistanceRequestPage.js and copy any changes since Nov 27 into IOURequestStepDistance.js

### ISSUE THREAD

**Issue by tgolen** [Expensify/App#34610] opened 2024-01-16 20:51 UTC
Held on https://github.com/Expensify/App/issues/34613

This is a part of https://github.com/Expensify/App/issues/29107. You can look at that issue for more context behind the cleanup process.

# Problem
The app has two redundant components:

**Old Component**: `NewDistanceRequestPage`
**New Component** `IOURequestStepDistance`

# Solution
Following the examples ([example 1](https://github.com/Expensify/App/pull/33646), [example 2](https://github.com/Expensify/App/pull/32764)), the Old Component needs to be completely removed from the codebase

1. Look at the history of the Old Component
1. If there are any changes since Nov 27, 2023 which have not been added to the New Component, copy those changes
1. Replace all uses of the Old Component with the New Component
2. Remove all traces of Old Component
3. Be sure to update all routes and navigation to use the new `:action` param (instead of being hard-coded with `"create"`)
4. Update any logic like `isEditing` to use the new action param from the route
<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01f10eeacf3fc8d218</li>
        <li>Upwork Job ID: 1747632624829898752</li>
        <li>Last Price Increase: 2024-01-17</li>
<li>Automatic offers: </li>
<ul>
<li>cubuspl42 | Reviewer | 28115391</li>
<li>DylanDylann | Contributor | 28115392</li>
</ul></li>
    </ul>
</details>

**Comment by KrAbhas** [comment] 2024-01-16 21:55
## Proposal

### Please re-state the problem that we are trying to solve in this issue.

Remove NewDistanceRequestPage.js and copy any changes since Nov 27 into IOURequestStepCategory.js

### What is the root cause of that problem?

Clean Up  of NewDistanceRequestPage

### What changes do you think we should make in order

We will be deleting the component here:

**Comment by njmulsqb** [comment] 2024-01-17 01:39
I would love to take this!

**Comment by DylanDylann** [comment] 2024-01-17 03:29
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
Remove NewDistanceRequestPage.js and copy any changes since Nov 27 into IOURequestStepDistance.js 

### What is the root cause of that problem?
Remove deprecated component 

### What changes do you think we should make in order to solve the problem?
1. Currently, we only use NewDistanceRequestPage in the MoneyRequestSelectorPage but MoneyRequestSelectorPage also be removed in [this issue](https://github.com/Expensify/App/issues/34613). So that we can remove NewDistanceRequestPage component and all traces 
https://github.com/Expensify/App/blob/278d04e0689d6f012354d89ec19c640a1cd9dc54/src/libs/Navigation/AppNavigator/ModalStackNavigators.tsx#L107

https://github.com/Expensify/App/blob/278d04e0689d6f012354d89ec19c640a1cd9dc54/src/libs/Navigation/linkingConfig.ts#L437

2. For new component IOURequestStepDistance. 

In here
https://github.com/Expensify/App/blob/a2f5bd5898eafc53801807c37929afaae8a23666/src/ROUTES.ts#L347-L351
We need to use the new :action param (instead of being hard-coded with "create") like we did here

https://github.com/Expensify/App/blob/a2f5bd5898eafc53801807c37929afaae8a23666/src/ROUTES.ts#L362-L366

3. We also copy changes since 27 Nov to new components based on list commit here: https://github.com/Expensify/App/commits/main/src/pages/iou/NewDistanceRequestPage.js
We only need to migrate 1 PR
### What alternative solutions did you explore? (Optional)

**Comment by MahmudjonToraqulov** [comment] 2024-01-17 14:57
I would love to take this!

**Comment by cubuspl42** [comment] 2024-01-18 09:23
I approve the proposal by @DylanDylann 

- As this is not TypeScript migration, we should still do proposals as per the guidelines
- The proposals shows some research related to the refactoring

C+ reviewed 🎀 👀 🎀

**Comment by cristipaval** [comment] 2024-01-22 14:47
Thanks @cubuspl42!

**Comment by DylanDylann** [comment] 2024-01-23 07:28
@cubuspl42 @cristipaval I want to confirm the expectation again. In this issue, we need to remove both `NewDistanceRequestPage` and `EditRequestDistancePage` and using `IOURequestStepDistance` instead. More context [here](https://github.com/Expensify/App/issues/34609#issuecomment-1902682279)

**Comment by cubuspl42** [comment] 2024-01-23 08:34
@DylanDylann 

- We definitely need to remove `NewDistanceRequestPage`
- We need to update the `IOURequestStepDistance` with changes and fixes that were applied to `NewDistanceRequestPage` (all that apply)
- As I understand it, we should replace all references to the Old Components with the appropriate references to the New Component (`IOURequestStepDistance`).

This is clear from our issue description. 

So the actual question is whether `EditRequestDistancePage` belongs to the Old Component set, right?

**Comment by DylanDylann** [comment] 2024-01-23 08:35
@cubuspl42 Yes, my question that do we need to remove `EditRequestDistancePage` and also use `IOURequestStepDistance`   for both create and edit flow

**Comment by DylanDylann** [comment] 2024-01-23 08:56
Posted on Slack to clear: https://expensify.slack.com/archives/C01GTK53T8Q/p1705999852089949

**Comment by DylanDylann** [comment] 2024-01-25 07:14
The final expectation is confirmed. I am working on PR

**Comment by cubuspl42** [comment] 2024-01-25 09:39
I'm glad to see you figured out the expected behavior! I'll review the PR when it's ready 👍

**Comment by DylanDylann** [comment] 2024-01-29 15:50
@cubuspl42 @cristipaval As discussion [here](https://expensify.slack.com/archives/C01GTK53T8Q/p1705999852089949), we decided to use `IOURequestStepDistance` instead of `EditRequestDistancePage` and `NewDistanceRequestPage`. But currently, in the edit flow
https://github.com/Expensify/App/blob/c9877d187084b34b038b0c939884865076019a93/src/pages/iou/request/IOURequestStartPage.js#L171-L173

Edit Distance Page is a child in `IOURequestStartPage`  and the route of `IOURequestStartPage` and `IOURequestStepDistance` is different. So that we need to hold this issue until https://github.com/Expensify/App/issues/34613 is done

**Comment by cubuspl42** [comment] 2024-01-30 09:23
Mhm, I get it. Sure, let's hold 👍

Hopefully, there won't be any circular dependencies between these tasks.

**Comment by cristipaval** [comment] 2024-02-22 15:40
Still on hold.

**Comment by cristipaval** [comment] 2024-03-18 11:27
great! Thanks!

**Comment by DylanDylann** [comment] 2024-03-25 15:19
@cubuspl42 I fixed [this issue](https://github.com/Expensify/App/issues/38814) and trying to find the best solution for [this issue](https://github.com/Expensify/App/issues/38864)

**Comment by greg-schroeder** [comment] 2024-03-26 22:43
Hi team - can anyone confirm if the fix will also fix https://github.com/Expensify/App/issues/38853?

**Comment by DylanDylann** [comment] 2024-03-27 07:22
@johncschuster Please remove the hold label

**Comment by cubuspl42** [comment] 2024-03-27 11:24
Just so it's clear, currently we're working on this PR:

- https://github.com/Expensify/App/pull/38987#issuecomment-2022511744

It was extracted from the original one (https://github.com/Expensify/App/pull/38911), which is now closed. 

@greg-schroeder I don't think so, but @DylanDylann can confirm.

**Comment by cubuspl42** [comment] 2024-04-02 07:46
Please don't tell me this is because this part...

```
[...] which intended to fix https://github.com/Expensify/App/issues/34610
```

...triggered the auto-closing regex 😭

**Comment by cubuspl42** [comment] 2024-04-02 08:12
Anyway, we indeed need to re-open this.

We're working on two of the regressions:
- https://github.com/Expensify/App/pull/38987
  - The ball is on my side, I'll try to wrap this up today
- https://github.com/Expensify/App/pull/39144
  - @DylanDylann is working on this

**Comment by cristipaval** [comment] 2024-04-02 09:48
I think it was automatically closed because it was linked in that PR

**Comment by DylanDylann** [comment] 2024-04-02 16:33
@cristipaval Please also help to remove the hold label on the title. Thanks

**Comment by mallenexpensify** [comment] 2024-04-24 00:43
@eVoloshchak reassigning, please take over as C+. If you don't have bandwidth, unassign yourself. Thanks
@DylanDylann can you please post an update on where we're at and what @eVoloshchak needs to help with?

**Comment by DylanDylann** [comment] 2024-04-24 02:06
@mallenexpensify Everything is done, waiting for payement

**Comment by mallenexpensify** [comment] 2024-04-25 23:52
Thanks @DylanDylann , removed `Reviewing`, added `Awaiting Payment` and updated the title to reflect payment date.

**Comment by DylanDylann** [comment] 2024-05-01 15:46
@mallenexpensify Bump for payment

**Comment by mallenexpensify** [comment] 2024-05-03 01:32
Contributor: @DylanDylann paid $250 via Upwork
Contributor+: @cubuspl42 paid $250 via Upwork

Doesn't look like this needs a regression test created, comment if anyone disagrees.

**Closed by mallenexpensify** 2024-05-03 01:32 UTC
Labels: External, Engineering, Daily, Awaiting Payment, Bug
