### ISSUE TITLE
Select Currency - Symbol for XPF is the same as the name of currency

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#53082] opened 2024-11-25 18:36 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 9.0.66-3
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**If this was caught on HybridApp, is this reproducible on New Expensify Standalone?:** Y
**If this was caught during regression testing, add the test name, ID and link from TestRail:** N/A
**Issue reported by:** Applause - Internal Team

## Action Performed:
1. Open https://staging.new.expensify.com/
2. Open any report
3. Tap on plus icon
4. Tap on Pay (user)
5. Tap on the currency name
6. Type "XPF" in the search bar

## Expected Result:
XPF symbol should be CFPF

## Actual Result:
Symbol is not correctly displayed for XPF, it is the same as the name of currency

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Standalone
- [x] Android: HybridApp
- [ ] Android: mWeb Chrome
- [x] iOS: Standalone
- [x] iOS: HybridApp
- [ ] iOS: mWeb Safari
- [ ] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

<details>
  <summary>Add any screenshot/video evidence</summary>

  
</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by FitseTLT** [comment] 2024-11-25 18:40
Should be fixed in BE

**Comment by ChavdaSachin** [comment] 2024-11-25 21:32
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
Wrong symbol for currency - XPF.

### What is the root cause of that problem?
Wrong symbol sent from BE.

### What changes do you think we should make in order to solve the problem?
Option 1. 
Fix the symbol from BE, and then update currency test here....
https://github.com/Expensify/App/blob/e4ac07a17c0939a7c35c231beac171bde0f99f01/tests/unit/currencyList.json#L843-L844

Option 2.
Since the currency list would be mostly static and might need minimal updates - we could move currency list to frontend.
Create a new file with currency list and merge data to onyx upon app initialization, or just read currency data from file itself.

### What alternative solutions did you explore? (Optional)

**Comment by CortneyOfstad** [comment] 2024-12-06 17:09
Still a hot pick

**Comment by CortneyOfstad** [comment] 2024-12-17 19:41
Still a hot pick

**Comment by cristipaval** [comment] 2024-12-17 20:09
I'll look into this

**Comment by CortneyOfstad** [comment] 2024-12-20 20:24
Hey @cristipaval, I will be OOO starting this afternoon (December 20th) and will be returning January 6th. If any action is needed during that time from a BZ perspective, feel free to reapply the BZ label. Otherwise, I'll review when I'm back. Thanks and Happy Holidays!

**Comment by cristipaval** [comment] 2024-12-20 22:27
Thanks @CortneyOfstad!
The fix hit production yesterday. Closing!

**Closed by cristipaval** 2024-12-20 22:27 UTC
Labels: Reviewing, Daily, Internal, Bug
