### ISSUE TITLE
[HOLD for payment 2024-12-20] Search - Submit button is not disabled in Search when "Prevent self-approvals" is enabled

### ISSUE THREAD

**Issue by IuliiaHerets** [Expensify/App#53989] opened 2024-12-12 07:34 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 9.0.75-0
**Reproducible in staging?:** Yes
**Reproducible in production?:** No
**If this was caught on HybridApp, is this reproducible on New Expensify Standalone?:** N/A
**If this was caught during regression testing, add the test name, ID and link from TestRail:** Exp
**Email or phone of affected tester (no customers):** applausetester+kh1311020@applause.expensifail.com
**Issue reported by:** Applause Internal Team
**Device used:** Mac 15.0 / Chrome
**App Component:** Search

## Action Performed:
Precondition:
- Delayed submission is enabled.
- Admin is the approver.
- "Prevent self-approvals" is enabled.

1. Go to staging.new.expensify.com
2. Go to workspace chat.
3. Submit an expense.
4. Note that Submit button is disabled.
5. Go to Search.
6. Click Submit button on the same expense in Step 3.

## Expected Result:
Submit button should also be disabled in Search when "Prevent self-approvals" is enabled.

## Actual Result:
Submit button is not disabled in Search when "Prevent self-approvals" is enabled.
User can still submit expenses in Search.

## Workaround:
Unknown

## Platforms:
- [ ] Android: Standalone
- [ ] Android: HybridApp
- [ ] Android: mWeb Chrome
- [x] iOS: Standalone
- [x] iOS: HybridApp
- [x] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

https://github.com/user-attachments/assets/f8089a6d-ab47-4abd-861f-16800e06a0ff

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Issue Owner</summary>Current Issue Owner: @sakluger</details>

**Comment by IuliiaHerets** [comment] 2024-12-12 07:35
Not repro on production 

https://github.com/user-attachments/assets/3be6cb39-da04-48b8-b145-192a42c78a3e

**Comment by mjasikowski** [comment] 2024-12-12 08:46
Looking into it

**Comment by mjasikowski** [comment] 2024-12-12 13:47
Discussing the expected behavior in https://expensify.slack.com/archives/C01GTK53T8Q/p1734003901809559?thread_ts=1733988869.753469&cid=C01GTK53T8Q

**Comment by mjasikowski** [comment] 2024-12-12 13:49
In the meantime I have a draft PR to replicate the behavior from report previews if we agree to follow that: https://github.com/Expensify/App/pull/54012/files

**Comment by luacmartins** [comment] 2024-12-12 22:45
Fixed in staging

**Comment by sakluger** [comment] 2024-12-24 19:04
Sorry @allgandalf for the delay, I was OOO the past few days due to holiday travel.

Here's the Upwork contract: https://www.upwork.com/nx/wm/offer/105455673. Please let me know once you've accepted the contract and I will complete payment. Thanks!

**Comment by sakluger** [comment] 2024-12-27 22:17
All paid, thanks again!

**Closed by sakluger** 2024-12-27 22:17 UTC
Labels: Engineering, Daily, Overdue, Awaiting Payment, Bug
