### ISSUE TITLE
[HOLD] Navigating Back takes the user to the home screen on the web when app is directly opened via RHN links - reported by @parasharrajat

### ISSUE THREAD

**Issue by mvtglobally** [Expensify/App#10508] opened 2022-08-24 03:26 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
Steps WEB:
  1. Open the app from the RHN URL (https://staging.new.expensify.com/new/chat).
  3. Go Back.
Steps MWeb:
  1. Open the app from the RHN URL (https://staging.new.expensify.com/new/chat).
  3. Press the hardware back button.
  
## Expected Result:
The user should not leave the app.

## Actual Result:
Navigating Back takes the user to the home screen on the web when app is directly opened via RHN links

## Workaround:
unknown 

## Platform:

Where is this issue occurring?

- Web
- Mobile Web

**Version Number:** 1.1.88-0
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**Email or phone of affected tester (no customers):** 
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation
Potentially related to 
https://github.com/Expensify/App/issues/9984
https://github.com/Expensify/App/issues/10507
https://github.com/Expensify/App/issues/10506

https://user-images.githubusercontent.com/43995119/186319703-48b6433b-ac6e-4f31-a3eb-566510f01a94.mp4

https://user-images.githubusercontent.com/43995119/186319725-2a8325d8-b287-45a7-af66-f4f71db81af4.mp4

**Expensify/Expensify Issue URL:** 
**Issue reported by:** @parasharrajat
**Slack conversation:** https://expensify.slack.com/archives/C01GTK53T8Q/p1659433630718529

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by Beamanator** [comment] 2022-08-25 08:16
This looks like almost an exact duplicate of https://github.com/Expensify/App/issues/10507

**Comment by Beamanator** [comment] 2022-08-25 08:17
Ok maybe not "exact" but very very similar, I think we should consolidate

**Comment by sonialiap** [comment] 2022-08-25 18:19
I can reproduce this 👍

**Comment by sonialiap** [comment] 2022-08-25 18:20
However I agree with @Beamanator that these issues would most likely get fixed by the same code change so I am closing this one out in preference of https://github.com/Expensify/App/issues/10507

**Closed by sonialiap** 2022-08-25 18:20 UTC
Labels: Daily
