### ISSUE TITLE
[Advanced Approvals] [$250] Web - LHN - Expense report needs to be opened after changing approver to be seen in LHN

### ISSUE THREAD

**Issue by IuliiaHerets** [Expensify/App#48462] opened 2024-09-03 12:08 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 9.0.28-0
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
Issue was found when executing this PR: https://github.com/Expensify/App/pull/48362
**Issue reported by:** Applause Internal Team

## Action Performed:
Precondition: log into OD as an admin, create a control policy, enable workspace chats, select "Advanced Approvals", invite 3 members (non-admin): 2 approvers and 1 submitter, set the approval flow as submitter submits to approver 1

1. Log into ND as submitter
2. Navigate to the workspace chat
3. Submit an expense
4. Log into ND as approver 1
5. Navigate to the workspace chat and open the submitted report
6. Open any other report in the LHN
7. As admin, change the the submitter's submitsTo to approver 2 in OD
8. Open the tab with approver 1 logged in

## Expected Result:
The approver can still see the expense report in the LHN

## Actual Result:
The expense report disappears after changing the approver, and it is not displayed in the LHN unless it is opened in Search, then it stays in the LHN

## Workaround:
Unknown

## Platforms:

- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

https://github.com/user-attachments/assets/9c4a0623-8454-4a0b-8232-ae12bc857a75

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~021833058783152137453</li>
        <li>Upwork Job ID: 1833058783152137453</li>
        <li>Last Price Increase: 2024-09-09</li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @chiragsalian</details>

**Comment by IuliiaHerets** [comment] 2024-09-03 12:09
@RachCHopkins  FYI I haven't added the External label as I wasn't 100% sure about this issue. Please take a look and add the label if you agree it's a bug and can be handled by external contributors

**Comment by RachCHopkins** [comment] 2024-09-05 23:21
Traditionally, workflow is set at the time of submission. If the workflow is changed after submission, this does not affect any reports already submitted. Users must retract a report and submit again to restart with a new workflow.

Has this been changed for New Expensify?

**Comment by RachCHopkins** [comment] 2024-09-05 23:27
I don't understand the "expected result" here. 

> The approver can still see the expense report in the LHN

Which approver? There are two approvers in the testing workflow.

> The expense report disappears after changing the approver, and it is not displayed in the LHN unless it is opened in Search, then it stays in the LHN

Disappears for whom? Displayed for whom? There are 3 users involved, is this for all of them?

@IuliiaHerets can we get more specific here, please?

**Comment by IuliiaHerets** [comment] 2024-09-06 08:58
@RachCHopkins 
**Expected Result:**
The approver 1 can still see the expense report in the LHN
**Actual Result:**
The expense report disappears from the LHN of approver 1 after admin changes the approver, and it is not displayed in the LHN of approver 1 unless it is opened in Search, then it stays in the LHN approver 1

**Comment by RachCHopkins** [comment] 2024-09-09 04:15
Thanks @IuliiaHerets - I'll check what the expected behaviour is.

**Comment by RachCHopkins** [comment] 2024-09-09 08:23
Expected behaviour is that when the approval workflow is changed for a user, this will not affect Processing expenses/reports. 

So there should be no change for Approver 1 and Approver 2 should not see anything new.

**Comment by nkdengineer** [comment] 2024-09-09 09:16
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
The expense report disappears after changing the approver, and it is not displayed in the LHN unless it is opened in Search, then it stays in the LHN

### What is the root cause of that problem?
After the admin change the `submitTo` of submitter to `approver 2`, the pusher sent the data that clears the parent report and parent report action but `hasParentAccess` of expense report is still `true` then the expense report is hidden in LHN because `shouldOverrideHidden` is `false`. After we open this report again `hasParentAccess` is updated to `false` so it stays in LHN even when we open other reports.

https://github.com/Expensify/App/blob/03ec468bfb14265d8953a8cfad7a0a875991fd8f/src/libs/SidebarUtils.ts#L132-L136

https://github.com/Expensify/App/blob/03ec468bfb14265d8953a8cfad7a0a875991fd8f/src/libs/ReportUtils.ts#L7795

### What changes do you think we should make in order to solve the problem?
We can pass `parentReportAction` to `isExpenseReportManagerWithoutParentAccess` and update this function to return true if `parentReportAction` is empty. Sometimes the parent report data can be empty if we open the expense report but the `OpenReport` API for open report always returns the parent report action of this report if we can access.

```
function isExpenseReportManagerWithoutParentAccess(report: OnyxEntry<Report>, parentReportAction: OnyxEntry<ReportAction>) {
    return isExpenseReport(report) && (report?.hasParentAccess === false || !!parentReportAction) && report?.managerID === currentUserAccountID;
}
```
https://github.com/Expensify/App/blob/03ec468bfb14265d8953a8cfad7a0a875991fd8f/src/libs/ReportUtils.ts#L7795
```
const isExpenseReportManagerWithoutParentAccess = ReportUtils.isExpenseReportManagerWithoutParentAccess(report, parentReportAction);
```
https://github.com/Expensify/App/blob/03ec468bfb14265d8953a8cfad7a0a875991fd8f/src/libs/SidebarUtils.ts#L132-L136

### What alternative solutions did you explore? (Optional)
BE should update `hasParentAccess` of expense report to `false` when sending the pusher data to approver 1

**Comment by trjExpensify** [comment] 2024-09-10 01:26
Sounds like an advanced approvals on control bug to me, moving to #wave-control.

**Comment by akinwale** [comment] 2024-09-12 06:20
@nkdengineer's [proposal](https://github.com/Expensify/App/issues/48462#issuecomment-2337577562) works here if we want to move forward with a frontend fix, otherwise, the backend fix suggested as the alternative solution can be implemented.

🎀👀🎀 C+ reviewed.

**Comment by chiragsalian** [comment] 2024-09-12 19:49
Thank you for the thoughts. I dont think front end is a good clean solution for this. I think the backend alternate solution is better/cleaner solution for this. Marking it internal for now. I'll verify the data and behavior in a few days.

**Comment by RachCHopkins** [comment] 2024-09-18 00:40
@chiragsalian are you taking this one on yourself?

**Comment by chiragsalian** [comment] 2024-09-18 19:22
ah yes, you can take down the job from upwork for now since its internal.

**Comment by chiragsalian** [comment] 2024-09-20 22:53
I investigated this a bit today. I'm actually i bit confused with expected behavior. So in the video for approver1 the chat report containing the expense to approve hides from the LHN when the approver is changed to approver2 (around the 0:55s mark). 

For me this does not happen locally. After submitting an expense to approver1 and switching the approver to approver2, the chat report is still displayed in the LHN along with GBR for approver1. To me this is correct because the expense was submitted to approver1 at first and so they need to approve it. I don't think the GBR action should change to approver2 for all existing submitted/unapproved reports the moment its been updated on oldDot. Correct me if I am mistaken. I'll ask internally as well.

Also in your video it shows my above statement is correct, because when the tester opens the report at the 1:08s mark you'll see it says that approver1 has to approve the report. So it looks like clearing report data for approver1 in the past was the mistake but it doesn't look like its cleared now so i think we're good here. Can someone else confirm while i also ask internally.

I also tested using oldDot and the same stays true i.e., when submitter submits to approver1 and then we change the approver to approver2 in advanced approval, the report remains submitted to approver1 to approve. So I believe things are fine as is.

If we want the approver to change immediately (like approver1 has report and GBR hidden, and approver2 get the report and GBR to take action) that's a bigger feature request. We've to discuss internally if this change is needed and even if it is its outside the scope of this issue imo.

**Comment by RachCHopkins** [comment] 2024-09-25 02:12
@chiragsalian there's conversation [above](https://github.com/Expensify/App/issues/48462#issuecomment-2333578723) on the expected outcome etc. [Here](https://expensify.slack.com/archives/C06ML6X0W9L/p1725855620153459)'s where I raised it in Slack.

**Comment by chiragsalian** [comment] 2024-09-25 22:18
From that slack post it looks like the expected behavior is,
> Approvers shouldn’t change for processing reports.

So with that said i don't think this bug exists anymore since the report is not cleared from the original approver which is good. Can someone else confirm, if that's true we can close out this issue.

**Comment by RachCHopkins** [comment] 2024-09-30 05:52
That's how I read it too @chiragsalian. I'll add the retest label.

**Comment by RachCHopkins** [comment] 2024-09-30 05:54
Not overdue. Awaiting a retest.

**Comment by kavimuru** [comment] 2024-10-01 14:06
Still tester is able to reproduce the issue. This bug was reported from this PR https://github.com/Expensify/App/pull/48362 validation.

https://github.com/user-attachments/assets/5e85e6dd-a10f-49ec-b59f-93433a9f56c4

**Comment by RachCHopkins** [comment] 2024-10-01 20:29
Ok, so going by that, the actual problem is this:

- User 1: create and submit expense
- Approver 1: Sees report for approval in LHN

---- Change User 1 approver ----

- Approver 1: No longer sees report for approval in LHN, and if they are actively in the report, it vanishes.

**Comment by chiragsalian** [comment] 2024-10-04 19:24
The problem you laid out sounds about right Rachael. I'm unable to reproduce it locally or on staging.

**Comment by RachCHopkins** [comment] 2024-10-08 04:26
Ok well it's pretty hard to fix if no one can reproduce it. I think we should close this until it becomes an issue that can be reproduced. Do you agree @chiragsalian?

**Comment by chiragsalian** [comment] 2024-10-08 17:14
Yeah thats fine by me. Closing.

**Closed by chiragsalian** 2024-10-08 17:14 UTC
Labels: Daily, Internal, Overdue, Bug, retest-weekly
