### ISSUE TITLE
[HOLD for payment 2024-03-29] [$500] LHN - Empty space displayed in LHN after opening IOU detail page offline

### ISSUE THREAD

**Issue by izarutskaya** [Expensify/App#38670] opened 2024-03-20 12:59 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** v1.4.55-0
**Reproducible in staging?:** Y
**Reproducible in production?:** N
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Issue reported by:** Applause-Internal team

## Action Performed:
1. Go to https://staging.new.expensify.com/
2. Go offline
3. Click on FAB and create a new group chat
4. In the group chat click on "+" > Spilt bill
5. Create a manual request and split it with one user of the group
6. Navigate to the chat with the user you split the bill
7. Open the money request detail page

## Expected Result:
No space between reports is displayed in LHN

## Actual Result:
Empty space displayed in LHN after opening the IOU detail page

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

https://github.com/Expensify/App/assets/115492554/97b31faa-cd4b-4c9e-a11c-659b52e8ddfc

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~0162cd9a8930d9526d</li>
        <li>Upwork Job ID: 1773726162377322496</li>
        <li>Last Price Increase: 2024-03-29</li>
    </ul>
</details>

**Comment by izarutskaya** [comment] 2024-03-20 13:01
@joekaufmanexpensify I haven't added the External label as I wasn't 100% sure about this issue. Please take a look and add the label if you agree it's a bug and can be handled by external contributors.

**Comment by izarutskaya** [comment] 2024-03-20 13:02
Production 

![Screenshot 2024-03-20 at 14 13 03](https://github.com/Expensify/App/assets/115492554/bc914f5c-9719-4fb6-9312-9d334185523c)

**Comment by joekaufmanexpensify** [comment] 2024-03-20 16:33
@youssef-lr do you think this needs to be a deploy blocker? I am not personally convinced. It's pretty niche behavior.

**Comment by youssef-lr** [comment] 2024-03-20 19:54
Testing on staging & production now

**Comment by youssef-lr** [comment] 2024-03-20 19:58
@aimane-chnaif I don't think this is the same issue, I can only reproduce in staging.

**Comment by youssef-lr** [comment] 2024-03-20 19:58
Going to try to find the offending PR now

**Comment by youssef-lr** [comment] 2024-03-20 20:09
This is a regression from this [PR](https://github.com/Expensify/App/pull/38255), after reverting it locally I can't reproduce anymore. cc @jbroma @allroundexperts @mountiny

**Comment by youssef-lr** [comment] 2024-03-20 20:28
This is also reproducible online, but the empty row disappears quickly

https://github.com/Expensify/App/assets/9680864/1eb13a7e-6872-4ea1-935e-53bfa4c3d9ab

**Comment by youssef-lr** [comment] 2024-03-20 20:37
I found out why this is happening [here](https://github.com/Expensify/App/pull/38255/files#r1532802697), I'm gonna open this up to contributors so we can hopefully find a fix

**Comment by youssef-lr** [comment] 2024-03-20 21:14
Already replied @GandalfGwaihir

**Comment by youssef-lr** [comment] 2024-03-21 00:18
Bumping this in the open source channel https://expensify.slack.com/archives/C01GTK53T8Q/p1710980255736579

**Comment by joekaufmanexpensify** [comment] 2024-03-21 13:31
@youssef-lr if this is a recent regression from a PR that @jbroma and @allroundexperts worked on, shouldn't we just have them fix it? Or revert that other PR so they can work on a fix?

**Comment by youssef-lr** [comment] 2024-03-21 20:23
@joekaufmanexpensify I think it would be great if @jbroma could chime in, but the solution @fedirjh proposed might be good too. I'm testing it now.

**Comment by youssef-lr** [comment] 2024-03-21 22:20
@situchan and I have discussed this in Slack and tested it together, so assigning this to them.

**Comment by situchan** [comment] 2024-03-24 14:28
- [x] The PR that introduced the bug has been identified. Link to the PR: https://github.com/Expensify/App/pull/38255
- [x] The offending PR has been commented on, pointing out the bug it caused and why, so the author and reviewers can learn from the mistake. Link to comment: https://github.com/Expensify/App/pull/38255/files#r1532802697
- [x] A discussion in #expensify-bugs has been started about whether any other steps should be taken (e.g. updating the PR review checklist) in order to catch this type of bug sooner. Link to discussion: N/A This came from big refactor and this kind of bug couldn't be easily caught.
- [x] Determine if we should create a regression test for this bug.
- [x] If we decide to create a [regression test](https://github.com/Expensify/App/blob/main/contributingGuides/REGRESSION_TEST_BEST_PRACTICES.md) for the bug, please propose the regression test steps to ensure the same bug will not reach production again.


### Regression Test Proposal

1. Go offline
2. Click on FAB and create a new group chat
3. In the group chat click on "+" > Spilt bill
4. Create a manual request and split it with one user of the group
5. Navigate to the chat with the user you split the bill
6. Open the money request detail page
7. Verify that no space between reports is displayed in LHN

**Comment by joekaufmanexpensify** [comment] 2024-03-25 14:21
Great. TY!

**Comment by joekaufmanexpensify** [comment] 2024-03-29 12:48
Due today!

**Comment by joekaufmanexpensify** [comment] 2024-03-29 14:50
This is a pretty niche bug and IMO does not need a regression test.

**Comment by joekaufmanexpensify** [comment] 2024-03-29 14:57
Only payment needed here is $500 to @situchan for C+. Paid via upwork.

**Comment by joekaufmanexpensify** [comment] 2024-03-29 14:57
Adding external to create upwork job

**Comment by joekaufmanexpensify** [comment] 2024-03-29 14:59
@situchan offer for $500 sent!

**Comment by joekaufmanexpensify** [comment] 2024-03-29 16:26
Defer to @youssef-lr on that. Mind weighing in on whether this proposal was what was used?

**Comment by joekaufmanexpensify** [comment] 2024-04-01 14:56
Bumped 1:1

**Comment by youssef-lr** [comment] 2024-04-01 19:01
@joekaufmanexpensify yes I did use Fedi's solution!

**Comment by joekaufmanexpensify** [comment] 2024-04-01 20:10
[Discussing internally ](https://expensify.slack.com/archives/C01SKUP7QR0/p1712002212979779)

**Comment by joekaufmanexpensify** [comment] 2024-04-01 20:11
@situchan $500 sent and contract ended!

**Comment by joekaufmanexpensify** [comment] 2024-04-01 20:36
@fedirjh we landed on 50% comp here since we used your proposal, but you did not raise a PR

**Comment by joekaufmanexpensify** [comment] 2024-04-01 20:37
@fedirjh offer sent for $250!

**Comment by joekaufmanexpensify** [comment] 2024-04-01 20:42
@fedirjh $250 sent and contract ended!

**Comment by joekaufmanexpensify** [comment] 2024-04-01 20:42
Upwork job closed.

**Comment by joekaufmanexpensify** [comment] 2024-04-01 20:42
All set. Thanks everyone!

**Closed by joekaufmanexpensify** 2024-04-01 20:42 UTC
Labels: External, Engineering, Daily, Awaiting Payment, Bug
