### ISSUE TITLE
[$500] Android - Login - Tapping on unused magic link, user is logged into that random account

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#40794] opened 2024-04-23 13:18 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.64
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**If this was caught during regression testing, add the test name, ID and link from TestRail:** N/A
**Issue reported by:** Applause - Internal Team

## Action Performed:
1. Launch app
2. Enter some "X"mail id eg: [applausetester+ggxfgg@applause.expensifail.com](mailto:applausetester+ggxfgg@applause.expensifail.com)
3. Tap continue and request magic code for this account.
4. Tap on unused magic link of " Y" account eg: [applausetester+ggxftttgg@applause.expensifail.com](mailto:applausetester+ggxftttgg@applause.expensifail.com)
5. Now user is logged into "Y" account as
[applausetester+ggxftttgg@applause.expensifail.com](mailto:applausetester+ggxftttgg@applause.expensifail.com)

## Expected Result:
Tapping on unused magic link, user must not be logged into that random account

## Actual Result:
Tapping on unused magic link, user is logged into that random account

## Workaround:
Unknown 

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [ ] Android: mWeb Chrome
- [x] iOS: Native
- [ ] iOS: mWeb Safari
- [ ] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details> 

https://github.com/Expensify/App/assets/78819774/2ea3822c-e966-47e1-b3b3-7f3fa7f47b14

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01c183559fb31b83a0</li>
        <li>Upwork Job ID: 1787967062835482624</li>
        <li>Last Price Increase: 2024-05-27</li>
    </ul>
</details>

**Comment by lanitochka17** [comment] 2024-04-23 13:18
@johncschuster  FYI I haven't added the External label as I wasn't 100% sure about this issue. Please take a look and add the label if you agree it's a bug and can be handled by external contributors

**Comment by lanitochka17** [comment] 2024-04-23 13:18
We think that this bug might be related to #vip-vsp

**Comment by johncschuster** [comment] 2024-04-30 22:08
@lanitochka17 can I get a bit of clarity from you on the unused link for the "Y" account in your reproduction steps?

Specifically, how long has that link been unused? Has it been 10 minutes, an hour, a few days?

I think that'll be important to understand and help us know if this is expected or not.

**Comment by lanitochka17** [comment] 2024-05-01 14:05
@johncschuster Hi
After re-testing, I was able to reproduce with a fresh, unused link (5 min) from another account.

**Comment by lanitochka17** [comment] 2024-05-01 14:06
@johncschuster Hi
After re-testing, I was able to reproduce with a fresh, unused link (5 min) from another account.

**Comment by johncschuster** [comment] 2024-05-07 22:05
Thank you for clarifying how long you waited before clicking the Magic Link. Out of curiosity, did you generate an additional Magic Link and _then_ click the original link? Something like this:

1. Generate Magic Link A
2. Wait X amount of time
3. Generate Magic Link B
4. Wait X amount of time
5. Click Magic Link A

?

**Comment by johncschuster** [comment] 2024-05-10 21:01
No proposals yet.

**Comment by johncschuster** [comment] 2024-05-10 21:13
No proposals yet.

**Comment by johncschuster** [comment] 2024-05-13 20:44
Bumping [this comment](https://github.com/Expensify/App/issues/40794#issuecomment-2099392909) in [Slack](https://expensify.slack.com/archives/C9YU7BX5M/p1715633062787649)

**Comment by kbecciv** [comment] 2024-05-13 21:11
@johncschuster Correct, the tester generated an additional Magic Link and then clicked the original link. The issue is still reproducible on build 1.4.73.1.

https://github.com/Expensify/App/assets/93399543/daffd091-0576-4aed-95b7-075a80e54f75

**Comment by johncschuster** [comment] 2024-05-13 21:21
No proposals so far. I'm raising the bounty.

**Comment by johncschuster** [comment] 2024-05-16 17:39
We are currently experiencing site instability, which might impact issuing magic links.

**Comment by johncschuster** [comment] 2024-05-20 22:22
[Bumped in Slack](https://expensify.slack.com/archives/C01GTK53T8Q/p1716243711863779)

**Comment by b4s36t4** [comment] 2024-05-21 05:59
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
Android - Login - Tapping on unused magic link, user is logged into that random account 

### What is the root cause of that problem?

The root cause for this issue lies mainly in backend.

With the normal flow we're passing the parameters like email, otp received via mail etc which are from onyx i.e correct data.

But for the magic link we're reading values from the magic link instead of the values from the onyx which are correct i.e user entered now.

When we press the magic link ex: `https://new.expensify.com/v/14936665/111650` we're reading the `accountID` and `OTP` from the url itself whereas for the normal login we're sending `email` from the value stored in onyx which is correct, but for magic link it's derived from the URL itself which really makes the magic link to work as expect.

### What changes do you think we should make in order to solve the problem?

While the flow is different same for both the ways of login but the implementation is different in terms of backend and frontend.

There can be two potential solutions

1. Fix the backend to support `email` parameter accept from frontend and verify if the `accountID` passed from body and `accountID` for the `email` passed from body are same, if not return error.

    * For this issue we need to incorporate the `email` parameter from frontend in `signInWithValidateCode` function here https://github.com/Expensify/App/blob/bcc705ed5f5c4bfcbd2503d3a54383e6291d4ca3/src/libs/actions/Session/index.ts#L572

2. For `BeginSignIn` method's response send the `accountID` of the respected account and we can set that value inside onyx, while calling `signInWithValidateCode` method we can verify the `accountID` from the parameter and `accountID` from the onyx which will give us the clarity that they're trying to use the same magic link which was sent to their email address instead of others.

> Both the solutions include the changes in the frontend and backend.


### What alternative solutions did you explore? (Optional)
NA

**Comment by johncschuster** [comment] 2024-05-21 22:00
@hoangzinh can you review the proposal above?

**Comment by neil-marcellini** [comment] 2024-05-28 21:16
I'm not sure this is really a bug. Discussing in Slack [here](https://expensify.slack.com/archives/C01GTK53T8Q/p1716930985472119)

**Comment by neil-marcellini** [comment] 2024-05-29 03:38
It's not really a bug, so closing. Lmk if you disagree and think there's an important UX problem here, and maybe we could re-open it. I think we have more pressing issues right now though.

**Closed by neil-marcellini** 2024-05-29 03:38 UTC
Labels: External, Daily, Help Wanted, Bug
