### ISSUE TITLE
IOS - Amount in split bill is not clear when open request money

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#26349] opened 2023-08-30 21:49 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Click FAB => Split bill
2. Input amount => next
3. Kill the app and re-open the app
4. Click FAB => Request money, Observe that the previous amount from the Split bill is shown

## Expected Result:
The amount must be cleared

## Actual Result:
The amount is not cleared

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [x] iOS / native
- [ ] iOS / Safari
- [ ] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 1.3.56-24
**Reproducible in staging?:** n/a
**Reproducible in production?:** n/a
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/93399543/0a0a3f93-1ed4-4f99-83ba-f5633587fd0e

**Expensify/Expensify Issue URL:**
**Issue reported by:** @namhihi237
**Slack conversation:**  https://expensify.slack.com/archives/C049HHMV9SM/p1692880939473349

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by adelekennedy** [comment] 2023-08-31 18:42
that's great context @namhihi237 but I want to confirm of the needs reproduction label was added correctly!

**Comment by kbecciv** [comment] 2023-09-01 11:18
Hey @adelekennedy! I just double check in latest build 1.3.61.0 and still unable to reproduce it. 

https://github.com/Expensify/App/assets/93399543/685740dd-5f25-4956-94f7-01e29d66ab56

**Comment by adelekennedy** [comment] 2023-09-01 19:16
closing this - we're unable to reproduce and the issue is small

**Closed by adelekennedy** 2023-09-01 19:16 UTC
Labels: Daily, Needs Reproduction, Bug
