### ISSUE TITLE
[$250] Expense - IOU preview disappeared when previous expense deleted and submitted a new one

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#45604] opened 2024-07-17 12:50 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 9.0.7-4
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**If this was caught during regression testing, add the test name, ID and link from TestRail:** N/A
**Issue reported by:** Applause - Internal Team

## Action Performed:
Precondition: user should be Signed In
1. Open app
2. Navigate to any conversation without submitted expenses
3. Send any message
4. Submit manual expense with any amount
5. Navigate to submitted expense details page
6. Sent any message
7. Click on Header
8. Click on Delete expense > Confirm
9. Click on header link to navigate to main conversation with other user
10. Submit another manual expense with any amount

## Expected Result:
A new IOU preview should be displayed in conversation

## Actual Result:
A new IOU preview disappeared in a moment after the expense was submitted. If user reloaded the conversation, the IOU preview will be revealed

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [ ] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details> 

https://github.com/user-attachments/assets/3ca08a1c-43bc-472d-81c4-45e3fff7e3bc

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~0100fa9fb060902c76</li>
        <li>Upwork Job ID: 1813584223842076616</li>
        <li>Last Price Increase: 2024-07-24</li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @fedirjh</details>

**Comment by lanitochka17** [comment] 2024-07-17 12:51
@bfitzexpensify  FYI I haven't added the External label as I wasn't 100% sure about this issue. Please take a look and add the label if you agree it's a bug and can be handled by external contributors

**Comment by kaushiktd** [comment] 2024-07-19 05:30
@fedirjh, I'm unable to reproduce the issue. Am I doing something wrong? below is the video
[screen-capture.webm](https://github.com/user-attachments/assets/c73044a3-ba46-421f-b6f5-b9fea5e59162)

**Comment by Zakpak0** [comment] 2024-07-19 07:50
## Proposal
### Please re-state the problem that we are trying to solve in this issue.

When we create a new expense after deleting a previous one, with a comment, it's disappearing.
We are trying to stop that new expense from disappearing off the screen.

### What is the root cause of that problem?
When we create our first expense, we the value of the **reportActionsID** becomes that of the created expense. 
[src/pages/home/report/ReportActionsView.tsx](https://github.com/Expensify/App/blob/main/src/pages/home/report/ReportActionsView.tsx#L104)
```typescript
    const reportActionID = route?.params?.reportActionID;
```

Afterwards, we then delete our expense, but because we've left a the comment, the deleted expense is still included in our **reportActions** array (otherwise it gets removed).

Now when we navigate backwards, the old expense was still being referenced as the **reportActionsID**
We create a new expense. 
This updates the value of the **iouReportID** property in our **report** from that of the old expense to the newer one.
This triggers a re-render but the previous **reportActionId** from our deleted expense is still being used as the indexing point.
[src/pages/home/report/ReportActionsView.tsx](https://github.com/Expensify/App/blob/main/src/pages/home/report/ReportActionsView.tsx#L235-L240)
```typescript
    const indexOfLinkedAction = useMemo(() => {
        if (!reportActionID) {
            return -1;
        }
        return combinedReportActions.findIndex((obj) => String(obj.reportActionID) === String(isFirstLinkedActionRender.current ? reportActionID : currentReportActionID));
    }, [combinedReportActions, currentReportActionID, reportActionID]);
```

Our **combinedreportActions** gets sliced too early and we end up with one element short on the next render.
[src/pages/home/report/ReportActionsView.tsx](https://github.com/Expensify/App/blob/main/src/pages/home/report/ReportActionsView.tsx#L250-L258)
```typescript
        if (isFirstLinkedActionRender.current) {
            return combinedReportActions.slice(indexOfLinkedAction);
        }
        const paginationSize = getInitialPaginationSize;
        return combinedReportActions.slice(Math.max(indexOfLinkedAction - paginationSize, 0));

        // currentReportActionID is needed to trigger batching once the report action has been positioned
        // eslint-disable-next-line react-compiler/react-compiler, react-hooks/exhaustive-deps
    }, [reportActionID, combinedReportActions, indexOfLinkedAction, isLoading, currentReportActionID]);
```

[src/pages/home/report/ReportActionsView.tsx](https://github.com/Expensify/App/blob/main/src/pages/home/report/ReportActionsView.tsx#L104)
### What changes do you think we should make in order to solve the problem?
Change our **reportActionID** reference
```typescript
    const reportActionID = route?.params?.reportActionID;

```
and instead check whether report action is **"a parent that has been deleted"** before we return it's ID
```typescript
    const reportActionID = useMemo(() => {
        const reportAction = allReportActions.find((obj) => (String(obj.reportActionID) === String(route?.params?.reportActionID)))
       return reportAction && ReportActionsUtils.isDeletedParentAction(reportAction) ? undefined : route?.params?.reportActionID
    },[allReportActions])
```
Leaving the reportActionID as undefined will stop us from slicing our array and give the component updates time to resolve.

Here's a fork branch where you can test the [changes](https://github.com/Zakpak0/Expensify-App-Fork/tree/zakpak0/bugfix-issue-%2345604) 

### What alternative solutions did you explore? (Optional)

We could also force a re-render of the component by adding another dependency to one of our useEffects.
But I'm not 100% why this works yet and the transition is not smooth. There's a small delay before the render of the new expense.

**Comment by kavimuru** [comment] 2024-07-29 16:01
Issue is not reproduced by the tester anymore

https://github.com/user-attachments/assets/fcb341ce-0f80-42a0-adc0-b484f2256aa7

**Comment by bfitzexpensify** [comment] 2024-07-29 16:28
Cool, closing.

**Closed by bfitzexpensify** 2024-07-29 16:28 UTC
Labels: External, Daily, Help Wanted, Overdue, Bug
