### ISSUE TITLE
[$500] IOU-In workspace transaction report page, split bill option is not displayed.

### ISSUE THREAD

**Issue by kavimuru** [Expensify/App#34423] opened 2024-01-12 09:58 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:**
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** Applause - Internal Team
**Slack conversation:**

## Action Performed:
1. Launch app
2. Tap on a Workspace chat
3. Tap plus icon near compose
4. Note split bill option is displayed
5. Tap on any expense report or create a new open and open it
6. In transaction report page, tap plus icon near compose
7. Note split bill option is missing

## Expected Result:
In workspace transaction report page, split bill option must be shown.

## Actual Result:
In workspace transaction report page, split bill option is not displayed.

## Workaround:
unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [x] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

https://github.com/Expensify/App/assets/43996225/4933a068-3a7b-47d9-b84b-8d298efbd744

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01a82e43fbd8ba4922</li>
        <li>Upwork Job ID: 1745747139352756224</li>
        <li>Last Price Increase: 2024-02-02</li>
    </ul>
</details>

**Comment by FitseTLT** [comment] 2024-01-12 10:04
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
In workspace transaction report page, split bill option is not displayed.

### What is the root cause of that problem?
We are only allowing split menu for group chat and room here
https://github.com/Expensify/App/blob/55746c78a6ef59d9ad636eda8c610023c3cd62ac/src/libs/ReportUtils.ts#L3815-L3817
### What changes do you think we should make in order to solve the problem?

We should allow workspace transaction report pages too
### What alternative solutions did you explore? (Optional)

**Comment by mananjadhav** [comment] 2024-01-15 17:37
I'll check and reproduce the issues. I can see code for both the proposals but not the explanation.

**Comment by johncschuster** [comment] 2024-01-18 22:30
Still reviewing proposals

**Comment by mananjadhav** [comment] 2024-01-20 20:40
I have been trying to figure out if the Split bill is supposed to show. I can see this comment in the code.

```
// User created policy rooms and default rooms like #admins or #announce will always have the Split Bill option
// unless there are no other participants at all (e.g. #admins room for a policy with only 1 admin)
// DM chats will have the Split Bill option only when there are at least 2 other people in the chat.
// Your own workspace chats will have the split bill option.

``` 

Based @dukenv0307's previous comment, @johncschuster can you please confirm if this is a valid bug?

**Comment by mananjadhav** [comment] 2024-01-29 00:41
Quick bump @johncschuster.

**Comment by johncschuster** [comment] 2024-02-01 22:52
Sorry I let this slip, @mananjadhav! I'm reviewing your comment above now!

**Comment by mananjadhav** [comment] 2024-02-06 20:14
quick bump @johncschuster ^

**Comment by johncschuster** [comment] 2024-02-14 22:28
Sorry for the delay here. I've had trouble finding the focus time to really dig into this. Yes, when I look a the comment from the code (from [your comment](https://github.com/Expensify/App/issues/34423#issuecomment-1902260456) above, @mananjadhav) and review the reproduction steps, I believe this behavior is expected.

**Comment by johncschuster** [comment] 2024-02-14 22:31
Unless this behavior was produced in an #admins room for a policy with only 1 admin (as mentioned above), I think we can close this one out.

**Closed by johncschuster** 2024-02-14 22:31 UTC
Labels: Engineering, Daily, Internal, Bug
