### ISSUE TITLE
[$500] Task - Font issues with the "&" character

### ISSUE THREAD

**Issue by izarutskaya** [Expensify/App#33059] opened 2023-12-14 12:13 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.12.0
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** Applause-Internal Team
**Slack conversation:** @

## Action Performed:
1. Navigate to https://staging.new.expensify.com/
2. Create a task with "&" in the title in any 1:1 conversation
3. Open the task report

## Expected Result:
The font should be the same. "&" should be recognizable and shouldn't differ through the whole app/web.

## Actual Result:
The title font used in the task report and in the 1:1 conversation are different. It also affects the member profile page. "&" character has been changed to something else.

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [x] Android: mWeb Chrome
- [x] iOS: Native
- [x] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

![Bug6312699_1702537527222!Profile](https://github.com/Expensify/App/assets/115492554/72bb4e5a-1ea8-447d-8fbd-2fa247e5709f)

![Bug6312699_1702537527238!Task](https://github.com/Expensify/App/assets/115492554/8a7ced0e-a04d-424b-9d24-956da4c85573)

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~0191a6f36ebaff7442</li>
        <li>Upwork Job ID: 1735271694782447616</li>
        <li>Last Price Increase: 2023-12-21</li>
    </ul>
</details>

**Comment by RASalamanca** [comment] 2023-12-14 23:06
## Proposal

### Unifying the style of the "&" character across different parts of the app

The font used in the task report, the 1:1 conversation, and member profile page are different. And as a result the "&" character as well as many other special characters look wildly different across the app.

### What is the root cause of that problem?

The task title uses the New Kansas font family, but in header view you are using Neue Bold.
The Unicode character has not changed, but the glyph used to represent it varies wildly across fonts.

For reference this is the "&" character in New Kansas
https://imgur.com/a/xAMcuBz

This is the same character in Neue Bold
https://imgur.com/a/KERAURM

### What changes should you make in order to solve the problem?

The easiest solution is to the ditch the New Kansas font and stick to the Bebas Neue font family across the entire app.

### Alternative solutions:
- I could modify the New Kansas font file to change the "&" glyph. However, the styling of the glyph will be inconsistent with the rest of the text written in that font.
- I could also recommend an alternative font similar to New Kansas, but less stylized.

**Comment by RASalamanca** [comment] 2023-12-14 23:11
Contributor details
Your Expensify account email: r.salamanca95@outlook.com
Upwork Profile Link: https://www.upwork.com/freelancers/~01cf11d5186c356d5a

**Comment by rushatgabhane** [comment] 2023-12-18 06:41
@JmillsExpensify i think we should close this issue? Different font style is intentional

**Comment by JmillsExpensify** [comment] 2023-12-27 23:42
Agreed, so closing.

**Closed by JmillsExpensify** 2023-12-27 23:42 UTC
Labels: External, Daily, Help Wanted, Overdue, Bug
