### ISSUE TITLE
DM with user does not show up in search results until the user sends the message

### ISSUE THREAD

**Issue by m-natarajan** [Expensify/App#35678] opened 2024-02-02 17:21 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:**
**Reproducible in staging?:** needs reproduction
**Reproducible in production?:** needs reproduction
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** @puneetlath 
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1706814460499029

## Action Performed:
1. Search for DM with Ryan using the email address ryan@expensify.com
## Expected Result:
Search result should show up
## Actual Result:
Not showing until Ryan sends message
## Workaround:
unknown
## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [ ] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence
![Screenshot 2024-02-01 at 2 05 08 PM](https://github.com/Expensify/App/assets/38435837/29c2199d-e601-4fbf-ade3-510d3b5d40ab)
![Screenshot 2024-02-01 at 12 27 56 PM](https://github.com/Expensify/App/assets/38435837/1c3c452f-82c9-44ee-bb92-cee233c1a77e)

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by joekaufmanexpensify** [comment] 2024-02-02 21:25
I can't reproduce. Discussing more [here. ](https://expensify.slack.com/archives/C049HHMV9SM/p1706909105450799?thread_ts=1706814460.499029&cid=C049HHMV9SM)

**Comment by joekaufmanexpensify** [comment] 2024-02-05 14:31
Going to try to reproduce more today

**Comment by joekaufmanexpensify** [comment] 2024-02-05 22:21
Still can't reproduce. Discussing more [here. ](https://expensify.slack.com/archives/C049HHMV9SM/p1707171665134779?thread_ts=1706814460.499029&cid=C049HHMV9SM)

**Comment by joekaufmanexpensify** [comment] 2024-02-08 16:51
Going to try and reproduce again today

**Comment by joekaufmanexpensify** [comment] 2024-02-08 21:59
Just tried to reproduce this again on desktop after freshly signing in and couldn't.

**Comment by joekaufmanexpensify** [comment] 2024-02-08 21:59
Closing this for now as it doesn't seem to be consistently reproducible. LMK if anyone experiences it again and happy to try and triage further!

**Closed by joekaufmanexpensify** 2024-02-08 21:59 UTC
Labels: Daily, Needs Reproduction, Bug
