### ISSUE TITLE
[HOLD for payment 2022-09-26] [$1000] When you send old :expensify: link and hover you will not see any tooltip and the link is without underline - reported by @Puneet-here

### ISSUE THREAD

**Issue by mvtglobally** [Expensify/App#9739] opened 2022-07-06 05:46 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/docs/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Go to any chat
2. Send https://www.expensify.com/inbox or [link](https://www.expensify.com/inbox)
3. Or go to concierge chat as it contains old :expensify: links

## Expected Result:
You should see underline below the link and tooltip when you hover

## Actual Result:
You don't see any tooltip or underline

## Workaround:
unknown 

## Platform:

Where is this issue occurring?

- Web
- iOS
- Android
- Desktop App
- Mobile Web

**Version Number:** 1.1.79-11
**Reproducible in staging?:** Y 
**Reproducible in production?:** Y 
**Email or phone of affected tester (no customers):** 
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation 

https://user-images.githubusercontent.com/43995119/177477653-25a955da-5383-482e-9174-396f0f065e6a.mov

**Expensify/Expensify Issue URL:** 
**Issue reported by:** @Puneet-here
**Slack conversation:** https://expensify.slack.com/archives/C01GTK53T8Q/p1656098692618689

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by mountiny** [comment] 2022-07-08 23:58
This definitely seems as a suitable External issue

**Comment by puneetlath** [comment] 2022-07-11 23:28
Upwork job is here: https://www.upwork.com/jobs/~0123b2819ac262a34e

**Comment by parasharrajat** [comment] 2022-07-12 15:46
> Send [expensify.com/inbox](https://www.expensify.com/inbox) or [link](https://www.expensify.com/inbox)

These are old links. For new, you can copy-paste the URL from the browser address bar.

**Comment by jeet-dhandha** [comment] 2022-07-12 18:32
I am not able to run the web app `yarn web`. Is there any issue with the app 🤔 
<img width="1436" alt="Screenshot 2022-07-13 at 12 02 06 AM" src="https://user-images.githubusercontent.com/78416198/178568479-9bf3d426-459e-4e57-9b9b-c0ca6a378144.png">

**Comment by jayeshmangwani** [comment] 2022-07-12 19:52
#### Proposal

We need to wrap the oldExpensifyLink in ToolTip here and need to add the style prop to text for underlining


https://github.com/Expensify/App/blob/41346c82c6c0854e0c5bc427e9193d40723feec6/src/components/HTMLEngineProvider/HTMLRenderers/AnchorRenderer.js#L44-L53
```diff
+            <Tooltip text={attrHref}>
                <Text
-                    style={styles.link}
+                     style={[styles.link, {...props.style}]}
                    onPress={() => Link.openOldDotLink(internalExpensifyPath)}
                >
                    <TNodeChildrenRenderer tnode={props.tnode} />
                </Text>
+            </Tooltip>
```

and this issue is happening with the new Expensify link also, please try with this link `https://new.expensify.com/inbox`,
new Expensify link also has to be wrapped in ToolTip

https://github.com/Expensify/App/blob/41346c82c6c0854e0c5bc427e9193d40723feec6/src/components/HTMLEngineProvider/HTMLRenderers/AnchorRenderer.js#L31-L40

```diff
+            <Tooltip text={attrHref}>
                <Text
-                    style={styles.link}
+                    style={[styles.link, {...props.style}]}
                    onPress={() => Navigation.navigate(internalNewExpensifyPath)}
                >
                    <TNodeChildrenRenderer tnode={props.tnode} />
                </Text>
+            </Tooltip>
```

Video:

https://user-images.githubusercontent.com/35371050/178581737-e19c53b1-da71-4612-85d1-e8a45e6ebffc.mov

**Comment by mountiny** [comment] 2022-07-12 23:03
@jeet-dhandha Sorry to see you having problems running the app :/

The best way to get help is through our open-source Slack channel where all the other contributors and Expensify engineers are. You can get more information about how the contributing process work [here](https://github.com/Expensify/App/blob/main/contributingGuides/CONTRIBUTING.md). There are also other important markdown files you can find in the repository which will help you get started.

If you haven't reached out yet, please, ask for access to the Slack channel and we will be able to help you resolve any problems way quicker.

Looking forward to you solving the issues in the App 🙌

**Comment by parasharrajat** [comment] 2022-07-12 23:59
@jayeshmangwani Although it will fix this issue, it won't work as expected. It will have regressions. What if this component is used outside the report message/comment?

**Comment by parasharrajat** [comment] 2022-07-13 00:00
Looking at code history, I can tell that when this code was added, tooltips didn't exist for links. This means it was missed during the implementation of link tooltips.

**Comment by parasharrajat** [comment] 2022-07-18 03:31
Waiting for proposals.

**Comment by puneetlath** [comment] 2022-07-19 15:15
Still waiting for proposals. Increasing price to $500.

**Comment by parasharrajat** [comment] 2022-07-19 15:22
@jayeshmangwani Would you like to update your proposal without the issue?

**Comment by jayeshmangwani** [comment] 2022-07-19 16:16
#### Updated proposal

Thanks for the ping @parasharrajat 

if we want to use ToolTip only for comment/message then we have to add a new if condition here with HTMLEngineUtils.isInsideComment(props.tnode)

https://github.com/Expensify/App/blob/41346c82c6c0854e0c5bc427e9193d40723feec6/src/components/HTMLEngineProvider/HTMLRenderers/AnchorRenderer.js#L44-L53

```diff
+    if (internalExpensifyPath && !isAttachment && HTMLEngineUtils.isInsideComment(props.tnode)) {
+        return (
+          <Tooltip text={attrHref}>
+            <Text
+                style={styles.link}
+                onPress={() => Link.openOldDotLink(internalExpensifyPath)}
+            >
+                <TNodeChildrenRenderer tnode={props.tnode} />
+            </Text>
+.         </Tooltip>
+        );
+    }
```
@parasharrajat please correct me if I misunderstood your concern from previous proposal my https://github.com/Expensify/App/issues/9739#issuecomment-1182409266

**Comment by mountiny** [comment] 2022-07-19 18:30
@jayeshmangwani Please, use `proposal` as the first word of the comment to make sure the issue becomes `Daily` 🙌  Thank you

**Comment by jayeshmangwani** [comment] 2022-07-19 20:26
> I see, still, the proposal can be improved and the code can be cleaned or refactored.

I am debugging this and if I get a better proposal then I will update it, Thanks

**Comment by jayeshmangwani** [comment] 2022-07-20 20:51
> I see, still, the proposal can be improved and the code can be cleaned or refactored.

@parasharrajat 

These are the few things that can be cleaned, 

this code is being used 3 times in the AnchorRendere file here, we can make a separate component and can pass onPress as a prop

https://github.com/Expensify/App/blob/41346c82c6c0854e0c5bc427e9193d40723feec6/src/components/HTMLEngineProvider/HTMLRenderers/AnchorRenderer.js#L33-L38
https://github.com/Expensify/App/blob/41346c82c6c0854e0c5bc427e9193d40723feec6/src/components/HTMLEngineProvider/HTMLRenderers/AnchorRenderer.js#L46-L51
https://github.com/Expensify/App/blob/41346c82c6c0854e0c5bc427e9193d40723feec6/src/components/HTMLEngineProvider/HTMLRenderers/AnchorRenderer.js#L59-L65
```diff
-<Text
-    style={styles.link}
-    onPress={() => Link.openOldDotLink(internalExpensifyPath)}
->
-    <TNodeChildrenRenderer tnode={props.tnode} />
-</Text>
```            
 we can replace this with this component,

```diff
+function LinkRenderer ({ onPress }) {
+  return (
+      <Text
+          style={[styles.link]}
+          onPress={onPress}
+      >
+          <TNodeChildrenRenderer tnode={props.tnode} />
+      </Text>
+  )
+};
```

and for ToolTip + Link (messages/comments) we can create a new component like this,

```diff
+function TooltipLinkRenderer ({ onPress }) {
+  return (
+      <Tooltip text={attrHref}>
+          <Text
+              style={[styles.link, {...props.style}]}
+              onPress={onPress}
+          >
+              <TNodeChildrenRenderer tnode={props.tnode} />
+          </Text>
+      </Tooltip>
+  )
+}
```

and if we want to use the ToolTip for the comments only then we can add this code at the old expensify link,

```diff
+const isInsideComment = !HTMLEngineUtils.isInsideComment(props.tnode);

-<Text
-  style={styles.link}
-  onPress={() => Navigation.navigate(internalNewExpensifyPath)}
->
-  <TNodeChildrenRenderer tnode={props.tnode} />
-</Text>
+  isInsideComment ?
+      <TooltipLinkRenderer onPress={() => Link.openOldDotLink(internalExpensifyPath)} />
+      :
+      <LinkRenderer onPress={() => Link.openOldDotLink(internalExpensifyPath)} />
```

**Comment by parasharrajat** [comment] 2022-07-20 22:00
> this code is being used 3 times in the AnchorRendere file here, we can make a separate component and can pass onPress as a prop

Good point. But You are missing a small pattern. Don't worry I'll help. 

Try to find what is different in all of three if blocks https://github.com/Expensify/App/blob/41346c82c6c0854e0c5bc427e9193d40723feec6/src/components/HTMLEngineProvider/HTMLRenderers/AnchorRenderer.js#L31-L37. 

Only the onPress call. Right? So why don't we create a common press handler and use it? 

```
    const navigateToLink = () => {
        // If we are handling a New Expensify link then we will assume this should be opened by the app internally. This ensures that the links are opened internally via react-navigation
        // instead of in a new tab or with a page refresh (which is the default behavior of an anchor tag)
        if (internalNewExpensifyPath) {
            Navigation.navigate(internalNewExpensifyPath);
            return;
        }

        // If we are handling an old dot Expensify link we need to open it with openOldDotLink() so we can navigate to it with the user already logged in.
        // As attachments also use expensify.com we don't want it working the same as links.
        if (internalExpensifyPath && !isAttachment) {
            Link.openOldDotLink(internalExpensifyPath);
            return;
        }
        Linking.openURL(attrHref);
    };
```

**But your proposal is still incomplete.** Try out the following links and check that hovering over them shows the tooltip and right-clicking shows the contextMenu for links.

![image](https://user-images.githubusercontent.com/24370807/180089321-49973258-ba53-473d-a2c3-85ffe838d4d5.png)

**Comment by jayeshmangwani** [comment] 2022-07-21 18:57
> Only the onPress call. Right? So why don't we create a common press handler and use it?

@parasharrajat Thanks for the above suggestions yes we can create a common function for this, and yes you are right my previous proposal missed the context menu part, 

```
const navigateToLink = () => {
  // If we are handling a New Expensify link then we will assume this should be opened by the app internally. This ensures that the links are opened internally via react-navigation
  // instead of in a new tab or with a page refresh (which is the default behavior of an anchor tag)
  if (internalNewExpensifyPath) {
      Navigation.navigate(internalNewExpensifyPath);
      return;
  }

  // If we are handling an old dot Expensify link we need to open it with openOldDotLink() so we can navigate to it with the user already logged in.
  // As attachments also use expensify.com we don't want it working the same as links.
  if (internalExpensifyPath && !isAttachment) {
      Link.openOldDotLink(internalExpensifyPath);
      return;
  }
  Linking.openURL(attrHref);
};
```

For contextMenu I took reference from the AnchorForCommentsOnly component and removed the email checking condition part from the first argument and used static type `CONTEXT_MENU_TYPES.LINK` 
 https://github.com/Expensify/App/blob/d48e1474241b32b5702101ab12679d0917df410f/src/components/AnchorForCommentsOnly/BaseAnchorForCommentsOnly/index.js#L65-L77
 
 created 2 functions, 
 
 1. for links only that has no tooltip
 2. for tooltip and link
 
 ```
 const linkRenderer = () => {
  return (
    <Text
        style={[styles.link, {...props.style}]}
        onPress={()=> navigateToLink()}
    >
      <TNodeChildrenRenderer tnode={props.tnode} />
    </Text>
  )
};

const tooltipLinkRenderer  = () => {
  return (
    <PressableWithSecondaryInteraction
      inline
      onSecondaryInteraction={
      (event) => {
          ReportActionContextMenu.showContextMenu(
              ContextMenuActions.CONTEXT_MENU_TYPES.LINK,
              event,
              attrHref,
              lodashGet(attrHref, 'current'),
          );
      }}
    >
      <Tooltip text={attrHref}>
        {linkRenderer()}
      </Tooltip>
    </PressableWithSecondaryInteraction>
  )
};
 ```
 
 and made a single if condition for old and new Expensify path as we have made a function that handles the onPress, and inside if added a ternary for checking the isComment , if from the comment then will show tooltip otherwise link only
 
 ```
 if ((internalExpensifyPath && !isAttachment) || internalNewExpensifyPath) {
  return (
    isInsideComment ?
      tooltipLinkRenderer()
      :
      linkRenderer()
  )
}
 ```
 
 Thanks for the help

**Comment by parasharrajat** [comment] 2022-07-21 20:02
> For contextMenu I took reference from the AnchorForCommentsOnly

Good. But you are still missing something big about AnchorForCommentsOnly and its usage in AnchorRenderer. Do we really need tooltipLinkRenderer?

**Comment by parasharrajat** [comment] 2022-07-26 06:06
@jayeshmangwani Are you still interested in this issue?

**Comment by jayeshmangwani** [comment] 2022-07-26 06:15
> @jayeshmangwani Are you still interested in this issue?

@parasharrajat Sorry for some reason I am not working for the next 4-5 days, so I can not work on this, Thanks

**Comment by puneetlath** [comment] 2022-07-26 19:02
Still waiting for proposals. Increasing price to $1000.

**Comment by parasharrajat** [comment] 2022-07-26 20:01
### Proposal

I think I can finish it. I have a pretty fair plan to do it. 

1. As the UI elements are same for all three conditions https://github.com/Expensify/App/blob/99d5dc3970c1ec62b55ef767349cef3fddc863ed/src/components/HTMLEngineProvider/HTMLRenderers/AnchorRenderer.js#L31-L67.

I will create a common function to navigate to different locations. 

```js
const navigateToLink = () => {
  // If we are handling a New Expensify link then we will assume this should be opened by the app internally. This ensures that the links are opened internally via react-navigation
  // instead of in a new tab or with a page refresh (which is the default behavior of an anchor tag)
  if (internalNewExpensifyPath) {
      Navigation.navigate(internalNewExpensifyPath);
      return;
  }

  // If we are handling an old dot Expensify link we need to open it with openOldDotLink() so we can navigate to it with the user already logged in.
  // As attachments also use expensify.com we don't want it working the same as links.
  if (internalExpensifyPath && !isAttachment) {
      Link.openOldDotLink(internalExpensifyPath);
      return;
  }
  Linking.openURL(attrHref);
};
```
2. Now there will be only one condition for `!HTMLEngineUtils.isInsideComment(props.tnode)`which is used for links other than report messages. 
```
    if (!HTMLEngineUtils.isInsideComment(props.tnode)) {
        // This is not a comment from a chat, the AnchorForCommentsOnly uses a Pressable to create a context menu on right click.
        // We don't have this behaviour in other links in NewDot
        // TODO: We should use TextLink, but I'm leaving it as Text for now because TextLink breaks the alignment in Android.
        return (
            <Text
                style={styles.link}
                onPress={navigateToLink}
            >
                <TNodeChildrenRenderer tnode={props.tnode} />
            </Text>
        );
    }
```

3. Lastly, we want to show the tooltips for all types of links as they will fall under the report messages but also want to handle the different navigation based on the type of link. Whether it is a newDotlink or oldDOtlink etc. 

To do this, I will use the same `AnchorForCommentsOnly` block and our `navigateToLink` function that we created on step 1. I will optionally pass this function to `AnchorForCommentsOnly`
 https://github.com/Expensify/App/blob/99d5dc3970c1ec62b55ef767349cef3fddc863ed/src/components/HTMLEngineProvider/HTMLRenderers/AnchorRenderer.js#L70 


```js
  <AnchorForCommentsOnly
            ...
            onPress={internalNewExpensifyPath || internalExpensifyPath || !HTMLEngineUtils.isInsideComment(props.tnode) ? navigateToLink : undefined}
        >
```

Here we are only passing the onPress handler when link is either `internalNewExpensifyPath` or `internalExpensifyPath` or `!HTMLEngineUtils.isInsideComment(props.tnode)`. This `onPress` when present will override the href of  `AnchorForCommentsOnly`. 

Now, all types of URLs will have tooltips in report Messages.

**Comment by parasharrajat** [comment] 2022-07-26 20:02
@puneetlath I have a proposal above.

**Comment by ahmdshrif** [comment] 2022-07-27 00:04
I was preparing a proposal like your proposal. 
the only addition you will need is to add 
`href={!this.props.onPress ? this.props.href : undefined}`  on BaseAnchorForCommentsOnly/index to prevent internal  link  on web form open 2 times .

**Comment by puneetlath** [comment] 2022-07-27 17:31
Your plan for the links sounds good to me. 

>Other than this, I have long planned to clean up BaseAnchorForCommentsOnly component as it does two different things, render links and render attachments(Except images). I will separate these two behavior into two different components so it is easy to follow the code.

This sounds like a good update, but can we separate it from this PR? Doesn't seem like it needs to be tied to it.

**Comment by puneetlath** [comment] 2022-07-27 17:33
@mananjadhav adding you as the C+ since @parasharrajat is going to take this issue on.

**Comment by parasharrajat** [comment] 2022-07-27 22:40
I found two bugs. 
1. Clicking on `new.expensify.com/index` does nothing. It throws an error on the console as `/index` is not a valid route in App. 
2. When a user is offline clicking on internal links shows a growl that you are offline. But as these are links it should work offline too. 

Will report them on slack shortly..

**Comment by puneetlath** [comment] 2022-08-09 23:20
@mananjadhav have you had a chance to review this one yet?

**Comment by mananjadhav** [comment] 2022-08-10 02:52
Hi @puneetlath, I thought as per the guidelines, if member of the C+ team is working on the issue, then C+ Review won't be needed?

I can take it up if you'd like, and give me time until tomorrow.

**Comment by puneetlath** [comment] 2022-08-30 11:19
@parasharrajat @mananjadhav I've sent you both hiring offers through Upwork. Please accept when you get a chance so that we can pay you out. Thanks!

**Comment by puneetlath** [comment] 2022-09-15 14:18
Looks like that PR was merged yesterday. Will pay this out in 6 days if no more regressions.

**Comment by puneetlath** [comment] 2022-09-27 00:10
@mananjadhav - paid. 
@parasharrajat - hiring offer sent
@Puneet-here - it doesn't look like you were paid for reporting. If not, can you apply here? https://www.upwork.com/jobs/~01af2bac857d001e72

**Comment by Puneet-here** [comment] 2022-09-27 07:21
Applied! Thanks.

**Comment by puneetlath** [comment] 2022-09-28 23:11
All paid! Thanks everyone.

**Closed by puneetlath** 2022-09-28 23:11 UTC
Labels: Exported, External, Engineering, Weekly, Awaiting Payment
