### ISSUE TITLE
[HOLD for payment 2024-10-25] [HOLD for payment 2024-10-24] [$250] mWeb - Room - Cursor and hashtag are not aligned in same line

### ISSUE THREAD

**Issue by IuliiaHerets** [Expensify/App#50777] opened 2024-10-15 06:43 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___
 
**Version Number:** v9.0.49-0
**Reproducible in staging?:** Y
**Reproducible in production?:**
**Issue reported by:** Applause Internal Team

## Action Performed:
1. Go to https://staging.new.expensify.com/home
2. Tap fab - start chat - room
3. Note the room name field

## Expected Result:
Cursor and hashtag must be aligned in same line

## Actual Result:
Cursor and hashtag are not aligned in same line

## Workaround:
Unknown

## Platforms:

- [ ] Android: Native
- [x] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [ ] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

https://github.com/user-attachments/assets/794bc419-9ef7-4ba5-9443-ae92b7b8a0a1
 
</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~021846180268747195858</li>
        <li>Upwork Job ID: 1846180268747195858</li>
        <li>Last Price Increase: 2024-10-15</li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @joekaufmanexpensify</details>

**Comment by ChavdaSachin** [comment] 2024-10-15 10:44
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
Room - Cursor and hashtag are not aligned in same line

### What is the root cause of that problem?
Extra padding right here is the culprit
https://github.com/Expensify/App/blob/b4b59651d38deb3d91b1fd561458fe0d4e23752c/src/styles/index.ts#L1184

### What changes do you think we should make in order to solve the problem?
Remove extra padding here
https://github.com/Expensify/App/blob/b4b59651d38deb3d91b1fd561458fe0d4e23752c/src/styles/index.ts#L1184

It still solves the original problem https://github.com/Expensify/App/issues/48281
while solving following new problems
https://github.com/Expensify/App/issues/50777
https://github.com/Expensify/App/issues/50778

### What alternative solutions did you explore? (Optional)

**Reminder:** Please use plain English, be brief and avoid jargon. Feel free to use images, charts or pseudo-code if necessary. Do not post large multi-line diffs or write walls of text. Do not create PRs unless you have been hired for this job.

**Comment by joekaufmanexpensify** [comment] 2024-10-15 13:23
Went ahead and assigned @tsa321 and @alitoshmatov as their original PR introduced the regression, and PR fixing is in review

**Comment by joekaufmanexpensify** [comment] 2024-10-21 13:43
This was fixing a regression, so IDT any checklist or payment needed here. Closing for now, but LMK if anyone disagrees with that!

**Closed by joekaufmanexpensify** 2024-10-21 13:43 UTC
Labels: External, Engineering, Weekly, Awaiting Payment, Bug
