### ISSUE TITLE
Chat - Compose box reappears when trying to edit a message, exit the chat and go to it again

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#31238] opened 2023-11-11 17:31 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.3.98.0
**Reproducible in staging?:** y
**Reproducible in production?:** n
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** Applause - Internal Team
**Slack conversation:**

## Action Performed:
Pre-requisite: user must be logged in.
1. Go to any chat.
2. Long tap on any sent message.
3. Tap on "Edit comment".
4. Verify the compose box gets hidden.
5. Tap on the back button to go to LHN.
6. Go to the same chat again.

## Expected Result:
The compose box should be still hidden.

## Actual Result:
The compose box reappears.

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [x] Android: mWeb Chrome
- [x] iOS: Native
- [ ] iOS: mWeb Safari
- [ ] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

https://github.com/Expensify/App/assets/93399543/64d71ca1-cffc-4817-aa93-1e417d9a6e30

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by DylanDylann** [comment] 2023-11-12 06:49
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
- Chat - Compose box reappears when trying to edit a message, exit the chat and go to it again

### What is the root cause of that problem?
- Currently, clicking on the back button will blur the edit composer. In onBlur callback, we call ```setShouldShowComposeInputKeyboardAware(true)```
https://github.com/Expensify/App/blob/ffe1c63a57f80479450dcf0e5c2fa82509630c8f/src/pages/home/report/ReportActionItemMessageEdit.js#L423-L430
- So when we come to this report again, the composer reappears
### What changes do you think we should make in order to solve the problem?
- Generally, we need to distinguish between two blur actions: blur + report is still mounted and blur + report is unmounted. We can do it by:
1. Once we focused on the edit composer, set global ```editingReportActionID``` to the current reportActionID by updating:
https://github.com/Expensify/App/blob/ffe1c63a57f80479450dcf0e5c2fa82509630c8f/src/pages/home/report/ReportActionItemMessageEdit.js#L410
to 
```
                          onFocus={() => {
                                editingReportActionID = props.action.reportActionID;
```
2. Once we blur this edit composer, clear the global ```editingReportActionID``` with the delay. We only clear the ```editingReportActionID``` in case the report still mounted. Do it by updating:
https://github.com/Expensify/App/blob/ffe1c63a57f80479450dcf0e5c2fa82509630c8f/src/pages/home/report/ReportActionItemMessageEdit.js#L423
to
```
                            onBlur={(event) => {
                                clearEditingReportActionIDWithDelay(null);
```
with ```clearEditingReportActionIDWithDelay``` is defined as below:
```
    const isMountedRef = useRef(false);
    useEffect(() => {
        isMountedRef.current = true;
        return () => {
            isMountedRef.current = false;
        };
    }, []);

    const clearEditingReportActionIDWithDelay = useCallback((value: string | null) => {
        setTimeout(() => {
            if (isMountedRef.current) {
                ReportActionComposeFocusManager.setEditingReportID(value);
            }
        }, 500);
    }, []);
```


### What alternative solutions did you explore? (Optional)

- NA

**Comment by situchan** [comment] 2023-11-12 07:18
Seems like regression from https://github.com/Expensify/App/pull/31041

**Comment by narefyev91** [comment] 2023-11-13 11:38
> Seems like regression from #31041

It's not a regression from linked pr https://github.com/Expensify/App/pull/31041 - i rolled back locally all those changes - and issue is still reproduced. I'm not even sure that such behaviour was fixed somewhere
Just a closely area - this PR -  https://github.com/Expensify/App/pull/27190
Issue has already been happened there
<img width="953" alt="Screenshot 2023-11-13 at 13 38 09" src="https://github.com/Expensify/App/assets/28352309/1d8e07f5-99dd-4abf-a8b3-25f968aa0636">

**Comment by s77rt** [comment] 2023-11-13 12:09
This does not seem to be a bug. When you exit the chat the edit composer is blurred. Going back you are expected to see the main composer.

If you ever open a chat and didn't find the main composer this can be more frustrating as you may not find the edit composer either (e.g. received new messages that pushed the message you were editing up - no longer in view)

**Comment by situchan** [comment] 2023-11-13 12:11
Since this is marked as deploy blocker, curious how this behaves in production right now

**Comment by s-alves10** [comment] 2023-11-14 13:54
I don't think this is a bug

**Comment by roryabraham** [comment] 2023-11-14 15:54
Not a bug

**Closed by roryabraham** 2023-11-14 15:54 UTC
Labels: Engineering, Hourly, Overdue
