### ISSUE TITLE
[$500] Web - Remove member from workspace does not hide workspace's rooms on that member account when he's offline

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#23000] opened 2023-07-17 11:38 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Login with account A and B on two browsers/devices
2. Create a workspace with A and B (A is admin)
3. Create a room for that workspace
4. Verify that on B, the workspace rooms & channels appear
5. On B, close App
6. On A, remove B from the workspace
7. On B, re-open App
8. Verify that the workspace's rooms & channels does not disappear
**Workaround**
The rooms/channels only disappears when B clicks on each of them

## Expected Result:
The workspace's rooms/channels disappear immediately on App opening when he's previously removed from that workspace.

## Actual Result:
The workspace's rooms/channels does not disappear on App opening when he's previously removed from that workspace. Instead it requires manual navigation to each room/channel to be removed.

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [x] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 1.3.41-2
**Reproducible in staging?:** n/a
**Reproducible in production?:** n/a
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/93399543/f6316c06-43f4-4e2d-ad93-4357a77ccdec

**Expensify/Expensify Issue URL:**
**Issue reported by:** @tienifr 
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1689313795202979

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01c726371d1e861cb4</li>
        <li>Upwork Job ID: 1704756557394501632</li>
        <li>Last Price Increase: 2023-10-12</li>
    </ul>
</details>

**Comment by kbecciv** [comment] 2023-07-17 11:39
## Proposal
### Please re-state the problem that we are trying to solve in this issue.
User can still see the workspace chat even when he's removed from the workspace while he's offline.
### What is the root cause of that problem?
This problem doesn't happen before, that's because earlier the `OpenApp` API is called whenever we load the page again. This will populate all the policies and reports data, and will not show stale data.
However, after [this PR](https://github.com/Expensify/App/pull/18807), we no longer call `OpenApp` on page load for performance reason (because `OpenApp` fetches all the data so it's slow), we only call `ReconnectApp` if the user was already logged in before.
After the user is removed from the workspace and the user loads the page, the `ReconnectApp` only sends back "set workspace to null", not "set reports and reportActions related to this workspace to null" (as the Pusher will send if the user opens the app at the time).
So that's the root cause. This not only happens when the the user is removed from the workspace and the user loads the page, it also happens when the user is re-added to the workspace and loads the page, the default chat reports will not show (because it's not sent back in `ReconnectApp`)
### What changes do you think we should make in order to solve the problem?
1. We need to fix the back-end to return correct report and reportActions data in `ReconnectApp` for the following case:
- The user is removed from the workspace and the user loads the page: should set report and reportActions of the workspace-related reports to null.
- The user is re-added to the workspace and loads the page: should send workspace-related reports and reportActions data.
2. For existing users which have incorrect data in Onyx due to this, and to be future-proof, we can add logic in https://github.com/Expensify/App/blob/60f48175c9e3342ef192d878218820e5ed5a76cd/src/libs/ReportUtils.js#L2022 to return false if the report is associated to a workspace and that workspace is no longer available. This will work for both default rooms and user-created rooms.
### What alternative solutions did you explore? (Optional)
In 2, another solution is in the `Onyx.connect` for policy data, if we see the policy is set to null, we'll remove the associated report data from Onyx.

**Comment by sakluger** [comment] 2023-07-19 22:24
I couldn't reproduce this on the latest build, closing for now.

**Comment by sakluger** [comment] 2023-09-21 07:16
Reopening after watching @tienifr's more recent video recording.

https://github.com/Expensify/App/assets/5997400/4dff3561-bf73-4e04-93de-545fa67d322f

**Comment by burczu** [comment] 2023-09-25 12:27
For now I can't reproduce this issue due to the problem with workspace invitations described here: https://expensify.slack.com/archives/C049HHMV9SM/p1695627542846449 - I need to wait until it's resolved.

**Comment by burczu** [comment] 2023-09-27 08:32
I've finally reviewed [the proposal](https://github.com/Expensify/App/issues/23000#issuecomment-1637955540) from @kbecciv and I think it does make sense. In the proposal we need to update BE first so I think we should go `Internal` for now to get an opinion from the BE engineer.

cc: @sakluger

**Comment by sakluger** [comment] 2023-10-02 20:19
I've added the internal label on @burczu's recommendation. @marcochavezf are you able to work on the backend piece of this so that we can move forward with the external piece?

**Comment by marcochavezf** [comment] 2023-10-03 06:51
Sure, I will checking the backend implementation during the week. Seems it could be an edge case where we're not including the null reports in the `ReconnectApp` as stated in the proposal

**Comment by sakluger** [comment] 2023-10-05 06:06
@marcochavezf I'm not sure if you were just saying that you were happy to work on the backend piece, or if you were also endorsing a solution. Can you confirm if @tienifr's solution works?

**Comment by marcochavezf** [comment] 2023-10-05 19:21
Ah I mean that I can work on the backend piece. In this case I think the backend implementation should be done first.

**Comment by mvtglobally** [comment] 2023-10-12 03:49
Issue not reproducible during KI retests. (First week)

**Comment by sakluger** [comment] 2023-10-12 06:31
Interesting, sounds like this may have somehow gotten fixed. @marcochavezf any idea why it's not reproduceable anymore?

**Comment by marcochavezf** [comment] 2023-10-12 19:44
There have been many policy changes recently from other wave initiatives that probably fixed this by side effect, I think it's a good thing that's not reproducible anymore.

**Comment by marcochavezf** [comment] 2023-10-16 20:43
Not reproducible anymore

**Comment by sakluger** [comment] 2023-10-18 16:16
Okay then, closing!

**Closed by sakluger** 2023-10-18 16:16 UTC
Labels: External, Engineering, Daily, Internal, Needs Reproduction, Help Wanted, Bug
