### ISSUE TITLE
[Hold#15212][$500] Chat -The " new message" is not shown on top of the page after mark as unread an IOU

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#26760] opened 2023-09-05 11:46 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Go to https://staging.new.expensify.com/
2. Tap on a report with IOU conversation
3. Long press the IOU conversation
4. Tap Mark as Unread
5. Scroll up the page to note " new message"
6. Long press any text message
7. Tap Mark as Unread
8. Scroll up the page

## Expected Result:
After marking as unread an IOU, if user mark as unread any text message and scrolls up, the " new message" must be shown on top of the page

## Actual Result:
After marking as unread an IOU, if user mark as unread any text message and scrolls up, the " new message" is not shown on top of the page

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [ ] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 1.3.63-0

**Reproducible in staging?:** Y

**Reproducible in production?:** Y

**If this was caught during regression testing, add the test name, ID and link from TestRail:**

**Email or phone of affected tester (no customers):**

**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/78819774/7ce8237c-4fb7-4e18-81f6-9074b45dec1e

**Expensify/Expensify Issue URL:**

**Issue reported by:** Applause - Internal Team

**Slack conversation:**

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01bbc84cf35cbe2835</li>
        <li>Upwork Job ID: 1699077904760467456</li>
        <li>Last Price Increase: 2023-09-05</li>
    </ul>
</details>

**Comment by slafortune** [comment] 2023-09-07 17:17
Thanks @rmm-fl

**Comment by slafortune** [comment] 2023-09-08 17:37
assigning a new BZ member, I am out on sabbatical

**Comment by sonialiap** [comment] 2023-09-12 09:23
Still on hold for https://github.com/Expensify/App/issues/15212

**Comment by sonialiap** [comment] 2023-09-18 09:15
Still on hold for https://github.com/Expensify/App/issues/15212

**Comment by sonialiap** [comment] 2023-10-02 04:41
Still on hold for https://github.com/Expensify/App/issues/15212

**Comment by sonialiap** [comment] 2023-10-10 12:40
Still on hold for https://github.com/Expensify/App/issues/15212

**Comment by sonialiap** [comment] 2023-10-23 11:33
Still on hold for https://github.com/Expensify/App/issues/15212

**Comment by sonialiap** [comment] 2023-10-31 21:14
Still on hold for https://github.com/Expensify/App/issues/15212

**Comment by sonialiap** [comment] 2023-11-09 18:55
Still on hold for https://github.com/Expensify/App/issues/15212

**Comment by sonialiap** [comment] 2023-11-20 15:05
PR not live yet, will test after it's out https://github.com/Expensify/App/pull/25935

**Comment by MonilBhavsar** [comment] 2023-11-21 17:27
This issue should be fixed! We can retest and most probably close it

**Comment by sonialiap** [comment] 2023-12-01 15:15
I cannot reproduce, I think this is fixed, closing

**Closed by sonialiap** 2023-12-01 15:15 UTC
Labels: External, Weekly, Help Wanted, Overdue, Bug
