### ISSUE TITLE
[$1000] Wrong timezone is being highlighted in the select timezone list

### ISSUE THREAD

**Issue by kavimuru** [Expensify/App#14782] opened 2023-02-03 02:47 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Actions Performed:

1. Go to Settings > Profile > Timezone
2. Toggle off "Automatically determine your location."
3. Click on Timezone
4. Select "Africa/Accra"
5. Click on Timezone again
6. Type "Africa/Accra" in the search input
7. Clear the search input

## Expected Result:
Only the selected timezone is highlighted

## Actual Result:
Another timezone is being highlighted along with the selected one. Sometimes only the wrong timezone gets highlighted and sometimes, no timezone is highlighted.

## Workaround:
unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [x] iOS / native
- [ ] iOS / Safari
- [ ] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 1.2.64-1
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** 

https://user-images.githubusercontent.com/43996225/216500482-08407bae-b179-443a-83e8-aaaeca7025e1.mp4

https://user-images.githubusercontent.com/43996225/216500502-fb436ac6-1181-485b-a4ed-a91cab4f2274.mp4

**Expensify/Expensify Issue URL:**
**Issue reported by:** @adeel0202 
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1675374273944679

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~0150bd8a42a47a8c0a</li>
        <li>Upwork Job ID: 1621467748822253568</li>
        <li>Last Price Increase: 2023-02-03</li>
    </ul>
</details>

**Comment by garrettmknight** [comment] 2023-02-03 11:16
Confirmed on v1.2.64-4 on iOS. Couldn't reproduce on either web or MacOS.

![IMG_86F12432152A-1](https://user-images.githubusercontent.com/1529980/216589617-6f3862c3-572e-4098-8a31-de36142333f9.jpeg)

**Comment by s77rt** [comment] 2023-02-03 11:47
Can't reproduce on iOS Simulator (iPhone 14 - iOS 16.2)

https://user-images.githubusercontent.com/16493223/216595731-f9802165-5e6b-479b-b109-bd70d842f31c.mp4

**Comment by getusha** [comment] 2023-02-03 11:55
@s77rt 

https://user-images.githubusercontent.com/75031127/216597529-eaa15b33-6996-4b4e-8614-b0ef06aefc28.mov

**Comment by Pujan92** [comment] 2023-02-03 12:13
I am not able to reproduce after the latest pull, I think this [PR](https://github.com/Expensify/App/pull/14791) solved the issue.

**Comment by mountiny** [comment] 2023-02-03 12:20
Yes I think this can be closed, the PR most likely resolved this.

**Comment by bernhardoj** [comment] 2023-02-03 12:24
Even though the highlight issue is solved by the PR mentioned above, it still does not meet the expected result where the selected timezone should be highlighted when we are searching. The highlight always given to the first item. I'm giving my proposal here in case we want to reopen this issue 👍.

### **Proposal**

```diff
diff --git a/src/components/OptionsSelector/BaseOptionsSelector.js b/src/components/OptionsSelector/BaseOptionsSelector.js
index 903a767ee..18decaac4 100755
--- a/src/components/OptionsSelector/BaseOptionsSelector.js
+++ b/src/components/OptionsSelector/BaseOptionsSelector.js
@@ -105,7 +105,9 @@ class BaseOptionsSelector extends Component {
         }
 
         const newOptions = this.flattenSections();
-        const newFocusedIndex = this.props.selectedOptions.length;
+        const newFocusedIndex = this.props.canSelectMultipleOptions 
+            ? this.props.selectedOptions.length 
+            : this.getInitiallyFocusedIndex(newOptions);
         // eslint-disable-next-line react/no-did-update-set-state
         this.setState({
             allOptions: newOptions,
```
The issue is simply because every component update, the focused index is set to `this.props.selectedOptions.length` .

**Comment by mountiny** [comment] 2023-02-03 12:27
> it still does not meet the expected result where the selected timezone should be highlighted when we are searching. The highlight always given to the first item. I'm giving my proposal here in case we want to reopen this issue 👍.

confirming: Is the expected behaviour you mention how it worked before the PR/ and the PR which caused the regression?

**Comment by bernhardoj** [comment] 2023-02-03 12:39
Previously, the timezone select page never show a highlight. And then it is getting fixed by this [PR](https://github.com/Expensify/App/pull/14466). The PR also introduces, I think I can say a feature that will scroll to the selected timezone every time we open the page and also highlight it.

However, every time we do search, the highlight is always given to the first item and the selected timezone is not highlighted anymore and this issue is not related to this [PR](https://github.com/Expensify/App/pull/14791).

**Comment by mountiny** [comment] 2023-02-03 12:47
Can you please define this new bug then in #expensify-bugs? I am not sure if its clear now whats bug/ whats feature request after that fix was merged since it influences lots of places of the code.

**Comment by bernhardoj** [comment] 2023-02-03 13:03
Yup, that makes sense. Reported [here](https://expensify.slack.com/archives/C049HHMV9SM/p1675429188261199). Thank you!

**Comment by s77rt** [comment] 2023-02-03 13:05
@bernhardoj I think the expected results in the OP are not what we want. The current behaviour of highlight the first item is correct (so you can use arrow navigation). Following the expected results in the OP will break the search (i.e. you won't get any highlight if you search for any timezone other than the selected one) Unless I'm missing something?

**Comment by bernhardoj** [comment] 2023-02-03 13:07
When the selected timezone is not on the list, the highlight will be given to the first item. `getInitiallyFocusedIndex` will return 0 in this case.

**Comment by mountiny** [comment] 2023-02-03 16:28
@garrettmknight Yep sorry about that, I think the report was still valid although there could have been many as that regression has broken lots of places in the App 😄 

@garrettmknight would you be able to issue $250 for reporting this bug to @adeel0202  please? 🙇

**Comment by garrettmknight** [comment] 2023-02-06 12:03
Just paid @adeel0202 for reporting.

**Comment by garrettmknight** [comment] 2023-02-06 12:13
Done - will leave this open. @mountiny reopen if you still want to chat on this one.

**Closed by garrettmknight** 2023-02-06 12:13 UTC
Labels: External, Daily, Awaiting Payment, Bug
