### ISSUE TITLE
[$250] Intro message from Concierge continuous to load for a while

### ISSUE THREAD

**Issue by m-natarajan** [Expensify/App#41150] opened 2024-04-27 17:06 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.67-0
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** @danielrvidal 
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1714152087204729

## Action Performed:
1. Create a new account
2. Select an option in the welcome modal
3. Observe the intro message and video loading

## Expected Result:
Video and messages should load immediately

## Actual Result:

- The intro message from Concierge seems to be loading above the message that just got sent to the user
- Video is not loading quickly
- Takes ~ 10 seconds to load the messages 

## Workaround:
unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

https://github.com/Expensify/App/assets/38435837/29b1bf03-167f-4c2a-97ed-168cdac9e2a8

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01c283021ef1ff8514</li>
        <li>Upwork Job ID: 1785527540281253888</li>
        <li>Last Price Increase: 2024-06-12</li>
    </ul>
</details>

**Comment by JmillsExpensify** [comment] 2024-05-01 04:31
Expect this is a back-end issue, though opening up to the community as adding to wave-collect as polish.

**Comment by JmillsExpensify** [comment] 2024-05-15 03:15
Still waiting for proposals

**Comment by mananjadhav** [comment] 2024-05-19 17:29
Still waiting on proposals.

**Comment by mananjadhav** [comment] 2024-05-21 23:18
Still waiting on proposals.

**Comment by mananjadhav** [comment] 2024-05-26 19:06
Waiting for proposals. @JmillsExpensify do you want to tag someone from the agency to pick this or increase the bounty?

**Comment by mananjadhav** [comment] 2024-05-29 04:23
Quick bump @JmillsExpensify on the previous comment?

**Comment by mananjadhav** [comment] 2024-06-02 15:51
@m-natarajan Can you confirm if this is still reproducible? I can't seem to reproduce this anymore.

**Comment by mananjadhav** [comment] 2024-06-04 10:52
Waiting for an update on the retest here.

**Comment by mvtglobally** [comment] 2024-06-10 12:33
Issue not reproducible during KI retests. (First week)

**Comment by mananjadhav** [comment] 2024-06-11 21:20
@JmillsExpensify I think we can wait for one more week and then close this one out if not reproducible.

**Comment by JmillsExpensify** [comment] 2024-06-19 05:13
Going to close since QA wasn't able to reproduce.

**Closed by JmillsExpensify** 2024-06-19 05:13 UTC
Labels: External, Daily, Help Wanted, Overdue, Bug
