### ISSUE TITLE
[$500] HIGH: Distance Split - Distance is not interactable on split distance confirmation page

### ISSUE THREAD

**Issue by izarutskaya** [Expensify/App#33700] opened 2023-12-28 11:27 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** v1.4.18-3
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** Applause-Internal Team
**Slack conversation:** @

## Action Performed:
1. Go to workspace chat > + > Request money.
2. Go to Distance.
3. Enter addresses and proceed to confirmation page.
4. Click Distance.
5. Note that Distance is interactable on distance confirmation page.
6. Repeat Step 1 - 6 with Split bill in the context menu (to create split distance request).

## Expected Result:
Distance is interactable on split distance confirmation page.

## Actual Result:
Distance is not interactable on split distance confirmation page. It is grayed out.

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [x] Android: mWeb Chrome
- [x] iOS: Native
- [x] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

https://github.com/Expensify/App/assets/115492554/3072418a-af07-47b9-b3f6-2410d53d48e5

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~0101cbee32541ad090</li>
        <li>Upwork Job ID: 1740333601812893696</li>
        <li>Last Price Increase: 2024-01-11</li>
    </ul>
</details>

**Comment by FitseTLT** [comment] 2023-12-28 11:35
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
Distance is not interactable on split distance confirmation page

### What is the root cause of that problem?
It is because we are disabling it when it is not request iou type in confirmation page
### What changes do you think we should make in order to solve the problem?

We should remove that condition
### What alternative solutions did you explore? (Optional)

**Comment by DylanDylann** [comment] 2023-12-28 11:42
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
Distance is not interactable on split distance confirmation page. It is grayed out.

### What is the root cause of that problem?
In split bill, isTypeRequest will be false and isTypeSplit will be true
https://github.com/Expensify/App/blob/573f6b7005d67e5f8ec83e2efa64fb8d3b9902d2/src/components/MoneyTemporaryForRefactorRequestConfirmationList.js#L679-L680

It makes the distance field disable and isn't interactable
### What changes do you think we should make in order to solve the problem?

https://github.com/Expensify/App/blob/573f6b7005d67e5f8ec83e2efa64fb8d3b9902d2/src/components/MoneyTemporaryForRefactorRequestConfirmationList.js#L679

https://github.com/Expensify/App/blob/573f6b7005d67e5f8ec83e2efa64fb8d3b9902d2/src/components/MoneyTemporaryForRefactorRequestConfirmationList.js#L671

We should update condition to 
```
shouldShowRightIcon={!isReadOnly && (isTypeRequest || isTypeSplit)}
```

```
disabled={didConfirm || (!isTypeRequest && !isTypeSplit)}
```


### What alternative solutions did you explore? (Optional)
NA

**Comment by bernhardoj** [comment] 2023-12-28 12:21
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
When we try to create a distance request from the composer add action menu, the distance menu on the confirmation page is disabled.

### What is the root cause of that problem?
The distance menu on the confirmation page is disabled because we only enable it if it's a request type.
https://github.com/Expensify/App/blob/573f6b7005d67e5f8ec83e2efa64fb8d3b9902d2/src/components/MoneyTemporaryForRefactorRequestConfirmationList.js#L679

Currently, we only allow a distance request for request type only, not a split bill.
https://github.com/Expensify/App/blob/88d837c2e88c8c4c22a4c80f93b622d634e67290/src/pages/iou/request/MoneyTemporaryForRefactorRequestParticipantsSelector.js#L272

So, it makes sense that the button is disabled. The bug here is that the Distance tab shouldn't show when we do a split bill.

### What changes do you think we should make in order to solve the problem?

Hide the Distance tab when it's a split bill or show it only for request type.
https://github.com/Expensify/App/blob/88d837c2e88c8c4c22a4c80f93b622d634e67290/src/pages/iou/request/IOURequestStartPage.js#L100
```
const shouldDisplayDistanceRequest = iouType !== 'split' && (isExpenseChat || isExpenseReport || isFromGlobalCreate);
or
const shouldDisplayDistanceRequest = iouType === 'request' && (isExpenseChat || isExpenseReport || isFromGlobalCreate);
```

**Comment by dzakki** [comment] 2023-12-28 13:10
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
Distance is not interactable on split distance confirmation page. It is grayed out.

### What is the root cause of that problem?
the menu `distance` is grey out because the condition only checking `disabled={didConfirm || !isTypeRequest}`

https://github.com/Expensify/App/blob/88d837c2e88c8c4c22a4c80f93b622d634e67290/src/components/MoneyTemporaryForRefactorRequestConfirmationList.js#L679


### What changes do you think we should make in order to solve the problem?

we need to add the condition if the `isTypeSplit` too. it's mean if distance coming from split bill

`disabled={didConfirm || (!isTypeRequest && !isTypeSplit)}`

### What alternative solutions did you explore? (Optional)
-

**Comment by dzakki** [comment] 2023-12-28 13:13
Contributor details
Your Expensify account email: dzakkiaz7@gmail.com
Upwork Profile Link: https://www.upwork.com/freelancers/~01aa92cd4c91423d94

**Comment by jliexpensify** [comment] 2023-12-28 23:19
Hi @izarutskaya - can you please check your video? I don't think you've uploaded it properly, thanks!

**Comment by jliexpensify** [comment] 2023-12-28 23:23
Let Dylan know here: https://expensify.slack.com/archives/C05DWUDHVK7/p1703805792841859

**Comment by shubham1206agra** [comment] 2023-12-29 04:03
@jliexpensify What is the ideal behaviour here? 
Should we allow user to split distance request at all?
In FAB, we have not allowed to do the same. In my opinion, we should go with @bernhardoj's proposal, and disable the split distance request.

**Comment by jliexpensify** [comment] 2023-12-29 04:18
@shubham1206agra I've checked the #wave5 slack channel and it looks like Distance requests can be split cc @neil-marcellini @dylanexpensify if you have any further input?

**Comment by DylanDylann** [comment] 2023-12-29 04:28
@FitseTLT Please follow contributing guideline, You need to post a new comment to the issue when you edit your proposal.
https://github.com/Expensify/App/blob/main/contributingGuides/CONTRIBUTING.md#propose-a-solution-for-the-job

**Comment by shubham1206agra** [comment] 2023-12-29 04:38
> @shubham1206agra I've checked the #wave5 slack channel and it looks like Distance requests can be split cc @neil-marcellini @dylanexpensify if you have any further input?

I was just saying this as there is currently no support for distance split request in API (I think as it strips all distance info while creating the split request, and only amount is kept).

cc @tgolen as you are working on request refactoring PR.

**Comment by DylanDylann** [comment] 2023-12-29 05:19
@shubham1206agra  I think that distance split request API will be implemented in this issue  https://github.com/Expensify/App/issues/33698

**Comment by jliexpensify** [comment] 2024-01-02 02:03
Thanks @DylanDylann , can you let us know when that other issue is sorted?

**Comment by DylanDylann** [comment] 2024-01-02 06:18
> @shubham1206agra I've checked the #wave5 slack channel and it looks like Distance requests can be split cc

@shubham1206agra @jliexpensify If that, I think we should enable distance split requests in the scope of this issue. In FE we need to add `requestType` to the payload of API and require API changes to return correct data

**Comment by shubham1206agra** [comment] 2024-01-02 06:32
> @shubham1206agra I think that distance split request API will be implemented in this issue #33698

Nope this is not true. @jliexpensify Can you please post about this in internal channel so we can know whether to disable distance split or not?
if not, then can we have complete API calls for split request and start split request to correct for distance request?

**Comment by jliexpensify** [comment] 2024-01-03 02:47
Asked here, will keep you updated! https://expensify.slack.com/archives/C05DWUDHVK7/p1704250033812399?thread_ts=1703805792.841859&cid=C05DWUDHVK7

**Comment by jliexpensify** [comment] 2024-01-05 01:12
@DylanDylann @neil-marcellini - [did you have any thoughts on this question](https://github.com/Expensify/App/issues/33700#issuecomment-1873660242)? I didn't get an answer in my thread, cheers!

I think this is blocking the proposal review atm.

**Comment by DylanDylann** [comment] 2024-01-05 01:15
@jliexpensify It seems you tagged @dylanexpensify 😄

**Comment by jliexpensify** [comment] 2024-01-05 02:18
Ha whoops sorry!

**Comment by jliexpensify** [comment] 2024-01-05 09:59
@shubham1206agra - @dylanexpensify has confirmed that we should be able to split Distance requests.

>then can we have complete API calls for split request and start split request to correct for distance request?

Could you clarify what you're asking in this second part? (I'm not an Engineer)

**Comment by shubham1206agra** [comment] 2024-01-05 10:09
Can I get `StartSplitBill`, and `SplitBill` API param related to split distance bill? I suspect that it is missing in BE too. Maybe take this internal to get some eyes on this by internal team.

cc @dylanexpensify @neil-marcellini

**Comment by shubham1206agra** [comment] 2024-01-11 16:03
@jliexpensify Bump on the above question

**Comment by jliexpensify** [comment] 2024-01-12 02:06
@shubham1206agra sorry for the delay, was OOO.

>then can we have complete API calls for split request and start split request to correct for distance request?

By "we", do you mean a Contributor or C+?

> Can I get StartSplitBill, and SplitBill API param related to split distance bill? 

Just to confirm, this is an access issue?

> I suspect that it is missing in BE too.

Sorry, what is `BE`?

Apologies if these are dumb questions, I'm not an Engineer and want to make sure I'm communicating your requests correctly.

**Comment by shubham1206agra** [comment] 2024-01-12 05:07
> > then can we have complete API calls for split request and start split request to correct for distance request?
> 
> By "we", do you mean a Contributor or C+?

In general, as we may want to know the API parameter.

> > Can I get StartSplitBill, and SplitBill API param related to split distance bill?
> 
> Just to confirm, this is an access issue? i.e. these are internal things you need access to? If so, should this be `Internal` instead?

We can make internal to get the parameters

> > I suspect that it is missing in BE too.
> 
> Sorry, what is `BE`?

I mean backend.

Adding 🎀👀🎀 for an engineer to help here.

**Comment by jliexpensify** [comment] 2024-01-15 05:04
The answers have been shared internally, just awaiting a response .ghanks for your patience @shubham1206agra!

**Comment by mountiny** [comment] 2024-01-15 11:16
I believe @neil-marcellini is back from ooo today and he has more context on this than anyone else so in sake of saving time I will just leave this over to him as he is already assigned

**Comment by jliexpensify** [comment] 2024-01-16 03:50
Had a chat with Neil, we're going to close this one! We'd like to wait until P2P distance requests (including split) are implemented, thanks.

**Closed by jliexpensify** 2024-01-16 03:50 UTC
Labels: External, Daily, Help Wanted, Bug, Distance

**Comment by shubham1206agra** [comment] 2024-01-16 05:43
@jliexpensify Can you close https://github.com/Expensify/App/issues/33673 https://github.com/Expensify/App/issues/33698 too as they have the same problem?

**Comment by jliexpensify** [comment] 2024-01-17 00:12
Posted and tagged you in both issues
