### ISSUE TITLE
[$250] Web - Multiple emojis are selected and added in compose box  when selecting emoji's via keyboard reported by @aneequeahmad

### ISSUE THREAD

**Issue by kavimuru** [Expensify/App#11438] opened 2022-09-29 18:31 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:

1. Open new.expensify.com.
2. Compose box will be auto focused.
3. Press tab 1 time(Emoji picker will get focus)
4. Press enter/return key to open Emoji picker
5. Search will get focus (autFocused)
6. Press tab 1 time (First emoji will get focus).
7. Press right arrow (->) key 3 times.
8. Press enter to select grey highlighted emoji.

## Expected Result:
One emoji where enter is pressed should be selected

## Actual Result:
Multiple emojis are selected (First emoji and the selected emoji)

## Workaround:
Unknown

## Platform:

Where is this issue occurring?

- Web

**Version Number:** 1.2.9-0
**Reproducible in staging?:** Needs reproduction
**Reproducible in production?:** Needs reproduction
**Email or phone of affected tester (no customers):** 
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** 

https://user-images.githubusercontent.com/43996225/193113918-d25fc3da-5985-45aa-a0e8-d75a1f17dd7e.mov

**Expensify/Expensify Issue URL:** 
**Issue reported by:** @aneequeahmad
**Slack conversation:** https://expensify.slack.com/archives/C01GTK53T8Q/p1663325527878289

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by tjferriss** [comment] 2022-10-19 16:46
I'm not able to reproduce this one on web staging (v1.2.18-2). I'm navigating the emoji selector with the keyboard and can select one emoji at a time.

**Comment by tjferriss** [comment] 2022-10-21 22:23
@kavimuru are you still able to reproduce this?

**Comment by kavimuru** [comment] 2022-10-21 23:55
@tjferriss I am still not able to reproduce. @aneequeahmad are you able to reproduce?

**Comment by aneequeahmad** [comment] 2022-10-21 23:58
@kavimuru, @tjferriss I can still reproduce this issue on production. 

Video: (Recorded just now)

https://user-images.githubusercontent.com/36359331/197306414-ad5542c0-76a9-4db2-9a2d-33d057bc46b3.mov

**Comment by aneequeahmad** [comment] 2022-10-22 00:05
### Action Performed: (Detailed)

- Open new.expensify.com.
- Compose box will be auto focused.
- Press tab 1 time(`Emoji picker` will get focus)
- Press enter/return key to open `Emoji picker`
- Search will get focus (autFocused)
- Press tab 1 time (First emoji will get focus).
- Press right arrow (->) key 3 times.
- Press enter to select grey highlighted emoji.


cc: @kavimuru

**Comment by aneequeahmad** [comment] 2022-10-22 00:05
Let me know if these detailed action performed work or not.

**Comment by tjferriss** [comment] 2022-10-25 20:36
Got it. I'm able to reproduce the bug. Thank you for the detailed steps. I've added these to the original post and added the `External` label.

**Comment by tjferriss** [comment] 2022-10-25 20:39
Upworks job posting is now live:
- https://www.upwork.com/jobs/~01c784eac1e6286898

**Comment by eVoloshchak** [comment] 2022-10-26 16:28
### Proposal

**Root cause**
When the user selects a different emoji using arrows, the selection of the first emoji doesn't get discarded.
So when user presses `Enter`, two listeners get called:

- [this.keyDownHandler](https://github.com/Expensify/App/blob/e263ffa9f69e696790547bca4bf93d3864da90c4/src/components/EmojiPicker/EmojiPickerMenu/index.js#L160) (which is the correct behavior) for the emoji you've selected with arrows
- EmojiPickerMenuItem's [onPress handler](https://github.com/Expensify/App/blob/e263ffa9f69e696790547bca4bf93d3864da90c4/src/components/EmojiPicker/EmojiPickerMenu/index.js#L441) (which is incorrect) fot the emoji with native selection, with the blue outline. 

**Solution**
After opening emoji picker user can press `Tab` button once, which will select the first emoji, after that the tab button becomes unusable. Pressing it does nothing, you can't select the next emoji, and you can't go back the search input.

This means that we have a simple solution of just disabling the `Tab` button on emoji picker
https://github.com/Expensify/App/blob/e263ffa9f69e696790547bca4bf93d3864da90c4/src/components/EmojiPicker/EmojiPickerMenu/index.js#L148

```js
if (keyBoardEvent.key === 'Tab') {
    keyBoardEvent.preventDefault();
    return;
}
```

Or we could select the next emoji when `Tab` button is pressed
```js
if (keyBoardEvent.key === 'Tab') {
    keyBoardEvent.preventDefault();
    if (this.state.isFocused) {
        this.searchInput.blur();
    }
    this.highlightAdjacentEmoji('ArrowRight');
    return;
}
```


https://user-images.githubusercontent.com/9059945/198082023-83c9e838-01d0-441a-bcb1-327a1dc01415.mov

**Comment by eVoloshchak** [comment] 2022-10-30 18:30
> what happens when `Shift + Tab` is pressed?

Same thing as when just the Tab is pressed: the next emoji is selected. 
We can change this by accessing  `keyBoardEvent. shiftKey`

What should happen on `Shift + Tab`?

**Comment by eVoloshchak** [comment] 2022-10-30 19:16
**Updated proposal**
https://github.com/Expensify/App/blob/e263ffa9f69e696790547bca4bf93d3864da90c4/src/components/EmojiPicker/EmojiPickerMenu/index.js#L148
```js
if (keyBoardEvent.key === 'Tab') {
    keyBoardEvent.preventDefault();

    if (keyBoardEvent.shiftKey) {
        if (this.state.highlightedIndex >= this.firstNonHeaderIndex) {
            this.searchInput.blur();
            this.highlightAdjacentEmoji('ArrowLeft');
        }

        // this means we have only the search input selected, so do nothing
        return;
    }

    this.searchInput.blur();
    this.highlightAdjacentEmoji('ArrowRight');
    return;
}
```




https://user-images.githubusercontent.com/9059945/198897281-7f535854-2b2b-46d7-97e8-ebfa132e1ed4.mov

**Comment by tjferriss** [comment] 2022-11-01 22:13
@rushatgabhane what do you think of the new proposal?

**Comment by arielgreen** [comment] 2022-11-03 20:24
Hey @rushatgabhane, can you prioritize getting this proposal reviewed today? Let's keep the momentum up to get this one closed out!

**Comment by eVoloshchak** [comment] 2022-11-03 21:25
According to [this comment](https://github.com/Expensify/App/issues/12043#issuecomment-1297594923)
> I think just skipping over emojis for the tabbing behavior would be the simplest solution. Feels like we are greatly exaggerating the importance of being able to tab to the emojis 

When `Tab` is disabled for emoji navigation, it won't be possible to reproduce this issue

**Comment by eVoloshchak** [comment] 2022-11-04 20:50
Looks like discussion is still ongoing in https://github.com/Expensify/App/issues/12043

**Comment by tjferriss** [comment] 2022-11-04 22:32
@eVoloshchak to clarify your comment, do you expect the proposed solution here would resolve the related issue https://github.com/Expensify/App/issues/12043. If so, it seems like we should close that issue and consolidate everything here. cc @maddylewis @marcaaron

**Comment by stitesExpensify** [comment] 2022-11-07 16:12
bump on that ^ question @eVoloshchak

**Comment by eVoloshchak** [comment] 2022-11-07 16:27
> @eVoloshchak to clarify your comment, do you expect the proposed solution here would resolve the related issue #12043. 

Yes, this [proposal](https://github.com/Expensify/App/issues/11438#issuecomment-1303982359) will also resolve `#12043` 
 
>If so, it seems like we should close that issue and consolidate everything here


 I feel like it's the other way around and we should close this one and keep #12043 open, but that doesn't really matter, we could just edit the title and description on this one

**Comment by stitesExpensify** [comment] 2022-11-07 20:35
I agree. There is significantly more discussion and the issue is worth more. It was also found by the same contributor.

Closing in favor of https://github.com/Expensify/App/issues/12043

**Closed by stitesExpensify** 2022-11-07 20:35 UTC
Labels: External, Daily, Help Wanted, Bug
