### ISSUE TITLE
[$250] IOU - Upload receipt with PDF file showing error

### ISSUE THREAD

**Issue by izarutskaya** [Expensify/App#39967] opened 2024-04-09 20:14 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** v1.4.61-5
**Reproducible in staging?:** Y
**Reproducible in production?:** N
**Email or phone of affected tester (no customers):** nhut.nguyenminh.it+2@gmail.com
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Issue reported by:** Applause-Internal team

## Action Performed:
1. Open the app
2. Go to any conversation and have a owed message
3. Tap on the detail
4. Create new request money
5. Tap on it
6. Tap on upload file
7. Choose a PDF

## Expected Result:
Upload receipt with PDF file success

## Actual Result:
Upload receipt with PDF file showing error

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

https://github.com/Expensify/App/assets/115492554/721cbf33-e6ed-4ce6-b071-638d6f9de15b

https://github.com/Expensify/App/assets/115492554/08164d14-dfa7-4039-add0-f19488f01ce6

<img width="1920" alt="Bug6437567_1712205935305!Screenshot_2024-04-04_at_11 17 00" src="https://github.com/Expensify/App/assets/115492554/d288b618-d6c9-4f42-9b05-8099279b80ec">

[Bug6437567_1712228124996!Invoice-06B4F79B-0002.pdf](https://github.com/Expensify/App/files/14923449/Bug6437567_1712228124996.Invoice-06B4F79B-0002.pdf)

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~014b85bb01634d9a91</li>
        <li>Upwork Job ID: 1777801709975195648</li>
        <li>Last Price Increase: 2024-04-09</li>
    </ul>
</details>

**Comment by izarutskaya** [comment] 2024-04-09 20:18
We think this issue might be related to the #collect project.

**Comment by izarutskaya** [comment] 2024-04-09 20:23
Production 


https://github.com/Expensify/App/assets/115492554/724505ab-5249-4d4f-a8b6-a69b1c20ac82

**Comment by mountiny** [comment] 2024-04-09 20:52
Making this external to get more eyes onto it

**Comment by neil-marcellini** [comment] 2024-04-09 20:59
Just seeing this now 👀

**Comment by neil-marcellini** [comment] 2024-04-09 21:06
I'm not able to reproduce this problem on staging. @izarutskaya would you please provide the specific problematic PDF. I'm going to close the issue for now since it doesn't seem to be a general problem.


https://github.com/Expensify/App/assets/26260477/705e23e9-f81d-4226-9103-666d1abc9e16

**Closed by neil-marcellini** 2024-04-09 21:06 UTC
Labels: DeployBlockerCash, External, Engineering, Hourly, Help Wanted, Bug

**Comment by mountiny** [comment] 2024-04-09 21:15
it worked for me too now
