### ISSUE TITLE
[$250] Inbox - Notification dot, keeps displaying in inbox icon despite having read all chats

### ISSUE THREAD

**Issue by izarutskaya** [Expensify/App#44686] opened 2024-07-01 15:50 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** v9.0.1-19
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**Email or phone of affected tester (no customers):** bellicoignacio@gmail.com
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Issue reported by:** Applause-Internal team

## Action Performed:
1. Open the https://staging.new.expensify.com/
website.
2. Tap on the "+" icon.
3. Tap on "Submit Expense"
4. Complete with the expense amount.
5. Tap on "Next"
6. Choose a person to add to the expense.
7. Tap on "Save"
8. Tap on the arrow on the top left corner.
9. Check the red dot displayed in the inbox icon.
10. Open the last chat again.
11. Tap on the arrow on the top left corner.
12. Check if the red dot is still displayed.

## Expected Result:
Notifications red dot, should disappear from the inbox icon, after the user finishes reading all the new messages on any chat.

## Actual Result:
Notifications red dot, doesn´t disappear from the inbox icon, despite not being any new message or notification. The only way to make it disappear, is by signing out and logging in again.

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [x] Android: mWeb Chrome
- [ ] iOS: Native
- [x] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

https://github.com/Expensify/App/assets/115492554/893928b9-f58b-4c98-a0ab-b2ce2a629fda

![Bug6517806_1718747093588!Dot](https://github.com/Expensify/App/assets/115492554/e7f72514-f7d6-4e99-a661-fe8abddc4c55)

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01e767530fde5ec943</li>
        <li>Upwork Job ID: 1809011507310295725</li>
        <li>Last Price Increase: 2024-08-08</li>
<li>Automatic offers: </li>
<ul>
<li>dukenv0307 | Contributor | 103412295</li>
</ul></li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @dukenv0307</details>

**Comment by RachCHopkins** [comment] 2024-07-01 21:51
@izarutskaya is there any unread number in the browser tab on Chrome, to go with the unread indicator?

![image](https://github.com/Expensify/App/assets/32854888/b877204f-086b-454b-9713-e6179b6960d6)

**Comment by RachCHopkins** [comment] 2024-07-04 06:08
Sorry, I just learned not to tag QA. That would be good to know, but not essential!

**Comment by atrgouti** [comment] 2024-07-05 03:48
there are so many reasons that can lead to this problem. Since signing out and logging back in fixes the issue temporarily, investigate the session management logic to ensure it correctly initializes the notification state. For example, verify that the session state is correctly cleared and reinitialized upon login.

here are other things that I will do in this situation to fix it:

1. Review Notification State Management: I would ensure that the state management (I don't know what you are using, maybe Redux or Context API) correctly updates when a message is read. I would try to use the React Developer Tools to toggle the state and see if it changes the button.
2. Inspect API calls: If you are using REST API, I would check the endpoint that marks messages as read and ensure it returns the correct status. Sometimes bugs can be there. It is also important to look into the API calls made when a message is marked as read. Ensure the backend correctly acknowledges the read status and that this is reflected in the response.
3. Handle response correctly: I would ensure that the frontend handles the response from the server correctly. Make sure to use try and catch. It would be something like this:
markMessageAsRead(messageId).then(response => {
    if (response.status === 200) {
        // Update state to reflect the message as read
        dispatch(updateReadStatus(messageId));
    }
}).catch(error => {
    console.error("Error marking message as read:", error);
});
4. Check the notification logic: Sometimes we make mistakes even on small and easy things, so I would review the logic that determines whether the red dot is shown or not and ensure that it accurately reflects the state of unread messages.
5. Check local store: Use the following code:
localStorage.setItem('unreadMessages', JSON.stringify(updatedUnreadMessages));
and check if the read status is being cached or stored locally and ensure it is updated correctly when messages are read.

**Comment by atrgouti** [comment] 2024-07-05 03:51
Contributor details
Your Expensify account email: btrgouti@gmail.com
Upwork Profile Link: https://www.upwork.com/freelancers/~017d973ca5ca9bd8ba

**Comment by nkdengineer** [comment] 2024-07-05 04:48
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
Notifications red dot, doesn´t disappear from the inbox icon, despite not being any new message or notification. The only way to make it disappear, is by signing out and logging in again.

### What is the root cause of that problem?
In https://github.com/Expensify/App/blob/74a6dbba2105ceba086f0387f50dcad573d4569f/src/pages/iou/request/step/withWritableReportOrNotFound.tsx#L69, we call `openReport` if there's reportID in the param but no report data.

So when submitting expense, in draft state, we generate a random report id [here](https://github.com/Expensify/App/blob/74a6dbba2105ceba086f0387f50dcad573d4569f/src/pages/home/sidebar/SidebarScreen/FloatingActionButtonAndPopover.tsx#L400), so this trigger `openReport` above that returns error because that report doesn't exist in back-end.

When there's error on any report, it will show RBR in the chat tab https://github.com/Expensify/App/blob/74a6dbba2105ceba086f0387f50dcad573d4569f/src/libs/WorkspacesSettingsUtils.ts#L112

### What changes do you think we should make in order to solve the problem?

We should have a way to indicate that the report is a draft report and will not `openReport` [here](https://github.com/Expensify/App/blob/74a6dbba2105ceba086f0387f50dcad573d4569f/src/pages/iou/request/step/withWritableReportOrNotFound.tsx#L69) if so.
There're a few ways to do this:
1. Add another param `isDraftReport` to the IOU-related path, if `isDraftReport` is true, early return here https://github.com/Expensify/App/blob/74a6dbba2105ceba086f0387f50dcad573d4569f/src/pages/iou/request/step/withWritableReportOrNotFound.tsx#L65
2. Create a `REPORT_DRAFT` for the draft report id generated (we did same for draft workspace [here](https://github.com/Expensify/App/blob/74a6dbba2105ceba086f0387f50dcad573d4569f/src/libs/actions/Policy/Policy.ts#L1780)), then clear that draft report in success data once the report and money request are created. If the report is draft, in [here](https://github.com/Expensify/App/blob/74a6dbba2105ceba086f0387f50dcad573d4569f/src/pages/iou/request/step/withWritableReportOrNotFound.tsx#L65) has condition to early return.

### What alternative solutions did you explore? (Optional)
NA

**Comment by abdulrahuman5196** [comment] 2024-07-08 20:05
Hi, I have lesser availability at the moment. So I am unassigning myself.

@RachCHopkins Kindly re-add the labels for another C+.

**Comment by nkdengineer** [comment] 2024-07-16 02:39
@RachCHopkins Can you please assign a new C+ to review this issue?

**Comment by mvtglobally** [comment] 2024-07-19 03:23
Issue not reproducible during KI retests. (First week)

**Comment by nkdengineer** [comment] 2024-07-24 06:42
@RachCHopkins Can you please check my comment here, thanks.

**Comment by RachCHopkins** [comment] 2024-08-06 04:50
@dukenv0307 sorry for the delay, thanks for the ping in slack! Testers say this is not reproducible anymore, and my own unreads seem ok. We may need to make sure it's definitely still a problem.

**Comment by aldo-expensify** [comment] 2024-08-06 18:09
hmmm, so the original issue is not reproducible, correct?

If we wanted to fix the multiple `OpenReport` calls with an invalid reportID, I think I like more the [alternative solution](https://github.com/Expensify/App/issues/44686#issuecomment-2210158174) because of its simplicity (no idea if it could cause an unforeseen bug though. Also, I think it may be cleaner to report and create a new issue for this problem? since it is very different to what is reported in this issue.

**Comment by nkdengineer** [comment] 2024-08-13 03:07
@RachCHopkins @dukenv0307  Recently, I'm working on this [PR](https://github.com/Expensify/App/pull/47212) that will prevent `OpenReport` API is called with an invalid `reportID`. I think we can close this issue now and no need to create a new issue.

cc @aldo-expensify

**Comment by aldo-expensify** [comment] 2024-08-14 01:27
Thanks @nkdengineer , closing then

**Closed by aldo-expensify** 2024-08-14 01:27 UTC
Labels: External, Weekly, Bug
