### ISSUE TITLE
[$500] Web - Pay with Expensify button for approved request disappears after VBA added

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#35721] opened 2024-02-02 20:57 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.36-0
**Reproducible in staging?:** y
**Reproducible in production?:**
**If this was caught during regression testing, add the test name, ID and link from TestRail:** https://expensify.testrail.io/index.php?/tests/view/4278917&group_by=cases:section_id&group_order=asc&group_id=296773
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** Applause - Internal Team
**Slack conversation:**

## Action Performed:
Precondition: Before reproduce, do this TRs:
1) https://expensify.testrail.io/index.php?/cases/view/2778074
2) https://expensify.testrail.io/index.php?/cases/view/2778075
3) https://expensify.testrail.io/index.php?/cases/view/2778077
4) Do Preconditions for https://expensify.testrail.io/index.php?/cases/view/2778078
1. As the admin - navigate to the workspace chat with the employee
2. Button is displayed as "Pay with Expensify" in the report preview of the report that was approved
3. Click on the report preview to navigate to the report conversation

## Expected Result:
The option to "Pay with Expensify" is displayed in the header

## Actual Result:
The option to "Pay with Expensify" is briefly displayed in the header and disappears.

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

https://github.com/Expensify/App/assets/93399543/9f353066-0775-474f-81f4-1fce0ebb058d

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01ac45cee2af607ba3</li>
        <li>Upwork Job ID: 1753523096410824704</li>
        <li>Last Price Increase: 2024-02-09</li>
<li>Automatic offers: </li>
<ul>
<li>hoangzinh | Reviewer | 0</li>
</ul></li>
    </ul>
</details>

**Comment by abekkala** [comment] 2024-02-06 20:08
Verifying if this is wave 6 [here](https://expensify.slack.com/archives/C02MW39LT9N/p1707250098437439)****

**Comment by abekkala** [comment] 2024-02-09 18:42
https://expensify.slack.com/archives/C03UK30EA1Z/p1707504123922889

**Comment by teneeto** [comment] 2024-02-13 07:22
Hi, I'm Eto from Callstack - expert contributor group - and I would like to take care of this issue.

**Comment by abekkala** [comment] 2024-02-13 14:26
Thanks @teneeto

**Comment by abekkala** [comment] 2024-02-14 20:21
@teneeto 
https://expensify.testrail.io/index.php?/cases/view/2778074
Employee - Collect Workspace chat is displayed after first login

<img width="957" alt="Screenshot 2024-02-14 at 2 20 39 PM" src="https://github.com/Expensify/App/assets/11966460/0621e7e3-aba6-4d82-92a5-58fe6f1b9b2d">

**Comment by abekkala** [comment] 2024-02-14 20:22
https://expensify.testrail.io/index.php?/cases/view/2778075
Employee - Approve button is not displayed for employee
<img width="823" alt="Screenshot 2024-02-14 at 2 21 39 PM" src="https://github.com/Expensify/App/assets/11966460/4d966dae-c4fc-440a-9aaf-545027f14cba">

**Comment by abekkala** [comment] 2024-02-14 20:22
https://expensify.testrail.io/index.php?/cases/view/2778077
Admin - Approve report - Status is updated
<img width="860" alt="Screenshot 2024-02-14 at 2 22 58 PM" src="https://github.com/Expensify/App/assets/11966460/d2a71cf2-cc23-41c4-bee0-08efff79336f">

**Comment by abekkala** [comment] 2024-02-14 20:23
https://expensify.testrail.io/index.php?/cases/view/2778078
Admin - Pay report with Expensify - Employee doesn't have BA
<img width="956" alt="Screenshot 2024-02-14 at 2 23 52 PM" src="https://github.com/Expensify/App/assets/11966460/b20a6df4-9614-48c4-bc36-43847ab57c18">

**Comment by abekkala** [comment] 2024-02-19 21:19
@teneeto do you have a timeframe for the PR?

**Comment by teneeto** [comment] 2024-02-20 09:10
Hi @abekkala, I believe we can clear this out on or before the weekend. I will be sure to attend to a few other reviews, and then come back to this.

**Comment by abekkala** [comment] 2024-02-21 21:42
@teneeto thanks for the update!

**Comment by abekkala** [comment] 2024-02-23 16:00
@teneeto is there a PR ready for this one?

**Comment by abekkala** [comment] 2024-02-26 17:04
@teneeto do you have an update here? or a PR to link?

**Comment by teneeto** [comment] 2024-02-27 16:06
Hi @abekkala, Apologies for missing updates here. I couldn't complete this at the time earlier promised. But I'll push for a PR tomorrow. Had some delays with reproducing this earlier.

**Comment by teneeto** [comment] 2024-02-29 01:48
> https://expensify.testrail.io/index.php?/cases/view/2778078 Admin - Pay report with Expensify - Employee doesn't have BA <img alt="Screenshot 2024-02-14 at 2 23 52 PM" width="956" src="https://private-user-images.githubusercontent.com/11966460/304865778-b20a6df4-9614-48c4-bc36-43847ab57c18.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDkxNjY2NjgsIm5iZiI6MTcwOTE2NjM2OCwicGF0aCI6Ii8xMTk2NjQ2MC8zMDQ4NjU3NzgtYjIwYTZkZjQtOTYxNC00OGM0LWJjMzYtNDM4NDdhYjU3YzE4LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAyMjklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMjI5VDAwMjYwOFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWI2OWFkNGNhZWY2MWNkZjVhYjhjODM5M2NhODQyZmExZTFlZDQ4NjM3YzU4YzY1YmQ1YjYxY2JhZTNiNmE2NzUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.M75kd8TfivMSLgCJPndYd19TQgc2URJ-c56fMkdm7lM">

The bank account here doesn't work for me. Is there another?

**Comment by teneeto** [comment] 2024-02-29 04:38
Hi @abekkala 

From my Findings `shouldShowPayButton` button has a condition called `isAutoReimbursable`. That condition is the reason why the `Pay with Expensify` button disappears.
https://github.com/Expensify/App/blob/3e74ddf0d2b408faa270ff243cf333065b177a87/src/components/MoneyReportHeader.tsx#L79-L82

**Investigating Further:**
This PR:  https://github.com/Expensify/App/pull/33987 is deliberate and responsible to Hide pay button when auto reimbursement is enabled.
This was included here: https://github.com/Expensify/App/pull/33987/files#diff-5163bae465a2e5449c9b49bd5a38af413a2b3f8b8cf0e3ed81552dba2899215fL68-R70

### Possible Solution
removing `isAutoReimbursable` condition.

### Discussion
This rather seem to be a future than a bug, can we check to confirm if this PR: https://github.com/Expensify/App/pull/33987 is valid?.

**Comment by teneeto** [comment] 2024-02-29 04:45
@marcochavezf I'm mentioning you here for clarity sake. any thoughts on my last comment?

**Comment by teneeto** [comment] 2024-03-01 08:52
@abekkala and Yes!, I simply removed the default `reimbursement` amount, which was `$100` and the button showed up again.

**Comment by marcochavezf** [comment] 2024-03-01 20:11
Yes, that's correct, we're not showing the Pay button if the policy has auto-reimbursement enabled. We can close it out.

**Closed** 2024-03-01 21:32 UTC
Labels: Engineering, Daily, Internal, Bug
