### ISSUE TITLE
[HOLD for payment 2024-09-12][Search v2.1] Workspace selected in workspace switcher resets to Expensify after switching status/tab

### ISSUE THREAD

**Issue by IuliiaHerets** [Expensify/App#48240] opened 2024-08-29 07:43 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 9.0.26-1
**Reproducible in staging?:** Y
**Reproducible in production?:** N
**Email or phone of affected tester (no customers):** applausetester+kh270803a@applause.expensifail.com
**Issue reported by:** Applause Internal Team

## Action Performed:
Precondition:
- Account has at least one workspace.

1. Go to staging.new.expensify.com
2. Go to Search.
3. Open workspace switcher.
4. Select a workspace.
5. Go to different status.
6. Note that the workspace switcher changes to Expensify.
7. Open workspace switcher.
8. Note that the selected workspace persists but the breadcrumbs show Expensify.
9. Refresh Search page.
10. Open workspace switcher and select another workspace.
11. Go to different tab (Invoices or Trips).
12. Note that the workspace switcher resets to Expensify.

## Expected Result:
In Step 8 and 12, the workspace selected in the workspace switcher should persist.

## Actual Result:
In Step 8 and 12, the workspace selected in the workspace switcher resets to Expensify after switching to another status or tab.

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [ ] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

https://github.com/user-attachments/assets/47e77514-9c77-4579-85e7-03cebfd34bc4

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Issue Owner</summary>Current Issue Owner: @Kicu</details>

**Comment by IuliiaHerets** [comment] 2024-08-29 07:44
We think that this bug might be related to #wave-control

**Comment by Kicu** [comment] 2024-08-29 12:28
I believe it was agreed with @luacmartins that this:

> Go to different tab

is not a bug, as our expectation is that clicking on a tab resets all filters, which should include resetting `policyID` in the switcher. 
The bug is wrong state of switcher and I will provide a fix for it. Please assign me to this task

**Comment by luacmartins** [comment] 2024-08-29 15:01
Yea, this is not a bug (at least not yet) since we reset all filters when moving to different state/statuses.

**Comment by lanitochka17** [comment] 2024-08-29 17:15
The selected workspace in the workspace switcher list and the breadcrumbs don't match after the reset
Cannot select the same workspace even though it has a green checkmark.


https://github.com/user-attachments/assets/ad9b2670-4ea8-4bc1-af85-4e7dbf939513

**Comment by luacmartins** [comment] 2024-08-29 17:38
cc @Kicu ^

**Comment by Kicu** [comment] 2024-08-30 08:01
I'm working today on this specific bug that selected workspace doesn't match.

While it looks like a minor thing it is tightly connected to my `policyID` PR: https://github.com/Expensify/App/pull/47787 and I treat it like a bug of how we pass `policyID` around between query, params and ws switcher.

Will be fixed

**Comment by Kicu** [comment] 2024-09-02 12:26
Fix available here: https://github.com/Expensify/App/pull/48403

**Comment by luacmartins** [comment] 2024-09-06 19:32
The PR was deployed to prod yesterday

**Comment by luacmartins** [comment] 2024-09-12 19:18
Payment due today

**Comment by luacmartins** [comment] 2024-09-17 01:15
Bump for payment @anmurali

**Comment by luacmartins** [comment] 2024-09-23 00:33
@anmurali Bump for payment

**Comment by anmurali** [comment] 2024-09-25 01:34
Sent @rayane-djouah an offer [here](https://www.upwork.com/nx/wm/offer/104116134)
@Kicu I need your upwork profile.

**Comment by Kicu** [comment] 2024-09-25 06:35
@anmurali I work at SWM (expert agency) so no payment is required for me :)

**Comment by luacmartins** [comment] 2024-10-01 01:31
Just pending payment to @rayane-djouah

**Comment by anmurali** [comment] 2024-10-05 20:46
Done.

**Closed by anmurali** 2024-10-05 20:46 UTC
Labels: Engineering, Daily, Overdue, Awaiting Payment, Bug
