### ISSUE TITLE
[HOLD for payment 2024-02-20] [$500]  Chat – Message draft created Offline disappears while go back Online and refresh page

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#34667] opened 2024-01-17 20:41 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.26-1
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** Applause - Internal Team
**Slack conversation:**

## Action Performed:
1. Go to https://staging.new.expensify.com/
2. Log in
3. Go Offline
4. Open any chat and draft a message in it
5. Go back Online (not focus on the chat) refresh the page

## Expected Result:
The conversation is still displayed to the top of LHN (maintaining the same drafted status)
The drafted message is still displayed in the compose box

## Actual Result:
The conversation is not displayed to the top of LHN (not maintaining the same drafted status)
The drafted message is not displayed in the compose box

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details> 

https://github.com/Expensify/App/assets/78819774/f2f08838-812b-429d-b102-153c9d5976d4

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01169b0346fc6a15b0</li>
        <li>Upwork Job ID: 1747720921283096576</li>
        <li>Last Price Increase: 2024-01-24</li>
<li>Automatic offers: </li>
<ul>
<li>situchan | Contributor | 28129739</li>
<li>ZhenjaHorbach | Contributor | 28142252</li>
</ul></li>
    </ul>
</details>

**Comment by anmurali** [comment] 2024-01-22 23:05
@alitoshmatov - can you review and comment on the proposal above?

**Comment by alitoshmatov** [comment] 2024-01-24 12:02
Not sure what I am doing wrong, but still not reproducible on me
https://github.com/Expensify/App/assets/59907218/c652f4a9-4ebe-4396-b0b3-57ecb20558f6

**Comment by alitoshmatov** [comment] 2024-01-24 12:15
I reproduced it on desktop application but, I don't think refreshing is expected behavior on desktop
https://github.com/Expensify/App/assets/59907218/34feff59-4647-485d-b62f-2f8f97575cd8

**Comment by alitoshmatov** [comment] 2024-01-24 12:24
Yes I was able to reproduce it on staging, still curious why it wasn't reproducible on local testing. Let me do some research on this issue then.

**Comment by alitoshmatov** [comment] 2024-01-25 06:42
@ZhenjaHorbach just to be 100% sure can you retest this issue on the latest main. If you manage to reproduce it. I will ask for other c+ help and reassign if they can also reproduce

**Comment by situchan** [comment] 2024-01-25 10:07
I reproduced with very simple step: (need to refresh quickly)
1. Open any chat and draft message
2. Quickly refresh app

https://github.com/Expensify/App/assets/108292595/735bc174-f849-4feb-87e1-065894fb4c1c

----

And another step: (no need quick action to refresh)
1. Open any chat and draft message
2. Open Settings page
3. Refresh


https://github.com/Expensify/App/assets/108292595/59c7c614-347b-48da-8e26-6bb3ac59f769



(both steps don't require offline/online switch)

**Comment by alitoshmatov** [comment] 2024-01-25 10:09
@situchan Will you be able to take it over?

**Comment by situchan** [comment] 2024-01-25 10:10
> @situchan Will you be able to take it over?

sure if you want to

**Comment by alitoshmatov** [comment] 2024-01-25 10:11
That would be great.

@anmurali can you reassign this issue to @situchan

**Comment by mvtglobally** [comment] 2024-01-30 04:58
Issue not reproducible during KI retests. (First week)

**Comment by situchan** [comment] 2024-01-31 15:15
@ZhenjaHorbach thanks for the proposal.

> The main problem with this issue is that when we reload the page in this state by default we have reportID === 0
As a result, we can't get any text value for Composer

Can you please share permalink which explains your RCA?

Also, please confirm that there's no side effect from your solution.

**Comment by situchan** [comment] 2024-01-31 15:52
@ZhenjaHorbach thanks. The root cause is correct.
So the solution is to call `updateComment` when `reportID` becomes valid.
Isn't it better to render `SilentCommentUpdater` conditionally like this?

```
            isValidReportID && <SilentCommentUpdater
                reportID={reportID}
                report={report}
                value={value}
                updateComment={updateComment}
                commentRef={commentRef}
            />
```

This will trigger `updateComment` automatically on mount of this component

**Comment by situchan** [comment] 2024-01-31 15:57
ok if you think it's better, please update proposal accordingly

**Comment by situchan** [comment] 2024-01-31 16:49
@ZhenjaHorbach's [proposal](https://github.com/Expensify/App/issues/34667#issuecomment-1897083777) looks good to me. Both solutions are fine but I prefer alternative one.
🎀 👀 🎀 C+ reviewed

**Comment by anmurali** [comment] 2024-02-16 15:34
Payment not due for another 4 days but I will be OOO so I have reassigned for payment

**Comment by joekaufmanexpensify** [comment] 2024-02-16 15:36
Sounds good! @situchan please complete the checklist so we can prep to issue payment next week.

**Comment by situchan** [comment] 2024-02-18 12:34
Not able to find exact offending PR as Report screen was refactored several times (mainly for performance improvement).
I think this bug existed for a while.
We can skip regression test as caught by QA team, assuming this case already exists in TestRail.

**Comment by joekaufmanexpensify** [comment] 2024-02-19 16:47
BZ checklist is all set. All set to issue payment tomorrow.

**Comment by joekaufmanexpensify** [comment] 2024-02-20 15:35
@ZhenjaHorbach $500 sent and contract ended!

**Comment by joekaufmanexpensify** [comment] 2024-02-20 15:35
@situchan $500 sent and contract ended!

**Comment by joekaufmanexpensify** [comment] 2024-02-20 15:35
All set. Thanks everyone!

**Closed by joekaufmanexpensify** 2024-02-20 15:35 UTC
Labels: External, Daily, Awaiting Payment, Bug
