### ISSUE TITLE
[HOLD for payment 2022-09-16] [$1000] Scrolling on code block does not work as expected - reported by @mdneyazahmad

### ISSUE THREAD

**Issue by mvtglobally** [Expensify/App#9705] opened 2022-07-05 17:43 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/docs/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Open app on web
2. Post(if not) some code block message with long lines so that it overflows.
3. Try to move two finger (scroll) not precisely horizontally but at some other angle eg. 45

## Expected Result:
We have to precisely scroll to left or right or else the page will also scroll vertically.

## Actual Result:
When we are scrolling horizontally it should ignore the vertical movement. You can test the same on Github for the expected result.

## Workaround:
unknown 

## Platform:

Where is this issue occurring?

- Web
- Desktop App

**Version Number:** 1.1.79-0
**Reproducible in staging?:** Y 
**Reproducible in production?:** Y
**Email or phone of affected tester (no customers):** 
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation 

https://user-images.githubusercontent.com/43995119/177385605-d0a29fb8-ff45-4e6b-ae11-9dfd23ab8d07.mp4

**Expensify/Expensify Issue URL:** 
**Issue reported by:** @mdneyazahmad
**Slack conversation:** https://expensify.slack.com/archives/C01GTK53T8Q/p1655124314604409

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by kevinksullivan** [comment] 2022-07-07 00:43
https://www.upwork.com/jobs/~017e918f410937c6d8

**Comment by railway17** [comment] 2022-07-12 10:09
### Proposal

I was able to reproduce this issue based on your issue report.
And I noticed that the current code base will not work for horizontal scrolling for below 2 reasons:

`file: /src/components/HTMLEngineProvider/HTMLRenderers/PreRenderer/index.js`

![image](https://user-images.githubusercontent.com/29966461/178464306-57a1fc49-6d4d-424b-a044-492ddd6bb9d9.png)

1. In the mouse wheel event, deltaX is always 0 and deltaY displays the **offset value**.
So, `isVerticalScrolling > 3` will be false when mouse is scrolled (wheel) up.
2. As I mentioned above, offset value is only represented by deltaY.
So, we can't change the scrollLeft by `node.scrollLeft += event.deltaX;`

By fixing these 2 issues, horizontal scrolling will be work in both web and desktop versions

**Comment by rushatgabhane** [comment] 2022-07-12 10:12
@railway17 and what do you propose to fix the 2 issues?

**Comment by railway17** [comment] 2022-07-12 10:15
> @railway17 and what do you propose to fix the 2 issues?

1. We don't need to use `isVerticalScrolling` variable.
2. Need to change `node.scrollLeft += event.deltaY;`
Regarding to 2nd fix, it might be not sensitive because deltaY changes is a little small.
So, we might use like `node.scrollLeft += 2 * event.deltaY;`
Thank you

**Comment by rushatgabhane** [comment] 2022-07-12 11:55
@railway17 that's breaking horizontal scroll 😅
I'm using my touchpad

https://user-images.githubusercontent.com/29673073/178484268-02d25999-0a89-4928-95b2-8a562f488931.mov

**Comment by railway17** [comment] 2022-07-12 11:58
> 

Well.. Actually, I've only tested it in my desktop browser and app.
It was working clearly.
Let me check more about why it is...

**Comment by kevinksullivan** [comment] 2022-07-14 19:58
Not overdue

**Comment by chiragsalian** [comment] 2022-07-14 21:29
Demoting to weekly since there isn't much reason for melvin pings daily as we wait for proposals.

**Comment by chiragsalian** [comment] 2022-07-26 18:26
Not overdue, still waiting on proposals.

**Comment by kevinksullivan** [comment] 2022-08-04 15:36
Price doubled

**Comment by railway17** [comment] 2022-08-04 15:53
Confirm again.
Are you referring `touchpad` of laptop, right?

**Comment by kevinksullivan** [comment] 2022-08-16 05:07
Price doubled

**Comment by b1tjoy** [comment] 2022-08-20 07:33
### PROPOSAL

### Problem

When user scroll the touchpad, the browser will raise a sequence of events. If we scroll at some angle(not preciselly horizontal or vertical), we may capture an event with `Math.abs(event.deltaY) > 3`, we mark it as vertical scrolling and bubble up the event to parent element, then make the `FlatList` scroll vertically.

https://github.com/Expensify/App/blob/22e39f9de1c1fbace6e7a0e4c06f364310129895/src/components/HTMLEngineProvider/HTMLRenderers/PreRenderer/index.js#L34-L40

### Solution

**Solution 1**

Only mark event with `Math.abs(event.deltaY) > 3` and `deltaX === 0` as vertical scrolling.

https://github.com/Expensify/App/blob/22e39f9de1c1fbace6e7a0e4c06f364310129895/src/components/HTMLEngineProvider/HTMLRenderers/PreRenderer/index.js#L35

```JSX
- const isVerticalScrolling = Math.abs(event.deltaY) > 3;
+ const isVerticalScrolling = Math.abs(event.deltaY) > 3 && event.deltaX === 0;
```

Drawback: if we scroll at some angle very fast, we may also capture an event with `Math.abs(event.deltaY) > 3` and `deltaX === 0`, which cause the vertical scroll bar shake up and down, it's not as stable as GitHub.

**Solution 2**

Calculate the scroll direction only based on the first event or the first several events, and use the calculation result later to decide scroll horizontal or vertical. Here is the code for calculate the scroll direction based on the first event.

1. Add member property

https://github.com/Expensify/App/blob/22e39f9de1c1fbace6e7a0e4c06f364310129895/src/components/HTMLEngineProvider/HTMLRenderers/PreRenderer/index.js#L10

```JSX
+ this.scrollStoppedTimerId = null;
+ this.isVerticalScrolling = false;
```

2. Replace this

https://github.com/Expensify/App/blob/22e39f9de1c1fbace6e7a0e4c06f364310129895/src/components/HTMLEngineProvider/HTMLRenderers/PreRenderer/index.js#L35-L40

with

```JSX
if (this.scrollStoppedTimerId) {
    clearTimeout(this.scrollStoppedTimerId);
} else {
    // First scroll event, calculate the scroll direction
    this.isVerticalScrolling = Math.abs(event.deltaY) > (Math.abs(event.deltaX) * 2);
}

this.scrollStoppedTimerId = setTimeout(() => {
    // Scroll stopped, reset to default value
    this.scrollStoppedTimerId = null;
    this.isVerticalScrolling = false;
}, 100);

if (event.currentTarget === node && horizontalOverflow && !this.isVerticalScrolling) {
    node.scrollLeft += event.deltaX;
    event.preventDefault();
    event.stopPropagation();
}
```

This solution make our code block as stable as GitHub, even if we scroll very fast at some angle, the vertical scroll bar of `FlastList` will not shake.

### Screenshot

Upload later.

**Comment by b1tjoy** [comment] 2022-08-22 10:47
Thanks for your quick and efficient review.

>     1. Isn't this what [_.debounce](https://underscorejs.org/#debounce) does? Can we use that instead?

I will do some more digging and get back to you later. 

>     2. I'm curious on your thought process that made you define `isVerticalScrolling`
>        `this.isVerticalScrolling = Math.abs(event.deltaY) > (Math.abs(event.deltaX) * 2)`

I found out even if I scroll at a wide angle (more than 45 degrees, `abs(deltaY) > abs(deltaX)`) on GitHub, I can still scoll the code block horizontally, but not the whole page vertically.

First I define `this.isVerticalScrolling = Math.abs(event.deltaY) > Math.abs(event.deltaX)`, and that does not make the same experience as GitHub, so I try to define isVerticalScroll with abs(deltaY) much greater than abs(deltaX), 2 is a magic number I choose. :)

**Comment by b1tjoy** [comment] 2022-08-23 15:45
@rushatgabhane Thanks for your guidance!

Here is a debounced version.

1. Add member attribute

https://github.com/Expensify/App/blob/22e39f9de1c1fbace6e7a0e4c06f364310129895/src/components/HTMLEngineProvider/HTMLRenderers/PreRenderer/index.js#L10

```JSX
this.isVerticalScrolling = false;
this.getScrollDirectionDebounced = _.debounce(this.getScrollDirection.bind(this), 100, true);
```

2. Add method

```JSX
getScrollDirection(event) {
    this.isVerticalScrolling = Math.abs(event.deltaY) > (Math.abs(event.deltaX) * 2);
}
```

3. Update event hanlder

Replace this

https://github.com/Expensify/App/blob/22e39f9de1c1fbace6e7a0e4c06f364310129895/src/components/HTMLEngineProvider/HTMLRenderers/PreRenderer/index.js#L35-L40

with

```JSX
this.getScrollDirectionDebounced(event);
if (event.currentTarget === node && horizontalOverflow && !this.isVerticalScrolling) {
    node.scrollLeft += event.deltaX;
    event.preventDefault();
    event.stopPropagation();
}
```

**Comment by chiragsalian** [comment] 2022-08-23 21:31
Proposal LGTM too, feel free to create the PR @b1tjoy.

**Comment by kevinksullivan** [comment] 2022-08-24 00:54
Going OOO for a bit so looking for someone to step in. Thanks @strepanier03 !

**Comment by strepanier03** [comment] 2022-08-24 16:21
I'm unsure if this needs my action at this time but I'm happy to take over Triage for it. Since a PR has been assigned to someone and I don't see that is has been linked to this GH I believe it's still being worked on. My plan is to send on to Eng once the PR is linked.

If I should take a different approach or action, please let me know.

**Comment by strepanier03** [comment] 2022-08-24 16:45
At that point, I think it will actually have to go to someone from the contributor management team because Triagers only interaction with Upwork is to apply the External label. That, or we need to update the [SO](https://stackoverflow.com/c/expensify/questions/4319) for the triage chore because it doesn't say anything about helping with payment or the Upwork job.

When the PR is merged, I'll find someone from that team to help guide me. Thanks @rushatgabhane!

**Comment by strepanier03** [comment] 2022-08-29 14:43
Waiting for PR merge

**Comment by strepanier03** [comment] 2022-09-01 21:45
Looks like the PR is in review - https://github.com/Expensify/App/pull/10659

I raised this in #contributor-management [here](https://expensify.slack.com/archives/C01SKUP7QR0/p1662068319796349) to get a hand moving this forward. I found this [SO](https://stackoverflow.com/c/expensify/questions/8561/8562#8562) but I can't follow it due to access limitations.

**Comment by mvtglobally** [comment] 2022-09-13 04:28
Issue not reproducible during KI retests. (First week)

**Comment by puneetlath** [comment] 2022-09-16 17:04
@b1tjoy @mdneyazahmad it looks like the original Upwork job expired. Can you apply here so I can get you both paid out? 

https://www.upwork.com/jobs/~01324c586d2d04915a

(internal post for me https://www.upwork.com/ab/applicants/1570820498091720704/applicants)

**Comment by rushatgabhane** [comment] 2022-09-17 03:03
@puneetlath payment not due yet.
This issue isn't fixed on native https://github.com/Expensify/App/issues/9705#issuecomment-1241745339

**Comment by puneetlath** [comment] 2022-09-17 19:36
Just to make sure I understand, there are multiple PRs that make up this issue?

**Comment by rushatgabhane** [comment] 2022-09-18 07:11
> . Both FlatList and ScrollView are build on iOS/Android native UI component, 45 degree is like a boundary to distinguish between vertical and horizontal movement.

It's more like an expected behaviour than issue to me, but the decision is yours.

@b1tjoy thanks for the investigation. I totally agree with you

**Comment by rushatgabhane** [comment] 2022-09-18 07:14
@puneetlath this issue can be settled. I agree with @b1tjoy that native platforms have the expected result too.

**Comment by puneetlath** [comment] 2022-09-19 18:12
Awesome, thanks for the detail. I agree. 

@mdneyazahmad I went ahead and paid. 

@rushatgabhane @b1tjoy can you please accept the Upwork hiring offer?

**Comment by mvtglobally** [comment] 2022-09-20 05:03
Issue not reproducible during KI retests. (First week)

**Comment by puneetlath** [comment] 2022-09-21 15:21
@rushatgabhane bump on accepting the Upwork offer.

**Comment by rushatgabhane** [comment] 2022-09-21 15:42
@puneetlath sorry for the delay. Applied!

**Comment by puneetlath** [comment] 2022-09-21 16:27
All paid!

**Closed by puneetlath** 2022-09-21 16:27 UTC
Labels: Reviewing, Exported, External, Daily, Awaiting Payment
