### ISSUE TITLE
After deleting mark as unread message chat still bold on home page - reported by @gadhiyamanan

### ISSUE THREAD

**Issue by mvtglobally** [Expensify/App#11274] opened 2022-09-26 04:29 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1.  go to any chat
2.  click on any message and marked as unread
3.  delete that message
4.  go back to home screen

## Expected Result:
chat should be not bold

## Actual Result:
chat shows as bold

## Workaround:
unknown 

## Platform:

Where is this issue occurring?

- Web
- iOS
- Android
- Desktop App
- Mobile Web

**Version Number:** 1.2.1-0
**Reproducible in staging?:** need repro
**Reproducible in production?:** need repro 
**Email or phone of affected tester (no customers):** 
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation 

https://user-images.githubusercontent.com/43995119/192194087-7dbad91a-9521-4f1e-8601-013aee675501.mov

https://user-images.githubusercontent.com/43995119/192194088-7f072de3-d81e-431c-b20f-5efc189cb105.mp4

**Expensify/Expensify Issue URL:** 
**Issue reported by:** @gadhiyamanan
**Slack conversation:** https://expensify.slack.com/archives/C01GTK53T8Q/p1661958992249579

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by gadhiyamanan** [comment] 2022-10-11 13:58
@mvtglobally no one assigned here, I am still able to reproduce it with the latest build

**Comment by mallenexpensify** [comment] 2022-10-12 00:30
@mvtglobally are you able to reproduce?

**Comment by gadhiyamanan** [comment] 2022-10-12 03:23
Please try to delete old messages, with latest messages it's working fine

**Comment by mallenexpensify** [comment] 2022-10-17 17:14
@mvtglobally can you try to reproduce please?

**Comment by mvtglobally** [comment] 2022-10-17 18:47
Checking

**Comment by mvtglobally** [comment] 2022-10-17 19:01
@mallenexpensify 
If we do the older messages issue seems repro. Should I add Auto-assignee label? 

https://user-images.githubusercontent.com/43995119/196260480-63ed75b7-8396-4b94-a31d-bad53001f402.mp4

**Comment by mallenexpensify** [comment] 2022-10-18 00:55
Thanks @mvtglobally I added the label and unassigned you.  Please triage @jliexpensify

**Comment by jliexpensify** [comment] 2022-10-18 03:13
I'm on v1.2.17-4 and can't replicate this. I asked @kadiealexander to try on 1.2.12 and she couldn't either.

@gadhiyamanan what version are you on?

**Comment by gadhiyamanan** [comment] 2022-10-18 03:19
@jliexpensify I am using v1.2.12-4(production) and able to reproduce it https://user-images.githubusercontent.com/54790231/196327734-957b11bb-e14c-4729-83a3-0dee307cee40.mp4

**Comment by gadhiyamanan** [comment] 2022-10-18 03:24
Able to reproduce on v1.2.17-4 
https://user-images.githubusercontent.com/54790231/196328414-c3198f45-72b0-4267-ad66-30ab3b07343e.mp4

**Comment by kadiealexander** [comment] 2022-10-18 03:33
HI Manan! Could you please share the following information to help us narrow this down?

 - Device model and OS
 - Browser used
 - Staging or production?

**Comment by kadiealexander** [comment] 2022-10-18 03:36
@gadhiyamanan I'm reasonably sure this is intended behaviour. You're marking all messages below that message as unread, and the rest of the messages below the deleted message are still unread even if one gets deleted.

If you mark the last message as unread and then delete it, the bolding disappears because all unread messages are now removed.

**Comment by jliexpensify** [comment] 2022-10-18 03:43
I agree with Kadie - I don't think this is an issue.

**Comment by gadhiyamanan** [comment] 2022-10-18 03:46
I think in that case we should not remove  "New" green line it should pass to next message

@jliexpensify @kadiealexander

**Comment by jliexpensify** [comment] 2022-10-18 03:53
> I think in that case we should not remove "New" green line it should pass to next message

I think we should remove "New" as you're only marking one message as Unread and removing it: hence there aren't new messages to read. 

In your first video, if you marked all 3 messages as Unread and removed one, then the "New" line should stay.

**Comment by gadhiyamanan** [comment] 2022-10-18 04:03
>In your first video, if you marked all 3 messages as Unread and removed one, then the "New" line should stay.

Right now "New" line disappears
https://user-images.githubusercontent.com/54790231/196332814-6f8850e1-a1b3-455f-aa24-5564eefbb8c8.mp4

**Comment by jliexpensify** [comment] 2022-10-18 04:19
@gadhiyamanan - you're just marking one unread message in that above video, right? If so, that seems correct - in terms of the "new" line disappearing.

If you mark 3 messages (one after another) and delete the first one, then the "new" line should remain.

**Comment by jliexpensify** [comment] 2022-10-19 22:06
Ok, I'm going to close this one as I don't think it's a bug (cc @kadiealexander as she confirmed this too). Feel free to re-open with further discussion if you disagree!

**Closed by jliexpensify** 2022-10-19 22:06 UTC
Labels: Daily, Bug
