### ISSUE TITLE
A peculiar grey space located in the top-left corner of the attachment modal.

### ISSUE THREAD

**Issue by m-natarajan** [Expensify/App#24652] opened 2023-08-16 21:33 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Open any Chat
2. Click on the plus icon in the composer and click Add attachment
3. Choose you attachment to open the attachment modal
4. Now notice the top-left corner of the attachment modal
## Expected Result:
There should be no gray space visible in the top-left corner of the attachment modal.
## Actual Result:
There is a peculiar grey space located in the top-left corner of the attachment modal.
## Workaround:
Can the user still use Expensify without this being fixed? Have you informed them of the workaround?

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [x] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 1.3.54-11
**Reproducible in staging?:** Yes
**Reproducible in production?:** Yes
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation

[Screencast from 08-08-23 04_25_06.webm](https://github.com/Expensify/App/assets/38435837/cf6320ae-d1ef-41b8-8e41-7c5081b2e4b8)

![Snip - (1) New Expensify - Google Chrome (2)](https://github.com/Expensify/App/assets/38435837/fac44e88-7609-47bf-8ebb-ea7c7aa2ca36)

**Expensify/Expensify Issue URL:**
**Issue reported by:** @Ahmed-Abdella
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1691463129453749

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by akinwale** [comment] 2023-08-17 02:49
That's the top-left edge of the "E" from the Expensify text brand. :smile:

**Comment by Ahmed-Abdella** [comment] 2023-08-17 02:52
@akinwale NO, it is not 😄

**Comment by Ahmed-Abdella** [comment] 2023-08-17 02:54
looks like you are right sorry for the confusion 😄

**Comment by Ahmed-Abdella** [comment] 2023-08-17 02:58
Thanks, this what makes me think it is part of the model
![Screenshot from 2023-08-17 05-56-26](https://github.com/Expensify/App/assets/77763699/33c289b1-5872-453b-9064-02e530d49b90)

sorry for that miss 😄

**Comment by anmurali** [comment] 2023-08-24 15:50
Not a bug! Closing.

**Closed by anmurali** 2023-08-24 15:50 UTC
Labels: Daily, Overdue, Bug
