### ISSUE TITLE
[HOLD for payment 2023-11-30] [$500] Distance - Search is open in background on distance image preview

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#29378] opened 2023-10-11 20:13 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.1.81.5
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** @dhanashree-sawant
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1697018060491379

## Action Performed:
1. Open the app
2. Open any distance request money report or raise one and open
3. Click on map image
4. Click on 3 dots to open replace popup
5. Click CTRL+K / CMD+K and observe that app changes URL to search but still displays map preview (search is open in background)

## Expected Result:
App should close map preview and open search on using search shortcut

## Actual Result:
 App opens search page in background when map preview is open with replace popup

## Workaround:
Unknown 

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos
<details>
<summary>Android: Native</summary>

</details>

<details>
<summary>Android: mWeb Chrome</summary>

</details>

<details>
<summary>iOS: Native</summary>

</details>

<details>
<summary>iOS: mWeb Safari</summary>

</details>

<details>
<summary>MacOS: Chrome / Safari</summary>

 

https://github.com/Expensify/App/assets/93399543/390e43c6-ec7b-4dbc-9b15-483fb61b9a86

https://github.com/Expensify/App/assets/93399543/5074b81e-18b4-415a-899a-3f198a05a039

https://github.com/Expensify/App/assets/93399543/9bc264f2-c779-4eb0-b895-524e453ee8c1

</details>

<details>
<summary>MacOS: Desktop</summary>

 

https://github.com/Expensify/App/assets/93399543/67eab396-b108-4d9b-b616-8f106eea4f72

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~0106699f927099ee98</li>
        <li>Upwork Job ID: 1712199786335612928</li>
        <li>Last Price Increase: 2023-10-25</li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @kevinksullivan</details>

**Comment by kevinksullivan** [comment] 2023-10-17 16:13
@ArekChr can you review the proposals above?

**Comment by ArekChr** [comment] 2023-10-19 07:35
Is this still reproducible? I couldn't reproduce this issue on the latest main using macOS Chrome

**Comment by ArekChr** [comment] 2023-10-19 08:15
@tienifr Your proposals regarding closing modals appear similar to implementations of an event emitter, where we can push functions and invoke them later. Could you elaborate on this implementation?

**Comment by ArekChr** [comment] 2023-10-20 10:45
@tienifr What if we will have three modals opened in a different scenario? This might not work as expected because we will close the last visible modal.

**Comment by ArekChr** [comment] 2023-10-20 10:53
@tienifr Do we really need getAvaiableKey? I think this could be simplified so we can make closeModals of an array type and then call all the methods from closeModals. Instead setting close function as a key in object we will push it to array

**Comment by ArekChr** [comment] 2023-10-20 11:06
When the component goes away, we can take out the 'listeners' function from the list. This would make the code clearer if we use something like a custom event system. But, this means changing more parts of the code. cc, @mountiny WDYT? 

So, when we open the modal, we add 'closeModal' to the list. And when the modal goes away, we take it out.

**Comment by mountiny** [comment] 2023-10-20 17:01
Seems like a great thing to bring up for discussion to a broader community, I am not sure myself whats the best path now so if @tienifr could ost a proposal/ solution to this to be generic in open source that would be great. Thanks!

**Comment by kevinksullivan** [comment] 2023-10-27 02:50
Waiting on proposals

**Comment by ArekChr** [comment] 2023-10-27 08:45
@tienifr I'm going ahead with your [proposal](https://github.com/Expensify/App/issues/29378#issuecomment-1758779541). Regarding details of the closing function, we'll check this in more detail when we review the PR.

:ribbon: :eyes: :ribbon: C+ reviewed

**Comment by pecanoro** [comment] 2023-10-27 19:42
Assigning @tienifr to the issue!

**Comment by ArekChr** [comment] 2023-11-27 10:11
- [x] Link to the PR: Didn't find regression PR. This bug may have been present since the initial stages.
- [x] Link to comment: n/a
- [x] Link to discussion: n/a
- [x] Determine if we should create a regression test for this bug: I think we can add a regression test, In case if have more modals we need to ensure shortcuts close them properly.

**Regression Test Proposal**

1. Open the app.
2. Open any distance request money report or raise one and open.
3. Click on the map image.
4. Click on three dots to open replace popup.
5. Click any NewDot shortcut: eg. Click CTRL+K / CMD+K.
6. Verify all modals close and shortcuts open the proper page.

**Comment by kevinksullivan** [comment] 2023-11-27 22:46
Waiting on payment

**Comment by pecanoro** [comment] 2023-12-04 18:12
@kevinksullivan All yours!

**Comment by kevinksullivan** [comment] 2023-12-12 02:07
Job expired, @tienifr just sent you a new job, let me know when you accept!

https://www.upwork.com/jobs/~0127266b62579f1f1b

**Comment by pecanoro** [comment] 2023-12-18 12:10
@kevinksullivan Did you send the payments? So we can close this

**Comment by kevinksullivan** [comment] 2023-12-19 16:41
ah yes sorry, I had paid this but forgot to close the issue. Done!

**Closed by kevinksullivan** 2023-12-19 16:41 UTC
Labels: External, Daily, Overdue, Awaiting Payment, Bug
