### ISSUE TITLE
[HOLD for #19453] delete workspace modal appears on three dots and hides header

### ISSUE THREAD

**Issue by kavimuru** [Expensify/App#19791] opened 2023-05-30 02:07 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. go to any chat
2. go to Settings> workspace
2. create a workspace if not created
3. click on three dots do open delete workspace modal
## Expected Result: 
delete workspace modal should not show on three dots and not hide header
## Actual Result: 
delete workspace modal appears on three dots

## Workaround:
Can the user still use Expensify without this being fixed? Have you informed them of the workaround?

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [x] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 1.3.20-0
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation
![Screenshot 2023-05-26 at 7 38 41 PM](https://github.com/Expensify/App/assets/43996225/d2a114b8-db1c-4704-a0a2-4331da516bb1)

https://github.com/Expensify/App/assets/43996225/abebcc55-785c-4779-9e5c-da8b564a5bc9

<img width="960" alt="Untitled" src="https://github.com/Expensify/App/assets/43996225/e3e5bd3c-f739-4b32-b07c-03ad9381dcb7">

**Expensify/Expensify Issue URL:**
**Issue reported by:** @gadhiyamanan 
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1685110046521609

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by sethraj14** [comment] 2023-05-30 10:17
@kavimuru @arielgreen Sorry for the delay was trying to fix a similar issue happening in the IOU section header as well.
## Proposal

### Please re-state the problem that we are trying to solve in this issue.

The Popover menu comes on click on three dots hiding the header in Workspace modal and IOU header as well.

### What is the root cause of that problem?

The Popover menu has a default anchor alignment set as 
```javascript
    anchorAlignment: {
        horizontal: CONST.MODAL.ANCHOR_ORIGIN_HORIZONTAL.LEFT,
        vertical: CONST.MODAL.ANCHOR_ORIGIN_VERTICAL.BOTTOM,
    },
``` 

The vertical bottom is placing the popover above and hiding the header.

### What changes do you think we should make in order to solve the problem?

Passing anchor alignment value to the Popover menu from the ThreeDotsMenu file which is being used in both the places-
Workspace Modal and IOU Header.

```javascript
    anchorAlignment: {
        horizontal: CONST.MODAL.ANCHOR_ORIGIN_HORIZONTAL.LEFT,
        vertical: CONST.MODAL.ANCHOR_ORIGIN_VERTICAL.TOP
    },
``` 

This will ensure the fix on both places without changing the core logic of the Popover Menu.


Working solution - 

![Screenshot 2023-05-30 at 3 47 08 PM](https://github.com/Expensify/App/assets/14844259/f436b424-3658-46e6-be43-4fe2f91693cf)
![Screenshot 2023-05-30 at 3 47 16 PM](https://github.com/Expensify/App/assets/14844259/34cb17a1-20d3-4d5e-bed6-3a8cf6aeaa2f)

### What alternative solutions did you explore? (Optional)

**Comment by arielgreen** [comment] 2023-06-02 02:09
Hold

**Comment by arielgreen** [comment] 2023-06-16 02:30
Reassigning, team change

**Comment by adelekennedy** [comment] 2023-07-05 02:22
still holding

**Comment by Santhosh-Sellavel** [comment] 2023-07-05 17:17
Yeah, we are good to close this one, thanks!

**Closed** 2023-07-05 20:16 UTC
Labels: Reviewing, Daily, Bug
