### ISSUE TITLE
[HOLD for payment 2024-11-05] [$250] Update LHN nav items to be 52px tall instead of 56px tall

### ISSUE THREAD

**Issue by m-natarajan** [Expensify/App#51089] opened 2024-10-18 13:56 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 9.0.50-8
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**If this was caught on HybridApp, is this reproducible on New Expensify Standalone?:**
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** @shawnborton 
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1729242925493769

## Action Performed:
1. Go to staging.new.expensify.com
2. Click search
3. Observe navigation items
## Expected Result:
All the navigation items are updated to use the correct height so we stay consistent with 52px for big buttons
## Actual Result:
Currently our LHN nav items for pages like Search, Settings, Workspace Editor, etc use a height of 56px.
## Workaround:
Unknown
## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Standalone
- [ ] Android: HybridApp
- [ ] Android: mWeb Chrome
- [ ] iOS: Standalone
- [ ] iOS: HybridApp
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

<details>
  <summary>Add any screenshot/video evidence</summary>

![CleanShot 2024-10-18 at 11 16 05@2x](https://github.com/user-attachments/assets/2d1bb27b-7db3-4dfc-a0c7-29aaa1a52f4b)

  
![Screenshot 2024-10-18 095019](https://github.com/user-attachments/assets/24e0073f-6b2a-459b-8603-300780e18a78)

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~021847349783902749913</li>
        <li>Upwork Job ID: 1847349783902749913</li>
        <li>Last Price Increase: 2024-10-18</li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @slafortune</details>

**Comment by jayeshmangwani** [comment] 2024-10-18 13:57
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
The LHN navigation items (MenuItem) need to have a height of 52px instead of 56px.

### What is the root cause of that problem?
This is a straightforward enhancement.

### What changes do you think we should make in order to solve the problem?
We just need to update the `sectionMenuItem` height from 56px to 52px, which will resolve the issue for Workspaces and Settings. However, to fix this height for Search, we also need to handle the `FocusableMenuItem`. Here, we can pass the `wrapperStyle`, which will include the following styles: `height: styles.sectionMenuItem.height` and `alignItems: 'center'`.
https://github.com/Expensify/App/blob/219707fd932242de5ed1d5dc4a63967df007be11/src/styles/index.ts#L2892-L2895

Screenshots showing how the 52px height will look are provided below.

<details>
  <summary>Web/Desktop</summary>
  
<details>
  <summary>Settings</summary>
  
<img width="377" alt="Screenshot 2024-10-18 at 19 16 09" src="https://github.com/user-attachments/assets/0bb64a64-d856-4048-83a0-19c98b66fdb2">

<img width="848" alt="Screenshot 2024-10-18 at 19 16 20" src="https://github.com/user-attachments/assets/a9361360-73f6-4ae9-9527-1f3d75cfd2e1">


</details>

<details>
  <summary>Workspace</summary>
  
<img width="848" alt="Screenshot 2024-10-18 at 19 15 46" src="https://github.com/user-attachments/assets/01ab038c-72ab-4af7-89e0-bfb7cbe32e9c">
<img width="377" alt="Screenshot 2024-10-18 at 19 15 54" src="https://github.com/user-attachments/assets/d9e2eada-baba-4810-b901-0caa1bf29468">


</details>

<details>
  <summary>Search</summary>
  
<img width="849" alt="Screenshot 2024-10-18 at 19 16 35" src="https://github.com/user-attachments/assets/f1ae89d4-031b-4778-8140-504d299faada">
<img width="850" alt="Screenshot 2024-10-18 at 19 16 44" src="https://github.com/user-attachments/assets/1de17b57-1390-486f-8a04-412cabed507e">



</details>

</details>


<details>
  <summary>iOS</summary>
  
<details>
  <summary>Settings</summary>
  
![Simulator Screenshot - iPhone SE (3rd generation) - 2024-10-18 at 19 18 18](https://github.com/user-attachments/assets/2477a785-02e4-4080-9fdc-0559f6e1f661)
![Simulator Screenshot - iPhone SE (3rd generation) - 2024-10-18 at 19 18 39](https://github.com/user-attachments/assets/faee015b-a1dc-45f8-a6e0-1263fbd0c870)


</details>

<details>
  <summary>Workspace</summary>
  
![Simulator Screenshot - iPhone SE (3rd generation) - 2024-10-18 at 19 18 56](https://github.com/user-attachments/assets/29b7698a-0a8d-402c-9951-cfe4c0bf5ac1)
![Simulator Screenshot - iPhone SE (3rd generation) - 2024-10-18 at 19 19 10](https://github.com/user-attachments/assets/0161e2aa-588b-4f0c-ad3b-756c9d4cbb4e)


</details>

<details>
  <summary>Search</summary>
  
![Simulator Screenshot - iPhone SE (3rd generation) - 2024-10-18 at 19 17 49](https://github.com/user-attachments/assets/d29ee690-ae5b-4968-8430-8c23ccddee34)
![Simulator Screenshot - iPhone SE (3rd generation) - 2024-10-18 at 19 18 04](https://github.com/user-attachments/assets/920ca6c8-c906-4858-9ef5-e0e708df96d8)


</details>

</details>


### What alternative solutions did you explore? (Optional)

**Comment by s77rt** [comment] 2024-10-19 18:05
@jayeshmangwani Thanks for the proposal.

> However, to fix this height for Search, we also need to handle the FocusableMenuItem

Can you please elaborate what part of the Search page this is needed for?

**Comment by jayeshmangwani** [comment] 2024-10-19 18:13
@s77rt If you inspect the Dropdown menu item height on mobile, you’ll notice it's set to 64px instead of 56px. On the web, the height works fine(56px).

To address this issue on mobile, I suggest passing the wrapperStyle prop. The wrapperStyle should be:

```js
wrapperStyle={{
    alignItems: 'center',
    height: styles.sectionMenuItem.height
}}
```


https://github.com/Expensify/App/blob/66cf824036a51183d73dab2cc621901e43fe3196/src/components/FocusableMenuItem.tsx#L14-L17

![Simulator Screenshot - iPhone SE (3rd generation) - 2024-10-19 at 23 38 05](https://github.com/user-attachments/assets/640de29e-6ef2-4d10-9ee1-33a79375709b)

**Comment by s77rt** [comment] 2024-10-19 18:20
Ah the popover, no I think that should remain untouched

**Comment by jayeshmangwani** [comment] 2024-10-19 18:22
I think it should be 56px (after fixing this issue, it should be 52px), as the same option on the web currently has a height of 56px.

**Comment by jayeshmangwani** [comment] 2024-10-19 18:24
Or, we could adjust the height of the menu item specifically for the Search dropdown here.

**Comment by s77rt** [comment] 2024-10-19 18:24
We need to change the height only for the LHN items. On small screens we will render the popover menu, nothing to change there

**Comment by jayeshmangwani** [comment] 2024-10-19 18:25
Alright, I'll go ahead and remove that part from the proposal.

**Comment by s77rt** [comment] 2024-10-19 18:32
🎀 👀 🎀 C+ reviewed
[Link to proposal](https://github.com/Expensify/App/issues/51089#issuecomment-2422541205)

**Comment by rafecolton** [comment] 2024-10-19 18:36
@shawnborton can you please clarify if the popover height should change too? 

@jayeshmangwani I'm assigning you, but let's wait to get this merged until we get clarification from Shawn if the popover is in scope too

**Comment by rafecolton** [comment] 2024-10-19 18:38
Removing and re-adding to try to re-trigger the upwork automation

**Comment by jayeshmangwani** [comment] 2024-10-19 18:42
@rafecolton Upwork automation might not trigger here because both s77rt and I were paid via NewDot

**Comment by rafecolton** [comment] 2024-10-20 01:48
Oh nice, good to know. @mallenexpensify is there a way to differentiate? Would be nice to have melvinbot post so the CME doesn't think the upwork automation is broken

**Comment by shawnborton** [comment] 2024-10-21 06:38
No need to change the popover option row item height, let's first just start with the LHN items. Thanks!

**Comment by s77rt** [comment] 2024-11-02 14:43
Checklist ^ does not apply. Not a bug

**Closed** 2024-11-05 13:11 UTC
Labels: External, Daily, Awaiting Payment, Bug

**Comment by JmillsExpensify** [comment] 2024-11-05 17:05
$250 approved for @s77rt

**Comment by garrettmknight** [comment] 2024-11-06 11:57
$250 approved for @jayeshmangwani
