### ISSUE TITLE
[$250] Held expense with violation showing up in the LHN pinned with an RBR

### ISSUE THREAD

**Issue by m-natarajan** [Expensify/App#41813] opened 2024-05-07 20:50 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.71-0
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** @puneetlath 
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1714164768659869

## Action Performed:
1. Submit a scanned receipt with violation (e.g. merchant name missing)
2. Login as Approver
3. Hold the expense

## Expected Result:
Should be removed from LHN
## Actual Result:
Still show up in with pinned with an RBR for the approver
## Workaround:
unknown
## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

![Screenshot 2024-04-26 at 4 52 29 PM](https://github.com/Expensify/App/assets/38435837/92dacfbc-23ae-4313-948a-3f5afe7cc851)

https://github.com/Expensify/App/assets/38435837/5648a200-57af-4080-bbcc-1b99a12e2f27

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01df89075151aabf71</li>
        <li>Upwork Job ID: 1788326881274195968</li>
        <li>Last Price Increase: 2024-05-15</li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @rushatgabhane</details>

**Comment by isabelastisser** [comment] 2024-05-08 21:57
@m-natarajan @rushatgabhane, which project this issue should be added to?

**Comment by nkdengineer** [comment] 2024-05-09 08:25
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
Still show up in with pinned with an RBR for the approver

### What is the root cause of that problem?
We don't check to return `false` if the transaction is held here.

https://github.com/Expensify/App/blob/807c945ef8edabe86cc62f16c866aa754db8750b/src/libs/TransactionUtils.ts#L502
### What changes do you think we should make in order to solve the problem?
We should add `!isOnHold(transaction)` here to return `false` if the transaction is held.

https://github.com/Expensify/App/blob/807c945ef8edabe86cc62f16c866aa754db8750b/src/libs/TransactionUtils.ts#L502

Or we can only add this check in this function
https://github.com/Expensify/App/blob/807c945ef8edabe86cc62f16c866aa754db8750b/src/libs/ReportUtils.ts#L2715
### What alternative solutions did you explore? (Optional)
NA

**Comment by rushatgabhane** [comment] 2024-05-13 05:59
@isabelastisser what is the expected result?

Why should be hide RBR for held expenses?

**Comment by isabelastisser** [comment] 2024-05-13 18:45
@rushatgabhane 

> Should be removed from LHN

@puneetlath  `Why should we hide RBR for held expenses?` Do you have more context on this?

**Comment by isabelastisser** [comment] 2024-05-16 17:19
Bump @puneetlath

**Comment by puneetlath** [comment] 2024-05-16 18:42
I think it shouldn't show up for the approver, but it's just a suggestion. This should have a bigger discussion before we decide whether we want to do anything.

**Comment by isabelastisser** [comment] 2024-05-20 17:15
No updates yet. cc @rushatgabhane

**Comment by puneetlath** [comment] 2024-05-20 18:56
I'm not actually seeing this as the case anymore, so I think we can close this.

**Comment by isabelastisser** [comment] 2024-05-20 19:12
Thanks, Puneet! Closing.

**Closed by isabelastisser** 2024-05-20 19:12 UTC
Labels: External, Daily, Help Wanted, Overdue, Bug
