### ISSUE TITLE
[HOLD for payment 2023-07-26] IOU - Money request header is not greyed out in offline mode

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#22640] opened 2023-07-11 13:28 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___
**Issue found when executing PR** https://github.com/Expensify/App/pull/21918
## Action Performed:
1. Go to staging.new.expensify.com
2. Disconnect network
3. Click + > Request money > Enter amount > Select contact > Submit
4. Click on the payment request in the new DM

## Expected Result:
Money request header is greyed out

## Actual Result:
Money request header is not greyed out

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android / native
- [x] Android / Chrome
- [x] iOS / native
- [x] iOS / Safari
- [x] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 1.3.39.5

**Reproducible in staging?:** Yes

**Reproducible in production?:** No

**If this was caught during regression testing, add the test name, ID and link from TestRail:**

**Email or phone of affected tester (no customers):**

**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/78819774/ffa0c647-b7f3-43be-bda4-806e0294b33a

<img width="1440" alt="Bug6123789_Screenshot_2023-07-11_at_21 15 56" src="https://github.com/Expensify/App/assets/78819774/8606cabb-cce6-4567-917f-8a210f07d3b9">

**Expensify/Expensify Issue URL:**

**Issue reported by:** Applause - Internal Team

**Slack conversation:**

**Comment by ShogunFire** [comment] 2023-07-11 13:32
This is caused by https://github.com/Expensify/App/pull/21918#issuecomment-1630672820

**Comment by danieldoglas** [comment] 2023-07-11 14:07
Also I don't think this is a deploy blocker

**Comment by madmax330** [comment] 2023-07-11 14:22
Agreed, removing the label

**Comment by madmax330** [comment] 2023-07-31 16:39
Not overdue

**Comment by madmax330** [comment] 2023-08-02 20:55
Not overdue

**Comment by madmax330** [comment] 2023-08-07 10:58
Not overdue

**Comment by madmax330** [comment] 2023-08-10 11:28
@aimane-chnaif we can close this out right? Since it's not a new issue, but one that stems from the PR for the other issue there's not payment to make right?

**Closed** 2023-08-10 11:30 UTC
Labels: Engineering, Daily, Awaiting Payment
