### ISSUE TITLE
[$500]  LHN - Report is not marked as unread in LHN when the IOU is received

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#38186] opened 2024-03-12 21:41 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.501
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**If this was caught during regression testing, add the test name, ID and link from TestRail:** N/A
**Email or phone of affected tester (no customers):** sustinov@applausemail.com
**Issue reported by:** Applause - Internal Team

**Issue found when executing PR** https://github.com/Expensify/App/pull/35928
## Action Performed:
Preconditions:
Set up an OldDot admin account, invite the employee and approver to the policy https://sites.google.com/applausemail.com/applause-expensifyproject/wiki-guides/newdot-categories?authuser=0
1. Open https://staging.new.expensify.com/
2. Log in with the account of the employee added to the policy
3. Open https://staging.new.expensify.com/
in incognito mode
4. Log in to the policy approver account
5. Under the approver account, go to the WS room.
6. Under the employee account, create a manual request and send it to the WS room
7. Click on the "Submit" button in the created IOU

## Expected Result:
When an IOU is received, the Report in the LHN should be marked as unread

## Actual Result:
Report is not marked as unread in LHN when the IOU is received

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [x] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [ ] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details> 

https://github.com/Expensify/App/assets/78819774/df2c20c9-fb56-4b0a-a074-6c1185ac1654

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~013810a6929404cade</li>
        <li>Upwork Job ID: 1769899997275127808</li>
        <li>Last Price Increase: 2024-07-18</li>
    </ul>
</details>

**Comment by lanitochka17** [comment] 2024-03-12 21:42
@MitchExpensify  FYI I haven't added the External label as I wasn't 100% sure about this issue. Please take a look and add the label if you agree it's a bug and can be handled by external contributors

**Comment by MitchExpensify** [comment] 2024-03-14 19:13
@dylanexpensify you've been super close to message unread/read behavior - Should a new IOU show as unread? I think "yes", right?

**Comment by MitchExpensify** [comment] 2024-03-19 01:34
Lets get this fixed

**Comment by MitchExpensify** [comment] 2024-03-20 01:31
Waiting for proposals

**Comment by MitchExpensify** [comment] 2024-03-25 23:08
Advertising for proposals here https://expensify.slack.com/archives/C01GTK53T8Q/p1711408083227239

**Comment by kmbcook** [comment] 2024-03-27 23:17
I think this is a regression from https://github.com/Expensify/App/pull/36950,  because of adding the `!!report.lastActorAccountID` condition here:

https://github.com/Expensify/App/blob/e542ba7c2d9e216c2cd401de0de8ed225fff4a7b/src/libs/SidebarUtils.ts#L270-L272

**Comment by DylanDylann** [comment] 2024-03-30 05:32
I can take over this issue as a C+ reviewer because @situchan is OOO in April

**Comment by mallenexpensify** [comment] 2024-04-01 16:34
@situchan is out OOO, reassigning a C+ via the auto-assigner for fairness.

**Comment by bernhardoj** [comment] 2024-04-02 04:34
Looks like the same issue as https://github.com/Expensify/App/issues/38778 based on @kmbcook finding.

**Comment by jjcoffee** [comment] 2024-04-02 09:14
Agree with @bernhardoj's [comment](https://github.com/Expensify/App/issues/38186#issuecomment-2031067856) and @kmbcook's [analysis](https://github.com/Expensify/App/issues/38186#issuecomment-2024137290). This issue _is_ older, but it probably makes sense to HOLD this in favour of https://github.com/Expensify/App/issues/38778 as the C+ there has already selected a proposal/plan of action. Once the BE fix is applied there we can retest this issue. cc @MitchExpensify

**Comment by MitchExpensify** [comment] 2024-04-04 00:41
Holding on https://github.com/Expensify/App/issues/38778, thanks @jjcoffee

**Comment by MitchExpensify** [comment] 2024-04-15 22:12
Holding on https://github.com/Expensify/App/issues/38778,

**Comment by MitchExpensify** [comment] 2024-04-25 21:48
Holding on https://github.com/Expensify/App/issues/38778

**Comment by MitchExpensify** [comment] 2024-05-06 20:17
Holding on https://github.com/Expensify/App/issues/38778

**Comment by MitchExpensify** [comment] 2024-05-20 22:57
Holding on https://github.com/Expensify/App/issues/38778

**Comment by MitchExpensify** [comment] 2024-06-03 21:10
Holding on https://github.com/Expensify/App/issues/38778

**Comment by MitchExpensify** [comment] 2024-06-18 02:49
Holding on https://github.com/Expensify/App/issues/38778

**Comment by MitchExpensify** [comment] 2024-07-01 22:25
Holding on https://github.com/Expensify/App/issues/38778

**Comment by MitchExpensify** [comment] 2024-07-16 19:33
Reassigning while I'm on leave 🙇

**Comment by twisterdotcom** [comment] 2024-07-17 10:43
@MitchExpensify https://github.com/Expensify/App/issues/38778 is closed. Is there anything else this should be held on?

**Comment by MitchExpensify** [comment] 2024-07-17 21:48
Ah closed yesterday, nice. No that's all that was holding this up

**Comment by twisterdotcom** [comment] 2024-07-22 12:59
Okay, I see this is still a thing: 

https://github.com/user-attachments/assets/0d8871d9-bbbd-421b-87bf-bc4bade93ce0

**Comment by bernhardoj** [comment] 2024-07-22 14:11
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
The chat item in LHN doesn't show as bold for the workspace admin/approver when there is an expense preview

### What is the root cause of that problem?
https://github.com/Expensify/App/pull/36950 changes the unread logic a bit by checking whether the report has a `lastActorAccountID` or not.
https://github.com/Expensify/App/blob/c2ded1dc91252803795948fa97888e420b0e648f/src/libs/SidebarUtils.ts#L339-L341

But in case the last action is a report preview, the last actor account ID is 0.
<img width="180" alt="image" src="https://github.com/Expensify/App/assets/50919443/2b3b3f67-5e1a-400a-bf52-5fead46ca1c6">

### What changes do you think we should make in order to solve the problem?

First of all, we should revert https://github.com/Expensify/App/pull/36950 as it doesn't fix the root cause of the issue. The issue that the PR is trying to fix is that when we delete the last message in a room from device A, the `lastVisibleActionCreated` property of the report isn't updated in device B, so the unread status stays true.
https://github.com/Expensify/App/blob/4e6c52cad9f893a00e72d989caecdaf457a0ea02/src/libs/ReportUtils.ts#L4182

It will be updated once the device B opens the room. So, the problem is in the pusher that doesn't send the update to device B. Instead of patching up the issue, we should fix the pusher.

_fyi, when we delete the last message, we [set the `lastVisibleActionCreated` to empty optimistically](https://github.com/Expensify/App/blob/4e6c52cad9f893a00e72d989caecdaf457a0ea02/src/libs/actions/Report.ts#L1160-L1178), that's why the device A doesn't experience the issue. I think it should be set to the CREATED action `created` value, but I guess that's another topic to discuss_

**Comment by bernhardoj** [comment] 2024-07-22 14:11
The issue is actually the same, but because the other issue is closed, I reposted my proposal here

**Comment by situchan** [comment] 2024-07-22 17:37
@twisterdotcom I can take this back as C+ while @jjcoffee is OOO

**Comment by trjExpensify** [comment] 2024-07-22 22:24
>@trjExpensify I'm correct in thinking that a new green dot request should be an unread comment right?

Go from 1.30 in the video. You were in the chat when the IOU came through. So I wouldn't expect it to be unread in that case, would you?

**Comment by twisterdotcom** [comment] 2024-07-23 11:25
Ahhh good point. Okay, tested again and this is fixed:
<img width="1147" alt="Arc 2024-07-23 12 25 19" src="https://github.com/user-attachments/assets/06b28f09-9d30-4219-93f8-7209b6c73f44">

<img width="1061" alt="image" src="https://github.com/user-attachments/assets/3b55d658-845c-43c2-bba7-38ead699520f">

**Closed by twisterdotcom** 2024-07-23 11:25 UTC
Labels: External, Daily, Help Wanted, Bug
