### ISSUE TITLE
Request money: 0.00 is shown for a seconds before updating its amount

### ISSUE THREAD

**Issue by kavimuru** [Expensify/App#25523] opened 2023-08-19 12:31 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Open the website
2. click the + icon from LHN
3. click the request money
4. request money from user 1 to user 2
5. observe the result from user 2
## Expected Result: 
1. the requested amount is not to be 0.00 for a seconds
## Actual Result: 
the requested money is 0.00 for a second

## Workaround:
Can the user still use Expensify without this being fixed? Have you informed them of the workaround?

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [x] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 1.3.55-5
**Reproducible in staging?:** y
**Reproducible in production?:** n
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/43996225/4a2e0f6a-a05e-42c5-a3b6-a9f945bf41a0

https://github.com/Expensify/App/assets/43996225/6646434b-6a43-45dd-8cd5-df3a8a0a7fd5

**Expensify/Expensify Issue URL:**
**Issue reported by:** @misgana96
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1692242726950869

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by parteekcoder** [comment] 2023-08-19 13:01
Can I work on this issue @puneetlath ?

**Comment by s-alves10** [comment] 2023-08-19 15:59
## Proposal

### Please re-state the problem that we are trying to solve in this issue.

Request money: show 0.00 for seconds before updating its amount

### What is the root cause of that problem?

This is a regression from [this PR](https://github.com/Expensify/App/pull/24345)

Now we are getting amount and currency info from the transaction
https://github.com/Expensify/App/blob/03cf0b14f82a41db004dfee27799e3cea1608ee5/src/components/ReportActionItem/IOUPreview.js#L146-L147

We get pusher events for the newly created iou action but that events don't include any transaction data as you can see in the below screenshot
![image](https://github.com/Expensify/App/assets/126839717/b9bc7053-b148-4ef3-85bd-67c28aacacec)

We get transaction data when opening report
![image](https://github.com/Expensify/App/assets/126839717/1b06c032-48ab-4260-ad4d-60b36f4fc2dd)

When we open an IOU report, we have all actions data(from pusher events) but don't have transaction data. So `TransactionUtils.getLinkedTransaction` returns empty object until `OpenReport` API call is finished.

This is the root cause

### What changes do you think we should make in order to solve the problem?

Here is a solution

1. Restore the `getMoneyRequestAction` function in [ReportUtils.js](https://github.com/Expensify/App/blob/main/src/libs/ReportUtils.js)

```
function getMoneyRequestAction(reportAction = {}) {
    const originalMessage = lodashGet(reportAction, 'originalMessage', {});
    let amount = originalMessage.amount || 0;
    let currency = originalMessage.currency || CONST.CURRENCY.USD;
    let comment = originalMessage.comment || '';

    if (_.has(originalMessage, 'IOUDetails')) {
        amount = lodashGet(originalMessage, 'IOUDetails.amount', 0);
        currency = lodashGet(originalMessage, 'IOUDetails.currency', CONST.CURRENCY.USD);
        comment = lodashGet(originalMessage, 'IOUDetails.comment', '');
    }

    return {amount, currency, comment};
}
```

2. If transaction is empty, get the transaction data from the iou action. 
Replace this line
https://github.com/Expensify/App/blob/03cf0b14f82a41db004dfee27799e3cea1608ee5/src/components/ReportActionItem/IOUPreview.js#L146

with
```
    let transaction = TransactionUtils.getLinkedTransaction(props.action);
    if (_.isEmpty(transaction)) {
        transaction = ReportUtils.getMoneyRequestAction(props.action)
    }
```

This works as expected

**Note**: This is a workaround. I am suggesting this because this is a deploy blocker. This issue should be fixed in the backend(The backend should send pusher event including transaction)



### What alternative solutions did you explore? (Optional)

**Comment by mountiny** [comment] 2023-08-21 08:17
@s-alves10 this is not valid solution as we cannot rely on the reportAction data when request is being edited.

@puneetlath This is not a deploy blocker fwiw. The reason is that the ReportActionItem is not re-rendering when the transaction object changes, but we are working on this with @luacmartins and should be resolved soon

**Comment by luacmartins** [comment] 2023-08-21 15:45
This has the same root cause and is a dupe of https://github.com/Expensify/App/issues/24608. Closing.

**Closed by luacmartins** 2023-08-21 15:45 UTC
Labels: Engineering, Daily, Bug
