### ISSUE TITLE
[HOLD for payment 2023-10-23] [HOLD for payment 2023-10-23] [$500] Request money - Description briefly displayed in preview after adding a receipt from a manual request

### ISSUE THREAD

**Issue by izarutskaya** [Expensify/App#28380] opened 2023-09-28 09:53 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Open a chat.
2. Navigate to the "" option.
3. Enter the desired amount and click "Next"
4. Click on the three dots menu and select "Add receipt" and select a file
5. Enter a description and save it.
6. Now send the request.

## Expected Result:
The description should either be removed from the preview or not displayed at all

## Actual Result:
The description is briefly displayed in the preview when adding a receipt from a manual request

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [x] Android / Chrome
- [x] iOS / native
- [x] iOS / Safari
- [x] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** v1.3.74-2 

**Reproducible in staging?:** Y

**Reproducible in production?:** Y

**If this was caught during regression testing, add the test name, ID and link from TestRail:**

**Email or phone of affected tester (no customers):**

**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/115492554/3f9a2d10-0ba2-4587-a2e1-decfac909665

https://github.com/Expensify/App/assets/115492554/aeb12f0c-c925-4cd5-a6d6-084e35097d77

https://github.com/Expensify/App/assets/43996225/a92e8d8d-053e-4451-83b3-7862b78e9d77

https://github.com/Expensify/App/assets/43996225/c1d3badc-f044-4138-8418-d016e077c5f3

https://github.com/Expensify/App/assets/43996225/2ea49d8d-882e-4683-af7d-8367d3c0e947

**Expensify/Expensify Issue URL:**

**Issue reported by:** @ayazhussain79

**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1695666475040319

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01a6766bd5a43af155</li>
        <li>Upwork Job ID: 1707332794345508864</li>
        <li>Last Price Increase: 2023-10-13</li>
<li>Automatic offers: </li>
<ul>
<li>situchan | Contributor | 27104418</li>
<li>s-alves10 | Contributor | 27104428</li>
</ul></li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @peterdbarkerUK</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @peterdbarkerUK</details>

**Comment by ikevin127** [comment] 2023-09-28 12:03
# Proposal
## Please re-state the problem that we are trying to solve in this issue
The description is briefly displayed in the preview when adding a receipt from a manual request.

## What is the root cause of that problem?
The problem comes from the `ReportPreview.js` component:

```
{!isScanning && (numberOfRequests > 1 || hasReceipts) && (
    <View style={styles.flexRow}>
        <View style={[styles.flex1, styles.flexRow, styles.alignItemsCenter]}>
            <Text style={[styles.textLabelSupporting, styles.mb1, styles.lh20]}>{previewSubtitle || moneyRequestComment}</Text>
        </View>
    </View>
)}
```

This code block is supposed to render the number of requests if multiple requests exists. The problem is the OR operator between these two variables `previewSubtitle || moneyRequestComment`, initially `previewSubtitle` is empty hence why the description shows up because `moneyRequestComment` is being shown.

This changes as soon as `previewSubtitle` is not empty anymore and is replaced by the number of requests label.

## What changes do you think we should make in order to solve the problem?
I would create another component below the existing one where we will always render the request description like so:

```
{moneyRequestComment && (
    <View style={styles.flexRow}>
        <View style={[styles.flex1, styles.flexRow, styles.alignItemsCenter]}>
            <Text style={[styles.textLabelSupporting, styles.mb1, styles.lh20]}>
                {moneyRequestComment}
            </Text>
        </View>
    </View>
)}
```

## What alternative solutions did you explore? (Optional)
N/A

## Videos

https://github.com/Expensify/App/assets/56457735/05487e8d-222d-40f9-8b36-88d22420faf2

**Comment by situchan** [comment] 2023-10-04 03:54
Taking this over based on @ntdiary's [request](https://expensify.slack.com/archives/C02NK2DQWUX/p1696354088058899)

**Comment by peterdbarkerUK** [comment] 2023-10-06 13:57
sorry, I missed this due to travel at the weekend. BZ team review complete.

**Comment by peterdbarkerUK** [comment] 2023-10-09 12:01
@situchan - what do you think of the current proposals?

**Comment by situchan** [comment] 2023-10-09 13:19
@s-alves10's [proposal](https://github.com/Expensify/App/issues/28380#issuecomment-1739570206) looks good to me.
I think we should go with Solution 1 which fixes optimistic data as sending Merchant value in backend seems intentional.
Assigned engineer will confirm this in backend logic.
🎀 👀 🎀 C+ reviewed

**Comment by situchan** [comment] 2023-10-09 13:20
@peterdbarkerUK can you please assign me to this issue?

**Comment by bondydaa** [comment] 2023-10-09 17:07
hmm dang something might have gotten borked with the c+ switch-a-roo but @s-alves10 👍 go ahead with your proposal 1 to just fix this on the front end.

**Comment by s-alves10** [comment] 2023-10-09 19:25
@situchan 

PR is ready for review https://github.com/Expensify/App/pull/29118

**Comment by peterdbarkerUK** [comment] 2023-10-09 19:36
Thanks Bondy!

**Comment by peterdbarkerUK** [comment] 2023-10-13 13:24
ooops my bad, not deployed to staging yet.

**Comment by peterdbarkerUK** [comment] 2023-10-24 15:10
Summarizing payouts for this issue:

Issue reporter: @ayazhussain79 $50 (offer sent)

Contributor: @s-alves10 $750 (inc urgency bonus)

Contributor+: @situchan  $750 (inc urgency bonus) - please complete the [BZ checklist](https://github.com/Expensify/App/issues/28380#issuecomment-1765330191) and notify me here so that I can complete the payout. 

[Upwork Job](https://www.upwork.com/jobs/~01a6766bd5a43af155)

**Comment by peterdbarkerUK** [comment] 2023-10-30 14:26
@situchan could you complete [the checklist](https://github.com/Expensify/App/issues/28380#issuecomment-1765330191)?

**Comment by peterdbarkerUK** [comment] 2023-10-31 15:12
(Just a note for myself that ohter contribs have been paid, and contract closed)

**Comment by situchan** [comment] 2023-10-31 15:46
- [x] The PR that introduced the bug has been identified. Link to the PR: https://github.com/Expensify/App/pull/25924
- [x] The offending PR has been commented on, pointing out the bug it caused and why, so the author and reviewers can learn from the mistake. Link to comment: https://github.com/Expensify/App/pull/25924/files#r1377800775
- [x] A discussion in #expensify-bugs has been started about whether any other steps should be taken (e.g. updating the PR review checklist) in order to catch this type of bug sooner. Link to discussion: N/A
- [x] Determine if we should create a regression test for this bug.
- [x] If we decide to create a [regression test](https://github.com/Expensify/App/blob/main/contributingGuides/REGRESSION_TEST_BEST_PRACTICES.md) for the bug, please propose the regression test steps to ensure the same bug will not reach production again.

### Regression Test Proposal
1. Go to FAB > Request money > select Manual
2. Input any amount and click Next
3. Click on the three dots menu and select "Add receipt" and select a file
4. Enter a description and save
5. Tap "Request"
6. Verify that description is not shown and "Request" is shown in preview

**Comment by situchan** [comment] 2023-10-31 15:48
@peterdbarkerUK sorry for late. Can you also help with payment on #27710 please?

**Comment by ayazhussain79** [comment] 2023-10-31 18:04
@peterdbarkerUK can you please check you have ended contract on upwork without paying

**Comment by peterdbarkerUK** [comment] 2023-11-02 14:47
Ah shoot, my mistake @ayazhussain79 - I'd had to add you to the job and didn't correctly pay it out when closing. I've sent you a new contract offer, bump me here once you've accepted it!

**Comment by ayazhussain79** [comment] 2023-11-02 15:20
@peterdbarkerUK Np, Offer accepted and thank you

**Comment by peterdbarkerUK** [comment] 2023-11-02 15:25
Paid, thanks Ayaz!

**Comment by situchan** [comment] 2023-11-02 15:36
> @situchan I've updated the original issue, thanks for raising it and I'm sorry for the error.

No problem. Thanks

Also payment for this one (https://github.com/Expensify/App/issues/28380) is pending

**Comment by peterdbarkerUK** [comment] 2023-11-02 15:55
Haha one at a time! I'm working through these but being interrupted by an ongoing interview ;-)

**Comment by peterdbarkerUK** [comment] 2023-11-02 16:05
Paid! Leaving open so I can sort out the regression testing tomorrow.

**Closed** 2023-11-06 12:01 UTC
Labels: External, Daily, Overdue, Awaiting Payment, Bug
