### ISSUE TITLE
[NEED CHECKLIST] [$2000] Inconsistent margin for reacted emojis to different sort of comments

### ISSUE THREAD

**Issue by kavimuru** [Expensify/App#18681] opened 2023-05-09 21:33 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:

1. open a chat
2. send a pic, code block, strike-through text, normal comment, multi-line code block.
3. Now react to all of these with some emoji

## Expected results: 
margin should be same in each comment
## Actual results: 
different margin in different type of comments

## Workaround:
Can the user still use Expensify without this being fixed? Have you informed them of the workaround?

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [x] MacOS / Chrome / Safari
- [ ] MacOS / Desktop
 
**Version Number:** 1.3.12.0
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation
![image](https://github.com/Expensify/App/assets/43996225/6d86841e-f700-4866-8584-ecdac4fce3ec)

https://github.com/Expensify/App/assets/43996225/064488ef-4de0-4858-8d70-1b55731aca61

**Expensify/Expensify Issue URL:**
**Issue reported by:** @chiragxarora
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1683646365352769

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01bb4e86a533ae3fac</li>
        <li>Upwork Job ID: 1656675989014130688</li>
        <li>Last Price Increase: 2023-06-09</li>
<li>Automatic offers: </li>
<ul>
<li>abdulrahuman5196 | Reviewer | 26608577</li>
<li>chiragxarora | Reporter | 26608579</li>
</ul></li>
    </ul>
</details>

**Comment by dukenv0307** [comment] 2023-05-10 08:18
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
Inconsistent margin between different type of comments.
### What is the root cause of that problem?
The multi-line code block comment has margin vertical 8px.
https://github.com/Expensify/App/blob/45c3212061983394e0919839248512874c2af83f/src/components/HTMLEngineProvider/HTMLRenderers/PreRenderer/BasePreRenderer.js#L35
The same with the heading comment 
https://github.com/Expensify/App/blob/45c3212061983394e0919839248512874c2af83f/src/styles/styles.js#L136-L139
So that if comment has multi-line code block or heading at the end of itself, reacted emojis is further than the others.

Besides on web the heading comment has margin top default of the browser is 9.38px so it is misaligned.
### What changes do you think we should make in order to solve the problem?
We could pass `containerStyles` to `ReportActionItemReactions` component. If the comment has `h1` or `pre` tag at the end, we will pass the styles `mt0` or `mt2` if otherwise.
https://github.com/Expensify/App/blob/45c3212061983394e0919839248512874c2af83f/src/components/Reactions/ReportActionItemReactions.js#L74
### What alternative solutions did you explore? (Optional)
NA

**Comment by chiragxarora** [comment] 2023-05-11 06:44
Margins for image and normal comment also look different from what I see on the app @dukenv0307

**Comment by dukenv0307** [comment] 2023-05-11 06:49
@chiragxarora I just tested in web in I saw that it's not different. Is it different in mobile devices.

**Comment by dukenv0307** [comment] 2023-05-11 06:56
@chiragxarora The reason is normal comment has text in the vertical middle with font-size 17px and wrap component has height 20px. So that margins for image and normal comment seem different.

**Comment by chiragxarora** [comment] 2023-05-11 08:58
Ohh I get it now, but I think that should be adjusted accordingly so that all margins appear consistent to the end user

**Comment by abdulrahuman5196** [comment] 2023-05-12 08:18
Thank you for the proposal. Will take a look into it in couple of hours.

**Comment by abdulrahuman5196** [comment] 2023-05-13 17:01
@dukenv0307 The RCA seems to be correct. I would suggest to check all types of messages and not just heading and quote. It seems codeblock and blockquote is also slightly affected but not that much to see visually.

Regarding the solution, I think the solution would work but we would end up creating a dependency between the elements in the message and the top margin of reactions section. So In future if one's margin is to be changed, the other is also required to be changed which should be avoided IMO.

So I am keeping this issue open for more proposals.

**Comment by Beamanator** [comment] 2023-05-16 07:35
Not overdue, still looking for good proposals

**Comment by Beamanator** [comment] 2023-05-19 07:23
@abekkala I think it's fair to double this one 👍

**Comment by abdulrahuman5196** [comment] 2023-05-19 18:25
Sounds right to me as well to double as well.

**Comment by abdulrahuman5196** [comment] 2023-05-22 08:52
Waiting on @abekkala  to increase the bounty.

**Comment by payal-lathidadiya** [comment] 2023-05-22 18:51
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
Inconsistent margin between reacted emojis and different type of comments messages

### What is the root cause of that problem?
As checked for different types of messages including image, code block, strike-through text, normal comment, multi-line code block, only found spacing/margin difference for multiline code block and normal text.

1. For multiline code block, difference is due to top and bottom margin of 8px. code is [here](https://github.com/Expensify/App/blob/main/src/components/HTMLEngineProvider/HTMLRenderers/PreRenderer/BasePreRenderer.js#LL35)
1. For Normal text comment, difference is due to lineHeight attribute. For different font size, little higher line height is set. for fontSize: 15px -> lineHeight: 20px.

For other elements like image, inline code block or strike through text, no margin/gap is applied at bottom which can make inconsistence margin with reacted emoji.

### What changes do you think we should make in order to solve the problem?

1. Remove the `styles.mv2` from `BasePreRenderer` component. This doesn't cause any impact to visibility of how code block gets render along with other messages. Also, that's how it gets shown in other messaging app and portals.
2. Add the lineHeight style for Text comment to have default as `normal` instead of specific value and refer it for Text comment [here](https://github.com/Expensify/App/blob/main/src/pages/home/report/ReportActionItemFragment.js#LL121)
    ```
    lineHeightDefault: {
        lineHeight: 'normal',
    },
    ```
### What alternative solutions did you explore? (Optional)
None

**Comment by Victor-Nyagudi** [comment] 2023-05-23 18:39
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
Inconsistent margin for reacted emojis to different sort of comments

### What is the root cause of that problem?
Components inside each comment have varying margins. The `marginBottom` value plays the biggest role in causing the inconsistency in margin above the emoji reactions and the comment itself. 

The comments I've found that break consistency include:

- Headings e.g. '# Heading'
- Headings in a quote e.g. '> # Heading'
- IOU comments e.g. after requesting money, the margin below the IOU preview isn't consistent with other comments
- Comments with image attachments

It seems this margin being consistent may have been overlooked as changes were being made. 

Take a look at the margins we have on the different types of comments even without emoji reactions. 

<details>

<summary>Screenshot of comments</summary>

#### No emoji reactions

![expensify-different-comments](https://github.com/Expensify/App/assets/79470910/9903bba9-c665-4ba7-a881-684055a12b8f)

#### With emoji reactions

![expensify-different-comments-with-emoji-reactions](https://github.com/Expensify/App/assets/79470910/afd5d555-f993-4537-a07e-fca0dab6695b)

##### Part 2

![expensify-different-comments-with-emoji-reactions-pt-2](https://github.com/Expensify/App/assets/79470910/b13e951c-6942-4d89-ad69-338ad7e160ad)

</details>

### What changes do you think we should make in order to solve the problem?

This one could be a bit tricky, but here's what I thought could solve the problem.

After unsuccessfully attempting to use context to fix this (see next section), I decided some of the margins would have to be manually adjusted to accommodate emoji reactions. 

The one caveat with this approach is that the `IOUPreview` comment will have a little bit more margin below it than what's currently there. 

We'll first adjust the image attachment's margin here. 

https://github.com/Expensify/App/blob/228f40961e41549e8fc9755f6f0394a3f669edec/src/components/HTMLEngineProvider/HTMLRenderers/ImageRenderer.js#L63

The new margin will be adjusted down by `4.5`. This number is a bit "magic-numbery", but it was closest to the consistent margin in the other comments. Some of the numbers could be included in `styles.js` in line with what's currently being done instead of using raw styling i.e. use `styles.mb4` or something of the sort instead of `{marginBottom: 4.5}`. 

```javascript
styles={[styles.noOutline, styles.alignItemsStart, {marginBottom: 4.5}]}
```

`BasePreRenderer` is up next. 

https://github.com/Expensify/App/blob/228f40961e41549e8fc9755f6f0394a3f669edec/src/components/HTMLEngineProvider/HTMLRenderers/PreRenderer/BasePreRenderer.js#L35

I found this one is closer to being consistent when adjusted by `5`.

```javascript
style={[styles.mv2, styles.overscrollBehaviorNone, {marginBottom: 5}]}
```

The `defaultViewProps` for web will also need to be adjusted. The `lineHeight` is set to `0` to prevent the heading's container from being bigger than the actual heading text. 

https://github.com/Expensify/App/blob/228f40961e41549e8fc9755f6f0394a3f669edec/src/components/HTMLEngineProvider/defaultViewProps/index.web.js#L7

Here's the code with the adjustment.

```javascript
style: [styles.dBlock, styles.userSelectText, {lineHeight: 0}]
```

Finally, the heading tag styles will need to be adjusted for more consistency. 

https://github.com/Expensify/App/blob/228f40961e41549e8fc9755f6f0394a3f669edec/src/styles/styles.js#L136-L139

`marginTop` is set to `0`, and a little `marginBottom` is added.

```javascript
h1: {
    fontSize: variables.fontSizeLarge,
    marginTop: 0,
    marginBottom: 1,
},
```

<details>

<summary>Screenshots after my changes</summary>

#### Part 1

![expensify-different-comments-with-emoji-reactions-solution](https://github.com/Expensify/App/assets/79470910/223a72d5-f2c3-44bf-baf4-f473b9f2aceb)

#### Part 2

![expensify-different-comments-with-emoji-reactions-solution-pt-2](https://github.com/Expensify/App/assets/79470910/206ada1d-19e8-49e1-89fb-0e24b40606b0)

#### Part 3

![expensify-different-comments-with-emoji-reactions-solution-pt-3](https://github.com/Expensify/App/assets/79470910/04d3f7ee-6152-420b-97c3-253696c758d3)

</details>

### What alternative solutions did you explore? 

My initial approach involved adjusting each comment's margin only if it had emoji reactions. 

I created a `ReportActionItemReactionsContext` and wrapped the fragment in `ReportActionItem` with this context. 

https://github.com/Expensify/App/blob/228f40961e41549e8fc9755f6f0394a3f669edec/src/pages/home/report/ReportActionItem.js#L280-L300

The `value` of the context provider would be `hasReactions`, and this `Boolean` value is what would decide if an element's `marginBottom` is adjusted or not in the `style` prop. 

This initially worked, but when it got to `RenderHTML`, there was no way to pass this value to the rendered markdown since each tag's styles is defined in `BaseHTMLEngineProvider` that is not a descendant of `ReportActionItem`.

The nearest common ancestor I found between `ReportActionItem` and `BaseHTMLEngineProvider` was the `App` itself, but I found it ludicrous wrapping the entire app with a context provider to fix some small margin issues. 

At the end of the day, we could always do nothing for this one. It might be too little to address to me, but I'll be curious to hear what other people come up with.

**Comment by abekkala** [comment] 2023-05-24 14:37
@abdulrahuman5196 what do you think of the proposals that have come in?

**Comment by abdulrahuman5196** [comment] 2023-05-24 18:34
@payal-lathidadiya 

>Remove the styles.mv2 from BasePreRenderer component. This doesn't cause any impact to visibility of how code block gets render along with other messages

Why don't you think "This doesn't cause any impact to visibility of how code block gets render along with other messages"? This removes the current margin space and pre tag message look closer to each other

<img width="332" alt="Screenshot 2023-05-25 at 12 03 13 AM" src="https://github.com/Expensify/App/assets/46707890/5f34d1cf-18ed-4a2b-8fa6-2a0dae78a609">

With your change
<img width="412" alt="Screenshot 2023-05-25 at 12 04 09 AM" src="https://github.com/Expensify/App/assets/46707890/219490bb-6b30-4146-99ce-1df4b5a600f6">

**Comment by abdulrahuman5196** [comment] 2023-05-24 18:52
@Victor-Nyagudi Thank you for the dive deep testing. 
But still if we directly reduce margins like `style={[styles.mv2, styles.overscrollBehaviorNone, {marginBottom: 5}]}` it will reflect in all messages regardless of whether the tag is at middle or end. I don't think we want to that behaviour.

It could be similar to this comment https://github.com/Expensify/App/issues/18681#issuecomment-1561750915



But I like your alternative solution, It seems to be a good start 
As you mentioned,
>This initially worked, but when it got to RenderHTML, there was no way to pass this value to the rendered markdown since each tag's styles is defined in BaseHTMLEngineProvider that is not a descendant of ReportActionItem.

If we could come over this somehow and make custom margin bottom only for last element it would be great.

**Comment by Victor-Nyagudi** [comment] 2023-05-24 19:22
@abdulrahuman5196 I'm not sure what you mean by tag being in the middle or end.

What kind of tag are we talking about? 

Also, just something I left out is with context, I could adjust the `marginBottom` of `BasePreRenderer` based on a comment having reactions, but that was just about it - I couldn't adjust the other markdown comments with context.

I might revisit this in the next day or so to see if there's more I can do with context.

**Comment by abdulrahuman5196** [comment] 2023-05-24 19:26
>What kind of tag are we talking about?

<pre> html tag - i meant this.

**Comment by payal-lathidadiya** [comment] 2023-05-25 05:33
> @payal-lathidadiya
> 
> > Remove the styles.mv2 from BasePreRenderer component. This doesn't cause any impact to visibility of how code block gets render along with other messages
> 
> Why don't you think "This doesn't cause any impact to visibility of how code block gets render along with other messages"? This removes the current margin space and pre tag message look closer to each other
> 
> <img alt="Screenshot 2023-05-25 at 12 03 13 AM" width="332" src="https://user-images.githubusercontent.com/46707890/240709375-5f34d1cf-18ed-4a2b-8fa6-2a0dae78a609.png">
> With your change <img alt="Screenshot 2023-05-25 at 12 04 09 AM" width="412" src="https://user-images.githubusercontent.com/46707890/240709388-219490bb-6b30-4146-99ce-1df4b5a600f6.png">

@abdulrahuman5196 Agreed, but shouldn't this be as expected? Not sure why do we want to keep specific margins with code block rendered along with messages.

In fact, I found this behavior consistent with other messaging apps like slack, and others..

**Comment by abdulrahuman5196** [comment] 2023-05-27 10:37
>@abdulrahuman5196 Agreed, but shouldn't this be as expected? Not sure why do we want to keep specific margins with code block rendered along with messages.
In fact, I found this behavior consistent with other messaging apps like slack, and others..

@payal-lathidadiya I don't think we would want to change the margins of all code blocks inside a message which would result in the above behaviour(https://github.com/Expensify/App/issues/18681#issuecomment-1562297134) just to solve this issue.
Correct me if wrong. @Beamanator

**Comment by payal-lathidadiya** [comment] 2023-05-27 18:31
I completely agree. 

IMO, keeping or adjustment of margin based on message/comment type or order may lead to complexity of interface maintenance for any future update or enhancement.

Any padding or margin requirements should be handled outside of particular element logic and can be placed in container where they are used/referenced (in our case, for report creation) to keep them independent and loosely coupled .

**Comment by Victor-Nyagudi** [comment] 2023-05-29 14:54
## Proposal

[Updated](https://github.com/Expensify/App/issues/18681#issuecomment-1559955792)

**Comment by abdulrahuman5196** [comment] 2023-05-30 15:26
@Victor-Nyagudi  Thank you for updating the proposal. But still your proposal will be affected by this case right?
`Even if the block is in middle of the message its margin would be reduced if the message has been reacted`. Kindly correct me if I am wrong.

https://github.com/Expensify/App/issues/18681#issuecomment-1561750915

**Comment by Victor-Nyagudi** [comment] 2023-05-30 16:15
@abdulrahuman5196 Only the `marginBottom` will be adjusted when a message has emoji reactions.

This is in line with the other messages that don't have a `marginBottom` making the margin above the emoji reactions the 'single source of truth' in determining the spacing between the reactions and the message itself.

I'm curious why you think of adjusting the margin as a case. Do you see that as a bad thing?

**Comment by abdulrahuman5196** [comment] 2023-05-30 18:15
@Victor-Nyagudi 

>Only the marginBottom will be adjusted when a message has emoji reactions.

I am fine with this actually. My concern is it will apply to all code blocks.
For example all the test blocks(test block1, test block 2, etc) marginBottom will be reduced in this case regardless of whether it is in middle or last. Do we actually need that?  Correct me if wrong.

<img width="429" alt="Screenshot 2023-05-30 at 11 41 11 PM" src="https://github.com/Expensify/App/assets/46707890/aa2679d2-3bce-43fb-8526-6ab321fc971f">

**Comment by abdulrahuman5196** [comment] 2023-05-30 18:55
@Victor-Nyagudi 

>If a message has multiple code blocks, are you concerned each individual code block's marginBottom is adjusted when emoji reactions are present?

Yes exactly. I think the proposal will make all individual code block's marginBottom to be reduced. Correct me if wrong.

>I'm also not sure what you mean by adjusting the last element in a message. Kindly explain.

The arrowed block is the last element.
<img width="429" alt="242058395-aa2679d2-3bce-43fb-8526-6ab321fc971f" src="https://github.com/Expensify/App/assets/46707890/de1049e0-506e-4280-877d-9d2b4d1ea6e6">


<br/>

>I can link my branch with the changes so you can test them out on your fork, if you wish, and let me know what behavior you don't like.

As per current guidelines, we don't expect direct code changes. But dont hesitate to correct me if I had misunderstood the working of the proposal in any way.


>If I may ask, what would be wrong with adjusting the margin of a code block if it's the middle message?

This is good question. Let me try to summarize our findings as part of multiple peoples proposals and try to loop in others to see if we can have different expectation. But my expectation was to have a solution where we would only adjust the marginBottom of last text element in the whole message when we have emojis. But I am open to other better proposals or ideas.

**Comment by Victor-Nyagudi** [comment] 2023-05-30 19:05
@abdulrahuman5196 Okay. I understand you now. 

Let me test my solution with multiple code blocks, and I'll let you know how it goes.

**Comment by Victor-Nyagudi** [comment] 2023-05-31 09:25
You're correct, @abdulrahuman5196. 

The `marginBottom` will be adjusted for each code block when a message has been reacted to. Good catch. 

I'll get to work on a better solution.

**Comment by Beamanator** [comment] 2023-05-31 13:39
@abdulrahuman5196 are we close to getting a perfect proposal yet? Do we need to bring any convo to slack to get the design team's opinion or can i help with anything?

**Comment by abdulrahuman5196** [comment] 2023-06-01 22:44
Summary from proposals on high level:

https://github.com/Expensify/App/issues/18681#issuecomment-1541555678 - If the comment ends with pre or appropriate tags we will reduce reactions component top margin. Good one so far but has a code drawback as mentioned here - https://github.com/Expensify/App/issues/18681#issuecomment-1546710942

https://github.com/Expensify/App/issues/18681#issuecomment-1557733669 - Suggestion to reduce code blocks or appropriate html tags margins

https://github.com/Expensify/App/issues/18681#issuecomment-1559955792 
First solution - Suggestion to reduce/adjust code blocks margins.
Second solution - Dynamically reduce the margins when message has reactions.Good start but has a problem of all codeblocks getting margin reduced. https://github.com/Expensify/App/issues/18681#issuecomment-1568922392


I am actually not aligned in reducing/adjusting the margin of html elements in message to solve this issue. But its good to check with design team if we want to change the html elements margin to solve this issue as contributors requested.

I am ideal expecting a solution where for reacted messages alone it removes the margin bottom of last html element shown in the message. This could be hard due to technical limitation. But as always still open for different better proposals or updation of existing proposals.

@Beamanator  What do you think of the above? And one curious question is do we think this issue is worth a complex solution?

**Comment by Beamanator** [comment] 2023-06-06 20:18
@abdulrahuman5196 Thanks so much for your investigation so far, sorry for my delay, lots of bigger priorities at the moment 😅  

But overall I do think we should fix this since it is a bit weird that margins are inconsistent depending on the type of message being reacted to... Though I definitely would prefer NOT needing a complex solution. So if there's currently no other option than a complex solution, I think we should see if any expert groups can help us tie this one off

**Comment by chiragxarora** [comment] 2023-06-09 15:33
Damnn

**Comment by abekkala** [comment] 2023-06-09 15:36
@Beamanator can you confirm that a price increase is warranted to see more proposals that fit this to get it done!

**Comment by abdulrahuman5196** [comment] 2023-06-09 16:12
@abekkala  Isn't this issue made internal?

**Comment by abekkala** [comment] 2023-06-09 16:13
ahhaah yes. yes, it is. 
I was actually viewing two GH's at the same time and mixed them up!

**Comment by abekkala** [comment] 2023-06-19 19:48
@Beamanator is there an update on this one?

**Comment by Beamanator** [comment] 2023-06-19 19:55
sorry @abekkala - I don't have a lot of time to look into this, can we take it to expert groups since it's been open a while?

**Comment by abekkala** [comment] 2023-06-21 13:07
Hi @rezkiy37 can you provide an ETA on your proposal?

**Comment by rezkiy37** [comment] 2023-06-21 17:43
**Daily updates:**

1. The bug occurs on every platform.
2. I am still investigating.

**Comment by rezkiy37** [comment] 2023-06-22 17:49
**Daily updates:**

1. I am not ready yet to post a proposal today.
2. I found 2 solutions how to fix this odd behaviour.
3. Posting a proposal tomorrow.

**Comment by rezkiy37** [comment] 2023-06-23 15:22
> @rezkiy37 do you think you'll have a proposal ready today?

Unfortunately, not today. I faced one bug during fixed this issue, that required some time to figure it out. We are discussing possible solutions internally now. 

I believe proposal will be on Monday.

**Comment by rezkiy37** [comment] 2023-06-26 14:18
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
When a message is a **code-block**, it has **vertical margins** that being extended with **margins** of reactions. Visually, it looks like more space if compare with other messages, because all other message types do not have these extra **margins**.

### What is the root cause of that problem?
`BasePreRenderer` is responsible to render **code-blocks**. Inside the component there is `ScrollView` with **vertical margins**.

### What changes do you think we should make in order to solve the problem?
I consider a complex solution regarding spaces across the report screen.

There are many places where the same spacings are being specified within the codebase. I mean the same **margin** could be specified in a few places. It is hard to understand which place should be tweaked to align components.

The idea is to unify spacings between messages. Since, the app uses `FlatList` (in `ReportActionsList`) to render messages, we are able to use `ItemSeparator`. This way I can remove a few duplicated **margin** styles in several places: `MoneyRequestAction` , `ReportActionItemMessage` , **vertical paddings** of `styles.chatItem`.
Also, the app uses `getItemLayout` under the hood of `BaseInvertedFlatList` . I would pass `separatorHeight` prop only to `InvertedFlatList` , if the prop comes to `InvertedFlatList` , the component adds it to `offset` and renders the separator itself.

The next step is to fix **margins** of **code-blocks** themself. `BasePreRenderer` receives 2 important props to understand is it a list of **code-blocks**: `renderLength` and `renderIndex`. Based on them, I would add **margin bottom** for the blocks, except the last one (to avoid extra space at the bottom). This way `BasePreRenderer` is not connected with the outside logic/UI, it is still independent. It has spacing only within own children and no outside **margins**.

### What alternative solutions did you explore?
There is another solution how to fix these weird **margins** only. 
I propose to use **margin top** instead of the **vertical**. This way it fixes extra-gap between the reactions and **code-blocks**. 
Also, the app still have all current spaces between items.

1. Open `BasePreRenderer`.
2. Replace `styles.mv2` with `styles.mt2` in `ScrollView`.

**Comment by abekkala** [comment] 2023-06-26 17:39
@abdulrahuman5196 can you review the proposal from @rezkiy37 when you have a moment? 😃

**Comment by abekkala** [comment] 2023-06-28 14:33
@abdulrahuman5196 have you reviewed the proposal yet?

**Comment by abdulrahuman5196** [comment] 2023-06-28 14:37
Hey sorry @abekkala , Was caught up in other issues, will close out on review today.

**Comment by abdulrahuman5196** [comment] 2023-06-28 18:03
@rezkiy37 

>The idea is to unify spacings between messages. Since, the app uses FlatList (in ReportActionsList) to render messages, we are able to use ItemSeparator. This way I can remove a few duplicated margin styles in several places: MoneyRequestAction , ReportActionItemMessage , vertical paddings of styles.chatItem.
Also, the app uses getItemLayout under the hood of BaseInvertedFlatList . I would pass separatorHeight prop only to InvertedFlatList , if the prop comes to InvertedFlatList , the component adds it to offset and renders the separator itself.

I think this would be good, but AFAIK other types of messages isn't affected by this issue. So I think this could be added as an extra layer on top of what we are trying to solve in the text message.


>The next step is to fix margins of code-blocks themself. BasePreRenderer receives 2 important props to understand is it a list of code-blocks: renderLength and renderIndex. Based on them, I would add margin bottom for the blocks, except the last one (to avoid extra space at the bottom). This way BasePreRenderer is not connected with the outside logic/UI, it is still independent. It has spacing only within own children and no outside margins.

I agree this would be good and was the idea i was looking out for. But could you provide references on how you would achieve this, since I am unable to find references of `renderLength and renderIndex`. And the proposal is also not having enough references.


I am not aligning with alternate solution since it will be weird looking if we have multiple code blocks in the same message.

**Comment by rezkiy37** [comment] 2023-06-29 08:54
@abdulrahuman5196 Firstly, thank you for the review. 

> I think this would be good, but AFAIK other types of messages isn't affected by this issue. So I think this could be added as an extra layer on top of what we are trying to solve in the text message.
- Exactly!

> I agree this would be good and was the idea i was looking out for. But could you provide references on how you would achieve this, since I am unable to find references of renderLength and renderIndex. And the proposal is also not having enough references.
- Let me attach links to the official doc of [react-native-render-html](https://meliorence.github.io/react-native-render-html/docs/intro) and an example.There is the [renderLength](https://meliorence.github.io/react-native-render-html/api/rendererbaseprops#renderlength) and [renderIndex](https://meliorence.github.io/react-native-render-html/api/rendererbaseprops#renderindex). 
```javascript
const BasePreRenderer = forwardRef((props, ref) => {
    ...
    // The condition is being created here
    const isLast = props.renderLength - 1 === props.renderIndex;

    return (
        <ScrollView
            // The condition is being used here
            style={[!isLast && styles.mb2, styles.overscrollBehaviorNone]}
            ...
        >
        ...
``` 

> I am not aligning with alternate solution since it will be weird looking if we have multiple code blocks in the same message.
- Not actually. As I said previously, the alternate solution fixes only the bottom space, all other spaces are legacy (current). Let me share how it looks like:
<img width="550" alt="Screenshot 2023-06-29 at 10 52 07" src="https://github.com/Expensify/App/assets/57314631/d54fbe2d-651d-48e7-9b9c-381a168f9418">
<img width="550" alt="Screenshot 2023-06-29 at 10 52 53" src="https://github.com/Expensify/App/assets/57314631/f6ba2d18-55c7-4906-ba58-137b07aeb1de">

**Comment by rezkiy37** [comment] 2023-06-29 14:41
@abdulrahuman5196 Please let me know a kind of final decision and which changes should I implement. Thank you!

**Comment by abdulrahuman5196** [comment] 2023-06-30 14:52
Hi @rezkiy37 I like the idea of renderLength and renderIndex. Seems to be a scalable solution for future as well.
And one more final thing to ask is not just the 'Codeblock' which is affected there are other text formats affected by the same as mentioned on the issue description like `single tick message`(But not to the extend of Codeblock). Can we expect similar fix there as well? If so i am good with the solution.

![237225658-6d86841e-f700-4866-8584-ecdac4fce3ec](https://github.com/Expensify/App/assets/46707890/65a5fa45-ea3a-485b-9606-8232eac24428)

**Comment by abekkala** [comment] 2023-06-30 20:11
@conorpendergrast Reassigning for sabbatical

___

### CURRENT STATUS: 

- Issue reported by: @chiragxarora
- Assigned for fix: @rezkiy37 (Callstack)
- C+: @abdulrahuman5196 

We need to get a PR merged!

**Comment by rezkiy37** [comment] 2023-06-30 20:15
> Hi @rezkiy37 I like the idea of renderLength and renderIndex. Seems to be a scalable solution for future as well. And one more final thing to ask is not just the 'Codeblock' which is affected there are other text formats affected by the same as mentioned on the issue description like `single tick message`(But not to the extend of Codeblock). Can we expect similar fix there as well? If so i am good with the solution.
> 
> ![237225658-6d86841e-f700-4866-8584-ecdac4fce3ec](https://user-images.githubusercontent.com/46707890/250120892-65a5fa45-ea3a-485b-9606-8232eac24428.png)

Yes, I am going to align those test formats as well. 
Sounds good and I am moving forward to develop and prepare a PR. Thank you!

**Comment by conorpendergrast** [comment] 2023-07-06 15:56
[Offers sent](https://www.upwork.com/ab/applicants/1656675989014130688/hired) to @chiragxarora and @abdulrahuman5196 via Upwork.

**Comment by abdulrahuman5196** [comment] 2023-07-13 20:12
PR in review melvin

**Comment by Beamanator** [comment] 2023-07-25 08:06
PR still in review

**Comment by conorpendergrast** [comment] 2023-08-01 09:39
Looks like the PR is still in review

**Comment by conorpendergrast** [comment] 2023-08-03 12:09
PR is actively being worked on 👍

**Comment by conorpendergrast** [comment] 2023-08-08 10:07
Looks like the PR is still under review

**Comment by abdulrahuman5196** [comment] 2023-08-23 15:56
Still in review

**Comment by rezkiy37** [comment] 2023-09-04 13:37
Continue discussion within the PR - https://github.com/Expensify/App/pull/22010#issuecomment-1701303078. 
Please consider the alternative solution from here - https://github.com/Expensify/App/issues/18681#issuecomment-1607593518.

**Comment by teneeto** [comment] 2023-09-11 11:35
Hi, I'm Eto from Callstack - expert contributor group - I'm currently looking into a different approach into this issue. Hence I'll assist @rezkiy37 from here.

**Comment by conorpendergrast** [comment] 2023-09-11 11:39
@jliexpensify I'm on parental leave; re-assigning! The fix is in the works here and it looks like @teneeto is now also helping out!

**Comment by rezkiy37** [comment] 2023-09-18 17:35
@abdulrahuman5196, a friendly reminder about - https://github.com/Expensify/App/pull/22010#issuecomment-1714832949.

**Comment by rezkiy37** [comment] 2023-09-26 12:23
Melvin, still waiting on some feedback here - https://github.com/Expensify/App/issues/18681#issuecomment-1724063340.
cc @abdulrahuman5196

**Comment by jliexpensify** [comment] 2023-09-26 23:04
@rezkiy37 looks like Abdul has very limited internet access. @Beamanator - are we blocked on Abdul? If so - does this need to be reassigned to another C+? Your call, also happy to discuss in person today!

**Comment by Beamanator** [comment] 2023-09-27 04:16
It looks like it, yes :'( Can you post in #contributor-plus to see if abdul will respond & if not, we go for another C+?

**Comment by jliexpensify** [comment] 2023-09-27 04:27
@Beamanator how about we just reassign? There's been multiple bumps for Abdul here so the quickest resolution is to give this to someone else.

**Comment by abdulrahuman5196** [comment] 2023-09-27 04:46
@jliexpensify sorry for the delay I am just back from Ooo. Will close this out Today

**Comment by rezkiy37** [comment] 2023-09-28 11:14
Good news. We are on the same page now:

- Preview of a new approach - https://github.com/Expensify/App/pull/22010#issuecomment-1737064888
- Approval for the new approach - https://github.com/Expensify/App/pull/22010#issuecomment-1737611391

Continue working on!

**Comment by jliexpensify** [comment] 2023-10-18 01:14
Wow this is an old issue! Hopefully this is correct:

Payment Summary

- Bug Reporter: @chiragxarora $250
- Contributor: @rezkiy37 $2000 
- C+: @abdulrahuman5196 $2000 

[NEW UPWORKS JOB](https://www.upwork.com/jobs/~015ad33883c8ab35ff)

The PR was merged in 76 days, so this would not qualify for any payment. However, since there were a few approaches [discussed](https://github.com/Expensify/App/issues/18681#issuecomment-1738948171), does it make sense to penalise here @Beamanator ?

**Comment by abdulrahuman5196** [comment] 2023-10-18 12:50
I am not sure if penalizing here is correct. We actually faced multiple issues down the line and had to switch approaches to fix the same which would have been unavoidable in this case. Since we couldn't find suitable proposal from external contributors and went to expert agencies for better solution as last resort as well.

**Comment by jliexpensify** [comment] 2023-10-19 01:39
Thanks for the context @abdulrahuman5196 - yes, I agree: I wouldn't penalise this issue given there was a switch in approach. Thanks, and will pay out now.

**Comment by jliexpensify** [comment] 2023-10-19 02:10
Paid and job removed

**Comment by jliexpensify** [comment] 2023-10-19 02:11
Oh whoops - @abdulrahuman5196 have you completed the checklist? It doesn't look like it.

**Comment by abdulrahuman5196** [comment] 2023-10-19 07:06
>The PR that introduced the bug has been identified. Link to the PR:
The offending PR has been commented on, pointing out the bug it caused and why, so the author and reviewers can learn from the mistake. Link to comment:
A discussion in #expensify-bugs has been started about whether any other steps should be taken (e.g. updating the PR review checklist) in order to catch this type of bug sooner. Link to discussion:

Not a regression but something missed during implementation

>Determine if we should create a regression test for this bug.

yes.

>If we decide to create a regression test for the bug, please propose the regression test steps to ensure the same bug will not reach production again.


1) Open any chat.
2) Create any type of messages like text, code-blocks, quote, attachment, etc.
3) Add emojis.
4) Verify that spacings are the same between all messages and emojis. Especially code-blocks and its reactions.


@jliexpensify Added the checklist. Sorry for missing it.

**Comment by jliexpensify** [comment] 2023-10-22 04:05
All good, closing!

**Closed by jliexpensify** 2023-10-22 04:05 UTC
Labels: External, Daily, Bug
