### ISSUE TITLE
Status- Date "Clear After" of Status is Unstable

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#50170] opened 2024-10-03 16:46 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 9.0.44-1
**Reproducible in staging?:** Y
**Reproducible in production?:** N
**If this was caught during regression testing, add the test name, ID and link from TestRail:** N/A
**Email or phone of affected tester (no customers):** applausetester+tw4355353122@applause.expensifail.com
**Issue reported by:** Applause - Internal Team

## Action Performed:
1. Go to Account Settings > Profile
2. Add a status and click Save

## Expected Result:
The Status "Clear After" date should remain stable

## Actual Result:
The Status "Clear After" date is unstable

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

<details>
  <summary>Add any screenshot/video evidence</summary>

  
</details> 

https://github.com/user-attachments/assets/82c9b42d-1ee5-4870-9909-6aa198a400e5

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~021841884588235486621</li>
        <li>Upwork Job ID: 1841884588235486621</li>
        <li>Last Price Increase: 2024-10-03</li>
<li>Automatic offers: </li>
<ul>
<li>ahmedGaber93 | Contributor | 104251800</li>
<li>Krishna2323 | Contributor | 104251856</li>
</ul></li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @jayeshmangwani</details>

**Comment by jasperhuangg** [comment] 2024-10-03 16:55
Super minor display bug that doesn't need to block deploy. Actually don't really think this needs fixing at all, going to close it out. Took me a few tries to even notice what the OP was describing.

**Comment by jasperhuangg** [comment] 2024-10-03 16:59
@Krishna2323 if you could look into this regression that would be great.

**Comment by mkzie2** [comment] 2024-10-04 03:12
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
- When saving status, the Status "Clear After" date is changed to "Never" for a while.

### What is the root cause of that problem?
- When clicking "Save" button, we call User.clearDraftCustomStatus():

https://github.com/Expensify/App/blob/821edc51788b616e323cae0dc00f4b0aa7246766/src/pages/settings/Profile/CustomStatus/StatusPage.tsx#L108

it makes the dataToShow:
https://github.com/Expensify/App/blob/821edc51788b616e323cae0dc00f4b0aa7246766/src/pages/settings/Profile/CustomStatus/StatusPage.tsx#L56
is "", and because the modal is not closed immediately:

https://github.com/Expensify/App/blob/821edc51788b616e323cae0dc00f4b0aa7246766/src/pages/settings/Profile/CustomStatus/StatusPage.tsx#L128

so the "Never" is the fallback value.

### What changes do you think we should make in order to solve the problem?
Remove:

https://github.com/Expensify/App/blob/821edc51788b616e323cae0dc00f4b0aa7246766/src/pages/settings/Profile/CustomStatus/StatusPage.tsx#L108
will fix the issue since we already have the cleanup function:

https://github.com/Expensify/App/blob/821edc51788b616e323cae0dc00f4b0aa7246766/src/pages/settings/Profile/CustomStatus/StatusPage.tsx#L142

### What alternative solutions did you explore? (Optional)
Remove the InteractionManager.runAfterInteractions in:

https://github.com/Expensify/App/blob/821edc51788b616e323cae0dc00f4b0aa7246766/src/pages/settings/Profile/CustomStatus/StatusPage.tsx#L128-L130

and just need navigateBackToPreviousScreen();

**Comment by mkzie2** [comment] 2024-10-04 03:18
@jasperhuangg It is easy to reproduce the bug in IOS/Android native and based on RCA, I think it is not related to @Krishna2323 's [PR](https://github.com/Expensify/App/pull/49914):


https://github.com/user-attachments/assets/8cb4f936-30a5-44d0-9943-01f966872890

**Comment by ahmedGaber93** [comment] 2024-10-04 15:06
> @jasperhuangg, ..., and I believe it’s happening due to the migration to useOnyx. The [PR changes](https://github.com/Expensify/App/pull/49914/files) are very straightforward—we just prevented multiple navigation.

@jasperhuangg I agree with that, this issue not a regression from our fix, it seems it is appeared after migration to `useOnyx`. I think we should fix it here as a new issue.

**Comment by jasperhuangg** [comment] 2024-10-07 17:17
Yeah agree that we don't really need to fix this. Also agree that it isn't a regression from the PR, and that it was caused separately by the useOnyx migrations.

**Closed by jasperhuangg** 2024-10-07 17:17 UTC
Labels: External, Engineering, Daily, Overdue, Bug

**Comment by mkzie2** [comment] 2024-11-25 03:09
@jasperhuangg A similar issue is reported in [here](https://github.com/Expensify/App/issues/53046). I think we should re-open this one.
