### ISSUE TITLE
[$500] IOU - On scan split with 2 users, individual IOU details page shows hhm not here

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#37758] opened 2024-03-05 14:51 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.47
**Reproducible in staging?:** Y
**Reproducible in production?:** N
**If this was caught during regression testing, add the test name, ID and link from TestRail:** https://expensify.testrail.io/index.php?/tests/view/4382182
**Email or phone of affected tester (no customers):** 
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** Applause - Internal Team
**Slack conversation:**

## Action Performed:
1. Launch app
2. Tap fab-- request money---scan
3. Upload image using camera
4. Select 2 contacts as split
5. Complete the flow & tap split
6. Open the newly created expense
7. Enter an amount
8. Tap split
9. Open the newly created expense
10. In details page, tap individual split amount
11. Tap message user
12. Tap individual IOU to open details page

## Expected Result:
On scan split with 2 users, individual IOU details page must show IOU details

## Actual Result:
On scan split with 2 users, individual IOU details
page shows hhm not here

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [x] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details>  

https://github.com/Expensify/App/assets/78819774/c1fd00c1-045e-41d9-adb1-86a4ea87b728

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~014b9c1a7230c9adfe</li>
        <li>Upwork Job ID: 1765081849283305472</li>
        <li>Last Price Increase: 2024-03-05</li>
    </ul>
</details>

**Comment by flodnv** [comment] 2024-03-05 18:28
Discussion here: https://expensify.slack.com/archives/C01GTK53T8Q/p1709662763360039

**Comment by flodnv** [comment] 2024-03-05 19:17
Tried twice, I can't reproduce, asking for a retest.

**Comment by flodnv** [comment] 2024-03-05 20:28
I think I was able to reproduce? Unsure, I am not getting the "not found" page, but I am getting an infinite loading skeleton.. The only thing I did differently was to use an inexistent account for the split.

**Comment by flodnv** [comment] 2024-03-05 20:30
I can also reproduce by clicking on the IOU on the receiving account

**Comment by paultsimura** [comment] 2024-03-05 22:21
One eternity later, I managed to find the offending PR: https://github.com/Expensify/App/pull/36713
It's the onyx bump from `2.0.7` to `2.0.10` that causes the regression, confirmed by reverting to `2.0.7`.

**Comment by roryabraham** [comment] 2024-03-06 00:05
@paultsimura is checking if this is fixed by https://github.com/Expensify/App/pull/37804

I was able to reproduce this on dev but was getting an image upload error earlier on when initiating a smartscan, so I'm not sure if I was experiencing the same issue or a dev environment issue

**Comment by roryabraham** [comment] 2024-03-06 01:33
should be fixed by https://github.com/Expensify/App/pull/37804

**Comment by roryabraham** [comment] 2024-03-06 06:01
requested retest: https://expensify.slack.com/archives/C9YU7BX5M/p1709704859552489

**Comment by kavimuru** [comment] 2024-03-06 13:41
Bug is fixed in the build 1.4.47-7. 

https://github.com/Expensify/App/assets/43996225/e4e0aee8-4b34-4564-ba13-1515cdd87ae4

**Comment by flodnv** [comment] 2024-03-06 13:48
Thanks!!! 👌

**Closed by flodnv** 2024-03-06 13:48 UTC
Labels: DeployBlockerCash, External, Engineering, Hourly
