### ISSUE TITLE
Web - Thread - The parent thread becomes blank and all messages are deleted momenterly  when refreshing the page after assigning tasks

### ISSUE THREAD

**Issue by izarutskaya** [Expensify/App#26189] opened 2023-08-29 12:06 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Click on the plus sign and select "Assign Task".
2. Add a title, assignee, and share location, then confirm the task.
3. Go to the parent thread.
4. Refresh the page and observe that the page turns blank and all messages are deleted.

## Expected Result:
The parent thread should not become blank and all messages should not be deleted momentarily when refreshing the page after assigning tasks.

## Actual Result:
The parent thread becomes blank and all messages are deleted when refreshing the page after assigning tasks.

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [x] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** v1.3.58-1

**Reproducible in staging?:** Y

**Reproducible in production?:** N

**If this was caught during regression testing, add the test name, ID and link from TestRail:**

**Email or phone of affected tester (no customers):**

**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/115492554/6176c73b-8330-4820-aa79-0c0d113e6aaa

https://github.com/Expensify/App/assets/115492554/e19a49ad-02e1-40c4-a538-7aa4d33cdb82

**Expensify/Expensify Issue URL:**

**Issue reported by:** @tewodrosGirmaA

**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1693291986016839

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by srikarparsi** [comment] 2023-08-29 15:42
Hey, I'm not able to reproduce this. Am I missing something @izarutskaya?

https://github.com/Expensify/App/assets/48188732/c3fee986-bdfb-49e5-8d4d-02fb8b62ffbc

**Comment by tewodrosGirmaA** [comment] 2023-08-29 15:54
@srikarparsi , I am not able to open the vedio

**Comment by srikarparsi** [comment] 2023-08-29 15:57
Hm, maybe this will work?

https://github.com/Expensify/App/assets/48188732/4bc93e71-9e29-4793-a738-3760afa59c92

**Comment by srikarparsi** [comment] 2023-08-29 17:20
Hm I'm still not able to reproduce. @tewodrosGirmaA do you think you could maybe double check your staging version?

**Comment by luacmartins** [comment] 2023-08-29 17:46
I can reproduce this in staging, but it has the same root cause as https://github.com/Expensify/App/issues/26181, where the response from `ReconnectApp` has the wrong format for reportActions. I'm gonna close this one in favor of https://github.com/Expensify/App/issues/26181 since the investigation is further along there.

**Closed** 2023-08-29 17:46 UTC
Labels: Engineering, Hourly, Bug
