### ISSUE TITLE
[HOLD for payment 2023-06-29] App crashes when trying to use mention `@`

### ISSUE THREAD

**Issue by kavimuru** [Expensify/App#20969] opened 2023-06-17 16:58 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Go to any chat
2. In the compose box type `@` to mention

## Expected Result:
List of emails should popup
## Actual Result:
App crashed
## Workaround:
Can the user still use Expensify without this being fixed? Have you informed them of the workaround?

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [x] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 1.3.29-0
**Reproducible in staging?:** y
**Reproducible in production?:** n
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/43996225/302401c6-eb71-4d1c-8e13-f101fa1a1c60

**Expensify/Expensify Issue URL:**
**Issue reported by:** applause internal team
**Slack conversation:** 

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~0106cd32b2d6c18034</li>
        <li>Upwork Job ID: 1674284198851424256</li>
        <li>Last Price Increase: 2023-06-29</li>
    </ul>
</details>

**Comment by kadiealexander** [comment] 2023-06-19 06:47
@abekkala I'm heading OOO so reassigning this to make sure it's looked after while I'm gone. If it's still open when I'm back next Monday I'll take it back!

**Comment by MonilBhavsar** [comment] 2023-06-19 13:24
We wouldn't send login(email) now for all accounts, so we need to adjust mentions logic to use display name if it is set

**Comment by luacmartins** [comment] 2023-06-19 21:20
We merged a fix. Removing the label. Gonna keep this issue open to process payment.

**Comment by luacmartins** [comment] 2023-06-21 01:23
I believe that @allroundexperts's proposal might still be necessary. I see a few Crashlytics reports, like the one below:

```
Non-fatal Exception: io.invertase.firebase.crashlytics.JavaScriptError: Cannot read property 'toLowerCase' of undefined
       at .getStyledTextArray(address at index.android.bundle:1:4687047)
       at .renderSuggestionMenuItem(address at index.android.bundle:1:4691110)
       at .renderSuggestionMenuItem(address at index.android.bundle:1:4688884)
       at .render(address at index.android.bundle:1:504538)
       at .renderProp(address at index.android.bundle:1:504633)
       at ._renderElement(address at index.android.bundle:1:556147)
       at .render(address at index.android.bundle:1:556286)
       at .finishClassComponent(address at index.android.bundle:1:367940)
       at .updateClassComponent(address at index.android.bundle:1:367801)
       at .beginWork$1(address at index.android.bundle:1:401149)
       at .performUnitOfWork(address at index.android.bundle:1:387954)
       at .workLoopSync(address at index.android.bundle:1:387815)
       at .renderRootSync(address at index.android.bundle:1:387699)
       at .performSyncWorkOnRoot(address at index.android.bundle:1:385116)
       at .flushSyncCallbacks(address at index.android.bundle:1:349437)
       at .scheduleUpdateOnFiber(address at index.android.bundle:1:382255)
       at .enqueueSetState(address at index.android.bundle:1:397598)
       at .anonymous(address at index.android.bundle:1:123199)
       at .calculateMentionSuggestion(address at index.android.bundle:1:4670217)
       at .apply((native):0:0)
       at .later(address at index.android.bundle:1:1020741)
       at .apply((native):0:0)
       at .anonymous(address at index.android.bundle:1:236193)
       at ._callTimer(address at index.android.bundle:1:235475)
       at .callTimers(address at index.android.bundle:1:237277)
       at .apply((native):0:0)
       at .__callFunction(address at index.android.bundle:1:139405)
       at .anonymous(address at index.android.bundle:1:137770)
       at .__guard(address at index.android.bundle:1:138723)
       at .callFunctionReturnFlushedQueue(address at index.android.bundle:1:137728)
```

**Comment by MonilBhavsar** [comment] 2023-06-21 07:28
> I believe that @allroundexperts's proposal might still be necessary. I see a few Crashlytics reports, like the one below:

@luacmartins that's weird, It shouldn't happen. Where do we see this? Is it happening frequently for all users or people on old app

**Comment by luacmartins** [comment] 2023-06-21 16:27
I haven't seen it on the latest staging version, so maybe it was fixed. I'll come back here if I see any new occurrence

**Comment by kadiealexander** [comment] 2023-06-26 03:07
Thanks for keeping this warm for me, April! Taking it back off you now :)

**Comment by kadiealexander** [comment] 2023-06-29 04:12
@MonilBhavsar can this one be closed since it was all resolved internally?

**Comment by MonilBhavsar** [comment] 2023-06-29 04:19
@0xmiroslav reviewed the PR. So I think we might need to pay them

**Comment by kadiealexander** [comment] 2023-06-29 05:16
@0xmiroslav please let me know when you've accepted the offer!

**Comment by kadiealexander** [comment] 2023-06-30 04:43
All paid! @MonilBhavsar is the checklist necessary here or can we close this out?

**Comment by MonilBhavsar** [comment] 2023-06-30 05:03
Thanks! we can close this out as it was a kind of expected regression from personalDetails migration. We already have QA tests for mentions

**Closed by MonilBhavsar** 2023-06-30 05:03 UTC
Labels: Engineering, Daily, Internal, Awaiting Payment, Bug
