### ISSUE TITLE
[HOLD for payment 2024-07-10] [$250] Web - Profile - Notify me about new messages disappears from profile page

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#43218] opened 2024-06-06 19:59 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.80-1
**Reproducible in staging?:** y
**Reproducible in production?:** y
**Issue reported by:** Applause - Internal team

## Action Performed:
1. Login with a expensifail account
2. Go to FAB> Start chat> Search for a expensifail account and create new chat
3. Click on the header to view user details

## Expected Result:
Notify me about new messages option should appear and remain

## Actual Result:
Notify me about new messages disappears from profile page

## Workaround:
n/a

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

https://github.com/Expensify/App/assets/93399543/297f6a70-1c5c-45f5-9f68-7d6622497811

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~015aa8cecd7682d626</li>
        <li>Upwork Job ID: 1800065189510532413</li>
        <li>Last Price Increase: 2024-06-10</li>
<li>Automatic offers: </li>
<ul>
<li>DylanDylann | Reviewer | 102711970</li>
<li>dominictb | Contributor | 102711971</li>
</ul></li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @VictoriaExpensify</details>

**Comment by Tony-MK** [comment] 2024-06-07 10:56
## Proposal

### Please re-state the problem that we are trying to solve in this issue.

Web - Profile - Notify me about new messages disappears from profile page

### What is the root cause of that problem?

In the profile page, we only show the `notify me` menu item based mainly on the user's `report.notificationPreference` is `CONST.REPORT.NOTIFICATION_PREFERENCE.HIDDEN`

https://github.com/Expensify/App/blob/4fcc5a9fbef90114ab4f38a1be698c471e3e75d1/src/pages/ProfilePage.tsx#L153-L155

Hence, if the user is new and the personal details get synced from the backend, the `notfiy me` menu item disappears because the user has never chatted with him.

https://github.com/Expensify/App/blob/4fcc5a9fbef90114ab4f38a1be698c471e3e75d1/src/pages/ProfilePage.tsx#L259-L266

### What changes do you think we should make in order to solve the problem?


Therefore, let's remove the condition `report.notificationPreference !== CONST.REPORT.NOTIFICATION_PREFERENCE.HIDDEN` to make the `shouldShowNotificationPreference` boolean is `true` even if the user's `report.notificationPreference` is  `CONST.REPORT.NOTIFICATION_PREFERENCE.HIDDEN`

So something like below should work.

```
const shouldShowNotificationPreference = !isEmptyObject(report) && !isCurrentUser && !!report.notificationPreference;
```

**Comment by VictoriaExpensify** [comment] 2024-06-10 07:20
This looks ok to me. I've added the project and the External label

**Comment by DylanDylann** [comment] 2024-06-12 08:40
Thanks for your proposals

@Tony-MK Your change may break other places because we need to hide `Notify me about new messages` option if `notificationPreference` is "hidden"

@dominictb Your proposal looks promising if we want to hide `Notify me about new messages` option for new users. 
Note that: this problem happens with all new users while creating a new chat (not only the expensifail account) because we have an inconsistency between BE and FE about the `notificationPreference` for  the new chat

**Comment by DylanDylann** [comment] 2024-06-12 08:55
>  if we don't send any message in this report. It's the same behavior with iou report or transaction thread report.

Ah, It makes sense to me

**Comment by DylanDylann** [comment] 2024-06-12 08:56
Let's go with @dominictb's [proposal](https://github.com/Expensify/App/issues/43218#issuecomment-2157793520) as explained [here](https://github.com/Expensify/App/issues/43218#issuecomment-2162466547)

🎀👀🎀 C+ reviewed

**Comment by DylanDylann** [comment] 2024-06-17 09:09
While reviewing PR, I see that we don't always want to hide the `notificationPreference` of the report. It depends on which report.
1. If the user doesn't exist on the Expensify, the BE return `notificationPreference: hidden`
2. If the user exists on the EPSF but the current user has never chatted with them before, the BE returns `notificationPreference: always`


@dominictb Could you help to confirm that?

**Comment by DylanDylann** [comment] 2024-06-17 10:11
@cead22 It is a bit tough if we want to mimic the `notificationPreference` like the back-end in the `optimisticData` because in the front-end we can't verify whether the user exists on Expensify or not. Which option should we set for `notificationPreference` in the `optimisticData` when creating a new chat?

**Comment by cead22** [comment] 2024-06-17 15:48
@JmillsExpensify @luacmartins is that the expected behavior, and if so, do you have a suggestion for solving this? Perhaps we pick one of the options to show as the default, show the option disabled at first until we get the value from the server, and then update the control and enable it

**Comment by luacmartins** [comment] 2024-06-17 17:43
I don't think we'd always want to set the notification preferences to hidden. It seems like that makes sense if the user doesn't exist, but not otherwise. I'd imagine we could hide that preferences menu until we get a response from the backend?

**Comment by DylanDylann** [comment] 2024-06-18 08:25
@luacmartins Should we also hide that preferences menu in group chat until we get a response from the backend?

**Comment by luacmartins** [comment] 2024-06-18 14:46
If we're seeing the same behavior there, I think we should.

**Comment by DylanDylann** [comment] 2024-07-15 09:47
BugZero Checklist: The PR fixing this issue has been merged! The following checklist ([instructions](https://stackoverflow.com/c/expensify/questions/14574)) will need to be completed before the issue can be closed:

 [@DylanDylann] The PR that introduced the bug has been identified. Link to the PR: **NA**
 [@DylanDylann] The offending PR has been commented on, pointing out the bug it caused and why, so the author and reviewers can learn from the mistake. Link to comment: **NA**
 [@DylanDylann] A discussion in #expensify-bugs has been started about whether any other steps should be taken (e.g. updating the PR review checklist) in order to catch this type of bug sooner. Link to discussion: **NA**
 [@DylanDylann] Determine if we should create a regression test for this bug. **Yes**
 [@DylanDylann] If we decide to create a [regression test](https://github.com/Expensify/App/blob/main/contributingGuides/REGRESSION_TEST_BEST_PRACTICES.md) for the bug, please propose the regression test steps to ensure the same bug will not reach production again.


Regression Test Proposal

1. Start a new chat/a new group chat
2. Click on the header of the newly created chat
3. Verify that the notify me about new messages option should not appear

Do we agree 👍 or 👎

**Comment by cead22** [comment] 2024-07-19 00:24
I'd take this a couple of steps further

1. Start a new chat/a new group chat
2. Click on the header of the newly created chat
3. Verify that the notify me about new messages option should not appear
4. Close the settings pane
5. Send a mesage
6. Click on the header of the created chat
7. Verify that the notify me about new messages option appears

**Comment by cead22** [comment] 2024-07-23 21:49
@VictoriaExpensify all yours

**Comment by cead22** [comment] 2024-07-23 21:50
This isn't overdue, just waiting for payment

**Comment by VictoriaExpensify** [comment] 2024-07-23 22:48
- Contributor: @dominictb  paid $250 via Upwork
- Contributor+: @DylanDylann due $250 via Upwork

Upwork Job Link [Here](https://www.upwork.com/jobs/~015aa8cecd7682d626)

**Comment by VictoriaExpensify** [comment] 2024-07-23 22:57
Contributor: @dominictb  paid $250 via Upwork

Contributor+: @DylanDylann  due $250 via NewDot

Upwork job [here](https://www.upwork.com/jobs/~015aa8cecd7682d626)

**Comment by VictoriaExpensify** [comment] 2024-07-23 23:20
@dominictb and @DylanDylann have been paid, the contract has been completed, and the Upwork post has been closed.

**Closed** 2024-07-23 23:22 UTC
Labels: External, Daily, Awaiting Payment, Bug
