### ISSUE TITLE
[$500] Scan - Admin is able to view the Scan request from employee when it is still scanning

### ISSUE THREAD

**Issue by izarutskaya** [Expensify/App#29859] opened 2023-10-18 11:47 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** v1.3.86-1
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** Applause-Internal Team
**Slack conversation:** @

## Action Performed:
1. Launch New Expensify app.
2. [Employee] Create a scan request in the workspace chat.

## Expected Result:
Admin should not be able to receive notification about the request when it is still scanning.

## Actual Result:
Admin receives a notification about the scanning request and is able to open the report to view it.

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [ ] Android: mWeb Chrome
- [x] iOS: Native
- [ ] iOS: mWeb Safari
- [ ] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos
<details>
<summary>Android: Native</summary>

https://github.com/Expensify/App/assets/115492554/4d6d53ba-122c-4661-8ad0-397bd54ce83d

</details>

<details>
<summary>Android: mWeb Chrome</summary>

</details>

<details>
<summary>iOS: Native</summary>

</details>

<details>
<summary>iOS: mWeb Safari</summary>

</details>

<details>
<summary>MacOS: Chrome / Safari</summary>

</details>

<details>
<summary>MacOS: Desktop</summary>

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01840353244ad23ae6</li>
        <li>Upwork Job ID: 1714609111420366848</li>
        <li>Last Price Increase: 2023-10-18</li>
    </ul>
</details>

**Comment by stephanieelliott** [comment] 2023-10-20 00:42
Awaiting proposals

**Comment by ikevin127** [comment] 2023-10-20 17:51
Was a bit hard debugging this one because of the local development notifications issue for android / ios but I managed to eventually get the notification and reproduce this by using the android folder file's `airshipconfig.properties` production keys `appKey` and `appSecret` in the development `airshipconfig.properties` file and rebuild android app on real device.

Looks like the initial response from `API.write('RequestMoney')` call contains the onyx object that trigger the display of the report and the push notification on the admin side even though the initial status of a Scan money request is `Scanning in progress`.

This should be corrected such that it wouldn't send the pusher event to the other users (in this case admin) of the workspace until the scan is actually finalized. Currently it looks like the pusher event is triggered as soon as the Scan request is submitted which leads to this issue.

In case I'm missing something here, please correct me!

**Comment by cubuspl42** [comment] 2023-10-23 06:57
@ikevin127 So you're essentially saying that a root cause lies on the backend side, right?

**Comment by ikevin127** [comment] 2023-10-23 13:03
Right, that's my bet.

This thing happens only on native mobiles (Android / iOS) and possibly desktop app but I did not check desktop.

I'm saying this because I could not reproduce the issue on web.

What I think is happening is that when 'RequestMoney' endpoint is called from any platform (web, desktop, mobiles), with Scan receipt within a workspace, the BE triggers a push notification which on native mobiles displays the notification together with the workspace chat saying 'Scanning receipt in progress...' on the admin side before the receipt scanning process is completed.

What I would do on the BE side in pseudocode would be:
- check if 'RequestMoney' call is a **Scan receipt** request
- if so, await scanning completion and only when scanning is completed -> trigger push notifications / pusher events that shows the request on the workspace admin's side
- else, keep current implementaion

This would be the way to go because say we can filter out displaying this pusher event / push notification on the FE side for the workspace admin, then when the request receipt scan is completed we wouldn't have a new response / notification to display because the initial was filtered out and we wouldn't get a new one on scan completion.

**Comment by cubuspl42** [comment] 2023-10-24 08:37
C+ reviewed 🎀 👀 🎀

**Comment by cubuspl42** [comment] 2023-10-24 08:38
@deetergp It seems we'll need backend changes to move forward with this. Could you see the analysis by @ikevin127 and share your thoughts?

**Comment by stephanieelliott** [comment] 2023-10-30 16:35
Adding the Internal label as well, since this requires BE change

**Comment by cubuspl42** [comment] 2023-10-31 11:07
@deetergp Bump



> @deetergp It seems we'll need backend changes to move forward with this. Could you see the analysis by @ikevin127 and share your thoughts?

**Comment by deetergp** [comment] 2023-11-08 02:10
The proposal sounds good in theory, but without a push notification to update onyx, how would they now that the receipt had begun to scan?

**Comment by cubuspl42** [comment] 2023-11-08 09:19
@deetergp It's not a proposal in the literal sense, more like an idea sketch...

The next step for this issue, as I see it, is properly classifying it as `External` / `Internal` / _feature-not-bug_ / or _won't-fix_ . We have a rough idea of how this could be fixed on the backend side, but I don't think we need to focus on its details _yet_. 

Do you think that, on the contrary, this could / should be worked externally on the frontend side?

**Comment by cubuspl42** [comment] 2023-11-08 09:21
@ikevin127 Any thoughts here?

**Comment by ikevin127** [comment] 2023-11-08 09:32
The issue's expected result says that the admin **should not** be able to receive notification and see request report about the request when scanning is **still pending**.

So the way I was looking at this was the same way it works on web where we don't have notifications: the other user (admin) is only seeing the request report in chat after the scan was completed on the side of the user that created the scan request.

Correct me if I'm wrong, if this does require front-end changes I'm happy to come up with a proposal after we sort out the back-end.

**Comment by stephanieelliott** [comment] 2023-11-13 15:30
@deetergp can you weigh in on whether this needs back end changes, or can be handled on the front end? Prevailing theory here is that this is a BE issue

**Comment by deetergp** [comment] 2023-11-15 01:13
I've done a bit of digging into this and am wondering if it's really a bug or not. I've asked about it in #expensify-open-source.

**Comment by deetergp** [comment] 2023-11-15 01:29
It looks like this is a bug but it's a dupe and the fix is already being handled here:
* https://github.com/Expensify/App/issues/29828
* https://github.com/Expensify/App/issues/28932

**Closed by deetergp** 2023-11-15 01:29 UTC
Labels: External, Engineering, Daily, Internal, Help Wanted, Bug
