### ISSUE TITLE
[HOLD for payment 2024-07-26] [HOLD for payment 2024-07-24] [HOLD for payment 2024-07-22] [HOLD for payment 2024-07-17] [Guided Setup Stage 2] [$500] Make the GBR on tasks at highest context and assign onboarding tasks to users

### ISSUE THREAD

**Issue by anmurali** [Expensify/App#41619] opened 2024-05-03 20:58 UTC
We are currently deliberately not assigning the onboarding tasks to users because the GBRs on the tasks are at lowest context. I.e. each task is shown in the LHN with a GBR and it looks very noisy and potentially annoying. But we're losing out by doing this because after the first read, the user can ignore the chat with their onboarding tasks, or worse forget where it was originally and kinda lose motivation. 

So, let's

- [ ] Make the GBR on tasks at highest context

1. if the user that the task is assigned to is in the parent chat where the task is shared, then the GBR is at that parent chat level
2. If the user that the task is assigned to is NOT in the parent chat where the task is shared, then the GBR is at the task level

- [ ] Assign all the onboarding tasks created for a user to said user
<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01c009eba2b6e9b0b1</li>
        <li>Upwork Job ID: 1787595574563139584</li>
        <li>Last Price Increase: 2024-07-15</li>
<li>Automatic offers: </li>
<ul>
<li>cretadn22 | Contributor | 102769474</li>
</ul></li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @puneetlath</details>

**Comment by allroundexperts** [comment] 2024-05-07 17:40
Taking over!

**Comment by Santhosh-Sellavel** [comment] 2024-05-07 17:41
Unassigning due to low bandwidth, thanks @allroundexperts!

**Comment by allroundexperts** [comment] 2024-05-07 18:12
@cretadn22 Do you have any branch with these changes so I can test?

**Comment by allroundexperts** [comment] 2024-05-09 15:24
@cretadn22 I need to test your approach a little. Did you test that as well? If so, can you provide a link to your branch?

**Comment by allroundexperts** [comment] 2024-05-12 20:32
Thanks @cretadn22. I will review this today.

**Comment by allroundexperts** [comment] 2024-05-14 19:33
@cretadn22 I reviewed the draft implementation and its looking fine to me. Can you elaborate in more detail what exact changes you need from the backend?

**Comment by trjExpensify** [comment] 2024-05-15 23:53
Thoughts on that, @allroundexperts?

**Comment by allroundexperts** [comment] 2024-05-16 16:10
> Thoughts on that, @allroundexperts?

Will update today.

**Comment by puneetlath** [comment] 2024-05-16 17:51
@allroundexperts I would think that we want the back-end to set `hasOutstandingChildRequest` on these reports, just like we do for expense reports, IOUs etc. Otherwise if you're in focus mode, the app won't have enough info to know whether to show the GBR.

**Comment by allroundexperts** [comment] 2024-05-16 19:36
> @allroundexperts I would think that we want the back-end to set `hasOutstandingChildRequest` on these reports, just like we do for expense reports, IOUs etc. Otherwise if you're in focus mode, the app won't have enough info to know whether to show the GBR.

Given this, @cretadn22 shouldn't you update your proposal? I think that will make things more easier?

**Comment by allroundexperts** [comment] 2024-05-17 19:56
Any update here @cretadn22?

**Comment by puneetlath** [comment] 2024-05-20 18:58
>no way to distinguish outstanding because child request is task or money request

Sorry, I don't totally follow. Why do we need to be able to distinguish what the cause of the GBR is? We just need to know whether the chat should have a GBR in the LHN or not, right?

**Comment by anmurali** [comment] 2024-05-21 17:26
I would think the GBR should behave the same for tasks and money requests actually

**Comment by anmurali** [comment] 2024-05-21 17:52
This is what a GBR on a money request in a chat looks like - it's at the highest context
<img width="1463" alt="image" src="https://github.com/Expensify/App/assets/14225673/56e76635-2765-47df-b9db-b18f8b256829">

On the other hand the GBR on a task that is assigned looks like this - it's at the lowest context
<img width="1457" alt="image" src="https://github.com/Expensify/App/assets/14225673/a52d9387-9a23-47aa-9296-a2e7244a93b1">

**Comment by allroundexperts** [comment] 2024-05-21 18:45
@cretadn22 Given [this](https://github.com/Expensify/App/issues/41619#issuecomment-2123182315), is your proposal ready?

**Comment by danielrvidal** [comment] 2024-05-23 17:48
How is the updated proposal looking @allroundexperts?

**Comment by puneetlath** [comment] 2024-05-23 18:22
Maybe a simple starting place is to just always GBR the parent chat. Yes, there will be edge-case scenarios where you don't have access to the parent chat, but maybe we can just not worry about those for now and focus on the primary case. 

I still think we'll need a back-end update for this though right? I'm not following how this will work in focus mode without it.

**Comment by trjExpensify** [comment] 2024-05-23 23:42
>I still think we'll need a back-end update for this though right? I'm not following how this will work in focus mode without it.

Yeah, I don't think anyone is disputing that. We should add this to `Hot picks`. 

>Yes, there will be edge-case scenarios where you don't have access to the parent chat, but maybe we can just not worry about those for now and focus on the primary case.

If the suggestion here is to just do two PRs, one before the other to separate out the GBR persisting on the parent chat and the fallback therefore, I can get down with that. If that's subtext for let's punt this and all forget about it and move on with our lives, I'm kinda' against that. 😅 

Status quo: the taskReport is always GBR'd, so there's absolutely no chance at all that the person assigned doesn't have a persistent GBR until they take action on it. 

Proposed change: The GBR can be applied to a chat you don't have or no longer have access to. There's no guarantee that the GBR will always persist for the assignee until they take action. 

We're knowingly introducing a regression of the GBR functionality. It's reliability to be the mechanism to persist as a reminder for the person who needs to take action on something until they do will no longer be true for all data types. I'm pretty against adding that quirk, because that's how we end up with a whole bunch of caveats to how something should work over time -- and it ends up being confusing, unreliable and hard to explain/support. 

_"The GBR is added to X, so the person who needs to take an action is consistently reminded that they need to. Except if X is a task, they can forget about it if they leave a chat or you shared it somewhere they don't have access which we don't prevent you from doing."_

**Comment by allroundexperts** [comment] 2024-05-27 19:35
This is waiting for a backend change as per https://github.com/Expensify/App/issues/41619#issuecomment-2127788853. @puneetlath Are we anywhere with it?

**Comment by puneetlath** [comment] 2024-05-29 20:37
@allroundexperts haven't started yet, but planning to tomorrow.

**Comment by puneetlath** [comment] 2024-05-30 15:16
Ok, so I'm going to update the back-end to send `hasOutstandingChildRequest` as true when a given report has a child task that is open and assigned to you. So that will make it so that the parent gets the GBR. 

Are there any back-end changes needed to no longer show the GBR on the task report itself? Or is that purely client-side?

**Comment by allroundexperts** [comment] 2024-06-01 19:38
@puneetlath We also need to make an update to the backend here as per @cretadn22's [proposal](https://github.com/Expensify/App/issues/41619#issuecomment-2123796228):

> When generating onboarding tasks, it's necessary to assign taskReport.managerID = currentUserID. https://github.com/Expensify/App/pull/42025#discussion_r1600813641

**Comment by allroundexperts** [comment] 2024-06-01 19:38
> @allroundexperts Wdyt about my proposal?

It looks good to me. Just waiting on the backend changes so I can test your draft PR.

**Comment by puneetlath** [comment] 2024-06-03 14:37
Sounds good. I'm actively working on the back-end but will likely take a few days.

**Comment by puneetlath** [comment] 2024-06-07 15:51
Back-end PRs are almost ready for review.

**Comment by puneetlath** [comment] 2024-06-10 19:20
Back-end PRs are in review.

**Comment by puneetlath** [comment] 2024-06-14 19:07
Yes @cretadn22. Should get merged/deployed early next week.

**Comment by puneetlath** [comment] 2024-06-17 19:25
@allroundexperts @cretadn22 the back-end has been deployed. We should be setting the `hasOutstandingChildTask` field on reports now. Let me know if you see any issues while testing your PR.

**Comment by puneetlath** [comment] 2024-06-18 19:43
That is interesting. @cretadn22 if the report were set to have the `hidden` notification preference, would it still show in the LHN in that scenario?

**Comment by puneetlath** [comment] 2024-06-20 13:39
Yes, but we are going to update it to be hidden. Basically, we are going to treat them the same way we do expense/IOU reports. Where we put the GBR on the parent report and the task report itself is "hidden" by default. So I'm curious if that will solve the issue you brought up.

**Comment by puneetlath** [comment] 2024-06-20 16:07
>@puneetlath How about this one?

Sorry, what do you mean @cretadn22?

**Comment by puneetlath** [comment] 2024-06-20 18:46
Ah got it. Yes, there will be a second set of back-end changes that will: 
1. Assign the onboarding tasks to the user
2. Make tasks hidden by default

But that shouldn't block you from making your changes, right?

**Comment by puneetlath** [comment] 2024-07-02 22:06
What's done so far: 
- back-end to add `hasOutstandingChildTask` to parent reports
- front-end to add GBR to parent reports when user has access, otherwise to child

What's left: 
- make task reports hidden by default when you have access to the parent. PR here: https://github.com/Expensify/Auth/pull/11434
- make optimistic task reports hidden by default when you have access to the parent @cretadn22 you want to do this? We can add another $250 for it
- assign onboarding tasks to the user -- I'll do this last, once the above is all merged

And then I think we'll be done.

**Comment by puneetlath** [comment] 2024-07-04 20:36
@cretadn22 seems like this is maybe a regression from your PR? https://github.com/Expensify/App/issues/44816#issuecomment-2209540178

**Comment by puneetlath** [comment] 2024-07-15 16:39
What's done so far:

- back-end to add hasOutstandingChildTask to parent reports
- front-end to add GBR to parent reports when user has access, otherwise to child
- back-end to make task reports hidden by default when you have access to the parent
- front-end to make optimistic task reports hidden by default when you have access to the parent

What's left:
- assign onboarding tasks to the user -- I'll do this now

**Comment by puneetlath** [comment] 2024-07-19 23:01
Reminder for myself -- @cretadn22 is owed $500 for two PRs. And @allroundexperts is owed $750 for 3 PRs.

**Comment by puneetlath** [comment] 2024-07-30 17:02
Payment summary: 
- C - @cretadn22 - $500 for two PRs - paid via Upwork
- C+ - @allroundexperts - $750 for three PRs - to be paid via NewDot

Thanks everyone!

**Closed by puneetlath** 2024-07-30 17:02 UTC
Labels: External, Engineering, Weekly, Internal, Overdue, Awaiting Payment

**Comment by JmillsExpensify** [comment] 2024-08-21 11:11
$750 approved for @allroundexperts
