### ISSUE TITLE
[Awaiting Payment 16th May] [Wave Collect] [Xero] Handle errors in the connections

### ISSUE THREAD

**Issue by lakchote** [Expensify/App#39726] opened 2024-04-05 16:13 UTC
We need to handle Xero connection errors. More details [here](https://docs.google.com/document/d/1VEIzxwNzedLNestAFVT5InGvD4N6FHb0922xjMGOkko/edit#bookmark=id.ixhxo6z0xe7).

This will be worked on by SWM engineers, see Slack discussion [here](https://expensify.slack.com/archives/C04878MDF34/p1712333484848839). 

Until the Xero authorization flow ([NewDot issue](https://github.com/Expensify/App/issues/39725))  is done (which entails NewDot, Web-E and IS changes), we won't be able to work on this yet.

**Comment by sonialiap** [comment] 2024-04-15 16:07
On hold for https://github.com/Expensify/App/issues/39725

**Comment by SzymczakJ** [comment] 2024-04-22 16:46
I can take care of that, since I'm already in context because I was doing [Xero authorization flow](https://github.com/expensify/app/issues/39725). Could you assign me @mountiny?

**Comment by hayata-suenaga** [comment] 2024-04-22 18:22
@lakchote thank you for handling this. I have one question:

Is this about the error handling when connecting to Xero or error handling for invalid configuration combinations?

or is it about error handling for sync errors?

**Comment by mountiny** [comment] 2024-04-22 18:29
I think this is purely the connection errors

**Comment by lakchote** [comment] 2024-04-30 09:07
> I think this is purely the connection errors

Yes @hayata-suenaga, as @mountiny said it's purely showing the connection errors and the RBR.

**Comment by sonialiap** [comment] 2024-05-01 11:41
On hold for https://github.com/Expensify/App/issues/39725

**Comment by lakchote** [comment] 2024-05-02 06:22
Not on hold anymore, cc @SzymczakJ

**Comment by lakchote** [comment] 2024-05-06 03:59
Assigning @mananjadhav as he'll be working on this.

**Comment by mananjadhav** [comment] 2024-05-06 04:17
@lakchote Added the PR to fix the disconnect Xero.

**Comment by trjExpensify** [comment] 2024-05-09 11:50
Deployed to prod 9 hours ago.

**Comment by mananjadhav** [comment] 2024-05-13 19:24
Payout for this will be handled after all Xero issues are done. We can close this after the regression period.

**Comment by trjExpensify** [comment] 2024-05-16 11:03
Yep, agreed. Regression period is over, closing.

**Closed by trjExpensify** 2024-05-16 11:03 UTC
Labels: Daily, NewFeature, Awaiting Payment
