### ISSUE TITLE
HybridApp blocked after signing into new experience account

### ISSUE THREAD

**Issue by Julesssss** [Expensify/App#49979] opened 2024-10-01 10:09 UTC
### Problem 

HybridApp iOS and Android apps are bricked by this screen after authenticating with a user set to new experience. 

- Clear app data, or uninstall and reinstall the HybridApp
- Authenticate as a user (user must be set to the new experience)
    - You can force this by [updating](https://stackoverflowteams.com/c/expensify/a/17804/297) your tryNewDot NVP  

## Expected Result: 
- You should land in the app with your LHN data displayed
- Your user avatar should be displayed in the bottom nav

## Actual Result:
- You are temporarily stuck at a blank page
- You then land in the app without any data
- The Woohoo animation is displayed and no chats are visible

Discussed [here](https://expensify.slack.com/archives/C036QM0SLJK/p1727730016994959) in Slack.

![IMG_A8B2918CE269-1](https://github.com/user-attachments/assets/2a51fd25-76b3-4c06-863b-bbd9f22dafaa) ![Screenshot_20240930-174637-2024-10-01 10_08_08 918](https://github.com/user-attachments/assets/19fc0f96-f380-4ccc-8ce7-58f05b391520)

### Solution

Work back through versions, seeking regression.

**Comment by Julesssss** [comment] 2024-10-01 10:33
Still seeing the issue this morning. It seems that after about 60 seconds I do land inside the app, but no data has loaded and I see the 'Woohoo! All caught up' animation 😕 

**Initial triage:** 
- Android `9.0.41.2` already authenticated -- land at empty LHN
- iOS `9.0.41.2` fresh install -- see blank page for a while, then land at blank page
- iOS `9.0.41.2` fresh install -- land at empty LHN

**Does app load correctly:**
- 9.0.42.0 ❌
- 9.0.41.10 ✅   
- 9.0.41.5 ✅     
- 9.0.40.6 ✅

**Comment by Julesssss** [comment] 2024-10-01 10:38
As we need to align NewDot and HybridApp releases, I think this is important enough to treat as a NewDot blocker given that HybridApp is live in the store, and this issue blocks us from shipping regular fixes to our production app. This will ensure: 

- We locate the regression while NewDot PRs are still fresh in people's minds
- We randomly assign the bug, rather than myself and Andrew having to drop other work to resolve

**Comment by Julesssss** [comment] 2024-10-01 11:40
Hey @lakchote (and FYI @jasperhuangg)

This is a HybridApp bug that pretty much bricks the app. For the first time we will treat this as a NewDot blocker, as the regression was caused by a newDot PR on the current checklist and it blocks us from shipping HybridApp releases/fixes.

This is the first step in a new process we have been planning for, and @andrew and myself are here to help to document any difficulties or questions that arise. [Here](https://stackoverflowteams.com/c/expensify/questions/20147) is a Stackoverflow post that documents some tips and differences in the triage process. 

@AndrewGable and myself are here to help answer any questions and help with the process, and we can also seek help from SWM. We can also review the blocking status if the rest of the App checklist ends up being complete before this issue is solved.

**Comment by lakchote** [comment] 2024-10-01 12:16
@Julesssss 

I think we should leverage SWM to gain a headstart on this given the urgency, as I have no previous experience working on HybridApp. The more diligent eyes on this, the better. What are your thoughts?

For the rest of my questions, I'll DM you to not bloat this issue.

**Comment by Julesssss** [comment] 2024-10-01 12:43
Sure, I have tagged our SWM friends [here](https://expensify.slack.com/archives/C01GTK53T8Q/p1727786327593249). 

I appreciate it's not easy, but we'll need everyone in the team to gain familiarity with HybridApp very soon. Please ask any questions here so we can document the process and make it easy for the next deploy blocker 👍 

We have verified reproduction, but that could be aa good first step for you as you are unfamiliar. Next, building the app would be good. The readme steps should make this simple and quite a few engineers have been able to do so already. At this point you should be able to git bisect or manually checkout commits to find the place the bug was introduced by using the submodule (Mobile-Expensify/react-native is a clone of App)

**Comment by lakchote** [comment] 2024-10-01 12:54
Thanks for tagging SWM.

And yes, I'm with you, we need every engineer to become familiar with it. We can't have 2-3 engineers familiar with it, if there is a problem that needs to be handled, we need to be able to solve it regardless. 

I feel like reaching out to SWM while I investigate is the best of both worlds as I gain experience from it AND the likelihood for the problem to be solved before next App release increases too.

I haven't had any trouble building the app nor reproducing the bug.

**The first problem I've encountered:** 
I wasn't hitting my dev environment for my requests.

Solution: update `.env`, in `react-native` folder, and rebuild. 
Maybe we should add a line for this to the `README` to save time and make sure we don't miss it when we run the project?

**Comment by mateuuszzzzz** [comment] 2024-10-01 12:57
It might be caused by the fact we haven't merge OldDot part of [onboarding fix ](https://github.com/Expensify/Mobile-Expensify/pull/13157).

Honestly, I have doubts, but I can't say that I'm 100% sure until I verify it.

**Comment by Julesssss** [comment] 2024-10-01 13:04
> Maybe we should add a line for this to the README to save time and make sure we don't miss it when we run the project?

We do have a couple of `.env` PRs in progress ([example](https://github.com/Expensify/Mobile-Expensify/pull/12926)), lets review this once they are all merged.

**Comment by Julesssss** [comment] 2024-10-01 13:42
Just noting that [we may also need to](https://github.com/Expensify/Mobile-Expensify/pull/13157#issuecomment-2377049673) bump the submodule commit.

**Comment by staszekscp** [comment] 2024-10-01 13:56
Hey @Julesssss! Even though I have a TestFlight build, and accounts using NewDot, I am unable to reproduce it... Does it happen on your account and are there any prerequisites to reproduce the crash?

**Comment by lakchote** [comment] 2024-10-01 14:06
I'm currently stuck while rebuilding on Android:

`> Task :installDebug FAILED
Installing APK 'Expensify-debug.apk' on 'Pixel_3a_API_30(AVD) - 11' for ::debug
Unable to install /Users/lucien/Expensidev/Mobile-Expensify/Android/build/outputs/apk/debug/Expensify-debug.apk
com.android.ddmlib.InstallException: INSTALL_FAILED_VERSION_DOWNGRADE`

I've tried deleting the app in Android studio already.

I've tried building on iOS to save time and wasn't able to do so:

`Mobile-Expensify/iOS/Pods/SDCAlertView/Source/AlertController.swift:132:42: 'Transition' is only available in iOS 18.0 or newer`

This makes it hard to test whether [this](https://github.com/Expensify/Mobile-Expensify/pull/13157) PR solves it or not.

**Comment by staszekscp** [comment] 2024-10-01 14:29
Thanks for the answer! Unfortunately there is a chance that your XCode version is too high... I use 15.4 myself, and I have no problems with the build. Another reason is that you may have accidentaly bumped the `SDCAlertView` version, but I rather doubt that - just to make sure - what is the version you have in the `Podfile.lock` file? It should be `11.0`

Also, thanks for the reproduction steps! Unfortunately whenever I create a new account via `expensify.com` I seem to be stuck on this screen... I when I click the link in the e-mail It just shows me the magic code, but I'm unable to provide it...

<img width="336" alt="image" src="https://github.com/user-attachments/assets/08b0c20f-09bb-49f6-86ac-75153b761c5f">

**Comment by Julesssss** [comment] 2024-10-01 14:36
> Does it happen on your account and are there any prerequisites to reproduce the crash?

Yeah it's happening on multiple accounts for me (assuming they are set to new experience). 

> Also, thanks for the reproduction steps! Unfortunately whenever I create a new account via expensify.com I seem to be stuck on this screen...

Ah odd, and there isn't a link provided within the email?

For now it

**Comment by staszekscp** [comment] 2024-10-01 14:38
Ok, I think that iOS problem is definitely related to the XCode, which introduced `Transition` in iOS 18 (XCode 15.4 doesn't support it yet, therefore there is no error). I think we need to upgrade `SDCAlertView` in order to avoid the problem in the nearest future

The fix for the clash was introduced [here](https://github.com/sberrevoets/SDCAlertView/commit/28e71bc9cf8e267175e044f10f5270c08c04c819#diff-204cbe6b4891901d2c9242445adeebd5d6c8506028d722a08a6f21b3a8d765d0R133)

**Comment by lakchote** [comment] 2024-10-01 14:39
`SDCAlertView` version is 11.0.

>Also, thanks for the reproduction steps! Unfortunately whenever I create a new account via expensify.com I seem to be stuck on this screen... I when I click the link in the e-mail It just shows me the magic code, but I'm unable to provide it...

Hmm, I had this problem on dev, I had to update my `.env` in react-native folder to use ngrok, and rebuild. Otherwise it would point to production server.

**Comment by lakchote** [comment] 2024-10-01 14:41
> Ok, I think that iOS problem is definitely related to the XCode, which introduced `Transition` in iOS 18 (XCode 15.4 doesn't support it yet, therefore there is no error). I think we need to upgrade `SDCAlertView` in order to avoid the problem in the nearest future
> 
> The fix for the clash was introduced [here](https://github.com/sberrevoets/SDCAlertView/commit/28e71bc9cf8e267175e044f10f5270c08c04c819#diff-204cbe6b4891901d2c9242445adeebd5d6c8506028d722a08a6f21b3a8d765d0R133)

Hmm, that's interesting. I think we'll encounter the problem down the line yes, for people with newest XCode versions.

What do you think @Julesssss? We could do it in a separate PR as a follow-up.

**Comment by Julesssss** [comment] 2024-10-01 14:46
> Created a new account

I just noticed this btw. It occurs on existing accounts, no need to create new accounts.

**Comment by staszekscp** [comment] 2024-10-01 14:49
@Julesssss what is the iOS version on your device? I start wondering if it's not caused by iOS18? 😄

**Comment by tgolen** [comment] 2024-10-01 14:50
Hi all, just as a heads up, while I have been able to consistently reproduce this, I got the latest version from testflight `9.0.42-0` (iOS 17.6.1) last night and I haven't been able to reproduce it since.

**Comment by lakchote** [comment] 2024-10-01 14:51
> I just noticed this btw. It occurs on existing accounts, no need to create new accounts.

Got it, it was to ensure I've entered with a fresh state to debug.

--

I was able to rebuild finally on Android thanks to @staszekscp.

While checking out the [PR's](https://github.com/Expensify/Mobile-Expensify/pull/13157) branch, the bug seems to not be present anymore! I'd like someone to retest it to confirm, but that's good news.

https://github.com/user-attachments/assets/4084fa86-e467-405e-b75e-5cf7f0446585

**Comment by Julesssss** [comment] 2024-10-01 14:59
> Hi all, just as a heads up, while I have been able to consistently reproduce this, I got the latest version from testflight 9.0.42-0 (iOS 17.6.1) last night and I haven't been able to reproduce it since.

@tgolen could you please try completely uninstalling the app and then re-installing? This sounds similar to my experience this morning, and it would be great to confirm this is easier to reproduce on a fresh install.

**Comment by Julesssss** [comment] 2024-10-01 15:18
Here's my reproduction. I'm following the steps listed at the top of the issue, but making sure to uninstall the app before reinstalling:

https://github.com/user-attachments/assets/450cb21b-f69d-4e2c-b0aa-14686066d870

**Comment by Julesssss** [comment] 2024-10-01 15:20
Ah that's great news @lakchote 👍 

Let's merge that PR and retest. I think we would need the PR to be CP'd in order for it to appear on the associated HybridApp build.

**Comment by tgolen** [comment] 2024-10-01 16:30
OK, I've reinstalled. Now I think I need to wait 2 hours for my authToken
to expire.

**Comment by jasperhuangg** [comment] 2024-10-01 16:33
@tgolen You should be able to expire your authToken if you get someone in ring1 to run this query

```sql
REPLACE INTO nameValuePairs (accountID, name, value, created) VALUES (<mainAccountID>, 'private_minimumAuthTokenIssueTime', strftime('%s', 'now', 'utc') || '000000', Date('now'));
```

**Comment by tgolen** [comment] 2024-10-01 19:58
Hm, even waiting til it naturaly expired, the app opened right up and loaded the LHN like I expected. So I still wasn't able to reproduce it.

**Comment by jasperhuangg** [comment] 2024-10-01 21:34
Cool, @tgolen if you can't reproduce this then think it should be safe to remove the blocker label based on [this](https://github.com/Expensify/App/issues/49979#issuecomment-2386299747).

**Comment by lakchote** [comment] 2024-10-02 10:27
@Julesssss issue not reproducible on the new build (`9.0.42-3`):

https://github.com/user-attachments/assets/8c262058-8f4a-4d34-a964-6afaf117e325

**Comment by lakchote** [comment] 2024-10-02 12:24
Closing the issue since the problem isn't reproductible anymore. (Discussed it with @Julesssss beforehand, as I'm not used to HybridApp process).

**Closed by lakchote** 2024-10-02 12:24 UTC
Labels: Engineering, Daily, Internal
