### ISSUE TITLE
[$500] Context menu popup is not dismissed when opening Sign In Model in Incognito mode

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#29830] opened 2023-10-17 21:11 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.3.85.0
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** @tranvantoan-qn
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1697565108183509

## Action Performed:
. Go to Incognito mode or log out of any account
2. Follow this public room's link:  https://staging.new.expensify.com/r/5593084223054221
3. Click the Three Dots icon in the top-right corner of the page.
4. Select either "Pin," "Zoom," or "Google Meet" from the menu.
5. Observe that: the context menu keeps opening and overlays the Sign-up Modal.

## Expected Result:
The context menu popup should close after selecting any option. So the users can use Sign-up Modal

## Actual Result:
The context menu keeps opening and overlays the Sign-up Modal

## Workaround:
Unknown 

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [x] Android: mWeb Chrome
- [x] iOS: Native
- [x] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos
<details>
<summary>Android: Native</summary>

 

https://github.com/Expensify/App/assets/93399543/5945a86f-e23c-4585-ae02-c35eee3832cc

</details>

<details>
<summary>Android: mWeb Chrome</summary>

 

https://github.com/Expensify/App/assets/93399543/78e0f555-06cd-4e9e-b105-0d01897bd31c

</details>

<details>
<summary>iOS: Native</summary>

 

https://github.com/Expensify/App/assets/93399543/a517a998-d7de-4df2-bf3f-d52b6c3acafd

</details>

<details>
<summary>iOS: mWeb Safari</summary>

 

https://github.com/Expensify/App/assets/93399543/a59fc277-91bf-4457-8154-68860884cf3c

</details>

<details>
<summary>MacOS: Chrome / Safari</summary>

 

https://github.com/Expensify/App/assets/93399543/90498b4b-5bb1-44c2-8659-8cc28be3cd62

https://github.com/Expensify/App/assets/93399543/e6a98dd0-0d29-48f1-9479-2f909c402cfe

https://github.com/Expensify/App/assets/93399543/7351388f-d834-42df-9499-5230c3290b9c

</details>

<details>
<summary>MacOS: Desktop</summary>

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~015958dd4a7d354810</li>
        <li>Upwork Job ID: 1714388653820784640</li>
        <li>Last Price Increase: 2023-10-17</li>
    </ul>
</details>

**Comment by graylewis** [comment] 2023-10-17 22:17
## Proposal
### Please re-state the problem that we are trying to solve in this issue.
When an anonymous user is signed in and uses the three dot menu to select a video conferencing option, the sign in modal is shown but the three dot menu is not dismissed. 

### What is the root of the issue
When the menu item is selected, it triggers the checkIfActionIsAllowed function which interrupts the flow of the logic and redirects the user to the sign in modal. Since the logic of the menu items' selection never gets to the part where it dismisses the popover, the popover is left open. 

### What changes do you think we should make in order to solve the problem?
There is an existing pattern to handle this issue. On the floating action button, the menu items' onSelected callback uses the interceptAnonymousUsers to handle this logic inside of the component. We could use this pattern to hide the popover before the redirect occurs.

What alternative solutions did you explore? (Optional)
NA

**Comment by olalekanteeblaze** [comment] 2023-10-17 22:49
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
When an anonymous user tries click on any of the items on the Three dot menu, it redirects and open the sign in modal without closing the the popover opened by the three dot menu, thereby blocking the sign in modal

### What is the root cause of that problem?
The cause of the issue is that when any of the item in the popover menu is clicked, it's intercepted by a `checkIfActionIsAllowed` function which redirects to the sign in page (opens the sign in modal) when the user is anonymous or the action isn't allowed. The function that actually close the popover is only called when the action is allowed.

### What changes do you think we should make in order to solve the problem?
By updating the `checkIfActionIsAllowed` function to accept a third optional argument called notAllowedCallback, we can pass a callback that actually closes the popover before opening the sign in modal

### What alternative solutions did you explore? (Optional)
N/A

**Comment by olalekanteeblaze** [comment] 2023-10-17 22:51
Contributor details
Your Expensify account email: Olalekanteeblaze@gmail.com
Upwork Profile Link: https://www.upwork.com/freelancers/~0119e461c83372a840

**Comment by ayazalavi** [comment] 2023-10-18 02:19
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
in case of anonymous user, three dots menu doesnt gets closed when you select an item

### What is the root cause of that problem?
The root cause is that the code is preventing the menu item callback from executing when the popover is closed due to a condition at this location:

https://github.com/Expensify/App/blob/f0d2d0864a748042ece6353a3a3874202a551bf0/src/components/MenuItem.js#L143

Popover closed for anonymous user is not implemented

### What changes do you think we should make in order to solve the problem?
Implement a utility method that handles a click/tap event anywhere on the page where it runs a callback for anonymous users only, allowing us to pass the close popover method.

### What alternative solutions did you explore? (Optional)
N/A

**Comment by laurenreidexpensify** [comment] 2023-10-18 09:13
@narefyev91 do you agree ^^

**Comment by narefyev91** [comment] 2023-10-18 09:14
> @narefyev91 do you agree ^^

Yup - i already tested those flow - and https://github.com/Expensify/App/pull/29653 fixed the issue

**Comment by tranvantoan-qn** [comment] 2023-10-18 09:17
Did you test it on main or staging?
![image](https://github.com/Expensify/App/assets/10254571/12a89abf-06bc-4a02-a462-3a64598b25ee)

**Comment by narefyev91** [comment] 2023-10-18 09:23
@laurenreidexpensify ops mixed up with other issue which was also related to menu https://github.com/Expensify/App/issues/28324
Let me check if that still happened

**Closed** 2023-10-20 10:27 UTC
Labels: External, Daily, Help Wanted, Bug
