### ISSUE TITLE
[HOLD for payment - Sept 28th] [$1000] Notification not receiving on iOS when long message is sent

### ISSUE THREAD

**Issue by izarutskaya** [Expensify/App#25982] opened 2023-08-25 22:00 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Login on iOS Native app
2. Login another account on another platform
3. Paste below text in composer -> Hit send

```
QWERTY qwerty QWERTY qwerty QWERTY qwerty QWERTY qwerty QWERTY qwerty QWERTY qwerty QWERTY qwerty QWERTY qwerty QWERTY qwerty QWERTY qwerty QWERTY qwerty QWERTY qwerty QWERTY qwerty QWERTY qwerty QWERTY qwerty QWERTY qwerty QWERTY qwerty QWERTY qwerty QWERTY qwerty QWERTY qwerty QWERTY qwerty QWERTY qwerty QWERTY qwerty QWERTY qwerty QWERTY qwerty QWERTY qwerty QWERTY qwerty QWERTY qwerty QWERTY qwerty QWERTY qwerty QWERTY qwerty QWERTY qwerty QWERTY qwerty QWERTY qwerty QWERTY qwerty QWERTY qwerty QWERTY qwerty QWERTY qwerty QWERTY qwerty QWERTY qwerty QWERTY qwerty QWERTY qwerty QWERTY qwerty QWERTY qwerty QWERTY qwerty QWERTY qwerty QWERTY qwerty QWERTY qwerty QWERTY qwerty QWERTY qwerty QWERTY qwerty QWERTY qwerty QWERTY qwerty QWERTY qwerty
```

## Expected Result:
iOS should receive notification

## Actual Result:
iOS native not receiving notification when message is long

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [x] iOS / native
- [ ] iOS / Safari
- [ ] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** v1.3.57-5

**Reproducible in staging?:** Y

**Reproducible in production?:** Y

**If this was caught during regression testing, add the test name, ID and link from TestRail:**

**Email or phone of affected tester (no customers):**

**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/115492554/c1b8742c-a229-43a4-af10-1a7888632d24

https://github.com/Expensify/App/assets/115492554/48073533-4192-4d4e-9181-c265b3237ca1

**Expensify/Expensify Issue URL:**

**Issue reported by:** @DinalJivani

**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1692129779665229

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~0139b0dc94f812c234</li>
        <li>Upwork Job ID: 1696149809907351552</li>
        <li>Last Price Increase: 2023-08-28</li>
    </ul>
</details>

**Comment by tamdao** [comment] 2023-08-26 14:41
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
Notification not receiving on iOS when long message is sent

### What is the root cause of that problem?

The maximum payload size of notification:

- For Voice over Internet Protocol (VoIP) notifications, the maximum payload size is 5 KB (5120 bytes).
- For all other remote notifications, the maximum payload size is 4 KB (4096 bytes).

You can take a look the document [here](https://developer.apple.com/documentation/usernotifications/setting_up_a_remote_notification_server/generating_a_remote_notification#overview)

So that's why it didn't send the notification with long message, because the payload of notification over the limit size.

### What changes do you think we should make in order to solve the problem?

You need to update backend to make sure the payload of notification not over the limit size, that mean you need to reduce the number of characters of title and body of notification

**Comment by joekaufmanexpensify** [comment] 2023-08-28 12:56
Not overdue

**Comment by joekaufmanexpensify** [comment] 2023-08-28 13:16
I can reproduce this. However, if this is an apple limitation, I'm not sure we'd do anything. Curious if others agree though.

**Comment by joekaufmanexpensify** [comment] 2023-08-29 20:23
@0xmiroslav curious for your thoughts [on this ](https://github.com/Expensify/App/issues/25982#issuecomment-1695684165), when you have a chance?

**Comment by joekaufmanexpensify** [comment] 2023-08-30 19:43
Still pending insight from Miroslav.

**Comment by joekaufmanexpensify** [comment] 2023-08-31 20:24
Sounds good. Making this internal!

**Comment by joekaufmanexpensify** [comment] 2023-08-31 20:24
@Gonals We're thinking this bug needs to be internal. Let us know if you agree!

**Comment by DinalJivani** [comment] 2023-09-02 21:02
> I can reproduce this. However, if this is an apple limitation, I'm not sure we'd do anything. Curious if others agree though.

I know this is Apple limitation. But also other chat apps can send as long message you want and notifications still works like Whatsapp, Instagram... Not sure what mechanisms they will be using 🧐

@joekaufmanexpensify  @0xmiroslav

**Comment by joekaufmanexpensify** [comment] 2023-09-05 20:35
@Gonals got it. Should we just re-assign this then? 

I'm also curious if there is anything we can actually do about this (if this is an apple limitation). Though I see referenced [here ](https://github.com/Expensify/App/issues/25982#issuecomment-1703939989) that other apps seem to get around this.

**Comment by joekaufmanexpensify** [comment] 2023-09-07 19:51
@Gonals bump on this when you have a sec!

**Comment by joekaufmanexpensify** [comment] 2023-09-08 19:17
Still pending further discussion.

**Comment by joekaufmanexpensify** [comment] 2023-09-11 13:14
Bumped Alberto 1:1

**Comment by Gonals** [comment] 2023-09-12 02:09
Yep! I think reassigning would be the way to go. I'll unassign myself. Can you roll the dice again, @joekaufmanexpensify? If I were to do it, I would just get reassigned 😅

**Comment by joekaufmanexpensify** [comment] 2023-09-12 19:09
@Beamanator as an fyi, we re-assigned this as this issue requires backend changes, but the engineer who works on it needs to have a physical iOS device, and Alberto does not. LMK if you have any questions!

**Comment by Beamanator** [comment] 2023-09-13 02:31
Asked for confirmation in slack if we can give external devs access to any certs to be able to test & work on this externally

**Comment by Julesssss** [comment] 2023-09-14 01:33
Taking over. 

> You need to update backend to make sure the payload of notification not over the limit size

We do this already for messages over 4kb 😕

**Comment by Julesssss** [comment] 2023-09-14 05:02
Testing this is very time-consuming and even more difficult for iOS. Demoting to weekly but I'm aiming to take a look today

**Comment by joekaufmanexpensify** [comment] 2023-09-14 12:17
Sounds good, thanks @Julesssss !

**Comment by Julesssss** [comment] 2023-09-15 10:12
I'm noticing the Onyx payload limit is also being hit on Android...

**Comment by joekaufmanexpensify** [comment] 2023-09-18 09:10
Ah, interesting. That means we need to fix this in both native apps?

**Comment by joekaufmanexpensify** [comment] 2023-09-19 08:03
Got it, sounds good!

**Comment by Julesssss** [comment] 2023-09-19 10:16
Figured this out. [PR here](https://github.com/Expensify/Web-Expensify/pull/38908)

**Comment by joekaufmanexpensify** [comment] 2023-09-20 08:02
Woo, thanks Jules!

**Comment by Julesssss** [comment] 2023-09-21 10:14
Fix deployed to prod, closing.

**Comment by Julesssss** [comment] 2023-09-22 01:27
Oh yep, thanks for the reminder

**Comment by joekaufmanexpensify** [comment] 2023-09-25 03:00
Yep! I'll pay today.

**Comment by joekaufmanexpensify** [comment] 2023-09-25 03:28
This issue is from before we changed pricing tiers, so bonus is $250 here.

**Comment by joekaufmanexpensify** [comment] 2023-09-25 03:30
@DinalJivani offer sent for $250!

**Comment by DinalJivani** [comment] 2023-09-25 09:24
@joekaufmanexpensify offer accepted! Thanks.

**Comment by joekaufmanexpensify** [comment] 2023-09-25 09:52
Since we are just paying out the reporting bonus here, we don't need to wait 7 days (since there is no possibility of the reporter causing a regression that results in reduced payment).

**Comment by joekaufmanexpensify** [comment] 2023-09-25 09:56
@DinalJivani $250 sent and contract ended!

**Comment by joekaufmanexpensify** [comment] 2023-09-25 09:56
Closing as this one is all set!

**Closed by joekaufmanexpensify** 2023-09-25 09:56 UTC
Labels: Reviewing, Engineering, Daily, Internal, Bug
