### ISSUE TITLE
[OldDot Rules Migration] [Polish] - No error under input field when saving auto-pay amount more than 20k

### ISSUE THREAD

**Issue by IuliiaHerets** [Expensify/App#48868] opened 2024-09-10 08:38 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 9.0.31-12
**Reproducible in staging?:** Y
**Reproducible in production?:** N/A
**Email or phone of affected tester (no customers):** applausetester+kh010901@applause.expensifail.com
**Issue reported by:** Applause Internal Team

## Action Performed:
1. Go to staging.new.expensify.com
2. Go to Workspace settings > Rules.
3. Enable Auto-pay approved reports.
4. Click Auto-pay reports under.
5. Enter amount more than 20k.
6. Click Save.

## Expected Result:
There will be error under input field when saving auto-pay amount more than 20k.

## Actual Result:
There is no error under input field when saving auto-pay amount more than 20k.

## Workaround:
Unknown

## Platforms:

- [x] Android: Native
- [x] Android: mWeb Chrome
- [x] iOS: Native
- [x] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

https://github.com/user-attachments/assets/d215cab1-bd53-43e4-a884-e43fd1114c6d

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by mkzie2** [comment] 2024-09-10 08:53
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
There is no error under input field when saving auto-pay amount more than 20k.

### What is the root cause of that problem?

We do not pass `errorText` to the `TextInput` here:

https://github.com/Expensify/App/blob/27161d160f60208a2526b2223f64f8bb243e28b0/src/components/AmountForm.tsx#L240-L242

### What changes do you think we should make in order to solve the problem?


Pass `errorText={errorText}` to the above `TextInput`.

**Comment by techievivek** [comment] 2024-09-10 09:44
This is coming from here: https://github.com/Expensify/App/pull/47468, I think the author we can just assign this to the PR author and they can work on it.

**Comment by techievivek** [comment] 2024-09-10 09:46
We can also remove the deployblocker label, as this issue only affects a specific flow and a certain case where the amount is > 20k.

**Comment by DylanDylann** [comment] 2024-09-11 07:41
@BrtqKr This is minor, please add it into https://github.com/Expensify/App/pull/48908

**Comment by marcaaron** [comment] 2024-09-16 21:45
This is in review.

**Comment by muttmuure** [comment] 2024-09-25 13:30
Not overdue

**Comment by marcaaron** [comment] 2024-11-23 01:08
I think this one can be closed.

**Closed by marcaaron** 2024-11-23 01:08 UTC
Labels: Reviewing, Engineering, Monthly, Internal, Bug
