### ISSUE TITLE
[HOLD for payment 2024-02-20] [HOLD for payment 2024-02-19] Request money - App reopens request details page after saving description

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#36175] opened 2024-02-08 20:02 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** Y
**Reproducible in staging?:** N
**Reproducible in production?:**
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** Applause - Internal Team
**Slack conversation:**

**Issue found when executing PR** https://github.com/Expensify/App/pull/35137
## Action Performed:
1. Launch New Expensify app
2. Go to FAB > Request money
3. Create a manual request from any person
4. Navigate to request details view
5. Tap Description
6. Enter or edit the description and save it
7. Return to previous page using device back navigation

## Expected Result:
In Step 6, the request details page will not reopen
In Step 7, app returns to IOU report

## Actual Result:
In Step 6, the request details page reopens
In Step 7, app returns to the same request details page

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [x] Android: mWeb Chrome
- [x] iOS: Native
- [ ] iOS: mWeb Safari
- [ ] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details> 

https://github.com/Expensify/App/assets/78819774/239e7799-8129-4fcd-b176-195ef3cc5bad

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by lanitochka17** [comment] 2024-02-08 20:04
We think that this bug might be related to [#vip-split-p2p-chat-groups](https://expensify.enterprise.slack.com/archives/C05RECHFBEW)

**Comment by marcaaron** [comment] 2024-02-09 00:29
@deetergp @s77rt any chance you can look into this one. It sounds possibly related to the PR linked [here](https://github.com/Expensify/App/pull/35137).

**Comment by s77rt** [comment] 2024-02-09 02:06
I confirm it's caused by that PR. This may not be a deploy blocker as the bug is already on production effecting other pages e.g. the receipt page.



https://github.com/Expensify/App/assets/16493223/f83ff4fa-c98e-4d98-a251-231681983c34


https://github.com/Expensify/App/blob/49886befa033ea0f81bcc9d39733006878141ca3/src/libs/Navigation/Navigation.ts#L214-L217

**Comment by s77rt** [comment] 2024-02-09 02:06
cc @DylanDylann

**Comment by arosiclair** [comment] 2024-02-09 14:32
Reproduced  on iOS staging **v1.4.39-0**.

https://github.com/Expensify/App/assets/6833644/c19b97ba-e2aa-49c8-9299-f909b2b54abd

**Comment by arosiclair** [comment] 2024-02-09 14:38
No reproduction on iOS prod **v1.4.38-6**

https://github.com/Expensify/App/assets/6833644/1e01d2c5-f24b-4fd4-bb1f-1c117fe39c0e

**Comment by arosiclair** [comment] 2024-02-09 15:29
Confirmed reverting https://github.com/Expensify/App/pull/35137 fixes the issue. Posting a revert PR...

**Comment by Beamanator** [comment] 2024-02-12 13:45
Fixed by https://github.com/Expensify/App/pull/36287 & https://github.com/Expensify/App/pull/36329

**Comment by arosiclair** [comment] 2024-02-13 18:34
I think this is all set

**Closed by arosiclair** 2024-02-13 18:34 UTC
Labels: Engineering, Weekly, Awaiting Payment
