### ISSUE TITLE
 Chat - Chat scrolled to the bottom when other part of the chat history loaded

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#38452] opened 2024-03-17 19:59 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.53-2
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**If this was caught during regression testing, add the test name, ID and link from TestRail:** https://expensify.testrail.io/index.php?/tests/view/4432845&group_by=cases:section_id&group_id=306202&group_order=asc
**Email or phone of affected tester (no customers):** applausetester+omq1@applause.expensifail.com
**Issue reported by:** Applause - Internal Team

## Action Performed:
Precondition: chat with a lot of messages should not be cached
1. Open app
2. Open chat with a lot of messages e.g. "#applause.expensifail.com"
3. Wait until the last messages will be loaded
4. Scroll up rapidly to the very top
5. Wait until the other part of the chat history will be loaded

## Expected Result:
The other part of the chat history should be loaded when user scrolled to the very top

## Actual Result:
Page scrolled down to the latest messages when other part of the chat history loaded

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [x] iOS: Native
- [x] iOS: IPad
- [ ] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details> 

https://github.com/Expensify/App/assets/78819774/697aa440-2e1b-4907-af24-a309b5c8dd1a

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by lanitochka17** [comment] 2024-03-21 14:37
@puneetlath  FYI I haven't added the External label as I wasn't 100% sure about this issue. Please take a look and add the label if you agree it's a bug and can be handled by external contributors

**Comment by puneetlath** [comment] 2024-03-21 20:34
@lanitochka17 does this only happen on iOS devices?

**Comment by kavimuru** [comment] 2024-03-22 20:05
This bug was happening only in iPad, not in iPhone or android.

**Comment by kavimuru** [comment] 2024-03-22 20:44
@puneetlath Tester was not able to reproduce in the latest staging build 1.4.56-0 on both iPhone and iPad

https://github.com/Expensify/App/assets/43996225/36873ca4-13d2-4518-add5-3e658b18640d


https://github.com/Expensify/App/assets/43996225/5642ee89-dcf5-4830-8969-e589ce9fb5d2

**Comment by puneetlath** [comment] 2024-03-22 20:45
Ok got it, that's good to hear! Closing out.

**Closed by puneetlath** 2024-03-22 20:45 UTC
Labels: Daily, Bug
