### ISSUE TITLE
[$250] Blank RHP opens for a moment when validating a new contact method

### ISSUE THREAD

**Issue by IuliiaHerets** [Expensify/App#53772] opened 2024-12-09 18:32 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 53762
**Reproducible in staging?:** Yes
**Reproducible in production?:** No
**If this was caught on HybridApp, is this reproducible on New Expensify Standalone?:** N/A
**If this was caught during regression testing, add the test name, ID and link from TestRail:** https://expensify.testrail.io/index.php?/tests/view/5315884
**Email or phone of affected tester (no customers):** N/A
**Issue reported by:** Applause Internal Team

## Action Performed:
1. Sing in to staging.new.expensify.com
2. Navigate to settings > Profile
3. Add a new contact method
4. Enter magic code sent for the primary contact method
5. Click on the newly added contact method to validate

## Expected Result:
RHP opens prompting to enter a magic code sent to the secondary contact email address.

## Actual Result:
A blank RHP is displayed for a moment when clicking on validating secondary contact method.

## Workaround:
Unknown

## Platforms:
- [ ] Android: Standalone
- [ ] Android: HybridApp
- [x] Android: mWeb Chrome
- [ ] iOS: Standalone
- [ ] iOS: HybridApp
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

https://github.com/user-attachments/assets/dc0416c6-4af6-4524-bf19-dd5e54def4a6

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)
<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~021866199762317784844</li>
        <li>Upwork Job ID: 1866199762317784844</li>
        <li>Last Price Increase: 2024-12-09</li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @rayane-djouah</details>

**Comment by amyevans** [comment] 2024-12-09 19:14
Demoting it to not block deploy and opening up for external proposals.

**Comment by FitseTLT** [comment] 2024-12-09 20:06
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
Blank RHP opens for a moment when validating a new contact method

### What is the root cause of that problem?
This is a regression from https://github.com/Expensify/App/pull/53475 The PR intended to solve animation bug by delaying the appearance of the modal via runAfterInteraction
https://github.com/Expensify/App/blob/219dabf6a0a907f16aef543306c78fab172c3c4b/src/components/Modal/BaseModal.tsx#L72-L81
### What changes do you think we should make in order to solve the problem?

We can apply the same fix in other less general modal components instead of on `BaseModal` which would affect several places like the one here.
For instance to solve the original problem we can apply the delay in `AttachmentModal`
https://github.com/Expensify/App/blob/219dabf6a0a907f16aef543306c78fab172c3c4b/src/components/AttachmentModal.tsx#L493
### What specific scenarios should we cover in automated tests to prevent reintroducing this issue in the future?


### What alternative solutions did you explore? (Optional)

**Comment by luacmartins** [comment] 2024-12-09 20:08
cc @chrispader can you work on a fix since it's coming from your PR? cc @ikevin127 @mountiny

**Comment by amyevans** [comment] 2024-12-09 20:15
Looks like the original PR is being reverted. Assigning @chrispader to handle during reintroduction of the code!

**Comment by ikevin127** [comment] 2024-12-09 20:31
This is what the PRs https://github.com/Expensify/App/pull/53475 description says:

> ### Explanation of Change
> This PR includes a temporary fix for the slide in animations of modal screens like the ProfileAvatar screen. The reason the animation was not visible is because the screens with NativeStack only get mounted once we navigate there and the screen has not finished rendering/mounting when the modal animates in.

> Similarly, when we animate the modal out, we'll have to delay the back navigation by the modal animation duration.

> Ultimately, we should think about migrating react-native-modal/RN Modal screens to @react-navigation modal screens.

Since this was pushed as a **temporary fix**, I wouldn't revert the PR for seeing blank RHP **"for a moment"**, but if that's the recommended course here and there is a stronger argument for not wanting this blank RHP **"for a moment"** vs the modals not animating in/out then feel free to proceed.

cc @chrispader @mountiny @ishpaul777 for more context on the discussion where the PR revert was suggested and your take on whether we should actually revert or not given the issue is not a blocker for users in any way

**Comment by luacmartins** [comment] 2024-12-09 22:45
Fixed in staging after the revert

https://github.com/user-attachments/assets/9c1d0c01-0eaa-4384-b19e-752e97aa123a

**Closed** 2024-12-09 22:45 UTC
Labels: Reviewing, Engineering, Weekly, Bug
