### ISSUE TITLE
[$1000] Dev: Web -  cursor comes at the beginning of pasted text when pasting text to editing composer

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#23506] opened 2023-07-24 19:53 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Open an existing chat
2. Copy one of the message
3. Hover over one of your message > click on 'Edit comment icon
4. Paste the message

## Expected Result:
Cursor should come after the pasted message as it does when pasting text to the main composer

## Actual Result:
Cursor comes at the beginning of the pasted text

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [x] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** Dev 1.3.44.0
**Reproducible in staging?:** no
**Reproducible in production?:** no
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation
 

https://github.com/Expensify/App/assets/93399543/d509fe05-02d9-483e-aa8b-cc906810d96d

**Expensify/Expensify Issue URL:**
**Issue reported by:** @Natnael-guchima
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1690195074363549

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~016dcab34f26a37f30</li>
        <li>Upwork Job ID: 1683846752500838400</li>
        <li>Last Price Increase: 2023-07-25</li>
    </ul>
</details>

**Comment by garrettmknight** [comment] 2023-07-25 14:28
Reproduced, opening up.

**Comment by daordonez11** [comment] 2023-07-25 14:39
This is a regression of https://github.com/Expensify/App/pull/22443 being fixed by @aldo-expensify with this revert https://github.com/Expensify/App/pull/23518

**Comment by Natnael-Guchima** [comment] 2023-07-26 10:56
It is because the PR that has caused the bug is reverted here https://github.com/Expensify/App/pull/23518

**Comment by aldo-expensify** [comment] 2023-07-26 16:26
@garrettmknight I think the only pending here is to handle payment for reporting the issue

**Comment by garrettmknight** [comment] 2023-07-26 16:40
Yep, I'll pay out the reporter.

**Comment by garrettmknight** [comment] 2023-07-26 16:41
@Natnael-Guchima accept the job and I'll pay you!

**Comment by Natnael-Guchima** [comment] 2023-07-26 17:08
I have accepted the offer. Thanks @garrettmknight.

**Comment by garrettmknight** [comment] 2023-07-26 17:25
Summarizing payout for the issue:
- Issue reporter = @Natnael-Guchima 
- Contributor = N/A
- Contributor+ = N/A

Upwork job is [here](https://www.upwork.com/en-gb/ab/applicants/1683846752500838400/job-details). Paid and closing.

**Closed by garrettmknight** 2023-07-26 17:25 UTC
Labels: Daily, Bug
