### ISSUE TITLE
[HOLD for payment 2024-10-24] [$250] Hold - Edited amount is not updated for hold report when approve partial report

### ISSUE THREAD

**Issue by IuliiaHerets** [Expensify/App#49269] opened 2024-09-16 13:53 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 9.0.35-0
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**If this was caught during regression testing, add the test name, ID and link from TestRail:** https://expensify.testrail.io/index.php?/tests/view/4964020&group_by=cases:section_id&group_order=asc&group_id=309128
**Email or phone of affected tester (no customers):** gocemate+workspaceapprover183@gmail.com
**Issue reported by:** Applause Internal Team
 

## Action Performed:
Precondition:
1. Login as the owner of the workspace
2. Create a workspace
3. Invite the approver and employee
4. Navigate to more features
5. Enable "workflows"
6. On the "Workflow" editor - enable "Add Approvals"
7. Set the Approver account as the Approver

Steps:
1. As Employee submit 2 manual expenses to the workspace chat
2. As Approver hold the first expense
3. As Employee update the first expense amount
4. As Approver click on green Approve button> Approve the report partially
5. As Approver navigate back to held expense
6. Check the amount of the held request

## Expected Result:
Amount should be updated since employee change the amount

## Actual Result:
Held expense shows old amount, instead of the updated amount

## Workaround:
Unknown
## Platforms:

- [x] Android: Native
- [x] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

https://github.com/user-attachments/assets/21293f4f-e383-4b5c-9c05-42bfb3e72549

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~021837119590958615915</li>
        <li>Upwork Job ID: 1837119590958615915</li>
        <li>Last Price Increase: 2024-09-20</li>
<li>Automatic offers: </li>
<ul>
<li>shubham1206agra | Reviewer | 104090038</li>
<li>nkdengineer | Contributor | 104090041</li>
</ul></li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @JmillsExpensify</details>

**Comment by IuliiaHerets** [comment] 2024-09-16 13:53
We think that this bug might be related to #wave-collect - Release 1

**Comment by IuliiaHerets** [comment] 2024-09-16 13:54
@miljakljajic  FYI I haven't added the External label as I wasn't 100% sure about this issue. Please take a look and add the label if you agree it's a bug and can be handled by external contributors

**Comment by nkdengineer** [comment] 2024-09-17 09:28
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
Held expense shows old amount, instead of the updated amount

### What is the root cause of that problem?
We pass the total param when creating an optimistic expense report as `firstHoldTransaction?.amount` which is the original amount when we create this transaction, it's not the updated amount

https://github.com/Expensify/App/blob/14b99ca0a12e9686818bc3e937f091199de69750/src/libs/actions/IOU.ts#L6447
### What changes do you think we should make in order to solve the problem?
We should use `firstHoldTransaction?.modifiedAmount` first if it exists

```
(firstHoldTransaction?.modifiedAmount ?? firstHoldTransaction?.amount  ?? 0) * -1, 

```
https://github.com/Expensify/App/blob/14b99ca0a12e9686818bc3e937f091199de69750/src/libs/actions/IOU.ts#L6447

Or we can use `TransactionUtils.getAmount` function that already implemented this logic

```
TransactionUtils.getAmount(firstHoldTransaction) * -1,
```
https://github.com/Expensify/App/blob/14b99ca0a12e9686818bc3e937f091199de69750/src/libs/actions/IOU.ts#L6447

### What alternative solutions did you explore? (Optional)

**Comment by miljakljajic** [comment] 2024-09-20 13:21
Headed out on my parental leave so reassigning this one out. Thank you @JmillsExpensify 

Next step: @shubham1206agra please review @nkdengineer 's proposal when you have a chance

**Comment by JmillsExpensify** [comment] 2024-10-24 21:47
Payment summary: 

 - Contributor: $250 @nkdengineer via Upwork
 - Reviewer: $250 @shubham1206agra via Upwork

Please don't forget the checklist!

**Comment by JmillsExpensify** [comment] 2024-10-30 16:39
Contributor paid out. Still waiting on reviewer's checklist to issue last payment.

**Comment by JmillsExpensify** [comment] 2024-10-31 10:39
Regression test linked above. @shubham1206agra it looks like you didn't accept the automatic offer, so I've just send you a new one.

**Comment by JmillsExpensify** [comment] 2024-10-31 14:57
I'm trying to pay you out @shubham1206agra but I'm having technical issues on the Upwork side. Will pay you out as soon as it's resolved.

**Comment by JmillsExpensify** [comment] 2024-11-01 09:13
Sent you another offer. The original one is affected by some Upwork bug.

**Comment by JmillsExpensify** [comment] 2024-11-01 12:15
That one worked. Closing this issue out.

**Closed by JmillsExpensify** 2024-11-01 12:15 UTC
Labels: External, Daily, Awaiting Payment, Bug
