### ISSUE TITLE
Hold - "Confirm payment amount" modal appears on top of Troubleshoot menu

### ISSUE THREAD

**Issue by izarutskaya** [Expensify/App#44828] opened 2024-07-04 13:33 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 9.0.4-0
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**Found when validating PR :** https://github.com/Expensify/App/pull/42736
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Issue reported by:** Applause-Internal team

## Action Performed:
1. Go to staging.new.expensify.com
2. Go to workspace chat.
3. Submit an expense.
4. Go to transaction thread.
5. Click 3-dot menu > Hold.
6. Hold the expense.
7. Click Pay elsewhere.
8. While "Confirm payment amount" modal is showing, open Troubleshoot menu via CMD+D.

## Expected Result:
Troubleshoot menu will appear on top of "Confirm payment amount" modal.

## Actual Result:
"Confirm payment amount" modal appears on top of Troubleshoot menu.

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

https://github.com/Expensify/App/assets/115492554/b399923b-e47f-4978-80ed-dda223d74a21

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by izarutskaya** [comment] 2024-07-04 13:34
We think this issue might be related to the #collect project.

**Comment by bernhardoj** [comment] 2024-07-05 06:56
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
The confirm payment amount modal is shown on top of the troubleshoot modal.

### What is the root cause of that problem?
This happens to every modal, not limited to confirm payment amount modal. When we press the troubleshoot menu shortcut, we toggle the troubleshoot menu modal visibility.
https://github.com/Expensify/App/blob/74a6dbba2105ceba086f0387f50dcad573d4569f/src/libs/Navigation/AppNavigator/AuthScreens.tsx#L300-L305

If we see on other shortcuts, we always close the modal first and wait for until it's closed before executing the shortcut navigation.
https://github.com/Expensify/App/blob/74a6dbba2105ceba086f0387f50dcad573d4569f/src/libs/Navigation/AppNavigator/AuthScreens.tsx#L290-L294

But we don't do it for troubleshoot menu modal shortcuts, so the confirm payment amount or any modal/popover is still visible..

### What changes do you think we should make in order to solve the problem?

Wrap the troubleshoot menu shortcut with `Modal.close`

```
Modal.close(toggleTestToolsModal);
```

**Comment by RachCHopkins** [comment] 2024-07-09 03:27
Just clarifying internally on this one as it's not customer-facing.

**Comment by RachCHopkins** [comment] 2024-07-09 22:28
Closing per internal discussion.

**Closed by RachCHopkins** 2024-07-09 22:28 UTC
Labels: Daily, Bug
