### ISSUE TITLE
[HOLD for payment 2024-09-06] [$250] Workflows - "Approver" field disappears after unselecting approver

### ISSUE THREAD

**Issue by IuliiaHerets** [Expensify/App#47723] opened 2024-08-20 15:46 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** v9.0.22-5
**Reproducible in staging?:** Y
**Reproducible in production?:** Y 
**Email or phone of affected tester (no customers):** applausetester+kh050806@applause.expensifail.com
**Issue reported by:** Applause Internal Team

## Action Performed:
1. Go to staging.new.expensify.com
2. Go to workspace settings > Workflows.
3. Click on the modal under Add approvals.
4. Click Approver
5. Unselect the approver and click Save.

## Expected Result:
There should be "Approver" field in "Edit approval workflow" page after removing the approver so that approver can be reselected.

## Actual Result:
There is no "Approver" field in "Edit approval workflow" page after removing the approver.
The other field "Additional approver" requires an upgrade to access.

## Workaround:
Unknown

## Platforms:

- [x] Android: Native
- [x] Android: mWeb Chrome
- [x] iOS: Native
- [x] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

https://github.com/user-attachments/assets/42af38ac-7bf7-4fb4-816a-7acbdc0acac3

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01ac1b073e9e5491ad</li>
        <li>Upwork Job ID: 1826615705245101757</li>
        <li>Last Price Increase: 2024-08-22</li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @abekkala</details>

**Comment by IuliiaHerets** [comment] 2024-08-20 15:46
@abekkala  FYI I haven't added the External label as I wasn't 100% sure about this issue. Please take a look and add the label if you agree it's a bug and can be handled by external contributors

**Comment by bernhardoj** [comment] 2024-08-20 17:02
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
The approver field disappears when unselecting the approver.

### What is the root cause of that problem?
The approver field is shown based on the approver array.
https://github.com/Expensify/App/blob/c7ec59bb4ff3996c2dfa218c8d7a4d35dc5cebc7/src/pages/workspace/workflows/approvals/ApprovalWorkflowEditor.tsx#L130-L134

When we unselect the approver, the array is empty, thus, nothing is shown.

### What changes do you think we should make in order to solve the problem?

If the approver is empty, we can render a menu item with minimum details.
```
{approvalWorkflow.approvers.length > 0 ? (
    approvalWorkflow.approvers.map((approver, approverIndex) => {
        return ...
    })
) : (
    <MenuItemWithTopDescription
        wrapperStyle={styles.sectionMenuItemTopDescription}
        description={translate('workflowsPage.approver')}
        onPress={() => editApprover(0)}
        shouldShowRightIcon
    />
)}
```
We will need to do this for create approval flow too.

**Comment by DylanDylann** [comment] 2024-08-21 04:23
@blazejkustra Oh, we've got a new little one! 

In this case, If the user continues to click on the `Save` button. An error will be displayed


<img width="1229" alt="Screenshot 2024-08-21 at 11 20 06" src="https://github.com/user-attachments/assets/c17dd6d9-88fe-4822-8821-bae2c8b46236">

If we move forward with this issue with an external contributor, I suggest going with @daledah's [proposal](https://github.com/Expensify/App/issues/47723#issuecomment-2300491856)

> The first approver should always be mandatory in all cases. We should allow the user to update the approver but prevent them from deselecting the selected approver.

**Comment by jjcoffee** [comment] 2024-08-22 13:57
I think we're good to go with @bernhardoj's [proposal](https://github.com/Expensify/App/issues/47723#issuecomment-2299334014) here, as we already have an error to display if we try and save without an approver. 

@daledah's [proposal](https://github.com/Expensify/App/issues/47723#issuecomment-2300491856) would result in a lack of feedback to the user.

:ribbon::eyes::ribbon: C+ reviewed

**Comment by bernhardoj** [comment] 2024-08-24 05:01
PR is ready

cc: @jjcoffee

**Comment by DylanDylann** [comment] 2024-08-25 10:48
> @daledah's https://github.com/Expensify/App/issues/47723#issuecomment-2300491856 would result in a lack of feedback to the user.

@jjcoffee Ah see your point, I gave my opinion previously to make it consistent with "Expense from" section


https://github.com/user-attachments/assets/e9759e7b-f480-4d30-b93f-918ebfcf47c3

If we go with @bernhardoj's solution, please also update the "Expense from" section to make it consistent. Thanks

**Comment by bernhardoj** [comment] 2024-08-25 13:58
@jjcoffee @mountiny do you agree to change "Expense from" behavior to allow it to save without any user selected so it's the same with the Approver selection page?

**Comment by DylanDylann** [comment] 2024-08-25 15:38
cc @JmillsExpensify

**Comment by blazejkustra** [comment] 2024-08-26 07:54
Hey guys! Let's not overcomplicate this, we just need to change the copy on the `additionalApprover` input, and make sure admins can edit the default approver without the need to update the workspace to Control plan.

### Not a Proposal 😆 

```diff
diff --git a/src/pages/workspace/workflows/approvals/ApprovalWorkflowEditor.tsx b/src/pages/workspace/workflows/approvals/ApprovalWorkflowEditor.tsx
index 9864241a8e8..f232e971b24 100644
--- a/src/pages/workspace/workflows/approvals/ApprovalWorkflowEditor.tsx
+++ b/src/pages/workspace/workflows/approvals/ApprovalWorkflowEditor.tsx
@@ -97,7 +97,7 @@ function ApprovalWorkflowEditor({approvalWorkflow, removeApprovalWorkflow, polic
 
     // User should be allowed to add additional approver only if they upgraded to Control Plan, otherwise redirected to the Upgrade Page
     const addAdditionalApprover = useCallback(() => {
-        if (!PolicyUtils.isControlPolicy(policy)) {
+        if (!PolicyUtils.isControlPolicy(policy) && approvalWorkflow.approvers.length > 0) {
             Navigation.navigate(ROUTES.WORKSPACE_UPGRADE.getRoute(policyID, CONST.UPGRADE_FEATURE_INTRO_MAPPING.approvals.alias, Navigation.getActiveRoute()));
             return;
         }
@@ -151,7 +151,7 @@ function ApprovalWorkflowEditor({approvalWorkflow, removeApprovalWorkflow, polic
                 })}
 
                 <MenuItemWithTopDescription
-                    description={translate('workflowsCreateApprovalsPage.additionalApprover')}
+                    description={approvalWorkflow.approvers.length === 0 ? translate('workflowsPage.approver') : translate('workflowsCreateApprovalsPage.additionalApprover')}
                     onPress={addAdditionalApprover}
                     shouldShowRightIcon
                     wrapperStyle={styles.sectionMenuItemTopDescription}
```

cc @jjcoffee @DylanDylann @bernhardoj

**Comment by blazejkustra** [comment] 2024-08-26 07:56
> We should disable the submit button if the user doesn't select an approver on the first approver selection page

@daledah I believe it is against Expensify's guidelines, we don't want to disable the submit button and instead allow user to make an action and display an error.

**Comment by blazejkustra** [comment] 2024-08-26 13:41
> @blazejkustra That doesn't sound quite related to this issue, at least I don't think the (not a) proposal would do anything to fix the issue of the Approver field disappearing. Unless I'm missing something obvious, of course!

Check out the logic in `ApprovalWorkflowEditor` component, it displays a bunch of menu items that link to `Approver` and `Expenses From` screens:
- first: for updating members
- n-menu items: for updating existing approvers
- last: for adding a new approver

The idea behind this setup is to always have one **empty** menu item displayed, no matter how many approvers there are currently. If all approvers are removed we want to display **only one input**, this way it's less confusing for the user.

Here is the video of how it behaves with my fix:

https://github.com/user-attachments/assets/4e82239f-968a-4889-ba95-ea5fc3498e12

**Comment by jjcoffee** [comment] 2024-08-26 14:25
@blazejkustra Ahh gotcha, now it makes sense! I thought that having the `Additional approver` field always there was the intended behaviour, so that's why I was confused by your proposal :smile:

I'm a bit on the fence on hiding it if you deselect the default approver, since the `Additional approver` field is always there otherwise so represents the "default" UI state in my mind, and it feels a bit jarring for that field to disappear when I've only interacted with the default approver field. Having said that I'm not sure how much it matters either way :smile: @bernhardoj or @mountiny Do you have any strong feelings?

**Comment by bernhardoj** [comment] 2024-08-26 15:17
I think what @blazejkustra suggested makes sense to me. The additional approver is shown to allow the user to add another approver, but if we unselect the current approver, then the additional approver field seems unneeded.

**Comment by mountiny** [comment] 2024-08-26 16:33
Ah alright so thanks for chiming in @blazejkustra I agree the solution that Blazej implemented is the desired behaviour here

**Comment by jjcoffee** [comment] 2024-08-27 07:14
Sounds like a consensus to me! @bernhardoj Can you go ahead and implement @blazejkustra's suggestion in your PR?

**Comment by abekkala** [comment] 2024-08-29 13:31
merged to staging yesterday

**Comment by jjcoffee** [comment] 2024-09-04 14:30
[Deployed](https://github.com/Expensify/App/pull/47955#issuecomment-2322123049) to production Aug 30th, so should be due for payment 2024-09-06.

**Comment by abekkala** [comment] 2024-09-05 21:51
### PAYMENT SUMMARY FOR SEPT 06

- Fix: @bernhardoj [$250] payment via NewDot
- PR Review: @jjcoffee [$250] **OFFER**

**Comment by jjcoffee** [comment] 2024-09-06 08:00
@abekkala Accepted, thanks! :pray:

**Comment by bernhardoj** [comment] 2024-09-06 08:25
Requested in ND.

**Comment by JmillsExpensify** [comment] 2024-09-06 12:08
$250 approved for @bernhardoj

**Comment by abekkala** [comment] 2024-09-06 13:48
@jjcoffee payment sent and contract ended - thank you! 🎉

**Closed by abekkala** 2024-09-06 13:48 UTC
Labels: External, Daily, Awaiting Payment, Bug
