### ISSUE TITLE
[$500] Chat -  Join thread appears even if user is already joined

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#28499] opened 2023-09-29 15:19 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Go to any chat
2. Hover on the message and click on reply in thread option
3. Dend any message in thread
4. Click on three dots and select leave thread option
5. Again go to same thread
6. Click on three dots

## Expected Result:
It should show leave thread option

## Actual Result:
Join thread option appears

## Workaround:
Unknown 

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android / native
- [x] Android / Chrome
- [x] iOS / native
- [x] iOS / Safari
- [x] MacOS / Chrome / Safari
- [x] MacOS / Desktop

**Version Number:** v1.3.75-2
**Reproducible in staging?:** y
**Reproducible in production?:** new feature 
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/93399543/9c72736a-3782-4185-a397-34a524e96e8a

https://github.com/Expensify/App/assets/93399543/165796d9-aab9-4920-b420-89d06a1eee50

https://github.com/Expensify/App/assets/93399543/eba1ba16-17c7-4226-a8ce-50ab6ec560ab

https://github.com/Expensify/App/assets/93399543/6e7365a5-0130-4d0d-b60b-82bd06801f08

https://github.com/Expensify/App/assets/93399543/1e14d4b9-5b30-45f0-b62c-15c332ede687

https://github.com/Expensify/App/assets/93399543/a661e312-7c14-4786-9545-b04dd2fd257c

**Expensify/Expensify Issue URL:**
**Issue reported by:** @gadhiyamanan
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1695907051686469

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01dabd7bc44f3cd7c6</li>
        <li>Upwork Job ID: 1707777132631470080</li>
        <li>Last Price Increase: 2023-09-29</li>
    </ul>
</details>

**Comment by abdel-h66** [comment] 2023-09-29 16:00
It looks like a normal behaviour, after leaving a thread, You don't want to receive notifications, and then the second click on the thread will not be considered as joining, it's more like previewing the thread. If you performed an extra step, like clicking on another chat for example, the thread will not stick on the LHN.

**Comment by puneetlath** [comment] 2023-09-30 01:54
I agree, this seems like expected behavior to me. 

I'm going to close this, but cc @srikarparsi @chiragsalian just in case I'm mistaken.

**Closed by puneetlath** 2023-09-30 01:54 UTC
Labels: External, Daily, Help Wanted, Bug
