### ISSUE TITLE
[$500] PR27257-mWeb-Login-Typing phone number without country code, country code not added &SMSnot received

### ISSUE THREAD

**Issue by izarutskaya** [Expensify/App#28805] opened 2023-10-04 11:55 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Go to https://staging.new.expensify.com/
2. Enter wrong email
3. Note error message displayed
4. Enter correct email id
5. Enter correct magic code and login to site
6. Tap profile --Log out
7. Enter a phone number with country code
8. From received SMS, enter correct magic number and login
9. Tap profile --Log out
10. Enter a phone number without country code

## Expected Result:
Typing phone number without country code, country code must be added to phone number& sms must be received.

## Actual Result:
Typing phone number without country code, country code not added to phone number& sms not received.

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android / native
- [x] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [x] Windows - 10/ Chrome 
- [ ] MacOS / Desktop

**Version Number:** 1.3.77-3

**Reproducible in staging?:** Y

**Reproducible in production?:** Y

**If this was caught during regression testing, add the test name, ID and link from TestRail:**

**Email or phone of affected tester (no customers):**

**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/115492554/9ab14f36-11d4-4bdb-8c4d-f7659de7c067

https://github.com/Expensify/App/assets/115492554/3a3a6807-e6d2-4cb7-ae14-eef3d412d8c5

https://github.com/Expensify/App/assets/115492554/f1e47d94-3139-4a34-b622-d44948d9f437

**Expensify/Expensify Issue URL:**

**Issue reported by:** Applause-Internal Team

**Slack conversation:** @

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~017eea02da3f18b41e</li>
        <li>Upwork Job ID: 1709537770602115072</li>
        <li>Last Price Increase: 2023-10-04</li>
    </ul>
</details>

**Comment by izarutskaya** [comment] 2023-10-04 11:56
Found when validating PR https://github.com/Expensify/App/pull/27257

**Comment by pradeepmdk** [comment] 2023-10-04 13:45
as per this is not a bug https://expensify.slack.com/archives/C049HHMV9SM/p1690373508303109 by default +1 country code added in the background.

**Comment by soro-kuraima** [comment] 2023-10-04 14:10
Does expensify intend to append country codes for the numbers of all countries ?
if the answer is no: then this is not a bug. 

the phone number is parsed and the country code +1 is appended to all the numbers. 

and on the codeValidate form formatted phone number is displayed.
```typescript
function formatPhoneNumber(number: string): string {
    if (!number) {
        return '';
    }

    const numberWithoutSMSDomain = Str.removeSMSDomain(number);
    const parsedPhoneNumber = parsePhoneNumber(numberWithoutSMSDomain);

    // return the string untouched if it's not a phone number
    if (!parsedPhoneNumber.valid) {
        if (parsedPhoneNumber.number?.international) {
            return parsedPhoneNumber.number.international;
        }
        return numberWithoutSMSDomain;
    }

    const regionCode = parsedPhoneNumber.countryCode;

    if (regionCode === countryCodeByIP) {
        return parsedPhoneNumber.number.national;
    }

    return parsedPhoneNumber.number.international;
}
```

since +1 is appended to all the numbers, it returns formatted number without country code.

it happens for all the us numbers. whether you enter country code in input or not.

the screen recording in the bug report is an edge case, where appending +1 to number, results in a valid number on passing to parsePhoneNumber even though it's not a us number.
otherwise international numbers without country code simply fail the validation.

if the intended behaviour is to append country codes to codes of all nations.

**Comment by zanyrenney** [comment] 2023-10-10 12:24
Closing based on https://github.com/Expensify/App/issues/28805#issuecomment-1746912123

**Closed by zanyrenney** 2023-10-10 12:24 UTC
Labels: External, Daily, Help Wanted, Overdue, Bug
