### ISSUE TITLE
[HOLD for payment 2023-08-24] [$1000] IOS - The email in welcome message acts like a button in iOS

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#22103] opened 2023-07-03 12:14 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Login to ND
2. Go to any new chat
3. Long-press on the email in welcome message

## Expected Result:
The opacity remains unchanged

## Actual Result:
The opacity of the email changes like a button

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [x] iOS / native
- [ ] iOS / Safari
- [ ] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 1.3.32-5
**Reproducible in staging?:** n/a
**Reproducible in production?:** n/a
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/93399543/79a1358c-b00f-40b7-98c8-a57687dbf3f0

**Expensify/Expensify Issue URL:**
**Issue reported by:** @aman-atg
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1688035358417099

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~011e1d49b9ff9897e9</li>
        <li>Upwork Job ID: 1676883137564983296</li>
        <li>Last Price Increase: 2023-07-27</li>
<li>Automatic offers: </li>
<ul>
<li>abdulrahuman5196 | Reviewer | 25887098</li>
<li>aman-atg | Contributor | 25887099</li>
<li>aman-atg | Reporter | 25887101</li>
<li>c3024 | Contributor | 25990000</li>
</ul></li>
    </ul>
</details>

**Comment by zanyrenney** [comment] 2023-07-06 09:19
Hey @abdulrahuman5196 please review the proposal above from @aman-atg - thanks!

**Comment by zanyrenney** [comment] 2023-07-10 12:10
bump @abdulrahuman5196 please can you review the proposals on this issue and decide which is the best path forward here? thanks!

**Comment by zanyrenney** [comment] 2023-07-11 09:55
bump @abdulrahuman5196 let me know your thoughts or any blockers I can help with? Thanks.

**Comment by abdulrahuman5196** [comment] 2023-07-12 20:02
Sorry for the delay. Will complete the reviews tomorrow morning.

**Comment by abdulrahuman5196** [comment] 2023-07-15 18:17
@zanyrenney proposal from @aman-atg here https://github.com/Expensify/App/issues/22103#issuecomment-1618145232 is good. Do we need the behaviour of `PressableWithFeedback` or `PressableWithoutFeedback` here?

**Comment by abdulrahuman5196** [comment] 2023-07-15 18:18
Thank you for the proposal @c3024 here https://github.com/Expensify/App/issues/22103#issuecomment-1623820326. But the current recommended approach is to use `PressableWithFeedback` or `PressableWithoutFeedback` or similar generic components instead of buttons

**Comment by zanyrenney** [comment] 2023-07-18 11:16
I'm going to bring this discussion to slack!

**Comment by zanyrenney** [comment] 2023-07-19 14:26
I don't think this is a bug, I think it is polish. I am not able to reproduce having tried again just now. I have asked in slack for more detail.

**Comment by abdulrahuman5196** [comment] 2023-07-19 19:42
@zanyrenney 

>I don't think this is a bug, I think it is polish. I am not able to reproduce having tried again just now. I have asked in slack for more detail.

I am able to reproduce it. I think you have to look much closer 😶‍🌫️ , the opacity will only be different.
I agree it a polish, but a needed one. We have already migrated multiple touch places to use PressableWithFeedback or PressableWithoutFeedback or similar. This would have been a missed place.

>I see. thanks! so, the discussion was about whether the iOS solution should be h is to use PressableWithFeedback or PressableWithoutFeedback  but, if the only goal of this bug is consistency, why is there a debate? surely we would just mirror the behaviour on Android?

I didn't ask this because of platform consistency. Currently each platform will behave with its default behaviour without the fix. So we can't take one platform behaviour and make it as reference.
I was checking to see if we have similar requirement in some place in our app and take it as reference behaviour. @zanyrenney @aman-atg It would be great if we can point out a similar place or we have to confirm on which pressable behaviour would be suited for this and go from there.

**Comment by abdulrahuman5196** [comment] 2023-07-24 12:38
@zanyrenney any update on the above?

**Comment by zanyrenney** [comment] 2023-07-31 09:45
Hi @abdulrahuman5196 I see @aman-atg comment above, I believe we should use that as the target behaviour. Thanks!

**Comment by abdulrahuman5196** [comment] 2023-07-31 11:54
Reviewing today

**Comment by situchan** [comment] 2023-07-31 16:23
I don't think this is bug and worthy of fixing. This is iOS default behavior.
If this should be fixed, it should be applied to all Text which has onPress events across the app.

**Comment by abdulrahuman5196** [comment] 2023-08-01 16:09
@aman-atg 's alternate proposal here looks good and works well - https://github.com/Expensify/App/issues/22103#issuecomment-1618145232 . We can wrap the text inside PressableWithoutFeedback. During PR kindly make sure other chat types welcome texts is also fixed, for eg. group chat.

🎀 👀 🎀
C+ Reviewed

**Comment by zanyrenney** [comment] 2023-08-01 16:57
Hey! I am going OOO, please watch over this issue whilst I am out. There are a few proposals that we need reviewing.

**Comment by conorpendergrast** [comment] 2023-08-03 12:19
Is there a PR for this already @aman-atg? I don't see one yet

**Comment by abdulrahuman5196** [comment] 2023-08-03 13:48
@aman-atg I think you can also take references on how to fix this from other pages if any have similar use case. I remember reimbursement page had something similar not sure though. Maybe checking our existing places could provide some help.

**Comment by zanyrenney** [comment] 2023-08-07 09:45
thank you @conorpendergrast I am back now.

**Comment by zanyrenney** [comment] 2023-08-07 09:45
Is there anything preventing us from following on with that better proppsal @aman-atg ?

**Comment by conorpendergrast** [comment] 2023-08-07 09:54
@zanyrenney Unassinging myself, back to you, welcome back!

**Comment by zanyrenney** [comment] 2023-08-07 10:29
Brilliant, thanks for the update @c3024 - @danieldoglas @abdulrahuman5196 please can you confirm we're happy to go forward with this proposal?

**Comment by danieldoglas** [comment] 2023-08-07 14:32
Wait, the integrations got wrong here. Let me fix that.

**Comment by danieldoglas** [comment] 2023-08-07 14:35
@zanyrenney the integrations might have gotten messed up here, so maybe when paying you'll need to recheck the Upwork contracts. Other than that, @c3024 , you're assigned now.

**Comment by zanyrenney** [comment] 2023-08-25 10:16
@abdulrahuman5196 PAID $1000 - no urgency bonus
@c3024 PAID $1000 - no urgency bonus
@aman-atg - PAID $250.

All payments completed.

**Closed by zanyrenney** 2023-08-25 10:16 UTC
Labels: External, Engineering, Daily, Overdue, Awaiting Payment, Bug
