### ISSUE TITLE
Inconsistency between the width of display name and workspace name

### ISSUE THREAD

**Issue by kavimuru** [Expensify/App#26362] opened 2023-08-31 01:22 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Create a workspace
2. Rename with a short name
3. Update the display name with a short name
4. Notice when hovering over the workspace name and display name
## Expected Result: 
We should be consistent the width of display name and workspace name
## Actual Result: 
With display name, we must hover over the text to see the tooltip while with workspace name, we can see the tooltip when we don't hover the text

## Workaround:
Can the user still use Expensify without this being fixed? Have you informed them of the workaround?

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [x] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 1.3.59-2
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation

[Screencast from 22-08-2023 09_35_52.webm](https://github.com/Expensify/App/assets/43996225/f9cebb6d-806d-4840-b97d-2ae6fd591fb8)

**Expensify/Expensify Issue URL:**
**Issue reported by:** @dukenv0307
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1692671816331559

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by jliexpensify** [comment] 2023-08-31 02:02
@dukenv0307 from your second video - essentially, you're saying one set of margins is 16px, and one is 22px?

**Comment by kadiealexander** [comment] 2023-08-31 02:09
@dukenv0307 how is this impacting people's ability to use the app?

**Comment by jliexpensify** [comment] 2023-08-31 02:48
@dukenv0307 I understand that this is a visual inconsistency, but as Kadie queried - is it actually affecting people's usage of the app? Unless this inconsistency is breaking something, I wouldn't consider this a bug - I've previously queried similar inconsistencies with our team, and our Designers have said that they don't need to be fixed.

**Comment by jliexpensify** [comment] 2023-08-31 06:03
I'm still trying to understand if this is an actual issue that affects people using New.Dot - in my eyes, this seems like a minor inconsistency, but I am not an engineer so I could be wrong.

For this:

>For workspace name, the user hovers outside the name tooltip still display and can click to open new page. 

Are you saying I can click here and open the Settings?

![image](https://github.com/Expensify/App/assets/30815269/53b28d51-d3e6-484e-84ab-916884c2e4a2)

>But the display name is not.

What does this mean? Can you share a screenshot indicating what you mean by this?

**Comment by jliexpensify** [comment] 2023-08-31 12:12
Thanks for the video @dukenv0307 - I can definitely better understand what you mean now. I actually also had a call with an Engineer to discuss a few things and shared this GH for an additional opinion.

The Engineer reviewed it and gave me some context on what the inconsistency was, why there's an inconsistency, and mentioned that this is very likely intentional because we wanted to limit the workspace name (in case it was a long name) with "..." after it.

He also agreed that while it was inconsistent, his opinion was that this was not a bug, it doesn't affect anyone's usage of New.Dot and it was unlikely to be changed/fixed. Due to this, I'm going to close this GH - sorry!

**Closed by jliexpensify** 2023-08-31 12:12 UTC
Labels: Daily, Bug
