### ISSUE TITLE
[$500] [LOW] No Animation for Distance Request

### ISSUE THREAD

**Issue by mountiny** [Expensify/App#26516] opened 2023-09-01 19:39 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
Break down in numbered steps

1. Open Money Request
2. Swipe through the tabs
3. Observes only Distance Request doesn't have any animation.

## Expected Result:
Describe what you think should've happened

Every tab should have same animation.

## Actual Result:
Describe what actually happened

No animation for Distance Request

## Workaround:
Can the user still use Expensify without this being fixed? Have you informed them of the workaround?

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [x] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:**
**Reproducible in staging?:**
**Reproducible in production?:**
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/36083550/b33d4f6f-fa82-4aaa-8c7a-933666f47e8d

**Expensify/Expensify Issue URL:** 
**Issue reported by:** @b4s36t4 
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1693589998709469

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~014a6350725c978f6f</li>
        <li>Upwork Job ID: 1697695672445005824</li>
        <li>Last Price Increase: 2023-09-15</li>
    </ul>
</details>

**Comment by mountiny** [comment] 2023-09-01 19:39
cc @neil-marcellini

**Comment by akinwale** [comment] 2023-09-01 19:46
## Proposal

### Please re-state the problem that we are trying to solve in this issue.

### What is the root cause of that problem?
DistanceRequest does not have a single root view.

### What changes do you think we should make in order to solve the problem?
Set the DistanceRequest root component to View.

### What alternative solutions did you explore? (Optional)
None.

**Comment by mountiny** [comment] 2023-09-01 19:46
Same, also cannot repro, sometimes it lags, or it jumps as here https://github.com/Expensify/App/issues/26407 but not super clear to me, logging to make sure we definitely fix this

**Comment by akinwale** [comment] 2023-09-01 19:56
> Same, also cannot repro, sometimes it lags, or it jumps as here #26407 but not super clear to me, logging to make sure we definitely fix this

@mountiny The jumping can be reliably reproduced if you try to swipe the page before the previous page swipe animation finishes loading. My [proposal](https://github.com/Expensify/App/issues/26516#issuecomment-1703247672) fixes this.

**Comment by ZhenjaHorbach** [comment] 2023-09-01 21:15
# Proposal
## Please re-state the problem that we are trying to solve in this issue.
After swiping for Distance screen, the animation sometimes disappears.

## What is the root cause of that problem?

On the Distance screen, we have useEffect that sometimes interrupts the animation.
https://github.com/Expensify/App/blob/57603a08d0e018c5a428a5839ddb48a0b66115cd/src/components/DistanceRequest.js#L161

Therefore, the easiest way is to add a check that will check the end of the animation, and after that the useEffect will be called functions inside.
Fortunately, we have the ability to track the start and end of the animation during the transition of screens.

## What changes do you think we should make in order to solve the problem?
---

**Comment by mallenexpensify** [comment] 2023-09-04 02:35
@ArekChr , can you please review the above proposal when you have a minute?

**Comment by mallenexpensify** [comment] 2023-09-04 02:37
@muttmuure , unsure why there's two BZ on here, can you keep 👀 on the next week while I'm OOO? Thx

**Comment by ZhenjaHorbach** [comment] 2023-09-04 06:55
> # Proposal
> ## Please re-state the problem that we are trying to solve in this issue.
> After swiping for Distance screen, the animation sometimes disappears.
> 
> ## What is the root cause of that problem?
> On the Distance screen, we have useEffect that sometimes interrupts the animation. Only reproduce if we swipe fast !!! Most likely for this reason the bug is not reproduced when we click on Distance button since the swipe speed is fixed.
> 
> https://github.com/Expensify/App/blob/57603a08d0e018c5a428a5839ddb48a0b66115cd/src/components/DistanceRequest.js#L161
> 
> ## What changes do you think we should make in order to solve the problem?
> Therefore, the easiest way is to add a check that will check the end of the animation, and after that the useEffect will be called functions inside. Fortunately, we have the ability to track the start and end of the animation during the transition of screens. OR We can also just check when the screen is in focus and then called functions inside in useEffect.
> 
> Both options are valid and fix the issue.

I was wrong
Still playing
But I found a way to reproduce

If we pay attention to routing
After the swipe, the route changes very slowly and if during this time we can to swipe to the previous screen
we get bug
https://github.com/Expensify/App/assets/68128028/fcdbbd1b-6813-4896-934d-441774d0c19b

> ## What is the root cause of that problem?
>  Animation is skipped due to stunting and slow change page after swipe and instant return  
> ## What changes do you think we should make in order to solve the problem?
> https://github.com/search?q=repo%3AExpensify%2FApp%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20const%20routeNames%20%3D%20state.routeNames%3B&type=code
we have a state that only triggers after a long delay after swipe.
we can disable the swipe when we are on a new screen, but the route has not changed yet.
OR
Instead of using a state in screenListeners , we can route the current function from the state to each component
And call it during the focus of the screen

**Comment by ArekChr** [comment] 2023-09-04 10:48
This is to `@react-navigation/material-top-tabs` on the web platform. It seems that you can't swipe the tab when the animation is not finished (the state of the current tab index is delayed, which is blocking swiping back to the previous tab).
This also will happen when swiping immediately from manual -> scan -> manual

Reproduced with a clear solution with clean screens and without screen listeners.

https://github.com/Expensify/App/assets/24796318/656f693c-cfb8-4a24-b31c-7e6369101f9e

**Comment by mallenexpensify** [comment] 2023-09-11 05:11
Thanks @ArekChr , do you have a recommendation or alternatives to how we might want to 'fix' this (if possible)?

I don't notice it when I reproduce in Chrome on mac

**Comment by ArekChr** [comment] 2023-09-11 11:37
The best fix will be directly in `@react-navigation/material-top-tabs`. Otherwise, we have to disable this animation on the web platform as a workaround.

**Comment by mallenexpensify** [comment] 2023-09-14 05:36
Checking on [in Slack](https://expensify.slack.com/archives/C049HHMV9SM/p1694669744791709?thread_ts=1693589998.709469&cid=C049HHMV9SM)
<img width="506" alt="image" src="https://github.com/Expensify/App/assets/22508304/da72c531-9376-4e52-9693-3bc6f5eef719">

**Comment by mallenexpensify** [comment] 2023-09-14 06:01
@ArekChr , do you have any idea how much work it'd be to fix the root @react-navigation/material-top-tabs issue? And if Callstack would be interested in the job?  Thx

**Comment by ArekChr** [comment] 2023-09-14 11:35
@mallenexpensify, this issue seems straightforward and shouldn't take much time to resolve, to make sure it needs investigation. I'll ask the team internally.

**Comment by tgolen** [comment] 2023-09-15 23:43
This is no longer reproducible on the branch for https://github.com/Expensify/App/pull/26141 (I didn't check `main` though) so I'm going to close this.

**Closed by tgolen** 2023-09-15 23:43 UTC
Labels: External, Daily, Help Wanted, Bug
