### ISSUE TITLE
Workspace - 'Track distance' has rate = 0 and endless spinner is shown instead of block ‘Unlock next-day reimbursements’

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#20977] opened 2023-06-17 20:36 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Create and verify NEW expensifail account
2. Create NEW workspace
3. Goto Workspace > Reimbursements
4. Check 'Track distance' rate
5. Log out from account and login again

## Expected Result:
'Track distance' has default rate
Workspace is saved in the account after relogin

## Actual Result:
 'Track distance' has rate = 0. Endless spinner is shown instead of block ‘Unlock next-day reimbursements’
 Workspace is NOT saved in the account after re-login

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [x] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 1.3.29.0

**Reproducible in staging?:** Yes

**Reproducible in production?:** No

**If this was caught during regression testing, add the test name, ID and link from TestRail:**

**Email or phone of affected tester (no customers):**

**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/78819774/42c4f312-d7b7-4fdc-ab7a-5d02db5c987f

**Expensify/Expensify Issue URL:**

**Issue reported by:** Applause - Internal Team

**Slack conversation:**

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by luacmartins** [comment] 2023-06-19 19:27
I'm not able to reproduce this.

**Comment by luacmartins** [comment] 2023-06-19 19:29
nvm, this does happen for a brand new account.

**Comment by marcochavezf** [comment] 2023-06-19 21:21
I see the Concierge chat is not loading, probably it's a side-effect of  https://github.com/Expensify/App/issues/21036#issuecomment-1597557095

**Comment by luacmartins** [comment] 2023-06-19 21:39
Coming from [this thread](https://expensify.slack.com/archives/C07J32337/p1687190161495509), this seems to be caused by [#fireroom-getpersonaldetailslist](https://expensify.slack.com/archives/C05DX9SGLDN). Gonna remove the deploy blocker label and add a hold to retest once Auth is deployed.

**Comment by thienlnam** [comment] 2023-06-26 17:15
The linked Auth PR is merged https://github.com/Expensify/Auth/pull/8142 and deployed

Let's get this tested again

**Comment by thienlnam** [comment] 2023-06-26 17:15
cc @lanitochka17 Could you please see if this is still an issue?

**Closed** 2023-06-26 20:38 UTC
Labels: Engineering, Daily
