### ISSUE TITLE
Chat - Global create menu not displayed after tapping no thanks on banner

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#26289] opened 2023-08-30 14:00 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___
**Issue found when executing PR** https://github.com/Expensify/App/pull/26182
## Action Performed:
1. Sign into a new account
2. Verify Download App Banner appears
3. Click the "Close" button on the Download App Banner
4. Verify that the Banner closes

## Expected Result:
Global Create menu is opened

## Actual Result:
Global Create menu is not opened

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [x] iOS / Safari
- [ ] MacOS / Chrome / Safari
- [x] MacOS / Desktop

**Version Number:** 1.3.59

**Reproducible in staging?:** Yes

**Reproducible in production?:** No

**If this was caught during regression testing, add the test name, ID and link from TestRail:**

**Email or phone of affected tester (no customers):**

**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/78819774/8c8b3d95-e5ad-4276-beba-2b3e8f58c24a

**Expensify/Expensify Issue URL:**

**Issue reported by:** Applause - Internal Team

**Slack conversation:**

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by tgolen** [comment] 2023-08-30 17:13
Looks like Georgia has fixed this one so I am removing my assignment.

**Comment by luacmartins** [comment] 2023-08-30 18:05
Seems like a dupe of https://github.com/Expensify/App/issues/26288. We already merged/CPed the fix. Closing this issue.

**Closed by luacmartins** 2023-08-30 18:05 UTC
Labels: Reviewing, DeployBlockerCash, Engineering, Weekly
