### ISSUE TITLE
[HOLD for payment 2024-01-26] [$500] Threads - User is redirected to Concierge instead of room when leaving thread in room chat

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#33875] opened 2024-01-03 16:14 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** v1.4.21-1
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** Applause - Internal Team
**Slack conversation:**

## Action Performed:
1. Go to 1:1 DM.
2. Send a message and create a thread reply.
3. In the thread, click 3-dot menu > Leave thread.
4. Go to a room.
5. Send a message and create a thread reply.
6. In the thread, click 3-dot menu > Leave thread.

## Expected Result:
User is redirected to the main room chat because user only leaves the thread and not the room.

## Actual Result:
Instead of being redirected to the room chat, user is redirected to Concierge.

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [x] Android: mWeb Chrome
- [x] iOS: Native
- [x] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

https://github.com/Expensify/App/assets/93399543/ff579ce6-ffca-4312-ae98-c72bd55d68ff

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~0161fe76234b280e52</li>
        <li>Upwork Job ID: 1742580096727760896</li>
        <li>Last Price Increase: 2024-01-10</li>
<li>Automatic offers: </li>
<ul>
<li>Ollyws | Reviewer | 28096383</li>
<li>paultsimura | Contributor | 28096385</li>
</ul></li>
    </ul>
</details>

**Comment by paultsimura** [comment] 2024-01-03 16:31
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
On leaving a thread in room, the user is navigated to Concierge.

### What is the root cause of that problem?
In `Report.leaveRoom`, we navigate to the Concierge chat if we are leaving the room:

https://github.com/Expensify/App/blob/b3fe02ac603bc07ad6a22866290acb2a484eb345/src/libs/actions/Report.ts#L2126-L2132

However, the `isWorkspaceMemberLeavingWorkspaceRoom` passed into this function is calculated incorrectly: it does not count that inside rooms, we also can have threads.

### What changes do you think we should make in order to solve the problem?

Here, we should also check if the report is not a thread:

```js
const isWorkspaceMemberLeavingWorkspaceRoom = lodashGet(props.report, 'visibility', '') === CONST.REPORT.VISIBILITY.RESTRICTED && isPolicyMember && !ReportUtils.isChatThread(props.report)
```

https://github.com/Expensify/App/blob/fabb0b0f76f8b29209b369679082afd44640f186/src/pages/home/HeaderView.js#L154

### What alternative solutions did you explore? (Optional)

**Comment by miljakljajic** [comment] 2024-01-08 16:38
@Ollyws any thoughts on the two proposals?

**Comment by paultsimura** [comment] 2024-01-09 12:31
@Ollyws I can reproduce. The key factor here is that you should be a member of the workspace the room belongs to.
Will attach a video in a sec,

**Comment by paultsimura** [comment] 2024-01-11 15:25
Hey @Ollyws, any chance you could give another look at this issue? I've described the pre-requisite to reproduce [here](https://github.com/Expensify/App/issues/33875#issuecomment-1882988153)

**Comment by MonilBhavsar** [comment] 2024-01-12 09:27
Proposal fixes the issue, but I think this logic can be improved. `isWorkspaceMemberLeavingWorkspaceRoom` is kind of very random argument for leaveRoom function. Looks like in leaveRoom, we use to determine where we want to redirect user. Instead can we just pass the redirect path as an argument and keep the navigation logic outside of leaveRoom function?

**Comment by paultsimura** [comment] 2024-01-12 09:35
Well, yes and no. We use the `isWorkspaceMemberLeavingWorkspaceRoom` param not only for the redirection logic, but also to determine whether we want to remove the room from Onyx:

https://github.com/Expensify/App/blob/c8b44193d1a3ed0e84f6e5696bbeb6cc4c5b8090/src/libs/actions/Report.ts#L2084-L2114

I don't think we'd like to determine this logic based on the redirection path. So if we want to add a redirection path from outside this funciton, it will mean we need to add a third param.

@MonilBhavsar

**Comment by MonilBhavsar** [comment] 2024-01-12 09:44
Thanks for clarification. Looks good then

**Comment by paultsimura** [comment] 2024-01-12 19:46
Thanks. The PR is ready for review: https://github.com/Expensify/App/pull/34461

**Comment by MonilBhavsar** [comment] 2024-01-17 16:59
PR Merged!

**Comment by miljakljajic** [comment] 2024-01-22 12:35
@Ollyws please accept the upwork offer before the 26th :)

**Closed** 2024-01-29 17:41 UTC
Labels: External, Weekly, Awaiting Payment, Bug
