### ISSUE TITLE
[$500] Web - Workspace - "Hmm... it's not here" error when creating workspaces

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#38322] opened 2024-03-14 16:39 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.51.0
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:** https://expensify.testrail.io/index.php?/tests/view/4405644&group_by=cases:section_id&group_id=296775&group_order=asc
**Issue reported by:** Applause - Internal Team

## Action Performed:
1. Log in with a new Gmail account
2. Click on the "Choose a workspace" button
3. Click on the "Get Started" button
4. Click on the "Choose a workspace" button again
5. Click on "Expensify"
6. Click on the "New workspace" button
7. Repeat steps 4-6 until you have 5 workspaces
8. Click on the "Choose a workspace" button
9. Click on the "+" button next to the Workspaces text

## Expected Result:
I shouldn't be getting an error.
I should be shown as the owner.

## Actual Result:
"Hmm... it's not here" error when creating workspaces.
I'm not shown as the owner of the workspace if an error occurs while creating it.

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

https://github.com/Expensify/App/assets/93399543/1869d5d1-0248-43c6-943c-ad1bedc7eebe

https://github.com/Expensify/App/assets/93399543/6719b470-179d-4cef-a16d-945933b0d284

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~012d4246a099f91460</li>
        <li>Upwork Job ID: 1770401523684294656</li>
        <li>Last Price Increase: 2024-03-20</li>
    </ul>
</details>

**Comment by kbecciv** [comment] 2024-03-14 16:39
@JmillsExpensify I haven't added the External label as I wasn't 100% sure about this issue. Please take a look and add the label if you agree it's a bug and can be handled by external contributors.

**Comment by kbecciv** [comment] 2024-03-14 16:40
We think that this bug might be related to #wave-collect - Release 1
CC @trjExpensify

**Comment by JmillsExpensify** [comment] 2024-03-20 02:46
Hmm, yes I think this might potentially be related to the on-going simplified collect project. cc @mountiny and @luacmartins

**Comment by luacmartins** [comment] 2024-03-20 03:02
hmm I'm not sure, those are all free workspaces and we didn't touch any of the logic for creating new workspaces. @kbecciv is there an error in your browser console?

**Comment by mountiny** [comment] 2024-03-20 10:47
I dont think its related to simplified collect but really odd reproductions steps too, I could not repro locally.


Mkaing this external though so we can see if there any contributor can help here

**Comment by iammudassirali** [comment] 2024-03-20 11:25
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
The issue revolves around encountering a "Hmm... it's not here" error when attempting to create workspaces in the Expensify web application. Additionally, users are not shown as the owner of the workspace if an error occurs during the creation process.

### What is the root cause of that problem?
The root cause of this problem likely lies in the workspace creation flow, specifically in the handling of errors and ownership assignment. It appears that there may be inconsistencies or issues with the validation and processing of workspace creation requests.

### What changes do you think we should make in order to solve the problem?
To address this issue, we should thoroughly review the workspace creation logic and error handling mechanisms. This may involve improving error messages to provide more meaningful feedback to users and ensuring that ownership is correctly assigned even in the event of errors.

### What alternative solutions did you explore? (Optional)
An alternative approach could involve implementing robust error logging and monitoring to track occurrences of the "Hmm... it's not here" error and identify patterns or underlying issues. Additionally, we could explore implementing retries or fallback mechanisms to gracefully handle errors and prevent disruptions in the workspace creation process.

By addressing the root cause and enhancing the error handling and ownership assignment mechanisms, we can ensure a smoother and more reliable workspace creation experience for users in the Expensify web application.

Please let me know if you need further clarification or assistance with implementing these solutions.

Best regards,
**Mudassir Ali**

**Comment by mountiny** [comment] 2024-03-20 13:35
Seems like this was tested on this PR ad hoc build https://github.com/Expensify/App/pull/37817 not in staging, not sure why it got reported like this

**Comment by mountiny** [comment] 2024-03-20 13:35
Asked for retest in staging https://expensify.slack.com/archives/C9YU7BX5M/p1710931652941519

**Comment by mountiny** [comment] 2024-03-20 14:10
So this seems to not be repro on staging anymore based on the discussion, it was repro in previous versions

I am going to close this one

**Closed by mountiny** 2024-03-20 14:10 UTC
Labels: External, Daily, Help Wanted, Bug
