### ISSUE TITLE
[HOLD for payment 2023-11-30] [$500] Request money - Hmm it's not here page opens when click on Learn more via the banner below

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#31567] opened 2023-11-20 17:34 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.1-5
**Reproducible in staging?:** Y
**Reproducible in production?:** N
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** Applause - Internal Team
**Slack conversation:**

## Action Performed:
1. Go to URL https://staging.new.expensify.com/
2. Login with any account
3. Go to FAB -> Request -> Manually
4. Enter any amount -> Next
5. Click on get $250 -> Learn more

## Expected Result:
The additional information page opens

## Actual Result:
Hmm it's not here page opens

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [x] Android: mWeb Chrome
- [x] iOS: Native
- [x] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details> 

https://github.com/Expensify/App/assets/78819774/7b445153-59f5-49da-83fa-1b4c073a0318

![Bug6284020_1700498537252!image__175_](https://github.com/Expensify/App/assets/78819774/8cb786be-79ef-4c3d-a7e1-0f4cc0fbb301)

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01fc74f5c607d04925</li>
        <li>Upwork Job ID: 1726668962396127232</li>
        <li>Last Price Increase: 2023-11-20</li>
<li>Automatic offers: </li>
<ul>
<li>ishpaul777 | Contributor | 27755628</li>
</ul></li>
    </ul>
</details>

**Comment by luacmartins** [comment] 2023-11-20 23:23
Removing label since we CPed a fix

**Comment by lschurr** [comment] 2023-11-26 17:26
@mananjadhav could you work on the checklist for this one if needed?

**Comment by lschurr** [comment] 2023-11-29 17:08
Payment summary:

- Bug reporter: Applause (no payment)
- Contributor: @ishpaul777 $500 (to be paid in Upwork)
- Contributor+: @mananjadhav $500 (to be paid in Newdot)

**Comment by lschurr** [comment] 2023-11-29 17:08
Bump on the checklist @mananjadhav

**Comment by mananjadhav** [comment] 2023-11-29 17:13
> Contributor+: @mananjadhav $500 (to be paid in Newdot)

@lschurr I wasn't able to review this PR. Do you want me to still work on the checklist for the payout?

**Comment by lschurr** [comment] 2023-11-29 17:22
Ah, thanks for clarifying @mananjadhav! Nope, if you didn't work on it, I'll update the payment summary.

**Comment by mananjadhav** [comment] 2023-11-29 17:25
> Do you want me to still work on the checklist for the payout

just clarifying, I meant the payout for the external contributor if it is stuck because of this.

**Comment by luacmartins** [comment] 2023-11-29 17:33
>@luacmartins - do we need a regression test for this one?

I don't think we do. Applause caught this during regression test.

**Comment by lschurr** [comment] 2023-11-29 17:43
Cool, we're good! I'll pay @ishpaul777 tomorrow and we'll be set to close.

**Comment by lschurr** [comment] 2023-11-30 17:28
Paid! Closing this one out.

**Closed by lschurr** 2023-11-30 17:28 UTC
Labels: External, Engineering, Daily, Awaiting Payment, Bug
