### ISSUE TITLE
[$1000] Not able to add a task assignee

### ISSUE THREAD

**Issue by Beamanator** [Expensify/App#20807] opened 2023-06-15 12:08 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. click on + icon and click on Assign task option
2. enter title and click on Next button
3. click on Assignee option
4. click on any user

## Expected Result:
user should be assign as Assignee

## Actual Result:
not able to assign any Assignee

## Workaround:
Can the user still use Expensify without this being fixed? Have you informed them of the workaround?

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [ ] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** `main`
**Reproducible in staging?:**
**Reproducible in production?:**
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation
**Expensify/Expensify Issue URL:**
**Issue reported by:** @gadhiyamanan
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1686829718168319

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01e2aaeba9308a0daa</li>
        <li>Upwork Job ID: 1669330942765027328</li>
        <li>Last Price Increase: 2023-06-15</li>
    </ul>
</details>

**Comment by BeeMargarida** [comment] 2023-06-15 12:50
Hi I'm Ana from Callstack - expert contributor group - I can work on this issue.

**Comment by alitoshmatov** [comment] 2023-06-15 13:00
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
Not able to add a task assignee
### What is the root cause of that problem?
We have changed field in recent PR,  `assigneeAccountID` was changed to `newAssigneeAccountID`

https://github.com/Expensify/App/blob/961d93c83b210f24666a79291e66336a10e93e54/src/libs/actions/Task.js#L474

https://github.com/Expensify/App/blob/961d93c83b210f24666a79291e66336a10e93e54/src/libs/actions/Task.js#L496

But we are not using updated field here
https://github.com/Expensify/App/blob/4fdc8dbec2cbd74190a68ca5008092a2dbbdbc16/src/pages/tasks/NewTaskPage.js#L81
### What changes do you think we should make in order to solve the problem?
We should change field name here

https://github.com/Expensify/App/blob/4fdc8dbec2cbd74190a68ca5008092a2dbbdbc16/src/pages/tasks/NewTaskPage.js#LL81C1-L81C1

to this
```javascript
assigneeAccountID: newAssigneeAccountID
``` 

### What alternative solutions did you explore? (Optional)

**Comment by Beamanator** [comment] 2023-06-15 13:09
@eVoloshchak please review the proposal above when you have time!

**Comment by youssef-lr** [comment] 2023-06-15 13:24
I'm getting this fixed in my PR here https://github.com/Expensify/App/pull/20808.

**Comment by conorpendergrast** [comment] 2023-06-15 13:44
Unassigning @eVoloshchak based on this being fixed in [this PR](https://github.com/Expensify/App/pull/20808), please correct me if that's wrong. 

I'll hire @gadhiyamanan as bug reporter... when Upwork comes back

**Comment by conorpendergrast** [comment] 2023-06-19 13:46
Ok, looks like the fix for this is on Staging now https://github.com/Expensify/App/pull/20808

I'll re-test now on Staging

**Comment by conorpendergrast** [comment] 2023-06-19 14:02
Tested on v1.3.29-1, and no issue with adding the task assignee 👍

**Comment by conorpendergrast** [comment] 2023-06-19 14:11
Once [that PR](https://github.com/Expensify/App/pull/20808) reaches production, I'll get that bug bounty paid and will close this issue

**Comment by youssef-lr** [comment] 2023-06-21 20:16
Not overdue.

**Comment by conorpendergrast** [comment] 2023-06-22 11:28
This is on Production: https://github.com/Expensify/App/pull/20808

Time to pay!

**Comment by conorpendergrast** [comment] 2023-06-22 11:31
Paid out @gadhiyamanan, ended contract. Closing!

**Closed by conorpendergrast** 2023-06-22 11:31 UTC
Labels: External, Daily, Help Wanted, Bug
