### ISSUE TITLE
UI - Border radius of attached protected pdf does not match with parent component

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#11520] opened 2022-10-02 17:59 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Go to staging.new.expensify.com
2. Go to any conversation
3. Send password protected pdf
4. Notice blue border of protect attachment
5. Notice there is white space in all corner

Expected Result:
Blue border radius of protected pdf should match with parent component

## Actual Result:
Blue border radius of protected pdf does not match with parent component (leaves white spaces in corner)

## Workaround:
Unknown

## Platform:

Where is this issue occurring?

- Web
- iOS
- Android
- Desktop App
- Mobile Web

**Version Number:** 1.2.11.1

**Reproducible in staging?:** Yes

**Reproducible in production?:** Yes

**Email or phone of affected tester (no customers):** any

**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Notes/Photos/Videos:** Any additional supporting documentation

![Screenshot_20221002-135136_New Expensify](https://user-images.githubusercontent.com/93399543/193468842-4911e6ad-c2bd-4d2c-b8e1-8562bd3c89fc.jpg)
![image (5)](https://user-images.githubusercontent.com/93399543/193468843-8603d08c-a5c2-48d7-88a1-e18f6d97790e.png)
![image (6)](https://user-images.githubusercontent.com/93399543/193468844-5d46c6d1-e55d-467e-8572-ce1b716e5fb9.png)

**Expensify/Expensify Issue URL:** 

**Issue reported by:** @dhairyasenjaliya

**Slack conversation:** https://expensify.slack.com/archives/C01GTK53T8Q/p1664363401205419

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by Justicea83** [comment] 2022-10-03 16:37
This can be external

**Comment by ajaynagwani777** [comment] 2022-10-03 20:03
**PROPOSAL**

` if (html !== text) {
                const editedTag = props.fragment.isEdited ? '<edited></edited>' : '';
                const htmlContent = html + editedTag;
                return (
                    <RenderHTML
                        html={props.source === 'email'
                            ? `<email-comment>${htmlContent}</email-comment>`
                            : `<comment>${htmlContent}</comment>`}
                    />
                );
            }`

The issue is with the HTML being rendered. If we remove the borderColor, borderWidth and borderRadius from the HTML it will be fixed. 

@kbecciv

**Comment by ajaynagwani777** [comment] 2022-10-04 15:47
@eVoloshchak 

I gave the solution because the gray outline is not visible apart from the incorrect border. Still if we need the border to be there we can set the `border-radius` to `15px` , rn it is `8px` in HTML.

**Comment by eVoloshchak** [comment] 2022-10-04 15:54
> I gave the solution because the gray outline is not visible apart from the incorrect border. 

For me it's visible

<img width="662" alt="Screenshot 2022-10-04 at 18 49 29" src="https://user-images.githubusercontent.com/9059945/193866187-cb93742a-f28c-4c7b-8a91-52839e74dc44.png">

> Still if we need the border to be there we can set the border-radius to 15px , rn it is 8px in HTML.

Yeah, that would be perfect!
Could you please include a code snipped with this change?

**Comment by ajaynagwani777** [comment] 2022-10-04 16:19
@eVoloshchak 

In `styles.js -> tagStyles -> img`
Existing object: 

```
img: {
            borderColor: themeColors.border,
            borderRadius: variables.componentBorderRadiusNormal, // 8
            borderWidth: 1,
        }
```

Updated object:

```
img: {
            borderColor: themeColors.border,
            borderRadius: 10,
            borderWidth: 1,
        }
```

**Comment by eVoloshchak** [comment] 2022-10-04 17:19
<img width="264" alt="Screenshot 2022-10-04 at 20 17 18" src="https://user-images.githubusercontent.com/9059945/193884289-5a50aff8-22c7-4d58-b4ff-1eca0abbcc59.png">
<img width="224" alt="Screenshot 2022-10-04 at 20 19 05" src="https://user-images.githubusercontent.com/9059945/193884639-717d2a4a-82a6-4e70-96f1-be9da447fedf.png">

That's what it looks like for me with `borderRadius: 10`.
We need to figure out why it's inconsistent, so in case we change the border radius of this card (or blue border around it), this issue doens't appear once again. They should have the same variable with border radius

**Comment by ajaynagwani777** [comment] 2022-10-04 17:21
> <img alt="Screenshot 2022-10-04 at 20 17 18" width="264" src="https://user-images.githubusercontent.com/9059945/193884289-5a50aff8-22c7-4d58-b4ff-1eca0abbcc59.png">
> 
> <img alt="Screenshot 2022-10-04 at 20 19 05" width="224" src="https://user-images.githubusercontent.com/9059945/193884639-717d2a4a-82a6-4e70-96f1-be9da447fedf.png">
> 
> That's what it looks like for me with `borderRadius: 10`. We need to figure out why it's inconsistent, so in case we change the border radius of this card (or blue border around it), this issue doens't appear once again. They should have the same variable with border radius

Sorry, it was 15. I mention 10 by mistake.

**Comment by Puneet-here** [comment] 2022-10-04 20:35
### Proposal

I think the image that is being used should be fixed so that it fits correctly but if we want a front end solution I propose changing the border radius but only for the pdf

we can check if it's a pdf by `Str.isPDF(source)`

and if it's true we will use borderRadius 15 ( we will add it in the styles.js)
https://github.com/Expensify/App/blob/93587b19296f6c07567b5576418725ae213321ed/src/components/HTMLEngineProvider/HTMLRenderers/ImageRenderer.js#L73
```js
 style={[styles.webViewStyles.tagStyles.img, Str.isPDF(source) && styles.bR15]}
```

**Comment by eVoloshchak** [comment] 2022-10-04 21:53
> I think the image that is being used should be fixed so that it fits correctly 

Agree, I also think this is the best solution. It would make it consistent with all of the other images 


> but if we want a front-end solution I propose changing the border-radius but only for the pdf, we can check if it's a pdf by Str.isPDF(source)

Awesome, that's what was missing from the previous proposal. I think it should be 14 instead of 15, but it's kinda hard to tell


To summarize, we have [2 ways](https://github.com/Expensify/App/issues/11520#issuecomment-1267547462) to fix this issue
1. Replace the "Password protected PDF" image with the one with the correct border-radius (probably requires changes to the back end)
2. Change border-radius on the front-end for the "Password protected PDF" image only 

@marcaaron, could you please take a look at this, what do you think?

**Comment by marcaaron** [comment] 2022-10-05 00:14
>I think the image that is being used should be fixed so that it fits correctly

Agree with this approach as well, but I would maybe modify it so that the image can have any custom border set in the front end so that we do not need to cut a new image each time someone changes the border.

So basically something like:

- generic version of this image without a border at all
- if we have the pdf that is password protected put the blue border on it
- otherwise use the grey one

Where does this image come from? I'm not really sure tbh. Maybe @Expensify/design knows.

**Comment by shawnborton** [comment] 2022-10-05 01:21
Ah yeah, we should just use a version that has no rounded borders, I agree. 

Hmm I'm not sure where it's hosted, but I remember @michelle-thompson working on it not that long ago? Maybe she can dig up the GH for it?

**Comment by michelle-thompson** [comment] 2022-10-05 19:30
I found the graphic but have to remove the border first - @shawnborton do you think we should make any updates to font/branding while we're at it?
![image](https://user-images.githubusercontent.com/43361905/194146242-ae45c0de-fc0d-48ff-a614-21f272d2314d.png)

**Comment by shawnborton** [comment] 2022-10-09 23:40
That makes sense to me. Do you have the old GH handy from where you first did this update? I'm trying to figure out where this is hosted - it might be something that we need to update internally on the Expensify end in the Web repo.

**Comment by michelle-thompson** [comment] 2022-10-10 15:45
I wasn't able to find it in my issues, but I think I worked with @thienlnam on this before so he might know!

**Comment by thienlnam** [comment] 2022-10-11 02:26
Yes, agree on all the sentiments here that we should be updating the image asset instead of making a front-end solution.

Here's that old issue for adding this - https://github.com/Expensify/Expensify/issues/136829

**Comment by michelle-thompson** [comment] 2022-10-12 23:55
@thienlnam do you know if the image is in the Web repo somewhere?

**Comment by thienlnam** [comment] 2022-10-13 01:01
It's in the Web-PDFs repo `var/pdfs.expensify.com/assets/encrypted-file-thumbnail.jpg` 

https://github.com/Expensify/Web-PDFs/blob/2240636796dd4ab730329552341bea83227efb5d/var/pdfs.expensify.com/assets/encrypted-file-thumbnail.jpg

**Comment by marcaaron** [comment] 2022-10-16 22:34
Going OOO for a week so unassigning, but looks like this is going to be internal before it's external - so I think we should consider just making it internal.

**Comment by shawnborton** [comment] 2022-10-17 16:39
Agree, I think we need to assign internally to an engineer to update the file in [the location Jack posted above](https://github.com/Expensify/App/issues/11520#issuecomment-1276898268).

**Comment by shawnborton** [comment] 2022-10-20 15:14
I can take this one now. I think this actually needs to be assigned to an internal engineer though, so let me try to do that, unless you can quickly tackle this one @thienlnam?

**Comment by thienlnam** [comment] 2022-10-20 23:59
I'm heading OOO after today as well, though if it's just to update the file locations you should have write access to make a PR in that location (maybe?). But I'll just pullerbear another engineer to help ya out with this

**Comment by thienlnam** [comment] 2022-10-21 00:06
Oh goodness sorry for the pings, I accidentally pressed the external label but it assigned an engineer so problem failed successfully

**Comment by sketchydroide** [comment] 2022-10-31 12:57
the new file is a png and the old one a jpg, is this a problem, should they both be the same formart? I'm not sure we use the formart when when ussing assets. @shawnborton

**Comment by sketchydroide** [comment] 2022-11-02 17:12
[It seems like Web-PDFs is not deployable at the moment, we need to wait for the upgrade to php8 ](https://expensify.slack.com/archives/C03TQ48KC/p1667408166217289)

**Comment by sketchydroide** [comment] 2022-11-02 19:24
BZ?

**Comment by marcaaron** [comment] 2022-11-02 20:48
Check this @sketchydroide -> https://docs.google.com/document/d/1JVk4S8r_ets5lwM6KdpggQHG7li_H3VSE8qETYbe6gI/edit

**Comment by sketchydroide** [comment] 2022-11-02 20:49
ahh Bug Zero of course

**Comment by JmillsExpensify** [comment] 2022-11-08 19:45
Huh, I'm not certain what's going on in this issue. The linked PR is merged, but is Web-PDFs still not deployable?

**Comment by sketchydroide** [comment] 2022-11-09 11:44
last time I checked it was because we couldn't deploy Web-PDFs yet due to the PHP 8 thing, I'll check if this has changed in the last week

**Comment by sketchydroide** [comment] 2022-11-16 13:34
@iwiznia any update on the PHP upgrade and deploying this? 🙇🏼 
Sorry to bring you in, but it's just easier to track that way

**Comment by JmillsExpensify** [comment] 2022-11-17 05:37
Oh right, I have been meaning to bug Ionatan on this one. 😄

**Comment by JmillsExpensify** [comment] 2022-11-22 07:07
Looks like this issue is just waiting on a production deploy to close.

**Comment by sketchydroide** [comment] 2022-11-22 14:17
![Screenshot 2022-11-22 at 14 17 24](https://user-images.githubusercontent.com/242568/203336896-c8f1824a-40e4-43d7-9da1-c8af934599ed.png)
confirmed, closing

**Closed by sketchydroide** 2022-11-22 14:17 UTC
Labels: Weekly, Internal, Bug

**Comment by dhairyasenjaliya** [comment] 2022-11-22 14:33
hello @sketchydroide @JmillsExpensify Upwork job for reporting the issue is missing

**Comment by dhairyasenjaliya** [comment] 2022-11-26 18:15
Bump for Upwork job for reporting the issue @JmillsExpensify

**Comment by JmillsExpensify** [comment] 2022-11-26 18:24
Ah for clarity, the US is currently on holiday. Let me create a quick job for you though since it seems we're both online.

**Comment by JmillsExpensify** [comment] 2022-11-26 18:26
Upwork job is here: https://www.upwork.com/jobs/~01ca1e43be96f08f0e.

**Comment by dhairyasenjaliya** [comment] 2022-11-26 18:30
Appied , Ah I see sorry for trouble have a great holiday

**Comment by JmillsExpensify** [comment] 2022-11-26 18:39
Not a problem! Let's get this settled for you, as I'm online. Just sent you an offer via Upwork. 🙌🏼

**Comment by dhairyasenjaliya** [comment] 2022-11-26 18:43
Accepted offer @JmillsExpensify

**Comment by JmillsExpensify** [comment] 2022-11-26 18:45
Payment issue and contract closed! You should be all set now, let me know if I can help with anything else.

**Comment by dhairyasenjaliya** [comment] 2022-11-26 18:47
All good thank you👍 @JmillsExpensify
