### ISSUE TITLE
[HOLD for payment 2024-11-05] [$250] Chat - File does not appear with strikethrough style when uploaded offline and deleted

### ISSUE THREAD

**Issue by m-natarajan** [Expensify/App#46616] opened 2024-07-31 21:59 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 9.0.15-4
**Reproducible in staging?:** y
**Reproducible in production?:** no, production has different behavior
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** Applause internal team
**Slack conversation:**

## Action Performed:
1. Go to staging.new.expensify.com
2. Go to any chat.
3. Go offline.
4. Upload a file.
5. Right click on the file.
6. Click Delete comment.

## Expected Result:
The file will appear with strikethrough style when deleted offline (production behavior).

## Actual Result:
The file does not appear with strikethrough style when deleted offline.

## Workaround:
unknown
## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [x] Android: mWeb Chrome
- [x] iOS: Native
- [x] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

https://github.com/user-attachments/assets/1b7124c0-9a7d-4181-b483-a168912ff58f

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Issue Owner</summary>Current Issue Owner: @OfstadC</details>
<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01f435ef631a03057d</li>
        <li>Upwork Job ID: 1825625197125448253</li>
        <li>Last Price Increase: 2024-08-19</li>
<li>Automatic offers: </li>
<ul>
<li>Krishna2323 | Contributor | 103626009</li>
</ul></li>
    </ul>
</details>

**Comment by m-natarajan** [comment] 2024-07-31 22:00
We think that this bug might be related to  #vip-vsb

**Comment by roryabraham** [comment] 2024-07-31 23:26
cc @kidroca I think this might be related to https://github.com/Expensify/App/pull/44889

**Comment by roryabraham** [comment] 2024-07-31 23:45
not sure this needs to be a blocker

**Comment by roryabraham** [comment] 2024-07-31 23:45
Curious for design input ... what should we display when you upload an image and then delete it, all offline? What should be the "strikethrough" equivalent for images?

**Comment by dubielzyk-expensify** [comment] 2024-07-31 23:54
Good question. There's a few things we could do:
A) Delete it altogether and not show it
B) Put some sort of visual treatment over it similar to what we do with the offline thumbnail. So something like the mock to the complete right:
![CleanShot 2024-08-01 at 09 54 00@2x](https://github.com/user-attachments/assets/7569688b-4b8e-42df-aa51-f6d488531451)

**Comment by roryabraham** [comment] 2024-08-01 17:00
I'm going to demote this to NAB

**Comment by OfstadC** [comment] 2024-08-01 20:53
Reassigning as i'm out tomorrow and Monday

**Comment by OfstadC** [comment] 2024-08-01 20:55
@kevinksullivan Feel free to assign back to me on Tuesday - I just don't want the first steps held up on me 😃

**Comment by dubielzyk-expensify** [comment] 2024-08-02 04:32
Forgot to cc @shawnborton for his thoughts on [this solution](https://github.com/Expensify/App/issues/46616#issuecomment-2261675844)

**Comment by shawnborton** [comment] 2024-08-02 10:34
For your B solution, I think my first reaction is it feels like a connectivity thing that the image wouldn't load. 

What if we literally tried the same treatment as a strikeout? Like we made the image at 50% opacity, and then put a 1px horizontal border running through the middle with some overlap on the sides? Is that nuts?

**Comment by neil-marcellini** [comment] 2024-08-02 20:20
I'm going to make Jon the owner until we nail down the design. I personally like this idea:
![image](https://github.com/user-attachments/assets/52c82096-014e-4919-8407-cb14e1dd0b7d)

**Comment by dubielzyk-expensify** [comment] 2024-08-04 06:07
> What if we literally tried the same treatment as a strikeout? Like we made the image at 50% opacity, and then put a 1px horizontal border running through the middle with some overlap on the sides? Is that nuts?

Is this what you mean? If so, then it feels very odd. Feel free to play around in [Figma](https://www.figma.com/design/WlrZyRCTQ0LFoKcjSmtTsd/General-UI-Patterns?node-id=3824-16964&t=ZJM8Bg3Zw6A0yoOC-4)
![image](https://github.com/user-attachments/assets/b8c22ac9-8ad2-46a7-8ca6-165fff4ebca3)

This is also a pretty edge-casey scenario. People have to be offline and delete a photo.

**Comment by shawnborton** [comment] 2024-08-05 12:38
So I think this is what I was thinking:
![CleanShot 2024-08-05 at 08 37 47@2x](https://github.com/user-attachments/assets/c998f3e8-5d5f-4f22-b8d6-53cee68a303e)

I agree though, it does feel a bit odd...

**Comment by dubielzyk-expensify** [comment] 2024-08-05 22:44
> That is what I was thinking, but I wasn't expecting a dark border/negative space around the strikethrough line.

The reason for this is the strikethrough could be very hard to see in some instances so it would create some visual distinction. 

I think the whole strikethrough looks a bit broken to me. Never seen this pattern to me. Keen to hear what @dannymcclain thinks though

**Comment by kidroca** [comment] 2024-08-06 05:46
I'm also thinking strike makes sense for text, but isn't intuitive on images. Replacing the image with a placeholder for deleted attachments (the bin), or some kind of a blend in case users have to see the underlying original image, seems more intuitive to me.

**Comment by shawnborton** [comment] 2024-08-06 12:39
> I think the whole strikethrough looks a bit broken to me. Never seen this pattern to me.

Yeah, I think I agree. I was curious to see what it would look like, but after seeing it in practice maybe it's not so great. 

>  Replacing the image with a placeholder for deleted attachments (the bin)

Definitely down to try this out. So maybe something like Jon's 4th screen [here](https://github.com/Expensify/App/issues/46616#issuecomment-2261675844), but perhaps the trash can icon is overlaid on top of the image somehow? Not sure if that will look great or not but maybe worth trying?

**Comment by dannymcclain** [comment] 2024-08-06 13:50
When the user goes back online in this situation, what happens? Do the messages just disappear completely?

I think Jon's option B + trash can mock looks good, but I'm honestly questioning why we don't just remove the message entirely if that's what is going to happen once you're back online anyways. What value is the user getting out of seeing the trashcan icon or file preview with strikethrough?

![CleanShot 2024-08-06 at 08 47 12@2x](https://github.com/user-attachments/assets/f4e974b7-446a-4c51-b9a3-c88b5f494ad8)

**Comment by shawnborton** [comment] 2024-08-06 14:14
I guess the idea here is it's a pending action? But yeah... maybe it should just be optimistic? I am going to call upon my favorite offline pattern expert @trjExpensify for a 4th opinion here :)

**Comment by dubielzyk-expensify** [comment] 2024-08-07 06:39
Yeah. I think we should keep the image there, Danny, because if not you'll see strikethrough on text for deleted text, but deleted images will go away. I think we should at least do the same everywhere for consistency.

**Comment by dannymcclain** [comment] 2024-08-07 13:58
Ok yeah that makes sense to me. In that case, I definitely prefer the trash-can-icon-placeholder-thingy version. Feels very clear that there used to be an image here, but it has been deleted.

**Comment by trjExpensify** [comment] 2024-08-07 22:59
>I guess the idea here is it's a pending action? But yeah... maybe it should just be optimistic? I am going to call upon my favorite offline pattern expert @trjExpensify for a 4th opinion here :)

Yeah, Pattern B here is "optimistic with feedback" - so it's pending in the UI until coming back online to confirm it succeeds or fails. For pending delete actions, we use strikethrough and 50% opacity. Then on failure, revert to 100% opacity, drop the strikethrough and RBR to an error message in-line. 

We keep the "data" in the UI until we confirm it has successfully been deleted, because the optimistic action could fail. I think attachment uploads fall into the pattern B bucket because it could be something sensitive or uploaded in error, so you want to know it successfully deleted. Otherwise, we'd use "Pattern A - optimistic without feedback" and optimistically remove it from the UI and not tell you if it was successful or not when you come back online. 

Anyhow, I recall we came up against this before for images in the Pattern B doc way back when. The profile avatar at the time, and we decided in [this ancient thread](https://expensify.slack.com/archives/C02HWMSMZEC/p1656005936435959) to only reduce the opacity of the image for pending delete actions. Interestingly, looks like that's offline action is now either broken in app today or purposefully changed to Pattern A.

So I think one option could be to still do that for the mainline "uploaded online, removed offline" case: 

- "attachment + text" - strikethrough and reduce the opacity of the text, only reduce the opacity of the attachment
- "attachment only" - only reduce the opacity of the attachment

But this edge case of "upload offline and delete offline" is sticky when it comes to "attachment only" because it's already at 50% opacity pending to be added, and so it'll seem like nothing happened. We could just live with that for now, or go with the idea to put some kind of trash overlay on pending delete images in all cases. I think that could work! 

Bit of a sidebar, but related.. an intuitive way (you'd think!) to handle all of the "add and delete the same thing offline" actions would be to remove it from the UI without feedback and that's that. After all, it was pending to be added, so there shouldn't be a risk of it not being deleted and being actioned on or seen by others etc. But we really don't handle taking these two actions on the same object well until we commit to fixing the "replay effect" ([context](https://github.com/Expensify/App/issues/12775)). It’s a bit of a downside of the offline design to handle these edge cases, but you basically see things get re-added, and disappears again as the queued create/delete actions run sequentially:

https://github.com/user-attachments/assets/3b77c851-27f1-4627-abb9-327f200cdc58


We determined it's not worth the effort to fix that now.

**Comment by dubielzyk-expensify** [comment] 2024-08-07 23:59
Ah that's really helpful context. Are you suggesting just reducing the opacity then or delete it altogether? If we just reduce the opacity it'll share the look of the uploaded-while-offline pattern which seems non-ideal?

I think this is such a small case that I don't feel super strongly about it. I guess I was mostly leaning towards consistency in this instance, but happy for someone to make the call.

**Comment by shawnborton** [comment] 2024-08-08 11:36
> After all, it was pending to be added, so there shouldn't be a risk of it not being deleted and being actioned on or seen by others etc

Ah yeah, this makes complete sense to me and I would be in favor of something like that.

**Comment by trjExpensify** [comment] 2024-08-08 12:10
Yeah, we could Shawn, though I think the replay effect will still end up showing it again, then removing it. So it's still not great for that "upload offline and delete offline" edge case.

That aside, we still need to decide how we want to handle the more typical case of just deleting an already uploaded attachment offline. That should remain pending delete in the UI, so do we want to do this:

>"attachment + text" - strikethrough and reduce the opacity of the text, only reduce the opacity of the attachment
>"attachment only" - only reduce the opacity of the attachment

Recognising (to Jon's point) that for that attachment only case it doesn't use strikethrough in addition to reduced opacity, and thus appears as the same pattern as "pending create" in that regard. 

![image](https://github.com/user-attachments/assets/62ca6a6c-712f-4b9a-afcb-6d98260b14d9)

Or, do we want to do something for attachment thumbnails where we reduce the opacity of the preview and add a trash can overlay or something, so it's a bit more visually distinct than just reducing the opacity like pending create? 

![image](https://github.com/user-attachments/assets/a062f5ad-81cd-4c19-ab2d-7c49fb3681e8)

I'm not super passionate about which one.

**Comment by shawnborton** [comment] 2024-08-08 12:19
I don't mind the latter option with the trash can icon (I mentioned that [here](https://github.com/Expensify/App/issues/46616#issuecomment-2271192540)), but I think the icon itself wouldn't get reduced opacity and it might use a brand color?

**Comment by trjExpensify** [comment] 2024-08-08 12:33
Cool, nice! Here's a look at using brand/ice and not reducing the opacity on the icon: 
![image](https://github.com/user-attachments/assets/d0960029-a1e7-46b1-9c14-f91b0e7212fb)

I'll leave that to the experts though! 😅

**Comment by shawnborton** [comment] 2024-08-08 12:34
Oh, I was thinking just to use our standard icon color there 🤣

**Comment by trjExpensify** [comment] 2024-08-08 12:37
>I'll leave that to the experts though

innit. 

![image](https://github.com/user-attachments/assets/a99c963e-f6fe-4df6-8ecd-3be36f66c8c4)

**Comment by shawnborton** [comment] 2024-08-08 12:39
Innit. I can get down with what you have there, let's see what the rest of the design team thinks though.

**Comment by kidroca** [comment] 2024-08-08 13:53
Hey guys, I think I might be responsible for setting this transparency idea in motion. I suggested to blend the icon with the attachment so the user has a sense of what particular attachment/photo would get deleted when they resume connectivity, but I'm not really sure if this is a requirement. 

If it's not a requirement to see the particular attachment, I think it would be much more user friendly and accessible to display a placeholder image/card containing something like "This attachment is pending deletion" and the trashcan icon 

For exclusively offline actions I'm on board of removing right away.
Regarding the "replay effect" it has a high impact on attachments. It would be beneficial to find some solution, because it would be pointless to upload some big attachment only to deleted it the next instant. 
Related to the "reply effect" and skipping the upload, I will soon be working on a separate "upload queue" that would be responsible for all attachment upload actions. It's being developed mainly to allow for bigger attachments, but it might help skip the "reply effect" when it concerns attachments

**Comment by dannymcclain** [comment] 2024-08-08 14:21
I think if we're going to continue displaying the attachment, we could maybe add our `overlay` behind the icon to give it some more distinction from the pending state. Don't feel too strongly about that though. I also think Jon's original mock of just showing the placeholder with trashcan icon works too (so not displaying the image/attachment anymore).

![image](https://github.com/user-attachments/assets/8216e4e6-e283-4f1e-a98d-be3b1d38e2c6)

**Comment by shawnborton** [comment] 2024-08-08 14:57
Cool, I can honestly get down with any and all of that. Happy to go with whatever the group decides :)

**Comment by dubielzyk-expensify** [comment] 2024-08-09 02:04
Whichever with the icon looks good to me 👍

**Comment by trjExpensify** [comment] 2024-08-09 16:43
I love the right side from Danny here: https://github.com/Expensify/App/issues/46616#issuecomment-2275957037

**Comment by trjExpensify** [comment] 2024-08-09 16:45
>Related to the "reply effect" and skipping the upload, I will soon be working on a separate "upload queue" that would be responsible for all attachment upload actions. It's being developed mainly to allow for bigger attachments, but it might help skip the "reply effect" when it concerns attachments

That would be great! 

We're also exploring a solution for the replay effect [here](https://github.com/Expensify/App/issues/46393#issuecomment-2278237800) which might be in place as well.

**Comment by dubielzyk-expensify** [comment] 2024-08-15 00:22
Looks like we have a solution here then. Let's get to implementing @neil-marcellini and/or @kevinksullivan  😄

**Comment by neil-marcellini** [comment] 2024-08-19 20:03
Sorry for the delay. I'm getting caught up on the huge discussion here.

From [Tom's longer comment](https://github.com/Expensify/App/issues/46616#issuecomment-2274487496):
> Bit of a sidebar, but related.. an intuitive way (you'd think!) to handle all of the "add and delete the same thing offline" actions would be to remove it from the UI without feedback and that's that. After all, it was pending to be added, so there shouldn't be a risk of it not being deleted and being actioned on or seen by others etc. But we really don't handle taking these two actions on the same object well until we commit to fixing the "replay effect" ([context](https://github.com/Expensify/App/issues/12775)). It’s a bit of a downside of the offline design to handle these edge cases, but you basically see things get re-added, and disappears again as the queued create/delete actions run sequentially:

I thought we fixed the replay effect! I can remember putting a month or more of effort into that so it's quite a bummer to see that it's still broken 😞. Oh well. I think we could implement what you're suggesting there regarding optimistic data although it would be challenging, and it's not directly related to the replay effect. Sounds like there are some plans to get it fixed so that's great

**Comment by neil-marcellini** [comment] 2024-08-19 20:05
To be clear, we're going with the [mockup on the right side here](https://github.com/Expensify/App/issues/46616#issuecomment-2275957037), yeah?

@Krishna2323 would you please update your proposal?

**Comment by dubielzyk-expensify** [comment] 2024-08-19 22:51
That looks good to me :)

**Comment by neil-marcellini** [comment] 2024-08-21 19:44
> Just caught up with the discussion. Based on the mock ups and the expected behaivor, @Krishna2323's [proposal](https://github.com/Expensify/App/issues/46616#issuecomment-2263047602) looks good to me.

I agree, assigning!

**Comment by kevinksullivan** [comment] 2024-09-12 19:23
PR still a draft. @Krishna2323 any update on when you'll hav this up for review? Also, I'm looping in a BZ member to handle payment as I'm going OOO

**Comment by OfstadC** [comment] 2024-09-27 13:15
Looks like there is still active discussion on the PR - so things are still moving along here?

**Comment by mananjadhav** [comment] 2024-09-27 23:08
@neil-marcellini Can you confirm https://github.com/Expensify/App/pull/47971#issuecomment-2371316308 ?

**Comment by OfstadC** [comment] 2024-10-14 15:25
Looks like the PR is still moving along 😄

**Comment by mananjadhav** [comment] 2024-10-14 15:48
Yes I am halfway through the code review (mostly final) and finish the checklist soon.

**Comment by OfstadC** [comment] 2024-11-01 15:14
@mananjadhav please complete the checklist before November 5th so I can issue payment - Thank you! 😃

**Comment by mananjadhav** [comment] 2024-11-01 18:32
I would treat this more of a feature request. But I think we should add a regression test for this one.

@OfstadC here's the regression test proposal:

1. Go to any chat
2. Upload a file (format: .txt/.html/.zip/)
3. Upload image & video
4. Go offline
5. Right click on the file
6. Click Delete comment
7. Verify an overlay with trash icon is shown for deleted video & image and the filename is crossed for the other file. (format: .txt/.html/.zip/)
8. Stay offline and repeat step 2 to 7

**Comment by OfstadC** [comment] 2024-11-04 22:14
https://github.com/Expensify/Expensify/issues/441632
Will issue payment tomorrow 😃

**Comment by OfstadC** [comment] 2024-11-05 19:17
## Payment Summary

- @mananjadhav due $250 via manual NewDot request
- @Krishna2323 [paid](https://www.upwork.com/nx/wm/workroom/38158732/overview) $250 via Upwork

**Closed by OfstadC** 2024-11-05 19:17 UTC
Labels: External, Engineering, Daily, Design, Awaiting Payment, Bug

**Comment by garrettmknight** [comment] 2024-11-06 10:07
$250 approved for @mananjadhav
