### ISSUE TITLE
[$250] [One expense report] Approving a report, followed by automations, causes a one-expense report to go blank or loading skeleton

### ISSUE THREAD

**Issue by m-natarajan** [Expensify/App#44878] opened 2024-07-04 23:48 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 9.0.4-0
**Reproducible in staging?:** Yes
**Reproducible in production?:** Yes
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** @JmillsExpensify 
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1720018295381949

## Action Performed:
1. Set up a Collect policy on NewDot as userA
2. On OldDot, configure a bank account, keep the auto-reimburse limit at $100
3. On OldDot, set the manual approve amount to $0 (so all reports need approval)
4. On OldDot, invite userB who submits expenses
5. On NewDot, have userB submit a $50 expense to the right policy
6. On NewDot, have userA approve the report
## Expected Result:
The one expense report shows the green paid checkmarks and is otherwise unchanged
## Actual Result:
The one expense report goes blank, Loading skeleton and clicking the expense displayed `Hmm, it's not here page`
## Workaround:
Unknown
## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [X] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos
![CleanShot 2024-07-03 at 09 36 32](https://github.com/Expensify/App/assets/38435837/3a687f4d-678f-4998-9e3d-3d3e77460a84)

https://github.com/Expensify/App/assets/38435837/b0a2dc26-1d35-497f-a39f-8369cb9f997e

Add any screenshot/video evidence

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01328ea73a58f5c7eb</li>
        <li>Upwork Job ID: 1810441796510837868</li>
        <li>Last Price Increase: 2024-07-22</li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @ZhenjaHorbach</details>

**Comment by jliexpensify** [comment] 2024-07-05 10:15
Still trying to repro

**Comment by jliexpensify** [comment] 2024-07-08 22:32
Hi @ZhenjaHorbach I was having some issues reproducing last week but we're going to open this one up to Contributors. Hopefully you can repro this!

**Comment by trjExpensify** [comment] 2024-07-11 18:14
@ZhenjaHorbach did you get setup and everything and it was working as expected?

**Comment by trjExpensify** [comment] 2024-07-11 20:20
Gotcha. Do you have a vid?

**Comment by trjExpensify** [comment] 2024-07-11 23:14
Yeah cool, because when you click approve it should be paid automatically if you have auto-reimbursement enabled. You shouldn't be needing to click pay at all.

**Comment by ahmedGaber93** [comment] 2024-07-12 08:15
I notice when trying to reproduce if I open the report from the search tab the new messages action not displayed (approve and paid message, also if I send message it not displayed), and I need to refresh the browser or open it from user report in workspace. And this not match the attached video in issue description. Maybe if the new message action appear, we can reproduce the issue.

**Comment by ahmedGaber93** [comment] 2024-07-12 08:28
I mean your video here https://github.com/Expensify/App/issues/44878#issuecomment-2225035734 after clicking "Approve" the approved and paid message not appear util refreshing the browser

**Comment by jliexpensify** [comment] 2024-07-16 04:37
Not overdue, any updates @ZhenjaHorbach?

**Comment by jliexpensify** [comment] 2024-07-18 23:06
Just curious - @JmillsExpensify are you still experiencing this issue? Are there any repro steps we're missing?

**Comment by trjExpensify** [comment] 2024-07-22 16:31
@JmillsExpensify isn't seeing this anymore, closing.

**Closed by trjExpensify** 2024-07-22 16:31 UTC
Labels: External, Daily, Help Wanted, Bug
