### ISSUE TITLE
[$1000] Text input label is moving while adding a bank account to a workspace

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#18714] opened 2023-05-10 12:41 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Issue found when executing PR** https://github.com/Expensify/App/pull/18468 

## Action Performed:
1. Open the App
2. Login
3. Open Settings > Workspaces
4. Open any existing workspace or create a new one if you don't have one
5. Open Connect Bank Account > Connect Bank Manually or with Plaid
6. Complete the 1st and 2nd step
7. From the 3rd step, go back
8. Verify the text input birthdate label is not moving

## Expected Result:
The text input label is not moving

## Actual Result:
The text input label is a little moving compared to other environments.

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android / native (example device:  SG M52)
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [ ] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 1.3.12.0

**Reproducible in staging?:** Yes

**Reproducible in production?:** Yes

**If this was caught during regression testing, add the test name, ID and link from TestRail:**

**Email or phone of affected tester (no customers):**

**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/93399543/22010baa-12e8-48c0-84aa-bb287265c910

**Expensify/Expensify Issue URL:**

**Issue reported by:** Applause - Internal Team

**Slack conversation:**

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01f18692795ade1d13</li>
        <li>Upwork Job ID: 1658893459664945152</li>
        <li>Last Price Increase: 2023-05-17</li>
    </ul>
</details>

**Comment by alex-mechler** [comment] 2023-05-10 16:46
@kbecciv Can you list what devices this was reproducible on? It seems to only affect a few specific devices. Samsung Galaxy S10 seems to be a device that we can get reproductions on

**Comment by kbecciv** [comment] 2023-05-15 20:30
@alex-mechler Issue reproduced on SG M52

**Comment by arielgreen** [comment] 2023-05-16 03:57
Thanks @kbecciv !

**Comment by arielgreen** [comment] 2023-05-19 02:07
Not overdue, the job was just created yesterday.

**Comment by fabioh8010** [comment] 2023-05-19 09:19
Hi I'm Fábio from Callstack - expert contributor group - I would like to take a look at this issue

**Comment by fabioh8010** [comment] 2023-05-22 16:28
**Update:** I wasn't able to reproduce this issue on the emulator, as stated before it seems to be very device-specific. I asked a team member which has a Galaxy A32 (Android 11) to test and he wasn't able to reproduce it.

https://github.com/Expensify/App/assets/20051562/daaea6d0-0890-4814-9d2f-a0371dae2514

Tomorrow I'll ask another team member that has a Galaxy S9 to try to test and reproduce the issue.

---

**Note:** It's not related to this issue and I'm not sure if it was already reported, but the checkbox text is "broken".

![Screenshot_1684772823](https://github.com/Expensify/App/assets/20051562/81240191-5ad3-48ec-884d-a81f5ac1c7eb)

**Comment by arielgreen** [comment] 2023-05-23 00:54
@fedirjh @fabioh8010 please be sure to apply to the Upwork posting [here](https://www.upwork.com/jobs/~01f18692795ade1d13).

**Comment by fabioh8010** [comment] 2023-05-23 14:29
**Update:** We tried another device, Samsung Galaxy S9 SM-G960F (Android 10), but again we weren't able to reproduce this issue.

https://github.com/Expensify/App/assets/20051562/329d7de0-e132-4f1a-9dd1-e25c52ca8790

I'm afraid that I won't be able to work on a fix for this issue, as I don't have the means to reproduce it. I also would like to reinforce that this kind of minor visual glitches that are very device-specific are usually not worth fixing it, as it can be a issue with a specific custom OS version or a range of devices of a specific brand. In most of these cases, the issue is with the custom OS / device itself and probably are not solvable.

**Comment by deetergp** [comment] 2023-05-23 23:09
@fabioh8010 @fedirjh @mountiny Should we just close this one then?

**Comment by mountiny** [comment] 2023-05-24 20:19
Yes completely agree, thanks for digging into this Fabio.

I will close this out as there seems to be no payments due here, thanks!

**Closed** 2023-05-24 20:19 UTC
Labels: External, Daily, Bug
