### ISSUE TITLE
The "Hmm... it's not here" page is displayed when attempting to view a profile after splitting the bill.

### ISSUE THREAD

**Issue by kavimuru** [Expensify/App#20970] opened 2023-06-17 17:53 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Open the app and click on the plus sign, then choose "split bill".
2. Enter the desired amount and click on  "Next".
3. Choose who you want to split with
4. Click on "split the bill" and click on the Profile. The detail section will appear on the right.
5. Click on the profile, but instead of displaying the profile details, the "Hmm... it's not here" page appears.
## Expected Result: 
Clicking on a profile after splitting the bill should display the profile details or images.
## Actual Result: 
Clicking on a profile after splitting the bill displays the "Hmm... it's not here" page instead of the profile details.

## Workaround:
Can the user still use Expensify without this being fixed? Have you informed them of the workaround?

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [x] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 1.29-0
**Reproducible in staging?:** y
**Reproducible in production?:** n
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation

[screen-capture (15).webm](https://github.com/Expensify/App/assets/43996225/737eab70-053b-420f-b403-763acff57c32)

https://github.com/Expensify/App/assets/43996225/0a01ce7e-0a84-4b5f-99f8-998618b50490

**Expensify/Expensify Issue URL:**
**Issue reported by:** @ayazhussain79 
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1686899440198109

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by BhuvaneshPatil** [comment] 2023-06-17 18:54
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
The "Hmm... it's not here" page is displayed when attempting to view a profile after splitting the bill

### What is the root cause of that problem?
We are using `login` in `MoneyRequestConfirmationList`.
https://github.com/Expensify/App/blob/83ab0160a3b5c385fd26fffe20bdbccabf9249c0/src/components/MoneyRequestConfirmationList.js#L236-L241

### What changes do you think we should make in order to solve the problem?
We shall update the `login` to `accountID` as per new implementations.

### What alternative solutions did you explore? (Optional)

**Comment by Pujan92** [comment] 2023-06-17 21:23
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
The "Hmm... it's not here" page is displayed when attempting to view a profile after splitting the bill.

### What is the root cause of that problem?
Empty string gets passed for `ReportUtils.getAccountIDForLogin(option.login)` here as that function call won't work bcoz we are passing loginId here and inside function `getAccountIDForLogin` it is fetching from `personalDetailsList` onyx key which has the mapping with accountID's.

https://github.com/Expensify/App/blob/bee8fd3e1634fa11761435ef405a3d3efd654b07/src/components/MoneyRequestConfirmationList.js#L236-L241

### What changes do you think we should make in order to solve the problem?
We have the `accountID` here for the option object which we can use directly.

https://github.com/Expensify/App/blob/bee8fd3e1634fa11761435ef405a3d3efd654b07/src/components/MoneyRequestConfirmationList.js#LL240C2-L240C2

`Navigation.navigate(ROUTES.getProfileRoute(option.accountID));`

Also this condition can be updated with accountID.
https://github.com/Expensify/App/blob/bee8fd3e1634fa11761435ef405a3d3efd654b07/src/components/MoneyRequestConfirmationList.js#L237

`!option.accountID`

**Comment by Beamanator** [comment] 2023-06-19 15:07
@0xmiroslav sorry it looks like you linked the PR twice, did you mean to link an issue?

**Comment by Beamanator** [comment] 2023-06-19 15:13
Aahhh this is the "Also, there was another new issue happening on main" issue, yeah? Great, i'll make this not a deploy blocker 😬 

@luacmartins whenever you see this, feel free to close if it's not reproducible (since it shouldn't be 🙏 )

**Comment by luacmartins** [comment] 2023-06-19 21:24
I can't reproduce this, but I also see no emails/display names in the list

![Screenshot 2023-06-19 at 3 24 42 PM](https://github.com/Expensify/App/assets/22219519/ce588fdf-91cd-4e4b-ac05-7bbfc22f6e91)

**Comment by luacmartins** [comment] 2023-06-20 15:01
@0xmiroslav same as the OP.

**Comment by Beamanator** [comment] 2023-06-20 16:00
FYI...

> I also see no emails/display names in the list

This was fixed earlier in PR: https://github.com/Expensify/App/pull/21113

**Comment by luacmartins** [comment] 2023-06-21 22:07
This specific issue has been fixed. We had other issues for the missing display names, etc. Closing.

**Closed by luacmartins** 2023-06-21 22:07 UTC
Labels: Engineering, Daily, Bug
