### ISSUE TITLE
[$125] Cancel payment - "Cancel payment" in three-dot menu is not translated to Spanish

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#33513] opened 2023-12-22 17:38 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.16-3
**Reproducible in staging?:** Y
**Reproducible in production?:** N
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** Applause - Internal Team
**Slack conversation:**

**Issue found when executing PR** https://github.com/Expensify/App/pull/32674
## Action Performed:
1. Go to workspace chat
2. Create a manual request
3. Open expense report
4. Click Pay elsewhere
5. Change app language to Spanish
6. Click 3-dot menu

## Expected Result:
In Step 6, "Cancel payment" in 3-dot menu is translated to Spanish

## Actual Result:
In Step 6, "Cancel payment" in 3-dot menu is not translated to Spanish

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [x] Android: mWeb Chrome
- [ ] iOS: Native
- [x] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details>  

https://github.com/Expensify/App/assets/78819774/7caff2d3-22f2-4f13-8db0-609d72e4b299

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~018f27688bf279c909</li>
        <li>Upwork Job ID: 1738316307016527872</li>
        <li>Last Price Increase: 2023-12-22</li>
    </ul>
</details>

**Comment by Pujan92** [comment] 2023-12-22 17:41
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
Cancel payment not translated to spanish

### What is the root cause of that problem?
We have static string here which added in this [PR](https://github.com/Expensify/App/pull/32674)
https://github.com/Expensify/App/blob/b0e038f65e716d333ecce0437fc61a2e258ea7c0/src/components/MoneyReportHeader.js#L124

### What changes do you think we should make in order to solve the problem?
We need to use translation key instead.

**Comment by puneetlath** [comment] 2023-12-22 21:51
Not a deploy blocker but we should fix this. Going to make it a $125 issue as this is very simple.

**Comment by getusha** [comment] 2023-12-25 12:45
Since the issue is straightforward, let's proceed with @neonbhai's [proposal](https://github.com/Expensify/App/issues/33513#issuecomment-1867931567), as it was the first one.
🎀 👀 🎀 C+ Reviewed!

**Comment by mountiny** [comment] 2023-12-25 21:53
Reverting the original PR because it has caused numerous deploy blockers and the author is ooo

**Comment by marcaaron** [comment] 2023-12-26 19:16
Closing since related PR was reverted. cc @Gonals

**Closed** 2023-12-26 19:15 UTC
Labels: Reviewing, External, Engineering, Weekly, Help Wanted
