### ISSUE TITLE
[$250] Web - Endless loading appears clicking on https://staging. new.expensify.com/details in concierge 

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#10966] opened 2022-09-13 16:38 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Issue found when executing PR** https://github.com/Expensify/App/pull/10820 

## Action Performed:
1. Go to NewDot and login
2. Go to /details
3. Send message 'https://staging.new.expensify.com/details'
in any chat room and click on it

## Expected Result:
Details page opens

## Actual Result:
Endless loading appears

## Workaround:
Unknown

## Platform:

Where is this issue occurring?

- Web

**Version Number:** 1.2.0.0

**Reproducible in staging?:** Yes

**Reproducible in production?:** Yes

**Email or phone of affected tester (no customers):** any

**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Notes/Photos/Videos:** Any additional supporting documentation

https://user-images.githubusercontent.com/93399543/189958067-b85be243-bc68-4c54-bbf7-185e4175edd2.mp4

**Expensify/Expensify Issue URL:** 

**Issue reported by:** Applause - Internal Team

**Slack conversation:** 

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by francoisl** [comment] 2022-09-13 17:13
It looks like the `details` page expects a `login` param - e.g. https://staging.new.expensify.com/details?login=concierge%40expensify.com works as you would expect. 

https://github.com/Expensify/App/blob/9a98116600f697d920f594db3bc3ab9dec5d2d29/src/pages/DetailsPage.js#L31-L32

Doesn't look like a bug to me, I'll reassign to the triage team for a second opinion.

**Comment by jboniface** [comment] 2022-09-14 15:47
[job post](https://www.upwork.com/jobs/~01deff72939e30eb36)

**Comment by Santhosh-Sellavel** [comment] 2022-09-14 16:00
@Beamanator There might be an issue with deployment let's wait until the next deployment and check this out, please put it on hold for time being thanks!

**Comment by Beamanator** [comment] 2022-09-15 08:32
@Santhosh-Sellavel - on hold! What makes you think deployment got messed up by the way?

**Comment by Santhosh-Sellavel** [comment] 2022-09-15 13:18
@Beamanator Here is another regression that was due to deploy error https://github.com/Expensify/App/issues/10963

**Comment by mountiny** [comment] 2022-09-15 13:22
That is true, the problem with the deploy has been fixed so this can be closed out since this was reported by applause there is nobody to pay

**Comment by Santhosh-Sellavel** [comment] 2022-09-16 18:51
@Beamanator I checked this again I am able to reproduce this issue.

But this can not be found on testing on local, that's the reason we might have missed this while testing!

**Comment by mountiny** [comment] 2022-09-16 18:57
@Santhosh-Sellavel hmm, I still cannot repro on staging web. In no account. Do you have any screen recording or logs?

**Comment by Santhosh-Sellavel** [comment] 2022-09-16 19:09
We verified accessing the  'https://staging.new.expensify.com/details' directly was handled. As we are able to test this locally just by modifying the address bar.

Try sending `https://staging.new.expensify.com/details` as a message and click the link from chat!

But sending` localhost:8080/details` is not treated as a hyperlink, so we are unable to verify to test this!

**Comment by Santhosh-Sellavel** [comment] 2022-09-16 19:22
https://user-images.githubusercontent.com/85645967/190714178-3f795880-cc7a-4d1a-a408-556c7b8bd560.mov

@mountiny

**Comment by mountiny** [comment] 2022-09-16 20:56
Sorry guys, this is not a bug. Thanks for the proposals but this is not really a natural flow we would have in the app so the fact the modal shows is not a problem as it closes automatically and the App does not crash, which was the original problem.

**Comment by Beamanator** [comment] 2022-09-20 11:51
@mountiny just wondering are you saying the "details" modal automatically closes for you when you go to `https://staging.new.expensify.com/details` directly? What about when you type `https://staging.new.expensify.com/details` in a chat and click on it?

For some reason for me only the 2nd flow ^ is still broken on Staging

**Comment by mountiny** [comment] 2022-09-20 12:15
Chatted with @Beamanator and he pointed out the fact that infinite spinner appears after clicking the link from chat. This kinda violates one of the premises given in this PR https://github.com/Expensify/App/pull/10820, where we say:

> redirect to root page if login query not exist in /details deep link

At the same time, the link in concierge on web is not specifically deeplink, right? Nonetheless, lets fix this if we can haha

**Comment by mountiny** [comment] 2022-09-20 12:23
Thank you @aimane-chnaif What do you think of @aimane-chnaif proposal above 🙌

**Comment by Santhosh-Sellavel** [comment] 2022-09-20 12:40
Check out these comments

https://github.com/Expensify/App/issues/10966#issuecomment-1249698804

https://github.com/Expensify/App/issues/10966#issuecomment-1249712781

Let me know this should be treated as regression Or fixed separately.
Thanks!

@Beamanator

**Comment by Beamanator** [comment] 2022-09-20 12:52
@Santhosh-Sellavel I guess it makes sense to fix this separately, the crash was fixed in the other issue so now let's fix clicking the link here, thoughts?

**Comment by Santhosh-Sellavel** [comment] 2022-09-21 19:35
I am also on the side of handling it separately.

**Comment by Santhosh-Sellavel** [comment] 2022-09-21 19:38
Need some time to dig this more.

**Comment by Santhosh-Sellavel** [comment] 2022-09-26 18:44
Will look into it this week, no need to double until then thanks! @dylanexpensify

**Comment by dylanexpensify** [comment] 2022-09-29 08:18
Sounds good, any update @Santhosh-Sellavel ??

**Comment by Beamanator** [comment] 2022-10-03 09:21
Bump @Santhosh-Sellavel

**Comment by Santhosh-Sellavel** [comment] 2022-10-03 19:30
@Beamanator This issue is unable to reproduce, can we verify and close this? May be I should have checked sooner to reproduce this again.

**Comment by Beamanator** [comment] 2022-10-04 13:42
I also can't reproduce, thanks for the notice, both! Closing

**Closed by Beamanator** 2022-10-04 13:42 UTC
Labels: External, Engineering, Daily, Help Wanted
