### ISSUE TITLE
[$500] Web -  Admin can submit and approve their own report when "Prevent Self-Approval" is on

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#36425] opened 2024-02-13 17:01 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** v1.4.40-4
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** Applause - Internal Team
**Slack conversation:**

**Issue found when executing PR** https://github.com/Expensify/App/pull/34450

## Action Performed:
Precondition:
- Admin is in the Collect workspace.
- "Prevent Self-Approval" is enabled.
1. On OD, create a report and add an expense to it.
2. Copy the report ID n OD, and paste it after https://staging.new.expensify.com/r/
3. On ND, submit and approve the report.

## Expected Result:
Admin will be prevented from submitting and approving the report as indicated by this line " Looks like you're submitting to yourself. Approving your own reports is forbidden by your policy." in Next step message.

## Actual Result:
Admin is able to submit and approve their own report when "Prevent Self-Approval" is enabled.

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [x] Android: mWeb Chrome
- [x] iOS: Native
- [x] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

https://github.com/Expensify/App/assets/93399543/c7f8eac7-58cb-42fd-b4d4-6d600106f602

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~011beabd7ddef2a97c</li>
        <li>Upwork Job ID: 1757449822623985664</li>
        <li>Last Price Increase: 2024-02-20</li>
<li>Automatic offers: </li>
<ul>
<li>alitoshmatov | Reviewer | 0</li>
<li>barros001 | Contributor | 0</li>
</ul></li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @kevinksullivan</details>

**Comment by kbecciv** [comment] 2024-02-13 17:02
We think that this bug might be related  #wave7-collect-approvers
CC @RachCHopkins

**Comment by jeremy-croff** [comment] 2024-02-13 21:30
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
We are able to approve reports in newdot when we configured on old dot to now allow this.

### What is the root cause of that problem?
We are not using the logic
```isPreventSelfApprovalEnabled && isSelfApproval```  to decide whether or not to disable to approval action. We are using this condition however to decide whethhr or not to show the information that its not allowed.

### What changes do you think we should make in order to solve the problem?
We can use the condition that determines ```isPreventSelfApprovalEnabled && isSelfApproval``` to disable to approval of the report. The back end is catching this error however we should prevent the user action.

We can additionally decide to just remove the approval button as well if this condition is met.

The conditions that determine the rendering of the button is found here:
https://github.com/Expensify/App/blob/19e28491a92d2ea74b85b73b86aad1f2f3e06174/src/components/SettlementButton.tsx#L36

### What alternative solutions did you explore? (Optional)

**Comment by alitoshmatov** [comment] 2024-02-16 21:10
@jeremy-croff Thank you for your proposal. There is not much details in your proposal and you are only suggesting to disable approve button whereas in OP expected result is to prevent user from submitting proposal to themself when self approving is disabled.

**Comment by alitoshmatov** [comment] 2024-02-16 21:13
@barros001 Thank you for your proposal. Did you mean to say `isAllowedToSumitDraftExpenseReport` instead of `isAllowedToApproveDraftExpenseReport`? Other than that I do agree with your approach, but still we have to also disable approve button for cases where `prevent self approval` is disabled after submitting report.

**Comment by jeremy-croff** [comment] 2024-02-16 21:23
So it looks like I have the steps for approval, and @barros001 for submit. And we need a combination of both.

**Comment by alitoshmatov** [comment] 2024-02-21 06:00
We can go with @barros001 's [proposal](https://github.com/Expensify/App/issues/36425#issuecomment-1942724649)

@barros001 One note, can't we just not show approve button?

C+ reviewed 🎀 👀 🎀

**Comment by alitoshmatov** [comment] 2024-02-22 06:00
I was meaning whole button with dropdown. But let's see what @lakchote thinks about it

**Comment by lakchote** [comment] 2024-02-26 13:53
Couple notes

- it should be isAllowedToSu**b**mitDraftExpenseReport instead of `isAllowedToSumitDraftExpenseReport`
- I'm not a fan of hiding the whole `Approve` button with dropdown entirely. I'd prefer to make it disabled to inform the user the action is not possible, instead of making him wondering where did the button go.

Thanks @alitoshmatov for reviewing.
@barros001's proposal LGTM.

**Comment by lakchote** [comment] 2024-02-29 07:10
@barros001 when does the PR will be up do you think? Thanks!

**Comment by alitoshmatov** [comment] 2024-04-08 09:29
The PR went into production in 27th of march, only payment is left. 
https://github.com/Expensify/App/issues/38889 - This issue was also related. Not sure if we are going to treat it as regression and apply penalty here

**Comment by lakchote** [comment] 2024-04-18 15:16
I'd say it's not a regression and more of an edge case that wasn't properly handled.

Thoughts @kevinksullivan?

**Comment by alitoshmatov** [comment] 2024-05-01 05:19
@kevinksullivan Friendly bump

**Comment by lakchote** [comment] 2024-05-22 07:20
DMed @kevinksullivan to make sure this is not missed.

**Comment by kevinksullivan** [comment] 2024-05-22 15:25
Sorry for the delay, I missed this.

**Comment by kevinksullivan** [comment] 2024-05-22 15:29
had to create a new job @barros001 @alitoshmatov . Lmk when you accept

https://www.upwork.com/ab/applicants/1793302649633525760/job-details

**Comment by kevinksullivan** [comment] 2024-05-22 21:27
paid @barros001

**Comment by alitoshmatov** [comment] 2024-05-22 22:04
Accepted the offer

**Comment by alitoshmatov** [comment] 2024-06-02 19:35
@kevinksullivan Bump

**Comment by mallenexpensify** [comment] 2024-06-19 18:38
Contributor: @barros001 paid $500 via Upwork (by Kev, as [mentioned above](https://github.com/Expensify/App/issues/36425#issuecomment-2125782488)) 
Contributor+: @alitoshmatov paid $500 via Upwork  

This _looks_ like a bug we'd want a regression test for, do you agree @alitoshmatov ? IF so, please fill out the BZ checklist below. 

**BugZero Checklist:** The PR fixing this issue has been merged! The following checklist ([instructions](https://stackoverflow.com/c/expensify/questions/14574)) will need to be completed before the issue can be closed:

- [ ] [@] The PR that introduced the bug has been identified. Link to the PR:
- [ ] [@] The offending PR has been commented on, pointing out the bug it caused and why, so the author and reviewers can learn from the mistake. Link to comment:
- [ ] [@] A discussion in #expensify-bugs has been started about whether any other steps should be taken (e.g. updating the PR review checklist) in order to catch this type of bug sooner. Link to discussion:
- [ ] [@] Determine if we should create a regression test for this bug.
- [ ] [@] If we decide to create a regression test for the bug, please propose the [regression test](https://github.com/Expensify/App/blob/main/contributingGuides/REGRESSION_TEST_BEST_PRACTICES.md) steps to ensure the same bug will not reach production again.
- [ ] [@BZ] Link the GH issue for creating/updating the regression test once above steps have been agreed upon:

**Comment by alitoshmatov** [comment] 2024-06-23 19:53
- The PR that introduced the bug has been identified. Link to the PR: https://github.com/Expensify/App/pull/28998
- The offending PR has been commented on, pointing out the bug it caused and why, so the author and reviewers can learn from the mistake. Link to comment: https://github.com/Expensify/App/pull/28998/files#r1650175146
- A discussion in #expensify-bugs has been started about whether any other steps should be taken (e.g. updating the PR review checklist) in order to catch this type of bug sooner. Link to discussion: No need
- Determine if we should create a regression test for this bug. No need

**Comment by alitoshmatov** [comment] 2024-06-23 19:53
@mallenexpensify Completed the checklist

**Comment by mallenexpensify** [comment] 2024-06-24 23:53
Are we should we don't want a regression test for this? It was a bug that didn't come from an existing regression test. 
@alitoshmatov can you provide reasoning why you don't think we need?
@lakchote , what do you think? Here's the PR
- [Disable Submit/Approve buttons when self approving is disabled and user is trying to self approve](https://github.com/Expensify/App/pull/37348#top)

**Comment by kevinksullivan** [comment] 2024-06-26 15:52
Waiting for @alitoshmatov response here

**Comment by alitoshmatov** [comment] 2024-06-27 10:39
@mallenexpensify I think regression tests created in this https://github.com/Expensify/App/issues/28771 should be sufficient. 

> @mallenexpensify Yep, we'll have to create a new one. The test steps given in the PR description https://github.com/Expensify/App/pull/34450 look comprehensive enough to me. Let me know if you need any help with those.

Based on [this comment](https://github.com/Expensify/App/issues/28771#issuecomment-1956522868) I think existing regression test steps are the same as test steps in https://github.com/Expensify/App/pull/34450 which caught this issue as OP states:

> Issue found when executing PR https://github.com/Expensify/App/pull/34450

**Comment by mallenexpensify** [comment] 2024-06-28 01:27
Thanks @alitoshmatov , I agree, closing
TR GH is here - https://github.com/Expensify/Expensify/issues/372499

Section is likely this one (there are many)
<img width="671" alt="image" src="https://github.com/Expensify/App/assets/22508304/f1cf1266-2765-4f79-a927-dc45fb5d15f1">

**Closed by mallenexpensify** 2024-06-28 01:27 UTC
Labels: External, Daily, Bug
