### ISSUE TITLE
[$1000] Admin is removed when inviting a secondary login account of an account that is not member of a workspace

### ISSUE THREAD

**Issue by kavimuru** [Expensify/App#23667] opened 2023-07-26 17:11 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
Precondition: Account B should have a secondary login account C
1. Sign in with account A
2. Create a workspace
3. Click on 'Members' link > click on 'Invite' button
4. Invite secondary login account C of primary login account B
## Expected Result: 
* Primary login account B should successfully be invited
* Members list should display members
* Existing reports, settings page header, and other parts shouldn't break
## Actual Result: 
* Members list is not displaying members including the admin
* Existing reports, settings page header, and other parts break

## Workaround:
Can the user still use Expensify without this being fixed? Have you informed them of the workaround?

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [x] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 1.3.56-0
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/43996225/ee3a6269-c1cf-4288-bce2-58243260f47a

https://github.com/Expensify/App/assets/43996225/b88d6872-4a81-4575-a2c6-218ef1531963

**Expensify/Expensify Issue URL:**
**Issue reported by:** @natnael-guchima
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1690289171286869

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01a6a943c377abf44b</li>
        <li>Upwork Job ID: 1686495677974990848</li>
        <li>Last Price Increase: 2023-08-15</li>
    </ul>
</details>

**Comment by tjferriss** [comment] 2023-08-01 21:54
Reproduced.

**Comment by akamefi202** [comment] 2023-08-02 21:37
I think we need to update the backend first. When we add a member to the workspace, we receive account id of new member from backend and update "policyMembers_" onyx data with it. And that onyx data refers member list of the workspace.

![Untitled](https://github.com/Expensify/App/assets/53784473/e7bec287-73fd-45ee-b710-3a284c7ebebc)

But if we add a member using secondary login, the backend returns empty array instead. We should make sure the backend returns correct account id first. Then we would be able to find the problem in frontend.

**Comment by tjferriss** [comment] 2023-08-03 18:36
@akamefi202 would you want to bring this up as a [formal proposal](https://github.com/Expensify/App/blob/main/contributingGuides/PROPOSAL_TEMPLATE.md)

**Comment by akamefi202** [comment] 2023-08-03 19:22
@tjferriss Updated the comment.
https://github.com/Expensify/App/issues/23667#issuecomment-1662996391

**Comment by tjferriss** [comment] 2023-08-09 04:23
@allroundexperts can you take a look at @akamefi202 proposal?

**Comment by tjferriss** [comment] 2023-08-11 16:57
@allroundexperts no worries, I didn't see a previous comment, but I do see the proposal calls for back end changes.

@NikkiWines would you be able to take a look at this one?

**Comment by NikkiWines** [comment] 2023-08-14 21:10
Will try and take a look at this during the week!

**Comment by tjferriss** [comment] 2023-08-15 18:58
Thanks Nikki!

**Comment by mvtglobally** [comment] 2023-08-16 20:42
Issue not reproducible during KI retests. (First week)

**Comment by NikkiWines** [comment] 2023-08-17 18:40
Hmm, yeah echoing @mvtglobally's comment, this doesn't seem to be reproducible on dev anymore

https://github.com/Expensify/App/assets/16747822/e6c08adb-02f5-4ed8-8398-1f221a773988

@tjferriss can you reproduce this on your end?

**Comment by tjferriss** [comment] 2023-08-17 22:26
Agreed, I'm not able to reproduce anymore. I invited tj+109840@expensifail.com which is a secondary login to tj@expensifail.com and it worked as expected. So I'm going to close this for now.

<img width="391" alt="Screenshot 2023-08-17 at 15 25 44" src="https://github.com/Expensify/App/assets/8292562/dde9bc74-a7a7-444f-a36d-fd3afda1e0ff">

**Closed by tjferriss** 2023-08-17 22:26 UTC
Labels: External, Engineering, Daily, Help Wanted, Bug
