### ISSUE TITLE
[HOLD for payment 2023-07-20] [$1000] DEV: console error on report screen which has task

### ISSUE THREAD

**Issue by kavimuru** [Expensify/App#21496] opened 2023-06-24 15:16 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. go to any chat
2. click on + icon
3. select Assign task option
4. enter title and click on next button
5. click on Confirm task button which will navigates to task thread
6. go back to previous report screen which has task
7. reload page
## Expected Result: 
should not show console error
## Actual Result: 
shows console error (Function components cannot be given refs. Attempts to access this ref will fail. Did you mean to use React.forwardRef()?)
## Workaround:
Can the user still use Expensify without this being fixed? Have you informed them of the workaround?

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [x] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** DEV
**Reproducible in staging?:** n/a
**Reproducible in production?:** n/a
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/43996225/3d3c78ba-a2dd-4635-b610-21a159e379b7

**Expensify/Expensify Issue URL:**
**Issue reported by:** @gadhiyamanan 
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1686809664829689

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01376acc439f64b8c7</li>
        <li>Upwork Job ID: 1673718992058445824</li>
        <li>Last Price Increase: 2023-06-27</li>
    </ul>
</details>

**Comment by StevenKKC** [comment] 2023-06-25 08:46
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
Console error is displayed when open report screen which has task.

### What is the root cause of that problem?
Task is displayed using `TaskPreview` in report, and this component use `RenderHTML` for task assignee and task title.
https://github.com/Expensify/App/blob/820fa93ad1e799c12d8b639b98018b5350ea17af/src/components/ReportActionItem/TaskPreview.js#L62
https://github.com/Expensify/App/blob/820fa93ad1e799c12d8b639b98018b5350ea17af/src/components/ReportActionItem/TaskPreview.js#L85

`RenderHTML` uses `MentionUserRenderer` -> `Tooltip` -> `Hoverable` -> `TextLink` components for task assignee.

`Hoverable` uses `ref` for children in his `render` fucntion, but `TextLink` is a function component.
https://github.com/Expensify/App/blob/820fa93ad1e799c12d8b639b98018b5350ea17af/src/components/Hoverable/index.js#L80-L94
https://github.com/Expensify/App/blob/820fa93ad1e799c12d8b639b98018b5350ea17af/src/components/TextLink.js#L34
So console error is displayed.

### What changes do you think we should make in order to solve the problem?
We should change `export default TextLink;` in `TextLink` as below.
```
export default React.forwardRef((props, ref) => (
    <TextLink
        // eslint-disable-next-line react/jsx-props-no-spreading
        {...props}
        forwardedRef={ref}
    />
));
```

### What alternative solutions did you explore? (Optional)
None.

**Comment by joelbettner** [comment] 2023-06-26 20:42
@abekkala I am able to reproduce on dev:
<img width="1059" alt="image" src="https://github.com/Expensify/App/assets/13264774/1ee6eab3-8936-42d6-90ef-eb2ef35256d8">

**Comment by mananjadhav** [comment] 2023-06-27 15:58
I [checked](https://github.com/Expensify/App/issues/21496#issuecomment-1605947378) @StevenKKC’s proposal and it looks good.

To be safe I tested a few TextLinks if it affects their behavior.  

@joelbettner all yours

**Comment by abekkala** [comment] 2023-06-30 15:08
@joelbettner do you agree with @mananjadhav's suggestion to hire @StevenKKC based on their proposal?

**Comment by joelbettner** [comment] 2023-06-30 17:18
@abekkala @mananjadhav That proposal from @StevenKKC looks good to me.

**Comment by abekkala** [comment] 2023-06-30 17:27
@maddylewis Reassigning for sabbatical

___

### CURRENT STATUS:

- Issue reported by: @gadhiyamanan [$250]
- Assigned for Fix: @StevenKKC [$1000] +/- potential bonus/penalty
- C+: @mananjadhav [$1000] +/- potential bonus/penalty

Based on the new update, offers were already sent/created by Upwork 🎉

**Comment by StevenKKC** [comment] 2023-07-01 03:33
@mananjadhav @joelbettner [PR](https://github.com/Expensify/App/pull/22007) is ready for review.
And I'm not received an offer on my Upwork account.

**Comment by maddylewis** [comment] 2023-07-07 15:04
@joelbettner is in the process of reviewing - https://github.com/Expensify/App/pull/22007#issuecomment-1624416951

**Comment by StevenKKC** [comment] 2023-07-07 18:08
@mananjadhav @joelbettner Thanks for reviewing PR. Am I eligible for bonus?

**Comment by mananjadhav** [comment] 2023-07-19 17:25
We created `UserMentionRenderer` component deprecating in this [PR](https://github.com/Expensify/App/pull/18495). We added the `Tooltip` over `TextLink` and that should've shown the console error. Ideally this should've been handled during the Hoverable component creation itself.  Hence I can't attribute this to that PR.

Also I don't think we need a regression test for this one.

**Comment by mananjadhav** [comment] 2023-07-20 02:17
@maddylewis this is ready for payout along with the timeline bonus. I've raised my request on NewDot. Can you help with the payout for @StevenKKC ?

**Comment by maddylewis** [comment] 2023-07-21 17:35
payments:
- [ ] @StevenKKC - $1500 (contributor)
- [ ] @mananjadhav - $1500 (C+ - NewDot)
- [ ] [gadhiyamanan](https://github.com/gadhiyamanan) - $250 (reporting)

**Comment by maddylewis** [comment] 2023-07-21 17:44
everyone is paid 👍

**Closed by maddylewis** 2023-07-21 17:44 UTC
Labels: External, Engineering, Daily, Awaiting Payment, Bug

**Comment by anmurali** [comment] 2023-07-21 19:06
Approved 1500 to Manan based on https://github.com/Expensify/App/issues/21496#issuecomment-1646034443
