### ISSUE TITLE
[HOLD for payment 2024-01-03] Settings - Animation in Settings is not smooth: background comes first then the animation

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#31196] opened 2023-11-10 18:15 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.3.98-0
**Reproducible in staging?:** Y
**Reproducible in production?:** N
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** Applause - Internal Team
**Slack conversation:**

## Action Performed:
1. Navigate to staging.new.expensify.com
2. Refresh the page
3. Click Settings
4. Click on the section that will bring up animation like Workspaces, Preferences and Security

## Expected Result:
The animation will come out smoothly

## Actual Result:
The background color comes first, then followed by the animation

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [x] Android: mWeb Chrome
- [ ] iOS: Native
- [x] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details> 

https://github.com/Expensify/App/assets/78819774/695fe280-3d75-4f1e-8dff-c96bf506d8be

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01b4567a2bafc6c5c0</li>
        <li>Upwork Job ID: 1733080116631719936</li>
        <li>Last Price Increase: 2023-12-08</li>
    </ul>
</details>

**Comment by puneetlath** [comment] 2023-11-10 22:06
Asked @kosmydel to take a look in Slack as well.

**Comment by kosmydel** [comment] 2023-11-13 09:21
Hey, thanks for reporting it!

This issue is related to the migration of animation files from the app bundle to the assets. 
Animations are no longer stored in the application code (reducing the bundle size and TTI). Instead, they are loaded when they are needed. It results in a little delay in loading. It is especially visible on the web, as the assets (just like any other image) are fetched through the internet.

I pointed this out [here](https://github.com/Expensify/App/pull/29975#issuecomment-1798071978) before it was reviewed and merged.

In my opinion, it is not a regression, as this was expected to happen. If we want to fix it, we have to discuss how to handle it.

cc @roryabraham

**Comment by puneetlath** [comment] 2023-11-13 16:30
This is not a deploy blocker. Discussion options in this thread: https://expensify.slack.com/archives/C04878MDF34/p1699646294012999

**Comment by roryabraham** [comment] 2023-11-13 16:31
Chatting about this in slack [here](https://expensify.slack.com/archives/C04878MDF34/p1699646294012999) – for some reason we're always getting cache misses on `.lottie` assets in `s3/cloudfront`. I think we can continue to look into that but it should not be a deploy blocker. I tend to agree that this is expected behavior.

The other thing we could potentially do is preload lottie assets at some earlier time, but I think it would be smart to try and fix cloudfront / browser caching for lottie assets _before_ we investigate a more complex preloading solution

**Comment by roryabraham** [comment] 2023-11-14 01:37
Suggesting that we put this on HOLD and consolidate discussion in https://github.com/Expensify/App/issues/28160

**Comment by puneetlath** [comment] 2023-11-14 17:53
Works for me. Putting it on hold.

**Comment by puneetlath** [comment] 2023-11-21 18:21
Still on hold.

**Comment by puneetlath** [comment] 2023-12-06 17:11
I notice that this is still a thing, that the background comes first, then the animation. @roryabraham @kosmydel is there any way for us to potentially improve that? Or is that just the way it is?

**Comment by roryabraham** [comment] 2023-12-08 19:02
It sounds like the other piece is just setting up some caching headers for `.lottie` assets in Cloudflare. I think we need ring0 help for that, but the change seems pretty easy:

![Screenshot 2023-11-30 at 12 35 47](https://github.com/Expensify/App/assets/47436092/0138eb51-2c57-4a0f-86c1-d2ea664832a5)

**Comment by roryabraham** [comment] 2023-12-08 19:06
So just to clarify what I think the next steps here are:

1. @robertjchen can help with setting up caching headers for `.lottie` assets in our Cloudflare edge server thingy
1. @kosmydel will open a PR to configure prefetching of `.lottie` assets in our webpack config. Once that's ready @mollfpr will review and help test.

Thanks!

**Comment by kosmydel** [comment] 2023-12-11 08:40
Hey @roryabraham, thanks for the summarized steps! 

I want to make sure if we want to create a patch for the existing `FontPreloadPlugin` library ([like it was in the draft](https://github.com/Expensify/App/pull/32789/files)), or should I look for something else?
Since it is a simple change, I would lean towards creating a patch, as adding a new library might add some redundancy here.

---

**Important Note:** Prefetching without cache headers only applies to the initial loading of the animation. Subsequent "loads" will utilize cached headers, which haven't been established yet, implying that the animation will be loaded repeatedly.

**Comment by roryabraham** [comment] 2023-12-11 17:09
Understood about the separate utilities of preloading and caching 👍

Yes, I agree that a patch will be fine to get this feature out. Do you think the contents of the patch are too specific to make an upstream PR?

**Comment by roryabraham** [comment] 2023-12-11 17:16
Removing @puneetlath as the issue owner as there are a few people with TODOs here, listed [above](https://github.com/Expensify/App/issues/31196#issuecomment-1847682290)

**Comment by kosmydel** [comment] 2023-12-12 10:42
> Do you think the contents of the patch are too specific to make an upstream PR?

@roryabraham  We might consider making the upstream more general, with config enabling the prefetching of other assets. However, the name of the library suggests that it's for Fonts only (`webpack-font-preload-plugin
`), so they might want to keep it as simple as it is.

---

Since this PR is not big, I'm going to prepare it for a review.

**Comment by robertjchen** [comment] 2023-12-12 21:05
Having reviewed our caching on the server-side, it appears that the settings currently in place are correct and already have the intended effect 👍

**Comment by kosmydel** [comment] 2023-12-13 07:56
> Having reviewed our caching on the server-side, it appears that the settings currently in place are correct and already have the intended effect 👍

Good to know! It works much better now!


> @kosmydel It looks like https://www.npmjs.com/package/preload-webpack-plugin hasn't been published for 6 years, so I doubt it's compatible with Webpack 5. So let's continue with the patch in the library we're already using

@roryabraham Oh, I haven't linked it. I meant a fork of this plugin, maintained by vuejs: [`@vue/preload-webpack-plugin`](https://github.com/vuejs/preload-webpack-plugin) (it has >350k weekly downloads). I quickly tested it yesterday, and [it worked](https://github.com/Expensify/App/commit/0cff94ca05364df5fb2058db02f5d7cb5ddb657d) with our current version of the Webpack.

Please let me know if this changes anything.

**Comment by kosmydel** [comment] 2023-12-15 12:57
I've made the PR with the patch ready for review. Please let me know if we change our mind and want to use the other library.

**Comment by roryabraham** [comment] 2023-12-16 23:49
Oh, `@vue/preload-webpack-plugin` looks good. Sorry for the confusion

**Comment by roryabraham** [comment] 2023-12-20 20:18
Left some comments on the PR

**Comment by puneetlath** [comment] 2024-01-02 18:37
Looks like we don't need any payments here and I don't think a regression test makes sense for this either, so I'm going to go ahead and close this out. Thanks y'all!

**Closed by puneetlath** 2024-01-02 18:37 UTC
Labels: Engineering, Daily, Internal, Awaiting Payment, ring0, Bug
