### ISSUE TITLE
The live formatting of indentation works different than the actual final format

### ISSUE THREAD

**Issue by m-natarajan** [Expensify/App#52318] opened 2024-11-11 16:37 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 9.0.59-3
**Reproducible in staging?:** Yes
**Reproducible in production?:** Yes
**If this was caught on HybridApp, is this reproducible on New Expensify Standalone?:**
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** @quinthar 
**Slack conversation** (hyperlinked to channel name): [ts_external_expensify_bugs](https://expensify-ts.slack.com/archives/C049HHMV9SM/p1731123693302669)

## Action Performed:
1. Navigate to any chat
2. Compose a message
3. Compose a message with indentation (>)
4. Compose another message with double indentation (>>)
5. Send the message

## Expected Result:
Message composed with double indentation formatted correctly
## Actual Result:
Message composed with double indentation is not formatted correctly, Requires space between >>
## Workaround:
Unknown
## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Standalone
- [ ] Android: HybridApp
- [ ] Android: mWeb Chrome
- [ ] iOS: Standalone
- [ ] iOS: HybridApp
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

<details>
  <summary>Add any screenshot/video evidence</summary>

  
</details>

![image (12)](https://github.com/user-attachments/assets/91741a96-e87d-415d-abd9-f6d55785877c)

![image (13)](https://github.com/user-attachments/assets/3534e00a-30e0-4de6-b31d-b8ec50a7c84d)

![Snip - (5) New Expensify - Google Chrome](https://github.com/user-attachments/assets/5d655dce-c8cb-480b-bcde-fb95e2adf92a)

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by tomekzaw** [comment] 2024-11-11 17:25
Looks like duplicate of https://github.com/Expensify/App/issues/45154

**Comment by zanyrenney** [comment] 2024-11-12 14:59
https://expensify.slack.com/archives/C049HHMV9SM/p1731423572626789

**Comment by zanyrenney** [comment] 2024-11-13 11:49
Didn't hear back on my thread, bumping.

**Comment by zanyrenney** [comment] 2024-11-13 18:46
Chatted about this here and seeing as it is finite and easy to fix, even though it doesn't exactly align with a cohort, let's get it fixed. There has been a bunch of prior work on it in this issue so I think reopening the original, rather than tackling here makes the most sense.

**Closed by zanyrenney** 2024-11-13 18:46 UTC
Labels: Daily, Bug
