### ISSUE TITLE
[Hold for #37435][$500] Scan - There is no link to download a corrupted file & unable to remove RBR

### ISSUE THREAD

**Issue by izarutskaya** [Expensify/App#39379] opened 2024-04-01 21:12 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** v1.4.58-4
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**If this was caught during regression testing, add the test name, ID and link from TestRail:** https://expensify.testrail.io/index.php?/tests/view/4465016
**Email or phone of affected tester (no customers):** natnael.expensify+3@gmail.com
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Issue reported by:** Applause-Internal team

## Action Performed:
Precondition: There should be no unsettled IOU in workspace chat
1. Navigate to a workspace chat
2. Make an IOU request using a corrupted file
3. Wait for the request to fail
4. Navigate to IOU details report page
5. Click on 'X' icon on the error message

## Expected Result:
* There should be a 'download the file' link
* And GBR should be removed from LHN & IOU preview component when clearing the error message

## Actual Result:
* There is no 'download the file' link
* And GBR is not removed from LHN & IOU preview component when clearing the error message

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

https://github.com/Expensify/App/assets/115492554/17933c08-f81b-48a7-9573-781ac779b18b

<img width="444" alt="Bug6434450_1711984534389!The_Link_Should_Be_Like_This" src="https://github.com/Expensify/App/assets/115492554/e905d625-c2ca-4609-b410-8210e13d49c6">

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01ba7035a81d656f19</li>
        <li>Upwork Job ID: 1775355332030312448</li>
        <li>Last Price Increase: 2024-04-10</li>
    </ul>
</details>

**Comment by nkdengineer** [comment] 2024-04-03 04:33
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
There is no 'download the file' link
And GBR is not removed from LHN & IOU preview component when clearing the error message

### What is the root cause of that problem?
When there's a receipt error, the receipt error will be on the `parentReportAction` of the `transaction`, so it will show only in the IOU report, but not in the money request view.

Now we've introduced the single transaction view, in case of 1 money request, there'll be no IOU report, so the receipt error and prompt to download the file will never show.

### What changes do you think we should make in order to solve the problem?

1. In [here](https://github.com/Expensify/App/blob/879378ff68dc026c1b4ba6af30b70051b99c6d35/src/components/ReportActionItem/MoneyRequestView.tsx#L257), get the receipt error from the `parentReportAction`, if there is, we'll add to current error list to show
```
const receiptErrorKey = Object.keys(parentReportAction?.errors ?? {}).find(key => isReceiptError(parentReportAction?.errors?.[key] ?? {}));

let errors = transaction?.errors ?? {};
if (receiptErrorKey) {
    errors = {
        ...errors,
        [receiptErrorKey]: parentReportAction?.errors?.[receiptErrorKey]
    }
}
```
2. In [here](https://github.com/Expensify/App/blob/879378ff68dc026c1b4ba6af30b70051b99c6d35/src/components/ReportActionItem/MoneyRequestView.tsx#L266), use that `errors`
```
errors={errors}
```
3. In [here](https://github.com/Expensify/App/blob/879378ff68dc026c1b4ba6af30b70051b99c6d35/src/components/ReportActionItem/MoneyRequestView.tsx#L272), add logic to clear the receipt error and go back, if the `receiptErrorKey` exists
```
if (receiptErrorKey) {
    ReportActions.clearAllRelatedReportActionErrors(report.parentReportID ?? '', parentReportAction, receiptErrorKey);
    Navigation.goBack(ROUTES.REPORT_WITH_ID.getRoute(report.parentReportID ?? ''));
}
```

### What alternative solutions did you explore? (Optional)
I also see another issue where after reloading, the Blob file download won't work because the Blob becomes invalid already. This is likely out of scope, but it can be fixed by checking the Blob validity first (via `fetch` for example), and only show the CTA to `Download the file` if the Blob is valid, otherwise just show an error message.

**Comment by kadiealexander** [comment] 2024-04-07 22:51
@eVoloshchak thoughts?

**Comment by eVoloshchak** [comment] 2024-04-09 22:44
@ZhenjaHorbach's [proposal](https://github.com/Expensify/App/issues/39379#issuecomment-2030728788) looks good to me!
> Here we use errors from current and parent reports and after pressing if we have a parent error we delete them (But clarification is required here what is more priority error )

We should prioritize errors from the current report, it's the one user is interacting with

> Also I'm not sure about the position of X icon

That doesn't look right, good catch, let's fix it too

🎀👀🎀 C+ reviewed!

**Comment by nkdengineer** [comment] 2024-04-10 06:57
@eVoloshchak What's your feedback on [my proposal](https://github.com/Expensify/App/issues/39379#issuecomment-2033512163)?

Just FYI the selected proposal doesn't work in my testing, does it work for you when you test it?

**Comment by thienlnam** [comment] 2024-04-10 17:42
From what @paultsimura mentioned, it seems like we ended up handling not being able to upload corrupt files with the [proposal](https://github.com/Expensify/App/issues/37435#issuecomment-1974159681) over there. I'll go ahead and hold this for that

**Comment by kadiealexander** [comment] 2024-04-15 04:40
On hold!

**Comment by kadiealexander** [comment] 2024-04-24 05:57
Still on hold!

**Comment by kadiealexander** [comment] 2024-05-03 05:59
Same as above.

**Comment by eVoloshchak** [comment] 2024-05-13 15:00
https://github.com/Expensify/App/issues/37435 is done! 
This issue isn't reproducible, since you cannot upload a corrupted file anymore


https://github.com/Expensify/App/assets/9059945/745063a8-020a-42c9-90dc-4912e7a03114

**Closed** 2024-05-13 19:34 UTC
Labels: External, Weekly, Help Wanted, Bug
