### ISSUE TITLE
[$250] Distance rate - Unable to proceed with empty name via Enter key, while it works with green CTA

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#40945] opened 2024-04-24 22:01 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.65-5
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**If this was caught during regression testing, add the test name, ID and link from TestRail:** N/A
**Issue reported by:** Applause - Internal Team

## Action Performed:
1. Go to staging.new.expensify.com
2. Go to Collect workspace settings
3. Go to Distance rates
4. Click Add rate
5. Click Name
6. Hit Enter without entering the name
7. Return to previous page

## Expected Result:
In Step 6, Enter key should save the empty name (because it works by clicking on the Save button)

## Actual Result:
In Step 6, Enter key does not save the empty name
When returning to previous page in Step 7, error appears below the empty fields, which means Enter key is working elsewhere instead

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details> 

https://github.com/Expensify/App/assets/78819774/a2d6b58f-378e-46cc-ad84-c0ca8a1db7d1

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~018c1c78753474f238</li>
        <li>Upwork Job ID: 1785417584710262784</li>
        <li>Last Price Increase: 2024-04-30</li>
<li>Automatic offers: </li>
<ul>
<li>akinwale | Reviewer | 0</li>
<li>abzokhattab | Contributor | 0</li>
</ul></li>
    </ul>
</details>

**Comment by lanitochka17** [comment] 2024-04-24 22:02
@kevinksullivan  FYI I haven't added the External label as I wasn't 100% sure about this issue. Please take a look and add the label if you agree it's a bug and can be handled by external contributors

**Comment by abzokhattab** [comment] 2024-04-24 22:07
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
Unable to proceed with empty name via Enter key
### What is the root cause of that problem?
 saving by clicking on enter is disable here: 

https://github.com/Expensify/App/blob/7f2b5ddbc721f95ddde9c20f2ad2113410d0d296/src/pages/workspace/taxes/WorkspaceCreateTaxPage.tsx#L87
### What changes do you think we should make in order to solve the problem?

we need to remove it to enable saving the new tax with the `Enter` key

**Comment by abzokhattab** [comment] 2024-04-25 02:25
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
Unable to proceed with empty name via Enter key in Distance rate modal
### What is the root cause of that problem?



The problem originates from how the Enter key event is managed across multiple interactive components within the `Create Tax` page setup.

Here's what's happening:
- The page uses a `FormProvider` component configured with [disablePressOnEnter={false}](https://github.com/Expensify/App/blob/7f2b5ddbc721f95ddde9c20f2ad2113410d0d296/src/pages/workspace/taxes/WorkspaceCreateTaxPage.tsx#L87), indicating that pressing the Enter key will submit the form.
- within the `FormProvider` children, the  `TextPicker` is used as an `InputComponent`.
- When the `TextPicker` is opened, it opens a modal that includes text input and a save button, which also has the [pressOnEnter enabled](https://github.com/Expensify/App/blob/bda7696cd1549bbbdd2860851ede5bce659fe1fb/src/components/TextPicker/TextSelectorModal.tsx#L51).

The core of the issue is that the `Enter` key press is activated in both the main form and the children modals, so when a user is in the `TextPicker` modal and presses `Enter`, `FormAlertWithSubmitButton` of the main will execute the `onPress` not the Text selector save button



This overlap in how the Enter key is handled between nested components causes confusion and incorrect behavior.





### What changes do you think we should make in order to solve the problem?

we can use the `enterKeyEventListenerPriority` to assign the enter key event priority inside the `FormAlertWithSubmitButton` and set it to `1` (lower priority) so that in such cases the child component submit button will have a  higher priority 

- to achieve that we need to add the `enterKeyEventListenerPriority` as new prop with a default value of `0` inside the  [FormAlertWithSubmitButton](https://github.com/Expensify/App/blob/46ea41a84693311f0f41e98cdf2dd4fa643f00e2/src/components/FormAlertWithSubmitButton.tsx#L59):
```js
    enterKeyEventListenerPriority = 0,
```
- then this value should be passed [here](https://github.com/Expensify/App/blob/46ea41a84693311f0f41e98cdf2dd4fa643f00e2/src/components/FormAlertWithSubmitButton.tsx#L103-L115):

```js
enterKeyEventListenerPriority={enterKeyEventListenerPriority}
```
- finally we need to set the `enterKeyEventListenerPriority` to `1` inside the `FormAlertWithSubmitButton` component call in the [FormWrapper](https://github.com/Expensify/App/blob/aa4301fc6ee8d56377a05b792269aef1b3ea1067/src/components/Form/FormWrapper.tsx#L109-L121): 
```js
enterKeyEventListenerPriority={1}
```

**Comment by kevinksullivan** [comment] 2024-04-30 21:14
Hm it's only for a brand new field but I was able to reproduce.

**Comment by kevinksullivan** [comment] 2024-04-30 21:14
Going to add to Collect wave and make external, but I'd consider this a low priority.

**Comment by akinwale** [comment] 2024-05-03 04:25
@abzokhattab's [proposal](https://github.com/Expensify/App/issues/40945#issuecomment-2076205336) makes sense here.

🎀👀🎀 C+ reviewed.

**Comment by akinwale** [comment] 2024-05-30 03:45
This was deployed to production on [2023-05-23](https://github.com/Expensify/App/pull/41678#issuecomment-2125962210) which makes payment due 2023-05-30.

cc @kevinksullivan

**Comment by blimpich** [comment] 2024-07-12 19:13
Closing, if this is wrong then please feel free to ping me in Slack.

**Closed by blimpich** 2024-07-12 19:13 UTC
Labels: Reviewing, External, Monthly, Bug
