### ISSUE TITLE
[HELD #44514] [$250] Expense chat flashes twice when navigating back from a transaction thread

### ISSUE THREAD

**Issue by m-natarajan** [Expensify/App#45386] opened 2024-07-15 01:55 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** v9.0.6-3
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** @youssef-lr 
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1720889593578589

## Action Performed:
1. Open app
2. Go to any expense report which has receipt
3. Tap on the expense to view the details in the thread
4. Tap back twice to go to report
## Expected Result:
Chat shouldn't flash twice
## Actual Result:
Chat flashes twice
## Workaround:
unknown
## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [x] iOS: Native
- [ ] iOS: mWeb Safari
- [ ] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

https://github.com/user-attachments/assets/9b4cb6c9-1ee9-475a-a095-f370b20d168d

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01422eed8a9c7e5eeb</li>
        <li>Upwork Job ID: 1816625563467221555</li>
        <li>Last Price Increase: 2024-08-23</li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @allgandalf</details>

**Comment by kevinksullivan** [comment] 2024-07-26 00:04
Confirmed I am seeing something similar. I don't think my flashing is occurring twice, but same issue in general. 


https://github.com/user-attachments/assets/674de61d-8f21-405e-9291-ad469fdb1cf4

**Comment by kirillzyusko** [comment] 2024-07-26 11:42
@allgandalf yeah, probably - maybe it's because of the `react-freeze` 🥶 ❄️

**Comment by kevinksullivan** [comment] 2024-08-09 23:42
updated OP

**Comment by mvtglobally** [comment] 2024-08-23 12:00
Issue not reproducible during KI retests. (First week)

**Comment by kevinksullivan** [comment] 2024-08-24 19:47
closing as it's no longer reproducible.

**Closed by kevinksullivan** 2024-08-24 19:47 UTC
Labels: External, Weekly, Help Wanted, Overdue, Bug
