### ISSUE TITLE
[$500] Chat - Profile pic is not displayed for non communicated existing report in chat area

### ISSUE THREAD

**Issue by kavimuru** [Expensify/App#35378] opened 2024-01-30 11:00 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.33-0
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** Applause internal team
**Slack conversation:**

## Action Performed:
1. Open the app and login with gmail account
2. Open search
3. Search for user which already exists on app, has a profile pic but current logged in user has no conversation history with it (should be gmail account)
4. Click on the result
5. Observe that app displays profile pic in header but not in chat area

## Expected Result:
App should either display profile pic in both chat area and header or should not display profile pic in either places

## Actual Result:
App displays profile pic in header but does not display profile pic in chat area

## Workaround:
unknown
## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

https://github.com/Expensify/App/assets/43996225/50254b4b-4ffc-40be-9629-0efa10d0a36c

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~017ddf238b8d0fa663</li>
        <li>Upwork Job ID: 1752285750358851584</li>
        <li>Last Price Increase: 2024-02-13</li>
    </ul>
</details>

**Comment by bernhardoj** [comment] 2024-01-30 11:18
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
Profile pic in chat area doesn't show the custom avatar when starting a new chat with a new user.

### What is the root cause of that problem?
When we start a new chat, the LHN and header avatar is updated after we receive the personal detail data, but not for the avatar in the chat area and that's because we memoize the component but didn't consider the personal details data.
https://github.com/Expensify/App/blob/aaa658fed7af4696e463cc80d93fd45054a4e889/src/pages/home/report/ReportActionItemCreated.tsx#L107-L119

So, the component isn't updated when the personal detail is updated.

### What changes do you think we should make in order to solve the problem?

Add check for personal details too.
```
_.isEqual(prevProps.personalDetails, nextProps.personalDetails)
```

**Comment by ikevin127** [comment] 2024-01-30 12:26
Dupe, mentioned here: https://github.com/Expensify/App/issues/35123
I posted the same proposal (rca, main solution) there as the one posted above here.

**Comment by s77rt** [comment] 2024-01-30 17:37
@ikevin127 Looks you reported a new (similar) bug. I think we can handle that there.

cc @sonialiap We can close this

**Comment by ikevin127** [comment] 2024-02-02 11:49
I can confirm that both issues are solved - not reproducible aymore 🚀
Must've been the big PR merged recently.

<details>
<summary>MacOS: mWeb Chrome</summary>

https://github.com/Expensify/App/assets/56457735/e1933c1b-abb3-48bb-99d7-24ff70648c70

</details>

cc @sonialiap @s77rt

**Comment by s77rt** [comment] 2024-02-02 18:22
We can close this then

**Comment by s77rt** [comment] 2024-02-05 14:49
To be closed

**Comment by s77rt** [comment] 2024-02-07 17:36
@sonialiap ^

**Comment by s77rt** [comment] 2024-02-12 19:29
To be closed

**Closed** 2024-02-15 21:24 UTC
Labels: External, Daily, Help Wanted, Overdue, Bug
