### ISSUE TITLE
[PAY TALHA] [HOLD for payment 2023-09-27] [$1000] ANDROID CHROME - Split Bill: LHN does not close if clicking on the Workspaces link

### ISSUE THREAD

**Issue by kavimuru** [Expensify/App#23810] opened 2023-07-28 17:15 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Go to https://help.expensify.com/articles/playbooks/Expensify-Chat-Playbook-for-Conferences on mobile device.
2. Open LHN and click on any step.
3. Notice the LHN closes and page scrolls down to relevant section.
4. Now go to https://help.expensify.com/hubs/split-bills.
5. Open LHN and click on Workspaces.
6. Notice the LHN does not close and nothing happens.
## Expected Result: 
In case of https://help.expensify.com/hubs/split-bill, clicking on links in the LHN which points to some section on the same page, the LHN should close and the screen should be scrolled down to relevant section.
## Actual Result: 
In case of https://help.expensify.com/hubs/split-bill, clicking on links in the LHN which points to some section on the same page, the LHN did not close.

Note: This seems to occur on the Workspaces link (the other 3 links seem fine).

## Workaround:
Can the user still use Expensify without this being fixed? Have you informed them of the workaround?

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [x] Android / Chrome
- [ ] iOS / native
- [x] iOS / Safari
- [ ] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 1.3.47-2
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/43996225/887fc734-4577-4317-a9b3-2d1318d247c2

https://github.com/Expensify/App/assets/43996225/a6ccfad3-b76d-40d3-938a-8062b00f0263

**Expensify/Expensify Issue URL:**
**Issue reported by:** @Talha345
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1690460581911079

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01b88583567474c0d1</li>
        <li>Upwork Job ID: 1685897339918934016</li>
        <li>Last Price Increase: 2023-09-11</li>
<li>Automatic offers: </li>
<ul>
<li>abdulrahuman5196 | Reviewer | 26631441</li>
<li>Talha345 | Contributor | 26631442</li>
<li>Talha345 | Reporter | 26631443</li>
</ul></li>
    </ul>
</details>

**Comment by kavimuru** [comment] 2023-07-28 17:15
## Proposal from contributor
### Please re-state the problem that we are trying to solve in this issue.
In help docs,the LHN does not close when clicking on some link that points to some section on the same page.This issue is only present on https://help.expensify.com/hubs/split-bill while other pages like https://help.expensify.com/articles/playbooks/Expensify-Chat-Playbook-for-Conferences do not have this issue.
### What is the root cause of that problem?
The RC is that there is no implementation to take care of this issue on this page.The issue does not exist on other pages because the same page links in the LHN on other pages are populated using the following [code](https://github.com/Expensify/App/blob/main/docs/assets/js/main.js#L81-L118).  [Here](https://github.com/Expensify/App/blob/main/docs/assets/js/main.js#L114-L116) we can clearly see that toggleHeaderMenu function is called whenever a link is clicked which was populated using [tocbot](https://tscanlin.github.io/tocbot/).
### What changes do you think we should make in order to solve the problem?
There are 2 solutions to fix this issue:
1. We implement a generic JS to take care of all such links in the help docs.That can be done as follows:
function isSamePageScrollLink(link) {
        const href = link.getAttribute("href");
        if (href.startsWith("#") && !!document.getElementById(href.slice(1))) {
            toggleHeaderMenu();
        }
    }

    const links = document.querySelectorAll("a.link");


    for (const link of links) {
        link.addEventListener('click', (event) => {
            isSamePageScrollLink(link);
        });
    }
Furthermore, this would require to remove the toggleHeaderMenu method call in the TocBot onclick event [here](https://github.com/Expensify/App/blob/main/docs/assets/js/main.js#L114-L116). This way we will have a generic code that deals with all such links in the entire help docs.
2. The second solution would be to just implement the links on https://help.expensify.com/hubs/split-bills using Tocbot but this does not make much sense imo because we can see that there are sublinks below 'Paying Friends' and 'Workspaces' links which are not actually links to the same page and redirect to some other page and therefore are not necessarily TOC.
### What alternative solutions did you explore? (Optional)
N/A (edited) 
tscanlin.github.io
[Tocbot](https://tscanlin.github.io/tocbot/)
Tocbot - Generate a table of contents based on the heading structure of an html document

**Comment by Talha345** [comment] 2023-07-28 17:29
Note: This is the same proposal as above, just adding markdown because QA member posted the proposal and the markdown was broken.

## Proposal
### Please re-state the problem that we are trying to solve in this issue.
In help docs,the LHN does not close when clicking on some link that points to some section on the same page.This issue is only present on https://help.expensify.com/hubs/split-bills while other pages like https://help.expensify.com/articles/playbooks/Expensify-Chat-Playbook-for-Conferences do not have this issue.

### What is the root cause of that problem?
The RC is that there is no implementation to take care of this issue on this page.The issue does not exist on other pages because the same page links in the LHN on other pages are populated using the following [code](https://github.com/Expensify/App/blob/main/docs/assets/js/main.js#L81-L118).  [Here](https://github.com/Expensify/App/blob/main/docs/assets/js/main.js#L114-L116) we can clearly see that toggleHeaderMenu function is called whenever a link is clicked which was populated using [tocbot](https://tscanlin.github.io/tocbot/).
### What changes do you think we should make in order to solve the problem?
There are 2 solutions to fix this issue:
1. We implement a generic JS to take care of all such links in the help docs.That can be done as follows:
```

function isSamePageScrollLink(link) {
        const href = link.getAttribute("href");
        if (href.startsWith("#") && !!document.getElementById(href.slice(1))) {
            toggleHeaderMenu();
        }
    }

    const links = document.querySelectorAll("a.link");


    for (const link of links) {
        link.addEventListener('click', (event) => {
            isSamePageScrollLink(link);
        });
    }
```

Furthermore, this would require to remove the `toggleHeaderMenu` method call in the TocBot onclick event [here](https://github.com/Expensify/App/blob/main/docs/assets/js/main.js#L114-L116). This way we will have a generic code that deals with all such links in the entire help docs.

2. The second solution would be to just implement the links on https://help.expensify.com/hubs/split-bills using Tocbot but this does not make much sense imo because we can see that there are sublinks below 'Paying Friends' and 'Workspaces' links are not actually links to the same page and redirect to some other page and therefore are not necessarily TOC.

### What alternative solutions did you explore? (Optional)

N/A

**Comment by kadiealexander** [comment] 2023-07-31 04:07
Swapping with JLi (we have an agreement to swap android/iOS issues)

**Comment by jliexpensify** [comment] 2023-07-31 06:16
I can verify this is a bug, but only for the Workspaces link. I would encourage more testing though, this is what I'm seeing on a Pixel 3a.

**Comment by Talha345** [comment] 2023-07-31 08:49
> 

@jliexpensify This bug exists only for Paying Friends and Workspaces links because both of these links have href attributes pointing to the same page.

**Comment by abdulrahuman5196** [comment] 2023-07-31 11:57
Reviewing today

**Comment by Talha345** [comment] 2023-08-01 16:19
@abdulrahuman5196 did you get a chance to review this?

**Comment by jliexpensify** [comment] 2023-08-02 00:01
@Talha345 thanks for the context - just as an FYI, the GH's are original created by the QA team based off the reporter's findings. So if it's also an iOS problem, I'd encourage you to add that in your initial report so it can be recorded.

**Comment by abdulrahuman5196** [comment] 2023-08-06 16:02
@jliexpensify Are we actually fine to report and to work on the help pages? Asking this because, I haven't personally seen issues raised on help pages. I could be wrong as well, but wanted to confirm

**Comment by Talha345** [comment] 2023-08-06 16:05
> s raised on help pages. I could b

@abdulrahuman5196 The code base for the help docs is in the same repository and I have actually worked on an issue within the help docs before too.Here is the link for that issue: https://github.com/Expensify/App/issues/22014

**Comment by jliexpensify** [comment] 2023-08-07 01:25
Yep @abdulrahuman5196 I'm pretty sure we can hire Contributors to work on the Help pages. I would say find a proposal that works and we'll get an Engineer assigned, and they can have the final say!

**Comment by jliexpensify** [comment] 2023-08-08 02:30
@abdulrahuman5196 how's @Talha345 's proposal looking?

**Comment by Talha345** [comment] 2023-08-08 15:39
Hi @abdulrahuman5196,do you have any update as this is a pretty straightforward task in my opinion?

**Comment by jliexpensify** [comment] 2023-08-11 11:26
Bump @abdulrahuman5196 please review the proposal, thanks!

**Comment by abdulrahuman5196** [comment] 2023-08-13 10:27
Reviewing now

**Comment by abdulrahuman5196** [comment] 2023-08-13 11:09
On @Talha345 's proposal here https://github.com/Expensify/App/issues/23810#issuecomment-1656068129 I am not able to fully understand the proposal.

>The issue does not exist on other pages because the same page links in the LHN on other pages are populated using the following [code](https://github.com/Expensify/App/blob/main/docs/assets/js/main.js#L81-L118). [Here](https://github.com/Expensify/App/blob/main/docs/assets/js/main.js#L114-L116) we can clearly see that toggleHeaderMenu function is called whenever a link is clicked which was populated using [tocbot](https://tscanlin.github.io/tocbot/).

What does this mean? Do we say that `toggleHeaderMenu` is not properly working or we are saying it should have never called or any other. I am not able to understand this clearly.

>The second solution would be to just implement the links on https://help.expensify.com/hubs/split-bills using Tocbot 

What do you mean by links here? Could you share references of those?

>We implement a generic JS to take care of all such links in the help docs.That can be done as follows:

Where are we going to add the mentioned code? And how is that impacting? 


@Talha345 Could you add more detailed information on the proposal?

**Comment by Talha345** [comment] 2023-08-13 12:12
Hi @abdulrahuman5196 , [Proposal](https://github.com/Expensify/App/issues/23810#issuecomment-1656068129) updated.

I think you did not understand my proposal clearly because the links to the code in my proposal had deviated because new code was added in the code base and the line numbers were not same anymore.I have updated those too.Let me know if you have any further questions.

**Comment by jliexpensify** [comment] 2023-08-16 01:32
Bumop @abdulrahuman5196 for review!

**Comment by getusha** [comment] 2023-08-16 14:01
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
LHN does not close if clicking on workspaces link.
### What is the root cause of that problem?

The links don't have any event listeners to close the LHN when clicked, **which is the better user experience**. This issue happens when users go to different parts of **the same page** without actually changing the whole page.

For example, from https://help.expensify.com/hubs/split-bills to https://help.expensify.com/hubs/split-bills#workspaces Here, the page doesn't fully change, it just moves to a specific section on the page.

When the page reloads, left-hand navigation closes. But in the situation mentioned above, where there's no complete page reload, this doesn't happen.

### What changes do you think we should make in order to solve the problem?


We need to invoke the `toggleHeaderMenu` function when the `hashchange` event occurs. This event is triggered when there's a change in the fragment identifier of the URL, which is the portion of the URL that starts with the `#` symbol. which is our current case. You can find additional information on this event [here](https://developer.mozilla.org/en-US/docs/Web/API/Window/hashchange_event).

We will add
``` js
window.addEventListener('hashchange', toggleHeaderMenu);
// or
window.onhashchange = toggleHeaderMenu;
```

below here: https://github.com/Expensify/App/blob/7f13cdd9f5ade3aed50827084aa49b5e3a6496e1/docs/assets/js/main.js#L204


https://github.com/Expensify/App/assets/75031127/331be74d-67be-4bf6-9cd8-47707e8cce19

### What alternative solutions did you explore? (Optional)
N/A

cc @abdulrahuman5196

**Comment by jliexpensify** [comment] 2023-08-22 05:53
Bump @abdulrahuman5196 for reviews!

**Comment by Talha345** [comment] 2023-08-22 13:16
@jliexpensify Can you ping @abdulrahuman5196 in Slack maybe because he has been MIA?

**Comment by abdulrahuman5196** [comment] 2023-08-23 16:07
Reviewing now

**Comment by abdulrahuman5196** [comment] 2023-08-23 17:58
@Talha345 

Thanks for the updated proposal. Now I have some idea on the proposal made.

>The second solution would be to just implement the sublinks on https://help.expensify.com/hubs/split-bills using Tocbot but this does not make much sense imo because we can see that there are sublinks below 'Paying Friends' and 'Workspaces' links which are not actually links to the same page and redirect to some other page and therefore are not necessarily TOC.

Why do you think this is not best? Any drawbacks to this?

IMO I think this is better, the reason is even in the code comments it is mentioned all the TOC links should come here on the onclick function. I think this case should extend to sublinks as well and clicking sublinks also should trigger this.

https://github.com/Expensify/App/blob/f32b695764ded61bdd771e2d2504e0dd6679ce8a/docs/assets/js/main.js#L210-L217

Do you have references on how we can I achieve this?

**Comment by Talha345** [comment] 2023-08-23 18:10
> IMO I think this is better, the reason is even in the code comments it is mentioned all the TOC links should come here on the onclick function. I think this case should extend to sublinks as well and clicking sublinks also should trigger this.

@abdulrahuman5196 You are completely right.The code you mentioned above also gets executed when a click on a sublink is triggered.

The reason I mentioned that this does not make sense is that if you see the links in the screenshot below, only "Paying Friends" and "Workspaces" links are pointing to the same page but the sublinks "Request and Split Bills" and "The Free Plan" redirect to some other page, therefore this navigation list is not a Table of Content because TOC usually lists all the headings on a particular page https://en.wikipedia.org/wiki/Table_of_contents.

![image](https://github.com/Expensify/App/assets/36226639/cf4389cd-33e1-44bd-963a-fd29994c38d8)

On the other hand, if you see the links in the screenshot below, all the links are headings to some section of the same page and are therefore TOC for this particular page.

![image](https://github.com/Expensify/App/assets/36226639/518255c7-9c23-4d7c-9954-92531e17432e)

If we go forward with the second solution, there is no problem technically but I think that the links are not logically TOC but we can definitely implement them as such.There would be no particular technical drawback of this approach.

**Comment by getusha** [comment] 2023-08-23 18:12
@abdulrahuman5196 any comments on my proposal? in case you missed it🙂  https://github.com/Expensify/App/issues/23810#issuecomment-1680676503

**Comment by jliexpensify** [comment] 2023-08-26 07:03
Still looking at proposals - bumping @abdulrahuman5196 to address comments

**Comment by abdulrahuman5196** [comment] 2023-08-28 15:38
Reviewing now

**Comment by abdulrahuman5196** [comment] 2023-08-28 16:17
@Talha345 

>The reason I mentioned that this does not make sense is that if you see the links in the screenshot below, only "Paying Friends" and "Workspaces" links are pointing to the same page but the sublinks "Request and Split Bills" and "The Free Plan" redirect to some other page, therefore this navigation list is not a Table of Content because TOC usually lists all the headings on a particular page https://en.wikipedia.org/wiki/Table_of_contents.

This is technically true, but AFAIK there are multiple pages in the docs, whose TOC points to different pages. So this might not hold true for us logically.


>Only the ARTICLES pages navigation links are generated using TocBot.

Not sure what you mean by here.

**Comment by abdulrahuman5196** [comment] 2023-08-28 16:18
> @abdulrahuman5196 any comments on my proposal? in case you missed it🙂 [#23810 (comment)](https://github.com/Expensify/App/issues/23810#issuecomment-1680676503)

@getusha I did review this proposal, but it was similar to the proposal here https://github.com/Expensify/App/issues/23810#issuecomment-1656068129. Just using different listener IMO.

**Comment by getusha** [comment] 2023-08-28 16:23
> @getusha I did review this proposal, but it was similar to the proposal here #23810 (comment). Just using different listener IMO.

The proposal you mentioned suggested to add click listener to every link with a loop, and i suggested to add window listener to check if the url is changed or not and it's one liner solution, which is completely different.

**Comment by Talha345** [comment] 2023-08-28 16:39
> This is technically true, but AFAIK there are multiple pages in the docs, whose TOC points to different pages. So this might not hold true for us logically.

@abdulrahuman5196 can you provide some examples?

> Not sure what you mean by here.

What I mean is that https://help.expensify.com/hubs/split-bills is a HUBS page as it belongs to the main 4 sections in the LHN which we call as HUBS.It also has hubs in the URL itself.

On the other hand, the pages where the LHN is generated using TocBot are ARTICLES pages like https://help.expensify.com/articles/playbooks/Expensify-Chat-Playbook-for-Conferences.

This can be seen [here](https://github.com/Expensify/App/blob/main/docs/_layouts/default.html#L48-L59).

Also my first solution is a totally generic solution and will also act as a single source for toggling the LHN using the `toggleHeaderMenu`. Not sure why aren't we just going further with that.

**Comment by abdulrahuman5196** [comment] 2023-08-28 16:49
@Talha345 @getusha 

I still feel adding a listener and closing the LHN based on the url is workaround solution. (I will check with others if this is the only path)

Let me gather up what I have understood till now and let me know if I am wrong about anything.

1) There are pages which is using TocBot And there are pages which are not
2) And the issue page doesn't use TocBot and so doesn't auto close the menu.
3) It is not feasible to implement TocBot to pages which currently doesn't have.

So the proposals target to add listeners in some form to detect page/url changes and close the header menu.

**Comment by getusha** [comment] 2023-08-28 16:54
@abdulrahuman5196 i believe the reason the LHN is closing when clicking on other links, is because of a full page reload, but in this case it is in-page link which will not cause a full page reload.

**Comment by Talha345** [comment] 2023-08-28 16:56
> Let me gather up what I have understood till now and let me know if I am wrong about anything.
> 
> 1. There are pages which is using TocBot And there are pages which are not
> 2. And the issue page doesn't use TocBot and so doesn't auto close the menu.
> 3. It is not feasible to implement TocBot to pages which currently doesn't have.
> 
> So the proposals target to add listeners in some form to detect page/url changes and close the header menu.

@abdulrahuman5196 Your understanding is correct. However, my proposal is to add an event listener for the click event and not to detect page/url changes.

Also, how this my proposal a workaround.It is basically implementing a functionality that is required and not present currently.When a user clicks a link in the LHN and the link points to the same page, we want to close the LHN and that's what my proposal is doing.If you look at the [main.js](https://github.com/Expensify/App/blob/main/docs/assets/js/main.js#L222-L245) file, we already have such listeners for other required functionality.

**Comment by Talha345** [comment] 2023-08-28 17:05
@getusha If you do not mind, I can provide some feedback on why your proposed solution is not very efficient and can also lead to further bugs. What you are suggesting is to add event listeners on `hashchange` or `popstate` event.If we do this and a user is on a page and goes to the URL and updates the fragment identifier manually, the LHN will open automatically if it is closed and vice versa.

Secondly, your solution will intefere with the pages implemented via TocBot and the `toggleHeaderMenu` will be called twice for those pages which will just close and open the LHN again.

**Comment by getusha** [comment] 2023-08-28 17:09
>I was trying both your solutions. For some reason both doesn't work for me. (Ran both solutions separate)

@abdulrahuman5196 Can you try the second solution? it probably is not working because of the hash changed at first and you tried again. postate should work perfectly.

**Comment by Talha345** [comment] 2023-08-28 17:10
> Yes true. Seems I need to re-evaluate if my workaround mention is right. But anyways I will try if the solution is working then, will proceed accordingly.
> 
>  Screen.Recording.2023-08-28.at.10.32.04.PM.mov

@abdulrahuman5196 my solution is working fine for me.


https://github.com/Expensify/App/assets/36226639/517e77f3-9513-4c81-8a76-31d5d9b3410a

**Comment by getusha** [comment] 2023-08-28 17:13
>@getusha If you do not mind, I can provide some feedback on why your proposed solution is not very efficient and can also lead to further bugs. What you are suggesting is to add event listeners on hashchange or popstate event.If we do this and a user is on a page and goes to the URL and updates the fragment identifier manually, the LHN will open automatically if it is closed and vice versa.


We can add conditions if there will be any issues related and can you show me a video of the bug? i appreciate that.

**Comment by Talha345** [comment] 2023-08-28 17:25
> ```js
> window.addEventListener('hashchange', toggleHeaderMenu);
> ```

@getusha Please find below the video of the bug I mentioned.


https://github.com/Expensify/App/assets/36226639/bb910051-6714-487c-9eb9-087502580130

**Comment by getusha** [comment] 2023-08-28 17:36
@Talha345 that can be easily avoided by only closing the LHN instead of toggling it, which is the right thing to do.

**Comment by Talha345** [comment] 2023-08-29 12:33
Hi @abdulrahuman5196, any update?

**Comment by abdulrahuman5196** [comment] 2023-08-29 16:10
@Talha345 @getusha 

On comment here https://github.com/Expensify/App/issues/23810#issuecomment-1696042503 i did try both solutions separately that time itself and didn't work. 

Now I tested again, it seems to be working in chrome web on laptop by changing the responsiveness to mobile screen. But the same is not working directly in android simulator. (I have to test on real device, need to check on how to run in real devices)

And all the videos of working is uploaded on web responsive change or safari change, none is directly on android simulator or real android chrome(Which is the original bug platform)

Kindly test and let me know if it is working or if I had missed something.

**Comment by Talha345** [comment] 2023-08-29 16:12
> est and let me know if it is

@abdulrahuman5196  The bug is not platform specific.The bug occurs on help docs in responsive view on any website.Maybe try ngrok to test on real device?

**Comment by abdulrahuman5196** [comment] 2023-08-29 16:18
I will check on real devices then and update back here

**Comment by Talha345** [comment] 2023-08-29 16:19
@abdulrahuman5196 You can test yourself using this ngrok link from my dev env https://60e1-85-8-80-53.ngrok-free.app/

**Comment by abdulrahuman5196** [comment] 2023-08-29 16:20
@Talha345 

>@abdulrahuman5196 You can test yourself using this ngrok link from my dev env https://60e1-85-8-80-53.ngrok-free.app/

Sorry, I need to check myself if the solution is working or not before proceeding to next steps. I will check at my end and will update.

**Comment by Talha345** [comment] 2023-08-29 16:22
> @Talha345
> 
> > @abdulrahuman5196 You can test yourself using this ngrok link from my dev env https://60e1-85-8-80-53.ngrok-free.app/
> 
> Sorry, I need to check myself if the solution is working or not before proceeding to next steps. I will check at my end and will update.

@abdulrahuman5196 Yes I understand that.I was just trying to help you to test on real device.

**Comment by Talha345** [comment] 2023-08-30 19:00
Hi @abdulrahuman5196 , any update?

**Comment by jliexpensify** [comment] 2023-09-04 00:53
Bumping @abdulrahuman5196 !

**Comment by Talha345** [comment] 2023-09-04 20:19
@jliexpensify Can you please ping @abdulrahuman5196 in slack as he has been MIA since a week?

**Comment by jliexpensify** [comment] 2023-09-05 01:06
Pinged, thanks @Talha345 !

**Comment by abdulrahuman5196** [comment] 2023-09-05 14:00
@Talha345 @getusha Both the solutions are not working even when trying with ngrok with real device.

It is only working in web chrome if I change the responsiveness to mobile device and test it out.

**Comment by Talha345** [comment] 2023-09-05 14:05
> @Talha345 @getusha Both the solutions are not working even when trying with ngrok with real device. Maybe it could be related to devices. I tested with pixel 6 in real device and pixel 6 pro in simulator

@abdulrahuman5196 Firstly, the issue is only present in responsive mode.Secondly, I have tested my proposal on real Android as well as IOS devices as well as simulators and it was working flawlessly.I have already offered to provide you a ngrok link from my development environment which I would be happy to provide to you again.I have also shared the working video on a real device [here](https://github.com/Expensify/App/issues/23810#issuecomment-1697764318).

Please let me know how can I can help you in this regard.

**Comment by abdulrahuman5196** [comment] 2023-09-05 14:09
@Talha345 Can you provide you ngrok? Let me see if that is working for me?

**Comment by Talha345** [comment] 2023-09-05 14:13
@abdulrahuman5196 Sure! There you go.

https://b4e6-141-30-226-252.ngrok-free.app/#gsc.tab=0

**Comment by getusha** [comment] 2023-09-05 14:14
>@Talha345 @getusha Both the solutions are not working even when trying with ngrok with real device. Maybe it could be related to devices. I tested with pixel 6 in real device and pixel 6 pro in simulator


@abdulrahuman5196 i will test on real device and emulator and let you know.

**Comment by abdulrahuman5196** [comment] 2023-09-05 15:26
Thanks for the information folks. It seems to working fine for the contributors, for some reason not working for me. I try for a little while to test it out at my end and come back with some findings or proposal approval.

**Comment by abdulrahuman5196** [comment] 2023-09-05 15:51
Hi Folks, Sorry for the back and forth. But for some reason, still not working for me. 

So I am sharing the code I am testing, let me know if I am missing something. 
Note: We don't usually do code diff checks, just a POC working would be fine, but since the proposals are not working at my end, sharing the code diff.

@Talha345 proposal I am testing.

```diff
--- a/docs/assets/js/main.js
+++ b/docs/assets/js/main.js
@@ -147,6 +147,13 @@ function insertElementAfter(referenceNode, newNode) {
     referenceNode.parentNode.insertBefore(newNode, referenceNode.nextSibling);
 }
 
+function isSamePageScrollLink(link) {
+    const href = link.getAttribute("href");
+    if (href.startsWith("#") && !!document.getElementById(href.slice(1))) {
+        toggleHeaderMenu();
+    }
+}
+
 // Need to wait up until page is load, so the svg viewBox can be changed
 // And the search label can be inserted
 window.addEventListener('load', () => {
@@ -210,9 +217,9 @@ window.addEventListener('DOMContentLoaded', () => {
             // onclick function to apply to all links in toc. will be called with
             // the event as the first parameter, and this can be used to stop,
             // propagation, prevent default or perform action
-            onClick() {
-                toggleHeaderMenu();
-            },
+            // onClick() {
+            //     toggleHeaderMenu();
+            // },
         });
     }
 
@@ -234,6 +241,12 @@ window.addEventListener('DOMContentLoaded', () => {
             e.preventDefault();
         }
     });
+    lhnContent.addEventListener('click', (event) => {
+        const clickedLink = event.target;
+        if (clickedLink) {
+            isSamePageScrollLink(clickedLink);
+        }
+    });
     window.addEventListener('scroll', (e) => {
         const scrollingElement = e.target.scrollingElement;
         const scrollPercentageInArticleContent = clamp(scrollingElement.scrollTop - articleContent.offsetTop, 0, articleContent.scrollHeight) / articleContent.scrollHeight;
```



@getusha  proposal I am testing took from here https://github.com/Expensify/App/issues/23810#issuecomment-1697397634

```diff
--- a/docs/assets/js/main.js
+++ b/docs/assets/js/main.js
@@ -1,10 +1,10 @@
 /* eslint-disable no-unused-vars */
-function toggleHeaderMenu() {
+function toggleHeaderMenu(close) {
     const lhn = document.getElementById('lhn');
     const lhnContent = document.getElementById('lhn-content');
     const anguleUpIcon = document.getElementById('angle-up-icon');
     const barsIcon = document.getElementById('bars-icon');
-    if (lhnContent.className === 'expanded') {
+    if (lhnContent.className === 'expanded' || close) {
         // Collapse the LHN in mobile
         lhn.className = '';
         lhnContent.className = '';
@@ -216,7 +216,8 @@ window.addEventListener('DOMContentLoaded', () => {
         });
     }
 
-    document.getElementById('header-button').addEventListener('click', toggleHeaderMenu);
+    window.addEventListener('popstate', () => toggleHeaderMenu(true))
+    document.getElementById('header-button').addEventListener('click', () => toggleHeaderMenu());
 
     // Back button doesn't exist on all the pages

```

**Comment by getusha** [comment] 2023-09-05 15:54
@abdulrahuman5196 on which browser are you testing this on?

**Comment by Talha345** [comment] 2023-09-05 15:56
> Note: We don't usually do code diff checks, just a POC working would be fine, but since the proposals are not working at my end, sharing the code diff.

@abdulrahuman5196 The code for my proposal seems fine on your end, however I think there might be some problem in your docs setup!

**Comment by abdulrahuman5196** [comment] 2023-09-05 15:56
> @abdulrahuman5196 on which browser are you testing this on?

@getusha 
Chrome web, firefox web, pixel 6 pro simulator, pixel 6 real device.

Only working on chrome web. None of the other is working.

**Comment by Talha345** [comment] 2023-09-05 15:57
> 



> Chrome web, firefox web, pixel 6 pro simulator, pixel 6 real device.
> 
> Only working on chrome web. None of the other is working.

@abdulrahuman5196 What command are you using to run the jekyll server?

**Comment by abdulrahuman5196** [comment] 2023-09-05 16:01
> > Note: We don't usually do code diff checks, just a POC working would be fine, but since the proposals are not working at my end, sharing the code diff.
> 
> @abdulrahuman5196 The code for my proposal seems fine on your end, however I think there might be some problem in your docs setup!

@Talha345 Not sure on how this bug fix alone is related to docs setup. 

Command I used to run `bundle exec jekyll serve --livereload` got from here https://github.com/Expensify/App/tree/main/docs#testing-locally

Anyways i will setup an another fresh repo clone and test this out. Even if not working will reach out to other members for help to avoid dragging on this issue.

**Comment by Talha345** [comment] 2023-09-05 16:02
> > > Note: We don't usually do code diff checks, just a POC working would be fine, but since the proposals are not working at my end, sharing the code diff.
> > 
> > 
> > @abdulrahuman5196 The code for my proposal seems fine on your end, however I think there might be some problem in your docs setup!
> 
> @Talha345 Not sure on how this bug fix alone is related to docs setup.
> 
> Command I used to run `bundle exec jekyll serve --livereload` got from here https://github.com/Expensify/App/tree/main/docs#testing-locally
> 
> Anyways i will setup an another fresh repo clone and test this out. Even if not working will reach out to other members for help to avoid dragging on this issue.

@abdulrahuman5196 can you simply try to run the server without the livereload flag i.e `bundle exec jekyll serve`

**Comment by getusha** [comment] 2023-09-05 16:03
>Chrome web, firefox web, pixel 6 pro simulator, pixel 6 real device.

Hmmm just tested on firefox and it seems to be working,

**Comment by abdulrahuman5196** [comment] 2023-09-05 16:04
> @abdulrahuman5196 can you simply try to run the server without the livereload flag i.e `bundle exec jekyll serve`

Yep tried all. Same results. 

> Hmmm just tested on firefox and it seems to be working,

Seems its working for all except me 😮‍💨 . 


Will try to setup fresh clone and if still not working will reach out to other members for help.

**Comment by Talha345** [comment] 2023-09-05 16:06
> Seems its working for all except me 😮‍💨 .
> 
> Will try to setup fresh clone and if still not working will reach out to other members for help.

@abdulrahuman5196 Sounds good! Will be waiting for an update! Do let me know if you need any further assistance in any way 🙂

**Comment by getusha** [comment] 2023-09-05 16:07
>Seems its working for all except me 😮‍💨 .
Will try to setup fresh clone and if still not working will reach out to other members for help.

thanks, let me know if you need me to build it and send you the link.

**Comment by abdulrahuman5196** [comment] 2023-09-05 16:08
> > Seems its working for all except me 😮‍💨 .
> > Will try to setup fresh clone and if still not working will reach out to other members for help.
> 
> thanks, let me know if you need me to build it and send you the link.

Thank you @getusha . Will reach out if anything else is required.

**Comment by Talha345** [comment] 2023-09-07 17:00
> > > Seems its working for all except me 😮‍💨 .
> > > Will try to setup fresh clone and if still not working will reach out to other members for help.
> > 
> > 
> > @abdulrahuman5196 Sounds good! Will be waiting for an update! Do let me know if you need any further assistance in any way 🙂
> 
> Thank you will provide an update by tomorrow.

Hi @abdulrahuman5196 , any update ?

**Comment by jliexpensify** [comment] 2023-09-08 02:09
Not overdue, waiting on @abdulrahuman5196

**Comment by abdulrahuman5196** [comment] 2023-09-11 16:30
Sorry folks, last week got some blocker issues. Setting up new workspace now. Will update in couple of hours.

**Comment by abdulrahuman5196** [comment] 2023-09-11 17:31
I setup a new workspace and both the solutions are working fine in the setup. 
@getusha 's solution here https://github.com/Expensify/App/issues/23810#issuecomment-1680676503 is on the same concept but with a different approach(different listener) comparing to @Talha345 's proposed solution here https://github.com/Expensify/App/issues/23810#issuecomment-1656068129. Previously pointed out the same here https://github.com/Expensify/App/issues/23810#issuecomment-1695974617

So I am going ahead with the first proposal of @Talha345 .

@Talha345 's proposal here https://github.com/Expensify/App/issues/23810#issuecomment-1656068129 looks good and works well.

🎀 👀 🎀
C+ Reviewed

**Comment by tgolen** [comment] 2023-09-12 13:36
I'm OK with that proposal, but I think the extra function is unnecessary and the code can be simplified to not have `isSamePageScrollLink()`. I'll address that in the PR.

**Comment by Talha345** [comment] 2023-09-12 14:29
@tgolen Job accepted on upwork for the contributor role.Since I was the reporter for this issue, I got the reporter offer too but it is for $50 but this issue was reported way before the rates were updated, so I guess it should be $250, right? This discrepancy can be fixed either right now or once we get to the payments part but just wanted to mention for the record.

PR will be up in a few hours! 🚀

**Comment by tgolen** [comment] 2023-09-12 15:07
Yeah, I agree with you that if it came before the rates were updated, then you get the original amount of $250. Let's handle that when this gets submitted for payment.

**Comment by Talha345** [comment] 2023-09-12 15:37
@tgolen @abdulrahuman5196 PR is ready for review https://github.com/Expensify/App/pull/27261

**Comment by jliexpensify** [comment] 2023-09-12 23:11
@Talha345 I always post a payments summary before paying, so you can verify the rates then!

**Comment by jliexpensify** [comment] 2023-09-25 03:57
Payment Summary ([is this right? It seems like it was marged in 3 days](https://github.com/Expensify/App/issues/23810#issuecomment-1721591159))

- Bug Reporter / Contributor: @Talha345 $250 + $1000 + $500 (speed bonus)
- C+: @abdulrahuman5196: $1000 + $500 (speed bonus)

Is this correct?

I'll need to make a new Upworks job as well.

**Comment by Talha345** [comment] 2023-09-25 06:19
> Payment Summary ([is this right? It seems like it was merged in 3 days](https://github.com/Expensify/App/issues/23810#issuecomment-1721591159))
> 
> - Bug Reporter / Contributor: @Talha345 $250 + $1000 + $500 (speed bonus)
> - C+: @abdulrahuman5196: $1000 + $500 (speed bonus)
> 
> Is this correct?
> 
> [New Upworks job](https://www.upwork.com/jobs/~01ef28246f3357b5a4).

@jliexpensify Looks correct! Do I have to apply to the new Upwork job or will you be sending an offer automatically?

**Comment by jliexpensify** [comment] 2023-09-25 06:23
Offers have been sent!

**Comment by Talha345** [comment] 2023-09-25 06:27
> Offers have been sent!

@jliexpensify Yes the offers were sent automatically on the old Upwork job and for this new Upwork job that you just linked, I simply got an invitation to submit a proposal but no offer.

**Comment by jliexpensify** [comment] 2023-09-27 07:34
Reminder for @abdulrahuman5196 to complete the checklist

**Comment by abdulrahuman5196** [comment] 2023-09-27 10:21
>The PR that introduced the bug has been identified. Link to the PR:
The offending PR has been commented on, pointing out the bug it caused and why, so the author and reviewers can learn from the mistake. Link to comment:
A discussion in #expensify-bugs has been started about whether any other steps should be taken (e.g. updating the PR review checklist) in order to catch this type of bug sooner. Link to discussion:

Not a regression. Seems to be the behaviour from beginning.

>Determine if we should create a regression test for this bug.
If we decide to create a regression test for the bug, please propose the regression test steps to ensure the same bug will not reach production again.

No. This is a minor case and wouldn't be beneficial to add tests.

**Comment by abdulrahuman5196** [comment] 2023-09-27 10:22
@jliexpensify Added checklist and submitted proposal on the upwork new job

**Comment by jliexpensify** [comment] 2023-09-28 01:18
Thanks @abdulrahuman5196 have hired you, just waiting on acceptance

**Comment by abdulrahuman5196** [comment] 2023-09-28 03:59
@jliexpensify accepted the offer

**Comment by jliexpensify** [comment] 2023-09-28 04:26
Paid out @abdulrahuman5196 - there was a very strange issue with your contract @Talha345 : can you confirm that you've not received any payment?

**Comment by jliexpensify** [comment] 2023-09-28 08:11
@Talha345 I see you ended a contract today. This is a bit confusing - can I confirm if you have been paid?

**Comment by Talha345** [comment] 2023-09-28 08:13
> Paid out @abdulrahuman5196 - there was a very strange issue with your contract @Talha345 : can you confirm that you've not received any payment?

@jliexpensify I have not received any payment, however I received a latest offer from you which I have accepted but I had now 3 different contracts for this same issue.

I have therefore ended the 2 previous contracts without any payment.Now you can pay me with the open contract.

**Comment by jliexpensify** [comment] 2023-09-28 09:17
Thanks for clarifying - paid and job closed.

**Closed by jliexpensify** 2023-09-28 09:17 UTC
Labels: External, Daily, Awaiting Payment, Bug
