### ISSUE TITLE
Clicking on a newly added avatar shows an empty attachment badge

### ISSUE THREAD

**Issue by kavimuru** [Expensify/App#14527] opened 2023-01-24 23:13 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed

1. Open Profile and upload new avatar
2. Close the drawer and click on an avatar in a report
3. Click on the avatar in the right drawer

## Expected Result
The avatar should display as normal

## Actual Result
There is an empty screen with an attachment logo

## Workaround:
unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?

- [ ] MacOS / Chrome / Safari

**Version Number:** 1.2.58-3
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** 

https://user-images.githubusercontent.com/43996225/214441728-4726be3c-936e-4562-b2b3-fadce979fdc4.mov

https://user-images.githubusercontent.com/43996225/214441763-193365b5-50e1-470a-947e-6c30f3369ab0.mp4

**Expensify/Expensify Issue URL:**
**Issue reported by:** @esh-g 
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1674229083160309

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by garrettmknight** [comment] 2023-01-25 20:57
Tested on v1.2.59-1 and I wasn't able to reproduce. @kavimuru can you give it another try and tell me if you're still seeing it?

**Comment by garrettmknight** [comment] 2023-01-30 13:06
Followed up in [slack](https://expensify.slack.com/archives/C049HHMV9SM/p1675083990070829?thread_ts=1674229083.160309&cid=C049HHMV9SM)

**Comment by garrettmknight** [comment] 2023-01-30 19:20
Fixing [here](https://github.com/Expensify/App/issues/12707) - closing this issue as a dupe.

**Closed by garrettmknight** 2023-01-30 19:20 UTC
Labels: Daily, Needs Reproduction, Bug
