### ISSUE TITLE
Chat - 'New' label does not appear until user switches to other chat and back to previous chat

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#22599] opened 2023-07-10 23:47 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Go to staging.new.expensify.com
2. As User A, go to any conversation
3. As User B, send a new message to User A.

## Expected Result:
As User A, 'new' label does not show up above new message. It only shows up after user A switches to other conversation and back to conversation with User B

## Actual Result:
Reproducible on web, mweb and Android. On Android, the 'new' label does not show up at all

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android / native
- [x] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [x] Windows / Chrome 
- [ ] MacOS / Desktop

**Version Number:** 1.3.38.4

**Reproducible in staging?:** Yes

**Reproducible in production?:** Yes

**If this was caught during regression testing, add the test name, ID and link from TestRail:**

**Email or phone of affected tester (no customers):**

**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/78819774/7a69f319-4c73-4417-95c1-800c756f936a

**Expensify/Expensify Issue URL:** Applause- Internal Team

**Slack conversation:**

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by StevenKKC** [comment] 2023-07-11 07:19
This seems to be intended.
https://github.com/Expensify/App/blob/e299de5cf3db15f40e2aeafd5060810a28464d64/src/pages/home/report/ReportActionsView.js#L137-L147

**Comment by trjExpensify** [comment] 2023-07-12 10:42
Hm, @MonilBhavsar, you're working on wholesale changes to the new unreads markers. Can I get an opinion from you on this one? I don't think we should spend time on this isolated fix versus addressing them holistically through your design doc.

**Comment by MonilBhavsar** [comment] 2023-07-12 11:31
This would be fixed by the refactor. The expected behavior is in this case is - Since user was active on the chat while receiving the message, we won't display unread marker(that seems to be working), and we also don't want to display marker when they revisit that chat, as message was already read previosuly(this seems broken)

**Comment by trjExpensify** [comment] 2023-07-12 12:08
Cool, so if this will be fixed by the refactors I'm going to close it out!

**Closed by trjExpensify** 2023-07-12 12:08 UTC
Labels: Daily, Bug
