### ISSUE TITLE
[$250] Android - Accounting - Sage Intacct connection stuck and freezes application

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#47109] opened 2024-08-08 20:10 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 9.0.18-3
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**If this was caught during regression testing, add the test name, ID and link from TestRail:** https://expensify.testrail.io/index.php?/cases/view/3155294
**Issue reported by:** Applause - Internal Team

## Action Performed:
Precondition: account with a Control workspace and Accounting enabled.
1. Navigate to Accounting
2. Connect Sage Intacct
3. Enter Sage Intacct credentials

## Expected Result:
Integration sync established. The menu items are shown for Import / Export / Advanced and can be opened by tap

## Actual Result:
Integration sync stuck in 'Syncing reimbursed reports and bill payments' status. Tapping on Import / Export / Advanced leads to nothing. Application freezes

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [ ] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details> 

https://github.com/user-attachments/assets/17972046-7303-40aa-8ecc-ec61d8b71e44

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~016b900fcf15a9753e</li>
        <li>Upwork Job ID: 1821973634716618730</li>
        <li>Last Price Increase: 2024-09-06</li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @shubham1206agra</details>

**Comment by lanitochka17** [comment] 2024-08-08 20:11
We think that this bug might be related to #wave-control

**Comment by nanegate** [comment] 2024-08-09 22:07
The problem is that the main thread of your application is blocked, so it throws ANR. I can fix it if you want.

**Comment by jp928** [comment] 2024-08-12 10:51
I need to access the `Sage Intacct` account if you have one for testing purpose.

**Comment by isabelastisser** [comment] 2024-08-15 18:23
@shubham1206agra, can you please follow up on the comment above? thanks!

**Comment by isabelastisser** [comment] 2024-08-19 15:39
@shubham1206agra, I DM'd you for visibility.

**Comment by isabelastisser** [comment] 2024-08-19 16:26
Waiting for access to Sage/Intacct:

https://expensify.slack.com/archives/C02NK2DQWUX/p1722928262349749

**Comment by isabelastisser** [comment] 2024-08-27 00:27
Still waiting for access. https://github.com/Expensify/Expensify/issues/422115

**Comment by isabelastisser** [comment] 2024-09-03 18:48
@shubham1206agra, I added the `retest-weekly` label. Is that what you meant? Thanks!

**Comment by isabelastisser** [comment] 2024-09-05 20:17
No progress yet.

**Comment by isabelastisser** [comment] 2024-09-06 16:33
Thanks for the update, @shubham1206agra! Closing this one.

**Closed by isabelastisser** 2024-09-06 16:33 UTC
Labels: External, Daily, Help Wanted, Bug, retest-weekly
