### ISSUE TITLE
[Payment due 3/6][$500]  iOS - Saved Private note field not sticky, page can be scrolled

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#35775] opened 2024-02-04 17:27 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.36
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):** applausetester+cknew@applause.expensifail.com
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** Applause - Internal Team
**Slack conversation:**

## Action Performed:
1. Launch New Expensify app
2. Open either #announce room, #admins room or 1:1 conversation
2. Tap on header to go to details or profile page
3. Tap on Private notes option
4. Enter note & save it
5. Scroll the private notes page (Note: Saved note field not sticky)

## Expected Result:
Saved note field should be sticky & should not be able to scroll

## Actual Result:
Saved note field should be sticky & should not be able to scroll

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [x] iOS: Native
- [ ] iOS: mWeb Safari
- [ ] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details> 

https://github.com/Expensify/App/assets/78819774/cf935a7e-b28b-4b33-aa27-6f67be8fef84

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~015ac87fcf9eab0d9e</li>
        <li>Upwork Job ID: 1754195036051189760</li>
        <li>Last Price Increase: 2024-02-04</li>
<li>Automatic offers: </li>
<ul>
<li>situchan | Contributor | 28149495</li>
<li>mkhutornyi | Contributor | 0</li>
</ul></li>
    </ul>
</details>

**Comment by lanitochka17** [comment] 2024-02-04 17:28
We think that this bug might be related to #vip-vsp
CC @quinthar

**Comment by jeremy-croff** [comment] 2024-02-04 17:40
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
The private notes are scrollable when there's no need to be scrollable.

### What is the root cause of that problem?
We use a ScrollView component

### What changes do you think we should make in order to solve the problem?
Use a regular View component
Will be scrollable once the content overflows.

component to replace is here:
https://github.com/Expensify/App/blob/3ab4e6e12d9ff38e69493321f0d31f032481b373/src/pages/PrivateNotes/PrivateNotesListPage.tsx#L92

### What alternative solutions did you explore? (Optional)

**Comment by Christinadobrzyn** [comment] 2024-02-06 00:17
I think this can be external, low priority, and seems to only be affecting iOS. 

@Santhosh-Sellavel feel free to review the proposals.

**Comment by Santhosh-Sellavel** [comment] 2024-02-07 17:27
Unassigning this one due to low bandwidth, please reassign @Christinadobrzyn!

**Comment by situchan** [comment] 2024-02-07 17:32
I can review this

**Comment by Santhosh-Sellavel** [comment] 2024-02-07 17:33
@situchan Are you subscribed to me? 😅

**Comment by situchan** [comment] 2024-02-07 17:36
> @situchan Are you subscribed to me? 😅

Not only you 😄.  I am subscribed to most issues/PRs to get full understanding of project status

**Comment by Christinadobrzyn** [comment] 2024-02-08 23:00
I think we're reviewing proposals right @situchan?

**Comment by situchan** [comment] 2024-02-09 00:15
@Christinadobrzyn to confirm, do you agree with expected behavior: `Saved note field should be sticky & should not be able to scroll`? This is iOS feature but should be fixed as inconsistent with other platforms?

**Comment by Christinadobrzyn** [comment] 2024-02-09 22:24
Hi @situchan yes, I agree this should be the expected behaviour

> Saved note field should be sticky & should not be able to scroll

**Comment by situchan** [comment] 2024-02-12 15:47
@Christinadobrzyn thanks.
In that case, @mkhutornyi's [proposal](https://github.com/Expensify/App/issues/35775#issuecomment-1925877214) looks good to me.
🎀 👀 🎀 C+ reviewed

**Comment by Christinadobrzyn** [comment] 2024-02-27 00:31
PR is in staging - https://github.com/Expensify/App/pull/36772

**Comment by situchan** [comment] 2024-03-06 16:40
PR was deployed to production on Feb 28

**Comment by Christinadobrzyn** [comment] 2024-03-07 01:26
Payouts due:

Contributor: $500 @mkhutornyi (paid in Upwork)
Contributor+: $500 @situchan (paid in Upwork)

Upwork job is [here](https://www.upwork.com/jobs/~015ac87fcf9eab0d9e).

Do we need a regression test for this @situchan?

**Comment by situchan** [comment] 2024-03-07 06:33
No need regression test as reported by QA team and issue is minor enough

**Comment by Christinadobrzyn** [comment] 2024-03-07 06:51
Awesome - thanks for conifrming @situchan! Closing this!

**Closed by Christinadobrzyn** 2024-03-07 06:51 UTC
Labels: Reviewing, External, Weekly, Bug
