### ISSUE TITLE
App crashes during the deletion of IOU requests

### ISSUE THREAD

**Issue by kavimuru** [Expensify/App#25995] opened 2023-08-26 17:15 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Open a chat.
2. Navigate to the "Request money" feature.
3. Enter an amount and send a request.
4. Return to the "Request money" section.
5. Enter another amount and send a request.
6. Click on the "Requested money".
7. Edit the "Merchant" field for the most recent request.
8. Proceed to delete the requests one by one.
## Expected Result: 
The app should not crash when deleting IOU requests
## Actual Result: 
The app crashes when attempting to delete IOU requests
## Workaround:
Can the user still use Expensify without this being fixed? Have you informed them of the workaround?

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [x] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 
**Reproducible in staging?:** needs reproduction
**Reproducible in production?:** needs reproduction
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/43996225/38d4da73-9133-43d1-98bc-105951fe0938

**Expensify/Expensify Issue URL:**
**Issue reported by:** @ayazhussain79 
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1692985633749559

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by ayazhussain79** [comment] 2023-08-26 17:21
If you have already requested money then delete them all and then try these steps:

**Action Performed:**

1. Open a chat.
2. Navigate to the "Request money" feature.
3. Enter an amount and send a request.
4. Return to the "Request money" section.
5. Enter another amount and send a request.
6. Click on the "Requested money".
7. Edit the "Merchant" field for the most recent request.
8. Proceed to delete the requests one by one.

**Comment by mountiny** [comment] 2023-08-27 21:23
@ayazhussain79 ca. You please share the console logs when there is crash like this? Please try to do that everytime as thats super helpful thanks

**Comment by ayazhussain79** [comment] 2023-08-27 21:29
@mountiny Ok, I shared it on slack forgot to share it here sorry


![Screenshot 2023-08-25 at 11.24.57 PM.png](https://github.com/Expensify/App/assets/56740856/b0045b52-4470-4f63-b43a-a0295ae527ce)

**Comment by kadiealexander** [comment] 2023-08-28 06:19
@ayazhussain79 I wasn't able to repro, could you please take a look?

https://github.com/Expensify/App/assets/59587260/c032bd69-159d-4bce-a786-998db385a8c6

**Comment by ayazhussain79** [comment] 2023-08-28 09:04
@kadiealexander please try it on staging

**Comment by kadiealexander** [comment] 2023-08-29 07:17
No crash on staging, and I tried it a few different ways:

https://github.com/Expensify/App/assets/59587260/1571b9c3-c075-453a-8e3f-abcf08e25558


https://github.com/Expensify/App/assets/59587260/7e8da49a-2fa7-450c-9612-127502944805

**Comment by ayazhussain79** [comment] 2023-08-29 11:23
@kadiealexander can you please try these steps i can still reproduce it using these steps:

**Action Performed:**

1. Open a chat.
2. Navigate to the "Request money" feature.
3. Enter an amount and send a request.
4. Return to the "Request money" section.
5. Enter another amount and send a request.
6. Click on the "Requested money".
7. Edit the "Merchant" field for the most recent request.
8. Now click on "From xyz" header link 
9. Now start deleting IOU from most recent IOU


https://github.com/Expensify/App/assets/56740856/e60223e7-8225-414d-b129-54a5f8f99f0f

**Comment by kadiealexander** [comment] 2023-08-30 06:35
@ayazhussain79 I did your steps exactly and still unable to reproduce:

https://github.com/Expensify/App/assets/59587260/2e270501-b075-424e-b3e1-d107c6e2bd8a

Do you think there are any actions being logged that might help us work out why this crash is occurring?

**Comment by ayazhussain79** [comment] 2023-08-30 13:06
@kadiealexander This is now fixed :disappointed: a bug PR may have fixed the issue reported after me

**Closed** 2023-08-31 06:30 UTC
Labels: Daily, Needs Reproduction, Bug
