### ISSUE TITLE
[HOLD for payment 2023-12-07] Tag - Child tags are not displayed in Recent

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#31760] opened 2023-11-22 22:47 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.2-0
**Reproducible in staging?:** Y
**Reproducible in production?:** N
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** Applause - Internal Team
**Slack conversation:**

## Action Performed:
precondition: enable and add parent and child tags < 8 as an admin on OD
1. Log in to ND as an employee
2. Navigate to workspace chat
3. Tap the "+" > Request money
4. Enter the amount
5. On the confirmation screen, tap the "Show more" button
6. Tap "Tags" and select a child tag
7. Start another money request
8. Open "Tags" on the confirmation page

## Expected Result:
Previously used child tag is displayed in Recent

## Actual Result:
The previously used child tag is not displyed in Recent

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [x] Android: mWeb Chrome
- [x] iOS: Native
- [x] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details> 

https://github.com/Expensify/App/assets/78819774/b75aa75f-f507-4944-b7cc-fea186522f37

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Issue Owner</summary>Current Issue Owner: @JmillsExpensify</details>

**Comment by lanitochka17** [comment] 2023-11-22 22:48
Production: 
 
https://github.com/Expensify/App/assets/78819774/a885c316-93e0-43a1-a672-0225f4976fb0

**Comment by bondydaa** [comment] 2023-11-22 23:02
I'm suspicious of this PR https://github.com/Expensify/App/pull/31494

**Comment by bondydaa** [comment] 2023-11-22 23:13
> precondition: enable and add parent and child tags < 8 as an admin on OD

Hmm I can't seem to figure out how to do this.

trying to click either of these workspaces I have just redirects me to new dot and I can't open up the policy editor in new dot 
<img width="1246" alt="image" src="https://github.com/Expensify/App/assets/4073354/3f46cca5-63f6-4b1b-bbde-7798c8b2f1d2">

**Comment by bondydaa** [comment] 2023-11-22 23:17
started a thread here https://expensify.slack.com/archives/C01GTK53T8Q/p1700694914941689

@lanitochka17 can you show me how to enable and create mutli-level tags on a workspace?

**Comment by luacmartins** [comment] 2023-11-23 00:50
I'm gonna demote this to NAB since it's a pretty small issue. @bondydaa can you confirm if [this PR](https://github.com/Expensify/App/pull/31494) is indeed the culprit and tag the original contributor to fix the issue?

**Comment by luacmartins** [comment] 2023-11-23 00:59
I confirmed that reverting PR https://github.com/Expensify/App/pull/31494 solves the issue. @FitseTLT can you work on a fix? cc @jjcoffee @roryabraham

**Comment by FitseTLT** [comment] 2023-11-23 07:39
@luacmartins I will create a fix pr 👍 and will link it to this issue. Isn't that what I am supposed to do? @luacmartins

**Comment by jjcoffee** [comment] 2023-11-23 07:54
@FitseTLT Yup, go ahead!

**Comment by jjcoffee** [comment] 2023-11-28 08:38
No payments will be due since it's a regression, as you say. I think we usually just close the issue once the fix hits production.

**Comment by JmillsExpensify** [comment] 2023-11-29 00:25
Agreed, let's close once it hits production.

**Comment by bondydaa** [comment] 2023-12-11 21:47
closing this out as per last few comments.

**Closed by bondydaa** 2023-12-11 21:47 UTC
Labels: Engineering, Daily, Overdue, Awaiting Payment, Bug
