### ISSUE TITLE
[HOLD for payment 2024-05-09] [$250] iOS - Start Chat - Offline indicator overlaps with navigation bar in Start chat list

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#40597] opened 2024-04-19 17:21 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.63-7
**Reproducible in staging?:** Y
**Reproducible in production?:** N
**If this was caught during regression testing, add the test name, ID and link from TestRail:** N/A
**Issue reported by:** Applause - Internal Team

## Action Performed:
1. Launch New Expensify app
2. Go to FAB > Start chat
3. Go offline

## Expected Result:
Offline indicator will not overlap with navigation bar

## Actual Result:
Offline indicator overlaps with navigation bar

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [x] iOS: Native
- [ ] iOS: mWeb Safari
- [ ] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details> 

![Bug6455127_1713545718946!IMG_3213](https://github.com/Expensify/App/assets/78819774/8b12ca32-5add-434b-90a0-883dcc592406)

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~011f820b0b52933326</li>
        <li>Upwork Job ID: 1781781063752663040</li>
        <li>Last Price Increase: 2024-04-20</li>
<li>Automatic offers: </li>
<ul>
<li>Krishna2323 | Contributor | 0</li>
</ul></li>
    </ul>
</details>

**Comment by lanitochka17** [comment] 2024-04-19 17:22
We think that this bug might be related to #vip-vsp

**Comment by lanitochka17** [comment] 2024-04-19 17:23
Production:

![img_2993_720](https://github.com/Expensify/App/assets/78819774/b6530b78-6b8e-4952-ada1-93cf2f02a2d7)

**Comment by srikarparsi** [comment] 2024-04-19 19:20
I believe this has to do with this [PR](https://github.com/Expensify/App/pull/38610/files). cc @Luke9389 @rushatgabhane. Is there a reason we don't use the shouldShowOfflineIndicator property in the outer [NewChatSelectorPage](https://github.com/Expensify/App/blob/cba5f033f18b2dd10e14d38fe7551c609deee544/src/pages/NewChatSelectorPage.tsx#L20).

**Comment by mountiny** [comment] 2024-04-20 20:24
We have to move ahead with this PR to get it CPed soon, I will assign @Krishna2323

**Comment by mountiny** [comment] 2024-04-20 20:26
Adding Rushat from the offending PR

**Comment by srikarparsi** [comment] 2024-04-21 18:57
Just left a comment @Krishna2323 but code changes look good to me.

**Comment by mountiny** [comment] 2024-04-21 21:31
Adding @allroundexperts for a quick pr review

@srikarparsi can you please merge and request CP once they are done and no problems found? thanks!

**Comment by srikarparsi** [comment] 2024-04-21 21:57
Yes will do :)

**Comment by srikarparsi** [comment] 2024-04-21 22:45
Merged and [requested CP](https://expensify.slack.com/archives/C07J32337/p1713739458369519) @mountiny

**Comment by mountiny** [comment] 2024-05-09 17:57
$250 to @Krishna2323 and to @allroundexperts

**Comment by sakluger** [comment] 2024-05-09 21:33
Summarizing payment on this issue:

Contributor: @Krishna2323 $250, paid via Upwork
Contributor+: @allroundexperts $250, please complete BZ checklist and request payment via Newdot

**Comment by allroundexperts** [comment] 2024-05-10 07:39
## Checklist

1. As mentioned by @srikarparsi, this is caused by https://github.com/Expensify/App/pull/38610
2. N/A
3. N/A
4. A regression test would be helpful. The steps given in the OP look clear enough to me.

**Comment by sakluger** [comment] 2024-05-10 16:39
Thanks! Closing.

**Closed by sakluger** 2024-05-10 16:39 UTC
Labels: Reviewing, External, Engineering, Daily, Awaiting Payment, Bug

**Comment by JmillsExpensify** [comment] 2024-06-28 17:47
$250 approved for @allroundexperts
