### ISSUE TITLE
[$1000] IOU - "you" string replaced with email if the characters are added after email

### ISSUE THREAD

**Issue by kavimuru** [Expensify/App#14099] opened 2023-01-06 23:15 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:

1. Open app.
2. Log-in into, for example, [abc@gmail.com](mailto:abc@gmail.com)
3. Create a new chat with abc@gmail.comElonMusk
4. Request any amount of money in the new chat

## Expected Result:
A string containing "Requested 1.00 from (actual email)"

## Actual Result:
A string containing "Requested 1.00 from youElonMusk"

## Workaround:
unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [ ] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 1.2.50-2
**Reproducible in staging?:** y 
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** 

https://user-images.githubusercontent.com/43996225/211115195-4a2225a0-0839-4e6d-991c-fdd0e1843119.mp4

https://user-images.githubusercontent.com/43996225/211115232-d06c9f13-6ed6-498c-bab1-c05e72856dcb.mov

**Expensify/Expensify Issue URL:**
**Issue reported by:** @oesayan
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1672998014125089

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01edd34880d6e24c55</li>
        <li>Upwork Job ID: 1612489201997221888</li>
        <li>Last Price Increase: 2023-01-09</li>
    </ul>
</details>

**Comment by NicMendonca** [comment] 2023-01-09 16:39
From the slack thread: 

> This issue may relate to the BE logic because when I turn off the internet, the FE still works correctly with IOU. However, after I turn on the internet, FE calls BE then the IOU is updated wrongly.

**Comment by priyeshshah11** [comment] 2023-01-09 17:10
> From the slack thread:
> 
> > This issue may relate to the BE logic because when I turn off the internet, the FE still works correctly with IOU. However, after I turn on the internet, FE calls BE then the IOU is updated wrongly.

@NicMendonca why is this External if it looks like it is coming from the backend? shouldn't it be Internal in that case?

**Comment by Santhosh-Sellavel** [comment] 2023-01-09 17:18
Tagging @Julesssss as you might have more context

**Comment by Julesssss** [comment] 2023-01-10 10:52
Error is possibly coming from here. Regardless, it needs to be internal.

**Comment by NicMendonca** [comment] 2023-01-19 18:32
hired @oesayan for reporting, thank you!

**Comment by abdulrahuman5196** [comment] 2023-01-19 18:51
@NicMendonca 


Would I be compensated for this https://github.com/Expensify/App/issues/14099#issuecomment-1375974868 as I was the first to root cause the issue and caused it to turn out internal?. I thought the process was to compensate, if the bug turns out to be internal depending on the analysis.

**Comment by NicMendonca** [comment] 2023-01-23 22:58
@abdulrahuman5196 there was an analysis happening in the [slack thread](https://expensify.slack.com/archives/C049HHMV9SM/p1672998014125089) prior to this GH being created

**Comment by techievivek** [comment] 2023-01-26 14:21
I think we can close this issue now, right? @NicMendonca

**Comment by NicMendonca** [comment] 2023-01-27 20:24
@oesayan you've been paid the reporting bonus - thanks!

**Closed by NicMendonca** 2023-01-27 20:24 UTC
Labels: Reviewing, Daily, Internal, Help Wanted, Bug
