### ISSUE TITLE
[$1000] Web -Chat -Changes made offline will not be saved after connecting to an internet connation, error message displayed

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#11126] opened 2022-09-19 22:36 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Navigate to http://staging.new.expensify.com/
2. Log in with your account
3. Sign in to an existing one or create one #Room
4. Disable the internet connection on the device
5. Click on the header of the #Room
5. Click Settings
6. In field "Notify me about new messages" select an option "Immediately" or "Mute"
8. Go back online
9. Refresh the page
10. Click on the header of the #Room
11. Click Settings

## Expected Result:
The changes made offline are still displayed after refreshing the page, no error messages.

## Actual Result:
Changes made offline will not be saved after connecting to an internet connection and an error message is displayed.

## Workaround:
Unknown

## Platform:

Where is this issue occurring?

- Web
- iOS
- Android
- Desktop App
- Mobile Web

**Version Number:** 1.2.2.0

**Reproducible in staging?:** Yes

**Reproducible in production?:** Yes

**Email or phone of affected tester (no customers):** any expensifail accounts

**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Notes/Photos/Videos:** Any additional supporting documentation

https://user-images.githubusercontent.com/93399543/191131346-93af82ad-2ede-4587-87b8-1728dc2f8748.mp4

**Expensify/Expensify Issue URL:** 

**Issue reported by:** Applause - Internal Team

**Slack conversation:** 

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by luacmartins** [comment] 2022-09-20 14:21
I can reproduce this. It seems like something [changes the value in Picker](https://github.com/Expensify/App/blob/971eb2fa3103c1153ae9348c067e432c3d4c4a9e/src/pages/ReportSettingsPage.js#L198-L204) and triggers two calls to [updateNotificationPreference](https://github.com/Expensify/App/blob/971eb2fa3103c1153ae9348c067e432c3d4c4a9e/src/libs/actions/Report.js#L1379-L1395), one with the new value and a second one with the old value. We need to identify what's triggering that second call and prevent it from happening.

**Comment by luacmartins** [comment] 2022-09-20 14:21
This can be external.

**Comment by luacmartins** [comment] 2022-09-23 16:29
Looking for proposals

**Comment by adelekennedy** [comment] 2022-09-23 23:07
[internal](https://www.upwork.com/ab/applicants/1573448917866233856/job-details)
[external](https://www.upwork.com/jobs/~0140799348fa63e0cc)

**Comment by getusha** [comment] 2022-09-24 05:02
The save Button is _specifically responsible_ for only changing the room name.
The notification preference gets updated when it is **picked**.

**Comment by luacmartins** [comment] 2022-09-26 18:02
@getusha correct! The issue here is that the notifications preference is reset when the user comes back online. I removed step 8 from the OP since it was unrelated as you pointed out!

**Comment by luacmartins** [comment] 2022-09-29 17:28
Still looking for proposals

**Comment by getusha** [comment] 2022-09-29 18:55
> Still looking for proposals

**Proposal**

Here is pseudo code
I approach this by using state.
first should check if the user is online
if user is online save the change
else set the change on pending 
user back online? save the change.

**Comment by parasharrajat** [comment] 2022-09-29 19:14
@getusha Please go through https://github.com/Expensify/App/blob/main/contributingGuides/CONTRIBUTING.md if you are new here. 

That proposal is unacceptable in its current state. A proposal should:
1. Explain the root cause. 
2. Show us, how you will solve it in **our app**.
3. It should fit into the codebase. 
4. Include technical details.

**Comment by adelekennedy** [comment] 2022-10-10 15:48
We're close to doubling again - @luacmartins @parasharrajat do we have a cap in mind for this issue?

**Comment by luacmartins** [comment] 2022-10-11 16:29
@adelekennedy no caps. Let's keep doubling until we get it fixed!

**Comment by tienifr** [comment] 2022-10-14 06:35
# Proposal


## Problem
I see this is BE bug. Even when online (don't disable network connection), this issue still display. As the below video, when I change `notificationPreferences`, it call API update successfully. But when I reload page, It call OpenAPI and the response from this API is wrong 


https://user-images.githubusercontent.com/113963320/195778502-a04a8e66-0877-4eab-bc27-494c1dbc937f.mp4



## Solution
Fix API in BE

**Comment by luacmartins** [comment] 2022-10-14 19:22
Thanks for the investigation. I'll take a look at our backend.

**Comment by adelekennedy** [comment] 2022-10-17 16:59
potentially a backend issue

**Comment by luacmartins** [comment] 2022-10-19 23:42
I'll take a look at this tomorrow!

**Comment by luacmartins** [comment] 2022-10-21 18:16
I think that this issue is related to https://github.com/Expensify/Expensify/issues/229696. The problem seems to be the order of events:

1. App comes back online and we trigger ReconnectApp
2. The server sends back the last know value, i.e. `Daily`. Since we had `Mute` saved locally, that value gets saved to Onyx and we add a `UpdateReportNotificationPreference` request with value `Daily` to the network queue
3. We trigger the `UpdateReportNotificationPreference` with value `Mute`, that was added to the network queue while we were offline
4. We trigger the `UpdateReportNotificationPreference` added to the queue in 2 and the value is set to `Daily`

As discussed in [this thread](https://expensify.slack.com/archives/C03TQ48KC/p1663797332998359), we should be triggering any write requests first, before any read requests.

@jasperhuangg are we tracking all issues that depend on this network queue sequence somewhere?

**Comment by mvtglobally** [comment] 2022-10-24 18:34
Issue not reproducible during KI retests. (First week)

**Comment by luacmartins** [comment] 2022-10-27 16:44
@adelekennedy thanks for bringing that up. That makes sense to me. I'll mark this as internal as well, since this will touch our API layer.

**Comment by luacmartins** [comment] 2022-10-31 14:46
I think this issue might be solved by https://github.com/Expensify/App/pull/12103. I'm demoting it to Weekly and will check once that PR is merged.

**Comment by luacmartins** [comment] 2022-11-03 19:59
The last PR was closed in favor of https://github.com/Expensify/App/pull/12219

**Comment by luacmartins** [comment] 2022-11-07 18:40
This is still failing but getting rid of the race condition surfaced the real issue. PR with fix [here](https://github.com/Expensify/Web-Expensify/pull/35480)

**Comment by adelekennedy** [comment] 2022-11-10 23:40
reassigning to you @johncschuster while I'm ooo!

**Comment by parasharrajat** [comment] 2022-11-16 00:00
Being worked internally.

**Comment by johncschuster** [comment] 2022-11-21 21:42
Thanks for the update, @mvtglobally!

**Comment by luacmartins** [comment] 2022-11-22 19:24
This has been on prod for 13 days now and it's no longer [reproducible](https://github.com/Expensify/App/issues/11126#issuecomment-1316189175). Closing the issue.

**Closed by luacmartins** 2022-11-22 19:24 UTC
Labels: Reviewing, Engineering, Daily, Internal, Bug
