### ISSUE TITLE
[HOLD for payment 2023-09-27] [$500] Chat - Emojis are selected when message is copied by selecting

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#26694] opened 2023-09-04 17:07 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Open any report
2. Send any text and add emojis
3. Copy text by double clicking and paste in composer

## Expected Result:
 Emojis should not be copied with text

## Actual Result:
Emojis are be copied with text

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [x] MacOS / Chrome / Safari
- [x] Windows / Chrome

**Version Number:** 1.3.63-0

**Reproducible in staging?:** Yes

**Reproducible in production?:** Yes

**If this was caught during regression testing, add the test name, ID and link from TestRail:**

**Email or phone of affected tester (no customers):**

**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/78819774/44af026f-1fdc-4643-9158-3f26a3751187

https://github.com/Expensify/App/assets/78819774/416987dd-b457-49e0-9842-5ee96dd04651

**Expensify/Expensify Issue URL:**

**Issue reported by:** @krishna2323

**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1693406411674209

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~0141e82a06a4ba237b</li>
        <li>Upwork Job ID: 1699027373879193600</li>
        <li>Last Price Increase: 2023-09-12</li>
<li>Automatic offers: </li>
<ul>
<li>0xmiroslav | Reviewer | 26659187</li>
<li>bernhardoj | Contributor | 26659189</li>
<li>krishna2323 | Reporter | 26659191</li>
</ul></li>
    </ul>
</details>

**Comment by MitchExpensify** [comment] 2023-09-05 11:51
Lets fix this!

**Comment by payal-lathidadiya** [comment] 2023-09-05 12:58
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
Chat - Emojis are selected when message is copied by selecting

### What is the root cause of that problem?
Couldn't really investigate the cause of this issue yet

### What changes do you think we should make in order to solve the problem?
Replace style of `userSelectNone` to `userSelectText` in `EmojiReactionBubble` component [here](https://github.com/Expensify/App/blob/main/src/components/Reactions/EmojiReactionBubble.js#L87-L88) while rendering emoji reaction element 

### What alternative solutions did you explore? (Optional)
None

**Comment by MitchExpensify** [comment] 2023-09-07 08:39
Bump on reviewing these proposal @0xmiroslav, thanks

**Comment by MitchExpensify** [comment] 2023-09-12 15:00
Bump @0xmiroslav 🙇

**Comment by Li357** [comment] 2023-09-13 18:54
Agreed, @bernhardoj all yours!

**Comment by MitchExpensify** [comment] 2023-09-21 00:04
**Payment summary:**

Reporter: $250 @Krishna2323 Upwork
C: $750 @bernhardoj Upwork
C+: $750 @0xmiroslav Upwork

Added a reminder to my cal to pay out

**Comment by MitchExpensify** [comment] 2023-09-29 05:31
Payment summary:

Reporter: $250 @Krishna2323 Upwork **PAID** 
C: $750 @bernhardoj Upwork - **PAID**
C+: $750 @0xmiroslav Upwork - Bump on BZ steps and accepting Upwork offer @0xmiroslav

**Comment by MitchExpensify** [comment] 2023-09-29 07:26
> Not sure @MitchExpensify already checked but you're luckily eligible for original price. 

I actually had not haha, thanks for doing that for me @0xmiroslav !

**Comment by MitchExpensify** [comment] 2023-10-03 00:57
Everyone is paid, no BZ steps needed, closing. Thanks, all!

**Closed by MitchExpensify** 2023-10-03 00:57 UTC
Labels: External, Daily, Overdue, Awaiting Payment, Bug
