### ISSUE TITLE
[$500] Chat - App adds emoji in wrong place on editing invite member message

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#27809] opened 2023-09-19 18:54 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Open the app
2. Open settings->workspaces->any workspace->members->invite
3. Select few users and continue
4. Add new lines in invite message and add some text after it
5. Invite the users
6. Open the new workspace chat with that user
7. Edit the invite message
8. Using emoji picker, insert any emoji and observe the location of inserted emoji is not in the end

## Expected Result:
App should insert emoji at the end of message while editing invite message

## Actual Result:
App inserts emoji at random location before the end of message while editing invite message

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android / native
- [x] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [x] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 1.3.71.8
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/93399543/b22687af-0a48-4c68-aa61-c4a19444de2c

https://github.com/Expensify/App/assets/93399543/afb9aa6f-157b-4b99-8d04-008896f84dbe

**Expensify/Expensify Issue URL:**
**Issue reported by:** @dhanashree-sawant
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1695119685609609

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01011d3dd991d38094</li>
        <li>Upwork Job ID: 1704207278295330816</li>
        <li>Last Price Increase: 2023-09-26</li>
<li>Automatic offers: </li>
<ul>
<li>ntdiary | Contributor | 26937729</li>
<li>dhanashree-sawant | Reporter | 26937731</li>
</ul></li>
    </ul>
</details>

**Comment by abdel-h66** [comment] 2023-09-19 19:38
## Proposal

### Please re-state the problem that we are trying to solve in this issue.

Emoji inserted in the wrong place when editing the Workspace invitiation note that contains line returns. 

### What is the root cause of that problem?

When adding new lines to the invitiation notes the text will be sent to the backend as 

`"You have been invited to Abdel's Worksp…ownload to start tracking your expenses.\r\n\r\n\r\n\r\nHello"`


### What changes do you think we should make in order to solve the problem?

The composer does not replace the  "\r\n\r\n\r\n\r\n" with "\n\n\n" which means that when we count the length of the draft we will get three characters more than what is actually visible. 

I suggest using originalDraft.replace(/\r\n/g, "\n") right before parsing the html to markdown here.

https://github.com/Expensify/App/blob/6d675529b2825b71c5c2bef332e7a07f0230c86f/src/pages/home/report/ReportActionItemMessageEdit.js#L97


### What alternative solutions did you explore? (Optional)

N/A

**Comment by kevinksullivan** [comment] 2023-09-21 06:40
Waiting on @ntdiary for a review of the above

**Comment by kevinksullivan** [comment] 2023-09-29 08:13
Hm weird that this is saying @ntdiary is eligible for internal. Going to try and get someone internal to check this.

**Comment by kevinksullivan** [comment] 2023-09-29 08:15
Alright, having @deetergp take a look at this 

https://github.com/Expensify/App/issues/27809#issuecomment-1736510888

**Comment by abdel-h66** [comment] 2023-09-29 08:39
Hey ! the comments from the bot are confusing 😄  is this going to be taken care of internally ?

**Comment by deetergp** [comment] 2023-10-02 19:31
To back up what @ntdiary has found, we are not doing anything additional to add `\r` unix like OSs use `\n` to slow line breaks but Windows machines use `\r` so browsers hedge their bets and use `\n\r` for line breaks, so it works across the board.

**Comment by deetergp** [comment] 2023-10-03 16:58
Yes, I think it's a moot point now. Let's close it.

**Closed** 2023-10-09 16:13 UTC
Labels: External, Engineering, Daily, Internal, Overdue, Bug
