### ISSUE TITLE
Web - Login - An error is displayed in the console when logging with magic link

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#23078] opened 2023-07-18 12:40 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___
**Issue found when executing PR** https://github.com/Expensify/App/pull/19850
## Action Performed:
1. Log in to the Expensify
2. Sign in using the magic link with an account with 2fa enabled
3. Verify that the tab open by the magic link works as usual
4. Repeat the steps 1-2 with an account with 2fa disabled

## Expected Result:
No errors should be displayed in console

## Actual Result:
Errors are displayed in the console

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [x] Windows / Chrome 
- [ ] MacOS / Desktop

**Version Number:** 1.3.42.0

**Reproducible in staging?:** Yes

**Reproducible in production?:** Yes

**If this was caught during regression testing, add the test name, ID and link from TestRail:**

**Email or phone of affected tester (no customers):**

**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/78819774/c7abcbf6-916b-44a3-94d2-920c8d792f04

**Expensify/Expensify Issue URL:**

**Issue reported by:** Applause Internal Team

**Slack conversation:**

**Comment by sakluger** [comment] 2023-07-18 18:26
It seems like even with the console errors, the user is able to log in without issue. I don't know if we need to prevent all console errors if the app is working fine, so I'm going to add the engineering label to get advice on whether this is actually something we need to fix.

**Comment by sakluger** [comment] 2023-07-20 16:25
@MariaHCD what do you think? Is this one a bug that we need to investigate, or is it okay to close since it's not impacting users at all?

**Comment by MariaHCD** [comment] 2023-07-21 07:28
It's a little hard to tell because this issue doesn't quite specify what the console error is. Couldn't quite catch it in the screen recording either. Will reproduce the issue.

**Comment by MariaHCD** [comment] 2023-07-21 07:35
Okay, tried on staging but I don't see any console errors besides `Unrecognized Content-Security-Policy directive 'prefetch-src'.` error which will be fixed [here](https://github.com/Expensify/Expensify/issues/298834), I believe.

<img width="1722" alt="Screenshot 2023-07-21 at 11 30 33 AM" src="https://github.com/Expensify/App/assets/12268372/5f2e5166-f340-417e-be16-e5c6acb762ce">

<img width="1721" alt="Screenshot 2023-07-21 at 11 30 56 AM" src="https://github.com/Expensify/App/assets/12268372/eb6b7267-4d2a-4c89-9c15-9e9a0d0740d7">

I don't see anything that's impacting users either so I think we're fine to #doNothing

**Closed by MariaHCD** 2023-07-21 07:35 UTC
Labels: Engineering, Daily, Bug
