### ISSUE TITLE
[HOLD for payment 2022-11-29] [$250] Workspace - Error message for invalid phone number invite disappears fast

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#12265] opened 2022-10-28 18:34 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___
**Issue found when executing PR** https://github.com/Expensify/App/pull/11784

## Action Performed:
1. Launch the app and login
2. Create 5 workspaces
3. Click on workspaces -> select a workspace -> manage members -> Turn on airplane mode
4. Invite user +25857527444 (this is an incorrect user and should throw error). Close settings.
5. Go back to online. Confirm you see error red dot on profile icon, click it.

## Expected Result:
Confirm you see error red dot next to the avatars and the UI still looks good.

## Actual Result:
Error message disappears too fast

## Workaround:
Unknown

## Platform:

Where is this issue occurring?

- Web
- iOS
- Android
- Desktop App
- Mobile Web

**Version Number:** 1.2.21.4

**Reproducible in staging?:** Yes

**Reproducible in production?:** Yes

**Email or phone of affected tester (no customers):** 

**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Notes/Photos/Videos:** Any additional supporting documentation

https://user-images.githubusercontent.com/93399543/198707896-8ce84da7-5aa1-43c5-8ba4-a34edc53635c.mp4

**Expensify/Expensify Issue URL:** 

**Issue reported by:** Applause - Internal Team

**Slack conversation:** 

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by flaviadefaria** [comment] 2022-11-08 12:27
Internal job posting - https://www.upwork.com/ab/applicants/1589957236115976192/job-details
External job posting - https://www.upwork.com/jobs/~018617c742041dfcfc

**Comment by s77rt** [comment] 2022-11-08 22:06
### Proposal
```diff
diff --git a/src/pages/workspace/WorkspaceMembersPage.js b/src/pages/workspace/WorkspaceMembersPage.js
index 477dc02f9..9a07e9a7a 100644
--- a/src/pages/workspace/WorkspaceMembersPage.js
+++ b/src/pages/workspace/WorkspaceMembersPage.js
@@ -73,7 +73,7 @@ class WorkspaceMembersPage extends React.Component {
     }
 
     componentDidMount() {
-        const clientMemberEmails = _.keys(this.props.policyMemberList);
+        const clientMemberEmails = _.keys(_.pick(this.props.policyMemberList, m => m.role));
         Policy.openWorkspaceMembersPage(this.props.route.params.policyID, clientMemberEmails);
     }
 
@@ -83,7 +83,7 @@ class WorkspaceMembersPage extends React.Component {
             return;
         }
 
-        const clientMemberEmails = _.keys(this.props.policyMemberList);
+        const clientMemberEmails = _.keys(_.pick(this.props.policyMemberList, m => m.role));
         Policy.openWorkspaceMembersPage(this.props.route.params.policyID, clientMemberEmails);
     }
```

### Explanation
Passing the whole clientMemberEmails object may contain keys which their corresponding values are just for show (ie. errors, pendingAction). When those keys get sent to the api, the api returns the found values and since they does not exists (as i said they are just for show) the api returns null. Then when merging, those "for show only" members get lost.
The proposed fix is only to pass members that have the "role" property (or not to pass those who have "pendingAction" and/or "errors" properties). This way the merging will be done on real members that exists and keep other for show only member untouched.

#### Pros/Cons?
The errors (red dot) will stay even after refreshing the page, it will only be dismissed if you close it manually or try to invite new members. IMHO, I think this is a desired behaviour, since you don't want to miss such errors anyway.

####  Action Performed
The reported actions are redundant (you don't need 5 workspaces). You can reproduce either by going offline/online or just closing the drawer and opening again.


https://user-images.githubusercontent.com/16493223/200685791-917f1c5c-215b-460a-9633-fe2b61c8fc48.mp4

**Comment by eVoloshchak** [comment] 2022-11-09 13:47
@s77rt's proposal looks good to me!

> The proposed fix is only to pass members that have the "role" property (or not to pass those who have "pendingAction" and/or "errors" properties).

I'm leaning more toward the first approach, since all accounts have the `role` property, while if we decide to filter out only items with `pendingAction` and `errors` properties, issues can arise in the future in case we add items with the new properties.

> The reported actions are redundant (you don't need 5 workspaces). You can reproduce either by going offline/online or just closing the drawer and opening again.

Can confirm this, the issue can be reproduced even while online and having only one workspace

🎀👀🎀 C+ reviewed!
cc: @jasperhuangg

**Comment by eVoloshchak** [comment] 2022-11-14 15:36
@jasperhuangg, what do you think about @s77rt's [proposal](https://github.com/Expensify/App/issues/12265#issuecomment-1307889721)?

**Comment by s77rt** [comment] 2022-11-15 20:05
Applied on Upwork.
[PR](12746) ready

**Comment by jasperhuangg** [comment] 2022-11-17 22:05
The PR for this issue is on staging! https://github.com/Expensify/App/pull/12746

**Comment by jasperhuangg** [comment] 2022-11-17 22:29
@flaviadefaria I think https://github.com/Expensify/App/pull/10395 is the source of this bug. 

Taking a look at the PR it doesn't include offline cases in its testing steps, which would have caught this before it was merged and deployed.

**Comment by eVoloshchak** [comment] 2022-11-21 08:25
Not overdue, PR was deployed to staging 4 days ago

**Comment by jasperhuangg** [comment] 2022-12-02 20:50
Hey @flaviadefaria were we able to get payment sorted out? Looks like it was scheduled for 2022-11-29, so I just wanted to double-check.

**Comment by flaviadefaria** [comment] 2022-12-05 17:30
I was checking on this with @mountiny as I didn't see the PR hit production. Got everything clarified and will process the payment now.

**Comment by flaviadefaria** [comment] 2022-12-05 18:47
@s77rt I got your message in Upwork. You do qualify for the 50% bonus, but this is added upon payment so first I need you to accept the job.

**Comment by eVoloshchak** [comment] 2022-12-05 18:50
> @s77rt I got your message in Upwork. You do qualify for the 50% bonus, but this is added upon payment so first I need you to accept the job so that I can proceed to payment.

Isn't the bonus applies to C+ also?

**Comment by s77rt** [comment] 2022-12-05 18:58
@flaviadefaria Accepted

**Comment by flaviadefaria** [comment] 2022-12-05 18:58
I'm not sure @eVoloshchak I'll double-check that for you.

**Comment by flaviadefaria** [comment] 2022-12-05 19:17
I just paid you both and the 50% bonus 👍

**Closed** 2022-12-05 19:28 UTC
Labels: Reviewing, External, Daily, Awaiting Payment, Bug
