### ISSUE TITLE
Web/Chrome - Broken emoji under Frequently used section 

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#9917] opened 2022-07-14 17:49 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/docs/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Go to staging.new.expensifail.com
2. Log in with applausetester+0901abb@applause.expensifail.com/ Feya86Katya
3.  Select Chat Kate Becciv and Click in Emoji

## Expected Result:
Correct emoji should be displayed

## Actual Result:
Broken emoji under Frequently used section 

## Workaround:
Unknown

## Platform:

Where is this issue occurring?

- Web
- iOS
- Android
- Desktop App
- Mobile Web

**Version Number:** 1.1.84.11

**Reproducible in staging?:**  Yes

**Reproducible in production?:** Yes

**Email or phone of affected tester (no customers):** applausetester+0901abb@applause.expensifail.com/ Feya87Katya

**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Notes/Photos/Videos:** Any additional supporting documentation
![Emojies](https://user-images.githubusercontent.com/93399543/179049348-67694922-9566-4d92-b746-0fea40f9f153.jpg)

**Expensify/Expensify Issue URL:** 

**Issue reported by:** Applause - Internal  Team

**Slack conversation:** 

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by Beamanator** [comment] 2022-07-15 09:08
I searched through my emojis and couldn't figure out which one that is - can you try to insert the broken one into a chat and then copy / paste it here maybe? 🤔

**Comment by kbecciv** [comment] 2022-07-15 12:15
@Beamanator Sorry, I was testing yesterday something and changed my password. Please try again this credentials:
applausetester+0901abb@applause.expensifail.com/Feya86Katya

**Comment by mvtglobally** [comment] 2022-07-15 23:03
Additional discussion here https://expensify.slack.com/archives/C01GTK53T8Q/p1657873845101639

**Comment by luacmartins** [comment] 2022-07-15 23:04
Likely caused by https://github.com/Expensify/Web-Expensify/pull/34210

**Comment by Beamanator** [comment] 2022-07-19 14:04
Hmm ok so I wonder if there **was** some weird bug but now it's fixed? I set my NVP to an empty array and now it seems it's working... I will ask around to see if others fix it with this - if so, I may write a CQ to clear out everyone's NVP (since our App is just in beta still)

**Comment by luacmartins** [comment] 2022-07-19 15:39
Well this PR was deployed 22h ago, which should have fixed this. In my initial implementation of `getUserDetails` I used Onyx `merge` instead of `set` as a method for frequently used emojis. That caused the array to be duplicated endlessly on each start / reconnect of the app 😅 I believe this was a front-end only issue, so a CQ shouldn't be necessary.

**Comment by Beamanator** [comment] 2022-07-28 19:02
Didn't get to this today, will look into it tomorrow or next week

**Comment by mvtglobally** [comment] 2022-08-02 04:03
Issue not reproducible during KI retests. (First week)

**Comment by luacmartins** [comment] 2022-08-02 19:26
I think we can close this. We didn't manage to repro last week!

**Comment by Beamanator** [comment] 2022-08-03 08:17
Yeah I agree, we can reopen if someone produces later 🤷

**Closed by Beamanator** 2022-08-03 08:17 UTC
Labels: Engineering, Weekly
