### ISSUE TITLE
[$500] IOU - Save button does not save and return to details page, only dismisses keyboard

### ISSUE THREAD

**Issue by izarutskaya** [Expensify/App#36218] opened 2024-02-09 10:32 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.39.0
**Reproducible in staging?:** Y
**Reproducible in production?:** N
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** Applause-Internal Team
**Slack conversation:**

## Action Performed:
Pre-requisite: the user must be logged in.

1. Go to any chat.
2. Initiate a manual money request, enter the amount.
3. On the details page, tap on "merchant" or "Description".
4. Enter any data.
5. Tap on the "Save" button.

## Expected Result:
After tapping on the "Save" button, the data should be saved and the user should be taken back to the request details.

## Actual Result:
After tapping on the "Save" button the keyboard is dismissed.

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [x] iOS: mWeb Safari
- [ ] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

https://github.com/Expensify/App/assets/115492554/f36922e4-997a-4da6-a45b-51707d7aace6

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01dac536754e07ef50</li>
        <li>Upwork Job ID: 1755902587474792448</li>
        <li>Last Price Increase: 2024-02-09</li>
    </ul>
</details>

**Comment by Julesssss** [comment] 2024-02-09 11:10
I just built that PR locally and I can't reproduce 😕  But I'll try once more from when it was merged to main
 
![Screenshot 2024-02-09 at 11 09 18](https://github.com/Expensify/App/assets/10736861/14eb9c8e-e1fd-45f6-b48b-67cbd24f3539)

**Comment by Julesssss** [comment] 2024-02-09 11:21
I actually can't reproduce this on `main`. I believe this has been fixed.

**Comment by situchan** [comment] 2024-02-09 11:23
This is reproducible on mSafari. After reverting https://github.com/Expensify/App/pull/34254 locally, not reproduced.

**Comment by Julesssss** [comment] 2024-02-09 11:25
Thanks, yeah was just able to repro on iOS mWeb. I thought it was just a case of not filling all the checkboxes 😭

**Comment by Julesssss** [comment] 2024-02-09 11:34
Okay, the workaround is simple (press the button again), so this isn't a blocker. I'll revert the PR when I have a moment, but won't cherry-pick it

**Comment by Julesssss** [comment] 2024-02-09 11:40
> Hey, i think the fix is straightforward we just need to add 'BUTTON' in tagNamesOpenKeyboard

Okay great, I'll close my revert if you'd like to raise the PR 👍

**Comment by Julesssss** [comment] 2024-02-09 11:42
Are they online though? I'd rather just get this resolved ASAP.

**Comment by Julesssss** [comment] 2024-02-09 11:43
Actually sure, we can wait a bit as we won't deploy today and it's no longer a blocker 👍

**Comment by Julesssss** [comment] 2024-02-12 09:33
Looks good @suneox thanks.

**Comment by DylanDylann** [comment] 2024-02-13 06:21
@Julesssss this is a regression from https://github.com/Expensify/App/pull/34254 , could you assign this issue to @shubham1206agra ? Or close this one and bring it to [the original issue](https://github.com/Expensify/App/issues/33546)

**Comment by jliexpensify** [comment] 2024-03-07 23:47
I think @shubham1206agra is still working on this?

**Closed** 2024-03-08 02:31 UTC
Labels: Reviewing, Engineering, Monthly, Bug
