### ISSUE TITLE
[$250] Android - IOU - From IOU report page, user deleting an IOU is directed to IOU details page

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#39939] opened 2024-04-09 13:45 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.61
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**If this was caught during regression testing, add the test name, ID and link from TestRail:** N/A
**Issue reported by:** Applause - Internal Team

## Action Performed:
1. Launch app
2. Tap on a 1:1 report with no prior conversation
3. Tap plus icon-- request money-- manual
4. Enter an amount and tap next
5. Tap request
6. Create another request performing step 3--step5
7. Tap on IOU preview and navigate to IOU report page
8. Long press the second IOU and delete the request

## Expected Result:
Long press the second IOU and deleting IOU request from IOU report page user must be directed to 1:1 conversation page

## Actual Result:
Long press the second IOU and deleting IOU request from IOU report page user is directed to IOU details page instead of 1:1 conversation page

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [ ] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details> 

https://github.com/Expensify/App/assets/78819774/a0d19238-e9c0-4a75-b509-87277eae6458

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~0149bcef5ff282e14b</li>
        <li>Upwork Job ID: 1779903278176915456</li>
        <li>Last Price Increase: 2024-04-22</li>
    </ul>
</details>

**Comment by lanitochka17** [comment] 2024-04-09 13:45
@sonialiap  FYI I haven't added the External label as I wasn't 100% sure about this issue. Please take a look and add the label if you agree it's a bug and can be handled by external contributors

**Comment by nkdengineer** [comment] 2024-04-12 19:43
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
- Android - IOU - From IOU report page, user deleting an IOU is directed to IOU details page
### What is the root cause of that problem?
- In [here](https://github.com/Expensify/App/blob/723d11dd3cfdd9927d83388d943e09565ba3350f/src/libs/actions/IOU.ts#L4175-L4186) we do not have a logic to navigate user to 1:1 DM if there is only one transaction after deleting a money request. 
### What changes do you think we should make in order to solve the problem?
- We can add the logic to the above:
```
    if (TransactionUtils.getAllReportTransactions(iouReportID).length === 2) {
        Navigation.goBack(ROUTES.REPORT_WITH_ID.getRoute(iouReport.chatReportID));
    }
```

### What alternative solutions did you explore? (Optional)
- NA

**Comment by sonialiap** [comment] 2024-04-15 16:03
Moving to external

**Comment by sonialiap** [comment] 2024-04-18 11:43
Looking for proposals

**Comment by nkdengineer** [comment] 2024-04-18 13:41
@rushatgabhane Do you have any feedback about my [proposal](https://github.com/Expensify/App/issues/39939#issuecomment-2052424626)?

**Comment by rushatgabhane** [comment] 2024-04-18 21:43
I think this is not a bug. It's expected behavior

**Comment by nkdengineer** [comment] 2024-04-23 03:19
@sonialiap Can you check this [comment](https://github.com/Expensify/App/issues/39939#issuecomment-2065374853) to confirm the expected behavior?

**Closed** 2024-04-23 11:22 UTC
Labels: External, Daily, Help Wanted, Overdue, Bug
