### ISSUE TITLE
[HOLD on 43641][$250] 'You' omitted after tracking expenses in self DM despite adding Display Name

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#43944] opened 2024-06-18 18:16 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.85-1
**Reproducible in staging?:** Y
**Reproducible in production?:** Y 
**If this was caught during regression testing, add the test name, ID and link from TestRail:** N/A 
**Email or phone of affected tester (no customers):** abebemiherat@gmail.com
**Issue reported by:** Applause - Internal Team

## Action Performed:
1. Go to self DM, click the plus sign
2. Choose Track Expense, add amount
3. Complete the flow
4. Go to profile, add Display Name. Note 'you' is omitted after adding Display Name

## Expected Result:
'You' should display even after adding Display Name

## Actual Result:
'You' is omitted after tracking expenses in self DM and adding Display Name

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [x] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details> 

https://github.com/Expensify/App/assets/78819774/a1fa8881-0f96-405c-86a4-37d0381c2efa

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01522e6d07d323336d</li>
        <li>Upwork Job ID: 1803455513921684291</li>
        <li>Last Price Increase: 2024-06-19</li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @sobitneupane</details>

**Comment by lanitochka17** [comment] 2024-06-18 18:16
@lschurr  FYI I haven't added the External label as I wasn't 100% sure about this issue. Please take a look and add the label if you agree it's a bug and can be handled by external contributors

**Comment by abzokhattab** [comment] 2024-06-19 08:54
I think this should be held until this issue is resolved: https://github.com/Expensify/App/issues/43641

**Comment by lschurr** [comment] 2024-06-19 15:51
@sobitneupane - do you agree we should hold? https://github.com/Expensify/App/issues/43944#issuecomment-2178133095

**Comment by sobitneupane** [comment] 2024-06-20 08:29
Yup @lschurr. This looks related to https://github.com/Expensify/App/issues/43641 issue and should probably be solved by the backend change being made in https://github.com/Expensify/App/issues/43641 issue.

**Comment by puneetlath** [comment] 2024-07-23 15:49
@lschurr are you sure this belongs in #newdot-quality? Is it a bug that happens consistently with reproducible steps?

**Comment by lschurr** [comment] 2024-07-23 16:12
Ah, let's see. It was on hold for https://github.com/Expensify/App/issues/43641 but that looks fixed now. @sobitneupane can you check?

**Comment by sobitneupane** [comment] 2024-07-25 16:00
@lschurr I could not reproduce the issue any longer.

**Comment by lschurr** [comment] 2024-07-25 18:04
Ok, going to close this one out since it's been fixed. I don't think there are any payments needed on this issue.

**Closed by lschurr** 2024-07-25 18:04 UTC
Labels: External, Monthly, Help Wanted, Bug
