### ISSUE TITLE
[HOLD for payment 2024-12-05] [$125] Wallet - No "Make default payment method" option after adding 2nd account

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#52641] opened 2024-11-15 17:56 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 9.0.63
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**If this was caught on HybridApp, is this reproducible on New Expensify Standalone?:** N/A
**If this was caught during regression testing, add the test name, ID and link from TestRail:** N/A
**Issue reported by:** Applause - Internal Team

**Issue found when executing PR** https://github.com/Expensify/App/pull/51437
## Action Performed:
1. Log in to the account that has no bank accounts
2. Navigate to Settings > Wallet and click on Add Bank Account > Personal Bank Account
3. On the Plaid modal, search and select Wells Fargo bank, enter credentials (e.g., user_good / pass_good), and complete the process
4. Verify that the added bank account is not marked as the default (because we are not showing default badge if there is only one bank account)
5. Repeat the process to add a second bank account by selecting Chase bank

## Expected Result:
The "Make default payment method" option is displayed in the three-dot menu of the first bank account added without needing a page refresh

## Actual Result:
The "Make default payment method" option is not displayed in the three-dot menu of the first bank account added after adding 2nd account. A page refresh is needed to display the option

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Standalone
- [ ] Android: HybridApp
- [x] Android: mWeb Chrome
- [ ] iOS: Standalone
- [ ] iOS: HybridApp
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

<details>
  <summary>Add any screenshot/video evidence</summary>

  
</details> 

https://github.com/user-attachments/assets/16e34de4-109c-449e-b5d7-a0066f07c196

![Bug6666585_1731691611180!Make_default_payment_method_-_After_refreshing](https://github.com/user-attachments/assets/e9abf478-c6ad-4a06-b2d0-b7d645918399)

![No_refresh](https://github.com/user-attachments/assets/a02a2c9a-8f8c-49e5-8cbc-81be3e210a6c)

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~021857547420122900843</li>
        <li>Upwork Job ID: 1857547420122900843</li>
        <li>Last Price Increase: 2024-11-15</li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @joekaufmanexpensify</details>

**Comment by joekaufmanexpensify** [comment] 2024-11-15 22:13
Reproduced

**Comment by joekaufmanexpensify** [comment] 2024-11-15 22:13
Pretty minor bug, so adjusting price

**Comment by Shahidullah-Muffakir** [comment] 2024-11-15 22:25
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
Make default payment method is not showing without refresh
### What is the root cause of that problem?
https://github.com/Expensify/App/blob/99bf5541f9d49da20952bd7f2592b7e773a6073b/src/pages/workspace/invoices/WorkspaceInvoiceVBASection.tsx#L57

this is causing the issue becausae the isSelectedPaymentMethodDefault is still true
### What changes do you think we should make in order to solve the problem?
we can add the same check here, as I added in my last PR here:https://github.com/Expensify/App/pull/51437
we need to use walletLinkedAccountID, and if the this paymnet is  isSelectedPaymentMethodDefault true
but the the account id does not mactch walletLinkedAccountID, then we should show Make default payment method

**Comment by nkdengineer** [comment] 2024-11-18 10:03
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
The "Make default payment method" option is not displayed in the three-dot menu of the first bank account added after adding 2nd account. A page refresh is needed to display the option

### What is the root cause of that problem?
The condition to show the `Default` badge and the condition to show `Make default payment method` are different

1. The condition to show the `Default` badge is based on `shouldShowDefaultBadge` which will return the most recent default method

https://github.com/Expensify/App/blob/b0378aad9ecb429db6983ba30255d1af0c9122c5/src/pages/settings/Wallet/PaymentMethodList.tsx#L421

2. While the condition to show the `Make default payment method` is based on `paymentMethod.isDefault` which can be wrong after we add the 2nd account. The context can see [here](https://github.com/Expensify/App/issues/50829)
https://github.com/Expensify/App/blob/b0378aad9ecb429db6983ba30255d1af0c9122c5/src/pages/settings/Wallet/PaymentMethodList.tsx#L333

https://github.com/Expensify/App/blob/b0378aad9ecb429db6983ba30255d1af0c9122c5/src/pages/settings/Wallet/WalletPage/WalletPage.tsx#L172

https://github.com/Expensify/App/blob/b0378aad9ecb429db6983ba30255d1af0c9122c5/src/pages/settings/Wallet/WalletPage/WalletPage.tsx#L317-L319
### What changes do you think we should make in order to solve the problem?
We should also use `shouldShowDefaultBadge` function to check if this `paymentMethod` is default or not

```
const finalCombinedPaymentMethods = combinedPaymentMethods.map((paymentMethod) => {
    const isMethodActive = isPaymentMethodActive(actionPaymentMethodType, activePaymentMethodID, paymentMethod);
    const isDefault = shouldShowDefaultBadge(
        combinedPaymentMethods,
        paymentMethod,
        userWallet?.walletLinkedAccountID ?? 0,
        invoiceTransferBankAccountID ? invoiceTransferBankAccountID === paymentMethod.methodID : paymentMethod.isDefault,
    );
    return {
        ...paymentMethod,
        onPress: (e: GestureResponderEvent) =>
            onPress(
                ...
                isDefault,
                paymentMethod.methodID,
            ),
        ...
    };
});
return finalCombinedPaymentMethods;
```


https://github.com/Expensify/App/blob/b0378aad9ecb429db6983ba30255d1af0c9122c5/src/pages/settings/Wallet/PaymentMethodList.tsx#L333
### What alternative solutions did you explore? (Optional)

**Comment by Shahidullah-Muffakir** [comment] 2024-11-20 00:04
> @nkdengineer's [proposal](https://github.com/Expensify/App/issues/52641#issuecomment-2482498437) is simpler. Let's go with them.
> 
> 🎀 👀 🎀 C+ reviewed

@thesahindia, I believe the selected proposal might not work as intended because `shouldShowDefaultBadge` and `isDefault` can represent different scenarios.

For example, add the fist payment method, we don't show the default badge for it. However, with the current proposal, the `Make default payment method` option would still appear for this method, which is not the expected behavior.

**Comment by joekaufmanexpensify** [comment] 2024-11-21 13:17
@Shahidullah-Muffakir Is there an eta for a PR here?

**Comment by Shahidullah-Muffakir** [comment] 2024-11-21 13:20
> @Shahidullah-Muffakir Is there an eta for a PR here?

The PR will be ready within few hrs.

**Comment by joekaufmanexpensify** [comment] 2024-11-21 13:22
TY!

**Comment by Shahidullah-Muffakir** [comment] 2024-11-21 20:14
@joekaufmanexpensify I noticed a similar issue in Prod and Staging:

When a user has two payment methods and deletes their default payment method, the "Make default payment method" button still shows for the remaining payment method until the page is refreshed.

I believe we should hide this button immediately after deletion (without requiring a refresh) since it's now the only payment method. Is this the correct behavior we want?

**Comment by Shahidullah-Muffakir** [comment] 2024-11-22 17:23
@thesahindia, [PR](https://github.com/Expensify/App/pull/52971) is ready for review, Thank you.

**Comment by joekaufmanexpensify** [comment] 2024-11-25 16:30
PR in review

**Comment by joekaufmanexpensify** [comment] 2024-12-02 15:49
@thesahindia could you handle checklist so we can prep to pay?

**Comment by joekaufmanexpensify** [comment] 2024-12-02 15:50
@Shahidullah-Muffakir offer sent for $125!

**Comment by joekaufmanexpensify** [comment] 2024-12-06 16:11
Consolidated regression test into https://github.com/Expensify/Expensify/issues/447939

**Comment by joekaufmanexpensify** [comment] 2024-12-06 16:13
Payment summary above is correct. All set to issue payment!

**Comment by joekaufmanexpensify** [comment] 2024-12-06 16:13
@Shahidullah-Muffakir $125 sent and contract ended!

**Comment by joekaufmanexpensify** [comment] 2024-12-06 16:14
@thesahindia please request payment in NewDot at your earliest convenience. Closing as this is otherwise all set!

**Closed by joekaufmanexpensify** 2024-12-06 16:14 UTC
Labels: External, Daily, Awaiting Payment, Bug

**Comment by garrettmknight** [comment] 2024-12-21 13:59
$125 approved for @thesahindia
