### ISSUE TITLE
[HOLD for C+ payment via Newdot] [$500] Dev:  mWeb - Offline message not positioned at bottom in private notes

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#27590] opened 2023-09-16 18:28 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Create a  workspace if not created
2. Go to #admins
3. Click on header
4. Go to Private notes
5. Go offline

## Expected Result:
Offline message should be positioned at bottom

## Actual Result:
Offline message not positioned at bottom

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [x] iOS / Safari
- [ ] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** Dev 1.3.70.5
**Reproducible in staging?:** no
**Reproducible in production?:** no
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/93399543/9ab25688-510f-49d6-acb8-6e7355a6a137

**Expensify/Expensify Issue URL:**
**Issue reported by:** @gadhiyamanan 
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1694784028569909

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~018108637756bc0d66</li>
        <li>Upwork Job ID: 1703113660113563648</li>
        <li>Last Price Increase: 2023-09-23</li>
<li>Automatic offers: </li>
<ul>
<li>dhairyasenjaliya | Contributor | 26884984</li>
<li>gadhiyamanan | Reporter | 26884986</li>
</ul></li>
    </ul>
</details>

**Comment by ahmedGaber93** [comment] 2023-09-16 18:28
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
 offline message not positioned at bottom in private notes
### What is the root cause of that problem?
The page content not wrapped with `<View style={[styles.flexGrow1]}>` so not fit the available screen height
https://github.com/Expensify/App/blob/76c1559fb3fbee1d07c8f210b522b63edd03920e/src/pages/PrivateNotes/PrivateNotesListPage.js#L131-L135
### What changes do you think we should make in order to solve the problem?
we need this wrap this  content with  `<View style={[styles.flexGrow1]}>` or at leatest `_.map`
https://github.com/Expensify/App/blob/76c1559fb3fbee1d07c8f210b522b63edd03920e/src/pages/PrivateNotes/PrivateNotesListPage.js#L131-L135

### What alternative solutions did you explore? (Optional)
N/A

**Comment by kadiealexander** [comment] 2023-09-20 05:52
@eVoloshchak any thoughts on the proposal above?

**Comment by eVoloshchak** [comment] 2023-09-21 14:01
I think we should proceed with @dhairyasenjaliya's [proposal](https://github.com/Expensify/App/issues/27590#issuecomment-1722290129)

The point about the page needing `ScrollView` is absolutely correct, currently if there are more notes that can fit into a screen, there is no way to scroll them
Good job spotting that @dhairyasenjaliya!

🎀👀🎀 C+ reviewed!

**Comment by eVoloshchak** [comment] 2023-09-23 17:48
Not overdue, waiting on @marcochavezf's review of [this](https://github.com/Expensify/App/issues/27590#issuecomment-1729649166)

**Comment by kadiealexander** [comment] 2023-10-10 04:37
Payouts due:

Issue Reporter: $50 @gadhiyamanan 
Contributor: $500 @dhairyasenjaliya
Contributor+: $500 @eVoloshchak

Eligible for 50% #urgency bonus? [Yes](https://github.com/Expensify/App/issues/27590#issuecomment-1738381036)

Upwork job is [here](https://www.upwork.com/jobs/~018108637756bc0d66).

**Comment by kadiealexander** [comment] 2023-10-10 04:42
**BugZero Checklist:** The PR fixing this issue has been merged! The following checklist ([instructions](https://stackoverflow.com/c/expensify/questions/14574)) will need to be completed before the issue can be closed:

- [ ] [@eVoloshchak] The PR that introduced the bug has been identified. Link to the PR:
- [ ] [@eVoloshchak] The offending PR has been commented on, pointing out the bug it caused and why, so the author and reviewers can learn from the mistake. Link to comment:
- [ ] [@eVoloshchak] A discussion in #expensify-bugs has been started about whether any other steps should be taken (e.g. updating the PR review checklist) in order to catch this type of bug sooner. Link to discussion:
- [ ] [@eVoloshchak] Determine if we should create a regression test for this bug.
- [ ] [@eVoloshchak] If we decide to create a regression test for the bug, please propose the [regression test](https://github.com/Expensify/App/blob/main/contributingGuides/REGRESSION_TEST_BEST_PRACTICES.md) steps to ensure the same bug will not reach production again.
- [ ] [@kadiealexander] Link the GH issue for creating/updating the regression test once above steps have been agreed upon:

**Comment by eVoloshchak** [comment] 2023-10-11 17:56
**Regression Test Proposal**

1. Create a workspace if not created
2. Go to #admins
3. Click on header
4. Go to Private notes
5. Turn off internet connection
6. Verify that offline indicator is be displayed at the bottom of the page

**Do we agree 👍 or 👎**

**Comment by eVoloshchak** [comment] 2023-10-11 17:57
>  Contributor: $500 @dhairyasenjaliya
 Contributor+: $500 @eVoloshchak
 
 @kadiealexander, shouldn't it be $750 if the bonus is applied?

**Comment by kadiealexander** [comment] 2023-10-17 03:19
Updated.

**Comment by eVoloshchak** [comment] 2023-10-17 13:04
Thanks!
Requested the payment

**Comment by JmillsExpensify** [comment] 2023-10-18 18:45
$750 payment approved for @eVoloshchak based on correct BZ summary.

**Comment by eVoloshchak** [comment] 2023-10-30 09:40
@kadiealexander, this one can be closed I think

**Closed** 2023-10-31 04:27 UTC
Labels: External, Monthly, Awaiting Payment
