### ISSUE TITLE
[$500] [HOLD for payment 2023-11-22] [HOLD for payment 2023-11-21] Workspace - App crashes when opening Bank account page

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#31188] opened 2023-11-10 17:04 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.3.98.0
**Reproducible in staging?:** y
**Reproducible in production?:** n
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** Applause - Internal Team
**Slack conversation:**

**Issue found when executing PR** https://github.com/Expensify/App/pull/29166

## Action Performed:
Precondition: The workspace should have currency other than USD.

1. Navigate to staging.new.expensify.com
2. Go to Settings > Workspaces > any workspace.
3. Go to Reimbursements.
4. Under "Unlock next-day reimbursements" section click Connect Bank Account.

## Expected Result:
App does not crash.

## Actual Result:
App crashes.

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [x] Android: mWeb Chrome
- [x] iOS: Native
- [x] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

https://github.com/Expensify/App/assets/93399543/f89a05fe-b6f6-4e88-8781-aae5090a3747

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01812bb71e787b4913</li>
        <li>Upwork Job ID: 1727448941019639808</li>
        <li>Last Price Increase: 2023-11-22</li>
    </ul>
</details>

**Comment by NikkiWines** [comment] 2023-11-10 18:09
@kbecciv looks like that reproduction video doesn't show a crash? Just an error message (albeit without standard styling) about currency 

I'm unable to reproduce the issue on staging

https://github.com/Expensify/App/assets/16747822/a0da640f-a14f-45bd-add4-8da685b73be2

Testing on dev next

**Comment by kbecciv** [comment] 2023-11-10 18:13
@NikkiWines Just uploaded correct one, can you please again, the default workspace currency should not be USD.

**Comment by NikkiWines** [comment] 2023-11-10 18:47
Thanks! Was able to reproduce on web + staging

**Comment by NikkiWines** [comment] 2023-11-10 19:03
Yes, definitely tied to the changes in https://github.com/Expensify/App/pull/29166. It looks like we're using `TextInput` when we should be using `Text` due to a wonky import 
```
import Text from '@components/TextInput';
```

![image](https://github.com/Expensify/App/assets/16747822/3c375b7a-1f3c-4e78-bda8-51f82e138bd7)

**Comment by NikkiWines** [comment] 2023-11-10 19:14
PR is up and in review: https://github.com/Expensify/App/pull/31201

**Comment by NikkiWines** [comment] 2023-11-10 20:37
Fix has resolved the issue on staging 🎊 

https://github.com/Expensify/App/assets/16747822/9dbb4881-c36e-4192-9c52-0ef9bb6ac27d

**Comment by NikkiWines** [comment] 2023-11-10 22:26
We ended up doing a larger revert of https://github.com/Expensify/App/pull/29166 due to another blocker (https://github.com/Expensify/App/issues/31212) so ended up reverting https://github.com/Expensify/App/pull/31201 as well. 

Going to add the `bug` label and assign @situchan though because they reviewed https://github.com/Expensify/App/pull/31201 and need to be issued payment for that.

**Comment by NikkiWines** [comment] 2023-11-10 22:27
@johncschuster can we please issue payment to @situchan for reviewing https://github.com/Expensify/App/pull/31201 please 🙇 thank you!

**Comment by johncschuster** [comment] 2023-11-22 22:10
Sorry I missed your comment above, @NikkiWines! I've just invited @situchan to the job.

@situchan, can you ping me here when you've accepted that so I can issue payment? Thank you!

**Comment by johncschuster** [comment] 2023-11-29 01:14
Payment has been issued. Thanks, @situchan!

**Comment by NikkiWines** [comment] 2023-12-04 20:14
I think we can close this out now. Feel free to re-open/comment if there's anything outstanding

**Closed by NikkiWines** 2023-12-04 20:14 UTC
Labels: External, Engineering, Daily, Help Wanted, Overdue, Awaiting Payment, Bug
