### ISSUE TITLE
[$500] Request - App allows to add receipt in manual request using edit receipt URL and removes the receipt image after process

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#28176] opened 2023-09-25 17:08 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
Action Performed:
1. Open the app
2. Click on plus and click request money
3. Click on manual and complete the process with any amount and any user
4. Open request money page by clicking twice on request money message
5. Copy the URL and paste on current or in any report
6. Add '/edit/receipt' in the end of URL and send the message
7. Click on the URL
8. Add a very large image file (like the one found [here](https://expensify.slack.com/archives/C049HHMV9SM/p1695985271292299?thread_ts=1695449840.605019&cid=C049HHMV9SM)). 
9. Observe that image is displayed, go back to parent report and observe now that app has removed the image

## Expected Result:
App should not remove the image after edit receipt

## Actual Result:
App allows user to edit receipt of manual request and after adding receipt image, it removes the image on visiting parent report

## Workaround:
Unknown 

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [x] Android / Chrome
- [ ] iOS / native
- [x] iOS / Safari
- [x] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 1.3.74.0
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/93399543/7462dfb8-27a7-40cf-b3da-9e9d624bac08

https://github.com/Expensify/App/assets/93399543/853d0d00-d078-4999-baf6-fd5804b02413

**Expensify/Expensify Issue URL:**
**Issue reported by:** @dhanashree-sawant
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1695449840605019
 
[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~0108e8d188bb6fabe4</li>
        <li>Upwork Job ID: 1706355034003038208</li>
        <li>Last Price Increase: 2023-10-16</li>
    </ul>
</details>

**Comment by joh42** [comment] 2023-09-25 18:02
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
It is possible to add a receipt to IOUs that are not distance requests.
### What is the root cause of that problem?
There is no logic preventing receipts from being added to non-distance request IOUs.
### What changes do you think we should make in order to solve the problem?

I suggest we show the [NotFoundPage](https://github.com/Expensify/App/blob/main/src/pages/ErrorPage/NotFoundPage.js) in case the [EditRequestReceiptPage](https://github.com/Expensify/App/blob/main/src/pages/EditRequestReceiptPage.js) is opened for IOUs that are not distance requests.

This can be done by:
1. Wrapping the [EditRequestReceiptPage](https://github.com/Expensify/App/blob/main/src/pages/EditRequestReceiptPage.js) in withOnyx, and getting the transaction
2. Checking if the transaction is a distance request using the [isDistanceRequest util](https://github.com/Expensify/App/blob/main/src/libs/TransactionUtils.js#L295)
3. Showing the [NotFoundPage](https://github.com/Expensify/App/blob/main/src/pages/ErrorPage/NotFoundPage.js) for IOUs that are not distance requests
### What alternative solutions did you explore? (Optional)

**Comment by joh42** [comment] 2023-09-25 19:42
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
It is possible to add a receipt to transactions that are not receipt requests by going to the [EditRequestReceiptPage](https://github.com/Expensify/App/blob/main/src/pages/EditRequestReceiptPage.js).
### What is the root cause of that problem?
There is no logic preventing receipts from being added to non-receipt requests.
### What changes do you think we should make in order to solve the problem?

I suggest we block the [EditRequestReceiptPage](https://github.com/Expensify/App/blob/main/src/pages/EditRequestReceiptPage.js) for requests that do not already have a receipt (you can't edit something that doesn't exist after all). This can be done either by showing 404, or adding a custom [BlockingView](https://github.com/Expensify/App/blob/main/src/components/BlockingViews/BlockingView.js), perhaps looking something like this:
![image](https://github.com/Expensify/App/assets/138504087/7e380449-0e69-4f8c-8229-2c00e399cdaf)

This can be done by:
1. Wrapping the [EditRequestReceiptPage](https://github.com/Expensify/App/blob/main/src/pages/EditRequestReceiptPage.js) in `withOnyx`, and getting the transaction (we already have the transactionID)
2. Checking if the `transaction.receipt` property is empty
3. If it is, we either show a [BlockingView](https://github.com/Expensify/App/blob/main/src/components/BlockingViews/FullPageNotFoundView.js) looking something like in the example above or show the [FullPageNotFoundView](https://github.com/Expensify/App/blob/main/src/components/BlockingViews/FullPageNotFoundView.js) or [NotFoundPage](https://github.com/Expensify/App/blob/main/src/pages/ErrorPage/NotFoundPage.js) (I think the former, please correct me if I'm wrong)
### What alternative solutions did you explore? (Optional)
While this approach would be suboptimal IMO, we could also just navigate back to the previous page. The logic would be the same as in the main solution suggested above, but instead of blocking the  [EditRequestReceiptPage](https://github.com/Expensify/App/blob/main/src/pages/EditRequestReceiptPage.js) in step 3, we navigate back.

**Comment by joekaufmanexpensify** [comment] 2023-09-28 08:53
I can't reproduce this. Discussing [here. ](https://expensify.slack.com/archives/C049HHMV9SM/p1695891185069599?thread_ts=1695449840.605019&cid=C049HHMV9SM)

**Comment by joekaufmanexpensify** [comment] 2023-09-29 07:49
Still can't reproduce. Discussing further.

**Comment by joekaufmanexpensify** [comment] 2023-10-02 20:09
Catching up from travel today. Will continue determining whether to proceed further here tomorrow

**Comment by joekaufmanexpensify** [comment] 2023-10-03 21:20
Still need to look into this further

**Comment by joekaufmanexpensify** [comment] 2023-10-06 17:49
I was able to reproduce this with the 12 MB image. So we can proceed with looking for proposals for now.

**Comment by joekaufmanexpensify** [comment] 2023-10-06 17:54
I also updated the expected behavior to clarify that we should not remove the receipt here. It is possible to add a receipt to a manual request (via the three dot overflow menu in the top right corner). So I don't see why we'd disallow editing the URL to do this (since that does the same thing as using the overflow menu).

**Comment by cubuspl42** [comment] 2023-10-09 07:31
@joekaufmanexpensify Thanks for the updates!

@joh42 Do you still reproduce the issue? Have you tested your solution with small/big image sizes, as we have a lead that this might be relevant?

**Comment by cubuspl42** [comment] 2023-10-09 07:40
@joekaufmanexpensify Thanks for the updates!

@joh42 As there is doubt whether this is easily reproducible, could I ask you to verify that you can still reproduce this?

In the root cause analysis section, would you include whether this is a front-end-only issue or whether the image reaches the backend and persists?

Commenting on the solution, is there any legitimate way to reach such a custom blocking view with a new copy? Because if not, I don't think that adding new copy (and translating it to other languages) makes sense.

**Comment by joh42** [comment] 2023-10-09 14:32
@cubuspl42 since the expected behavior has been clarified to allow images to be added to manual requests, I do not think my proposal contains the correct solution.

I think there is a high probability that this is a backend issue, but I have not looked into it further.

**Comment by cubuspl42** [comment] 2023-10-10 08:39
@joh42 Actually, would you elaborate on _why_ your proposal doesn't contain a correct solution?

> I suggest we block the [EditRequestReceiptPage](https://github.com/Expensify/App/blob/main/src/pages/EditRequestReceiptPage.js) for requests that do not already have a receipt

This sounds fine; what's the blocker to implement this?

I'm not saying that there's nothing to be done on the backend, but we shouldn't display the "Upload receipt" UI to begin with for non-receipt requests, am I wrong?

**Comment by joh42** [comment] 2023-10-10 12:10
@cubuspl42 I thought that the BugZero member meant that we should not block receipts from being added:

> I also updated the expected behavior to clarify that we should not remove the receipt here. It is possible to add a receipt to a manual request (via the three dot overflow menu in the top right corner). _So I don't see why we'd disallow editing the URL_ to do this (since that does the same thing as using the overflow menu).

IE it's possible to get to the /edit/receipt page by clicking here:

![image](https://github.com/Expensify/App/assets/138504087/0542bb4f-292a-4489-9b85-3282c7a73b33)

Not just by editing the url

**Comment by cubuspl42** [comment] 2023-10-11 08:26
@joekaufmanexpensify So everything works fine when we enter the mentioned screen via the button, but the receipt image is seemingly "rejected" if we enter the route by typing the URL manually?

**Comment by joekaufmanexpensify** [comment] 2023-10-11 19:51
Yeah, that is my understanding.

**Comment by joekaufmanexpensify** [comment] 2023-10-16 14:29
@cubuspl42 are we close to being able to accept a proposal here?

**Comment by cubuspl42** [comment] 2023-10-17 09:24
The main issue here is that big images are rejected by the back-end with an error, no matter if we add them in the "clean" way, in the "Scan" tab, or via the "Add Receipt" button the URL editing (`/edit/receipt`).

There might be something to do on the front-end side here, for example, displaying a clean error "The receipt file is too big", but we still need to coordinate with the back-end.

C+ reviewed 🎀 👀 🎀

**Comment by cubuspl42** [comment] 2023-10-17 09:25
@joelbettner

Would you share your opinion here, and help us figure our what should be done on the backend, so we can later go back and see if there's anything to do on the frontend?

**Comment by joekaufmanexpensify** [comment] 2023-10-18 20:22
still pending input from @joelbettner

**Comment by joekaufmanexpensify** [comment] 2023-10-20 15:52
@joelbettner mind taking a look at this one?

**Comment by joekaufmanexpensify** [comment] 2023-10-23 13:52
Bumped joel 1:1

**Comment by joelbettner** [comment] 2023-10-23 19:08
> The main issue here is that big images are rejected by the back-end with an error, no matter if we add them in the "clean" way, in the "Scan" tab, or via the "Add Receipt" button the URL editing (/edit/receipt).

If the backend is rejecting a file because it is too large, we are going to continue to do so. We just need to handle that error on the front end gracefully and let the user know that the file was too large.

Are you seeing what the error is that was returned from the back end?

**Comment by joh42** [comment] 2023-10-23 20:00
@joelbettner the weird thing is that there is already frontend validation checking the file size of receipts:
https://github.com/Expensify/App/blob/3e94d84ad33e284cc964b001c5ceaa03d1d59331/src/pages/iou/ReceiptSelector/index.js#L111

Could the value used there be different from the actual backend max file size?

Specifically, the value used is the same that is used for attachments generally - could the max file size for receipts be different? The value for all attachments has not been updated in roughly a year:
https://github.com/Expensify/App/blob/3e94d84ad33e284cc964b001c5ceaa03d1d59331/src/CONST.ts#L47-L49

If that's the case, I've updated my [proposal](https://github.com/Expensify/App/issues/28176#issuecomment-1734357492)

**Comment by luacmartins** [comment] 2023-10-24 17:06
@joelbettner it seems like some of those requestIDs are to process the `Log` API request and `ReplaceReceipt` just happened to be in the payload and the 2 calls to ReplaceReceipt seem to be distinct given they are 21min apart. So from the logs you linked above I see:

Log API command
- [81ac65823a7927e6-SEA](https://www.expensify.com/_devportal/tools/logSearch/#query=request_id:(%2281ac65823a7927e6-SEA%22)+AND+timestamp:[2023-10-23T18:30:46.934Z+TO+2023-10-23T20:30:46.934Z]&index=logs_expensify-024935)
- [81ac80806aef27e6-SEA](https://www.expensify.com/_devportal/tools/logSearch/#query=request_id:(%2281ac80806aef27e6-SEA%22)+AND+timestamp:[2023-10-23T18:49:12.649Z+TO+2023-10-23T20:49:12.649Z]&index=logs_expensify-024935)
- [81ac80c92bbe27e6-SEA](https://www.expensify.com/_devportal/tools/logSearch/#query=request_id:(%2281ac80c92bbe27e6-SEA%22)+AND+timestamp:[2023-10-23T18:49:24.111Z+TO+2023-10-23T20:49:24.111Z]&index=logs_expensify-024935)
- [81ac65823a7927e6-SEA](https://www.expensify.com/_devportal/tools/logSearch/#query=request_id:(%2281ac65823a7927e6-SEA%22)+AND+timestamp:[2023-10-23T18:30:46.936Z+TO+2023-10-23T20:30:46.936Z]&index=logs_expensify-024935)

ReplaceReceipt
- [81ac611dbd7f27e6-SEA](https://www.expensify.com/_devportal/tools/logSearch/#query=request_id:(%2281ac611dbd7f27e6-SEA%22)+AND+timestamp:[2023-10-23T18:28:54.747Z+TO+2023-10-23T20:28:54.747Z]&index=logs_expensify-024934)
- [81ac7f1aad2827e6-SEA](https://www.expensify.com/_devportal/tools/logSearch/#query=request_id:(%2281ac7f1aad2827e6-SEA%22)+AND+timestamp:[2023-10-23T18:49:22.173Z+TO+2023-10-23T20:49:22.173Z]&index=logs_expensify-024935)

You could try searching for `blob:"Called API write ~~ command: 'ReplaceReceipt'"` to make sure you're getting only the actual calls to the command

**Comment by joekaufmanexpensify** [comment] 2023-10-24 20:18
Still pending further discussion on the solution

**Comment by joekaufmanexpensify** [comment] 2023-10-26 14:31
@joelbettner @cubuspl42 curious if we think we'll be able to proceed with a proposal here soon?

**Comment by joelbettner** [comment] 2023-10-26 22:11
It looks like we are defaulting this to allow 10MB images to be uploaded, here:
https://github.com/Expensify/Web-Expensify/blob/dbef7bf642d6f6c2b1fd32d20bbe742ffdfc6e99/lib/ReceiptAPI.php#L1087
https://github.com/Expensify/Web-Expensify/blob/dbef7bf642d6f6c2b1fd32d20bbe742ffdfc6e99/lib/FileUtils.php#L246
https://github.com/Expensify/Web-Expensify/blob/dbef7bf642d6f6c2b1fd32d20bbe742ffdfc6e99/lib/FileUtils.php#L281

I will update this section of the backend to make sure we are in line with what the front end is currently allowing.
Instead of 10 mb (10485760 bytes) I'll make it 24 mb (25165824).

**Comment by joelbettner** [comment] 2023-10-26 22:24
Fix PR is there^.

**Comment by joekaufmanexpensify** [comment] 2023-10-27 14:34
Chatted with Joel, and his PR above fixed this, so no further action is needed here. We just need to pay out the reporting bonus, and we'll be all set to close this one the PR is deployed.

**Comment by joekaufmanexpensify** [comment] 2023-10-27 14:36
Original upwork job closed. New one [here. ](https://www.upwork.com/jobs/~01232d79b160a9d5be)

**Comment by joekaufmanexpensify** [comment] 2023-10-27 14:37
@dhanashree-sawant offer sent for $50!

**Comment by dhanashree-sawant** [comment] 2023-10-28 13:14
Thanks @joekaufmanexpensify, I have accepted the offer.

**Comment by joekaufmanexpensify** [comment] 2023-11-06 16:17
@dhanashree-sawant $50 sent and contract ended!

**Comment by joekaufmanexpensify** [comment] 2023-11-06 16:18
Bug is fixed, and all payment issued. Closing!

**Closed by joekaufmanexpensify** 2023-11-06 16:18 UTC
Labels: Reviewing, Engineering, Weekly, Internal, Bug
