### ISSUE TITLE
[HOLD for payment 2022-08-08] [HOLD for payment 2022-08-01] [$500] At #admins and #announce rooms, users own timezone displayed - reported by @Puneet-here

### ISSUE THREAD

**Issue by mvtglobally** [Expensify/App#9238] opened 2022-05-31 04:08 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Create a new workspace
2. Search announce and admins room of that workspace
3. Check the timezone above the text composer

## Expected Result:
It should not show users their own timezone

## Actual Result:
It's showing the user their own timezone

## Workaround:
unknown 

## Platform:

Where is this issue occurring?

- Web
- iOS
- Android
- Desktop App
- Mobile Web

**Version Number:** 1.1.69-0
**Reproducible in staging?:** Y 
**Reproducible in production?:** Y 
**Email or phone of affected tester (no customers):** 
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation
<img width="1065" alt="Screenshot 2022-04-27 at 3 03 27 AM" src="https://user-images.githubusercontent.com/43995119/171090857-5c609128-b812-4d83-a546-e4c0bc806299.png">

**Expensify/Expensify Issue URL:** 
**Issue reported by:** @Puneet-here
**Slack conversation:** https://expensify.slack.com/archives/C01GTK53T8Q/p1651012796912239

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by Christinadobrzyn** [comment] 2022-05-31 05:12
I don't see any dupe GHs about this subject and it sounds like we've confirmed it's a new bug in this [convo](https://expensify.slack.com/archives/C01GTK53T8Q/p1651068570981029?thread_ts=1651012796.912239&cid=C01GTK53T8Q). So sending to eng to see if this can be fixed externally!

**Comment by thienlnam** [comment] 2022-05-31 18:33
Yeah, good point @Puneet-here it depends on what we expect would happen here.  Since a workspace is basically a group chat, I imagine it should function in the same way in that we don't show the timezone.

However, it doesn't seem like your proposal would work.  The workspace rooms are considered a default room and would return true for isChatRoom(report)

**Comment by thienlnam** [comment] 2022-05-31 20:27
The type of room in the issue is an POLICY_ANNOUNCE room.  This is considered a default room and will pass the check https://github.com/Expensify/App/blob/3e52b9a549add24c84670fd7db46836db5a8025b/src/libs/ReportUtils.js#L116-L128

Which returns true in isChatRoom
https://github.com/Expensify/App/blob/3e52b9a549add24c84670fd7db46836db5a8025b/src/libs/ReportUtils.js#L165-L168

This probably happens when there is a single person in the workspace

**Comment by Puneet-here** [comment] 2022-06-01 06:29
Yes and that's why if we use `!isChatRoom(report)` (notice the exclamation mark) it will return false for rooms.

**Comment by thienlnam** [comment] 2022-06-01 17:15
We don't want to disable it for all rooms.. just in group rooms

**Comment by Puneet-here** [comment] 2022-06-01 19:45
Oh I thought we wanna disable it for user created rooms too, if we only wanna disable it for default rooms we can use `!isDefaultRoom(report)` instead of `!isChatRoom(report)`. 

This problem will stay in user created chat rooms so if we wanna show the timezone when a second member is inside the room we can also use my second approach together with `!isDefaultRoom(report)` check

>Second case: If we wanna show timezone when another person is in the room except you. 
For this case we can pass myPersonalDetails as an argument when calling `canShowReportRecipientLocalTime` and we can use myPersonalDetails.login to filter out our own email and we can just check if `reportParticipants.length ===1` instead of `!hasMultipleParticipants`  at line 314

https://github.com/Expensify/App/blob/db27a3dc4a61c552b8e827819261310592ad7914/src/libs/ReportUtils.js#L308-L314

**Comment by Puneet-here** [comment] 2022-06-01 19:50
Just for the clarification: 
1. We want to disable it for announce/admins/domain rooms (which all are group rooms) 
2. We wanna show timezone in user created rooms if there's an another person except you.

Question:- Isn't user created room also a group room because all the workspace members will be in user created rooms?

**Comment by stephanieelliott** [comment] 2022-06-03 23:19
Posted this to Upwork: https://www.upwork.com/jobs/~01d6142210d1049054

**Comment by stephanieelliott** [comment] 2022-06-06 14:52
Oops, thanks @Puneet-here!

**Comment by thienlnam** [comment] 2022-06-06 18:23
> Question:- Isn't user created room also a group room because all the workspace members will be in user created rooms?

To clarify, we want to disable the timezone display when there are multiple users in a group / chat.  So regardless of default or user created room

**Comment by thienlnam** [comment] 2022-06-15 19:54
Waiting for proposals

**Comment by stephanieelliott** [comment] 2022-06-16 01:32
Increased to $500

**Comment by JosueEchandiaAsto** [comment] 2022-06-17 18:35
@thienlnam

### Proposal

### Issue

It's showing the user their own timezone at #admin and #announce rooms

### Fix

This validation prevents the timezone from being displayed when the number of participants is greater than one.

https://github.com/JosueEchandiaAsto/App/blob/325b01990969362e16c21f5b35ad675ee333071a/src/libs/ReportUtils.js#L301-L308

The only thing missing is to avoid showing timezone when the logged in user is the only participant in the room.

https://github.com/JosueEchandiaAsto/App/blob/325b01990969362e16c21f5b35ad675ee333071a/src/libs/ReportUtils.js#L301-L308

https://github.com/JosueEchandiaAsto/App/blob/325b01990969362e16c21f5b35ad675ee333071a/src/libs/ReportUtils.js#L316-L324

**Commit:** https://github.com/Expensify/App/commit/325b01990969362e16c21f5b35ad675ee333071a

### Result

https://user-images.githubusercontent.com/16966456/174357488-42377a3d-feb3-4910-9440-3634ebf30c30.mp4

**Comment by Puneet-here** [comment] 2022-06-18 17:41
>To clarify, we want to disable the timezone display when there are multiple users in a group / chat. So regardless of default or user created room

Sorry for being late here. In my proposal [here](https://github.com/Expensify/App/issues/9238#issuecomment-1141892408) (at second approach) I have given a proposal for this.

>we can pass myPersonalDetails as an argument when calling `canShowReportRecipientLocalTime` and we can use myPersonalDetails.login to filter out our own email and we can just check if `reportParticipants.length ===1` instead of `!hasMultipleParticipants`  at line 314

https://github.com/Expensify/App/blob/db27a3dc4a61c552b8e827819261310592ad7914/src/libs/ReportUtils.js#L308-L314

by this approach we will only show timezone when there's another user except you and we won't show timezone when there are multiple user or only you.

**Comment by mananjadhav** [comment] 2022-06-19 16:42
Thanks for the proposals here.

> To clarify, we want to disable the timezone display when there are multiple users in a group / chat. So regardless of default or user created room

Making the requirement a bit more clearer:
1. If there are two participants, you + 1 other participant, then show the timezone
2. More than 1 participants, other than you (so in all 2+) participants, then don't show the timezone
3. If you're the only participant in the room, don't show the timezone

@thienlnam Correct me if I am wrong.

> function sessionEmailIsTheOnlyParticipant(participants) { 
>    return _.intersection(participants, [sessionEmail]).length == 1; 
> } 

@JosueEchandiaAsto I am trying to understand how your `sessionEmailIsTheOnlyParticipant ` works. The `_.intersection` function returns the common elements between two arrays. So if that will be true always for announce rooms? and it'll also be true when the announce_room has you and 1 other participant. This would end up not showing the timezone of the second participant.

@Puneet-here I am guessing in your last [comment](https://github.com/Expensify/App/issues/9238#issuecomment-1159522219) you your updated proposal starts from: `this is how we will filter out -`

> and just need to add reportParticipants.length ===1 instead of !hasMultipleParticipants

Can you help me clarify, if we're removing the `sessionEmail` from the participants, then why do we need to change the `hasMultipleParticipants` condition?

**Comment by Puneet-here** [comment] 2022-06-19 18:31
Oh sorry, you are correct @mananjadhav. I mixed that up with something else and didn't notice that we don't need to remove `hasMultipleParticipants` condition. Only filtering out our own email will do the job.

**Comment by mananjadhav** [comment] 2022-06-19 18:50
Okay thanks for clarifying @Puneet-here. Let @thienlnam confirm the acceptance criteria. Rest your proposal looks good to me.

**Comment by JosueEchandiaAsto** [comment] 2022-06-19 19:08
@mananjadhav 
Considering point 2 of the clarification, the code would look like this:
https://github.com/Expensify/App/blob/263738bf5e6025c13327a0a9fa454e54ae183d8c/src/libs/ReportUtils.js#L307-L314
should be removed has `hasMultipleParticipants`, because with the `hasOnlyOneRecipient` validation, the `hasMultipleParticipants` condition would be unnecessary.

By removing the `sessionEmail`, we are left with the list of recipients, we only show when there is a recipient, if there are no recipients we do not show, if there is more than one recipient we do not show.
Receivers:
0: No
1: Yes
Greater than 1: No

It is not enough to just remove the `sendEmail`, because when this is the only participant, the receivers will be 0, and the timezone will be show.

**Comment by mananjadhav** [comment] 2022-06-19 19:15
Thank you for the comment @JosueEchandiaAsto. You're right `reportParticipants.length ===1` would be needed. I totally missed the part because the default conversation chats never had 1 single person.

**Comment by Puneet-here** [comment] 2022-06-19 19:42
Yeah I thought about it but I found that we have another condition `reportRecipient` so if we are the only user in the room and we filter out our own email, then `reportRecipient` will be false and no timezone will be shown.

**Comment by Puneet-here** [comment] 2022-06-20 05:43
@mananjadhav, we also have to filter our own email here:
https://github.com/Expensify/App/blob/5b0cd481c87e89772f7d21fdbad6bf815b495b15/src/pages/home/report/ReportActionCompose.js#L471-L472
like this:
```js
        const reportParticipants = _.without(lodashGet(this.props.report, 'participants', []), this.props.myPersonalDetails.login);
```
**Reason:** We show the timezone for `reportRecipient` and because our own email is in the participants so the `reportRecipient` will show our timezone instead of the other person.

**Comment by mananjadhav** [comment] 2022-06-21 11:44
@Puneet-here Quick question with your updated comment.
Whats the difference between the following lines:
```      
const reportParticipants = _.without(lodashGet(this.props.report, 'participants', []), this.props.myPersonalDetails.login);
```
and
```
const reportParticipants = _.without(lodashGet(this.props.report, 'participants', []), sessionEmail);
```

**Comment by Puneet-here** [comment] 2022-06-21 13:07
We have to filter out our email at two places:
1. https://github.com/Expensify/App/blob/5b0cd481c87e89772f7d21fdbad6bf815b495b15/src/pages/home/report/ReportActionCompose.js#L471-L472
2. https://github.com/Expensify/App/blob/db27a3dc4a61c552b8e827819261310592ad7914/src/libs/ReportUtils.js#L308-L309
 We have `sessionEmail` variable available inside reportUtils.js so we can use that to filter out at `canShowReportRecipientLocalTime`  function but at `reportActionCompose.js` we don't have this variable so to get our own email we have to use `this.props.myPersonalDetails.login`

We have to remove our own email from `reportParticipants` at `reportActionCompose.js` because we take the first user from this array and pass it to `ParticipantLocalTime` component and there we show the timezone for the user that we passed. Now because in rooms we include our own self in participants we will see our own timezone.

**Comment by mananjadhav** [comment] 2022-06-25 16:10
@thienlnam Did you get a chance to look at the above conversations?

**Comment by JosueEchandiaAsto** [comment] 2022-06-27 18:23
@thienlnam something like this? https://github.com/Expensify/App/issues/9238#issuecomment-1159794329

**Comment by thienlnam** [comment] 2022-06-27 18:58
Good catch on the ReportActionCompose.  In this case, yes we should change reportRecipient to be the email that is not us.  

Going to hire @Puneet-here - he has been working on the solution first and included a fix for another part where this might become an issue

I'll just need review your PR to make sure the changes to canShowReportRecipientLocalTime are correct

**Comment by stephanieelliott** [comment] 2022-06-30 00:14
Hey @Puneet-here and @mananjadhav can you grab the job on Upwork when you get a chance? https://www.upwork.com/jobs/~01d6142210d1049054

**Comment by Puneet-here** [comment] 2022-06-30 17:35
> Hey @Puneet-here and @mananjadhav can you grab the job on Upwork when you get a chance? 
Applied and raised the PR 🚀

**Comment by mananjadhav** [comment] 2022-06-30 19:19
Thanks @Puneet-here, I can see @thienlnam has already posted some feedback. I'll be reviewing and testing this by tomorrow.

**Comment by stephanieelliott** [comment] 2022-07-06 20:35
Changes requested on the PR, also waiting on @mananjadhav's review I think?

**Comment by mananjadhav** [comment] 2022-07-12 05:41
Done from my end @stephanieelliott. I was waiting for changes to be applied, but reviewed it anyway.

**Comment by stephanieelliott** [comment] 2022-07-13 15:49
Reassigning this one as I am going OOO, thanks @trjExpensify!

**Comment by trjExpensify** [comment] 2022-08-09 00:14
👋 @Puneet-here you still need to apply to the job [here](https://www.upwork.com/jobs/~01e673ea3f72bd1dd4) before I can settle up on this one. @mananjadhav with the two deploys above, can you confirm there was a regression here for C+ payment due?

**Comment by Puneet-here** [comment] 2022-08-09 04:33
Applied.
Thank you.

**Comment by trjExpensify** [comment] 2022-08-09 11:29
Cool, offer sent to you @Puneet-here. @mananjadhav still waiting on confirmation of this: 

>@mananjadhav with the two deploys above, can you confirm there was a regression here for C+ payment due?

**Comment by trjExpensify** [comment] 2022-08-09 13:25
Cool, settled up with @Puneet-here.

**Comment by Puneet-here** [comment] 2022-08-09 14:41
Eep sorry @trjExpensify, I didn't notice it first but the total compensation was $750. $500 for the fix and $250 for the reporting.

**Comment by Puneet-here** [comment] 2022-08-09 14:48
> @mananjadhav with the two deploys above, can you confirm there was a regression here for C+ payment due?

Just sharing a note. I think we can't call it a regression, the PR was working and was approved but https://github.com/Expensify/App/pull/9560 got merged just before the PR for this issue and https://github.com/Expensify/App/pull/9560 changed an onyx key which we were using at our PR, that's why we were getting an error.

**Comment by trjExpensify** [comment] 2022-08-09 16:49
>I didn't notice it first but the total compensation was $750. $500 for the fix and $250 for the reporting.

Ahh, got it. Sent an offer for an additional $250. 

>I think we can't call it a regression, the PR was working and was approved but https://github.com/Expensify/App/pull/9560 got merged just before the PR for this issue and https://github.com/Expensify/App/pull/9560 changed an onyx key which we were using at our PR, that's why we were getting an error.

Okay, helpful context. It was a timing issue. That makes sense. Thanks! @mananjadhav, I've sent you an offer now as well.

**Comment by trjExpensify** [comment] 2022-08-09 17:13
Alright, both settled up. Closing.

**Closed by trjExpensify** 2022-08-09 17:13 UTC
Labels: Reviewing, Exported, External, Engineering, Weekly, Awaiting Payment
