### ISSUE TITLE
[HOLD for payment 2024-04-05] [$500] Workspace - If title is changed offline, the description is no longer greyed out

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#37254] opened 2024-02-27 02:34 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.44-0
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):** applausetester+emilio@applause.expensifail.com
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** Applause - Internal Team
**Slack conversation:**

## Action Performed:
1. Access staging.new.expensify.com
2. Sign into a valid account
3. Go to any Workspace setting
4. Turn off the internet and change the Description (Note that the text will be greyed out)
5. Still offline, change the title of the WS and observe the description

## Expected Result:
User expects the Description to continued greyed out until internet is back online

## Actual Result:
The description text turns "normal black" after editing the WS name offline

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details> 

https://github.com/Expensify/App/assets/78819774/7bd85fee-8702-4f2b-a2a2-d5b2ddac8662

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01a5b48695496946bf</li>
        <li>Upwork Job ID: 1765718526440808448</li>
        <li>Last Price Increase: 2024-03-07</li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @rushatgabhane</details>

**Comment by lanitochka17** [comment] 2024-02-27 02:35
We think that this bug might be related to #wave8
CC @zanyrenney

**Comment by lanitochka17** [comment] 2024-02-27 02:35
@sonialiap  FYI I haven't added the External label as I wasn't 100% sure about this issue. Please take a look and add the label if you agree it's a bug and can be handled by external contributors

**Comment by sonialiap** [comment] 2024-03-05 13:00
Reproducible. I've asked in [slack](https://expensify.slack.com/archives/C05RECHFBEW/p1709643576456159) if we want to add it to #vip-split

**Comment by sonialiap** [comment] 2024-03-07 12:38
Might be related to https://github.com/Expensify/App/issues/36598

**Comment by dragnoir** [comment] 2024-03-07 15:34
## Proposal

### Please re-state the problem that we are trying to solve in this issue.

Workspace setting page, when offline, editing settings make description opacity back to 1

### What is the root cause of that problem?

The issue is that we are using Onyx.set for updating name and currency BUT we are using Onyx.merge for updating the description. As discussed on slack many times, Onyx.set can't be used aside with Onyx.merge, and it can defect data like removing previous data)

- updateGeneralSettings 
https://github.com/Expensify/App/blob/15cf6adceb3a209a28cbafe1d460580afa2a433e/src/libs/actions/Policy.ts#L1094
- updateWorkspaceDescription
https://github.com/Expensify/App/blob/15cf6adceb3a209a28cbafe1d460580afa2a433e/src/libs/actions/Policy.ts#L1178

Links to slack discussions:
- https://expensify.slack.com/archives/C01GTK53T8Q/p1702656897746359?thread_ts=1702656464.396679&cid=C01GTK53T8Q
- https://expensify.slack.com/archives/C01GTK53T8Q/p1706541752212389?thread_ts=1705484273.717249&cid=C01GTK53T8Q

### What changes do you think we should make in order to solve the problem?

We need to use Onyx.merge with updateGeneralSettings [here](https://github.com/Expensify/App/blob/15cf6adceb3a209a28cbafe1d460580afa2a433e/src/libs/actions/Policy.ts#L1094)

```diff
-  onyxMethod:  Onyx.METHOD.SET,
+  onyxMethod:  Onyx.METHOD.MERGE,
```

**Comment by rushatgabhane** [comment] 2024-03-07 21:15
C+ reviewed  🎀 👀 🎀 

I like @Krishna2323's [proposal](https://github.com/Expensify/App/issues/37254#issuecomment-1965696407) because they were first.

**Comment by sonialiap** [comment] 2024-03-11 12:38
@rushatgabhane @rlinoz who do you think we should assign to this?

**Comment by rushatgabhane** [comment] 2024-03-11 22:48
I gave this a look again. I think we should assign @Krishna2323 because they were first - https://github.com/Expensify/App/issues/37254#issuecomment-1984502868

**Comment by rlinoz** [comment] 2024-03-12 16:52
I agree with @rushatgabhane , so I am assigning @Krishna2323 

The RCA could have been better explained in the first post, and we didn't need to update `updateWorkspaceDescription`, but the proposal already points to fix `updateGeneralSettings`.

**Comment by rlinoz** [comment] 2024-03-12 17:05
Hey @sonialiap if you could help with the comment above

**Comment by rlinoz** [comment] 2024-03-22 13:12
Hey @rushatgabhane do you have an idea of when you will be able to review the PR?

**Comment by sonialiap** [comment] 2024-04-05 11:47
@rushatgabhane $500 - please request in ND - [please complete the checklist](https://github.com/Expensify/App/issues/37254#issuecomment-2026483024)
@Krishna2323 $500 - offer sent

**Comment by JmillsExpensify** [comment] 2024-04-08 03:08
$500 approved for @rushatgabhane

**Comment by sonialiap** [comment] 2024-04-08 09:01
@rushatgabhane bump on completing [the checklist 🙏 ](https://github.com/Expensify/App/issues/37254#issuecomment-2026483024)

**Comment by sonialiap** [comment] 2024-04-11 14:35
@rushatgabhane bump for the checklist https://github.com/Expensify/App/issues/37254#issuecomment-2026483024

**Comment by rushatgabhane** [comment] 2024-04-13 15:52
WIP ⚠️ 

1. The PR that introduced the bug has been identified. Link to the PR:

2. The offending PR has been commented on, pointing out the bug it caused and why, so the author and reviewers can learn from the mistake. Link to comment:

3. A discussion in #expensify-bugs has been started about whether any other steps should be taken (e.g. updating the PR review checklist) in order to catch this type of bug sooner. Link to discussion:

4. Determine if we should create a regression test for this bug.

5. If we decide to create a [regression test](https://github.com/Expensify/App/blob/main/contributingGuides/REGRESSION_TEST_BEST_PRACTICES.md) for the bug, please propose the regression test steps to ensure the same bug will not reach production again

**Comment by sonialiap** [comment] 2024-04-15 10:26
Morning, my favorite type of bump, @rushatgabhane could we get the checklist completed so that we can close this out? 😁

**Comment by rushatgabhane** [comment] 2024-04-18 18:16
soon soon soon 🔜

**Comment by sonialiap** [comment] 2024-04-22 09:09
@rushatgabhane Looking forward to it 😜

**Comment by rlinoz** [comment] 2024-04-24 19:24
@rushatgabhane friendly bump

**Comment by rushatgabhane** [comment] 2024-04-25 05:51
Updated https://github.com/Expensify/App/issues/37254#issuecomment-2053685369

we can close after regression test is added

**Closed** 2024-04-25 14:21 UTC
Labels: External, Daily, Awaiting Payment, Bug
