### ISSUE TITLE
[HOLD for payment 2023-08-28] [$1000] ReportPreview has replies, but there's no option to reply in thread when hovering.

### ISSUE THREAD

**Issue by kavimuru** [Expensify/App#23377] opened 2023-07-21 21:22 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Login with any account.
2. Try to request money to any account.
3. Hover on the money request.
4. Notice that, it showed 1 reply but there's no option to reply in thread.
## Expected Result: 
There should be option to reply in thread when hovering or right click on money request.
## Actual Result: 
There's no action to reply in thread when hovering or right click on money request.

## Workaround:
Can the user still use Expensify without this being fixed? Have you informed them of the workaround?

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android / native
- [x] Android / Chrome
- [x] iOS / native
- [x] iOS / Safari
- [x] MacOS / Chrome / Safari
- [x] MacOS / Desktop

**Version Number:** 1.3.44-0
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/43996225/b359c6e9-6eba-4ba3-99b9-efbcf73a13b4

https://github.com/Expensify/App/assets/43996225/6d053678-f3ec-49c4-96c1-590c0dba825f

**Expensify/Expensify Issue URL:**
**Issue reported by:** @hungvu193 
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1689606579815989

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~011c9047e249918424</li>
        <li>Upwork Job ID: 1684138930178179072</li>
        <li>Last Price Increase: 2023-08-09</li>
<li>Automatic offers: </li>
<ul>
<li>situchan | Contributor | 26006189</li>
<li>hungvu193 | Reporter | 26006191</li>
</ul></li>
    </ul>
</details>

**Comment by kavimuru** [comment] 2023-07-21 21:22
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
ReportPreview has replies, but there's no option to reply in thread when hovering.
### What is the root cause of that problem?
We're checking here to show reply in thread option, we only showed "reply in thread" when our reportActions have type "ADDCOMMENT", but since we introduced report preview action and IOU which also had replies, we didn't add it in here yet.
https://github.com/Expensify/App/blob/7770b866bff96efa42c337fb5db8473d34102e71/src/pages/home/report/ContextMenu/ContextMenuActions.js#L121
### What changes do you think we should make in order to solve the problem?

We should also include `REPORTPREVIEW` and `IOU` type in our `shouldShow` condition in [here](https://github.com/Expensify/App/blob/7770b866bff96efa42c337fb5db8473d34102e71/src/pages/home/report/ContextMenu/ContextMenuActions.js#L121):
```javascript

                    type === CONTEXT_MENU_TYPES.REPORT_ACTION &&
                    ((reportAction.actionName === CONST.REPORT.ACTIONS.TYPE.ADDCOMMENT && !ReportUtils.isThreadFirstChat(reportAction, reportID)) ||
                        reportAction.actionName === CONST.REPORT.ACTIONS.TYPE.REPORTPREVIEW ||
                        reportAction.actionName === CONST.REPORT.ACTIONS.TYPE.IOU)
```
Alternatively, we can replace `reportAction.actionName === CONST.REPORT.ACTIONS.TYPE.REPORTPREVIEW)` with `ReportActionUtils.isReportPreviewAction(reportAction)`

### What alternative solutions did you explore? (Optional)
N/A

**Comment by conorpendergrast** [comment] 2023-07-21 23:31
@CortneyOfstad I'm OoO on Monday and Tuesday, so co-assigning this in case you can get to it before Wednesday!

**Comment by conorpendergrast** [comment] 2023-07-26 09:48
My bad, sorry, I unassigned the wrong account here. Reproduced, all done: 

<img width="1038" alt="image" src="https://github.com/Expensify/App/assets/5802477/af4cb7d0-5951-43c4-86d5-41b7bfdb19ec">

**Comment by conorpendergrast** [comment] 2023-07-31 09:32
@0xmiroslav There's a proposal from @hungvu193 to review [above](https://github.com/Expensify/App/issues/23377#issuecomment-1646251266), fyi

**Comment by conorpendergrast** [comment] 2023-08-02 19:23
@0xmiroslav Is that proposal workable?

**Comment by conorpendergrast** [comment] 2023-08-10 13:37
@situchan Waiting for your review of [this proposal](https://github.com/Expensify/App/issues/23377#issuecomment-1646251266), please

**Comment by situchan** [comment] 2023-08-11 07:16
I think it's expected to show reply for IOUPreview.
We also show reply for TaskPreview.

https://github.com/Expensify/App/assets/108292595/017e5e30-7b0e-43fc-baf4-c8911289283e

**Comment by situchan** [comment] 2023-08-11 07:28
[Proposal](https://github.com/Expensify/App/issues/23377#issuecomment-1646251266) looks good to me. This is straightforward fix.
@hungvu193 please comment here to get assigned.
🎀 👀 🎀 C+ reviewed

**Comment by Julesssss** [comment] 2023-08-11 08:29
Agree with the proposal. Maybe we should create a helper func for all these actions that can be replied to.

**Comment by conorpendergrast** [comment] 2023-08-16 11:31
Nice, looks like the PR is making progress and _just_ got sent to Jules for review

**Comment by conorpendergrast** [comment] 2023-08-29 12:22
From reading https://github.com/Expensify/App/issues/25688, this issue (#23377) wasn't the cause of the deploy blocker. So we are good to pay here, [without urgency bonus](https://github.com/Expensify/App/issues/23377#issuecomment-1687086889)

**Comment by situchan** [comment] 2023-08-29 12:27
I think Melvin miscalculated timeline.
@hungvu193 was [assigned](https://github.com/Expensify/App/issues/23377#event-10067196782) on Aug 11
PR was C+ [approved](https://github.com/Expensify/App/pull/24412#pullrequestreview-1579943471) on Aug 16
PR was [merged](https://github.com/Expensify/App/pull/24412#event-10109880578) without further requests on Aug 16
Aug 12, 13 was weekend

**Comment by conorpendergrast** [comment] 2023-08-29 12:28
@situchan That looks like more than 72 hours, when you exclude weekends. Can you share your maths for the timeline being less than 72 hours between assign and merge?

**Comment by situchan** [comment] 2023-08-29 12:36
I updated comment - https://github.com/Expensify/App/issues/23377#issuecomment-1697348284 regarding timeline

**Comment by conorpendergrast** [comment] 2023-08-29 16:31
@situchan In that example above, the Contributor created the PR around 9 hours after they were assigned to the issue, and the C+ 36 hours later. Then the engineer led discussed that didn't end up changing the PR for four days. I don't think that's the equivalent to here, when the engineer reviewed and merged the PR 8 hours after you approved it. 

I'm sticking with no urgency bonus as a result

**Comment by conorpendergrast** [comment] 2023-08-29 16:32
Thanks for the checklist too - I'm closing this out!

**Closed by conorpendergrast** 2023-08-29 16:32 UTC
Labels: External, Daily, Awaiting Payment, Bug
