### ISSUE TITLE
[$250] mWeb/safari - Invoice - App shows confirmation page when swiping right after sending invoice

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#41940] opened 2024-05-09 17:53 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.72-0
**Reproducible in staging?:** y
**Reproducible in production?:** y
**Issue reported by:** Applause - Internal Team

## Action Performed:
1. Go to staging.new.expensify.com
2. Go to FAB > Send invoice.
3. Enter amount and select a user.
4. Create the invoice.
5. In invoice chat, swipe the page to the right (iOS style).

## Expected Result:
Invoice confirmation page will not appear when swiping right.

## Actual Result:
Invoice confirmation page appears briefly when swiping right.

## Workaround:
n/a

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [x] iOS: mWeb Safari
- [ ] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

https://github.com/Expensify/App/assets/93399543/10520c0d-e888-428e-8cdf-4fb573ccdd4b

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01aea40b16c5d0e563</li>
        <li>Upwork Job ID: 1790003603403919360</li>
        <li>Last Price Increase: 2024-05-13</li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @jjcoffee</details>

**Comment by kbecciv** [comment] 2024-05-09 17:53
We think that this bug might be related to #wave-collect - Release 1

**Comment by VickyStash** [comment] 2024-05-13 12:53
Hi, I'm Viktoryia from Callstack - expert contributor group - and I would like to work on this issue.
cc @cristipaval

**Comment by cristipaval** [comment] 2024-05-13 12:57
@davidcardoza, I added `LOW` priority on this one, please let me know if you think another one fits better

**Comment by VickyStash** [comment] 2024-05-13 13:45
I was able to reproduce the issue, but it looks like it doesn't relate specifically to `Send Invoice` flow, it's reproducible with `Submit expense` as well.

**Comment by VickyStash** [comment] 2024-05-14 15:47
I'm still working on the proposal. 
The problem seems to occurs because the navigation history that Safari manages does not sync up perfectly with the navigation controlled by React Navigation. 
The navigation from _Confirmation_ page to _Report_ page is handled by `replace` method. But the iOS Safari swipe back gesture can still access the browser's history stack and shows the previous (confirmation) screen during the swipe.

**Comment by CortneyOfstad** [comment] 2024-05-15 18:28
Thanks @VickyStash!

**Comment by cristipaval** [comment] 2024-05-15 18:36
Not overdue, Melv

**Comment by VickyStash** [comment] 2024-05-16 16:40
I haven't had a lot of time today for this ticket, but I created a simple app to test similar navigation scenario and it looks like I had the same problem. So the main guess for now that's it can be navigation lib problem rather than the app bug.

**Comment by Pujan92** [comment] 2024-05-17 20:05
@CortneyOfstad To inform, I am OOO until 27th May. Either we can reassign to other C+ or else I will check post 27th May.

**Comment by CortneyOfstad** [comment] 2024-05-20 15:28
Going to reassign the C+ — thanks @Pujan92 and have a great time away!

**Comment by CortneyOfstad** [comment] 2024-05-20 15:29
@jjcoffee most recent update from @VickyStash is [here](https://github.com/Expensify/App/issues/41940#issuecomment-2115735992) — any questions, just let us know!

**Comment by jjcoffee** [comment] 2024-05-21 09:08
Okay looks like we're just waiting for @VickyStash to provide another update then?

**Comment by VickyStash** [comment] 2024-05-21 09:11
@jjcoffee Yeah, I'm spending the time today on this one and hope to provide updates later 🔍

**Comment by CortneyOfstad** [comment] 2024-05-22 15:24
Awesome — thanks @VickyStash!

**Comment by VickyStash** [comment] 2024-05-23 17:00
### Updates: 
Unfortunately, even with my approach, I have found a problem that the user can then move forward to other screens using browser buttons.

https://github.com/Expensify/App/assets/23176449/2cb81916-9bb0-4677-abb5-21a4ec5cd467

I'm still looking for a safe way to update the browser history to make both - swipes and browser navigation works as expected.

**Comment by jjcoffee** [comment] 2024-05-24 09:34
Chill Melv, this is under investigation :smile:

**Comment by VickyStash** [comment] 2024-05-28 07:22
Unfortunately, I still haven't found a safe way to eliminate this problem.

Hey @adamgrzybowski, it looks like you [were working](https://github.com/Expensify/App/pull/24165) on handling browser history during complex navigation flows. Maybe you have any thoughts about it?

**Context:**
When the app dismisses a modal and navigates to the Report screen the [replace method is called](https://github.com/Expensify/App/blob/2514f2988eb26858d30fa501c0040b1f8fc2e239/src/libs/Navigation/dismissModalWithReport.ts#L59-L63).
You've updated [useLinking logic](https://github.com/Expensify/App/blob/2514f2988eb26858d30fa501c0040b1f8fc2e239/patches/%40react-navigation%2Bnative%2B6.1.12.patch#L253-L267) so the browser history handles the navigation in alignment with the app and user navigated to the right place using browser back/forward buttons.
But in the mweb safari if a user uses a swipe gesture to go back he sees previous screen during the swipe, but navigates to another right place.

**Comment by VickyStash** [comment] 2024-05-29 08:44
Me and @adamgrzybowski had a discussion yesterday, and unfortunately it looks like there is no safe way to get rid of the described issue without side effects.
Overall, it looks like it's more of an internal Safari feature to show a cached view of the previous route on swipe, and there are not many things we can do about it.
cc @jjcoffee

**Comment by jjcoffee** [comment] 2024-05-29 12:20
@VickyStash Thanks for looking into it! Just for completeness could you outline what the side effects are if you implement a fix for the issue?

**Comment by VickyStash** [comment] 2024-05-29 15:40
@jjcoffee Any attempts to resolve the issue affected the browser history, leading to wrong navigation using the browser back/forward buttons on all of the web platforms.

**Comment by jjcoffee** [comment] 2024-05-30 09:08
Okay sounds like we should close this then, unless others disagree? @CortneyOfstad @cristipaval

**Comment by CortneyOfstad** [comment] 2024-05-30 13:50
Sounds good and thank you @VickyStash for your incredibly thorough investigation on this! Closing!

**Closed by CortneyOfstad** 2024-05-30 13:50 UTC
Labels: External, Daily, Bug
