### ISSUE TITLE
[$250] Android - Chat - Both parentheses and code block alignment is not same

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#49935] opened 2024-09-30 14:15 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 9.0.41-2
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**If this was caught during regression t sting, add the test name, ID and link from TestRail:** N/A
**Issue reported by:** Applause - Internal Team

## Action Performed:
1. Launch app in both Android and mweb
2. Open a chat
3. Paste the text - def test_code(): print(`ode block test`)
4. Send the message
5. Note code block and Parentheses alignment

## Expected Result:
Both parentheses and code block alignment must be same

## Actual Result:
In Android, slightly above parentheses, code block is displayed. In mweb, both parentheses and code block display in same line

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [ ] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details> 

![om expensify chat-edit](https://github.com/user-attachments/assets/3e9eeed0-24d1-4bb2-9a15-c1b17de07fb0)

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~021844887140240525614</li>
        <li>Upwork Job ID: 1844887140240525614</li>
        <li>Last Price Increase: 2024-11-01</li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @hungvu193</details>

**Comment by lanitochka17** [comment] 2024-09-30 14:16
We think that this bug might be related to #Live Markdown

**Comment by alexpensify** [comment] 2024-10-02 22:10
Adding this one to my test list and will get to it later this week.

**Comment by alexpensify** [comment] 2024-10-07 21:13
No update yet

**Comment by alexpensify** [comment] 2024-10-11 23:46
@hungvu193 - when you get a chance, can you see if this proposal will fix this issue? Thanks! I'm able to replicate on my Android device. Thanks!

**Comment by hungvu193** [comment] 2024-10-12 01:05
> @hungvu193 - when you get a chance, can you see if this proposal will fix this issue? Thanks! I'm able to replicate on my Android device. Thanks! 

Oops let's reopen it 😂

**Comment by hungvu193** [comment] 2024-10-13 13:54
I can reproduce this one, reviewing shortly

<img width="346" alt="Screenshot 2024-10-13 at 20 54 40" src="https://github.com/user-attachments/assets/889ffc35-a27c-4dc8-8489-a9fe4405d488">

**Comment by hungvu193** [comment] 2024-10-13 15:13
Hi @kushu7, your proposal worked. However please elaborate a bit more about your RCA.
The `height` of `codeWordWrapper` style was added a long time ago and it was increased to 20 to fix [this issue](https://github.com/Expensify/App/issues/4005).
My question here is what are the recent changes that introduced this bug?

**Comment by alexpensify** [comment] 2024-10-14 17:08
🤦🏼‍♂️ whoops, reopening again.

**Comment by hungvu193** [comment] 2024-10-15 07:34
I don't think we can go forward without a clear RCA.

**Comment by bernhardoj** [comment] 2024-10-17 09:06
This is actually an [old issue](https://github.com/Expensify/App/issues/8132#issuecomment-1436734572).

**Comment by hungvu193** [comment] 2024-10-18 02:31
hmm linked facebook PR was closed :/

**Comment by alexpensify** [comment] 2024-10-18 04:14
## Heads up, I will be offline until Tuesday, October 22, 2024, and will not actively watch over this GitHub during that period.

If this GitHub requires an urgent update, please ask for help in the #expensify-open-source Slack Room. If the inquiry can wait, I'll review it when I return online.

**Comment by hungvu193** [comment] 2024-10-22 03:52
Not overdue.

**Comment by bernhardoj** [comment] 2024-10-23 02:59
@alexpensify nope, I just want to link to the RCA of the issue 😅

**Comment by alexpensify** [comment] 2024-10-25 23:42
Not overdue, waiting for proposals here

**Comment by hungvu193** [comment] 2024-10-31 04:24
Same

**Comment by hungvu193** [comment] 2024-11-05 08:49
According to https://github.com/Expensify/App/issues/8132#issuecomment-2450727023, it looks like we don't have plan to fix this bug yet. We can close this one @alexpensify

**Comment by alexpensify** [comment] 2024-11-05 16:12
Thanks, closing in favor of https://github.com/Expensify/App/issues/8132#issuecomment-2450727023.

**Closed by alexpensify** 2024-11-05 16:12 UTC
Labels: External, Daily, Help Wanted, Bug
