### ISSUE TITLE
[HOLD #20908] [$1000] After leaving the thread and going back user gets not found page and after a brief moment thread appears

### ISSUE THREAD

**Issue by kavimuru** [Expensify/App#21602] opened 2023-06-26 18:34 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Go to a chat
2. Send a message
3. Hover over it and create a thread
4. Click on the chat header
5. Leave the thread
6. Click back button on concierge chat
7. You will see the not found page
8. Wait a little and the thread details will appear
## Expected Result: 
You shouldn't see the not found page
## Actual Result: 
You will see the not found page
## Workaround:
Can the user still use Expensify without this being fixed? Have you informed them of the workaround?

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android / native
- [x] Android / Chrome
- [x] iOS / native
- [x] iOS / Safari
- [x] MacOS / Chrome / Safari
- [x] MacOS / Desktop

**Version Number:** 1.3.32-5
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/43996225/695ef252-11cf-46cc-89a9-0277e3ff9985

https://github.com/Expensify/App/assets/43996225/b319549c-1783-4920-8a2b-3c6378fb3a0b

**Expensify/Expensify Issue URL:**
**Issue reported by:** @Puneet-here 
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1687339999531589

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01d6cab793b6f7462a</li>
        <li>Upwork Job ID: 1673980636951183360</li>
        <li>Last Price Increase: 2023-06-28</li>
    </ul>
</details>

**Comment by DrLoopFall** [comment] 2023-06-28 11:34
## Proposal

### Please re-state the problem that we are trying to solve in this issue.

Not found page is displayed after leaving a thread and navigating back.

### What is the root cause of that problem?

When leaving a thread only the `optimisticData` and `failureData` is set, without setting the `successData`

### What changes do you think we should make in order to solve the problem?

Adding the `successData` for the report in `Report.js` would fix the issue.

```js
successData: [
    {
        onyxMethod: Onyx.METHOD.SET,
        key: `${ONYXKEYS.COLLECTION.REPORT}${reportID}`,
        value: {
            stateNum: CONST.REPORT.STATE_NUM.SUBMITTED,
            statusNum: CONST.REPORT.STATUS.CLOSED,
        },
    },
],

```

### What alternative solutions did you explore? (Optional)

N/A

**Comment by DrLoopFall** [comment] 2023-06-28 11:37
Contributor details
Your Expensify account email: DrLoopFall@gmail.com
Upwork Profile Link: https://www.upwork.com/freelancers/~01c8c2835e5319aa72

**Comment by Santhosh-Sellavel** [comment] 2023-06-29 20:47
@bfitzexpensify 
Not sure if this is a duplicate, but looks definitely related. Better to have https://github.com/Expensify/App/issues/20908 handled before. So let's add Hold for https://github.com/Expensify/App/issues/20908 in this issue.

**Comment by bfitzexpensify** [comment] 2023-06-30 02:31
Agreed. Updated title, once https://github.com/Expensify/App/issues/20908 is fixed I can retest to see if this is still an issue.

**Comment by bfitzexpensify** [comment] 2023-07-03 07:41
Still held on #20908

**Comment by bfitzexpensify** [comment] 2023-07-05 10:59
Still held

**Comment by bfitzexpensify** [comment] 2023-07-07 12:16
Still held on https://github.com/Expensify/App/issues/20908

**Comment by bfitzexpensify** [comment] 2023-07-12 13:58
Still held on https://github.com/Expensify/App/issues/20908

**Comment by bfitzexpensify** [comment] 2023-07-17 09:29
Still held

**Comment by bfitzexpensify** [comment] 2023-07-18 15:19
Still held

**Comment by bfitzexpensify** [comment] 2023-07-20 14:25
Remains held

**Comment by bfitzexpensify** [comment] 2023-07-21 12:39
Still held

**Comment by bfitzexpensify** [comment] 2023-07-24 12:22
Priority over in https://github.com/Expensify/App/issues/20908 changed to weekly, doing the same here.

**Comment by bfitzexpensify** [comment] 2023-07-31 13:20
Still held on #20908

**Comment by bfitzexpensify** [comment] 2023-08-09 10:26
still held

**Comment by bfitzexpensify** [comment] 2023-08-23 11:00
still held

**Comment by bfitzexpensify** [comment] 2023-09-19 15:27
OK, I was unable to reproduce this, so I believe it's now fixed. Closing this out.

**Comment by Puneet-here** [comment] 2023-09-21 08:11
@bfitzexpensify, I think it is eligible for reporting compensation.

**Comment by bfitzexpensify** [comment] 2023-09-21 11:13
Agreed @Puneet-here - sent you an offer via Upwork.

**Comment by Puneet-here** [comment] 2023-09-25 07:03
Accepted @bfitzexpensify!

**Comment by bfitzexpensify** [comment] 2023-09-25 09:41
Ok, all paid out.

**Closed by bfitzexpensify** 2023-09-25 09:41 UTC
Labels: External, Weekly, Help Wanted, Bug
