### ISSUE TITLE
[HOLD for payment 2024-08-19] [$500] No feedback and delay when uploading a large attachment

### ISSUE THREAD

**Issue by m-natarajan** [Expensify/App#38478] opened 2024-03-18 15:19 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:**
**Reproducible in staging?:** needs reproduction
**Reproducible in production?:** needs reproduction
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** @neil-marcellini 
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1710524006372329

## Action Performed:
1. Use iOS on a slow network connection
2. Go to any chat
3. Click the plus button
4. Add an attachment
5. Select a video larger than the current limit of 24mb

## Expected Result: 
"Attachment too large Attachment size is larger than 25 MB limit" popup shows immediately

<img width="378" alt="image" src="https://github.com/user-attachments/assets/7763e061-6d0c-4454-91dc-968b401b9018">

## Actual Result: 
Nothing happens for quite a while, then you receive a popover explaining that the attachment is too large

## Workaround:
unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [x] iOS: Native
- [ ] iOS: mWeb Safari
- [ ] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

https://github.com/Expensify/App/assets/38435837/1eb76771-48a3-4f74-8e04-2833e052d922

https://github.com/Expensify/App/assets/26260477/aa4196a1-9d32-4706-94d6-b7480efaed94

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01398c6a10dbc0b325</li>
        <li>Upwork Job ID: 1770333731300958208</li>
        <li>Last Price Increase: 2024-07-17</li>
<li>Automatic offers: </li>
<ul>
<li>hoangzinh | Reviewer | 0</li>
<li>ShridharGoel | Contributor | 0</li>
</ul></li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @Christinadobrzyn / @Christinadobrzyn</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @puneetlath / @Christinadobrzyn</details>

**Comment by Christinadobrzyn** [comment] 2024-03-20 06:17
I can reproduce this. Here's the GH about increasing the size from 24 MB - https://github.com/Expensify/App/issues/32702

I think this can be external

**Comment by situchan** [comment] 2024-03-22 16:45
@ShridharGoel I can test on my iPhone. Can you attach or share link to video file you tested?

**Comment by situchan** [comment] 2024-03-22 17:19
I am seeing "Attachment too large" modal immediately

**Comment by Christinadobrzyn** [comment] 2024-03-25 02:06
testing this again, I am also seeing the "attachment too large" prompt immediately. So I think this is resolved. 

Asking QA to test 

https://github.com/Expensify/App/assets/51066321/768cc2a8-1c6c-439c-bb4b-681232866077

**Comment by neil-marcellini** [comment] 2024-03-25 08:37
@Christinadobrzyn that looks like a slightly different flow you tested. I'm consistently able to reproduce with this video, regardless of network speed. I'm on iOS 17.3.1, New Expensify v1.4.50-5


https://github.com/Expensify/App/assets/26260477/aa4196a1-9d32-4706-94d6-b7480efaed94

**Comment by Christinadobrzyn** [comment] 2024-03-26 05:35
Thanks @neil-marcellini! I can also reproduce with the above video - I added it to the OP so we can use it for testing.

**Comment by Christinadobrzyn** [comment] 2024-03-27 08:52
Yep! Updated the Expected Result in the OP @hoangzinh!

**Comment by Christinadobrzyn** [comment] 2024-03-28 06:37
Just a heads up that I'm going to be ooo on Friday and Monday for Easter. I'll check in on this on Tuesday when I'm back.

**Comment by AndrewGable** [comment] 2024-04-18 22:59
FYI the PR was reverted for regression/deploy blocker. Please make sure to address the bug in a future PR.

**Comment by Christinadobrzyn** [comment] 2024-05-03 10:13
hi @hoangzinh and @ShridharGoel - can you provide an update on this?

**Comment by AndrewGable** [comment] 2024-05-06 17:47
Yes it was before the revert

**Comment by Christinadobrzyn** [comment] 2024-05-14 09:00
just checking in here @hoangzinh or @ShridharGoel do you have an update?

**Comment by Christinadobrzyn** [comment] 2024-05-21 07:48
Just checking in on this - @hoangzinh and @ShridharGoel can you provide an update?

**Comment by Christinadobrzyn** [comment] 2024-06-05 08:39
monitoring PR - https://github.com/Expensify/App/pull/42739

**Comment by Christinadobrzyn** [comment] 2024-06-12 11:13
Payouts due:

- [ ] Contributor: $500 @ShridharGoel (Upwork offer - https://www.upwork.com/nx/wm/offer/102702299)
- [ ] Contributor+: $500 @hoangzinh (Upwork offer - https://www.upwork.com/nx/wm/workroom/36826243/overview)

Upwork job is [here](https://www.upwork.com/jobs/~01398c6a10dbc0b325). @ShridharGoel's post (https://www.upwork.com/jobs/~019b8a7f0aa6251df3)

@hoangzinh do we need a regression test?

**Comment by puneetlath** [comment] 2024-06-20 18:59
@ShridharGoel you need to accept the Upwork offer. 

@hoangzinh bump on the checklist for you.

**Comment by puneetlath** [comment] 2024-06-24 20:38
Ah ok. So we are waiting for a new PR from @ShridharGoel is that right?

**Comment by puneetlath** [comment] 2024-06-25 15:22
@ShridharGoel do you have an ETA for the new PR?

**Comment by Christinadobrzyn** [comment] 2024-07-01 18:10
hi @ShridharGoel - can you please provide an update when you have a moment? TY!

**Comment by Christinadobrzyn** [comment] 2024-07-03 19:23
@hoangzinh or @ShridharGoel can either of you provide an update on this?

**Comment by Christinadobrzyn** [comment] 2024-07-09 23:26
I'm not quite sure what would be best on the engineering side @puneetlath or @tylerkaraszewski do you have a suggestion?

**Comment by puneetlath** [comment] 2024-07-11 21:52
That seems fine to me. I think it's more of a product question of whether we see that as an acceptable behavior.

**Comment by shawnborton** [comment] 2024-07-12 07:37
I thought we already had a good design for letting the user know that the attachment is too big? The problem is that we just aren't showing the the alert modal fast enough, right? cc @Expensify/design for any additional thoughts too.

**Comment by shawnborton** [comment] 2024-07-12 07:45
I'm not quite following - are you saying that we would add some kind of loading state to uploading an attachment for all attachments? Why can't we check the file size immediately?

**Comment by dannymcclain** [comment] 2024-07-12 13:29
I'm having a hard time following too. I also thought we already had a good pattern for this?

**Comment by shawnborton** [comment] 2024-07-16 13:28
I mentioned this before but I think ideally we'd check for the file size immediately and return the error ASAP rather than using any kind of loading indicator which might worsen the experience for all users.

**Comment by Christinadobrzyn** [comment] 2024-07-16 15:43
Sorry @hoangzinh - just to make sure I understand: 

It sounds like we want to reopen to other contributors to determine if there's a way to check the loading state immediately so we can throw the 'attachment is too large' popup immediately. 

If that's right, and we don't have a solution to do it now, yes, I think we should reopen for other proposals.

**Comment by Christinadobrzyn** [comment] 2024-07-17 17:21
Add help wanted back on again. I'll see if someone from SWM might be able to take a peek at this.

**Comment by BrtqKr** [comment] 2024-07-18 07:52
> Add help wanted back on again. I'll see if someone from SWM might be able to take a peek at this.
> 
> https://expensify.slack.com/archives/C04878MDF34/p1721237101820579

@Christinadobrzyn I'd like to take a look, please assign me

**Comment by Christinadobrzyn** [comment] 2024-07-18 14:00
Thank you @BrtqKr!

**Comment by BrtqKr** [comment] 2024-07-19 14:33
@Christinadobrzyn I'm not sure why reverting the original solution helped at all. [This PR ](https://github.com/Expensify/App/pull/39334/files) is affecting a completely different library, adding an attachment is not react-native-image-picker, but react-native-document-picker. with a completely separate config. I've tested everything and it seems to be working for pdf and removing the delay in general. There's even [a related issue ](https://github.com/react-native-image-picker/react-native-image-picker/issues/2278) with a comment that suggests adding a native config that does the same thing as in the reverted PR.

**Comment by Christinadobrzyn** [comment] 2024-07-19 15:44
Thank you for digging into this, @BrtqKr! I see the communication about the revert [here](https://github.com/Expensify/App/issues/38478#issuecomment-2096475740). It looks like this was caused by a deploy blocker. 

I see the @ShridharGoel asked if the deploy blocker might be related to something else. 

I'm not sure what we should do in this case - should we try again and see if there's another blocker? 

@ShridharGoel @hoangzinh @tylerkaraszewski @puneetlath @AndrewGable

**Comment by Christinadobrzyn** [comment] 2024-07-22 18:00
@BrtqKr would you have any suggestions based on @ShridharGoel's summary - https://github.com/Expensify/App/issues/38478#issuecomment-2239726006

Do you know if there's anything in the 2nd PR that we could adjust to push this forward?

**Comment by BrtqKr** [comment] 2024-07-22 21:28
@Christinadobrzyn I've been looking into this HEIC issue today. For now it seems like there's a mime type conversion happening for those images at some. Conversion is a pretty standard approach for the HEIC format, but with `assetRepresentationMode` property used in there  the transcoding is probably skipped and we end up with a broken file. I have an idea for a workaround - we might be able to convert it manually and skip the bug at the same time, but I'll try to verify it tomorrow morning.

**Comment by BrtqKr** [comment] 2024-07-23 15:44
@Christinadobrzyn the PR is ready, I'll complete the recordings later this evening, but since the heic is being treated as a file attachment on other platforms, this should be ready for review. To sum up - the manual conversion worked and they indeed had an incorrect magic bytes signature in comparison to the file extension.

**Comment by Christinadobrzyn** [comment] 2024-07-23 23:47
Awesome! Thank you so much @BrtqKr!

**Comment by Christinadobrzyn** [comment] 2024-07-30 17:01
update for Melvin - PR is under review - @hoangzinh do you have a update on the PR?

**Comment by Christinadobrzyn** [comment] 2024-08-06 21:56
monitoring PR https://github.com/Expensify/App/pull/46025 - let us know if you have any other updates @hoangzinh

**Comment by Christinadobrzyn** [comment] 2024-08-13 20:29
Payouts due - can we confirm this is the correct payment for this job? 

- [ ] Contributor: $500 @ShridharGoel (Upwork offer - https://www.upwork.com/nx/wm/offer/103513737) 
- [ ] Contributor+: $500 @hoangzinh (Upwork offer - https://www.upwork.com/nx/wm/offer/101646357)

Do we need a regression test for this @hoangzinh?

**Comment by Christinadobrzyn** [comment] 2024-08-19 16:50
Awesome! Thanks @hoangzinh. 

Regression test - https://github.com/Expensify/Expensify/issues/421516

This is payment day and there are no regressions so paying this out based on this [payment summary ](https://github.com/Expensify/App/issues/38478#issuecomment-2287083303)

Closing!

**Closed by Christinadobrzyn** 2024-08-19 16:50 UTC
Labels: External, Daily, Awaiting Payment, Bug
