### ISSUE TITLE
[$250] Task – Assignee avatar is greyed out in main chat when complete a task

### ISSUE THREAD

**Issue by IuliiaHerets** [Expensify/App#48834] opened 2024-09-09 21:11 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 9.0.31-5
**Reproducible in staging?:** Y
**Reproducible in production?:** N/A
**Email or phone of affected tester (no customers):** applausetester+jp_e_category_2@applause.expensifail.com
**Issue reported by:** Applause Internal Team

## Action Performed:
1. Go to https://staging.new.expensify.com/
2. Log in
3. Navigate to any chat
4. Create a task and assign to any user
5. In the main chat mark this task as complete using checkbox

## Expected Result:
Assignee avatar is not greyed out

## Actual Result:
Assignee avatar is greyed out

## Workaround:
Unknown

## Platforms:

- [ ] Android: Native
- [x] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

https://github.com/user-attachments/assets/9d143e37-aae5-4420-ac79-0b115a7a5a65

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~021833261573770418634</li>
        <li>Upwork Job ID: 1833261573770418634</li>
        <li>Last Price Increase: 2024-09-09</li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @rushatgabhane</details>

**Comment by rushatgabhane** [comment] 2024-09-09 21:56
not a bug. 

@Expensify/design expilicitly asked for the avatar to be greyed in PR - https://github.com/Expensify/App/pull/48552

**Comment by BhuvaneshPatil** [comment] 2024-09-09 21:58
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
Task assignee avatar is grayed out in main chant when complete a task
- Offending PR https://github.com/Expensify/App/pull/48552

### What is the root cause of that problem?
We have added these styles which reduces the opacity - 

https://github.com/Expensify/App/blob/4d250acb0fe1a54088c4f761d054e6c9c174fc97/src/components/ReportActionItem/TaskPreview.tsx#L115-L116

But As mentioned in this comment (which is later approved as well)

https://github.com/Expensify/App/pull/48552#issuecomment-2336736659

The requirements are - 
```
Just to confirm here:

The checkbox and the text won't be faded off
The avatar will be faded off
The text will be strikethrough
```

### What changes do you think we should make in order to solve the problem?
We shall remove -

https://github.com/Expensify/App/blob/4d250acb0fe1a54088c4f761d054e6c9c174fc97/src/components/HTMLEngineProvider/BaseHTMLEngineProvider.tsx#L79-L84

```
...styles.textSupporting
```
From here.

<img width="1145" alt="Screenshot 2024-09-10 at 3 28 19 AM" src="https://github.com/user-attachments/assets/5646e4b1-8471-42e7-b6c6-1cf79e5bb3a9">


### What alternative solutions did you explore? (Optional)

**Comment by deetergp** [comment] 2024-09-09 22:06
As @rushatgabhane, this change is not a bug and was requested by our designers. 

@IuliiaHerets please update your tests to reflect that the avatar should be faded when the task is checked off.

**Comment by dubielzyk-expensify** [comment] 2024-09-10 00:08
> @rushatgabhane In this design the avatar is not grey https://github.com/Expensify/App/pull/48552#issuecomment-2338141735

Yeah I believe that's just a tiny error by @dannymcclain . This isn't a bug. We want the avatar to be faded out and the text to be strikedthrough with text supporting color. The video recording in the original post looks like what we want 👍

**Comment by shawnborton** [comment] 2024-09-10 06:30
Yup, agree with all of that Jon. So can we close this then?

**Comment by dannymcclain** [comment] 2024-09-10 14:04
>Yeah I believe that's just a tiny error by @dannymcclain.

Yes indeed! Sorry about that.

>This isn't a bug. We want the avatar to be faded out and the text to be strikedthrough with text supporting color. The video recording in the original post looks like what we want 👍

Agree. All looks well here. We can definitely close this one.

**Closed** 2024-09-10 18:13 UTC
Labels: External, Engineering, Daily, Help Wanted, Bug
