### ISSUE TITLE
[Wave9] [$500] Sign up - User is signed out after validation account created via old dot path

### ISSUE THREAD

**Issue by hayata-suenaga** [Expensify/App#34595] opened 2024-01-16 17:58 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:**
**Reproducible in staging?:**
**Reproducible in production?:**
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:**
**Slack conversation:**

## Action Performed:
1. Go to staging.expensify.com
2. Click Email
3. Input new email -> please use a gmail email. Temp Email doesn't work. When the email is a gmail account, it takes you to the NewDot, which I need to reproduce this.
4. Click Join
5. You're navigated to NewDot. Go to Profile \ Contact method
6. Click Didn't receive magic code
7. Input verification code

## Expected Result:
Account should be verified. User should stay logged in

## Actual Result:
User is signed out from New Expensify after typing the magic code.

## Workaround:
Can the user still use Expensify without this being fixed? Have you informed them of the workaround?

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

https://github.com/Expensify/App/assets/98560306/14b077ba-0f9e-4f65-a046-18d7f159e342

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~013f74161e8c07ceee</li>
        <li>Upwork Job ID: 1747317457231319040</li>
        <li>Last Price Increase: 2024-02-06</li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @hayata-suenaga</details>

**Comment by DylanDylann** [comment] 2024-01-17 04:00
## Proposal
                      
### Please re-state the problem that we are trying to solve in this issue.
- Sign up - User is signed out after validation account created via old dot path
### What is the root cause of that problem?
- After entering an Email and clicking on button "Join" in OD, it will redirect user to the ND.
- In ND, go to setting => profile => contact-method => contact-method/detail, then enter the magic code, the session has expired (In essence, it validates the email, so the old authToken of the login passwordless method without email verification will be invalidated).
- And we have the logic that will sign out here:
https://github.com/Expensify/App/blob/a2f5bd5898eafc53801807c37929afaae8a23666/src/pages/settings/Profile/Contacts/ContactMethodDetailsPage.js#L136-L139 

### What changes do you think we should make in order to solve the problem?
 when API ValidateSecondaryLogin is called, beside the ```loginList``` data, BE should return new authToken, credentials to update to Onyx and then, we can update the app to make sure it works properly, for example, authenticatePusher. So, with this solution, the user do not need to signe out. 
- First, create a variable ```shouldUpdateSession``` in [here](https://github.com/Expensify/App/blob/main/src/pages/settings/Profile/Contacts/ContactMethodDetailsPage.js)
```
const shouldUpdateSession = isDefaultContactMethod && !loginData.validatedDate && !isFailedAddContactMethod
```
- And then updating:
https://github.com/Expensify/App/blob/d985a0ee2604686911f34c99f5298af059622244/src/pages/settings/Profile/Contacts/ContactMethodDetailsPage.js#L121-L130
to:
````diff
    componentDidUpdate(prevProps) {
        const validatedDate = lodashGet(this.props.loginList, [this.getContactMethod(), 'validatedDate']);
        const prevValidatedDate = lodashGet(prevProps.loginList, [this.getContactMethod(), 'validatedDate']);

        // Navigate to methods page on successful magic code verification
        // validatedDate property is responsible to decide the status of the magic code verification
+        if(shouldUpdateSession){
+            // Update session logic here
+  PusherConnectionManager.init();
+        Pusher.init({
+            appKey: CONFIG.PUSHER.APP_KEY,
+            cluster: CONFIG.PUSHER.CLUSTER,
+            authEndpoint: `${CONFIG.EXPENSIFY.DEFAULT_API_ROOT}api?command=AuthenticatePusher`,
+        }).then(() => {
+            User.subscribeToUserEvents();
+        });
+            return
+        }
        if (!prevValidatedDate && validatedDate) {
            Navigation.goBack(ROUTES.SETTINGS_CONTACT_METHODS.route); 
        }
    }
````
### What alternative solutions did you explore? (Optional)
- NA

**Comment by bernhardoj** [comment] 2024-01-17 05:21
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
After validating our main account that was created from OldDot, we got signed out from the app.

### What is the root cause of that problem?
We have a logic here to sign out the user after they successfully validate their default/main contact method.
https://github.com/Expensify/App/blob/a2f5bd5898eafc53801807c37929afaae8a23666/src/pages/settings/Profile/Contacts/ContactMethodDetailsPage.js#L132-L139

It was added to "fix" https://github.com/Expensify/App/issues/31856 where the user is signed out when trying to change the workspace currency because the session has expired after validating the account, so their solution is to sign out early, but this gives a bad experience.

### What changes do you think we should make in order to solve the problem?

When the session expires and we make an API request, we already have a logic to [re-authenticate](https://github.com/Expensify/App/blob/a2f5bd5898eafc53801807c37929afaae8a23666/src/libs/Middleware/Reauthentication.ts#L73-L95), but somehow it always fails because of this 404 error and we get [signed-out if fail](https://github.com/Expensify/App/blob/a2f5bd5898eafc53801807c37929afaae8a23666/src/libs/Authentication.ts#L75-L85).
<img width="721" alt="image" src="https://github.com/Expensify/App/assets/50919443/b91178a8-ab80-4bc5-ac03-ab49f964f3e5">

So, in my opinion, the real fix here is to fix the reauth API error and remove the [sign-out early code](https://github.com/Expensify/App/blob/a2f5bd5898eafc53801807c37929afaae8a23666/src/pages/settings/Profile/Contacts/ContactMethodDetailsPage.js#L132-L139).

**Comment by hayata-suenaga** [comment] 2024-01-18 18:24
@0xmiroslav do we have satisfactory proposal? Do we need backend changes?

**Comment by hayata-suenaga** [comment] 2024-01-22 14:17
seems like the backend change is needed. @0xmiroslav could you check and confirms the proposals and summarize what needs to be changed in the backend if any is needed?

**Comment by mallenexpensify** [comment] 2024-01-24 03:31
@eVoloshchak reassigning, please take over as C+. If you don't have bandwidth, unassign yourself. Thanks

**Comment by hayata-suenaga** [comment] 2024-01-24 18:23
sorry this issue completely slipped off my mind. working on this again.

**Comment by hayata-suenaga** [comment] 2024-01-25 17:14
@bernhardoj @eVoloshchak

Which API command was used for the network request in [this proposal's screenshot](https://github.com/Expensify/App/issues/34595#issuecomment-1894961249)?

**Comment by bernhardoj** [comment] 2024-01-25 17:21
@hayata-suenaga it's an `Authenticate` request that is made from here

https://github.com/Expensify/App/blob/95631f67f1c24b5228abe83ee8f970c45925e3e5/src/libs/Authentication.ts#L53-L64
https://github.com/Expensify/App/blob/95631f67f1c24b5228abe83ee8f970c45925e3e5/src/libs/Authentication.ts#L23-L28

> I couldn't find any request resulted in 404 when I authenticated the account that I created on OldDot.

After validating the main account, try to create a new workspace. (or any action that requires authenticated user)

**Comment by hayata-suenaga** [comment] 2024-01-26 16:25
I'm still a little bit confused here as I'm not well versed in the authentication flow

I don't see `Authenticate` command called when I tries to validate the account that was created in OldDot.

![Screenshot 2024-01-26 at 8 24 37 AM](https://github.com/Expensify/App/assets/98560306/29e37037-09c2-4929-b53f-024d60d7c0bc)

Which command needs to changed in what way?

**Comment by bernhardoj** [comment] 2024-01-27 04:12
> After validating the main account, try to create a new workspace. (or any action that requires authenticated user)

Have you tried creating a new workspace after validating?

**Comment by hayata-suenaga** [comment] 2024-01-29 18:23
@bernhardoj I apologize but I need more explanation on this. Could you help me understand why creating a workspace is relevant to this sign out issue?

**Comment by bernhardoj** [comment] 2024-01-30 04:36
@hayata-suenaga it's actually not limited to creating a workspace but any request that requires an authenticated user and one of the examples is creating a workspace. When we create a new workspace after validating our main account, the API request will return 407, not authenticated code which will trigger Reauthentication middleware but it fails and this logic below will log the user out.
https://github.com/Expensify/App/blob/1b1eeb81cf1dd3b439b53b94abf4c476c792aa74/src/libs/Authentication.ts#L75-L85

**Comment by hayata-suenaga** [comment] 2024-01-30 17:23
okay I think I'm getting close to understanding the issue

but what is exactly the reason that the user is logged out after validating their account? Which API command is exactly the issue?

**Comment by bernhardoj** [comment] 2024-01-31 03:18
It's because of this logic

https://github.com/Expensify/App/blob/4e88eea26a79c7d69e3bf9fac28a515586c3855b/src/pages/settings/Profile/Contacts/ContactMethodDetailsPage.js#L132-L139

**Comment by hayata-suenaga** [comment] 2024-02-02 18:23
I was stamped with all regressions from Wave 8 but I believe I have time next week to work on this 🙇

**Comment by hayata-suenaga** [comment] 2024-02-05 03:33
[`Authenticate` command](https://github.com/Expensify/Web-Expensify/blob/e14355bc5aa512731e28ed976a09098137bc7a2c/api.php#L2635C5-L2635C45)

**Comment by hayata-suenaga** [comment] 2024-02-05 04:02
I deleted this part of the code

https://github.com/Expensify/App/blob/a2f5bd5898eafc53801807c37929afaae8a23666/src/pages/settings/Profile/Contacts/ContactMethodDetailsPage.js#L136C12-L140C25

I wanted to investigate the re-authentication issue that occurs when the code doesn't re-authenticate early, as per the above code. After validating the account I created on OldDot and navigating back from the Account Settings page, I was logged out. This likely happened because the app calling the `OpenReport` command, which requires authentication. However, I did not encounter the 404 error with `Authenticate`  command shown in [[the screenshot](https://github.com/Expensify/App/issues/34595#issuecomment-1894961249)](https://github.com/Expensify/App/issues/34595#issuecomment-1894961249) you provided. The `Authenticate`  command was successful, as shown in the screenshot below. Yet, the `OpenReport`  command failed. Without being able to inspect the response from the OpenReport command, I cannot determine why it failed.

Should I continue to address the issue with the Authenticate API command, or could the error potentially lie elsewhere?

I apologize for my slow grasp of the issue. This is my first time delving into the app's authentication mechanism. I sincerely appreciate your help.

 ![Screenshot 2024-02-04 at 7 46 48 PM](https://github.com/Expensify/App/assets/98560306/b71864ea-304c-4119-9ea6-362ef9645818) 
![Screenshot 2024-02-04 at 7 48 10 PM](https://github.com/Expensify/App/assets/98560306/40130694-25c9-4624-9f7a-24576542bd15)
![Screenshot 2024-02-04 at 7 48 27 PM](https://github.com/Expensify/App/assets/98560306/9156bded-a3c0-4b6a-84a3-7f897711ca59)

**Comment by bernhardoj** [comment] 2024-02-06 09:37
@hayata-suenaga I can still see the Authenticate fails. Even though the status code is 200, the response code is 407. Please check the video below.


https://github.com/Expensify/App/assets/50919443/873910a4-1e76-471b-bf85-8ddf68c53168

**Comment by hayata-suenaga** [comment] 2024-02-06 18:55
> @hayata-suenaga I can still see the Authenticate fails. Even though the status code is 200, the response code is 404/407. Please check the video below.

ah I see! I forgot to check the response code inside the JSON. Thank you for reminding of that 🙇

**Comment by hayata-suenaga** [comment] 2024-02-09 18:17
will resume working on this

**Comment by hayata-suenaga** [comment] 2024-02-12 01:30
### Memo for myself

The `Authenticate` API command fails. This command is called when the user tries to perform an action that required the authenticated state after validating the account created on OldDot.


The error is captured in the following screenshot:

![Screenshot 2024-02-11 at 5 29 50 PM](https://github.com/Expensify/App/assets/98560306/8de376d4-93e8-4e25-b16e-1273b5060e64)

The above error stems from the following part of `Auth`.

https://github.com/Expensify/Auth/blob/d46723155972c7c50e3e871158dd1cc5e4f26268/auth/command/Authenticate.cpp#L152

**Comment by hayata-suenaga** [comment] 2024-02-12 02:09
Asking for some info in [the engineering-chat slack channel](https://expensify.slack.com/archives/C03TQ48KC/p1707703570216299).

**Comment by hayata-suenaga** [comment] 2024-02-13 18:27
I'm still working on it

this is [the latest question](https://expensify.slack.com/archives/C03TQ48KC/p1707800618693909?thread_ts=1707703570.216299&cid=C03TQ48KC) I'm asking about this issue on Slack

**Comment by strepanier03** [comment] 2024-02-16 00:09
Got it, thanks for the updates @hayata-suenaga

**Comment by hayata-suenaga** [comment] 2024-02-19 16:13
I was focusing writing the design doc for the QBO project. I've [asked help](https://expensify.slack.com/archives/C03TQ48KC/p1708021260741309?thread_ts=1707703570.216299&cid=C03TQ48KC) from other engineers with the authentication logic, but I haven't received any replies.

Will start investing this more myself this week.

**Comment by strepanier03** [comment] 2024-02-21 22:18
Appreciate the update @hayata-suenaga - let me know if there's something I can do to help or any testing you want done, I'll help the best I can.

**Comment by hayata-suenaga** [comment] 2024-02-24 15:32
still having trouble understanding the authentication mechanisms. Bumped my previous question [on Slack](https://expensify.slack.com/archives/C03TQ48KC/p1708788195331759?thread_ts=1707703570.216299&cid=C03TQ48KC). I also [posted a regression note ](https://github.com/Expensify/App/issues/31856#issuecomment-1962398314)to the issue that caused this bug.

**Comment by strepanier03** [comment] 2024-03-01 03:51
Thank you @hayata-suenaga - I got caught up on the thread and will continue to follow this. Don't hesitate to let me know if there's something you need that I can help with.

**Comment by hayata-suenaga** [comment] 2024-03-01 19:15
thank you for the offer of help 😄 out of the discussion, now I know what I need to do here. I just didn't have time this week. I'll work on this early next week 🙇

**Comment by hayata-suenaga** [comment] 2024-03-04 21:40
will resume working on this this week

**Comment by hayata-suenaga** [comment] 2024-03-07 20:39
made a draft Auth PR

**Comment by hayata-suenaga** [comment] 2024-03-11 19:48
there is a failing integration test. I'll fix it today

**Comment by hayata-suenaga** [comment] 2024-03-13 21:10
I'm addressing PR review

**Comment by strepanier03** [comment] 2024-03-15 16:50
Thanks for all the updates @hayata-suenaga - Let me know if there's anything you need me to do or help with!

**Comment by hayata-suenaga** [comment] 2024-03-19 17:03
I'm still fixing the RP for the failed tests

**Comment by strepanier03** [comment] 2024-03-25 18:17
Thank you for your update, @hayata-suenaga .

**Comment by hayata-suenaga** [comment] 2024-03-26 15:37
I'm been postposing this issue for a long time. I'm resume working on this today 🙇

**Comment by hayata-suenaga** [comment] 2024-04-02 15:58
PR is ready for review

**Comment by bernhardoj** [comment] 2024-04-09 10:23
@hayata-suenaga I can help with the App PR if you need (as I propose the FE change)

**Comment by hayata-suenaga** [comment] 2024-04-09 16:50
Thank you for the offer of help. I already have a draft PR so I'll finish this myself 😄

**Comment by hayata-suenaga** [comment] 2024-04-12 19:10
I've been busy with the QBO project and the fire. I'll work on this soon.

**Comment by hayata-suenaga** [comment] 2024-04-15 17:38
I'll work on this this week

**Comment by hayata-suenaga** [comment] 2024-04-29 22:12
sorry, I have been occupied with the QBO project. Let me come back to this after the QBO project lease is over. Probably some time next week. 🙇

**Comment by strepanier03** [comment] 2024-05-08 23:49
Sounds good thanks @hayata-suenaga, good luck on the rest of QBO 🍀

**Comment by hayata-suenaga** [comment] 2024-05-09 01:10
I'll make the PR ready tonight

**Comment by hayata-suenaga** [comment] 2024-06-05 06:27
will resume working on [the App PR](https://github.com/Expensify/App/pull/35791)

**Closed** 2024-08-01 18:33 UTC
Labels: Reviewing, Engineering, Monthly, Internal, Bug
