### ISSUE TITLE
[$250] Dev - Console error after sign in

### ISSUE THREAD

**Issue by kavimuru** [Expensify/App#21760] opened 2023-06-27 21:53 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. User A requests money from user B
2. User B opens the chat with A. Verify in user B you see the green button Pay in the last message
3. User B signs out from the app
4. User B reloads the app
5. User B signs in
6. Verify when user B is signed in, the chat with user A is open
## Expected Result: 
No console error
## Actual Result: 
Console error (invalid prop payPalMeData) shows

## Workaround:
Can the user still use Expensify without this being fixed? Have you informed them of the workaround?

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [x] MacOS / Chrome / Safari
- [ ] MacOS / Desktop
 
**Version Number:** 
**Reproducible in staging?:** Dev
**Reproducible in production?:** Dev
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/43996225/e0576c30-7b87-4aea-8fc9-606e24df14aa

**Expensify/Expensify Issue URL:**
**Issue reported by:** @bernhardoj 
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1687776393036369

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~018d0dd3fea0bd5872</li>
        <li>Upwork Job ID: 1679736611365277696</li>
        <li>Last Price Increase: 2023-07-21</li>
    </ul>
</details>

**Comment by alexpensify** [comment] 2023-06-29 22:38
Reassigning another bug team member, I'm going OOO until Monday, July 10, and will take it back if it's still open by my return date.

Required action from the 🐛 team: I've run out of time and haven't tested this one yet. This needs testing to confirm if it's a bug, check if it's a dupe, and then assign the applicable labels. Thank you!

**Comment by JmillsExpensify** [comment] 2023-07-05 12:44
Slammed with bug reports. I'll close the loop on these today.

**Comment by alexpensify** [comment] 2023-07-10 21:17
@JmillsExpensify -- I'm back online. Were you able to test this one or should we close since it's about 2 weeks old now?

**Comment by JmillsExpensify** [comment] 2023-07-12 13:01
It's a DEV issue so we can't reproduce. @mountiny Are you going to touch Paypal stuff anytime soon? I know we talked about this one recently and what the future looks like.

**Comment by mountiny** [comment] 2023-07-12 20:15
I will look into this one

**Comment by mountiny** [comment] 2023-07-13 22:12
Pr in review

**Comment by alexpensify** [comment] 2023-07-14 18:58
Thank you @JmillsExpensify for pushing this one forward. I'm going to take it back over since we have a plan in place.

**Comment by alexpensify** [comment] 2023-07-16 17:28
PR is still in review

**Comment by alexpensify** [comment] 2023-07-18 20:24
The PR was merged!

**Comment by alexpensify** [comment] 2023-07-20 21:11
@mountiny - this one moved to production, are we good to issue the payment for the review here? Thanks!

**Comment by mountiny** [comment] 2023-07-20 23:07
@alexpensify yes please $250 to @bernhardoj

**Comment by alexpensify** [comment] 2023-07-21 14:42
Alright, I've prepared the payment in Upwork for @bernhardoj. Please accept and then I can complete the process. After that, I'll close this GH. Thank you!

**Comment by alexpensify** [comment] 2023-07-21 19:37
All set @bernhardoj has been paid via Upwork. Thank you for your help here! I'm going to close this GH now.

**Closed by alexpensify** 2023-07-21 19:37 UTC
Labels: Daily, Internal, Help Wanted, Bug
