### ISSUE TITLE
[HOLD for payment 2024-01-24] [$500] Web - Workspace - The initial selection applies to the new name too

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#33652] opened 2023-12-27 18:03 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.17.1
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** Applause - Internal Team
**Slack conversation:**

## Action Performed:
1. Navigate to https://staging.new.expensify.com/
2. Log in with an expensifail account
3. Create a workspace
4. Create a room named "asd"
5. Rename the room by selecting "asd" and replacing it with this text from the clipboard "the user is able to select"

## Expected Result:
The previous selection shouldn't be applied to the pasted text.

## Actual Result:
The initial selection applies to the new name too.

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

https://github.com/Expensify/App/assets/93399543/1dea7fba-2982-4000-886b-82664cbaad9b

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by paultsimura** [comment] 2023-12-27 18:32
## Proposal

### Please re-state the problem that we are trying to solve in this issue.


### What is the root cause of that problem?
This is happening because of the following code: 

https://github.com/Expensify/App/blob/054eb86c638dc35d4a28bf71ad7788adf8a2256a/src/components/RoomNameInput/index.js#L35-L42

### What changes do you think we should make in order to solve the problem?

We should check if there was an active selection. If there was – we should move the cursor to the end of the replaced text:

```js
            let newSelection;
            if (selection.start === selection.end) {
                newSelection = {
                    start: selection.start + offset,
                    end: selection.end + offset,
                };
            } else {
                newSelection = {
                    start: selection.end + offset,
                    end: selection.end + offset,
                };
            }

            setSelection(newSelection);
```



### What alternative solutions did you explore? (Optional)

**Comment by yh-0218** [comment] 2023-12-27 19:04
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
Web - Workspace - The initial selection applies to the new name too
### What is the root cause of that problem?
This is happening because of the following code:
https://github.com/Expensify/App/blob/054eb86c638dc35d4a28bf71ad7788adf8a2256a/src/components/RoomNameInput/index.js#L35-L42
### What changes do you think we should make in order to solve the problem?
We need to remove this logic.
### What alternative solutions did you explore? (Optional)

**Comment by yh-0218** [comment] 2023-12-27 19:28
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
When replacing the text in the room name, the selection remains.
### What is the root cause of that problem?
This is happening because of the following code:
https://github.com/Expensify/App/blob/054eb86c638dc35d4a28bf71ad7788adf8a2256a/src/components/RoomNameInput/index.js#L35-L42
### What changes do you think we should make in order to solve the problem?
We need this logic and add new.
```js
if (modifiedRoomName !== newRoomNameWithHash) {
      const newSelection = {
          start: modifiedRoomName.length,
          end: modifiedRoomName.length,
      };
      setSelection(newSelection);
  }
```
### What alternative solutions did you explore? (Optional)

**Comment by getusha** [comment] 2023-12-29 11:10
@paultsimura your RCA makes sense, but i am not sure why this is happening on texts with space between words. i am trying to test the solution.

**Comment by paultsimura** [comment] 2023-12-29 11:14
> i am not sure why this is happening on texts with space between words

This is because, in the room names, the spaces (and only spaces) get replaced with dashes:

https://github.com/Expensify/App/blob/5c5c862a10b75214899da32333a7f3a694e38be3/src/libs/RoomNameInputUtils.ts#L6-L14

And because of this, only for the names with spaces, this condition becomes `true`:

https://github.com/Expensify/App/blob/5c5c862a10b75214899da32333a7f3a694e38be3/src/components/RoomNameInput/index.js#L35-L42

**Comment by getusha** [comment] 2024-01-01 13:54
Testing proposals.

**Comment by paultsimura** [comment] 2024-01-01 13:57
@getusha does this explanation make sense to you though? https://github.com/Expensify/App/issues/33652#issuecomment-1871961619

**Comment by getusha** [comment] 2024-01-01 13:59
>And because of this, only for the names with spaces, this condition becomes true:

@paultsimura Can't we  instead compare the length of the strings like ` if (modifiedRoomName.length !== newRoomNameWithHash.length)` then?

**Comment by paultsimura** [comment] 2024-01-01 14:08
> Can't we instead compare the length of the strings

We must compare the string values here. If we enter "some text", it will be transformed into "some-text", so the length will be the same and the logic will not be executed. As a result, the cursor will jump to the end of the input every time a space is added, and this logic was added to fix exactly this:


https://github.com/Expensify/App/assets/12595293/d014c54b-d606-4b92-b5c9-7d988652d174

The whole logic is correct, we just need to handle the selection start as I've described in the proposal.

**Comment by JmillsExpensify** [comment] 2024-01-03 18:34
Discussing proposals

**Comment by getusha** [comment] 2024-01-04 15:13
The [proposal](https://github.com/Expensify/App/issues/33652#issuecomment-1870537268) from @paultsimura looks good to me and works well, thanks for the patience!
🎀 👀 🎀 
C+ Reviewed!

**Comment by marcaaron** [comment] 2024-01-05 22:45
Proposal looks ok. The bug feels very minor to me. I am surprised we have such complex logic for pasting text into an input.

**Comment by paultsimura** [comment] 2024-01-06 15:50
Thanks. The PR is ready for review: https://github.com/Expensify/App/pull/34076

**Comment by JmillsExpensify** [comment] 2024-01-26 15:50
@getusha Mind helping get us kicked off with the BZ checklist?

**Comment by JmillsExpensify** [comment] 2024-01-26 15:51
Payment summary:

 - Issue reporter: QA
 - Contributor: @paultsimura $500
 - Contributor+: @getusha $500

**Comment by JmillsExpensify** [comment] 2024-01-26 15:54
Offers sent to both contributors!

**Comment by paultsimura** [comment] 2024-01-26 16:18
Thanks, accepted

**Comment by getusha** [comment] 2024-01-26 16:38
**BugZero Checklist:** The PR fixing this issue has been merged! The following checklist ([instructions](https://stackoverflow.com/c/expensify/questions/14574)) will need to be completed before the issue can be closed:

 [@getusha] The PR that introduced the bug has been identified. Link to the PR: https://github.com/Expensify/App/pull/
 
[@getusha] The offending PR has been commented on, pointing out the bug it caused and why, so the author and reviewers can learn from the mistake. Link to comment: https://github.com/Expensify/App/pull/12899/files#r1467873981
 
[@getusha] A discussion in #expensify-bugs has been started about whether any other steps should be taken (e.g. updating the PR review checklist) in order to catch this type of bug sooner. Link to discussion: N/a
 
[@getusha] Determine if we should create a regression test for this bug. **No, this is a very minor bug**
 
 [@getusha] If we decide to create a [regression test](https://github.com/Expensify/App/blob/main/contributingGuides/REGRESSION_TEST_BEST_PRACTICES.md) for the bug, please propose the regression test steps to ensure the same bug will not reach production again.

**Comment by JmillsExpensify** [comment] 2024-01-27 16:29
Thanks @getusha. Those make sense to me. I've processed your offer in Upwork so I'll close this issue.

**Closed by JmillsExpensify** 2024-01-27 16:29 UTC
Labels: External, Weekly, Awaiting Payment, Bug
