### ISSUE TITLE
[NEEDS REPRO] IOU - App crashes when changing the date for IOU

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#25837] opened 2023-08-24 12:15 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Open the app
2. Tap the FAB and select "Request money"
3. Complete the money request flow
4. Open the IOU in the chat history
5. Select Money Request Preview to open Money Request Details
6. Change the date

## Expected Result:
User is navigated back to the Money Request Details and can continue interacting with the app

## Actual Result:
The app crashes. Also, selecting an IOU crashes the app.
On iOS native app, the empty box instead of the receipt image is displayed and the Money Request Preview gets expanded after performing the same steps, but the app does not crash

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [ ] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 1.3.56-18

**Reproducible in staging?:** Yes

**Reproducible in production?:** Yes

**If this was caught during regression testing, add the test name, ID and link from TestRail:**

**Email or phone of affected tester (no customers):**

**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/78819774/ea3808db-5e2d-4152-8d5a-c4ae7ed316f8

https://github.com/Expensify/App/assets/78819774/d46351aa-54bf-4ef9-a8c1-99c73863ca65

**Expensify/Expensify Issue URL:**

**Issue reported by:** Applause - Internal Team

**Slack conversation:**

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by pradeepmdk** [comment] 2023-08-24 14:46
same root case https://github.com/Expensify/App/issues/25841#issuecomment-1691821920

**Comment by kadiealexander** [comment] 2023-08-29 06:00
Not overdue, sorry was OOO last week. Reassigning to JLi as we have an agreement to swap iOS and Android bugs.

**Comment by jliexpensify** [comment] 2023-08-29 06:13
@pradeepmdk can you elaborate on your comment re: the same root cause? As that GH is closed (the last comment was that it was no longer reproducible), are you saying that the solution to this issue is what you've previously proposed?

**Comment by jliexpensify** [comment] 2023-08-29 06:17
I am also struggling to repro this on v1.3.58-1 on a Pixel 3a - I can change the date with no issues. @pradeepmdk and @lanitochka17 can you please try repro-ing on the newest Android app version and share a video here?

**Comment by pradeepmdk** [comment] 2023-08-29 06:34
@jliexpensify  as this fixed by the backend from this PR https://github.com/Expensify/App/issues/25841#issuecomment-1692081987.

**Comment by jliexpensify** [comment] 2023-08-29 06:51
Got it, thanks for clarifying! I can't reproduce this issue so closing this out.

**Closed by jliexpensify** 2023-08-29 06:51 UTC
Labels: Daily, Needs Reproduction, Bug
