### ISSUE TITLE
[$500]  Distance - Inconsistency in error message when more than two same adddress is added

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#29803] opened 2023-10-17 17:36 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.3.85-0

**Reproducible in staging?:** Yes

**Reproducible in production?:** Yes

**If this was caught during regression testing, add the test name, ID and link from TestRail:**

**Email or phone of affected tester (no customers):**

**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Expensify/Expensify Issue URL:**

**Issue reported by:** Applause - Internal Team

**Slack conversation:**

## Action Performed:
1. Launch New Expensify app
2. Go to + > Request money > Distance
3. Enter the same address for both Start and Finish point
4. Tap Next
5. Note the error message is 'Please remove duplicate waypoints'
6. Tap Add stop and add the same address and save it
7. Tap Next

## Expected Result:
The error message should still be 'Please remove duplicate waypoints'

## Actual Result:
The error message now shows 'Please enter at least two waypoints'

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [x] Android: mWeb Chrome
- [x] iOS: Native
- [x] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos
<details>
<summary>Android: Native</summary>

 

https://github.com/Expensify/App/assets/78819774/98a6a710-2a05-4ee4-b885-6090ee1ccccc

</details>

<details>
<summary>Android: mWeb Chrome</summary>

</details>

<details>
<summary>iOS: Native</summary>

</details>

<details>
<summary>iOS: mWeb Safari</summary>

</details>

<details>
<summary>MacOS: Chrome / Safari</summary>

</details>

<details>
<summary>MacOS: Desktop</summary>

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~018cedadf58c08d896</li>
        <li>Upwork Job ID: 1714334639555403776</li>
        <li>Last Price Increase: 2023-10-17</li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @GabiHExpensify</details>

**Comment by tgolen** [comment] 2023-10-17 18:16
@BhuvaneshPatil this is related to the changes in https://github.com/Expensify/App/pull/29125. Can you work on correcting this, please?

**Comment by kuttyhub** [comment] 2023-10-18 00:14
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
Inconsistent error message while adding duplicate waypoints.

### What is the root cause of that problem?
The root cause for this problem is the logic used in the onError function that returns the error message, which checks duplication only the waypoints have no additional points init  `_.keys(waypoints).length === 2` .
which leads to hit to the final if conditions and returns the `Please enter at least two waypoints`.
https://github.com/Expensify/App/blob/b494186cafdd4706a7ddb2127a0442ee90f8ebe7/src/components/DistanceRequest/index.js#L148-L162




also, I noticed the error handling is not done properly and it only checks if it has any two valid points. That introduces bugs like allowing duplicate waypoints if they have any two valid points.
https://github.com/Expensify/App/blob/b494186cafdd4706a7ddb2127a0442ee90f8ebe7/src/components/DistanceRequest/index.js#L226-L233
https://github.com/Expensify/App/blob/b494186cafdd4706a7ddb2127a0442ee90f8ebe7/src/components/DistanceRequest/index.js#L185-L192 

check the recordings for the bug.
https://github.com/Expensify/App/assets/71143839/37328a72-1da2-452f-937e-76dc2794db9d



### What changes do you think we should make in order to solve the problem?
to fix the error handling properly we can introduce the memo variable ` hasInValidWayPoints`  which tracks differences in original waypoints and validatedWaypoints which has the list of unique and valid waypoints.

```
const hasInValidWayPoints = useMemo(
  () => _.size(validatedWaypoints) < _.keys(waypoints).length ,
  [waypoints, validatedWaypoints]
)
```

Then update the OnError functions logic:

```
 const getError = () => {
        // Get route error if available else show the invalid number of waypoints error.
        if (hasRouteError) {
            return ErrorUtils.getLatestErrorField(transaction, 'route');
        }
        const startAddress = lodashGet(waypoints, 'waypoint0.address', {})
        const finalAddress = lodashGet(waypoints, 'waypoint1.address', {})
        // check start and final waypoints is empty
        if (_.keys(waypoints).length === 2 && (_.isEmpty(startAddress) || _.isEmpty(finalAddress))) {
            return { 0: translate('iou.error.emptyWaypointsErrorMessage') };
        }

        // Checking Duplicates in waypoints from start to end
        if (hasInValidWayPoints) {
            return {0: translate('iou.error.duplicateWaypointsErrorMessage')};
        }
    };
```

Then update the logic on submitWaypoints to prevent submission and set hasError to true.
 ``` 
  const submitWaypoints = useCallback(() => {
        // If there is any error or loading state, don't let user go to next page.
        if ( hasInValidWayPoints || hasRouteError || isLoadingRoute || isLoading) {
            setHasError(true);
            return;
        }
        onSubmit(waypoints);
    }, [onSubmit, setHasError, hasRouteError, isLoadingRoute, isLoading, waypoints, hasInValidWayPoints]);
```

Then update the logic on showing error in view.
```
  {/* Show error message if there is route error or there are less than 2 routes and use

r has tried submitting, */}
  {((hasError && hasInValidWayPoints) || hasRouteError) && (
      <DotIndicatorMessage
          style={[styles.mh4, styles.mv3]}
          messages={getError()}
          type="error"
      />
  )}
```
by using the `hasInValidWayPoints`  value now we can properly update `hasError` state and it prevents submitting.  demo here,
https://github.com/Expensify/App/assets/71143839/c5afa8d2-d60e-41cb-a029-9f4725056e06

### What alternative solutions did you explore? (Optional)
N/A

**Comment by kuttyhub** [comment] 2023-10-18 00:17
Contributor details
Your Expensify account email: nishanthsundaraj@outlook.com
Upwork Profile Link: https://www.upwork.com/freelancers/~018770a46267a23e10

**Comment by kuttyhub** [comment] 2023-10-18 15:37
Thanks @tgolen for the advice, I will keep it my mind for future proposals. I have one doubt regards the sub bug I found which allows submission when you have any two valid waypoints even though its contains duplicates. Is that expected behaviour?

**Comment by kuttyhub** [comment] 2023-10-18 15:50
Thanks @tgolen for the advice. I will keep it in my mind for future proposals. I have doubt about the sub-bug I found. which allows submission when the waypoints have any two valid points even though it contains duplicates/non valid waypoints. Is that expected behaviour?

**Comment by kuttyhub** [comment] 2023-10-18 16:45
>It was kind of difficult to write this up, so I would actually welcome any proposals to simplify this even further. Maybe we should only have a single error case? Would that make it less confusing? Let's maybe consider some out-of-the-box solutions that would refactor this a bit.

Thanks for the detailed explanation @tgolen. In my view, we need two error messages for the proper UX experience.

The thing we confused because the duplication errors only showed for partial cases. 
like `A>A>A`
unlike `A>B>A` which is handled by the backend as you said. But it gives doubt to people who don't know about it.

that's why @dukenv0307 thought the scenario should be handled by the UI.

so, for a better UX experience, I would suggest, handle the unlikely cases in the UI itself and send only valid waypoints to the backend. Which is straightforward.

please add your thoughts on this approach.

**Comment by tgolen** [comment] 2023-10-18 17:04
@kuttyhub I'm not sure what you're asking for. If you'd like to change your proposal, I can give another look at it. At this point I think that @dukenv0307's proposal is more comprehensive.

**Comment by kuttyhub** [comment] 2023-10-18 17:24
I am good with my current proposal @tgolen.

**Comment by tgolen** [comment] 2023-10-18 17:27
@ntdiary sounds like [the proposal](https://github.com/Expensify/App/issues/29803#issuecomment-1767624097) from @dukenv0307 is the most comprehensive and covers the most cases, so we should go with that one.

**Comment by kuttyhub** [comment] 2023-10-18 18:31
[updated proposal](https://github.com/Expensify/App/issues/29803#issuecomment-1767387775) @tgolen, @dukenv0307.
Found the root cause for that behaviour relies on the utill function `getValidWaypoints` only checks duplicates on neighbours only and doesn't check distant duplicates.

**Comment by tgolen** [comment] 2023-10-27 15:05
Sorry, I was OOO this week. I agree with @ntdiary and their suggestions. I especially like having just a single error message for `Please enter at least two different waypoints`.

**Comment by GabiHExpensify** [comment] 2023-11-01 21:13
Let's nix the word "waypoint", that's not really a word that people use colloquially. 

Could you update this message to, "Please enter a different starting and ending address"?

Alternatively, we could write, "The start and finish addresses are the same. Please update one of them."

**Comment by GabiHExpensify** [comment] 2023-11-01 21:15
posted here to get some help with the spanish translation: https://expensify.slack.com/archives/C21FRDWCV/p1698873251740589

**Comment by GabiHExpensify** [comment] 2023-11-02 15:38
That looks great, thanks @tgolen! Are we good to go on the Spanish translation, or does that still need to be double-checked?

**Comment by GabiHExpensify** [comment] 2023-11-02 19:23
Here's Spanish:
> Por favor introduce al menos dos direcciones diferentes.

**Comment by tgolen** [comment] 2023-11-06 16:12
Thanks for the translations, Gabi! This should be merged soon.

**Comment by rakshitjain13** [comment] 2023-11-14 05:03
@dukenv0307 But I see ```getValidWaypoints``` has bug even now when start is empty but it is not creating any problem because of a recent change that add stop button will show only after start and end are there . But I think it is more of a workaround . For more details regarding the bug I am saying : https://github.com/Expensify/App/issues/29895#issuecomment-1769064322  cc: @tgolen .

**Comment by tgolen** [comment] 2023-11-27 16:50
@GabiHExpensify Can you help with the payments on this one? It is past the regression period, but looks like the automation didn't work for some reason.

**Comment by tgolen** [comment] 2023-12-04 16:01
bump @GabiHExpensify

**Comment by GabiHExpensify** [comment] 2023-12-04 18:31
ah sorry i missed your comment last week @tgolen -- i don't know anything about the payments, i'm just on this GH for the copy. should there be someone from the contributor team who handles that?

**Comment by tgolen** [comment] 2023-12-04 18:53
Oops, sorry about that! I'll get someone from the bugzero team.

**Comment by tgolen** [comment] 2023-12-04 18:56
@sonialiap Could you help us settle up some payments here? I _think_ this is what is needed:

- @dukenv0307 wrote [the PR](https://github.com/Expensify/App/pull/30548) so they need paid as a contributor
- @ntdiary reviewed and tested the PR so they need paid as a C+

**Comment by tgolen** [comment] 2023-12-05 16:54
bump @sonialiap

**Comment by tgolen** [comment] 2023-12-06 15:58
bump @sonialiap

**Comment by sonialiap** [comment] 2023-12-06 17:02
@dukenv0307 contributor $500 - offer sent
@ntdiary reviewer $500 - offer sent

**Comment by sonialiap** [comment] 2023-12-08 09:49
Everyone has been paid ✔️ 
Seems like we're good to close

**Closed by sonialiap** 2023-12-08 09:49 UTC
Labels: Reviewing, External, Daily, Bug
