### ISSUE TITLE
[$250] Chat - Chat history screen starts to shake when 'New Messages' badge appears

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#42308] opened 2024-05-16 16:45 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.74-1
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**If this was caught during regression testing, add the test name, ID and link from TestRail:** https://expensify.testrail.io/index.php?/tests/vifew/4565233
**Email or phone of affected tester (no customers):** fischer9966@gmail.com
**Issue reported by:** Applause - Internal Team

## Action Performed:
1. Open iOS App
2. Login with any account with long chats
3. Open any chat with long history
4. Clear any unread messages if needed.
5. Scroll up a few screens in the chat
6. Send a message to this chat from the second device

## Expected Result:
The "New Message" badge appears at the top of the screen without any distortion

## Actual Result:
Chat history screen starts to shake when 'New Messages' badge appears

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [x] iOS: Native
- [ ] iOS: mWeb Safari
- [ ] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details> 

https://github.com/Expensify/App/assets/78819774/06bc02cd-ec58-45ab-bbf2-832d9700a37d

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~011f7777bd257c3722</li>
        <li>Upwork Job ID: 1792568241125892096</li>
        <li>Last Price Increase: 2024-06-03</li>
    </ul>
</details>

**Comment by lanitochka17** [comment] 2024-05-16 16:47
@lschurr  FYI I haven't added the External label as I wasn't 100% sure about this issue. Please take a look and add the label if you agree it's a bug and can be handled by external contributors

**Comment by lanitochka17** [comment] 2024-05-16 16:47
We think that this bug might be related to #vip-vsp

**Comment by emilkaminski1022** [comment] 2024-05-20 18:18
Hello,  @jayeshmangwani
Let me try to solve this issue.
I think the one of these are listed below can be the cause.
1. The app might be trying to adjust the scroll position automatically when a new message arrives.
2. Inserting new messages might cause a full layout pass, leading to the shake.
3. Improper constraints might cause the entire view to re-layout in an unexpected way.
4. Frequent updates to the "New Message" badge can cause rapid layout changes.
I will find more.

**Comment by emilkaminski1022** [comment] 2024-05-20 18:31
Contributor details
Your Expensify account email: emilkaminski1022@gmail.com
Upwork Profile Link: Don't have.

**Comment by jayeshmangwani** [comment] 2024-05-21 19:50
@emilkaminski1022 Please check our [Contributing Guidelines](https://github.com/Expensify/App/blob/main/contributingGuides/CONTRIBUTING.md) to understand the process

**Comment by emilkaminski1022** [comment] 2024-05-22 10:21
Okay, thanks.

**Comment by jayeshmangwani** [comment] 2024-05-27 16:02
No proposals yet, Waiting on proposal

**Comment by lschurr** [comment] 2024-05-30 20:54
Still waiting on proposals.

**Comment by lschurr** [comment] 2024-05-30 23:42
Not overdue.

**Comment by lschurr** [comment] 2024-06-03 15:18
@jayeshmangwani can you confirm this bug is still happening?

**Comment by jayeshmangwani** [comment] 2024-06-04 04:41
@lschurr I just tested in latest app store build(v1.4.77-11) and issue is not happening for me, I can see the New Message badge and there no screen flickering.

https://github.com/Expensify/App/assets/35371050/c88b545c-12bc-4a1d-9e2f-4584994f4e75

**Comment by lschurr** [comment] 2024-06-04 17:07
Alright, thanks! I'm going to close this one since it's not happening anymore.

**Closed by lschurr** 2024-06-04 17:07 UTC
Labels: External, Daily, Help Wanted, Bug
