### ISSUE TITLE
[$500] Chat - Group chat is not shown in LHN until page refresh for Expensfail and gmail users

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#34768] opened 2024-01-18 20:00 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.27-1
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** Applause - Internal Team
**Slack conversation:**

## Action Performed:
1. Log into New Expensify with Gmail account on Device A
2. Log into New Expensify with Expensifail account on Device B
3. As Gmail user - click on FAB > create group chat with user logged in Device B and another gmail user
4. Send any message in the created group chat

## Expected Result:
Group chat should be immediately shown in Device B's LHN.

## Actual Result:
Describe what actually happened

## Workaround:
Can the user still use Expensify without this being fixed? Have you informed them of the workaround?

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [x] Android: mWeb Chrome
- [ ] iOS: Native
- [x] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

https://github.com/Expensify/App/assets/93399543/5e0f9979-9299-4b2c-9e9f-d777d91c7abd

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~012807f984a76e61da</li>
        <li>Upwork Job ID: 1748072934551138304</li>
        <li>Last Price Increase: 2024-01-25</li>
    </ul>
</details>

**Comment by kbecciv** [comment] 2024-01-18 20:01
@quintar  - #vip-vsb

**Comment by s-alves10** [comment] 2024-01-22 08:06
This issue has the same root cause as https://github.com/Expensify/App/issues/34757.

**Comment by JmillsExpensify** [comment] 2024-01-24 03:24
@mananjadhav Do you agree with that? If so, we can close it.

**Comment by mananjadhav** [comment] 2024-01-29 00:44
Yes we can close this one out @JmillsExpensify.

**Closed** 2024-01-29 00:50 UTC
Labels: External, Daily, Help Wanted, Bug
