### ISSUE TITLE
Seeing grey avatar for a brief moment when inviting a new user reported by @thesahindia

### ISSUE THREAD

**Issue by kavimuru** [Expensify/App#12786] opened 2022-11-16 17:24 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:

1. Navigate to settings > Workspaces
2. Select a workspace
3. Click on manage members
4. Click invite
5. Search a new user
6. Select and invite

## Expected Result: 
You shouldn't see the offline default avatar

## Actual Result: 
You will see the offline default avatar for a brief moment

## Workaround:
unknown

## Platform:

Where is this issue occurring?

- Web
- iOS
- Android
- Desktop App
- Mobile Web

**Version Number:** 1.2.28-0
**Reproducible in staging?:** y
**Reproducible in production?:** y
**Email or phone of affected tester (no customers):** 
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** 

https://user-images.githubusercontent.com/43996225/202250061-c15af0c7-dd0e-4085-848b-867b85522686.mov
https://user-images.githubusercontent.com/43996225/202250082-90f9be1c-7b24-48b1-8fc7-b2136a9789a5.mp4

**Expensify/Expensify Issue URL:** 
**Issue reported by:** @thesahindia 
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1668609896587349

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by JmillsExpensify** [comment] 2022-11-16 22:42
Potentially a dupe of https://github.com/Expensify/App/issues/11425. Check the Slack thread for more details.

**Comment by strepanier03** [comment] 2022-11-16 22:58
Thank you for linking this @JmillsExpensify I appreciate it a lot. After reviewing the behavior in both it does look like it could potentially be a dupe. 

The avatars in the GH you linked are a full grey circle whereas the avatar in the video in this GH is a grey offline avatar instead, so I'm not 100% sure they are the same issue.

@thesahindia - Would you mind checking https://github.com/Expensify/App/issues/11425 and weighing in on whether you think the behavior you reported is the same behavior reported in that GH?

If we're still unsure, I'll raise in the Slack thread for more opinions.

**Comment by thesahindia** [comment] 2022-11-17 08:33
I believe it's different because -
1. It was working correctly at some point (it's a regression)
2. [#11425](https://github.com/Expensify/App/issues/11425) is not reproducible for default avatars but the current issue is.

**Comment by strepanier03** [comment] 2022-11-17 22:13
Thank you @thesahindia, I really appreciate you getting to this so quickly. 

In light of that, I'll move forward with triaging and recreating the behavior and take the next appropriate action.

**Comment by strepanier03** [comment] 2022-11-18 01:01
Tested these steps on the following devices and I'm unable to recreate this. 

Google Chrome web browser on Mac
![2022-11-17_16-54-53 (1)](https://user-images.githubusercontent.com/10925636/202591745-37ed6701-9301-4f78-8f54-aae365927051.gif)

Android phone (Pixel 6)
No video, sorry.

Desktop app on Mac
![2022-11-17_16-58-29 (1)](https://user-images.githubusercontent.com/10925636/202592212-b6f82c01-c1e1-4977-8b1f-406333facd07.gif)

@thesahindia can you still reproduce this behavior? If so, can you tell me a bit more about how you are?

**Comment by thesahindia** [comment] 2022-11-18 07:06
Yep, it's still reproducible. To repro this you will need to search a new user (it shouldn't be in your contacts already).

**Comment by JmillsExpensify** [comment] 2022-11-18 08:00
I'm still not convinced that this separate issue, as I actually remembering seeing the same issue when the older report was created. Accordingly, I think we need to take the discussion back to the original slack thread and get on the same page before moving forward. The important thing is ensuring that we're not working on the same core problem in two separate issues.

**Comment by strepanier03** [comment] 2022-11-22 04:18
Continued the discussion in the OG bug report [here](https://expensify.slack.com/archives/C049HHMV9SM/p1669090669017379?thread_ts=1668609896.587349&cid=C049HHMV9SM).

I have proposed we place this GH on hold until #11425 is resolved and we can test again.

**Comment by strepanier03** [comment] 2022-11-23 02:50
After discussion we have decided to close this until #11425 is resolved and we'll confirm this behavior is resolved.

**Closed by strepanier03** 2022-11-23 02:50 UTC
Labels: Daily, Bug
