### ISSUE TITLE
[$500] Expense - The gap between buttons in Concierge whisper is too wide

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#35168] opened 2024-01-25 17:10 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:**  1.4.31.1
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** @shawnborton
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1706185611151319

## Action Performed:
1. User A sends a payment to User B. Then User B @mentions user A in that same IOU thread.

## Expected Result:
 The space between the two buttons should only be 8-12px

## Actual Result:
The gap between buttons in Concierge whisper is too wide

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

![CleanShot 2024-01-25 at 07 23 56@2x](https://github.com/Expensify/App/assets/93399543/1adadb74-9da5-40bd-ba10-5f02230feea4)

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~010f9c7527fb2a6675</li>
        <li>Upwork Job ID: 1750566867979767808</li>
        <li>Last Price Increase: 2024-01-25</li>
    </ul>
</details>

**Comment by kbecciv** [comment] 2024-01-25 17:11
We think that this bug might be related to #vip-vsb
CC @quinthar

**Comment by bernhardoj** [comment] 2024-01-25 17:13
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
The gap between invite and do nothing button is too big.

### What is the root cause of that problem?
The gap is set to 16 here.
https://github.com/Expensify/App/blob/95631f67f1c24b5228abe83ee8f970c45925e3e5/src/components/ReportActionItem/ActionableItemButtons.tsx#L24

Instead of 8/12
### What changes do you think we should make in order to solve the problem?

Updat the gap to gap2 or gap3

**Comment by BhuvaneshPatil** [comment] 2024-01-25 17:13
## Proposal

### Please re-state the problem that we are trying to solve in this issue.

### What is the root cause of that problem?
We are using gap4 here, that's value is 16
```js
<View style={[styles.flexRow, styles.gap4]}> {props.items?.map((item) => ( <Button key={item.key} style={[styles.mt2]} onPress={item.onPress} text={translate(item.text)} small success={item.isPrimary} /> ))} </View>
```

### What changes do you think we should make in order to solve the problem?
use gap3 or gap2

### What alternative solutions did you explore? (Optional)

**Comment by shawnborton** [comment] 2024-01-25 17:14
I think we should do 8px as the solution, just to make that clear. cc @Expensify/design in case you disagree.

**Comment by shawnborton** [comment] 2024-01-25 17:15
Also, would we have any interest in doing this one internally? Paying out $500 just for a tiny change seems a bit extreme, no?

**Comment by shawnborton** [comment] 2024-01-25 17:18
That would be wonderful!

**Comment by situchan** [comment] 2024-01-29 15:03
Not overdue. @ishpaul777 please link this issue in your [PR](https://github.com/Expensify/App/pull/34560)

**Comment by zanyrenney** [comment] 2024-01-30 18:28
@ishpaul777 I think we can close this and manage the change in your PR right? I don't think we need to keep this separate as you'll tackle it in that PR.

**Closed by zanyrenney** 2024-01-30 18:28 UTC
Labels: External, Daily, Help Wanted, Bug
