### ISSUE TITLE
[HOLD for payment 2023-11-30] [$500] Workspace-WS Invite phone number shown with prefix+91, but on members list 0 is shown

### ISSUE THREAD

**Issue by izarutskaya** [Expensify/App#29852] opened 2023-10-18 11:14 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.3.86-1
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):** 
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** Applause-Internal Team
**Slack conversation:** @

## Action Performed:
1. Go to https://staging.new.expensify.com/
2. Tap profile
3. Tap Workspaces--Workspace
4. Tap members
5. Tap invite
6. Enter phone number 8765467895 and note search results show in bold +918765467895
7. Tap next
8. Tap invite

## Expected Result:
In workspace members page, the member added is shown in bold as 08765467895 but while invite it was shown with prefix +918765467895. In both place in same format in a consistent manner phone number should be displayed with same prefix.

## Actual Result:
In workspace members page, the member added is shown in bold as 08765467895 but while invite it was shown with prefix +918765467895.The behaviour is inconsistent.

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [x] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos
<details>
<summary>Android: Native</summary>

</details>

<details>
<summary>Android: mWeb Chrome</summary>

https://github.com/Expensify/App/assets/115492554/f2d04492-afe9-4257-a5f0-d73241dfb20a

</details>

<details>
<summary>iOS: Native</summary>

</details>

<details>
<summary>iOS: mWeb Safari</summary>

</details>

<details>
<summary>MacOS: Chrome / Safari</summary>

</details>

<details>
<summary>MacOS: Desktop</summary>

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~0169e8308b7b2db2a8</li>
        <li>Upwork Job ID: 1714600877296508928</li>
        <li>Last Price Increase: 2023-11-01</li>
<li>Automatic offers: </li>
<ul>
<li>Ollyws | Reviewer | 27547046</li>
<li>c3024 | Contributor | 27547049</li>
</ul></li>
    </ul>
</details>

**Comment by c3024** [comment] 2023-10-18 11:24
## Proposal
### Please re-state the problem that we are trying to solve in this issue.
Number in invite page shows country code like +91 instead of 0
### What is the root cause of that problem?
Here 
https://github.com/Expensify/App/blob/e8cb124e83c9ce588c1fb4402827880839ed88e9/src/libs/OptionsListUtils.js#L1457
we are not formatiing the phone number properly
### What changes do you think we should make in order to solve the problem?
We should change. this to 
```js
text: LocalePhoneNumber.formatPhoneNumber(lodashGet(member, 'text', '') || lodashGet(member, 'displayName', '')),
```
### What alternative solutions did you explore? (Optional)

**Comment by zukilover** [comment] 2023-10-18 12:08
## Proposal
### Please re-state the problem that we are trying to solve in this issue.
Phone number formats inconsistent between search result list and the member list.

### What is the root cause of that problem?
The search value is formatted so that it will use the `e164` format whenever possible, while the member lists use different approach where it eliminates the unnecessary country code when the region code is similar to the country code by IP:

Search list:
https://github.com/Expensify/App/blob/e8cb124e83c9ce588c1fb4402827880839ed88e9/src/libs/OptionsListUtils.js#L1019-L1020

Member list:
https://github.com/Expensify/App/blob/e8cb124e83c9ce588c1fb4402827880839ed88e9/src/libs/LocalePhoneNumber.ts#L34-L36

### What changes do you think we should make in order to solve the problem?
We need to decide which format is expected. If the search result should follow the rules for the member list, then I propose that we utilize the same `formatPhoneNumber` to format the search value, e.g.:

```javascript
    const searchValue = LocalePhoneNumber.formatPhoneNumber(searchInputValue.toLowerCase());
```

### What alternative solutions did you explore? (Optional)
N/A

**Comment by CortneyOfstad** [comment] 2023-10-18 20:21
I am heading OoO until Oct. 25, so reapplying the BZ label to have someone keep an eye on this while I am gone 👍

**Comment by c3024** [comment] 2023-10-20 14:03
It should add country code based on IP for a valid number even when entered without country code.


https://github.com/Expensify/App/assets/102477862/7424d9dc-1a55-4751-8782-8c7909ececb4

**Comment by CortneyOfstad** [comment] 2023-10-25 19:20
@MitchExpensify I am back from OoO, so I can take this back over — thanks for holding down the fort while I was out!

**Comment by CortneyOfstad** [comment] 2023-10-30 17:27
> I think we first need to determine wether we want to display both the number with/without the area code in the options list.
Right now it seems that in most places in the app we display phone numbers stripped of their area code where possible.

I agree @Ollyws so going to get engineering perspective on this 👍

**Comment by marcochavezf** [comment] 2023-10-30 18:57
Looking for more opinions in the open-source channel https://expensify.slack.com/archives/C01GTK53T8Q/p1698692198272549

**Comment by marcochavezf** [comment] 2023-11-01 13:23
I think the solution that Puneet proposed in the slack post is the best one:

```
I would think we should always show it in the same way which is:
- don’t show the country code for people in the same country as you 
- do show the country code for anyone else
```

**Comment by marcochavezf** [comment] 2023-11-06 20:09
Perfect, assigning @c3024 🚀

**Comment by CortneyOfstad** [comment] 2023-12-01 14:08
@Ollyws @c3024 — both have been paid in Upwork and no regression test is needed, so closing! Thanks all!

**Closed by CortneyOfstad** 2023-12-01 14:08 UTC
Labels: External, Engineering, Daily, Awaiting Payment, Bug
