### ISSUE TITLE
[Onyx re-key] Needs reproduction steps

### ISSUE THREAD

**Issue by Beamanator** [Expensify/App#20811] opened 2023-06-15 12:36 UTC
These are issues that were reported but either can't be reproduced or don't have good enough reproduction steps:
- [ ] https://expensify.slack.com/archives/C049HHMV9SM/p1686830123862429

Action Performed:
1. Go to any workspace(Profile->Workspace)
2. then go to Members
3. click on the "invite" button
4. Observe the list
Expected Result: There should not behave any duplicate emails on the list
Actual Result: There is same Email id is visible for 2 Times in the workspace invite list
Platforms: IOS
Version Number: v1.3.28-4
From: [@Nirav Kakadiya](https://expensify.slack.com/team/U052K733JTD)

**Comment by flaviadefaria** [comment] 2023-06-20 20:54
I'll handle this tomorrow.

**Comment by flaviadefaria** [comment] 2023-06-21 12:12
I'm not able to reproduce this. This [GH](https://github.com/Expensify/App/issues/21061) tests the same flow and also there this issue isn't reproducible. I posted in the Slack thread to see if the bug reported is still experiencing it.

**Comment by flaviadefaria** [comment] 2023-06-21 12:46
As discussed in Slack this is no longer being experienced so closing this GH.

**Closed by flaviadefaria** 2023-06-21 12:46 UTC
Labels: Daily, Bug
