### ISSUE TITLE
[HOLD for payment 2024-07-26] [$250]  Hold - Red dot remains when unhold expense

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#45064] opened 2024-07-09 12:05 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 9.0.5-3
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**If this was caught during regression testing, add the test name, ID and link from TestRail:** https://expensify.testrail.io/index.php?/tests/view/4700894&group_by=cases:section_id&group_id=309128&group_order=asc
**Email or phone of affected tester (no customers):** gocemate+workspaceapprover135@gmail.com
**Issue reported by:** Applause - Internal Team

## Action Performed:
Preconditions:
1. Login as the owner of the workspace
2. Create a workspace
3. Invite the approver and employee
4. Navigate to more features
5. Enable "workflows"
6. On the "Workflow" editor - enable "Add Approvals"
7. Set the Approver account as the Approver
Steps:
1. As Employee submit 2 expenses to Workspace chat
2. As Approver hold the first expense
3. As Approver go back to the expenses page ( there is red dot on the expense that is on Hold)
4. As Approver go back to transaction thread> Unhold the expense
4. As Approver go back to expenses page

## Expected Result:
There should be no red dot on the unheld expense

## Actual Result:
Red dot remains when approver unhold expense

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [x] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details> 

https://github.com/Expensify/App/assets/78819774/c8fa0886-2f65-4585-9459-2498c5609c95

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01785e48b0c37e8c52</li>
        <li>Upwork Job ID: 1810949376048189607</li>
        <li>Last Price Increase: 2024-07-10</li>
<li>Automatic offers: </li>
<ul>
<li>paultsimura | Reviewer | 103143168</li>
</ul></li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @dylanexpensify</details>

**Comment by bernhardoj** [comment] 2024-07-09 13:39
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
The hold status isn't removed immediately from the money request preview.

### What is the root cause of that problem?
The hold status comes from the `transaction.comment.hold` status or the transaction violations.
https://github.com/Expensify/App/blob/bb9b4864694e6a97ee00bd07e3d87e9d9d462e6b/src/components/ReportActionItem/MoneyRequestPreview/MoneyRequestPreviewContent.tsx#L111
https://github.com/Expensify/App/blob/bb9b4864694e6a97ee00bd07e3d87e9d9d462e6b/src/components/ReportActionItem/MoneyRequestPreview/MoneyRequestPreviewContent.tsx#L130

When we hold, the `transaction.comment.hold` is set, but the transaction violations are still empty. After we reopen the transaction thread, the transaction violations are returned from the BE. When we unhold the request, we only optimistically remove the `transaction.comment.hold`.
https://github.com/Expensify/App/blob/bb9b4864694e6a97ee00bd07e3d87e9d9d462e6b/src/libs/actions/IOU.ts#L7041-L7059

So, the transaction violations (that contain hold violations) still exist, thus the money request preview still shows the hold status. Reopening the transaction thread once again will clear it.

### What changes do you think we should make in order to solve the problem?

Optimistically removes the transaction violations of hold when unhold-ing a request. (and revert it when fails)
```
{
    onyxMethod: Onyx.METHOD.SET,
    key: `${ONYXKEYS.COLLECTION.TRANSACTION_VIOLATIONS}${transactionID}`,
    value: transactionViolations?.filter((violation) => violation.name !== 'hold') ?? [],
},
```
I also suggest to return the onyx update to clears the hold violation from the UnholdRequest API.

**Comment by dylanexpensify** [comment] 2024-07-10 08:09
moving!

**Comment by Beamanator** [comment] 2024-07-15 10:58
I'm OOO today, hopefully @cead22 can check the comments above - if not, I'll get back to this by wednesday / thursday

**Comment by cead22** [comment] 2024-07-16 16:42
> We should modify the BE to remove the `hold` violation on the `UnholdRequest` API endpoint (in addition to the App changes). Could you please check it?

I created an issue for us to update this

**Comment by bernhardoj** [comment] 2024-07-17 10:15
PR is ready

cc: @paultsimura

**Comment by Beamanator** [comment] 2024-07-17 14:23
Thanks @cead22 - I am happy to review the PR for this front end part, but also feel free to assign yourself if you want :pray

**Comment by dylanexpensify** [comment] 2024-07-22 12:38
Payment coming up!

**Comment by dylanexpensify** [comment] 2024-07-25 08:49
@OfstadC I'm heading OOO starting this afternoon, so reassigning for payment! TY!

**Comment by bernhardoj** [comment] 2024-07-26 07:24
Payment is due today. Requested in ND.

**Comment by OfstadC** [comment] 2024-07-26 15:18
### Payment Summary:
@paultsimura paid $250 via Upwork
@bernhardoj **due** $250 via NewDot

**Closed by OfstadC** 2024-07-26 15:18 UTC
Labels: External, Daily, Awaiting Payment, Bug

**Comment by JmillsExpensify** [comment] 2024-07-26 18:40
$250 approved for @bernhardoj
