### ISSUE TITLE
Expensify Card - There is an empty report in workspace chat after activating Expensify Card

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#52490] opened 2024-11-13 16:59 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 9.0.61-0
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**If this was caught on HybridApp, is this reproducible on New Expensify Standalone?:** N/A
**If this was caught during regression testing, add the test name, ID and link from TestRail:** 
**Email or phone of affected tester (no customers):** applausetester+w13@applause.expensifail.com
**Issue reported by:** Applause - Internal Team

## Action Performed:
Precondition:
- Workspace has enabled Expensify Card
- Admin has assigned a physical card to member
1. Go to staging.new.expensify.com
2. Go to Wallet
3. Click on the Expensify Card
4. Click Get physical card
5. Enter legal name, phone number and address
7. Click Next > Click Ship card
8. Click Activate card
9. Go to workspace chat

## Expected Result:
There will be no empty report after activating Expensify Card

## Actual Result:
There is an empty report in the workspace chat after activating Expensify Card

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Standalone
- [x] Android: HybridApp
- [x] Android: mWeb Chrome
- [ ] iOS: Standalone
- [x] iOS: HybridApp
- [x] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

<details>
  <summary>Add any screenshot/video evidence</summary>

  
</details> 

https://github.com/user-attachments/assets/ff7dd8d2-054a-4cfb-8d56-0b65e85a5009

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by trjExpensify** [comment] 2024-11-13 17:23
@mountiny @grgia @MariaHCD @koko57 @DylanDylann @allgandalf where do ya'll want this one? $0 transaction after card assignment.

**Comment by DylanDylann** [comment] 2024-11-13 17:24
I can help on this issue

**Comment by mountiny** [comment] 2024-11-14 00:45
Thats a new one, @DylanDylann @allgandalf since you showed interest, can you please try to debug to see where the report comes from? can you also see it on OldDot?

**Comment by DylanDylann** [comment] 2024-11-14 06:17
@mountiny This is a BE bug. After RequestPhysicalExpensifyCard API is successful, GetMissingOnyxMessages API returns an money report action


https://github.com/user-attachments/assets/9350ef6e-a4e1-4507-ae12-e1cb815226d8

**Comment by mountiny** [comment] 2024-11-18 12:19
no update yet

**Comment by nkuoch** [comment] 2024-11-19 11:41
```
nkuoch@db1.lax:~$ sudo readdb.sh -tsv "SELECT * FROM reportActions WHERE reportActionID=2892952241882612414"
created	reportID	accountID	action	message	reportActionID
2024-11-14 06:15:36.099	515981627738494	18601678	REPORTPREVIEW	{"isNewDot":false,"lastModified":"2024-11-14 06:15:36.099","linkedReportID":5988855688443757}	2892952241882612414

nkuoch@db1.lax:~$ sudo readdb.sh -tsv "SELECT * FROM reports WHERE reportID=515981627738494"
created	submitted	approved	reportID	accountID	managerID	reportName	state	total	currency	cachedData	status	details
2024-10-30 14:51:44			515981627738494	18601678		Chat Report	0	0	USD		0	{"type":"chat","policyID":"130EE0E6EC0BB3B4"}

nkuoch@db1.lax:~$ sudo readdb.sh -tsv "SELECT * FROM sharedReports WHERE reportID=515981627738494"

nkuoch@db1.lax:~$ sudo readdb.sh -tsv "SELECT * FROM reportNameValuePairs WHERE reportID=515981627738494"
reportID	name	value
515981627738494	chatType	policyExpenseChat
515981627738494	expensify_policyID	130EE0E6EC0BB3B4
515981627738494	lastReadTime_18601678	2024-11-14 06:15:38.239
515981627738494	type	chat

nkuoch@db1.lax:~$ sudo readdb.sh -tsv "SELECT * FROM reportActions WHERE reportID=515981627738494"
created	reportID	accountID	action	message	reportActionID
2024-10-30 14:51:44.573	515981627738494	18601678	CREATED	{"creatorAccountID":18601678,"isNewDot":true,"lastModified":"2024-10-30 14:51:44.573"}	4071460809009152185
2024-10-30 16:47:32.757	515981627738494	18601678	CARDISSUEDVIRTUAL	{"assigneeAccountID":18601678,"cardID":21415784,"isNewDot":true,"lastModified":"2024-10-30 16:47:32.757"}	8189453769835824148
2024-11-14 06:14:34.614	515981627738494	18601678	CARDMISSINGADDRESS	{"assigneeAccountID":18601678,"cardID":21506416,"isNewDot":true,"lastModified":"2024-11-14 06:14:34.614"}	6446334290183170777
2024-11-14 06:15:36.099	515981627738494	18601678	REPORTPREVIEW	{"isNewDot":false,"lastModified":"2024-11-14 06:15:36.099","linkedReportID":5988855688443757}	2892952241882612414
```

**Comment by nkuoch** [comment] 2024-11-19 18:09
Report preview got created in request_id:8e24de2e39450589-IAD when receiving Marqeta event:

`
{"transactions":[{"type":"authorization","state":"CLEARED","identifier":"6610698","token":"<REDACTED>","business_token":"18601682","acting_user_token":"18601682-18601678","card_token":"18601678-21415784-V","card_product_token":"0517d483-af92-4859-ab64-950ad905a3e9","network_metadata":{"product_id":"VISA_PURCHASING"},"is_recurring":false,"gpa":{"currency_code":"USD","ledger_balance":0,"available_balance":0,"credit_balance":0,"pending_credits":0,"balances":{"USD":{"currency_code":"USD","ledger_balance":0,"available_balance":0,"credit_balance":0,"pending_credits":0}}},"duration":60,"created_time":"2024-11-14T06:15:35Z","user_transaction_time":"2024-11-14T06:15:35Z","settlement_date":"2024-11-14T00:00:00Z","request_amount":0,"amount":0,"issuer_interchange_amount":0,"currency_code":"USD","approval_code":"193711","response":{"code":"1830","memo":"Card account verification success"},"network":"VISA","subnetwork":"VISANET","acquirer_fee_amount":0,"acquirer":{"institution_country":"840","institution_id_code":"401134","retrieval_reference_number":"431906787617","system_trace_audit_number":"787617"},"card":{"last_four":"9749","metadata":[]},"business":{"metadata":[]},"address_verification":{"request":{"street_address":"","postal_code":"12345"},"on_file":{"street_address":"Fauna Glen Drive","postal_code":"80927"},"response":{"code":"0303","memo":"Not validated"}},"card_security_code_verification":{"type":"CVV2","response":{"code":"0000","memo":"Card security code match"}},"fraud":{"network":{"transaction_risk_score":6,"account_risk_score":"00"}},"cardholder_authentication_data":{"electronic_commerce_indicator":"no_authentication","verification_result":"not_present"},"issuer_received_time":"2024-11-14T06:15:35.101Z","issuer_payment_node":"3b6f886809b578a85dc12501841961be","network_reference_id":"0002304319225341560","acquirer_reference_data":"401134","local_transaction_date":"2024-11-13T22:15:34Z","digital_wallet_token_transaction_service_provider_info":[],"card_acceptor":{"mid":"ZFDTOQPZON8YW7X","mcc":"5734","name":"EXPENSIFY, INC.","city":"+19713653939","state":"06","postal_code":"94108","country_code":"USA","payment_facilitator_id":"10069917","sub_merchant_id":"187AIJKMVuTn5q"},"pos":{"pan_entry_mode":"MANUAL","pin_entry_mode":"FALSE","terminal_id":"QRS6HG3O","terminal_attendance":"UNSPECIFIED","card_holder_presence":false,"card_presence":false,"pin_present":false,"card_data_input_capability":"NO_TERMINAL","partial_approval_capable":false,"purchase_amount_only":false,"is_recurring":false,"is_installment":false,"special_condition_indicator":"UNSPECIFIED","transaction_initiated_by":"CONSUMER","transaction_initiated_category":"UNSCHEDULED_PAYMENT"},"transaction_metadata":{"payment_channel":"ECOMMERCE"}}]}' marqetaSignature: '47efc44a5a3456ba7575614c11d4726e2364616a' marqetaTransactionIndex: '0' mergedTransactionID: '' mergeComment: '' modifiedMerchant: 'Expensify' modifiedMCC: '0' originalAmount: '0' originalCurrency: '' idempotent: '' logParam: 'dylandylan9112+20003@gmail.com' urlToNewDot: 'https://new.expensify.com/' shouldReadUsingThreads: '' shouldHandleOnyxUpdates: '1' isNewDotRequest: '' clientUpdateID: '0' maxNumberOfUpdates: '500' commitCount: '25604899884' requestID: '8e24de2e39450589-IAD' lastIP: '52.72.69.182' writeConsistency: 'ASYNC' priority: '500' timeout: '110000']'
`

**Comment by nkuoch** [comment] 2024-11-19 18:21
```
Expensify\Marqeta\MarqetaAPI - Final transaction ~~ 0: '[amount: '0' currency: 'USD' merchant: 'EXPENSIFY, INC.' mcc: '5734' created: '2024-11-14 06:15:35' card_token: '18601678-21415784-V' externalID: '14718b64-f9cc-4442-86b3-3fcb1a31c17c' reimbursable: 'false' user_transaction_time: '2024-11-14T06:15:35Z' nameValuePairs: '[liabilityType: 'corporate' forceReimbursable: '']' type: 'authorization' preceding_related_transaction_token: '' modifiedMerchant: 'Expensify']'

Bedrock\Client - Starting a request ~~ command: 'BuildWorkspaceExpenseReport' clusterName: 'auth' headers: '[authToken: '<REDACTED>' policyID: '130EE0E6EC0BB3B4' excludedExpenseReportIDs: '' alwaysCreateNewReport: '1' idempotent: '' logParam: 'dylandylan9112+20003@gmail.com' urlToNewDot: 'https://new.expensify.com/' shouldReadUsingThreads: '' shouldHandleOnyxUpdates: '1' isNewDotRequest: '' clientUpdateID: '0' maxNumberOfUpdates: '500' requestID: '8e24de2e39450589-IAD' lastIP: '52.72.69.182' writeConsistency: 'ASYNC' priority: '500' timeout: '110000']

Trying to create action (reportID 5988855688443757, requestingAccountID: 18601678, actionAccountID: 18601678, action: CREATED, reportActionID: 0)

CreateReport::process reportID 5988855688443757

Trying to create action (reportID 515981627738494, requestingAccountID: 18601678, actionAccountID: 18601678, action: REPORTPREVIEW, reportActionID: 0)

Setting report state, status, managerID as Instantly Submitted

Creating a new Expense report for 18601678 and shared with the admins of policy 130EE0E6EC0BB3B4

```

**Comment by nkuoch** [comment] 2024-11-19 18:25
So, I think that when activating Expensify Card:

- Marqeta sends use a $0 authorization.
- We create an expense report for it
- We create the report preview action on the workspace chat
- We end up hiding the transaction

**Comment by nkuoch** [comment] 2024-11-19 19:41
Maybe we can do https://github.com/Expensify/Web-Expensify/pull/44498 but I need to double check

**Comment by mountiny** [comment] 2024-11-22 11:11
PR deployed

**Comment by mountiny** [comment] 2024-11-25 11:50
PR only merged, I lied

**Comment by mountiny** [comment] 2024-11-28 15:07
Asked QA to retest https://expensify.slack.com/archives/C9YU7BX5M/p1732806271904629

**Comment by kavimuru** [comment] 2024-11-28 16:03
not reproducible.

https://github.com/user-attachments/assets/c8d3fd44-ad23-40f3-8e7b-ca0d251118d1

**Closed** 2024-11-28 16:09 UTC
Labels: Reviewing, Daily, Internal, Bug, retest-weekly
