### ISSUE TITLE
 Threads - Context menu shows 'Unsubscribe from thread' after leaving the thread

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#30587] opened 2023-10-30 15:07 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.3.93-0
**Reproducible in staging?:**Y
**Reproducible in production?:**N
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** Applause - Internal Team
**Slack conversation:**

**Issue found when executing PR** https://github.com/Expensify/App/pull/27994
## Action Performed:
1. Go to staging.new.expensify.com
2. Send a message in any chat
3. Send a reply to the message
4. Click on the three-dot menu > Leave thread
5. In the main 1:1 DM, right click on the parent message
Note that it shows 'Unsubscribe from thread' instead of 'Subscribe to thread'

## Expected Result:
The context menu shows 'Subscribe to thread', since user has left the thread

## Actual Result:
The context menu still shows 'Unsubscribe from thread'

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [x] Android: mWeb Chrome
- [x] iOS: Native
- [x] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos
<details>
<summary>Android: Native</summary>

</details>

<details>
<summary>Android: mWeb Chrome</summary>

</details>

<details>
<summary>iOS: Native</summary>

</details>

<details>
<summary>iOS: mWeb Safari</summary>

</details>

<details>
<summary>MacOS: Chrome / Safari</summary>

 

https://github.com/Expensify/App/assets/78819774/4c8e75b1-2b3a-44a5-aaf4-bf5d346b9ce8

</details>

<details>
<summary>MacOS: Desktop</summary>

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by sakluger** [comment] 2023-10-30 16:44
Thanks @ishpaul777, this is a duplicate of that one.

**Closed by sakluger** 2023-10-30 16:44 UTC
Labels: DeployBlockerCash, Engineering, Hourly, Bug
