### ISSUE TITLE
[HOLD for payment 2024-07-17][$250] Expense - App crashes when opening an expense report after submitting another expense

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#44960] opened 2024-07-08 13:31 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 9.0.5-2
**Reproducible in staging?:** Y
**Reproducible in production?:** N
**If this was caught during regression testing, add the test name, ID and link from TestRail:** N/A
**Issue reported by:** Applause - Internal Team

## Action Performed:
1. Sign in to an account
2. Go to FAB > submit expense > Manual expense
3. Enter an amount
4. Select a user you have never submitted an expense to
5. Submit the expense
5. Navigate to the chat with the user you just submitted the expense to
6. Click on the "+" icon
7. Click on submit expense > Manual expense > Enter amount >Next > Submit
8. Go to the combined expense report and open the first expense you submitted

## Expected Result:
The expense report opens and the app does not crash

## Actual Result:
App crashes after opening the report

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details> 

https://github.com/Expensify/App/assets/78819774/12d0733e-a607-4484-acd2-91bb79466b00

[logs (2).txt](https://github.com/user-attachments/files/16129077/logs.2.txt)

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01ab200eebc7b06724</li>
        <li>Upwork Job ID: 1810395750787214444</li>
        <li>Last Price Increase: 2024-07-08</li>
<li>Automatic offers: </li>
<ul>
<li>brunovjk | Reviewer | 103047644</li>
<li>nkdengineer | Contributor | 103047648</li>
</ul></li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @allroundexperts</details>

**Comment by lanitochka17** [comment] 2024-07-08 13:31
@rlinoz  FYI I haven't added the External label as I wasn't 100% sure about this issue. Please take a look and add the label if you agree it's a bug and can be handled by external contributors

**Comment by Julesssss** [comment] 2024-07-08 13:47
Crash seems to be related to Policy key changing? Are we temporarily setting it to __FAKE__

<img width="246" alt="Screenshot 2024-07-08 at 14 46 08" src="https://github.com/Expensify/App/assets/10736861/6924de50-1ec3-4995-aa78-0238567ed7b1">

**Comment by rlinoz** [comment] 2024-07-08 14:00
Taking a look at this, weird one

**Comment by rlinoz** [comment] 2024-07-08 14:45
It looks like we are creating the first money request in a different policyID other than `_FAKE_`, and when we open that report again we set it back to fake, which then crashes. Looking like a backend bug.

**Comment by rlinoz** [comment] 2024-07-08 15:29
not happening in prod though, and apparently we didn't deploy anything related to staging in Web-E

**Comment by Julesssss** [comment] 2024-07-08 15:40
Hmm, nice. At least it points back to app. 

I wonder if any of the PRs seem associated with policies. Does [this issue](https://github.com/Expensify/App/issues/44960) seem related?

**Comment by Julesssss** [comment] 2024-07-08 15:41
Oops lol, ignore that

**Comment by rlinoz** [comment] 2024-07-08 15:44
Yeah, tested with the production Web-E branch and still happens in dev, so I am gonna go ahead and remove the DeployBlocker for Web-E, will continue looking after lunch.

**Comment by rlinoz** [comment] 2024-07-08 19:30
I am having a hard time finding what started causing the issue, so let's ask for some external help.

Also, I think we probably shouldn't be sending the report with a policyID other than _FAKE_, so that is weird, but it is also happening in prod.

**Comment by rlinoz** [comment] 2024-07-08 22:04
Asked for help here: https://expensify.slack.com/archives/C01GTK53T8Q/p1720476223648779

**Comment by nkdengineer** [comment] 2024-07-09 08:42
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
App crashes after opening the report

### What is the root cause of that problem?
When we submit an expense, we create an optimistic transaction thread here

https://github.com/Expensify/App/blob/dd96852320612fd5188c95e659fce3814150af82/src/libs/ReportUtils.ts#L5213

When we submit an expense in a new DM, we create an optimistic iou report with `policyID` as `undefined` here
https://github.com/Expensify/App/blob/dd96852320612fd5188c95e659fce3814150af82/src/libs/ReportUtils.ts#L3868

And then the optimistic transaction thread report has `policyID` as `_FAKE_` by default here
https://github.com/Expensify/App/blob/dd96852320612fd5188c95e659fce3814150af82/src/libs/ReportUtils.ts#L5146

https://github.com/Expensify/App/blob/dd96852320612fd5188c95e659fce3814150af82/src/libs/ReportUtils.ts#L4579

After BE returns data, the `policyID` is changed to personal `policyID` so the app crashes
### What changes do you think we should make in order to solve the problem?
We can change the default `policyID` here to `-1` or `undefined` and update other places that use this function to pass `policyID` as `undefined` if we're passing it as `_FAKE_`

https://github.com/Expensify/App/blob/dd96852320612fd5188c95e659fce3814150af82/src/libs/ReportUtils.ts#L4579

### What alternative solutions did you explore? (Optional)

**Comment by nkdengineer** [comment] 2024-07-09 14:54
@rlinoz @brunovjk The PR is [here](https://github.com/Expensify/App/pull/45084).

**Comment by rlinoz** [comment] 2024-07-09 16:59
CP fixed the issue

**Comment by rlinoz** [comment] 2024-07-12 12:19
I think the automation failed, but this is in prod already.

@isabelastisser

**Comment by isabelastisser** [comment] 2024-07-12 17:42
@rlinoz, to clarify, when is the payment due?

**Comment by rlinoz** [comment] 2024-07-12 18:17
It got to prod 2 days ago, so the 17, updated the title.

**Comment by isabelastisser** [comment] 2024-07-12 19:39
thanks!

**Comment by isabelastisser** [comment] 2024-07-18 19:56
The payments were processed in Upwork. All set!

**Comment by brunovjk** [comment] 2024-07-18 21:51
I got paid but @allroundexperts reviewed the PR

cc: @rlinoz, @isabelastisser

**Comment by brunovjk** [comment] 2024-07-18 21:54
I got paid but @allroundexperts reviewed the PR

@rlinoz, @isabelastisser

**Comment by brunovjk** [comment] 2024-07-19 01:27
@allroundexperts reviewed the PR

@isabelastisser @rlinoz

**Comment by mallenexpensify** [comment] 2024-07-19 22:08
Thanks @brunovjk , I just requested a refund, please confirm via a comment here when you've done so.

**Comment by brunovjk** [comment] 2024-07-19 22:31
Great @mallenexpensify, I went to make the refund, but the 10% Upwork fee has already been debited, I can refund $225 (Bounty - Upwork fee), okay?
Next week I have other contracts to receive, maybe we'll leave this one alone, and next week we'll cash it. I have no preference, whatever is best for the project.

**Note**: While we're here, would you know if I can get paid through Expensify instead of Upwork? I don't live in USA. Thank you.

**Comment by mallenexpensify** [comment] 2024-07-20 00:30
Thx @brunovjk , that's weird that the fee isn't removed too, hmmm... 
How has the 10% fee been debited if it takes them 5 days to pay?  Do you have any screenshots you can share. 

Currently, all contributors need to be paid via Upwork for 18 months from their first hire, unfortunately you have a while. 2025-08-09	Bruno Rocha

**Comment by brunovjk** [comment] 2024-07-20 00:50
> Thx @brunovjk , that's weird that the fee isn't removed too, hmmm... How has the 10% fee been debited if it takes them 5 days to pay? Do you have any screenshots you can share.

![image](https://github.com/user-attachments/assets/ac19df6d-0a47-403d-b69d-3cffc5aaa406)

It shows that the fee was removed, I tried refund anyway, can you confirm if everything went well?

> Currently, all contributors need to be paid via Upwork for 18 months from their first hire, unfortunately you have a while. 2025-08-09 Bruno Rocha



Thank you very much for the information!!!! I'll leave a note here, it goes quickly :D

**Comment by mallenexpensify** [comment] 2024-07-22 20:59
Yup, confirming we got the refund.  Thanks @brunovjk , I know it's a bit of a pain.  Luckily it happens pretty rarely.  

Contributor: @nkdengineer paid $250 via Upwork
Contributor+: @allroundexperts owed $250 via NewDot. 

@isabelastisser when you pay contributors can you provide more detail in the description so that we know who's getting paid where, and how much?  Thx.  

@allroundexperts plz complete the BZ checklist below, seems like we'd want a regression test for this, right? 

**BugZero Checklist:** The PR fixing this issue has been merged! The following checklist ([instructions](https://stackoverflow.com/c/expensify/questions/14574)) will need to be completed before the issue can be closed:

- [ ] [@] The PR that introduced the bug has been identified. Link to the PR:
- [ ] [@] The offending PR has been commented on, pointing out the bug it caused and why, so the author and reviewers can learn from the mistake. Link to comment:
- [ ] [@] A discussion in #expensify-bugs has been started about whether any other steps should be taken (e.g. updating the PR review checklist) in order to catch this type of bug sooner. Link to discussion:
- [ ] [@] Determine if we should create a regression test for this bug.
- [ ] [@] If we decide to create a regression test for the bug, please propose the [regression test](https://github.com/Expensify/App/blob/main/contributingGuides/REGRESSION_TEST_BEST_PRACTICES.md) steps to ensure the same bug will not reach production again.
- [ ] [@BZ] Link the GH issue for creating/updating the regression test once above steps have been agreed upon:
- [ ]

**Comment by rlinoz** [comment] 2024-07-24 12:49
friendly bump @allroundexperts

**Comment by allroundexperts** [comment] 2024-07-29 09:01
## Checklist
1. I was not able to pinpoint the exact PR which caused this issue.
2. N/A
3. N/A
4. A regression test would be useful here.

### Regression test
1. Sign in to an account and go to FAB > submit expense > Manual expense
2. Enter an amount and select a user you have never submitted an expense to
3. Submit the expense
4. Navigate to the chat with the user you just submitted the expense to
5. Click on the "+" icon
6. Click on submit expense > Manual expense > Enter amount >Next > Submit
7. Go to the combined expense report and open the first expense you submitted

Verify that the expense report opens and the app does not crash

Do we 👍 or 👎 ?

**Comment by isabelastisser** [comment] 2024-07-29 17:06
Sounds good, thanks @rlinoz!

This is all set, closing!

**Closed by isabelastisser** 2024-07-29 17:06 UTC
Labels: External, Engineering, Daily, Awaiting Payment, Bug

**Comment by JmillsExpensify** [comment] 2024-08-21 11:09
$250 approved for @allroundexperts
