### ISSUE TITLE
[$250] Attachment shows misaligned in the chat thread

### ISSUE THREAD

**Issue by m-natarajan** [Expensify/App#41982] opened 2024-05-10 13:36 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.72.0
**Reproducible in staging?:** y 
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** @zanyrenney 
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1715338513772949

## Action Performed:
1. Open app and go to any report
2.  Go to thread of any message
3.  Send an a csv attachment

## Expected Result:
Attachment should be aligned in the chat thread
## Actual Result:
Attachment on Expensify Chat shows misaligned in the chat thread

## Workaround:
unknown
## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence
Expected design
![2024-05-10_11-55-36](https://github.com/Expensify/App/assets/38435837/32ae3538-1356-4470-b0f1-e52cab2eee42)
Actual 
![2024-05-10_11-54-01](https://github.com/Expensify/App/assets/38435837/f02c627c-119a-4371-9d44-2adf165b5718)

![Snip - (47) New Expensify - Google Chrome (2)](https://github.com/Expensify/App/assets/38435837/560da01c-cc20-4513-8efa-e7d65415558b)

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~012d8357ee1785e0c9</li>
        <li>Upwork Job ID: 1790068118206586880</li>
        <li>Last Price Increase: 2024-05-20</li>
<li>Automatic offers: </li>
<ul>
<li>Krishna2323 | Contributor | 0</li>
</ul></li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @parasharrajat</details>

**Comment by kaushiktd** [comment] 2024-05-14 03:21
Hey @Krishna2323, were you able to replicate this issue? I've attempted to follow the steps provided, but I'm unable to reproduce it on the staging environment. @m-natarajan
![image](https://github.com/Expensify/App/assets/43398804/e7652c9d-c195-4226-86b7-17ca3e236aea)

**Comment by isabelastisser** [comment] 2024-05-23 18:58
@Krishna2323, any updates?

**Comment by isabelastisser** [comment] 2024-05-24 16:22
Thanks for the update, @Krishna2323 

@parasharrajat, closing this issue.

**Closed by isabelastisser** 2024-05-24 16:22 UTC
Labels: External, Daily, Bug
