### ISSUE TITLE
[$250] [HOLD for payment 2024-09-23] Bank account - Bank account modal prompts user to verify account after being done validating

### ISSUE THREAD

**Issue by IuliiaHerets** [Expensify/App#49215] opened 2024-09-14 19:39 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 9.0.35-0
**Reproducible in staging?:** Y
**Reproducible in production?:** N
**Email or phone of affected tester (no customers):** nathanmulugetatesting+1484@gmail.com
**Issue reported by:** Applause Internal Team

## Action Performed:
1. Navigate to staging.new.expensify.com and sign up with a new unvalidated Gmail account
2. Create a workspace
3. Enable workflows
4. Click on connect to bank account
5. Update currency to usd if already not
6. Click on "Verify your account here" link and validate your account

## Expected Result:
After validating account bank account setup continues

## Actual Result:
After validating account bank account setup continues

## Workaround:
Unknown

## Platforms:

- [x] Android: Native
- [x] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

https://github.com/user-attachments/assets/2d15efbe-babb-4e66-adcd-88730c0a23bc

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Issue Owner</summary>Current Issue Owner: @</details>
<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~021839023851099596990</li>
        <li>Upwork Job ID: 1839023851099596990</li>
        <li>Last Price Increase: 2024-09-25</li>
    </ul>
</details>

**Comment by CyberAndrii** [comment] 2024-09-14 20:21
Damn, I accidentally reverted that line while I was reverting [other changes](https://github.com/Expensify/App/compare/68872443d1e778b31d5cf7e641bd465913be1728..acd46d08ba68a72c431f6249ca2aaebaf8903d69#diff-5dd63139f1b1773b20e18b067e9df0da8ede95dd9e2dc64f5f6eb953dc4deb59R624) :facepalm:

**Comment by s77rt** [comment] 2024-09-14 22:20
@CyberAndrii This happens only optimistically right? IOW if we refresh the page the error would disappear? If so, I agree with the suggested solution, please raise a PR asap

**Comment by CyberAndrii** [comment] 2024-09-14 23:35
[PR](https://github.com/Expensify/App/pull/49221) is ready. @s77rt yes, after reloading the error disappears (but only with the changes from the PR)

**Comment by s77rt** [comment] 2024-09-14 23:55
@CyberAndrii If you logout and login, do you still see the error?

This bug could be related to the BE if that flow is still using `user.validated` internally. If that's the case we should revert the PR (to unblock the deploy), make the necessary changed in BE and then re-submit the PR (basically same as [the plan](https://github.com/Expensify/App/issues/48699#issuecomment-2344028513))

**Comment by CyberAndrii** [comment] 2024-09-15 00:01
No error, BE sets the value correctly

![image](https://github.com/user-attachments/assets/8b4266cc-3944-49b4-beaa-6926842f30dd)

**Comment by s77rt** [comment] 2024-09-15 00:11
Unfortunately I'm unable to reproduce the bug ([asked in Slack](https://expensify.slack.com/archives/C01GTK53T8Q/p1726358698700859)). @ishpaul777 If you can reproduce both the initial bug and this new bug, do you want to take that issue over and review/test the [follow up PR](https://github.com/Expensify/App/pull/49221)?

**Comment by grgia** [comment] 2024-09-16 11:24
We discussed and decided to move forward with the fix proposed in https://github.com/Expensify/App/pull/49221

**Comment by garrettmknight** [comment] 2024-09-23 16:30
**Payment Summary:**
- Reviewer: @ishpaul777 $250

**Comment by garrettmknight** [comment] 2024-09-25 19:28
@ishpaul777 offer out to you

**Comment by garrettmknight** [comment] 2024-09-25 20:19
Paid, closing!

**Closed by garrettmknight** 2024-09-25 20:19 UTC
Labels: Engineering, Daily, Awaiting Payment, Bug
