### ISSUE TITLE
[$1000] Routing Number shows an error before typing anything

### ISSUE THREAD

**Issue by kavimuru** [Expensify/App#24044] opened 2023-08-02 09:57 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1- Click on your avatar
2- click on Worspaces option
3- select any workspace
4- Click on bank account option
5- click on Connect manually
6- Close the keyboard without typing anything

## Expected Result: 
Routing Number shouldn't show any error before typing ( Account Number works perfectly)
## Actual Result: 
Routing Number shows an error before typing anything

## Workaround:
Can the user still use Expensify without this being fixed? Have you informed them of the workaround?

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android / native
- [x] Android / Chrome
- [x] iOS / native
- [x] iOS / Safari
- [x] MacOS / Chrome / Safari
- [x] MacOS / Desktop

**Version Number:** 1.3.49-0
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/43996225/d1f8146e-9756-4d69-97ec-2f9b3c82eb71

https://github.com/Expensify/App/assets/43996225/882d2785-ee20-46bd-9608-e96264e27b4e

**Expensify/Expensify Issue URL:**
**Issue reported by:** @mejed-alkoutaini
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1690724240140599

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01c0ac78d2c9b90a4f</li>
        <li>Upwork Job ID: 1686753426700144640</li>
        <li>Last Price Increase: 2023-08-02</li>
    </ul>
</details>

**Comment by hanzalahsamana** [comment] 2023-08-02 15:09
Proposal,

I am submitting my proposal to resolve the "Routing Number" error display issue in the FormAlertWrapper component. The current problem displays an error message prematurely, even before any user input. To address this, I will make the following changes:

Conditional Error Rendering: I will update the FormAlertWrapper to show error messages only when there are validation issues or when users attempt to submit incomplete forms.

Enhanced Offline Handling: The component will handle offline scenarios gracefully, displaying appropriate messages to inform users about their connection status.

Accessibility & Localization: I will ensure that the error messages are accessible and support multi-language localization.

My goal is to deliver a polished solution that improves the user experience by providing accurate error feedback and seamless form interactions.

I am excited to collaborate on this project and welcome any specific preferences or additional requirements you may have.

Thank you for considering my proposal. I am eager to contribute to your project's success.

Best regards,
Hanzalah Imran

**Comment by hanzalahsamana** [comment] 2023-08-02 15:10
Expensify account email: hanzalahsamana789@gmail.com
Upwork Profile Link: https://www.upwork.com/freelancers/~019b0a755f7bda1754

**Comment by ares-dev05** [comment] 2023-08-02 16:48
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
The issue is that the Routing Number field in the form shows a validation error prematurely when the keyboard is closed without entering any input.
### What is the root cause of that problem?
When the keyboard is closed without entering any input, the Routing Number field is automatically filled with an empty string. Subsequently, when you select another field or lose focus on the Routing Number field, the validation process is triggered. However, since the Routing Number is empty, it is currently displaying an error.
### What changes do you think we should make in order to solve the problem?
If the Routing Number field is an empty string, we need to display an error message stating "Please input the Routing Number field." If you prefer not to show this error message, we can prevent the error from being displayed when the Routing Number field is empty. However, this approach may introduce potential new issues, so it is recommended to display the error message as "Please input the Routing Number field."

In BankAccountManualStep.js, you can find `validate` function and then we can update the error message.
```
const validate = useCallback(
    (values) => {
        const errorFields = {};
        const routingNumber = values.routingNumber && values.routingNumber.trim();

        if (
            !values.accountNumber ||
            (!CONST.BANK_ACCOUNT.REGEX.US_ACCOUNT_NUMBER.test(values.accountNumber.trim()) && !CONST.BANK_ACCOUNT.REGEX.MASKED_US_ACCOUNT_NUMBER.test(values.accountNumber.trim()))
        ) {
            errorFields.accountNumber = 'bankAccount.error.accountNumber';
        } else if (values.accountNumber === routingNumber) {
            errorFields.accountNumber = translate('bankAccount.error.routingAndAccountNumberCannotBeSame');
        }
        if (!routingNumber) {
            errorFields.routingNumber = 'bankAccount.error.routingNumberEmpty';
        }
        if (!CONST.BANK_ACCOUNT.REGEX.SWIFT_BIC.test(routingNumber) || !ValidationUtils.isValidRoutingNumber(routingNumber)) {
            errorFields.routingNumber = 'bankAccount.error.routingNumber';
        }
        if (!values.acceptTerms) {
            errorFields.acceptTerms = 'common.error.acceptTerms';
        }

        return errorFields;
    },
    [translate],
);
```
And in en.js, add the error message.
![image](https://github.com/Expensify/App/assets/83194791/f4189f57-3488-4631-8bbe-d5dc5a0e7dca)


### What alternative solutions did you explore? (Optional)
We can ignore the empty string error in the validate function.
![image](https://github.com/Expensify/App/assets/83194791/a2ee0aee-1eae-473f-95e4-d5f15fef4d1e)
const validate = useCallback(
    (values) => {
        const errorFields = {};
        const routingNumber = values.routingNumber && values.routingNumber.trim();

        if (
            !values.accountNumber ||
            (!CONST.BANK_ACCOUNT.REGEX.US_ACCOUNT_NUMBER.test(values.accountNumber.trim()) && !CONST.BANK_ACCOUNT.REGEX.MASKED_US_ACCOUNT_NUMBER.test(values.accountNumber.trim()))
        ) {
            errorFields.accountNumber = 'bankAccount.error.accountNumber';
        } else if (values.accountNumber === routingNumber) {
            errorFields.accountNumber = translate('bankAccount.error.routingAndAccountNumberCannotBeSame');
        }
        if (routingNumber && (!CONST.BANK_ACCOUNT.REGEX.SWIFT_BIC.test(routingNumber) || !ValidationUtils.isValidRoutingNumber(routingNumber))) {
            errorFields.routingNumber = 'bankAccount.error.routingNumber';
        }
        if (!values.acceptTerms) {
            errorFields.acceptTerms = 'common.error.acceptTerms';
        }

        return errorFields;
    },
    [translate],
);

**Comment by mudassar69** [comment] 2023-08-03 10:51
# Proposal About Bank Account Manual Step - Form Validation Enhancement

## Problem Statement:
In the Bank Account Manual Step component, there is an issue with form validation where error messages persist even after the user closes the input field without entering any data. This creates a confusing user experience as the errors should disappear when the user starts typing.

## Root Cause:
The issue arises from how the error state is managed in the component. The current implementation does not handle the scenario when the user closes the input field without entering any data, resulting in the error message remaining visible.

## Proposed Solution:
Please check my fixed solution in the below video now no errors are shown initially only errors are shown on continue button pressed:

[Fixed Video Demo](https://firebasestorage.googleapis.com/v0/b/takepicwasabiupload.appspot.com/o/Expensify%20Bug%20Solution.mp4)

<html><iframe width="320" height="240" src="https://firebasestorage.googleapis.com/v0/b/takepicwasabiupload.appspot.com/o/Expensify%20Bug%20Solution.mp4" frameborder="0" allowfullscreen></iframe></html>

To fix the form validation issue and ensure a smooth user experience, the following changes are recommended:
- **Introduce isFormSubmitted State**: Add a new state property isFormSubmitted to track whether the form has been submitted.

- **Modiied the validate Method**: I have adjusted the validate method to set errors for the input fields only when the form is submitted (isFormSubmitted is true). If the form has not been submitted, the method will return an empty error object, ensuring that errors disappear when the user closes the input field without entering any data.

- **Modified  the submit Method**: In the submit method, I have set the isFormSubmitted state to true when the form is submitted. This will enable the validation to occur based on the user's interaction with the form.

- **Removed onFocus and onBlur**: I have temporarily remove the onFocus and onBlur event handlers from the input fields. These event handlers were causing issues and will be re-evaluated for a better solution in the future.

## Updated Code:

Relative Path of file: `src/pages/ReimbursementAccount/BankAccountManualStep.js`
```js
import React from 'react';
import {Image} from 'react-native';
import lodashGet from 'lodash/get';
import HeaderWithBackButton from '../../components/HeaderWithBackButton';
import CONST from '../../CONST';
import * as BankAccounts from '../../libs/actions/BankAccounts';
import Text from '../../components/Text';
import TextInput from '../../components/TextInput';
import styles from '../../styles/styles';
import CheckboxWithLabel from '../../components/CheckboxWithLabel';
import TextLink from '../../components/TextLink';
import withLocalize from '../../components/withLocalize';
import * as ValidationUtils from '../../libs/ValidationUtils';
import ONYXKEYS from '../../ONYXKEYS';
import exampleCheckImage from './exampleCheckImage';
import Form from '../../components/Form';
import shouldDelayFocus from '../../libs/shouldDelayFocus';
import ScreenWrapper from '../../components/ScreenWrapper';
import StepPropTypes from './StepPropTypes';

const propTypes = {
    ...StepPropTypes,
};

class BankAccountManualStep extends React.Component {
    constructor(props) {
        super(props);
        this.state = {
            errors: {},
            isFormSubmitted: false, // New state property to track form submission
        };
        this.submit = this.submit.bind(this);
        this.validate = this.validate.bind(this);
        this.handleInputChange = this.handleInputChange.bind(this);
    }

    handleInputChange(inputID, value) {
        // Clear the error for the specific input when the user starts typing
        this.setState((prevState) => ({
            errors: {
                ...prevState.errors,
                [inputID]: undefined,
            },
        }));
    }

    validate(values) {
        // Only set the errors if the form is submitted
        if (this.state.isFormSubmitted) {
            const errorFields = {};
            const routingNumber = values.routingNumber && values.routingNumber.trim();

            if (
                !values.accountNumber ||
                (!CONST.BANK_ACCOUNT.REGEX.US_ACCOUNT_NUMBER.test(values.accountNumber.trim()) && !CONST.BANK_ACCOUNT.REGEX.MASKED_US_ACCOUNT_NUMBER.test(values.accountNumber.trim()))
            ) {
                errorFields.accountNumber = this.props.translate('bankAccount.error.accountNumber');
            } else if (values.accountNumber === routingNumber) {
                errorFields.accountNumber = this.props.translate('bankAccount.error.routingAndAccountNumberCannotBeSame');
            }
            if (!routingNumber || !CONST.BANK_ACCOUNT.REGEX.SWIFT_BIC.test(routingNumber) || !ValidationUtils.isValidRoutingNumber(routingNumber)) {
                errorFields.routingNumber = this.props.translate('bankAccount.error.routingNumber');
            }
            if (!values.acceptTerms) {
                errorFields.acceptTerms = this.props.translate('common.error.acceptTerms');
            }

            this.setState({errors: errorFields});
            return errorFields;
        }
        return {};
    }

    submit(values) {
        // Set isFormSubmitted to true when the form is submitted
        this.setState({isFormSubmitted: true});

        // If values of routing number and account number are empty give error
        if (!values.routingNumber || !values.accountNumber) {
            // alert('Please enter routing number and account number');
            const errorFields = {};
            const routingNumber = values.routingNumber && values.routingNumber.trim();

            if (
                !values.accountNumber ||
                (!CONST.BANK_ACCOUNT.REGEX.US_ACCOUNT_NUMBER.test(values.accountNumber.trim()) && !CONST.BANK_ACCOUNT.REGEX.MASKED_US_ACCOUNT_NUMBER.test(values.accountNumber.trim()))
            ) {
                errorFields.accountNumber = 'bankAccount.error.accountNumber';
            } else if (values.accountNumber === routingNumber) {
                errorFields.accountNumber = this.props.translate('bankAccount.error.routingAndAccountNumberCannotBeSame');
            }
            if (!routingNumber || !CONST.BANK_ACCOUNT.REGEX.SWIFT_BIC.test(routingNumber) || !ValidationUtils.isValidRoutingNumber(routingNumber)) {
                errorFields.routingNumber = 'bankAccount.error.routingNumber';
            }
            if (!values.acceptTerms) {
                errorFields.acceptTerms = 'common.error.acceptTerms';
            }

            this.setState({errors: errorFields});
            return errorFields;
        } else {
            BankAccounts.connectBankAccountManually(
                lodashGet(this.props.reimbursementAccount, 'achData.bankAccountID') || 0,
                values.accountNumber,
                values.routingNumber,
                lodashGet(this.props, ['reimbursementAccountDraft', 'plaidMask']),
            );
        }
    }

    render() {
        const shouldDisableInputs = Boolean(lodashGet(this.props.reimbursementAccount, 'achData.bankAccountID'));

        return (
            <ScreenWrapper includeSafeAreaPaddingBottom={false}>
                <HeaderWithBackButton
                    title={this.props.translate('workspace.common.connectBankAccount')}
                    stepCounter={{step: 1, total: 5}}
                    shouldShowGetAssistanceButton
                    guidesCallTaskID={CONST.GUIDES_CALL_TASK_IDS.WORKSPACE_BANK_ACCOUNT}
                    onBackButtonPress={this.props.onBackButtonPress}
                />
                <Form
                    formID={ONYXKEYS.FORMS.REIMBURSEMENT_ACCOUNT_FORM}
                    onSubmit={this.submit}
                    validate={this.validate}
                    // Remove onFocus/onBlur when we have a better solution for
                    submitButtonText={this.props.translate('common.continue')}
                    style={[styles.mh5, styles.flexGrow1]}
                >
                    <Text style={[styles.mb5]}>{this.props.translate('bankAccount.checkHelpLine')}</Text>
                    <Image
                        resizeMode="contain"
                        style={[styles.exampleCheckImage, styles.mb5]}
                        source={exampleCheckImage(this.props.preferredLocale)}
                    />
                    <TextInput
                        autoFocus
                        shouldDelayFocus={shouldDelayFocus}
                        inputID="routingNumber"
                        label={this.props.translate('bankAccount.routingNumber')}
                        defaultValue={this.props.getDefaultStateForField('routingNumber', '')}
                        keyboardType={CONST.KEYBOARD_TYPE.NUMBER_PAD}
                        disabled={shouldDisableInputs}
                        shouldSaveDraft
                        shouldUseDefaultValue={shouldDisableInputs}
                        error={this.state.errors.routingNumber} // Pass the error message to the TextInput component
                        onChangeText={(value) => this.handleInputChange('routingNumber', value)}
                    />
                    <TextInput
                        inputID="accountNumber"
                        containerStyles={[styles.mt4]}
                        label={this.props.translate('bankAccount.accountNumber')}
                        defaultValue={this.props.getDefaultStateForField('accountNumber', '')}
                        keyboardType={CONST.KEYBOARD_TYPE.NUMBER_PAD}
                        disabled={shouldDisableInputs}
                        shouldSaveDraft
                        shouldUseDefaultValue={shouldDisableInputs}
                        error={this.state.errors.accountNumber} // Pass the error message to the TextInput component
                        onChangeText={(value) => this.handleInputChange('accountNumber', value)}
                    />

                    <CheckboxWithLabel
                        style={styles.mt4}
                        inputID="acceptTerms"
                        LabelComponent={() => (
                            <Text>
                                {this.props.translate('common.iAcceptThe')}
                                <TextLink href={CONST.TERMS_URL}>{this.props.translate('common.expensifyTermsOfService')}</TextLink>
                            </Text>
                        )}
                        defaultValue={this.props.getDefaultStateForField('acceptTerms', false)}
                        shouldSaveDraft
                        error={this.state.errors.acceptTerms} // Pass the error message to the CheckboxWithLabel component
                    />
                </Form>
            </ScreenWrapper>
        );
    }
}

BankAccountManualStep.propTypes = propTypes;
export default withLocalize(BankAccountManualStep);
```

Please review these changes in which I have ensured that error messages are displayed correctly during form submission and cleared appropriately when the user interacts with the form. It will improve the overall user experience and streamline the validation process in the Bank Account Manual Step component.

Looking forward to fixing it for production as well!
Thanks
Regards

**Comment by mudassar69** [comment] 2023-08-03 10:55
Contributor details
Expensify account email: razamudassar867@gmail.com
Upwork Profile Link: https://www.upwork.com/freelancers/~012f6c0781bee2ce23

**Comment by joh42** [comment] 2023-08-07 13:12
As the person who authored https://github.com/Expensify/App/pull/23306, I agree with @chiragxarora. I don't think we can fix this regression while keeping the solution we implemented in that PR. 

CC @eVoloshchak @techievivek

**Comment by techievivek** [comment] 2023-08-08 08:25
I think we can put this on HOLD for now until we have decided the next step [here](https://github.com/Expensify/App/issues/21838#issuecomment-1669144805)

**Comment by techievivek** [comment] 2023-08-10 04:41
We have reverted the original fix https://github.com/Expensify/App/issues/21838#issuecomment-1672542172 that caused this regression, so we can close this now.

**Closed by techievivek** 2023-08-10 04:41 UTC
Labels: Reviewing, Weekly, Bug
