### ISSUE TITLE
[$2000] Web - Sign up - Display name and avatar image does not update automatically

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#20399] opened 2023-06-07 17:41 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Sign up with new account 
2. Check display name and avatar image
3. Refresh

## Expected Result:
Display name and avatar image updated automatically with Clearbit when sign up 

## Actual Result:
Display name and avatar image does not update automatically with Clearbit when sign up 

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [x] MacOS / Chrome
- [ ] MacOS / Desktop

**Version Number:** 1.3.21-2

**Reproducible in staging?:** Yes

**Reproducible in production?:** n/a

**If this was caught during regression testing, add the test name, ID and link from TestRail:**

**Email or phone of affected tester (no customers):**

**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Notes/Photos/Videos:** Any additional supporting documentation

![image (55)](https://github.com/Expensify/App/assets/93399543/20a7127b-4875-4ce7-886e-bacc96fbb461)

![image (54)](https://github.com/Expensify/App/assets/93399543/5707d4dc-840e-40fb-b070-c871d4780261)

**Expensify/Expensify Issue URL:**

**Issue reported by:** David Barrett

**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1685567574364299

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01686e8a575bb277c8</li>
        <li>Upwork Job ID: 1671569692603797504</li>
        <li>Last Price Increase: 2023-06-30</li>
    </ul>
</details>

**Comment by mallenexpensify** [comment] 2023-06-13 00:34
@kbecciv , can you see if you're able to reproduce, I was not able to

**Comment by kbecciv** [comment] 2023-06-15 17:35
I have never used Clearbit before, but if you guide me, happy to try.

**Comment by mallenexpensify** [comment] 2023-06-21 17:15
> Can you test by using an email that associated with a twitter account that has a custom avatar?

@kbecciv can you test again plz?

**Comment by mallenexpensify** [comment] 2023-06-21 17:24
Tested again and was able to reproduce

https://github.com/Expensify/App/assets/22508304/fd7370f5-92d7-4250-9451-617a40e2f871

**Comment by ygshbht** [comment] 2023-06-21 21:03
### Proposal 

Hello Expensify Team,

I'm Yogesh, a seasoned web developer eager to get my hands dirty solving your "Sign up - Display name and avatar image does not update automatically" issue. I understand that it's been up for grabs for a couple of weeks now – but rest assured, when I'm on the task, you won't be kept waiting.

**Based on the provided details, it seems the hitch is in the display name and avatar image not updating right after sign-up. A plausible starting point could be to direct the new display name and avatar image to draw from the same data source that is accurately updating post-refresh. Yet, this initial analysis only scratches the surface. A precise, fail-proof solution can only be determined once I've delved deep into your existing codebase and unraveled its architecture.**

Over the years, I've accumulated a wealth of experience in web development, which is reflected in my 100% job success rate on Upwork. You're welcome to verify this yourself on my profile: https://www.upwork.com/freelancers/~01ca41cc1d47038084. For a more comprehensive look at the diverse array of projects I've undertaken, head over to my portfolio at yogeshbhatt.com.

Let's turn this issue into a non-issue. Looking forward to contributing to Expensify.

Best,
Yogesh

**Comment by mollfpr** [comment] 2023-06-22 15:07
@ygshbht Thank you for your interest in contributing here. We have a template for proposing a solution that you can find in the [CONTRIBUTING.md](https://github.com/Expensify/App/blob/main/contributingGuides/CONTRIBUTING.md).

**Comment by ygshbht** [comment] 2023-06-22 15:28
@mollfpr Thank you for pointing that out. As I'm relatively new here, your guidance is much appreciated!

## Proposal

### Please re-state the problem that we are trying to solve in this issue.
After a new user signs up, the display name and avatar image are not automatically updated via Clearbit.

### What is the root cause of that problem?
It's possible that the application isn't correctly or promptly fetching the updated data from Clearbit post sign-up, or there may be a delay or error in the rendering process.

### What changes do you think we should make in order to solve the problem?
The ideal solution would be to ensure synchronization between the Clearbit data fetch and the UI update mechanism. If this issue resides in the frontend, we might need to restructure the way data is rendered or refresh the display post the Clearbit update. Alternatively, if the problem stems from the backend, we might need to examine how and when data is fetched from Clearbit.

**Comment by mollfpr** [comment] 2023-06-23 13:26
Thanks @ygshbht for the proposal!

What is Clearbit? I'm not sure if we use that. I also not understand what the root cause in our app.

**Comment by ygshbht** [comment] 2023-06-23 13:38
I referenced Clearbit as it was mentioned quite frequently in the initial message of this issue. I apologize if that detail sidetracked - my proposal was rather generic, relying on the information I collected from this Github issue.

As for the root cause, I'm under the impression it's the initial process of fetching and displaying the data that's causing the issue - a delay or miscommunication in the update process. If you could specify what aspect of my explanation was unclear, I would be happy to provide further clarification.

A quick question on my end: How intimately are we expected to understand the app before our proposal is finalized for the job? As a new contributor, I haven't had the chance to work directly with the app's code. For now, I've been going through the README.md and CONTRIBUTING.md for guidance.

> If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email [contributors@expensify.com](mailto:contributors@expensify.com) to request to join our Slack channel!
> 
> ## Action Performed:
> 1. Sign up with new account
> 2. Check display name and avatar image
> 3. Refresh
> 
> ## Expected Result:
> Display name and avatar image updated automatically with Clearbit when sign up
> 
> ## Actual Result:
> Display name and avatar image does not update automatically with Clearbit when sign up
> 
> ## Workaround:
> Unknown
> 
> ## Platforms:
> Which of our officially supported platforms is this issue occurring on?
> 
> * [ ]  Android / native
> * [ ]  Android / Chrome
> * [ ]  iOS / native
> * [ ]  iOS / Safari
> * [x]  MacOS / Chrome
> * [ ]  MacOS / Desktop
> 
> **Version Number:** 1.3.21-2
> 
> **Reproducible in staging?:** Yes
> 
> **Reproducible in production?:** n/a
> 
> **If this was caught during regression testing, add the test name, ID and link from TestRail:**
> 
> **Email or phone of affected tester (no customers):**
> 
> **Logs:** https://stackoverflow.com/c/expensify/questions/4856
> 
> **Notes/Photos/Videos:** Any additional supporting documentation
> 
> ![image (55)](https://user-images.githubusercontent.com/93399543/244152495-20a7127b-4875-4ce7-886e-bacc96fbb461.png)
> 
> ![image (54)](https://user-images.githubusercontent.com/93399543/244152498-5707d4dc-840e-40fb-b070-c871d4780261.png)
> 
> **Expensify/Expensify Issue URL:**
> 
> **Issue reported by:** David Barrett
> 
> **Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1685567574364299
> 
> [View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)
> 
> Upwork Automation - Do Not Edit

**Comment by mollfpr** [comment] 2023-06-23 13:44
@ygshbht I think you can start to run the app on your local machine. Usually, we will try to reproduce the issue in the DEV environment and start analyzing the issue. This way, you will clearly understand what went wrong and what we should fix. 

You are not required to add a diff code to your solution, but it's essential to analyze the root cause that corresponds to our code.

**Comment by ygshbht** [comment] 2023-06-23 15:19
Thanks for the insights! I've initiated a thorough exploration of the app's structure. Interestingly, during my initial attempts to reproduce the issue both locally and on the staging server, the avatar and name (already populated in my Twitter profile) did not update automatically, despite waiting and multiple refresh attempts. My testing environment comprises Windows and Chrome.

Since this is my first deep-dive into the code, I may need a few days at most to familiarize myself with its architecture and to pinpoint the root cause. Once I've gathered more insights, I'll definitely circle back and share my findings. I appreciate your guidance on this matter.

**Comment by ygshbht** [comment] 2023-06-24 01:50
@mollfpr 

I spent some time trying to reproduce the issue on my local setup but encountered a slight roadblock. After multiple attempts, the avatar and name from my Twitter profile didn't show up in the app, despite multiple refreshes and waiting periods.

Considering this, it leads me to think that perhaps Clearbit might require additional time to update this information. Alternatively, there might be some specific conditions or steps involved that I'm not yet aware of.

To proceed efficiently and pinpoint the problem, I believe it would be helpful if I could have access to an account that exhibits the expected behavior, i.e., updates the avatar with the photo that Clearbit provides. This would help me better understand the process flow and come up with a concrete solution.

**Comment by mollfpr** [comment] 2023-06-26 15:09
>I spent some time trying to reproduce the issue on my local setup but encountered a slight roadblock. After multiple attempts, the avatar and name from my Twitter profile didn't show up in the app, despite multiple refreshes and waiting periods.

Yeah, I couldn't make it either.

>To proceed efficiently and pinpoint the problem, I believe it would be helpful if I could have access to an account that exhibits the expected behavior, i.e., updates the avatar with the photo that Clearbit provides. This would help me better understand the process flow and come up with a concrete solution.

@mallenexpensify Do we have this kind of account? I just created a new Twitter account and then signed up the email to NewDot but it does not display the avatar or my display name from Twitter.

**Comment by mallenexpensify** [comment] 2023-06-26 22:27
@mollfpr and @ygshbht , for Clearbit, my guess is that the avatars from twitter aren't updated quickly, so it likely wouldn't work with a new account.  

I think this issue falls into the bucket of "app not updating dynamically".   From the steps in the OP

1. Sign up with new account
2. Check display name and avatar image (generic avatar)
3. Once we have a new avatar, we should update it instantly, without the user needing to refresh. 
 
 I asked about this [here](https://expensify.slack.com/archives/C01GTK53T8Q/p1687471385852519)
 > I'm been seeing a lot of bug reports about parts of the app not dynamically updating.  I'm going to continue to treat these individually as bugs, if they should be rolled into a project or tracking GH, please :thread:   cc 
[@Dhanashree Dattaram Sawant](https://expensify.slack.com/team/U04FW4A1RHR)
, since it appears you're reporting a lot of 'em

**Comment by mollfpr** [comment] 2023-06-27 07:53
@mallenexpensify Thanks. I can make it updated with my primary email.

The avatar and display name did update after refresh or open a new chat.

**Comment by BilalAtique** [comment] 2023-06-28 11:44
@ygshbht How did you setup project locally on windows?
I receive the following error while running npm install:
```
npm ERR! code 1
npm ERR! path D:\expensify\App\node_modules\shellcheck
npm ERR! command failed
npm ERR! command C:\Windows\system32\cmd.exe /d /s /c ./install.sh
npm ERR! '.' is not recognized as an internal or external command,
npm ERR! operable program or batch file.
```

**Comment by BilalAtique** [comment] 2023-06-28 11:51
Contributor details
Your Expensify account email: bilalbinatique@gmail.com
Upwork Profile Link: https://www.upwork.com/freelancers/~0137e567875b2c6be4

**Comment by ygshbht** [comment] 2023-06-28 22:17
> @ygshbht How did you setup project locally on windows? I receive the following error while running npm install:
> 
> ```
> npm ERR! code 1
> npm ERR! path D:\expensify\App\node_modules\shellcheck
> npm ERR! command failed
> npm ERR! command C:\Windows\system32\cmd.exe /d /s /c ./install.sh
> npm ERR! '.' is not recognized as an internal or external command,
> npm ERR! operable program or batch file.
> ```

Use WSL

**Comment by mallenexpensify** [comment] 2023-06-30 03:37
Bumping this to $2000 to see if we can get it figured out before taking internally or to a contributor-agency

**Comment by alitoshmatov** [comment] 2023-06-30 07:17
I think the issue is in the backend side, since there is no logic to handle this in client side.

**Comment by mollfpr** [comment] 2023-07-03 15:20
Not overdue, but I will check whether it's a BE issue.

**Comment by mollfpr** [comment] 2023-07-05 04:14
Kind of miss this issue, I will check again today.

**Comment by rfwoolf** [comment] 2023-07-05 08:39
Contributor details
Your Expensify account email: rfwoolf@gmail.com
Upwork Profile Link: https://www.upwork.com/freelancers/~01488b1374506aa570

Please can someone invite me to the slack channels.

I have created a test environment on Windows, but I am stuck here:
My browser loads the page with url localhost:8080 and displays a logo (see below).
Is that correct? How is this a test environment - how do I interact with it or log in?
![image](https://github.com/Expensify/App/assets/312073/917c99e3-814e-41cb-ae6d-8e22237d0f43)

**Comment by rfwoolf** [comment] 2023-07-08 17:09
> Contributor details Your Expensify account email: [rfwoolf@gmail.com](mailto:rfwoolf@gmail.com) Upwork Profile Link: https://www.upwork.com/freelancers/~01488b1374506aa570
> 
> Please can someone invite me to the slack channels.
> 
> I have created a test environment on Windows, but I am stuck here: My browser loads the page with url localhost:8080 and displays a logo (see below). Is that correct? How is this a test environment - how do I interact with it or log in? ![image](https://user-images.githubusercontent.com/312073/251089478-917c99e3-814e-41cb-ae6d-8e22237d0f43.png)

Hi all
I'd be grateful if someone could please help me with this.

**Comment by rfwoolf** [comment] 2023-07-08 17:10
Contributor details
Your Expensify account email: rfwoolf@gmail.com
Upwork Profile Link: https://www.upwork.com/freelancers/~01488b1374506aa570

**Comment by mollfpr** [comment] 2023-07-09 12:21
> Please can someone invite me to the slack channels.

@rfwoolf Have you send email to [contributors@expensify.com](mailto:contributors@expensify.com) with the subject Slack Channel Invites?

> My browser loads the page with url localhost:8080 and displays a logo (see below).

I'm not sure what is happening, but usually, I try to clear the storage or use incognito mode.

**Comment by rfwoolf** [comment] 2023-07-09 16:07
>"@rfwoolf Have you send email to [contributors@expensify.com](mailto:contributors@expensify.com) with the subject Slack Channel Invites?"
Yes, I've done so 2-3 times with no response:
![image](https://github.com/Expensify/App/assets/312073/80bab89d-ecf1-4f96-8c24-9b663cc4cdfa)

>"I'm not sure what is happening, but usually, I try to clear the storage or use incognito mode."
Thanks! I've tried multiple browsers but no luck. It'd be helpful to see even just 1 example, so I know exactly what to try replicate.

**Comment by mallenexpensify** [comment] 2023-07-12 02:21
@rfwoolf it looks like you were invited to the Slack channels, comment if not and I'll try to do it

**Comment by mallenexpensify** [comment] 2023-07-12 02:27
I think this issue falls into the 'update dynamically' category but I can't say with certainty.  The avatar eventually updates, it just doesn't do it immediately, with no other actions taken.  Removed and readded the `Engineering` label to get more eyes here.  @johnmlee101 ,   thoughts here? 

Two resources... 
1. Slack chat about 'dynamically update' where we plan to treat those as feature requests is [here](https://expensify.slack.com/archives/C01GTK53T8Q/p1689009972403289?thread_ts=1688646398.596839&cid=C01GTK53T8Q)
2. Tracking issue for 'dynamically updated' in case we want to add this to that. 
3. - https://github.com/Expensify/App/issues/22699

**Comment by rfwoolf** [comment] 2023-07-12 02:29
> I think @mallenexpensify can help you with the invitation.
@mallenexpensify - I have now been invited to slack. Many thanks :)

@mollfpr 
>"Is there any error in your console log? Or is that also happen with staging or production sites?
Firstly, I have tried 5 different browsers, so it isn't a cache issue as far as I can tell.
In terms of console errors, yes there are some errors concerning `exports` but they seem mild or false alarms:
![image](https://github.com/Expensify/App/assets/312073/1edcc276-1d16-41a4-a154-f9a41f7c591e)
In terms of terminal / compile errors, I have 7 errors also related to exports:
![image](https://github.com/Expensify/App/assets/312073/517cc7b6-63f9-497f-9629-d0ab9a1d208f)

**Comment by mallenexpensify** [comment] 2023-07-17 21:39
@johnmlee101 👀 above plz
https://github.com/Expensify/App/issues/20399#issuecomment-1631754923

**Comment by johnmlee101** [comment] 2023-07-17 21:52
Yeah I agree, its a very dynamic thing. It's a bedrock job in the background, so ultimately you're up to a bit of variability on whether you see this happen soon or later. I think in most instances it will be a bit slower since our Clearbit implementation isn't instant, and we shouldn't also block the app on it or show a loading indicator since it might not even populate with anything. 

I don't think its a bug, but rather something that if our implementation was different we could improve.

**Comment by mallenexpensify** [comment] 2023-07-18 18:29
@quinthar can you review John's comment above?  We're likely to close this issue and you raised it as a bug.  I would add to the [Dynamic updating tracking issue](https://github.com/Expensify/App/issues/22699) we have too, in case we ever want to holistically address it.

**Comment by mallenexpensify** [comment] 2023-07-21 14:40
Added to the tracking list, closing.  Reopen/comment if you disagree
- https://github.com/Expensify/App/issues/22699

**Closed by mallenexpensify** 2023-07-21 14:40 UTC
Labels: Engineering, Daily, Internal, Overdue, Bug
