### ISSUE TITLE
[$500] In edit message, cursor shifts back on inserting emoji

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#27273] opened 2023-09-12 17:07 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Open the app
2. Open any report
3. Write some text and write wrong emoji text like :hheart:
4. Rectify the emoji and observe that cursor shifts to end of emoji after emoji is inserted
5. Send the message with or without emoji
6. Edit the message and again write wrong emoji text like :hheart:
7. Rectify and observe that cursor shifts few characters back

## Expected Result:
Cursor should shift to end of text after emoji is added

## Actual Result:
Cursor shifts back few characters after emoji is rectified in edit mode

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [x] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 1.3.68.12
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/93399543/8dda3702-5817-40c0-93ae-5822827d5798

**Expensify/Expensify Issue URL:**
**Issue reported by:**  @dhanashree-sawant
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1694189660065529

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01c31527ad022a2246</li>
        <li>Upwork Job ID: 1701643656830824448</li>
        <li>Last Price Increase: 2023-09-12</li>
<li>Automatic offers: </li>
<ul>
<li>ahmedGaber93 | Contributor | 26674793</li>
</ul></li>
    </ul>
</details>

**Comment by ahmedGaber93** [comment] 2023-09-12 17:27
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
In edit message, cursor shifts back on inserting emoji
### What is the root cause of that problem?
this issue is fixed here https://github.com/Expensify/App/issues/17275 for main composer but not fixed for edit composer
### What changes do you think we should make in order to solve the problem?
apply the same fix here
`const remainder = ComposerUtils.getCommonSuffixLength(prevDraft, newDraft);`
https://github.com/Expensify/App/blob/3e506835eb7214ae15c3e36334484188c8ba50e3/src/pages/home/report/ReportActionItemMessageEdit.js#L186

### What alternative solutions did you explore? (Optional)

**Comment by amyevans** [comment] 2023-09-14 14:21
I don't think the `[HOLD]` in this title is valid 🤔 I'm going to remove it, but someone please correct me if I'm wrong

**Comment by amyevans** [comment] 2023-09-14 14:23
Okay sorry, just checked the linked Slack thread, I think the HOLD was intentional. So @ahmedGaber93 please don't start on a PR yet.

**Comment by amyevans** [comment] 2023-09-14 14:24
Held on https://github.com/Expensify/App/issues/27195

**Comment by ahmedGaber93** [comment] 2023-09-14 15:50
Ok, I will wait #27195, thanks @amyevans.

**Comment by amyevans** [comment] 2023-09-26 12:28
Still on hold

**Comment by stephanieelliott** [comment] 2023-10-04 01:20
Still on hold for https://github.com/Expensify/App/issues/27195,

**Comment by stephanieelliott** [comment] 2023-10-11 05:07
Still on hold for https://github.com/Expensify/App/issues/27195,

**Comment by stephanieelliott** [comment] 2023-10-17 01:21
Looks like https://github.com/Expensify/App/issues/27195 was merged -- we suspected that PR may also fix this issue. @kbecciv would you mind retesting this one?

**Comment by amyevans** [comment] 2023-10-25 13:30
Friendly bump @kbecciv

**Comment by stephanieelliott** [comment] 2023-10-30 16:17
I went ahead and tested, I am not seeing the behavior anymore so it seems like this is fixed. Closing!

**Closed by stephanieelliott** 2023-10-30 16:17 UTC
Labels: External, Weekly, Bug
