### ISSUE TITLE
[HOLD for payment 2023-10-30] [HOLD for payment 2023-09-15] [$1000] HIGH [W4 Scan Receipts] LHN shows `user paid $0.00` when sending first money request via Scan

### ISSUE THREAD

**Issue by luacmartins** [Expensify/App#25778] opened 2023-08-23 15:50 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. As userA, request money from userB via `Scan`
2. Notice that the LHN shows `<user> paid $0.00`

## Expected Result:
The LHN should show `Scan in progress`

## Actual Result:
LHN says `<user> paid $0.00`

## Workaround:
Can the user still use Expensify without this being fixed? Have you informed them of the workaround?

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android / native
- [x] Android / Chrome
- [x] iOS / native
- [x] iOS / Safari
- [x] MacOS / Chrome / Safari
- [x] MacOS / Desktop

**Version Number:**
**Reproducible in staging?:**
**Reproducible in production?:**
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation
**Expensify/Expensify Issue URL:**
**Issue reported by:**
**Slack conversation:**

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)
![Screenshot 2023-08-23 at 9 46 40 AM](https://github.com/Expensify/App/assets/22219519/405d43aa-22c5-43fd-b20f-f81b59ea0b29)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~015c1a629214ef23ce</li>
        <li>Upwork Job ID: 1694442535880183808</li>
        <li>Last Price Increase: 2023-08-23</li>
    </ul>
</details>

**Comment by ygshbht** [comment] 2023-08-23 23:10
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
LHN shows user paid $0.00 when sending first money request via Scan

### What is the root cause of that problem?
`getMoneyRequestReportName` function doesn't have check for scanning receipts.

### What changes do you think we should make in order to solve the problem?
Add the below code to show the correct status.
```
// eslint-disable-next-line no-use-before-define
const transactionsWithReceipts = getTransactionsWithReceipts(report.reportID);
if (_.some(transactionsWithReceipts, (transaction) => TransactionUtils.isReceiptBeingScanned(transaction))) {
    return Localize.translate(undefined, 'iou.receiptScanning');
}
```
The above will show the message if any receipt in the Report is being scanned. To show only for the last message, we can only check with the `lastReportAction`. We can get that by passing it as argument or use methods such as `getLastVisibleMessage` (have further checks to see if its not a pending action like delete). 


https://github.com/Expensify/App/assets/65986357/e600b0de-3e2b-40e8-a598-28bb303f2b79



<sub>Though it's not main issue listed here, i'd like to mention that if such message has to be shown somehwere else, like in the report where the IOU was created, similar logic can be used in functions like `getLastMessageTextForReport`.  </sub>

**Comment by luacmartins** [comment] 2023-08-24 15:32
@ygshbht proposal looks mostly good to me, but what is the first undefined param here `Localize.translate(undefined, 'iou.receiptScanning');`?

**Comment by luacmartins** [comment] 2023-08-24 15:33
We can sort that out in the PR review. Assigning you to the issue.

**Comment by ygshbht** [comment] 2023-08-24 22:51
@luacmartins  @thesahindia The [PR](https://github.com/Expensify/App/pull/25906) is ready for review!

**Comment by ygshbht** [comment] 2023-09-05 20:03
@luacmartins Can this be eligible for bonus? The PR was ready within a day of assignment. Then a slight delay due to change of C+. Post that some additional changes to other places were mentioend. And then once again. All these changes were done immediately within few hours or maximum a day due to timezone. Then some of those additional changes were reverted. At last, the PR ended up fixing issue different than the original one. I'd even say for such intensive back and forth and revisions, the base price should be doubled lol 😆. However, I'll respect whatever you deem fair

**Comment by luacmartins** [comment] 2023-09-07 20:35
Hey @ygshbht! We certainly appreciate the speed in the response and I think your contributions have been great so far. While I understand there have been delays in getting the PR reviewed and discussions, these are part of the process and and we have accounted for them in deciding to pay a speed bonus. So in this case, I'd say that no bonus is applicable.

Again, I think you've been doing great work and I'm sure you'll be getting a lot of speed bonuses in other issues. Let's keep it up!

**Comment by ygshbht** [comment] 2023-09-07 21:50
@luacmartins I understand. My primary concern has been the change of requirements throughout the process which was not outlined in the original issue. And as you see, the end result is different than what the original issue wanted to fix (title of LHN vs subtitle of LHN). Nevertheless, if you still feel that no bonus should be applicable, no problem with that

> Post that some additional changes to other places were mentioend. And then once again. All these changes were done immediately within few hours or maximum a day due to timezone. Then some of those additional changes were reverted. At last, the PR ended up fixing issue different than the original one

**Comment by maddylewis** [comment] 2023-09-13 18:19
payment due Friday

**Comment by maddylewis** [comment] 2023-09-13 19:25
### Payments
- [ ] Reporting bonus - N/A
- [ ] Contributor ($1k) - @ygshbht 
- [ ] C+ ($1k - paid via NewDot) - @allroundexperts

**Comment by maddylewis** [comment] 2023-09-14 18:19
if no regressions, will pay @ygshbht on 9/15.

**Comment by maddylewis** [comment] 2023-09-15 18:26
everyone is paid 👍

**Comment by luacmartins** [comment] 2023-09-18 00:56
I think this will be covered by receipt regression tests once we create those. So no need to create a separate test for it.

**Comment by luacmartins** [comment] 2023-09-18 00:56
I think we're good to close this issue. Thanks everyone!

**Comment by ygshbht** [comment] 2023-09-18 03:41
Thanks @maddylewis. I have accepted the Upwork job offer

**Comment by maddylewis** [comment] 2023-09-22 14:12
sorry for the delay @ygshbht - paid now!

**Comment by ygshbht** [comment] 2023-09-22 14:18
No problem. Thanks!

**Comment by JmillsExpensify** [comment] 2023-10-05 12:52
$1,000 payment approved for @allroundexperts based on BZ summary.

**Comment by trjExpensify** [comment] 2023-10-13 11:53
👋 @ygshbht @allroundexperts @luacmartins looks like `user paid $0.00` is still showing as the iouReport/expenseReport title in the LHN when the receipt scan is in progress.  

https://github.com/Expensify/App/assets/16232057/a5e1716c-1e71-45c4-9950-fadfbda08a0f

If the expense/iouReport is viewed in the LHN while the only request on it is still scanning, it should be showing as: 

**iouReport**
`%displayName% owes $0.00`
`Receipt scan in progress...`

**expenseReport**
`%workspaceName% owes $0.00`
`Receipt scan in progress...`

**Comment by trjExpensify** [comment] 2023-10-13 11:57
Can you guys help look into this please? I'm going to track this now in wave7.

**Comment by ygshbht** [comment] 2023-10-13 13:09
@trjExpensify I think that was the inital job but had to revert due to change in requirements. You can follow the dicussion in the [PR](https://github.com/Expensify/App/pull/25906) or read only from [here](https://github.com/Expensify/App/pull/25906#issuecomment-1705465391). Unfortunately, there were confusions 
![image](https://github.com/Expensify/App/assets/65986357/12675e6f-f837-4d1e-b3b8-650cafac1e1c)

**Comment by ygshbht** [comment] 2023-10-13 15:38
@trjExpensify Sorry, I don't understand. 
 Here is the expectation and I asking for clarificaiton 
![image](https://github.com/Expensify/App/assets/65986357/9d2e7e43-1bc1-41af-be2c-a740db57acfb)
Here's the response https://github.com/Expensify/App/pull/25906#issuecomment-1705480579
![image](https://github.com/Expensify/App/assets/65986357/a44b6459-ea53-4a14-b3d5-7aab685305c5)

**Comment by trjExpensify** [comment] 2023-10-13 16:42
Right, and prior to the receipt scan completing then the title of the expenseReport (providing this is the only request on the report) is `%workspaceName% owes $0.00`?

**Comment by ygshbht** [comment] 2023-10-13 17:05
That's what you see, don't you? 
From what i infer, you probably want to show the `Scan in progress..` message for LHN title if it's the first `reportAction` as the job title says? 
Again, this was the basis on which I did/ undid the changes
![image](https://github.com/Expensify/App/assets/65986357/24f0ddb8-7682-4590-9e5a-54f3edcc7a56)

https://github.com/Expensify/App/pull/25906#issuecomment-1705465391
![image](https://github.com/Expensify/App/assets/65986357/30ed2fa5-68fd-4cd3-bc88-9570dcab67dd)
Minor issues here and there happen. I regret if its a fault on my side. 
If you want, I am more than willing to implement your request through a new job.

**Comment by trjExpensify** [comment] 2023-10-13 17:24
>From what i infer, you probably want to show the Scan in progress.. message for LHN title if it's the first reportAction as the job title says?

Ah, so that's the diff. I'm not saying that. For the expenseReport...
The LHN title is: `%workspaceName% owes $0.00`
The LHN description is: `Receipt scan in progress...`

Right now the LHN title is `user paid $0.00` which is incorrect. The LHN description is correct.

**Comment by ygshbht** [comment] 2023-10-13 17:39
So instead of `user paid $0.00`, you want to show `%workspaceName% owes $0.00`? `Owe` instead of `Pay`?

**Comment by trjExpensify** [comment] 2023-10-13 18:23
Correct, owes, and more specifically given we have two types of reports in question here: 

**iouReport**
%displayName% owes $0.00
Receipt scan in progress...

**expenseReport**
%workspaceName% owes $0.00
Receipt scan in progress...

**Comment by ygshbht** [comment] 2023-10-13 18:26
Sorry, whats the `iouReport `from the below three? Is it the **request view**?
![image](https://github.com/Expensify/App/assets/65986357/ba1d0c34-7cec-488c-93d8-bdb686757716)

**Comment by trjExpensify** [comment] 2023-10-13 18:33
It's the expenseReport one. 

If I request money from you, the expense goes on a report of type `iou` and therefore **you** owe me. 
If I request money from my company on a workspace, the expense goes on a report of type `expense` therefore the **workspace** owes me.

**Comment by ygshbht** [comment] 2023-10-13 18:38
Ok, so in iou, `user owes` and in expense `workspace owes`. 
And does this needs to be shown under the condition that there's only one `reportAction ` and is being scanned or when the owe amount is 0?

**Comment by trjExpensify** [comment] 2023-10-16 11:18
>Ok, so in iou, user owes and in expense workspace owes.

That's correct! 

>I can make that change and create a small PR with the commit or push it to this PR.

I don't understand the latter as an option because this PR has been deployed already. I also don't think this needs a new issue, so can we please create a follow-up PR linked to this issue to fix it?

**Comment by ygshbht** [comment] 2023-10-16 15:30
@trjExpensify The `owes` is not limited to the first request or scan request right? Instead of showing `user paid $$`, you always want to show `userB owes $$`?

**Comment by ygshbht** [comment] 2023-10-16 16:22
@trjExpensify Created [PR](https://github.com/Expensify/App/pull/29689)

**Comment by trjExpensify** [comment] 2023-10-30 11:55
Okay, so with that now taken care of I think we can proceed to close this out for good now. Thanks everyone!

**Closed by trjExpensify** 2023-10-30 11:55 UTC
Labels: External, Weekly, Awaiting Payment, Bug
