### ISSUE TITLE
[HOLD for payment 2023-08-01] [$1000] User was not shown on Invite members page after immediately inviting

### ISSUE THREAD

**Issue by kavimuru** [Expensify/App#22442] opened 2023-07-07 20:09 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1) Go to workspace invite member page -> Invite
2) Type a new user whom you have not interacted yet
3) Invite them
4) Observe invite member page
## Expected Result: 
The invited user should immediately show up in the invite member page
## Actual Result: 
The invited user shows up after sometime

## Workaround:
Can the user still use Expensify without this being fixed? Have you informed them of the workaround?

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [x] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 1.3.38-3
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/43996225/27cdd13e-ae7b-4b19-971e-02a5ca7cc8f4

https://github.com/Expensify/App/assets/43996225/0e80d8bd-aa14-4231-ab73-df495e299eb9

**Expensify/Expensify Issue URL:**
**Issue reported by:** @abdulrahuman5196 
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1688755739075519

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~0101aca3aeff5e6e57</li>
        <li>Upwork Job ID: 1678399914954649600</li>
        <li>Last Price Increase: 2023-07-10</li>
    </ul>
</details>

**Comment by maddylewis** [comment] 2023-07-10 13:45
C+ assigned to review existing proposal

**Comment by s77rt** [comment] 2023-07-10 19:29
@samh-nl Thanks for the proposal. Your RCA is correct. The solution makes sense.

:ribbon: :eyes: :ribbon: C+ reviewed

**Comment by yuwenmemon** [comment] 2023-07-13 05:15
@samh-nl let us know when you have a PR!

**Comment by maddylewis** [comment] 2023-07-17 13:55
PR is up - will be reviewed this week 👍

**Comment by maddylewis** [comment] 2023-07-19 20:51
@yuwenmemon is reviewing here - https://github.com/Expensify/App/pull/22904#issuecomment-1642446157

**Comment by s77rt** [comment] 2023-07-19 22:35
PR is merged

**Comment by maddylewis** [comment] 2023-07-21 18:27
Payments: 
- [ ] [abdulrahuman5196](https://github.com/abdulrahuman5196) - $250 (reporting)
- [ ] @s77rt - $1000 (C+)
- [ ] @samh-nl - $1000 (contributor)

**Comment by s77rt** [comment] 2023-07-22 00:16
PR is merged already, Melvin

**Comment by maddylewis** [comment] 2023-07-24 17:06
PR is merged / awaiting regression period before issuing payment 👍

**Comment by maddylewis** [comment] 2023-07-29 14:06
moving to daily since payments are due early next week

**Comment by maddylewis** [comment] 2023-08-02 17:57
### Payments: 
- [ ] [abdulrahuman5196](https://github.com/abdulrahuman5196) - $250 (reporting)
- [ ] @s77rt - $1000 (C+)
- [ ] @samh-nl - $1000 (contributor)

**Comment by maddylewis** [comment] 2023-08-02 18:03
everyone is paid - closing!

**Closed by maddylewis** 2023-08-02 18:03 UTC
Labels: Reviewing, External, Daily, Awaiting Payment, Bug
