### ISSUE TITLE
[HOLD for payment 2023-10-10] [$500] Stop storing queued Onyx updates to disk

### ISSUE THREAD

**Issue by marcaaron** [Expensify/App#25612] opened 2023-08-21 18:38 UTC
# Problem

In some cases, the payload of `OpenApp` is very large and since we save all Onyx responses to disk in `queuedOnyxUpdates` this leads to double-storing our largest resource. It will be deleted after, but doesn't seem like there is a clear reason why these updates should be persisted instead of just hanging around in memory.

# Solution

Let's store the "queued updates" in memory instead.
<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01451356cead02359a</li>
        <li>Upwork Job ID: 1702119738769117184</li>
        <li>Last Price Increase: 2023-09-29</li>
    </ul>
</details>

**Comment by marcaaron** [comment] 2023-08-24 22:23
Just blocked on testing on all platforms. Will try to get this done today.

**Comment by marcaaron** [comment] 2023-08-29 21:55
Focusing on pagination research atm. I will try to run through test steps for this one today.

**Comment by marcaaron** [comment] 2023-09-14 00:42
Hey @alexpensify this is something I am fixing and enlisting the C+ to help with on reviews. There was no bug report or anything as it's more of an improvement, so I checked off everything on the BZ checklist.

**Comment by alexpensify** [comment] 2023-09-14 16:11
@marcaaron - when is the payment date for this one?

**Comment by situchan** [comment] 2023-09-14 16:34
> @marcaaron - when is the payment date for this one?

N/A as PR was not merged yet

**Comment by alexpensify** [comment] 2023-09-18 19:06
Update: The PR is still under review.

**Comment by alexpensify** [comment] 2023-09-25 08:36
It looks like the PR is moving along but there is a lint error to address.

**Comment by alexpensify** [comment] 2023-09-28 07:21
@marcaaron can you review the lint error flag? Thanks!

**Comment by marcaaron** [comment] 2023-09-28 09:25
Yep sorry this one slipped through the cracks - thanks for the bump @alexpensify

**Comment by marcaaron** [comment] 2023-09-29 04:50
Merged and waiting for deploy

**Comment by alexpensify** [comment] 2023-09-29 05:14
@situchan - it looks like automation might not kick in, so please apply here: 

https://www.upwork.com/jobs/~01451356cead02359a

**Comment by alexpensify** [comment] 2023-10-05 23:38
@situchan looks like the previous Upwork link was not working, so can you apply to this one --- https://www.upwork.com/jobs/~01a80b6b1d1c2a3260

Thanks!

**Comment by situchan** [comment] 2023-10-06 03:08
Applied thanks

**Comment by alexpensify** [comment] 2023-10-10 23:35
Here is the payment summary: 

-  External issue reporter N/A 
-  Contributor that fixed the issue N/A 
-  Contributor+ that helped on the issue and/or PR @situchan $500 

Upwork Job: https://www.upwork.com/jobs/~01a80b6b1d1c2a3260

*If applicable, the bonuses will be applied on the final payment 

Extra Notes regarding payment: Confirmed here that there is no need to complete the BZ -- https://github.com/Expensify/App/issues/25612#issuecomment-1718491612

**Comment by alexpensify** [comment] 2023-10-10 23:35
@situchan - I've extended the contract in Upwork, please accept and I can complete he payment process. Thanks!

**Comment by alexpensify** [comment] 2023-10-11 21:07
The payment has been sent out. All set here, so closing for now.

**Closed by alexpensify** 2023-10-11 21:07 UTC
Labels: Daily, Improvement, Internal, Help Wanted, Awaiting Payment, Bug
