### ISSUE TITLE
[$500] Not able to get the Hybrid app to go into NewDot app

### ISSUE THREAD

**Issue by m-natarajan** [Expensify/App#36717] opened 2024-02-16 16:58 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.42-1 and OD app version 8.5.39
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** @danielvldal
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1708054233917059

## Action Performed:
1. Open OD app
2. Tap on "Try New Expensify

## Expected Result:
Use lands in ND app

## Actual Result:
The link in the page is not clickable and can't go back 

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [x] iOS: Native
- [ ] iOS: mWeb Safari
- [ ] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

https://github.com/Expensify/App/assets/38435837/bd672e1f-f09a-493e-a2a3-d4567bcf49d1

![IMG_4806](https://github.com/Expensify/App/assets/38435837/c0f8b8f3-5b10-44df-923e-d09eb0444545)

<img src="https://github.com/Expensify/App/assets/38435837/c0f8b8f3-5b10-44df-923e-d09eb0444545" width=“40%” height=“40%“>

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01f8c5a663acb0d15e</li>
        <li>Upwork Job ID: 1758536328807780352</li>
        <li>Last Price Increase: 2024-02-16</li>
    </ul>
</details>

**Comment by AndrewGable** [comment] 2024-02-16 17:00
This is internal

**Comment by AndrewGable** [comment] 2024-02-16 23:45
According to git bisect this is the commit 21711bc0ed1e9dd9e8e0042b539a85e91649d9a1 and this PR is the issue: https://github.com/Expensify/App/pull/34777

**Comment by AndrewGable** [comment] 2024-02-17 01:26
Sent PR to fix

**Comment by AndrewGable** [comment] 2024-02-19 16:39
Yes, that wouldn't hurt

**Comment by roryabraham** [comment] 2024-03-01 23:53
Chatted with @AndrewGable about this and I'm going to help get https://github.com/Expensify/App/pull/36750 over the finish line next week. I need some experience running HybridApp locally

**Comment by roryabraham** [comment] 2024-03-11 23:08
working on this in https://github.com/Expensify/App/pull/36750

**Comment by roryabraham** [comment] 2024-03-12 06:19
super duper stuck here 😭 

https://expensify.slack.com/archives/C01GTK53T8Q/p1710224144415049

**Comment by roryabraham** [comment] 2024-03-12 22:40
Spent more time on this today and got unstuck, with a working build. However, I'm finding that the PR isn't solving the issue. The app transition flows are notoriously complicated, hard to bug, and brittle towards with so many different entry points / states we need to handle.

So I'm considering taking a new approach here, and doing some TDD, with component tests that render the whole app and simulate various scenarios. I believe this will:

- help me understand the app transition code more holistically
- codify better how it's _supposed_ to work
- give me better confidence in making changes without breaking stuff
- hopefully prevent future regressions

It's difficult to know before I dive in how difficult or worthwhile this approach may be.

**Comment by roryabraham** [comment] 2024-03-12 23:16
@AndrewGable encouraged me to try out and older commit (`d72cda0382c4d6f35d7f040bf14d31aa7c062d55`) from the PR branch (before review comments) and see if it works. I manually applied changes to get back to that state, and we'll see if it works

**Comment by roryabraham** [comment] 2024-03-12 23:18
doesn't seem to work unfortunately

**Comment by roryabraham** [comment] 2024-03-12 23:23
Going to try to enumerate all the different factors that can create variations of the "app transition" flow:

- a `url` parameter provided to the top-level `<App>` component (provided by HybridApp)
- an `exitTo` parameter provided in the URL/route (comes from `Linking.getInitialURL` asynchronously). Common `exitTo` urls might be:
    - home
    - a specific report
    - settings for a specific workspace
- Whether the same user, a different user, or no user was signed in on NewDot
- Whether we have a `shortLivedToken` or `shortLivedAuthToken` provided via route params
- Whether we have a supportal token or not
- anything else???

**Comment by roryabraham** [comment] 2024-03-13 01:20
Have started to scratch the surface on app transition tests in https://github.com/Expensify/App/pull/38195/files

**Comment by roryabraham** [comment] 2024-03-18 19:43
I see that @AndrewGable pushed some fresh code to https://github.com/Expensify/App/pull/36750. I had run into an infinite loop issue with the same diff in my testing last week, but it's possible that I had something misconfigured. going to retest (tomorrow, since I have a flight to catch pretty soon here today). @mananjadhav if you can get to it before me that would be great!

**Comment by anmurali** [comment] 2024-03-19 21:44
Just updated both apps to the latest on Test Flight and it works now. But it is quite slow to load New Dot. @AndrewGable is that to be expected? Took like 15 seconds to load my chats/ LHN.

**Comment by AndrewGable** [comment] 2024-03-19 21:47
Is it loading any slower than NewDot on a fresh login? I think there is a bug on NewDot and it's not exclusive to HybridApp

**Comment by roryabraham** [comment] 2024-03-20 19:47
For me, it loaded in about 5 or 6 seconds. This appears to be fixed, so I'm going to close it. I think any TTI performance concerns on the NewDot side should be addressed separately

**Closed by roryabraham** 2024-03-20 19:47 UTC
Labels: Engineering, Daily, Internal, Bug

**Comment by mananjadhav** [comment] 2024-03-31 16:39
@roryabraham @AndrewGable  Will there by any partial payout for the first review that I did on the PR?

**Comment by AndrewGable** [comment] 2024-04-17 16:19
Yes, you reviewed so payout is eligible 👍

**Comment by mananjadhav** [comment] 2024-04-17 17:26
@anmurali can you please add a payout summary for this one ?

**Comment by mananjadhav** [comment] 2024-04-23 19:43
@anmurali quick bump

**Comment by anmurali** [comment] 2024-04-23 20:25
-[ ] $250 to @mananjadhav approved per [Slack conversation](https://expensify.slack.com/archives/C02NK2DQWUX/p1713903752712589?thread_ts=1713323524.607299&cid=C02NK2DQWUX) on ND

**Comment by mananjadhav** [comment] 2024-04-23 21:06
Thanks @AndrewGable @anmurali

**Comment by JmillsExpensify** [comment] 2024-04-25 00:16
$250 approve for @mananjadhav
