### ISSUE TITLE
[PAYMENT DUE 2024-03-06] [$500] RHP - User redirected from "Room" tab to "Chat" tab when tapped on the back button

### ISSUE THREAD

**Issue by kavimuru** [Expensify/App#35143] opened 2024-01-25 12:43 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.31-1
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** Applause internal team
**Slack conversation:**

## Action Performed:
1. Open app
2. Tap on FAB
3. Select "Start Chat"
4. Select "Room" tab
5. Tap on back button
## Expected Result:
RHP should be closed and user should be navigated to LHN when user tapped on back button

## Actual Result:
User redirected from "Room" tab to "Chat" tab when tapped on the back button

## Workaround:
Can the user still use Expensify without this being fixed? Have you informed them of the workaround?

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [x] Android: mWeb Chrome
- [x] iOS: Native
- [x] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

https://github.com/Expensify/App/assets/43996225/b5a44953-8900-46d2-8942-a0377109fd02

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01a7c80f42a2fdfb07</li>
        <li>Upwork Job ID: 1750499615463923712</li>
        <li>Last Price Increase: 2024-01-25</li>
<li>Automatic offers: </li>
<ul>
<li>situchan | Reviewer | 28134705</li>
<li>bernhardoj | Contributor | 28134706</li>
</ul></li>
    </ul>
</details>

**Comment by FitseTLT** [comment] 2024-01-25 12:48
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
User redirected from "Room" tab to "Chat" tab when tapped on the back button

### What is the root cause of that problem?
We are using the default back mechanism here
https://github.com/Expensify/App/blob/74f11635afab513d3c7cf12b70c286b4f3cd4d74/src/pages/NewChatSelectorPage.js#L36-L37
### What changes do you think we should make in order to solve the problem?

We need to dissmissModal instead
### What alternative solutions did you explore? (Optional)

**Comment by Pujan92** [comment] 2024-01-25 13:03
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
On back for new chat selector the modal is not dismissed

### What is the root cause of that problem?
It seems to be intentional from this [PR](https://github.com/Expensify/App/pull/28138) where we have removed dismissing the modal for issue https://github.com/Expensify/App/issues/27669. Issue was - when the modal is opened for settings and if we use keyboard shortcut CTRL+SHIFT+K to open start chat and click back then it is not going back to the settings modal.

### What changes do you think we should make in order to solve the problem?
We can re-add the `onBackButtonPress` which will dismiss the modal.

**Comment by JordanLevy19** [comment] 2024-01-25 13:33
**Proposal**

**Please re-state the problem that we are trying to solve in this issue.**
When a user selects the 'Room' tab within the 'New Chat' page and then taps the back button, the app redirects them to the 'Chat' tab instead of closing the Right Hand Panel (RHP) and returning them to the Left Hand Navigation (LHN)

**What is the root cause of that problem?**
The root of the issue may be found within the following parts of the code:

HeaderWithBackButton: The HeaderWithBackButton is responsible for rendering the back button on the header. The specific behavior when the back button is pressed (such as closing the panel or switching tabs) is not detailed here, which suggests that the logic is defined elsewhere, possibly in a parent component or within the HeaderWithBackButton's implementation itself.

	<HeaderWithBackButton title={props.translate('sidebarScreen.fabNewChat')} />


OnyxTabNavigator:  The OnyxTabNavigator manages the tab navigation. It includes a custom tabBar prop that uses TabSelector. If the logic associated with the back button is tied into the tab navigator’s state, it might be causing the incorrect navigation.

	<OnyxTabNavigator
    id={CONST.TAB.NEW_CHAT_TAB_ID}
    tabBar={({state, navigation, position}) => (
        <TabSelector
            state={state}
            navigation={navigation}
            position={position}
        />
    )}
>
    <TopTab.Screen
        name={CONST.TAB.NEW_CHAT}
        component={NewChatPage}
    />
    <TopTab.Screen
        name={CONST.TAB.NEW_ROOM}
        component={WorkspaceNewRoomPage}
    />
</OnyxTabNavigator>

**What changes do you think we should make in order to solve the problem?**

Review and Update HeaderWithBackButton Logic:
Investigate the implementation of the HeaderWithBackButton. Ensure that the back button is configured to close the Right Hand Panel (RHP) and return to the Left Hand Navigation (LHN) instead of switching tabs.
If necessary, update the onPress handler to explicitly define the desired navigation action. 

Adjust Navigation State Management in OnyxTabNavigator:
Review how OnyxTabNavigator manages the navigation state, especially in relation to the back button actions. Ensure that the tab navigator's state management doesn't override or conflict with the back button's intended functionality.

**Comment by bernhardoj** [comment] 2024-01-25 15:35
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
Pressing back in start chat page goes to the previous tab.

### What is the root cause of that problem?
The back button will call `Navigation.goBack()` which will call `navigationRef.current.goBack()`.
https://github.com/Expensify/App/blob/83a7535cf5b691fc8965607327d651d10a283bd8/src/components/HeaderWithBackButton/index.tsx#L27

`navigationRef` is the ref of the root NavigationContainer
https://github.com/Expensify/App/blob/83a7535cf5b691fc8965607327d651d10a283bd8/src/libs/Navigation/NavigationRoot.tsx#L96-L100

and when we call `goBack` on it, it will pop the navigation history one by one including the tab history.

### What changes do you think we should make in order to solve the problem?

Use `useNavigation` hook to get the navigation object that "belongs" to the Start Chat stack and call goBack using the navigation object. This way, it will pop the Start Chat from the stack.

```
const navigation = useNavigation();

<HeaderWithBackButton title={props.translate('sidebarScreen.fabNewChat')} onBackButtonPress={() => navigation.goBack()} />
```

**Comment by adarsh0raj** [comment] 2024-01-25 16:38
### Proposal

#### Please re-state the problem that we are trying to solve in this issue.
After selecting 'Room' Tab in Right Hand Panel, and then clicking on Back Button, the user is redirected to 'Chat' Tab. The ideal behaviour should be closing the Right Hand Panel and going back to LHN.

#### What is the root cause of that problem?

The root cause is not passing an updated prop value for the function 'onBackButtonPress()', in the component HeaderWithBackButton. This leads to its default behaviour.

Integration of Component:
https://github.com/Expensify/App/blob/83a7535cf5b691fc8965607327d651d10a283bd8/src/pages/NewChatSelectorPage.js#L36

The default behaviour of 'onBackButtonPress()' function defined in the component is to call 'Navigation.goBack(ROUTES.Home)', as can be seen in the following line. The goBack() function is implemented in 'libs/Navigation' in such a way that it takes multiple arguments, in which one argument is "shouldPopToTop" which is "false" by default. Hence, when we are calling the goBack function it is not going to LHN, as we are not passing the "shouldPopToTop" param as true in the default function above.

https://github.com/Expensify/App/blob/83a7535cf5b691fc8965607327d651d10a283bd8/src/components/HeaderWithBackButton/index.tsx#L27

![image](https://github.com/Expensify/App/assets/58843763/9b055d8d-4955-4d32-8143-f116abe3c882)


#### What changes do you think we should make in order to solve the problem?

We can update the 'onBackButtonPress()' in the call as below, after importing Navigation from libs in 'NewChatSelectorPage'. Or passing True for 'shouldPopToTop' which will take the user directly to LHN.
```
<HeaderWithBackButton 
      title={props.translate('sidebarScreen.fabNewChat')} 
      // First Option:    onBackButtonPress={Navigation.dismissModal} 
      // Second Option:    onBackButtonPress={Navigation.goBack(ROUTES.HOME, false, true)}
/>
```

---

**Comment by adarsh0raj** [comment] 2024-01-25 16:48
Contributor details
Your Expensify account email: testadarsh72@gmail.com
Upwork Profile Link: https://www.upwork.com/freelancers/~01e6080583f375d0d1

**Comment by situchan** [comment] 2024-01-25 16:51
Search page is moved to LHP so New chat page can no longer be compared to Search page for consistency check.

**Comment by situchan** [comment] 2024-01-29 15:08
Personally I am looking for solution to skip tab navigation default behavior on navigation back. So as if there were not tab navigator.

**Comment by bernhardoj** [comment] 2024-01-30 03:07
> Personally I am looking for solution to skip tab navigation default behavior on navigation back

My proposal did this.

**Comment by situchan** [comment] 2024-02-01 13:14
@bernhardoj's [proposal](https://github.com/Expensify/App/issues/35143#issuecomment-1910453748) looks good to me.
Other proposals cause regression of closing all RHP modals (i.e. Cmd+Shift+K on Settings page)

🎀 👀 🎀 C+ reviewed

**Comment by bernhardoj** [comment] 2024-02-01 16:12
PR is ready

cc: @situchan

**Comment by Beamanator** [comment] 2024-02-09 15:36
PR still in progress

**Comment by situchan** [comment] 2024-02-15 22:42
Same

**Comment by zanyrenney** [comment] 2024-02-16 15:47
what's the ETA on the PR @Beamanator ?

**Comment by Beamanator** [comment] 2024-02-17 06:14
As you can see in [the PR](https://github.com/Expensify/App/pull/35568#issuecomment-1949765958) linked a bit above, I just bumped @situchan for another review

**Comment by situchan** [comment] 2024-02-26 15:24
PR was merged

**Comment by zanyrenney** [comment] 2024-03-04 13:44
PR was merged and deployed to prod5 days ago, waiting the 7 day period and then will do payments.

**Comment by zanyrenney** [comment] 2024-03-06 15:27
**Payment summary**
@bernhardoj $500 PAID on upwork
@situchan $500 PAID on upwork

**Closed by zanyrenney** 2024-03-06 15:27 UTC
Labels: Reviewing, External, Daily, Bug
