### ISSUE TITLE
[$1000] App does not display error message for invalid email format when creating new contact method

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#21230] opened 2023-06-21 17:11 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Navigate to the Settings menu.
2. Select the Profile option and then go to Contact Methods.
3. Click on Create New Contact Method and enter an invalid email address such as "[Hello@gmail.com.com](mailto:Hello@gmail.com.com)". Note that no relevant error message is displayed.

## Expected Result:
The app should display an error message when an invalid email format is entered in the contact methods.

## Actual Result:
he app does not display an error message for the user to enter a relevant email address when an invalid email format is entered to create a new contact method (such as "[Hello@gmail.com.com](mailto:Hello@gmail.com.com)").

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [x] MacOS / Chrome / Safari
- [x] MacOS / Desktop

**Version Number:** 1.3.27-6

**Reproducible in staging?:** y

**Reproducible in production?:** y

**If this was caught during regression testing, add the test name, ID and link from TestRail:**

**Email or phone of affected tester (no customers):**

**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Notes/Photos/Videos:** Any additional supporting documentation

[screen-capture (98).webm](https://github.com/Expensify/App/assets/93399543/e12f3914-33d6-40fb-8cc0-331dc3df0b0f)

https://github.com/Expensify/App/assets/93399543/f9c37ae0-1c5a-42cc-8e10-777deaafd993

**Expensify/Expensify Issue URL:**

**Issue reported by:** @tewodrosGirmaA

**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1686755183045119

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01686595e7adb44dfc</li>
        <li>Upwork Job ID: 1673481379174330368</li>
        <li>Last Price Increase: 2023-06-27</li>
    </ul>
</details>

**Comment by tewodrosGirmaA** [comment] 2023-06-21 17:48
It is not possible for an email address to have two ".com" domains. An email address can only have one domain extension, such as ".com", ".org", or ".net".

**Comment by slafortune** [comment] 2023-06-27 00:00
Looks like this is still an issue - 
<img width="754" alt="image" src="https://github.com/Expensify/App/assets/11725910/1e58d2da-6829-47aa-a2e2-44c342dcd925">

**Comment by tewodrosGirmaA** [comment] 2023-06-27 07:15
Hello @tienifr @getusha, I did not receive an error message for the email address "--------@----------.com" also. Can you please perform one final check? what is your thought on this

**Comment by tewodrosGirmaA** [comment] 2023-06-27 07:17
![image](https://github.com/Expensify/App/assets/118253010/6553a7ce-3bdc-4afd-aceb-5e8f8afb834d)

**Comment by BeeMargarida** [comment] 2023-06-27 09:52
Isn't this issue a duplicate of https://github.com/Expensify/App/issues/17387?

**Comment by Piotrfj** [comment] 2023-06-29 13:09
Is this issue a duplicate or is it open for a solution?

**Comment by MitchExpensify** [comment] 2023-07-01 22:40
This looks like a dupe of https://github.com/Expensify/App/issues/17387, closing!

**Closed by MitchExpensify** 2023-07-01 22:40 UTC
Labels: External, Daily, Help Wanted, Overdue, Bug
