### ISSUE TITLE
[HOLD for payment 2023-10-13] [HOLD for payment 2023-10-12] [$500] Contact Method - Reloading the page does not clear the error on Contact Methods

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#28825] opened 2023-10-04 15:20 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Go to settings> profile > contact method
2. Click on Add contact method > Add a new contact method
3. Click on this contact method to verify
4. Enter a random magic code to make the error appear
5. Reload the page and notice the error

## Expected Result:
Reloading the page clears the error

## Actual Result:
Reloading the page does not clear the error

## Workaround:
Unknown 

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native -missing
- [x] Android / Chrome 
- [x] iOS / native
- [x] iOS / Safari
- [x] MacOS / Chrome / Safari
- [x] MacOS / Desktop

**Version Number:** v1.3.77-5
**Reproducible in staging?:** y
**Reproducible in production?:** n
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/93399543/8662fe01-2d80-4c4b-896d-b3fac4147b6c

https://github.com/Expensify/App/assets/93399543/58dd1f11-a989-4e87-8d1d-e1b8fdcd7259

https://github.com/Expensify/App/assets/93399543/298c69fc-2f27-4dfa-8ea9-f38be2c144f9

https://github.com/Expensify/App/assets/93399543/4f621422-af40-49e6-bd8c-4cef938bbd87

https://github.com/Expensify/App/assets/93399543/8d949dd6-370b-4ab2-a65c-fd0d43e1f094

**Expensify/Expensify Issue URL:**
**Issue reported by:** @daveSeife
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1696430803154119

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01a03426ab964ebd8c</li>
        <li>Upwork Job ID: 1709601906373169152</li>
        <li>Last Price Increase: 2023-10-04</li>
<li>Automatic offers: </li>
<ul>
<li>s77rt | Contributor | 27025964</li>
<li>daveSeife | Reporter | 27025966</li>
</ul></li>
    </ul>
</details>

**Comment by mountiny** [comment] 2023-10-04 16:13
I dont think this is a blocker, curious if this is even a bug as the error is probably saved in onyx so you need to clear it with the X button and not with refresh. Same as if you get error when sending a message you need to clear the error with X

I am going to close this now thinking about it more, feel free to reopen if you disagree

**Comment by s77rt** [comment] 2023-10-04 18:46
@namhihi237 Thanks for the proposal. I agree that we should not mutate the `persistedRequests` array. But in your solution you are still mutation that array. How is this supposed to work?

**Comment by s77rt** [comment] 2023-10-04 18:48
@namhihi237 I understand that we may be dealing with a race condition here, but did you find an explanation on what's going on exactly with the array as even we are mutating the object we are updating Onyx with the expected data.

**Comment by s77rt** [comment] 2023-10-04 18:49
@namhihi237 I see 

```js
persistedRequests = requests;
```

**Comment by s77rt** [comment] 2023-10-04 19:35
@namhihi237 I can't validate your RCA. Your solution still mutates the array. Did you manage to get it working that way?

**Comment by s77rt** [comment] 2023-10-04 19:49
@namhihi237 We should not reassign the array at any point

```js
    const requests = [...persistedRequests];
    requests.splice(index, 1);
    Onyx.set(ONYXKEYS.PERSISTED_REQUESTS, requests);
```

**Comment by s77rt** [comment] 2023-10-04 19:53
I confirm that calling splice on the global object `persistedRequests` is the root cause here. I guess we are accessing the request from somewhere else and unexpectedly delete it. As this is a deploy blocker I think we have enough info.

@namhihi237 Please raise a PR fixing the bug for all the `PersistedRequests` methods

**Comment by s77rt** [comment] 2023-10-04 19:59
@namhihi237 No we don't. That variable is supposed to be read-only. It's only written by Onyx thought the onyx connector.

**Comment by mountiny** [comment] 2023-10-04 20:12
Thanks for nailing this down cc @roryabraham for visibility

**Comment by mountiny** [comment] 2023-10-04 22:23
Fixed https://expensify.slack.com/archives/C9YU7BX5M/p1696456883868739

**Comment by s77rt** [comment] 2023-10-06 01:16
- The PR that introduced the bug has been identified: https://github.com/Expensify/App/pull/27996
- The offending PR has been commented on: https://github.com/Expensify/App/pull/27996#discussion_r1348149431
- A discussion in #expensify-bugs has been started: Not needed
- Determine if we should create a regression test for this bug: No

**Comment by s77rt** [comment] 2023-10-06 16:31
Checklist provided already https://github.com/Expensify/App/issues/28825#issuecomment-1749859344

**Comment by Christinadobrzyn** [comment] 2023-10-11 20:11
still a few more days before payment. 

Payouts due:

Issue Reporter: $50 @daveSeife (in Upwork)
Contributor: $500 + $250 bonus @namhihi237 (in Upwork)
Contributor+: $500 + $250 bonus @s77rt (in Upwork)

Eligible for 50% #urgency bonus? Yes - PR created Oct 4th - merged Oct 4th @s77rt @mountiny is that correct?

Upwork job is [here](https://www.upwork.com/jobs/~01a03426ab964ebd8c).

**Comment by s77rt** [comment] 2023-10-11 20:51
No payment due for me here since it's a regression from a [PR](https://github.com/Expensify/App/pull/27996) I reviewed

**Comment by Christinadobrzyn** [comment] 2023-10-13 22:04
Alright, paid based on https://github.com/Expensify/App/issues/28825#issuecomment-1758460835

Closing!

**Closed by Christinadobrzyn** 2023-10-13 22:04 UTC
Labels: External, Engineering, Daily, Overdue, Awaiting Payment, Bug
