### ISSUE TITLE
[HOLD for payment 2024-06-20] [$250] [Violations] Tags - Violation for unselected dependent tags displays tag name briefly then changes to "tag"

### ISSUE THREAD

**Issue by izarutskaya** [Expensify/App#38095] opened 2024-03-11 21:20 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.50-0
**Reproducible in staging?:** Y
**Reproducible in production?:** N
**Issue reported by:** Applause-Internal team
**Workspace ID**:  34D57014C907E72E
**Transaction thread reportID**: 2426939351372174
**Transaction ID**: 7718685459543892670

## Action Performed:
Precondition:
- User is an employee of Collect workspace.
- The Collect workspace has multilevel dependent tags.

1. Go to staging.new.expensify.com
2. Go to workspace chat.
3. Create a manual request without tags.
4. Go to request details page immediately after the request is created.

## Expected Result:
The violation for unselected tags will display "missing tagname".

## Actual Result:
The violation for unselected tags displays "missing tagname" briefly, then changes to "missing tag".

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [x] Android: mWeb Chrome
- [x] iOS: Native
- [x] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

https://github.com/Expensify/App/assets/115492554/c6567bd7-49a2-4662-b00e-34862b4e4314

[Dependent - Multi Level tags NEW.csv](https://github.com/Expensify/App/files/14564633/Dependent.-.Multi.Level.tags.NEW.csv)

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01f0cc71bb900348ff</li>
        <li>Upwork Job ID: 1769788312802717696</li>
        <li>Last Price Increase: 2024-05-23</li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @isabelastisser</details>

**Comment by izarutskaya** [comment] 2024-03-11 21:25
@stitesExpensify I haven't added the External label as I wasn't 100% sure about this issue. Please take a look and add the label if you agree it's a bug and can be handled by external contributors.

**Comment by izarutskaya** [comment] 2024-03-11 21:25
We think that this bug might be related to #wave6-collect-submitters
CC @greg-schroeder

**Comment by izarutskaya** [comment] 2024-03-11 21:27
Production video 

https://github.com/Expensify/App/assets/115492554/6c85c4c1-859e-437a-8c80-e623807d955a

**Comment by luacmartins** [comment] 2024-03-11 21:34
Demoting to NAB since it involves violations

**Comment by shahinyan11** [comment] 2024-03-12 11:58
@izarutskaya  Can you please help me to done following `Create Collect workspace which has multilevel dependent tags.` . I don't know which workspace is called Collect and how to create it.

**Comment by isabelastisser** [comment] 2024-03-19 19:42
Waiting for proposals.

**Comment by isabelastisser** [comment] 2024-03-28 19:29
Waiting for proposals.

**Comment by isabelastisser** [comment] 2024-04-02 01:29
Added to wave-collect, due on May 1st.

**Comment by mvtglobally** [comment] 2024-04-04 03:24
Issue not reproducible during KI retests. (First week)

**Comment by isabelastisser** [comment] 2024-04-04 13:43
Not overdue.

**Comment by pac-guerreiro** [comment] 2024-04-09 17:20
@izarutskaya I'm not able to create a collect workspace that behaves exactly as described here. I'm uploading the CSV you provided through expensify classic and then I'm setting the tags as required, but they never show as required in the money request. I also don't understand how to enable violations which seems to be related to betas. @luacmartins maybe you can help me with this 😄

**Comment by stitesExpensify** [comment] 2024-04-11 20:15
@luacmartins is there a beta that I need to put @pac-guerreiro on?

**Comment by luacmartins** [comment] 2024-04-11 20:33
I think we still have the `violations` beta, @cead22 would be able to confirm

**Comment by cead22** [comment] 2024-04-12 20:31
Yes, you can look for it in the code and you'll see we still have code wrapped in `if (isInbeta(violations)) { ... }`

**Comment by isabelastisser** [comment] 2024-04-15 14:16
Not overdue.

**Comment by cead22** [comment] 2024-04-15 16:46
This isn't a bug as much as something we haven't yet implemented, which is the missing tag violation for the case of dependent multi-level tags.

For this case, we seem to calculate a `missing tag` violation, and because there are multiple tags, returning `tagName => $tagName` like we do for other cases won't work here, because we'll only have 1 missing tag violation, but we have more than one tag.

I think we need to do the following
1. Implement a method that returns true when a workspace has dependent multi level tags, if we don't have it already
2. Update MoneyRequestView to pass the tagListName and/or tagListIndex to `getViolationsForField` for each of the dependent tags
3. Update `getViolationsForField` to include a `tagName` key in the returned violation's `data` object, similar to what we do for `someTagLevelsRequired` in there
4. `getViolationTranslation` should work as is because the case for `missingTag` already passes `{tagName}` to `translate`

@stitesExpensify I'll steal this one since I'm familiar with it

**Comment by cead22** [comment] 2024-04-15 23:51
@pac-guerreiro you can use this file [dependent_tags.csv](https://github.com/Expensify/App/files/14985164/dependent_tags.csv). If you have any questions, feel free to post them here, or ping me in #expensify-open-source or new dot

**Comment by pac-guerreiro** [comment] 2024-04-16 19:33
@cead22 

So since I'm not a part of violations beta, I forced the flag to be true in my local environment. Then I tried to reproduce the issue but I wasn't able to (maybe it was fixed by some PR).

I did notice though that before I create the money request, no tag shows as required, as you can see below:

https://github.com/Expensify/App/assets/48553277/40510f24-e287-40bc-8247-0181c7b750fc

Also I'm able to pick any combination of tags although I uploaded your CSV which includes dependent tags. 

I already reported my findings on an ongoing discussion about multi level tags - https://expensify.slack.com/archives/C01GTK53T8Q/p1713295658981909?thread_ts=1708732718.173419&cid=C01GTK53T8Q

**Comment by cead22** [comment] 2024-04-16 20:44
It looks like you setup the tags as independent tags, and they need to be dependent. Make sure the checkbox `Are these independent tags?` is unchecked
<img width="654" alt="image" src="https://github.com/Expensify/App/assets/165133/35a7c28a-40b4-4db0-96fe-6d79e65a6cb3">


It'd be helpful if you can share the policy's `tagLists` property. I added pedro.guerreiro@callstack.com to the violations beta

**Comment by pac-guerreiro** [comment] 2024-04-17 17:18
These are the tags list that the BE is returning:

![Screenshot 2024-04-17 at 18 17 52](https://github.com/Expensify/App/assets/48553277/8fdb69e8-78fd-4fdf-b20a-abf6759e655c)

**Comment by pac-guerreiro** [comment] 2024-04-17 17:48
@cead22 

This change seems to do the trick:

![Screenshot 2024-04-17 at 18 47 57](https://github.com/Expensify/App/assets/48553277/1063eb0f-03a4-4f4a-9b04-abb7866d79dc)

**Comment by cead22** [comment] 2024-04-17 20:10
Yeah but that's not what we want, since that case is for independent tags and should be working fine (let me know if it isn't).

I invited pedro.guerreiro@callstack.com to a workspace that's setup with dependent tags, and that is showing for me as an option to request money from in new dot. The workspace is `carlos control (dependent tags)` with ID `1089C3C9478BF694`

Let me know if you can reproduce using that workspace

**Comment by pac-guerreiro** [comment] 2024-04-19 16:35
@cead22

Thank you for the invite! I was able to reproduce the issue 😄

**Comment by cead22** [comment] 2024-04-23 00:44
@pac-guerreiro how progress looking on this one?

**Comment by pac-guerreiro** [comment] 2024-04-23 02:37
@cead22 

[Draft PR](https://github.com/Expensify/App/pull/40741) is now available with a possible fix for this! 

Let me know if you encounter any problems 😄

**Comment by isabelastisser** [comment] 2024-04-26 13:47
Not overdue.

**Comment by isabelastisser** [comment] 2024-04-29 18:25
@pac-guerreiro and @abdulrahuman5196, please provide an update. Thanks!

**Comment by abdulrahuman5196** [comment] 2024-05-01 14:00
@isabelastisser I think the PR is in draft state.

@pac-guerreiro Can you set the PR ready for review when its available to review?

**Comment by pac-guerreiro** [comment] 2024-05-03 09:26
@abdulrahuman5196 

Yes I can! 😄

**Comment by cead22** [comment] 2024-05-06 22:25
PR is a WIP

**Comment by isabelastisser** [comment] 2024-05-09 20:49
not overdue.

**Comment by abdulrahuman5196** [comment] 2024-05-22 20:15
Hi, Sorry. I am bit occupied at the moment. Unassigning myself to avoid further delays. Kindly re-apply the bug label for a different C+.

**Comment by isabelastisser** [comment] 2024-05-23 18:39
Hey @hoangzinh, can you do the PR review for this issue before the end of this week? Thanks!

**Comment by isabelastisser** [comment] 2024-06-20 19:27
@hoangzinh, can you please complete the BZ list? Thanks!

ROLE: @hoangzinh paid $250 Contributor role
Contributor: @pac-guerreiro is from an agency-contributor and not due payment

**Comment by cead22** [comment] 2024-06-21 22:55
That looks good to me. I had written a similar testing script, which I think is a bit more comprehensive, what do you think

- In old dot, in the workspace editor > tags tab, switch on the Use multiple levels of tags and the People must tag expenses toggles
- Click import from spreadsheet, uncheck “Are these independent tags?”, and upload the file in [this issue comment](https://github.com/Expensify/App/issues/37117#issuecomment-2177239758)
- On new dot, press big plus sign > submit expense
- Select Manual tab (from Manual | Scan | Distance)
- Enter $15 as the amount amount and press next
- Press the workspace from the pre-testing steps (press the row, not the split button in the row)
- Press the merchant row and enter a merchant
    - Confirm the Required label shows on the State, Region, and City rows
- Press the Submit $15 button
    - Confirm the report preview has a red circle
- Press the report preview
- If the report has more than 1 expense
    - Confirm the money request preview has a red circle and shows “Review Required”
- Press the money request preview
    - Verify you see Missing State, Missing Region, and Missing City violations
- Press the Region menu item, and select a region
    - Verify that the Missing Region violation disappears right away
    - Verify you see All tags required violations under State and City
- Select a State
    - Verify that the see All tags required violation disappears from under State
    - Verify you see All tags required violations under City
- Select a City
    - Verify that the see All tags required violations are gone
- De-select City
    - Verify that the All tags required violation appears under City
- 🛜Switch to new dot and go offline
- Repeat steps 1-16. The report preview, money request preview should be grayed out
- Go online, and confirm everything looks the same, except nothing is grayed out
- Submit a new expense on the same workspace, and select all the required fields so there are no violation on that expense
- Click on the link in the transaction thread header to go back to the expense report if you didn’t land there already
    - Verify the money request preview for the first expense says Review Required next to the a red circle

**Comment by isabelastisser** [comment] 2024-06-22 01:01
All set! Thanks, team!

**Closed by isabelastisser** 2024-06-22 01:01 UTC
Labels: External, Engineering, Daily, Awaiting Payment, Bug
