### ISSUE TITLE
[$500] Chat - Emoji search is not in focus when tapping on emoji icon

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#27715] opened 2023-09-18 21:01 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___
**Issue found when executing PR** https://github.com/Expensify/App/pull/27340
## Action Performed:
1. Open ND and log in with any account
2. Open any chat
3. Click on emoji symbol button in composer or context menu

## Expected Result:
Search input is focused

## Actual Result:
Search input is not focused on mWeb Safari. It's in focus on Chrome on Android

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [x] Android / Chrome
- [ ] iOS / native
- [x] iOS / Safari
- [ ] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 1.3.71-5

**Reproducible in staging?:** Yes

**Reproducible in production?:** Yes

**If this was caught during regression testing, add the test name, ID and link from TestRail:**

**Email or phone of affected tester (no customers):**

**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/78819774/f120aacd-8bff-4bda-8c9d-87c1fbf0fd39

**Expensify/Expensify Issue URL:**

**Issue reported by:** Applause - Internal Team

**Slack conversation:**

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~010738eb289b561032</li>
        <li>Upwork Job ID: 1704746351026159616</li>
        <li>Last Price Increase: 2023-09-21</li>
    </ul>
</details>

**Comment by kevinksullivan** [comment] 2023-09-21 06:36
reproduced and moving forward

**Comment by Talha345** [comment] 2023-09-21 20:59
I am unable to reproduce as per the mentioned steps in the issue! It also seems to be working fine in the attached video.
@kevinksullivan can you please clarify what is the issue?

**Comment by kevinksullivan** [comment] 2023-09-27 04:28
Ok, closing till we can reproduce

**Closed by kevinksullivan** 2023-09-27 04:28 UTC
Labels: External, Daily, Help Wanted, Overdue, Bug
