### ISSUE TITLE
[$500] "Unavailable workspace" appears when adding a member to a workspace

### ISSUE THREAD

**Issue by m-natarajan** [Expensify/App#33560] opened 2023-12-24 19:30 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.16-3
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** @puneetlath 
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1703014430002699

## Action Performed:
1. Login  as account B in NewDot
2. Login as account A in OldDot
3. Add account B as member

## Expected Result:
In the LHN workspace name should appear

## Actual Result:
showed up in my LHN as “unavailable workspace”. Seems we are not sending the workspace info along with the pusher event that is sending the new room.

## Workaround:
unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

![image](https://github.com/Expensify/App/assets/38435837/f9f389a2-a340-4e9c-90a5-f8293a77b952)

https://github.com/Expensify/App/assets/38435837/e0cd99e5-0d77-4b88-91ef-49a6cbc4b148

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01488edc00fcf10453</li>
        <li>Upwork Job ID: 1739005691185319936</li>
        <li>Last Price Increase: 2024-01-14</li>
    </ul>
</details>

**Comment by Famzy-codes** [comment] 2023-12-24 19:53
Dear **Expensify Team**,

I've thoroughly reviewed the technical details concerning the issue reported by @puneetlath regarding the missing display of workspace names in the LHN (Left Hand Navigation) within Expensify. This discrepancy occurs when adding account B as a member, resulting in the workspace name appearing as "unavailable workspace" instead of the expected display.

**Summary of the Problem:**

1. **Issue Reproduction:**
   - Confirmed reproducibility in both staging and production environments (version 1.4.16-3).
   - Observed the discrepancy when adding account B as a member within the NewDot and OldDot interfaces.

2. **Expected vs. Actual Behavior:**
   - Expected: The workspace name should be prominently displayed in the LHN.
   - Actual: The workspace name appears as "unavailable workspace," indicating a failure in transmitting the workspace information with the pusher event related to new room creation.

**Technical Analysis and Proposed Solution:**

- The investigation revealed a gap in transmitting workspace details during the pusher event associated with room creation, leading to an absence of workspace name display in the LHN.
- Proposed Resolution:
  - Analyze and update the code logic responsible for sending pusher events to include accurate workspace information.
  - Verify that the workspace details are being correctly retrieved and transmitted during the account member addition process.
  - Conduct comprehensive testing to ensure the proper display of workspace names in the LHN across supported platforms (MacOS: Chrome / Safari).

**Action Plan:**

1. **Code Review and Debugging:**
   - Review the pusher event handling code segments.
   - Debug the code to trace the transmission of workspace details during room creation and account member addition.

2. **Code Modification and Testing:**
   - Implement necessary code changes to include accurate workspace information in pusher events.
   - Thoroughly test the updated functionality to ensure the correct display of workspace names in the LHN.

3. **Quality Assurance and Release:**
   - Perform rigorous testing across staging and production environments.
   - Validate the fix's effectiveness without introducing new issues.
   - Document the resolution process and coordinate the deployment of the updated version.

I am ready to delve into the intricacies of the codebase and swiftly resolve this issue, ensuring the seamless display of workspace names as expected in the LHN.

Looking forward to contributing to Expensify's commitment to delivering top-notch user experiences.

Best regards,
Favour codes.

**Comment by mananjadhav** [comment] 2023-12-28 16:58
I haven't been reliably able to reproduce this. We're still waiting for any good proposal.

@Famzy-codes Thanks for the interest. The proposal has to highlight the specific root cause and how you plan to fix it. Please check the previously worked issues to get a sense on the quality of proposals.

**Comment by anmurali** [comment] 2024-01-02 22:54
Lets see if we get any proposals for this in the new year and if not, I can bump up to $1000 next week.

**Comment by Famzy-codes** [comment] 2024-01-04 21:26
@anmurali is the website on WordPress or what type of hosting

**Comment by anmurali** [comment] 2024-01-10 00:38
The reproduction steps are not super clear, I am asking on Slack to clarify and then I will try again and close if this is no longer reproducible.

**Comment by anmurali** [comment] 2024-01-16 19:36
So turns out we do not pull in Collect workspaces into ND and that's what is causing this and it is (thus far) by design. So closing this bug report.

**Comment by puneetlath** [comment] 2024-01-18 14:01
Let's reopen this. Everyone in the company is experiencing this with inviting them to the NewDot test workspace and we better know how to reproduce it now. Plus it'll potentially start to affect real users as we start the migration.

**Comment by jasperhuangg** [comment] 2024-01-22 16:43
Taking a look at the fix for this one today!

**Comment by mananjadhav** [comment] 2024-01-29 00:41
@jasperhuangg I can see a linked PR with a comment change. Is it related to the expected behavior?

**Comment by jasperhuangg** [comment] 2024-01-29 23:41
@mananjadhav yep, we should be good to close this out!

**Closed by jasperhuangg** 2024-01-29 23:41 UTC
Labels: Reviewing, Engineering, Weekly, Internal, Bug
