### ISSUE TITLE
Collect admin - New invited user appears four times in workspace chat member list

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#35407] opened 2024-01-30 14:52 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.33-4
**Reproducible in staging?:** Y
**Reproducible in production?:** N
**If this was caught during regression testing, add the test name, ID and link from TestRail:** https://expensify.testrail.io/index.php?/tests/view/4254707
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** Applause - Internal Team
**Slack conversation:**

## Action Performed:
1. On Old Dot, create a Collect workspace and add this snippet to console.

```javascript
if (Url.getCurrentPageName()!="policy" ){ alert('Only run this snippet from a policy editor!'); } else { var p = Policy.getCurrent(); p.policy.isPolicyExpenseChatEnabled = "true"; p.save().done(function(){$.jGrowl('Workspace chat creation enabled!')}); }
```

2. Log in to New Dot (log out and log in again if logged in to see the Collect workspace in New Dot settings).
3. Go to Settings > Workspaces > Collect workspace > Members
4. Invite a new member who is not registered on New Dot
5. Go to workspace chat with the new member
6. Click on the chat header
7. Click Members

## Expected Result:
The new member only appears one time in the member list

## Actual Result:
The new member appears four times in the member list

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [x] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details> 

https://github.com/Expensify/App/assets/78819774/fc1057bd-4105-45b9-b2e9-b11ce4a5aca5

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by lanitochka17** [comment] 2024-01-30 14:53
We think that this bug might be related to #wave8. 
CC @zanyrenney

**Comment by arosiclair** [comment] 2024-01-30 16:15
Tried twice with private (expensifail.com) and public (gmail.com) domains and did not reproduce.

https://github.com/Expensify/App/assets/6833644/11d557b1-4835-47ff-a592-e795b80a71b4

Closing this out

**Comment by francoisl** [comment] 2024-01-30 20:47
Hmm yeah I can't repro either. The workspace chat doesn't appear unread in my LHN after inviting the user though, but I think that's from a different issue.

https://github.com/Expensify/App/assets/2229301/548f875f-ca02-4513-9970-8d10fb4d20d3

Looks like it _might_ be an issue with optimistic data and the members list is correct once the API returns the updated chat members list? Either way, doesn't look like it's blocking any major workflow so we can remove the label for now.

**Comment by arosiclair** [comment] 2024-01-30 20:54
@kbecciv @lanitochka17 there seems to be something missing from the reproduction steps. Please update them otherwise we'll just close this as it is not reproducible currently.

**Comment by arosiclair** [comment] 2024-02-02 20:37
No update. Closing this out again

**Closed by arosiclair** 2024-02-02 20:37 UTC
Labels: Engineering, Daily, Overdue
