### ISSUE TITLE
Dev: Clicking on user detail page throws the 2 console error

### ISSUE THREAD

**Issue by kavimuru** [Expensify/App#23208] opened 2023-07-19 22:14 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Login to ND
2. Navigate to any conversation
3. Press on any receiver name to open their user detail page
4. Notice on console we are getting 2 errors
## Expected Result: 
no console error should appear
## Actual Result: 
console error appears

## Workaround:
Can the user still use Expensify without this being fixed? Have you informed them of the workaround?

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [x] MacOS / Chrome / Safari
- [x] MacOS / Desktop

**Version Number:** Dev
**Reproducible in staging?:** dev
**Reproducible in production?:** dev
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation
![Screenshot 2023-07-18 at 7 11 54 AM](https://github.com/Expensify/App/assets/43996225/4f73a5c1-15a7-4bb6-aa32-82660562885c)
![Screenshot 2023-07-18 at 7 11 41 AM](https://github.com/Expensify/App/assets/43996225/7e48c447-1fd9-40eb-b1aa-78b341be7388)

**Expensify/Expensify Issue URL:**
**Issue reported by:** @dhairyasenjaliya 
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1689644468877559

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by MitchExpensify** [comment] 2023-07-20 21:06
What exactly are you clicking when you say "Press on any receiver name"? I'm unable to reproduce this so far

**Comment by Santhosh-Sellavel** [comment] 2023-07-20 21:16
@MitchExpensify this is a dupe of #23201

**Comment by MitchExpensify** [comment] 2023-07-20 22:12
Ah cool, typically I try to reproduce before scouring for dupes! Thanks for the assist @Santhosh-Sellavel & @dhairyasenjaliya  🙇

**Closed by MitchExpensify** 2023-07-20 22:12 UTC
Labels: Daily, Needs Reproduction, Bug
