### ISSUE TITLE
[$500] Report - A tooltip does not appear above the mentioned user with no conversation history

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#35554] opened 2024-02-01 14:10 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.35-0
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**If this was caught during regression testing, add the test name, ID and link from TestRail:** https://expensify.testrail.io/index.php?/tests/view/4257564
**Email or phone of affected tester (no customers):** sustinov@applausemail.com
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** Applause - Internal Team
**Slack conversation:**

## Action Performed:
1. Open https://staging.new.expensify.com/
2. Log in under your HT account
3. Navigate to any conversation
4. Paste the text "@[unexistingperson@gmail.com"](mailto:unexistingperson@gmail.com%22)
into the Compose Box
5. Send a message
6. Hover over "@[unexistingperson@gmail.com"](mailto:unexistingperson@gmail.com%22)
in the conversation

## Expected Result:
A tooltip should appear above the mentioned user who has no conversation history

## Actual Result:
A tooltip does not appear above the mentioned user with no conversation history

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details> 

https://github.com/Expensify/App/assets/78819774/14c7a373-b021-4dde-8b32-88d57a17ac57

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~016bf9af6101d5958e</li>
        <li>Upwork Job ID: 1753058291231088640</li>
        <li>Last Price Increase: 2024-02-01</li>
<li>Automatic offers: </li>
<ul>
<li>akinwale | Reviewer | 28145420</li>
<li>FitseTLT | Contributor | 28145421</li>
</ul></li>
    </ul>
</details>

**Comment by lanitochka17** [comment] 2024-02-01 14:11
We think that this bug might be related to #vip-vsp
CC @quinthar

**Comment by FitseTLT** [comment] 2024-02-01 14:31
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
A tooltip does not appear above the mentioned user with no conversation history

### What is the root cause of that problem?
Currently if we don't have the user in personal details we display the mention without tooltip
https://github.com/Expensify/App/blob/9d4c634a87890ccbdcc2efe353ae9d929aa5530b/src/components/UserDetailsTooltip/BaseUserDetailsTooltip/index.tsx#L88-L89
### What changes do you think we should make in order to solve the problem?

We are already passing the login in `fallbackUserDetails` so we can use it to be `title` and `subtitle` of the tooltip here
https://github.com/Expensify/App/blob/9d4c634a87890ccbdcc2efe353ae9d929aa5530b/src/components/UserDetailsTooltip/BaseUserDetailsTooltip/index.tsx#L39-L41
and change the current display logic to display with tooltip when there is `fallbackUserDetails`
https://github.com/Expensify/App/blob/9d4c634a87890ccbdcc2efe353ae9d929aa5530b/src/components/UserDetailsTooltip/BaseUserDetailsTooltip/index.tsx#L88-L89

### What alternative solutions did you explore? (Optional)

**Comment by garrettmknight** [comment] 2024-02-05 16:37
@akinwale can you review these proposals please?

**Comment by akinwale** [comment] 2024-02-06 08:38
The suggested approaches are valid in both proposals are valid. We can move forward with @FitseTLT's proposal since it was first chronologically.

@FitseTLT While this is not an issue here, please always follow the contributing guidelines by posting an Updated post after making a significant edit to your proposal, even if there are no other proposals at the time.

🎀👀🎀 C+ reviewed.

**Comment by Julesssss** [comment] 2024-02-06 09:45
I agree with @FitseTLT proposal being the best option here.

**Comment by Tony-MK** [comment] 2024-02-06 19:22
Hey @akinwale and @Julesssss, I am happy with the decision, but I am just curious about the downside of my proposal.

Due to the fact no feedback was provided. 

Also, congrats @FitseTLT.

Thank you

**Comment by garrettmknight** [comment] 2024-02-06 20:08
@Tony-MK we go with the first, best option. Your solution was viable, just not first.

**Comment by Tony-MK** [comment] 2024-02-06 20:10
Thanks

**Comment by Julesssss** [comment] 2024-02-07 09:56
Hi @Tony-MK it was mentioned here: 

> The suggested approaches in both proposals are valid. We can move forward with @FitseTLT's proposal **since it was first chronologically.**

**Comment by garrettmknight** [comment] 2024-02-09 18:30
@FitseTLT how's that PR coming?

**Comment by garrettmknight** [comment] 2024-02-12 15:59
Shouldn't be overdue, waiting on the PR.

**Comment by FitseTLT** [comment] 2024-02-12 18:04
PR will be ready in 2 days

**Comment by garrettmknight** [comment] 2024-02-14 19:03
@anmurali just reassigning in case this needs help while I'm OOO this week - will be back 2/21 to pick it back up.

**Comment by akinwale** [comment] 2024-03-04 12:33
Deployed to production: [2024-02-26](https://github.com/Expensify/App/pull/36584#issuecomment-1965250394)
Payment due date: 2024-03-04

cc @garrettmknight

**Comment by FitseTLT** [comment] 2024-03-11 16:10
Payment Overdue @garrettmknight @anmurali

**Comment by garrettmknight** [comment] 2024-03-13 13:56
All paid out - sorry about that!

**Closed by garrettmknight** 2024-03-13 13:56 UTC
Labels: External, Weekly, Awaiting Payment, Bug
