### ISSUE TITLE
[HOLD FOR PAYMENT - 2023-07-12] [$1000] Background hero image on Android device looks distorted

### ISSUE THREAD

**Issue by kavimuru** [Expensify/App#20829] opened 2023-06-15 14:19 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Open New Expensify and navigate to sign-in page on an Android device
2.  Observe the hero image in background
## Expected Result: 
The background image should be sharp and look exactly like on other platforms
## Actual Result: 
The background image looks distorted/blurred with some image elements incorrectly overlapped.

## Workaround:
Can the user still use Expensify without this being fixed? Have you informed them of the workaround?

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [ ] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 1.3.28-3
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation

<img src="https://github.com/Expensify/App/assets/43996225/7c6eab9e-794e-459b-8533-dbc8252f827e" width="40%" height="40%">

![image (5)](https://github.com/Expensify/App/assets/43996225/9a7984a3-6fd7-4133-8559-153ba17c0c4d)

<img src="https://github.com/Expensify/App/assets/43996225/9421aa59-b14c-4ef3-967c-e846d99e47ca" width="40%" height="40%">

**Expensify/Expensify Issue URL:**
**Issue reported by:** @aswin-s
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1686193141475819

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01fb98c0a3c23730f9</li>
        <li>Upwork Job ID: 1670909937522839552</li>
        <li>Last Price Increase: 2023-06-26</li>
    </ul>
</details>

**Comment by anmurali** [comment] 2023-06-19 21:42
Added an external label for contributors to pick up

**Comment by ayushgupta-1** [comment] 2023-06-20 20:18
Is there any animation involved in the hero image ? I believe there is some alignment issue with the android as sometimes the alignment for iOS and android are different. I can understand better if I have some idea of code used for this screen. Thanks.

**Comment by ayushgupta-1** [comment] 2023-06-20 20:58
Contributor details
Expensify account email: ayushgupta.au@gmail.com
Upwork Profile Link: https://www.upwork.com/freelancers/~011e3b0b756f8eba6a

My take on above problem : I believe the issue is being caused due to flex adjustment error of the components on the following screens as the android phones screens are taller as compared to iPhone's screen which are fatter. Hence some adjustments to the flex and alignment properties with some platform centric code should solve the issue.

**Comment by waterim** [comment] 2023-06-21 10:49
Hi!
I'm Artem from Callstack - expert contributor group
Maybe I could help with this one?

**Comment by waterim** [comment] 2023-06-22 11:00
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
Login page SVG background image on Android looks different from IOS

### What is the root cause of that problem?
The main issue here is that Android and IOS opacity works in a different manner.
IOS applying opacity from root to child correctly, but Android sometimes can apply just fill-opacity to child elements even when you are using regular "opacity".

**File we are working with**: home-background--mobile.svg

### What changes do you think we should make in order to solve the problem?
The best way to fix this issue with opacity will be to ask designers to update the file, _to avoid regressions if for some reason the design changes or the file needs to be re-downloaded_ :
**Move opacity from parent .st2 to child .st3 class.**

### What alternative solutions did you explore?
We need to apply opacity to child elements: Instead of applying the opacity directly to the <g> element. This approach can help achieve more consistent opacity rendering across platforms.

In order to achieve correct rendering only thing we need to do:
1. Remove parent opacity: 
```js
.st2{opacity:6.000000e-02;}
```
2. Update child st3 path style with opacity:
```js
.st3{fill:#FFFFFF;filter:url(#Adobe_OpacityMaskFilter); opacity:6.000000e-02;}
```

<img width="857" alt="image" src="https://github.com/Expensify/App/assets/39777589/dda7d857-5873-4e03-8964-763580965c26">

**Comment by waterim** [comment] 2023-06-26 09:23
@allroundexperts About this solution:

> The best way to fix this issue with opacity will be to ask designers to update the file, _to avoid regressions if for some reason the design changes or the file needs to be re-downloaded_ :
> **Move opacity from parent .st2 to child .st3 class.**

As I mentioned above, the best way to fix issue with SVG is to ask designers to update SVG image from the top level(during creating). 
Because with the alternative solution if for some reason the design changes or the file(SVG image) needs to be re-downloaded in the future - we need to update this opacity by hands again.

But if we are not going to update the image or its impossible to do that, then the alternative solution can help us to achieve fixed view.

Should I start with a PR for an alternative solution?

**Comment by waterim** [comment] 2023-06-26 09:28
@allroundexperts Cool, thank you, lets wait.

**Comment by shawnborton** [comment] 2023-06-26 13:28
Hmm I'm not sure how we would change this while creating the svg - basically we just export this from Figma or Illustrator. Given that the svg is really just XML code, are these changes you can make directly in the code yourself?

**Comment by waterim** [comment] 2023-06-26 13:46
@shawnborton Yes, I can make changes directly inside of the SVG file

**Comment by anmurali** [comment] 2023-06-26 17:12
>@waterim Let's wait for @shawnborton's reply. After that, @Julesssss will need to assign you the issue. After that, you can start on the PR.

@Julesssss - I think we're waiting on you to assign this issue to @waterim. 
Can you do that asap so we can unblock this?

**Comment by Julesssss** [comment] 2023-06-27 08:09
Hey @shawnborton and @waterim, if it's possible to edit XML file directly to resolve this, is it possible Figma has a feature to achieve a similar change? Regardless, if Shawn is happy to go ahead we can simply edit the XML manually for now. 

Can you please confirm @shawnborton and I'll go ahead and assign it.

**Comment by shawnborton** [comment] 2023-06-27 10:49
Yup, I'm cool with the contributor directly editing the svg to see if we can get the desired results.

**Comment by Julesssss** [comment] 2023-06-27 12:37
Sweet, lets do it

**Comment by Julesssss** [comment] 2023-06-30 08:46
Awaiting deployment

**Comment by Julesssss** [comment] 2023-07-10 10:29
[Deployed](https://github.com/Expensify/App/pull/21745#issuecomment-1622167639) to prod 5 days ago, not sure why the hold message wasn't added. Will do it manually

**Comment by waterim** [comment] 2023-07-17 20:20
No overdue

**Comment by Julesssss** [comment] 2023-07-28 08:12
This one is ready for payment @anmurali

**Comment by Julesssss** [comment] 2023-08-07 10:53
As Anu is OOO, I will ask for someone to take over in Slack.

**Comment by Julesssss** [comment] 2023-08-07 10:54
Ah sorry I didn't realise you were OOO until today, and I see you are back in now :)

**Comment by Julesssss** [comment] 2023-08-29 12:03
> @anmurali I think this is eligible for bonus. It was assigned on Jun 27 at 5.37PM (GMT +5) and was merged on Jun 30 at 1:34PM (GMT +5).

Yeah I agree, not sure why the automation failed this time...

**Comment by JmillsExpensify** [comment] 2023-09-01 02:50
Reviewed the details for @allroundexperts. $1,500 approved for payment based on BZ summary.

**Comment by Julesssss** [comment] 2023-09-15 03:04
> Reviewed the details for @allroundexperts. $1,500 approved for payment based on BZ summar

Hi @JmillsExpensify, was this paid?

**Comment by Julesssss** [comment] 2023-09-15 08:22
Thanks, closing

**Closed by Julesssss** 2023-09-15 08:22 UTC
Labels: Reviewing, External, Daily, Bug
