### ISSUE TITLE
Login - cursor height changes when user starts typing

### ISSUE THREAD

**Issue by kavimuru** [Expensify/App#13771] opened 2022-12-21 22:14 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:

1. Go to login page
2. type any letter and remove it
3. check cursor height

## Expected Result: 
cursor height should not change

## Actual Result : 
cursor height changes

## Workaround:
unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native

**Version Number:** 1.2.42-2
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** 

https://user-images.githubusercontent.com/43996225/209012594-335db1b1-ed2a-492f-acea-b1fcbe6e61b8.mp4

https://user-images.githubusercontent.com/43996225/209012642-33b40ce5-1bdf-4766-8698-a821e1f83198.mp4

**Expensify/Expensify Issue URL:**
**Issue reported by:** @gadhiyamanan 
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1671626406375379

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by miljakljajic** [comment] 2022-12-22 13:25
I wasn't able to reproduce this - adding the `needs reproduction` label!

**Comment by luacmartins** [comment] 2023-01-16 21:35
I'm also unable to reproduce

**Comment by luacmartins** [comment] 2023-01-16 21:39
I tested on 3 different devices in browser stack and couldn't reproduce. Closing, please reopen if needed.

**Closed by luacmartins** 2023-01-16 21:39 UTC
Labels: Weekly, Needs Reproduction, Bug
