### ISSUE TITLE
Sign up - No error indicating that magic code is incorrect when validating account via Wallet

### ISSUE THREAD

**Issue by IuliiaHerets** [Expensify/App#50150] opened 2024-10-03 14:14 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 9.0.44-0
**Reproducible in staging?:** Y
**Reproducible in production?:** N/A - new feature, doesn't exist in prod
**Email or phone of affected tester (no customers):** yonghongkok2+dsposjpds@gmail.com
**Issue reported by:** Applause Internal Team

## Action Performed:
1. Go to staging.new.expensify.com
2. Log in with a new Gmail account.
3. Complete onboarding.
4. Go to Account settings > Wallet.
5. Click Add bank account.
6. Enter incorrect magic code.

## Expected Result:
There will be error indicating that the magic code is incorrect.

## Actual Result:
There is no error indicating that the magic code is incorrect.
Nothing happens after entering incorrect magic code.

## Workaround:
Unknown

## Platforms:

- [x] Android: Native
- [x] Android: mWeb Chrome
- [x] iOS: Native
- [x] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

https://github.com/user-attachments/assets/93ff27ff-c54d-4859-a9c5-453f2697e7ad

  
</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by drminh2807** [comment] 2024-10-03 14:55
## Proposal

### Please re-state the problem that we are trying to solve in this issue.

### What is the root cause of that problem?

### What changes do you think we should make in order to solve the problem?

change `!validateError` to `!isEmptyObject(validateError)` in 
https://github.com/Expensify/App/blob/main/src/components/ValidateCodeActionModal/ValidateCodeForm/BaseValidateCodeForm.tsx#L128-L134

### What alternative solutions did you explore? (Optional)

**Reminder:** Please use plain English, be brief and avoid jargon. Feel free to use images, charts or pseudo-code if necessary. Do not post large multi-line diffs or write walls of text. Do not create PRs unless you have been hired for this job.

**Comment by jasperhuangg** [comment] 2024-10-03 16:14
This is a bug that wasn't caught during review in https://github.com/Expensify/App/pull/49230

**Comment by jasperhuangg** [comment] 2024-10-03 16:14
cc @daledah Are you available to fix this?

**Comment by jasperhuangg** [comment] 2024-10-03 16:15
cc @arosiclair @jjcoffee

**Comment by jasperhuangg** [comment] 2024-10-03 16:16
The PR causes another blocker, but I think it would be better to fix than revert since the PR is so large.

**Comment by jasperhuangg** [comment] 2024-10-03 16:31
@daledah Thanks! Please address https://github.com/Expensify/App/issues/50153 in your followup as well.

**Comment by arosiclair** [comment] 2024-10-03 16:44
I can takeover on this one. @daledah do you think you can clean up these blockers today? 

> The PR causes another blocker, but I think it would be better to fix than revert since the PR is so large.

It's not a big deal to revert IMO. If we can't fix these before today's deploy, I think we should just go ahead and revert and clean everything up later.

**Comment by arosiclair** [comment] 2024-10-03 21:05
Fix is merged and CP'd. I'm going to close this in favor of https://github.com/Expensify/App/issues/50153. We'll handle Ishpaul's payment there

**Closed by arosiclair** 2024-10-03 21:05 UTC
Labels: Reviewing, DeployBlockerCash, Engineering, Weekly, Bug
