### ISSUE TITLE
[HOLD for payment 2024-06-20] [$250] iOS - Chat - The cursor moves one space backward when inserting text after an emoji

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#42664] opened 2024-05-27 19:56 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** v1.4.76-1
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:** https://expensify.testrail.io/index.php?/tests/view/4577924
**Issue reported by:** Applause - Internal Team

## Action Performed:
Pre-requisite: the user must be logged in.
1. Go to any chat.
2. Tap on the compose box.
3. Enter any text and an emoji.
4. After you have entered the emoji, enter any character again.
5. Verify the cursor moves one space backward.

## Expected Result:
The cursor should remain at the end of the compose box content.

## Actual Result:
The cursor moves one space backward when inserting text after an emoji.

## Workaround:
n/a

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [x] iOS: Native
- [ ] iOS: mWeb Safari
- [ ] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

https://github.com/Expensify/App/assets/93399543/b44491bc-2ce6-45cb-91f4-07e68ab4d95c

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~011bc1604b6420e233</li>
        <li>Upwork Job ID: 1795296506360057856</li>
        <li>Last Price Increase: 2024-05-28</li>
<li>Automatic offers: </li>
<ul>
<li>eh2077 | Reviewer | 102571526</li>
<li>bernhardoj | Contributor | 102571528</li>
</ul></li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @kadiealexander</details>

**Comment by kbecciv** [comment] 2024-05-27 19:59
We think that this bug might be related to #vip-vsb

**Comment by kbecciv** [comment] 2024-05-27 19:59
@kadiealexander FYI I haven't added the External label as I wasn't 100% sure about this issue. Please take a look and add the label if you agree it's a bug and can be handled by external contributors.

**Comment by bernhardoj** [comment] 2024-05-28 08:36
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
The cursor selection moves to the left by one character when adding a character after inserting an emoji.

### What is the root cause of that problem?
When we add a text to the composer, it will save the new selection position to a ref if the `commentValue` is not equal to `newComment`
https://github.com/Expensify/App/blob/2514f2988eb26858d30fa501c0040b1f8fc2e239/src/pages/home/report/ReportActionCompose/ComposerWithSuggestions/ComposerWithSuggestions.tsx#L439-L444

`commentValue` is the text that we type while the `newComment` is the `commentValue` that has emoji code replaced to emoji character (for example :smile: to 😄).

If they are different, we want to manually correct the selection, however, on iOS, the selection prop is buggy so we use the ref sync solution that imperatively updates the selection that is introduced in https://github.com/Expensify/App/pull/30835.

It will update/sync the selection in `onChangeText`. 

https://github.com/Expensify/App/blob/2514f2988eb26858d30fa501c0040b1f8fc2e239/src/pages/home/report/ReportActionCompose/ComposerWithSuggestions/ComposerWithSuggestions.tsx#L553-L563

However, there are a few things to notice here.

First, when we add an emoji from the emoji picker, `commentValue` is not equal to `newComment` even though there is no emoji code converted to an emoji character. The reason behind this is that we add a whitespace to the text

https://github.com/Expensify/App/blob/2514f2988eb26858d30fa501c0040b1f8fc2e239/src/pages/home/report/ReportActionCompose/ComposerWithSuggestions/ComposerWithSuggestions.tsx#L417

So, `commentValue` doesn't have the whitespace while the `newComment` has the whitespace. Previously, `commentValue` already contained the whitespace every time we added an emoji from the emoji picker, but this [PR](https://github.com/Expensify/App/pull/30955) changes it so the whitespace is also added when we add the emoji from the device keyboard emoji picker.

This will then set the selection to the ref (syncSelectionWithOnChangeTextRef).

Next, if we add an emoji from the emoji picker, `onChangeText` won't be triggered. `onChangeText` will only be triggered if we input the text manually from keyboard.

So, when we add a character, it will run the selection sync logic which contains the old selection.

https://github.com/Expensify/App/blob/2514f2988eb26858d30fa501c0040b1f8fc2e239/src/pages/home/report/ReportActionCompose/ComposerWithSuggestions/ComposerWithSuggestions.tsx#L553-L563

### What changes do you think we should make in order to solve the problem?

We need to compare `newComment` with the `commentValue` with whitespace appended because the manual selection correction is only used when we add emoji through emoji code.
```
const commentWithSpaceInserted = isEmojiInserted ? ComposerUtils.insertWhiteSpaceAtIndex(commentValue, endIndex) : commentValue;
...
if (commentWithSpaceInserted !== newComment) {
...
```

**Comment by kaushiktd** [comment] 2024-05-28 11:09
### Please re-state the problem that we are trying to solve in this issue.
iOS - Chat - The cursor moves one space backward when inserting text after an emoji

### What is the root cause of that problem?
When inputting text into the composer, the system saves the new selection position to a reference (ref) if the commentValue doesn't match the newComment. This disparity occurs due to the presence of an extra whitespace added to newComment during emoji insertion, which is absent in commentValue.

### What changes do you think we should make in order to solve the problem?
Instead of comparing **commentValue** and **newComment**, directly track the insertion point to determine cursor positioning.
Calculate the **newCursorPosition** dynamically based on the difference in length between the old and new comments.

https://github.com/Expensify/App/blob/2514f2988eb26858d30fa501c0040b1f8fc2e239/src/pages/home/report/ReportActionCompose/ComposerWithSuggestions/ComposerWithSuggestions.tsx#L439-L444
```
// Calculate the new cursor position based on the difference in text length
const currentLength = commentRef.current.length;
const newLength = newCommentConverted.length;
let newCursorPosition = cursorPosition ?? 0;

// Determine if an emoji was inserted and adjust cursor position accordingly
if (isEmojiInserted && newLength > currentLength) {
    newCursorPosition = endIndex + 1; // Move the cursor after the inserted emoji
} else if (currentLength > newLength) {
    newCursorPosition = Math.max(selection.end - (currentLength - newLength), 0); // Adjust cursor for deleted characters
} else {
    newCursorPosition = selection.end + (newLength - currentLength); // Adjust cursor for added characters
}

// Update the selection position and clear the ref if necessary
setSelection({ start: newCursorPosition, end: newCursorPosition });
if (isIOSNative) {
    syncSelectionWithOnChangeTextRef.current = { position: newCursorPosition, value: newComment };
}
```

This approach ensures accurate cursor positioning by directly tracking insertion points and dynamically adjusting cursor positions, thereby resolving the cursor issue caused by indirect comparisons and ensuring correct placement after inserting emojis or additional text.

video:-https://drive.google.com/file/d/19PDhzOkps6aXYRAWwyeWr3qyrc_xXzAP/view?usp=sharing

**Comment by eh2077** [comment] 2024-05-29 14:26
@bernhardoj 's [proposal](https://github.com/Expensify/App/issues/42664#issuecomment-2134649360) looks good to me. Nice write up to unwrap the root cause! I also agree with the idea of fixing it by narrowing the scope of the manual-selection-correction-specific code.

🎀👀🎀 C+ reviewed

**Comment by eh2077** [comment] 2024-05-31 15:41
@MonilBhavsar Friendly bump, wdyt https://github.com/Expensify/App/issues/42664#issuecomment-2137553685

**Comment by MonilBhavsar** [comment] 2024-06-03 09:31
Yes, looking at this...

**Comment by MonilBhavsar** [comment] 2024-06-03 10:17
@bernhardoj proposal's looks good and simple. 
Is there any specific reason to clear `syncSelectionWithOnChangeTextRef`?

**Comment by bernhardoj** [comment] 2024-06-03 11:27
> Is there any specific reason to clear syncSelectionWithOnChangeTextRef?

Do you mean the alternative solution? `syncSelectionWithOnChangeTextRef` is supposed to be consumed (in `onChangeText `) every time we type something (`updateComment`). But as explained in my proposal, `onChangeText` will only be called when we type from the keyboard, not from adding an emoji from the emoji picker. So, I suggest an alternative solution to always clear it before creating a new `syncSelectionWithOnChangeTextRef` so each `syncSelectionWithOnChangeTextRef` corresponds to each `updateComment`.

Btw, after retesting my main solution, it causes a regression, the cursor is before the emoji when adding an emoji

https://github.com/Expensify/App/assets/50919443/110ec416-3e5c-4739-8b18-5eb769c352ed


so I use the alternative instead.

PR is ready.

cc: @eh2077

**Comment by eh2077** [comment] 2024-06-15 02:51
### Checklist

- [x] [@eh2077] The PR that introduced the bug has been identified. Link to the PR: https://github.com/Expensify/App/pull/30955
- [x] [@eh2077] The offending PR has been commented on, pointing out the bug it caused and why, so the author and reviewers can learn from the mistake. Link to comment: https://github.com/Expensify/App/pull/30955/files#r1640633047
- [x] [@eh2077] A discussion in #expensify-bugs has been started about whether any other steps should be taken (e.g. updating the PR review checklist) in order to catch this type of bug sooner. Link to discussion: NA
- [x] [@eh2077] Determine if we should create a regression test for this bug. _**No**_, as this is edge case.

**Comment by kadiealexander** [comment] 2024-06-19 06:15
Payouts due:

- [ ] Contributor: $250 @bernhardoj - https://www.upwork.com/nx/wm/offer/102571528
- [ ] Contributor+: $250 @eh2077 - https://www.upwork.com/nx/wm/offer/102571526

**Closed** 2024-06-20 05:13 UTC
Labels: External, Daily, Awaiting Payment, Bug
