### ISSUE TITLE
[HOLD #11768] [$250] Report detail page is opened and closed immediately after login while trying to open that deeplink url reported by @0xmiroslav

### ISSUE THREAD

**Issue by kavimuru** [Expensify/App#12428] opened 2022-11-03 14:45 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:

1. Login to any account
2. Go to report detail page
3. Copy url link
4. Logout
5. Visit copied url link
6. Login to same account

## Expected Result:
Report detail page should keep open

## Actual Result:
Report detail page is opened and closed immediately

## Workaround:
unknown

## Platform:

Where is this issue occurring?

- Web

**Version Number:** 1.2.23-7
**Reproducible in staging?:** y
**Reproducible in production?:** y
**Email or phone of affected tester (no customers):** 
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** 

https://user-images.githubusercontent.com/43996225/199752503-924df49e-ab59-4455-93d8-cb7c1c3fdb05.mov

https://user-images.githubusercontent.com/43996225/199752547-f1fa3c65-230a-4337-a5ff-3ecd3d5100ad.mp4

**Expensify/Expensify Issue URL:** 
**Issue reported by:** @0xmiroslav
**Slack conversation:** https://expensify.slack.com/archives/C01GTK53T8Q/p1667406681481269

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by kevinksullivan** [comment] 2022-11-04 15:54
Hm I'm not sure entering the URL should work when completely signed out. If you sent me that link, for example, I shouldn't be able to login/view the details without first entering your username / password.

**Comment by kevinksullivan** [comment] 2022-11-08 23:28
Closing unless someone can help me understand this issue better.

**Comment by kevinksullivan** [comment] 2022-11-09 17:14
@0xmiroslav I see what you're saying now. I misread your reproduction steps in [slack](https://expensify.slack.com/archives/C01GTK53T8Q/p1667406681481269), as if they implied you should be able to access the page in (5) before logging in. 

Thanks for explaining further, that's all I was asking for. FYI everyone on our team knows what a deeplink is 😉 .

**Comment by kevinksullivan** [comment] 2022-11-09 17:16
https://www.upwork.com/jobs/~0157c3b18be3398b9d

**Comment by puneetlath** [comment] 2022-11-09 21:16
For when it comes time to do the RCA checklist, @aimane-chnaif brought up that this was likely caused by [this PR](https://github.com/Expensify/App/pull/12089).

**Comment by yrshva** [comment] 2022-11-09 21:49
it gets on Navigation.dismissModal() in withReportOrNavigateHome, which does navigateBackToRootDrawer and doesn't enter any ifs

**Comment by parasharrajat** [comment] 2022-11-11 16:28
I will review the proposal in few hours.

**Comment by parasharrajat** [comment] 2022-11-14 09:12
Reviewing now.

**Comment by puneetlath** [comment] 2022-11-17 21:18
@NikkiWines this is one of the oldest issues in the /App repo. To help us clear out the large backlog of bugs, can you:  
- Decide whether any proposals currently meet our guidelines and can be approved as-is 
- For any that can't, please take this issue internal and treat it as one of your highest priorities 
- If you have any questions, don't hesitate to start a discussion in #bug-zero

**Comment by NikkiWines** [comment] 2022-11-18 02:46
@mollfpr, thanks for your proposal. It looks pretty good for the deep linking flow, but there're some anomalies in the UI as it loads the view. It looks like it cycles through a few options for the name of the workspace and the name of the room before loading correctly. 

For the `account doesn't have access` flow, it seems like we still end up showing the `ReportSettingsPage1 very briefly.

I'll look into this issue further tomorrow.

**Comment by NikkiWines** [comment] 2022-11-18 18:56
Chatted with @puneetlath, since this issue is only a week only we're going to continue moving forward through the normal external process. @mollfpr please see my comments in [this PR](https://github.com/Expensify/App/issues/12428#issuecomment-1319475069) on your current proposal 🙇

**Comment by mollfpr** [comment] 2022-11-19 03:13
> It looks like it cycles through a few options for the name of the workspace and the name of the room before loading correctly.

Could be related to https://github.com/Expensify/App/issues/12629

> For the account doesn't have access flow, it seems like we still end up showing the ReportSettingsPage very briefly.

Any suggestion for this part?

**Comment by parasharrajat** [comment] 2022-11-19 17:08
I am trying to figure out why the settings page is opened after login. It should take the user directly to the home screen.

**Comment by parasharrajat** [comment] 2022-11-21 19:41
@aimane-chnaif Interested to take this on. I am not getting time for this. Unassigning...

**Comment by mountiny** [comment] 2022-11-22 00:10
Just noting here, this might be similar cause in terms of react-navigation state so we might want to consider holding this for react-navigation project and apply workarounds if this persists. Similarly to this https://github.com/Expensify/App/issues/12717

**Comment by thienlnam** [comment] 2022-11-22 04:18
Added this issue to the main tracking issue https://github.com/Expensify/App/issues/11768

**Comment by marcaaron** [comment] 2022-11-23 20:56
I think we should revert [this PR](https://github.com/Expensify/App/pull/12089) instead of build on it further. I've [explained in detail here](https://github.com/Expensify/App/issues/12676#issuecomment-1322477705) why the HOC solution is most likely **not** the one we want and have concerns that we are just adding complexity to a design that should be investigated and potentially rolled back.

**Comment by kevinksullivan** [comment] 2022-11-23 22:39
Hm, ok Melv. So is the approach @marcaaron  revert the [PR](https://github.com/Expensify/App/pull/12089), re-test to see if this issue exists, and if not close it out?

**Comment by JmillsExpensify** [comment] 2022-11-26 17:42
Assigning myself to this issue as part of the larger navigation reboot and also putting this issue on hold.

**Comment by kevinksullivan** [comment] 2022-11-30 19:58
Just double checking on this @marcaaron . So we need to revert https://github.com/Expensify/App/pull/12089 (@mollfpr ), then see if this issue still exists?

**Comment by marcaaron** [comment] 2022-12-01 22:07
@kevinksullivan That's my understanding, yes. 

@Beamanator Are you able to follow up on the plan we discussed [here](https://github.com/Expensify/App/issues/12676#issuecomment-1323833015)?

**Comment by Beamanator** [comment] 2022-12-02 15:22
Yep yep didn't have time the last few days but planning on that follow-up for early next week 👍

**Comment by JmillsExpensify** [comment] 2022-12-05 13:32
Still working on the revert of #12089 as well as the larger react navigation initiative.

**Comment by JmillsExpensify** [comment] 2022-12-12 12:29
No longer on hold for #12089 but still on hold for navigation re-write.

**Comment by JmillsExpensify** [comment] 2022-12-19 01:36
Still on hold for the navigation revamp.

**Comment by JmillsExpensify** [comment] 2022-12-27 19:55
Switched out weekly for monthly given that the navigation project is large in scope and has no clear ETA.

**Comment by JmillsExpensify** [comment] 2023-01-11 05:35
Still on hold for navigation. We're going to be stuck here for some time to come.

**Comment by JmillsExpensify** [comment] 2023-02-14 06:16
Same same.

**Comment by NikkiWines** [comment] 2023-03-17 22:17
Still on hold I believe!

**Comment by JmillsExpensify** [comment] 2023-04-18 15:33
Still on hold.

**Comment by kevinksullivan** [comment] 2023-05-18 01:32
offer sent @0xmiroslav 

https://www.upwork.com/jobs/~01f027dd8b9450b032

**Comment by kevinksullivan** [comment] 2023-05-18 01:32
FYI I am going OOO a few days so this payment may be delayed.

**Comment by Naveed273** [comment] 2023-05-18 06:09
Hi, I am here to help you, this issue a deeplinking issue. And I think some props are missing to pass and receive which will need to be fixed. I am also going to submit proposal on upwork for this job. 
If you are satisfy with my answer, then please submit my proposal, and we will sort it out within 3 business days

**Comment by Naveed273** [comment] 2023-05-18 07:02
Contributor details
Your Expensify account email: softengr273@gmail.com
Upwork Profile Link: https://www.upwork.com/freelancers/~019c8de8fba62a664d

**Comment by kevinksullivan** [comment] 2023-05-18 15:56
Got around to the payment! Should be all set here.

**Closed by kevinksullivan** 2023-05-18 15:56 UTC
Labels: External, Monthly, Bug
