### ISSUE TITLE
[$1000] Web - Workspace - An error is visible when go back from Connect manually

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#13024] opened 2022-11-24 21:50 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Go to URL https://staging.new.expensify.com/
2. Log in with any account
3. Go to Settings -> Workspaces -> Connect bank account -> Connect manually
4. Click "Back" NOT entering any data

## Expected Result:
There should NOT be any error

## Actual Result:
An error is visible

## Workaround:
Unknown

## Platform:

Where is this issue occurring?

- Web

**Version Number:** 1.2.31.5

**Reproducible in staging?:** Yes

**Reproducible in production?:** Yes

**Email or phone of affected tester (no customers):** 

**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Notes/Photos/Videos:** Any additional supporting documentation

https://user-images.githubusercontent.com/93399543/203867325-9ecc2079-5206-4ee0-b2dc-6a8cf69b1442.mp4

**Expensify/Expensify Issue URL:** 

**Issue reported by:** Applause - Internal Team

**Slack conversation:** 

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~016000f297c530dd31</li>
        <li>Upwork Job ID: 1596215030529708032</li>
        <li>Last Price Increase: 2022-12-08</li>
    </ul>
</details>

**Comment by hungvu193** [comment] 2022-11-25 10:55
<b>Proposal</b>
When clicking back button, the input loses focus and trigger the error validation.
https://github.com/Expensify/App/blob/39b2f9924060c7381b2ff37563a5af88360b0d9d/src/pages/ReimbursementAccount/BankAccountManualStep.js#L77
<b>Solution</b>
Add preventDefault when click back will do the trick.

```diff
-  onBackButtonPress={() => BankAccounts.setBankAccountSubStep(null)} 
+ onBackButtonPress={(e) => { BankAccounts.setBankAccountSubStep(null); e.preventDefault(); }}
```
We can also add onLongPress event too incase we don't want the input to loose focus when long click.
It will also happen if we click other button like: Get Assistance, Close. We can also do the same.
Result:

https://user-images.githubusercontent.com/16502320/203968166-7c1a5c52-d4e8-442e-9957-9b76d1929c95.mov

**Comment by thesahindia** [comment] 2022-11-25 21:12
This behaviour is present at every page that is using `Form` component. If we wanna fix this then we should be fixing this for all the pages.

**Comment by allroundexperts** [comment] 2022-11-25 21:22
### Proposal

## Problem
We're not preventing default in the `HeaderWithBackButton` component.

## Solution
Following is a generic solution that works across all pages.
```diff
diff --git a/src/components/HeaderWithCloseButton.js b/src/components/HeaderWithCloseButton.js
index 27ab5dbbe..3a2a94336 100755
--- a/src/components/HeaderWithCloseButton.js
+++ b/src/components/HeaderWithCloseButton.js
@@ -202,7 +202,10 @@ class HeaderWithCloseButton extends Component {
                         && (
                         <Tooltip text={this.props.translate('common.close')}>
                             <Pressable
-                                onPress={this.props.onCloseButtonPress}
+                                onPress={(e) => {
+                                    e.preventDefault();
+                                    this.props.onCloseButtonPress(e);
+                                }}
                                 style={[styles.touchableButtonImage, styles.mr0]}
                                 accessibilityRole="button"
                                 accessibilityLabel={this.props.translate('common.close')}

```

**Comment by allroundexperts** [comment] 2022-11-25 21:40
### Updated Proposal

## Problem
The issue is that clicking on the `x` button triggers the `onBlur` handler of the `Form input` element. Since `onBlur` has a greater priority than `onClick` handler, `onBlur` gets called first. As such, adding an `e.preventDefault` in the `onClick` handler is of no use. 

## Fix
We need to not fire validation in the `onBlur` handler that is attached to the `Form` component given:
1. Events related target is clickable having a tab index of less than 1.

Thus the following changes:
```diff
diff --git a/src/components/Form.js b/src/components/Form.js
index 4734381bc..99b8abe3b 100644
--- a/src/components/Form.js
+++ b/src/components/Form.js
@@ -217,7 +217,10 @@ class Form extends React.Component {
                 ref: node => this.inputRefs[inputID] = node,
                 value: this.state.inputValues[inputID],
                 errorText: this.state.errors[inputID] || fieldErrorMessage,
-                onBlur: () => {
+                onBlur: (e) => {
+                    if ('tabIndex' in e.relatedTarget && e.relatedTarget.tabIndex < 1) {
+                        return e.preventDefault();
+                    }
                     this.setTouchedInput(inputID);
                     this.validate(this.state.inputValues);
                 },

```
## Result

**Comment by Delgee** [comment] 2022-11-26 09:26
### Proposal
We encountered a similar issue on https://github.com/Expensify/App/issues/12715 and fixed it by calling `preventDefault` on `onMouseDown` event. We can do a similar thing on back button. Since this issue is only occurring on back button. No need to change Form component I think.

**Comment by allroundexperts** [comment] 2022-11-26 09:51
@Delgee `onMouseDown` has a greater precedence than the `onBlur` event. We need to `preventDefault` in a handler that has a greater precedence than the `onBlur` event. As such, your solution works as well. But it's not generic. We'll have to do it on every `Form` with `Back` button. What I've purposed is generic and will work for all the forms.

**Comment by Delgee** [comment] 2022-11-26 10:46
@allroundexperts I think validating input on focus loss is correct behavior. And we should be able to validate input even if the focus is lost because of a click outside of `Form` element. So we should fix this issue on every page this issue happening instead of removing validation when clicked outside `Form` element. Also using `e.relatedTarget.tabIndex` is a bad idea `tabIndex` is just working on the specific cases it is not related to `Form` element at all.

**Comment by allroundexperts** [comment] 2022-11-26 10:52
@Delgee We are validating the input if the focus is lost because of click outside the Form. It's just for specific elements (like href), that when clicked, we don't want to validate. Also, TabIndex is just a single way to do it. As mentioned in proposal, we can use id / class as well to pinpoint this further. 

Also, If we change this on every page, I'm sure this will come up again when new pages get added.

**Comment by Delgee** [comment] 2022-11-26 10:59
@allroundexperts Yes, we just don't want to validate in specific cases, not general cases. So we should fix this issue in those specific cases.

**Comment by fedirjh** [comment] 2022-11-26 19:05
## Proposal
### Problem
As mentioned before `onBlur` is fired before `onClick` , hence the error shows when we click back button
### Solution
We can handle mouse event for the form and only validate when mouse is inside the form , this will prevent any validation when we click outside the `Form`
```diff
diff --git a/src/components/Form.js b/src/components/Form.js
index 4734381bc9..6a47329fa9 100644
--- a/src/components/Form.js
+++ b/src/components/Form.js
@@ -75,6 +75,7 @@ class Form extends React.Component {
         this.state = {
             errors: {},
             inputValues: {},
+            focused: false,
         };
 
         this.inputRefs = {};
@@ -83,6 +84,7 @@ class Form extends React.Component {
         this.setTouchedInput = this.setTouchedInput.bind(this);
         this.validate = this.validate.bind(this);
         this.submit = this.submit.bind(this);
+        this.toggleFocus = this.toggleFocus.bind(this);
     }
 
     /**
@@ -128,6 +130,10 @@ class Form extends React.Component {
         this.props.onSubmit(this.state.inputValues);
     }
 
+    toggleFocus() {
+        this.setState(prev => ({focused: !prev.focused}));
+    }
+
     /**
      * @param {Object} values - An object containing the value of each inputID, e.g. {inputID1: value1, inputID2: value2}
      * @returns {Object} - An object containing the errors for each inputID, e.g. {inputID1: error1, inputID2: error2}
@@ -218,6 +224,9 @@ class Form extends React.Component {
                 value: this.state.inputValues[inputID],
                 errorText: this.state.errors[inputID] || fieldErrorMessage,
                 onBlur: () => {
+                    if (!this.state.focused) {
+                        return;
+                    }
                     this.setTouchedInput(inputID);
                     this.validate(this.state.inputValues);
                 },
@@ -249,6 +258,8 @@ class Form extends React.Component {
                     style={[styles.w100, styles.flex1]}
                     contentContainerStyle={styles.flexGrow1}
                     keyboardShouldPersistTaps="handled"
+                    onMouseEnter={this.toggleFocus}
+                    onMouseLeave={this.toggleFocus}
                 >
                     <View style={[this.props.style]}>
                         {this.childrenWrapperWithProps(this.props.children)}
```

**Comment by thesahindia** [comment] 2022-11-26 20:16
@flodnv, can you please confirm if we wanna fix this issue

**Comment by flodnv** [comment] 2022-11-28 11:10
Thank you for the discussion everyone. For now let's hold on that discussion, see you there!

**Comment by JmillsExpensify** [comment] 2022-12-01 19:04
Commented in the linked thread. I think we should close this issue. Taking it off hold in any case because the discussion there is wrapping up.

**Closed** 2022-12-10 16:55 UTC
Labels: External, Weekly, Help Wanted, Overdue, Bug
