### ISSUE TITLE
[$1000] completed task and reopened task message does not reflect immediately in task thread

### ISSUE THREAD

**Issue by kavimuru** [Expensify/App#21350] opened 2023-06-22 21:05 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. click on + icon
2. select  Assign task option
3. enter and click on next button
4. click on Assignee and select userB as Assignee
5. click on confirm task button
6. from userA, click on mark as done button
7. check the completed task message in userB
## Expected Result: 
completed task and reopened task message should reflect immediately
## Actual Result: 
completed task and reopened task message should reflects after reload

## Workaround:
Can the user still use Expensify without this being fixed? Have you informed them of the workaround?

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [x] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 1.3.30-5
**Reproducible in staging?:** needs reproduction  (it updated immediately for me)
**Reproducible in production?:** needs reproduction 
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/43996225/e44d3e77-3436-4ced-bd37-ed62fe206668

**Expensify/Expensify Issue URL:**
**Issue reported by:** @gadhiyamanan 
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1686577854879009

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01e5403b941c449d68</li>
        <li>Upwork Job ID: 1673393206339190784</li>
        <li>Last Price Increase: 2023-06-26</li>
    </ul>
</details>

**Comment by isabelastisser** [comment] 2023-06-23 16:49
I'm heading OOO until July 5th, reassigning!

**Comment by joekaufmanexpensify** [comment] 2023-06-23 18:22
I think this is a dupe of https://github.com/Expensify/App/issues/20549 , confirming in slack

**Comment by joekaufmanexpensify** [comment] 2023-06-26 12:31
Still discussing

**Comment by joekaufmanexpensify** [comment] 2023-06-26 18:09
Okay, I actually think this is a separate bug from the one I linked above. As the checkbox for marking tasks as complete is syncing immediately. But we are not showing the `completed task` message until after reloading. 

LMK if you disagree with that though @thienlnam , as I see you closed https://github.com/Expensify/App/issues/20549#issuecomment-1605101091

**Comment by StevenKKC** [comment] 2023-06-27 03:40
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
Completed task and reopened task message does not reflect immediately in task thread.

### What is the root cause of that problem?
The root cause is that app is not getting pusher events when a task report is created or reopened.

### What changes do you think we should make in order to solve the problem?
We can send `ReconnectToReport` API if the task status is changed.
In [`componentDidUpdate`](https://github.com/Expensify/App/blob/5f5dd023a8102ef47ac4b58e4bfe79b995cb0330/src/pages/home/report/ReportActionsView.js#L187-L237) function in `ReportActionsView`, we can add below code to request reconnect.
```js
    const wasTaskStatusChangeDetected = lodashGet(prevProps.report, 'statusNum') !== lodashGet(this.props.report, 'statusNum') || lodashGet(prevProps.report, 'stateNum') !== lodashGet(this.props.report, 'stateNum');
        if (wasTaskStatusChangeDetected) {
            Report.reconnect(this.props.report.reportID);
        }
```
### What alternative solutions did you explore? (Optional)
None.

**Comment by joekaufmanexpensify** [comment] 2023-06-27 17:43
@rushatgabhane Could you review this proposal when you have a chance?

**Comment by joekaufmanexpensify** [comment] 2023-06-28 19:12
Sure! Adding engineering as we're thinking this one needs to be internal.

**Comment by joekaufmanexpensify** [comment] 2023-06-28 20:55
Actually wondering if we should hold for https://github.com/Expensify/App/issues/19330 as this may be redesigned/fixed there?

**Comment by joekaufmanexpensify** [comment] 2023-06-29 18:37
@rushatgabhane curious if you agree this should be held until the above issue is complete?

**Comment by joekaufmanexpensify** [comment] 2023-06-29 20:17
Sounds good! Then next step is for Ionatan to confirm that this should in fact be internal.

**Comment by joekaufmanexpensify** [comment] 2023-06-30 17:35
@iwiznia curious on whether you agree [here](https://github.com/Expensify/App/issues/21350#issuecomment-1613743019) that this has to be internal, when you have a chance?

**Comment by joekaufmanexpensify** [comment] 2023-07-03 13:12
Not overdue. Pending internal review.

**Comment by iwiznia** [comment] 2023-07-03 16:14
Hmmmm not sure. @rushatgabhane are you saying the backend is missing sending an onyx update to the appropriate users?

**Comment by joekaufmanexpensify** [comment] 2023-07-05 18:19
@rushatgabhane bump on confirming this when you have a chance?

**Comment by isabelastisser** [comment] 2023-07-06 01:36
I'm back. Thanks @joekaufmanexpensify !

**Comment by isabelastisser** [comment] 2023-07-06 15:45
Hey @rushatgabhane,  please follow up on this question https://github.com/Expensify/App/issues/21350#issuecomment-1618811411

**Comment by iwiznia** [comment] 2023-07-07 16:36
So it seems we need to make 2 fixes? One to send the missing events and one to download the missing data?

@thienlnam can you check out this issue and advise, since you worked on tasks?

**Comment by StevenKKC** [comment] 2023-07-07 16:50
@iwiznia No need to make 2 fixes. There are two approach to fix this issue.
One is modify BE to push events, and one is modify FE to get data.

**Comment by isabelastisser** [comment] 2023-07-10 10:33
@rushatgabhane how should we move forward here?

**Comment by thienlnam** [comment] 2023-07-10 17:28
Yeah, it looks like we need to update the BE to push the reportAction for certain task actions that create a comment

**Comment by thienlnam** [comment] 2023-07-10 17:28
I can update those

**Comment by isabelastisser** [comment] 2023-07-11 09:19
Thanks @thienlnam !

**Comment by isabelastisser** [comment] 2023-07-14 08:22
@thienlnam checking on the status of this.

**Comment by thienlnam** [comment] 2023-07-17 23:54
Have an internal PR up for review https://github.com/Expensify/Web-Expensify/pull/38197

**Comment by thienlnam** [comment] 2023-07-20 21:10
Internal PR merged, now pending deploy

**Comment by arosiclair** [comment] 2023-08-01 14:26
Bump for @thienlnam. Your fix is out on prod and working well. Somebody reported a dupe of this same issue earlier

**Comment by thienlnam** [comment] 2023-08-01 17:15
Sweet, looks like this is ready for payment cc @isabelastisser 
Just the reporter here since it was fixed with an internal PR

**Comment by isabelastisser** [comment] 2023-08-01 18:40
Thanks @thienlnam!

Payment summary:

Issue reported by: @gadhiyamanan - paid $250.

**Closed by isabelastisser** 2023-08-01 18:40 UTC
Labels: Engineering, Daily, Internal, Bug

**Comment by gadhiyamanan** [comment] 2023-08-01 18:44
@isabelastisser you just send me the offer, payment is pending
