### ISSUE TITLE
[HOLD for payment 2024-03-22] [$500] Tag - Selected tag in Parent: Child format is displayed as Parent\: Child in split menu

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#37289] opened 2024-02-27 13:55 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.44-0
**Reproducible in staging?:** Y
**Reproducible in production?:** N
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** Applause - Internal Team
**Slack conversation:**

## Action Performed:
Precondition:
- User is an employee of paid workspace
- The paid workspace has tags in Parent: Child format
1. Go to workspace chat
2. Go to + > Split bill > Scan
3. Select a receipt
4. Click Tag
5. Select a tag in Parent: Child format
6. Click Split
7. Click on the split preview

## Expected Result:
The selected Tag in Parent: Child format will be displayed correctly in the split menu

## Actual Result:
The selected Tag in Parent: Child format is displayed as Parent\: Child in split menu

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [x] Android: mWeb Chrome
- [x] iOS: Native
- [x] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details> 

https://github.com/Expensify/App/assets/78819774/dc8aa00e-58dd-4b45-849d-19263e4ca41e

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01a0f7b9261707ddc4</li>
        <li>Upwork Job ID: 1762476499067256832</li>
        <li>Last Price Increase: 2024-03-06</li>
<li>Automatic offers: </li>
<ul>
<li>dukenv0307 | Contributor | 0</li>
</ul></li>
    </ul>
</details>

**Comment by lanitochka17** [comment] 2024-02-27 13:56
We think that this bug might be related to #vip-split-p2p-chat-groups
CC @arielgreen

**Comment by FitseTLT** [comment] 2024-02-27 13:58
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
Tag - Selected tag in Parent: Child format is displayed as Parent\: Child in split menu

### What is the root cause of that problem?
We are missing the colon cleaning code here
https://github.com/Expensify/App/blob/cfa0ae37156208ebecdc6b2126464ec462271b76/src/components/MoneyRequestConfirmationList.js#L792-L793
### What changes do you think we should make in order to solve the problem?

we should clean the escaping char as
```
                                title={PolicyUtils.getCleanedTagName(TransactionUtils.getTag(transaction, index))}

```
### What alternative solutions did you explore? (Optional)

**Comment by iwiznia** [comment] 2024-02-27 16:22
Context https://expensify.slack.com/archives/C01GTK53T8Q/p1709049225214569
Seems this was fixed in https://github.com/Expensify/App/pull/36978

**Comment by kbecciv** [comment] 2024-03-05 17:01
QA team is able to reproduce the issue on build 1.4.47.0

![bandicam 2024-03-06 00-57-13-029](https://github.com/Expensify/App/assets/93399543/7fd32b27-960b-4d77-8f63-b45a951afa99)

**Comment by FitseTLT** [comment] 2024-03-10 18:59
> This is not a deploy blocker, but seems like earlier PR didn't fix this.
> 
> @dukenv0307 @FitseTLT Can you review your own proposals and confirm if they're still valid? If yes, then I can take a look.

Yep @mananjadhav

**Comment by mananjadhav** [comment] 2024-03-11 17:43
I think it makes sense to use `getTagForDisplay` as it already has `getCleanedTagName` method call. @dukenv0307's [proposal](https://github.com/Expensify/App/issues/37289#issuecomment-1966752678) looks good.

🎀 👀 🎀 C+ reviewed.

**Comment by mananjadhav** [comment] 2024-03-13 18:12
Done with the PR Review, waiting on @yuwenmemon now.

**Comment by yuwenmemon** [comment] 2024-03-13 18:41
Merged!

**Comment by mananjadhav** [comment] 2024-03-22 14:46
We replaced the `PolicyUtils.getCleanedTagName(props.iouTag)` [here](https://github.com/dukenv0307/App/commit/cd77d071dd15ec6adfa78950d9c08e32dc4e9596) with `TransactionUtils.getTag(transaction, index)` which caused the issue. 

I am not sure if we should be adding a regression test here. @yuwenmemon wdyt?

**Comment by JmillsExpensify** [comment] 2024-03-25 15:59
@adelekennedy Can you provide a payment summary and help with payouts please. Thanks!

**Comment by adelekennedy** [comment] 2024-03-25 16:03
Payouts due:

Contributor: $500 @dukenv0307 (Upwork)
Contributor+: $500 @mananjadhav (NewDot)

Upwork job is [here](https://www.upwork.com/nx/wm/offer/0).

**Closed** 2024-03-26 15:17 UTC
Labels: External, Engineering, Daily, Awaiting Payment, Bug

**Comment by JmillsExpensify** [comment] 2024-03-27 04:10
$500 approved for @mananjadhav.
