### ISSUE TITLE
[HOLD for 28618][$500] IOU - IOU details page is grayed out with a red dot in LHN when visiting it after requesting

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#31327] opened 2023-11-15 00:33 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.3.99.0
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** Applause - Internal team
**Slack conversation:**

## Action Performed:
1. Navigate to staging.new.expensify.com
2. Click + > Request money.
3. Create a manual request to any user.
4. Click on the IOU preview twice to open IOU details page.

## Expected Result:
IOU details page will not become grayed out.

## Actual Result:
IOU details page is grayed out with a red dot on LHN.
The reproducibility of this issue depends on how quick user opens the IOU details page after creating it.

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [x] Android: mWeb Chrome
- [x] iOS: Native
- [x] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

https://github.com/Expensify/App/assets/93399543/5e7cf6bb-3357-4f9f-b600-4665e50ebd33

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01cded938787993b8e</li>
        <li>Upwork Job ID: 1724586409305042944</li>
        <li>Last Price Increase: 2023-11-15</li>
    </ul>
</details>

**Comment by Christinadobrzyn** [comment] 2023-11-15 17:35
I'm not able to reproduce this. Asking QA if this is still happening and what additional steps are needed to reproduce it - https://expensify.slack.com/archives/C9YU7BX5M/p1700069743206079

**Comment by jjcoffee** [comment] 2023-11-16 09:48
Interesting, on latest staging now I just get a crash when repeating the same steps.

**Comment by Christinadobrzyn** [comment] 2023-11-17 00:57
I'm really confused by this. I kinda think we should close this without action. 

I reached out to QA asking if this still exists and they said: 

`Tester is still able to reproduce. IOU details page should be open immediately after the request created`

https://github.com/Expensify/App/assets/51066321/255f6149-53fc-4cb4-9da9-3ecb8b2b9c68

This video doesn't show the LHN bar with the red dot so I don't think this is the same issue?

What are the steps you're getting for the crash @jjcoffee?

**Comment by Christinadobrzyn** [comment] 2023-11-17 23:46
I'm going ooo until Monday Nov 27th so going to assign another BZ teammate to monitor this until I'm back. Thanks!

Status: We're trying to reproduce the error or confirm what steps are needed in the OP to create the error. 

- I haven't been able to reproduce this
- QA said it exists and provided this (but I don't see how it's the same issue) https://github.com/Expensify/App/issues/31327#issuecomment-1815567671
- @jjcoffee is getting something different when reproducing - https://github.com/Expensify/App/issues/31327#issuecomment-1814108991

**Comment by Christinadobrzyn** [comment] 2023-11-28 23:33
I can take this back, thanks for monitoring @slafortune!

**Comment by Christinadobrzyn** [comment] 2023-12-06 01:23
hold for https://github.com/Expensify/App/pull/28618

**Comment by Christinadobrzyn** [comment] 2023-12-12 23:30
looks like https://github.com/Expensify/App/pull/28618 is merged so let's test again. 

I just tested and I think this is resolved - @jjcoffee could you check too?

**Comment by jjcoffee** [comment] 2023-12-13 10:45
I can still repro by making a request inside an existing IOU report. 

@dukenv0307 Are you able to take a quick look to see if your proposal is still relevant after the changes in https://github.com/Expensify/App/pull/28618?

**Comment by jjcoffee** [comment] 2023-12-15 09:47
Apologies, only just caught that this is going to be handled here https://github.com/Expensify/App/issues/31411. I think we can close this @Christinadobrzyn :bow:

**Closed** 2023-12-22 01:01 UTC
Labels: External, Weekly, Needs Reproduction, Help Wanted, Bug
