### ISSUE TITLE
[HOLD for payment 2023-12-20] [$500] Copy to Clipboard- Email displayed inconsistently in mweb and Android

### ISSUE THREAD

**Issue by izarutskaya** [Expensify/App#30985] opened 2023-11-07 12:03 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.3.96-9
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** Applause-Internal Team
**Slack conversation:** @

## Action Performed:
1. Launch app
2. Tap on a report
3. Send the mail [applausetester+06075lsn@applause.expensifail.com](mailto:applausetester+06075lsn@applause.expensifail.com)
4. Long press the message sent and note the email displayed in copy to clipboard section
5. Go to https://staging.new.expensify.com/
6. Repeat step 2 -- step 4

## Expected Result:
In Copy to clipboard section, in both mweb and Android, email should be displayed in the same format in a consistent manner.

## Actual Result:
Copy to clipboard section in(.com) shows till "c" in one line ([applausetester+06075lsn@](mailto:applausetester+06075lsn@)

applause.expensifail.c
om) in mweb and shows(.com) in second line ([applausetester+06075lsn@](mailto:applausetester+06075lsn@)

applause.expensifail
.com) in Android.

The displayed email format differs and it is inconsistent in mweb and Android.

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [x] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [ ] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

https://github.com/Expensify/App/assets/115492554/f6f3fa41-8a7d-44e9-9c08-f52264560f10

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~0123a768f29d8cc1b6</li>
        <li>Upwork Job ID: 1721861002279923712</li>
        <li>Last Price Increase: 2023-11-07</li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @kevinksullivan</details>

**Comment by artus9033** [comment] 2023-11-08 09:40
Hi, I'm Artur from Callstack - expert contributor group - and I would like to work on this issue.

**Comment by saikoaizen** [comment] 2023-11-08 14:37
Contributor details
Your Expensify account email: dsenzaimon@gmail.com
Upwork Profile Link: https://www.upwork.com/freelancers/~014114c159b515fad8

**Comment by mananjadhav** [comment] 2023-11-08 14:45
Thanks for the interest @artus9033. Can you post a small proposal with what changes so that we're aligned.

🎀 👀 🎀 C+ reviewed.

**Comment by Julesssss** [comment] 2023-11-08 15:15
Getting Callstack involved sounds good to me

**Comment by artus9033** [comment] 2023-11-08 15:20
@Julesssss thanks, however from mail notifications it seems like something strange happened and somebody assigned their Upwork details through melvinbot? It definitely wasn't me. Could you take a look at this and unassign if that's what happened?

**Comment by Julesssss** [comment] 2023-11-08 15:36
> however from mail notifications it seems like something strange happened and somebody assigned their Upwork details as mine through melvinbot?

Can you forward the email to me please, I'm not sure exactly what you mean but can take a look

**Comment by artus9033** [comment] 2023-11-08 15:38
Sure thing

**Comment by Julesssss** [comment] 2023-11-08 16:30
Yeah, somebody seems to have added their details in place of Artur's. Investigating...

**Comment by artus9033** [comment] 2023-11-09 11:13
Daily update: issue identifed, solution found; working on a proposal

**Comment by artus9033** [comment] 2023-11-13 20:52
Update: I'll be ooo until Wednesday, when I am planning to submit the proposal

**Comment by artus9033** [comment] 2023-11-16 10:18
## Proposal
### Please re-state the problem that we are trying to solve in this issue.
Sliding context menu used for copying email address from chat to clipboard on Android native and Android mobile web inconsistently break words when breaking lines in case the email width exceeds screen width.
### What is the root cause of that problem?
The `Text` component on native Android utilizes more robust word breaking mechanisms (Text's `textBreakStrategy` Android-only prop has a default value of `highQuality`) that detect individual segments of the email and split them e.g. between words. On the web, however, the default word breaking style set in `src/components/ContextMenuItem.js` is `break-all`  (CSS: `wordBreak: 'break-all'`), which is the cause why web splits the words in the unwanted manner:
https://github.com/Expensify/App/blob/9862a3e65393b26184369d312a02e1f7de88b64b/src/components/ContextMenuItem.js#L99
### What changes do you think we should make in order to solve the problem?
The solution consists of two phases:
- changing `wordBreak` to `'break-word'` in the style of menu item description element in `src/components/ContextMenuItem.js`
- inserting zero-width spaces (U+200B) characters, between email segment delimiters (`.`, `@`):
```typescript
getDescription: (selection) =>
            selection.replace('mailto:', '').replace(
                /([.@])/g,
                // below: zero-width space (U+200B) character
                '​$1',
            ),
```

Side note: An alternative (but inferior) approach to the second point could be to use word break opportunity <wbr/> tags, however these are web-only and would require reorganizing prop types and possibly the rendering method in src/components/MenuItem.js, thus making the UTF8 character solution more viable and cross-platform (according to https://developer.mozilla.org/en-US/docs/Web/HTML/Element/wbr#notes they behave the same on UTF-8 encoded pages). Such a move also helps ensure that other platforms than web should also behave consistently in case their word breaking mechanisms would change in future thanks to UTF8 word break opportunities being inserted manually in same places on all platforms.

**Comment by mananjadhav** [comment] 2023-11-16 18:59
Thanks for the proposal @artus9033. With adding zero-width space character we're aiming that the email will be split between any `.` and `@`, right?  But what would happen if I have a very long email with just characters before the domain.  I think the `break-word` will overflow right?


Digging more at my own end, I think this is a non-issue. 

> In Copy to clipboard section, in both mweb and Android, email should be displayed in the same format in a consistent manner.

@Julesssss @kevinksullivan Can we define what do we mean by `consistent manner`?

**Comment by artus9033** [comment] 2023-11-16 21:58
> With adding zero-width space character we're aiming that the email will be split between any . and @, right? But what would happen if I have a very long email with just characters before the domain. I think the break-word will overflow right?

Thanks for the comment @mananjadhav. To answer your question: no, it should not overflow, it will wrap to a new line according to the old behaviour - zero-width spaces will serve as an additional opportunity for wrapping - here is an example with an email with an overlong local part I just tested with my approach:

<img width="893" alt="image" src="https://github.com/Expensify/App/assets/10586109/3549e952-68bb-4437-92cd-24f799c8d02a">

**Comment by Julesssss** [comment] 2023-11-21 14:16
No problem! Your last explanation looks great to me, I'd say we can go ahead as long as @mananjadhav agrees.

**Comment by mananjadhav** [comment] 2023-11-26 17:45
Works for me too.

**Comment by artus9033** [comment] 2023-11-29 08:20
Absolutely @Julesssss, I am making the last style touches to the code, will report back with the final PR today.

**Comment by artus9033** [comment] 2023-11-29 09:20
@Julesssss the PR is ready for review now.
CC: @mananjadhav

**Comment by kevinksullivan** [comment] 2023-12-14 15:09
Hey @mananjadhav please fill out the checklist above when you get a chance. Thanks!

**Comment by mananjadhav** [comment] 2023-12-14 16:51
I don't think we have any offending PR for this one. We changed the behavior of `word-break` styling. I am on the fence for this one regarding regression test. It's a small feature and I don't think we need one. @Julesssss what are your thoughts?

**Comment by Julesssss** [comment] 2023-12-15 08:30
I agree

**Comment by Julesssss** [comment] 2023-12-21 15:54
Ready for payment

**Comment by mananjadhav** [comment] 2023-12-21 16:58
@kevinksullivan can you please post the payout summary for this one?

**Comment by kevinksullivan** [comment] 2023-12-22 18:01
Summary
- Contributor: @artus9033 $500
- C+: @mananjadhav $500

**Comment by kevinksullivan** [comment] 2023-12-22 18:02
Hi @artus9033 can you apply to the job and let me know when you've done so?

https://www.upwork.com/jobs/~0123a768f29d8cc1b6

**Comment by mananjadhav** [comment] 2023-12-22 18:14
Thanks for summary @kevinksullivan. The payout is only for me here for C+ review. @artus9033 is from Callstack (mentioned [here](https://github.com/Expensify/App/issues/30985#issuecomment-1801430654)).

**Comment by artus9033** [comment] 2023-12-22 18:56
That's right, thanks for the explanation @mananjadhav

**Comment by JmillsExpensify** [comment] 2023-12-26 16:29
$500 payment approved for @mananjadhav based on summary above.

**Comment by Julesssss** [comment] 2024-01-04 10:35
Hey @mananjadhav has the payment been accepted?

**Comment by mananjadhav** [comment] 2024-01-04 13:45
Yes @Julesssss Payment is done. We can close this one out.

**Closed** 2024-01-04 14:56 UTC
Labels: External, Engineering, Daily, Overdue, Awaiting Payment, Bug
