### ISSUE TITLE
 Personal details - City and Postcode fields are not populated with suggested address

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#31091] opened 2023-11-09 00:46 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.3.97.0
**Reproducible in staging?:** y
**Reproducible in production?:** n
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** Applause - Internal Team
**Slack conversation:**

## Action Performed:
1. Navigate to staging.new.expensify.com
2. Go to Settings > Profile > Personal details.
3. Click Address.
4. Enter Terrance Street in Address line 1.
5. Select the result with Fort Worth as the City.

## Expected Result:
City and Postcode fields will be populated.

## Actual Result:
City and Postcode fields are not populated.

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [x] Android: mWeb Chrome
- [x] iOS: Native
- [x] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

https://github.com/Expensify/App/assets/93399543/227da905-3fc4-416f-a346-30ad6e5842a5

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by DylanDylann** [comment] 2023-11-09 05:28
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
Personal details - City and Postcode fields are not populated with suggested address

### What is the root cause of that problem?
Currently in address page
- when we change the country we will reset state, city, zipcode to empty
- when we change the state we will reset city, zipcode to empty
- when we change the city we will reset zipcode to empty

When we update address line 1, all fields will be updated in order to: country, city, zipCode, state

zipcode and city fields is updated before state field, so that when state field is updated the App will reset zipcode and city 


### What changes do you think we should make in order to solve the problem?
When we update address line 1, all fields should be updated in order to: country, state, city, zipCode
To do that in here
https://github.com/Expensify/App/blob/dee9b3110a7ebe0aa250c3f966d6a69925d916f4/src/components/AddressSearch/index.js#L231-L239

Should move the state field to before city field like this
```
            country: '',
            state: state || stateAutoCompleteFallback,
            city: locality || postalTown || sublocality || cityAutocompleteFallback,
            zipCode,
```

### What alternative solutions did you explore? (Optional)

**Comment by robertKozik** [comment] 2023-11-09 10:35
@DylanDylann please ping me if you will have the fix for this regression 🙇🏼

**Comment by DylanDylann** [comment] 2023-11-09 10:36
@robertjchen Please help to check this one https://github.com/Expensify/App/issues/31091#issuecomment-1803185521

**Comment by lakchote** [comment] 2023-11-09 11:05
@DylanDylann I've just tested to revert your PR and I don't have the problem anymore, so it looks like it's a regression.

You can test it doing `git revert --no-commit 040c8a7`

**Comment by DylanDylann** [comment] 2023-11-09 11:08
Agree it is a regression. I mean  `Because this issue have another RCA, I miss to check if It is regression from our PR`

**Closed** 2023-11-10 07:27 UTC
Labels: DeployBlockerCash, Engineering, Hourly
