### ISSUE TITLE
[$1000] Chat - Room admin sees all welcome messages to invited users (appears after page refresh)

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#19689] opened 2023-05-26 19:20 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Issue found when executing PR** https://github.com/Expensify/App/pull/18662

## Action Performed:
1. Login to NewDot
2. As user A create a public room and add a welcome message
3. As a user A invite user B to public room
4. As user B accept invitation to the room (enter the room). Observe you see welcome message.
5. As a user A refresh the room page

## Expected Result:
Welcome messages should be visible only to invited users

## Actual Result:
Welcome message to every user that joined the room is visible to admin (with tag, that message is visible only to that joining user)

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [x] Android / Chrome
- [ ] iOS / native
- [x] iOS / Safari
- [x] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 1.3.19.1

**Reproducible in staging?:** yes

**Reproducible in production?:** new feature

**If this was caught during regression testing, add the test name, ID and link from TestRail:**

**Email or phone of affected tester (no customers):**

**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Notes/Photos/Videos:** Any additional supporting documentation

https://platform.applause.com/services/links/v1/external/86a90ede63d027d507e3b0d7caffd19534dbaef8b6bd1ac1d30e8c226d23d120

**Expensify/Expensify Issue URL:**

**Issue reported by:** Applause - Infernal team

**Slack conversation:**

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01454f0d4365208af8</li>
        <li>Upwork Job ID: 1664740336325787648</li>
        <li>Last Price Increase: 2023-06-02</li>
    </ul>
</details>

**Comment by michaelhaxhiu** [comment] 2023-05-31 19:58
Ya this is strange UX for sure. I agree with the expected outcome.

**Comment by michaelhaxhiu** [comment] 2023-06-02 21:28
1 proposal already added

**Comment by dangrous** [comment] 2023-06-05 14:22
@abdulrahuman5196 if you have time to take a look at @huzaifa-99's [proposal](https://github.com/Expensify/App/issues/19689#issuecomment-1569947282) that would be great!

**Comment by abdulrahuman5196** [comment] 2023-06-05 16:49
@dangrous Based on the [proposal](https://github.com/Expensify/App/issues/19689#issuecomment-1569947282) I checked on the action items. We are getting the unwanted action from API itself. 
Can we filter the unwanted reportActions at server itself? Any specific reason we should do it in frontend?

**Comment by dangrous** [comment] 2023-06-05 18:27
Oh hm, yeah whispers shouldn't be sent at all to anyone who isn't the recipient, i don't think.

I'll cc @pecanoro here in case she has some ideas, but otherwise I'll take a look at the backend and see what I can figure out.

**Comment by pecanoro** [comment] 2023-06-05 18:52
This is by design, whoever sent the whisper can see the message as well so they know who was sent to (both are aware). However, it's true this can be a bit more annoying for welcome messages as they can be sent to a lot of people if they join a big room. I vote to close it for now and deal with it later. Or maybe just bring up the discussion to Slack in product to see how we should approach it. We would need some kind of flag to tell welcome messages apart from normal whispers.

**Comment by dangrous** [comment] 2023-06-05 19:13
Oh interesting. I have started a discussion in [Slack](https://expensify.slack.com/archives/C03U7DCU4/p1685992370977739), and closed this for now. Thank you for the details @pecanoro!

**Closed by dangrous** 2023-06-05 19:13 UTC
Labels: External, Daily, Help Wanted, Bug
