### ISSUE TITLE
[HOLD for payment 2022-05-20][$250] New room - Not able to create a new room, error message appears

### ISSUE THREAD

**Issue by kavimuru** [Expensify/App#8534] opened 2022-04-07 13:13 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:

1. Log in to any expensifail account
2. Click on the green plus button in the bottom.
3. Choose new room
4. Enter room's name
5. Choose workspace
6. Click create room

## Expected Result:
New room must be created when I click create room

## Actual Result:
New room is not created and I see error message

## Workaround:
unknown

## Platform:

Where is this issue occurring?

- Web
- iOS
- Android
- Desktop App
- Mobile Web

**Version Number:** 1.1.52-0

**Reproducible in staging?:** y

**Reproducible in production?:** y

**Email or phone of affected tester (no customers):** 

**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Notes/Photos/Videos:** 

https://user-images.githubusercontent.com/43996225/162206860-40cf5b13-0f65-476c-b274-047d6fe1060a.mp4
![Bug5523390_issue_0704](https://user-images.githubusercontent.com/43996225/162206880-bfafebd4-1b36-46e7-b57a-41b2fdc4f01e.png)

**Expensify/Expensify Issue URL:** 

**Issue reported by:** Applause @thesahindia 

**Slack conversation:** https://expensify.slack.com/archives/C01GTK53T8Q/p1648760293684219

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by francoisl** [comment] 2022-04-11 18:00
Reproducible in production.
The API returns a 200 response for the `CreatePolicyRoom` call, so it's most likely a front-end issue interpreting the response.

<img width="1440" alt="image" src="https://user-images.githubusercontent.com/2229301/162800939-14102d88-7aaa-4e90-a19d-9498ee2697f9.png">

**Comment by thesahindia** [comment] 2022-04-11 20:52
I think that the backend must be sending the data in the form of an array earlier which was working just fine -
https://github.com/Expensify/App/blob/0596be5899916b4eae8d723dfc4c07e4fd05ed7e/src/libs/actions/Report.js#L1526

But now, you can see the logged response below (we're getting an object with key : report_SOME-ID)


<img width="401" alt="Screenshot 2022-04-12 at 2 03 21 AM" src="https://user-images.githubusercontent.com/83179295/162827850-31fe6ca0-6046-4868-8d10-0bdfe6575a8a.png">

I think we it should be fixed at the backend, but if for some reason we can't then I propose this fix -
We can make a variable for reportID and we just need to set the value after line 1523 (or we can just extract the key from the Object & use it)
https://github.com/Expensify/App/blob/0596be5899916b4eae8d723dfc4c07e4fd05ed7e/src/libs/actions/Report.js#L1518-L1525

```diff
 Onyx.set(ONYXKEYS.IS_LOADING_CREATE_POLICY_ROOM, true);
+    let reportID;
    return API.CreatePolicyRoom({policyID, reportName, visibility})
        .then((response) => {
            if (response.jsonCode !== 200) {
                Growl.error(response.message);
                return;
            }
+            reportID = response.reportID;
            return fetchChatReportsByIDs([response.reportID]);
        })
        .then(() => {
            if (!reportID) {
                Log.error('Unable to grab policy room after creation', reportID);
                return;
            }
```

**Comment by jliexpensify** [comment] 2022-04-12 02:37
Posted!

Internal - https://www.upwork.com/ab/applicants/1513707338062458880/job-details
External - https://www.upwork.com/jobs/~0149d3c7692c4cf31b

Invited @thesahindia as the bug reporter

**Comment by rushatgabhane** [comment] 2022-04-13 15:49
@thesahindia you found the cause. But I think we should fix it here by correctly accessing the `reportID`

https://github.com/Expensify/App/blob/0596be5899916b4eae8d723dfc4c07e4fd05ed7e/src/libs/actions/Report.js#L1526

Thoughts?

**Comment by rushatgabhane** [comment] 2022-04-18 13:55
bump ^^ @thesahindia

**Comment by thesahindia** [comment] 2022-04-19 19:27
> @thesahindia you found the cause. But I think we should fix it here by correctly accessing the `reportID`

The object key keeps changing( reportID is not the key but the "report_" + value of reportID is ) so to do that we need to extract the key or the simple way would be to just use the reportID that we get in response here
https://github.com/Expensify/App/blob/0596be5899916b4eae8d723dfc4c07e4fd05ed7e/src/libs/actions/Report.js#L1518-L1525

I had mentioned this here https://github.com/Expensify/App/issues/8534#issuecomment-1095554357

**Comment by aneequeahmad** [comment] 2022-04-19 22:24
### PROPOSAL

We can extract the key from the response as below 

```
        .then((response) => {
          const reportID = Object.values(response).map(({ reportID }) => reportID)[0]
            if (!reportID) {
                Log.error('Unable to grab policy room after creation', reportID);
                return;
            }
            
  ``` 
  
  Instead of ` .then(([{reportID}]) => {`

**Comment by rushatgabhane** [comment] 2022-04-20 07:02
> New contributors are limited to working on one job at a time, however experienced contributors may work on numerous jobs simultaneously. [see contributing.md](https://github.com/Expensify/App/blob/main/CONTRIBUTING.md#payment-for-contributions)

@aneequeahmad since you're a new contributor, you're limited to only one job at a time. So I'd suggest that you complete the PR https://github.com/Expensify/expensify-common/pull/441 as soon as possible. After which, you may work on multiple jobs. Thanks!

**Comment by rushatgabhane** [comment] 2022-04-20 07:05
@thesahindia I'm sure we can figure something out using [underscore.js](https://underscorejs.org/#objects). Please let me know when you submit an updated proposal, thanks!

**Comment by thesahindia** [comment] 2022-04-20 08:49
### Updated Proposal 

We can use `_.values` to access the object

```js
        .then((response) => {
            const {reportID} = _.values(response)[0];
```

**Comment by rushatgabhane** [comment] 2022-04-20 12:59
@AndrewGable I like @thesahindia's [proposal](https://github.com/Expensify/App/issues/8534#issuecomment-1103639990). Changes will be made over here.
https://github.com/Expensify/App/blob/0596be5899916b4eae8d723dfc4c07e4fd05ed7e/src/libs/actions/Report.js#L1526-L1527

🎀 👀 🎀 C+ reviewed

**Comment by AndrewGable** [comment] 2022-04-20 16:06
Looking forward to the PR 👍

**Comment by jliexpensify** [comment] 2022-05-02 08:16
Not overdue Melv!

**Comment by jliexpensify** [comment] 2022-05-13 06:53
Not overdue Melvin

**Comment by mvtglobally** [comment] 2022-05-17 03:28
Issue not reproducible during KI retests. (First week)

**Comment by jliexpensify** [comment] 2022-05-23 03:36
Paying now!

**Comment by jliexpensify** [comment] 2022-05-23 03:39
Previous created job was closed, so re-created: https://www.upwork.com/ab/applicants/1528581043536789504/job-details

@rushatgabhane and @thesahindia - have re-invited you. Thanks!

**Comment by jliexpensify** [comment] 2022-05-23 23:32
Paid @rushatgabhane , will pay $500 to @thesahindia once he accepts. Cheers!

**Comment by mvtglobally** [comment] 2022-05-24 04:27
Issue not reproducible during KI retests. (Second week)

**Comment by thesahindia** [comment] 2022-05-24 06:19
Accepted the offer, good to go 🚀

**Comment by jliexpensify** [comment] 2022-05-24 06:26
Paid @thesahindia and closed the Upwork job.

**Closed by jliexpensify** 2022-05-24 06:26 UTC
Labels: Exported, External, Engineering, Weekly, Awaiting Payment
