### ISSUE TITLE
Chat - Unable to type a few symbols and console error shows up

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#30583] opened 2023-10-30 14:25 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.3.93-0
**Reproducible in staging?:** Y
**Reproducible in production?:**N
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** Applause - Internal Team
**Slack conversation:**

**Issue found when executing PR** https://github.com/Expensify/App/pull/28587
## Action Performed:
1. Go to staging.new.expensify.com
2. Open any new chat.
3. Type the following
.
( and )
[
*
+
|
\

## Expected Result:
User is able to type the symbols without issue

## Actual Result:
User is unable to type the symbols. Console error shows up as well
For |, the content in the composer is cleared

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [x] Android: mWeb Chrome
- [x] iOS: Native
- [x] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos
<details>
<summary>Android: Native</summary>

</details>

<details>
<summary>Android: mWeb Chrome</summary>

</details>

<details>
<summary>iOS: Native</summary>

</details>

<details>
<summary>iOS: mWeb Safari</summary>

</details>

<details>
<summary>MacOS: Chrome / Safari</summary>

 

https://github.com/Expensify/App/assets/78819774/da2a6266-a56c-4fbd-a51c-4f2ac6dadde8

</details>

<details>
<summary>MacOS: Desktop</summary>

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by grgia** [comment] 2023-10-30 14:36
I think this is being fixed by https://github.com/Expensify/App/pull/30559

**Comment by situchan** [comment] 2023-10-30 14:38
yes dupe of #30578

**Closed** 2023-10-30 14:40 UTC
Labels: DeployBlockerCash, Engineering, Hourly, Bug
