### ISSUE TITLE
[$250] Chat - Missing start convo message and description room changes to a code

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#50168] opened 2024-10-03 16:24 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 9.0.44
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**If this was caught during regression testing, add the test name, ID and link from TestRail:** N/A
**Issue reported by:** Applause - Internal Team

## Action Performed:
1. Create a new chat room
2. Send a message

## Expected Result:
The start conversation message is displayed below the Welcome message and the description room remains unchanged when the user performs any activity in the room

## Actual Result:
The start conversation message is not displayed below the Welcome message
The description room changes to a code when the user sends a message

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [x] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

<details>
  <summary>Add any screenshot/video evidence</summary>

  
</details> 

https://github.com/user-attachments/assets/d2d5a107-1e74-4b75-adf5-6917a5df8e8a

https://github.com/user-attachments/assets/75fe02e9-2f79-4f81-99cd-8041ade949f6

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~021842271623775763004</li>
        <li>Upwork Job ID: 1842271623775763004</li>
        <li>Last Price Increase: 2024-10-11</li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @rushatgabhane</details>

**Comment by lanitochka17** [comment] 2024-10-03 16:25
@joekaufmanexpensify  FYI I haven't added the External label as I wasn't 100% sure about this issue. Please take a look and add the label if you agree it's a bug and can be handled by external contributors

**Comment by joekaufmanexpensify** [comment] 2024-10-07 14:05
Pending review of proposal

**Comment by truph01** [comment] 2024-10-07 18:51
@joekaufmanexpensify Can you confirm the expected behavior here: Do we want to display both room's description and start conversation message? Currently in staging, if room's description is existed, we don't display the start conversation message

**Comment by joekaufmanexpensify** [comment] 2024-10-08 13:39
I don't think we should change that behavior. I would focus just on the scope of the issue in OP.

**Comment by truph01** [comment] 2024-10-08 13:51
> I don't think we should change that behavior. I would focus just on the scope of the issue in OP.

@joekaufmanexpensify If so, we just need to fix "The description room changes to a code when the user sends a message", which is dupe of https://github.com/Expensify/App/issues/49355

**Comment by joekaufmanexpensify** [comment] 2024-10-08 13:54
Ah, hmm. Let me investigate a bit further then.

**Comment by joekaufmanexpensify** [comment] 2024-10-08 18:20
>@joekaufmanexpensify Can you confirm the expected behavior here: Do we want to display both room's description and start conversation message? Currently in staging, if room's description is existed, we don't display the start conversation message

@truph01 are you seeing that this was recently introduced somewhere in a specific PR? Or just became aware of this as part of this issue.

**Comment by joekaufmanexpensify** [comment] 2024-10-10 22:17
@truph01 could you confirm [this](https://github.com/Expensify/App/issues/50168#issuecomment-2400530356) when you have a sec?

**Comment by truph01** [comment] 2024-10-11 16:31
> @truph01 are you seeing that this was recently introduced somewhere in a specific PR? Or just became aware of this as part of this issue.

- In staging, if room does not have description, we display the text "This chat room is for anything test-room related". Otherwise, we display the room's description instead. But now I can't find which PR introduced this behavior.



















- In the expected section of this issue, _"The start conversation message is displayed below the Welcome message"_

So, what is the intended behavior here? Should we keep it as it currently is, or switch to the new expected behavior outlined in this issue?

**Comment by joekaufmanexpensify** [comment] 2024-10-11 20:49
>In staging, if room does not have description, we display the text "This chat room is for anything test-room related". Otherwise, we display the room's description instead. But now I can't find which PR introduced this behavior.

I just tested this behavior. It works identically on staging and production.

**Comment by joekaufmanexpensify** [comment] 2024-10-11 20:51
Therefore, I think the only issue here to address would be showing the code in the room description, which like you said is a dupe of the other issue linked above. So closing this as seems like there is nothing to handle here!

**Closed by joekaufmanexpensify** 2024-10-11 20:51 UTC
Labels: External, Daily, Help Wanted, Overdue, Bug
