### ISSUE TITLE
[HOLD for payment 2023-10-16] [$500] Attachment -  Red error message appears briefly when closing password protected PDF

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#28195] opened 2023-09-25 20:54 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
Action Performed:
1. Go any report
2. Open password protected PDF page
3. Click close button, Observe error message appears briefly

## Expected Result:
No error message after close

## Actual Result:
Error message appears briefly after closing password protected PDF

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [x] Android / Chrome
- [ ] iOS / native - did not provided yet, requested
- [x] iOS / Safari
- [x] MacOS / Chrome / Safari
- [x] MacOS / Desktop

**Version Number:** 1.3.74.0
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/93399543/b94e2076-1ee1-4372-a728-f1375c31110f

https://github.com/Expensify/App/assets/93399543/35740037-9389-47df-b353-2884ee8a7a73

**Expensify/Expensify Issue URL:**
**Issue reported by:** @namhihi237
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1695551022734439

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01b3fbc4b9a33f9413</li>
        <li>Upwork Job ID: 1706411843181993984</li>
        <li>Last Price Increase: 2023-10-02</li>
<li>Automatic offers: </li>
<ul>
<li>jjcoffee | Reviewer | 26985177</li>
<li>namhihi237 | Contributor | 26985179</li>
<li>namhihi237 | Reporter | 26985182</li>
</ul></li>
    </ul>
</details>

**Comment by kbecciv** [comment] 2023-09-25 20:57
Proposal by: @namhihi237
Slack conversation: https://expensify.slack.com/archives/C049HHMV9SM/p1695551022734439

## Proposal
### Please re-state the problem that we are trying to solve in this issue.
Error message appears briefly after closing password-protected PDF, It also when we click download
### What is the root cause of that problem?
We call the function check error when blur input:
https://github.com/Expensify/App/blob/5217721ea99ccf00bd723b2ae0a121dcd90a2e25/src/components/PDFView/PDFPasswordForm.js#L129
In the function `validateAndNotifyPasswordBlur` we call `validate` function. That means when we click outside the input> it will tricker and show an error.
https://github.com/Expensify/App/blob/5217721ea99ccf00bd723b2ae0a121dcd90a2e25/src/components/PDFView/PDFPasswordForm.js#L98-L101
https://github.com/Expensify/App/blob/5217721ea99ccf00bd723b2ae0a121dcd90a2e25/src/components/PDFView/PDFPasswordForm.js#L81-L89
### What changes do you think we should make in order to solve the problem?
I think we can remove validation when blur input. We only check when click confirm.
### What alternative solutions did you explore? (Optional)
N/A

**Comment by DylanDylann** [comment] 2023-09-26 10:05
## Proposal

### Please re-state the problem that we are trying to solve in this issue.

Red error message appears briefly when closing password protected PDF

### What is the root cause of that problem?
When clicking close button
https://github.com/Expensify/App/blob/3486648811b9bb6bdacbea07e0ab4bb2236ba372/src/components/PDFView/PDFPasswordForm.js#L98-L102

This function will be triggered, It makes a red error appear a moment

### What changes do you think we should make in order to solve the problem?
We should trigger the validate function on blur only when the current app is visible and has focus. And then we can use setTimeOut to delay validation like this
```
const validateAndNotifyPasswordBlur = () => {
        // Only run validation when user proactively blurs the input.
        if (!Visibility.isVisible() || !Visibility.hasFocus()) {
            return
        }
        setTimeout(() => {
            validate();
            onPasswordFieldFocused(false);
        }, 300);
    }
```

This is the way we did in Form Component and used in many places
https://github.com/Expensify/App/blob/4af18f632511acbbebe7c9b1e8b26f44d871d1a9/src/components/Form.js#L301

### What alternative solutions did you explore? (Optional)

**Comment by jjcoffee** [comment] 2023-09-28 12:41
I'm leaning towards @namhihi237's [proposal](https://github.com/Expensify/App/issues/28195#issuecomment-1734452137) here as there isn't really any need to validate on blur in this case as we just have a single input (it also fixes the issue @DylanDylann mentions where the error shows when the app is put in the background). 

The alternative would be to refactor `PDFPasswordForm` to use `Form` (suggested [here](https://github.com/Expensify/App/issues/23552#issuecomment-1688606781)), which would take advantage of the fix in https://github.com/Expensify/App/issues/23552, but again I don't see that as super necessary since we really don't need to blur the input at all here.

 :ribbon::eyes::ribbon: C+ reviewed

**Comment by michaelhaxhiu** [comment] 2023-09-28 13:59
I'm re-assigning this to another BZ as part of my preparation for Sabbatical (starting Friday).

**Next steps:**
- @aldo-expensify will review and approve @jjcoffee's assessment, at which point we should assign a contributor 🤞 
- Await completion of the PR
- Pay the bug reporter / contributor / C+

**Comment by aldo-expensify** [comment] 2023-10-02 10:56
@namhihi237 can you leave a message in this GH issue so I can assigned it to you 🙏

**Comment by DylanDylann** [comment] 2023-10-02 11:19
@aldo-expensify i think the validation when blurring is a feature. Could we verify that before moving forward?

**Comment by aldo-expensify** [comment] 2023-10-02 11:34
@DylanDylann thanks for prompting me to check again. Looking at the problem again, this doesn't feel like a bug to me, it is just the validation validating correctly when the focus is lost from the input. I think we should just close this.

**Comment by aldo-expensify** [comment] 2023-10-02 11:35
I'm going to ask for a second opinion on slack, but my vote for now is :donothing

cc @NicMendonca

**Comment by DylanDylann** [comment] 2023-10-02 12:25
@aldo-expensify I have investigated using Form Component and I also have the same thought as you in [here](https://expensify.slack.com/archives/C01GTK53T8Q/p1696249291470599?thread_ts=1696246686.018609&cid=C01GTK53T8Q)

**Comment by aldo-expensify** [comment] 2023-10-02 12:26
From the slack conversation:

- We will fix this since we consider it a bug and we have already fixed it in other cases
- We already worked on this same problem for `Form` components, see https://github.com/Expensify/App/pull/24011 and the `setTimeout` that is there
- @DylanDylann 's [proposal](https://github.com/Expensify/App/issues/28195#issuecomment-1735229048) is consistent with the solution implemented in other cases [here](https://github.com/Expensify/App/pull/24011)

Maybe we want to use Form Component in PDF Password

**Comment by aldo-expensify** [comment] 2023-10-02 12:34
I'm a bit hesitant also because the existing fix for `Form` with `setTimeout` doesn't work well in all cases. For example:


https://github.com/Expensify/App/assets/87341702/ba6b0e46-3197-47e2-804d-b0b43392cabf



I think it doesn't work well here because the hide modal animation takes longer than the `200ms` defined here:

https://github.com/Expensify/App/blob/bba600a3f8a339f293e3a74b1e80398cb4e8bc67/src/components/Form.js#L355

**Comment by aldo-expensify** [comment] 2023-10-02 12:37
> since we're not using the form component here so there's no real benefit to re-implementing the same fix where we don't need to

True, also I see very little value on having the validation on `blur` and for me it would totally fine to have it only on `submit`. If we are ok with that, then @namhihi237 's proposal is much cleaner IMO.

**Comment by aldo-expensify** [comment] 2023-10-02 12:55
Ok, lets continue with @namhihi237 proposal. It makes the code simpler and will work good enough. Introducing `setTimeout` is a pattern we want to avoid if possible, it will also need more work to fix [this case](https://github.com/Expensify/App/issues/28195#issuecomment-1742950820) and just doing it to be consistent with the `Form` case is not enough reason to go with it.

Thanks @DylanDylann for raising questions about considering other approaches and investigating, but I think we are at a good point to make the decision and stop spending more time on this.

**Comment by NicMendonca** [comment] 2023-10-16 20:33
@jjcoffee bump on the BZ check list ^

**Comment by NicMendonca** [comment] 2023-10-16 20:39
everyone has been paid 🎉 @jjcoffee @namhihi237

**Comment by jjcoffee** [comment] 2023-10-17 10:59
- The PR that introduced the bug has been identified. Link to the PR: **N/A - behaviour always existed**
- The offending PR has been commented on, pointing out the bug it caused and why, so the author and reviewers can learn from the mistake. Link to comment: **N/A**
- A discussion in #expensify-bugs has been started about whether any other steps should be taken (e.g. updating the PR review checklist) in order to catch this type of bug sooner. Link to discussion: **N/A**
- Determine if we should create a regression test for this bug. **No - not really impactful enough**
- If we decide to create a [regression test](https://github.com/Expensify/App/blob/main/contributingGuides/REGRESSION_TEST_BEST_PRACTICES.md) for the bug, please propose the regression test steps to ensure the same bug will not reach production again.

**Comment by NicMendonca** [comment] 2023-10-17 15:05
all set here then!

**Closed by NicMendonca** 2023-10-17 15:05 UTC
Labels: External, Daily, Awaiting Payment, Bug
