### ISSUE TITLE
Web - Inbox - User has to click "Continue setup" CTA twice in olddot to display "Connect bank account" page in the right sidebar

### ISSUE THREAD

**Issue by kavimuru** [Expensify/App#8295] opened 2022-03-24 15:17 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___
Issue was found when executing #8257
## Action Performed:
1. Go to OldDot and sign up for a new account with an @gmail.com address
2. Click on the "Get started" on the inbox task that says "Would you like to get started with our free plan?".
3. Sign out of NewDot
4. Go back to the OldDot inbox and refresh the page
5. Click "Continue setup" on the inbox task that says "Finish setting up your bank account".

## Expected Result:
The Connect bank account page should open in the right sidebar

## Actual Result:
The Connect bank account page opens only on second click and refresh page.

## Workaround:
Unknown

## Platform:

Where is this issue occurring?

- Web

**Version Number:** v1.1.44-5

**Reproducible in staging?:** Y 

**Reproducible in production?:** Y

**Email or phone of affected tester (no customers):** 
**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Notes/Photos/Videos:** 
![Bug5504272_Screen_Shot_2022-03-24_at_10 00 35_AM](https://user-images.githubusercontent.com/43996225/159949295-143d6f22-63ac-4e3f-9386-ce511bb1eaca.png)

https://user-images.githubusercontent.com/43996225/159949299-d4dd8f30-14bf-42d5-b4e4-eec2210563cd.mp4

**Expensify/Expensify Issue URL:** 

**Issue reported by:** Applause

**Slack conversation:** 

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)
Issue was found when executing #8257

**Comment by MariaHCD** [comment] 2022-03-28 14:07
From the [logs](https://www.expensify.com/_devportal/tools/logSearch/#query=request_id:(%226f1042a0c9376393-LAX%22)+AND+timestamp:[2022-03-24T13:57:37.470Z+TO+2022-03-24T15:57:37.470Z]&index=logs_expensify-015966), the call to GetShortLivedAuthToken [here](https://github.com/Expensify/Web-Expensify/blob/b8a84dfe1ad6d71e12edb17f3dae55461252985b/site/lib/policyUtils.js#L233-L250) succeeded.
 
However, looks like the first few attempts to navigate to the bank account page didn't work ([logs](https://www.expensify.com/_devportal/tools/logSearch/#sort=asc&size=10000&query=blob%3A%22Not%20showing%20new%20bank%20account%20page%20because%20user%20is%20not%20on%20free%20plan%20beta%22%20AND%20email%3A%22rybkina%2B324fi%40gmail.com%22%20AND%20timestamp%3A%5B2022-03-14T00%3A00%20TO%202022-03-29T23%3A59%5D)):

```
Not showing new bank account page because user is not on free plan beta
```

Which is why we [redirected](https://github.com/Expensify/App/blob/b347866b2af95bd2c51eb6bb65098bd1d756e7d0/src/pages/ReimbursementAccount/ReimbursementAccountPage.js#L148-L152) back to OldDot. But it looks like the test account is on the free plan beta. Not sure what went wrong here.

cc: @TomatoToaster @madmax330 any ideas?

**Comment by neil-marcellini** [comment] 2022-03-31 21:29
>  But it looks like the test account is on the free plan beta.

@MariaHCD what makes you say that? How can we tell if they are on that beta? According to [this SO](https://stackoverflow.com/c/expensify/questions/5585) gmail.com accounts are not on the betas.

We only show "Continue to setup" if they are in the `FREE_PLAN_FULL_LAUNCH` beta. They are redirected from the bank account page if they are not in the `FREE_PLAN` beta. Is it possible that they are in the former and not the latter?

**Comment by MariaHCD** [comment] 2022-04-01 14:34
> How can we tell if they are on that beta? 

I used Supportal. The [list of the betas](https://github.com/Expensify/Web-Expensify/blob/4c6181f5210c7726758fcca7798e6cabc04ce14a/_support/index.php#L293) that are enabled for the user is displayed there. According to that list, the user is on both the freePlan and the frePlanLaunch betas.

**Comment by neil-marcellini** [comment] 2022-04-01 22:19
Ah ok awesome, thanks! I was planning to look at that yesterday but then my expensify.com account got screwed up. I'll keep investigating.

**Comment by neil-marcellini** [comment] 2022-04-04 18:37
👀

**Comment by neil-marcellini** [comment] 2022-04-04 20:04
I'm able to reproduce the problem on dev if I add these betas `[BetaManager::BETA_FREE_PLAN, BetaManager::BETA_FREE_PLAN_FULL_LAUNCH];` [here](https://github.com/Expensify/Web-Expensify/blob/31444587b13c5ec4ed0a3ebbce3b7ed828b9631a/lib/BetaManager.php#L102-L103), then prevent all betas from automatically being enabled on dev in NewDot [here](https://github.com/Expensify/App/blob/a671ac659f49157c6106c9ba1abbc7cbaf6cb975/src/libs/Permissions.js#L11), and then adding a delay to the loading of the betas. So the problem is that the betas are not loading by the time the ReimbursementsAccountPage loads.

**Comment by neil-marcellini** [comment] 2022-04-05 20:22
I've fixed the problem here where the user is immediately navigated back. However, when closing the RHN for the bank account page it still navigates back to OldDot, so I'm looking into that.

**Comment by neil-marcellini** [comment] 2022-04-08 21:49
I have no idea why this is happening. When [Navigation.goBack()](https://github.com/Expensify/App/blob/f0a4118a1b55673624f5f4a41ab39a6f49bc9b66/src/pages/ReimbursementAccount/BankAccountStep.js#L195) is called when the back button is pressed on the BankAccountStep page, the document is unloaded. I ran this snippet in the js console before pressing the back button `window.onbeforeunload = function(){ return 'Leave page?'; };`. If I hit cancel on the leave page alert, then I was able to see the navigation state change and the report page would display properly. It seems that something about the goBack method is navigating back in the browser history.

If I change the "Continue setup" button to open the link in a new tab then there is no problem. That could be a good work around for now. Maybe someone else knows what's going on here.

**Comment by neil-marcellini** [comment] 2022-04-11 16:59
The other flow that opens in the same tab, "Setup my company for free", has the same problem, but only if the 'X' button is clicked in the upper right, which calls dismissModal.
<img width="390" alt="image" src="https://user-images.githubusercontent.com/26260477/159349621-f1735fbf-034f-497e-8c2c-19317bf1fb9c.png" style="max-width: 100%;">

**Comment by neil-marcellini** [comment] 2022-04-18 20:29
I'm updating the PR for this issue to merge into the feature branch neil-transition-flows. Once all of the transition flows are working I will put up a PR to merge the feature branch into main.

**Comment by neil-marcellini** [comment] 2022-04-28 22:30
Under review and working on the transitions.

**Comment by neil-marcellini** [comment] 2022-05-06 20:55
Still under review for this Onyx PR [Set default key states when clearing the cache](https://github.com/Expensify/react-native-onyx/pull/129).

**Comment by neil-marcellini** [comment] 2022-05-16 21:21
I'm still working on this, trying to get this [new Onyx PR](https://github.com/Expensify/react-native-onyx/pull/129) merged in.

**Comment by mvtglobally** [comment] 2022-05-17 03:24
Issue not reproducible during KI retests. (First week)

**Comment by mvtglobally** [comment] 2022-05-24 04:24
Issue not reproducible during KI retests. (Second week)

**Comment by neil-marcellini** [comment] 2022-05-24 21:37
Sounds like this is currently not reproducible and I believe the previous PRs linked here have fixed it. I'm going to close this.

**Closed by neil-marcellini** 2022-05-24 21:37 UTC
Labels: Reviewing, Engineering, Daily, Improvement, Demolition, Internal
