### ISSUE TITLE
[$1000] The emoji picker menu overlaps the emoji picker button.

### ISSUE THREAD

**Issue by kavimuru** [Expensify/App#14401] opened 2023-01-18 22:04 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:

1 Write a multi-line message in the edit text input.
2 Click on the emoji picker button to choose an emoji.
3  Notice the emoji picker menu covers the emoji picker button.

## Expected Result:
The emoji picker menu shouldn't interfere with the emoji picker button.

## Actual Result:
The emoji menu overlaps and covers the emoji picker button.

## Workaround:
unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?

- [ ] MacOS / Chrome / Safari

**Version Number:** 1.2.56-0
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** 

https://user-images.githubusercontent.com/43996225/213305286-38688e95-ac78-4a59-8d20-d23822768505.mp4

https://user-images.githubusercontent.com/43996225/213305328-c08b0118-6f8a-4453-ab60-a9c6408d8445.mp4

**Expensify/Expensify Issue URL:**
**Issue reported by:** @karim-30
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1674048640389029

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01079388f45e32ad5a</li>
        <li>Upwork Job ID: 1616230985130721280</li>
        <li>Last Price Increase: 2023-01-20</li>
    </ul>
</details>

**Comment by strepanier03** [comment] 2023-01-20 00:14
### Bug0 Triage Checklist
_Note: see [this SO](https://stackoverflow.com/c/expensify/questions/14418) for more information._
- [ ] The "bug" is actually a bug 
- [ ] The bug is not a duplicate report of an existing GH.
  - If it is, close the GH and add any novel details to the original GH instead 
- [ ] The bug is reproducible, following the reproduction steps.
  - [ ] If the GH doesn’t have steps to reliably reproduce the bug and you figure it out, then please add them.
  - [ ] If you’re unable to reproduce the bug, add the `Needs reproduction` label. 
  - [ ] Comment on the issue outlining the steps you took to try to reproduce the bug, your results and tag the issue reporter and the Applause QA member who created the issue. Ask them to clarify reproduction steps and/or to check the reproduction steps again. Close issue. 
- [ ] The GH template is filled out as fully as possible
  - The GH body and title are clear (ie. could an external contributor understand it and work on it?) 
- [ ] The GH was created by an Expensify employee or a QA tester 
- [ ] If the bug is an OldDot issue, you should decide whether it is widespread enough to justify fixing or it is better to wait for reunification. If it’s better to wait, close the GH & provide this justification 
- [ ] If there's a link to Slack, check the discussion to see if we decided not to fix it 
- [ ] Decide if the GH should be resolved by an External contributor or Internal engineer, add the appropriate label

**Comment by strepanier03** [comment] 2023-01-20 00:28
Reminder for myself to bump the reporting [thread](https://expensify.slack.com/archives/C049HHMV9SM/p1674174382197099?thread_ts=1674048640.389029&cid=C049HHMV9SM) so we can get the bug reporter's GH handle.

**Comment by priyeshshah11** [comment] 2023-01-20 01:44
## Proposal

### Problem
We add the `width` of the `emojiPopoverAnchor` to move the EmojiPicker popover to the very right.

### Solution

We should remove the width from this line https://github.com/Expensify/App/blob/0bf7f51cf5070145125f2b3939892ec3f7c0cc34/src/components/EmojiPicker/EmojiPicker.js#L105
`this.emojiPopoverAnchor.measureInWindow((x, y) => resolve({horizontal: x, vertical: y}));`

**Comment by sobitneupane** [comment] 2023-01-20 03:51
I am not sure if this is really a bug. I don't mind emoji picker button blocked by emoji picker menu as it doesn't have any use case when emoji picker menu is opened.

cc: @neil-marcellini @strepanier03

**Comment by Karim-30** [comment] 2023-01-20 17:45
### Proposal

The edit emoji button should be at the bottom as we did in the Composer.

```diff
+++ b/src/styles/styles.js
@@ -1523,6 +1523,7 @@ const styles = {
 
     editChatItemEmojiWrapper: {
         marginRight: 3,
+        justifyContent: 'flex-end',
     },
 
     hoveredButton: {
```
![Screen Shot 2023-01-20 at 7 43 05 PM](https://user-images.githubusercontent.com/108357004/213770075-f487712f-a721-4ce1-abdc-ecc018740515.png)

**Comment by priyeshshah11** [comment] 2023-01-20 17:50
@Karim-30 Does that fix the issue when you edit the top most comment on the page?

**Comment by Karim-30** [comment] 2023-01-20 19:07
> Does that fix the issue when you edit the top most comment on the page?

@priyeshshah11 In this case we should shift the menu to the left when the gap between the button and the top is less than  (menu height + button height).

it will look like this.

https://user-images.githubusercontent.com/108357004/213784539-b468bdd2-989d-47ae-901c-363b782a982d.mov

```diff
+++ b/src/components/EmojiPicker/EmojiPicker.js
@@ -4,7 +4,12 @@ import _ from 'underscore';
 import EmojiPickerMenu from './EmojiPickerMenu';
 import CONST from '../../CONST';
 import PopoverWithMeasuredContent from '../PopoverWithMeasuredContent';
+import withWindowDimensions, {windowDimensionsPropTypes} from '../withWindowDimensions';
 
+const propTypes = {
+
+    ...windowDimensionsPropTypes,
+};
 class EmojiPicker extends React.Component {
     constructor(props) {
         super(props);
@@ -102,7 +107,10 @@ class EmojiPicker extends React.Component {
             if (!this.emojiPopoverAnchor) {
                 return resolve({horizontal: 0, vertical: 0});
             }
-            this.emojiPopoverAnchor.measureInWindow((x, y, width) => resolve({horizontal: x + width, vertical: y}));
+            this.emojiPopoverAnchor.measureInWindow((x, y, width) => {
+                const horizontal = !this.props.isSmallScreenWidth && (y < CONST.EMOJI_PICKER_SIZE.HEIGHT + 32) ? (x + width) - 32 : x + width;
+                resolve({horizontal, vertical: y});
+            });
         });
     }
 
@@ -172,4 +180,5 @@ class EmojiPicker extends React.Component {
     }
 }
 
-export default EmojiPicker;
+EmojiPicker.propTypes = propTypes;
+export default withWindowDimensions(EmojiPicker);
diff --git a/src/styles/styles.js b/src/styles/styles.js
index 71fed02015..de71bf2517 100644
--- a/src/styles/styles.js
+++ b/src/styles/styles.js
@@ -1523,6 +1523,7 @@ const styles = {
 
     editChatItemEmojiWrapper: {
         marginRight: 3,
+        justifyContent: 'flex-end',
     },
 
     hoveredButton: {
```

**Comment by Karim-30** [comment] 2023-01-20 19:46
### Updated Proposal
We don't need to check `isSmallScreenWidth` since the picker menu occupies the full width in small-screen devices.

```diff
+++ b/src/components/EmojiPicker/EmojiPicker.js
@@ -102,7 +102,10 @@ class EmojiPicker extends React.Component {
             if (!this.emojiPopoverAnchor) {
                 return resolve({horizontal: 0, vertical: 0});
             }
-            this.emojiPopoverAnchor.measureInWindow((x, y, width) => resolve({horizontal: x + width, vertical: y}));
+            this.emojiPopoverAnchor.measureInWindow((x, y, width) => {
+                const horizontal = y < CONST.EMOJI_PICKER_SIZE.HEIGHT + 32 ? (x + width) - 32 : x + width;
+                resolve({horizontal, vertical: y});
+            });
         });
     }
 ```
```diff
diff --git a/src/styles/styles.js b/src/styles/styles.js
index 71fed02015..de71bf2517 100644
--- a/src/styles/styles.js
+++ b/src/styles/styles.js
@@ -1523,6 +1523,7 @@ const styles = {
 
     editChatItemEmojiWrapper: {
         marginRight: 3,
+        justifyContent: 'flex-end',
     },
 
     hoveredButton: {
```

**Comment by strepanier03** [comment] 2023-01-20 23:04
@sobitneupane - Hmmm, thinking about your comment [here](https://github.com/Expensify/App/issues/14401#issuecomment-1397890954), I can see your point. 

I also do not mind the emoji picker button being covered because I'm either going to click on an emoji or click outside the emoji picture box to dismiss it, I'm not going to click the emoji picker icon button to dismiss it.

I'm going to bring this up in Slack to get a quick consensus on what we want to do here.

**Comment by strepanier03** [comment] 2023-01-23 19:11
We are going to close this GH and not "fix" this the behavior is not considered a bug.

**Closed by strepanier03** 2023-01-23 19:11 UTC
Labels: External, Daily, Help Wanted, Overdue, Bug
