### ISSUE TITLE
[HOLD #41020] New search - Console error shows up when returning to previous page from Hold request in RHP

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#41797] opened 2024-05-07 18:25 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.71-0
**Reproducible in staging?:** Y
**Reproducible in production?:** N
**If this was caught during regression testing, add the test name, ID and link from TestRail:** N/A
**Email or phone of affected tester (no customers):** applausetester+kh070501@applause.expensifail.com
**Issue reported by:** Applause - Internal Team

## Action Performed:
Precondition:
- User has some submitted some expenses
1. Go to staging.new.expensify.com
2. Go to Account settings > Troubleshoot
3. Click Navigate next to "New Search Page"
4. Click on the expense that does not have fake users
5. Click on the 3-dot menu > Hold expense
6. Click on the back button in RHP

## Expected Result:
No console error will show up

## Actual Result:
Console error shows up

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details> 

https://github.com/Expensify/App/assets/78819774/7851d29e-8b4b-42fa-90ce-55508f1840dc

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by lanitochka17** [comment] 2024-05-07 18:25
We think that this bug might be related to #vip-vsp

**Comment by lanitochka17** [comment] 2024-05-07 18:26
@thienlnam  FYI I haven't added the External label as I wasn't 100% sure about this issue. Please take a look and add the label if you agree it's a bug and can be handled by external contributors

**Comment by marcaaron** [comment] 2024-05-07 20:34
@thienlnam taking over since I see you working on some fire stuff

**Comment by marcaaron** [comment] 2024-05-07 20:36
@luacmartins given that this page appears to be only accessible from the staging debug menu I think we can remove the blocker, but maybe you'll want to add it to whatever milestone you've got for polish issues.

**Comment by luacmartins** [comment] 2024-05-07 21:13
Thanks for the ping @marcaaron! I think this issue is a subset of https://github.com/Expensify/App/issues/41020, but I think we can keep it open to make sure we resolve it as part of https://github.com/Expensify/App/issues/41020 as well.

**Comment by luacmartins** [comment] 2024-05-07 21:14
@marcaaron feel free to unassign yourself if you want to

**Comment by luacmartins** [comment] 2024-05-15 00:44
Still on hold

**Comment by luacmartins** [comment] 2024-05-21 05:57
Gonna move this to monthly since the holding issue is also put on hold until after the August release.

**Comment by miljakljajic** [comment] 2024-06-25 13:14
still holding

**Comment by luacmartins** [comment] 2024-06-27 15:50
This is no longer reproducible. Closing!

**Closed by luacmartins** 2024-06-27 15:50 UTC
Labels: Engineering, Monthly, Bug
