### ISSUE TITLE
[$500] [MEDIUM] LHN - Green dot(IOU) disappears from WS conversation in LHN when going offline-online

### ISSUE THREAD

**Issue by izarutskaya** [Expensify/App#33544] opened 2023-12-23 11:42 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.16-3
**Reproducible in staging?:** Y
**Reproducible in production?:** N
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** Applause-Internal Team
**Slack conversation:** @

## Action Performed:

⚠️ To reproduce you need an account that has the beta: `excludedFromReliableUpdates`.

1. Open New Expensify app
2. Log in with any account
3. Create new workspace
4. Request money on that workspace
5. Go to offline mode and after a few seconds return to online mode

## Expected Result:
The IOU green dot must be present in the LHN in any mode of operation until the IOU request is paid or an IOU error occurs.

## Actual Result:
The green dot IOU disappears from the LHN if the user goes offline and comes back online.

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [x] Android: mWeb Chrome
- [x] iOS: Native
- [x] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

https://github.com/Expensify/App/assets/115492554/de7c4828-3504-493c-8238-2a0a8fa1674b

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~019c2e500b47b7def2</li>
        <li>Upwork Job ID: 1738525487918645248</li>
        <li>Last Price Increase: 2024-01-31</li>
    </ul>
</details>

**Comment by paultsimura** [comment] 2023-12-23 12:40
First of all, this is not a deploy blocker – it's happening in prod as well:

<img width="865" alt="image" src="https://github.com/Expensify/App/assets/12595293/476b2a05-aa27-4414-a6cc-e36037843d0f">


We're potentially facing the **out-of-order Onyx updates** again:
When coming back online, 2 conflicting responses set `report.hasOutstandingChildRequest`:

**First** comes the `ReconnectApp` that sets it to `false` via the `mergeCollection` action:
<img width="1184" alt="image" src="https://github.com/Expensify/App/assets/12595293/20573cfe-1ac4-4a7e-bbd5-3247e47a61a7">

**Second** comes the `ReconnectToReport`, which should set the value to `true`, but this value is ignored. I suppose it gets overwritten by the `mergeCollection` from above similar to what was happening in https://github.com/Expensify/App/issues/28737

<img width="1066" alt="image" src="https://github.com/Expensify/App/assets/12595293/73ac6068-d91c-4cdd-87b2-f2bac2c6dd5d">

This particular issue can be fixed by making sure the `ReconnectApp` returns `report.hasOutstandingChildRequest: true` (which is correct), but the Onyx issue should be addressed as well.

cc: @Julesssss for the out-of-order updates

**Comment by aim-salam** [comment] 2023-12-25 01:44
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
The Green dot(IOU) should keep appear whether offline or online
( LHN - Green dot(IOU) disappears from WS conversation in LHN when going offline-online )

### What is the root cause of that problem?

=> OptionRowLHN.js

The component wrapped with <OfflineWithFeedback>

   <OfflineWithFeedback
            pendingAction={optionItem.pendingAction}
            errors={optionItem.allReportErrors}
            shouldShowErrorMessages={false}
            needsOffscreenAlphaCompositing
        >

### What changes do you think we should make in order to solve the problem?

Just unwrap/delete the <OfflineWithFeedback>

### What alternative solutions did you explore? (Optional)

**Comment by aim-salam** [comment] 2023-12-25 01:45
Contributor details
Your Expensify account email: aimsalam.com@gmail.com
Upwork Profile Link: https://www.upwork.com/freelancers/~0165dd5f4e0e952fdd

**Comment by Christinadobrzyn** [comment] 2023-12-29 19:19
I think we're reviewing propsals?

**Comment by paultsimura** [comment] 2023-12-29 19:32
I'd say we need a look from @Julesssss on https://github.com/Expensify/App/issues/33544#issuecomment-1868286445

**Comment by aldo-expensify** [comment] 2024-01-02 16:51
Considering @paultsimura 's investigation [here](https://github.com/Expensify/App/issues/33544#issuecomment-1868286445), I think it may be good to hold on https://github.com/Expensify/App/issues/32583 and check if https://github.com/Expensify/App/pull/32776 fixes this. That PR may help with avoiding fetching outdated Onyx updates.

**Comment by Julesssss** [comment] 2024-01-04 10:05
Just back from holiday. I agree with both [this](https://github.com/Expensify/App/issues/33544#issuecomment-1868286445) and Aldo's hold.

**Comment by Christinadobrzyn** [comment] 2024-01-04 21:49
okay! putting on hold until https://github.com/Expensify/App/issues/33544#issuecomment-1874280226 is complete to see if that resolves this issue. Moved this to weekly while we wait

**Comment by Christinadobrzyn** [comment] 2024-01-16 15:26
on hold until https://github.com/Expensify/App/issues/33544#issuecomment-1874280226 is complete

**Comment by Christinadobrzyn** [comment] 2024-01-23 21:52
PR https://github.com/Expensify/App/pull/32776 is in production

Testing this again based on the steps in the OP - this is still happening. 


https://github.com/Expensify/App/assets/51066321/8f6679e7-2cf5-4ee5-a2fc-ec059fd951e1

Should we continue with proposals @aldo-expensify?

**Comment by aldo-expensify** [comment] 2024-01-24 17:53
> Should we continue with proposals @aldo-expensify?

yes, I think we should

**Comment by alitoshmatov** [comment] 2024-01-25 07:18
No proposals yet, @paultsimura what do you think, can you provide a proposal to this issue?

**Comment by Christinadobrzyn** [comment] 2024-01-26 17:22
@alitoshmatov @aldo-expensify should we increase the bounty or is the payment sufficient for this job?

**Comment by paultsimura** [comment] 2024-01-29 19:37
@alitoshmatov @Christinadobrzyn I can no longer reproduce this on main. Could you please re-test?

**Comment by Christinadobrzyn** [comment] 2024-01-29 20:50
ah yep! I can't reproduce this either. I'll ask QA to test to see if we can close this.

**Comment by kbecciv** [comment] 2024-01-29 21:50
Issue is reproducible in our end, build 1.4.33.0

https://github.com/Expensify/App/assets/93399543/8e270d75-f98c-4a9e-a5c2-677d09594139

**Comment by Christinadobrzyn** [comment] 2024-01-29 23:18
Ah okay, thanks @kbecciv I can reproduce the same thing but if you remove the pin, the green dot will stay. So I think we want to figure out if the green dot or the pin should take precedent or what we want this to look like. 

asking the team. https://expensify.slack.com/archives/C01SKUP7QR0/p1706570242136159

**Comment by Christinadobrzyn** [comment] 2024-01-30 18:27
Okay, talking with the team https://expensify.slack.com/archives/C01SKUP7QR0/p1706570242136159 - we want this to be the behaviour - 

1. Open New Expensify app
2. Log in with any account
3. Create new workspace
4. **Verify** workspace is pinned
5. Request money on that workspace
6. **Verify** the workspace has a green dot now that Request Money has been made
8. Go to offline mode 
9. **Verify** the green dot still appears on the workspace with the Request Money
10. Go back online
11. Verify the workspace is Pinned and the green dot has disappeared

Expected result

The green dot continues to show because of the Request Money > on the backend the workspace should still be pinned. 

So @alitoshmatov & @aldo-expensify I think we do still want to fix this and change it so that the Pin is replaced with a green dot when coming back online. Thoughts?

**Comment by alitoshmatov** [comment] 2024-01-30 18:45
That sounds like plan, @paultsimura can you come up with proposal based on the above

**Comment by paultsimura** [comment] 2024-01-31 16:13
> That sounds like plan, @paultsimura can you come up with proposal based on the above

Unfortunately no, I still think this is an Onyx-related issue and don't see an FE-based solution

**Comment by Christinadobrzyn** [comment] 2024-01-31 18:16
Ah okay, should I change this to `Internal` or who could help with Onyx issues? Happy to reach out to them

**Comment by Christinadobrzyn** [comment] 2024-02-02 23:47
asking if someone at Software Mansion could take this on - https://expensify.slack.com/archives/C04878MDF34/p1706917632543559

**Comment by aldo-expensify** [comment] 2024-02-06 00:12
Thanks @paultsimura for the investigation [here](https://github.com/Expensify/App/issues/33544#issuecomment-1868286445). We were considering removing `ReconnectReport` completely but ran into a problem because of Onyx updates coming in the wrong order. I have to investigate the updates coming in wrong order, but maybe once that is fixed, then this issue will also be fixed.

https://github.com/Expensify/App/pull/34902

**Comment by aldo-expensify** [comment] 2024-02-06 00:19
> asking if someone at Software Mansion could take this on - https://expensify.slack.com/archives/C04878MDF34/p1706917632543559

I also think this is a backend issue, so I don't think Software Mansion will be able to help here.

**Comment by aldo-expensify** [comment] 2024-02-06 00:21
huh, extremely long search query: `	pbarker@expensify.com	Slow query (110010ms): WITH chatReports(reportID) A`, but it only happened once.

**Comment by BartoszGrajdek** [comment] 2024-02-06 13:33
Hi! I'm Bartosz from Software Mansion, I was working on this issue yesterday (I wanted to run a few more tests today) and I think that it may have been fixed with the whole navigation rework. Following [these steps](https://github.com/Expensify/App/issues/33544#issuecomment-1917644526) here's the result:

https://github.com/Expensify/App/assets/41169160/77ceee9a-cceb-44bc-be9f-88df8ccdc354

**Comment by aldo-expensify** [comment] 2024-02-06 18:06
oh, nice! thanks for taking a look @BartoszGrajdek

**Comment by aldo-expensify** [comment] 2024-02-09 23:06
👋  @BartoszGrajdek where you able to run more tests?

**Comment by BartoszGrajdek** [comment] 2024-02-12 09:34
Oh, I took it as if you didn't need any more help, so I just shared what I have found out. I tested out several scenarios with going online/offline and it really looks like it got fixed. I can investigate what might have fixed this problem if you want to - just let me know 😄

**Comment by aldo-expensify** [comment] 2024-02-12 19:35
> I can investigate what might have fixed this problem if you want to - just let me know 😄

No need @BartoszGrajdek , thank you again. If we can't reproduce, we can just close this.

**Comment by lanitochka17** [comment] 2024-02-12 22:10
Issue is still reproducible on the latest build 1.4.40-1


https://github.com/Expensify/App/assets/78819774/d1c7e690-8ed8-49fe-9949-b2df486282e4

**Comment by BartoszGrajdek** [comment] 2024-02-13 16:38
Well, that's strange. I tested it by trying both steps found [here](https://github.com/Expensify/App/issues/33544#issuecomment-1917644526) and [here](https://github.com/Expensify/App/issues/33544#issue-2054762674). I also tried it on multiple browsers just to be sure and I still couldn't reproduce the problem. 

Maybe I'm missing something, or this is some edge case and we still haven't figured out all the necessary steps. I'm attaching a video of how it behaves for me (build 1.4.40-4) @lanitochka17 let me know if there's anything I have done incorrectly there.

**Comment by aldo-expensify** [comment] 2024-02-13 19:16
For some reason I'm not being able to reproduce in `main` in my dev environment but I was able to reproduce in https://staging.new.expensify.com/


https://github.com/Expensify/App/assets/87341702/bf7f119b-d52d-4f6a-bfd1-37470664a238

**Comment by aldo-expensify** [comment] 2024-02-13 19:19
From looking at `ReconnectApp` and `OpenReport` response, I agree with @paultsimura 's findings [here](https://github.com/Expensify/App/issues/33544#issuecomment-1868286445) and it does look like `ReconnectApp` calculates `hasOutstandingChildRequest` incorrectly.

**Comment by aldo-expensify** [comment] 2024-02-13 19:28
Reproduced in dev, the key is that the account has to have the beta `excludedFromReliableUpdates`. Accounts under `expensifail.com` , `applause.expensifail.com` and some big domains have this, so I guess that explain why @BartoszGrajdek can't reproduce.

**Comment by aldo-expensify** [comment] 2024-02-13 20:15
I have a fix here https://github.com/Expensify/Auth/pull/9929, I just need to add the tests and I'll make it ready for review

**Comment by Christinadobrzyn** [comment] 2024-02-14 01:33
Yay! Exciting @aldo-expensify!

**Comment by aldo-expensify** [comment] 2024-02-14 20:29
PR was deployed

**Comment by aldo-expensify** [comment] 2024-02-14 20:48
Tested and now it is working:


https://github.com/Expensify/App/assets/87341702/b127904e-8271-41b6-95f0-b19132c03bf5

In the video we can see that the policyExpenseChat (reportID: 2130476157825373) comes with `hasOutstandingChildRequest: true` in `ReconnectApp`

**Closed by aldo-expensify** 2024-02-14 20:48 UTC
Labels: Reviewing, Engineering, Daily, Internal, Bug

**Comment by Christinadobrzyn** [comment] 2024-02-15 00:08
hey @aldo-expensify or @alitoshmatov do we need to pay out anyone for this?

**Comment by aldo-expensify** [comment] 2024-02-15 00:11
@Christinadobrzyn not as far as I know, the backend PR wasn't reviewed by C+
