### ISSUE TITLE
[HOLD for payment 2024-07-29][$250] Chat - Live markdown preview for Heading is not shown in the composer if space exist before

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#41908] opened 2024-05-09 13:08 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.72-0
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:** https://expensify.testrail.io/index.php?/tests/view/4547651
**Issue reported by:** Applause - Internal Team

## Action Performed:
1. Open ND Expensify
2. Navigate to any Chat
3. Enter a space and a header markdown text for example " space # Header "
4. Verify the preview
5. Send the text
6. Verify the message is shown as heading markdown

## Expected Result:
Live markdown preview for Heading (inside the composer) is shown if space is used before

## Actual Result:
If space is used before, Live Markdown preview for heading (inside the composer) is not shown. But it is correctly shown after the message is sent.
Note: -It is ok that if a character (except space) is used before, live markdown is not shown because the heading is not applied even after the message is sent.
-The same issue occurs also for Quotes markdown >

## Workaround:
Can the user still use Expensify without this being fixed? Have you informed them of the workaround?

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [x] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

https://github.com/Expensify/App/assets/93399543/921be3b0-bc4a-42f2-b784-970ca2438913

![image](https://github.com/Expensify/App/assets/93399543/91fa4225-5390-43ff-9ddf-636cc2b81dad)

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01e69db88132b2d1b4</li>
        <li>Upwork Job ID: 1788634876612800512</li>
        <li>Last Price Increase: 2024-05-30</li>
<li>Automatic offers: </li>
<ul>
<li>badeggg | Contributor | 102592680</li>
</ul></li>
    </ul>
</details>

**Comment by kbecciv** [comment] 2024-05-09 13:09
@sonialiap FYI I haven't added the External label as I wasn't 100% sure about this issue. Please take a look and add the label if you agree it's a bug and can be handled by external contributors.

**Comment by sonialiap** [comment] 2024-05-09 18:30
@Expensify/design I can reproduce, but do we think this is a bug we want to fix? The end result in both scenarios is that the heading formatting applies, it just doesn't show up in the preview if there's a space leading the hashtag 

https://github.com/Expensify/App/assets/17131195/81b17886-4e58-4cc5-b934-c67554ba1bba

**Comment by dannymcclain** [comment] 2024-05-09 19:55
Happy for others to weigh in too, but I feel like if it ends up as a header when you send it, we should reflect that in the composer.

**Comment by sonialiap** [comment] 2024-05-09 21:22
Sounds good to me

**Comment by dubielzyk-expensify** [comment] 2024-05-10 03:58
I believe we feel pretty strongly about making sure the editor at all times show what you send, so I wouldn't call it a huge priority, but I would say we should fix it.

**Comment by Afrin127329** [comment] 2024-05-10 05:56
Normal users(not developers) won't understand this markdown and they can get confused easily. So I would also suggest the fix.

**Comment by Afrin127329** [comment] 2024-05-10 06:06
Contributor details
Your Expensify account email: afrinnahar1999@gmail.com
Upwork Profile Link: https://www.upwork.com/freelancers/~0198fbe075b3e822ae

**Comment by sonialiap** [comment] 2024-05-15 00:47
@dragnoir I agree that this is not really a bug, but we have two design team members saying they'd like to have the composer accurately show what will be sent. Do you think it is not possible to have ` # header` show `# **header**` as it would without the leading space?

**Comment by sonialiap** [comment] 2024-05-15 21:35
@dragnoir that would be great! Would you like to make a proposal?

**Comment by badeggg** [comment] 2024-05-16 11:02
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
heading1 and quote does not show preview in composer box when prefix with one or more spaces.

### What is the root cause of that problem?
We have not consider this situation in expensify-common ExpensiMark lib. [heading1 here](https://github.com/Expensify/expensify-common/blob/18fa764be9d68f72b48d238dcc20f2b0ca8f1147/lib/ExpensiMark.js#L108) and [quote here](https://github.com/Expensify/expensify-common/blob/18fa764be9d68f72b48d238dcc20f2b0ca8f1147/lib/ExpensiMark.js#L243)

### What changes do you think we should make in order to solve the problem?
- We need amend few lines of https://github.com/Expensify/expensify-common/blob/main/lib/ExpensiMark.js to take care of prefixing space(s) in heading1 and quote case
  + [here](https://github.com/Expensify/expensify-common/blob/18fa764be9d68f72b48d238dcc20f2b0ca8f1147/lib/ExpensiMark.js#L111) change to
    ```
        const regexp = shouldKeepRawInput ? /^ *# ( *(?! )(?:(?!<pre>|\n|\r\n).)+)/gm : /^ *# +(?! )((?:(?!<pre>|\n|\r\n).)+)/gm;
    ```
  + [here](https://github.com/Expensify/expensify-common/blob/18fa764be9d68f72b48d238dcc20f2b0ca8f1147/lib/ExpensiMark.js#L250) change to
      ```
          const regex = /^ *(?:&gt;)+ +(?! )(?![^<]*(?:<\/pre>|<\/code>))([^\v\n\r]+)/gm;
      ```
  + [here](https://github.com/Expensify/expensify-common/blob/18fa764be9d68f72b48d238dcc20f2b0ca8f1147/lib/ExpensiMark.js#L268C21-L268C82) change to 
    ```
        const textToReplace = g1.replace(/^ *&gt;( )?/gm, handleMatch);
    ```
  + [here](https://github.com/Expensify/expensify-common/blob/18fa764be9d68f72b48d238dcc20f2b0ca8f1147/lib/ExpensiMark.js#L948) change to
    ```
        if (textSplitted[i].match(/^ *&gt;/) && !insideCodefence) {
    ```
  + [here](https://github.com/Expensify/expensify-common/blob/18fa764be9d68f72b48d238dcc20f2b0ca8f1147/lib/ExpensiMark.js#L995) change to
    ```
        const quoteContent = row.replace(/^ *&gt;(.*)/, '$1');
    ```
- Update expensify-common package version in [react-native-live-markdown parser](https://github.com/Expensify/react-native-live-markdown/blob/20305894e0d04cd224696780420eba7676659f92/parser/package.json#L23)
  + update expensify-common version
  + `npm run build`
  + publish react-native-live-markdown
- Update expensify-common package version and react-native-live-markdown package version in [Expensify/App](https://github.com/Expensify/App/blob/main/package.json)


### What alternative solutions did you explore? (Optional)
N/A

**Comment by allroundexperts** [comment] 2024-05-21 06:32
Still waiting for proposals here.

**Comment by allroundexperts** [comment] 2024-05-23 18:34
Not overdue. We are still waiting for proposals here.

**Comment by sonialiap** [comment] 2024-05-28 11:30
@allroundexperts what do you think of badeggg's update? https://github.com/Expensify/App/issues/41908#issuecomment-2114919703

**Comment by sonialiap** [comment] 2024-05-31 14:16
@allroundexperts what do you think of badeggg's update? https://github.com/Expensify/App/issues/41908#issuecomment-2114919703

**Comment by allroundexperts** [comment] 2024-06-01 20:09
@badeggg Can't we just update the regex inside the `parseMarkdownToHTML` function to ignore the whitespace? That seems much simpler option. What do you think?

**Comment by badeggg** [comment] 2024-06-01 23:55
That's my first think, and is actually my previous proposal. The test branch is [here](https://github.com/badeggg/expensify-common/tree/fix-41908-markdown-header)

The problem is that in react-native-live-markdown we will get ranges with shifted `start` value too, like we simply trim the leading spaces of the comment string. Related code [here](https://github.com/Expensify/react-native-live-markdown/blob/6541a6ea44785d3e3de8fc83ac085963fea30829/parser/index.ts#L244-L257). We still need to recover the shifted `start` value in ranges, which is more complicated compared to simply trim the leading spaces of a comment string. Since we will need do the same change to `parser/index.ts` like change to `parser/index.ts` in my current proposal, plus we adjusted the regex in `lib/ExpensiMark.js`.

After we recovering shifted `start` value, you'll realize we still need considering rendering problem in iOS and android, which will be the same concern and same code changes in my current proposal.

**Comment by allroundexperts** [comment] 2024-06-02 12:40
@badeggg I get that but, In [here](https://github.com/Expensify/expensify-common/compare/main...badeggg:expensify-common:fix-41908-markdown-header#diff-da44d2f545491c592bcca8c327495dee708dacf2263ac9b192807aab46874f04R109-R113), you can use a capture group to capture the spaces and add it in the replacement. That way, we won't have to store the ranges which sounds like a much more complex solution.

**Comment by badeggg** [comment] 2024-06-02 13:28
Hi, in [code here from react-native-live-markdown](https://github.com/Expensify/react-native-live-markdown/blob/6541a6ea44785d3e3de8fc83ac085963fea30829/parser/index.ts#L244-L247), we have to make sure `ranges` must describe the *original comment string* correctly, to render correctly. `html` `text` and `ranges` must have identical meaning.

If we change [here](https://github.com/Expensify/expensify-common/compare/main...badeggg:expensify-common:fix-41908-markdown-header#diff-da44d2f545491c592bcca8c327495dee708dacf2263ac9b192807aab46874f04R109-R113) to
```js
            {
                name: 'heading1',
                process: (textToProcess, replacement, shouldKeepRawInput = false) => {
                    const regexp = shouldKeepRawInput ? /^( *)# ( *(?! )(?:(?!<pre>|\n|\r\n).)+)/gm : /^( *)# +(?! )((?:(?!<pre>|\n|\r\n).)+)/gm;
                    return textToProcess.replace(regexp, replacement);
                },
                replacement: '<h1>$1$2</h1>',
            },

```
as you suggest, for example for input `    # dddd`(4 spaces before #), `ranges` will be 
```js
[
    {
        "type": "syntax",
        "start": 0,
        "length": 2
    },
    {
        "type": "h1",
        "start": 2,
        "length": 8
    }
]
```
which is not correct.
<img width="773" alt="image" src="https://github.com/Expensify/App/assets/10908996/deab0759-299c-4ddd-92a8-55965e60bb68">
Notice the rendering is not correct in the screen shot, `#` should not be bold.

**Comment by allroundexperts** [comment] 2024-06-02 13:31
Hm... Why are ranges incorrect? What should be the correct range?

**Comment by badeggg** [comment] 2024-06-02 13:35
For specific input `    # dddd`(4 spaces before #), the correct ranges should be:
```
[
    {
        "type": "syntax",
        "start": 4,
        "length": 2
    },
    {
        "type": "h1",
        "start": 6,
        "length": 4
    }
]
```

**Comment by allroundexperts** [comment] 2024-06-02 13:37
Why are the ranges not correct? I'm not able to understand that. We're not trimming the comment, and yet, still the ranges are incorrect?

**Comment by badeggg** [comment] 2024-06-02 13:47
By word `correct`, we mean the rendering system should be able to render as we expect bases on `ranges` object.

The meaning of an example ranges object:
```
[
    {  // this indicate the syntax sub-string, which should be not apply any specific style when render
        "type": "syntax",
        "start": 4,
        "length": 2
    },
    {  // this indicate the content of a syntax, which should be apply proper style of the syntax, e.g. for heading1, that's bold style
        "type": "h1",
        "start": 6,
        "length": 4
    }
]
```

I gently suggest you check the rendering logic in `react-native-live-markdown`, https://github.com/Expensify/react-native-live-markdown/tree/6541a6ea44785d3e3de8fc83ac085963fea30829

**Comment by badeggg** [comment] 2024-06-02 13:53
cc @sonialiap

**Comment by allroundexperts** [comment] 2024-06-04 15:15
Thanks for your explanation @badeggg. I've dig into it more and I agree with your proposal. Just ignoring the whitespace in the regex seems like a straightforward solution, but unfortunately, it doesn't work.

@badeggg's [proposal](https://github.com/Expensify/App/issues/41908#issuecomment-2114919703) looks good to me.

🎀 👀 🎀 C+ reviewed

PS: Regarding:

> That's too much. So maybe more bounty? Just saying...

I think the assigned internal engineer can consider your request. Although, I would agree that the solution is not so straight forward.

**Comment by badeggg** [comment] 2024-06-05 07:55
@luacmartins @allroundexperts Hi, how do you think about the flaw that I mentioned in the last section of [my proposal](https://github.com/Expensify/App/issues/41908#issuecomment-2114919703), I do think it's negligible:
> to implement quote rendering result 1, there is a inconsistency between iOS and web/android.(I do think it's negligible):
On android/web, we make a left-margin to glyph > to acquire room for filled rectangle drawing, while on iOS, we make a right-margin to the char before > to acquire room for filled rectangle drawing. I can not find a way to also make a left-margin to specific glyph in iOS. This will cause cursor in different place when it's between > and the char before >

Please check related screen shots in the original proposal.

**Comment by badeggg** [comment] 2024-06-05 08:01
@luacmartins And can you consider my [concern here](https://github.com/Expensify/App/issues/41908#issuecomment-2133178208) about the compensation.

**Comment by luacmartins** [comment] 2024-06-05 19:55
@badeggg I think the compensation for this issue is still fair at $250.

**Comment by badeggg** [comment] 2024-06-10 06:57
will make a pr in ~24 hrs

**Comment by badeggg** [comment] 2024-06-11 03:57
I have made [pr to react-native-live-markdown](https://github.com/Expensify/react-native-live-markdown/pull/382)
We will need update react-native-live-markdown version in `package.json` of expensify-app after it's published.

**Comment by luacmartins** [comment] 2024-06-17 22:39
PR is in review

**Comment by thienlnam** [comment] 2024-06-24 17:32
I took another look at the issue we're trying to solve, and think that that removing trimming whitespace from text inputs to solve this is actually a worse tradeoff.

I did this same markdown test in Discord and the same issue exists there
https://github.com/Expensify/App/assets/30609178/0da4491c-7324-4c86-9dcb-17f451003cae

After a second though, it seems like opening up a bunch of pre-pending or ending white space is not what we want to end up doing here.

I know others felt otherwise above, but curious for your thoughts? @dannymcclain / @dubielzyk-expensify

**Comment by luacmartins** [comment] 2024-06-26 20:45
@Expensify/design bump on the above

**Comment by shawnborton** [comment] 2024-06-26 21:01
@thienlnam what would your recommendation be then? I'm also starting to feel a bit lost on this one.

**Comment by thienlnam** [comment] 2024-06-27 12:52
Just to do nothing for this issue - the only problem that exists is if we start a message with spaces and add a header, the composer doesn't show it in live markdown, and if the trade-off is removing all whitespace stripping from the beginning of the message it doesn't seem worth it to solve that bug

```
    # Header
```

**Comment by dannymcclain** [comment] 2024-06-27 13:18
> if the trade-off is removing all whitespace stripping from the beginning of the message it doesn't seem worth it to solve that bug

Ok yeah, I agree with this and am fine with doing nothing.

**Comment by luacmartins** [comment] 2024-06-27 14:57
Ok, seems like we agree that we should do nothing and just close this then.

**Comment by thienlnam** [comment] 2024-06-27 15:06
Great, it seems we are in agreement on this. Let's also offer partial compensation like 50% for the pull requests since considerable effort was put into finding a solution, even though we ultimately chose a different direction.

**Comment by shawnborton** [comment] 2024-06-27 15:13
Works for me too, thanks for all of the discussion and effort put into this one!

**Comment by thienlnam** [comment] 2024-07-22 20:44
cc @sonialiap Could you please do payments for this based on https://github.com/Expensify/App/issues/41908#issuecomment-2194968151 so we can close this out?

**Comment by luacmartins** [comment] 2024-07-29 22:32
Bump @sonialiap

**Comment by sonialiap** [comment] 2024-07-30 13:56
Payment summary:
Per this comment https://github.com/Expensify/App/issues/41908#issuecomment-2194968151 paying 50% for effort put into resolving this before it was closed
- @badeggg $125 - offer sent in upwork ([job link](https://www.upwork.com/ab/applicants/1818284383323773882/job-details))
- @allroundexperts $125 - please request in ND

**Closed** 2024-08-02 11:52 UTC
Labels: External, Daily, Overdue, Awaiting Payment, Bug

**Comment by JmillsExpensify** [comment] 2024-08-21 11:11
$125 approved for @allroundexperts
