### ISSUE TITLE
[$250] [HOLD for payment 2024-04-05] [Simplified Collect][Taxes] - App crashes when opening Foreign currency default row after deleting the selected tax

### ISSUE THREAD

**Issue by izarutskaya** [Expensify/App#38931] opened 2024-03-25 12:19 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Found when executing PR :** https://github.com/Expensify/App/pull/38208

**Version Number:** 1.4.56-2
**Reproducible in staging?:** Y
**Reproducible in production?:** N
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Issue reported by:** Applause-Internal team

## Action Performed:
Precondition:
- User is admin of Collect workspace.
- There are a few tax rates in the Collect workspace.

1. Go to staging.new.expensify.com.
2. Go to Profile > Workspaces > Collect workspace.
3. Go to Taxes.
4. Click Settings > Foreign currency default > Select any tax rate.
5. Delete the tax rate selected in Step 4.
6. Click Settings > Foreign currency default.

## Expected Result:
App does not crash.

## Actual Result:
App crashes.

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [x] Android: mWeb Chrome
- [x] iOS: Native
- [x] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

https://github.com/Expensify/App/assets/115492554/976e1484-0024-4e37-83dc-c54af415e5ac

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Issue Owner</summary>Current Issue Owner: @alexpensify</details>
<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01e292bf5e67d0c666</li>
        <li>Upwork Job ID: 1776020973492867072</li>
        <li>Last Price Increase: 2024-04-04</li>
    </ul>
</details>

**Comment by izarutskaya** [comment] 2024-03-25 12:21
@alexpensify I haven't added the External label as I wasn't 100% sure about this issue. Please take a look and add the label if you agree it's a bug and can be handled by external contributors.


We think that this bug might be related to #wave-control.

**Comment by mountiny** [comment] 2024-03-25 12:24
Happy to take over since its related to simplified collect 

@ArekChr is going to look into this one

**Comment by ArekChr** [comment] 2024-03-25 12:25
Sure, happy to handle this issue!

**Comment by kosmydel** [comment] 2024-03-25 12:46
Hey, if needed we can check this issue as I with @filip-solecki was responsible for the Taxes feature. Just let me know, if we should investigate it.

**Comment by shahinyan11** [comment] 2024-03-25 15:14
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
Taxes - App crashes when opening Foreign currency default row after deleting the selected tax
### What is the root cause of that problem?
The Onyx data is not updated correct
### What changes do you think we should make in order to solve the problem?
Update [onyxData](https://github.com/Expensify/App/blob/9b142726f95e3279bfc1923fcd9c712b8f4a90a9/src/libs/actions/TaxRate.ts#L269C5-L315C7) like below 
```
const onyxData: OnyxData = {
        optimisticData: [
            {
                onyxMethod: Onyx.METHOD.MERGE,
                key: `${ONYXKEYS.COLLECTION.POLICY}${policyID}`,
                value: {
                    taxRates: {
                        foreignTaxDefault: policy?.taxRates?.defaultExternalID,
                        pendingFields: {foreignTaxDefault: CONST.RED_BRICK_ROAD_PENDING_ACTION.UPDATE},
                        errorFields: null,
                        taxes: taxesToDelete.reduce<TaxRateDeleteMap>((acc, taxID) => {
                            acc[taxID] = {pendingAction: CONST.RED_BRICK_ROAD_PENDING_ACTION.DELETE, errors: null};
                            return acc;
                        }, {}),
                    },
                },
            },
        ],
        successData: [
            {
                onyxMethod: Onyx.METHOD.MERGE,
                key: `${ONYXKEYS.COLLECTION.POLICY}${policyID}`,
                value: {
                    taxRates: {
                        pendingFields: {foreignTaxDefault: null},
                        errorFields: null,
                        taxes: taxesToDelete.reduce<TaxRateDeleteMap>((acc, taxID) => {
                            acc[taxID] = null;
                            return acc;
                        }, {}),
                    },
                },
            },
        ],
        failureData: [
            {
                onyxMethod: Onyx.METHOD.MERGE,
                key: `${ONYXKEYS.COLLECTION.POLICY}${policyID}`,
                value: {
                    taxRates: {
                        foreignTaxDefault: policy?.taxRates?.defaultExternalID,
                        pendingFields: {foreignTaxDefault: null},
                        errorFields: {foreignTaxDefault: ErrorUtils.getMicroSecondOnyxError('common.genericErrorMessage')},
                        taxes: taxesToDelete.reduce<TaxRateDeleteMap>((acc, taxID) => {
                            acc[taxID] = {
                                pendingAction: null,
                                errors: ErrorUtils.getMicroSecondOnyxError('workspace.taxes.errors.deleteFailureMessage'),
                            };
                            return acc;
                        }, {}),
                    },
                },
            },
        ],
    };
```

### What alternative solutions did you explore? (Optional)

**Comment by luacmartins** [comment] 2024-03-25 15:44
@ArekChr @filip-solecki are either of you available to investigate this one?

**Comment by filip-solecki** [comment] 2024-03-25 15:55
Sure, I can check it!

**Comment by luacmartins** [comment] 2024-03-25 15:59
Thanks! I think the solution involves:

1. Check if the taxes being deleted include the foreign tax default
2. If it does, we need to update the foreign tax default to the workspace default one
3. Update the pending action only for the foreign tax default field. The error will be shown on the deleted tax already, so no need to duplicate it here too

**Comment by luacmartins** [comment] 2024-03-25 15:59
I'm gonna demote this from being a blocker.

**Comment by shahinyan11** [comment] 2024-03-25 17:03
Doesn't anyone have any feedback on my proposal ?

**Comment by luacmartins** [comment] 2024-03-25 18:41
@shahinyan11 this was not made external yet since it's part of an ongoing project and the original authors of the PR should be fixing the issue.

**Comment by luacmartins** [comment] 2024-03-25 18:42
>In the Old Dot we have rule that the first tax from the list became Foreign tax default so do we want to keep it or do we want to use Workspace default tax?

We could keep it consistent for now and select the first one in the list.

**Comment by luacmartins** [comment] 2024-03-25 18:52
@filip-solecki when do you think you can get a PR up in review?

**Comment by filip-solecki** [comment] 2024-03-25 20:54
A few minutes 😄

**Comment by mountiny** [comment] 2024-03-29 22:29
$250 to @Ollyws

**Comment by alexpensify** [comment] 2024-04-04 22:57
@Ollyws - please apply to the job here: 

https://www.upwork.com/jobs/~01e292bf5e67d0c666

Tomorrow, I can complete the payment process. Thanks!

**Comment by alexpensify** [comment] 2024-04-05 21:10
@Ollyws - I sent an offer via Upwork, please accept and I can continue the payment process. Thanks!

**Comment by alexpensify** [comment] 2024-04-05 21:32
Payouts due:

- [ ] Contributor: @filip-solecki Payment handled via the vendor 
- [ ] Contributor+: $250 @Ollyws 

Upwork job is [here](https://www.upwork.com/jobs/~01e292bf5e67d0c666).

--- 

Closing, the payment process is complete in Upwork.

**Closed by alexpensify** 2024-04-05 21:32 UTC
Labels: Engineering, Weekly, Awaiting Payment, Bug
