### ISSUE TITLE
[HOLD for payment 2024-05-08] [HOLD for payment 2024-05-06] [$250] Track expense - Education video is displayed in public room when viewed anonymously

### ISSUE THREAD

**Issue by m-natarajan** [Expensify/App#41148] opened 2024-04-27 16:11 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.67-0
**Reproducible in staging?:** y
**Reproducible in production?:** no, new feature
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** applause internal team
**Slack conversation:** 
 
## Action Performed:
1. Go to staging.new.expensify.com
2. Log out if logged in.
3. Navigate to public room anonymously (https://staging.new.expensify.com/r/2376199970894587).
4. Go to FAB.
5. Click Track expense.
6. Click Got it.

## Expected Result:
The RHP should not be distorted

<img width="1140" alt="image" src="https://github.com/Expensify/App/assets/48188732/2dd0e27b-4d36-411d-905e-59ecf380a3b4">

## Actual Result:
After dismissing the modal, the RHP is distorted

<img width="1138" alt="image" src="https://github.com/Expensify/App/assets/48188732/92b5f771-09e5-4eba-bbca-26099502a539">

## Workaround:
unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [x] Android: mWeb Chrome
- [x] iOS: Native
- [x] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

https://github.com/Expensify/App/assets/38435837/0f6d2a8a-0a75-4e97-8475-477e88f3c08b

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01737d06f4b632dcb2</li>
        <li>Upwork Job ID: 1785022453427478528</li>
        <li>Last Price Increase: 2024-04-29</li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @allroundexperts</details>

**Comment by m-natarajan** [comment] 2024-04-27 16:12
@kevinksullivan FYI I haven't added the External label as I wasn't 100% sure about this issue. Please take a look and add the label if you agree it's a bug and can be handled by external contributors.

**Comment by m-natarajan** [comment] 2024-04-27 16:12
We think this bug might be related to #vip-vsb

**Comment by thienlnam** [comment] 2024-04-28 22:15
I don't think the issue is with showing the educational video, but why is the RHP distorted after dismissing the video. Could we address that issue?

**Comment by thienlnam** [comment] 2024-04-28 22:17
This also was added in https://github.com/Expensify/App/pull/40675
cc @tienifr @rushatgabhane @srikarparsi

**Comment by francoisl** [comment] 2024-04-29 17:39
@tienifr any idea on this one? 
Using the other options in the LHN like "Start Chat" or "Submit Expense" opens the sign-in RHP correctly, so I feel like it's really the modal with the video that makes it look distorted.

**Comment by srikarparsi** [comment] 2024-04-29 17:58
cc @rushatgabhane as well

**Comment by srikarparsi** [comment] 2024-04-29 19:16
Switching the order of these [seems](https://github.com/Expensify/App/blob/57e33ccfdce3cb0ca00e75d6992e7c76feea3354/src/pages/home/sidebar/SidebarScreen/FloatingActionButtonAndPopover.tsx#L325-L336) to work:

```
onSelected: () => {
                                      if (!hasSeenTrackTraining && !isOffline) {
                                          Navigation.navigate(ROUTES.TRACK_TRAINING_MODAL);
                                      }
                                      interceptAnonymousUser(() =>
                                          IOU.startMoneyRequest(
                                              CONST.IOU.TYPE.TRACK,
                                              // When starting to create a track expense from the global FAB, we need to retrieve selfDM reportID.
                                              // If it doesn't exist, we generate a random optimistic reportID and use it for all of the routes in the creation flow.
                                              // eslint-disable-next-line @typescript-eslint/prefer-nullish-coalescing
                                              ReportUtils.findSelfDMReportID() || ReportUtils.generateReportID(),
                                          ),
                                      );
                                  },
```

But, clicking got it or clicking the first click outside is clearing both modals and then subsequent clicks are unresponsive.

**Comment by srikarparsi** [comment] 2024-04-29 19:24
If we keep the order and add a 500ms timeout between the first and second, that also seems to work. Trying to find a better way to determine once the first navigate is finished animating.

**Comment by srikarparsi** [comment] 2024-04-29 19:49
Thanks @GandalfGwaihir, it does seem to be working but it takes over a 1s to show the video when 250ms is enough. Just feels a bit too slow. Do you know if there are any faster alternatives, that maybe check if less things are complete?

**Comment by srikarparsi** [comment] 2024-04-29 19:53
Internal conversation [here](https://expensify.slack.com/archives/C03TQ48KC/p1714419140332789) for progress.

**Comment by srikarparsi** [comment] 2024-04-29 20:06
Yeah, that's essentially what I originally had [here](https://github.com/Expensify/App/pull/41244/files) but I'm not sure if it's a good practice to use constant times, especially without testing. I see that we've done something similar [here](https://github.com/Expensify/App/blob/e6eb892e0ebe94ec63761906de3226fc3e52c059/src/components/OptionsSelector/BaseOptionsSelector.js#L371) but I'll wait a little longer to see if anyone has [other ideas](https://expensify.slack.com/archives/C01GTK53T8Q/p1714420292067339).

**Comment by srikarparsi** [comment] 2024-04-29 21:02
I think that makes sense since we also keep showing the video on every track expense until the user clicks "Don't show me this again" right. So I think it's fine that we're showing it twice since it'll be beneficial for anonymous new users.

**Comment by srikarparsi** [comment] 2024-04-30 06:07
Adding @allroundexperts for reviewing the [PR](https://expensify.slack.com/archives/C07J32337/p1714429081950169)

**Comment by srikarparsi** [comment] 2024-04-30 06:12
@tienifr and @rushatgabhane, we merged this fix [here](https://github.com/Expensify/App/pull/41244) but not sure if this is the best way to go about it. Do you guys have any other ideas that are more dependent on render/animation time rather than a constant timeout?

**Comment by kevinksullivan** [comment] 2024-05-08 18:06
Payment summary all set for @allroundexperts . Can you finish out the steps above and then I'll close this? Thanks!

**Comment by kevinksullivan** [comment] 2024-05-20 23:43
Waiting on @allroundexperts for the steps above

**Comment by srikarparsi** [comment] 2024-05-21 05:40
^

**Comment by allroundexperts** [comment] 2024-05-21 16:22
I don't think if a checklist is needed here. This was a bug with no definite root cause and as such, we just used a timeout to solve it. A regression test would be an overkill here as well.

**Comment by kevinksullivan** [comment] 2024-06-07 20:48
Payment summary:
- C+: @allroundexperts $250

**Closed by kevinksullivan** 2024-06-07 20:48 UTC
Labels: Engineering, Weekly, Awaiting Payment, Bug

**Comment by JmillsExpensify** [comment] 2024-06-28 17:29
$250 approved for @allroundexperts
