### ISSUE TITLE
[$500]  Unavailable workspace is shown in LHN and header for a new user

### ISSUE THREAD

**Issue by m-natarajan** [Expensify/App#29212] opened 2023-10-10 17:36 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.3.80-1
**Reproducible in staging?:** Yes
**Reproducible in production?:** Yes
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** @c3024 
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1696951775313699

## Action Performed:
1. Create a workspace from User A
2. Invite a User B who is not an Expensify member yet to this workspace
3. Login with User B (the new user who does not have an Expensify account yet) from another device
## Expected Result:
 Workspace chat on LHN and header of the workspace chat should show workspace name
## Actual Result:
Workspace chat on LHN and header of the workspace chat show “Unavailable Workspace”
## Workaround:
Unknown
## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [x] Android: mWeb Chrome
- [x] iOS: Native
- [x] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos
<details>
<summary>Android: Native</summary>

https://github.com/Expensify/App/assets/38435837/d79d520c-e426-4191-81ab-a56156b0761b

</details>

<details>
<summary>Android: mWeb Chrome</summary>

https://github.com/Expensify/App/assets/38435837/d9fef446-7f2b-4a79-af32-cf3d43586b7a

</details>

<details>
<summary>iOS: Native</summary>

https://github.com/Expensify/App/assets/38435837/3f5b150a-5538-4eeb-b4c8-67917fbdbfad

</details>

<details>
<summary>iOS: mWeb Safari</summary>

https://github.com/Expensify/App/assets/38435837/2eb411ad-11b1-4ddc-b921-1406e783b79c

</details>

<details>
<summary>MacOS: Chrome / Safari</summary>

https://github.com/Expensify/App/assets/38435837/1120ea38-5ffb-47fd-8ea3-ad7b2d4d554f

</details>

<details>
<summary>MacOS: Desktop</summary>

https://github.com/Expensify/App/assets/38435837/6d4d159a-af9f-41dc-b38b-b565eee61741

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~014d48a26dd4885d0a</li>
        <li>Upwork Job ID: 1711797907953733632</li>
        <li>Last Price Increase: 2023-11-07</li>
    </ul>
</details>

**Comment by deomaius** [comment] 2023-10-11 01:04
Inability to reproduce the bug on MacOS chrome web application and Electron builds, please clarify further input.

**Comment by c3024** [comment] 2023-10-11 01:12
@deomaius could you post the video?

**Comment by deomaius** [comment] 2023-10-12 07:37
# Proposal 

## Please re-state the problem that we are trying to solve in this issue.

Workspace details are insufficient for newly onboarded users once invited. 

## What is the root cause of that problem?

Failure to initialise the account's active policies to global state management and thus for the relative report the account indexes to, which resulted in insufficient metadata for apprioriate display. 

## What changes do you think we should make in order to solve the problem?

Simply merge all policies in Welcome.js before filtering for the workspace report via `workspaceChatReport`.

```
Onyx.mergeCollection(ONYXKEYS.COLLECTION.POLICY, allPolicies);
```

https://github.com/Expensify/App/blob/ae9f83fe54b35706ab52f9b994c407dcf110f97e/src/libs/actions/Welcome.js#L124-L129

**Comment by deomaius** [comment] 2023-10-12 07:38
> @deomaius could you post the video?

Ended up being able to reproduce on the native iOS build.

**Comment by arnaut08** [comment] 2023-10-12 12:42
# Proposal
## Please re-state the problem that we are trying to solve in this issue.
"Unavailable workspace" label is there instead of workspace name on the LHN and the chat header for a new user that was invited to the workspace.
## What is the root cause of that problem?
Policy for the workspace resets and the relevant fields are removed which causes `getPolicyName` to return "Unavailable workspace" instead of the workspace name.
## What changes do you think we should make in order to solve the problem?
We need to add the new properties to the existing policy instead of resetting it here:
https://github.com/Expensify/App/blob/9699988a0354e619b04d5b47c1b5b29936952c38/src/libs/ReportUtils.js#L69-L74

Here is a demo of the behaviour after the fix:
https://github.com/Expensify/App/assets/52157140/98a9b13e-d878-4736-9196-4cc6888d347c

**Comment by Architn08** [comment] 2023-10-12 12:44
# Proposal
## Please re-state the problem that we are trying to solve in this issue.
"Unavailable workspace" label is there instead of workspace name on the LHN and the chat header for a new user that was invited to the workspace.
## What is the root cause of that problem?
Policy for the workspace resets and the relevant fields are removed which causes `getPolicyName` to return "Unavailable workspace" instead of the workspace name.
## What changes do you think we should make in order to solve the problem?
We need to add the new properties to the existing policy instead of resetting it here:
https://github.com/Expensify/App/blob/9699988a0354e619b04d5b47c1b5b29936952c38/src/libs/ReportUtils.js#L69-L74

Here is a demo of the behaviour after the fix:
https://github.com/Expensify/App/assets/52157140/98a9b13e-d878-4736-9196-4cc6888d347c

**Comment by sourcecodedeveloper** [comment] 2023-10-12 19:39
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
Login with user A. Create workspace and logout. Login again with user A. Notice under Chats workspace name is unavailable also the chat header is unavailable.

### What is the root cause of that problem?
In ReportUtils.js, the callback for allPolicies is receiving partial data. It sends the workspace name in first half and then second time around it sends another set of data but skips the first half which has the workspace name. The callback should only be called once when it has both the sets of data.

### What changes do you think we should make in order to solve the problem?
In Policy.js, 

Add
```
        const policyID = key.replace(ONYXKEYS.COLLECTION.POLICY, '');
        Onyx.merge(`${ONYXKEYS.COLLECTION.POLICY}${policyID}`, val);
```


After, the allPolicies callback is only called 
```
{
    "autoReporting": true,
    "autoReportingFrequency": "immediate",
    "defaultBillable": false,
    "disabledFields": {
        "defaultBillable": true,
        "reimbursable": false
    },
    "isFromFullPolicy": false,
    "id": "605A84CA7CB2D40D",
    "name": "Hexv's Workspace",
    "role": "admin",
    "type": "free",
    "owner": "pplebyulofcbhd@hexv.com",
    "outputCurrency": "USD",
    "avatar": "",
    "employeeList": [],
    "isPolicyExpenseChatEnabled": true,
    "areChatRoomsEnabled": true,
    "lastModified": 1697129236345858
}

```


### What alternative solutions did you explore? (Optional)

**Comment by sourcecodedeveloper** [comment] 2023-10-16 12:13
@0xmiroslav please review [proposal](https://github.com/Expensify/App/issues/29212#issuecomment-1760259583)

**Comment by sourcecodedeveloper** [comment] 2023-10-17 16:19
@0xmiroslav please review [proposal](https://github.com/Expensify/App/issues/29212#issuecomment-1760259583)

**Comment by akamefi202** [comment] 2023-10-19 15:18
I'm not able to reproduce this issue anymore.

**Comment by sourcecodedeveloper** [comment] 2023-10-19 15:23
@0xmiroslav please review https://github.com/Expensify/App/issues/29212#issuecomment-1760259583

**Comment by deomaius** [comment] 2023-10-19 19:20
> @0xmiroslav please review [proposal](https://github.com/Expensify/App/issues/29212#issuecomment-1760259583)

Kindly please stop spamming the issue, let alone posting a proposal that is clearly plagiarism.

**Comment by deomaius** [comment] 2023-10-19 19:27
> Is this still reproducible?

You're a reviewer it's your job to investigate these questions, the point of interest related to this issue of the repository - has not changed - the assumption is, it is still reproducible. 

I do not have further time to commit unless authenticated to implementing the solution, I will remark this is the second occasion that makes me question committing to this organisation again.

**Comment by deomaius** [comment] 2023-10-25 16:00
2 weeks overdue actually, @c3024 anychance you could pass word to a higher up about the reviewer assigned to this issue and #29207. I am in the situation now of not contributing to this organisation again because of the treatment thus far.

**Comment by mvtglobally** [comment] 2023-10-27 00:48
Issue not reproducible during KI retests. (First week)

**Comment by deomaius** [comment] 2023-10-27 12:50
> Issue not reproducible during KI retests. (First week)

I imagine that's because of changes to the API to negate the issue, is the only feasbile consideration on how the issue is no longer present. I may say that is quite frustrating to someone who spent the time to find the source of conflict yet have been frontrun in a solution. 

I remain patient in a **sufficient** review to my proposals, yet the negligence is persistent here.

**Comment by mvtglobally** [comment] 2023-11-02 03:33
Issue not reproducible during KI retests. (Second week)

**Comment by mvtglobally** [comment] 2023-11-09 21:03
Issue not reproducible during KI retests. (Third week)

**Comment by c3024** [comment] 2023-11-09 22:59
It's not reproducible anymore.

**Comment by CortneyOfstad** [comment] 2023-11-13 15:20
Sounds good @0xmiroslav — thanks!

**Closed by CortneyOfstad** 2023-11-13 15:20 UTC
Labels: External, Daily, Help Wanted, Bug
