### ISSUE TITLE
Android - Xero - List quickly scrolls down when opening Xero bill payment account

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#52707] opened 2024-11-18 16:06 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 9.0.63-3
**Reproducible in staging?:** Y 
**Reproducible in production?:** Y
**If this was caught on HybridApp, is this reproducible on New Expensify Standalone?:** Y
**If this was caught during regression testing, add the test name, ID and link from TestRail:** https://expensify.testrail.io/index.php?/tests/view/5220819
**Email or phone of affected tester (no customers):** applausetester+214254435@applause.expensifail.com
**Issue reported by:** Applause - Internal Team

## Action Performed:
1. Go to staging.new.expensify.com
2. Go to workspace settings > Accounting
3. Connect to Xero
4. After connecting to Xero, click Advanced
5. Click Xero bill payment account
6. Scroll down and select an account at the bottom of the list
7. Click Xero bill payment account

## Expected Result:
The list will not scroll down every time Xero bill payment account is opened after selecting an account

## Actual Result:
The list quickly scrolls down every time Xero bill payment account is opened after selecting an account

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Standalone
- [x] Android: HybridApp
- [ ] Android: mWeb Chrome
- [ ] iOS: Standalone
- [ ] iOS: HybridApp
- [ ] iOS: mWeb Safari
- [ ] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

<details>
  <summary>Add any screenshot/video evidence</summary>

  
</details> 

https://github.com/user-attachments/assets/8b21ab63-c6c8-4626-b525-abcebdf3a0a4

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by OfstadC** [comment] 2024-11-20 18:12
Reviewing now...

**Comment by OfstadC** [comment] 2024-11-21 17:50
https://expensify.slack.com/archives/C06ML6X0W9L/p1732211443058909

**Comment by OfstadC** [comment] 2024-11-21 19:39
Confirmed in Slack that this is intended - Closing

**Closed by OfstadC** 2024-11-21 19:39 UTC
Labels: Daily, Bug
