### ISSUE TITLE
[HOLD for payment 2022-11-11] [$250] mWeb- Search -Focus and keyboard dismissed when start searching second user reported by @rushatgabhane

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#11801] opened 2022-10-13 14:40 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___
**Issue found when executing** https://github.com/Expensify/App/pull/11673

## Action Performed:
1. Go to staging.new.expensifail.com
2. Log in with your account
3. Select Fub menu - Select New Group
4. Type the user in search filed
5. Tap on the user
6. Go back to the search field
7. Search second user

## Expected Result:
Able to search second user without any issues

## Actual Result:
Focus and keyboard dismissed when start searching second user

## Workaround:
Unknown

## Platform:

Where is this issue occurring?

- Mobile Web

**Version Number:** 1.2.14.0

**Reproducible in staging?:** Yes

**Reproducible in production?:** Yes

**Email or phone of affected tester (no customers):** any

**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Notes/Photos/Videos:** Any additional supporting documentation

https://user-images.githubusercontent.com/93399543/195627326-dc5721cc-40ef-4eff-81bd-e81bf70911c7.mp4

**Expensify/Expensify Issue URL:** 

**Issue reported by:** [rushatgabhane](https://github.com/rushatgabhane)

**Slack conversation:** 

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by marcochavezf** [comment] 2022-10-13 17:25
I reproduced this error on Chrome (Android), for some reason seems it happens when the search input loses the focus, it's focused again and the user types something.

**Comment by mollfpr** [comment] 2022-10-14 06:37
### Proposal

_**Root cause**_
We scrolled the list whenever we select an option or the options list is changed.
https://github.com/Expensify/App/blob/7044ab2b96067081c8f67191e51fa859dba66d91/src/components/OptionsSelector/BaseOptionsSelector.js#L198

We also settings the `OptionList` to dismiss the keyboard when the list is scrolled.
https://github.com/Expensify/App/blob/7044ab2b96067081c8f67191e51fa859dba66d91/src/components/OptionsList/index.js#L11

So every time the scroll position is changed the keyboard will be dismissed.





_**Solution**_
Remove `keyboardDismissMode` and replace it with `onScroll` callback. We will dismiss the keyboard only when the user is touch scroll the list not when we scroll the list programmaticly.

```diff
diff --git a/src/components/OptionsList/BaseOptionsList.js b/src/components/Opti
onsList/BaseOptionsList.js
index c8337b87a..3fe0d31b7 100644
--- a/src/components/OptionsList/BaseOptionsList.js
+++ b/src/components/OptionsList/BaseOptionsList.js
@@ -17,12 +17,15 @@ const propTypes = {
     /** Called when the user begins to drag the scroll view */
     onScrollBeginDrag: PropTypes.func,

+    onScroll: PropTypes.func,
+
     ...optionsListPropTypes,
 };

 const defaultProps = {
     keyboardDismissMode: 'none',
     onScrollBeginDrag: () => {},
+    onScroll: () => {},
     ...optionsListDefaultProps,
 };

@@ -229,6 +232,7 @@ class BaseOptionsList extends Component {
                     indicatorStyle="white"
                     keyboardShouldPersistTaps="always"
                     keyboardDismissMode={this.props.keyboardDismissMode}
+                    onScroll={this.props.onScroll}
                     onScrollBeginDrag={this.props.onScrollBeginDrag}
                     contentContainerStyle={this.props.contentContainerStyles}
                     showsVerticalScrollIndicator={false}
```
```diff
diff --git a/src/components/OptionsList/index.js b/src/components/OptionsList/in
dex.js
index 7db02df56..1e0d535b3 100644
--- a/src/components/OptionsList/index.js
+++ b/src/components/OptionsList/index.js
@@ -1,16 +1,48 @@
-import React, {forwardRef} from 'react';
+import React, {forwardRef, useEffect} from 'react';
+import {Keyboard} from 'react-native';
 import BaseOptionsList from './BaseOptionsList';
 import withWindowDimensions from '../withWindowDimensions';
 import {propTypes, defaultProps} from './optionsListPropTypes';
+import canUseTouchScreen from '../../libs/canUseTouchscreen';

-const OptionsList = forwardRef((props, ref) => (
-    <BaseOptionsList
-        // eslint-disable-next-line react/jsx-props-no-spreading
-        {...props}
-        ref={ref}
-        keyboardDismissMode={props.isSmallScreenWidth ? 'on-drag' : 'none'}
-    />
-));
+let isScreenTouched = false;
+
+const OptionsList = forwardRef((props, ref) => {
+    useEffect(() => {
+        const onTouchStart = () => {
+            if (!canUseTouchScreen()) {
+                return;
+            }
+            isScreenTouched = true;
+        };
+
+        const onTouchEnd = () => {
+            isScreenTouched = false;
+        };
+
+        document.addEventListener('touchstart', onTouchStart);
+        document.addEventListener('touchend', onTouchEnd);
+
+        return () => {
+            document.removeEventListener('touchstart', onTouchStart);
+            document.removeEventListener('touchend', onTouchEnd);
+        };
+    }, []);
+
+    return (
+        <BaseOptionsList
+            // eslint-disable-next-line react/jsx-props-no-spreading
+            {...props}
+            ref={ref}
+            onScroll={() => {
+                if (!isScreenTouched) {
+                    return;
+                }
+                Keyboard.dismiss();
+            }}
+        />
+    );
+});

 OptionsList.propTypes = propTypes;
 OptionsList.defaultProps = defaultProps;
```

_**Result**_

https://user-images.githubusercontent.com/25520267/195778763-3b15a659-fb31-4167-8283-422aec851b4d.mov


https://user-images.githubusercontent.com/25520267/195778841-3bc859d4-98d9-4774-b7c0-f7291e5f7449.mp4

**Comment by sophiepintoraetz** [comment] 2022-10-17 20:05
@marcochavezf - does @mollfpr's proposal work here?

**Comment by eVoloshchak** [comment] 2022-10-18 15:50
@mollfpr's proposal looks good to me, works on mWeb correctly

🎀👀🎀 C+ reviewed!
cc: @marcochavezf 
The better approach would be to figure out how to disable onScroll callback when selecting an option, but I doubt that's viable

**Comment by marcochavezf** [comment] 2022-10-18 22:48
Thanks for the review @eVoloshchak and for the proposal @mollfpr! A few comments about the proposal: 

- I noticed `keyboardDismissMode` is removed, and [historically](https://github.com/Expensify/App/pull/6272/files) had the value `on-drag`. Do we test it in other places where `OptionsList` is used? I'm a bit worried that this could cause a regression, but if it's working fine in other places or we can confirm that this is not necessary, then we're good.
- We're not allowed to use [hooks](https://github.com/Expensify/App/blob/main/contributingGuides/STYLE.md#are-we-allowed-to-use-insert-brand-new-react-feature-why-or-why-not), could we update the proposal to use an alternative to `useEffect`?

Alternatively, I was wondering if another solution could be just setting `keyboardDismissMode="none"` for the search, thoughts?

**Comment by mollfpr** [comment] 2022-10-19 02:58
>I noticed keyboardDismissMode is removed, and [historically](https://github.com/Expensify/App/pull/6272/files) had the value on-drag. Do we test it in other places where OptionsList is used? I'm a bit worried that this could cause a regression, but if it's working fine in other places or we can confirm that this is not necessary, then we're good.

On native `keyboardDismissMode="on-drag"` is replaced with `onScrollBeginDrag` but for web `onScrollBeginDrag` is not available while `keyboardDismissMode="on-drag"` is also dismiss the keyboard when we scroll the view programmatically. My proposal is mimicking the `onScrollBeginDrag` usage on native to dismiss the keyboard only when the user is doing the scroll. I also try the proposal on `IOUParticipantsSplit` and it's working fine.

>We're not allowed to use [hooks](https://github.com/Expensify/App/blob/main/contributingGuides/STYLE.md#are-we-allowed-to-use-insert-brand-new-react-feature-why-or-why-not), could we update the proposal to use an alternative to useEffect?

We can convert the `OptionsList/index.js` from a functional component to a class component.

> Alternatively, I was wondering if another solution could be just setting keyboardDismissMode="none" for the search, thoughts?

Unfortunately, the keyboard is not dismissed when we scroll the view by dragging the screen.


cc @eVoloshchak @marcochavezf

**Comment by muttmuure** [comment] 2022-10-19 15:26
Since this one is getting more proposals I've closed the other and updated the job posting. 

The job is posted here: https://www.upwork.com/jobs/~01f1aaaefeb1b37071

**Comment by muttmuure** [comment] 2022-10-19 15:44
Done

**Comment by eVoloshchak** [comment] 2022-10-19 17:50
> * I noticed `keyboardDismissMode` is removed, and [historically](https://github.com/Expensify/App/pull/6272/files) had the value `on-drag`. Do we test it in other places where `OptionsList` is used? I'm a bit worried that this could cause a regression, but if it's working fine in other places or we can confirm that this is not necessary, then we're good.

I've tested it in other places, it mimics the previous behavior, so as long as all we need is to dismiss the keyboard on scroll, I think we're good
I'm not sure what's the correct behavior for each of the screens that use `OptionsList`, this one, for example, dismisses the keyboard after the user was selected, while this is not the case for the search screen. 

https://user-images.githubusercontent.com/9059945/196765542-f4f1d3ec-98f5-401a-94b3-b2de95f6ad6f.mov


Both of these scenarios are unaffected by @mollfpr's proposal, so nothing should change.

> Alternatively, I was wondering if another solution could be just setting `keyboardDismissMode="none"` for the search, thoughts?

We can, but the keyboard won't be dismissed when scrolling. Not sure if that's a big deal, but that would be inconsistent with the rest of the screens.

We could, however, wait for a better proposal since this one is a workaround technically

**Comment by mvtglobally** [comment] 2022-11-09 03:37
Issue not reproducible during KI retests. (First week)

**Comment by mollfpr** [comment] 2022-11-10 16:52
@muttmuure Applied to the job, thanks!

**Comment by mollfpr** [comment] 2022-11-14 03:50
bump @muttmuure

**Comment by muttmuure** [comment] 2022-11-14 19:51
Hired both @rushatgabhane as reporter you also need to apply

**Comment by muttmuure** [comment] 2022-11-15 16:32
@mollfpr has been paid. @rushatgabhane waiting for you to accept @eVoloshchak you still need to apply

**Comment by mvtglobally** [comment] 2022-11-16 02:17
Issue not reproducible during KI retests. (Second week)

**Comment by eVoloshchak** [comment] 2022-11-16 17:41
> @mollfpr has been paid. @rushatgabhane waiting for you to accept @eVoloshchak you still need to apply

Applied ✅

**Comment by muttmuure** [comment] 2022-11-17 22:37
Rushat paid. Just waiting for Eugene to accept and get paid then we can close.

**Comment by muttmuure** [comment] 2022-11-22 12:49
Everyone paid. Closing out

**Closed by muttmuure** 2022-11-22 12:49 UTC
Labels: Reviewing, External, Engineering, Daily, Awaiting Payment, Bug
