### ISSUE TITLE
[$250] Track expenses - Not here page displayed after trying to track another expense

### ISSUE THREAD

**Issue by izarutskaya** [Expensify/App#43265] opened 2024-06-07 11:58 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.80-9
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**If this was caught during regression testing, add the test name, ID and link from TestRail:** https://expensify.testrail.io/index.php?/tests/view/4605664
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Issue reported by:** Applause-Internal team

## Action Performed:
1. Open the app and log in
2. Tap FAB > Track expense
3. Enter amount and complete expense creation
4. Tap the FAB again > Track expenses

## Expected Result:
The BNP is opened and user can add another expenses

## Actual Result:
Hmm not here page is displayed

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

https://github.com/Expensify/App/assets/115492554/d5d8fba0-a282-446e-92bb-caab77cd49b7

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01456f04f812c99ae6</li>
        <li>Upwork Job ID: 1800135623299222302</li>
        <li>Last Price Increase: 2024-06-24</li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @eVoloshchak</details>

**Comment by izarutskaya** [comment] 2024-06-07 11:59
We think this issue might be related to the #collect project.

**Comment by Tony-MK** [comment] 2024-06-10 09:49
## Proposal

### Please re-state the problem that we are trying to solve in this issue.

Track expenses - Not here page displayed after trying to track another expense

### What is the root cause of that problem?

The root cause of the problem is when we check if the user has access to the page, the `canCreateRequest` function returns `false`. 

https://github.com/Expensify/App/blob/cd77d59942df0dd8e6b6468fab05eb6a8f2dd60f/src/pages/workspace/AccessOrNotFoundWrapper.tsx#L37

This is because `report.participants` array has an extra account ID linked to Expensify.

https://github.com/Expensify/App/blob/cd77d59942df0dd8e6b6468fab05eb6a8f2dd60f/src/libs/ReportUtils.ts#L5995

Therefore, when the `getMoneyRequestOptions` function is called,  `doParticipantsIncludeExpensifyAccounts` is `true`.

https://github.com/Expensify/App/blob/cd77d59942df0dd8e6b6468fab05eb6a8f2dd60f/src/libs/ReportUtils.ts#L5700-L5703

Hence, it returns an empty array of options the user can perform.

![Debug Screenshot](https://github.com/Expensify/App/assets/22982173/d0346f43-47d3-4380-adbb-5815f9ec3fde)

### What changes do you think we should make in order to solve the problem?


Let's use the `getParticipantAccountIDs` function to get the exact participant account IDs for the `getMoneyRequestOptions` function.

https://github.com/Expensify/App/blob/cd77d59942df0dd8e6b6468fab05eb6a8f2dd60f/src/libs/ReportUtils.ts#L5995

Therefore the changes to the line of code below should look like this.

```
const participantAccountIDs = getParticipantAccountIDs(report?.reportID ?? '');
```

### What alternative solutions did you explore? (Optional)

Remove the extra Expensify account in the `report.participants` array.

**Comment by sonialiap** [comment] 2024-06-10 11:59
Thanks for the bump @jainilparikh 🙏 added label and we have a C+

**Comment by sonialiap** [comment] 2024-06-18 13:06
@eVoloshchak what do you think of the above proposals?

**Comment by eVoloshchak** [comment] 2024-06-18 23:29
I can reproduce this on the Android app that is currently up on Play Market (`v1.4.83-3`), but unable to reproduce it with current app that's on `main` (`v1.4.85-2`)
@jainilparikh, @Tony-MK, could you please double-check if this is still reproducible for you?

**Comment by sonialiap** [comment] 2024-06-26 10:37
I've asked QA for a retest ([slack](https://expensify.slack.com/archives/C9YU7BX5M/p1719398252630739))

**Comment by kavimuru** [comment] 2024-06-26 16:45
@sonialiap Tester wasn't able to reproduce. 

https://github.com/Expensify/App/assets/43996225/00ce0a82-e9c7-4000-86bf-5595fa57c1b1


https://github.com/Expensify/App/assets/43996225/2b9f1e80-0ec1-4946-997e-9680a1ebd2be

**Comment by sonialiap** [comment] 2024-06-27 10:48
Thanks Kavi! 

Since neither Eugene nor Kavi were able to reproduce, I'm going to close this

**Closed by sonialiap** 2024-06-27 10:48 UTC
Labels: External, Daily, Help Wanted, Overdue, Bug
