### ISSUE TITLE
[HOLD for payment 2023-08-03] [$1000] Web -  Incorrect Redirection to Chat Page when Accessing /workspace/new-room URL

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#23067] opened 2023-07-18 10:35 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Log into any account and open any chat.
2. Change the URL in the browser to "https://staging.new.expensify.com/workspace/new-room" and press Enter.
3. Observe the page that is displayed.

## Expected Result:
The ''Hmm... it's not here'' page should be displayed, indicating the user has attempted to access an inaccessible URL.

## Actual Result:
The user is incorrectly redirected to the chat page, instead of being shown the ''Hmm... it's not here'' page.

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [x] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 1.3.40-5
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/93399543/3e137185-a525-4545-a123-cfe2cea1df2b

https://github.com/Expensify/App/assets/93399543/fdf70e3d-a62a-42f8-9d48-5d0c4e60127f

**Expensify/Expensify Issue URL:**
**Issue reported by:** @rayane-djouah
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1689468456062279

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~016da10a4664ea006b</li>
        <li>Upwork Job ID: 1681791241049214976</li>
        2023-07-19<li>Automatic offers: </li>
<ul>
<li> |  | 0</li>
<li>Ollyws | Contributor | 25717033</li>
<li>rayane-djouah | Reporter | 25717036</li>
</ul></li>
    </ul>
</details>

**Comment by jliexpensify** [comment] 2023-07-18 23:28
Is this fixed on v1.3.42-24? @kbecciv please re-test this one!

Here's what I see:

![image](https://github.com/Expensify/App/assets/30815269/868d3a13-ec18-4551-8d65-dff7bb85db6c)

**Comment by jliexpensify** [comment] 2023-07-19 22:08
@Ollyws and @rayane-djouah - thanks for letting me know!c I will re-test with a different account.

**Comment by jliexpensify** [comment] 2023-07-19 22:20
I'm seeing slightly different behaviour - I get an archived chat room. But I agree: this is an issue.

https://github.com/Expensify/App/assets/30815269/e58e4c9d-4df6-4fc1-8f02-ace659b86fcd

**Comment by Talha345** [comment] 2023-07-20 00:52
## Proposal

### Please re-state the problem that we are trying to solve in this issue.

User is redirected to chat page instead of showing 404 page.

### What is the root cause of that problem?

In the following code block, we are just returning null in Line 140 - 142  if the user does not have valid permissions due to which it redirects to the default opened report page.

https://github.com/Expensify/App/blob/ab3d0e876e311ed1ce3cd859ad6dd77a5d8e3cdf/src/pages/workspace/WorkspaceNewRoomPage.js#L132-L142

### What changes do you think we should make in order to solve the problem?

1. Remove this [line](https://github.com/Expensify/App/blob/ab3d0e876e311ed1ce3cd859ad6dd77a5d8e3cdf/src/pages/workspace/WorkspaceNewRoomPage.js#L137).
2. Return `<NotFoundPage/>` instead of `null` in [line 141](https://github.com/Expensify/App/blob/ab3d0e876e311ed1ce3cd859ad6dd77a5d8e3cdf/src/pages/workspace/WorkspaceNewRoomPage.js#L141).




### What alternative solutions did you explore? (Optional)

N/A


### Result:

<img width="1510" alt="image" src="https://github.com/Expensify/App/assets/36226639/aa718a86-cfed-4f02-8ed1-b24032d028d1">

**Comment by MariaHCD** [comment] 2023-07-24 11:44
@Ollyws's proposal looks good to me too. Assigned!

**Comment by jliexpensify** [comment] 2023-07-28 00:48
Payment Summary:

- Issue Reporter: @rayane-djouah $250
- Contributor: @Ollyws $1000
- C+: @allroundexperts $1000

Let me know if this is incorrect! Upworks job [here](https://www.upwork.com/jobs/~016da10a4664ea006b).

@allroundexperts bump to complete the checklist!

**Comment by jliexpensify** [comment] 2023-07-31 00:04
Cheers, checked and adjusted above

**Closed** 2023-08-04 01:35 UTC
Labels: External, Daily, Awaiting Payment, Bug

**Comment by JmillsExpensify** [comment] 2023-08-08 03:04
Reviewed the payment details for @allroundexperts. This is approved for payment on NewDot.
