### ISSUE TITLE
Search-Search result shows fallback avatar and email instead of custom avatar and display name

### ISSUE THREAD

**Issue by IuliiaHerets** [Expensify/App#51123] opened 2024-10-19 15:24 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 9.0.51-1
**Reproducible in staging?:** Y
**Reproducible in production?:** N
**Issue was found when executing this PR:** https://github.com/Expensify/App/pull/48652
**Email or phone of affected tester (no customers):** applausetester+kh081006@applause.expensifail.com
**Issue reported by:** Applause Internal Team

## Action Performed:
1. Go to staging.new.expensify.com
2. Click on the search icon in any report.
3. Enter an email address that has custom avatar and display name.

## Expected Result:
The search result will show user with custom avatar and display name.

## Actual Result:
The search result shows user with fallback avatar and email address as display name instead of custom avatar and custom display name.

## Workaround:
Unknown

## Platforms:

- [x] Android: Standalone
- [x] Android: HybridApp
- [x] Android: mWeb Chrome
- [ ] iOS: Standalone
- [ ] iOS: HybridApp
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

https://github.com/user-attachments/assets/b94533a2-09b9-4c17-87fe-b327d9673e97

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by hannojg** [comment] 2024-10-21 05:17
Hey, I was responsible for the accused PR. Feel free to assign this to me I can look into it today!

**Comment by hannojg** [comment] 2024-10-21 08:20
Hm, i can neither reproduce this on staging or latest dev commit:


https://github.com/user-attachments/assets/4722535e-fcc7-4ff9-9ad7-d40b48934b6d

The PR hasn't changed anything about how we display search results, it just changed how we filter for them. So i am not really sure if the PR could've caused such behaviour.

**Comment by MarioExpensify** [comment] 2024-10-21 11:41
I also cannot reproduce here, either from the Desktop or the WebApp, both react to the search the same as Production App. 
Maybe we could get this retested?

![image](https://github.com/user-attachments/assets/25e32bbd-5cd5-408d-a121-a2ddefba23eb)

**Comment by izarutskaya** [comment] 2024-10-21 13:47
Still reproducible on staging 
Build v9.0.51-2
And different behavior in production 

https://github.com/user-attachments/assets/8a1fe034-45dd-4771-909a-2b7862f7fe10

https://github.com/user-attachments/assets/0d899ea6-1a1e-4724-a1b3-0d22929e287c

**Comment by MarioExpensify** [comment] 2024-10-21 14:13
Hey @hannojg, mind taking another look? I looked through other PRs and did not find any other that may be the cause for this issue. Feel free to reach me out if you think it is unrelated to your latest changes.

**Comment by isabelastisser** [comment] 2024-10-25 19:42
Not overdue; it looks like we still working on the PR.

**Comment by isabelastisser** [comment] 2024-10-29 19:29
Bump @hannojg. Thanks!

**Comment by isabelastisser** [comment] 2024-10-30 18:47
### Heads up, I will be OOO from Oct 31 until Nov 4, so please re-apply the Bug label and assign a new member if needed. Thanks!

**Comment by hannojg** [comment] 2024-11-04 08:53
Guys sorry, this completely slipped past me! I will take another look at that one this week!

**Comment by hannojg** [comment] 2024-11-05 08:19
Okay, so after investigating this, this isn't a problem with the PR originally mentioned:

 - https://github.com/Expensify/App/pull/48652

The problem seems to be that sometimes you get a 407 error for the search query, thus we are not getting any data from the backend:

![CleanShot 2024-11-04 at 17 57 16](https://github.com/user-attachments/assets/146c2fb7-48d6-4395-bcb9-df245533cad1)

We can see from the screenshot that the network command for the search was fired before the user got re-authenticated.

I originally got assigned to this issue because it was suspected that my PR caused this issue - which it didn't. Our team (margelo) can look into the issue if you like nevertheless, or you can make it external i think.

**Comment by isabelastisser** [comment] 2024-11-05 19:43
@hannojg, thanks for the update! Can you please continue to work on this issue? Thanks!

**Comment by hannojg** [comment] 2024-11-06 16:26
@chrispader can you comment here? Chris from the Margelo team will work on a fix for this ticket (as i am very busy with other tasks rn).

**Comment by chrispader** [comment] 2024-11-06 16:34
commenting for assignment :)

**Comment by isabelastisser** [comment] 2024-11-07 14:53
hey @chrispader, I just assigned you. Thanks!

**Comment by marcaaron** [comment] 2024-11-23 01:41
@chrispader do you have an update for this one? 

My understanding is that the `Reviewing` label should not have been applied and nobody is working on this yet.

**Comment by isabelastisser** [comment] 2024-11-25 15:26
Hey @chrispader, can you please follow up on the questions above? Thanks!

**Comment by chrispader** [comment] 2024-11-25 19:06
Hey sorry for the massive delay! I was totally busy on another PR 🫠

I investigated the problem and can **clearly reproduce the problem** for a particular set of accounts/email addresses.

### Problem

The problem essentially is, that the response received from the backend for `SearchForReports` sometimes returns a `login` (email) property in the fetched (to-be merged) `personalDetails`, whereas **sometimes not**.

If no `login` property is provided in the response from the backend, the personal details option received from [`useOptionsList()`](https://github.com/Expensify/App/blob/c7fc577bfb7829858210fc66853ab370a60cc615/src/components/Search/SearchRouter/SearchRouter.tsx#L75) will not have a `login` property and therefore the logic in [`OptionsListUtils.filterOptions()`](https://github.com/Expensify/App/blob/c7fc577bfb7829858210fc66853ab370a60cc615/src/libs/OptionsListUtils.ts#L1780-L1783) is not able to match it to the email that the user types in the search field.

Because the logic couldn't find any personal details item, we will just add a "blank" options list item to the options list and  therefore the default avatar is used.

### Solution

Because of this i would argue that this is a backend issue and the `SearchForReports` should **always** return a `login` property for the Onyx key `personalDetailsList_`. Looking into the local Onyx DB, we also don't really have any other data to match  the (typed in) email address to the personal details, except for the name (could be ambiguous) or the account ID, where we would have to do a very compley and costly lookup.

### Backend responses for different accounts/email addresses and Onyx DB screenshot

- `yonghongkok2@gmail.com`: (same as in the repro video)

![Screenshot 2024-11-25 at 19 44 11](https://github.com/user-attachments/assets/4ea53fbf-2b32-422a-a679-cfc9f8e4ea34)

- `hanno@margelo.com`:

![Screenshot 2024-11-25 at 19 43 49](https://github.com/user-attachments/assets/c55aeba4-1732-4440-8f32-923f5f5ef0c2)

- Onyx DB `personalDetailsList_` key:

![Screenshot 2024-11-25 at 19 59 25](https://github.com/user-attachments/assets/7b2dde2e-f8e7-4c41-a76d-b970eb3e2b56)

**Comment by chrispader** [comment] 2024-11-25 19:08
I don't think it is on purpose, that the backend sometimes doesn't send a `login` property right? Or am i missing something here?

**Comment by marcaaron** [comment] 2024-11-26 00:28
AFAICT there's really only one case where we would not return a `login` in the `personalDetail`.

There is a property called `isKnownUser` and if it's `false` then no `login` is returned (actually a few other fields will not be returned either `pronouns`, `timezone`, `phoneNumber` and `validated`). Internal code [here](https://github.com/Expensify/Auth/blob/52af561b2f2e8b0b9870f6069b93ab523bb8b532/auth/lib/Account.cpp#L3262-L3272).

I think this feature is working as intended. @puneetlath worked on this and can give a second opinion. But my guess for this issue based on the evidence provided is that we didn't make the connection to `isKnownUser` feature.

**Comment by chrispader** [comment] 2024-11-26 19:34
> That sounds correct to me. You should get the full personal details, including login, when you "know" someone. You should get the partial personal details when you don't.

Ok i understand. Does that mean, that since we don't receive these infos, we also don't want to show things like the avatar? 

Without the email, address we cannot really match it with the search input... e.g. when i'm searching for an email address of a user i "don't know", e.g. "yonghongkok2@gmail.com", we receive the missing data like avatar and name from the `SearchForReports` query, but cannot match it with the mail address.

**Comment by marcaaron** [comment] 2024-11-26 21:08
I think what is being reported is probably fine and we should close this out (but seems like it could reopen again as a suspected bug). We could maybe improve the UX so that "not known" users show up with a `?` avatar or something, but I don't feel strongly about prioritizing this right now.

**Comment by isabelastisser** [comment] 2024-12-05 20:25
Closing this!

**Closed by isabelastisser** 2024-12-05 20:25 UTC
Labels: Engineering, Weekly, Overdue, Bug
