### ISSUE TITLE
[Pay on 6/16] [$250] Inconsistent position of the maximum number of participants reached message on different screens - reported by @adeel0202

### ISSUE THREAD

**Issue by mvtglobally** [Expensify/App#8847] opened 2022-05-02 06:09 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Press + icon
2. Select New group
3. Choose 8 participants
4. Observe that the maximum number of participants reached message is on top
5. Press + icon
6. Select Split bill
7. Enter any amount and press Next
8. Choose 8 participants
9. Observe that the maximum number of participants reached message is on bottom

## Expected Result:
The position of maximum number of participants reached message should be consistent

## Actual Result:
The position of maximum number of participants reached message is not consistent

## Workaround:
unknown 

## Platform:

Where is this issue occurring?

- Web
- iOS
- Android
- Desktop App
- Mobile Web

**Version Number:** 1.1.57-0
**Reproducible in staging?:** Y 
**Reproducible in production?:** Y 
**Email or phone of affected tester (no customers):** 
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation 
![Split bill message](https://user-images.githubusercontent.com/43995119/166191762-3cc9ecd3-1a2c-4c83-9dd4-7858f18c46d2.jpg)
![New group message](https://user-images.githubusercontent.com/43995119/166191763-e27d80ce-02cb-4f2b-b7b7-08c336caef60.jpg)

**Expensify/Expensify Issue URL:** 
**Issue reported by:** @adeel0202
**Slack conversation:** https://expensify.slack.com/archives/C01GTK53T8Q/p1649272255080289

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by adeel0202** [comment] 2022-05-02 07:01
**Proposal (If External)**
_(Early as I reported the issue)_

On `NewChatPage`, we can remove `maxParticipantsReached` from `line 221`
https://github.com/Expensify/App/blob/f174c3223a1d6d0f571e5bd799441690951f078c/src/pages/NewChatPage.js#L217-L222

And add the message text inside the `FixedFooter` component on `line 271` like this
```
{maxParticipantsReached && (
    <Text style={[styles.textLabelSupporting, styles.textAlignCenter, styles.mt1, styles.mb3]}>
        {this.props.translate('iou.maxParticipantsReached', {count: CONST.REPORT.MAXIMUM_PARTICIPANTS})}
    </Text>
)}
```
We can also move the `iou.maxParticipantsReached` to `common.maxParticipantsReached`, so that the same error message is used on `New group chat` screen and `Split bill` screen.  This will require replacing `iou.maxParticipantsReached` to `common.maxParticipantsReached` on `IOUParticipantsSplit`'s `line 239` as well.

**Comment by Tushu17** [comment] 2022-05-02 09:39
### Proposal 

We have different message for maximum group participants. so instead of using `iou.maxParticipantsReached` we should use `messages.maxParticipantsReached`.

To solve the issue:- 

We can remove message from the header by removing line 221 
https://github.com/Expensify/App/blob/fc3e13ea735874b4223b3ce2a88cc03e83ec9ee7/src/pages/NewChatPage.js#L219-L222

then we just need to add 

```
{maxParticipantsReached && (
<Text style={[styles.textLabelSupporting, styles.textAlignLeft, styles.mt1, styles.mb3]}> 
{this.props.translate('messages.maxParticipantsReached')}
</Text>
 )}
```
below line 270
https://github.com/Expensify/App/blob/fc3e13ea735874b4223b3ce2a88cc03e83ec9ee7/src/pages/NewChatPage.js#L269-L271

**Comment by Beamanator** [comment] 2022-05-02 17:12
Confirmed this bug currently exists 👍 Marking `External`

**Comment by adeel0202** [comment] 2022-05-02 18:47
**Update Proposal** (since in [thread](https://expensify.slack.com/archives/C01GTK53T8Q/p1649272255080289), the team decided to show the message below the search field)

In `IOUParticipantsSplit`, we can pass the `maxParticipantsReached` boolean to `OptionsListUtils`'s `getHeaderMessage` method, like this
```
const headerMessage = OptionsListUtils.getHeaderMessage(
            this.state.personalDetails.length + this.state.recentReports.length !== 0,
            Boolean(this.state.userToInvite),
            this.state.searchValue,
            maxParticipantsReached,
        );
```

Then in `getHeaderMessage` method, instead of using `messages.maxParticipantsReached` _(You've reached the maximum number of participants for a group chat.)_, we can use a common message `common.maxParticipantsReached` _(You've selected the maximum number (${count}) of participants.)_
We can then remove the unused `messages.maxParticipantsReached` and `iou.maxParticipantsReached` from translation files.

Also we can remove this code inside `IOUParticipantsSplit`'s `FixedFooter` because we won't need it anymore
```
{maxParticipantsReached && (
  <Text style={[styles.textLabelSupporting, styles.textAlignCenter, styles.mt1, styles.mb3]}>
      {this.props.translate('iou.maxParticipantsReached', {count: CONST.REPORT.MAXIMUM_PARTICIPANTS})}
  </Text>
)}
```

**Outputs**
<img width="367" alt="Screenshot 2022-05-02 at 11 45 51 PM" src="https://user-images.githubusercontent.com/13783842/166306662-578d8b75-b5a1-42cd-8d9b-412210bfa439.png">
<img width="363" alt="Screenshot 2022-05-02 at 11 46 13 PM" src="https://user-images.githubusercontent.com/13783842/166306704-28291726-39a6-4088-9aae-f5fd64b3b69d.png">

**Comment by bfitzexpensify** [comment] 2022-05-03 02:18
Upwork job [here](https://www.upwork.com/jobs/~01bf77086c3e197389)

**Comment by bfitzexpensify** [comment] 2022-05-12 02:52
Looks like we have a couple of proposals for review - be great to have your eyes on this one when you get a chance @rushatgabhane!

**Comment by rushatgabhane** [comment] 2022-05-12 02:54
@bfitzexpensify sorry but I'm OOO till May 14.
Please assign this issue to @mananjadhav for a review as per this thread https://expensify.slack.com/archives/C02NK2DQWUX/p1652282380139939?thread_ts=1652277963.845719&cid=C02NK2DQWUX

**Comment by bfitzexpensify** [comment] 2022-05-12 04:38
All good @rushatgabhane - hope you're enjoying your time off!

**Comment by Beamanator** [comment] 2022-05-12 08:44
Adding `Help Wanted` & hid the bot post b/c this job **has not been assigned yet** :D

@mananjadhav since you're the new C+ on this issue would you please review the proposals above? 👍

**Comment by mananjadhav** [comment] 2022-05-12 18:48
Give me time until tomorrow I'll review them.

**Comment by Beamanator** [comment] 2022-05-17 10:28
@mananjadhav Please let me know if you're unable to review and we can add a different C+ 👍

**Comment by mananjadhav** [comment] 2022-05-18 04:23
Apologies for the delay @Beamanator

@adeel0202's updated proposal https://github.com/Expensify/App/issues/8847#issuecomment-1115240721 is good to go 

🎀 👀 🎀 
C+ reviewed

**Comment by Beamanator** [comment] 2022-05-18 08:50
Thanks @mananjadhav - I agree it looks great 👍

**Comment by adeel0202** [comment] 2022-05-23 06:47
@Beamanator, I'm getting errors on API calls in android and web (please refer to [this thread](https://expensify.slack.com/archives/C01GTK53T8Q/p1652066886829219)). I can raise the PR but I will only be able to attach screenshots for iOS and desktop app. Will that work?
cc: @mananjadhav

**Comment by adeel0202** [comment] 2022-05-23 06:52
Note: Since I'm already signed into the web app so I think I will be able to provide web screenshots too, however, I'm not signed into the android app and I get [error](https://expensify.slack.com/archives/C01GTK53T8Q/p1652889702792369?thread_ts=1652066886.829219&cid=C01GTK53T8Q) while trying to sign in, so I won't be able to provide android screenshots.

**Comment by Beamanator** [comment] 2022-05-23 12:45
@adeel0202 since this is a pretty small PR, I'm ok with that - @mananjadhav or I can test your PR on android 👍

**Comment by adeel0202** [comment] 2022-05-24 12:33
Thank you @Beamanator. I have raised the PR.

**Comment by mananjadhav** [comment] 2022-06-15 05:38
@bfitzexpensify This deployed to production 6 days ago but its title for the payment hasn't changed.

**Comment by bfitzexpensify** [comment] 2022-06-15 09:26
Thanks for letting me know! Updated the title to remind myself to process payment tomorrow.

**Comment by bfitzexpensify** [comment] 2022-06-16 09:11
Alright, contracts all paid out. Thanks for the work here!

**Closed by bfitzexpensify** 2022-06-16 09:11 UTC
Labels: Reviewing, Exported, External, Engineering, Weekly
