### ISSUE TITLE
[HOLD for payment 2022-09-02] [$250] iOS - Sending a misspelled word to chat return auto-corrected word in the text input - reported by @dhairyasenjaliya

### ISSUE THREAD

**Issue by mvtglobally** [Expensify/App#10291] opened 2022-08-08 03:25 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Launch the app
2. Login with any account
3. Send a message with any misspelled word that the spell checker highlights blue opacity and send that misspelled message

## Expected Result:
Sent Messages should be shown in the chat list and removed from text input

## Actual Result:
Currently, if we sent misspelled word it sends to the chat list it remains in text input with auto-correct spell
for example if sent message 'rew' it send message as 'rew' but it remains in text input as 'few' which is auto correct

## Workaround:
unknown 

## Platform:

Where is this issue occurring?

- iOS

**Version Number:** 1.1.88-0
**Reproducible in staging?:** Y 
**Reproducible in production?:** Y
**Email or phone of affected tester (no customers):** 
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation

https://user-images.githubusercontent.com/43995119/183332210-277bbf5b-b522-42e4-9a8d-2a21017ce6fa.mp4

**Expensify/Expensify Issue URL:** 
**Issue reported by:** @dhairyasenjaliya
**Slack conversation:** https://expensify.slack.com/archives/C01GTK53T8Q/p1654860503611229

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by bfitzexpensify** [comment] 2022-08-08 20:27
Upwork job [here](https://www.upwork.com/jobs/~014406160e54028c57)
Reporting job [here](https://www.upwork.com/jobs/~012384282af9b4ff2a) - please apply to this @dhairyasenjaliya

**Comment by dhairyasenjaliya** [comment] 2022-08-09 03:17
### Proposal

**Note: This proposal I have already added along with the report here https://github.com/Expensify/App/issues/8592#issuecomment-1152926071** 

- When we add any message which is a typo (misspelled) into the composer and it sends as a message, but also it remains in text input with the auto-correct word in the iOS (app) 

- It causes 2 issue 
  1. Auto Text remains as it is
  2. Blue opacity also remains as it is for spellcheck 

### Solution

- To fix the issue in iOS (App) we need to remove the line setNativeProps in submit() function as we are already clearing the text from the composer after submitting text so applying selection with setNativeProps to empty text causes this issue 

- Also setNativeProps is deprecated only because it causes weird issues like this one and also it ignores the latest style 

   ``// this.textInput.setNativeProps({selection: {start: 0, end: 0}});``

https://github.com/Expensify/App/blob/11a1f0debac2dfee461e6b71751c3b3bcfb9f2cf/src/pages/home/report/ReportActionCompose.js#L425-L430

Like this : 

     this.props.onSubmit(trimmedComment);
     this.updateComment(''); // here we are already clearing composer textinput so applying 0 selection below this has no effect 
     this.setTextInputShouldClear(true);
     // Important to reset the selection on Submit action
     //this.textInput.setNativeProps({selection: {start: 0, end: 0}}); // comment this line solves problem in iOS (app)

**Note**: commenting on this line won't affect any other platform as we are already clearing the composer 

### Result (After commenting setNativeProps line) :  
Device : iPhone 13(App)

https://user-images.githubusercontent.com/47522946/173188941-a898f924-0cd1-455b-97f5-35d35ee38f0f.mp4

### Result (Without commenting setNativeProps line Current behavior) :  

https://user-images.githubusercontent.com/47522946/173188991-d0c0ecf2-dcbc-4ea5-b165-69431e46cc8f.mp4

**Comment by bfitzexpensify** [comment] 2022-08-12 13:07
@mananjadhav some proposals for you to review when you get a chance

**Comment by mananjadhav** [comment] 2022-08-12 13:33
Hi @bfitzexpensify, I am running behind on the backlog, is it possible to assign another C+?

**Comment by dhairyasenjaliya** [comment] 2022-08-15 13:21
**Result** (After removing setNativeProps line) 

@parasharrajat added all platform video also added one scenario whereby I select all text from text input and send a message with selection ON so we can confirm removing the setNativeProps line works well

**iOS (App)**

https://user-images.githubusercontent.com/47522946/184640730-9ad667df-92d9-4928-9578-f68e25dafb20.mp4

**Android (slow to send even 2 messages on the latest build 🤦)**

https://user-images.githubusercontent.com/47522946/184641160-dd2b2720-cda9-4339-b8cb-0c825ef3fb5e.mp4

**Mobile Safari**

https://user-images.githubusercontent.com/47522946/184641605-9810709e-07b0-4374-81a8-07eb83f69a73.mp4

**Chrome Web**

https://user-images.githubusercontent.com/47522946/184642137-db42287e-9037-4a3a-aa42-5501a2994347.mp4


**Safari Web**

https://user-images.githubusercontent.com/47522946/184641260-4ecac28c-aefd-4b3e-bb71-25482a2123fa.mov

**Mac Desktop**

https://user-images.githubusercontent.com/47522946/184642627-5c9295df-2f1b-4056-acdd-d99728d4fb55.mp4

**Comment by AndrewGable** [comment] 2022-08-24 09:30
External contributor assigned, awaiting C+ review on PR.

**Comment by bfitzexpensify** [comment] 2022-09-02 08:13
Payment complete and contracts ended. Thanks @dhairyasenjaliya!

**Comment by kbecciv** [comment] 2022-09-08 15:58
@bfitzexpensify @parasharrajat QA team is able to reproduce it with build 1.1.98.0

https://user-images.githubusercontent.com/93399543/189169455-ddd8f93f-8159-4c0f-b63b-5dbdbf9d76d9.MP4

**Comment by dhairyasenjaliya** [comment] 2022-09-08 16:02
@kbecciv yup this is an open issue here https://github.com/Expensify/App/issues/8592 for M-Safari only currently in this PR we have fixed only the iOS app 
- I think we can re-close this one from here

**Closed** 2022-09-08 16:09 UTC
Labels: Exported, External, Engineering, Daily, Improvement, Awaiting Payment
