### ISSUE TITLE
Account – Infinite loading spinner when closing an account

### ISSUE THREAD

**Issue by IuliiaHerets** [Expensify/App#49532] opened 2024-09-20 12:11 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** v9.0.39-0
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**Email or phone of affected tester (no customers):** applausetester+shsb22acc1177@applause.expensifail.com
**Issue reported by:** Applause Internal Team

## Action Performed:
1. Login with an account
2. Navigate to account settings > Security > Close account
3. Enter the reason and default contact method > Close > Confirm

## Expected Result:
User is signed out from the app and the account is closed successfully

## Actual Result:
Infinite loading spinner is displayed in the RHP and the user is not logged out from the app

## Workaround:
Unknown

## Platforms:

- [ ] Android: Native
- [x] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

https://github.com/user-attachments/assets/648b7e07-e5d5-4d69-a696-01db6013cc4f

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by IuliiaHerets** [comment] 2024-09-20 12:11
@RachCHopkins  FYI I haven't added the External label as I wasn't 100% sure about this issue. Please take a look and add the label if you agree it's a bug and can be handled by external contributors

**Comment by MonilBhavsar** [comment] 2024-09-23 20:36
Thanks for confirming @daledah!

**Comment by MonilBhavsar** [comment] 2024-09-23 20:36
@jjcoffee were you looking at this bug? Do you mind if I assign you as a C+?

**Comment by situchan** [comment] 2024-09-23 20:38
> I tested it by removing the changes from that PR, and it worked fine.

If this is true, I would be C+ as regression. Not tested yet though.

**Comment by MonilBhavsar** [comment] 2024-09-23 20:39
I agree the PR could not be the reason as we're only subscribing guides to specific channel and since the user experiencing the issue is not a guide.

**Comment by MonilBhavsar** [comment] 2024-09-23 20:43
I had a look at the server side code and we're only returning pusher response for CloseAccount API command. I think we should return the API response too for the user taking an action and that should probably fix this issue. Will make a change and see if we still are able to reproduce the issue

**Comment by MonilBhavsar** [comment] 2024-09-24 06:16
Yes, this is internal issue

**Comment by MonilBhavsar** [comment] 2024-09-24 19:21
Got PR in review!

**Comment by RachCHopkins** [comment] 2024-09-30 06:09
Are there any steps left here @MonilBhavsar?

**Comment by MonilBhavsar** [comment] 2024-09-30 06:12
Thanks for the comment. No this is fixed! We can close this as it was all internal

**Closed by MonilBhavsar** 2024-09-30 06:12 UTC
Labels: Reviewing, Daily, Internal, Bug
