### ISSUE TITLE
[$500] IPad - Chat - Keyboard briefly displayed after closing emoji picker

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#34772] opened 2024-01-19 00:31 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.27-1
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** Applause - Internal Team
**Slack conversation:**

## Action Performed:
Precondition: user has changed the iPad orientation to landscape and locked it
1. Open the app and log in
2. Navigate to any chat
3. Tap the emoji picker
4. Tap outside the emoji picker modal

## Expected Result:
The emoji picker modal closes without any visual distortions

## Actual Result:
The keyboard is briefly displayed on the left side after closing the emoji picker

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [x] iOS: Native
- [ ] iOS: mWeb Safari
- [ ] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details> 

https://github.com/Expensify/App/assets/78819774/438825be-99ef-4bd2-902c-278f76d27c11

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~013e19e2e6eb778cdc</li>
        <li>Upwork Job ID: 1748141043533287424</li>
        <li>Last Price Increase: 2024-01-19</li>
    </ul>
</details>

**Comment by lanitochka17** [comment] 2024-01-19 00:31
[#vip-vsb](https://expensify.enterprise.slack.com/archives/C066HJM2CAZ)

**Comment by ikevin127** [comment] 2024-01-19 17:05
Hello @lanitochka17, any details in terms of device model / generation / ios version ?
I tried reproducing on simulator of iPad Pro 12.9-inch (6th generation) iOS 17.0 and it doesn't happen.

**Comment by lanitochka17** [comment] 2024-01-19 18:58
@ikevin127 Hello
iPad 8th gen / iPadOS 17.2.1

**Comment by c3024** [comment] 2024-01-24 06:41
awaiting proposals

**Comment by abekkala** [comment] 2024-01-25 21:09
https://github.com/Expensify/App/issues/34772

**Comment by abekkala** [comment] 2024-01-26 15:59
[lukasz.morawski@callstack.com](mailto:lukasz.morawski@callstack.com) is going to pick this up on Monday

**Comment by lukemorawski** [comment] 2024-01-29 14:39
@abekkala 
Well I'm not sure if we really can do anything about it. If you look closely you'll see that iPad's orientation from the video is locked to a landscape mode. Exfy app on the other hand only handles portrait mode. So when the keyboard shows up, iPadOS for a split second shows it in the landscape mode to switch to portrait mode later on. 
This problem does not occur when the iPad is held in portrait mode.
Looks like it's either a React Native or iOS bug. I'm pretty much sure I've seen this behaviour in other apps from time to time.
I guess the best way to get rid of this glitch is to allow expensify to work in landscape mode on tablets and update the UI to support this mode.
I was exploring some config/prop changes to mitigate this problem but nothing really helps.

**Comment by abekkala** [comment] 2024-01-29 19:08
@lukemorawski ah ok, thanks for that explanation!

Closing this.

**Closed by abekkala** 2024-01-29 19:08 UTC
Labels: External, Daily, Overdue, Bug
