### ISSUE TITLE
Copilot - Selected access level is not highlighted

### ISSUE THREAD

**Issue by IuliiaHerets** [Expensify/App#48965] opened 2024-09-11 08:26 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 9.0.32-0
**Reproducible in staging?:** Y
**Reproducible in production?:** N/A
**Issue was found when executing this PR:** https://github.com/Expensify/App/pull/47353
**Email or phone of affected tester (no customers):** applausetester+kh010901@applause.expensifail.com
**Issue reported by:** Applause Internal Team

## Action Performed:
1. Go to staging.new.expensify.com
2. Go to Account settings > Security.
3. Click Add copilot.
4. Select a user.
5. Select an access level.
6. Click Access level on the confirmation page

## Expected Result:
The selected access level will be highlighted.

## Actual Result:
The selected access level is not highlighted.

## Workaround:
Unknown

## Platforms:

- [x] Android: Native
- [x] Android: mWeb Chrome
- [x] iOS: Native
- [x] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

https://github.com/user-attachments/assets/0fc53dcc-0b78-4542-9c80-8867adbb1866

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by mkzie2** [comment] 2024-09-11 09:01
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
The selected access level is not highlighted.

### What is the root cause of that problem?

We're missing `initiallyFocusedOptionKey` for this `SelectionList`:

https://github.com/Expensify/App/blob/7ff29a6235812bc6e1d60887fb3608b062e2491c/src/pages/settings/Security/AddDelegate/SelectDelegateRolePage.tsx#L41

### What changes do you think we should make in order to solve the problem?


Add `initiallyFocusedOptionKey={route.params.role}`

**Comment by rushatgabhane** [comment] 2024-09-11 09:29
not a blocker. @iwiznia @adelekennedy kindly assign it to me because im working on copilot project

**Closed** 2024-09-18 19:26 UTC
Labels: Reviewing, Engineering, Daily, Bug
