### ISSUE TITLE
[$500] Send money - Enter keypress on amount page triggers pay with expensify popup and displays in corner

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#29608] opened 2023-10-14 15:02 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.3.84.0
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** @dhanashree-sawant
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1697205384875589

## Action Performed:
1. Open the app
2. Click on green plus and click send money
3. Select USD as currency, enter any amount and click Next
4. Select any user
5. Open amount page
6. Click enter and observe that pay with expensify popup is open in top left corner

## Expected Result:
App should not trigger pay with expensify popup on enter keypress on amount page

## Actual Result:
App triggers pay with expensify popup on enter keypress on amount page and displays it in top left corner

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos
<details>
<summary>Android: Native</summary>

</details>

<details>
<summary>Android: mWeb Chrome</summary>

</details>

<details>
<summary>iOS: Native</summary>

</details>

<details>
<summary>iOS: mWeb Safari</summary>

</details>

<details>
<summary>MacOS: Chrome / Safari</summary>

 

https://github.com/Expensify/App/assets/93399543/9e25b703-4bc8-435d-95cc-24666b7cb3fd

https://github.com/Expensify/App/assets/93399543/85f7db87-084c-4528-9906-e4ebdce4f9c4

https://github.com/Expensify/App/assets/93399543/06b84bea-3fd8-40b0-a929-6c17cf8299a5

</details>

<details>
<summary>MacOS: Desktop</summary>

 

https://github.com/Expensify/App/assets/93399543/95fa4790-3527-4432-ba70-b9219da5f024

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01620c1716cd0baeb7</li>
        <li>Upwork Job ID: 1713208560531128320</li>
        <li>Last Price Increase: 2023-10-14</li>
    </ul>
</details>

**Comment by abzokhattab** [comment] 2023-10-14 15:02
## Proposal

### Please re-state the problem that we are trying to solve in this issue.

Enter keypress on amount page triggers the pay with expensify popup which is present in the prev page

### What is the root cause of that problem?

user goes to confimation list then to the amount page then back to the confirmation...
on back from the amount page, the confirmation page opens the same ref

### What changes do you think we should make in order to solve the problem?

enforce fallback route when going back from the amount page so that it respwans the confirmation list page ,,, the same as we are doing in the other request money pages .

https://github.com/Expensify/App/blob/2c9c303199ef53f91d586c1fa35acb75b42afd1b/src/pages/iou/steps/NewRequestAmountPage.js#L145

to

```js
Navigation.goBack(
  ROUTES.MONEY_REQUEST_CONFIRMATION.getRoute(iouType, reportID),
  true
);
```

### POC

https://github.com/Expensify/App/assets/59809993/6ee8d09f-dac5-4ea5-b610-7eb5eab534cd

**Comment by twisterdotcom** [comment] 2023-10-17 14:44
Okay, closing as dupe: https://github.com/Expensify/App/issues/29051

**Closed by twisterdotcom** 2023-10-17 14:44 UTC
Labels: External, Daily, Help Wanted, Overdue, Bug
