### ISSUE TITLE
[$500] Android - Chat - Unable to paste text  few times & scroller is not shown

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#32737] opened 2023-12-08 18:31 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.10-0
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** Applause - Internal Team
**Slack conversation:**

## Action Performed:
1. Launch app
2. Tap on a report
3. Paste repeatedly the same text
4. Note user cannot paste after few times
5. Note compose box does not extends automatically and scroller is not shown

## Expected Result:
User must be able to paste repeatedly, compose box must extends automatically and scroller must be shown on the side

## Actual Result:
When pasting text repeatedly in android, scroller is not shown and unable to paste after few times without pressing enter key and compose box does not extends automatically
In mweb, user can paste repeatedly, scroller is shown, compose box extends automatically

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [ ] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details> 

https://github.com/Expensify/App/assets/78819774/190f410d-8c2e-4e3a-833e-a74499774d45

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01a9b12a84af02cd56</li>
        <li>Upwork Job ID: 1733192528413265920</li>
        <li>Last Price Increase: 2024-03-13</li>
    </ul>
</details>

**Comment by sophiepintoraetz** [comment] 2023-12-12 01:37
Only the one proposal to review - @jjcoffee, want to take a look?

**Comment by jjcoffee** [comment] 2023-12-13 10:56
@yh-0218 Thanks for the proposal! Would you mind including more detail particularly around the root cause.

@sophiepintoraetz I think it might be worth holding this on https://github.com/Expensify/App/pull/31483

**Comment by yh-0218** [comment] 2023-12-13 11:55
@jjcoffee Thanks for your reply. I think that is react-native android issue. so we can't control that.
 so I post alternative way.

**Comment by sophiepintoraetz** [comment] 2023-12-17 23:48
@jjcoffee - holding makes sense based on the PR! Likely, I won't revisit this until after the Christmas break (at which point, we can check to see if it's still happening).

**Comment by sophiepintoraetz** [comment] 2024-01-03 23:18
Linked PR is still open.

**Comment by sophiepintoraetz** [comment] 2024-01-14 23:45
Almost at the point of merging.

**Comment by sophiepintoraetz** [comment] 2024-01-25 04:00
Same

**Comment by JmillsExpensify** [comment] 2024-02-07 02:31
Removing the HOLD since the linked PR has been merged/deployed.

**Comment by JmillsExpensify** [comment] 2024-02-07 02:32
Back open for reviews

**Comment by jjcoffee** [comment] 2024-02-12 15:48
Open for proposals.

**Comment by JmillsExpensify** [comment] 2024-02-14 16:33
Still open for proposals

**Comment by JmillsExpensify** [comment] 2024-02-21 01:36
Still open for proposals.

**Comment by nagypite** [comment] 2024-03-02 12:15
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
When pasting text repeatedly in android, scroller is not shown and compose box does not extend automatically.
As opposed to the original issue specs pasting seems to be working for me as expected.

### What is the root cause of that problem?
A `maxHeight` style is applied to the `<RNMarkdownTextInput>` element, which in turn extends React Native's `TextInput`. `TextInput` scrolling on Android isn't properly supported (yet), see: https://reactnative.dev/docs/textinput#scrollenabled-ios

### What changes do you think we should make in order to solve the problem?
`<RNMarkdownTextInput>` should be enclosed in a propertly styled `<ScrollView>`, with the calculated `maxHeight` (from `StyleUtils.getComposerMaxHeightStyle()`) applied to it.

### What alternative solutions did you explore? (Optional)
I've played around with different props and styles trying to force the `TextInput` to show a proper scollbar, looked at a loosely related 3rd party library for inspiration (https://github.com/baijunjie/react-native-input-scroll-view), but our only robust option at the moment seems to be `ScrollView` after all.

**Comment by JmillsExpensify** [comment] 2024-03-02 17:40
@jjcoffee Thoughts on this proposal?

**Comment by jjcoffee** [comment] 2024-03-05 11:37
@nagypite Does your [proposal](https://github.com/Expensify/App/issues/32737#issuecomment-1974781528) solve the issue of not being able to paste multiple times too?

**Comment by nagypite** [comment] 2024-03-05 12:25
@jjcoffee As I stated in the proposal, I couldn't reproduce the paste issue.

In fact, I don't think it's an issue at all. In the OP recording the text doesn't seem to update after a few pastes, but IMO it's only because the last lines of the text don't change, only the number of repetitions and thus the length. The changing part is simply invisible.

My proposal will fix this in a way because we'll get feedback of the text's changing length with the properly working scrollbar.

**Comment by jjcoffee** [comment] 2024-03-06 16:05
Reviewing tomorrow!

**Comment by jjcoffee** [comment] 2024-03-11 15:47
Damn, missed this one. On my list for tomorrow.

**Comment by jjcoffee** [comment] 2024-03-13 10:02
We've [closed](https://github.com/Expensify/App/issues/14118) [similar](https://github.com/Expensify/App/issues/8131) issues in the past, so I think it makes sense to do the same here given that the "unable to paste text a few times" part of the issue seems fixed. cc @JmillsExpensify

**Comment by JmillsExpensify** [comment] 2024-03-20 02:43
Ok, that's a fair point both of ya'll. I'll close the issue.

**Closed by JmillsExpensify** 2024-03-20 02:44 UTC
Labels: External, Daily, Help Wanted, Bug
