### ISSUE TITLE
Android - Chat - Text enclosed in backquotes is hidden

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#22815] opened 2023-07-13 15:31 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Open the app
2. Login with any account
3. Go to any chat
4. Send any message in backquotes:
![image](https://github.com/Expensify/App/assets/78819774/e6291e43-cfe1-4d90-b654-68289619ebba)

## Expected Result:
Text NOT hidden

## Actual Result:
Text is hidden

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [ ] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 1.3.40.1

**Reproducible in staging?:** Yes

**Reproducible in production?:** Yes

**If this was caught during regression testing, add the test name, ID and link from TestRail:**

**Email or phone of affected tester (no customers):**

**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/78819774/f273318d-72cd-4862-bbf2-70e3a1a2ac00

**Expensify/Expensify Issue URL:**

**Issue reported by:** Applause - Internal Team

**Slack conversation:**

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by MitchExpensify** [comment] 2023-07-14 19:32
Reproduced 
<img width="367" alt="image" src="https://github.com/Expensify/App/assets/36425901/3e21eb2a-71fc-4ab0-9284-fe041ec1b9ad">

**Comment by MitchExpensify** [comment] 2023-07-24 20:56
Any help with links to the corresponding issue or thread would be appreciated @chiragxarora - I cannot find either 👀

**Comment by MitchExpensify** [comment] 2023-07-25 17:43
I really appreciate it! Thanks @chiragxarora 

Closing as this is a dupe

**Closed by MitchExpensify** 2023-07-25 17:43 UTC
Labels: Daily, Bug
