### ISSUE TITLE
Web - Expense - Fields are blank and header shows $0.00 request when changing date

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#33103] opened 2023-12-14 17:55 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.13.0
**Reproducible in staging?:** Y
**Reproducible in production?:** N
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** Applause - Internal Team
**Slack conversation:**

## Action Performed:
1. Go to staging.new.expensify.com
2. Go to created manual expense details page
3. Click Date
4. Change the date

## Expected Result:
Date is saved without having other areas of the app going blank

## Actual Result:
When date is saved, the other fields go blank, the header turns $0.00 request and the date reverts to today's date briefly

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [x] Android: mWeb Chrome
- [x] iOS: Native
- [x] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details> 

https://github.com/Expensify/App/assets/78819774/6bbe968a-7a3a-4a5c-aa70-cae448375992

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by abzokhattab** [comment] 2023-12-14 18:22
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
Fields are blank and when changing money request date 

### What is the root cause of that problem?


when chaning the money request date we set `onlyIncludeChangedFields` param as `true` That is why it only returns the changed 
param: https://github.com/Expensify/App/blob/53dc13a362242e46d4486e93b55e08c7da21440a/src/libs/actions/IOU.js#L1020


### What changes do you think we should make in order to solve the problem?


we should set it to `true` in order not to affect other fields

**Comment by paultsimura** [comment] 2023-12-14 18:27
## Proposal

### Please re-state the problem that we are trying to solve in this issue.


### What is the root cause of that problem?
We are building the Onyx data that contains only updated fields, and use SET operation that fully replaces the transaction:

https://github.com/Expensify/App/blob/052c5cc258228e770c8091250ba0be871aee27c3/src/libs/actions/IOU.js#L1016-L1022

### What changes do you think we should make in order to solve the problem?
We should call `getUpdateMoneyRequestParams` with `onlyIncludeChangedFields=false`.

### What alternative solutions did you explore? (Optional)

**Comment by francoisl** [comment] 2023-12-14 18:39
So this is mostly a visual issue where the money request's fields temporarily show as blank, right? Going to remove the blocker label while we evaluate the proposals, it doesn't break updating the money request.

**Comment by paultsimura** [comment] 2023-12-14 19:03
@tgolen I think you might want to look at the alternative solution section of my proposal https://github.com/Expensify/App/issues/33103#issuecomment-1856370911, since it might become quite a bad bug in the future, and you are probably most in the context of those changes

**Comment by francoisl** [comment] 2023-12-14 19:19
Yes overall, I don't know if using `onlyIncludeChangedFields=false` is the best solution, we don't need to pass all the data that didn't change to the backend.

An alternative solution that works for me is to simply use the full transaction object in the optimistic data that we `SET`, i.e. replace this line with `...updatedTransaction`.

https://github.com/Expensify/App/blob/bd251125a2e13fdabe834de3ba4ba2265104dccb/src/libs/actions/IOU.js#L934-L934

Curious for Tim's thoughts as well since he indeed probably has the most context on this.

**Comment by tgolen** [comment] 2023-12-15 15:21
Hi, the main proposal to change `Onyx.set()` to `Onyx.merge()` is the right thing to do here. I am not sure why I used `set()` and it could have just been a mistake or oversight. Let's give that a try. All the changes mentioned to turn this into `merge()` look correct.

**Comment by paultsimura** [comment] 2023-12-15 15:25
> I am not sure why I used `set()` and it could have just been a mistake or oversight

The `merge` was changed to `set` in https://github.com/Expensify/App/pull/31340 in the middle of your big refactoring, and most likely was mishandled during the merge into the refactoring PR

**Comment by bondydaa** [comment] 2023-12-15 15:56
hi coming from this other blocker https://github.com/Expensify/App/issues/33098#issuecomment-1858086997, looks like @situchan is suggesting we revert https://github.com/Expensify/App/pull/31340 which sounds would fix this GH and https://github.com/Expensify/App/issues/33098

We'd have to redo a PR for https://github.com/Expensify/App/issues/30290 to fix that bug but def seems like https://github.com/Expensify/App/pull/31340 is the main problem here.

Do others agree with reverting https://github.com/Expensify/App/pull/31340?

**Comment by bondydaa** [comment] 2023-12-15 16:08
took this to slack here to discuss https://expensify.slack.com/archives/C01GTK53T8Q/p1702656464396679

**Comment by paultsimura** [comment] 2023-12-15 16:09
> Do others agree with reverting https://github.com/Expensify/App/pull/31340?

That should fix this issue only partially. But we could link this issue and a proper fix to https://github.com/Expensify/App/issues/30290 together in one PR, as they are tightly connected code-wise.

**Comment by paultsimura** [comment] 2023-12-22 11:57
This shouldn't be reproducible anymore after the fix was deployed: https://github.com/Expensify/App/pull/33174

**Comment by francoisl** [comment] 2024-01-08 22:36
Confirmed this no longer happens, closing.

**Closed by francoisl** 2024-01-08 22:36 UTC
Labels: Reviewing, Engineering, Monthly, Bug
