### ISSUE TITLE
Android - LHN - Invited user needs to re-login to be able to see active/archived announce room 

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#11542] opened 2022-10-03 17:15 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Issue found when executing PR** https://github.com/Expensify/App/pull/10452 

## Action Performed:
1. Go to staging.new.expensify.com and log in with Account A
2. Launch the app
2. Log in with account B
3. On Account A - Go to Setting - Workspace - Manage members
4. Invite Account B as a member
5. Back to Android app and check the announce room
5. Or try to search announce room
6. Account B needs to re-log in to able to see announce room
7. Go back to Account A and remove the Account B from member
8. Go back in Account B and check if the room archived.

## Expected Result:
Invited user should see active/archived announce room without re-login

## Actual Result:
Invited user needs to re-login to be able to see active/archived announce room

## Workaround:
Unknown

## Platform:

Where is this issue occurring?

- iOS (don't need to re-login to see the archived room)
- Android

**Version Number:** 1.2.11.1

**Reproducible in staging?:** Yes

**Reproducible in production?:** Yes

**Email or phone of affected tester (no customers):** 

**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Notes/Photos/Videos:** Any additional supporting documentation

https://user-images.githubusercontent.com/93399543/193638408-d9dba5f6-0d83-486e-8df4-0879b6e6bef4.mp4

**Expensify/Expensify Issue URL:** 

**Issue reported by:** Applause - Internal Team

**Slack conversation:** 

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by aldo-expensify** [comment] 2022-10-05 21:29
@chiragsalian since you worked in the Policy merge refactor (I think inviting users to a workspaces uses that command, right?)

I'm labeling this internal as I think this is probably related to not sending the right pusher events from the API once we add new employees to the workspace.

**Comment by chiragsalian** [comment] 2022-10-05 23:38
I think invited members were not able to see announce channel unless they refreshed in the past so that did not change with the API refactor. Atleast if I remember correctly. Either way, yeah we can add this in. Assigning to self.

**Comment by chiragsalian** [comment] 2022-10-11 19:20
Not really a daily so demoting for now. But its on my plate.

**Comment by chiragsalian** [comment] 2022-10-26 18:16
Haven't gotten to due to other priorities. I also wonder if this was tackled elsewhere, i need to retest.

**Comment by chiragsalian** [comment] 2022-11-02 00:37
Haven't gotten to it due to other priorities. @kbecciv, would you be able to retest and confirm if the issue still persists?

**Comment by kbecciv** [comment] 2022-11-02 15:22
Issue is not fixed with build 1.2.22.3

https://user-images.githubusercontent.com/93399543/199529552-91599a05-d854-4247-bffe-7cc8f475f577.mp4

**Comment by chiragsalian** [comment] 2022-11-09 00:28
Haven't gotten to it due to other priorities. Hoping to tackle next week.

**Comment by mvtglobally** [comment] 2022-11-09 03:36
Issue not reproducible during KI retests. (First week)

**Comment by mvtglobally** [comment] 2022-11-16 02:16
Issue not reproducible during KI retests. (Second week)

**Comment by chiragsalian** [comment] 2022-11-28 18:17
Closing since the issue hasn't been reproducible in a while. If it does feel free to reopen.

**Closed by chiragsalian** 2022-11-28 18:17 UTC
Labels: Engineering, Daily, Internal, Overdue, Bug
