### ISSUE TITLE
[$1000] Remove Safari workaround to fix attachment picker issue

### ISSUE THREAD

**Issue by dangrous** [Expensify/App#24297] opened 2023-08-08 20:29 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

In https://github.com/Expensify/App/pull/19011 we added in a [workaround](https://github.com/Expensify/App/pull/19011/files#r1270720176) for Safari's specific behavior for pop-ups and actions, because they always have to be triggered by a user action. This works, but is probably not ideal. Let's figure out a way to improve it!

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01ce38317e6e2f0866</li>
        <li>Upwork Job ID: 1689306743240826880</li>
        <li>Last Price Increase: 2023-08-16</li>
    </ul>
</details>

**Comment by twisterdotcom** [comment] 2023-08-09 16:04
Doesn't need designing.

**Comment by jeet-dhandha** [comment] 2023-08-09 20:51
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
- To remove work around for the safari browser's issue with Open Attachment Picker

### What is the root cause of that problem?
- As explained by @allroundexperts the picker only open's by user's interaction. And not on call of `onSelected` in `onModalHide`.
- We want to simplyfy the code to not use index and find more of a generic solution.

### What changes do you think we should make in order to solve the problem?

### Solution 1:
- We can use `InteractionManager` for IOS and Safari browser to run the `onSelected` method after the interaction is completed.
```js
if (getOperatingSystem() === CONST.OS.IOS || Browser.isSafari()) {
    InteractionManager.runAfterInteractions(() => {
        selectedItem.onSelected();
    });
} else {
    selectedItem.onSelected();
}
```

Pros for this solution:
- It is a generic solution and `onSelected` method is handled only in one place.

Cons for this solution:
- It increases execution time by 40-60 ms.

### Solution 2:
- We can pass a boolean variable `triggerOnItemSelected` with `onSelected` prop to menuItems.
`triggerOnItemSelected: getOperatingSystem() === CONST.OS.IOS || Browser.isSafari()`
- And then in `onModalHide` we can check if `triggerOnItemSelected` is true then we call `onSelected` from `onItemSelected` method.

Pros for this solution:
- Execution time remains same as we are just adding a check.

Cons for this solution:
- We have to add `triggerOnItemSelected` to all the menuItems having `openPicker` method call and also we will have to maintain it for future openPicker calls. 

### What alternative solutions did you explore? (Optional)
- N/A

**Comment by twisterdotcom** [comment] 2023-08-14 11:02
Are these proposals any good @sobitneupane?

**Comment by sobitneupane** [comment] 2023-08-14 15:44
Thanks for the [proposal](https://github.com/Expensify/App/issues/24297#issuecomment-1672131394) @jeet-dhandha.

Can you please add more details in the Root Cause Analysis.

Solution 1 looks similar to [this proposal](https://github.com/Expensify/App/issues/24297#issuecomment-1671990280). I didn't get your second proposal. Can you please add more details. Please make use of permalinks to refer to the files and code blocks where you are suggesting changes.

**Comment by sobitneupane** [comment] 2023-08-16 17:44
Thanks for the [update](https://github.com/Expensify/App/issues/24297#issuecomment-1677971733) @alex2bc.

As @alex2bc suggested [here](https://github.com/Expensify/App/issues/24297#issuecomment-1671990280), reverting https://github.com/Expensify/App/pull/19339 PR will solve the issue in Safari and we can remove the workaround. But, it will recreate [another issue](https://github.com/Expensify/App/issues/19310). Looks like we don't have any way of solving [the issue](https://github.com/Expensify/App/issues/19310), without using some workaround like `InteractionManager.runAfterInteractions`.

What's your thought on this @dangrous?

**Comment by dangrous** [comment] 2023-08-16 20:41
Okay, if all of our possibilities are really just replacing one workaround with another (which I understand), I think we might be okay to just close this issue, and not complete. What do you think?

**Comment by sobitneupane** [comment] 2023-08-18 08:55
> Okay, if all of our possibilities are really just replacing one workaround with another (which I understand), I think we might be okay to just close this issue, and not complete. What do you think?

We will be replacing workarounds with some other workaround. So, I agree on closing the issue.

**Comment by twisterdotcom** [comment] 2023-08-18 10:05
Apologies but I am finally going on Parental Leave. I am reassigning to another member of the team. But I also agree, we should close.

**Closed** 2023-08-18 10:05 UTC
Labels: External, Daily, Weekly, NewFeature, Help Wanted

**Comment by jeet-dhandha** [comment] 2023-08-22 05:15
> Thanks for the update @jeet-dhandha.
> 
> But probably, your solution will resurface #19310 issue. And also, it looks like a workaround.

I already tested this it works 👍  fine.
