### ISSUE TITLE
[$500] Settings -QR Code- Inconsistency in profile avatar & QR code avatar

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#27057] opened 2023-09-08 20:04 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1 Observe the avatar in profile
2 Verify if avatar is same in Share Code > QR Code

## Expected Result:
Avatar is same with QA code

## Actual Result:
Avatar is different with QA code

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [x] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 1.3.66.1
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/93399543/5f5bc144-04ab-45df-9051-9851ca6416df

https://github.com/Expensify/App/assets/93399543/a387ceeb-d4b6-4eb5-a64a-8623107f7025

**Expensify/Expensify Issue URL:**
**Issue reported by:** @avi-shek-jha
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1686609992247039

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01c8e880a11e839c60</li>
        <li>Upwork Job ID: 1700238615688482816</li>
        <li>Last Price Increase: 2023-09-08</li>
    </ul>
</details>

**Comment by b4s36t4** [comment] 2023-09-08 20:09
I think it's a dupe of #25889

**Comment by PiyushChandra17** [comment] 2023-09-09 06:26
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
Avatar is different with QA code 

### What is the root cause of that problem?
In [UserUtils](https://github.com/Expensify/App/blob/main/src/libs/UserUtils.js#L111), We are using the different hash calculation for Share Code > QR Code than Profile page for the Avatar to be the same, hence this is the root cause.

Calculation done in Profile page:
- `const accountIDHashBucket = (accountID % CONST.DEFAULT_AVATAR_COUNT) + 1;`

Calculation done in QR code page
- `const accountIDHashBucket = hashText(String(accountID), isNewDot ? CONST.DEFAULT_AVATAR_COUNT : CONST.OLD_DEFAULT_AVATAR_COUNT) + 1;`

### What changes do you think we should make in order to solve the problem?
We need to use the same calculation for both the profile page and QR code page in order for the avatar to be the same.

`const accountIDHashBucket = (Number(accountID) % (isNewDot ? CONST.DEFAULT_AVATAR_COUNT : CONST.OLD_DEFAULT_AVATAR_COUNT)) + 1;`



### What alternative solutions did you explore? (Optional)
None.

**Comment by PiyushChandra17** [comment] 2023-09-09 06:45
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
Avatar is different with QA code 

### What is the root cause of that problem?
In [UserUtils](https://github.com/Expensify/App/blob/main/src/libs/UserUtils.js#L111), We are using the different hash calculation for Share Code > QR Code than Profile page for the Avatar to be the same, hence this is the root cause.

Calculation done in Profile page:
- ```const accountIDHashBucket = (accountID % CONST.DEFAULT_AVATAR_COUNT) + 1;```


Calculation done in QR code page:
- ```const accountIDHashBucket = hashText(String(accountID), isNewDot ? CONST.DEFAULT_AVATAR_COUNT : CONST.OLD_DEFAULT_AVATAR_COUNT) + 1;```

### What changes do you think we should make in order to solve the problem?
We need to use the same calculation in QR code page.

`const accountIDHashBucket = (Number(accountID) % (isNewDot ? CONST.DEFAULT_AVATAR_COUNT : CONST.OLD_DEFAULT_AVATAR_COUNT)) + 1;`


### What alternative solutions did you explore? (Optional)
None.

**Comment by Tony-MK** [comment] 2023-09-10 16:43
## Proposal

### Please re-state the problem that we are trying to solve in this issue.

Inconsistency in profile avatar & QR code avatar

### What is the root cause of that problem?

We are computing the `accountIDHashBucket` variable differently in the two functions used in the profile and share code page. The `accountIDHashBucket` value determines which default avatar to show. When the avatar is default, the share page uses the function `getDefaultAvatarURL` and the profile page uses the `getDefaultAvatar`.

For Share Code page avatar - `getDefaultAvatarURL`:
https://github.com/Expensify/App/blob/b11bddc054f54bb46d5fb5aaf05e25b8a7df7faf/src/libs/UserUtils.js#L92

For profile page avatar - `getDefaultAvatar`:
https://github.com/Expensify/App/blob/b11bddc054f54bb46d5fb5aaf05e25b8a7df7faf/src/libs/UserUtils.js#L111

The root cause of the problem is that `hashText` function is not giving us the result we expect. It is giving us a different answer.

### What changes do you think we should make in order to solve the problem?


In the `getDefaultAvatarURL` in change the how `accountIDHashBucket` is computed. It should match how the `accountIDHashBucket` variable in the `getDefaultAvatar` function. So using the using the `hashText` function

So something like this :

`
const accountIDHashBucket = (accountID % (isNewDot ? CONST.DEFAULT_AVATAR_COUNT : CONST.OLD_DEFAULT_AVATAR_COUNT)) + 1;
`

Result ->
https://github.com/Expensify/App/assets/22982173/981d8cf7-0ec7-4a65-b59a-851b594c4c20

**Comment by alexpensify** [comment] 2023-09-11 22:12
@luacmartins and @rushatgabhane - can we get confirmation if this is a dupe of https://github.com/Expensify/App/issues/25889

**Comment by alexpensify** [comment] 2023-09-11 22:23
Thanks! I'm going to close this GH.

**Closed by alexpensify** 2023-09-11 22:23 UTC
Labels: External, Daily, Help Wanted, Bug
