### ISSUE TITLE
[$1000] 2FA codes are not loading on visit using deep link 

### ISSUE THREAD

**Issue by kavimuru** [Expensify/App#22512] opened 2023-07-09 03:38 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Open the app
2. Visit link: https://staging.new.expensify.com/settings/security/two-factor-auth/codes
3. Observe that 2FA codes are not loaded, close and visit properly from settings->security->Two factor authentication and observe that codes are visible
## Expected Result: 
App should load 2FA codes on visiting by deep link
## Actual Result: 
App does not load 2FA codes on visiting by deep link

## Workaround:
Can the user still use Expensify without this being fixed? Have you informed them of the workaround?

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [x] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 1.3.38-2
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/43996225/7f7c712d-3fd2-471a-b2bf-9e2cad69a0ea

https://github.com/Expensify/App/assets/43996225/cafbcec6-8fc1-4cff-9ce6-90f1a107f13e

**Expensify/Expensify Issue URL:**
**Issue reported by:** @dhanashree-sawant
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1688837558310729
 
[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~016fc6d7045a374e59</li>
        <li>Upwork Job ID: 1679001033250156544</li>
        <li>Last Price Increase: 2023-07-12</li>
    </ul>
</details>

**Comment by multijump** [comment] 2023-07-11 15:04
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
2FA codes are not loading on visit using deep link

### What is the root cause of that problem?
When `EnableTwoFactorAuth` is called, `recoveryCodes` are merged to Onyx and this action run in `toggleTwoFactorAuth` in `SecuritySettingsPage.js`
So if go to `CodesPage.js` directly via url, `requiresTwoFactorAuth` doesn't run so can't get the `recoveryCodes` from Onyx.
This is the RC

### What changes do you think we should make in order to solve the problem?

If `props.account.requiresTwoFactorAuth` is `false`, that means user didn't enable 2FA so we need to run `Session.toggleTwoFactorAuth(true)` function to get `recoveryCodes` from Onyx.
If `props.account.requiresTwoFactorAuth` is `true`, we need to redirect to `ROUTES.SETTINGS_2FA_IS_ENABLED`.
just like this.
```
    useEffect(() => {
        if (props.account.requiresTwoFactorAuth) {
            Navigation.navigate(ROUTES.SETTINGS_2FA_IS_ENABLED);
        } else {
            Session.toggleTwoFactorAuth(true);
        }
    }, []);
```
### What alternative solutions did you explore? (Optional)
N/A
**Reminder:** Please use plain English, be brief and avoid jargon. Feel free to use images, charts or pseudo-code if necessary. Do not post large multi-line diffs or write walls of text. Do not create PRs unless you have been hired for this job.

**Comment by tjferriss** [comment] 2023-07-12 05:34
The codes did not load when I clicked on the deep link.

<img width="663" alt="Screenshot 2023-07-11 at 22 33 45" src="https://github.com/Expensify/App/assets/8292562/3671dd01-36ae-49f2-9273-d788e80c1d2b">

**Comment by gadhiyamanan** [comment] 2023-07-12 05:39
@tjferriss dupe of https://github.com/Expensify/App/issues/19496

**Comment by tjferriss** [comment] 2023-07-12 18:45
Thanks for finding that one @gadhiyamanan

**Closed by tjferriss** 2023-07-12 18:45 UTC
Labels: External, Daily, Help Wanted, Bug
