### ISSUE TITLE
[$500] When selecting the Finish point the Start and Finish points are grayed out for a moment with the "Next" button

### ISSUE THREAD

**Issue by m-natarajan** [Expensify/App#29596] opened 2023-10-13 23:16 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.3.84-0
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** @ayazhussain79 
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1696433219544139

## Action Performed:
1. Click on the "+" button.
2. Go to Request money > Distance.
3. Select Start and then the Finish point.
4. Observe that both Start and Finish points are grayed out with the "Next" button.
## Expected Result: 
Start and Finish points should not be grayed out when selecting the Finish point
## Actual Result: 
Start and Finish points are grayed out with the "Next" button when selecting the Finish point.

## Workaround:
Can the user still use Expensify without this being fixed? Have you informed them of the workaround?

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native - not provided
- [ ] Android: mWeb Chrome
- [x] iOS: Native
- [x] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos
<details>
<summary>Android: Native</summary>

</details>

<details>
<summary>Android: mWeb Chrome</summary>

</details>

<details>
<summary>iOS: Native</summary>

https://github.com/Expensify/App/assets/38435837/3bc8a955-ca0a-494a-b989-68a6053eb6e0

</details>

<details>
<summary>iOS: mWeb Safari</summary>

</details>

<details>
<summary>MacOS: Chrome / Safari</summary>

https://github.com/Expensify/App/assets/38435837/b310b268-0d11-44fa-a468-78cf97652136

https://github.com/Expensify/App/assets/38435837/1ff8b9ac-deb4-496a-8aa3-d555eeb797fc

</details>

<details>
<summary>MacOS: Desktop</summary>

https://github.com/Expensify/App/assets/38435837/b1a56e93-89b9-44d4-a1d1-d7f3e4e30729

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01acf4f61c03542500</li>
        <li>Upwork Job ID: 1712970654951510016</li>
        <li>Last Price Increase: 2023-10-27</li>
    </ul>
</details>

**Comment by DylanDylann** [comment] 2023-10-13 23:16
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
- When selecting the Finish point the Start and Finish points are grayed out with the "Next" button

### What is the root cause of that problem?
- Currently, we disable the Start and Finish points when the route is loading, that leads to the bug " When selecting the Finish point the Start and Finish points are grayed out with the "Next" button"
https://github.com/Expensify/App/blob/25f7ac14d3dcadbb60e24074494b12d181567ba3/src/components/DistanceRequest/index.js#L172
- The above logic is added to [commit](https://github.com/Expensify/App/pull/26307/commits/08dd080a174646d7d5ac62bb3aa1d3acb3810a49) which fixes the issue [Bug2: flicker issue (showing old order for a brief moment)]( https://github.com/Expensify/App/pull/26307#issuecomment-1735667273). It disables the items of draggable list when the route is reloading. 

### What changes do you think we should make in order to solve the problem?
- We should only prevent the items from being dragged when the route is loading, other methods like clicking on items to edit waypoints, ... still be allowed. We can do it by:
- Update the ```DraggableList``` from https://github.com/Expensify/App/blob/4078503d8e2468a3f0c54fc37af0f888ed2abf41/src/components/DraggableList/index.tsx#L91
to 
```
  <Draggable isDragDisabled={props.isDragDisabled} ... />
```
- Then when using ```DraggableList```, update
https://github.com/Expensify/App/blob/4078503d8e2468a3f0c54fc37af0f888ed2abf41/src/components/DistanceRequest/index.js#L157
to
```
<DraggableList isDragDisabled={isLoadingRoute} ... />
```
- Also we need to remove the ```isDragDisabled={isLoadingRoute}``` from https://github.com/Expensify/App/blob/4078503d8e2468a3f0c54fc37af0f888ed2abf41/src/components/DistanceRequest/index.js#L172
### What alternative solutions did you explore? (Optional)
- NA

**Comment by DylanDylann** [comment] 2023-10-13 23:20
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
- When selecting the Finish point the Start and Finish points are grayed out with the "Next" button

### What is the root cause of that problem?
- Currently, we disable the Start and Finish points when the route is loading, that leads to the bug " When selecting the Finish point the Start and Finish points are grayed out with the "Next" button"
https://github.com/Expensify/App/blob/25f7ac14d3dcadbb60e24074494b12d181567ba3/src/components/DistanceRequest/index.js#L172
- The above logic is added to [commit](https://github.com/Expensify/App/pull/26307/commits/08dd080a174646d7d5ac62bb3aa1d3acb3810a49) which fixes the issue [Bug2: flicker issue (showing old order for a brief moment)]( https://github.com/Expensify/App/pull/26307#issuecomment-1735667273). It disables the items of draggable list when the route is reloading. 

### What changes do you think we should make in order to solve the problem?
- We should only prevent the items from being dragged when the route is loading, other methods like clicking on items to edit waypoints, ... still be allowed. We can do it by:
- Update the ```DraggableList``` from https://github.com/Expensify/App/blob/4078503d8e2468a3f0c54fc37af0f888ed2abf41/src/components/DraggableList/index.tsx#L91
to 
```
  <Draggable isDragDisabled={props.isDragDisabled} ... />
```
- Then when using ```DraggableList```, update
https://github.com/Expensify/App/blob/4078503d8e2468a3f0c54fc37af0f888ed2abf41/src/components/DistanceRequest/index.js#L157
to
```
<DraggableList isDragDisabled={isLoadingRoute} ... />
```
- Also we need to remove the ```isDragDisabled={isLoadingRoute}``` from https://github.com/Expensify/App/blob/4078503d8e2468a3f0c54fc37af0f888ed2abf41/src/components/DistanceRequest/index.js#L172
### What alternative solutions did you explore? (Optional)
- NA

**Comment by mallenexpensify** [comment] 2023-10-16 19:15
@m-natarajan, can you please provide screenshots or vids in the OP?  Here's what I'm seeing which doesn't _seem_ like a bug , not looks particularly greyed out
![IMG_0340](https://github.com/Expensify/App/assets/22508304/ddd3ea38-9d68-4c01-9bec-7a36b1f99e60)

**Comment by mallenexpensify** [comment] 2023-10-23 15:57
Waiting on feedback from above.
> @m-natarajan, can you please provide screenshots or vids in the OP? Here's what I'm seeing which doesn't seem like a bug , not looks particularly greyed out

**Comment by m-natarajan** [comment] 2023-10-23 18:55
@mallenexpensify Videos are added to iOS native, MacOS: Chrome / Safari and MacOS: Desktop.

I am adding video here, at the timeline 08sec both waypoints are grayed out for a brief moment. Now "Next" button is not disabled. 

https://github.com/Expensify/App/assets/38435837/c5d8b5aa-cee6-457b-9f84-ad889b8abebe

**Comment by narefyev91** [comment] 2023-10-24 09:05
@mallenexpensify like this:
<img width="478" alt="Screenshot 2023-10-24 at 12 05 14" src="https://github.com/Expensify/App/assets/28352309/be5764d7-13a5-4105-bb0e-15bc198f5085">

**Comment by mallenexpensify** [comment] 2023-10-25 00:11
I _feel_ like this looks more like a loading process than a significant bug.  Like, the app is quickly processing the addresses before producing the map.  

Is there something I'm maybe _missing_ here?  I'm leaning towards closing this as being too minor to fix. 

Thanks for posting the vid and screenshot @m-natarajan and @narefyev91

**Comment by DylanDylann** [comment] 2023-10-25 02:42
@mallenexpensify In this case, the loading is unnecessary. If we can move forward this issue, It will help to improve the performance: smoother and avoid fetching route unnecessary

**Comment by mallenexpensify** [comment] 2023-10-26 19:34
Thanks for the comment @DylanDylann , I'm [checking internally](https://expensify.slack.com/archives/C05DWUDHVK7/p1698348788505189) since I'm not well-versed in distance-related bugs and features.

**Comment by mallenexpensify** [comment] 2023-10-30 23:05
I posted internally and got back
> Yeah this definitely does not look like a bug, we’re generating the route to show on the map

Going to close

**Closed by mallenexpensify** 2023-10-30 23:05 UTC
Labels: External, Daily, Help Wanted, Overdue, Bug
