### ISSUE TITLE
Clicking return button twice redirect to personal details screen 

### ISSUE THREAD

**Issue by mvtglobally** [Expensify/App#24251] opened 2023-08-08 03:27 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Go to settings-> Click on profile
2. Click personal details-> Click home address
3. Click on Country/State option
4. Focus in textfield-> Clear value of textfield (If Any)
5. Click return button twice from keyboard

## Expected Result:
It should stay on the same screen instead of redirecting to personal details page
or
it should go to Home address screen

## Actual Result:
It redirects back to the Personal details page

## Workaround:
unknown 

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [X] iOS / Safari
- [ ] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 1.3.46-0
**Reproducible in staging?:** needs repro
**Reproducible in production?:** needs repro 
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation 

https://github.com/Expensify/App/assets/43995119/ccdff63f-2265-48a6-9f9e-02549fbeac30

**Expensify/Expensify Issue URL:**
**Issue reported by:** @DinalJivani
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1690405904862489 

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by gadhiyamanan** [comment] 2023-08-08 04:00
Dupe of https://github.com/Expensify/App/issues/23725

**Comment by bfitzexpensify** [comment] 2023-08-09 13:33
Agreed. Closing

**Closed by bfitzexpensify** 2023-08-09 13:33 UTC
Labels: Daily, Needs Reproduction, Bug
