### ISSUE TITLE
Dev: The search field does not automatically focus when selecting a member for a money request

### ISSUE THREAD

**Issue by kavimuru** [Expensify/App#25803] opened 2023-08-23 22:17 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Navigate to the "Request Money" section
2. Enter an amount and click "Next"
3. Notice the search field does not automatically focus
## Expected Result: 
The search field should automatically be in focus when selecting a member for a money request
## Actual Result: 
The search field does not auto focus when selecting a member for a money request
## Workaround:
Can the user still use Expensify without this being fixed? Have you informed them of the workaround?

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [x] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** Dev 
**Reproducible in staging?:** dev 
**Reproducible in production?:** dev
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/43996225/075b8f23-d5ed-4165-9484-a70a4faf59c0

**Expensify/Expensify Issue URL:**
**Issue reported by:**  @ayazhussain79 
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1692819705952809

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by roryabraham** [comment] 2023-08-23 23:17
IDK the answer to that @parasharrajat, but I'm definitely not going to block deploy on this.

**Comment by gadhiyamanan** [comment] 2023-08-24 02:18
This is dupe of https://github.com/Expensify/App/issues/24314

**Comment by ayazhussain79** [comment] 2023-08-24 07:51
this issue is two weeks old https://github.com/Expensify/App/issues/24314 and not reproducible on staging

**Comment by gadhiyamanan** [comment] 2023-08-24 08:04
This issue was introduced after adding scan option in request money. right now it's behind the the beta and you can not use with your normal account in staging

**Comment by jasperhuangg** [comment] 2023-08-24 18:35
Closing in favor of https://github.com/Expensify/App/issues/24314

**Closed by jasperhuangg** 2023-08-24 18:35 UTC
Labels: Engineering, Daily, Bug
