### ISSUE TITLE
[$250] mWeb on Chrome and mobile app experience differs on signup

### ISSUE THREAD

**Issue by m-natarajan** [Expensify/App#46672] opened 2024-08-01 16:10 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 9.0.15-5
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** @davidcardoza 
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1722471696514569

## Action Performed:
1. Sign up for account
2. UsertTaps track expenses > taps get started after watching the video
       A. On mWeb the user is dropped into LHN with a GBR to Concierge
       B. On mobile iOS, the user is dropped into the Concierge chat
## Expected Result:
The user should always be dropped into LHN with a GBR to Concierge
## Actual Result:
Sign ups see two different experiences
## Workaround:
Unknown
## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [x] iOS: Native
- [ ] iOS: mWeb Safari
- [ ] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

https://github.com/user-attachments/assets/f742259c-ee39-45b5-95cb-5942c145a4fb

https://github.com/user-attachments/assets/4aa4c3fd-9770-40be-b7ad-d645e1bdcee7

Add any screenshot/video evidence

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01dc1e03761805d373</li>
        <li>Upwork Job ID: 1820461993908929902</li>
        <li>Last Price Increase: 2024-08-05</li>
<li>Automatic offers: </li>
<ul>
<li>rojiphil | Reviewer | 103494199</li>
</ul></li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @rojiphil</details>

**Comment by bernhardoj** [comment] 2024-08-02 09:22
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
The concierge page opens after completing onboarding in native.

### What is the root cause of that problem?
In the onboarding page, we have an effect that prevent the user to access the onboarding page again by redirecting them to the concierge page. (it was added in https://github.com/Expensify/App/pull/42087)
https://github.com/Expensify/App/blob/4f16e2654ec1f1bd8db19fb52d4752e22e358c0d/src/libs/Navigation/AppNavigator/Navigators/OnboardingModalNavigator.tsx#L36-L46

When we complete the onboarding, we call the API and dismiss the modal.
https://github.com/Expensify/App/blob/4f16e2654ec1f1bd8db19fb52d4752e22e358c0d/src/pages/OnboardingPersonalDetails/BaseOnboardingPersonalDetails.tsx#L64-L78

Looks like on native, the request is completed first before the navigator is completely closed, so the effect is triggered because the effect depends on `hasCompletedGuidedSetupFlow`.

### What changes do you think we should make in order to solve the problem?

Remove `hasCompletedGuidedSetupFlow` from the dependency so it's only triggered on mount which will still prevent the user to access the page if it's already completed.
https://github.com/Expensify/App/blob/4f16e2654ec1f1bd8db19fb52d4752e22e358c0d/src/libs/Navigation/AppNavigator/Navigators/OnboardingModalNavigator.tsx#L36-L46

**Comment by abekkala** [comment] 2024-08-05 14:11
@rojiphil there is already a proposal above ready for review! 🎉

**Comment by abekkala** [comment] 2024-08-08 18:20
@rojiphil can you please review the proposal above?

**Comment by rojiphil** [comment] 2024-08-09 18:12
Sorry for the delay here. I will review and provide an update by tomorrow my day.

**Comment by rojiphil** [comment] 2024-08-10 16:46
Yeah. An unnecessary trigger of the effect due to `hasCompletedGuidedSetupFlow` dependency is causing this issue. Removing the `hasCompletedGuidedSetupFlow` dependency makes sense.
@bernhardoj [proposal](https://github.com/Expensify/App/issues/46672#issuecomment-2264951903) LGTM.
🎀👀🎀 C+ reviewed

**Comment by dangrous** [comment] 2024-08-12 15:40
cool, makes sense! we should just make sure that this still works appropriately on desktop, as well as fixing mobile. But sounds good to me. Will assign!

**Comment by bernhardoj** [comment] 2024-08-13 10:02
@rojiphil @dangrous I can't reproduce this anymore after this [PR](https://github.com/Expensify/App/pull/45705). Looks like the issue that PR is trying to solve is the same as this one but with a different solution.

**Comment by dangrous** [comment] 2024-08-13 14:25
oh interesting! @abekkala do you have a moment to retest this? we might be able to just close it out

**Comment by rojiphil** [comment] 2024-08-13 15:58
yeah. Just tested the latest and this is fixed now. We can close this.

**Comment by dangrous** [comment] 2024-08-14 15:15
Nice, closing!

**Closed by dangrous** 2024-08-14 15:15 UTC
Labels: External, Daily, Bug
