### ISSUE TITLE
[$500] Android - Scan - The styles of the header out of alignment

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#28849] opened 2023-10-04 18:42 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Click on global + button
2. Select Scan
3. Upload an image
4. Once you are taken to the chat with the image in the "scanning" state, click on the preview to go to the details
5. Verify the styles of the header out of alignment

## Expected Result:
The styles of the header is not out of alignment

## Actual Result:
The styles of the header out of alignment

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [ ] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 1.3.77.5
**Reproducible in staging?:** n/a
**Reproducible in production?:** n/a
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation

![image (1)](https://github.com/Expensify/App/assets/93399543/11c3f8c8-c763-4089-ae4d-9d43bc510324)

**Expensify/Expensify Issue URL:**
**Issue reported by:** @tgolen 
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1696347198412019

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01d099292c50d200b6</li>
        <li>Upwork Job ID: 1711411675240120320</li>
        <li>Last Price Increase: 2023-10-23</li>
    </ul>
</details>

**Comment by manancodes** [comment] 2023-10-09 21:51
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
Wrong alignment when there is too much content in the header.

Although this is not replicable, there is still another issue, the text gets truncated and there is no way to see the whole text. Please refer this thread: https://app.slack.com/client/T03SC9DTT/C049HHMV9SM 

### What is the root cause of that problem?
We are limiting `numberOfLines` to `1` which is why it gets truncated. 
https://github.com/Expensify/App/blob/a348859ff43f38c487de96a3f1b4a75428f493b9/src/components/ParentNavigationSubtitle.js#L47-L50

### What changes do you think we should make in order to solve the problem?
The best solution, provided that we do not want the text to be truncated, is to use dynamic height for the header. 
If the content is too much for the space, the size of the header would increase, pushing down the content below the header.

### What alternative solutions did you explore? (Optional)

1. https://github.com/Expensify/App/issues/28851#issuecomment-1747586832 This is an alternate solution but does not completely solve the issue because it will still occur when there is a subtitle present.

2. Another solution would be to truncate the text, but make it touchable and pressing the text would open up a tooltip revealing the rest of the text.

     Example:
     <img width="400" alt="Screenshot 2023-10-10 at 3 15 01 AM" src="https://github.com/Expensify/App/assets/54790263/fd4edb3c-008f-4b6d-b1a8-e5ccb7f13c30">

**Comment by manancodes** [comment] 2023-10-09 22:02
I am not able to reproduce this on android.

**Comment by kbecciv** [comment] 2023-10-10 14:50
Hello @kevinksullivan Sorry about that, I did not add the "External" label, because unable to reproduce it, posted in thread https://expensify.slack.com/archives/C049HHMV9SM/p1696444323317159?thread_ts=1696347198.412019&cid=C049HHMV9SM. Thank you

**Comment by kevinksullivan** [comment] 2023-10-17 16:15
Looking for proposals

**Comment by mvtglobally** [comment] 2023-10-27 00:47
Issue not reproducible during KI retests. (First week)

**Comment by kevinksullivan** [comment] 2023-10-27 02:49
Closing then

**Closed by kevinksullivan** 2023-10-27 02:49 UTC
Labels: External, Engineering, Daily, Help Wanted, Overdue, Bug
