### ISSUE TITLE
Web - Tooltip is misaligned on long name user in LHN

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#22931] opened 2023-07-15 10:51 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Login with any account
2. Create a new chat with an account that has really long name.
3. Hover the mouse at that user name in LHN from the chat that you’ve just created
4. Observe the tooltip position

## Expected Result:
 Tooltip shouldn't be misaligned.
 
## Actual Result:
Tooltip is misaligned.

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [x] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 1.3.41.0
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/93399543/9e47fa45-7fff-4ce7-97e5-3b0f2a1e2398

https://github.com/Expensify/App/assets/93399543/412423ca-e93c-4a0c-aed4-9abf8d202342

**Expensify/Expensify Issue URL:**
**Issue reported by:** @hungvu193
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1689303792671209

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by trjExpensify** [comment] 2023-07-17 14:57
Yeah, it appears to be the same root cause with that component. I'm closing this out!

**Closed by trjExpensify** 2023-07-17 14:57 UTC
Labels: Daily, Bug
