### ISSUE TITLE
[$500] Workspace - The first WS created on a new account is displayed with a delay on the WS list

### ISSUE THREAD

**Issue by izarutskaya** [Expensify/App#41882] opened 2024-05-09 09:03 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.72.0
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**If this was caught during regression testing, add the test name, ID and link from TestRail:** https://github.com/Expensify/App/issues/40568
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Issue reported by:** Applause-Internal team

## Action Performed:
1. Log in with a new expensifail account
2. Create a workspace using the FAB
3. Quickly navigate back using the "<" button of the app

## Expected Result:
The workspace should be visible on the list without any delays.

## Actual Result:
The first WS created on a new account is displayed with a delay on the WS list. Any other workspaces created after the first one are displayed instantly, even if you delete all of your workspaces.

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

https://github.com/Expensify/App/assets/115492554/df48708e-d19b-4e99-aa1a-b9668174a843

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01d47ac840fb98d66a</li>
        <li>Upwork Job ID: 1788536723739299840</li>
        <li>Last Price Increase: 2024-06-13</li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @laurenreidexpensify</details>

**Comment by izarutskaya** [comment] 2024-05-09 09:04
We think this issue might be related to the #collect project.

**Comment by laurenreidexpensify** [comment] 2024-05-13 09:27
not overdue

**Comment by laurenreidexpensify** [comment] 2024-05-17 11:21
Waiting for fresh proposals

**Comment by laurenreidexpensify** [comment] 2024-05-20 12:15
Same update: Awaiting proposals

**Comment by laurenreidexpensify** [comment] 2024-05-22 10:39
@tienifr bump on that update :)

**Comment by laurenreidexpensify** [comment] 2024-05-28 08:51
proposals still in discussion

**Comment by laurenreidexpensify** [comment] 2024-05-31 12:03
@fedirjh thoughts on the above?

**Comment by laurenreidexpensify** [comment] 2024-06-04 11:16
@fedirjh bump thanks

**Comment by laurenreidexpensify** [comment] 2024-06-07 12:13
@fedirjh have you had a chance to review yet? thanks

**Comment by laurenreidexpensify** [comment] 2024-06-10 10:43
@fedirjh bump thanks

**Comment by laurenreidexpensify** [comment] 2024-06-13 10:28
Increased bounty

**Comment by abzokhattab** [comment] 2024-06-13 13:48
I am not able to reproduce it on latest main

**Comment by laurenreidexpensify** [comment] 2024-06-20 13:41
Agree this looks resolved - am closing. 

If we need to re-open for any reason, please re-add Bug label for a new BZ team member to take over, as I will be on parental leave. Thanks

**Closed by laurenreidexpensify** 2024-06-20 13:41 UTC
Labels: External, Daily, Help Wanted, Overdue, Bug
