### ISSUE TITLE
[HOLD for payment 2023-10-13] [$500] Web - Pronouns value not displayed on login

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#27675] opened 2023-09-18 13:50 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Open the app
2. Open settings->profile->pronouns
3. Copy the URL
4. Logout and paste the URL
5. Login and observe that currently selected pronouns value is not displayed

## Expected Result:
App should display pronouns value if present on login

## Actual Result:
App does not display pronouns value if present on login on login with pronouns page

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [x] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 1.3.71.4
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/93399543/8e6c1ffa-4714-4f77-9481-7e26b7048344

https://github.com/Expensify/App/assets/93399543/fdb1ea18-7854-421d-b473-9e97562b31bd

**Expensify/Expensify Issue URL:**
**Issue reported by:**  @dhanashree-sawant
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1694889012343609

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~014246fda785f9f058</li>
        <li>Upwork Job ID: 1703768490032054272</li>
        <li>Last Price Increase: 2023-09-25</li>
<li>Automatic offers: </li>
<ul>
<li>dukenv0307 | Contributor | 26916802</li>
</ul></li>
    </ul>
</details>

**Comment by c3024** [comment] 2023-09-18 13:50
## Proposal
### Please re-state the problem that we are trying to solve in this issue.
Pronouns list is not shown initially when accessed from deep link and then logging in
### What is the root cause of that problem?
We are setting the initial `searchValue` here
https://github.com/Expensify/App/blob/c77814fd5e643cba78e8c8294370d78f633a59c5/src/pages/settings/Profile/PronounsPage.js#L29-L35
When we access this page from deep link, initially `currentPronounsKey` is empty because `currentUserPersonalDetails` has not been loaded yet.
### What changes do you think we should make in order to solve the problem?
We should show a loading indicator when the page is loading and the `pronouns` field in `currentUserPersonalDetails` does not exist by adding this.
```js
    if (!_.has(currentUserPersonalDetails, 'pronouns')) {
        return <FullScreenLoadingIndicator />;
    }
```

### What alternative solutions did you explore? (Optional)

**Comment by saranshbalyan-1234** [comment] 2023-09-18 14:17
## Proposal
### Please re-state the problem that we are trying to solve in this issue.
Pronouns list is not shown initially when accessed from deep link and then logging in

### What is the root cause of that problem?
The initial state does not contains the pronouns.

https://github.com/Expensify/App/blob/ea5f461dc42844750529dbe6e285aeeae9c1c231/src/pages/settings/Profile/PronounsPage.js#L29-L36

When we access this page from deep link, initially currentPronounsKey is empty because currentUserPersonalDetails has not been loaded yet.

### What changes do you think we should make in order to solve the problem?
What we can do is we can use the below code to get the latest values from the currentUserPersonalDetails object.

```javascript
    useMemo(() => {
        setSearchValue(() => {
            const currentPronounsText = _.chain(CONST.PRONOUNS_LIST)
                .find((_value) => _value === currentPronounsKey)
                .value();

            return currentPronounsText ? translate(`pronouns.${currentPronounsText}`) : '';
        });
    }, [currentPronounsKey]);
``` 

Also the callback that is passed in the setSearchValue, should be a different fucntion to reduce code redundancy
### What alternative solutions did you explore? (Optional)
N/A

**Comment by CortneyOfstad** [comment] 2023-09-18 14:53
@joekaufmanexpensify there is a known issue with two assigners for BZ being applied (more info [here](https://expensify.slack.com/archives/C01SKUP7QR0/p1694513579526909)), so going to remove my assignment as the second one for this issue 👍

**Comment by joekaufmanexpensify** [comment] 2023-09-19 08:04
Sounds good!

**Comment by joekaufmanexpensify** [comment] 2023-09-20 08:20
i can reproduce this. Checking internally about something before saying definitively we should change this.

**Comment by joekaufmanexpensify** [comment] 2023-09-20 08:55
I chatted with @puneetlath to make sure we should fix this, since this form was designed with a lot intentionality, and confirmed that this is a bug. Next step is for @thesahindia to review proposals!

**Comment by joekaufmanexpensify** [comment] 2023-09-21 08:15
Pending review of proposals

**Comment by joekaufmanexpensify** [comment] 2023-09-22 07:17
@thesahindia could you take a look at these proposals when you have a sec? TY!

**Comment by joekaufmanexpensify** [comment] 2023-09-25 04:17
Pending review of proposals

**Comment by joekaufmanexpensify** [comment] 2023-09-27 06:33
Pending sign off from @amyevans

**Comment by joekaufmanexpensify** [comment] 2023-10-09 15:10
@allroundexperts mind taking care of the BZ checklist this week?

**Comment by joekaufmanexpensify** [comment] 2023-10-12 17:46
[Bumped BZ checklist](https://expensify.slack.com/archives/C02NK2DQWUX/p1697132773443099)

**Comment by joekaufmanexpensify** [comment] 2023-10-13 17:34
Pending completion of BZ checklist before we issue payment

**Comment by joekaufmanexpensify** [comment] 2023-10-17 19:49
Bumped in Slack

**Comment by joekaufmanexpensify** [comment] 2023-10-18 15:23
TY! IMO, we can punt the regression test here, as it doesn't seem realistic to me that many/any users will be frequently trying to deeplink login specifically to the pronouns page. This feels like a significant edge case to me, so no need to include it in every regression run.

**Comment by joekaufmanexpensify** [comment] 2023-10-18 21:52
Going to sort through the questions about contributor bounty, and whether the speed bonus applies here tomorrow. Once those are resolved, we'll be all set to issue payment!

**Comment by joekaufmanexpensify** [comment] 2023-10-19 16:00
We are still discussing [this](https://github.com/Expensify/App/issues/27675#issuecomment-1744118829) a bit, and will issue payment as soon as that is resolved!

**Comment by joekaufmanexpensify** [comment] 2023-10-19 20:18
@dukenv0307 checking in on [this](https://github.com/Expensify/App/issues/27675#issuecomment-1744118829). After further discussions, it sounds like the PR you ultimately implemented used some aspects of the other contributor's proposal.

No worries about this! But we're discussing splitting the $500 bounty with them, and want to make sure you don't have any significant concerns with that? TY!

**Comment by joekaufmanexpensify** [comment] 2023-10-23 13:31
@dukenv0307 could you please [review this](https://github.com/Expensify/App/issues/27675#issuecomment-1771646260) and let us know your thoughts? TY!

**Comment by joekaufmanexpensify** [comment] 2023-10-23 16:46
Okay, while we wait for the contributor payments to be sorted out (via Upwork), we can handle @allroundexperts payment now. They will get $750 ($500 for C+ review + $250 speed bonus), paid via NewDot

**Comment by JmillsExpensify** [comment] 2023-10-24 16:19
$750 payment approved for @allroundexperts based on summary above.

**Comment by joekaufmanexpensify** [comment] 2023-10-24 20:31
Great, thanks for confirming. That means we still need to issue the following payments: 

- @dukenv0307 - $375 ($250 for half of PR bounty, and $125 for 50% speed bonus for bounty paid). Paid vua Upwork. 
- @suneox - $250 for providing elements used in the solution. No speed bonus here since they did not contribute to the timed work to get this merged. Paid via upwork. 
- @dhanashree-sawant - $50 for reporting the bug. Paid via Upwork.

**Comment by joekaufmanexpensify** [comment] 2023-10-24 20:31
@suneox offer sent for $250!

**Comment by joekaufmanexpensify** [comment] 2023-10-24 20:31
@dhanashree-sawant offer sent for $50!

**Comment by joekaufmanexpensify** [comment] 2023-10-25 14:20
@dukenv0307 the urgency bonus is 50% of the bounty earned by the contributor who raised the PR, rather than a static bonus. Since you raised the PR, and are earning a $250 bounty for this issue, your 50% bonus for the PR is $125. A $250 bonus on your $250 bounty would be a 100% bonus. 

@suneox isn't earning a bonus since they were not involved in the collaborative process of raising the PR quickly. 

LMK if you have any other questions!

**Comment by joekaufmanexpensify** [comment] 2023-10-25 14:22
@dukenv0307 $375 sent and contract ended!

**Comment by joekaufmanexpensify** [comment] 2023-10-25 14:23
@suneox $250 sent and contract ended!

**Comment by joekaufmanexpensify** [comment] 2023-10-25 14:24
@dhanashree-sawant $50 sent and contract ended!

**Comment by joekaufmanexpensify** [comment] 2023-10-25 14:24
Upwork job closed

**Comment by joekaufmanexpensify** [comment] 2023-10-25 14:25
Bug is fixed, BZ checklist complete, and all payment issued. Closing as this is all set. Thanks everyone!

**Closed by joekaufmanexpensify** 2023-10-25 14:25 UTC
Labels: External, Daily, Awaiting Payment, Bug

**Comment by joekaufmanexpensify** [comment] 2023-11-15 15:50
@dukenv0307 I definitely understand where you're coming from. However, the previous guidance on the urgency bonus is fairly clear. It is a 50% bonus applied to the bounty earned to incentivize the individual writing the PR to get it done quickly. It scaled down with the various compensation changes we've made to the contributor program as well.  

I think we handled the urgency bonus in that other issue incorrectly, so I don't think we'd issue a 100% urgency bonus here based on that. 

We appreciate your understanding. Let me know if you have any other questions!
