### ISSUE TITLE
[$500] Android - There is a vertical shake every time I tap on a member

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#34300] opened 2024-01-10 21:48 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.24.0
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** Applause - Internal Team
**Slack conversation:**

**Issue found when executing PR** https://github.com/Expensify/App/pull/33584
## Action Performed:
1. Log in with an expensifail account
2. Create a workspace
3. Invite new members
4. Tap on several members checkbox

## Expected Result:
There shouldn't be any shaking

## Actual Result:
There is a vertical shake every time I tap on a member

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [ ] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details> 

https://github.com/Expensify/App/assets/78819774/7d8c74ab-071d-470e-8f61-d57ad3abd760

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by ikevin127** [comment] 2024-01-11 00:05
# Proposal

## Please re-state the problem that we are trying to solve in this issue

There is a vertical shake every time I tap on a member.

## What is the root cause of that problem?

When selecting a member to invite, within `BaseSelectionList.js` the `scrollToIndex()` function is called twice, once in the `selectRow()` after selection and a second time in `useEffect()` when section changes in order reset focus and scroll to item at index 0 (first selected in the list).

This causes the vertical scrolling shake animation between the first call of the scroll to the previously unselected item via `selectRow()` and the second one which resets the focus and scrolls to item at index 0 (first selected in the list) via the `useEffect()` when selected items section updates.

## What changes do you think we should make in order to solve the problem?

https://github.com/Expensify/App/blob/6aa90629717928532fc56064d162deac0c7ab03f/src/components/SelectionList/BaseSelectionList.js#L210-L217

Change the second `if` to (!item.isSelected && !shouldUnfocusRow), adding `!shouldUnfocusRow` check since the `onSelectRow={() => selectRow(item, true)}` function is initialized with `shouldUnfocusRow` true (second argument) which calls `setFocusedIndex(-1)` which means unfocus all rows when selecting row with click/press.

**Comment by jliexpensify** [comment] 2024-01-12 00:55
@lanitochka17 can you repro this on a non-Expensifail account? If it affects a normal account, then maybe we could consider fixing.

@eVoloshchak - curious tog et your thoughts on this issue: I'm leaning towards closing it, since it's so minor.

**Comment by lanitochka17** [comment] 2024-01-12 13:31
Issue reproducible on gmail account 
Samsung Galaxy A50/Android11

https://github.com/Expensify/App/assets/78819774/eec50b09-3b84-4c03-bd69-cc9bce3b7ce7

**Comment by jliexpensify** [comment] 2024-01-14 21:37
Cool, thanks @lanitochka17 - I was having repro-ing. The shake looks a bit more pronounced in your second video, let me bring this up with our team.

**Comment by jliexpensify** [comment] 2024-01-15 22:47
Bump @eVoloshchak for reviews, thanks!

**Comment by jjcoffee** [comment] 2024-01-17 10:57
@ikevin127 Thanks for your proposal! Based on what you've said, this looks like it may be a regression from https://github.com/Expensify/App/pull/30438? I'm also curious to know if you have any insight as to why this only occurs on native platforms?

I think the expected result here is actually that we should scroll to the selected member, rather than scrolling to the top of the page each time. I believe https://github.com/Expensify/App/pull/30438 was meant to adjust the scroll behaviour for searches, not for selections.

**Comment by jjcoffee** [comment] 2024-01-17 15:26
Just noticed that the PR author is working on a [PR](https://github.com/Expensify/App/pull/34196) for the regression that looks like it may fix this issue. I've [asked](https://github.com/Expensify/App/issues/29080#issuecomment-1896042916) to confirm.

**Comment by ikevin127** [comment] 2024-01-17 15:38
Looking at the PR I can confirm that it won't fix our issue, it will still run the useEffect for our case as his fix is strictly related to single select aka timezone.

If the author will see your comment and change the current PR by adding the suggested check from this solution then it will probably fix it.

**Comment by jliexpensify** [comment] 2024-01-19 02:26
Thanks @jjcoffee !

**Comment by zanyrenney** [comment] 2024-01-26 18:07
How did retesting this go @jliexpensify ?

**Comment by jliexpensify** [comment] 2024-01-28 04:25
@zanyrenney I tested on my own @expensifail.com and it looks like the problem has gone away (I originally didn't see it on my Gmail, like Applause reported):

https://github.com/Expensify/App/assets/30815269/7f7a76f5-8c80-4766-af99-7557cdcbf0c5

@jjcoffee can you verify this?

**Comment by jjcoffee** [comment] 2024-01-30 14:09
@jliexpensify Still seeing it on latest main (v1.4.33-4) actually! Can we ask Applause to retest? cc @lanitochka17 

https://github.com/Expensify/App/assets/27287420/cd7b8259-7aae-44d2-b492-95fc0dc73fcf

**Comment by jliexpensify** [comment] 2024-02-08 04:09
Bump @lanitochka17 for a re-test!

**Comment by lanitochka17** [comment] 2024-02-08 17:24
Issue reproducible on the  build 1.4.38-0

https://github.com/Expensify/App/assets/78819774/aa613d46-98a0-4f6e-8436-986b2e1c9f55

**Comment by jliexpensify** [comment] 2024-02-08 23:37
Hmm @jjcoffee - correct me if I'm wrong, but @lanitochka17's video [mirrors mine](https://github.com/Expensify/App/issues/34300#issuecomment-1913444319): and I don't see a shake? 

[The shake in your video is much more prominent.](https://github.com/Expensify/App/issues/34300#issuecomment-1916945362)

**Comment by jjcoffee** [comment] 2024-02-09 15:01
@jliexpensify I see a bit of a wobble in @lanitochka17's video too, so there's definitely some scroll-jumping going on, it's just more subtle. I'm testing on a high traffic account so the list of members available to invite (and scrollable height) is very long; that could potentially make a difference.

**Comment by jliexpensify** [comment] 2024-02-10 05:23
@jjcoffee ok great - so I guess my question is: will standard users have high-traffic accounts? i.e. is it something they'll experience? 

If so, lets try and find a fix. If not, lets close this - thoughts?

**Comment by jjcoffee** [comment] 2024-02-12 11:05
@jliexpensify I believe that there are users with high traffic accounts, since we have a checklist item to test using a high traffic account. Unfortunately I've no idea how many users would hit the "high traffic" threshold, but I don't think the list of users has to be super long to trigger this particular issue!

**Comment by jliexpensify** [comment] 2024-02-12 21:20
@jjcoffee I'm going to ask here: https://expensify.slack.com/archives/C01SKUP7QR0/p1707772810258999

Will loop back with an update!

**Comment by jliexpensify** [comment] 2024-02-22 07:13
Bumped again as I didn't get any responses :(

**Comment by jliexpensify** [comment] 2024-02-22 20:49
@jjcoffee - We're adding this to the Performance project, so lets work on it. Thanks!

**Comment by jjcoffee** [comment] 2024-02-23 09:19
@ikevin127 Would you be able to confirm that your [proposal](https://github.com/Expensify/App/issues/34300#issuecomment-1885954333) is still relevant after the PR we thought would fix this got merged?

**Comment by ikevin127** [comment] 2024-02-23 12:54
Looking at the latest main branch testing videos below we can notice that the scrolling behaviour changed, it doesn't stick to the top anymore therefore the issue cannot be reproduced. Now it scrolls to the latest added item which is handled by the `selectRow` function.

What changed between the JS `selectRow` function and the TS one is that when migrated the `shouldUnfocusRow` argument / functionality was removed. This together with the changes from PR https://github.com/Expensify/App/pull/34196 result in the current behaviour:

<details>
<summary>Android: Native</summary>

https://github.com/Expensify/App/assets/56457735/ccd5d3f6-89ba-4e8b-9665-921d3bba6438

</details>

<details>
<summary>iOS: Native</summary>

https://github.com/Expensify/App/assets/56457735/e0bbd1f4-5249-4251-b1fb-c78d719d4261

</details>

This being said, my proposal is outdated and wouldn't fix the issue anymore because the scrolling behaviour also changed.

**Comment by jjcoffee** [comment] 2024-02-27 16:13
@ikevin127 Thanks a lot for retesting! I agree the scrolling behaviour has now changed and so this particular issue seems fixed. cc @jliexpensify in case you have thoughts?

**Comment by jliexpensify** [comment] 2024-02-27 22:49
Thanks @jjcoffee and @ikevin127 - lets close this out then!

**Closed by jliexpensify** 2024-02-27 22:49 UTC
Labels: External, Weekly, Help Wanted, Bug
