### ISSUE TITLE
[$500] Workspace - No padding around workspace upload error

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#29652] opened 2023-10-16 01:24 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.3.84.1
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** @dhanashree-sawant
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1697206853776269

## Action Performed:
1. Open the app
2. Open settings->workspaces->any workspace->settings
3. Click on profile and click upload
4. Upload file greater then 6mb
5. Observe error has no padding around
6. Try similar file upload in settings->profile->click on profile->upload
7. Observe that it has proper padding around error

## Expected Result:
App should display proper padding around workspace upload errors like it does for user profile upload errors

## Actual Result:
App does not display proper padding around workspace upload errors

## Workaround:
Unknown 

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [x] Android: mWeb Chrome
- [x] iOS: Native
- [x] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos
<details>
<summary>Android: Native</summary>

 

https://github.com/Expensify/App/assets/93399543/1f54adc7-b8a4-4ccc-a3bc-8f24472f2fcf

</details>

<details>
<summary>Android: mWeb Chrome</summary>

 

https://github.com/Expensify/App/assets/93399543/de392a58-cdf4-4f89-92d2-5ee6bc77fcda

</details>

<details>
<summary>iOS: Native</summary>

 

https://github.com/Expensify/App/assets/93399543/1cd9aaff-a10f-497a-a3cd-50daa3592538

</details>

<details>
<summary>iOS: mWeb Safari</summary>

 

https://github.com/Expensify/App/assets/93399543/770378e1-96d5-44c2-a509-c736661255ec

</details>

<details>
<summary>MacOS: Chrome / Safari</summary>

 

https://github.com/Expensify/App/assets/93399543/4f09be9b-ebcb-4ae3-aa75-0d5db13bcdbe

https://github.com/Expensify/App/assets/93399543/5aeb26e2-ce6f-4e1e-b672-d18afa7d9e3e

https://github.com/Expensify/App/assets/93399543/1ad9eb25-0a2e-4a69-963b-f26f4102dea9

</details>

<details>
<summary>MacOS: Desktop</summary>

 

https://github.com/Expensify/App/assets/93399543/07473f4b-6d32-44a4-8377-cdd1588623bf

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01226fa069ff423c98</li>
        <li>Upwork Job ID: 1713727632636690432</li>
        <li>Last Price Increase: 2023-10-30</li>
<li>Automatic offers: </li>
<ul>
<li>esh-g | Contributor | 27451133</li>
<li>dhanashree-sawant | Reporter | 27451134</li>
</ul></li>
    </ul>
</details>

**Comment by c3024** [comment] 2023-10-16 01:24
## Proposal
### Please re-state the problem that we are trying to solve in this issue.
No margin around the error when uploading large image for workspace image upload but in profile pic update there is a proper margin
### What is the root cause of that problem?
There is a horizontal margin for `AvatarWithImagePicker` here
https://github.com/Expensify/App/blob/fe282b45cb13e01519282ccc023e5bfbd7714158/src/pages/settings/Profile/ProfilePage.js#L135
but not here
https://github.com/Expensify/App/blob/fe282b45cb13e01519282ccc023e5bfbd7714158/src/pages/workspace/WorkspaceSettingsPage.js#L128
### What changes do you think we should make in order to solve the problem?
We need to add the horizontal margin `mh5` for the `AvatarWithImagePicker` of `WorkspaceSettingsPage` also.
### What alternative solutions did you explore? (Optional)

**Comment by esh-g** [comment] 2023-10-16 01:24
# Proposal

## Please re-state the problem we are trying to solve:
No padding around workspace upload error

## What is the root cause of this problem?
The root cause is that there is no horizonal margin on the `AvatarWithImagePicker` component in `WorkspaceSettingsPage`:
<img width="374" alt="Screenshot 2023-10-14 at 6 00 31 PM" src="https://github.com/Expensify/App/assets/77237602/a1be5321-5102-410c-b323-86a1f9121a2b">

Unlike the profile page with has margin on `AvatarWithImagePicker`:
<img width="374" alt="Screenshot 2023-10-14 at 6 00 22 PM" src="https://github.com/Expensify/App/assets/77237602/30911565-cd20-4705-906d-46e1b5d640e5">

## What changes should be made to fix this?
We should add the style `styles.mh5` to the `AvatarWithImagePicker` in `WorkspaceSettingsPage` just like we do in the profile page here:
https://github.com/Expensify/App/blob/fe282b45cb13e01519282ccc023e5bfbd7714158/src/pages/settings/Profile/ProfilePage.js#L135

**Comment by abdel-h66** [comment] 2023-10-16 12:22
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
Workspace settings avatar container has no horizontal paddings 

### What is the root cause of that problem?
For both profile settings and workspace settings, we are using the same component `AvatarWithImagePicker`  to display the handle the display and upload of avatar. In the profile settings page we are passing horizontal paddings to the component, we should do the same in the Workspace settings 

### What changes do you think we should make in order to solve the problem?

```js
<AvatarWithImagePicker
    style={[styles.mb3, styles.mh5]}
```

### What alternative solutions did you explore? (Optional)
I noticed some differences in margins of the profile page vs the workspace settings page. 

Profile settings page: 
The `AvatarWithImagePicker` has styles.mh5
The section right under it has styles.mt4

Workspace settings page 
 If we apply suggestion above `AvatarWithImagePicker` will have `style={[styles.mb3, styles.mh5]}`

I suggest removing the `styles.mt4` from the View in the profile settings page. 
And moving it to the `AvatarWithImagePicker` to have `[styles.mb3, styles.mh5]`

![image](https://github.com/abdel-h66/proposals/assets/144037189/ad7385ff-bc27-4968-b005-b476278f4bad)

**Comment by peterdbarkerUK** [comment] 2023-10-17 10:02
One note for future reference: expensify.com user accounts will get the [MISSING TRANSLATION error](https://github.com/Expensify/App/issues/27759) here instead.

**Comment by dhairyasenjaliya** [comment] 2023-10-17 19:57
### Proposal  

### Please re-state the problem that we are trying to solve in this issue. 

-  Workspace name Red dot error does not align horizontally with the text field

### What is the root cause of that problem?

-  The root cause is we have not added `marginHorizontal` directly to `<Form>` instead we have added it on the separate component which is placed inside `<Form>` making the error style to broke 

### What changes do you think we should make in order to solve the problem?

- Firstly we need to remove `submitButtonStyles` style from `<Form>` which has `mh5` only to the `submitButton` and not to the entire `<Form>` https://github.com/Expensify/App/blob/91e2120e647aa9ee22171b6dbb772b4aebe64992/src/pages/workspace/WorkspaceSettingsPage.js#L105

- After that we need to add `mh5` directly to `<Form>` style to apply on entire `<Form>` 
https://github.com/Expensify/App/blob/91e2120e647aa9ee22171b6dbb772b4aebe64992/src/pages/workspace/WorkspaceSettingsPage.js#L104
-  After that, we need to clean up the extra horizontal style applied to multiple components which is redundant as we already added directly to `<Form>` which the above proposal is missing which can cause regression (at the time of adding this non of the proposal added this) https://github.com/Expensify/App/blob/91e2120e647aa9ee22171b6dbb772b4aebe64992/src/pages/workspace/WorkspaceSettingsPage.js#L148  
 https://github.com/Expensify/App/blob/91e2120e647aa9ee22171b6dbb772b4aebe64992/src/pages/workspace/WorkspaceSettingsPage.js#L161

- Once we added `mh5` to `<Form>` we need to adjust styling of `MenuItemWithTopDescription` by adding `wrapperStyle` and we need to add both the styles as `styles.mhn5, styles.wAuto` seems like the component already had `mh5` by default so we need to remove and the same condition can be found on other pages like `WorkspaceReimburseView.js` 
https://github.com/Expensify/App/blob/91e2120e647aa9ee22171b6dbb772b4aebe64992/src/pages/workspace/reimburse/WorkspaceReimburseView.js#L149

 
### What alternative solutions did you explore? (Optional)

-  N/A

### Result 

<img src=https://github.com/Expensify/App/assets/47522946/361bc00b-6911-4386-b73a-a19ab9ebe3f2  width=50%>

<img width="912" alt="Screenshot 2023-10-17 at 4 07 13 PM" src="https://github.com/Expensify/App/assets/47522946/99b618fa-011b-4c73-aa3b-796c5f105438">

**Comment by peterdbarkerUK** [comment] 2023-10-22 15:16
@eVoloshchak could you take a look at these proposals? Thanks!

**Comment by eVoloshchak** [comment] 2023-10-23 11:58
I think we should proceed with @c3024's [proposal](https://github.com/Expensify/App/issues/29652#issuecomment-1763587428), as this was the first proposal to fund the root cause for this and propose a valid fix
The fix is simple and straightforward with zero potential regressions
There are a couple of proposals that _extend_ @c3024's proposal finding further inconsistencies on this page, but those should be reported and handled in a separate issue.

🎀👀🎀 C+ reviewed!

**Comment by esh-g** [comment] 2023-10-23 12:56
@eVoloshchak if we create a separate issue for those inconsistencies, we will end up undoing what we are going to do here... because to fix the whole page, we need to add padding to the whole form and if we do that the change that @c3024 proposed is not needed...

**Comment by Beamanator** [comment] 2023-10-27 13:13
Bump @eVoloshchak

**Comment by eVoloshchak** [comment] 2023-10-30 10:42
> I'm actually leaning toward @esh-g 's proposal https://github.com/Expensify/App/issues/29652#issuecomment-1763587430 - because it is an attempt to make the entire page layout similar to other pages - Plus it fixes that additional name error message issue

Yeah, that is a good point. While this isn't the first proposal, it will allow us to make the whole page consistent with the rest of the app, and the UX is more important
Let's proceed with @esh-g's [proposal](https://github.com/Expensify/App/issues/29652#issuecomment-1763587430)

**Comment by esh-g** [comment] 2023-10-31 15:18
PR is here: https://github.com/Expensify/App/pull/30638

cc @eVoloshchak

**Comment by peterdbarkerUK** [comment] 2023-11-15 10:53
PR deployed to production without issue.

[UpWork job](https://www.upwork.com/ab/applicants/1713727632636690432/hired)

Payment summary:
- $50 bug report to @dhanashree-sawant
- $500 contributor to @esh-g 

@eVoloshchak please request payment in NewDot (assigned to @JmillsExpensify for payout)

**Comment by JmillsExpensify** [comment] 2023-11-24 18:08
Haven't received a money request yet, though feel free to close this out and I'll comment with approval once I receive it via NewDot.

**Comment by eVoloshchak** [comment] 2023-11-27 15:41
Requested the payment

**Comment by peterdbarkerUK** [comment] 2023-11-28 13:13
Updated! It should be $500.

**Comment by JmillsExpensify** [comment] 2023-11-28 15:28
$500 payment approved for @eVoloshchak based on comment above.

**Comment by peterdbarkerUK** [comment] 2023-11-29 10:50
Thanks Jason!

**Closed by peterdbarkerUK** 2023-11-29 10:50 UTC
Labels: Reviewing, External, Weekly, Bug
