### ISSUE TITLE
[HOLD for payment 2024-06-28] [$250] mWeb - Workspace - Wrong members number is displayed

### ISSUE THREAD

**Issue by m-natarajan** [Expensify/App#42262] opened 2024-05-16 10:38 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.74-1
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:** https://expensify.testrail.io/index.php?/tests/view/4563078
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** Applause internal team
**Slack conversation:**

## Action Performed:
1. Create a workspace
2. Invite one member
3. Navigate to the workspace chat with the invited member.
4. Click on the header to go to the details page
5. Notice that the members number is displayed as 4.
6. Click on members, Notice that only 3 members are there.

## Expected Result:
members number displayed is equal to the workspace members

## Actual Result:
members number is displayed as 4 when there are only 3 members.

## Workaround:
unknown
## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [x] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [ ] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

https://github.com/Expensify/App/assets/38435837/37d0c804-ead0-4433-a111-acce390aa756

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Issue Owner</summary>Current Issue Owner: @alexpensify</details>
<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~0110eb98a4dc986510</li>
        <li>Upwork Job ID: 1792305587832528896</li>
        <li>Last Price Increase: 2024-06-02</li>
<li>Automatic offers: </li>
<ul>
<li>alitoshmatov | Reviewer | 102574059</li>
<li>nkdengineer | Contributor | 102574060</li>
</ul></li>
    </ul>
</details>

**Comment by m-natarajan** [comment] 2024-05-16 10:39
@alexpensify FYI I haven't added the External label as I wasn't 100% sure about this issue. Please take a look and add the label if you agree it's a bug and can be handled by external contributors

**Comment by m-natarajan** [comment] 2024-05-16 10:41
We think that this bug might be related to  #vip-vsb

**Comment by nkdengineer** [comment] 2024-05-17 09:18
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
members number is displayed as 4 when there are only 3 members.

### What is the root cause of that problem?
- When adding any member that did not log in yet to the workspace, we add that member to report's participant as the optimistic data. Now, the report's participants is something like ```[a]```. Then BE returns a new data for that user with a new accountID. Now the report's participants is something like ```[a, a1]``` and bot ```a``` and ```a1``` pointer to the new user.


- The number of members is from [activeChatMembers](https://github.com/Expensify/App/blob/e8ae3c5acedf0e6788dc574c7b6f3043ca37092a/src/pages/ReportDetailsPage.tsx#L97).

### What changes do you think we should make in order to solve the problem?
- In ```activeChatMembers```, we should only get the ```accountID``` that has ```personalDetails[accountID```

### What alternative solutions did you explore? (Optional)
NA

**Comment by adelekennedy** [comment] 2024-05-19 21:26
moving this to external and adding to vip-vsb, may juts be a polish but I think we should address it @alitoshmatov one proposal above to review

**Comment by alitoshmatov** [comment] 2024-05-21 20:30
@nkdengineer Can you pinpoint me where exactly this is happening, I am having a hard time understanding this one: 

> When calling API AddMembersToWorkspace to add the account which did not signed in yet, we create an optimistic accountID for this account, then add that accountID to the workspaceMemberChats.participants.

**Comment by nkdengineer** [comment] 2024-05-21 23:14
> Can you pinpoint me where exactly this is happening

1. When searching for the account that is not signed in yet, we generate a random one in [here](https://github.com/Expensify/App/blob/e8ae3c5acedf0e6788dc574c7b6f3043ca37092a/src/libs/OptionsListUtils.ts#L1608)

2. Then, when calling API AddMembersToWorkspace, we add that random accountID to workspaceMemberChats.participants.

**Comment by nkdengineer** [comment] 2024-05-21 23:20
> we create an optimistic accountID for this account

You can see it by:

1. Go offline then open any workspace invite member page.

2. Invite the user that you do not have contact yet.

3. In workspace member page, click on the user invited in step 2 and see the accountID in URL

4. Go online. In workspace member page, click on the user invited in step 2 and see the accountID in URL

**Comment by alitoshmatov** [comment] 2024-05-26 18:35
@nkdengineer I think we are not addressing the real root cause, this issue is only happening right after inviting new member but if we are to refresh the page or come back later the issue is no longer present, meaning that there is already a mechanism to remove temporary account id, we should focus on why it is not immediately removing this id after user data is fetched preventing two ids for the same user

**Comment by nkdengineer** [comment] 2024-05-27 08:58
@alitoshmatov When you refreshing the page, the API ```OpenReport``` is called, then the correct ```report.participants``` is returned, that leads to the issue is no longer present.

**Comment by alexpensify** [comment] 2024-05-28 19:30
Thanks, @adelekennedy, for the help here. I'm back online and taking over again as the BZ member here.

**Comment by nkdengineer** [comment] 2024-05-30 19:17
@alitoshmatov Do you have any feedback about my comment [above](https://github.com/Expensify/App/issues/42262#issuecomment-2132999988)?

**Comment by nkdengineer** [comment] 2024-06-01 02:54
I updated alternative solution

**Comment by alitoshmatov** [comment] 2024-06-02 19:11
Let's go with @nkdengineer 's [proposal](https://github.com/Expensify/App/issues/42262#issuecomment-2117113009), specifically alternative solution

C+ reviewed 🎀 👀 🎀

**Comment by arosiclair** [comment] 2024-06-03 13:43
> Let's go with @nkdengineer 's [proposal](https://github.com/Expensify/App/issues/42262#issuecomment-2117113009), specifically alternative solution
> 
> C+ reviewed 🎀 👀 🎀

Agree, let's use the alternate solution. Please be sure to test inviting both emails that do exist and emails that do not exist.

**Comment by nkdengineer** [comment] 2024-06-04 11:03
@alitoshmatov  this [PR](https://github.com/Expensify/App/pull/43024) is ready for preview

**Comment by mvtglobally** [comment] 2024-06-05 21:23
Issue not reproducible during KI retests. (First week)

**Comment by alexpensify** [comment] 2024-06-11 23:03
Weekly Update: @alitoshmatov please keep us posted if you can't review this PR, thanks!

**Comment by alexpensify** [comment] 2024-06-18 21:58
Weekly Update: Waiting for the PR to go to Prod.

**Comment by alexpensify** [comment] 2024-06-27 20:45
Automation worked here, I'll work on the payment process tomorrow.

**Comment by alexpensify** [comment] 2024-06-28 17:38
Payouts due: 2024-06-28

- [x] Contributor: $250 @arosiclair 
- [ ] Contributor+: $250 @alitoshmatov  

Upwork job is [here](https://www.upwork.com/jobs/~0110eb98a4dc986510).

Status: Everyone has been paid in Upwork.

**Closed by alexpensify** 2024-06-28 17:38 UTC
Labels: External, Daily, Awaiting Payment, Bug
