### ISSUE TITLE
[HOLD  #24452] Cursor does not auotfocus when Reply in thread and go back

### ISSUE THREAD

**Issue by m-natarajan** [Expensify/App#35467] opened 2024-01-31 12:46 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.34-0
**Reproducible in staging?:** yes
**Reproducible in production?:** no
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** Applause internal team
**Slack conversation:**

## Action Performed:
1. Go to https://staging.new.expensify.com/
2. On a conversation send a message
3. Reply in thread of that message
4. Click on the header link to go back

## Expected Result:
Chat is focused when Reply in thread and go back

## Actual Result:
Focus is lost when Reply in thread and go back

## Workaround:
Can the user still use Expensify without this being fixed? Have you informed them of the workaround?

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

https://github.com/Expensify/App/assets/38435837/bdf7347f-2ad8-4dfc-b34f-3a5988531241

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~0124cc089e9b34bbda</li>
        <li>Upwork Job ID: 1762855625558597632</li>
        <li>Last Price Increase: 2024-02-28</li>
    </ul>
</details>

**Comment by m-natarajan** [comment] 2024-01-31 12:58
We think this bug might be related to #vip-vsb

**Comment by situchan** [comment] 2024-01-31 14:49
I managed to find offending PR. [Commented](https://github.com/Expensify/App/pull/33929/files#r1472936606) with the root cause.
cc: @kubabutkiewicz

**Comment by vishrutagarwal97** [comment] 2024-01-31 15:23
Hello! How to contribute to Expensify ?

**Comment by vishrutagarwal97** [comment] 2024-01-31 15:25
Contributor details
Your Expensify account email: vishrutagarwal97@gmail.com
Upwork Profile Link: https://www.upwork.com/freelancers/~01c00d1d3da8d6daee

**Comment by vishrutagarwal97** [comment] 2024-01-31 15:27
Contributor details
Your Expensify account email: vishrutagarwal97@gmail.com
Upwork Profile Link: https://www.upwork.com/freelancers/~01c00d1d3da8d6daee

**Comment by youssef-lr** [comment] 2024-01-31 15:42
Thanks @situchan!

**Comment by youssef-lr** [comment] 2024-01-31 15:43
Demoting this as it's a minor bug. @kubabutkiewicz when you have a second please @situchan has left a comment in your PR.

**Comment by kubabutkiewicz** [comment] 2024-02-01 19:46
Hi @youssef-lr I am looking at this issue and what I found is that we are no able to just revert change which cause this regression because is causing TS error in `WithOnyx` hook because from `key` function we need to return onyx collection or entry and undefined is forbidden, but also what I noticed that this code which caused this regression was some sort of work around for this issue with not re focusing composer, for example when I removed that AttachmentModal component (which caused this regression) from `ReportActionCompose` where its used and te focus/unfocus is happening the issue is still there. Currently looking into it found that there extra `onBlur` event is causing the bug here but not sure where its happening. But I also noticed that here https://github.com/Expensify/App/issues/24452#issuecomment-1915027525 they are working on completely refactoring re-focus behaviour so maybe they will also fix that issue. Will keep you updated

**Comment by youssef-lr** [comment] 2024-02-02 21:52
Sounds good @kubabutkiewicz, thanks for the update!

**Comment by youssef-lr** [comment] 2024-02-06 17:22
Not overdue.

**Comment by youssef-lr** [comment] 2024-02-12 22:10
Not overdue. Waiting for updates.

**Comment by kubabutkiewicz** [comment] 2024-02-15 08:56
@youssef-lr Still waiting for resolving this https://github.com/Expensify/App/issues/24452#issuecomment-1915027525

**Comment by youssef-lr** [comment] 2024-02-16 13:55
Sounds good, thanks for the update!

**Comment by youssef-lr** [comment] 2024-02-20 04:38
No update yet.

**Comment by youssef-lr** [comment] 2024-02-22 01:14
No update yet.

**Comment by youssef-lr** [comment] 2024-02-23 20:59
Same.

**Comment by youssef-lr** [comment] 2024-02-26 12:35
No updates yet.

**Comment by youssef-lr** [comment] 2024-02-28 02:22
Same.

**Comment by youssef-lr** [comment] 2024-03-02 05:41
@kubabutkiewicz should this be on hold for https://github.com/Expensify/App/issues/24452#issuecomment-1915027525? it' s not clear to me how they're related if you could let me know please, thanks 🙇

**Comment by kubabutkiewicz** [comment] 2024-03-04 09:00
I think yes, we can put it on hold, in the issue mentioned they are working on  completely refactor refocusing of composer so it should probably fix also this issue.

**Comment by kubabutkiewicz** [comment] 2024-03-04 12:19
ok, I thought it will be whole rewrite of refocus functionality, so I will work on this soon

**Comment by youssef-lr** [comment] 2024-03-04 14:03
Cool, thanks for confirming folks!

**Comment by mallenexpensify** [comment] 2024-03-04 20:02
Put on hold, pending the below, bumped to weekly
- https://github.com/Expensify/App/issues/24452

**Comment by mallenexpensify** [comment] 2024-03-07 16:26
I'm going to close this for now because we're hyper-focusing on on VIP/Wave projects and our roadmap.  I view this as a nice-to-have but it's not keeping someone from using the product.

**Closed by mallenexpensify** 2024-03-07 16:26 UTC
Labels: Engineering, Weekly, Internal, Bug
