### ISSUE TITLE
LHN - Transaction thread changes to [Deleted message] after reloading

### ISSUE THREAD

**Issue by izarutskaya** [Expensify/App#26191] opened 2023-08-29 12:25 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Send a money request from account A to account B
2. Open the transaction thread and click on the amount
3. Change the amount
4. Go back twice or open the chat page
5. Reload the page
6. Observe the transaction thread on LHN

## Expected Result:
 Transaction thread should not turn to a [Deleted message]

## Actual Result:
Transaction thread changes to [Deleted message] upon reloading the page

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [x] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** v1.3.58-1

**Reproducible in staging?:** Y

**Reproducible in production?:** N 

**If this was caught during regression testing, add the test name, ID and link from TestRail:**

**Email or phone of affected tester (no customers):**

**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/115492554/172e4a02-808b-466d-a68e-9f75c0efc19b

https://github.com/Expensify/App/assets/115492554/3b3a377a-08d2-415f-94f1-1229a226576d

**Expensify/Expensify Issue URL:**

**Issue reported by:** @Nathan-Mulugeta

**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1693299858979649

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~018ab5c075ccb14fca</li>
        <li>Upwork Job ID: 1696634543518457856</li>
        <li>Last Price Increase: 2023-08-29</li>
    </ul>
</details>

**Comment by dangrous** [comment] 2023-08-29 13:47
Looking into this. Based on how it's presenting, it's something to do with it handling the response from the server. I'm hoping it's still a FE issue and not something on the backend?

**Comment by joekaufmanexpensify** [comment] 2023-08-29 14:35
I just checked and I can reproduce on staging only.

**Comment by dangrous** [comment] 2023-08-29 16:52
I have a (probably bad) hunch that it might be something to do with https://github.com/Expensify/Web-Expensify/pull/38626 and it not finding the right message/info for the parent report. But as that gets investigated hopefully we'll get some answers!

**Comment by luacmartins** [comment] 2023-08-29 17:57
@dangrous I agree that the root cause seems to come from https://github.com/Expensify/Web-Expensify/pull/38626

**Comment by luacmartins** [comment] 2023-08-29 20:11
Fix here - https://github.com/Expensify/Web-Expensify/pull/38665. The fix is in Web-E, so gonna remove the blocker label

**Comment by chiragsalian** [comment] 2023-08-29 20:55
Resolved on staging with a web-E CP. Closing issue. If it persists feel free to reopen.

**Comment by Nathan-Mulugeta** [comment] 2023-08-29 21:21
Hey guys payment for issue reporter has not been processed

**Comment by joekaufmanexpensify** [comment] 2023-08-29 21:22
Good call, sorry about that @Nathan-Mulugeta !

**Comment by joekaufmanexpensify** [comment] 2023-08-29 21:23
@Nathan-Mulugeta offer sent for $250!

**Comment by Nathan-Mulugeta** [comment] 2023-08-29 21:25
Great, I just accepted the offer.

**Comment by joekaufmanexpensify** [comment] 2023-08-29 21:31
@Nathan-Mulugeta $250 sent and contract ended!

**Comment by joekaufmanexpensify** [comment] 2023-08-29 21:31
Upwork job closed.

**Closed by joekaufmanexpensify** 2023-08-29 21:31 UTC
Labels: Engineering, Daily, Internal, Bug
