### ISSUE TITLE
[$500] IOU - App crashes after editing all empty request fields in IOU details page in offline mode

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#32663] opened 2023-12-07 13:41 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.9-2
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** Applause - Internal Team
**Slack conversation:**

## Action Performed:
1. Log in to [applausetester+kh@applause.expensifail.com](mailto:applausetester+kh@applause.expensifail.com)
(This account has a lot of unpaid IOU)
2. Go offline
3. Go to a chat with user called Flower (pinned)
4. Tap on the unpaid IOU preview
5. Tap on any preview
6. Edit the amount, description, merchant and date field in the correct order

## Expected Result:
In Step 5, the IOU preview will show skeleton loading
In Step 6, app will not crash

## Actual Result:
In Step 5, the IOU preview shows IOU details page with empty fields
In Step 6, after saving the date, the app crashes

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [x] Android: mWeb Chrome
- [x] iOS: Native
- [x] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details> 

https://github.com/Expensify/App/assets/78819774/4a8f005f-19ee-4eb4-9a57-2bcb6b515c27

[logs.txt](https://github.com/Expensify/App/files/13600801/logs.txt)

 
[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01c03aa534f5e5c9a2</li>
        <li>Upwork Job ID: 1732757258160873472</li>
        <li>Last Price Increase: 2023-12-07</li>
    </ul>
</details>

**Comment by DylanDylann** [comment] 2023-12-07 14:25
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
In Step 5, the IOU preview shows IOU details page with empty fields
In Step 6, after saving the date, the app crashes

### What is the root cause of that problem?
When offline and navigating to the transaction thread report, the transaction is not loaded
So that in here

https://github.com/Expensify/App/blob/10727a7979709987c77e94a2d059f56bd09fa5eb/src/libs/ReportUtils.ts#L2070-L2071

`reportActionOriginalMessage?.oldCreated` will be undefined because this field is get from transaction. It caused crash app


### What changes do you think we should make in order to solve the problem?
We can disable all field and don't allow user editting all field in `MoneyRequestView` If transaction is empty (isn't loaded from server)


### What alternative solutions did you explore? (Optional)
We can load all transactions right after user login successful

**Comment by situchan** [comment] 2023-12-07 14:41
Not able to reproduce. Is there any clear repro step to see transaction date unset?

**Comment by DylanDylann** [comment] 2023-12-07 14:55
@situchan Because the RCA is that user offline before the transaction is not loaded. You can log out and log in again to make sure ONYX is clear then try to reproduce again

**Comment by narefyev91** [comment] 2023-12-07 16:15
After reviewing proposals i come to this conclusion:
Correct root case - that we trying to format "Invalid Data" because of `reportActionOriginalMessage?.oldCreated is empty string`.
We do not have a huge restriction to prevent user in opening anything during loading and editing something which may be potentially empty/not loaded at all - and i do not think we should do it. Based on that - we should just have a fallback to not run `format` function from `data-fns` based on the proposal from @gijoe0295 https://github.com/Expensify/App/issues/32663#issuecomment-1845466456
🎀 👀 🎀 C+ reviewed

**Comment by DylanDylann** [comment] 2023-12-07 18:40
@narefyev91 even if user edit field, it is not updated. What do you think about this bug?

**Comment by narefyev91** [comment] 2023-12-08 07:51
`The main root case - is that we allow user to interact with items which are not fully loaded`. But i think this is happened almost everywhere in the app... and we continue getting bugs in offline workflows
Yes we have mostly 3 options here - either fix crash because it's very important by `adding safe checks` or we `fully disable ability to view` loading items or we `disable editing logic` allowing user to open item.
But based on preferable feelings - i will say that we may still continue getting bugs, when user will try to do anything with not fully loaded items. 
- If we will decide to prevent user in viewing loading item - we can go with @tienifr proposal https://github.com/Expensify/App/issues/32663#issuecomment-1845582051. @gijoe0295 alternative proposal is closely to @tienifr proposal but @tienifr also indicate change for deep link navigation - which is also very important.
- if we plan to only block editing we can go with @DylanDylann proposal
- if we plan just to fix crash and do not make any changes in flow - we can still go with @gijoe0295 proposal
In any case let's wait @marcochavezf final decision
Thank you all!

**Comment by narefyev91** [comment] 2023-12-11 09:06
Friendly ping @marcochavezf

**Comment by rojiphil** [comment] 2023-12-12 08:49
@narefyev91 @marcochavezf 

While it may be sufficient to prevent the user from interacting with non-loaded contents, I think the question is also why the Transaction Thread/Report is not present in the FE. If the IOU Report is present, shouldn’t the Transaction Report be also present in FE during offline workflows? Or am I missing something simple here?

Have also raised a related query in Slack [here](https://expensify.slack.com/archives/C01GTK53T8Q/p1702369258137099)

**Comment by CortneyOfstad** [comment] 2023-12-12 13:49
Hey! Sorry for the confusion here, but we just got an internal update. Per [this post](https://expensify.enterprise.slack.com/archives/C01SKUP7QR0/p1702341886807759), we can close any bugs that are not related to Waves, so closing this out 👍 We will re-address once the waves are completed.

**Closed by CortneyOfstad** 2023-12-12 13:49 UTC
Labels: External, Daily, Help Wanted, Bug
