### ISSUE TITLE
[HOLD for payment 2024-07-10] [HOLD for payment 2024-07-02] [$250] Context/popover menus have incorrect border radius

### ISSUE THREAD

**Issue by m-natarajan** [Expensify/App#42716] opened 2024-05-28 17:42 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.76-4
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** @dannymcclain 
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1716913234239859

## Action Performed:
1. Go to NewDot
2. Open context menu, Edit comment Global create (any context menu)
 
## Expected Result:
Context/popover menus should use one of our predefined border radius variables. Not an engineer, but I would think componentBorderRadiusLarge (https://github.com/Expensify/App/blob/95d328fb90c2bca9b57255ed645dcb3f363d64e5/src/styles/variables.ts#L28), which is 16px.

## Actual Result:
The border radius of context menus is 12px.

## Workaround:
unknown
## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence
![image (3)](https://github.com/Expensify/App/assets/38435837/b7fe21b6-6de5-4233-9283-4161088ccfac)
![Screenshot 2024-05-28 133907](https://github.com/Expensify/App/assets/38435837/55fdf678-5111-4e00-9ec0-54ef8afe9a23)
![Screenshot 2024-05-28 133946](https://github.com/Expensify/App/assets/38435837/da42ec89-d592-4316-ba31-58ec16b8e839)

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~015010f0cbb4319b2e</li>
        <li>Upwork Job ID: 1798225869486452736</li>
        <li>Last Price Increase: 2024-06-05</li>
<li>Automatic offers: </li>
<ul>
<li>rojiphil | Reviewer | 102612211</li>
<li>s77rt | Contributor | 102712893</li>
</ul></li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @rojiphil</details>

**Comment by JmillsExpensify** [comment] 2024-06-05 05:30
Opening up to the community given that we have proposals.

**Comment by rojiphil** [comment] 2024-06-05 12:20
Thanks for all your proposals. 
@dragnoir [proposal](https://github.com/Expensify/App/issues/42716#issuecomment-2136173320) LGTM as the border-radius of pop-over menu alone has to be updated. The other proposals (i.e. [here](https://github.com/Expensify/App/issues/42716#issuecomment-2135822744) and [here](https://github.com/Expensify/App/issues/42716#issuecomment-2135827498)) suggested changing at multiple places which is not correct.
🎀👀🎀 C+ reviewed

**Comment by s77rt** [comment] 2024-06-12 23:46
I will take this one

**Comment by s77rt** [comment] 2024-06-13 03:04
@Expensify/design 

I have raised the [PR](https://github.com/Expensify/App/pull/43627) but I don't really think we need it. The 12px is used in many places and it's a multiple of 4 (as per the design requirement).

> Context/popover menus should use one of our predefined border radius variables

Maybe we should just add 12 to the border radius variables?

**Comment by s77rt** [comment] 2024-06-13 03:06
The 12px is used in confirmation modals too

<img width="1840" alt="Screenshot 2024-06-13 at 4 04 46 AM" src="https://github.com/Expensify/App/assets/16493223/a648a7e7-914f-4e2f-bec4-9eed59a5fdab">

**Comment by shawnborton** [comment] 2024-06-13 06:12
We should update all of those to 16px though, what's in the product seems wrong compared to our design system in Figma. cc @Expensify/design for the gut check though!

**Comment by s77rt** [comment] 2024-06-29 21:48
I don't think checklist applies here. This is more like a design change than an actual bug

**Comment by jasperhuangg** [comment] 2024-07-01 17:51
@s77rt Agree, I think we can skip the checklist. @mallenexpensify If we pay them out I think we can go ahead and close this one out. I'll check everything off the checklist just for consistency.

**Comment by mallenexpensify** [comment] 2024-07-02 23:44
@rojiphil can you please accept the job and reply here once you have? 
https://www.upwork.com/jobs/~015010f0cbb4319b2e

@s77rt , I'm planning to pay you via NewDot, I canceled the Upwork job.

**Comment by rojiphil** [comment] 2024-07-03 18:46
> can you please accept the job and reply here once you have?

@mallenexpensify Accepted. Thanks.

**Comment by mallenexpensify** [comment] 2024-07-05 21:51
Damn it! We got the double post/title update thing happening again. 

Contributor: @s77rt due $250 via NewDot.   
Contributor+: @rojiphil paid $250 via Upwork

Unsure if we need/want a testcase for this, since it's design related.  If so.. it'd be included in the monthly test that QA runs for design and edge cases.  @rojiphil, can you complete the BZ checklist above plz?

@

**Comment by mallenexpensify** [comment] 2024-07-11 01:06
@rojiphil can you complete the BZ checklist above plz?

**Comment by rojiphil** [comment] 2024-07-11 02:40
@mallenexpensify Sorry for the delay here. Here is the BZ checklist

* [x]  [@rojiphil] The PR that introduced the bug has been identified. Link to the PR: [Offending PR](https://github.com/Expensify/App/pull/32498)
* [x]  [@rojiphil] The offending PR has been commented on, pointing out the bug it caused and why, so the author and reviewers can learn from the mistake. Link to comment: [Added comment](https://github.com/Expensify/App/pull/32498/files#r1673306437)
* [x]  [@rojiphil] A discussion in #expensify-bugs has been started about whether any other steps should be taken (e.g. updating the PR review checklist) in order to catch this type of bug sooner. Link to discussion: Not Required. Existing checklist includes the provision to involve design team during styling changes which should catch such issues
* [x]  [@rojiphil] Determine if we should create a regression test for this bug. :  Since the changes are related to styling which is widely used, this is prone to regression. Let’s add regression test case for this. 
* [x]  [@rojiphil] If we decide to create a regression test for the bug, please propose the [regression test](https://github.com/Expensify/App/blob/main/contributingGuides/REGRESSION_TEST_BEST_PRACTICES.md) steps to ensure the same bug will not reach production again. 
1. Click on Global FAB button to show the popover menu
2. Verify that the border radius is of size 16 (This can be verified via `Inspect` window in console on web versions) (#Test 1)
3. Navigate to a report with comments
4. Invoke the context menu for a comment. 
5. Verify that the border radius is of size 16 (#Test 2)
6. Navigate to `Settings` and edit Avatar image to show the context menu
7. Verify that the border radius is of size 16 (#Test 3)
8. Navigate to `Workspace`. For a given workspace, invoke 3Dots Menu popover and select `Delete workspace` to display confirmation modal dialog.
9. Verify that the border radius is of size 16 (#Test 4)

**Comment by mallenexpensify** [comment] 2024-07-12 00:25
Thanks @rojiphil ! 

Commented that the test case is design/edge case and should likely be run monthly 
https://github.com/Expensify/Expensify/issues/412266

**Closed by mallenexpensify** 2024-07-12 00:25 UTC
Labels: External, Daily, Awaiting Payment, Bug

**Comment by JmillsExpensify** [comment] 2024-07-16 04:55
$250 approved for @s77rt
