### ISSUE TITLE
The message /report item should remain highlighted when context menu is being opened.

### ISSUE THREAD

**Issue by kavimuru** [Expensify/App#13139] opened 2022-11-29 17:03 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:

1. Open the app on web.
2. Open any report/chat.
3. Hover over any message.
4. Notice the highlighted background of the message.
5. Right click to open the context menu.

## Expected result: 
The message/report item background should remain highlighted when context is being opened.

## Actual result: 
The background flickers between highlighted and normal state when context is opened.

## Workaround:
unknown

## Platform:

Where is this issue occurring?

- Web
- Desktop App

**Version Number:** v1.2.33-2
**Reproducible in staging?:** y
**Reproducible in production?:** n
**Email or phone of affected tester (no customers):** 
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** 

https://user-images.githubusercontent.com/43996225/204594540-86526d63-77e5-4e1b-95fd-a57b1160df3d.mp4

https://user-images.githubusercontent.com/43996225/204594572-58ebd346-50df-4090-b003-87d73bf7d322.mp4

**Expensify/Expensify Issue URL:** 
**Issue reported by:** @parasharrajat 
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1669647312018439

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by thesahindia** [comment] 2022-11-29 17:08
It's also on production. Not a blocker.

**Comment by arosiclair** [comment] 2022-11-29 17:15
Yep reproduced both in **staging v1.2.33-2** and **prod v1.2.32-2**. Closing

**Comment by parasharrajat** [comment] 2022-11-30 13:59
I do not get the reason for closing this. Because it is present on PROD, we are not fixing it.

**Comment by parasharrajat** [comment] 2022-11-30 18:11
@arosiclair Bump.

**Comment by arosiclair** [comment] 2022-11-30 18:32
Yep good point I closed this by accident. Let's mark this as a regular bug, not a blocker

**Comment by arosiclair** [comment] 2022-11-30 21:01
@bfitzexpensify I'll just take this internal if this issue passes your BZ checks

**Comment by bfitzexpensify** [comment] 2022-11-30 21:11
### Bug0 Triage Checklist
_Note: see [this SO](https://stackoverflow.com/c/expensify/questions/14418) for more information._
- [x] The "bug" is actually a bug 
- [x] The bug is not a duplicate report of an existing GH.
  - If it is, close the GH and add any novel details to the original GH instead 
- [x] The bug is reproducible, following the reproduction steps.
- [x] The GH template is filled out as fully as possible
  - The GH body and title are clear (ie. could an external contributor understand it and work on it?) 
- [x] The GH was created by an Expensify employee or a QA tester 

Good to for you to takeover @arosiclair!

**Comment by marcaaron** [comment] 2022-12-01 05:36
I agree with @arosiclair's instinct here. low value and isn't clearly broken. I'd vote we close.

**Comment by arosiclair** [comment] 2022-12-01 16:25
Yeah definitely low value but seems easy to fix and I got the bandwidth to fix it so might as well

**Comment by arosiclair** [comment] 2022-12-13 20:40
PR was merged and should've have been deployed to staging in **1.2.37-0**. Not sure if it has hit prod yet. Weird how this is not getting any updates from melvinbot... Either way, I'll close this out as completed.

**Comment by arosiclair** [comment] 2022-12-14 19:21
Good call I thought this was just caught by applause

**Comment by bfitzexpensify** [comment] 2022-12-15 12:48
Reporting bonus paid, we're good to close

**Closed by bfitzexpensify** 2022-12-15 12:48 UTC
Labels: Reviewing, Engineering, Daily, Bug

**Comment by sobitneupane** [comment] 2022-12-23 10:32
@bfitzexpensify I am C+ in the [PR](https://github.com/Expensify/App/pull/13249). Can you please help me with the payment.
