### ISSUE TITLE
 Search - Deleted message displayed for previously visited threads from left public room

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#50475] opened 2024-10-08 19:33 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 9.0.46-3
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**If this was caught during regression testing, add the test name, ID and link from TestRail:** N/A
**Issue reported by:** Applause - Interrnal Team

## Action Performed:
1. Go to https://staging.new.expensify.com/
and log in
2. Navigate to a public room https://staging.new.expensify.com/r/2091104345528462
3. Open a few threads and do not comment
4. Leave the room
5. Navigate to Search

## Expected Result:
The parent message of the thread is displayed

## Actual Result:
[Deleted message] is displayed until the thread is reopened again

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

<details>
  <summary>Add any screenshot/video evidence</summary>

  
</details> 

https://github.com/user-attachments/assets/628fdbe7-f34a-4cbe-8450-7cf7fd716414

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by lanitochka17** [comment] 2024-10-08 19:34
@JmillsExpensify  FYI I haven't added the External label as I wasn't 100% sure about this issue. Please take a look and add the label if you agree it's a bug and can be handled by external contributors

**Comment by bernhardoj** [comment] 2024-10-09 07:43
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
The public room thread shows Deleted message in the search list when leaving public room.

### What is the root cause of that problem?
A thread title is based on the parent report data (the report actions specifically), in this case, the public room. When we leave a public room, BE will clear the report and report actions from Onyx.
<img width="379" alt="image" src="https://github.com/user-attachments/assets/2b60364e-60cb-4cc1-bd7c-e0e5326bb917">

Thus, a [Deleted message] is shown.
https://github.com/Expensify/App/blob/7947b8e25c9c4799f8bec6e3986d129db06a2939/src/libs/ReportUtils.ts#L3628-L3630

### What changes do you think we should make in order to solve the problem?

We can clear all child report of a public room when leaving.
```
let reportsToClear;
if (ReportUtils.isPublicRoom(report)) {
    reportsToClear = Object.values(reports).filter((r): r is Report => ReportUtils.isThread(r) && ReportUtils.getRootParentReport(r)?.reportID === report.reportID);
    reportsToClear.forEach((reportToClear) => {
        optimisticData.push({
            onyxMethod: Onyx.METHOD.SET,
            key: `${ONYXKEYS.COLLECTION.REPORT}${reportToClear.reportID}`,
            value: null,
        });
        failureData.push({
            onyxMethod: Onyx.METHOD.SET,
            key: `${ONYXKEYS.COLLECTION.REPORT}${reportToClear.reportID}`,
            value: reportToClear,
        });
    });
}
```

After leaving the room, the user will be navigated to the most recent accessed report, ignoring the current report that we are leaving. However, since we clear the child reports, we also need to ignore the cleared child reports.
https://github.com/Expensify/App/blob/7947b8e25c9c4799f8bec6e3986d129db06a2939/src/libs/actions/Report.ts#L2893-L2894

So, we also need to update `navigateToMostRecentReport` and `findLastAccessedReport` to receive an array of excluded reportID.
```
function navigateToMostRecentReport(currentReport: OnyxEntry<Report>, excludeLastAccessReportIDs: string[]) {
    const lastAccessedReportID = ReportUtils.findLastAccessedReport(false, false, undefined, excludeLastAccessReportIDs)?.reportID;
```

and update the filter logic
```
const shouldFilter = !!excludeReportIDs?.length || ignoreDomainRooms;
if (shouldFilter) {
    reportsValues = reportsValues.filter((report) => {
        if (!report) {
            return false;
        }

        if (!!excludeReportIDs?.length && excludeReportIDs.includes(report?.reportID)) {
            return false;
        }
```

**Comment by JmillsExpensify** [comment] 2024-10-16 18:10
Closing this. It's not a priority.

**Closed by JmillsExpensify** 2024-10-16 18:10 UTC
Labels: Daily, Overdue, Bug
