### ISSUE TITLE
Clicking Enter on the Country page activates the Save button on Home Address Page

### ISSUE THREAD

**Issue by kavimuru** [Expensify/App#23834] opened 2023-07-28 22:16 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Go profile > Personal detail > Home Address Page
2. Click on the Country item
3. Write any county and press Enter
## Expected Result: 
Return back to the Home Address
## Actual Result: 
Clicking Enter activates the Save button on Home Address Page

## Workaround:
Can the user still use Expensify without this being fixed? Have you informed them of the workaround?

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [x] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 1.3.47-2
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/43996225/f110286e-e546-421c-aeb1-3a2333148a6c

https://github.com/Expensify/App/assets/43996225/ae1ce8be-0754-4cb8-adf0-3c8d2027d43e

**Expensify/Expensify Issue URL:**
**Issue reported by:** @daveSeife
**Slack conversation:**  https://expensify.slack.com/archives/C049HHMV9SM/p1690477217945929

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by ygshbht** [comment] 2023-07-29 05:49
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
The problem at hand is that while entering a country name within the **Country Picker** in the **Home Address Page**, pressing Enter inadvertently activates the Save button of the **Home Address Page**.


### What is the root cause of that problem?
This behavior arises because the Country Picker input is part of the Home Address form. Consequently, when Enter is pressed in the Country Picker, it's treated as a form submission, leading to the activation of the Save button.


### What changes do you think we should make in order to solve the problem?
We can approach this issue with several potential solutions:

a) One approach is we could disable the submit and validate functions when the Country Picker modal is open. This could be done by passing dummy validate and submit functions when the modal is open, or by adding a new disableEnterPress prop to the form submit component, which would prevent submission when the modal is active.

a) We could aslo transition the Country Picker to a standalone page, mirroring the structure of pages like the New Task Pages. This could provide a more consistent user experience across the application.

c) We could implement a listener on a component that monitors for the Enter key press and halts its propagation. This listener could be incorporated into a new wrapper component or an existing component in the Country Picker modal.

d) Alternatively, the form submit component could be modified to determine if the element triggering the Enter key press is inside a modal before proceeding with the submit action.

e) Lastly, a combination of these methods could be used to address this issue effectively, depending on specific use cases and testing.

**Comment by s-alves10** [comment] 2023-07-29 06:25
## Proposal

### Please re-state the problem that we are trying to solve in this issue.

Pressing enter on country picker activates the save button on home address page

### What is the root cause of that problem?

When pressing enter key on country picker, keyboard listener receives and handles the enter key event here
https://github.com/Expensify/App/blob/eb020063789091eb2e3086b5b54af3ead8436645/src/components/SelectionListRadio/BaseSelectionListRadio.js#L190-L205

As you can see in `useKeyboardShortcut`, there is no option for stopping propagation of keyboard event. So `enter` key event is propagated and form's `submit` method is called. This is the root cause 

### What changes do you think we should make in order to solve the problem?

We have to stop propagation of keyboard event

1. Add `shouldStopPropagation` option to the `useKeyboardSHortcut` hook
- Add this option to the 3rd parameter of the `useKeyboardSHortcut` hook(`default = false`)

- Add the `shouldStopPropagation` parameter to `KeyboardShortcut.subscribe` function with `default = false`
https://github.com/Expensify/App/blob/eb020063789091eb2e3086b5b54af3ead8436645/src/libs/KeyboardShortcut/index.js#L118

- Add the following code right before the return statement of the `bindHandlerToKeydownEvent` function here
https://github.com/Expensify/App/blob/main/src/libs/KeyboardShortcut/bindHandlerToKeydownEvent/index.js

```
        if (callback.shouldStopPropagation) {
            event.stopPropagation();
        }
```

2. Call the `useKeyboardSHortcut` with config `shouldStopPropagation: true` here
https://github.com/Expensify/App/blob/eb020063789091eb2e3086b5b54af3ead8436645/src/components/SelectionListRadio/BaseSelectionListRadio.js#L201-L204

```
            captureOnInputs: true,
            shouldStopPropagation: true,
            shouldBubble: () => !flattenedSections.allOptions[focusedIndex],
```

3. Update all `useKeyboardSHortcut` and `KeyboardShortcut.subscribe` with the new parameter

This works as expected

<details>
    <summary>Result</summary>


</details>

### What alternative solutions did you explore? (Optional)

**Comment by jliexpensify** [comment] 2023-07-30 23:57
I've reviewed the video and this looks like expected behaviour? When you use `Enter` it should either send a message, or save. In this case, it should save as it's a field we want to fill out.

In regards to the errors in the video, that's because none of the other details are filled in, so it makes sense to throw those errors. The same occurs when you choose a country which has a different address format to the one you've currently entered - below is an example where I've used New Zealand (similar to Australia), but as soon as I switch to the USA, it throws the error:

https://github.com/Expensify/App/assets/30815269/19640ca5-c87d-4bad-a181-42773a53af4e

I'm going to close this GH as this as I don't believe that this is an actual issue.

**Closed by jliexpensify** 2023-07-30 23:57 UTC
Labels: Daily, Bug

**Comment by ygshbht** [comment] 2023-07-31 04:01
Oh I assumed that in the country modal, when a user presses enter, they'd expect to save the country and then return to the address page to continue, not to inadvertently submit the entire form

**Comment by joh42** [comment] 2023-08-28 11:45
@jliexpensify The problem here is the discrepancy between using a mouse compared to using a keyboard. When using a mouse to select a country, the validation is not triggered/we get sent back to the home address page. But when we use a keyboard, the enter event escapes from the [SelectionList](https://github.com/Expensify/App/blob/main/src/components/SelectionList/BaseSelectionList.js) input field, triggering `onSubmit` on the [AddressPage](https://github.com/Expensify/App/blob/main/src/pages/settings/Profile/PersonalDetails/AddressPage.js).

In the video below, I first use my mouse to select an option, then I use my keyboard. As you can see, the behavior is not consistent.

https://github.com/Expensify/App/assets/138504087/af604aa2-daa8-4198-be94-e068a38baa50

I'm going to submit a proposal similar to one I have posted on another issue, but modifying it slightly so it works if we want to submit when the country/state changes.

**Comment by joh42** [comment] 2023-08-28 11:45
I've written a similar proposal on [another issue](https://github.com/Expensify/App/issues/24198). But since we might want to submit when an option has been selected, I'll post a slightly modified version here: 
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
When we use the keyboard to select a country/state, form validation is triggered on the [AddressPage](https://github.com/Expensify/App/blob/main/src/pages/settings/Profile/PersonalDetails/AddressPage.js). The problem is that the same behavior does not occur when we use a mouse to select a country/state. In the below video, I first select using my mouse, which does not trigger onSubmit. But when I do the exact same thing using my keyboard, onSubmit is triggered:

https://github.com/Expensify/App/assets/138504087/f2fed48f-cf2d-4969-8a97-e26a41b60551



### What is the root cause of that problem?
We do not stop the propagation of submit (enter) events originating from the Country/State input field in the [BaseSelectionList](https://github.com/Expensify/App/blob/main/src/components/SelectionList/BaseSelectionList.js) component. This enter event triggers onSubmit for the form on the [AddressPage](https://github.com/Expensify/App/blob/main/src/pages/settings/Profile/PersonalDetails/AddressPage.js).

It is worth noting that if we blur the input field by clicking outside of it, onSubmit will not be triggered. As such, the behavior is even inconsistent when keyboard is being used.
### What changes do you think we should make in order to solve the problem?

I think the cleanest solution is to just stop event propagation right in the [BaseSelectionList](https://github.com/Expensify/App/blob/main/src/components/SelectionList/BaseSelectionList.js) file:
```
    useKeyboardShortcut(CONST.KEYBOARD_SHORTCUTS.ENTER, (event) => {
        event.stopPropagation();
        selectFocusedOption();
    }, {
        captureOnInputs: true,
        shouldBubble: () => !flattenedSections.allOptions[focusedIndex],
        isActive: !activeElement,
    });
```

This requires minimal changes to the codebase. Currently, the code looks like this:
https://github.com/Expensify/App/blob/df510ff83101d045972e8eaf3607b4e923d9b578/src/components/SelectionList/BaseSelectionList.js#L288-L299

If submitting when a country/state has been selected is the desired behavior, we should manually submit in the onAddressChange function, which is triggered when the country/state has been updated:

https://github.com/Expensify/App/blob/df510ff83101d045972e8eaf3607b4e923d9b578/src/pages/settings/Profile/PersonalDetails/AddressPage.js#L183-L187

This makes sure we end up with consistent behavior regardless of whether the user selected a country/state with their keyboard/mouse.

### What alternative solutions did you explore? (Optional)
