### ISSUE TITLE
[$1000] Details - blank shows instead of profile pic and workspace image

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#25447] opened 2023-08-17 23:10 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Create workspace if not created
2. Add workspace image
3. Go to #admins of #announce
4. Go offline
5. Send any message and click on reply in thread option
6. Click on profile pic and workspace image
7. Switch to online
8. Again click on profile pic and workspace image

## Expected Result:
Should show profile pic and workspace image

## Actual Result:
Does not show profile pic and workspace image

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [x] Windows / Chrome 
- [ ] MacOS / Desktop

**Version Number:** 1.3.55-3

**Reproducible in staging?:** Yes

**Reproducible in production?:** No

**If this was caught during regression testing, add the test name, ID and link from TestRail:**

**Email or phone of affected tester (no customers):**

**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/78819774/66df2e63-348d-42af-abbc-80058b4a74af

**Expensify/Expensify Issue URL:**

**Issue reported by:** @GadhiyaManan

**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1692184330658159

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01751027ece6cdd9f4</li>
        <li>Upwork Job ID: 1694056260901515264</li>
        <li>Last Price Increase: 2023-08-22</li>
    </ul>
</details>

**Comment by ShogunFire** [comment] 2023-08-19 14:59
## Proposal

### Please re-state the problem that we are trying to solve in this issue.

The profile pic and workspace image appears as blank

### What is the root cause of that problem?

In RoomHeaderAvatars we pass the icon to display to AttachmentModal here: 
https://github.com/Expensify/App/blob/03cf0b14f82a41db004dfee27799e3cea1608ee5/src/components/RoomHeaderAvatars.js#L33

To retrieve that icon we call the server, when it's offline it fails.

I think this is expected and showing the loading spinner is consistent with other places in the app. The problem is that when we go back online we don't try to retrieve the avatar again. 

### What changes do you think we should make in order to solve the problem?

We need to retrieve the source again when we go back online, for that we can use withNetwork event to rerender when we go back online.

### What alternative solutions did you explore? (Optional)

**Comment by isabelastisser** [comment] 2023-08-21 20:39
I didn't have time to review this today, on my to-do list for tomorrow.

**Comment by isabelastisser** [comment] 2023-08-24 14:34
Not overdue, waiting for more proposals.

**Comment by ShogunFire** [comment] 2023-08-24 14:53
There are two proposals that have not been reviewed I think

**Comment by isabelastisser** [comment] 2023-08-25 15:22
@thesahindia can you please review the proposals above? Thanks!

**Comment by StevenKKC** [comment] 2023-08-25 19:56
I think maybe related to https://github.com/Expensify/App/issues/18057

**Comment by isabelastisser** [comment] 2023-08-29 15:45
Thanks @thesahindia ! Closing this.

**Closed by isabelastisser** 2023-08-29 15:45 UTC
Labels: External, Daily, Help Wanted, Bug
