### ISSUE TITLE
[HOLD for payment 2024-06-20] [HOLD for payment 2024-06-18] [$250] Accounting-Renaming Customers/Projects tag doesn't work and has weird behavior while offline

### ISSUE THREAD

**Issue by kavimuru** [Expensify/App#42957] opened 2024-06-01 11:34 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.78-2
**Reproducible in staging?:** y
**Reproducible in production?:** n
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** Applause internal team
**Slack conversation:**

## Action Performed:
Pre-requisite:
- Account must have a workspace connected with a QBO

1. Navigate to staging.new.expensify.com
2. Go to settings > Workspace and select the workspace you have QBO setup with
3. Go to tags
4. Go to Customers/Projects tag
5. Open any tag and rename it
6. Go offline
7. Go to Customers/Projects tag again and rename a tag
8. Go to Classes tag

## Expected Result:
On step 5 after renaming the tag the renamed tag must appear in the tag list, and on step 8 the renamed tag on step 7 should not appear on Classes tag

## Actual Result:
On step 5 after renaming the tag it is not being reflected on the tag list. And on step 8 while the user is offline and tries to rename the tag in Customers/Projects the renamed tag is visible on Classes tag list.

## Workaround:
unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

https://github.com/Expensify/App/assets/43996225/8639b86b-a1ed-4de9-9654-501853eedbfc

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01f7371d4279355423</li>
        <li>Upwork Job ID: 1797044032564117504</li>
        <li>Last Price Increase: 2024-06-01</li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @sakluger</details>

**Comment by goldenbear101** [comment] 2024-06-02 20:24
Since the issue described with Expensify involves the renaming of tags in the Customers/Projects section not working as expected, particularly when you are offline. I'll get a detailed breakdown of the problem and potential steps to investigate and fix it. Please do keep contact.

**Comment by puneetlath** [comment] 2024-06-03 14:13
Not a blocker as discussed here: https://expensify.slack.com/archives/C036QM0SLJK/p1717423475598289

**Comment by trjExpensify** [comment] 2024-06-03 14:16
I wanted to test this against the latest changes here: https://github.com/Expensify/App/pull/42543 but I can't run an adhoc build on that anymore because it's merged awaiting a staging deploy.

**Comment by carlosmiceli** [comment] 2024-06-03 14:28
Ah, was about to start triaging what to do because I found that the PR that caused this was this one: https://github.com/Expensify/App/pull/42315

@puneetlath Now this would be a regular bug then, correct?

**Comment by trjExpensify** [comment] 2024-06-03 14:32
Yeah, this isn't a deploy blocker - but let's fix it if you know what the issue is and the changes in [this PR](https://github.com/Expensify/App/pull/42543) hasn't solved it already! CC: @hayata-suenaga

**Comment by carlosmiceli** [comment] 2024-06-03 14:41
Not sure what the issue is, just looked at the PRs and this one is almost for sure the one that's causing it. @hayata-suenaga wanna tackle it since you probably have more context on what could be breaking it?

**Comment by carlosmiceli** [comment] 2024-06-03 14:43
@trjExpensify I added the External label over the weekend but should we keep it now?

**Comment by hayata-suenaga** [comment] 2024-06-03 14:54
@carlosmiceli I can take over this 😄

**Comment by hayata-suenaga** [comment] 2024-06-03 17:49
[The PR](https://github.com/Expensify/App/pull/43005) is open

**Comment by hayata-suenaga** [comment] 2024-06-14 06:26
> [@hayata-suenaga] The PR that introduced the bug has been identified. Link to the PR:

This is a new feature. We just didn't account for multi tag before.

> [@hayata-suenaga] The offending PR has been commented on, pointing out the bug it caused and why, so the author and reviewers can learn from the mistake. Link to comment:

N/A

> [@hayata-suenaga] A discussion in #expensify-bugs has been started about whether any other steps should be taken (e.g. updating the PR review checklist) in order to catch this type of bug sooner. Link to discussion:

No need for discussion

> [@hayata-suenaga] Determine if we should create a regression test for this bug.

N/A

> [@hayata-suenaga] If we decide to create a regression test for the bug, please propose the [regression test](https://github.com/Expensify/App/blob/main/contributingGuides/REGRESSION_TEST_BEST_PRACTICES.md) steps to ensure the same bug will not reach production again.

N/A

**Comment by sakluger** [comment] 2024-06-20 18:07
@s77rt do you need to be paid here for the PR review, or are you being paid somewhere else?

**Comment by s77rt** [comment] 2024-06-20 18:32
@sakluger I'm due payment here

**Comment by sakluger** [comment] 2024-06-21 17:38
Summarizing payment on this issue:

Contributor+: @s77rt $250, please request via Newdot

**Closed by sakluger** 2024-06-21 17:38 UTC
Labels: External, Engineering, Daily, Help Wanted, Awaiting Payment, Bug

**Comment by JmillsExpensify** [comment] 2024-06-22 16:57
$250 approved for @s77rt
