### ISSUE TITLE
[HOLD for payment 2024-04-15] Split button has incorrect hover styles

### ISSUE THREAD

**Issue by m-natarajan** [Expensify/App#39020] opened 2024-03-26 21:23 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.56-5
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** @shawnborton 
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1711469875796639

## Action Performed:
1. Click on fab > send money
2. enter amount and click next
3. select a user and go to confirmation page

## Expected Result:
The split button should have hover zones that line up with the two button areas that are split by a border

## Actual Result:
There is a weird overlap and you can trigger the hover zone of one side of the button without fully being hovered over it.

## Workaround:
unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

https://github.com/Expensify/App/assets/38435837/c9ef7c56-e69d-4d1b-87aa-6aa8c8af2e1a

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by nkdengineer** [comment] 2024-03-26 22:00
## Proposal

### Please re-state the problem that we are trying to solve in this issue.

### What is the root cause of that problem?
- In [here](https://github.com/Expensify/App/blob/main/src/components/ButtonWithDropdownMenu/index.tsx#L102)The divider is in the button view
### What changes do you think we should make in order to solve the problem?
- We should move the divider to outside the dropdown button like below:
```
     <Button />
                    <View style={[styles.dropDownButtonCartIconView, innerStyleDropButton]}>
                        <View style={[success ? styles.buttonSuccessDivider : styles.buttonDivider]} />
                    </View>
                    <Button  />
```

### What alternative solutions did you explore? (Optional)
- NA

**Comment by bernhardoj** [comment] 2024-03-27 04:17
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
The hover doesn't take the full width of the button.

### What is the root cause of that problem?
This only happens when the `ButtonWithDropdownMenu` has a `buttonSize` of large. When we set the size to large, the button will have a minimum size of 52.
https://github.com/Expensify/App/blob/1bbb594d1735cab697ac6cba0bf3435c295dc291/src/styles/index.ts#L598-L601
https://github.com/Expensify/App/blob/1bbb594d1735cab697ac6cba0bf3435c295dc291/src/styles/variables.ts#L22

However, the total width of the arrow and divider is only 43 (16 arrow icon + 26 margin horizontal + 1 border width).
<img width="242" alt="image" src="https://github.com/Expensify/App/assets/50919443/d0bf5ed7-eed0-423d-8682-f024d2d45d00">

Then, the button has an align items center style which puts the children to the center.

https://github.com/Expensify/App/assets/50919443/eaae7306-62d2-4e79-80b3-2241c7c5ac56

You can also notice that this doesn't happen in a smaller size.

https://github.com/Expensify/App/assets/50919443/acb5c54e-3f68-4af5-8048-cc8ad31a04c2

### What changes do you think we should make in order to solve the problem?

First, move the divider element to the direct child of the Button.
https://github.com/Expensify/App/blob/1bbb594d1735cab697ac6cba0bf3435c295dc291/src/components/ButtonWithDropdownMenu/index.tsx#L102

Next, add flex row style to the Button `innerStyles`.

Last, add `styles.flex1, styles.justifyContentCenter` styles to the dropdown view wrapper. This will align the arrow to the center and take all available space.
https://github.com/Expensify/App/blob/1bbb594d1735cab697ac6cba0bf3435c295dc291/src/components/ButtonWithDropdownMenu/index.tsx#L101

```
<Button ...
    innerStyles={[..., styles.flexRow, ...]} ...
>
    <View style={[success ? styles.buttonSuccessDivider : styles.buttonDivider]} />
    <View style={[styles.dropDownButtonCartIconView, styles.flex1, styles.justifyContentCenter, innerStyleDropButton]}>
... 
```

### What alternative solutions did you explore? (Optional)
Adjust the arrow icon margin left and right based on the button size so the whole width is equal or bigger than the button min width.

**Comment by shawnborton** [comment] 2024-03-27 12:16
Actually @narefyev91 is saying that this is fixed on production already? 

https://github.com/Expensify/App/assets/2319350/965fbf11-80ea-4c76-b93e-34106f2e033c

**Comment by narefyev91** [comment] 2024-03-27 12:53
will take this one as it was coming from global button refactoring

**Comment by CortneyOfstad** [comment] 2024-03-27 14:28
Assigned you to the issue @narefyev91 👍

**Comment by CortneyOfstad** [comment] 2024-04-15 13:46
For some reason job link did not post — https://www.upwork.com/ab/applicants/1779868341125738496/job-details

**Comment by akinwale** [comment] 2024-04-15 13:48
@CortneyOfstad Accepted. Thanks!

**Comment by akinwale** [comment] 2024-04-15 13:53
> * [x]  [@akinwale] The PR that introduced the bug has been identified. Link to the PR:
> * [x]  [@akinwale] The offending PR has been commented on, pointing out the bug it caused and why, so the author and reviewers can learn from the mistake. Link to comment:
> * [x]  [@akinwale] A discussion in #expensify-bugs has been started about whether any other steps should be taken (e.g. updating the PR review checklist) in order to catch this type of bug sooner. Link to discussion:

Not a regression. This is a design change following a global button refactor.

> * [x]  [@akinwale] Determine if we should create a regression test for this bug.
> * [x]  [@akinwale] If we decide to create a regression test for the bug, please propose the [regression test](https://github.com/Expensify/App/blob/main/contributingGuides/REGRESSION_TEST_BEST_PRACTICES.md) steps to ensure the same bug will not reach production again.

**Regression Test Steps**
1. Launch Expensify
2. Click on the global create menu and select Send Money
3. Enter an amount and click Next
4. Select a recipient and continue to the confirmation page
5. Hover the mouse on each side of the button separated by the divider (text on the lhs, icon on the rhs).
6. Verify that the hover effect is separated by the divider.

Do we agree 👍 or 👎?

**Comment by CortneyOfstad** [comment] 2024-04-15 16:47
## Payment Summary

@akinwale — paid $500 via Upwork

**Comment by CortneyOfstad** [comment] 2024-04-15 16:49
Regression test created here — https://github.com/Expensify/Expensify/issues/387839. Closing!

**Closed by CortneyOfstad** 2024-04-15 16:49 UTC
Labels: Daily, Awaiting Payment, Bug
