### ISSUE TITLE
[$500] Task - Cancel task option appears even after task was cancelled by other user

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#28808] opened 2023-10-04 12:23 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Click on + button and select assign task option
2. Enter title and assignee task to userB
4. Create task
5. Go to task thread
6. Click on three dots
7. From userB, cancel the task

## Expected Result:
Cancel option should not show for userA after task is deleted

## Actual Result:
Cancel option shows

## Workaround:
Unknown 

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android / native
- [x] Android / Chrome
- [x] iOS / native
- [x] iOS / Safari
- [x] MacOS / Chrome / Safari
- [x] MacOS / Desktop

**Version Number:** 1.3.77.3
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/93399543/64c8496f-c8ec-4971-9ade-836aa65f181b

https://github.com/Expensify/App/assets/93399543/48146729-5761-4481-be0c-5a414d75beed

https://github.com/Expensify/App/assets/93399543/0e06f98d-9d53-4312-9275-48f76195487b

https://github.com/Expensify/App/assets/93399543/5e5e764b-e34b-4619-bebc-e1dbdd871f02

https://github.com/Expensify/App/assets/93399543/dc0c2954-0a18-4d08-9102-162d656f17b1

https://github.com/Expensify/App/assets/93399543/afabce00-4e24-49f5-a147-d3798b45e28c

https://github.com/Expensify/App/assets/93399543/71b45386-dddd-412f-bfa6-c2c011b1d771

**Expensify/Expensify Issue URL:**
**Issue reported by:** @gadhiyamanan 
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1696328082885309

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01edf544ccba8f9869</li>
        <li>Upwork Job ID: 1709544807184429056</li>
        <li>Last Price Increase: 2023-10-11</li>
    </ul>
</details>

**Comment by DylanDylann** [comment] 2023-10-04 12:25
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
- Cancel task option appears even after task was cancelled by other user

### What is the root cause of that problem?
- The "Cancel task" option is displayed if the ```canModifyTask(taskReport)```returns true and also ```ReportUtils.isCanceledTaskReport(taskReport)```returns false in the case of this bug:
https://github.com/Expensify/App/blob/be98ca20f54c59e575dad21846293d642f1da1df/src/libs/actions/Task.js#L880-L883
- When the user B clicks "Cancel task", it works properly from user B, but in user A, the taskReport is just updated with the below data: 
```
    "lastMessageText": "deleted task: 444",
    "lastActorAccountID": 15802415,
    "lastReadTime": "2023-10-03 15:02:28.266"
```
- With the above data, it is not enough information for the ```ReportUtils.isCanceledTaskReport(taskReport)``` to return true. So it leads to the ```canModifyTask(taskReport)``` still true and the "Task cancelled" still displays.

### What changes do you think we should make in order to solve the problem?
- When user B clicks "Task cancelled", the reportActions collections for this task report will be merged with the new action, like below:
```
{
actionName: "TASKCANCELLED",
...
}
```
- Based on the above report action, we can get the up-to-date state of this task report by update the ```ReportUtils.isCanceledTaskReport``` `s logic from https://github.com/Expensify/App/blob/d2c573fae7e3cba0173254ec78836ac65944ce2e/src/libs/ReportUtils.js#L204-L214 to
```
function isCanceledTaskReport(report = {}, parentReportAction = {}) {
...
    if (some(ReportActionsUtils.getAllReportActions(report.reportID), (reportAction) => reportAction.actionName === CONST.REPORT.ACTIONS.TYPE.TASKCANCELLED)) {
        return true;
    }
...
}
```
### What alternative solutions did you explore? (Optional)
- NA

### Result

[Screencast from 03-10-2023 22:41:00.webm](https://github.com/Expensify/App/assets/141406735/eec76b67-ca1e-4794-873e-7e91db9db0fa)

**Comment by abzokhattab** [comment] 2023-10-04 16:29
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
Task menu items are not updated on report change while the menu is opened
### What is the root cause of that problem?
in the following logic, we push the menu items to an array and display them only when the three-dot icon is clicked, whenever it's opened we don't update the menu even when the  `props`  change 

https://github.com/Expensify/App/blob/a6eaf02e66c541cf031c90a58036b440d9fa9b5a/src/pages/home/HeaderView.js#L94-L179


### What changes do you think we should make in order to solve the problem?
we should use  `useEffect` to alway listen for changes in the `props` and recalculate the items array: 

```javascript
    const [threeDotMenu, setThreeDoMenu] = useState([]);
```


```diff
+ useEffect(() => {
        // We hide the button when we are chatting with an automated Expensify account since it's not possible to contact
        // these users via alternative means. It is possible to request a call with Concierge so we leave the option for them.
        const threeDotMenuItems = [];
        if (isTaskReport && !isCanceledTaskReport) {
            const canModifyTask = Task.canModifyTask(props.report, props.session.accountID);

            // Task is marked as completed
            if (ReportUtils.isCompletedTaskReport(props.report) && canModifyTask) {
                threeDotMenuItems.push({
                    icon: Expensicons.Checkmark,
                    iconFill: themeColors.icon,
                    text: props.translate('task.markAsIncomplete'),
                    onSelected: () => Task.reopenTask(props.report),
                });
            }

            // Task is not closed
            if (props.report.stateNum !== CONST.REPORT.STATE_NUM.SUBMITTED && props.report.statusNum !== CONST.REPORT.STATUS.CLOSED && canModifyTask) {
                threeDotMenuItems.push({
                    icon: Expensicons.Trashcan,
                    iconFill: themeColors.icon,
                    text: props.translate('common.cancel'),
                    onSelected: () => Task.cancelTask(props.report.reportID, props.report.reportName, props.report.stateNum, props.report.statusNum),
                });
            }
        }

        if (isChatThread && !isEmptyChat) {
            if (props.report.notificationPreference === CONST.REPORT.NOTIFICATION_PREFERENCE.HIDDEN) {
                threeDotMenuItems.push({
                    icon: Expensicons.ChatBubbles,
                    iconFill: themeColors.icon,
                    text: props.translate('common.joinThread'),
                    onSelected: () => Report.updateNotificationPreference(props.report.reportID, props.report.notificationPreference, CONST.REPORT.NOTIFICATION_PREFERENCE.ALWAYS, false),
                });
            } else if (props.report.notificationPreference.length) {
                threeDotMenuItems.push({
                    icon: Expensicons.ChatBubbles,
                    iconFill: themeColors.icon,
                    text: props.translate('common.leaveThread'),
                    onSelected: () => Report.leaveRoom(props.report.reportID),
                });
            }
        }

        if (!props.report.isPinned) {
            threeDotMenuItems.push({
                icon: Expensicons.Pin,
                iconFill: themeColors.icon,
                text: props.translate('common.pin'),
                onSelected: Session.checkIfActionIsAllowed(() => Report.togglePinnedState(props.report.reportID, props.report.isPinned)),
            });
        } else {
            threeDotMenuItems.push({
                icon: Expensicons.Pin,
                iconFill: themeColors.icon,
                text: props.translate('common.unPin'),
                onSelected: Session.checkIfActionIsAllowed(() => Report.togglePinnedState(props.report.reportID, props.report.isPinned)),
            });
        }

        if (isConcierge && props.guideCalendarLink) {
            threeDotMenuItems.push({
                icon: Expensicons.Phone,
                iconFill: themeColors.icon,
                text: props.translate('videoChatButtonAndMenu.tooltip'),
                onSelected: () => {
                    Link.openExternalLink(props.guideCalendarLink);
                },
            });
        } else if (!isAutomatedExpensifyAccount && !isTaskReport) {
            threeDotMenuItems.push({
                icon: ZoomIcon,
                iconFill: themeColors.icon,
                text: props.translate('videoChatButtonAndMenu.zoom'),
                onSelected: () => {
                    Link.openExternalLink(CONST.NEW_ZOOM_MEETING_URL);
                },
            });
            threeDotMenuItems.push({
                icon: GoogleMeetIcon,
                iconFill: themeColors.icon,
                text: props.translate('videoChatButtonAndMenu.googleMeet'),
                onSelected: () => {
                    Link.openExternalLink(CONST.NEW_GOOGLE_MEET_MEETING_URL);
                },
            });
        }
+      setThreeDoMenu(threeDotMenuItems);
+    }, [props]);
```

and change the `shouldShowThreeDotsButton` to:

```javascript
    const shouldShowThreeDotsButton = !!threeDotMenu.length;
```

and change the menu items reference to the new state: 
```javascript
                              <ThreeDotsMenu
                                    anchorPosition={styles.threeDotsPopoverOffset(props.windowWidth)}
                                    menuItems={threeDotMenu}
                                />
```
### What alternative solutions did you explore? (Optional)

**Comment by CortneyOfstad** [comment] 2023-10-16 14:52
Not overdue

**Comment by mountiny** [comment] 2023-10-18 17:01
Making this weekly, currently working on wave6 project

**Comment by mountiny** [comment] 2023-10-23 15:50
same as las t week

**Comment by mountiny** [comment] 2023-10-25 13:49
Still not a priority

**Comment by mountiny** [comment] 2023-11-02 12:33
low priority still

**Comment by CortneyOfstad** [comment] 2023-12-12 13:40
Per [this post](https://expensify.enterprise.slack.com/archives/C01SKUP7QR0/p1702341886807759), we can close any bugs that are not related to Waves, so closing this out 👍

**Closed by CortneyOfstad** 2023-12-12 13:40 UTC
Labels: Engineering, Monthly, Internal, Bug
