### ISSUE TITLE
[HOLD for payment 2023-11-09] [$500] Wallet - Once after login, debit card page exits without open

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#30024] opened 2023-10-19 20:19 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.3.87.1
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** @dhanashree-sawant
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1697728465566479

## Action Performed:
1. Open the app
2. If logged in then log out
3. Login again
4. Open settings->wallet
5. Click Add payment method and click bank account
6. Before it redirects, click on back
7. Again click on add payment method
8. Click on debit card and observe that it opens the debit card page for a second and closes it

## Expected Result:
App should not close debit card page directly after opening

## Actual Result:
App closes debit card page directly after opening once after login

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [x] Android: mWeb Chrome
- [ ] iOS: Native
- [x] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos
<details>
<summary>Android: Native</summary>

</details>

<details>
<summary>Android: mWeb Chrome</summary>

 

https://github.com/Expensify/App/assets/93399543/e9cf0a86-ed3d-49bd-9779-b5cccd6145ed

</details>

<details>
<summary>iOS: Native</summary>

 

</details>

<details>
<summary>iOS: mWeb Safari</summary>

 

https://github.com/Expensify/App/assets/93399543/86de0f6e-e223-4cbd-9320-b436a5087ed2

</details>

<details>
<summary>MacOS: Chrome / Safari</summary>

 

https://github.com/Expensify/App/assets/93399543/1b11c173-adac-47ed-9908-54151a115eca

https://github.com/Expensify/App/assets/93399543/2d507454-379f-499d-9b7c-596767da35f4

https://github.com/Expensify/App/assets/93399543/6ebc1cf6-7dda-4ce8-9cc2-acfbbceea90d

</details>

<details>
<summary>MacOS: Desktop</summary>

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01c55ad3e6cb6401c8</li>
        <li>Upwork Job ID: 1715100322264395776</li>
        <li>Last Price Increase: 2023-10-19</li>
<li>Automatic offers: </li>
<ul>
<li>Pujan92 | Contributor | 27357327</li>
<li>dhanashree-sawant | Reporter | 27357331</li>
</ul></li>
    </ul>
</details>

**Comment by Pujan92** [comment] 2023-10-20 11:53
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
First time opening a debit card page navigates back

### What is the root cause of that problem?
It is not reproducible in prod and might be a deploy blocker.
Seems a regression from https://github.com/Expensify/App/pull/29074 where value for the `setupComplete` sets to true [here](https://github.com/Expensify/App/pull/29074/files#diff-66205963d265b61fdac2f5e06b5293a7b867ed4dc352390f9c4722c426a4dc9cR217) in `clearDebitCardFormErrorAndSubmit`.
Bcoz of that change this `!props.formData.setupComplete` will be false and will not return from the below part.
https://github.com/Expensify/App/blob/69cf29e32950f915ea888fe294dfdea6a9fabbb5/src/pages/settings/Wallet/AddDebitCardPage.js#L52-L55

### What changes do you think we should make in order to solve the problem?
We need to make the value for the `setupComplete` to false in `clearDebitCardFormErrorAndSubmit` as that is the default value for it.
https://github.com/Expensify/App/blob/69cf29e32950f915ea888fe294dfdea6a9fabbb5/src/libs/actions/PaymentMethods.ts#L213-L217

Additionally, we can move this cleanup function to correct useEffect block as that will be called on unmount. Currently, it is called each time the dependency updates.
https://github.com/Expensify/App/blob/69cf29e32950f915ea888fe294dfdea6a9fabbb5/src/pages/settings/Wallet/AddDebitCardPage.js#L59-L62
https://github.com/Expensify/App/blob/69cf29e32950f915ea888fe294dfdea6a9fabbb5/src/pages/settings/Wallet/AddDebitCardPage.js#L48-L50

**Comment by kbecciv** [comment] 2023-10-20 14:56
Added Deploy Blocker label, because issue is not reproducible in production

https://github.com/Expensify/App/assets/93399543/7e48d3f5-446b-4eb3-9fbc-fa18c9649c26

**Comment by bondydaa** [comment] 2023-10-20 15:59
posted on https://github.com/Expensify/App/pull/29074 to get help confirming if that is the cause or not. 

looking at it more and doing the steps I think we can remove the deploy blocker here, I agree it's not great UX but also don't think it's that drastic of a problem and doesn't prevent someone from just clicking the debit card again to edit.

Going to remove blocker and put it through BZ process.

**Comment by joekaufmanexpensify** [comment] 2023-10-20 16:03
I can reproduce this, but only the first time I try after signing in. On the second (any subsequent attempts), it works fine. I am not convinced that we need to do anything here, as you have to be lightning quick to click the back button before we redirect to the Plaid iFrame. It took me a couple of tries to even time it correctly. 

So not sure how realistic it is that actual customers will ever do this. But not opposed to fixing it either.

**Comment by Pujan92** [comment] 2023-10-20 16:23
Yes, this persists the first time only after setting the incorrect value I believe in onyx. For each subsequent attempts `prevFormDataSetupComplete` should be true so it won't navigate back.

https://github.com/Expensify/App/blob/18abfde5c9505608c6d3e93bbea2c974f9382ef0/src/pages/settings/Wallet/AddDebitCardPage.js#L53-L55

**Comment by joekaufmanexpensify** [comment] 2023-10-23 13:53
Agreed!

**Comment by joekaufmanexpensify** [comment] 2023-11-06 16:15
@parasharrajat  could you take care of BZ checklist this week so we can prep to issue payments? TY!

**Comment by joekaufmanexpensify** [comment] 2023-11-08 22:47
I am not really convinced we need a regression test for this. When I was triaging this originally, it was actually challenging to do this unless you really knew what to look for. So I don't think this is really worth testing every time. Especially given this was only reproducible the first time after signing in.

**Comment by joekaufmanexpensify** [comment] 2023-11-08 22:50
All set to issue payment, as follows: 

- @Pujan92 - $500 for PR. Paid via Upwork. 
- @parasharrajat - $500 for C+. Paid via NewDot. 
- @dhanashree-sawant - $50 for reporting. Paid via Upwork.

**Comment by joekaufmanexpensify** [comment] 2023-11-08 22:51
@parasharrajat could you please request $500 via NewDot and comment here once complete?

**Comment by joekaufmanexpensify** [comment] 2023-11-09 14:53
@dhanashree-sawant $50 sent and contract ended!

**Comment by joekaufmanexpensify** [comment] 2023-11-09 14:54
Closing as this is all set. All that's left is to pay out @parasharrajat's $500 request. Payment summary message is [here](https://github.com/Expensify/App/issues/30024#issuecomment-1802822832).

**Closed by joekaufmanexpensify** 2023-11-09 14:54 UTC
Labels: External, Daily, Awaiting Payment, Bug

**Comment by JmillsExpensify** [comment] 2023-12-11 01:25
$500 payment approved for @parasharrajat based on [this comment](https://github.com/Expensify/App/issues/30024#issuecomment-1802822832).
