### ISSUE TITLE
[$500] Public room - Messages does not receive in real time on Public room

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#38582] opened 2024-03-19 13:20 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.54-0
**Reproducible in staging?:** y
**Reproducible in production?:** y
**Issue reported by:** Applause - Internal Team

## Action Performed:
1. As User A on web go to public room (https://staging.new.expensify.com/r/5408450846930023)
2. As User B on mweb go to public room (https://staging.new.expensify.com/r/5408450846930023)
3. As User A send a message in public room
4. Notice the conversation history on public room

## Expected Result:
Messages should be displayed in conversation history in real time

## Actual Result:
User must refresh the page to read the new messages

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [x] Android: mWeb Chrome
- [x] iOS: Native
- [ ] iOS: mWeb Safari
- [ ] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

https://github.com/Expensify/App/assets/93399543/bb1a71e6-ca1b-4a46-94e1-677a6d2d6aa0

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01e3f5a64790d1897b</li>
        <li>Upwork Job ID: 1770639394966056960</li>
        <li>Last Price Increase: 2024-03-21</li>
    </ul>
</details>

**Comment by kbecciv** [comment] 2024-03-19 13:21
@stephanieelliott I haven't added the External label as I wasn't 100% sure about this issue. Please take a look and add the label if you agree it's a bug and can be handled by external contributors.

**Comment by stephanieelliott** [comment] 2024-03-21 02:32
Adding the `External` label to get a C+ to review -- @mollfpr this seems like an issue that would need to be fixed on the back end, can you check me on that?

**Comment by mollfpr** [comment] 2024-03-21 06:06
@stephanieelliott Sure!

**Comment by stephanieelliott** [comment] 2024-03-26 01:44
Hey @mollfpr what do you think - does this seem like it needs a BE fix?

**Comment by mollfpr** [comment] 2024-03-27 04:22
@stephanieelliott I'm unable to reproduce it on `v1.4.56-8`. If this issue is reproduced I also don't think this issue is specific to the public room and mweb, this should happen on regular chat reports. There's nothing we can do on the FE to fix it, this might be an issue with the pusher notification.

We can close it after we confirm that the issue not reproduceable anymore.

**Comment by stephanieelliott** [comment] 2024-03-28 22:13
Thanks @mollfpr! I actually can't repro it either. I am going to close

**Closed by stephanieelliott** 2024-03-28 22:13 UTC
Labels: External, Daily, Bug
