### ISSUE TITLE
[Awaiting Payment 26th Sept] [$250] Selecting a filter and using keyboard return on the filter confirmation screen ends up clearing filters.

### ISSUE THREAD

**Issue by m-natarajan** [Expensify/App#48108] opened 2024-08-27 17:55 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 9.0.25-7
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** @JmillsExpensify 
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1724762642354929

## Action Performed:
1. Go to Search
2. Click on Filters
3. Click on a specific filter
4. Enter your query, use return on your keyboard to confirm
5. You’re taken back to the main filters page, click on another filter
6. Enter your query, use return on your keyboard to confirm
7. Now enter the return key again on the filter summary/confirmation screen
## Expected Result:
No filters are cleared
## Actual Result:
All filters are cleared, nothing happens.

## Workaround:
Unknown
## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

![CleanShot 2024-08-27 at 14 43 10](https://github.com/user-attachments/assets/11469322-eaba-41df-916a-68f64aa01e01)

https://github.com/user-attachments/assets/7bcdbb9f-ce81-452c-bea1-fcdf34cb8fa5

Add any screenshot/video evidence

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01e1f39a3a6d7c0f4a</li>
        <li>Upwork Job ID: 1828501186366247316</li>
        <li>Last Price Increase: 2024-09-03</li>
<li>Automatic offers: </li>
<ul>
<li>alitoshmatov | Reviewer | 103916367</li>
<li>suneox | Contributor | 103916369</li>
</ul></li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @trjExpensify</details>

**Comment by luacmartins** [comment] 2024-08-27 18:34
This is related to focus trap. It seems like the top back button is selected when `Enter` is pressed, which navigates the user back. This also seems to happen in other flows, e.g. Submit expense

**Comment by alitoshmatov** [comment] 2024-09-03 16:46
@abzokhattab Thank you for your proposal, your RCA is correct and solution does solve the issue

**Comment by alitoshmatov** [comment] 2024-09-03 16:54
@Krishna2323 Thank you for your proposal, I think you solution is great since it addresses all the instances of this issue

**Comment by alitoshmatov** [comment] 2024-09-03 16:54
@tsa321 Thank you for your proposal, I think we should not change current logic of focus trap

**Comment by suneox** [comment] 2024-09-03 18:18
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
Avoid initial focus trap element while container includes button has an enter event listener

### What is the root cause of that problem?
We only have condition [isFocusedElementInsideContainer](https://github.com/Expensify/App/blob/7426771daf77f3dc9cd9b51e75dec4b4af3f6f26/src/components/FocusTrap/FocusTrapForScreen/index.web.tsx#L54) to prevent set initial focus but at AdvancedSearchFilters screen we don't have any focused element so the initial focus will be set to the first focusable element in the screen container.

### What changes do you think we should make in order to solve the problem?
To prevent this issue from occurring in other places, we should add a new condition that prevents setting the initial focus when the container includes a button with an [enter](https://github.com/Expensify/App/blob/7426771daf77f3dc9cd9b51e75dec4b4af3f6f26/src/components/FormAlertWithSubmitButton.tsx#L123) event listener.

```diff
      const isFocusedElementInsideContainer = !!focusTrapContainers?.some((container) => container.contains(document.activeElement));
+     const isButtonHasEnterListener = !!focusTrapContainers?.some((container) => !!container.querySelector('button[data-listener="ENTER"]'));
+     if (isFocusedElementInsideContainer || isButtonHasEnterListener) {
-     if (isFocusedElementInsideContainer) {
          return false;
      }
```

Update [Button](https://github.com/Expensify/App/blob/7426771daf77f3dc9cd9b51e75dec4b4af3f6f26/src/components/Button/index.tsx#L325) component to add a new attribute `data-listener` 

```diff
    <PressableWithFeedback
+       dataSet={{
+           listener: !!pressOnEnter ? 'ENTER' : undefined,
+       }}
        ref={ref}
        onPress={(event) => {
```
### What alternative solutions did you explore? (Optional)

**Comment by alitoshmatov** [comment] 2024-09-04 18:11
I think we should go with @abzokhattab 's [proposal](https://github.com/Expensify/App/issues/48108#issuecomment-2313257228) and solve it for current issue.

C+ reviewed 🎀 👀 🎀

**Comment by suneox** [comment] 2024-09-04 18:50
I think we should find an overall solution to prevent [initialFocus](https://github.com/Expensify/App/blob/7426771daf77f3dc9cd9b51e75dec4b4af3f6f26/src/components/FocusTrap/FocusTrapForScreen/index.web.tsx#L54)  early when the screen has a [focused element](https://github.com/Expensify/App/blob/7426771daf77f3dc9cd9b51e75dec4b4af3f6f26/src/components/FocusTrap/FocusTrapForScreen/index.web.tsx#L54) or a button listening for the enter event, instead of relying on trigger `initialFocus`  and then using `blurActiveElement` (note: initialFocus doesn’t disable the focus trap functionality).

**Comment by luacmartins** [comment] 2024-09-05 15:10
I agree that we should look at a holistic solution for other pages as well, so we don't end up with 42 different ways to solve the same problem. Let's fix the root cause.

**Comment by trjExpensify** [comment] 2024-09-09 18:29
>I agree that we should look at a holistic solution for other pages as well, so we don't end up with 42 different ways to solve the same problem. Let's fix the root cause.

💯 agree, anyone got thoughts on a proposal for that?

**Comment by suneox** [comment] 2024-09-10 14:22
@alitoshmatov How about my [proposal](https://github.com/Expensify/App/issues/48108#issuecomment-2327146125)? It can prevent the [initial focus](https://github.com/Expensify/App/blob/7426771daf77f3dc9cd9b51e75dec4b4af3f6f26/src/components/FocusTrap/FocusTrapForScreen/index.web.tsx#L49) early, rather than deactivating the focused element.

**Comment by alitoshmatov** [comment] 2024-09-11 15:13
I think @suneox 's [proposal](https://github.com/Expensify/App/issues/48108#issuecomment-2327146125) makes sense now. It goes to source of the problem, and will make sure focus is not reset into first focusable element when there is a button with `pressOnEnter` attribute.

@luacmartins What do you think?

**Comment by trjExpensify** [comment] 2024-09-23 17:17
PR on prod, updated the title to reflect the payment hold.

**Comment by trjExpensify** [comment] 2024-09-25 01:10
Go away, melvin.

**Comment by trjExpensify** [comment] 2024-09-26 22:58
Payment summary as follows:

- $250 to @suneox for the fix
- $250 to @alitoshmatov for the C+ review

Paid, closing!

**Closed by trjExpensify** 2024-09-26 22:58 UTC
Labels: External, Weekly, Overdue, Awaiting Payment, Bug
