### ISSUE TITLE
Android- expense - In camera screen receipt header is missing

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#49881] opened 2024-09-28 14:23 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 9.0.41-1
**Reproducible in staging?:** Y
**Reproducible in production?:** N
**If this was caught during regression testing, add the test name, ID and link from TestRail:** N/A
**Issue reported by:** Applause - Internal Team

## Action Performed:
1. Launch app
2. Tap on a workspace chat
3. Create a expense
4. Open the expense and tap plus receipt placeholder and try to upload a image using camera

## Expected Result:
In camera screen receipt header must not be missing

## Actual Result:
In camera screen receipt header is missing
Reproduction on: Redmi note 10s android  13

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [ ] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details> 

https://github.com/user-attachments/assets/15f63d78-51c8-45fb-9492-c1c0e9037c22

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by lanitochka17** [comment] 2024-09-28 14:24
Production:

![IMG_6322](https://github.com/user-attachments/assets/09ac7db7-f6a9-40f5-9de8-dac89fb2fa96)

**Comment by huult** [comment] 2024-09-29 07:53
## Proposal

### Please re-state the problem that we are trying to solve in this issue.

Android- expense - In camera screen receipt header is missing

### What is the root cause of that problem?

The `backTo` is `undefined`, which prevents the wrapper from showing and causes this issue.

https://github.com/Expensify/App/blob/3047c1baa21f47825f5c1ffd652184341dd22256/src/pages/iou/request/step/IOURequestStepScan/index.native.tsx#L479

`backTo` is `undefined` because `Navigation.getReportRHPActiveRoute()` returns `undefined` when clicked from the money request view.
https://github.com/Expensify/App/blob/3047c1baa21f47825f5c1ffd652184341dd22256/src/components/ReportActionItem/MoneyRequestView.tsx#L538

### What changes do you think we should make in order to solve the problem?
we should `getActiveRouteWithoutParams` instead use `getReportRHPActiveRoute`. some thing like that:
```diff
{shouldShowReceiptEmptyState && (
                    <ReceiptEmptyState
                        hasError={hasErrors}
                        disabled={!canEditReceipt}
                        onPress={() =>
                            Navigation.navigate(
                                ROUTES.MONEY_REQUEST_STEP_SCAN.getRoute(
                                    CONST.IOU.ACTION.EDIT,
                                    iouType,
                                    transaction?.transactionID ?? '-1',
                                    report?.reportID ?? '-1',
-                                    Navigation.getReportRHPActiveRoute(),
+                                    Navigation.getReportRHPActiveRoute() || Navigation.getActiveRouteWithoutParams(),
                                ),
                            )
                        }
                    />
                )}```

<summary>
<details>POC

https://github.com/user-attachments/assets/7982ca0b-18b3-4c66-87eb-14eb4e83d009

</details>
</summary>

**Comment by huult** [comment] 2024-09-30 02:43
## [Proposal Update](https://github.com/Expensify/App/issues/49881#issuecomment-2381248111)

- Updated the path in the code example.

**Comment by NikkiWines** [comment] 2024-09-30 14:31
Looks like this is already being resolved [here](https://github.com/Expensify/App/pull/49916) - asked for a status update there.

**Comment by luacmartins** [comment] 2024-09-30 15:41
Thank you @rayane-djouah!

**Comment by luacmartins** [comment] 2024-09-30 15:42
PR merged and being CPed

**Comment by luacmartins** [comment] 2024-09-30 18:33
Confirmed fix on staging.

**Closed by luacmartins** 2024-09-30 18:33 UTC
Labels: Reviewing, Engineering, Weekly
