### ISSUE TITLE
[HOLD for payment 2024-04-25] [Regression] Task - Duplicate task displayed after assigning task to another user & skeleton loading

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#39260] opened 2024-03-29 16:35 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.58-0
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**N/A
**Issue reported by:** Applause - Internal Team

## Action Performed:
1. Go to https://staging.new.expensify.com/
and log in
2. Open any chat
3. Create a task
4. Open the task details and assign the task to the user you share the task with
5. Navigate to the chat and open the task again

## Expected Result:
Only the system message that the task was assigned to a user is displayed

## Actual Result:
The duplicate task is displayed below the system message, after opening the task again the skeleton loading is displayed

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [ ] Android: mWeb Chrome
- [x] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details> 

https://github.com/Expensify/App/assets/78819774/926169bc-c7bc-400b-bc9f-3c824c40b7e2

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by lanitochka17** [comment] 2024-03-29 16:35
@stephanieelliott  FYI I haven't added the External label as I wasn't 100% sure about this issue. Please take a look and add the label if you agree it's a bug and can be handled by external contributors

**Comment by lanitochka17** [comment] 2024-03-29 16:36
We think that this bug might be related to #vip-vsp

**Comment by stephanieelliott** [comment] 2024-04-08 22:18
PR is under active review

**Comment by stephanieelliott** [comment] 2024-04-15 21:54
[New PR](https://github.com/Expensify/App/pull/39328) is on staging! I will update with payment dates once this hits prod

**Comment by twisterdotcom** [comment] 2024-04-23 08:55
@stephanieelliott how can I help here?

**Comment by stephanieelliott** [comment] 2024-04-23 14:49
Oh sorry @twisterdotcom it looks like my little note didn't make it on here: 

> Reapplying the Bug label to get another BZ member on this while I am OOO til May 2. Thanks @twisterdotcom! 

Heads up this is a regression from https://github.com/Expensify/App/pull/39215, so no payment is actually due for this one. So the only thing left to do here is create an issue for the regression test (assuming @nexarvo determines we should create one) and then close this issue!

**Closed** 2024-04-24 12:27 UTC
Labels: Daily, Awaiting Payment, Bug
