### ISSUE TITLE
[HOLD for payment 2023-08-10] App crashes when clicking 'Split bill' button for newly created account

### ISSUE THREAD

**Issue by kavimuru** [Expensify/App#23951] opened 2023-07-31 19:35 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Sign-up with a new account
2. Click on 'FAB' menu
3. Click on 'Split bill' button
## Expected Result: 
App shouldn't crash
## Actual Result: 
App crashes

## Workaround:
Can the user still use Expensify without this being fixed? Have you informed them of the workaround?

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [x] Android / Chrome
- [ ] iOS / native
- [x] iOS / Safari
- [x] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 1.3.48-0
**Reproducible in staging?:** y
**Reproducible in production?:** n
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/43996225/5237c6d0-ffc0-42d0-a7ab-f68f6dea40bb

https://github.com/Expensify/App/assets/43996225/19296699-e8cc-4660-b1aa-767d49677ab0

**Expensify/Expensify Issue URL:**
**Issue reported by:** @natnael-guchima
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1690828817211769

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01c58572b05d76428f</li>
        <li>Upwork Job ID: 1689034160602599424</li>
        <li>Last Price Increase: 2023-08-08</li>
    </ul>
</details>

**Comment by Li357** [comment] 2023-07-31 19:43
Is this a dupe of https://github.com/Expensify/App/issues/23568?

**Comment by Li357** [comment] 2023-07-31 19:46
Hmm, seems not because this crash occurs right when the Split Bill button is clicked. Investigating

**Comment by aldo-expensify** [comment] 2023-07-31 19:51
In case it helps... this may have the same root cause as: https://expensify.slack.com/archives/C049HHMV9SM/p1690832195690459

**Comment by situchan** [comment] 2023-07-31 20:06
Not reproducible on main. Only staging.

**Comment by ahmedGaber93** [comment] 2023-07-31 20:12
I think it dup of https://github.com/Expensify/App/issues/23420

**Comment by situchan** [comment] 2023-07-31 20:18
Seems like dupe. Then not sure why this is deploy blocker as https://github.com/Expensify/App/pull/17964 which caused this regression was deployed to production long time ago.

**Comment by getusha** [comment] 2023-07-31 20:32
@situchan it's reproducible on staging only. and i don't think the linked PR is the cause no?

**Comment by Li357** [comment] 2023-07-31 20:48
Agree, it seems to be the same root cause as https://github.com/Expensify/App/issues/23420 since `currency` is undefined (because default props are not applied) when loading.

**Comment by Li357** [comment] 2023-07-31 20:58
Closing because fix PR is already ready.

**Comment by Natnael-Guchima** [comment] 2023-07-31 21:05
Shouldn't this bug be reproducible on production too if it has the same root cause with this pr https://github.com/Expensify/App/issues/23420

**Comment by Li357** [comment] 2023-07-31 21:13
True, I suspect there was some backend change that was merged recently that caused this intermediate case where `currency` had no default. I'm going to search for it.

**Comment by hannojg** [comment] 2023-08-01 09:25
Hey, thesis very likely a regression introduced by my PR! I am looking into it:

- https://github.com/Expensify/App/pull/23749

**Comment by hannojg** [comment] 2023-08-01 09:26
After looking into this, it seems it's a combo of changes that caused this issue. This PR will fix this error as well:

- https://github.com/Expensify/App/issues/23420

**Comment by Li357** [comment] 2023-08-01 16:41
Confirmed fix on staging!

**Comment by alexpensify** [comment] 2023-08-05 00:43
@Li357 - it appears the only payment here is to @Natnael-Guchima for reporting. Please confirm, so I can prepare for the upcoming pay period. Thanks!

**Comment by Li357** [comment] 2023-08-07 21:54
@alexpensify Yep! That should be it.

**Comment by alexpensify** [comment] 2023-08-08 22:08
@Natnael-Guchima - to prepare for the upcoming pay period, I've sent a request in Upwork. Please accept and I can finalize the process on August 10. Thanks!

**Comment by Natnael-Guchima** [comment] 2023-08-08 22:10
I have accepted the offer. Thanks @alexpensify

**Comment by alexpensify** [comment] 2023-08-10 23:03
Here is the payment summary: 

-  External issue reporter - @Natnael-Guchima 
-  Contributor that fixed the issue - N/A 
-  Contributor+ that helped on the issue and/or PR - N/A

Upwork Job: https://www.upwork.com/jobs/~01c58572b05d76428f

*If applicable, the bonuses will be applied on the final payment 

Extra Notes regarding payment: The payment has been paid in Upwork and the job has been closed there too.

**Closed by alexpensify** 2023-08-10 23:03 UTC
Labels: Reviewing, Engineering, Weekly, Internal, Awaiting Payment, Bug
