### ISSUE TITLE
[HybridApp] Potential authentication issues on signin

### ISSUE THREAD

**Issue by Julesssss** [Expensify/App#49081] opened 2024-09-12 13:19 UTC
_This is an unconfirmed issue related to authentication._

### Problem

We recently dealt with authentication issues which are linked to the way we share authentication tokens between HybridApp app experiences. We believe these issues should have been resolved with recent PRs such as https://github.com/Expensify/Mobile-Expensify/pull/13061 & https://github.com/Expensify/Mobile-Expensify/pull/12993

However, [recent reports](https://expensify.slack.com/archives/C036QM0SLJK/p1726087029116039?thread_ts=1726076979.058339&cid=C036QM0SLJK) have highlighted issues where app data has failed to load for users signing in. I am not certain these issues are linked, but we should determine this before unblocking the HybridApp release

### Solution

Investigate whether reports from @puneetlath and @garrettmknight are issues related to our HybridApp authentication, or are unrelated NewDot issues.

**Comment by Julesssss** [comment] 2024-09-12 15:40
Garrett is potentially [seeing](https://expensify.slack.com/archives/C036QM0SLJK/p1726149020111899?thread_ts=1726076979.058339&cid=C036QM0SLJK) the same issue in HybridApp `9.0.33.1`

**Comment by AndrewGable** [comment] 2024-09-12 19:49
Added debugging to CI/CD to see what the `.env` is so I can match that on my local machine to see what is happening

**Comment by AndrewGable** [comment] 2024-09-17 20:17
We dug deep into the `.env` file, but it turned out to be working as intended.

**Comment by AndrewGable** [comment] 2024-09-17 20:18
Asking to see if a fresh install fixes the issue.

**Comment by Julesssss** [comment] 2024-09-20 09:17
Our internal reports have been positive and I believe the upgrade path has also been verified. 

Can we close? @trjExpensify @AndrewGable

**Comment by trjExpensify** [comment] 2024-09-20 10:05
I think so, closing!

**Closed by trjExpensify** 2024-09-20 10:05 UTC
Labels: Engineering, Daily, Overdue, Bug
