### ISSUE TITLE
Profile - Different avatar is displayed before default avatar is displayed when removing profile picture

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#35570] opened 2024-02-01 16:33 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.35-0
**Reproducible in staging?:** Y
**Reproducible in production?:** N 
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):** natnael.expensify+3@gmail.com
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** Applause - Internal Team
**Slack conversation:**

## Action Performed:
Precondition: Account shouldn't have a profile picture when starting testing
1. Add a profile picture
2. Remove the profile picture

## Expected Result:
Default avatar should be displayed when removing profile picture

## Actual Result:
Different profile picture is displayed first then default avatar on removing profile picture

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [x] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details> 

https://github.com/Expensify/App/assets/78819774/e28ac05b-8224-40b4-96d2-dd432b372fe5

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by sobitneupane** [comment] 2024-02-01 17:11
Can you retry with a different email? I can reproduce the issue.

https://github.com/Expensify/App/assets/25876548/7b37009d-4533-4cab-88d3-4cfdb6b8965f

**Comment by sobitneupane** [comment] 2024-02-01 18:06
I am pretty sure, this issue has the same root cause as [this one](https://github.com/Expensify/App/issues/35560). Discussion on: https://github.com/Expensify/App/issues/35560

**Comment by roryabraham** [comment] 2024-02-01 19:29
Not going to treat this as a deploy blocker.

**Comment by trjExpensify** [comment] 2024-02-01 19:52
Are we consolidating this one with #35560?

**Comment by trjExpensify** [comment] 2024-02-05 13:16
Bump on the Q! @tienifr maybe you have an opinion on that?

**Comment by trjExpensify** [comment] 2024-02-05 16:13
Cool, sounds good. Going to close this out then!

**Closed by trjExpensify** 2024-02-05 16:13 UTC
Labels: Engineering, Daily, Bug
