### ISSUE TITLE
[HOLD for payment 2024-04-05] [$500] Android - Chat - Chat flickers if a PDF was previously sent or when a new one is sent

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#34520] opened 2024-01-15 17:22 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.25-1
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** Applause - Internal Team
**Slack conversation:**

## Action Performed:
1. Open the app
2. Navigate to any chat
3. Tap on ''+'' button
4. Select "Add attachment''
5. Upload a PDF file
6. Check the chat view

## Expected Result:
Chat view should not flicker when there are previously sent PDF files or when a PDF file is sent in the chat

## Actual Result:
Chat view flickers when there are previously sent PDF file, or when user send a PDF file

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [ ] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details> 

https://github.com/Expensify/App/assets/78819774/5b254928-088a-4613-8d32-2ccca2baa4a7

[Slack___TEST_ing__3-2023-12-28_22_42_24.367-2024-01-15 16_09_19.026.pdf](https://github.com/Expensify/App/files/13941490/Slack___TEST_ing__3-2023-12-28_22_42_24.367-2024-01-15.16_09_19.026.pdf)

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~0184552ac59563af4b</li>
        <li>Upwork Job ID: 1746946018928300032</li>
        <li>Last Price Increase: 2024-03-19</li>
<li>Automatic offers: </li>
<ul>
<li>jsdev2547 | Contributor | 0</li>
</ul></li>
    </ul>
</details>

**Comment by Ykumar1415** [comment] 2024-01-15 17:44
I Tried to produce the issue and followed below actions : 
Open the app
Navigate to any chat
Tap on ''+'' button
Select "Add attachment''
Upload a PDF file
Check the chat view

got same response.

**Comment by trjExpensify** [comment] 2024-01-16 10:34
@sobitneupane do you have a native Android device by any chance?

**Comment by sobitneupane** [comment] 2024-01-18 00:35
Nope. I don't have Android device with me.

**Comment by sourcecodedeveloper** [comment] 2024-01-21 23:19
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
Chat flickers if PDF was previously sent or when new one is uploaded.

### What is the root cause of that problem?
The root cause of the issue is the image size is defaulting to width 200 and height 200 after upload and then GetSize() is called after upload which then calculates correct width and height and the image size is adjusted which causes the flicker. 

### What changes do you think we should make in order to solve the problem?
After the file is uploaded, the correct image width and height should be calculated rather than showing placeholder image of width and height 200. After the correct size is obtained from GetSize(), the correct attachment preview size can be displayed to avoid the flicker from placeholder image width/height of 200 to correct width/height. Then after obtaining the correct values store the image width/height in Onyx storage, so after the use changes chat reports, the image sizes are already available for the image to be displayed rather than showing defaults.

In ReportActionItemFragment, use UseEffect to intercept loading of attachment. After the attachment is uploaded, the fragment contains the imgUrl. The useState setIsAttachment loading is for displaying activity indicator while the attachment is uploading and correct size obtained.

https://github.com/Expensify/App/blob/c14ca54536a50ecf251bd3ef7ebb4561f8e0e716/src/pages/home/report/ReportActionItemFragment.js#L96

```
    useEffect(()=>{
        if (ReportUtils.isReportMessageAttachment(fragment)) {
            if (fragment.html === CONST.ATTACHMENT_UPLOADING_MESSAGE_HTML) {
                return;
            }
            const attachmentDetails = getAttachmentDetails(fragment.html);
            const previewSource = tryResolveUrlFromApiRoot(attachmentDetails.previewSourceURL);
            const authToken = lodashGet(props.session, 'encryptedAuthToken', null);
            const imgUrl = { uri: `${previewSource}?encryptedAuthToken=${encodeURIComponent(authToken)}` };
            const img = _.find(props.imageCache, (img) => img.imgUrl == previewSource);
            if (img) {
                setisAttachedmentLoading(false);
                return;
            }
// obtain image size and store in onyx storage.
            RNImage.getSize(imgUrl.uri, (width, height) => {
                setImageCache(previewSource, width, height);
                setisAttachedmentLoading(false);
            });

        }
    },[fragment])
```
### What alternative solutions did you explore? (Optional)

**Comment by trjExpensify** [comment] 2024-01-22 12:25
Awaiting proposal review, Melvin!

**Comment by sobitneupane** [comment] 2024-01-24 02:45
@trjExpensify I will be able review the issue only in the weekend. Please feel free to re-assign the issue if it's high-priority or urgent.

**Comment by trjExpensify** [comment] 2024-01-25 20:54
This weekend is cool!

**Comment by trjExpensify** [comment] 2024-01-29 20:12
👋 How'd you get on @sobitneupane over the weekend?

**Comment by sobitneupane** [comment] 2024-01-30 14:09
Oops I could not get to it before weekend. I will review it by EOD tomorrow NPT.

**Comment by trjExpensify** [comment] 2024-01-30 15:10
Thanks!

**Comment by sobitneupane** [comment] 2024-02-01 13:10
@sourcecodedeveloper 

I believe the flicker that we are talking about is constant flickering of the pdf thumbnail. Not the change from placeholder thumbnail.

https://github.com/Expensify/App/assets/25876548/e03a12de-8624-4a85-b07b-42d07063a925



> The root cause of the issue is the image size is defaulting to width 200 and height 200 after upload and then GetSize() is called after upload which then calculates correct width and height and the image size is adjusted which causes the flicker.

**Comment by sobitneupane** [comment] 2024-02-01 13:11
I cannot reproduce the issue 


https://github.com/Expensify/App/assets/25876548/7cab69e3-bfde-4c28-a0aa-ada59c0ccbd0

**Comment by trjExpensify** [comment] 2024-02-01 19:56
Okay, I'm happy to close this out then! I'm sure if it comes back someone will flag it. :)

**Comment by kbecciv** [comment] 2024-02-07 23:03
Issue is reproduced on build 1.4.38.0

https://github.com/Expensify/App/assets/93399543/5f39df6e-b757-426f-975b-6b13765531ed

**Comment by sourcecodedeveloper** [comment] 2024-02-13 22:27
@sobitneupane I was able to reproduce the issue.

[android.bug.webm](https://github.com/Expensify/App/assets/141340971/e98a4048-86f0-4ebc-b999-8a899102bd5b)

Also, fortunately the original proposal I had proposed does resolve the flickering issue.

[android.poc.webm](https://github.com/Expensify/App/assets/141340971/a911988f-b177-45ed-88f1-e50e624c8929)

**Comment by trjExpensify** [comment] 2024-02-14 01:52
Cool, @sobitneupane if you could give this a review please. Thanks! 

(Internal: Adding this to #vip-vsb as a LOW chat attachment bug to fix)

**Comment by sobitneupane** [comment] 2024-02-15 14:56
@kbecciv In which android version was the issue reproduced?

**Comment by sobitneupane** [comment] 2024-02-15 15:11
@sourcecodedeveloper I am trying to reproduce the issue on my end. I could not reproduce the issue on Android Version 8 (real device). Did you reproduce it in simulator or real device? Is the issue reproducible only on uploading an attachment or is it reproducible even with existing attachments?

> I would store the attachment width and height in Onyx,

So, we need to store attachment width and height for all the attachments, right? It doesn't feel like an optimal solution. May be if we can pin point the exact root cause, we can get better solution. But I am not sure if it is worth it as market share of Android 7.0 or less is less than 5%.

**Comment by sourcecodedeveloper** [comment] 2024-02-15 17:39
@sobitneupane I used the android simulator Android 7.0 API 24. The issue is also reproducible on Android 8.0 API 26. The issue happens right away as soon as the chat report is opened with existing attachments, no need to upload any attachments.
Storing width and height in Onyx is option 1, option 2 would be to replace the ImageWithSizeCalculation component with the Image component. Option 2 would be simpler and easier. I have tested option 2 on Android 8 and the issue does get resolved also included in proposal as alternate option.

**Comment by trjExpensify** [comment] 2024-02-19 12:12
- The latest version of Android is 13.0
- This bug is apparently **only** reproducible on versions 10.0 and below?
- @kbecciv did you get confirmation what [version](https://github.com/Expensify/App/issues/34520#issuecomment-1946263383) this was tested and reported on?

**Comment by kbecciv** [comment] 2024-02-19 14:14
@trjExpensify @sobitneupane Issue reproduced on Samsung Galaxy S9+, Android 10

**Comment by trjExpensify** [comment] 2024-02-19 14:17
Cool, so has anyone been able to reproduce this on Android 11, Android 12, Android 13 or Android 14? The latest 4 versions account for [75% of the market share](https://github.com/Expensify/App/issues/34520#issuecomment-1952539594).

**Comment by sourcecodedeveloper** [comment] 2024-02-19 16:28
@trjExpensify I tested and the issue is reproducible on Pixel 2 Android 11, 12, 13 and 14. Pixel 3 Android 14 did not have the issue. So the issue seems to vary across device models.
@sobitneupane Try using the emulator for testing purposes and use Pixel 2. For alternate solution, no need to store attachment width and height for attachments. The ImageWithSizeCalculation is not needed and the Image component can be used instead. The ImageWithSizeCalculation component is only used in the thumbnail component so can be replaced safely. I have tested and replacing ImageWithSizeCalculation with Image resolves the flickering.

**Comment by kbecciv** [comment] 2024-02-19 20:00
Tester is still able to reproduce the issue.

https://github.com/Expensify/App/assets/93399543/73cbf7df-fa16-4799-a4ee-b8240f1cb7d2

**Comment by sobitneupane** [comment] 2024-02-20 08:27
@sourcecodedeveloper 
>The ImageWithSizeCalculation is not needed and the Image component can be used instead. The ImageWithSizeCalculation component is only used in the thumbnail component so can be replaced safely. I have tested and replacing ImageWithSizeCalculation with Image resolves the flickering.

`ImageWithSizeCalculation` is a very old component introduced by https://github.com/Expensify/App/pull/685 PR. Can you please explain what purpose  `ImageWithSizeCalculation` is serving and what drawbacks will we have by replacing it with `Image`? Will it have any effect in UI and performance?

**Comment by sourcecodedeveloper** [comment] 2024-02-20 19:53
@sobitneupane I went through some previous commits for ImageWithSizeCalculation, the component has been slowly phased out. Previously ImageWithSizeCalculation was used by ImageView both index.js and index.native.js but was removed with the Image component, so no drawbacks replacing the component with Image and also no side effects in the UI and performance.
https://github.com/Expensify/App/commit/ee56271061393a8e8b171c86a2337a8d4d272964
The ImageView index.js is still using Image but the index.native.js is using LightBox. The ThumbnailImage does not have separate index files for web and native and is basically tied to the ImageWithSizeCalculation.

**Comment by sobitneupane** [comment] 2024-02-21 15:07
I could finally reproduce the issue using the pdf attached in the issue. Looks like it is only reproducible with pdf having large widths.

Only change that is required is to solve the issue is 

```diff
- resizeMode={RESIZE_MODES.cover}
+ resizeMode={RESIZE_MODES.contain}
```
https://github.com/Expensify/App/blob/20ca041595e76cdd289977e55b2af3fbb9618868/src/components/ImageWithSizeCalculation.tsx#L83

But the change was made by https://github.com/Expensify/App/pull/18485/ PR to solve https://github.com/Expensify/App/issues/18040 issue.

@sourcecodedeveloper Would you like to investigate further?

**Comment by sourcecodedeveloper** [comment] 2024-02-21 15:11
@sobitneupane I can do test build and get back.

**Comment by sourcecodedeveloper** [comment] 2024-02-25 19:46
@sobitneupane The problem with using RESIZE_MODES.contain is the thumbnail(long images) do not fill the container rather the thumbnail is contained and empty area is visible on the top and bottom. So need to use RESIZE_MODES.cover and also resolve the flickering.

The ThumbnailImage component uses the useThumbnailDimensions hook, which is using aspectRatio prop of Layout.
https://github.com/Expensify/App/blob/8bdb753045cf0eee6cf1d342adf8b76040cabac4/src/hooks/useThumbnailDimensions.ts#L22

According to documentation,
https://reactnative.dev/docs/layout-props#aspectratio

Consider the following points,
1. On a node with a set width/height, aspect ratio controls the size of the unset dimension.
2. On a node with a measure function, aspect ratio works as though the measure function measures the flex basis.

Considering point 1 and the useThumbnailDimensions, the hook only sets one of the props width or height and the aspectRatio controls the size of the other dimension.

https://github.com/Expensify/App/blob/8bdb753045cf0eee6cf1d342adf8b76040cabac4/src/hooks/useThumbnailDimensions.ts#L24

Going back to the ImageWithSizeCalculation component, the component declares onMeasure function
https://github.com/Expensify/App/blob/8bdb753045cf0eee6cf1d342adf8b76040cabac4/src/components/ThumbnailImage.tsx#L102

Considering point 2, if measure function is provided, the aspect ratio functions as though the measure function is measuring the flex basis, but from the definition of onMeasure function, the function is not handling flex basis but returning image dimensions.
The root cause of the flickering would be how aspectRatio behaves when used along with measure function. Only point 1 is needed. The onMeasure function may have been used to provide dimensions but react interprets the measure function for measuring flex basis and not for returning image dimensions.

The aspectRatio prop is necessary to provide when sizing thumbnails, removing aspectRatio is not suitable so rather the solution would be to remove the measure function from ImageWithSizeCalculation and calculate image size in ThumbnailImage component using GetSize() method of image.

Given the root cause, the issue becomes easier to solve, need to add useEffect in ThumbnailImage component and then call GetSize method of image.

```
useEffect(()=>{
        RNImage.getSize(source, (width, height) => {
            updateImageSize({width, height});
        });
},[source])
```

Also remove the onMeasure callback from ImageWithSizeCalculation component. I have tested on Pixel 2,3,4 and the issue is resolved.

**Comment by trjExpensify** [comment] 2024-02-27 12:26
What do you think about this, @sobitneupane?

**Comment by sobitneupane** [comment] 2024-02-28 10:18
I cannot find comments from @sourcecodedeveloper any longer.

We are waiting for proposals. [Here](https://github.com/Expensify/App/issues/34520#issuecomment-1956874620) is my finding so far.

**Comment by jsdev2547** [comment] 2024-02-28 13:02
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
Upload pdf in chat. The pdf flickers on Android (Pixel 2, 3, 4).

### What is the root cause of that problem?
The root cause of the issue is the use of aspect ratio along with the measure function measure the flex basis but the expectation is to get the image dimensions. According to layout prop documentation
https://reactnative.dev/docs/layout-props#aspectratio

1) On a node with a set width/height, aspect ratio controls the size of the unset dimension
2) On a node with a measure function, aspect ratio works as though the measure function measures the flex basis

The useThumbnailDimensions hook uses aspect ratio
https://github.com/Expensify/App/blob/bee752ac593f40d96391199f680b14466076ab9d/src/hooks/useThumbnailDimensions.ts#L22

The aspectRatio is applied on the node
https://github.com/Expensify/App/blob/bee752ac593f40d96391199f680b14466076ab9d/src/components/ThumbnailImage.tsx#L99

The ImageWithSizeCalculation component also uses onMeasure function which affects the functionality of the aspect ratio.
https://github.com/Expensify/App/blob/bee752ac593f40d96391199f680b14466076ab9d/src/components/ThumbnailImage.tsx#L102

Instead of providing the flex basis, the onMeasure function provides the image dimensions.

### What changes do you think we should make in order to solve the problem?

The aspect ratio property is necessary to resize thumbnail, so the aspectRatio needs to be kept instead the onMeasure function is affecting the functionality of the aspectRatio and can be replaced with the GetSize function of image.

In ThumbnailComponent, add useEffect and call getSize.
https://github.com/Expensify/App/blob/bee752ac593f40d96391199f680b14466076ab9d/src/components/ThumbnailImage.tsx#L45

```
    useEffect(() => {
        if (updateImageSize == null) {
            return;
        }
        const sourceURLWithAuth = addEncryptedAuthTokenToURL(previewSourceURL as string);
        RNImage.getSize(sourceURLWithAuth, (width, height) => {
            updateImageSize({width, height});
        });
    }, [updateImageSize, previewSourceURL, isOffline]);
```

Remove onMeasure function call from so the aspectRatio only controls the size of the unset dimension and not act as flex basis
https://github.com/Expensify/App/blob/bee752ac593f40d96391199f680b14466076ab9d/src/components/ThumbnailImage.tsx#L102


### What alternative solutions did you explore? (Optional)

**Comment by jsdev2547** [comment] 2024-02-28 13:12
@sobitneupane The problem with using resizeMode={RESIZE_MODES.contain} is the the thumbnails (long images) have empty space on top and the bottom. The other PR used resizeMode={RESIZE_MODES.cover} so the long images would fill the container.

I have revised the proposal to explain the layout prop and how aspect ratio functions when applied on node with onMeasure function.

**Comment by jsdev2547** [comment] 2024-03-01 07:37
@sobitneupane I am waiting for feedback regarding https://github.com/Expensify/App/issues/34520#issuecomment-1956874620
I explained why resizeMode={RESIZE_MODES.contain} cannot be used. PR 18485 added resizeMode={RESIZE_MODES.cover} so the long images would fill the container. For solution I had explained how the aspectRatio functions when applied to node using measure function.

**Comment by trjExpensify** [comment] 2024-03-04 09:50
Strange, so what happened here to all of @sourcecodedeveloper's comments? @jsdev2547 is this your new account handle or something? 

Anyhow, @sobitneupane I think this is ready for your input please!

**Comment by jsdev2547** [comment] 2024-03-06 11:55
@sobitneupane Please provide input.

**Comment by sobitneupane** [comment] 2024-03-07 08:30
Thanks for the proposal @jsdev2547. I am not totally convinced by the RCA.

My findings so far is the width and height value returned by onMeasure is fluctuating(687, 688). It is resulting the change in `imageDimensions` and `thumbnailDimensionsStyles`. So, the thumbnail image is re-rendering infinite times resulting the flicker. One possible solution would be to return width and height by ceiling or flooring the value instead of returning aspect ration. But it would require more detailed RCA.

<img width="338" alt="Screenshot 2024-03-07 at 14 03 31" src="https://github.com/Expensify/App/assets/25876548/b5b0d735-3cb5-4f9b-97db-c1feda5723c1">

**Comment by jsdev2547** [comment] 2024-03-07 09:07
@sobitneupane I can confirm the issue is reproducible for when height is greater than width, with the long images. Also need to understand how the aspectRatio functions when applied to node with measure function i.e measure the flex basis but the expectation of the measure function is to return image width and height not flex basis. Another approach I can try is use GetSize in the measure function instead of calculating size from image load and perhaps the fluctuation would get resolved.

**Comment by jsdev2547** [comment] 2024-03-11 07:05
@sobitneupane I have revised proposal. The root cause for the flicker is the android native is using expo-image component and the imagecomponent after call to onLoad is already calculating the image aspect ratio but then the call to onMeasure calls updateImageSize which calls setImageDimensions which causes re-render and the aspect ratio is re-calculated based on thumbnail dimensions. The effective approach is to use useRef instead of setState for setImageDimensions.

**Comment by trjExpensify** [comment] 2024-03-11 10:58
Let us know what you think about that RCA @sobitneupane!

**Comment by sobitneupane** [comment] 2024-03-12 16:54
Thanks for the update @jsdev2547.

But the proposed change has some glitch. The size of the thumbnail changes on opening the chat and on uploading new attachment.

https://github.com/Expensify/App/assets/25876548/5c0e8f71-4a1e-47b8-bf70-6b45528482f6

**Comment by jsdev2547** [comment] 2024-03-12 18:54
@sobitneupane The thumbnail size is initially set to 200 after the image has been loaded the correct image size is loaded which is why the thumbnail is resized. I checked and the thumbnail is also resizing on staging so the thumbnail resizing is unrelated to the proposed solution.

[poc.webm](https://github.com/Expensify/App/assets/161593779/dc699375-38e3-480c-9ad1-8dcfff55567a)

The thumbnail resizing issue is separate from the flickering but the resizing issue can also be addressed but displaying loading indicator while the image size is getting calculated and only display the image once the correct image size is available.

Please confirm if the thumbnail resizing issue should also be addressed along with flickering issue.

**Comment by sobitneupane** [comment] 2024-03-13 14:19
> The thumbnail size is initially set to 200 after the image has been loaded the correct image size is loaded which is why the thumbnail is resized. I checked and the thumbnail is also resizing on staging so the thumbnail resizing is unrelated to the proposed solution.

My bad. I was also able to reproduce the issue in staging IOS/native and Web.

**Comment by sobitneupane** [comment] 2024-03-13 14:24
> Please confirm if the thumbnail resizing issue should also be addressed along with flickering issue.

@jsdev2547 Yep. It would be great if we can also address the thumbnail resizing issue. 

> The thumbnail resizing issue is separate from the flickering but the resizing issue can also be addressed by displaying loading indicator instead of the initial placeholder image of default width and height. The Image thumbnail is displayed after the image is loaded.

I am not sure if it looks better with loading indicator or not.

**Comment by mvtglobally** [comment] 2024-03-14 15:39
Issue not reproducible during KI retests. (First week)

**Comment by jsdev2547** [comment] 2024-03-15 11:28
@sobitneupane I have attached poc using loading indicator. The flickering and the resizing issue is resolved.

[android-poc.webm](https://github.com/Expensify/App/assets/161593779/ee32a8f5-4da1-43d9-8329-94f5a68a918a)

**Comment by jsdev2547** [comment] 2024-03-15 12:01
@sobitneupane I have attached poc using loading indicator. The flickering and the resizing issue is resolved.

[android-poc.webm](https://github.com/Expensify/App/assets/161593779/5f55e8d8-4bec-419d-a5e0-b676c14c4101)

**Comment by jsdev2547** [comment] 2024-03-15 13:11
@sobitneupane I have attached poc using loading indicator. The flickering and the resizing issue is resolved.

[android-poc.webm](https://github.com/Expensify/App/assets/161593779/d89c33d8-98f5-4af5-acb8-4313cb19cdc7)

**Comment by trjExpensify** [comment] 2024-03-18 10:38
I'm not really a big fan of the loading indicators that get replaced with the thumbnail, tbh. What do you think, @sobitneupane?

**Comment by sobitneupane** [comment] 2024-03-18 10:57
I agree @trjExpensify. I also don't think we should go with loading indicator. 

@jsdev2547 As you can easily notice in the following video, your [proposed change](https://github.com/Expensify/App/issues/34520#issuecomment-1968940399) will make thumbnail with default Width more distinct. Also, on uploading a new image, it would remain in the default size until the screen is refreshed.

|Before | After |
|---|---|
<video src="https://github.com/Expensify/App/assets/25876548/da97015a-0923-4da8-8db6-08a199a30e03"> | <video src="https://github.com/Expensify/App/assets/25876548/8ca82102-4f70-461e-ad33-084ca1b49130">
|<video src="https://github.com/Expensify/App/assets/25876548/9d1acea6-84d3-499a-abc7-fd072477b60b"> | <video src="https://github.com/Expensify/App/assets/25876548/43144604-89c0-4354-a5fc-5ff74b16f6b3">
|<video src="https://github.com/Expensify/App/assets/25876548/856e6f75-063b-4a5a-93da-e27362ccde17"> | <video src="https://github.com/Expensify/App/assets/25876548/74174d2e-aae5-46aa-9ea7-5adfe03c4141">

**Comment by jsdev2547** [comment] 2024-03-18 17:22
@sobitneupane I have revised proposal and instead of adding useRef in the thumbnailImage component, I have added useRef in the android Image component BaseImage.native.tsx. Adding useRef in thumbnailImage was making the default width more distinct and the resizing issue more visible. Adding useRef in BaseImage.native component does not add on further delay to resizing issue and also does not have any impact on uploading new attachments and also resolves the flickering.

I have added video of the revised proposal and also [branch](https://github.com/jsdev2547/App/tree/imageflicker_test) for testing,

[android-poc.webm](https://github.com/Expensify/App/assets/161593779/d9a38cb1-9c3e-4584-9136-eabb3013c134)

Please test using the branch. As for the resizing issue, need to discuss if the issue is still notable and requires to be addressed after adding useRef in BaseImage.native component. Some options to address resizing issue, currently when the user uploads attachment, the chat report displays "Uploading attachment...", similarly when the image size is getting calculated, the chat report could display "Loading attachment...", or use placeholder image which is replaced by the thumbnail after the image size is calculated.

**Comment by mvtglobally** [comment] 2024-03-20 03:39
Issue not reproducible during KI retests. (Second week)

**Comment by sobitneupane** [comment] 2024-03-20 08:03
Thanks for the proposal @jsdev2547

Your [latest proposal ](https://github.com/Expensify/App/issues/34520#issuecomment-1968940399)looks good. But let's make sure it doesn't cause any regression by testing all the components using BaseImage.

🎀 👀 🎀 C+ reviewed

**Comment by sobitneupane** [comment] 2024-03-20 15:54
@srikarparsi I was able to reproduce with the steps in issue body. Is it not reproducible any longer? I might have tested in older version. I will retest in latest main and update here asap.

**Comment by sobitneupane** [comment] 2024-03-20 16:04
@srikarparsi The issue is still reproducible with the steps in issue body.

https://github.com/Expensify/App/assets/25876548/26e00ac9-5def-4b91-8859-1622e3fda25d

**Comment by srikarparsi** [comment] 2024-03-20 20:47
Ah got it thank you, I thought the focus shifted to the images resizing but see that that was a byproduct of one of the fixes. @jsdev2547's proposal looks good to me as well.

**Comment by jsdev2547** [comment] 2024-03-21 19:34
@sobitneupane Thanks for the review. I have PR(https://github.com/Expensify/App/pull/38766) ready for review.

**Comment by srikarparsi** [comment] 2024-03-28 19:28
Hi @sobitneupane and @jsdev2547, QA reported that they are still able to reproduce the [issue](https://github.com/Expensify/App/pull/38766#issuecomment-2025430282). Can you please take a look into it when you get a chance.

**Comment by jsdev2547** [comment] 2024-03-28 21:52
@sobitneupane I have tested on main and not getting any flickers.

[android.webm](https://github.com/Expensify/App/assets/161593779/54bdb953-7b1c-451f-8742-a3dac9f75bba)

**Comment by trjExpensify** [comment] 2024-04-08 14:14
👋 checklist time, @sobitneupane!

**Comment by sobitneupane** [comment] 2024-04-11 09:35
> * [ ]  [@sobitneupane] The PR that introduced the bug has been identified. Link to the PR:

https://github.com/Expensify/App/pull/18485
> * [ ]  [@sobitneupane] The offending PR has been commented on, pointing out the bug it caused and why, so the author and reviewers can learn from the mistake. Link to comment:

https://github.com/Expensify/App/pull/18485#issuecomment-2049300608

> * [ ]  [@sobitneupane] Determine if we should create a regression test for this bug.

Yes.
> * [ ]  [@sobitneupane] If we decide to create a regression test for the bug, please propose the [regression test](https://github.com/Expensify/App/blob/main/contributingGuides/REGRESSION_TEST_BEST_PRACTICES.md) steps to ensure the same bug will not reach production again.

**Comment by sobitneupane** [comment] 2024-04-11 09:36
**Regression Test Proposal:**

1. Go to any chat and upload pdf/image with width much larger than height.
2. Verify the pdf thumbnail/image does not flicker in Android/native.

Do we agree 👍 or 👎

**Comment by trjExpensify** [comment] 2024-04-11 23:37
Thanks! As it's quite the edge case, I'm down to not a regression test for it. 

Payment summary as follows:

- $500 to @sobitneupane for the C+ review (go ahead and submit)
- $500 to @jsdev2547 for the fix. 

@jsdev2547 an offer wasn't sent, so can you confirm your Upwork handle?

**Comment by jsdev2547** [comment] 2024-04-12 09:00
@trjExpensify Please check, I did receive offer (https://github.com/Expensify/App/issues/34520#issuecomment-2010595315)

**Comment by jsdev2547** [comment] 2024-04-12 10:13
@trjExpensify I accepted the offer, need to process payment.

**Closed** 2024-04-12 10:34 UTC
Labels: External, Weekly, Awaiting Payment, Bug

**Comment by JmillsExpensify** [comment] 2024-05-12 19:12
$500 approved for @sobitneupane
