### ISSUE TITLE
[HOLD for payment 2024-08-19] [$250] Report fields - List values are not arranged in alphabetical order

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#46528] opened 2024-07-30 18:17 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 9.0.14-2
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**If this was caught during regression testing, add the test name, ID and link from TestRail:** n/a
**Issue reported by:** Applause - Internal Team

## Action Performed:
1. Go to staging.new.expensify.com
2. Go to workspace settings > Report fields
3. Click Add field
4. Select List from Type
5. Go to List values and add a few list values

## Expected Result:
The list values will be arranged in alphabetical order

## Actual Result:
The list values are arranged in the order of time added

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [x] Android: mWeb Chrome
- [x] iOS: Native
- [x] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details> 

https://github.com/user-attachments/assets/1a4a17ca-6460-4e2f-9b40-b69ff898a881

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01a0087963c0b045ee</li>
        <li>Upwork Job ID: 1819053827579434361</li>
        <li>Last Price Increase: 2024-08-01</li>
<li>Automatic offers: </li>
<ul>
<li>paultsimura | Reviewer | 103375714</li>
<li>cretadn22 | Contributor | 103375715</li>
</ul></li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @isabelastisser</details>

**Comment by lanitochka17** [comment] 2024-07-30 18:17
@isabelastisser  FYI I haven't added the External label as I wasn't 100% sure about this issue. Please take a look and add the label if you agree it's a bug and can be handled by external contributors

**Comment by lanitochka17** [comment] 2024-07-30 18:18
We think that this bug might be related to #wave-control

**Comment by FitseTLT** [comment] 2024-07-30 18:23
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
Report fields - List values are not arranged in alphabetical order

### What is the root cause of that problem?
We haven't sorted the list based on the name here
https://github.com/Expensify/App/blob/3722b22302e5d89f2916d5e8958b2cf17ecb6285/src/pages/workspace/reportFields/ReportFieldsListValuesPage.tsx#L82-L96
### What changes do you think we should make in order to solve the problem?

We need to sort it as 
```
const data = listValues
            .sort((a, b) => localeCompare(a.toLocaleLowerCase, b.toLocaleLowerCase()))
            .map<ValueListItem>((value, index) => ({
                value,
                index,
                text: value,
                keyForList: value,
                isSelected: selectedValues[value],
                enabled: !disabledListValues[index] ?? true,
                pendingAction: reportFieldID ? policy?.fieldList?.[ReportUtils.getReportFieldKey(reportFieldID)]?.pendingAction : null,
                rightElement: (
                    <ListItemRightCaretWithLabel
                        shouldShowCaret={false}
                        labelText={disabledListValues[index] ? translate('workspace.common.disabled') : translate('workspace.common.enabled')}
                    />
                ),
            }));
```
### What alternative solutions did you explore? (Optional)

**Comment by nkdengineer** [comment] 2024-07-30 18:27
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
The list values are arranged in the order of time added

### What is the root cause of that problem?
We don't re-order before returning the list value here.



https://github.com/nkdengineer/App/blob/d4104a73c1a6159e61c170bbbaf3949865991852/src/pages/workspace/reportFields/ReportFieldsListValuesPage.tsx#L83


### What changes do you think we should make in order to solve the problem?
We should sort the list value before returning here. Because we also use the list value to find the index of the selected item, we should sort the list here 

```
reportFieldValues = reportFieldValues.sort((field1, field2) => localeCompare(field1.toLocaleLowerCase(), field2.toLocaleLowerCase()));
```

https://github.com/nkdengineer/App/blob/d4104a73c1a6159e61c170bbbaf3949865991852/src/pages/workspace/reportFields/ReportFieldsListValuesPage.tsx#L83

### What alternative solutions did you explore? (Optional)

**Comment by nkdengineer** [comment] 2024-07-30 18:27
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
The list values are arranged in the order of time added

### What is the root cause of that problem?
We don't re-order before returning the list value here.



https://github.com/Expensify/App/blob/d4104a73c1a6159e61c170bbbaf3949865991852/src/pages/workspace/reportFields/ReportFieldsListValuesPage.tsx#L83


### What changes do you think we should make in order to solve the problem?
We should sort the list value before returning here. Because we also use the list value to find the index of the selected item, we should sort the list here 

```
reportFieldValues = reportFieldValues.sort((field1, field2) => localeCompare(field1.toLocaleLowerCase(), field2.toLocaleLowerCase()));
```

https://github.com/Expensify/App/blob/d4104a73c1a6159e61c170bbbaf3949865991852/src/pages/workspace/reportFields/ReportFieldsListValuesPage.tsx#L83

### What alternative solutions did you explore? (Optional)

**Comment by FitseTLT** [comment] 2024-07-30 18:30
[Updated](https://github.com/Expensify/App/issues/46528#issuecomment-2258947483) to add other places we need to apply the sorting

**Comment by flodnv** [comment] 2024-08-02 15:55
I'm ooo as of now and for 10 days, @paultsimura  please reassign by commenting `🎀👀🎀 C+ reviewed`

**Comment by youssef-lr** [comment] 2024-08-02 20:23
Agree with your decision @paultsimura

**Comment by isabelastisser** [comment] 2024-08-19 17:12
@youssef-lr, do you agree with the Regression Test Proposal?

**Comment by isabelastisser** [comment] 2024-08-20 15:48
Payment summary:

@paultsimura, $250 for C+ review. Paid in Upwork.
@cretadn22, $250 for proposal. Paid in Upwork.

**Comment by isabelastisser** [comment] 2024-08-20 15:52
All set!

**Closed by isabelastisser** 2024-08-20 15:52 UTC
Labels: External, Daily, Awaiting Payment, Bug
