### ISSUE TITLE
[$1000]  Unread on LHN flickering when clicking to "messenger..."

### ISSUE THREAD

**Issue by kavimuru** [Expensify/App#23606] opened 2023-07-26 02:13 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Click FAB => New chat
2. Search new chat with new user doesn't have chat before
3. Click chat header =>  Click "Message ..."
4. Observed that the unread the report on LHN was flickering
## Expected Result: 
After clicking "Message" the report changes to unread
## Actual Result: 
Unread the report on LHN was flickering

## Workaround:
Can the user still use Expensify without this being fixed? Have you informed them of the workaround?

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [x] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 1.3.45-2
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/43996225/4bbba007-0337-45af-b4c8-c0a636ad2dcb

https://github.com/Expensify/App/assets/43996225/e9e5141c-e5ce-4c56-8193-e118541e6404

**Expensify/Expensify Issue URL:**
**Issue reported by:** @namhihi237 
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1690270610484409

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~010f7319f824ba760d</li>
        <li>Upwork Job ID: 1686040726140968960</li>
        <li>Last Price Increase: 2023-07-31</li>
    </ul>
</details>

**Comment by kavimuru** [comment] 2023-07-26 02:14
## Proposal from Contributor

## Proposal
by @namhihi237
### Please re-state the problem that we are trying to solve in this issue.
After clicking "Message" the report changes to Unread
### What is the root cause of that problem?
When we create a new report, we have `lastReadTime = null` resulting in `isUnread = true` at the time it's unread.
Then we are in this new report and click on "Message..." here we will reopen this report and dismiss the modal https://github.com/Expensify/App/blob/1580aa92892fa1d8426ef8e519b22bbf671b07f1/src/libs/actions/Report.js#L563-L575
At `OpenReport` we first update `lastReadTime` in `optimisticReportData` here https://github.com/Expensify/App/blob/1580aa92892fa1d8426ef8e519b22bbf671b07f1/src/libs/actions/Report.js#L399
=> report `isUnread = false`, since we pass params participantAccountIDList so the API return `lastReadTime = null`
That's why we see that after clicking we will see the report on LHN from unread => read => unread.
### What changes do you think we should make in order to solve the problem?
We will check if there is already chat then we will not pass `participantAccountIDList` as a param so API returns lastReadTime as read:
```
  const participantIDs = chat ? [] : participantAccountIDs;
  openReport(reportID, [], newChat, '0', false, participantIDs);
```
### What alternative solutions did you explore? (Optional)
N/A

**Comment by flaviadefaria** [comment] 2023-07-31 09:33
>Expected Result:
After clicking "Message" the report changes to unread

I was able to reproduce this but I need clarification on why the expected behavior is to have the chat marked as unread. I think it should always be marked as read since you're only starting a conversation with a new user.

**Comment by flaviadefaria** [comment] 2023-07-31 15:46
Ok I've reproduced this, but the expected behavior should be that a no time the chat is marked as unread as no message has been sent and all that the user is doing is clicking the user's name to message them.

**Comment by flaviadefaria** [comment] 2023-08-02 14:35
@sobitneupane what do you think about @namhihi237's proposal?

**Comment by sobitneupane** [comment] 2023-08-03 08:46
> Ok I've reproduced this, but the expected behavior should be that a no time the chat is marked as unread as no message has been sent and all that the user is doing is clicking the user's name to message them.


@flaviadefaria I didn't get you. Can you please clarify the expected behavior?

**Comment by sobitneupane** [comment] 2023-08-03 09:18
@flaviadefaria  As of now, on creating a new chat it is marked as unread. Do we want newly created chat report to be marked as read?

Or

Is https://github.com/Expensify/App/issues/23606#issuecomment-1662416070 expected output (where newly created as marked as unread and after pressing message username it is marked as read)?

**Comment by flaviadefaria** [comment] 2023-08-03 10:20
>@flaviadefaria As of now, on creating a new chat it is marked as unread. Do we want newly created chat report to be marked as read?

Let me confirm this internally.

**Closed** 2023-08-03 15:53 UTC
Labels: External, Daily, Help Wanted, Bug
