### ISSUE TITLE
Profile - Something went wrong error when trying to open a room/profile picture

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#34016] opened 2024-01-05 11:44 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.22-0
**Reproducible in staging?:** Y
**Reproducible in production?:** N
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** Applause - Internal Team
**Slack conversation:**

## Action Performed:
1. Open Expensify app or navigate to staging.new.expensify.com
2. Go to any room or profile details page
3. Open room or profile picture

## Expected Result:
The app should not crash when attempting to open a profile or room picture

## Actual Result:
The app crashes when attempting to open a profile or room picture
Uh-oh, something went wrong!
If the problem persists, reach out to [concierge@expensify.com](mailto:concierge@expensify.com)

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [x] Android: mWeb Chrome
- [x] iOS: Native
- [x] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details> 

https://github.com/Expensify/App/assets/78819774/3b66b8e2-573a-4835-9ba6-a6125800813d

<img width="1440" alt="Bug6332745_1704422183928!Something_went_wrong" src="https://github.com/Expensify/App/assets/78819774/e3e74566-40f7-47a0-93f2-3954e83746c4">

[logs.txt](https://github.com/Expensify/App/files/13841519/logs.txt)

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by situchan** [comment] 2024-01-05 11:54
Regression from https://github.com/Expensify/App/pull/33586

**Comment by mvtglobally** [comment] 2024-01-07 04:49
Still repro on build 1.4.22-2 

https://github.com/Expensify/App/assets/43995119/a0b532c5-9562-436d-93e0-dc22a1e1c6c1


https://github.com/Expensify/App/assets/43995119/d804398e-1b57-48ce-a349-90991ffdeecc

**Comment by thienlnam** [comment] 2024-01-08 03:06
Being handled in https://github.com/Expensify/App/pull/33586

**Comment by thienlnam** [comment] 2024-01-08 03:07
Taking this over since I am reviewing the linked PR that should fix this

**Comment by thienlnam** [comment] 2024-01-08 06:36
Verified this is fixed on staging

**Closed by thienlnam** 2024-01-08 06:36 UTC
Labels: Reviewing, DeployBlockerCash, Engineering, Weekly

**Comment by Pujan92** [comment] 2024-01-08 14:48
I am still able to reproduce the crash when opening the default avatar on the workspace chat. Can you plz confirm @namhihi237 @thienlnam 

https://github.com/Expensify/App/assets/14358475/ff5df595-a36c-4ecb-bf7a-e866a666adac

**Comment by Pujan92** [comment] 2024-01-08 14:50
> I am still able to reproduce the crash when opening the default avatar on the workspace chat. Can you plz confirm @namhihi237 @thienlnam

cc: @0xmiroslav @sobitneupane

**Comment by namhihi237** [comment] 2024-01-08 14:54
@Pujan92  Are you pull the new code from the main yet? Work well from the latest main and staging from me.

**Comment by Pujan92** [comment] 2024-01-08 14:57
Version - v1.4.22-2

<img width="376" alt="Screenshot 2024-01-08 at 20 26 45" src="https://github.com/Expensify/App/assets/14358475/5e334d74-60b5-407f-a9b9-b91cb2332783">

**Comment by namhihi237** [comment] 2024-01-08 15:04
Can you try `npm i`

**Comment by Pujan92** [comment] 2024-01-08 15:06
Ok, Tried relogin but it is crashing.

> Can you try npm i

Sure, will try now.

**Comment by Pujan92** [comment] 2024-01-08 15:11
Yes, it is not crashing now.
