### ISSUE TITLE
[HOLD for payment 2024-04-05] [$250] Web - Inconsistent behavior when saving existing name without edit

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#38668] opened 2024-03-20 12:41 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.55-0
**Reproducible in staging?:** y
**Reproducible in production?:**  new feature
**Issue reported by:** Applause - Internal Team

## Action Performed:
Precondition:
- User is admin of Collect workspace.
- The Collect workspace has categories and tags.
1. Go to staging.new.expensify.com.
2. Go to Profile > Workspaces > Collect workspace.
3. Go to Categories.
4. Click on any category.
5. Click Category name.
6. Save the name without editing.
7. Note that an error shows up.
8. Go to Tags.
9. Click on any tag.
10. Click Tag name.
11. Save the name without editing.

## Expected Result:
When saving category and tag name without editing, the behavior should be consistent. If error is meant to show up, it should show up for both. Otherwise, there should be no error for both.

For any feature - Category, tag, distance or tax, when the name is being changed but no change has been done, do nothing and just close the modal (skip the API call too)

## Actual Result:
In Step 6, error shows up when saving category name without editing it.
In Step 11, no error shows up when saving tag name without editing it.

## Workaround:
n/a

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

https://github.com/Expensify/App/assets/93399543/171faf8b-4033-4559-af9e-b5cae80fdbc3

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~017d373a5e049d77c6</li>
        <li>Upwork Job ID: 1770442815835451392</li>
        <li>Last Price Increase: 2024-03-20</li>
<li>Automatic offers: </li>
<ul>
<li>GandalfGwaihir | Contributor | 0</li>
<li>shubham1206agra | Contributor | 0</li>
</ul></li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @shubham1206agra</details>

**Comment by mountiny** [comment] 2024-03-20 12:47
This is not a blocker, its a new feature, I can take over.

**Comment by cristipaval** [comment] 2024-03-20 13:16
> This is not a blocker, its a new feature, I can take over.

Thanks @mountiny ! 🙏

**Comment by mountiny** [comment] 2024-03-20 14:14
To make it clear, we want same behavior on all pages in workspace settings where this applies:
- categories
- tags
- taxes
- distances

Whenever the user does not change the name on the page, do not show any error, make no api call and close the modal

**Comment by mountiny** [comment] 2024-03-20 14:14
@ntdiary can you please review the proposals

**Comment by askavyblr** [comment] 2024-03-20 14:15
### Proposal

### Please re-state the problem that we are trying to solve in this issue.

When storing the category and tag name as is, without any modifications, the process should remain uniform. It is not necessary to display an error for the category.

### What is the root cause of that problem?

We have a mechanism in place to check for duplicate categories, but it is incorrect.

https://github.com/Expensify/App/blob/0fa4d0f2a200d58af452fa6c37bdc27b7f7fe2d5/src/pages/workspace/categories/CategoryForm.tsx#L42-L43

### What changes do you think we should make in order to solve the problem?

https://github.com/Expensify/App/blob/0fa4d0f2a200d58af452fa6c37bdc27b7f7fe2d5/src/pages/workspace/categories/CategoryForm.tsx#L42-L43

`policyCategories?.[newCategoryName] && currentCategoryName !== newCategoryName`

### What alternative solutions did you explore? (Optional)

N/A

**Comment by TVictor87** [comment] 2024-03-20 14:39
Greetings 🤝🏻
If we take a general look, there are simply different behaviors in two places for the same action. In categories, when editing, there's a check for an existing category. But in tags, there isn't. To understand why this is the case, we need to dive into the project and examine the code.

Perhaps in categories, the request is not for editing but for creating, which is why the error "category with this name already exists" occurs.

Would you be open to connect on Upwork to further discuss the details?

Best regards,
Viktor

**Comment by TVictor87** [comment] 2024-03-20 14:41
Greetings 🤝🏻
If we take a general look, there are simply different behaviors in two places for the same action. In categories, when editing, there's a check for an existing category. But in tags, there isn't. To understand why this is the case, we need to dive into the project and examine the code.

Perhaps in categories, the request is not for editing but for creating, which is why the error "category with this name already exists" occurs.

Would you be open to connect on Upwork to further discuss the details?

Best regards,
Viktor

**Comment by mountiny** [comment] 2024-03-20 14:42
If we are only going to be changing this for tags, I am going to drop the price to $250

**Comment by TVictor87** [comment] 2024-03-20 14:44
Contributor details
Your Expensify account email: tershivskiyvictor@gmail.com
Upwork Profile Link: https://www.upwork.com/jobs/~017d373a5e049d77c6

**Comment by mountiny** [comment] 2024-03-20 14:50
I believe its not a complex change to not call the API

**Comment by mountiny** [comment] 2024-03-29 22:16
$250 to @GandalfGwaihir and $250 to @shubham1206agra

**Comment by slafortune** [comment] 2024-04-05 15:47
@shubham1206agra please accept this offer - https://www.upwork.com/nx/wm/offer/101650388
@GandalfGwaihir  - Paid

**Comment by slafortune** [comment] 2024-04-11 17:04
@shubham1206agra please accept this offer - https://www.upwork.com/nx/wm/offer/101650388

**Comment by slafortune** [comment] 2024-04-15 14:39
I'll be out of the office until 4/22 and will check on this then.

**Comment by slafortune** [comment] 2024-04-23 21:40
Yep, just back today!  Paid and closing ✔️

**Closed by slafortune** 2024-04-23 21:40 UTC
Labels: External, Engineering, Weekly, Awaiting Payment, Bug
