### ISSUE TITLE
[Awaiting Payment April 29th] HIGH: [Performance] [$500] Reliably unsubscribe from isTyping events when leaving rooms

### ISSUE THREAD

**Issue by quinthar** [Expensify/App#38905] opened 2024-03-25 01:55 UTC
Problem:
====
When you join a room, you subscribe to various Pusher channels that should only be active while in that room.  However, when you leave the room, sometimes it doesn't unsubscribe you from the channels.  This "leak" will gradually slow down the app.  But particularly concerning is that it will cause you to receive Pusher events that do not relate to the current room (such as "istyping" events in rooms you aren't looking at), and thus drag down your performance.

Solution:
====
Reliably unsubscribe from the room's Pusher channel when leaving by any method. There is a theory that we do this when leaving a room to switch to another, but perhaps not when leaving the room to go to a non-room page (eg, Settings).

See: https://expensify.slack.com/archives/C049HHMV9SM/p1711131919203929
<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~012a36c87d591ea59b</li>
        <li>Upwork Job ID: 1773645194916745216</li>
        <li>Last Price Increase: 2024-03-29</li>
<li>Automatic offers: </li>
<ul>
<li>jjcoffee | Reviewer | 0</li>
<li>tienifr | Contributor | 0</li>
</ul></li>
    </ul>
</details>

**Comment by quinthar** [comment] 2024-03-29 02:25
yes please!

**Comment by dylanexpensify** [comment] 2024-03-29 09:35
Let's get it!

**Comment by quinthar** [comment] 2024-03-30 06:04
Hi!  What's the ETA on assigning this out?

**Comment by Beamanator** [comment] 2024-03-31 14:09
Yo yo! I'm planning to review the review tomorrow, so should be able to get someone assigned early 👍

**Comment by Beamanator** [comment] 2024-03-31 20:47
I like @tienifr 's proposal as well so let's move forward!

**Comment by jjcoffee** [comment] 2024-04-01 14:17
There are a couple of extra cases I've found that we need to handle on the PR. Waiting on @tienifr to look into it :pray:

**Comment by quinthar** [comment] 2024-04-02 23:16
@jjcoffee do you mean taht @tienifr should re-review?  @tienifr can you please do this today, or what's your ETA?

**Comment by mvtglobally** [comment] 2024-04-04 03:29
Issue not reproducible during KI retests. (First week)

**Comment by quinthar** [comment] 2024-04-17 18:43
What's the update here?

**Comment by Beamanator** [comment] 2024-04-18 12:44
Yes sorry for not updating here! Was merged 3 days ago, on staging as of 7 hours ago 🙏 🚀

**Comment by quinthar** [comment] 2024-04-25 02:23
Can we close this?

**Comment by Beamanator** [comment] 2024-04-25 08:42
Hmm this has been in prod for only 3 days now, so i don't believe we should close - we normally wait 7 days before payment & before considering the PR having caused no regressions

**Comment by quinthar** [comment] 2024-04-27 19:23
Should this be tagged `Awaiting Payment` then?

**Comment by Beamanator** [comment] 2024-04-29 07:47
Aah true, I think that automation wasn't working one day last week, so I manually updated 👍 

@dylanexpensify FYI looks like payment is due today! 😅

**Comment by dylanexpensify** [comment] 2024-04-29 10:29
Wahooo! Will do it!

**Comment by dylanexpensify** [comment] 2024-04-29 10:30
Payment summary:
- Contributor: @tienifr $500
- Contributor+: @jjcoffee $500

Please apply/request!

**Comment by jjcoffee** [comment] 2024-04-29 12:08
- The PR that introduced the bug has been identified. Link to the PR: **N/A - this behaviour was always present**
- The offending PR has been commented on, pointing out the bug it caused and why, so the author and reviewers can learn from the mistake. Link to comment: **N/A**
- A discussion in #expensify-bugs has been started about whether any other steps should be taken (e.g. updating the PR review checklist) in order to catch this type of bug sooner. Link to discussion: **N/A**
- Determine if we should create a regression test for this bug. **Yes**
- If we decide to create a [regression test](https://github.com/Expensify/App/blob/main/contributingGuides/REGRESSION_TEST_BEST_PRACTICES.md) for the bug, please propose the regression test steps to ensure the same bug will not reach production again.

**Regression Test Proposal**

1. Device A: Sign in with user A and open report with user B
2. Device B: Sign in with user B and open report with user A
3. Device A: Type anything in composer
4. Device B: Verify that there is a text "User A is typing..." appears below the composer for a while
5. Device B: Open another report
6. Device A: Type anything in composer
7. Device B: Open developer mode, choose "Console" tab. Verify that there is no `reportUserIsTyping...` log in console, e.g. `[info] [Onyx] merge() called for key: reportUserIsTyping_4555629044294735 properties: 15225462 - ""`

Do we agree 👍 or 👎

**Comment by dylanexpensify** [comment] 2024-05-08 19:38
nice!

**Comment by dylanexpensify** [comment] 2024-05-08 19:39
done!

**Closed by dylanexpensify** 2024-05-08 19:39 UTC
Labels: External, Engineering, Daily, Improvement, Task, Awaiting Payment, Bug
