### ISSUE TITLE
IOU Receipt - Add receipt icon in receipt attachment modal is partially colored

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#33778] opened 2023-12-29 19:37 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.20-0
**Reproducible in staging?:** Y
**Reproducible in production?:** N
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** Applause - Internal Team
**Slack conversation:**

## Action Performed:
1. Create a manual request with no receipt
2. Go to the request details page

## Expected Result:
The add receipt icon in receipt attachment modal is fully colored

## Actual Result:
The add receipt icon in receipt attachment modal is partially colored

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [x] Android: mWeb Chrome
- [ ] iOS: Native
- [x] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details> 

![Bug6328647_1703876214773!bandicam_2023-12-30_02-34-35-976](https://github.com/Expensify/App/assets/78819774/a8366d69-82dc-4d44-b2f7-a449f1b92aff)

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by mountiny** [comment] 2023-12-29 19:42
Dupe of https://github.com/Expensify/App/issues/33777

**Closed by mountiny** 2023-12-29 19:42 UTC
Labels: Engineering, Hourly
