### ISSUE TITLE
[Hold for payment 2022-12-20] Web - The "FAB" menu and the sidebar can be opened at the same time

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#13159] opened 2022-11-29 20:38 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Go to https://staging.new.expensify.com/
2. Login with any account
3. Click on the global create button. 
4. Press "CTRL+K" (command + k on mac). 
5. Notice that the global create menu stays open with right pane. 
6. Click the chat area outside of both global create menu and right pane. Notice that neither close. 
7. Try to click the X in the top right corner of right pane. Notice it does not close. 

## Expected Result:
Global create menu must close when typing command +  K (which opens right pane). Further, when this happens, the user should be able to successfully interact with the menu options in the right pane, and close it, 

## Actual Result:
1. The global create menu stays open alongside the right pane when typing command + k
2. User cannot close global create or right pane menus. 

## Workaround:
command + r force reloads the browser on web and resolves the issue. 

## Platform:

Where is this issue occurring?

- Web

**Version Number:** 1.2.33.2

**Reproducible in staging?:** Yes

**Reproducible in production?:** Yes

**Email or phone of affected tester (no customers):** 

**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Notes/Photos/Videos:** Any additional supporting documentation

https://user-images.githubusercontent.com/93399543/204642574-2adcc85a-f8b0-4f4f-ab6d-ae8a51f8cb96.mp4

**Expensify/Expensify Issue URL:** 

**Issue reported by:** Applause - Internal Team

**Slack conversation:** 

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

## Upwork Automation - Do Not Edit
- Upwork Job URL: https://www.upwork.com/jobs/~015fb8fe5245972fe6
- Upwork Job ID: 1598081974853922816

**Comment by joekaufmanexpensify** [comment] 2022-11-29 21:12
From this SO: https://stackoverflow.com/c/expensify/questions/14418
- [ ] **The "bug" is actually a bug**: 
- [ ] **The bug is not a duplicate report of an existing GH (close the GH and add any novel details to the original GH instead)**: 
- [ ] **The bug is reproducible, following the reproduction steps:**
- [ ] **If you're unable to reproduce the bug, add the _Needs reproduction_ label. Comment on the issue outlining the steps you took to try to reproduce the bug, your results and tag the issue reporter and the Applause QA member who created the issue. Ask them to clarify reproduction steps and/or to check the reproduction steps again. Close issue.**: 
- [ ] **The GH template is filled out as fully as possible -- this means the GH body and title are clear (ie. could an external contributor understand it and work on it?):** 
- [ ] **The GH was created by an Expensify employee or a QA tester:** 
- [ ] **If the bug is an OldDot issue, you should decide whether it is widespread enough to justify fixing or it is better to wait for reunification. If it's better to wait, close the GH & provide this justification:** 
- [ ] **If there's a link to Slack, check the discussion to see if we decided not to fix it:** 
- [ ] **Decide if the GH should be resolved by an External contributor or Internal engineer, add the appropriate label:**

**Comment by joekaufmanexpensify** [comment] 2022-11-29 21:17
This is def a bug. I reproduced on web: 
![2022-11-29_16-16-33 (1)](https://user-images.githubusercontent.com/54866469/204649761-2a389063-4d27-41e1-8ba4-79d083106e04.gif)

Discussing the exact scope of the bug in slack before proceeding.

**Comment by hannojg** [comment] 2022-11-30 10:04
> I think @hannojg copy & pasted wrong code while moving from BaseSidebarScreen to FloatingActionButtonAndPopover

Oh yeah, that's very likely - good catch!

**Comment by joekaufmanexpensify** [comment] 2022-11-30 17:13
Finished triaging this. My thinking is we can handle this externally. Assigning engineering to confirm!

**Comment by mountiny** [comment] 2022-11-30 22:30
@0xmiroslav

**Comment by mountiny** [comment] 2022-11-30 22:31
@sobitneupane I have gone ahead and assigned @0xmiroslav as the proposal seems very reasonable to me. Let me know if you have any concerns, thank you!

**Comment by joekaufmanexpensify** [comment] 2022-12-01 19:16
Okay, going to hire everyone. I'll be hiring: 

- @sobitneupane 
- @0xmiroslav 

This was reported by applause, so no reporting bonus.

**Comment by joekaufmanexpensify** [comment] 2022-12-01 19:18
Sent invitations to both of you to apply. LMK when you've submitted a proposal and I'll hire you!

**Comment by joekaufmanexpensify** [comment] 2022-12-02 19:04
@sobitneupane hired!

**Comment by joekaufmanexpensify** [comment] 2022-12-02 19:04
@0xmiroslav please submit proposal when you have a chance so I can hire you.

**Comment by joekaufmanexpensify** [comment] 2022-12-05 18:03
@0xmiroslav thanks for submitting a proposal! I sent you an offer for $1,000 on upwork. (I reduced amount from $1,500 to $1,000 as the job amount is $1,000. Because the PR was merged within 3 business days though, we will also add a $500 bonus at the time of payment, bringing the total to $1,500.) 

LMK if you have any questions!

**Comment by joekaufmanexpensify** [comment] 2022-12-06 16:29
PR is merged, and QA is ongoing.

**Comment by joekaufmanexpensify** [comment] 2022-12-07 19:27
Same.

**Comment by joekaufmanexpensify** [comment] 2022-12-08 17:15
Same.

**Comment by joekaufmanexpensify** [comment] 2022-12-09 18:34
QA still ongoing.

**Comment by joekaufmanexpensify** [comment] 2022-12-12 19:56
Same.

**Comment by joekaufmanexpensify** [comment] 2022-12-13 16:02
Same

**Comment by joekaufmanexpensify** [comment] 2022-12-14 18:51
The solution for this issue has been 🚀 deployed to production 🚀 in version 1.2.38-6 and is now subject to a 7-day regression period 📆. Here is the list of pull requests that resolve this issue:

https://github.com/Expensify/App/pull/13226

If no regressions arise, payment will be issued on 2022-12-20. 🎊

After the hold period, please check if any of the following need payment for this issue, and if so check them off after paying:

- [ ] External issue reporter
- [ ] Contributor that fixed the issue
- [ ] Contributor+ that helped on the issue and/or PR

As a reminder, here are the bonuses/penalties that should be applied for any External issue:

- Merged PR within 3 business days of assignment - 50% bonus
- Merged PR more than 9 business days after assignment - 50% penalty

**Comment by joekaufmanexpensify** [comment] 2022-12-14 18:53
BugZero Checklist: The PR fixing this issue has been merged! The following checklist ([instructions](https://stackoverflow.com/c/expensify/questions/14574)) will need to be completed before the issue can be closed:

- [ ]  [@sobitneupane  / @mountiny] The PR that introduced the bug has been identified. Link to the PR:
- [ ]  [@sobitneupane  / @mountiny] The offending PR has been commented on, pointing out the bug it caused and why, so the author and reviewers can learn from the mistake. Link to comment:
- [ ]  [@sobitneupane  / @mountiny] A discussion in #expensify-bugs has been started about whether any other steps should be taken (e.g. updating the PR review checklist) in order to catch this type of bug sooner. Link to discussion:
- [ ]  [@joekaufmanexpensify] A [regression test](https://expensify.testrail.io/index.php?/dashboard) has been added or updated so that the same bug will not reach production again. Link to the GH issue for creating the test here:

**Comment by mountiny** [comment] 2022-12-14 21:39
I dont think there are any changes to the checklist or our process required to prevent this issue, this was a mistake all reviewers missed so the best way is for us to be more thorough in the review and with the testrail test, this should not happen again.

**Comment by mountiny** [comment] 2022-12-14 21:39
@joekaufmanexpensify Will you be able to add a testRail regression test please?

**Comment by joekaufmanexpensify** [comment] 2022-12-14 22:01
Yep, will work on getting this added!

**Comment by joekaufmanexpensify** [comment] 2022-12-19 21:52
Proposed new regression test [here. ](https://expensify.slack.com/archives/C01SKUP7QR0/p1671486709702439)

**Comment by joekaufmanexpensify** [comment] 2022-12-20 20:46
Linked new regression test above in BZ checklist.

**Comment by joekaufmanexpensify** [comment] 2022-12-20 20:48
This was an issue where the BZ checklist/payment automation was not working, so moving this one back to daily manually as 7 days have passed with no regressions, so we can now issue payment.

**Comment by joekaufmanexpensify** [comment] 2022-12-20 20:59
@0xmiroslav $1,500 sent, and contract ended!

**Comment by joekaufmanexpensify** [comment] 2022-12-20 21:00
@sobitneupane $1,500 sent, and contract ended!

**Comment by joekaufmanexpensify** [comment] 2022-12-20 21:02
Job closed in Upwork.

**Comment by joekaufmanexpensify** [comment] 2022-12-20 21:02
Closing as this is all set!

**Closed by joekaufmanexpensify** 2022-12-20 21:02 UTC
Labels: Reviewing, External, Engineering, Daily, Awaiting Payment, Bug
