### ISSUE TITLE
[$250] Search - Infinite loading when searching for a non existing user

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#39866] opened 2024-04-08 21:17 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.61-0
**Reproducible in staging?:** Y
**Reproducible in production?:** N
**If this was caught during regression testing, add the test name, ID and link from TestRail:** N/A
**Issue reported by:** Applause - Internal Team

**Issue found when executing PR** https://github.com/Expensify/App/pull/39384
## Action Performed:
1. Access staging.new.expensify.com
2. Sign into a valid account
3. Search for a non existing user
4. Once the DM is open, tap on the header

## Expected Result:
User expects that when tapping on the header, the users info modal will open from the right

## Actual Result:
When user first tries to tap on search modal, there is a small "Locked" symbol, then after a while, the header name will completely disappear and begin to load indefinitely. On Desktop app, the app even crashed once while performing this

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [x] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details> 

https://github.com/Expensify/App/assets/78819774/5cd7c8cb-e125-4f15-aea4-59051ac3149f

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01fe30a5f76eb81164</li>
        <li>Upwork Job ID: 1777450137396224000</li>
        <li>Last Price Increase: 2024-04-08</li>
    </ul>
</details>

**Comment by lanitochka17** [comment] 2024-04-08 21:18
@aldo-expensify  FYI I haven't added the External label as I wasn't 100% sure about this issue. Please take a look and add the label if you agree it's a bug and can be handled by external contributors

**Comment by lanitochka17** [comment] 2024-04-08 21:18
We think that this bug might be related to #vip-vsp

**Comment by aldo-expensify** [comment] 2024-04-08 21:31
I can reproduce often, but doesn't always happen. And sometimes the top bar goes into loading state and the email disappears from the LHN without having to even click on it:

<img width="950" alt="image" src="https://github.com/Expensify/App/assets/87341702/946ecec4-a5e5-4009-8f45-7c831e80ac75">

**Comment by aldo-expensify** [comment] 2024-04-08 21:34
Can't reproduce in Production. I'll open it to `external` as I don't see a difference in the `onyxData` coming from the server when comparing production vs staging.

**Comment by aldo-expensify** [comment] 2024-04-08 22:48
Thanks for checking @GandalfGwaihir. Now I see that I can reproduce only reproduce with `@expensifail.com` accounts but not logged in as a `@gmail.com` account. I think this can mean one of two things:

- The problem is because the domain is excluded from reliable updates because of beta flags, or
- The problem is related to domain-controlled accounts

**Comment by aldo-expensify** [comment] 2024-04-08 22:51
Reproduced in dev disabling "reliable updates" for a `@gmail.com` account

**Comment by aldo-expensify** [comment] 2024-04-08 23:08
Seems like the personal details somehow go missing from onyx

**Comment by aldo-expensify** [comment] 2024-04-08 23:35
I think this is a product of my work moving the OpenReport onyx updates from Web-Expensify to Auth. These two PRs:

https://github.com/Expensify/Web-Expensify/pull/41310
https://github.com/Expensify/Auth/pull/10226

That works based on the assumption that the onyx update created and queued in Auth will be automatically included in the response in PHP later, but this doesn't happen thanks to the Reliable updates check here: https://github.com/Expensify/Web-Expensify/blob/9665848765ad8df8dd478dd3a3a242a6ead62ea6/lib/Onyx.php#L368

Then, I made this third PR to kill some code I thought unnecessary https://github.com/Expensify/Web-Expensify/pull/41492. The removed code unintentionally was still adding the missing report update for accounts with reliable updates disabled.

Considering the above, this is not an App deploy blocker because the bug is in the staging PHP API.

**Comment by aldo-expensify** [comment] 2024-04-09 18:31
I merged this PR which should fix the problem once deployed: https://github.com/Expensify/Web-Expensify/pull/41588
Also, we are trying to get rid of the reliable updates beta asap, so that would have fixed it too.

**Comment by alexpensify** [comment] 2024-04-12 23:15
Aldo, I think the only action is the get rid of the beta-- is that right? Thanks!

**Comment by aldo-expensify** [comment] 2024-04-15 17:25
> I think the only action is the get rid of the beta-- is that right? Thanks!

This is fixed now, I just tested.

**Closed by aldo-expensify** 2024-04-15 17:25 UTC
Labels: Reviewing, External, Engineering, Daily, Bug

**Comment by alexpensify** [comment] 2024-04-15 17:59
No payment is due here, all reviews were handled internally
