### ISSUE TITLE
[$1000] Web - Getting a task assigned to you unpins sender's chat in LHN

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#23891] opened 2023-07-30 19:54 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Log into two accounts in separate tabs on Mac Chrome (one might need to be in an incognito window).
2. As "User A", ensure "User B's" chat is pinned by clicking on their chat in the LHN and then clicking on the pin icon on the top right of the screen.
3. As "User B", click on "User A's" chat and then on the "+" in the composer and choose "Assign task".
4. Add a title and click "Next".
5. Select "User A" as both the assignee and as the option in "Share somewhere" (you don't need to click on **Confirm task**)
6. Switch to the tab you're logged in as "User A".
7. Observe the LHN.

## Expected Result:
"User B's" chat remains pinned in "User A's" LHN after "User B" selects them as an assignee for a task.

## Actual Result:
"User B's" chat gets unpinned in "User A's" chat, after "User B" selects them as an assignee for a task ("User B" doesn't need to create the task for this to happen). Sometimes the chat is briefly unpinned, while other times, you have to click on a different chat for it to be re-pinned.

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [x] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 1.3.47-3
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/93399543/d00fd892-c00a-4cce-b0e5-f22ed9c094a3

https://github.com/Expensify/App/assets/93399543/58fc1e80-6192-4a42-91ef-d44d7639754e

**Expensify/Expensify Issue URL:**
**Issue reported by:** @Victor-Nyagudi
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1690618024593589

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~014a5fd4b54bde0755</li>
        <li>Upwork Job ID: 1686325311654125568</li>
        <li>Last Price Increase: 2023-08-08</li>
    </ul>
</details>

**Comment by conorpendergrast** [comment] 2023-07-31 08:25
I'm sorry, I haven't been able to reproduce this yet! I tried with Chrome and Safari, and Chrome (normal) and Chrome (incognito) and haven't been able to get the same effect. The chats remain pinned after the task is created.

I'll close this now unless there are steps that I'm missing to reproduce!

**Comment by Victor-Nyagudi** [comment] 2023-07-31 08:52
@conorpendergrast I've just reproduced this.

https://github.com/Expensify/App/assets/79470910/ec238df1-a01e-4b0d-9c40-54f2fc8c9a2c

The window on the left is the regular Chrome, and the one on the right is the incognito one. 

Could you kindly share a video of how you're trying to reproduce this?

**Comment by conorpendergrast** [comment] 2023-08-01 10:36
Ah, I was able to reproduce. But, check out this recording. You **don't need to finish creating the task** to reproduce. It's when you select user A as the assignee, not when you click **Confirm task**, that the chat is unpinned


https://github.com/Expensify/App/assets/5802477/97181e82-4fd5-4b3b-b42b-9f588fc02f83

**Comment by railway17** [comment] 2023-08-01 15:42
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
Getting a task assigned to you unpins sender's chat in LHN

### What is the root cause of that problem?
Let's says User A pinned the User B chat.
And User B is trying to create task and assign to User A.
Assumed their chat reportID is `report_xxx`.
Even though User A pinned this report, User B didn't pin it.

By `onSelectRow` props in AssigneeList (`TaskAssigneeSelectorModal > OptionsSelector component`), it calls `Task.setAssigneeValue` method.
Inside of `setAssigneeValue` method, it calls `OpenReport` API with this `report_xxx` key.
_I think only participant's information is different in User A/User B's report for same reportID and using same report from backend._
Because of this `report.isPinned = false` in User B side, it is updated to false while calling `OpenReport` API.
And it is subscribed to User A side.
That's why, User A's report is unpinned.
We can confirm by pinning and trying from User B side.
If pin `report_xxx` in User B side and reproduce above steps, it works as expected result.

### What changes do you think we should make in order to solve the problem?
In the `setAssigneeValue` method, we don't need to call `OpenReport` api if chat is existing.
So, we can fix this code like below

```diff
function setAssigneeValue(assignee, assigneeAccountID, shareDestination, isCurrentUser = false) {
    let newAssigneeAccountID = Number(assigneeAccountID);

    // Generate optimistic accountID if this is a brand new user account that hasn't been created yet
    if (!newAssigneeAccountID) {
        newAssigneeAccountID = UserUtils.generateAccountID(assignee);
    }
    if (!isCurrentUser) {
        let newChat = {};
        const chat = ReportUtils.getChatByParticipants([newAssigneeAccountID]);
        if (!chat) {
            newChat = ReportUtils.buildOptimisticChatReport([newAssigneeAccountID]);
+          const reportID = chat ? chat.reportID : newChat.reportID;
+    
+            if (!shareDestination) {
+                setShareDestinationValue(reportID);
+            }
+            Report.openReport(reportID, [assignee], newChat);
         }
-        const reportID = chat ? chat.reportID : newChat.reportID;
-
-        if (!shareDestination) {
-            setShareDestinationValue(reportID);
-        }
-
-        Report.openReport(reportID, [assignee], newChat);

    }

    // This is only needed for creation of a new task and so it should only be stored locally
    Onyx.merge(ONYXKEYS.TASK, {assignee, assigneeAccountID: newAssigneeAccountID});
}
```

### What alternative solutions did you explore? (Optional)
We may update the backend in order to prevent updating the `isPinned` based on `report-participants`

**Comment by akamefi202** [comment] 2023-08-02 15:37
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
Getting a task assigned to you unpins sender's chat in LHN.

### What is the root cause of that problem?
Let's assume that there is a chat which includes user A & user B. User A pinned the chat and user B didn't pin it.
So `isPinned` value of report data is `true` for user A, `false` for user B.

![Untitled1](https://github.com/Expensify/App/assets/53784473/300b77ec-8e68-4922-96b8-233a793a93b6)

If user B creates a task and assign it to user A, the frontend of user B calls OpenReport API to update assignee.
And then the frontend of user A receives the updated report data sent by Pusher and updates the chat report page with received data.

![Untitled3](https://github.com/Expensify/App/assets/53784473/2c10df4a-453a-4941-903e-e4c4b7d0f323)

The problem is that received data contains `isPinned` value of user B which is `false` currently.
So if the frontend of user A updates the chat report page with received data, it will be unpinned although `isPinned` value of user A is `true`.

This could happen in opposite way too. For example, if user A unpinned the chat and user B pinned it, assigning will pin the chat in the frontend of user A.

### What changes do you think we should make in order to solve the problem?
We should remove `isPinned` value before updating onyxData with it.
https://github.com/Expensify/App/blob/6292e5b2e90f4b00d544e7ffbd7f52ed0e1aab55/src/libs/actions/User.js#L565-L574

We don't need to update `isPinned` value of chat report using the data sent by Pusher because it's usually value of other user.
So we should ignore it and the chat report will keep its pin status.
```
_.map(pushJSON, (onyxData) => {
    const reportRegex = new RegExp('^report_[0-9]*$', 'g');
    if (onyxData.onyxMethod === Onyx.METHOD.MERGE && reportRegex.test(onyxData.key)) {
        onyxData.value = _.omit(onyxData.value, 'isPinned')
    }
    return onyxData;
});
```

### What alternative solutions did you explore? (Optional)
N/A

**Comment by akamefi202** [comment] 2023-08-03 06:25
@allroundexperts @conorpendergrast 
I think it's impossible for Pusher to send correct `isPinned` value of the user.

```
pusher.trigger('my-channel', 'my-event', {
  "message": "hello world"
});
```

This is how Pusher sends data to clients. It just broadcasts data to subscribers of the channel.

```
var channel = pusher.subscribe('my-channel');
channel.bind('my-event', function(data) {
  alert('Received my-event with message: ' + data.message);
});
```

And in the client side, clients who subscribed the channel will receive that data.
Pusher don't know who will receive the data and it can't send correct `isPinned` value for the user.
`isPinned` value is different for each user. It depends on whether the user pinned it or not.
So I think we need to ignore `isPinned` value in the frontend while updating report page with data received from Pusher.

**Comment by railway17** [comment] 2023-08-04 13:23
@allroundexperts 
Do you think we should call OpenReport API while selecting assignee?

**Comment by conorpendergrast** [comment] 2023-08-08 10:01
@robertjchen Hey! Tagging you in here, to confirm @allroundexperts's point [earlier](https://github.com/Expensify/App/issues/23891#issuecomment-1663238937)

**Comment by robertjchen** [comment] 2023-08-09 19:17
Thanks, let me evaluate

**Comment by robertjchen** [comment] 2023-08-22 06:58
Diving back into this to see if I can reproduce the issue locally

**Comment by conorpendergrast** [comment] 2023-08-25 13:21
@robertjchen Any joy here Bobby?

**Comment by akamefi202** [comment] 2023-08-25 13:31
@conorpendergrast @robertjchen @allroundexperts 
Could you please review my proposal and investigation again?
I think this issue can be fixed from FE. Please let me know your opinion.
https://github.com/Expensify/App/issues/23891#issuecomment-1662436128
https://github.com/Expensify/App/issues/23891#issuecomment-1663363925

**Comment by robertjchen** [comment] 2023-08-28 05:42
> Pusher don't know who will receive the data and it can't send correct isPinned value for the user.
> isPinned value is different for each user. It depends on whether the user pinned it or not.

We have logic in the backend that customizes the pusher message for each user 👍 It's a matter of us handling this flag properly. Local testing in-progress 👍

**Comment by robertjchen** [comment] 2023-08-30 10:41
Still testing things out, aiming for a resolution by EOW

**Comment by robertjchen** [comment] 2023-09-04 08:52
Didn't get to this one due to ongoing priorities, will check it out this week for sure.

**Comment by robertjchen** [comment] 2023-09-11 09:19
ok, just shipped something big and now have some time. This week for sure!

**Comment by conorpendergrast** [comment] 2023-09-11 11:30
@adelekennedy I'm on parental leave; re-assigning! This has been triaged and Bobby is working on it as an internal fix

**Comment by robertjchen** [comment] 2023-09-14 10:11
Yep, still an internal fix 🙏

**Comment by adelekennedy** [comment] 2023-09-18 08:36
not overdue - Bobby is working on a fix!

**Comment by adelekennedy** [comment] 2023-09-21 10:01
@robertjchen how's the fix coming?

**Comment by robertjchen** [comment] 2023-09-22 08:12
It's coming after Offshore 😄

**Comment by adelekennedy** [comment] 2023-09-25 07:56
moving this to weekly then!

**Comment by robertjchen** [comment] 2023-10-09 10:10
Diving back into this

**Comment by adelekennedy** [comment] 2023-10-17 23:52
@robertjchen I'm going to unassign myself for now but am happy to be re-added for payment or any next steps!

**Comment by Victor-Nyagudi** [comment] 2023-10-27 18:49
I'm curious if the reporting bonus could be paid early for this one.

It was reported over 3 months ago, and it's already been decided it'll be fixed internally (once all the delays are dealt with).

Just thinking out loud.

**Comment by robertjchen** [comment] 2023-10-31 11:28
That makes sense to me, what are your thoughts @adelekennedy ?

**Comment by adelekennedy** [comment] 2023-10-31 16:03
@Victor-Nyagudi sent offer!

**Comment by Victor-Nyagudi** [comment] 2023-10-31 16:08
@adelekennedy This was reported before the price decrease of August 30th.

The reporting bonus for issues reported before then were to be $250.

https://expensify.enterprise.slack.com/archives/C01GTK53T8Q/p1693424078129649?thread_ts=1693424078.129649&cid=C01GTK53T8Q

Did something change?

**Comment by Victor-Nyagudi** [comment] 2023-11-02 06:04
I haven't accepted the offer yet, by the way.

**Comment by Victor-Nyagudi** [comment] 2023-11-03 14:57
Friendly bump @adelekennedy to see if we can figure out the reporting bonus before the weekend.

cc: @robertjchen in case she doesn't see this in time.

**Comment by adelekennedy** [comment] 2023-11-09 18:34
Sorry! I was on ooo - updating now

**Comment by Victor-Nyagudi** [comment] 2023-11-09 19:02
No worries.

I've accepted the offer.

Thank you.

**Comment by Victor-Nyagudi** [comment] 2023-11-16 08:12
@adelekennedy I accepted the offer and submitted a milestone on Upwork, but the funds won't be released until you take action on your end.

I'm yet to receive any payment.

**Comment by adelekennedy** [comment] 2023-11-20 23:02
this slipped my radar - just paid now

**Comment by robertjchen** [comment] 2023-11-29 13:23
Thanks! Closing this for now

**Closed by robertjchen** 2023-11-29 13:23 UTC
Labels: Engineering, Weekly, Internal, Overdue, Bug
