### ISSUE TITLE
[$1000] Web -  Bug in Keyboard Shortcuts Modal opening/closing behaviour

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#23696] opened 2023-07-26 20:58 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Open ND
2. Press `CTRL + J` to open the Keyboard Shortcuts Modal
3. Press `CTRL + J`

## Expected Result:
Keyboard Shortcuts Modal should not close on pressing `CTRL + J`  after opening Keyboard Shortcuts Modal

## Actual Result:
Keyboard Shortcuts Modal closes on pressing `CTRL + J`  after opening Keyboard Shortcuts Modal

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [x] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 1.3.45-7
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/93399543/0b20cd60-5128-4285-87e1-f267e8ffd5b5

https://github.com/Expensify/App/assets/93399543/572d2f1d-afac-49fa-bb23-4613e1d4b515

**Expensify/Expensify Issue URL:**
**Issue reported by:** @shubham1206agra
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1690382150018799

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01caad76786cb2948d</li>
        <li>Upwork Job ID: 1684656116445630464</li>
        <li>Last Price Increase: 2023-07-27</li>
    </ul>
</details>

**Comment by shubham1206agra** [comment] 2023-07-27 05:20
## Proposal
### Please re-state the problem that we are trying to solve in this issue.

Web - Bug in Keyboard Shortcuts Modal opening/closing behaviour

### What is the root cause of that problem?

useEffect has empty dependency array and the change of `isShortcutModalOpen` is not reflected here so the early return statement never gets triggered and only closes the modal with `ModalActions.close();`.

https://github.com/Expensify/App/blob/0d876a4a4e8975cc9df9ae606dcda118d0e2291d/src/components/KeyboardShortcutsModal.js#L113-L126

However, the `KeyboardShortcutsActions.showKeyboardShortcutModal();` does not re-open it, as this function also checks if `isShortcutsModalOpen` is set. The difference is that this uses a synced copy retrieved using Onyx.connect, therefore leading to a return statement.

https://github.com/Expensify/App/blob/0d876a4a4e8975cc9df9ae606dcda118d0e2291d/src/libs/actions/KeyboardShortcuts.js#L14-L19

Another problem 
On refresh, while opening this modal, the value inside Onyx is different from value reflected in `KeyboardShortcutsModal` component. Non persistence of KeyboardShortcutsModal is intentional. But the workaround is not very good.
https://expensify.slack.com/archives/C01GTK53T8Q/p1683563738386549?thread_ts=1683551147.132719&cid=C01GTK53T8Q

### What changes do you think we should make in order to solve the problem?

I think we should not use onyx to store visibility state as this is not persistable modal, and so we should use state variable inside KeyboardShortcutsModal component.

Since KeyboardShortcutsModal is functional component, we can expose the methods to update the variables using `useImperativeHandle` hook, and we can use the function by getting ref from `Expensify` component.

We can update the KeyboardShortcutsActions similar to `src/libs/Growl.js` to call update functions one-at-a-time so that any other issues will not occur.

To stop running useEffect in which `CTRL+J` shortcut is subscribed every time visibility changes, we can take the function from KeyboardShortcutsModal component to Expensify component.

### What alternative solutions did you explore? (Optional)

NA

**Comment by shubham1206agra** [comment] 2023-07-27 07:08
> This is not a bug - [#15413 (comment)](https://github.com/Expensify/App/pull/15413#issuecomment-1442759392)

Oh
Then I think we need to update the language here
https://github.com/Expensify/App/blob/ac74ab9cb25a55e2d042feee24846d5cb7155239/src/languages/en.js#L1350

**Comment by shubham1206agra** [comment] 2023-07-27 07:18
> Yes and also change `openShortcutModalConfig` to for example `toggleShortcutModalConfig`

I think to keep both, don't know when we need them

**Comment by maddylewis** [comment] 2023-07-27 20:06
heya @0xmiroslav - it seems like this isn't technically a bug but a few contributors are suggesting some updates. 

will you take a look at this one and lmk your thoughts - ty! 

https://github.com/Expensify/App/issues/23696#issuecomment-1652995485

**Comment by shubham1206agra** [comment] 2023-07-28 03:19
## Proposal

[Updated](https://github.com/Expensify/App/issues/23696#issuecomment-1652928894)

**Comment by maddylewis** [comment] 2023-07-31 16:57
bump on this comment @0xmiroslav https://github.com/Expensify/App/issues/23696#issuecomment-1654482372

**Comment by maddylewis** [comment] 2023-08-02 21:51
im going to close this out since a couple of contributors have said this isn't a bug / I've not heard back from @0xmiroslav telling us otherwise. 

https://github.com/Expensify/App/issues/23696#issuecomment-1652995485

**Closed by maddylewis** 2023-08-02 21:51 UTC
Labels: External, Daily, Help Wanted, Overdue, Bug
