### ISSUE TITLE
Concierge-Clicking back from concierge page leads to wrong page (Manage my team's expenses)

### ISSUE THREAD

**Issue by izarutskaya** [Expensify/App#37894] opened 2024-03-07 14:20 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Found when validating PR :** https://github.com/Expensify/App/pull/37652

**Version Number:** 1.4.48-0
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Issue reported by:** Applause-Internal team

## Action Performed:
1. Sign up for a new account at staging.new.expensify.com
2. Once you get into your account and see the right-hand modal click on "Manage my team's expenses"
3, Select "No" on the follow up right-hand modal
4. You should get a message from Concierge.
5. After getting the message click on the back button at the top left corner

## Expected Result:
The app should take the user to LHN

## Actual Result:
The app takes user back to the Right hand modal where user already filled out the option "No"

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [x] Android: mWeb Chrome
- [ ] iOS: Native
- [x] iOS: mWeb Safari
- [ ] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

https://github.com/Expensify/App/assets/115492554/77108857-f7d4-49d3-a431-d57280dc7d13

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by izarutskaya** [comment] 2024-03-07 14:23
@kevinksullivan I haven't added the External label as I wasn't 100% sure about this issue. Please take a look and add the label if you agree it's a bug and can be handled by external contributors.

**Comment by bernhardoj** [comment] 2024-03-07 14:44
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
Clicking the back button from concierge page doesn't lead to LHN but instead shows the engagement modal back.

### What is the root cause of that problem?
When we navigate from the engagement modal to the concierge chat, we don't dismiss the modal, so when we press back, the modal is shown instead of the LHN.
https://github.com/Expensify/App/blob/4c1f697c496c7bb587cb18625adfe1548e3e1c6a/src/pages/OnboardEngagement/ManageTeamsExpensesPage.tsx#L58-L62

We dismiss the modal on the first engagement page.
https://github.com/Expensify/App/blob/4c1f697c496c7bb587cb18625adfe1548e3e1c6a/src/pages/OnboardEngagement/PurposeForUsingExpensifyPage.tsx#L85-L90

`navigateToConciergeChat` first param is to dismiss the modal.
### What changes do you think we should make in order to solve the problem?

Pass `true` to `navigateToConciergeChat` to dismiss the modal when going to the concierge chat.

**Comment by kevinksullivan** [comment] 2024-03-15 22:35
checking [here](https://expensify.slack.com/archives/C01SKUP7QR0/p1710542126623139)

**Comment by kevinksullivan** [comment] 2024-03-19 21:44
closing per the convo above

**Closed by kevinksullivan** 2024-03-19 21:44 UTC
Labels: Daily, Overdue, Bug
