### ISSUE TITLE
"You don't have access to this chat" error message appears when closing, then reopening an account

### ISSUE THREAD

**Issue by kavimuru** [Expensify/App#13490] opened 2022-12-09 23:49 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
 1. Create a new account
 2. Create a workspace
 3. Close the account
 4. Re-open same account

##Expected Result:
The re-opened account should show the home page

##Actual Result:
The re-opened account "doesn't have access" to the home page

## Workaround:
unknown

## Platform:

Where is this issue occurring?

- iOS
- Android

**Version Number:** 1.2.37-1
**Reproducible in staging?:** y
**Reproducible in production?:** y
**Email or phone of affected tester (no customers):** 
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** 

https://user-images.githubusercontent.com/43996225/206813172-816eb127-2780-47f4-951b-08c5f09c5024.mp4

**Expensify/Expensify Issue URL:** 
**Issue reported by:** @gadhiyamanan 
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1670575770141179

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

https://user-images.githubusercontent.com/43996225/206813188-ebf61f87-dd44-4d94-ac0b-7cb27aff829b.mp4

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~015e0563825701bf90</li>
        <li>Upwork Job ID: 1602072797425627136
<li>Last Price Increase: 2022-12-19</li></li>
    </ul>
</details>

**Comment by allroundexperts** [comment] 2022-12-12 08:43
### Proposal

The reason for this not working is because of wrong link being sent to the email to set password. Setting password on staging should lead to an email with reset link that corresponds to staging. Instead, we are sending production link for password reset. Thus, when trying to login, we get access denied error.

The fix for this should come from the backend where correct email should be sent.

**Comment by tienifr** [comment] 2022-12-12 10:09
# Proposal

## Problem

In https://github.com/Expensify/App/blob/10dd188fea5793648da7dcf6d113361b35fed866/src/libs/actions/Welcome.js#L55-L66

we inject report to `allReports` when both val and key exist. But when user close account `val` is null so `allReports` is not updated.

In https://github.com/Expensify/App/blob/10dd188fea5793648da7dcf6d113361b35fed866/src/libs/actions/Welcome.js#L115

we find `workspaceChatReport` from `allReports` to display the Workspace chat first. But allReports is stale when user re-logins => workspaceChatReport does not exist

## Solution

Like https://github.com/Expensify/App/blob/10dd188fea5793648da7dcf6d113361b35fed866/src/libs/SidebarUtils.js#L22-L34

we'll check the report is null then remove it from `allReports`

In https://github.com/Expensify/App/blob/main/src/libs/actions/Welcome.js

```diff

const allReports = {};
Onyx.connect({
    key: ONYXKEYS.COLLECTION.REPORT,
    initWithStoredValues: false,
    callback: (val, key) => {
-        if (!val || !key) {
-            return;
-        }
-
-        allReports[key] = {...allReports[key], ...val};

+        if (!val) {
+            delete allReports[key];
+        }else{
+            allReports[key] = {...allReports[key], ...val};
        }
    },
});

const allPolicies = {};
Onyx.connect({
    key: ONYXKEYS.COLLECTION.POLICY,
    callback: (val, key) => {
-        if (!val || !key) {
-            return;
-        }
-
-        allPolicies[key] = val;

+        if (!val) {
+            delete allPolicies[key];
+       }else{
+            allPolicies[key] = val;
    },
});

```

Before:

https://user-images.githubusercontent.com/113963320/207017822-64098f25-1c6f-4057-bcf8-623e4a84080f.mp4


After:

https://user-images.githubusercontent.com/113963320/207017791-8213244d-7327-4093-b9fd-191fb044742f.mp4

**Comment by lordthien** [comment] 2022-12-12 11:42
proposal: 
Because `allReports` is not deleted after `Close accounts`, So I will delete `allReports` like turning off the app.
```diff
index d1130b9450..a1e5904729 100644
--- a/src/libs/actions/Welcome.js
+++ b/src/libs/actions/Welcome.js
@@ -58,10 +58,10 @@ Onyx.connect({
     initWithStoredValues: false,
     callback: (val, key) => {
         if (!val || !key) {
-            return;
+            delete allReports[key];
+        } else {
+            allReports[key] = {...allReports[key], ...val};
         }
-
-        allReports[key] = {...allReports[key], ...val};
     },
 });
```
https://user-images.githubusercontent.com/71846803/207036460-c0b0e161-9b51-4574-bb4e-adce53ee81db.mov

**Comment by marcochavezf** [comment] 2022-12-13 04:38
I'm not able to reproduce this issue in v1.2.38-5 locally in web. I'm going to try again tomorrow on iOS/Android.

**Comment by eVoloshchak** [comment] 2022-12-13 14:18
I was able to reproduce this on Android with the latest sources

All of the proposals include deleting `allReports[ONYXKEYS.COLLECTION.REPORT]`  and `allReports[ONYXKEYS.COLLECTION.POLICIES]`, which seems to be the root cause. 
This indeed happens on logout also, you can log in and out multiple times and the error persists.

I think we should go with @0xmiroslav's proposal since they were the first one to figure out the root cause and the proposal is working correctly. We should make those `if` statements a bit more clear (and not nested), but other than that it looks great to me.

🎀👀🎀 C+ reviewed!
cc: @marcochavezf

**Comment by marcochavezf** [comment] 2022-12-13 22:33
>This happens when navigate to report which id doesn't exist after close account and login (without closing the app)
>This is set here:

Thanks for the proposals guys! But I think the solutions are not fixing the root problem because we're checking [here](https://github.com/Expensify/App/blob/10dd188fea5793648da7dcf6d113361b35fed866/src/libs/actions/Welcome.js#L100) if the user is an `isFirstTimeNewExpensifyUser` which technically should be false. Also for this issue, why are we navigating to an archived workspace chat?

**Comment by priyeshshah11** [comment] 2022-12-14 12:00
> Thanks for the proposals guys! But I think the solutions are not fixing the root problem because we're checking [here](https://github.com/Expensify/App/blob/10dd188fea5793648da7dcf6d113361b35fed866/src/libs/actions/Welcome.js#L100) if the user is an `isFirstTimeNewExpensifyUser` which technically should be false. Also for this issue, why are we navigating to an archived workspace chat?

@marcochavezf In that case, this will need to be fixed by the API right? I don't know what `CloseAccount` API does internally but it should either clear all the data related to the user or if we don't actually do that for other storage purposes and only soft close it then `isFirstTimeNewExpensifyUser` key should be set to false by that API.

**Comment by marcochavezf** [comment] 2022-12-16 02:07
> @marcochavezf In that case, this will need to be fixed by the API right? 

Yeah, we're resetting the value `isFirstTimeNewExpensifyUser` when the account is closed (`null` and defaulting to `true` in the server) when it should be false since it's not a first-time new user. I'm already working on a fix on the server side.

> As I stated in proposal, allReports data is not cleared when close account or logout (stale data of archived or deleted report remaining in this global variable). But Onyx data is cleared.

All the Onyx data is cleared when the account is closed and we retrieve again all the reports after the password is reset (this happens when the command `OpenApp` is called).

**Comment by fedirjh** [comment] 2022-12-16 21:04
> it should be false since it's not a first-time new user

@marcochavezf I think that `isFirstTimeNewExpensifyUser` refer to the first time new user login ( first time login ) and not for the fact that this user has registered before or not.
I think the real issue is that `data` persists in memory for `allReports` and `allPolicies` , so when user logout or close his account all data should be cleared from memory too ( we are not talking about Onyx data here , but global variables ).
in this case I will suggest some changes in conjunction with the lastest Onyx release `^1.0.31`

#### Before
https://user-images.githubusercontent.com/36869046/208157195-60681419-1e31-4258-9666-c6ddfc130f0f.mov

#### After

https://user-images.githubusercontent.com/36869046/208186125-4968fe35-788b-4de8-b1ca-04d9734c7090.mov

#### Changes

Onyx will be updated already in the PR #13600

```diff
diff --git a/package.json b/package.json
index 0cc12944bb..0fc593f963 100644
--- a/package.json
+++ b/package.json
@@ -100,7 +100,7 @@
     "react-native-modal": "^13.0.0",
-    "react-native-onyx": "1.0.29",
+    "react-native-onyx": "^1.0.31",
     "react-native-pdf": "^6.6.2",
```

```diff
diff --git a/src/libs/actions/Welcome.js b/src/libs/actions/Welcome.js
index d1130b9450..407caa3c6a 100644
--- a/src/libs/actions/Welcome.js
+++ b/src/libs/actions/Welcome.js
@@ -52,29 +52,19 @@ Onyx.connect({
     },
 });
 
-const allReports = {};
+let allReports = {};
 Onyx.connect({
     key: ONYXKEYS.COLLECTION.REPORT,
     initWithStoredValues: false,
-    callback: (val, key) => {
-        if (!val || !key) {
-            return;
-        }
-
-        allReports[key] = {...allReports[key], ...val};
-    },
+    waitForCollectionCallback: true,
+    callback: val => allReports = val,
 });
 
-const allPolicies = {};
+let allPolicies = {};
 Onyx.connect({
     key: ONYXKEYS.COLLECTION.POLICY,
-    callback: (val, key) => {
-        if (!val || !key) {
-            return;
-        }
-
-        allPolicies[key] = {...allPolicies[key], ...val};
-    },
+    waitForCollectionCallback: true,
+    callback: val => allPolicies = val,
 });
```

**Comment by fedirjh** [comment] 2022-12-16 21:45
@0xmiroslav what am I supposed to do if I see an improved fix ? the root cause is the same . I have another proposal to refactor the whole component in this  #13672 but need to discuss that with internal team ,
some points to mention :

- `Welcome.show` is always called on `componentDidMount` and that not performance wise , because it always creates connection to onyx and uses memory .
- Another point , the data for `allPolicies` , `allReports` ,`email` and `isFirstTimeNewExpensifyUser' can be obtained directly from the `FloatingActionButtonAndPopover` component
- we should instead conditionally call `Welcome.show` only the first time the user login as suggested on this PR #13672

**Comment by jliexpensify** [comment] 2022-12-18 21:44
Hi @marcochavezf and @eVoloshchak - I'll be out of office until the 4th so re-assigning. Thanks @sakluger !

**Comment by marcochavezf** [comment] 2022-12-19 20:31
>@marcochavezf I think that isFirstTimeNewExpensifyUser refer to the first time new user login ( first time login ) and not for the fact that this user has registered before or not.

@fedirjh ah this value is for the first time a user is logging in to NewDot and used to show Welcome actions in NewDot (like the Welcome message for a created Workspace chat by the user). But the problem is that we're trying to open the workspace chat that was archived because the user closed the account (despite having any data or not in the device). So technically what we want is to avoid showing that action because the user, for some reason, just closed their account (no longer a first-time user).

**Comment by marcochavezf** [comment] 2022-12-19 23:13
Created a PR to fix this on the backend.

**Comment by sakluger** [comment] 2022-12-20 23:04
@marcochavezf should we change this to an internal issue, or are there still any pieces that should be external?

**Comment by marcochavezf** [comment] 2022-12-23 20:25
Yeah, forgot to label it as internal. The corresponding [PR](https://github.com/Expensify/Auth/pull/7343#issuecomment-1363258954) was already deployed. I'm going to test it on NewDot.

**Comment by marcochavezf** [comment] 2022-12-23 20:51
I can't re-open the account because, according to the logs, I'm getting an authorized error: 

```
message: '401 Unauthorized' exceptionMessage: 'Auth ReopenAccount returned an error'
```

I will try again later.

**Comment by sakluger** [comment] 2022-12-27 19:29
@marcochavezf I'm going to create an Upwork job since there are a few people that still need to be paid here, but before I create the post, I wanted to make sure I understand who all needs to be paid and how much.

1. We need to pay @gadhiyamanan the reporting bonus
2. @eVoloshchak should be paid as the C+. It looks like the issue price was automatically changed to $2000 **after** you had already created the PR to fix this, so I think they be paid the default $1000, but let me know if you think this PR review should qualify for a different payment amount.
3. Did your PR use any of the code in any of the proposals in this issue? If so, we should pay out a percentage to the contributors whose code you used.

Also as a heads up to all the contributors here, the PR was deployed 5 days ago, so payment would normally be due in two days (on Dec 29). But given the holidays, I will be out of the office for the next few days and may not be able to hire and pay out until next week. Sorry for the delay, and thanks for your patience on this one!

**Comment by marcochavezf** [comment] 2022-12-28 01:03
Hi @sakluger, 

1. Agree
2. @eVoloshchak helped to review the proposals but the change was in Auth, so only another internal engineer reviewed the PR.
3. Similar to 2, since it was in Auth, the solution didn't use code from some of the proposals.

**Comment by sakluger** [comment] 2023-01-03 16:54
Thanks @marcochavezf, since it was taken internal and no code was used from the proposals, we'll only pay out the reporting bonus for this issue.

@gadhiyamanan I've sent you an offer through Upwork, I'll pay out once you accept.

**Comment by gadhiyamanan** [comment] 2023-01-03 16:55
@sakluger accepted

**Comment by sakluger** [comment] 2023-01-04 23:32
All paid, thanks everyone!

**Closed by sakluger** 2023-01-04 23:32 UTC
Labels: Reviewing, Daily, Internal, Bug

**Comment by gadhiyamanan** [comment] 2023-01-05 02:35
@sakluger can uou please close the upwork contract?

**Comment by gadhiyamanan** [comment] 2023-01-05 17:19
@sakluger please close the upwork contact

**Comment by gadhiyamanan** [comment] 2023-01-09 19:15
> @sakluger please close the [upwork](https://www.upwork.com/nx/wm/workroom/32387969/overview) contact 

bump @sakluger

**Comment by gadhiyamanan** [comment] 2023-01-16 13:38
> @sakluger please close the [upwork](https://www.upwork.com/nx/wm/workroom/32387969/overview) contact 

bump @sakluger

**Comment by gadhiyamanan** [comment] 2023-02-01 18:13
> @sakluger please close the [upwork](https://www.upwork.com/nx/wm/workroom/32387969/overview) contact 

Bump @sakluger
