### ISSUE TITLE
[$500] IOU - Description, merchant, date order changed after creating split bill in group chat.

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#34566] opened 2024-01-16 12:43 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.25-4 
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** Applause - Internal Team
**Slack conversation:**

## Action Performed:
1. Launch app
2. Tap on a group chat
3. Tap plus icon near compose
4. Tap split bill
5. Enter an amount and tap next
6. Tap show more & enter description, merchant
7. Note the order of display of description, merchant and date
8. Tap split
9. Tap the split created to open details page
10.Tap show more
11. Note the order of display changed to description, date and merchant

## Expected Result:
Description, merchant, date order must not be changed after creating split bill in group chat.

## Actual Result:
Description, merchant, date order changed after creating split bill in group chat.

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [x] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

https://github.com/Expensify/App/assets/93399543/5bb3e836-c25a-4f5b-856e-fc010e615528

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01bf7e0226a4739f95</li>
        <li>Upwork Job ID: 1747238369577791488</li>
        <li>Last Price Increase: 2024-01-16</li>
    </ul>
</details>

**Comment by abzokhattab** [comment] 2024-01-16 12:50
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
IOU - Description, merchant, date order changed after creating split bill in group chat. #34566

### What is the root cause of that problem?
 Date is switched with the merchant in this componet: 
https://github.com/Expensify/App/blob/61c7e0bcddac907b50e3600ff651655c5eb8d2e1/src/components/MoneyRequestConfirmationList.js#L666-L685
### What changes do you think we should make in order to solve the problem?


we need to swap the date with the merchant

**Comment by rushatgabhane** [comment] 2024-01-17 05:27
Yes, looks like we created a temporary copy of `MoneyRequestConfirmationList`  to avoid merge conflicts. 
https://github.com/Expensify/App/pull/28618

**Comment by rushatgabhane** [comment] 2024-01-17 05:30
@tgolen im trying to gain clarity here. In https://github.com/Expensify/App/pull/28618 we created a temporary copy of `MoneyRequestConfirmationList`. 

But `MoneyRequestConfirmationList` and `MoneyTemporaryForRefactorRequestConfirmationList` are out of sync now, it is causing this bug.

I'm sure there is a plan to sync them when refactor is done. Could you please let us know if we should hold this issue or proceed with fixing it? Thank you so much 🙇

**Comment by rushatgabhane** [comment] 2024-01-17 05:32
Thank you so much @aimane-chnaif! @lschurr let's close this issue :)

**Comment by lschurr** [comment] 2024-01-18 16:07
Great, thanks!

**Closed by lschurr** 2024-01-18 16:07 UTC
Labels: External, Daily, Help Wanted, Bug
