### ISSUE TITLE
[$250] [Track tax] Send invoice - Tax amount does not update after selecting a tax rate

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#41794] opened 2024-05-07 17:49 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.71-0
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**If this was caught during regression testing, add the test name, ID and link from TestRail:** N/A
**Issue reported by:** Applause - Internal Team

**Issue found when executing PR** https://github.com/Expensify/App/pull/41524
## Action Performed:
Precondition:
- Workspace has enabled taxes
1. Go to staging.new.expensify.com
2. Go to FAB > Send invoice
3. Enter amount and select a user
4. On confirmation page, select the workspace with taxes
5. Send the invoice
6. In invoice chat, click on the invoice preview
7. Click Tax
8. Select a tax rate

## Expected Result:
Tax amount will update after selecting a tax rate

## Actual Result:
Tax amount does not update after selecting a tax rate

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [x] Android: mWeb Chrome
- [x] iOS: Native
- [x] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details> 

https://github.com/Expensify/App/assets/78819774/9c9da408-2857-4b25-830a-65be7eb6d8e7

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01e647d43a762c1223</li>
        <li>Upwork Job ID: 1788212378196783104</li>
        <li>Last Price Increase: 2024-05-08</li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @s77rt</details>

**Comment by lanitochka17** [comment] 2024-05-07 17:50
@joekaufmanexpensify  FYI I haven't added the External label as I wasn't 100% sure about this issue. Please take a look and add the label if you agree it's a bug and can be handled by external contributors

**Comment by joekaufmanexpensify** [comment] 2024-05-08 14:20
Yeah, it's not working for me either. When I select tax rate, we just say I updated the expense, but don't actually add the new tax amount: 

<img width="1511" alt="image" src="https://github.com/Expensify/App/assets/54866469/1f031abd-5f6b-4453-b5c7-552ea53f6cd5">

**Comment by MonilBhavsar** [comment] 2024-05-08 15:03
This issue is already being fixed here https://github.com/Expensify/App/pull/40443

**Comment by joekaufmanexpensify** [comment] 2024-05-08 15:04
Ah sweet. Will close since this is a dupe of that PR and the issue it's linked to. TY!

**Closed by joekaufmanexpensify** 2024-05-08 15:04 UTC
Labels: External, Daily, Help Wanted, Bug
