### ISSUE TITLE
[HOLD for payment 2023-07-26] [$1000] Web - Chat - Inconsistent behaviour while entering emails in chat

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#20085] opened 2023-06-02 18:12 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Login to ND
2. Click on any chat
3. Send [test+1@gmail.com](mailto:test+1@gmail.com)@gmail.com
4. Send [test@gmail.com](mailto:test@gmail.com)@gmail.com

## Expected Result:
The formatting in first message is similar to the 2nd message or vice versa

## Actual Result:
Behaviour is inconsistent

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [x] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 1.3.22.0

**Reproducible in staging?:** yes

**Reproducible in production?:** yes

**If this was caught during regression testing, add the test name, ID and link from TestRail:**

**Email or phone of affected tester (no customers):**

**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Notes/Photos/Videos:** Any additional supporting documentation

![image (51)](https://github.com/Expensify/App/assets/93399543/1d47e79e-ab3d-4db4-bbd9-9dd0b4ed9f68)

https://github.com/Expensify/App/assets/93399543/aaff10b7-59fc-4229-a4bf-2c6091e418bf

**Expensify/Expensify Issue URL:**

**Issue reported by:** @aman-atg 

**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1684776832487869

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01d7534e113b95a39f</li>
        <li>Upwork Job ID: 1667290768145391616</li>
        <li>Last Price Increase: 2023-06-09</li>
    </ul>
</details>

**Comment by alexpensify** [comment] 2023-06-02 20:25
I'll test soon

**Comment by alexpensify** [comment] 2023-06-04 16:11
I'll test tomorrow

**Comment by alexpensify** [comment] 2023-06-06 22:01
@kbecciv - could you please double-check if this is happening on other platforms? 

I tested in Chrome like the GH suggested: 

![image](https://github.com/Expensify/App/assets/8107070/354ed9d5-7ad7-4f8a-a340-9a8aa66810ef)

I noticed that the issue happens in MacOS/Desktop too: 

![image](https://github.com/Expensify/App/assets/8107070/68b20cbf-739e-499e-9196-36d26e1a6287)

Thanks!

**Comment by alexpensify** [comment] 2023-06-11 18:10
Waiting for proposals

**Comment by s-alves10** [comment] 2023-06-12 14:46
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
When sending emails in chat, it is parsed inconsistently.

### What is the root cause of that problem?

Here is the user-mention regex
https://github.com/Expensify/expensify-common/blob/743108fd2428945c5a75baa2a027b5a4ab407b5b/lib/ExpensiMark.js#L111-L120

`test+1@hero@gmail.com` is parsed as user-mention while `test@hero@gmail.com` isn't parsed.

```
    test+1@gmail.com@gmail.com => test+1<user-mention>@gmail.com@gmail.com</user-mention>
    test@gmail.com@gmail.com => test@gmail.com@gmail.com
```

This result is passed to the `autoEmail` rule. `@gmail.com@gmail.com` isn't parsed as email while `test@gmail.com` is parsed as valid email.
That's why the latter is parsed as email, the former is parsed as mention


### What changes do you think we should make in order to solve the problem?

I think both should be parsed as email. In order to do that We need to change the user-mention rule.

```
    {
        name: 'userMentions',
        regex: new RegExp(`((?:(?:\\W)|^)(_?))@${CONST.REG_EXP.EMAIL_PART}(\\2)(?![^<]*(<\\/pre>|<\\/code>|<\\/a>))`, 'gm'),
        replacement: (match, g1, g2, g3, g4) => {
            if (!Str.isValidMention(match)) {
                return match;
            }
            return `${g1}<mention-user>@${g3}</mention-user>${g4}`;
        },
    },
```

This works as expected and passed all existing tests.

The following is the manual test result.
```
    @hero@gmail.com  ===>  <mention-user>@hero@gmail.com</mention-user>
    _@hero@gmail.com  ===>  _@hero@gmail.com
    _@hero@gmail.com_  ===>  _<mention-user>@hero@gmail.com</mention-user>_
    ~@hero@gmail.com  ===>  ~<mention-user>@hero@gmail.com</mention-user>
    ~@hero@gmail.com~  ===>  ~<mention-user>@hero@gmail.com</mention-user>~
    *@hero@gmail.com  ===>  *<mention-user>@hero@gmail.com</mention-user>
    *@hero@gmail.com*  ===>  *<mention-user>@hero@gmail.com</mention-user>*
    test@gmail.com@gmail.com  ===>  test@gmail.com@gmail.com
    test@@gmail.com@gmail.com  ===>  test@<mention-user>@gmail.com@gmail.com</mention-user>
    test+1@gmail.com@gmail.com  ===>  test+1@gmail.com@gmail.com
    test+1@@gmail.com@gmail.com  ===>  test+1@<mention-user>@gmail.com@gmail.com</mention-user>
    test_@gmail.com@gmail.com  ===>  test_@gmail.com@gmail.com
    test_@gmail.com@gmail.com_  ===>  test_@gmail.com@gmail.com_
    test*@gmail.com@gmail.com  ===>  test*<mention-user>@gmail.com@gmail.com</mention-user>
    test*@gmail.com@gmail.com*  ===>  test*<mention-user>@gmail.com@gmail.com</mention-user>*
    test#@gmail.com@gmail.com  ===>  test#<mention-user>@gmail.com@gmail.com</mention-user>
    test"@gmail.com@gmail.com  ===>  test"<mention-user>@gmail.com@gmail.com</mention-user>
    test'@gmail.com@gmail.com  ===>  test'<mention-user>@gmail.com@gmail.com</mention-user>
    @@gmail.com@gmail.com  ===>  @<mention-user>@gmail.com@gmail.com</mention-user>
    _@@gmail.com@gmail.com  ===>  _@<mention-user>@gmail.com@gmail.com</mention-user>
    #@@gmail.com@gmail.com  ===>  #@<mention-user>@gmail.com@gmail.com</mention-user>
    '@@gmail.com@gmail.com  ===>  '@<mention-user>@gmail.com@gmail.com</mention-user>
    @@@@gmail.com@gmail.com  ===>  @@@<mention-user>@gmail.com@gmail.com</mention-user>
```

<details>
    <summary>Result</summary>

https://github.com/Expensify/App/assets/126839717/ea117de7-c5ff-4459-94a6-b06791943d4e

</details>


### What alternative solutions did you explore? (Optional)

**Comment by alexpensify** [comment] 2023-06-13 17:48
@eVoloshchak - when you get a chance, can you review the latest proposal? Thanks!

**Comment by jeet-dhandha** [comment] 2023-06-15 08:44
@eVoloshchak I have a question:
1. What are we expecting this text to be parsed as `email` or `mention` ?
2. Based on what we decide then we need to fix the issue.

It should also be test with below texts:
- `test@here@gmail.com`
- `test+1@here@gmail.com`

**Comment by eVoloshchak** [comment] 2023-06-15 15:54
I think mention should always start with a space/new line, so we should render all of these as emails (same as Github does on this page). 
@tienifr's [proposal](https://github.com/Expensify/App/issues/20085#issuecomment-1574804133) looks good to me
> we should display the texts as emails instead of mentions. It can be achieved by moving the autoEmail rule to before the userMentions and hereMentions rule. This ensures that the email will always be replaced first, then if no email matches then it should be replaced with mentions.

I completely agree with this. We should test with test@here@gmail.com and test+1@here@gmail.com, since, as @jeet-dhandha pointed out those are also rendered incorrectly. @tienifr, we should have a couple of tests to ensure this isn't broken in the future

🎀👀🎀 C+ reviewed!
cc: @yuwenmemon

**Comment by alexpensify** [comment] 2023-06-15 23:21
Thanks for the review @eVoloshchak! Alright, @tienifr it's time to party.

**Comment by alexpensify** [comment] 2023-06-16 19:39
Awesome, thanks @tienifr

**Comment by alexpensify** [comment] 2023-06-18 15:49
Easy melvin, the PR is in review!

**Comment by alexpensify** [comment] 2023-06-20 21:43
Not sure why Melvin didn't add `Reviewing` but I updated this GH to avoid confusion.

**Comment by alexpensify** [comment] 2023-06-22 18:51
Still under review

**Comment by alexpensify** [comment] 2023-06-23 15:55
The PR is waiting on final feedback from @cead22

**Comment by alexpensify** [comment] 2023-06-26 04:01
Ok, PR is moving and automation should run early this week!

**Comment by alexpensify** [comment] 2023-06-27 19:42
Alright, waiting for the automation to kick in. 👏🏼

**Comment by alexpensify** [comment] 2023-06-29 22:24
Reassigning another `bug` team member, I'm going OOO until Monday, July 10, and will take it back then if it's not closed by then. 

Required action from the 🐛 team:  This one might be ready for payment by early next week.

**Comment by greg-schroeder** [comment] 2023-06-30 07:28
PR review continues

**Comment by greg-schroeder** [comment] 2023-07-08 00:31
Last update was yesterday asking for @eVoloshchak to re-review: https://github.com/Expensify/expensify-common/pull/550#issuecomment-1624450806

**Comment by alexpensify** [comment] 2023-07-10 21:10
Alright, removing the other 🐛 team member. I'm back online and see that this is our current state: 

The PR still needs a @eVoloshchak review

**Comment by alexpensify** [comment] 2023-07-12 22:33
PR is moving along!

**Comment by alexpensify** [comment] 2023-07-12 22:33
PR is moving along!

**Comment by eVoloshchak** [comment] 2023-07-13 15:25
[expensify-common](https://github.com/Expensify/expensify-common) PR was merged, only PR to update `expensify-common` version in the App is left

**Comment by alexpensify** [comment] 2023-07-14 18:40
Awesome, looks like the PR is moving along.

**Comment by alexpensify** [comment] 2023-07-16 17:25
PR was approved

**Comment by alexpensify** [comment] 2023-07-18 20:23
Alright, waiting for automation to kick in here.

**Comment by alexpensify** [comment] 2023-07-25 21:16
@eVoloshchak when you get a chance, can you please complete the checklist? 

I'll be working on the payment process tomorrow.

**Comment by eVoloshchak** [comment] 2023-07-26 17:43
- The PR that introduced the bug has been identified. Link to the PR: https://github.com/Expensify/expensify-common/pull/532
- The offending PR has been commented on, pointing out the bug it caused and why, so the author and reviewers can learn from the mistake. Link to comment: https://github.com/Expensify/expensify-common/pull/532/files#r1275295550
- A discussion in #expensify-bugs has been started about whether any other steps should be taken (e.g. updating the PR review checklist) in order to catch this type of bug sooner. Link to discussion: we already have a checklist item precisely for this, I think that and the unit tests are sufficient 
- Determine if we should create a regression test for this bug.
This isn't an impactful bug. We've added automated unit tests in https://github.com/Expensify/expensify-common/pull/550, I don't think manual regression tests are needed

**Comment by alexpensify** [comment] 2023-07-26 21:32
Here is the payment summary: 

-  External issue reporter - @aman-atg $250
-  Contributor that fixed the issue - @tienifr $1000
-  Contributor+ that helped on the issue and/or PR - @eVoloshchak $1000

Upwork Job: 

*_If applicable, the bonuses will be applied on the final payment_

Extra Notes regarding payment: This one was held because of the merge freeze, so I believe there is still a payment here. With that said, there will be no urgency bonus.

**Comment by alexpensify** [comment] 2023-07-26 21:38
I'm having trouble with the Upwork job and will complete the process tomorrow.

**Comment by eVoloshchak** [comment] 2023-07-26 23:47
Requested the payment via NewDot

**Comment by JmillsExpensify** [comment] 2023-07-27 04:04
Reviewed details for @eVoloshchak. This is accurate and approved for payment in NewDot.

**Comment by alexpensify** [comment] 2023-07-27 23:22
@aman-atg and @tienifr - I've sent the payment via Upwork, please accept and I can complete the process. Thanks!

**Comment by alexpensify** [comment] 2023-07-28 20:47
Closing - I've paid @aman-atg and @tienifr via Upwork and I closed the job there too.

**Closed** 2023-07-28 20:47 UTC
Labels: External, Daily, Awaiting Payment, Bug
