### ISSUE TITLE
LHN - Archived rooms have "Mark as unread" option

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#21485] opened 2023-06-24 11:12 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Delete a workspace
2. Look for the archived announce room in LHN
3. Right click on it

## Expected Result:
"Mark as unread" option shouldn't be present since there's no use of it.

## Actual Result:
"Mark as unread" option is present

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [ ] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 1.3.29-0

**Reproducible in staging?:** y

**Reproducible in production?:** y

**If this was caught during regression testing, add the test name, ID and link from TestRail:**

**Email or phone of affected tester (no customers):**

**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Notes/Photos/Videos:** Any additional supporting documentation

![Screenshot 2023-06-17 at 2 48 07 AM](https://github.com/Expensify/App/assets/93399543/5329e9f8-1309-4a5e-bb8c-674ced2a11ee)

https://github.com/Expensify/App/assets/93399543/875da4b5-9aa5-49be-9654-f317c17bee38

**Expensify/Expensify Issue URL:**

**Issue reported by:** https://expensify.slack.com/archives/C049HHMV9SM/p1686950725059539

**Slack conversation:** @Puneet-here

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by ahmedGaber93** [comment] 2023-06-24 11:16
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
LHN - Archived rooms have "Mark as unread" option
### What is the root cause of that problem?

mark as read option `shouldShow` not use !isArchivedRoom on it's condition
### What changes do you think we should make in order to solve the problem?
add `&& !isArchivedRoom` in mark as read option `shouldShow` condition

### What alternative solutions did you explore? (Optional)

**Comment by puneetlath** [comment] 2023-06-24 20:15
I don't think this is a bug. An archived room can still have messages in it, so in theory it can be marked as unread. I'm going to close, but feel free to respond here or in the Slack thread if you'd like to discuss further.

**Closed by puneetlath** 2023-06-24 20:15 UTC
Labels: Daily, Bug
