### ISSUE TITLE
[HOLD for payment 2024-01-25] [HOLD for payment 2024-01-24] Referral - Info icon in Referral banner is black in dark mode

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#34501] opened 2024-01-15 14:51 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.25-1
**Reproducible in staging?:** Y
**Reproducible in production?:** N
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** Applause - Internal Team
**Slack conversation:**

## Action Performed:
1. Go to FAB > Request money > Manual
2. Enter amount > Next

## Expected Result:
The info icon in Referral banner is white in dark mode

## Actual Result:
The info icon in Referral banner is black in dark mode

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [x] Android: mWeb Chrome
- [x] iOS: Native
- [x] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details> 

![Bug6342945_1705327581095!Screenshot_2024-01-15_at_21 02 40](https://github.com/Expensify/App/assets/78819774/67f24c45-0b88-4ac2-8643-d28f9d18df27)

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by bernhardoj** [comment] 2024-01-15 14:58
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
The referral info icon color is black in dark mode.

### What is the root cause of that problem?
This is a regression from https://github.com/Expensify/App/pull/32692/ where we migrate to SelectionList and creating our own referral component but we forget to pass a `fill` props to the icon like we do in BaseOptionsSelector.

https://github.com/Expensify/App/blob/178a339b993dfd46d8465823ad4b9a498c2324ab/src/components/OptionsSelector/BaseOptionsSelector.js#L687-L701

### What changes do you think we should make in order to solve the problem?

Pass the fill props as below
```
fill={theme.icon}
```

**Comment by shubham1206agra** [comment] 2024-01-15 14:58
I believe @lukemorawski is working on this already.
cc @cristipaval

**Comment by brunovjk** [comment] 2024-01-15 15:20
> I believe @lukemorawski is working on this already.

https://github.com/Expensify/App/pull/34443

**Comment by lukemorawski** [comment] 2024-01-15 16:13
@pecanoro I can fix this in couple minutes and post a PR to this issue

**Comment by brunovjk** [comment] 2024-01-15 17:01
@pecanoro My [PR](https://github.com/Expensify/App/pull/32665) will be ready for review today, I have an urgent to complete the [PR](https://github.com/Expensify/App/pull/32665) because there are other blockers that it solves.

But I understand the urgency, the main purpose of my PR is different anyway:  [Issue #31779](https://github.com/Expensify/App/issues/31779),
So perhaps it would be better if @lukemorawski deals with this 'icon style' in a new PR here and I revert the [commit](https://github.com/Expensify/App/pull/32665/commits/6d15a87cc10a4f59e1b474272e563aa5968ba8c8) about it in my PR. 
What do you think @lukemorawski?

**Comment by lukemorawski** [comment] 2024-01-15 17:03
> @pecanoro My [PR](https://github.com/Expensify/App/pull/32665) will be ready for review today, I have an urgent to complete the [PR](https://github.com/Expensify/App/pull/32665) because there are other blockers that it solves.
> 
> But I understand the urgency, the main purpose of my PR is different anyway, So perhaps it would be better if @lukemorawski deals with this 'icon style' in a new PR here and I revert the [commit](https://github.com/Expensify/App/pull/32665/commits/6d15a87cc10a4f59e1b474272e563aa5968ba8c8) about it in my PR. What do you think @lukemorawski?

sure, the less conflicts the better :) My fix icon PR is on it's way. Should be ready in few minutes and posted here https://github.com/Expensify/App/issues/34501

**Comment by brunovjk** [comment] 2024-01-15 17:04
> sure, the less conflicts the better :) My fix icon PR is on it's way. Should be ready in few minutes and posted here #34501

Awesome!

**Comment by lukemorawski** [comment] 2024-01-15 17:17
@pecanoro here's the PR https://github.com/Expensify/App/pull/34517

**Comment by pecanoro** [comment] 2024-01-15 20:24
Fix works, removing deploy blocker label!

**Comment by ikevin127** [comment] 2024-01-15 21:52
Reported [here](https://expensify.enterprise.slack.com/archives/C01GTK53T8Q/p1705068053060889) on Slack, 3 days ago 🚀

**Comment by pecanoro** [comment] 2024-01-29 09:51
@allroundexperts Do you request payment in newdot or do I need to add a BZ member to handle it?

**Comment by allroundexperts** [comment] 2024-01-29 20:57
@pecanoro I request it in ND.

**Comment by pecanoro** [comment] 2024-01-29 21:03
Perfect! Closing this one then

**Comment by JmillsExpensify** [comment] 2024-01-30 19:49
Can I get a payment summary on this issue?

**Comment by trjExpensify** [comment] 2024-01-30 23:25
👋 What's the history of this issue? It was a follow-up PR to fix a regression, so no payment to the PR author. @allroundexperts wasn't the OG C+ reviewer of that PR, so he's eligible for $500 for the C+ review. Is that right? 

P.s - let's always assign a BZ to manage this part.

**Comment by allroundexperts** [comment] 2024-01-30 23:34
> @allroundexperts wasn't the OG C+ reviewer of that PR, so he's eligible for $500 for the C+ review. Is that right?

That's correct!

**Comment by trjExpensify** [comment] 2024-01-30 23:42
Cool, so @JmillsExpensify.. 

@allroundexperts - $500 for the C+ review of this follow-up PR is an accurate payment summary. Proceed!

**Comment by JmillsExpensify** [comment] 2024-01-30 23:42
$500 approved for @allroundexperts based on comment above.

**Closed by JmillsExpensify** 2024-01-30 23:42 UTC
Labels: Engineering, Weekly, Awaiting Payment
