### ISSUE TITLE
[$500] Incorrect calculation of 10000 character limit in composer

### ISSUE THREAD

**Issue by kavimuru** [Expensify/App#28349] opened 2023-09-27 20:13 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Open the app
2. Open any report
3. Type or copy paste message with commas, brackets, single inverted commas, full stop in composer
4. Insert enough words/characters to just trigger 10,000 words limit error
5. Copy the text and insert it into any only character calculator app to calculate number of characters and observe that it will always be way less then 10,000
## Expected Result:
 Leaving emojis, app shouldn't occupy multiple character space for other characters and should provide user with proper 10,000 characters limit in composer
## Actual Result: 
Even for normal text and normal characters, lesser amount of characters triggers 10,000 character limit error

## Workaround:
Can the user still use Expensify without this being fixed? Have you informed them of the workaround?

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [X] Android / native
- [x] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [x] MacOS / Chrome / Safari
- [x] MacOS / Desktop

**Version Number:** 1.3.74-2
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/43996225/a5bcd4a6-c875-4aed-a2e7-7cd30d9a3111

https://github.com/Expensify/App/assets/43996225/175a3d7d-150f-48e1-bbd2-7356e1e5e9d3

https://github.com/Expensify/App/assets/43996225/d76e7fa1-811a-4bf1-adee-e9450964e35f

https://github.com/Expensify/App/assets/43996225/4b1e87c2-0b29-4e44-a3f1-0e1870defb59

https://github.com/Expensify/App/assets/43996225/6495e4da-ccc9-4bc3-a154-20e0218f7a41

https://github.com/Expensify/App/assets/43996225/84bda2a2-698b-4cce-a7ab-4581be76bb32

**Expensify/Expensify Issue URL:**
**Issue reported by:** @dhanashree-sawant
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1695661836654169

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01685204932c0284c2</li>
        <li>Upwork Job ID: 1707126287892926464</li>
        <li>Last Price Increase: 2023-09-27</li>
    </ul>
</details>

**Comment by saranshbalyan-1234** [comment] 2023-09-27 20:53
## Proposal
### Please re-state the problem that we are trying to solve in this issue.
Comment length is different from what we write or paste.
### What is the root cause of that problem?
This is due to this
https://github.com/Expensify/App/blob/f596e350faf8a914f053f1b5abeb469b00b17af1/src/libs/ReportUtils.js#L3132-L3136
We are trimming and some other operations like 
.replace(/[^ -~]/g, '\\u????'): This part of the code is using the replace method with a regular expression to find all characters that are not in the ASCII printable range (characters between space ' ' and tilde '~' in the ASCII table). The regular expression [^ -~] matches any character that is not in this range. However, the replacement value ('\\u????') is incomplete, and the actual Unicode escape sequence is not provided. You need to replace '\\u????' with the proper Unicode escape sequence, like '\\uXXXX', where XXXX should be the hexadecimal representation of the Unicode code point you want to replace it with.
I think this is already correct, if any modifications needed please explain the expected behavior more
### What changes do you think we should make in order to solve the problem?
We can change the above function to
```javascript
function ExceededCommentLength(props) {
    const {numberFormat, translate} = useLocalize();
    const [commentLength, setCommentLength] = useState(0);
    const updateCommentLength = useMemo(
        () =>
            debounce((comment, onExceededMaxCommentLength) => {
                const newCommentLength = comment.length
                setCommentLength(newCommentLength);
                onExceededMaxCommentLength(newCommentLength > CONST.MAX_COMMENT_LENGTH);
            }, CONST.TIMING.COMMENT_LENGTH_DEBOUNCE_TIME),
        [],
    );

``` 
### What alternative solutions did you explore? (Optional)
N/A

**Comment by lcsvcn** [comment] 2023-09-27 21:16
# Proposal
## Please re-state the problem that we are trying to solve in this issue
Comment length is different from what we write or paste.
## What is the root cause of that problem?
This is due to we're converting the comment text to HTML before return length.

## What changes do you think we should make in order to solve the problem?
I suggest to return the length of the text itself.

## What alternative solutions did you explore? (Optional)
N/A

**Comment by cubuspl42** [comment] 2023-10-04 10:50
I'll review the proposals soon

**Comment by cubuspl42** [comment] 2023-10-04 12:45
I opened [an internal discussion on Slack](https://expensify.slack.com/archives/C02NK2DQWUX/p1696423496490989), we might want to do nothing here.

**Comment by cubuspl42** [comment] 2023-10-04 13:52
We agreed in the internal discussion that this behavior is intended, so we'll proceed to close this issue.

As for some reason I'm the only person assigned, I'll still use the marker to assign an internal engineer:

C+ reviewed 🎀 👀 🎀

**Comment by cubuspl42** [comment] 2023-10-04 13:52
@NikkiWines Could you close this issue, as per [this thread](https://expensify.slack.com/archives/C02NK2DQWUX/p1696423496490989)?

**Comment by NikkiWines** [comment] 2023-10-05 02:35
Sounds good! Closing!

**Closed by NikkiWines** 2023-10-05 02:35 UTC
Labels: External, Daily, Help Wanted
