### ISSUE TITLE
[$500] Scan receipts- After admin approves request with error, RD still present in LHN

### ISSUE THREAD

**Issue by izarutskaya** [Expensify/App#38219] opened 2024-03-13 11:52 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.51-0
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**If this was caught during regression testing, add the test name, ID and link from TestRail:** https://expensify.testrail.io/index.php?/tests/view/4418424
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Issue reported by:** Applause-Internal team

## Action Performed:
1. Open the App
2. Start the request money flow &gt; "Scan" receipt
3. Upload a blurry receipt
4. Complete the money request flow
5. While the receipt is scanning - navigate to the request conversation
6. Manually edit the amount field
7. Leave the merchant field empty,so it shows an error to "Enter a merchant"
8. As the admin - Mark the expense as approved

## Expected Result:
The red dot is removed from the report preview, from the LHN conversation and the expense details.

## Actual Result:
After approval, the red dot is still present in the report preview, the LHN conversation and the expense details.

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

https://github.com/Expensify/App/assets/115492554/6940c5d7-c9de-466b-9d2c-bcba752d502c

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01f659429db634ed75</li>
        <li>Upwork Job ID: 1769848374606114816</li>
        <li>Last Price Increase: 2024-03-25</li>
    </ul>
</details>

**Comment by izarutskaya** [comment] 2024-03-13 11:53
@johncschuster I haven't added the External label as I wasn't 100% sure about this issue. Please take a look and add the label if you agree it's a bug and can be handled by external contributors.

**Comment by izarutskaya** [comment] 2024-03-13 11:54
We think that this bug might be related to #wave-collect - Release 1
CC @trjExpensify

**Comment by bernhardoj** [comment] 2024-03-13 13:32
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
The red dot still shows in LHN even after the admin approves the request.

### What is the root cause of that problem?
Currently, we check for any smart scan error in all report actions.
https://github.com/Expensify/App/blob/632b1f8d46bac05d5bc4592215156fa8a5044040/src/libs/OptionsListUtils.ts#L504-L506

We will show the error if there a missing fields and the request is not settled yet, but we never check whether it's approved or not.
https://github.com/Expensify/App/blob/632b1f8d46bac05d5bc4592215156fa8a5044040/src/libs/ReportUtils.ts#L5069

### What changes do you think we should make in order to solve the problem?

Add the approved state check and don't show the error if it's approved.
```
&& !isReportApproved(IOUReportID)
```
We will do the same for report preview.
https://github.com/Expensify/App/blob/632b1f8d46bac05d5bc4592215156fa8a5044040/src/components/ReportActionItem/ReportPreview.tsx#L214

**Comment by trjExpensify** [comment] 2024-03-13 14:29
I _think_ this is more violations related. @JmillsExpensify, did we land on removing the RBR on approval but keeping the error in-line within the expense?

**Comment by nkdengineer** [comment] 2024-03-13 14:31
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
After approval, the red dot is still present in the report preview, the LHN conversation and the expense details.

### What is the root cause of that problem?
We show the error for policy expense chat in LHN if at least one report preview action or split bill action has smart scan error

https://github.com/Expensify/App/blob/fa6bcc0da0554067dc1169a802b28e796dbf1d8d/src/libs/OptionsListUtils.ts#L504-L507

In this function we missed to check the report is approved or not
https://github.com/Expensify/App/blob/fa6bcc0da0554067dc1169a802b28e796dbf1d8d/src/libs/ReportUtils.ts#L5069


### What changes do you think we should make in order to solve the problem?

1. Add the check `!isReportApproved(IOUReportID)` here

https://github.com/Expensify/App/blob/fa6bcc0da0554067dc1169a802b28e796dbf1d8d/src/libs/ReportUtils.ts#L5069

2. After add the check above, with the test steps of the issue, the red dot still appears because the whisper split action that doesn't appear in `ReportScreen` of admin has error after scanning completely and we don't remove this to the list action need to check. 

To fix this case, we should check if the report action is not visible we will return false here

```
 if ((!ReportActionsUtils.isSplitBillAction(action) && !ReportActionsUtils.isReportPreviewAction(action)) || !ReportActionsUtils.shouldReportActionBeVisible(action, key)) {

```
https://github.com/Expensify/App/blob/fa6bcc0da0554067dc1169a802b28e796dbf1d8d/src/libs/ReportUtils.ts#L5065-L5067

3. We should add the check `!isReportApproved(IOUReportID)` in `ReportPreview` and `MoneyRequestPreviewContext` to prevent show the error when it's approved as well.
### What alternative solutions did you explore? (Optional)
NA

**Comment by johncschuster** [comment] 2024-03-14 21:39
Thanks for calling out that this is likely related to #wave-control, @trjExpensify! I've added it to the project tracker and raised it in [Slack](https://expensify.slack.com/archives/C06ML6X0W9L/p1710452307172589). 👍

**Comment by johncschuster** [comment] 2024-03-18 22:10
Not overdue. I've just triaged this one out.

**Comment by JmillsExpensify** [comment] 2024-03-23 19:30
We should close the issue. It's being handled here instead: https://github.com/Expensify/App/issues/34548

**Closed** 2024-03-25 20:38 UTC
Labels: External, Daily, Help Wanted, Bug
