### ISSUE TITLE
[$250] mWeb - BNP - After selecting different currency, for big number next button alignment changes

### ISSUE THREAD

**Issue by IuliiaHerets** [Expensify/App#53992] opened 2024-12-12 07:55 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** V9. 0.75-0
**Reproducible in staging?:** Yes
**Reproducible in production?:** No
**Issue reported by:** Applause Internal Team
**Device used:** Redmi note 10s android 13
**App Component:** Money Requests

## Action Performed:
1. Go to https://staging.new.expensify.com/home
2. Tap fab - create expense
3. Enter big number 8 digits
4. Select a different currency
5. Note the next button alignment

## Expected Result:
After selecting different currency, for big number next button alignment must not change.

## Actual Result:
After selecting different currency, for big number next button alignment changes from middle to left.

## Workaround:
Unknown

## Platforms:
- [ ] Android: Standalone
- [ ] Android: HybridApp
- [x] Android: mWeb Chrome
- [ ] iOS: Standalone
- [ ] iOS: HybridApp
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

https://github.com/user-attachments/assets/ba7d7bb1-45ba-42d9-ab4a-1fe0f8a10376

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)
<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~021867194147621109596</li>
        <li>Upwork Job ID: 1867194147621109596</li>
        <li>Last Price Increase: 2024-12-12</li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @rojiphil</details>

**Comment by IuliiaHerets** [comment] 2024-12-12 07:56
Production behavior 

https://github.com/user-attachments/assets/ab4dc386-fded-49a3-bcff-0b6ecce84459

**Comment by NikkiWines** [comment] 2024-12-12 12:44
I'm unable to reproduce this on staging or production - demoting this from a blocker and the needs repro label.

https://github.com/user-attachments/assets/30e1de7a-b79c-45c8-9453-47980971ebf9


https://github.com/user-attachments/assets/95ac1be8-a074-443a-99bc-2b3e339bfc3e

**Comment by allroundexperts** [comment] 2024-12-12 12:49
@allgandalf I already posted on Slack 😄

**Comment by allroundexperts** [comment] 2024-12-12 12:52
This is easily reproducible. Here are the steps:

1. In android chrome, open https://staging.new.expensify.com
2. Click on the Fab, then click on `Create Expense`
3. Enter an amount like `22222222`
4. Click next, and enter a recipient email like: `aaaaaaaaaa@aaaaa.com`
5. Click next, and on the review screen, click on the amount again.

It can be easily seen that the `Next` button is misaligned.

https://github.com/user-attachments/assets/bb4a1c3f-7761-4403-82be-617a5dc552a0

**Comment by NikkiWines** [comment] 2024-12-12 12:58
Cool 👍 Re-applying appropriate labels then - not sure why I don't see the UI issue (even following those updated steps, thanks @allroundexperts) but happy to have this one investigated.

**Comment by rojiphil** [comment] 2024-12-12 14:15
Unassigning myself as @allroundexperts is taking this over

**Comment by Unique-Programmer** [comment] 2024-12-12 19:08
Hi, could you please help me, should I post what I think is the correct solution here in the comments?

**Comment by Unique-Programmer** [comment] 2024-12-12 19:25
Contributor details
Your Expensify account email: vitalyberyoza@gmail.com
Upwork Profile Link: https://www.upwork.com/freelancers/~01588b7de4d2e62c93

**Comment by luacmartins** [comment] 2024-12-12 19:32
Caused by https://github.com/Expensify/App/pull/53740

**Comment by luacmartins** [comment] 2024-12-12 19:46
Revert merged and being Cped

**Comment by luacmartins** [comment] 2024-12-12 22:46
Fixed in staging

**Closed by luacmartins** 2024-12-12 22:46 UTC
Labels: External, Engineering, Hourly, Help Wanted, Bug
