### ISSUE TITLE
[HOLD for payment 2022-08-01] [$250] Android -  When user tapped on the eye icon in password field the keyboard changes @Puneet-here

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#9444] opened 2022-06-14 13:18 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Sign out > Enter Email > Continue
2. Focus on password field
3. Check the keyboard it has a numbers row at the top.
4. Now tap on the eye, the keyboard will change and you won't see the number row.

## Expected Result:
The keyboard shouldn't change, it should have the number row.

## Actual Result:
 The keyboard changes.

## Workaround:
Unknown

## Platform:

Where is this issue occurring?

- Android

**Version Number:** 1.1.76.2

**Reproducible in staging?:** Yes

**Reproducible in production?:** Yes

**Email or phone of affected tester (no customers):** 

**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Notes/Photos/Videos:** Any additional supporting documentation

https://user-images.githubusercontent.com/93399543/173586659-f0fcdfa5-abc3-4ef2-bece-35d815f372c6.mp4

**Expensify/Expensify Issue URL:** 

**Issue reported by:** @Puneet-here

**Slack conversation:** https://expensify.slack.com/archives/C01GTK53T8Q/p1652896569021399

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by conorpendergrast** [comment] 2022-06-15 02:10
Checking for [volunteers to triage](https://expensify.slack.com/archives/C03U7DCU4/p1655259023973889), as I do not have an Android device

**Comment by conorpendergrast** [comment] 2022-06-16 22:37
@cristipaval was [able to reproduce it](https://expensify.slack.com/archives/C03U7DCU4/p1655372678656419?thread_ts=1655259023.973889&cid=C03U7DCU4)! Thanks so much!

**Comment by b1tjoy** [comment] 2022-06-19 16:00
### PROPOSAL
### Problem
This issue can be reproduced on virtual device. When we tap on the eye, the keyboard suggestions show.

The `secureTextEntry` props of `TextInput` is `true` in `PasswordForm` component, `inputType` will [set to InputType.TYPE_TEXT_VARIATION_PASSWORD](https://github.com/facebook/react-native/blob/1b31d6bb582768ccbe92d3c1a9e43354a8c531e5/ReactAndroid/src/main/java/com/facebook/react/views/textinput/ReactTextInputManager.java#L774) on native side.

When we tap on the eye, the `secureTextEntry` props of `TextInput` change to `false`, and `inputType` [unset with InputType.TYPE_TEXT_VARIATION_PASSWORD](https://github.com/facebook/react-native/blob/1b31d6bb582768ccbe92d3c1a9e43354a8c531e5/ReactAndroid/src/main/java/com/facebook/react/views/textinput/ReactTextInputManager.java#L773) on native side. It means keyboardType change to default.

### Solution
When we change `secureTextEntry` to `false`, also set `keyboardType` props of `TextInput` to `visible-password`. Since this value works on Android only, we need to do some modification.

1.Copy [src/components/TextInput/index.native.js](https://github.com/Expensify/App/blob/5b0cd481c87e89772f7d21fdbad6bf815b495b15/src/components/TextInput/index.native.js) to src/components/TextInput/index.ios.js, keep iOS unchanged.

2.Add `getKeyboardType` props to `BaseTextInput` in [src/components/TextInput/index.native.js](https://github.com/Expensify/App/blob/5b0cd481c87e89772f7d21fdbad6bf815b495b15/src/components/TextInput/index.native.js)
https://github.com/Expensify/App/blob/5b0cd481c87e89772f7d21fdbad6bf815b495b15/src/components/TextInput/index.native.js#L7-L15
```JSX
+ getKeyboardType={(passwordHidden) => props.secureTextEntry && !passwordHidden ? 'visible-password' : props.keyboardType}
```

3.Rename [src/components/TextInput/index.native.js](https://github.com/Expensify/App/blob/5b0cd481c87e89772f7d21fdbad6bf815b495b15/src/components/TextInput/index.native.js) to src/components/TextInput/index.android.js, so the changes only apply to Android.

4.Add `keyboardType` to [src/components/TextInput/BaseTextInput.js](https://github.com/Expensify/App/blob/5b0cd481c87e89772f7d21fdbad6bf815b495b15/src/components/TextInput/BaseTextInput.js).
https://github.com/Expensify/App/blob/5b0cd481c87e89772f7d21fdbad6bf815b495b15/src/components/TextInput/BaseTextInput.js#L195-L201
```JSX
+ const keyboardType = this.props.getKeyboardType ? this.props.getKeyboardType(this.state.passwordHidden) : this.props.keyboardType;
```
https://github.com/Expensify/App/blob/5b0cd481c87e89772f7d21fdbad6bf815b495b15/src/components/TextInput/BaseTextInput.js#L272-L274
```JSX
+ keyboardType={keyboardType}
```

5.When we tap on the eye, the keyboard will automatically capitalize, we don't want that, set `autoCapitalize` to `none` in `PasswordForm` to fix it.
https://github.com/Expensify/App/blob/5b0cd481c87e89772f7d21fdbad6bf815b495b15/src/pages/signin/PasswordForm.js#L139
```JSX
+ autoCapitalize="none"
```

**Comment by tgolen** [comment] 2022-06-20 19:14
I got confirmation from @parasharrajat that it is OK to work on this one due to some of the confusing status of your other issues.

The proposal above looks OK to me 👍

**Comment by tgolen** [comment] 2022-06-22 20:06
@stephanieelliott I think the next step here is to hire them in Upwork?

**Comment by stephanieelliott** [comment] 2022-06-23 16:30
Sorry for the wait, I've been out at a conference! 

Upwork job is here: https://www.upwork.com/jobs/~01e107e5f916abe7ab

@b1tjoy please apply for the job in Upwork

**Comment by mananjadhav** [comment] 2022-06-25 16:15
Looks like I got assigned after the proposal was accepted. Will be reviewing the PR.

**Comment by mananjadhav** [comment] 2022-06-28 07:59
@b1tjoy Do you have any updates for me on this one?

**Comment by b1tjoy** [comment] 2022-06-28 09:10
@mananjadhav I will post pull request soon, in less than 12 hours.

**Comment by stephanieelliott** [comment] 2022-06-30 00:19
Hey @mananjadhav and @b1tjoy can you grab the job on Upwork when you get a chance? https://www.upwork.com/jobs/~01e107e5f916abe7ab

**Comment by stephanieelliott** [comment] 2022-07-11 17:57
PR submitted, this is just waiting on internal and C+ review!

**Comment by stephanieelliott** [comment] 2022-07-13 15:52
Reassigning this one as I am going OOO, thanks @kadiealexander!

**Comment by b1tjoy** [comment] 2022-07-19 00:26
The PR https://github.com/Expensify/App/pull/9593 has been successfully merged.

My upwork proposal status was **declined by client**, should I do anything about it?

**Comment by kadiealexander** [comment] 2022-07-19 00:37
@b1tjoy could you please link your Upwork profile here so I can take a look at your Upwork proposal and see what happened?

**Comment by b1tjoy** [comment] 2022-07-19 04:33
@kadiealexander Thank you! My upwork profile https://www.upwork.com/freelancers/~015f3ce165fe53a62f

**Comment by kadiealexander** [comment] 2022-07-25 04:28
Thanks @b1tjoy! I'm not sure what happened there sorry! I've created a new job post just for this here https://www.upwork.com/jobs/~01e1db0a026ba15120 and sent you a hire request.

**Comment by kadiealexander** [comment] 2022-08-03 05:45
Everyone is paid! Thanks team!

**Closed by kadiealexander** 2022-08-03 05:45 UTC
Labels: Exported, External, Engineering, Daily, Improvement, Awaiting Payment
