### ISSUE TITLE
[$250] Chat - Unread message indicator not displayed after flagging message as offensive

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#39170] opened 2024-03-28 12:06 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** v1.4.57-2
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:** https://expensify.testrail.io/index.php?/tests/view/4459671
**Issue reported by:** Applause - Internal Team

## Action Performed:
Pre-requisite: the user must be logged in.
1. Verify you have a chat where the latest messages are not from you.
2. Go to LHN and long press on the chat and mark it as unread.
3. Open the chat and verify that the unread indicator appears on the latest message from the other participant.
4. Long press on the message and flag it as offensive (any option).
5. Send a message.
5. Return to LHN and long press on the chat and mark it as unread.
6. Open the chat.
7. Verify no unread message indicator is displayed.

## Expected Result:
Unread message indicator should be displayed on the latest message from the other participant.

## Actual Result:
There is no unread message indicator on the chat after flagging as offensive.

## Workaround:
n/a

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [x] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

https://github.com/Expensify/App/assets/93399543/93b33146-3f16-4ca2-8db9-b17ca4dc6f9a

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01103e15827eecbf8f</li>
        <li>Upwork Job ID: 1773462943050678272</li>
        <li>Last Price Increase: 2024-03-28</li>
<li>Automatic offers: </li>
<ul>
<li>akinwale | Reviewer | 0</li>
<li>bernhardoj | Contributor | 0</li>
</ul></li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @akinwale</details>

**Comment by kbecciv** [comment] 2024-03-28 12:06
@bfitzexpensify I haven't added the External label as I wasn't 100% sure about this issue. Please take a look and add the label if you agree it's a bug and can be handled by external contributors

**Comment by kbecciv** [comment] 2024-03-28 12:07
We think that this bug might be related to #vip-vsb

**Comment by bernhardoj** [comment] 2024-03-28 16:24
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
Mark us unread do nothing when the last action/message is a flagging whisper.

### What is the root cause of that problem?
When we mark as unread, we find the latest action that is not coming from the current user and take its `created` data.
https://github.com/Expensify/App/blob/58abe8950e291e71e15506385b16d0443d6ce41c/src/libs/actions/Report.ts#L1005-L1013

In our case, it takes the whisper `created` data and subtracts 1 ms from it, and sets it as the new `lastReadTime`.
https://github.com/Expensify/App/blob/58abe8950e291e71e15506385b16d0443d6ce41c/src/libs/actions/Report.ts#L1018

Then, to decide whether it's unread or not, it checks whether the `lastReadTime` is smaller than `lastVisibleActionCreated`.
https://github.com/Expensify/App/blob/58abe8950e291e71e15506385b16d0443d6ce41c/src/libs/ReportUtils.ts#L4161

You may expect that `lastVisibleActionCreated` value is the flagging whisper `created` value, however, that's not the case. Looks like `lastVisibleActionCreated` doesn't consider a whisper message, with the exception of `ACTIONABLEMENTIONWHISPER`. So, the `lastVisibleActionCreated` contains the message `created` that we flag thus the condition is always false.

### What changes do you think we should make in order to solve the problem?

If it's expected that `lastVisibleActionCreated` doesn't consider some whisper action, then we can ignore a whisper action when searching for the latest action from another user.
https://github.com/Expensify/App/blob/58abe8950e291e71e15506385b16d0443d6ce41c/src/libs/actions/Report.ts#L1005-L1010

(FYI, another example where a whisper message created value isn't included in `lastVisibleActionCreated` is a scan  money request)

```
if (current.actorAccountID !== currentUserAccountID && (!latest || current.created > latest.created) && (current.actionName !== 'ACTIONABLEMENTIONWHISPER' && !ReportActionsUtils.isWhisperAction(current))) {
    return current;
}
```

_this is assuming ACTIONABLEMENTIONWHISPER is the only whisper that is considered in lastVisibleActionCreated value_

### What alternative solutions did you explore? (Optional)
If `lastVisibleActionCreated` need to always include whisper action `created`, then we need to update the BE and FE optimistic value on some action.

**Comment by bfitzexpensify** [comment] 2024-04-01 21:26
How does @bernhardoj's proposal look @akinwale?

**Comment by akinwale** [comment] 2024-04-03 07:38
@bernhardoj's [proposal](https://github.com/Expensify/App/issues/39170#issuecomment-2025619834) makes sense here. The caveat is that `ACTIONABLEMENTIONWHISPER` is the only whisper that will be considered when checking the `lastVisibleActionCreated` value.

🎀👀🎀 C+ reviewed.

**Comment by Julesssss** [comment] 2024-04-03 09:40
Lets go with this solution for now. We have a lot of Action types in the backend and it's unrealistic to figure out all possible trigger types any time soon.

**Comment by bernhardoj** [comment] 2024-04-03 10:37
PR is ready

cc: @akinwale

**Comment by Julesssss** [comment] 2024-04-11 16:58
Review in progress

**Comment by akinwale** [comment] 2024-05-01 06:10
@bfitzexpensify Automation missed this. The PR was deployed to production on [2024-04-22](https://github.com/Expensify/App/pull/39482#issuecomment-2069771440) which makes the payment due date 2024-04-29.

Thanks.

**Comment by bfitzexpensify** [comment] 2024-05-01 13:33
Thanks for the bump @akinwale. Payments complete. Adding a manual BZ checklist, please complete this when you get a moment. 

**BugZero Checklist:** The PR fixing this issue has been merged! The following checklist ([instructions](https://stackoverflow.com/c/expensify/questions/14574)) will need to be completed before the issue can be closed:

- [ ] [@akinwale] The PR that introduced the bug has been identified. Link to the PR:
- [ ] [@akinwale] The offending PR has been commented on, pointing out the bug it caused and why, so the author and reviewers can learn from the mistake. Link to comment:
- [ ] [@akinwale] A discussion in #expensify-bugs has been started about whether any other steps should be taken (e.g. updating the PR review checklist) in order to catch this type of bug sooner. Link to discussion:
- [ ] [@akinwale] Determine if we should create a regression test for this bug.
- [ ] [@akinwale] If we decide to create a regression test for the bug, please propose the [regression test](https://github.com/Expensify/App/blob/main/contributingGuides/REGRESSION_TEST_BEST_PRACTICES.md) steps to ensure the same bug will not reach production again.
- [ ] [@bfitzexpensify] Link the GH issue for creating/updating the regression test once above steps have been agreed upon:

**Comment by bfitzexpensify** [comment] 2024-05-04 14:00
Bump on the checklist @akinwale - thank you.

**Comment by Julesssss** [comment] 2024-05-17 08:43
@bfitzexpensify this is good to go I think

**Closed** 2024-05-17 12:55 UTC
Labels: Reviewing, External, Daily, Bug
