### ISSUE TITLE
 Chat - Original message appears after editing in offline mode and relaunch the app

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#31749] opened 2023-11-22 20:52 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.2-0
**Reproducible in staging?:** Y
**Reproducible in production?:** N
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** Applause - Internal Team
**Slack conversation:**

## Action Performed:
Pre-requisite: user must be logged in
1. Go to any chat and send a message
2. Disable internet connection
3. Edit the recently sent message
4. Edit it again to something new
5.  Force-kill and relaunch the app
6. Enable internet connection
7. Open New Expensify app again and go to chat

## Expected Result:
The message should be displayed as last edit

## Actual Result:
Original message appears

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [x] Android: mWeb Chrome
- [x] iOS: Native
- [x] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details> 

https://github.com/Expensify/App/assets/78819774/6522cd66-4f17-4d50-83be-1a3c116bb628

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by lanitochka17** [comment] 2023-11-22 20:55
Production:

https://github.com/Expensify/App/assets/78819774/ac35351a-84f3-4aff-b44d-d8da86e709c3

**Comment by luacmartins** [comment] 2023-11-22 21:35
I have a feeling that this was caused by https://github.com/Expensify/App/pull/30425 which was reverted and CPed

**Comment by luacmartins** [comment] 2023-11-22 21:35
Testing in staging now

**Comment by luacmartins** [comment] 2023-11-22 21:39
yea, can't repro in latests staging anymore. Gonna close this issue.

**Closed** 2023-11-22 21:39 UTC
Labels: Engineering, Hourly
