### ISSUE TITLE
[$500] Distance - Clicking on Use current location when suggestion list is open does not trigger action

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#29015] opened 2023-10-06 16:24 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___
**Issue found when executing PR** https://github.com/Expensify/App/pull/26546
## Action Performed:
1. Go to https://staging.new.expensify.com/
2. Go to + > Request money > Distance
3. Click Start
4. Enter any address so that the suggestion list shows up
5. Click on Use current location

## Expected Result:
Since the cursor displays as a hand when hovering over 'Use current location', clicking on it should trigger the app to detect user's current location

## Actual Result:
Clicking on 'Use current location' does not trigger the intended action of the button when the suggestion list is open.
On Android, it works without issue when the suggestion list is open

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [x] Android / Chrome
- [x] Windows / Chrome
- [x] iOS / Safari
- [x] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 1.3.79-3

**Reproducible in staging?:** Yes

**Reproducible in production?:** No

**If this was caught during regression testing, add the test name, ID and link from TestRail:**

**Email or phone of affected tester (no customers):**

**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/78819774/94af9cc5-8927-4d84-b84b-7ec8346101f2

**Expensify/Expensify Issue URL:**

**Issue reported by:** Applause - Internal Team

**Slack conversation:**

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01cd6068abd5a84d8a</li>
        <li>Upwork Job ID: 1710364184113389568</li>
        <li>Last Price Increase: 2023-10-13</li>
    </ul>
</details>

**Comment by deetergp** [comment] 2023-10-06 18:39
@lanitochka17 You can't say that clicking on "Use current location" works in production if that link does not exist on production. Not a deploy blocker, but I agree that clicking on the link should work as intended, rather than simply trigger hiding the list when clicking outside it.

**Comment by hayata-suenaga** [comment] 2023-10-09 01:17
@huzaifa-99 doesn't clicking the "Use current lcoation" button both make the input loose focus and the onPress callback to be invoked?

**Comment by paultsimura** [comment] 2023-10-09 04:06
> @huzaifa-99 doesn't clicking the "Use current lcoation" button both make the input loose focus and the onPress callback to be invoked?

@hayata-suenaga the RCA here is that the "Use current location" button is located below the expanding suggestion lost. So when we click on it:
1. The list hides
2. "Press" event is executed

However, after the list hides, the button changes its location, and the press event clicks an empty space. You can prove it by, for example, simply changing the position of this button to above the waypoint search field.

I couldn't find a solid solution for now, so I'm just posting my findings to help someone make a valid proposal.

**Comment by hayata-suenaga** [comment] 2023-10-10 02:11
> but the button doesn't get the click when the list changes position

ah this is tricky...

**Comment by jliexpensify** [comment] 2023-10-17 00:29
Ok great, looks like @jjcoffee gave the thumbs up so closing it out.

**Closed by jliexpensify** 2023-10-17 00:29 UTC
Labels: External, Engineering, Weekly, Help Wanted, Overdue, Bug
