### ISSUE TITLE
[$500] iOS - RHP- Keyboard persist when user opened chat and navigated on Profile via QR Code or share link

### ISSUE THREAD

**Issue by izarutskaya** [Expensify/App#36003] opened 2024-02-07 10:42 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.37-7
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** Applause-Internal Team
**Slack conversation:**

## Action Performed:
1. Open app
2. Navigate to any chat
3. Tap on the compose box
4. Open camera app
5. Scan the Profile QR code of different user

## Expected Result:
Profile page should be properly displayed

## Actual Result:
Keyboard persist when user opened the chat and then navigated on profile page

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [x] iOS: Native
- [ ] iOS: mWeb Safari
- [ ] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

https://github.com/Expensify/App/assets/115492554/fc7f867f-b227-431f-9609-42fb706efac8

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01f5e97312ab13244c</li>
        <li>Upwork Job ID: 1755180155710287872</li>
        <li>Last Price Increase: 2024-02-14</li>
<li>Automatic offers: </li>
<ul>
<li>situchan | Contributor | 0</li>
<li>akinwale | Contributor | 0</li>
</ul></li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @situchan</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @situchan</details>

**Comment by akinwale** [comment] 2024-02-07 12:57
## Proposal
[Updated](https://github.com/Expensify/App/issues/36003#issuecomment-1931988484)

**Comment by akinwale** [comment] 2024-02-13 14:32
@thesahindia Did you get a chance to review my [proposal](https://github.com/Expensify/App/issues/36003#issuecomment-1931988484) yet?

**Comment by anmurali** [comment] 2024-02-13 23:31
@thesahindia - bump on the above.

**Comment by anmurali** [comment] 2024-02-16 15:18
Rotated the label since I will be OOO till 29th! I can take it back when I return!
But that will also get us a new C+ here

**Comment by anmurali** [comment] 2024-02-16 15:20
@mallenexpensify rotating bug and help wanted didn't assign a new C+. You will need to ask manually in the C+ slack channel and get this assigned! Thank you.

**Comment by situchan** [comment] 2024-02-18 15:12
I am interested in reviewing this. I can also install app on physical iPhone.

**Comment by mallenexpensify** [comment] 2024-02-18 20:55
Assigned to @situchan , please review the proposal above, thx

**Comment by akinwale** [comment] 2024-02-18 23:18
@situchan Just to note here, this is also reproducible without having to use a physical device. Quoting from my proposal:

> The issue is also reproducible by trying to open the URI scheme of a user profile when their corresponding chat report is the current active window. The command to do this with an example profile is: `npx uri-scheme open new-expensify://a/16292980 --ios`

**Comment by situchan** [comment] 2024-02-19 04:57
Thanks. `xcrun simctl openurl booted 'new-expensify://a/16292980'` also works


https://github.com/Expensify/App/assets/108292595/d89d1203-908a-4fd9-aa5e-0f03bdcdf17a

**Comment by akinwale** [comment] 2024-02-20 21:26
@situchan My [PR](https://github.com/Expensify/App/pull/36953) is ready for review. Thanks.

**Comment by situchan** [comment] 2024-03-06 16:39
PR was deployed to production on Feb 28

**Comment by mallenexpensify** [comment] 2024-03-10 21:28
@situchan, we want a regression test for this, right?  Below is the checklist, it didn't auto-populate for some reason. 

BugZero Checklist: The PR fixing this issue has been merged! The following checklist ([instructions](https://stackoverflow.com/c/expensify/questions/14574)) will need to be completed before the issue can be closed:

- [ ] The PR that introduced the bug has been identified. Link to the PR:
- [ ] The offending PR has been commented on, pointing out the bug it caused and why, so the author and reviewers can learn from the mistake. Link to comment:
- [ ] A discussion in #expensify-bugs has been started about whether any other steps should be taken (e.g. updating the PR review checklist) in order to catch this type of bug sooner. Link to discussion:
- [ ] If we decide to create a regression test for the bug, please propose the [regression test](https://github.com/Expensify/App/blob/main/contributingGuides/REGRESSION_TEST_BEST_PRACTICES.md) steps to ensure the same bug will not reach production again.
- [ ] Link the GH issue for creating/updating the regression test once above steps have been agreed upon:
- [ ]

**Comment by mallenexpensify** [comment] 2024-03-10 21:30
Contributor: @akinwale paid $500 via Upwork
Contributor+: @situchan paid $500 via Upwork

**Comment by situchan** [comment] 2024-03-15 10:50
I haven't found any culprit PR. I think this bug existed for long time and just not caught as unusual case.
This was caught by QA team so I don't think new regression test is needed here.

**Comment by mallenexpensify** [comment] 2024-03-15 21:34
@situchan , most bugs are created by QA/Applause and most end up with new or updated regression tests.  
Unless you're 100% sure we don't need one, it's best practice to err on the side of creating one because QA can easily close if it' not needed. Created one for this issue. 
- https://github.com/Expensify/Expensify/issues/379526

Thx

**Closed by mallenexpensify** 2024-03-15 21:34 UTC
Labels: External, Daily, Bug
