### ISSUE TITLE
[HOLD for payment 2023-07-17] [$1000] mWeb -  Emoji modal stops working in the chat if the user opens it in the IOU report.

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#21101] opened 2023-06-20 10:46 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Opened mWeb.
2. Navigated to the chat.
3. Sent money and accessed the IOU report page.
4. Opened the emoji modal
5.  Click Back to return to the chat.
6. Tried opening the emoji box.

## Expected Result:
 The emoji modal should open in the chat compose box.

## Actual Result:
The emoji modal doesn't open in the chat compose box.

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [x] iOS / Safari
- [ ] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 1.3.29.3

**Reproducible in staging?:** y

**Reproducible in production?:**y

**If this was caught during regression testing, add the test name, ID and link from TestRail:**

**Email or phone of affected tester (no customers):**

**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/93399543/b49ebfe7-bd8d-4183-95e7-d79a040fcb31

https://github.com/Expensify/App/assets/93399543/6b081e2d-30b0-4383-b59c-913a77dfc27c

**Expensify/Expensify Issue URL:**

**Issue reported by:** @Tushu17

**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1686644077744109

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01f59b5426989a9373</li>
        <li>Upwork Job ID: 1673469119557054464</li>
        <li>Last Price Increase: 2023-07-03</li>
    </ul>
</details>

**Comment by bernhardoj** [comment] 2023-06-20 14:25
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
Emoji picker won't open after going back from a child chat.

### What is the root cause of that problem?
This has the same root cause with https://github.com/Expensify/App/issues/20513 and https://github.com/Expensify/App/issues/20847. Emoji picker uses a global ref defined in EmojiPickerAction
https://github.com/Expensify/App/blob/e6c2704eb43d4d31a55eff5d5d1b3e89c5292bc3/src/libs/actions/EmojiPickerAction.js#L3

The ref will be set when ReportScreen is mounted and will be set to null once ReportScreen is unmounted. In our case, the second chat is unmounted which will set the global ref to null.
 
1. Open first chat
ref: picker 1
2. Open second chat
ref: picker 2
3. Close second chat, report screen is unmounted
ref: null

### What changes do you think we should make in order to solve the problem?

Use local ref instead. Define the ref in ReportScreen and pass it down with Context. We planned to create a ReportScreenContext here https://github.com/Expensify/App/issues/20847 that holds all the ref(s), so we can just wait for it first and then use it for emoji picker ref too.

Every component that uses the global emoji picker ref will now use the emoji picker ref from ReportScreenContext

**Comment by alexpensify** [comment] 2023-06-22 18:58
This is on my test list

**Comment by payal-lathidadiya** [comment] 2023-06-23 14:32
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
Emoji modal stops working in the chat if the user opens it in the IOU report

### What is the root cause of that problem?
`emojiPickerRef` is created as global ref instance [here](https://github.com/Expensify/App/blob/e6c2704eb43d4d31a55eff5d5d1b3e89c5292bc3/src/libs/actions/EmojiPickerAction.js#L3)

This ref will be set when ReportScreen is mounted and will be set to null once ReportScreen is unmounted. In our case, the second chat is unmounted which will set the global ref to null.

### What changes do you think we should make in order to solve the problem?
We can move `EmojiPicker` component from `ReportScreen` [here](https://github.com/Expensify/App/blob/main/src/pages/home/ReportScreen.js#L351) to `App` [here](https://github.com/Expensify/App/blob/main/src/App.js#L58) or `Expensify` component [here](https://github.com/Expensify/App/blob/main/src/Expensify.js#L214), so that it won't loose state while re-rendering of report component.

### What alternative solutions did you explore? (Optional)
None

**Comment by alexpensify** [comment] 2023-06-24 17:00
I'm catching up from my half day, I'll review soon.

**Comment by alexpensify** [comment] 2023-06-26 23:12
I've confirmed this is an issue and don't believe there is another GH related to it. 

![image](https://github.com/Expensify/App/assets/8107070/a7f772d7-ec29-431a-8c46-0f760f595bd2)

**Comment by alexpensify** [comment] 2023-06-28 23:14
Still waiting for proposals here.

**Comment by alexpensify** [comment] 2023-06-29 22:22
Reassigning another `bug` team member, I'm going OOO until Monday, July 10, and will take it back then if it's not closed by then. 

Required action from the 🐛 team: Make sure the proposal process is moving forward, so we can get this one assigned out to fix. If no movement on the proposals by next week, then we may want to consider shopping for a reviewer.

**Comment by payal-lathidadiya** [comment] 2023-06-30 10:51
> Do you think it'll cause performance regressions? Does the entire app re-render when emoji drawer is reopened?

@rushatgabhane thanks for reviewing my proposal.

As investigated and tested, i didn't observe or notice any performance regressions with proposed update. And it won't impact app to cause re-render when emoji drawer is reopened.

In fact, I think this would be more optimised way of handling emoji picker instance global ref here, IMO.

FYI, we also have similar report action context menu global component ref defined in Expensify component [here](https://github.com/Expensify/App/blob/main/src/Expensify.js#L189)

**Comment by michaelhaxhiu** [comment] 2023-07-03 22:57
@rushatgabhane do we have a viable proposal to choose yet or not?

**Comment by payal-lathidadiya** [comment] 2023-07-04 15:37
[PR](https://github.com/Expensify/App/pull/22188) is up for review

cc: @rushatgabhane @michaelhaxhiu

**Comment by alexpensify** [comment] 2023-07-10 21:07
Alright, removing the other 🐛 team member. I'm back online and see that this is our current state: 

Waiting for automation here

**Comment by alexpensify** [comment] 2023-07-14 18:44
To prepare for payment: @Tushu17 can you please apply to the job? I don't think that automation accounted for you finding this 🐛. Thanks! 

https://www.upwork.com/jobs/~01f59b5426989a9373

**Comment by Tushu17** [comment] 2023-07-14 19:12
@alexpensify Okay, I've applied for the job.

**Comment by alexpensify** [comment] 2023-07-17 20:03
I'll work on the payment process tomorrow.

**Comment by alexpensify** [comment] 2023-07-18 00:28
@Tushu17 - I've prepared the payment in Upwork, please accept and I can complete the next steps

@payal-lathidadiya - I've sent the payment via Upwork

@rushatgabhane - please request payment in NewDot, thanks!

**Comment by Tushu17** [comment] 2023-07-18 00:55
@alexpensify I've accepted the offer. Thank you!

**Comment by alexpensify** [comment] 2023-07-18 20:12
Everyone has been paid here. 

--- 

@rushatgabhane - When you get a chance, can you please complete the checklist: 

https://github.com/Expensify/App/issues/21101#issuecomment-1629882520

Thank you!

**Comment by alexpensify** [comment] 2023-07-20 20:38
@rushatgabhane - I'm checking in to see if the checklist is ready and we can close this out. Thanks!

**Comment by alexpensify** [comment] 2023-07-21 19:42
@anmurali - we are on hold for C+ payment and will give the 🟢 as soon as the checklist has been completed.

**Comment by michaelhaxhiu** [comment] 2023-07-21 19:43
Note: you can pay the job out before the checklist is completed. We just need to ensure the checklist is done before the GH is closed.

**Comment by rushatgabhane** [comment] 2023-07-23 11:05
WIP ⚠️ 

1. The PR that introduced the bug has been identified. Link to the PR:

2. The offending PR has been commented on, pointing out the bug it caused and why, so the author and reviewers can learn from the mistake. Link to comment:

3. A discussion in #expensify-bugs has been started about whether any other steps should be taken (e.g. updating the PR review checklist) in order to catch this type of bug sooner. Link to discussion:

4. Determine if we should create a regression test for this bug.

5. If we decide to create a [regression test](https://github.com/Expensify/App/blob/main/contributingGuides/REGRESSION_TEST_BEST_PRACTICES.md) for the bug, please propose the regression test steps to ensure the same bug will not reach production again

**Comment by rushatgabhane** [comment] 2023-07-23 13:36
Made a manual request here https://staging.new.expensify.com/r/2734383403522123

**Comment by alexpensify** [comment] 2023-07-23 15:53
Thank you @rushatgabhane! @anmurali all set for payment here. I'm going to close this GH since all actions have been completed.

**Closed by alexpensify** 2023-07-23 15:53 UTC
Labels: External, Daily, Awaiting Payment, Bug

**Comment by JmillsExpensify** [comment] 2023-07-27 04:31
@alexpensify Can you please summarize the appropriate individual payments for all parties involved in this issue? This is holding up @rushatgabhane's NewDot payments. More information on this compliance process [in Slack](https://expensify.slack.com/archives/C01SKUP7QR0/p1690321157273869).

**Comment by alexpensify** [comment] 2023-07-27 20:49
Here is the payment summary: 

-  External issue reporter: @Tushu17 $250
-  Contributor that fixed the issue: @payal-lathidadiya $1500
-  Contributor+ that helped on the issue and/or PR: @rushatgabhane $1500

Upwork Job: 
https://www.upwork.com/jobs/~01f59b5426989a9373

*_If applicable, the bonuses will be applied on the final payment_ 

Extra Notes regarding payment: All set here @JmillsExpensify! This one was pre-summary days. Everyone has been paid here except @rushatgabhane. Thank you!

**Comment by JmillsExpensify** [comment] 2023-07-27 22:37
Reviewed details for @rushatgabhane. This is accurate based on summary from Business Reviewer and approved for payment in NewDot.
