### ISSUE TITLE
Links aren't highlighted correctly when copying message text

### ISSUE THREAD

**Issue by Julesssss** [Expensify/App#8536] opened 2022-04-07 13:28 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:

- Send a message to another use which includes a link
- Try to copy the message you just sent

## Expected Result:
- All of the selected message should be highlighted blue

## Actual Result:
- The URL section of the message is not highlighted blue

## Workaround:
Can the user still use Expensify without this being fixed? Have you informed them of the workaround?

<img width="835" alt="Screenshot 2022-04-07 at 13 54 18" src="https://user-images.githubusercontent.com/10736861/162203491-03db033a-0adc-47d7-a5fe-bf004fc9ac3d.png">

https://user-images.githubusercontent.com/10736861/162203348-c404712d-9261-4cd8-8242-a04abe8e07d1.mov

## Platform:

Where is this issue occurring?

- Web ✅ 
- iOS ❌ 
- Android ❌  
- Desktop App ❓ -- I get an error when building to Desktop currently
- Mobile Web ❌ 

**Version Number:** v1.1.52-0
**Reproducible in staging?:** Yes
**Reproducible in production?:** Yes
**Email or phone of affected tester (no customers):** 
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** See above
**Issue reported by:** @Julesssss 
**Slack conversation:** N/A

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by parasharrajat** [comment] 2022-04-07 13:52
I also reported it here https://expensify.slack.com/archives/C01GTK53T8Q/p1649262491613459. The selection is not good overall. For links, it just never works.

**Comment by mvtglobally** [comment] 2022-04-08 00:38
Could it be similar to this? https://github.com/Expensify/App/issues/8421

**Comment by laurenreidexpensify** [comment] 2022-04-08 07:43
yeah looks like a dupe of that thanks @mvtglobally

**Closed by laurenreidexpensify** 2022-04-08 07:43 UTC
Labels: AutoAssignerTriage, Daily
