### ISSUE TITLE
[HOLD for payment 2024-05-06] [HIGH] [Splits][$500] Split - Group chat is missing everywhere when created via FAB and bill is split in group chat

### ISSUE THREAD

**Issue by m-natarajan** [Expensify/App#37519] opened 2024-02-29 15:42 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** v1.4.45-1

**Reproducible in staging?:** Yes
**Reproducible in production?:** Yes
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** Applause internal team
**Slack conversation:**

## Action Performed:
1. Go to staging.new.expensify.com
2. Click FAB > Request money > Manual.
3. Click a split bill with two users that have no prior chat via FAB.
4. Navigate to a different chat.
5. Note that the group chat remains in LHN and appears in Search.
6. Go to FAB > Start chat.
7. Create a group chat with two users that have no prior chat.
8. In the group chat, click + > Split bill.
9. Create a bill split.
10. Go to a different chat.
11. Open Search.
## Expected Result:
The group chat will remain in LHN and appear in Search list.

## Actual Result:
The group chat disappears from LHN and is missing in Search list.
This issue only happens when user creates a group chat first, then splits bill in the group chat (Step 6 - 11).
The only way to retrieve the group chat is by recreating it.
## Workaround:
Unknown
## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [x] Android: mWeb Chrome
- [x] iOS: Native
- [x] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

https://github.com/Expensify/App/assets/38435837/87159b78-56c6-46d5-a8ef-62a010e870e6

Add any screenshot/video evidence

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~016f541763635e6d84</li>
        <li>Upwork Job ID: 1767854808847859712</li>
        <li>Last Price Increase: 2024-03-13</li>
<li>Automatic offers: </li>
<ul>
<li>mkhutornyi | Contributor | 0</li>
<li>bernhardoj | Contributor | 0</li>
</ul></li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @mananjadhav</details>

**Comment by m-natarajan** [comment] 2024-02-29 15:43
We think that this bug might be related to #vip-split-p2p-chat-groups
cc @arielgreen

**Comment by m-natarajan** [comment] 2024-02-29 15:43
@dylanexpensify FYI I haven't added the External label as I wasn't 100% sure about this issue. Please take a look and add the label if you agree it's a bug and can be handled by external contributors.

**Comment by bernhardoj** [comment] 2024-03-02 15:11
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
The group chat disappears from LHN even after splitting a bill and can't be found on the search page.

### What is the root cause of that problem?
When we create a new group chat, the `notificationPreference` and `visibleChatMemberAccountIDs` from the BE response will be hidden and empty. After doing a split bill, both data are unchanged. It will be updated once we trigger the OpenReport request by reopening or refreshing the page. If `notificationPreference` is hidden, it will render nothing.
https://github.com/Expensify/App/blob/22cb01c968a53407f7a9d864bfba30f41366f6a0/src/components/LHNOptionsList/OptionRowLHN.tsx#L60-L63

If `visibleChatMemberAccountIDs` is empty, we won't include it in the search results
https://github.com/Expensify/App/blob/22cb01c968a53407f7a9d864bfba30f41366f6a0/src/libs/OptionsListUtils.ts#L1513-L1515

We previously encountered the `notificationPreference` issue [here](https://github.com/Expensify/App/pull/29681#pullrequestreview-1683415098) when adding a new comment to the report.

### What changes do you think we should make in order to solve the problem?

We can use the same solution from https://github.com/Expensify/App/pull/29681, that is to update the `notificationPreference` to **always** if it's currently **hidden** when splitting bill.

```
if (ReportUtils.getReportNotificationPreference(splitChatReport) === CONST.REPORT.NOTIFICATION_PREFERENCE.HIDDEN) {
    splitChatReport.notificationPreference = CONST.REPORT.NOTIFICATION_PREFERENCE.ALWAYS;
}
```

And to show it on the search page, we should also optimistically update the `visibleChatMemberAccountIDs`.

```
splitChatReport.visibleChatMemberAccountIDs = splitChatReport.participantAccountIDs;
```

(we probably would need to do the same for assign task, send, and request money, but depends on how BE do it because for request money, BE never updates `notificationPreference` & `visibleChatMemberAccountIDs`)

**Comment by dylanexpensify** [comment] 2024-03-06 10:39
Apologies, I've been OOO sick, but am reviewing today!

**Comment by dylanexpensify** [comment] 2024-03-11 10:05
Hmm @m-natarajan can you confirm this is still reproducible?

**Comment by dylanexpensify** [comment] 2024-03-11 10:25
Hm so this shows in the Search but not LHN.

**Comment by dylanexpensify** [comment] 2024-03-11 11:48
confirming [here](https://expensify.slack.com/archives/C05RECHFBEW/p1710157727592929)

**Comment by dylanexpensify** [comment] 2024-03-13 10:06
Confirmed and making external

**Comment by dylanexpensify** [comment] 2024-03-18 21:08
@mkhutornyi to review

**Comment by bernhardoj** [comment] 2024-03-19 09:29
@mkhutornyi hmm, you're right.

> (we probably would need to do the same for assign task, send, and request money, but depends on how BE do it because for request money, BE never updates notificationPreference & visibleChatMemberAccountIDs)

There are indeed some cases where it doesn't update as I mention here, but for split bill, it does updated when I writing down the proposal.

In this case, then we should update the BE first to decide the behavior.

**Comment by dylanexpensify** [comment] 2024-03-20 11:43
@marcochavezf to review!

**Comment by marcochavezf** [comment] 2024-03-20 18:18
I looked at the backend and found out we are in the process of deprecating `participantAccountIDs` and `visibleChatMemberAccountIDs` in favor of `participants`. So we should use `participants` instead when possible.

**Comment by bernhardoj** [comment] 2024-03-21 08:27
Hmm, I can't reproduce this anymore. Now, the created group chat has a `notificationPreference` of `always` and the `visibleChatMemberAccountIDs` is not empty. Either it's a new BE bug or it's the new expected behavior. (or is it only me?)

**Comment by mananjadhav** [comment] 2024-03-23 20:20
Taking this over.

**Comment by marcochavezf** [comment] 2024-03-25 17:14
Assigning you @mananjadhav

**Comment by dylanexpensify** [comment] 2024-03-26 10:37
thanks @mananjadhav!

**Comment by marcochavezf** [comment] 2024-03-28 18:40
Hi @mananjadhav, can you review the updated proposals?

**Comment by dylanexpensify** [comment] 2024-03-29 13:18
Bump @mananjadhav 🙇‍♂️

**Comment by mananjadhav** [comment] 2024-03-31 16:44
I just reviewed the whole conversation. 

> Can you confirm whether we should update the report `notificationPreference` from `hidden` to `always` when doing a split bill in a group? (we did this when adding a comment on both BE and FE).

@marcochavezf Can you please confirm this behavior 

Will then shortlist one of the posted proposals.

**Comment by marcochavezf** [comment] 2024-04-02 03:19
If we're changing the notification preference when adding a comment, then yes. It makes sense to have consistent behavior when an action happens in a group, so the participants can be aware of the conversation happening about the money requested.

**Comment by mananjadhav** [comment] 2024-04-08 15:40
Checking in 2-3 hours after a PR review.

**Comment by dylanexpensify** [comment] 2024-04-11 11:14
@mananjadhav let us know if you have an update or if you need some help! 🙇‍♂️

**Comment by mananjadhav** [comment] 2024-04-11 12:37
I just need to test both the proposals and update. I'll do that today. Apologies for the delay.

**Comment by mananjadhav** [comment] 2024-04-12 15:47
Thanks for the patience. I think @bernhardoj's [proposal](https://github.com/Expensify/App/issues/37519#issuecomment-1974825777) looks good. 

🎀 👀 🎀 C+ reviewed.

**Comment by dylanexpensify** [comment] 2024-04-12 19:55
@marcochavezf to review! All good @mananjadhav!

**Comment by dylanexpensify** [comment] 2024-04-15 09:29
@marcochavezf will review today!

**Comment by dylanexpensify** [comment] 2024-04-15 10:10
Mel look above

**Comment by marcochavezf** [comment] 2024-04-15 18:52
Assigning @bernhardoj 🚀

**Comment by bernhardoj** [comment] 2024-04-16 06:58
PR is ready

cc: @mananjadhav

**Comment by dylanexpensify** [comment] 2024-04-29 11:00
waiting for deploy to prod -> regression period

**Comment by bernhardoj** [comment] 2024-04-29 16:45
We have a regression because looks like `participants` contains the current user ID, so we need to filter it out. The PR is ready to fix ti.

cc: @mananjadhav

**Comment by mananjadhav** [comment] 2024-04-29 17:05
Taking a look.

**Comment by dylanexpensify** [comment] 2024-04-30 13:45
Payment coming up!

**Comment by dylanexpensify** [comment] 2024-05-07 08:31
Payment summary:
- Contributor: @bernhardoj $500
- Contributor+: @mananjadhav $500

Please apply/request!

**Comment by dylanexpensify** [comment] 2024-05-07 08:38
@bernhardoj paid out! @mananjadhav to request, closing issue

**Comment by dylanexpensify** [comment] 2024-05-07 08:38
JK - we need @mananjadhav to give regression step proposal

**Comment by mananjadhav** [comment] 2024-05-07 19:04
@dylanexpensify Shouldn't a regression test exist already for group chat in LHN? If they don't we can use the steps mentioned below.

These are the test steps.

1. Create a new group chat with user that is not in your contacts
2. Create a new split bill
3. (Web/Desktop) Switch to another chat (Android/iOS/mWeb) Close the group chat
4. Verify the group chat is still shown in LHN
5. Go to search page and verify the group chat is shown

**Comment by mananjadhav** [comment] 2024-05-08 17:07
Quick bump @dylanexpensify

**Comment by JmillsExpensify** [comment] 2024-05-09 09:44
$250 approved for @mananjadhav

**Comment by lanitochka17** [comment] 2024-05-13 17:58
Do we need to open a new bug or is it the same one?
The tester was able to reproduce this issue again.


https://github.com/Expensify/App/assets/78819774/a35ef934-918a-4c70-9e44-87c67d150f72

**Comment by mananjadhav** [comment] 2024-05-13 18:17
We had fixed this for Split bill and group chat. But in the new video I can see you're trying Submit expense on DM. Could be a separate issue.

**Comment by dylanexpensify** [comment] 2024-05-13 19:04
Agree, @lanitochka17 separate issue

**Closed by dylanexpensify** 2024-05-13 19:04 UTC
Labels: External, Weekly, Awaiting Payment, Bug
