### ISSUE TITLE
[$500] mWeb – Attachment - Unable to open image in new tab.

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#27896] opened 2023-09-20 21:03 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Go to https://staging.new.expensify.com/
2. Log in with any Gmail account
3. Open 1:1 conversation, click on the + button in the compose box
4. Tap on add attachment
5. Upload an image (jpeg or png)
6. Tap on Send
7. Tap on the image
8. Press and hold over the image

## Expected Result:
The context menu opens and tap “Open image in new tab”. Verify the URL starts with "[https://staging.new.expensify.com/chat-attachments/".](https://staging.new.expensify.com/chat-attachments/%22.)

## Actual Result:
Nothing happens. The context menu does not open. Unable to open image in new tab

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [x] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [ ] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 1.3.72-6

**Reproducible in staging?:** Yes

**Reproducible in production?:** Yes

**If this was caught during regression testing, add the test name, ID and link from TestRail:**

**Email or phone of affected tester (no customers):**

**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/78819774/5dad9e95-e802-41be-a2d0-6ae1ac4b50f2

**Expensify/Expensify Issue URL:**

**Issue reported by:** Applause - Internal Team

**Slack conversation:**

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~014bc07c9f376c4612</li>
        <li>Upwork Job ID: 1714382069331976192</li>
        <li>Last Price Increase: 2023-10-17</li>
    </ul>
</details>

**Comment by abdel-h66** [comment] 2023-09-23 14:44
## Proposal

### Please re-state the problem that we are trying to solve in this issue.

Unable to open image in new tab on long pressing the attachment 

### What is the root cause of that problem?

The issue only happens on Chrome due to this line of code 
https://github.com/Expensify/App/blob/5aa7f6da94ddb1c8ca55a6cce714555f819c1dd0/src/components/Pressable/GenericPressable/BaseGenericPressable.js#L131 

This passes an empty longPressHandler when the browser is chrome. 
This line of code was added to fix an issue with the emojies being highlighted when long pressed. this is the issue 
https://github.com/Expensify/App/issues/24654#issuecomment-1688210677
And this is the PR fixing https://github.com/Expensify/App/pull/26931 


### What changes do you think we should make in order to solve the problem?
The changes that I have made are basically avoid passing the empty handler in all cases and pass undefined instead  to the Pressable 
           `onLongPress={!isDisabled && onLongPress ? onLongPressHandler : undefined}`

Being aware of the Emojies issue I also tested that to make sure it won't introduce a regression. and it didn't. 

I believe @s-alves10 can have more information about that fix, and what could this proposal break, beside the emojies styling that I made sure it stayed behaving the same. 

### What alternative solutions did you explore? (Optional)

N/A

**Comment by s-alves10** [comment] 2023-09-23 15:21
We're preventing default context menus. Is this worth fixing?

**Comment by abdel-h66** [comment] 2023-09-24 10:37
Do you mean by passing the `undefined` we are preventing the default context menu ? Or that's the behavior that we are looking for ?

**Comment by s-alves10** [comment] 2023-10-12 12:05
I'll update here this weekend

**Comment by JmillsExpensify** [comment] 2023-10-17 20:45
Triaging for proposals.

**Comment by abdel-h66** [comment] 2023-10-23 13:32
Not sure, we need to double-check again.

**Comment by JmillsExpensify** [comment] 2023-10-24 22:39
@applausebot Can we have someone re-test this issue to see if it's still outsanding?

**Comment by JmillsExpensify** [comment] 2023-11-01 12:51
@lanitochka17 Are you able to re-test this one when you get a chance?

**Comment by JmillsExpensify** [comment] 2023-11-08 12:30
In the queue for QA to re-test.

**Comment by greg-schroeder** [comment] 2023-11-21 06:47
closing

**Closed by greg-schroeder** 2023-11-21 06:47 UTC
Labels: Engineering, Daily, Internal, Overdue, Bug
