### ISSUE TITLE
[$250] Room - When you assign tasks for member outside private room, we should show a popup inviting them

### ISSUE THREAD

**Issue by izarutskaya** [Expensify/App#39799] opened 2024-04-07 16:05 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** v1.4.60-13
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**Email or phone of affected tester (no customers):** [nhut.nguyenminh.it+5000@gmail.com](mailto:nhut.nguyenminh.it+5000@gmail.com)
/ [nhut.nguyenminh.it+2@gmail.com](mailto:nhut.nguyenminh.it+2@gmail.com)
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Issue reported by:** Applause-Internal team

## Action Performed:
Pre-condition: A private room, two accounts ( 1 inside room and 1 outside room - we call A and B)
1. Open the app
2. On A Account, access to Private Room
3. Assign a task for B
4. On B, receive a task
5. B tries to action with Task (mark complete ..)

## Expected Result:
Same as a GROUP chat function.
When assigning tasks to outside members, a popup invites them to show up, and we can invite them to the room.
After B joined a Room, can see tasks or everything in the room
Before B joins a Room, B can't see a Room in the LHN component.

## Actual Result:
Assign tasks for members outside the private room, not show a popup inviting them

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

<img width="1920" alt="Bug6438926_1712305689784!Screenshot_2024-04-05_at_15 11 21" src="https://github.com/Expensify/App/assets/115492554/9c51e1b8-db2a-48dc-a254-429c6365a1bb">
<img width="1920" alt="Bug6438926_1712305689784!Screenshot_2024-04-05_at_15 11 33" src="https://github.com/Expensify/App/assets/115492554/8e36c5fd-a743-4b98-b38b-9f78e8f2ff79">

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

https://github.com/Expensify/App/assets/115492554/3c459032-9089-4713-bd3e-e782c5060a86

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~018bfc480615cf43ae</li>
        <li>Upwork Job ID: 1777344480525914112</li>
        <li>Last Price Increase: 2024-05-07</li>
    </ul>
</details>

**Comment by twisterdotcom** [comment] 2024-04-08 14:35
Task bugs are `MEDIUM` or `LOW` at the moment. I do think this is a bug, because we should prompt you to invite, even if you agree not to. It's great you can assign tasks outside of private rooms and have somebody complete them back to the private room, but it would be confusing to an end user if they thought that made them a member, which I think is a logical jump.

https://github.com/Expensify/App/assets/9133401/3a4b5501-00c9-4e36-8f89-5480869337df

cc @quinthar.

**Comment by VickyStash** [comment] 2024-04-09 10:30
Hi, I'm Viktoryia from Callstack - expert contributor group - and I would like to work on this issue.

**Comment by VickyStash** [comment] 2024-04-09 11:54
@izarutskaya In the expected result section you mentioned that we should act the same way as in the group chat. I've checked how the group chat works and it looks like it does all the same, I don't see an invitation popup. Could you please help me to figure out how the expected result should look?

**Comment by twisterdotcom** [comment] 2024-04-09 12:37
Like this:
<img width="797" alt="image" src="https://github.com/Expensify/App/assets/9133401/c2d6c800-b0a1-469c-b26e-5c68a75871cc">

**Comment by VickyStash** [comment] 2024-04-10 07:47
## Proposal
### Please re-state the problem that we are trying to solve in this issue.
Assigning tasks to a user outside of the private room doesn't trigger a concierge whisper message with this user invitation.
### What is the root cause of that problem?
The API doesn't return an `ACTIONABLEMENTIONWHISPER` report action for task assignees outside of the room, though it does it for usual mentions of members outside of the room.
### What changes do you think we should make in order to solve the problem?
The API should return a report action where `actionName` is `ACTIONABLEMENTIONWHISPER` and `inviteeAccountIDs` has the id of the assignee in case the created task assignee isn't a member of the private room. The FE [already supports](https://github.com/Expensify/App/pull/33665) this type of message, so it should be displayed as expected.

**Comment by twisterdotcom** [comment] 2024-04-10 14:15
@hoangzinh let me know how you feel about this proposal.

**Comment by VickyStash** [comment] 2024-04-15 14:07
@hoangzinh I'll try to provide more details here tomorrow, currently working on a higher priority ticket

**Comment by twisterdotcom** [comment] 2024-04-16 13:30
It's definitely expected that the task is sent to the DM - the system purposefully allows you to assign tasks to somebody who doesn't have the full context of the room; this is normal for people doing tasks part of a wider process.

We just want to always allow the assigner to invite them there and then because:
1. It makes that step easy
2. It prompts the assigner with the information that this user isn't aware of the full context, meaning they can choose to make them aware or not.

**Comment by VickyStash** [comment] 2024-04-16 17:02
@twisterdotcom Got it, thank you for confirming!
But should the assigned user be able to complete the task from DM, if the task was created in a private room and the user wasn't added as a member of this room?
Right now the app shows an error, but the task turns into a completed (though it takes some time for it to be updated):

https://github.com/Expensify/App/assets/23176449/8cf90ad7-3e67-47a9-877d-f1429f53fc26

Is it expected? Or should we hide the task from DM/LHN if the assigned user wasn't added as a member? Or maybe the error shouldn't be shown?

**Comment by twisterdotcom** [comment] 2024-04-16 22:03
>But should the assigned user be able to complete the task from DM, if the task was created in a private room and the user wasn't added as a member of this room?

Yes! They should be able to complete the task.

**Comment by twisterdotcom** [comment] 2024-04-17 10:08
Correct, if they need to complete a task that originated in a room they don't have access to, they have to see it somewhere, in order to know what to do and complete it.

**Comment by twisterdotcom** [comment] 2024-04-19 16:13
Yes, you understand perfectly.

**Comment by VickyStash** [comment] 2024-04-22 14:36
## Proposal
### Please re-state the problem that we are trying to solve in this issue.
1. Assigning tasks to a user outside of the private room doesn't trigger a concierge whisper message with this user invitation.
2. If a user is assigned to a task in a private room, the task is also sent to user's DM, even if the user is not a member of the private room. When a user tries to complete the task from DM, he sees the error message: `You do not have the permission to do the requested action.`, though he should be able to complete a task.



### What is the root cause of that problem?
1. The API doesn't return an `ACTIONABLEMENTIONWHISPER` report action for task assignees outside of the room, though it does it for usual mentions of members outside of the room.
2. The `CompleteTask` API call a `Report no longer exists` error (see the screenshot below), when a user outside of a private room tries to complete the assigned task from DM. Though the task is completed after all.
![image](https://github.com/Expensify/App/assets/23176449/5bb0ae2e-e0dd-4ffd-9cf1-eaa3d21f772a)

### What changes do you think we should make in order to solve the problem?
1. The API should return a report action where `actionName` is `ACTIONABLEMENTIONWHISPER` and `inviteeAccountIDs` has the id of the assignee in case the created task assignee isn't a member of the private room. The FE [already supports ](https://github.com/Expensify/App/pull/33665) this type of message, so it should be displayed as expected.
2. The API shouldn't return an error if a user completes the task he is assigned to. Even if the task was assigned in the private room and the user is not a member of it, the user is still able to see/complete the task from DM.

^^ @hoangzinh

**Comment by VickyStash** [comment] 2024-04-25 13:22
@hoangzinh I think we can use the existing `ACTIONABLE_MENTION_WHISPER` type, at least in the app it was added exactly to display the message mentioned [here](https://github.com/Expensify/App/issues/39799#issuecomment-2045087107), and we need to display the exactly same message.

**Comment by luacmartins** [comment] 2024-04-25 16:44
Seems like the issue is in the API, so we need someone internal to work on this. @jasperhuangg I see you on the blame for code related to `ACTIONABLEMENTIONWHISPER`, would you be available to work on this?

**Comment by luacmartins** [comment] 2024-04-29 16:47
Bump @jasperhuangg, would you be able to take this on since it seems like you're familiar with this code?

**Comment by jasperhuangg** [comment] 2024-04-29 21:50
Sorry I'm having trouble understanding the issue. Are we saying that if we are assigning a task in a room to someone outside of the room, we should display an actionable mention whisper inviting them to the room since they are mentioned in the task?

This was never an expected behavior in the task flow, but it could make sense to add. I think it would be good to get @thienlnam's opinion on this, since he originally implemented tasks.

**Comment by luacmartins** [comment] 2024-04-30 14:35
>Are we saying that if we are assigning a task in a room to someone outside of the room, we should display an actionable mention whisper inviting them to the room since they are mentioned in the task?

Yea, I think that's it.

@thienlnam what do you think, is this something we want for tasks?

**Comment by twisterdotcom** [comment] 2024-04-30 20:20
Yeah I agree. Wow, I assumed this was specifically designed for it, I swore I remember reading this was intended which is why I found it odd not to allow inviting. Seems like we have a solution for it here too, so I say we do it.

**Comment by luacmartins** [comment] 2024-05-06 16:40
Yea, I agree that having a separate action for this would make it consistent with how we're solving it for `actionableRoomMentionWhisper`

**Comment by jasperhuangg** [comment] 2024-05-07 17:04
I can handle the back-end logic for this, probably some time this week.

**Comment by luacmartins** [comment] 2024-05-07 18:50
Thanks @jasperhuangg!

**Comment by jasperhuangg** [comment] 2024-05-09 20:03
Have a few local changes, caught up in some higher priority initiatives at the moment.

**Comment by jasperhuangg** [comment] 2024-05-10 17:04
Demoting to Weekly, will bring it back to `Daily` once I can focus more on this.

**Comment by isabelastisser** [comment] 2024-05-20 16:05
Not overdue. @jasperhuangg deprioritized it to weekly. We should have an update soon!

**Comment by jasperhuangg** [comment] 2024-05-23 18:47
Just got back from OOO, prioritizing some #fast-apis work over this at the moment in lieu of the merge slush. Will have more updates soon.

**Comment by isabelastisser** [comment] 2024-05-31 19:28
not overdue.

**Comment by jasperhuangg** [comment] 2024-05-31 19:43
Still haven't gotten around to doing this yet, focusing on #fast-apis work.

**Comment by jasperhuangg** [comment] 2024-06-10 16:55
Still haven't gotten around to doing this yet, focusing on #fast-apis work.

**Comment by twisterdotcom** [comment] 2024-06-18 22:13
Shall we make it Monthly?

**Comment by jasperhuangg** [comment] 2024-06-20 18:36
Monthly seems like a good idea, especially considering [the update](https://expensify.slack.com/archives/C066HJM2CAZ/p1718231219111659) in #vip-vsb that the room in on HOLD for the time being.

**Comment by twisterdotcom** [comment] 2024-07-22 10:48
Been making these `Not a priority` and closing when it comes to vip-vsb actually.

**Closed** 2024-07-22 10:48 UTC
Labels: Monthly, Internal, NewFeature, Help Wanted, Not a priority
