### ISSUE TITLE
[HOLD for payment 2024-06-20] [$250] Chat - Unable to open chat if going back from not found page after using send invoice link

### ISSUE THREAD

**Issue by izarutskaya** [Expensify/App#42902] opened 2024-05-31 09:49 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.78-2
**Reproducible in staging?:** Y
**Reproducible in production?:** N
**Found when executing PR :** https://github.com/Expensify/App/pull/41730
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Issue reported by:** Applause-Internal team

## Action Performed:
1. Open the app and log in with an account that does not have a workspace
2. Paste the send invoice link https://staging.new.expensify.com/create/invoice/start/1/7783051691252045
in any chat
3. Open the link
4. Tap the back icon
5. Open the chat where the link was shared

## Expected Result:
The chat is opened.

## Actual Result:
Unable to open the chat, it is not responding to a tap. It seems like user should be navigated to the chat in the first place instead of the LHN when going back from the not found page.

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [ ] Android: mWeb Chrome
- [x] iOS: Native
- [ ] iOS: mWeb Safari
- [ ] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

https://github.com/Expensify/App/assets/115492554/c3b139a0-cbc1-4300-a0eb-a89b0296852a

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~019eaddaf6970628b2</li>
        <li>Upwork Job ID: 1796604996438876160</li>
        <li>Last Price Increase: 2024-05-31</li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @isabelastisser</details>

**Comment by izarutskaya** [comment] 2024-05-31 09:50
@isabelastisser I haven't added the External label as I wasn't 100% sure about this issue. Please take a look and add the label if you agree it's a bug and can be handled by external contributors.

**Comment by izarutskaya** [comment] 2024-05-31 09:50
We think this issue might be related to the #collect project.

**Comment by izarutskaya** [comment] 2024-05-31 09:51
Production 

https://github.com/Expensify/App/assets/115492554/38387a91-760e-4136-a2e3-70b2e23ed0ac

**Comment by cristipaval** [comment] 2024-05-31 15:05
Removed the deploy blocker as per [this plan](https://expensify.slack.com/archives/CSL3XBCCR/p1717167018470479?thread_ts=1717165640.669459&cid=CSL3XBCCR). Let's assign @tienifr to fix and @shubham1206agra for the c+ review, since they are the authors of the original PR 🙏

**Comment by kpadmanabhan** [comment] 2024-06-02 03:55
@izarutskaya : i see that after multiple taps (randomly) the chat opens up and shows the oage not found view. do you see the same behaviour? looking into the issue.

**Comment by kpadmanabhan** [comment] 2024-06-02 09:35
> Removed the deploy blocker as per [this plan](https://expensify.slack.com/archives/CSL3XBCCR/p1717167018470479?thread_ts=1717165640.669459&cid=CSL3XBCCR). Let's assign @tienifr to fix and @shubham1206agra for the c+ review, since they are the authors of the original PR 🙏

@tienifr / @cristipaval : can you please point me to the original PR here? Thank you.

**Comment by kpadmanabhan** [comment] 2024-06-02 09:52
> Removed the deploy blocker as per [this plan](https://expensify.slack.com/archives/CSL3XBCCR/p1717167018470479?thread_ts=1717165640.669459&cid=CSL3XBCCR). Let's assign @tienifr to fix and @shubham1206agra for the c+ review, since they are the authors of the original PR 🙏

@cristipaval : Is this already assigned to @tienifr as a regression issue? `HelpWanted` was misleading in this case without `melvin-bot` assigning this to @tienifr . I will await your confirmation before further investigation.

**Comment by isabelastisser** [comment] 2024-06-20 18:46
@shubham1206agra, please complete the BZ list above. Thanks!

**Comment by isabelastisser** [comment] 2024-06-20 18:58
ROLE: c+ @shubham1206agra paid $250via Upwork 
ROLE: Contributor @tienifr paid $250 via Upwork 

@tienifr, can you please share your Upwork profile link?

@shubham1206agra I sent you an offer.

**Comment by isabelastisser** [comment] 2024-06-21 18:58
Thanks for the heads up! I will cancel @shubham1206agra offer in Upwork now.

Closing.

**Closed by isabelastisser** 2024-06-21 18:58 UTC
Labels: External, Engineering, Daily, Help Wanted, Awaiting Payment, Bug
