### ISSUE TITLE
[HOLD for payment 2023-10-31] [$500] Send money - Extra space after 'Pay' in option select popup of send money

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#29340] opened 2023-10-11 16:23 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.3.81.5
**Reproducible in staging?:** y
**Reproducible in production?:** n (send money flow just implemented)
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** @dhanashree-sawant
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1697011023670229

## Action Performed:
1. Open the app
2. Click on green plus and click send money
3. Select USD and enter any amount and click Next
4. Select any user
5. Observe that spacing between is correct for 'Pay with expensify' on button
6. Click on dropdown besides to display option select popup and observe that 'Pay with expensify' has extra space after 'Pay' text

## Expected Result:
App should only have single space after any word

## Actual Result:
App has 2 spaces after 'Pay' in 'Pay with expensify' option select popup in send money

## Workaround:
Unknown 

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [x] Android: mWeb Chrome
- [x] iOS: Native
- [x] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos
<details>
<summary>Android: Native</summary>

![Screenshot_20231011_121700_New Expensify](https://github.com/Expensify/App/assets/93399543/4368dd49-21c0-42c7-a5ab-9a9073936c7e)

</details>

<details>
<summary>Android: mWeb Chrome</summary>

 
![android chrome space after pay](https://github.com/Expensify/App/assets/93399543/70c8954c-aeab-4129-8cd8-49ba7f812acd)

</details>

<details>
<summary>iOS: Native</summary>

 
![ios native space after pay](https://github.com/Expensify/App/assets/93399543/bca5946c-10e7-4dac-b871-559dd1cd742f)

</details>

<details>
<summary>iOS: mWeb Safari</summary>

 
![ios safari space after pay](https://github.com/Expensify/App/assets/93399543/6bd1f5f8-7065-4009-a2e3-a6d216333d20)

</details>

<details>
<summary>MacOS: Chrome / Safari</summary>

 

https://github.com/Expensify/App/assets/93399543/3d09ae2b-e873-44e5-b39b-f6e3bcbd083d

https://github.com/Expensify/App/assets/93399543/2e543584-085d-4191-8da4-4980063e0a8d

</details>

<details>
<summary>MacOS: Desktop</summary>

 

https://github.com/Expensify/App/assets/93399543/73540a38-f1a3-401e-8dc0-d9e28e0b4dad

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01f865c8c8563e96b7</li>
        <li>Upwork Job ID: 1712141948988710912</li>
        <li>Last Price Increase: 2023-10-11</li>
<li>Automatic offers: </li>
<ul>
<li>c3024 | Contributor | 27259604</li>
<li>dhanashree-sawant | Reporter | 27259605</li>
</ul></li>
    </ul>
</details>

**Comment by c3024** [comment] 2023-10-11 16:23
## Proposal
### Please re-state the problem that we are trying to solve in this issue.
There is an extra space in the popover option of "Pay with expensify"
### What is the root cause of that problem?
We are not passing `formattedAmount` to `SettlementButton` here
https://github.com/Expensify/App/blob/36f26e8dfa10622da77c594e1dbee8a4776c30c1/src/components/MoneyRequestConfirmationList.js#L436
and this here
https://github.com/Expensify/App/blob/36f26e8dfa10622da77c594e1dbee8a4776c30c1/src/components/SettlementButton.js#L130
and this here further
https://github.com/Expensify/App/blob/36f26e8dfa10622da77c594e1dbee8a4776c30c1/src/languages/en.ts#L536
shows two spaces one before the amount and one after the amount with the amount being empty
### What changes do you think we should make in order to solve the problem?
We should change this to
```js
settleExpensify: ({formattedAmount}: SettleExpensifyCardParams) => formattedAmount 
        ? `Pay ${formattedAmount} with Expensify` 
        : `Pay with Expensify`,
```
We do the same change in `es.ts`
### What alternative solutions did you explore? (Optional)
We might consider passing the `formattedAmount` to `SettlementButton` but then I think we should also change the "Pay elsewhere" here 
https://github.com/Expensify/App/blob/36f26e8dfa10622da77c594e1dbee8a4776c30c1/src/languages/en.ts#L537
to similar to 
https://github.com/Expensify/App/blob/36f26e8dfa10622da77c594e1dbee8a4776c30c1/src/languages/en.ts#L536
to show formatted amount for consistency.

Another choice is to remove the formattedAmount from the settleExpensify as well and simply show Pay with Expensify
<details>
<summary>Result</summary>



<img width="1440" alt="Screenshot 2023-10-11 at 8 46 58 PM" src="https://github.com/Expensify/App/assets/102477862/35e41979-f48b-485a-920f-5f9aba157ae9">


</details>

**Comment by Pujan92** [comment] 2023-10-11 16:27
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
Extra space for Pay with expensify option in the popover

### What is the root cause of that problem?
In the translation, we are using `formattedAmount` between "pay" and "with". Extra space persists when we are not passing the prop `formattedAmount`.
https://github.com/Expensify/App/blob/d7b1deb7e7fb4d6ae8846ad9488fef1205fdc5d6/src/languages/en.ts#L536

### What changes do you think we should make in order to solve the problem?
We can cut down an extra space when there isn't `formattedAmount` available with the ternary condition. Need to apply in both translation files.

```js
settleExpensify: ({formattedAmount}: SettleExpensifyCardParams) => `Pay ${formattedAmount ? `${formattedAmount} `: ''}with Expensify`,
```

**Comment by DylanDylann** [comment] 2023-10-12 14:32
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
-  Extra space after 'Pay' in option select popup of send money

### What is the root cause of that problem?
- We are not passing formattedAmount to SettlementButton here:
https://github.com/Expensify/App/blob/61920ff55011f3d72577f69b2c6526a5fade624a/src/components/SettlementButton.js#L125-L133
with the ```settleExpensify``` is defined as:
https://github.com/Expensify/App/blob/d7b1deb7e7fb4d6ae8846ad9488fef1205fdc5d6/src/languages/en.ts#L536
- So it will add extra space after "Pay"
### What changes do you think we should make in order to solve the problem?
- We can add the ```noWrap``` style to the MenuItem so it will auto remove all the extra space between texts. Also, we should add the flag props, for example ```shouldRemoveExtraSpace``` to check whether we should remove extra space or not, like below:
- Update https://github.com/Expensify/App/blob/f942acd2c87d3babcdb6fb83f19e8dc02518efc8/src/components/MenuItem.js#L90-L103 to
```
...
 props.shouldRemoveExtraSpace && styles.noWrap
```
- In this case of display button options, we set ```shouldRemoveExtraSpace``` to true.

### What alternative solutions did you explore? (Optional)
- NA

**Comment by astrohunter62** [comment] 2023-10-13 20:11
## Proposal
### Please re-state the problem that we are trying to solve in this issue.
Extra space after "Pay" in option select popup of send money.
### What is the root cause of that problem?
The option popover text  of payment method are defined here:
https://github.com/Expensify/App/blob/abfa6a58e8a4301afc446c8fc96789501fd6db8f/src/components/SettlementButton.js#L133-L149
And `translate` function call the `settleExpensify()`.
https://github.com/Expensify/App/blob/abfa6a58e8a4301afc446c8fc96789501fd6db8f/src/languages/en.ts#L545
When `formattedAmount` is undefined, there are double space between "Pay" and "with".
### What changes do you think we should make in order to solve the problem?
We can change the `settleExpensify` function.
```js
settleExpensify: ({formattedAmount}: SettleExpensifyCardParams) => (formattedAmount ? `Pay ${formattedAmount} with Expensify` : `Pay with Expensify`),
```
### What alternative solutions did you explore? (Optional)
We can also remove the extra spaces in `SettlementButton` when setting payment method text.
```js
text: translate('iou.settleExpensify', {formattedAmount}).replace(/\s+/g, ' ').trim()
```
![Screenshot 2023-10-13 160753](https://github.com/Expensify/App/assets/136574831/5b418bbc-9c8a-417f-b808-b964b59ca021)

**Comment by burczu** [comment] 2023-10-17 12:25
not overdue - I'll be reviewing proposals soon

**Comment by JmillsExpensify** [comment] 2023-10-17 21:02
Per the above, proposals will be reviewed shortly

**Comment by burczu** [comment] 2023-10-18 07:22
I've just reviewed all the proposals and I think they all identified the root cause correctly. We had few solutions to choose but I think the simplest (and the best) is just the one with using ternary operator in the translations files (we already use such approach in these files).

That being said, it looks like the first contributor with [the proposal](https://github.com/Expensify/App/issues/29340#issuecomment-1758059584) containing such solution was @c3024 and we should proceed with them.

🎀 👀 🎀 C+ reviewed

**Comment by JmillsExpensify** [comment] 2023-10-24 22:49
@burczu Mind kicking off the BZ checklist? In the meantime, payment summary as follows:

 - Issue reporter: @dhanashree-sawant $50
 - Contributor: @c3024 $750 (incl. bonus)

**Comment by burczu** [comment] 2023-10-31 13:39
**BugZero Checklist:** The PR fixing this issue has been merged! The following checklist ([instructions](https://stackoverflow.com/c/expensify/questions/14574)) will need to be completed before the issue can be closed:
> 
* [ ]  [@burczu] The PR that introduced the bug has been identified. Link to the PR: **I don't think this issue is an regression after merging any other PR.**
* [ ]  [@burczu] The offending PR has been commented on, pointing out the bug it caused and why, so the author and reviewers can learn from the mistake. Link to comment: **n/a**
* [ ]  [@burczu] A discussion in #expensify-bugs has been started about whether any other steps should be taken (e.g. updating the PR review checklist) in order to catch this type of bug sooner. Link to discussion: **n/a**
* [ ]  [@burczu] Determine if we should create a regression test for this bug. **I think there is no need to add any regression here - this was just a minor UI bug that didn't break any important flow in the App and wasn't impactful.**
* [ ]  [@burczu] If we decide to create a regression test for the bug, please propose the [regression test](https://github.com/Expensify/App/blob/main/contributingGuides/REGRESSION_TEST_BEST_PRACTICES.md) steps to ensure the same bug will not reach production again.
* [ ]  [@JmillsExpensify] Link the GH issue for creating/updating the regression test once above steps have been agreed upon:

**Comment by hayata-suenaga** [comment] 2023-11-06 19:00
waiting for the checklist to complete and payment to be processed

**Comment by hayata-suenaga** [comment] 2023-11-10 00:51
waiting for the checklist to complete and payment to be processed

**Comment by hayata-suenaga** [comment] 2023-11-13 16:16
waiting for the checklist to complete and payment to be processed

**Comment by burczu** [comment] 2023-11-14 09:05
@hayata-suenaga Checklist is completed here: https://github.com/Expensify/App/issues/29340#issuecomment-1787240223

**Comment by hayata-suenaga** [comment] 2023-11-14 18:27
okay then we're waiting for the payment

**Comment by hayata-suenaga** [comment] 2023-11-20 16:45
melvin, we're waiting for payment

**Comment by hayata-suenaga** [comment] 2023-11-24 15:47
melvin, we're waiting for payment

**Comment by JmillsExpensify** [comment] 2023-11-24 17:37
Jumping in to close the loop on payment.

**Comment by JmillsExpensify** [comment] 2023-11-24 17:40
All contributors paid out via the payment summary and no regression test required. Closing this out.

**Closed by JmillsExpensify** 2023-11-24 17:40 UTC
Labels: External, Daily, Awaiting Payment, Bug
