### ISSUE TITLE
[payment due 9/6][$250] Avatar - Unable to choose profile avatar from library

### ISSUE THREAD

**Issue by izarutskaya** [Expensify/App#48242] opened 2024-08-29 08:18 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** v9.0.26-1
**Reproducible in staging?:** Y
**Reproducible in production?:** N
**Pending when validation PR** https://github.com/Expensify/App/pull/47338
**Email or phone of affected tester (no customers):** applausetester+kh050806@applause.expensifail.com
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Issue reported by:** Applause-Internal team

## Action Performed:
1. Launch New Expensify app.
2. Go to Account settings > Profile.
3. Tap on the avatar.
4. Tap Choose from library.
5. Select a photo.
6. Tap on the app back button.
7. Tap on the avatar.
8. Tap Choose from library.

## Expected Result:
User should be able to choose profile avatar from library.

## Actual Result:
Nothing happens after tapping Choose from library.

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [ ] Android: mWeb Chrome
- [x] iOS: Native
- [ ] iOS: mWeb Safari
- [ ] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

https://github.com/user-attachments/assets/91434dbd-82c8-40c6-82f2-97cdcfe28def

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01ca983c30cf1e2b4a</li>
        <li>Upwork Job ID: 1829208880175339857</li>
        <li>Last Price Increase: 2024-08-29</li>
<li>Automatic offers: </li>
<ul>
<li>eh2077 | Reviewer | 103738968</li>
</ul></li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @eh2077</details>

**Comment by bernhardoj** [comment] 2024-08-29 16:27
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
The option to select image doesn't show after selecting Upload photo

### What is the root cause of that problem?
The profile page is wrapped with MenuItemGroup.
https://github.com/Expensify/App/blob/c8679187cd766270e1f8485180a16429403372d0/src/pages/settings/Profile/ProfilePage.tsx#L147-L158

MenuItemGroup pass down a context of single execution and wait for navigate function.
https://github.com/Expensify/App/blob/c8679187cd766270e1f8485180a16429403372d0/src/components/MenuItemGroup.tsx#L22-L31

When we press Upload photo, it will call single execution and wait for navigate. Single execution will set the `isExecuting` state to true
https://github.com/Expensify/App/blob/c8679187cd766270e1f8485180a16429403372d0/src/components/MenuItem.tsx#L531-L540

which will disable the menu item.
https://github.com/Expensify/App/blob/c8679187cd766270e1f8485180a16429403372d0/src/components/MenuItem.tsx#L583

It will be enabled back once the promise of the action passed to `singleExecution` is resolved.
https://github.com/Expensify/App/blob/c8679187cd766270e1f8485180a16429403372d0/src/hooks/useSingleExecution/index.native.ts#L26-L33

In our case, the promise is the `waitForNavigate`,
https://github.com/Expensify/App/blob/c8679187cd766270e1f8485180a16429403372d0/src/hooks/useWaitForNavigation.ts#L27-L31

and it will be resolved once the blur event is triggered. But since there is no navigation happening, the promise is never resolved.

This issue happens after the copilot PR where we move the profile image to profile page.

### What changes do you think we should make in order to solve the problem?

We can disable the single execution + wait for navigate thing for the profile image picker by wrapping it with another `MenuItemGroup` and pass `shouldUseSingleExecution` as false. This way, the menu item inside the popover menu won't use the single execution logic and will behave like before the copilot PR.

```
<MenuItemGroup shouldUseSingleExecution={false}>
    <AvatarWithImagePicker ...
```

https://github.com/Expensify/App/blob/c8679187cd766270e1f8485180a16429403372d0/src/pages/settings/Profile/ProfilePage.tsx#L157-L158

Or we can do it the hard way by accepting a new props to disable either single execution or wait for navigate or both.

### What alternative solutions did you explore? (Optional)

**Comment by bernhardoj** [comment] 2024-08-29 18:13
PR is ready

cc: @eh2077

**Comment by allroundexperts** [comment] 2024-08-29 21:37
Since I reviewed the PR, can I be assigned here?

**Comment by Christinadobrzyn** [comment] 2024-09-03 23:46
Looks like PR was deployed to production on 8/30. Payment day is 9/6. I'm going to be ooo so going to add a BZ teammate to issue payment. 

Payouts due:

- [ ] Contributor: $250 @bernhardoj 
- [ ] Contributor+: $250 @allroundexperts 

- I think both of you are paid in NewDot? (if not please accept these [Upwork offers](https://www.upwork.com/ab/applicants/1831116104394530384/offers))

- Do we need a regression test?

**Comment by bernhardoj** [comment] 2024-09-04 03:10
Yes, I'll request in ND.

**Comment by zanyrenney** [comment] 2024-09-10 14:26
I don't think we need a regression test for this.

**Comment by zanyrenney** [comment] 2024-09-10 14:27
Payment summary [above](https://github.com/Expensify/App/issues/48242#issuecomment-2327637568) closing as both are paid via ND.

**Closed by zanyrenney** 2024-09-10 14:27 UTC
Labels: Reviewing, External, Engineering, Daily, Bug

**Comment by bernhardoj** [comment] 2024-09-11 05:53
Requested in ND.

**Comment by JmillsExpensify** [comment] 2024-09-11 12:10
$250 approved for @bernhardoj
