### ISSUE TITLE
[$500] Names missing in LHN for a group chat

### ISSUE THREAD

**Issue by m-natarajan** [Expensify/App#35537] opened 2024-02-01 04:21 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.35-0
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** @mallenexpensify 
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1706727753588069

## Action Performed:

1. Sent message to group chat
2. Noticed names were missing when searching
3. Scroll through the LHN and again search

## Expected Result:
Group chat members name should appear when searching
## Actual Result:
members name does not show immediately when searching after sending a message. Has to scrolldown the LHN to appear the name when searching
## Workaround:
unknown
## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

https://github.com/Expensify/App/assets/38435837/923fb458-3193-46b5-a858-436b25649efa
![image](https://github.com/Expensify/App/assets/38435837/68a6d050-4973-4052-80b4-349e18ff13e5)
![image (1)](https://github.com/Expensify/App/assets/38435837/a52315aa-bf52-4e76-a372-b5ab93e3f928)
![image (2)](https://github.com/Expensify/App/assets/38435837/6f4d2744-467b-41da-a6c6-018ae9b89bc1)

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01a6b3d85f01d11739</li>
        <li>Upwork Job ID: 1752910067363061760</li>
        <li>Last Price Increase: 2024-02-01</li>
    </ul>
</details>

**Comment by pc11000** [comment] 2024-02-01 09:47
I do not understand the problem, seems to work for me.
Also in the attached video nothing is being searched?

**Comment by godofoutcasts94** [comment] 2024-02-01 10:28
Contributor details
Your Expensify account email: godofoutcasats94@gmail.com
Upwork Profile Link: https://www.upwork.com/freelancers/~0166de62e4f4b743fd

**Comment by godofoutcasts94** [comment] 2024-02-01 10:29
Contributor details
Your Expensify account email: godofoutcasats94@gmail.com
Upwork Profile Link: https://www.upwork.com/freelancers/~0166de62e4f4b743fd

**Comment by nebiyuelias1** [comment] 2024-02-01 12:23
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
After creating a chat group, the names of the members are not shown on the search result page.

### What is the root cause of that problem?
This is happening because of inconsistent report data inside Onyx. In particular to construct the search result options, the report's `visibleChatMemberAccountIDs` field is accessed in https://github.com/nebiyuelias1/App/blob/aeb8638a46bbc50013e263f037a45c7c3b7af8ad/src/libs/OptionsListUtils.ts#L1441. But this is sometimes empty array and as a result, the names of the members are not shown. 

### What changes do you think we should make in order to solve the problem?
If the visibleChatMemberAccountIDs field is an empty array it's better to use a fallback field: `participantAccountIDs` like this:
```
 const accountIDs = (report.visibleChatMemberAccountIDs?.length ?? 0) > 0 ? report.visibleChatMemberAccountIDs : report.participantAccountIDs ?? [];

```

### What alternative solutions did you explore? (Optional)
We can directly use `participanetAccountIDs` field all the time if it's possible.

**Comment by getusha** [comment] 2024-02-02 08:28
Trying to reproduce the issue.

**Comment by mallenexpensify** [comment] 2024-02-03 00:43
Maybe create the group chat, don't comment on it, navigate away, the search in lhn for it?
<img width="363" alt="image" src="https://github.com/Expensify/App/assets/22508304/688f192c-30c4-4d95-bc21-d4cda4336a39">

**Comment by getusha** [comment] 2024-02-04 11:46
Thanks @mallenexpensify, i'm able to reproduce it.
Reviewing @nebiyuelias1's proposal.

**Comment by getusha** [comment] 2024-02-04 12:23
@nebiyuelias1 your solution works, about the RCA could we try to find why the onyx data is being inconsistent, sometimes the names are correctly displayed?

**Comment by nebiyuelias1** [comment] 2024-02-04 13:09
> @nebiyuelias1 your solution works, about the RCA could we try to find why the onyx data is being inconsistent, sometimes the names are correctly displayed?

I believe the BE sends incomplete data for some reports and the FE would periodically send an `OpenReport` action for some inconsistent reports. That's why I suggest using a fallback.

**Comment by nebiyuelias1** [comment] 2024-02-04 13:15
> @nebiyuelias1 your solution works, about the RCA could we try to find why the onyx data is being inconsistent, sometimes the names are correctly displayed?
@getusha This is from the readme:

![image](https://github.com/Expensify/App/assets/25957442/dd5e7e67-ce98-4c80-88b5-ac2451f6c7e8)

**Comment by Tony-MK** [comment] 2024-02-04 19:51
This issue has the same root cause as https://github.com/Expensify/App/issues/35679.

**Comment by nebiyuelias1** [comment] 2024-02-04 20:26
> This issue has the same root cause as https://github.com/Expensify/App/issues/35679.

Apparently yes. Which means this is sorta a dupe issue.

**Comment by stephanieelliott** [comment] 2024-02-06 05:53
Ah ok yes, let's close this in favor of https://github.com/Expensify/App/issues/35537 since we already have a proposal and a PR being worked on there.

**Closed by stephanieelliott** 2024-02-06 05:53 UTC
Labels: External, Daily, Help Wanted, Bug
