### ISSUE TITLE
[hold for payment 2024-10-07] [$250] [OldDot Rules Migration] - Auto-pay approved reports amount is 0 instead of 100 when enabled for the first time

### ISSUE THREAD

**Issue by IuliiaHerets** [Expensify/App#49254] opened 2024-09-16 10:23 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 9.0.34-2
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**Email or phone of affected tester (no customers):** applausetester+kh010901@applause.expensifail.com
**Issue reported by:** Applause Internal Team

## Action Performed:
1. Go to staging.new.expensify.com
2. Go to workspace settings > Rules.
3. Enable "Auto-pay approved reports".
4. Note that the amount for "Auto-pay reports under" is 0.
5. Disable "Auto-pay approved reports".
6. Reenable "Auto-pay approved reports".
7. Note that the amount for "Auto-pay reports under" is 100.00.

## Expected Result:
Since the default value after reenabling "Auto-pay approved reports" is 100 (Step 7), when enabling it for the first time (Step 4), the value should be 100.

## Actual Result:
In Step 4, when enabling "Auto-pay approved reports" for the first time, it is 0.
In Step 7, after disabling and reenabling it, it becomes 100.

## Workaround:
Unknown

## Platforms:

- [x] Android: Native
- [x] Android: mWeb Chrome
- [x] iOS: Native
- [x] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

https://github.com/user-attachments/assets/6df166cd-75df-42f2-a266-f0ae39b64c95

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~021835706244754359508</li>
        <li>Upwork Job ID: 1835706244754359508</li>
        <li>Last Price Increase: 2024-09-16</li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @</details>

**Comment by IuliiaHerets** [comment] 2024-09-16 10:23
@joekaufmanexpensify  FYI I haven't added the External label as I wasn't 100% sure about this issue. Please take a look and add the label if you agree it's a bug and can be handled by external contributors

**Comment by DylanDylann** [comment] 2024-09-16 10:28
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
In Step 4, when enabling "Auto-pay approved reports" for the first time, it is 0.
In Step 7, after disabling and reenabling it, it becomes 100.

### What is the root cause of that problem?
We only set default value when disable "Auto-pay approved reports"

### What changes do you think we should make in order to solve the problem?
We also need to set default value when. we enable "Auto-pay approved reports"

### What alternative solutions did you explore? (Optional)

**Comment by DylanDylann** [comment] 2024-09-16 10:30
@BrtqKr It seems this relates to this issue https://github.com/Expensify/App/issues/47014. Could you take a look?

**Comment by nkdengineer** [comment] 2024-09-16 10:48
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
In Step 4, when enabling "Auto-pay approved reports" for the first time, it is 0.
In Step 7, after disabling and reenabling it, it becomes 100.

### What is the root cause of that problem?
When we enable we update nothing in optimistic data then the default limit amount is 0. After we disable and enable again, the amount is 100 because it's updated in optimistic data when we disable the limit amount.


https://github.com/Expensify/App/blob/19d037b3a900b08de1f8ba2f22624ba445abe3a5/src/libs/actions/Policy/Policy.ts#L4481-L4489
### What changes do you think we should make in order to solve the problem?
We should change `!enabled` condition here to `enabled` to update the correct optimistic data. 


https://github.com/Expensify/App/blob/19d037b3a900b08de1f8ba2f22624ba445abe3a5/src/libs/actions/Policy/Policy.ts#L4481-L4489

I checked after reset cache and restart again the amount limit still is `0` so we also need a back-end change to update the correct limit amount value when we enable `Auto-pay approved reports` 

### What alternative solutions did you explore? (Optional)

**Comment by joekaufmanexpensify** [comment] 2024-09-16 15:43
I couldn't reproduce it 100% on the first try. The first time I tried it, I saw $100 initially, but then when I toggled the setting back off, the app crashed. When I reloaded, and tried a second time, I saw the behavior of defaulting to $0. 

Then, when I tried with a second workspace, I saw the bug on the first try. So it def exists, and maybe the crash is a related issue? Both are shown below: 


https://github.com/user-attachments/assets/5c207171-0836-4874-9207-0b4adafce6fa

https://github.com/user-attachments/assets/74ed2f59-04dc-4d5e-a673-5fdc6196e75c

**Comment by joekaufmanexpensify** [comment] 2024-09-16 15:43
@DylanDylann assigning you as C+ here as I see you worked on the original PR

**Comment by joekaufmanexpensify** [comment] 2024-09-16 15:44
cc @marcaaron too as I see you're the project lead

**Comment by joekaufmanexpensify** [comment] 2024-09-16 15:45
If this is a FE fix, and @BrtqKr is available, that makes sense to me as I see Software Mansion is working on this project

**Comment by marcaaron** [comment] 2024-09-16 23:06
@joekaufmanexpensify did you see any JS console logs when the crash happened?

This issue LGTM. I assigned myself so I can help look into the backend changes. @nkdengineer's proposal sounds correct and we will need some kind of change.

**Comment by marcaaron** [comment] 2024-09-16 23:23
I also noticed that the current code is wrong as it sets the `autoApproval.rate` to `5` which is not correct. It should be a float value as per the design doc:

```
Random report audit
Command name: SetPolicyAutomaticApprovalAuditRate
API request parameters: policyID: String, auditRate: Int
New values:
{
    autoApproval: {
        auditRate: Float
    }
}

API Note: We will accept Int values to the API, but end up using this as a fraction so 1 = 0.1 and 100 = 1. Values over 100 are not permitted.
```

I think the best thing would be to just make it a float value in the Onyx data and for what gets sent to the API. So the new "default" would be `0.05` not `5`. Does it make sense?

**Comment by marcaaron** [comment] 2024-09-16 23:38
I think I'm gonna take over this whole issue sorry. It's just gonna be easier for me to implement than to explain exactly what needs to be done.

**Comment by marcaaron** [comment] 2024-09-18 03:13
Ok looked at this some more today. We are also sending the incorrect params to the API. Fixing it now...

**Comment by joekaufmanexpensify** [comment] 2024-09-19 13:29
Various PRs in review here

**Comment by joekaufmanexpensify** [comment] 2024-09-23 14:37
Web PR merged pending deploy. App PR on hold for that.

**Comment by marcaaron** [comment] 2024-09-26 00:12
Just down to the final App PR now.

**Comment by joekaufmanexpensify** [comment] 2024-09-30 14:13
App PR on staging

**Comment by joekaufmanexpensify** [comment] 2024-10-07 14:50
App PR went out to prod on the 30th, but automation failed. Payment is due today

**Comment by joekaufmanexpensify** [comment] 2024-10-07 14:51
Only payment here is $250 to @DylanDylann for C+ review of App PR via upwork

**Comment by joekaufmanexpensify** [comment] 2024-10-07 14:51
@DylanDylann offer for $250 sent!

**Comment by DylanDylann** [comment] 2024-10-07 15:36
@joekaufmanexpensify Accepted 🙏

**Comment by joekaufmanexpensify** [comment] 2024-10-07 15:39
@DylanDylann $250 sent and contract ended!

**Comment by joekaufmanexpensify** [comment] 2024-10-07 15:39
All set, thanks everyone!

**Closed by joekaufmanexpensify** 2024-10-07 15:39 UTC
Labels: Reviewing, Weekly, Internal, Bug
