### ISSUE TITLE
Receiving double notifications on desktop app

### ISSUE THREAD

**Issue by mvtglobally** [Expensify/App#9559] opened 2022-06-24 15:14 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Using app, receiving messages

## Expected Result:
Receive one notification per message

## Actual Result:
Received two notification per message

## Workaround:
unknown 

## Platform:

Where is this issue occurring?

- Desktop App
- IOS
- Web

**Version Number:** 1.1.77-2
**Reproducible in staging?:** Y 
**Reproducible in production?:** need repro
**Email or phone of affected tester (no customers):** 
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation 

**Expensify/Expensify Issue URL:** 
**Issue reported by:** @mallenexpensify 
**Slack conversation:** https://expensify.slack.com/archives/C01GTK53T8Q/p1656017883939069?thread_ts=1655917421.982199&cid=C01GTK53T8Q

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by mallenexpensify** [comment] 2022-06-27 21:13
@cead22 👀 plz, do you think an external contributor can work on this?

**Comment by cead22** [comment] 2022-06-27 21:38
Does anybody have reliable steps to reproduce?

**Comment by roryabraham** [comment] 2022-06-27 22:11
> Are these notifications push notifications sent from the backend or local notifications generated on the front end

Browser notifications are locally-generated on the front-end actually, so external contributors should be able to investigate this.

**Comment by roryabraham** [comment] 2022-06-27 22:23
I've seen observed this but don't know about reliable reproduction steps. Here's some info to get us started though:

- Local comment notifications are generated [here](https://github.com/Expensify/App/blob/cbfccce7e7e585e12c630aacce010382ecd06734/src/libs/actions/Report.js#L1484-L1490), in `viewNewReportAction`
- The library that actually displays the notifications is [here](https://github.com/Expensify/App/blob/d3e1840a3bfa61599062442f7aae3e007e3893cf/src/libs/Notification/LocalNotification/BrowserNotifications.js)

Looking at recent changes to the latter, I don't think any of those changes are likely to cause the double-notifications we're seeing. I think it's more likely that `viewNewReportAction` is getting called twice in some context. Maybe we're double-triggering a `reportActions` Onyx update that's getting picked up and generating two notifications [here](https://github.com/Expensify/App/blob/cbfccce7e7e585e12c630aacce010382ecd06734/src/libs/actions/Report.js#L1513).

**Comment by mallenexpensify** [comment] 2022-06-27 22:29
For steps, it really is 'use app, have someone send you message, see two notifications'.  I'm still getting them now, Version 1.1.77-2 desktop. 

I'm going to post in #engineering in case someone has more info/thoughts.   If we think it can be an external issue, add `External` and a CM will get the job posted promptly.  I'd start it at $500 since it ~annoys me~ is annoying. 

Also, I've added this to the RCA sheet

**Comment by marcaaron** [comment] 2022-06-27 22:33
Agree with Rory's assessment as the most likely cause. We are sending both `reportComment` and `onyxApiUpdate` events  and they happen in close proximity so the "timestamp" test we're using won't work. Not sure what the best solution would be.

**Comment by marcaaron** [comment] 2022-06-27 22:35
I don't think there's anything an external contributor could do here and we can probably CP something to Web-Expensify to stop sending the `onyxApiUpdate` event for now which will give us some time to think about how to fix this.

**Comment by marcaaron** [comment] 2022-06-27 23:40
This should be back to normal soon for affected clients as soon as the PR hits prod.

Discussing solutions in [Slack](https://expensify.slack.com/archives/C03TQ48KC/p1656371221045389).

**Comment by mallenexpensify** [comment] 2022-06-28 00:24
Thanks for the super-dooper quick fix @marcaaron

**Comment by marcaaron** [comment] 2022-06-28 00:35
Anytime, and you're welcome! You can also thank me for breaking this 😅

**Comment by mallenexpensify** [comment] 2022-06-28 17:21
On Version 1.1.78-8  I'm mostly getting single notifications but have seen at least one double notification come through. 
Here's a janky vid showing a double from my test account to my main. When I tried to film a screen capture vid the notifications wouldn't show, so had to do on phone. Let me know if there's anything I can do to continue to help test

https://user-images.githubusercontent.com/22508304/176244267-a695c33e-71eb-4620-9e64-e79ff0ecfe37.MOV

**Comment by marcaaron** [comment] 2022-07-13 20:09
This should be fixed now. If anyone is experiencing this please try updating to the latest version of New Expensify.

**Closed by marcaaron** 2022-07-13 20:09 UTC
Labels: Engineering, Weekly, Internal, Overdue
