### ISSUE TITLE
[$500] Web - Report title vanishes after chat creation fails

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#27471] opened 2023-09-14 20:28 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Open the app on web.
2. Login with any user.
3. Go offline.
4. Create a new chat with `+74232323232`.
5. After chat is created and chat screen is opened, go online.
6. Observe that failed chat report in LHN.

## Expected Result:
Chat title should remain visible even after failure. we expect to remove the whole chat after user has cleared RBR error.

## Actual Result:
Chat title is removed from LHN while the failed chat is still visible to the user.

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [x] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 1.3.70.2
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/93399543/258314d5-36b1-4e76-9f3d-7b7955baacda

https://github.com/Expensify/App/assets/93399543/ee90d892-8a59-4caf-b222-722df4d6cd6e

**Expensify/Expensify Issue URL:**
**Issue reported by:** @parasharrajat
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1694550580877519

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~0157709def6ace3b8b</li>
        <li>Upwork Job ID: 1702419031354740736</li>
        <li>Last Price Increase: 2023-09-14</li>
    </ul>
</details>

**Comment by sakluger** [comment] 2023-09-18 07:48
Thanks @hungvu193, closing!

**Closed by sakluger** 2023-09-18 07:48 UTC
Labels: External, Daily, Help Wanted, Bug

**Comment by kaushiktd** [comment] 2023-09-18 09:15
### Please re-state the problem that we are trying to solve in this issue
Display Name vanishes after chat creation fails

### What is the root cause of that problem?
we are  encountering a synchronization issue where data from the server is overwriting new data that you've added when we regain internet connectivity.

### What changes do you think we should make in order to solve the problem?
To solve this problem conditionally set the displayName prop in DisplayNamesWithToolTip based on online/offline status using isOffline and name state. Here's a concise summary:
https://github.com/Expensify/App/blob/main/src/components/DisplayNames/DisplayNamesWithTooltip.js
```
const [name, setName] = useState('');

 const isOffline = useNetwork();
   useEffect(() => {
    // ...
    if (isOffline) {
        setName(props.fullTitle);
    }
}, [isOffline]);
```

and also add this in line no:66

`displayName={displayName || name}`

Video:-https://drive.google.com/file/d/14SEcbfChKY4j-rJpWkvbPENJ9LKB9yEb/view?usp=sharing
