### ISSUE TITLE
[$500] [Wave 6: Workspace Chat] GBR appears and disappears again after a refresh for the member.

### ISSUE THREAD

**Issue by Christinadobrzyn** [Expensify/App#33446] opened 2023-12-21 20:17 UTC
**Slack conversation:** https://expensify.slack.com/archives/C02MW39LT9N/p1703187894839509?thread_ts=1703187017.215259&cid=C02MW39LT9N

## Action Performed:

1. Sign-in for the first time using the member account
2. Verify that you land in the workspace chat
3. Go to global create (+) > Request money > enter an amount > confirm
4. Repeat Request Money > enter an amount > confirm (send it to the same contact)
• Verify that the request gets added to a new draft report and not the processing report awaiting approval
• Refresh the browser and notice the GBR disappears
• Refresh the browser > click on the IOU in the chat > click on the expense details > notice the GBR reappears when you click on the request

## Expected Result:

The GBR should always remain when a new IOU is created

## Actual Result:

The GBR appears and then disappears with a browser refresh 

## Screenshots/Videos

https://github.com/Expensify/App/assets/51066321/d2bf9aee-1de6-41e4-ba50-c0a8cd0088ec

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01ce44492032d68e4c</li>
        <li>Upwork Job ID: 1738195832282099712</li>
        <li>Last Price Increase: 2024-01-12</li>
    </ul>
</details>

**Comment by zanyrenney** [comment] 2023-12-22 13:52
adding external.

**Comment by zanyrenney** [comment] 2024-01-05 13:13
@parasharrajat, please can you review the proposal above?

**Comment by zanyrenney** [comment] 2024-01-11 11:47
thank you!

**Comment by techievivek** [comment] 2024-01-15 09:29
I will share this in wave 6 channel to see if someone would be interested in picking this up, thanks.

**Comment by techievivek** [comment] 2024-01-15 09:30
Shared here: https://expensify.slack.com/archives/C02MW39LT9N/p1705310992215509

**Comment by zanyrenney** [comment] 2024-01-15 11:41
tagged the team in the issue.

**Comment by zanyrenney** [comment] 2024-01-19 11:57
@parasharrajat still occuring for you? I cannot repro!

**Comment by zanyrenney** [comment] 2024-01-22 15:43
hey @Christinadobrzyn welcome back :) I can't reproduce this anymore. Can you? I asked @techievivek and @parasharrajat to try too. We're checking if this is still occurring. If not, we can close this out. I'm unassigning myself now though as we on't need two bug people.

**Comment by zanyrenney** [comment] 2024-01-22 15:43
Closing this out as I cannot reproduce this anymore, Please reopen if that is incorrect nd others can.

**Closed by zanyrenney** 2024-01-22 15:43 UTC
Labels: Engineering, Daily, Internal, Bug
