### ISSUE TITLE
[Needs regression test steps][$1000] Restricted access - The crash when navigate to the link https://staging.new.expensify.com/r/6821704960193694/details

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#13509] opened 2022-12-11 03:39 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Go to URL https://staging.new.expensify.com/
2. Login with any chat
3. Navigate to the link https://staging.new.expensify.com/r/6821704960193694/details

## Expected Result:
You're redirected to the concierge conversation

## Actual Result:
System is crashed

## Workaround:
Unknown

## Platform:

Where is this issue occurring?

- Web
- iOS
- Android
- Desktop App
- Mobile Web

**Version Number:** 1.2.38.0

**Reproducible in staging?:** Yes

**Reproducible in production?:** No

**Email or phone of affected tester (no customers):** 

**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Notes/Photos/Videos:** Any additional supporting documentation

https://user-images.githubusercontent.com/93399543/206885200-c6dee595-4747-4a83-8e31-41de87b1cdad.mp4

![image (2)](https://user-images.githubusercontent.com/93399543/206885210-e80ad94f-0b98-410c-af3f-b53a1081581b.png)

**Expensify/Expensify Issue URL:** 

**Issue reported by:** Applause - Internal Team

**Slack conversation:** 

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01342b9d79a0c15641</li>
        <li>Upwork Job ID: 1602317515226468352</li>
    </ul>
</details>

**Comment by situchan** [comment] 2022-12-11 04:40
### **Proposal**

This is a regression from #13398 
The crash happens when `report` is empty json: `{}` so `report.participants` is `undefined`
https://github.com/Expensify/App/blob/10dd188fea5793648da7dcf6d113361b35fed866/src/libs/ReportUtils.js#L476

**Solution:**
https://github.com/Expensify/App/blob/main/src/libs/ReportUtils.js#L438
```diff
function getIcons(report, personalDetails, policies, defaultIcon = null) {
-   if (!report) {
+   if (_.isEmpty(report)) {
        return [defaultIcon || getDefaultAvatar()];
    }
```

**Comment by CortneyOfstad** [comment] 2022-12-12 15:00
Was able to recreate on my side 👍

**Comment by chiragsalian** [comment] 2022-12-12 19:17
Removing external and help wanted labels. Normally for deploy blockers issues we try to handle them internally for speediness. If we use your solution @situchan we will compensate you.

**Comment by aldo-expensify** [comment] 2022-12-12 19:50
> ### **Proposal**
> This is a regression from #13398 The crash happens when `report` is empty json: `{}` so `report.participants` is `undefined`
> 
> https://github.com/Expensify/App/blob/10dd188fea5793648da7dcf6d113361b35fed866/src/libs/ReportUtils.js#L476
> 
> **Solution:** https://github.com/Expensify/App/blob/main/src/libs/ReportUtils.js#L438
> 
> ```diff
> function getIcons(report, personalDetails, policies, defaultIcon = null) {
> -   if (!report) {
> +   if (_.isEmpty(report)) {
>         return [defaultIcon || getDefaultAvatar()];
>     }
> ```

Thanks @situchan !, I'm wondering why there is a report `{}`, maybe we should fix that?

**Comment by situchan** [comment] 2022-12-12 20:11
> Thanks @situchan !, I'm wondering why there is a report {}, maybe we should fix that?

https://github.com/Expensify/App/blob/1c60740ac8eaf3882451facca05ce296161c0a5b/src/pages/ReportDetailsPage.js#L123
The crash happens on this line when user navigates to report detail page directly that they don't have access.
So `ReportDetailsPage` is rendered first before loading `report` data and quickly redirects to main page.
This is not avoidable case (anyone can visit any link on any browser).

Another solution is to render null before loading report data on `ReportDetailsPage` but I prefer above solution for safety (in case `ReportUtils.getIcons` is called in other pages).

**Comment by aldo-expensify** [comment] 2022-12-12 20:28
Still it may be worth to change the `!report` for safer `_.isEmpty(report)` checks, we have this in a few functions

**Comment by MonilBhavsar** [comment] 2022-12-12 20:29
I think I partially agree with @situchan on the cause. The root cause is correct but I don't think the proposed solution works. I feel like if empty report json is passed, we should just return early instead of rendering the component.

**Comment by situchan** [comment] 2022-12-12 20:34
Before that regression PR, it was supposed to return `[]` when `report` is `{}`

**Comment by aldo-expensify** [comment] 2022-12-12 20:36
> I think I partially agree with @situchan on the cause. The root cause is correct but I don't think the proposed solution works. I feel like if empty report json is passed, we should just return early instead of rendering the component.

Something like this? https://github.com/Expensify/App/pull/13528

**Comment by situchan** [comment] 2022-12-12 20:37
I think it's better to return empty array `[]`

**Comment by aldo-expensify** [comment] 2022-12-12 20:38
> I think it's better to return empty array `[]`

are we talking about the `getIcons` function?

**Comment by situchan** [comment] 2022-12-12 20:39
![image](https://user-images.githubusercontent.com/108292595/207149380-050aad04-fe2e-4028-a9f6-4a0882a51cd4.png)

This was original return (`sortedParticipants` is empty array when `report.participants` is `undefined`)

**Comment by youssef-lr** [comment] 2022-12-12 20:40
Ok this is code from the `production` branch, and it seems like it has always been like this, as in the report for a non existent chat was always `{}` but the error never got triggered because `_.map(report.participants...)` did not throw any error. So the switch now to use `report.participants.length` made the faulty check `!report` surface up. So I'm personally in favor of fixing this by using `!_.isEmpty`.


<img width="831" alt="Screenshot 2022-12-12 at 21 37 30" src="https://user-images.githubusercontent.com/9680864/207149369-3cc7f091-6011-4a21-9294-31d0f7a3341e.png">

**Comment by aldo-expensify** [comment] 2022-12-12 20:43
> as in the report for a non existent chat was always {} 

can you clarify this part? are we talking about what `WithReportOrNavigateHome` setting report to `{}`? I think it is better to fix it there, I don't think we should expect to be rendering fine a report `{}`. There are other parts of the code where this could also cause a crash:

https://github.com/Expensify/App/blob/ed6451885f7b251ac4b6d78adfadbbff3fab5f91/src/libs/OptionsListUtils.js#L479-L487

**Comment by youssef-lr** [comment] 2022-12-12 20:48
> can you clarify this part?

Yeah I was just confirming that this is what we've been doing before, the report that reaches `ReportDetailsPage` was an empty object if the chat is non-existent, it's just that before the code did not trigger the error because it relied on `_.map`. 

And I agree we shouldn't be trying to render that component if we don't have a chat for it. But this seems like out of scope for fixing this deploy blocker, maybe we can create a separate issue for it? Unless we can find an easy fix for it quickly.

**Comment by aldo-expensify** [comment] 2022-12-12 20:52
> Unless we can find an easy fix for it quickly.

I think the fix is easy: https://github.com/Expensify/App/pull/13528 (unless I'm missing something)

**Comment by aldo-expensify** [comment] 2022-12-12 20:52
> I suggest to apply both solutions:
> 
> * use `!_.isEmpty` in `getIcons` (for crash-free in case this function is called in any other references with bad report data)
> * early return null in withReportOrNavigateHome render (for rendering optimization)

This makes sense to me, I'm just not 100% convinced because it can also hide bugs... but I guess we prefer to hide an unexpected `{}` than crashing

**Comment by MonilBhavsar** [comment] 2022-12-12 20:56
I agree with @youssef-lr. Let's fix this issue for now and create a new performance issue to return early from HOC. @aldo-expensify you can then link this PR to that issue, if that sounds good?

**Comment by aldo-expensify** [comment] 2022-12-12 21:03
Okay then, lets play it safe and do the minimal/safest change to fix this deploy blocker

**Comment by aldo-expensify** [comment] 2022-12-12 21:11
Draft PR: https://github.com/Expensify/App/pull/13531, taking videos...

**Comment by aldo-expensify** [comment] 2022-12-12 21:17
Ready for review: https://github.com/Expensify/App/pull/13531

**Comment by chiragsalian** [comment] 2022-12-13 19:01
Qa tested the CP PR and its a pass, removing deploy blocker label.

**Comment by CortneyOfstad** [comment] 2022-12-16 20:46
Heading OoO for two weeks (over the payment date), so reassigning so it is not delayed 👍

**Comment by mallenexpensify** [comment] 2022-12-16 21:30
@eVoloshchak can you help me here... .I see two payment dates in the title, I reckon it's because there were two PRs that linked back to this one issue.  Should the payment date be Dec 22 or Dec 20? Thx

**Comment by eVoloshchak** [comment] 2022-12-17 09:33
@mallenexpensify, looks like https://github.com/Expensify/App/pull/13531 is the last PR to hit production, so the payment date should be Dec 22

**Comment by mallenexpensify** [comment] 2022-12-24 00:09
@eVoloshchak can you please accept the job and reply here once you have? https://www.upwork.com/jobs/~01342b9d79a0c15641

**Comment by situchan** [comment] 2022-12-24 00:31
I think I can get compensation based on [this comment](https://github.com/Expensify/App/issues/13509#issuecomment-1347142745) since I found the exact root cause and my [solution](https://github.com/Expensify/App/issues/13509#issuecomment-1345455874) was used.
cc: @aldo-expensify

**Comment by eVoloshchak** [comment] 2022-12-24 06:02
> @eVoloshchak can you please accept the job and reply here once you have? https://www.upwork.com/jobs/~01342b9d79a0c15641

I'm not eligible for any payment, the issue was handled internally, I didn't review any proposals or PRs

**Comment by mallenexpensify** [comment] 2022-12-27 00:00
Sorry @eVoloshchak , I think I checked your name in the upper right of the PR but didn't look for the ✔️ showing that you had reviewed the PR. 

@situchan , Aldo is out this week, I pinged our engineers who aren't out to see if anyone can give me a 👍 to pay.  Hopefully it won't be long

**Comment by youssef-lr** [comment] 2022-12-27 00:04
@mallenexpensify I can confirm we used @situchan solution in the PR.

**Comment by mallenexpensify** [comment] 2022-12-27 00:39
Thanks @youssef-lr !  I hired you for $1000 @situchan , can you please accept the job and reply here once you have? 
https://www.upwork.com/jobs/~01342b9d79a0c15641

**Comment by situchan** [comment] 2022-12-27 09:23
@mallenexpensify accepted. Thank you

**Comment by mallenexpensify** [comment] 2022-12-27 16:56
Paid @situchan , thanks!   Leaving issue open and weekly for regression test steps, cc @CortneyOfstad and @eVoloshchak (I think you _should_ be the one doing the engineering parts Eugene).  I'll try to help later this week @CortneyOfstad

**Comment by eVoloshchak** [comment] 2022-12-27 17:58
> Leaving issue open and weekly for regression test steps, cc @CortneyOfstad and @eVoloshchak (I think you _should_ be the one doing the engineering parts Eugene)

@mallenexpensify, not sure I understand correctly how this works for internal issues, I should be here in case some regressions arise, correct?

**Comment by mallenexpensify** [comment] 2022-12-27 21:02
@eVoloshchak , I'm unsure too, thanks for commenting. I hadn't taken into consideration `Internal` issues and what engineer is responsible for those.  I'm going to address in #contributor-plus, it's [here](https://expensify.slack.com/archives/C02NK2DQWUX/p1672173999496869)

**Comment by mallenexpensify** [comment] 2023-01-20 16:39
@eVoloshchak @MonilBhavsar @aldo-expensify This one slipped through the cracks cuz the `Reviewing` label kept it from going overdue.   Can one of you complete the top three steps here plz https://github.com/Expensify/App/issues/13509#issuecomment-1353792732

I'll get to the fourth, hopefully, today.

**Comment by aldo-expensify** [comment] 2023-01-21 04:28
Completed the first two, I'm not sure how to go about 3.

About the tests update, I'm missing if this was happened with any report / details, or if it happened only when accessing the specific report details: https://staging.new.expensify.com/r/6821704960193694/details (going to test this)

**Comment by aldo-expensify** [comment] 2023-01-21 04:36
@mvtglobally 👋 do you know if we have a test that opens the url of a report's details, but of a report that doesn't exists? It should be as simple as:

1. Open https://staging.new.expensify.com/r/6666666666666/details
2. Make sure that you get redirected to a conversation and the app doesn't crash

If we don't we can add it as a test 🤷 , what do you think @mallenexpensify

**Comment by mallenexpensify** [comment] 2023-01-23 16:44
@aldo-expensify is it "report that doesn't exist", one a user user doesn't have access to or both?
I did a quick search in TestRail for `report redirect` but couldn't find any relevant steps.  Any other terms I should check?

**Comment by mallenexpensify** [comment] 2023-01-23 17:39
I founds [this TestRail](https://expensify.testrail.io/index.php?/cases/view/1971180) that likely covers it if it's an access issue. Under the top link I could add https://staging.new.expensify.com/r/6666666666666/details if we know it's a non-existent report vs one a user doesn't have access to .

1. Navigate to the following link
- https://staging.new.expensify.com/r/6821704960193694
1. Verify you're redirected to a blank conversation with a message indicating that the user doesn't have access in web and to LHN in mobile view
2. Navigate to each of the following links
- https://staging.new.expensify.com/r/6821704960193694/details
- https://staging.new.expensify.com/r/6821704960193694/participants
- https://staging.new.expensify.com/r/6821704960193694/settings
1. Verify you're redirected to the concierge conversation in Web and to the LHN in mobile view in each

**Comment by aldo-expensify** [comment] 2023-01-25 00:09
> if we know it's a non-existent report vs one a user doesn't have access to .

I tested this a bit, an a report where the user doesn't have access and a report that doesn't exists leads to the same `report = {}`. So it can be either.

**Comment by mallenexpensify** [comment] 2023-01-25 02:00
Thanks @aldo-expensify , after reviewing again, I'm unsure if we need/want to update any of the steps. Checking in #qa
https://expensify.slack.com/archives/C9YU7BX5M/p1674611981896969

**Comment by aldo-expensify** [comment] 2023-01-25 16:49
> Thanks @aldo-expensify , after reviewing again, I'm unsure if we need/want to update any of the steps. Checking in #qa
https://expensify.slack.com/archives/C9YU7BX5M/p1674611981896969

Yep, I think the test without changes is fine to cover the case.

**Comment by mallenexpensify** [comment] 2023-01-27 01:55
Agreed, I'm going to close. 
Put another way... I think the existing steps would catch the bug if it occurred.

**Closed by mallenexpensify** 2023-01-27 01:55 UTC
Labels: Reviewing, Daily, Internal, Awaiting Payment, Bug
