### ISSUE TITLE
[$1000] Chat - When sending a message to the chat room, an error appears and the chat disappears

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#23397] opened 2023-07-22 15:41 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Open https://staging.new.expensify.com/
2. Click on the + button
3. Click on "New chat" in the action window
4. In the search bar, type "[workprofiletestuser@gmail.com"](mailto:workprofiletestuser@gmail.com%22)
5. Select "[workprofiletestuser@gmail.com"](mailto:workprofiletestuser@gmail.com%22)
from the list
6. If the chat is missing, repeat steps 2-5
7. Send any phrase to the chat that appears
8. Click on the chat with "Concierge"
9. Click on the chat with user "[workprofiletestuser@gmail.com"](mailto:workprofiletestuser@gmail.com%22)

## Expected Result:
When you create a new chat room and send a message, the chat room should display the message and the chat should be saved for further communication

## Actual Result:
When creating a new chat with the user "[workprofiletestuser@gmail.com"](mailto:workprofiletestuser@gmail.com%22)
and sending a message in the chat an error appears, after moving to another chat and returning to the chat with the user "[workprofiletestuser@gmail.com"](mailto:workprofiletestuser@gmail.com%22)
this chat disappears. When trying to create an initial chat with user "[workprofiletestuser@gmail.com"](mailto:workprofiletestuser@gmail.com%22)
- the chat disappears. It is necessary to repeat the steps to create a chat. But if you refresh the page after the first attempt to create a chat, the chat appears and everything works as intended

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [x] MacOS / Chrome 
- [ ] MacOS / Desktop

**Version Number:** 1.3.44.0

**Reproducible in staging?:** Yes

**Reproducible in production?:** Yes

**If this was caught during regression testing, add the test name, ID and link from TestRail:**

**Email or phone of affected tester (no customers):**

**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/78819774/8e61fa1c-ecf1-48c2-9f63-d435133f75cf

https://github.com/Expensify/App/assets/78819774/4c2afe9d-2681-4b93-a498-cee6fe2ab3eb

**Expensify/Expensify Issue URL:**

**Issue reported by:** Applause - Internal Team

**Slack conversation:**

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01fcb64ba2f2bd4abc</li>
        <li>Upwork Job ID: 1687631763673255936</li>
        <li>Last Price Increase: 2023-08-05</li>
    </ul>
</details>

**Comment by sakluger** [comment] 2023-07-25 02:10
@lanitochka17 this looks like a pretty bad bug and I've never seen it before for other accounts, but I was able to reproduce for this `workprofiletestuser@gmail.com` account. Are you able to reproduce with other accounts? I'm wondering if it's happening when you try to create a new chat with the secondary login of a phone number account.

**Comment by sakluger** [comment] 2023-07-27 23:36
Assigning to @lanitochka17 to answer my clarifying question.

**Comment by sakluger** [comment] 2023-08-01 16:01
Asked in Slack how to get in touch with @lanitochka17: https://expensify.slack.com/archives/C9YU7BX5M/p1690905690553929

**Comment by mvtglobally** [comment] 2023-08-01 18:36
@sakluger 
Tester tried using another accounts, e.g. [ustinovsergeyborisovich@gmail.com](mailto:ustinovsergeyborisovich@gmail.com) account and the problem was the same. Tester tried ustinovsergeyborisovich+******@gmail.com, the error did not occur. Only when tester sent a request for money to [workprofiletestuser@gmail.com](mailto:workprofiletestuser@gmail.com), the chat and the request disappear. 
issue is not consistent

**Comment by sakluger** [comment] 2023-08-05 01:08
Okay thanks for clarifying. It's strange that this one account would cause that issue, and I'm not really sure how to troubleshoot further, but I was able to reproduce the issue so I'm going to move it forward.

**Comment by nicookenny** [comment] 2023-08-05 02:42
Hi, hope you're doing well. I am trying to replicate the bug but with personal account is not possible. Could I get credentials for workprofiletestuser@gmail account so I could retry using that account?

Thank you.

**Comment by robertKozik** [comment] 2023-08-05 15:52
Hi @nicookenny I was able to reproduce this issue by sending the money request to `workprofiletestuser@gmail.com`. Did you try it this way?

**Comment by grimor** [comment] 2023-08-06 13:59
@robertKozik @nicookenny I can't reproduce it as well. I've tried creating a chat and making money request. I think @lanitochka17 need to verify if that problem still occur or provide more details on it.

**Comment by robertKozik** [comment] 2023-08-07 11:03
@grimor @nicookenny  I was able to reproduce it in the following steps:
1. Create the conversation with `workprofiletestuser@gmail.com`
2. Send message to him/her
3. Click `+` and then `request money`
4. Request money from `workprofiletestuser@gmail.com`
5. Created request displays error indicator on LHN
6. Clicking the request automatically redirects to concierge and removes the request

**Comment by StevenKKC** [comment] 2023-08-07 14:42
This is a BE issue.

After open report with `workprofiletestuser@gmail.com`, BE responds returns account information that does not have a `login` field.
![Screenshot 2023-08-07 103256](https://github.com/Expensify/App/assets/131836113/615a897f-e502-4fa4-aa1d-44bd12899d6e)

As a result, `RequestMoney` API does not have a `debtorEmail` parameter, and then BE returns an error.
https://github.com/Expensify/App/blob/8639fb6847cf20a5335d7f5e0c5329e8529b68c0/src/libs/actions/IOU.js#L317
https://github.com/Expensify/App/blob/8639fb6847cf20a5335d7f5e0c5329e8529b68c0/src/libs/actions/IOU.js#L425
![Screenshot 2023-08-07 103821](https://github.com/Expensify/App/assets/131836113/7a1de95f-e25d-48e2-9093-3487be469a79)

So the created money request displays error indicator on LHN, and if we click the request, BE responds as below.
![Screenshot 2023-08-07 104002](https://github.com/Expensify/App/assets/131836113/180e1ae1-bc73-4c3a-a480-f59907227f61)

Since the report is set to `null`, the app automatically redirects to concierge and the request is removed.

**Comment by sakluger** [comment] 2023-08-09 21:08
Hey @robertKozik, do you think that @StevenKKC's proposal correctly identifies the root cause and would it solve the issue?

**Comment by robertKozik** [comment] 2023-08-10 14:30
I need to double check @StevenKKC findings, but if they are right it's for sure backend issue. Will come back to confirm it

**Comment by robertKozik** [comment] 2023-08-10 22:08
Yes I can confirm the @StevenKKC assumption. I confired that the BE response on the `openReport` request does not have the login field. Moreover i've compared the `requestMoney` responses and the one after requesting from `workprofiletestuser@gmail.com` is not like the others (below the snippet)

```json
{
    "code": 666,
    "jsonCode": 666,
    "type": "Expensify\\Libs\\Error\\ExpError",
    "UUID": "F12EAA71-A469-4665-8125-D33131FDFA22",
    "message": "There is a previously existing chat between these users.",
    "title": "",
    "data": {
        "onyxData": [
            {
                "onyxMethod": "merge",
                "key": "report_3398409453345583",
                "value": {
                    "errorFields": {
                        "createChat": {
                            "1691704850496765": "There is a previously existing chat between these users."
                        }
                    }
                }
            }
        ]
    },
    "htmlMessage": "",
    "onyxData": [
        {
            "onyxMethod": "merge",
            "key": "report_3398409453345583",
            "value": {
                "errorFields": {
                    "createChat": {
                        "1691704850496765": "There is a previously existing chat between these users."
                    }
                }
            }
        },
        {
            "onyxMethod": "set",
            "key": "report_5141998720559394",
            "value": null
        },
        {
            "onyxMethod": "merge",
            "key": "report_3398409453345583",
            "value": {
                "errors": {
                    "1691704850496527": "There is a previously existing chat between these users."
                }
            }
        }
    ],
    "requestID": "7f4b8392c8460a58-AMS"
}
```

Because of that I'm thinking same as @StevenKKC that this issue has to be fixed on BackEnd side. 
@sakluger Can you make it internal?

**Comment by sakluger** [comment] 2023-08-10 22:15
Sure thing, thanks for reviewing!

**Comment by sakluger** [comment] 2023-08-10 22:17
Hmm, the internal label isn't adding an engineer. I'll add the engineering label too.

**Comment by MonilBhavsar** [comment] 2023-08-14 12:22
Looking today

**Comment by mvtglobally** [comment] 2023-08-16 20:43
Issue not reproducible during KI retests. (First week)

**Comment by sakluger** [comment] 2023-08-17 04:52
Thanks @mvtglobally - since this is no longer reproduceable, I'm going to close the issue.

**Closed by sakluger** 2023-08-17 04:52 UTC
Labels: Engineering, Daily, Internal, Overdue, Bug

**Comment by MonilBhavsar** [comment] 2023-08-17 06:30
The original issue is not reproducible, but this issue when requesting money is reproducible. We can log it and fix it https://github.com/Expensify/App/issues/23397#issuecomment-1673980574
