### ISSUE TITLE
[HOLD for payment 2023-09-20] [$1000] mWeb - Topbar color is different in LHN

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#23345] opened 2023-07-21 10:51 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Open App
2. Check the top bar  of LHN

## Expected Result:
Top bar colour should not be different on the sign up/in page.

## Actual Result:
Top bar colour is different

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [x] iOS / Safari
- [ ] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 1.3.43-2
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation

![IMG_3630](https://github.com/Expensify/App/assets/93399543/70bcc164-d640-4eb3-8447-e4cf3137a55e)

![IMG_6547](https://github.com/Expensify/App/assets/93399543/de12f00d-c29b-43e6-a0df-6678ee535e49)

**Expensify/Expensify Issue URL:**
**Issue reported by:** @niravkakadiya25
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1689856723308669

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~0107562926acd531ac</li>
        <li>Upwork Job ID: 1689496626413031424</li>
        <li>Last Price Increase: 2023-08-17</li>
<li>Automatic offers: </li>
<ul>
<li>niravkakadiya25 | Reporter | 26295148</li>
</ul></li>
    </ul>
</details>

**Comment by alitoshmatov** [comment] 2023-07-21 12:09
I think it is matching background color of the chat

**Comment by mallenexpensify** [comment] 2023-07-26 02:40
@shawnborton do know what expected behaviour is here?  I checked on new.dot and staging in Safari and, once signed in, the colors seem to match at the top.

**Comment by shawnborton** [comment] 2023-07-26 11:57
Yeah, we should update the color to match the page BG here.

**Comment by shawnborton** [comment] 2023-07-31 12:24
Not overdue. This is something we should fix. @mallenexpensify can you take it from here please? Thanks!

**Comment by mallenexpensify** [comment] 2023-08-10 04:41
Added `External` and updated the expected behaviour to 
- Top bar colour should not be different on the sign up/in page.

**Comment by Santhosh-Sellavel** [comment] 2023-08-10 22:39
@allroundexperts This promise seems to work well. 

```
 Navigation.isNavigationReady().then(() => {
      animateStatusBarBackgroundColor();
   });
```

And this [suggestion](https://github.com/Expensify/App/issues/23345#issuecomment-1672898370) kind of crashes the app on other platforms.


If we implemented your solution we won't need to call  `animateStatusBarBackgroundColor`  method [here](https://github.com/allroundexperts/Expensify/blob/be2c81fb1e0b27517451a6d00be097c8d3954ef6/src/libs/Navigation/NavigationRoot.js#L115) right or am I missing something?

Let me know, thanks!

**Comment by Santhosh-Sellavel** [comment] 2023-08-17 16:52
Somehow missed [this](https://github.com/Expensify/App/issues/23345#issuecomment-1674170559)

**Comment by Santhosh-Sellavel** [comment] 2023-08-21 16:04
Oops I missed posting this comment
@allroundexperts 

> > If we implemented your solution we won't need to call `animateStatusBarBackgroundColor` method [here](https://github.com/allroundexperts/Expensify/blob/be2c81fb1e0b27517451a6d00be097c8d3954ef6/src/libs/Navigation/NavigationRoot.js#L115) right or am I missing something?
> 
> We still need that. What I have suggested would execute just on the first render. Beyond that point, if someone navigates to other screens, we have to rely on `onStateChange` for triggering `animateStatusBarBackgroundColor`.

Can you share an example of where we require this?

Otherwise Looks good to me!

**Comment by Santhosh-Sellavel** [comment] 2023-08-22 18:12
Thanks @allroundexperts [proposal](https://github.com/Expensify/App/issues/23345#issuecomment-1645491438) looks good to me
C+ Reviewed
🎀 👀 🎀

**Comment by mallenexpensify** [comment] 2023-09-21 05:23
Issue reporter: @niravkakadiya25 paid $250 via Upwork
Contributor: @allroundexperts owed $500 via NewDot
Contributor+: @Santhosh-Sellavel owed $500 via NewDot. 

50% reduction in pay due to time between hiring and PR being merged. 
<img width="696" alt="image" src="https://github.com/Expensify/App/assets/22508304/6eef69b9-ee9e-4cb3-8ad4-d2233f416068">

<img width="799" alt="image" src="https://github.com/Expensify/App/assets/22508304/3f7713d7-1d06-499d-a25e-e68b3372ada9">

@allroundexperts please complete the BZ checklist above

**Comment by mountiny** [comment] 2023-09-25 14:23
@mallenexpensify in this case I agree that the penalty should not be put in place, we were not adding the bonuses and same should go for penalties so I would do the full price here

**Comment by mallenexpensify** [comment] 2023-09-29 16:50
Issue reporter: @niravkakadiya25 paid $250 via Upwork
Contributor: @allroundexperts owed $1000 via NewDot
Contributor+: @Santhosh-Sellavel owed $1000 via NewDot.

**Updated** based on Vit's [comment above](https://github.com/Expensify/App/issues/23345#issuecomment-1733816160)

Thanks @mountiny

**Closed by mallenexpensify** 2023-09-29 16:50 UTC
Labels: External, Daily, Design, Overdue, Awaiting Payment, Bug

**Comment by JmillsExpensify** [comment] 2023-10-05 13:20
$1,000 payment approved for @allroundexperts based on BZ summary.

**Comment by JmillsExpensify** [comment] 2023-12-11 01:11
$1,00o payment approved for @Santhosh-Sellavel based on BZ summary.
