### ISSUE TITLE
[HOLD for payment 2024-05-01] [$500] Workspace  – “Submitted $amount” system message appears for a moment when Employee submit IOU

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#38579] opened 2024-03-19 12:49 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.54-1
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**If this was caught during regression testing, add the test name, ID and link from TestRail:** https://expensify.testrail.io/index.php?/tests/view/4434476
**Email or phone of affected tester (no customers):** applausetester+jp_e_category@applause.expensifail.com
**Issue reported by:** Applause - Internal Team

## Action Performed:
1. Go to https://staging.new.expensify.com/
2. Log in as Employee of a Collect WS
3. Open WS chat and request a money
4. Open IOU and press Submit button in the header

## Expected Result:
“You submitted this report to Admin (email)” system message appears when Employee submit IOU

## Actual Result:
“Submitted $amount” system message appears for a moment when Employee submit IOU and then appears “You submitted this report to Admin (email)”

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [x] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details> 

https://github.com/Expensify/App/assets/78819774/27cf0e98-eb17-44e5-94e6-fe238e107bd7

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01304a705cb67bed22</li>
        <li>Upwork Job ID: 1770177446924410880</li>
        <li>Last Price Increase: 2024-03-19</li>
<li>Automatic offers: </li>
<ul>
<li>situchan | Reviewer | 0</li>
<li>FitseTLT | Contributor | 0</li>
</ul></li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @garrettmknight</details>

**Comment by garrettmknight** [comment] 2024-03-19 19:55
Confirmed the bug - I think it fits in #wave-collect.

**Comment by FitseTLT** [comment] 2024-03-19 20:10
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
Workspace – “Submitted $amount” system message appears for a moment when Employee submit IOU

### What is the root cause of that problem?
The optimistic submited report action contains `message`  with only one fragment of ` you submitted`
https://github.com/Expensify/App/blob/0d700c31dfadce758d4a623789e6bd1857573131/src/libs/actions/IOU.ts#L3893-L3894 
### What changes do you think we should make in order to solve the problem?

The optimistic submitted report action should have all the message fragments same as what the BE returns
like 
```
[
  {
    "type": "TEXT",
    "style": "strong",
    "text": "You"
  },
  {
    "type": "TEXT",
    "style": "normal",
    "text": " submitted this report"
  },
  {
    "type": "TEXT",
    "style": "normal",
    "text": " to "
  },
  {
    "type": "TEXT",
    "style": "strong",
    "text": "F A T (test.engfitsum@gmail.com)"
  }
]
```
### What alternative solutions did you explore? (Optional)

**Comment by iammudassirali** [comment] 2024-03-20 04:56
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
The issue involves a momentary display of the "Submitted $amount" system message when an Employee submits an IOU in the Expensify workspace. This message is unexpected and causes confusion among users.

### What is the root cause of that problem?
The root cause of this problem appears to be a timing issue in the system message display mechanism. It seems that the "Submitted $amount" message is briefly shown before being replaced by the correct "You submitted this report to Admin (email)" message.

### What changes do you think we should make in order to solve the problem?
To solve this issue, we need to adjust the timing or sequence of events related to the display of system messages when an IOU is submitted. This may involve modifying the backend logic or frontend rendering to ensure that the correct message is displayed immediately without any intermediate messages.

### What alternative solutions did you explore? (Optional)
An alternative solution could involve implementing a more robust message handling mechanism that prevents the display of any interim messages during the submission process. Additionally, we could explore optimizing the system response time to minimize the delay in displaying the correct message.

By addressing the timing issue and ensuring consistent messaging behavior, we can enhance the user experience and eliminate confusion during IOU submission in the Expensify workspace.

Please let me know if you need further clarification or assistance with implementing this solution.

Best regards,
**Mudassir Ali.**

**Comment by garrettmknight** [comment] 2024-03-21 20:22
@situchan can you take a look at these proposals when you get a chance?

**Comment by situchan** [comment] 2024-03-21 20:23
reviewing

**Comment by situchan** [comment] 2024-03-22 07:35
@FitseTLT's [proposal](https://github.com/Expensify/App/issues/38579#issuecomment-2008043289) looks good to me.
We need to make sure that optimistic message and server message are exactly the same, not only text but also style.
🎀 👀 🎀 C+ reviewed

<img width="677" alt="Screenshot 2024-03-22 at 1 34 26 PM" src="https://github.com/Expensify/App/assets/108292595/e2f6f852-0279-4701-a578-d8584a101eec">
<img width="677" alt="Screenshot 2024-03-22 at 1 34 31 PM" src="https://github.com/Expensify/App/assets/108292595/d8fe6245-92a6-44dc-b809-685f8980257b">

**Comment by FitseTLT** [comment] 2024-03-25 14:02
PR will be up in 3 days

**Comment by pecanoro** [comment] 2024-03-27 23:25
@FitseTLT Any updates?

**Comment by pecanoro** [comment] 2024-03-28 21:43
@FitseTLT friendly bump

**Comment by FitseTLT** [comment] 2024-03-29 07:10
will create it EOD

**Comment by DylanDylann** [comment] 2024-03-30 05:32
I can take over this issue as a C+ reviewer because @situchan is OOO in April

**Comment by mallenexpensify** [comment] 2024-04-01 16:35
@situchan is out OOO, reassigning a C+ via the auto-assigner for fairness.

**Comment by hungvu193** [comment] 2024-04-02 17:09
https://github.com/Expensify/App/pull/39321 is in review. I'll complete the checklist tomorrow morning.

**Comment by hungvu193** [comment] 2024-04-09 23:11
PR is in review

**Comment by garrettmknight** [comment] 2024-04-18 12:13
Still working through the PR

**Comment by pecanoro** [comment] 2024-04-26 13:13
Hmm,, it seems the automation didn't get triggered to update the title and payment

**Comment by garrettmknight** [comment] 2024-04-29 17:07
@hungvu193 had to send a new offer: https://www.upwork.com/nx/wm/offer/102083093

**Comment by hungvu193** [comment] 2024-04-29 22:15
> @hungvu193 had to send a new offer: https://www.upwork.com/nx/wm/offer/102083093

Accepted. Thank you!

**Comment by mvtglobally** [comment] 2024-05-01 14:00
Issue not reproducible during KI retests. (First week)

**Comment by garrettmknight** [comment] 2024-05-01 18:15
Payment summary:
- Contributor: @FitseTLT $500 paid via Upwork
- Reviewer: @hungvu193 $500 paid via Upwork

**Comment by garrettmknight** [comment] 2024-05-01 18:17
@hungvu193 please complete the checklist when you get a chance.

**Comment by hungvu193** [comment] 2024-05-02 01:47
-The PR that introduced the bug has been identified. Link to the PR: https://github.com/Expensify/App/pull/28947
- The offending PR has been commented on, pointing out the bug it caused and why, so the author and reviewers can learn from the mistake. Link to comment: https://github.com/Expensify/App/pull/28947/files#r1586975839
- A discussion in #expensify-bugs has been started about whether any other steps should be taken (e.g. updating the PR review checklist) in order to catch this type of bug sooner. Link to discussion: N/A
- Determine if we should create a regression test for this bug: No

This is a minor bug, so I don't think we need a regression test for it. Instead, we need to ensure that the optimistic data from the client matches what is returned from the server to avoid this kind of bug in the future.

**Comment by pecanoro** [comment] 2024-05-09 09:25
@garrettmknight All yours!

**Closed** 2024-05-09 10:43 UTC
Labels: External, Daily, Overdue, Awaiting Payment, Bug

**Comment by situchan** [comment] 2025-10-08 15:19
Am I eligible for partial compensation?
I fully reviewed proposals and 🎀 [here](https://github.com/Expensify/App/issues/38579#issuecomment-2014510534) and I went parental leave while [waiting](https://github.com/Expensify/App/issues/38579#issuecomment-2026787709) for PR to be raised.
