### ISSUE TITLE
[$500] IOU - Deleted IOU remains on participant's conversation

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#34756] opened 2024-01-18 19:31 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.27-0
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** Applause - Internal Team
**Slack conversation:**

## Action Performed:
1. User A create an IOU in a 1:1 conversation with User B
2. User A navigates to the IOU detail conversation
3. Delete Request

## Expected Result:
Request should be deleted also on participant's account

## Actual Result:
Deleted IOU remains on participant's conversation

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [x] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

https://github.com/Expensify/App/assets/93399543/38237cfe-bfd5-4a68-ae00-748e532d113c

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01bf06f0751327cf86</li>
        <li>Upwork Job ID: 1748065588983451648</li>
        <li>Last Price Increase: 2024-01-18</li>
    </ul>
</details>

**Comment by kbecciv** [comment] 2024-01-18 19:31
@Quintar - #vip-vsb

**Comment by s-alves10** [comment] 2024-01-18 19:58
This looks like a backend issue. No pusher events arrived

**Comment by isabelastisser** [comment] 2024-01-22 12:45
@s-alves10 can you please clarify what's next here? Thanks!

**Comment by s-alves10** [comment] 2024-01-22 12:46
I think this issue should be handled by backend team

**Comment by isabelastisser** [comment] 2024-01-22 12:50
@flodnv what do you think?

**Comment by flodnv** [comment] 2024-01-22 14:14
Sounds right 👍 I guess this belongs in #vip-split @GabiHExpensify

**Comment by isabelastisser** [comment] 2024-01-22 15:07
Posted [here.](https://expensify.slack.com/archives/C05RECHFBEW/p1705936028394199)

**Comment by cubuspl42** [comment] 2024-01-25 11:17
🎀 👀 🎀

**Comment by cubuspl42** [comment] 2024-01-25 11:18
@puneetlath 

No proposals, sounds like a backend issue

**Comment by flodnv** [comment] 2024-01-25 14:18
@cubuspl42 why did you trigger another assignment? I had already agreed it is a backend issue.

**Comment by cubuspl42** [comment] 2024-01-26 10:22
Sorry. I missed your comment.

As per "another" assignment, from my perspective you unassigned yourself and no internal engineer was assigned to this issue.

![image](https://github.com/Expensify/App/assets/2590174/6c5ce93b-3ffe-499d-b0c6-d51a599a4f18)

**Comment by puneetlath** [comment] 2024-01-26 16:59
For internal issues, we don't need to auto-assign an engineer. It'll get picked up as part of the VIP project.

**Comment by isabelastisser** [comment] 2024-01-29 14:31
Not overdue.

**Comment by isabelastisser** [comment] 2024-01-31 19:18
Not overdue; waiting for an engineer to pick this up.

**Comment by isabelastisser** [comment] 2024-02-02 01:40
No updates, waiting for wave 5.

**Comment by flodnv** [comment] 2024-02-02 13:58
Why is @isabelastisser assigned anyways? 😕

**Comment by mvtglobally** [comment] 2024-02-13 04:56
Issue not reproducible during KI retests. (First week)

**Comment by arielgreen** [comment] 2024-02-20 21:12
Looks like we can probably close. This should have a bugzero assignee. Throwing the label on so we can confirm this is no longer reproducible.

**Comment by strepanier03** [comment] 2024-02-26 17:05
I can't repro this so closing as suggested. THanks!

**Closed by strepanier03** 2024-02-26 17:05 UTC
Labels: Engineering, Daily, Internal, Overdue, Bug
