### ISSUE TITLE
[$250] Android - Chat - List of emoji suggestions aren't visible in the self DM with the ":" method

### ISSUE THREAD

**Issue by IuliiaHerets** [Expensify/App#47549] opened 2024-08-16 07:54 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 9.0.21-1
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**Issue reported by:**Applause Internal Team

## Action Performed:
1. Open the app
2. Log in with a new Gmail account
3. Open the self DM
4. Type ":smiley" into the composer

## Expected Result:
List of emoji suggestions should appear.

## Actual Result:
List of emoji suggestions aren't visible in the self DM with the ":" method. The emoji appears if you type in the full command ":smiley:".

## Workaround:
Unknown

## Platforms:

- [x] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [ ] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

https://github.com/user-attachments/assets/e85daac8-6833-48da-90cb-09a8a4af8669

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~012a74b5c5a5d9e16c</li>
        <li>Upwork Job ID: 1825625979735071754</li>
        <li>Last Price Increase: 2024-08-19</li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @allroundexperts</details>

**Comment by IuliiaHerets** [comment] 2024-08-16 07:54
We think that this bug might be related to #vip-vsb

**Comment by IuliiaHerets** [comment] 2024-08-16 07:54
@CortneyOfstad  FYI I haven't added the External label as I wasn't 100% sure about this issue. Please take a look and add the label if you agree it's a bug and can be handled by external contributors

**Comment by CortneyOfstad** [comment] 2024-08-19 20:08
Sorry, was OoO, but reviewing this now!

**Comment by CortneyOfstad** [comment] 2024-08-19 20:09
I had this issue on iPhone as well so got eyes on this!

**Comment by kubabutkiewicz** [comment] 2024-08-20 08:14
Hi! I am Jakub from Callstack - expert contributor group. I’d like to work on this job

**Comment by kubabutkiewicz** [comment] 2024-08-20 09:54
Hey, I started to invesitigate that and for me this seems to be working like that by design 
```
/**
 * Check if this piece of string looks like an emoji
 */
const isEmojiCode = (str: string, pos: number): boolean => {
    const leftWords = str.slice(0, pos).split(CONST.REGEX.SPECIAL_CHAR_OR_EMOJI);
    const leftWord = leftWords.at(-1) ?? '';
    return CONST.REGEX.HAS_COLON_ONLY_AT_THE_BEGINNING.test(leftWord) && leftWord.length > 2;
};```

we have this piece of code which is checking if the string provided to composer looks like an emoji and we are checking firstly if the string start with colon and then if the string have more then 3 letters. So now the question is what we want to do with it? Do nothing because it is done by purpose or we want to change it?

**Comment by CortneyOfstad** [comment] 2024-08-22 13:40
Thanks for looking into this @kubabutkiewicz! Going to close this as this appears to be by design. If the team decides to change this logic, we can definitely do that, but with VIP-VSB being such a low priority I don't see that happening now. 

Thanks again!

**Closed by CortneyOfstad** 2024-08-22 13:40 UTC
Labels: External, Daily, Help Wanted, Bug
