### ISSUE TITLE
[$500] Web - Reload on user profile page removes text in composer in group

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#29349] opened 2023-10-11 17:40 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.3.80.0
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** @dhanashree-sawant
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1696928138479079

## Action Performed:
1. Open the app
2. Click on plus and click on send message
3. Select few users to add to group and create group
4. Type in any message in composer
5. Click on group header and click on any user to open user profile page
6. Reload on profile page and observe that app removes text from composer added in step 4

## Expected Result:
App should not remove text from composer automatically

## Actual Result:
App removes text from composer automatically when we type something in group, open any group member profile page and reload

## Workaround:
Unknown 

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos
<details>
<summary>Android: Native</summary>

</details>

<details>
<summary>Android: mWeb Chrome</summary>

</details>

<details>
<summary>iOS: Native</summary>

</details>

<details>
<summary>iOS: mWeb Safari</summary>

</details>

<details>
<summary>MacOS: Chrome / Safari</summary>

 

https://github.com/Expensify/App/assets/93399543/6a4673d4-a055-41f0-971a-c37d1abebcb5

https://github.com/Expensify/App/assets/93399543/72834086-5b8e-4484-9319-e71b7757808d

https://github.com/Expensify/App/assets/93399543/aa82522c-2033-460a-8eda-a77d2091ba59

</details>

<details>
<summary>MacOS: Desktop</summary>

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01a06d741d7592e31f</li>
        <li>Upwork Job ID: 1712161300047749120</li>
        <li>Last Price Increase: 2023-11-01</li>
    </ul>
</details>

**Comment by graylewis** [comment] 2023-10-11 18:19
### Proposal
Please re-state the problem that we are trying to solve in this issue.
Reloading on a user's profile page while using the composer on the report view clears the composer 

### What is the root cause of that problem?
The ComposerWithSuggestions component uses an initializer function which is only run once, e.g. `const [value, setValue] = useState(() => // Function that returns an initial value and is only run once`. This function calls getDraftComment() with the reportID supplied to it as props. When the composer is in the background, it is lazy loaded, meaning that the initial value that is computed is null because the default ReportID is 0. Ideally, useState would detect this change and reinitialize the value, but since the function is only run once it misses the change.

### What changes do you think we should make in order to solve the problem?
Instead of computing the initial value in a one-shot callback function, we initialize the value to an empty string and then use a useEffect function with the reportID in its dependency array to update the value whenever the reportID is updated. function. That means that once the reportID is lazy loaded, the change will be detected and the composer will be initialized with the proper value. 

What alternative solutions did you explore?
N/A

**Comment by redpanda-bit** [comment] 2023-10-12 02:49
## Proposal

if you are satisfied with proposal above feel free to omit this one. This proposal is a perspective different from using a useEffect hook.

### Please re-state the problem that we are trying to solve in this issue.
Draft comment is lost when refreshing from user profile page.

### What is the root cause of that problem?
Report screen initially renders when reportID is `null` and due to this the Composer is not able to retrieve the correct draft comment from storage. More specifically, reportID = null stems from the navigation missing reportID in the navigation params which is being queried here (line 130):

https://github.com/Expensify/App/blob/633c94b9a4793230b06fd5a89cb1a5f7239c329a/src/pages/home/ReportScreen.js#L129-L131

In addition, the reportID is neither found in the `initialParams` object. [This react-navigation prop (initialParams)](https://reactnavigation.org/docs/screen/#initialparams), is specific for these use cases – needing data as soon as possible.

Once again, when page is loaded, reportID=null > initial value for the composer is set to empty (below) since no draft comment was found. Below is where the draft comment is searched for and not found:

https://github.com/Expensify/App/blob/aff40fe54218d196f620d983cf9acb6d6c73bba8/src/pages/home/report/ReportActionCompose/ComposerWithSuggestions.js#L106-L112

### What changes do you think we should make in order to solve the problem?

We should find the last accessed report, get the reportID and add it to the `initialParams` object of CentralPaneNavigator.js:

https://github.com/Expensify/App/blob/aff40fe54218d196f620d983cf9acb6d6c73bba8/src/libs/Navigation/AppNavigator/Navigators/CentralPaneNavigator.js#L21

The changes would happen in [ReportUtils.js](https://github.com/Expensify/App/blob/main/src/libs/ReportUtils.js#L541) and [CentralPaneNavigator.js](https://github.com/Expensify/App/blob/main/src/libs/Navigation/AppNavigator/Navigators/CentralPaneNavigator.js):

```js
// ReportUtils.js
const lastAccessedReport = () => findLastAccessedReport(allReports, false, false, false); // add this 

// CentralPaneNavigator.js
const lastReport = ReportUtils.lastAccessedReport(); // add this

function CentralPaneNavigator() {
// ...
    <Stack.Screen
        name={SCREENS.REPORT}
        initialParams={{
            openOnAdminRoom: openOnAdminRoom ? 'true' : undefined,
            reportID: lodashGet(lastReport, 'reportID', undefined), // add this
        }}
    />
// ...
}
```

This way the root cause of having reportID = null would be addressed and the report would be ready for display faster also, no need to wait for useEffect to be triggered **and then** trigger another render.

**Comment by redpanda-bit** [comment] 2023-10-12 02:50
## Proposal

if you are satisfied with proposal above feel free to omit this one. This proposal is a perspective different from using a useEffect hook.

### Please re-state the problem that we are trying to solve in this issue.
Draft comment is lost when refreshing from user profile page.

### What is the root cause of that problem?
Report screen initially renders when reportID is `null` and due to this the Composer is not able to retrieve the correct draft comment from storage. More specifically, reportID = null stems from the navigation missing reportID in the navigation params which is being queried here (line 130):

https://github.com/Expensify/App/blob/633c94b9a4793230b06fd5a89cb1a5f7239c329a/src/pages/home/ReportScreen.js#L129-L131

In addition, the reportID is neither found in the `initialParams` object. [This react-navigation prop (initialParams)](https://reactnavigation.org/docs/screen/#initialparams), is specific for these use cases – needing data as soon as possible.

Once again, when page is loaded, reportID=null > initial value for the composer is set to empty (below) since no draft comment was found. Below is where the draft comment is searched for and not found:

https://github.com/Expensify/App/blob/aff40fe54218d196f620d983cf9acb6d6c73bba8/src/pages/home/report/ReportActionCompose/ComposerWithSuggestions.js#L106-L112

### What changes do you think we should make in order to solve the problem?

We should find the last accessed report, get the reportID and add it to the `initialParams` object of CentralPaneNavigator.js:

https://github.com/Expensify/App/blob/aff40fe54218d196f620d983cf9acb6d6c73bba8/src/libs/Navigation/AppNavigator/Navigators/CentralPaneNavigator.js#L21

The changes would happen in [ReportUtils.js](https://github.com/Expensify/App/blob/main/src/libs/ReportUtils.js#L541) and [CentralPaneNavigator.js](https://github.com/Expensify/App/blob/main/src/libs/Navigation/AppNavigator/Navigators/CentralPaneNavigator.js):

```js
// ReportUtils.js
const lastAccessedReport = () => findLastAccessedReport(allReports, false, false, false); // add this 

// CentralPaneNavigator.js
const lastReport = ReportUtils.lastAccessedReport(); // add this

function CentralPaneNavigator() {
// ...
    <Stack.Screen
        name={SCREENS.REPORT}
        initialParams={{
            openOnAdminRoom: openOnAdminRoom ? 'true' : undefined,
            reportID: lodashGet(lastReport, 'reportID', undefined), // add this
        }}
    />
// ...
}
```

This way the root cause of having reportID = null would be addressed and the report would be ready for display.

**Comment by yh-0218** [comment] 2023-10-12 18:38
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
Web - Reload on user profile page removes text in composer in group
### What is the root cause of that problem?
At first time, `reportID` is 0.
https://github.com/Expensify/App/blob/f5578523a10653b03de827e38f99f3ba54241a69/src/pages/home/report/ReportActionCompose/ComposerWithSuggestions.js#L106-L107
So value is set null.
After some delay `reportID` is set correct value.
https://github.com/Expensify/App/blob/f5578523a10653b03de827e38f99f3ba54241a69/src/pages/home/report/ReportActionCompose/ComposerWithSuggestions.js#L563
By this, comment is updated.
### What changes do you think we should make in order to solve the problem?
We need to remove delay of `reportID`
https://github.com/Expensify/App/blob/f5578523a10653b03de827e38f99f3ba54241a69/src/pages/home/report/ReportFooter.js#L64
We can update like this
```
const hideComposer = ReportUtils.shouldDisableWriteActions(props.report)|| props.report.reportID === '0';
```
### What alternative solutions did you explore? (Optional)

**Comment by jliexpensify** [comment] 2023-10-17 03:19
Bump @0xmiroslav for reviews please!

**Comment by dhanashree-sawant** [comment] 2023-10-19 06:15
For me, whenever I kept group chat in top in LHN, I was able to recreate it everytime.

**Comment by dhanashree-sawant** [comment] 2023-10-21 05:17
Sure, here is the video with new account

https://github.com/Expensify/App/assets/87513216/10863b31-7813-488b-876f-65be2712b370

**Comment by jliexpensify** [comment] 2023-10-22 02:37
@0xmiroslav I am unable to reproduce on v1.3.88-3

https://github.com/Expensify/App/assets/30815269/ed6a8554-04d2-4536-9808-d3f38ebce7db

@dhanashree-sawant what version are you on? Also, can you repro with more than 1 person? The original videos had multiple in the group.

**Comment by dhanashree-sawant** [comment] 2023-10-22 04:38
Hi @jliexpensify, tested on v1.3.88-3 with multiple users in group. I am still able to reproduce.

https://github.com/Expensify/App/assets/87513216/ef677682-f2d6-45b1-812e-09fc601e18c7

**Comment by jliexpensify** [comment] 2023-10-24 05:50
Hmm wow so in testing this again in Staging .v90, I think I discovered a new bug: when you refresh, a completely different page (i.e. not the group chat) loads. Here's a video:

https://github.com/Expensify/App/assets/30815269/a23b13cb-f2cf-4aae-b6de-611c3d54edd4

@0xmiroslav @dhanashree-sawant can you test and see if you can also replicate this issue?

**Comment by jliexpensify** [comment] 2023-10-26 03:23
Still seeing the same [issue](https://github.com/Expensify/App/issues/29349#issuecomment-1776574661) - @dhanashree-sawant @kbecciv @0xmiroslav can you verify?

**Comment by jliexpensify** [comment] 2023-10-26 04:38
I can't repro what @dhanashree-sawant is seeing. If @kbecciv can't repro, I vote that we close this issue and make a new issue for what is reported [here](https://github.com/Expensify/App/issues/29349#issuecomment-1765797908).

**Comment by mvtglobally** [comment] 2023-11-02 03:32
Issue not reproducible during KI retests. (First week)

**Comment by jliexpensify** [comment] 2023-11-02 04:16
Great, going to close this one out then + due to the lack of responses from everyone else.

**Closed by jliexpensify** 2023-11-02 04:16 UTC
Labels: External, Engineering, Daily, Help Wanted, Bug

**Comment by dhanashree-sawant** [comment] 2023-11-02 05:21
Hi @jliexpensify, sorry I just saw all the messages. The key is to ensure that group chat is first in LHN else it will open new chat on reload, this is testing video on latest staging

https://github.com/Expensify/App/assets/87513216/e0384b4d-29e1-4c38-85b3-c7b59d059714

**Comment by jliexpensify** [comment] 2023-11-02 05:37
@dhanashree-sawant I have tested on my end, with your new instructions - I still cannot reproduce. However, I can [reproduce this issue consistently](https://github.com/Expensify/App/issues/29349#issuecomment-1765797908), and I think a new GH needs to be opened.

**Comment by dhanashree-sawant** [comment] 2023-11-02 05:47
Yes even I could reproduce that issue. Thanks for testing again.

**Comment by jliexpensify** [comment] 2023-11-02 05:59
No worries! I have created a bug report for the new issue here - https://expensify.slack.com/archives/C049HHMV9SM/p1698904742009159
