### ISSUE TITLE
[HOLD for payment 2024-06-28] [HOLD for payment 2024-06-20] [HOLD for payment 2024-06-18] [$250] Split scan- Error message only changes after clicking Split expense button for the second time

### ISSUE THREAD

**Issue by m-natarajan** [Expensify/App#41336] opened 2024-04-30 14:10 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.68-0
**Reproducible in staging?:** Yes
**Reproducible in production?:** Yes
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** Applause Internal Team
**Slack conversation:**

## Action Performed:
1. Go to staging.new.expensify.com
2. Go to workspace chat.
3. Go to + > Split expense.
4. Create a scan split expense with an invaid receipt.
5. Wait for the scanning to fail.
6. When the scanning fails, click on the split preview.
7. Click Split expense.
8. Click Split expense again.

## Expected Result:
When clicking Split expense for the first time, the error message should turn to "Transaction is missing fields".

## Actual Result:
When clicking Split expense for the first time, the error message remains the same.
Only when clicking on the same button for the second time, the error message turns to "Transaction is missing fields".

## Workaround:
Unknown
## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [X] Android: Native
- [X] Android: mWeb Chrome
- [X] iOS: Native
- [X] iOS: mWeb Safari
- [X] MacOS: Chrome / Safari
- [X] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

https://github.com/Expensify/App/assets/38435837/fc99770a-3f5f-4f32-b168-9b31a372251b

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~012c836450a7395578</li>
        <li>Upwork Job ID: 1787821258983333888</li>
        <li>Last Price Increase: 2024-05-07</li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @miljakljajic</details>

**Comment by m-natarajan** [comment] 2024-04-30 14:10
@miljakljajic FYI I haven't added the External label as I wasn't 100% sure about this issue. Please take a look and add the label if you agree it's a bug and can be handled by external contributors.

**Comment by m-natarajan** [comment] 2024-04-30 14:11
We think this bug might be related to #vip-split

**Comment by nkdengineer** [comment] 2024-05-07 12:42
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
When clicking Split expense for the first time, the error message remains the same.
Only when clicking on the same button for the second time, the error message turns to "Transaction is missing fields".

### What is the root cause of that problem?
In [here](https://github.com/Expensify/App/blob/9cad71513fc52ab0cfd5ca5a5434770eb6eec7a7/src/components/MoneyRequestConfirmationList.tsx#L663), we will early return if there's a `formError`. In the case where the receipt scanning failed, the `formError` will indicate that, so when pressing `Split expense`, it will not show the `Transaction is missing fields` error [here](https://github.com/Expensify/App/blob/9cad71513fc52ab0cfd5ca5a5434770eb6eec7a7/src/components/MoneyRequestConfirmationList.tsx#L684). Only in the second time when the `formError` was already cleared, it will show `Transaction is missing fields` error.

### What changes do you think we should make in order to solve the problem?

Move the error setting logic [here](https://github.com/Expensify/App/blob/main/src/components/MoneyRequestConfirmationList.tsx#L679-L688) to [here](https://github.com/Expensify/App/blob/9cad71513fc52ab0cfd5ca5a5434770eb6eec7a7/src/components/MoneyRequestConfirmationList.tsx#L662)
```
if (iouType !== CONST.IOU.TYPE.PAY) {
    ... check and set error
}
```

### What alternative solutions did you explore? (Optional)
NA

**Comment by rushatgabhane** [comment] 2024-05-08 23:11
https://github.com/Expensify/App/blob/192bb56ef3578a898d379bd1c95762621f95e410/src/components/MoneyRequestConfirmationList.tsx#L675

I don't know why we're using `else` here. Seems like a straightfoward fix to me.

C+ reviewed 🎀 👀 🎀 @nkdengineer's [proposal](https://github.com/Expensify/App/issues/41336#issuecomment-2098318729)

**Comment by miljakljajic** [comment] 2024-05-15 07:34
still reviewing

**Comment by miljakljajic** [comment] 2024-05-15 07:36
@rushatgabhane are you happy with the solution?

**Comment by mvtglobally** [comment] 2024-05-22 04:39
Issue not reproducible during KI retests. (First week)

**Comment by nkdengineer** [comment] 2024-05-22 04:57
@rushatgabhane  this [PR](https://github.com/Expensify/App/pull/42450) is ready to preview

**Comment by nkdengineer** [comment] 2024-06-10 04:28
@rushatgabhane we have a new PR [here](https://github.com/Expensify/App/pull/43342)

**Comment by miljakljajic** [comment] 2024-06-19 15:05
Sent offer to @nkdengineer 

Payment summary for @rushatgabhane -

@rushatgabhane is owed 250 USD for their work on this issue

**Comment by rushatgabhane** [comment] 2024-06-19 19:23
1. The PR that introduced the bug has been identified. Link to the PR: https://github.com/Expensify/App/pull/40386

2. The offending PR has been commented on, pointing out the bug it caused and why, so the author and reviewers can learn from the mistake. Link to comment: https://github.com/Expensify/App/pull/40386/files#r1646619910

3. A discussion in #expensify-bugs has been started about whether any other steps should be taken (e.g. updating the PR review checklist) in order to catch this type of bug sooner. Link to discussion: N.A. 

4. Determine if we should create a regression test for this bug. - No. Really minor and insignificant bug

5. If we decide to create a [regression test](https://github.com/Expensify/App/blob/main/contributingGuides/REGRESSION_TEST_BEST_PRACTICES.md) for the bug, please propose the regression test steps to ensure the same bug will not reach production again - N.A.

**Comment by miljakljajic** [comment] 2024-06-21 09:43
@nkdengineer please accept the offer so I can pay you and close this out

**Comment by JmillsExpensify** [comment] 2024-06-23 15:59
BZ checklist already completed above. $250 approved for @rushatgabhane

**Comment by miljakljajic** [comment] 2024-06-25 12:51
@nkdengineer paid - closing out

**Closed by miljakljajic** 2024-06-25 12:51 UTC
Labels: External, Weekly, Awaiting Payment, Bug
