### ISSUE TITLE
Searching for workspace does not work when you write the full word(workspace)

### ISSUE THREAD

**Issue by mvtglobally** [Expensify/App#24433] opened 2023-08-11 15:12 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Open search tab
2. Search for workspace

## Expected Result:
The search result should show the results of the search for workspace.

## Actual Result:
The search result works fine until you write the last letter of workspace(letter e).

## Workaround:
unknown 

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [X] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [X] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 1.3.51-2
**Reproducible in staging?:** Y 
**Reproducible in production?:** Y 
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation 

https://github.com/Expensify/App/assets/43995119/a2413187-52c3-4a35-a6ca-9f7323d0805f

https://github.com/Expensify/App/assets/43995119/7b91b3e5-0073-469a-9b5c-14043696303e

**Expensify/Expensify Issue URL:**
**Issue reported by:** @jo-ui
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1691010591893369 

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by mvtglobally** [comment] 2023-08-11 15:12
We are not able to reproduce consistently. Please double check

**Comment by Talha345** [comment] 2023-08-11 18:07
Unable to reproduce!

**Comment by flaviadefaria** [comment] 2023-08-15 11:43
I also can't recreate it so closing this.

**Closed by flaviadefaria** 2023-08-15 11:43 UTC
Labels: Daily, Needs Reproduction, Overdue, Bug

**Comment by jo1290** [comment] 2023-08-15 14:02
@flaviadefaria it is still reproducible on most of the platforms try it again

**Comment by Talha345** [comment] 2023-08-15 14:08
> @flaviadefaria it is still reproducible on most of the platforms try it again

Can you please share the platforms and respective videos?

**Comment by jo1290** [comment] 2023-08-15 14:19
https://github.com/Expensify/App/assets/129380070/7de45eaa-fa8d-4729-8cdf-7036f78c4ab2


https://github.com/Expensify/App/assets/129380070/d51d8586-e3ed-410b-87c0-6ce740a3d186

https://github.com/Expensify/App/assets/129380070/96796c6f-3aba-42a0-834d-76c291795a4d

**Comment by Talha345** [comment] 2023-08-15 14:31
> workspace_search.mp4 
>  workspace_search_new.mp4 
>  20230815_171741.mp4

I tried with multiple accounts,still unable to reproduce.
Can you try with a different account after clearing your cache.

**Comment by jo1290** [comment] 2023-08-16 14:06
@Talha345 @flaviadefaria any updates?

**Comment by jo-ui** [comment] 2023-08-21 10:30
@flaviadefaria It is still reproducible consider it as an issue
