### ISSUE TITLE
[HOLD for C+ newdot payment] [$1000] Web - Bank - Error message 'bank account should end with 1111' disappears after blurring the routing number input field

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#21838] opened 2023-06-28 20:23 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Go to staging.new.expensify.com
2. Go to Settings > Workspace > Bank account > Connect with plaid method > Chase Bank
3. Use the following credentials for Chase Bank
Username: user_good
Password: pass_good
4. If a verification is prompted - select mobile and enter "credentials_good" as the verification mode
5. Checkmark the "Plaid Checking" and "Plaid Saving" and the last 2 options.
6. Click on continue
7. Check the T&C and click "Connect account information"
8. Click on the last confirmation on the plaid modal
9. Select the bank account ending in 1111
10. Enter Routing Number: 011401533 an enter an incorrect bank account number (e.g 1111222233334444)
11. Blur or take the focus away from the routing number input field by clicking outside of it or switching the tabs.

## Expected Result:
The error message 'Your account number should end with 1111' should not disappear

## Actual Result:
The error message 'Your account number should end with 1111' disappears after switching tab. The issue is still reproduced after the page is refreshed

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [x] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 1.3.34.1

**Reproducible in staging?:** Yes

**Reproducible in production?:** N/A

**If this was caught during regression testing, add the test name, ID and link from TestRail:**

**Email or phone of affected tester (no customers):**

**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/78819774/9fe1dfe1-d313-47e8-be45-d2d69a615df9

![Bug6110088_bandicam_2023-06-29_04-05-10-131](https://github.com/Expensify/App/assets/78819774/e1dbe42d-6db0-4dc7-b845-0c29189686f0)

**Expensify/Expensify Issue URL:**

**Issue reported by:** Applause - Internal Team

**Slack conversation:**

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01964ffb3d42e77df4</li>
        <li>Upwork Job ID: 1674308097839382528</li>
        <li>Last Price Increase: 2023-08-10</li>
<li>Automatic offers: </li>
<ul>
<li>hungvu193 | Contributor | 26383005</li>
</ul></li>
    </ul>
</details>

**Comment by kadiealexander** [comment] 2023-06-29 06:45
Repro'd:

https://github.com/Expensify/App/assets/59587260/7c96376c-128f-42ee-96ed-59f2d488fe22

**Comment by kadiealexander** [comment] 2023-07-04 06:16
@eVoloshchak please review the proposal [here](https://github.com/Expensify/App/issues/21838#issuecomment-1612263965) as a priority.

**Comment by joh42** [comment] 2023-07-04 12:58
Contributor details
Your Expensify account email: expensify@johannes.software
Upwork Profile Link: https://www.upwork.com/freelancers/~01c600f0d690c3dfe1

**Comment by eVoloshchak** [comment] 2023-07-04 13:44
I think we should proceed with @joh42's [proposal](https://github.com/Expensify/App/issues/21838#issuecomment-1620203806)
While the root cause is obviously the same in both proposals, @joh42's proposal is universal, we'll ensure the same problem isn't present on any other pages that use Form. 
> We only need to revalidate values on blur if changes have been made

> Additionally, we might want to add a prop called something like onlyValidateChanges which defaults to false, to make sure no other forms are affected by this change.

I think we should implement this behavior as default for all forms, but we can work this out via discussion on slack in case we  decide to implement this

🎀👀🎀 C+ reviewed!
cc: @kadiealexander

**Comment by kadiealexander** [comment] 2023-07-04 23:21
Getting an engineer assigned - unsure why it didn't happen automatically!

**Comment by kadiealexander** [comment] 2023-07-07 02:17
@techievivek could you please do a final review and decide if we should assign @joh42?

**Comment by techievivek** [comment] 2023-07-10 13:19
The [proposal](https://github.com/Expensify/App/issues/21838#issuecomment-1620203806) looks good to me.

> I think we should implement this behavior as default for all forms, but we can work this out via discussion on slack in case we decide to implement this

@eVoloshchak Would you mind initiating the conversation on Slack to ensure that everyone is on the same platform before we move with a PR? Thanks

**Comment by joh42** [comment] 2023-07-10 15:06
Thanks for the reviews. This is my profile if you want to @ me on Slack: https://app.slack.com/client/T03SC9DTT/C049HHMV9SM/rimeto_profile/U05FUG2UHQQ

**Comment by eVoloshchak** [comment] 2023-07-12 20:09
Oops, missed this one, apologies
Will spin up the conversation on Slack tomorrow

**Comment by joh42** [comment] 2023-07-14 09:11
Okay, let's [implement this for all forms](https://expensify.slack.com/archives/C01GTK53T8Q/p1689269225988629?thread_ts=1689265381.709579&cid=C01GTK53T8Q). Should the [form docs](https://github.com/Expensify/App/blob/main/contributingGuides/FORMS.md#validate-on-blur-on-change-and-submit) be updated to reflect this change?

@eVoloshchak @techievivek

**Comment by eVoloshchak** [comment] 2023-07-16 22:52
> Should the [form docs](https://github.com/Expensify/App/blob/main/contributingGuides/FORMS.md#validate-on-blur-on-change-and-submit) be updated to reflect this change?

@joh42, yes, we need to update the doc, it currently says
> When the form field loses focus (blur) we will run that validate test and show feedback 

We can add something like this, not sure how to phrase that properly
_(we don't run validate test if the data hasn't changed since we last ran it)_

**Comment by joh42** [comment] 2023-07-17 09:26
> We can add something like this, not sure how to phrase that properly _(we don't run validate test if the data hasn't changed since we last ran it)_

Perhaps we can add this to the end of that paragraph: _To prevent server errors from being cleared inadvertently, we only run validation on blur if any form data has changed since the last validation/submit_.

Other than that, is there anything else that needs to be done before we can start tackling this issue?

**Comment by joh42** [comment] 2023-07-17 14:16
Ping @eVoloshchak

**Comment by kadiealexander** [comment] 2023-07-20 02:48
@techievivek should we go ahead with @joh42?

**Comment by techievivek** [comment] 2023-07-20 04:38
Yes, it looks like we have agreed to fix the behaviour on all the form's usages. Going to assign the job to @joh42

**Comment by joh42** [comment] 2023-07-20 08:16
Thanks, applied to the Upwork job. If everything goes according to plan you can expect a PR later today.

**Comment by joh42** [comment] 2023-07-20 09:04
Btw this is the proposal https://www.upwork.com/ab/proposals/1681940855075270657 @techievivek / @kadiealexander (unsure who handles hiring)

**Comment by joh42** [comment] 2023-07-20 13:41
Just an update, PR will be ready tomorrow (21st of July 2023)

**Comment by joh42** [comment] 2023-07-20 20:06
Also, FYI, the error I get today, even on staging, is "An unexpected error occurred while trying to add your bank account. Please try again." as opposed to "Your account number should end with 1111".
![image](https://github.com/Expensify/App/assets/138504087/1f4853a0-a87f-4938-8fe5-18b2f3c76347)

This issue pertains to all server errors however, so even if the actual error we see now is not the same as when the issue was created, the solution is still the same.

**Comment by joh42** [comment] 2023-07-21 14:19
Another update: I'm having some trouble testing on Mac, I'll hopefully have the PR ready for review sometime during the weekend

**Comment by joh42** [comment] 2023-07-24 14:02
PR is now ready for review https://github.com/Expensify/App/pull/23306

**Comment by joh42** [comment] 2023-07-28 08:55
A regression has been discovered: https://github.com/Expensify/App/issues/23743

I'm working on a PR to fix it https://github.com/Expensify/App/pull/23780

**Comment by joh42** [comment] 2023-07-28 11:10
PR https://github.com/Expensify/App/pull/23780 to fix the regression (https://github.com/Expensify/App/issues/23743) is now ready for review @eVoloshchak @techievivek

**Comment by Pujan92** [comment] 2023-07-28 13:14
@joh42 seems a regression https://github.com/Expensify/App/issues/23789

**Comment by joh42** [comment] 2023-07-28 14:12
Yep @Pujan92 that's correct, same bug as https://github.com/Expensify/App/issues/23743, thanks for the heads up! Tested it with PR https://github.com/Expensify/App/pull/23780, which solves it

**Comment by techievivek** [comment] 2023-08-08 08:22
@joh42 Looks like the PR caused a few regressions. Do you think you have a followup fix for it or should we just revert the original PR? And then you can look into fixing this correctly?

**Comment by techievivek** [comment] 2023-08-08 08:22
CC @eVoloshchak

**Comment by joh42** [comment] 2023-08-08 20:10
Given [this regression](https://github.com/Expensify/App/issues/24044), I do not think validating only when data has been changed is viable. As such I think right thing to do here is revert the original PR.

Since my proposed solution does not work, I actually think the solution proposed by @hungvu193 might be optimal. If it's okay with you, I can unassign myself from this issue and let @hungvu193 solve this instead.

@eVoloshchak
@techievivek

**Comment by techievivek** [comment] 2023-08-09 12:51
@joh42 Can you send the revert PR? I can merge that. And once we have that done, I can close all the regression issues and wait for someone to fix this issue correctly.

**Comment by joh42** [comment] 2023-08-09 22:54
PR created here https://github.com/Expensify/App/pull/24347

Should I complete the regular PR checklist @techievivek?

**Comment by techievivek** [comment] 2023-08-10 04:38
Our previous fix for this bug has been [reverted](https://github.com/Expensify/App/pull/24347) and this is once again open for proposals.

**Comment by techievivek** [comment] 2023-08-10 12:29
Thanks @hoangzinh, I have asked QA team to verify if this is reproducible or not https://expensify.slack.com/archives/C9YU7BX5M/p1691670468429039.

**Comment by mvtglobally** [comment] 2023-08-10 13:53
@techievivek It doesnt seem to be repro any more 


https://github.com/Expensify/App/assets/43995119/c7bff99b-017e-41f7-82d1-375247e415a0


https://github.com/Expensify/App/assets/43995119/31f706f6-3f74-4ad2-9691-1ec2e62540d1

**Comment by joh42** [comment] 2023-08-10 14:14
As far as I can tell the revert has not been deployed to staging: https://github.com/Expensify/App/pull/24347#issuecomment-1672542625

The bug exists on main:

https://github.com/Expensify/App/assets/138504087/36ed43f9-2db6-4a0f-b7c2-4805295e2d7e


It's worth noting that the original issue description only includes switching tabs, but in reality the bug occurs whenever the routing number input field is blurred. It might be worth changing the 11th testing step to something like "Blur the routing number input field by clicking outside of it"

**Comment by kadiealexander** [comment] 2023-08-14 01:41
Updated the testing steps.

**Comment by techievivek** [comment] 2023-08-14 08:53
@eVoloshchak Can you please take a look at this comment https://github.com/Expensify/App/issues/21838#issuecomment-1672557447 and review the proposal, thanks.

**Comment by techievivek** [comment] 2023-08-16 08:49
Gentle bump @eVoloshchak ^

**Comment by eVoloshchak** [comment] 2023-08-17 11:16
This has been resolved it seems, I can't reproduce it. 
@hungvu193, could you please verify if this is still reproducible for you? Thanks

https://github.com/Expensify/App/assets/9059945/e8c1826c-8053-478d-9267-01e45c62d67b

**Comment by kadiealexander** [comment] 2023-08-22 01:45
@hungvu193 is that a new bug, or do you think it's the same as this one?

**Comment by eVoloshchak** [comment] 2023-08-22 11:51
@hungvu193, thank you for the [proposal](https://github.com/Expensify/App/issues/21838#issuecomment-1612263965)
Your proposal will fix this specific issue, but I wonder if we could do better. Even if we don't run validate on blur, we will run it when user edits an input. Imagine the following case
- Enter Routing Number: 011401533 an enter an incorrect bank account number (e.g 1111222233334444)
- Press Continue, observe  an error message 'Your account number should end with 1111' (this is correct)
- focus the account number input, with your proposal applied the error is not dismissed (which is correct)
- delete a single number, observe the error message is dismissed (which isn't correct, since it still does not end with 1111)

 I fully agree with you on this

> If we can synchronize the validation of account number between client and server then we can avoid this issue.

This is the root cause we should be trying to fix. Is there a way we could implement this validation check on the front end?

**Comment by kadiealexander** [comment] 2023-08-28 06:36
@eVoloshchak bump!

**Comment by eVoloshchak** [comment] 2023-08-28 17:26
On a second thought, this isn't impactful enough (or at all) to implement the same validation on the front end. @hungvu193's proposal is universal, can be turned on for any of the Forms, it's better than implementing a FE validation for this specific page
I think we can proceed with @hungvu193's [proposal](https://github.com/Expensify/App/issues/21838#issuecomment-1612263965)

🎀👀🎀 C+ reviewed!

**Comment by kadiealexander** [comment] 2023-09-20 04:24
Payouts due:

Contributor: $1000 @hungvu193 
Contributor+: $1000 @eVoloshchak

Eligible for 50% #urgency bonus? [No](https://github.com/Expensify/App/issues/21838#issuecomment-1713509269)

Upwork job is [here](upwork.com/jobs/~01964ffb3d42e77df4).

**Comment by kadiealexander** [comment] 2023-09-20 04:27
@eVoloshchak please remember the checklist! :)

**Comment by eVoloshchak** [comment] 2023-09-21 09:10
- The PR that introduced the bug has been identified. Link to the PR: there isn't a PR that caused it, this is how validation was implemented initially, we just decided to alter it
- The offending PR has been commented on, pointing out the bug it caused and why, so the author and reviewers can learn from the mistake. Link to comment: N/A
- A discussion in #expensify-bugs has been started about whether any other steps should be taken (e.g. updating the PR review checklist) in order to catch this type of bug sooner. Link to discussion: this isn't a bug per se, just a slightly different behavior we decided to implement, I don't think an additional discussion is necessary
- Determine if we should create a regression test for this bug.
_Is it easy to test for this bug? Yes 
Is the bug related to an important user flow? Yes
Is it an impactful bug? Not this specific case, but it could, since it's implemented in `Form` component that is used throughout the app_

**Comment by eVoloshchak** [comment] 2023-09-21 09:11
**Regression Test Proposal**

1. Go to staging.new.expensify.com
2. Go to Settings > Workspace > Bank account > Connect with plaid method > Chase Bank
3. Use the following credentials for Chase Bank
4. Username: user_good
5. Password: pass_good
6. If a verification is prompted - select mobile and enter "credentials_good" as the verification mode
7. Checkmark the "Plaid Checking" and "Plaid Saving" and the last 2 options.
8. Click on continue
9. Check the T&C and click "Connect account information"
10. Click on the last confirmation on the plaid modal
11. Select the bank account ending in 1111
12. Enter Routing Number: 011401533 an enter an incorrect bank account number (e.g 1111222233334444)
13. Blur or take the focus away from the routing number input field by clicking outside of it or switching the tabs.
14. Verify that server error isn't cleared.

**Do we agree 👍 or 👎**

**Comment by eVoloshchak** [comment] 2023-09-21 09:17
> Eligible for 50% #urgency bonus? https://github.com/Expensify/App/issues/21838#issuecomment-1713509269

@kadiealexander, I'm not sure how these cases are handled, so I might be completely wrong, but I think this _might_ qualify for the urgency bonus. @hungvu193 got assigned to the job on Aug 29, I [approved](https://github.com/Expensify/App/pull/26225#pullrequestreview-1607408041) the PR on Sep 1, but it wasn't merged due to the merge freeze until it was lifted on Sep 11

**Comment by kadiealexander** [comment] 2023-09-25 04:47
@techievivek would you agree with the above?

**Comment by techievivek** [comment] 2023-09-25 04:56
@kadiealexander Yes, I agree this is within the urgency bonus deadline but we holded it because of the merge freeze that was going on.

**Comment by JmillsExpensify** [comment] 2023-09-28 00:37
So this is eligible for the urgency bonus? If so, can we update the payment summary above?

**Comment by kadiealexander** [comment] 2023-09-28 02:48
Sorry @JmillsExpensify, seems to be! Have updated the payment summary [here](https://github.com/Expensify/App/issues/21838#issuecomment-1726944851) and paid @hungvu193 their bonus via Upwork.

**Comment by JmillsExpensify** [comment] 2023-10-01 02:12
$1,500 payment for @eVoloshchak approved based on BZ summary.

**Closed** 2023-10-05 05:51 UTC
Labels: External, Engineering, Weekly, Awaiting Payment, Bug
