### ISSUE TITLE
Web - Wallet Statement Modal - Statement is not displayed and errors appear

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#28490] opened 2023-09-29 14:11 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___
**Issue found when executing PR** https://github.com/Expensify/App/pull/27934
## Action Performed:
1. Login to staging.new.expensify.com
2. Go to staging.new.expensify.com/statements/202308
3. Check the modal and console in local environment

## Expected Result:
There should be no error in the console in local environment

## Actual Result:
"Refused to connect" message is displayed and error in the console in local environment shows up

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [x] Windows / Chrome 
- [ ] MacOS / Desktop

**Version Number:** 1.3.75-0

**Reproducible in staging?:** Yes

**Reproducible in production?:** No

**If this was caught during regression testing, add the test name, ID and link from TestRail:**

**Email or phone of affected tester (no customers):**

**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/78819774/678410a8-8ef0-448c-82ca-c538533477e2

**Expensify/Expensify Issue URL:**

**Issue reported by:** Applause - Internal Team

**Slack conversation:**

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01e92423cfeff9e754</li>
        <li>Upwork Job ID: 1708417503606587392</li>
        <li>Last Price Increase: 2023-10-01</li>
    </ul>
</details>

**Comment by lanitochka17** [comment] 2023-09-30 21:09
Issue is still repro it on latest build v1.3.75-3 on Windows 10/Chrome 

https://github.com/Expensify/App/assets/78819774/55f2aa6c-ab26-4b65-90bb-d8e696684d2c

![retest](https://github.com/Expensify/App/assets/78819774/3a431be0-e881-4653-aee3-42f206fb718a)

**Comment by mountiny** [comment] 2023-10-01 09:44
Coming from this Slack convo https://expensify.slack.com/archives/C02NK2DQWUX/p1696148431657419 it seems like this is not coming from the App but more so from internal changes but the statement should work fine in production so going to remove the deploy blocker label

**Comment by hayata-suenaga** [comment] 2023-10-01 11:05
On production, the wallet statement page is displayed without any issue

Links in the iframe seems not be working:
https://github.com/Expensify/App/assets/98560306/0c941eb6-9c4d-45f0-93e3-4009e9e59a34

**Comment by hayata-suenaga** [comment] 2023-10-01 12:08
@AndrewGable @mountiny 
This is my suggestion

### Root cause

- NewDot embeds an OldDot page (wallet statement page) inside an iframe of NewDot.
- Both production and staging NewDots embed production OldDot.
- This means that when on staging, `staging.new.expensify.com` embeds `www.expensify.com`.
- These websites are considered as separate websites by the browser.
- Because current production OldDot CSP header doesn't explicitly list `staging.new.expensify.com` under `frame-ancestors`, the browser denies to display production OldDot inside the staging NewDot.

### Solution

- Let's embed the staging OldDot when NewDot is the staging one.
- Let's modify the CSP of staging OldDot so that the staging NewDot can embed it.

**Comment by mountiny** [comment] 2023-10-02 11:10
@hayata-suenaga I have confirmed with the QA they normally dont test this so its not a new issue. I think that this will eventually be handled by the changes required for the hybrid web so I think we dont have to do anything specific here and changes made for the hybrid web will fix this too.

Hence I think we can close this issue, feel free to reopen if you disgree

**Closed by mountiny** 2023-10-02 11:10 UTC
Labels: Engineering, Daily, Internal, Bug
