### ISSUE TITLE
Workspace - Email is missing in member tooltip when hovering over member

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#22636] opened 2023-07-11 12:07 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Go to staging.new.expensify.com
2. Go to Settings > Workspace > any workspace > Members
3. Hover over any member

## Expected Result:
Tooltip shows up with member avatar and email

## Actual Result:
Tooltip shows up with only member avatar

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [x] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:**1.3.39.5

**Reproducible in staging?:** Yes

**Reproducible in production?:** No

**If this was caught during regression testing, add the test name, ID and link from TestRail:**

**Email or phone of affected tester (no customers):**

**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Notes/Photos/Videos:** Any additional supporting documentation

<img width="1440" alt="Bug6123708_Screenshot_2023-07-11_at_19 34 32" src="https://github.com/Expensify/App/assets/78819774/22c1d204-88c4-44e8-8556-77e32d41b6fe">

https://github.com/Expensify/App/assets/78819774/61126c60-0f6a-471e-abfa-4f3fe79c6e16

**Expensify/Expensify Issue URL:**

**Issue reported by:** Applause - Internal Team

**Slack conversation:**

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by situchan** [comment] 2023-07-11 12:10
Dupe of https://github.com/Expensify/App/issues/22485

**Closed** 2023-07-11 14:12 UTC
Labels: DeployBlockerCash, Engineering, Hourly
