### ISSUE TITLE
[HOLD for payment 2023-06-21] [$1000] Avatar has no tooltip in thread report header

### ISSUE THREAD

**Issue by kavimuru** [Expensify/App#19825] opened 2023-05-30 15:41 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Create new room from any workspace (if not exist)
2. Send any message in room chat
3. Thread that message
4. Hover avatar on thread report header or on LHN
## Expected Result:
Tooltip shows with thread creator's avatar title
## Actual Result: 
No tooltip and Tooltip shows "__fake__" text in workspace chat thread header
## Workaround:
Can the user still use Expensify without this being fixed? Have you informed them of the workaround?

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [x] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 1.3.20-2
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/43996225/a58eb1df-8e4b-42f9-8fcf-8a01067508f2

https://github.com/Expensify/App/assets/43996225/99b26e53-dfcf-4979-a5b9-f837e19ef76b

**Expensify/Expensify Issue URL:**
**Issue reported by:** @0xmiroslav 
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1685268118865469

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~013f86178576b081ad</li>
        <li>Upwork Job ID: 1665777714293276672</li>
        <li>Last Price Increase: 2023-06-05</li>
    </ul>
</details>

**Comment by sakluger** [comment] 2023-06-01 17:20
I can't get `fake` to show up on hover, but it does just show nothing. We also show nothing though when hovering over the avatar for an `#admins` room. Asking in Slack to confirm that this is the intended behavior: https://expensify.slack.com/archives/C04QEB4MJEQ/p1685639994048869?thread_ts=1684920485.401849&cid=C04QEB4MJEQ

**Comment by sakluger** [comment] 2023-06-02 22:36
Reassigning BZ label since I'm OOO next week.

**Comment by priyeshshah11** [comment] 2023-06-05 18:43
## Proposal
### Please re-state the problem that we are trying to solve in this issue.
Avatar in thread header does not show tooltip on hover.

### What is the root cause of that problem?
The main issue is coming from `HeaderView` where we pass `shouldShowTooltip` as false for threads.
```
<MultipleAvatars
   icons={icons}
   shouldShowTooltip={!isChatRoom}
/>
```
### What changes do you think we should make in order to solve the problem?

We should pass true for to `shouldShowTooltip` for threads like 
`shouldShowTooltip={!isChatRoom || isThread}`

cc: @rushatgabhane

**Comment by JavSFDev** [comment] 2023-06-05 19:14
Contributor details
Your Expensify account email: javsfdev323@gmail.com
Upwork Profile Link: https://www.upwork.com/freelancers/~01b7fc496875b2b3dd

**Comment by puneetlath** [comment] 2023-06-07 22:29
@rushatgabhane thoughts on the proposals?

**Comment by puneetlath** [comment] 2023-06-08 20:30
@0xmiroslav are you taking over as C+ from @rushatgabhane on this?

**Comment by puneetlath** [comment] 2023-06-12 13:37
PR has been merged. Just waiting for deploy.

**Comment by puneetlath** [comment] 2023-06-22 19:16
@hoangzinh @0xmiroslav sorry for the delay, I've sent offers. 

@0xmiroslav friendly bump on the checklist. I'll pay your contract once that's been completed. Thanks!

**Comment by puneetlath** [comment] 2023-06-23 16:17
All paid. Thanks everyone!

**Closed by puneetlath** 2023-06-23 16:17 UTC
Labels: External, Daily, Awaiting Payment, Bug
