### ISSUE TITLE
[$250] Settings - The starting "s" is capitalised in the "Account settings" tooltip

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#43923] opened 2024-06-18 15:37 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.85-0
**Reproducible in staging?:** Y
**Reproducible in production?:** Y 
**If this was caught during regression testing, add the test name, ID and link from TestRail:** N/A
**Issue reported by:** Applause - Internal Team

## Action Performed:
1. Log in with any account
2. Hover over the "Account settings" button

## Expected Result:
The tooltip should be "Account settings"

## Actual Result:
The starting "s" is capitalised in the "Account settings" tooltip

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details> 

https://github.com/Expensify/App/assets/78819774/189d19e1-9220-4f2e-b500-d6976ee99563

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01c180ec6dec4f4508</li>
        <li>Upwork Job ID: 1803244539736034334</li>
        <li>Last Price Increase: 2024-06-26</li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @mallenexpensify</details>

**Comment by lanitochka17** [comment] 2024-06-18 15:38
We think that this bug might be related to #vip-vsp

**Comment by rigestshala** [comment] 2024-06-19 07:07
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
Settings - The starting "s" is capitalised in the "Account settings" tooltip

### What is the root cause of that problem?
Translation string needs to be modified.

### What changes do you think we should make in order to solve the problem?
Change "Account Settings" to "Account settings" and "Street Address" to "Street address".

https://github.com/Expensify/App/blob/f6085d284bfb69c837fbac7e3b4e3fba9853df26/src/languages/en.ts#L978

https://github.com/Expensify/App/blob/f6085d284bfb69c837fbac7e3b4e3fba9853df26/src/languages/en.ts#L1241

**Comment by sandysh3090** [comment] 2024-06-19 07:59
Contributor details
Your Expensify account email: gatiktech@gmail.com
Upwork Profile Link: https://www.upwork.com/freelancers/~01547a18555dde1c71

**Comment by bikramiter** [comment] 2024-06-19 08:01
Contributor details
Your Expensify account email: bikramiter@gmail.com
Upwork Profile Link: https://www.upwork.com/freelancers/~018f2471a350e1b5be

**Comment by sandysh3090** [comment] 2024-06-19 08:18
Contributor details
Your Expensify account email: [gatiktech@gmail.com](mailto:gatiktech@gmail.com)
Upwork Profile Link: https://www.upwork.com/freelancers/~01547a18555dde1c71

Please re-state the problem that we are trying to solve in this issue.
Settings - The starting "s" is capitalized in the "Account settings" tooltip

**Proposed Solution**
Update the tooltip on the "Account settings" button, Need to localize the string to capitalize it.

What is the root cause of that problem?
Right now tooltip fetches the text from the translation file. we need to add a logic to capitalize the first letter of the tooltip text. 

What changes do you think we should make in order to solve the problem?
Add a function to fetch a tooltip that capitalizes the first letter of the text in a sentence case.

**Comment by sandysh3090** [comment] 2024-06-19 08:27
Contributor details
Your Expensify account email: [gatiktech@gmail.com](mailto:gatiktech@gmail.com)
Upwork Profile Link: https://www.upwork.com/freelancers/~01547a18555dde1c71

**Comment by amardeep911** [comment] 2024-06-19 08:37
Contributor details
Your Expensify account email: [amardeepranjan911@gmail.com](mailto:amardeepranjan@gmail.com)
Upwork Profile Link: https://www.upwork.com/freelancers/~01922d1856797de60a

**Comment by rigestshala** [comment] 2024-06-19 08:38
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
Settings - The starting "s" is capitalised in the "Account settings" tooltip

### What is the root cause of that problem?
Translation string needs to be modified.

### What changes do you think we should make in order to solve the problem?

1. Change "Account Settings" to "Account settings";
2. Change "Street Address" to "Street address";
3. Remove unnecessary space at the end of the string on line 1455;
4. Change : 'The Entered Contact Method already exists.' to 'The entered Contact Method already exists.'.

https://github.com/Expensify/App/blob/f6085d284bfb69c837fbac7e3b4e3fba9853df26/src/languages/en.ts#L978

https://github.com/Expensify/App/blob/f6085d284bfb69c837fbac7e3b4e3fba9853df26/src/languages/en.ts#L1446

https://github.com/Expensify/App/blob/f6085d284bfb69c837fbac7e3b4e3fba9853df26/src/languages/en.ts#L1455

https://github.com/Expensify/App/blob/f6085d284bfb69c837fbac7e3b4e3fba9853df26/src/languages/en.ts#L868

**Comment by amardeep911** [comment] 2024-06-19 08:39
Contributor details
Your Expensify account email: [amardeepranjan911@gmail.com](mailto:amardeepranjan911@gmail.com)
Upwork Profile Link: https://www.upwork.com/freelancers/~01922d1856797de60a

**Comment by amardeep911** [comment] 2024-06-19 08:41
Contributor details
Your Expensify account email: amardeepranjan911@gmail.com
Upwork Profile Link: https://www.upwork.com/freelancers/~01922d1856797de60a

**Comment by Sparth19** [comment] 2024-06-19 10:30
Contributor details
Your Expensify account email: parthshekhaliya18@gmail.com
Upwork Profile Link: https://www.upwork.com/freelancers/parthshekhaliya

**Comment by allroundexperts** [comment] 2024-06-26 16:04
Since this is a very straight forward issue, I'd go with the first [proposal](https://github.com/Expensify/App/issues/43923#issuecomment-2176422187) with the correct RCA and the fix.

Let's go with @devguest07's [proposal](https://github.com/Expensify/App/issues/43923#issuecomment-2176422187).

🎀 👀 🎀 C+ reviewed

**Comment by allroundexperts** [comment] 2024-07-22 09:28
Oh, I think the automation did not kick in here. The PR was merged some time ago. @strepanier03 Can you check?

**Comment by francoisl** [comment] 2024-08-27 18:51
Yep @strepanier03 can you help with the payments here please? Thanks

**Comment by mallenexpensify** [comment] 2024-08-30 16:04
@devguest07 can you please accept the job and reply here once you have? 
https://www.upwork.com/jobs/~011c3fb8ccd13b93fb

Apologies for the delay.

**Comment by mallenexpensify** [comment] 2024-08-30 16:36
Contributor: @devguest07  paid $250 via Upwork
Contributor+: @allroundexperts due $250 via NewDot

Not going to create a regression test for this since it's just a capped letter.

**Closed by mallenexpensify** 2024-08-30 16:36 UTC
Labels: External, Daily, Awaiting Payment, Bug
