### ISSUE TITLE
Allow assigning a member that does not exist to a task

### ISSUE THREAD

**Issue by kavimuru** [Expensify/App#19678] opened 2023-05-26 15:57 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:

1. click on + button
2. choose Assign task option
3. Enter title
4. click on Next button
5. click on Share somewhere
6. enter email id which is not present in list
7. click on member
## Expected Result: 
member does not selected as share destination
## Actual Result: 
member should be selected as share destination

## Workaround:
Can the user still use Expensify without this being fixed? Have you informed them of the workaround?

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [x] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 1.3.19-2
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/43996225/38174a5c-995e-4221-8669-0a3952c0bd87

https://github.com/Expensify/App/assets/43996225/2fa4ecef-7ca4-4d35-b01a-9cfb97c7c2d0

**Expensify/Expensify Issue URL:**
**Issue reported by:** @gadhiyamanan 
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1684906260370359

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01a3a0b047b80b2ebb</li>
        <li>Upwork Job ID: 1664408410115301376</li>
        <li>Last Price Increase: 2023-06-01</li>
    </ul>
</details>

**Comment by alexpensify** [comment] 2023-05-27 16:36
I will test soon.

**Comment by alexpensify** [comment] 2023-05-27 23:10
I'll review soon.

**Comment by alexpensify** [comment] 2023-05-28 15:56
@thienlnam and @strepanier03 - This seems to be sort of related to https://github.com/Expensify/App/issues/19132. This GH is for someone who is not on the selection option and yours is assigning yourself. Any chance your GH will cover this case too?

**Comment by thienlnam** [comment] 2023-05-29 03:25
I don't think so, they are slightly different issues. This seems like a new issue 

I'm going to be OOO next week but this bug would likely exist when assigning a new member in a task as well

**Comment by thienlnam** [comment] 2023-05-29 03:25
I have read and reviewed this Design Doc!

**Comment by alexpensify** [comment] 2023-05-30 21:49
I confirmed this bug in my testing and I can't select the person who doesn't have an Expensify account: 

![image](https://github.com/Expensify/App/assets/8107070/05b587e3-8970-4509-83d2-7e7ee47f595e)

**Comment by alexpensify** [comment] 2023-05-30 21:50
@deetergp - Jack is offline for the week. I'm not sure if Jack's action to add this to Expensify Tasks means it should be an internal bug. I've verified the bug and am ready to assign it as External. Thanks for the feedback!

**Comment by thienlnam** [comment] 2023-06-01 23:04
This will require internal changes - though I think there might be a duplicate somewhere

**Comment by thienlnam** [comment] 2023-06-01 23:07
Ah yup here it is https://github.com/Expensify/App/issues/19820 - though this issue is older so I will keep this one open and update the requirements

**Comment by alexpensify** [comment] 2023-06-02 20:25
Thank you for the update here @thienlnam!

**Comment by alexpensify** [comment] 2023-06-04 15:44
No recent news

**Comment by thienlnam** [comment] 2023-06-07 13:45
This appears to have been fixed by another issue - the only problem I'm seeing though is that sometimes the task preview shows above the created reportAction

**Comment by thienlnam** [comment] 2023-06-09 15:12
Leaving this open for a BE refactor to use an optimistic user / chat report. Not urgent for right now though

**Comment by alexpensify** [comment] 2023-06-11 18:09
@thienlnam are we looking for proposals now?

**Comment by thienlnam** [comment] 2023-06-12 16:22
Nope, this is working but can be refactored to work better in the BE. I'll just close this for now and re-open when we need to revisit

**Closed by thienlnam** 2023-06-12 16:22 UTC
Labels: Engineering, Daily, Internal, NewFeature, Bug
