### ISSUE TITLE
Incorrect CP messages are showing up

### ISSUE THREAD

**Issue by luacmartins** [Expensify/App#46442] opened 2024-07-29 19:38 UTC
# Problem
We ran a CP for [this PR](https://github.com/Expensify/App/pull/46438), but it seems like we got duplicated CP messages added to two different issues for the same staging version.

- https://github.com/Expensify/App/pull/46438#issuecomment-2256745401
- https://github.com/Expensify/App/pull/46022#issuecomment-2256740456 (this PR had been merged before the deploy, so it was already in staging)

It seems like all [issues in the checklist](https://github.com/Expensify/App/issues/46436) got the cherry pick comment, instead of the deploy one

Additionally, it seems like we auto-assigned Chirag to the checklist for whatever reason.
![Screenshot 2024-07-29 at 3 57 02 PM](https://github.com/user-attachments/assets/70dc0052-98d7-468a-a4b3-e2b09a0e4b91)

# Solution
Investigate

**Comment by roryabraham** [comment] 2024-07-29 23:50
The problem is that [this variable](https://github.com/Expensify/App/blob/f556e7b5233d3685be7752418adc513a03568cce/.github/actions/javascript/markPullRequestsAsDeployed/markPullRequestsAsDeployed.ts#L109) only looks at the tag for the deploy. However, sometimes deploys are "batched" with deploys because of [this cancel-in-progress key](https://github.com/Expensify/App/blob/5b99455db40fd7c5acfe25189cf7465e67e41cd3/.github/workflows/platformDeploy.yml#L16).

So we really need to look at another piece of data to determine if a PR is being CP'd or deployed via the normal process.

**Comment by roryabraham** [comment] 2024-07-31 23:11
Got https://github.com/Expensify/App/pull/46535 prettymuch ready, but I'd like to wait for some CP'd merge commits to appear on staging so I can double-check what the commit messages look like before I put that PR in for review

**Comment by roryabraham** [comment] 2024-08-01 22:08
Sample commit message for a CP'd PR, pulled from staging log (had to do it after CP'ing some stuff because full staging deploys delete these commits and replace them with whatever's on main)

```
Merge pull request #46679 from neonbhai/selection-dropdown-fix
    
Fix: Dropdown button is not disabled when no selection is made
(cherry picked from commit 7b1b260ee9ed71e253e25642f95d362d70259368)
```

**Comment by greg-schroeder** [comment] 2024-08-05 13:43
PR still in progress

**Comment by roryabraham** [comment] 2024-08-05 18:07
ok, I've gotten this to the point where we can see which PRs were CP'd and in what versions. However, now we need a way to determine who actually triggered the CP workflow.

I tried listing cherryPick workflow runs but it doesn't seem like there's really a way to associate runs with a version. meanwhile, all platformDeploy runs are triggered by `OSBotify`

So my best idea right now is to try and update the cherryPick workflow to run the CP commits as the deployer, not `OSBotify`. But that could have all kinds of side-effects that would need to be carefully considered 😬

**Comment by roryabraham** [comment] 2024-08-08 18:41
> update the cherryPick workflow to run the CP commits as the deployer, not OSBotify

Looks like [we're already trying to do this](https://github.com/Expensify/App/blob/d0970ec24e19da6a891f0bc83622f0ece23c640f/.github/workflows/cherryPick.yml#L85), but it doesn't look like it's working: https://github.com/Expensify/App/commit/8d2f90b4dbfa126fbe733a83b3aa9df4fe33af52

**Comment by roryabraham** [comment] 2024-08-08 21:23
ok, chatted with @francoisl and we came up with a clever solution. PR ready for review

**Comment by roryabraham** [comment] 2024-08-08 23:23
PR merged

**Comment by greg-schroeder** [comment] 2024-08-14 10:44
Thanks @roryabraham! Awaiting deploy to staging -> prod

**Comment by roryabraham** [comment] 2024-08-23 20:23
This should be fixed now

**Closed by roryabraham** 2024-08-23 20:23 UTC
Labels: Reviewing, Weekly, Bug
