### ISSUE TITLE
[$500] Contact methods - Two error messages appear the same time

### ISSUE THREAD

**Issue by izarutskaya** [Expensify/App#33061] opened 2023-12-14 12:21 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** v1.4.12-0
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** Applause-Internal Team
**Slack conversation:** @

## Action Performed:
1. Go to URL https://staging.new.expensify.com/
2. Login with any account
3. Go to Settings -> Profile -> Contact methods
4. Enter a new contact method -> Don't validate
5. Several times click `Didn't receive a magic code?` until you get an error message
6. Then enter incorrect magic code -> Verify

## Expected Result:
The previous error disappears when the next one appears

## Actual Result:
Two error messages appear the same time

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [x] Android: mWeb Chrome
- [x] iOS: Native
- [x] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

https://github.com/Expensify/App/assets/115492554/4165d175-0287-44a2-8cc3-2b32b95664ee

![Bug6312958_1702554590611!image__194_](https://github.com/Expensify/App/assets/115492554/afb31530-09b2-4e14-8b0f-ef60f6c8c54b)

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01f249f131d8120932</li>
        <li>Upwork Job ID: 1735273944025079808</li>
        <li>Last Price Increase: 2023-12-14</li>
<li>Automatic offers: </li>
<ul>
<li>c3024 | Reviewer | 28065356</li>
<li>dukenv0307 | Contributor | 28065358</li>
</ul></li>
    </ul>
</details>

**Comment by zukilover** [comment] 2023-12-14 12:37
## Proposal
### Please re-state the problem that we are trying to solve in this issue.
Magic code shows error while other error is still shown

### What is the root cause of that problem?
The error for the maximum retries is shown regardless of the validateLoginError is empty or not.


### What changes do you think we should make in order to solve the problem?
Add a condition so that it only shows then the `validateLoginError` is empty:

```javascript
          <OfflineWithFeedback
                pendingAction={lodashGet(loginData, 'pendingFields.validateCodeSent', null)}
                errors={_.isEmpty(validateLoginError) ? ErrorUtils.getLatestErrorField(loginData, 'validateCodeSent') : null}
                errorRowStyles={[styles.mt2]}
                onClose={() => User.clearContactMethodErrors(props.contactMethod, 'validateCodeSent')}
            >

### What alternative solutions did you explore? (Optional)

N/A

**Comment by yh-0218** [comment] 2023-12-14 12:52
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
Two error messages appear the same time
### What is the root cause of that problem?
we have several issues (`validateCodeSent`, `validateLogin`) in error case.
### What changes do you think we should make in order to solve the problem?
We need to remove `validateCodeSent` when we get `validateLogin` error.
https://github.com/Expensify/App/blob/207d4ac23598dd10dad0275344d750b62b67a4a3/src/libs/actions/User.js#L420-L422
```js
 errorFields: {
         validateCodeSent: null,
          validateLogin: ErrorUtils.getMicroSecondOnyxError('contacts.genericFailureMessages.validateSecondaryLogin'),
 },
```
### What alternative solutions did you explore? (Optional)


https://github.com/Expensify/App/assets/65789015/b529139a-3ca9-43b4-91b7-419cc9d0c78c

**Comment by c3024** [comment] 2023-12-17 16:43
[Proposal here](https://github.com/Expensify/App/issues/33061#issuecomment-1855771657) by @dukenv0307 looks good to me.

🎀 👀 🎀 C+ Reviewed

**Comment by yh-0218** [comment] 2023-12-17 17:57
@c3024 [My proposal](https://github.com/Expensify/App/issues/33061#issuecomment-1855797615) has been updated.

**Comment by jacobkim9881** [comment] 2023-12-19 06:37
Since two components are created at each place these doesn't need to be one components. Because when maximum request error occurs the error shows below the clickable resend asking besides when verifying fails, incorrect error shows below the verify button.

**Comment by jacobkim9881** [comment] 2023-12-19 06:54
I found `<OfflineWithFeedback>` uses a props [` shouldShowErrorMessages = true,`](https://github.com/Expensify/App/blob/aa1d87caddb6831061f3750bd78f77b42603e5e3/src/components/OfflineWithFeedback.tsx#L75) as default. `<OfflineWithFeedback>` is used for `validateCodeSent` error. Seems the props can have a condition to show maximum request error of magic codes. 

``` javascript
 <OfflineWithFeedback
                pendingAction={lodashGet(loginData, 'pendingFields.validateCodeSent', null)}
                errors={ErrorUtils.getLatestErrorField(loginData, 'validateCodeSent')}
                //new condition below:
                shouldShowErrorMessages={isVerifyingFailed}
                errorRowStyles={[styles.mt2]}
                onClose={() => User.clearContactMethodErrors(props.contactMethod, 'validateCodeSent')}
            >
```

**Comment by c3024** [comment] 2023-12-28 14:39
**BugZero Checklist:** The PR fixing this issue has been merged! The following checklist ([instructions](https://stackoverflow.com/c/expensify/questions/14574)) will need to be completed before the issue can be closed:

* [x]  [@c3024] The PR that introduced the bug has been identified. Link to the PR: https://github.com/Expensify/App/pull/15204
* [x]  [@c3024] The offending PR has been commented on, pointing out the bug it caused and why, so the author and reviewers can learn from the mistake. Link to comment: https://github.com/Expensify/App/commit/748f3db2473f0747311e85fffa4e2c3cb38bc11e#r135840628
* [x]  [@c3024] A discussion in #expensify-bugs has been started about whether any other steps should be taken (e.g. updating the PR review checklist) in order to catch this type of bug sooner. Link to discussion: This is a unique case and a discussion in the channel has no use.
* [x]  [@c3024] Determine if we should create a regression test for this bug. Yes
* [x]  [@c3024] If we decide to create a regression test for the bug, please propose the [regression test](https://github.com/Expensify/App/blob/main/contributingGuides/REGRESSION_TEST_BEST_PRACTICES.md) steps to ensure the same bug will not reach production again.

**Comment by c3024** [comment] 2023-12-28 14:39
## Regression Test Proposal
1. Go to Profile > Contact Method
2. Click on 'New Contact Method' button
3. Input an email and click 'Add'
4. Click on the email added in the 'Contact Methods' page
5. Click on the 'Didn't receive magic code' button several times quickly so that the error "You've reached the maximum number of magic codes..." is shown.
6. Input an incorrect code
7. Verify that only the error "Incorrect or invalid magic code..." is shown and the error "You've reached the maximum number of magic codes..." is not shown.

👍  or 👎

**Comment by cristipaval** [comment] 2024-01-02 10:54
I wonder why Melvin didn't remove the hold 👀

**Comment by cristipaval** [comment] 2024-01-04 19:52
@NicMendonca, What is the payment status here?

**Comment by NicMendonca** [comment] 2024-01-04 21:00
@c3024 / @dukenv0307 - you've both been paid via upwork

**Comment by NicMendonca** [comment] 2024-01-04 21:01
all set here

**Closed by NicMendonca** 2024-01-04 21:01 UTC
Labels: External, Engineering, Daily, Awaiting Payment, Bug
