### ISSUE TITLE
[$500]  Request money - App displays Full message in search for description change request money

### ISSUE THREAD

**Issue by izarutskaya** [Expensify/App#28185] opened 2023-09-25 19:28 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Open the app
2. Open a request money report or raise new report and open it
3. Click on description
4. Enter multiline report and save it
5. Open search and observe that app displays full description change message in search in place of small preview with  3 dots as it does for other big messages.

## Expected Result:
App should display multiline description change messages with small preview and 3 dots in search

## Actual Result:
App displays multiline description change messages fully in search

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [x] Android / Chrome
- [ ] iOS / native
- [x] iOS / Safari
- [x] MacOS / Chrome / Safari
- [x] MacOS / Desktop

**Version Number:** v1.3.74-0

**Reproducible in staging?:** Y

**Reproducible in production?:** Y

**If this was caught during regression testing, add the test name, ID and link from TestRail:**

**Email or phone of affected tester (no customers):**

**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/115492554/14b64df0-9fc6-42fe-9ecf-19f53e9bf1fc

https://github.com/Expensify/App/assets/115492554/4b97627a-402f-4682-a4ce-f9d86c44357d

https://github.com/Expensify/App/assets/93399543/845d0032-38c2-49d3-9907-ccaa8fb6feac

https://github.com/Expensify/App/assets/93399543/ea8c0047-1d72-4602-b308-37900033093a

**Expensify/Expensify Issue URL:**

**Issue reported by:** @dhanashree-sawant

**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1695464156823429

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)
App displays Full message in search for description change request money

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01d694f13e5dde7a66</li>
        <li>Upwork Job ID: 1706390155446837248</li>
        <li>Last Price Increase: 2023-10-02</li>
    </ul>
</details>

**Comment by jliexpensify** [comment] 2023-09-25 22:24
Removing Mitch as I am the first b0 person assigned

**Comment by talha-programmer** [comment] 2023-09-27 00:56
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
The search bar shows detailed message in case the description of Money Request is changed and contains new line characters

### What is the root cause of that problem?
Due to new line characters, the text is not automatically reduced to a single line

### What changes do you think we should make in order to solve the problem?
In order solve the problem, we have to remove new line characters from the message text displayed in the search bar. In my opinion, the most appropriate way to do that is through a utility function defined in `StringUtils.ts`  file like this: 

```
function replaceNewLineChars(str: string, replaceWith = '') :string {
    return str.replaceAll(CONST.REGEX.NEW_LINE_CHARS, replaceWith);
}
```


Also, a new constant added in the `CONST.ts` file like this `NEW_LINE_CHARS: /\r\n/g,` inside the `REGEX` object. 

After that we will use the utility function in the `OptionsListUtils.js` file in the `createOption()` function: 
```
        if(removeNewLineChars) {
            result.alternateText = StringUtils.replaceNewLineChars(result.alternateText, ' ');
        }
```

The `removeNewLineChars` is passed to the third parameter of  `createOption` function:
```
function createOption(accountIDs, personalDetails, report, reportActions = {}, {showChatPreviewLine = false, forcePolicyNamePreview = false, removeNewLineChars = false}) 
```

The parameter 'removeNewLineChars' is used to have the ability to remove new line characters only when required. So that it won't conflict with any other functionality. 

This parameter will be set to true when called from the `getSearchOptions` function and passed all the way down to the `createOption` function. 

I haven't posted the complete code to make the proposal to the point. Please let me know if anything is not clear! 

### What alternative solutions did you explore? (Optional)
N/A

**Comment by talha-programmer** [comment] 2023-09-27 00:57
Contributor details
Your Expensify account email: talhashabbir9@gmail.com
Upwork Profile Link: https://www.upwork.com/freelancers/~01d2a31eb1ae210807

**Comment by shubham1206agra** [comment] 2023-09-27 12:37
# Proposal
## Please re-state the problem that we are trying to solve in this issue

Web - Request money - App displays Full message in search for description change request money

## What is the root cause of that problem?

During the description transition from single line to multiline, the whiteSpace style was also switched from `styles.pre` to `styles.noWrap` for this exact issue in the sidebar.

They just forgot to do the same here.

## What changes do you think we should make in order to solve the problem?

Just replace `styles.pre` with `styles.noWrap` here.

https://github.com/Expensify/App/blob/f5409e72f3517022421a98c7b0a9d8f7f075f06c/src/components/OptionRow.js#L152

## What alternative solutions did you explore? (Optional)
NA

**Comment by shubham1206agra** [comment] 2023-09-28 03:54
This is fixed by https://github.com/Expensify/App/pull/27822
cc @eVoloshchak @jliexpensify

**Comment by jliexpensify** [comment] 2023-09-29 07:34
@eVoloshchak Tested and I think it's fixed? Could youy verify too?

If so, I will pay out the reporter and close this!

**Comment by eVoloshchak** [comment] 2023-10-02 10:19
@jliexpensify, this is resolved for me too!

**Comment by jliexpensify** [comment] 2023-10-02 23:37
Great thanks!

Payment summary:

- Reporter: @dhanashree-sawant $50

[Could you apply here](https://www.upwork.com/jobs/~01d694f13e5dde7a66)? Sorry, having issues inviting you to this specific job.

**Comment by dhanashree-sawant** [comment] 2023-10-03 05:27
That's okay, I have applied to the job

**Comment by jliexpensify** [comment] 2023-10-03 21:49
Paid and job closed, thanks!

**Closed by jliexpensify** 2023-10-03 21:49 UTC
Labels: External, Daily, Help Wanted, Bug
