### ISSUE TITLE
[HOLD] [$1000] mWeb - mWeb - Keyboard opens automatically after going back from attachment

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#23489] opened 2023-07-24 14:49 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Go to any chat
2. Send any image as attachment.
3. Click on image to view it.
4. Click back arrow to go back to chat.
5. Keyboard opens automatically

## Expected Result:
Keyboard should not open automatically.

## Actual Result:
Keyboard opens automatically

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [x] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [ ] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:**
**Reproducible in staging?:**
**Reproducible in production?:**
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/93399543/3e9013bf-46d3-4c7e-b446-aff005c11b68

https://github.com/Expensify/App/assets/93399543/2cc62c3f-47d1-4f98-acae-76f67995ce25

**Expensify/Expensify Issue URL:**
**Issue reported by:** @Talha345
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1690147484102679

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~011c973cf5ceb3c3f7</li>
        <li>Upwork Job ID: 1683583847311867904</li>
        <li>Last Price Increase: 2023-07-31</li>
    </ul>
</details>

**Comment by stephanieelliott** [comment] 2023-07-24 21:03
Was able to repro.

**Comment by s-alves10** [comment] 2023-07-26 14:52
@stephanieelliott @fedirjh 

Refocusing on main composer opens the keyboard. I think this is an expected behavior

**Comment by Talha345** [comment] 2023-07-26 14:59
> @stephanieelliott @fedirjh
> 
> Refocusing on main composer opens the keyboard. I think this is an expected behavior

Nope, as we had the same issue on native platforms previously and we disabled it.This is not the expected behaviour.Only when the user taps the composer, only then the keyboard should open.

**Comment by situchan** [comment] 2023-07-26 15:09
I think composer autofocus issues on mWeb can be handled in https://github.com/Expensify/App/issues/23382.

**Comment by Talha345** [comment] 2023-07-26 15:39
> @situchan It looks like they are separate bugs, However, for this issue, I think this is the expected behavior. cc @stephanieelliott, looking at this comment, it seems like this is the expected, Focusing the input will open the keyboard on non-native platforms.
> 
> https://github.com/Expensify/App/blob/64e719e04c1a9712ba74633eb20d93690250f907/src/pages/home/report/ReportActionCompose.js#L269-L271

If you read the comment,it is mentioned that this same issue existed on native platforms and was solved using this code.If we are fixing it on native platforms,why not on mWeb?

**Comment by stephanieelliott** [comment] 2023-07-28 22:18
This feels like expected behavior to me too... I don't know enough about the RN variable to be certain though. @fedirjh based on the above, do you still agree this is not a bug?

**Comment by Talha345** [comment] 2023-07-28 22:23
> This feels like expected behavior to me too... I don't know enough about the RN variable to be certain though. @fedirjh based on the above, do you still agree this is not a bug?

@stephanieelliott Think from the perspective of a user using the platform.
They open a chat and scroll through it and every time they open an image attachment to preview it and close it,the keyboard pops up.Feels like buggy behavior to me at least.

**Comment by stephanieelliott** [comment] 2023-08-01 17:30
I agree with @fedirjh, it feels like polish if anything. Taking `Help Wanted` off this one and adding it to the tracking issue.

**Comment by stephanieelliott** [comment] 2023-08-04 06:34
Not overdue, just removed the `Daily` label since this is on hold

**Comment by stephanieelliott** [comment] 2023-10-06 05:08
Still on hold.

**Comment by stephanieelliott** [comment] 2024-01-03 23:22
Closing this as I don't think it is a priority. It is linked to the master tracking issue for composer component polish (which has also been deprioritized), so we may reopen it when we decide to focus on that issue.

**Closed by stephanieelliott** 2024-01-03 23:22 UTC
Labels: External, Monthly, Bug
