### ISSUE TITLE
[$500] Asking sign-in again from public room after refresh

### ISSUE THREAD

**Issue by izarutskaya** [Expensify/App#27198] opened 2023-09-11 20:40 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Open any public room without any authentication
2. Login from the prompts shown in the public channel
3. Complete login and observe you're loggedin
4. Refresh page and it's asking login again.

## Expected Result:
Once after login it shouldn't ask login again.

## Actual Result:
Asking login again.

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [x] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** v1.3.67-3

**Reproducible in staging?:** Y

**Reproducible in production?:** Y

**If this was caught during regression testing, add the test name, ID and link from TestRail:**

**Email or phone of affected tester (no customers):**

**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/115492554/79839c1f-ca6a-434d-b7b0-aedb5c937c8c

https://github.com/Expensify/App/assets/115492554/533b62da-7f7c-4ba7-bf8d-070cc274eeaf

**Expensify/Expensify Issue URL:**

**Issue reported by:** @b4s36t4

**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1693989869553719

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~015c546ad4cf74de6e</li>
        <li>Upwork Job ID: 1701334953343184896</li>
        <li>Last Price Increase: 2023-10-02</li>
    </ul>
</details>

**Comment by saraelsa** [comment] 2023-09-12 02:40
## Proposal

### Please re-state the problem that we are trying to solve in this issue.

If the user signs in while viewing an anonymous report, the authentication state is not persisted.

### What is the root cause of that problem?

Once the user opens a public room without having been signed in, they are signed in as an anonymous user. This information is retained in Oryx in the `session` key with `authTokenType` being `anonymousUser`, which is not unset when the user signs in. Once the window is refreshed, this value leads the application to incorrectly believe that the stored session belongs to an anonymous user, rather than a signed in user.

### What changes do you think we should make in order to solve the problem?

Default `authTokenType` to `null` in `DEFAULT_ACCOUNT_DATA`.

### What alternative solutions did you explore? (Optional)

**Reminder:** Please use plain English, be brief and avoid jargon. Feel free to use images, charts or pseudo-code if necessary. Do not post large multi-line diffs or write walls of text. Do not create PRs unless you have been hired for this job.

**Comment by saraelsa** [comment] 2023-09-12 02:41
Contributor details
Your Expensify account email: sara-etx+expensify-1@outlook.com
Upwork Profile Link: https://www.upwork.com/freelancers/~01ba3da8d6f0466a75

**Comment by strepanier03** [comment] 2023-09-12 21:23
Thanks @parasharrajat - In that case do you recommend closing this or leaving it open but not accepting proposals?

**Comment by strepanier03** [comment] 2023-09-12 21:23
@sophiepintoraetz - Looks like a double assignment so I'm going to remove you so you don't have to worry about this.

**Comment by strepanier03** [comment] 2023-09-14 21:32
Gotcha, thanks @parasharrajat - I'm raising internally now.

**Comment by strepanier03** [comment] 2023-09-18 20:47
Bumped [internally](https://expensify.slack.com/archives/C01SKUP7QR0/p1695070062031959) again.

**Comment by strepanier03** [comment] 2023-09-18 21:32
@parasharrajat - Can you tell me who the people are that are working on these Onyx changes you mention? I've asked a few times in Slack and no one can point me in the right direction.

**Comment by strepanier03** [comment] 2023-09-21 01:31
Thank you!

**Comment by b4s36t4** [comment] 2023-09-25 15:28
@parasharrajat Yes it still re-produceable took a latest pull and tested.

**Comment by marcochavezf** [comment] 2023-09-26 02:57
Coming from [here](https://expensify.slack.com/archives/C049HHMV9SM/p1695696997272519?thread_ts=1695648071.050709&cid=C049HHMV9SM), assigning myself. @daordonez11 mentioned that we're still getting the value for `authTokenType`, so probably we're not clearing out the value from an API command.

**Comment by strepanier03** [comment] 2023-09-27 22:21
Thank you @marcochavezf - I'll follow along but ping me if you need me to do something I'm not doing 🙌

**Comment by pradeepmdk** [comment] 2023-09-27 22:35
I think this dube of this https://github.com/Expensify/App/issues/26615#issuecomment-1737031211

@marcochavezf you are right. this onyx issue 
https://github.com/Expensify/react-native-onyx/pull/333

**Comment by marcochavezf** [comment] 2023-09-29 05:24
Hi @pradeepmdk, I saw your comment [here](https://github.com/Expensify/App/issues/26615#issuecomment-1740069630), do you know by chance if that also impacts this issue?

**Comment by pradeepmdk** [comment] 2023-09-29 05:35
@marcochavezf Yes, this is also fixed.. because the root cause same. 
https://github.com/Expensify/App/pull/28299
this PR upgrading the onyx. but after upgrading we are facing some crash issues due to some other fix also, in this upgraded version
https://github.com/Expensify/react-native-onyx/pull/329/files.
 so maybe they will revert but I am not sure about that part.

**Comment by pradeepmdk** [comment] 2023-09-29 05:45
@marcochavezf you can verify this one staging now.

https://github.com/Expensify/App/assets/16595846/e7e0452d-1264-4dd8-bd06-28d3de6b0117

**Comment by marcochavezf** [comment] 2023-10-03 05:41
> @marcochavezf yes, this is fixed now. you can verify this one staging now.
> 
>  Untitled.mp4

Oh cool, @strepanier03 I think we can then close this one

**Comment by strepanier03** [comment] 2023-10-04 21:49
Sounds good, I'll do that now.

**Closed by strepanier03** 2023-10-04 21:49 UTC
Labels: External, Engineering, Daily, Help Wanted, Bug
