### ISSUE TITLE
[HOLD for payment 2024-06-13] [HOLD for payment 2024-06-11] [$250] "Upload Photo" Popup Jitters When Clicking on Group Avatar

### ISSUE THREAD

**Issue by izarutskaya** [Expensify/App#42911] opened 2024-05-31 10:26 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** v1.4.78-2
**Reproducible in staging?:** Y
**Reproducible in production?:** N
**Email or phone of affected tester (no customers):** abebemiherat@gmail.com
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Issue reported by:** Applause-Internal team

## Action Performed:
1. FAB > Start Chat
2. Add Members > Click Next
3. Click on the Group Avatar > Notice that the "Upload Photo" popup jitters

## Expected Result:
The "Upload Photo" popup should appear smoothly when clicking on the group avatar.

## Actual Result:
The "Upload Photo" popup jitters when clicking on the group avatar.

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [x] Android: mWeb Chrome
- [ ] iOS: Native
- [x] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

https://github.com/Expensify/App/assets/115492554/ca5cabc5-752a-49ae-afea-18e534d023a5

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~0120e4c44848d7810a</li>
        <li>Upwork Job ID: 1796494461285986304</li>
        <li>Last Price Increase: 2024-05-31</li>
<li>Automatic offers: </li>
<ul>
<li>getusha | Contributor | 102570456</li>
</ul></li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @trjExpensify</details>

**Comment by izarutskaya** [comment] 2024-05-31 10:27
@trjExpensify I haven't added the External label as I wasn't 100% sure about this issue. Please take a look and add the label if you agree it's a bug and can be handled by external contributors.

**Comment by izarutskaya** [comment] 2024-05-31 10:27
We think this issue might be related to the #vip-vsb.

**Comment by Julesssss** [comment] 2024-05-31 10:48
Let's fix. But this doesn't need to block deploy.

**Comment by abzokhattab** [comment] 2024-05-31 11:50
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
Popover menu jitters when opened 
### What is the root cause of that problem?
here is the offending PR https://github.com/Expensify/App/pull/36292 
specifically this change 

<img width="1465" alt="image" src="https://github.com/Expensify/App/assets/59809993/0aa223bb-58ea-48f6-87eb-6c05f7f573de">

<img width="1397" alt="image" src="https://github.com/Expensify/App/assets/59809993/8cd0452c-1ae4-437d-ad2b-0a37965e9550">

what happens is that the `shouldUseNarrowLayout` keeps changing   


### What changes do you think we should make in order to solve the problem?

we can use `useMemo` to only calculate it once

```
    const shouldUseNarrowLayout = useMemo(() => (willAlertModalBecomeVisible ? isSmallScreenWidth : isSmallScreenWidth || isInModal), []);
```


or instead useRef

**Comment by bernhardoj** [comment] 2024-05-31 11:55
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
Upload photo popover jitters when showing.

### What is the root cause of that problem?
It's from https://github.com/Expensify/App/pull/36292. Same root cause as https://github.com/Expensify/App/issues/42908.

The jitter effect is because the width and padding are changing when the popover is showing. The `createMenuContainer` gives the width and padding style. When `shouldUseNarrowLayout` is true, the style isn't applied
<img width="215" alt="image" src="https://github.com/Expensify/App/assets/50919443/94f94981-c0a7-4390-aec6-d8a356810ed2">

The reason `shouldUseNarrowLayout` can change value is because if a modal is shown, the condition used is different.
https://github.com/Expensify/App/blob/e915d369db27d9ac77871322c5b7b2515bc29b52/src/hooks/useResponsiveLayout.ts#L55

Before the modal is shown, we use `isSmallScreenWidth || isInModal` condition which is true because we are in RHP, but when the modal is shown, we use `isSmallScreenWidth` which is false.

The reason we do that is because [we want to safely use shouldUseNarrowLayout in a modal](https://github.com/Expensify/App/pull/36292#discussion_r1580224875), that is, if `useResponsiveLayout` is being used in a modal, it will just use `isSmallScreenWidth` condition.

However, `willAlertModalBecomeVisible` is any modal visibility state, so it doesn't tell whether the `useResponsiveLayout` us being used inside a modal or not but rather is there any modal currently visible on the app. So, we can't use it like that.

### What changes do you think we should make in order to solve the problem?

We can add a new param to `useResponsiveLayout` to decide whether we use it in a modal or not, but it's not scalable because it's possible that we use the hook for both modal and non-modal component in a page.

So, I think we should re-use `isSmallScreenWidth` back for modal. (basically reverting this [commit](https://github.com/Expensify/App/pull/36292/commits/89e84de16a18eff83bb4643c0795758612e51330))

**Comment by Julesssss** [comment] 2024-06-03 08:02
Bumping this as it is likely linked to these two deploy blockers: 
- https://github.com/Expensify/App/issues/42912
- https://github.com/Expensify/App/issues/42910

**Comment by situchan** [comment] 2024-06-03 08:04
reviewing shortly

**Comment by getusha** [comment] 2024-06-03 08:46
@abzokhattab your solution will cause a regression

https://github.com/Expensify/App/assets/75031127/8a5462bd-01a7-4081-bad0-39aeb57ed9d5

**Comment by getusha** [comment] 2024-06-03 08:47
>So, I think we should re-use isSmallScreenWidth back for modal. (basically reverting this [commit](https://github.com/Expensify/App/pull/36292/commits/89e84de16a18eff83bb4643c0795758612e51330))

@bernhardoj We don't want to manually use `isSmallScreenWidth` for modals everywhere, as it defeats the purpose of adding the `useResponsiveLayout` hook. Is there a way to fix this by checking if it is a modal inside the hook?

**Comment by getusha** [comment] 2024-06-03 08:48
Interestingly we caught similar issue during the PR review

https://github.com/Expensify/App/pull/36292#issuecomment-2068179274

It was reproducible on `main` and `staging`

https://github.com/Expensify/App/pull/36292#issuecomment-2078215466

**Comment by getusha** [comment] 2024-06-03 08:49
@dragnoir could you please add more detail about your solution?

**Comment by bernhardoj** [comment] 2024-06-03 10:08
> Is there a way to fix this by checking if it is a modal inside the hook?

I don't think there is a way to do that.

> We don't want to manually use isSmallScreenWidth for modals everywhere, as it defeats the purpose of adding the useResponsiveLayout hook. 

I don't think the purpose of `useResponsiveLayout` should replace `isSmallScreenWidth` with `shouldUseNarrowLayout` in a modal. Both  `isSmallScreenWidth` and `shouldUseNarrowLayout` have their own valid usage. Instead of "hacking" around the definition, I think it would be better if we keep it as before,

`shouldUseNarrowLayout`: in small screen / RHP / LHP
`isSmallScreenWidth`: in small screen

No exception.

**Comment by getusha** [comment] 2024-06-03 10:43
>Both isSmallScreenWidth and shouldUseNarrowLayout have their own valid usage. Instead of "hacking" around the definition, I think it would be better if we keep it as before,

If there is no option, i think it's better to have an optional param in `useResponsiveLayout` to pass a value whether we use it in a modal or not.

cc @roryabraham @rayane-djouah

**Comment by Julesssss** [comment] 2024-06-03 11:47
> So, I think we should re-use isSmallScreenWidth back for modal. (basically reverting this [commit](https://github.com/Expensify/App/pull/36292/commits/89e84de16a18eff83bb4643c0795758612e51330))

I think this seems reasonable.

> When we click to open a popup, many other components render and change the value inside ONYXKEYS.MODAL this lead to many renders for [willAlertModalBecomeVisible](https://github.com/Expensify/App/blob/0cb2dc052f01b6a024ac872ad8bf628159fe7873/src/hooks/useResponsiveLayout.ts#L27) and then the value of shouldUseNarrowLayout will be a wrong value

This is a good find, but isn't the real problem here that the value of `shouldUseNarrowLayout` becomes wrong after other components update?

**Comment by Julesssss** [comment] 2024-06-03 14:52
Hi @dragnoir. I was curious about your alternative solution. 

But I assume [this logic](https://github.com/Expensify/App/pull/36292/files#diff-ed51849ac6db371cccf0d49b8b17972311143c9e67c1586bf487b2307d21d193R30-R40) was specifically introduced so that we only set `isInModal` once?

**Comment by getusha** [comment] 2024-06-03 15:05
>@getusha, to clarify, I think we've agreed on @bernhardoj's proposal being ideal -- we just need to clarify https://github.com/Expensify/App/issues/42911#issuecomment-2144873792. Is that correct?

@Julesssss Yes, lets assign @bernhardoj we can use `isSmallScreenWidth` in modal components, we agreed on that before finding an alternative https://github.com/Expensify/App/pull/36292#issuecomment-1987334312. We'll discuss that in the original issue since it's still in progress.

**Comment by getusha** [comment] 2024-06-03 15:06
>Yes true. by changing the initial state of isInModal to true, the component will initially consider itself to be in a modal. This will affect the value of shouldUseNarrowLayout until the updateModalStatus function runs and updates the state based on the actual navigation state.

@dragnoir `isInModal ` or `hasSetIsInModal`?

**Comment by Julesssss** [comment] 2024-06-03 15:30
I agree it works, I just want to make sure that there wasn't a specific reason for that default. I have asked Rory to take a look at both proposals when he is online, as he has more context regarding the PR.

**Comment by roryabraham** [comment] 2024-06-03 17:03
> The change must be:
>
> const hasSetIsInModal = useRef(true);

@dragnoir I'm pretty sure this is not a safe change:

1. if `hasSetIsInModal.current` is `true`, then [updateModalStatus becomes a no-op](https://github.com/Expensify/App/blob/501e6193246317f929e759281eaba1f823b70cc7/src/hooks/useResponsiveLayout.ts#L32-L34).
1. The means that `isInModal` will always be false.
1. This means that any usage of `useResponsiveLayout` in a RHP/LHP modal (i.e: a modal that's not a popover or alert) on a wide screen will get `shouldUseNarrowLayout=false`, which isn't right.

**Comment by roryabraham** [comment] 2024-06-03 17:13
I'm happy with @bernhardoj's solution to temporarily revert the problematic usage of `useResponsiveLayout` to unblock the deploy. But I'm not sure I agree with his analysis overall:

> I don't think the purpose of useResponsiveLayout should replace isSmallScreenWidth with shouldUseNarrowLayout in a modal
> shouldUseNarrowLayout: in small screen / RHP / LHP
> isSmallScreenWidth: in small screen

But a screen being in the RHP/LHP often means that the screen is a modal?

we should all try to be a bit more precise when talking about "modals". Because there's several forms of modals:

- popovers
- alerts
- modal stack navigators
- RHP modals (using react-native-modal, not a route reflected in the URL / navigation state)
    - side-note: this kind generally causes problems with back navigation and such, so I kind of think we should get rid of them. but it's a big lift to do that for all address forms and such

**Comment by roryabraham** [comment] 2024-06-03 17:39
yes, you can update your proposals. It would be helpful if you could hide any outdated proposals or ones that have been ruled out.

**Comment by roryabraham** [comment] 2024-06-03 18:27
My proposal to fix this issue leverages the fact that only a single modal can be displayed at a given time in React Native, and is like this:

- Create a global `ModalContext`.
- Update `BaseModal` to include a `ModalContextProvider` that includes the type for the currently displayed modal (or `undefined` if there's no modal currently visible)
- Update `useResponsiveLayout` to consume the `ModalContext` with `useContext`, and return `shouldUseNarrowLayout: true` if `isSmallScreenWidth || isInRightDockedModal`

The main piece of this proposal that's unclear to me is the nature of modal stack navigators - should these have any effect on the `ModalContext` or not?

_*Additional note:*_ the `ModalContextProvider` may or may not be able to replace the global [setModalVisibility](https://github.com/Expensify/App/blob/c9703417e8446611c37cef56f38f3bbf2282795d/src/libs/actions/Modal.ts#L68-L70) Onyx action. These two things are different in that the Onyx `ONYXKEYS.MODAL.isVisible` action is global and can be accessed from anywhere, whereas the context value is (by design) only accessible from a child of the context provider. This gives a child component a way to tell if it's a child of a modal or not.

_Additional question:_ Are we using portals for modals? Is that going to be a problem?

**Comment by roryabraham** [comment] 2024-06-03 18:44
Since @rayane-djouah is OOO and @getusha is offline, I suppose the best thing to do is for me to build a POC for this and see if it fixes the issue.

**Comment by roryabraham** [comment] 2024-06-03 21:44
Created https://github.com/Expensify/App/pull/43013, I _think_ it makes sense but I'm currently testing it out.

**Comment by roryabraham** [comment] 2024-06-06 17:05
Closing this out. It has been fixed and the only C+ payment that's due will be handled in https://github.com/Expensify/App/issues/42912

**Closed by roryabraham** 2024-06-06 17:05 UTC
Labels: External, Engineering, Weekly, Awaiting Payment, Bug
