### ISSUE TITLE
Chat - App does not shift focus to new group page or search page on use of shortcuts in specific manner

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#24663] opened 2023-08-16 22:09 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Open the app
2. Open any report which has attachment
3. Open attachment
4. Click 'CTRL+J'/'CMD+J' to open keyboard shortcut
5. Click 'CTRL+SHIFT+K'/'CMD+SHIFT+K' to open new group shortcut and observe that app does not focus on the new group search page

## Expected Result:
App should focus on new group page or search page when we open them using keyboard shortcuts

## Actual Result:
App does not focus on new group page or search page when we open them using keyboard shortcuts in following sequence: image preview->CTRL+J to open keyboard shortcut popup-> CTRL+SHIFT+K to open new group page

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [x] MacOS / Chrome / Safari
- [x] Windows / Chrome

**Version Number:** 1.3.54.11

**Reproducible in staging?:** Yes

**Reproducible in production?:** Yes

**If this was caught during regression testing, add the test name, ID and link from TestRail:**

**Email or phone of affected tester (no customers):**

**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/78819774/abd675a5-b5ed-4324-950e-9ffc2e9deca5

https://github.com/Expensify/App/assets/78819774/fefba2dd-9fbc-4de6-8d49-c6c62036d6c1

**Expensify/Expensify Issue URL:**

**Issue reported by:** @Dhanashree-Sawant

**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1691396399344909

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by jfquevedol2198** [comment] 2023-08-17 02:19
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
Chat - App does not shift focus to new group page or search page on use of shortcuts in specific manner

### What is the root cause of that problem?
https://github.com/Expensify/App/blob/b3789c90d884c6bae654edbcd0ed61a96ac07017/src/libs/actions/Modal.js#L12-L14

When new modal is opened, we set `closeModal` variable in Modal action to new modal's onClose callback.
And, we call `closeModal()` to close current modal.
 
https://github.com/Expensify/App/blob/b3789c90d884c6bae654edbcd0ed61a96ac07017/src/components/Modal/BaseModal.js#L53-L62

In this method, `componentWillUnmount` is calling `setCloseModal(null)` for invisible modals. So current modal cannot be closed.


### What changes do you think we should make in order to solve the problem?
https://github.com/Expensify/App/blob/b3789c90d884c6bae654edbcd0ed61a96ac07017/src/components/Modal/BaseModal.js#L53-L62

Here, if modal is invisible, it should be not called `setCloseModal` action

```javascript
    componentWillUnmount() {
        // Only trigger onClose and setModalVisibility if the modal is unmounting while visible.
        if (this.props.isVisible) {
            this.hideModal(true);
            Modal.willAlertModalBecomeVisible(false);
        } else {
            return;
        }

        // To prevent closing any modal already unmounted when this modal still remains as visible state
        Modal.setCloseModal(null);
    }
```

### What alternative solutions did you explore? (Optional)

**Comment by stephanieelliott** [comment] 2023-08-22 16:34
This is expected behavior, that shortcut menu is a directory -- it assumes you are still reviewing the shortcuts until you close the window manually. This is a conscious UX decision, not a bug.

**Comment by dhanashree-sawant** [comment] 2023-08-22 17:32
Hi @stephanieelliott, you can try using CTRL+J and then CTRL+K, it will close the shortcut window and open search page, the issue only occurs when we first open attachment preview and then use CTRL+J and CTRL+K which actually doesn't make sense

**Comment by sophiepintoraetz** [comment] 2023-08-28 05:23
I am inclined to agree with @stephanieelliott - I don't think this is worth fixing and is intended by design.

**Comment by sophiepintoraetz** [comment] 2023-08-28 05:44
Ahk, if we do this on chrome already, then I agree with you. Reopening to see what you think, @stephanieelliott!

**Comment by stephanieelliott** [comment] 2023-09-01 18:40
We're discussing this internally! While this is too minor to prioritize fixing as a one-off, we're considering changing the shortcut menu completely and moving it into the RHP. Will update shortly on the outcome of that discussion.

**Comment by stephanieelliott** [comment] 2023-09-11 23:16
See https://github.com/Expensify/App/issues/27141#issuecomment-1714215970 -- we're going to be moving the keyboard shortcuts to the RHP instead, so closing this.

**Closed by stephanieelliott** 2023-09-11 23:16 UTC
Labels: Daily, Overdue, Bug
