### ISSUE TITLE
[HOLD for payment 2022-12-08] Profile - If user uses saved information, background turns white & is very hard to read

### ISSUE THREAD

**Issue by kavimuru** [Expensify/App#13116] opened 2022-11-29 01:25 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
Pre-Condition: User has saved information on their device
1. Access staging.new.expensify.com
2. Enter a valid account
3. Tap on Profile icon > Profile > Add phone number
4. Selected the saved information option

## Expected Result:
User expects the background to match the dark theme

## Actual Result:
The background turns to a bright white and afterwards makes it very hard to read the text in the field

## Workaround:
unknown

## Platform:

Where is this issue occurring?

- Web

**Version Number:** 1.2.33-1
**Reproducible in staging?:** Y
**Reproducible in production?:** New UI
**Email or phone of affected tester (no customers):** 
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** 
EXTRA: This seems to happen with any input field as long as you have saves information
https://user-images.githubusercontent.com/43996225/204415527-9c4f235c-788c-413f-b1e8-e74f78a818f7.mp4

<img width="1440" alt="Bug5839961_Field_turns_white" src="https://user-images.githubusercontent.com/43996225/204415531-ac8090b3-a058-45b0-89a3-fffa03d6ea2a.png">

**Expensify/Expensify Issue URL:** 
**Issue reported by:** Applause internal team
**Slack conversation:** 

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by marcaaron** [comment] 2022-11-29 01:38
Not able to reproduce given these test steps. The input looks fine on my end:

<img width="1512" alt="2022-11-28_15-37-42" src="https://user-images.githubusercontent.com/32969087/204417140-1e03e4af-2d63-4bcb-b0d7-0d85c4b91dcc.png">

What does "if the user users saved information" mean exactly? Are there missing test steps?

**Comment by marcaaron** [comment] 2022-11-29 01:39
Oh, I think you mean "auto complete"... lemme try that.

**Comment by marcaaron** [comment] 2022-11-29 01:57
Ok, so the user agent stylesheet will need to be overwritten in our app. 

Guessing we did not notice this before because our theme was similar to the defaults that Chrome (and others) add in. I also came across this -> https://developer.mozilla.org/en-US/docs/Web/CSS/:autofill which seems to suggest that the autocomplete UA styles can't be easily overwritten in CSS and require some hacks.

Will look around for some solution... but in the meantime... cc @shawnborton @grgia to see if you all know any workarounds.

**Comment by marcaaron** [comment] 2022-11-29 01:58
<img width="955" alt="2022-11-28_15-47-30" src="https://user-images.githubusercontent.com/32969087/204419708-fa03bf54-27e3-42e1-a069-9e871090a71e.png">

**Comment by sobitneupane** [comment] 2022-11-29 02:31
I had reported this bug earlier [here](https://expensify.slack.com/archives/C049HHMV9SM/p1669652308876229) in slack. Raising here for compensation request as a bug reporter.

**Comment by marcaaron** [comment] 2022-11-29 03:00
Found a kind of ridiculous hack to fix this [here](https://stackoverflow.com/a/59572885/10577587) that does work kind of perfectly. 

Honestly, it's not looking good for going through the proper channels:

<img width="1004" alt="2022-11-28_16-58-38" src="https://user-images.githubusercontent.com/32969087/204427996-3fca804d-506d-4d0b-93ce-7b088b801050.png">

🥲

**Comment by marcaaron** [comment] 2022-11-29 23:04
I am not really sure how the staging regression could have been avoided in this case. The fix worked in one place but not for all cases. Staging did what it was supposed to in this case and the issue was caught at the right layer.

**Comment by luacmartins** [comment] 2022-11-30 16:49
This was fixed by https://github.com/Expensify/App/pull/13164. Closing!

**Comment by thesahindia** [comment] 2022-12-01 05:46
@luacmartins, c+ review compensation is pending as well.

**Comment by thesahindia** [comment] 2022-12-08 20:00
> @luacmartins, c+ review compensation is pending as well.

bump @luacmartins

**Comment by luacmartins** [comment] 2022-12-08 20:10
@sobitneupane @thesahindia sorry we missed those. I'll reopen this issue for compensation.

**Comment by luacmartins** [comment] 2022-12-08 20:12
@sophiepintoraetz can you help with the reporting bonus to @sobitneupane and @thesahindia for C+ PR review?

**Comment by thesahindia** [comment] 2022-12-08 20:12
Thanks @luacmartins

**Comment by sophiepintoraetz** [comment] 2022-12-12 05:22
To clarify, @thesahindia you're owed $250 C+ plus the bonus of $125, making it a total of $375 owed, correct?
(@sobitneupane - you're $250)

**Comment by thesahindia** [comment] 2022-12-12 08:46
@sobitneupane, the bonus only applies to external PRs and for internal PRs the compensation is $1000 ([slack post here](https://expensify.slack.com/archives/C01GTK53T8Q/p1668726522584349))

**Comment by sophiepintoraetz** [comment] 2022-12-12 23:48
Got it - thanks for confirming, @thesahindia! Hired you both for the[Profile - If user uses saved information, background turns white & is very hard to read - #13116](https://www.upwork.com/ab/applicants/1602448697358340096/suggested)

**Comment by sophiepintoraetz** [comment] 2022-12-13 21:36
paid!

**Closed by sophiepintoraetz** 2022-12-13 21:36 UTC
Labels: Engineering, Daily, Awaiting Payment, Bug
