### ISSUE TITLE
Web - Task - Task title changes to older task's title in small screen

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#21427] opened 2023-06-23 16:59 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Create a task TASK-1
2. Cancel it
3. Create another task TASK-2
4. Create another task TASK-3
5. Go to the chat report of task 3
6. Open the title
7. Go back
8. Reduce screen size
9. Now again open the task title
10. Go back
11. Repeat 9,10 a few times
12. Assign all the tasks to yourself

## Expected Result:
 Task title should remain the same what we have set

## Actual Result:
Title changes to the title of previous task in small screen

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [x] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** n/a

**Reproducible in staging?:** n/a

**Reproducible in production?:** n/a

**If this was caught during regression testing, add the test name, ID and link from TestRail:**

**Email or phone of affected tester (no customers):**

**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/93399543/71644ba6-0400-47a2-94d8-ba29d4026c0d

**Expensify/Expensify Issue URL:**

**Issue reported by:** @chiragxarora

**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1686931751373249

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by lschurr** [comment] 2023-06-23 21:26
I can't reproduce. The title stays the same for me.

**Comment by thienlnam** [comment] 2023-06-23 21:40
Unsure if this is still reproducible - but we're redesigning the task title in https://github.com/Expensify/App/issues/19330, so going to put this on hold

**Comment by lschurr** [comment] 2023-07-05 15:18
On hold.

**Comment by lschurr** [comment] 2023-07-13 20:21
Still on hold.

**Comment by lschurr** [comment] 2023-07-24 15:16
On hold.

**Comment by thienlnam** [comment] 2023-07-24 21:11
Held PR has been deployed to production. Can we see if this is still reproducible? If not we can close it out after paying reporter

**Comment by lschurr** [comment] 2023-08-02 20:29
Bumped the Slack thread once more to see if this is reproducible - https://expensify.slack.com/archives/C049HHMV9SM/p1691008128266109?thread_ts=1686931751.373249&cid=C049HHMV9SM

**Comment by lschurr** [comment] 2023-08-11 16:36
I reached out in Slack again and will close once we have confirmation.

**Comment by lschurr** [comment] 2023-08-11 18:02
Thanks @chiragxarora - could you apply for the job here? https://www.upwork.com/jobs/~0110b0e542cfacce63

**Comment by lschurr** [comment] 2023-08-11 18:13
Offer sent!

**Comment by lschurr** [comment] 2023-08-11 18:28
For tracking, the payment summary is:

- Bug reporter @chiragxarora: $250 (paid in Upwork)

**Closed by lschurr** 2023-08-11 18:28 UTC
Labels: Weekly, Needs Reproduction, Bug
