### ISSUE TITLE
[$250] Workspace - Invite new member - 403 error message in console

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#12637] opened 2022-11-10 15:00 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Issue found when executing PR** https://github.com/Expensify/App/pull/12551 

## Action Performed:
1. Launch the app
2. Login with any account
3. Go to Settings -> Workspaces -> workspace -> Manage members
4. Verify that no console error shows
5. Click Invite button to go to Invite new members page

## Expected Result:
Verify that no console error shows

## Actual Result:
403 error message displayed in console

## Workaround:
Unknown

## Platform:

Where is this issue occurring?

- Web
- Desktop App

**Version Number:** 1.2.26.0

**Reproducible in staging?:** Yes

**Reproducible in production?:** Yes

**Email or phone of affected tester (no customers):** 

**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Notes/Photos/Videos:** Any additional supporting documentation

https://user-images.githubusercontent.com/93399543/201126924-79971fcb-1784-4c5e-907e-f5aa011bdd33.mp4

![Screen Shot 2022-11-09 at 5 51 17 PM (1)](https://user-images.githubusercontent.com/93399543/201126932-e7469c1d-da20-4cf7-b52c-8f9dd4cb906c.png)

**Expensify/Expensify Issue URL:** 

**Issue reported by:** Applause - Internal Team

**Slack conversation:** 

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by alexpensify** [comment] 2022-11-11 01:38
I see the Console response but I still can invite the user. 

![image](https://user-images.githubusercontent.com/8107070/201243374-e22f959f-3a98-428d-9799-af6ed67f2671.png)

Assigning to engineering for extra eyes if we need to fix.

**Comment by iwiznia** [comment] 2022-11-11 10:49
I can't reproduce this, @kbecciv can you share the full console error message (preferrably as text, since it has a huge URL in it)? The one you shared is truncated.
My guess is that it has something to so with the avatar image...

**Comment by iwiznia** [comment] 2022-11-11 10:50
Oh, also, @alexpensify can't reproduce either (the console messages there are different than the OG post)

**Comment by kbecciv** [comment] 2022-11-14 14:39
@iwiznia Checking, update you shortly

**Comment by kbecciv** [comment] 2022-11-14 14:49
@iwiznia Please attach the requested for .txt. file for console error message.

[console error.txt](https://github.com/Expensify/App/files/10004050/console.error.txt)

**Comment by iwiznia** [comment] 2022-11-14 15:02
Ah cool. I think I've seen this before. We are apparently trying to download this image https://d1wpcgnaa73g0y.cloudfront.net/825d2d6d08b35c4e47d9a7d6da678e68062f8f6c_128.jpeg which does not exist. The OG one does https://d1wpcgnaa73g0y.cloudfront.net/825d2d6d08b35c4e47d9a7d6da678e68062f8f6c.jpeg so I assume we think we created a thumbnail, but we did not. We need to figure out where this is coming from and check if we indeed should not be trying to display it OR if we are failing to generate the thumbnail in the server. If the former, this is internal, if the latter then it's external, but adding internal to investigate the issue to begin with.

**Comment by alexpensify** [comment] 2022-11-15 01:35
@deetergp - Keep me posted if I need to create a job.

**Comment by alexpensify** [comment] 2022-11-17 17:42
@deetergp - any update here?

**Comment by alexpensify** [comment] 2022-11-18 16:50
@tylerkaraszewski - It looks like this is being moved to Internal. Keep me posted if you need anything from me to keep this moving forward. I'm OOO starting today but will check GH from time to time until I return on November 30.

**Comment by Gonals** [comment] 2022-11-21 09:53
Unable to reproduce in either Staging, Prod or Dev. Closing

**Comment by Gonals** [comment] 2022-11-21 09:56
While testing https://github.com/Expensify/App/issues/12205, I went ahead and tested this too. @tylerkaraszewski, I can't reproduce this issue anymore. Are you ok with closing it?

**Comment by tylerkaraszewski** [comment] 2022-11-22 00:33
Let's close. It'll get reopened if someone reproduces, and if not, great.

**Closed by tylerkaraszewski** 2022-11-22 00:33 UTC
Labels: Engineering, Daily, Internal, Bug
