### ISSUE TITLE
[$500] Wrong subject line for the paid IOU

### ISSUE THREAD

**Issue by m-natarajan** [Expensify/App#32781] opened 2023-12-09 16:07 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.10-0
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** @quinthar 
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1702085625758089

## Action Performed:
1. As user A  create a money request to B
2. As user B complete payment 
3. Check the email received

## Expected Result:
Subject line in the email should be " Account B paid $XX"

## Actual Result:
Subject line in the email should be " Account A owes  $XX"

## Workaround:
unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

![image (6)](https://github.com/Expensify/App/assets/38435837/21939b9b-f72f-4c4c-a8cc-dc2e96d5f5a9)

![email](https://github.com/Expensify/App/assets/38435837/6e9a3b9d-7a3e-4778-99f1-e0164f91d389)

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~011af6adb90d7b4738</li>
        <li>Upwork Job ID: 1733518701278203904</li>
        <li>Last Price Increase: 2023-12-09</li>
    </ul>
</details>

**Comment by omarirfan68** [comment] 2023-12-09 21:13
hoping that this task should assign to me :)

**Comment by aldo-expensify** [comment] 2023-12-14 23:25
Investigated this a bit, I think that subject line comes from the fact that the activity belongs to a money request. It is not related to the activity taking place at the moment. I have to verify, but I'm pretty sure that you will see the same subject with `owes` if you just send a message in the IOU/expense chat.

**Comment by aldo-expensify** [comment] 2023-12-18 17:51
> Investigated this a bit, I think that subject line comes from the fact that the activity belongs to a money request. It is not related to the activity taking place at the moment. I have to verify, but I'm pretty sure that you will see the same subject with `owes` if you just send a message in the IOU/expense chat.

Verified this:

<img width="647" alt="image" src="https://github.com/Expensify/App/assets/87341702/0f36fd0e-8598-4357-b97c-acf0df332f4d">

The subject is fixed, and is independent of the latest offline action being done. The subject says "owes" because this is happening in the context of a money request.

**Comment by aldo-expensify** [comment] 2023-12-18 17:59
@slafortune I think this is by design and not a bug, we may need to confirm if we really want to do this change and how it would look for offline activity that is not "paying".

**Comment by aldo-expensify** [comment] 2023-12-21 14:52
Changing to `Weekly` while we figure out what we want to do here.

**Comment by aldo-expensify** [comment] 2023-12-21 14:55
Asking [here](https://expensify.slack.com/archives/C01GTK53T8Q/p1703170531481529) about what do do with this issue. I'm on the side of just closing it.

**Comment by slafortune** [comment] 2023-12-27 15:04
Thanks for checking on this @aldo-expensify ! Closing per the linked conversation.

**Closed by slafortune** 2023-12-27 15:04 UTC
Labels: Engineering, Daily, Internal, Overdue, Bug
