### ISSUE TITLE
[$500] Contact method - Error message when add contact method is not translated to Spanish

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#32754] opened 2023-12-08 21:28 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.10-0
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** Applause - Internal Team
**Slack conversation:**

## Action Performed:
1. Open staging.new.expensify.com
2. Navigate to Settings> Preferences> Language> Spanish
3. Go to Settings> Profile> Contact Method
4. Add [receipts@expensify.com](mailto:receipts@expensify.com)
as contact method

## Expected Result:
Error message should be present in Spanish language

## Actual Result:
Error message is displayed in English

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [x] Android: mWeb Chrome
- [x] iOS: Native
- [x] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details> 

https://github.com/Expensify/App/assets/78819774/3a6fd243-5e37-4d08-a135-f19472cfa2ef

![Bug6306304_1702070204481!image](https://github.com/Expensify/App/assets/78819774/f4bdc4e8-25c7-4e4d-8e41-0033e942bab4)

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01e336f47edd43fd48</li>
        <li>Upwork Job ID: 1733237184652222464</li>
        <li>Last Price Increase: 2023-12-08</li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @garrettmknight</details>

**Comment by ZhenjaHorbach** [comment] 2023-12-08 21:37
Looks like BE issue

**Comment by nikosamofa** [comment] 2023-12-08 22:35
## Proposal

### Please re-state the problem that we are trying to solve in this issue.

Error message while adding receipts@expensify.com as contact method doesn't show in Spanish, when the language preference is set to Spanish

### What is the root cause of that problem?

The error message is from the backend when failed to add the contact method.
The UI just shows the error message.


https://github.com/Expensify/App/assets/30532000/237a6be2-f692-43a5-84e9-28ee7c17cdba



### What changes do you think we should make in order to solve the problem?

This requires collaboration with the backend team.

1. The error message in En/Sp will be added to `src/languages/en.ts` and `es.ts`
2. If the `code: 666`(OR `type: Expensify\\Error\\User\\CannotAddSecondaryLogin`) corresponds to this error case, check the jsonCode and show the error message from the message added step 1. This will be decided with the collaboration of the backend team.
3. Else, collaborate with the backend team to add a new field, something like `reason: ADMINISTRATOR_RESTRICTED`. And for this error, show the error message from step 1.

**Comment by AmjedNazzal** [comment] 2023-12-09 09:38
This is a BE issue as it was decided not to expand on local translation and there will be consideration in the future to support Spanish by the BE side and local translation will be deprecated eventually from what I understood looking at discussions of similar issues in the past.

**Comment by Santhosh-Sellavel** [comment] 2023-12-10 18:47
@garrettmknight I think we can close this, Can you check internally let me whats the action plan, thanks!

**Comment by garrettmknight** [comment] 2023-12-12 17:15
@AmjedNazzal can you point me to the thread where this was decided? I couldn't find it on a quick search.

**Comment by AmjedNazzal** [comment] 2023-12-12 17:26
@garrettmknight https://github.com/Expensify/App/issues/26621#event-10360036119 not the exact same issue but the general idea I was trying to talk about is that the BE doesn't return Spanish and it seem to be something that was decided to be put aside along with similar Spanish related issues until BE localisation becomes supported.

**Comment by garrettmknight** [comment] 2023-12-14 11:14
Thanks @AmjedNazzal - closing!

**Closed by garrettmknight** 2023-12-14 11:14 UTC
Labels: External, Daily, Help Wanted, Bug
