### ISSUE TITLE
[$500]  Chat - Parent message shows editing mode when editing the message in the thread

### ISSUE THREAD

**Issue by izarutskaya** [Expensify/App#30488] opened 2023-10-27 10:13 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.3.92.0

**Reproducible in staging?:** Y

**Reproducible in production?:** Y

**If this was caught during regression testing, add the test name, ID and link from TestRail:**

**Email or phone of affected tester (no customers):**

**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Expensify/Expensify Issue URL:**

**Issue reported by:** Applause-Internal Team

**Slack conversation:** @

## Action Performed:
1. go to any chat
2. send a message
3. start thread
4. hover over the message and click edit option
5. without doing anything go back to parent clicking on the header

## Expected Result:
Message should not be in edited mode

## Actual Result:
Message is showing in edit mode

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [x] Android: mWeb Chrome
- [x] iOS: Native
- [x] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos
<details>
<summary>Android: Native</summary>

</details>

<details>
<summary>Android: mWeb Chrome</summary>

</details>

<details>
<summary>iOS: Native</summary>

</details>

<details>
<summary>iOS: mWeb Safari</summary>

</details>

<details>
<summary>MacOS: Chrome / Safari</summary>

https://github.com/Expensify/App/assets/115492554/7b12463a-63d9-4579-99c0-8238f973084e

</details>

<details>
<summary>MacOS: Desktop</summary>

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~011db84558d8f19401</li>
        <li>Upwork Job ID: 1717846962126123008</li>
        <li>Last Price Increase: 2023-10-27</li>
    </ul>
</details>

**Comment by eh2077** [comment] 2023-10-27 10:26
This is not a bug, see https://github.com/Expensify/App/pull/28154

**Comment by mananjadhav** [comment] 2023-10-27 18:44
> This is not a bug, see #28154

@maddylewis @izarutskaya As pointed in the previous comment it looks like it was added in the PR. Can you confirm and then we can close this one.

Thanks @eh2077

**Comment by situchan** [comment] 2023-10-27 19:05
Discussion: https://expensify.slack.com/archives/C01GTK53T8Q/p1691673930838889?thread_ts=1689867403.367019&cid=C01GTK53T8Q

We can close as expected. Maybe we need to update Test Rail so QA team won't treat this as bug in the future.

**Comment by maddylewis** [comment] 2023-10-30 15:41
>  Maybe we need to update Test Rail so QA team won't treat this as bug in the future.

@situchan - which steps would you suggest adding/updating to test rail? i can create an issue to get that updated.

**Comment by situchan** [comment] 2023-10-30 15:46
> @situchan - which steps would you suggest adding/updating to test rail? i can create an issue to get that updated.

https://github.com/Expensify/App/issues/21527#issuecomment-1743015904

**Comment by maddylewis** [comment] 2023-11-02 01:04
cool, already added - https://github.com/Expensify/Expensify/issues/324787

**Closed by maddylewis** 2023-11-02 01:04 UTC
Labels: External, Daily, Help Wanted, Bug
