### ISSUE TITLE
Web - Language is out of sync when logging in to another device

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#22106] opened 2023-07-03 13:29 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Login account A on device 1
2. Go Setting => Preference => Language
3. Change language to "Spanish"
4. Login account A on on device 2, observed that the language is not the same as device 1

## Expected Result:
The language of the 2 devices must be the same

## Actual Result:
The language is not the same as device 1

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [x] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 1.3.35-5
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/93399543/08bde6f0-9763-4249-93b9-512f38359fd5

https://github.com/Expensify/App/assets/93399543/29c46209-d781-4463-8367-9a0c2ef087e2

**Expensify/Expensify Issue URL:**
**Issue reported by:** @namhihi237
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1688272791784679

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by laurenreidexpensify** [comment] 2023-07-04 09:17
@namhihi237 When you say two devices here - do you mean two web browsers? When I change the language on web Chrome on staging it updates my Android device is updating, so would be good to get clarity what the exact devices are. Thanks!

**Comment by laurenreidexpensify** [comment] 2023-07-06 07:29
I cannot reproduce this on my end, it updates both ways when I have tested this, so closing

**Closed by laurenreidexpensify** 2023-07-06 07:29 UTC
Labels: Daily, Bug
