### ISSUE TITLE
[$1000] Anchor Payment Details Skeleton UI to Top not Bottom

### ISSUE THREAD

**Issue by dangrous** [Expensify/App#24647] opened 2023-08-16 20:38 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
Break down in numbered steps
1. Click on FAB icon
2. Click on 'Request money'
3. Enter amount & click on 'Next' button
4. Search user
5. Select user
6. Go to that user's account and that request
7. Click on 'I will settle up elsewhere' button
8. Click on settled up message
9. Turn your connection offline
10. Click on the sent money preview component

## Expected Result:
Skeleton UI should be anchored to the top of the view

## Actual Result:
Skeleton UI is anchored to the bottom of the view

## Workaround:
Can the user still use Expensify without this being fixed? Have you informed them of the workaround?

Yes, not blocking.

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [X] Android / native
- [X] Android / Chrome
- [X] iOS / native
- [X] iOS / Safari
- [X] MacOS / Chrome / Safari
- [X] MacOS / Desktop

**Version Number:** 
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:** not a regression
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:**
Any additional supporting documentation
https://github.com/Expensify/App/issues/19442#issuecomment-1679795540
<img width="1156" alt="Screenshot 2023-08-16 at 15 36 41" src="https://github.com/Expensify/App/assets/5487802/71c315fb-047e-4ff5-9e96-11504e028266">
**Expensify/Expensify Issue URL:**
**Issue reported by:** @dangrous 
**Slack conversation:**

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01109ef2c8bfb13e85</li>
        <li>Upwork Job ID: 1692495002835177472</li>
        <li>Last Price Increase: 2023-08-18</li>
    </ul>
</details>

**Comment by akinwale** [comment] 2023-08-17 00:42
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
The skeleton UI loading view looks like it is anchored to the bottom of the report, not the UI.

### What is the root cause of that problem?
The skeleton UI view height does not take into account the height of the report header, so the report header covers the top area of the skeleton UI view.

### What changes do you think we should make in order to solve the problem?


### What alternative solutions did you explore? (Optional)

**Comment by flaviadefaria** [comment] 2023-08-18 11:15
@isabelastisser I'm heading OoO for a week so re-assigning this issue in the meantime.

**Comment by blazejkustra** [comment] 2023-08-18 11:54
I don't entirely agree that skeleton should be anchored from the top of the chat. Skeleton UI should mimic how messages are displayed and messages are anchored from the bottom:
![image](https://github.com/Expensify/App/assets/46095609/b8239f48-8512-49bc-a45f-11d4827520ce)

That being said I don't think it is a bug.

**Comment by dangrous** [comment] 2023-08-18 16:22
Coz that's what @shawnborton [said](https://github.com/Expensify/App/issues/19442#issuecomment-1679795540) :) . But if we confirm that all chat skeletons should start from the bottom instead we can rethink. I do agree that it should be consistent

**Comment by shawnborton** [comment] 2023-08-18 16:24
Bottom makes sense. I am mostly passionate that we follow the same pattern everywhere, so if we use bottom-anchored for chats, let's do that everywhere.

**Comment by dangrous** [comment] 2023-08-18 16:51
Oh okay so maybe I was mistaken. It looks like normal chats are anchored to the bottom. If so, I think we're aligned. Can anyone double check for me?

I think we can close this, if that's indeed the case.

**Comment by isabelastisser** [comment] 2023-08-21 13:59
@dangrous I agree that this seems to be expected behavior, so I will close this now. Thanks!

**Closed by isabelastisser** 2023-08-21 13:59 UTC
Labels: External, Daily, Help Wanted, Overdue, Bug
