### ISSUE TITLE
[HOLD for payment 2023-10-09] [$500] Web - Can edit private note of archived workspace using URL

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#27891] opened 2023-09-20 20:32 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Go to https://staging.new.expensify.com
2. Click on the #admins room of a workspace
3. Click on the room details > Privacy Notes > My Note > Note
4. Create a note > Save
5. Copy the URL
6.  Delete that workspace
7. Past the copied URL

## Expected Result:
User should not be able to edit private note of archived workspace

## Actual Result:
User is able to edit private note of archived workspace

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [x] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 1.3.72.6
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation

[note-archived (1).webm](https://github.com/Expensify/App/assets/93399543/a5d40c58-2056-4ce3-a396-4080982329cb)

https://github.com/Expensify/App/assets/93399543/53a8d987-8d66-46d7-bb0d-b7ed37c9f823

**Expensify/Expensify Issue URL:**
**Issue reported by:** @hichamcc
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1695067265209059

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~011c113c6aa5282936</li>
        <li>Upwork Job ID: 1704594359596937216</li>
        <li>Last Price Increase: 2023-09-20</li>
<li>Automatic offers: </li>
<ul>
<li>jjcoffee | Reviewer | 26875976</li>
<li>dukenv0307 | Contributor | 26875977</li>
</ul></li>
    </ul>
</details>

**Comment by ahmedGaber93** [comment] 2023-09-20 20:32
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
Can edit private note of archived workspace using URL
### What is the root cause of that problem?
In `ReportDetailsPage.js` page, We hide private notes based on `isArchivedRoom`, but in `PrivateNotesEditPage.js` page we don't show not fount screen in this case.
### What changes do you think we should make in order to solve the problem?
we need to add condition `isArchivedRoom` in FullPageNotFoundView `shouldShow` 
```javascript
const isArchivedRoom = useMemo(() => ReportUtils.isArchivedRoom(report), [report]);

<FullPageNotFoundView
    shouldShow={..... || isArchivedRoom}
```
here
https://github.com/Expensify/App/blob/6d675529b2825b71c5c2bef332e7a07f0230c86f/src/pages/PrivateNotes/PrivateNotesEditPage.js#L84

We can apply the same fix in other notes pages, like PrivateNotesViewPage.js, PrivateNotesListPage.js ...
### What alternative solutions did you explore? (Optional)
we can instead allow displaying the private notes, but disable edit it when isArchived

**Comment by iamuddeshya** [comment] 2023-09-21 12:14
Suggestion: This must be handled on the backend as well. If the workspace is archived and yet a PUT/PATCH to Note is made, the backend must throw 405 [ Not Allowed ].

**Comment by jjcoffee** [comment] 2023-09-21 15:22
Reviewing tomorrow!

**Comment by jjcoffee** [comment] 2023-09-22 15:54
Assuming the expected behaviour is to display "not found", then since we have two pretty much identical proposals, we can go with @dukenv0307's [proposal](https://github.com/Expensify/App/issues/27891#issuecomment-1728385976) - it was first and LGTM!

:ribbon::eyes::ribbon: C+ reviewed

**Comment by ahmedGaber93** [comment] 2023-09-22 16:32
> since we have two pretty much identical proposals

Hi @jjcoffee 
I think my proposal is not identical, I propose to do this change in `PrivateNotesEditPage.js` and the other note page in the middle like `PrivateNotesViewPage.js`, and `PrivateNotesListPage.js`, but the other proposal doesn't.
Thanks!

**Comment by ahmedGaber93** [comment] 2023-09-23 07:37
@jjcoffee can you please give me the last opinion about this https://github.com/Expensify/App/issues/27891#issuecomment-1731714013

**Comment by jjcoffee** [comment] 2023-09-25 15:22
@ahmedGaber93 Small additional changes like those [you mention](https://github.com/Expensify/App/issues/27891#issuecomment-1731714013) can be addressed in the PR and don't usually influence proposal selection.

**Comment by ahmedGaber93** [comment] 2023-09-25 16:18
@jjcoffee I just thought this wouldn't be remembered, so I refer to it.
Thanks for your time.

**Comment by puneetlath** [comment] 2023-09-26 03:52
Cool, @dukenv0307's proposal sounds good to me. I'll also update the back-end to disallow editing this for archived rooms.

**Comment by Christinadobrzyn** [comment] 2023-10-10 18:51
@jjcoffee Can you complete the [checklist](https://github.com/Expensify/App/issues/27891#issuecomment-1743440382) and list any regression test steps?

Payouts due:

Issue Reporter: $50 @hichamcc - @hichamcc can you please accept my offer in Upwork?
Contributor: $500 + $250 bonus @dukenv0307
Contributor+: $500 + $250 bonus @jjcoffee 

Eligible for 50% #urgency bonus? Y - based on https://github.com/Expensify/App/issues/27891#issuecomment-1738710476

Upwork job is [here](https://www.upwork.com/jobs/~011c113c6aa5282936).

**Comment by hichamcc** [comment] 2023-10-10 23:29
@Christinadobrzyn accepted

**Comment by jjcoffee** [comment] 2023-10-11 08:45
**Regression Test Proposal**

1. On any workspace's #admin room, open the details pane and create a note and save it
2. Copy the URL to the edit note page
3. Delete the workspace
4. Paste the copied URL and verify that the "not found" screen shows

Do we agree 👍 or 👎

**Comment by Christinadobrzyn** [comment] 2023-10-11 20:23
Thanks! Test regression made and paid out based on https://github.com/Expensify/App/issues/27891#issuecomment-1756046287

Closing!

**Closed by Christinadobrzyn** 2023-10-11 20:23 UTC
Labels: External, Daily, Awaiting Payment, Bug
