### ISSUE TITLE
Android - Thread - Thread header is truncated in Android app

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#34514] opened 2024-01-15 16:35 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.25-1
**Reproducible in staging?:** Y
**Reproducible in production?:** N
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** Applause - Internal Team
**Slack conversation:**

**Issue found when executing PR** https://github.com/Expensify/App/pull/33365
## Action Performed:
1. Open the app
2. Navigate to any chat
3. Send a message
4. Long tap on a message
5. Select "Reply in thread''

## Expected Result:
Thread header should display the email of the recipient user

## Actual Result:
Thread header is trotally truncated on Android app

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [ ] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details>  

https://github.com/Expensify/App/assets/78819774/78ffeaac-fe6b-4084-8d76-922827467caa

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by situchan** [comment] 2024-01-15 16:40
This seems to be dupe of #24339

**Comment by francoisl** [comment] 2024-01-15 17:46
I can't repro on 1.4.25-1 and 1.4.25-2. Going to remove the blocker label for now and check back after the next deploy if it's good to close.

<img width="1512" alt="Screenshot 2024-01-15 at 9 39 41 AM" src="https://github.com/Expensify/App/assets/2229301/4795a592-685e-4463-bcfd-13bc512d39bb">
<img width="1512" alt="Screenshot 2024-01-15 at 9 39 20 AM" src="https://github.com/Expensify/App/assets/2229301/8ce0dbc4-3523-471d-95ca-605d97023d48">

**Comment by francoisl** [comment] 2024-01-17 22:03
Can't repro on v1.4.26 either.

**Closed by francoisl** 2024-01-17 22:02 UTC
Labels: Engineering, Daily, Overdue
