### ISSUE TITLE
Split bill - Receiver can't see "Split bill $" at the LHN in case of long Sender's name/email

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#21003] opened 2023-06-19 00:40 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___
**Issue found when executing PR** https://github.com/Expensify/App/pull/20752
## Action Performed:
1. Create a Split bill (with a long Sender's email/name)
2. Check the Receiver's side LHN

## Expected Result:
Receiver side should see "Split bill $summ" text at the LHN

## Actual Result:
In case of long Sender's email/name there is not enough room at the LHN to see "Split bill $summ" on the Receiver's side

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [x] MacOS / Chrome / Safari
- [x] MacOS / Desktop

**Version Number:** 1.3.29.0

**Reproducible in staging?:** Yes

**Reproducible in production?:** Yes

**If this was caught during regression testing, add the test name, ID and link from TestRail:**

**Email or phone of affected tester (no customers):**

**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/78819774/2077fd90-a97e-4078-a570-a6f3f29cf878

**Expensify/Expensify Issue URL:**

**Issue reported by:** Applause - Internal Team

**Slack conversation:**

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by MitchExpensify** [comment] 2023-06-19 21:55
Unable to reproduce on Chrome:

<img width="396" alt="image" src="https://github.com/Expensify/App/assets/36425901/ffcf3dc4-8589-4c12-b12c-e5e57dc1bf2e">

**Comment by MitchExpensify** [comment] 2023-06-19 21:58
Or on the desktop app:

<img width="381" alt="image" src="https://github.com/Expensify/App/assets/36425901/fb1c9177-17a2-4840-8dd8-6e12d3ac687e">

Closing until we have reliable reproduction steps!

**Closed by MitchExpensify** 2023-06-19 21:58 UTC
Labels: Daily, Needs Reproduction, Bug

**Comment by MitchExpensify** [comment] 2023-06-21 18:59
I am unable to reproduce using the step in the main issue. What steps are you following @spcheema ? Perhaps I can try them with more success
