### ISSUE TITLE
On creating a workspace we should navigate the user to the general settings page of workspace - Reported by @Puneet-here

### ISSUE THREAD

**Issue by mvtglobally** [Expensify/App#8938] opened 2022-05-11 04:07 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Problem: 
1. When you create a workspace from an old workspace it looks like that you are on the previous workspace which is confusing.
2. After creating a workspace you have to go to the settings to change its name and avatar, (generally after creating something users expect to get navigated to the settings to customize what they just created)

## Solution: 
After creating a workspace navigate the user to general settings of that new workspace. 

## Action Performed:
1. Create workspace 
2. Navigate to Settings > Workspace 
3. Click ... > New Workspace on top 

## Expected Result:
After creation, user should navigate to the general settings page of workspace

## Actual Result:
User is in the settings of the previous workspace 

## Workaround:
Can the user still use Expensify without this being fixed? Have you informed them of the workaround?

## Platform:

Where is this issue occurring?

- Web
- iOS
- Android
- Desktop App
- Mobile Web

**Version Number:** 1.1.57-12
**Reproducible in staging?:** Y 
**Reproducible in production?:** Y 
**Email or phone of affected tester (no customers):** 
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation 
![Screen Shot 2022-05-11 at 12 06 48 AM](https://user-images.githubusercontent.com/43995119/167767170-ed3e3dc1-6d84-4f77-b2a3-07d89b7dbeb0.png)

**Expensify/Expensify Issue URL:** 
**Issue reported by:** @Puneet-here
**Slack conversation:** https://expensify.slack.com/archives/C01GTK53T8Q/p1650459643371259

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by alex-mechler** [comment] 2022-05-11 23:24
Hmm, while testing locally, I can confirm I am brought to the new workspace, not left on the old one. It appears like you were left on the old one, but if you have set a name on the existing workspace, you will see that you have been transitioned to the new one

https://recordit.co/i7YQZVPbHl

Am I missing something here? This was tested on web

**Comment by Puneet-here** [comment] 2022-05-12 06:13
Hi @alex-mechler, after creating a new workspace the user should be navigated to the general settings page of that new workspace where he can change the name avatar of the workspace

**Comment by alex-mechler** [comment] 2022-05-12 23:41
I'm not sure that we want to redirect to the general settings in this case. If we direct to the general workspace overview, the user gets to see all the features for their new workspace, instead of just a few settings

@trjExpensify do you have any thoughts here?

**Comment by trjExpensify** [comment] 2022-05-12 23:41
I tried to reproduce this on the latest on web as well, and I can't produce the same result as reported.

1. I'm navigated to the new workspace to the main workspace settings page, which is the expected behaviour
2. I receive the confirmation growl that the new workspace was created 
3. I receive the notification from Concierge that the new workspace was created

Given that we both can't reproduce this and it's the intended behaviour, I'm going to close this issue out.

**Closed by trjExpensify** 2022-05-12 23:41 UTC
Labels: Engineering, Daily, NewFeature
