### ISSUE TITLE
Error message appears while changing Distance unit in workspace multiple times

### ISSUE THREAD

**Issue by kavimuru** [Expensify/App#24220] opened 2023-08-07 15:56 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1- go to #admin chat of a workspace
2- go to details => Reimbursements
3- change distance unit multiple times
## Expected Result: 
The message " updated the pendingAction of the Distance rate "Default Rate" from "" to "update" Should not appear
## Actual Result: 
updated the pendingAction of the Distance rate "Default Rate" from "" to "update" Appears
## Workaround:
Can the user still use Expensify without this being fixed? Have you informed them of the workaround?

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [x] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 1.3.50-0
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation

[distance-bug (1).webm](https://github.com/Expensify/App/assets/43996225/9ec51b6a-dc62-44c6-bda2-7cf7548bb12e)

https://github.com/Expensify/App/assets/43996225/718a88e0-fd35-47b8-8663-38a22d1bd05b

**Expensify/Expensify Issue URL:**
**Issue reported by:** @hichamcc
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1690894613800769

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by joekaufmanexpensify** [comment] 2023-08-07 20:11
Unable to reproduce this. Further, in the second video in OP (which I'm thinking is @kavimuru's reproduction attempt), the message referenced in OP as being the bug does not appear. 


https://github.com/Expensify/App/assets/54866469/1d7faa8d-5341-43c8-8a5a-e24619006a7e

**Comment by joekaufmanexpensify** [comment] 2023-08-07 20:13
Closing for now as it seems like this is fixed/is no longer reproducible. Commented in the Slack thread, and will revisit if others can still reproduce this!

**Closed by joekaufmanexpensify** 2023-08-07 20:13 UTC
Labels: Daily, Bug
