### ISSUE TITLE
[HOLD for payment 2023-07-10] [$1000] Web- Chat - Unable to leave the Concierge "Welcome Message" thread

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#20197] opened 2023-06-05 19:31 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Sign in with a new account
2. Go to the Concierge chat
3. Hover over the welcome message from Concierge
4. Click on Reply in thread icon
5. Click on thread header
6. Click on Leave thread

Note: this only occurs on the Welcome message

## Expected Result:
Thread is no longer there on LHN

## Actual Result:
Thread is still there on LHN

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [x] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** v1.3.24-4

**Reproducible in staging?:** yes

**Reproducible in production?:* n/a

**If this was caught during regression testing, add the test name, ID and link from TestRail:**

**Email or phone of affected tester (no customers):**

**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/93399543/0a7efa97-90e6-47b9-a28a-26bf0e8dfe63

**Expensify/Expensify Issue URL:**

**Issue reported by:** @adeel0202 

**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1685376970661379

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~0168a95ee497fd9964</li>
        <li>Upwork Job ID: 1665923109054201856</li>
        <li>Last Price Increase: 2023-06-06</li>
    </ul>
</details>

**Comment by jliexpensify** [comment] 2023-06-06 01:33
We're on staging v1.3.24-4, please re-test on the newest version.

I am not seeing this issue on my end.

**Comment by esh-g** [comment] 2023-06-06 03:01
@jliexpensify I'm still able to reproduce on `staging` `v1.3.24-4`

https://github.com/Expensify/App/assets/77237602/3b9b167f-e1b8-4a7a-b0b3-e66b5e4f148c

**Comment by esh-g** [comment] 2023-06-06 03:08
# Proposal
posted in [slack](https://expensify.slack.com/archives/C049HHMV9SM/p1685625153024239?thread_ts=1685376970.661379&cid=C049HHMV9SM) 5 days ago

## Please re-state the problem that we are trying to solve in this issue
Unable to leave the thread that was created with Concierge

## What is the root cause of that problem?
https://github.com/Expensify/App/blob/edf9b18fb72c28530a4d70ea22d69eefcb970210/src/libs/actions/Report.js#L761-L772
In `Report.js` we are updating `conciergeChatReportID` in the `handleReportChanged` function and when we create a new thread from concierge chat, this gets updated to the chat thread instead of the actual concierge report. Therefore, when we exit the thread, it tries to direct the user to what it thinks is concierge chat but actually is the chat that we left.

## What changes do you think we should make in order to solve the problem?
Before updating `conciergeChatReportID`, we are checking if it is concierge by the `ReportUtils.isConciergeChatReport()` method
https://github.com/Expensify/App/blob/edf9b18fb72c28530a4d70ea22d69eefcb970210/src/libs/ReportUtils.js#L376-L378
So, we need to add an additional condition to this method `report.parentReportID === null` .  So we can use the function `isThread(report)` to do that as well. This will make sure that we don't set a thread of concierge as the conciergeChatReportID and this successfully eliminates this issue. 

Complete implementation
```js
function isConciergeChatReport(report) {
    return lodashGet(report, 'participants', []).length === 1 && report.participants[0] === CONST.EMAIL.CONCIERGE && !isThread(report);
}
```
## What alternative solutions did you explore? (Optional)

**Comment by jliexpensify** [comment] 2023-06-06 03:23
Thanks @esh-g for testing - so I misunderstood the original issue and tested on a standard thread in Concierge, which works as normal.

I can repro the behaviour with the Concierge auto-message, but I would also say an additional issue is that Concierge is duplicating the exact same message in-thread (when you leave it):

![image](https://github.com/Expensify/App/assets/30815269/8a123254-0e66-405a-b6a8-a22bee2bb213)

**Comment by esh-g** [comment] 2023-06-06 04:04
> additional issue is that >Concierge is duplicating the >exact same message in-thread >(when you leave it):

There is an issue for that also

**Comment by jliexpensify** [comment] 2023-06-06 04:07
Oh, you're right - https://github.com/Expensify/App/issues/19982. I'll amend the title.

**Comment by Santhosh-Sellavel** [comment] 2023-06-07 19:15
@tylerkaraszewski  @esh-g's [proposal](https://github.com/Expensify/App/issues/20197#issuecomment-1577829745) looks good to me. Let me know your thoughts, thanks!

**Comment by Santhosh-Sellavel** [comment] 2023-06-08 02:44
It's okay to proposal the solution on slack. And Bring to github for review before it's too late.

**Comment by esh-g** [comment] 2023-06-08 03:56
@dukenv0307  There anyway is a difference in our approaches. I'm choosing to amend the `ReportUtils.isConciergeReport` method itself while you are adding the condition at one level upper than that. I think it's better to to amend the the method itself

**Comment by esh-g** [comment] 2023-06-08 04:13
In all the other instances of this method, we are not considering for a concierge thread as that is a relatively new addition. 

For example here:
https://github.com/Expensify/App/blob/78aa3bab34b305f9f3aa818ce501c6f133881200/src/libs/SidebarUtils.js#L105
This code was written considering only the main `concierge` parent report. Although it doesn't matter much in this case, I would say the original intention of this function would be to identify only one thread which is the main `concierge` as we are using `find` and not `findAll`.

But still, I would let @Santhosh-Sellavel be the judge of that, I'm fine with any approach we go with 😇

**Comment by esh-g** [comment] 2023-06-08 11:07
@dukenv0307 The above points are not true. Please test before stating.

1. We do get the concierge icon for a thread as well because that is the default behaviour for all threads.
2. It doesn't show flag as offensive because see just the next line after the one you posted 😅
https://github.com/Expensify/App/blob/b8d45763b6d9dcf011ab66936df7eba85b80bc24/src/pages/home/report/ContextMenu/ContextMenuActions.js#L304-L305
If it is concierge email, then you cannot flag it as offensive.

Moreover, you brought this to my attention that currently if we invite another person to a concierge thread (with the QR code) I think we would not be even able to mark their comments as offensive with your proposal. Although while testing I was unable to invite another person despite there being an option to share the QR 🤔

But anyway, let's leave it to the reviewers to check 😇

**Comment by Santhosh-Sellavel** [comment] 2023-06-12 19:40
@tylerkaraszewski 

I still like the @esh-g [proposal](https://github.com/Expensify/App/issues/20197#issuecomment-1577829745) here. Thats the straight forward thing to improve `isConciergeChatReport` and fix the issue.

C+ Reviewed
🎀 👀 🎀

**Comment by Santhosh-Sellavel** [comment] 2023-06-12 19:43
@dukenv0307 I verified [this](https://github.com/Expensify/App/issues/20197#issuecomment-1582348551). I don't see any improvement.

Both are invalid 
1. Thread Icon is based on the actor/author of the message from which the thread is created.
2. Flag as offensive is not shown for the Concierge or Concierge's message. That's working fine.

**Comment by Santhosh-Sellavel** [comment] 2023-06-13 12:43
Yeah but that's good catch. It's better to leave a comment on the PR where it was added to get feedback why it was added in the first place.

**Comment by Santhosh-Sellavel** [comment] 2023-06-16 20:15
@jliexpensify we are waiting for @tylerkaraszewski here, if they are unavailable please assign a new CME thanks!

**Comment by jliexpensify** [comment] 2023-06-19 05:19
Hmm looks like @tylerkaraszewski is around - could you review this [recommendation](https://github.com/Expensify/App/issues/20197#issuecomment-1587964354) from Santhosh?

**Comment by Santhosh-Sellavel** [comment] 2023-06-20 17:32
Still waiting for @tylerkaraszewski Can you reassign a new CME here, thanks!

**Comment by jliexpensify** [comment] 2023-06-22 05:29
Hi @bondydaa - could you approve [this proposal](https://github.com/Expensify/App/issues/20197#issuecomment-1587964354)?

**Comment by bondydaa** [comment] 2023-06-23 21:37
please don't abuse the label system, why was engineering added here? 

i don't see why we even allow threading on the concierge welcome message that seems like the bug to me.

**Comment by Santhosh-Sellavel** [comment] 2023-06-23 22:36
@bondydaa We are waiting for CME here for the last two weeks that's why the engineering label was added again.

**Comment by tylerkaraszewski** [comment] 2023-06-23 23:26
Sorry about letting this one slip through the cracks.

**Comment by esh-g** [comment] 2023-06-24 19:43
@Santhosh-Sellavel The PR is here https://github.com/Expensify/App/pull/21481

**Comment by jliexpensify** [comment] 2023-06-25 22:43
Hired @adeel0202 and @Santhosh-Sellavel . @esh-g - your profile (I assume it's "Esh G.") seems to have an issue when I invite it...it says it doesn't exist?

**Comment by esh-g** [comment] 2023-06-26 04:13
@jliexpensify I submitted a proposal for the job. Here is my profile: https://www.upwork.com/freelancers/~0186b1d7cc69656f22

**Comment by jliexpensify** [comment] 2023-06-26 04:58
Oh, ok - different profile, thanks @esh-g!

**Comment by esh-g** [comment] 2023-06-26 05:02
> Oh, ok - different profile, thanks @esh-g!

Thanks for sending the offer! I have accepted it 👍

**Comment by tylerkaraszewski** [comment] 2023-06-28 19:50
PR is merged.

**Comment by tylerkaraszewski** [comment] 2023-06-30 16:57
@jliexpensify - I am leaving on sabbatical today. I don't expect this issue to need any further engineering input, but if it does, please unassign me and re-apply the `Engineering` label to get a new engineer to finish this issue, as I'll be out until the end of August.

**Comment by jliexpensify** [comment] 2023-07-11 04:49
@Santhosh-Sellavel before any payments are made, can you please complete the checklist? I'll also need to assign a new Engineer to review this checklist, as Tyler is on sabbatical.

**Comment by esh-g** [comment] 2023-07-13 17:10
bump @Santhosh-Sellavel

**Comment by Santhosh-Sellavel** [comment] 2023-07-13 17:40
> **BugZero Checklist:** The PR fixing this issue has been merged! The following checklist ([instructions](https://stackoverflow.com/c/expensify/questions/14574)) will need to be completed before the issue can be closed:
> 
> * [x]  [@Santhosh-Sellavel] The PR that introduced the bug has been identified. Link to the PR: https://github.com/Expensify/App/pull/18772
> * [x]  [@Santhosh-Sellavel] The offending PR has been commented on, pointing out the bug it caused and why, so the author and reviewers can learn from the mistake. Link to comment: https://github.com/Expensify/App/pull/18772#issuecomment-1634642989
> * [x]  [@Santhosh-Sellavel] A discussion in #expensify-bugs has been started about whether any other steps should be taken (e.g. updating the PR review checklist) in order to catch this type of bug sooner. Link to discussion: Not need we could have caught this while testing.
> * [x]  [@Santhosh-Sellavel] Determine if we should create a regression test for this bug. N/A We can skip here as it a minor.
> * [x]  [@Santhosh-Sellavel] If we decide to create a regression test for the bug, please propose the [regression test](https://github.com/Expensify/App/blob/main/contributingGuides/REGRESSION_TEST_BEST_PRACTICES.md) steps to ensure the same bug will not reach production again. N/A
> * [x]  [@jliexpensify] Link the GH issue for creating/updating the regression test once above steps have been agreed upon:

Let me know your thoughts thanks @jliexpensify!

**Comment by jliexpensify** [comment] 2023-07-14 00:28
@Santhosh-Sellavel just checking, no regression test needed?

**Comment by jliexpensify** [comment] 2023-07-14 00:31
Paid @adeel0202 and @esh-g . @Santhosh-Sellavel - i';=ll let you record your own payment (you qualify for a bonus). Job closed and removed1

**Closed** 2023-07-14 00:33 UTC
Labels: External, Daily, Awaiting Payment, Bug

**Comment by Santhosh-Sellavel** [comment] 2023-07-14 22:54
Requested Payment on ND

**Comment by anmurali** [comment] 2023-07-18 18:06
Approved $1500 with bonus for Santhosh on ND
