### ISSUE TITLE
[HOLD for payment 2023-10-30] [$250] IOU - Text under "category" header is not displayed

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#28952] opened 2023-10-05 19:20 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Go to https://staging.new.expensify.com/

2. Tap on Workspace chat
3. Tap plus icon
4. Tap request money
5. Enter an amount
6. Tap next
7. Tap show more
8. Tap categories

## Expected Result:
In the header " category" , the text "Select a category to help organize your money, or we’ll auto-categorize it for you” must be displayed

## Actual Result:
In the header " category" , the text "Select a category to help organize your money, or we’ll auto-categorize it for you” is not displayed

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android / native
- [x] Android / Chrome
- [x] iOS / native
- [x] iOS / Safari
- [x] MacOS / Chrome / Safari
- [x] MacOS / Desktop

**Version Number:** 1.3.78-0

**Reproducible in staging?:** Yes

**Reproducible in production?:** Yes

**If this was caught during regression testing, add the test name, ID and link from TestRail:**

**Email or phone of affected tester (no customers):**

**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/78819774/10d9ce64-0a0e-426d-9cc6-5a40b2ddc75f

**Expensify/Expensify Issue URL:**

**Issue reported by:** Applause - Internal Team

**Slack conversation:**

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01298a914a67495601</li>
        <li>Upwork Job ID: 1710257172167360512</li>
        <li>Last Price Increase: 2023-10-09</li>
<li>Automatic offers: </li>
<ul>
<li>DylanDylann | Contributor | 27123526</li>
</ul></li>
    </ul>
</details>

**Comment by DylanDylann** [comment] 2023-10-06 05:42
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
Text under "category" header is not displayed

### What is the root cause of that problem?
<img width="383" alt="Screenshot 2023-10-06 at 12 34 25" src="https://github.com/Expensify/App/assets/141406735/b1495602-38f3-4967-9266-236ca8e59017">

Let's see the Tag Page (MoneyRequestTagPage Component), we are displaying the subtitle 

But in the Edit Tag page (EditRequestTagPage Component), Category Page and Edit Category Page, we don't have logic to display the subtitle.
### What changes do you think we should make in order to solve the problem?
1. Edit Tag page (EditRequestTagPage Component)
Add a new Text like we did in MoneyRequestTagPage Component
https://github.com/Expensify/App/blob/779a1e5b5ee19ac2b8e54d047507f90db01df689/src/pages/iou/MoneyRequestTagPage.js#L84

2. For Category Feature
We need to define new translation key like we did with tag feature
https://github.com/Expensify/App/blob/779a1e5b5ee19ac2b8e54d047507f90db01df689/src/languages/en.ts#L561

Then add the subtitle to Category Page and Edit Category Page like we did with Tag feature above


### What alternative solutions did you explore? (Optional)

**Comment by laurenreidexpensify** [comment] 2023-10-06 11:05
Isa is OOO, manually reassigning to move forward while she's offline

**Comment by puneetlath** [comment] 2023-10-09 12:44
@greg-schroeder I'll take this over from you. Looks like this was just an oversight when we implemented the page. 

I'm going to reduce this to a $250 issue. @DylanDylann if you are still down for it, your solution seems to make sense to me. But let's wait for @Santhosh-Sellavel to weigh in as well.

**Comment by Santhosh-Sellavel** [comment] 2023-10-09 19:30
Yes, @DylanDylann's Proposal looks good to me!
C+ Reviewed
🎀 👀 🎀 

@puneetlath But How to  test tags?

**Comment by puneetlath** [comment] 2023-10-10 16:41
This issue is for Categories, so you can test it by creating a free workspace and then making a request in the workspace chat. That request will have the category selector.

**Comment by DylanDylann** [comment] 2023-10-10 16:43
@puneetlath How we can test Tag feature?

**Comment by puneetlath** [comment] 2023-10-10 16:45
Ahh ok. Here's how you can test tags: 
1. On OldDot (www.expensify.com) create a Collect policy
2. Go to the Collect policy's settings and add some tags
3. Open the JS console while in the policy settings and do:
a. p = Policy.getCurrent();
b. p.policy.isPolicyExpenseChatEnabled = "true";
c. p.save();
4. Invite a new user to the policy
5. Log into NewDot with the new user
6. You should see a workspace chat for that user and be able to make requests against it. You should see the categories and tags fields on the request (you'll need to enable all betas locally)

**Comment by DylanDylann** [comment] 2023-10-11 07:51
@puneetlath @greg-schroeder 

Anyone help to confirm the copy translation for subtitle in Category Page, currently I copied from TagPage like this
en.ts: Select a ${categoryName} to add additional organization to your money
es.ts: Seleccione una ${categoryName} para organizar mejor tu dinero

**Comment by DylanDylann** [comment] 2023-10-11 09:39
@Santhosh-Sellavel The PR is ready for review

**Comment by Santhosh-Sellavel** [comment] 2023-10-11 18:14
@puneetlath I'm confused too, why did I get unassigned here?

**Comment by puneetlath** [comment] 2023-10-11 19:41
@Santhosh-Sellavel my bad, must've done that on accident. I've re-assigned you.

**Comment by puneetlath** [comment] 2023-10-30 14:56
@Santhosh-Sellavel friendly reminder on the checklist so we can pay 😄

**Comment by puneetlath** [comment] 2023-11-03 14:01
@Santhosh-Sellavel just waiting on the checklist.

**Comment by Santhosh-Sellavel** [comment] 2023-11-06 16:40
**BugZero Checklist:** The PR fixing this issue has been merged! The following checklist ([instructions](https://stackoverflow.com/c/expensify/questions/14574)) will need to be completed before the issue can be closed:

* [x]  [@Santhosh-Sellavel] The PR that introduced the bug has been identified. Link to the PR: https://github.com/Expensify/App/pull/25470
https://github.com/Expensify/App/pull/27459
* [x]  [@Santhosh-Sellavel] The offending PR has been commented on, pointing out the bug it caused and why, so the author and reviewers can learn from the mistake. Link to comment: https://github.com/Expensify/App/pull/25470#issuecomment-1795407879 https://github.com/Expensify/App/pull/27459#issuecomment-1795418505
* [x]  [@Santhosh-Sellavel] A discussion in #expensify-bugs has been started about whether any other steps should be taken (e.g. updating the PR review checklist) in order to catch this type of bug sooner. Link to discussion: N/A As said this is little oversight we can skip this
* [x]  [@Santhosh-Sellavel] Determine if we should create a regression test for this bug. I guess not, because it is from applause/QA should already have this covered.
* [x]  [@Santhosh-Sellavel] If we decide to create a regression test for the bug, please propose the [regression test](https://github.com/Expensify/App/blob/main/contributingGuides/REGRESSION_TEST_BEST_PRACTICES.md) steps to ensure the same bug will not reach production again.
* [x]  [@puneetlath] Link the GH issue for creating/updating the regression test once above steps have been agreed upon:

@puneetlath Let me know if you differ on any of the above, thanks!

**Closed** 2023-11-06 16:50 UTC
Labels: External, Daily, Awaiting Payment, Bug

**Comment by JmillsExpensify** [comment] 2023-12-11 01:16
$250 payment approved for @Santhosh-Sellavel based on comment above.
