### ISSUE TITLE
Chat - New marker displayed briefly when chat is opened

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#25673] opened 2023-08-22 13:25 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___
**Issue found when executing PR** https://github.com/Expensify/App/pull/18637
## Action Performed:
1. Log in as user B on the main device and as user A on another device
2. Open the chat between users B and A on the main device
3. Send the message as user A to user B from the secondary device

## Expected Result:
The marker "New" is not displayed for both users

## Actual Result:
The marker "New" is displayed briefly for user B on the main device (android)

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android / native
- [ ] Android / Chrome
- [x] iOS / native
- [ ] iOS / Safari
- [ ] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 1.3.56-2

**Reproducible in staging?:** Yes

**Reproducible in production?:** No

**If this was caught during regression testing, add the test name, ID and link from TestRail:**

**Email or phone of affected tester (no customers):**

**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/78819774/c48b2f7d-9259-4158-aa35-439740a913a1

**Expensify/Expensify Issue URL:**

**Issue reported by:** Applause - Internal Team

**Slack conversation:**

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by srikarparsi** [comment] 2023-08-22 20:22
Hi @MonilBhavsar and @allroundexperts, do you think you could take a look at this deploy blocker. It seems to have been caused by this PR [here](https://github.com/Expensify/App/pull/18637).

**Comment by roryabraham** [comment] 2023-08-22 21:10
This is an deploy blocker so it supposed to be hourly. Not sure why melvin-bot decided to change that, but he's not supposed to. Anyways, reassigning this one to you @srikarparsi

**Comment by roryabraham** [comment] 2023-08-23 18:23
@MonilBhavsar is working on a fix: https://expensify.slack.com/archives/C01GTK53T8Q/p1692814036685529?thread_ts=1692748028.210719&cid=C01GTK53T8Q

**Comment by roryabraham** [comment] 2023-08-23 20:37
Not seeing enough movement here and it's the middle of the night for @MonilBhavsar so I'm going to jump in and try to help push this forward

**Comment by marcaaron** [comment] 2023-08-23 20:40
If the revert also solves this -> https://github.com/Expensify/App/issues/25688#issuecomment-1690542526

Should we just revert?

**Comment by roryabraham** [comment] 2023-08-23 20:48
I think I seeing that @JmillsExpensify said that the change is needed for wave1?

**Comment by roryabraham** [comment] 2023-08-23 22:11
Coming back to this, I'm not able to reproduce, because a worse bug is getting in the way:

https://github.com/Expensify/App/assets/47436092/7d289e0a-b23a-4b52-b75c-9881d33c07b0

This is probably a problem with my local pusher configuration, not a real bug

**Comment by roryabraham** [comment] 2023-08-23 23:02
Ok, after wrestling with my dev environment a bit I got set up and am not able to reproduce this bug on main:

https://github.com/Expensify/App/assets/47436092/bf6c1b74-af61-4e23-9349-93d92ca14082

**Comment by roryabraham** [comment] 2023-08-23 23:10
I'm trying to test the same thing on staging but unable to sign in (presumably due to the back-end site outage)

**Comment by roryabraham** [comment] 2023-08-23 23:29
Not able to reproduce on staging either. Going to demote this one to regular bug. @lanitochka17 are you or your team still able to reproduce this?

**Comment by mountiny** [comment] 2023-08-23 23:43
I can repro with latest staging iOS on physical device but I dont think its a deploy blocker
https://github.com/Expensify/App/assets/36083550/2a54376f-bd35-4837-8320-34c5cf5d3863

**Comment by roryabraham** [comment] 2023-08-23 23:46
Odd, it was not happening for me on latest staging w/ iOS or Android physical devices

**Comment by MonilBhavsar** [comment] 2023-08-24 05:45
Yes, it's flaky but it happens sometimes.

**Comment by MonilBhavsar** [comment] 2023-08-28 13:15
Still investigating!

**Comment by srikarparsi** [comment] 2023-08-28 20:48
Un-assigning since @MonilBhavsar is in the process of investigating.

**Comment by gedu** [comment] 2023-09-01 05:42
Hey I'm Edu from Callstack, and I've been working on unread refactor

**Comment by MonilBhavsar** [comment] 2023-09-01 05:57
Eduardo will be helping with investigation here

**Comment by MonilBhavsar** [comment] 2023-09-04 19:55
Bumped to weekly, as happening rarely

**Comment by MonilBhavsar** [comment] 2023-09-13 09:28
Making it daily again as we can reproduce by sending successive messages and focussing on and off the chat screen. Also, we want to close the project soon

**Comment by MonilBhavsar** [comment] 2023-09-19 00:46
@gedu has a got a draft up. I need to review. Been tackling critical issue in parallel.

**Comment by MonilBhavsar** [comment] 2023-09-27 05:30
PR is being reviewed

**Comment by MonilBhavsar** [comment] 2023-12-28 11:15
This is fixed. No action required here. Closing

**Closed by MonilBhavsar** 2023-12-28 11:15 UTC
Labels: Reviewing, Engineering, Monthly
