### ISSUE TITLE
[$1000] mWeb - Chat - The chat window is visible in a blue frame when editing a message and opening the emoji picker

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#22955] opened 2023-07-15 20:19 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Go to staging.new.expensify.com
2. Post message in chat
3. Long tap on message and select 'Edit message'
4. Click emoji picker

## Expected Result:
There should be no blue border when opening the emoji picker

## Actual Result:
When editing messages and clicking on an emoji, the chat window is visible in a blue frame

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [x] iOS / Safari
- [ ] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 1.3.41.2

**Reproducible in staging?:** Yes

**Reproducible in production?:** No

**If this was caught during regression testing, add the test name, ID and link from TestRail:**

**Email or phone of affected tester (no customers):**

**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Notes/Photos/Videos:** Any additional supporting documentation
 
https://github.com/Expensify/App/assets/78819774/996e7560-8c42-45a8-a4d0-a83414c2ec57

https://github.com/Expensify/App/assets/78819774/df14520d-b855-4e03-ad6e-767ecb4ca0be

![зображення_viber_2023-07-15_15-33-08-586 (1)](https://github.com/Expensify/App/assets/78819774/f2abe910-eae7-42ed-a4c2-91d226ccad50)

**Expensify/Expensify Issue URL:**

**Issue reported by:** Applause - Internal Team

**Slack conversation:**
<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01f0dc397dc0cc64cb</li>
        <li>Upwork Job ID: 1681648827715117056</li>
        <li>Last Price Increase: 2023-07-26</li>
    </ul>
</details>

**Comment by getusha** [comment] 2023-07-16 15:03
reported similar issue 5 months ago https://expensify.slack.com/archives/C049HHMV9SM/p1677562433759409

**Comment by marcochavezf** [comment] 2023-07-17 14:14
I can reproducing it but the another component is highlighted

https://github.com/Expensify/App/assets/6829422/baa34cdf-6d32-4170-946f-f5c56e45f843

**Comment by marcochavezf** [comment] 2023-07-17 14:17
I can reproducing in production too. So I'm going to remove the deploy blocker and mark it as bug.

![image](https://github.com/Expensify/App/assets/6829422/c4018642-832e-4635-84d4-c56b742f3d38)

**Comment by muttmuure** [comment] 2023-07-19 12:55
Thanks @marcochavezf!

**Comment by marcochavezf** [comment] 2023-07-25 02:25
Not overdue

**Comment by Talha345** [comment] 2023-07-27 18:08
Unable to reproduce

**Comment by marcochavezf** [comment] 2023-07-27 23:31
I'm also unable to reproduce it

![image](https://github.com/Expensify/App/assets/6829422/71ced1b6-22b4-4806-b7ee-b062c164ff7a)

**Comment by mananjadhav** [comment] 2023-07-29 19:58
I am also unable to reproduce this.

**Comment by mananjadhav** [comment] 2023-08-01 03:57
I think we should just close this if we're not able to reproduce this.

**Comment by JKobrynski** [comment] 2023-08-01 09:45
I couldn't reproduce this issue either.

**Comment by pac-guerreiro** [comment] 2023-08-01 10:33
I wasn't able to reproduce this in iPhone 14 Plus, using Safari and Firefox Focus

**Comment by marcochavezf** [comment] 2023-08-01 18:23
Thanks guys for testing it, I'm going to close it

**Closed by marcochavezf** 2023-08-01 18:23 UTC
Labels: External, Engineering, Daily, Help Wanted, Bug
