### ISSUE TITLE
[HOLD #29057] [$500] Search Icon in LHN is misaligned

### ISSUE THREAD

**Issue by m-natarajan** [Expensify/App#29870] opened 2023-10-18 15:24 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.3.86-1
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** @hungvu193 
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1697622324056149

## Action Performed:
1. Login with any account.
2. Observer the right spacing of Search icon.
## Expected Result: 
Search icon right spacing should be the same with left header spacing.
## Actual Result: 
Search icon right spacing is different with left header spacing.

## Workaround:
unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [x] Android: mWeb Chrome
- [x] iOS: Native
- [x] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos
<details>
<summary>Android: Native</summary>

</details>

<details>
<summary>Android: mWeb Chrome</summary>

</details>

<details>
<summary>iOS: Native</summary>

![simulator_screenshot_26C8E4F2-E98A-42A8-98F4-930099B7B18F](https://github.com/Expensify/App/assets/38435837/c576c1d1-95f6-4430-877c-9f533a9e0e11)

</details>

<details>
<summary>iOS: mWeb Safari</summary>

![Screenshot 2023-10-18 at 16 49 04](https://github.com/Expensify/App/assets/38435837/d924c78e-4fe3-4b96-92c5-fd8accdb122b)

</details>

<details>
<summary>MacOS: Chrome / Safari</summary>

![Screenshot 2023-10-18 at 16 48 30](https://github.com/Expensify/App/assets/38435837/408b3a03-4cea-4dc1-a010-c4af93f04388)

![2](https://github.com/Expensify/App/assets/38435837/6d523e86-a7ac-42f9-82d2-a2bb65399b4a)

</details>

<details>
<summary>MacOS: Desktop</summary>
![Screenshot 2023-10-18 at 16 45 47](https://github.com/Expensify/App/assets/38435837/3ec1f627-713b-4667-948f-6f8252966120)

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01f8fd3fddc118b87b</li>
        <li>Upwork Job ID: 1714663721263878144</li>
        <li>Last Price Increase: 2023-10-18</li>
    </ul>
</details>

**Comment by m-natarajan** [comment] 2023-10-18 15:25
## Proposal from contributor @hungvu193 

### Please re-state the problem that we are trying to solve in this issue.
The search icon in LHN is misaligned.
### What is the root cause of that problem?
In the past, the search icon is next to avatar, so it has its padding, however with the new UI we don't have the avatar in the header any more but we still keep the padding of search icon:
https://github.com/Expensify/App/blob/e8cb124e83c9ce588c1fb4402827880839ed88e9/src/pages/home/sidebar/SidebarLinks.js#L158
### What changes do you think we should make in order to solve the problem?
We should remove the `styles.ph5` from [here](https://github.com/Expensify/App/blob/e8cb124e83c9ce588c1fb4402827880839ed88e9/src/pages/home/sidebar/SidebarLinks.js#L158) 

### What alternative solutions did you explore? (Optional)
Incase we still wanna keep the paddingLeft we can replace the `styles.ph5` with `styles.pl5`.

**Comment by mallenexpensify** [comment] 2023-10-18 20:13
I'm unsure what the exact deliverable is here.  Commented in the Slack thread
https://expensify.slack.com/archives/C049HHMV9SM/p1697659934289569?thread_ts=1697622324.056149&cid=C049HHMV9SM

[@hungvu193](https://expensify.slack.com/team/U0467MRB03X)
@hungvu193  I'm unsure what the exact deliverable is here.  Can you update one of your screenshots above to include more details.
ie. the :mag:  glass should be moved up/down/left/right here so that it's alight with [something])

**Comment by mallenexpensify** [comment] 2023-10-19 18:26
@shawnborton can you confirm we want 20px spacing on the 🔍 , so that it's aligned to be above the 📌 ? Thx

**Comment by hayata-suenaga** [comment] 2023-10-23 01:52
asking [here](https://github.com/Expensify/App/issues/29057#issuecomment-1774309915)

**Comment by mallenexpensify** [comment] 2023-10-23 18:13
Putting on hold pending the below, which I just commented on. (we're likely fixing this regression as part of one PR)
- https://github.com/Expensify/App/issues/29057#issuecomment-1775750001

**Comment by mallenexpensify** [comment] 2023-11-03 23:31
Still held
- https://github.com/Expensify/App/issues/29057

**Comment by shawnborton** [comment] 2023-11-13 20:14
I think we can just close this out since all of the LHN changes were reverted.

**Closed** 2023-11-13 20:14 UTC
Labels: External, Weekly, Design, Bug
