### ISSUE TITLE
[Payment Due 09/11] [$250] Expense - Missing green unread line after marking first expense as unread in expense report

### ISSUE THREAD

**Issue by m-natarajan** [Expensify/App#45843] opened 2024-07-20 15:25 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 9.0.10-2
**Reproducible in staging?:** y
**Reproducible in production?:** n
**If this was caught during regression testing, add the test name, ID and link from TestRail:** n/a
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** Applause internal team
**Slack conversation:**

## Action Performed:
1. Go to staging.new.expensify.com
2. Go to DM.
3. Submit two expenses to the user.
4. Click on the expense preview to go to expense report.
5. Right click on the first expense preview.
6. Select Mark as unread.

## Expected Result:
The line separator below "Total" will change to a green line with "New" label on the right.

## Actual Result:
The line separator below "Total" disappears after marking the first expense as unread.
There is no green unread line.
## Workaround:
unknown
## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [x] Android: mWeb Chrome
- [x] iOS: Native
- [x] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

https://github.com/user-attachments/assets/fab12199-180b-42f6-ad99-bcc654454ad1

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~012c73811fb416526a</li>
        <li>Upwork Job ID: 1815405989806434770</li>
        <li>Last Price Increase: 2024-07-29</li>
<li>Automatic offers: </li>
<ul>
<li>dominictb | Contributor | 103407584</li>
</ul></li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @sakluger</details>

**Comment by Beamanator** [comment] 2024-07-21 02:52
@nyomanjyotisa thanks for your proposal! Can you also help us figure out what PR may have caused this bug?

**Comment by francoisl** [comment] 2024-07-22 17:44
Thanks for all the proposals so far. Can anyone identify what PR caused the regression though? It seems like all of suggested code changes aren't in code that changed recently.

**Comment by mountiny** [comment] 2024-07-23 07:21
Demoting this because:
- its one of last blockers
- its edge case where user needs to mark the first IOU action as unread
- the chat shows as unread in the LHN so the user would not miss the chat as unread

**Comment by mountiny** [comment] 2024-07-23 07:22
@dominictb @daledah @nyomanjyotisa With any deploy blocker, always include the PR that introduced the regression

**Comment by Beamanator** [comment] 2024-07-24 00:54
@allroundexperts mind reviewing this one? I'd also love to get to the bottom of how this happened, as this must have only happened recently 🤔

**Comment by allroundexperts** [comment] 2024-07-29 08:26
On it today.

**Comment by allroundexperts** [comment] 2024-07-29 17:47
Melv I'll be reviewing this today.

**Comment by allroundexperts** [comment] 2024-07-31 10:05
@dominictb Can you please post a video of your solution in action? I can't seem to make it work by applying your changes.

**Comment by allroundexperts** [comment] 2024-08-04 20:45
Thanks for the proposals everyone!

@dominictb's [proposal](https://github.com/Expensify/App/issues/45843#issuecomment-2243459212) looks better to me as it utilises an already used piece of code in another component.

🎀 👀 🎀 C+ reviewed

**Comment by Beamanator** [comment] 2024-09-25 19:37
Oof yep, this probably got merged & deployed when our automation was broken 🙃

**Comment by sakluger** [comment] 2024-09-25 20:09
Sorry about that!

Summarizing payment on this issue:

Contributor: @dominictb $250, paid via Upwork
Contributor+: @allroundexperts $250, please request on Newdot

**Comment by sakluger** [comment] 2024-09-26 19:37
Pasting the BZ checklist here for convenience.

BugZero Checklist: The PR fixing this issue has been merged! The following checklist ([instructions](https://stackoverflow.com/c/expensify/questions/14574)) will need to be completed before the issue can be closed:

 [@allroundexperts] The PR that introduced the bug has been identified. Link to the PR: 
 [@allroundexperts] The offending PR has been commented on, pointing out the bug it caused and why, so the author and reviewers can learn from the mistake. Link to comment: 
 [@allroundexperts] A discussion in #expensify-bugs has been started about whether any other steps should be taken (e.g. updating the PR review checklist) in order to catch this type of bug sooner. Link to discussion: 
 [@allroundexperts] Determine if we should create a regression test for this bug. 
 [@allroundexperts] If we decide to create a [regression test](https://github.com/Expensify/App/blob/main/contributingGuides/REGRESSION_TEST_BEST_PRACTICES.md) for the bug, please propose the regression test steps to ensure the same bug will not reach production again.

**Comment by allroundexperts** [comment] 2024-09-26 21:59
## Checklist
1. I wasn't able to pinpoint the exact PR that caused this issue. It seems to me that this is something that was like this when it was first implemented.
2. N/A
3. N/A
4. I think a regression test would be helpful.

## Regression test

1. Open the app and go to any direct message
2. Submit two expenses to the user
3. Click on the expense preview to go to expense report
4. Right click on the first expense preview
5. Select Mark as unread.

Verify that the line separator below "Total" will change to a green line with "New" label on the right.

Do we 👍 or 👎 ?

**Comment by sakluger** [comment] 2024-09-27 16:37
Looks good to me. Thanks!

**Closed by sakluger** 2024-09-27 16:37 UTC
Labels: External, Engineering, Daily, Awaiting Payment, Bug

**Comment by JmillsExpensify** [comment] 2024-10-14 21:57
$250 approved for @allroundexperts
