### ISSUE TITLE
Android -  LHN - Period is displayed in between the user names of group chat in unread messages

### ISSUE THREAD

**Issue by kavimuru** [Expensify/App#4074] opened 2021-07-15 14:21 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Lunch the app
2. Log in with any account
## Expected Result:
Comma is displayed in between the user names for both read and unread groups
## Actual Result:
Period is displayed in between the user names for the unread groups

## Workaround:
Unknown
## Platform:
Where is this issue occurring?

 Web
 iOS 
 Android ✔️
 Desktop App
 Mobile Web

**Version Number:**
1.0.78-0
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation
**Expensify/Expensify Issue URL:**
<img src="https://user-images.githubusercontent.com/43996225/125803835-fa66337b-d048-4cd7-a6a6-ab6f1cf9c674.jpg" width="40%">

[View all open jobs on Upwork](https://www.upwork.com/ab/jobs/search/?q=Expensify%20React%20Native&sort=recency&user_location_match=2)

**Comment by parasharrajat** [comment] 2021-07-15 15:05
@roryabraham I think this is a side-effect of replacing the Text with ExpensiText. I found that we have `height:18` set on these styles and if we remove it will be fixed. Also if you look closely, you will found that in focused mode the Chat title is not centered with respect to Avatar.

**Comment by roryabraham** [comment] 2021-07-16 15:57
Sorry I didn't get to this yesterday. I'll work on getting this resolved now.

**Comment by roryabraham** [comment] 2021-07-16 16:07
Confirmed that this doesn't seem to be happening on other platforms.

**Comment by roryabraham** [comment] 2021-07-16 22:25
Sorry, I had a bunch of issues with my Android emulators + not being able to update the hosts file to access the VM API. So I wasn't able to reproduce this. Lame, I know, but I have to give this back to you @yuwenmemon because I'll be OOO next week. I'm guessing it's just a simple issue with the default lineHeight [here](https://github.com/Expensify/Expensify.cash/blob/993be4650fe80ac8f8955ff2c3d1b861aed9bf0a/src/components/Text.js#L63)

**Comment by isagoico** [comment] 2021-07-19 09:49
Issue reproducible during KI retests

**Comment by yuwenmemon** [comment] 2021-07-19 18:50
Hmmm... I'm actually not seeing this on the latest version of Master:
![Screen Shot 2021-07-19 at 11 48 35 AM](https://user-images.githubusercontent.com/4741899/126211626-0678f961-53c3-453d-9db3-abe4f98d7459.png)

What kind of Android device was it specifically?

**Comment by parasharrajat** [comment] 2021-07-19 21:40
So @yuwenmemon This issue started showing up when Rory moved the RN `text` to our `Text` component. Previously Line-height and height were set to 18px which had no issues. https://github.com/Expensify/Expensify.cash/blob/47494884adb24d23226edb0eb7d22d8240ecf979/src/styles/styles.js#L801-L806.

Now line height will be taken from Text component default which is 20 so issues are coming. We are in discussion on removing the line height from the Text component as it has caused many issues. But to fix this.
either we set the line height back to 18 or remove the height.

**Comment by isagoico** [comment] 2021-07-23 20:39
Retested this after https://github.com/Expensify/App/pull/4143 was CPd and it was a pass 🎉 Closing the issue

**Closed by isagoico** 2021-07-23 20:39 UTC
Labels: DeployBlockerCash, Engineering, Hourly, Reviewing
