### ISSUE TITLE
[$250] Tax - Refreshing the page while tax code RHP is open disrupts navigation

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#46878] opened 2024-08-06 12:34 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 9.0.17-0
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**If this was caught during regression testing, add the test name, ID and link from TestRail:** N/A
**Issue reported by:** Applause - Internal Team

## Action Performed:
1. Navigate to staging.new.expensify.com
2. Create a workspace
3. Enable taxes on More features page
4. Open a tax rate
5. Click on Tax code
6. Refresh the page
7. Click on back to close the RHP
8. While the workspace editor is open click on the back button at the top left

## Expected Result:
After a refresh the page stays on the same page

## Actual Result:
After the refresh the page navigates to workspace chat page and closing the RHP navigates the app to the workspace editor page and upon clicking on the back button to go to workspace list page the app navigates back to workspace chat page

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details> 

https://github.com/user-attachments/assets/7d9f0b23-cd63-43e6-a24f-61558df0d393

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01e25fc083ddb12e26</li>
        <li>Upwork Job ID: 1823686714567800651</li>
        <li>Last Price Increase: 2024-08-21</li>
<li>Automatic offers: </li>
<ul>
<li>rayane-djouah | Reviewer | 103676928</li>
</ul></li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @rayane-djouah</details>

**Comment by lanitochka17** [comment] 2024-08-06 12:35
We think that this bug might be related to #wave-collect - Release 1

**Comment by lanitochka17** [comment] 2024-08-06 12:35
@JmillsExpensify  FYI I haven't added the External label as I wasn't 100% sure about this issue. Please take a look and add the label if you agree it's a bug and can be handled by external contributors

**Comment by JmillsExpensify** [comment] 2024-08-14 11:43
Opening up for proposal review and filing in wave-control polish.

**Comment by bernhardoj** [comment] 2024-08-16 01:15
I actually find another problem. I have updated my proposal to explain and fix that and also include the suggestion above.

**Comment by bernhardoj** [comment] 2024-08-26 11:10
It's not repro anymore since the main issue that I mentioned is already solved with the same solution.

**Comment by roryabraham** [comment] 2024-08-26 23:43
requested retest: https://expensify.slack.com/archives/C9YU7BX5M/p1724715774304039

If not reproducible, let's close this out

**Comment by bernhardoj** [comment] 2024-08-27 04:16
> After the refresh the page navigates to workspace chat page

Oh btw, we can still repro this by removing the `backTo` from the URL and it happens to every upgrade page. Do we want to fix it?

**Comment by m-natarajan** [comment] 2024-08-27 12:18
Issue not reproducible 

https://github.com/user-attachments/assets/61151f2f-679d-4e0a-81b4-e7dff4052a57

**Closed** 2024-08-27 16:25 UTC
Labels: External, Daily, Bug
