### ISSUE TITLE
[$1000]  "Members" item doesn't appear in thread details without refreshing the page

### ISSUE THREAD

**Issue by kavimuru** [Expensify/App#21600] opened 2023-06-26 18:32 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Go to a chat
2. Send a message
3. Hover over it and create a thread
4. Click on chat header
5. Check that "Members" item is not present
6. Reload the page and check again
## Expected Result: 
You should see the "Members" item without refreshing the page
## Actual Result:
 "Members" item doesn't appear without refreshing the page. In production it appears then disappears
## Workaround:
Can the user still use Expensify without this being fixed? Have you informed them of the workaround?

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android / native
- [x] Android / Chrome
- [x] iOS / native
- [x] iOS / Safari
- [x] MacOS / Chrome / Safari
- [x] MacOS / Desktop
 
**Version Number:** 1.3.32-5
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/43996225/51ec69f8-1520-4b67-aca2-bd0241e62f6b

https://github.com/Expensify/App/assets/43996225/706ddb8c-2632-4128-bd1f-4b149db12683

**Expensify/Expensify Issue URL:**
**Issue reported by:** @Puneet-here 
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1687339647252079

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01426c99239721a0e1</li>
        <li>Upwork Job ID: 1673433552396025856</li>
        <li>Last Price Increase: 2023-06-26</li>
    </ul>
</details>

**Comment by trjExpensify** [comment] 2023-06-26 20:50
Ah yeah, interesting. I wonder if this has something to do with the secure logins refactor project or public rooms as we check to see if you have permission to view the members list. What's interesting though is that it's fine in the #announce room itself (shows immediately), just not the details of the threadReport. 

Moving it on!

**Comment by bernhardoj** [comment] 2023-06-27 08:27
This is a BE issue. When we create the thread, it will do an OpenReport request to the BE and BE will return empty `participantAccountIDs`

It works fine if we create the thread while offline.

**Comment by trjExpensify** [comment] 2023-06-27 09:25
Cool, thanks! Moving internal.

**Comment by s77rt** [comment] 2023-06-27 10:54
@srikarparsi The BE seems to return 2 onyx objects for everything (include the `report`) which is strange. The first report object contains the participants but the second contains an empty array which overwrites the first.

![Screenshot from 2023-06-27 11-45-19](https://github.com/Expensify/App/assets/16493223/728da11f-be15-419c-8f0c-54508d010d8a)
![Screenshot from 2023-06-27 11-47-15](https://github.com/Expensify/App/assets/16493223/d63df62c-bfb4-4cae-b86c-06c3f40bddd8)
 ![Screenshot from 2023-06-27 11-47-43](https://github.com/Expensify/App/assets/16493223/c09a2ead-ffc8-4875-901a-922609cd8992)

**Comment by srikarparsi** [comment] 2023-06-29 06:44
Thanks @s77rt! Seeing the same duplicate data in the response. Will take a look at this on Friday as I'll mostly be OOO tomorrow.

**Comment by trjExpensify** [comment] 2023-07-03 10:50
@srikarparsi did you take a look on Friday?

**Comment by srikarparsi** [comment] 2023-07-05 16:34
Hey @trjExpensify! I didn't get a chance Friday and was mostly OOO yesterday and day before for the 4th but will prioritize this today :)

**Comment by srikarparsi** [comment] 2023-07-07 05:02
Update: Working on it but running into an issue where the response of the first OpenReport for a new thread is empty. Also unable to post a message to the newly created thread. Not sure if a new PR broke threads on dev or something is wrong locally but will look into it more tomorrow.

<img width="1509" alt="Screenshot 2023-07-07 at 1 02 13 AM" src="https://github.com/Expensify/App/assets/48188732/f1f9f4fa-d974-4fc3-9cbf-dbe8201b6609">

**Comment by trjExpensify** [comment] 2023-07-10 10:09
How are you getting on @srikarparsi?

**Comment by srikarparsi** [comment] 2023-07-11 01:28
Hey @trjExpensify! The issue seems to be resolved in dev. I wasn't able to find the related PR yet but I am working on that as it does not seem to be resolved in staging yet.

https://github.com/Expensify/App/assets/48188732/c4bc0c32-305b-4f53-9aa6-d53f4b1a5587

**Comment by srikarparsi** [comment] 2023-07-11 01:49
Hey @grgia! By any chance, do you know which PR this issue was resolved in? I checked through these [issues](https://github.com/Expensify/App/issues/19877) but couldn't find what could be related. I looked through the code as well but couldn't find any recent changes that would lead to this fix. Just asking to see when the fix would reach staging and to figure out myself how to fix issues like these.

**Comment by trjExpensify** [comment] 2023-07-12 21:47
Bump on the Q @grgia! :)

**Comment by grgia** [comment] 2023-07-13 12:25
@srikarparsi here's how we tracked the project - https://github.com/orgs/Expensify/projects/32
I'm not sure the exact issue, maybe @chiragsalian remembers if it's related to the `participantAccountIDs` report key. It would probably be in Web?

**Comment by srikarparsi** [comment] 2023-07-17 07:58
After looking through them and not finding anything, I tested again and now it's back to the same error. I'm not sure how [this](https://github.com/Expensify/App/issues/21600#issuecomment-1629956336) happened because I made sure to check I was on main so maybe the fix got reverted? I'll investigate more into the code that could be causing this tomorrow.

https://github.com/Expensify/App/assets/48188732/35b0f83f-e2e6-479f-a3fd-760f5c31c6ec

**Comment by srikarparsi** [comment] 2023-07-18 07:37
Found the root cause: Removing these [three lines](https://github.com/Expensify/Web-Expensify/blob/main/lib/ReportAPI.php#L4824-L4826) fixes the issue. The ReportUtils::pushNewChat method is duplicating the openReport response which causes this error. The lines were added in this [PR](https://github.com/Expensify/Web-Expensify/pull/37797) so I'll look into why it was added and find a workaround tomorrow but I'll be partly OOO so should get a PR out by Wednesday.

**Comment by trjExpensify** [comment] 2023-07-18 22:53
Niceee! Appreciate being kept in the loop :)

**Comment by srikarparsi** [comment] 2023-07-20 04:29
Tried a fix but it affected the outcome of this [PR](https://github.com/Expensify/Web-Expensify/pull/37797). Will try coming up with a different approach tomorrow and should have a draft pr by the afternoon.

**Comment by srikarparsi** [comment] 2023-07-21 02:33
Still working on it and posted about it in eng chat [here](https://expensify.slack.com/archives/C03TQ48KC/p1689905657861799)

1. https://github.com/Expensify/Web-Expensify/blob/main/lib/ReportAPI.php#L4882
2. https://github.com/Expensify/Web-Expensify/blob/main/lib/ReportUtils.php#L2919
3. https://github.com/Expensify/Web-Expensify/blob/main/lib/Onyx.php#L151
4. https://github.com/Expensify/Web-Expensify/blob/main/lib/Onyx.php#L261

**Comment by techievivek** [comment] 2023-07-21 10:28
I got assigned a [issue](https://github.com/Expensify/App/issues/21607) with a similar RCA. I started a [discussion](https://expensify.slack.com/archives/C03TQ48KC/p1689924201903419) in the #eng-chat room so I should be able to help here.

**Comment by trjExpensify** [comment] 2023-07-24 10:55
Nice! How's that going @techievivek?

**Comment by srikarparsi** [comment] 2023-07-25 03:58
@iwiznia pointed out that it may be resolved in a [different PR](https://expensify.slack.com/archives/C03TQ48KC/p1690212973793179?thread_ts=1689905657.861799&cid=C03TQ48KC). I will take a look into it tomorrow. It's a little complicated because the eventLog is core to other push features.

**Comment by techievivek** [comment] 2023-07-25 05:51
I think we can hold working on this issue for now as this _may_ get resolved with our reliable updates project(PR https://github.com/Expensify/Web-Expensify/pull/38264/commits/3affa68e8947842714594b828a0c50560d9cc748). It seems that there could be some revamp required in the pusher data sending part of the code, so it's better to wait for a while. Otherwise, this could potentially result in having to do double the amount of work.

**Comment by trjExpensify** [comment] 2023-07-25 13:34
That sounds reasonable to me. I've linked the PR in the header and I'll drop this to `weekly` to remove the hold, retest and go from there. 👍

**Comment by s77rt** [comment] 2023-08-13 01:53
Not overdue. @techievivek Any updates on that PR? (whether it's deployed to staging/production)

**Comment by trjExpensify** [comment] 2023-08-14 10:30
It's on production. :)

**Comment by techievivek** [comment] 2023-08-14 12:18
Taking a look.

**Comment by techievivek** [comment] 2023-08-14 12:49
I was able to reproduce this on staging.

**Comment by techievivek** [comment] 2023-08-14 13:00
Ok, so I dug up a bit and figured out that the reliable updates PR that could potentially solve the bug is behind a beta and unlike other betas which are managed by the beta manager this is actually configured through [defining a constant](https://github.com/Expensify/Web-Expensify/pull/38264#issue-1816062486) at the config label(have a look at this [PR](https://github.com/Expensify/Web-Expensify/pull/38264#issue-1816062486) to learn more about testing of reliable updates PR), I am going to test this on the DEV to see if turning the beta manually fixes the issue or not.

**Comment by techievivek** [comment] 2023-08-15 06:07
Just tested this, and it is broken even after turning on the reliable updates changes. I am ooo today, but I should be able to look into it tomorrow.

**Comment by trjExpensify** [comment] 2023-08-15 10:25
Oh hm, interesting. I wonder why I couldn't reproduce. Thanks for looking into it, @techievivek!

**Comment by trjExpensify** [comment] 2023-08-21 11:19
@techievivek did you get any further [here](https://github.com/Expensify/App/issues/21600#issuecomment-1678468844)?

**Comment by techievivek** [comment] 2023-08-21 12:49
Sorry, I couldn't get back to this last week. I will take a look at it today/tomorrow. But it looks like reliable updates PR didn't help us here.

> Oh hm, interesting. I wonder why I couldn't reproduce. Thanks for looking into it, @techievivek!

Interesting, I was able to reproduce this consistently. 😕

**Comment by techievivek** [comment] 2023-08-29 08:08
Working on this today.

**Comment by techievivek** [comment] 2023-08-29 13:19
This seems really tricky particularly considering that it's a fundamental aspect of how we provide responses to users. I have started a discussion in the #eng-channnel to figure out a solution that would work https://expensify.slack.com/archives/C03TQ48KC/p1693314354987449

**Comment by trjExpensify** [comment] 2023-08-30 14:17
Thanks for the update, @techievivek!

**Comment by trjExpensify** [comment] 2023-09-04 09:33
👋 @techievivek did you take [that last action](https://expensify.slack.com/archives/C03TQ48KC/p1693323588662109?thread_ts=1693314354.987449&cid=C03TQ48KC) to test?

**Comment by techievivek** [comment] 2023-09-11 10:44
Sorry, I was ooo last week. Taking a look at it today as we have a potential solution now.

**Comment by trjExpensify** [comment] 2023-09-25 11:20
@techievivek mind providing a quick update, please?

**Comment by techievivek** [comment] 2023-09-26 08:23
Sorry, I have put the PR on HOLD and caught up with @neil-marcellini yesterday to discuss the solution in detail as he has some context around the changes. The code in `openReport` is extremely tricky especially in terms of participants because we handle them differently. I am working on updating the PR after the discussions but integration tests are failing. I will give it another look by the EOW as I have to focus on other stuff as well.

**Comment by techievivek** [comment] 2023-09-26 09:38
Ok, figured out the reason tests were failing and have fixed it, it's ready for a review https://github.com/Expensify/Web-Expensify/pull/38851#issuecomment-1735183083

**Comment by srikarparsi** [comment] 2023-09-29 05:09
Unassigning myself from this since @techievivek is working on it

**Comment by techievivek** [comment] 2023-10-09 05:44
Yes, QA is over for the staging changes so this should be on PROD today 🤞

**Comment by trjExpensify** [comment] 2023-10-09 17:51
Cool, it hit prod an hour ago. Confirming that's the only PR for this issue is it? If so, we can just go forward and pay out the bug report now.

**Comment by trjExpensify** [comment] 2023-10-17 15:36
Bump, @techievivek. Can you confirm we're good to pay @Puneet-here $250 for the bug report?

**Comment by techievivek** [comment] 2023-10-17 15:42
Yes, this was deployed to PROD: https://github.com/Expensify/Web-Expensify/pull/38851#issuecomment-1753346389 so we can pay the reporting bonus here, thanks.

**Comment by trjExpensify** [comment] 2023-10-17 21:42
Cool, sent an offer @Puneet-here!

**Comment by Puneet-here** [comment] 2023-10-20 08:05
Accepted the offer.

**Comment by trjExpensify** [comment] 2023-10-20 18:18
Paid!

**Closed by trjExpensify** 2023-10-20 18:18 UTC
Labels: Reviewing, Engineering, Daily, Internal, Bug
