### ISSUE TITLE
[$500] Setting channel notification settings does not affect threads

### ISSUE THREAD

**Issue by m-natarajan** [Expensify/App#33373] opened 2023-12-20 18:48 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.14-2
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** @rafecolton 
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1703021942787129

## Action Performed:
1. Join a channel
2. Change notification settings for that channel to mute
3. Open a thread from that channel
4. Receive immediate notifications

## Expected Result: 
Notifications for new thread should match the channel. So if the channel is muted, new threads joined are also muted. It should still be possible to change them, but by default, they should match the channel.

## Actual Result: 
Muted the channel, joined a thread, heard dinging and had to go mute the individual thread.

## Workaround:
unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [ ] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

![Screen Shot 2023-12-20 at 1 46 15 PM](https://github.com/Expensify/App/assets/38435837/cb07d292-32cf-4251-9e19-2f02f0371406)

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01aadd58e547ca6f1b</li>
        <li>Upwork Job ID: 1737545535201861632</li>
        <li>Last Price Increase: 2023-12-27</li>
    </ul>
</details>

**Comment by FitseTLT** [comment] 2023-12-20 18:57
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
Setting channel notification settings does not affect threads

### What is the root cause of that problem?
When we set notification preference for a channel we are only setting it for that specific report not all the threads under it
### What changes do you think we should make in order to solve the problem?

We should also set notification for all threads in the channel in `updateNotificationPreference` 
### What alternative solutions did you explore? (Optional)

**Comment by puneetlath** [comment] 2023-12-28 20:34
Asked about expected behavior here: https://expensify.slack.com/archives/C066HJM2CAZ/p1703795630714529

**Comment by puneetlath** [comment] 2023-12-28 20:49
Ok closing this issue as it looks like this is the expected behavior from the slack discussion. Feel free to comment/reopen if you disagree.

**Closed by puneetlath** 2023-12-28 20:49 UTC
Labels: External, Daily, Help Wanted, Bug
