### ISSUE TITLE
[$500] [MEDIUM] Money Request - Offline Paid request in User A isn't deleted after returning online

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#34851] opened 2024-01-20 15:21 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.28-0
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** Applause - Internal Team
**Slack conversation:**

## Action Performed:
1. Using secondary device(User B), send request to main device(User A)
2. Go offline with User A and pay request elsewhere
3. Delete money request on secondary device(B)
4. On main device(A), go back online and observe request

## Expected Result:
Sent money request is deleted on main device after returning online.

## Actual Result:
Money request is not deleted and loses its paid status after returning online. Paying request does nothing.

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [x] Android: mWeb Chrome
- [x] iOS: Native
- [x] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

https://github.com/Expensify/App/assets/93399543/721cb864-d4ea-4f4c-b970-153b791c1c6c

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~018c93e10b09de847a</li>
        <li>Upwork Job ID: 1748727434202918912</li>
        <li>Last Price Increase: 2024-02-10</li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @greg-schroeder</details>

**Comment by kbecciv** [comment] 2024-01-20 15:23
We think that this bug might be related to #wave6-collect-submitters
CC @greg-schroede

**Comment by rojiphil** [comment] 2024-01-20 16:15
@greg-schroeder @slafortune @allroundexperts 
I am not sure if we should allow payment(i.e. settlement) when offline. 
Or is this intentional?

**Comment by slafortune** [comment] 2024-01-22 21:03
Adding you to this GH @greg-schroeder so you can clarify the expected outcome.

**Comment by greg-schroeder** [comment] 2024-01-23 01:37
Hi! I'll take a look at this shortly

**Comment by greg-schroeder** [comment] 2024-01-23 02:00
>I am not sure if we should allow payment(i.e. settlement) when offline.
>Or is this intentional?

Yes, it's intentional afaik, but it should definitely be clearer. I chatted with @mountiny and he said that the paid action should still show up and the user should be able to click X to clear it up, alongside an error that explains what happened.

**Comment by allroundexperts** [comment] 2024-01-25 18:39
Still looking for proposals.

**Comment by slafortune** [comment] 2024-01-25 20:40
We'll give it another day before reaching out else where

**Comment by rojiphil** [comment] 2024-01-26 11:51
## Proposal

### Please re-state the problem that we are trying to solve in this issue.

Money Request - Offline Paid request in User A isn't deleted after returning online

### What is the root cause of that problem?

[Here](https://github.com/Expensify/App/blob/caf91aefc70e8bb82813a421097fd37b412bb137/src/libs/actions/IOU.js#L3186C1-L3188C19), we are not showing errors for `payMoneyRequest`. Further, we are not handling the error such that the ReportPreview is cleared. This is the root cause.

### What changes do you think we should make in order to solve the problem?

First, we should capture the error [here](https://github.com/Expensify/App/blob/caf91aefc70e8bb82813a421097fd37b412bb137/src/libs/actions/IOU.js#L3186C1-L3188C19) like this:

                    errors: ErrorUtils.getMicroSecondOnyxError('iou.error.other'),

Further, we should handle the error [here](https://github.com/Expensify/App/blob/caf91aefc70e8bb82813a421097fd37b412bb137/src/libs/actions/ReportActions.ts#L9C1-L41C2) when the user clear the error. 
The simplest way to do this would be to set the ReportPreview action to null and refetch the chat report contents again via `ReconnectToReport` when there are any `add` pending actions of `iou` type with `errors` in the child IOU Report. Otherwise, I think we will need BE support as well to remove the Report Preview. 

### What alternative solutions did you explore? (Optional)

**Comment by rojiphil** [comment] 2024-01-26 11:53
Sorry for the delay in response here. This completely went out of my mind.

@allroundexperts 
Do you think the above proposal is fine to solve the problem from FE or would it be better to get some BE support here?

**Comment by greg-schroeder** [comment] 2024-01-26 18:57
Thanks for the proposal! Let's see what Sibtain thinks

**Comment by greg-schroeder** [comment] 2024-01-26 18:57
Stop being annoying Melvin, this isn't overdue

**Comment by greg-schroeder** [comment] 2024-01-26 18:58
Not overdue

**Comment by greg-schroeder** [comment] 2024-01-26 20:19
Go away melvin

**Comment by slafortune** [comment] 2024-01-26 20:58
Does Melvin need me to tell them what to do??

**Comment by slafortune** [comment] 2024-01-29 17:11
@allroundexperts will you have time to review the proposal shared in the next day or so?

**Comment by allroundexperts** [comment] 2024-01-29 17:21
Yep, on it today.

**Comment by allroundexperts** [comment] 2024-01-29 20:16
@rojiphil I think it should be fine to just clear the report action but why do we need to refetch the report? I don't understand that part. Also, it would be great if you can share a short demo of your solution.

**Comment by greg-schroeder** [comment] 2024-01-29 22:10
@rojiphil is next up to respond to the above! Just commenting to get Melvin off our backs

**Comment by rojiphil** [comment] 2024-02-02 15:53
> I think it should be fine to just clear the report action but why do we need to refetch the report? I don't understand that part. Also, it would be great if you can share a short demo of your solution

@allroundexperts 
I am unsure if `payMoneyRequest` can fail for any other reason. That is why I was suggesting fetching the report so that the report action would come back if at all failure is due to a reason other than the remote User deleting the Money Request. But now I am wondering if this looks like a workaround. I think we may have to look at this differently here. 

If we look at the `PayMoneyRequest` response, BE throws `666` as `jsonCode` and `code`. 
Can we confirm in BE if this means that the money request is deleted? 

If so, we can use this information in FE to clear the report action. 
Alternatively, BE can also set the report action to `null` on the failure of `payMoneyRequest`. But, this may not be good UX as the user would notice that the money request has disappeared suddenly.

What do you think about this?

![Screenshot 2024-01-27 at 5 18 49 PM](https://github.com/Expensify/App/assets/3004659/4f5cf380-2541-469b-93fd-f2e0c88832b5)

**Comment by greg-schroeder** [comment] 2024-02-06 01:01
I'm unassigning myself as we have two people from BZ assigned and Stevie was the original assignee. @allroundexperts do you mind responding to the question posed above when you're able? Thanks!

**Comment by allroundexperts** [comment] 2024-02-07 08:54
> > I think it should be fine to just clear the report action but why do we need to refetch the report? I don't understand that part. Also, it would be great if you can share a short demo of your solution
> 
> @allroundexperts I am unsure if `payMoneyRequest` can fail for any other reason. That is why I was suggesting fetching the report so that the report action would come back if at all failure is due to a reason other than the remote User deleting the Money Request. But now I am wondering if this looks like a workaround. I think we may have to look at this differently here.
> 
> If we look at the `PayMoneyRequest` response, BE throws `666` as `jsonCode` and `code`. Can we confirm in BE if this means that the money request is deleted?
> 
> If so, we can use this information in FE to clear the report action. Alternatively, BE can also set the report action to `null` on the failure of `payMoneyRequest`. But, this may not be good UX as the user would notice that the money request has disappeared suddenly.
> 
> What do you think about this?
> 
> ![Screenshot 2024-01-27 at 5 18 49 PM](https://private-user-images.githubusercontent.com/3004659/301897293-4f5cf380-2541-469b-93fd-f2e0c88832b5.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDcyODY3OTEsIm5iZiI6MTcwNzI4NjQ5MSwicGF0aCI6Ii8zMDA0NjU5LzMwMTg5NzI5My00ZjVjZjM4MC0yNTQxLTQ2OWItOTNmZC1mMmUwYzg4ODMyYjUucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDIwNyUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDAyMDdUMDYxNDUxWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9ZmM2ZmVlZDY5YmZmY2QxNjg1YTkzYTBkOTE2MDVkNzRjNmI2Nzg3NjVhYTQ3YTY4ZWE3MTkzNjA1MWEzNjBiNyZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.RCM6VqFdAkc8cx1h0Kny5lBIutVFAk8nRVgaOhhqbok)

Yes, if the code corresponds to the request being deleted, then the solution would be simplified. I agree with you @rojiphil. @slafortune Can you please loop in an internal engineer to confirm the meaning of the error code 666?

**Comment by slafortune** [comment] 2024-02-14 13:44
Yes - I'll reach out today to get insight on that error.

**Comment by slafortune** [comment] 2024-02-16 18:29
Checking here - https://expensify.slack.com/archives/C02MW39LT9N/p1708108175593739

**Comment by slafortune** [comment] 2024-02-19 23:54
Checking in the BugZero and Wave 6 rooms

**Comment by chiragsalian** [comment] 2024-02-20 01:09
@rojiphil / @allroundexperts 

> Can we confirm in BE if this means that the money request is deleted?

In the database i doubt we would delete anything. Here is how i understand the request money flow works.
1. UserA requests money to UserB. We create a transaction entry of the amount and create an expense report tied to the transaction.
2. The state/status of report tells us whether UserB paid or not. Its status will be 1 to start with to indicate itself as "OPEN".
3. Once UserB successfully pays with expensify or elsewhere. The expense report status will change to say 4 for "APPROVED".

Nothing gets deleted here as far as i understand.

Here are some [logs](https://www.expensify.com/_devportal/tools/logSearch/#query=request_id:(%22857b96fc0a2426b1-BLR%22)+AND+timestamp:[2024-02-19T02:58:09.468Z+TO+2024-02-19T04:58:09.468Z]&index=logs_expensify-026868) from you @rojiphil,
```
Processing 'PayMoneyRequest' for 'expensify.com' from '106.222.203.69' ~~ initialReferer: '<REDACTED>' browserGUID: '64f575bbad17a' command: 'PayMoneyRequest' iouReportID: '8655004979274503' chatReportID: '503660483645734' reportActionID: '3680393124994871571' paymentMethodType: 'ACH' appversion: '1.4.42-1' pusherSocketID: '661166.734699' authToken: '<REDACTED>' referer: 'ecash' platform: 'web' api_setCookie: 'false' email: 'roji+test292@owesee.com' isFromDevEnv: 'true' partnerName: 'expensify.com' HTTP_CF_BOT_SCORE: '2' HTTP_CF_JA3_HASH: 'a685258a6b9efe7d51633cf248ba2c83'
Throwing exception with message: '410 Credit and debit account can not be the same' from auth/command/PayMoneyRequest.cpp:157
Throw ExpException - d1cbd3c64a46b9acc503d06b59a1e863 ~~ message: '410 Credit and debit account can not be the same' exceptionMessage: 'Auth PayMoneyRequest returned an error' exceptionFile: '/git/releases/expensify.com/da41e72/lib/Auth.php' exceptionLine: '125' exceptionCode: '410'
ReportAPI - Error thrown in payMoneyRequest ExpException - d1cbd3c64a46b9acc503d06b59a1e863 ~~ moneyRequestReportID: '8655004979274503' reportActionID: '3680393124994871571' message: '410 Credit and debit account can not be the same' exceptionMessage: 'Auth PayMoneyRequest returned an error' exceptionFile: '/git/releases/expensify.com/da41e72/lib/Auth.php' exceptionLine: '125' exceptionCode: '410'
API threw ExpError Expensify\Libs\Error\ExpError - c4e9feed-5f49-48cf-90d0-1f1c04203e77 ~~ onyxData: '[0: '[onyxMethod: 'merge' key: 'reportActions_8655004979274503' value: '[3680393124994871571: '[errors: '[1708315089466342: 'The deposit and withdrawal accounts are the same.']']']']']' exceptionJsonCode: '666' exceptionUserMessage: 'The deposit and withdrawal accounts are the same.' exceptionMessage: 'The deposit and withdrawal accounts are the same.' exceptionFile: '/git/releases/expensify.com/da41e72/lib/ReportAPI.php' exceptionLine: '5109' exceptionCode: '666'
```

If i check the database for reportID 8655004979274503 i see,
```
chirag@db2.rno:~$ sudo readdb.sh "select * from reports where reportID = 8655004979274503;"
created              submitted            approved  reportID          accountID  managerID  reportName                 state  total   currency  cachedData                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                 status
-------------------  -------------------  --------  ----------------  ---------  ---------  -------------------------  -----  ------  --------  -------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------  ------
2024-02-16 15:33:46  2024-02-16 15:33:46            8655004979274503  16281435   16281435   Expense Report 2024-02-16  1      -60296  USD       {"submitted":"","submittedTo":"","approved":"","unapproved":"","reimbursed":"","shared":"","type":"expense","retracted":"","expensify_policyID":"2EF1D338AB337AF9","policyLastModified":1708159188255549,"isSmartReport":false,"cacheComputedBy":16281435,"inbox":{"violations":{"oldestExpenseDate":"2024-02-16","newestExpenseDate":"2024-02-17 07:44:42","maxAge":null,"potentialRTERViolations":[],"cacheableViolationTypes":["notice"],"ignoredWarnings":[],"hasTransactionsWithDifferentCurrency":true,"violationsReportAmount":-60296,"totalViolations":6},"policyType":"team","firstSubmittedDate":"2024-02-16 15:33:46","wasComputedInReportCache":true},"reimburserEmail":"roji+test292@owesee.com","queuedForAutoExport":{"queued":false,"connections":[],"exportFailed":false,"failedConnections":[]},"hasBeenExportedToIntegration":false,"wasReimbursedViaACH":false,"statementCardID":null,"statementBank":null,"statementPeriodEndDay":null,"isWaitingOnBankAccount":false,"isABAReimbursed":false,"expectedReimbursementDate":null,"canMarkReimbursementReceived":true,"hasReimbursableTotal":true,"hasTransactions":true,"hasBillableTransactions":false,"reportOwners":[],"managerOnVacation":"","isSmartReportOnFile":false,"invoiceID":0,"billID":0}  1
```

its status is 1 so its not completed which seems good to me. Let me know if you guys have any other questions.
Meanwhile I'll tag @luacmartins to verify what i mentioned since i see he wrote parts related to that error message.

**Comment by chiragsalian** [comment] 2024-02-20 01:11
> Can you please loop in an internal engineer to confirm the meaning of the error code 666?

It's just a generic error code that we sometimes use. I'm unsure in this flow why we're not posting error code 410 but i would need to dig in a lot more to find that out. For 666 cases we would need to check the logs to know the exact reason of failure.

**Comment by rojiphil** [comment] 2024-02-20 09:41
@chiragsalian Thanks for your comments and also for sharing the details.

The issue here happens when User A initiates a `PayMoneyRequest` on an IOU report but the IOU report was already deleted by User B by deleting the last money request. In this case, the FE would want to know that the IOU report does not exist. I don’t know what would be the best way to handle it in BE but I can think of the following two options:
1) BE sends the appropriate error code/message within the Report Preview action in the chat report.
2) Currently, BE sends error code `666` as the response to the failure of the `PayMoneyRequest` request. Instead, if an appropriate error code is sent, the FE can pass the response error to the Report Preview action. However, this would mean that we need to pass this error information somehow into Onyx for the Report Preview action [here](https://github.com/Expensify/App/blob/0f372c2517b8ebd93e4dbbb53f542ab444c16adb/src/libs/Network/SequentialQueue.ts#L81C1-L95C20). And I am not quite sure if it would be a good idea to modify the implementation here as it is network specific code. So, I think it may be better to do (1).

Anyway, once (1) or (2) is undertaken, we would be able to display the appropriate error message upon  `PayMoneyRequest` request failure and remove the Report Preview action when the user clears the report action error. 
Does this make sense?

cc @allroundexperts

**Comment by luacmartins** [comment] 2024-02-20 18:55
Let me know if there's anything I can help with. From the comments above, it seems like the error is working as intended since both the accountID and managerID are the same and we don't allow that kind of payment.

**Comment by chiragsalian** [comment] 2024-02-20 20:27
@rojiphil, ah thanks for the usecase. Yeah in that scenario the moment userB deletes the money request i believe the report is deleted from the database. If userA still sees IOU report then i think its a bug wrt push notification and an internal engineer  should ensure userA gets the proper push notification.

Additionally if we worried of a race condition i.e., userA started the payment request but userB just deleted the IOU report. Then yes, i believe we can update the backend to return a better error code/message.

**Comment by rojiphil** [comment] 2024-02-21 00:59
@chiragsalian  I think this is a kinda race condition. But then we can reproduce this consistently in offline scenarios as mentioned in the OP. So, yes, I too think that BE needs to return a better error code/message. 
As mentioned [here](https://github.com/Expensify/App/issues/34851#issuecomment-1953826027), I can think of (1) and (2).  
What do you think is the way ahead?

**Comment by slafortune** [comment] 2024-02-23 16:50
@chiragsalian @luacmartins I kind of think that looking into the logs for this issue for this specific case wouldn't happen very often.  Do you think we should update the error code shown to the user still seeing the payment that was deleted - seems they should then just be able to x out of that and no issue involved as mentioned [here](https://github.com/Expensify/App/issues/34851#issuecomment-1905156504).

**Comment by chiragsalian** [comment] 2024-02-26 19:22
> As mentioned https://github.com/Expensify/App/issues/34851#issuecomment-1953826027, I can think of (1) and (2).
What do you think is the way ahead?

Cool, I'll leave it to the internal engineer working on the issue to decide whichever is best. Without looking at the code i think option 2 is better so that a different error code is sent and then the UI can update accordingly to allow user to remove the request since it no longer exists, or remove the request automatically.
I however don't think this is a daily, maybe a weekly. I'm currently busy on other tasks so i wont be picking this up right now. Maybe someone else can help here.

> Do you think we should update the error code shown to the user still seeing the payment that was deleted - seems they should then just be able to x out of that and no issue involved as mentioned https://github.com/Expensify/App/issues/34851#issuecomment-1905156504.

Yup i think this should work just fine. Maybe a question for product but maybe we can do this better by returning a unique error code for this case so that front end can remove the request and we add a whisper informing the request was deleted. Feels odd to me when the user sees an error for something they did not do wrong and that the user needs to dismiss it to clear their UI. I like it automatically clearing the UI with a nice whisper message informing them the request was removed and don't need to take any action from their end.

**Comment by slafortune** [comment] 2024-02-28 14:40
@allroundexperts @rojiphil does this answer all your questions?

**Comment by allroundexperts** [comment] 2024-02-29 10:29
Yes, we will need an internal engineer to change the error code first before creating a FE PR.

**Comment by slafortune** [comment] 2024-02-29 21:24
I'll add the first pick label - and we can refer to @chiragsalian comment [here](https://github.com/Expensify/App/issues/34851#issuecomment-1965051466)
As commented [here](https://github.com/Expensify/App/issues/34851#issuecomment-1953826027) we should update the code currently sent (666) when a initiates a `PayMoneyRequest` on an IOU report but the IOU report is deleted.

**Comment by chiragsalian** [comment] 2024-03-02 00:54
if its not picked up by next week i think i can pick up this issue.

**Comment by chiragsalian** [comment] 2024-03-05 21:11
I just picked this up.
Actually, i should create another internal issue for this. That way my PR won't end up closing this issue out. I'll create one shortly and keep you guys updated.

**Comment by chiragsalian** [comment] 2024-03-07 23:35
Investigated the backend today. When User A initiates a PayMoneyRequest on an IOU report but the IOU report was already deleted, how does this look for the response,
```json
{
    "code": 666,
    "jsonCode": 404,
    "type": "Expensify\\Libs\\Error\\ExpError",
    "UUID": "4c369f5a-3299-4562-be25-1ff15b3ebd70",
    "message": "The report does not exist.",
    "title": "",
    "data": {
        "onyxData": [
            {
                "onyxMethod": "merge",
                "key": "reportActions_2564012877219454",
                "value": {
                    "7366151788668142846": {
                        "errors": {
                            "1709854301667371": "The report does not exist."
                        }
                    }
                }
            }
        ]
    },
    "htmlMessage": "",
    "onyxData": [
        {
            "onyxMethod": "merge",
            "key": "reportActions_2564012877219454",
            "value": {
                "7366151788668142846": {
                    "errors": {
                        "1709854301667371": "The report does not exist."
                    }
                }
            }
        }
    ],
    "requestID": "S9JZmo"
}
```
I can change the jsonCode and message so i updated them to jsonCode: 404 and message: "The report does not exist". Can you let me know if that works and then I'll push my changes. If you prefer some changes let me know and i can incorporate them @allroundexperts @rojiphil.

**Comment by allroundexperts** [comment] 2024-03-08 14:15
Thanks @chiragsalian!

I think this should be it but lets wait on @rojiphil to confirm.

**Comment by rojiphil** [comment] 2024-03-08 20:22
@chiragsalian  @allroundexperts  Thanks for taking this forward. Looks like we are very close to nailing this. I also updated the [proposal](https://github.com/Expensify/App/issues/34851#issuecomment-1911952173) and it looks good from the perspective of FE changes except for one thing mentioned in the proposal as follows. What are your thoughts on this?

> I think it would be better for the BE to send an error code like `iou.error.reportDeleted` than the error string. This will help us to abide by the localization principle. BE can send an array with `isTranslated` set to `false` as demonstrated below:
> 
> ![Screenshot 2024-03-08 at 10 53 18 PM](https://github.com/Expensify/App/assets/3004659/56f43ef5-56d4-4b21-a11e-d8e38801b96f)

**Comment by chiragsalian** [comment] 2024-03-09 00:22
> I think it would be better for the BE to send an error code

Technically backend is sending an error code. Its jsonCode will be 404 with my changes.
I do not think backend ever sends an error code like `iou.error.reportDeleted` from my understanding i believe that's set from failure data in the front end.

> This will help us to abide by the localization principle. BE can send an array with isTranslated set to false as demonstrated below:

So i don't think backend ever sends isTranslated either. While i think it might be a nice change for backend to return a localization key like `iou.error.reportDeleted` i think that would be a larger discussion to decide if its worth it and to incorporate it into our design properly. If I'm mistaken and you think we do this elsewhere let me know. Until then i think by looking at the jsonCode or error message you can set localization error message if needed.

**Comment by rojiphil** [comment] 2024-03-09 05:39
> If I'm mistaken and you think we do this elsewhere let me know.

Thanks for your response. You are correct as I too do not see any place in FE where `isTranslated ` or error codes like `iou.error.reportDeleted` are processed. Looks like we still have some way to go before we arrive at a consensus on an agreed approach. Until then, we can consider this as an alternative solution if at all we want to proceed on this via a larger discussion.

> Until then i think by looking at the jsonCode or error message you can set localization error message if needed.

So, here is how both these options look to me.

1) Based on the `error` message:

If we consider BE sending an `error` message within the report actions, the FE will display it as it is for the report action. In the context of API response [here](https://github.com/Expensify/App/issues/34851#issuecomment-1984782587), I am referring to the `The report does not exist.` error message. I think based on the comment [here](https://github.com/Expensify/App/blob/9302ade9988b1cba3e07b48f474bc35a6deea7fb/src/libs/ErrorUtils.ts#L55C1-L55C102) FE considers this as already translated. If we go ahead with this approach, 
A) BE needs to ensure that the error message is a translated one
B) In FE, the current proposal still holds good largely. The only additional change would be to look at the error translations directly instead of `CONST.ERROR.REPORT_DELETED`. 
I think this may be the way to go.

The other alternative to this is to put the onus of translation of report action error messages to the FE as it is currently proposed. But then this would require a larger discussion as already mentioned.

2) Based on `jsonCode` error code:

Feels like we are venturing out into uncharted territory as I do not find a parallel for this. Please correct me if I am going wrong here. I think until now we have only set predefined `errors` at the time of making API request via `failureData` and, later, update Onyx with `failureData` [here](https://github.com/Expensify/App/blob/9302ade9988b1cba3e07b48f474bc35a6deea7fb/src/libs/actions/OnyxUpdates.ts#L44) as part of API response when `jsonCode` is not 200. But now we are also talking about dynamically adding the errors within `failureData` based on `jsonCode` as part of the API response. I am a little apprehensive about this as the code [here](https://github.com/Expensify/App/blob/9302ade9988b1cba3e07b48f474bc35a6deea7fb/src/libs/actions/OnyxUpdates.ts#L44) is a generic implementation and adding context-specific code just doesn’t seem right here. On the other hand, it could make sense if we want to apply this globally within the FE.

@chiragsalian  @allroundexperts  What are your thoughts on the above?

**Comment by chiragsalian** [comment] 2024-03-11 17:55
> Based on jsonCode error code:

I think this is the cleaner approach but I'll let @allroundexperts also weigh in.

> BE needs to ensure that the error message is a translated one

Yeah, i don't think backend ever sends a translated message. It would be a much larger BE design change to support this if necessary.

>  I think until now we have only set predefined errors at the time of making API request via failureData..

Hmm i don't think so, we can set errors like this - [code](https://github.com/Expensify/App/blob/1a9ceb775cd5c52a74405722689e0a1f38bfb3e9/src/components/DistanceRequest/index.tsx#L181-L196). Within the method we can look at prop data like the jsonCode for our example and set the translated error message accordingly. And then the error is displayed using DotIndicatorMessage like so - [code](https://github.com/Expensify/App/blob/1a9ceb775cd5c52a74405722689e0a1f38bfb3e9/src/components/DistanceRequest/index.tsx#L269-L273). Once the user clears the error message the reportAction should be removed. Let me know if that works for you.

**Comment by rojiphil** [comment] 2024-03-11 19:22
> We use API.makeRequestWithSideEffects and then check the jsonCode to throw a translated key if needed.

[Here](https://github.com/Expensify/App/blob/f4c73788da481103c5ad9400b5f26949f5b7d440/src/libs/API/index.ts#L97C1-L98C81), explicitly we are discouraged to use this. So I think it may be better to rule this out.

> I think this is the cleaner approach

I am also getting inclined towards using `jsonCode` as the error message from BE would have translation issues. However, I still think using `jsonCode` in the current form would be challenging. But I may be missing something here. Alternatively, if BE can send `jsonCode` instead of error message in Report Preview and Money Request action, I think that could do the trick. I am curious to know your thoughts on this while we wait for @allroundexperts comments.

**Comment by chiragsalian** [comment] 2024-03-11 20:23
I discussed this a bit with my team.
1. Yup, like you said `API.makeRequestWithSideEffects` is not advised.
2. It looks like we don't prioritize translating error messages. So if you want to display this error message as is that's totally fine too.
3. But on clear of the error message i imagine we'd want to clear the reportAction from the onyx data.

**Comment by chiragsalian** [comment] 2024-03-13 18:22
The more i think about this the more I'm convinced to not translate the error message, just show the server error message as is.

Friendly bump for your thoughts on the rest of our conversation here @allroundexperts.

**Comment by allroundexperts** [comment] 2024-03-13 18:37
> The more i think about this the more I'm convinced to not translate the error message, just show the server error message as is.
> 
> Friendly bump for your thoughts on the rest of our conversation here @allroundexperts.

In my opinion, the best approach to follow is:
> Based on jsonCode error code:
It makes our error messages more flexible and adds the ability to change them on the fly on frontend. Not only that, it also makes our API's more universal ie we might want to expose our API's to the public in the future and having error codes defined would make everything much easier to understand.

**Comment by chiragsalian** [comment] 2024-03-13 19:14
Cool sounds good to me. For now let's not focus on translating the error message though. Let's focus on showing the server error message in red along with a dismiss button and once the user clicks the dismiss button the action should be cleared from onyx. Sounds cool with you guys? 

Also, i just retested this issue. I think the delete request onyx data has been updated. So when userB deletes the request, once userA comes online and receives their updated onyx data the money request is no longer there. If that's the case then nothing needs to be done here right. Can someone double check.

**Comment by rojiphil** [comment] 2024-03-14 10:10
> I think the delete request onyx data has been updated. So when userB deletes the request, once userA comes online and receives their updated onyx data the money request is no longer there. If that's the case then nothing needs to be done here right. Can someone double check.

@chiragsalian I just double-checked and you are right. A recent change in BE to the Report Preview action (i.e. setting the message text to empty string) has caused it to be hidden in the report. If so, nothing needs to be done here as Report Preview disappears once the user comes online.

**Comment by slafortune** [comment] 2024-03-14 13:06
Thanks everyone for your attention to this - sounds like we're in the clear now.
Closing

**Closed by slafortune** 2024-03-14 13:06 UTC
Labels: Engineering, Daily, Internal, Bug
