### ISSUE TITLE
[HOLD for payment 2023-06-19] [$1000] Split Bill preview not showing correct description/currency 

### ISSUE THREAD

**Issue by kavimuru** [Expensify/App#19870] opened 2023-05-31 01:16 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Create a Split Bill request using currency A and no description
2. Start a new money request flow (send/request/split)
3. Choose currency B and set description to any text
4. Don't complete it and close the page
5. Press the Split Bill preview to see the detail
## Expected Result: 
The currency and description should show the currency and description used when creating the request
## Actual Result: 
The currency and description dynamically changes every time we set a new value from money request flow

## Workaround:
Can the user still use Expensify without this being fixed? Have you informed them of the workaround?

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android / native
- [x] Android / Chrome
- [x] iOS / native
- [x] iOS / Safari
- [x] MacOS / Chrome / Safari
- [x] MacOS / Desktop

**Version Number:** 1.3.20-3
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/43996225/092297b9-15b7-4331-b641-071603003621

https://github.com/Expensify/App/assets/43996225/228b4354-b760-4709-974b-16070df57758

**Expensify/Expensify Issue URL:**
**Issue reported by:** @bernhardoj 
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1685369261418519

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~012fa29a23a09e4f51</li>
        <li>Upwork Job ID: 1663824064534704128</li>
        <li>Last Price Increase: 2023-05-31</li>
    </ul>
</details>

**Comment by therealsujitk** [comment] 2023-05-31 03:15
## Proposal

### Please re-state the problem that we are trying to solve in this issue.

The description in the split bill details page gets reset to the latest value saved in Onyx. Note that the same issue also occurs for the currency code.

### What is the root cause of that problem?

The reason for this is because we are not getting these details from the report but rather from Onyx as shown in the code below.

https://github.com/Expensify/App/blob/2157057bdc23aaf1eb48846c9a87cd33ff6645ae/src/components/MoneyRequestConfirmationList.js#L318

https://github.com/Expensify/App/blob/2157057bdc23aaf1eb48846c9a87cd33ff6645ae/src/components/MoneyRequestConfirmationList.js#L348

### What changes do you think we should make in order to solve the problem?


To fix this these values have to passed down as props from the [`SplitBillDetailsPage`](https://github.com/Expensify/App/blob/2157057bdc23aaf1eb48846c9a87cd33ff6645ae/src/pages/iou/SplitBillDetailsPage.js#L65). This prop will be `undefined` by default, if so it'll use the values from Onyx like it is done for `iouAmount`.

### What alternative solutions did you explore? (Optional)
None.

**Comment by BhuvaneshPatil** [comment] 2023-05-31 08:55
original proposal here - https://github.com/Expensify/App/issues/19855#issuecomment-1569371969

## Proposal

### Please re-state the problem that we are trying to solve in this issue.
in Split bill detail page, the description shown is not matching with original

### What is the root cause of that problem?
For `MoneyRequestConfirmationList` we are taking `IOU` from Onyx, that is global IOU.
https://github.com/Expensify/App/blob/0d1995a209218f721eb8ba123091b17d3fb29964/src/components/MoneyRequestConfirmationList.js#L361-L372 example - When I try to create new Split Bill, the IOU will be using its description for the value. It's being set at below - 
https://github.com/Expensify/App/blob/0d1995a209218f721eb8ba123091b17d3fb29964/src/pages/iou/MoneyRequestDescriptionPage.js#L53-L56

### What changes do you think we should make in order to solve the problem?
Like we are passing the `iouAmount` to `MoneyRquestConfirmationList` component, we can pass the new prop `iouComment` from `SplitBillDetailsPage`. Similarly we can add another prop for currency as well.
The values for them can be grabbed from `reportAction` in `SplitBillDetailsPage` component.
<details>
<summary>Working Solution
</summary>

https://github.com/Expensify/App/assets/27822551/9fefe5ca-3f56-4f3a-92cb-2bba75ba9ba2



</details>

### What alternative solutions did you explore? (Optional)
- Updating IOU in ONYX using `setMoneyRequestDescription()` can be a alternative, however this change should be made carefully, because that value(IOU) is being used at many places. When we open the modal we can use `setMoneyRequestDescription()` to set the value of description and upon closing we can reset it to empty string.

- We can pass the reportAction as a prop as well, if there are multiple things we need to add from reportAction to `MoneyRequestConfirmationLinks`

**Comment by esh-g** [comment] 2023-06-01 19:41
# Proposal

## Please re-state the problem that we are trying to solve in this issue
'Description' field displays blank content for split bill participants

## What is the root cause of that problem?
The root cause is that we are using MoneyRequestConformationList component while creating the split bill as well as displaying details of the IOU reportAction. While creating bill, the `this.props.iou.comment` is defined and is passed to the description text but while viewing details,` this.props.iou.comment` is undefined because the viewing details come from the `reportAction` and not from `ONYXKEYS.IOU` which was the case while creating the bill.

https://github.com/Expensify/App/blob/d661708d0aae864caeceb98801e921f07c0954a8/src/components/MoneyRequestConfirmationList.js#L346-L353

## What changes do you think we should make in order to solve the problem?
https://github.com/Expensify/App/blob/d661708d0aae864caeceb98801e921f07c0954a8/src/pages/iou/SplitBillDetailsPage.js#L85-L93
While rendering the MoneyRequestConformationList in SplitBillDetailsPage, we are passing the amount as a prop but not the comment. So, we need to pass a prop called `iouComment` which should be equal to `lodashGet(reportAction, 'originalMessage.comment', '')` Just like we do for amount on line 71.
Then in MoneyRequestConformationList we need to check if `this.props.iouComment` exists, then display that, otherwise display `this.props.iou.comment` like this: (in line 348, MoneyRequestConformationList.js)
```
title={this.props.iouComment || this.props.iou.comment}
```

After Applying:


https://github.com/Expensify/App/assets/77237602/865a12fc-32f4-4336-8ac0-7000371d078f

**Comment by esh-g** [comment] 2023-06-01 19:53
Proposals of @therealsujitk and @BhuvaneshPatil will cause a regression because we are using `MoneyRequestConformationList` while displaying details as well as while creating a bill, and for that we cannot completely replace `this.props.iou.comment` like suggested in their proposals.

https://github.com/Expensify/App/assets/77237602/a0159b34-1a32-4224-8531-0558311c0b5e

**Comment by therealsujitk** [comment] 2023-06-01 23:09
@esh-g I didn't say to fully replace it, please read the proposal properly. It will use the value from Onyx if `undefined` **exactly** as your proposal says so.

**Comment by Julesssss** [comment] 2023-06-02 10:03
Bumping for review @eVoloshchak

**Comment by eVoloshchak** [comment] 2023-06-02 11:00
All of the proposals are quite similar, I think we should proceed with the first proposal that correctly identified the root cause.
Since https://github.com/Expensify/App/issues/19870 is a dupe of this issue, I did review proposals in both.
@BhuvaneshPatil's [proposal](https://github.com/Expensify/App/issues/19870#issuecomment-1569777297) was posted first ([here](https://github.com/Expensify/App/issues/19855#issuecomment-1569371969)), It looks good to me

🎀👀🎀 C+ reviewed!
cc: @Julesssss

**Comment by BhuvaneshPatil** [comment] 2023-06-03 03:54
Hello, I have applied. PR will be ready by EOD. Thank you

**Comment by BhuvaneshPatil** [comment] 2023-06-09 13:17
Hello, the PR is merged. What is next process?

**Comment by Julesssss** [comment] 2023-06-09 13:37
We're still waiting for it to be [deployed to production](https://github.com/Expensify/App/blob/main/contributingGuides/CONTRIBUTING.md#completing-the-final-checklist). We often don't deploy on Fridays, but you should see an automated comment on this issue either today or Monday.

**Comment by BhuvaneshPatil** [comment] 2023-06-21 10:13
@eVoloshchak @Julesssss @flaviadefaria 
friendly bump for further process.

**Comment by Julesssss** [comment] 2023-06-21 10:25
This one is ready to pay once the checklists above are filled by @flaviadefaria and @eVoloshchak 👍

**Comment by flaviadefaria** [comment] 2023-06-21 11:28
Waiting for @eVoloshchak to complete the checklist so that I can issue the following payments:
@bernhardoj $250
@BhuvaneshPatil $1000 (no bonus)
@eVoloshchak $1000 (no bonus)

**Comment by BhuvaneshPatil** [comment] 2023-06-21 11:44
Hello @flaviadefaria , can you please share the timing of assignment and when the PR got merged, because there was a weekend in between.

**Comment by Julesssss** [comment] 2023-06-21 13:03
I think our CI script failed to generate it for this PR. Removing the Saturday and Sunday I think is eligible: 

**Assigned**
<img width="249" alt="Screenshot 2023-06-21 at 14 01 49" src="https://github.com/Expensify/App/assets/10736861/2bdd0b11-ae6a-4168-87d2-9cecf62b7ce2">


**Merged**
![Screenshot 2023-06-21 at 14 02 06](https://github.com/Expensify/App/assets/10736861/cc78f621-e311-4486-b6c3-d94293e214d5)

**Comment by flaviadefaria** [comment] 2023-06-21 13:12
Cool, thanks for checking. So updated payments will be:
@bernhardoj $250
@BhuvaneshPatil $1000 + $500 bonus
@eVoloshchak $1000 + $500 bonus

I'll issue then as soon as @eVoloshchak completes the checklist above.

**Comment by eVoloshchak** [comment] 2023-06-22 17:44
-  The PR that introduced the bug has been identified. Link to the PR: N/A, that's how it was implemented initially in https://github.com/Expensify/App/pull/2194

-  The offending PR has been commented on, pointing out the bug it caused and why, so the author and reviewers can learn from the mistake. Link to comment: N/A

-  A discussion in #expensify-bugs has been started about whether any other steps should be taken (e.g. updating the PR review checklist) in order to catch this type of bug sooner. Link to discussion: Don't think there's anything we could add to our processes/docs, this was simply missed during the initial implementation

- Determine if we should create a regression test for this bug.
_Is it easy to test for this bug? Yes
Is the bug related to an important user flow? Yes
Is it an impactful bug? Yes_

**Comment by eVoloshchak** [comment] 2023-06-22 17:47
**Regression Test Proposal**

1.  Press FAB -> Create a Split Bill request using currency A and no description
2. Start a new money request flow (send/request/split)
3. Choose another currency and enter a description
4. Don't complete it and close the page
5. Press the Split Bill preview to see the details of the first split bill
6. Verify currency and description arr correct for the first split bill

**Do we agree 👍 or 👎**

**Comment by BhuvaneshPatil** [comment] 2023-06-22 18:04
I have tested it, shows the correct currency and description. Sharing video soon

**Comment by Julesssss** [comment] 2023-06-26 10:36
Hey @flaviadefaria, based on your [last question](https://github.com/Expensify/App/issues/19870#issuecomment-1600811229), I think we are good to pay out now?

**Comment by flaviadefaria** [comment] 2023-06-26 11:20
Yep, now we are. I'll handle the payment today.

**Comment by Julesssss** [comment] 2023-06-26 11:26
Thanks

**Comment by flaviadefaria** [comment] 2023-06-26 11:54
Offer sent!

**Comment by flaviadefaria** [comment] 2023-06-26 12:11
All done so closing this GH.

**Closed by flaviadefaria** 2023-06-26 12:11 UTC
Labels: External, Daily, Awaiting Payment, Bug
