### ISSUE TITLE
[HOLD for payment 2024-11-18] mWeb - "Saved" header is also highlighted when saved search is selected

### ISSUE THREAD

**Issue by IuliiaHerets** [Expensify/App#51984] opened 2024-11-04 18:46 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 9.0.57-0
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**Email or phone of affected tester (no customers):** applausetester+kh22100010ad@applause.expensifail.com
**Issue reported by:** Applause Internal Team

## Action Performed:
1. Go to staging.new.expensify.com
2. Go to Search.
3. Tap on the filter icon.
4. Add any filter.
5. Tap Save search.
6. Tap on the dropdown.

## Expected Result:
Only the currently opened saved search will be highlighted.

## Actual Result:
"Saved" header is also highlighted when saved search is selected.

## Workaround:
Unknown

## Platforms:

- [x] Android: Standalone
- [x] Android: HybridApp
- [x] Android: mWeb Chrome
- [ ] iOS: Standalone
- [ ] iOS: HybridApp
- [ ] iOS: mWeb Safari
- [ ] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

https://github.com/user-attachments/assets/69f5014d-8fed-40ca-80bc-68ca9939107d

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Issue Owner</summary>Current Issue Owner: @adelekennedy</details>

**Comment by luacmartins** [comment] 2024-11-04 20:46
I have a PR up. Since this is a small issue, I'll remove the blocker label so we can properly test it to make sure it wont cause other regressions.

**Comment by greg-schroeder** [comment] 2024-11-18 07:08
FYI @adelekennedy this was a regression from https://github.com/Expensify/App/issues/50779, so I don't believe payment is due for the reviewer role in this case

**Comment by luacmartins** [comment] 2024-11-18 16:31
I agree. Closing.

**Closed by luacmartins** 2024-11-18 16:31 UTC
Labels: Engineering, Daily, Overdue, Awaiting Payment, Bug
