### ISSUE TITLE
Workspace - System throws an error when refreshing 'Invite new members' page immediately after creating a workspace

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#23536] opened 2023-07-25 10:29 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Click on 'Profile' avatar
2. Click on 'Workspaces' link
3. Open an existing workspace
4. Click on 'Members' link
5. Click on 'Invite' button
6. Refresh the page

## Expected Result:
No error should be thrown & 'Invite new members' page should be displayed

## Actual Result:
 'Invite new members' page is closed * system throws an error & user can't clear the error by clicking the close icon

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [x] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [x] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 1.3.45-1
**Reproducible in staging?:** y
**Reproducible in production?:** n
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/93399543/2cd15588-8e33-44f4-8610-0bdf3867f016

https://github.com/Expensify/App/assets/93399543/a52064af-1a86-49c1-a138-6ad2d097e206

**Expensify/Expensify Issue URL:**
**Issue reported by:**  @Natnael-guchima
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1690272138001129

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by flodnv** [comment] 2023-07-25 12:21
@Natnael-Guchima @kbecciv I can't presently reproduce on staging 😕 can you?

**Comment by Natnael-Guchima** [comment] 2023-07-25 12:28
I am able to reproduce it @flodnv. To reproduce it, I think, the following condition must hold.
1. Create a new workspace 
2. Navigate to the 'Invite new members' page immediately after creating the workspace 
3. Refresh the page

Let me know if it not working with these steps😃

https://github.com/Expensify/App/assets/57330233/2098763b-1128-4b3b-a8bd-2bde8cc04cfe

**Comment by flodnv** [comment] 2023-07-25 12:43
Ah yes, I was able to reproduce now

**Comment by flodnv** [comment] 2023-07-25 13:52
git bisect shows this commit caused the bug: https://github.com/Expensify/App/pull/22727/commits/46595c37d5bd4359a2b63839542bbd1be0bff0b2

Indeed, with this diff on `main`:
```diff
diff --cc src/libs/actions/PersistedRequests.js
index c99ed2ace7,f2bafb0d13..0000000000
--- a/src/libs/actions/PersistedRequests.js
+++ b/src/libs/actions/PersistedRequests.js
@@@ -25,16 -25,14 +25,9 @@@ function save(requestsToPersist) 
   * @param {Object} requestToRemove
   */
  function remove(requestToRemove) {
-     /**
-      * We only remove the first matching request because the order of requests matters.
-      * If we were to remove all matching requests, we can end up with a final state that is different than what the user intended.
-      */
-     const index = _.findIndex(persistedRequests, (persistedRequest) => _.isEqual(persistedRequest, requestToRemove));
 -    const persistedRequestsCopy = _.clone(persistedRequests);
 -    const index = _.findIndex(persistedRequestsCopy, (persistedRequest) => _.isEqual(persistedRequest, requestToRemove));
--    if (index !== -1) {
-         persistedRequests.splice(index, 1);
 -        persistedRequestsCopy.splice(index, 1);
 -        persistedRequests = persistedRequestsCopy;
--    }
 -
 -    Onyx.set(ONYXKEYS.PERSISTED_REQUESTS, persistedRequestsCopy);
++    persistedRequests = _.reject(persistedRequests, (persistedRequest) => _.isEqual(persistedRequest, requestToRemove));
 +
 +    Onyx.set(ONYXKEYS.PERSISTED_REQUESTS, persistedRequests);
  }
  
  /**
```

The bug is gone. Should we revert [that PR](https://github.com/Expensify/App/pull/22727) @puneetlath @allroundexperts @namhihi237 ?

**Comment by puneetlath** [comment] 2023-07-25 14:17
Looks like it caused another deploy blocker here: https://github.com/Expensify/App/issues/23542#issuecomment-1649928206

**Comment by puneetlath** [comment] 2023-07-25 14:29
Here's a PR to revert: https://github.com/Expensify/App/pull/23551

@allroundexperts can you do the reviewer checklist?

**Comment by flodnv** [comment] 2023-07-25 15:52
Thanks all! The bug is gone from staging so we can close this.

**Comment by Natnael-Guchima** [comment] 2023-07-25 15:54
@flodnv I reported this issue. And no reporting bonus is issued 🙃.

**Comment by Natnael-Guchima** [comment] 2023-07-25 16:07
Accepted the offer. Thanks @puneetlath

**Comment by puneetlath** [comment] 2023-07-25 16:12
Paid!

**Closed by puneetlath** 2023-07-25 16:12 UTC
Labels: Reviewing, Engineering, Weekly
