### ISSUE TITLE
[On-Hold for Mentions #379005][$500] [LOW] Save the world - The email refers to people by email address + grammar issue

### ISSUE THREAD

**Issue by izarutskaya** [Expensify/App#31112] opened 2023-11-09 11:31 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.3.97.0
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** Applause-Internal Team
**Slack conversation:** @

## Action Performed:
1. Navigate to https://staging.new.expensify.com/
2. Click on the FAB button
3. Click on the "Save the word" button
4. Click on the "I know a teacher" button
5. Fill in all fields
6. Click on the "Let's do this!" button
7. Open your email app

## Expected Result:
The mail should start with "Hey".
If the name of the sender and teacher is known (filled out before sending) the email should refer them by name.

## Actual Result:
The email for the teacher starts with ": Hey".
It refers to both the sender and the teacher by email address.

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [x] Android: mWeb Chrome
- [x] iOS: Native
- [x] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

https://github.com/Expensify/App/assets/115492554/29d24079-7acd-477f-b9df-76c205eca15e

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~019c866a41051c1129</li>
        <li>Upwork Job ID: 1722577721011531776</li>
        <li>Last Price Increase: 2023-11-09</li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @roryabraham</details>

**Comment by erquhart** [comment] 2023-11-09 12:26
Not seeing email templates in Expensify's OSS repos, guessing this is an internal issue.

**Comment by CortneyOfstad** [comment] 2023-11-09 20:45
Yeah, this would be internal — going to get engineering eyes on this 👍

**Comment by erquhart** [comment] 2023-11-13 14:36
This is internal but Help Wanted label is still applied.

**Comment by CortneyOfstad** [comment] 2023-11-13 18:16
@roryabraham any ideas with this one?

**Comment by CortneyOfstad** [comment] 2023-11-20 16:08
Bump @roryabraham — TIA!

**Comment by roryabraham** [comment] 2023-11-21 20:29
Ok, so this happens because the HTML in question looks like this:

```cpp
const string whisperMessageForTeacher = "Hey <mention-user>@" + partnerUserID + "</mention-user>! Your friend <mention-user>@" + inviterEmail + "</mention-user> referred you to Expensify.org's latest campaign which helps teachers and their students. Our Teachers Unite campaign splits teachers' out-of-pocket expenses for essential school supplies. <a href=\"" + AuthCommand::getURLToNewDot() + "teachersunite/i-am-a-teacher\" rel=\"noreferrer noopener\">Click on Save The World</a> in the app's main menu to sign up now and start splitting your expenses with Expensify.org!";
```

This displays in-product as a mention, which by our current design does not use `displayName` at all, and instead just uses the full email. There was [a ton of discussion](https://expensify.slack.com/archives/C01GTK53T8Q/p1678810680548199) about this but I think we went with full emails for simplicity in the V1. cc @puneetlath 

So if we wanted to change this it would need to be a broader discussion around mentions in general

**Comment by roryabraham** [comment] 2023-11-21 20:35
My main questions here are:

- Do we care about this issue?
- Why did we end up always using full emails for mentions? Is that a long-term plan? Whatever happened to [this nice mockup](https://expensify.slack.com/archives/C01GTK53T8Q/p1679085315969439?thread_ts=1678810680.548199&cid=C01GTK53T8Q)?
- If we don't have any plans to update how mentions are displayed in-product, should we hack something up to inject displayNames for mentions in emails?

**Comment by roryabraham** [comment] 2023-11-21 20:43
I suppose even if we _were_ going to change how mentions are displayed in-product, it would probably be a front-end thing that happens on the fly where we lookup the personal details for that login and show their displayName, rather than using the displayName that can change at any time in the HTML.

So I feel like our options here are:

- :donothing:
- Update `NotifyOfflineUsersAboutActivity` to search for any instances of `<mention-user>` tags and replace them with the displayName for that user, if one exists. Maybe need to grab this from the form as I'm not sure if that form is going to actually set the invitee's personalDetails or not

**Comment by puneetlath** [comment] 2023-11-22 18:05
Just to give some context: 

We currently support two types of mentions as both: 
1. `<mention-user accountID=1234></mention-user>`
2. `<mention-user>@fullemailadress@gmail.com</mention-user>`

The long-term plan is to transition all mentions to be the first. Then the client will decide how to render the mention, based on the data available in personalDetails. It could be any of: 
- `@rory@expensify.com`
- `@rory`
- `@Rory`
- `@Rory Abraham`
- etc

So once we fully transition to the `<mention-user accountID=1234></mention-user>` approach, we will need to update our email notifications to handle that. Maybe it's best to go ahead and do that now? And then update these whisper messages to use the first style of mentions.

**Comment by CortneyOfstad** [comment] 2023-11-27 14:54
> So once we fully transition to the <mention-user accountID=1234></mention-user> approach, we will need to update our email notifications to handle that. Maybe it's best to go ahead and do that now? And then update these whisper messages to use the first style of mentions.

@roryabraham @sobitneupane does that work for you guys?

**Comment by CortneyOfstad** [comment] 2023-11-27 14:55
> So once we fully transition to the approach, we will need to update our email notifications to handle that. Maybe it's best to go ahead and do that now? And then update these whisper messages to use the first style of mentions.

@roryabraham @sobitneupane does that work for you guys?

**Comment by roryabraham** [comment] 2023-11-28 20:38
Thanks for the context @puneetlath. I'll get started on a PR to make our emails expand mentions using the information available about the user.

**Comment by roryabraham** [comment] 2023-11-30 19:39
Btw, I think overdue is sticking around since I made myself the issue owner in K2.

Moving this back to weekly as it's not particularly urgent

**Comment by roryabraham** [comment] 2023-12-06 21:01
Mini update – I think [`Notification_Standard::macroReplace`](https://github.com/Expensify/Web-Expensify/blob/5bc241187f4457d86612031bca6d4933acd954bc/lib/Notification/Standard.php#L1124-L1164) might be the right place to implement this change.

**Comment by CortneyOfstad** [comment] 2023-12-11 15:30
Thanks @roryabraham!

**Comment by CortneyOfstad** [comment] 2023-12-12 13:43
No worries and thanks for the context @roryabraham! Going to adjust the frequency on this as well to help avoid those pesky overdue labels 👍

**Comment by CortneyOfstad** [comment] 2023-12-21 14:06
Not overdue!

**Comment by CortneyOfstad** [comment] 2023-12-21 17:33
Not overdue

**Comment by roryabraham** [comment] 2023-12-24 00:40
Back from jury duty now, but obviously we're headed into Christmas. I expect I should be able to provide another substantive update next week

**Comment by roryabraham** [comment] 2024-01-02 23:48
Another small update with a WIP PR: https://github.com/Expensify/Web-Expensify/pull/40342. Still need to test, but in theory that should work for users that already have personalDetails saved. It's also likely that I'll need to update that invite form to set personal details on the invited account with the values from the form too.

**Comment by roryabraham** [comment] 2024-01-16 04:57
Sorry, no update over the last few weeks, have been swamped trying to get some more urgent things over the finish line.

**Comment by roryabraham** [comment] 2024-01-29 20:57
Brought this up as a potential candidate to get added into wave6: https://expensify.slack.com/archives/C02MW39LT9N/p1706561779540699?thread_ts=1706548232.782599&cid=C02MW39LT9N

**Comment by CortneyOfstad** [comment] 2024-01-31 18:27
@roryabraham any updates? Thanks!

**Comment by CortneyOfstad** [comment] 2024-02-07 16:16
@roryabraham bump ^^^ thanks!

**Comment by CortneyOfstad** [comment] 2024-02-15 18:28
It looks like Rorys comment was finally updated to approve this for Wave6, so added that project. Based on this, it looks like the urgency is low, so selected that frequency. If you feel that needs to be adjusted, please let me know @roryabraham 👍

**Comment by roryabraham** [comment] 2024-02-20 18:23
Sorry, I am currently spread too thin, so I'm going to send this issue back to the pool, hopefully having left some useful breadcrumbs for someone to pick up where I left off.

**Comment by CortneyOfstad** [comment] 2024-02-22 18:42
Adjust the tags to also include `hot pick` for engineers to select

**Comment by CortneyOfstad** [comment] 2024-03-11 16:33
Was OoO last week, but this is not overdue — still waiting on an engineer. Since this is listed as "polish," going to keep at Weekly 👍

**Comment by CortneyOfstad** [comment] 2024-03-18 14:21
Huzzah — this is going to be fixed via https://github.com/Expensify/Expensify/issues/379005. This is in the works, so going to adjust the title and put this on-hold until that is resolved.

**Comment by CortneyOfstad** [comment] 2024-04-01 13:05
Doc is still being reviewed so no update 👍

**Comment by CortneyOfstad** [comment] 2024-05-01 15:14
Still no update on the on-hold issue. David just bumped them [here](https://github.com/Expensify/Expensify/issues/379005#issuecomment-2081152410), so will continue to monitor 👍

**Comment by CortneyOfstad** [comment] 2024-05-15 13:19
Only a small amount still left! 

Project link [here](https://github.com/orgs/Expensify/projects/133)

**Comment by CortneyOfstad** [comment] 2024-06-03 13:29
Only 3 issues left 😍

**Comment by CortneyOfstad** [comment] 2024-06-25 13:44
Per [this comment](https://github.com/Expensify/Expensify/issues/379005#issuecomment-2161573442), there are two issues that are backlog, which will delay this a bit. However, good progress across the board! 🎉

**Comment by CortneyOfstad** [comment] 2024-07-29 15:04
Getting close! Most recent comment is [here](https://github.com/Expensify/Expensify/issues/379005#issuecomment-2255953237)

**Comment by CortneyOfstad** [comment] 2024-07-31 12:15
No update on on-hold issue

**Comment by CortneyOfstad** [comment] 2024-08-12 14:40
Latest update is [here](https://github.com/Expensify/Expensify/issues/379005#issuecomment-2272119580)!

**Comment by CortneyOfstad** [comment] 2024-08-19 13:55
Only [two bugs](https://github.com/Expensify/Expensify/issues/379005#issuecomment-2293774003) left! 🎉

**Comment by mvtglobally** [comment] 2024-09-21 04:23
Issue not reproducible during KI retests. (First week)

**Comment by CortneyOfstad** [comment] 2024-09-23 14:36
Waiting on [this last bug](https://github.com/Expensify/App/issues/38025) 🎉

**Comment by mvtglobally** [comment] 2024-10-05 03:06
Issue not reproducible during KI retests. (Second week)

**Comment by CortneyOfstad** [comment] 2024-10-14 14:21
Still waiting on https://github.com/Expensify/react-native-live-markdown/issues/317

**Comment by mvtglobally** [comment] 2024-10-19 03:47
Issue not reproducible during KI retests. (Third week)

**Comment by mvtglobally** [comment] 2024-10-30 09:39
Issue not reproducible during KI retests. (Fourth week)

**Comment by mvtglobally** [comment] 2024-11-08 15:21
Issue not reproducible during KI retests. (Fifth week). Can we close this?

**Closed** 2024-11-12 18:04 UTC
Labels: Engineering, Monthly, Internal, Bug, Hot Pick
