### ISSUE TITLE
[HOLD for payment 2022-08-11] [$250] The create group chat list uses different default avatars than the actual users who you invite

### ISSUE THREAD

**Issue by mvtglobally** [Expensify/App#9876] opened 2022-07-13 03:45 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/docs/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. open app 
2. Click + > Create group 
3. select few existing and new users to be added to the group 

## Expected Result:
The avatars should be consistent 

## Actual Result:
The create group chat list uses different default avatars than the actual users who you invite

## Workaround:
Can the user still use Expensify without this being fixed? Have you informed them of the workaround?

## Platform:

Where is this issue occurring?

- Web
- iOS
- Android
- Desktop App
- Mobile Web

**Version Number:** 1.1.82-0
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**Email or phone of affected tester (no customers):** 
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation 
<img width="376" alt="image - 2022-07-12T234310 342" src="https://user-images.githubusercontent.com/43995119/178646081-998bef66-36d2-4d1b-be35-e808a222dee1.png">
<img width="372" alt="image - 2022-07-12T234308 937" src="https://user-images.githubusercontent.com/43995119/178646084-a7572c0a-af70-4dac-8901-5ea6931262c2.png">

**Expensify/Expensify Issue URL:** 
**Issue reported by:** @shawnborton 
**Slack conversation:** https://expensify.slack.com/archives/C01GTK53T8Q/p1657639279664059

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by tylerkaraszewski** [comment] 2022-07-13 15:32
This seems super low priority but I do agree it would be better.

**Comment by Christinadobrzyn** [comment] 2022-07-13 17:24
Created Upwork job 

Internal posting - https://www.upwork.com/ab/applicants/1547270524636602368/job-details
External posting - https://www.upwork.com/jobs/~01b994676f0c2a7858

**Comment by puneetlath** [comment] 2022-07-14 19:52
Hm, I'm also not able to reproduce this on Desktop. Perhaps this was already fixed. @Christinadobrzyn are you able to reproduce it?

**Comment by Santhosh-Sellavel** [comment] 2022-07-15 19:29
This issue is possible in one scenario where you never initiated a chat with the account you are adding to the group.

**Comment by Santhosh-Sellavel** [comment] 2022-07-15 19:30
I believe that's expected behaviour

**Comment by shawnborton** [comment] 2022-07-17 15:49
Interesting, I think I would have expected all of the avatar colors to appear random and not all in green. Thoughts on that?

**Comment by Santhosh-Sellavel** [comment] 2022-07-17 16:27
> Interesting, I think I would have expected all of the avatar colors to appear random and not all in green. Thoughts on that?

Yeah we could do that.

**Comment by eVoloshchak** [comment] 2022-07-18 17:48
**Proposal:**
Nothing prevents us from showing avatar of the correct color even for users you never initiated a chat with. For the `Details` page we generate avatar colors on [this](https://github.com/Expensify/App/blob/b31f0eb107e1068058b8925e81aa95b98959f54a/src/libs/OptionsListUtils.js#L125) line, but for the `New group` page, we use [defaultAvatarForUserToInvite](https://github.com/Expensify/App/blob/b31f0eb107e1068058b8925e81aa95b98959f54a/src/libs/OptionsListUtils.js#L94), intentionally not passing `login` to `ReportUtils.getDefaultAvatar`.
All we need to do is change this line 
https://github.com/Expensify/App/blob/b31f0eb107e1068058b8925e81aa95b98959f54a/src/libs/OptionsListUtils.js#L594
``` diff
+   userToInvite.icons = [ReportUtils.getDefaultAvatar(login)];
```

Before:

https://user-images.githubusercontent.com/9059945/179571424-2b785694-4ccb-4cc7-aa74-1183f1e763cf.mp4

After:

https://user-images.githubusercontent.com/9059945/179571532-4bb9a755-9f64-41f2-a4d8-d166d903414a.mp4

**Comment by Santhosh-Sellavel** [comment] 2022-07-18 18:27
@puneetlath 

Need to ensure this case alone,

Consider users A & B both have set a profile picture. Also, User A & User B never had a one-to-one chat. 
Now when `User A` tries to create a group with `User B` we would show a random colored avatar only in suggestion.

If are expecting just to randomize the avatar color then we are good to go with @eVoloshchak's proposal else we need to look for a different proposal.

**Comment by shawnborton** [comment] 2022-07-18 19:53
I think we can keep it simple and just randomize the color per the proposal above.

**Comment by Christinadobrzyn** [comment] 2022-07-20 22:07
Ah sorry, @puneetlath I missed your ping about testing - https://github.com/Expensify/App/issues/9876#issuecomment-1184837886. It looks like we're moving forward with a fix!

The [original job posting](https://www.upwork.com/ab/applicants/1547270524636602368/job-details) is closed so I can't hire @Santhosh-Sellavel as the C+. 

I created a duplicate Upwork posting and hired you as the C+ @Santhosh-Sellavel 

Internal posting: https://www.upwork.com/ab/applicants/1549878109834797056/job-details
External posting: https://www.upwork.com/jobs/~01fe88959409bc009c

**Comment by Christinadobrzyn** [comment] 2022-08-01 17:14
QA is ongoing for the PR - https://github.com/Expensify/App/pull/9963#issuecomment-1195899754

**Comment by eVoloshchak** [comment] 2022-08-06 21:17
Is https://github.com/Expensify/App/issues/10220 considered a regression, should I submit the [fix](https://github.com/Expensify/App/issues/10220#issuecomment-1203529729) for it?

**Comment by Santhosh-Sellavel** [comment] 2022-08-07 17:07
@puneetlath 
Looks mostly related to root of this issue.
I think this is not a treated as regression. Also issue not introduced by fix provided here. 

I'll looking forward to hear your thoughts too on this thanks!

**Comment by Santhosh-Sellavel** [comment] 2022-08-08 18:24
@puneetlath bump

**Comment by puneetlath** [comment] 2022-08-08 22:21
Sorry! I was off last week. Thanks for the bumps. 

I agree that it's not a regression. That's how we agreed to implement it. So I think it's fine to just go ahead and handle that on the separate issue.

**Comment by Christinadobrzyn** [comment] 2022-08-12 03:49
Looks like we're good to pay this! 

Paid @eVoloshchak through this job - https://www.upwork.com/jobs/~01b994676f0c2a7858
Paid @Santhosh-Sellavel as C+ through this job - https://www.upwork.com/jobs/~01fe88959409bc009c

Closed the jobs in Upwork and closing this GH

**Closed by Christinadobrzyn** 2022-08-12 03:49 UTC
Labels: Exported, External, Engineering, Weekly, Awaiting Payment
