### ISSUE TITLE
[HOLD for payment 2024-02-09] [$250] Room - Tapping on "Leave" room directed to previously visited page for an second

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#35579] opened 2024-02-01 17:34 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.35
**Reproducible in staging?:** Y
**Reproducible in production?:** N
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** Applause - Internal Team
**Slack conversation:**

## Action Performed:
1. Launch app
2. Tap on any report
3. Navigate back to LHN
4. Tap fab---Start chat
5. Tap room
6. Enter all required fields
7. Tap create room
8. Tap on top right 3 dots and select "Leave" room

## Expected Result:
When user leaves room, previously visited page must not be shown for an second and user must be navigated to concierge page

## Actual Result:
When user leaves room, previously visited page( in step 2 visited page) shown for an second and then only navigated to concierge page

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [ ] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details> 

https://github.com/Expensify/App/assets/78819774/1de431a8-bcd4-4e18-8f54-8e1c550b465d

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~0171a4f0bb95566a69</li>
        <li>Upwork Job ID: 1753162906835521536</li>
        <li>Last Price Increase: 2024-02-09</li>
<li>Automatic offers: </li>
<ul>
<li>situchan | Reviewer | 28135564</li>
<li>dukenv0307 | Contributor | 28135565</li>
</ul></li>
    </ul>
</details>

**Comment by situchan** [comment] 2024-02-01 18:29
This is deploy blocker. @dukenv0307 do you know offending PR?

**Comment by situchan** [comment] 2024-02-01 19:05
I am not sure about the expected behavior.
After adding `visibility`, it doesn't return to Concierge chat.

**Comment by bondydaa** [comment] 2024-02-01 21:05
sounds like that PR might have introduced a few regressions but nothing too major so we'll just patch them as needed instead of reverting the PR.

Going to assign you @dukenv0307 and @situchan for everything.

**Comment by getusha** [comment] 2024-02-01 21:09
@situchan @dukenv0307 just as a note, we do navigate to Concierge if there is no report opened before leaving the room.

**Comment by situchan** [comment] 2024-02-01 21:10
@getusha thanks for the note

**Comment by sakluger** [comment] 2024-02-01 21:18
@bondydaa @situchan @dukenv0307 it seems like you all have this under control - let me know if I can help with anything.

**Comment by bondydaa** [comment] 2024-02-01 21:55
👍 yeah just assigned you so I wouldn't forget like I have in the past for payment stuff, sort of skipped past the first steps of BZ team on ya. mostly I think you're just along for the ride for now 😂

**Comment by mountiny** [comment] 2024-02-01 22:26
@dukenv0307 are you able to raise the PR with a fix soon? I also suggest to lower the reward for this one to $250 because its very simple change and we have already done couple PRs patching the missing properties. Does that work for you @dukenv0307 ? Thanks!

**Comment by sakluger** [comment] 2024-02-09 15:26
Changing the bounty to $250 on @mountiny's suggestion since he confirmed it was the fair price before the PR was merged.

**Comment by sakluger** [comment] 2024-02-09 15:30
All paid out!

@situchan could you please complete the BZ checklist before I close the issue?

**Comment by situchan** [comment] 2024-02-09 15:31
offending PR: https://github.com/Expensify/App/pull/30168
Since it was large refactor, this was easily missed.

As this was deploy blocker, we can skip regression test. QA team caught this during staging regression testing.

**Comment by sakluger** [comment] 2024-02-09 16:02
Nice, thanks for that! Closing out 👍

**Closed by sakluger** 2024-02-09 16:02 UTC
Labels: External, Engineering, Daily, Awaiting Payment, Bug
