### ISSUE TITLE
[PAID][$500] NewDot App scroll is 2-3x faster than other apps

### ISSUE THREAD

**Issue by mvtglobally** [Expensify/App#10654] opened 2022-08-29 14:55 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Navigate to any chat with a lot of messages 
2. Scroll through the tread quickly 
3. Leave your finger on the trackpad and move it a little

## Expected Result:
Match the scroll behaviour with native apps, having a different speed will influence the users as they will notice it differs and there is no reason for this

## Actual Result:
One trackpad of scrolling in Slack seems to scroll about 2/3 of a screen -- which feels "right".  But one trackpad of scrolling in NewDot scrolls like 3 screens, which feels like way too much.

## Workaround:
unknown 

## Platform:

Where is this issue occurring?

- Web
- iOS
- Android
- Desktop App
- Mobile Web

**Version Number:** 1.1.91-0
**Reproducible in staging?:** Y
**Reproducible in production?:** Y 
**Email or phone of affected tester (no customers):** 
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation

https://user-images.githubusercontent.com/43995119/187230792-45e6b932-1834-4269-b96f-4334f6da32ed.mp4

**Expensify/Expensify Issue URL:** 
**Issue reported by:** @quinthar 
**Slack conversation:** https://expensify.slack.com/archives/C01GTK53T8Q/p1661767055711919?thread_ts=1661331711.805659&cid=C01GTK53T8Q

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by luacmartins** [comment] 2022-08-30 07:26
I couldn't reproduce this. I'll mark it as external to get more eyes on it though.

**Comment by laurenreidexpensify** [comment] 2022-08-30 09:05
https://www.upwork.com/jobs/~01fe8cc5249f5233cc

**Comment by Santhosh-Sellavel** [comment] 2022-08-31 13:40
@luacmartins Any thoughts?

cc: @Expensify/design

**Comment by Santhosh-Sellavel** [comment] 2022-08-31 15:41
I believe not!

**Comment by AndrewGable** [comment] 2022-08-31 15:56
Yes I believe we did introduce it recently with the react-native-web update.

**Comment by luacmartins** [comment] 2022-09-09 10:24
I'm not sure that this is actually an issue. I've been testing the scroll in our platforms and they seem fine to me. I vote we close this issue. Does anybody else disagree? @AndrewGable @shawnborton since you commented here.

**Comment by shawnborton** [comment] 2022-09-09 14:52
I mostly use NewDot desktop app with an external mouse and scroll wheel and I haven't experienced this personally. So I would lean on someone to test the scenario in which is described above (trackpad + NewDot web) to see if it feels funky there still?

**Comment by luacmartins** [comment] 2022-09-14 13:52
IMO the scrolling speed seems fine on trackpad + web. I'm leaning towards closing this issue.

**Comment by laurenreidexpensify** [comment] 2022-09-20 12:15
Doublechecking if we should close https://expensify.slack.com/archives/C01SKUP7QR0/p1663676075990669

**Comment by mountiny** [comment] 2022-09-20 12:22
I also could not really reproduce and I think we can close this issue.

**Comment by quinthar** [comment] 2022-11-04 18:24
This is 100% still happening.

**Comment by quinthar** [comment] 2022-11-04 20:47
Here's a video of scrolling in a normal website, versus scrolling in NewDot.  Note that NewDot scrolls like 2-3x faster.

https://user-images.githubusercontent.com/575186/200071831-4724cc45-dcc7-46f7-8570-9508554dbedb.mp4


https://user-images.githubusercontent.com/575186/200071795-bbc7daa4-6133-4fc5-97c3-8c2f5250905c.mp4

**Comment by laurenreidexpensify** [comment] 2022-11-07 11:46
Ah I see what you mean @quinthar. Okay getting this back and live on Upwork.

**Comment by mountiny** [comment] 2022-11-07 11:50
Carlos is OOO for 2 weeks now so assigning myself as CME. 

Waiting for proposals, @thomas-coldwell might be interested into this one.

**Comment by laurenreidexpensify** [comment] 2022-11-07 11:53
https://www.upwork.com/jobs/~01fd1a95401ef8c40d new post

**Comment by mountiny** [comment] 2022-11-07 11:54
I have updated the `Expected results` a bit, in a nutshell we should just make sure the scrolling behaviour is _same_ as on other native app/browsers. The speed and reaction should be same as in Chrome, or Safari in web/desktop. On native platforms it should be same as in WhatsApp/Messenger, they all have the same speed/behaviour, no reason for NewDot having some custom speed.

**Comment by parasharrajat** [comment] 2022-11-07 12:12
I have a proposal above.

**Comment by mountiny** [comment] 2022-11-07 12:20
@parasharrajat does that guarantee the scroll speed will be the same as in other apps and in browsers? It still feels like something we define/ hardcode

**Comment by mountiny** [comment] 2022-11-07 15:41
I think the issue might be that in native platform the scroll speed is dynamic. The more you move your finger on trackpad/display, the faster it scrolls. How do native scrollViews handle this in ReactNative 🤔

**Comment by dbond09** [comment] 2022-11-07 17:15
### Proposal
In the current implementation, we are attaching an event listener to handle the scrolling of `InvertedFlatList`, because `FlatList` was handling the scroll direction incorrectly. It turns out that this same solution was implemented with the update of `react-native-web` (see the [issue](https://github.com/necolas/react-native-web/issues/995)), so now two very similar event listeners handle the scroll events, essentially leading to twice as large scrolling distance as intended.

My solution is to factor out the current "hacked" implementation, and just use simple inverted `FlatList`s, as the underlying problem was fixed.


[Here](https://user-images.githubusercontent.com/22153853/200372375-8385e8ff-61e0-429e-a1e7-ee6a83ba0bc8.mov) you can see scrolling one trackpad-height on both sides, with the right one using my implementation.

**Comment by Santhosh-Sellavel** [comment] 2022-11-07 23:25
@dbond09 Solution looks good to me.
C+ Reviewed
🎀 👀 🎀 
@mountiny Please have a look at let me know your thoughts too, thanks!

**Comment by mountiny** [comment] 2022-11-07 23:44
@dbond09 @Santhosh-Sellavel Will this solution also implement a native iOS/Android scrolling behaviour? That means speed and also the dynamic aspect of it?

What needs to be done so the invertedFlatList can behave like that

**Comment by Santhosh-Sellavel** [comment] 2022-11-07 23:51
@mountiny 
I believe native platforms are working correctly, if not we have to look for other solutions.

> What needs to be done so the invertedFlatList can behave like that

We need to remove the `invertedWheelEvent` listener here!
https://github.com/Expensify/App/blob/91acada3b65af8c465febe6853bcc7d37995f0f4/src/components/InvertedFlatList/index.js#L43-L46

**Comment by parasharrajat** [comment] 2022-11-08 00:28
How will this [proposal](https://github.com/Expensify/App/issues/10654#issuecomment-1305934229) handle inverted scrolling?

**Comment by Santhosh-Sellavel** [comment] 2022-11-08 00:33
It is available with the linked issue it was closed with this commit https://github.com/necolas/react-native-web/commit/7ec2489c78f9734bae5bcfdc514b0c91621a6300

**Comment by dbond09** [comment] 2022-11-08 01:07
@Santhosh-Sellavel You got it correctly.

**Comment by mountiny** [comment] 2022-11-08 10:38
@Santhosh-Sellavel @dbond09 Thanks! 

Please @dbond09 raise the PR and lets get to testing. I think this will improve the experience quite a bit!

**Comment by dbond09** [comment] 2022-11-08 17:59
@mountiny The PR is almost ready. Please accept my proposal on Upwork.

**Comment by mountiny** [comment] 2022-11-09 09:26
cc @laurenreidexpensify

@dbond09 the payment will be scheduled one week after the deployment to production, just so you are aware of the process everyone follows here. The guidelines are here https://github.com/Expensify/App/blob/main/contributingGuides/CONTRIBUTING.md

**Comment by laurenreidexpensify** [comment] 2022-11-09 12:59
@dbond09 do you have a link to the draft PR? Thanks!

**Comment by mountiny** [comment] 2022-11-14 22:29
@Santhosh-Sellavel Can you by any chance find the PR which updated the package but did not remove the custom handler? thank you, I would look tomorrow

**Comment by laurenreidexpensify** [comment] 2022-11-16 15:04
Checking where to put this in testrail https://expensify.slack.com/archives/C01SKUP7QR0/p1668611021810339

**Comment by AndrewGable** [comment] 2022-11-17 21:19
Seems much better! Thanks for the fix.

**Comment by mountiny** [comment] 2022-11-17 21:22
+1 it is way nicer on mobile especially but web is great too

**Comment by laurenreidexpensify** [comment] 2022-11-23 15:31
@mountiny @Santhosh-Sellavel is this the PR that introduced the regression https://github.com/Expensify/App/pull/11035?

**Comment by laurenreidexpensify** [comment] 2022-11-23 15:35
Asking about TestRail [here](https://expensify.slack.com/archives/C01SKUP7QR0/p16692176728015090)

**Comment by laurenreidexpensify** [comment] 2022-11-24 10:59
Payment issued, let's close out the final steps in the checklist

**Comment by Santhosh-Sellavel** [comment] 2022-11-24 13:36
@laurenreidexpensify This PR Qualifies for an additional bonus $250 for both!

**Comment by Santhosh-Sellavel** [comment] 2022-11-25 15:38
> @mountiny @Santhosh-Sellavel is this the PR that introduced the regression #11035?

No that's not the PR.

**Comment by Santhosh-Sellavel** [comment] 2022-11-29 18:47
I believe these are the PRs
https://github.com/Expensify/react-native-web/pull/6 - Which included a fix to our fork
 https://github.com/Expensify/App/pull/10434 - Fork to App.

**Comment by Santhosh-Sellavel** [comment] 2022-11-29 18:48
> @laurenreidexpensify This PR Qualifies for an additional bonus $250 for both!

bump again!

**Comment by mountiny** [comment] 2022-11-30 10:47
@Santhosh-Sellavel Asked internally

**Comment by laurenreidexpensify** [comment] 2022-11-30 11:09
Hey @Santhosh-Sellavel - payment of $750 was issued in Upwork  6 days ago, which was $500 for the job and the $250 bonus. Please recheck your account and let me know if this did not reflect on Upwork. Thanks

**Closed by laurenreidexpensify** 2022-11-30 11:09 UTC
Labels: Reviewing, External, Engineering, Daily, Bug

**Comment by mountiny** [comment] 2022-11-30 14:18
Thanks @Santhosh-Sellavel and @laurenreidexpensify 

I think in this case the offending PR is fine given it is RN update, that is very hard to catch every possible issue.
