### ISSUE TITLE
Assign task - Green dot in LHN is displayed after the task has been cancelled

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#27890] opened 2023-09-20 20:30 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Go to https://staging.new.expensify.com/

2. Log in with any Gmail account
3. On LHN, click on the FAB button
4. Select Assign Task
5. Enter a title, description
6. Assign the task to yourself
7. On Share Somewhere, select a conversation with another user you have access to
8. Click on the 3 dot menu in the task report
9. Cancel the task

## Expected Result:
The task report is archived
The green dot in LHN is not displayed after the task has been cancelled (chat can be found at the bottom of LHN)

## Actual Result:
The task report is not archived
The green dot in LHN is displayed after the task has been cancelled

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android / native
- [x] Android / Chrome
- [x] iOS / native
- [x] iOS / Safari
- [x] MacOS / Chrome / Safari
- [x] MacOS / Desktop

**Version Number:** 1.3.72-6

**Reproducible in staging?:** Yes

**Reproducible in production?:** No

**If this was caught during regression testing, add the test name, ID and link from TestRail:**

**Email or phone of affected tester (no customers):**

**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/78819774/0b62d495-7304-45a5-8898-35e792957d03

Video in Production 

https://github.com/Expensify/App/assets/78819774/d55157fa-794a-4300-9726-2cc292dbb8c1

**Expensify/Expensify Issue URL:**

**Issue reported by:** Applause - Internal Team

**Slack conversation:**

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by gadhiyamanan** [comment] 2023-09-21 02:58
Dupe of https://github.com/Expensify/App/issues/27805

**Comment by jasperhuangg** [comment] 2023-09-21 04:13
It seems this is already going to be fixed in https://github.com/Expensify/App/issues/27805. It seems a bug that was present on dev made its way to staging.

**Comment by jasperhuangg** [comment] 2023-09-21 04:13
I'm going to update the other issue and close this one out.

**Closed** 2023-09-21 04:15 UTC
Labels: DeployBlockerCash, Engineering, Hourly, Bug
