### ISSUE TITLE
[HOLD for payment 2023-08-16] [$1000] Message with button gets cut off early for certain length of emails

### ISSUE THREAD

**Issue by kavimuru** [Expensify/App#23769] opened 2023-07-27 22:23 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Open ND on android
2. Click on FAB > split bill > enter an amount
3. Share with account emails which are not renamed (for easier reproduction use these emails for testing [nathanmulugetatesting+123@gmail.com](mailto:nathanmulugetatesting+123@gmail.com), [nathanmulugetatesting+1234@gmail.com](mailto:nathanmulugetatesting+1234@gmail.com), [nathanmulugetatesting+12345@gmail.com](mailto:nathanmulugetatesting+12345@gmail.com))
4. Split the bill
5. Click on the IOU card
6. Select one of the contacts from the side panel
7. Observe the Message with button
## Expected Result: 
Message with button should not be cut off early
## Actual Result: 
Message with button gets cut off early.

## Workaround:
Can the user still use Expensify without this being fixed? Have you informed them of the workaround?

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [ ] MacOS / Chrome / Safari
- [ ] MacOS / Desktop
 
**Version Number:** 1.3.47-1
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/43996225/3730e72e-d70f-4245-9c80-9c7e3f37d3b6

<img src="https://github.com/Expensify/App/assets/43996225/fde2270a-4a9d-4ef1-be34-6da1e7611b07" width="40%" height="40%">

**Expensify/Expensify Issue URL:**
**Issue reported by:** @nathan-mulugeta
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1690444037073499

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~013be117aa6991d578</li>
        <li>Upwork Job ID: 1685001865802149888</li>
        <li>Last Price Increase: 2023-07-28</li>
<li>Automatic offers: </li>
<ul>
<li>Ollyws | Contributor | 25886833</li>
<li>ahmedGaber93 | Contributor | 25909402</li>
<li>nathan-mulugeta | Reporter | 25909403</li>
</ul></li>
    </ul>
</details>

**Comment by ahmedGaber93** [comment] 2023-07-27 22:52
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
Message with button gets cut off early for certain length of emails
### What is the root cause of that problem?
ther is no style flex1 on title which is important for android when using ellipsis to take the full space available.
### What changes do you think we should make in order to solve the problem?
add style styles.flex1 to titleTextStyle here.
https://github.com/Expensify/App/blob/975146fa30bc65a19df8e0cca525af32ce2ceda5/src/components/MenuItem.js#L81

### What alternative solutions did you explore? (Optional)
we can pass style styles.flex1 in props.titleStyle if we need to support this case only

**Comment by garrettmknight** [comment] 2023-07-28 18:58
Confirmed on browserstack

**Comment by Santhosh-Sellavel** [comment] 2023-07-28 23:32
Seems like a regression to me, couldn't find any. It's hard to reproduce, needs a proper root cause here why it occurs thanks!

**Comment by pradeepmdk** [comment] 2023-07-29 11:41
### Proposal

### Please re-state the problem that we are trying to solve in this issue.
A message with a button gets cut off early for a certain length of emails

### What is the root cause of that problem?

In React Native, the `Text` component does not automatically take the full available space within its parent container by default. This behavior is different from web-based HTML elements, where elements such as `<div>` automatically take the full width of their parent container.

The reason why the `Text` component doesn't take full space is because of its inherent behavior as a text-rendering component. The width of the `Text` component is determined by the size of its content, and it will wrap to the next line if the content exceeds the available width. The default width of a `Text` component is essentially based on the width required to display its content without overflowing.

If we want the Text component to take full space or expand to fill the available width of its parent container, we need to explicitly specify a width style for the Text component or use flexbox properties to control its dimensions.

### What changes do you think we should make in order to solve the problem?
     1) using Flexbox `flex:1`
     2) Using Fixed Width:  `width:100%`
What alternative solutions did you explore? (Optional)

**Comment by garrettmknight** [comment] 2023-07-31 12:38
@Santhosh-Sellavel can you take a look at this root cause analysis today?

**Comment by Santhosh-Sellavel** [comment] 2023-07-31 17:33
Left a comment [here](https://expensify.slack.com/archives/C02NK2DQWUX/p1690824771304289) for volunteers to take over

**Comment by allstarsmen** [comment] 2023-08-01 02:29
I found if we add `flex1` or `flex:1` to MenuItem.js will create another issue.

https://github.com/Expensify/App/blob/975146fa30bc65a19df8e0cca525af32ce2ceda5/src/components/MenuItem.js#L81

Before adding `flex1`

![Screenshot_1690856471](https://github.com/Expensify/App/assets/497313/8e293685-4714-4433-b654-a690b5d36200)

After adding `flex1`, It will move the `Check` icon to the end of the row.

![Screenshot_1690856576](https://github.com/Expensify/App/assets/497313/badc5ad4-d4d8-4fe5-8c47-b7d14e20c8a8)

**Comment by garrettmknight** [comment] 2023-08-01 18:42
Hey @Ollyws - good to have you! Can you take a look at the root cause proposal [here](https://github.com/Expensify/App/issues/23769#issuecomment-1656711385) when you get a chance and let us know what you think?

**Comment by ahmedGaber93** [comment] 2023-08-02 15:20
## Proposal
[Updated](https://github.com/Expensify/App/issues/23769#issuecomment-1654683433)

**Comment by ahmedGaber93** [comment] 2023-08-04 01:59
@Ollyws [PR](https://github.com/Expensify/App/pull/24142) is now ready for review.

**Comment by garrettmknight** [comment] 2023-08-16 09:32
@Ollyws have you started a discussion around regression or created a regression test? Once you do, I'll process payment on this issue.

**Comment by garrettmknight** [comment] 2023-08-18 22:00
@Ollyws are you getting paid via NewDot or Upwork?

**Comment by garrettmknight** [comment] 2023-08-21 17:41
Paid via Upwork. Closing!

**Closed by garrettmknight** 2023-08-21 17:41 UTC
Labels: External, Daily, Overdue, Awaiting Payment, Bug
