### ISSUE TITLE
[HOLD for payment 2022-12-23] [$1000] Web splash screen does not work correctly on dev

### ISSUE THREAD

**Issue by roryabraham** [Expensify/App#13123] opened 2022-11-29 07:15 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
Run the dev web app.

## Expected Result:
The JS code for splash screen (and the `.svg` component) should be inlined in index.html instead of included in a separate bundle.

<img width="455" alt="Screen Shot 2022-11-28 at 11 45 58 PM" src="https://user-images.githubusercontent.com/47436092/204469228-24f4616a-bd82-44ae-b9a9-ff4d66424621.png">
<img width="783" alt="image" src="https://user-images.githubusercontent.com/47436092/204469210-e066a1cb-ebd4-4385-b899-48357ddc8511.png">

## Actual Result:
This works as expected on staging and production, but not on dev. On dev the splash screen JS ends up in a separate bundle, not inlined.

<img width="1101" alt="Screen Shot 2022-11-28 at 11 42 35 PM" src="https://user-images.githubusercontent.com/47436092/204468730-a5c547fa-7194-46b5-828a-23ac493cf9c5.png">

## Workaround:
n/a – only affects developers.

## Platform:
Where is this issue occurring?

- Web
- Desktop App
- Mobile Web

**Version Number:** 1.2.32-1
**Reproducible in staging?:** no
**Reproducible in production?:** no
**Notes/Photos/Videos:** I created an issue [over here](https://github.com/icelam/html-inline-script-webpack-plugin/issues/402) to ask the library maintainer about this.

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

## Upwork Automation - Do Not Edit
- Upwork Job URL: https://www.upwork.com/jobs/~01ea03aab22a5c88d1
- Upwork Job ID: 1597497576249335808
<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01e02c14f4b93626af</li>
        <li>Upwork Job ID: 1603853587688243200</li>
        <li>Last Price Increase: 2022-12-16</li>
    </ul>
</details>

**Comment by roryabraham** [comment] 2022-11-29 07:22
Confirmed that removing `SpeedMeasurePlugin` altogether fixes the issue. Going to see if we can employ [this workaround](https://github.com/stephencookdev/speed-measure-webpack-plugin/issues/167#issuecomment-976836861)

**Comment by roryabraham** [comment] 2022-11-29 07:45
Unfortunately none of the workarounds listed in https://github.com/stephencookdev/speed-measure-webpack-plugin/issues/167 seem to work to resolve the issue.

**Comment by roryabraham** [comment] 2022-11-29 07:47
Going to make this external and see if we can get a fix that doesn't force us to give up speed-measure-webpack-plugin completely, since it is a useful tool for what it does.

**Comment by JalalMitali** [comment] 2022-11-29 13:33
I can't reproduce this issue on Safari MacOS

**Comment by mdneyazahmad** [comment] 2022-11-29 13:39
@JalalMitali make this changes in order to reproduce.

```diff
diff --git a/config/webpack/webpack.dev.js b/config/webpack/webpack.dev.js
index 2a418f882..f692d2147 100644
--- a/config/webpack/webpack.dev.js
+++ b/config/webpack/webpack.dev.js
@@ -59,5 +59,5 @@ module.exports = (env = {}) => portfinder.getPortPromise({port: BASE_PORT})
             },
         });
 
-        return speedMeasure.wrap(config);
+        return config;
     });

```

**Comment by JalalMitali** [comment] 2022-11-29 14:11
okay thanks and by the way I don't have the following :
`--- a/config/webpack/webpack.dev.js
+++ b/config/webpack/webpack.dev.js`

**Comment by WestDon** [comment] 2022-11-29 14:28
**Proposal**

Update webpack.dev.js
with following lines:

`        const confPlugins = config.plugins;
        
        const pluginsToSkipMeasure = confPlugins.filter(item => item.constructor.name === 'HtmlWebpackPlugin' || item.constructor.name === 'HtmlInlineScriptPlugin');
        
        config.plugins = confPlugins.filter(x => !pluginsToSkipMeasure.includes(x));

        const configWithTimeMeasures = new SpeedMeasurePlugin().wrap(config);

        configWithTimeMeasures.plugins.push(...pluginsToSkipMeasure);

        return configWithTimeMeasures;`
        
The following plugins, HtmlWebpackPlugin and HtmlInlineScriptPlugin, don't work with HtmlWebpackPlugin as excepted, so the idea is for the dev to exclude them from SpeedMeasurePlugin wrapper

**Comment by roryabraham** [comment] 2022-11-29 20:18
Not sure how viable it is, but I would love to see a proposal for an upstream fix in SpeedMeasurePlugin that doesn't rely on a workaround like this.

**Comment by ShuiRuTian** [comment] 2022-12-01 03:58
I believe https://github.com/Expensify/App/pull/13182 will fix the issue, and it will also improve("fix" might be more proper) the build/rebuild speed.

The fix PR replace SpeedMeasurePlugin with time-analytics-webpack-plugin, because SpeedMeasurePlugin is almost dead and time-analytics-webpack-plugin fixes some situations(like this).

And, as the author of time-analytics-webpack-plugin, any feedback is welcomed.

**Comment by Santhosh-Sellavel** [comment] 2022-12-01 04:36
@ShuiRuTian 

Please read our contributing [guidelines](https://github.com/Expensify/App/blob/main/contributingGuides/CONTRIBUTING.md#) to understand our process.

Also Refer [proposing a solution to the job](https://github.com/Expensify/App/blob/main/contributingGuides/CONTRIBUTING.md#propose-a-solution-for-the-job).

So as first step close the PR and write a proper proposal here thanks!

**Comment by ShuiRuTian** [comment] 2022-12-01 05:31
**Proposal**

What we need to do:
Replace `speed-measure-plugin` with `time-analytics-webpack-plugin`.

Reason:
1. `speed-measure-plugin` is almost dead and does not get any updates for about 1.5 years. 

2. `speed-measure-plugin` will make custom hooks of other plugins go wrong. This will cause some strange issues. I guess this issue is just caused by this reason.

3. This replacement will also fix the build speed, In my machine, the first build time is reduced from 47s to 34s, and the rebuild time is reduced from 10s to 3s. Not sure whether this is due to the correct use of the plugin or webpack could reuse some internal cache.

4. I am the author of `time-analytics-webpack-plugin`. I want feedback from real users. And if there is any regression, I could provide response as soon as possible. It's win-win.

Tech details:
"tap" methods are the callback that every webpack plugin will use to do something at some time point.
`speed-measure-plugin` uses Proxy to take over the control of "tap" methods, so that it could measure the time.
However, the reference of Proxy object and the origin target is different. So Map and WeakMap will treat them as different key, then the value is not correct either.
`time-analytics-webpack-plugin` hack for such keys, so the plugin will work.

**Comment by Santhosh-Sellavel** [comment] 2022-12-01 16:49
Thanks, @ShuiRuTian, seems we are not likely to give up the plugin based on this [comment](https://github.com/Expensify/App/issues/13123#issuecomment-1330218089).  

@roryabraham What's your thought?

**Comment by roryabraham** [comment] 2022-12-02 01:02
@ShuiRuTian I'm intrigued.

@Santhosh-Sellavel I'm willing to consider @ShuiRuTian's proposal since I agree it seems like https://github.com/stephencookdev/speed-measure-webpack-plugin is close to EOL:

- https://github.com/stephencookdev/speed-measure-webpack-plugin/issues/187
- https://github.com/stephencookdev/speed-measure-webpack-plugin/issues/160
- https://github.com/stephencookdev/speed-measure-webpack-plugin/issues/149
- https://github.com/stephencookdev/speed-measure-webpack-plugin/issues/174

**Comment by Santhosh-Sellavel** [comment] 2022-12-05 19:14
Thanks, @roryabraham. I too agree with the points mentioned [here](https://github.com/Expensify/App/issues/13123#issuecomment-1334635826). 

What factors should I consider while reviewing this one, as this is a new library?

**Comment by Santhosh-Sellavel** [comment] 2022-12-06 22:09
Tests well, @roryabraham bump!

**Comment by roryabraham** [comment] 2022-12-06 22:24
Well if it tests well I'd say we can take a chance on the new library. Typically we look at factors like:

- How popular the library is
- How actively maintained it is
- How well documented it is

But in this case this library is brand new and solves a specific problem we're having with an unmaintained library, so I'm good with using it.

**Comment by ShuiRuTian** [comment] 2022-12-07 04:47
I think we could reopen this PR now: https://github.com/Expensify/App/pull/13182

**Comment by Santhosh-Sellavel** [comment] 2022-12-07 15:10
We could do that too, Let's start on a clean state. Please submit a fresh PR if possible to avoid some unnecessary confusion, thanks!

**Comment by ShuiRuTian** [comment] 2022-12-07 16:27
The new clean PR is here: https://github.com/Expensify/App/pull/13399

**Comment by roryabraham** [comment] 2022-12-07 19:35
Thanks for the quick PR. I reviewed and requested a number of changes. Let's keep the urgency up on this and get those changes addressed quickly so that we can get the fix out and get everyone paid as soon as possible.

**Comment by Santhosh-Sellavel** [comment] 2022-12-09 20:45
@ShuiRuTian Please get your changes done, We have still one business day left to merge the PR for qualifying a bonus. Else we might lose it!

**Comment by Santhosh-Sellavel** [comment] 2022-12-12 14:41
PR is reviewed, hopefully, will be merged today!

**Comment by roryabraham** [comment] 2022-12-14 17:34
Looks like the PR was merged

**Comment by CortneyOfstad** [comment] 2022-12-16 20:44
Heading OoO for the next two weeks (which is over the held payment date) so reassigning

**Comment by Santhosh-Sellavel** [comment] 2022-12-21 23:08
I guess this PR qualifies for a 50% bonus, as the delay was due to some other lint issue.

**Comment by mallenexpensify** [comment] 2022-12-24 01:25
@ShuiRuTian , @Santhosh-Sellavel can you please accept the job and reply here once you have? 
https://www.upwork.com/jobs/~01ea03aab22a5c88d1

**Comment by ShuiRuTian** [comment] 2022-12-26 03:30
@mallenexpensify @Santhosh-Sellavel 
Thanks. I accepted the job just now on upwork.

**Comment by mallenexpensify** [comment] 2022-12-27 00:21
Paid @ShuiRuTian and @Santhosh-Sellavel, $1000 each. The bonus timeline doesn't reflect this issue - Dec 6th hired, Dec 14th merged. 

@Santhosh-Sellavel can you check off these please?
https://github.com/Expensify/App/issues/13123#issuecomment-1354111793

@CortneyOfstad , please do too, I'll try to help over break if I have time

**Comment by Santhosh-Sellavel** [comment] 2022-12-28 01:17
@mallenexpensify 
Regarding the checklist 

There is no offending PR here as it doesn't cause any issues on production. Also, this is a development-only case where we just migrating to a new library for measuring build stats,  so please anyone check all off (I don't have permission)

cc: @roryabraham

**Comment by mallenexpensify** [comment] 2022-12-28 23:04
Thanks @Santhosh-Sellavel, I'm still new to the BZ checklists. 
So.. even though the issue is unlocked, you still can't check the boxes, I didn't know that.  I addressed in a #contributor-plus thread [here](https://expensify.slack.com/archives/C02NK2DQWUX/p1672268506368889?thread_ts=1672173999.496869&cid=C02NK2DQWUX). 

I missed the 'on dev' part (yes, even though it's clearly in the title).  Based on that, I think we can close this for now.  comment/reopen if needed

**Closed by mallenexpensify** 2022-12-28 23:04 UTC
Labels: Reviewing, External, Daily, Help Wanted, Awaiting Payment, Bug
