### ISSUE TITLE
Switching tabs or apps selects text in search input

### ISSUE THREAD

**Issue by kavimuru** [Expensify/App#18513] opened 2023-05-05 23:24 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:

1. Click on the search icon
2. write something in the search text input
3. Open another tab and return back to newDot tab

## Expected Result:
The text in the search input box should not be selected. Just like it doesn't in other text inputs
## Actual Result:
The text inside the search input gets selected

## Workaround:
Can the user still use Expensify without this being fixed? Have you informed them of the workaround?

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [x] MacOS / Chrome / Safari
- [ ] MacOS / Desktop
 
**Version Number:** 1.3.11-4
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation

https://user-images.githubusercontent.com/43996225/236583596-a5c19431-bfe1-4c97-a917-efff8662d04a.mp4

https://github.com/Expensify/App/assets/111440031/c280d191-1b20-4935-8767-6a4e610a5b6f

**Expensify/Expensify Issue URL:**
**Issue reported by:** @nathan-mulugeta
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1683276526905619

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by sakluger** [comment] 2023-05-08 18:20
@kavimuru the second screenshot looks like a different bug. Could you review and remove it if it's for a different bug?

**Comment by tienifr** [comment] 2023-05-09 10:43
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
The text in search input box is selected after switching browser tab.

### What is the root cause of that problem?
Currently, the input `selectTextOnFocus` in [BaseOptionsSelector](https://github.com/Expensify/App/blob/bc8cc52162dca556db0a9b4a4719d09682e49745/src/components/OptionsSelector/BaseOptionsSelector.js#L291) is being set to true. This makes the text selected every time the input is focused. When we switch tab and switch back, the page is repainted and the input is focused.

### What changes do you think we should make in order to solve the problem?
Removing the `selectTextOnFocus` will solve the issue

### What alternative solutions did you explore? (Optional)
None

### Records
Working well after the fix



https://github.com/Expensify/App/assets/113963320/af782745-088f-4690-922f-2a9e201a0208

**Comment by sakluger** [comment] 2023-05-09 17:58
Assigning this back to @kavimuru to clarify if both GIFs in the description apply to this bug.

**Comment by sakluger** [comment] 2023-05-10 22:00
Hi @Nathan-Mulugeta, that's a separate video from either in the original description. I was asking if the second video is related to this issue, because if it's not, I'd like to delete it to avoid confusion for anyone who is working on the issue.

**Comment by Nathan-Mulugeta** [comment] 2023-05-11 01:28
Yes @sakluger the second video is from another bug report, the video I have linked is the original video found on the bug report, you can check it out on the slack discussion. I think you can delete the second video linked.

**Comment by sakluger** [comment] 2023-05-13 22:42
Thanks @Nathan-Mulugeta!

I tested this and confirmed it's happening as described, and it's true that the search field is the only field that behaves this way. But I'm not sure if it negatively impacts the user experience, or if it does, not that much. I've raised in Slack for discussion and will update here when I get some feedback.

**Comment by sakluger** [comment] 2023-05-13 22:54
I got back some feedback - the browser select text in search upon focus by default, and we don't want to change this behavior.

**Closed by sakluger** 2023-05-13 22:54 UTC
Labels: Daily, Bug
