### ISSUE TITLE
[$1000] Chat - An anonymous user don't see any hover states when mousing over a user

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#21488] opened 2023-06-24 12:03 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Open Incognito window
2. Open a public room https://staging.new.expensify.com/r/5593084223054221
3. Mousing over a user

## Expected Result:
An anonymous user should see hover states when mousing over a user

## Actual Result:
An anonymous user don't see any hover states when mousing over a user

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [x] MacOS / Chrome / Safari
- [x] MacOS / Desktop

**Version Number:** 1.3.29.0

**Reproducible in staging?:** y

**Reproducible in production?:** y

**If this was caught during regression testing, add the test name, ID and link from TestRail:**

**Email or phone of affected tester (no customers):**

**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/93399543/80e7cd4b-1b9e-4652-8ac6-5353db1a56a4

**Expensify/Expensify Issue URL:**

**Issue reported by:** David Barrett

**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1686956197780569

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01f0f8567b6aaa4284</li>
        <li>Upwork Job ID: 1673185121191821312</li>
        <li>Last Price Increase: 2023-07-10</li>
    </ul>
</details>

**Comment by alitoshmatov** [comment] 2023-06-24 12:23
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
Chat - An anonymous user don't see any hover states when mousing over a user
### What is the root cause of that problem?
When user is anonymous they don't have any data in `personalDetails` and we are just passing `accountID` here to tooltips which is resulting tooltip not having any data
https://github.com/Expensify/App/blob/46bf1b9b5eeb1e155844ec963644eca432c3ba19/src/pages/home/report/ReportActionItemSingle.js#L122-L129

And here for displayed names
https://github.com/Expensify/App/blob/34df808f487fe0cf5840f1d59ecb285a8a1a1a70/src/pages/home/report/ReportActionItemFragment.js#L148-L155
### What changes do you think we should make in order to solve the problem?
We should pass `fallbackUserDetails` to `UserDetailsTooltip` so that it can have available default values.
We should pass these values for tooltip wrapped avatar
```javascript
fallbackUserDetails={{
                                displayName: actorHint,
                                avatar: avatarSource,
                            }}
``` 

For display names we should pass `fallbackUserDetails` alongside `accountID` here 
https://github.com/Expensify/App/blob/46bf1b9b5eeb1e155844ec963644eca432c3ba19/src/pages/home/report/ReportActionItemSingle.js#L145-L152

### What alternative solutions did you explore? (Optional)

**Comment by alexpensify** [comment] 2023-06-26 04:24
Labeling as `External`, I confirmed this is a bug. Here are my test results: 

Non-Incognito window

![2023-06-25_21-21-27](https://github.com/Expensify/App/assets/8107070/b60dd20e-27c4-4e9c-9ef2-3ed7d6ccff1a)

Incognito window

![2023-06-25_21-21-50](https://github.com/Expensify/App/assets/8107070/3fdfd367-0b74-4878-aa9d-fda8dbbc9182)

**Comment by manjesh-yadav** [comment] 2023-06-26 09:31
This problem is related to the API while migrating from `PersonalDetails` to `PersonalDetailsList`.
We are not getting `PersonalDetailsList` data in response when we call the API command `OpenReport` when the user is not login, It is working when user is login

I don't think this data restriction is an App flow because the same data we get when we click on the avatar, then the tooltip also works fine.

**Comment by sobitneupane** [comment] 2023-06-27 08:10
@alitoshmatov Thanks for the proposal.

You have proposed to pass `fallbackUserDetails` to display the tooltip. Can you please explain what is `actorHint` and how is the variable available in those files?

**Comment by alitoshmatov** [comment] 2023-06-27 09:27
@sobitneupane 
As far as I understood `actorHint` is email of user, and it. is provided in these line:
https://github.com/Expensify/App/blob/e5f00f86fb412702e9c212b5a88766a8ef7da611/src/pages/home/report/ReportActionItemSingle.js#L78

**Comment by alitoshmatov** [comment] 2023-06-27 09:28
Also I think since opening user details is only showing display name not email, we can maybe ommit this email field in tooltip and just show display name and avatar

**Comment by sobitneupane** [comment] 2023-06-28 11:47
I think it's good idea to show email whenever it is available.

I noticed that we are showing default avatar instead of user-uploaded image for users. It looks like a related issue.
What do you think @alitoshmatov?

**Comment by sobitneupane** [comment] 2023-06-29 14:39
> Yes that's because initially we don't have userDetailsList value provided by the backend. When we open user details, individual call is being to backend to fetch user data

@alitoshmatov In that case I believe we should solve the issue first. We expect the pictures to be shown if user has uploaded one.

**Comment by alitoshmatov** [comment] 2023-06-29 15:25
In that case backend should send `personalDetailsList` containing all data for participants of the room. If applied would solve this issue too since `UserDetailsTooltip` can access data with `accountID` .

**Comment by alexpensify** [comment] 2023-06-29 22:23
Reassigning another `bug` team member, I'm going OOO until Monday, July 10, and will take it back then if it's not closed by then. 

Required action from the 🐛 team: Make sure the proposal process is moving forward, so we can get this one assigned out to fix.

**Comment by sobitneupane** [comment] 2023-06-30 03:35
> In that case backend should send personalDetailsList containing all data for participants of the room. If applied would solve this issue too since UserDetailsTooltip can access data with accountID .

I am not sure if `personalDetailsList` was intentionally not returned for anonymous user. I think we should add an internal engineer for more context. 

cc: @adelekennedy

**Comment by adelekennedy** [comment] 2023-07-03 17:30
added an internal engineer based on @sobitneupane question [here](https://github.com/Expensify/App/issues/21488#issuecomment-1614068442) @flodnv

**Comment by flodnv** [comment] 2023-07-03 17:41
>I am not sure if personalDetailsList was intentionally not returned for anonymous user. I think we should add an internal engineer for more context.

@marcochavezf @puneetlath @Beamanator can you please chime in on this if you know? 🙏

**Comment by puneetlath** [comment] 2023-07-03 17:56
Hmm, it's not on purpose that I'm aware of. I think it makes sense that we don't get personalDetailsList as part of the openApp/reconnectApp commands for an anonymous user. But, I would think that we'd still return the personalDetailsList as part of fetching the reportActions in the public room. 

cc @MonilBhavsar as well since has also worked on this.

**Comment by MonilBhavsar** [comment] 2023-07-04 09:17
I think it is on purpose, based on the argument passed here https://github.com/Expensify/Web-Expensify/blob/5ce1380284289ac3c7378ec2d454030593925a87/lib/ReportAPI.php#L4879

**Comment by sobitneupane** [comment] 2023-07-04 10:46
We have [this issue](https://github.com/Expensify/App/issues/21488#issuecomment-1611256615) (default avatar is shown instead of user-uploaded image) as `personalDetailsList` is  not returned for anonymous user.

**Comment by alitoshmatov** [comment] 2023-07-05 08:12
I think there are a lot of issues related to backend not sending `personalDetailsList`, and there could be more in the future.

Maybe backend should send `personalDetailsList` list of all participants when anonymous user joins a public room. It can contain minimum data like display name, since anonymous user can already see it in rooms. Avatar is also should be sent, because when anonymous user clicks on user too see their profile details, avatar also is sent there

**Comment by puneetlath** [comment] 2023-07-06 00:14
>I think it is on purpose, based on the argument passed here https://github.com/Expensify/Web-Expensify/blob/5ce1380284289ac3c7378ec2d454030593925a87/lib/ReportAPI.php#L4879

Nice find @MonilBhavsar I think we should just update that so that it does return the the public personal details to anonymous accounts.

**Comment by adelekennedy** [comment] 2023-07-10 20:26
Should this issue be put on hold because it's related to a larger change or, can this be solved externally? @puneetlath @MonilBhavsar?

**Comment by alexpensify** [comment] 2023-07-10 21:08
Alright, removing the other 🐛 team member. I'm back online and see that this is our current state: 

We need an answer to @adelekennedy's question

**Comment by flodnv** [comment] 2023-07-11 10:10
@MonilBhavsar @Beamanator can you please clarify next steps since you wrote this code recently?

**Comment by Beamanator** [comment] 2023-07-11 10:14
@adelekennedy - I believe this needs to be internal as it requires a backend fix

@MonilBhavsar - for some reason I thought you had a PR started for this, am I crazy?

**Comment by MonilBhavsar** [comment] 2023-07-11 11:13
Sorry, I have not. I'll push a quick one soon

**Comment by Beamanator** [comment] 2023-07-11 11:23
Aah i was crazy, sorry 🙃 but thanks for looking into this 🙏

**Comment by flodnv** [comment] 2023-07-12 16:51
Thanks @MonilBhavsar ! ❤️

**Comment by alexpensify** [comment] 2023-07-12 22:34
Cool, we are moving along here.

**Comment by alexpensify** [comment] 2023-07-14 18:41
Looks like @MonilBhavsar's PR was merged, can we get an update on the next steps here? Thank you!

**Comment by alexpensify** [comment] 2023-07-16 17:25
Waiting for the update here

**Comment by MonilBhavsar** [comment] 2023-07-17 08:06
PR is on staging. It will be deployed to production when we deploy today

**Comment by alexpensify** [comment] 2023-07-18 20:22
Thank you for the update @MonilBhavsar!

**Comment by MonilBhavsar** [comment] 2023-07-19 05:45
This is fixed now!

**Comment by mvtglobally** [comment] 2023-07-20 02:54
Issue not reproducible during KI retests. (First week)

**Closed** 2023-07-20 06:48 UTC
Labels: Reviewing, External, Engineering, Daily, Help Wanted, Bug

**Comment by alexpensify** [comment] 2023-07-20 21:09
I'm a bit confused here. @MonilBhavsar should we close this GH now or are we good to move forward with reviewing the proposals shared here? Thanks!

**Comment by MonilBhavsar** [comment] 2023-07-21 06:07
No, the fix was required to be internal, and issue is fixed, so need to review proposals

**Comment by alexpensify** [comment] 2023-07-22 00:34
@flodnv closed this issue. @MonilBhavsar are you suggesting that we reopen it and review the submitted proposals?
