### ISSUE TITLE
[HOLD for payment 2024-04-25] [$500] Remove `Save the World` from Global Create, and move it into Settings

### ISSUE THREAD

**Issue by zsgreenwald** [Expensify/App#36649] opened 2024-02-15 23:27 UTC
## Problem

Global create is designed to call out quick actions to use New Expensify, whether its creating an expense or starting a chat. It's prime real estate for users to understand how to use our platform. Save the World is a unique campaign to help increase adoption, but it's not usable for everyone (especially those who don't know teachers). For that reason, it causes confusion and distraction from everything else in global create.

## Solution

1.  Remove Save The World from Global Create

<img width="322" alt="image" src="https://github.com/Expensify/App/assets/11618505/929eb6e1-d17b-49e8-8a70-52720fa6fdea">

2. Move Save The World over to Account Settings (by selecting the avatar) > Under the `General` section underneath `About` and `Help`. See below:

<img width="350" alt="image" src="https://github.com/Expensify/App/assets/11618505/e045e053-33e5-4ff6-b293-79b809a9729c">

Notes:

- We'll want to confirm with design with icon we want to use
- We'll want to confirm the same RHP (right-hand pane) signup flow still works when it's selected. When someone clicks the new Save the World button, it'll take them to https://new.expensify.com/teachersunite while alsp sparning the RHP signup flow: See below for what the RHP looks like:

<img width="425" alt="image" src="https://github.com/Expensify/App/assets/11618505/35d7187c-900f-4b9f-a9f0-22e8520b86e3">

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01ac6974700a830749</li>
        <li>Upwork Job ID: 1758271776871825408</li>
        <li>Last Price Increase: 2024-02-15</li>
<li>Automatic offers: </li>
<ul>
<li>Ollyws | Reviewer | 0</li>
<li>Amarparab2024 | Contributor | 0</li>
</ul></li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @Amarparab2024</details>

**Comment by zsgreenwald** [comment] 2024-02-16 02:46
I like the idea of keeping the heart as the icon, as mentioned here:

`icon: Expensicons.Heart, `

**Comment by badeggg** [comment] 2024-02-19 09:55
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
Remove Save the World from Global Create, and move it into Settings

### What is the root cause of that problem?
new feature request

### What changes do you think we should make in order to solve the problem?
**I don't think it's complete to simply move the place of link button.** The 'save the world' page is not consistent with other account settings page.

1. (like other proposals say) Delete https://github.com/Expensify/App/blob/d28f86fbeed6f81c3d95e64653ff466cc865566c/src/pages/home/sidebar/SidebarScreen/FloatingActionButtonAndPopover.js#L188-L192
 add similar config
 ```
                 {
                    translationKey: 'sidebarScreen.saveTheWorld',
                    icon: Expensicons.Heart,
                    routeName: ROUTES.SETTINGS_SAVE_THE_WORLD,
                    action: () => {
                        interceptAnonymousUser(
                            waitForNavigate(() => {
                                Navigation.navigate(ROUTES.SETTINGS_SAVE_THE_WORLD);
                            })
                        );
                    },
                },
 ```
below code https://github.com/Expensify/App/blob/d28f86fbeed6f81c3d95e64653ff466cc865566c/src/pages/settings/InitialSettingsPage.js#L231-L235

2. Change file `src/pages/TeachersUnite/SaveTheWorldPage.tsx` to make it's layout align with other account settings items. The code change is too large to fit in this proposal, although it's not difficult, the result looks like: 
![image](https://github.com/Expensify/App/assets/10908996/080164dd-c2d3-4a6a-8eb2-33435e8ea68d)
**The icon need redesign**, I demo it with PalmTree, which is used in 'about' setting page.

3. Other small code changes to coordinate the main change. e.g. 
add 
```
        [SCREENS.SETTINGS.SAVE_THE_WORLD]: () => require('../../../pages/TeachersUnite/SaveTheWorldPage').default as React.ComponentType,
```
below https://github.com/Expensify/App/blob/d28f86fbeed6f81c3d95e64653ff466cc865566c/src/libs/Navigation/AppNavigator/ModalStackNavigators.tsx#L196


### What alternative solutions did you explore? (Optional)
N/A

**Comment by badeggg** [comment] 2024-02-19 10:07
I don't think it's complete to simply move the place of link button. The 'save the world' page is not consistent with other account settings page. Especially on web. There is no other account setting items which show page content on right modal.

the 'save the world' page:
![image](https://github.com/Expensify/App/assets/10908996/9e6007fc-433c-4c84-b6cc-ee63be019c05)
the 'about' page:
![image](https://github.com/Expensify/App/assets/10908996/44f6aa9c-e20e-4c15-bd5f-30bf26e0799c)
the 'security' page:
![image](https://github.com/Expensify/App/assets/10908996/a64002e0-a0e7-4ec7-9d5b-3deeb17e6f24)



Hence my [proposal](https://github.com/Expensify/App/issues/36649#issuecomment-1952086969).

**Comment by laurenreidexpensify** [comment] 2024-02-19 15:42
@marcochavezf bump for review https://github.com/Expensify/App/issues/36649#issuecomment-1950243280 to assign thanks

**Comment by marcochavezf** [comment] 2024-02-19 18:52
This [proposal](https://github.com/Expensify/App/issues/36649#issuecomment-1952086969) looks more complete since I agree we'd need to update the layout for the SaveTheWord page, though it was posted after C+ review. Said that, let's assign @Amarparab2024 and we can split the compensation if the PR ends up with some of @badeggg's suggested changes

**Comment by marcochavezf** [comment] 2024-02-19 19:07
Oh interesting, but then that means the `Save the world` button won't be selected because the content of another page will be shown beneath the RHP. I will apply the `Design` label to gut-check if this is desired given the new design for the settings menu

**Comment by zsgreenwald** [comment] 2024-02-19 19:13
I personally think the screenshot you linked [here](https://github.com/Expensify/App/issues/36649#issuecomment-1952108047) is good. I think we want keep the existing RHP in place no matter what

**Comment by dannymcclain** [comment] 2024-02-19 19:29
@zsgreenwald so that nav item will kinda function more like a button that triggers the RHP? I think that's probably alright, but I'd love to get the @Expensify/design team's opinions too. Only because I was kinda leaning towards something more like what's shown [here](https://github.com/Expensify/App/issues/36649#issuecomment-1952086969).

![image](https://github.com/Expensify/App/assets/7516624/cd675b78-78d2-4b71-ba7e-364cac80244e)

Clicking one of those rows would still pop open the RHP with the current "sign up" form.

**Comment by zsgreenwald** [comment] 2024-02-19 19:36
Ah, I mean I think that's the ideal scenario. I was thinking of the path to least resistance but I'm good with whatever you think is best. What you shared does look a lot better.

**Comment by shawnborton** [comment] 2024-02-19 21:14
I agree with what Danny has mocked up. That's the new standard we have for all of our settings pages, so we should 100% go with that.

**Comment by dannymcclain** [comment] 2024-02-19 21:42
[Figma is here if it's helpful!](https://www.figma.com/file/Xv3yHJooZcxRGkXbAcTZD5/%23ideal-nav-(Ideal-Nav)?type=design&node-id=3635-49785&mode=design&t=Ou4j0bkaPhIHzFSe-11)

![image](https://github.com/Expensify/App/assets/7516624/7487df17-5dff-4ef9-b591-9469bdf9ae1f)

**Comment by trjExpensify** [comment] 2024-02-20 01:38
Beauty!

**Comment by dannymcclain** [comment] 2024-02-20 14:08
@Expensify/design Quick question about this: these are the only two option rows I've ever seen that _don't_ have a left icon—is that legal? Do we have icons that make sense for these options if it is indeed illegal? Not a blocker I don't think, just something I wanted to bring to our attention so we can think on it.

**Comment by shawnborton** [comment] 2024-02-20 14:09
I think it's okay, but if we did have icons, that would be great! It's just tough to think of what appropriate icons would be for these two...

**Comment by dannymcclain** [comment] 2024-02-20 14:10
> It's just tough to think of what appropriate icons would be for these two...

That's where I'm at. I tried to think of some when I initially did the mock but was struggling so I decided to leave them out. But I would love for them to have icons lol.

**Comment by dannymcclain** [comment] 2024-02-20 14:13
> should that open in RHP

@Amarparab2024 Yup! We want both of those options to open up in the RHP (like they do today).

**Comment by badeggg** [comment] 2024-02-20 14:22
> these are the only two option rows I've ever seen that don't have a left icon
seems 'Profile' and 'Preferences' pages have no-left-icon rows too, although those rows are a little bit different ---- have subtitle

**Comment by badeggg** [comment] 2024-02-20 22:43
Question here, so @Amarparab2024 will do the PR, will I get some coin or something? Since it looks like that the solution ends with my proposal.

**Comment by dubielzyk-expensify** [comment] 2024-02-20 23:44
>That's where I'm at. I tried to think of some when I initially did the mock but was struggling so I decided to leave them out. But I would love for them to have icons lol.

Just chiming in that, I agree. I think it'll be hard to find appropriate icons. I don't mind them without icons though

**Comment by marcochavezf** [comment] 2024-02-21 17:18
> Question here, so @Amarparab2024 will do the PR, will I get some coin or something? Since it looks like that the solution ends with my proposal.

This was not a standard case, as commented [here](https://github.com/Expensify/App/issues/36649#issuecomment-1953020968), so I think it would be fair to split the compensation in this GH; what do you think @Amarparab2024 @badeggg? cc @Ollyws @laurenreidexpensify

**Comment by marcochavezf** [comment] 2024-02-21 17:40
Yeah, I understand the original description stated one expected solution, but from a UI perspective, it was not the correct one. @badeggg made a good observation about it, and that's why we asked the design team to corroborate. From my perspective, I think it's fair because your proposal was selected based on the description, but again, that doesn't mean it was the correct one for the product.

**Comment by badeggg** [comment] 2024-02-21 21:00
@marcochavezf @Amarparab2024 This is my 'first' proposal(it's the second one in fact, only because that issue was closed with no pr), so I am a little excited. It means more to me that my proposal can actually help, than just the money. Although I do think I deserve some coin.

**Comment by laurenreidexpensify** [comment] 2024-02-22 12:29
Just catching up here! Would we say that @Amarparab2024's proposal significantly builds or on re-uses elements of the first proposal that @badeggg wrote?

Also @badeggg great to have you excited to get started in the community - there's plenty of other issues out there to help out with, just search by the `help wanted` label and see if there are any others that you can help solve for us!

**Comment by marcochavezf** [comment] 2024-02-22 18:42
> Would we say that @Amarparab2024's proposal significantly builds or on re-uses elements of the first proposal that @badeggg wrote?

@Amarparab2024's proposal addresses the original request, which was to show the content of STW in the RHP. But after getting a review from the design team, the best solution is to show the content in line with the new design, which matches @badeggg's proposal.

Since this is not a standard case, I think it would be fair to give an opportunity to both contributors and split the compensation here.

**Comment by badeggg** [comment] 2024-02-22 20:28
Just saying, I think my proposal should be selected in the first place, even though it's posted after C+ has reviewed Amarparab2024's proposal. A not proper proposal be selected just because it's been reviewed, that's confusing

**Comment by badeggg** [comment] 2024-02-23 01:04
>  just search by the help wanted label and see if there are any others that you can help solve for us!

Yeah, that's what I am going to do. ;-)

**Comment by dannymcclain** [comment] 2024-02-26 14:28
>Now as we add one more option, we get the scrollbar in view, Do we need to disable this or keep it?

@Amarparab2024 I think we should leave it alone/keep it. cc @Expensify/design for viz.

>where do we find the symbol at the top left in the attached figma?

You should be able to find that illustration in the Web-Static repo: `Web-Static/images/illustrations/simple-illustration__handheart.svg`
Let me know if you have any trouble and I can upload the SVG here/to the PR.

**Comment by zsgreenwald** [comment] 2024-03-20 19:54
Hey guys, what's the latest here? Can we merge this week?

**Comment by zsgreenwald** [comment] 2024-03-25 16:03
Out of curiosity, what prevented this from hitting staging last week as you mentioned?

**Comment by shawnborton** [comment] 2024-03-29 07:40
Who are you waiting on to make the decision?

**Comment by zsgreenwald** [comment] 2024-04-01 18:38
I'm not too sure what you're referring to here. We're:

- Removing `Save the World` from Global Create
- Moving it under `General` in Settings
- When `Save the World` is selected there, we'll display the original sign-up flow as shown below:

<img width="758" alt="image" src="https://github.com/Expensify/App/assets/11618505/cc82becc-fa51-4ea7-85dd-64a98d3a3815">

**Comment by zsgreenwald** [comment] 2024-04-01 18:38
Does that answer your question?

**Comment by trjExpensify** [comment] 2024-04-02 15:54
The `https://new.expensify.com/teachersunite` route is currently linked on our [Expensify.org](
https://www.expensify.org/teachersunite) website, when you click the "Let's get started" button. We should of course update that, so it won't be a problem going forward. 

The biggest reason to keep it would be because we sent a newsletter to everyone with the existing URL, which would be broken if someone clicks it now and we deprecate the route:

<img width="707" alt="image" src="https://github.com/Expensify/App/assets/16232057/abfab524-0d18-4e39-abca-ea2de7fdbaf4">

**Comment by mountiny** [comment] 2024-04-02 16:22
@Ollyws Let's implement the `https://new.expensify.com/settings/teachersunite` route and we can add 301 reditect from `https://new.expensify.com/teachersunite` to `https://new.expensify.com/settings/teachersunite` to catch anyone coming from old links

**Comment by trjExpensify** [comment] 2024-04-02 17:29
Yep, makes sense!

**Comment by laurenreidexpensify** [comment] 2024-04-15 13:30
@marcochavezf ^^

**Comment by marcochavezf** [comment] 2024-04-15 17:12
Deploy blocker being fixed [here](https://github.com/Expensify/App/pull/40091)

**Comment by laurenreidexpensify** [comment] 2024-04-25 10:02
Clarifying something internally - https://expensify.slack.com/archives/C01SKUP7QR0/p1714039326863999

**Comment by badeggg** [comment] 2024-04-26 09:33
Thanks, fair enough ;-)

**Comment by laurenreidexpensify** [comment] 2024-04-26 10:16
- C+ @Ollyws $500 payment issued in Upwork
- Contributor: @Amarparab2024 $500 payment issued in Upwork
- Discretionary Bonus: @badeggg $100 - payment will be issued in Upwork once contract is firmed

@Ollyws can you please confirm re: regression steps thanks

**Comment by laurenreidexpensify** [comment] 2024-04-26 13:02
Yeah I agree - a regression test isn't needed thinking about it now. 

All payments have been made, no outstanding tasks here, closing out. Thanks all!

**Closed by laurenreidexpensify** 2024-04-26 13:02 UTC
Labels: External, Daily, NewFeature, Design, Awaiting Payment
