### ISSUE TITLE
[HOLD for payment 2024-06-13] [HOLD for payment 2024-06-11] [QBO] Accounting - Multi tag - Not here page opens instead of subtag settings

### ISSUE THREAD

**Issue by m-natarajan** [Expensify/App#42056] opened 2024-05-13 13:13 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___
Issue found when validating https://github.com/Expensify/App/pull/41351

**Version Number:** 1.4.73-0
**Reproducible in staging?:** Yes
**Reproducible in production?:** No
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** Applause Internal Team
**Slack conversation:**

## Action Performed:
1. Go to staging.new.expensify.com
2. Go to workspace settings.
3. Go to Accounting.
4. Connect to QBO.
5. Click Import and import Classes and Customers/Projects.
6. Go to Tags.
7. Click Customers/Projects.
8. Click on any subtag.

## Expected Result:
RHP for subtag settings will open.
## Actual Result:
Not here page opens instead of subtag settings.
## Workaround:
Unknown
## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [X] Android: Native
- [X] Android: mWeb Chrome
- [X] iOS: Native
- [X] iOS: mWeb Safari
- [X] MacOS: Chrome / Safari
- [X] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

https://github.com/Expensify/App/assets/38435837/6e2b3a70-3ff3-4e89-9d9e-fb1aee629e58

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Issue Owner</summary>Current Issue Owner: @trjExpensify</details>

**Comment by m-natarajan** [comment] 2024-05-13 13:22
@youssef-lr @greg-schroeder FYI I haven't added the External label as I wasn't 100% sure about this issue. Please take a look and add the label if you agree it's a bug and can be handled by external contributors

**Comment by m-natarajan** [comment] 2024-05-13 13:23
We think that this bug might be related to #wave-collect - Release 1

**Comment by youssef-lr** [comment] 2024-05-13 21:56
Removing blocker as QBO stuff is still behind a beta.

**Comment by youssef-lr** [comment] 2024-05-13 21:57
cc @aldo-expensify @hayata-suenaga

**Comment by hayata-suenaga** [comment] 2024-05-13 22:22
@s77rt, I think this is a regression from [this PR](https://github.com/Expensify/App/pull/41351). could you open a follow up issue?

**Comment by s77rt** [comment] 2024-05-13 22:31
@hayata-suenaga As far as I know this is a backend issue, can you check if this PR is deployed https://github.com/Expensify/Web-Expensify/pull/41894

cc @MonilBhavsar

**Comment by MonilBhavsar** [comment] 2024-05-14 05:35
The PR is merged and deployed. We should investigate root cause, and confirm if issue is caused by encoded tag name

**Comment by trjExpensify** [comment] 2024-05-14 11:33
Hm, I don't think this is an encoding issue. 

The tester looks to have used this QBO account (credentials in 1Password): `Applause QBO` & `applausetester+qbo@applause.expensifail.com`

Here's the customer record they clicked, which contains both a `+` operator and `@` symbol: `applausetester+0117mvt@applause.expensifail.com`

![Image](https://github.com/Expensify/App/assets/16232057/28eb1bd3-994c-454b-993a-a9fed9223a41)

That imports into a policy like so:

![Image](https://github.com/Expensify/App/assets/16232057/c8700ba1-7409-4ada-98b9-9664c7812876)

Displays like so in the tag list in OldDot:

![Image](https://github.com/Expensify/App/assets/16232057/8d9430cd-9c6d-4177-a47e-798022af7bf5)

On NewDot:

- any of the tag values in the `Customers/Projects` list can't be accessed, not just ones that may contains special character
- you can access the values of the first tag level of `Classes` fine:

https://github.com/Expensify/App/assets/16232057/73f5cabe-eec8-4d40-bcb8-d4513ff118c0

- if I disable the import of `Classes` and "Sync now" the connection such that `Customers/Projects` is the single level of tags on the workspace, I can access the individual tag values that are not accessible when they are in a multi tag list:

https://github.com/Expensify/App/assets/16232057/03f11a35-91aa-4779-920d-5152f478395d

Then, when I re-enable `Classes` and "Sync now" the connection such that `Classes` are now in the second level position for tags, I can't access any of the individual tag values in `Classes`:

https://github.com/Expensify/App/assets/16232057/e6615ceb-4a7a-49b4-8b5a-1db860324dcc

So I think this has something to do with accessing tag values when they are in the second level position in the tags list, @s77rt. Whichever tag list is in the second position on the tags page results in the tag values not being accessible. I.e 

- Classes (tag values accessible)
- Customers/Projects (tag values not accessible)

OR 

- Customers/Projects (tag values accessible)
- Classes (tag values not accessible)

**Comment by s77rt** [comment] 2024-05-14 11:50
Got it! Seems like a frontend bug then; Will work on this

**Comment by s77rt** [comment] 2024-05-14 11:53
Was able to reproduce with multi level tags 

https://github.com/Expensify/App/assets/16493223/f78d185d-fe65-4de9-b1a9-6773341edd52

**Comment by narefyev91** [comment] 2024-05-14 12:03
@s77rt probably this line - just pick first level of tags:
`const policyTag = useMemo(() => PolicyUtils.getTagList(policyTags, 0), [policyTags]);
`
src/pages/workspace/tags/TagSettingsPage.tsx

**Comment by s77rt** [comment] 2024-05-14 12:08
But now I'm seeing another problem, the `renamePolicyTag` API only supports changing tag names for the first tag list

**Comment by s77rt** [comment] 2024-05-14 12:48
Raised a draft PR that fixes the not found issue but still need API commands to make it functional



https://github.com/Expensify/App/assets/16493223/1c4f6a73-036d-4ba8-839a-1fc1b11a9c32

**Comment by hayata-suenaga** [comment] 2024-05-14 17:53
@s77rt, thank you for raising the front end fix

Can you confirm the APIs that need to be changed in the backend?
- `RenamePolicyTag`
- `RenamePolicyTaglist`
- `SetPolicyRequiresTag`

I think we don't need changes for the `DeletePolicyTags` as the user cannot delete or create tags when there is accounting connection and we only have multi level tags when there is an accounting connection?

**Comment by s77rt** [comment] 2024-05-14 18:52
`RenamePolicyTaglist` works already. We need:
- `RenamePolicyTag`
- `SetPolicyRequiresTag` ([issue](https://github.com/Expensify/App/issues/41374))
- `SetPolicyTagsEnabled`

**Comment by trjExpensify** [comment] 2024-05-14 20:25
>I think we don't need changes for the DeletePolicyTags as the user cannot delete or create tags when there is accounting connection and we only have multi level tags when there is an accounting connection?

That's correct on `collect` that multi-level tags will only be supported via an accounting integration, but on control workspaces we will support manual multi-level tags. That said, I think on OldDot the only way we support adding or deleting multi-level tags is via a CSV import to read/replace the lists. So I think I agree Add/Delete are out of scope for this here.

**Comment by trjExpensify** [comment] 2024-05-24 00:27
Merged into the feature branch. 👍

**Comment by trjExpensify** [comment] 2024-06-13 09:05
This was a regression issue, right? So we can just close this? Feel free to let me know if that's inaccurate and we can reopen.

**Closed by trjExpensify** 2024-06-13 09:05 UTC
Labels: Engineering, Daily, Overdue, Awaiting Payment, Bug
