### ISSUE TITLE
[HOLD for payment 2023-11-21] [DISTANCE] [$500] LOW: BUG: individuals can be selected for distance requests

### ISSUE THREAD

**Issue by neil-marcellini** [Expensify/App#30210] opened 2023-10-23 21:03 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** v1.3.89-6
**Reproducible in staging?:** yes
**Reproducible in production?:** yes
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** `@Ashim Sharma`
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1693731984757459

## Action Performed:
1. go to fab button -> request money -> distance
2. Select valid addresses in start and finish points
3.  click next
4. Now type in and select a user's mail address . eg [user1@gmail.com](mailto:user1@gmail.com)

## Expected Result:
Individuals should not appear as participant options for distance requests

## Actual Result:
Individuals do appear as participant options for distance requests. After selecting one the confirmation page shows the amount as $0.

## Workaround:
You will get an error after requesting and can make a request to a workspace instead.

## Platforms:

Which of our officially supported platforms is this issue occurring on?
All
- [x] Android: Native
- [x] Android: mWeb Chrome
- [x] iOS: Native
- [x] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos
<details>
<summary>Android: Native</summary>

</details>

<details>
<summary>Android: mWeb Chrome</summary>

</details>

<details>
<summary>iOS: Native</summary>

</details>

<details>
<summary>iOS: mWeb Safari</summary>

</details>

<details>
<summary>MacOS: Chrome / Safari</summary>

</details>

<details>
<summary>MacOS: Desktop</summary>

https://expensify.enterprise.slack.com/files/U04H96S40LC/F05RFFKS9T2/screen_recording_2023-09-03_at_2.45.37_pm.mov
</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01c5428782ec334786</li>
        <li>Upwork Job ID: 1716560993895415808</li>
        <li>Last Price Increase: 2023-10-23</li>
<li>Automatic offers: </li>
<ul>
<li>cubuspl42 | Reviewer | 27491620</li>
<li>neonbhai | Contributor | 27491621</li>
</ul></li>
    </ul>
</details>

**Comment by shahinyan11** [comment] 2023-10-24 08:50
@neil-marcellini How do we distinguish individuals from others ? With what properties ?

**Comment by Christinadobrzyn** [comment] 2023-10-24 17:37
hi @cubuspl42 could you take a peek at the proposals to see if any will work?

**Comment by Christinadobrzyn** [comment] 2023-10-27 18:48
looks like we're reviewing proposals! @cubuspl42 please feel free to add any other updates!

**Comment by cubuspl42** [comment] 2023-10-30 10:36
@dukenv0307 Thanks for clarification! Now, the proposal seems fully equivalent to the earlier one. Would you point any differences?

If there are none, this proposal should've even been submitted per the [contributing guidelines](https://github.com/Expensify/App/blob/main/contributingGuides/CONTRIBUTING.md).

**Comment by cubuspl42** [comment] 2023-10-30 10:51
@dukenv0307 Oh, I understand. While I get your perspective, I don't think that I'll treat it this way. The fix is relatively straight-forward, and each contributor could get to it independently. And separate issues are separate issues.

**Comment by cubuspl42** [comment] 2023-10-30 10:54
The fix to update the usage of the `canInviteUser` param is straight-forward. The first one to suggest it here was @neonbhai (even though @dukenv0307 suggested it earlier as a solution to a different but somewhat related issue).

In my opinion, we should go with @neonbhai

C+ reviewed 🎀 👀 🎀

**Comment by hayata-suenaga** [comment] 2023-10-30 21:14
@cubuspl42 can you check the commemt above and check if this is the dupe?

**Comment by cubuspl42** [comment] 2023-10-31 13:46
@hayata-suenaga As I can see it, the other issue is stated to be about distance requests _not working_ with individuals.

Title:  Request money **does not work with email & phone number**

> Expected Result:
>
> Since email and phone number are said to be accepted, request money reports **should be created using both**.

The issue is closed with the comment:

> This is a known limitation that we haven't built yet. I'm closing this in favor of https://github.com/Expensify/App/issues/23291 which is where we're building the functionality.

----

Our current issue is about a problem where individuals _do_ show up in the results, even when they shouldn't (as https://github.com/Expensify/App/issues/23291 is still in progress).

I cannot see how this is a dupe.

**Comment by hayata-suenaga** [comment] 2023-10-31 21:06
If after https://github.com/Expensify/App/issues/23291 is complete, we can create the distance request with the new account, I think we can close this issue.

I think this is true @neil-marcellini for confirmation

**Comment by neil-marcellini** [comment] 2023-11-01 21:18
The point of this issue is to fix the current problem on the frontend, which is that individuals can be selected for distance requests. After P2P distance requests are enabled in #23291 it will be possible, but that's a ways out, so we should fix it in th meantime.

**Comment by hayata-suenaga** [comment] 2023-11-02 16:36
okay although there is [a previous, duplicate issue](https://github.com/Expensify/App/issues/27070) exists, let's handle this here.

Assigning @neonbhai

**Comment by cubuspl42** [comment] 2023-11-03 08:11
> okay although there is [a previous, duplicate issue](https://github.com/Expensify/App/issues/27070) exists, let's handle this here.
> 
> Assigning @neonbhai

If issue A is summed up as: "X doesn't work, and it's a problem (let's make it work!)"

...while issue B is summed up as: "Acknowledging that X doesn't work (yet), behavior Y is inconsistent (let's fix it!)"

...then issue B is not a duplicate of A, no matter how many times you repeat it! 😃

Sorry for being a logic nazi here. We can move on.

**Comment by cubuspl42** [comment] 2023-11-15 10:09
- The PR that introduced the bug has been identified. Link to the PR:
    - N/A (this was more of a "UX bug"; we needed to adjust the app's behavior until #23291 is live)
- The offending PR has been commented on, pointing out the bug it caused and why, so the author and reviewers can learn from the mistake. Link to comment:
    - N/A
- A discussion in #expensify-bugs has been started about whether any other steps should be taken (e.g. updating the PR review checklist) in order to catch this type of bug sooner. Link to discussion:
    - No need for additional discussion
- Determine if we should create a regression test for this bug.
    -  No need for a regression test (this functionality will soon change as part of #23291)
- If we decide to create a regression test for the bug, please propose the regression test steps to ensure the same bug will not reach production again.
    - N/A

**Comment by Christinadobrzyn** [comment] 2023-11-18 01:26
I'm going ooo until Monday Nov 27th so going to assign another BZ teammate to monitor this until I'm back. Thanks!

Status: Waiting for payment on Nov 21

Payouts due:

Issue Reporter: $50 @Ashim Sharma
Contributor: $500 @neonbhai 
Contributor+: $500 @cubuspl42 

Eligible for 50% #urgency bonus? N

Upwork job is [here](https://www.upwork.com/jobs/~01c5428782ec334786).

**Comment by laurenreidexpensify** [comment] 2023-11-20 10:37
Payment due tomorrow

**Comment by laurenreidexpensify** [comment] 2023-11-21 10:34
Payment Summary:

- Issue Reporter: $50 @ashim Sharma - offer sent in Upwork 
- Contributor: $500 @neonbhai - paid in Upwork 
- Contributor+: $500 @cubuspl42 - paid in Upwork

**Comment by laurenreidexpensify** [comment] 2023-11-22 11:16
Payment Summary:

Issue Reporter: $50 @ashim Sharma -  paid in Upwork
Contributor: $500 @neonbhai - paid in Upwork
Contributor+: $500 @cubuspl42 - paid in Upwork

**Closed by laurenreidexpensify** 2023-11-22 11:16 UTC
Labels: External, Daily, Awaiting Payment, Bug, Distance
