### ISSUE TITLE
[HOLD for payment 2024-01-24] [$500] Upgrade react-native to 0.73+

### ISSUE THREAD

**Issue by roryabraham** [Expensify/App#31381] opened 2023-11-15 16:10 UTC
### Problem
There are two problems that significantly affect us with the current version of react-native we're using:

> TL;DR: animations done using RN’s Animated skip changing the shadow tree, which is used to calculate hit regions of views, so animating a pressable will move the view itself, but not its hitbox

which is fixed by https://github.com/facebook/react-native/pull/37836 in 0.73+

Second, there's a very painful delay on starting the android app with `npm run android` due to a bug in the react-native cli, that's fixed in 0.72.7+

### Solution
Upgrade to the latest react-native RC version ASAP.
<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~010abb6a11a875d563</li>
        <li>Upwork Job ID: 1724835564082188288</li>
        <li>Last Price Increase: 2023-11-15</li>
    </ul>
</details>

**Comment by WoLewicki** [comment] 2023-11-15 16:59
Let's do it :rocket:

**Comment by roryabraham** [comment] 2023-11-15 17:04
Marking this as external for the sake of C+ payment. @WoLewicki works for SWM and will invoice us separately

**Comment by WoLewicki** [comment] 2023-11-21 08:55
PR is here: https://github.com/Expensify/App/pull/31558 🚀

**Comment by laurenreidexpensify** [comment] 2024-01-22 12:18
@situchan Upwork job is here https://www.upwork.com/jobs/~016f56acd80d15a12e

**Comment by situchan** [comment] 2024-01-31 04:52
Is it possible to increase bounty? The PR was large, I had to review and test multiple times, and took responsible for all follow-up issues caused by RN upgrade.
cc: @roryabraham

**Comment by laurenreidexpensify** [comment] 2024-02-08 16:59
@situchan sorry I missed this - I've checked with @roryabraham and @mountiny and we agree a one off discretionary bonus makes sense in this case, because of the additional work you did. I will issue this in upwork now. 

Sorry for teh delay here, I've been offline unwell!

**Comment by laurenreidexpensify** [comment] 2024-02-08 17:04
Payment Summary:

- Contributor @WoLewicki payment N/A - expert contributor
- C+ @situchan $1500 (due to additional work - internal convo here https://expensify.slack.com/archives/C01SKUP7QR0/p1707410501008239) offer sent in Upwork

**Comment by laurenreidexpensify** [comment] 2024-02-08 17:05
@situchan pls accept offer and I will issue payment and then we can close

**Comment by situchan** [comment] 2024-02-08 17:11
Thanks so much. Offer accepted

**Comment by laurenreidexpensify** [comment] 2024-02-08 17:20
Payment issued in upwork. Closing

**Closed by laurenreidexpensify** 2024-02-08 17:20 UTC
Labels: External, Weekly, NewFeature, Awaiting Payment
