### ISSUE TITLE
[$250] Workspace - Next page is shown briefly before a loading animation is shown in manual BA flow

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#45278] opened 2024-07-11 13:29 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 9.0.6-0
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**If this was caught during regression testing, add the test name, ID and link from TestRail:** https://expensify.testrail.io/index.php?/tests/view/4710752&group_by=cases:section_id&group_id=306204&group_order=asc
**Issue reported by:** Applause - Internal Team

## Action Performed:
1. Open the app
2. Log in with a new expensifail account
3. Create a workspace
4. Navigate to Workspace settings - More features
5. Enable "Workflows"
6. Navigate to Workflows - Connect bank account
7. Enter "011401533" as Routing Number
8. Enter "1111222233331111" as Account Number
9. Tap on the "Next" button
10. Tap on the "Confirm" button
11. Enter "Alberta" as first name
12. Enter "Charleson" as last name
13. Tap on the "Next" button
14. Select any date
15. Tap on the "Next" button
16. Enter "3333" as SSN
17. Tap on the "Next" button
18. Select any suggested address
19. Tap on the "Next" button
20. Enter "Alberta Bobbeth Charleson" as Legal company name
21. Tap on the "Next" button
22. Enter "123456789" as Tax ID
23. Tap on the "Next" button

## Expected Result:
The loading animation should appear, and the next page should only be shown after it's completed

## Actual Result:
The app flickers every time a new page is opened in the manual bank account flow. The next page is shown briefly before a loading animation is shown. The issue isn't affecting the Plaid flow

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [ ] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details> 

https://github.com/Expensify/App/assets/78819774/414e49cc-00b2-4960-be4d-f9817734839e

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01959c19102edf5000</li>
        <li>Upwork Job ID: 1815178759737094306</li>
        <li>Last Price Increase: 2024-08-05</li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @neil-marcellini</details>

**Comment by lanitochka17** [comment] 2024-07-11 13:29
@VictoriaExpensify  FYI I haven't added the External label as I wasn't 100% sure about this issue. Please take a look and add the label if you agree it's a bug and can be handled by external contributors

**Comment by bernhardoj** [comment] 2024-07-11 14:22
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
The next step shown briefly and one moment loader appears every time completing a sub-step of personal info. This happens in company/business info too.

### What is the root cause of that problem?
This happens after this [PR](https://github.com/Expensify/App/pull/37680) where we save each sub-step data. Every time we save a substep, we set the loading data to true.
https://github.com/Expensify/App/blob/105dce5151053bf6c81e60e68a610dd888c5da45/src/libs/actions/BankAccounts.ts#L131-L138

The loading will then show the one moment loading indicator as shown below. The next step appears briefly because we the step is changed before the onyx data is updated.
https://github.com/Expensify/App/blob/cbd7d394fe7eeaeb551590dffda81bf51526cbe1/src/pages/ReimbursementAccount/ReimbursementAccountPage.tsx#L391-L396

The reason this only happens in Android is because `shouldReopenOnfido` is true for Android but false for other platforms. The comment above explains why.
https://github.com/Expensify/App/blob/cbd7d394fe7eeaeb551590dffda81bf51526cbe1/src/libs/shouldReopenOnfido/index.android.ts#L3

### What changes do you think we should make in order to solve the problem?

If we are saving a sub-step data, don't set the loading data to true. The loading is only needed when we are confirming the information. We can pass the `isConfirmPage` from `updatePersonalInformationForBankAccount` to `getVBBADataForOnyx`.
https://github.com/Expensify/App/blob/cbd7d394fe7eeaeb551590dffda81bf51526cbe1/src/libs/actions/BankAccounts.ts#L292-L302

Then, set the loading state to true if `isConfirmPage` is true.
https://github.com/Expensify/App/blob/cbd7d394fe7eeaeb551590dffda81bf51526cbe1/src/libs/actions/BankAccounts.ts#L131-L138

**Comment by VictoriaExpensify** [comment] 2024-07-15 10:54
Will review this in the morning

**Comment by VictoriaExpensify** [comment] 2024-07-17 06:51
@lanitochka17 I can see the issue you mentioned in your screen recording, but I am not able to recreate it - mine just briefly shows the "we're taking a look at your information" animation. It doesn't flicker the next screen.

It looks like this may be resolved - are you still able to recreate the issue? Is so, is it on iPhone or android?

**Comment by VictoriaExpensify** [comment] 2024-07-17 06:53
Asking the above in Slack - https://expensify.slack.com/archives/C9YU7BX5M/p1721199183154919

**Comment by kavimuru** [comment] 2024-07-17 12:19
Tester is still able to reproduce

https://github.com/user-attachments/assets/09a057cb-0453-40cf-8615-d0a3c20bbbfd

**Comment by VictoriaExpensify** [comment] 2024-07-22 00:15
Ohh ok you're right. I'm not sure what I did differently in the last test but I'm getting the flicker now


Uploading screen-20240722-101254.mp4…

Adding the required labels

**Comment by VictoriaExpensify** [comment] 2024-07-29 21:19
@mollfpr can you please review @bernhardoj's [proposal](https://github.com/Expensify/App/issues/45278#issuecomment-2223073815) and see what you think?

**Comment by VictoriaExpensify** [comment] 2024-07-29 22:32
Drop the OD label Melvin!

**Comment by mollfpr** [comment] 2024-07-30 05:17
Checking 👀

**Comment by mollfpr** [comment] 2024-07-30 05:30
I agree with @bernhardoj proposal but I'm not sure if the expected result should have the loading page appear or not.

@VictoriaExpensify Could you help confirm if this result looks good? The loading page only appears after the confirm page which makes sense because there's a process for the user to wait.

https://github.com/user-attachments/assets/aa9713e5-8ad6-4758-83c7-b662df9ee217

**Comment by mollfpr** [comment] 2024-08-05 17:34
Friendly bump @VictoriaExpensify https://github.com/Expensify/App/issues/45278#issuecomment-2257497053

**Comment by trjExpensify** [comment] 2024-08-08 21:32
Let's get @Expensify/design input here. I don't think we show the loading screen at each step, only the step that calls the API IIRC.

**Comment by dubielzyk-expensify** [comment] 2024-08-08 23:44
> I don't think we show the loading screen at each step, only the step that calls the API IIRC.

Agree with this. Showing a loading indicator at each step is too jarring.

**Comment by VictoriaExpensify** [comment] 2024-08-12 01:56
Hey @mollfpr - it looks like there is agreement on how this should look, so I think we're good to continue

**Comment by mollfpr** [comment] 2024-08-12 14:27
The [proposal](https://github.com/Expensify/App/issues/45278#issuecomment-2223073815) from @bernhardoj looks good to me!

🎀 👀 🎀 C+ reviewed!

**Comment by neil-marcellini** [comment] 2024-08-21 19:52
@bernhardoj could you please help describe the timeline here for this issue, any related issues and regressions? It's quite confusing. The PR was deployed to prod so the next step is just handling payment which @VictoriaExpensify will do.

**Comment by bernhardoj** [comment] 2024-08-22 01:52
@neil-marcellini there is no PR yet for this issue. https://github.com/Expensify/App/pull/47345 is a temp fix for https://github.com/Expensify/App/issues/47227. We'll revert https://github.com/Expensify/App/pull/47345 once this issue is resolved (or we can do it in 1 PR).

**Comment by VictoriaExpensify** [comment] 2024-08-26 02:19
It looks like this is just waiting for your review now @neil-marcellini (https://github.com/Expensify/App/issues/45278#issuecomment-2303520272)

**Comment by neil-marcellini** [comment] 2024-08-27 18:17
Oh ok thanks, I didn't know. Reviewing now.

**Comment by neil-marcellini** [comment] 2024-08-27 18:57
> The [proposal](https://github.com/Expensify/App/issues/45278#issuecomment-2223073815) from @bernhardoj looks good to me!
> 
> 🎀 👀 🎀 C+ reviewed!

Looks good to me too, hiring

**Comment by bernhardoj** [comment] 2024-08-28 10:17
PR is ready

cc: @mollfpr

**Comment by VictoriaExpensify** [comment] 2024-09-11 02:22
**BugZero Checklist:** The PR fixing this issue has been merged! The following checklist ([instructions](https://stackoverflow.com/c/expensify/questions/14574)) will need to be completed before the issue can be closed:

- [ ] [@bernhardoj] The PR that introduced the bug has been identified. Link to the PR:
- [ ] [@bernhardoj] The offending PR has been commented on, pointing out the bug it caused and why, so the author and reviewers can learn from the mistake. Link to comment:
- [ ] [@bernhardoj] A discussion in #expensify-bugs has been started about whether any other steps should be taken (e.g. updating the PR review checklist) in order to catch this type of bug sooner. Link to discussion:
- [ ] [@bernhardoj] Determine if we should create a regression test for this bug.
- [ ] [@bernhardoj] If we decide to create a regression test for the bug, please propose the [regression test](https://github.com/Expensify/App/blob/main/contributingGuides/REGRESSION_TEST_BEST_PRACTICES.md) steps to ensure the same bug will not reach production again.
- [ ] [@VictoriaExpensify Link the GH issue for creating/updating the regression test once above steps have been agreed upon:

**Comment by VictoriaExpensify** [comment] 2024-09-11 02:33
Payment summary:
Contributor: @bernhardoj owed $250 via NewDot

@mollfpr I'll organise your payment once the checklist is complete

**Comment by bernhardoj** [comment] 2024-09-11 05:48
Requested in ND.

**Comment by JmillsExpensify** [comment] 2024-09-11 12:09
$250 approved for @bernhardoj

**Comment by mollfpr** [comment] 2024-09-11 14:19
> [@mollfpr] The PR that introduced the bug has been identified. Link to the PR:
 [@mollfpr] The offending PR has been commented on, pointing out the bug it caused and why, so the author and reviewers can learn from the mistake. Link to comment:

https://github.com/Expensify/App/pull/37680

> [@mollfpr] A discussion in #expensify-bugs has been started about whether any other steps should be taken (e.g. updating the PR review checklist) in order to catch this type of bug sooner. Link to discussion:

The regression step should be enough.

> [@mollfpr] Determine if we should create a regression test for this bug.
 [@mollfpr] If we decide to create a regression test for the bug, please propose the [regression test](https://github.com/Expensify/App/blob/main/contributingGuides/REGRESSION_TEST_BEST_PRACTICES.md) steps to ensure the same bug will not reach production again.

1. Open workspace workflow page
2. Press Connect bank account
3. Complete the first 4 steps of the BA
4. **_Verify_** that each time you save a sub-step, no loading animation is shown.
5. **_Verify_** that each time you confirm in a confirmation step, a loading animation is shown (except personal info where only loading is shown on the button)
6. 👍 or 👎

**Comment by garrettmknight** [comment] 2024-09-11 19:24
$250 approved for @mollfpr

**Comment by mollfpr** [comment] 2024-09-18 08:49
@VictoriaExpensify Could you give the payment summary? Thank you!

**Comment by VictoriaExpensify** [comment] 2024-09-18 09:57
Thanks @mollfpr !

**Comment by VictoriaExpensify** [comment] 2024-09-18 10:03
Payment summary:
**Contributor+:** @mollfpr owed $250 via NewDot

**Closed by VictoriaExpensify** 2024-09-18 10:03 UTC
Labels: Reviewing, External, Weekly, Bug
