### ISSUE TITLE
[$1000] Web - Sending message in two open chat page in different tabs is not reflected on the other tabs.

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#27034] opened 2023-09-08 15:36 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Open the website
2. Open any chat from LHN
3. Hover the message and click the copy link
4. Paste the link in the new tab
5. Send a message
6. Observe the result from the other tab

## Expected Result:
The message should be reflected in the tabs

## Actual Result:
The message is not reflected in the tabs

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [ ] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 1.3.66.3
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/93399543/382979e9-e650-4867-8ec7-18e44f720239

https://github.com/Expensify/App/assets/93399543/9bfa6eb8-a4fe-4467-abc5-a78b0c0f5582

**Expensify/Expensify Issue URL:**
**Issue reported by:** @misgana96
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1693831294391699

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01c1fd00c75672684e</li>
        <li>Upwork Job ID: 1700171246406656000</li>
        <li>Last Price Increase: 2023-10-04</li>
    </ul>
</details>

**Comment by garrettmknight** [comment] 2023-09-11 08:41
Wow, Melv. Really going nuts on this one. Bug is open and we're waiting on proposals.

**Comment by rakshitjain13** [comment] 2023-09-12 21:00
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
The message is not reflected in the tabs

### What is the root cause of that problem?
In ````SequentialQueue.js```` in this file, the ````flush```` method checks that only the leader in tabs of a single browser can make requests. 
https://github.com/Expensify/App/blob/3fe7ab1c7d860f40eeb9a52b911f8d7bc4781dd5/src/libs/Network/SequentialQueue.js#L104-L108

It is clearly return in ````src/libs/ActiveClientManager/index.js```` that 
https://github.com/Expensify/App/blob/3fe7ab1c7d860f40eeb9a52b911f8d7bc4781dd5/src/libs/ActiveClientManager/index.js#L1-L5

### What changes do you think we should make in order to solve the problem?
So now if a tab which is not a leader makes a request we will do the same thing. i.e. Ensure persistedRequests are read from storage which is shown below.

https://github.com/Expensify/App/blob/3fe7ab1c7d860f40eeb9a52b911f8d7bc4781dd5/src/libs/Network/SequentialQueue.js#L122-L127


### What alternative solutions did you explore? (Optional)
NA

**Comment by garrettmknight** [comment] 2023-09-13 09:21
@Ollyws when you get a chance, what do you think of that proposal?

**Comment by rakshitjain13** [comment] 2023-09-14 16:43
@Ollyws @garrettmknight Any thoughts about the above proposal

**Comment by misgana96** [comment] 2023-09-19 16:26
@Ollyws I can reproduce it in the latest main
[Screencast from 19-09-2023  7:20:04 ከሰዓት.webm](https://github.com/Expensify/App/assets/48551032/e1c621b6-0766-40dd-add5-8494a8c30f9c)

**Comment by rakshitjain13** [comment] 2023-09-19 16:59
@Ollyws Message will be synced again when focus on tab again comes like if you switch between tabs or application

**Comment by rakshitjain13** [comment] 2023-09-19 17:50
> @misgana96 Hmm on mine sometimes there is a slight delay but ultimately the messages are all updated eventually, maybe I'm missing something?:
> 
>  Screen.Recording.2023-09-19.at.17.45.52.mov 
> VIDEO

@Ollyws In this video, you are seeing messages synced because you send messages from the activeLeader of tabs. You can refer below video.

https://github.com/Expensify/App/assets/54314936/ce41a56b-9b02-4494-8415-5f680c721f8c

**Comment by garrettmknight** [comment] 2023-09-22 10:41
@Ollyws can you give this one another look?

**Comment by garrettmknight** [comment] 2023-09-25 10:55
Bumped in slack

**Comment by rakshitjain13** [comment] 2023-09-25 20:20
@Ollyws I just removed the [activeClientManger check block](https://github.com/Expensify/App/blob/38030f88f885b13f9ca89fcaea31492061f602cf/src/libs/Network/SequentialQueue.js#L106-L108) . I cannot see any duplicate requests as only one client is pushing to the queue not all clients. You can also take a look at the below video. Let me know if I am missing something 

https://github.com/Expensify/App/assets/54314936/4473d64e-be4d-48fa-b99f-047e6c927bf9

**Comment by mvtglobally** [comment] 2023-09-28 03:19
Issue not reproducible during KI retests. (First week)

**Comment by garrettmknight** [comment] 2023-10-04 19:48
Upping the price to see if we can give any other proposals.

**Comment by mvtglobally** [comment] 2023-10-05 03:06
Issue not reproducible during KI retests. (Second week)

**Comment by garrettmknight** [comment] 2023-10-09 18:12
@Ollyws can you double check this is still happening in dev before we find an internal assignee?

**Comment by mvtglobally** [comment] 2023-10-12 03:49
Issue not reproducible during KI retests. (Third week) Lets close it?

**Comment by garrettmknight** [comment] 2023-10-12 10:34
Awesome, closing!

**Closed by garrettmknight** 2023-10-12 10:34 UTC
Labels: Engineering, Daily, Internal, Overdue, Bug
