### ISSUE TITLE
[HOLD for payment 2024-04-25] Profile - Personal details not open on off line mode

### ISSUE THREAD

**Issue by kavimuru** [Expensify/App#23873] opened 2023-07-29 23:41 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. https://staging.new.expensify.com/
2. Log in with a HIGH TRAFFIC account. 
3. Click on the profile icon
4. After login in with a High Traffic account - enable Airplane mode to simulate a connection loss
5. Click on Personal Details
## Expected Result:
Personal details is open and options are visible
## Actual Result:
Personal details not open

## Workaround:
Can the user still use Expensify without this being fixed? Have you informed them of the workaround?

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [x] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:**  1.3.47-2
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/43996225/ccab7673-7f42-4dfa-b392-3c1ef488c5f4

**Expensify/Expensify Issue URL:**
**Issue reported by:** applause internal team
**Slack conversation:**

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~015f3b23a3e3d5db40</li>
        <li>Upwork Job ID: 1686070604511633408</li>
        <li>Last Price Increase: 2023-07-31</li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @grgia</details>

**Comment by trjExpensify** [comment] 2023-07-31 11:54
Oh hm, interesting! @zanyrenney @twisterdotcom @Beamanator - what was the implementation of this from the account settings doc? 

If the `personal details` pages require being online, we should be using the full page blocking form ([offline pattern D](https://github.com/Expensify/App/blob/main/contributingGuides/OFFLINE_UX.md#d---full-page-blocking-ui-pattern)) in that case?

**Comment by trjExpensify** [comment] 2023-07-31 14:28
That's helpful to know. I'm keen to hear from the team on the expected behaviour of accessing the personal details pages when offline.

**Comment by twisterdotcom** [comment] 2023-07-31 16:29
No these should be available offline. This must be a regression.

**Comment by trjExpensify** [comment] 2023-07-31 17:45
Cool, moving on! :)

**Comment by michaelraoof** [comment] 2023-08-01 02:00
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
##### if you click at Personal details for the first time, it keeps uploading 
### What is the root cause of that problem?
##### When you sign in, your personal details are neither retrieved from the backend nor stored in the local storage. Therefore, if you click on 'personal details' for the first time, the app will need to obtain your details and set them in the local storage.
### What changes do you think we should make in order to solve the problem?
##### I think we should load the private personal details from the back end and set it inside the local storage after you sign in

[](https://github.com/Expensify/App/blob/eb020063789091eb2e3086b5b54af3ead8436645/src/libs/actions/Welcome.js#L98-L98)

and we should add this code in Welcome.js file in order to load the personal details in the first time after you sign in
`
let privatePersonalDetails;
Onyx.connect({
  key: ONYXKEYS.PRIVATE_PERSONAL_DETAILS,
  callback: (val) => (privatePersonalDetails = val),
});
`

### What alternative solutions did you explore? (Optional)

**Reminder:** Please use plain English, be brief and avoid jargon. Feel free to use images, charts or pseudo-code if necessary. Do not post large multi-line diffs or write walls of text. Do not create PRs unless you have been hired for this job.

**Comment by trjExpensify** [comment] 2023-08-01 11:49
Ah, so let's take this internal then!

**Comment by trjExpensify** [comment] 2023-08-14 10:03
Can we pop this back on `daily` now?

**Comment by trjExpensify** [comment] 2023-08-22 13:31
Going to put this back on `daily`, we have a week to go before it breaks WAQ.

**Comment by grgia** [comment] 2023-08-28 09:12
Am I correct in understanding:

**Problem:** 
When a user logs in and goes offline BEFORE opening the personal details page, their private personal details are not retrieved and the private personal details page loads infinitely?

So the solution that has been proposed to go with (internally) is:

return `privatePersonalDetails` of current user in `openApp` API call.

cc @Beamanator @puneetlath could I get a check on this and your insight on what our methodology is for storing private personal details?

**Comment by puneetlath** [comment] 2023-08-28 15:56
I don't think this has anything to do with the securing logins project that we did. That was all about how we deal with _ther people's_ personal details. Which in this case it seems like we just aren't returning the users own private personal details in openApp, which we definitely can start doing. Do we return all other profile/settings stuff in openApp?

**Comment by trjExpensify** [comment] 2023-08-30 13:22
Yeah, I think this is more about the offline approach in the [account settings doc implementation](https://docs.google.com/document/d/17akqrbC-w8FqEoDLvcLmrX6iw4uaVrT_xlwAl-IhEzE/edit#heading=h.j9j08bxknsqy) when these new API commands were introduced, right @Beamanator?

**Comment by Beamanator** [comment] 2023-08-30 15:32
Oof sorry for not responding earlier!!

Yeah in the Account Settings doc we decided it wasn't necessary to pull the user's private personal details in OpenApp - though I can't recall the exact reason why 😬 

@zanyrenney @twisterdotcom @cristipaval (team awesome) - do y'all think we should start pulling private personal details in OpenApp as well just so we at least have that data initially, even if it's slightly out of date (assuming the case you signed in at some point and have been offline for some time, when you finally navigate back to your "personal details" page)

**Comment by trjExpensify** [comment] 2023-09-04 09:41
>Yeah in the Account Settings doc we decided it wasn't necessary to pull the user's private personal details in OpenApp - though I can't recall the exact reason why 😬

Ah, it would be great if a decision like this was documented somewhere in like alt solutions to refer back to. I couldn't find it when taking a quick search through the doc just now. 

>@zanyrenney @twisterdotcom @cristipaval (team awesome) - do y'all think we should start pulling private personal details in OpenApp as well just so we at least have that data initially, even if it's slightly out of date (assuming the case you signed in at some point and have been offline for some time, when you finally navigate back to your "personal details" page)

@zanyrenney @cristipaval, do you guys agree or recall a reason we didn't do this initially? If there isn't one, let's do it. Of course, let's make sure it doesn't slow down the openApp call considerably or something like that as we proceed with a PR.

**Comment by trjExpensify** [comment] 2023-09-11 11:29
@grgia, I think we have enough to prepare a PR to fix this. :)

**Comment by zanyrenney** [comment] 2023-09-11 14:41
@trjExpensify hmm I don't remember there being any reason we elected to not load personal details offline. I've searched around in Slack too and not generating heaps there. I think we can change this and do it, I nothing is coming to mind why not to do it.

**Comment by cristipaval** [comment] 2023-09-11 19:45
I don't remember either about a decision made about this. I joined the Account Settings team when the detailed section of the doc was already approved and helped mainly with some implementation of the push to page design in the Account Settings pages.

**Comment by cristipaval** [comment] 2023-09-11 20:37
@Beamanator why `OpenApp` command and not add them in the response of a successful login?

**Comment by Beamanator** [comment] 2023-09-12 05:03
> @Beamanator why add the private personal details in the OpenApp command and not add them in the response of a successful login?

No preference here, but what's the advantage of that vs the OpenApp?

**Comment by cristipaval** [comment] 2023-09-12 20:55
> > @Beamanator why add the private personal details in the OpenApp command and not add them in the response of a successful login?
> 
> No preference here, but what's the advantage of that vs the OpenApp?

No preference either, I was just wondering if we have a standard process for deciding the best command to use. I would say it's more natural to get the account information when I sign into the account 🤔

**Comment by Beamanator** [comment] 2023-09-13 01:31
Aah ok fair! I could see that point, but maybe someone (the assigned person here 😉 ) can start that convo somewhere to confirm :D

**Comment by grgia** [comment] 2023-09-14 10:25
I haven't had the bandwidth to look at this this week

**Comment by grgia** [comment] 2023-09-14 10:27
I'm making this a weekly because the bug doesn't affect any major user flows

**Comment by grgia** [comment] 2023-09-25 10:02
Haven't worked on this

**Comment by trjExpensify** [comment] 2023-11-06 11:32
Interestingly, commented on another issue today that might have the same root cause as this one. @grgia don't suppose you're going to be able to look into this again soon?

**Comment by trjExpensify** [comment] 2023-12-11 10:34
Sounds good!

**Comment by grgia** [comment] 2024-01-09 20:34
Revisiting this convo, I think we should add to OpenApp. We don't need ay personal details during the login and I think adding them to the signin commad breaks 1:1:1

**Comment by grgia** [comment] 2024-01-09 20:34
Moving to weekly, but I have wave work to prioritize before I can get to this

**Comment by trjExpensify** [comment] 2024-01-26 16:53
Commented here on where to put this: https://expensify.slack.com/archives/C01GTK53T8Q/p1706285619541089?thread_ts=1706281735.244719&cid=C01GTK53T8Q

**Comment by grgia** [comment] 2024-01-27 00:02
I think we just need to add these to openApp. cc @marcaaron can you think of any reasons not to?

**Comment by marcaaron** [comment] 2024-01-27 01:48
Can't think of anything. I would also vote to add them to `OpenApp`

Let's do this in Auth [here](https://github.com/Expensify/Auth/blob/main/auth/command/OpenApp.cpp).
And only return the stuff we are returning [here](https://github.com/Expensify/Web-Expensify/blob/0860c97326de84d4c64c70cace73d1251dc06d6a/lib/PersonalDetailsAPI.php#L611-L638).

**Comment by grgia** [comment] 2024-02-08 21:05
Sweet, I'll make this a daily so I can open a PR this week

**Comment by grgia** [comment] 2024-02-12 22:30
working on this today

**Comment by grgia** [comment] 2024-02-14 20:43
BE in review, will work on the App update next as those are reviewed

**Comment by grgia** [comment] 2024-02-21 01:31
Auth was merged, working on App update

**Comment by trjExpensify** [comment] 2024-02-27 12:32
How you getting on, Georgia?

**Comment by trjExpensify** [comment] 2024-04-27 11:35
👋 Checklist time @thesahindia!

**Comment by grgia** [comment] 2024-04-30 11:29
PR was reviewed by @s77rt @trjExpensify

**Comment by grgia** [comment] 2024-04-30 11:30
Handled here though https://github.com/Expensify/App/issues/36647

**Comment by grgia** [comment] 2024-04-30 11:30
Closing this out

**Closed by grgia** 2024-04-30 11:30 UTC
Labels: Engineering, Daily, Internal, Awaiting Payment, Bug
