### ISSUE TITLE
[HOLD for Payment 5/30][$250] Allow creating a Group Chat with a single member

### ISSUE THREAD

**Issue by marcaaron** [Expensify/App#40258] opened 2024-04-15 22:22 UTC
Coming from [this thread](https://expensify.slack.com/archives/C05RECHFBEW/p1712957481605129) we have decided that there is no real reason why a user should not be able to start a Group Chat with only themselves (h/t @shawnborton who noticed that we cannot do this).

**Deliverable:**

- Investigate the front end code and determine what changes need to be made to allow a user to take the following actions:

1. Add several people to a Group Chat via the Global Create menu 
2. Advance to the "Confim" page with the "Start group" button.
3. Remove each member
4. "Start group" button should allowing creating a group with only yourself.

**Current behavior we need to improve:**

![Image](https://github.com/Expensify/App/assets/32969087/903d3323-461c-46cf-a79a-9ce837c34f54)

- Verify if it appears that some backend changes need to be made (this is possible, I have not yet looked)
<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~016c3003963dd24c78</li>
        <li>Upwork Job ID: 1779998805262094336</li>
        <li>Last Price Increase: 2024-04-15</li>
<li>Automatic offers: </li>
<ul>
<li>abzokhattab | Contributor | 0</li>
</ul></li>
    </ul>
</details>

**Comment by nkdengineer** [comment] 2024-04-16 04:00
## Proposal

### Please re-state the problem that we are trying to solve in this issue.

Enable create group chat with only one user.

### What is the root cause of that problem?

This is a new feature request.
### What changes do you think we should make in order to solve the problem?
1. Since the current user option will always selected, we can remove the condition here and always show the confirm button
```
onConfirm={createGroup} 
```
https://github.com/Expensify/App/blob/90412ec0c38cc1ccd0a1198cf1f4712474667906/src/pages/NewChatConfirmPage.tsx#L157

```
showConfirmButton
```
https://github.com/Expensify/App/blob/90412ec0c38cc1ccd0a1198cf1f4712474667906/src/pages/NewChatConfirmPage.tsx#L155

2. We should add an extra param in `navigateToAndOpenReport` like `isGroupChat` with default value is `false`, use this instead of [here](https://github.com/Expensify/App/blob/90412ec0c38cc1ccd0a1198cf1f4712474667906/src/libs/actions/Report.ts#L836) or we can update the `isGroupChat` condition by checking it includes the current user or not because for selfDM we always navigate to this report.
We should not use `> 0` condition because it maybe a DM


And then pass `isGroupChat` as `true` here

```
Report.navigateToAndOpenReport(logins, true, newGroupDraft.reportName ?? '', newGroupDraft.avatarUri ?? '', fileRef.current, optimisticReportID.current, true);

```
https://github.com/Expensify/App/blob/90412ec0c38cc1ccd0a1198cf1f4712474667906/src/pages/NewChatConfirmPage.tsx#L104

> Verify if it appears that some backend changes need to be made (this is possible, I have not yet looked)

I've tested and we don't need backend changes here.

3. Since we allow create group chat with single use now, we should separate the `Create Chat` and `Next` button. So we can go to the confirm group page without select any option

```
const footerContent = useMemo(() => {
    /**
     * Creates a new group chat with all the selected options and the current user,
     * or navigates to the existing chat if one with those participants already exists.
     */
    const createGroup = () => {
        if (!personalData || !personalData.login || !personalData.accountID) {
            return;
        }
        const selectedParticipants: SelectedParticipant[] = selectedOptions.map((option: OptionData) => ({login: option.login ?? '', accountID: option.accountID ?? -1}));
        const logins = [...selectedParticipants, {login: personalData.login, accountID: personalData.accountID}];
        Report.setGroupDraft({participants: logins});
        Navigation.navigate(ROUTES.NEW_CHAT_CONFIRM);
    };

    return (
        <>
            <ReferralProgramCTA
                    referralContentType={CONST.REFERRAL_PROGRAM.CONTENT_TYPES.START_CHAT}
                    style={styles.mb5}
                />

                {selectedOptions.length === 1 && (
                    <Button
                        success
                        text={translate('newChatPage.createChat')}
                        onPress={createChat}
                        pressOnEnter
                        style={styles.mb5}
                    />
                )}
                <Button
                    success
                    text={translate('common.next')}
                    onPress={createGroup}
                    pressOnEnter
                />
        </>
    );
}, [createChat, personalData, selectedOptions, styles.mb5, translate]);
```
https://github.com/Expensify/App/blob/90412ec0c38cc1ccd0a1198cf1f4712474667906/src/pages/NewChatPage.tsx#L247
### What alternative solutions did you explore? (Optional)
NA

**Comment by ahmedGaber93** [comment] 2024-04-16 08:47
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
Allow creating a Group Chat with a single member.
### What is the root cause of that problem?
new feature
### What changes do you think we should make in order to solve the problem?
For that we need 3 steps (important step 3).
1. edit confirm button visibility [here](https://github.com/Expensify/App/blob/eef5fde8536c78726dcbcf1632839b803b7d8526/src/pages/NewChatConfirmPage.tsx#L155)
```javascript
// showConfirmButton={selectedOptions.length > 1}
showConfirmButton={selectedOptions.length > 0}
```

2. edit confirm button `onConfirm` [here](https://github.com/Expensify/App/blob/eef5fde8536c78726dcbcf1632839b803b7d8526/src/pages/NewChatConfirmPage.tsx#L157)
```javascript
// onConfirm={selectedOptions.length > 1 ? createGroup : undefined}
onConfirm={selectedOptions.length > 0 ? createGroup : undefined}
```


3. as we now allow creating a group chat with a single member, so we need to edit `navigateToAndOpenReport`  [here](https://github.com/Expensify/App/blob/eef5fde8536c78726dcbcf1632839b803b7d8526/src/libs/actions/Report.ts#L836) to differentiates between DM 1:1 and group chat with a single member, this function now is used in many places, so we need to confirm it will work fine in those cases (exist/not exist) for DM 1:1, group. 

The only different now between DM 1:1 and group is `participantAccountIDs.length > 1`, and if we edit it to `participantAccountIDs.length > 0` it will return true in both DM 1:1 and group with a single member, and if we pass `isGroupChat` as a parameter it will be hard code as we need to pass it in all cases (exist/not exist) for DM 1:1 and group.
So my fix for this is creating a new variable `isSignalMemberGroupChat` which differentiates between 1:1 DM and group with a single member, and the final `isGroupChat` definition will be  `isSignalMemberGroupChat` or `participantAccountIDs.length > 1`
 
```javascript
// remove old isGroupChat
//  const isGroupChat = participantAccountIDs.length > 1;

// we need to handle `isSignalMemberGroupChat` in (exist/not exist)
// for not exist group >>> participant === 1 and isDraftGroup called by cretae group(explained below).
// for exist group >>> participant === 1 and chatType is group.

// isDraftGroup definition
// as we pass `optimisticReportID` only when we create a new group, so if it not undeifined that mean this is draft group.
// we can also create new param isDraftGroup and pass it true when creating the group (only in this place)
const isDraftGroup = !!optimisticReportID;

const isSignalMemberGroupChat = participantAccountIDs.length === 1 &&
  (isDraftGroup || ReportUtils.getChatByParticipants(participantAccountIDs)?.chatType === CONST.REPORT.CHAT_TYPE.GROUP);

// the new `isGroupChat` will be
const isGroupChat = isSignalMemberGroupChat || participantAccountIDs.length > 1;

```
We don't need backend changes. 
### What alternative solutions did you explore? (Optional)

**Comment by sobitneupane** [comment] 2024-04-16 12:01
Thanks for the proposal everyone.

[Proposal](https://github.com/Expensify/App/issues/40258#issuecomment-2058184879) from @nkdengineer and [proposal](https://github.com/Expensify/App/issues/40258#issuecomment-2058566788) from @ahmedGaber93 both solves the issue.


In @ahmedGaber93's proposal `ReportUtils.getChatByParticipants(participantAccountIDs)?.chatType === CONST.REPORT.CHAT_TYPE.GROUP);` will probably always return false as we skip group chat while looking for the report in `getChatByParticipants` function.

As `navigateToAndOpenReport ` is used only in case of new group chat or general chats(existing and new), I believe we will be okay going with the @nkdengineer's proposal. I don't think we would want to go with the 3rd step though.

@marcaaron Do we want to show  two buttons for group chat and normal chat so that user can create group chat alone or even with one other user as suggested in 3rd step in this [proposal](https://github.com/Expensify/App/issues/40258#issuecomment-2058184879)?

**Comment by marcaaron** [comment] 2024-04-16 19:15
>Should we include two buttons—one for group chat and one for normal chat—allowing users to create group chats either alone or with just one other user

No, we should make the change described in the issue. That would be a decision for the Design team to consider, not us.

**Comment by sobitneupane** [comment] 2024-04-17 09:51
Thanks for the proposal everyone.

[Update Proposal](https://github.com/Expensify/App/issues/40258#issuecomment-2057915930) from @abzokhattab looks good.

🎀 👀 🎀 C+ reviewed

**Comment by nkdengineer** [comment] 2024-04-17 10:16
> No, we should make the change described in the issue. That would be a decision for the Design team to consider, not us.

@marcaaron I think we should discuss about this because if we want to create a group chat with only one user, we need to select another to allow go to next and then de-select this one. I have another ideal for this action that we can do the dropdown button that will have two option one is create a group chat one is create a single chat. 


https://github.com/Expensify/App/assets/161821005/05215872-1828-4c1c-8718-7c681192927b




What do you think about it? And should we discuss with design team about this here?

**Comment by shawnborton** [comment] 2024-04-17 12:05
I don't think we want to do anything like that yet. If anything, we'll plan to pull out "Start a group chat" as it's own item or own tab, and then from there it makes sense to start the group without selecting anyone. But as it currently stands, I don't think we want to change the start a chat functionality like that. Curious what others think though.

**Comment by sobitneupane** [comment] 2024-04-22 08:44
@marcaaron Can you please check [this comment ](https://github.com/Expensify/App/issues/40258#issuecomment-2060862212)whenever you are available. Thanks.

**Comment by sobitneupane** [comment] 2024-04-27 03:15
@abzokhattab Any update? When can we expect PR?

**Comment by marcaaron** [comment] 2024-04-29 23:31
@abzokhattab Can we get please get an update on this one?

**Comment by abzokhattab** [comment] 2024-04-30 06:04
Apologies for the delay.. was pretty busy the last few days. 
working on it now.

**Comment by abzokhattab** [comment] 2024-05-01 10:28
the PR is ready [here](https://github.com/Expensify/App/pull/41315)

**Comment by Christinadobrzyn** [comment] 2024-05-03 10:02
monitoring https://github.com/Expensify/App/pull/41315

**Comment by Christinadobrzyn** [comment] 2024-05-08 08:56
monitoring https://github.com/Expensify/App/pull/41315

**Comment by Christinadobrzyn** [comment] 2024-05-14 08:44
monitoring https://github.com/Expensify/App/pull/41315

**Comment by Christinadobrzyn** [comment] 2024-05-21 07:45
monitoring https://github.com/Expensify/App/pull/41315

**Comment by Christinadobrzyn** [comment] 2024-05-28 07:44
[PR](https://github.com/Expensify/App/pull/41315) deployed to production 5 days ago so payment is coming up. 

Payouts due:

- [ ] Contributor: $250 @abzokhattab (offer here https://www.upwork.com/nx/wm/offer/101981803)
- [ ] Contributor+: $250 @sobitneupane 

Upwork job is [here](https://www.upwork.com/jobs/~016c3003963dd24c78).

@sobitneupane are you paid in NewDot? 

@sobitneupane or @abzokhattab I know this is a new feature but do we need a regression test for this?

**Comment by sobitneupane** [comment] 2024-05-28 10:26
> @sobitneupane are you paid in NewDot?

@Christinadobrzyn Yup. I will request payment in NewDot.

**Comment by sobitneupane** [comment] 2024-05-28 10:28
**Regression Test Proposal**

1. Add several people to a Group Chat via the Global Create menu
2. Advance to the "Confirm" page with the "Start group" button.
3. Remove all members
4. Verify that the "Start group" button still shows up allowing you to create a group with only yourself.
5. Click on "Start group" button and verify that the group is created properly without any errors.

DO we agree 👍 or 👎

**Comment by marcaaron** [comment] 2024-05-28 21:52
LGTM

**Comment by Christinadobrzyn** [comment] 2024-05-29 09:06
Regression test - https://github.com/Expensify/Expensify/issues/400167

Payment planned for tomorrow

**Comment by Christinadobrzyn** [comment] 2024-05-30 04:49
Ready for payment - no regression tests reported. 

payment summary here - https://github.com/Expensify/App/issues/40258#issuecomment-2134553063

Closing this out as complete but let me know if we need to reopen for anything!

**Closed by Christinadobrzyn** 2024-05-30 04:49 UTC
Labels: Reviewing, External, Daily, NewFeature

**Comment by JmillsExpensify** [comment] 2024-06-22 16:50
$250 approved for @sobitneupane
