### ISSUE TITLE
[HOLD for payment 2023-10-09] [$500] Web - App displays waypoint address page briefly on click on 'Go back to Home page'

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#27106] opened 2023-09-10 13:45 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Open the app
2. Open request money
3. Click on distance
4. Click on Start/Finish
5. Copy the URL
6. Modify number in the end of URL and send it to any chat (this is to trigger 'Hmm its not here' page)
7. Click on link, it should display 'Hmm its not here' page
8. Click on 'Go back to Home page' and observe that it displays waypoint address page in transition

## Expected Result:
App should not display any other page on click on 'Go back to Home page'

## Actual Result:
Waypoint page is briefly displayed when clicking on 'Go back to Home page'

## Workaround:
Can the user still use Expensify without this being fixed? Have you informed them of the workaround?

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [x] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 1.3.66.3
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/93399543/c951721c-0844-4a82-b069-ca1a9c4da75c

https://github.com/Expensify/App/assets/93399543/11757bad-853c-45d7-8f15-b7490af073b9

**Expensify/Expensify Issue URL:**
**Issue reported by:** @dhanashree-sawant
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1693910663601209

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01820733228279d2b2</li>
        <li>Upwork Job ID: 1700868221786181632</li>
        <li>Last Price Increase: 2023-09-10</li>
<li>Automatic offers: </li>
<ul>
<li>ZhenjaHorbach | Contributor | 26787091</li>
<li>dhanashree-sawant | Reporter | 26787093</li>
</ul></li>
    </ul>
</details>

**Comment by ahmedGaber93** [comment] 2023-09-10 13:45
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
App displays waypoint page in 'Go back to home page' transition
### What is the root cause of that problem?
https://github.com/Expensify/App/blob/5c138163049ef0f036d46c4359c51fcde673066f/src/pages/iou/WaypointEditor.js#L166

When clicking going back, the `isFocused` in `shouldShow` condition will be false, then `shouldShow` will be false and the content inside it will appear.


The `isFocused` is added here to fix an issue appeared unexpectedly and not related to the PR here https://github.com/Expensify/App/pull/25977#issuecomment-1699909081 
> "when deleting a waypoint, the Not Found screen became visible for a few milliseconds during the animation" 

And it fixed by `isFocused`, and it fixed correctly, but the fix not cover this case.

### What changes do you think we should make in order to solve the problem?
We need to remove `isFocused` from `shouldShow` condition and it will work fine.

We will replace `isFocused` with a new fix for:
> "when deleting a waypoint, the Not Found screen became visible for a few milliseconds during the animation" 

When start deleting, we will save state and use it in `shouldShow` to prevent showing Not found page.
```javascript
// define state
const [didDelete, setDidDelete] = useState(false);

// set it here
const deleteStopAndHideModal = () => {
    setDidDelete(true);
    ...
};
//and here
const onSubmit = (values) => {
  ...
  // Allows letting you set a waypoint to an empty value
  if (waypointValue === '') {
      setDidDelete(true);
      ...
  }
}

// use it here
<FullPageNotFoundView 
  shouldShow={(Number.isNaN(parsedWaypointIndex) || parsedWaypointIndex < 0 || parsedWaypointIndex > waypointCount - 1) && !didDelete}>

```

Now if this part `parsedWaypointIndex > waypointCount - 1` return true, the new part `&& !didDelete` will prevent it

### What alternative solutions did you explore? (Optional)
N/A

**Comment by kbecciv** [comment] 2023-09-10 13:46
Proposal by: @dhanashree-sawant
Slack conversation: https://expensify.slack.com/archives/C049HHMV9SM/p1693910663601209

## Proposal
### Please re-state the problem that we are trying to solve in this issue.
We are solving the problem of app displaying waypoint page in transition of go back to home page
### What is the root cause of that problem?
Currently we have `isFocused` check in `shouldShow` check of `FullPageNotFoundView` of `WaypointEditor` page. When we click on 'Go back to home page' on waypoint page, it removes focus from `address` field making `isFocused` false
### What changes do you think we should make in order to solve the problem?
We cannot keep the focus on `address` field on 'Go back to home page' click as we are using native component for that part. Ideally, we can remove `isFocused` condition to solve the issue.
We can do that by changing the code [here](https://github.com/Expensify/App/blob/b11bddc054f54bb46d5fb5aaf05e25b8a7df7faf/src/pages/iou/WaypointEditor.js#L166)
```
<FullPageNotFoundView shouldShow={(Number.isNaN(parsedWaypointIndex) || parsedWaypointIndex < 0 || parsedWaypointIndex > waypointCount - 1)}>
```
### What alternative solutions did you explore? (Optional)

**Comment by lschurr** [comment] 2023-09-11 15:42
@thesahindia could you review the proposals here?

**Comment by ahmedGaber93** [comment] 2023-09-12 19:39
@thesahindia 
Steps to reproduce:
1. Click fab icon > request money > distance.
2. Click add stop.
3. Open the last stop "in the video case it is the finish stop".
4. Click the three dots on the header and delete this stop.

Notice while navigation back animation the Not found page appear for mills.

https://github.com/Expensify/App/assets/41129870/bbc76d49-2f0b-4b73-bc95-43aad7648924

**Comment by ahmedGaber93** [comment] 2023-09-12 19:40
@thesahindia Confirm you delete the `isFocused` before test it.

**Comment by lschurr** [comment] 2023-09-15 15:06
Bump @thesahindia

**Comment by lschurr** [comment] 2023-09-18 08:20
Bump on this @chiragsalian :)

**Comment by lschurr** [comment] 2023-09-21 00:19
I've assigned @ZhenjaHorbach to keep this one moving :)

**Comment by lschurr** [comment] 2023-10-09 17:34
@thesahindia could you work on the checklist for this one?

**Comment by lschurr** [comment] 2023-10-09 17:35
Payment summary:

- Bug reporter: @dhanashree-sawant $50
- Contributor: @ZhenjaHorbach $500
- Contributor+: @thesahindia $500

**Comment by lschurr** [comment] 2023-10-10 16:03
Bump @thesahindia for the checklist: https://github.com/Expensify/App/issues/27106#issuecomment-1743427282

**Comment by lschurr** [comment] 2023-10-11 15:53
Great, I added the QA test request. Closing.

**Closed by lschurr** 2023-10-11 15:53 UTC
Labels: External, Daily, Awaiting Payment, Bug

**Comment by JmillsExpensify** [comment] 2023-10-25 17:10
$500 payment approved for @thesahindia based on BZ summary.
