### ISSUE TITLE
[$250] IOS - Expense/IOU - Keyboard overlaps camera when replacing receipt

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#51063] opened 2024-10-17 20:52 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 9.0.50
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**If this was caught on HybridApp, is this reproducible on New Expensify Standalone?:** Y
**If this was caught during regression testing, add the test name, ID and link from TestRail:** N/A
**Issue reported by:** Applause - Internal Team

## Action Performed:
1. Open the app and log in
2. Navigate to any chat
3. Tap + > Submit expense > Manual
4. Enter the amount, add the receipt on the confirmation step and submit IOU/expense
5. Navigate to the IOU/expense details
6. While the keyboard is up, scroll up and tap the receipt
7. Select 3 dots > Replace

## Expected Result:
The keyboard is hidden

## Actual Result:
The keyboard is still displayed and overlaps the camera

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Standalone
- [ ] Android: HybridApp
- [ ] Android: mWeb Chrome
- [x] iOS: Standalone
- [ ] iOS: HybridApp
- [ ] iOS: mWeb Safari
- [ ] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

<details>
  <summary>Add any screenshot/video evidence</summary>

  
</details> 

https://github.com/user-attachments/assets/620e69bb-f0d4-49ec-9f0b-74fa88f45ce8

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~021849498756209836053</li>
        <li>Upwork Job ID: 1849498756209836053</li>
        <li>Last Price Increase: 2024-10-31</li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @suneox</details>

**Comment by c3024** [comment] 2024-10-21 10:01
## Proposal
### Please re-state the problem that we are trying to solve in this issue.
Keyboard overlaps with camera view when replacing receipt.
### What is the root cause of that problem?
When we click on `Replace` in `AttachmentModal`, we execute `closeModal` first and then navigate to the receipt selection scan page.
https://github.com/Expensify/App/blob/8ca4576f77efd6b5312309702feaeb0b49fab17e/src/components/AttachmentModal.tsx#L419-L428
This `closeModal` executes `onModalClose` if it is a function
https://github.com/Expensify/App/blob/8ca4576f77efd6b5312309702feaeb0b49fab17e/src/components/AttachmentModal.tsx#L381-L386
We dismiss the attachment modal in `TransactionReceiptPage` here in `onModalClose`
https://github.com/Expensify/App/blob/8ca4576f77efd6b5312309702feaeb0b49fab17e/src/pages/TransactionReceiptPage.tsx#L53-L58
When we dispatch two such navigation actions (dismissModal and navigate to scan page) one after another immediately, we cannot be sure of the order in which they execute and the actions seem to be interfere with each other.

`navigationRef.dispatch` with `StackActions.pop()` used in `dismissModal` involves a little more complex process of action handling, so this issue is most evident when using `dismissModal`. A similar issue is seen [here](https://github.com/Expensify/App/issues/45774).

Using `goBack` instead of `dismissModal` reduces this largely but still there are chances of unexpected order.

### What changes do you think we should make in order to solve the problem?
We should wait for the navigation actions in `onModalClose` to complete before sending new navigation actions.
So, we can change this
https://github.com/Expensify/App/blob/8ca4576f77efd6b5312309702feaeb0b49fab17e/src/components/AttachmentModal.tsx#L420
to
```js
Navigation.setNavigationActionToMicrotaskQueue(() => Navigation.navigate(
```
so that the next navigation action is added to the micro task queue and gets executed only after the previous navigation action is complete.
### What alternative solutions did you explore? (Optional)

**Comment by JmillsExpensify** [comment] 2024-10-24 17:10
Opening up to the community.

**Comment by suneox** [comment] 2024-10-25 03:33
@c3024 Thank you for your proposal. However, your RCA isn’t clear about which event or referenced code is triggering the input focus that opens the keyboard. Could you please provide more information on that point?

**Comment by c3024** [comment] 2024-10-25 06:03
When we go to a report without any messages, composer autofocuses here

https://github.com/Expensify/App/blob/66112d13bd47ed3d9b029e77b8d494e13808a594/src/pages/home/report/ReportActionCompose/ComposerWithSuggestions/ComposerWithSuggestions.tsx#L306

So, when we close the attachment modal we return to the money request report and the money request view is not considered a message so the composer autofocuses and the keyboard shows up.

I think when the navigation actions are dispatched simultaneously and not successively, the focus seems to trigger later than the second navigation action (here opening the scan page) or the next navigation to scan page happens before the blurring of the composer and the keyboard remains visible.

**Comment by shahinyan11** [comment] 2024-10-25 06:30
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
Review duplicates - Keep this one button does not appear unless expense thread is visited
### What is the root cause of that problem?
On pressing `replace` in the three-dot menu we call the [closeModal](https://github.com/Expensify/App/blob/d6f883a4f21e74b600d241ee5acbcbab69add386/src/components/AttachmentModal.tsx#L381C11-L381C21) function [here](https://github.com/Expensify/App/blob/d6f883a4f21e74b600d241ee5acbcbab69add386/src/components/AttachmentModal.tsx#L419) before navigation. The `closeModal`  in turn calls the `onModalClose` function from the component props  and it calls  `Navigation.dismissModal` inside ( See [here](https://github.com/Expensify/App/blob/d6f883a4f21e74b600d241ee5acbcbab69add386/src/pages/TransactionReceiptPage.tsx#L52C1-L58C10) ).
Above implementation leads to keyboard activation on report screen  before navigation to new screen
### What changes do you think we should make in order to solve the problem?
1. Add optional `shouldCallParentClose` param for [closeModal](https://github.com/Expensify/App/blob/d6f883a4f21e74b600d241ee5acbcbab69add386/src/components/AttachmentModal.tsx#L381C11-L381C21) function and update function body to below
```
    const closeModal = useCallback(( shouldCallParentClose =  true) => {
        setIsModalOpen(false);

        if (typeof onModalClose === 'function' && shouldCallParentClose) {
            onModalClose();
        }

        // eslint-disable-next-line react-compiler/react-compiler, react-hooks/exhaustive-deps
    }, [onModalClose]);
```
2. Call the [closeModal](https://github.com/Expensify/App/blob/d6f883a4f21e74b600d241ee5acbcbab69add386/src/components/AttachmentModal.tsx#L419C21-L419C31) function with `false` parameter .

3. OPTIONAL: Move  `closeModal(false)` under `Navigation.navigate` 
```
onSelected: () => {
    Navigation.navigate(
        ROUTES.MONEY_REQUEST_STEP_SCAN.getRoute(
            CONST.IOU.ACTION.EDIT,
            iouType,
            transaction?.transactionID ?? '-1',
            report?.reportID ?? '-1',
            Navigation.getActiveRouteWithoutParams(),
        ),
    );
    closeModal(false);
},
```

### What alternative solutions did you explore? (Optional)

**Comment by shahinyan11** [comment] 2024-10-25 06:38
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
 IOS - Expense/IOU - Keyboard overlaps camera when replacing receipt
### What is the root cause of that problem?
On pressing `replace` in the three-dot menu we call the [closeModal](https://github.com/Expensify/App/blob/d6f883a4f21e74b600d241ee5acbcbab69add386/src/components/AttachmentModal.tsx#L381C11-L381C21) function [here](https://github.com/Expensify/App/blob/d6f883a4f21e74b600d241ee5acbcbab69add386/src/components/AttachmentModal.tsx#L419) before navigation. The `closeModal`  in turn calls the `onModalClose` function from the component props  and it calls  `Navigation.dismissModal` inside ( See [here](https://github.com/Expensify/App/blob/d6f883a4f21e74b600d241ee5acbcbab69add386/src/pages/TransactionReceiptPage.tsx#L52C1-L58C10) ).
Above implementation leads to keyboard activation on report screen  before navigation to new screen
### What changes do you think we should make in order to solve the problem?
1. Add optional `shouldCallParentClose` param for [closeModal](https://github.com/Expensify/App/blob/d6f883a4f21e74b600d241ee5acbcbab69add386/src/components/AttachmentModal.tsx#L381C11-L381C21) function and update function body to below
```
    const closeModal = useCallback(( shouldCallParentClose =  true) => {
        setIsModalOpen(false);

        if (typeof onModalClose === 'function' && shouldCallParentClose) {
            onModalClose();
        }

        // eslint-disable-next-line react-compiler/react-compiler, react-hooks/exhaustive-deps
    }, [onModalClose]);
```
2. Call the [closeModal](https://github.com/Expensify/App/blob/d6f883a4f21e74b600d241ee5acbcbab69add386/src/components/AttachmentModal.tsx#L419C21-L419C31) function with `false` parameter .

3. OPTIONAL: Move  `closeModal(false)` under `Navigation.navigate` 
```
onSelected: () => {
    Navigation.navigate(
        ROUTES.MONEY_REQUEST_STEP_SCAN.getRoute(
            CONST.IOU.ACTION.EDIT,
            iouType,
            transaction?.transactionID ?? '-1',
            report?.reportID ?? '-1',
            Navigation.getActiveRouteWithoutParams(),
        ),
    );
    closeModal(false);
},
```

### What alternative solutions did you explore? (Optional)

**Comment by shahinyan11** [comment] 2024-10-25 06:39
@suneox I posted a proposal for this issue a week ago, but somehow it was posted under a different issue. I must have mixed up the issues and posted the solution in the wrong place.

**Comment by shahinyan11** [comment] 2024-10-25 06:40
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
 IOS - Expense/IOU - Keyboard overlaps camera when replacing receipt
### What is the root cause of that problem?
On pressing `replace` in the three-dot menu we call the [closeModal](https://github.com/Expensify/App/blob/d6f883a4f21e74b600d241ee5acbcbab69add386/src/components/AttachmentModal.tsx#L381C11-L381C21) function [here](https://github.com/Expensify/App/blob/d6f883a4f21e74b600d241ee5acbcbab69add386/src/components/AttachmentModal.tsx#L419) before navigation. The `closeModal`  in turn calls the `onModalClose` function from the component props  and it calls  `Navigation.dismissModal` inside ( See [here](https://github.com/Expensify/App/blob/d6f883a4f21e74b600d241ee5acbcbab69add386/src/pages/TransactionReceiptPage.tsx#L52C1-L58C10) ).
Above implementation leads to keyboard activation on report screen  before navigation to new screen
### What changes do you think we should make in order to solve the problem?
1. Add optional `shouldCallParentClose` param for [closeModal](https://github.com/Expensify/App/blob/d6f883a4f21e74b600d241ee5acbcbab69add386/src/components/AttachmentModal.tsx#L381C11-L381C21) function and update function body to below
```
    const closeModal = useCallback(( shouldCallParentClose =  true) => {
        setIsModalOpen(false);

        if (typeof onModalClose === 'function' && shouldCallParentClose) {
            onModalClose();
        }

        // eslint-disable-next-line react-compiler/react-compiler, react-hooks/exhaustive-deps
    }, [onModalClose]);
```
2. Call the [closeModal](https://github.com/Expensify/App/blob/d6f883a4f21e74b600d241ee5acbcbab69add386/src/components/AttachmentModal.tsx#L419C21-L419C31) function with `false` parameter .

3. OPTIONAL: Move  `closeModal(false)` under `Navigation.navigate` 
```
onSelected: () => {
    Navigation.navigate(
        ROUTES.MONEY_REQUEST_STEP_SCAN.getRoute(
            CONST.IOU.ACTION.EDIT,
            iouType,
            transaction?.transactionID ?? '-1',
            report?.reportID ?? '-1',
            Navigation.getActiveRouteWithoutParams(),
        ),
    );
    closeModal(false);
},
```

### What alternative solutions did you explore? (Optional)

**Comment by suneox** [comment] 2024-10-27 03:38
@c3024  Your solution to delay navigation to the next screen until after closing the modal will also trigger keyboard focus and creating an odd behavior


https://github.com/user-attachments/assets/66ea132f-51cc-4119-823b-be9a854f084c


@shahinyan11 Your solution to close the modal after navigating to the next screen could lead to unresponsiveness when returning to the previous screen.


https://github.com/user-attachments/assets/7e4cebb5-a3bd-4c22-935f-04b740729150

**Comment by shahinyan11** [comment] 2024-10-28 13:19
The problem doesn't seem to be reproducible on the latest main.

**Comment by suneox** [comment] 2024-10-30 15:35
@JmillsExpensify This issue isn’t reproducible on the latest main branch or the most recent release in the store

**Closed** 2024-11-06 18:16 UTC
Labels: External, Daily, Help Wanted, Overdue, Bug
