### ISSUE TITLE
[Awaiting payment] [$250] [Dupe detection] Description review appears when distance expenses are created without description

### ISSUE THREAD

**Issue by IuliiaHerets** [Expensify/App#47974] opened 2024-08-24 21:50 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** v9.0.24-1
**Reproducible in staging?:** Y
**Reproducible in production?:** Y 
**Email or phone of affected tester (no customers):** applausetester+kh050806@applause.expensifail.com
**Issue reported by:** Applause Internal Team 

## Action Performed:
1. Go to staging.new.expensify.com
2. Go to workspace chat.
3. Submit two same distance expenses without description.
4. Go to transaction thread of any of the expense.
5. Click Review duplicates.
6. Click Keep this one (any).

## Expected Result:
Description review will not show up because both distance expenses are created without description.

## Actual Result:
Description review appears when both distance expenses are created without description.

## Workaround:
Unknown

## Platforms:

- [x] Android: Native
- [x] Android: mWeb Chrome
- [x] iOS: Native
- [x] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

https://github.com/user-attachments/assets/70398b91-c43d-4c2d-b2c2-bf44e54ed76a

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01d6cf4756c6ab01be</li>
        <li>Upwork Job ID: 1828335490161750402</li>
        <li>Last Price Increase: 2024-08-27</li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @adelekennedy</details>

**Comment by IuliiaHerets** [comment] 2024-08-24 21:50
We think that this bug might be related to #wave-control

**Comment by IuliiaHerets** [comment] 2024-08-24 21:51
@adelekennedy  FYI I haven't added the External label as I wasn't 100% sure about this issue. Please take a look and add the label if you agree it's a bug and can be handled by external contributors

**Comment by trjExpensify** [comment] 2024-08-28 00:34
Dupe detection is a #wave-control project. CC: @dylanexpensify @pecanoro @parasharrajat @kubabutkiewicz

**Comment by mananjadhav** [comment] 2024-08-28 17:07
Are we looking at regression or something @trjExpensify ? Should I go ahead with the proposal reviews?

**Comment by trjExpensify** [comment] 2024-08-28 17:45
Go ahead with the reviews, I was just bringing it to the attention of the dupe detection team.

**Comment by pecanoro** [comment] 2024-08-29 12:32
The cause and proposals seem to be the same as this one https://github.com/Expensify/App/issues/47975 so we can go ahead with this one for now

**Comment by pecanoro** [comment] 2024-08-30 09:45
@mananjadhav Could you review the proposals when you have a moment?

**Comment by mananjadhav** [comment] 2024-09-02 09:30
I think it makes sense to use `getDescription`. Hence @daledah's [proposal](https://github.com/Expensify/App/issues/47974#issuecomment-2308610869) looks good to me.

🎀 👀 🎀 C+ reviewed.

**Comment by pecanoro** [comment] 2024-09-02 11:31
Yes, after reading the proposals, I think we should always just compare the description/comment without taking into account whatever else is stored in the field (since it can vary from expense to expense).

**Comment by mananjadhav** [comment] 2024-09-26 19:01
PR has been merged and deployed to staging

**Comment by pecanoro** [comment] 2024-10-07 19:20
PR has been on production for a week, not sure why the automatization did not work, so I am going to adjust manually

**Comment by mananjadhav** [comment] 2024-10-08 16:36
I don't have a specific offending PR for this one. We've been comparing raw comment hence the issue. But I feel we should have a regression test for this.

**Regression test proposal:**

1. Go to workspace chat.
2. Submit two same distance expenses without description.
3. Go to transaction thread of any of the expense.
4. Click Review duplicates.
5. Click Keep this one (any).
6. Verify that: Description review will not show up because both distance expenses are created without description.

**Comment by adelekennedy** [comment] 2024-10-09 16:41
Payouts due:

- [ ] Contributor: $250 @daledah [Upwork](https://www.upwork.com/ab/applicants/1844055581358767584/suggested)
- [ ] Contributor+: $250 @mananjadhav NewDot

Upwork job is [here](https://www.upwork.com/jobs/~021844055581358767584). @daledah please apply!

**Comment by adelekennedy** [comment] 2024-10-14 02:37
@daledah hired you for the job

**Comment by adelekennedy** [comment] 2024-10-14 15:18
payments made

**Closed by adelekennedy** 2024-10-14 15:18 UTC
Labels: External, Daily, Awaiting Payment, Bug

**Comment by garrettmknight** [comment] 2024-10-15 01:12
$250 approved for @mananjadhav
