### ISSUE TITLE
Email not shown for new user in the contact method (on Profile page) 

### ISSUE THREAD

**Issue by kavimuru** [Expensify/App#21039] opened 2023-06-19 14:56 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Go to staging dot on web chrome and login with a new user -create a new account (important step)
2. Click on Settings > Profile
3. You're on the Profile page and notice that on 'Contact method' that is just present below the 'Display name' doesn't shown the email
4. Follow the same steps on production with a new user and notice that on the Profile page, email is shown as default under 'Contact method'
## Expected Result: 
Email should be shown for new user in the contact method (on Profile page)
## Actual Result: 
Email not shown for new user in the contact method (on Profile page) in staging but works well on production

## Workaround:
Can the user still use Expensify without this being fixed? Have you informed them of the workaround?

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [x] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 1.3.29-0
**Reproducible in staging?:** y
**Reproducible in production?:** n
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/43996225/c44cac4a-29fe-4b25-a8e5-f4fb40c3975e

<img width="955" alt="IMG_4125" src="https://github.com/Expensify/App/assets/43996225/52c2b7a7-39ca-4fc2-80e6-3de98c2f3b23">

**Expensify/Expensify Issue URL:**
**Issue reported by:** @priya-zha
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1687155411925429

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by luacmartins** [comment] 2023-06-19 22:57
This had the same root cause of #fireroom-getpersonaldetailslist and it's no longer reproducible after the latest Auth deploy. Closing.

**Closed by luacmartins** 2023-06-19 22:57 UTC
Labels: DeployBlockerCash, Engineering, Hourly, Bug

**Comment by priya-zha** [comment] 2023-06-20 12:36
@luacmartins It's still reproducible on staging. Can you please check it once more?
![Screenshot from 2023-06-20 18-21-07](https://github.com/Expensify/App/assets/34065075/4209008b-ad6f-4918-8aef-daee9213b8d9)

**Comment by luacmartins** [comment] 2023-06-20 15:26
Just tried again with a brand new account and still can't reproduce

https://github.com/Expensify/App/assets/22219519/8ff5befd-7151-468f-a987-399205298d2b

**Comment by priya-zha** [comment] 2023-06-20 16:14
It seems weird that I'm still able to reproduce it. Also the same issue was posted by some other contributor today [here :](https://expensify.slack.com/archives/C049HHMV9SM/p1687256778913529). I tried this on chrome web with a gmail account. I don't know whether it's related or not , but have you tried with a gmail account?  Thanks

https://github.com/Expensify/App/assets/34065075/f68828fb-a0a6-4721-b512-f94f96313338

**Comment by luacmartins** [comment] 2023-06-20 18:47
Just tried with a new gmail account and I still can't reproduce the issue.
