### ISSUE TITLE
[$1000] Web - App Redirects to Concierge when Refreshing and Clicking on Composer in Assign Task

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#23581] opened 2023-07-25 19:14 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Go to staging.new.expensify.com
2. Create a new account
3. Click on the plus sign, then select "Assign Task."
4. Add a Title, Description, Assignee, Share somewhere, and confirm the task.
5. Click anywhere on the composer to observe its behavior.
6. Refresh the page and click anywhere on the composer again. Notice that the app redirects to the Concierge section.

## Expected Result:
After refreshing the page, the app should not redirect to the Concierge section when clicking on the composer in the Assign Task section. The composer should function as intended without any redirection.

## Actual Result:
Currently, when clicking on the composer after refreshing the page in the Assign Task section, the app unexpectedly redirects to the Concierge section. This behavior deviates from the expected behavior and may disrupt the user's workflow.

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [x] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 1.3.45.3
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/93399543/c0796867-aee1-4315-b128-dfddfffc1ae3

https://github.com/Expensify/App/assets/93399543/628e39bb-265d-42a5-8028-72ef28796160

**Expensify/Expensify Issue URL:**
**Issue reported by:** @tewodrosGirmaA
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1690292692487909

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~0184c3a537500f9673</li>
        <li>Upwork Job ID: 1683981240680468480</li>
        <li>Last Price Increase: 2023-07-25</li>
    </ul>
</details>

**Comment by thanhle98** [comment] 2023-07-26 02:04
Hello guys, I tested the issue again and found the bug could not reproduce anymore. Maybe it is because the current version of staging I am testing is v1.3.45-7. (The bug got reported in v1.3.45-3). 

It could be fixed by someone else I guess.

<img width="1387" alt="Screenshot 2023-07-26 at 08 58 51" src="https://github.com/Expensify/App/assets/34940000/068aaf7e-aff2-4481-87e0-5caa0d584efc">

**Comment by twisterdotcom** [comment] 2023-07-26 13:09
Okay, let's close!

**Closed by twisterdotcom** 2023-07-26 13:09 UTC
Labels: External, Daily, Help Wanted, Bug
