### ISSUE TITLE
[HOLD for payment 2024-12-09] [$250] iOS - Accounting - Confirm button jumps when entering user ID for Sage Intacct

### ISSUE THREAD

**Issue by IuliiaHerets** [Expensify/App#52234] opened 2024-11-08 08:24 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 9.0.59.0
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**If this was caught during regression testing, add the test name, ID and link from TestRail:** https://expensify.testrail.io/index.php?/tests/view/5195617
**Issue reported by:** Applause Internal Team

## Action Performed:
Precondition: user has saved credentials
1. Open the app and log in
2. Create a workspace if there is no any
3. Navigate to the workspace settings > More features and enable the Accounting option
4. Open Accounting and select Intacct
5. Upgrade the policy if it has not been done yet
6. Proceed to the step to enter credentials
7. Tap the user ID field and start entering the credentials

## Expected Result:
The Confirm button does not jump

## Actual Result:
The Confirm button jumps when entering user ID. It does not happen when entering a password even though the password auto-fill is present.

## Workaround:
Unknown

## Platforms:

- [ ] Android: Standalone
- [ ] Android: HybridApp
- [ ] Android: mWeb Chrome
- [ ] iOS: Standalone
- [x] iOS: HybridApp
- [x] iOS: mWeb Safari
- [ ] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

https://github.com/user-attachments/assets/5660998b-2f01-4e33-827d-bfd9605b5f88
 
</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~021859980122209615794</li>
        <li>Upwork Job ID: 1859980122209615794</li>
        <li>Last Price Increase: 2024-11-22</li>
<li>Automatic offers: </li>
<ul>
<li>suneox | Reviewer | 105074090</li>
<li>huult | Contributor | 105074091</li>
</ul></li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @johncschuster</details>

**Comment by IuliiaHerets** [comment] 2024-11-08 08:26
Issue is repro on newest iOS devices (iPhone 15 Pro Max and iPhone 16)

**Comment by truph01** [comment] 2024-11-11 16:54
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
The Confirm button jumps when entering user ID. It does not happen when entering a password even though the password auto-fill is present.

### What is the root cause of that problem?

It's an issue with the Passwords option in the Keyboard toolbar. We already notice it in https://github.com/facebook/react-native/issues/39411#issuecomment-1744962420

We should fix it since it can affect on users experience (button jumps unexpectedly on non-password input)
### What changes do you think we should make in order to solve the problem?


We can use `textContentType='oneTimeCode'`

```
textContentType='oneTimeCode'

```

### What alternative solutions did you explore? (Optional)

We can show the `Confirm` button right below the inputs by updating the `styles.justifyContentEnd` here

https://github.com/Expensify/App/blob/5b1ee3f2b07ed6e9f46915d07574cb3ee8e0d8a3/src/components/FormAlertWithSubmitButton.tsx#L100


```
            containerStyles={[shouldShowConfirmButtonAtTheEnd && styles.justifyContentEnd, safePaddingBottomStyle, containerStyles]}
```

**Comment by abekkala** [comment] 2024-11-19 15:25
Stevie has been and will be ooo - reapplying label

**Comment by huult** [comment] 2024-11-24 14:14
## Proposal

### Please re-state the problem that we are trying to solve in this issue.

Confirm button jumps when entering user ID for Sage Intacct

### What is the root cause of that problem?

This is our ticket related to the discussion on the React Native issue: https://github.com/facebook/react-native/issues/39411

> https://github.com/facebook/react-native/issues/39411#issuecomment-1726601414

They identified the problem in this comment

> https://github.com/facebook/react-native/issues/39411#issuecomment-1744962420

It confirms that this is an OS-specific issue that emerged with iOS 17.x

### What changes do you think we should make in order to solve the problem?

> https://github.com/facebook/react-native/issues/39411#issuecomment-2467008120

We can use the workaround solution mentioned in this comment to resolve the issue.
Something like that:

```diff
// src/pages/workspace/accounting/intacct/EnterSageIntacctCredentialsPage.tsx#L81
    <InputWrapper
        InputComponent={TextInput}
        inputID={formItem}
        label={translate(`common.${formItem}`)}
        aria-label={translate(`common.${formItem}`)}
        role={CONST.ROLE.PRESENTATION}
        spellCheck={false}
        secureTextEntry={formItem === INPUT_IDS.PASSWORD}
+      autoCorrect={false}
+      textContentType={formItem === INPUT_IDS.USER_ID ? 'none' : undefined}
    />
```

As mentioned in [this StackOverflow comment](https://stackoverflow.com/questions/77327819/issues-with-ios-17-and-keyboardavoidingview-email-type-input/78681410#78681410), it explains why we shouldn't use `textContentType="oneTimeCode"`. I think we should use autoCorrect={false} as well. The flickering only occurs the first time, so I believe it's okay and doesn't significantly impact the user experience. 

<details>
<summary>POC</summary>

https://github.com/user-attachments/assets/0acdf500-8cf4-4075-99cb-3f276a1ac5b4

</details>

### What alternative solutions did you explore? (Optional)

**Comment by suneox** [comment] 2024-11-25 06:34
Thank you for all the proposals. This issue is related to iOS issue when we have multiple fields with `secureTextEntry`. @huult proposal can fix the flashing issue while typing. Although it still flashes once on the first input, but I think it’s acceptable as it prevents the flashing noise on every keystroke. Therefore, I think we can proceed with @huult [proposal](https://github.com/Expensify/App/issues/52234#issuecomment-2496026459).

🎀 👀 🎀 C+ reviewed

**Comment by huult** [comment] 2024-11-26 02:18
@grgia , With [this approach](https://github.com/Expensify/App/issues/52234#issuecomment-2496026459), we can't prevent the flash on the first input. However, aside from that, we don't encounter issues like the one mentioned in [this StackOverflow comment](https://stackoverflow.com/questions/77327819/issues-with-ios-17-and-keyboardavoidingview-email-type-input/78681410#78681410).

**Comment by suneox** [comment] 2024-11-26 04:49
It looks like we have a limitation with this issue. I also checked a few apps has multiple field using the iOS password hint feature, and they also have the same flashing issue.

<details>
<summary>Notion / DaiChi / Booking</summary>


https://github.com/user-attachments/assets/5de3a1fe-6bf8-4a51-96c5-daa544aeffe3



https://github.com/user-attachments/assets/f0222846-d2f3-49cb-8fb7-a288526dff9e



https://github.com/user-attachments/assets/ca32f876-8957-4838-95c4-6b183896860d



</details>


Here is the behavior before and after the fix for this issue. If we agree with this behavior, we can proceed by disabling the max height for this screen to avoid height changes on iOS.

Before fix


https://github.com/user-attachments/assets/cc314248-c90e-40f2-9a3c-626fbbf9d868


After fix


https://github.com/user-attachments/assets/073d24ae-c7a2-4b70-aba0-af8a73fe9b94

**Comment by grgia** [comment] 2024-11-26 09:37
@suneox hmm yeah it's not perfect, but I see the limitations. It's definitely an improvement from every input, I'll assign for now

**Comment by johncschuster** [comment] 2024-12-03 13:51
# BugZero Checklist:

- [ ] **[Contributor]** Classify the bug:

<details>
<summary>Bug classification</summary>


Source of bug:
  - [ ] 1a. Result of the original design (eg. a case wasn't considered)
  - [ ] 1b. Mistake during implementation
  - [ ] 1c. Backend bug
  - [ ] 1z. Other:

Where bug was reported:
  - [ ] 2a. Reported on production
  - [ ] 2b. Reported on staging (deploy blocker)
  - [ ] 2c. Reported on both staging and production
  - [ ] 2d. Reported on a PR
  - [ ] 2z. Other:

Who reported the bug:
  - [ ] 3a. Expensify user
  - [ ] 3b. Expensify employee
  - [ ] 3c. Contributor
  - [ ] 3d. QA
  - [ ] 3z. Other:

</details>

- [ ] **[Contributor]** The offending PR has been commented on, pointing out the bug it caused and why, so the author and reviewers can learn from the mistake.

    Link to comment:

- [ ] **[Contributor]** If the regression was CRITICAL (e.g. interrupts a core flow) A discussion in [#expensify-open-source](https://app.slack.com/client/E047TPA624F/C01GTK53T8Q) has been started about whether any other steps should be taken (e.g. updating the PR review checklist) in order to catch this type of bug sooner.

    Link to discussion:

- [ ] **[Contributor]** If it was decided to create a regression test for the bug, please propose the [regression test](https://github.com/Expensify/App/blob/main/contributingGuides/REGRESSION_TEST_BEST_PRACTICES.md) steps using the template below to ensure the same bug will not reach production again.

<details>
<summary>Regression Test Proposal Template</summary>


- [ ] **[BugZero Assignee]** Create a GH issue for creating/updating the regression test once above steps have been agreed upon.

    Link to issue:

## Regression Test Proposal
### Precondition:


-

### Test:


1.

Do we agree 👍 or 👎


</details>

**Comment by suneox** [comment] 2024-12-08 07:35
# BugZero Checklist:

- [x] **[Contributor]** Classify the bug:

<details>
<summary>Bug classification</summary>


Source of bug:
  - [ ] 1a. Result of the original design (eg. a case wasn't considered)
  - [ ] 1b. Mistake during implementation
  - [ ] 1c. Backend bug
  - [x] 1z. Other: *Existing issue on iOS*

Where bug was reported:
  - [x] 2a. Reported on production (eg. bug slipped through the normal regression and PR testing process on staging)
  - [ ] 2b. Reported on staging (eg. found during regression or PR testing)
  - [ ] 2d. Reported on a PR
  - [ ] 2z. Other:

Who reported the bug:
  - [ ] 3a. Expensify user
  - [ ] 3b. Expensify employee
  - [ ] 3c. Contributor
  - [x] 3d. QA
  - [ ] 3z. Other:

</details>

- [x] **[Contributor]** The offending PR has been commented on, pointing out the bug it caused and why, so the author and reviewers can learn from the mistake.

    Link to comment: *This issue related to ios issue, so we don’t have an offending PR.*

- [x] **[Contributor]** If the regression was CRITICAL (e.g. interrupts a core flow) A discussion in [#expensify-open-source](https://app.slack.com/client/E047TPA624F/C01GTK53T8Q) has been started about whether any other steps should be taken (e.g. updating the PR review checklist) in order to catch this type of bug sooner.

    Link to discussion: *N/A*

- [x] **[Contributor]** If it was decided to create a regression test for the bug, please propose the [regression test](https://github.com/Expensify/App/blob/main/contributingGuides/REGRESSION_TEST_BEST_PRACTICES.md) steps using the template below to ensure the same bug will not reach production again.
    *N/A: It isn't an impactful bug*

**Closed** 2024-12-09 17:13 UTC
Labels: External, Daily, Awaiting Payment, Bug
