### ISSUE TITLE
Web - Assign Task - Delay in assigning emojis to the "completed/reopened task" and the emojis disappear after a short period of time.

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#22061] opened 2023-07-02 13:31 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Clicked on the plus sign.
2. Clicked on "Assign Task".
3. Entered the title and clicked on "Next".
4. Filled in the "Assignee" and "Share somewhere" fields.
5. Clicked on "Confirm Task".
6. Reacted with an emoji to the "completed/reopened task" message.
7. Notice that there is a delay in the emoji reaction and the emojis disappear after a short period of time.

## Expected Result:
There should be no delay or disappearance of emojis when reacting to "completed/reopened task" messages.

## Actual Result:
There is a delay and disappearance of emojis when reacting to "completed/reopened task" messages.

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [x] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 1.3.35-5
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/93399543/973ca6ab-2bfb-4769-8025-91f84b58fa2a

https://github.com/Expensify/App/assets/93399543/0dc270eb-35c9-4524-bc97-f76b3c76fc25

**Expensify/Expensify Issue URL:**
**Issue reported by:** @usmantariq96
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1688197693362519

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by sophiepintoraetz** [comment] 2023-07-05 02:19
I've been able to reproduce this! (coming from https://github.com/Expensify/App/issues/22213)
![2023-07-05_14-17-55 (1)](https://github.com/Expensify/App/assets/42940078/a647bbf1-277f-40b1-b402-8efa40b893ce)

**Comment by sophiepintoraetz** [comment] 2023-07-05 02:20
@s-alves10 - you're welcome to add your proposal here!

**Comment by sophiepintoraetz** [comment] 2023-07-05 02:21
Although, this https://github.com/Expensify/App/issues/16506 may have an impact?

**Comment by s-alves10** [comment] 2023-07-05 04:59
## Proposal

### Please re-state the problem that we are trying to solve in this issue.

Reactions to task disappears when come back from parent chat

### What is the root cause of that problem?

When reacting to the message, we get the original report ID here
https://github.com/Expensify/App/blob/7e908b17565e7bf659309f4b4d95141e70094ab9/src/libs/ReportUtils.js#L2392-L2394

Taking a look into `isThreadFirstChat` function
https://github.com/Expensify/App/blob/7e908b17565e7bf659309f4b4d95141e70094ab9/src/libs/ReportUtils.js#L554-L556

we can notice that task messages(TASKCOMPLETED and TASKREOPENED) meet the condition, but they are not the thread first messages. So when reacting to task messages, parent reportID is used. This is wrong.

This is the 1st reason of the issue.

When call reaction API with the corrected reportID, backend returns reactions in originalMessage, not in message
![image](https://github.com/Expensify/App/assets/126839717/ad5f6ea1-106c-4dae-9a52-98920e2f5c78)

This is the 2nd reason of the issue

### What changes do you think we should make in order to solve the problem?

1. Frontend only solution
Creates the `isTaskAction` function in ReportActionUtils.js
```
function isTaskAction(reportAction) {
    const taskActions = [
        CONST.REPORT.ACTIONS.TYPE.TASKCOMPLETED,
        CONST.REPORT.ACTIONS.TYPE.TASKREOPENED,
        CONST.REPORT.ACTIONS.TYPE.TASKCANCELED,
    ];
    return _.includes(taskActions, lodashGet(reportAction, 'actionName', ''));
}
```

Updates the `isThreadFirstChat` function
```
    return (
        isThreadFirstChat(reportAction, reportID) && !ReportActionUtils.isTaskAction(reportAction) ?
        lodashGet(allReports, [`${ONYXKEYS.COLLECTION.REPORT}${reportID}`, 'parentReportID']) :
        reportID
    );
```

Merge `message`'s reactions and `originalMessage`'s reactions

This works as expected.

2. Frontend & Backend solution
The 1st issue can be fixed in frontend and the 2nd issue can be fixed in backend

3. Backend only solution
Backend should return task messages without `childReportID`. I think this is reasonable
Backend also should return reactions in `message`


### What alternative solutions did you explore? (Optional)

**Comment by sakluger** [comment] 2023-07-05 17:53
Thanks @sophiepintoraetz for the repro! I posted in the other issue you linked to see if that PR would fix this issue as well.

**Comment by sakluger** [comment] 2023-07-07 22:05
We're not sure if the PR in the other issue will fix this one, so I'm going to put this one on hold until that one is live.

**Comment by sakluger** [comment] 2023-07-18 22:37
Still on hold.

**Comment by sakluger** [comment] 2023-07-28 00:11
Still on hold for https://github.com/Expensify/App/issues/16506.

**Comment by sakluger** [comment] 2023-08-07 21:32
That hold issue doesn't seem to have fixed things here. I asked @stitesExpensify in the other issue if we should continue holding or look for solutions here.

**Comment by stitesExpensify** [comment] 2023-08-09 15:02
Disappointed that the other issue didn't fix this, but it was still the right call to hold since I'm now almost sure that this is an internal issue. I'll take a look and post my findings here

**Comment by sakluger** [comment] 2023-08-10 21:55
Thanks @stitesExpensify - if you find that it is an internal issue, please add the internal label. 🙏

**Comment by sakluger** [comment] 2023-08-14 17:22
Hey @stitesExpensify, were you able to test this yet? I'll assign to you for now while you test, feel free to unassign once you're done if you find that it's not actually internal.

**Comment by stitesExpensify** [comment] 2023-08-14 22:02
Not yet, I've been focused elsewhere. I'll try to take care of it tomorrow

**Comment by stitesExpensify** [comment] 2023-08-15 21:40
It looks like there is a different issue now where you can't react to those messages at all. IMO we should just close this and open a new external issue for that issue since this is so old. Thoughts @sakluger ?

**Comment by sakluger** [comment] 2023-08-17 18:30
Weird - I can't emoji react on the "completed task" and "reopened task" comments on an existing task , but I can add emojis just fine on a new task. I think something may have been screwy with the tasks created during a certain time, and they are working fine now.

I'm going to ask in the main thread if they can try reproducing on a newly created task.

**Comment by sakluger** [comment] 2023-08-17 18:31
Actually, @stitesExpensify can you try reproducing first on a newly created task?

**Comment by sakluger** [comment] 2023-08-21 16:59
@stitesExpensify checking in again - are you seeing the same behavior I did, where emojis are working on newly created tasks, but not on old tasks?

**Comment by stitesExpensify** [comment] 2023-08-22 13:51
Testing now

**Comment by stitesExpensify** [comment] 2023-08-22 15:26
Yes I'm seeing the same issue as you @sakluger

**Comment by sakluger** [comment] 2023-08-23 21:03
I'm not really sure how to handle this now, since the original issue is not occurring, and there is a new issue that is only occurring on certain tasks created in the past. I can't reproduce the issue on newly created tasks, so I'm inclined to close the issue for now. @stitesExpensify please reopen if you disagree and think we should look into the issue on those old tasks.

**Closed by sakluger** 2023-08-23 21:03 UTC
Labels: Daily, Bug
