### ISSUE TITLE
[$500] Chat - User paste 2 email together, the part after @ is not considered as url & shown as link

### ISSUE THREAD

**Issue by izarutskaya** [Expensify/App#30697] opened 2023-11-01 13:06 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.3.94-0
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** Applause-Internal Team
**Slack conversation:** @

## Action Performed:
1. Go to https://staging.new.expensify.com/
2. Tap on a report
3. Paste a email id twice without space together and send it eg: [Dghg@ry.comDghg@ry.com](mailto:Dghg@ry.comDghg@ry.com)

## Expected Result:
ry.com must be displayed as url.

## Actual Result:
After com, Dghg is considered as email and shown as url. But ry.com is not shown as url.

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [x] Android: mWeb Chrome
- [x] iOS: Native
- [x] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

![Bug6259123_1698829459691!IMG_20231101_142340](https://github.com/Expensify/App/assets/115492554/fb2eca58-1103-419e-bec0-b5c9f2436f7b)

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~019e814827368ea6c0</li>
        <li>Upwork Job ID: 1719702566051106816</li>
        <li>Last Price Increase: 2023-11-08</li>
    </ul>
</details>

**Comment by erquhart** [comment] 2023-11-01 13:15
I don't know if there's an optimal way to handle this, if a user pastes nonsense like this I think the current behavior is what I'd expect.

**Comment by barros001** [comment] 2023-11-01 13:55
I agree with @erquhart, this looks like the expected behavior. This is how Slack handles it as well, see below:

![IMG_2587](https://github.com/Expensify/App/assets/765936/5c852456-7f9c-475d-9027-11919f962352)

**Comment by AlienistSolution** [comment] 2023-11-01 23:47
In step 3 of Action Performed above GitHub actually shows the entire thing as 1 URL. The question is what do you want to achieve functionally here? 

Do you want the two email addresses to appear as one and be clickable? 

Or do you want some logic that can assess this and identify that it's actually two or more addresses joint together and then split them up?

In scenario 1 that is not a valid email addresses since it contains two @ signs and it will act as a faulty URL. But at least it's clickable as a whole and the user's original text is not altered.

In scenario 2 you have two separated addresses that both qualify as valid email addresses and are clickable, but it means changing the user's original content, which might not be what you want.

If you could clarify a bit more what the functional idea behind the expected result is, that would help to assess whether this is a good idea and then also how to suggest fixing it.

**Comment by AlienistSolution** [comment] 2023-11-01 23:56
Contributor details
Your Expensify account email: arjuna@alienistsolution.com
Upwork Profile Link: https://www.upwork.com/freelancers/~01677298654b2ba748

**Comment by AlienistSolution** [comment] 2023-11-02 06:46
Okay, so just parse it as if it's a link, noted. I would like to fix it, but I think your rules state that I have to provide a solution here first before pushing a proposal on Upwork, is that correct? If so, I'll have to peek quickly through your codebase and provide a more detailed solution. Please let me know.

**Comment by mollfpr** [comment] 2023-11-02 13:48
>Do you want the two email addresses to appear as one and be clickable?

@NisargDeveloper @AlienistSolution No. The expected result is listed in the description.

>I would like to fix it, but I think your rules state that I have to provide a solution here first before pushing a proposal on Upwork, is that correct? If so, I'll have to peek quickly through your codebase and provide a more detailed solution. Please let me know.

There's no proposal for an issue process on Upwork. You will get the Upwork offer after you've been assign to the issue.

**Comment by erquhart** [comment] 2023-11-02 13:56
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
When two emails are pasted in with no space between them, the first email address is treated as a link, except the first email address domain is concatenated to the beginning of the second email address. There is a trailing `@` symbol after the link. The request is for the domain after the trailing `@` symbol to be styled as a link.

### What is the root cause of that problem?
The user pasted two email addresses with no space in between.

### What changes do you think we should make in order to solve the problem?

I do not believe a change should be made. If you change your message parsing to try and create an optimal outcome for this, I would fully expect new bugs to occur because of it. The requirements also don't account for the fact that the initial email address being styled as a link here is incorrect, as it concatenates the beginning of the second email address to the TLD of the first.

Also, as another commenter mentioned, Slack handles this the same, so you're in good company.

### What alternative solutions did you explore? (Optional)
None, I recommend not making changes to fix this specific case.

**Comment by NisargDeveloper** [comment] 2023-11-02 14:41
@mollfpr Thanks. Will Wait then

**Comment by NisargDeveloper** [comment] 2023-11-03 14:36
Hey I was wondering if you still need a help

**Comment by dylanexpensify** [comment] 2023-11-06 09:39
@mollfpr please review proposal 🙇‍♂️ 
@NisargDeveloper we're still accepting proposals!

**Comment by NisargDeveloper** [comment] 2023-11-06 11:39
I already gave the proposal... I

I think we have to parse the whole input as an URL. Then it should work fine.
There is one more Library in React/ React Native we can use which parses everything into a link.

Let me know if you want to solve this issue. THanks

**Comment by mollfpr** [comment] 2023-11-06 16:58
@NisargDeveloper Please post the proposal in the issue, not in the Upwork.

@dylanexpensify I think the proposal from @erquhart is we do nothing. I am curious about the benefits of the expected result.

**Comment by NisargDeveloper** [comment] 2023-11-06 20:37
## Proposal

### Please re-state the problem that we are trying to solve in this issue.

When pasting two email it is not showing as link

### What is the root cause of that problem?

It looks like we are not parsing whole email address as an input. That is the reason it is causing an issue.

### What changes do you think we should make in order to solve the problem?

We have to store in input field and once we get the data we have to parse it as email address. Right now it seems it is happening by default.



### What alternative solutions did you explore? (Optional)

We can use React/React native library to solve this problem.

**Comment by dylanexpensify** [comment] 2023-11-07 09:45
Got it - @shawnborton @Expensify/design what do we think?

**Comment by dannymcclain** [comment] 2023-11-07 14:43
I kinda think we should do nothing?

Echoing others, I don't really see what we gain by updating this—and "updating" is the key word here to me, I don't think we're "fixing" anything by changing it.

I don't like the idea of trying to discern that the user actually meant to paste two separate emails, that feels way too complicated and error prone. And if we just make it a link, and the user clicks on `Dghg@ry.comDghg@ry.com`... they're just going to be taken to nothing because the URL is invalid?

I think this is a case of "the user made a mistake and needs to fix it, and the system is behaving how I'd expect it to behave if I made that mistake" Just my 2 cents! 🤷‍♂️

**Comment by erquhart** [comment] 2023-11-07 15:20
@mollfpr any chance this counts as my proposal being accepted 😬

**Comment by mollfpr** [comment] 2023-11-07 15:21
@erquhart I'm afraid not, there are no changes you propose and there will be PR to work on.

**Comment by erquhart** [comment] 2023-11-07 15:23
Fair enough - but I will say, that incentivizes contributors to just find a way to get a bugfix proposal accepted, rather than help drive conversations at the product/design level. Not doing something is a really valuable decision. But I digress.

**Comment by NisargDeveloper** [comment] 2023-11-08 16:47
## Proposal

### Please re-state the problem that we are trying to solve in this issue.

When pasting two email it is not showing as link

### What is the root cause of that problem?

It looks like we are not parsing whole email address as an input or developing the regex in such as way that accepts two emails. That is the reason it is causing an issue.

### What changes do you think we should make in order to solve the problem?

We have to store in input field and once we get the data we have to parse it as email address. Right now it seems it is happening by default.



### What alternative solutions did you explore? (Optional)

We can use React/React native library to solve this problem.

**Comment by erquhart** [comment] 2023-11-13 14:35
@mollfpr @dylanexpensify should this be closed, proposals are still coming in

**Comment by mollfpr** [comment] 2023-11-13 14:42
I believe we can close this.

**Closed** 2023-11-14 09:51 UTC
Labels: External, Daily, Help Wanted, Bug
