### ISSUE TITLE
Web - Expense - Default tax rate and first tag item are not highlighted

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#39838] opened 2024-04-08 16:31 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** v1.4.61-0
**Reproducible in staging?:** y
**Reproducible in production?:** n
**Issue reported by:** Applause - Internal Team

## Action Performed:
Precondition: Tag and Tax features should be enabled in the workspace
1. Navigate to a workspace chat
2. Click on '+' > 'Request money' > 'Manual' > Enter amount & click 'Next'
3. Click on 'Show more' > 'Tag' > back navigate > click on 'Tax'

## Expected Result:
Highlight should be applied to the first item on 'Tag' and the default tax option

## Actual Result:
Highlight is not applied to the first item on 'Tag' and the default tax option

## Workaround:
n/a

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

https://github.com/Expensify/App/assets/93399543/43b9f862-d89b-4a0e-9e69-8cad190b3995

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by kbecciv** [comment] 2024-04-08 16:31
We think that this bug might be related to #wave-collect - Release 1

**Comment by godofoutcasts94** [comment] 2024-04-08 16:40
I think it is caused by this [PR](https://github.com/Expensify/App/pull/33927)

**Comment by luacmartins** [comment] 2024-04-08 17:02
I don't think this is a blocker. However we should fix this. cc @teneeto @rezkiy37 @alitoshmatov @MonilBhavsar since it seems to come from https://github.com/Expensify/App/pull/33927. @teneeto can you work on a fix please?

**Comment by MonilBhavsar** [comment] 2024-04-11 18:19
Tax is fixed with TS migration PR. Will fix for tags

**Comment by MonilBhavsar** [comment] 2024-04-12 13:00
When creating a new money request, category and tag are not selected by default. Tax is selected by default.
When clicking on category or tag, none of the item(first or selected) from TagPicker or CategoryPicker is highlighted
When clicking on tax, the default taxRate is highlighted.
So, this is working as expected!

https://github.com/Expensify/App/assets/32012005/b9cb045a-a233-454d-8a3d-0cf2af119721

**Closed by MonilBhavsar** 2024-04-12 13:00 UTC
Labels: Engineering, Daily
