### ISSUE TITLE
PDF - PDF preview icon is not displayed correctly in conversation

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#24430] opened 2023-08-11 14:54 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Open New Expensify app
2. Open any conversation
3. Add a PDF attachment

## Expected Result:
The PDF icon preview in the conversation should display the first page of the entire PDF file in a thumbnail view

## Actual Result:
The preview of the PDF icon in the conversation is displayed incorrectly and only the enlarged part of the first page is visible

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android / native
- [x] Android / Chrome
- [x] iOS / native
- [x] iOS / Safari
- [x] MacOS / Chrome / Safari
- [x] MacOS / Desktop

**Version Number:** 1.3.53.1
 
**Reproducible in staging?:** Yes

**Reproducible in production?:** No

**If this was caught during regression testing, add the test name, ID and link from TestRail:**

**Email or phone of affected tester (no customers):**

**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/78819774/731d0e11-8085-4d67-bf53-72a68efe8fb2

![Bug6161069_Screenshot_2023-08-11-13-34](https://github.com/Expensify/App/assets/78819774/fbee7ced-a2b6-43ae-9abd-6f59f6b27d1f)

**Expensify/Expensify Issue URL:**

**Issue reported by:** Applause - Internal Team

**Slack conversation:**

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by luacmartins** [comment] 2023-08-11 18:06
I can't reproduce this issue. Asking the team.

https://github.com/Expensify/App/assets/22219519/ae831986-ca87-494d-9187-8caa58150e65

**Comment by situchan** [comment] 2023-08-11 18:51
I am also not able to reproduce.
@lanitochka17 can you please share pdf file you tested?

**Comment by luacmartins** [comment] 2023-08-11 19:12
I'm gonna remove the blocker label since we have 2 people unable to reproduce the issue and it being something minor and not breaking any functionality. I'll leave the issue open until Monday, in case we manage to reproduce or find anything new until then.

**Comment by lanitochka17** [comment] 2023-08-12 19:22
Issue reproducible with Build 1.3.53-1
Samsung Galaxy A50/Android11


https://github.com/Expensify/App/assets/78819774/0d7d2fed-e8d6-4c38-89db-72226c3deffb

[password-protected.pdf](https://github.com/Expensify/App/files/12328123/password-protected.pdf)

**Comment by luacmartins** [comment] 2023-08-14 14:44
We had several team members unable to reproduce. I'm gonna close the issue for now.

**Closed by luacmartins** 2023-08-14 14:44 UTC
Labels: Engineering, Daily, Overdue
