### ISSUE TITLE
NewDot randomly hangs

### ISSUE THREAD

**Issue by m-natarajan** [Expensify/App#35741] opened 2024-02-03 01:38 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 
**Reproducible in staging?:** needs reproduction
**Reproducible in production?:** needs reproduction
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** @quinthar 
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1706778055194719

## Action Performed:
1. Login to ND and close the tab
2. Open the tab after 1 hour or so
## Expected Result:
Should load without any issue
## Actual Result:
ND freezes
## Workaround:
unknown
## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence
![image (5)](https://github.com/Expensify/App/assets/38435837/79bd5f5b-2ec5-4e0b-ae15-8da40e3bd7d4)

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by trjExpensify** [comment] 2024-02-05 21:07
Asking [here](https://expensify.slack.com/archives/C036QM0SLJK/p1707160869311329?thread_ts=1707160557.662799&cid=C036QM0SLJK) whether this is a dupe of where the issue report was referenced [here](https://github.com/Expensify/App/issues/35704).

**Comment by hayata-suenaga** [comment] 2024-02-05 22:56
Coming from the Slack thread Tom linked above. I think we can handle this issue over https://github.com/Expensify/App/issues/35741 as you suggested. Please feel free to close this issue. I'll copy the issue description over there.

**Comment by trjExpensify** [comment] 2024-02-05 23:05
Sounds good! This issue was first reported pre-ideal nav being deployed to staging as well. So there's that to keep in mind!

**Closed by trjExpensify** 2024-02-05 23:05 UTC
Labels: Daily, Needs Reproduction, Bug
