### ISSUE TITLE
[HOLD for payment 2023-07-26] [$2000] Cursor position and hover effect on emoji picker doesn't match

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#21217] opened 2023-06-21 14:44 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Open chat
2. Click on emoji icon
3. Search 'face'
4. Hover cursor over the first row of emoji suggestion list

## Expected Result:
Hover effect should be displayed on the hovered emojis

## Actual Result:
Hover effect is applied on the row below the hovered emojis

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [x] MacOS / Chrome / Safari
- [x] MacOS / Desktop

**Version Number:** 1.3.27-6

**Reproducible in staging?:** y

**Reproducible in production?:** y

**If this was caught during regression testing, add the test name, ID and link from TestRail:**

**Email or phone of affected tester (no customers):**

**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/93399543/bd8be649-71d4-44b9-8238-a50b7a7f93d3

https://github.com/Expensify/App/assets/93399543/d0787da0-f315-4cfa-a4d0-537f208065c1

**Expensify/Expensify Issue URL:**

**Issue reported by:** @Natnael-guchima

**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1686746752843639

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~013f5fca26d43bb264</li>
        <li>Upwork Job ID: 1674460563854848000</li>
        <li>Last Price Increase: 2023-07-11</li>
    </ul>
</details>

**Comment by AmjedNazzal** [comment] 2023-06-21 14:44
## Proposal

### Please re-state the problem that we are trying to solve in this issue.

Cursor position and hover effect on emoji picker doesn't match

### What is the root cause of that problem?

The issue stems from the fact that keyExtractor is using only item.code while onHoverIn is using index which causes discrepancy between the hovered emoji and the highlighted emoji.
https://github.com/Expensify/App/blob/8ba223457b9a2e8d02f1c57d7c21fd7f0c523573/src/components/EmojiPicker/EmojiPickerMenu/index.js#L431-L433

### What changes do you think we should make in order to solve the problem?

We need to modify the keyExtractor function to generate unique keys for each item in the FlatList. which should include both the item.code and the index of the item. This ensures that each item has a unique identifier, even if multiple items have the same item.code value.
```javascript
keyExtractor(item, index) {
    return `emoji_picker_${item.code}_${index}`;
}
```

### Result

https://github.com/Expensify/App/assets/74202751/f3adf282-193d-4c72-9749-641e5c4c75c6

**Comment by michaelhaxhiu** [comment] 2023-06-29 16:51
Reproduced easily - https://recordit.co/efc6HT0uFv

**Comment by abdulrahuman5196** [comment] 2023-06-30 15:51
@AmjedNazzal From this proposal, https://github.com/Expensify/App/issues/21217#issuecomment-1600975100
I am not sure of the root cause mentioned

>The issue stems from the fact that keyExtractor is using only item.code while onHoverIn is using index which causes discrepancy between the hovered emoji and the highlighted emoji.

item.code is actually unique, it is the actual emoji which is expected to present only once.

**Comment by AmjedNazzal** [comment] 2023-07-01 18:32
@abdulrahuman5196 yes sure item.code is unique, however we also have items that would have item.spacer initially before typing in search keywords. they take the first 8 items which include the first one but we highlight it with highlightedIndex: 0, the rest of the items out of those 8 might have their index excluded during render when FlatList doesn't update properly as items that have spacer won't have item.code which is why giving an index to the keyExtractor helps here.

If you go to filterEmojis and you change the highlightedIndex in this code this.setState({filteredEmojis: newFilteredEmojiList, headerIndices: [], highlightedIndex: 0}); to let's say 2, you will see that the item with index 2 will be highlighted correctly while the other items in the first 8 will still behave like we see in the issue here.

**Comment by michaelhaxhiu** [comment] 2023-07-03 23:00
@abdulrahuman5196 waiting for your input here.

**Comment by abdulrahuman5196** [comment] 2023-07-04 13:27
@AmjedNazzal I am unable to understand the comment here https://github.com/Expensify/App/issues/21217#issuecomment-1616037685

>FlatList doesn't update properly as items that have spacer won't have item.code which is why giving an index to the keyExtractor helps here.

even spacers have item.code. For example
{"code":"SPACER_0_7","spacer":true},{"code":"SPACER_0_6","spacer":true},{"code":"SPACER_0_5","spacer":true},{"code":"SPACER_0_4","spacer":true},{"code":"SPACER_0_3","spacer":true},{"code":"SPACER_0_2","spacer":true},{"code":"SPACER_0_1","spacer":true}

And another point is it is only reproducible if you search for `face` for the other searches i am unable to reproduce this issue.

**Comment by abdulrahuman5196** [comment] 2023-07-06 13:24
@AmjedNazzal Do you have any response on this? https://github.com/Expensify/App/issues/21217#issuecomment-1620254031

**Comment by abdulrahuman5196** [comment] 2023-07-06 13:26
@michaelhaxhiu Current status.
 @AmjedNazzal proposal change is working, but I am not sure on the root cause mentioned. So not approving as of now. Let me know if we should increase bounty or wait on the reply.

**Comment by AmjedNazzal** [comment] 2023-07-06 13:54
@abdulrahuman5196 I'm still trying to dig deeper into the root cause and will give an update as soon as I have sufficient information on it.

**Comment by AmjedNazzal** [comment] 2023-07-06 18:37
@abdulrahuman5196 Okay, you are correct that the spacer is not the issue. after digging into the issue here are my findings, I will try to explain as best as I can what is going on here so bear with me please because I need to show photos, videos and code: 

So let's start by examining the bug itself, the bug occurs not when we finish typing face but rather as soon as we start typing face. as soon as we type "f" and as long as the next character we type wouldn't make it impossible for the word to end up being face, meaning if we type "f" then "a" then "c" and so on so the first prediction is still face, the bug will occur. 

Now the question is: why "face"? let's answer this question by first looking at the emojis present in the first row of the emojis before and during the typing of "face": 

![emojiDemo](https://github.com/Expensify/App/assets/74202751/b5a1c8dc-48f2-4e97-8b1b-9bc4e5530ba7)


As we can see the emojis in the first row never change when we type "face". now why is that important and what is the relationship between that and keyExtractor? well, as long as we are using item.code, given that the items in the row never changes, it's like the first row never changed before and after filtering the emojis, this is where this piece of code comes into play: 
https://github.com/Expensify/App/blob/01a18f02aeff2c1b7a39c094babba56d3a3c5584/src/components/EmojiPicker/EmojiPickerMenuItem.js#L98-L104

Now this code is trying to make sure things are not rendered multiple times unless something about them changes, so if we log this.props.emoji in the render of EmojiPickerMenuItem component, we would notice that the items in the first row are not getting re-rendered which in turn means the index of these items would still be preserved as their index before filtering. to confirm this, if we go to EmojiPickerMenu component which is the parent of EmojiPickerMenuItem, we can go to renderItem and in the onHoverIn we can log the index and we would notice that the index being logged for these first row emojis remains the same before and after filtering the emojis with "face" search. 

To further examine why all this is happening, let's examine emojis.js: 
<img width="736" alt="emojiCode" src="https://github.com/Expensify/App/assets/74202751/82e651b3-2be1-403a-a2e7-2145349f5060">

Notice that the first 8 items all have "face" as a keyword which is why they remain the same while we search "face", staying in the exact same position since they are already organised in emojis.js that way. this result in the bug as seen in the video below:

https://github.com/Expensify/App/assets/74202751/96112182-0685-4b3e-bdac-a2620a2e14c0

Now let's try something, let's try to remove "face" from the keyword of any of the items in the first row:
<img width="697" alt="emojiCodeEdited" src="https://github.com/Expensify/App/assets/74202751/c5917bd3-6e53-4491-97de-3c0864fc4879">

Here I removed "face" from the keywords of the "grin" emoji and the result is the issue being fixed as I will show in the video below: 


https://github.com/Expensify/App/assets/74202751/452b3f64-61e7-4d33-bda0-0bdeb774ffbc

And so in conclusion, the reason for adding an index to keyExtractor is to add another thing other than item.code which for the first row remains the same usually, by doing this the emojis will have an index that changes ensuring that something about the emojis changed so that EmojiPickerMenuItem re-renders and the correct index is updated.

**Comment by shubham1206agra** [comment] 2023-07-08 09:17
## Proposal
### Please re-state the problem that we are trying to solve in this issue.

Cursor position and hover effect on emoji picker doesn't match
### What is the root cause of that problem?

The root cause is that the `React.memo` logic which incorrectly stops index to be updated after filter for `face` cause relative position of 1st 8 elements are same for `face` search but their indices are different from original.

Here is the current condition:

https://github.com/Expensify/App/blob/60f48175c9e3342ef192d878218820e5ed5a76cd/src/components/EmojiPicker/EmojiPickerMenuItem.js#L98-L104


### What changes do you think we should make in order to solve the problem?

We need to update the `React.memo` condition for `EmojiPickerMenuItem` to take care change of index which happens due to change in `filteredEmojis`.

Update it to following:

```js
export default React.memo(
    EmojiPickerMenuItem,
    (prevProps, nextProps) =>
        prevProps.index === nextProps.index &&prevProps.isHighlighted === nextProps.isHighlighted && prevProps.emoji === nextProps.emoji && prevProps.isUsingKeyboardMovement === nextProps.isUsingKeyboardMovement,
);
```

PS - We now need to pass index as required prop to `EmojiPickerMenuItem` component.

Another optimization we can do is by reducing no of states update happens whenever we hover to different item, i.e., when we change highlightedIndex property of state object by introducing some kind of debounce mechanism (Need to discuss though about this).

### What alternative solutions did you explore? (Optional)

N/A

**Comment by AmjedNazzal** [comment] 2023-07-11 10:52
@abdulrahuman5196 any thoughts on the RC in my latest comment?

**Comment by michaelhaxhiu** [comment] 2023-07-11 20:40
Doubling price to ensure this continues to get interest and/or proposals for resolution. Let's give @abdulrahuman5196 1 more day to review the outstanding comments.

**Comment by abdulrahuman5196** [comment] 2023-07-11 21:24
Yes will review this within today

**Comment by abdulrahuman5196** [comment] 2023-07-12 20:09
Extremely sorry I was unable to do the review as i was caught up on a personal task. But I will complete this issue in first Morning IST.

**Comment by abdulrahuman5196** [comment] 2023-07-13 15:18
@shubham1206agra Your proposal here seems to an alternate version of the accepted proposal. But I don't think its beneficial to add an another variable just for the memo.

**Comment by AmjedNazzal** [comment] 2023-07-13 15:41
@abdulrahuman5196 Thank you :) [proposal](https://github.com/Expensify/App/issues/21217#issuecomment-1600975100) has been updated.

**Comment by marcochavezf** [comment] 2023-07-14 17:16
Thanks @abdulrahuman5196 for the review. The proposal LGTM, assigning @AmjedNazzal 🚀

**Comment by AmjedNazzal** [comment] 2023-07-14 22:12
Thank you! Offer accepted and PR will be ready first thing in the morning :)

**Comment by Natnael-Guchima** [comment] 2023-07-15 05:46
Contributor details
Your Expensify account email: natnaelguchima12@gmail.com
Upwork Profile Link: https://www.upwork.com/freelancers/~0135b3a84ec2709c21

**Comment by AmjedNazzal** [comment] 2023-07-15 09:41
@abdulrahuman5196 @marcochavezf PR is ready for review.

**Comment by abdulrahuman5196** [comment] 2023-07-22 14:11
BZ checklist:

>The PR that introduced the bug has been identified. Link to the PR:
The offending PR has been commented on, pointing out the bug it caused and why, so the author and reviewers can learn from the mistake. Link to comment:
A discussion in #expensify-bugs has been started about whether any other steps should be taken (e.g. updating the PR review checklist) in order to catch this type of bug sooner. Link to discussion:

I don't think we can point to certain PR which caused this issue. This is basically a edge case issue which we hadn't noticed before.


>Determine if we should create a regression test for this bug.
[@abdulrahuman5196] If we decide to create a [regression test](https://github.com/Expensify/App/blob/main/contributingGuides/REGRESSION_TEST_BEST_PRACTICES.md) for the bug, please propose the regression test steps to ensure the same bug will not reach production again.

No. Since its edge case issue.

**Comment by michaelhaxhiu** [comment] 2023-07-26 19:49
@abdulrahuman5196 you get paid via Upwork still right? Not newDot (yet?)

**Comment by abdulrahuman5196** [comment] 2023-07-26 19:58
>you get paid via Upwork still right? Not newDot (yet?)

@michaelhaxhiu Yes. Throught upwork.

And this issue is eligible for speed bonus.

**Comment by michaelhaxhiu** [comment] 2023-07-26 19:59
Oops I missed the speed bonus

**Comment by michaelhaxhiu** [comment] 2023-07-26 20:01
Updated my comment to include 50% raise for contributor & C+

**Comment by Natnael-Guchima** [comment] 2023-07-26 20:07
I have accepted the offer. Thanks @michaelhaxhiu. But it seems like duplicate offers are sent. 

![Screenshot_20230726_230537_Chrome.jpg](https://github.com/Expensify/App/assets/57330233/04af14de-6dc1-4381-8f44-f6402d2e4ff6)

**Comment by michaelhaxhiu** [comment] 2023-07-26 20:07
let me see what happened, I had a feeling it botched my invite to the job.

**Comment by michaelhaxhiu** [comment] 2023-07-26 20:08
thanks for telling me @Natnael-Guchima

**Comment by Natnael-Guchima** [comment] 2023-07-26 20:09
You are welcome 👍

**Comment by michaelhaxhiu** [comment] 2023-07-26 20:10
Retracted 1 of the duplicate offers. I'll pay the second one now.

**Comment by michaelhaxhiu** [comment] 2023-07-26 20:13
all are paid

**Closed by michaelhaxhiu** 2023-07-26 20:13 UTC
Labels: External, Engineering, Daily, Awaiting Payment, Bug

**Comment by Natnael-Guchima** [comment] 2023-07-26 20:15
Great! Thanks @@michaelhaxhiu
