### ISSUE TITLE
[$250] 43871 Search - Merchant is "Expense" in transaction thread after paying someone but empty in Search

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#43905] opened 2024-06-18 14:09 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.85-0
**Reproducible in staging?:** Y
**Reproducible in production?:** Y 
**If this was caught during regression testing, add the test name, ID and link from TestRail:** N/A
**Issue reported by:** Applause - Internal Team

## Action Performed:
1. Go to staging.new.expensify.com
2. Go to 1:1 DM
3. Go to + > Pay someone
4. Pay money to the user
5. Go to transaction thread
6. Wait for "Expense" to autofill in Merchant field
7. Go to Search > Finished

## Expected Result:
The transaction from "Pay someone" will display "Expense" in Merchant field

## Actual Result:
The transaction from "Pay someone" does not display "Expense" in Merchant field. The field is empty

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [x] Android: mWeb Chrome
- [x] iOS: Native
- [x] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details> 

https://github.com/Expensify/App/assets/78819774/63699375-8af6-442a-91fd-af93e7a17df3

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01465570b010c8c460</li>
        <li>Upwork Job ID: 1803090574893598740</li>
        <li>Last Price Increase: 2024-06-25</li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @hoangzinh</details>

**Comment by lanitochka17** [comment] 2024-06-18 14:10
@isabelastisser  FYI I haven't added the External label as I wasn't 100% sure about this issue. Please take a look and add the label if you agree it's a bug and can be handled by external contributors

**Comment by luacmartins** [comment] 2024-06-20 19:23
This is the expected behavior. From the design doc:

>The Merchant and Description columns will show based on the same logic already in use for the expense previews in Inbox. In other words, Merchant will always be shown for workspace expenses, because Merchant is required and triggers violations. Off-workspace, we’ll show Merchant as long as at least one value isn’t “Expense” or “Unknown merchant”, based on existing logic. In all other cases, we’ll show Description as long as at least one expense has one (and if a description is long, we’ll truncate with an ellipsis, just like any other column).

**Comment by luacmartins** [comment] 2024-06-20 19:24
@JmillsExpensify can you confirm that filtering out the default `Expense` merchant is still intended?

**Comment by isabelastisser** [comment] 2024-06-25 17:33
Bump @JmillsExpensify

**Comment by isabelastisser** [comment] 2024-06-26 19:11
I bumped Mills in NewDot.

**Comment by JmillsExpensify** [comment] 2024-06-26 20:44
It was intended, yes.

**Comment by JmillsExpensify** [comment] 2024-06-26 21:20
I think I'm ok if we keep doing that, as `merchant` names are required for all workspace expenses, so this should mostly be a consideration for off-workspace expenses.

**Comment by luacmartins** [comment] 2024-06-27 15:25
Cool, so it seems like we can just close this issue then?

**Comment by isabelastisser** [comment] 2024-06-27 18:27
Closing!

**Closed by isabelastisser** 2024-06-27 18:27 UTC
Labels: External, Daily, Help Wanted, Overdue, Bug
