### ISSUE TITLE
[HOLD #36071][$500] Chat - Chat is partially scrolled down when editing message

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#36254] opened 2024-02-09 15:56 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4-39-0
**Reproducible in staging?:** Y
**Reproducible in production?:** N
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** Applause - Internal Team
**Slack conversation:**

## Action Performed:
1. Go to staging.new.expensify.com
2. Go to FAB > Request money
3. Create a manual request with receipt from any user
4. In 1:1 DM, send two messages
5. Right click on the latest message > Edit message
6. Click close button
7. Right click on the latest message > Edit message

## Expected Result:
The chat is completely scrolled down to reveal the edit composer

## Actual Result:
The chat is partially scrolled down to reveal the edit composer

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details> 

https://github.com/Expensify/App/assets/78819774/3529b476-8c6d-4354-a985-4e5bec44baa8

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01aa6de1a654051f75</li>
        <li>Upwork Job ID: 1756009647894945792</li>
        <li>Last Price Increase: 2024-02-09</li>
    </ul>
</details>

**Comment by lanitochka17** [comment] 2024-02-09 15:57
We think that this bug might be related to #vip-vsp
CC @quinthar

**Comment by tgolen** [comment] 2024-02-09 17:39
I'm going to see if I can get some help to look into this. If this is related to LiveMarkdown, then we should stop looking into it further because all those bugs are being addressed separately in https://github.com/Expensify/App/issues/36071.

**Comment by thienlnam** [comment] 2024-02-09 18:53
https://github.com/Expensify/App/assets/30609178/101ddb18-4d55-483d-916c-276e35145f7c
I wasn't able to reproduce after reverting the Live markdown PR, so going to mark this off and hold onto it for tracking

**Comment by thienlnam** [comment] 2024-02-21 17:45
Not a current bug, but being worked on as part of https://github.com/Expensify/App/issues/36071

**Comment by thienlnam** [comment] 2024-03-05 23:35
Not a current bug, but being worked on as part of https://github.com/Expensify/App/issues/36071

**Comment by BartoszGrajdek** [comment] 2024-04-02 10:19
I believe this is not happening anymore @thienlnam can we get someone to test it on staging & close this issue in case of it being fixed?

**Comment by kavimuru** [comment] 2024-04-03 14:37
@thienlnam Unable to reproduce.

https://github.com/Expensify/App/assets/43996225/22e9c6e4-a7bc-4358-9c7a-dc3d2ff560ef

**Comment by thienlnam** [comment] 2024-04-03 14:58
Sweet - thanks!

**Closed by thienlnam** 2024-04-03 14:58 UTC
Labels: Engineering, Weekly, Overdue, Bug
