### ISSUE TITLE
[$500] Web -  The whisperer of the workspace's invitation message is being displayed for the workspace owner

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#27179] opened 2023-09-11 17:21 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Log in to account A.
2. Create a new workspace.
3. Select account B as a new member of the workspace.
4. Add an invitation message and send an invite.
5. Check if the whisperer is displayed.

## Expected Result:
The whisperer should be displayed only for account B, who is invited.

## Actual Result:
The whisperer of the workspace's invitation message is being displayed for the workspace owner

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [x] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 1.3.67.3
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/93399543/0e4d22b8-6d0f-45ee-8255-f034409c1314

https://github.com/Expensify/App/assets/93399543/7c5925c7-ade1-4a2c-8277-535c004802a1

**Expensify/Expensify Issue URL:**
**Issue reported by:** @tranvantoan-qn
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1694107415659359

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~0182a613d99c2becdb</li>
        <li>Upwork Job ID: 1701284979889573888</li>
        <li>Last Price Increase: 2023-09-11</li>
    </ul>
</details>

**Comment by DylanDylann** [comment] 2023-09-12 04:37
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
The whisperer of the workspace's invitation message is being displayed for the workspace owner

### What is the root cause of that problem?
https://github.com/Expensify/App/blob/52c54f4e39236f2b09ed81a1a080c0eca81084ea/src/pages/home/report/ReportActionItem.js#L543

We don't hide the whisper message if this whisper message doesn't belong to the current user

### What changes do you think we should make in order to solve the problem?
we should display the whisper message if the whisperedToAccountIDs is the current user like this
```
    const isWhisper = whisperedToAccountIDs.length > 0 && ReportUtils.isCurrentUserTheOnlyParticipant(whisperedToAccountIDs); 

```

### What alternative solutions did you explore? (Optional)

**Comment by joekaufmanexpensify** [comment] 2023-09-13 18:16
Triaging this today.

**Comment by joekaufmanexpensify** [comment] 2023-09-14 15:02
@NicMendonca I can take this one as you were incorrectly double assigned!

**Comment by tranvantoan-qn** [comment] 2023-09-14 15:11
Fyi,
I mentioned this issue before, when it was supposed to be fixed in the other report.
https://github.com/Expensify/App/issues/20990#issuecomment-1630694633

**Comment by pecanoro** [comment] 2023-09-15 02:53
I debugged this, when you log out and in again the message disappears so we must be notifying the participants with a pusher event with a message that does not aply.

**Comment by pecanoro** [comment] 2023-09-22 15:29
@joekaufmanexpensify This is done, we only need to pay the bug report.

**Comment by joekaufmanexpensify** [comment] 2023-09-25 02:58
Sounds good! I'll handle that today.

**Comment by joekaufmanexpensify** [comment] 2023-09-25 03:33
@tranvantoan-qn could you please confirm your username in upwork so I can send you an offer?

**Comment by tranvantoan-qn** [comment] 2023-09-25 03:35
@joekaufmanexpensify It's is https://www.upwork.com/freelancers/~012f07ead7068a224c

**Comment by joekaufmanexpensify** [comment] 2023-09-25 03:38
Great! Offer sent for $50!

**Comment by joekaufmanexpensify** [comment] 2023-09-25 03:46
@tranvantoan-qn $50 sent and contract ended!

**Comment by joekaufmanexpensify** [comment] 2023-09-25 03:47
Closing as this is all set!

**Closed by joekaufmanexpensify** 2023-09-25 03:47 UTC
Labels: Daily, Internal, Awaiting Payment, Bug

**Comment by tranvantoan-qn** [comment] 2023-09-25 03:48
Thank you, that was very quick!  :D
