### ISSUE TITLE
[HOLD for payment 2023-07-12] [$1000] Update to USD popup is not dismissed dynamically if currency is updated (connect bank account page is updated dynamically on change in currency)

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#21570] opened 2023-06-26 14:17 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Open the app and login with user A (device 1)
2. Open the app in another device or incognito and login with user A (device 2)
3. Open settings-> workspaces->any specific workspace (select same on both) on both the devices
4. If in settings, currency is USD, change to any other currency using either of the device
5. Click on bank account in device 1 to trigger 'Update to USD' popup
6. From device 2, change currency to USD and observe that popup is not dismissed in device 1
7. Open bank account in device 1, click connect manually, fill in step 1 details (eg details: routing: 210021002, acc no: 1234) and click continue
8. From device 2, again change currency to any other except USD and observe in device 1 that it dynamically updates the screen to display the message

## Expected Result:
App should dynamically dismiss popup 'Update to USD' if currency is updated to USD like it updates connect bank account pages dynamically

## Actual Result:
App does not dynamically dismiss 'Update to USD' if currency is updated to USD

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android / native
- [x] Android / Chrome
- [x] iOS / native
- [x] iOS / Safari
- [x] MacOS / Chrome / Safari
- [x] MacOS / Desktop

**Version Number:** 1.3.30-5
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/93399543/1f4bb0a6-2843-4725-a7a5-f5d174009c34

https://github.com/Expensify/App/assets/93399543/1eb8a275-45d1-4a3a-8dcd-8b0355d5a88b

**Expensify/Expensify Issue URL:**
**Issue reported by:** @dhanashree-sawant
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1687426441178099

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01a8436d652229e8bc</li>
        <li>Upwork Job ID: 1673425700658876416</li>
        <li>Last Price Increase: 2023-06-26</li>
    </ul>
</details>

**Comment by Pujan92** [comment] 2023-06-26 14:35
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
Update to USD popup is not dismissed dynamically if currency is updated (connect bank account page is updated dynamically on change in currency)

### What is the root cause of that problem?
Currently, we don't watch the change for the `policy.outputCurrency` and not closing the CurrencyModal if the currency gets updated to USD in some other tab.

### What changes do you think we should make in order to solve the problem?
We can create a `useEffect` hook where we can add `policy.outputCurrency` in the dependency and inside that we can validate if the CurrencyModal is opened and the new currenct is the USD then just close the opened CurrencyModal.
```
useEffect(() => {
        if(!isCurrencyModalOpen || policy.outputCurrency !== CONST.CURRENCY.USD) {
            return;
        }
        setIsCurrencyModalOpen(false);
    }, [policy.outputCurrency, isCurrencyModalOpen])
```

**Comment by MairaBakali** [comment] 2023-06-26 20:56
### Proposal

### Please re-state the problem that we are trying to solve in this issue.

Problem: The problem in this issue is that the "Update to USD" popup in the WorkspaceInitialPage component is not being dismissed automatically when the currency is updated to USD.

### What is the root cause of that problem?

Root Cause: The root cause of this problem is that the isCurrencyModalOpen state is not being updated when the currency is changed to USD. As a ### **result,** the popup remains visible even after the currency has been successfully updated.

### What changes do you think we should make in order to solve the problem?

Solution: To solve the problem, the following changes can be made:

Locate the confirmCurrencyChangeAndHideModal function in the code.

After successfully updating the workspace currency to USD, update the isCurrencyModalOpen state.

Ensure that the state update occurs within the callback function of setIsCurrencyModalOpen.

By updating the state, the component will re-render and the popup will be hidden.

### What alternative solutions did you explore? (Optional)
Event-based approach to trigger an event whenever the currency is updated. This event can be listened to by the components that need to react to the currency change. When the event is triggered, the components can update their state and dismiss the popup if necessary.
Or Using a global state management library or pattern (such as Redux or Context API) to manage the currency state

**Comment by MairaBakali** [comment] 2023-06-26 21:04
Contributor details
Your Expensify account email: mairabakali5@gmail.com
Upwork Profile Link: [<REPLACE LINK HERE>](https://www.upwork.com/freelancers/~01edd776c2e623db27)

**Comment by Christinadobrzyn** [comment] 2023-06-27 18:30
Sorry, I should not have added the eng label until we choose a PR, removing @amyevans from this!

**Comment by mollfpr** [comment] 2023-06-27 19:46
Thank you all for the proposals!

I'm inclined to control the value `isCurrencyModalOpen` to display the confirm modal instead of adding a condition. So @Pujan92 proposal looks good to me.

🎀 👀 🎀 C+ reviewed!

**Comment by Li357** [comment] 2023-06-28 16:16
@Pujan92 Proposal looks good!

**Comment by Pujan92** [comment] 2023-06-29 13:44
@mollfpr @Li357 [PR](https://github.com/Expensify/App/pull/21873) is ready for review!

**Comment by Christinadobrzyn** [comment] 2023-07-10 23:28
@mollfpr do we need a regression test for this?

**Comment by mollfpr** [comment] 2023-07-12 16:07
> [@mollfpr] The PR that introduced the bug has been identified. Link to the PR:
 [@mollfpr] The offending PR has been commented on, pointing out the bug it caused and why, so the author and reviewers can learn from the mistake. Link to comment:

I don't think this is a bug. Instead, it's an improvement where we can hide the modal if the policy currency is updated to USD.

> [@mollfpr] A discussion in #expensify-bugs has been started about whether any other steps should be taken (e.g. updating the PR review checklist) in order to catch this type of bug sooner. Link to discussion:

The regression step should be enough.

> [@mollfpr] Determine if we should create a regression test for this bug.
 [@mollfpr] If we decide to create a [regression test](https://github.com/Expensify/App/blob/main/contributingGuides/REGRESSION_TEST_BEST_PRACTICES.md) for the bug, please propose the regression test steps to ensure the same bug will not reach production again.

1. Login with two different devices
2. In device A, Goto Settings -> Workspace -> Select any workspace(where default currency is not USD) -> Bank Account 
3. From other device B update the default currency to the USD for the same workspace
4. **Verify** device A's open update currency modal gets closed.
5. 👍 or 👎

**Comment by Christinadobrzyn** [comment] 2023-07-13 20:19
No regressions - ready for payment

- Paid with 50% bonus (PR created June 29th and merged 30th) 
- Payment based on hiring here - https://github.com/Expensify/App/issues/21570#issuecomment-1611895388
- Closed just on Upwork
- Created regression test  https://github.com/Expensify/Expensify/issues/299830
- Closing this GH

**Closed by Christinadobrzyn** 2023-07-13 20:19 UTC
Labels: External, Engineering, Daily, Awaiting Payment, Bug
