### ISSUE TITLE
[$500] Wallet - Wallet page does not update instantly when bank account is added or deleted

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#29767] opened 2023-10-17 13:02 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.3.85-0
**Reproducible in staging?:** Yes
**Reproducible in production?:** Yes
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** Applause - Internal Team
**Slack conversation:**

**Issue found when executing PR** https://github.com/Expensify/App/pull/28316

## Action Performed:
1. Go to staging.new.expensify.com
2. Go to Settings > Wallet > Add payment method > Bank account
3. Proceed with adding a bank account
4. After adding a bank account, in the Wallet page, return to Settings and go back to Wallet
5. Note that now Expensify Wallet shows up
6. Delete the added bank account
7. Return to Settings and go back to Wallet
8. Now it only shows the intro page

## Expected Result:
The Wallet page should update instantly when bank account is added or deleted

## Actual Result:
When the bank account is added, Expensify Wallet does not show up until the Wallet page is revisited.
The same also happens when the bank account is deleted - Wallet introduction page only shows up after revisting the Wallet page

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [x] Android: mWeb Chrome
- [x] iOS: Native
- [x] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos
<details>
<summary>Android: Native</summary>

</details>

<details>
<summary>Android: mWeb Chrome</summary>

</details>

<details>
<summary>iOS: Native</summary>

</details>

<details>
<summary>iOS: mWeb Safari</summary>

</details>

<details>
<summary>MacOS: Chrome / Safari</summary>

 

https://github.com/Expensify/App/assets/78819774/1d73d50b-d7d4-44ae-afd9-5ffc7ac08b2b

</details>

<details>
<summary>MacOS: Desktop</summary>

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~0195a510ee20eb2208</li>
        <li>Upwork Job ID: 1714697645631545344</li>
        <li>Last Price Increase: 2023-10-18</li>
<li>Automatic offers: </li>
<ul>
<li>situchan | Reviewer | 27446140</li>
<li>Pujan92 | Contributor | 27446142</li>
</ul></li>
    </ul>
</details>

**Comment by Pujan92** [comment] 2023-10-17 16:47
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
Wallet page doesn't update the wallet section on add/deletion of an account

### What is the root cause of that problem?
Showing of that section depends on the `userWallet` data which we received from the backend with the `OpenPaymentsPage` api. This api is currently only called on the mount of the component but seems to be missed In the migration [PR](https://github.com/Expensify/App/pull/22412) to consider calling again for [bankAccountList/cardList](https://github.com/Expensify/App/pull/22412/files#diff-339a7f89041cd4c701ecc3eafa4b7919d282a3cbe1b6ff0abd2e31438622ea5bL114).

### What changes do you think we should make in order to solve the problem?
We should add dependencies `bankAccountList` & `cardList` in the `useEffect` for making a call to `openWalletPage`.
https://github.com/Expensify/App/blob/623ea8470629ac72aa1e8e416c50fbb708120775/src/pages/settings/Wallet/WalletPage/WalletPage.js#L248-L250

We can combine two([1](https://github.com/Expensify/App/blob/623ea8470629ac72aa1e8e416c50fbb708120775/src/pages/settings/Wallet/WalletPage/WalletPage.js#L248-L250), [2](https://github.com/Expensify/App/blob/623ea8470629ac72aa1e8e416c50fbb708120775/src/pages/settings/Wallet/WalletPage/WalletPage.js#L261-L266)) blocks to one like below.
```js
    useEffect(() => {
        if (network.isOffline) {
            return;
        }
        PaymentMethods.openWalletPage();
    }, [network.isOffline, bankAccountList, cardList]);
```

**Comment by adelekennedy** [comment] 2023-10-20 16:22
two proposals above for you @situchan

**Comment by adelekennedy** [comment] 2023-10-24 00:54
still pending a review

**Comment by situchan** [comment] 2023-10-24 12:27
I don't think backend should send pusher event with wallet info whenever wallet/bank account/card added/removed.
Assigned engineer will confirm. 🎀 👀 🎀

If no change needed in backend, @Pujan92's [proposal](https://github.com/Expensify/App/issues/29767#issuecomment-1766801187) looks good. This also sync across devices.

**Comment by adelekennedy** [comment] 2023-10-26 16:12
@jasperhuangg please check @Pujan92 [proposal](https://github.com/Expensify/App/issues/29767#issuecomment-1766801187!)

**Comment by situchan** [comment] 2023-10-27 07:20
bank account setup is offline blocked. So it doesn't make sense to have optimistic data

**Comment by situchan** [comment] 2023-10-30 08:56
optimistic data doesn't fix the problem on another device.

**Comment by situchan** [comment] 2023-10-30 08:56
@jasperhuangg will decide if this should be fixed purely on backend or [this proposal](https://github.com/Expensify/App/issues/29767#issuecomment-1766801187) is fine to go.

**Comment by jasperhuangg** [comment] 2023-10-30 23:24
I think updating the useEffect here makes sense, let's move forward with that!

**Comment by jasperhuangg** [comment] 2023-10-31 20:49
@Pujan92 friendly bump!

**Comment by Pujan92** [comment] 2023-11-02 05:37
@situchan @jasperhuangg [PR](https://github.com/Expensify/App/pull/30700) is ready for review!

**Comment by jasperhuangg** [comment] 2023-11-30 00:29
Got it, thanks. I'll look into it when I get the chance!

**Comment by jasperhuangg** [comment] 2024-01-02 04:30
I still haven't had a chance to look into this, but I can probably take another look at this this week.

**Comment by jasperhuangg** [comment] 2024-01-03 10:20
I can't seem to reproduce this bug anymore. Even though we initially weren't sending out a Pusher update for the wallet in Onyx, we send one out when the user finishes the Terms KYC step. I don't think this bug should be happening anymore.

**Closed by jasperhuangg** 2024-01-03 10:20 UTC
Labels: Reviewing, External, Daily, Bug
