### ISSUE TITLE
[HOLD for payment 2023-10-30] Distance IOU - Map preview is not extended to full view on RHP

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#28911] opened 2023-10-05 13:01 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___
**Issue found when executing PR** https://github.com/Expensify/App/pull/26307
## Action Performed:
1. Go to https://staging.new.expensify.com/
2. Go to + > Request money > Distance

## Expected Result:
Map preview is extended to full view on RHP

## Actual Result:
Map preview is not extended to full view on RHP

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android / native
- [x] Android / Chrome
- [x] iOS / native
- [x] iOS / Safari
- [x] MacOS / Chrome / Safari
- [x] MacOS / Desktop
 
**Version Number:** 1.3.78-0

**Reproducible in staging?:** Yes

**Reproducible in production?:** No

**If this was caught during regression testing, add the test name, ID and link from TestRail:**

**Email or phone of affected tester (no customers):**

**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/78819774/40cc133f-4746-480e-bc41-018a3b1c477c

**Expensify/Expensify Issue URL:**

**Issue reported by:** Applause - Internal Team

**Slack conversation:**

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by hayata-suenaga** [comment] 2023-10-05 13:43
tagged PR author (SWM engineer) [here](https://expensify.slack.com/archives/C04878MDF34/p1696513258140859) and C+ [here](https://expensify.slack.com/archives/C02NK2DQWUX/p1696513335060489)

**Comment by situchan** [comment] 2023-10-05 13:52
What will be max height on mobile?

![Simulator Screenshot - iPhone 14 Pro - 2023-10-05 at 19 51 29](https://github.com/Expensify/App/assets/108292595/6744ed1c-32bf-462b-adc8-4445c1eb706d)

**Comment by hayata-suenaga** [comment] 2023-10-05 13:53
@shawnborton since you were involved in the Distance Request screen design,

should the map be stretched out to fill the remaining space or the current heigh is okay?

**Comment by hayata-suenaga** [comment] 2023-10-05 13:54
Please check the hight [here](https://expensify.slack.com/archives/C02NK2DQWUX/p1696514010543219?thread_ts=1696513335.060489&cid=C02NK2DQWUX)

**Comment by s-alves10** [comment] 2023-10-05 13:59
I think min-height: 300, max-height: 500

**Comment by situchan** [comment] 2023-10-05 14:02
I was also thinking to add flex to `contentContainerStyle` but web and native are implemented differently so it won't work on native.
We should confirm if map should be stretched on native as well.

**Comment by mountiny** [comment] 2023-10-05 14:23
This is a new feature/ change and the behaviour is not blocking user so I am removing the blocker label and the original PR author can address the changes based on design feedback. 

Let me know if you disagree about the blocker status. thanks!

**Comment by kosmydel** [comment] 2023-10-05 14:29
> I was also thinking to add flex to `contentContainerStyle` but web and native are implemented differently so it won't work on native. We should confirm if map should be stretched on native as well.

This one solves the issue. Preparing PR with that change.

**Comment by s-alves10** [comment] 2023-10-05 14:31
The mentioned change doesn't solve the issue on natives

**Comment by s-alves10** [comment] 2023-10-05 14:34
For native platforms, we need to change the [DraggableList](https://github.com/Expensify/App/blob/main/src/components/DraggableList/index.native.tsx) as follows

```
    return (
        <DraggableFlatList
            ref={ref}
            contentContainerStyle={styles.flex1}
            containerStyle={styles.flex1}
            ListFooterComponentStyle={styles.flex1}
            // eslint-disable-next-line react/jsx-props-no-spreading
            {...viewProps}
        />
    );
```

**Comment by shawnborton** [comment] 2023-10-05 16:57
>should the map be stretched out to fill the remaining space or the current heigh is okay?

Yes, it should fill the available space. I feel like we have multiple threads/places where we've given feedback about the correct design and behavior of this page. @trjExpensify or @JmillsExpensify can you help shed some light on that here?

**Comment by neil-marcellini** [comment] 2023-10-05 21:21
Reminder: please add distance related issues to the project. It helps us keep track of them.

**Comment by trjExpensify** [comment] 2023-10-05 21:32
>Yes, it should fill the available space. I feel like we have multiple threads/places where we've given feedback about the correct design and behavior of this page. @trjExpensify or @JmillsExpensify can you help shed some light on that here?

It looks like this was a regression found when executing [this PR](https://github.com/Expensify/App/pull/26307), which is linked to the issue that references the main discussion on deciding the design of this: https://expensify.slack.com/archives/C05DWUDHVK7/p1694509495995009

While there are a healthy number of PR reviews on that PR, and it was shared in the thread, there wasn't a review requested from someone on the design team. So I think this is just another reminder to make sure that happens, and this would likely have been caught. CC: @hayata-suenaga

**Comment by neil-marcellini** [comment] 2023-10-05 22:36
@pecanoro I can take this over if you like since it's a distance requests issue.

**Comment by pecanoro** [comment] 2023-10-06 11:17
@neil-marcellini Nah, it's fine, it seems like an easy issue to review.

**Comment by pecanoro** [comment] 2023-10-06 11:18
@neil-marcellini Nah, it's fine, it seems like an easy issue to review.

**Comment by pecanoro** [comment] 2023-10-31 16:54
Ah we can close this one since it was a regression and it was fixed by the original person

**Closed by pecanoro** 2023-10-31 16:54 UTC
Labels: Engineering, Daily, Overdue, Awaiting Payment, Bug
