### ISSUE TITLE
Close account - App freezes on login screen after deleting account

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#26040] opened 2023-08-27 16:51 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Go to settings -> click Security
2. Click Close account -> enter default contact email -> Click close account
3. Try to login (If login happens properly, try same steps for 1-2 more times)

## Expected Result:
It should not freeze app on login and it should work normally

## Actual Result:
App freezes on login screen after deleting account

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [x] iOS / native
- [ ] iOS / Safari
- [ ] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 1.3.57-5

**Reproducible in staging?:** Yes

**Reproducible in production?:** Yes

**If this was caught during regression testing, add the test name, ID and link from TestRail:**

**Email or phone of affected tester (no customers):**

**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/78819774/349d18e1-3365-44fe-9dec-5629aea67130

https://github.com/Expensify/App/assets/78819774/7ca71d7f-2877-43cb-b198-540a464a3ad8

**Expensify/Expensify Issue URL:**

**Issue reported by:**  @DinalJivani

**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1692437358427389

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by b4s36t4** [comment] 2023-08-27 16:57
Feels like dupe of #25793

**Comment by isabelastisser** [comment] 2023-08-28 19:51
Yes, I think it's a dupe! Closing

**Closed by isabelastisser** 2023-08-28 19:51 UTC
Labels: Daily, Bug
