### ISSUE TITLE
Message - Previously sent offline message displayed for new phone user

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#12127] opened 2022-10-25 18:25 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Issue found when executing PR** https://github.com/Expensify/App/pull/11439

## Action Performed:
1. Launch the app and login
2. Turn off your internet connection
3. Create a new chat with a valid email
4. Make sure your chat was created locally
5. Add messages and make sure it looks normal
6. Turn connection back on and make sure nothing changes
7. Turn off your connection in the network tab of the console
8. Create a new chat with an invalid phone number (5555555555555)
9. Make sure your chat was created locally
10. Add messages and make sure it looks normal
11. Turn connection back on and make sure you see errors like the screenshot below

## Expected Result:
Previously sent offline message should not be display for new phone user

## Actual Result:
Previously sent offline message displayed for new phone user

## Workaround:
Unknown

## Platform:

Where is this issue occurring?

- Web
- iOS

**Version Number:** 1.2.19.1

**Reproducible in staging?:** Yes

**Reproducible in production?:** Yes

**Email or phone of affected tester (no customers):** 

**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Notes/Photos/Videos:** Any additional supporting documentation

https://user-images.githubusercontent.com/93399543/197851941-6d101cc7-89c9-4f25-8e31-32c59d766148.mp4
![Bug5792034_Window_-_11439_iPhone MP4__2_](https://user-images.githubusercontent.com/93399543/197852808-bb3da371-c690-40a4-9b31-e8435ef075f5.png)

![Bug5792034_Window_-_11439_iPhone MP4](https://user-images.githubusercontent.com/93399543/197852008-5e774fc6-b542-454e-ae1d-5b8b29372e19.png)
![Web](https://user-images.githubusercontent.com/93399543/197852166-3ac0401f-0459-4b33-8627-06a4c0f113c5.jpg)

**Expensify/Expensify Issue URL:** 

**Issue reported by:** Applause - Internal Team

**Slack conversation:** 

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by Luke9389** [comment] 2022-10-28 20:28
I think this is a dupe of this: https://github.com/Expensify/App/issues/11265#issuecomment-1295101299

**Closed by Luke9389** 2022-10-28 20:28 UTC
Labels: Engineering, Daily
