### ISSUE TITLE
[$500] Web - Report Preview in Report Screen shows up even after deletion of Money Request

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#26627] opened 2023-09-03 21:39 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Use FAB on a ChatReport and generate money request
2. Click on IOUReport to show the IOUReport
3. Use menu to delete the Money Request
4. Come back to ChatReport of Step 1
5. Reload the page.

## Expected Result:
 Report Previous should not show up for a deleted Money Request

## Actual Result:
Report Preview shows up for a deleted Money Request

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [x] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 1.3.62.0
**Reproducible in staging?:** y 
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/93399543/afaf2363-4413-40c6-8500-757f81e7e1ad

https://github.com/Expensify/App/assets/93399543/1dd1c34c-c03a-4322-a3e5-233ac94e822e

**Expensify/Expensify Issue URL:**
**Issue reported by:** @rojiphil
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1693399731169779

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~013c7ff8faa3f9e5a6</li>
        <li>Upwork Job ID: 1704099592925270016</li>
        <li>Last Price Increase: 2023-09-26</li>
    </ul>
</details>

**Comment by rojiphil** [comment] 2023-09-04 00:36
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
Web - Report Preview in Report Screen shows up even after deletion of Money Request

### What is the root cause of that problem?
The problem occurs because we are not clearing the Report Preview on deletion of the IOU Report.

### What changes do you think we should make in order to solve the problem?
This can be solved by clearing up the Report Preview when IOU Report is deleted [at this location](https://github.com/Expensify/App/blob/91ff78db32f0284a73db13b2e2372583d71cb27f/src/libs/actions/IOU.js#L1213) within `successData` of `deleteMoneyRequest` method

The changes can be as follows:
```
        ...(shouldDeleteIOUReport
            ? [
                {
                    onyxMethod: Onyx.METHOD.MERGE,
                    key: `${ONYXKEYS.COLLECTION.REPORT_ACTIONS}${chatReport.reportID}`,
                    value: {
                        [reportPreviewAction.reportActionID]: {
                            pendingAction: null,
                            message: [
                                {
                                    type: 'COMMENT',
                                    html: '',
                                    text: '',
                                    isEdited: true,
                                },
                            ],
                            errors: null,
                        },
                    },
                },
              ]
            : []),        
```

### What alternative solutions did you explore? (Optional)

**Comment by s-alves10** [comment] 2023-09-04 15:24
## Proposal

### Please re-state the problem that we are trying to solve in this issue.

Report preview in report page shows again even after money request is deleted

### What is the root cause of that problem?

When we delete a money request, [deleteMoneyRequest](https://github.com/Expensify/App/blob/d971190c3feb4ea35a0d704aa097919ca13e3958/src/libs/actions/IOU.js#L1074) function is called.
As you can see, if `shouldDeleteIOUReport` is true, we optimistically merge the report preview action with null
https://github.com/Expensify/App/blob/d971190c3feb4ea35a0d704aa097919ca13e3958/src/libs/actions/IOU.js#L1183-L1189

And the `deleteMoneyRequest` API returns `{[reportPreviewActionID]: null}`, too.
The problem is in `Onyx.merge`

Please check the code [here](https://github.com/Expensify/react-native-onyx/blob/d03c2a316db0c9dc8b600f21ef3222cc6a8b1b67/lib/Onyx.js#L1074-L1101)

We remove the keys with null value in `modifiedData` and call `Storage.mergeItem`. This means null values are not updated in storage though they are updated in memory. This is a bug and the root cause of this issue

### What changes do you think we should make in order to solve the problem?

In Onyx.merge function, we merge the changes with existing data and remove all keys with null values, we have to call `Storage.setItem` instead of `Storage.mergeItem`

This works as expected

<details>
    <summary>Result</summary>


</details>


### What alternative solutions did you explore? (Optional)

**Comment by chrispader** [comment] 2023-09-05 14:54
Calling Storage.setItem instead of Storage.mergeItem is definitely not what we want to do here, because we added JSON_PATCH  functionality for SQLite on native [here](https://github.com/Expensify/react-native-onyx/pull/238).

I just discovered the potential problem. I think it’s related to the [idb-keyval PR](https://github.com/Expensify/react-native-onyx/pull/293) by @hannojg. The problem is, that before this PR, on web we just set the modified data with the nullish keys removed already. After this PR, on web we’re using [yet another merge funcationality](https://github.com/Expensify/react-native-onyx/blob/d03c2a316db0c9dc8b600f21ef3222cc6a8b1b67/lib/storage/providers/IDBKeyVal.js#L49-L63), which will not drop the nullish keys, because the modified data with the removed nullish keys will be merged.

I’m gonna open a PR, which fixes this.

**Comment by chrispader** [comment] 2023-09-11 08:07
> I hope you open the PR asap. I think this bug may cause several issues

@s-alves10 just created a PR in Onyx that fixes this issue: https://github.com/Expensify/react-native-onyx/pull/333

**Comment by muttmuure** [comment] 2023-09-19 11:46
I was out last week. Catching up this week

**Comment by muttmuure** [comment] 2023-09-26 08:10
@allroundexperts can you verify if @chrispader's PR fixes this?

**Comment by rojiphil** [comment] 2023-10-03 16:46
@muttmuure 
As I understand, the PR in [this comment ](https://github.com/Expensify/App/issues/26627#issuecomment-1713377956)was supposed to resolve this issue. 
@chrispader @s-alves10 can confirm

**Comment by mvtglobally** [comment] 2023-10-05 03:06
Issue not reproducible during KI retests. (First week)

**Comment by mvtglobally** [comment] 2023-10-12 03:50
Issue not reproducible during KI retests. (Second week)

**Comment by rojiphil** [comment] 2023-10-19 02:10
@allroundexperts @muttmuure 
Can we not close this issue if the issue is fixed already? 
Also, there are other issues dependent on the resolution of this one. Closing this would help us move further on the other issues.

**Comment by miljakljajic** [comment] 2023-10-19 12:26
This hasn't been reproducible for two weeks [following this PR] (https://github.com/Expensify/App/issues/26627#issuecomment-1745357694) - closing. Thank you @rojiphil !

**Closed by miljakljajic** 2023-10-19 12:26 UTC
Labels: Engineering, Weekly, Internal, Overdue, Bug

**Comment by rojiphil** [comment] 2023-10-25 04:25
@muttmuure 
Don't I qualify for a reporter bonus here as I had reported the bug?

**Comment by rojiphil** [comment] 2023-10-25 04:27
@miljakljajic @muttmuure 
Don't I qualify for a reporter bonus here as I had reported the bug?
