### ISSUE TITLE
[$500] PDF - The unlocked PDF file becomes blocked after scrolling right and left

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#32213] opened 2023-11-29 18:42 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.5-3
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** Applause - Internal Team
**Slack conversation:**

## Action Performed:
1. Go to https://staging.new.expensify.com/
2. Log in with any Gmail account.
3. On a conversation, click on the + button in the compose box
4. Click on add attachment
5. Send 2 PDF or images attachments
6. Send a password protected PDF
7. Open the PDF
8. Click on enter password
9. Enter the password (Test12345)
10. Click on the left nav (3 times) arrow to navigate to the previous PDF
11. Click on the right nav arrow to navigate back to the password protected PDF

## Expected Result:
Password protected PDF file is not locked

## Actual Result:
I can see the password protected PDF file when Enter the password, Click on the left nav arrow and Click on the right nav arrow. But when I click on the nav arrow 3 times (you need to have 3 attachments before that PDF file) and go back to the previous PDF - it is locked

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [x] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] Windows: Chrome
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details> 

https://github.com/Expensify/App/assets/78819774/05165e1e-6a44-40a8-a775-8c38e310ab96

[Password_protected Test12345 (1).pdf](https://github.com/Expensify/App/files/13504405/Password_protected.Test12345.1.pdf)

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01ddb14a6e24811e4d</li>
        <li>Upwork Job ID: 1729933932008587264</li>
        <li>Last Price Increase: 2023-12-06</li>
    </ul>
</details>

**Comment by ZhenjaHorbach** [comment] 2023-11-29 19:06
# Proposal
## Please re-state the problem that we are trying to solve in this issue.

PDF - The unlocked PDF file becomes blocked after scrolling right and left

## What is the root cause of that problem?

The main problem related to windowSize which we use for Carousel

https://github.com/Expensify/App/blob/089ddf472cc1fb125d3b1153ede647f2c8737b5d/src/components/Attachments/AttachmentCarousel/index.js#L187-L215


## What changes do you think we should make in order to solve the problem?

We can update windowSize value and make it bigger
Or use a dynamic value equal to a list of elements

## What alternative solutions did you explore? (Optional)
NA

**Comment by unicorndev-727** [comment] 2023-11-29 19:29
I can't reproduce it on dev.

**Comment by ZhenjaHorbach** [comment] 2023-11-29 19:32
> `windowSize={5} ` - this is intentional for performance. I don't think we'll agree with increasing this number.

What about my alternative solution?)
I can write example

**Comment by ZhenjaHorbach** [comment] 2023-11-29 19:37
@aimane-chnaif ↑

**Comment by anup2230** [comment] 2023-11-29 20:05
**Please re-state the problem that we are trying to solve in this issue.**

PDF - The unlocked PDF file becomes blocked after scrolling right and left

**What is the root cause of that problem?**

In the PDF 'render' function in ~/components/PDFView/index.js will check if the PDF is password protected, and then the method will call initiatePasswordChallenge if it is password protected. The method 'initiatePasswordChallenge' will reset the state 'shouldRequestPassword' and the pdf will be hidden until password is entered. [here](https://github.com/Expensify/App/blob/a0b219711080751d6826bb2330ddd85c1641d7bf/src/components/PDFView/index.js#L296C1-L297C1)
```
onPassword={this.initiatePasswordChallenge}
               

```

**What changes do you think we should make in order to solve the problem?**

We can check the state 'shouldRequestPassword' before initiating the password challenge. This would avoid the 'initiatePasswordChallenge' method that will result in the password being needed again.

```
onPassword={() => this.state.shouldInitiatePasswordChallenge ? this.initiatePasswordChallenge() : null}



```

**Comment by mallenexpensify** [comment] 2023-12-05 23:29
@aimane-chnaif , can you please review the above?  Thx

**Comment by mallenexpensify** [comment] 2023-12-09 01:08
This seems like a pretty extreme edge case and, starting next week we're going to be prioritizing fixing bugs on our roadmap, so I have strong feeling we'll want to close this.  I'm going to remove `Help Wanted` for now, the revisit next week

**Comment by mallenexpensify** [comment] 2023-12-19 04:17
Closing for now

**Closed by mallenexpensify** 2023-12-19 04:17 UTC
Labels: External, Daily, Overdue, Bug
