### ISSUE TITLE
[HOLD for payment 2024-12-20] [$250] Expensify Card - Empty card details page can be opened after deactivating card

### ISSUE THREAD

**Issue by vincdargento** [Expensify/App#53560] opened 2024-12-04 14:57 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 9.0.71-0
**Reproducible in staging?:** Yes
**Reproducible in production?:** Yes
**If this was caught on HybridApp, is this reproducible on New Expensify Standalone?:** N/A
**If this was caught during regression testing, add the test name, ID and link from TestRail:** N/A
**Email or phone of affected tester (no customers):** applausetester+khcategory19@applause.expensifail.com
**Issue reported by:** Applause Internal Team

## Action Performed:
Precondition:
- Expensify Card feature is enabled.
- User has assigned themselves a virtual card.

1. Go to staging.new.expensify.com
2. Go to workspace settings > Expensify Card.
3. Click on the virtual card.
4. Click Deactivate card.
5. Deactivate the card.
6. Click browser forward button.

## Expected Result:
Not here page should open because the card is deactivated.

## Actual Result:
Empty card details page opens. It can be edited, which leads to "Hidden" profile in Expensify Card list.

## Workaround:
Unknown

## Platforms:
- [ ] Android: Standalone
- [ ] Android: HybridApp
- [x] Android: mWeb Chrome
- [ ] iOS: Standalone
- [ ] iOS: HybridApp
- [x] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

https://github.com/user-attachments/assets/af6e1e72-3718-48df-bfca-0c79290f3463

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Issue Owner</summary>Current Issue Owner: @</details>
<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~021865065766629964229</li>
        <li>Upwork Job ID: 1865065766629964229</li>
        <li>Last Price Increase: 2024-12-06</li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @alexpensify</details>

**Comment by thelullabyy** [comment] 2024-12-04 15:29
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
Expensify Card - Empty card details page can be opened after deactivating card

### What is the root cause of that problem?
We haven't restricted access to the detail card page if a user tries to view an invalid card

### What changes do you think we should make in order to solve the problem?
In WorkspaceExpensifyCardDetailsPage we need to implement the same logic as we did in WorkspaceCompanyCardDetailsPage

https://github.com/Expensify/App/blob/d839c4dd34e81b6d5d19f1a5708d0d256cdcfa1c/src/pages/workspace/companyCards/WorkspaceCompanyCardDetailsPage.tsx#L75-L77

```
    if (!card && !isLoadingOnyxValue(cardsListMetadata)) {
        return <NotFoundPage />;
    }
```

### What specific scenarios should we cover in automated tests to prevent reintroducing this issue in the future?


### What alternative solutions did you explore? (Optional)

**Reminder:** Please use plain English, be brief and avoid jargon. Feel free to use images, charts or pseudo-code if necessary. Do not post large multi-line diffs or write walls of text. Do not create PRs unless you have been hired for this job.

**Comment by DylanDylann** [comment] 2024-12-05 03:19
@mountiny This seems like a lack of when implementing this feature. Could I take over this one?

**Comment by mountiny** [comment] 2024-12-05 12:31
yeah if the cardId is not locally we should show not found page

**Comment by DylanDylann** [comment] 2024-12-06 03:43
@thelullabyy's [proposal](https://github.com/Expensify/App/issues/53560#issuecomment-2517784127) looks good to me

@twilight2294 I noticed that you mentioned another bug in your proposal: "When deactivating the card, the card is removed before the modal is dismissed. It caused the empty value to be displayed in a moment". But I believe that we shouldn't add `pendingAction` to the deactivating card action because this action follows Offline Pattern C

@thelullabyy Let's also resolve this additional bug in your PR. One potential approach that we already used widely in our codebase is to deactivate the card after the modal is closed completely by using runAfterInteractions. 

🎀 👀 🎀 C+ Reviewed

**Comment by DylanDylann** [comment] 2024-12-06 04:16
@twilight2294 I just checked again
- Company Card: Applying offline pattern B
- Expensify Card: Applying offline pattern C

It isn't the same.

**Comment by mountiny** [comment] 2024-12-06 16:08
@twilight2294 No, the company cards is a simple update in our database hence pattern B but for anything related to Expensify card we also need to communication with thirdparty api and that can fail for unknown reasons hence we only want users to be able to do take these critical actions online

**Comment by DylanDylann** [comment] 2024-12-10 09:40
@thelullabyy Any update?

**Comment by thelullabyy** [comment] 2024-12-10 10:49
@DylanDylann I created a draft PR, I just need to test and finish all videos before opening to review.

**Comment by alexpensify** [comment] 2024-12-20 22:50
@thelullabyy - I'm having trouble finding you in Upwork. Please apply for the job in Upwork, and I can complete the payment process. Thanks!

**Comment by DylanDylann** [comment] 2024-12-23 02:53
# BugZero Checklist:

- [ ] **[Contributor]** Classify the bug:

<details>
<summary>Bug classification</summary>


Source of bug:
  - [ ] 1a. Result of the original design (eg. a case wasn't considered)
  - [ ] 1b. Mistake during implementation
  - [ ] 1c. Backend bug
  - [ ] 1z. Other:

Where bug was reported:
  - [ ] 2a. Reported on production (eg. bug slipped through the normal regression and PR testing process on staging)
  - [ ] 2b. Reported on staging (eg. found during regression or PR testing)
  - [ ] 2d. Reported on a PR
  - [ ] 2z. Other:

Who reported the bug:
  - [ ] 3a. Expensify user
  - [ ] 3b. Expensify employee
  - [ ] 3c. Contributor
  - [ ] 3d. QA
  - [ ] 3z. Other:

</details>

- [ ] **[Contributor]** The offending PR has been commented on, pointing out the bug it caused and why, so the author and reviewers can learn from the mistake.

    Link to comment:

- [ ] **[Contributor]** If the regression was CRITICAL (e.g. interrupts a core flow) A discussion in [#expensify-open-source](https://app.slack.com/client/E047TPA624F/C01GTK53T8Q) has been started about whether any other steps should be taken (e.g. updating the PR review checklist) in order to catch this type of bug sooner.

    Link to discussion:

- [ ] **[Contributor]** If it was decided to create a regression test for the bug, please propose the [regression test](https://github.com/Expensify/App/blob/main/contributingGuides/REGRESSION_TEST_BEST_PRACTICES.md) steps using the template below to ensure the same bug will not reach production again.

<details>
<summary>Regression Test Proposal Template</summary>


- [ ] **[BugZero Assignee]** Create a GH issue for creating/updating the regression test once above steps have been agreed upon.

    Link to issue:

## Regression Test Proposal
### Precondition:


-

### Test:


1.

Do we agree 👍 or 👎


</details>

**Comment by thelullabyy** [comment] 2024-12-24 04:38
> @thelullabyy - I'm having trouble finding you in Upwork. Please apply for the job in Upwork, and I can complete the payment process. Thanks!

@alexpensify Applied!

**Comment by alexpensify** [comment] 2024-12-24 05:42
Thanks, I've sent offers to @thelullabyy and @DylanDylann in Upwork. Please accept and I can complete the payment process.

**Comment by DylanDylann** [comment] 2024-12-25 14:23
@alexpensify Accepted, ty!

**Comment by alexpensify** [comment] 2024-12-25 19:15
All set and closing, everyone has been paid via Upwork. Since I'm OOO until January 3, I'm going to close and work on the QA step when I'm back online.

**Closed by alexpensify** 2024-12-25 19:15 UTC
Labels: External, Daily, Help Wanted, Awaiting Payment, Bug
