### ISSUE TITLE
[HOLD for payment 2024-06-20] [HOLD for payment 2024-06-18] [$250] mWeb - IOU - Creating a split expense with IQD currency & 10 digit amount unexpected error shown

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#42084] opened 2024-05-13 14:58 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.73
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**If this was caught during regression testing, add the test name, ID and link from TestRail:** https://expensify.testrail.io/index.php?/tests/view/4554848
**Issue reported by:** Applause - Internal Team

## Action Performed:
1. Go to https://staging.new.expensify.com/home
2. Tap on a new 1:1 report
3. Create a split expense with IQD currency and 10 digit amount 2000000000

## Expected Result:
If 10 digit amount are not allowed, user must not be allowed to create expense. If user allowed to create expense, then unexpected error must not be shown

## Actual Result:
Creating a split expense with IQD currency & 10 digit amount unexpected error displayed

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [x] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [ ] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details> 

https://github.com/Expensify/App/assets/78819774/287f9037-60f8-4819-8868-1f2f7289b00c

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01894cc4ac52447ce7</li>
        <li>Upwork Job ID: 1790841039070965760</li>
        <li>Last Price Increase: 2024-05-15</li>
<li>Automatic offers: </li>
<ul>
<li>ikevin127 | Reviewer | 0</li>
<li>bernhardoj | Contributor | 0</li>
</ul></li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @trjExpensify</details>

**Comment by lanitochka17** [comment] 2024-05-13 14:58
@trjExpensify  FYI I haven't added the External label as I wasn't 100% sure about this issue. Please take a look and add the label if you agree it's a bug and can be handled by external contributors

**Comment by lanitochka17** [comment] 2024-05-13 14:58
We think that this bug might be related to #vip-split

**Comment by bernhardoj** [comment] 2024-05-14 03:25
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
Creating a new expense with a 10 digit gives an unexpected error.

### What is the root cause of that problem?
This issue not only happens with IQD currency but with any currency that has no decimals, such as JPY. We are validating the amount length here,
https://github.com/Expensify/App/blob/f8a30a156159c2dd564da73ebbbeb5f05ffa3cb5/src/libs/MoneyRequestUtils.ts#L58-L64

and the default max length is 10.
https://github.com/Expensify/App/blob/f8a30a156159c2dd564da73ebbbeb5f05ffa3cb5/src/CONST.ts#L1557

We calculate the amount length using `calculateAmountLength` function.

https://github.com/Expensify/App/blob/f8a30a156159c2dd564da73ebbbeb5f05ffa3cb5/src/libs/MoneyRequestUtils.ts#L43-L46

In `calculateAmountLength`, we multiply the amount with 10 to the power of the number of decimals allowed on a currency. So, if the currency allows 2 decimals, then it will be multiplied by 100, that's why we can only input 8 digit length for currency like USD. But if the currency doesn't allow decimal, such as IQD, then we can input 10 digit length.

However, [in the BE, all amounts are in cent](https://github.com/Expensify/App/pull/5243/files#r708725517), so the 10-digit length will be 12 digit length, and BE will return an error for it.

The wrong length calculation logic is changed in https://github.com/Expensify/App/pull/34849

### What changes do you think we should make in order to solve the problem?

Always multiply the amount with 100 to convert it to cents instead of depending on the decimals allowed on a currency, just like what we did for the first time in https://github.com/Expensify/App/pull/5243.

**Comment by trjExpensify** [comment] 2024-05-15 20:25
Whoops, slipped through the cracks. I agree there should be front-end validation to match here.

**Comment by ikevin127** [comment] 2024-05-16 00:33
♻️ Reviewing proposal.

**Comment by ikevin127** [comment] 2024-05-16 22:15
@bernhardoj's [proposal](https://github.com/Expensify/App/issues/42084#issuecomment-2109204723) makes sense to me. The root cause was identified, together with the offending PR and the proposed solution looks solid.

🎀👀🎀 C+ reviewed

**Comment by ikevin127** [comment] 2024-05-20 18:30
**`Overdue` notes:** Awaiting CME review / assignment for the [selected proposal](https://github.com/Expensify/App/issues/42084#issuecomment-2116295139).

**Comment by trjExpensify** [comment] 2024-05-20 23:06
Marco is out for a few days. @mountiny mind doing the honours [on this](https://github.com/Expensify/App/issues/42084#issuecomment-2109204723)?

**Comment by mountiny** [comment] 2024-05-21 14:31
Thanks, the analysis makes sense to me too

**Comment by bernhardoj** [comment] 2024-05-21 15:03
PR is ready

cc: @ikevin127

**Comment by ikevin127** [comment] 2024-05-30 21:19
No payment required here yet since the first PR was reverted in issue https://github.com/Expensify/App/issues/42780.
We're working on a re-work of the initial PR which is open (https://github.com/Expensify/App/pull/42815) and we're actively discussing the way to go!

**Comment by trjExpensify** [comment] 2024-05-31 10:53
Sounds good!

**Comment by ikevin127** [comment] 2024-06-04 17:35
@trjExpensify False alarm, the initial PR was reverted - now we're working on the second one.

**Comment by trjExpensify** [comment] 2024-06-05 23:50
Cool, removing the payment hold. Thanks for the heads up!

**Comment by ikevin127** [comment] 2024-06-07 19:36
2nd PR was just merged, hopefully this will do without any other regressions🤞

**Comment by ikevin127** [comment] 2024-06-15 20:30
* [x]  [@ikevin127] The PR that introduced the bug has been identified. Link to the PR: [#34849](https://github.com/Expensify/App/pull/34849).
* [x]  [@ikevin127] The offending PR has been commented on, pointing out the bug it caused and why, so the author and reviewers can learn from the mistake. Link to comment: [#34849 (comment)](https://github.com/Expensify/App/pull/34849/files#r1641439048).
* [x]  [@ikevin127] A discussion in #expensify-bugs has been started about whether any other steps should be taken (e.g. updating the PR review checklist) in order to catch this type of bug sooner. Link to discussion: **N/A**
* [x]  [@ikevin127] Determine if we should create a regression test for this bug.
* [x]  [@ikevin127] If we decide to create a regression test for the bug, please propose the [regression test](https://github.com/Expensify/App/blob/main/contributingGuides/REGRESSION_TEST_BEST_PRACTICES.md) steps to ensure the same bug will not reach production again.

## Regression Test Proposal

1. Open the FAB menu.
2. Create a **Split expense** and select the `IQD` currency.
3. Verify that we cannot enter an amount with more than 8 digits. (e.g. 12345678)
4. Submit the **Split expense**.
5. Verify that the expense request is submitted successfully without any errors being shown.

Do we agree 👍 or 👎.

**Comment by ikevin127** [comment] 2024-06-15 20:34
⚠️ Not sure why the automation added the second HOLD date her, since the PR was deployed **4 days ago** according to https://github.com/Expensify/App/pull/42815#issuecomment-2161773521 -> therefore the **[HOLD for payment 2024-06-18]** is the correct payment date.

**Summary:**
- 1st PR was reverted due to regression -> **no compensation due** for contributor / reviewer
- 2nd PR was deployed to production **4 days ago** -> **compensation due** for contributor / reviewer on **2024-06-18**

cc @trjExpensify

**Comment by ikevin127** [comment] 2024-06-18 18:16
⚠️ Not sure why the automation added the second HOLD date her, since the PR was deployed **4 days ago** according to https://github.com/Expensify/App/pull/42815#issuecomment-2161773521 -> therefore the **[HOLD for payment 2024-06-18]** is the correct payment date.

**Summary:**
- 1st PR was reverted due to regression -> **no compensation due** for contributor / reviewer
- 2nd PR was deployed to production **4 days ago** -> **compensation due** for contributor / reviewer on **2024-06-18**

cc @trjExpensify

**Comment by trjExpensify** [comment] 2024-06-19 09:18
Not sure where 4 days ago is coming from, but if we're talking about these two PRs ([1](https://github.com/Expensify/App/pull/42815), [2](https://github.com/Expensify/App/pull/42426)), I agree it's due for payment now. 

Confirming that as follows: 

- $125 to @bernhardoj for the fix (minus 50% for the regression that caused the revert)
- $125 to @ikevin127 for the C+ review (minus 50% for the regression that caused the revert)

Let me know if I'm missing something, and I'll settle up with you both once confirmed.

**Comment by trjExpensify** [comment] 2024-06-19 09:37
Cool, settled up!

**Closed by trjExpensify** 2024-06-19 09:37 UTC
Labels: External, Daily, Awaiting Payment, Bug
