### ISSUE TITLE
[$1000] Red dot appears on Assign task to user which is not registered in expensify

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#19820] opened 2023-05-30 14:49 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Click on + button
2. Click on Assign task option
3. Enter title and click on Next button
4. Click on Assignee
5. Search for the user which is not registered yet in Expensify  (ex. c.dobrzyn+Fake+1@gmail.com)
6. Assign task to that user
7. Click on Confirm task

## Expected Result:
 Should be able to assign task

## Actual Result:
Red dot appears on Assign task to user which is not registered in Expensify

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android / native
- [x] Android / Chrome
- [x] iOS / native
- [x] iOS / Safari
- [x] MacOS / Chrome / Safari
- [x] MacOS / Desktop

**Version Number:** 1.3.20.1

**Reproducible in staging?:** Yes

**Reproducible in production?:** Yes

**If this was caught during regression testing, add the test name, ID and link from TestRail:**

**Email or phone of affected tester (no customers):**

**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/93399543/fa6b4f92-9c1e-486b-ad0e-ef352429430f

https://github.com/Expensify/App/assets/93399543/4b83da4c-52de-49e3-9c49-06a0c8ea2f37

**Expensify/Expensify Issue URL:**

**Issue reported by:** @gadhiyamanan

**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1685165330262289

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~016da1603637d87c19</li>
        <li>Upwork Job ID: 1663568431671189504</li>
        <li>Last Price Increase: 2023-05-30</li>
    </ul>
</details>

**Comment by Christinadobrzyn** [comment] 2023-05-30 15:29
- I can reproduce this
- I don't know if this is a `Bug` (that you can't assign a task to a new Expensify user) or a `Feature Request `(that you should be able to assign a task to a new Expensify user) - asking for more clarity in [Slack](https://expensify.slack.com/archives/C049HHMV9SM/p1685460554445929?thread_ts=1685165330.262289&cid=C049HHMV9SM)
- I think this can be external?

**Comment by mkarkachov** [comment] 2023-05-30 19:15
It looks like a Feature Request. If userA assigns task to userB who has not signed to platform yet -> userB should get email with invitation, has to accept it and after successful login `brickRoadIndicator` should change status

**Comment by Christinadobrzyn** [comment] 2023-05-30 21:42
> Can we please confirm this bug on slack first?

@parasharrajat good call - reaching out to the team to find out if this is a bug or feature request. Internal slack chat for my personal tracking here - https://expensify.slack.com/archives/C04QEB4MJEQ/p1685482928860259

**Comment by Christinadobrzyn** [comment] 2023-05-30 22:52
- Sounds like this is expected behaviour- you need to have an Expensify account to be assigned a task. So this is not a bug. 
- I think we can close this for now or at least it needs to be fixed internally (I removed the External label)
 
@JmillsExpensify or @thienlnam (since you're on the design doc) would you like us to keep this open and work on it as a feature request?

**Comment by JavSFDev** [comment] 2023-06-01 17:44
Hello. I can do this.

**Comment by JavSFDev** [comment] 2023-06-01 17:44
Hello. I can do this.

**Comment by thienlnam** [comment] 2023-06-01 23:06
Looks like this is a dupe of https://github.com/Expensify/App/issues/19678 so going to close this in favor of that one

**Closed by thienlnam** 2023-06-01 23:06 UTC
Labels: Daily, Internal, Help Wanted, Bug
