### ISSUE TITLE
Web - Split bill RHN doesn't close after member has been removed from a workspace

### ISSUE THREAD

**Issue by izarutskaya** [Expensify/App#26262] opened 2023-08-29 21:35 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Create a workspace on account A and invite account B into that workspace
2. On account B go to the announce room and click on the plus icon > split bill > enter an amount and click next
3. Go to account A and remove account B from the workspace
4. Observe account B

## Expected Result:
The split bill RHN should close as soon as account B has been removed from the workspace

## Actual Result:
The RHN doesn't close on account B when account B has been removed from the workspace

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [x] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** v1.3.58-3

**Reproducible in staging?:** Y

**Reproducible in production?:** Y

**If this was caught during regression testing, add the test name, ID and link from TestRail:**

**Email or phone of affected tester (no customers):**

**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/115492554/24dc72e2-c3c3-47ca-9725-4d8a77b3d74d

https://github.com/Expensify/App/assets/115492554/a043341e-0503-4e0f-8cc1-728a10b3f1f0

**Expensify/Expensify Issue URL:**

**Issue reported by:** @Nathan-Mulugeta

**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1692706711050379

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by DylanDylann** [comment] 2023-08-30 03:25
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
Split bill RHN doesn't close after member has been removed from a workspace

### What is the root cause of that problem?
https://github.com/Expensify/App/blob/93bde2010f145bbb97c54c06922f0ea52453958c/src/pages/iou/steps/NewRequestAmountPage.js#L107-L112

In NewRequestAmountPage we will dismiss modal when the user don't have permission to comment like this report

<img width="945" alt="Screenshot 2023-08-30 at 10 10 30" src="https://github.com/Expensify/App/assets/141406735/0f4e4cd0-9cf3-42bf-8803-b671c2ce69cb">

But with the announce room, when the user is removed from workspace the announce room will disappear totally and we don't have logic to dismiss modal in this case

In MoneyRequestConfirmPage, we also don't have logic to dismiss modal in above cases
### What changes do you think we should make in order to solve the problem?
1. In NewRequestAmountPage
https://github.com/Expensify/App/blob/93bde2010f145bbb97c54c06922f0ea52453958c/src/pages/iou/steps/NewRequestAmountPage.js#L107-L112
Update the condition to dismiss modal when the report is deleted like this
```
useEffect(() => {
        if ((report.reportID || report.isLoadingReportActions) && !ReportUtils.shouldDisableWriteActions(report)) {
            return;
        }
        Navigation.dismissModal(reportID);
    }, [report, reportID]);
```

2. In MoneyRequestConfirmPage, add the same logic like we did in NewRequestAmountPage
```
useEffect(() => {
        if ((props.report.reportID || props.report.isLoadingReportActions) && !ReportUtils.shouldDisableWriteActions(props.report)) {
            return;
        }
        
        Navigation.dismissModal(reportID);
    }, [props.report, reportID]);
```
### Result
My proposal works well for 4 cases
1. Remove user when user is requesting money in amount step (at workspace room)
2. Remove user when user are requesting money in confirm step (at workspace room)
3. Remove user when user are splitting bill in amount step (at announce room)
4. Remove user when user are splitting bill in confirm step (at announce room)


https://github.com/Expensify/App/assets/141406735/802dc129-a2ca-491e-ab89-832eb8678212

**Comment by stephanieelliott** [comment] 2023-09-01 20:32
This is the expected behavior, you can split a bill without a shared workspace. We would expect the RHP to persist on user B's account until they manually closed it.

**Closed by stephanieelliott** 2023-09-01 20:32 UTC
Labels: Daily, Overdue, Bug
