### ISSUE TITLE
Web - group details page shows "hidden" for newly added mails

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#21829] opened 2023-06-28 17:31 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. go to '+' -> new group
2. select any already chatted ( from recent ) and a new mail address ( that is not shown on the list)< I,e add a new friend not shown there. >
ADD NEW MAILS NOT PHONE NUMBERS.
3. Now create group , on group page , click on header name
4. now it lists all members . Notice that on newly added member, "hidden" text is shown at bottom.

## Expected Result:
On newly added member, "hidden" text should not be shown at bottom.

## Actual Result:
Group details page shows "hidden" for newly added mails

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [x] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 1.3.33-3
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/93399543/445edfd9-a555-4ec9-9d03-23d0e5d79539

https://github.com/Expensify/App/assets/93399543/c4d19594-4ea6-40a6-b98a-17960c8cde2d

**Expensify/Expensify Issue URL:**
**Issue reported by:** @ashimsharma10
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1687865402707309

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by manjesh-yadav** [comment] 2023-06-28 18:02
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
group details page shows "hidden" for newly added mails 
### What is the root cause of that problem?

When a newly added email user does  not have a login, we shows the text `hidden`

https://github.com/Expensify/App/blob/d1a743c3d6ed9ff3767e6da93daf9a604c45a781/src/pages/ReportParticipantsPage.js#L62


### What changes do you think we should make in order to solve the problem?

We can remove it with an empty string or anything else which is suitable

**Comment by alrizkipascar** [comment] 2023-06-28 21:15
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
In the group participants list, the text 'Hidden' is shown for newly created users.

### What is the root cause of that problem?
I think the code is not the main problem as you can see from the screenshot below, the data have inconsistence structure for some reason, is this a backend problem?

#### Good Data
![good data 1](https://github.com/Expensify/App/assets/87491167/fd54035c-46ea-481c-a626-7ec17b1622f2)
![good data 2](https://github.com/Expensify/App/assets/87491167/fdf512b4-ca7a-44f0-ba18-fe0c500f7456)

#### Bad Data

![bad data 1](https://github.com/Expensify/App/assets/87491167/d7db1d5d-40fa-4bec-86cf-e9a1b201467b)
![bad data 2](https://github.com/Expensify/App/assets/87491167/bddeeb87-080a-44e1-8c43-e3906693e427)


### What changes do you think we should make in order to solve the problem?

- If this a backend problem, then the structure data need to be fix by team.

### What alternative solutions did you explore? (Optional)
If this problem only worried about the "Hidden" status/email and my assumption about backend is wrong, then I have a "bandage" solution for this.
Since in the `getAllParticipants` method use `props.report` data in this page and report have `report.participants` data, and `report.participantAccountIDs` as an iterative or mapping we can match the index from both of the data by changing the code

from this:
https://github.com/Expensify/App/blob/ecfcd8325d73851499f00399b14b8ae8e7f55f90/src/pages/ReportParticipantsPage.js#L57

https://github.com/Expensify/App/blob/ecfcd8325d73851499f00399b14b8ae8e7f55f90/src/pages/ReportParticipantsPage.js#L62

to this:
`const {participantAccountIDs,participants} = report;`
`const userLogin = Str.removeSMSDomain(userPersonalDetail.login || '') || participants[index];`

result:
![result](https://github.com/Expensify/App/assets/87491167/eee71647-9875-4c12-9845-d1125a2f6510)


but the problem doesn't end here IMO, because if you clicked for the user detail and the structure data doesn't complete it will showing the user like this:

#### bad user
![bad user](https://github.com/Expensify/App/assets/87491167/0b5c4391-a330-4b70-8197-ad33b46cc50b)

#### good user (good data)
![good user](https://github.com/Expensify/App/assets/87491167/7610aba3-10b2-4b07-aff1-b3c843b04498)

**Comment by trjExpensify** [comment] 2023-06-30 17:11
I have a feeling this is expected behaviour. 

I've looped in a coupla' of peeps who worked on this [here](https://expensify.slack.com/archives/C049HHMV9SM/p1688145026211989?thread_ts=1687865928.997579&cid=C049HHMV9SM).

**Comment by trjExpensify** [comment] 2023-06-30 17:45
As suspected, this is expected behaviour. I'm going to close this issue out!

**Closed by trjExpensify** 2023-06-30 17:45 UTC
Labels: Daily, Bug
