### ISSUE TITLE
Mweb – Split Bill – Emoji doesn't open on click

### ISSUE THREAD

**Issue by kavimuru** [Expensify/App#22666] opened 2023-07-11 18:19 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1.	Click on the plus (+) sign to initiate the "Split Bill" process.
2.	Navigate to the "Split Bill" section.
3.	Enter the desired amount.
4.	Click on "Next."
5.	Select the members involved in the bill splitting.
6.	Click on "Next."
7.	Proceed to the Owe chat conversation with User B, with whom the bill has been split, and exchange some messages with emojis.
8.	Return to the chat conversation with User A, who initiated the bill splitting, and exchange some messages with emojis.
9.	Notice that after a few messages in User A's chat, the emoji stops opening when clicked.
## Expected Result: 
The emoji should open and display properly in all cases.
## Actual Result:
 In the case of split bills, the emoji is not opening when clicked.
## Workaround:
Can the user still use Expensify without this being fixed? Have you informed them of the workaround?

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [x] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [ ] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 
**Reproducible in staging?:** Needs reproduction (applause can't reproduce)
**Reproducible in production?:** needs reproduction
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/43996225/58b913bd-0583-4fa1-a08a-cf8ed40fa2cc

**Expensify/Expensify Issue URL:**
**Issue reported by:** @usmantariq96
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1686548484252989

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by dylanexpensify** [comment] 2023-07-12 08:41
Reviewing today!

**Comment by dylanexpensify** [comment] 2023-07-13 12:26
Cannot reproduce @usmantariq96 can you confirm if this is occurring on the latest build?

**Comment by dylanexpensify** [comment] 2023-07-14 11:56
closing, feel free to reopen if you can repro @usmantariq96 cc @kavimuru

**Closed by dylanexpensify** 2023-07-14 11:56 UTC
Labels: Daily, Needs Reproduction, Bug

**Comment by usmantariq96** [comment] 2023-07-14 12:53
@dylanexpensify thanks for consideration, now it is not reproducable.
