### ISSUE TITLE
Mac / Safari - Chat - Add Attachment - Scroll bars are not needed but place for them is left and not recolored

### ISSUE THREAD

**Issue by kavimuru** [Expensify/App#13115] opened 2022-11-29 01:20 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Go to https://staging.new.expensify.com/
and login
2. Open any chat and select '+' and Add attachment
3. Select any small size JPG image

## Expected Result:
Scroll bars and space for them are not displayed on preview screen if they are not needed or colored to match the background

## Actual Result:
Scroll bars are not needed but place for them is left for JPG files and not recolored.
In the case of a small PDF file, this issue does not exist.

## Workaround:
unknown

## Platform:

Where is this issue occurring?

- Web - Safari

**Version Number:** 1.2.33-1
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**Email or phone of affected tester (no customers):** 
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** 
![Bug5839954_scroll-bar-spaces](https://user-images.githubusercontent.com/43996225/204414923-1aa3bdf9-7359-45e9-b3df-1246ca9f6f1b.png)

https://user-images.githubusercontent.com/43996225/204414926-3463c444-aac8-490c-9964-3319b542d10f.mp4

**Expensify/Expensify Issue URL:** 
**Issue reported by:** Applause internal team
**Slack conversation:** 

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by alex-mechler** [comment] 2022-11-30 18:02
I can't seem to reproduce this. @kavimuru can you share the file that was used to reproduce this?

**Comment by marcaaron** [comment] 2022-12-01 04:58
also what OS and version of Safari? Could always be an old Safari bug that is resolved now (couldn't repro either on my end)

**Comment by kavimuru** [comment] 2022-12-02 18:07
@marcaaron @alex-mechler macOS 10.15.7 Safari Version 15.6.1 (15613.3.9.1.16, 15613) and the image used
![3500](https://user-images.githubusercontent.com/43996225/205357604-e6532080-ae41-4347-a264-9e79903f8d15.jpg)

**Comment by alex-mechler** [comment] 2022-12-02 18:10
On MacOS 13.0.1 and Safari 16.1 I can't get this to reproduce with that image 
<img width="1319" alt="image" src="https://user-images.githubusercontent.com/22447860/205358222-c1739185-01d2-4e5f-9b46-4abbf720881c.png">

**Comment by marcaaron** [comment] 2022-12-02 18:24
>macOS 10.15.7 Safari Version 15.6.1

That's relatively recent. I am kinda split on whether this should be fixed or not. Feels low priority but could still be looked into.

**Comment by MitchExpensify** [comment] 2022-12-02 20:00
Also unable to reproduce on Safari 16.1

<img width="1591" alt="image" src="https://user-images.githubusercontent.com/36425901/205375883-a94eb25a-75fd-4158-9e6f-b6018b7aff5f.png">

Agree with @marcaaron that this feels low priority. I think we should ignore

**Comment by kavimuru** [comment] 2022-12-04 23:05
@MitchExpensify @marcaaron This issue was able to reproduce by Rajat Parashar https://expensify.slack.com/archives/C049HHMV9SM/p1670020543640669 too.

**Comment by MitchExpensify** [comment] 2022-12-05 15:46
Still unable to repro on Chrome or Safari, versions v1.2.36-1 and v1.2.35-0

**Comment by MitchExpensify** [comment] 2022-12-08 18:51
Closing as unable to identify reliable reproduction steps

**Closed by MitchExpensify** 2022-12-08 18:51 UTC
Labels: Daily, Overdue, Bug
