### ISSUE TITLE
DEV: Console error on clicking remove button

### ISSUE THREAD

**Issue by kavimuru** [Expensify/App#21758] opened 2023-06-27 21:47 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Go to dev on web chrome
2. Create a new workspace and invite few members
3. Then select any user and click on remove button
4. Notice console error - Invalid attempt to destructure non-iterable instance
## Expected Result: 
No Console error on clicking remove button
## Actual Result: 
Console error on clicking remove button

## Workaround:
Can the user still use Expensify without this being fixed? Have you informed them of the workaround?

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [x] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:**
**Reproducible in staging?:** DEV
**Reproducible in production?:**
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/43996225/a59c2685-8a48-455a-84e2-c89b97cf8b50

**Expensify/Expensify Issue URL:**
**Issue reported by:** @priya-zha
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1687759580383579

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by maddylewis** [comment] 2023-06-28 18:14
@kavimuru - i see you added the `Needs Reproduction` label to this one. were you able to reproduce this on your end?

**Comment by jeet-dhandha** [comment] 2023-06-29 16:48
Reproduction:

<img width="910" alt="Screenshot 2023-06-29 at 10 17 44 PM" src="https://github.com/Expensify/App/assets/78416198/f446d300-6c5a-4d4f-a0af-782284d16460">

**Comment by gadhiyamanan** [comment] 2023-06-29 16:52
This is dupe of https://github.com/Expensify/App/issues/21833
Both issue have same root cause

**Comment by kavimuru** [comment] 2023-06-30 12:10
@maddylewis This is happening only in Dev environment. I won't be able to test.

**Comment by situchan** [comment] 2023-06-30 12:11
This is already being worked and can be closed

**Comment by maddylewis** [comment] 2023-07-05 13:34
https://github.com/Expensify/App/issues/21758#issuecomment-1614564282

**Closed by maddylewis** 2023-07-05 13:34 UTC
Labels: Daily, Needs Reproduction, Overdue, Bug
