### ISSUE TITLE
Track expense- Error after uploading receipt, preview turns to skeleton after dismissing error

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#48112] opened 2024-08-27 18:47 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:**  9.0.25-2
**Reproducible in staging?:** Y
**Reproducible in production?:**  Y
**If this was caught during regression testing, add the test name, ID and link from TestRail:** N/A
https://expensify.testrail.io/index.php?/tests/view/4894701
**Email or phone of affected tester (no customers):** applausetester+kh050806@applause.expensifail.com
**Issue reported by:** Applause - Internal Team

## Action Performed:
1. Go to staging.new.expensify.com
2. Go to self DM
3. Click + > Track expense > Manual
4. Submit a track manual expense
5. Go to transaction thread
6. Click on the receipt placeholder
7. Upload a receipt

## Expected Result:
Receipt will be uploaded successfully

## Actual Result:
Error shows up after uploading a receipt. Expense preview turns to skeleton after dismissing the error

`The receipt didn't upload.Download the file or dismiss this error and lose it.`

<img width="1313" alt="Snagit 2021 2024-09-03 12 56 20" src="https://github.com/user-attachments/assets/2379ebca-5725-4e50-b6ed-870c86323de7">

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [x] Android: mWeb Chrome
- [x] iOS: Native
- [x] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details> 

https://github.com/user-attachments/assets/f8160b7a-1f94-46e6-b29f-81473b75a8d4

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by lanitochka17** [comment] 2024-08-27 18:48
@Christinadobrzyn  FYI I haven't added the External label as I wasn't 100% sure about this issue. Please take a look and add the label if you agree it's a bug and can be handled by external contributors

**Comment by Christinadobrzyn** [comment] 2024-08-28 17:34
I can reproduce it - thanks for investigating @abzokhattab - adding Internal and waiting for a volunteer

**Comment by Christinadobrzyn** [comment] 2024-08-30 19:54
waiting for a volunteer

**Comment by Christinadobrzyn** [comment] 2024-09-03 18:49
Checking to see if this is still happening - yes this is still happening. Asking for a volunteer in Slack. https://expensify.slack.com/archives/C06ML6X0W9L/p1725389361361729

**Comment by Christinadobrzyn** [comment] 2024-09-03 18:50
Heads up: I'm going to be ooo 9/4-9/10. Since this is internal, I think it's okay to move it to weekly while I'm gone and continue looking for a volunteer when I'm back.

**Comment by Christinadobrzyn** [comment] 2024-09-03 22:00
discussing here https://expensify.slack.com/archives/C07CACYRTJS/p1725400751821889?thread_ts=1725389858.667469&cid=C07CACYRTJS

**Comment by Christinadobrzyn** [comment] 2024-09-03 22:00
I'm going to be ooo 9/4 - 9/10 so adding a BZ teammate to watch that Slack thread and determine next steps - I'm not sure if we want to fix this. If yes, we need a volunteer

**Comment by Christinadobrzyn** [comment] 2024-09-03 23:20
Moved the discussion to the collect room - https://expensify.slack.com/archives/C036QM0SLJK/p1725405582578229

**Comment by VictoriaExpensify** [comment] 2024-09-06 06:03
Hey @Christinadobrzyn - I'm not sure I understand what's happening with this one. If this is able to be reproduced, what kind of additional investigation do we need from a volunteer? Or are we just trying to get a volunteer to fix this? In that case, I think we can post this in #Open_Source.

I think this can wait until you get back

**Comment by VictoriaExpensify** [comment] 2024-09-09 09:41
No responses to the Slack thread. Not OD

**Comment by trjExpensify** [comment] 2024-09-09 15:22
This is a track expense flow, not a bottom up track > submit flow. I'm moving it to #vip-vsb. I suspect it's something to do with being an unreported expense in the selfDM and the `ReplaceReceipt` auth command is expecting to find a reportID for canEdit or something. It's throwing [here](https://github.com/Expensify/Auth/blob/1f9a0e60e90d73a23b4c4a7fda4734f0370169aa/auth/command/ReplaceReceipt.cpp#L40C1-L43C6) I think. 

@thienlnam might be good to look at this!

**Comment by thienlnam** [comment] 2024-09-09 22:36
Ah yeah, nice find - I'll fix this

**Comment by Christinadobrzyn** [comment] 2024-09-11 18:06
looking at the PR - I think this is fixed - https://github.com/Expensify/Auth/pull/12422

@thienlnam did you have a C+ help you with this or can we just close this as complete?

**Comment by thienlnam** [comment] 2024-09-11 18:13
Just me, we can close it

**Closed by thienlnam** 2024-09-11 18:13 UTC
Labels: Daily, Internal, Bug, Hot Pick
