### ISSUE TITLE
[$500] Web -Split bill- Square appears over checkmark when deselect participant and than use keyboard arrow

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#32400] opened 2023-12-02 15:06 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.7-0
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** Applause - Internal Team
**Slack conversation:**

## Action Performed:
1. Navigate to http://staging.new.expensify.com/
2. Open Group DM
3. Click on "+" near message composer
4. Click on "Split bill"
5. Insert amount
6. Click "Next"
7. Click with mouse on any member to deselect it
8. Use the keyboard up/down arrows to go through the list

## Expected Result:
There should be no visual errors while scrolling through members list

## Actual Result:
White square appears over checkmark when deselect participant and than use keyboard arrow

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

https://github.com/Expensify/App/assets/93399543/8f934c01-e9bd-42dc-9ea6-f24e31415cbf

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~017a562fd6464d4101</li>
        <li>Upwork Job ID: 1730966804029255680</li>
        <li>Last Price Increase: 2023-12-23</li>
    </ul>
</details>

**Comment by tanmai-kms** [comment] 2023-12-02 17:06
Contributor details
Your Expensify account email: duytan.learning.agu@gmail.com
Upwork Profile Link: https://www.upwork.com/freelancers/~01b376159894de44f5

**Comment by dylanexpensify** [comment] 2023-12-05 19:57
@eVoloshchak to review proposals!

**Comment by dylanexpensify** [comment] 2023-12-11 09:26
@eVoloshchak to review proposals!

**Comment by dylanexpensify** [comment] 2023-12-13 08:48
Bump @eVoloshchak

**Comment by eVoloshchak** [comment] 2023-12-13 22:17
The issue turned out to be more complex, we have 3 distinct problems with the participants list

1. Blue outline appears over the checkmark when selecting participant and then using a keyboard arrow
2. Select a participant using arrow keys, press "Space" to add a participant. Notice the wrong participant is selected (@dragnoir has described this problem in their [proposal](https://github.com/Expensify/App/issues/32400#issuecomment-1845149459))
3. Whether you can select a user by pressing "Space" is not consistent. It's possible only if you click on the list of participants (which defeats the purpose of keyboard navigation), and if you click outside the list, it stops working

https://github.com/Expensify/App/assets/9059945/d29ffc9f-e157-465b-b574-98c913e727e3

A proposal to resolve all of the issues above would be ideal, we'd fix the whole keyboard navigation flow on this page

**Comment by dylanexpensify** [comment] 2023-12-20 09:31
bump @eVoloshchak for reply

**Comment by eVoloshchak** [comment] 2023-12-22 22:36
> Keyboard navigation should be out of the scope of this issue. The issue here is simply about the focus outline of the circle. There is an issue https://github.com/Expensify/App/issues/21392 that is trying to fix the inconsistent keyboard navigation

Thank you for linking that issue, @bernhardoj 

I think we should proceed with @suneox's [proposal](https://github.com/Expensify/App/issues/32400#issuecomment-1837220034). This is the most straightforward approach. @tanmai-kms's [proposal](https://github.com/Expensify/App/issues/32400#issuecomment-1837201990) is similar, but applies the same styles to all pressables, which isn't ideal: we shouldn't disable the ability to highlight **any** pressable, as that would break the keyboard navigation

🎀👀🎀 C+ reviewed!

**Comment by dragnoir** [comment] 2023-12-23 09:29
@eVoloshchak the style is not fixing the issue and it's wrong for accessibility. Removing outline is just a workaround.
Also when the outline is removed and the user keep using keyboard, he will be distracted because the current focused element is not what the UI display as I mentioned in my proposal. 
The style.noSelect will just cause another bug.

**Comment by tanmai-kms** [comment] 2023-12-24 05:57
@eVoloshchak @bernhardoj My proposal was just based on existing styles. If it's related to accessibility why the `input` and `select` were set border to none for `:focus-visible`? That makes inconsistent if we don't set for pressable component.
<img width="611" alt="Screenshot 2023-12-24 at 12 22 16 PM" src="https://github.com/Expensify/App/assets/83775864/37645d8e-5908-4a5c-8855-4df4614a8e0d">

**Comment by eVoloshchak** [comment] 2024-01-03 21:51
Will post a review on this tomorrow

**Comment by dylanexpensify** [comment] 2024-01-09 12:18
@eVoloshchak mind reviewing @suneox updated proposal?

**Comment by dylanexpensify** [comment] 2024-01-15 13:39
bump @eVoloshchak

**Comment by dylanexpensify** [comment] 2024-01-17 09:28
@shubham1206agra mind giving us an update?

**Comment by shubham1206agra** [comment] 2024-01-17 09:49
@dylanexpensify @AndrewGable You can review the above comment and assign here.

**Comment by shubham1206agra** [comment] 2024-01-17 12:10
> > @suneox proposal does work, but the focus remains on the checkmark pressable (but outline is not pressent),
> 
> @shubham1206agra have you tested [my proposal](https://github.com/Expensify/App/issues/32400#issuecomment-1837220034) with 'tabIndex'? to fix style and handle focus avoid tab to `SelectCircle`
> 
> > which will have the problem @dragnoir mentioned.
> > Select a participant using arrow keys, press "Space" to add a participant. Notice the wrong participant is selected
> 

@suneox Let me clarify here. Your proposal removed the blue square, but this will make user believe that there is no focus there and will be misleading.

> I have missed this information so I just double-checked on the latest main this issue is another issue related to `OptionRow` handling select items by using `Space` or `Enter`.

Can you point to the GH for this?

> > we can go with @bernhardoj's [proposal](https://github.com/Expensify/App/issues/32400#issuecomment-1837197816)
> 
> If we only fix the style it will not cover the problem has mentioned

The problem defined is very clear here.
> There should be no visual errors while scrolling through members list

> 
> > Select a participant using arrow keys, press "Space" to add a participant. Notice the wrong participant is selected
> 
> Does it include fixing the issue selected item by `Space/Enter`?

Not really. But your proposal will create even more problems as we try to remove focus entirely, and remove the blue box, and it will confuse / misdirect the user which I think we don't want.

**Comment by dylanexpensify** [comment] 2024-01-23 13:24
@AndrewGable do you agree with [this](https://github.com/Expensify/App/issues/32400#issuecomment-1895450314)

**Comment by dylanexpensify** [comment] 2024-01-23 13:26
posted internally also on flow

**Comment by bernhardoj** [comment] 2024-01-24 05:02
PR is ready

cc: @shubham1206agra

**Comment by dragnoir** [comment] 2024-01-25 12:47
@shubham1206agra the PR submitted still have the issue I mentioned.

I think my proposal is better, it remove the issue.

> @dragnoir solution works in this case but will have a problem with keyboard selection and we can still see misaligned blue box if we try to go with keyboard (tab/shift+tab).

Also about keyboard keyboard (tab/shift+tab), pls check here https://expensify.slack.com/archives/C01GTK53T8Q/p1668604822482759 we are not supporting this type of navigation I guess

**Comment by dylanexpensify** [comment] 2024-01-29 11:38
@bernhardoj @shubham1206agra what's holding up our merge?

**Comment by shubham1206agra** [comment] 2024-01-29 13:04
@dylanexpensify I am OOO right now. Will review the PR tomorrow.

**Comment by shubham1206agra** [comment] 2024-01-30 12:28
> @shubham1206agra thank you for your reply.
> 
> Please test the PR when you have time, if you do this:
> 
>     * Select or deselect an option with mouse
> 
>     * navigate with arrow key top or down
> 
>     * click on space or enter
> 
> 
> then the wrong option will be actioned (selected/deselected) not the one highlighted.

Highlighted by what?
I think there are 2 different highlighting occurring at the same time, which is causing these problems. I will open up a discussion for the same later.

**Comment by dylanexpensify** [comment] 2024-02-07 10:30
@bernhardoj @shubham1206agra can we get an update please

**Comment by shubham1206agra** [comment] 2024-02-07 10:35
PR is merged already

**Comment by dragnoir** [comment] 2024-02-09 10:00
@shubham1206agra as I mentioned before, the issue is not fixed, the silution implemented I think it's just a workaround.

Please check the video demonstrationg the issue after the PR.


https://github.com/Expensify/App/assets/12425932/da790e07-b06e-4e4a-a9ad-8a97848e2c71

Currently just the focus style is changed from square to round. But when you navigate and try to select an element from the list, the action happen the the previous element where the focus is not where the new element selected

@dylanexpensify As you see from the video and the screenshot below, when I navigate to (2) and I click on space or enter on the keyboard, the item that should be selected/deselected is (2) not (1) as happening now.

![image](https://github.com/Expensify/App/assets/12425932/0cbc1921-3cdc-41f7-870c-1c07297e291b)

**Comment by dragnoir** [comment] 2024-02-09 10:20
@shubham1206agra we already support this type of navigation in other component like search, LHN, .... also keeping the focus actif on an item, for the user, means the ability to interact with it with keyboard or with other navigation tools. I think just changing the style to round and don't care about what element is trully focused it very bad UX and not a fix for such an app.

**Comment by dylanexpensify** [comment] 2024-02-13 20:20
@shubham1206agra mind confirming where we're at

**Comment by dylanexpensify** [comment] 2024-02-21 10:45
Got it - will do today!

**Comment by dylanexpensify** [comment] 2024-02-28 08:52
Yes!

Payment summary:
- Contributor: @bernhardoj $500
- Contributor+: @shubham1206agra $500

Please request/apply!

**Comment by dylanexpensify** [comment] 2024-02-28 08:59
I know - in the works!

**Comment by dylanexpensify** [comment] 2024-02-28 10:45
Offers sent!

**Comment by dylanexpensify** [comment] 2024-02-28 13:11
done!

**Closed by dylanexpensify** 2024-02-28 13:11 UTC
Labels: Reviewing, Engineering, Weekly, Internal, Bug
