### ISSUE TITLE
Empty space above thread chat

### ISSUE THREAD

**Issue by kavimuru** [Expensify/App#21514] opened 2023-06-25 14:40 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:

1.  Go to any chat and start a thread
2.  Keep on entering messages until scroll bar appears
3.  Now scroll to the top of the page

## Expected Result:
No empty space above the first message

## Actual Result:
Empty space equal to half of the page visible at top

## Workaround:
Can the user still use Expensify without this being fixed? Have you informed them of the workaround?

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [x] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 1.3.23-5
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/43996225/bf42157a-ea21-447e-b1a1-45f70f86a926

https://github.com/Expensify/App/assets/43996225/3d96e3ac-75ba-47ea-8013-cee253c504ad

**Expensify/Expensify Issue URL:**
**Issue reported by:** @allroundexperts 
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1687020871684899

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by bernhardoj** [comment] 2023-06-26 04:19
It's a dupe of this https://github.com/Expensify/App/issues/21493

**Comment by kadiealexander** [comment] 2023-06-26 05:26
Agreed, closing as a dupe.

**Closed by kadiealexander** 2023-06-26 05:26 UTC
Labels: Daily, Bug
