### ISSUE TITLE
[$500] IOU - IOU report preview in LHN does not show the latest amount when the amount is updated

### ISSUE THREAD

**Issue by izarutskaya** [Expensify/App#31840] opened 2023-11-24 16:29 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** v1.4.3-2
**Reproducible in staging?:** Y
**Reproducible in production?:** N
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** Applause-Internal Team
**Slack conversation:** @

## Action Performed:
1. Navigate to staging.new.expensify.com.
2. Go to 1:1 DM.
3. Click + > Request money.
4. Create a manual request.
5. Click on the IOU preview twice to open IOU details page.
6. Click Amount and change the amount.
7. Save the new amount.

## Expected Result:
IOU report preview in LHN shows the updates amount.

## Actual Result:
IOU report preview in LHN still shows the old amount.

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [x] Android: mWeb Chrome
- [x] iOS: Native
- [x] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

Uploading Bug6289651_1700842392605!20231124_214203.mp4…

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01924a32b5337a7203</li>
        <li>Upwork Job ID: 1728088534416240640</li>
        <li>Last Price Increase: 2023-11-24</li>
    </ul>
</details>

**Comment by mountiny** [comment] 2023-11-24 16:31
might be related to the LHN PR too cc @koko57 https://github.com/Expensify/App/pull/31061

**Comment by koko57** [comment] 2023-11-24 17:19
@mountiny isn't it something with the optimistic update like here: https://github.com/Expensify/App/issues/30042#issuecomment-1801460957 https://github.com/Expensify/App/issues/30042#issuecomment-1802396093

**Comment by jgd8542** [comment] 2023-11-24 17:29
The video for this issue seems to have had a problem uploading.

Is this where the issue occurs? I orignally requested $3 then changed it to for. Should the panel "Jdunn7008's Workspace" have the same text as the "$4.00 request" panel?

![Screen Shot 2023-11-24 at 9 26 04 AM](https://github.com/Expensify/App/assets/67573303/c8058a05-4e79-422a-8d01-e9cf64df2309)

**Comment by koko57** [comment] 2023-11-24 17:48
@mountiny I will take care of this one. Or maybe should we revert this PR?

**Comment by s-alves10** [comment] 2023-11-24 17:56
## Proposal

### Please re-state the problem that we are trying to solve in this issue.

LHN for IOU report shows the local currency when a different currency is requested

### What is the root cause of that problem?

This is a regression of the PR https://github.com/Expensify/App/pull/31061

https://github.com/Expensify/App/blob/e355608a9e0ee107abe06f610031c80f74ed8fa8/src/libs/OptionsListUtils.js#L386-L388
As you can see above, we get report preview message from the last report action. We should get from the corresponding transaction

This is the root cause

### What changes do you think we should make in order to solve the problem?

Updating the above code to
```
    if (!isPreviewMessageForParentChatReport && reportAction.originalMessage && reportAction.originalMessage.IOUTransactionID) {
        const transaction = lodashGet(allTransactions, `${ONYXKEYS.COLLECTION.TRANSACTION}${reportAction.originalMessage.IOUTransactionID}`, {});
        const amount = Math.abs(TransactionUtils.getAmount(transaction, ReportUtils.isExpenseReport(report)));
```
solves the issue



### What alternative solutions did you explore? (Optional)

**Comment by luacmartins** [comment] 2023-11-24 21:23
I'm gonna close this as a dupe of https://github.com/Expensify/App/issues/31838, since they have the same root cause and we have a fix for that one.

**Closed** 2023-11-24 21:23 UTC
Labels: Reviewing, External, Engineering, Weekly, Help Wanted, Bug
