### ISSUE TITLE
[HOLD for payment 2024-08-09] [CRITICAL] [Advanced Approval Workflows] Divide workflows page into three sections

### ISSUE THREAD

**Issue by tgolen** [Expensify/App#45949] opened 2024-07-22 20:08 UTC
Coming from: [#wave-control: advanced approval + workflows polish](https://docs.google.com/open?id=12X-hsNo9BBRcG5NSS1JzyjWD1w-iM0uciQJSD1i5mZc#bookmark=id.k6c7enb7w88k)

<details><summary>Issue Owner</summary>Current Issue Owner: @Guccio163</details>

**Comment by Guccio163** [comment] 2024-07-23 09:26
Hi! I'm Wiktor Gut from Software Mansion, an expert agency, I talked with @blazejkustra and I'd like to work on this issue!

**Comment by jayeshmangwani** [comment] 2024-07-29 10:46
@tgolen I have been assigned to the PR for this issue. May I get access to the [document](https://docs.google.com/open?id=12X-hsNo9BBRcG5NSS1JzyjWD1w-iM0uciQJSD1i5mZc#bookmark=id.k6c7enb7w88k) please?

**Comment by tgolen** [comment] 2024-07-29 15:02
Sure! Can you let me know what email address I can share it with?

**Comment by jayeshmangwani** [comment] 2024-07-29 15:33
> Sure! Can you let me know what email address I can share it with?

jayeshmangwani@gmail.com

**Comment by tgolen** [comment] 2024-07-29 15:39
OK, shared!

**Comment by jayeshmangwani** [comment] 2024-08-12 16:41
@tgolen Can you please assign me to this issue and also assign a BZ member to add the payment summary?

**Comment by tgolen** [comment] 2024-08-12 18:04
@Christinadobrzyn Could you please help pay @jayeshmangwani for a C+ review of the PR?

**Comment by Christinadobrzyn** [comment] 2024-08-12 18:27
Yes! Payouts due:

- [ ] Contributor+: $250 @jayeshmangwani (Upwork offer - https://www.upwork.com/nx/wm/offer/103496779)

**Comment by jayeshmangwani** [comment] 2024-08-12 18:28
Hi @Christinadobrzyn, I am receiving payment from NewDot.

**Comment by Christinadobrzyn** [comment] 2024-08-13 15:44
Perfect! Thanks @jayeshmangwani - I think this is good to close unless we should have a regression test?

**Comment by jayeshmangwani** [comment] 2024-08-13 18:20
> we should have a regression test?

I don't think we need a regression test here since it's just a feature enhancement.

**Comment by Christinadobrzyn** [comment] 2024-08-13 19:11
Sounds good! Closing this!

**Closed by Christinadobrzyn** 2024-08-13 19:11 UTC
Labels: Engineering, Daily, Task, Awaiting Payment, Bug

**Comment by jayeshmangwani** [comment] 2024-08-15 18:15
Requested on ND as per https://github.com/Expensify/App/issues/45949#issuecomment-2284656434

**Comment by JmillsExpensify** [comment] 2024-08-21 10:57
$250 approved for @jayeshmangwani
