### ISSUE TITLE
[$500] Chat - The line breaks won't clear/appear on the chat

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#35417] opened 2024-01-30 17:19 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.33.0
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** Applause- Internal Team
**Slack conversation:**

**Issue found when executing PR** https://github.com/Expensify/App/pull/35300

## Action Performed:
1. Open a chat
2. Insert a few line breaks into the composer
3. Send a photo attachment

## Expected Result:
Line breaks should clear/appear on the chat.

## Actual Result:
If you send an attachment, the line breaks won't clear/appear on the chat.

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [x] Android: mWeb Chrome
- [x] iOS: Native
- [x] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

https://github.com/Expensify/App/assets/93399543/6e6527e6-aad0-4fe9-80c8-0e299903d711

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01c9ba0e8e79576abf</li>
        <li>Upwork Job ID: 1752381112662769664</li>
        <li>Last Price Increase: 2024-02-13</li>
    </ul>
</details>

**Comment by kbecciv** [comment] 2024-01-30 17:20
We think that this bug might be related to #vip-vsb
CC @quinthar

**Comment by FitseTLT** [comment] 2024-01-30 17:34
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
The line breaks won't clear/appear on the chat

### What is the root cause of that problem?
We are early returning after length is zero after trimming the comment 
https://github.com/Expensify/App/blob/a44e80436248c8ec39a9e28d618364181a0df829/src/pages/home/report/ReportActionCompose/ComposerWithSuggestions/ComposerWithSuggestions.js#L336-L342
### What changes do you think we should make in order to solve the problem?

We should take the clearing code before the early return
```
        updateComment('');

```
### What alternative solutions did you explore? (Optional)

**Comment by slafortune** [comment] 2024-01-31 20:27
I think that the "attachment" should always be attached to the message - with one send.  If someone want to send something separate, they would simply add only an attachement.

**Comment by FitseTLT** [comment] 2024-02-01 12:34
> @slafortune I think it can make users confuse. Currently, clicking on "Send" button in the attachment modal (see below image) will send the attached with a message that the user has typed, so it can make user confuse that: why I just click on "Send" attachment, but the text message is also sent? ![image](https://private-user-images.githubusercontent.com/129500732/301495365-b92ce753-dbab-40a3-bd05-abcd1b0bf3ef.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDY3OTA3NzYsIm5iZiI6MTcwNjc5MDQ3NiwicGF0aCI6Ii8xMjk1MDA3MzIvMzAxNDk1MzY1LWI5MmNlNzUzLWRiYWItNDBhMy1iZDA1LWFiY2QxYjBiZjNlZi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMjAxJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDIwMVQxMjI3NTZaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0yNGNjZjRjNjU3OWM0ODI0Njc3MDc0OTJiYjkzNTJmYzY1ZmYxY2U0ZGU5ZTZjNTg2MzVmZmJkYWRkZDJmMTg2JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.-UeYJuLu7dsTq_8E_Em_ZWah58slbe86U8OqWF0Q8dI)

Although I can't give the link to the discussion (difficult to find it), I remember I have come up with a discussion that this `sending message with attachement` is indeed the expected behaviour. NOw because the default behaviour is send the message reset it when attachement is sent and in this case the message is all but a bunch of new lines it is not considered as a message b/c we trim it and it will end up with an empty string. So what we can do is reset the message although nothing is to be sent expect the attachement as I am recommending in my [propsal](https://github.com/Expensify/App/issues/35417#issuecomment-1917554334) otherwise we leave it as it is and close this issue.

**Comment by FitseTLT** [comment] 2024-02-05 09:11
> @FitseTLT, I think your solution will cause a regression. If we reach the character limit and send an attachment the composer will get clear.

@thesahindia We can separate the condition and clear only when the trimmed comment is empty to deal with this current issue
https://github.com/Expensify/App/blob/a44e80436248c8ec39a9e28d618364181a0df829/src/pages/home/report/ReportActionCompose/ComposerWithSuggestions/ComposerWithSuggestions.js#L339-L342
```
if (commentLength > CONST.MAX_COMMENT_LENGTH) {
            return '';
        }

        debouncedSaveReportComment.cancel();

        updateComment('');
        setTextInputShouldClear(true);
        if (isComposerFullSize) {
            Report.setIsComposerFullSize(reportID, false);
        }
        setIsFullComposerAvailable(false);
        // Don't submit empty comments or comments that exceed the character limit
        if (!commentLength) {
            return '';
        }
```

**Comment by slafortune** [comment] 2024-02-07 16:22
I think we should close this for more pressing issues, as the functionality is working as discussed.  Thoughts on this @thesahindia ?

**Closed** 2024-02-13 17:24 UTC
Labels: External, Daily, Help Wanted, Overdue, Bug
