### ISSUE TITLE
Chat - List of mentioned accounts cover the typed text when composer has multiple lines

### ISSUE THREAD

**Issue by m-natarajan** [Expensify/App#46622] opened 2024-07-31 22:51 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 9.0.15-4
**Reproducible in staging?:** y
**Reproducible in production?:** no
**If this was caught during regression testing, add the test name, ID and link from TestRail:** https://expensify.testrail.io/index.php?/tests/view/4802024&group_by=cases:section_id&group_order=asc&group_id=290914
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** Applause internal team
**Slack conversation:**

## Action Performed:
1. Go to any chat and tap to compose a message
2. Add seven lines of text
3. Type @

## Expected Result:
The list of mentioned accounts do not cover the typed line

## Actual Result:
The list of mentioned accounts cover the typed line and user can't see what its typed

## Workaround:
unknown
## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [ ] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

https://github.com/user-attachments/assets/7dfc85d7-d2a1-42ce-8d46-b3244048d844

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by m-natarajan** [comment] 2024-07-31 22:52
We think that this bug might be related to  #vip-vsb

**Comment by roryabraham** [comment] 2024-07-31 23:38
Maybe caused by https://github.com/Expensify/App/pull/46091? Will create an AdHoc build of a revert to test

**Comment by kadiealexander** [comment] 2024-08-01 00:11
@roryabraham should I assign you?

**Comment by roryabraham** [comment] 2024-08-01 17:02
no

**Comment by roryabraham** [comment] 2024-08-01 17:04
requested retest with AdHoc build: https://expensify.slack.com/archives/C9YU7BX5M/p1722531831074969

**Comment by roryabraham** [comment] 2024-08-01 18:12
we merged a revert of https://github.com/Expensify/App/pull/46091

**Comment by kavimuru** [comment] 2024-08-01 19:19
Issue is fixed in the latest staging 9.0.15-8

https://github.com/user-attachments/assets/3bd397dc-0970-4060-a8b2-aac987684414

**Closed** 2024-08-01 19:24 UTC
Labels: Engineering, Hourly, Bug
