### ISSUE TITLE
LHN- Unread message is not displayed in bold after reply by email

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#10736] opened 2022-09-01 02:25 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Launch the app
2. Go to chat.expensify.com and log in as account A
3. As account A send some messages to an account that must be a main email address without the +. Wait 10 minutes. This will trigger an email notification to this account
4. Log out of Account A
5. After 10 min has passed, check the main account email inbox and open the mail with this name "Chat between <A> and <B>".
6. Answer to the email with any message.
7. Wait a minute or 2 and log into both accounts (A and main account).

## Expected Result:
Unread message is displayed in bold after reply by email

## Actual Result:
Unread message is not displayed in bold after reply by email

## Workaround:
Unknown

## Platform:

Where is this issue occurring?

- Web
- iOS
- Android
- Desktop App
- Mobile Web

**Version Number:** 1.1.95.4

**Reproducible in staging?:** Yes

**Reproducible in production?:** Yes

**Email or phone of affected tester (no customers):** any

**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Notes/Photos/Videos:** Any additional supporting documentation

https://user-images.githubusercontent.com/93399543/187818973-e400e4ff-ded6-4454-91b3-451ac99a519c.mp4

**Expensify/Expensify Issue URL:** 

**Issue reported by:** Applause - Internal Team

**Slack conversation:** 

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by johnmlee101** [comment] 2022-09-07 08:57
Not sure if this is a front or back-end issue will investigate

**Comment by johnmlee101** [comment] 2022-09-20 21:37
I believe this issue is because the response trigger when we use the email isn't kicking off the unread indicator properly, but I also think we're doing a lot of changes to the LHN and unread messages so going to hold on solving this since its also has a small effect on the app

**Comment by MitchExpensify** [comment] 2022-09-27 22:20
I wonder if this is related to reports from Guides that no new messages in #admins or are showing in bold as unread in LHN

**Comment by marcaaron** [comment] 2022-09-27 22:48
Just adding that the message would not be bold for the person who sent it. That expectation is 100% wrong. If you send a message and then log in as the person who sent it the chat should be marked as read.

**Comment by johnmlee101** [comment] 2022-10-04 22:27
Going to open this up to the pool, but I also think that the email triggers for this shouldn't be too hard to resolve on the backend

**Comment by nkuoch** [comment] 2022-10-21 08:53
Sorry, too much on my plate, unassigning myself

**Comment by tjferriss** [comment] 2022-10-24 19:36
I was not able to reproduce this. The unread message was bold when I came back to the account. This appears to be working as intended so I'm leaning towards closing this out. 

<img width="378" alt="Screen Shot 2022-10-24 at 12 34 52 PM" src="https://user-images.githubusercontent.com/8292562/197610524-65860422-52b7-4780-a40a-092a3cae23a0.png">

**Comment by tjferriss** [comment] 2022-10-28 16:55
Ok I'm going to close this out. Please reopen if you can reproduce.

**Closed by tjferriss** 2022-10-28 16:55 UTC
Labels: Engineering, Daily, Improvement, Overdue, Bug
