### ISSUE TITLE
[$500] Disabled tags are showing as required for "Multi level tags"

### ISSUE THREAD

**Issue by m-natarajan** [Expensify/App#37095] opened 2024-02-22 18:06 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.43-12
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** @joeldavis
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1708607040166479
 
## Action Performed:
1. In OD as admin enable "People must tag expenses" for some workspace
2. Enable "Use multiple levels of tags"
3. Create/import some multi-level tags and mark at least one as disabled
4. Invite user B to the policy as employee
5. As employee go to the workspace chat invited to
6. Request money and enter the amount and click next

## Expected Result:
Disabled tags shouldn't appear

## Actual Result:
Disabled tag appear as required (Multi-level tags all show as required)

## Workaround:
unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

![image_720](https://github.com/Expensify/App/assets/38435837/146eec78-dd3c-4435-8af6-5dfc57f196a5)

![Screen Shot 2024-02-22 at 12 53 26 PM](https://github.com/Expensify/App/assets/38435837/422809da-a1e1-49ca-9f05-a0f4a14904b9)

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~019af1911417c9325b</li>
        <li>Upwork Job ID: 1760727691225997312</li>
        <li>Last Price Increase: 2024-02-22</li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @akinwale</details>

**Comment by FitseTLT** [comment] 2024-02-22 18:31
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
Disabled tags are showing as required for "Multi level tags"

### What is the root cause of that problem?
Currently we are displaying the tags menu without checking whether it is disabled or not here
https://github.com/Expensify/App/blob/29ad8787c7c889271c117dd4420109f9be8e180d/src/components/MoneyTemporaryForRefactorRequestConfirmationList.js#L761-L766
### What changes do you think we should make in order to solve the problem?

When we disable a tag on OD it's `required` field is set to `false` so we can filter out tags with `required` false before displaying here
https://github.com/Expensify/App/blob/29ad8787c7c889271c117dd4420109f9be8e180d/src/components/MoneyTemporaryForRefactorRequestConfirmationList.js#L761-L766
```
 ..._.map(
            _.filter(policyTagLists, ({required}) => required !== false),
            ({name}, index) => ({
                item: (
                    <MenuItemWithTopDescription
                        key={name}
```
### What alternative solutions did you explore? (Optional)

**Comment by akinwale** [comment] 2024-02-22 23:26
Since this is a fairly straightforward issue, we can go with the first correct solution, which can be found in @dukenv0307's [proposal](https://github.com/Expensify/App/issues/37095#issuecomment-1959995099).

🎀👀🎀 C+ reviewed.

**Comment by Christinadobrzyn** [comment] 2024-02-23 19:29
awesome! We'll wait for @MonilBhavsar's review of https://github.com/Expensify/App/issues/37095#issuecomment-1960505959

**Comment by MonilBhavsar** [comment] 2024-02-26 09:30
@akinwale thanks for reviewing. I feel like @FitseTLT 's proposal makes more sense. If tag is disabled, we should not simply render the item rather than checking if it is required or not. What do you think?

**Comment by MonilBhavsar** [comment] 2024-02-26 09:39
Thanks for quick response. I'll take a look and confirm

**Comment by MonilBhavsar** [comment] 2024-02-26 10:03
Okay thanks makes sense @dukenv0307 
Do you think the variable `isTagRequired` needs to have the updated condition?
and why we just update the label, we need to also update `isSupplementary` prop

> Note: BE need to return the required field for each tag in multiple levels tags beside the name and tags fields

It is already sent, no?

**Comment by MonilBhavsar** [comment] 2024-02-26 10:16
Can you please update your proposal then

**Comment by MonilBhavsar** [comment] 2024-02-26 10:29
It should be sent in `policyTags_` key. Can you please double check

**Comment by MonilBhavsar** [comment] 2024-02-26 12:06
The structure looks odd to me.
Here's what I am seeing. May be you can try sign out and sign in?

<img width="397" alt="Screenshot 2024-02-26 at 5 34 25 PM" src="https://github.com/Expensify/App/assets/32012005/d551326f-3514-42b5-813c-1e6e815c7f2d">

**Comment by Christinadobrzyn** [comment] 2024-02-27 23:40
I _think_ this is right, 

I hired @akinwale and @dukenv0307 in Upwork - https://www.upwork.com/jobs/~019af1911417c9325b

**Comment by Christinadobrzyn** [comment] 2024-03-13 04:32
PR in the works https://github.com/Expensify/App/pull/37388

**Comment by Christinadobrzyn** [comment] 2024-03-20 07:24
PR in the works https://github.com/Expensify/App/pull/37388

**Comment by Christinadobrzyn** [comment] 2024-03-25 08:39
PR in the works https://github.com/Expensify/App/pull/37388

**Comment by Christinadobrzyn** [comment] 2024-04-02 09:27
Monitoring https://github.com/Expensify/App/pull/37388

**Comment by Christinadobrzyn** [comment] 2024-04-08 06:36
I think we're still watching PR https://github.com/Expensify/App/pull/37388 which should be done soon - is that correct @MonilBhavsar?

**Comment by MonilBhavsar** [comment] 2024-04-08 07:01
Yes, PR is merged. Should be deployed this week

**Comment by MonilBhavsar** [comment] 2024-04-12 11:19
@dukenv0307 @akinwale we have a regression here. Can anyone please take a look

**Comment by akinwale** [comment] 2024-05-01 19:16
@Christinadobrzyn Automation missed this. Payment for this can be processed (deployed to production [2024-04-10](https://github.com/Expensify/App/pull/37388#issuecomment-2048095073), payment due 2024-04-17) as https://github.com/Expensify/App/issues/39916 is [not being considered as a regression](https://github.com/Expensify/App/issues/39916#issuecomment-2088521084) since the cause is a backend issue.

**Comment by akinwale** [comment] 2024-05-03 07:30
@Christinadobrzyn bump on the above. Thanks.

**Comment by Christinadobrzyn** [comment] 2024-05-08 08:47
DMd @akinwale about the regression test

**Comment by akinwale** [comment] 2024-05-10 06:37
> * [x]  [@akinwale] The PR that introduced the bug has been identified. Link to the PR:
> * [x]  [@akinwale] The offending PR has been commented on, pointing out the bug it caused and why, so the author and reviewers can learn from the mistake. Link to comment:
> * [x]  [@akinwale] A discussion in #expensify-bugs has been started about whether any other steps should be taken (e.g. updating the PR review checklist) in order to catch this type of bug sooner. Link to discussion:

Not a regression. Specifically handling the display of the required label on multi-level tags was not implemented.

> * [x]  [@akinwale] Determine if we should create a regression test for this bug.
> * [x]  [@akinwale] If we decide to create a regression test for the bug, please propose the [regression test](https://github.com/Expensify/App/blob/main/contributingGuides/REGRESSION_TEST_BEST_PRACTICES.md) steps to ensure the same bug will not reach production again.

**Regression Test Steps**
_Prerequisites_
* In OD, as admin, enable the "People must tag expenses" option for a workspace
* In OD, as admin, enable "Use multiple levels of tags
* Create or import a few multi-level tags and mark at least one as not required

1. As an admin, Invite an employee to the workspace.
2. As the employee, navigate to the workspace chat invited to.
3. Request money, enter an amount and click Next.
4. Click on the More button to display the rest of the list items.
5. Verify that only tags that have Required enabled in OD appear as required in ND (The text 'Required' is displayed next to the name of the corresponding tag in the list).

Do we agree 👍 or 👎?

**Comment by akinwale** [comment] 2024-05-10 06:38
@Christinadobrzyn Done!

**Comment by Christinadobrzyn** [comment] 2024-05-13 02:44
Created regression test - https://github.com/Expensify/Expensify/issues/395323

Closing!

**Closed by Christinadobrzyn** 2024-05-13 02:44 UTC
Labels: Reviewing, External, Daily, Bug
