### ISSUE TITLE
[HOLD for payment 2024-02-07] [$500]  Reimbursement - Reimbursement message is not copied with "Copy to clipboard"

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#34045] opened 2024-01-05 18:10 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.22-0
**Reproducible in staging?:** Y
**Reproducible in production?:** N
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** Applause - Internal Team
**Slack conversation:**

## Action Performed:
1. [User A] Request money from User B
2. [User B] Pay the request
3. [User A] Go to the paid IOU report
4. [User A] Right click on reimbursement message > Copy to clipboard
5. [User A] Paste the content

## Expected Result:
The reimbursement message is copied successfully

## Actual Result:
The reimbursement message is not copied

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [x] Android: mWeb Chrome
- [x] iOS: Native
- [x] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details> 

https://github.com/Expensify/App/assets/78819774/04545607-03bf-4eab-9d76-a25f44c6e308

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01143d94d68559e19a</li>
        <li>Upwork Job ID: 1743429727276658688</li>
        <li>Last Price Increase: 2024-01-13</li>
    </ul>
</details>

**Comment by namhihi237** [comment] 2024-01-05 18:22
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
Can not copy message reimbursement
### What is the root cause of that problem?
We do not have a logic for copying the type "MARKEDREIMBURSED" of message in [here](https://github.com/namhihi237/App/blob/2d455bfb820b13fc83a5dd4057f19516faf2f238/src/pages/home/report/ContextMenu/ContextMenuActions.js#L275C1-L299C1)
### What changes do you think we should make in order to solve the problem?
We should add logic like this
```js
if (reportAction.actionName === 'MARKEDREIMBURSED') {
 const reimbursMementessage = _.reduce(reportAction.message, (acc, curr) => `${acc}${curr.text}`, '');
 Clipboard.setString(reimbursMementessage);
}

```

### What alternative solutions did you explore? (Optional)

**Comment by Pujan92** [comment] 2024-01-05 18:24
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
Marked reimbursement message isn't copied with Copy to clipboard option

### What is the root cause of that problem?
We don't have any condition here for setting that message to the clipboard when the action is `MARKEDREIMBURSED`
https://github.com/Expensify/App/blob/main/src/pages/home/report/ContextMenu/ContextMenuActions.js#L274-L298

### What changes do you think we should make in order to solve the problem?
Add condition for `MARKEDREIMBURSED` and use util method `getMarkedReimbursedMessage` to generate that string.
https://github.com/Expensify/App/blob/ae4245e2e643439903b8fb95c69ad5dbe674b039/src/libs/ReportActionsUtils.ts#L774

**Comment by bernhardoj** [comment] 2024-01-05 18:41
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
Copying reimbursed system message copies nothing.

### What is the root cause of that problem?
The reimbursed system message object only contains `text` property and not `html`.
<img width="504" alt="image" src="https://github.com/Expensify/App/assets/50919443/80e46f48-fc54-4c18-8162-5e96b073d7eb">

When we press copy to clipboard, we only take the first message `html`.
https://github.com/Expensify/App/blob/ae4245e2e643439903b8fb95c69ad5dbe674b039/src/pages/home/report/ContextMenu/ContextMenuActions.js#L271-L276

So, the copy to clipboard fails to copy the message.

### What changes do you think we should make in order to solve the problem?

Previously, we had a similar issue for SUBMITTED action and the solution is to concat all message `text`. 
https://github.com/Expensify/App/blob/ae4245e2e643439903b8fb95c69ad5dbe674b039/src/pages/home/report/ContextMenu/ContextMenuActions.js#L293-L296

But instead of handling it case by case, we can make it a general case. So, in addition to `messageHtml`, we can create `messageText` which is the result of all the messages' concatenation. Then, we will use it as the last fallback.

```
const messageText = _.reduce(reportAction.message, (acc, curr) => `${acc}${curr.text}`, '');

} else if (messageText) {
    Clipboard.setString(messageText)
}
```

**Comment by bernhardoj** [comment] 2024-01-17 12:07
Updated

**Comment by bernhardoj** [comment] 2024-01-18 08:33
PR is ready

cc: @0xmiroslav

**Comment by mallenexpensify** [comment] 2024-01-24 00:05
@fedirjh, reassigning, please take over as C+. If you don't have bandwidth, unassign yourself. Thanks

**Comment by muttmuure** [comment] 2024-02-09 14:59
Invited @0xmiroslav and @bernhardoj

**Comment by muttmuure** [comment] 2024-02-12 15:51
Offer sent to @bernhardoj

**Comment by muttmuure** [comment] 2024-02-12 15:51
Waiting for @0xmiroslav to accept

**Comment by muttmuure** [comment] 2024-02-13 15:05
Going to close for now, @0xmiroslav please reopen when you'd like to be paid

**Closed by muttmuure** 2024-02-13 15:05 UTC
Labels: External, Engineering, Daily, Help Wanted, Awaiting Payment, Bug

**Comment by bernhardoj** [comment] 2024-04-09 13:53
@muttmuure Hi, I was scanning through my pending payment and saw that I haven't been paid yet on this one. Here is the [offer](https://www.upwork.com/nx/wm/workroom/36328551) that I was checking, could you kindly check it on your side?

**Comment by mallenexpensify** [comment] 2024-04-09 23:01
Contributor: @bernhardoj paid $500 via Upwork
Sorry we missed that @bernhardoj

**Comment by bernhardoj** [comment] 2024-04-10 01:24
@mallenexpensify Thanks!
