### ISSUE TITLE
 iOS - Profile - The App crashes when saving the user's avatar

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#37963] opened 2024-03-08 11:45 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.49-0
**Reproducible in staging?:** y
**Reproducible in production?:** n
**If this was caught during regression testing, add the test name, ID and link from TestRail:** https://expensify.testrail.io/index.php?/tests/view/4410248
**Issue reported by:** Applause - Internal Team

## Action Performed:
1. Open iOS App
2. Login with any account
3. Go to Account Settings
4. Tap to User Avatar
5. Select "Upload photo"
6. Select "Take photo" or "Choose from gallery"
7. Take/select photo and tap "Save"

## Expected Result:
Photo was successfully saved as the user's avatar.

## Actual Result:
App crashes after user taps on "Save" button

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [x] iOS: Native
- [ ] iOS: mWeb Safari
- [ ] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

https://github.com/Expensify/App/assets/93399543/61bd385b-6315-414f-9dd9-c4b4b33951fd

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by kbecciv** [comment] 2024-03-08 11:45
We think that this bug might be related to #vip-vsb
@quinthar

**Comment by kbecciv** [comment] 2024-03-08 15:30
@shubham1206agra Please attached
[logs crash.docx](https://github.com/Expensify/App/files/14539968/logs.crash.docx)

**Comment by roryabraham** [comment] 2024-03-08 20:07
not able to reproduce on dev

**Comment by roryabraham** [comment] 2024-03-08 20:14
this appears to be related to [this crash](https://console.firebase.google.com/u/0/project/expensify-chat/crashlytics/app/ios:com.chat.expensify.chat/issues/f48ee66dac3f22d3425201cbc542028c?time=last-seven-days&types=crash&sessionEventKey=ee538b7e3945404b9925608b772f0d16_1922515179538253842), which was first caught on 1.4.47-10. So I'm not sure if it's a blocker (but it was my mistake not noticing this earlier this week, I had been looking only at Android crashes by mistake)

**Comment by roryabraham** [comment] 2024-03-08 20:20
was able to reproduce on staging. I wonder if it has to be an HEIC?

**Comment by roryabraham** [comment] 2024-03-08 20:21
need to test on a physical device...

**Comment by situchan** [comment] 2024-03-08 21:04
I reproduced in iOS Simulator.
The crash happens only on release build. It's pretty bad that once reproduced following OP, crash happens on app launch until uninstall and reinstall the app.
After reverting https://github.com/Expensify/App/pull/36019, not able to reproduce.

**Comment by situchan** [comment] 2024-03-08 21:51
I managed to debug more.

After reproducing crash on release build, switch to debug scheme and build, console error on app launch:

<img width="324" alt="Screenshot 2024-03-09 at 3 49 54 AM" src="https://github.com/Expensify/App/assets/108292595/faad800f-f959-450e-8dcc-83797a3dc826">

**Comment by roryabraham** [comment] 2024-03-08 22:32
I wonder if this can be fixed by removing deprecated `useWorkletCallback`: https://github.com/software-mansion/react-native-reanimated/pull/5377/files#r1501883320

**Comment by roryabraham** [comment] 2024-03-08 22:58
cool, was able to reproduce on a release build. Going to try nixing `useWorkletCallback` and see if that helps

**Comment by roryabraham** [comment] 2024-03-09 00:47
I am very stuck on trying to fix this, mostly because it's very difficult to debug or even get logs in a release build, which seems to be the only place where this is reproducible.

**Comment by roryabraham** [comment] 2024-03-09 15:08
https://github.com/Expensify/App/pull/36019 is already on production. Have we verified that this is not reproducible on prod?

**Comment by roryabraham** [comment] 2024-03-09 15:10
Requested retest: https://expensify.slack.com/archives/C9YU7BX5M/p1709996985170449

**Comment by roryabraham** [comment] 2024-03-09 15:19
Noodling about in https://github.com/Expensify/App/pull/38018, but confident that I'm any closer to a fix

**Comment by roryabraham** [comment] 2024-03-09 15:29
Ok, this was reproduced in prod, so not a deploy blocker. But it's very bad, maybe a fire

**Comment by kavimuru** [comment] 2024-03-09 15:30
Bug is reproduced in production too.

https://github.com/Expensify/App/assets/43996225/104d8279-d96d-4252-ac37-30ccb28e5f36

**Comment by roryabraham** [comment] 2024-03-09 16:25
I confirmed that commenting out [this line](https://github.com/Expensify/App/blob/8f872b09a2e29e6c8fa6d5013478968dc793a286/src/components/AvatarCropModal/AvatarCropModal.tsx#L292) prevents the crash. This doesn't really tell us much, other than that the crash doesn't appear to be happening inside `cropOrRotateImage`, or `manipulateAsync`. It's still possible that the crash is caused by a problem there though, such as a file not being saved correctly.

**Comment by roryabraham** [comment] 2024-03-09 16:49
some logs: https://staging.expensify.com/_devportal/tools/logSearch/#query=request_id:(%22861c7ee5cdbbef73-PDX%22)+AND+timestamp:[2024-03-09T15:38:30.081Z+TO+2024-03-09T17:38:30.081Z]&index=logs_expensify-027211

**Comment by roryabraham** [comment] 2024-03-09 17:05
ok, so I confirmed that the crash happens after [this point](https://github.com/Expensify/App/blob/d6d2db5184926fb012fdc47a7bd02c141ca703ac/src/libs/actions/PersonalDetails.ts#L334). I tried just removing the Onyx data from `API.write(WRITE_COMMANDS.UPDATE_USER_AVATAR, parameters, {});`, but the crash still happens in this case.

**Comment by roryabraham** [comment] 2024-03-09 17:11
ok, commented out `API.write()` entirely and put `Onyx.update(optimisticData)` directly in `PersonalDetails.updateAvatar` and that worked. I'm seeing the new avatar image, which tells me the file _is_ being saved locally.

So next up I need to figure out where the actual image upload code is and try to narrow down what's going wrong.

**Comment by roryabraham** [comment] 2024-03-09 17:19
I found a [random article](https://www.reactnativeschool.com/how-to-upload-images-from-react-native) which does this to upload a file:

```
const createFormData = (photo, body = {}) => {
  const data = new FormData();

  data.append('photo', {
    name: photo.fileName,
    type: photo.type,
    uri: Platform.OS === 'ios' ? photo.uri.replace('file://', '') : photo.uri,
  });

  Object.keys(body).forEach((key) => {
    data.append(key, body[key]);
  });

  return data;
};
```

note the `Platform.OS === 'ios' ? photo.uri.replace('file://', '') : photo.uri` - the uri we have definitely starts with `file://`...

**Comment by hungvu193** [comment] 2024-03-09 17:21
Hey @roryabraham  hope this can help, I can see the JS log.

<img width="535" alt="Screenshot 2024-03-10 at 00 20 34" src="https://github.com/Expensify/App/assets/16502320/40c57080-e7e6-418f-a759-4fb35bf97e9b">

**Comment by hungvu193** [comment] 2024-03-09 17:33
The crash happened right after you clicked Send button and after reseting the app (later), so I think it must be something with applying optimisticData.

**Comment by roryabraham** [comment] 2024-03-09 17:37
> ok, commented out API.write() entirely and put Onyx.update(optimisticData) directly in PersonalDetails.updateAvatar and that worked

I'm not sure. I think it's the file upload that's failing?

**Comment by roryabraham** [comment] 2024-03-09 17:45
I tried adding a line [here](https://github.com/Expensify/App/blob/caf4552358d109be8793213d3cc5272bb6d6899f/src/libs/cropOrRotateImage/index.native.ts#L13) like `result.uri = result.uri.replace('file://', '');`, no dice 😞

**Comment by hungvu193** [comment] 2024-03-09 19:14
I can confirm revert to use `@oguzhnatly/react-native-image-manipulator` will fix the issue. So the problem will be with `expo-image-manipulator`.

**Comment by roryabraham** [comment] 2024-03-10 17:28
Going to proceed with a revert due to the severity of the bug. I'd like to CP the revert to staging so we can fix prod ASAP

**Comment by roryabraham** [comment] 2024-03-10 17:46
reopening to verify the fix in [1.4.49-4](https://github.com/Expensify/App/actions/runs/8223725113)

**Comment by situchan** [comment] 2024-03-10 18:11
ok so as I said [here](https://github.com/Expensify/App/issues/37963#issuecomment-1986418277), app still crashes on launch for the users who already triggered crash on avatar upload in previous build.
They should uninstall and reinstall to continue using the app.

**Comment by roryabraham** [comment] 2024-03-10 18:50
yeah, that's unfortunate but I don't think there's anything we can do about it really ☹️

**Comment by roryabraham** [comment] 2024-03-10 18:53
well, maybe if we found a "restorative" fix to the crash rather than a "preventative" fix, but idk if we'll be able to do that since it seems to be a low-level crash in the native network request code, presumably caused by some bad url or something?

**Comment by roryabraham** [comment] 2024-03-10 18:56
verified this is fixed after you uninstall and reinstall

**Closed by roryabraham** 2024-03-10 18:56 UTC
Labels: Engineering, Hourly

**Comment by kosmydel** [comment] 2024-03-11 19:26
Hey, I've investigated this issue today.

---

The reason behind it was that we were passing the `base64=null` param inside the `file` parameter when calling the API:
https://github.com/Expensify/App/blob/95a774e597bed9621733e48df1b61e8c77b0c590/src/libs/actions/PersonalDetails.ts#L385

The `RCTNetworking` networking library didn't like the `base64` nullish value, and early returned causing the crash:

https://github.com/facebook/react-native/blob/a7fde7c885a3827c03b058a21023b18501e2a57a/packages/react-native/Libraries/Network/RCTNetworking.mm#L425-L428


**Why did we pass the `base64` value?**
The `expo-image-manipulator` library by default sets the `base64` option to false, meaning that we don't need to generate it. But the library instead of skipping this param, adds `base64=null` in this line:

https://github.com/expo/expo/blob/a05bfbc3a907177bca2dd8a2dd22073763daa895/packages/expo-image-manipulator/ios/ImageManipulatorModule.swift#L33

Commenting out this line fixes the problem.


**So I come up with two solutions (without touching the library):**
- We can pass [here](https://github.com/Expensify/App/blob/caf4552358d109be8793213d3cc5272bb6d6899f/src/libs/cropOrRotateImage/index.native.ts#L12) `base64: true` option to generate the base64 (instead of passing null)
- We can remove the `base64` prop from the parameters when calling the API command:

```javascript
const {base64, ...fileWithoutBase64} = file;
const parameters: UpdateUserAvatarParams = {file: fileWithoutBase64};
```

I will also contact with the internal expo maintainers at SWM, as they might want to fix it in the library.

---

I will prepare a PR with the fix tomorrow. 

Thanks @roryabraham for the initial investigation, as it helped a lot!

**Comment by roryabraham** [comment] 2024-03-11 21:47
sounds good @kosmydel and thanks for figuring that out. Glad my initial investigation was helpful! If we're not using the base64 encoding I imagine it's likely better not to generate it unnecessarily. So let's go with the 2nd solution to remove the `base64` from the parameters when calling the API command.

Alternatively, maybe we can update expo-image-manipulator to remove `base64: null` from the response if no `base64` encoding is created. That seems like the best solution if they're down for that

**Comment by kosmydel** [comment] 2024-03-12 09:43
> https://github.com/expo/expo/blob/a05bfbc3a907177bca2dd8a2dd22073763daa895/packages/expo-image-manipulator/ios/ImageManipulatorModule.swift#L33

> Alternatively, maybe we can update expo-image-manipulator to remove base64: null from the response if no base64 encoding is created. That seems like the best solution if they're down for that

I've contacted an Expo maintainer, so I will keep you updated.

For now, I think to unblock the issue, I can prepare a PR with the 2nd solution.

**Comment by kosmydel** [comment] 2024-03-13 08:12
> sounds good @kosmydel and thanks for figuring that out. Glad my initial investigation was helpful! If we're not using the base64 encoding I imagine it's likely better not to generate it unnecessarily. So let's go with the 2nd solution to remove the `base64` from the parameters when calling the API command.
> 
> Alternatively, maybe we can update expo-image-manipulator to remove `base64: null` from the response if no `base64` encoding is created. That seems like the best solution if they're down for that

**Quick update:** After contacting Expo maintainers they told me, that this is expected, and consistent across other parameters. They will improve the types, so the `base64` will also include the `null` type (currently it is `string | undefined`). So in that way, we would know, that `base64` could be null, and we would be able to handle it appropriately.

For now, I've created a PR with 2nd solution.
