### ISSUE TITLE
"hmm it's not here" page appears clicking global create button 

### ISSUE THREAD

**Issue by m-natarajan** [Expensify/App#52602] opened 2024-11-14 20:29 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:**
**Reproducible in staging?:** needs reproduction
**Reproducible in production?:** need reproduction
**If this was caught on HybridApp, is this reproducible on New Expensify Standalone?:**
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** @heyjennahay 
**Slack conversation** (hyperlinked to channel name): [Expensify_migrate](https://expensify.slack.com/archives/C07NMDKEFMH/p1731604898067159?thread_ts=1731519872.122089&cid=C07NMDKEFMH)

## Action Performed:
1. Click on the FAB
2. Or click on the QAB to submit the expese
## Expected Result:
BNP opens in the RHP to enter amount and choose workspace
## Actual Result:
"hmm it is not here page opens"
## Workaround:
unknown
## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Standalone
- [ ] Android: HybridApp
- [ ] Android: mWeb Chrome
- [ ] iOS: Standalone
- [ ] iOS: HybridApp
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

<details>
  <summary>Add any screenshot/video evidence</summary>

  
</details>

![image (22)](https://github.com/user-attachments/assets/7c1bdaa6-2ed2-4d36-8e0e-1c0b537b9186)

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by VictoriaExpensify** [comment] 2024-11-18 10:18
I think this is essentially the same issue that's being worked on [here](https://github.com/Expensify/App/issues/52515)  - they have both been created from the same thread with two users experiencing the same issue.

The recreate steps in this issue are very very vague, but I think they are the same. @heyjennahay and @justinpersaud are you able to confirm if you were both experiencing the same issues, or were there variences?

**Comment by heyjennahay** [comment] 2024-11-19 15:27
@justinpersaud I think the issue you reported is slightly different when I read it, to me it seems like you were able to create the expense but it didn't then appear in your account, is that right?

With mine I cannot even create the expense:
- Via quick action button > scan receipt to Expenses - Expensify NL workspace, I get the "hmm it's not here" page ❌ 
- Via the workspace chat, there is not create expense options ❌
- Via global create > create expense > scan > add to workspace, does work ✅

**Comment by heyjennahay** [comment] 2024-11-19 16:15
Ok I think we can close this as a duplicate.  Justin confirmed that he is having the same flow issues as me, the only difference is that his expenses are not then visible in NewDot while mine are

**Comment by VictoriaExpensify** [comment] 2024-11-20 00:09
Thanks @heyjennahay - closing this as a dupe

**Closed by VictoriaExpensify** 2024-11-20 00:09 UTC
Labels: Daily, Needs Reproduction, Bug
