### ISSUE TITLE
New icons are corrupted

### ISSUE THREAD

**Issue by IuliiaHerets** [Expensify/App#54514] opened 2024-12-24 11:45 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 9.0.78-1
**Reproducible in staging?:** Yes
**Reproducible in production?:** No
**If this was caught on HybridApp, is this reproducible on New Expensify Standalone?:** Yes, reproducible on both
**If this was caught during regression testing, add the test name, ID and link from TestRail:** Exp
**Email or phone of affected tester (no customers):** nathanmulugetatesting+2558@gmail.com
**Issue reported by:** Applause Internal Team
**Device used:** iPhone 11 / iOS 18.1
**App Component:** Other

## Action Performed:
1. Open NewDot app
2. Navigate to Workspaces 
3. Navigate to a Workspace
4. Navigate to Members

## Expected Result:
The icon next to the header "Members" should have the right color:
![image](https://github.com/user-attachments/assets/93b1d18e-1eeb-4c40-ab96-8242eec22780)

## Actual Result:
The icon color is wrong:
![image](https://github.com/user-attachments/assets/b3f0dfa3-1cd5-4192-8736-63f1460e62a4)

## Workaround:
Unknown

## Platforms:
- [ ] Android: Standalone
- [ ] Android: HybridApp
- [ ] Android: mWeb Chrome
- [x] iOS: Standalone
- [x] iOS: HybridApp
- [ ] iOS: mWeb Safari
- [ ] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

https://github.com/user-attachments/assets/06ed12b3-a9c0-4c10-9a29-166d574d0e77

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by aldo-expensify** [comment] 2024-12-24 13:17
The corruption is also reproducible in web:

![image](https://github.com/user-attachments/assets/e3eede84-561c-4104-b14f-69c13ac0bfed)

**Comment by aldo-expensify** [comment] 2024-12-24 13:43
Thanks @daledah for the investigation, I tried to go with a simpler approach that I think should also work: https://github.com/Expensify/App/pull/54531

Do you want to review as C+?

**Comment by aldo-expensify** [comment] 2024-12-24 15:17
> @aldo-expensify Can I help review the PR?

No need @daledah , I think we need a C+ or someone from the Expensify engineering team. Thanks for offering though.

**Comment by shawnborton** [comment] 2024-12-24 15:26
Just to clarify this one, isn't it a regression? If so, shouldn't as ask the offending PR author to fix it?

**Comment by aldo-expensify** [comment] 2024-12-24 15:58
> Just to clarify this one, isn't it a regression?

It is a regression.

> If so, shouldn't as ask the offending PR author to fix it?

Yes, but that sometimes can take time and here the fix seems to be easy, so I put a PR to be able to clear the deploy blocker asap.

**Comment by aldo-expensify** [comment] 2024-12-24 19:10
Closing this as a dupe of https://github.com/Expensify/App/issues/54480

**Closed by aldo-expensify** 2024-12-24 19:10 UTC
Labels: Reviewing, DeployBlockerCash, Engineering, Weekly, Bug
