### ISSUE TITLE
[$250] IOS - Search - Transaction is not smooth and missing focused when tap on search for new account

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#11513] opened 2022-10-01 19:11 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Launch the app
2. Put a new user in log in account
3. Tap Continue
4. Go back to your email and check the link for password
5. Tap on new link and create a password
6. Tap Set Password button
7. Tap on Search

## Expected Result:
Transaction is smooth and cursor is focused on search box when tap on search for new account

## Actual Result:
Transaction is not smooth and missing focused when tap on search for new account

## Workaround:
Unknow

## Platform:

Where is this issue occurring?

- iOS

**Version Number:** 1.2.11.1

**Reproducible in staging?:** Yes

**Reproducible in production?:** Yes

**Email or phone of affected tester (no customers):** new account only

**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Notes/Photos/Videos:** Any additional supporting documentation

https://user-images.githubusercontent.com/93399543/193424667-3f431a5c-e9fd-4ed8-ac37-2948c073401d.MP4

**Expensify/Expensify Issue URL:** 

**Issue reported by:** Applause - Internal Team

**Slack conversation:** 

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by Julesssss** [comment] 2022-10-03 10:15
This is pretty minor. It looks like we're opening the keyboard only to immediately dismiss it when opening the search page. 

Ideally, we wouldn't attempt to open the keyboard in the first place. Let's see if we can locate a fix.

**Comment by Uros787** [comment] 2022-10-06 20:51
Couldn't reproduce, new acc. Somebody to check also or help me on what i could've done wrong
https://user-images.githubusercontent.com/70144379/194415988-087e78cd-dd9f-45b7-b5ef-d02e474ac4fa.mov

**Comment by sobitneupane** [comment] 2022-10-07 02:23
Could not reproduce on iOS simulator.

cc: @Julesssss

**Comment by Julesssss** [comment] 2022-10-07 10:16
Hey both, this won't be reproducible on the simulator because the soft keyboard has different behavior to real iOS devices. @sobitneupane do you have a physical iOS device? No worries if not, I'll reassign the issue to someone that does. 

I reproduced it here:  iPhone 7, iOS 13.3.

https://user-images.githubusercontent.com/10736861/194530891-47a668fe-b779-4446-9f6f-fb2a244c9f0f.MP4

**Comment by sobitneupane** [comment] 2022-10-07 11:54
> @sobitneupane do you have a physical iOS device?

I don't have a physical iOS device. Unassigning.

**Comment by Julesssss** [comment] 2022-10-07 13:57
Thanks @mananjadhav for volunteering. I'm curious to see whether you can reproduce this bug on a simulator with the hardware keyboard disconnected.

**Comment by mananjadhav** [comment] 2022-10-07 19:58
Okay so weirdly I can neither reproduce this on physical device (iPhone 12, iOS 15.5) nor simulator (iPhone 7 13.3, iPhone 8 14.4, iPhone 13 15.5).

**Comment by Julesssss** [comment] 2022-10-10 10:50
Yeah, but only on `iPhone 7, iOS 13.3.`

**Comment by mananjadhav** [comment] 2022-10-10 17:07
yeah Hence I downloaded iOS 13.3 on my mac, but can't reproduce this on simulator. Are you able to reproduce this on simulator same version `iPhone 7, iOS 13.3` ?

**Comment by Julesssss** [comment] 2022-10-11 09:43
> Are you able to reproduce this on simulator same version

I don't have time to try this today unfortunately, but this suggests that the bug is only reproducible on physical devices. Let's seek proposals, ensuring that we verify fixes on our physical devices.

**Comment by stephanieelliott** [comment] 2022-10-11 18:51
Posted to Upwork: https://www.upwork.com/jobs/~01fd379e92cd167377

**Comment by stephanieelliott** [comment] 2022-10-14 22:12
I'm OOO til 10/25, reapplied the `External` label to get a new CME/BZ team member! Thanks @tjferriss

**Comment by Julesssss** [comment] 2022-10-17 09:06
Awaiting proposals.

**Comment by mvtglobally** [comment] 2022-10-18 11:29
Issue not reproducible during KI retests. (First week)

**Comment by tjferriss** [comment] 2022-10-18 22:33
Upworks job is posted - https://www.upwork.com/jobs/~01cf6e5fdde2aef351

Internal link https://www.upwork.com/ab/applicants/1582499881623302144/job-details

**Comment by mvtglobally** [comment] 2022-10-24 18:38
Issue not reproducible during KI retests. (Second week)

**Comment by tjferriss** [comment] 2022-10-25 19:05
I also can't reproduce this so I'm going to close it and take down the Upwork's posts.

**Closed** 2022-10-25 19:06 UTC
Labels: External, Engineering, Weekly, Help Wanted, Bug

**Comment by Julesssss** [comment] 2022-10-26 10:12
Confirmed this is no longer reproducible on the same device I reproduced it on [previously](https://github.com/Expensify/App/issues/11513#issuecomment-1271403779).
