### ISSUE TITLE
[HOLD for payment 2024-02-26] [$500] Add support for redirecting user to a target URL(via exitTo query param) when they click on the magic link code

### ISSUE THREAD

**Issue by techievivek** [Expensify/App#36325] opened 2024-02-12 12:37 UTC
Part of https://github.com/Expensify/App/issues/34166

Please go through the description of the above issue carefully before you post any questions. 

We aim to enhance user experience by allowing first-time users to directly access our product feature without a need to manually go through the login process. This enhancement involves embedding a magic code in the offline activity email sent to users.

Magic Link Format: https://new.expensify.com/v/<accountID>/<magicCode>?exitTo=valid_target_path_in_newDot
https://new.expensify.com/v/123/000000?exitTo=r/12345

Functional Requirements:

1. If the user is not logged in, the magic code should trigger the sign-in process automatically and redirect the user to the target URL specified in the exitTo parameter of the link once the sign-in logic is successfully executed.

2. If the user is already logged in, the magic code sign-in should be skipped, and the user should be directly redirected to the exitTo URL.

Resources:
You will probably need to play with ValidateLoginPage logic
Website file: https://github.com/Expensify/App/blob/main/src/pages/ValidateLoginPage/index.website.tsx
Other platform: https://github.com/Expensify/App/blob/main/src/pages/ValidateLoginPage/index.tsx

Let me know if anything is unclear or if you need help with anything. Thanks.

CC @MitchExpensify 
<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01a6d9657733b55abf</li>
        <li>Upwork Job ID: 1757021871380135936</li>
        <li>Last Price Increase: 2024-02-12</li>
<li>Automatic offers: </li>
<ul>
<li>rayane-djouah | Contributor | 0</li>
</ul></li>
    </ul>
</details>

**Comment by techievivek** [comment] 2024-02-12 13:40
I was already playing with changes similar to above, can you please add a branch for testing in your proposal, thanks.

**Comment by techievivek** [comment] 2024-02-12 13:40
Cc @rayane-djouah @abzokhattab

**Comment by techievivek** [comment] 2024-02-13 05:35
Great, thanks for the screen recordings. It seems to behave the way we expected. @allroundexperts, can you please review the above proposals? This is a time-sensitive one, thanks. 🙇

**Comment by allroundexperts** [comment] 2024-02-13 05:48
Both @rayane-djouah and @abzokhattab proposed the solution correctly. @abzokhattab was the first one to propose, but @rayane-djouah created a draft PR and shared the working screen recordings as well. Normally, the first one to propose gets the issue but since we need to move fast here, and the draft PR is already up, let's go with @rayane-djouah's [proposal](https://github.com/Expensify/App/issues/36325#issuecomment-1938660069).

🎀 👀 🎀 C+ reviewed

**Comment by bfitzexpensify** [comment] 2024-02-21 07:11
Switching this to `Daily` so I'm on top of it for payment

**Comment by techievivek** [comment] 2024-02-22 05:00
@rayane-djouah Another improvement that we can make here is that the magic code page appears for a moment. QA team shared this video.


https://github.com/Expensify/App/assets/35863227/06803114-31b0-447f-b2d8-c7c015e65675

Can you look into it and see if we can improve this.

**Comment by MitchExpensify** [comment] 2024-02-23 20:53
Reminder set to pay

**Comment by bfitzexpensify** [comment] 2024-02-27 00:55
@techievivek just checking in on your comment [here](https://github.com/Expensify/App/issues/36325#issuecomment-1958706106) - do you consider this a regression from the solution used in this issue?

**Comment by techievivek** [comment] 2024-02-27 05:15
No, we can't classify it as a regression because it doesn't cause any general breakage. It would simply contribute to a smoother transition.

**Comment by bfitzexpensify** [comment] 2024-02-27 06:08
Gotcha, thanks for clarifying. 

**Payment summary:**

C+: $500 to be paid to @allroundexperts through NewDot Manual Requests
Contributor: $500 to be paid to @rayane-djouah via Upwork - complete ✅ 

@allroundexperts, a reminder to complete the BZ checklist when you get a chance - thanks!

**Comment by bfitzexpensify** [comment] 2024-03-04 00:59
Bump on the BZ checklist @allroundexperts - thank you!

**Comment by allroundexperts** [comment] 2024-03-06 14:02
@bfitzexpensify This is a new feature and checklist isn't needed here.

**Comment by bfitzexpensify** [comment] 2024-03-06 23:32
Cool - closing this out. Thanks everyone!

**Closed by bfitzexpensify** 2024-03-06 23:32 UTC
Labels: Reviewing, External, Engineering, Daily, Awaiting Payment, Bug

**Comment by JmillsExpensify** [comment] 2024-03-12 02:44
$500 approved for @allroundexperts based on summary.
