### ISSUE TITLE
 Workspace - Second Expense Submission Delayed in Workspace After Paying First Expense Elsewhere

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#47252] opened 2024-08-12 17:47 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 9.0.19-0
**Reproducible in staging?:** Y
**Reproducible in production?:** N
**If this was caught during regression testing, add the test name, ID and link from TestRail:** N/A 
**Email or phone of affected tester (no customers):** abebemiherat@gmail.com
**Issue reported by:** Applause - Internal Team

## Action Performed:
1. Go to FAB > Workspace
2. In Workspace Settings, enable the Report Field under More Features
3. Add a Report Field, name it, select a type, and save
4. In Workspace Chat, click the plus sign, submit an expense, enter the amount and merchant, and submit
5. In IOU, fill in the Report Field, exit, submit, and select Pay Elsewhere
6. Submit a second expense as in Step 4 and observe the delay

## Expected Result:
The second expense should not be delayed after paying the first expense elsewhere

## Actual Result:
The second expense submission is delayed in Workspace after paying the first expense elsewhere

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [x] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details> 

https://github.com/user-attachments/assets/579bd71e-2a97-4a7b-a252-8a676f31e3b9

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by dangrous** [comment] 2024-08-12 23:34
Huh that's weird. Does the behavior only occur when the report fields are enabled? I also noticed that the RBR on the original expense didn't go away after you updated the field. Is that a separate bug? If so, can you try reproducing if there is NOT an RBR still on the original expense? I'm wondering if it's something to do with that.

**Comment by Beamanator** [comment] 2024-08-13 03:33
report fields are on beta so demoting

**Comment by dangrous** [comment] 2024-08-13 15:36
@luacmartins @mountiny looks like y'all might know more about this one... it feels like the error is an onyx update not being sent appropriately from the backend but I'm not sure why the report fields would cause that specifically

**Comment by dangrous** [comment] 2024-08-13 16:30
actually, I just retested this and it's not happening any more. Closing!

**Closed by dangrous** 2024-08-13 16:30 UTC
Labels: Engineering, Daily
