### ISSUE TITLE
Can't assign task when completed but still create chat report on LHN

### ISSUE THREAD

**Issue by kavimuru** [Expensify/App#23213] opened 2023-07-19 22:43 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Open 2 accounts on 2 browsers
2. A create a task and assign B
3.B go to task detail and click assignee, observe the modal appear
4. A check complete the task
5. B search and select the user C not have a chat before, Observe that a report with user C is generated on LHN and last message shows "assigned a task to you:...."
## Expected Result:
Can't update assignee when task is complete, and not create a report on the LHN

## Actual Result:
 report with user C is generated on LHN and last message shows "assigned a task to you:...."

## Workaround:
Can the user still use Expensify without this being fixed? Have you informed them of the workaround?

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [x] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 
**Reproducible in staging?:** needs reproduction
**Reproducible in production?:** needs reproduction
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/43996225/8aa77f1b-a7c1-40e1-ad48-ee817cd16634

**Expensify/Expensify Issue URL:**
**Issue reported by:** @namhihi237 
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1689587434890729

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by kavimuru** [comment] 2023-07-19 22:43
## Proposal
by @namhihi237
### Please re-state the problem that we are trying to solve in this issue.
Can't update assignee when a task is complete, and not create a report on the LHN
### What is the root cause of that problem?
Currently when updating assignee task backend returned an error but FE has not updated optimisticData yet so still creating a report if the report is available, update the report  with `optimisticAssigneeReport` [here](https://github.com/Expensify/App/blob/ab3d0e876e311ed1ce3cd859ad6dd77a5d8e3cdf/src/libs/actions/Task.js#L394C1-L417C1)
### What changes do you think we should make in order to solve the problem?
We will handle dismiss modal when the task is complete in [TaskAssigneeSelectorModal](https://github.com/Expensify/App/blob/main/src/pages/tasks/TaskAssigneeSelectorModal.js)
```javascript
const isCompleted = ReportUtils.isCompletedTaskReport(props.task.report);
useEffect(() => {
    if (!props.task.report || !isCompleted) {
        return;
    }
    Navigation.dismissModal(props.task.report.reportID);
}, [props.task.report.reportID, isCompleted])
```
Also, we can do the same with the title and description
### What alternative solutions did you explore? (Optional)
Also, we have another way to update the original state of the report but do not prefer

**Comment by adelekennedy** [comment] 2023-07-25 21:35
also unable to reproduce following reproduction steps, [asked](https://expensify.slack.com/archives/C049HHMV9SM/p1690320914808449?thread_ts=1689587434.890729&cid=C049HHMV9SM) the reporting to try to repro again

**Comment by adelekennedy** [comment] 2023-07-27 03:51
@Nodebrute you think this is the same root cause as https://github.com/Expensify/App/issues/21579?

I think in that case we want to close

**Comment by adelekennedy** [comment] 2023-07-28 03:04
closing this as we're both still unable to reproduce and there seem to be similar issues

**Closed by adelekennedy** 2023-07-28 03:04 UTC
Labels: Daily, Needs Reproduction, Bug
