### ISSUE TITLE
[$500] Web - After using the Enter key in any field, the 'Upload Photo' feature becomes visible on another

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#31756] opened 2023-11-22 21:23 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.2.0
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** Applause - Internal Team
**Slack conversation:**

## Action Performed:
1. Go to staging.new.expensify.com
2. Log in with any account
3. Go to Setting - Profile
4. Use Tab Key and navigate to default avatar
5. Press Enter Key - you will see the upload photo option displayed
6. Use Tab Key and navigate to Status
7. Hit Enter Key

## Expected Result:
After using the Enter key in any field, the 'Upload Photo' feature should not be visible on another page

## Actual Result:
After using the Enter key in any field, the 'Upload Photo' feature becomes visible on another page

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] Windows: Chrome 
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details> 

https://github.com/Expensify/App/assets/78819774/2ba52606-5f34-4d9a-bec3-5e2e45457ba7

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01faa982f8264324b6</li>
        <li>Upwork Job ID: 1727437775455944704</li>
        <li>Last Price Increase: 2023-11-22</li>
    </ul>
</details>

**Comment by zukilover** [comment] 2023-11-22 22:41
## Proposal
### Please re-state the problem that we are trying to solve in this issue.
Upload Photo popover is still visible when clicking Enter on other field.

### What is the root cause of that problem?
When user presses Enter outside of the PopoverMenu, it simply doing nothing instead of closing it.
See this line:

https://github.com/Expensify/App/blob/14abfa118d473baeba163f15e6042180892f71cf/src/components/PopoverMenu/index.js#L68-L70


### What changes do you think we should make in order to solve the problem?
We should close the popover if user presses Enter outside of the popover.
We can do so by changing the line above to:

```javascript
            if (focusedIndex === -1) {
                props.onClose();
                return;
            }
```

### What alternative solutions did you explore? (Optional)
N/A

**Comment by ikevin127** [comment] 2023-11-23 01:50
I was able to reproduce the issue on **Web** (Chrome / Safari / Firefox) and **Desktop** -> all platforms where the user can navigate using keyboard TAB key.

# Proposal

## Please re-state the problem that we are trying to solve in this issue

After opening Avatar's popover menu 'Upload Photo' via keyboard Enter key, the popover remains opened after navigating away from Avatar to other fields via keyboard TAB key, the popover persisting even when navigating to one of the other fields pages like `Status` or any other.

## What is the root cause of that problem?

This is happening because the `AvatarWithImagePicker.js` is missing logic that should handle the conflict between keyboard navigation using TAB key and the Avatar's popover component **open** state which is handled by the `isMenuVisible` state variable.

## What changes do you think we should make in order to solve the problem?

My solution for this is to writa a useEffect with `isMenuVisible` in the dependency array, where if `isMenuVisible` is `true`, I will re-use already written `keydown` listeners:
- addKeyDownPressListener
- removeKeyDownPressListener

from `@libs/KeyboardShortcut/KeyDownPressListener` to set `isMenuVisible` to `false` when TAB key is pressed again while the popover menu is open.

<details>
<summary>useEffect - Code implementation</summary>

```
    // Closes the opened popover menu when the user navigates
    // using keyboard TAB key on web / desktop.
    useEffect(() => {
        if (!isMenuVisible) {
            return;
        }

        function handleKeyDown(e) {
            if (e.key !== 'Tab') {
                return;
            }
            setIsMenuVisible(false);
        }

        addKeyDownPressListener(handleKeyDown);
        return () => removeKeyDownPressListener(handleKeyDown);
    }, [isMenuVisible]);
```

</details>

What's different in my proposal is that it closes the popover menu as soon as the TAB key is pressed and the focus is set to the next / previous item from the Avatar (popover origin), instead of closing the popup only when navigating to another section like `Status` by pressing the Enter key (which looks kinda buggy).

<details>
<summary>Video of first proposal's solution (for reference)</summary>

https://github.com/Expensify/App/assets/56457735/b02deba8-9702-49e7-a3ce-dec029c834c4

</details>

 ### Videos

<details>
<summary>MacOS: Chrome - Current proposal's solution</summary>

https://github.com/Expensify/App/assets/56457735/814a66ab-296a-4a74-be6c-b85d3aed0616

</details>

**Comment by zanyrenney** [comment] 2023-11-27 15:45
@Santhosh-Sellavel please can you review the propsoals?

**Comment by zanyrenney** [comment] 2023-12-01 12:28
bump @Santhosh-Sellavel what are your thoughts on what @thienlnam said above [here](https://github.com/Expensify/App/issues/31756#issuecomment-1828466170)

**Comment by Santhosh-Sellavel** [comment] 2023-12-01 17:59
@thienlnam Sorry I didn't post a reply earlier,  yes we can hold this for that as it seems it might resolve this one too!

**Comment by zanyrenney** [comment] 2023-12-04 11:55
cool, so what's next? how can we get this moving more? Is [this](https://github.com/Expensify/App/issues/31756#issuecomment-1828303820) the latest plan? @thienlnam @Santhosh-Sellavel

**Comment by thienlnam** [comment] 2023-12-04 22:42
This is the [latest](https://github.com/Expensify/App/issues/31756#issuecomment-1828466170), there's another issue that likely has the same root cause as this issue. We're going to hold it until the fix for that is handled and see if this is still a problem

**Comment by zanyrenney** [comment] 2023-12-14 22:06
thanks for the update @thienlnam

**Comment by zanyrenney** [comment] 2023-12-14 22:06
please can you link the other issue that we are holding this on though?

**Comment by thienlnam** [comment] 2023-12-14 22:16
https://github.com/Expensify/App/issues/15631

**Comment by thienlnam** [comment] 2024-01-03 00:16
Still on hold

**Comment by Santhosh-Sellavel** [comment] 2024-01-27 17:10
I'm unavailable next week, Please assign a new C+ Issue here if required while I am away, thanks!

cc: @zanyrenney

**Comment by Santhosh-Sellavel** [comment] 2024-02-02 19:05
Back now

**Comment by zanyrenney** [comment] 2024-03-06 14:13
No worries @Santhosh-Sellavel

**Comment by zanyrenney** [comment] 2024-03-06 14:17
Stillon HOLD.

**Comment by zanyrenney** [comment] 2024-04-04 10:32
@thienlnam I have been sifting through the projects but I am actually not 100% sure which one this would fit in. DO you have any ideas? Would appreciate a second opinion! I was thinking maybe performance?

**Comment by thienlnam** [comment] 2024-04-04 15:49
I would probably categorize under vip-vsb as part of general improvements related to the individual user experience

**Comment by zanyrenney** [comment] 2024-04-04 16:13
okay fab, thank you for taking a look!

**Comment by thienlnam** [comment] 2024-05-13 18:42
Holding PR is complete, we should retest to see if this is still reproducible

**Comment by Santhosh-Sellavel** [comment] 2024-05-22 17:00
Still Occurs here 

<img width="1438" alt="Screenshot 2024-05-22 at 10 29 51 PM" src="https://github.com/Expensify/App/assets/85645967/1c8479d8-bd52-4829-9e05-31f15d447da1">

**Comment by bernhardoj** [comment] 2024-05-23 03:07
The previous focus trap PR was closed, so it's not completed yet. Here is the new focus trap [PR](https://github.com/Expensify/App/pull/39520).

**Comment by bernhardoj** [comment] 2024-06-18 07:14
The focus trap PR is done. I can't repro it anymore.

cc: @Santhosh-Sellavel

**Comment by thienlnam** [comment] 2024-06-18 17:21
Great, thanks - going to close

**Closed by thienlnam** 2024-06-18 17:21 UTC
Labels: External, Monthly, Help Wanted, Bug
