### ISSUE TITLE
Delete payment method modal has an inconsistent design with other modals like delete workspace, delete comment.

### ISSUE THREAD

**Issue by kavimuru** [Expensify/App#19212] opened 2023-05-18 20:50 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:

1. Open App
2. Go to Settings > Payments
3. If no payment has been added then add any one
4. Press on the added payment method
5. It will open a popover menu
6. Press on delete
7. It will open a confirmation modal

## Expected Result: 
The confirmation modal should be centered on the screen like the delete workspace modal, etc.
## Actual Result: 
The confirmation modal is shown below the payment method.
## Workaround:
Can the user still use Expensify without this being fixed? Have you informed them of the workaround?

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [x] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 1.3.16-3
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation
![delete_payment_method](https://github.com/Expensify/App/assets/43996225/5d6cf528-b548-4b37-9769-90d5db3cb261)

https://github.com/Expensify/App/assets/43996225/599ff551-62a5-4dd4-86ca-5c9d4bdc6ffe

**Expensify/Expensify Issue URL:**
**Issue reported by:** @Nikhil-Vats
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1684249772922829

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by Nikhil-Vats** [comment] 2023-05-18 21:46
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
Delete payment method modal has an inconsistent design with other modals like delete workspace, delete comment. The Confirmation modal for delete payment method is not centered like other confirmation modals.

### What is the root cause of that problem?
The `BasePaymentsPage` uses the `ConfirmContent` component with its own styles and `anchorPosition` rather than using the `ConfirmModal` which is used everywhere else. This is an inconsistency with all other similar modals and should be fixed.
https://github.com/Expensify/App/blob/2090c0525de9cd87b8c738e9ccb7dafe79a9a229/src/pages/settings/Payments/PaymentsPage/BasePaymentsPage.js#L483-L500

### What changes do you think we should make in order to solve the problem?

Use `ConfirmModal` instead of `ConfirmContent` to center the delete payment method confirm modal.

```javascript
<ConfirmModal
      title={this.props.translate('paymentsPage.deleteAccount')} 
      onConfirm={() => {
          this.hideDefaultDeleteMenu(false);
          this.deletePaymentMethod();
      }}
      onCancel={this.hideDefaultDeleteMenu}
      prompt={this.props.translate('paymentsPage.deleteConfirmation')}
      confirmText={this.props.translate('common.delete')}
      cancelText={this.props.translate('common.cancel')}
      isVisible
      danger
  />
```

### What alternative solutions did you explore? (Optional)
NA

**Comment by Nikhil-Vats** [comment] 2023-05-18 21:54
I would also like to discuss an additional change in the UI -
1. To open the first delete popover, we have to click the payment method. 
2. There is no proper indication to the user so they'll have to make a guess and click on the payment method to reveal the popover menu with the delete button. Not everyone will be able to guess it which may be bad for UX.
3. I think similar to the delete workspace UI, we should show a `ThreeDotsMenu` on the right of each payment method which will reveal the initial menu with Delete button and Make default payment method button (a beta feature right now). 
4. Then we can click the delete button to show the confirmation modal which is centered.

A rough final look should be something like this -
Please note that the Paypal button also looks selected but that is because I wanted to visualize the UI so I just wrote a rough version of the code.

![delete_payment_method](https://github.com/Expensify/App/assets/31413407/aa748596-e703-4b71-9dea-5905cc22706d)

If everyone agrees, I will update my proposal to add the changes required for using the ThreeDotsMenu component in it.

**Comment by muttmuure** [comment] 2023-05-23 16:43
Out of office this week, picking this up when I'm back

**Comment by muttmuure** [comment] 2023-06-01 11:31
Back in office

**Comment by muttmuure** [comment] 2023-06-01 16:04
I can reproduce this but am happy to defer to @thesahindia - I think we should feel free to reopen if discussions go another way and this is still happening, but I am going to close for now.

**Closed by muttmuure** 2023-06-01 16:04 UTC
Labels: Daily, Bug
