### ISSUE TITLE
[$250] Split - No spacing between username + email address and split amount on confirmation page

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#42191] opened 2024-05-15 13:00 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.74-0
**Reproducible in staging?:** Y
**Reproducible in production?:** N
**If this was caught during regression testing, add the test name, ID and link from TestRail:** N/A
**Issue reported by:** Applause - Internal Team

## Action Performed:
Precondition:
- User has long email address
1. Go to staging.new.expensify.com
2. Open a chat with user that also has long email address
3. Click + > Split expense
4. Enter amount > Next

## Expected Result:
There should be some spacing between username + email address and the split amount (production behavior) on the confirmation page

## Actual Result:
There is no spacing between username + email address and the split amount on the confirmation page

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [x] Android: mWeb Chrome
- [x] iOS: Native
- [x] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details> 

https://github.com/Expensify/App/assets/78819774/174308be-e4a2-4a5b-b9bc-4d002447ee89

 
[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01b8b1885e9bbd36c6</li>
        <li>Upwork Job ID: 1790789501118193664</li>
        <li>Last Price Increase: 2024-05-15</li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @allroundexperts</details>

**Comment by lanitochka17** [comment] 2024-05-15 13:02
@danieldoglas  FYI I haven't added the External label as I wasn't 100% sure about this issue. Please take a look and add the label if you agree it's a bug and can be handled by external contributors

**Comment by lanitochka17** [comment] 2024-05-15 13:03
We think that this bug might be related to #vip-split

**Comment by samilabud** [comment] 2024-05-15 17:33
It doesn't seem to be happening in the current main branch (only in staging):

https://github.com/Expensify/App/assets/5216036/a6fef288-4a31-4f63-a967-05248be30f8c

**Comment by srikarparsi** [comment] 2024-05-15 18:12
Hm that's true, the cause looks like it comes from this [PR](https://github.com/Expensify/App/pull/40785#issuecomment-2104058839) but trying to find what PR might've fixed it so that we can CP it.

**Comment by srikarparsi** [comment] 2024-05-15 21:14
Ah it was this PR which [fixed](https://github.com/Expensify/App/pull/41077) it. It's a pretty big PR so I'm not sure if CPing it is worth it since it might create new blockers. This is a pretty small issue so I think it might be better to just wait until QA finishes for the PR. Will check internally.

**Comment by srikarparsi** [comment] 2024-05-15 22:01
Removing the deploy blocker as per this [discussion](https://expensify.slack.com/archives/C03TQ48KC/p1715808028879119). Will wait for this [PR](https://github.com/Expensify/App/pull/41077) to hit staging and will check back.

**Comment by srikarparsi** [comment] 2024-05-21 18:49
Still waiting on the merge freeze for this [PR](https://github.com/Expensify/App/pull/41077) to hit staging.

**Comment by srikarparsi** [comment] 2024-05-23 18:54
The [PR](https://github.com/Expensify/App/pull/41077) hit staging and it looks good now. Closing this out.

<img width="375" alt="image" src="https://github.com/Expensify/App/assets/48188732/c85d6e24-ca3d-44df-8071-b3810b5d9d7e">

**Closed** 2024-05-23 18:54 UTC
Labels: Engineering, Daily
