### ISSUE TITLE
[HOLD for payment 06-07-2023] Editing the message with attachment before sending caused the message to be overwritten

### ISSUE THREAD

**Issue by kavimuru** [Expensify/App#19379] opened 2023-05-22 14:09 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:

1. Open [staging.new.expensify.com](http://staging.new.expensify.com/)
2. Send an attachment to a chat
3. Before the attachment got uploaded, edit the "Uploading attachment..." message with Arrow Up key
4. After some times, press Enter

## Expected Result : 
Image should not be removed and the image still persists since message with attachments shouldn't be able to be edited
## Actual Result : 
The image is changed into "Uploading attachment..." message

## Workaround:
Can the user still use Expensify without this being fixed? Have you informed them of the workaround?

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [x] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 1.3.16-6
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/43996225/f66b892a-04d3-4190-8317-d28b39dbe413

https://github.com/Expensify/App/assets/43996225/8eddedf6-a4a9-485e-84ae-7ea278b91003

**Expensify/Expensify Issue URL:**
**Issue reported by:** @kerupuksambel
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1684468856653929

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~0152e084e6db9ed6cd</li>
        <li>Upwork Job ID: 1661421473852272640</li>
        <li>Last Price Increase: 2023-05-31</li>
    </ul>
</details>

**Comment by stephanieelliott** [comment] 2023-05-24 17:19
Looks like this one already has a proposal in the scrollback @s77rt

**Comment by s77rt** [comment] 2023-05-24 22:41
@Ollyws Thanks for the proposal. Your RCA is correct and the suggested fix looks good. Let's do both:
- Consider ongoing attachment upload as attachments (prevent edit). [Code ref](https://github.com/Expensify/App/blob/1d9cf24256c0f4d429b44ba68faf581cc3542768/src/libs/isReportMessageAttachment.js#L16).
- Consider ongoing attachment upload as non-downloadable (prevent download). [Code ref](https://github.com/Expensify/App/blob/fc6594a4010a3d2e9ba462a0a89e9d862577de37/src/pages/home/report/ContextMenu/ContextMenuActions.js#L91).

:ribbon: :eyes: :ribbon: C+ reviewed

cc @srikarparsi

**Comment by s77rt** [comment] 2023-05-24 22:55
I think this is a regression from https://github.com/Expensify/App/issues/19379. It should be fixed as a follow up since the regression period is not over yet.

**Comment by eh2077** [comment] 2023-05-24 23:48
@thesahindia Should be put this on hold? Because I saw you mentioned 

> `Uploading attachment...` will be removed.

in slack comment https://expensify.slack.com/archives/C049HHMV9SM/p1684727952017239?thread_ts=1684691792.176519&cid=C049HHMV9SM

**Comment by s77rt** [comment] 2023-05-25 08:56
So we are likely going to hold in favour of https://github.com/Expensify/App/issues/9402.

**Comment by s77rt** [comment] 2023-05-25 17:05
@dangrous That issue is on `Monthly` priority so it may take some time indeed. As for the process on fixing this, yes I think @eh2077 should raise a follow up PR. I have commented on https://github.com/Expensify/App/issues/17289 and provided possible solution.

**Comment by michaelhaxhiu** [comment] 2023-05-25 17:43
@Ollyws you'd receive compensation if we use your proposal, even if you aren't the one implementing it. Let's decide what's most efficient for "who implements it now" as a collective. Technically speaking, it's the responsibility of the individual who introduced the regression. But let's do what's more efficient to fix this, and the individual who introduced this will be disqualified from getting a _payment bonus_.

As for payment of the bug report - we will pay the bug reporter for discovery of the regression. We always want to encourage discovery of bugs.

**Comment by srikarparsi** [comment] 2023-05-25 18:13
It seems like the PR is already in progress [here](https://github.com/Expensify/App/pull/19618/files) by @eh2077. I think this is fine as he is fixing his regression and we could compensate @Ollyws for the idea.

**Comment by s77rt** [comment] 2023-05-29 11:55
Not overdue. [PR](https://github.com/Expensify/App/pull/19618) is being worked on.

**Comment by srikarparsi** [comment] 2023-05-31 16:43
^^

**Comment by s77rt** [comment] 2023-05-31 17:07
PR is merged. Can we change the title to this to HOLD for payment?

**Comment by stephanieelliott** [comment] 2023-06-07 16:22
All paid, thanks guys!

**Closed by stephanieelliott** 2023-06-07 16:22 UTC
Labels: External, Daily, Bug
