### ISSUE TITLE
mWeb/Safari - Search- Search input field is not auto-focused when tapping Search icon

### ISSUE THREAD

**Issue by IuliiaHerets** [Expensify/App#53783] opened 2024-12-09 19:24 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 9.0.73-0
**Reproducible in staging?:** Yes
**Reproducible in production?:** No
**If this was caught on HybridApp, is this reproducible on New Expensify Standalone?:** N/A
**If this was caught during regression testing, add the test name, ID and link from TestRail:** https://github.com/Expensify/App/pull/53198
**Email or phone of affected tester (no customers):** N/A
**Issue reported by:** Applause Internal Team

## Action Performed:
1. Navigate to staging.new.expensify.com and sign in with existing gmail account.
2. Go to Inbox and tap Search icon at the top right corner.
3. Go to Search tab and tap Search icon.

## Expected Result:
Search input field is auto-focused when tapping Search icon

## Actual Result:
Search input field is not auto-focused when tapping Search icon

## Workaround:
Unknown

## Platforms:
- [ ] Android: Standalone
- [ ] Android: HybridApp
- [ ] Android: mWeb Chrome
- [ ] iOS: Standalone
- [ ] iOS: HybridApp
- [x] iOS: mWeb Safari
- [ ] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

https://github.com/user-attachments/assets/0f18e14d-2700-4629-9a46-682ae3b54abb

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by tgolen** [comment] 2024-12-09 20:47
Thanks! From looking through the PRs, [this PR](https://github.com/Expensify/App/pull/53198) looks like a good candidate. It deals with the search input field and focus functionality.

@Kicu @rojiphil

**Comment by luacmartins** [comment] 2024-12-09 20:53
Yea, I agree that that's likely the offending PR. Let's get a fix up for it @Kicu

**Comment by rojiphil** [comment] 2024-12-10 02:31
I am not able to reproduce this in the latest staging (v9.0.73-6) version of mWeb safari. 
@Kicu Can you also please check?

https://github.com/user-attachments/assets/a56a0d57-5356-4b9d-938c-9d145ebc0444

**Comment by Kicu** [comment] 2024-12-10 08:36
Will check later today 👍

**Comment by Kicu** [comment] 2024-12-10 15:25
I have tested this on staging using my Iphone (Safari, ios `17.6.1`) and I was not able to reproduce.
Accessing Search from: Inbox, Search Page, Setting/workspaces and a few others always focuses the Input for me.

**Comment by tgolen** [comment] 2024-12-10 15:43
@IuliiaHerets Could you please give a little bit more information on the iPhone version and iOS version that this is reproducible on?

**Comment by luacmartins** [comment] 2024-12-10 18:41
I'm unable to reproduce this as well. Tried on iOS native, mWeb safari and mWeb chrome.

**Comment by IuliiaHerets** [comment] 2024-12-10 19:27
@tgolen Tester used iPhone 15 18.1.1/Safari

**Comment by tgolen** [comment] 2024-12-11 17:25
@Kicu Would it be possible to update to iOS 18.1.1 and try reproducing it again?

**Comment by luacmartins** [comment] 2024-12-11 17:30
Still can't reproduce on mWeb safari/chrome iOS 18.1.1

**Comment by tgolen** [comment] 2024-12-11 18:57
OK, I am going to close this out for now then until it can be more widely reproduced.

**Closed by tgolen** 2024-12-11 18:57 UTC
Labels: Engineering, Daily, Bug
