### ISSUE TITLE
[HOLD for payment 2024-10-22] [$250] Book travel - Report screen changes to profile view when clicking Country field

### ISSUE THREAD

**Issue by IuliiaHerets** [Expensify/App#50155] opened 2024-10-03 14:39 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 9.0.44-0
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**Email or phone of affected tester (no customers):** applausetester+kh0110001@applause.expensifail.com
**Issue reported by:** Applause Internal Team

## Action Performed:
1. Go to staging.new.expensify.com
2. Go to FAB > Book travel.
3. Click Book travel.
4. Click Country.

## Expected Result:
The report screen in the background will not change to profile page.

## Actual Result:
The report screen in the background changes to profile page while LHN remains the same after opening Country RHP.

## Workaround:
Unknown

## Platforms:

- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

https://github.com/user-attachments/assets/cb3402f7-db60-4a4a-8783-28b9d1fd2fc3

  
</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~021843246313566765560</li>
        <li>Upwork Job ID: 1843246313566765560</li>
        <li>Last Price Increase: 2024-10-07</li>
<li>Automatic offers: </li>
<ul>
<li>dukenv0307 | Contributor | 104317443</li>
</ul></li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @trjExpensify</details>

**Comment by IuliiaHerets** [comment] 2024-10-03 14:39
We think that this bug might be related to #vip-travel

**Comment by bernhardoj** [comment] 2024-10-03 15:09
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
Report screen changes to profile screen when open the Country page from the book travel page.

### What is the root cause of that problem?
By default, the address country RHP maps to the profile screen.
https://github.com/Expensify/App/blob/91f610cefd1f2d8665fdc47a961b367eebacb93c/src/libs/Navigation/linkingConfig/CENTRAL_PANE_TO_RHP_MAPPING.ts#L5-L21

But we have a logic to find the matching central pane screen based on the `backTo` params.
https://github.com/Expensify/App/blob/91f610cefd1f2d8665fdc47a961b367eebacb93c/src/libs/Navigation/linkingConfig/getAdaptedStateFromPath.ts#L114-L139

In our case, the last backTo param is the travel page which doesn't have a central pane screen mapping, which will later be defaulted to the report screen.
https://github.com/Expensify/App/blob/91f610cefd1f2d8665fdc47a961b367eebacb93c/src/libs/Navigation/linkingConfig/getAdaptedStateFromPath.ts#L203

However, the result is ignored because of `isRHPinState` is false here.
https://github.com/Expensify/App/blob/91f610cefd1f2d8665fdc47a961b367eebacb93c/src/libs/Navigation/linkingConfig/getAdaptedStateFromPath.ts#L119-L125

It's because stateForBackTo.routes contains [BottomTabNavigator, RHPNavigator], so always accessing the first index won't work. We can just remove `isRHPinState` because we already have rhpNavigator which already finds RHP inside stateForBackTo.routes.

### What changes do you think we should make in order to solve the problem?

Remove the `isRHPInState`. We previously fixed this before, but the `isRHPinState` is reintroduced in https://github.com/Expensify/App/pull/49534, specifically [this changes](https://github.com/Expensify/App/pull/49534/files#diff-431da5317a5ef6f078e6a905c55de8e3387c1c41a3abab9cf749b23d71b45296). I believe it's a bad merge.

**Comment by trjExpensify** [comment] 2024-10-07 11:05
Filing this one under vip-travel. CC: @stitesExpensify

**Comment by yoodule-dev** [comment] 2024-10-07 13:50
### Proposal

**Please re-state the problem that we are trying to solve in this issue:**  
When a user clicks the "Country" field from the "Book Travel" screen, the background report screen unexpectedly changes to the profile view. The Left-Hand Navigation (LHN) remains static, creating an inconsistent user experience. The expected behavior is for the report screen to stay visible while only the right-hand panel (RHP) updates to show the country selection modal.

**What is the root cause of that problem?**  
The problem is linked to the logic within the `getAdaptedStateFromPath` function located in [`getAdaptedStateFromPath.ts`](https://github.com/Expensify/App/blob/main/src/libs/Navigation/linkingConfig/getAdaptedStateFromPath.ts). Specifically, there are two key issues:

1. **Incorrect `backTo` Parameter Handling:**  
   The `backTo` parameter is responsible for determining the target screen for the central pane when the RHP is opened. In the case of the "Book Travel" screen, the `backTo` parameter does not have a defined mapping for this central pane, which causes the navigation logic to default incorrectly to the profile screen.

2. **Flawed `isRHPinState` Check:**  
   In the same file, the code section between [Lines 119-125](https://github.com/Expensify/App/blob/main/src/libs/Navigation/linkingConfig/getAdaptedStateFromPath.ts#L119-L125) uses the condition `isRHPinState` to check whether the first route in `stateForBackTo.routes` is `NAVIGATORS.RIGHT_MODAL_NAVIGATOR`. This assumption is problematic because the first route may not always correspond to the RHP navigator, leading to the navigation logic falling back incorrectly to the profile screen.

**What changes do you think we should make in order to solve the problem?**

### Option A: Refactor the Navigation Logic

1. **Remove the `isRHPinState` Condition**  
   The presence of `rhpNavigator` in `stateForBackTo.routes` already indicates that the RHP is active, making the `isRHPinState` check redundant. Removing this check will prevent incorrect fallback behavior and ensure that the correct central pane is maintained when opening the "Country" field modal.

   - **File:** [`getAdaptedStateFromPath.ts`](https://github.com/Expensify/App/blob/main/src/libs/Navigation/linkingConfig/getAdaptedStateFromPath.ts)  
   - **Code Location:** [Lines 119-125](https://github.com/Expensify/App/blob/main/src/libs/Navigation/linkingConfig/getAdaptedStateFromPath.ts#L119-L125).

   **Before:**
   ```javascript
   if (rhpNavigator && rhpNavigator.state) {
       const isRHPinState = stateForBackTo.routes.at(0)?.name === NAVIGATORS.RIGHT_MODAL_NAVIGATOR;
       if (isRHPinState) {
           return getMatchingRootRouteForRHPRoute(findFocusedRoute(stateForBackTo) as NavigationPartialRoute);
       }
   }
   ```

   **After:**
   ```javascript
   if (rhpNavigator && rhpNavigator.state) {
       return getMatchingRootRouteForRHPRoute(findFocusedRoute(stateForBackTo) as NavigationPartialRoute);
   }
   ```

   By removing the `isRHPinState` check, the logic ensures that the RHP correctly matches to its expected root route, preventing the fallback to the profile view.

2. **Update the `backTo` Parameter Logic for Central Pane Mapping**  
   Modify the logic handling the `backTo` parameter to validate that it only points to valid central pane screens. If no valid central pane mapping exists for the "Book Travel" screen, the code should maintain the current screen state or provide a fallback that does not revert to the profile screen.

   **Implementation:**
   ```javascript
   // Adjust the fallback to avoid defaulting to the profile screen.
   matchingRootRoute = matchingRootRoute ?? (!isNarrowLayout ? {name: SCREENS.REPORT} : undefined);
   ```

3. **Separate Logic for Parsing and Navigation Handling**  
   Refactor the existing code into two distinct functions:
   - **`parseNavigationParams`**: This function will handle parsing the `backTo` parameter and ensuring it aligns with valid central pane mappings.
   - **`handleRHPNavigation`**: This function will execute the actual navigation logic based on the parameters parsed, improving code clarity and maintainability.

### Option B: Validate and Adjust Navigation in `ReportActionCompose`

We could add validation for the `backTo` parameter directly in the `ReportActionCompose` component, similar to how we currently validate `maxCommentLength`.

1. **Modify `onValueChange` in [`ReportActionCompose.tsx`](https://github.com/Expensify/App/blob/main/src/pages/home/report/ReportActionCompose/ReportActionCompose.tsx)**

   **Lines:** [512-517](https://github.com/Expensify/App/blob/main/src/pages/home/report/ReportActionCompose/ReportActionCompose.tsx#L512-L517)
   ```javascript
   onValueChange={(value) => { 
       if (value.length === 0 && isComposerFullSize) { 
           Report.setIsComposerFullSize(reportID, false); 
       } 
       validateCommentMaxLength(value, {reportID}); 
   }} 
   ```

2. **Introduce `validateNavigation` Function:**  
   Create a `validateNavigation` function to ensure that the `backTo` parameter matches valid central pane screens before allowing state updates. If it doesn’t, the function will prevent navigation changes and display an error.

   ```javascript
   const validateNavigation = (route) => {
       const isValidCentralPane = isCentralPaneName(route.name);
       if (!isValidCentralPane) {
           showError('Invalid Navigation State');
           return false;
       }
       return true;
   };
   ```

3. **Implement Error Handling Component:**  
   Develop a `NavigationError` component to display error messages in the UI when invalid navigation states are detected, maintaining a consistent user experience.

### Option C: Pre-Validation in `ReportFooter`

Add validation logic directly in the `ReportFooter` component before state changes are executed. This ensures that invalid states do not propagate and provides immediate feedback to the user if an issue is detected.

**Comparison of Options:**

- **Option A** is the most straightforward and effective approach, requiring minimal changes while ensuring correctness. This option, however, will need regression testing to verify that no other parts of the app are affected by the removal of the `isRHPinState` check.
- **Options B and C** offer enhanced validation but add complexity. They ensure that invalid states are caught early, and they also provide feedback directly within the UI, which can improve the user experience. These options might be considered if further testing reveals issues with Option A.

### Recommendation

I recommend starting with **Option A** due to its simplicity and direct alignment with the root cause identified. If issues persist or further edge cases are discovered, expanding to **Option B** or **Option C** may be appropriate for enhanced validation and improved error messaging.

**Comment by yoodule-dev** [comment] 2024-10-07 13:51
### Proposal

**Please re-state the problem that we are trying to solve in this issue:**  
When a user clicks the "Country" field from the "Book Travel" screen, the background report screen unexpectedly changes to the profile view. The Left-Hand Navigation (LHN) remains static, creating an inconsistent user experience. The expected behavior is for the report screen to stay visible while only the right-hand panel (RHP) updates to show the country selection modal.

**What is the root cause of that problem?**  
The problem is linked to the logic within the `getAdaptedStateFromPath` function located in [`getAdaptedStateFromPath.ts`](https://github.com/Expensify/App/blob/main/src/libs/Navigation/linkingConfig/getAdaptedStateFromPath.ts). Specifically, there are two key issues:

1. **Incorrect `backTo` Parameter Handling:**  
   The `backTo` parameter is responsible for determining the target screen for the central pane when the RHP is opened. In the case of the "Book Travel" screen, the `backTo` parameter does not have a defined mapping for this central pane, which causes the navigation logic to default incorrectly to the profile screen.

2. **Flawed `isRHPinState` Check:**  
   In the same file, the code section between [Lines 119-125](https://github.com/Expensify/App/blob/main/src/libs/Navigation/linkingConfig/getAdaptedStateFromPath.ts#L119-L125) uses the condition `isRHPinState` to check whether the first route in `stateForBackTo.routes` is `NAVIGATORS.RIGHT_MODAL_NAVIGATOR`. This assumption is problematic because the first route may not always correspond to the RHP navigator, leading to the navigation logic falling back incorrectly to the profile screen.

**What changes do you think we should make in order to solve the problem?**

### Option A: Refactor the Navigation Logic

1. **Remove the `isRHPinState` Condition**  
   The presence of `rhpNavigator` in `stateForBackTo.routes` already indicates that the RHP is active, making the `isRHPinState` check redundant. Removing this check will prevent incorrect fallback behavior and ensure that the correct central pane is maintained when opening the "Country" field modal.

   - **File:** [`getAdaptedStateFromPath.ts`](https://github.com/Expensify/App/blob/main/src/libs/Navigation/linkingConfig/getAdaptedStateFromPath.ts)  
   - **Code Location:** [Lines 119-125](https://github.com/Expensify/App/blob/main/src/libs/Navigation/linkingConfig/getAdaptedStateFromPath.ts#L119-L125).

   **Before:**
   ```javascript
   if (rhpNavigator && rhpNavigator.state) {
       const isRHPinState = stateForBackTo.routes.at(0)?.name === NAVIGATORS.RIGHT_MODAL_NAVIGATOR;
       if (isRHPinState) {
           return getMatchingRootRouteForRHPRoute(findFocusedRoute(stateForBackTo) as NavigationPartialRoute);
       }
   }
   ```

   **After:**
   ```javascript
   if (rhpNavigator && rhpNavigator.state) {
       return getMatchingRootRouteForRHPRoute(findFocusedRoute(stateForBackTo) as NavigationPartialRoute);
   }
   ```

   By removing the `isRHPinState` check, the logic ensures that the RHP correctly matches to its expected root route, preventing the fallback to the profile view.

2. **Update the `backTo` Parameter Logic for Central Pane Mapping**  
   Modify the logic handling the `backTo` parameter to validate that it only points to valid central pane screens. If no valid central pane mapping exists for the "Book Travel" screen, the code should maintain the current screen state or provide a fallback that does not revert to the profile screen.

   **Implementation:**
   ```javascript
   // Adjust the fallback to avoid defaulting to the profile screen.
   matchingRootRoute = matchingRootRoute ?? (!isNarrowLayout ? {name: SCREENS.REPORT} : undefined);
   ```

3. **Separate Logic for Parsing and Navigation Handling**  
   Refactor the existing code into two distinct functions:
   - **`parseNavigationParams`**: This function will handle parsing the `backTo` parameter and ensuring it aligns with valid central pane mappings.
   - **`handleRHPNavigation`**: This function will execute the actual navigation logic based on the parameters parsed, improving code clarity and maintainability.

### Option B: Validate and Adjust Navigation in `ReportActionCompose`

We could add validation for the `backTo` parameter directly in the `ReportActionCompose` component, similar to how we currently validate `maxCommentLength`.

1. **Modify `onValueChange` in [`ReportActionCompose.tsx`](https://github.com/Expensify/App/blob/main/src/pages/home/report/ReportActionCompose/ReportActionCompose.tsx)**

   **Lines:** [512-517](https://github.com/Expensify/App/blob/main/src/pages/home/report/ReportActionCompose/ReportActionCompose.tsx#L512-L517)
   ```javascript
   onValueChange={(value) => { 
       if (value.length === 0 && isComposerFullSize) { 
           Report.setIsComposerFullSize(reportID, false); 
       } 
       validateCommentMaxLength(value, {reportID}); 
   }} 
   ```

2. **Introduce `validateNavigation` Function:**  
   Create a `validateNavigation` function to ensure that the `backTo` parameter matches valid central pane screens before allowing state updates. If it doesn’t, the function will prevent navigation changes and display an error.

   ```javascript
   const validateNavigation = (route) => {
       const isValidCentralPane = isCentralPaneName(route.name);
       if (!isValidCentralPane) {
           showError('Invalid Navigation State');
           return false;
       }
       return true;
   };
   ```

3. **Implement Error Handling Component:**  
   Develop a `NavigationError` component to display error messages in the UI when invalid navigation states are detected, maintaining a consistent user experience.

### Option C: Pre-Validation in `ReportFooter`

Add validation logic directly in the `ReportFooter` component before state changes are executed. This ensures that invalid states do not propagate and provides immediate feedback to the user if an issue is detected.

**Comparison of Options:**

- **Option A** is the most straightforward and effective approach, requiring minimal changes while ensuring correctness. This option, however, will need regression testing to verify that no other parts of the app are affected by the removal of the `isRHPinState` check.
- **Options B and C** offer enhanced validation but add complexity. They ensure that invalid states are caught early, and they also provide feedback directly within the UI, which can improve the user experience. These options might be considered if further testing reveals issues with Option A.

### Recommendation

I recommend starting with **Option A** due to its simplicity and direct alignment with the root cause identified. If issues persist or further edge cases are discovered, expanding to **Option B** or **Option C** may be appropriate for enhanced validation and improved error messaging.

**Comment by rlinoz** [comment] 2024-10-23 19:21
Personally I think that is a very odd test to have, I think we don't need one for this bug.

**Comment by trjExpensify** [comment] 2024-10-23 22:11
Standalone as a test, I agree. But in some wider regression test about Book travel, having a one liner added doesn't sound so bad. 

>The PR that introduced the bug has been identified. Link to the PR: N/A
>The offending PR has been commented on, pointing out the bug it caused and why, so the author and reviewers can learn from the mistake. Link to comment: N/A

@dukenv0307 can you provide context behind these "N/A"'s please?

**Comment by trjExpensify** [comment] 2024-10-24 23:16
Thanks! Confirming the payment summary as follows: 

- $250 to @bernhardoj for the fix (go ahead and request!)
- $250 to @dukenv0307 for the C+ review (paid!)

Closing!

**Closed by trjExpensify** 2024-10-24 23:16 UTC
Labels: External, Daily, Awaiting Payment, Bug

**Comment by trjExpensify** [comment] 2024-10-24 23:32
^^ @mallenexpensify what is this?

**Comment by bernhardoj** [comment] 2024-10-25 02:25
Requested in ND.

**Comment by JmillsExpensify** [comment] 2024-10-25 11:43
$250 approved for @bernhardoj

**Comment by mallenexpensify** [comment] 2024-10-25 19:05
@trjExpensify posted about in #bug-zero [here](https://expensify.slack.com/archives/C01SKUP7QR0/p1729883091032869)
