### ISSUE TITLE
[HOLD for payment 2024-04-09] [$500] [Mobile] Don't immidiately prompt for Camera permission in Scan Receipt flow

### ISSUE THREAD

**Issue by Julesssss** [Expensify/App#37737] opened 2024-03-05 12:14 UTC
Do not automatically prompt users for the camera permission until the user selects the 'Continue' button -- to prevent permission denials

iOS | Android
-- | --
![E4ED35A0-91E2-4409-9359-6DC526D31727](https://github.com/Expensify/App/assets/10736861/83b74574-7917-4b49-bddc-9b126e8d4c80) | ![Screenshot_20240305-113921](https://github.com/Expensify/App/assets/10736861/c43dc98c-077d-4191-9c47-fd1b3d3fe0f2)

If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
- Have camera permission disabled
- Request Money
- Switch to Scan Receipt

## Expected Result:
- Nothing should happen

## Actual Result:
- User is prompted for the camera permission before they have even seen the Explainer UI

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [ ] Android: mWeb Chrome
- [x] iOS: Native
- [ ] iOS: mWeb Safari
- [ ] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01bc79d21437eb7104</li>
        <li>Upwork Job ID: 1764987970290671616</li>
        <li>Last Price Increase: 2024-03-05</li>
    </ul>
</details>

**Comment by ShridharGoel** [comment] 2024-03-05 12:27
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
Don't immediately prompt for Camera permission in Scan Receipt.

### What is the root cause of that problem?
`refreshCameraPermissionStatus` is called in below code directly.
```
useEffect(() => {
        const refreshCameraPermissionStatus = (shouldAskForPermission = false) => {
            CameraPermission.getCameraPermissionStatus()
                .then((res) => {
                    // In android device app data, the status is not set to blocked until denied twice,
                    // due to that the app will ask for permission twice whenever users opens uses the scan tab
                    setCameraPermissionStatus(res);
                    if (shouldAskForPermission && !askedForPermission.current) {
                        askedForPermission.current = true;
                        askForPermissions(false);
                    }
                })
                .catch(() => setCameraPermissionStatus(RESULTS.UNAVAILABLE));
        };

        // Check initial camera permission status
        refreshCameraPermissionStatus(true);

        // Refresh permission status when app gain focus
        const subscription = AppState.addEventListener('change', (appState) => {
            if (appState !== 'active') {
                return;
            }

            refreshCameraPermissionStatus();
        });

        return () => {
            subscription.remove();
        };
    }, []);
```
### What changes do you think we should make in order to solve the problem?
`refreshCameraPermissionStatus` should be called when continue button is clicked.

**Comment by ahmedGaber93** [comment] 2024-03-05 12:55
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
Don't immidiately prompt for Camera permission in Scan Receipt flow
### What is the root cause of that problem?
when scan tab amount in useEffect we call  `refreshCameraPermissionStatus` with parameter `shouldAskForPermission`  = true  
https://github.com/Expensify/App/blob/9411a08168d53df44a957fd8bb86fd9a363b25b4/src/pages/iou/request/step/IOURequestStepScan/index.native.js#L138-L139
### What changes do you think we should make in order to solve the problem?
in useEffect don't pass `shouldAskForPermission` with true to prevent prompt for Camera permission when scan tab amount
```javascript
 //refreshCameraPermissionStatus(true); 
 refreshCameraPermissionStatus(); 
```


### What alternative solutions did you explore? (Optional)

**Comment by Julesssss** [comment] 2024-03-05 12:59
> We should remove the logic to ask permission in refreshCameraPermissionStatus function and use the old logic below or we only apply it for Android device

@dukenv0307 perhaps I missunderstand, but if we only apply it for Android, wouldn't the issue still exist for Android?

**Comment by cubuspl42** [comment] 2024-03-06 07:36
@dukenv0307 

> We should remove the logic to ask permission in refreshCameraPermissionStatus function and **use the old logic below**

You just threw the term "old" without any context. What old logic? When and why was this logic removed?

> or we only apply it for Android device

Again, you mentioned potential Android-specific behavior without any context. Why would we want to be Android-specific? I can see that this was brought in the discussion above; ensure to include the minimal necessary context in the proposal itself.

**Comment by cubuspl42** [comment] 2024-03-06 08:07
@dukenv0307 

Thank you!

I agree that the crucial part is ensuring to keep https://github.com/Expensify/App/issues/34750 fixed while improving the user experience at the same time. We'll have to double-check this on the implementation phase.

**Comment by cubuspl42** [comment] 2024-03-06 08:08
I approve the proposal by @dukenv0307 

C+ reviewed 🎀 👀 🎀

**Comment by Julesssss** [comment] 2024-03-06 09:42
> ❌ There was an error making the offer to @cubuspl42 for the Reviewer role. The BZ member will need to manually hire the contributor.

> ❌ There was an error making the offer to @dukenv0307 for the Contributor role. The BZ member will need to manually hire the contributor.

FYI @stephanieelliott

**Comment by stephanieelliott** [comment] 2024-03-11 22:45
PR is actively being reviewed.

**Comment by cubuspl42** [comment] 2024-03-14 10:18
@Julesssss 

Is there a difference in the expected behavior between mWeb and Native? Don't we want to show the Explainer UI on mWeb and delay the permission prompt, too?

**Comment by Julesssss** [comment] 2024-03-14 10:44
> Is there a difference in the expected behavior between mWeb and Native? Don't we want to show the Explainer UI on mWeb and delay the permission prompt, too?

I don't believe we allow users to use the camera on Desktop/Web, so no we shouldn't be showing the prompt.

**Comment by stephanieelliott** [comment] 2024-03-19 01:30
Looks like all PR changes requests have been addressed, just waiting for internal approval

**Comment by cubuspl42** [comment] 2024-03-19 10:25
I don't think we're there yet. I [asked for clarification](https://github.com/Expensify/App/pull/37817#issuecomment-2006716854) of an important bit. But we're actively working on this.

**Comment by cubuspl42** [comment] 2024-04-02 08:06
PR merged and deployed to staging 🚀

**Comment by cubuspl42** [comment] 2024-04-08 09:21
- The PR that introduced the bug has been identified. Link to the PR:
    - This bug was a Native/mWeb inconsistency, I don't think any specific PR introduced it 
- The offending PR has been commented on, pointing out the bug it caused and why, so the author and reviewers can learn from the mistake. Link to comment:
    - N/A
- A discussion in #expensify-bugs has been started about whether any other steps should be taken (e.g. updating the PR review checklist) in order to catch this type of bug sooner. Link to discussion:
    - No need for additional discussion
- Determine if we should create a regression test for this bug.
    - Up to the QA team
- If we decide to create a regression test for the bug, please propose the regression test steps to ensure the same bug will not reach production again.
    - Android Native / iOS Native / mWeb:
        - Reset app / web app permissions
        - Navigate to FAB > Request Money > Scan.
        - Confirm that the camera request permission prompt does not appear.
        - Click on the 'Continue' button or the 'Capture' icon.
        - Verify that the camera request permission prompt now appears.
        - Accept the permission and ensure that photo capture is possible.

**Comment by stephanieelliott** [comment] 2024-04-09 19:25
Hey @cubuspl42 @dukenv0307 please accept the Upwork offer when you get a chance https://www.upwork.com/jobs/~011f4474761d208ba4

**Comment by cubuspl42** [comment] 2024-04-10 10:04
Done 👍

**Comment by stephanieelliott** [comment] 2024-04-10 19:35
Thanks @cubuspl42, you've been paid. 

> ROLE: @dukenv0307 Upwork offer extended, please accept

@dukenv0307 bump on this!

**Comment by stephanieelliott** [comment] 2024-04-15 22:14
All paid! See summary here: https://github.com/Expensify/App/issues/37737#issuecomment-2045800619

**Closed by stephanieelliott** 2024-04-15 22:14 UTC
Labels: External, Daily, Overdue, Awaiting Payment, Bug
