### ISSUE TITLE
[HOLD App 35455][$500] Send money -  Not here page opens when opening Description in Send money flow

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#36342] opened 2024-02-12 15:19 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.40-0
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** Applause - Internal Team
**Slack conversation:**

**Issue found when executing PR** https://github.com/Expensify/App/pull/33601
## Action Performed:
1. Go to staging.new.expensify.com
2. Go to FAB > Send money
3. Enter amount and select participant
4. On confirmation page, click Description

## Expected Result:
Description editor opens without issue

## Actual Result:
Not here page shows up

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [x] Android: mWeb Chrome
- [x] iOS: Native
- [x] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details>  

https://github.com/Expensify/App/assets/78819774/3dbebc86-78f2-4340-96b1-ccd6d2449e0e

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~0169a121d63defc5fe</li>
        <li>Upwork Job ID: 1757179215235969024</li>
        <li>Last Price Increase: 2024-02-19</li>
    </ul>
</details>

**Comment by lanitochka17** [comment] 2024-02-12 15:20
We think that this bug might be related to [#vip-bills](https://expensify.enterprise.slack.com/archives/CSL3XBCCR)
CC @davidcardoza

**Comment by mananjadhav** [comment] 2024-02-12 15:37
@lanitochka17 I am able to reproduce this on production, but the GH states `Reproducible in production?: N`.

<img width="1512" alt="Screenshot 2024-02-12 at 9 06 41 PM" src="https://github.com/Expensify/App/assets/3069065/a5011c9a-070a-42ad-aba8-54557c36d66d">

**Comment by lanitochka17** [comment] 2024-02-12 15:54
sorry for confusion I can reproduce on Production too


https://github.com/Expensify/App/assets/78819774/e5a5745c-3d9c-4a86-a4ee-052bca44df5c

**Comment by srikarparsi** [comment] 2024-02-12 23:05
Sounds good, removing the deploy blocker label from this issue

**Comment by zoilorys** [comment] 2024-02-13 07:19
## Proposal

### Please re-state the problem that we are trying to solve in this issue.

During send money flow description is not opening.

### What is the root cause of that problem?

After looking into the implementation I noticed that there is actually no description step for creating a send request. The only implementation I could find is only for edit transaction flow. There is even no description route defined for `send/new` flow and it is hardcoded to navigate to description step in edit mode when clicking Description.

### What changes do you think we should make in order to solve the problem?

In order to fix this, we should add new `send/new/description/:reportID?` route (similar to already existing `send/new/amount/:reportID?`), and update `IOURequestStepDescription` component to support create scenario.

### What alternative solutions did you explore? (Optional)

**Comment by mananjadhav** [comment] 2024-02-13 07:37
Looks like it, and @DylanDylann is the original author as well as C+ here, so guessing they'll be able to confirm it.

**Comment by DylanDylann** [comment] 2024-02-14 17:50
[This PR](https://github.com/Expensify/App/pull/35455) (It's about to be merged) will be resolve this issue

**Comment by srikarparsi** [comment] 2024-02-20 04:56
On hold for this [PR](https://github.com/Expensify/App/pull/35455)

**Comment by DylanDylann** [comment] 2024-02-28 17:00
still on hold

**Comment by srikarparsi** [comment] 2024-03-08 02:45
Still on hold, asked for an ETA on the PR

**Comment by srikarparsi** [comment] 2024-03-19 04:08
[PR](https://github.com/Expensify/App/pull/35455) hit staging, no longer reproducible. Going to close this out.

**Closed** 2024-03-19 04:08 UTC
Labels: External, Engineering, Weekly, Help Wanted
