### ISSUE TITLE
[$250]  Markdown- Bold markdown is not rendered when copied from another app

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#46891] opened 2024-08-06 14:17 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 9.0.17-0
**Reproducible in staging?:** Y
**Reproducible in production?:** Y 
**Issue reported by:** Applause - Internal Team

## Action Performed:
An account signed in to newdot
1. Navigate to a chat app that supports Markdown (Example: Slack)
2. Send a message containing the bold markdown
3. Copy the text (CTRL + C) with markdown and navigate back to NewDot
4. Open any conversation and paste the copied text with CTRL + V into the compose box

## Expected Result:
The text is displayed with the bold markdown icon in the compose box and is rendered as bold when the text is sent

## Actual Result:
The text is not displayed with the bold markdown icon in the compose box and is not rendered as bold when the text is sent

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details> 

https://github.com/user-attachments/assets/80e35282-2e41-4df2-8a34-311387086e63

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01e87ca27ee2372740</li>
        <li>Upwork Job ID: 1821228929551530763</li>
        <li>Last Price Increase: 2024-08-14</li>
    </ul>
</details>

**Comment by lanitochka17** [comment] 2024-08-06 14:17
@sakluger  FYI I haven't added the External label as I wasn't 100% sure about this issue. Please take a look and add the label if you agree it's a bug and can be handled by external contributors

**Comment by bernhardoj** [comment] 2024-08-06 16:51
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
Copying bold text from another app (such as Slack) isn't pasted as a bold markdown which is inconsistent with other markdowns.

### What is the root cause of that problem?
The regex for bold and italic for example is pretty similar.
https://github.com/Expensify/expensify-common/blob/7351ac7e19f5cc8e694f8eb40768b9c6d6302852/lib/ExpensiMark.ts#L558-L564

The difference in bold markdown replacement is that it checks the `<strong>` or `<b>` HTML `style` attribute and doesn't render it as bold if the `style` doesn't have a font-weight of bold or 700.

https://github.com/Expensify/expensify-common/blob/7351ac7e19f5cc8e694f8eb40768b9c6d6302852/lib/ExpensiMark.ts#L565-L592

It's to fix https://github.com/Expensify/App/issues/41109 where copying text from gdocs is rendered as bold because gdocs text HTML is `b` but with a style of `font-weight: 400`.

The problem with the current bold replacement logic is that if a `style` attribute is found on the HTML tag, then the decision to render it as bold or not relies on the `style` attribute even though there is no `font-weight` style found. This causes any bold HTML tag that has a `style` but no `font-weight` to be rendered as not bold, for example:
```
<b>example</b> rendered as bold
<b style="font-size:10px">example</b> not rendered as bold
<b style="font-size:10px; font-weight:bold">example</b> rendered as bold
```

### What changes do you think we should make in order to solve the problem?

We must decide whether to render it as bold or not based on the `style` attribute only if the style has `font-weight` value, otherwise, we will render it as bold. To do that, update the regex [[1](https://github.com/Expensify/expensify-common/blob/7351ac7e19f5cc8e694f8eb40768b9c6d6302852/lib/ExpensiMark.ts#L579)] [[2](https://github.com/Expensify/expensify-common/blob/7351ac7e19f5cc8e694f8eb40768b9c6d6302852/lib/ExpensiMark.ts#L585)] to:
```
/style="([^"]*?\bfont-weight:\s*(\d+|bold|normal)[^"]*?)"/
```

**Comment by sakluger** [comment] 2024-08-12 22:44
@rushatgabhane thoughts on the proposal above?

**Comment by rushatgabhane** [comment] 2024-08-12 23:37
@bernhardoj font weight can be a number too right?

**Comment by bernhardoj** [comment] 2024-08-13 02:56
@rushatgabhane Yes it can. The regex in the proposal can handle that (`\d+`)

**Comment by sakluger** [comment] 2024-08-14 19:11
@rushatgabhane friendly bump.

**Comment by rushatgabhane** [comment] 2024-08-16 08:32
@bernhardoj's proposal LGTM 

🎀 👀 🎀

**Comment by bernhardoj** [comment] 2024-08-18 10:16
The expensify-common PR is ready

cc: @rushatgabhane

**Comment by sakluger** [comment] 2024-08-19 16:42
@rushatgabhane is OOO today - commenting to clear the Overdue label.

**Comment by bernhardoj** [comment] 2024-08-21 03:37
Opened the App PR, but I [hold](https://github.com/Expensify/App/pull/47764#issuecomment-2300582060) it.

**Comment by sakluger** [comment] 2024-08-24 02:02
Commenting for Melvin since I will be OOO until Aug 30. @bernhardoj let us know if you make any progress in the meantime.

**Comment by bernhardoj** [comment] 2024-08-30 03:18
PR is merged

**Comment by sakluger** [comment] 2024-09-10 21:22
The automation didn't work. The [PR](https://github.com/Expensify/App/pull/47764) was deployed on Aug 30, so payment was due on Sept 6.

**Comment by sakluger** [comment] 2024-09-10 21:24
Summarizing payment on this issue:

Contributor: @bernhardoj $250, please request on Newdot 
Contributor+: @rushatgabhane $250, please request on Newdot

**Comment by sakluger** [comment] 2024-09-10 21:24
@rushatgabhane can you please propose regression test steps if you think they are needed?

**Comment by bernhardoj** [comment] 2024-09-11 05:50
Requested in ND.

**Comment by rushatgabhane** [comment] 2024-09-11 12:17
no regression steps needed here. it's covered by Expensify markdown tests

**Comment by garrettmknight** [comment] 2024-09-11 19:13
$250 approved @rushatgabhane

**Comment by sakluger** [comment] 2024-09-16 18:48
No regression steps needed and all payments approved. We're good to close 👍

**Closed by sakluger** 2024-09-16 18:48 UTC
Labels: External, Daily, Overdue, Awaiting Payment, Bug
