### ISSUE TITLE
Room name does not support special characters

### ISSUE THREAD

**Issue by kavimuru** [Expensify/App#12653] opened 2022-11-10 21:09 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Proposal:
Update our rooms names to allow both dash - and underscore _ instead of just underscore as they do now. And also update our default when a user types a space from underscore to dash. I think dashes just look better than underscores

## Platform:

Where is this issue occurring?

- Web
- iOS
- Android
- Desktop App
- Mobile Web

**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** 

https://user-images.githubusercontent.com/43996225/201206243-0f893eca-c35b-4f60-84a2-1561db8ab0d8.mp4

**Expensify/Expensify Issue URL:** 
**Issue reported by:** @puneetlath 
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1668112427854869

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by Puneet-here** [comment] 2022-11-10 21:25
### Proposal 

Change the regex
`[^a-zA-Z\d_-]/g`
https://github.com/Expensify/App/blob/5401816f3781da2db128781ab92084ffffc589c8/src/components/RoomNameInput.js#L62

**Comment by JmillsExpensify** [comment] 2022-11-10 21:45
Not a bug, this is a design decision. Closing

**Closed by JmillsExpensify** 2022-11-10 21:45 UTC
Labels: Daily, NewFeature

**Comment by JmillsExpensify** [comment] 2022-11-10 21:46
Ah sorry I see now this doesn't have a `bug` label on it. I personally think we should put a freeze on all new features for WAQ so I'm keeping this closed.

**Comment by JmillsExpensify** [comment] 2022-11-10 21:51
@puneetlath feel free to re-open if you'd like. I think my concern is that any person working on a new feature isn't solving bugs. And we have a mountain of bugs in this repo that we need to maintain focus on for the duration of WAQ.
