### ISSUE TITLE
[$500] mweb - Chat - User navigates to LHN when refresh attachment page and hit Back button

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#34037] opened 2024-01-05 17:22 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.22-0
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** Applause - Internal Team
**Slack conversation:**

## Action Performed:
1. Open staging.new.expensify.com
2. Navigate to chat and add attachment
3. Open the attachment
4. Refresh the page
5. Tap Back button

## Expected Result:
User should navigate to chat conversation where attachment is open

## Actual Result:
User navigates to LHN

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [x] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [ ] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details> 

https://github.com/Expensify/App/assets/78819774/128002e0-9647-49c9-9160-1602636d1ff6

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01d7de26b158795e5d</li>
        <li>Upwork Job ID: 1743322006740606976</li>
        <li>Last Price Increase: 2024-01-05</li>
    </ul>
</details>

**Comment by shahinyan11** [comment] 2024-01-05 17:37
## Proposal

### Please re-state the problem that we are trying to solve in this issue.

### What is the root cause of that problem?
There is not back route for Report attachment screen as other routes 
### What changes do you think we should make in order to solve the problem?
We should add backTo param for `REPORT_ATTACHMENTS.getRoute` and pass backTo route  here  `const route = ROUTES.REPORT_ATTACHMENTS.getRoute(report.reportID, source);`

### What alternative solutions did you explore? (Optional)
N/A

**Comment by FitseTLT** [comment] 2024-01-05 17:38
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
 Chat - User navigates to LHN when refresh attachment page and hit Back button

### What is the root cause of that problem?
We are not passing the target report id here
https://github.com/Expensify/App/blob/7ae1ec7e74b908e6340bccaf7e42b0345d766711/src/pages/home/report/ReportAttachments.js#L46-L47
### What changes do you think we should make in order to solve the problem?

We should pass the target report id to the dismissModal
### What alternative solutions did you explore? (Optional)

**Comment by paultsimura** [comment] 2024-01-05 17:40
## Proposal

### Please re-state the problem that we are trying to solve in this issue.


### What is the root cause of that problem?
On mWeb, we use the `goBack` button to hide the modal, which triggers this action:

https://github.com/Expensify/App/blob/30061bd22c7655720b8e85824cdd88cf4585ac65/src/pages/home/report/ReportAttachments.js#L45-L49

When the page is refreshed, the navigation stack is cleared, so `Navigation.dismissModal` falls back to the LHN.

### What changes do you think we should make in order to solve the problem?
Here, we should pass the reportID as the targetReportId parameter:

```js
            onModalHide={() => {
                Navigation.dismissModal(reportID);
                // This enables Composer refocus when the attachments modal is closed by the browser navigation
                ComposerFocusManager.setReadyToFocus();
            }}
```

https://github.com/Expensify/App/blob/30061bd22c7655720b8e85824cdd88cf4585ac65/src/pages/home/report/ReportAttachments.js#L45-L49
### What alternative solutions did you explore? (Optional)

**Comment by bernhardoj** [comment] 2024-01-05 18:15
Added an alternative [solution](https://github.com/Expensify/App/issues/34037#issuecomment-1879060635)

**Comment by FitseTLT** [comment] 2024-01-05 19:25
Added alternative solution to deal with opening attachments via deeplink

**Comment by cubuspl42** [comment] 2024-01-09 10:03
@bernhardoj Thank you for the research regarding the issue https://github.com/Expensify/App/issues/25779!

Unluckily for you, I don't feel convinced by your solution. The contract of `dismissModal` becomes unclear when it ignores `targetReportID` just because it finds some other report route on the stack.

It feels cleaner to handle it on the call site, which @FitseTLT suggests. I know that he updated the proposal after you wrote yours, but I think this is acceptable per the process.

**Comment by abekkala** [comment] 2024-01-11 19:16
@thienlnam I realize that this is a real issue that should be fixed but I'm having a hard time placing it to a specific wave? Do you have a suggestion here?

**Comment by thienlnam** [comment] 2024-01-12 04:02
I'm with you - I'm not sure this would fall under a wave. Maybe vip-vsb which mostly focuses on chat improvements? But also looking at this bug, I'm not entirely convinced we need to address. Happy to go with whatever you decide here

**Comment by cubuspl42** [comment] 2024-01-12 10:00
I approve the solution by @FitseTLT

C+ reviewed 🎀 👀 🎀

**Comment by cubuspl42** [comment] 2024-01-12 10:00
@abekkala Let us know how we proceed with the classification of the issue!

**Comment by cubuspl42** [comment] 2024-01-12 11:08
Isn't this an unrelated problem? We currently depend on `Navigation.dismissModal` on `main`

**Comment by cubuspl42** [comment] 2024-01-15 11:49
@suneox 

Your solution has a better UX; we're not observing the intermediate state of the animation.

On the other hand, we're in the context of a corner case. While the app should continue to work as expected whenever the user refreshes the page, I don't think it is a high priority to polish the UX of such cases. You should never be _required_ to reload a single-page application manually, or we're doing something wrong.

The solution by @FitseTLT is a very simple fix for the discussed case, and we're not throwing away the `dismissModal` call, which has some logic inside. Speaking from experience, this logic might be needed, and removing it might cause an unexpected regression.

So, speaking pragmatically, I think we will want to favor solution's simplicity here.

Thank you for your proposal and describing its features in detail!

**Comment by abekkala** [comment] 2024-01-17 18:17
sorry, I agree this is not something we need to spend time on at this moment. Closing

**Closed by abekkala** 2024-01-17 18:17 UTC
Labels: External, Engineering, Daily, Help Wanted, Overdue, Bug
