### ISSUE TITLE
[$250] IOS/Android - App crashed after tap on download in optional menu

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#9010] opened 2022-05-13 23:28 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Launch the app
2. Log in with any account
3. Find the chat where you can download the file
4. Hold the finger on any type of file (mp4, png., mov)
5. Tap download

## Expected Result:
Able to download the file in optional menu

## Actual Result:
App crashed after tap on download in optional menu

## Workaround:
Unknown

## Platform:

Where is this issue occurring?

- iOS

**Version Number:** 1.1.61.2

**Reproducible in staging?:** Yes

**Reproducible in production?:** Yes

**Email or phone of affected tester (no customers):** 

**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Notes/Photos/Videos:** Any additional supporting documentation

https://user-images.githubusercontent.com/93399543/168401111-ea15d5c3-915d-46bb-92af-fe0bb366b986.MP4

**Expensify/Expensify Issue URL:** 

**Issue reported by:** Applause

**Slack conversation:** 

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by roryabraham** [comment] 2022-05-15 22:38
Seems like [this crash](https://console.firebase.google.com/u/1/project/expensify-chat/crashlytics/app/android:com.expensify.chat/issues/6b16c2248fae75df31013c91848765c1?time=last-seven-days&sessionEventKey=627EF7DE022100017B6B5DBDDC50E926_1675828285970791263) is relevant

**Comment by roryabraham** [comment] 2022-05-15 22:49
Found a couple seemingly related issues:

- https://github.com/joltup/rn-fetch-blob/issues/694
- https://github.com/joltup/rn-fetch-blob/issues/236

**Comment by MariaHCD** [comment] 2022-05-17 10:41
Thanks, @roryabraham! From those issues, it looks this needs some more investigation:
- If adding `android:requestLegacyExternalStorage="true"` to the Android manifest would help solved this and/or;
- Whether the package `rn-fetch-blob` has released a fix for this.

**Comment by arielgreen** [comment] 2022-05-17 21:56
https://www.upwork.com/jobs/~015cbb750a025a202d

**Comment by jayeshmangwani** [comment] 2022-05-18 16:49
Proposal: 

https://github.com/Expensify/App/blob/20c11746070dc462454feb14a748db494115d7ae/src/libs/fileDownload/getAttachmentDetails.js#L21-L24


crash is happening because of these lines, anchor tag does not have ATTACHMENT_PREVIEW_ATTRIBUTE = "src", and also we are not using previewSourceURL from the getAttachmentName anywhere, so we can remove these lines,

and anchor tag has no data-name attribute, so we have to remove this line from here,
https://github.com/Expensify/App/blob/20c11746070dc462454feb14a748db494115d7ae/src/libs/fileDownload/getAttachmentDetails.js#L29

and can get filename for anchor tag as we are getting here
https://github.com/Expensify/App/blob/5096dea4e6bbeb6203df3ae8c896f282bf570e66/src/components/HTMLEngineProvider/HTMLRenderers/AnchorRenderer.js#L20

**Comment by mananjadhav** [comment] 2022-05-19 18:33
@kbecciv I've been trying to reproduce this but I am just not able to. I've attempted to download pdf, png, and mp4 files. My installed version is 1.1.62-0 and my local version is 1.1.64-0.

@jayeshmangwani Thank you for the proposal, are you able to reproduce it at your end?

**Comment by jayeshmangwani** [comment] 2022-05-19 19:37
@mananjadhav  Yes, I am able to reproduce on my side, 
I have tried with zip and mp4 files and both are crashing, latest main branch (  "version": "1.1.62-0")
please check this video for reference

https://user-images.githubusercontent.com/35371050/169388469-fcd9a1d6-eb8f-42df-9a27-6f54355b6c02.mov

**Comment by jayeshmangwani** [comment] 2022-05-19 19:42
@mananjadhav yes this issue has been handled in   "version": "1.1.64-0", it was happening in "version": "1.1.62-0" and now it's fixed

**Comment by mananjadhav** [comment] 2022-05-20 05:55
Thanks for responding @jayeshmangwani. Appreciate your help.

@arielgreen We can wait for one KI test and then close this one out.

**Comment by arielgreen** [comment] 2022-05-27 01:18
@mananjadhav are we good to close?

**Comment by mananjadhav** [comment] 2022-06-02 19:46
Yeah @arielgreen, good to close.

**Comment by mvtglobally** [comment] 2022-06-07 04:05
Issue not reproducible during KI retests. (First week)

**Closed** 2022-06-08 03:17 UTC
Labels: Exported, External, Engineering, Weekly, Help Wanted
