### ISSUE TITLE
[$500] `Switch to focus mode` modal appears every time sign out and sign in for same account

### ISSUE THREAD

**Issue by m-natarajan** [Expensify/App#37580] opened 2024-03-01 00:32 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.46-0
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** @iwiznia 
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1709229575556299

## Action Performed:

1. Have an account with many chats
2. Have your message `Priority mode` setting set to`most recent` mode
3. Sign out and sign back in
4. See the "switch to focus mode" modal is shown and you are switched to `focus` mode
5. Switch your message `Priority mode` setting to`most recent` mode
6. Sign out and sign back in

## Expected Result:
The account's message `Priority mode` should not be switched to `#focus` mode, nor should the `#focus` mode modal  appear since the account should not be in `#focus` mode.

## Actual Result:
The switch to focus mode modal is shown and you are switched to focus mode 

## Workaround:
unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

https://github.com/Expensify/App/assets/38435837/c33a9f67-06bd-415b-a56a-f9155dafb64b

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01f91501e19c2b41b5</li>
        <li>Upwork Job ID: 1765136631800881152</li>
        <li>Last Price Increase: 2024-03-05</li>
<li>Automatic offers: </li>
<ul>
<li>ishpaul777 | Reviewer | 0</li>
<li>bernhardoj | Contributor | 0</li>
</ul></li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @johncschuster</details>

**Comment by CortneyOfstad** [comment] 2024-03-01 12:51
Hi @johncschuster! This issue was assigned to me after I went OoO last night, so reassigning. Thanks!

**Comment by bernhardoj** [comment] 2024-03-02 09:27
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
Switch to focus mode modal appears and the priority mode is switched to focus every time a user signs out and signs in back.

### What is the root cause of that problem?
In `tryFocusModeUpdate`, we check for `hasTriedFocusMode` value. If it's true, we won't switch it to focus mode. However, after sign-in, `hasTriedFocusMode` is null. We already guard the function to wait until all required data is available,
https://github.com/Expensify/App/blob/af68510ad375bc99679908ce26dafead3a8b3dc1/src/libs/actions/PriorityMode.ts#L111-L112

but we only check whether `hasTriedFocusMode` is undefined or not.
https://github.com/Expensify/App/blob/af68510ad375bc99679908ce26dafead3a8b3dc1/src/libs/actions/PriorityMode.ts#L103-L109

The `hasTriedFocusMode` value could be null because it's cleared when we sign out. That's why the type is either boolean, undefined, or null.

### What changes do you think we should make in order to solve the problem?

In `checkRequiredData`, return early if `hasTriedFocusMode` is undefined or null.

Or even better, we can just check if `hasTriedFocusMode` is not a boolean.

**Comment by johncschuster** [comment] 2024-03-05 21:51
This seems like an internal issue to me

**Comment by johncschuster** [comment] 2024-03-05 22:05
I've clarified the repro steps and am adding the `External` label.

**Comment by johncschuster** [comment] 2024-03-11 14:45
@ishpaul777 just to clarify, are you suggesting above that I assign this one to @bernhardoj?

**Comment by bernhardoj** [comment] 2024-03-12 07:43
PR is ready

cc: @ishpaul777

**Comment by techievivek** [comment] 2024-04-08 04:46
Closing this as per this comment https://github.com/Expensify/App/pull/38115#discussion_r1555214785 since the issue is no longer reproducible.

**Comment by bernhardoj** [comment] 2024-04-08 06:26
@techievivek @johncschuster Are we at least eligible for partial payment since we've done some work on the PR?

_I think I ever seen some cases where the contributor is due to partial payment when they did their work on the PR but get closed because the issue is not reproducible anymore, but I could be wrong, so asking to be sure_

**Comment by techievivek** [comment] 2024-04-09 03:32
Sorry, I do think we need to compensate here. I will reopen the issue so John can look into payment. Thanks.

**Comment by techievivek** [comment] 2024-04-19 07:37
Going to DM John to take a look into the payments here.

**Comment by johncschuster** [comment] 2024-05-09 21:07
Sorry for the delay! I've issued payment through Upwork.

**Closed by johncschuster** 2024-05-09 21:07 UTC
Labels: Reviewing, External, Daily, Bug
