### ISSUE TITLE
[$500] Some reports are not loading and get in a loop of calling OpenReport

### ISSUE THREAD

**Issue by m-natarajan** [Expensify/App#35620] opened 2024-02-02 01:55 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.35-0
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** @cead22 
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1706816577968589

## Action Performed:
1. Open some of the reports (one of the reproducing step is on an account where the other user was no longer a member of the workspace)

## Expected Result:
Open the chat without any issues 

## Actual Result:
Loading screen appears and get in a loop of calling OpenReport
Few of the affected ReportIDs : 66604416, 65279538 and 66589491

## Workaround:
unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

https://github.com/Expensify/App/assets/38435837/21b296b4-23d1-44a6-ac54-8ad84d823231

![image](https://github.com/Expensify/App/assets/38435837/1e70e3bb-2879-4152-9e9e-a89254ed62dc)

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01b0c48a8c47035913</li>
        <li>Upwork Job ID: 1753235697020526592</li>
        <li>Last Price Increase: 2024-02-02</li>
    </ul>
</details>

**Comment by cead22** [comment] 2024-02-02 20:27
I've been looking into this today but still haven't figured out the root cause

**Comment by cead22** [comment] 2024-02-06 02:36
- Looking into the code, and `onEndReached={loadOlderChats}` got me thinking that this is why having a message after all the deleted ones makes the report load. But I couldn't prove that
- Deleting the onyx key `reportActions_65630295` didn't fix the issue. Signing out and back in didn't fix the issue either

**Comment by cead22** [comment] 2024-02-14 03:43
@iwiznia did you happen to look into this?

I have no updates on this one yet

**Comment by puneetlath** [comment] 2024-02-19 17:23
@cead22 is this most likely a back-end issue?

**Comment by cead22** [comment] 2024-02-20 00:58
This was triggered by a back end change (https://github.com/Expensify/Insiders/issues/8824), but the client should be able to handle that update. I haven't figured this one out yet

**Comment by puneetlath** [comment] 2024-02-21 15:55
Asked Callstack for help here: https://expensify.slack.com/archives/C03UK30EA1Z/p1708465703703169

**Comment by cead22** [comment] 2024-02-23 18:35
CS said they'd take this next week

**Comment by cead22** [comment] 2024-02-27 23:56
I bumped them again. I'll find someone else for this tomorrow if I don't hear back

**Comment by puneetlath** [comment] 2024-03-01 21:16
Asked again here: https://expensify.slack.com/archives/C03UK30EA1Z/p1708465703703169

**Comment by cead22** [comment] 2024-03-02 01:29
Thanks, if I finish the PR I'm currently working on before somebody picks this up, I'll grab it and prioritize it

**Comment by kbieganowski** [comment] 2024-03-04 11:38
Hi, I'm Kamil from Callstack - expert contributor group. I’d like to work on this issue

**Comment by kbieganowski** [comment] 2024-03-04 13:31
Hey @cead22, I've tried to reproduce this issue but unfortunately with no luck, removing user from the workspace and opening it from the link didn't cause mentioned issue either. Can you please provide us repro steps and recording (if possible)?

**Comment by cead22** [comment] 2024-03-04 21:33
This is a tricky one to reproduce, but the way we triggered this was by updating our database to delete some messages in some DM chats using the following query
```sql
update reportactions set message = json_set(json_set(message, '$.edits[#]', message->>'$.html'), '$.html', '') where reportID = {0} and action = 'ADDCOMMENT' and message->>'$.html' is not null and message->>'$.html' != ''
```

When opening a DM chat that got messages deleted, we get in a loop of making api requests to `GetOlderActions`

**Comment by kbieganowski** [comment] 2024-03-05 09:05
Could you please elaborate more on how I can run this query? Otherwise, I'm not able to reproduce this issue

**Comment by cead22** [comment] 2024-03-05 17:10
@kbieganowski I messaged you yesterday in new dot from my carlos@expensifail.com account (https://staging.new.expensify.com/r/328657243571140). I'm going to add a lot of messages to that chat, and then I'll run that query for the chat and see if we can get you to reproduce

**Comment by cead22** [comment] 2024-03-05 17:43
@puneetlath buddy check please
```
update reportactions set message = json_set(json_set(message, '$.edits[#]', message->>'$.html'), '$.html', '') where reportID = 328657243571140 and action = 'ADDCOMMENT' and message->>'$.html' is not null and message->>'$.html' != ''
```

**Comment by puneetlath** [comment] 2024-03-05 17:51
Looks good 👍🏾

**Comment by cead22** [comment] 2024-03-05 18:13
Done, verification below
```
carlos@db2.sjc:~$ sudo readdb.sh "select count() from reportactions where reportid = 328657243571140 and action = 'ADDCOMMENT' and message->>'$.html' is  not null and message->>'$.html' = ''"
count()
-------
2214
carlos@db2.sjc:~$ sudo readdb.sh "select count() from reportactions where reportid = 328657243571140 and action = 'ADDCOMMENT' and message->>'$.html' is  not null and message->>'$.html' != ''"
count()
-------
0
```

**Comment by cead22** [comment] 2024-03-05 18:14
@kbieganowski I'm able to reproduce by switching to the DM report between carlos@expensifail.com and kamil.bieganowski@callstack.com.

Let me know if you can reproduce as well

**Comment by kbieganowski** [comment] 2024-03-06 08:41
Hi @cead22, unfortunately I wasn't able to reproduce this issue in staging as well. I've also tried switching between multiple reports at fast rate and going back to mentioned one but without any luck

https://github.com/Expensify/App/assets/26638539/dcb6cfbb-4370-49b0-8f97-3fc375e8f5de

**Comment by cead22** [comment] 2024-03-06 20:43
@kbieganowski can you try signing out and back in? Those messages you're seeing should all be deleted. Also feel free to ping me on slack or new expensify if that's quicker

**Comment by cead22** [comment] 2024-03-06 20:44
I'm currently seeing GetOlderActions being called over and over when I switch to that chat

**Comment by cead22** [comment] 2024-03-06 20:45
Ha, I just posted a question in there 👍

**Comment by cead22** [comment] 2024-03-06 20:47
It looks like the same issue that is happening here for deleted messages happens in chats with whispers, and we're going to push a change to solve the issues for whispers. I'll test again to see if I can reproduce once the fix is out to see if it fixes this issue as well

**Comment by roryabraham** [comment] 2024-03-06 20:47
seems plausible that this might be fixed by https://github.com/Expensify/App/pull/37839

**Comment by cead22** [comment] 2024-03-06 21:57
It looks like we fixed the case where we call GetOlderActions over and over, which is the case I was able to reproduce with the chat between carlos@expensifail.com and kamil.bieganowski@callstack.com.

That said, I'm still seeing this issue with reports that trigger OpenReport over and over, but I need to figure out steps to reproduce

**Comment by cead22** [comment] 2024-03-20 17:38
This was fixed while fixing a fire. I tried reproducing with all the reports that I was able to reproduce with before and didn't manage, so closing

**Closed by cead22** 2024-03-20 17:38 UTC
Labels: Engineering, Weekly, Internal, Bug

**Comment by puneetlath** [comment] 2024-03-20 18:19
Nice!
