### ISSUE TITLE
Unauthorized Message Deletion: The person that's owed money can delete messages of the other iouReport participant.

### ISSUE THREAD

**Issue by kavimuru** [Expensify/App#21038] opened 2023-06-19 14:20 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
~1. Go to web chrome and login with User A
2. Create a group with User B and User C
3. Click on add and split money in the group
This will generate individual message to Recepients User B and C
4. Go to User B and click on the message or go to the chat and click on the split money message
5. Write some messages as User B
6. Go to User A and try to delete the messages.~

TRJ Edit: 

1. send a request from userA to userB, such that userA is owed money 
2. As userB write a couple of messages on the iouReport directly 
3. As userA hover over the message(s) and click the trashcan icon

## Expected Result: 
userA should NOT be able to delete UserB's messages on an iouReport

## Actual Result: 
UserA is able to delete UserB's messages

## Workaround:
Can the user still use Expensify without this being fixed? Have you informed them of the workaround?

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android / native
- [x] Android / Chrome
- [x] iOS / native
- [x] iOS / Safari
- [x] MacOS / Chrome / Safari
- [x] MacOS / Desktop

**Version Number:** 1.3.29-0
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation

Comment [here](https://github.com/Expensify/App/issues/21038#issuecomment-1597719006) on why I think this is happening. We need to exclude iouReports from the new "admin delete" logic.

https://github.com/Expensify/App/assets/43996225/81c1a1f2-15c0-4b7b-9193-7ff0a75c6bb8

https://github.com/Expensify/App/assets/43996225/2afa589a-f80f-4abb-bf85-c0d405f5c7bf

**Expensify/Expensify Issue URL:**
**Issue reported by:** @avi-shek-jha
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1686343933703009

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~017c8b2f6ee327ce37</li>
        <li>Upwork Job ID: 1670890147893735424</li>
        <li>Last Price Increase: 2023-06-19</li>
    </ul>
</details>

**Comment by Pujan92** [comment] 2023-06-19 14:45
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
User A Has Ability to Remove User B's Messages in ‘Thread' of Split Money Chat 

### What is the root cause of that problem?
For the `canDeleteReportAction` we are allowing the admin role to delete the messages of other participants. As per the slack discussion only for Rooms we need this functionality.
https://github.com/Expensify/App/blob/057a18292aba57a50f791f735793f64d1aba3824/src/libs/ReportUtils.js#L261`

### What changes do you think we should make in order to solve the problem?
We need to add one more condition here which will also check for reportType is a `policyRoom` or not. If it is `policyRoom` then only consider the role admin condition else it will return false.
https://github.com/Expensify/App/blob/057a18292aba57a50f791f735793f64d1aba3824/src/libs/ReportUtils.js#L261

**Comment by trjExpensify** [comment] 2023-06-19 15:02
@neil-marcellini you might have some context here from [this PR](https://github.com/Expensify/App/pull/18735). Looks like something might have slipped through the net which is allowing a member with the `admin` role to delete other people's comments on an iouReport/in the request thread.

**Comment by neil-marcellini** [comment] 2023-06-19 16:13
I thought that was the expected behavior. An admin of the report can delete a member's comment. We can certainly change it but we should update the backend if we do as well.

**Comment by trjExpensify** [comment] 2023-06-19 17:31
An iouReport isn't attached to a policy, it's shared between say you and me. Why would you be able to delete my messages because you happen to be an `admin` on an (unrelated) policy?

**Comment by Pujan92** [comment] 2023-06-19 17:43
My doubt is why for iouReport we get the attached policyId from the backend onyx response whereas for normal chat report it is `policyID: "_FAKE_" `

**Comment by trjExpensify** [comment] 2023-06-19 17:52
I think that's to do with how we dynamically change the direction of who's currently owed and what currency the reportTotal will be based on the personal policy currency of the person that is owed.

**Comment by trjExpensify** [comment] 2023-06-19 20:23
I'll take this from you Sasha. I've been [following it up internally](https://expensify.slack.com/archives/C04QEB4MJEQ/p1687197365604749) and looking into it. I can reproduce this, and confirmed its not the intention of the design. Basically what's happening is that: 

1. when you're owed money, you technically "own" the iouReport because we use the person that's owed policyID to determine things like the report output currency 
2. As such, the person who's owed is also technically the policy admin of the policy the iouReport is attached to 
3. Meaning that [because of this](https://github.com/Expensify/Auth/blob/8388418126b466428ee98fef89311527e63c9531/auth/lib/Report.cpp#L531) new logic to allow admins the right to delete messages, the person that's owed can delete other people's messages. 

As I understand it, it'll require a backend change, so I'm going to mark this as `internal` to fix. I think the solution is to exclude iouReports from this logic entirely.

**Comment by joelbettner** [comment] 2023-06-21 18:54
@neil-marcellini I'm confused on how this is happening from the back end perspective.

```c++
    // The account must own the comment to edit, unless the edit is deleting the comment and the account is an admin of the report's policy
    string accountClause = "AND accountID = " + SQ(accountID) + " ";
    if (isDeleteUpdate) {
        const int64_t reportID = Report::getReportIDFromReportActionID(db, reportActionID);
        const string requesterPolicyID = Report::getPolicyID(db, reportID);
        if (Policy::verifyAdmin(db, accountID, requesterPolicyID)) {
            accountClause.clear();
        }
    }
```

The comment is only deletable if the report is on a policy that the user is an admin of. If a userA is sending an IOUReport for payment from userB, wouldn't that only be on userA's personal policy? Why would/how could userA ever put an IOUReport on a policy for which userB is an admin??

**Comment by joelbettner** [comment] 2023-06-21 20:06
I created that^ PR for the backend change, but I'm still unclear how it is even possible that a user could have admin permissions on an IOU report that they didn't create.

**Comment by trjExpensify** [comment] 2023-06-22 00:52
Not sure I'm following yah! This is what's happening:

1. userA sends a request to userB for $100, such that userB owes. 
2. the iouReport gets created and has: `policyID:<user-A-personal-policy>` such that userA is deemed the `admin`
3. userB writes a comment on the iouReport
4. userA, as the admin of the iouReport can delete userB's comment
5. userB, as the non-admin of the iouReport cannot delete userA's comment

>The comment is only deletable if the report is on a policy that the user is an admin of. 

So this is true. 

>If a userA is sending an IOUReport for payment from userB, wouldn't that only be on userA's personal policy?

Yep!

>Why would/how could userA ever put an IOUReport on a policy for which userB is an admin??

By the polarity of the iouReport changing, such that userA owes userB. Carrying the above example through.. 

6. userB now sends a request to userA for $150, such that userA owes $50 
7. userB is now the owner of the iouReport, and as such deemed the admin
8. userB can now delete userA's comments, as the admin.
9. userA can't delete userB's comments anymore, as the non-admin.

**Comment by joelbettner** [comment] 2023-06-22 15:36
Thanks @trjExpensify I was misunderstanding the situation. Makes sense. The PR I pushed should be the back end changes that we need to take care of this.

**Comment by trjExpensify** [comment] 2023-06-22 15:37
Dope, thanks!

**Comment by joelbettner** [comment] 2023-06-23 22:06
There was a lengthy Slack conversation about this [here](https://expensify.slack.com/archives/C04QEB4MJEQ/p1687553996818969?thread_ts=1687197365.604749&cid=C04QEB4MJEQ).

It sounds like we are going to be deprecating IOU Reports, so we don't need to put front end effort into fixing this. In the meantime, the Auth PR I linked to this issue has been merged, so non-comment owners won't be able to delete comments on an IOU report before they get deprecated.

**Closed by joelbettner** 2023-06-23 22:06 UTC
Labels: Reviewing, Engineering, Daily, Internal, Bug
