### ISSUE TITLE
[HOLD for payment 2023-09-21] Web - Inconsistency bug: Home equivalent of spanish first letter is not capital on 'Hmm its not here page'

### ISSUE THREAD

**Issue by izarutskaya** [Expensify/App#24627] opened 2023-08-16 13:50 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Open the app
2. Open settings->workspaces->any workspace->settings
3. Remove last 's' from URL to trigger 'Hmm its not here page', eg link: 
4. https://staging.new.expensify.com/workspace/148AB979666D2030/setting
5. Observe that when language is english, it display 'Home' in 'Go back to Home page' with capital H
6. Change language to spanish and follow same steps, observe that spanish equivalent of 'Home' does not have capital H

## Expected Result:
App should either display 'Home' in 'Go back to Home page' link in english with small 'h' or should display its equivalent in spanish in capital

## Actual Result:
App displays 'Home' in 'Go back to Home page' link in english with capital 'H' and displays its equivalent in spanish in small letters

## Workaround:
unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [x] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** v1.3.54-11

**Reproducible in staging?:** Y

**Reproducible in production?:** Y

**If this was caught during regression testing, add the test name, ID and link from TestRail:**

**Email or phone of affected tester (no customers):**

**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/115492554/67c0eddf-1c94-4309-8f1f-921b70f33d3c

https://github.com/Expensify/App/assets/115492554/9760aff0-26f4-4d45-bcff-e5e8d77b5aa3

**Expensify/Expensify Issue URL:**

**Issue reported by:** @Dhanashree-Sawant

**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1691301214398869

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01949489296e056716</li>
        <li>Upwork Job ID: 1694377206281830400</li>
        <li>Last Price Increase: 2023-08-23</li>
    </ul>
</details>

**Comment by ahmedGaber93** [comment] 2023-08-16 13:50
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
Inconsistency bug: Home equivalent of spanish first letter is not capital on Hmm its not here page
### What is the root cause of that problem?
the translated value of `goBackHome` for word "Home" is capital for english and small for spanish.
### What changes do you think we should make in order to solve the problem?
we need to change the translated value of `goBackHome` in spanish to be
```javascript
// goBackHome: 'Volver a la página principal',
goBackHome: 'Volver a la Página principal',
```

### What alternative solutions did you explore? (Optional)
we need to change the translated value of `goBackHome` in english to be
```javascript
// goBackHome: 'Go back to Home page',
goBackHome: 'Go back to home page',
```

**Comment by laurenreidexpensify** [comment] 2023-08-23 15:49
I will do this next week

**Comment by laurenreidexpensify** [comment] 2023-08-29 16:28
I haven't had a chance to do this yet, will work on this on Friday

**Comment by laurenreidexpensify** [comment] 2023-09-12 16:17
Merged 🎉

**Comment by laurenreidexpensify** [comment] 2023-09-20 14:22
No payments - i wrote the PR and @Julesssss reviewed it for me.

**Comment by dhanashree-sawant** [comment] 2023-09-21 05:16
Hi @laurenreidexpensify, reporting bonus is left for this job

**Comment by dhanashree-sawant** [comment] 2023-09-25 07:56
Thanks @mallenexpensify, I have accepted the offer.

**Closed** 2023-10-02 13:30 UTC
Labels: Weekly, Internal, Awaiting Payment, Bug
