### ISSUE TITLE
Search - Unable to exit selection mode via app back button while the expense is selected

### ISSUE THREAD

**Issue by izarutskaya** [Expensify/App#46650] opened 2024-08-01 10:53 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 9.0.15-4
**Reproducible in staging?:** Y
**Reproducible in production?:** N
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Issue reported by:** Applause-Internal team

## Action Performed:
1. Launch New Expensify app.
2. Go to any chat.
3. Submit an expense.
4. Go to Search.
5. Long press on the expense.
6. Tap Select.
7. Tap on the back button while the expense is selected.

## Expected Result:
Selection mode will exit.

## Actual Result:
App is unable to exit the selection mode when tapping on back button while the expense is selected.

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [x] Android: mWeb Chrome
- [x] iOS: Native
- [x] iOS: mWeb Safari
- [ ] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

https://github.com/user-attachments/assets/2671b9c5-87f2-49f7-8263-886aafebef84

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by izarutskaya** [comment] 2024-08-01 10:53
We think this issue might be related to the #collect project.

**Comment by Kicu** [comment] 2024-08-01 10:56
@filip-solecki do you mind taking a look here?

**Comment by pecanoro** [comment] 2024-08-01 10:57
I was able to reproduce it, it takes a little bit for me to go back to the selection page but yeah, it keeps getting back without being able to cancel it.

**Comment by pecanoro** [comment] 2024-08-01 11:02
Yeah, I also think it's coming from here: https://github.com/Expensify/App/pull/46096

**Comment by filip-solecki** [comment] 2024-08-01 11:12
Hi! I can take a look tomorrow, maybe it will be good to open it for external if anyone consider it as a deploy blocker

**Comment by pecanoro** [comment] 2024-08-01 11:15
I will open it for proposals then since we probably want this fixed asap

**Comment by ikevin127** [comment] 2024-08-01 16:19
Hey, this is the issue I was talking about in https://github.com/Expensify/App/pull/46096#issuecomment-2259796014, found it right after PR was merged.

This issue was fixed in PR https://github.com/Expensify/App/pull/46406 which was merged 18h ago but not yet deployed to staging.

Once that deploys, the issue will be fixed. Until that happens we should put this in hold.

Also we agreed that this should not be counted as a regression as it was part of another polishing / cleanup issue https://github.com/Expensify/App/issues/44916.

cc @pecanoro @filip-solecki @luacmartins

**Comment by luacmartins** [comment] 2024-08-01 17:56
We should probably CP https://github.com/Expensify/App/pull/46406 if it fixes this blocker

**Comment by roryabraham** [comment] 2024-08-01 19:18
already done: https://expensify.slack.com/archives/C07J32337/p1722533185644439

and deployed in [9.0.15-6](https://github.com/Expensify/App/tree/9.0.15-6)

we just need to retest this on staging

**Comment by roryabraham** [comment] 2024-08-01 20:34
confirmed this was fixed by https://github.com/Expensify/App/pull/46406

**Closed by roryabraham** 2024-08-01 20:34 UTC
Labels: Engineering, Hourly, Bug
