### ISSUE TITLE
After sending messages they show in correct order then get updated seconds later and reshow.

### ISSUE THREAD

**Issue by kavimuru** [Expensify/App#14576] opened 2023-01-25 23:45 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Open NewDot 
2. Go to any report
3. Send numbers 1-7 one at a time

## Expected Result:
For numbers to show in order and stay in order (ie. not update or move around)

## Actual Result:
Numbers show in order then they each reappear at the bottom until the chats and order are restored

## Workaround:
unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?

- [ ] MacOS / Desktop

**Version Number:** 1.2.59-1
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** 

https://user-images.githubusercontent.com/43996225/214718864-c2218e22-bb70-4979-b7c0-25f91efc88ff.mp4

https://user-images.githubusercontent.com/43996225/214718980-681c7891-03ac-4315-93f7-137134baac12.mp4

**Expensify/Expensify Issue URL:**
**Issue reported by:** @mallenexpensify 
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1674662537140229

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by marcaaron** [comment] 2023-01-26 23:36
This was discussed before recently. I don't have the exact context. Pretty sure it's gotta be internal and maybe will be handled by the deprecate sequence numbers stuff. tagging @roryabraham in case he remembers the thread.

**Comment by roryabraham** [comment] 2023-01-31 23:01
Closing as duplicate of https://github.com/Expensify/App/issues/13250

**Closed by roryabraham** 2023-01-31 23:01 UTC
Labels: Daily, Overdue, Bug
