### ISSUE TITLE
[$500] Web - Chat - Composer with emoji is expanded with an empty line after expanding the composer

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#39361] opened 2024-04-01 14:19 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.58-4
**Reproducible in staging?:** Y
**Reproducible in production?:** N
**If this was caught during regression testing, add the test name, ID and link from TestRail:** N/A
**Issue reported by:** Applause - Internal Team

## Action Performed:
1. Go to staging.new.expensify.com
2. Go to any chat
3. Enter an emoji with a multi-line message
4. Expand the composer

## Expected Result:
No new line should be added at the end of the message

## Actual Result:
A new empty line is added at the end of the message

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

https://github.com/Expensify/App/assets/6829422/433fe70f-8310-42e1-b420-a6298391a10c

</details> 

https://github.com/Expensify/App/assets/78819774/7a3add2e-1cc2-476e-a78f-d2bd61ed5785

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~016de42cbd35e27ee2</li>
        <li>Upwork Job ID: 1775310993834332160</li>
        <li>Last Price Increase: 2024-04-16</li>
    </ul>
</details>

**Comment by lanitochka17** [comment] 2024-04-01 14:20
@marcochavezf  FYI I haven't added the External label as I wasn't 100% sure about this issue. Please take a look and add the label if you agree it's a bug and can be handled by external contributors

**Comment by lanitochka17** [comment] 2024-04-01 14:20
We think that this bug might be related to #vip-vsp

**Comment by shahinyan11** [comment] 2024-04-01 20:22
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
Web - Chat - Composer with emoji is expanded with an empty line after returning from Settings
### What is the root cause of that problem?
[Here](https://github.com/Expensify/App/blob/f3d18feeea9620a2fe76d95de473aa8e9cdbc0b8/src/components/Composer/index.tsx#L251C39-L251C145) we calculate number of lines . When we add emoji in comment the calculation works incorrect and returns `1` line more
### What changes do you think we should make in order to solve the problem?
Add below code on [this](https://github.com/Expensify/App/blob/f3d18feeea9620a2fe76d95de473aa8e9cdbc0b8/src/components/Composer/index.tsx#L253) line
```
if(extractEmojis(value ?? '').length > 0 && generalNumberOfLines > 1){
    generalNumberOfLines--
}
```
### What alternative solutions did you explore? (Optional)

**Comment by marcochavezf** [comment] 2024-04-01 20:52
I found out this is introduced by https://github.com/Expensify/App/pull/38955, reverting the offending PR [here](https://github.com/Expensify/App/pull/39377)

**Comment by marcochavezf** [comment] 2024-04-01 21:02
Sure, we can wait

**Comment by marcaaron** [comment] 2024-04-01 21:47
@ishpaul777 @marcochavezf can you give an ETA on when this will be ready?

**Comment by marcochavezf** [comment] 2024-04-02 01:25
Original [PR](https://github.com/Expensify/App/pull/39377) reverted, requested CP [here](https://expensify.slack.com/archives/C07J32337/p1712020353262049)

**Comment by marcaaron** [comment] 2024-04-02 03:15
Asking for re-test

**Comment by marcochavezf** [comment] 2024-04-02 03:40
Tested on staging and looks good

https://github.com/Expensify/App/assets/6829422/87aad32f-d738-4fa0-ada4-0eb4ccdbb228

So we can close it out

**Comment by marcochavezf** [comment] 2024-04-02 17:52
Re-opening per discussion and updating the title and reproduction steps

**Comment by marcochavezf** [comment] 2024-04-02 17:58
@allroundexperts could you review as C+ @shahinyan11's [proposal](https://github.com/Expensify/App/issues/39361#issuecomment-2030494465) when you have a chance?

**Comment by allroundexperts** [comment] 2024-04-03 23:37
> @allroundexperts could you review as C+ @shahinyan11's [proposal](https://github.com/Expensify/App/issues/39361#issuecomment-2030494465) when you have a chance?

I don't think its the correct RCA. Can someone please explain WHY adding `return String(route.params?.reportID || 0);` in `function getReportID(route: ReportScreenNavigationProps['route']): string {` fixes the issue?

**Comment by shahinyan11** [comment] 2024-04-04 07:23
> Can someone please explain WHY adding `return String(route.params?.reportID || 0);` in `function getReportID(route: ReportScreenNavigationProps['route']): string {` fixes the issue?

@allroundexperts It will not fix the current issue . The steps to reproduce was updated in issue  and adding `return String(route.params?.reportID || 0);` would fix the old one

**Comment by bfitzexpensify** [comment] 2024-04-09 19:59
@allroundexperts thoughts on https://github.com/Expensify/App/issues/39361#issuecomment-2036382880?

**Comment by shahinyan11** [comment] 2024-04-10 09:22
@allroundexperts Don't you agree that the line calculation is not working correctly due to the size of the emoji?

**Comment by marcochavezf** [comment] 2024-04-15 19:07
> Can someone please explain WHY adding return String(route.params?.reportID || 0); in function getReportID(route: ReportScreenNavigationProps['route']): string { fixes the issue?

Yeah I agree this a weird workaround, but yeah I think that was a solution for the previous problem

> Don't you agree that the line calculation is not working correctly due to the size of the emoji?

One question that comes to my mind is, why do we have a different size for emojis and text?

**Comment by shahinyan11** [comment] 2024-04-15 19:39
> One question that comes to my mind is, why do we have a different size for emojis and text?

This is also a question for me. But it is a fact that line calculation does not work correctly when adding emoji

**Comment by marcochavezf** [comment] 2024-04-16 19:01
> And [here](https://github.com/Expensify/App/blob/a7820d2027138a1a9670b204f608d6b92ec0a454/src/components/Composer/index.tsx#L269C16-L269C34) we have a case where currentNumberOfLines can be set to undefined if isComposerFullSize is true

Oh interesting, I don't know why it's undefined, seems the `numberOfLines` is a flawed design because I think the value can be relative to the size of the composer or the screen

**Comment by allroundexperts** [comment] 2024-04-18 13:29
@shahinyan11 Sorry, I'm not sure what you're expecting from me here. I think I should be reviewing the proposals rather than correcting the already made proposals. That'd be unfair to other contributors.

**Comment by mvtglobally** [comment] 2024-04-18 16:05
Issue not reproducible during KI retests. (First week)

**Comment by shahinyan11** [comment] 2024-04-18 18:16
It's just a shame how my efforts on this issue were appreciated

**Comment by allroundexperts** [comment] 2024-04-18 18:54
@shahinyan11 I see that the solution you proposed in-fact got applied by Software mansion. I think you should get a partial compensation here. @marcochavezf Would you agree?

**Comment by marcochavezf** [comment] 2024-04-18 22:43
> @allroundexperts for your information the change I suggested was implemented [here](https://github.com/Expensify/App/pull/39597/files)  what led to the problem being solved. 

Oh thanks for pointing it out @shahinyan11, and yeah I agree that in this case we should make a partial payment. @bfitzexpensify could you handle that?

**Comment by bfitzexpensify** [comment] 2024-04-19 13:13
Agreed, I think a $250 payment is correct here. @shahinyan11 can you please apply to [this Upwork job](https://www.upwork.com/jobs/~016de42cbd35e27ee2)?

**Comment by bfitzexpensify** [comment] 2024-04-19 15:03
Payment complete, closing this out.

**Closed by bfitzexpensify** 2024-04-19 15:03 UTC
Labels: External, Daily, Help Wanted, Bug
