### ISSUE TITLE
[HOLD for payment 2023-06-21] [$1000] Mweb - Workspace - the "Next" button overlaps the input field for specific phone modal (Huawei P10 lite)

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#19740] opened 2023-05-29 13:15 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Open the "Settings" menu.
2. Click on "Workspaces."
3. Open any Workspace.
4. Select "Manage Members."
5. Select "Invite."
6. Select "Invite New Members."
7. Tap on the input field.
8. Notice that the "Next" button overlaps the input field.

## Expected Result:
The "Next" button should not overlap the input field.

## Actual Result:
On small screen devices, the "Next" button overlaps the input field.

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [ ] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 1.3.19.2

**Reproducible in staging?:** yes

**Reproducible in production?:** yes

**If this was caught during regression testing, add the test name, ID and link from TestRail:**

**Email or phone of affected tester (no customers):**

**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/93399543/63fa8f2f-8497-471a-86b3-3a2c2d664406

**Expensify/Expensify Issue URL:**

**Issue reported by:** @usmantariq96

**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1684994471559049

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01a873f4cf420dcd10</li>
        <li>Upwork Job ID: 1663674368458465280</li>
        <li>Last Price Increase: 2023-06-06</li>
    </ul>
</details>

**Comment by mallenexpensify** [comment] 2023-05-30 22:31
Was able to reproduce using the one Huawei phone available in Browserstack. 
<img width="424" alt="image" src="https://github.com/Expensify/App/assets/22508304/a5b19b3b-624d-451f-ae25-b1c87293e9a0">

**Comment by mallenexpensify** [comment] 2023-05-30 22:32
@mollfpr , can you review @Ollyws proposal above please?
https://github.com/Expensify/App/issues/19740#issuecomment-1567302766

**Comment by mollfpr** [comment] 2023-06-01 16:26
Reviewing now!

**Comment by mollfpr** [comment] 2023-06-01 16:55
@Ollyws Could you attach a video result of your proposal? Thanks!

**Comment by flodnv** [comment] 2023-06-05 16:02
@mollfpr what are your thoughts?

**Comment by mollfpr** [comment] 2023-06-05 16:10
The result looks good, but I want to try the proposal on my local. @Ollyws Could you attach the code diff?

**Comment by mollfpr** [comment] 2023-06-06 16:41
Thanks @Ollyws for the diff code, it solves the issue. Now I am confident to bring forward the proposal.

@flodnv the [proposal](https://github.com/Expensify/App/issues/19740#issuecomment-1567302766) looks good to me!

🎀 👀 🎀 C+ reviewed!

**Comment by flodnv** [comment] 2023-06-06 21:30
Thanks! Go for it @Ollyws 👍

**Comment by mallenexpensify** [comment] 2023-06-09 17:42
@Ollyws @mollfpr hired for the job, @usmantariq96 hired for reporting.  Please accept
https://www.upwork.com/jobs/~01a873f4cf420dcd10

**Comment by usmantariq96** [comment] 2023-06-09 17:47
@mallenexpensify applied with thanks

**Comment by mallenexpensify** [comment] 2023-06-15 21:42
@Ollyws , can you please accept the job and reply here once you have?  (there's two offers cuz I didn't see there was a pending one when I invited ya again)
https://www.upwork.com/jobs/~01a873f4cf420dcd10

**Comment by mollfpr** [comment] 2023-06-21 17:04
> [@mollfpr] The PR that introduced the bug has been identified. Link to the PR:
 [@mollfpr] The offending PR has been commented on, pointing out the bug it caused and why, so the author and reviewers can learn from the mistake. Link to comment:

No offending PR is causing this bug and this is very edge-case.

> [@mollfpr] A discussion in #expensify-bugs has been started about whether any other steps should be taken (e.g. updating the PR review checklist) in order to catch this type of bug sooner. Link to discussion:

I don't think any checklist will cover this bug since it's related to specific devices.

>  [@mollfpr] Determine if we should create a regression test for this bug.

Yes!

>[@mollfpr] If we decide to create a [regression test](https://github.com/Expensify/App/blob/main/contributingGuides/REGRESSION_TEST_BEST_PRACTICES.md) for the bug, please propose the regression test steps to ensure the same bug will not reach production again.

1. Open Settings > Workspaces > Manage members > Invite > Invite New Members
2. Select the text input to open the keyboard
3. Verify that the 'Next' button does not overlap the text input
4. 👍 or 👎

**Comment by flodnv** [comment] 2023-06-21 21:49
IDK, this feels very specific.... What I'm saying is that if we already have a test that does 
1. Open Settings > Workspaces > Manage members > Invite > Invite New Members
2. Select the text input to open the keyboard
Then it's already covered. Let's ask QA @mollfpr @mallenexpensify ?

**Comment by mallenexpensify** [comment] 2023-06-22 19:21
Going to treat this one as an edge case. I'll add this to our issue [list](https://docs.google.com/spreadsheets/d/1VTQKn9t9xNMbrhD46OIf3fJGmpH4Gmi42jXjQgmtBoY/edit#gid=0) that will be tested on a monthly basis.

For more context on edge cases, please check this [thread](https://expensify.slack.com/archives/C9YU7BX5M/p1682431765823119).
Closing the issue - please reopen if needed."

Everyone is paid, no bonus - Hire/assign date was the 6th, PR merged on the 12th.

**Closed by mallenexpensify** 2023-06-22 19:21 UTC
Labels: External, Daily, Awaiting Payment, Bug
