### ISSUE TITLE
[$500] Profile - Infinite loading on Private section when changes made offline & back online

### ISSUE THREAD

**Issue by izarutskaya** [Expensify/App#36678] opened 2024-02-16 12:03 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** v1.4.42-1
**Reproducible in staging?:** Y
**Reproducible in production?:** N
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** Applause-Internal Team
**Slack conversation:**

## Action Performed:
1. Launch New Expensify app on Android device
2. Go to Account settings >> Profile
3. Disable the internet connection in the device
4. Modify first name, last name in Private section
5. Save and Verify everything looks like it updated correctly
6. Enable internet connection & wait for few seconds

## Expected Result:
Private section should load with changes modified during offline & when internet connection is enabled

## Actual Result:
Infinite loading on Private section when changes made offline & enable internet connection

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [ ] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

https://github.com/Expensify/App/assets/115492554/a6989ad9-781c-4c42-938c-0d23f288d656

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01cabd5b5c25a34b36</li>
        <li>Upwork Job ID: 1758462336438116352</li>
        <li>Last Price Increase: 2024-02-16</li>
    </ul>
</details>

**Comment by brandonhenry** [comment] 2024-02-17 22:58
Is this accepting proposals?

**Comment by kavimuru** [comment] 2024-02-19 23:12
@fedirjh We are not able to reproduce now.

Uploading Notrepro.mp4…

**Comment by chiragsalian** [comment] 2024-02-19 23:19
Awesome, closing out this issue since its not reproducible right now.

**Closed by chiragsalian** 2024-02-19 23:19 UTC
Labels: DeployBlockerCash, External, Engineering, Hourly, Help Wanted, Bug
