### ISSUE TITLE
[$1000] Web -  Incorrect Display of Wrapped Words in Quotation Marks in Previous Description Notifications in IOU

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#26006] opened 2023-08-26 19:41 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Click on the plus sign and select "Request Money."
2. Enter the desired amount and email address for the money request.
3. Go to the IOU section and write a description, wrapping it with quotation marks (e.g., "Hello").
4. Edit the description again and observe that in the previous notification, only the words are displayed without quotation marks.

## Expected Result:
The previous description notification should not remove any characters, including the quotation marks

## Actual Result:
When wrapping a statement with quotation marks, the words are displayed correctly in the Changed notification section, but the quotation marks are not shown in the previous description notification.

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [x] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 1.3.57.5
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation

[screen-capture - 2023-08-26T115237.252.webm](https://github.com/Expensify/App/assets/93399543/9a09f46b-74ac-4303-8c25-d8b4b0661866)

**Expensify/Expensify Issue URL:**
**Issue reported by:** @tewodrosGirmaA
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1692255619787139

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01d8244bf1b5b5b204</li>
        <li>Upwork Job ID: 1696227622973382656</li>
        <li>Last Price Increase: 2023-08-28</li>
    </ul>
</details>

**Comment by sakluger** [comment] 2023-08-28 18:26
The similar issue that I linked (https://github.com/Expensify/App/issues/10404) was a BE issue. @ntdiary do you think this one will also be internal?

**Comment by saadaoui-salah** [comment] 2023-08-28 23:02
@sakluger i need to run the project locally but when trying to where the issue is located it tooks me to the staging live server can you help me ??

**Comment by saadaoui-salah** [comment] 2023-08-31 09:58
@ntdiary  you can replace ' " ' with '&quot;'

**Comment by saadaoui-salah** [comment] 2023-08-31 09:59
Contributor details
Your Expensify account email: salahsaadaoui8@gmail.com
Upwork Profile Link: https://www.upwork.com/freelancers/~01e3cd4014cc8dd97d

**Comment by sakluger** [comment] 2023-09-01 22:52
Thanks, reassinging to internal!

**Comment by sakluger** [comment] 2023-09-05 18:32
Assigning a different engineer since Yuwen is going on extended leave soon.

**Comment by sakluger** [comment] 2023-09-14 17:30
Bumped @chiragsalian in Slack.

**Comment by chiragsalian** [comment] 2023-09-14 19:34
Sorry for the delay, yes this is internal and yes we should be able to fix this on the backend. My plate is a bit full and this doesn't feel like an immediate priority so I'll demote it to weekly. Feel free to bump it back to daily if you feel there is a good reason this should be tackled with more urgency.

**Comment by sakluger** [comment] 2023-09-14 20:37
I think weekly priority makes sense given the competing priorities right now.

**Comment by sakluger** [comment] 2023-09-18 07:55
It's okay Melvin, we are on it.

**Comment by sakluger** [comment] 2023-09-27 08:31
Switching back to weekly.

**Comment by chiragsalian** [comment] 2023-10-11 17:08
i haven't had the chance to look at this yet. I'm wondering if we should ask if anyone has some free cycles to look into this one.

**Comment by chiragsalian** [comment] 2023-10-25 19:27
Posted on slack if anyone else has free cycles to tackle this. If not i can maybe revisit next week.

**Comment by sakluger** [comment] 2023-11-03 23:45
I'm OOO all next week so I need to assign another BZ member.

**Comment by chiragsalian** [comment] 2023-11-07 22:28
Doesn't feel like a daily so i'm going to demote to weekly. If anyone feels that this should be prioritized to daily let me know.

**Comment by chiragsalian** [comment] 2023-11-22 00:57
Demoting to monthly, since we're focusing only on wave's, VIPs and chores.
If anyone disagree and feels like we should tackle sooner let me know.

**Comment by anmurali** [comment] 2024-01-02 23:41
Yea, this doesn't seem like a mainline bug. Let's close it for now.

**Closed by anmurali** 2024-01-02 23:41 UTC
Labels: Engineering, Monthly, Internal, Overdue, Bug
