### ISSUE TITLE
[$1000] LHN - Task persist it's position in LHS even after assignee is changed

### ISSUE THREAD

**Issue by izarutskaya** [Expensify/App#26088] opened 2023-08-28 14:27 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Assign a task to account A from B
2. Observe task is on the top & report with latest message is below in account A
3. Change the assignee from account B
4. Send any message in any report
5. Observe task is still on the top (with no green dot indicator)
6. Open task, observe now it's on the right index

## Expected Result:
The task should not persist it's position if the assignee is changed.

## Actual Result:
The task persists it's position if the assignee is changed.

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [x] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** v1.3.57-5

**Reproducible in staging?:** Y

**Reproducible in production?:** Y

**If this was caught during regression testing, add the test name, ID and link from TestRail:**

**Email or phone of affected tester (no customers):**

**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/115492554/7dae5312-39ab-4c20-bdb1-d389bef19590

https://github.com/Expensify/App/assets/115492554/baf0b95e-da7b-476d-a950-5cd42798ea5d

**Expensify/Expensify Issue URL:**

**Issue reported by:** @krishna2323

**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1692512938649409

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01f53f26cbea1ae4ec</li>
        <li>Upwork Job ID: 1699150958423752704</li>
        <li>Last Price Increase: 2023-09-19</li>
    </ul>
</details>

**Comment by mollfpr** [comment] 2023-09-11 16:53
I'm not sure what's the actual issue here. I believe it's expected that when the report has a green dot has a higher position in the LHN.

**Comment by mollfpr** [comment] 2023-09-14 14:20
I see the issue now.

**Comment by mollfpr** [comment] 2023-09-18 10:17
No proposals.

**Comment by johncschuster** [comment] 2023-09-19 21:42
Raising the bounty

**Comment by Swor71** [comment] 2023-09-21 09:02
Hey, I'm Marcin from Callstack - expert contributor group - I would like to help resolve this issue.

One question / observation to help me better understand this problem - the change of the assignee makes the green dot disappear but the task has not been viewed/read by that point so shouldn't it actually keep the green dot?

Also, although a different issue altogether, this constant swap of places when typing in a different chat also seems odd, it'd make more sense to keep the unread chats bunched up together towards the top and only move the most recent conversations underneath that group, what do you think about that?

**Comment by Swor71** [comment] 2023-09-25 09:24
@johncschuster @mollfpr
hey, would you be so kind to have a look at the questions I posted above? Thanks!

**Comment by mollfpr** [comment] 2023-09-25 16:13
Hey @Swor71 for the late response. Regarding this issue, I'm unable to reproduce it. This is probably because the sort list of the LHN is changed.

![Screenshot 2023-09-25 at 23 11 49](https://github.com/Expensify/App/assets/25520267/87449656-919f-4896-b9a7-514344a932b1)

Previously, we will priority the position of a report that has a green dot (you can observe the attached video in the description).

**Comment by Swor71** [comment] 2023-09-26 14:27
@mollfpr hey, thanks for your reply. In light of what you said, is this issue still valid? Also, what about the read/unread status when switching the assignee?

**Comment by mvtglobally** [comment] 2023-09-28 03:14
Issue not reproducible during KI retests. (First week)

**Comment by mollfpr** [comment] 2023-09-28 16:57
>In light of what you said, is this issue still valid?

I think it's not.

>Also, what about the read/unread status when switching the assignee?

IIRC this doesn't happen to me, but let me check it again.

**Comment by mollfpr** [comment] 2023-10-02 15:31
Tested on the latest `main`, the issue is not reproduced.

**Comment by johncschuster** [comment] 2023-10-05 20:49
Thanks for testing that, @mollfpr! In that case, I think we can close this issue.

**Closed** 2023-10-05 20:49 UTC
Labels: Engineering, Daily, Internal, Bug
