### ISSUE TITLE
[HOLD for payment 2024-01-24] [HOLD PR #33863][$500] Settings - Expensify icon of "Go to Expensify Classic" option doesn't turn to white when hover

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#33519] opened 2023-12-22 19:23 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.16-3
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** Applause - Inernal Team
**Slack conversation:**

## Action Performed:
1. Login to ND Expensify
2. Navigate to account settings
3. Hover over each of the options
4. Verify if Expensify icon of "Go to Expensify Classic" option turn to white when hover

## Expected Result:
Expensify icon of "Go to Expensify Classic" option should turn to white color when hover (or black color in light theme)

## Actual Result:
Expensify icon of "Go to Expensify Classic" option doesn't turn to white color when hover (or black color in light theme)

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [x] Android: mWeb Chrome
- [x] iOS: Native
- [x] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details> 

![Bug6324269_1703272807489!icon_white](https://github.com/Expensify/App/assets/78819774/f7dab9f0-23d3-483a-8305-1db83e738dc2)

https://github.com/Expensify/App/assets/78819774/67740c0c-f45b-417a-92ea-518e84c71a44

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01b5dbb083b2a8f016</li>
        <li>Upwork Job ID: 1738279174350815232</li>
        <li>Last Price Increase: 2023-12-29</li>
    </ul>
</details>

**Comment by Pujan92** [comment] 2023-12-22 19:25
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
For 'Go to expensify classic' menu item, Icon color is not changing on hover

### What is the root cause of that problem?
Currently, static color has been set for fill prop in the svg file.
https://github.com/Expensify/App/blob/main/assets/images/new-expensify.svg?short_path=38276ec#L1C161-L1C161

It is added in this [PR](https://github.com/Expensify/App/pull/32947).

### What changes do you think we should make in order to solve the problem?
We need to remove this fill attribute from the svg file and allow the IconComponent to fill dynamic value. 
Not related to fixing this issue but we can also add the same class prop `.st1{fill-rule:evenodd;clip-rule:evenodd}` which we have for other svgs file.

**Comment by paultsimura** [comment] 2023-12-22 19:30
The original issue https://github.com/Expensify/App/issues/32875 is still on the regression period, so this issue should be handled as a follow-up.
cc: @barttom @thesahindia

**Comment by NoumanHunzai** [comment] 2023-12-23 01:42
**Proposal to Resolve  SVG Icon Color Change Issue:

Proposed Solution:**
Update the SVG style rule from:
`.st1 {
    fill: #03d47c;
}`

to 

`.st1 {
    fill-rule: evenodd;
    clip-rule: evenodd;
}`

**Verification:**
A video demonstrating the successful implementation is available
https://www.loom.com/share/a807263b9c4444b58c7d0e69286dffff?sid=15696b45-109b-43e0-9040-8e6ba8a01866

**Description of Logic:**
The addition of fill-rule: evenodd; and clip-rule: evenodd; in the SVG styling simplifies and unifies the color change behavior.

fill-rule: evenodd;:
This makes sure that when coloring the shape, a point is considered inside if it crosses the boundary an odd number of times and outside if it's even.

clip-rule: evenodd;:
Similarly, when clipping the element, areas crossed an odd number of times remain visible, while those crossed an even number of times are hidden.

Why It Matters:
By using the same even-odd logic for both filling and clipping, we ensure a consistent and visually pleasing hover effect on the SVG icon.

Thank You

**Comment by NoumanHunzai** [comment] 2023-12-23 01:52
Contributor details
Your Expensify account email: noumanhunzai222@gmail.com
Upwork Profile Link: https://www.upwork.com/freelancers/~01cc5e42206c63e202

**Comment by pecanoro** [comment] 2024-01-08 09:26
@miljakljajic This should be fixed when [33863](https://github.com/Expensify/App/pull/33863) gets merged since it was coming from a different issue. Once that gets deployed, please simply check if it's reproducible and close it if it is fixed!

**Comment by miljakljajic** [comment] 2024-01-08 14:34
Thank you, will do!

**Comment by miljakljajic** [comment] 2024-01-22 12:29
Not reproducible any more - closing as per Rocio's comment above.

**Closed by miljakljajic** 2024-01-22 12:29 UTC
Labels: External, Weekly, Help Wanted, Awaiting Payment, Bug
