### ISSUE TITLE
[HOLD for payment 2022-08-11] [$500] IOS/Android - Attachment- App crashed after tap on link

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#9624] opened 2022-06-29 14:03 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Launch the app
2. Log in with expensifail account
3. Go to any conversation and tap on plus button
4. Select Add Attachment
5. Select any attachment and Send
6.. Hold with finger by the attachment until option menu is displayed
7. Select Copy Link option
8. Insert link to the conversation
9. Tap on link

## Expected Result:
App is not crashed after tap on link

## Actual Result:
App crashed after tap on link

## Workaround:
Unknown

## Platform:

Where is this issue occurring?

- Web
- iOS
- Android
- Desktop App
- Mobile Web

**Version Number:** 1.1.79.2

**Reproducible in staging?:** Yes

**Reproducible in production?:** Yes

**Email or phone of affected tester (no customers):** any expensifail account

**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Notes/Photos/Videos:** Any additional supporting documentation

https://user-images.githubusercontent.com/93399543/176456166-9cca8380-cda8-4f14-a0e9-85748b443051.MP4

![crashed](https://user-images.githubusercontent.com/93399543/176456265-b004f1c5-c7f7-47a3-8789-ca18d09af82e.jpg)

**Upwork job link:** https://www.upwork.com/jobs/~012c15c3203494d613

**Issue reported by:** Applause - Internal Team

**Slack conversation:** 

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by ctkochan22** [comment] 2022-07-05 05:28
Mistakenly added External. I can do this

**Comment by Christinadobrzyn** [comment] 2022-07-07 22:51
ooo so assigning to a teeammate!

**Comment by michaelhaxhiu** [comment] 2022-07-11 12:35
@ctkochan22 quick question - is this internal or external? Seems the label has been added/removed a few times.

**Comment by ctkochan22** [comment] 2022-07-11 15:26
Its external. I accidentally put the label on once because I wanted to fix it. But with n7 I don't have time so I need to pass it off. MY bad

**Comment by michaelhaxhiu** [comment] 2022-07-11 15:33
Ah makes perfect sense. No problem at all, this is precisely the reason we have `external` assignment and outsourcing :) 

I'll get it moving.

**Comment by michaelhaxhiu** [comment] 2022-07-11 15:35
Job link - https://www.upwork.com/jobs/~012c15c3203494d613

**Comment by woodenlabs** [comment] 2022-07-11 17:07
Applied for job link

**Comment by mananjadhav** [comment] 2022-07-11 17:47
> Applied for job link

@woodenlabs Got me a bit confused here. If you're planning to add a proposal, please refer to this [contribution guidelines](https://github.com/Expensify/App/blob/main/contributingGuides/CONTRIBUTING.md) and specifically [proposing solution](https://github.com/Expensify/App/blob/main/contributingGuides/CONTRIBUTING.md#propose-a-solution-for-the-job)

**Comment by errahsoufiane** [comment] 2022-07-11 20:38
This crash happens when try to open deep link with reportActionID
Current deep link implementation handles `r/:reportID` (chatroom deep link) which goes to report screen but not handling `r/:reportID/:reportActionID` (message deep link in chat room)
It's a new feature to implement scrolling to specific message (when click message deep link).
So for now, I suggest redirecting to room deep link when click message deep link as a temporary solution, until that new feature implemented.
i.e.
https://staging.new.expensify.com/r/97208274/1065573786 can be redirected to
https://staging.new.expensify.com/r/97208274

I will create PR as soon as my suggestion approved.

I applied for job on upwork

**Comment by mananjadhav** [comment] 2022-07-13 18:59
I'll need a day to investigate the issue and review @errahsoufiane's proposal.

**Comment by mananjadhav** [comment] 2022-07-15 22:45
I agree with @errahsoufiane's evaluation. But I am not sure if we should redirect to the chat instead of the attachment.

@NikkiWines @michaelhaxhiu What do we think of the expected behavior here?  I would have been great to load the exact chat, but I am not sure how it'll work with pagination.

**Comment by NikkiWines** [comment] 2022-07-19 03:18
Sorry, I'm OOO this week. Assigning another contributor manager to take this over while I'm out

**Comment by mananjadhav** [comment] 2022-07-20 20:59
> I agree with @errahsoufiane's evaluation. But I am not sure if we should redirect to the chat instead of the attachment.
> 
> @NikkiWines @michaelhaxhiu What do we think of the expected behavior here? I would have been great to load the exact chat, but I am not sure how it'll work with pagination.

@Gonals @michaelhaxhiu  Can someone please confirm this?

**Comment by michaelhaxhiu** [comment] 2022-07-21 19:54
Sorry for the delay, looking now.

**Comment by michaelhaxhiu** [comment] 2022-07-21 20:20
Hmm @mananjadhav I'm a little conflicted. I do think re-directing to the chat would be ideal. But would that be significantly harder to accomplish or do you feel it's a breach of scope? 

This could be a good opportunity to post it in #expensify-open-source for more input, too.

**Comment by mananjadhav** [comment] 2022-07-22 04:18
Thanks @michaelhaxhiu. Started the slack thread [here](https://expensify.slack.com/archives/C01GTK53T8Q/p1658463458826979)

**Comment by mananjadhav** [comment] 2022-07-22 20:55
@michaelhaxhiu @Gonals Based on the chat [here](https://expensify.slack.com/archives/C01GTK53T8Q/p1658504425975639?thread_ts=1658463458.826979&cid=C01GTK53T8Q), our solution for the time being would be to hide the `Copy Link` behind the betas. The Key for the beta is `BETA_COMMENT_LINKING`. Can we please have the GH body updated for the expected fix.

@errahsoufiane If you're keen on working on this, can you please send in a revised proposal to get this expected behavior.

**Comment by errahsoufiane** [comment] 2022-07-22 21:52
### Updated Proposal:
`    {
        textTranslateKey: 'reportActionContextMenu.copyLink',
        icon: Expensicons.LinkCopy,
        shouldShow: () => Permissions.canUseCommentLinking,
        onPress: (closePopover, {reportAction, reportID}) => {
            Environment.getEnvironmentURL()
                .then((environmentURL) => {
                    const reportActionID = parseInt(lodashGet(reportAction, 'reportActionID'), 10);
                    Clipboard.setString(`${environmentURL}/r/${reportID}/${reportActionID}`);
                });
            hideContextMenu(true, ReportActionComposeFocusManager.focus);
        },
        getDescription: () => {},
    },`

Here, we can update `shouldShow` like this: `shouldShow: () => Permissions.canUseCommentLinking,`

**Comment by mananjadhav** [comment] 2022-07-24 21:12
@errahsoufiane I don't see a function `canUseCommentLinking`, can you expand your proposal to share the implementation for the same?

**Comment by errahsoufiane** [comment] 2022-07-25 03:05
> @errahsoufiane I don't see a function `canUseCommentLinking`, can you expand your proposal to share the implementation for the same?

@mananjadhav updated

**Comment by mananjadhav** [comment] 2022-07-25 03:49
@errahsoufiane's proposal is good. @Gonals all yours

@chiragsalian Tagging you just in case we get the betas key incorrect.

🎀 👀 🎀 
C+ reviewed

**Comment by Gonals** [comment] 2022-07-25 10:07
The proposal looks good! @errahsoufiane, feel free to go ahead and create a PR following the steps detailed above!

**Comment by michaelhaxhiu** [comment] 2022-07-25 15:45
@errahsoufiane just accepted you on the Upwork job. We'll stay tuned for your updates on this GH while you go 🤓

**Comment by michaelhaxhiu** [comment] 2022-08-04 14:25
Update on behalf of @errahsoufiane. It seems this is in progress, but the PR hasn't merged successfully to staging. 

https://github.com/Expensify/App/pull/10071#issuecomment-1201803371

**Comment by michaelhaxhiu** [comment] 2022-08-12 12:41
paid.

**Closed by michaelhaxhiu** 2022-08-12 12:41 UTC
Labels: Exported, External, Engineering, Weekly, Improvement, Awaiting Payment
