### ISSUE TITLE
[HOLD for payment 2024-12-12] Hybrid - Android - Settings- General section on settings disappears when navigating back from profile

### ISSUE THREAD

**Issue by IuliiaHerets** [Expensify/App#53380] opened 2024-12-02 12:14 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 9.0.69-1
**Reproducible in staging?:** Y
**Reproducible in production?:** N
**If this was caught on HybridApp, is this reproducible on New Expensify Standalone?:** N
**Email or phone of affected tester (no customers):** ibellicotest+61@gmail.com
**Issue reported by:** Applause Internal Team

## Action Performed:
1. Open the Expensify app.
2. Tap on "Settings" on the bottom of the screen.
3. Tap on "Profile"
4. Tap on the search icon on the top right corner and select any chat from search results.
5. Tap on compose box to open the keyboard.
6. Tap on the arrow on the top left corner.
7. When landing on "Profile" again, tap fast on the arrow on the top left corner again.
8. Verify you land on "Settings" tab and all the sections are correctly displayed.

## Expected Result:
When navigating back to settings from profile, all the tab should be completely visible and no section should disappear.

## Actual Result:
When navigating back fast to "Settings" from profile, after opening a chat from search results, the "General" section disappears.

## Workaround:
Unknown

## Platforms:

- [ ] Android: Standalone
- [x] Android: HybridApp
- [ ] Android: mWeb Chrome
- [ ] iOS: Standalone
- [ ] iOS: HybridApp
- [ ] iOS: mWeb Safari
- [ ] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

https://github.com/user-attachments/assets/e802b74e-4c79-407e-9ee5-4a0a3c86e40d

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Issue Owner</summary>Current Issue Owner: @slafortune</details>

**Comment by war-in** [comment] 2024-12-02 13:49
Hi 👋 I tried to go through steps on the newest main branches and can't reproduce the issue


https://github.com/user-attachments/assets/5891dc41-ee0f-4474-b82f-5d2dc94c3dbf

**Comment by isagoico** [comment] 2024-12-02 14:36
Our testers reported that this issue is not consistently reproducible. It's reproduced 1 out of 5 times. 3 Testers were able to reproduce the issue. Here's a video of another attempt: 

https://github.com/user-attachments/assets/abad604e-d2f1-423d-8ca8-bf81a10dc5d4

**Comment by mountiny** [comment] 2024-12-02 15:02
Thanks! I am adding it to the quality project and marking as critical, but given this does not block the user and its not reliably reproducible i dont think it has to be a blocker.

@kirillzyusko any ideas why the keyboard might be causing this? Probably long shot as you dont have access to hybrid

**Comment by war-in** [comment] 2024-12-02 16:11
I found out that if we set 

```
shouldEnableKeyboardAvoidingView={false}
```

in `ScreenWrapper` props the issue is gone. 
Based on that, the bug is somewhere there: https://github.com/Expensify/App/blob/cb0613c083baa987c63a5bdd724a729c5a1795b8/src/components/KeyboardAvoidingView/index.android.tsx

**Comment by kirillzyusko** [comment] 2024-12-02 16:19
@war-in @mountiny Interesting - looks like `KeyboardAvoidingView` can not be resized properly 🤔 But very curious why it happens only in Hybrid app?..

**Comment by war-in** [comment] 2024-12-02 16:28
After some `KeyboardAvoidingView` investigation I can tell that the issue comes from the wrong `bottom` value which is computed [here](https://github.com/Expensify/App/blob/cb0613c083baa987c63a5bdd724a729c5a1795b8/src/components/KeyboardAvoidingView/index.android.tsx#L96)

I think the problem is with the progress value of the keyboard const
```
keyboard.progress.get()
```

It returns 1 but I guess it should return 0 when there is no keyboard 🤔

**Comment by kirillzyusko** [comment] 2024-12-02 17:15
> What do you think? Any ideas on what could be the root cause of it?

@war-in First of all I would log values from `onStart`/`onMove`/`onEnd` handlers to understand which handler is broken. Once we understnad that we can go to the native code to see how it's getting calculated so that we can fix it.

But you are right - even when the problem gets fixed on a single page, there is no guarantee that the same problem will not re-appear on other pages. And you are also right - if keyboard is closed then `progress` should be `0` 🙂 

Feel free to drop me any messages in Slack - I'm responding much faster there 👀

**Comment by slafortune** [comment] 2024-12-05 20:46
# BugZero Checklist:

- [ ] **[Contributor]** Classify the bug:

<details>
<summary>Bug classification</summary>


Source of bug:
  - [ ] 1a. Result of the original design (eg. a case wasn't considered)
  - [ ] 1b. Mistake during implementation
  - [ ] 1c. Backend bug
  - [ ] 1z. Other:

Where bug was reported:
  - [ ] 2a. Reported on production (eg. bug slipped through the normal regression and PR testing process on staging)
  - [ ] 2b. Reported on staging (eg. found during regression or PR testing)
  - [ ] 2d. Reported on a PR
  - [ ] 2z. Other:

Who reported the bug:
  - [ ] 3a. Expensify user
  - [ ] 3b. Expensify employee
  - [ ] 3c. Contributor
  - [ ] 3d. QA
  - [ ] 3z. Other:

</details>

- [ ] **[Contributor]** The offending PR has been commented on, pointing out the bug it caused and why, so the author and reviewers can learn from the mistake.

    Link to comment:

- [ ] **[Contributor]** If the regression was CRITICAL (e.g. interrupts a core flow) A discussion in [#expensify-open-source](https://app.slack.com/client/E047TPA624F/C01GTK53T8Q) has been started about whether any other steps should be taken (e.g. updating the PR review checklist) in order to catch this type of bug sooner.

    Link to discussion:

- [ ] **[Contributor]** If it was decided to create a regression test for the bug, please propose the [regression test](https://github.com/Expensify/App/blob/main/contributingGuides/REGRESSION_TEST_BEST_PRACTICES.md) steps using the template below to ensure the same bug will not reach production again.

<details>
<summary>Regression Test Proposal Template</summary>


- [ ] **[BugZero Assignee]** Create a GH issue for creating/updating the regression test once above steps have been agreed upon.

    Link to issue:

## Regression Test Proposal
### Precondition:


-

### Test:


1.

Do we agree 👍 or 👎


</details>

**Comment by slafortune** [comment] 2024-12-05 20:46
Closing - https://github.com/Expensify/App/issues/53380#issuecomment-2517163504

**Closed by slafortune** 2024-12-05 20:46 UTC
Labels: Engineering, Weekly, Awaiting Payment, Bug
