### ISSUE TITLE
[HOLD for payment 2023-07-20] [$1000]  [Attachment] shows in LHN even after close error message

### ISSUE THREAD

**Issue by kavimuru** [Expensify/App#19913] opened 2023-05-31 22:38 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Go to any chat
2. send any corrupted file
3. click on X button in Unexpected error message
## Expected Result: 
should not show [Attachment] in LHN
## Actual Result: 
in LHN still shows [Attachment] even after close error message
## Workaround:
Can the user still use Expensify without this being fixed? Have you informed them of the workaround?

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [x] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 1.3.21-2
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/43996225/732f1e8b-cea5-4c3a-beb4-6c97a21e09fc

https://github.com/Expensify/App/assets/43996225/93ac50d9-0efe-42ee-9816-f900e42fc29c

**Expensify/Expensify Issue URL:**
**Issue reported by:** @gadhiyamanan 
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1685341334486499

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01da8eae4fb504ea71</li>
        <li>Upwork Job ID: 1664682621010223104</li>
        <li>Last Price Increase: 2023-06-23</li>
    </ul>
</details>

**Comment by therealsujitk** [comment] 2023-05-31 22:39
```## Proposal

### Please re-state the problem that we are trying to solve in this issue.

The last message in the LHN doesn't get updated when a report action is removed by the user due to an error.

### What is the root cause of that problem?

The reason for this is that we are not updating the report's `lastMessageText` while deleting the report action in Onyx in the function below.

https://github.com/Expensify/App/blob/06192acc94f8fa31f95adb76f57bd9f4145bdf11/src/libs/actions/ReportActions.js#L6-L31

### What changes do you think we should make in order to solve the problem?
<!-- DO NOT POST CODE DIFFS -->

To resolve this issue, we simply update the `lastMessageText` in this function just like we do while deleting a report action. This is what the function would look like,

```js
/**
 * @param {String} reportID
 * @param {Object} reportAction
 */
function clearReportActionErrors(reportID, reportAction) {
    if (reportAction.pendingAction === CONST.RED_BRICK_ROAD_PENDING_ACTION.ADD) {
        // Delete the optimistic action
        const optimisticReportAction = {
            [reportAction.reportActionID]: null,
        };
        // Update the report's last message
        const optimisticReport = {
            lastMessageText: '',
            lastVisibleActionCreated: '',
        };

        const lastMessageText = ReportActionsUtils.getLastVisibleMessageText(reportID, optimisticReportAction);
        if (lastMessageText.length > 0) {
            const lastVisibleActionCreated = ReportActionsUtils.getLastVisibleAction(reportID, optimisticReportAction).created;
            optimisticReport.lastMessageText = lastMessageText;
            optimisticReport.lastVisibleActionCreated = lastVisibleActionCreated;
        }

        Onyx.merge(`${ONYXKEYS.COLLECTION.REPORT}${reportID}`, optimisticReport);
        Onyx.merge(`${ONYXKEYS.COLLECTION.REPORT_ACTIONS}${reportID}`, optimisticReportAction);

        // If there's a linked transaction, delete that too
        const linkedTransactionID = ReportActionsUtils.getLinkedTransactionID(reportID, reportAction.reportActionID);
        if (linkedTransactionID) {
            Onyx.set(`${ONYXKEYS.COLLECTION.TRANSACTION}${linkedTransactionID}`, null);
        }

        return;
    }

    Onyx.merge(`${ONYXKEYS.COLLECTION.REPORT_ACTIONS}${reportID}`, {
        [reportAction.reportActionID]: {
            errors: null,
        },
    });
}
```

> **Note:** We could optimise this by creating a function in **ReportActionsUtils.js** to format the last message, this way we will only have to call `getLastVisibleAction` instead of `getLastVisibleMessageText` as well.

### What alternative solutions did you explore? (Optional)
None.

```

**Comment by therealsujitk** [comment] 2023-05-31 22:39
## Proposal

### Please re-state the problem that we are trying to solve in this issue.

The last message in the LHN doesn't get updated when a report action is removed by the user due to an error.

### What is the root cause of that problem?

The reason for this is that we are not updating the report's `lastMessageText` while deleting the report action in Onyx in the function below.

https://github.com/Expensify/App/blob/06192acc94f8fa31f95adb76f57bd9f4145bdf11/src/libs/actions/ReportActions.js#L6-L31

### What changes do you think we should make in order to solve the problem?


To resolve this issue, we simply update the `lastMessageText` in this function just like we do while deleting a report action. This is what the function would look like,

```js
/**
 * @param {String} reportID
 * @param {Object} reportAction
 */
function clearReportActionErrors(reportID, reportAction) {
    if (reportAction.pendingAction === CONST.RED_BRICK_ROAD_PENDING_ACTION.ADD) {
        // Delete the optimistic action
        const optimisticReportAction = {
            [reportAction.reportActionID]: null,
        };
        // Update the report's last message
        const optimisticReport = {
            lastMessageText: '',
            lastVisibleActionCreated: '',
        };

        const lastMessageText = ReportActionsUtils.getLastVisibleMessageText(reportID, optimisticReportAction);
        if (lastMessageText.length > 0) {
            const lastVisibleActionCreated = ReportActionsUtils.getLastVisibleAction(reportID, optimisticReportAction).created;
            optimisticReport.lastMessageText = lastMessageText;
            optimisticReport.lastVisibleActionCreated = lastVisibleActionCreated;
        }

        Onyx.merge(`${ONYXKEYS.COLLECTION.REPORT}${reportID}`, optimisticReport);
        Onyx.merge(`${ONYXKEYS.COLLECTION.REPORT_ACTIONS}${reportID}`, optimisticReportAction);

        // If there's a linked transaction, delete that too
        const linkedTransactionID = ReportActionsUtils.getLinkedTransactionID(reportID, reportAction.reportActionID);
        if (linkedTransactionID) {
            Onyx.set(`${ONYXKEYS.COLLECTION.TRANSACTION}${linkedTransactionID}`, null);
        }

        return;
    }

    Onyx.merge(`${ONYXKEYS.COLLECTION.REPORT_ACTIONS}${reportID}`, {
        [reportAction.reportActionID]: {
            errors: null,
        },
    });
}
```

> **Note:** We could optimise this by creating a function in **ReportActionsUtils.js** to format the last message, this way we will only have to call `getLastVisibleAction` instead of `getLastVisibleMessageText` as well.

### What alternative solutions did you explore? (Optional)
None.

**Comment by isabelastisser** [comment] 2023-06-02 17:02
I tried to reproduce it with multiple corrupt files and couldn't reproduce it. @kavimuru @mananjadhav, can you please attach the corrupt file you used to this issue? I would like to try it before dismissing the `bug`. Thanks!

**Comment by therealsujitk** [comment] 2023-06-02 17:06
@isabelastisser you can find it in the slack discussion.

**Comment by isabelastisser** [comment] 2023-06-02 17:17
Thanks and yep, I can reproduce it!

**Comment by bernhardoj** [comment] 2023-06-03 07:40
We have a same issue [here](https://github.com/Expensify/App/issues/18546) with just a different set of reproduction step that gets closed because they can't reproduce it anymore, but I can. I have posted a [proposal](https://github.com/Expensify/App/issues/18546#issuecomment-1538296520) there which basically the same as @therealsujitk above. Is there any possibility my proposal take precedence over the others? 😄

_coincidentally the C+ is the same_

**Comment by therealsujitk** [comment] 2023-06-03 12:11
I think #18546 isn't exactly the same as this one because they have different expected behaviors as stated [here](https://github.com/Expensify/App/issues/18546#issuecomment-1552311456) so the solution would've been different if it were still reproducible.

**Comment by isabelastisser** [comment] 2023-06-05 16:25
Not overdue!

**Comment by rojiphil** [comment] 2023-06-05 16:38
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
[Attachment] is shown in LHN even when the uploading of attachment has failed. In case of failure, the LHN should have shown the last successful message.

### What is the root cause of that problem?
The root cause of the problem is that we are not updating the message with the last successful one if there is failure in adding a new attachment to the report. If this is taken care of, the LHN will show the last successful message. 

### What changes do you think we should make in order to solve the problem?

We can fix this by updating the `lastMessageText` in `Onyx` as follows for the failure case [here in Report.js](https://github.com/Expensify/App/blob/main/src/libs/actions/Report.js#LL266C5-L266C5). Now, when the LHN row picks up the `lastMessageText`, it will get the message of the last successful one.
```
    const prevVisibleMessageText = ReportActionsUtils.getLastVisibleMessageText(reportID);
    const failureReport = {
        lastMessageText: prevVisibleMessageText,
        lastReadTime: currentTime,
    };
    const failureData = [
        {
            onyxMethod: Onyx.METHOD.MERGE,
            key: `${ONYXKEYS.COLLECTION.REPORT}${reportID}`,
            value: failureReport,
        },
```

### What alternative solutions did you explore? (Optional)

**Comment by rojiphil** [comment] 2023-06-06 17:19
@isabelastisser I have also updated the proposal with a test video for the fix. Kindly review.

**Comment by isabelastisser** [comment] 2023-06-07 20:09
Summary:

We are still receiving and reviewing proposals!

I'm reassigning ([SO](https://stackoverflowteams.com/c/expensify/questions/8836)) because I will be OOO until June 14. Thanks!

`Once I return from OOO if the chore is still outstanding, I will take over any remaining action items`

**Comment by rojiphil** [comment] 2023-06-13 05:26
I had posted a [proposal here](https://github.com/Expensify/App/issues/19913#issuecomment-1577124594). Would be great if someone can review this. Thanks.

**Comment by tylerkaraszewski** [comment] 2023-06-14 22:16
@rushatgabhane, can you evaluate @rojiphil's proposal?

**Comment by isabelastisser** [comment] 2023-06-15 17:42
@rushatgabhane can you please follow up on the comment above? Thanks!

**Comment by rojiphil** [comment] 2023-06-19 16:37
@alexpensify   I don't think the issues are similar or the changes required are similar. This issue occurs when the upload of an attachment fails. Whereas, the other issue deals with a case post-successful attachment.

**Comment by rojiphil** [comment] 2023-06-19 16:39
I sent a [proposal ](https://github.com/Expensify/App/issues/19913#issuecomment-1577124594) about 2 weeks ago and is still not been reviewed. Just wanted to gently remind of this again.  Thanks

**Comment by isabelastisser** [comment] 2023-06-20 14:38
Hey @rushatgabhane, can you please review the proposals so we can move this issue forward? Do we need to wait for new proposals? Please follow up; thanks!

**Comment by therealsujitk** [comment] 2023-06-21 02:53
@rushatgabhane would just like to note that there are a few more proposals above.

**Comment by rojiphil** [comment] 2023-06-21 04:14
> @rojiphil thanks for your proposal. Where exactly are you suggesting to add failure data? Could you please attach a permalink to the code?
> 
> Because we still want the error to be show when backend returns an error when adding a comment

@rushatgabhane 

Please have a look at the [changes in file here](https://github.com/Expensify/App/compare/main...rojiphil:App:19913-attachmentinlhn)

The suggestion is to add `failureReport` to `failureData` so that if there is failure in `API.write` operation, it will use the previous visible message text.
The changes are in `addActions` function so that this would work for both  `addAttachment` and `addComment`

**Comment by isabelastisser** [comment] 2023-06-23 19:46
I will be OOO until July 5, so assigning another team member. [SO](https://stackoverflowteams.com/c/expensify/questions/883) for reference.

**Comment by rojiphil** [comment] 2023-06-26 04:51
> @rojiphil thanks for your proposal. Where exactly are you suggesting to add failure data? Could you please attach a permalink to the code?
> 
> Because we still want the error to be show when backend returns an error when adding a comment

@rushatgabhane I have [updated the proposal](https://github.com/Expensify/App/issues/19913#issuecomment-1577124594) with the permalink. Also, the suggested changes will also work for comments. Kindly review.

**Comment by lschurr** [comment] 2023-06-26 15:21
@rushatgabhane could you review?

**Comment by bernhardoj** [comment] 2023-06-27 04:02
Copying my proposal from [here](https://github.com/Expensify/App/issues/18546#issuecomment-1538296520)

## Proposal

### Please re-state the problem that we are trying to solve in this issue.
LHN last message text does not update when we clear the error when adding a message/comment.

### What is the root cause of that problem?
When we clear the error of new message, it will also clear the report action.

https://github.com/Expensify/App/blob/ab9171f953603bb8e4e061f5582a4b7cab3d4a43/src/libs/actions/ReportActions.js#L11-L24

However, the last message of the report does not get the update.

### What changes do you think we should make in order to solve the problem?

We should update the last message and other data taken from the previous action. We did this when we delete a message.
https://github.com/Expensify/App/blob/5f5dd023a8102ef47ac4b58e4bfe79b995cb0330/src/libs/actions/Report.js#L854-L867

So, we can take the logic and use it when clearing the error with some additional changes.
1. When we optimistically add a message, we update these 4 data:
https://github.com/Expensify/App/blob/ab9171f953603bb8e4e061f5582a4b7cab3d4a43/src/libs/actions/Report.js#L220-L225

I think it make sense to update the lastActorEmail too when clearing the error.

So, we should get the whole action instead of `created` here to also be able to get the `actorEmail` to update the `lastActorEmail`.
https://github.com/Expensify/App/blob/ab9171f953603bb8e4e061f5582a4b7cab3d4a43/src/libs/actions/Report.js#L756

2. The optimisticReportActions will be taken from
https://github.com/Expensify/App/blob/ab9171f953603bb8e4e061f5582a4b7cab3d4a43/src/libs/actions/ReportActions.js#L13-L15

I also think maybe we can create a new function called `Report.buildOptimisticReportLastAction`. However, as you can see in delete comment, we are not updating the `lastActorEmail`. I don't know if it's intended or not. (Update: Just check that the lastActorEmail is updated through Pusher. I think we should optimistically update it too)

**Comment by lschurr** [comment] 2023-06-28 20:26
@rushatgabhane - could you review the most recent proposal?

**Comment by tylerkaraszewski** [comment] 2023-06-30 16:49
@lschurr  - I am leaving today on sabbatical. Can you please remove and re-apply the `Engineering` label to select a new engineer to finish this issue? Thanks!

**Comment by rojiphil** [comment] 2023-07-01 03:37
@rushatgabhane  As I understand, under error conditions, we are using the last successful visible message. I think, the backend also works this way. Please have a look at the following video and notice how the last visible message changes to the most recent successful one for our failed attachment upload case. I don't think, the proposal you are approving resolves this as it addresses the issue only after the close of the comment. Or am I missing something here?

https://github.com/Expensify/App/assets/3004659/ef225aa9-d82f-4f55-ba6a-fc47b389741c

**Comment by techievivek** [comment] 2023-07-03 08:23
Not overdue, waiting for @rushatgabhane's input on the [above](https://github.com/Expensify/App/issues/19913#issuecomment-1615425131) case.

**Comment by lschurr** [comment] 2023-07-03 15:22
Bump @rushatgabhane

**Comment by techievivek** [comment] 2023-07-05 18:40
@rushatgabhane It looks like we would want to go with @rojiphil's proposal here, right?

**Comment by isabelastisser** [comment] 2023-07-06 01:50
I'm back, thanks @lschurr!

Assigning @rojiphil.

**Comment by isabelastisser** [comment] 2023-07-06 01:53
@rushatgabhane hm, I think you need to assign @rojiphil to this issue.

**Comment by techievivek** [comment] 2023-07-06 02:14
@rojiphil I have assigned you to the Job, You may start working on the PR now.

**Comment by rojiphil** [comment] 2023-07-06 05:23
Thanks @techievivek for the assignment. Am working on the PR.

**Comment by rojiphil** [comment] 2023-07-06 12:26
@rushatgabhane [PR created here](https://github.com/Expensify/App/pull/22342). Kindly review. Thanks.

**Comment by isabelastisser** [comment] 2023-07-06 15:38
Thanks @rojiphil! 

@rushatgabhane, please review the PR when you can so we can move this along. Thanks!

**Comment by isabelastisser** [comment] 2023-07-12 13:17
Bump @rushatgabhane ^

**Comment by isabelastisser** [comment] 2023-07-12 14:19
@rojiphil was assigned on July 5
[The PR ](https://github.com/Expensify/App/pull/22342)was merged on July 10.

I need clarification because we didn't generate the automated message for the payment date. 

@rushatgabhane, can you please clarify when the payment should be issued? Could you confirm that this DOES NOT qualify for the 72 hours bonus? Thanks!

**Comment by rushatgabhane** [comment] 2023-07-13 05:11
Agree with @rojiphil https://github.com/Expensify/App/issues/19913#issuecomment-1632652723

**Comment by isabelastisser** [comment] 2023-07-21 16:26
The offers were sent in Upwork, please accept, and I will process the payments.

@rushatgabhane, please complete the BZ checklist asap and I will close this issue. Thanks!

**Comment by gadhiyamanan** [comment] 2023-07-21 16:27
@isabelastisser offer accepted, thanks!

**Comment by rojiphil** [comment] 2023-07-21 17:04
> The offers were sent in Upwork, please accept, and I will process the payments.

@isabelastisser Accepted Offer. Thanks.

**Comment by isabelastisser** [comment] 2023-07-21 20:47
Payments were processed in Upwork.

C+ payment will be made via NewDot upon BZ checklist completion. cc @rushatgabhane

**Comment by rushatgabhane** [comment] 2023-07-23 14:35
WIP ⚠️ 

1. The PR that introduced the bug has been identified. Link to the PR:

2. The offending PR has been commented on, pointing out the bug it caused and why, so the author and reviewers can learn from the mistake. Link to comment:

3. A discussion in #expensify-bugs has been started about whether any other steps should be taken (e.g. updating the PR review checklist) in order to catch this type of bug sooner. Link to discussion:

4. Determine if we should create a regression test for this bug.

5. If we decide to create a [regression test](https://github.com/Expensify/App/blob/main/contributingGuides/REGRESSION_TEST_BEST_PRACTICES.md) for the bug, please propose the regression test steps to ensure the same bug will not reach production again

**Comment by rushatgabhane** [comment] 2023-07-23 14:56
made a manual request on new dot https://staging.new.expensify.com/r/1523003362514356

**Comment by isabelastisser** [comment] 2023-07-24 15:57
> [@isabelastisser] Link the GH issue for creating/updating the regression test once above steps have been agreed upon:

https://github.com/Expensify/Expensify/issues/302488

all set!

**Closed by isabelastisser** 2023-07-24 15:57 UTC
Labels: Engineering, Daily, Internal, Awaiting Payment, Bug

**Comment by JmillsExpensify** [comment] 2023-07-27 04:35
@isabelastisser Can you please summarize the appropriate individual payments for all parties involved in this issue? This is holding up @rushatgabhane's NewDot payments. More information on this compliance process [in Slack](https://expensify.slack.com/archives/C01SKUP7QR0/p1690321157273869).

**Comment by isabelastisser** [comment] 2023-07-31 19:55
Payment summary:

Issue reported by @gadhiyamanan - $250
C+ review @rushatgabhane - $1.000 for review, $500 urgency bonus 
Issue fixed by @rojiphil - $1000 for accepted proposal, $500 urgency bonus

**Comment by JmillsExpensify** [comment] 2023-07-31 20:13
Reviewed details for @rushatgabhane. These details are accurate based on summary from Business Reviewer and are now approved for payment in NewDot.
