### ISSUE TITLE
 After sending a message to an old chat when you delete the message the chat stays at the top - reported by @thesahindia

### ISSUE THREAD

**Issue by mvtglobally** [Expensify/App#9419] opened 2022-06-13 05:07 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Navigate to a chat which isn't on top
2. Send a message, now the chat will show up on top at the LHN
3. Delete the last message that you sent
4. Check that the chat is still at the top
5. Now refresh the page and see the chat will go back to its previous position in LHN

## Expected Result:
After deleting the message the chat should go back to its previous position without refreshing the page

## Actual Result:
The chat stays at top until you refresh the page

## Workaround:
unknown 

## Platform:

Where is this issue occurring?

- Web
- iOS
- Android
- Desktop App
- Mobile Web

**Version Number:** 1.1.75-0
**Reproducible in staging?:** Y 
**Reproducible in production?:** Y 
**Email or phone of affected tester (no customers):** 
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation 

https://user-images.githubusercontent.com/43995119/173283550-af594c02-5b8e-49ea-bd87-ce583fffdbf0.mov

**Expensify/Expensify Issue URL:**  
**Issue reported by:** @thesahindia
**Slack conversation:** https://expensify.slack.com/archives/C01GTK53T8Q/p1654085753868869

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by mountiny** [comment] 2022-06-14 14:42
I am not sure if this is a bug at this moment, I think that if one deletes the comment and then refreshes we do not even send any information about the deleted comments to the front-end hence it makes sense it is not shown.

I think we should close this out as not a bug but a feature and if we decide to change this in future, we would need to make some backend changes too.

**Closed by mountiny** 2022-06-14 14:42 UTC
Labels: Engineering, Daily

**Comment by thesahindia** [comment] 2022-06-14 14:54
@mountiny, the chat doesn't get back to its place just after deleting the comment but it does go back after few seconds of refreshing the page, so I think this is a front end issue

**Comment by mountiny** [comment] 2022-06-14 15:12
@thesahindia I assume that is because the message is cached and after refreshing it takes some time to fetch the new data where the comment does not exist. 

I am not sure if it is worth fixing right now. If we decide to do so later we should reopen this issue 🙌
