### ISSUE TITLE
[HOLD for payment 2024-02-14] [$500] Login - After opening public room and killing app user stuck on login page & back icon shown

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#35121] opened 2024-01-25 01:25 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.31-4
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**If this was caught during regression testing, add the test name, ID and link from TestRail:** https://expensify.testrail.io/index.php?/tests/view/4228315
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** Applause - Internal Team
**Slack conversation:**

## Action Performed:
1. Navigate to a public room via deeplink, e.g. https://staging.new.expensify.com/r/5408450846930023
2. Kill the app
3. Open the app again
4. Log in with any email address

## Expected Result:
The back icon is no longer displayed and user is able to log in

## Actual Result:
The back icon is displayed and it is not functioning. When user is trying to log in, user is stuck on the sign page with the "Incorrect magic code" message. After restarting the app, user is logged in

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [ ] Android: mWeb Chrome
- [x] iOS: Native
- [ ] iOS: mWeb Safari
- [ ] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details> 

https://github.com/Expensify/App/assets/78819774/36aeb18a-8f51-4cb0-9e3c-94a15d46a294

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01434d068cd2fd6a96</li>
        <li>Upwork Job ID: 1750328972969820160</li>
        <li>Last Price Increase: 2024-01-25</li>
<li>Automatic offers: </li>
<ul>
<li>jjcoffee | Reviewer | 28131302</li>
<li>bernhardoj | Contributor | 28131303</li>
</ul></li>
    </ul>
</details>

**Comment by bernhardoj** [comment] 2024-01-25 04:23
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
As anonymous user, closing and reopening the app will show a sign in page/modal, but the back button isn't functional.

### What is the root cause of that problem?
When we open the app, `openReportFromDeepLink` will always be called, but with a null `url`, because we didn't do any deeplink. If we open it as an anonymous user, it will check whether the URL can be accessed by the user or not.
https://github.com/Expensify/App/blob/0d0b0a8c9b073c30a9b54de15066789d17f7c718/src/libs/actions/Report.ts#L2068-L2071
https://github.com/Expensify/App/blob/0d0b0a8c9b073c30a9b54de15066789d17f7c718/src/libs/actions/Session/index.ts#L114-L115

Because it's null, `canAccessRouteByAnonymousUser` will return false and will be redirected to the sign in page. Notice that we pass `true` to the param which will replace the current screen with the sign-in screen. So, the LHN is replaced with the sign-in page making it impossible to go back.

### What changes do you think we should make in order to solve the problem?

If the `url` is null, return early.

```
if (!url) return
```

**Comment by jjcoffee** [comment] 2024-01-29 15:39
Reviewing tomorrow!

**Comment by jjcoffee** [comment] 2024-01-30 15:09
Happy to go with @bernhardoj's [proposal](https://github.com/Expensify/App/issues/35121#issuecomment-1909328909) here. It seems pretty clear that this is just a missed case from https://github.com/Expensify/App/pull/29248 (see [here](https://github.com/Expensify/App/commit/ce653159b75e12465402d199712bd2e02e9f4a37#diff-8afe5b71ee0436c21364148c86dadd640f2bff3e3d916addbb1f1f6f7e5b6a43)), where they weren't expecting to have to handle a null route.

:ribbon::eyes::ribbon: C+ reviewed

**Comment by bernhardoj** [comment] 2024-01-31 04:41
PR is ready

cc: @jjcoffee

**Comment by lschurr** [comment] 2024-02-12 18:11
Hi @jjcoffee - Could you work through the checklist for this one?

**Comment by jjcoffee** [comment] 2024-02-13 10:28
- The PR that introduced the bug has been identified. Link to the PR: https://github.com/Expensify/App/pull/29248
- The offending PR has been commented on, pointing out the bug it caused and why, so the author and reviewers can learn from the mistake. Link to comment: https://github.com/Expensify/App/commit/ce653159b75e12465402d199712bd2e02e9f4a37#r138568449
- A discussion in #expensify-bugs has been started about whether any other steps should be taken (e.g. updating the PR review checklist) in order to catch this type of bug sooner. Link to discussion: **N/A - just a missed test case**
- Determine if we should create a regression test for this bug. **Yes**
- If we decide to create a [regression test](https://github.com/Expensify/App/blob/main/contributingGuides/REGRESSION_TEST_BEST_PRACTICES.md) for the bug, please propose the regression test steps to ensure the same bug will not reach production again.

**Regression Test Proposal**

1. Log out
2. Open a public room as anonymous user (deep link)
3. Close and reopen the app or on web go directly to `staging.new.expensify.com`
4. Verify the LHN is shown with the public room visible
5. Verify the sign in button works

Do we agree 👍 or 👎

**Comment by lschurr** [comment] 2024-02-14 17:08
Payment summary:

- Contributor: @bernhardoj $500 (paid in Upwork)
- Contributor+: @jjcoffee $500 (paid in Upwork)

**Comment by lschurr** [comment] 2024-02-14 17:11
Submitted regression test request. Closing this one out :)

**Closed by lschurr** 2024-02-14 17:11 UTC
Labels: External, Daily, Awaiting Payment, Bug
