### ISSUE TITLE
[HOLD for payment 2023-09-13] [$1000] Emoji - When scrolling with the down arrows, the emoji selection disappears

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#24471] opened 2023-08-12 00:37 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Open https://staging.new.expensify.com/
2. Open any conversation
3. Open the emoji window
4. Press the down arrow to scroll downward

## Expected Result:
When scrolling with the down arrows, the emoji highlighting should remain in the user's field of view

## Actual Result:
When scrolling with the down arrows, the emoji highlighting disappears, it wilts again after clicking on the other arrows

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [x] MacOS / Chrome 
- [ ] MacOS / Desktop

**Version Number:** 1.3.53.1

**Reproducible in staging?:** Yes

**Reproducible in production?:** Yes

**If this was caught during regression testing, add the test name, ID and link from TestRail:**

**Email or phone of affected tester (no customers):**

**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/78819774/9b15e603-a528-47e9-b14b-36bba3b5878e

**Expensify/Expensify Issue URL:**

**Issue reported by:** Applause - Internal Team

**Slack conversation:**

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~018ba7fbfbb4ccc435</li>
        <li>Upwork Job ID: 1692235536154705920</li>
        <li>Last Price Increase: 2023-08-31</li>
<li>Automatic offers: </li>
<ul>
<li>DrLoopFall | Contributor | 26458681</li>
</ul></li>
    </ul>
</details>

**Comment by DrLoopFall** [comment] 2023-08-12 09:16
## Proposal

### Please re-state the problem that we are trying to solve in this issue.

When scrolling with the down arrows, the emoji selection disappears

### What is the root cause of that problem?

Currently, we're using `CONST.NON_NATIVE_EMOJI_PICKER_LIST_HEIGHT` for scrolling the highlighted emoji, which is set to `300` pixels, but the actual height is `256` pixels.
https://github.com/Expensify/App/blob/ed2c287daf6a1d59f4f43a9bfc84128597575730/src/components/EmojiPicker/EmojiPickerMenu/index.js#L400

### What changes do you think we should make in order to solve the problem?

Changing the `CONST.NON_NATIVE_EMOJI_PICKER_LIST_HEIGHT` to `256` pixels in `src/CONST.js` would fix the issue.


```diff
-    NON_NATIVE_EMOJI_PICKER_LIST_HEIGHT: 300,
+    NON_NATIVE_EMOJI_PICKER_LIST_HEIGHT: 256,
```

**Comment by s-alves10** [comment] 2023-08-12 16:43
## Proposal

### Please re-state the problem that we are trying to solve in this issue.

In EmojiPicker, the emoji highlight disappears when scroll with the down arrow

### What is the root cause of that problem?

In order to scroll to the highlighted emoji, we're comparing the highlighted emoji position with `CONST.NON_NATIVE_EMOJI_PICKER_LIST_HEIGHT` now as below
https://github.com/Expensify/App/blob/ed2c287daf6a1d59f4f43a9bfc84128597575730/src/components/EmojiPicker/EmojiPickerMenu/index.js#L399

This value is set to 300 now
https://github.com/Expensify/App/blob/ed2c287daf6a1d59f4f43a9bfc84128597575730/src/CONST.js#L805

But the height of EmojiPicker's list isn't always same with this value

The reasons are:
1. In wide-screen devices, EmojiPicker's height is set to 416 as you can see below
https://github.com/Expensify/App/blob/ed2c287daf6a1d59f4f43a9bfc84128597575730/src/CONST.js#L798

This includes search input(height: 72), category bar(height: 32), EmojiPicker list, and skintone list(height: 56). EmojiPicker list has style `flexShrink: 1, flexGrow: 1` and so its height becomes 256

2. In small-screen devices, we don't explicityl set the height of the EmojiPicker as you can see below
https://github.com/Expensify/App/blob/ed2c287daf6a1d59f4f43a9bfc84128597575730/src/styles/StyleUtils.js#L593-L597

So the the height of the EmojiPicker list has the same value as `CONST.NON_NATIVE_EMOJI_PICKER_LIST_HEIGHT`

3. We have `maxHeight` style for the EmojiPicker list below
https://github.com/Expensify/App/blob/ed2c287daf6a1d59f4f43a9bfc84128597575730/src/styles/StyleUtils.js#L1191

This also affect the height of the EmojiPicker list

These are the root causes of this issue

### What changes do you think we should make in order to solve the problem?

We need to know the current height of the EmojiPicker list. In order to do this,

1. Set NON_NATIVE_EMOJI_PICKER_LIST_HEIGHT to 256
```
    NON_NATIVE_EMOJI_PICKER_LIST_HEIGHT: 256,
```

This ensures the height of the EmojiPicker list is same as this value when maxHeight is larger than this.

2. Update the below line to store the correct height to member variable
https://github.com/Expensify/App/blob/ed2c287daf6a1d59f4f43a9bfc84128597575730/src/components/EmojiPicker/EmojiPickerMenu/index.js#L528-L529

```
        this.emojiListHeight = !listStyle.maxHeight || listStyle.height < listStyle.maxHeight ? listStyle.height : listStyle.maxHeight;
        const overflowLimit = Math.floor(this.emojiListHeight / CONST.EMOJI_PICKER_ITEM_HEIGHT) * 8;
```

3. Use the stored height value when scrolling
https://github.com/Expensify/App/blob/ed2c287daf6a1d59f4f43a9bfc84128597575730/src/components/EmojiPicker/EmojiPickerMenu/index.js#L399-L400

```
        if (offsetAtEmojiBottom - this.currentScrollOffset >= this.emojiListHeight) {
            targetOffset = offsetAtEmojiBottom - this.emojiListHeight;
        }
```

This works perfect for all cases

<details>
    <summary>Result</summary>


https://github.com/Expensify/App/assets/126839717/1ebff0b5-ebf3-4eb6-af6f-e2b64b3ade0f


</details>

### What alternative solutions did you explore? (Optional)

**Comment by kevinksullivan** [comment] 2023-08-17 18:03
Was OOO last week, pushing forward

**Comment by DrLoopFall** [comment] 2023-08-17 20:58
Hi @Santhosh-Sellavel,
Looks like it's caused by #8221 (f734e1c1)

Also, I think we can need to remove `CONST.NON_NATIVE_EMOJI_PICKER_LIST_HEIGHT`, so it sizes automatically with the emoji popup because now the emoji picker is resizable, the picker list height is not constant.

**Comment by carlosalmonte04** [comment] 2023-08-18 01:53
a) Looks like the emoji picker scrolls on its own without needing the `scrollToHighlightedIndex` implementation. Maybe removing it fixes this issue.
b) I saw a significant improvement from using a `throttle` or `debounce` on the `scrollToHighlightedIndex`. Might be a race condition.

**Comment by TTaro** [comment] 2023-08-18 22:01
**Please re-state the problem that we are trying to solve in this issue.**
When navigating through the list using the arrow keys and holding down the key, the selected emoji disappears.

**What is the root cause of that problem?**
f the arrow key is held down, multiple keyboard events are generated, leading to race issues when calculating the highlighted emoji.

**What changes do you think we should make in order to solve the problem?**
1 * Add a new property in the constructor
IsKeyDownInProgress = false

2 In keyDownHandler we can avoid any calculation if is true and if keyBoardEvent="ArrowDown" If not we continue 

3 As last step of  keyDownHandler we change IsKeyDownInProgress =false for same conditions

**Comment by kevinksullivan** [comment] 2023-08-21 22:03
Next step is for @Santhosh-Sellavel to review the comment here https://github.com/Expensify/App/issues/24471#issuecomment-1682971847

**Comment by kevinksullivan** [comment] 2023-08-24 22:52
Hi @Santhosh-Sellavel can you provide an ETA on when you'll be able to review this?. If it's not till next week I'm going to have to reassign.

**Comment by ArekChr** [comment] 2023-08-29 09:48
@DrLoopFall Adjusting the height to 256 affects the 'scroll to bottom' behaviour when using the arrow down key—it now scrolls by just one row of emojis rather than multiple, making it hard to preview the next set of emoji rows. However, changing the height to 460 maintains the original scrolling behaviour. Personally, I'm with the second option which is more user-friendly.

> Also, I think we need to remove CONST.NON_NATIVE_EMOJI_PICKER_LIST_HEIGHT, so it sizes automatically with the emoji popup because now the emoji picker is resizable, so the emoji picker list height is not constant.

That means existing logic in `scrollToHighlightedIndex` is not needed anymore. Do you have this in mind?

**Comment by DrLoopFall** [comment] 2023-08-29 11:47
@ArekChr 

> That means existing logic in `scrollToHighlightedIndex` is not needed anymore. Do you have this in mind?

No, we still need `scrollToHighlightedIndex`

Alternately, I have an even better and more efficient solution, using `scroll-padding-top`
And I've updated my [proposal](https://github.com/Expensify/App/issues/24471#issuecomment-1675806768)(main solution), please have a look at it and let me know what do you think about this?

**Comment by DrLoopFall** [comment] 2023-08-29 11:47
## Proposal
[Updated](https://github.com/Expensify/App/issues/24471#issuecomment-1675806768)

**Comment by DrLoopFall** [comment] 2023-08-29 12:24
The updated proposal fixes the "scrolling to top" behavior it now scrolls multiple rows at once(similar to the bottom scroll) making it easier to preview the next set of emoji rows.

If by chance it was not the intended behavior we can scroll one row at a time just by preventing scroll on focus, and manually focus using the option `{block: 'nearest'}`

```diff
- this.ref.focus();
+ this.ref.focus({preventScroll: true});
+ this.ref.scrollIntoView({block: 'nearest'})
```

@ArekChr Also please let me know your opinion about this?

**Comment by ArekChr** [comment] 2023-08-29 12:28
@DrLoopFall I've experimented with the [proposal](https://github.com/Expensify/App/issues/24471#issuecomment-1675806768) to remove `scrollToHighlightedIndex`, and I think probably `CONST.EMOJI_PICKER_ITEM_HEIGHT` is not needed as well. It works fine, suggesting they may be unnecessary. While there are many ways to address this issue, I am more concerned with removing redundant code over tweaking constant values.

**Comment by DrLoopFall** [comment] 2023-08-29 12:42
@ArekChr 

> I think probably CONST.EMOJI_PICKER_ITEM_HEIGHT is not needed as well

It's actually used in `mWeb`(small width), so if we remove it, then we need to add `CONST.SMALL_EMOJI_PICKER_SIZE.HEIGHT` for `mWeb`, so I think it's better to leave it as it is, as it's just used `mWeb` not won't affect the `web`.

**Comment by TTaro** [comment] 2023-08-29 13:20
Hello @ArekChr @kevinksullivan can you review my proposal ??

**Comment by DrLoopFall** [comment] 2023-08-29 19:20
@ArekChr 
I think the original design was to scroll one row at a time, not multiple rows, see this PR #2532. I think the multiple rows scrolling is a bug. I'm not sure if it was changed later.

As I said [earlier here](https://github.com/Expensify/App/issues/24471#issuecomment-1697342967), this can be achieved by manually scroll with `{block: 'nearest'}`, so I've updated my [proposal](https://github.com/Expensify/App/issues/24471#issuecomment-1675806768) accordingly, please have a look.

**Comment by DrLoopFall** [comment] 2023-08-29 19:20
## Proposal
[Updated](https://github.com/Expensify/App/issues/24471#issuecomment-1675806768)

**Comment by ArekChr** [comment] 2023-08-30 11:17
@TTaro, your proposal makes this part more complicated. I prefer @DrLoopFall's more straightforward idea, which uses scrollIntoView instead of scrollToHighlightedIndex. It seems like a cleaner fix.

**Comment by ArekChr** [comment] 2023-08-30 11:29
@DrLoopFall, your proposal has issues when the window size is smaller than the full size of the emoji picker. This problem is actually addressed in @s-alves10's proposal.

**Comment by TTaro** [comment] 2023-08-30 11:44
@ArekChr ok. Understood, many thanks !

**Comment by s-alves10** [comment] 2023-08-30 11:52
@ArekChr 

What do you think about [my proposal](https://github.com/Expensify/App/issues/24471#issuecomment-1675997903)?

**Comment by DrLoopFall** [comment] 2023-08-30 11:52
Hi @ArekChr,
I can't reproduce the issue, Can you please elaborate a bit more, also please make sure you have added `scrollPaddingTop`.


https://github.com/Expensify/App/assets/120749263/9171a36b-f61a-4c41-8f5e-5c96943f1d6e


https://github.com/Expensify/App/assets/120749263/e2f9a4ed-a334-4171-8676-2b0bfd25fd55

**Comment by ArekChr** [comment] 2023-08-30 11:57
@DrLoopFall, you're correct—I overlooked the styles. Upon including them, there are no additional regressions or bugs. Your [proposal](https://github.com/Expensify/App/issues/24471#issuecomment-1675806768) looks good to me.

:ribbon: :eyes: :ribbon: C+ Reviewed

**Comment by s-alves10** [comment] 2023-08-30 21:29
@DrLoopFall 

Yes, I missed it.

**Comment by ArekChr** [comment] 2023-09-01 08:30
@s-alves10 I've been trying to find the simplest way to fix the issue. I think @DrLoopFall was the first to understand and solve the root problem. Regarding your proposal, it works, and that's appreciated. However, I'm in favour of removing the scrolling logic by replacing `scrollToHighlightedIndex` with `this.ref.scrollIntoView({block: 'nearest'})`. It seems less like a workaround and more like a fix to the problem which will be less susceptible for regressions.

**Comment by DrLoopFall** [comment] 2023-09-04 07:34
@ArekChr @jasperhuangg
The PR #26633 is ready for review

**Comment by kevinksullivan** [comment] 2023-09-07 22:02
Hey @ArekChr please get to the checklist above when you have a chance!

**Comment by kevinksullivan** [comment] 2023-09-07 22:03
@DrLoopFall are you Afsar P on upwork? If yes, please accept the offer! And if not, pelase submit an application to the job

https://www.upwork.com/jobs/~018ba7fbfbb4ccc435

**Comment by DrLoopFall** [comment] 2023-09-08 04:49
@kevinksullivan Yes, I've accepted the offer.

**Comment by kevinksullivan** [comment] 2023-09-14 16:26
All set with payments, closing out

**Closed by kevinksullivan** 2023-09-14 16:26 UTC
Labels: External, Engineering, Daily, Awaiting Payment, Bug
