### ISSUE TITLE
[$2000] mWeb/Chrome - Chat -After refresh the page while offline - the composed box is frizzed and message appears in composed box

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#11265] opened 2022-09-24 17:16 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Issue found when executing PR** https://github.com/Expensify/App/pull/11219

## Action Performed:
1. Go to staging.new.expensify.com
2. Log in with any account
3. Navigate to a chat
4. Go offline
5. Type a draft comment in the composer, **but don’t send it** i.e “test”
6. Tap `+` > `Add attachment` > Take a picture
7. Click `Send`
8. **Verify** “test” appears pending greyed out in the chat
9. **Verify** “Uploading attachment..” appears pending greyed out in the chat
10. Refresh the mWeb browser 
11. Observe the pending message and pending attachment disappear from the chat 
12. Observe the pending message appears in the composer 
13. Go back online
14. Refresh the mWeb browser again to reload the NewDot page
15. The pending message disappears from the composer 
16. The pending message and attachment appear in the chat 

## Expected Result:
When refreshing the mWeb browser when offline, the pending message and pending attachment should not disappear from the chat. Further, the pending message should not appear in the composer. 

## Actual Result:
See action steps 10-16 above. 

## Workaround:
Unknown

## Platform:

Where is this issue occurring?

- Mobile Web (Android/Chrome)

**Version Number:** v1.2.39-0

**Reproducible in staging?:** Yes

**Reproducible in production?:** Yes

**Email or phone of affected tester (no customers):** any

**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Notes/Photos/Videos:** Any additional supporting documentation

https://user-images.githubusercontent.com/16232057/207465005-bc6123c9-5688-4c5f-8de4-09432a528caa.mp4

Device reproduced on: 
- Chrome v⁦108.0.5359.79
- Android 13 build TP1A.221105.002
- Pixel 5a

**Expensify/Expensify Issue URL:** 

**Issue reported by:** Applause - Internal Team

**Slack conversation:** related discussion on latest reproduction [here](https://expensify.slack.com/archives/C01GTK53T8Q/p1670868049859889). 

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by Justicea83** [comment] 2022-09-26 17:35
this can be external

**Comment by Luke9389** [comment] 2022-09-26 22:16
Whoops! Sorry for the noise @kbecciv 

@Justicea83 I reassigned everyone bc I assumed you unassigned us by mistake.

**Comment by mallenexpensify** [comment] 2022-09-27 00:28
posted! https://www.upwork.com/jobs/~01a755aaccee46f8a1

**Comment by mallenexpensify** [comment] 2022-10-05 18:19
Price Doubled to $500
https://www.upwork.com/jobs/~01a755aaccee46f8a1

**Comment by mallenexpensify** [comment] 2022-10-13 14:42
Price Doubled to $1000
https://www.upwork.com/jobs/~01a755aaccee46f8a1

**Comment by mallenexpensify** [comment] 2022-10-25 00:52
Price Doubled to $2000
https://www.upwork.com/jobs/~01a755aaccee46f8a1

**Comment by Luke9389** [comment] 2022-10-25 21:49
Ok so just to help clarify this, it looks like the messages we send when offline are not being saved as pending messages. 

@marcaaron, I know you were across a lot of the `Report_AddComment` refactors. Does this look like something you've seen before in any of the tests for those? If it's not something you recognize off-hand then don't worry about it. I figured it'd be best to just get you to peak at this though.

**Comment by marcaaron** [comment] 2022-10-26 00:02
haven't seen this one before and it looks like a regression

**Comment by Luke9389** [comment] 2022-10-26 20:17
Yeah I agree that it looks like a regression. Thanks for checkin' it out. 

So in this case, would we keep this external and have the Contributor or C+ do the RCA, or do I do that as the assigned CME?

**Comment by Luke9389** [comment] 2022-10-26 20:28
asking in slack

**Comment by marcaaron** [comment] 2022-10-26 20:31
I'm not sure what the current process for an RCA is or if we have one ironed out. Last time I checked it was "nobody's" job to do one. I found [this SO post](https://stackoverflow.com/c/expensify/questions/12156) and it lists the What, Where, When, and Why - but not Who.

**Comment by Luke9389** [comment] 2022-10-26 20:32
Yep, I saw that post too... I'll report back w answers.

**Comment by marcaaron** [comment] 2022-10-26 20:33
This [other post here](https://stackoverflow.com/c/expensify/questions/12158) is implying that the RCA should be done by whoever fixes the issue. Which makes sense since figuring out the "root cause" is probably a pre-requisite for fixing the bug. So in this case, I think it's the C+?

**Comment by mallenexpensify** [comment] 2022-10-26 22:08
I added this to the [RCA sheet](https://docs.google.com/spreadsheets/d/1u73RE8J1DdX3mDohV1RXgulF6_cke3N_a15Sk-UUdQo/edit#gid=0), I know that's step 1! 

We [briefly discussed this morn](https://expensify.slack.com/archives/C02NK2DQWUX/p1666800539491509?thread_ts=1666792980.543399&cid=C02NK2DQWUX), I think it should be @sobitneupane 's job to do the RCA since we don't know the offending PR.  I added the below blurb to the bottom of the [C+ process doc](https://docs.google.com/document/d/1BvohU05MTaHnjOD_vwJv_aqDAirv-ChkyRnKCAvOVyQ/edit#heading=h.ns12dr1f35rx). 

Example from the Slack thread
We want C+ doing as many of these as possible so let's make/keep it fair.
1. C+ (Rajat) is assigned to do an RCA, offending  PR is unknown
2. Offending PR is found
  - If Rajat is author of offending PR, they continue RCA - no pay
  - If Rajat is not author, they assign the RCA to the PR author (Rushat)
  - If Rajat did enough initial work to warrant compensation, they comment on the issue, tag the BZ and provide reasoning why they're due compensation. 
  
 That make enough sense to everyone here?!?!?

**Comment by sobitneupane** [comment] 2022-10-28 14:55
After reloading the page, not only the compose box, nothing is pressable. We don't need to send attachment to reproduce this issue just reloading page is enough.

https://user-images.githubusercontent.com/25876548/198659806-6288097f-160a-493a-ab0a-81cd95a5af40.mp4

**Comment by sobitneupane** [comment] 2022-10-28 15:03
In fact, this issue exists in other pages as well (probably throughout the app). Nothing is pressable after reloading the page in offline.

https://user-images.githubusercontent.com/25876548/198665830-c0196e99-8c94-4e29-8f1f-20a7cb2b4c4c.mp4

**Comment by sobitneupane** [comment] 2022-10-31 05:07
I believe this issue should be divided into following two issues:

->App does not respond to onpress events after reloading. (https://github.com/Expensify/App/issues/11265#issuecomment-1295101299 https://github.com/Expensify/App/issues/11265#issuecomment-1295109964)
->Message reappears in compose box on reloading after sending attachment.

I tried to trace back the commit causing these issues. But both of them were reproducible even ten months back.

cc: @mallenexpensify @Luke9389

**Comment by mallenexpensify** [comment] 2022-10-31 22:45
@Luke9389 do you agree?  

> Message reappears in compose box on reloading after sending attachment.
Is there an issue for this already? Or maybe it's just 'message reappears in compose box after a message is sent'.  I think I commented on that issue last week, wondering if it might be related to "deprecate sequence #" or if we should hold on that

**Comment by Luke9389** [comment] 2022-11-02 18:39
Hmmm, i wonder if another Offline issue is blocking our ability to test the original one. Clearly things _were_ clickable while offline when this issue was created.

**Comment by Luke9389** [comment] 2022-11-02 18:41
@sobitneupane I don't think we should split this issue to address that nothing is clickable after a refresh, that will be a separate bug report. An issue for that might even exist already. We'll need to HOLD this one and wait for the other to be resolved before moving forward (and retesting).

**Comment by mallenexpensify** [comment] 2022-11-09 02:27
@maddylewis Reassigning as I'm heading OOO for a month 
@sobitneupane and @Luke9389 can you help catch Maddy up on where we're at? (I did a quick review and I'm a bit lost, sorry)

**Comment by maddylewis** [comment] 2022-11-14 14:26
@Luke9389 - are we still holding on this issue? https://github.com/Expensify/App/issues/11265#issuecomment-1301065633

**Comment by sobitneupane** [comment] 2022-11-18 11:55
> An issue for that might even exist already. We'll need to HOLD this one and wait for the other to be resolved before moving forward (and retesting).

I cannot find any issue logged in for this.

**Comment by maddylewis** [comment] 2022-11-18 18:44
@Luke9389 - can you provide some clarity on - 
https://github.com/Expensify/App/issues/11265#issuecomment-1301065633 and https://github.com/Expensify/App/issues/11265#issuecomment-1319901107

thank you!

**Comment by maddylewis** [comment] 2022-11-21 14:24
sounds like we're still holding this one: 
> We'll need to HOLD this one and wait for the other to be resolved before moving forward (and retesting).

**Comment by Luke9389** [comment] 2022-11-30 19:09
Ok we just need to verify that the original issues is reproducible, because earlier we couldn't get through all the reproduction steps (my assumption was that there was another bug blocking us from doing so).

@sobitneupane are you able to reproduce this one? 

I'll give it a try too.

**Comment by Luke9389** [comment] 2022-11-30 22:28
OK so I got confused about this earlier. I agree that we should split this into two issues (and tackle the one where nothing is clickable _first_). 
Before we do that, I'm going to reproduce that and search to see if an issue exists already.

**Comment by Luke9389** [comment] 2022-12-01 01:16
When testing this on iOS, I'm not able to reproduce the problem that nothing is clickable after an offline refresh. 

In part that's because I get sent back to the homepage after the refresh. That's covered in this issue [here](https://github.com/Expensify/App/issues/8126). But even then, the UI is definitely clickable. So I think we need to HOLD on that issue. Do you agree @sobitneupane?

**Comment by sobitneupane** [comment] 2022-12-01 12:49
@Luke9389 I can still reproduce it on android mWeb/Chrome.

**Comment by JmillsExpensify** [comment] 2022-12-08 17:43
Tried to test this via Browserstack, but I couldn't get it to work (Browserstack issue more than anything else). 

Regardless though, I feel like this and related issues where a refresh is applied should be held and tackled more holistically. It's also a bit unclear whether this is related to the app navigation reboot (liked the issue @Luke9389 [linked](https://github.com/Expensify/App/issues/8126)), or whether this should be treated independently.

**Comment by Luke9389** [comment] 2022-12-13 02:38
I've just attempted to reproduce this one and still can't. Can you post a video with your reproduction @sobitneupane ?

**Comment by trjExpensify** [comment] 2022-12-13 23:33
Linking [the thread](https://expensify.slack.com/archives/C01GTK53T8Q/p1670868049859889) for the breadcrumbs. 

@alex-mechler was able to help us reproduce this (❤️). Here are the steps we followed: 

> 1. Go to staging.new.expensify.com
> 2. Log in with any account
> 3. Navigate to a chat
> 4. Go offline
> 5. Type a draft comment in the composer, but don’t send it i.e “test”
> 6. Tap `+` > `Add attachment` > Take a picture
> 7. Click `Send`
> 8. **Verify** “test” appears pending greyed out in the chat
> 8. **Verify** “Uploading attachment..” appears pending greyed out in the chat
> 9. Refresh the mWeb browser 
> 10. Observe the pending message and pending attachment disappear from the chat 
> 11. Observe the pending message appears in the composer 
> 12. Go back online
> 13. Refresh the mWeb browser again to reload the NewDot page
> 14. The pending message disappears from the composer 
> 15. The pending message and attachment appear in the chat again and upload

Video reproduction: 

https://user-images.githubusercontent.com/16232057/207465005-bc6123c9-5688-4c5f-8de4-09432a528caa.mp4

Additional notes: 
- If you send the message and attachment separately offline, it works as intended on Android mWeb chrome. Video reproduction [here](https://expensify.slack.com/archives/C01GTK53T8Q/p1670970540877599?thread_ts=1670868049.859889&cid=C01GTK53T8Q). 
- The bug is not reproducible on iOS mWeb Safari & Chrome, Desktop or Web (Chrome) so it's an isolated issue to mWeb chrome on Android only 
- I don’t believe this issue is related to anything with the navigation reboot, so it shouldn’t be held on that initiative. It more so seems to be a regression from the Report_AddComment API refactors, or something that never worked as intended on Android mWeb chrome perhaps?
- Given that it’s well over 4 weeks old at this point and potentially related to something in the API refactors this should become `Internal`. Luke doesn't quite have the bandwidth for it

**Comment by alex-mechler** [comment] 2022-12-14 18:13
I'm seeing the same behavior as that video @sobitneupane

**Comment by trjExpensify** [comment] 2022-12-14 18:25
@sobitneupane I think that's a separate issue, but likely the same cause being how Chrome on Android caches an old version of our site after the refresh. Both of which I don't think we're going to solve now.

**Comment by Luke9389** [comment] 2022-12-14 22:39
Yeah, after speaking about this one at length last night, @trjExpensify @marcaaron and I have come to the conclusion that this issue falls under "unsupported feature". I'll quote Marc's reasoning for this (apologies for not having that discussion in expensify-open-source where it'd be visible and linkable)

> I think we flag this as an “unsupported” feature for now and close anything related to a page that was “reloaded” while offline in Android Chrome. If the repro steps have that then it’s “unsupported”. If we want to support a progressive web app like behavior for our website then we can look into what it takes to do that in the future.

**Comment by trjExpensify** [comment] 2022-12-14 23:40
Cool, cool. That was a fun one! Let's go ahead and close this out. I've added it to an issue housing known bugs when we come across them.

**Closed by trjExpensify** 2022-12-14 23:40 UTC
Labels: External, Engineering, Weekly, Bug
