### ISSUE TITLE
[HOLD for payment 2023-01-23] [$4000] Workspace - The welcome message does not appear immediately after deleting the workspace

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#13615] opened 2022-12-15 11:25 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Go to URL https://staging.new.expensify.com/
2. Login with any account
3. Go to Settings -> Workspace (you should NOT have any workspaces - delete all workspaces if you do)
4. Click "New Workspace" for creating the workspace
5. In the newly created workspace click on 3 dots
6. Click on "Delete workspace" -> "Delete"

## Expected Result:
The welcome message appears immediately

## Actual Result:
The welcome message does not appear immediately - it blinks

## Workaround:
Unknown

## Platform:

Where is this issue occurring?

- Web
- iOS
- Android
- Desktop App
- Mobile Web

**Version Number:** 1.2.39.0

**Reproducible in staging?:** Yes

**Reproducible in production?:** Yes
 
**Email or phone of affected tester (no customers):** 

**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Notes/Photos/Videos:** Any additional supporting documentation

https://user-images.githubusercontent.com/93399543/207847494-e86ae370-5b51-4204-87b3-010443aafed4.mp4

**Expensify/Expensify Issue URL:** 

**Issue reported by:** Applause - Internal Team

**Slack conversation:** 

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~010de9dc97b9a28579</li>
        <li>Upwork Job ID: 1603567405855707136</li>
        <li>Last Price Increase: 2022-12-30</li>
    </ul>
</details>

**Comment by Christinadobrzyn** [comment] 2022-12-16 01:45
- I am able to replicate this by following the steps above. 
- No other GHs matching this issue exist
- I think this can be external

**Comment by bernhardoj** [comment] 2022-12-16 02:53
**Proposal**

When we delete a workspace, we set the optimistic value with `pendingAction` of delete. When we navigated back to the workspace list page, the list still has one workspace left with delete `pendingAction`. If we look at the implementation of `OfflineWithFeedback`, if the `pendingAction` is delete, we will hide it.

https://github.com/Expensify/App/blob/3620bf2fbeba22429e1497802c183626b5803fad/src/components/OfflineWithFeedback.js#L83-L103

And after a while, we will receive a Pusher API update that will set the workspace item value to null.
```[{"key": "policy_142AC62FE7444C5B", "onyxMethod": "set", "value": null}]```

What we can do here is to change the condition to show the empty workspace view. Filter out all workspace with `pendingAction` of delete.

```diff
render() {
    const workspaces = this.getWorkspaces();
+   const isWorkspacesEmpty = _.isEmpty(_.filter(workspaces, workspace => workspace.pendingAction !== CONST.RED_BRICK_ROAD_PENDING_ACTION.DELETE));
    return (
        <ScreenWrapper>
            <HeaderWithCloseButton
                title={this.props.translate('common.workspaces')}
                shouldShowBackButton
                onBackButtonPress={() => Navigation.navigate(ROUTES.SETTINGS)}
                onCloseButtonPress={() => Navigation.dismissModal(true)}
            />
+           {isWorkspacesEmpty ? (
-           {_.isEmpty(workspaces) ? (
                <BlockingView
                    icon={Expensicons.Building}
                    title={this.props.translate('workspace.emptyWorkspace.title')}
                    subtitle={this.props.translate('workspace.emptyWorkspace.subtitle')}
                />
            ) : (
                <ScrollView style={styles.flex1}>
                    {_.map(workspaces, (item, index) => this.getMenuItem(item, index))}
                </ScrollView>
            )}
            <FixedFooter style={[styles.flexGrow0]}>
                <Button
                    success
                    text={this.props.translate('workspace.new.newWorkspace')}
                    onPress={() => Policy.createWorkspace()}
                />
            </FixedFooter>
        </ScreenWrapper>
    );
}

```

**Comment by tienifr** [comment] 2022-12-16 03:38
# Proposal

## Problem

When we delete the workspace we just update the `pendingAction` to `delete` and remove this workspace when API call is successful.
In https://github.com/Expensify/App/blob/main/src/pages/workspace/WorkspacesListPage.js#L118

 we get all the policies and filter by `policy && policy.type === CONST.POLICY.TYPE.FREE && policy.role === CONST.POLICY.ROLE.ADMIN` => the deleted workspace still be there until the API call is  successful.

## Solution
we shouldn't filter out the workspace that has pendingAction === 'delete' when we're in offline

I'll filter out the workspace that has pendingAction === 'delete' when we're in online.

In https://github.com/Expensify/App/blob/main/src/pages/workspace/WorkspacesListPage.js

```diff
...
    getWorkspaces() {
        return _.chain(this.props.policies)
            .filter(policy => policy && policy.type === CONST.POLICY.TYPE.FREE && policy.role === CONST.POLICY.ROLE.ADMIN)
+           .filter(policy => this.props.network.isOffline || policy.pendingAction !== CONST.RED_BRICK_ROAD_PENDING_ACTION.DELETE)

...

export default compose(
    withLocalize,
+   withNetwork(),
...

```

https://user-images.githubusercontent.com/113963320/208016348-7e3fd25a-cf38-47b4-b2c0-5f6bdc20fa35.mp4

**Comment by s77rt** [comment] 2022-12-16 10:15
### Proposal
```diff
diff --git a/src/pages/workspace/WorkspacesListPage.js b/src/pages/workspace/WorkspacesListPage.js
index 41c6b3babe..2c037c685d 100755
--- a/src/pages/workspace/WorkspacesListPage.js
+++ b/src/pages/workspace/WorkspacesListPage.js
@@ -115,7 +115,10 @@ class WorkspacesListPage extends Component {
      */
     getWorkspaces() {
         return _.chain(this.props.policies)
-            .filter(policy => policy && policy.type === CONST.POLICY.TYPE.FREE && policy.role === CONST.POLICY.ROLE.ADMIN)
+            .filter(policy => policy
+                && policy.type === CONST.POLICY.TYPE.FREE
+                && policy.role === CONST.POLICY.ROLE.ADMIN
+                && policy.pendingAction !== CONST.RED_BRICK_ROAD_PENDING_ACTION.DELETE)
             .map(policy => ({
                 title: policy.name,
                 icon: policy.avatar ? policy.avatar : Expensicons.Building,
@@ -128,7 +131,6 @@ class WorkspacesListPage extends Component {
                 pendingAction: policy.pendingAction,
                 errors: policy.errors,
                 dismissError: () => dismissWorkspaceError(policy.id, policy.pendingAction),
-                disabled: policy.pendingAction === CONST.RED_BRICK_ROAD_PENDING_ACTION.DELETE,
             }))
             .sortBy(policy => policy.title)
             .value();
@@ -164,7 +166,6 @@ class WorkspacesListPage extends Component {
                     badgeText={this.getWalletBalance(isPaymentItem)}
                     fallbackIcon={item.fallbackIcon}
                     brickRoadIndicator={item.brickRoadIndicator}
-                    disabled={item.disabled}
                 />
             </OfflineWithFeedback>
         );
```

### RCA
I agree with the above @bernhardoj @tienifr analysis

### Solution
Filter out workspaces that have `pendingAction` equal to `CONST.RED_BRICK_ROAD_PENDING_ACTION.DELETE` 
Remove the unused `disabled` prop

### Alternative solutions
1. Add a new prop `OfflineWithFeedback` to decide whether children should be hidden

**Comment by Christinadobrzyn** [comment] 2022-12-21 02:18
I'll be ooo till Jan 9th, assigning this issue to @mallenexpensify. Matt, I'm happy to take it back when I return!

**Comment by syedsaroshfarrukhdot** [comment] 2022-12-21 04:11
Proposal :- 

With all above proposals when we `filter` list  on `policy.pendingAction` it causes a regression as shown in below `video`. The `pendingAction` changes from `delete` to `undefined` which causes deleted workspace to reappear in the list for a split second.

Regression Video :-

https://user-images.githubusercontent.com/81307212/208817357-99faf45c-a9ef-43bc-9072-6d67597daebc.mov

As `pendingAction : undefined` is set before removing it from the list. We can fix it in Policy.js `deleteWorkspace` function by passing a new value `lastAction` in `optimisticData` which isn't modified and filter list on it.

``` diff 
diff --git a/src/libs/actions/Policy.js b/src/libs/actions/Policy.js
index 0f6784e7d..2bb5117eb 100644
--- a/src/libs/actions/Policy.js
+++ b/src/libs/actions/Policy.js
@@ -68,6 +68,7 @@ function deleteWorkspace(policyID, reports) {
             value: {
                 pendingAction: CONST.RED_BRICK_ROAD_PENDING_ACTION.DELETE,
                 errors: null,
+                lastAction : CONST.RED_BRICK_ROAD_PENDING_ACTION.DELETE,
             },
         },
         ..._.map(reports, ({reportID}) => ({
@@ -82,6 +83,7 @@ function deleteWorkspace(policyID, reports) {
         })),
     ];
 
+
     // Restore the old report stateNum and statusNum
     const failureData = [
         ..._.map(reports, ({


diff --git a/src/pages/workspace/WorkspacesListPage.js b/src/pages/workspace/WorkspacesListPage.js
index 41c6b3bab..a79fce73d 100755
--- a/src/pages/workspace/WorkspacesListPage.js
+++ b/src/pages/workspace/WorkspacesListPage.js
@@ -114,8 +114,9 @@ class WorkspacesListPage extends Component {
      * @returns {Array} the menu item list
      */
     getWorkspaces() {
+        
         return _.chain(this.props.policies)
-            .filter(policy => policy && policy.type === CONST.POLICY.TYPE.FREE && policy.role === CONST.POLICY.ROLE.ADMIN
)
+            .filter(policy => policy && policy.type === CONST.POLICY.TYPE.FREE && policy.role === CONST.POLICY.ROLE.ADMIN && policy.lastAction !== CONST.RED_BRICK_ROAD_PENDING_ACTION.DELETE)
             .map(policy => ({
                 title: policy.name,
                 icon: policy.avatar ? policy.avatar : Expensicons.Building,
@@ -172,6 +173,7 @@ class WorkspacesListPage extends Component {
 
     render() {
         const workspaces = this.getWorkspaces();

         return (
             <ScreenWrapper>
                 <HeaderWithCloseButton
```

After Fix :- 

https://user-images.githubusercontent.com/81307212/208818113-9185caff-1c2d-4380-9fd5-f95dcd6d9a0c.mov

We can also not filter list when we are offline if we want to

``` diff
...
    getWorkspaces() {
        return _.chain(this.props.policies)
            .filter(policy => policy && policy.type === CONST.POLICY.TYPE.FREE && policy.role === CONST.POLICY.ROLE.ADMIN)
+           .filter(policy => this.props.network.isOffline || policy.pendingAction !== CONST.RED_BRICK_ROAD_PENDING_ACTION.DELETE)

...

export default compose(
    withLocalize,
+   withNetwork(),
...
```
After Offline Filtering Fix :-


https://user-images.githubusercontent.com/81307212/208819235-296294c0-a3ae-4a61-8581-883dd701f414.mov

**Comment by s77rt** [comment] 2022-12-21 11:55
@syedsaroshfarrukhdot Nice catch, but this is not a regression from my proposal, this issue existed long before. Your solution does not address the root cause for that either.

The workspace will appear again for a short period only if you create the workspace and delete it immediately (in very short time), here is the order of events:
1. Create workspace button is clicked
2. `optimisticData` sets the `pendingAction` to `add`
3. Create workspace request is still going...
4. Delete workspace
5. `optimisticData` sets the `pendingAction` to `delete` <-- Workspace no longer visible
6. Delete workspace request is still going...
7. Create workspace request is done
8. `successData` sets the `pendingAction` to `null` <-- Workspace is visible again (root cause)
9. Delete workspace request is done
10. A pusher notification will be received where it sets the `workspace` to `null` <-- Workspace no longer exists

As you see this is an edge case and we shouldn't prioritise it, besides the final results is the workspace being deleted and not visible (self fix)

___

I think we still should go with my proposal, but just curious why you are adding the `network.isOffline` check?

**Comment by syedsaroshfarrukhdot** [comment] 2022-12-22 00:52
@s77rt Yes, I agree with your analysis it is an edge case and it can be handled on filtering `Workspaces` on a prop which doesn't change just like in my proposal. So I believe once we are taking care of it it should be fixed along with edge case rest is up to team on what they decide how to handle it. 

I am using `network.isOffline ` to not filter out deleted workspace when in offline mode just like in the proposal video. When a workspace is deleted while offline it shouldn't be filtered unless user becomes online and actually the workspaces I deleted.

**Comment by s77rt** [comment] 2022-12-22 12:42
@syedsaroshfarrukhdot Thanks for the clarification, however I still think we should go with my proposal (without adding a new prop) as that's how we deal with similar cases https://github.com/Expensify/App/blob/main/src/pages/settings/InitialSettingsPage.js#L130-L137

As for the offline case, your explanation makes sense, I will update my proposal to cover the offline cases in few minutes in both `InitialSettingsPage` and `WorkspacesListPage` 

Another question: Why you are using two filters calls? it's expensive to call functions in JS and iterate over the objects twice, just wrap them in one filter for future proposals.

**Comment by s77rt** [comment] 2022-12-22 12:45
### Proposal (Updated)
```diff
diff --git a/src/pages/settings/InitialSettingsPage.js b/src/pages/settings/InitialSettingsPage.js
index c2bf6b384b..18d1067f31 100755
--- a/src/pages/settings/InitialSettingsPage.js
+++ b/src/pages/settings/InitialSettingsPage.js
@@ -131,7 +131,7 @@ class InitialSettingsPage extends React.Component {
             .filter(policy => policy
                 && policy.type === CONST.POLICY.TYPE.FREE
                 && policy.role === CONST.POLICY.ROLE.ADMIN
-                && policy.pendingAction !== CONST.RED_BRICK_ROAD_PENDING_ACTION.DELETE)
+                && (this.props.network.isOffline || policy.pendingAction !== CONST.RED_BRICK_ROAD_PENDING_ACTION.DELETE))
             .sortBy(policy => policy.name)
             .pluck('avatar')
             .value();
diff --git a/src/pages/workspace/WorkspacesListPage.js b/src/pages/workspace/WorkspacesListPage.js
index 41c6b3babe..5fc2446513 100755
--- a/src/pages/workspace/WorkspacesListPage.js
+++ b/src/pages/workspace/WorkspacesListPage.js
@@ -23,6 +23,7 @@ import Permissions from '../../libs/Permissions';
 import Button from '../../components/Button';
 import FixedFooter from '../../components/FixedFooter';
 import BlockingView from '../../components/BlockingViews/BlockingView';
+import {withNetwork} from '../../components/OnyxProvider';
 
 const propTypes = {
     /* Onyx Props */
@@ -115,7 +116,10 @@ class WorkspacesListPage extends Component {
      */
     getWorkspaces() {
         return _.chain(this.props.policies)
-            .filter(policy => policy && policy.type === CONST.POLICY.TYPE.FREE && policy.role === CONST.POLICY.ROLE.ADMIN)
+            .filter(policy => policy
+                && policy.type === CONST.POLICY.TYPE.FREE
+                && policy.role === CONST.POLICY.ROLE.ADMIN
+                && (this.props.network.isOffline || policy.pendingAction !== CONST.RED_BRICK_ROAD_PENDING_ACTION.DELETE))
             .map(policy => ({
                 title: policy.name,
                 icon: policy.avatar ? policy.avatar : Expensicons.Building,
@@ -222,4 +226,5 @@ export default compose(
             key: ONYXKEYS.BETAS,
         },
     }),
+    withNetwork(),
 )(WorkspacesListPage);
```

### Update
- Cover offline cases in `InitialSettingsPage` and `WorkspacesListPage`



https://user-images.githubusercontent.com/16493223/209137025-fdd13835-7783-4ae8-8704-ac44797d2f8f.mp4

**Comment by syedsaroshfarrukhdot** [comment] 2022-12-22 13:37
> Another question: Why you are using two filters calls? it's expensive to call functions in JS and iterate over the objects twice, just wrap them in one filter for future proposals.

Agree with you will also post an updated proposal and will use one filter call to avoid it.

**Comment by syedsaroshfarrukhdot** [comment] 2022-12-22 14:08
Update Proposal :- 

With all above proposals when we `filter` list  on `policy.pendingAction` it causes a regression as shown in below `video`. The `pendingAction` changes from `delete` to `undefined` which causes deleted workspace to reappear in the list for a split second.

Regression Video :-

https://user-images.githubusercontent.com/81307212/208817357-99faf45c-a9ef-43bc-9072-6d67597daebc.mov

As `pendingAction : undefined` is set before removing it from the list. We can fix it in Policy.js `deleteWorkspace` function by passing a new value `lastAction` in `optimisticData` which isn't modified and filter list on it.

``` diff
diff --git a/src/libs/actions/Policy.js b/src/libs/actions/Policy.js
index 0f6784e7d..eaa86a752 100644
--- a/src/libs/actions/Policy.js
+++ b/src/libs/actions/Policy.js
@@ -67,6 +67,7 @@ function deleteWorkspace(policyID, reports) {
             key: `${ONYXKEYS.COLLECTION.POLICY}${policyID}`,
             value: {
                 pendingAction: CONST.RED_BRICK_ROAD_PENDING_ACTION.DELETE,
+                lastAction: CONST.RED_BRICK_ROAD_PENDING_ACTION.DELETE,
                 errors: null,
             },
         },
diff --git a/src/pages/settings/InitialSettingsPage.js b/src/pages/settings/InitialSettingsPage.js
index c2bf6b384..bd64cf64d 100755
--- a/src/pages/settings/InitialSettingsPage.js
+++ b/src/pages/settings/InitialSettingsPage.js
@@ -131,7 +131,7 @@ class InitialSettingsPage extends React.Component {
             .filter(policy => policy
                 && policy.type === CONST.POLICY.TYPE.FREE
                 && policy.role === CONST.POLICY.ROLE.ADMIN
-                && policy.pendingAction !== CONST.RED_BRICK_ROAD_PENDING_ACTION.DELETE)
+                && (this.props.network.isOffline || policy.lastAction !== CONST.RED_BRICK_ROAD_PENDING_ACTION.DELETE))
             .sortBy(policy => policy.name)
             .pluck('avatar')
             .value();
diff --git a/src/pages/workspace/WorkspacesListPage.js b/src/pages/workspace/WorkspacesListPage.js
index 41c6b3bab..a097a7433 100755
--- a/src/pages/workspace/WorkspacesListPage.js
+++ b/src/pages/workspace/WorkspacesListPage.js
@@ -23,6 +23,7 @@ import Permissions from '../../libs/Permissions';
 import Button from '../../components/Button';
 import FixedFooter from '../../components/FixedFooter';
 import BlockingView from '../../components/BlockingViews/BlockingView';
+import { withNetwork } from '../../components/OnyxProvider';
 
 const propTypes = {
     /* Onyx Props */
@@ -115,7 +116,10 @@ class WorkspacesListPage extends Component {
      */
     getWorkspaces() {
         return _.chain(this.props.policies)
-            .filter(policy => policy && policy.type === CONST.POLICY.TYPE.FREE && policy.role === CONST.POLICY.ROLE.ADMIN)
+        .filter(policy => policy
+                && policy.type === CONST.POLICY.TYPE.FREE
+                && policy.role === CONST.POLICY.ROLE.ADMIN
+                && (this.props.network.isOffline || policy.lastAction !== CONST.RED_BRICK_ROAD_PENDING_ACTION.DELETE))
             .map(policy => ({
                 title: policy.name,
                 icon: policy.avatar ? policy.avatar : Expensicons.Building,
@@ -208,6 +212,7 @@ WorkspacesListPage.defaultProps = defaultProps;
 
 export default compose(
     withLocalize,
+    withNetwork(),
     withOnyx({
         policies: {
             key: ONYXKEYS.COLLECTION.POLICY,
```
After Fix :- 

https://user-images.githubusercontent.com/81307212/208818113-9185caff-1c2d-4380-9fd5-f95dcd6d9a0c.mov

Offline Fix :-

https://user-images.githubusercontent.com/81307212/208819235-296294c0-a3ae-4a61-8581-883dd701f414.mov

**Comment by jatinsonijs** [comment] 2022-12-23 11:48
**Proposal**

We have to filter policies - Filter out all delete pending policy if not offline and not have an error in policy.

```diff
diff --git a/src/pages/settings/InitialSettingsPage.js b/src/pages/settings/InitialSettingsPage.js
index c2bf6b384b..0c28382cd2 100755
--- a/src/pages/settings/InitialSettingsPage.js
+++ b/src/pages/settings/InitialSettingsPage.js
@@ -130,8 +130,9 @@ class InitialSettingsPage extends React.Component {
         const policiesAvatars = _.chain(this.props.policies)
             .filter(policy => policy
                 && policy.type === CONST.POLICY.TYPE.FREE
-                && policy.role === CONST.POLICY.ROLE.ADMIN
-                && policy.pendingAction !== CONST.RED_BRICK_ROAD_PENDING_ACTION.DELETE)
+                && policy.role === CONST.POLICY.ROLE.ADMIN)
+            .filter(policy => this.props.network.isOffline
+                    || (policy.pendingAction === CONST.RED_BRICK_ROAD_PENDING_ACTION.DELETE ? !_.isEmpty(policy.errors) : true))
             .sortBy(policy => policy.name)
             .pluck('avatar')
             .value();
diff --git a/src/pages/workspace/WorkspacesListPage.js b/src/pages/workspace/WorkspacesListPage.js
index 41c6b3babe..174469437f 100755
--- a/src/pages/workspace/WorkspacesListPage.js
+++ b/src/pages/workspace/WorkspacesListPage.js
@@ -23,6 +23,7 @@ import Permissions from '../../libs/Permissions';
 import Button from '../../components/Button';
 import FixedFooter from '../../components/FixedFooter';
 import BlockingView from '../../components/BlockingViews/BlockingView';
+import {withNetwork} from '../../components/OnyxProvider';
 
 const propTypes = {
     /* Onyx Props */
@@ -116,6 +117,8 @@ class WorkspacesListPage extends Component {
     getWorkspaces() {
         return _.chain(this.props.policies)
             .filter(policy => policy && policy.type === CONST.POLICY.TYPE.FREE && policy.role === CONST.POLICY.ROLE.ADMIN)
+            .filter(policy => this.props.network.isOffline
+                || (policy.pendingAction === CONST.RED_BRICK_ROAD_PENDING_ACTION.DELETE ? !_.isEmpty(policy.errors) : true))
             .map(policy => ({
                 title: policy.name,
                 icon: policy.avatar ? policy.avatar : Expensicons.Building,
@@ -208,6 +211,7 @@ WorkspacesListPage.defaultProps = defaultProps;
 
 export default compose(
     withLocalize,
+    withNetwork(),
     withOnyx({
         policies: {
             key: ONYXKEYS.COLLECTION.POLICY,
```

**Note: We can do actions in one filter also but it will become lengthy and not easy to read.**

**Optionally:** We can also create common function in PolicyUtil In future it will easy to change and not have to do changes on two places.

```diff
diff --git a/src/libs/PolicyUtils.js b/src/libs/PolicyUtils.js
index 3def54c19f..aad55035a2 100644
--- a/src/libs/PolicyUtils.js
+++ b/src/libs/PolicyUtils.js
@@ -54,9 +54,26 @@ function getPolicyBrickRoadIndicatorStatus(policy, policyMembers) {
     return '';
 }
 
+/**
+ * Check if policy can be display
+ * @param {Object} policy
+ * @param {boolean} isOffline
+ * @returns {boolean}
+ */
+function shouldShowPolicy(policy, isOffline) {
+    return policy
+    && policy.type === CONST.POLICY.TYPE.FREE
+    && policy.role === CONST.POLICY.ROLE.ADMIN
+    && (isOffline || (
+        policy.pendingAction === CONST.RED_BRICK_ROAD_PENDING_ACTION.DELETE
+            ? !_.isEmpty(policy.errors) : true
+    ));
+}
+
 export {
     hasPolicyMemberError,
     hasPolicyError,
     hasCustomUnitsError,
     getPolicyBrickRoadIndicatorStatus,
+    shouldShowPolicy,
 };
diff --git a/src/pages/settings/InitialSettingsPage.js b/src/pages/settings/InitialSettingsPage.js
index c2bf6b384b..6d1aa97ea2 100755
--- a/src/pages/settings/InitialSettingsPage.js
+++ b/src/pages/settings/InitialSettingsPage.js
@@ -128,10 +128,7 @@ class InitialSettingsPage extends React.Component {
      */
     getDefaultMenuItems() {
         const policiesAvatars = _.chain(this.props.policies)
-            .filter(policy => policy
-                && policy.type === CONST.POLICY.TYPE.FREE
-                && policy.role === CONST.POLICY.ROLE.ADMIN
-                && policy.pendingAction !== CONST.RED_BRICK_ROAD_PENDING_ACTION.DELETE)
+            .filter(policy => PolicyUtils.shouldShowPolicy(policy, this.props.network.isOffline))
             .sortBy(policy => policy.name)
             .pluck('avatar')
             .value();
diff --git a/src/pages/workspace/WorkspacesListPage.js b/src/pages/workspace/WorkspacesListPage.js
index 41c6b3babe..5ef22eea79 100755
--- a/src/pages/workspace/WorkspacesListPage.js
+++ b/src/pages/workspace/WorkspacesListPage.js
@@ -23,6 +23,7 @@ import Permissions from '../../libs/Permissions';
 import Button from '../../components/Button';
 import FixedFooter from '../../components/FixedFooter';
 import BlockingView from '../../components/BlockingViews/BlockingView';
+import {withNetwork} from '../../components/OnyxProvider';
 
 const propTypes = {
     /* Onyx Props */
@@ -115,7 +116,7 @@ class WorkspacesListPage extends Component {
      */
     getWorkspaces() {
         return _.chain(this.props.policies)
-            .filter(policy => policy && policy.type === CONST.POLICY.TYPE.FREE && policy.role === CONST.POLICY.ROLE.ADMIN)
+            .filter(policy => PolicyUtils.shouldShowPolicy(policy, this.props.network.isOffline))
             .map(policy => ({
                 title: policy.name,
                 icon: policy.avatar ? policy.avatar : Expensicons.Building,
@@ -208,6 +209,7 @@ WorkspacesListPage.defaultProps = defaultProps;
 
 export default compose(
     withLocalize,
+    withNetwork(),
     withOnyx({
         policies: {
             key: ONYXKEYS.COLLECTION.POLICY,
```

**Comment by jatinsonijs** [comment] 2022-12-23 11:51
And I think causes deleted workspace to reappear in the list for a split second its different issue not related to this issue. There is also another issue related to race condition.
Try to create workspace and immediately turn off network. Now turn on network workspace will not create with error 
"An unexpected error occurred while trying to create your Workspace. Please try again.New workspace"

**Comment by mallenexpensify** [comment] 2022-12-23 23:55
@parasharrajat , can you review the proposals above when you get a chance?

**Comment by mallenexpensify** [comment] 2022-12-29 01:22
@parasharrajat  to review proposals

**Comment by jatinsonijs** [comment] 2022-12-30 17:03
@parasharrajat I have found some ref which may be case of this issue

Issue: https://github.com/Expensify/App/issues/13192
PR: https://github.com/Expensify/App/pull/13201

**Comment by s77rt** [comment] 2022-12-31 18:55
@jatinsonijs Do you think the provided solutions re-create the issue? Are we in a loop?

**Comment by s77rt** [comment] 2022-12-31 20:00
@jatinsonijs I see that your proposal have a condition for errors too. I think that will do it.

___

Just a note, I think you can change the third condition to:
```
this.props.network.isOffline || policy.pendingAction !== CONST.RED_BRICK_ROAD_PENDING_ACTION.DELETE || !_.isEmpty(policy.errors)
``` 

It's the same condition used here https://github.com/Expensify/App/blob/304d759a4792c2fa1e5294741c142c28448fe507/src/components/OfflineWithFeedback.js#L90


___

Overall, good catch. I like your proposal :+1:

**Comment by jatinsonijs** [comment] 2023-01-01 03:38
> ```
> this.props.network.isOffline || policy.pendingAction !== CONST.RED_BRICK_ROAD_PENDING_ACTION.DELETE || !_.isEmpty(policy.errors)
> ```

Hi @s77rt thanks for you comment. At starting I also thought or || condition will be enough but I guess above linked issue condition is
policy is in delete pending action and also have error. In this case this condition will not work.

**Comment by s77rt** [comment] 2023-01-01 06:50
@jatinsonijs I don't see why it won't work.
We will return policies that meets at least of those requirements, if a policy has an error it will be kept and shown.

> it will never check error it will return from the != deletePending

Yes, and that what is expected to happen. If a policy is not being deleted, keep it
If it's being deleted (condition not met) we will check the last condition, if it has error or not...

**Comment by jatinsonijs** [comment] 2023-01-01 07:01
Yes right, I had over thought it 🙂. Both condition are working we can use or || to simplify it.

**Comment by jatinsonijs** [comment] 2023-01-02 06:58
@parasharrajat if you are on Mac you can try on desktop app.

**Comment by srikarparsi** [comment] 2023-01-02 21:23
Hey @mallenexpensify! I'm taking a break from expensify this semester to finish up classes. Do you think you could reassign this to another engineer?

**Comment by mallenexpensify** [comment] 2023-01-03 02:15
Sorry @thesahindia there was an issue with auto-assign logic, looking into internally.  
Welcome @NikkiWines !!

**Comment by jatinsonijs** [comment] 2023-01-03 16:04
@parasharrajat I think you have to get special account access which is creating error in workspace deletion. With normal account I haven't got any error.

**Comment by jatinsonijs** [comment] 2023-01-06 16:38
> It seems that @jatinsonijs's proposal makes the most sense out of all.

@parasharrajat have you test it ?, if you have any feedback plz let me know

**Comment by jatinsonijs** [comment] 2023-01-06 18:23
no dont know the password

**Comment by jatinsonijs** [comment] 2023-01-06 19:57
> **Optionally:** We can also create common function in PolicyUtil In future it will easy to change and not have to do changes on two places.

@parasharrajat should I create common function in PolicyUtils.js or we are ok with do changes at 2 places ?

**Comment by jatinsonijs** [comment] 2023-01-06 20:03
Yeah understood, waiting for final approval.

**Comment by NikkiWines** [comment] 2023-01-06 21:51
Agreed, the common function is the better route. @jatinsonijs' proposal also looks good to me. @mallenexpensify or @Christinadobrzyn can one of you hire @jatinsonijs for this role? Thank you 🙇

**Comment by JmillsExpensify** [comment] 2023-01-09 19:31
I went ahead and assigned the Contributor so we can get the PR in motion.

**Comment by jatinsonijs** [comment] 2023-01-09 19:35
Thanks @JmillsExpensify, applied

**Comment by jatinsonijs** [comment] 2023-01-09 19:58
PR is ready for review

**Comment by mallenexpensify** [comment] 2023-01-09 23:09
@jatinsonijs hired in Upwork. 
@parasharrajat can you please apply? 
https://www.upwork.com/jobs/~010de9dc97b9a28579

**Comment by mallenexpensify** [comment] 2023-01-12 20:00
Reminder @jatinsonijs is eligible for the timeliness bonus.  Assigned the issue on Jan 9 and PR merged on Jan 12.

**Comment by NikkiWines** [comment] 2023-01-18 02:01
> A discussion in #expensify-bugs has been started about whether any other steps should be taken (e.g. updating the PR review checklist) in order to catch this type of bug sooner. Link to discussion: 

For this, I don't really think there was a regression or we could've caught this earlier. This behavior was introduced back when we originally added workspaces into newDot. We have solid documentation on ensuring actions are done optimistically, so I think that should be sufficient in this case.

**Comment by mallenexpensify** [comment] 2023-01-19 01:21
I'd just check the box then @NikkiWines , I'm asking about the steps/process for updating TestRail here
https://expensify.slack.com/archives/C9YU7BX5M/p1674091251918159

**Comment by jatinsonijs** [comment] 2023-01-25 15:33
@mallenexpensify can you plz look into this, regression period is over.

**Comment by mallenexpensify** [comment] 2023-01-25 18:44
@jatinsonijs I'm working on updating the regression steps and I see the final test step listed in your PR as
> Verify welcome message (empty list message) appear immediately.

Yet, when I delete a workspace I:
- If the main chat window isn't #announce for the workspace, nothing happens
- If the main chat window **is** the #announce room it shows as archived. 

So I'm not seeing a 'welcome message'.  Am I missing something or are the two steps above the expected behavior?

**Comment by jatinsonijs** [comment] 2023-01-25 18:47
@mallenexpensify it is about this message

<img width="373" alt="Screenshot 2023-01-26 at 12 16 34 AM" src="https://user-images.githubusercontent.com/114683042/214655247-8454090b-3f7b-4ad1-9a22-43e9787227a3.png">
 message:

**Comment by jatinsonijs** [comment] 2023-01-25 18:49
I have referred it as welcome message bcz in issue title it is called as welcome message.

**Comment by mallenexpensify** [comment] 2023-01-25 19:43
Thanks @jatinsonijs, I was testing on Desktop.  Was able to reproduce to get the screen above.

**Comment by mallenexpensify** [comment] 2023-01-25 19:48
Checking with QA about test step updates https://expensify.slack.com/archives/C9YU7BX5M/p1674676068594109

**Comment by mallenexpensify** [comment] 2023-01-27 01:58
Checking in #qa again
https://expensify.slack.com/archives/C9YU7BX5M/p1674676068594109

**Comment by mallenexpensify** [comment] 2023-01-30 20:41
Hired @parasharrajat , can you please accept the job and reply here once you have? 
Total is $6K inc. timeliness bonus

**Comment by mallenexpensify** [comment] 2023-01-31 21:32
Paid $6K to @parasharrajat for +C, includes timeliness budget. 

Triple checking in #qa about steps

**Comment by mallenexpensify** [comment] 2023-02-01 16:20
Gonna propose these. 
 https://expensify.testrail.io/index.php?/cases/view/1971214
Update step 8 and add step 9 
8. Desktop - Verify the main chat window is the #announce room it shows as archived.
9 Mobile - Verify you're taken to the "Create a new workspace" window.

https://expensify.slack.com/archives/C01SKUP7QR0/p1675268410262409

**Comment by mallenexpensify** [comment] 2023-02-01 19:35
https://github.com/Expensify/Expensify/issues/259653
TestRail steps proposed, assigned myself to ensure they're updated. Checklist updated 👋

**Closed by mallenexpensify** 2023-02-01 19:35 UTC
Labels: External, Daily, Awaiting Payment, Bug

**Comment by mallenexpensify** [comment] 2023-02-10 22:12
@parasharrajat , reviewing this issue.  It appears your reviews took a while and the priced jumped from $1k to $4k before you reviewed the accepted proposal from @jatinsonijs.  I think part (at least) of the reason was due to IP-related issues around this time.  Please try to review proposals as promptly as possible to reduce the chance of prices unnecessarily doubling. 

12/23 - @jatinsonijs [proposal ](https://github.com/Expensify/App/issues/13615#issuecomment-1363886220)
12/29 - no reviews, [comment from you](https://github.com/Expensify/App/issues/13615#issuecomment-1367453852) - "Checking the issue now."
Jan 1 - issues raised to $4000 before[ proposal review.](https://github.com/Expensify/App/issues/13615#issuecomment-1368694131)
