### ISSUE TITLE
[HOLD for payment 2024-02-26] [$500] Chat - Some skin colors are only affecting one of the faces

### ISSUE THREAD

**Issue by kavimuru** [Expensify/App#35382] opened 2024-01-30 11:19 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.33.0

**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** Applause internal team
**Slack conversation:**

## Action Performed:
1. Open a chat
2. Open the emoji picker
3. Scroll down until you see couples with a heart above them
4. Switch between all skin colors

## Expected Result:
All skin colors should affect both of the faces or just only one of them.

## Actual Result:
The yellow color is appecting both of the faces. All other skin tones are only affecting the right face.

## Workaround:
unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [ ] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

https://github.com/Expensify/App/assets/43996225/332e5e9e-2e18-45e2-bf0d-b44210097b08

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~0105e72483a5f5d73f</li>
        <li>Upwork Job ID: 1752290333764239360</li>
        <li>Last Price Increase: 2024-01-30</li>
<li>Automatic offers: </li>
<ul>
<li>dukenv0307 | Contributor | 28142553</li>
</ul></li>
    </ul>
</details>

**Comment by Yokomon** [comment] 2024-01-30 20:31
### Proposal

### Please re-state the problem that we are trying to solve in this issue.

The yellow color is affecting both of the faces. All other skin tones are only affecting the right face.

### What is the root cause of that problem?

Did some investigation related to the EmojiPicker component and found out the bug is related to the index used to fetch the filteredEmojis based from the selectedSkinTone. From the index of the [preferredSkinTone](https://github.com/Expensify/App/blob/5aa322544c984d5d754ae6980ab577cea2d1f301/src/components/EmojiPicker/EmojiPickerMenu/index.js#L344) in the EmojiPickerMenu, the system uses an index system that ranges from [-1 to 4]. And the index generated from the selected skin tone is used to Map to the emojis types which is an **array** gotten from [assets/common](https://github.com/Expensify/App/blob/eb031dc2ee42def13f84e47dd978992659a11a05/assets/emojis/common.ts#L39). 

Currently there is 25 items in the array for the emoji with the couple_kisses and other related emojis, The problem is that the mapped emoji from the **preferredSkinTone** index is mapping to the wrong index in the **emojis types**.

### What changes do you think we should make in order to solve the problem?

If we can make a complete refactor of the emojis assets and place the right emojis based on the preferredSkinTone selected from the user, we fix the problem. Therefore, if the preferredSkinTone is having an index of 4, we are mapping the types from the refactored emojis to equal the right emoji types[4].

I made a refactor of the emojis assets file and also made some regression tests locally to make sure all works fine as well.

P.S: In the creation of the emoji assets creation, i noticed there were some emoji items which were not of use anymore and were collecting memory in the array. I removed those emojis to make sure we have a consistent emoji system across the application and to prevent future bugs from reoccurring.


Attached is the solution working on my local machine awaiting approval.

https://github.com/Expensify/App/assets/47699250/7ace505d-f759-4766-a123-5475f612bf57


@kavimuru Please have a look. Thank you.

**Comment by Yokomon** [comment] 2024-01-30 20:34
Contributor details
Your Expensify account email: marowmars@gmail.com
Upwork Profile Link: https://www.upwork.com/freelancers/~01457ed5bd560af031

**Comment by allroundexperts** [comment] 2024-02-02 20:55
Reviewing now @MelvinBot!

**Comment by allroundexperts** [comment] 2024-02-02 21:29
Thanks for the proposals everyone. Both proposals have the correct RCA and the solution is more or less the same as well.

Since @dukenv0307 was the first one to propose the solution, I think we should proceed with there [proposal](https://github.com/Expensify/App/issues/35382#issuecomment-1916685740).

🎀 👀 🎀 C+ reviewed

**Comment by Yokomon** [comment] 2024-02-02 21:47
@allroundexperts  Yeah i agree with you 💪. But seems there is an auto-assignment from bot already 😂

**Comment by strepanier03** [comment] 2024-02-26 17:09
@dukenv0307 - I've paid you via Upwork and closed the contract. 

@allroundexperts - I'll check back in later today for the checklist and reg test steps, then move your payment forward as well. Otherwise, I'll check tomorrow morning if I can't.

**Comment by strepanier03** [comment] 2024-02-28 21:21
@allroundexperts - Can you complete the checklist answers [here](https://github.com/Expensify/App/issues/35382#issuecomment-1953270249) as soon as you can so we can close this out?

**Comment by allroundexperts** [comment] 2024-03-01 09:43
## Checklist
1. I wasn't able to pinpoint the exact PR which caused this. It seems like we never considered adding all skin colours for every emoji.
2. N/A
3. N/A
4. I think a regression test might not be strictly needed here since this is a really minor design thing with no impact on the app functionality. If we still decide to add it, then the steps given in the OP look good enough to me!

**Comment by strepanier03** [comment] 2024-03-01 18:41
Thank you @allroundexperts - I'll finish up and I agree with you regarding the reg test.

**Comment by strepanier03** [comment] 2024-03-01 18:42
### Payment summary

- [x] Contributor - @dukenv0307 - Paid $500 via Upwork
- [ ] C+ - @allroundexperts - Owed $500 via Manual Requests

@JmillsExpensify - Money request incoming from @allroundexperts for $500.

**Comment by strepanier03** [comment] 2024-03-01 18:43
@allroundexperts - Closing this out now but feel free to put in the request since the payment summary is above.

**Closed by strepanier03** 2024-03-01 18:43 UTC
Labels: External, Daily, Awaiting Payment, Bug
