### ISSUE TITLE
[LOW] [Splits] [$1000] Mweb-IOU-Previously selected currency is shown for an second in send money confirmation page.

### ISSUE THREAD

**Issue by kavimuru** [Expensify/App#35147] opened 2024-01-25 12:52 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:**  1.4.31-1
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** Applause internal team
**Slack conversation:**

## Action Performed:
1. Go to https://staging.new.expensify.com/
2. Tab fab---- send money
3. Enter an amount
4. Tap next
5. Select a contact
6. Tap on amount section
7. Change the currency
8. Tap save
9. Perform step 7 and step 8 repeatedly and note currency display in send money confirmation page

This issue also happens in the request flow:

1. Open the app
2. Go to FAB > Request money
3. Change currency to UAH
4. Close the app and re-open
5. Go to FAB > Request money
6. BUG: UAH is briefly shown before showing user's local currency

## Expected Result:
Previously selected currency must not be shown for an second in send money confirmation page.

## Actual Result:
Previously selected currency is shown for an second in send money confirmation page.

## Workaround:
Can the user still use Expensify without this being fixed? Have you informed them of the workaround?

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [x] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [ ] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

https://github.com/Expensify/App/assets/43996225/33fab953-9a28-433e-9d26-d3cf5bcaeb4b

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01a75f53fa7369a183</li>
        <li>Upwork Job ID: 1750501967791529984</li>
        <li>Last Price Increase: 2024-03-07</li>
    </ul>
</details>

**Comment by JordanLevy19** [comment] 2024-01-26 12:50
**Proposal**

**Please re-state the problem that we are trying to solve in this issue.**

When clicking on the currency icon to change the currency, and after selecting the new currency, there's a flickering or delay with the currency symbol switching between the old currency and the newly selected currency within a 2-second interval. This seems to suggest that there is an issue with the state management of the currency selection. 

**What is the root cause of that problem?**

The issue may stem from a combination of asynchronous state updates and the React rendering cycle, which can momentarily display outdated content

Delayed Currency Update:

In NewRequestAmountPage.js, the currency is determined and then passed to MoneyRequestAmountForm. If there is any delay or asynchronous operation in updating this prop, the child component could render with outdated currency information initially and then update once the new currency prop is received.

`const currency = CurrencyUtils.isValidCurrencyCode(currentCurrency) ? currentCurrency : iou.currency;
`

State Management in Form:

The MoneyRequestAmountForm component has a complex state management mechanism that includes multiple useState and useEffect hooks, which could lead to a lag when updating the currency symbol.

```
useEffect(() => {
    if (!currency || !_.isNumber(amount)) {
        return;
    }
    initializeAmount(amount);
}, [selectedTab, amount]);

```

**What changes do you think we should make in order to solve the problem?**

Optimize State Updates in MoneyRequestAmountForm:

Ensure that the state updates dependent on the currency prop are synchronized. Use the useReducer hook to manage the state more predictably, which could help prevent the flickering caused by multiple useState and useEffect updates.

Stabilize Currency Symbol Updates:

Modify the TextInputWithCurrencySymbol component to handle currency changes more gracefully. This could involve implementing a loading state that shows a spinner or a placeholder until the currency symbol is confirmed to be updated to prevent showing the wrong symbol even momentarily.

Review Navigation Flow:

In NewRequestAmountPage, ensure that navigation and state updates related to currency selection are completed before rendering the MoneyRequestAmountForm.

**Comment by MitchExpensify** [comment] 2024-01-28 02:56
I don't thin this fits into any wave or VIP right now

**Comment by situchan** [comment] 2024-01-28 13:07
@MitchExpensify I think this should be fixed as bad user experience. This also happens at the start of money request flow.
Please check this video: (clearly noticeable on android)


https://github.com/Expensify/App/assets/108292595/941df676-1b0f-4a53-941d-020a7c9ba352

**Comment by situchan** [comment] 2024-01-30 19:51
Thanks. We can simplify repro step like this:
1. Open the app
2. Go to FAB > Request money
3. Change currency to UAH
4. Close the app and re-open
5. Go to FAB > Request money
6. BUG: UAH is briefly shown before showing user's local currency

**Comment by MitchExpensify** [comment] 2024-01-31 02:54
Added that to the OP @situchan ! 

Let's hunt down some proposals here, what d'you think on the priority level @dylanexpensify ?

**Comment by MitchExpensify** [comment] 2024-02-06 20:52
@situchan what do you think about this proposal? https://github.com/Expensify/App/issues/35147#issuecomment-1912022099

**Comment by situchan** [comment] 2024-02-06 20:56
@JordanLevy19 can you please update proposal to fix https://github.com/Expensify/App/issues/35147#issuecomment-1917779272? And I am not convinced about your solutions. Please provide more details with permalink.

**Comment by JordanLevy19** [comment] 2024-02-07 21:17
Hey @situchan - more specific, updated proposal with a fix below! Thank You!



**Proposal**

**Please re-state the problem that we are trying to solve in this issue.**

Users experience a noticeable delay when changing the currency in the IOU request flow. Specifically, after selecting a new currency from the IOURequestStepCurrency and returning to the MoneyRequestAmountForm, the currency symbol updates, but not instantly. Instead, there's a delay where the old currency symbol is visible before it switches to the new one. 

**What is the root cause of that problem?**

The way the currency symbol's update is handled within the state management and corresponding logic. When a user selects a new currency, the component responsible for displaying the currency symbol - BaseTextInputWithCurrencySymbol - does not immediately respond to the state change. Instead, it waits for the next rendering cycle to receive the updated currency prop and then displays the new symbol. 

**What changes do you think we should make in order to solve the problem?**

Direct modifications to the BaseTextInputWithCurrencySymbol.js 

**State Management for Currency Symbol**

We introduce a localized state within the BaseTextInputWithCurrencySymbol component to manage the currency symbol. The state is directly tied to the selectedCurrencyCode prop to ensure immediate updates.
Upon the selection of a new currency, this state is updated to reflect the change, triggering a re-render of the currency symbol without waiting for the parent component's state to refresh.

**UseEffect Hook for Immediate Updates**

We leverage the useEffect hook within BaseTextInputWithCurrencySymbol to listen for changes to the selectedCurrencyCode prop. When a change is detected, the localized currency symbol state is updated, which in turn updates the UI instantly.


**Code**

function BaseTextInputWithCurrencySymbol(props) {
    const {fromLocaleDigit} = useLocalize();
    const styles = useThemeStyles();

    // State to hold the dynamically updated currency symbol
    const [localizedCurrencySymbol, setLocalizedCurrencySymbol] = useState(CurrencyUtils.getLocalizedCurrencySymbol(props.selectedCurrencyCode));

    // Effect to update the currency symbol when the selected currency code changes
    useEffect(() => {
        setLocalizedCurrencySymbol(CurrencyUtils.getLocalizedCurrencySymbol(props.selectedCurrencyCode));
    }, [props.selectedCurrencyCode]);
    ...
}


Permalinks below:

**IOURequestStepAmount.js**
App/src/pages/iou/request/step/IOURequestStepAmount.js

**MoneyRequestAmountForm.js**
App/src/pages/iou/steps/MoneyRequestAmountForm.js

**BaseTextInputWithCurrencySymbol.js**
App/src/components/TextInputWithCurrencySymbol/BaseTextInputWithCurrencySymbol.js

**Comment by situchan** [comment] 2024-02-08 15:36
Thanks. I will provide feedback on Monday

**Comment by situchan** [comment] 2024-02-12 16:09
> The way the currency symbol's update is handled within the state management and corresponding logic. When a user selects a new currency, the component responsible for displaying the currency symbol - BaseTextInputWithCurrencySymbol - does not immediately respond to the state change. Instead, it waits for the next rendering cycle to receive the updated currency prop and then displays the new symbol.

@JordanLevy19  can you please explain your root cause in detail combined with permalink?

**Comment by JordanLevy19** [comment] 2024-02-12 22:54
@situchan - yes please see below:

The cause of the delay when users change the currency in the IOU request flow is related to how the BaseTextInputWithCurrencySymbol component manages updates to its currency symbol upon receiving new selectedCurrencyCode props. When a user selects a new currency from IOURequestStepCurrency and returns to MoneyRequestAmountForm, the expectation is for the currency symbol within BaseTextInputWithCurrencySymbol to update immediately to reflect the user's choice. However, due to the component's reliance on the prop update, there's a noticeable delay. 

Currently, BaseTextInputWithCurrencySymbol uses the selectedCurrencyCode prop to determine which currency symbol to display:

const currencySymbol = CurrencyUtils.getLocalizedCurrencySymbol(props.selectedCurrencyCode);

The above method doesn't facilitate an update of the currency symbol when there's a change in the selectedCurrencyCode prop, leading to the delay.

Permalink:

BaseTextInputWithCurrencySymbol.js
[App/src/components/TextInputWithCurrencySymbol/BaseTextInputWithCurrencySymbol.js](https://github.com/Expensify/App/blob/main/src/components/TextInputWithCurrencySymbol/BaseTextInputWithCurrencySymbol.js)

**Comment by mvtglobally** [comment] 2024-02-13 04:57
Issue not reproducible during KI retests. (First week)

**Comment by situchan** [comment] 2024-02-15 19:04
I still think the root cause is not accurate

**Comment by situchan** [comment] 2024-02-19 15:33
Looking for proposals

**Comment by MitchExpensify** [comment] 2024-02-23 21:14
Looking at this again, still considered MEDIUM @dylanexpensify ?

**Comment by MitchExpensify** [comment] 2024-02-27 00:16
Friendly bump here @dylanexpensify

**Comment by dylanexpensify** [comment] 2024-02-27 10:44
replied via dm!

**Comment by MitchExpensify** [comment] 2024-02-27 16:46
@cristipaval or perhaps @neil-marcellini seeing as you are close to this wave, would either of you be able to take this on? I'm considering doubling to entice more proposals

**Comment by MitchExpensify** [comment] 2024-03-05 05:40
Gonna hold on making any moves on this (e.g. doubling) until I see how it falls into the new quarterly release plan

**Comment by trjExpensify** [comment] 2024-03-05 19:31
Send money is a IOU feature, so I haven't moved this to #wave-collect, but rather #vip-split

**Comment by jeremy-croff** [comment] 2024-03-07 04:05
> Thanks. We can simplify repro step like this:
> 
> 1. Open the app
> 2. Go to FAB > Request money
> 3. Change currency to UAH
> 4. Close the app and re-open
> 5. Go to FAB > Request money
> 6. BUG: UAH is briefly shown before showing user's local currency

I cannot reproduce it anymore with these steps.

**Comment by shahinyan11** [comment] 2024-03-07 06:06
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
Mweb-IOU-Previously selected currency is shown for an second in send money confirmation page.
### What is the root cause of that problem?
[Here](https://github.com/Expensify/App/blob/ffa731a28a2d1402148eef54e51d86fbb64321fe/src/pages/iou/steps/NewRequestAmountPage.js#L134C1-L139C10) we update IOU currency in Onyx data then navigate to `MoneyRequestConfirmPage`. Moving between screens is faster than updating Onyx data and `MoneyRequestConfirmPage` re-rendering
### What changes do you think we should make in order to solve the problem?
1. Add ability to send currency as a route param [here](https://github.com/Expensify/App/blob/ffa731a28a2d1402148eef54e51d86fbb64321fe/src/ROUTES.ts#L295C9-L295C106).  As done for the lower route ( `MONEY_REQUEST_CURRENCY` ) 
2. Send currency code as route params [here](https://github.com/Expensify/App/blob/ffa731a28a2d1402148eef54e51d86fbb64321fe/src/pages/iou/steps/NewRequestAmountPage.js#L137C13-L137C94)
```
Navigation.navigate(ROUTES.MONEY_REQUEST_CONFIRMATION.getRoute(iouType, reportID, currency));
```
3. Use `currency` from `route.params` instead `props.iou.currency` everywhere  in `MoneyRequestConfirmPage` component  .  But using only [here](https://github.com/Expensify/App/blob/ffa731a28a2d1402148eef54e51d86fbb64321fe/src/pages/iou/steps/MoneyRequestConfirmPage.js#L396C42-L396C60)  also enough to fix problem
### What alternative solutions did you explore? (Optional)

**Comment by shahinyan11** [comment] 2024-03-07 06:57
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
Mweb-IOU-Previously selected currency is shown for an second in send money confirmation page.
### What is the root cause of that problem?
[Here](https://github.com/Expensify/App/blob/ffa731a28a2d1402148eef54e51d86fbb64321fe/src/pages/iou/steps/NewRequestAmountPage.js#L134C1-L139C10) we update IOU currency in Onyx data then navigate to `MoneyRequestConfirmPage`. Moving between screens is faster than updating Onyx data and `MoneyRequestConfirmPage` re-rendering
### What changes do you think we should make in order to solve the problem?
1. Add ability to send `currency` as a route param [here](https://github.com/Expensify/App/blob/ffa731a28a2d1402148eef54e51d86fbb64321fe/src/ROUTES.ts#L295C9-L295C106).  As done for the lower route ( `MONEY_REQUEST_CURRENCY` ) 
2. Send `currency` as route params [here](https://github.com/Expensify/App/blob/ffa731a28a2d1402148eef54e51d86fbb64321fe/src/pages/iou/steps/NewRequestAmountPage.js#L137C13-L137C94)
```
Navigation.navigate(ROUTES.MONEY_REQUEST_CONFIRMATION.getRoute(iouType, reportID, currency));
```
3. Use `currency` from `route.params` instead `props.iou.currency` everywhere  in `MoneyRequestConfirmPage` component. But using only [here](https://github.com/Expensify/App/blob/ffa731a28a2d1402148eef54e51d86fbb64321fe/src/pages/iou/steps/MoneyRequestConfirmPage.js#L396C42-L396C60)  also enough to fix problem
### What alternative solutions did you explore? (Optional)
1. Add `CONST.NAVIGATION.TYPE.FORCED_UP` as the second parameter for [this](https://github.com/Expensify/App/blob/ffa731a28a2d1402148eef54e51d86fbb64321fe/src/components/MoneyRequestConfirmationList.js#L660) call
```
Navigation.navigate(ROUTES.MONEY_REQUEST_AMOUNT.getRoute(props.iouType, props.reportID), CONST.NAVIGATION.TYPE.FORCED_UP);
```
2. Change the `.goBack` call to `.navigate` with `CONST.NAVIGATION.TYPE.FORCED_UP` as the second parameter [here](https://github.com/Expensify/App/blob/ffa731a28a2d1402148eef54e51d86fbb64321fe/src/pages/iou/steps/NewRequestAmountPage.js#L137C13-L137C94)
```
Navigation.navigate(ROUTES.MONEY_REQUEST_CONFIRMATION.getRoute(iouType, reportID), CONST.NAVIGATION.TYPE.FORCED_UP);
```

**Comment by shahinyan11** [comment] 2024-03-07 12:16
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
Mweb-IOU-Previously selected currency is shown for an second in send money confirmation page.
### What is the root cause of that problem?
[Here](https://github.com/Expensify/App/blob/ffa731a28a2d1402148eef54e51d86fbb64321fe/src/pages/iou/steps/NewRequestAmountPage.js#L134C1-L139C10) we update IOU currency in Onyx data then navigate to `MoneyRequestConfirmPage`. Moving between screens is faster than updating Onyx data and `MoneyRequestConfirmPage` re-rendering
### What changes do you think we should make in order to solve the problem?
1. Add ability to send `currency` as a route param [here](https://github.com/Expensify/App/blob/ffa731a28a2d1402148eef54e51d86fbb64321fe/src/ROUTES.ts#L295C9-L295C106).  As done for the lower route ( `MONEY_REQUEST_CURRENCY` ) 
2. Send `currency` as route params [here](https://github.com/Expensify/App/blob/ffa731a28a2d1402148eef54e51d86fbb64321fe/src/pages/iou/steps/NewRequestAmountPage.js#L137C13-L137C94)
```
Navigation.navigate(ROUTES.MONEY_REQUEST_CONFIRMATION.getRoute(iouType, reportID, currency));
```
3. Use `currency` from `route.params` instead `props.iou.currency` everywhere  in `MoneyRequestConfirmPage` component. But using only [here](https://github.com/Expensify/App/blob/ffa731a28a2d1402148eef54e51d86fbb64321fe/src/pages/iou/steps/MoneyRequestConfirmPage.js#L396C42-L396C60)  also enough to fix problem
### What alternative solutions did you explore? (Optional)
We can remove the previous screen ( in this it is `MoneyRequestConfirmPage` ) from the navigation stack to force it to recreate which will help us avoid displaying the old UI. 
1. Add  new `shouldRecreate` parameter for [goBack](https://github.com/Expensify/App/blob/79d6cdafe77879a2aa3bc01d62b5a6a3ac105149/src/libs/Navigation/Navigation.ts#L185C1-L185C96) function and add below code [here](https://github.com/Expensify/App/blob/79d6cdafe77879a2aa3bc01d62b5a6a3ac105149/src/libs/Navigation/Navigation.ts#L189).
```
    if(shouldRecreate){
        navigationRef.current?.dispatch(StackActions.pop(2));
        navigate(fallbackRoute);
        return;
    }
```
2. Change [this](https://github.com/Expensify/App/blob/ffa731a28a2d1402148eef54e51d86fbb64321fe/src/pages/iou/steps/NewRequestAmountPage.js#L137C13-L137C94) line with below code
```
Navigation.goBack(ROUTES.MONEY_REQUEST_CONFIRMATION.getRoute(iouType, reportID), false, false, true);
```

**Comment by MitchExpensify** [comment] 2024-03-08 19:42
@shahinyan11 were you able to reproduce this on Android's latest version?

**Comment by MitchExpensify** [comment] 2024-03-10 22:01
Thanks!

@situchan - How does @shahinyan11 's proposal look like to you?

**Comment by jeremy-croff** [comment] 2024-03-11 02:35
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
Sometimes, the previous currency is shown for a brief moment before it updates between the edit amount screen and the confirmation screen when sending an IOU.

### What is the root cause of that problem?
We see on slower devices, such as mobile or on a slowed-down browser with throttling, that this is a race condition between the rerendering of the component that receives the new currency prop and the animation of the modal stack navigator. This is because, on the edit amount screen, we save the currency at the same time we navigate back. 

note: this is virtually unreproducible on faster laptops because the speed at which it can set the onyx variable and receive the new prop is faster than the animation.

### What changes do you think we should make in order to solve the problem?
There are a few ways we can facilitate passing back the selected currency context to the previous screen so that there's no delay. Either through a callback that set the parent state or directly passing the value as a param and using the param.

I choose the param route and would implement it specifically as the following:

1. From the Amount edit screen, we update Navigation.goBack to Navigation.navigate for the confirmation screen [here](https://github.com/Expensify/App/blob/77375e86525257fcd7ccd9f813f9c6dc7d125f4b/src/pages/iou/steps/NewRequestAmountPage.js#L116) so that we can pass params.
2. Then, we could directly pass the updated currency as a route parameter. (We  need to update the ROUTES.ts as well with the new param)
3. We would now add the code to listen to query parameters on the confirmation screen. And  we want to add some default logic:
` const routeCurrency = lodashGet(route, 'params.currency', '');`
 This is how we can now retrieve the new currency we receive as an optional param.
 
` const currency = CurrencyUtils.isValidCurrencyCode(routeCurrency) ? routeCurrency : iou.currency `
 
This step validates the route param so that users cannot mess it up accidentally. Otherwise, it falls back to the IOU reports currency from Onyx so that all existing flows work as expected.


### What alternative solutions did you explore? (Optional)
We can also pass a callback that updates the parent state in the confirm screen and triggers it from the amount screen when they save. This avoids route params altogether, but I preferred following existing patterns more.

**Comment by situchan** [comment] 2024-03-15 20:59
Expecting update early next week

**Comment by situchan** [comment] 2024-03-18 21:18
Not overdue

**Comment by MitchExpensify** [comment] 2024-03-19 03:30
@situchan We really need an update here after this amount of time. Can you please provide one in the next 24 hours? Otherwise I'll need to reassign to another C+

**Comment by situchan** [comment] 2024-03-19 05:14
The 2nd issue I reported [here](https://github.com/Expensify/App/issues/35147#issuecomment-1917779272) was fixed in https://github.com/Expensify/App/pull/36845.

I am not able to reproduce 1st issue because of loading:


https://github.com/Expensify/App/assets/108292595/137ee4cd-19ab-40d9-b6b6-8e58c76706e0


@shahinyan11 @jeremy-croff can you please confirm?

**Comment by shahinyan11** [comment] 2024-03-19 07:47
@situchan Yes. This is no longer reproducible

**Comment by situchan** [comment] 2024-03-19 08:05
@MitchExpensify we can close this

**Closed** 2024-03-20 01:31 UTC
Labels: Engineering, Daily, Internal, Bug
