### ISSUE TITLE
[HOLD for payment 2022-12-20] Chat - The bold chat is hard to see in dark mode

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#13202] opened 2022-11-30 18:14 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Go to URL https://staging.new.expensify.com/
2. Log in with any account (account A)
3. Log in in other device with other account (account B)
4. Verify that account A go out of the conversation with account B
5. Send a message to account A from account B

## Expected Result:
The bold chat is not hard to see in dark mode

## Actual Result:
The bold chat is hard to see in dark mode

## Workaround:
Unknown

## Platform:

Where is this issue occurring?

- Web
- iOS
- Android
- Desktop App
- Mobile Web

**Version Number:** 1.2.34.0

**Reproducible in staging?:** Yes

**Reproducible in production?:** Yes

**Email or phone of affected tester (no customers):** 

**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Notes/Photos/Videos:** Any additional supporting documentation

https://user-images.githubusercontent.com/93399543/204876171-167071e4-84c2-4927-a348-af83c36fe8b9.mp4

**Expensify/Expensify Issue URL:** 

**Issue reported by:** Applause - Internal Team

**Slack conversation:** 

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~013a926a86043b84c4</li>
        <li>Upwork Job ID: 1606453248846229504</li>
        <li>Last Price Increase: 2022-12-24</li>
    </ul>
</details>

**Comment by sakluger** [comment] 2022-11-30 19:34
I agree! I'm labeling with design since I think this is more of a design thing rather than a bug. @shawnborton what are your thoughts on this one?

**Comment by shawnborton** [comment] 2022-11-30 19:37
Yeah I don't think this is a bug... it would just be a design optimization

**Comment by rafecolton** [comment] 2022-11-30 21:30
Came here to say I experience this as well!

**Comment by JmillsExpensify** [comment] 2022-11-30 23:23
Definitely polish. That said, this has come up a bunch of times so I think we should pursue a solution.

**Comment by srikarparsi** [comment] 2022-12-01 04:59
sounds good, @shawnborton will you prefer taking this one or should I stay on to implement the color changes?

**Comment by shawnborton** [comment] 2022-12-01 14:57
I'll take this one from a design/mockup standpoint, but you are more than welcome to be the one to implement any changes we might settle on!

**Comment by srikarparsi** [comment] 2022-12-02 22:34
cool thanks shawn! I'll stay on the issue in that case :)

**Comment by sakluger** [comment] 2022-12-02 23:42
Okay I've removed the Bug label, not sure if any others should be added. @shawnborton feel free to update the priority label with whatever you feel is appropriate.

**Comment by shawnborton** [comment] 2022-12-03 00:33
Posted an idea to [Slack here](https://expensify.slack.com/archives/C01GTK53T8Q/p1670027578022319)

<img width="1076" alt="image" src="https://user-images.githubusercontent.com/2319350/205413127-4259db3d-ddc6-4c26-b3a8-92f6a0641465.png">

**Comment by srikarparsi** [comment] 2022-12-05 18:28
pr in review

**Comment by sakluger** [comment] 2022-12-09 23:39
Forgot to label with Internal before.

**Comment by sakluger** [comment] 2022-12-19 18:20
No external reporters or contributors, so checking off the three checkboxes above.

**Comment by thesahindia** [comment] 2022-12-19 18:33
Hey @sakluger, can we reopen? [C+ review ](https://github.com/Expensify/App/pull/13331#pullrequestreview-1207111759) compensation is pending on this.

**Comment by thesahindia** [comment] 2022-12-22 16:51
Bump @sakluger

**Comment by JmillsExpensify** [comment] 2022-12-22 19:22
@sakluger Don't forget the C+ compensation.

**Comment by mallenexpensify** [comment] 2022-12-24 00:55
@thesahindia can you please accept the job and reply here once you have? 
https://www.upwork.com/jobs/~013a926a86043b84c4

**Comment by thesahindia** [comment] 2022-12-24 08:26
Accepted, thanks!

**Comment by mallenexpensify** [comment] 2022-12-27 00:06
Paid @thesahindia $1000 for PR review.  Closing cuz I'm not seeing a regression checklist that needs to be filled out

**Closed by mallenexpensify** 2022-12-27 00:06 UTC
Labels: Weekly, Internal, Design, Awaiting Payment
