### ISSUE TITLE
[HOLD for payment 2024-11-18] [HOLD for payment 2024-11-14] Android -Copilot-App crashes when adding a copilot

### ISSUE THREAD

**Issue by IuliiaHerets** [Expensify/App#52106] opened 2024-11-06 11:52 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** v9.0.58-0
**Reproducible in staging?:** Y
**Reproducible in production?:** N
**If this was caught on HybridApp, is this reproducible on New Expensify Standalone?:** Y
**Issue was found when executing this PR:** https://github.com/Expensify/App/pull/51588
**Issue reported by:** Applause Internal Team

## Action Performed:
1. Go to settings > security
2. Tap Add copilot
3. Enter the email address of any user

## Expected Result:
The loading icon is displayed for a few seconds and the user is found.
After selecting the user found, the flow can continue.

## Actual Result:
Infinite loading when entering the email address and a few seconds later the system message "Expensify isn't responding" is displayed.

## Workaround:
Unknown

## Platforms:

- [x] Android: Standalone
- [x] Android: HybridApp
- [ ] Android: mWeb Chrome
- [ ] iOS: Standalone
- [ ] iOS: HybridApp
- [ ] iOS: mWeb Safari
- [ ] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

https://github.com/user-attachments/assets/cad151b9-741e-4852-af70-d1f0b07ff569

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Issue Owner</summary>Current Issue Owner: @mjasikowski</details>

**Comment by IuliiaHerets** [comment] 2024-11-06 13:08
@mjasikowski @RachCHopkins App also crashed when we invited a new member to a workspace. 
Do we need to raise a new issue or it is the same root as this?

https://github.com/user-attachments/assets/3b50b985-20c3-472d-b8c5-ceb0b9ab6499

**Comment by mjasikowski** [comment] 2024-11-06 13:42
@IuliiaHerets the root cause is most likely the same and is currently being investigated, but please raise a new issue so we won't miss the new problem when testing for a fix

**Comment by mjasikowski** [comment] 2024-11-06 14:11
This is investigated and discussed [in Slack](https://expensify.enterprise.slack.com/archives/C02NK2DQWUX/p1730894208049459)

**Comment by kavimuru** [comment] 2024-11-06 18:40
Fixed 

Uploading 51588-No Repro.mp4…

**Comment by RachCHopkins** [comment] 2024-11-08 04:42
@mjasikowski who do I need to pay here?

**Comment by mjasikowski** [comment] 2024-11-08 06:12
@RachCHopkins This was fixed internally with the help of Applause as far as I see, so no one needs to be paid.

**Comment by RachCHopkins** [comment] 2024-11-10 23:14
Ok cool, in that case do we need to do the checklist @mjasikowski ?

**Comment by mjasikowski** [comment] 2024-11-12 08:10
@RachCHopkins This was a one-off related to other crashes, so we can skip the checklist here. I'll close this one.

**Closed by mjasikowski** 2024-11-12 08:10 UTC
Labels: Engineering, Weekly, Awaiting Payment, Bug
