### ISSUE TITLE
[$1000] Web - Messages in thread are lost when sending many messages

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#23887] opened 2023-07-30 19:04 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1.Open any chat
2. Chat a message
3. Go Reply in thread
4. Send many message (about > 40 messages or more), Observe that the thread does not display all the messages

## Expected Result:
 Thread show all message

## Actual Result:
Thread does not display all the messages

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [x] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 1.3.47-3
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/93399543/91492ede-3040-42da-a60e-65b260315d73

https://github.com/Expensify/App/assets/93399543/43d4d383-3e38-4b66-a838-4ea60f4ac1f9

![image (10)](https://github.com/Expensify/App/assets/93399543/cbe2e108-1c7c-4173-b4c9-183b8066bad1)

**Expensify/Expensify Issue URL:**
**Issue reported by:** @namhihi237
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1690613255443729

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~0154d84cddbf95e721</li>
        <li>Upwork Job ID: 1686824255957950464</li>
        <li>Last Price Increase: 2023-08-02</li>
    </ul>
</details>

**Comment by michaelhaxhiu** [comment] 2023-08-02 19:39
This bug seems legit but it may already be captured in another ongoing GH. I will ask a C+ to help me determine that aspect.

**Comment by Crystalian0322** [comment] 2023-08-03 05:56
How can I submit proposal

**Comment by Crystalian0322** [comment] 2023-08-03 06:01
Contributor details
Your Expensify account email: eugenii.97525.sch@outlook.com
Upwork Profile Link: https://www.upwork.com/freelancers/~01f76925f200af331f

**Comment by Crystalian0322** [comment] 2023-08-03 06:02
how can i write proposal?

**Comment by fahad-islam** [comment] 2023-08-03 10:48
Contributor details
Your Expensify account email: [fahadislam.dev@gmail.com](mailto:fahadislam.dev@gmail.com)
Upwork Profile Link: https://www.upwork.com/freelancers/~01b12bc7773753485d

**Comment by fahad-islam** [comment] 2023-08-03 10:51
Contributor details
Your Expensify account email: [fahadislam.dev@gmail.com](mailto:fahadislam.dev@gmail.com)
Upwork Profile Link: https://www.upwork.com/freelancers/~01b12bc7773753485d

**Comment by fahad-islam** [comment] 2023-08-03 10:52
Contributor details
Your Expensify account email: fahadislam.dev@gmail.com
Upwork Profile Link: https://www.upwork.com/freelancers/~01b12bc7773753485d

**Comment by fahad-islam** [comment] 2023-08-03 14:48
For me there is no such issue. But When I added new messages every-time application got hangs because I think so the state of application is very poorly managed.  

[Screen Recording](https://github.com/Expensify/App/assets/89579421/baeca3de-80e0-40fc-95c7-6f12f266e2ea)

If I am wrong, then please correct me!

**Comment by fahad-islam** [comment] 2023-08-04 07:36
@MelvinBot What's next step

**Comment by michaelhaxhiu** [comment] 2023-08-04 16:17
@fahad-islam please give 1-2 days for the assigned C+ member to review your proposal.

**Comment by michaelhaxhiu** [comment] 2023-08-04 16:19
Note: I'm preparing to go OOO for ~2 weeks and need a BZ buddy to watch over this in the meantime. 🙏

Next step: Please ensure that we push this forward and double price if no winning proposal in the next week (by 8/8).

Thanks in advance @stephanieelliott, I can take this back when I get back if it's not complete before then.

**Comment by stephanieelliott** [comment] 2023-08-07 17:14
Thanks @bernhardoj! Agree this is a dupe of https://github.com/Expensify/App/issues/15116 which was closed in favor of https://github.com/Expensify/App/issues/12054#issuecomment-1505811916

**Closed by stephanieelliott** 2023-08-07 17:14 UTC
Labels: External, Daily, Help Wanted, Overdue, Bug
