### ISSUE TITLE
[HOLD for payment 2024-12-03] [Search v1.2] - Unable to pay held expense in Search

### ISSUE THREAD

**Issue by IuliiaHerets** [Expensify/App#52377] opened 2024-11-12 11:29 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 9.0.60-0
**Reproducible in staging?:** Y
**Reproducible in production?:** N/A - new feature, doesn't exist in prod
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):** applausetester+kh011101@applause.expensifail.com
**Issue reported by:** Applause Internal Team

## Action Performed:
Precondition:
- User has paid expense in Search before.

1. Go to staging.new.expensify.com
2. [User A] Submit an expense to User B.
3. [User B] Go to transaction thread > Click report header.
4. [User B] Click Hold expense, enter reason and save it.
5. [User B] Go to Search.
6. [User B] Click Pay button for the held expense.

## Expected Result:
Confirmation modal will show when paying held expense in Search.

## Actual Result:
Confirmation modal does not show when paying held expense in Search. The pay button shows loading and then reverts to initial state.

## Workaround:
Unknown

## Platforms:

- [ ] Android: Standalone
- [ ] Android: HybridApp
- [x] Android: mWeb Chrome
- [ ] iOS: Standalone
- [ ] iOS: HybridApp
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

https://github.com/user-attachments/assets/d092259f-297a-476a-a51b-22dca2f03701
 
</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Issue Owner</summary>Current Issue Owner: @OfstadC</details>

**Comment by iwiznia** [comment] 2024-11-12 12:07
Feature was added in this PR https://github.com/Expensify/App/pull/51445

@IuliiaHerets was this issue open while testing that PR? If so, you should've noted that, so the assigned person does not need to go find it.

ccing @luacmartins because it's your PR, but looking into it now.

**Comment by iwiznia** [comment] 2024-11-12 12:12
I can't reproduce this... I see the RHP opening:
<img width="1512" alt="image" src="https://github.com/user-attachments/assets/81ee113a-12dd-498c-b20e-7cae49e32352">

**Comment by iwiznia** [comment] 2024-11-12 12:28
Yeah, still can't reproduce it, even in a new workspace... @IuliiaHerets can you retry? Is there any added context on the test you did that might be triggering this bug?

**Comment by luacmartins** [comment] 2024-11-12 15:46
I think the reason applause can reproduce is because for the pay action we only do a "one-click pay" if you have previously paid something in that workspace, which saves that payment method to `nvp_private_lastPaymentMethod`. Otherwise, we open the RHP.

**Comment by iwiznia** [comment] 2024-11-12 16:25
AHA! You are right!

**Comment by luacmartins** [comment] 2024-11-12 16:27
I'm still working on adding RBR to Search actions (see [this PR](https://github.com/Expensify/App/pull/52333)). I'll also discuss what the pattern for reports with held expenses should be and come back here.

**Comment by iwiznia** [comment] 2024-11-12 16:53
Must've entered [this if](https://github.com/Expensify/Auth/blob/b0d3aaf8222a0a59531eab1bcc067a8f94234a07/auth/command/PayMoneyRequestOnSearch.cpp#L111) but it is completely impossible to know what happened since the https requests are not linked to this one.
@lakchote I see you worked on this command, do you know what could be going on? Also, I think we should pass the requestID to the https request, so logs are all tied to the same requestID.
Going to try to find it by other data

**Comment by iwiznia** [comment] 2024-11-12 16:56
Could not find it. Tried [this](https://www.expensify.com/_devportal/tools/logSearch/#query=blob%3A%22PayMoneyRequest%22%20AND%20blob%3A%225844620916720344%22%20AND%20timestamp%3A%5B2024-11-12T00%3A00%20TO%202024-11-13T23%3A59%5D&index=_all) and don't see it [here](https://www.expensify.com/_devportal/tools/logSearch/#query=blob%3A%22PayMoneyRequest%22%20AND%20email%3A%22ionatan%40expensifail.com%22%20AND%20timestamp%3A%5B2024-11-12T00%3A00%20TO%202024-11-13T23%3A59%5D&index=_all) either.

@luacmartins @lakchote I think this should not block newDot deploy anyway since seems like the problem is in the backend, no?

**Comment by luacmartins** [comment] 2024-11-12 17:01
Yea, I don't think this is a blocker since the fix is in the backend. We're still working on sending correct Onyx updates from the backend (see [this comment](https://github.com/Expensify/Expensify/issues/386310#issuecomment-2455225838))

**Comment by iwiznia** [comment] 2024-11-12 17:06
if we are working on it on that other issue, should we close this one?

**Comment by iwiznia** [comment] 2024-11-12 17:07
Actually, even if we are, let's keep this one to improve debugability of this. Going to assign @lakchote for that since he added this code.

**Comment by IuliiaHerets** [comment] 2024-11-12 17:10
@iwiznia Issue was found by exploratory. Asked for retesting, I'll back to you soon with an answer

**Comment by iwiznia** [comment] 2024-11-12 17:18
Oh @IuliiaHerets, no need, we already know how to trigger the error.

**Comment by IuliiaHerets** [comment] 2024-11-12 17:41
Tester shared new steps if you need 

1. Go to [staging.new.expensify.com](http://staging.new.expensify.com/)
2. [User A] Submit an expense to User B.
3. [User B] Go to Search.
4. [User B] Click Pay next to the expense.
5. [User B] Click Pay elsewhere.
6. [User A] Submit an expense to User B.
7. [User B] Go to transaction thread > Click report header.
8. [User B] Click Hold expense, enter reason and save it.
9. [User B] Go to Search.
10. [User B] Click Pay button for the held expense. 

https://github.com/user-attachments/assets/441be320-375f-47d1-af88-8ddb58732d97

**Comment by luacmartins** [comment] 2024-12-03 17:38
Done!

**Closed by luacmartins** 2024-12-03 17:38 UTC
Labels: Engineering, Daily, Awaiting Payment, Bug
