### ISSUE TITLE
[CHECKLIST] [$250]  Tasks - Task stays on the previously assigned user after assignee has been changed

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#46782] opened 2024-08-03 21:48 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:**  9.0.16
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**If this was caught during regression testing, add the test name, ID and link from TestRail:** N/A
**Email or phone of affected tester (no customers):** biruknew45+22s9sj@gmail.com
**Issue reported by:** Applause - Internal Team

## Action Performed:
1. Go to [staging.new.expensify.com]
2. Go to any chat
3. Click on the plus icon in the compose box
4. Select "Assign Task."
5. Give it a title, then click "Next."
6. Add an assignee, then confirm the task
7. Open the task
8. Click on the assignee and reassign it to another person
9. Open the task and reassign it to another person again

## Expected Result:
When reassigning to the third person, the chat created when reassigning to the second person should be cleared or removed

## Actual Result:
When reassigning to the third person, the chat created for the second person assigned still exists/persists, and they can see it and take some actions

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details> 

https://github.com/user-attachments/assets/329bd8f0-766a-4afd-875e-7954a9b95bd6

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~0116c365af04938c86</li>
        <li>Upwork Job ID: 1821259987888071161</li>
        <li>Last Price Increase: 2024-08-14</li>
<li>Automatic offers: </li>
<ul>
<li>jjcoffee | Reviewer | 103541888</li>
<li>dominictb | Contributor | 103541890</li>
</ul></li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @garrettmknight</details>

**Comment by lanitochka17** [comment] 2024-08-03 21:48
@garrettmknight  FYI I haven't added the External label as I wasn't 100% sure about this issue. Please take a look and add the label if you agree it's a bug and can be handled by external contributors

**Comment by lanitochka17** [comment] 2024-08-03 21:48
We think that this bug might be related to #vip-vsp

**Comment by kpadmanabhan** [comment] 2024-08-04 12:49
@lanitochka17 : unable to reproduce this in staging. is there a separate setting that should be enabled in account settings?
i do not see the PM chat popping up with assignee. see screenshot below.
![image](https://github.com/user-attachments/assets/c5fe89ee-bdeb-4d5d-8db6-0c8f42e3e0d1)

**Comment by jjcoffee** [comment] 2024-08-08 09:12
The expected result is a bit unclear here, do we actually expect the created chat to be hidden/deleted? What's happening is a 1:1 DM is being created with the assigned user and the task shared there. Once re-assigned, the previously assigned user still has write access to the task report, which is why `canModifyTask` returns true here

**Comment by kpadmanabhan** [comment] 2024-08-08 13:14
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
With clarity of requirement from @jjcoffee previous task owner is shown ability to complete task, which is unexpected.

### What is the root cause of that problem?
Lack of clarity of requirement. 
BE allows user to save comments to previously assigned task owner. FE allows at the moment and should continue to do the same. However BE allows only current task owner to complete the task. FE should behave the same.

### What changes do you think we should make in order to solve the problem?
Complete task option to be shown ONLY to task owner and current assignee. If user is a previous owner of the task, complete task checkbox and "mark as complete" button should be hidden.
Visibility of task completion checkbox and button to be connected to task owner / assignee.

### What alternative solutions did you explore? (Optional)
N.A.

**Comment by garrettmknight** [comment] 2024-08-08 18:54
Thanks for checking out @jjcoffee - I think the expected behavior was that the chat for the second assignee is removed. That likely means that the assignee is removed from the task room if it's not shared in a chat they'd have access to normally; however, I'd agree that it's better to allow them access to that chat and block their ability to complete the task they're not assigned to.

**Comment by jjcoffee** [comment] 2024-08-12 14:51
@dominictb's [proposal](https://github.com/Expensify/App/issues/46782#issuecomment-2278963344) is something along the lines of what I was thinking, but just to check @garrettmknight are you able to confirm if this would be the expected behaviour. Essentially there would be two separate groups:

1. `canModifyTask` - users that can edit the description or title of the task only (current behaviour).
2. `canActionTask` - users that can actually change the status of the task (mark complete or incomplete), which currently would be the owner or assignee of the task (which I think matches current BE expectations).

**Comment by garrettmknight** [comment] 2024-08-13 17:28
Could we just disable `canModifyTask` when the assignee is changed? Would that still allow them to comment on the task, but not change the description, title, or complete the task? That feels like a really simple, clean solution if so.

**Comment by garrettmknight** [comment] 2024-08-14 19:34
Thanks @dominictb - In that case it does seem like we need a different function `canActionTask`. @jjcoffee let's move forward with the expected behavior you explained [here](https://github.com/Expensify/App/issues/46782#issuecomment-2284199034)

**Comment by jjcoffee** [comment] 2024-08-15 16:04
Thanks for confirming @garrettmknight! Let's move forward with @dominictb's [proposal](https://github.com/Expensify/App/issues/46782#issuecomment-2278963344) then, with a util function `canActionTask` (unless someone can come up with a neater name!).

:ribbon::eyes::ribbon: C+ reviewed

**Comment by bondydaa** [comment] 2024-08-15 17:44
I agree we should update this logic on the front end so assigning @dominictb but we should also then be checking these things in the backend which doesn't seem to be the case.

taking a look at the git history and tagging @rafecolton @puneetlath @thienlnam since I see you in there for the CompleteTask command `https://github.com/Expensify/Auth/blob/main/auth/command/CompleteTask.cpp`.

Do know more about how to better check in auth to prevent someone who isn't assigned or is the creator? I didn't look too closely at the code but can dive deeper if needed.

**Comment by puneetlath** [comment] 2024-08-15 17:49
Hmm, I'm not totally following. What does this have to do with completing a task? It sounds like the "problem" is that when a task is re-assigned by userA from userB to userC, there is still a reportAction in the userA/userB DM which links to the task. Is that right? 

If so, it doesn't really sound like a big deal and my vote would be to do nothing and just leave it as-is.

**Comment by jjcoffee** [comment] 2024-08-16 10:39
> there is still a reportAction in the userA/userB DM which links to the task. Is that right?

@puneetlath User B can also still action the task (mark complete/incomplete) on the FE, but BE throws an error in this case. I think the confusion is that in a room anyone can action the task (not just the task owner and assignee), and the same is true of sharing a task to a chat, so it's a bit unclear why we're not allowing it in this case.

**Comment by jjcoffee** [comment] 2024-08-16 10:41
Actually looking at this again the error is `Report no longer exists`, and it only happens for completing the task, not for reopening.

**Comment by puneetlath** [comment] 2024-08-20 21:07
I see. What do y'all think the ideal behavior is? Should they be able to complete it? Or should we be removing that report action in the DM? Or something else?

**Comment by garrettmknight** [comment] 2024-08-20 22:48
Given the choice between the two, I'd say that we should stop User B from completing it on the FE since they're no longer assigned.

**Comment by jjcoffee** [comment] 2024-08-21 07:53
I agree with @garrettmknight, but there's a slight hitch in that currently if a task is shared with someone (but not assigned to them) they are able to mark it complete/incomplete. If that's the correct behaviour, I'm not sure how feasible it is to target the specific case where the task has been assigned (which shares it in the 1:1 DM) and then unassigned. Maybe @dominictb has ideas? :smile:

**Comment by jjcoffee** [comment] 2024-08-21 08:03
@dominictb Your PR will change the current behaviour though, no? I think if you share a task with someone without assigning to them, with your changes they won't be able to action it.

**Comment by jjcoffee** [comment] 2024-08-21 14:29
@dominictb Sorry if I was unclear, but that's what I'm talking about. The current behaviour is that when you share a task with someone (without assigning it to them), they will be able to complete/incomplete the task. I'm not sure if that's an intentional behaviour but your PR will change this so they will no longer be able to complete/incomplete the task.

**Comment by jjcoffee** [comment] 2024-08-28 13:41
@garrettmknight Do you have any thoughts on [this](https://github.com/Expensify/App/issues/46782#issuecomment-2306496606)? Or do you know who to bring in to get a consensus on this so we can move forward with the PR?

**Comment by jjcoffee** [comment] 2024-09-04 14:21
@puneetlath @garrettmknight Do you guys have thoughts on what should happen in these [two cases](https://github.com/Expensify/App/issues/46782#issuecomment-2304250165)?

**Comment by garrettmknight** [comment] 2024-09-05 18:25
I'd agree that both cases should share the same behavior.

**Comment by jjcoffee** [comment] 2024-09-06 11:23
@garrettmknight Sweet, thanks for clearing that up! So we'll proceed with the PR under the assumption that only task assignees and the task owner can complete the task - anyone the task was shared with (who are not either of those) won't be able to complete/incomplete the task.

That means the PR is basically ready, just waiting for one small tweak from @dominictb.

**Comment by jjcoffee** [comment] 2024-09-13 08:14
@garrettmknight Could we get a new engineer assigned to review the PR as @bondydaa is OOO?

**Comment by bondydaa** [comment] 2024-09-16 20:15
merged that PR earlier, looks like it was included in the latest deploy to staging.

**Comment by bondydaa** [comment] 2024-09-20 15:12
looks like it was deploy to production https://github.com/Expensify/App/pull/47519#issuecomment-2356865572 but the automation must have failed

**Comment by jjcoffee** [comment] 2024-09-23 08:22
@garrettmknight This one should be due payment 2024-09-24.

**Comment by garrettmknight** [comment] 2024-09-23 16:32
**Payment Summary:**
- Contributor: @dominictb $250
- Reveiwer: @jjcoffee $250

**Comment by garrettmknight** [comment] 2024-09-24 14:32
@jjcoffee can you complete the checklist when you get a chance?

**Comment by jjcoffee** [comment] 2024-09-25 08:40
- The PR that introduced the bug has been identified. Link to the PR: https://github.com/Expensify/App/pull/23971/
- The offending PR has been commented on, pointing out the bug it caused and why, so the author and reviewers can learn from the mistake. Link to comment: https://github.com/Expensify/App/pull/23971/files#r1774811254
- A discussion in #expensify-bugs has been started about whether any other steps should be taken (e.g. updating the PR review checklist) in order to catch this type of bug sooner. Link to discussion: N/A - a fairly specific case that was missed
- Determine if we should create a regression test for this bug. **Yes**
- If we decide to create a [regression test](https://github.com/Expensify/App/blob/main/contributingGuides/REGRESSION_TEST_BEST_PRACTICES.md) for the bug, please propose the regression test steps to ensure the same bug will not reach production again.

**Regression Test Proposal**

1. Go to FAB -> Assign Task
2. Give the task a title and assign it to User A
3. Open the task, click on the assignee and reassign it to User B
4. [User A] Verify that you cannot mark the task as complete/incomplete

Do we agree 👍 or 👎

**Closed** 2024-10-01 12:33 UTC
Labels: External, Daily, Awaiting Payment, Bug
