### ISSUE TITLE
[$500] Web – Request Money - Duplicated chats do not appear in the LHN

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#28491] opened 2023-09-29 14:17 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Go to https://staging.new.expensify.com/
2. Log in with the same account in the main testing device and a secondary device
3. Disable the internet connection in the main testing device
4. In the secondary device Split a bill with 2 users, this should create a new group and 2 new 1:1 conversations
5. In the main testing device (should be offline) create the SAME split bill with the 2 users
6. Enable the internet connection in the main testing device. The split bill request will be sent and you will get an error in the main device only

## Expected Result:
Duplicated chats appear in the LHN

## Actual Result:
Duplicated chats do not appear in the LHN

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [x] Windows / Chrome
- [ ] MacOS / Desktop

**Version Number:** 1.3.75-0

**Reproducible in staging?:** Yes

**Reproducible in production?:** Yes

**If this was caught during regression testing, add the test name, ID and link from TestRail:**

**Email or phone of affected tester (no customers):**

**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/78819774/efdeb63e-f992-4aa7-8ff0-d7d124e058eb

**Expensify/Expensify Issue URL:**

**Issue reported by:** Applausec - Internal Team

**Slack conversation:**

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~0103fc103b68458f78</li>
        <li>Upwork Job ID: 1709188061816893440</li>
        <li>Last Price Increase: 2023-10-17</li>
    </ul>
</details>

**Comment by sophiepintoraetz** [comment] 2023-10-02 09:31
Checking the label logic [here](https://expensify.slack.com/archives/C9YU7BX5M/p1696239079473519) before confirming next step.

**Comment by sophiepintoraetz** [comment] 2023-10-05 10:17
@sonialiap - just need a hand with baby sitting this issue whilst I'm OOO - there are no proposals yet but I'll take it back on 17 Oct if it's still going then!

**Comment by MrMuzyk** [comment] 2023-10-16 13:24
@lanitochka17 

With help of my team member @roksanaz I was able to reproduce it once and so did she. It doesn't seem to happen everytime. However the error that we both recieved said - `Unexpected error creating this chat, please try again later. There is a previously existing chat between these users.` which seems to be reasonable behaviour.  Here is a response I got this one time.

```{
    "code": 666,
    "jsonCode": 666,
    "type": "Expensify\\Libs\\Error\\ExpError",
    "UUID": "61F4D57E-F025-4289-B7F0-483FA8EB820D",
    "message": "There is a previously existing chat between these users.",
    "title": "",
    "data": {
        "onyxData": [
            {
                "onyxMethod": "merge",
                "key": "report_8615329571914203",
                "value": {
                    "errorFields": {
                        "createChat": {
                            "1697460612565675": "There is a previously existing chat between these users."
                        }
                    }
                }
            },
            {
                "onyxMethod": "merge",
                "key": "report_8981857230926563",
                "value": {
                    "errorFields": {
                        "createChat": {
                            "1697460612565666": "There is a previously existing chat between these users."
                        }
                    }
                }
            },
            {
                "onyxMethod": "merge",
                "key": "report_3435898379201309",
                "value": {
                    "errorFields": {
                        "createChat": {
                            "1697460612565667": "There is a previously existing chat between these users."
                        }
                    }
                }
            }
        ]
    },
    "htmlMessage": "",
    "onyxData": [
        {
            "onyxMethod": "merge",
            "key": "report_8615329571914203",
            "value": {
                "errorFields": {
                    "createChat": {
                        "1697460612565675": "There is a previously existing chat between these users."
                    }
                }
            }
        },
        {
            "onyxMethod": "merge",
            "key": "report_8981857230926563",
            "value": {
                "errorFields": {
                    "createChat": {
                        "1697460612565666": "There is a previously existing chat between these users."
                    }
                }
            }
        },
        {
            "onyxMethod": "merge",
            "key": "report_3435898379201309",
            "value": {
                "errorFields": {
                    "createChat": {
                        "1697460612565667": "There is a previously existing chat between these users."
                    }
                }
            }
        }
    ],
    "requestID": "81706d1ae90dbf35-WAW"
}```

Given the BE response I'm not sure if behaviour described in this issue is a bug and expected behaviour is a valid one.
Expected behaviour in this issues is - `Duplicated chats appear in the LHN` where BE clearly states that you can't have duplicated chats.

**Comment by lanitochka17** [comment] 2023-10-16 14:02
@MrMuzyk Hello
Thank you for the clarification

**Comment by sonialiap** [comment] 2023-10-17 01:31
I'm OOO Oct 16-23 and we don't need two BZ on this issue, unassigning myself

**Comment by sophiepintoraetz** [comment] 2023-10-17 21:33
@MrMuzyk and @roksanaz, thank you for taking the time to break down your findings, I agree with you that the expected behaviour in the OP is incorrect. I'm closing this issue as not a bug.

**Closed by sophiepintoraetz** 2023-10-17 21:33 UTC
Labels: External, Daily, Help Wanted, Bug
