### ISSUE TITLE
[$250] Web - Unable to open public room when user is signed out

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#40917] opened 2024-04-24 16:27 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.65-0
**Reproducible in staging?:** Y
**Reproducible in production?:** N
**If this was caught during regression testing, add the test name, ID and link from TestRail:** https://expensify.testrail.io/index.php?/tests/view/4506639&group_by=cases:section_id&group_order=asc&group_id=229066
**Issue reported by:** Applause - Internal Team

## Action Performed:
1. Log out of New Expensify
2. Navigate to this link as anon user- https://staging.new.expensify.com/r/2652281908731856

## Expected Result:
Public room page should open

## Actual Result:
Unable to open public room when user is signed out. User can see infinite new expensify logo screen

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details> 

https://github.com/Expensify/App/assets/78819774/fbc73da1-d3aa-4610-9885-c7310cd017b6

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01af683507cc110cb3</li>
        <li>Upwork Job ID: 1783171334978912256</li>
        <li>Last Price Increase: 2024-04-24</li>
    </ul>
</details>

**Comment by lanitochka17** [comment] 2024-04-24 16:28
@stitesExpensify  I haven't added the External label as I wasn't 100% sure about this issue. Please take a look and add the label if you agree it's a bug and can be handled by external contributors

**Comment by mountiny** [comment] 2024-04-24 16:35
I cannot reproduce, it seems like it might be some backend issue rather than app issue
https://github.com/Expensify/App/assets/36083550/6fda6472-6666-4367-a6ce-0b762367e0ea

**Comment by sword1202** [comment] 2024-04-24 17:15
It's not issue only from Mac Chrome/Safari.
It happened on Android Phone (Chrome) and iPhone (Safari).
![screenshot-Google Pixel 8-14 0](https://github.com/Expensify/App/assets/23204263/54d92666-446a-4008-8bd8-aff3f9de31de)
![screenshot-iPhone 15-17 4](https://github.com/Expensify/App/assets/23204263/d406ef6b-b26e-4686-a86c-47abd0ef1513)

**Comment by proverbed** [comment] 2024-04-24 18:22
Yes, seems like you just need to wait very long.

**Comment by mountiny** [comment] 2024-04-24 18:57
Yep it seems like this is a backend issue where the [OpenReport command takes a long time](https://www.expensify.com/_devportal/tools/logSearch/#query=request_id:(%2287976cdcdcaa8fcc-BOS%22)+AND+timestamp:[2024-04-24T15:23:05.651Z+TO+2024-04-24T17:23:05.651Z]&index=logs_expensify-027998)

**Comment by mountiny** [comment] 2024-04-24 18:59
It seems like its related to [this discussion](https://expensify.slack.com/archives/C05CBC62HGW/p1713385008481159)

**Comment by stitesExpensify** [comment] 2024-05-02 01:42
Like Vit said it seems like this is due to general slowness with queries. Going to make this a weekly while that is worked on

**Comment by stitesExpensify** [comment] 2024-05-09 23:14
I'm about to be OOO for a while so I'm going to unassign. If this is still not resolved we can add the bug label which will assign the proper people!

**Comment by mallenexpensify** [comment] 2024-06-04 18:54
Added `Bug` to assign a BZ since no one was assigned here. Post in #fast-apis last week about this [here](https://expensify.slack.com/archives/C05CBC62HGW/p1717003695862809).

**Comment by JmillsExpensify** [comment] 2024-06-07 04:43
Not sure if we I went ahead and added this to vip-vsb since this issue was created in that initiative. We can re-file when/if fast-apis has a GH project.

**Comment by JmillsExpensify** [comment] 2024-06-12 03:59
Public rooms aren't a priority. Closing.

**Closed by JmillsExpensify** 2024-06-12 03:59 UTC
Labels: Engineering, Daily, Internal, Overdue, Bug

**Comment by mallenexpensify** [comment] 2024-06-14 21:41
fwiw, I was able to open the link in the OP without being signed in, on production and staging, Chrome
![Uploading image.png…]()

**Comment by mallenexpensify** [comment] 2024-06-14 21:41
fwiw, I was able to open the link in the OP without being signed in, on production and staging, Chrome
<img width="1064" alt="image" src="https://github.com/Expensify/App/assets/22508304/abd34eb4-f1be-431a-8da4-5902a3f88787">
