### ISSUE TITLE
[$500] Task - Long tap on task assignee crashes the app

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#30799] opened 2023-11-02 20:39 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:**1.3.95-0
**Reproducible in staging?:**Y
**Reproducible in production?:**Y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** Applause - Internal Team
**Slack conversation:**

## Action Performed:
1. Open the app
2. Navigate to any chat
3. Tap the "+" > Assign task
4. Assign a task to any user
5. Navigate to the 1:1 chat where the task was created
6. Long tap the task assignee

## Expected Result:
Profile details of the assignee are shown

## Actual Result:
The app crashes

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [ ] Android: mWeb Chrome
- [x] iOS: Native
- [ ] iOS: mWeb Safari
- [ ] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details> 

https://github.com/Expensify/App/assets/78819774/3f014d1f-b5bd-4528-95ed-b529c085372a

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~0198f55141115236ec</li>
        <li>Upwork Job ID: 1720178789185605632</li>
        <li>Last Price Increase: 2023-11-02</li>
    </ul>
</details>

**Comment by abzokhattab** [comment] 2023-11-02 22:20
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
on long press on the assigned user in the task preview, the app breaks 



### What is the root cause of that problem?

on long press on the mentioned user the app renders the `MentionUserRenderer` which is contained by a `ShowContextMenuContext` consumer .. this context consumer shows a  undefined `report` value is causing the app to break when accessing the `report.reportID` property

https://github.com/Expensify/App/blob/5d45f0f6c86e97d4ae58ac167b6c162a610b817c/src/components/HTMLEngineProvider/HTMLRenderers/MentionUserRenderer.js#L64-L68


### What changes do you think we should make in order to solve the problem?

we dont register a `ShowContextMenuContext.Provider` for the `TaskPreview` here 

https://github.com/Expensify/App/blob/5d45f0f6c86e97d4ae58ac167b6c162a610b817c/src/pages/home/report/ReportActionItem.js#L587-L590


so we need to wrap it with `ShowContextMenuContext.Provider` to pass the context to the `TaskPreview`

```
           <ShowContextMenuContext.Provider value={contextValue}>
                    <TaskPreview
                        taskReportID={props.action.originalMessage.taskReportID.toString()}
                        action={props.action}
                        isHovered={hovered}
                    />
                </ShowContextMenuContext.Provider>
```

**Comment by abzokhattab** [comment] 2023-11-03 00:09
isnt this related to this [issue](https://github.com/Expensify/App/pull/28840) ? is it reproducable in dev ?

**Comment by twisterdotcom** [comment] 2023-11-03 08:46
Closing as a dupe.

**Closed by twisterdotcom** 2023-11-03 08:46 UTC
Labels: External, Daily, Help Wanted, Bug
