### ISSUE TITLE
[HOLD for payment 2023-10-02] [HOLD for payment 2023-09-29] Pressing 'Next' while setting up 2FA does not redirect the user

### ISSUE THREAD

**Issue by thienlnam** [Expensify/App#27928] opened 2023-09-21 10:02 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. go to Settings > Security > Two-factor authentication
2. click on copy button and next button
3. enter code and click on Next button

## Expected Result:
Describe what you think should've happened
should show next screen / close the modal

## Actual Result:
Stays on the same page

## Workaround:
It sets the 2FA Code, but the user doesn't know because pressing 'Next' doesn't lead to another page

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [x] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** v1.3.72-8
**Reproducible in staging?:** Y
**Reproducible in production?:** N
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation
**Expensify/Expensify Issue URL:**
**Issue reported by:** @gadhiyamanan
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1695272344034999

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by BhuvaneshPatil** [comment] 2023-09-21 11:13
@thienlnam 

Can you check what value server is sending upon clicking verify for  `requiresTwoFactorAuth`.
<img width="660" alt="Screenshot 2023-09-21 at 4 42 30 PM" src="https://github.com/Expensify/App/assets/27822551/dd829fb3-68b6-4b1a-ba98-69f8967b6882">


Because we check here before redirecting user - 
https://github.com/Expensify/App/blob/b225b53829f8fa4ef5f7a75616469d1fc7d347b9/src/pages/settings/Security/TwoFactorAuth/Steps/VerifyStep.js#L37-L40

It should be false in order to redirect, but we are getting true

**Comment by situchan** [comment] 2023-09-21 11:43
I finally managed to find the offending PR - https://github.com/Expensify/App/pull/27230
Onyx version bump to 1.0.78 caused this regression.
Not repro on 1.0.77 but from 1.0.78
I also checked comments history in that PR.
QA team already [found](https://github.com/Expensify/App/pull/27230#issuecomment-1722245821) this during regression testing but it seems overlooked.

**Comment by thienlnam** [comment] 2023-09-21 11:52
Assigning Situ as the C+ for this issue as he has been investigating

**Comment by thienlnam** [comment] 2023-09-21 11:53
Assigning Situ as the C+ for this issue as he has been investigating

**Comment by techievivek** [comment] 2023-09-22 02:44
Looks like this is already being worked on. 🎉

**Comment by techievivek** [comment] 2023-10-06 14:42
Not overdue, waiting for the payment to be done here.

**Comment by techievivek** [comment] 2023-10-09 09:35
Gentle bump @muttmuure ^

**Comment by techievivek** [comment] 2023-10-11 12:13
Dmed Matt, we should be able to get this done soon. Sorry for the delay.

**Comment by situchan** [comment] 2023-10-11 12:37
BZ Checklist:
This regression came from big refactor in Onyx.
I believe this already exists in 2fa flow test cases but in case not exist:

**Regression Test Proposal**
1. Go to Settings > Security > Two-factor authentication
2. Click on Copy button and Next button
3. Enter code and click on Next button
4. Verify that it goes to the success screen

**Comment by muttmuure** [comment] 2023-10-11 12:53
@situchan and @gadhiyamanan invited to payment issue: https://www.upwork.com/jobs/~018f11146a6a0a35ab

**Comment by gadhiyamanan** [comment] 2023-10-11 12:55
@muttmuure applied,thanks!

**Comment by gadhiyamanan** [comment] 2023-10-11 16:34
Offer accepted!

**Comment by techievivek** [comment] 2023-10-16 10:48
Not overdue, waiting for the payment to be done here.

**Comment by techievivek** [comment] 2023-10-18 14:04
@muttmuure Are we done with the payment here? Shall we close the issue now?

**Comment by muttmuure** [comment] 2023-10-18 16:00
Paying them now

**Closed** 2023-10-18 16:01 UTC
Labels: Engineering, Daily, Awaiting Payment, Bug
