### ISSUE TITLE
[$500] The tricky emoji is displayed incorrectly in the expiration date and CVV section

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#31393] opened 2023-11-15 17:18 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.3.99.0
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** Applause - Internal Team
**Slack conversation:**
 
**Issue found when executing PR** https://github.com/Expensify/App/pull/31259

## Action Performed:
1. Go to staging.new.expensify.com
2. Log in with any account
3. Go to Setting - Wallet
4. Select Add bank account - Debit card
5. Input with emojis, especially tricky ones (e.g. 😶‍🌫️)

## Expected Result:
The tricky emoji is displayed correctly in the expiration date and CVV section or user cannot use emojis for two fields.

## Actual Result:
The tricky emoji is displayed incorrectly in the expiration date and CVV section

## Workaround:
Unknown 

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [x] Android: mWeb Chrome
- [x] iOS: Native
- [x] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

https://github.com/Expensify/App/assets/93399543/48c8df95-9bb2-4188-b578-58627fe4701b

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~0133f13d68bcdd3d58</li>
        <li>Upwork Job ID: 1724839362727112704</li>
        <li>Last Price Increase: 2023-11-15</li>
    </ul>
</details>

**Comment by yh-0218** [comment] 2023-11-15 18:26
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
The tricky emoji is displayed incorrectly in the expiration date and CVV section
### What is the root cause of that problem?
Because we have maxLength [here](https://github.com/Expensify/App/blob/cc5a272b3fdcdbe9ecfca056cc8bbd4a405a5b17/src/pages/settings/Wallet/AddDebitCardPage.js#L153) and [here](https://github.com/Expensify/App/blob/cc5a272b3fdcdbe9ecfca056cc8bbd4a405a5b17/src/pages/settings/Wallet/AddDebitCardPage.js#L162)
😶‍🌫️ -> length = 6
😶‍ -> length = 3
Max length = 4
### What changes do you think we should make in order to solve the problem?
Option 1:
We can skip this issue.

Option 2:
We can allow only number input.

Option 3:
We can increase maxLength

### What alternative solutions did you explore? (Optional)
<img width="361" alt="Screenshot 2023-11-15 at 8 24 48 PM" src="https://github.com/Expensify/App/assets/65789015/79bebef4-8048-4c82-a140-9c70f7a3a5dd">

**Comment by yakupafsin** [comment] 2023-11-15 20:40
## Proposal


### Please re-state the problem that we are trying to solve in this issue.
The issue revolves around the incorrect display of a specific emoji in the expiration date and CVV sections

### What is the root cause of that problem?
The root cause lies in the UTF-16 encoding used by JavaScript, treating emojis as multiple characters. This conflicts with the maxLength setting of the text input field, causing the incorrect rendering of emojis.

### What changes do you think we should make in order to solve the problem? 
To address this issue, we propose implementing the following changes in the onInputChange() function within [Form.js](https://github.com/Expensify/App/blob/1eb1f7259bb8e45c1aad3a040539ce367178090b/src/components/Form.js#L368C21-L368C34):

```javascript
// Check if the input has 'numeric' input mode
const isNumericInput = inputMode === CONST.INPUT_MODE.NUMERIC;
                    
// Only allow numeric values for inputs with 'numeric' input mode
const sanitizedValue = isNumericInput ? value.replace(CONST.REGEX.NUMERIC, '') : value;               
````

Subsequently, replace instances of the variable 'value' with 'sanitizedValue' in the [onInputChange](https://github.com/Expensify/App/blob/1eb1f7259bb8e45c1aad3a040539ce367178090b/src/components/Form.js#L368C21-L368C34) function. This modification ensures that users cannot input non-numeric characters in fields with the 'numeric' input mode, preventing current and potential issues.

By restricting input to numeric values in fields with 'numeric' input mode, we eliminate the problem at its source and mitigate future issues. This solution maintains the integrity of numeric inputs while addressing the root cause of the emoji display problem.

### What alternative solutions did you explore? (Optional)
While not ideal, an alternative solution is to remove the maxLength restriction in the text input fields. This would allow the proper rendering of emojis but may introduce issues related to input length. Consider this option cautiously, as it might impact the expected behavior of the form.


### Screen record

https://github.com/Expensify/App/assets/66640310/9667beb2-63b7-48bd-9756-e3f0a44bcb6f

**Comment by strepanier03** [comment] 2023-11-17 22:12
This was raised internally and while we understand the emoji isn't displayed correctly, this is also a field that will never have an emoji accepted in it. As such we're closing this out for now to focus on bugs with use cases that move use closer to our goals with New Expensify.

**Closed by strepanier03** 2023-11-17 22:12 UTC
Labels: External, Daily, Help Wanted, Bug
