### ISSUE TITLE
[HOLD for payment 2022-12-08] [$1000] Try to copy and paste an emoji from Slack into the chat editor shows an error

### ISSUE THREAD

**Issue by mvtglobally** [Expensify/App#9505] opened 2022-06-21 05:26 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Navigate to Slack 
2. Copy any emoji 
3. Paste Emoji in App 

## Expected Result:
User should be able to paste 

## Actual Result:
Try to copy and paste an emoji from Slack into the chat editor shows an error.

## Workaround:
unknown 

## Platform:

Where is this issue occurring?

- Web
- Desktop App

**Version Number:** 1.1.77-0
**Reproducible in staging?:** Y 
**Reproducible in production?:** Y 
**Email or phone of affected tester (no customers):** 
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation 

https://user-images.githubusercontent.com/43995119/174722628-f574bc16-1ec9-4c4e-817e-5d2678cfac7a.mp4

<img width="396" alt="Screen Shot 2022-06-09 at 9 40 51 AM" src="https://user-images.githubusercontent.com/43995119/174722651-fd63be19-d2ce-4c85-999f-b2c727c61a13.png">

**Expensify/Expensify Issue URL:**  
**Issue reported by:** @AndrewGable 
**Slack conversation:** https://expensify.slack.com/archives/C01GTK53T8Q/p1654789237813029

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by amyevans** [comment] 2022-06-22 20:47
When pasted content is parsed as HTML and contains an image tag, we attempt to fetch the image(s) in [this block](https://github.com/Expensify/App/blob/main/src/components/Composer/index.js#L272-L301).

The fetch fails due to our strict Content Security Policy:
![failure-ex-1](https://user-images.githubusercontent.com/7277067/175132282-766ebe3c-9253-4d24-8783-1fbba812c4a7.png)
 
Note that the subdomain isn't always the same:
![failure-ex-2](https://user-images.githubusercontent.com/7277067/175132458-c026f9e8-8240-4034-baa9-ef4892fade19.png)

So I think allow-listing `https://*.slack-edge.com` makes sense.

I'll get a PR up for this change.

Also, just for completeness since it confused me a bit while debugging - if the emoji is the _only_ thing being copy/pasted (via right click > copy image) then it can be pasted as a blob and does succeed:
![blob-success](https://user-images.githubusercontent.com/7277067/175132741-2ce84d05-89e8-45b0-b26e-f7c011714ea3.png)

**Comment by amyevans** [comment] 2022-06-24 21:14
@justinpersaud deployed the linked PR. Unfortunately in QAing it, I've now encountered a new error:
![Screen Shot 2022-06-24 at 5 12 07 PM](https://user-images.githubusercontent.com/7277067/175668098-2cff9333-d95e-4185-91a0-c3d6cc26f945.png)

Seems like we'd need to proxy the request through the back end to get around that, but I'm not sure if that's a good idea / worth pursuing. Any thoughts off the top of your head @AndrewGable?

**Comment by justinpersaud** [comment] 2022-06-24 22:21
Hm, I am just thinking about this more now after seeing your error and not thinking about it when I reviewed the original PR. Are we going about this the right way?

It seems like when we paste an emoji from Slack into NewDot, it is trying to paste the image URL instead of the emoji language or whatever you call it. I think that's the issue, no? I wouldn't expect that Slack would just freely let anyone use their emojis off their CDN (or would they?).

If you paste into a text editor instead, you see the actual emoji language like `:tent:` -- so perhaps we need to figure out why it's trying to paste the image as an attachment?

**Comment by amyevans** [comment] 2022-06-27 16:06
Yeah, I think that's a very reasonable suggestion. I compared against a few other platforms just to see what they do:
* **iMessage**: paste as text (`hi :aussie_peace_out: bye`)
* **WhatsApp**: paste as text (`hi :aussie_peace_out: bye`)
* A different workspace in **Slack**:
![Slack-paste-emoji](https://user-images.githubusercontent.com/7277067/175983092-67907985-6f46-4a74-b8d7-bd634e11115e.png)

It looks like there's some data attributes on the image I could access to use the stringified version of the emoji:

https://user-images.githubusercontent.com/7277067/175983301-b8933305-a366-4bc9-a138-7b1db4a6b316.mov

So that seems like a good path forward to me. Thanks @justinpersaud!

**Comment by parasharrajat** [comment] 2022-06-27 16:29
Good discussion overall. There are two things that need to be done to make emojis work from slack. 
1. Instead of taking slack emojis as images, allow pasting `:emoji:` in text form. 
2. Second would be adding new parsing rules to parse `:text:` as emoji. 

Both of these have been discussed before so I think it would be better to discuss this internally as well to decide the next step. Maybe it is already planned.

**Comment by amyevans** [comment] 2022-06-27 22:39
Thanks for chiming in here @parasharrajat! I spent some time looking at prior discussions in Slack and GitHub and you're right, this has already been discussed _a lot_ 😅. A non-exhaustive list:
* Bug `Emojis are pasted like images when copied and pasted from other apps (e.g Slack, Gmail)` closed as `Won't Do` ([GH](https://github.com/Expensify/App/issues/4888))
* Render Emoji when typed with emoji code ([GH](https://github.com/Expensify/App/issues/4324)) - Although the original post in the issue focuses specifically on converting things like `:)` to emoji, I think its scope has been expanded to include the `:colon_code:` implementation. Opened to external contributors recently, although not officially (no `Help Wanted` label)
* ([Slack thread](https://expensify.slack.com/archives/C01GTK53T8Q/p1643388153631749)) with some discussion

For this issue, I see a few options:
1. Close it and continue to `Do nothing` for now
2. Take care of what's labeled as `1` by @parasharrajat now, which would be relatively straightforward. Essentially:
* Prevent the fetch/growl for emoji images here: https://github.com/Expensify/App/blob/main/src/components/Composer/index.js#L272-L301
* Add a new regex rule here: https://github.com/Expensify/expensify-common/blob/main/lib/ExpensiMark.js#L194 that would find image tags and display their `alt`, or the contents of `data-stringify-emoji`, or something like that (exact implementation TBD)

Tagging in @stitesExpensify and @jboniface too since it seems like y'all have been heavily involved in the emoji feature development to date.

Also separately, I'll put up a revert PR for the CSR rule change since that's a non-factor here now.

**Comment by stitesExpensify** [comment] 2022-07-05 17:12
I think that we should:
1. Put this on hold
2. Add `Help Wanted` to the `:colon_code:` issue and get that completed
3. Come back to this once we have alternate codes (this is the proposed solution for `colon_code`s) and then add a regex rule like you suggested

Thoughts?

**Comment by stitesExpensify** [comment] 2022-07-06 21:04
Added the labels

**Comment by amyevans** [comment] 2022-09-20 12:39
The PR this is held on is in the final stages of review but not yet complete

**Comment by sonialiap** [comment] 2022-10-31 11:45
[Job added to Upwork](https://www.upwork.com/jobs/~01149844cc73b03490)

**Comment by sonialiap** [comment] 2022-11-03 11:14
@rushatgabhane have you had a chance to review this yet?

**Comment by sonialiap** [comment] 2022-11-10 12:42
Price increased

**Comment by pecanoro** [comment] 2022-11-21 21:50
I was actually looking into this and I think @0xmiroslav's proposal is fine. The problem is not their solution but the fact that our code only handles one pasted image at a time, which it's a different bug. @rushatgabhane If you try to paste two images, you will notice how only one gets sent and parsed. @0xmiroslav, do you want to go ahead with your solution? If not, I am taking over to speed things up a bit! 

However, something that I am going to check is if we have an issue to silence that CORS issue since basically images from Slack can't be pasted unless you copy them as images. It's not our problem, it's more like a Slack limitation because those images belong to a private workspace.

Going to assign myself to keep track of it, but removing the `Help Wanted` label because either @0xmiroslav will fix it or me.

**Comment by pecanoro** [comment] 2022-11-21 22:02
Awesome! don't forget to apply for the job on Upwork!

**Comment by pecanoro** [comment] 2022-11-22 16:51
@rushatgabhane Do you want to report that issue in Slack? Maybe it's worth solving it and opening another bug for it. I think this issue should just handle emojis 😄

**Comment by pecanoro** [comment] 2022-11-22 16:54
I am actually not totally sure if this a feature request, it feels kind of broken that we can only paste one emoji or one image at a time.

**Comment by pecanoro** [comment] 2022-11-22 16:55
@srikarparsi I am taking over if you don't mind since I got too involved now hahaha

**Comment by pecanoro** [comment] 2022-11-28 16:23
I was out for Thanksgiving break, I will review it today!

**Comment by mallenexpensify** [comment] 2022-12-26 17:17
Hired @rushatgabhane and @0xmiroslav , please accept and comment here once you have. 

For payment..... 
11/21 - @0xmiroslav hired
11/23 - PR reviewed by Rushat and Rocio was bumped to review
11/28 - PR merged. 

For all intents and purposes.... with Thanksgiving being 11/24.  I think the bonus is due here. so payment for both Rushat and Miroslav will be $1500 (Thanks for the reminder about the holiday @0xmiroslav )

**Comment by mallenexpensify** [comment] 2022-12-27 01:35
Paid @0xmiroslav and @rushatgabhane $1500 each. 
@sonialiap , please complete the regression test steps above, I'll try to help this week if I have time

**Comment by pecanoro** [comment] 2023-01-18 18:32
@sonialiap Bump on the above!

**Comment by mallenexpensify** [comment] 2023-01-19 02:28
Thanks @pecanoro , I think the issue is that the `Reviewing` label is keeping issues from going `Overdue` and BZ aren't being alerted they need attention.  Removed and bumped back to daily.  Instructions for regression test steps are here @sonialiap https://stackoverflow.com/c/expensify/questions/14574

**Comment by sonialiap** [comment] 2023-01-20 01:26
My checklist
- [ ] A [regression test](https://expensify.testrail.io/index.php?/dashboard) has been added or updated so that the same bug will not reach production again. Link to the updated test here:
- [ ] The PR that introduced the bug has been identified. Link to the PR:
- [ ] The offending PR has been commented on, pointing out the bug it caused and why, so the author and reviewers can learn from the mistake. Link to comment:
- [ ] A discussion in #contributor-plus has been started about whether any other steps should be taken (e.g. updating the PR review checklist) in order to catch this type of bug sooner. Link to discussion:
- [ ] Payment has been made to the issue reporter (if applicable)
- [ ] Payment has been made to the contributor that fixed the issue (if applicable)
- [ ] Payment has been made to the contributor+ that helped on the issue (if applicable)

**Comment by sonialiap** [comment] 2023-01-20 01:26
Regression test [proposal posted in slack](https://expensify.slack.com/archives/C01SKUP7QR0/p1674177978065129)

**Comment by sonialiap** [comment] 2023-01-25 08:33
Sorry, OOO for some family stuff. Will be back Thursday. Regression test [proposal](https://expensify.slack.com/archives/C01SKUP7QR0/p1674177978065129) has been approved

**Comment by sonialiap** [comment] 2023-01-31 19:08
GH issue to add regression test is [created](https://github.com/Expensify/Expensify/issues/259214)

**Comment by sonialiap** [comment] 2023-01-31 19:12
@rushatgabhane could you please help me identify the PR that caused the bug here?

**Comment by pecanoro** [comment] 2023-01-31 19:18
It has never worked, so not a regression per se, but I think we can link the original PR that introduced image parsing.

**Comment by sonialiap** [comment] 2023-02-01 19:09
Sounds good to me. Is this it - [link](https://github.com/Expensify/Cloudflare-Workers/commit/01e8132d314b9922b8e2fd2bf48fc5ff847aa3a4)?

**Comment by pecanoro** [comment] 2023-02-01 21:48
@sonialiap This PR https://github.com/Expensify/App/pull/4009

**Comment by sonialiap** [comment] 2023-02-02 01:05
Thanks!

**Closed** 2023-02-02 01:10 UTC
Labels: External, Engineering, Daily, Awaiting Payment, Bug

**Comment by pecanoro** [comment] 2023-02-02 15:34
We didn't say this was a regression, we already mentioned in previous comments it never worked, we just want to keep track of when we started parsing HTML as the feature was introduced.

**Comment by pecanoro** [comment] 2023-02-02 16:48
I updated the check-list so it's clear it wasn't a regression.
