### ISSUE TITLE
[Workspace Feeds] [$250] Close account - Can't close account if Expensify card once was enabled and disabled

### ISSUE THREAD

**Issue by IuliiaHerets** [Expensify/App#49020] opened 2024-09-11 19:06 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** v9.0.32-3
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**Issue reported by:** Applause Internal Team

## Action Performed:
Precondition: sign in with a new expensifail account. Add a new workspace.

1. Go to workspace > More features
2. Enable Expensify card
3. Disable expensify card
4. Go to Account settings > Security
5. Close account

## Expected Result:
Account is closed. User is logged out from application.

## Actual Result:
Account is not closed. There is an alert 'You are the only admin on a domain. Please assign another admin or delete this domain before you try again'.

NOTE: even after workspace deletion there is impossible to close account.

## Workaround:
Unknown

## Platforms:

- [x] Android: Native
- [x] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

https://github.com/user-attachments/assets/8dd5278a-d839-429a-a14c-43e4ddc5ccf2

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~021836811647509168004</li>
        <li>Upwork Job ID: 1836811647509168004</li>
        <li>Last Price Increase: 2024-10-03</li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @stitesExpensify</details>

**Comment by IuliiaHerets** [comment] 2024-09-11 19:06
@strepanier03  FYI I haven't added the External label as I wasn't 100% sure about this issue. Please take a look and add the label if you agree it's a bug and can be handled by external contributors

**Comment by strepanier03** [comment] 2024-09-13 21:48
Taking a look at this one now.

**Comment by strepanier03** [comment] 2024-09-13 22:44
Working on creating this. The error mentioned is about a domain, not a workspace, and if this is similar in anyway to Classic you can't close you're account with a verified domain if you're the only admin. 

I'm going to need to test this a bit more. Update coming Monday.

**Comment by strepanier03** [comment] 2024-09-17 17:33
Did get to testing this yesterday but it's on my todo for today.

**Comment by strepanier03** [comment] 2024-09-19 16:54
I have been able to test this now and get a different result in the middle, not sure if the tester got it as well.

----

1. Created a new account under sheena+10@expensifail.com
2. Created a new workspace,
3. Enabled Expensify Card > Disabled Expensify Card,
4. Attempted to close account > Received below message.

> Your account cannot be deleted because you have an active annual subscription. If you would still like to close your account, switch your subscription to pay-per-use and try again.

This is expected at least. 

5. I then requested early cancelation to move to PPU billing.
6. Attempted to close account > Received below message.

> You are the only admin on a domain. Please assign another admin or delete this domain before you try again.

This account is not a domain member, nor a domain admin, so I get blocked from moving forward and fully closing the account. 

<img width="1058" alt="image" src="https://github.com/user-attachments/assets/71c82f7e-b8c8-421e-8a38-b5983d348fc6">

**Comment by strepanier03** [comment] 2024-09-19 16:55
I wonder if this is an expensifail only issue or not? I haven't heard reports of this otherwise so I feel like this is limited in impact.

**Comment by strepanier03** [comment] 2024-09-19 16:57
Also not 100% sure this is external either. @Pujan92 once you take a look at this, can you please let me know if you think this should be switched to Internal?

**Comment by Pujan92** [comment] 2024-09-19 18:27
@strepanier03 It seems to be an internal issue and API needs to be checked.

**Comment by Pujan92** [comment] 2024-10-01 16:14
Adding stamp to assign internal engineer as this seems to be a backend change

🎀👀🎀 C+ reviewed

**Comment by stitesExpensify** [comment] 2024-10-02 18:35
@strepanier03 do you think this is really a bug? I think that this is intended functionality, and that the user would need to go to oldDot, delete the workspace, and then they could delete their account right?

**Comment by strepanier03** [comment] 2024-10-07 18:05
@stitesExpensify— Yes, I think there is a bug here somewhere. The error they get is that they are the last admin on the domain, not the workspace.

If you check my testing steps [here](https://github.com/Expensify/App/issues/49020#issuecomment-2361632770), you'll see that you'll get an initial error about the workspace being on an annual sub (expected) and after going to PPU the workspace you get the domain admin error. You shouldn't get that error here.

Since we're testing on expensifail, I can't reset the domain to continue testing the account closure.

I also deleted the workspace so the account owned none, and tried to close again, in which case the same domain error occurs. 

<img width="1439" alt="image" src="https://github.com/user-attachments/assets/5cd94a6f-e2b2-4d7d-a3d7-be746370836b">
<img width="1439" alt="image" src="https://github.com/user-attachments/assets/84a29fc8-6741-4ef0-b4f5-fd21871c2fd5">

**Comment by stitesExpensify** [comment] 2024-10-07 22:44
From those steps above 

> This account is not a domain member, nor a domain admin, so I get blocked from moving forward and fully closing the account.

They must be one of those things right? Otherwise how were they able to have an expensify card? You can't get them without being on a domain right?

**Comment by strepanier03** [comment] 2024-10-10 23:13
Thanks for the ping @stitesExpensify I had missed your question, apologies. 

sheena+10@expensifail.com is not a domain admin either 🤷‍♀️ 
<img width="1004" alt="image" src="https://github.com/user-attachments/assets/c3849247-42fe-4eae-871b-ed08504d47c9">

Sounds to me like there's two things here.

1. I shouldn't have been able to enable the Expensify Card,
2. ND thinks I am a domain admin when I'm not

**Comment by trjExpensify** [comment] 2024-10-15 10:40
@mountiny @MariaHCD @madmax330 @nkuoch this looks like it's related to Workspace Feeds. Seems strange they can't close the account after simply toggling `Expensify Card` on/off without provisioning a card feed. Equally, the "domain" error message is confusing in this case.

**Comment by trjExpensify** [comment] 2024-10-15 10:40
The remaining work for Workspace Feeds is being moved to #newdot-quality, so I'm moving this issue to that GH project.

**Comment by mountiny** [comment] 2024-10-18 04:04
I can take over, yeah I think we have some bug in deleting the workspace flow, if they deleted the workspace, the domain should have been deleted too

**Comment by mountiny** [comment] 2024-10-30 15:31
Havent got around yet

**Comment by mountiny** [comment] 2024-11-20 12:58
@IuliiaHerets Could you please retest this one now?

**Comment by kavimuru** [comment] 2024-11-20 13:56
Bug is not reproducible anymore.

https://github.com/user-attachments/assets/58feaef4-f701-42d1-8f7c-6265e1c82aba

**Closed** 2024-11-20 14:08 UTC
Labels: Reviewing, Weekly, Internal, Bug
