### ISSUE TITLE
[HOLD for payment 2023-06-29] [$1000] Tooltip not showing for single member in a group chat icon in LHN

### ISSUE THREAD

**Issue by Beamanator** [Expensify/App#20822] opened 2023-06-15 13:34 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. look for a group in LHN
2. hover over single person and then +4 or +n icon

## Expected Result:
tooltips should be present for each

## Actual Result:
Describe what actually happened

## Workaround:
tooltip present only in +n icon and not in single member icon

ALSO:

## Action Performed:
1. go to settings-> worksapces
2. select any workspace and go to invite members
3. select invite -> choose few members -> next
4. ON add message page, hover over avatar and notice there is profile tooltip

## Expected Result:
tooltip with profile description

## Actual Result:
no Tooltip is shown on add message page after memeber invitation

## Workaround:
Can the user still use Expensify without this being fixed? Have you informed them of the workaround?

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android / native
- [x] Android / Chrome
- [x] iOS / native
- [x] iOS / Safari
- [x] MacOS / Chrome / Safari
- [x] MacOS / Desktop

**Version Number:** `main`
**Reproducible in staging?:** N
**Reproducible in production?:** N
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation
**Expensify/Expensify Issue URL:**
**Issue reported by:** @chiragxarora
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1686833052798899
**Issue reported by:** @ashimsharma10
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1686832877081139

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~0126747ee9e5114f69</li>
        <li>Upwork Job ID: 1669337684643139584</li>
        <li>Last Price Increase: 2023-06-15</li>
    </ul>
</details>

**Comment by jayeshmangwani** [comment] 2023-06-15 13:50
@Beamanator same root cause as this issue https://github.com/Expensify/App/issues/20820

**Comment by situchan** [comment] 2023-06-15 14:30
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
Tooltip not showing on avatars in LHN, workspace invite page

### What is the root cause of that problem?
accountID is not passed correctly here
https://github.com/Expensify/App/blob/d39643006874bf5ffec923291afa6b43884a4aec/src/components/MultipleAvatars.js#L81


`allPersonalDetails` now has `accountID` as key, was `login` before.
https://github.com/Expensify/App/blob/ff4df6b60244c64dd9cd1c756046c2fc38796107/src/libs/ReportUtils.js#L830-L832

### What changes do you think we should make in order to solve the problem?

Introduce `id` in avatar object and deprecate `getAccountIDForLogin` function (I suggest this for optimization. No need to pull up personalDetails data again to get `accountID` which is already fetched)

old avatar object: {source, type, name}
new avatar object: {source, type, name, id}


1. add `id: accountID` here:
https://github.com/Expensify/App/blob/9ea7b45d8b69cd5c89889a64abd16567ee94fe09/src/libs/OptionsListUtils.js#L156-L165

2. add `id: accountID` in all occurrences of creating avatar object in https://github.com/Expensify/App/blob/9ea7b45d8b69cd5c89889a64abd16567ee94fe09/src/libs/ReportUtils.js#L659

3. replace all `getAccountIDForLogin` occurrences with `icon.id` in `MultipleAvatars` component

**Comment by alex-mechler** [comment] 2023-06-15 16:30
@Beamanator actually pointed me in the direction of https://github.com/Expensify/App/pull/20818, which was created for https://github.com/Expensify/App/issues/20801#issuecomment-1592977789. 

That PR solves both this and https://github.com/Expensify/App/issues/20820, so closing in favor of that

**Comment by alitoshmatov** [comment] 2023-06-15 16:41
I think we should still apply solution proposed in https://github.com/Expensify/App/issues/20822#issuecomment-1593180839 . Since it makes everything much simpler and benefits the performance. 

But, yes not high priority right now.

**Comment by Beamanator** [comment] 2023-06-19 08:02
@0xmiroslav @mananjadhav can y'all please agree on the best proposed solution so we can move forward with this issue quickly?

**Comment by Beamanator** [comment] 2023-06-19 08:25
I think we're good to move forward with the solution, as we've had enough people agreeing on this idea.

@situchan are you able to make a PR quickly? A few of these possibly related PRs are deploy blockers so we need to get a PR up soon. If you're not able to, I will create the PR soon

**Comment by burczu** [comment] 2023-06-19 08:41
Hi I'm Bartek from Callstack - expert contributor group - I will work on this issue.

**Comment by Beamanator** [comment] 2023-06-19 08:41
Ok looks like I overlooked the fact that `ROUTES.getProfileRoute` accepts an accountID, and I believe we have started to store accountIDs in `options` so we should be able to still get rid of `ReportUtils.getAccountIDForLogin(` here 👍

**Comment by situchan** [comment] 2023-06-19 08:43
I can work on this quickly

**Comment by situchan** [comment] 2023-06-19 08:44
oh I see @burczu already assigned. Please go ahead then.

**Comment by Beamanator** [comment] 2023-06-19 08:44
@situchan if you're free to work on this ASAP please do! I'll assign you 👍

**Comment by mananjadhav** [comment] 2023-06-19 08:45
I think we should ask @situchan to work on it as they've commented on their availability and we can review this asap

**Comment by Beamanator** [comment] 2023-06-19 08:45
Thanks @situchan - sorry for the confusion, I just wasn't sure if you'd be free quickly 😅

**Comment by Beamanator** [comment] 2023-06-20 11:04
This fix was CP'd to staging

**Comment by twisterdotcom** [comment] 2023-06-21 11:30
Okay, this issue is linked to about 5 others. Who on earth am I paying here @Beamanator?

$1k for @situchan and @0xmiroslav for the PR and Review + 50% bonus?
$250 for @ashimsharma10 and @chiragxarora for the report?

**Comment by situchan** [comment] 2023-06-21 11:41
[PR](https://github.com/Expensify/App/pull/21026) fixed all these issues:
https://github.com/Expensify/App/issues/20801
https://github.com/Expensify/App/issues/20813
https://github.com/Expensify/App/issues/20820
https://github.com/Expensify/App/issues/20822
https://github.com/Expensify/App/issues/20971
https://github.com/Expensify/App/issues/20934
https://github.com/Expensify/App/issues/20981

All of these are related each other but some had a bit different root cause and fixes were in different places. Also throughly tested all those issues in PR.
Given that, is this eligible for more bounty? (similar case: https://expensify.slack.com/archives/C01GTK53T8Q/p1685711548218919)

**Comment by twisterdotcom** [comment] 2023-06-21 13:47
Nice, thanks @0xmiroslav. Okay, given the size of the fix, I'm not included to say it's worth... _counts issues_ $8k, but I think we can add another $1k + bonus (so this would be $3k total = $2k + 50% bonus). I'll pay out $250 for each of the reporters above.

**Comment by michaelhaxhiu** [comment] 2023-06-21 18:15
🧇 I'm removing AlexM's assignment. Seems this doesn't need a new CME since we are just doing payment.

**Comment by twisterdotcom** [comment] 2023-06-28 09:11
All offers sent. @0xmiroslav do we need a regression test for this?

**Comment by twisterdotcom** [comment] 2023-06-28 09:12
@NicMendonca I'm OOO now. If this needs a test case, could you handle it. Otherwise, everything is done. I'll pay out the contracts when everyone has accepted.

**Comment by tewodrosGirmaA** [comment] 2023-06-28 10:11
Accepted, Thanks @twisterdotcom

**Comment by twisterdotcom** [comment] 2023-06-29 10:31
All paid out.

**Comment by NicMendonca** [comment] 2023-06-29 17:00
no regression test needed, so closing!

**Closed by NicMendonca** 2023-06-29 17:00 UTC
Labels: External, Daily, Awaiting Payment, Bug, Upwork Automation
