### ISSUE TITLE
[HOLD for payment 2024-06-11] [$250] Chat - Emoji is deleted if entered quickly after some text

### ISSUE THREAD

**Issue by izarutskaya** [Expensify/App#41778] opened 2024-05-07 16:23 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** v1.4.71-0
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**If this was caught during regression testing, add the test name, ID and link from TestRail:** https://expensify.testrail.io/index.php?/tests/view/4544514
**Email or phone of affected tester (no customers):** vdargentotest+ios050724@gmail.com
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Issue reported by:** Applause-Internal team

## Action Performed:
Pre-requisite: user must be logged in.

1. Go to any chat.
2. Tap on the compose box.
3. Enter any text but do not send the message.
4. Tap on the emoji picker and quickly select any emoji. (Note: don't add a space between the word and the emoji)
5. Verify it appears for a moment on the compose box, but suddenly disappears.

## Expected Result:
The selected emoji should remain on the compose box.

## Actual Result:
The selected emoji is displayed for a moment, but suddenly disappears.

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [x] iOS: Native
- [ ] iOS: mWeb Safari
- [ ] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

https://github.com/Expensify/App/assets/115492554/f3bb9143-dec2-4e32-98e8-1e3e1343bfbf

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01f96963f235e9c546</li>
        <li>Upwork Job ID: 1787904276326506496</li>
        <li>Last Price Increase: 2024-05-07</li>
<li>Automatic offers: </li>
<ul>
<li>hungvu193 | Reviewer | 0</li>
</ul></li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @trjExpensify</details>

**Comment by izarutskaya** [comment] 2024-05-07 16:23
We think this issue might be related to the #vip-vsb.

**Comment by trjExpensify** [comment] 2024-05-07 17:56
I can reproduce this. You have to add the emoji to the end of the text with no space for it to disappear.

**Comment by roitman-g** [comment] 2024-05-09 16:38
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
When you enter some text (it can also be space in the end) and then insert an emoji in less than a second after finishing typing, the emoji is being removed. This also can be reproduced in any other platform, just be quick.

### What is the root cause of that problem?
In "ComposerWithSuggestions" component "updateComment" function a comment update with regular text is saved with the debounced function, while comment update with emoji is not. So what happens is first the comment with the emoji is being saved and then the debounced function is being invoked with the old value, reverting the comment to the previous non-emoji state.

### What changes do you think we should make in order to solve the problem?
There are two way to solve this issue.

1. Either adding `debouncedSaveReportComment.flush()` line of code when updating the comment with the emoji in "updateComment" function. This will invoke the debounced function before the emoji insertion.
2. Or save emoji with debounced function. So `updateComment(ComposerUtils.insertText(commentRef.current, selection, text), true);` in "replaceSelectionWithText" function. This will update the debounced function and invoke it with the correct value.



### What alternative solutions did you explore? (Optional)
N/A

**Comment by hungvu193** [comment] 2024-05-11 01:27
I'll review it tmr

**Comment by hungvu193** [comment] 2024-05-13 02:59
Thanks @roitman-g, your proposal makes sense to me, do you know which PR cause this issue?

**Comment by roitman-g** [comment] 2024-05-13 16:04
> Thanks @roitman-g, your proposal makes sense to me, do you know which PR cause this issue?

I am not sure, the bug was probably introduced the same time the emoji insertion functionality and debounced comment caching was first written. But it is very difficult to follow the commits back to that place, since these lines were overwritten by many different commits both for the debounced save draft and emoji insertion.

**Comment by hungvu193** [comment] 2024-05-14 06:09
@roitman-g 's [proposal here](https://github.com/Expensify/App/issues/41778#issuecomment-2103018619) looks good to me. I'd prefer  the first solution. 🎀 👀 🎀  C+ reviewed

**Comment by iwiznia** [comment] 2024-05-14 18:27
Hmmmm curious why you think first solution is better than the 2nd one @hungvu193, it seems to me like comment with or without emoji should be saved debounced so that any comment works the same way....

**Comment by hungvu193** [comment] 2024-05-15 00:00
Yeah, it's just my opinion because we can't enter many emojis at the same time so we don't need to debounce it like we did with comments

**Comment by roitman-g** [comment] 2024-05-15 07:02
I would go with the second, it seems simpler. What if the app is changed so that many emojis can be inserted or any other feature with some other multiple selections is added.

**Comment by iwiznia** [comment] 2024-05-15 20:12
You can paste a message with many emojis, no?
But also I agree is simpler and makes it work the same no matter what you write.
Let's go with the second one.

**Comment by hungvu193** [comment] 2024-05-15 23:49
> You can paste a message with many emojis, no?

Yeah you can, but even you paste it, it will be debounced because it's treated as comment.
But yeah, let go with 2 to make it consistent with comment.

**Comment by hungvu193** [comment] 2024-05-17 11:20
@roitman-g Do you have any ETA for the PR?

**Comment by roitman-g** [comment] 2024-05-17 12:05
> @roitman-g Do you have any ETA for the PR?

I will do it by Sunday.

**Comment by roitman-g** [comment] 2024-05-18 18:40
[PR](https://github.com/Expensify/App/pull/42367) is ready for review

**Comment by hungvu193** [comment] 2024-05-21 09:42
PR was approved, waiting for merge freeze over.

**Comment by hungvu193** [comment] 2024-05-27 02:24
Same

**Comment by hungvu193** [comment] 2024-06-11 11:33
- [x] The PR that introduced the bug has been identified. Link to the PR: https://github.com/Expensify/App/pull/25758
- [x] The offending PR has been commented on, pointing out the bug it caused and why, so the author and reviewers can learn from the mistake. Link to comment:  https://github.com/Expensify/App/pull/25758/files#r1634693264
- [x] A discussion in #expensify-bugs has been started about whether any other steps should be taken (e.g. updating the PR review checklist) in order to catch this type of bug sooner. Link to discussion: N/A
- [x] Determine if we should create a regression test for this bug: Yes
- [x] If we decide to create a regression test for the bug, please propose the [regression test](https://github.com/Expensify/App/blob/main/contributingGuides/REGRESSION_TEST_BEST_PRACTICES.md) steps to ensure the same bug will not reach production again.

**Regression test**:
1. Open any chat.
2. Type some text.
3. Quickly insert some emoji with the help of the app's emoji picker.
4. Verify the emoji is not deleted after that.
Do we 👍 or 👎 ?

**Comment by trjExpensify** [comment] 2024-06-11 17:20
Thanks, @hungvu193! I don't think we need a standalone regression test for this, it was caught while executing an existing one as per the OP link. 

Payment summary as follows: 

- $250 to @hungvu193 for the C+ review 
- $250 to @roitman-g for the fix 

Hans is paid. @roitman-g, can you send me your Upwork profile please?

**Comment by roitman-g** [comment] 2024-06-12 13:18
> Thanks, @hungvu193! I don't think we need a standalone regression test for this, it was caught while executing an existing one as per the OP link.
> 
> Payment summary as follows:
> 
> * $250 to @hungvu193 for the C+ review
> * $250 to @roitman-g for the fix
> 
> Hans is paid. @roitman-g, can you send me your Upwork profile please?

May I use this upwork account for this - https://www.upwork.com/freelancers/~0197cfa7f554b66970?

**Comment by trjExpensify** [comment] 2024-06-13 08:42
@hungvu193 looks paid to me: 

<img width="1413" alt="image" src="https://github.com/Expensify/App/assets/16232057/0f228ce7-1ba6-429b-b369-8f4f6a36e70a">

>May I use this upwork account for this - https://www.upwork.com/freelancers/~0197cfa7f554b66970?

Yeah @roitman-g, if that's your Upwork profile? 😕

**Comment by iwiznia** [comment] 2024-06-17 18:11
Anything else to do here?

**Comment by roitman-g** [comment] 2024-06-19 13:07
> @roitman-g can you confirm on this?
> 
> > Yeah @roitman-g, if that's your Upwork profile? 😕

It is not mine, it is my brother's, I need to prepare my documents to verify my upwork. If it needs to be my upwork, can I send it in the next two weeks?

**Comment by trjExpensify** [comment] 2024-06-19 22:07
Sounds good, @roitman-g. I've sent an offer to that Upwork profile. Please accept and then I'll pay and close this issue out.

**Comment by trjExpensify** [comment] 2024-06-20 12:21
Paid, closing!

**Closed by trjExpensify** 2024-06-20 12:21 UTC
Labels: External, Daily, Awaiting Payment, Bug
