### ISSUE TITLE
[HOLD for regression test steps, maybe] [Dark Mode] Use same overlay color for all modals, action sheets, etc

### ISSUE THREAD

**Issue by shawnborton** [Expensify/App#13208] opened 2022-11-30 19:35 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
Currently we have mismatched styles when opening things like rightDocked modals or bottom action sheets:

<img width="1152" alt="image" src="https://user-images.githubusercontent.com/2319350/204890657-717df382-919f-43e7-96f4-1ef60ead0f3f.png">

## Expected Result:
Let's standardize on the overlay color used for all modals (both web and mobile). 
![image](https://user-images.githubusercontent.com/2319350/204891738-6d45b52d-e094-498a-be59-e55d0d9a272d.png)

Let's use our brand dark green (#002E22) at 60% opacity. 

## Actual Result:
Styles are mismatched and not using the right colors. 

## Workaround:
This doesn't block user actions. 

## Platform:

Where is this issue occurring? All platforms

**Version Number:** 
**Reproducible in staging?:** 
**Reproducible in production?:** 
**Email or phone of affected tester (no customers):** 
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation
**Expensify/Expensify Issue URL:** 
**Issue reported by:** 
**Slack conversation:** 

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01a2fe253f63b94c3c</li>
        <li>Upwork Job ID: 1606452536036261888</li>
        <li>Last Price Increase: 2022-12-24</li>
    </ul>
</details>

**Comment by grgia** [comment] 2022-11-30 19:38
This will make a big difference, I'm gonna take this on internally this week

**Comment by shawnborton** [comment] 2022-11-30 20:11
Woo, thank you Georgia!

**Comment by shawnborton** [comment] 2022-12-01 14:51
Noting that @dhairyasenjaliya reported that we missed the overlay color here too:
<img width="525" alt="image" src="https://user-images.githubusercontent.com/2319350/205083908-4e065b06-4bfd-4564-b601-3273d32ec42d.png">


Same applies for starting a group chat:
![image](https://user-images.githubusercontent.com/2319350/205083992-8ba714e2-7b75-409f-bfa8-7058ba8e364d.png)

**Comment by sonialiap** [comment] 2022-12-01 22:21
Since Georgia is picking it up, I'll skip the triage and unassign myself 👋

**Comment by grgia** [comment] 2022-12-05 19:25
Looking at this today!

**Comment by grgia** [comment] 2022-12-07 03:39
https://user-images.githubusercontent.com/38015950/206081947-022c972b-2c9d-43a6-8539-20bd35ed2f06.mov

Right now, the overlay colors overlap- what's the ideal solution for this modal? (PS I made it pink for visibility 😄  )

**Comment by grgia** [comment] 2022-12-07 03:41
Here's what it looks like with the 60% opacity green:

https://user-images.githubusercontent.com/38015950/206082662-8a7aa8b0-c0fd-4a4c-878a-526beff62d00.mov

**Comment by grgia** [comment] 2022-12-07 03:58
<img width="378" alt="Screenshot 2022-12-06 at 7 46 29 PM" src="https://user-images.githubusercontent.com/38015950/206083380-e99d0090-e31a-4ca8-a967-ab1d0dc4e55e.png">
For the workspace overlay, should we use this pattern instead? 
<img width="70" alt="image" src="https://user-images.githubusercontent.com/38015950/206083609-f6940501-42e3-4d05-91cb-2b6ab4f0394e.png"> 

Avatar overlay:
<img width="693" alt="image" src="https://user-images.githubusercontent.com/38015950/206084367-cc9fb134-c6eb-4980-a095-348f70e5a915.png">

**Comment by shawnborton** [comment] 2022-12-07 20:08
Whoa, didn't realize we were doing the double overlay there. That being said, I think the 60% green works just fine though - thoughts? 

For the workspace/avatar overlay, are the screenshots above using 60% green? Maybe we can use the same color from the little `+5` screenshot you shared, but use it at something like 88% opacity so you can slightly see the avatar behind? I wouldn't necessarily refactor the small chat row stack for this, but we could try it for the workspace row and chat empty state?

**Comment by grgia** [comment] 2022-12-07 20:32
I agree, once I switched it to green I thought the double overlay looked fine. I'll test the workspace with the '+5' color overlay now!

**Comment by grgia** [comment] 2022-12-07 20:54
I agree, it somewhat works for the workspaces, but I prefer the green overlay for the 4 avatars.

Here's a few more options

AppBG at 70%  
<img width="405" alt="image" src="https://user-images.githubusercontent.com/38015950/206292645-484a21a1-a43f-43a0-be66-5e779aa5e58f.png">

Icons color at 100%
<img width="343" alt="image" src="https://user-images.githubusercontent.com/38015950/206292728-33bfd928-2cf1-40d5-991c-09d84f2d0126.png">
Borders color at 100% (works when workspace icons are all green, not sure how this will look when we add in the new colored ones)
<img width="349" alt="image" src="https://user-images.githubusercontent.com/38015950/206292908-ee582fc0-fc4f-4a56-a066-a582c060f055.png">

**Comment by shawnborton** [comment] 2022-12-07 21:34
I think I am leaning towards just using the same color we use for modal overlays for consistency's sake?

**Comment by grgia** [comment] 2022-12-12 16:52
not overdue, in review!

**Comment by grgia** [comment] 2022-12-16 16:49
Checking off as this was more of a feature/color update than a bug. Regression tests will be bundled with dark mode  TestRail tests

**Comment by mollfpr** [comment] 2022-12-22 00:55
@grgia Could you pull someone from BZ to create the Upwork job for the PR review? Thank you!

**Comment by mallenexpensify** [comment] 2022-12-24 00:53
@mollfpr can you please apply to the job and reply here once you have? 
https://www.upwork.com/jobs/~01a2fe253f63b94c3c

**Comment by mollfpr** [comment] 2022-12-24 01:19
@mallenexpensify Can’t access the job

**Comment by dhairyasenjaliya** [comment] 2022-12-26 13:42
@mallenexpensify I have reported a bug on slack https://expensify.slack.com/archives/C049HHMV9SM/p1669898961401989 which we are addressing here as per this comment https://github.com/Expensify/App/issues/13208#issuecomment-1333884029 do I need to apply for reporting here?

**Comment by mollfpr** [comment] 2022-12-26 23:36
Bump @mallenexpensify

**Comment by mallenexpensify** [comment] 2022-12-27 01:00
Hired @mollfpr for $1000 for PR review
Hired @dhairyasenjaliya for $250 for bug reporting (thanks for the ping, I would have missed it cuz it wasn't in the OP)
Both, can you please accept the job and reply here once you have?

**Comment by mollfpr** [comment] 2022-12-27 01:58
Accepted, thanks @mallenexpensify

**Comment by dhairyasenjaliya** [comment] 2022-12-27 04:28
accepted, thank you @mallenexpensify

**Comment by mallenexpensify** [comment] 2022-12-27 16:30
Paid @mollfpr and @dhairyasenjaliya , leaving open and weekly cuz I want to double check the regression steps before closing

**Comment by mallenexpensify** [comment] 2023-01-20 00:30
I know I'd be _responsible_ for one of these issues that needed regression test steps that wasn't going overdue cuz of the `Reviewing` label, thanks for the reminder Mel. 🤖 

OH.. actually, this is just a dark mode update and I think we're not creating/updating TestRail steps for this, at least not yet. Closing!

**Closed** 2023-01-20 00:30 UTC
Labels: Daily, Monthly, Internal, Awaiting Payment, Bug
