### ISSUE TITLE
Thread – Thread is bold in LHN when leave thread and open again, chat reloads sometimes

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#42515] opened 2024-05-23 11:44 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.75-0
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**If this was caught during regression testing, add the test name, ID and link from TestRail:** https://expensify.testrail.io/index.php?/tests/view/4568669
**Email or phone of affected tester (no customers):** applausetester+jpcategory_1@applause.expensifail.com
**Issue reported by:** Applause - Internal Team

## Action Performed:
1. Go to https://staging.new.expensify.com/
2. Log in
3. Open any chat and send a message
4. Create a thread and send a message
5. Leave the thread using three dot menu
6. Open thread again
7. Observe the thread in LHN

## Expected Result:
Thread is not bold in LHN, as it is opened. Chat doesn’t reload

## Actual Result:
Thread is bold in LHN when left the chat message appears, chat reloads sometimes

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details> 

https://github.com/Expensify/App/assets/78819774/31c60e63-f266-47ce-89a9-852c4fb04d61

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~018ea1c5ef6f4844fe</li>
        <li>Upwork Job ID: 1798111207890632704</li>
        <li>Last Price Increase: 2024-06-11</li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @hungvu193</details>

**Comment by lanitochka17** [comment] 2024-05-23 11:45
@kevinksullivan  FYI I haven't added the External label as I wasn't 100% sure about this issue. Please take a look and add the label if you agree it's a bug and can be handled by external contributors

**Comment by kevinksullivan** [comment] 2024-06-04 21:54
agree this is VSB related.

**Comment by hungvu193** [comment] 2024-06-05 14:28
Waiting for proposals

**Comment by hungvu193** [comment] 2024-06-07 03:50
We're still looking for proposals

**Comment by hungvu193** [comment] 2024-06-10 23:32
Still looking for proposals

**Comment by hungvu193** [comment] 2024-06-11 06:38
I can't reproduce this on latest main, can you please check again? @lanitochka17 

https://github.com/Expensify/App/assets/16502320/5105c2f5-1f10-45b7-878d-9f574e75ab92

**Comment by hungvu193** [comment] 2024-06-11 07:14
Also I got this error while waiting for Pusher event to update the `left the chat` message. I think this issue should be internal.
cc @kevinksullivan 

<img width="552" alt="Screenshot 2024-06-11 at 14 11 42" src="https://github.com/Expensify/App/assets/16502320/50642892-f2e2-4e86-9caf-ecb8b15041f2">

**Comment by hungvu193** [comment] 2024-06-11 23:28
This can be BE issue

**Comment by hungvu193** [comment] 2024-06-12 01:23
I tested this one today and can't reproduce anymore.

Can you please verify this again? @lanitochka17 

https://github.com/Expensify/App/assets/16502320/611886f1-c42c-4ffd-8011-0bcc550976e4

**Comment by hungvu193** [comment] 2024-06-14 01:57
little bump @kevinksullivan

**Comment by hungvu193** [comment] 2024-06-17 02:16
Still waiting for the above question ✋

**Comment by mallenexpensify** [comment] 2024-06-18 02:22
@hungvu193 co-assigning since Kev's going OOO. 
I get a _flash_ but I feel like that's different than the reported bug, it appears the 'left the chat' doesn't post til the thread is revisited. 

https://github.com/Expensify/App/assets/22508304/71923e85-dec2-4501-8694-fb07020b5d6c

**Comment by hungvu193** [comment] 2024-06-18 02:40
I think there's another issue here that `left the chat` text will never show up until you refresh or re-visit that thread again.

**Comment by mallenexpensify** [comment] 2024-06-21 18:39
Checking in #expensify-open-source about 
https://expensify.slack.com/archives/C01GTK53T8Q/p1718995150527849

**Comment by mallenexpensify** [comment] 2024-06-21 19:40
From Kevin in the chat above
> Regarding "`left the chat` text will never show up until you refresh or re-visit that thread again." I think this is a simpler issue which might be potentially easy to solve from BE (pusher events issue).

@hungvu193 do you agree?

**Comment by hungvu193** [comment] 2024-06-21 23:51
> From Kevin in the chat above
> 
> > Regarding "`left the chat` text will never show up until you refresh or re-visit that thread again." I think this is a simpler issue which might be potentially easy to solve from BE (pusher events issue).
> 
> 
> 
> @hungvu193 do you agree? 

Agreed 😄

**Comment by mallenexpensify** [comment] 2024-06-24 22:31
Bumped to internal, let's see what the `retest-weekly` ends up returning.

**Comment by lanitochka17** [comment] 2024-06-27 17:28
Thread is bold for a moment

https://github.com/Expensify/App/assets/78819774/9035ed56-7778-45f4-b038-ab3b3786b326

**Comment by mallenexpensify** [comment] 2024-06-28 01:51
Thanks @lanitochka17 , going to close this one.

**Closed by mallenexpensify** 2024-06-28 01:51 UTC
Labels: Weekly, Internal, Bug, retest-weekly
