### ISSUE TITLE
[HOLD for payment 2024-07-26] [$250]  iOS - Distance - Center icon overlaps with compass icon

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#44486] opened 2024-06-26 16:36 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 9.0.2-0
**Reproducible in staging?:** Y
**Reproducible in production?:** Y 
**If this was caught during regression testing, add the test name, ID and link from TestRail:** N/A 
**Issue reported by:** Applause - Internal Team

## Action Performed:
1. Launch New Expensify app
2. Go to FAB > Submit expense > Distance
3. Use two fingers to rotate the map

## Expected Result:
Center icon will not overlap with compass icon

## Actual Result:
Center icon overlaps with compass icon

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [x] iOS: Native
- [ ] iOS: mWeb Safari
- [ ] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details> 

https://github.com/Expensify/App/assets/78819774/778a221d-284c-49cc-89fd-d17e7b2870ad

<img width="385" alt="00 08 43" src="https://github.com/Expensify/App/assets/78819774/b2e8e98c-528a-433f-a2b3-70dc6d7eb47d">

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01c7fdbfc969413a5e</li>
        <li>Upwork Job ID: 1806794874145887299</li>
        <li>Last Price Increase: 2024-06-28</li>
<li>Automatic offers: </li>
<ul>
<li>ahmedGaber93 | Reviewer | 102939572</li>
<li>Krishna2323 | Contributor | 102939574</li>
</ul></li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @trjExpensify</details>

**Comment by lanitochka17** [comment] 2024-06-26 16:37
@trjExpensify  FYI I haven't added the External label as I wasn't 100% sure about this issue. Please take a look and add the label if you agree it's a bug and can be handled by external contributors

**Comment by lanitochka17** [comment] 2024-06-26 16:37
We think that this bug might be related to #vip-vsp

**Comment by trjExpensify** [comment] 2024-06-26 19:26
Hm, @Expensify/design I'm not sure on this. Do we literally just cover the compass icon in the background or should it not be there at all?

**Comment by shawnborton** [comment] 2024-06-26 19:38
Ah interesting, that only shows up if you rotate the map I bet?

**Comment by dannymcclain** [comment] 2024-06-26 19:51
>Ah interesting, that only shows up if you rotate the map I bet?

Yup you're right. I had never seen that compass before but I just tested out rotating the map and that's when it shows up. Womp.

**Comment by trjExpensify** [comment] 2024-06-26 23:06
Goooot it. So both of these UI elements need to live together in the same view then conceivably?

**Comment by shawnborton** [comment] 2024-06-27 05:41
It looks like we can also just move the compass or disable it entirely. From [here](https://github.com/rnmapbox/maps/blob/main/docs/MapView.md):


![CleanShot 2024-06-27 at 07 41 07@2x](https://github.com/Expensify/App/assets/2319350/6b54f509-7979-4df1-a749-f56639053f75)

So I like the idea of maybe moving the compass to the bottom right or something? Curious what @Expensify/design thinks.

**Comment by trjExpensify** [comment] 2024-06-27 08:47
Got it. Bottom right, above the info button? We can pay a retainer to get rid of all the Mapbox stuff at the bottom at some point in the future.  

I think we should keep the compass, as I think it's pretty standard when turning the map to reorientate it.

**Comment by shawnborton** [comment] 2024-06-27 08:49
Yeah, that's what I was thinking. And the info button would typically always show because the default view is not to rotate the map.

**Comment by trjExpensify** [comment] 2024-06-27 09:02
Sounds good!

**Comment by trjExpensify** [comment] 2024-06-27 11:34
Works for me, but I'll defer to Shawn!

**Comment by dannymcclain** [comment] 2024-06-27 13:29
I like it beneath the scale bar—it does feel kinda related and tucks up in there nicely. Will also wait for Shawn to weigh in 🙂

**Comment by shawnborton** [comment] 2024-06-27 16:43
Oh I really like that too, let's do it

**Comment by trjExpensify** [comment] 2024-06-28 21:00
Let's do it!

**Comment by ahmedGaber93** [comment] 2024-06-29 00:17
@Krishna2323's [alternative solutions](https://github.com/Expensify/App/issues/44486#issuecomment-2192191193) option 2 using `compassPosition` to change the compass position LGTM! 
also, [result](https://github.com/Expensify/App/issues/44486#issuecomment-2194372119) is accepted by the design team.

🎀 👀 🎀 C+ reviewed

**Comment by GoldenDragon320** [comment] 2024-07-01 05:28
Hi! I am a new developer on expensify.
I understand the bug

**Comment by lakchote** [comment] 2024-07-01 07:35
@Krishna2323's proposal LGTM.

**Comment by ahmedGaber93** [comment] 2024-07-01 18:35
@Krishna2323 please let me know when PR is ready. thanks!

**Comment by ahmedGaber93** [comment] 2024-07-23 08:47
**BugZero Checklist**: The PR fixing this issue has been merged! The following checklist ([instructions](https://stackoverflow.com/c/expensify/questions/14574)) will need to be completed before the issue can be closed:

- [x] [@ahmedGaber93] The PR that introduced the bug has been identified. Link to the PR: https://github.com/Expensify/App/pull/40759
- [x] [@ahmedGaber93] The offending PR has been commented on, pointing out the bug it caused and why, so the author and reviewers can learn from the mistake. Link to comment: https://github.com/Expensify/App/pull/40759#issuecomment-2244596368
- [x] [@ahmedGaber93] A discussion in #expensify-bugs has been started about whether any other steps should be taken (e.g. updating the PR review checklist) in order to catch this type of bug sooner. Link to discussion: N/A
- [x] [@ahmedGaber93] Determine if we should create a regression test for this bug. Yes
- [x] [@ahmedGaber93] If we decide to create a regression test for the bug, please propose the [regression test](https://github.com/Expensify/App/blob/main/contributingGuides/REGRESSION_TEST_BEST_PRACTICES.md) steps to ensure the same bug will not reach production again.

### Regression Test Proposal

1. Go to FAB > Submit expense > Distance
2. Android only - Look at the map view Verify compass icon is displayed by default on the top left corner and there is no scale bar
3. iOS only - Use two fingers to rotate the map and Verify compass icon is displayed after rotate on the top left corner and there is no scale bar

 Do we agree 👍 or 👎

**Comment by trjExpensify** [comment] 2024-07-26 18:10
Payment summary as follows: 

- $250 to @ahmedGaber93 for C+ 
- $250 to @Krishna2323 for the fix

Paid!

**Closed by trjExpensify** 2024-07-26 18:10 UTC
Labels: External, Daily, Overdue, Awaiting Payment, Bug
