### ISSUE TITLE
[HOLD for payment 2024-03-07] Splash logo icon is black instead of green (prod only)

### ISSUE THREAD

**Issue by isagoico** [Expensify/App#35018] opened 2024-01-23 23:50 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** v1.4.29-1
**Reproducible in staging?:** No 
**Reproducible in production?:** Yes
**If this was caught during regression testing, add the test name, ID and link from TestRail:** N/A
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** @coleaeason 
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1706050599347949

## Action Performed:
1. Reload the app 

## Expected Result:
Splash icon should be green. 

## Actual Result:
Splash icon is black. 

## Workaround:
N/A 

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [x] Android: mWeb Chrome
- [ ] iOS: Native
- [x] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

![image](https://github.com/Expensify/App/assets/44479856/d3f5512a-f62d-40d8-adcf-7951fe148ed7)

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01aac5767909c58b6b</li>
        <li>Upwork Job ID: 1749942692150059008</li>
        <li>Last Price Increase: 2024-01-23</li>
    </ul>
</details>

**Comment by jeremy-croff** [comment] 2024-01-24 00:25
I believe this is intentional 
https://github.com/Expensify/App/blob/main/assets/images/new-expensify.svg
If you have requirements to change it I can do so by updating what the splashLogo maps to

The other ones are specific to dev and staging

The dark green one wouldn't have enough contrast

**Comment by aswin-s** [comment] 2024-01-24 00:26
## Proposal

### Please re-state the problem that we are trying to solve in this issue.

Expensify icon shown on splash screen is black in production environment for web platforms

### What is the root cause of that problem?

The icon file being used as splash icon is new-expensify.svg

https://github.com/Expensify/App/blob/0efabc2b40fe845b13faa94ec508a6693167ede9/web/index.html#L168

https://github.com/Expensify/App/blob/0efabc2b40fe845b13faa94ec508a6693167ede9/config/webpack/webpack.common.js#L68

Other logos have fill color defined in styles as `st2{fill:#03d47c}`. However for production logo  fill color is missing in styles.


### What changes do you think we should make in order to solve the problem?

Add `fill:#03d47c` to svg style definition.

```
.st0{fill-rule:evenodd;clip-rule:evenodd; fill:#03d47c}
```

### What alternative solutions did you explore? (Optional)
None (edited)

**Comment by jliexpensify** [comment] 2024-01-24 05:59
@abdulrahuman5196 can you confirm this?

>This is because of a regression from: https://github.com/Expensify/App/pull/33863

If so, this should be assigned to @thesahindia

**Comment by shawnborton** [comment] 2024-01-24 08:44
cc @barttom for the possible regression above ^^

**Comment by barttom** [comment] 2024-01-24 09:03
@shawnborton Yup, I think this is regression. I didn't know that this file is used anywhere instead of an app icon.
I've removed the defined color because for icon we need to have a neutral color to provide different states e.g. for hover.
I haven't found any possibility to define color for the splash logo, so I'll create a separate file dedicated to a splash logo.
I'll create PR today

**Comment by shawnborton** [comment] 2024-01-24 09:13
Wonderful, thanks!

**Comment by jliexpensify** [comment] 2024-01-31 21:37
@thesahindia @dangrous ^ do we have another regression?

**Comment by situchan** [comment] 2024-02-01 09:46
The 2nd PR was also reverted unfortunately due to [regression](https://github.com/Expensify/App/issues/35468)

**Comment by barttom** [comment] 2024-02-01 09:46
This fix is reverted, I'll send another soon
https://github.com/Expensify/App/issues/35468

**Comment by jeremy-croff** [comment] 2024-02-01 14:05
> @jliexpensify Since [the fix PR](https://github.com/Expensify/App/pull/35097) for this GH issue is using [my proposal](https://github.com/Expensify/App/issues/35018#issuecomment-1907375427), can you assign me to this GH issue for compensation, thank you!

Is this common practice?

Looks like I had the first proposal and the correct one.

https://github.com/Expensify/App/issues/35018#issuecomment-1907140745

**Comment by jliexpensify** [comment] 2024-02-02 00:57
@jeremy-croff @dukenv0307 I'm not an Engineer so I can't make a judgement here

@dangrous @thesahindia tagging you in for some help here! Should @dukenv0307 be assigned?

**Comment by dangrous** [comment] 2024-02-02 15:25
I'm actually not fully sure what we do in this situation normally - but at this point it's moot since we ended up reverting that fix anyway. So no need to adjust payment at this point as we're waiting for a fix of the regression of the fix of the regression. Le sigh

**Comment by jeremy-croff** [comment] 2024-02-02 18:13
> I'm actually not fully sure what we do in this situation normally - but at this point it's moot since we ended up reverting that fix anyway. So no need to adjust payment at this point as we're waiting for a fix of the regression of the fix of the regression. Le sigh

The current approach in latest fix https://github.com/Expensify/App/pull/35544 is the one that I suggested. The previous approach from @dukenv0307 is what got reverted.

But reading a request from a more experienced contributor to request payment for having the correct suggestion made me curious about exactly this process.. It seems the final fix will be the one I suggested.

However,  the actual bug and solution is so rudimentary that I don't necessarily deserve any credit. I just called it from the start :D

**Comment by jliexpensify** [comment] 2024-02-06 03:42
Hmm sorry, I am not sure I'm understanding here - wasn't this a regression, as correctly identified by @jeremy-croff ? If so, then the GH issue goes to the Contributor and C+ who worked on the original PR which caused the regression. So why is @dukenv0307 proposing compensation?

**Comment by jliexpensify** [comment] 2024-02-06 03:43
Said another way - it's great that your proposal is the fix @dukenv0307, but in the case of a regression, it's on the original PR owners to fix it, right? Which is @barttom

**Comment by dangrous** [comment] 2024-02-06 20:30
ha so this one is particularly confusing - I think these are the discussions:
* @dukenv0307 proposed a solution for this bug, however the issue was determined to be a regression, so the original authors took it on. The solution they pushed is similar. This solution ended up being reverted as well, so it's moot, but even if it was, I don't think we typically offer compensation (but we appreciate the effort!)
* @jeremy-croff proposed a solution for this bug, however the issue was determined to be a regression, so the original authors took it on. The solution they pushed was reverted, and the new solution is similar to the one @jeremy-croff proposed. Again, I don't think we typically offer compensation for this case, since it's covered by the original authors.
 
However, it brings up an interesting more general point - think of the following scenario:
* Issue exists
* Contributor A proposes Solution A
* Contributor B proposes Solution B
* We go with Contributor A, and merge Solution A
* Solution A causes a regression and is reverted
* Contributor A looks into the regression and determines that Solution B would be a better fix and implements it.
* So, in the end, we're using Contributor B's proposal but Contributor A was the only one involved.

Important: I don't think this is likely to happen very often, and I will stress again, since this issue itself was a regression as well, it doesn't apply here either. But might be interesting to discuss at some point. All in all, no action required here I don't think. Just a thought experiment.

**Comment by jeremy-croff** [comment] 2024-02-06 20:41
> ha so this one is particularly confusing - I think these are the discussions:
> 
> * @dukenv0307 proposed a solution for this bug, however the issue was determined to be a regression, so the original authors took it on. The solution they pushed is similar. This solution ended up being reverted as well, so it's moot, but even if it was, I don't think we typically offer compensation (but we appreciate the effort!)
> * @jeremy-croff proposed a solution for this bug, however the issue was determined to be a regression, so the original authors took it on. The solution they pushed was reverted, and the new solution is similar to the one @jeremy-croff proposed. Again, I don't think we typically offer compensation for this case, since it's covered by the original authors.
> 
> However, it brings up an interesting more general point - think of the following scenario:
> 
> * Issue exists
> * Contributor A proposes Solution A
> * Contributor B proposes Solution B
> * We go with Contributor A, and merge Solution A
> * Solution A causes a regression and is reverted
> * Contributor A looks into the regression and determines that Solution B would be a better fix and implements it.
> * So, in the end, we're using Contributor B's proposal but Contributor A was the only one involved.
> 
> Important: I don't think this is likely to happen very often, and I will stress again, since this issue itself was a regression as well, it doesn't apply here either. But might be interesting to discuss at some point. All in all, no action required here I don't think. Just a thought experiment.

I agree and thanks for reviewing the situation. It's a tiny bit painful as a new contributor because this has happened to me twice this week and I have not gotten any proposals accepted yet. I will keep on trying though.
This one was unfortunately more verbose copy paste of my logic:
https://github.com/Expensify/App/issues/35663#issuecomment-1925066729 and PR https://github.com/Expensify/App/pull/35872/files#diff-78609be64f9c89b1986ed92266ac4cfd0ad05a5751bee8678d61a1e61822ac39R102
Which is not even what the accepted proposal proposed.

**Comment by dangrous** [comment] 2024-02-07 18:12
That makes sense to me @jliexpensify!

So to update/clarify melvin's comment up there ^ - we will not be handling payment fo either the contributor or reviewer on this issue, as it's a regression (it will be handled on the original issue). We _will_ be giving partial payment to @jeremy-croff for their help and solutions.

But no payment should happen yet since [the fix of the fix of the fix](https://github.com/Expensify/App/pull/35544) is still in progress, despite it now being 7 days after the merge of the PR that supposedly fixed this issue but was reverted.

Is that all correct?

**Comment by jliexpensify** [comment] 2024-02-07 23:13
Yep, I think that's fair and thanks for considering my approach @dangrous!

So in summary - for this specific GH:

- Contributor: @jeremy-croff $250 ([context here](https://github.com/Expensify/App/issues/35018#issuecomment-1931110258))

[Upworks Job](https://www.upwork.com/jobs/~01aac5767909c58b6b)

**Comment by jeremy-croff** [comment] 2024-02-13 07:11
> Yep, I think that's fair and thanks for considering my approach @dangrous!
> 
> So in summary - for this specific GH:
> 
> * Contributor: @jeremy-croff $250 ([context here](https://github.com/Expensify/App/issues/35018#issuecomment-1931110258))
> 
> [Upworks Job](https://www.upwork.com/jobs/~01aac5767909c58b6b)

I applied to it, is there anything else I need to do to get it accepted?

**Comment by jliexpensify** [comment] 2024-02-13 22:54
Huh, is that Job loading for you @jeremy-croff ? I'm getting timeout errors when trying to view it

**Comment by jeremy-croff** [comment] 2024-02-13 22:56
> Huh, is that Job loading for you @jeremy-croff ? I'm getting timeout errors when trying to view it

Yeah it is

**Comment by jliexpensify** [comment] 2024-02-13 23:12
Weird, must have been temporary! Sent you an offer, just got to wait until the fix hits prod - we pay after 7 days.

**Comment by jliexpensify** [comment] 2024-02-16 00:17
Not deployed yet

**Comment by dangrous** [comment] 2024-02-16 15:32
fix number 3 has been merged! not yet on staging/prod but we should be able to close this out shortly

**Comment by jliexpensify** [comment] 2024-02-21 03:55
Deployed to staging yesterday

**Comment by jliexpensify** [comment] 2024-03-05 22:05
The above summary is not correct, [here's the correct one](https://github.com/Expensify/App/issues/35018#issuecomment-1933087691) to be paid.

**Comment by jliexpensify** [comment] 2024-03-08 00:04
Paid, job closed!

**Closed by jliexpensify** 2024-03-08 00:04 UTC
Labels: Reviewing, External, Daily, Awaiting Payment, Bug
