### ISSUE TITLE
[$250]  Web - Hold request - Education header shows "Back" instead of "Hold request"

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#40577] opened 2024-04-19 15:08 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.63-7
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**If this was caught during regression testing, add the test name, ID and link from TestRail:** N/A
**Issue reported by:** Applause - Internal Team

## Action Performed:
1. Go to staging.new.expensify.com
2. Go to workspace chat
3. Create a request
4. Create another request if there is only one request (because Hold request is not showing in combined report)
5. Go to transaction thread
6. Click 3-dot menu > Hold request
7. Note that the RHP header shows "Hold request"
8. Select a reason and save it
9. Note the RHP educational header

## Expected Result:
The education header should display "Hold request"

## Actual Result:
The education header displays "Back"

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details> 

https://github.com/Expensify/App/assets/78819774/225e9737-fb47-41d1-9fe0-482025d9ad3f

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01f393cccfa8c17c69</li>
        <li>Upwork Job ID: 1781344144098091008</li>
        <li>Last Price Increase: 2024-04-19</li>
    </ul>
</details>

**Comment by lanitochka17** [comment] 2024-04-19 15:09
@bfitzexpensify  FYI I haven't added the External label as I wasn't 100% sure about this issue. Please take a look and add the label if you agree it's a bug and can be handled by external contributors

**Comment by FitseTLT** [comment] 2024-04-19 15:15
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
Hold request - Education header shows "Back" instead of "Hold request"

### What is the root cause of that problem?
We set it to back here
https://github.com/Expensify/App/blob/9b2c5187e2203d83bba50bfa66936691788cbd18/src/pages/ProcessMoneyRequestHoldPage.tsx#L36-L37
### What changes do you think we should make in order to solve the problem?

give the title same as here
https://github.com/Expensify/App/blob/9b2c5187e2203d83bba50bfa66936691788cbd18/src/pages/iou/HoldReasonPage.tsx#L94-L95
### What alternative solutions did you explore? (Optional)

**Comment by s77rt** [comment] 2024-04-20 20:41
Asking how to handle this internally https://expensify.slack.com/archives/C02NK2DQWUX/p1713645665251239

**Comment by bfitzexpensify** [comment] 2024-04-23 14:47
OK we got a thumbs up there, so closing this out for it to be handled by https://github.com/Expensify/App/pull/38471 instead.

**Closed by bfitzexpensify** 2024-04-23 14:47 UTC
Labels: External, Daily, Help Wanted, Bug
