### ISSUE TITLE
[HOLD for payment 2024-03-20] Tag - Newly added tags aren't displayed under the "Tags" section in workspace settings

### ISSUE THREAD

**Issue by izarutskaya** [Expensify/App#37873] opened 2024-03-07 09:03 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** v1.4.48-0
**Reproducible in staging?:** Y
**Reproducible in production?:** N
**Email or phone of affected tester (no customers):** applausetester+alm1018@applause.expensifail.com
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Issue reported by:** Applause-Internal Team

## Action Performed:
Precondition:
User is an admin of Collect workspace with no previously added tags (you should add new tags before steps reproduction )

1. Navigate to staging.new.expensify.com
2. Go to Workspace settings > Collect workspace
3. Select the "Tags" tab
4. Add some tags via classic app
5. Refresh the page to see the newly added tags

## Expected Result:
Newly added tags should be displayed under the "Tags" section in workspace settings.

## Actual Result:
Newly added tags aren't displayed under the "Tags" section in workspace settings.

## Workaround:
Can the user still use Expensify without this being fixed? Have you informed them of the workaround?

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [x] Android: mWeb Chrome
- [x] iOS: Native
- [x] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

https://github.com/Expensify/App/assets/115492554/9ccc428e-bb46-477b-8fbd-15e28aaa7df5

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by izarutskaya** [comment] 2024-03-07 09:05
@MonilBhavsar I haven't added the External label as I wasn't 100% sure about this issue. Please take a look and add the label if you agree it's a bug and can be handled by external contributors.


We think that this bug might be related to #wave8-collect-admins
CC @zanyrenney

**Comment by MonilBhavsar** [comment] 2024-03-07 11:19
@luacmartins @waterim @Abdallah-Ahmed-moh looks like it is coming from this PR https://github.com/Expensify/App/pull/37621
Given that this is WIP under simplified collect, I think this is not a not a blocker. Let me know what do you think

**Comment by MonilBhavsar** [comment] 2024-03-07 13:06
Yes, I confirmed Onyx updates are not being delivered. I am aware of work going on to deliver Policy onyx updates to send update to everyone. I think this is not a blocker

**Comment by luacmartins** [comment] 2024-03-07 13:08
This is not a blocker, but @waterim we need to call `OpenPolicyTagsPage` API command when we load the page to make sure we load those, similar to how we do [here](https://github.com/Expensify/App/blob/bc655ed133a0ae6a807858758132c81a7799afca/src/pages/workspace/categories/WorkspaceCategoriesPage.tsx#L59-L68)

**Comment by MonilBhavsar** [comment] 2024-03-07 14:01
Assigning @waterim to the issue as per above mentioned comment

**Comment by waterim** [comment] 2024-03-07 14:51
@MonilBhavsar This one will be added [here](https://github.com/Expensify/App/pull/37755)

**Comment by luacmartins** [comment] 2024-03-07 15:01
Nice! Added this issue to the list of fixed issues in that PR.

**Comment by greg-schroeder** [comment] 2024-03-25 08:52
Apologies, I was OOO last week. Taking a look at this now!

**Comment by greg-schroeder** [comment] 2024-03-25 09:45
Closing per https://github.com/Expensify/App/issues/37873#issuecomment-1995527696

**Closed by greg-schroeder** 2024-03-25 09:45 UTC
Labels: Engineering, Daily, Awaiting Payment, Bug
