### ISSUE TITLE
[$250] Attachment - Attachment preview does not show the image

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#43660] opened 2024-06-13 13:34 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.83-0
**Reproducible in staging?:** Y
**Reproducible in production?:** N 
**If this was caught during regression testing, add the test name, ID and link from TestRail:** N/A
**Issue reported by:** Applause - Internal Team

## Action Performed:
1. Go to staging.new.expensify.com
2. Go to chat
3. Go to + > Add attachment
4. Upload an image

## Expected Result:
Attachment preview will show the image

## Actual Result:
Attachment preview does not show the image

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [x] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details> 

https://github.com/Expensify/App/assets/78819774/0be4c6a6-9e62-47ca-b807-5f4fd9f9f215

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~0102fdf94fdad3d721</li>
        <li>Upwork Job ID: 1801255717183191652</li>
        <li>Last Price Increase: 2024-06-13</li>
<li>Automatic offers: </li>
<ul>
<li>hungvu193 | Reviewer | 102725541</li>
</ul></li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @hungvu193</details>

**Comment by lanitochka17** [comment] 2024-06-13 13:35
@flodnv  FYI I haven't added the External label as I wasn't 100% sure about this issue. Please take a look and add the label if you agree it's a bug and can be handled by external contributors

**Comment by flodnv** [comment] 2024-06-13 14:08
I was able to reproduce, not sure what caused this, posted here: https://expensify.slack.com/archives/C01GTK53T8Q/p1718287685135869?thread_ts=1718285665.504579&cid=C01GTK53T8Q

**Comment by bernhardoj** [comment] 2024-06-13 14:54
Same root cause as https://github.com/Expensify/App/issues/43657

**Comment by flodnv** [comment] 2024-06-13 14:57
Thanks for pointing that out @bernhardoj 🙇

**Comment by luacmartins** [comment] 2024-06-13 19:10
I removed C+ assignment since this is already being handled in [this issue](https://github.com/Expensify/App/issues/43657)

**Comment by mountiny** [comment] 2024-06-14 12:58
This is fixed now, we can close it as payments are handled here https://github.com/Expensify/App/issues/43657

**Closed by mountiny** 2024-06-14 12:58 UTC
Labels: Reviewing, External, Engineering, Daily
