### ISSUE TITLE
[HOLD for payment 2023-06-13] [$1000] Android - Room details - Welcome message can be inputted only from the middle of Welcome message section

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#19698] opened 2023-05-26 21:33 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Issue found when executing PR** https://github.com/Expensify/App/pull/18662

## Action Performed:
1. Login to NewDot
2. Create new room
3. Go to room settings
4. Tap Welcome message
5. Start typing

## Expected Result:
Typed text of welcome message should appear from the top of corresponding section

## Actual Result:
Typed text of welcome message appears from the middle of corresponding section

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [ ] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 1.3.19.2

**Reproducible in staging?:** yes

**Reproducible in production?:** no

**If this was caught during regression testing, add the test name, ID and link from TestRail:**

**Email or phone of affected tester (no customers):**

**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Notes/Photos/Videos:** Any additional supporting documentation

https://platform.applause.com/services/links/v1/external/87f6f9931f00f24607b5541cf30f2be5e2f0389d45870a7fba372af2c5abc45a

**Expensify/Expensify Issue URL:**

**Issue reported by:** Applause - Internal Team

**Slack conversation:**

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~017d6b7a4c0773819c</li>
        <li>Upwork Job ID: 1663614088285298688</li>
        <li>Last Price Increase: 2023-05-30</li>
    </ul>
</details>

**Comment by ahmedGaber93** [comment] 2023-05-26 22:10
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
Room details - Welcome message can be inputted only from the middle of Welcome message section
### What is the root cause of that problem?
There is no trim for welcomeMessage here before saving 

https://github.com/Expensify/App/blob/a6e6fe9252af0d3cc19966abaf550e5eba5a466c/src/pages/ReportWelcomeMessagePage.js#L46-L48
### What changes do you think we should make in order to solve the problem?
Trim value before saving

### What alternative solutions did you explore? (Optional)

**Comment by hungvu193** [comment] 2023-05-29 08:55
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
Android - Room details - Welcome message can be inputted only from the middle of Welcome message section 
### What is the root cause of that problem?
We are using multilines TextInput for welcome message, but we didn't set the textAlignVertical for it yet, so when we clicked the input on Android, the cursor will be displayed at the center.
https://github.com/Expensify/App/blob/eaf31460e1be0ac177a49a56fe473462e25b655c/src/pages/ReportWelcomeMessagePage.js#L75-L79
### What changes do you think we should make in order to solve the problem?
We should add the `textAlignVertical: top` props to the TextInput to make sure the cursor will be at the top.
```javascript
                        <TextInput
                            inputID="welcomeMessage"
                            label={props.translate('welcomeMessagePage.welcomeMessage')}
                            multiline
                            numberOfLines={10}
                            maxLength={CONST.MAX_COMMENT_LENGTH}
                            ref={welcomeMessageInputRef}
                            value={welcomeMessage}
                            onChangeText={handleWelcomeMessageChange}
                            autoCapitalize="none"
                            textAlignVertical="top"
                        />
```

### What alternative solutions did you explore? (Optional)
N/A

### Result

https://github.com/Expensify/App/assets/16502320/1c294930-1681-48c3-91be-87914d6aa735

**Comment by Beamanator** [comment] 2023-06-02 18:02
Agreed @fedirjh 👍

**Comment by trjExpensify** [comment] 2023-06-15 19:05
Sounds good! Offers [here](https://www.upwork.com/jobs/~017d6b7a4c0773819c). 

$1,500 - @fedirjh for C+ 
$1,500 - @hungvu193 for the bug fix

**Comment by trjExpensify** [comment] 2023-06-15 19:43
@fedirjh - paid!

**Comment by trjExpensify** [comment] 2023-06-16 16:50
@hungvu193 paid! All done here, closing. Thanks!

**Closed by trjExpensify** 2023-06-16 16:50 UTC
Labels: External, Daily, Awaiting Payment, Bug
