### ISSUE TITLE
[$500]  Message has a higlighted background when Delete message is canceled

### ISSUE THREAD

**Issue by m-natarajan** [Expensify/App#28869] opened 2023-10-04 22:41 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:

1. Send multiple message in a chat.
2. Right click on a message to show popover menu.
3. Click on Delete message
4. Cancel the delete message

## Expected Result: 
Message should not have highlighted background
## Actual Result:
Message has highlighted background

## Workaround:
unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [x] Android / Chrome
- [x] iOS / native
- [x] iOS / Safari
- [x] MacOS / Chrome / Safari
- [x] MacOS / Desktop

**Version Number:** 1.3.77-6
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/38435837/52de3719-9537-4805-b90b-41fb68737ad8

https://github.com/Expensify/App/assets/38435837/2a24c0ea-dd5f-479c-9da0-9a17778245b4

https://github.com/Expensify/App/assets/38435837/33fe87ed-27d2-4851-a01b-1c1c56f17115

https://github.com/Expensify/App/assets/38435837/03942eaf-ce41-4fb6-a139-f8d196f408b6

**Expensify/Expensify Issue URL:**
**Issue reported by:** @ishpaul777
**Slack conversation:** 
https://expensify.slack.com/archives/C049HHMV9SM/p1696418330096069
[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01d2135619eda07bc2</li>
        <li>Upwork Job ID: 1709700326616563712</li>
        <li>Last Price Increase: 2023-10-11</li>
    </ul>
</details>

**Comment by s-alves10** [comment] 2023-10-04 22:56
This is a dupe of https://github.com/Expensify/App/issues/28029

**Comment by Gabriel-Freire6** [comment] 2023-10-05 00:07
This is likely a react hover::enabled problem, I think I can find it and fixed for all platforms, let me know if I can post the proposal on upwork.

**Comment by Gabriel-Freire6** [comment] 2023-10-05 00:11
I already found a problem on your homepage 
![image](https://github.com/Expensify/App/assets/129862212/82164e16-2186-47d2-a229-b506f32f1905)
'expensify' on the bottom is cropped

**Comment by Gabriel-Freire6** [comment] 2023-10-05 00:13
This is likely a react hover::enabled problem, I think I can find it and fixed for all platforms, let me know if I can post the proposal on upwork.

Contributor details
Your Expensify account email: gfcf441+expensify@gmail.com
Upwork Profile Link: https://www.upwork.com/freelancers/~012041c7bdc9bc2bdb

**Comment by ayazalavi** [comment] 2023-10-05 02:56
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
When right clicking any chat and clicking on delete comment, after closing modal chat stays highlighted.

### What is the root cause of that problem?
The root cause of the problem arises when we click "delete comment," which closes the context menu. This results in the following two callbacks being called:

1. First, the onHide callback of the context menu is fired.
2. Then, the isActiveReportAction useEffect gets fired due to the fact that the popover keeps the report item in an active state.

The above sequence of events results in the report context menu staying active because the second callback mentioned above keeps it in a true state.

You can find the relevant code here:
https://github.com/Expensify/App/blob/6d86d5aecc47096bffdfbf59dcaefcb5dd0a0509/src/pages/home/report/ReportActionItem.js#L149

Now, when the popover gets closed, we are not updating isActiveReportActionForMenu since the report is no longer in an active state. This results in the context menu remaining in a true state from above keeping chat to stay highlighted.
https://github.com/Expensify/App/blob/6d86d5aecc47096bffdfbf59dcaefcb5dd0a0509/src/pages/home/report/ReportActionItem.js#L131

### What changes do you think we should make in order to solve the problem?

We need to ensure that these lines of code are called as soon as the popover is closed to maintain the latest active state of the report. You can find these lines of code here:
https://github.com/Expensify/App/blob/6d86d5aecc47096bffdfbf59dcaefcb5dd0a0509/src/pages/home/report/ReportActionItem.js#L147-L150

To achieve this, we can track the modal's visible state by adding ONYXKEYS.MODAL:

```javascript
modal: {
    key: ONYXKEYS.MODAL
},
```

You can make this change here:
https://github.com/Expensify/App/blob/6d86d5aecc47096bffdfbf59dcaefcb5dd0a0509/src/pages/home/report/ReportActionItem.js#L689

Additionally, update the memo callback to include:

```javascript
prevProps.modal.isVisible === nextProps.modal.isVisible
```

You can make this update here:
https://github.com/Expensify/App/blob/6d86d5aecc47096bffdfbf59dcaefcb5dd0a0509/src/pages/home/report/ReportActionItem.js#L707

This will help maintain the active state of the report and update the component accordingly.

https://github.com/Expensify/App/assets/767439/2f5e8dd4-771c-4da1-b8a0-79bea32d879d

### What alternative solutions did you explore? (Optional)
N/A

**Comment by s-alves10** [comment] 2023-10-10 11:59
https://github.com/Expensify/App/issues/28869#issuecomment-1747758642

**Comment by cubuspl42** [comment] 2023-10-11 08:05
> This is a dupe of #28029

@sakluger This indeed looks like a dupe

**Comment by sakluger** [comment] 2023-10-13 17:57
Yeah sorry for the delay, @s-alves10 is correct that this is a duplicate of https://github.com/Expensify/App/issues/28029.

**Closed by sakluger** 2023-10-13 17:57 UTC
Labels: External, Daily, Help Wanted, Overdue, Bug
