### ISSUE TITLE
mWeb/Safari - Emoji Picker - Emoji search field is not focused

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#43965] opened 2024-06-18 22:01 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.85-0
**Reproducible in staging?:** Y
**Reproducible in production?:** Y 
**If this was caught during regression testing, add the test name, ID and link from TestRail:** N/A
**Issue reported by:** Applause - Internal Team

## Action Performed:
1. Navigate to a conversation
2. Open the emoji picker

## Expected Result:
The search field is auto-focused

## Actual Result:
The search field is not auto-focused

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [x] iOS: mWeb Safari
- [ ] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details> 

https://github.com/Expensify/App/assets/78819774/9d1f80d6-0f6b-4a9b-9825-9235c2934415

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by lanitochka17** [comment] 2024-06-18 22:02
@VictoriaExpensify  FYI I haven't added the External label as I wasn't 100% sure about this issue. Please take a look and add the label if you agree it's a bug and can be handled by external contributors

**Comment by lanitochka17** [comment] 2024-06-18 22:02
We think that this bug might be related to #vip-vsp

**Comment by abzokhattab** [comment] 2024-06-18 22:17
This is the expected behavior according to this comment: https://github.com/Expensify/App/blob/7d8dbc418aea0f0e5b54ebb425a3e7b4b90178ce/src/components/EmojiPicker/EmojiPickerMenu/index.tsx#L58-L60

**Comment by VictoriaExpensify** [comment] 2024-06-24 00:57
Since this is expected behaviour, I'm getting some input on whether it is the _preferred_ behaviour

https://expensify.slack.com/archives/C01GTK53T8Q/p1719190631083709

**Comment by VictoriaExpensify** [comment] 2024-06-25 05:26
Bumped the above post since I haven't had a response yet

**Comment by VictoriaExpensify** [comment] 2024-07-01 21:17
There are some reasons for this being the preferred behaviour:

> I think it was that auto-focusing requires a tap to remove focus from the picker, so if you see the emoji that you want on-open you need to tap it twice to actually add in


> my only thought is that by autofocusing the input, that means the keyboard will also automatically show which will make the emoji picker + keyboard take up basically the entire screen?


Closing this out

**Closed by VictoriaExpensify** 2024-07-01 21:17 UTC
Labels: Daily, Overdue, Bug
