### ISSUE TITLE
[HOLD for payment 2023-08-02] [$1000] Web - Assignee and share somewhere deep link closes RHN on selection even though it intiates changes

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#22290] opened 2023-07-05 18:32 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Open the app
2. Click plus and click on 'Assign task'
3. Enter any title and click on next
4. Click on assignee and copy the URL
5. Close the RHN, paste URL in any report and send
6. Click on the URL from report and click on any user in assignee list, observe that it closes RHN
7. Again click on URL and click on back, observe that assignee selected in step 6 was saved

## Expected Result:
 App should not close the RHN menu on selection of assignee or selection of user in share somewhere

## Actual Result:
App closes the RHN menu on selection of assignee or selection of user in share somewhere when assignee and share somewhere pages are opened using deep link

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [x] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 1.3.36-4
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/93399543/cf65babb-f1a2-4ddb-84b5-7bf289a5b214

https://github.com/Expensify/App/assets/93399543/4bda56be-b949-481a-88c7-58e618da8f70

**Expensify/Expensify Issue URL:**
**Issue reported by:** GH handle - @dhanashree-sawant
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1688486902490709
 
[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01d444ffece6132556</li>
        <li>Upwork Job ID: 1676994558637928448</li>
        <li>Last Price Increase: 2023-07-13</li>
    </ul>
</details>

**Comment by Israr-ul-haq** [comment] 2023-07-06 19:56
Hi I saw the job on upwork I think I can help you with this if you want me to contribute in this issue

**Comment by Israr-ul-haq** [comment] 2023-07-06 20:10
Contributor details
Your Expensify account email: israrulhaq764@gmail.com
Upwork Profile Link: https://www.upwork.com/freelancers/~018c6121572f1b951c

**Comment by isabelastisser** [comment] 2023-07-10 10:37
Waiting for more proposals.

**Comment by abdulrahuman5196** [comment] 2023-07-12 20:36
Will review the proposal in the morning

**Comment by Israr-ul-haq** [comment] 2023-07-13 17:56
Hi , If you need any help from me to resolve this issue let me know if i can help you

**Comment by abdulrahuman5196** [comment] 2023-07-15 08:03
@Israr-ul-haq  Kindly follow our [contributing guidelines](https://github.com/Expensify/App/blob/main/contributingGuides/CONTRIBUTING.md)  and provide a proposal as per our [proposal template ](https://raw.githubusercontent.com/Expensify/App/main/contributingGuides/PROPOSAL_TEMPLATE.md)

**Comment by abdulrahuman5196** [comment] 2023-07-15 08:10
@dukenv0307 's proposal here https://github.com/Expensify/App/issues/22290#issuecomment-1622272265 looks good and works well.

Nit: @dukenv0307 For future issues, kindly add more information on root cause.

🎀 👀 🎀
C+ Reviewed

cc: @isabelastisser

**Comment by abdulrahuman5196** [comment] 2023-07-15 08:11
@neil-marcellini C+ approved comment is here - https://github.com/Expensify/App/issues/22290#issuecomment-1636705933

**Comment by abdulrahuman5196** [comment] 2023-07-18 11:59
@neil-marcellini Waiting on you for this - https://github.com/Expensify/App/issues/22290#issuecomment-1636705933

**Comment by isabelastisser** [comment] 2023-07-19 15:45
@neil-marcellini can you please review @dukenv0307 proposal? Thanks! 

> https://github.com/Expensify/App/issues/22290#issuecomment-1622272265

**Comment by neil-marcellini** [comment] 2023-07-19 17:28
Yes sorry. This somehow slipped through the cracks. There's a lot going on right now but I'll put it on my list for today.

**Comment by neil-marcellini** [comment] 2023-07-19 21:11
I like @dukenv0307 's proposal https://github.com/Expensify/App/issues/22290#issuecomment-1622272265 too, very simple 👍.

I've seen this pattern a few times where Navigation.goBack() causes problems. Maybe we should add something to the checklists about only using it when you want to go back in the navigation stack specifically vs going back to a specific screen.

**Comment by abdulrahuman5196** [comment] 2023-08-01 18:54
>The PR that introduced the bug has been identified. Link to the PR:
The offending PR has been commented on, pointing out the bug it caused and why, so the author and reviewers can learn from the mistake. Link to comment:

Not a regression. Seems to present from the task implementation.

>A discussion in #expensify-bugs has been started about whether any other steps should be taken (e.g. updating the PR review checklist) in order to catch this type of bug sooner. Link to discussion:

https://expensify.slack.com/archives/C049HHMV9SM/p1690915949087489

>Determine if we should create a regression test for this bug.
If we decide to create a [regression test](https://github.com/Expensify/App/blob/main/contributingGuides/REGRESSION_TEST_BEST_PRACTICES.md) for the bug, please propose the regression test steps to ensure the same bug will not reach production again.

No. Regression test won't be beneficial here since its a corner case. 

@isabelastisser

**Comment by isabelastisser** [comment] 2023-08-03 18:23
Payment summary:

Issue reported by xIssue reported by @dhanashree-sawant $250
C+ Review: @abdulrahuman5196 $1000
Issue fixed by: @dukenv0307 $1000

Assigned to @dukenv0307 on July 19
Deployed on July 26
Not eligible for urgency bonus

**Comment by abdulrahuman5196** [comment] 2023-08-03 18:29
@isabelastisser Its not the deployment time. But the PR approved/merged time which makes the issue eligible for bonus.

PR assigned - 20/7 2:41 AM
C+ approval - 22/7 9:45 PM
Merge - 25/7 12:51 AM

In between 2 days non-working days. So the PR is within 3 days bonus periods

**Comment by isabelastisser** [comment] 2023-08-03 18:44
Thanks for following up on this @abdulrahuman5196!

Context:

Payment amounts are variable, dependent on when the PR was merged. Payment timeline all based on the day the contributor has an accepted proposal and is assigned to the Github issue.
- Merged PR within 3 business days and no regressions - 50% bonus 

- Contributor assigned on July 19, 5:11PM EDT
Merged July 24 3:21PM EDT

I will issue the bonus in Upwork now.

**Comment by isabelastisser** [comment] 2023-08-03 18:50
All set!

**Closed by isabelastisser** 2023-08-03 18:50 UTC
Labels: External, Daily, Awaiting Payment, Bug
