### ISSUE TITLE
[$1000] Dev: Web - Console log error on clicking 'Description'

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#22823] opened 2023-07-13 16:54 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Open an existing chat
2. Click on '+' icon
3. Click on 'Assign task' button
4. Enter title & description > click on 'Next'
5. Click on 'Confirm task' button
6. Click on 'Description'

## Expected Result:
There should be no console log error

## Actual Result:
Console log error displayed [TextInput contains a textarea with both value and defaultValue props.]

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [x] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** Dev 1.3.39-8
**Reproducible in staging?:** n/a
**Reproducible in production?:** n/a
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/93399543/1639eb3f-498e-4a24-8686-89ea3547138d

**Expensify/Expensify Issue URL:**
**Issue reported by:** @Natnael-guchima
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1689172593965979

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01f075b8ea28c0e303</li>
        <li>Upwork Job ID: 1679840976501219328</li>
        <li>Last Price Increase: 2023-07-14</li>
    </ul>
</details>

**Comment by jfquevedol2198** [comment] 2023-07-13 19:33
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
Web - Console log error on clicking 'Description'

### What is the root cause of that problem?
`defaultValue` in `TextInput` component was used

https://github.com/Expensify/App/blob/9b205fbb26aeafea690b62412d00fd1aa5529bde/src/pages/tasks/TaskDescriptionPage.js#L68-L80

### What changes do you think we should make in order to solve the problem?
Instead of `defaultValue`, need to use `value` for `controlled input`

### What alternative solutions did you explore? (Optional)
N/A

**Comment by dylanexpensify** [comment] 2023-07-14 11:54
posted in slack to have repro'd

**Comment by situchan** [comment] 2023-07-14 13:35
Will be fixed in https://github.com/Expensify/App/pull/22589

**Closed** 2023-07-17 09:18 UTC
Labels: External, Daily, Help Wanted, Overdue, Bug
