### ISSUE TITLE
Workspace rooms details page display user list in place of room name

### ISSUE THREAD

**Issue by kavimuru** [Expensify/App#23416] opened 2023-07-23 12:04 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Open the app
2. Open any workspace room report (eg room: #announce, #admin)
3. Click on header to open details page
4. Observe that on details page, app displays user list in place of room name before room profile
## Expected Result: 
App should display room name below room profile on room details page
## Actual Result: 
App displays user list instead of room name below room profile on room details page
## Workaround:
Can the user still use Expensify without this being fixed? Have you informed them of the workaround?

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android / native
- [x] Android / Chrome
- [x] iOS / native
- [x] iOS / Safari
- [x] MacOS / Chrome / Safari
- [x] MacOS / Desktop

**Version Number:** v1.3.44-0
**Reproducible in staging?:** y
**Reproducible in production?:** n
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/43996225/52d5dbb2-66eb-44ce-a1d5-005760c38bb4

**Expensify/Expensify Issue URL:**
**Issue reported by:** @dhanashree-sawant
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1690038296569129

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

![Snip - New Expensify - Google Chrome](https://github.com/Expensify/App/assets/43996225/e5e20d02-0514-45bf-bec1-cb4196103c04)

**Comment by BhuvaneshPatil** [comment] 2023-07-23 12:44
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
Workspace rooms details page display user list in place of room name

### What is the root cause of that problem?
This is caused by - https://github.com/Expensify/App/pull/23255

For showing full title we are using `shouldUseFullTitle` prop.
https://github.com/Expensify/App/blob/b7d17e0fd33b83e9fbd45146b6123b6323ece79e/src/pages/ReportDetailsPage.js#L152-L159

For calculating that we are using - 

!isPolicyExpenseChat(report) && !isChatRoom(report) && !isChatThread(report)


Before this we used - `isChatRoom || isPolicyExpenseChat || isThread` for displaying full title.

### What changes do you think we should make in order to solve the problem?
We shall change -

https://github.com/Expensify/App/blob/b7d17e0fd33b83e9fbd45146b6123b6323ece79e/src/pages/ReportDetailsPage.js#L158

to - `!shouldUseFullTitle`

### What alternative solutions did you explore? (Optional)
We can also change it to - `shouldUseFullTitle || ReportUtils.isTaskReport(props.report)`

**Comment by mananjadhav** [comment] 2023-07-23 14:02
This [PR](https://github.com/Expensify/App/pull/23358) is open to resolve the regression from https://github.com/Expensify/App/issues/22997.

cc - @cristipaval @maddylewis

**Comment by marcaaron** [comment] 2023-07-25 18:24
The fix for this here was deployed yesterday so I think the blocker is resolved here.

**Comment by arosiclair** [comment] 2023-07-27 16:02
This issue was already fixed by [this PR](https://github.com/Expensify/App/pull/23358). 

The bug was a regression from a contributor trying to fix another [issue](https://github.com/Expensify/App/issues/22997).  The same contributor and C+ (@ginsuma and @robertKozik) pushed out this fix so, in this case, I think there's no extra payment necessary. That sounds right to you @maddylewis?

**Comment by dhanashree-sawant** [comment] 2023-07-28 05:36
Hi @arosiclair, @maddylewis, If this issue helped to change that PR for fix, will it be eligible for reporting bouns?

**Comment by arosiclair** [comment] 2023-07-28 17:10
Not in this case. The issue was already known before you reported it. (PR was posted Jul 21 and you posted on slack Jul 22)

**Comment by maddylewis** [comment] 2023-07-29 12:46
> The bug was a regression from a contributor trying to fix another https://github.com/Expensify/App/issues/22997. The same contributor and C+ (@ginsuma and @robertKozik) pushed out this fix so, in this case, I think there's no extra payment necessary. That sounds right to you @maddylewis?

@arosiclair - got it! thanks for the breakdown. are we now waiting for the 7-day regression period to pass before closing this one out?

**Comment by arosiclair** [comment] 2023-07-31 15:28
Don't think that's needed either we can just use the main issue #22997. Closing this out in favor of that one

**Closed by arosiclair** 2023-07-31 15:28 UTC
Labels: Engineering, Daily, Bug
