### ISSUE TITLE
[HOLD for payment 2024-06-06] [$500] Can't select mention when there is a single item

### ISSUE THREAD

**Issue by rlinoz** [Expensify/App#40508] opened 2024-04-18 21:42 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.63-0
**Reproducible in staging?:**
**Reproducible in production?:**
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:**
**Slack conversation:**

## Action Performed:
Break down in numbered steps
1. Start trying to mention a user in a room
2. Narrow it down to 1 user only
3. Try to tap on it

## Expected Result:
Describe what you think should've happened
User should be selected and auto complete closed

## Actual Result:
Describe what actually happened
Nothing happens no tap.

## Workaround:
Can the user still use Expensify without this being fixed? Have you informed them of the workaround?

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [x] iOS: Native
- [ ] iOS: mWeb Safari
- [ ] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

https://github.com/Expensify/App/assets/5201282/c21dfb14-f620-455b-9f32-f7a75567ccae

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01e879d520febf1253</li>
        <li>Upwork Job ID: 1781370564759228416</li>
        <li>Last Price Increase: 2024-05-21</li>
<li>Automatic offers: </li>
<ul>
<li>dukenv0307 | Reviewer | 0</li>
</ul></li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @JmillsExpensify</details>

**Comment by puneetlath** [comment] 2024-04-19 16:16
@rlinoz should we make this external?

**Comment by rlinoz** [comment] 2024-04-19 17:13
Ops, yes we should.

**Comment by jingp-ofload** [comment] 2024-04-20 04:04
Solved.

```
commit b5377e48f4801ae1583c0c138f7e7b5b4f862eb5
Author: Jingtai Piao <piaojingtai@gmail.com>
Date:   Sat Apr 20 13:58:01 2024 +1000

    Fix mentioned suggestion list

diff --git a/src/components/AutoCompleteSuggestions/BaseAutoCompleteSuggestions.tsx b/src/components/AutoCompleteSuggestions/BaseAutoCompleteSuggestions.tsx
index ccd0f21626..1228d21143 100644
--- a/src/components/AutoCompleteSuggestions/BaseAutoCompleteSuggestions.tsx
+++ b/src/components/AutoCompleteSuggestions/BaseAutoCompleteSuggestions.tsx
@@ -1,10 +1,11 @@
+/* eslint-disable rulesdir/prefer-early-return */
 import {FlashList} from '@shopify/flash-list';
 import type {ForwardedRef, ReactElement} from 'react';
-import React, {forwardRef, useCallback, useEffect, useMemo, useRef} from 'react';
+import React, {forwardRef, useCallback, useEffect, useMemo, useRef, useState} from 'react';
 import type {View} from 'react-native';
 // We take ScrollView from this package to properly handle the scrolling of AutoCompleteSuggestions in chats since one scroll is nested inside another
 import {ScrollView} from 'react-native-gesture-handler';
-import Animated, {Easing, FadeOutDown, useAnimatedStyle, useSharedValue, withTiming} from 'react-native-reanimated';
+import Animated, {Easing, FadeOutDown, runOnJS, useAnimatedStyle, useSharedValue, withTiming} from 'react-native-reanimated';
 import ColorSchemeWrapper from '@components/ColorSchemeWrapper';
 import PressableWithFeedback from '@components/Pressable/PressableWithFeedback';
 import useStyleUtils from '@hooks/useStyleUtils';
@@ -76,12 +77,18 @@ function BaseAutoCompleteSuggestions<TSuggestion>(
         }),
         [isLargeScreenWidth, suggestions.length, windowWidth],
     );
+
+    const [data, setData] = useState<TSuggestion[]>([]);
     useEffect(() => {
-        rowHeight.value = withTiming(measureHeightOfSuggestionRows(suggestions.length, isSuggestionPickerLarge), {
-            duration: 100,
-            easing: Easing.inOut(Easing.ease),
-        });
-    }, [suggestions.length, isSuggestionPickerLarge, rowHeight]);
+        rowHeight.value = withTiming(
+            measureHeightOfSuggestionRows(suggestions.length, isSuggestionPickerLarge),
+            {
+                duration: 100,
+                easing: Easing.inOut(Easing.ease),
+            },
+            (finished) => finished && runOnJS(setData)(suggestions),
+        );
+    }, [suggestions, isSuggestionPickerLarge, rowHeight]);
 
     useEffect(() => {
         if (!scrollRef.current) {
@@ -101,8 +108,9 @@ function BaseAutoCompleteSuggestions<TSuggestion>(
                     estimatedItemSize={CONST.AUTO_COMPLETE_SUGGESTER.SUGGESTION_ROW_HEIGHT}
                     estimatedListSize={estimatedListSize}
                     ref={scrollRef}
+                    disableAutoLayout
                     keyboardShouldPersistTaps="handled"
-                    data={suggestions}
+                    data={data}
                     renderItem={renderItem}
                     renderScrollComponent={ScrollView}
                     keyExtractor={keyExtractor}
```

**Comment by jp928** [comment] 2024-04-20 04:58
Contributor details Your Expensify account email: piaojingtai@gmail.com Upwork Profile Link: https://www.upwork.com/freelancers/~01a3ce7f9619e1a922?viewMode=1

**Comment by jp928** [comment] 2024-04-22 03:08
Closed. Sry for that

**Comment by jp928** [comment] 2024-04-23 07:22
@dukenv0307 anybody review my proposal on upwork? I am stuck.

**Comment by jp928** [comment] 2024-04-23 08:10
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
In a workspace, when there is only one mentioned contact in the list, the contact is not clickable.

### What is the root cause of that problem?
There is rendering issue inside Flashlist (related hot it calculate the height of each item and render them) so that even though the component is visible but actually it is not interact-able.

### What changes do you think we should make in order to solve the problem?
Disable Flashlist auto layout and update the data props after the animation on the modal completed.

### What alternative solutions did you explore? (Optional)
Alternatively, use Flatlist instead.

**Comment by puneetlath** [comment] 2024-04-29 20:37
Increasing to $500. I think this is an important one to try and fix.

**Comment by jp928** [comment] 2024-04-30 00:26
I had a proposal on upword already but I don't have connect to re do it. Just post it here.

## Proposal

### Please re-state the problem that we are trying to solve in this issue.
In a workspace, when there is only one mentioned contact in the list, the contact is not clickable.

### What is the root cause of that problem?
The flashlist need time to calculate the position of the items, in this case, there is a animation in the component `src/components/AutoCompleteSuggestions/BaseAutoCompleteSuggestions.tsx` line 104, which will make the flashlist cannot calculate the item position correctly, see the implementation of flashlist on `ios/Sources/AutoLayoutView.swift` line  86. When the flashlist getting the layout, the parent view's height isn't completed from the animation yet. Even though the item is visible from the view, flashlist still treats it is not within the visible area. To approve my idea, simply apply fixed style on the `<Animated.View` like below 
```
<Animated.View
            ref={viewForwardedRef(ref)}
            style={[styles.autoCompleteSuggestionsContainer, {height: 50, top: -50}]}
            exiting={FadeOutDown.duration(100).easing(Easing.inOut(Easing.ease))}
        >
```
you will see the list's item is always clickable, especially when there is only one left.
 
### What changes do you think we should make in order to solve the problem?
set the `disableAutolayout=false`, probably with condition such as `Platform.os !== 'ios' , then set the flashlist data props after the animation complete.
```
   const animatedStyles = useAnimatedStyle(() => {
        runOnJS(setData)(suggestions);

        return StyleUtils.getAutoCompleteSuggestionContainerStyle(rowHeight.value);
    });
```     

### What alternative solutions did you explore? (Optional)
Alternatively, use Flatlist instead.

**Comment by ikevin127** [comment] 2024-04-30 01:15
I cannot reproduce on latest main! Am I miss-reproducing some of the steps ?
@dukenv0307 Can you reproduce ?

https://github.com/Expensify/App/assets/56457735/b39f3666-b9af-48d2-ae25-b8e862bc4b1a

Can we have a re-test of this issue ? I'm thinking this might've been fixed in the meantime by some of the new arch follow-ups from SWM.

**Comment by jp928** [comment] 2024-04-30 02:02
@ikevin127 to reproduce, just type more after @ til the result narrows down to only one.

**Comment by jp928** [comment] 2024-04-30 02:03
also, in your video some mentioned has overlapping already my proposal could fix it too.

**Comment by JmillsExpensify** [comment] 2024-05-01 19:58
Triaging to vip-vsb as a low.

**Comment by jp928** [comment] 2024-05-03 04:20
@dukenv0307 I am not expert on Swift side, but I do believe the cause is from `ios/Sources/AutoLayoutView.swift::fixLayout` needs to execute in our case, the condition `subviews.count > 1,` will make the list **bypass** re-sort and `clearGaps` when there is only one item in the list. The prop `disableAutoLayout=false` in my proposal actually enable the function.
The best solution could be raise an issue in flashlist repo with detailed use cases.

**Comment by rlinoz** [comment] 2024-05-15 13:30
Sounds good to me!

**Comment by JmillsExpensify** [comment] 2024-05-19 18:29
Awaiting confirmation of proposal

**Comment by puneetlath** [comment] 2024-05-21 16:29
@rlinoz shall we go forward with that one?

**Comment by JmillsExpensify** [comment] 2024-05-22 06:52
@roryabraham thoughts on the C+ proposal review?

**Comment by rlinoz** [comment] 2024-05-22 12:22
Yeah, I think we can go with the proposed solution. Let me take this one.

**Comment by jp928** [comment] 2024-05-23 03:19
@dukenv0307 Sure. Will do later today.

**Comment by jp928** [comment] 2024-06-07 01:41
> * Needs manual offer from BZ

@dukenv0307 I am not sure who would be the best person to ask for the manual offer. I do have a Upwork account proposed  on this.

**Comment by JmillsExpensify** [comment] 2024-06-07 04:52
Payment summary: 

 - Contributor: @jp928 $500
 - Contributor+: @dukenv0307 $500

**Comment by JmillsExpensify** [comment] 2024-06-07 04:57
@jp928 sent you an offer. Mind accepting. C+ offer is paid out!

**Comment by JmillsExpensify** [comment] 2024-06-07 05:04
All contributors paid out. Closing this one. Thanks!

**Closed by JmillsExpensify** 2024-06-07 05:04 UTC
Labels: External, Daily, Awaiting Payment, Bug
