### ISSUE TITLE
[LOW] [Splits] [$500] IOU - Both IOUs were settled when the user paid one IOU offline and then returned online

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#35288] opened 2024-01-28 15:00 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.32.2
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** Applause - Internal Team
**Slack conversation:**

## Action Performed:
1. Account B requested money from account A
2. Account A disabled the internet connection and paid the IOU
3. Account B requested money for the second time
4. Account A re-enabled the internet connection

## Expected Result:
Only one IOU should be paid when the user returns online, as the second IOU was created when the user was already online

## Actual Result:
Both IOUs were settled when the user paid one IOU offline and then returned online

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [x] Android: mWeb Chrome
- [x] iOS: Native
- [x] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details> 

https://github.com/Expensify/App/assets/78819774/6b051281-f1a0-4f4b-a91d-2c21c47b7ebc

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01a476f4ff2923c49c</li>
        <li>Upwork Job ID: 1751621383657607168</li>
        <li>Last Price Increase: 2024-02-04</li>
    </ul>
</details>

**Comment by c3024** [comment] 2024-01-29 14:58
Thanks for digging. That makes sense.

This needs `Internal` label as well to identify exactly how we should go about.

**Comment by JmillsExpensify** [comment] 2024-01-31 17:32
Yes, I agree that this needs to be internal. I will add to the relevant internal project and we can get someone involved.

**Comment by JmillsExpensify** [comment] 2024-02-07 02:38
Floated internally.

**Comment by JmillsExpensify** [comment] 2024-02-14 03:28
Still waiting for someone internal to pick this up.

**Comment by JmillsExpensify** [comment] 2024-02-21 01:39
Same as above. This is in our internal project and waiting to be picked up.

**Comment by JmillsExpensify** [comment] 2024-03-06 04:38
Still waiting to be picked up by internal. It's on the project board and has been highlighted internally.

**Comment by JmillsExpensify** [comment] 2024-03-13 04:28
Still waiting to be picked up as part of vip-split.

**Comment by JmillsExpensify** [comment] 2024-03-20 02:44
Still looking for internal volunteers in the weekly VIP Split update.

**Comment by JmillsExpensify** [comment] 2024-03-27 04:15
Moving this to monthly. Waiting for someone internal to pick this up.

**Comment by mvtglobally** [comment] 2024-03-28 04:29
Issue not reproducible during KI retests. (First week)

**Comment by JmillsExpensify** [comment] 2024-05-01 04:14
Asked for a re-test to see if this is no longer reproducible.

**Comment by kavimuru** [comment] 2024-05-01 14:44
Unable to reproduce now.

https://github.com/Expensify/App/assets/43996225/2f7f959b-7103-441e-9b28-b9a42769e611
https://github.com/Expensify/App/assets/43996225/03b20717-44ad-4b1b-befb-e7fa3185d194

**Closed** 2024-05-01 15:23 UTC
Labels: Engineering, Monthly, Internal, Bug, Hot Pick
