### ISSUE TITLE
[HOLD for 46200] Expense - In offline, on creating 2nd expense, receipt placeholder is not greyed out

### ISSUE THREAD

**Issue by IuliiaHerets** [Expensify/App#49174] opened 2024-09-13 13:23 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** v9.0.34-2
**Reproducible in staging?:** Y 
**Reproducible in production?:** Y
**Issue reported by:** Applause Internal Team

## Action Performed:
1. Launch app -- Go offline
2. Tap fab -- submit expense
3. Enter an amount and tap next
4. Select a user
5. Tap submit expense
6. Open the expense created
7. Note the receipt placeholder is greyed out
8. Tap plus icon near compose
9. Create other expense
10. Now open the both expense
11.Note receipt placeholder is not greyed out

## Expected Result:
In offline, on creating 2nd expense, receipt placeholder must be greyed out.

## Actual Result:
In offline, on creating 2nd expense, receipt placeholder is not greyed out.

## Workaround:
Unknown

## Platforms:

- [x] Android: Native
- [x] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

https://github.com/user-attachments/assets/d0826981-953c-40e1-b3ac-773e0df6940d

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by IuliiaHerets** [comment] 2024-09-13 13:24
@stephanieelliott   FYI I haven't added the External label as I wasn't 100% sure about this issue. Please take a look and add the label if you agree it's a bug and can be handled by external contributors

**Comment by FitseTLT** [comment] 2024-09-13 13:51
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
Expense - In offline, on creating 2nd expense, receipt placeholder is not greyed out

### What is the root cause of that problem?
When there is only one transaction the `MoneyRequestView` is displayed inside `OfflineWithFeedback`
https://github.com/Expensify/App/blob/00bc167940607f1418109f00e2b4e2d7d4ae858b/src/pages/home/report/ReportActionItemContentCreated.tsx#L151-L170
but when we add another transaction the iou report will have two requests so the request details view/MoneyRequestView will be displayed without OfflineWithFeedback here
https://github.com/Expensify/App/blob/00bc167940607f1418109f00e2b4e2d7d4ae858b/src/pages/home/report/ReportActionItemContentCreated.tsx#L107-L115
### What changes do you think we should make in order to solve the problem?

We need to be consistent on how we display the MoneyRequestView, so we have two option
1. we can display  the MoneyRequestView inside OfflineWithFeedback [here](https://github.com/Expensify/App/blob/00bc167940607f1418109f00e2b4e2d7d4ae858b/src/pages/home/report/ReportActionItemContentCreated.tsx#L107-L115)
```
<OfflineWithFeedback pendingAction={parentReportAction?.pendingAction}>
                        <MoneyRequestView
                            report={report}
                            shouldShowAnimatedBackground
                        />
                    </OfflineWithFeedback>
```
2. Or we should only display under OfflineWithFeedback [here](https://github.com/Expensify/App/blob/00bc167940607f1418109f00e2b4e2d7d4ae858b/src/pages/home/report/ReportActionItemContentCreated.tsx#L151-L170) for `isEmptyObject(transactionThreadReport)` case
### What alternative solutions did you explore? (Optional)

**Comment by FitseTLT** [comment] 2024-09-13 14:04
Edited by **proposal-police**: This proposal was **edited** at 2024-09-13 14:00:44 UTC.

## Proposal

### Please re-state the problem that we are trying to solve in this issue.
Expense - In offline, on creating 2nd expense, receipt placeholder is not greyed out

### What is the root cause of that problem?
When there is only one transaction the `MoneyRequestView` is displayed inside `OfflineWithFeedback`
https://github.com/Expensify/App/blob/00bc167940607f1418109f00e2b4e2d7d4ae858b/src/pages/home/report/ReportActionItemContentCreated.tsx#L151-L170
but when we add another transaction the iou report will have two requests so the request details view/MoneyRequestView will be displayed without OfflineWithFeedback here
https://github.com/Expensify/App/blob/00bc167940607f1418109f00e2b4e2d7d4ae858b/src/pages/home/report/ReportActionItemContentCreated.tsx#L107-L115
### What changes do you think we should make in order to solve the problem?

We need to be consistent on how we display the MoneyRequestView, so we have two option
1. we can display  the MoneyRequestView inside OfflineWithFeedback [here](https://github.com/Expensify/App/blob/00bc167940607f1418109f00e2b4e2d7d4ae858b/src/pages/home/report/ReportActionItemContentCreated.tsx#L107-L115)
```
<OfflineWithFeedback pendingAction={parentReportAction?.pendingAction}>
                        <ShowContextMenuContext.Provider value={contextValue}> 
                         <View> 
                              <MoneyRequestView 
                              report={report} 
                              shouldShowAnimatedBackground 
                              /> 
                             {renderThreadDivider} 
                         </View> 
                      </ShowContextMenuContext.Provider> 
</OfflineWithFeedback>
```
2. we can avoid displaying the MoneyRequestView under OfflineWithFeedback [here](https://github.com/Expensify/App/blob/00bc167940607f1418109f00e2b4e2d7d4ae858b/src/pages/home/report/ReportActionItemContentCreated.tsx#L151-L170) by applying OfflineWithFeedback only for the other components like MoneyReportView (we can also add it for `renderThreadDivider`)
```
   return transactionThreadReport && !isEmptyObject(transactionThreadReport) ? (
            <>
                <OfflineWithFeedback pendingAction={action.pendingAction}>
                    <MoneyReportView
                        report={report}
                        policy={policy}
                        isCombinedReport
                        shouldShowTotal={transaction ? transactionCurrency !== report.currency : false}
                        shouldHideThreadDividerLine={shouldHideThreadDividerLine}
                    />
                </OfflineWithFeedback>
                <ShowContextMenuContext.Provider value={contextValue}>
                    <View>
                        <MoneyRequestView
                            report={transactionThreadReport}
                            shouldShowAnimatedBackground={false}
                        />
                        {renderThreadDivider}
                    </View>
                </ShowContextMenuContext.Provider>
            </>
        ) : (
            <OfflineWithFeedback pendingAction={action.pendingAction}>
                <MoneyReportView
                    report={report}
                    policy={policy}
                    shouldHideThreadDividerLine={shouldHideThreadDividerLine}
                />
            </OfflineWithFeedback>
        )
```
### What alternative solutions did you explore? (Optional)

**Comment by nkdengineer** [comment] 2024-09-13 15:34
The same RCA with https://github.com/Expensify/App/issues/46200

**Comment by stephanieelliott** [comment] 2024-09-17 02:20
Oh yea sounds like it @nkdengineer, let's hold for https://github.com/Expensify/App/issues/46200

**Comment by stephanieelliott** [comment] 2024-09-24 09:11
Still holding for https://github.com/Expensify/App/issues/46200

**Comment by stephanieelliott** [comment] 2024-10-03 22:55
This is still held on https://github.com/Expensify/App/issues/46200. That issue just was merged to main though so we should be able to pick this back up soon

**Comment by stephanieelliott** [comment] 2024-10-15 00:05
I think this is no longer occurring, both expenses created while offline are greyed out now: 

<img width="767" alt="image" src="https://github.com/user-attachments/assets/1fcb7d11-9f07-46ba-abac-cf17d9c5e519">

**Closed by stephanieelliott** 2024-10-15 00:05 UTC
Labels: Weekly, Overdue, Bug
