### ISSUE TITLE
[HOLD for #47984]Copilot – 3-dots menu on Copilot does not response

### ISSUE THREAD

**Issue by IuliiaHerets** [Expensify/App#49547] opened 2024-09-20 17:55 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 9.0.39-0
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**Email or phone of affected tester (no customers):** applausetester+gm103129@applause.expensifail.com
**Issue reported by:** Applause Internal Team

## Action Performed:
1. Go to Account settings> Security> Add Copilot
2. Click on the 3-Dot menu of added Copilot

## Expected Result:
3-Dots menu should open

## Actual Result:
3-dots menu does not response

## Workaround:
Unknown

## Platforms:

- [x] Android: Native
- [x] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

https://github.com/user-attachments/assets/60fa1c9f-2655-40a4-a375-14b17881f8bc

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by IuliiaHerets** [comment] 2024-09-20 17:56
@johncschuster  FYI I haven't added the External label as I wasn't 100% sure about this issue. Please take a look and add the label if you agree it's a bug and can be handled by external contributors

**Comment by truph01** [comment] 2024-09-20 22:15
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
3-dots menu does not response

### What is the root cause of that problem?
- We are displaying the three dot as a icon, so click on it do nothing:
https://github.com/Expensify/App/blob/83835702a43ee9299475e406fa7aa10027e05584/src/pages/settings/Security/SecuritySettingsPage.tsx#L103-L104

### What changes do you think we should make in order to solve the problem?
1. We should remove:
https://github.com/Expensify/App/blob/83835702a43ee9299475e406fa7aa10027e05584/src/pages/settings/Security/SecuritySettingsPage.tsx#L103-L104

2. Add ```interactive``` prop to:
https://github.com/Expensify/App/blob/83835702a43ee9299475e406fa7aa10027e05584/src/pages/settings/Security/SecuritySettingsPage.tsx#L94
```
                interactive: !isEmptyObject(pendingAction)
```

### What alternative solutions did you explore? (Optional)

**Comment by truph01** [comment] 2024-09-20 22:18
It should be fixed in https://github.com/Expensify/App/pull/47984

**Comment by johncschuster** [comment] 2024-09-23 21:55
Thanks, @truph01! I've put this one on hold while we wait for that PR.

**Comment by johncschuster** [comment] 2024-09-26 20:41
Still holding

**Comment by johncschuster** [comment] 2024-09-30 21:58
Still holding

**Comment by johncschuster** [comment] 2024-10-03 21:13
Still holding

**Comment by johncschuster** [comment] 2024-10-07 21:35
Still on hold

**Comment by johncschuster** [comment] 2024-10-07 21:38
Still on hold

**Comment by johncschuster** [comment] 2024-10-11 20:26
It looks like the linked PR was just merged. Once deployed we should retest this one.

**Comment by johncschuster** [comment] 2024-10-15 21:50
Looks like the linked PR has been deployed to staging. @IuliiaHerets, can we get a retest on staging to see if this behavior persists?

**Comment by johncschuster** [comment] 2024-10-18 22:50
Asked for a retest

**Comment by kavimuru** [comment] 2024-10-19 16:30
Not reproducible 

https://github.com/user-attachments/assets/8e1f6a28-d397-4d96-9d30-e9132e56b07a

**Comment by johncschuster** [comment] 2024-10-22 02:05
Ok! In that case, let's close this one up 👍

**Closed by johncschuster** 2024-10-22 02:05 UTC
Labels: Daily, Weekly, Overdue, Bug
