### ISSUE TITLE
Carousel - Next button is displayed when opening last image in report

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#38837] opened 2024-03-22 20:44 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.56-0
**Reproducible in staging?:** Y
**Reproducible in production?:** N
**If this was caught during regression testing, add the test name, ID and link from TestRail:** N/A
**Email or phone of affected tester (no customers):** natnael.expensify+3@gmail.com
**Issue reported by:** Applause - Internal Team

## Action performed:
1. Send a public image using markdown. You can use the following markdown: holla ![off]https://images.unsplash.com/photo-1705467648979-f66c9584827a?q=80&w=2000&auto=format&fit=crop&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D
2. Click on '+' > Add attachment > send an image
3. Repeat step 1
4. Open the last sent image

## Expected Result:
Previous button should be displayed on Carousel

## Actual Result:
Next button is displayed on Carousel

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details> 

https://github.com/Expensify/App/assets/78819774/fd886c80-96b7-4b87-b967-8153834e2c75

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by lanitochka17** [comment] 2024-03-22 20:45
We think that this bug might be related to #vip-vsp

**Comment by lanitochka17** [comment] 2024-03-22 20:45
@hayata-suenaga  FYI I haven't added the External label as I wasn't 100% sure about this issue. Please take a look and add the label if you agree it's a bug and can be handled by external contributors

**Comment by situchan** [comment] 2024-03-22 21:02
Not blocker.
markdown image is new feature and still WIP of polish.
And this bug is known and planned to fix as follow-up.

**Comment by situchan** [comment] 2024-03-22 21:02
cc: @kidroca

**Comment by hayata-suenaga** [comment] 2024-03-25 15:19
@kidroca please feel free to close this issue if this regression is already tracked somewhere 😄 

let me know if you don't have a permission to close this issue 👍

**Comment by hayata-suenaga** [comment] 2024-03-26 15:43
okay I'll keep this as the tracking issue. Please link any PR that addresses this regressions once it's ready 🙇

**Comment by hayata-suenaga** [comment] 2024-04-02 15:53
@situchan, please let me know if there is a project that is tracking the markdown feature implementation.

**Comment by hayata-suenaga** [comment] 2024-04-05 20:55
changing the priority to weekly

**Comment by hayata-suenaga** [comment] 2024-04-08 16:22
this issue is used as a tracking issue for a regression for the ongoing markdown project

**Comment by hayata-suenaga** [comment] 2024-04-16 20:14
same as above

**Comment by hayata-suenaga** [comment] 2024-04-29 22:18
@situchan, please update on this when you come back from OOO 🙇

**Comment by hayata-suenaga** [comment] 2024-05-09 00:30
@situchan, I know you just came back from OOO but please provide an update on this issue when you have time 🙇

**Comment by hayata-suenaga** [comment] 2024-05-20 21:55
Waiting for @situchan's response 😄

**Comment by situchan** [comment] 2024-05-20 21:57
Since I was OOO for a while, I am not sure if this issue is being handled elsewhere.
Maybe @kidroca can answer

**Comment by kidroca** [comment] 2024-05-23 08:43
Hi team,

This is actually intended behavior. The attachment carousel removes duplicate attachments when `<img>` tags have the same `src`. Tapping on a thumbnail shared multiple times opens the carousel at the first instance, hence the next arrow is visible. This situation occurs when public images are attached using the Markdown image syntax, allowing users to attach the same source multiple times. Instead of displaying multiple instances of the same image, we only show the first one in the carousel.

Even if we didn't remove duplicates, we lack the information to detect which instance of the repeating image was opened. When tapping a thumbnail, the carousel searches for an attachment matching the `source` of the thumbnail. Since duplicates share the same `source`, the carousel opens at the first match.

There were some issues that arose after implementing the Markdown image syntax feature, but they were considered minor and perhaps not affecting real use cases. As David stated:

> "The others I think I'd like to experience before we bother solving."
> [Slack thread link](https://expensify.slack.com/archives/C01GTK53T8Q/p1711389997314559?thread_ts=1707270017.261459&cid=C01GTK53T8Q)

I haven't done any more work around Markdown images since then.

To address this, we can consider the following:

The `ImageRenderer` component, which renders thumbnails, has access to:
- Full image source (currently used to differentiate attachments)
- Report action ID (the report action containing the image)
- `tnode` (element information provided by the HTML parser)

We can update the `ImageRenderer` and related logic to also use `reportActionID` to uniquely identify attachments. To fully differentiate between attachments from the same action, we would need to use `tnode` information like `index`. These additional parameters would be forwarded along with the `source` to the Attachment Carousel to present the correct attachment.

However, we can't rely solely on `tnode` information. For example, the `index` doesn't match the element `index` identified in the Attachment Carousel, as the Carousel uses a simpler parser and skips plain text not wrapped by HTML tags.

We need someone to find a way to uniquely identify attachments. I've explored one path using available information, but someone else might try a different approach, such as modifying existing logic to pass more information, or double-checking my idea to identify any missed details.

**Comment by hayata-suenaga** [comment] 2024-05-23 17:46
@kidroca, than you for the detailed explanation!

> Tapping on a thumbnail shared multiple times opens the carousel at the first instance, hence the next arrow is visible.

This explains the issue!

> There were some issues that arose after implementing the Markdown image syntax feature, but they were considered minor and perhaps not affecting real use cases.

I agree with this and this issue can also be considered as a minor issue. Let's close this and if the real user really gets confused by this, we can always reopen this issue to fix it 😄

**Closed by hayata-suenaga** 2024-05-23 17:46 UTC
Labels: Engineering, Weekly
