### ISSUE TITLE
No error is displayed when billing is out of date and user submit an expense.

### ISSUE THREAD

**Issue by m-natarajan** [Expensify/App#42081] opened 2024-05-13 14:32 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.73-0
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** @rayane-djouah 
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1715515661620349

## Action Performed:

1. Login with an account that has billing information is out of date
2. Create a workspace
3. Open your own workspace chat
4. Submit an expense with local currency
5. Click on submit button

## Expected Result:
A red dot error should be displayed that reflect the api error:
Policy billing is out of date. Please visit your settings page on Expensify.com and update your billing information.
## Actual Result:
The Submit Report api command return an error response but no error is displayed in frontend, Pay with Expensify button shows briefly and then Submit button is displayed again.
## Workaround:
Can the user still use Expensify without this being fixed? Have you informed them of the workaround?

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [X] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

https://github.com/Expensify/App/assets/38435837/098d4288-26d3-4087-8044-b2caa7ec6d27

![No Error](https://github.com/Expensify/App/assets/38435837/cbb1e0cc-439c-46ed-ad7e-169475a97b7e)

Add any screenshot/video evidence

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by nkdengineer** [comment] 2024-05-14 09:09
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
The Submit Report api command return an error response but no error is displayed in frontend, Pay with Expensify button shows briefly and then Submit button is displayed again.

### What is the root cause of that problem?
We don't generate the submit action if the `approveMode` of the policy is `optional`. So when BE returns error, no action in `iouReport` has error and then no RBR appears in report preview.

https://github.com/Expensify/App/blob/b587bf7080291285cfcde8c9b6ef5f7538e63b27/src/libs/actions/IOU.ts#L6184
### What changes do you think we should make in order to solve the problem?
If we submit a report of a policy that has `approveMode` is `optional`, we can generate an error for iouReport or an error for report preview action  in `failureData` so the report preview can be displayed with RBR or showing an error,

https://github.com/Expensify/App/blob/b587bf7080291285cfcde8c9b6ef5f7538e63b27/src/libs/actions/IOU.ts#L6184

### What alternative solutions did you explore? (Optional)
NA

**Comment by JmillsExpensify** [comment] 2024-05-15 22:10
@MitchExpensify I tend to view this as a feature request, and one that we are going to address as part of your design doc. Thoughts?

**Comment by MitchExpensify** [comment] 2024-05-15 22:16
Yes any paywall situation should be solved in [Free trials & paywall in NewDot](https://docs.google.com/document/d/1skGyubv96LtirPTiCQC41jT6b65UCh0M6y_J3acqVAY/edit#heading=h.mnjguil21u0a)

**Comment by JmillsExpensify** [comment] 2024-05-15 22:35
Nice, closing.

**Closed by JmillsExpensify** 2024-05-15 22:35 UTC
Labels: Daily, Bug
