### ISSUE TITLE
[$250] [Polish] [Group Chats] Share code name does not match report title for Group Chats

### ISSUE THREAD

**Issue by marcaaron** [Expensify/App#39630] opened 2024-04-04 17:01 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:**
**Reproducible in staging?:**
**Reproducible in production?:**
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** @shawnborton 
**Slack conversation:** https://expensify.slack.com/archives/C05RECHFBEW/p1712152423672299

## Action Performed:
1. Create a Group Chat
2. Navigate to Details
3. Navigate to Share Code

## Expected Result:

Share Code name is consistent with report title

## Actual Result:

Share Code name is not consistent with report title

![image](https://github.com/Expensify/App/assets/32969087/e312609a-15da-4555-b392-1724fb5c26bd)

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~018cd9c13c0c4b5d35</li>
        <li>Upwork Job ID: 1775931707348549632</li>
        <li>Last Price Increase: 2024-04-04</li>
    </ul>
</details>

**Comment by louisdeb** [comment] 2024-04-04 19:05
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
Share code title (beneath QR) is inconsistent with group chat names.

### What is the root cause of that problem?
Title logic in `ShareCodePage` does not check for Group Chats or get Group Chat members.

### What changes do you think we should make in order to solve the problem?

Create a `ReportUtils.getTitle` function which checks whether a report is a group chat and makes a decision about what its title should be. This allows us to respect the existing `isReport` check in `ShareCodePage` and avoids code duplication between `HeaderView` and `ShareCodePage`. Refactoring the duplicated logic into `ReportUtils` results in not only more robust code, but in increased legibility in `HeaderView` and `ShareCodePage`.

`HeaderView`:
```ts
const title = ReportUtils.getTitle(report);
```

`ShareCodePage`:
```ts
const title = isReport ? ReportUtils.getTitle(report) : currentUserPersonalDetails.displayName ?? '';
```

### What alternative solutions did you explore? (Optional)
Introducing a second check `isGroupChat` in `ShareCodePage` was another possible solution, as long as a check for `isReport` was respected. However the code gained an extra layer of nesting, and it took 5 lines to define `title` safely. Furthermore, the `isGroupChat` logic would be repeated between the `HeaderView` and `ShareCodePage`.

**Comment by louisdeb** [comment] 2024-04-04 19:08
Contributor details
Your Expensify account email: mail@poundian.com
Upwork Profile Link: https://www.upwork.com/freelancers/~01f9d10bed07e88b07

**Comment by jayeshmangwani** [comment] 2024-04-04 21:35
@roryabraham @dylanexpensify We can Close or Hold this issue, as @gijoe0295 [mentioned](https://github.com/Expensify/App/issues/39630#issuecomment-2037870265) here, this is a dupe of https://github.com/Expensify/App/issues/39316

**Closed** 2024-04-05 17:58 UTC
Labels: External, Daily, Help Wanted, Bug
