### ISSUE TITLE
[HOLD for payment 2023-11-17] [$250] Clean the usage of double onyx call on profile page

### ISSUE THREAD

**Issue by techievivek** [Expensify/App#29165] opened 2023-10-10 09:32 UTC
# Problem
We currently have used a double onyx call on the profile page to subscribe to the DM chat report in order for notification preference to update correctly for the profile page. This was reported during PR review here: https://github.com/Expensify/App/pull/28200#issuecomment-1736658690

https://github.com/Expensify/App/blob/a63f853381cd6ea680c31ee24c7c72f02e2d1513/src/pages/ProfilePage.js#L306-L317

Discussed here: https://github.com/Expensify/App/pull/28200#discussion_r1351969208

# Why is this important?
Using a double Onyx subscription for any component is not a recommended practice so it would be nice to clean that up. Moreover, we have now enabled the notification preference option for all the chat reports so maybe we can create a separate component for the notification preference page and reuse that across various pages.

# Solution
Create a separate component for notification preference and get rid of the double onyx call on the profile page. Feel free to come up with your own solutions.

Here is a potential solution to the problem: https://github.com/Expensify/App/pull/28200#discussion_r1338051983

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~013768a6222352d168</li>
        <li>Upwork Job ID: 1711676109112000512</li>
        <li>Last Price Increase: 2023-10-24</li>
<li>Automatic offers: </li>
<ul>
<li>pradeepmdk | Contributor | 27435339</li>
</ul></li>
    </ul>
</details>

**Comment by techievivek** [comment] 2023-10-10 09:33
Bug0 triage checklist is not required for this GH, as this is just a code improvement issue.

**Comment by alexxxwork** [comment] 2023-10-10 09:34
Is it available without a proposal? I would like to take it.

**Comment by techievivek** [comment] 2023-10-10 09:42
I would appreciate it if you can share the proposal beforehand.

**Comment by pradeepmdk** [comment] 2023-10-10 09:45
### Proposal
### Please re-state the problem that we are trying to solve in this issue.
clean code

### What is the root cause of that problem?

double onyx is used

### What changes do you think we should make in order to solve the problem?
https://github.com/Expensify/App/blob/a63f853381cd6ea680c31ee24c7c72f02e2d1513/src/pages/ProfilePage.js#L306-L317
we should remove the second one and move to the above one

**Comment by techievivek** [comment] 2023-10-12 12:50
@burczu Can you please have a look at the above proposals. Thanks.

**Comment by techievivek** [comment] 2023-10-16 10:43
Gentle bump @burczu

**Comment by burczu** [comment] 2023-10-17 12:27
@techievivek I'm sorry, I was busy reviewing PR's - I'll get back to checking proposals soon.

**Comment by techievivek** [comment] 2023-10-19 13:11
Friendly bump @burczu

**Comment by burczu** [comment] 2023-10-20 10:40
@techievivek I'm sorry that it took me so long but I had to read all the mentioned comments and threads to get an understanding about the issue we are trying to solve here.

So, the issue here is that we have double `withOnyx` used because we are relying in the second one on the value added to props in the first one - is it correct. Then I think the change to the `react-native-onyx` introduced by this PR: https://github.com/Expensify/react-native-onyx/pull/385 could potentially allow us moving the key from the second `withOnyx` to the first one and this way getting rid of the second one, as @pradeepmdk suggested in [their proposal](https://github.com/Expensify/App/issues/29165#issuecomment-1754840362).

But first, I wonder how could I test it - if I understand correctly there should be some new option in `/settings/profile` related to notifications, am I right? I can't see such option so what do I need to do to enable it?

**Comment by burczu** [comment] 2023-10-23 12:38
not overdue

**Comment by techievivek** [comment] 2023-10-25 13:54
> So, the issue here is that we have double withOnyx used because we are relying in the second one on the value added to props in the first one - is it correct? 

Correct.

> But first, I wonder how could I test it - if I understand correctly there should be some new option in /settings/profile related to notifications, am I right? I can't see such option so what do I need to do to enable it?

You can navigate to any DM chat and access the profile of an user from the chat report and that should show you the notification preference option.

**Comment by johncschuster** [comment] 2023-10-26 19:55
@burczu ^^

**Comment by burczu** [comment] 2023-10-27 11:12
Ok, thanks @techievivek for the answer.

So I think the first solution from @pradeepmdk's [proposal](https://github.com/Expensify/App/issues/29165#issuecomment-1754840362) could potentially help fixing the issue and we could give it a try, as I wrote in my previous [comment](https://github.com/Expensify/App/issues/29165#issuecomment-1772505768).

🎀 👀 🎀 C+ reviewed

**Comment by techievivek** [comment] 2023-10-30 11:51
Not overdue, assigned the GH to @pradeepmdk

**Comment by burczu** [comment] 2023-10-31 13:02
Just to inform, I'll be ooo for the next few days and we'll be back on Monday, November 6th.

**Comment by pradeepmdk** [comment] 2023-11-21 06:09
bump for payment

**Comment by pradeepmdk** [comment] 2023-11-25 16:32
@johncschuster bump for payment

**Comment by techievivek** [comment] 2023-12-04 09:50
Gentle bump @johncschuster ^

**Comment by burczu** [comment] 2023-12-11 09:10
**BugZero Checklist:** The PR fixing this issue has been merged! The following checklist ([instructions](https://stackoverflow.com/c/expensify/questions/14574)) will need to be completed before the issue can be closed:

* [x]  [@burczu] The PR that introduced the bug has been identified. Link to the PR:

**This was just refactor of an existing feature.**

* [x]  [@burczu] The offending PR has been commented on, pointing out the bug it caused and why, so the author and reviewers can learn from the mistake. Link to comment:

**n/a**

* [x]  [@burczu] A discussion in #expensify-bugs has been started about whether any other steps should be taken (e.g. updating the PR review checklist) in order to catch this type of bug sooner. Link to discussion:

**n/a**

* [x]  [@burczu] Determine if we should create a regression test for this bug.

**As this was just a refactor, I guess we should expect regression tests for this feature: https://github.com/Expensify/App/issues/27394 should cover testing this issue.**

* [x]  [@burczu] If we decide to create a regression test for the bug, please propose the [regression test](https://github.com/Expensify/App/blob/main/contributingGuides/REGRESSION_TEST_BEST_PRACTICES.md) steps to ensure the same bug will not reach production again.
* [ ]  [@johncschuster] Link the GH issue for creating/updating the regression test once above steps have been agreed upon:

**Comment by pradeepmdk** [comment] 2023-12-13 02:21
@johncschuster bump for payment

**Comment by pradeepmdk** [comment] 2023-12-16 15:56
@techievivek can u help me for payment here

**Comment by johncschuster** [comment] 2023-12-18 15:03
Sorry I dropped the ball, @pradeepmdk. I'll get payment issued this morning.

**Comment by pradeepmdk** [comment] 2023-12-18 15:04
Thank you @johncschuster

**Comment by johncschuster** [comment] 2023-12-18 15:50
Payment has been issued! Thanks for your patience!

**Closed by johncschuster** 2023-12-18 15:50 UTC
Labels: External, Engineering, Weekly, FirstPick, Awaiting Payment, Bug
