### ISSUE TITLE
[$250] Expense - Leading zeros are not removed when returning to amount input page

### ISSUE THREAD

**Issue by kavimuru** [Expensify/App#43243] opened 2024-06-07 02:37 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.80-9
**Reproducible in staging?:** y
**Reproducible in production?:** n
**If this was caught during regression testing, add the test name, ID and link from TestRail:** https://expensify.testrail.io/index.php?/tests/view/4592856
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** Applause internal team
**Slack conversation:**

## Action Performed:
1. Go to staging.new.expensify.com
2. Go to FAB > Submit expense > Manual.
3. Enter many zeros, then any digit > Next.
4. Return to amount input page via back button.

## Expected Result:
The leading zeros will be removed.

## Actual Result:
The leading zeros are not removed.

## Workaround:
unknown
## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [x] Android: mWeb Chrome
- [x] iOS: Native
- [x] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

https://github.com/Expensify/App/assets/43996225/0f1a3f84-3862-4857-8009-7aae6a454384

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01d1b0565d440e64fb</li>
        <li>Upwork Job ID: 1799101354337638448</li>
        <li>Last Price Increase: 2024-06-07</li>
<li>Automatic offers: </li>
<ul>
<li>hungvu193 | Reviewer | 102719101</li>
<li>abzokhattab | Contributor | 102719103</li>
</ul></li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @hungvu193</details>

**Comment by kavimuru** [comment] 2024-06-07 02:37
@techievivek  FYI I haven't added the External label as I wasn't 100% sure about this issue. Please take a look and add the label if you agree it's a bug and can be handled by external contributors.

**Comment by kavimuru** [comment] 2024-06-07 02:38
We think this bug might be related to #wave-collect - Release 1

**Comment by neonbhai** [comment] 2024-06-07 04:07
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
Expense - Leading zeros are not removed when returning to amount input page

### What is the root cause of that problem?
This happens as in the Submit Expense flow we access the IOU amount page from here:
https://github.com/Expensify/App/blob/1426c4e4c3c8182d1f69cffb4ff6b2bb9e55f449/src/pages/iou/request/IOURequestStartPage.tsx#L166

This does not have the `shouldKeepUserInput` prop passed to it.


Since the prop is `false` by default:
https://github.com/Expensify/App/blob/1426c4e4c3c8182d1f69cffb4ff6b2bb9e55f449/src/pages/iou/request/step/IOURequestStepAmount.tsx#L74

The last param here is `false`, leading to the amount not being formatted. 
https://github.com/Expensify/App/blob/1426c4e4c3c8182d1f69cffb4ff6b2bb9e55f449/src/pages/iou/request/step/IOURequestStepAmount.tsx#L171

### What changes do you think we should make in order to solve the problem?
Since `<IOURequestStepAmount` is only accessed from the `IOURequestStartPage`, we can simply have the prop true by default.

https://github.com/Expensify/App/blob/1426c4e4c3c8182d1f69cffb4ff6b2bb9e55f449/src/pages/iou/request/step/IOURequestStepAmount.tsx#L74

```jsx
shouldKeepUserInput = false, 
```

### Alternatively
- We can pass `shouldKeepUserInput` [here](https://github.com/Expensify/App/blob/1426c4e4c3c8182d1f69cffb4ff6b2bb9e55f449/src/pages/iou/request/IOURequestStartPage.tsx#L166)

- We should also consider renaming the prop to `shouldFormatUserInput` to better reflect what its doing

**Comment by trjExpensify** [comment] 2024-06-07 09:53
Have we identified the PR on staging that caused this bug?

**Comment by luacmartins** [comment] 2024-06-07 15:11
I think [this PR](https://github.com/Expensify/App/pull/40062) caused the regression

**Comment by techievivek** [comment] 2024-06-07 15:28
Not a backend blocker.

**Comment by sakluger** [comment] 2024-06-07 15:28
I don't think this needs to be a deploy blocker, since it doesn't block the user from doing anything, it's just a display bug in a single flow.

cc @trjExpensify in case you feel otherwise.

**Comment by techievivek** [comment] 2024-06-07 15:29
Yeah, it doesn't break anything related to making request so we can remove the blocker label.

**Comment by techievivek** [comment] 2024-06-07 15:30
@abzokhattab Can you take a look at this issue, it seems to have stem from https://github.com/Expensify/App/pull/40062

**Comment by trjExpensify** [comment] 2024-06-07 15:30
^^ this. Thanks! Agree we don't need to block on it.

**Comment by Rakshh** [comment] 2024-06-07 19:35
Can't we use regex to prevent this:

Something like: textboxText.replace(/^0+/, '')
[+]: https://stackoverflow.com/questions/30626094/remove-leading-zeros-from-input-type-number

**Comment by Har103** [comment] 2024-06-07 22:38
Just saw this on UW
And I might give a stupid solution.

Why are we not checking user input at the time of input (like on change event) and removing the leading zeros or any non numaric character at that time.
A small sterilization function should not cause any performance issues.

**Comment by hungvu193** [comment] 2024-06-09 02:19
> @abzokhattab Can you take a look at this issue, it seems to have stem from https://github.com/Expensify/App/pull/40062

Thanks for proposals everyone. But I think we should wait for this comment first.

**Comment by hungvu193** [comment] 2024-06-11 02:07
> @abzokhattab Can you take a look at this issue, it seems to have stem from #40062

little bump @abzokhattab for this comment

**Comment by abzokhattab** [comment] 2024-06-11 15:08
Thank you @hungvu193   sure i will work on it

**Comment by hungvu193** [comment] 2024-06-13 01:25
Hold for https://github.com/Expensify/App/issues/43243#issuecomment-2155073016

**Comment by techievivek** [comment] 2024-06-13 11:36
Assigning it to @abzokhattab based on https://github.com/Expensify/App/issues/43243#issuecomment-2155073016

**Comment by hungvu193** [comment] 2024-06-14 01:58
@techievivek I think the original C+ will handle this one right?

**Comment by sakluger** [comment] 2024-06-14 23:08
Hey @abzokhattab - do you have a proposal or PR to fix this issue yet?

**Comment by abzokhattab** [comment] 2024-06-15 21:38
isn't this already the expected behavior according to https://github.com/Expensify/App/pull/35797#issuecomment-1943786891 and https://github.com/Expensify/App/issues/34894#issuecomment-1915238369? 

cc @dangrous @eVoloshchak

**Comment by dangrous** [comment] 2024-06-18 14:21
So yeah this is currently expected behavior - to maintain user input in this flow. I could see us making an exception for leading zeros, but I don't think this should count as a regression.

Basically our reasoning was that it's confusing if what you put in changed when you go back to it, and we do all the parsing afterwards. Again, this can be open for discussion, but shouldn't be a regression.

We could also go the other route that Square Cash (and maybe others) take, and just disallow leading zeros from the beginning.

**Comment by sakluger** [comment] 2024-06-18 17:54
Thanks for clarifying @dangrous. I agree that we don't need to count this as a regression, but we should change the behavior to disallow leading zeros.

**Comment by sakluger** [comment] 2024-06-21 17:42
You know what - since this is the expected behavior at the moment, I'm going to close the issue for now. We can reopen later or open a new issue if we want to change the behavior.

**Closed by sakluger** 2024-06-21 17:42 UTC
Labels: External, Engineering, Daily, Overdue, Bug
