### ISSUE TITLE
[$500] FAB - No tooltip is displayed when hovering over FAB button when FAB menu is open

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#35964] opened 2024-02-06 21:35 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4-37.3
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** Applause - Internal Team
**Slack conversation:**

## Action Performed:
1. Go to staging.new.expensify.com
2. Click FAB button
3. Hover over FAB button

## Expected Result:
Tooltip will be displayed for FAB button when FAB menu is open (old UI behavior)

## Actual Result:
Tooltip is not displayed for FAB button when FAB menu is open (old UI behavior)

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details> 

https://github.com/Expensify/App/assets/78819774/43abe4dc-cd1e-4b1e-86a3-cbf01de9dce7

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~016d5a427366019641</li>
        <li>Upwork Job ID: 1754982105754923008</li>
        <li>Last Price Increase: 2024-02-06</li>
    </ul>
</details>

**Comment by lanitochka17** [comment] 2024-02-06 21:36
We think that this bug might be related to #wave8
CC @zanyrenney

**Comment by Tony-MK** [comment] 2024-02-06 21:41
## Proposal

### Please re-state the problem that we are trying to solve in this issue.

### What is the root cause of that problem?

No `Tooltip` component to wrap the `FloatingActionButton` component.
 
https://github.com/Expensify/App/blob/a4183ecaa13bce5db3da7a66901aec1692bf8938/src/pages/home/sidebar/SidebarScreen/FloatingActionButtonAndPopover.js#L211

### What changes do you think we should make in order to solve the problem?


We should wrap the `FloatingActionButton` component with the `Tooltip` component.

Should look like this.
```
<Tooltip>
 <FloatingActionButton/>
</>
```

**Comment by Tony-MK** [comment] 2024-02-06 21:58
## Proposal

### Please re-state the problem that we are trying to solve in this issue.

### What is the root cause of that problem?

In the [`Overlay`](https://github.com/Expensify/App/blob/a4183ecaa13bce5db3da7a66901aec1692bf8938/src/libs/Navigation/AppNavigator/Navigators/Overlay.tsx#L22-L23) component, we do not warp the close buttons with the `Tooltip` component.

### What changes do you think we should make in order to solve the problem?


We should wrap the `Overlay` component with the `Tooltip` component and the text to 'common.close'.

Just like the `FloatingActionButton`
https://github.com/Expensify/App/blob/a4183ecaa13bce5db3da7a66901aec1692bf8938/src/pages/home/sidebar/SidebarScreen/FloatingActionButtonAndPopover.js#L210-L211

Therefore, the `Tooltip` component will warp as demonstrated below.

```
<Tooltip text={translate('common.close')}>
...
</Tooltip>
```

**Comment by Tony-MK** [comment] 2024-02-06 22:08
## Proposal

### Please re-state the problem that we are trying to solve in this issue.

### What is the root cause of that problem?

In the [`Overlay`](https://github.com/Expensify/App/blob/a4183ecaa13bce5db3da7a66901aec1692bf8938/src/libs/Navigation/AppNavigator/Navigators/Overlay.tsx#L22-L23) component, we do not warp the `PressableWithoutFeedback` components (close buttons) with the `Tooltip` component.

On the other hand, the `FloatingActionButton` (open button) operates because it is wrapped in a `Tooltip` component.

https://github.com/Expensify/App/blob/ccad06103b56b1469034658c50f1e6218cc04057/src/components/FloatingActionButton.tsx#L106-L107

### What changes do you think we should make in order to solve the problem?


Similar to the `FloatingActionButton`, we should wrap the `PressableWithoutFeedback` components inside the [`Overlay`](https://github.com/Expensify/App/blob/a4183ecaa13bce5db3da7a66901aec1692bf8938/src/libs/Navigation/AppNavigator/Navigators/Overlay.tsx#L22-L23) component with the `Tooltip` component.

```
<Tooltip text={translate('common.close')}>
...
</Tooltip>
```

**Comment by DylanDylann** [comment] 2024-02-07 04:18
@Expensify/design Could you guys help to confirm whether this is a bug or expected?

Current behavior

https://github.com/Expensify/App/assets/141406735/19c931b5-c98f-44bf-941f-140e3ec4e4dd

After fixing


https://github.com/Expensify/App/assets/141406735/5a63584d-0e0c-4c58-9063-f2d0ba26448d

**Comment by dubielzyk-expensify** [comment] 2024-02-07 04:53
I'm not convinced this is a bug. By having the tooltip display "Close" so quickly it feels like it's giving itself too much prominence. Keen to hear what @Expensify/design thinks

**Comment by situchan** [comment] 2024-02-07 05:01
Expected Result and Actual Result are reversed.
In https://github.com/Expensify/App/issues/24296, we intentionally disabled tooltip when related popover is open.

Should we update TestRail?

**Comment by DylanDylann** [comment] 2024-02-07 06:00
@situchan Thanks for your information. Let's close this issue

cc @abekkala

**Comment by shawnborton** [comment] 2024-02-07 13:52
Down to close as well!

**Comment by dannymcclain** [comment] 2024-02-08 14:56
Agree that we should close this.

**Closed** 2024-02-08 23:20 UTC
Labels: External, Daily, Help Wanted, Bug
