### ISSUE TITLE
[$500] IOS - Private notes are displaying extra spaces and text beyond the box boundaries

### ISSUE THREAD

**Issue by izarutskaya** [Expensify/App#28623] opened 2023-10-02 15:41 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Open a chat.
2. Click on the header and navigate to “Private notes”
3. Enter “```Test1```Test2” and save it.
4. Observe that “Test2” extends beyond the box boundaries

## Expected Result:
Private notes should not display extra spaces, and text should be displayed correctly within the box

## Actual Result:
Private notes are showing extra spaces, and text is extending beyond the box boundaries

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [x] iOS / native
- [ ] iOS / Safari
- [ ] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** v1.3.75-8

**Reproducible in staging?:** Y

**Reproducible in production?:** Y

**If this was caught during regression testing, add the test name, ID and link from TestRail:**

**Email or phone of affected tester (no customers):**

**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/115492554/d83b0ab5-bafe-423f-995e-3710f1d372f9

https://github.com/Expensify/App/assets/115492554/8dfb3140-4e5c-44d9-a5ca-b6f0947c8d41

**Expensify/Expensify Issue URL:**

**Issue reported by:** @ayazhussain79

**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1696199737738539

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01125e9386d4320219</li>
        <li>Upwork Job ID: 1708869806201487360</li>
        <li>Last Price Increase: 2023-10-02</li>
    </ul>
</details>

**Comment by burczu** [comment] 2023-10-03 11:54
It looks like regression caused by this PR: https://github.com/Expensify/App/pull/27769. This PR supposed to fix few issues, and one of them: https://github.com/Expensify/App/issues/27802 looks quite similar to this issue. I wonder how should we approach this issue - maybe the author of mentioned PR should fix it?

@garrettmknight ^^

**Comment by garrettmknight** [comment] 2023-10-11 20:08
Making sure this regression is fixed in the other issue. Agreed that the other issue (https://github.com/Expensify/App/issues/27802) looks almost exactly like this one. I'm going to close as a duplicate and we can make sure the regression gets sorted in the other issue.

**Closed by garrettmknight** 2023-10-11 20:08 UTC
Labels: Reviewing, External, Weekly, Help Wanted, Bug
