### ISSUE TITLE
[$250] Invoice - Unsuccessful workspace deletion results in archived label on Invoice

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#48479] opened 2024-09-03 14:08 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 9.0.28-0
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**If this was caught during regression testing, add the test name, ID and link from TestRail:** N/A
**Email or phone of affected tester (no customers):** biruknew45+598@gmail.com
**Issue reported by:** Applause - Internal Team

## Action Performed:
1. Go to https://staging.new.expensify.com/
2. Click on the FAB > New Workspace
3. Navigate back to the Inbox
4. Click on the FAB > Send Invoice > Enter amount > Enter receiver > Send Invoice
5. Navigate to another chat (either your own or any unrelated to the workspace and invoice)
6. Go to Settings > Workspace
7. Click on the three dots menu, then select "Delete
8. An error message appears; click on "X"
9. Go back to the Inbox

## Expected Result:
The workspace chat and the invoice chat should not have the "Archived" label since the workspace was not successfully deleted

## Actual Result:
Both the workspace chat and the invoice chat have the "Archived" label in their titles

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [ ] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details> 

![6!1 (1)](https://github.com/user-attachments/assets/b2f63b5e-4534-433f-b820-75909c66a62b)

https://github.com/user-attachments/assets/3830a0d0-7aa8-49d4-a28f-2fe907786b0d

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01aaf6465a7187e62b</li>
        <li>Upwork Job ID: 1831307112820248511</li>
        <li>Last Price Increase: 2024-09-04</li>
<li>Automatic offers: </li>
<ul>
<li>dukenv0307 | Reviewer | 103828758</li>
<li>FitseTLT | Contributor | 103828759</li>
</ul></li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @dukenv0307</details>

**Comment by FitseTLT** [comment] 2024-09-03 14:23
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
Invoice - Unsuccessful workspace deletion results in archived label on Invoice

### What is the root cause of that problem?
We are setting the optimistic value here
https://github.com/Expensify/App/blob/e60b8210a1f5a2471d8aa9d84d0e461774b791d6/src/libs/actions/Policy/Policy.ts#L304-L315
and setting the failureData here
https://github.com/Expensify/App/blob/e60b8210a1f5a2471d8aa9d84d0e461774b791d6/src/libs/actions/Policy/Policy.ts#L369-L380
But the problem is we forgot to revert `private_isArchived` field on failureData

### What changes do you think we should make in order to solve the problem?

So revert private_isArchived on failureData
```
reportsToArchive.forEach((report) => {
        const {reportID, stateNum, statusNum, oldPolicyName, private_isArchived} = report ?? {};
        failureData.push({
            onyxMethod: Onyx.METHOD.MERGE,
            key: `${ONYXKEYS.COLLECTION.REPORT}${reportID}`,
            value: {
                stateNum,
                statusNum,
                oldPolicyName,
                policyName: report?.policyName,
                private_isArchived,
            },
        });
    });
```
### What alternative solutions did you explore? (Optional)

**Comment by miljakljajic** [comment] 2024-09-20 14:51
It seemed like this was deployed to prod on the 11th of September, so I paid both offers.

If there ends up being another BZ task to complete please re-assign to to someone else, I am going on extended leave.

**Closed by miljakljajic** 2024-09-20 14:51 UTC
Labels: Reviewing, External, Weekly, Bug
