### ISSUE TITLE
[$500] Deeplinks - "It's not here" displayed when background the app and open /enable-payment deeplink

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#29232] opened 2023-10-10 20:28 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.3.80-1

**Reproducible in staging?:** Yes

**Reproducible in production?:** Yes

**If this was caught during regression testing, add the test name, ID and link from TestRail:**

**Email or phone of affected tester (no customers):**

**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Expensify/Expensify Issue URL:**

**Issue reported by:** Applause - Internal Team

**Slack conversation:**

## Action Performed:
Precondition: user should NOT be Signed In
1. Open app
2. Background the app
3. Tap on deeplink from other app (messanger/notes)
   [staging.new.expensify.com/enable-payments](http://staging.new.expensify.com/enable-payments)

## Expected Result:
User should be navigated on "Enable-payments" page

## Actual Result:
"Hmm... it's not here" page opens

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [x] iOS: Native
- [ ] iOS: mWeb Safari
- [ ] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos
<details>
<summary>Android: Native</summary>

 

https://github.com/Expensify/App/assets/78819774/01b9765d-aa66-4639-8c65-47eec611b2e7

</details>

<details>
<summary>Android: mWeb Chrome</summary>

</details>

<details>
<summary>iOS: Native</summary>

 

https://github.com/Expensify/App/assets/78819774/73d85d40-82b8-4189-a97f-199911c2052a

</details>

<details>
<summary>iOS: mWeb Safari</summary>

</details>

<details>
<summary>MacOS: Chrome / Safari</summary>

</details>

<details>
<summary>MacOS: Desktop</summary>

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01f993ca3dfb12ab11</li>
        <li>Upwork Job ID: 1802829645254455808</li>
        <li>Last Price Increase: 2024-08-08</li>
<li>Automatic offers: </li>
<ul>
<li>shubham1206agra | Reviewer | 102925992</li>
</ul></li>
    </ul>
</details>

**Comment by alexpensify** [comment] 2023-10-11 20:35
Still on my testing list, other GHs have taken priority.

**Comment by alexpensify** [comment] 2023-10-13 17:15
I've run out of time and will have to test over the weekend.

**Comment by alexpensify** [comment] 2023-10-16 04:33
Closing - I've been unable to replicate

**Comment by alexpensify** [comment] 2024-03-14 22:47
I'll need to test again then.

**Comment by alexpensify** [comment] 2024-03-18 23:01
Still on my testing list.

**Comment by alexpensify** [comment] 2024-03-22 19:32
I'll test soon.

**Comment by alexpensify** [comment] 2024-03-26 00:25
On my testing list

**Comment by alexpensify** [comment] 2024-03-27 19:11
Closing again, I tested again and did not get the oops error: 

1. I logged into the application 
![2024-03-27_12-06-36](https://github.com/Expensify/App/assets/8107070/a59d7348-f6c1-4520-a44b-6894ca94b831)

2. I opened the browser and input the following link: 
staging.new.expensify.com/enable-payments

I get to the following location: 

![2024-03-27_12-06-08](https://github.com/Expensify/App/assets/8107070/163497f0-c188-4774-a5eb-b788dcc972cd)

When I log in, I land on the following page: 

![2024-03-27_12-10-49](https://github.com/Expensify/App/assets/8107070/81e2d5de-2de4-4c3e-9bee-5982ebe5355d)

**Comment by lanitochka17** [comment] 2024-06-07 23:28
Issue is still reproducible 


https://github.com/Expensify/App/assets/78819774/f09cd341-1bf4-4167-a7cd-653ff19edbbc

**Comment by alexpensify** [comment] 2024-06-10 04:08
This week, I'll try to test again.

**Comment by alexpensify** [comment] 2024-06-11 17:26
I've asked for help here - https://expensify.slack.com/archives/C01SKUP7QR0/p1718126752943919 and confirm on a physical device instead of a simulator.

**Comment by mallenexpensify** [comment] 2024-06-11 21:35
I'm a bit confused. In the OP it states "Precondition: user should be Signed In" but in the vid [here](https://github.com/Expensify/App/issues/29232#issuecomment-2155692151), the user needs to sign in then be redirected to the error page.   

For me... when I'm signed into my mallen@expensify.com email on the latest staging version and I click http://staging.new.expensify.com/enable-payments in a text message I sent to a test account, the app opens to LHN. 

When I sign out then use my mattqwerty9@gmail.com to sign in after clicking http://staging.new.expensify.com/enable-payments , I'm sent to an error page. @alexpensify , want to update the OP to state
> Precondition: user should **not** be Signed In ?

**Comment by alexpensify** [comment] 2024-06-14 00:11
Thanks, @mallenexpensify, for testing! I'll update the OP and include that precondition.

**Comment by alexpensify** [comment] 2024-06-17 22:24
Assigning external, we need proposals here.

**Comment by alexpensify** [comment] 2024-06-19 18:13
Waiting for proposals here

**Comment by alexpensify** [comment] 2024-06-21 22:18
Waiting for proposals here

**Comment by alexpensify** [comment] 2024-06-22 00:40
Waiting for proposals here

**Comment by alexpensify** [comment] 2024-06-24 23:03
Waiting for proposals here

**Comment by alexpensify** [comment] 2024-06-28 21:57
Following this process: https://stackoverflowteams.com/c/expensify/questions/8260/8261#8261

**Comment by alexpensify** [comment] 2024-06-28 22:38
## Heads up, I will be offline until Monday, July 8, 2024, and will not actively watch over this GitHub during that period. 

I'll try to check in a few times. If anything urgent is needed here, please ask for help in the #expensify-open-source Slack Room-- thanks!

**Comment by BrtqKr** [comment] 2024-06-29 06:44
Hey, I'm a developer from SWM I'd like to take care of this ticket.

**Comment by alexpensify** [comment] 2024-06-29 15:04
Thanks, I've assigned you @BrtqKr.

**Comment by alexpensify** [comment] 2024-07-01 14:21
## Heads up, I will be offline until Monday, July 8, 2024, and will not actively watch over this GitHub during that period.

If this GitHub needs an urgent update, please ask for help in the #expensify-open-source Slack Room. If it can wait, I'll continue the review process when I return online. Thanks!

**Comment by BrtqKr** [comment] 2024-07-01 15:37
Since the issue is only able to be reproduced using universal links, do you know how can I set this up locally? Without a compatible app ID I'm unable to debug this in any way, because it doesn't detect the app and is redirecting me to the web instead.

**Comment by alexpensify** [comment] 2024-07-04 23:17
No update yet, waiting for a PR from @BrtqKr.

**Comment by alexpensify** [comment] 2024-07-08 17:44
@BrtqKr - I'm catching up from being OOO, any update here? Thanks!

**Comment by alexpensify** [comment] 2024-07-10 17:34
@BrtqKr - please keep me posted if you can't work on this one and I'll ask around for help. Thanks!

**Comment by alexpensify** [comment] 2024-07-12 22:41
Waiting for an update

**Comment by BrtqKr** [comment] 2024-07-15 08:12
Sorry @alexpensify, I was talking about this with @AndrewGable on the shared channel during your absence. I'd need a provisioning profile to test this on a physical device, otherwise it wasn't working. There's a `?mode=developer` thing for the universal links, but it has to relate web and mobile versions properly.

**Comment by alexpensify** [comment] 2024-07-15 18:45
Ok, thanks for that update. Did you chat with Andrew in a public channel, if yes, can you share a link here? Thanks!

**Comment by BrtqKr** [comment] 2024-07-15 22:12
Sure, [it's here](https://swmansion.slack.com/archives/C04878MDF34/p1719849633995639)

**Comment by alexpensify** [comment] 2024-07-19 00:18
Thanks, I'll review that thread and figure out what we should do here.

**Comment by alexpensify** [comment] 2024-07-22 19:29
No update and still need to plan the next steps here

**Comment by alexpensify** [comment] 2024-07-29 18:48
I bumped the Slack 🧵 to figure out the next steps or if we should close: 

https://expensify.slack.com/archives/C04878MDF34/p1722278661242209?thread_ts=1719849633.995639&cid=C04878MDF34

**Comment by alexpensify** [comment] 2024-07-31 22:05
I'm still reviewing the next steps here and what's possible.

**Comment by alexpensify** [comment] 2024-08-05 20:30
No update

**Comment by alexpensify** [comment] 2024-08-08 22:00
Other GHs have been a higher priority. I'll review the options soon.

**Comment by alexpensify** [comment] 2024-08-12 21:32
There is no update; I was OOO on Friday and catching up.

**Comment by alexpensify** [comment] 2024-08-15 19:58
No update yet

**Comment by alexpensify** [comment] 2024-08-19 21:19
No news yet

**Comment by alexpensify** [comment] 2024-08-22 13:11
Moving to weekly for now, other GHs have been a priority.

**Comment by alexpensify** [comment] 2024-08-26 15:10
## Next Steps

Other GHs have been a higher priority, I'll review this one again when I'm back from OOO. 

## Heads up, I will be offline until Tuesday, September 3, 2024, and will not actively watch over this GitHub during that period. 

If anything urgent is needed here, please ask for help in the #expensify-open-source Slack Room-- thanks!

**Comment by alexpensify** [comment] 2024-09-03 23:05
I'm catching up from being OOO last week and review the discussion again soon.

**Comment by alexpensify** [comment] 2024-09-11 22:58
No update

**Comment by alexpensify** [comment] 2024-09-20 22:15
Other GitHubs have been a priority, I'll get to this one soon.

**Comment by alexpensify** [comment] 2024-09-27 18:00
I've been sick this week and haven't been able to review this GitHub. There is no major update here; I'll try to carry on next week.

**Comment by alexpensify** [comment] 2024-10-04 20:25
No update

**Comment by alexpensify** [comment] 2024-10-07 21:33
I'm going to close this issue as the Project this was part of was closed too.

**Closed by alexpensify** 2024-10-07 21:33 UTC
Labels: External, Weekly, Bug
