### ISSUE TITLE
[HOLD for payment 2024-11-29] [HOLD for payment 2024-11-28] Hybrid - Login-App flickers when login and Splash screen is displayed every time

### ISSUE THREAD

**Issue by IuliiaHerets** [Expensify/App#52746] opened 2024-11-19 09:43 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:**  9.0.64-0
**Reproducible in staging?:** N
**Reproducible in production?:** N
**If this was caught on HybridApp, is this reproducible on New Expensify Standalone?:** Y
**Email or phone of affected tester (no customers):** htad26+hghgh@gmail.com
**Issue reported by:** Applause Internal Team

## Action Performed:
1. Log in to hybrid android app (Here notice that the login page is flickering and is unstable)
2. Create a new workspace > Submit a manual expense to the workspace
3. Open the expense report

## Expected Result:
Step 1. App logs in without an issue and does not flicker
Step 3. The expense transaction page is opened

## Actual Result:
Step 1. App flickers
Step 3. Splash screen is displayed. This happens when performing other actions on the app too.

## Workaround:
Unknown

## Platforms:

- [ ] Android: Standalone
- [x] Android: HybridApp
- [ ] Android: mWeb Chrome
- [ ] iOS: Standalone
- [x] iOS: HybridApp
- [ ] iOS: mWeb Safari
- [ ] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

https://github.com/user-attachments/assets/c7e02fb4-0a53-4b5c-b709-13366c832518
  
</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Issue Owner</summary>Current Issue Owner: @youssef-lr</details>

**Comment by jnowakow** [comment] 2024-11-19 14:49
It's caused by [this PR](https://github.com/Expensify/App/pull/52694)

**Comment by Julesssss** [comment] 2024-11-19 15:11
Being discussed [here](https://expensify.slack.com/archives/C04878MDF34/p1732027392384929) in Slack

**Comment by RachCHopkins** [comment] 2024-11-20 00:29
Revert PR created and linked above. Approved by @neil-marcellini but not yet deployed.

**Comment by RachCHopkins** [comment] 2024-11-25 05:42
Do you need to do the checklist @youssef-lr, or can we close this?

**Comment by jnowakow** [comment] 2024-11-25 08:14
This bug was fix by the revert. Original issue was fixed by [this PR](https://github.com/Expensify/App/pull/52824)

**Comment by RachCHopkins** [comment] 2024-12-02 06:23
Looks like we can close this!

**Closed by RachCHopkins** 2024-12-02 06:23 UTC
Labels: Engineering, Daily, Overdue, Awaiting Payment, Bug
