### ISSUE TITLE
[HOLD] [$250] The green dot disappears after the admin has approved but not yet paid

### ISSUE THREAD

**Issue by m-natarajan** [Expensify/App#39529] opened 2024-04-03 18:21 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.59-3
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** @DylanDylann 
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1712137559164489

## Action Performed:
Pre-requisites:

1. Have a collect WS and make chat enabled on ND
2. Have 2 accounts (one admin, one employee)
3. Having `Make or track payments enabled
4. Toggle off Add approvals

5. [Employee] Request money from the workspace chat and submit it
6. [Admin] approve the above request

## Expected Result: 
The green dot should be appear after the admin has approved but not yet paid

## Actual Result: 
The green dot disappears after the admin has approved but not yet paid

## Workaround:
unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

https://github.com/Expensify/App/assets/38435837/821175c0-2070-42db-ac97-c0753503d256

https://github.com/Expensify/App/assets/38435837/53e2028a-683f-4d01-b602-567a83af1223

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01ebb3d2379b3cb18b</li>
        <li>Upwork Job ID: 1777701518072827904</li>
        <li>Last Price Increase: 2024-04-09</li>
<li>Automatic offers: </li>
<ul>
<li>DylanDylann | Reviewer | 0</li>
</ul></li>
    </ul>
</details>

**Comment by DylanDylann** [comment] 2024-04-03 18:22
I have context while finding this bug. Could I take over this issue as a C+ role?

**Comment by FitseTLT** [comment] 2024-04-03 19:02
## Proposal

### Please re-state the problem that we are trying to solve in this issue.

The green dot disappears after the admin has approved but not yet paid

### What is the root cause of that problem?
The green dot indicator is displayed based on the report `hasOutstandingChildRequest`
https://github.com/Expensify/App/blob/398636a109452a6442d5e9fd0774f928ceaddee0/src/libs/ReportUtils.ts#L2071-L2072
which is set to false when it is approved
### What changes do you think we should make in order to solve the problem?

We need to show the indicator when the report is not settled one so change it to
```
    if (optionOrReport.hasOutstandingChildRequest || !isSettled(optionOrReport.reportID)) {

```
### What alternative solutions did you explore? (Optional)

**Comment by miljakljajic** [comment] 2024-04-09 14:14
Thank you @DylanDylann

**Comment by DylanDylann** [comment] 2024-04-10 08:17
@nkdengineer's proposal looks good to me. In the PR phase, we can consider adding `isPayer` condition to make sure this report still needs to be paid

🎀 👀 🎀 C+ reviewed

**Comment by Julesssss** [comment] 2024-04-10 08:46
> we can consider adding isPayer condition to make sure this report still needs to be paid

Lets try that in the PR 👍

**Comment by nkdengineer** [comment] 2024-04-12 07:59
https://github.com/Expensify/App/assets/161821005/2f32e9e2-8219-4958-9bd3-949c9699a13c

We have draft PR [here](https://github.com/Expensify/App/pull/40164), but we still need to change Back End. Because it's return `hasOutstandingChildRequest=false` when we call api `ApproveMoneyRequest`
@DylanDylann @Julesssss

**Comment by miljakljajic** [comment] 2024-04-15 12:12
@Julesssss just checking you're good to help with this at some point this week?

**Comment by nkdengineer** [comment] 2024-04-22 03:57
@Julesssss please check this [comment](https://github.com/Expensify/App/issues/39529#issuecomment-2051224314) when you get a chance

**Comment by nkdengineer** [comment] 2024-04-22 03:58
@DylanDylann we have open PR [here](https://github.com/Expensify/App/pull/40164)

**Comment by Julesssss** [comment] 2024-04-23 11:17
Sorry for the late response.

I'm afraid I'm not going to be able to prioritise this any time soon. @miljakljajic due to other critical tasks we'll need to wait for a couple of months, or get this attached to a release and maybe find someone else to work on it. This might be tricky to find a volunteer without it being attached to a release.

**Comment by miljakljajic** [comment] 2024-04-23 14:19
I've added it to wave collect, thank you Jules - no problem

**Comment by DylanDylann** [comment] 2024-04-24 09:32
@Julesssss Should we move forward with the fix on FE instead of holding the BE change? If that, this issue will be fixed in offline mode

cc @nkdengineer

**Comment by Julesssss** [comment] 2024-04-24 09:37
Nice idea, but I think we shouldn't. It could be months before the backend fix is made, and in the meantime lots of things could have changed or altered the eventual implementation. lets keep the offline/online code aligned.

**Comment by DylanDylann** [comment] 2024-04-24 09:40
Yeah, let's mark this issue on hold

**Comment by Julesssss** [comment] 2024-05-20 08:58
It's going to be on hold for a while. No update

**Comment by nkdengineer** [comment] 2024-06-10 09:56
@Julesssss What's the latest here?

**Comment by Julesssss** [comment] 2024-06-10 10:19
> @Julesssss What's the latest here?

I'm not going to have time for this for the next few months so it'll remain held. 

Though I am curious if this is still occurring and hasn't been fixed elsewhere. I'll ask QA to retest in the meantime.

**Comment by Julesssss** [comment] 2024-06-27 17:24
Although this issue is reproducable, we aren't able to prioritise this over internal projects. So I am closing it.

**Comment by DylanDylann** [comment] 2024-07-02 07:30
@Julesssss Should we handle payment for this issue? The contributor gets assigned and the PR also be reviewing

**Comment by Julesssss** [comment] 2024-07-02 10:37
@DylanDylann  hmm, I think ideally the proposal should have [noticed](https://github.com/Expensify/App/issues/39529#issuecomment-2051224314) the backend fix was required. In which case we wouldn't have moved forward. 

@nkdengineer please let me know if you disagree though

**Comment by nkdengineer** [comment] 2024-07-09 02:41
@Julesssss  We both invest considerable effort in investigating and creating the PR. How would you feel about a half of compensation for this issue?

**Comment by Julesssss** [comment] 2024-07-09 11:17
That seems fair to me. @miljakljajic could we create payments but update the price to $125 please?

**Comment by miljakljajic** [comment] 2024-07-11 16:27
Agreed - I issued a bonus for @nkdengineer and paid @DylanDylann via the upwork job

**Closed by miljakljajic** 2024-07-11 16:27 UTC
Labels: Reviewing, External, Monthly, Bug
