### ISSUE TITLE
[HOLD for payment 2023-07-28] [$1000] Room name can be changed by non admin users

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#21498] opened 2023-06-24 15:22 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Let User A Create a new room where User B is a member.
2. Using User B click on the room avatar on top.
3. Go to settings
4. Click on room names.
5. Change the name and click the save button.

## Expected Result:
Non-admin users can't change room names.

## Actual Result:
Non-admin users can change room names

## Workaround:
Can the user still use Expensify without this being fixed? Have you informed them of the workaround?

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [x] MacOS / Chrome / Safari
- [x] MacOS / Desktop

**Version Number:** 1.3.32.5
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/93399543/48a90e53-246f-4f8d-95e3-fced5961d6e5

https://github.com/Expensify/App/assets/93399543/3ef496e0-2ff5-41c6-aab0-248da559abd2

**Expensify/Expensify Issue URL:**
**Issue reported by:**@daveSeife
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1686945159267029

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~012941a26a49d6fdc1</li>
        <li>Upwork Job ID: 1673340653182439424</li>
        <li>Last Price Increase: 2023-06-26</li>
    </ul>
</details>

**Comment by abdulrahuman5196** [comment] 2023-06-29 11:03
@CortneyOfstad @hungvu193  proposal here https://github.com/Expensify/App/issues/21498#issuecomment-1605588348 is working fine

But before approving I wanted to double confirm if the expectation is correct.

For any room only the admin can change the room name? Since backend is also not validating this, wanted to confirm on this expectation.

**Comment by CortneyOfstad** [comment] 2023-06-30 15:18
@abdulrahuman5196 Yes, that is the expectation. Policy or Workspace Rooms should only be edited by Admins of those policies/workspaces 👍

**Comment by CortneyOfstad** [comment] 2023-06-30 19:34
Heading OoO for the week (back July 10) so re-assigning this in the meantime 👍

**Comment by joekaufmanexpensify** [comment] 2023-07-03 13:08
@CortneyOfstad As an fyi, I think we're supposed to leave ourselves assigned when temporarily assigning others for OOO, per [this update](https://expensify.slack.com/archives/CK49UADB9/p1684182291511799). Happy to watch this one in the meantime though!

**Comment by abdulrahuman5196** [comment] 2023-07-03 13:17
@hungvu193 Your proposal here is working but it is missing a case. 
If we directly route to room rename url - https://github.com/Expensify/App/issues/21498#issuecomment-1605588348, it is allowing us to edit. Could you include fix for the same in the proposal?

**Comment by abdulrahuman5196** [comment] 2023-07-03 13:30
@hungvu193 's proposal here https://github.com/Expensify/App/issues/21498#issuecomment-1605588348 looks good and works well.

🎀👀🎀
C+ Reviewed

🎀 👀 🎀 C+ reviewed

cc: @joekaufmanexpensify

**Comment by abdulrahuman5196** [comment] 2023-07-03 13:31
@chiragsalian C+ approved comment here - https://github.com/Expensify/App/issues/21498#issuecomment-1618266556

**Comment by joekaufmanexpensify** [comment] 2023-07-05 18:20
Pending confirmation from @chiragsalian that this proposal works.

**Comment by chiragsalian** [comment] 2023-07-05 18:43
Proposal LGTM, but its only a partial solution i.e., its a good front end solution. But we should also update the backend otherwise any user could use curl or postman to modify room names if we don't check for admins in the backend. I'll create another GH issue for that. 

Feel free to create a PR @hungvu193

**Comment by abdulrahuman5196** [comment] 2023-07-05 18:45
@chiragsalian 

>Proposal LGTM, but its only a partial solution i.e., its a good front end solution. But we should also update the backend otherwise any user could use curl or postman to modify room names if we don't check for admins in the backend. I'll create another GH issue for that.

Yes. I noticed this while review, but missed to mention it. We should fix this in backend as well.

**Comment by chiragsalian** [comment] 2023-07-05 18:50
cool, i just created a GH issue for someone to tackle the backend issue [here](https://github.com/Expensify/App/issues/22292)

**Comment by joekaufmanexpensify** [comment] 2023-07-11 19:52
@CortneyOfstad I saw you're back from OOO, so going to unassign. LMK if there's anything else I can help with!

**Comment by CortneyOfstad** [comment] 2023-07-13 12:37
Where are we at here @abdulrahuman5196 and @chiragsalian? Just checking to see if there is anything waiting on me — TIA!

**Comment by CortneyOfstad** [comment] 2023-07-14 14:28
Thank you @abdulrahuman5196!

**Comment by CortneyOfstad** [comment] 2023-07-17 14:17
Things still looking good?

**Comment by CortneyOfstad** [comment] 2023-07-19 13:14
Chirag is OoO on paternity leave, so going to get engineering eyes on this to do the final review 👍

**Comment by Julesssss** [comment] 2023-07-19 13:28
Can someone link to the correct PR please

**Comment by abdulrahuman5196** [comment] 2023-07-19 13:36
Here is the PR https://github.com/Expensify/App/pull/22316 @Julesssss .
Previously @chiragsalian had approved the PR https://github.com/Expensify/App/pull/22316#pullrequestreview-1529375654

**Comment by Julesssss** [comment] 2023-07-19 15:30
✅

**Comment by CortneyOfstad** [comment] 2023-07-21 13:33
Thanks @Julesssss!

@hungvu193 looks like we're ready to keep moving forward! 🎉

**Comment by Julesssss** [comment] 2023-07-21 14:11
Merged and awaiting deployment

**Comment by abdulrahuman5196** [comment] 2023-07-22 14:19
>The PR that introduced the bug has been identified. Link to the PR:
The offending PR has been commented on, pointing out the bug it caused and why, so the author and reviewers can learn from the mistake. Link to comment:
A discussion in #expensify-bugs has been started about whether any other steps should be taken (e.g. updating the PR review checklist) in order to catch this type of bug sooner. Link to discussion:

Not a regression. This issue was present during the creation of the page itself. 

>Determine if we should create a regression test for this bug.

Yes

>If we decide to create a [regression test](https://github.com/Expensify/App/blob/main/contributingGuides/REGRESSION_TEST_BEST_PRACTICES.md) for the bug, please propose the regression test steps to ensure the same bug will not reach production again.


1) Let User A Create a new room where User B is a member.
2) Using User B click on the room avatar on top.
3) Verify that user B can't change the room name
4) From userA copy url to the rename page and paste to the userB browser.
5) Verify that user B can't change the room name

**Comment by CortneyOfstad** [comment] 2023-07-28 14:44
@daveSeife is this your UpWork profile? https://www.upwork.com/freelancers/~01b619c381741a0db1

I just want to make sure that I offer the contract for the reporting payment to the correct location. If this is not correct, can you please link your profile?

**Comment by daveSeife** [comment] 2023-07-28 17:58
@CortneyOfstad Yes it is my Profile. You are correct. Thank you

**Comment by CortneyOfstad** [comment] 2023-07-28 19:50
Perfect! @daveSeife, I've sent the contract your way. Let me know as soon as you accept it so I can provide the payment. 

@hungvu193 and @abdulrahuman5196 — payments both sent to you!

**Comment by daveSeife** [comment] 2023-07-29 01:24
@CortneyOfstad Accepted the offer. Thank you.

**Comment by CortneyOfstad** [comment] 2023-07-31 12:07
Paid!

**Comment by CortneyOfstad** [comment] 2023-07-31 12:15
Done with my portion of the checklist. Closing!

**Closed by CortneyOfstad** 2023-07-31 12:15 UTC
Labels: External, Engineering, Daily, Awaiting Payment, Bug
