### ISSUE TITLE
[HOLD for payment 2024-08-09] [$250] Invoice - There is "Delete expense" option in the invoice paid system message

### ISSUE THREAD

**Issue by izarutskaya** [Expensify/App#45632] opened 2024-07-17 20:29 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 9.0.7-4
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**If this was caught during regression testing, add the test name, ID and link from TestRail:** https://expensify.testrail.io/index.php?/tests/view/4728016
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Issue reported by:** Applause-Internal team

## Action Performed:
Precondition:
- User has received invoice.
- The following steps will be performed by the invoice receiver.

1. Go to staging.new.expensify.com
2. Go to invoice chat.
3. Click on the invoice preview.
4. Click on the pay button.
5. Pay the invoice.
6. Right click on the paid system message.

## Expected Result:
There should be no "Delete expense" option in the invoice paid system message.

## Actual Result:
There is "Delete expense" option in the invoice paid system message. The invoice cannot be deleted.

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [x] Android: mWeb Chrome
- [x] iOS: Native
- [x] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

https://github.com/user-attachments/assets/8af6bb68-c8e7-40f8-a470-b72bf42c4ce1

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01a731bc49d6a020e0</li>
        <li>Upwork Job ID: 1814354277180193004</li>
        <li>Last Price Increase: 2024-07-19</li>
<li>Automatic offers: </li>
<ul>
<li>FitseTLT | Contributor | 103229523</li>
</ul></li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @CortneyOfstad</details>

**Comment by izarutskaya** [comment] 2024-07-17 20:30
We think this issue might be related to the #collect project.

**Comment by FitseTLT** [comment] 2024-07-17 22:45
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
Invoice - There is "Delete expense" option in the invoice paid system message
### What is the root cause of that problem?
As the `linkedReport` is an invoice type `canAddOrDeleteTransactions` will not be executed and `true` will be returned  here 
https://github.com/Expensify/App/blob/7ba66a1542fa815eed5cb4622244bc2935593484/src/libs/ReportUtils.ts#L1632-L1635
which will make the report action to be deleteable
### What changes do you think we should make in order to solve the problem?

We need to change 
https://github.com/Expensify/App/blob/7ba66a1542fa815eed5cb4622244bc2935593484/src/libs/ReportUtils.ts#L1632-L1633
```
            if (!isEmptyObject(linkedReport) && (isMoneyRequestReport(linkedReport) || isInvoiceReport(linkedReport))) {

```
### What alternative solutions did you explore? (Optional)
Or we can also change
https://github.com/Expensify/App/blob/7ba66a1542fa815eed5cb4622244bc2935593484/src/libs/ReportUtils.ts#L1634
to 
```
return !isInvoiceReport(linkedReport);
```

**Comment by FitseTLT** [comment] 2024-07-17 22:47
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
Invoice - There is "Delete expense" option in the invoice paid system message
### What is the root cause of that problem?
As the `linkedReport` is an invoice type `canAddOrDeleteTransactions` will not be executed and `true` will be returned  here 
https://github.com/Expensify/App/blob/7ba66a1542fa815eed5cb4622244bc2935593484/src/libs/ReportUtils.ts#L1632-L1635
which will make the report action to be deleteable
### What changes do you think we should make in order to solve the problem?

We need to change 
https://github.com/Expensify/App/blob/7ba66a1542fa815eed5cb4622244bc2935593484/src/libs/ReportUtils.ts#L1632-L1633
```
            if (!isEmptyObject(linkedReport) && (isMoneyRequestReport(linkedReport) || isInvoiceReport(linkedReport))) {

```
### What alternative solutions did you explore? (Optional)
Or we can also change
https://github.com/Expensify/App/blob/7ba66a1542fa815eed5cb4622244bc2935593484/src/libs/ReportUtils.ts#L1635
to 
```
return !isInvoiceReport(linkedReport);
```

**Comment by FitseTLT** [comment] 2024-07-17 23:07
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
Invoice - There is "Delete expense" option in the invoice paid system message
### What is the root cause of that problem?
As the `linkedReport` is an invoice type `canAddOrDeleteTransactions` will not be executed and `true` will be returned  here 
https://github.com/Expensify/App/blob/7ba66a1542fa815eed5cb4622244bc2935593484/src/libs/ReportUtils.ts#L1632-L1635
which will make the report action to be deleteable
### What changes do you think we should make in order to solve the problem?

We need to change 
https://github.com/Expensify/App/blob/7ba66a1542fa815eed5cb4622244bc2935593484/src/libs/ReportUtils.ts#L1635
to 
```
return !isInvoiceReport(linkedReport);
```
or 
```
return false;
```
### What alternative solutions did you explore? (Optional)
Alternatively we can change 
https://github.com/Expensify/App/blob/7ba66a1542fa815eed5cb4622244bc2935593484/src/libs/ReportUtils.ts#L1624-L1628
to 
```
const isSplitAction = ReportActionsUtils.getOriginalMessage(reportAction)?.type === CONST.IOU.REPORT_ACTION_TYPE.SPLIT;
        const isPayAction = ReportActionsUtils.getOriginalMessage(reportAction)?.type === CONST.IOU.REPORT_ACTION_TYPE.PAY;

        if (isSplitAction || isPayAction) {
            return false;
        }
```

**Comment by FitseTLT** [comment] 2024-07-17 23:26
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
Invoice - There is "Delete expense" option in the invoice paid system message
### What is the root cause of that problem?
As the `linkedReport` is an invoice type `canAddOrDeleteTransactions` will not be executed and `true` will be returned  here 
https://github.com/Expensify/App/blob/7ba66a1542fa815eed5cb4622244bc2935593484/src/libs/ReportUtils.ts#L1632-L1635
which will make the report action to be deleteable
### What changes do you think we should make in order to solve the problem?

We need to change 
https://github.com/Expensify/App/blob/7ba66a1542fa815eed5cb4622244bc2935593484/src/libs/ReportUtils.ts#L1635
to 
```
return !isInvoiceReport(linkedReport);
```
or
```
return false;
```
alternatively change 
https://github.com/FitseTLT/App/blob/7ba66a1542fa815eed5cb4622244bc2935593484/src/libs/ReportUtils.ts#L1632
to
```
            if (!isEmptyObject(linkedReport) && (isMoneyRequestReport(linkedReport) || isInvoiceReport(linkedReport))) {

```

### What alternative solutions did you explore? (Optional)
But we can disallow delete menu for  all `pay` type IOU report actions by changing
https://github.com/Expensify/App/blob/7ba66a1542fa815eed5cb4622244bc2935593484/src/libs/ReportUtils.ts#L1624-L1628
to 
```
const isSplitAction = ReportActionsUtils.getOriginalMessage(reportAction)?.type === CONST.IOU.REPORT_ACTION_TYPE.SPLIT;
        const isPayAction = ReportActionsUtils.getOriginalMessage(reportAction)?.type === CONST.IOU.REPORT_ACTION_TYPE.PAY;

        if (isSplitAction || isPayAction) {
            return false;
        }
```
We can also include other `REPORT_ACTION_TYPE` if needed

**Comment by FitseTLT** [comment] 2024-07-17 23:33
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
Invoice - There is "Delete expense" option in the invoice paid system message
### What is the root cause of that problem?
As the `linkedReport` is an invoice type `canAddOrDeleteTransactions` will not be executed and `true` will be returned  here 
https://github.com/Expensify/App/blob/7ba66a1542fa815eed5cb4622244bc2935593484/src/libs/ReportUtils.ts#L1632-L1635
which will make the report action to be deleteable
### What changes do you think we should make in order to solve the problem?

we should disallow delete menu for  all `pay` type IOU report actions by changing
https://github.com/Expensify/App/blob/7ba66a1542fa815eed5cb4622244bc2935593484/src/libs/ReportUtils.ts#L1624-L1628
to 
```
const isSplitAction = ReportActionsUtils.getOriginalMessage(reportAction)?.type === CONST.IOU.REPORT_ACTION_TYPE.SPLIT;
        const isPayAction = ReportActionsUtils.getOriginalMessage(reportAction)?.type === CONST.IOU.REPORT_ACTION_TYPE.PAY;

        if (isSplitAction || isPayAction) {
            return false;
        }
```
We can also include other `REPORT_ACTION_TYPE` if needed

We can narrow down the logic by applying it to pay actions of only invoice reports  `isInvoiceReport(linkedReport)`
### What alternative solutions did you explore? (Optional)
We can change 
https://github.com/Expensify/App/blob/7ba66a1542fa815eed5cb4622244bc2935593484/src/libs/ReportUtils.ts#L1635
to 
```
return !isInvoiceReport(linkedReport);
```
or
```
return false;
```
alternatively change 
https://github.com/Expensify/App/blob/7ba66a1542fa815eed5cb4622244bc2935593484/src/libs/ReportUtils.ts#L1632
to
```
            if (!isEmptyObject(linkedReport) && (isMoneyRequestReport(linkedReport) || isInvoiceReport(linkedReport))) {

```

**Comment by bernhardoj** [comment] 2024-07-18 08:34
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
There is an option to delete expense on a paid system message on an invoice report.

### What is the root cause of that problem?
The option to delete will show if `canDeleteReportAction` returns true.
https://github.com/Expensify/App/blob/f392cd369131e80b09e1ada8afd239d461257b24/src/libs/ReportUtils.ts#L1616-L1637

For money request action, if the money request action belongs to a money request report (IOU/expense), then it will check using `canAddOrDeleteTransactions`, otherwise, it will straightly returns true.

In our case, it's not either an IOU/expense report, but an invoice report, so `canDeleteReportAction` always returns true for the paid system message (which is also an IOU action) which shows the option to delete the message.

### What changes do you think we should make in order to solve the problem?

We can simplify the condition by following the condition from the details page as shown below:
https://github.com/Expensify/App/blob/f392cd369131e80b09e1ada8afd239d461257b24/src/pages/ReportDetailsPage.tsx#L195

https://github.com/Expensify/App/blob/f392cd369131e80b09e1ada8afd239d461257b24/src/libs/ReportUtils.ts#L1631-L1636
to
```
return isActionOwner && (canAddOrDeleteTransactions(linkedReport) || isSelfDM(linkedReport)) && !ReportActionsUtils.isDeletedAction(reportAction);
```

_we actually don't need isDeletedAction because once we delete an aciont, we can't interact with it anymore, even while offline, but I'm gonna leave that_

**Comment by CortneyOfstad** [comment] 2024-07-19 17:43
@jayeshmangwani we have a couple of proposals above when you have a chance — thank you!

**Comment by jayeshmangwani** [comment] 2024-07-22 06:23
@bernhardoj Can you please break down for us how this issue will be solved if we use the same condition from the details page?

I see you are suggesting removing the checks for `isEmptyObject` and `isMoneyRequestReport`. Will this not cause a regression if we do not check these before calling `canAddOrDeleteTransactions`?

Lastly, do we need to add an isSelfDM check here? I am not sure if the invoice will be for the self DM.

**Comment by bernhardoj** [comment] 2024-07-22 14:42
> Can you please break down for us how this issue will be solved if we use the same condition from the details page?

The money request action opens the transaction thread and to delete it, we need to delete it from the details page, so it makes sense to use the same condition for both details and money request action. If you compare the condition, they look similar,
https://github.com/Expensify/App/blob/ccf9591f3c603716afd92a26a11bc137eecd0b5e/src/libs/ReportUtils.ts#L1628-L1634
https://github.com/Expensify/App/blob/ccf9591f3c603716afd92a26a11bc137eecd0b5e/src/pages/ReportDetailsPage.tsx#L196

but the canDeleteReportAction is not really good. If `isActionOwner` is false, then it proceeds with the non-money request action logic instead of returning false. If it's not a money request report, then we always return true.

> I see you are suggesting removing the checks for isEmptyObject and isMoneyRequestReport. Will this not cause a regression if we do not check these before calling canAddOrDeleteTransactions?

canAddOrDeleteTransactions already contains the condition for isMoneyRequestReport which will returns false if it's not a money request report compared to the current logic which will return true. If it's an empty object, then isMoneyRequestReport will be false.
https://github.com/Expensify/App/blob/ccf9591f3c603716afd92a26a11bc137eecd0b5e/src/libs/ReportUtils.ts#L1589-L1592

> Lastly, do we need to add an isSelfDM check here? I am not sure if the invoice will be for the self DM.

We need it for the self DM track expense.

**Comment by jayeshmangwani** [comment] 2024-07-23 10:12
I feel that we should only add the missing `isInvoiceReport` Check here, as suggested by @FitseTLT in their alternate [Proposal](https://github.com/Expensify/App/issues/45632#issuecomment-2234719910)

https://github.com/Expensify/App/blob/7ba66a1542fa815eed5cb4622244bc2935593484/src/libs/ReportUtils.ts#L1632

🎀 👀 🎀 C+ reviewed

**Comment by CortneyOfstad** [comment] 2024-07-31 13:43
No update on the PR

**Comment by CortneyOfstad** [comment] 2024-08-12 13:22
@FitseTLT you have been paid!

@jayeshmangwani can you complete the checklist at your earliest convenience?

**Comment by CortneyOfstad** [comment] 2024-08-12 13:22
## Payment Summary

@FitseTLT — paid $250 via Upwork
@jayeshmangwani — to be paid $250 via NewDot

**Comment by jayeshmangwani** [comment] 2024-08-12 14:03
- [x]  [@jayeshmangwani] The PR that introduced the bug has been identified. Link to the PR: https://github.com/Expensify/App/pull/40303
- [x]  [@jayeshmangwani] The offending PR has been commented on, pointing out the bug it caused and why, so the author and reviewers can learn from the mistake. Link to comment: https://github.com/Expensify/App/pull/40303#issuecomment-2284067204
- [x]  [@jayeshmangwani] A discussion in #expensify-bugs has been started about whether any other steps should be taken (e.g. updating the PR review checklist) in order to catch this type of bug sooner. Link to discussion: N/A
- [x]  [@jayeshmangwani] Determine if we should create a regression test for this bug. **Yes**
- [x]  [@jayeshmangwani] If we decide to create a regression test for the bug, please propose the regression test steps to ensure the same bug will not reach production again.

### Regression Test Proposal

1. `Precondition`: Ensure the user has received an invoice.
2. Open App -> Go the invoice chat.
3. Click on the invoice preview.
4. Click on the Pay button to pay the invoice.
5. Right click on the Paid system message.
6. Verify that the `Delete Expense` option does not appear.

Do we agree 👍 or 👎

**Comment by CortneyOfstad** [comment] 2024-08-14 21:19
No worries thank you! Payment summary is linked [here](https://github.com/Expensify/App/issues/45632#issuecomment-2283981817)!

Test rail regression GH linked above, so closing!

**Closed by CortneyOfstad** 2024-08-14 21:19 UTC
Labels: External, Daily, Overdue, Awaiting Payment, Bug

**Comment by jayeshmangwani** [comment] 2024-08-15 18:11
Requested on ND as per https://github.com/Expensify/App/issues/45632#issuecomment-2283981817

**Comment by JmillsExpensify** [comment] 2024-08-21 10:55
$250 approved for @jayeshmangwani
