### ISSUE TITLE
[HOLD for payment 2024-06-20] [$250] Workspace switcher resets to All (Expensify) after page refresh

### ISSUE THREAD

**Issue by m-natarajan** [Expensify/App#42153] opened 2024-05-14 13:55 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.73-4
**Reproducible in staging?:** Yes
**Reproducible in production?:** Yes
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** @shawnborton 
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1715648972336829

## Action Performed:
1. Go the staging.new.expensify.com and login
2. Click the dropdown on the top left and choose different workspace
3. Refresh the page
## Expected Result:
The selected workspace should remain the same 
## Actual Result:
The workspace switcher changes back to all (still filtering based on the workspace picked, but the icon and title resets back to Expensify)
## Workaround:
Unknown
## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [X] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

https://github.com/Expensify/App/assets/38435837/e0e8a892-1d70-4077-a049-7a96d9b2ed23

Add any screenshot/video evidence

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~016d7c9a80aa03fdc3</li>
        <li>Upwork Job ID: 1792505861453303808</li>
        <li>Last Price Increase: 2024-05-20</li>
<li>Automatic offers: </li>
<ul>
<li>c3024 | Reviewer | 102452994</li>
<li>abzokhattab | Contributor | 102452997</li>
</ul></li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @trjExpensify</details>

**Comment by shawnborton** [comment] 2024-05-14 13:57
FWIW, this was originally reported by @GandalfGwaihir

**Comment by m-natarajan** [comment] 2024-05-14 13:57
Solution from reporter @GandalfGwaihir : We need to subscribe to the active policy using Onyx in the WorkspaceSwitcherButton component, we used to do this but in Ideal nav 2 PR, we removed it and shifted the subscription to the TopBar component, this caused the bug.

**Comment by trjExpensify** [comment] 2024-05-20 10:40
Interesting! @GandalfGwaihir @shawnborton I can reproduce this one, but only in this condition: 

1. Click on the chats tab
2. Switch to a different workspace 
3. Click the avatar in the bottom tab bar
4. Refresh the page
5. Click the chats tab in the bottom tab
6. Observe the workspace has reverted back to the Expensify "All" view

https://github.com/Expensify/App/assets/16232057/9a7164c3-6137-4629-bcf8-325e48a67235

As you can see in the video above, if I just refresh while on the Chats tab, it doesn't revert back to the All view. 

CC: @adamgrzybowski @WojtekBoman @mountiny for vis on this as well.

**Comment by c3024** [comment] 2024-05-20 11:00
OP [here](https://github.com/Expensify/App/issues/42153#issue-2295532868) says

>Actual Result:
The workspace switcher changes back to all (still filtering based on the workspace picked, but the icon and title resets back to Expensify)

so, there is clear deviation from header to LHN here in the `Actual Result` description.

But [here](https://github.com/Expensify/App/issues/42153#issuecomment-2120178541), 

>Observe the workspace has reverted back to the Expensify "All" view

Here, header and LHN are consistent. Is this a bug?

cc: @GandalfGwaihir, does your proposal fix this case as well? ^

**Comment by trjExpensify** [comment] 2024-05-20 11:03
@c3024 have you tested this on the latest staging? [This](https://github.com/Expensify/App/issues/42153#issuecomment-2120178541) was a repro video from a few mins ago. The only case I can see of reverting back to "All" is when you're on the settings bottom tab, not the `Chats` tab.

**Comment by c3024** [comment] 2024-05-20 11:13
@trjExpensify , yes I tested on `main` and saw the same behaviour as you described.

@abzokhattab Is your video of `before` on latest `main`? I don't see the workspace avatar or name resetting to Expensify and All when testing on `main`.

**Comment by abzokhattab** [comment] 2024-05-20 12:28
@c3024  you are right, i updated to main and i couldn't reproduce the original issue. 

Updated [my proposal](https://github.com/Expensify/App/issues/42153#issuecomment-2120214640) to fix the second issue

**Comment by c3024** [comment] 2024-05-21 07:27
@abzokhattab I think we prefer saving to Onyx over using a URL param. URL params are not frequently used.

For the first option, could you share a bit more about the code changes or a branch with the changes required?

**Comment by abzokhattab** [comment] 2024-05-21 10:33
There we go, here are the changes: https://github.com/Expensify/App/compare/main...abzokhattab:App:fix-chat-navigation


POC: 


https://github.com/Expensify/App/assets/59809993/7edeec31-22b2-458f-ac40-e8f58d67a122

**Comment by c3024** [comment] 2024-05-21 11:52
@abzokhattab, thanks! 

@abzokhattab's [proposal here](https://github.com/Expensify/App/issues/42153#issuecomment-2120214640) looks good to me.

🎀 👀 🎀 C+ Reviewed

**Comment by trjExpensify** [comment] 2024-05-21 11:59
>We don't handle this case on the settings page, because we don't store a policyID in the url there.
> 
>  Screen.Recording.2024-05-20.at.14.14.52.mov

Thanks, @WojtekBoman. Are we cool with the [proposed solution](https://github.com/Expensify/App/issues/42153#issuecomment-2120214640) to fix this problem of going chats > switch > settings > chats > revert back to home? I'm just kinda' curious why we didn't broach this with the ideal nav v2 changes that removed the workspace from the URL path for settings. CC: @mountiny for vis

**Comment by mountiny** [comment] 2024-05-22 10:52
I feel like both options work well, but we would have to add this to many URLs as you loose this policyID refreshing on all pages where its not in url (workspace settings).

Discussed with @WojtekBoman IRL and he will look into potential problems with the Onyx approach as then we are creating situation where there are two sources of truth and could lead to some other unintended behaviour if not done well.

If the proposal then works well, we would choose the contributor to implement it

**Comment by WojtekBoman** [comment] 2024-05-22 11:34
I've found one possible problem with the Onyx approach to store a policyID. We decided to store this param in the url to allow users to open different workspaces on different cards in a browser. 

If we store the current policyID in the Onyx, it could override it for another tab. For instance, when we open two cards with different workspaces and change a workspace on the second card and then go back to the previous one, we will have a difference between the policyID in the url and the value stored in the Onyx.

To me, we should consider storing this value in `sessionStorage`. It will keep this data after refreshing page and it won't introduce any changes to the url and every tab will store their own policyID.

**Comment by abzokhattab** [comment] 2024-05-22 11:55
>  To me, we should consider storing this value in sessionStorage. It will keep this data after refreshing page and it won't introduce any changes to the url and every tab will store their own policyID.

Good, to achieve that we can just replace the `Policy.setActiveWorkspaceID` with `sessionStorage.setItem(CONST.SESSION_STORAGE_KEYS.ACTIVE_WORKSPACE_ID,activeWorkspaceID)`  in my [branch](https://github.com/Expensify/App/compare/main...abzokhattab:App:fix-chat-navigation):
<img width="1482" alt="Screenshot 2024-05-22 at 1 14 33 PM" src="https://github.com/Expensify/App/assets/59809993/9e1d50d4-488a-46ce-83b9-8f3f4fec1e44">

then instead of connecting with oynx in the `BottomTabBar`, we can should use `sessionStorage.getItem(CONST.SESSION_STORAGE_KEYS.ACTIVE_WORKSPACE_ID);`


Let me know if this looks good to you

**Comment by mountiny** [comment] 2024-05-23 10:16
@WojtekBoman @c3024 should we pick the proposal and work on the details in the PR?

**Comment by c3024** [comment] 2024-05-24 07:36
@mountiny yes, I think @abzokhattab 's proposal is good. [This change](https://github.com/Expensify/App/issues/42153#issuecomment-2124610236) will fix the tab issue.

**Comment by mountiny** [comment] 2024-05-24 13:56
@NikkiWines all yours, seems like @abzokhattab' proposal should work well and with help of @WojtekBoman if needed, we should be able to sort this out

**Comment by NikkiWines** [comment] 2024-05-24 16:33
Nice, agreed 👍 🚀

**Comment by c3024** [comment] 2024-05-28 03:17
@abzokhattab update on PR?

**Comment by abzokhattab** [comment] 2024-05-28 09:43
Working together on it here: https://github.com/Expensify/App/pull/42684

**Comment by trjExpensify** [comment] 2024-06-20 14:17
👋 checklist time, please!

**Comment by c3024** [comment] 2024-06-21 11:52
>The PR that introduced the bug has been identified. Link to the PR:

#33280 

>The offending PR has been commented on, pointing out the bug it caused and why, so the author and reviewers can learn from the mistake. Link to comment:

https://github.com/abzokhattab/App/commit/7c7f8fa8b06ddabb5056a4f838bdb88f91823a49#r143387608

>A discussion in #expensify-bugs has been started about whether any other steps should be taken (e.g. updating the PR review checklist) in order to catch this type of bug sooner. Link to discussion:

No discussion has been started because this is not a bug that could be identified earlier.

>Determine if we should create a regression test for this bug.

Yes

>If we decide to create a regression test for the bug, please propose the [regression test](https://github.com/Expensify/App/blob/main/contributingGuides/REGRESSION_TEST_BEST_PRACTICES.md) steps to ensure the same bug will not reach production again.

### Regression Test Proposal
1. Click on the `Inbox` in the bottom tab bar.
2. Switch to a different workspace with the workspace switcher on top left of LHN.
3. Click the avatar (`Account Settings`) in the bottom tab bar.
4. Refresh the page.
5. Click on the `Inbox` in the bottom tab bar.
6. Verify that workspace switcher shows the correct selected workspace selected in Step 2.

**Comment by trjExpensify** [comment] 2024-06-24 09:50
Regression test issue created [here](https://github.com/Expensify/Expensify/issues/407128). 

Payment summary as follows: 

- $250 to @c3024 for the C+ review
- $250 to @abzokhattab for the fix

Paid, closing!

**Closed by trjExpensify** 2024-06-24 09:50 UTC
Labels: External, Daily, Overdue, Awaiting Payment, Bug
