### ISSUE TITLE
distance - Calculated amount  from waypoints is displayed on manual section on going back

### ISSUE THREAD

**Issue by kavimuru** [Expensify/App#27305] opened 2023-09-13 01:03 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. fab button -> request money -> manual
2.NOtice the amount is 0.
3. go to distance section.
4. Add waypoints.
5. share to a workspace
6. Now on the distance details page, notice the amount.
7. Now click back twice and go to manual section.
8. Notice that the amount is not 0.
## Expected Result: 
Amount on manual section should be 0.
## Actual Result: 
Calculated amount  from waypoints is displayed on manual section

## Workaround:
Can the user still use Expensify without this being fixed? Have you informed them of the workaround?

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [x] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 1.3.68-15
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/43996225/dad751d1-9cb6-45eb-a15d-a4a8dcff9e6f

https://github.com/Expensify/App/assets/43996225/ea3547fd-b1b8-4f4c-bf27-8a42c4af31cd

**Expensify/Expensify Issue URL:**
**Issue reported by:** @ashimsharma10
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1693999827026719

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by akinwale** [comment] 2023-09-13 02:48
This is a duplicate of https://github.com/Expensify/App/issues/26945

**Closed** 2023-09-13 16:22 UTC
Labels: Daily, Bug
