### ISSUE TITLE
[$500] Web - IOU - TBD shows up for preview component after uploading picture as receipt and deleting it

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#33935] opened 2024-01-04 09:52 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.21-1
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** Applause - Internal Team
**Slack conversation:**

## Action Performed:
1. Open a conversation
2. Click on plus icon inside composer
3. Click on request money > Scan receipt
4. Upload a picture which is not a receipt
5. Finish the IOU flow and wait for the scan to finish
6. After the scan finished and an error shows up go inside the IOU details page and delete the request
7. Go back to the report

## Expected Result:
TBD should not show as the preview component for the iou

## Actual Result:
The IOU preview component turns to TBD

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

https://github.com/Expensify/App/assets/93399543/bc8f1868-5c25-4b1d-823b-fcd0f7fede1f

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01c149adeb2e7da69f</li>
        <li>Upwork Job ID: 1742846560571473920</li>
        <li>Last Price Increase: 2024-01-04</li>
    </ul>
</details>

**Comment by paultsimura** [comment] 2024-01-04 10:11
## Proposal

### Please re-state the problem that we are trying to solve in this issue.


### What is the root cause of that problem?
When calculating whether to show TBD on the IOU Report view, we use this function:

https://github.com/Expensify/App/blob/3b424bba3dfd691990755ecec3be5eae1125abf9/src/libs/ReportUtils.ts#L980-L987

It returns true if the transactions list in empty.
### What changes do you think we should make in order to solve the problem?
Modify that function to return false if there are no transaction.

### What alternative solutions did you explore? (Optional)

**Comment by rojiphil** [comment] 2024-01-04 10:37
This issue is been addressed in this [PR](https://github.com/Expensify/App/pull/32698)
We can either put this on hold or close this
cc @fedirjh

**Comment by NicMendonca** [comment] 2024-01-04 21:11
thanks both! closing for now

**Closed by NicMendonca** 2024-01-04 21:11 UTC
Labels: External, Daily, Help Wanted, Bug
