### ISSUE TITLE
Chat - Chat disappears & shows skeleton when going offline (web) or backgrounding the app (native)

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#24573] opened 2023-08-15 11:23 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. IMPORTANT: Sign out and sign into the app again
2. Background the app
3. Bring the app into the foreground again

## Expected Result:
The user expects the chats in the LHN to continue displaying throughout this entire process

## Actual Result:
The chats are loading and displaying "skeletons" when the user switches the internet on and off

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android / native
- [x] Android / Chrome
- [x] iOS / native
- [x] iOS / Safari
- [x] MacOS / Chrome 
- [x] MacOS / Desktop

**Version Number:** 1.3.54.7

**Reproducible in staging?:** Yes

**Reproducible in production?:** Yes

**If this was caught during regression testing, add the test name, ID and link from TestRail:**

**Email or phone of affected tester (no customers):**

**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/78819774/6453815a-b55e-4787-a0b7-4813260cc1ef

**Expensify/Expensify Issue URL:**

**Issue reported by:** Applause - Internal Team

**Slack conversation:**

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by s-alves10** [comment] 2023-08-15 12:20
I can't reproduce this

**Comment by madmax330** [comment] 2023-08-15 13:10
I was able to reproduce, however, I don't think it's a blocker since the chat list loads up after you get back online

**Comment by marcaaron** [comment] 2023-08-17 20:41
Coming from https://github.com/Expensify/App/pull/25426#issuecomment-1682943594 the repro steps are wrong we think. It has nothing to do with inviting a WS member. Just going offline and coming back is enough to trigger it. BUT...

1. You have to have logged in during that session (not rehydrating state from storage).
2. It's on **production** already so can't be a blocker.

**Comment by s-alves10** [comment] 2023-08-17 20:48
This issue can be fixed with this [PR](https://github.com/Expensify/App/pull/25159)
Some modification might be needed

**Comment by marcaaron** [comment] 2023-08-17 20:49
In this case we are good as it's on prod already, but this looks like an otherwise legitimate blocker to me. The offending PR is [here](https://github.com/Expensify/App/pull/24204).

**Comment by aldo-expensify** [comment] 2023-08-17 21:24
> This issue can be fixed with this [PR](https://github.com/Expensify/App/pull/25159)
> Some modification might be needed

what kind of modifications? Are you saying that it doesn't fix it in the current state?

**Comment by s-alves10** [comment] 2023-08-17 21:28
If there are only a few reports, turning back on internet would show skeleton below the exiting reports with the current PR
I'm not sure if this is expected

**Comment by s-alves10** [comment] 2023-08-17 21:30
I think we need to set the expectation here before moving forward

**Comment by madmax330** [comment] 2023-08-21 12:32
@aldo-expensify going to assign you then since this is a regression cause by that PR you're assigned to.

**Comment by aldo-expensify** [comment] 2023-08-29 01:11
PR under review

**Comment by aldo-expensify** [comment] 2023-09-01 02:23
[PR](https://github.com/Expensify/App/pull/25159) is in production, verified that it is working now:


https://github.com/Expensify/App/assets/87341702/48c23236-4d34-4650-ab63-5f792e1813c2


https://github.com/Expensify/App/assets/87341702/75115180-9ac1-4537-b99f-ac4df61cc0c9

**Closed by aldo-expensify** 2023-09-01 02:23 UTC
Labels: Reviewing, Engineering, Daily
