### ISSUE TITLE
[$500]  Inconsistent Behavior When Closing Error Messages

### ISSUE THREAD

**Issue by m-natarajan** [Expensify/App#29883] opened 2023-10-18 16:51 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.3.86-1
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** @tranvantoan-qn
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1697645112450689

## Action Performed:
1. Login to any account
2. Go to OFFLINE mode.
3. Send a message to an invalid phone number, for example: +60165555559 or +842374999999.
4. Come back ONLINE. You will see two error messages displayed simultaneously.
5. Close the FIRST error message >> Observe that the user is navigated to the chat with Concierge.
6. Repeat step 2, step 3 and step 4.
7. Close the SECOND error message >> Observe that the FIRST error message remains, which is not consistent with what happened in step 5.
## Expected Result: .
Closing either of these two error messages should navigate the user to the chat with Concierge.
## Actual Result: .
Inconsistent Behavior When Closing Error Messages. Clicking the FIRST one navigates the user to the chat with Concierge, but clicking the SECOND one does not.

## Workaround:
unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [x] Android: mWeb Chrome
- [x] iOS: Native
- [x] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos
<details>
<summary>Android: Native</summary>

https://github.com/Expensify/App/assets/38435837/d410502c-43f2-49bf-9c42-019b43046204

</details>

<details>
<summary>Android: mWeb Chrome</summary>

https://github.com/Expensify/App/assets/38435837/c0f5059b-fa69-4181-be89-b9afaec4696a

</details>

<details>
<summary>iOS: Native</summary>

https://github.com/Expensify/App/assets/38435837/9002d62b-8c49-4ba9-ab08-87da44ecc674

</details>

<details>
<summary>iOS: mWeb Safari</summary>

</details>

<details>
<summary>MacOS: Chrome / Safari</summary>

https://github.com/Expensify/App/assets/38435837/f022c284-a820-4091-8a43-fb0c5a75794d

https://github.com/Expensify/App/assets/38435837/8681e59b-07f1-41df-b350-9354af5513d8

https://github.com/Expensify/App/assets/38435837/42f8374d-be73-4005-80ce-f8c218ce9f44

</details>

<details>
<summary>MacOS: Desktop</summary>

https://github.com/Expensify/App/assets/38435837/09602665-8822-4085-8485-b9735e1a14c1

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~0129abb4c288017eeb</li>
        <li>Upwork Job ID: 1714685748289875968</li>
        <li>Last Price Increase: 2023-11-01</li>
    </ul>
</details>

**Comment by tranvantoan-qn** [comment] 2023-10-18 18:37
For me, We can either navigate the user back to the chat with Concierge or let them close each error **one by one**, since it is important to keep the logic consistent.

**Comment by Santhosh-Sellavel** [comment] 2023-10-20 22:16
@miljakljajic Can you check/confirm what's the expectations?

**Comment by Santhosh-Sellavel** [comment] 2023-10-24 20:02
bump @miljakljajic

**Comment by DylanDylann** [comment] 2023-10-30 11:48
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
- Inconsistent Behavior When Closing Error Messages

### What is the root cause of that problem?
- Firstly, we need to note that the phone numbers that are mentioned in the report bug are valid phone numbers  ( +60165555559 or +842374999999). And the two errors that we are encoutering after come back to "online" mode are:
1. When calling "OpenReport" API, BE returns "**The provided phone number does not match the country you are currently located in, please use your email address instead**" because the current user country code and the phone number that we want to send message are not the same. **Clicking to close this error** message will navigate the user to the concierge report is our expected:
https://github.com/Expensify/App/blob/2707647bdc905f7ee0cedbaabb8ec30f9b505d2a/src/pages/home/report/ReportActionItemCreated.js#L64

2.  When calling "AddComment" API, BE returns "**Report no longer exists**" because the report is not created. **Clicking to remove this error** without redirecting to concierge report is expected as well because it is just a comment`s error, not a report`s error.
- So i think just need to add the **improvement** in this case: We can prevent user from creating a conversation with the phone number that is not the same country as the current user. So user can not open the report with that phone number, and no more comments can be added in the future.
### What changes do you think we should make in order to solve the problem?
- We can prevent user from create the conversation with the phone number that is not the same country code with current user by using ```countryCodeByIP``` variable:
https://github.com/Expensify/App/blob/92813426a67df9b9a934d62dd9b1e4c41f5171a8/src/libs/LocalePhoneNumber.ts#L6-L10
- So when user are in country code for example +66, searching "+60165555559" will still display it in the result but disable selecting this phone number option

### What alternative solutions did you explore? (Optional)

- NA

**Comment by Santhosh-Sellavel** [comment] 2023-10-30 17:53
@miljakljajic  bump!

> @miljakljajic Can you check/confirm what's the expectations?

**Comment by miljakljajic** [comment] 2023-11-02 15:18
This seems like expected behaviour - we wouldn't need to redirect the user to Concierge each time. apologies for the delay, I was out of the office. Closing.

**Closed by miljakljajic** 2023-11-02 15:18 UTC
Labels: External, Daily, Help Wanted, Overdue, Bug

**Comment by DylanDylann** [comment] 2023-11-02 15:20
@miljakljajic what about the improvement that i mentioned in my proposal:

> So i think just need to add the improvement in this case: We can prevent user from creating a conversation with the phone number that is not the same country as the current user. So user can not open the report with that phone number, and no more comments can be added in the future.
