### ISSUE TITLE
[WAITING ON MIROSLAV] [HOLD for payment 2023-10-02]  🟢  [$500] Update 'Add Stop' to directly navigate to the waypoint editor

### ISSUE THREAD

**Issue by hayata-suenaga** [Expensify/App#26888] opened 2023-09-06 15:57 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
_I recommend following the following reproduction steps in a fresh account_
1. Open NewDot on Chrome
1. Go to a workspace chat
2. Click on the "+" icon next to the text composer
3. Select "Request money" and then choose "Distance"
4. Add addresses for "Start" and "Finish"
5. Click "Add stop" several times to create empty "Stop"s
6. Click "Next"
7. Open the developer console of Chrome and go to the Application tab > Storage > IndexedDB -> OnyxDB -> keyvaluepairs
8. Find the draft transaction being created. You can type "transaction" on the search field.
    _This is tricky if you have already several transactions. That's the reason I recommends using a new account_
    <img width="400" alt="Screenshot 2023-09-06 at 8 51 40 AM" src="https://github.com/Expensify/App/assets/98560306/9a4135af-ece4-4da6-9280-d6fcac0dbead">

## Expected Result:
Waypoints should only contains valid waypoints, and none of them should be unfilled.
    <img width="400" alt="Screenshot 2023-09-06 at 8 48 27 AM" src="https://github.com/Expensify/App/assets/98560306/8d02157a-8112-4678-90bc-628dc5a087c7">

## Actual Result:
Invalid / empty waypoints are in transaction.
    <img width="400" alt="Screenshot 2023-09-06 at 8 56 39 AM" src="https://github.com/Expensify/App/assets/98560306/b67847d0-8451-4e5a-b040-21b4f1e34d11">

## Workaround:
This doesn't affect the user directly, but the Onyx data should be cleaned to reflect the state of the database.

## Platforms:

Which of our officially supported platforms is this issue occurring on?
_You can inspect the issue only on Chrome_
- [x] Android / native
- [x] Android / Chrome
- [x] iOS / native
- [x] iOS / Safari
- [x] MacOS / Chrome / Safari
- [x] MacOS / Desktop

**Version Number:**
**Reproducible in staging?:** Yes
**Reproducible in production?:** Yes
**If this was caught during regression testing, add the test name, ID and link from TestRail:** N/A
**Email or phone of affected tester (no customers):** N/A
**Logs:** N/A
**Notes/Photos/Videos:**
**Expensify/Expensify Issue URL:** N/A
**Issue reported by:** Internal engineer
**Slack conversation:** https://expensify.slack.com/archives/C05DWUDHVK7/p1693959000958689?thread_ts=1693949572.430099&cid=C05DWUDHVK7

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01be476129f2f20c23</li>
        <li>Upwork Job ID: 1701078084614434816</li>
        <li>Last Price Increase: 2023-09-11</li>
<li>Automatic offers: </li>
<ul>
<li>0xmiroslav | Reviewer | 26728805</li>
<li>DylanDylann | Contributor | 26728807</li>
</ul></li>
    </ul>
</details>

**Comment by neil-marcellini** [comment] 2023-09-06 16:01
Following. I would like to review the PR.

**Comment by hayata-suenaga** [comment] 2023-09-11 03:40
I don't have the bandwidth to open a PR right now, so I'm making this issue external

**Comment by DylanDylann** [comment] 2023-09-11 05:00
## Proposal


### Please re-state the problem that we are trying to solve in this issue.
Delete unfilled waypoints from Onyx data before moving to the confirmation screen

### What is the root cause of that problem?
This is a new improvement
### What changes do you think we should make in order to solve the problem?
When the user clicks "add stop" we will direct to Address waypoint page and we only create a new stop if the user selects address as new expected [here](https://github.com/Expensify/App/issues/26888#issuecomment-1708938445) that is proposed by @fedirjh 

To do that:
1. In here
https://github.com/Expensify/App/blob/f896f71a1ce00320a2ba029e44396d4e29b88223/src/components/DistanceRequest.js#L231

we will redirect the user to the waypoint address page and not use addStop function anymore (maybe delete it)
```
onPress={() => {
                        const existingWaypoints = lodashGet(transaction, 'comment.waypoints', {});
                        const newLastIndex = _.size(existingWaypoints);
                        Navigation.navigate(ROUTES.getMoneyRequestWaypointRoute('request', newLastIndex))
 }}
```
2. In step 1, we redirect to the new waypoint address page with index === newLastIndex. It means that if we have a start point and a finish point and then click add stop, the index of the new stop is 2. But when displaying the waypoint list, we always display the last index as the finish waypoint. This bug is created before [here](https://github.com/Expensify/App/issues/27073) 

To fix that
In here:
https://github.com/Expensify/App/blob/6488e9fd74fcffb6780a28fc401973ecec65d3e5/src/pages/iou/WaypointEditor.js#L156
https://github.com/Expensify/App/blob/6488e9fd74fcffb6780a28fc401973ecec65d3e5/src/pages/iou/WaypointEditor.js#L136

Instead of only saving the new waypoint, we also update the index of the finish waypoint (to ensure that the last index always be the finish waypoint) like this
```
if(parsedWaypointIndex < _.size(allWaypoints)) {       // Check if this is creating new stop point 
                Transaction.saveWaypoint(transactionID, waypointIndex, waypoint);
} else {
                const finishWaypoint = lodashGet(allWaypoints, `waypoint${_.size(allWaypoints)-1}`, {});
                Transaction.saveWaypoint(transactionID, waypointIndex, finishWaypoint);
                Transaction.saveWaypoint(transactionID, waypointIndex - 1 , waypoint);
}


```
Optional, We can create a util function for a cleaner

3. With this approach, we also need to update the condition here

https://github.com/Expensify/App/blob/6488e9fd74fcffb6780a28fc401973ecec65d3e5/src/pages/iou/WaypointEditor.js#L166

Remove this condition `parsedWaypointIndex > waypointCount - 1` or update like this `parsedWaypointIndex > waypointCount`

### Result 

https://github.com/Expensify/App/assets/141406735/a7b7a485-31c5-4d1a-8bb4-7b83f2eda3b1

### What alternative solutions did you explore? (Optional)

**Comment by Pluto0104** [comment] 2023-09-11 05:32
## Proposal
### Please re-state the problem that we are trying to solve in this issue.
Delete unfilled waypoints from Onyx data before moving to the confirmation screen.
### What is the root cause of that problem?
There is no specific root cause as this is a new feature aimed at optimizing Onyx data.
### What changes do you think we should make in order to solve the problem?
Our first step would be to introduce a new function within [Transaction.js](https://github.com/Expensify/App/blob/main/src/libs/actions/Transaction.js), outlined as follows:
```js
function setWaypoints(transactionID, waypoints) {
    const transaction = lodashGet(allTransactions, transactionID, {});
    Onyx.set(`${ONYXKEYS.COLLECTION.TRANSACTION}${transactionID}`, {
        ...transaction,
        comment: {
            ...transaction.comment,
            waypoints,
        },
    });
}
```
Next, we will integrate the necessary logic in the following section:
https://github.com/Expensify/App/blob/6488e9fd74fcffb6780a28fc401973ecec65d3e5/src/components/DistanceRequest.js#L266
```js
onPress={() => {
    Transaction.setWaypoints(iou.transactionID, validatedWaypoints);
    IOU.navigateToNextPage(iou, iouType, reportID, report);
}}
```
This solution ensures that only validated waypoints are set to the transaction data when the "Next" button is pressed.
### What alternative solutions did you explore? (Optional)
N/A

**P.S.**
I've taken a look at the other proposals here, and it appears they only address handling empty objects {} and not invalid waypoints. Fortunately, we have validatedWaypoints readily available, which we can utilize to set transaction data. My suggested approach relies on this, making it a more consistent solution compared to the others.

**Result**

https://github.com/Expensify/App/assets/136573674/9e81f709-02e2-4867-9068-dc25b72141c9

**Comment by hayata-suenaga** [comment] 2023-09-11 06:22
@0xmiroslav could you review proposals when you have time?

**Comment by hayata-suenaga** [comment] 2023-09-11 06:47
> @hayata-suenaga if we clear unfilled waypoints when move to Confirmation screen, original state (with unfilled waypoints) will not be preserved when click back button or refresh page and go /distance route directly. Is it fine?

yep that' fine 👍 

> Personally I like the UX what @fedirjh https://github.com/Expensify/App/issues/26888#issuecomment-1708938445, combined with drag & drop for sort (this is WIP I believe).

I'm checking with the internal team about this potential UX change. I'll get back to you once we decide if we go with this proposal or not

**Comment by hayata-suenaga** [comment] 2023-09-11 07:32
@0xmiroslav so... we decided not to go with @fedirjh's UX proposal. Can you select a proposal that actually remove the unfilled waypoints from the Onyx data?

**Comment by Pluto0104** [comment] 2023-09-11 10:43
Hey @Nikhil-Vats, of course, that's a valid point. However, I want to clarify that my proposal provides pseudo-code, not the complete code. I've come across those functions that clear the coordinates of the route, but that's not the main issue I'm addressing. 😄

**Comment by shawnborton** [comment] 2023-09-11 15:11
Interesting. I kind of love that tapping "Add stop" takes you right to the push-to-page edit screen for that stop, it does feel way smoother IMO and I personally don't find it jarring.

**Comment by DylanDylann** [comment] 2023-09-11 15:48
@0xmiroslav Re-post the proposal with [another expected](https://github.com/Expensify/App/issues/26888#issuecomment-1714087058) 

## Proposal
### Please re-state the problem that we are trying to solve in this issue.
Delete unfilled waypoints from Onyx data before moving to the confirmation screen

### What is the root cause of that problem?
This is a new improvement

### What changes do you think we should make in order to solve the problem?
When the user clicks "add stop" we will direct to Address waypoint page and we only create a new stop if the user selects address as new expected https://github.com/Expensify/App/issues/26888#issuecomment-1708938445 that is proposed by @fedirjh

To do that:

In here
https://github.com/Expensify/App/blob/f896f71a1ce00320a2ba029e44396d4e29b88223/src/components/DistanceRequest.js#L231
we will redirect the user to the waypoint address page and not use addStop function anymore (maybe delete it)
```
onPress={() => {
                        const existingWaypoints = lodashGet(transaction, 'comment.waypoints', {});
                        const newLastIndex = _.size(existingWaypoints);
                        Navigation.navigate(ROUTES.getMoneyRequestWaypointRoute('request', newLastIndex))
 }}
```
In step 1, we redirect to the new waypoint address page with index === newLastIndex. It means that if we have a start point and a finish point and then click add stop, the index of the new stop is 2. But when displaying the waypoint list, we always display the last index as the finish waypoint. This bug is created before https://github.com/Expensify/App/issues/27073
To fix that
In here:
https://github.com/Expensify/App/blob/6488e9fd74fcffb6780a28fc401973ecec65d3e5/src/pages/iou/WaypointEditor.js#L156
https://github.com/Expensify/App/blob/6488e9fd74fcffb6780a28fc401973ecec65d3e5/src/pages/iou/WaypointEditor.js#L136

Instead of only saving the new waypoint, we also update the index of the finish waypoint (to ensure that the last index always be the finish waypoint) like this
```
if(parsedWaypointIndex < _.size(allWaypoints)) {       // Check if this is creating new stop point 
                Transaction.saveWaypoint(transactionID, waypointIndex, waypoint);
} else {
                const finishWaypoint = lodashGet(allWaypoints, `waypoint${_.size(allWaypoints)-1}`, {});
                Transaction.saveWaypoint(transactionID, waypointIndex, finishWaypoint);
                Transaction.saveWaypoint(transactionID, waypointIndex - 1 , waypoint);
}

```
Optional, We can create a util function for a cleaner

With this approach, we also need to update the condition here
https://github.com/Expensify/App/blob/6488e9fd74fcffb6780a28fc401973ecec65d3e5/src/pages/iou/WaypointEditor.js#L166

Remove this condition parsedWaypointIndex > waypointCount - 1 or update like this `parsedWaypointIndex > waypointCount`

Result
https://github.com/Expensify/App/assets/141406735/a7b7a485-31c5-4d1a-8bb4-7b83f2eda3b1

What alternative solutions did you explore? (Optional)

**Comment by DylanDylann** [comment] 2023-09-11 15:50
@shawnborton Could you check the this video and confirm if this is expected
https://github.com/Expensify/App/assets/141406735/a7b7a485-31c5-4d1a-8bb4-7b83f2eda3b1

**Comment by shawnborton** [comment] 2023-09-11 16:04
Interesting, I kinda would expect "Add Stop" to just add the new waypoint to the very end, not in the middle. Curious what others think though.

**Comment by hayata-suenaga** [comment] 2023-09-12 03:03
@JmillsExpensify let use know your thoughts on this ⬆️

**Comment by Pluto0104** [comment] 2023-09-12 04:18
Hello, @0xmiroslav, @hayata-suenaga, can you please explain why we require another distance transaction? Would it be acceptable to use just one distance transaction?

**Comment by hayata-suenaga** [comment] 2023-09-12 05:27
> can you please explain why we require another distance transaction? Would it be acceptable to use just one distance transaction?

@Pluto0104 can you clarify your question?

**Comment by Pluto0104** [comment] 2023-09-12 05:35
@hayata-suenaga could you please take a look [here](https://github.com/Expensify/App/issues/26888#issuecomment-1713593139)?

**Comment by hayata-suenaga** [comment] 2023-09-12 05:39
ah I see

we're not deleting draft transactions created?

**Comment by Pluto0104** [comment] 2023-09-12 05:40
yes, in that case, how can we do?

**Comment by hayata-suenaga** [comment] 2023-09-12 05:41
I think we can take care of that issue here.

@Pluto0104 do you have a proposal for it?

**Comment by Pluto0104** [comment] 2023-09-12 05:43
Hmm, I believe we can utilize just one set of distance transaction data for this purpose and make necessary edits or resets as needed.

**Comment by Pluto0104** [comment] 2023-09-12 05:47
If we don't want to modify current logic, alternatively, we can employ this function to remove distance transaction data that contains empty waypoints, and also tidy up any other data with invalid waypoints.
```js
function cleanDistanceRequests() {
  _.each(allTransactions, (transaction) => {
    const waypoints = lodashGet(transaction, "comment.waypoints");
    const transactionID = lodashGet(transaction, "transactionID");

    // handle non-distance transaction data
    if (!waypoints || !transactionID) {
      return;
    }

    // handle distance transaction data
    const validWaypoints = TransactionUtils.getValidWaypoints(waypoints, true);
    Onyx.set(
      `${ONYXKEYS.COLLECTION.TRANSACTION}${transactionID}`,
      _.size(validWaypoints) > 1
        ? {
            ...transaction,
            comment: {
              ...transaction.comment,
              waypoints: validWaypoints,
            },
            routes: {
              route0: {
                geometry: {
                  coordinates: null,
                },
              },
            },
          }
        : null
    );
  });
}
```

**Comment by Pluto0104** [comment] 2023-09-12 05:53
@hayata-suenaga, would you like me to create a proposal? However, I'm not entirely certain if there are as many UX issues as we've been discussing in the comments above.

**Comment by hayata-suenaga** [comment] 2023-09-12 10:50
> if there are as many UX issues as we've been discussing in the comments above.

sorry which one are you taking about 😓

**Comment by Pluto0104** [comment] 2023-09-12 10:52
> sorry which one are you taking about 😓

https://github.com/Expensify/App/issues/26888#issuecomment-1714087058
https://github.com/Expensify/App/issues/26888#issuecomment-1714220264

**Comment by hayata-suenaga** [comment] 2023-09-13 04:30
@JmillsExpensify 

coming from [this slack thread](https://expensify.slack.com/archives/C05DWUDHVK7/p1694412800548889), could you check [these comments](https://github.com/Expensify/App/issues/26888#issuecomment-1715496345) and see if we should implement the change suggested [here](https://github.com/Expensify/App/issues/26888#issuecomment-1708938445)?

**Comment by thienlnam** [comment] 2023-09-15 04:48
Taking this over from Hayata https://expensify.slack.com/archives/C05DWUDHVK7/p1694733251543699

**Comment by JmillsExpensify** [comment] 2023-09-15 04:50
> Interesting. I kind of love that tapping "Add stop" takes you right to the push-to-page edit screen for that stop, it does feel way smoother IMO and I personally don't find it jarring.

Ok cool, that approach sounds good @shawnborton. I see several votes for this option. Let's do it and keep our ear to the ground on user feedback to see if anything comes up.

**Comment by JmillsExpensify** [comment] 2023-09-15 04:51
>@shawnborton Oh that is interesting. I think adding it in the middle is what I would expect! Haha. I'm thinking about it like this:
> I have my start (where I am), my destination (finish), and then I'm adding stops along the way to that destination. But this is just how I think about it. I don't really think there is a "wrong" answer here.

I agree with @dannymcclain on this one.

**Comment by thienlnam** [comment] 2023-09-15 04:53
Okay - latest update for this issue we're going to go with the new proposed UI solution [here](https://github.com/Expensify/App/issues/26888#issuecomment-1708938445)
1. Pressing 'Add Stop' will directly send you to the Waypoint Editor
2. A new stop will get added in the middle (I believe this already happens though)

Let's get some proposals for this new direction!

**Comment by DylanDylann** [comment] 2023-09-15 04:58
I updated [proposal](https://github.com/Expensify/App/issues/26888#issuecomment-1714153645) to match new direction

**Comment by DylanDylann** [comment] 2023-09-15 05:15
@0xmiroslav I think it is an invalid proposal as mentioned [here](https://github.com/Expensify/App/blob/main/contributingGuides/CONTRIBUTING.md)
```
After you reproduce the issue, complete the [proposal template here](https://github.com/Expensify/App/blob/main/contributingGuides/PROPOSAL_TEMPLATE.md) and post it as a comment in the corresponding GitHub issue (linked in the Upwork job).
```

It seems that he suggested a new feature not post a proposal

**Comment by thienlnam** [comment] 2023-09-18 09:29
Going to move forward with the provided solution from @DylanDylann as there isn't a new proposal yet

**Comment by DylanDylann** [comment] 2023-09-18 11:53
@0xmiroslav The PR is ready for review

**Comment by DylanDylann** [comment] 2023-09-18 11:57
<img width="899" alt="Screenshot 2023-09-18 at 18 57 09" src="https://github.com/Expensify/App/assets/141406735/3bbb1878-be4d-47e9-98ff-03a2152a70e0">

@0xmiroslav This is screenshot

**Comment by DylanDylann** [comment] 2023-09-18 12:00
@0xmiroslav Thanks so much for your reminder. Noted in the future

**Comment by jliexpensify** [comment] 2023-09-21 23:41
Not overdue

**Comment by jliexpensify** [comment] 2023-09-25 07:45
Payment Summary:

- Contributor: @DylanDylann $500 + $250 (speed bonus)
- C+: @0xmiroslav  $500 + $250 (speed bonus)

[Upwork job](https://www.upwork.com/jobs/~01be476129f2f20c23)

**Comment by jliexpensify** [comment] 2023-10-02 06:36
Updated payment date, looks like it was just deployed to prod 3 days ago? Correct me if I am wrong here!

**Comment by jliexpensify** [comment] 2023-10-03 04:08
Cheers, paying now.

@0xmiroslav any need for a checklist? Also are you ready tor receive payments yet?

**Comment by jliexpensify** [comment] 2023-10-03 04:09
Paid out @DylanDylann

**Comment by jliexpensify** [comment] 2023-10-06 04:02
Bumpo @0xmiroslav to complete the checklist. Also, do you want me to close this out?

**Closed** 2023-10-06 04:17 UTC
Labels: External, Engineering, Daily, Awaiting Payment
