### ISSUE TITLE
[$500] Expense - Add your bank account not responding&console error when opening expense as employe

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#34936] opened 2024-01-22 23:17 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.29-1
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**If this was caught during regression testing, add the test name, ID and link from TestRail:** https://expensify.testrail.io/index.php?/tests/view/4211882
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** Applause - Internal Team
**Slack conversation:**

## Action Performed:
1. Log into OD with a new Gmail account
2. Create a Collect policy and enable rooms
3. Invite a new Gmail account as an employee
4. Log into ND as an employee
5. Request money from the WS and submit it
6. Log into ND as an admin and approve it
7. In OD select Reimbursement > Direct
8. Add a fully verified VBA
9. Navigate to ND as an employee
10. Open the expense
11. Click on "Add your bank account" hyperlink below the header

## Expected Result:
User is navigated to add bank account modal and there is no console error

## Actual Result:
The "Add your bank account" hyperlink is not responding to a click/tap, and there is a console error when opening the expense as an employee

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [x] Android: mWeb Chrome
- [x] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details>  

https://github.com/Expensify/App/assets/78819774/6961d8a0-c6e5-42aa-a825-7d609a9377d7

![Bug6351176_1705960192994!console_error](https://github.com/Expensify/App/assets/78819774/2c9f1dab-e2ae-488f-ab49-66ac25c41c07)

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01f5925435db4574ed</li>
        <li>Upwork Job ID: 1749572047170543616</li>
        <li>Last Price Increase: 2024-02-05</li>
    </ul>
</details>

**Comment by shubham1206agra** [comment] 2024-01-30 04:27
No proposals yet.

**Comment by Christinadobrzyn** [comment] 2024-02-06 00:33
I think we need to get this involved in a Project or we need to close it but I haven't been able to reproduce this yet so I think that's the first part, ensure we can reproduce this and then add it to a project

**Comment by shubham1206agra** [comment] 2024-02-06 13:54
> hey @shubham1206agra have you been able to reproduce this? How do I test this step in the OP:
> 
> > 2. Create a Collect policy and enable rooms

@Christinadobrzyn Please try https://github.com/Expensify/App/pull/34127 QA steps to get through this step.

**Comment by Christinadobrzyn** [comment] 2024-02-06 23:34
Thanks thanks @shubham1206agra! I just tested this following the [QA steps ](https://github.com/Expensify/App/pull/34127)and I'm not getting an error. Both have the same bank account. 

https://github.com/Expensify/App/assets/51066321/150b7502-109f-4071-895b-ce939d2c4547

It looks like PR https://github.com/Expensify/App/pull/34127 is related to https://github.com/Expensify/App/issues/33524

So does that mean that this issue isn't happening anymore? I'm confused.

**Comment by shubham1206agra** [comment] 2024-02-07 02:17
I don't think so you followed the steps correctly here.

**Comment by Christinadobrzyn** [comment] 2024-02-08 00:25
I'll ask QA to test again and see if this is resolved. https://expensify.slack.com/archives/C9YU7BX5M/p1707351945352359

**Comment by kbecciv** [comment] 2024-02-08 14:30
Issue is not reproduced on build 1.4.38.0

https://github.com/Expensify/App/assets/93399543/fdc6b5c3-2601-46a0-8343-58224ee74d22

**Comment by shubham1206agra** [comment] 2024-02-08 14:38
It looks like the hyperlink was removed. 😄

**Comment by Christinadobrzyn** [comment] 2024-02-08 22:31
awesome! I think this can be closed. Feel free to let me know if anyone feels otherwise. thanks!

**Closed by Christinadobrzyn** 2024-02-08 22:31 UTC
Labels: External, Daily, Help Wanted, Bug
