### ISSUE TITLE
[HOLD for payment 2024-06-13] [$250] Workspace - Missing options from settings if a WS is created on another device with same acc

### ISSUE THREAD

**Issue by izarutskaya** [Expensify/App#40686] opened 2024-04-22 11:49 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.62.17
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**Found when executing PR :** https://github.com/Expensify/Expensify/issues/281020
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Issue reported by:** Applause-Internal team

## Action Performed:
1. Device 1: Log in with a new Gmail account
2. Device 2: Log in with the same account
3. Device 1: Create a workspace
4. Device 2: Navigate to the workspace settings
4. Device 2: Click on members

## Expected Result:
All settings should be available for the second device.

## Actual Result:
Missing options from settings if a WS is created on another device with same account. The missing options are: "Categories" and "More features" from the settings tab, "Description", "Share" and "Delete" from the "Profile tab, "Invite members" from the "Members" tab. The settings are restored after relogging.

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

https://github.com/Expensify/App/assets/115492554/212a863c-7954-4a6f-b01e-ba1b73d78ba4

https://github.com/Expensify/App/assets/115492554/60cb13c0-4921-4bea-8bdb-ab8aa9a5ea1f

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01133e97d014430d38</li>
        <li>Upwork Job ID: 1784518575691853824</li>
        <li>Last Price Increase: 2024-05-05</li>
<li>Automatic offers: </li>
<ul>
<li>eh2077 | Reviewer | 0</li>
</ul></li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @laurenreidexpensify</details>

**Comment by izarutskaya** [comment] 2024-04-22 11:49
We think this issue might be related to the #collect project.

**Comment by laurenreidexpensify** [comment] 2024-04-25 11:37
@trjExpensify - what you reckon - this wave-collect / a priority?

**Comment by trjExpensify** [comment] 2024-04-27 10:33
Yeah, we should fix that. Very strange. It's treating the user on the second device like a mere member, not an admin. The majority of the workspace settings aren't visible to a member, only profile (read-only) and members list (without the ability to add anyone new).

**Comment by eh2077** [comment] 2024-05-01 07:56
@dragnoir 's [proposal](https://github.com/Expensify/App/issues/40686#issuecomment-2069524832) looks good to me. I agreed with their RCA and the solution. Implementation details can be discussed in PR.

🎀👀🎀 C+ reviewed

**Comment by stitesExpensify** [comment] 2024-05-02 01:48
Can you explain why we have 2 `employeeList` objects? It looks like they have the same information...?

**Comment by stitesExpensify** [comment] 2024-05-02 20:25
Okay. Should we _always_ look at the policy employee list for `isAdmin`? My concern here is that looking for something in 2 places seems like an anti-pattern. We should know where data is, and always look there. Ideally we should not have any duplicated data either

**Comment by eh2077** [comment] 2024-05-06 04:27
I found that `policyDraft` also has `employeeList`
https://github.com/Expensify/App/blob/0c2d5130727105535ee16ec0b5e932456ce3fea5/src/libs/actions/Policy.ts#L2086-L2112

> Should we always look at the policy employee list for `isAdmin`?

So, I think it'll be neat to only check `employeeList`.

cc @stitesExpensify @dragnoir

**Comment by eh2077** [comment] 2024-05-06 11:37
> If we use `employeeList` from Policy, the value will be available from all devices.

@dragnoir This is exactly what I mean given they're coalesced here
https://github.com/Expensify/App/blob/98d85e0863fe62292a7a086f6cf4bfb4c5b59fdc/src/pages/workspace/WorkspaceInitialPage.tsx#L81

**Comment by eh2077** [comment] 2024-05-07 02:59
Not overdue, waiting for @stitesExpensify to check if it's good to assign or not

**Comment by stitesExpensify** [comment] 2024-05-09 22:59
Hmm @laurenreidexpensify do you know how we can get a new CME assigned to this? I'm about to go OOO and need someone to take over for me while I'm gone

**Comment by laurenreidexpensify** [comment] 2024-05-10 06:24
🎀👀🎀 C+ reviewed

**Comment by laurenreidexpensify** [comment] 2024-05-10 06:25
@eh2077 can you do me a favour and repaste this message - https://github.com/Expensify/App/issues/40686#issuecomment-2088114408 - so we can get another internal eng assigned to watch while @stitesExpensify is out thanks

**Comment by eh2077** [comment] 2024-05-10 08:03
Sure

🎀👀🎀 C+ reviewed

**Comment by eh2077** [comment] 2024-05-18 01:20
Still working on the PR

**Comment by rlinoz** [comment] 2024-05-31 13:07
PR merged today, waiting for next deploy.

**Comment by laurenreidexpensify** [comment] 2024-06-13 10:22
Payment Summary - 

- contributor @dragnoir paid in upwork $250 
- C+ @eh2077 paid in upwork $250 

@eh2077 please confirm the the checklist steps above thanks

**Comment by laurenreidexpensify** [comment] 2024-06-14 08:59
@eh2077 please confirm the the checklist steps above s so we can close this out thank

**Comment by eh2077** [comment] 2024-06-14 09:43
### Checklist

- [x] [@eh2077] The PR that introduced the bug has been identified. Link to the PR: _**I don't think there's a PR which is responsible for it. This is a missing edge case we choose to polish**_
- [x] [@eh2077] The offending PR has been commented on, pointing out the bug it caused and why, so the author and reviewers can learn from the mistake. Link to comment: N/A
- [x] [@eh2077] A discussion in #expensify-bugs has been started about whether any other steps should be taken (e.g. updating the PR review checklist) in order to catch this type of bug sooner. Link to discussion: N/A
- [x] [@eh2077] Determine if we should create a regression test for this bug. No

**Comment by eh2077** [comment] 2024-06-14 09:43
@laurenreidexpensify Checklist completed, thanks for the bump

**Closed** 2024-06-17 08:45 UTC
Labels: External, Daily, Overdue, Awaiting Payment, Bug
