### ISSUE TITLE
[HOLD for payment 2024-08-01] [$500] Keyboard focus is on the "close" button when uploading an attachment

### ISSUE THREAD

**Issue by m-natarajan** [Expensify/App#43726] opened 2024-06-13 19:56 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** v1.4.83-0
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** @quinthar 
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1718296177557209

## Action Performed:
1. Go to staging.new.expensify.com
2. Open any report and add attachment
3. Press "enter" key on keyboard
## Expected Result:
Keyboard focus on "Send" button and image sent
## Actual Result:
 Keyboard focus on cancel button and pressing "enter" on keyboard cancels the upload
## Workaround:
Unknown
## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [X] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence
![image (8)](https://github.com/Expensify/App/assets/38435837/cf27e6b4-1914-4c60-b9a6-17f148f76a10)

https://github.com/Expensify/App/assets/38435837/3f301e26-1397-4d01-b8fc-bc05f255478f

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01ab436ac7382c9793</li>
        <li>Upwork Job ID: 1802770011901307524</li>
        <li>Last Price Increase: 2024-07-08</li>
<li>Automatic offers: </li>
<ul>
<li>rojiphil | Reviewer | 103095843</li>
<li>suneox | Contributor | 103095845</li>
</ul></li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @CortneyOfstad</details>

**Comment by tsa321** [comment] 2024-06-13 23:33
Cannot reproduce in production release. 
offending PR: https://github.com/Expensify/App/pull/39520

**Comment by tsa321** [comment] 2024-06-14 01:38
## Proposal

### Please re-state the problem that we are trying to solve in this issue.

Keyboard focus is on the "close" button when uploading an attachment

### What is the root cause of that problem?

We introduce focusTrap in https://github.com/Expensify/App/pull/39520
But in react-native-modal we already have focusTrap:

https://github.com/necolas/react-native-web/blob/master/packages/react-native-web/src/exports/Modal/ModalFocusTrap.js

### What changes do you think we should make in order to solve the problem?

We can remove the new focusTrap and use react native web focusTrap.


Another alternative solution is to include the attachment screen in: 

include the coresponding attachment modal screen in `SCREENS_WITH_AUTOFOCUS`.
https://github.com/Expensify/App/blob/2a641d98760dfdc1a2ebe9b958787c9cfacb02c2/src/components/FocusTrap/SCREENS_WITH_AUTOFOCUS.ts#L4

**Comment by CortneyOfstad** [comment] 2024-06-17 18:28
I was able to recreate so going to get some eyes on this. @rojiphil we have a proposal [here](https://github.com/Expensify/App/issues/43726#issuecomment-2167055802) for review when you have a chance!

**Comment by CortneyOfstad** [comment] 2024-06-19 16:27
@rojiphil can you provide feedback on the proposal [here](https://github.com/Expensify/App/issues/43726#issuecomment-2167055802) by EOD please? Thanks!

**Comment by rojiphil** [comment] 2024-06-21 19:15
Based on the OP test steps, I am unable to launch the `Attachment` modal on press of `Enter` key. Maybe I am missing something here. 
@tsa321 Are you able to reproduce the problem on the latest main? If so, please share a video as well.

**Comment by tsa321** [comment] 2024-06-21 19:36
@rojiphil I cannot reproduce it anymore, but I found another bug because of the new focusTrap in baseModal:

Send an attachment -> edit a report action (keep the focus in compose edit) -> open the attachment -> press back browser back button. Notice the edit composer isn't highlighted. 

https://github.com/Expensify/App/assets/114975543/cd59e94f-8c5a-4d1c-804f-49dd51a65be6

Maybe there are another bugs too. So my suggestion is, since baseModal (react-native-modal) already has focusTrap in it:

https://github.com/necolas/react-native-web/blob/master/packages/react-native-web/src/exports/Modal/ModalFocusTrap.js

We could remove the new focusTrap.

**Comment by rojiphil** [comment] 2024-06-24 06:26
> I cannot reproduce it anymore, but I found another bug because of the new focusTrap in baseModal:

@tsa321 As the raised issue is completely different, it is best to raise it separately and go through the normal assignment process. You can raise this in the `expensify-open-source` channel.

**Comment by rojiphil** [comment] 2024-06-24 06:27
@CortneyOfstad We can close this issue as it is not reproduceable

**Comment by CortneyOfstad** [comment] 2024-06-24 15:45
Sounds good — thanks @rojiphil! I was not able to reproduce again either!

**Comment by mallenexpensify** [comment] 2024-06-28 16:39
This is still happening on staging and production. 

- open chat
- paste in an image
- tap enter/return. 

Expected behavior - image uploads

Actual behaviour - nothing happens, you have to navigate to the send button and click. 

@CortneyOfstad , if you're unable to reproduce, please swap assignments with me.  Thx

**Comment by mallenexpensify** [comment] 2024-07-01 19:48
@tsa321 @rojiphil can you both try to reproduce again? If you're **not** able to reproduce, can you share your steps?  I'm able to consistently. Thx

**Comment by CortneyOfstad** [comment] 2024-07-03 15:15
@tsa321 @rojiphil bump on the above ^^^ thank you!

**Comment by tsa321** [comment] 2024-07-03 23:00
@mallenexpensify @CortneyOfstad I can reproduce the issue mentioned [here](https://github.com/Expensify/App/issues/43726#issuecomment-2197289432), but I think it is a different issue. Should we open a new issue?

**Comment by mallenexpensify** [comment] 2024-07-03 23:59
@rojiphil , do you think @tsa321 's[ proposal above ](https://github.com/Expensify/App/issues/43726#issuecomment-2167055802)will fix the bug?

**Comment by rojiphil** [comment] 2024-07-04 11:38
> We introduce focusTrap in https://github.com/Expensify/App/pull/39520

> We can remove the new focusTrap and use react native web focusTrap in baseModal which is already there. So we only need to remove FocusTrapForModal

@tsa321 `FocusTrapForModal` was introduced intentionally in the mentioned PR. So, removal is not an option. 
And your alternative solution is not clear to me. Can you provide more details of the code changes if you think that would work? Or if you have any other ideas, please share.

**Comment by rojiphil** [comment] 2024-07-09 04:07
@suneox Thanks for your [proposal](https://github.com/Expensify/App/issues/43726#issuecomment-2216348401). 
Your alternative solution LGTM i.e setting `initialFocus` with the element that needs to be focused. 
This way we are also extending the feature to bring the initial focus to a custom element.
🎀👀🎀 C+ reviewed

**Comment by mvtglobally** [comment] 2024-07-11 03:45
Issue not reproducible during KI retests. (First week)

**Comment by mallenexpensify** [comment] 2024-07-12 01:34
@grgia 👀 on the proposal above plz

**Comment by mallenexpensify** [comment] 2024-07-12 17:59
@rojiphil @suneox , if possible, let's try to expedite this fix.  It's a smaller bug but it's affecting quite a few folks. Thx

**Comment by strepanier03** [comment] 2024-08-01 22:19
I'll check tomorrow for the checklist. I'm heading out soon.

**Comment by rojiphil** [comment] 2024-08-03 12:24
* [x]  [@rojiphil] The PR that introduced the bug has been identified. Link to the PR: [Offending PR](https://github.com/Expensify/App/pull/43743)
* [x]  [@rojiphil] The offending PR has been commented on, pointing out the bug it caused and why, so the author and reviewers can learn from the mistake. Link to comment: [Added comment](https://github.com/Expensify/App/pull/43743/files#r1702735326)
* [x]  [@rojiphil] A discussion in #expensify-bugs has been started about whether any other steps should be taken (e.g. updating the PR review checklist) in order to catch this type of bug sooner. Link to discussion: Not Required. Existing checklist is good enough to capture such issues.
* [x]  [@rojiphil] Determine if we should create a regression test for this bug. :  Since the changes in `focusTrapForModal` are generic and can impact other modals, it is better to have a regression test 
* [x]  [@rojiphil] If we decide to create a regression test for the bug, please propose the [regression test](https://github.com/Expensify/App/blob/main/contributingGuides/REGRESSION_TEST_BEST_PRACTICES.md) steps to ensure the same bug will not reach production again. 

Test
	1	Copy image to clipboard
	2	Open any report
	3	Paste image to the composer input by hotkey (Ctrl+V)
	4	Press 'Enter' key to send the message
	5	Verify that the image is sent

**Comment by rojiphil** [comment] 2024-08-03 12:27
@strepanier03 @CortneyOfstad 
Completed BZ checklist and accepted offer. 
Thanks and sorry for the delayed response.

**Comment by strepanier03** [comment] 2024-08-05 18:37
Both contracts are paid and closed in Upwork. Thank you all!

**Closed by strepanier03** 2024-08-05 18:37 UTC
Labels: External, Daily, Overdue, Awaiting Payment, Bug
