### ISSUE TITLE
[HOLD for payment 2024-01-24] [$500] Workspace - Invite message does not remain when refresh page

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#32835] opened 2023-12-11 17:14 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.11-1
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** Applause - Internal Team
**Slack conversation:**

## Action Performed:
1. Open staging.new.expensify.com
2. Navigate to Settings> Workspace> Members> Invite
3. Select few members to invite and click Next
4. Add random invite message and confirm Invite button
5. Refresh the page
6. Repeat steps 2 & 3

## Expected Result:
Once entered invite message should remain when invite more users when refresh the page

## Actual Result:
Invite message does not remain when refresh page

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [x] Android: mWeb Chrome
- [ ] iOS: Native
- [x] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

https://github.com/Expensify/App/assets/93399543/2e6f50be-510f-490e-94db-07bede77469a

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01e780374dd3bf487d</li>
        <li>Upwork Job ID: 1734260347582304256</li>
        <li>Last Price Increase: 2023-12-18</li>
<li>Automatic offers: </li>
<ul>
<li>DylanDylann | Contributor | 28064891</li>
</ul></li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @bfitzexpensify</details>

**Comment by AmjedNazzal** [comment] 2023-12-11 20:50
## Proposal

### Please re-state the problem that we are trying to solve in this issue.

Workspace - Invite message does not remain when refresh page

### What is the root cause of that problem?

The issue here is a simple case of react lifecycle no aligning with the intended behaviour, the `welcomeNote` is a state variable with a default value of either `this.props.workspaceInviteMessageDraft` or `this.getDefaultWelcomeNote()`, But `workspaceInviteMessageDraft` is populated from an asynchronous data fetch, therefore on the component mounting it will be empty and the code will default to the default welcome message.

https://github.com/Expensify/App/blob/bc7728735b31dcf645dda84e21a7aba149ae6108/src/pages/workspace/WorkspaceInviteMessagePage.js#L84-L86

### What changes do you think we should make in order to solve the problem?

We already have a `componentDidUpdate` being used to ensure state variables are populated correctly so we just have to add a simple check in there to ensure that the `welcomeNote` is included

```javascript
componentDidUpdate(prevProps) {
    ...
    if(prevProps.workspaceInviteMessageDraft !== this.props.workspaceInviteMessageDraft){
        this.setState({welcomeNote: this.props.workspaceInviteMessageDraft});
    }

```

### Result

https://github.com/Expensify/App/assets/74202751/3c4c08d0-22e2-4869-a290-20cd04ebb7ec

**Comment by DylanDylann** [comment] 2023-12-12 06:05
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
- Workspace - Invite message does not remain when refresh page

### What is the root cause of that problem?
- Refer to [react-native-onyx docs](https://github.com/Expensify/react-native-onyx):
> withOnyx() will delay the rendering of the wrapped component until all keys/entities have been fetched and passed to the component

- And, we know that whether all the keys/entities have been fetched or not based on the value, if  any key have value is ```undefined```, so its data is not fetched, if any key have value is ```nulll```, so its data is fetched successfully and have ```null``` value.
- In this bug, we have the selector:
https://github.com/Expensify/App/blob/4239252d5ace1039fa2aaf8d707f4e5de8523309/src/pages/workspace/WorkspaceInviteMessagePage.js#L264-L267
that always returns a value that is not ```undefined``` value. And as I mentioned above, it will consider that all the keys have been fetched successfully but the fact is that the workspaceInviteMessageDraft `s data is not fetched, and goes to render the wrapped component, in this case, is WorkspaceInviteMessage page.
- Then, it will set the message invite with the default message:
https://github.com/Expensify/App/blob/4239252d5ace1039fa2aaf8d707f4e5de8523309/src/pages/workspace/WorkspaceInviteMessagePage.js#L85
### What changes do you think we should make in order to solve the problem?
- Based on the above RCA, we can just update the selector to:
```
 selector: (draft) => {
                if (isUndefined(draft)) {
                    return draft;
                }
                return isEmpty(draft) ? '' : draft;
            },
```

### What alternative solutions did you explore? (Optional)
- NA

**Comment by rushatgabhane** [comment] 2023-12-18 13:13
reviewing

**Comment by rushatgabhane** [comment] 2023-12-18 22:11
C+ reviewed 🎀 👀 🎀 

I like @DylanDylann's proposal https://github.com/Expensify/App/issues/32835#issuecomment-1851357992

**Comment by DylanDylann** [comment] 2023-12-19 05:43
@rushatgabhane PR #33269 is ready to review

**Comment by DylanDylann** [comment] 2023-12-19 05:43
@bernhardoj I think the important in this issue is the RCA rather than the solution

**Comment by DylanDylann** [comment] 2023-12-19 06:03
I think the important point in this issue is that we need to find out the RCA (Why the current selector does not work correctly). Use or not use the selector is just a refactor.

**Comment by bernhardoj** [comment] 2024-01-10 14:22
So, will I get any compensation because my solution is used on the PR?

I'm still the same with my opinion above.

**Comment by rushatgabhane** [comment] 2024-01-17 05:04
1. The PR that introduced the bug has been identified. Link to the PR: https://github.com/Expensify/App/pull/31770

2. The offending PR has been commented on, pointing out the bug it caused and why, so the author and reviewers can learn from the mistake. Link to comment: https://github.com/Expensify/App/pull/31770/files#r1454592244

3. A discussion in #expensify-bugs has been started about whether any other steps should be taken (e.g. updating the PR review checklist) in order to catch this type of bug sooner. Link to discussion: N.A.

4. Determine if we should create a regression test for this bug. No

5. If we decide to create a [regression test](https://github.com/Expensify/App/blob/main/contributingGuides/REGRESSION_TEST_BEST_PRACTICES.md) for the bug, please propose the regression test steps to ensure the same bug will not reach production again - N.A.

**Comment by rushatgabhane** [comment] 2024-01-17 05:05
PR on prod 1 week ago. @bfitzexpensify could you please attach a payment summary.  Thank you 🙇

**Comment by DylanDylann** [comment] 2024-01-26 04:13
@bfitzexpensify Could you help to move forward this issue?

**Comment by JmillsExpensify** [comment] 2024-01-30 16:56
I'll step in on this one, as Ben is OOO. 

Payment summary:
 - Issue reporter: QA
 - Contributor: @DylanDylann $500 
 - Contributor+: @rushatgabhane $500

**Comment by JmillsExpensify** [comment] 2024-01-30 16:58
$500 payment approved for @rushatgabhane based on summary above.

**Comment by JmillsExpensify** [comment] 2024-01-30 16:58
Closing this issue, as no regression test is required.

**Closed by JmillsExpensify** 2024-01-30 16:58 UTC
Labels: External, Daily, Awaiting Payment, Bug
