### ISSUE TITLE
Task – When attempting to add an assignee to a task in the new group chat, an error occursError appears when add assignee to task in new group chat

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#39296] opened 2024-03-29 21:26 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** v1.4.58-1
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:** https://expensify.testrail.io/index.php?/tests/view/4466917
**Issue reported by:** Applause - Internal Team

## Action Performed:
Break down in numbered steps

## Expected Result:
Assigning a task to a user in the new group chat is successful without encountering any errors.

## Actual Result:
When attempting to add an assignee to a task in the new group chat, an error occurs

## Workaround:
n/a

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [x] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

https://github.com/Expensify/App/assets/93399543/c5542e07-f32c-431a-9232-254c44a64ee2

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by kbecciv** [comment] 2024-03-29 21:27
@kevinksullivan I haven't added the External label as I wasn't 100% sure about this issue. Please take a look and add the label if you agree it's a bug and can be handled by external contributors.

**Comment by kbecciv** [comment] 2024-03-29 21:28
We think that this bug might be related to #vip-vsb

**Comment by abzokhattab** [comment] 2024-03-30 01:02
Not reproducible on main.

**Comment by kevinksullivan** [comment] 2024-04-05 23:18
couldn't reproduce on staging either so I'm closing.

**Closed by kevinksullivan** 2024-04-05 23:18 UTC
Labels: Daily, Overdue, Bug
