### ISSUE TITLE
[$250] MEDIUM: Allow arbitrary users to be added/removed to/from workspace chat via @mention or members list

### ISSUE THREAD

**Issue by waterim** [Expensify/App#35391] opened 2024-01-30 12:15 UTC
## Problem:
Right now there are no possibilities to add anyone to the automatically created workspace chats, but it should be possible to add by "mention"; it's similarly not possible to remove someone who has been thus added.

## Solution:
As discussed [here](https://github.com/Expensify/App/issues/33575#issuecomment-1915456021), we would like to add this possibility to:
1. Allow anyone to be added to the workspace chat via @mention
2. Allow anyone to be added to the workspace chat via the `Invite` button of the members page
3. Allow anybody who *wasn't* auto-added (ie, admins or the employee) to be removed via the members page

**IMPORTANT details for workspace chats:**
* To understand more regarding automatically added users read this https://github.com/Expensify/App/issues/33575#issuecomment-1911270326
* What we want to achieve: https://github.com/Expensify/App/issues/33575#issuecomment-1915471286
<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~013623b6c6ce0881ae</li>
        <li>Upwork Job ID: 1753488042510364672</li>
        <li>Last Price Increase: 2024-06-28</li>
<li>Automatic offers: </li>
<ul>
<li>brunovjk | Contributor | 0</li>
</ul></li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @johncschuster</details>

**Comment by quinthar** [comment] 2024-02-01 03:15
optimistically assigning to @waterim

**Comment by waterim** [comment] 2024-02-02 16:58
@quinthar Yes, I can take this one
Im still OOO(sick leave) today and can work in this one from Monday.

**Comment by jasperhuangg** [comment] 2024-02-02 18:27
This has to be fixed internally, I can take this

**Comment by jasperhuangg** [comment] 2024-02-02 18:42
Won't need C+ reviews for these PRs, at least for now

**Comment by quinthar** [comment] 2024-02-08 07:01
What's the next step here?  Who is doing it and when?

**Comment by jasperhuangg** [comment] 2024-02-14 04:31
@quinthar sorry, been bogged down with Wave work. The next step is to update the Auth checks that dictate who can be invited to a workspace chat. We can then update the front-end to handle the changes involving allowing only the people who weren't automatically added to be removed.

One of my wave issues was deprioritized, so I can get cracking with this tomorrow!

**Comment by jasperhuangg** [comment] 2024-02-14 23:07
First thing I noticed is that policy expense chats don't give the user/approvers "read, write, share" permissions by default, so I'm going to open a PR to fix that since those permissions are needed in order to invite to the report.

**Comment by jasperhuangg** [comment] 2024-02-21 01:34
Just a quick update on this, I have a PR up and I'm figuring out some MergeAccount tests that it broke.

**Comment by jasperhuangg** [comment] 2024-02-21 18:11
Gonna continue pushing this PR forward today.

**Comment by jasperhuangg** [comment] 2024-03-15 19:30
Review on the Auth PR is moving along, should be able to open this up to contributors for the front-end soon.

**Comment by jasperhuangg** [comment] 2024-03-15 19:35
Gonna bump this to Daily

**Comment by jasperhuangg** [comment] 2024-03-22 17:22
The Auth PR was recently deployed to prod! https://github.com/Expensify/Auth/pull/9955

It looks like we can open this up to external contributors to work on the front-end.

**Comment by johncschuster** [comment] 2024-04-01 22:06
This was just opened up to FE contributors last week. I'm going to keep this at `Daily` and start bumping Slack channels this week to get some proposals.

**Comment by johncschuster** [comment] 2024-04-05 19:12
[Raised in Slack](https://expensify.slack.com/archives/C01GTK53T8Q/p1712344310351229)

**Comment by brunovjk** [comment] 2024-04-05 22:49
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
The current issue revolves around the inability to add or remove users from automatically created workspace chats via @mention or the Invite button. Additionally, there's a challenge in allowing users who weren't auto-added to be removed from the workspace chat via the members page.

### What is the root cause of that problem?
The root cause lies in the lack of functionality to add or remove users through @mention or the Invite button, as well as the limitation in managing users who weren't auto-added to the workspace chat.

### What changes do you think we should make in order to solve the problem?
To address this issue, I propose implementing the following changes:

1. Enable the addition of users to the workspace chat via @mention.
2. Allow users to be added to the workspace chat via the Invite button on the members page.
3. Provide the capability for admins or employees who weren't auto-added to be removed from the workspace chat via the members page.

### What alternative solutions did you explore? (Optional)

**Comment by brunovjk** [comment] 2024-04-05 23:03
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
The current issue revolves around the inability to add or remove users from automatically created workspace chats via @mention or the Invite button. Additionally, there's a challenge in allowing users who weren't auto-added to be removed from the workspace chat via the members page.

### What is the root cause of that problem?
The root cause lies in the lack of functionality to add or remove users through @mention or the Invite button, as well as the limitation in managing users who weren't auto-added to the workspace chat.

### What changes do you think we should make in order to solve the problem?
To address this issue, we propose implementing the following changes:

1. Enable the addition of users to the workspace chat via @mention.
2. Allow users to be added to the workspace chat via the Invite button on the members page.
3. Provide the capability for admins or employees who weren't auto-added to be removed from the workspace chat via the members page.

### What alternative solutions did you explore? (Optional)

**Comment by mananjadhav** [comment] 2024-04-06 14:20
@brunovjk Your proposal doesn't cover any technical details on how are you planning to solve this.


Still open for proposals.

**Comment by brunovjk** [comment] 2024-04-06 14:52
@mananjadhav Thank you for the review.

> Your proposal doesn't cover any technical details

Im sorry, I will remake it

**Comment by brunovjk** [comment] 2024-04-08 14:57
## Proposal
[Updated](https://github.com/Expensify/App/issues/35391#issuecomment-2040742869)

Incorporated backend and frontend details to address technical implementation

**Comment by jasperhuangg** [comment] 2024-04-09 17:22
@mananjadhav can you review the updated proposal?

**Comment by jasperhuangg** [comment] 2024-04-10 00:21
@brunovjk 

> Enable the addition of users to the workspace chat via @mention:
I believe we need to change the backend to send an "Invitation Message" when we mention users in the workspace's default chats.

The back-end has already been updated to do support mention invites in workspace chats, fyi

**Comment by jasperhuangg** [comment] 2024-04-10 00:23
@brunovjk I think I prefer your alternative solution, the RoomMembersPage is intended to be used to manage the members for all types of reports, can you update your proposal to elaborate the specific changes you'd make for your alternative solution to work?

**Comment by brunovjk** [comment] 2024-04-10 11:04
Thank you very much for the review, I will be working on these suggestions immediately.

**Comment by mananjadhav** [comment] 2024-04-10 17:23
> The back-end has already been updated to support mention invites in workspace chats, fyi

Just got it. Thanks for clarifying. I agree using the `RoomMembersPage`.

**Comment by brunovjk** [comment] 2024-04-11 21:32
> The back-end has already been updated to support mention invites in workspace chats, fyi

Mention invites in workspace chats is indeed working, but I haven't managed to get default chats, `#announce` and `#admins` , yet.

**Comment by jasperhuangg** [comment] 2024-04-12 17:36
> Mention invites in workspace chats is indeed working, but I haven't managed to get default chats, #announce and #admins , yet.

That's expected. You aren't supposed to be able to invite people to default rooms. This issue only pertains to workspace chats.

**Comment by jasperhuangg** [comment] 2024-04-12 17:37
@brunovjk ^

**Comment by brunovjk** [comment] 2024-04-12 17:50
Ok. I understand now. Thank you. I will update my proposal.

**Comment by brunovjk** [comment] 2024-04-12 18:44
## Proposal
[Updated](https://github.com/Expensify/App/issues/35391#issuecomment-2040742869)

Using the `RoomMembersPage` instead of `ReportParticipantsPage` when we access "Members" on the "Detail Page" in a "Workspace chat"

**Comment by brunovjk** [comment] 2024-04-12 18:46
Thank you for the review @jasperhuangg, can you please check again?

**Comment by brunovjk** [comment] 2024-04-12 21:46
Thanks. Estimated ETA to raise PR by 4/17

**Comment by brunovjk** [comment] 2024-04-12 21:46
Thank you. Estimated ETA to raise PR by 4/17

**Comment by brunovjk** [comment] 2024-04-14 22:22
While testing our PR, I came across 2 bugs:
1. Inconsistency in the **number of members** displayed on the "Details" page compared to the "Member List."
2. Ability to add an unknown user (without personal details) and immediately "delete" them.


Both issues were replicated in "public room": https://github.com/Expensify/App/issues/37192 and https://github.com/Expensify/App/issues/36378
Those  [_"issue needs to be addressed on the backend"_](https://github.com/Expensify/App/issues/36378#issuecomment-1965357368). Does this apply here too? Thank you.

**Comment by brunovjk** [comment] 2024-04-14 22:29
We just don't do anything in `RoomMembersPage` when dealing with user (`accountID`) without `personalDetails`
https://github.com/Expensify/App/blob/db9e01cc302df7f2b3dd53a99c1082404676aedb/src/pages/RoomMembersPage.tsx#L173-L175

I believe that the ideal would be to fix it via the backend, but we can update this logic in teh FE to deal with users without `personalDetails` anyway.

**Comment by mananjadhav** [comment] 2024-04-15 17:08
I am not sure if this needs to be fixed from BE. @jasperhuangg Can you comment?

**Comment by jasperhuangg** [comment] 2024-04-24 18:07
I think this should have been fixed in https://github.com/Expensify/Web-Expensify/pull/41771

**Comment by brunovjk** [comment] 2024-04-25 12:16
Nice @jasperhuangg!! 
There are 3 similar issues that I believe were resolved by your PR:
1. #40459
2. #40301
3. #37970

However, the problem persists when we **add an unknown user to a workspace chat** (our task in this same issue):
<details>
<summary>add an unknown user to a workspace chat</summary>



https://github.com/Expensify/App/assets/95647348/a3c2b86c-5618-4c05-a9f9-9b2f541df0f7


</details>

Maybe I'm missing something here, I have to go now, when I return I'll test more. Thanks.

**Comment by brunovjk** [comment] 2024-04-29 12:38
Nice @ jasperhuangg!! 
There are 3 similar issues that I believe were resolved by your PR:
1. #40459
2. #40301
3. #37970

However, the problem persists when we add unknown users to a `public-room` or `workspace-chat-room` via `Invite button` (The latter you can only test using our [PR](https://github.com/Expensify/App/pull/40220))

I'll wait a few more days and test again. **Last test: 04/29**

**Comment by brunovjk** [comment] 2024-05-02 13:36
@jasperhuangg, do you think we should merge our [PR](https://github.com/Expensify/App/pull/40220) at once? This way I believe it is easier to test/solve the problem of adding 'unknown users' after.

**Comment by brunovjk** [comment] 2024-05-06 21:19
@jasperhuangg The issue when adding unknown user via "Invite Button" in workspace chat is **no longer reproducible**. It seems to me that the changes you made on the server side took effect.
However, before we were able to add by `@mention` successfully, today I was unable to do so. Do you know something about it? This issue is also reproducible in other chats. The rest **our [PR](https://github.com/Expensify/App/pull/41699) looks good and ready for review**.
Thank's for your time.

cc: @mananjadhav

**Comment by jasperhuangg** [comment] 2024-05-06 21:47
@brunovjk there have been site outages today so I imagine those were probably the reason for your testing difficulties.

**Comment by jasperhuangg** [comment] 2024-05-06 21:48
Nothing has changed about that functionality so I think you can move ahead with the review of the PR @mananjadhav

**Comment by jasperhuangg** [comment] 2024-05-30 19:26
@brunovjk I'm seeing that you're able to select policy admins + guides that were added to the workspace chats by default in the UI, which shouldn't be allowed. Can you submit another PR that prevents them from being removed from workspace chats?

Basically, when a workspace chat is first created, there are people who are in the report by default. Those people should not be removable.

**Comment by brunovjk** [comment] 2024-05-30 19:50
@jasperhuangg sure :D I will work on it and raise the PR ASAP. Thank you for the catch :)

**Comment by johncschuster** [comment] 2024-05-31 14:28
Sweet! I'll get payment issued next Thursday.

@mananjadhav can you propose regression steps when you get a chance? Thanks!

**Comment by brunovjk** [comment] 2024-06-03 11:36
Update: I continue creating "PR" to align the behavior of who can invite and be removed to workspace chats, following:
https://github.com/Expensify/App?tab=readme-ov-file#workspace-chats

**Comment by brunovjk** [comment] 2024-06-03 11:43
**Update:** I continue working on PR to align the behavior of who can invite and be removed to workspace chats, following:
https://github.com/Expensify/App?tab=readme-ov-file#workspace-chats

**Comment by brunovjk** [comment] 2024-06-03 14:02
@johncschuster Working on this same issue. We need to ensure an important detail:
> 3. Allow anyone who wasn't auto-added (ie, admins or the employee) to be removed via the members page

I'm raising another PR. I believe we should wait for payment here.

**Comment by brunovjk** [comment] 2024-06-04 14:45
Of course, almost everything is ready, I just need to record the test video on some remaining platforms.

**Comment by brunovjk** [comment] 2024-06-07 09:37
**Update**: Keep working on the PR

**Comment by brunovjk** [comment] 2024-06-10 10:53
**Update**: [PR](https://github.com/Expensify/App/pull/43065) being reviewed

**Comment by johncschuster** [comment] 2024-06-18 14:48
Acknowledged! I'll issue payment on the 24th!

**Comment by brunovjk** [comment] 2024-06-24 12:05
> Acknowledged! I'll issue payment on the 24th!

@johncschuster Could we get an increase in the bounty here? Mainly to cover regression.  Excessive testing and adjustments was done during and after the PR was merged. Thank you 🙏

**Comment by brunovjk** [comment] 2024-06-24 12:08
> Acknowledged! I'll issue payment on the 24th!

@johncschuster Could we get an increase in the bounty here? Mainly to cover regression. Extensive testing and adjustments were necessary during and after the PR was merged. Thank you 🙏

cc: @jasperhuangg

**Comment by johncschuster** [comment] 2024-06-24 16:16
@brunovjk Let me check in with the team about your request. I'll follow up in a bit!

**Comment by brunovjk** [comment] 2024-06-24 16:35
Thank you :D

**Comment by johncschuster** [comment] 2024-06-25 15:24
@brunovjk, I chatted with the team, and it seems like a regression was introduced here, which would result in a payment reduction, not an increase. Can you tell me a bit more about why you feel there should be an increase here?

**Comment by brunovjk** [comment] 2024-06-26 20:52
Thank you @johncschuster. Here's an explanation:

The initial task here was **Allow arbitrary users to be added/removed to/from workspace chat via @mention or members list** [PR](https://github.com/Expensify/App/pull/42320), then we had to update **"who can" select/add/remove and which users can be selected/removed on workspace chats** [PR](https://github.com/Expensify/App/pull/43065). That's why I asked for an increase in the reward, since this second PR involved a lot of testing and two regressions, https://github.com/Expensify/App/issues/43828 and https://github.com/Expensify/App/issues/42928 .
My idea was for the bounty to be $1000, minus the two regressions totalizing $250. But, I am in favor of any of your decisions.

@jasperhuangg do we need to wait for https://github.com/Expensify/App/issues/42928 to proceed with payment here?

Thank you :D

**Comment by brunovjk** [comment] 2024-06-26 20:53
Thank you @johncschuster. Here's an explanation:

The initial task here was **Allow arbitrary users to be added/removed to/from workspace chat via @mention or members list** [PR](https://github.com/Expensify/App/pull/42320), then we had to update **"who can" select/add/remove and which users can be selected/removed on workspace chats** [PR](https://github.com/Expensify/App/pull/43065). That's why I asked for an increase in the reward, since this second PR involved a lot of testing and two regressions, https://github.com/Expensify/App/issues/43828 and https://github.com/Expensify/App/issues/42928 .
My idea was for the bounty to be $1000, minus the two regressions totalizing $250. But, I am in favor of any of your decisions.

@jasperhuangg do we need to wait for https://github.com/Expensify/App/issues/42928 to proceed with payment here?

**Comment by johncschuster** [comment] 2024-06-28 14:48
# Payment Summary:
Contributor: @brunovjk - ~$1000~ $250 (reduced for 2x regresssions) - paid [via Upwork](https://www.upwork.com/nx/wm/offer/0)
Contributor+: @mananjadhav  - ~$1000~ $250 (reduced for 2x regresssions) - requires payment through NewDot Manual Requests

**Comment by johncschuster** [comment] 2024-06-28 14:52
@mananjadhav, can you propose a regression test checklist?

**Comment by mananjadhav** [comment] 2024-06-28 15:42
@johncschuster I think the test steps from the PR [here](https://github.com/Expensify/App/pull/43065#issue-2334256204). I  are good for the checklist. Can we please use that?



### Pre-condition:

**1.** We need 4 accounts for this test:

- Workspace Creator
- Workspace Admin
- Workspace Member
- No-workspace member (invited)

**2.** Login in the app as _"Workspace Creator"_ **3.** Create a workspace **4.** Go to the automatically created _"Workspace Chat"_ **5.** Go to the _"Report Details"_ **6.** Go to _"Members"_ page Click _"Invite"_ **7.** Invite all the other 3 accounts (`admin`, `member`, and `invited`) to the _"Workspace Chat"_ **8.** Still on the _"Members"_ page, change the `admin` role to `Administrator` **8.** Click on the _"Global Fab"_ _"Start Chat"_ Select _"#Room"_ tab **9.** Create a _"workspace-room"_ **10.** Invite all the other 3 accounts (`admin`, `member`, and `invited`) to the _"workspace-room"_

### Tests:

**1. Logged as the "Workspace Creator"**:

**i.** Go to the "Workspace Chat" Report Details page **ii.** Verify that the "Leave" button doesn't show, as you are a "workspace admin". **iii.** Go to "Members" page **iv.** Verify that you cannot select/remove admin and default added members **v.** Verify that you can "Invite" and "Remove" (admin cannot be removed) members **vi.** Go to the "workspace-room" Report Details page **vii**. Go to "Members" page **viii.** Verify that you can "Invite" and "Remove" (you cannot remove yourself here) members

**2. Logged as the "Workspace Admin"**:

**i.** Go to the "Workspace Chat" Report Details page **ii.** Verify that the "Leave" button doesn't show, as you are a "workspace admin". **iii.** Go to "Members" page **iv.** Verify that you cannot select/remove admin and default added members **v.** Verify that you can "Invite" and "Remove" (admin cannot be removed) members **vi.** Go to the "workspace-room" Report Details page **vii.** Go to "Members" page **viii.** Verify that you can "Invite" and "Remove" (you cannot remove yourself here) members

**3. Logged as the "Workspace Member"**:

**i.** Go to the "Workspace Chat" Report Details page **ii.** Verify that the "Invite" button does not show. **iii.** Go to "Members" page **iv.** Verify that you cannot "Invite" and "Remove" members. **vii.** Logged as the "Workspace Member" Go to the "workspace-room" Report Details page **viii.** Verify that the "Invite" button does not show. **x.** Go to "Members" page **xi.** Verify that you can "Invite" and "Remove" (you cannot remove yourself here) members.

**4. Logged as the "Workspace Chat Invited**":

**i.** Go to the "Workspace Chat" Report Details page **ii.** Verify that the "Invite" button does not show. **iii.** Go to "Members" page **iv.** Verify that you cannot "Invite" and "Remove" members. **vii.** Logged as the "Workspace Room Invited" Go to the "workspace-room" Report Details page **viii.** Verify that the "Invite" button does show and you can invite members to the chat.

**Comment by JmillsExpensify** [comment] 2024-06-28 17:07
$250 approved for @mananjadhav

**Closed** 2024-06-28 21:27 UTC
Labels: External, Weekly, NewFeature, Awaiting Payment
