### ISSUE TITLE
[$500] Upon returning from the Referral Section, a black page appears and modals are floating

### ISSUE THREAD

**Issue by m-natarajan** [Expensify/App#35969] opened 2024-02-06 21:44 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.37-1
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** Applause internal team
**Slack conversation:**

## Action Performed:
1, Profile
2, Share code
3, Click on "Get $250," then the referral section opens. Click on the back icon from the referral section.
## Expected Result:
When we navigate back from the referral section, it should redirect back to the share code section.

## Actual Result:
Upon returning from the referral section, a black page appears and modals are floating.

## Workaround:
unknown
## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

https://github.com/Expensify/App/assets/38435837/8a832d1b-d94a-4aa5-b032-b523ea8df335

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~0151c67071986a4446</li>
        <li>Upwork Job ID: 1754984369541861376</li>
        <li>Last Price Increase: 2024-02-06</li>
    </ul>
</details>

**Comment by trjExpensify** [comment] 2024-02-07 17:03
@adamgrzybowski is going to sense check whether his solution on the main issue addressing `goBack` bugs will fix this. Let's hold on making a PR until then!

**Comment by adamgrzybowski** [comment] 2024-02-07 17:49
@trjExpensify Should be fixed by https://github.com/Expensify/App/pull/36050

**Comment by hayata-suenaga** [comment] 2024-02-07 18:06
The issue is tracked in [this GH issue](https://github.com/Expensify/App/issues/35626). Closing this in favor of that one 🙇

**Closed by hayata-suenaga** 2024-02-07 18:06 UTC
Labels: External, Daily, Help Wanted, Bug
