### ISSUE TITLE
Android - Payments - Debit card option Is missing under the Add payment method

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#10094] opened 2022-07-25 23:32 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Launch the app
2. Log in with expensifail accounr
3. Go to Setting - Payments
4. Tap on Add Payment method 

## Expected Result:
Debit Card option is visible under Payments

## Actual Result:
Debit Card option is missing under Payments

## Workaround:
Unknown

## Platform:

Where is this issue occurring?

- Android

**Version Number:** 1.1.86.0

**Reproducible in staging?:** Yes

**Reproducible in production?:** No

**Email or phone of affected tester (no customers):** any expensifail account

**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Notes/Photos/Videos:** Any additional supporting documentation

https://user-images.githubusercontent.com/93399543/180892026-cc07d5a8-0b3e-4688-9ce0-24a47036f0c5.mp4

**Expensify/Expensify Issue URL:** 

**Issue reported by:** Applause - Internal Team

**Slack conversation:** 

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by marcaaron** [comment] 2022-07-26 00:14
Just to confirm, this is only occurring on Android? And it is 100% reproducible or intermittent? 

Seems this option would be hidden if the betas are not yet loaded. 

Does the option appear eventually?

**Comment by marcaaron** [comment] 2022-07-26 00:16
Seems potentially related to this -> https://github.com/Expensify/Expensify/issues/213881

https://github.com/Expensify/App/pull/9768

cc @yuwenmemon @luacmartins

**Comment by luacmartins** [comment] 2022-07-26 01:52
It could be related to removing the beta, but I couldn't repro on the simulator. @marcaaron did you manage to reproduce this?

**Comment by marcaaron** [comment] 2022-07-26 17:11
Testing on a hardware device. App feels pretty unstable...

- white screen for several seconds when logging in
- unable to tap the settings icon for many seconds later
- generally very slow

But I am able to access the Debit Card option fine.

**Comment by luacmartins** [comment] 2022-07-26 17:28
@kbecciv could you test this again? We are having issues reproducing this on our end.

**Comment by mvtglobally** [comment] 2022-07-26 18:29
@luacmartins We are checking

**Comment by mvtglobally** [comment] 2022-07-27 00:58
Issue is repro

https://user-images.githubusercontent.com/43995119/181137616-934e37fc-5e68-4d5f-a7ae-587a8f432a70.mp4

**Comment by luacmartins** [comment] 2022-07-27 20:19
The only way I could reproduce this issue was delaying the response of `OpenApp` with a setTimeout, but the option eventually shows up when the call completes. @kbecciv can you confirm if the issue still happens with the steps below?

1. Log out
2. Sing back in
3. Wait 15-20s
4. Navigate to `Settings > Payments > Add payment method`
5. Verify that debit card is an option

**Comment by mvtglobally** [comment] 2022-07-28 02:25
checking with the team

**Comment by luacmartins** [comment] 2022-07-29 00:14
Removing the blocker label since we couldn't reproduce and this would only affect a beta feature. @mvtglobally Can we add this to the KI tests?

**Comment by luacmartins** [comment] 2022-08-19 15:54
@kbecciv  is this issue still reproducible?

**Comment by kbecciv** [comment] 2022-08-19 17:45
@luacmartins Chcking, update you shortly

**Comment by kbecciv** [comment] 2022-08-19 17:47
Unable to reproduce it with build v1.1.88-14
![Screenshot_20220819-134625_New Expensify](https://user-images.githubusercontent.com/93399543/185677559-4d302a48-4917-4396-8951-22997b66720c.jpg)

**Comment by luacmartins** [comment] 2022-08-19 18:43
Thanks for confirming! I think this was fixed [here](https://github.com/Expensify/Web-Expensify/pull/34497). Not really sure how though.

Closing this issue. Please reopen if you see this happening again.

**Closed by luacmartins** 2022-08-19 18:43 UTC
Labels: Engineering, Weekly
