### ISSUE TITLE
[HOLD for payment 2022-11-02] [$250] Web - Workspace - Invited user is displayed without a username and an avatar image

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#11815] opened 2022-10-13 18:09 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Go to URL https://staging.new.expensify.com/
2. Login with any account
3. Go to Settings->Workspace->Manage members
4. Kill internet connection
5. Invite a new member (you should not have had any communication with him before)
6. Turn on internet connection

## Expected Result:
The invited user should be displayed with a username and avatar image without refreshing the page

## Actual Result:
Invited user displayed without a username and avatar image

## Workaround:
Unknown

Where is this issue occurring?

- Web
- iOS
- Android
- Desktop App
- Mobile Web

**Version Number:** 1.2.14.0

**Reproducible in staging?:** Yes

**Reproducible in production?:** Yes

**Email or phone of affected tester (no customers):** any

**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Notes/Photos/Videos:** Any additional supporting documentation

https://user-images.githubusercontent.com/93399543/195673478-bcf6a373-2955-4683-84ed-e2f033cc3ae5.mp4

**Expensify/Expensify Issue URL:** 

**Issue reported by:** Applause - Internal Team

**Slack conversation:** 

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by mountiny** [comment] 2022-10-13 18:37
I dont think this is necessarily a bug, if you are offline you cannot get the username of a user you havent chatted with before. We could use default avatar. cc @neil-marcellini for your thoughts as you worked in this area i believe

**Comment by neil-marcellini** [comment] 2022-10-13 22:01
I think it's a bug, but the expected result should be clarified. Yes we should show a default avatar and the email, just like it shows in the options selector and LHN.

cc @chiragsalian since he worked on `AddMembersToWorkspace`.

**Comment by mountiny** [comment] 2022-10-13 22:03
I agree with the avatar, the email is already shown correctly.

Just not sure if there is already some fix in motion, so thanks for tagging Chirag 🙇

**Comment by chiragsalian** [comment] 2022-10-14 21:06
Ah yup part of it looks like a bug,
Not a bug - we definitely cannot get username information and their actual avatar when offline.
A bug - we should be showing default avatar when we don't have actual avatar information. This should be addressed in this issue.

My plate is a bit full so I'm not taking this on but it should be straightforward to test and fix locally.

**Comment by mountiny** [comment] 2022-10-14 22:30
I think this can be external, right? The optimistic action is handled in App where also the default avatar should be added

**Comment by chiragsalian** [comment] 2022-10-14 22:31
Yes it can definitely be external 🙂

**Comment by mollfpr** [comment] 2022-10-16 03:29
### Proposal
When offline after inviting members to the workspace, the `personalDetails` data from Onyx is not updated.
https://github.com/Expensify/App/blob/62394cca18424fafe09c046fa63199d98696cc49/src/pages/workspace/WorkspaceMembersPage.js#L293

We get the member info from the `personalDetails`, so in this case, because we can't find the email just invited in `personalDetail` we add a default value to `displayName` and `login` but not with the avatar.

**Solution**
Rather than checking network status, we can add a default avatar together with `displayName` and `login`.
```diff
diff --git a/src/pages/workspace/WorkspaceMembersPage.js b/src/pages/workspace/WorkspaceMembersPage.js
index 5e00fdce8..22e641f03 100644
--- a/src/pages/workspace/WorkspaceMembersPage.js
+++ b/src/pages/workspace/WorkspaceMembersPage.js
@@ -15,6 +15,7 @@ import ScreenWrapper from '../../components/ScreenWrapper';
 import withLocalize, {withLocalizePropTypes} from '../../components/withLocalize';
 import compose from '../../libs/compose';
 import * as Policy from '../../libs/actions/Policy';
+import * as ReportUtils from '../../libs/ReportUtils';
 import Button from '../../components/Button';
 import Checkbox from '../../components/Checkbox';
 import Text from '../../components/Text';
@@ -290,7 +291,7 @@ class WorkspaceMembersPage extends React.Component {
             if (email !== this.props.session.email && email !== this.props.policy.owner) {
                 removableMembers.push(email);
             }
-            const details = this.props.personalDetails[email] || {displayName: email, login: email};
+            const details = this.props.personalDetails[email] || {displayName: email, login: email, avatar: ReportUtils.getDefaultAvatar(email)};
             data.push({
                 ...policyMember,
                 ...details,
```

**Result**

https://user-images.githubusercontent.com/25520267/196016581-e1b5ef98-ed03-475f-9c89-9997a977cb21.mov

**Comment by mananjadhav** [comment] 2022-10-16 10:12
Thanks a lot for the proposals @Uros787 and @mollfpr, but I had issues to get both of them working fine.

@Uros787 In your video it seems to be working fine, but when I applied it, it only loads the profile picture after I reconnect to the internet. If I am offline, it showed empty avatar to me. Can you verify if you've added all the details for the change?

@mollfpr Your proposal loaded the display avatar in all cases, but the moment I switch from offline to online, it changed the avatar color. Did you come across this issue at your end?

**Comment by mollfpr** [comment] 2022-10-16 14:03
@mananjadhav It's because the avatar that we get from the server and what we set in the App with `getDefaultAvatar` has a different value.

<img width="988" alt="Screen Shot 2022-10-16 at 20 57 27" src="https://user-images.githubusercontent.com/25520267/196039637-2fb45576-f85a-41d0-9ab9-70f44e6979a2.png">


In this example, the avatar that we get from `getDefaultAvatar` is https://d2k5nsl2zxldvw.cloudfront.net/images/avatars/avatar_8.png while from the server is https://d2k5nsl2zxldvw.cloudfront.net/images/avatars/avatar_1.png

**Comment by mananjadhav** [comment] 2022-10-18 18:36
I haven't been able to get both the proposals working.  @mollfpr proposal works for me but I feel switching the avatar colors from offline to online is not a good experience.

I am wondering if while the user is added offline, we should show a greyed avatar only and then when it switches online, it could load from internet (user's actual dp or fallback to one of the colored avatars)

**Comment by mountiny** [comment] 2022-10-18 20:07
@shawnborton Would you be able to help us decide on the look of the default avatar here? If user is invited to a policy offline, we currently dont show any avatar, which is a bug. I think we should be good y showing a grew default avatar in this case as that align with the offline optimistic nature. 

Would you be bale to confirm this? Dont wanna make some assumption here which we would have to change later. Thank you!

**Comment by shawnborton** [comment] 2022-10-18 20:22
I'm cool with using a gray avatar when the user is offline. I think we already have that asset in the repo as well.

**Comment by mountiny** [comment] 2022-10-18 20:38
Thanks

**Comment by mananjadhav** [comment] 2022-10-19 02:46
@Uros787 Your last proposal is similar to @mollfpr 's proposal.

Anyway I prefer to set the default value when we set the object.  I am fine with @mollfpr's proposal [here](https://github.com/Expensify/App/issues/11815#issuecomment-1279882632) with the value to set `greyed` avatar.

**Comment by mountiny** [comment] 2022-10-19 15:31
@mollfpr Feel free to raise the PR

Thanks @mananjadhav for the review.

**Comment by mollfpr** [comment] 2022-10-21 00:15
@mananjadhav @mountiny PR is ready 🚀

**Comment by mollfpr** [comment] 2022-11-02 17:40
Bump @mountiny for the Upwork link

**Comment by mountiny** [comment] 2022-11-02 18:05
@mateocole can you please help with the payment for @mollfpr ? Thank you 🙇

**Comment by mvtglobally** [comment] 2022-11-03 03:12
Issue not reproducible during KI retests. (First week)

**Comment by mollfpr** [comment] 2022-11-05 01:48
Bump @mateocole

**Comment by mananjadhav** [comment] 2022-11-05 18:56
@mountiny @mateocole Can you expedite please? It is 4 days overdue the payment date.

**Comment by mountiny** [comment] 2022-11-07 14:27
Asking for someone to step in here, sorry for the delay

**Comment by dylanexpensify** [comment] 2022-11-07 15:02
Hello! I'll get going on this NOW

**Comment by dylanexpensify** [comment] 2022-11-07 15:05
Upwork: https://www.upwork.com/jobs/~012e8c7dcb621a9da7

cc @mananjadhav @mollfpr

**Comment by mollfpr** [comment] 2022-11-07 15:11
@dylanexpensify Applied, thank you!

**Comment by dylanexpensify** [comment] 2022-11-07 15:12
Offer sent @mollfpr !

**Comment by mananjadhav** [comment] 2022-11-07 15:15
Done @dylanexpensify

**Comment by dylanexpensify** [comment] 2022-11-07 15:28
Offer sent @mananjadhav !

**Comment by mananjadhav** [comment] 2022-11-07 15:29
done. @dylanexpensify

**Comment by dylanexpensify** [comment] 2022-11-07 15:39
Payments sent, contracts ended, job posting closed! Thanks everyone!

**Closed by dylanexpensify** 2022-11-07 15:39 UTC
Labels: Reviewing, External, Engineering, Daily, Design, Awaiting Payment, Bug
