### ISSUE TITLE
Android - Room - Hard to focus the name input field after the error message appears

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#32402] opened 2023-12-02 15:22 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** v1.4.7-0
**Reproducible in staging?:** y
**Reproducible in production?:** n
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** Applause - Internal Team
**Slack conversation:**

## Action Performed:
1. Open the App
2. Log in with any Expensifail account
3. Press + button > Press Start chat > Switch to # Room
4. Enter incorrect data for receiving an error
5. Focus on another input field
6. Try to focus again on the name input field

## Expected Result:
No any problems with focusing the name input field after the error message appears

## Actual Result:
Hard to focus the name input field after the error message appears

## Workaround:
Unknown 

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [ ] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

https://github.com/Expensify/App/assets/93399543/4957d726-3e16-477a-af32-e24bff93cf19

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by kbecciv** [comment] 2023-12-02 15:23
Not reproduced on production

https://github.com/Expensify/App/assets/93399543/d6b34cc6-0625-422e-9ce4-0de32c51a0d3

**Comment by luacmartins** [comment] 2023-12-04 17:58
Potentially caused by https://github.com/Expensify/App/pull/30996

**Comment by luacmartins** [comment] 2023-12-04 18:02
Gonna see if the revert fixes this issue

**Comment by luacmartins** [comment] 2023-12-04 21:50
Fixed on this revert https://github.com/Expensify/App/pull/32440

**Closed** 2023-12-04 21:50 UTC
Labels: Engineering, Hourly

**Comment by dangrous** [comment] 2023-12-05 02:17
Thank you for handling! We should figure out why I was assigned an hourly on a weekend though - or was it just that everyone was off so it picked randomly?

**Comment by kowczarz** [comment] 2023-12-05 08:55
I've tried to reproduce this issue on here https://github.com/Expensify/App/pull/32432 (the https://github.com/Expensify/App/pull/32440 is reverted, so the bug should occur) and I couldn't do it


https://github.com/Expensify/App/assets/91068263/d0ca497f-7d24-4481-a604-0d1581d36a56

**Comment by luacmartins** [comment] 2023-12-05 16:22
hmm that issue was resolved when I reverted https://github.com/Expensify/App/pull/30996. Not sure why it's not reproducible. In that case, I'd just add a test step covering the issue so we make sure to test it and that's indeed fixed.

**Comment by kowczarz** [comment] 2023-12-07 10:53
I know, but I tested it on a branch where I reverted that revert. I just added this flow to test scenarios in https://github.com/Expensify/App/pull/32432

**Comment by luacmartins** [comment] 2023-12-07 16:04
Sounds good! Thanks for adding that!
