### ISSUE TITLE
[$500] Web - Room - Welcome message when create room can not enter multiple line

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#28935] opened 2023-10-05 17:04 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Click FAB button
2. Click Send message
3. Select Room tab
4. In a Welcome message, Observed that it is not possible to enter multiple lines

## Expected Result:
Can input multiple in welcome message

## Actual Result:
 Can't input multiple in welcome message

## Workaround:
Unknown 

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [x] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 1.3.78.0
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/93399543/59eaf997-e2a6-481b-92c1-69d43cbab40d

https://github.com/Expensify/App/assets/93399543/7270f63f-80ad-4d38-9794-232f30faa22b

**Expensify/Expensify Issue URL:**
**Issue reported by:**@namhihi237
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1696481609247479

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01f77d44c0e5899006</li>
        <li>Upwork Job ID: 1709977909187358720</li>
        <li>Last Price Increase: 2023-10-05</li>
    </ul>
</details>

**Comment by abzokhattab** [comment] 2023-10-05 17:13
## Proposal

### Please re-state the problem that we are trying to solve in this issue.

cannot enter multiline in the welcome message field when creating a room 
### What is the root cause of that problem?
mutliline is not enabled in the `TextInput` of the welcome message field
https://github.com/Expensify/App/blob/67d19598fcc3b34949a80cfc340086c8781fe0ad/src/pages/workspace/WorkspaceNewRoomPage.js#L196

### What changes do you think we should make in order to solve the problem?

add `multiline` prop to the textInput field:

```javascript
         <TextInput
                                    inputID="welcomeMessage"
                                    label={translate('welcomeMessagePage.welcomeMessageOptional')}
                                    accessibilityLabel={translate('welcomeMessagePage.welcomeMessageOptional')}
                                    accessibilityRole={CONST.ACCESSIBILITY_ROLE.TEXT}
                                    autoGrowHeight
                                    multiline
                                    maxLength={CONST.MAX_COMMENT_LENGTH}
                                    autoCapitalize="none"
                                    textAlignVertical="top"
                                    containerStyles={[styles.autoGrowHeightMultilineInput]}
                                />
```

### What alternative solutions did you explore? (Optional)

**Reminder:** Please use plain English, be brief and avoid jargon. Feel free to use images, charts or pseudo-code if necessary. Do not post large multi-line diffs or write walls of text. Do not create PRs unless you have been hired for this job.

**Comment by chahedmoetaz** [comment] 2023-10-05 17:16
Proposal

Please re-state the problem that we are trying to solve in this issue.
Here's an example of how you might address this issue in code



import javax.swing.*;
import java.awt.*;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;

public class WelcomeMessageApp extends JFrame implements ActionListener {
    private JTextArea welcomeTextArea;
    private JButton sendButton;

    public WelcomeMessageApp() {
        setTitle("Welcome Message Example");
        setSize(400, 300);
        setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);

        JPanel panel = new JPanel();
        panel.setLayout(new BorderLayout());

        welcomeTextArea = new JTextArea();
        welcomeTextArea.setLineWrap(true); // Enable line wrapping for multiple lines
        JScrollPane scrollPane = new JScrollPane(welcomeTextArea);
        panel.add(scrollPane, BorderLayout.CENTER);

        sendButton = new JButton("Send Message");
        sendButton.addActionListener(this);
        panel.add(sendButton, BorderLayout.SOUTH);

        add(panel);
    }

    @Override
    public void actionPerformed(ActionEvent e) {
        if (e.getSource() == sendButton) {
            String welcomeMessage = welcomeTextArea.getText();
            // Your code to send the message goes here
            // ...
            // Handle sending the message with the entered welcomeMessage
            System.out.println("Welcome Message: " + welcomeMessage);
        }
    }

    public static void main(String[] args) {
        SwingUtilities.invokeLater(() -> {
            WelcomeMessageApp app = new WelcomeMessageApp();
            app.setVisible(true);
        });
    }
}

**Comment by hayesnano** [comment] 2023-10-05 18:05
I am not able to access the new chat page that you have i always get this page @Ollyws: 

i am on main last version:

is there any env variable or something that i need to use?
<img width="1496" alt="image" src="https://github.com/Expensify/App/assets/88592661/985a5ded-9a80-4860-9334-101788281a80">

**Comment by hayesnano** [comment] 2023-10-05 18:17
Thanks @Ollyws  its working now

**Comment by tjferriss** [comment] 2023-10-05 20:40
I'm going to close this as I don't view it to be a bug. This is a new feature request which I don't think we'll prioritize at this time.

**Closed by tjferriss** 2023-10-05 20:40 UTC
Labels: External, Daily, Help Wanted, Bug
