### ISSUE TITLE
[$500]  last entered value is cleared from composer when user enters value while composer is not focused

### ISSUE THREAD

**Issue by m-natarajan** [Expensify/App#29110] opened 2023-10-09 17:45 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.3.79-3
**Reproducible in staging?:** Yes
**Reproducible in production?:** Yes
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** @Natnael-guchima
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1696826994078919

## Action Performed:
1. Open an existing chat
2. Click outside of the composer to remove focus from the composer
3. type: 123
4. Click outside of the composer to remove focus from the composer quickly
5. type 3 quickly
## Expected Result:
'3' should be entered to composer and remain in the composer
## Actual Result:
'3' is entered to composer then cleared from the composer
## Workaround:
Unknown
## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos
<details>
<summary>Android: Native</summary>

</details>

<details>
<summary>Android: mWeb Chrome</summary>

</details>

<details>
<summary>iOS: Native</summary>

</details>

<details>
<summary>iOS: mWeb Safari</summary>

</details>

<details>
<summary>MacOS: Chrome / Safari</summary>

https://github.com/Expensify/App/assets/38435837/35c7187f-be3a-467d-aeee-a5a12b883b1c

https://github.com/Expensify/App/assets/38435837/4cd93fd7-2248-4634-9f02-2482fd055be1

</details>

<details>
<summary>MacOS: Desktop</summary>

https://github.com/Expensify/App/assets/38435837/37207c55-04ec-46db-8635-f62805e4e0da

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01c5cac46ca86c6638</li>
        <li>Upwork Job ID: 1711437859721748480</li>
        <li>Last Price Increase: 2023-10-16</li>
    </ul>
</details>

**Comment by deomaius** [comment] 2023-10-09 22:45
Your Expensify account email: samuel.jj.gosling@gmail.com
Upwork Profile Link: https://www.upwork.com/freelancers/~01ce0a9aea6baa0b6a

**Comment by deomaius** [comment] 2023-10-09 22:46
Contributor details
Your Expensify account email: samuel.jj.gosling@gmail.com
Upwork Profile Link: https://www.upwork.com/freelancers/~01ce0a9aea6baa0b6a

**Comment by deomaius** [comment] 2023-10-10 00:50
# Proposal

## Please re-state the problem that we are trying to solve in this issue.

Solve unnecessary composer resets, when bearing a previous input state and refocused via keyboard inputs.

## What is the root cause of that problem?

Implict declaration of the `comment` prop in SilentCommentUpdater.js as it is used with state conditioning with the `shouldSyncComment` parameter.

https://github.com/Expensify/App/blob/5fb236e8d50af46df1828ee0fa31ccfaa87df24b/src/pages/home/report/ReportActionCompose/ComposerWithSuggestions.js#L563-L569

https://github.com/Expensify/App/blob/5fb236e8d50af46df1828ee0fa31ccfaa87df24b/src/pages/home/report/ReportActionCompose/SilentCommentUpdater.js#L50

## What changes do you think we should make in order to solve the problem?

Explictly define the suitable parameter to reflect the most recent composer input, that being `commentRef.current`in the `shouldSyncComment` condition parameter. Redact the `comment`prop in SilentCommentUpdater.js as it is redundant. 

```
const shouldSyncComment = prevCommentProp !== commentRef.current && value !== commentRef.current;
```

What alternative solutions did you explore? (Optional)

Originally the problem was percieved to be a delayed state operation on behalf on Onyx report injections, on further analysis the solution was far less complex.

**Comment by deomaius** [comment] 2023-10-13 01:21
> @deomaius, the change will affect the sync functionality. We synchronise the draft value between tabs.

What? The comment prop value is implictly undefined in the context of the component. You're statement does not make sense, please clarify further.

**Comment by deomaius** [comment] 2023-10-16 06:45
> @deomaius, the change will affect the sync functionality. We synchronise the draft value between tabs.

Then without modifying SilentCommentUpdater.js, the root of the issue may be able to be addressed by not explicitly defining whether the `updateComment` parameter `shouldDebounceSaveComment`  as true but false in for the Composer props.

https://github.com/Expensify/App/blob/5fb236e8d50af46df1828ee0fa31ccfaa87df24b/src/pages/home/report/ReportActionCompose/ComposerWithSuggestions.js#L516

**Closed** 2023-10-17 16:03 UTC
Labels: External, Daily, Help Wanted, Overdue, Bug

**Comment by deomaius** [comment] 2023-10-17 16:57
> This isn't an expected worfklow or an action that would occur naturally in the product. I'm going to close this out.

Amazing, would appreciate a more timely response to the review process so I know I am not wasting my time analysing your extensive codebase. I imagine out of the three proposals I submitted, not one will result in remuneration.
