### ISSUE TITLE
[$1000] Unable to logout user completely in low network condition

### ISSUE THREAD

**Issue by kavimuru** [Expensify/App#24501] opened 2023-08-13 14:09 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
PRECONDITION: The network condition needs to be slow, and the user should have many chats.
1. Login to the account.
2. Logout while data is not fully loaded.
3. The user will be re-directed to the login page.
4. Reload the page >> Observe that the user is logged in again.

## Expected Result: 
The user should be completely logged out.
## Actual Result: 
The user is not completely logged out and can be logged in again just by reloading the page.

## Workaround:
Can the user still use Expensify without this being fixed? Have you informed them of the workaround?

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [x] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:**
**Reproducible in staging?:** Needs reproduction (Applause team can't reproduce)
**Reproducible in production?:** Needs reproduction 
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/43996225/4ad6f3a5-dcfe-4476-bafb-7d04ba21a93b

**Expensify/Expensify Issue URL:**
**Issue reported by:** @tranvantoan-qn
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1691080207532809

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01f4a7280251bd89e8</li>
        <li>Upwork Job ID: 1690993607616303104</li>
        <li>Last Price Increase: 2023-09-11</li>
    </ul>
</details>

**Comment by kadiealexander** [comment] 2023-08-14 07:47
Reproed kind of, it doesn't seem to populate MY account but it does behave odd once logged out:

https://github.com/Expensify/App/assets/59587260/51161bf8-c830-4c6b-852a-7d4928b2f3ea

**Comment by tranvantoan-qn** [comment] 2023-08-14 07:51
@kadiealexander 
I'm glad you were able to reproduce the issue too, so it's now more likely to be fixed.
I wasn't sure if it was related to the network connection, but I've seen this issue many times before.
Sometimes, it leads to the common error that prevents users from logging in, until they clear OnxDB.

**Comment by Santhosh-Sellavel** [comment] 2023-08-14 21:08
Unable to reproduce this bug

**Comment by kadiealexander** [comment] 2023-08-14 21:55
@Santhosh-Sellavel do you have a high-traffic account you could test this on? It seems to only happen for accounts with enough chats/content in, I wasn't able to repro in a test account but I could on my main account that has a lot more chats in it.

**Comment by Santhosh-Sellavel** [comment] 2023-08-15 20:37
I tried with a new high-traffic account and my account with my main testing account which has most chat reports still unable to reproduce at my end. Can you check again today @kadiealexander?

**Comment by tranvantoan-qn** [comment] 2023-08-16 02:36
Yeah, low network connection and logging out quickly after logging in may help.
Though, I dont have high traffic account, just joined 2 public chat rooms (Scale New Height's room), some chats/content but the issue still happen quite often for me.

**Comment by Santhosh-Sellavel** [comment] 2023-08-21 16:42
I couldn't reproduce the issue even once.

**Comment by Santhosh-Sellavel** [comment] 2023-08-22 16:58
@tienifr No luck

https://github.com/Expensify/App/assets/85645967/0379c2cd-4e37-439a-9ecf-b2ac88728b51

**Comment by tranvantoan-qn** [comment] 2023-08-22 17:02
@Santhosh-Sellavel Can you change this Throttling setting to something like **Slow 3G** and use normal Chrome mode - not private (sometimes it happens easier on normal mode)

![image](https://github.com/Expensify/App/assets/10254571/c6097061-0888-4a9b-a80a-64d1513e4919)

**Comment by Santhosh-Sellavel** [comment] 2023-08-22 17:04
@tranvantoan-qn No throttling shouldn't be the problem as @tienifr can reproduce with the same [here](https://github.com/Expensify/App/issues/24501?notification_referrer_id=NT_kwDOBRraj7M3MzcwODUxNDA1Ojg1NjQ1OTY3#issuecomment-1687345126). But FYI - I've tried using Slow 3G & Normal chrome too!

**Comment by kadiealexander** [comment] 2023-08-28 06:29
Bumped [here](https://expensify.slack.com/archives/C02NK2DQWUX/p1693203978480169)

**Comment by Santhosh-Sellavel** [comment] 2023-08-28 20:25
I couldn't reproduce at all, @kadiealexander Are you still able to reproduce?

**Comment by kadiealexander** [comment] 2023-08-29 05:32
I can't reproduce this anymore on staging.

**Comment by kadiealexander** [comment] 2023-09-01 01:34
@tienifr could you please share a video of you reproducing this on staging?

**Comment by kadiealexander** [comment] 2023-09-04 02:29
@tienifr @tranvantoan-qn could either of you please confirm if this is still reproducible?

**Comment by Santhosh-Sellavel** [comment] 2023-09-07 18:29
@kadiealexander We are good to close this then, thanks!

**Comment by tranvantoan-qn** [comment] 2023-09-07 18:39
It still happens to me sometimes, though less often. Can you keep it open a little longer so I can continue to investigate the specific condition (if any)?

**Comment by Santhosh-Sellavel** [comment] 2023-09-08 17:05
Sorry, I was never able to reproduce this even once. 

But if there is a flaw in Onyx it might haunt us in other areas too not just in this flow. So Feel free to start a thread in expensify-open-source explaining the problem & solution. Let's see what community & engineers thoughts act based on the consensus thereby creating a new issue with more context to the problem, thanks!

cc: @kadiealexander

**Comment by kadiealexander** [comment] 2023-09-12 04:00
Closing as no longer reproducible. @tranvantoan-qn if you investigate and find something helpful please feel free to comment here and we can consider reopening this.

**Closed by kadiealexander** 2023-09-12 04:00 UTC
Labels: External, Engineering, Daily, Help Wanted, Overdue, Bug
