### ISSUE TITLE
[HOLD for payment 2023-12-15] [$500] IOS - A spinner appears in the chat when a message is posted

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#30729] opened 2023-11-01 17:54 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.3.94.1
**Reproducible in staging?:** YES
**Reproducible in production?:** NO
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:**  @mountiny 
**Slack conversation:**

## Action Performed:
1. Log in IOS app
2. Send the message

## Expected Result:
A spinner doesn't appear in the chat when a message is posted

## Actual Result:
A spinner appears in the chat when a message is posted

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [x] iOS: Native
- [ ] iOS: mWeb Safari
- [ ] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

https://github.com/Expensify/App/assets/93399543/a42f7ceb-5284-4b9a-936c-957b94efb537

https://github.com/Expensify/App/assets/93399543/1784256c-63ae-4111-a7d0-935f5c46e26f

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01d9960c2187a7e349</li>
        <li>Upwork Job ID: 1719847322291130368</li>
        <li>Last Price Increase: 2023-11-01</li>
<li>Automatic offers: </li>
<ul>
<li>abdulrahuman5196 | Reviewer | 27654812</li>
</ul></li>
    </ul>
</details>

**Comment by aldo-expensify** [comment] 2023-11-01 18:16
Can't reproduce in Web, I'm trying to setup my env to run IOS

**Comment by aldo-expensify** [comment] 2023-11-01 19:39
I'm not being able to reproduce this.

This is the code that renders that spinner at the bottom: https://github.com/Expensify/App/blob/30da921305c0b70cef887ce0321b3da820afbfd8/src/pages/home/report/ListBoundaryLoader/ListBoundaryLoader.js#L59-L64 (thanks @Beamanator)

This can only happen when `type` is HEADER, so the only usage of the `ListBoundaryLoader` we should look at is this one: https://github.com/Expensify/App/blob/30da921305c0b70cef887ce0321b3da820afbfd8/src/pages/home/report/ReportActionsList.js#L401C1-L404

**Comment by aldo-expensify** [comment] 2023-11-01 19:42
Asking for help reproducing here: https://expensify.slack.com/archives/C01GTK53T8Q/p1698867709638349

**Comment by aldo-expensify** [comment] 2023-11-01 20:41
Testing if this is happening in production

**Comment by s-alves10** [comment] 2023-11-01 20:43
I think this would be reproducible in production as well

**Comment by aldo-expensify** [comment] 2023-11-01 20:50
> I think this would be reproducible in production as well

I have the same feeling, and I just confirmed it.

Removing deploy blocker, reproduced in production:


https://github.com/Expensify/App/assets/87341702/d0858e52-e06c-4c9e-8cd8-a3b8753957e1

**Comment by s-alves10** [comment] 2023-11-01 21:48
## Proposal

### Please re-state the problem that we are trying to solve in this issue.

A spinner appears in the chat when pressing enter after send a message

### What is the root cause of that problem?

Please check the code
https://github.com/Expensify/App/blob/3db5ff4a1924156c748291d25eb9d774d82f879e/src/components/InvertedFlatList/BaseInvertedFlatList.js#L137-L140

`minIndexForVisible` makes the flatlist change its scroll position to maintain the position of the last message when sending a new message. This causes `onStartReached` call.

This is the root cause



### What changes do you think we should make in order to solve the problem?

I think we can safely remove the `minIndexForVisible` setting. 

`autoscrollToTopThreshold` was added to fix https://github.com/Expensify/App/issues/30395 and https://github.com/Expensify/App/issues/30423 but these issues doesn't happen without `minIndexForVisible` setting. So we can remove the `maintainVisibleContentPosition` props

Remove the code below
https://github.com/Expensify/App/blob/3db5ff4a1924156c748291d25eb9d774d82f879e/src/components/InvertedFlatList/BaseInvertedFlatList.js#L137-L140

This works fine as expected

<details>
    <summary>Result</summary>


https://github.com/Expensify/App/assets/126839717/11ef6c49-61ee-46f7-9565-c46274b6919a


</details>

### What alternative solutions did you explore? (Optional)

**Comment by roryabraham** [comment] 2023-11-04 01:04
cc @quinthar as you reported a [similar bug](https://expensify.slack.com/archives/C049HHMV9SM/p1698623055435299) in slack

**Comment by roryabraham** [comment] 2023-11-04 01:05
> I think we can safely remove the minIndexForVisible setting.

No can do – that was put in place in anticipation of an upcoming change

**Comment by roryabraham** [comment] 2023-11-04 01:08
> We should add the stop condition in loadNewerChats if we already loaded all messages.

That's the right idea, but the proposed solution won't work as we don't have a global count of reportActions. Everything `sequenceNumber` is deprecated and should no longer be used

**Comment by roryabraham** [comment] 2023-11-04 01:11
So I think as @quinthar suggested, the solution here has to be something like:

1. Detect if `GetNewerActions` returned less than a page of actions – that tells us we're at the front of the chat and up-to-date
1. If we're at the end of the chat and up-to-date, don't trigger any more `GetNewerActions` calls.
1. Need to figure out how and when to reset that logic.

If it's okay with everyone, I think it's best if @perunt handles this as he has the most context. I'll take it over from @aldo-expensify as the internal assignee. @perunt can you comment on this so I can assign to you?

**Comment by roryabraham** [comment] 2023-11-04 01:12
Not overdue melvin, I literally just commented...

**Comment by roryabraham** [comment] 2023-11-04 01:13
Making this a weekly until we finish the last comment linking issue. Want to make sure we can correctly paginate in both directions before trying to add some logic to skip `GetNewerActions` when we know we're at the front

**Comment by aldo-expensify** [comment] 2023-11-04 01:21
Thanks for jumping in @roryabraham I definitely wouldn't have known this: https://github.com/Expensify/App/issues/30729#issuecomment-1793280439

**Comment by aldo-expensify** [comment] 2023-11-04 01:21
This plan https://github.com/Expensify/App/issues/30729#issuecomment-1793282280 sounds good to me 😉

**Comment by perunt** [comment] 2023-11-04 09:16
Sure thing, I'll handle this

**Comment by perunt** [comment] 2023-11-06 09:10
> This loader appears because onStartReached triggered with each rerender of the list. So, ideally, the solution should be to reduce the render of this list to at least two renders (ideally one). Or go upstream and update onStartReached to be not triggered on list mount. I haven't tried your fix yet, but it looks like it fixes traces but not a core problem

This loader appears because `onStartReached` triggered with each rerender of the list. So, ideally, the solution should be to reduce the render of this list to at least two renders (ideally one). Or go upstream and update `onStartReached` to be not triggered on list mount. I haven't tried your fix yet, but it looks like it fixes traces but not a core problem

**Comment by perunt** [comment] 2023-11-08 10:18
Yes, the `onStartReached` is triggered by the `reportScrollManager.scrollToBottom()` when scrolling down. This action is necessary because we want to scroll the user to the bottom when a new message arrives via Pusher.
Currently, it works because we've implemented `autoscrollToTopThreshold` as a temporary fix. However, in the next iteration, we will remove this workaround. Consequently, the reception of a new message will result in scrolling to the bottom as per the scrollToBottom function.
Imo, we should focus on preventing the unwanted triggering of this function instead of disabling the scroll-to-end feature

**Comment by perunt** [comment] 2023-11-08 10:19
Yes, you're right that the onStartReached is triggered by the reportScrollManager.scrollToBottom() when scrolling down. This action is necessary because we want to scroll the user to the bottom when a new message arrives via Pusher.
Currently, it works because we've implemented autoscrollToTopThreshold as a temporary fix. However, in the next iteration, we will remove this workaround. Consequently, the reception of a new message will result in scrolling to the bottom as per the scrollToBottom function.
Imo, we should focus on preventing the unwanted triggering of this function instead of disabling the scroll-to-end feature

**Comment by perunt** [comment] 2023-11-15 17:06
@roryabraham Hey, I've been giving this some thought, and here's an idea I came up with:

- We could limit the use of `onStartReached` to only when we have a `reportActionID` that we're specifically linked to.
- Since we're sorting manually each time, we can add a 'latest' flag to the most recent message

We've had that persistent bug where the report action gets lost when returning from offline. Currently, we always invoke `OpenReport` in such scenarios to get the most recent ReportAction. And with gap detection in place, we start fetching new elements just before this last ReportAction. This makes the use of `OnStartReached` somewhat redundant, as `OnEndReached` is already doing the heavy lifting.

In regular cases, we have a pusher that will handle data receiving

However, there's one exception to this:
Imagine we scroll back to an older message, then go offline, and later come back online. We perform `OpenReport` again, notice a gap, then select the `ReportActionID` from the viewport (to avoid any jumps), and re-filter all reports. In this scenario, it's essential to trigger `OnStartReached` when we hit the bottom edge. Once we reach the last message marked as 'latest', we'll know we're up to date.

**Comment by conorpendergrast** [comment] 2023-11-21 10:13
@roryabraham do you have a moment to check @perunt's idea here?

**Comment by conorpendergrast** [comment] 2023-11-23 21:40
Rory is enjoying Thanksgiving, so I'll pester him for proposal reviews next week!

**Comment by conorpendergrast** [comment] 2023-11-30 11:32
@roryabraham could you give a perspective on [this](https://github.com/Expensify/App/issues/30729#issuecomment-1812927281), please?

**Comment by conorpendergrast** [comment] 2023-12-18 13:50
**Payouts due:**

Issue Reporter: N/A - @mountiny 
Contributor: N/A (contractor) @perunt 

- [x] Contributor+: $500 @abdulrahuman5196 - [contract](https://www.upwork.com/nx/wm/workroom/35443637/overview)

Upwork job is [here](https://www.upwork.com/jobs/~01d9960c2187a7e349).

**Comment by conorpendergrast** [comment] 2023-12-18 13:50
@abdulrahuman5196 just [the C+ checklist](https://github.com/Expensify/App/issues/30729#issuecomment-1846340613) to do now, thanks!

**Comment by abdulrahuman5196** [comment] 2023-12-19 09:06
>The PR that introduced the bug has been identified. Link to the PR:
The offending PR has been commented on, pointing out the bug it caused and why, so the author and reviewers can learn from the mistake. Link to comment:
A discussion in #expensify-bugs has been started about whether any other steps should be taken (e.g. updating the PR review checklist) in order to catch this type of bug sooner. Link to discussion:

Seems to related to code changes introduced as part of comment linking.

>Determine if we should create a regression test for this bug.

Yes. If not already present.

>If we decide to create a regression test for the bug, please propose the regression test steps to ensure the same bug will not reach production again.

1) Open a chat and check the bottom loader, you shouldn't see it.
2) Scroll to the top and bottom to check if it appears.
3) Send messages.
4) No bottom loader should appear as you send messages

Thank you for processing. @conorpendergrast I have also added the checklist.

**Comment by conorpendergrast** [comment] 2023-12-22 11:47
Regression test created: https://github.com/Expensify/Expensify/issues/353947

Thanks all!

**Closed by conorpendergrast** 2023-12-22 11:47 UTC
Labels: External, Engineering, Daily, Overdue, Awaiting Payment, Bug
