### ISSUE TITLE
[HOLD for payment 2024-10-24] [$250] When using the account switcher on iOS there is no safe area

### ISSUE THREAD

**Issue by m-natarajan** [Expensify/App#48292] opened 2024-08-29 19:50 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 9.0.26-1
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** @AndrewGable 
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1724946621382309

## Action Performed:
1.Launch the app and login
2. Tap settings > Account switcher arrows

## Expected Result:
No display issues and modal view is scrollable
## Actual Result
There is no safe area when using the account switcher
## Workaround:
Unknown
## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [x] iOS: Native
- [ ] iOS: mWeb Safari
- [ ] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

![unnamed](https://github.com/user-attachments/assets/67673cd8-b20d-4379-a80b-108fa8d9de53)

![IMG_1397](https://github.com/user-attachments/assets/d6415083-1113-4f20-b742-a99366578106)

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~021831817133463086139</li>
        <li>Upwork Job ID: 1831817133463086139</li>
        <li>Last Price Increase: 2024-09-05</li>
<li>Automatic offers: </li>
<ul>
<li>nkdengineer | Contributor | 103922536</li>
</ul></li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @RachCHopkins</details>

**Comment by dangrous** [comment] 2024-08-29 20:02
cc @rushatgabhane on this one

**Comment by RachCHopkins** [comment] 2024-08-30 02:27
> Launch the app

Which app? Hybrid app?

> Tap settings > Account switcher arrows

I don't know what this means.

Can we get some more detailed instructions for testing/reproducing, please?

**Comment by RachCHopkins** [comment] 2024-08-30 02:31
Ok, looks like it's:

Launch the New Expensify app. 
Go to Settings > tap username at the top to switch accounts

I can confirm I can't scroll in the list. I'm not sure what "safe area" means, but if I try to select my own account, the app crashes.

**Comment by RachCHopkins** [comment] 2024-08-30 02:32
Waiting to see what @rushatgabhane has to add here! However this is supposed to work, it's definitely not working like it should.

**Comment by dangrous** [comment] 2024-08-30 15:06
safe area means the area where default phone interface stuff should be (like in the screenshot, it's overlapping with the wifi symbols, etc.)\

I think we can go ahead and assign @rushatgabhane here for a solution! I can also take this on from the engineering side

**Comment by RachCHopkins** [comment] 2024-09-05 23:14
@dangrous do we need to remove @rushatgabhane?

**Comment by ItxAltaf** [comment] 2024-09-06 01:57
You can use SafeAreaView property if you are working with react native

**Comment by ItxAltaf** [comment] 2024-09-06 03:28
Contributor details
Your Expensify account email: itxaltaf789@gmail.com
Upwork Profile Link: https://www.upwork.com/freelancers/~01ff545e274abdf999?mp_source=share

**Comment by kishan-dhankecha** [comment] 2024-09-06 03:51
You can add a `SafeArea` widget as the scaffold body. So that AppBar and such things won't affect with the padding, it is also safe for content.

**Comment by kishan-dhankecha** [comment] 2024-09-06 03:53
Contributor details
Your Expensify account email: dhankechakishan@gmail.com
Upwork Profile Link: https://www.upwork.com/freelancers/kishandhankecha

**Comment by nkdengineer** [comment] 2024-09-06 08:04
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
There is no safe area when using the account switcher and the list is not scrollable

### What is the root cause of that problem?
We don't apply `SafeAreaConsumer` for account switcher popover and we don't wrap this component with a `ScrollView` then it's not scrollable

https://github.com/Expensify/App/blob/da8370fd434594a2ade67a81035a6caec0d0118c/src/components/AccountSwitcher.tsx#L169

### What changes do you think we should make in order to solve the problem?
We should use `SafeAreaConsumer` and wrap this component with a `ScrollView` with maxHeight style based on the `insets`

```
<Popover
    isVisible={shouldShowDelegatorMenu}
    onClose={() => {
        setShouldShowDelegatorMenu(false);
        clearDelegatorErrors();
    }}
    anchorRef={buttonRef}
    anchorPosition={styles.accountSwitcherAnchorPosition}
>
    <SafeAreaConsumer>
        {({insets}) => {
            return (
                <ScrollView
                    contentContainerStyle={[styles.flexGrow1]}
                    style={{maxHeight: windowHeight - (insets?.bottom ?? 0) - (insets?.top ?? 0)}}
                >
                    <View style={[styles.pb4]}>
                        <Text style={[styles.createMenuHeaderText, styles.ph5, styles.pb2, styles.pt4]}>{translate('delegate.switchAccount')}</Text>
                        <MenuItemList
                            menuItems={menuItems()}
                            shouldUseSingleExecution
                        />
                    </View>
                </ScrollView>
            );
        }}
    </SafeAreaConsumer>
</Popover>
```

https://github.com/Expensify/App/blob/da8370fd434594a2ade67a81035a6caec0d0118c/src/components/AccountSwitcher.tsx#L178


### What alternative solutions did you explore? (Optional)

### Result

https://github.com/user-attachments/assets/9f30fb77-2931-49e9-a5d8-b3ae1482cd00

**Comment by s77rt** [comment] 2024-09-06 15:25
@nkdengineer Thanks for the proposal. Your RCA is correct. Regarding the solution, can we use `SelectionList` instead? It should cover both `SafeAreaConsumer` and `ScrollView`.

**Comment by nkdengineer** [comment] 2024-09-06 16:27
@s77rt I just tested, on native, it only displays the header.  on Web the scroll issue isn't fixed.

**Comment by s77rt** [comment] 2024-09-06 16:32
@nkdengineer Can you elaborate? How come only the header is visible? You should be able to make it work. If not, can you explain the problem?

**Comment by nkdengineer** [comment] 2024-09-06 17:00
I tested with a `View` that wrap the `SelectionList`, if I fix the height of `View` component it works on both web and native. If not the bugs I mentioned above happens.

**Comment by s77rt** [comment] 2024-09-07 05:26
@Expensify/design How is the account switcher list supposed to look when the list contains too many accounts?

Currently it's broken, no safearea consideration, the list is not scrollable and the popover cannot be dismissed 

<img width="559" alt="Screenshot 2024-09-07 at 6 09 55 AM" src="https://github.com/user-attachments/assets/02cbff53-fe91-4fc3-ad16-7f34b93ca5fd">

After fixing the safearea and the scroll issues, it will look like this but it's still not dismissible
<img width="559" alt="Screenshot 2024-09-07 at 6 10 08 AM" src="https://github.com/user-attachments/assets/af1f47bb-eab6-488e-afe3-9a6470dad7a8">
 
Can we have a design view for this case? And is the push to page an option here? (like we done with the workspace switcher)

**Comment by rushatgabhane** [comment] 2024-09-07 08:16
@s77rt i think there would be a max height (50% of the screen) so you can still tap outside to close the modal

**Comment by shawnborton** [comment] 2024-09-08 15:12
I think push to page is a bit heavy for this solution - I think a majority of the use cases won't have so many copilots that it fills the screen.

I agree with the comment about making the modal have a smaller max-height though. Perhaps we cap it at something like 75% or something so there is still amply area to tap to close outside of it?

**Comment by s77rt** [comment] 2024-09-08 21:21
Sounds good

**Comment by s77rt** [comment] 2024-09-08 21:22
@nkdengineer Can you update your proposal based on the above? (and with `SelectionList`)

**Comment by rushatgabhane** [comment] 2024-09-08 21:22
@dangrous let's assign @s77rt

**Comment by rushatgabhane** [comment] 2024-09-08 21:25
If we're using SelectionList then keyboard should navigation should work too, right?

It'll also fix https://github.com/Expensify/App/issues/48245 then

**Comment by nkdengineer** [comment] 2024-09-09 08:10
@s77rt Update my [proposal](https://github.com/Expensify/App/issues/48292#issuecomment-2333482798)

**Comment by nkdengineer** [comment] 2024-09-09 11:48
Let me check again.

**Comment by nkdengineer** [comment] 2024-09-10 14:15
@s77rt I updated proposal with alternative solution for `PopoverMenu`.

**Comment by s77rt** [comment] 2024-09-10 17:49
@nkdengineer Thanks for the update. The proposal overall looks good to me.

🎀 👀 🎀 C+ reviewed
[Link to proposal](https://github.com/Expensify/App/issues/48292#issuecomment-2333482798)

**Comment by dangrous** [comment] 2024-09-11 23:29
works for me!

**Comment by nkdengineer** [comment] 2024-09-12 10:49
@s77rt The PR is ready https://github.com/Expensify/App/pull/49051.

**Comment by s77rt** [comment] 2024-10-07 20:05
Still trying to fix a performance issue

**Comment by dangrous** [comment] 2024-10-15 14:31
Just to pull it out here - that ^ is not a regression, correct? It's an existing bug.

**Comment by s77rt** [comment] 2024-10-15 16:44
Yes technically it's an existing bug in `PopoverMenu` which is what we opted to use in the `AccountSwitcher`.

**Comment by s77rt** [comment] 2024-10-20 10:43
- The PR that introduced the bug has been identified: https://github.com/Expensify/App/pull/47338
- The offending PR has been commented on: https://github.com/Expensify/App/pull/47338#discussion_r1807767503
- A discussion in #expensify-bugs has been started: Not needed
- Determine if we should create a regression test for this bug: No (edge case)

**Comment by RachCHopkins** [comment] 2024-10-24 04:54
Payment Summary:

- Contributor: @nkdengineer to be paid $250 via Upwork
- Contributor+: @s77rt to be paid $250 via NewDot Manual Request
Upwork job [here](https://www.upwork.com/jobs/~021831817133463086139)

**Comment by RachCHopkins** [comment] 2024-10-24 04:57
Contributor has been paid, the contract has been completed, and the Upwork post has been closed.

**Comment by JmillsExpensify** [comment] 2024-10-24 09:22
$250 approved for @s77rt

**Comment by tgolen** [comment] 2024-10-24 16:36
Reopening so @RachCHopkins can complete the BZ checklist. Can you please copy @s77rt's answers to the checklist and finish it out?

**Comment by RachCHopkins** [comment] 2024-10-25 05:42
Sorry @tgolen I don't understand - there is no regression test for me to set up?

Did you need me to change @s77rt's checklist bullet points to check boxes and tick them?

**Comment by tgolen** [comment] 2024-10-25 17:18
I'll just close this for now.

**Closed by tgolen** 2024-10-25 17:18 UTC
Labels: External, Daily, Awaiting Payment, Bug
