### ISSUE TITLE
[HOLD for payment 2024-10-10] [$250] Expenses - Deleted Expense that was edited appears when user goes offline

### ISSUE THREAD

**Issue by IuliiaHerets** [Expensify/App#49329] opened 2024-09-17 09:11 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 9.0.36-1
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**Email or phone of affected tester (no customers):** applausetester+uo0914@applause.expensifail.com
**Issue reported by:** Applause Internal Team

## Action Performed:
1. Submit any expense to Workspace or 1:1 chat
2. Tap and edit any details of the expense
3. Tap header of expense and delete expense
4. After returning to chat, go offline

## Expected Result:
Deleted expense doesn't appear

## Actual Result:
Deleted expense re-appears greyed out and says "user owes" after going offline

## Workaround:
Unknown

## Platforms:

- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

https://github.com/user-attachments/assets/5a602f31-d42d-44c0-a310-3acbe110a6b7

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~021836153049228663209</li>
        <li>Upwork Job ID: 1836153049228663209</li>
        <li>Last Price Increase: 2024-09-24</li>
<li>Automatic offers: </li>
<ul>
<li>huult | Contributor | 104163087</li>
</ul></li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @aimane-chnaif</details>

**Comment by IuliiaHerets** [comment] 2024-09-17 09:11
@mallenexpensify  FYI I haven't added the External label as I wasn't 100% sure about this issue. Please take a look and add the label if you agree it's a bug and can be handled by external contributors

**Comment by mkzie2** [comment] 2024-09-17 14:41
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
Deleted expense re-appears greyed out and says "user owes" after going offline

### What is the root cause of that problem?

We don't clear the `pendingAction` of the `REPORTPREVIEW` action when the delete API is complete then this action appears when we go offline because it's marked as pending delete

### What changes do you think we should make in order to so blve the problem?
In `buildOnyxDataForMoneyRequest` function we should check if we create a new report preview action we will clear the `pendingAction` in `successData`.

> if we create a new report preview action

To check this we can use `shouldCreateNewMoneyRequestReport` variable

```
if (shouldCreateNewMoneyRequestReport) {
    successData.push(
        {
            onyxMethod: Onyx.METHOD.MERGE,
            key: `${ONYXKEYS.COLLECTION.REPORT_ACTIONS}${chatReport?.reportID}`,
            value: {
                [reportPreviewAction.reportActionID]: {
                    pendingAction: null
                },
            },
        },
    )
}
```
https://github.com/Expensify/App/blob/7674e838f453d47ecaba6a4d003a8c69ad30aa8b/src/libs/actions/IOU.ts#L505

We should check for other actions and other build onyx function in money request flow if it has the same problem.
### What alternative solutions did you explore? (Optional)

**Comment by mallenexpensify** [comment] 2024-09-17 21:20
👀 plz @aimane-chnaif .   Can you confirm that you're able to reproduce? It appears I was but I ran into a couple issues an my flow was funky. 


https://github.com/user-attachments/assets/31875ca5-53ab-4724-91c4-92150320a73c

**Comment by huult** [comment] 2024-09-22 08:53
## Proposal

### Please re-state the problem that we are trying to solve in this issue.

Deleted Expense that was edited appears when user goes offline

### What is the root cause of that problem?

The reason for this issue is that `reportAction.pendingAction` is not updated when the `DeleteMoneyRequest` command is called. As a result, `reportAction.pendingAction` remains `delete` after the command is executed. This causes the condition [`ReportActionsUtils.shouldReportActionBeVisible(reportAction, reportAction.reportActionID)`](https://github.com/Expensify/App/blob/539327dc2d0585624e5e0b990ca0d79f4e66e81b/src/libs/ReportActionsUtils.ts#L662) to return `true`, and since `isOffline` is also `true`, the issue occurs

https://github.com/Expensify/App/blob/9160fa585c26d3312fd6d6fbd69d334e66cb373d/src/pages/home/report/ReportActionsList.tsx#L194-L199

The reason `DeleteMoneyRequest` did not update `pendingAction` is because we called the `UpdateMoneyRequestDate` command to update the date, and it returned a `lastUpdateID` greater than DeleteMoneyRequest.

https://github.com/Expensify/App/blob/539327dc2d0585624e5e0b990ca0d79f4e66e81b/src/libs/Middleware/SaveResponseInOnyx.ts#L33

The warning I mentioned for that.

<img width="598" alt="Screenshot 2024-09-22 at 15 10 53" src="https://github.com/user-attachments/assets/8e068ce6-a9f3-4ef9-9f82-3206cb1be10f">


### What changes do you think we should make in order to solve the problem?

We need the backend to update `lastUpdateID` for `DeleteMoneyRequest` because we send `clientUpdateID` to the API, but the response contains a different value, as shown in the image below:

send `clientUpdateID: 1973749768`

<img width="1707" alt="Screenshot 2024-09-22 at 15 51 39" src="https://github.com/user-attachments/assets/f9accdb4-fc0e-4e8a-b82d-801dc9e0c184">

and reponse `previousUpdateID: 1973749978` that should be `previousUpdateID: 1973749769` and `lastUpdateID: 1973749980`

<img width="1706" alt="Screenshot 2024-09-22 at 15 52 05" src="https://github.com/user-attachments/assets/4dfd4bb8-9c1f-4b5c-9ea6-0167dcaf3741">

or 
If we don't want to update the backend, then we should add the command `DELETE_MONEY_REQUEST` to the ignore list, something like this:

```diff
// ./src/libs/Middleware/SaveResponseInOnyx.ts#L8
const requestsToIgnoreLastUpdateID: string[] = [
    WRITE_COMMANDS.OPEN_APP,
+   WRITE_COMMANDS.DELETE_MONEY_REQUEST,
     ...
];
```
<summary>
<details>POC

https://github.com/user-attachments/assets/b0894f8c-b071-4993-9975-af8c47c06570

</details>
</summary>

**Comment by mallenexpensify** [comment] 2024-09-23 18:24
@aimane-chnaif 👀 on @huult 's proposal above plz

**Comment by huult** [comment] 2024-09-24 04:03
> The reason DeleteMoneyRequest did not update pendingAction is because we called the UpdateMoneyRequestDate command to update the date, and it returned a lastUpdateID greater than DeleteMoneyRequest.

Can you check this command? The API responds, but the data is not stored locally due to the reason I mentioned. You can add a log above this condition, and you will see.

**Comment by mallenexpensify** [comment] 2024-09-24 21:55
@jasperhuangg , can you confirm if you think this issue is BE? 
You don't need to leave yourself assigned.

**Comment by jasperhuangg** [comment] 2024-09-26 19:01
This seems expected, since it appears the API request to delete the expense hasn't completed, so we display it as greyed out to indicate to the user that it hasn't been deleted yet on the server.

It is strange that the amount doesn't display. That seems like an issue with the Onyx data that's set locally when the expense is deleted. We should probably get the amount to display correct.

This is a front-end issue.

**Comment by huult** [comment] 2024-09-27 16:46
@jasperhuangg , When does the expense delete successfully on the server? I waited for 1 minute and disconnected the network, but the issue still occurred.
If we know when the deletion is successful, I suggest keeping the data, including the amount, until it is deleted on the server and then deleting it.

**Comment by jasperhuangg** [comment] 2024-09-27 18:04
@huult, I see; sorry for the misunderstanding. In that case, your alternative approach of adding the command to the ignore list should work! If the user intends to delete the money request, it doesn't seem like we need to wait for any requests to update fields in the money request.

**Comment by huult** [comment] 2024-09-28 07:10
The PR for [this issue](https://github.com/Expensify/App/pull/49878) is already open

**Comment by mallenexpensify** [comment] 2024-10-11 00:47
Contributor: @huult paid $250 via Upwork
Contributor+: @aimane-chnaif owed $250 via Upwork

@aimane-chnaif can you please accept the job and reply here once you have? 
https://www.upwork.com/jobs/~021836153049228663209

Please fill out the BZ checklist above too, thx

**Comment by mallenexpensify** [comment] 2024-10-14 20:38
test case created
- https://github.com/Expensify/Expensify/issues/435989

@aimane-chnaif can you please accept the job and reply here once you have? 
https://www.upwork.com/jobs/~021836153049228663209

**Comment by mallenexpensify** [comment] 2024-10-17 23:47
@aimane-chnaif paid, payment comment above updated. Thx

**Closed by mallenexpensify** 2024-10-17 23:47 UTC
Labels: External, Daily, Overdue, Awaiting Payment, Bug
