### ISSUE TITLE
[PAYMENT - 01-16: $1000]  Android - Console error when any report is opened - reported by @aneequeahmad

### ISSUE THREAD

**Issue by mvtglobally** [Expensify/App#11096] opened 2022-09-19 05:32 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Launch android app.
2. Click on any report.

## Expected Result:
No console errors

## Actual Result:
Console error Warning: Failed prop type: The prop `anchorPosition.horizontal` is marked as required in `PopoverWithMeasuredContent`, but its value is `undefined`.

## Workaround:
unknown 

## Platform:

Where is this issue occurring?

- Android

**Version Number:** 1.1.94-3
**Reproducible in staging?:** need repro 
**Reproducible in production?:** need repro 
**Email or phone of affected tester (no customers):** 
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation 

**Expensify/Expensify Issue URL:** 
**Issue reported by:** @aneequeahmad
**Slack conversation:** https://expensify.slack.com/archives/C01GTK53T8Q/p1661901563422729

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01064e852643baf5f4</li>
        <li>Upwork Job ID: 1610433379500457984</li>
        <li>Last Price Increase: 2023-01-04</li>
    </ul>
</details>

**Comment by michaelhaxhiu** [comment] 2022-09-20 14:50
@mvtglobally were you not able to reproduce this one when you tried on android?

**Comment by mvtglobally** [comment] 2022-09-20 14:51
@michaelhaxhiu when I use physical device, I can see the console. So I am not sure if it's repro or not

**Comment by abekkala** [comment] 2022-09-20 18:08
If we're not able to reproduce to confirm a bug then I'm going to close this for now.

**Comment by kavimuru** [comment] 2022-10-14 13:49
@abekkala There is another bug reported https://expensify.slack.com/archives/C01GTK53T8Q/p1665657234159879
Do you want me reopen this bug?

**Comment by aneequeahmad** [comment] 2022-10-27 07:07
@kavimuru this is still reproducible in `v1.2.20-0`. Please see the attached video:

**Video**:


https://user-images.githubusercontent.com/36359331/198207580-5803dab0-6442-47a5-a114-eac4aa7d909b.mov

**Comment by aneequeahmad** [comment] 2022-10-27 07:45
**Action Performed:**

- Launch android app.
- Click on any report having attachment like image.
- Long press on attachment(image) message. 

**Expected Result:**

- No console errors

**Actual Result:**

- Console error Warning: Failed prop type: The prop anchorPosition.horizontal is marked as required in PopoverWithMeasuredContent, but its value is undefined.






### **PROPOSAL**

**Problem:**

As `anchorPosition` is set to isRequired in component `PopoverWithMeasuredContent` which is not needed in every case.
https://github.com/Expensify/App/blob/66a05aa4015f96f5bab59929698d517a616620d1/src/components/PopoverWithMeasuredContent.js#L18-L22

**Solution:**

`anchorPosition` should not be set to `isRequired` cuz we don't need to pass prop `anchorPosition` to `PopoverWithMeasuredContent` like `anchorPosition` is not set to `isRequired`  in other components. for example

- **AddPaymentMethodMenu**

https://github.com/Expensify/App/blob/d6ad76fbb83e3a45501dce6625520499f6195d63/src/components/AddPaymentMethodMenu.js#L15-L21



**CODE CHANGE:** 

**FROM**

https://github.com/Expensify/App/blob/66a05aa4015f96f5bab59929698d517a616620d1/src/components/PopoverWithMeasuredContent.js#L18-L22


**TO:**

```
    anchorPosition: PropTypes.shape({
        horizontal: PropTypes.number,
        vertical: PropTypes.number,
    }),

```

**Comment by aneequeahmad** [comment] 2022-11-09 02:31
This is still reproducible on dev main branch v1.2.25-0

**VIDEO:**

https://user-images.githubusercontent.com/36359331/200722675-feec8c4e-df9e-476d-92b8-9c6f4ae95d66.mov



cc: @abekkala

**Comment by aneequeahmad** [comment] 2022-11-22 01:34
@mvtglobally, This error is reproducible on `main branch dev` in version `1.2.29-6`.

**Comment by kavimuru** [comment] 2022-12-15 17:58
@abekkala , @aneequeahmad is still able to reproduce on  dev main v1.2.39-0. I am reopening this bug again.

**Comment by abekkala** [comment] 2022-12-15 19:40
It seems to be on dev only, correct? not reproducible on staging/production?

**Comment by aneequeahmad** [comment] 2022-12-16 13:54
@abekkala Yes, it is dev only not reproducible on staging/production.

**Comment by abekkala** [comment] 2022-12-16 14:56
@deetergp based on [this convo](https://expensify.slack.com/archives/C01SKUP7QR0/p1671133317978389)
Can I get your thoughts here?

**Comment by deetergp** [comment] 2022-12-19 19:10
After some internal discussion, here's where were at with this:
* This only shows in dev because the logging of this kind is only shown in dev.
* This warning doesn't happen in release builds because we turn off propType checking for better performance
* If we did check types, it would warn in staging & production, but wouldn't be shown anywhere due to being sent to the [error boundary](https://github.com/Expensify/App/blob/main/src/App.js#L47)
* The warn is indicative of an issue and should probably be fixed.
(h/t to @roryabraham for filling in the gaps for me)

Now, with all that said, I'm not sure that removing the propType requirement for the `anchorPosition` is the correct solution. @aneequeahmad, can you explain why should this be optional here, or any of the other components you cross-checked?

**Comment by roryabraham** [comment] 2022-12-19 19:17
> If we did check types, it would warn in staging & production, but wouldn't be shown anywhere due to being sent to the [error boundary](https://github.com/Expensify/App/blob/main/src/App.js?rgh-link-date=2022-12-19T19%3A10%3A25Z#L47)

Minor correction – JS _errors_ would typically land the user in the error boundary and be logged in Firebase Crashlytics. JS _warnings_ would go into the void, never to be seen again (unless you were looking at JS logs for the release app using Android Studio's LogCat or something similar)

**Comment by aneequeahmad** [comment] 2022-12-19 19:41
@deetergp Yeah here is the list of `components` or `PropTypes` where `anchoPosition` is optional


- **AddPaymentMethodMenu.js**

https://github.com/Expensify/App/blob/d6ad76fbb83e3a45501dce6625520499f6195d63/src/components/AddPaymentMethodMenu.js#L15-L21

- **HeaderWithCloseButton.js**

https://github.com/Expensify/App/blob/5e297476d5ac1ed10f4151b3bbce0adb5f944d4c/src/components/HeaderWithCloseButton.js#L59-L64

- **modalPropTypes**

https://github.com/Expensify/App/blob/e7c44da13bd4b8f270868073e8d3d0c7ddcb276c/src/components/Modal/modalPropTypes.js#L51-L56

- **popoverPropTypes**

https://github.com/Expensify/App/blob/d4a1cb5029a7e713a7cd7983ae47c061d39ce308/src/components/Popover/popoverPropTypes.js#L10-L15

**Comment by deetergp** [comment] 2022-12-19 22:34
@aneequeahmad Yes, those other components have mixed requirements, but what does that mean for this component? It's being used by both `EmojiPicker.js`, where we are passing both the [vertical and horizontal positions](https://github.com/Expensify/App/blob/67198f9f654d937ffea6dc4e4d73ab8373e893a6/src/components/EmojiPicker/EmojiPicker.js#L152-L155) and in `PopoverReportActionContextMenu` where we [pass it whatever happens to be going on in `state`](https://github.com/Expensify/App/blob/d3cd179e7b975b1a8094c4ac1e0e2f09d2419855/src/pages/home/report/ContextMenu/PopoverReportActionContextMenu.js#L298). It seems to me with this component having the word `Measured` in its name, we'd want to be pretty explicit about its size. Rather than make it less specific, let's figure out why we aren't passing `horizontal` along with vertical in this situation.

**Comment by abekkala** [comment] 2022-12-20 12:55
I'm ooo now so this one will need to be re-assigned out. 

@deetergp if we've determined that we do want this to be worked on we can either leave it internal and you can apply the `Bug` label to get a BZ team member co-assigned to manage the payments and checklist.
Or, if you want it to be External, the `External` and `Bug` label can be applied to auto-create an Upwork job and also get a BZ member assigned to manage this.

**Comment by aneequeahmad** [comment] 2022-12-20 23:49
@deetergp You're right it makes sense what you said [here](https://github.com/Expensify/App/issues/11096#:~:text=It%20seems%20to%20me%20with%20this%20component%20having%20the%20word%20Measured%20in%20its%20name%2C%20we%27d%20want%20to%20be%20pretty%20explicit%20about%20its%20size.%20Rather%20than%20make%20it%20less%20specific%2C%20let%27s%20figure%20out%20why%20we%20aren%27t%20passing%20horizontal%20along%20with%20vertical%20in%20this%20situation). i'll investigate the component and let know here soon. Thank you for your comment.

**Comment by aneequeahmad** [comment] 2022-12-21 00:55
### UPDATE:

@deetergp I looked into the component `PopoverReportActionContextMenu` and found that

-  In this component `propTypes` we are omitting [anchorPosition](https://github.com/Expensify/App/blob/66a05aa4015f96f5bab59929698d517a616620d1/src/components/PopoverWithMeasuredContent.js#L15-L16)

https://github.com/Expensify/App/blob/66a05aa4015f96f5bab59929698d517a616620d1/src/components/PopoverWithMeasuredContent.js#L15-L16

-  In `popoverPropTypes` i found this comment [Anchor position is optional only because it is not relevant on mobile](PopoverReportActionContextMenu) and it was added in [commit # 798ad5b](https://github.com/Expensify/App/commit/798ad5bfcbd31defa4cfabb9e1e9b950d16cc9c7) as shown in diff image below

<img width="1393" alt="Screen Shot 2022-12-21 at 5 44 03 AM" src="https://user-images.githubusercontent.com/36359331/208794338-09ec4606-5815-488e-8876-32970accf063.png">


Also, `popoverPropTypes` has defaultProps where we are omitting `popoverPropTypes` from defaultModalProps 
 https://github.com/Expensify/App/blob/d4a1cb5029a7e713a7cd7983ae47c061d39ce308/src/components/Popover/popoverPropTypes.js#L24-L25

and the `defaultModalProps` also has optional `popoverAnchorPosition` here https://github.com/Expensify/App/blob/e7c44da13bd4b8f270868073e8d3d0c7ddcb276c/src/components/Modal/modalPropTypes.js#L50-L56 

**Conclusion:**
From investigation explained above it seems like the prop under question is optional. What's your opinion ? @deetergp

**Comment by aneequeahmad** [comment] 2022-12-31 01:39
@deetergp Any update here ?

**Comment by deetergp** [comment] 2023-01-02 19:31
No updates yet, was ooo. Will update later today.

**Comment by deetergp** [comment] 2023-01-03 02:06
@aneequeahmad Based on your investigation it does look like you're right and we can make it optional. Let's go with your proposal and thanks for the deep dive!

**Comment by aneequeahmad** [comment] 2023-01-03 02:08
@deetergp Sound's good. Let do it. Thank-you for you comment.

**Comment by deetergp** [comment] 2023-01-04 00:31
I re-applied the `External` and `Bug` labels. @aneequeahmad has a workable solution so let's go with that.

**Comment by jliexpensify** [comment] 2023-01-04 04:22
Hi @deetergp - I'm assuming that I'm taking care of hiring, not @johncschuster ?

**Comment by aneequeahmad** [comment] 2023-01-04 10:20
@aimane-chnaif Please see this comment here [Anchor position is optional only because it is not relevant on mobile](https://github.com/Expensify/App/issues/PopoverReportActionContextMenu). 

Also, `popoverPropTypes` has defaultProps where we are omitting `popoverAnchorPosition`  from defaultModalProps as this is optional and not required.

**Comment by aneequeahmad** [comment] 2023-01-04 11:14
@aimane-chnaif `nativeEvent` has this object on android `{"absoluteX": 234.32847595214844, "absoluteY": 712.0527954101562, "duration": 521, "handlerTag": 5, "numberOfPointers": 1, "oldState": 2, "returnValue": false, "state": 4, "x": 234.32847595214844, "y": 28.052824020385742}` which doesn't have `pageX` or `pageY` in it as commented `the horizontal and vertical position (relative to the screen) where the popover will display.`  


https://github.com/Expensify/App/blob/9cf07d2b81dfc0206932e1c5b38c190712564651/src/pages/home/report/ContextMenu/PopoverReportActionContextMenu.js#L46-L50

Does it make sense why it is not relevant on mobile ?

**Comment by aneequeahmad** [comment] 2023-01-04 11:28
@aimane-chnaif Why are we complexing the issue which is The prop `anchorPosition.horizontal` is marked as required in PopoverWithMeasuredContent, but its value is undefined as we already know anchor position is optional.

What's main concern for this issue is the following
>  let's figure out why we aren't passing horizontal along with vertical in this situation.

Which i explained above in the [comment](https://github.com/Expensify/App/issues/11096#issuecomment-1360616708)

**Comment by aneequeahmad** [comment] 2023-01-04 13:08
@aimane-chnaif `pageX` and `pageY` value exists for `PointerEvent` and doesn't exist for LongPress

![Screen Shot 2023-01-04 at 4 54 41 PM](https://user-images.githubusercontent.com/36359331/210550258-d4ccbaac-1074-43c8-acc3-132c57b9272c.png)

**Comment by aneequeahmad** [comment] 2023-01-04 16:04
@aimane-chnaif What are your thoughts on my comment [here](https://github.com/Expensify/App/issues/11096#issuecomment-1370808059).

The issue that i reported here is the prop is not optional and it's required. I investigated and explained in detail why these values are not needed. I feel like what you said [it makes event data consistent between native and web though actually not used](https://github.com/Expensify/App/issues/11096#:~:text=event%20data%20consistent%20between%20native%20and%20web%20though%20actually%20not%20used) is overEngineering. 

Please read this issue from first comment so that you can get idea what i'm talking about.

**Comment by deetergp** [comment] 2023-01-04 17:12
Yeah, it sounds like @Ollyws's proposal, which would make it more consistent across the platforms, is the right way to go here.

**Comment by jliexpensify** [comment] 2023-01-05 02:42
Going to unassign @johncschuster since it looks like we both got added. I'll go ahead and hire @Ollyws and @aimane-chnaif

**Comment by jliexpensify** [comment] 2023-01-05 02:45
@Ollyws can you link me your Upworks profile?

**Comment by trjExpensify** [comment] 2023-01-06 01:15
👋 @Ollyws needs to be assigned to this issue right? Is there a PR to link as well, yet?

**Comment by JmillsExpensify** [comment] 2023-01-06 01:55
@deetergp @abekkala @johncschuster @jliexpensify Pretty please make sure that your issues correctly have the `bug` label on them if we're actively looking for proposals. `Bug` was just added to this issue, so before it was not on the WAQ initiative radar, but now it is. Then given that the bug is well over 30 days old, it's immediately something that we've got to prioritize as a result.

**Comment by aneequeahmad** [comment] 2023-01-06 03:03
@aimane-chnaif, @deetergp I'm still not clear how can we add the wrong/irrelevant data just to make the data consistent  and this `pageX and pageY` property is not provided by the `react-native-gesture-handler` for LongPressGestureHandler. 

Moreover, `PageX` and `PageY` and different from `absoluteX` and `absoluteY`. Value of x, y and absoluteX and absoluteY are alike and absoluteX and absoluteY value can be used instead of x and y as written in the doc.

**Comment by aneequeahmad** [comment] 2023-01-06 03:14
Even in `react-native` doc pageX and pageY value only exist in `nativeEvent` of [Synthetic Touch Events for View responder props](https://reactnative.dev/docs/0.62/view#synthetic-touch-events:~:text=pageX%20%2D%20The%20X%20position%20of%20the%20touch,the%20touch%2C%20relative%20to%20the%20root%20element.). Also, I can't find any authentic source that says that absoluteX and absoluteY value can be given to pageX and pageY. 


The react-native doc says: Method that provides pageX and pageY value is [measure(callback)](https://reactnative.dev/docs/0.62/direct-manipulation#:~:text=The%20methods%20described%20here%20are%20available%20on%20most%20of%20the%20default%20components%20provided%20by%20React%20Native) which determines the location on screen, width, and height of the given view and returns the values via an async callback. If successful, the callback will be called with the following arguments:

- x
- y
- width
- height
- pageX
- pageY

**Comment by JmillsExpensify** [comment] 2023-01-12 05:53
> For new feature issues, Bug label should be added as well if we're actively looking for proposals?
i.e. https://github.com/Expensify/App/issues/12698 has lack of proposals maybe because of Bug label not applied.

Missed this last week, though we aren't added the `bug` label for `NewFeature` issues. Main reason is that we still favor bug fixing over features at the moment, though I'm sure there are process improvements we can still make.

**Comment by jliexpensify** [comment] 2023-01-16 00:07
Job - https://www.upwork.com/ab/applicants/1610433379500457984/job-details

Changed title to reflect payment date (huh, I thought it would update automatically?), hired @Ollyws and @aimane-chnaif and invited @aneequeahmad . Cheers!

**Comment by aneequeahmad** [comment] 2023-01-16 01:25
@jliexpensify applied thanks

**Comment by jliexpensify** [comment] 2023-01-16 23:37
Everyone's been paid, thanks!

**Comment by jliexpensify** [comment] 2023-01-17 02:47
Hi @aimane-chnaif - apologies: I'll get a new Upworks link for both you and @Ollyws for the $500.

**Comment by jliexpensify** [comment] 2023-01-17 02:57
I ran into some errors on the Upworks site doing that (not sure what's happening), so I've just rehired you on the new job - that seems to have worked.

**Comment by jliexpensify** [comment] 2023-01-17 22:01
All sorted, thanks Oliver and Aimane!

**Closed by jliexpensify** 2023-01-17 22:01 UTC
Labels: Reviewing, External, Engineering, Daily, Bug
