### ISSUE TITLE
[HOLD for payment 2024-09-23] [$250] [Workspace feeds] update copy in card name step of issue card flow

### ISSUE THREAD

**Issue by kevinksullivan** [Expensify/App#48733] opened 2024-09-06 17:35 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Slack conversation:** https://expensify.slack.com/archives/C036QM0SLJK/p1725488109420779

## Action Performed:

1. Sign up with gmail account added to Workspace feeds beta
2. Enable Expensify Card in more features
3. Complete setup using credentials from option 3 in the [SO](https://stackoverflowteams.com/c/expensify/questions/342)
4. Go through issue card flow, land on card name step

## Expected Result:
Copy should say: `Make it unique enough to tell apart from other cards. Specific use cases are even better!`

- Translation: `Hazlo lo suficientemente único para distinguirla de otras tarjetas. ¡Los casos de uso específicos son aún mejores!`

## Actual Result:

Copy is currently wrong

![image](https://github.com/user-attachments/assets/e9b02645-02c4-4192-898b-8b6684418645)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~021832428586783897931</li>
        <li>Upwork Job ID: 1832428586783897931</li>
        <li>Last Price Increase: 2024-09-07</li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @anmurali</details>

**Comment by mountiny** [comment] 2024-09-07 14:39
Sorry handling this with the team

**Comment by abhinaybathina** [comment] 2024-09-07 18:42
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
In the issue card flow, the instructions for making a unique name is not clear.

### What is the root cause of that problem?
Incorrect locales in both en and es files

### What changes do you think we should make in order to solve the problem?
We need to update the `giveItNameInstruction` locale value with the updated text

### What alternative solutions did you explore? (Optional)

**Comment by abhinaybathina** [comment] 2024-09-07 18:43
Contributor details
Your Expensify account email: abhinaybathina2@gmail.com
Upwork Profile Link: https://www.upwork.com/freelancers/~0168e425032efb76e6

**Comment by abhinaybathina** [comment] 2024-09-07 18:52
Can you please assign this job to me?

**Comment by abhinaybathina** [comment] 2024-09-07 18:57
Okay, thanks! I'll check the others

**Comment by mountiny** [comment] 2024-09-23 15:47
Updated! We fixed two things in this PR so $250 is appropriate.

**Comment by mvtglobally** [comment] 2024-10-05 03:10
Issue not reproducible during KI retests. (First week)

**Comment by anmurali** [comment] 2024-10-05 20:45
Payment Summary
- [ ] Reviewer: @allroundexperts approved $250, request via NewDot
- [ ] Contributor: @ishpaul777 [offer for $250 via Upwork](https://www.upwork.com/nx/wm/offer/104282430)

**Closed** 2024-10-09 02:57 UTC
Labels: External, Daily, Overdue, Awaiting Payment, Bug

**Comment by JmillsExpensify** [comment] 2024-10-14 21:55
$250 approved for @allroundexperts
