### ISSUE TITLE
Misspelling suggested in Composer before word is finished

### ISSUE THREAD

**Issue by thienlnam** [Expensify/App#36193] opened 2024-02-09 00:02 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.39-0
**Reproducible in staging?:** Y 
**Reproducible in production?:** N
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** @mallenexpensify 
**Slack conversation:** https://expensify.slack.com/archives/C06BDSWLDPB/p1707433054366919

## Action Performed:
Break down in numbered steps
1. In the composer, start writing out a sentence

## Expected Result:
Describe what you think should've happened
Spellchecker doesn't kick in until word is completed

## Actual Result:
Describe what actually happened
Notice that a suggested misspelling is happening while you write out a word

## Workaround:
Can the user still use Expensify without this being fixed? Have you informed them of the workaround?

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

https://github.com/Expensify/App/assets/30609178/613a56f8-e8d2-4c8b-a992-18cada7a1275

Add any screenshot/video evidence

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by thienlnam** [comment] 2024-02-09 00:03
This is probably related to https://github.com/Expensify/App/issues/36188

**Comment by kadiealexander** [comment] 2024-02-09 01:24
Closing as a dupe of https://github.com/Expensify/App/issues/36188

**Closed by kadiealexander** 2024-02-09 01:24 UTC
Labels: Daily, Bug
