### ISSUE TITLE
[SMARTSCAN] HIGH: Merchant name got modified to "none" after smartscanning

### ISSUE THREAD

**Issue by m-natarajan** [Expensify/App#33256] opened 2023-12-18 22:14 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:**
**Reproducible in staging?:** Needs reproduction
**Reproducible in production?:** Needs reproduction
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** @puneetlath 
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1702933304718039

## Action Performed:
1. Open chat
2. Add an expense by smartscan process

## Expected Result:
Merchant name should remail as in the receipt

## Actual Result:
Merchant name changed to none for some reason

## Workaround:
unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

![image](https://github.com/Expensify/App/assets/59587260/d93cff7d-f137-4f9e-b319-22788549c66a)

![image](https://github.com/Expensify/App/assets/59587260/6f37608c-5a99-4346-bac2-8edfb2361870)

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~012e7b11eb9a76e357</li>
        <li>Upwork Job ID: 1736976440493682688</li>
        <li>Last Price Increase: 2023-12-19</li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @jasperhuangg</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @jasperhuangg</details>

**Comment by kadiealexander** [comment] 2023-12-19 05:05
Nov 29 20:51 - Expense is created with a merchant value of "none", as expected because it hasn't been smartscanned ([logs](https://www.expensify.com/_devportal/tools/logSearch/#query=request_id:(%2282ddba517d356093-ORD%22)+AND+timestamp:[2023-11-29T19:51:18.460Z+TO+2023-11-29T21:51:18.460Z]&index=logs_expensify-025545))

Nov 29 20:53 - Smartscan agent correctly enters "Kaigo Steak House" ([logs](https://www.expensify.com/_devportal/tools/logSearch/#query=request_id:(%22V5HxJp%22)+AND+timestamp:[2023-11-29T19:53:10.806Z+TO+2023-11-29T21:53:10.806Z]&index=logs_expensify-025545)) 

Nov 29 21:01 - Onyx does something(?) and the merchant is registered as (none)  ([logs](https://www.expensify.com/_devportal/tools/logSearch/#query=request_id:(%2282ddc98e793878e7-EWR%22)+AND+timestamp:[2023-11-29T20:01:41.631Z+TO+2023-11-29T22:01:41.631Z]&index=logs_expensify-025545))

**Comment by kadiealexander** [comment] 2023-12-22 02:56
Noting that I'm on leave from tomorrow until Jan 8th and will check in on my return.

**Comment by jasperhuangg** [comment] 2024-01-03 04:20
I suspect that the merchant is getting cleared out when we set the category of the expense.

**Comment by jasperhuangg** [comment] 2024-01-03 05:01
It looks like we sent a request [here](https://www.expensify.com/_devportal/tools/logSearch/#query=request_id:(%22833844cbfd50e174-ORD%22)+AND+timestamp:[2023-12-10T19:34:27.901Z+TO+2023-12-10T21:34:27.901Z]&index=logs_expensify-025736) that cleared out the merchant to "(none").

**Comment by jasperhuangg** [comment] 2024-01-03 05:11
Here's what I see happening via the logs:
1. The Scan money request is created [here](https://www.expensify.com/_devportal/tools/logSearch/#sort=asc&size=10000&query=blob%3A%221576233900602363077%22%20AND%20timestamp%3A%5B2023-12-04T00%3A00%20TO%202024-01-04T23%3A59%5D)
2. 7 seconds afterwards, the category is updated [here](https://www.expensify.com/_devportal/tools/logSearch/#query=request_id:(%2283384494aa68e174-ORD%22)+AND+timestamp:[2023-12-10T19:34:19.532Z+TO+2023-12-10T21:34:19.532Z]&index=logs_expensify-025736)
3. The SmartScan job runs after, and updates the merchant to `KAIGO COFFEE ROOM` [here](https://www.expensify.com/_devportal/tools/logSearch/#query=request_id:(%228g5D4s%22)+AND+timestamp:[2023-12-10T21:21:22.659Z+TO+2023-12-10T23:21:22.659Z]&index=logs_expensify-025737)

**Comment by jasperhuangg** [comment] 2024-01-03 05:37
The expense seems to have all the expected fields when SmartScan finishes. I'm seeing that it was merged with a card transaction a few weeks afterwards, so I'm wondering if this is what caused the merchant to get cleared.

**Comment by jasperhuangg** [comment] 2024-01-03 06:03
[Here](https://www.expensify.com/_devportal/tools/logSearch/#query=request_id:(%2282de7a111dd678e7-EWR%22)+AND+timestamp:[2023-11-29T22:02:12.251Z+TO+2023-11-30T00:02:12.251Z]&index=logs_expensify-025547) we send out the updated transaction via Pusher and save it correctly into the Onyx store

**Comment by jasperhuangg** [comment] 2024-01-03 06:03
I'm not seeing any subsequent Onyx updates where the merchant is being reset to (none)

**Comment by jasperhuangg** [comment] 2024-01-03 06:05
I can't reproduce the bug either, and there's no evidence of the merchant being cleared in the DB or in Onyx 😨

**Comment by jasperhuangg** [comment] 2024-01-04 03:54
I've posted some questions/notes [here](https://expensify.slack.com/archives/C049HHMV9SM/p1704262013954569?thread_ts=1702933304.718039&cid=C049HHMV9SM)–hopefully @puneetlath can help me take a look 🙇

**Comment by kadiealexander** [comment] 2024-01-09 01:29
Not overdue, @puneetlath would love your thoughts on this! Unfortunately this example is too far back to find good logs in Logsearch anymore.

**Comment by jasperhuangg** [comment] 2024-01-17 13:22
Not overdue, was OOO and looking into this today

**Comment by jasperhuangg** [comment] 2024-01-17 13:24
It's been a while since this has happened, so either the bug was fixed or it'll happen again. The logs when this last happened happened too long ago, so I'm going to demote the priority to weekly cc @puneetlath

**Comment by puneetlath** [comment] 2024-01-17 15:59
Let's just close it and I'll reopen if I see it again. Thanks!

**Closed by puneetlath** 2024-01-17 15:59 UTC
Labels: Engineering, Weekly, Internal, Bug, SmartScan
