### ISSUE TITLE
[$500] Incorrect avatar being displayed for expense report row in LHN

### ISSUE THREAD

**Issue by m-natarajan** [Expensify/App#32416] opened 2023-12-03 15:45 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.7.0
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** @shawnborton 
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1701391697330139

## Action Performed:
1. Submit an expense on a workspace. 
2. Then look at the expense report row that appears in the LHN

## Expected Result: 
My correct avatar should show up

## Actual Result: 
A default backup avatar shows in place of my own photo

## Workaround:
unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence
![CleanShot 2023-11-30 at 19 47 15@2x](https://github.com/Expensify/App/assets/38435837/689b1354-a447-4880-b421-c9f059c378c5)

https://github.com/Expensify/App/assets/38435837/84aff5bb-a7c4-4fe5-8293-44622f76a66e

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01a355eb499fe4a8bb</li>
        <li>Upwork Job ID: 1731338946374533120</li>
        <li>Last Price Increase: 2023-12-03</li>
    </ul>
</details>

**Comment by shubham1206agra** [comment] 2023-12-03 16:47
## Proposal
### Please re-state the problem that we are trying to solve in this issue

Incorrect avatar being displayed for expense report row in LHN

### What is the root cause of that problem?

This is due to a bug in getting participants correctly.  
Line
https://github.com/Expensify/App/blob/1682be47d71b5a84c20c2396e833c0a015829252/src/components/LHNOptionsList/LHNOptionsList.js#L121

Here, it will create a list of lists instead of a list, as it didn't use the spread operator.

### What changes do you think we should make in order to solve the problem?

Add spread operator here.

```js
const participants = [...ReportUtils.getParticipantsIDs(itemFullReport), itemFullReport.ownerAccountID];
```


### What alternative solutions did you explore? (Optional)

**Comment by chiItepin** [comment] 2023-12-03 17:49
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
A default avatar is being displayed for a user on the left navbar even though the app already has its profile image stored.

### What is the root cause of that problem?

The `participants` variable in the `renderItem` callback in `LHNOptionsList.js` is creating a new array with missing participantIds

https://github.com/Expensify/App/blob/1682be47d71b5a84c20c2396e833c0a015829252/src/components/LHNOptionsList/LHNOptionsList.js#L121

### What changes do you think we should make in order to solve the problem?


Instead of creating a new array, we should provide the `ReportUtils.getParticipantsIDs` reference and even drop the `itemFullReport.ownerAccountID` property inside the `renderItem`callback,  this is because  `ReportUtils.getParticipantsIDs` already comes with the full list of participantIds including the ownerId, so there's no need to create a new array and on top of that manually set the ownerId, it would make the code less maintainable.

### Before

<img width="379" alt="Screenshot 2023-12-03 at 10 37 17" src="https://github.com/Expensify/App/assets/50275849/75916237-17f9-490a-869e-eedcd65cd89e">


### After

<img width="377" alt="Screenshot 2023-12-03 at 10 40 21" src="https://github.com/Expensify/App/assets/50275849/6fc3b039-2ced-477f-b70f-0be7d9f21a3a">


### What alternative solutions did you explore? (Optional)

**Reminder:** Please use plain English, be brief and avoid jargon. Feel free to use images, charts or pseudo-code if necessary. Do not post large multi-line diffs or write walls of text. Do not create PRs unless you have been hired for this job.

**Comment by situchan** [comment] 2023-12-03 19:19
Note: the original issue (expense **request** main avatar) happening on production now fixed on staging. This was [reported](https://expensify.slack.com/archives/C049HHMV9SM/p1701623567361639?thread_ts=1701391697.330139&cid=C049HHMV9SM) by @shawnborton 3 days ago.
The new issue (expense **report** main avatar) is not yet deployed to staging and it's just regression from https://github.com/Expensify/App/pull/32113 which was merged into main 2 days ago.

**Comment by chiItepin** [comment] 2023-12-03 19:20
Q: Have you guys considered using the `ReportUtils.getParticipantsIDs` reference instead of creating a new array?

**Comment by shubham1206agra** [comment] 2023-12-04 15:51
@mallenexpensify Can I get any compensation for the fix, as I was the one pointing towards the problem, and my solution is used in https://github.com/Expensify/App/pull/32421?
Proposal: https://github.com/Expensify/App/issues/32416#issuecomment-1837535673

**Comment by mallenexpensify** [comment] 2023-12-05 21:32
That's a good question @shubham1206agra , situations like this rarely occur so we don't have concrete documentation to point too.  Let me address internally.

**Comment by mallenexpensify** [comment] 2023-12-05 21:36
Actually... before I raise the issue internally, @fedirjh , would you agree with @shubham1206agra that their proposal above - was the one pointing towards the problem, and my solution is used in https://github.com/Expensify/App/pull/32421? ?

**Comment by mallenexpensify** [comment] 2023-12-06 18:06
Thanks @fedirjh, our standard for payments for edge cases is 25, 50 and 100% of the issue price.  I propose we compensate @shubham1206agra 50% here, do you agree @fedirjh and @shubham1206agra ?

**Comment by mallenexpensify** [comment] 2023-12-09 01:11
@shubham1206agra can you please accept the job and reply here once you have? 
https://www.upwork.com/jobs/~01a355eb499fe4a8bb

**Comment by shubham1206agra** [comment] 2023-12-09 01:46
Done

**Comment by mallenexpensify** [comment] 2023-12-11 22:05
Contributor: @shubham1206agra paid $250 via Upwork
 
I belive that's the only payment due here, right?

**Comment by mvtglobally** [comment] 2023-12-21 16:09
Issue not reproducible during KI retests. (First week)

**Comment by mvtglobally** [comment] 2023-12-31 06:11
Issue not reproducible during KI retests. (Second week)

**Closed** 2024-01-03 00:25 UTC
Labels: Reviewing, External, Weekly, Help Wanted, Bug
