### ISSUE TITLE
[HOLD for payment 2024-11-18] [$500] [Dupe detection] Tax code review step shows empty option when workspace does not have tax rate

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#47796] opened 2024-08-21 14:19 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 9.0.23-0
**Reproducible in staging?:** Y
**Reproducible in production?:**  Y
**If this was caught during regression testing, add the test name, ID and link from TestRail:** N/A
**Email or phone of affected tester (no customers):** applausetester+kh05081@applause.expensifail.com
**Issue reported by:** Applause - Internal Team

## Action Performed:
Precondition:
- Workspace A has tax rates.
- Workspace B does not have Taxes feature (disabled)
1. Go to staging.new.expensify.com
2. Go to workspace chat (workspace A)
3. Submit an expense with tax rate
4. Go to workspace chat (workspace B)
5. Submit the same expense as Step 3 but without tax rate
6. Submit another expense (any amount) to workspace chat (workspace B)
7. Open transaction thread of the expense submitted in Step 5
8. Click Review duplicates
9. Click Keep this one (any)
10. Proceed to Tax code review page

## Expected Result:
Tax code review page will not have blank option

## Actual Result:
Tax code review page shows blank option

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [x] Android: mWeb Chrome
- [x] iOS: Native
- [x] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details> 

https://github.com/user-attachments/assets/29d537cb-7059-4c95-9a27-bcda44aa8383

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01bb1c0676c6145d31</li>
        <li>Upwork Job ID: 1828505882730671209</li>
        <li>Last Price Increase: 2024-11-06</li>
<li>Automatic offers: </li>
<ul>
<li>brunovjk | Reviewer | 103811978</li>
<li>Krishna2323 | Contributor | 103811979</li>
</ul></li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @adelekennedy</details>

**Comment by lanitochka17** [comment] 2024-08-21 14:19
@adelekennedy  FYI I haven't added the External label as I wasn't 100% sure about this issue. Please take a look and add the label if you agree it's a bug and can be handled by external contributors

**Comment by adelekennedy** [comment] 2024-08-27 18:52
@brunovjk one existing proposal to review above!

**Comment by trjExpensify** [comment] 2024-08-28 00:29
Dupe detection is in #wave-control, moving this over. CC: @pecanoro @kubabutkiewicz @parasharrajat @dylanexpensify

**Comment by pecanoro** [comment] 2024-08-28 09:45
I am going to put a HOLD on this issue because I have the feeling the proposal [here](https://github.com/Expensify/App/issues/47975) will fix this.

**Comment by brunovjk** [comment] 2024-08-28 20:30
Hello @pecanoro, I tested both proposals (test branches) separately, and it seems that each one resolves its specific problem, but neither addresses the other's issue. They appear to be distinct problems with different root causes.
For the current problem, the test branch is working well, and I can no longer reproduce the issue. However, I still need to do a bit more investigation into the underlying cause. I’ll provide an update on this tomorrow morning. Thanks

**Comment by pecanoro** [comment] 2024-09-02 12:00
After reviewing the issue in depth, yeah, we can remove the HOLD in this one. @brunovjk Feel free to review the proposals!

**Comment by brunovjk** [comment] 2024-09-02 13:03
Thanks, I will finish the review soon.

**Comment by brunovjk** [comment] 2024-09-03 17:23
Apologies for the delay. @Krishna2323's [proposal](https://github.com/Expensify/App/issues/47796#issuecomment-2302529441) seems good to me. The approach of using `ONYXKEYS.REVIEW_DUPLICATES` instead of `route.params.threadReportID` to correctly fetch the transactionID is sound. Additionally, the suggestion to skip the field review step when no field options are available is logical and improves the flow.

🎀👀🎀 C+ reviewed

**Comment by pecanoro** [comment] 2024-09-04 12:46
Sounds good, assigning @Krishna2323!

**Comment by brunovjk** [comment] 2024-09-09 09:50
> Sorry for the delay 🙏🏻, I have been sick from last 3 days 🥲. Will work on this today.

Feeling better now? Let me know if I can assist in anyway

**Comment by brunovjk** [comment] 2024-10-09 11:43
[PR](https://github.com/Expensify/App/pull/48958) under review.

**Comment by brunovjk** [comment] 2024-10-16 14:16
Weekly Update: PR is still in review

**Comment by brunovjk** [comment] 2024-10-21 12:33
Same as above

**Comment by brunovjk** [comment] 2024-10-28 12:29
PR is still in review

**Comment by pecanoro** [comment] 2024-11-06 16:02
I am doubling the reward of this one since it took longer than anticipated!

**Comment by brunovjk** [comment] 2024-11-18 11:44
# BugZero Checklist:

- [x] **[Contributor]** Classify the bug:

<details>
<summary>Bug classification</summary>


Source of bug:
  - [ ] 1a. Result of the original design (eg. a case wasn't considered)
  - [x] 1b. Mistake during implementation
  - [ ] 1c. Backend bug
  - [x] 1z. Other: Additional to the issue reported here, during the PR, we introduced an improvement to skip the review page if no fields (e.g., tax codes) are enabled in the policy and extracted from different transactions. This enhancement prevents unnecessary steps when reviewing duplicates.

Where bug was reported:
  - [x] 2a. Reported on production
  - [ ] 2b. Reported on staging (deploy blocker)
  - [ ] 2c. Reported on both staging and production
  - [ ] 2d. Reported on a PR
  - [ ] 2z. Other:

Who reported the bug:
  - [ ] 3a. Expensify user
  - [ ] 3b. Expensify employee
  - [ ] 3c. Contributor
  - [ ] 3d. QA
  - [x] 3z. Other: Applause - Internal Team

</details>

- [ ] **[Contributor]** The offending PR has been commented on, pointing out the bug it caused and why, so the author and reviewers can learn from the mistake.

    Link to comment:

- [ ] **[Contributor]** If the regression was CRITICAL (e.g. interrupts a core flow) A discussion in [#expensify-open-source](https://app.slack.com/client/E047TPA624F/C01GTK53T8Q) has been started about whether any other steps should be taken (e.g. updating the PR review checklist) in order to catch this type of bug sooner.

    Link to discussion:

- [ ] **[Contributor]** If it was decided to create a regression test for the bug, please propose the [regression test](https://github.com/Expensify/App/blob/main/contributingGuides/REGRESSION_TEST_BEST_PRACTICES.md) steps using the template below to ensure the same bug will not reach production again.

- [ ] **[BugZero Assignee]** Create a GH issue for creating/updating the regression test once above steps have been agreed upon.

    Link to issue:

## Regression Test Proposal
### Precondition:
- Workspace A has tax rates, categories, and tags enabled.
- Workspace B does not have the taxes, categories, and tags features enabled.

### Test:
1. Open the chat for Workspace A.
2. Submit an expense in Workspace A with a tax rate, category, and tag (use the same amount and merchant).
3. Submit another expense in Workspace A with all fields left empty (defaults).
4. Open the chat for Workspace B.
5. Submit an expense in Workspace B with the same amount and merchant as the previous entries.
6. Open the transaction thread for the expense submitted in Workspace B.
7. Click "Review Duplicates."
8. Choose "Keep this one" for the first transaction and verify that the tax, tag, and category review step is skipped since Workspace B does not have these features enabled.
9. Return to the initial duplicate review step (where you select the transaction to keep).
10. Choose "Keep this one" for the second transaction and verify that the tax, tag, and category review step is not skipped, as Workspace A has these features enabled.
11. Repeat steps 9 and 10 for the third transaction, ensuring the tax, tag, and category review step is not skipped since it belongs to Workspace A.
12. Return to the chat for Workspace A and open any transaction thread for an expense submitted there.
13. Click "Review Duplicates."
14. Choose "Keep this one" for the first transaction and verify that the tax, tag, and category review step is not skipped, as Workspace A has these features enabled.
15. Return to the initial duplicate review step.
16. Choose "Keep this one" for the second transaction and verify that the tax, tag, and category review step is not skipped since Workspace A has these features enabled.
17. Return to the initial duplicate review step again.
18. Choose "Keep this one" for the third transaction and confirm that the tax, tag, and category review step is skipped, as this transaction belongs to Workspace B, which does not have these features enabled.

Do we agree 👍 or 👎

**Comment by adelekennedy** [comment] 2024-11-18 17:03
@pecanoro the test steps above make sense to me - any additional thoughts?

**Comment by adelekennedy** [comment] 2024-11-18 17:05
Payouts due:

- [ ] Contributor: $500 @Krishna2323 Upwork
- [ ] Reviewer: $500 @brunovjk Upwork

**Closed** 2024-11-23 02:29 UTC
Labels: External, Daily, Overdue, Awaiting Payment, Bug
