### ISSUE TITLE
[$250] Taxes – App freezes for a moment when Enable Tax in the workspace settings second time

### ISSUE THREAD

**Issue by kavimuru** [Expensify/App#45787] opened 2024-07-19 15:30 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** v9.0.9-1
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:** https://expensify.testrail.io/index.php?/tests/view/4735501
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** Applause internal team
**Slack conversation:**

## Action Performed:
1. Go to https://staging.new.expensify.com/

2. Log in with the same account in NewDot and OldDot
3. In NewDot create a WS
4. Enable Tax in the workspace
5. In OldDot refresh the page and Disable Tax in the workspace
6. Verify that the feature is OFF in NewDot
7. In OldDot Enable Tax in the workspace
8. Verify that the feature is ON in NewDot. Missing Taxes in the workspace editor.
9. Click on some another features

## Expected Result:
Taxes appears in the LHN and app is not frozen

## Actual Result:
Taxes appears in the LHN after few moments and app frozen for a moment

## Workaround:
unknown
## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

https://github.com/user-attachments/assets/28ea8b29-1589-4cd5-9477-30270f44bb90

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~0166ca43ee94d71420</li>
        <li>Upwork Job ID: 1815392583930838349</li>
        <li>Last Price Increase: 2024-07-29</li>
    </ul>
</details>

**Comment by kavimuru** [comment] 2024-07-19 15:32
@joekaufmanexpensify FYI I haven't added the External label as I wasn't 100% sure about this issue. Please take a look and add the label if you agree it's a bug and can be handled by external contributors.

**Comment by kavimuru** [comment] 2024-07-19 15:33
We think this bug might be related to #wave-collect - Release 1

**Comment by joekaufmanexpensify** [comment] 2024-07-19 20:08
I can reproduce this. However, this is a pretty niche bug. It's hard to imagine someone doing this exact set of steps. Further, refreshing the page solves the issue. So doesn't feel super important to me to prioritize. 

https://github.com/user-attachments/assets/b40bb0a8-4525-4264-b52a-adf42ed7c706

**Comment by joekaufmanexpensify** [comment] 2024-07-19 20:08
Going to check in Slack whether we want to be prioritizing these types of cross platform bugs.

**Comment by joekaufmanexpensify** [comment] 2024-07-19 20:13
[Discussing ](https://expensify.slack.com/archives/C036QM0SLJK/p1721419999270439)

**Comment by joekaufmanexpensify** [comment] 2024-07-22 14:10
Same

**Comment by joekaufmanexpensify** [comment] 2024-07-22 14:25
This is a pretty niche bug. We're interested to see if this turns out to be a very quick/simple fix. If it is, then we're interested in doing it. If it seems like it's more involved, then we may just close. Let us know your thoughts!

**Comment by joekaufmanexpensify** [comment] 2024-07-23 13:21
Pending proposals

**Comment by joekaufmanexpensify** [comment] 2024-07-24 13:36
Same

**Comment by joekaufmanexpensify** [comment] 2024-07-25 13:36
Same.

**Comment by joekaufmanexpensify** [comment] 2024-07-26 13:37
Still waiting for proposals, will bump in Slack soon if none

**Comment by joekaufmanexpensify** [comment] 2024-07-29 15:43
[Bumped in slack ](https://expensify.slack.com/archives/C01GTK53T8Q/p1722267787997339)

**Comment by joekaufmanexpensify** [comment] 2024-07-29 16:04
Not overdue

**Comment by joekaufmanexpensify** [comment] 2024-07-31 13:03
Same

**Comment by joekaufmanexpensify** [comment] 2024-08-01 13:40
Going to bump this again in slack

**Comment by joekaufmanexpensify** [comment] 2024-08-02 13:27
[Highlighted again in Slack ](https://expensify.slack.com/archives/C01GTK53T8Q/p1722605233486869)

**Comment by jacobkim9881** [comment] 2024-08-03 05:49
Is it reproducible? Not reproducible on my end.

**Comment by joekaufmanexpensify** [comment] 2024-08-05 13:24
will check again

**Comment by joekaufmanexpensify** [comment] 2024-08-05 14:35
Hm, I can still reproduce it a bit, but the behavior is much less bad now. A few weeks ago, the app actually froze and you had to reload to fix it. Now it is freezing for a second while the taxes row is added back to the workspace editor, and then is fine. 

Given this was already a very niche bug, the behavior is much less bad than before, and we haven't gotten any bites in 2 weeks, going to close this one for now. Let me know if anyone disagrees!

**Closed by joekaufmanexpensify** 2024-08-05 14:35 UTC
Labels: External, Daily, Help Wanted, Bug
