### ISSUE TITLE
[C+ Checklist Needs Completion] [$500] App triggers mention results after '!' and allows to select value but after sending, displays the email as link

### ISSUE THREAD

**Issue by kavimuru** [Expensify/App#24226] opened 2023-08-07 17:55 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Open the app
2. Open any report
3. Send any text and end with exclamation point and write @ after it to trigger mention results eg: 'Hello!@'
4. Select any value and send the message
5. Observe that in message, it is displayed as email link even though while sending, app displayed it as mention and allowed us to select any value
## Expected Result:
App should not trigger mention results if text has no space before @
## Actual Result:
App triggers mention results right after '!' (exclaimation) and after selecting and sending message, displays the email as email link
## Workaround:
Can the user still use Expensify without this being fixed? Have you informed them of the workaround?

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android / native
- [x] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [x] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 1.3.50.3
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/43996225/a706ccac-ce52-4722-a190-4c9ffd01935e

https://github.com/Expensify/App/assets/43996225/638350b5-e122-489f-a834-bc6409604a4c

**Expensify/Expensify Issue URL:**
**Issue reported by:** @dhanashree-sawant
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1690906004615859

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~013a7e78f93955508d</li>
        <li>Upwork Job ID: 1701232379675463680</li>
        <li>Last Price Increase: 2023-09-18</li>
<li>Automatic offers: </li>
<ul>
<li>akamefi202 | Contributor | 26812390</li>
<li>dhanashree-sawant | Reporter | 26812392</li>
</ul></li>
    </ul>
</details>

**Comment by greg-schroeder** [comment] 2023-08-08 05:35
I don't know about this as a "bug" tbh

**Comment by greg-schroeder** [comment] 2023-08-08 05:36
Actually, I believe this will be fixed by https://github.com/Expensify/App/issues/17387 so perhaps we hold for that

**Comment by greg-schroeder** [comment] 2023-08-21 17:43
Holding

**Comment by greg-schroeder** [comment] 2023-08-24 02:55
""

**Comment by greg-schroeder** [comment] 2023-08-29 11:08
""

**Comment by dhanashree-sawant** [comment] 2023-09-02 16:39
Hi @greg-schroeder, hold issue is deployed to live and following issue is still reproducible on latest staging.

**Comment by greg-schroeder** [comment] 2023-09-11 13:52
Okay, removing the hold

**Comment by greg-schroeder** [comment] 2023-09-14 14:42
Awaiting proposals

**Comment by akamefi202** [comment] 2023-09-14 14:54
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
App triggers mention results after '!' and allows to select value but after sending, displays the email as link.

### What is the root cause of that problem?
https://github.com/Expensify/App/blob/95c9e4743f44ca42ece2c6ac56259b911d5feafc/src/pages/home/report/ReportActionCompose/SuggestionMention.js#L200-L207

This is happening because, the app splits text by special characters & space before checking if the prefix is `@`.
`!` is a special character which is included in `CONST.REGEX.SPECIAL_CHAR_OR_EMOJI` regex.
So if the user writes `@` after `!`, it is recognized as the prefix of new word and it triggers mentions.

### What changes do you think we should make in order to solve the problem?
We need to split text by `CONST.REGEX.SPACE_OR_EMOJI` regex instead.

### What alternative solutions did you explore? (Optional)
N/A

**Comment by greg-schroeder** [comment] 2023-09-18 10:48
proposal ready for review @thesahindia!

**Comment by akamefi202** [comment] 2023-09-22 08:51
Thank you. I accepted the offer and I will create a PR very soon.

**Comment by dhanashree-sawant** [comment] 2023-09-22 09:47
Hi @puneetlath, the following issue was raised on 7th August but melvin bot has provided me with 50$ offer, can you have a look once you are available?

**Comment by puneetlath** [comment] 2023-09-24 04:36
@greg-schroeder is the BZ on this one, so I'll let him handle that.

**Comment by greg-schroeder** [comment] 2023-09-25 07:03
Looking!

**Comment by dhanashree-sawant** [comment] 2023-09-25 07:08
Thanks for updating the offer @puneetlath, I have accepted the offer.

**Comment by greg-schroeder** [comment] 2023-09-25 07:09
Hmm. This issue was reported prior to the change in payment scale, so I've modified the reporting offer out of fairness. With that said, the entire implementation and review flow took place after the change, so that will remain in place.

**Comment by Christinadobrzyn** [comment] 2023-10-03 23:57
Hi there, can we check to see if this is a regression? https://github.com/Expensify/App/issues/28753#issuecomment-1745887800

**Comment by akamefi202** [comment] 2023-10-09 09:23
@puneetlath @greg-schroeder @thesahindia 
Can we complete this issue if there isn't any other problem?
I think https://github.com/Expensify/App/issues/28753 is not bug after all so this issue is not a regression.

**Comment by akamefi202** [comment] 2023-10-12 05:31
bump @greg-schroeder

**Comment by greg-schroeder** [comment] 2023-10-12 16:13
Payments made

**Closed** 2023-10-16 14:43 UTC
Labels: External, Daily, Awaiting Payment, Bug

**Comment by akamefi202** [comment] 2023-10-16 15:04
@greg-schroeder @thesahindia Could you plz pay the bonus and finish the contract on Upwork?

**Comment by greg-schroeder** [comment] 2023-10-16 19:56
this is done

**Comment by JmillsExpensify** [comment] 2023-10-25 17:11
$750 payment approved for @thesahindia based on [this comment](https://github.com/Expensify/App/issues/24226#issuecomment-1759938260).
