### ISSUE TITLE
[HOLD for payment 2024-12-03] [Search v1.2] Invoice preview still shows "User owes x" after the invoice is paid

### ISSUE THREAD

**Issue by IuliiaHerets** [Expensify/App#52367] opened 2024-11-12 10:24 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 9.0.60-0
**Reproducible in staging?:** Y
**Reproducible in production?:**  N
**Email or phone of affected tester (no customers):** applausetester+kh011102@applause.expensifail.com
**Issue reported by:** Applause Internal Team

## Action Performed:
Bug 1
1. Go to staging.new.expensify.com
2. [User A] Send an invoice to User B.
3. [User B] Go to invoice chat.
4. [User B] Pay the invoice from the main chat (not invoice report).

Bug 2
1. Go to staging.new.expensify.com
2. Open DM with User B.
3. Click + > Pay.
4. Enter amount and pay the user.

## Expected Result:
Bug 1
- When it shows "Payment complete" animation, the preview will change to "User paid" and it will be accompanied by a green checkmark.
- After the payment is complete, the expense preview will show "User paid x" for both the sender and receiver.

Bug 2
- After the payment is complete, the expense preview will show "User paid x".

## Actual Result:
Bug 1
- When it shows "Payment complete" animation, the preview still shows "User owes" instead of "User paid" and there is no green checkmark.
- After the payment is complete, the expense preview shows "User owes x" for both the sender and receiver, while the LHN preview shows "User paid x".

Bug 2
- After the payment is complete, the expense preview shows "User paid x", then reverts to "User owes x".

## Workaround:
Unknown

## Platforms:

- [x] Android: Standalone
- [x] Android: HybridApp
- [x] Android: mWeb Chrome
- [ ] iOS: Standalone
- [ ] iOS: HybridApp
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos
  
https://github.com/user-attachments/assets/1aa9ccd8-093e-4ead-b468-d8e06ba24de6

Uploading Bug6662173_1731394644956!bug_1.mp4…

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Issue Owner</summary>Current Issue Owner: @luacmartins</details>

**Comment by grgia** [comment] 2024-11-12 10:28
@IuliiaHerets WDYM  by  `N/A - new feature, doesn't exist in prod` - was this found via PR QA or regression testing?

**Comment by IuliiaHerets** [comment] 2024-11-12 10:31
@grgia Sorry, added `N/A - new feature, doesn't exist in prod` by mistake. Not repro in prod. Issue was found by exploratory

**Comment by grgia** [comment] 2024-11-12 10:56
This looks like a missing onyx update issue

**Comment by grgia** [comment] 2024-11-12 12:43
Caused by https://github.com/Expensify/App/pull/51445

**Comment by garrettmknight** [comment] 2024-11-12 17:22
@grgia I'm not sure this _needs_ to be a blocker since it's a feature we aren't promoting and no one's using at the moment, but I'll let you remove that if you agree.

**Comment by francoisl** [comment] 2024-11-12 20:52
I can't repro on 9.0.60-2


<table>
<tr>
<td><video src="https://github.com/user-attachments/assets/e679614d-2fdb-4db7-a27e-7dbe6494afaa" />
<td><video src="https://github.com/user-attachments/assets/2844c878-58dd-44ae-8dd7-818b778275e2" />

Also agree it's not breaking anything major – going to demote for now, maybe we can retest and confirm if it's fixed now.

**Comment by luacmartins** [comment] 2024-11-12 22:04
>Caused by https://github.com/Expensify/App/pull/51445

@grgia can you elaborate on what from that PR caused this issue please?

**Comment by luacmartins** [comment] 2024-11-13 19:37
Cool, I'll assign it to me so I can work on a fix on v2 of my PR

**Comment by luacmartins** [comment] 2024-11-13 20:21
@garrettmknight I'll unassign you from this issue since it's resolved. I'm keeping it open to track the fix in the v2 of my PR.

**Comment by luacmartins** [comment] 2024-11-13 23:41
Lol the issue happens because sometimes the reportID is passed as a number and not a string. I'm pretty sure that might cause other issues since reportIDs can be larger than the 53bit allowed by JS so we'd truncate reportIDs and this might lead to other errors.

**Comment by luacmartins** [comment] 2024-11-14 02:02
PR up

**Comment by luacmartins** [comment] 2024-11-27 22:54
This is done

**Closed by luacmartins** 2024-11-27 22:54 UTC
Labels: Engineering, Weekly, Awaiting Payment, Bug
