### ISSUE TITLE
[HOLD for payment 2024-06-20] [HOLD for payment 2024-06-18] [$250] IOU-Distance unit isn't updated immediately if changed previously while offline

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#41527] opened 2024-05-02 19:12 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.70-0
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**If this was caught during regression testing, add the test name, ID and link from TestRail:** https://expensify.testrail.io/index.php?/tests/view/4536140
**Issue reported by:** Applause - Internal Team

## Action Performed:
Prerequisites: - Collect WS with enabled Distance rates
- Previously created Distance expense (Because we need waypoints while offline)
1. Navigate to Workspace > Distance Rates
2. Click on Settings
3. Go Offline
4. Change the distance unit and the default category (For example change them to Kilometers and Travel)
5. Navigate to the workspace chat
6. Start a distance expense creation, enter Start,Stop waypoints and click Next
7. Verify the category selected is correctly displayed in the expense creation
8. Verify the unit is displayed as Pending
9. Go Online
10. Verify the new distance unit is not updated (still previous one)

## Expected Result:
The distance unit which is changed while offline is updated after getting online

## Actual Result:
The distance unit is still the previous one, for example miles instead of kilometers which was changed while offline

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [x] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details> 

https://github.com/Expensify/App/assets/78819774/55c1870f-d291-489e-ba31-d9b52f3ba271

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~010102a7d212d9a75c</li>
        <li>Upwork Job ID: 1787921613462294528</li>
        <li>Last Price Increase: 2024-05-14</li>
<li>Automatic offers: </li>
<ul>
<li>akinwale | Reviewer | 0</li>
<li>nkdengineer | Contributor | 0</li>
</ul></li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @muttmuure</details>

**Comment by lanitochka17** [comment] 2024-05-02 19:13
@muttmuure  FYI I haven't added the External label as I wasn't 100% sure about this issue. Please take a look and add the label if you agree it's a bug and can be handled by external contributors

**Comment by lanitochka17** [comment] 2024-05-02 19:13
We think that this bug might be related to #vip-vsp.

**Comment by nkdengineer** [comment] 2024-05-03 09:34
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
The distance unit is still the previous one, for example miles instead of kilometers which was changed while offline

### What is the root cause of that problem?
The `openDraftWorkspaceRequest` API is called before `SetPolicyDistanceRatesUnit`. So the old unit is returned by back-end before the newest is updated.

We already have the logic here to wait all write requests has finished before calling the read API but it doesn't work as expected.

https://github.com/Expensify/App/blob/cb39a546bef3e55315af1b43fd464e36727fcf36/src/libs/API/index.ts#L166

The reason is `isReadyPromise` is resolved before we offline 

https://github.com/Expensify/App/blob/cb39a546bef3e55315af1b43fd464e36727fcf36/src/libs/Network/SequentialQueue.ts#L195

and when a new write request is added, we do nothing if offline. So the read API is called immediately.

https://github.com/Expensify/App/blob/cb39a546bef3e55315af1b43fd464e36727fcf36/src/libs/Network/SequentialQueue.ts#L171
### What changes do you think we should make in order to solve the problem?
We should reset `isReadyPromise` if we're offline when we push a write request.

```
if (NetworkStore.isOffline()) {
    isReadyPromise = new Promise((resolve) => {
        resolveIsReadyPromise = resolve;
    });
    return;
}
```

https://github.com/Expensify/App/blob/cb39a546bef3e55315af1b43fd464e36727fcf36/src/libs/Network/SequentialQueue.ts#L171

### What alternative solutions did you explore? (Optional)
If the workspace has already added the custom unit, I think we can prevent calling `OpenDraftWorkspaceRequest` API here

https://github.com/Expensify/App/blob/cb39a546bef3e55315af1b43fd464e36727fcf36/src/pages/iou/request/step/IOURequestStepConfirmation.tsx#L143

**Comment by muttmuure** [comment] 2024-05-08 07:53
@akinwale some proposals to take a look at

**Comment by muttmuure** [comment] 2024-05-15 07:33
@akinwale some proposals above!

**Comment by akinwale** [comment] 2024-05-16 12:53
I'll review proposals today.

**Comment by akinwale** [comment] 2024-05-20 08:48
After reviewing the proposals, @nkdengineer's [solution](https://github.com/Expensify/App/issues/41527#issuecomment-2092648458) is a cleaner approach to solving the issue.

🎀👀🎀 C+ reviewed.

**Comment by mvtglobally** [comment] 2024-05-22 04:40
Issue not reproducible during KI retests. (First week)

**Comment by nkdengineer** [comment] 2024-05-22 08:38
@mvtglobally i still reproduce this issue

https://github.com/Expensify/App/assets/161821005/00b9086e-ea6a-4936-a4e7-5abc73009d1f

**Comment by nkdengineer** [comment] 2024-05-22 08:54
@akinwale this [PR](https://github.com/Expensify/App/pull/42409) is ready for preview

**Comment by carlosmiceli** [comment] 2024-05-28 20:14
@akinwale @muttmuure trying to understand/learn, is there anything left to do here? What's the status of this and what's needed to close this issue?

**Comment by akinwale** [comment] 2024-06-11 05:49
> @akinwale @muttmuure trying to understand/learn, is there anything left to do here? What's the status of this and what's needed to close this issue?

@carlosmiceli Just saw this message. After the PR is merged, we wait for deployment to production, during which the 7-day regression period starts. If no regression occurs, then payment can be issued and then the BZ checklist can be completed afterwards.

**Comment by akinwale** [comment] 2024-06-19 02:17
> **BugZero Checklist:** The PR fixing this issue has been merged! The following checklist ([instructions](https://stackoverflow.com/c/expensify/questions/14574)) will need to be completed before the issue can be closed:
> 
> * [x]  [@akinwale] The PR that introduced the bug has been identified. Link to the PR:
> * [x]  [@akinwale] The offending PR has been commented on, pointing out the bug it caused and why, so the author and reviewers can learn from the mistake. Link to comment:
> * [x]  [@akinwale] A discussion in #expensify-bugs has been started about whether any other steps should be taken (e.g. updating the PR review checklist) in order to catch this type of bug sooner. Link to discussion:

Not a regression.

> * [x]  [@akinwale] Determine if we should create a regression test for this bug.
> * [x]  [@akinwale] If we decide to create a regression test for the bug, please propose the [regression test](https://github.com/Expensify/App/blob/main/contributingGuides/REGRESSION_TEST_BEST_PRACTICES.md) steps to ensure the same bug will not reach production again.

**Regression Test Steps**
_Prerequisites_
* Collect workspace with Distance rates enabled
* Previously created distance expense in the session (to allow the ability to select waypoints while offline)

1. Launch the Expensify app
2. Navigate to Workspace > (select workspace) > Distance Rates.
3. Click on Settings.
4. Go offline
5. Change the distance unit and the default category.
6. Navigate to the workspace chat.
7. Create a new distance expense.
8. Select the Start and Stop waypoints and click Next.
9. Verify the category selected is correctly displayed in the expense creation.
10. Verify the unit is displayed as Pending.
11. Go online.
12. Verify that the distance unit is updated using the value from the workspace settings.

Do we agree 👍 or 👎?

**Comment by akinwale** [comment] 2024-06-19 02:19
@muttmuure The PR was originally deployed to production on [2024-06-11](https://github.com/Expensify/App/pull/42409#issuecomment-2161772527), so the correct payment due date is 2024-06-18.

**Comment by carlosmiceli** [comment] 2024-06-21 15:15
Not overdue.

**Comment by carlosmiceli** [comment] 2024-06-21 18:08
Melvin, what the hell.

**Comment by carlosmiceli** [comment] 2024-06-24 17:39
@muttmuure Matt, why can't we remove the overdue label in this one? Just curious.

**Comment by muttmuure** [comment] 2024-06-26 11:15
I'm starred so I'm the one who removes it. I think this is already paid out, I just need to ask applause to create a regression test

**Comment by muttmuure** [comment] 2024-06-26 11:15
Yeah everyone is paid

**Closed** 2024-06-26 11:16 UTC
Labels: External, Daily, Awaiting Payment, Bug
