### ISSUE TITLE
[HOLD for payment 2023-10-27] [$250] Dev: Emojipicker in Set status page has a text cursor instead of pointer

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#29097] opened 2023-10-09 15:04 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** Dev 1.3.79.3
**Reproducible in staging?:** n
**Reproducible in production?:** n
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** @ishpaul777
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1696763872801869

## Action Performed:
Pre condition: Make sure you have Beta for status feature
1. Navigate to Profile -> Status -> Set Status
2. Hover on Emoji Picker Drop Down Button

## Expected Result:
 Emojipicker Dropdown button has a pointer cursor

## Actual Result:
 Emojipicker Dropdown button has a text cursor.

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos
<details>
<summary>Android: Native</summary>

</details> n/a

<details>
<summary>Android: mWeb Chrome</summary>

</details> n/a

<details>
<summary>iOS: Native</summary>

</details> n/a

<details>
<summary>iOS: mWeb Safari</summary>

</details> n/a

<details>
<summary>MacOS: Chrome / Safari</summary>

 

https://github.com/Expensify/App/assets/93399543/7fc3a6cd-3a36-4abe-88d9-0906b71be4f6

</details>

<details>
<summary>MacOS: Desktop</summary>

 

https://github.com/Expensify/App/assets/93399543/8a9abace-b631-40d0-894e-760c635becb0

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~018aae903757e06f35</li>
        <li>Upwork Job ID: 1711460039105232896</li>
        <li>Last Price Increase: 2023-10-10</li>
<li>Automatic offers: </li>
<ul>
<li>ishpaul777 | Contributor | 27225708</li>
<li>ishpaul777 | Reporter | 27225711</li>
</ul></li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @JmillsExpensify</details>

**Comment by kbecciv** [comment] 2023-10-09 15:05
Proposal by: @ishpaul777
Slack conversation: https://expensify.slack.com/archives/C049HHMV9SM/p1696763872801869

## Proposal 
### Problem
Emojipicker in Set status page has a "text" cursor instead of pointer

### Root Cause 
We are setting the accessibilityRole="text" for PressableWithoutFeedback used for the dropdown which result in curesor style as "text" I have aasked clarifying question why we used "text" instead of "button" (here)[https://github.com/Expensify/App/pull/23267]

### Changes 
We can change  accessibilityRole=CONST.ACCESSIBILITY_ROLE.BUTTON or expilicty add cursor style to cursorPointer and cursorDisabled when disabled














Reply…
Also send to expensify-bugs

**Comment by vadymbokatov** [comment] 2023-10-09 19:31
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
Emojipicker in Set status page has a "text" cursor instead of pointer
### What is the root cause of that problem?
https://github.com/Expensify/App/blob/4a24fd6e518b2fbccaf8dcd49ee6d77b07a489d2/src/components/EmojiPicker/EmojiPickerButtonDropdown.js#L40-L48
accessibilityRole="text" in the PressableWithoutFeedback is the root cause of this issue.
### What changes do you think we should make in order to solve the problem?
we can add cursor: 'pointer' to style of PressableWithoutFeedback or change accessibilityRole to button.

**Comment by cead22** [comment] 2023-10-10 00:30
Simple bug, trivial fix, so I decreased the bounty

**Comment by stitesExpensify** [comment] 2023-11-02 22:37
Hey @JmillsExpensify can we pay @ishpaul777 and @allroundexperts please? This PR has been merged for a while

**Comment by JmillsExpensify** [comment] 2023-11-08 12:32
@allroundexperts do you mind filling out the BZ checklist for payment? In the meantime, I'll pay out the contributor based on the following payment summary:

 - Issue reporter: @ishpaul777 $50
 - Contributor: @ishpaul777 $750 (incl. urgency bonus)
 - Contributor+: @allroundexperts $750 (incl. urgency bonus)

**Comment by JmillsExpensify** [comment] 2023-11-08 12:34
Whoops updating the prices per [this comment](https://github.com/Expensify/App/issues/29097#issuecomment-1754113181).

**Comment by JmillsExpensify** [comment] 2023-11-08 12:36
Contributor paid out. Will circle back on C+.

**Comment by JmillsExpensify** [comment] 2023-11-15 16:04
@allroundexperts Looks like this one lacks a checklist, though at that point I can approve payment and we can close this one out.

**Comment by JmillsExpensify** [comment] 2023-11-24 17:36
Still awaiting a checklist.

**Comment by JmillsExpensify** [comment] 2023-11-24 21:04
Actually, going to go ahead and close this one out. I can verify checklist ahead of approving payment via NewDot.

**Closed by JmillsExpensify** 2023-11-24 21:04 UTC
Labels: External, Daily, Awaiting Payment, Bug

**Comment by allroundexperts** [comment] 2023-11-28 09:48
## Checklist
1. https://github.com/Expensify/App/pull/23267
2. https://github.com/Expensify/App/pull/23267/files#r1407485604
3. N/A
4. I think this is really minor and a regression test is not needed. However, if there's disagreement, then the steps given in the OP seems to be clear enough.

**Comment by JmillsExpensify** [comment] 2023-11-28 15:31
Thanks @allroundexperts. $375 payment approved based on [this comment](https://github.com/Expensify/App/issues/29097#issuecomment-1801799639).
