### ISSUE TITLE
mWeb - After sending an invoice to a new user, it gets changed to some other user after a few minutes

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#42115] opened 2024-05-13 21:38 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.73.1
**Reproducible in staging?:** y
**Reproducible in production?:** n
**Issue reported by:** Applause - Internal Team

## Action Performed:
Pre-condition: Login with gmail account
1. Go to https://staging.new.expensify.com/home
2. Tap fab -- send invoice
3. Enter an amount and tap continue
4. Select a new user
5. Tap send invoice
6. Wait for few seconds, when header changes to hidden, tap on invited contact
7. Tap message user
8. Note email not found error
9. Navigate back to send invoice page and pin it
10. Navigate to LHN and open the report after few seconds
11. Open the report and wait few seconds

## Expected Result:
After sending an invoice to a new user, it doesn't get changed to some other user after a few minutes

## Actual Result:
After sending an invoice to a new user, it gets changed to some other user after a few minutes

## Workaround:
n/a

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [x] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [ ] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

https://github.com/Expensify/App/assets/93399543/1538b8fc-3eab-4170-9719-82d2a77770a1

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by kbecciv** [comment] 2024-05-13 21:39
We think that this bug might be related to #wave-collect - Release 1

**Comment by yuwenmemon** [comment] 2024-05-14 02:44
I can't reproduce this and the _other_ errors that are described in the pre-requisite steps are reproducible in prod: 
![Screenshot 2024-05-13 at 7 44 05 PM](https://github.com/Expensify/App/assets/4741899/de0ed3a3-e6e3-4f1d-8ee1-b45d2913cf3d)

Removing the label

**Comment by yuwenmemon** [comment] 2024-05-14 02:45
@cristipaval Do you know about the error here?

**Comment by yuwenmemon** [comment] 2024-05-20 18:39
@cristipaval quick bump on the above!

**Comment by yuwenmemon** [comment] 2024-05-20 20:25
Sweeeeet! No worries at all. Closing this out!

**Closed by yuwenmemon** 2024-05-20 20:25 UTC
Labels: Engineering, Daily, Improvement
