### ISSUE TITLE
 Incorrect empty state for some Search page filters

### ISSUE THREAD

**Issue by m-natarajan** [Expensify/App#51420] opened 2024-10-24 14:17 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 9.0.53-1
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**If this was caught on HybridApp, is this reproducible on New Expensify Standalone?:**
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** @shawnborton 
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1729753553105859

## Action Performed:
1. Go to staging.new.expensify.com
2. Click Search > Expenses > Drafts or any other filter/sort options
## Expected Result:
Show the generic one that says "Nothing to show" if no expenses to showup
## Actual Result:
Empty state that says "You haven't created any expenses yet" even If user have created expenses
## Workaround:
Unknown
## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Standalone
- [ ] Android: HybridApp
- [ ] Android: mWeb Chrome
- [ ] iOS: Standalone
- [ ] iOS: HybridApp
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

<details>
  <summary>Add any screenshot/video evidence</summary>

  
![CleanShot 2024-10-24 at 09 04 44@2x](https://github.com/user-attachments/assets/e19bb66d-a4ec-4e83-98c4-08aaf991d8d4)

![Full Screen #17](https://github.com/user-attachments/assets/3254742c-bc56-41b4-a615-ccb870cffeda)

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by FitseTLT** [comment] 2024-10-24 14:55
@shawnborton  This is a dupe of https://github.com/Expensify/App/issues/51168#issuecomment-2432535689. In fact, the reviewer is waiting for your suggestions, in terms of design.

**Comment by shawnborton** [comment] 2024-10-24 15:45
Hmm this does feel quite similar to the linked issue. Perhaps we can combine them and just focus on the issue that was created first.

**Comment by FitseTLT** [comment] 2024-10-24 15:48
> Hmm this does feel quite similar to the linked issue. Perhaps we can combine them and just focus on the issue that was created first.

Yes we can close this one 👍

**Comment by isabelastisser** [comment] 2024-10-25 14:54
Closing! https://github.com/Expensify/App/issues/51168#issuecomment-2438039548

**Closed by isabelastisser** 2024-10-25 14:54 UTC
Labels: Daily, Bug
