### ISSUE TITLE
[$250] Room - "Auth AddComment returned an error" shows up after sending Bye in public room thread

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#49794] opened 2024-09-26 14:19 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 9.0.40-1
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**If this was caught during regression testing, add the test name, ID and link from TestRail:** N/A
**Email or phone of affected tester (no customers):** applausetester+kh230901@applause.expensifail.com
**Issue reported by:** Applause - Internal Team

## Action Performed:
1. Go to staging.new.expensify.com
2. Go to a public room
3. Send a message
4. Open the message in thread
5. Send Bye in the thread

## Expected Result:
No error will show up

## Actual Result:
"Auth AddComment returned an error" shows up after sending Bye in public room thread

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [x] Android: mWeb Chrome
- [x] iOS: Native
- [x] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details> 

https://github.com/user-attachments/assets/b57ad8a8-9b35-4cc4-9c6a-28386ddb128d

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~021839402753570184613</li>
        <li>Upwork Job ID: 1839402753570184613</li>
        <li>Last Price Increase: 2024-09-26</li>
    </ul>
</details>

**Comment by sakluger** [comment] 2024-09-26 20:33
Given this is an auth error, I have a feeling this will require a BE fix. I added the external label for now just to be safe - if we're able to fix this on the FE, feel free to submit proposals!

**Comment by jestinjoshi** [comment] 2024-09-26 22:58
@sakluger I looked into this issue and it will require a BE fix. It's not something that can be resolved from the FE

**Comment by brunovjk** [comment] 2024-09-27 11:49
I agree, it seems to be related to the server responses:

https://github.com/user-attachments/assets/32976623-325b-435a-a88e-f532b6506578

**Comment by sakluger** [comment] 2024-09-27 16:28
Thanks - I've set to `Internal` and am demoting to weekly since it's not really tied to any waves right now.

**Comment by brunovjk** [comment] 2024-10-10 19:37
I can still reproduce it, now with the words _"Good bye"_ and _"Adios"_ 😂

https://github.com/user-attachments/assets/d3191047-0631-42fb-a1b4-28e97a261ae7

**Comment by mvtglobally** [comment] 2024-10-19 03:50
Issue not reproducible during KI retests. (First week)

**Comment by brunovjk** [comment] 2024-10-21 19:42
I can still reproduce (v9.0.51-3 - 21 Oct):

https://github.com/user-attachments/assets/1b01207b-c77b-4852-b729-79f12df5b5c4

It still seems like an issue with BE, I haven't found a problem or solution related to FE.

**Comment by brunovjk** [comment] 2024-10-23 11:29
This is an internal issue so going to unassign myself, but if this at all requires any front end changes, do assign me back, would love to help, thanks :)

**Comment by mvtglobally** [comment] 2024-10-30 09:42
Issue not reproducible during KI retests. (Second week)

**Comment by sakluger** [comment] 2024-10-30 19:51
Since this hasn't been reproducible for several weeks and because it doesn't relate to paid features, I'm going to close the issue. Feel free to reopen if it occurs again.

**Closed by sakluger** 2024-10-30 19:51 UTC
Labels: Weekly, Internal, Bug, Hot Pick
