### ISSUE TITLE
[Payment due] [$250] Wrong navigation occurs when we create a category with the name 'new'

### ISSUE THREAD

**Issue by m-natarajan** [Expensify/App#48604] opened 2024-09-04 23:28 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 9.0.29-6
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** @jayeshmangwani 
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1725484110243019

## Action Performed:
1. Open the app and go to Settings -> Workspaces.
2. Select any workspace and navigate to Categories.
3. Click Add Category and create a new category with the name "new".
4. Click on the newly created category "new".

## Expected Result:
Pressing on the category should have opened the category details.
## Actual Result:
Pressing on the category with the name 'new' goes to Add Category.
## Workaround:
unknown
## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

https://github.com/user-attachments/assets/a3c963bc-31b1-4c62-8667-09082ba5e603

https://github.com/user-attachments/assets/938a181d-cf77-44ab-b6ca-49e29183ae02

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~021833438666330489454</li>
        <li>Upwork Job ID: 1833438666330489454</li>
        <li>Last Price Increase: 2024-09-10</li>
<li>Automatic offers: </li>
<ul>
<li>shubham1206agra | Reviewer | 103900935</li>
<li>dominictb | Contributor | 103900936</li>
</ul></li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @shubham1206agra</details>

**Comment by ChavdaSachin** [comment] 2024-09-05 00:02
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
Clicking on category named `new` on `WORKSPACE_CATEGORIES` page, App navigates to wrong page

### What is the root cause of that problem?
- RCA for this issue is - 
when clicked on a category  on `WORKSPACE_CATEGORIES` page, App tries to navigate to `CATEGORY_SETTINGS` page using 
https://github.com/Expensify/App/blob/6760f96d9f7fc425e6972be27e5fb0a277805bd6/src/ROUTES.ts#L734-L737 or 
https://github.com/Expensify/App/blob/6760f96d9f7fc425e6972be27e5fb0a277805bd6/src/ROUTES.ts#L405-L408

- So, in both cases if category name is `new`  then `CATEGORY_SETTINGS` page route will look like - `settings/:policyID/categories/new`
which is the exact route of `CATEGORY_CREATE` page
https://github.com/Expensify/App/blob/6760f96d9f7fc425e6972be27e5fb0a277805bd6/src/ROUTES.ts#L413-L416
So, when we click on category named `new` we actually navigate to `CATEGORY_CREATE` page

- Similar problem will arise in case of category named `settings`



### What changes do you think we should make in order to solve the problem?
- To solve this issue we should alter `CATEGORY_SETTINGS` page route in such way it does not clash with any other path.
- So, append "/settings" to both route
```javascript
route: 'settings/workspaces/:policyID/categories/:categoryName/settings',
getRoute: (policyID: string, categoryName: string) => `settings/workspaces/${policyID}/categories/${encodeURIComponent(categoryName)}/settings` as const,
```
https://github.com/Expensify/App/blob/6760f96d9f7fc425e6972be27e5fb0a277805bd6/src/ROUTES.ts#L735-L736
- And,
```javascript
route: 'settings/:policyID/categories/:categoryName/settings',
getRoute: (policyID: string, categoryName: string, backTo = '') => getUrlWithBackToParam(`settings/${policyID}/categories/${encodeURIComponent(categoryName)}/settings
```
https://github.com/Expensify/App/blob/6760f96d9f7fc425e6972be27e5fb0a277805bd6/src/ROUTES.ts#L406-L407

### What alternative solutions did you explore? (Optional)
- We could edit `SETTINGS_CATEGORY_CREATE` , `SETTINGS_CATEGORIES_SETTINGS` , `SETTINGS_CATEGORIES_SETTINGS` and `SETTINGS_CATEGORY_CREATE` if we do not wish to edit `SETTINGS_CATEGORY_SETTINGS` and `WORKSPACE_CATEGORY_SETTINGS` or any similar change could be applied.

**Comment by dylanexpensify** [comment] 2024-09-10 09:33
external

**Comment by dylanexpensify** [comment] 2024-09-18 10:46
Merged!

**Comment by dylanexpensify** [comment] 2024-10-07 12:47
Payment summary:

Contributor: @dominictb $250 via Upwork
Contributor+: @shubham1206agra $250 via Upwork

Please apply/request!

**Comment by dylanexpensify** [comment] 2024-10-07 12:48
@shubham1206agra please accept offer 🙇‍♂️ 

@dominictb payment sent!

**Comment by dylanexpensify** [comment] 2024-10-08 09:51
Done!

**Closed by dylanexpensify** 2024-10-08 09:51 UTC
Labels: Reviewing, External, Monthly, Bug
