### ISSUE TITLE
[$500] [ANDROID APP] Notifications are displayed in the wrong order

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#26834] opened 2023-09-05 23:35 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Open New Expensify app
2. Log in with account A
3. Minimize the application under account A
4. From another device under account B, send 10 messages (for example, numbers from 1 to 10) to the device with account A.
5. Check the order in which notifications are displayed on the device with account A

## Expected Result:
Notifications are received and displayed in the correct order

## Actual Result:
Notifications are displayed in the wrong order

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [ ] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 1.3.64-0

**Reproducible in staging?:** Yes

**Reproducible in production?:** Yes

**If this was caught during regression testing, add the test name, ID and link from TestRail:**

**Email or phone of affected tester (no customers):**

**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/78819774/2be01dd5-01d1-43ca-afbb-d15150153a46

**Expensify/Expensify Issue URL:**

**Issue reported by:** Applause - Interanal Team

**Slack conversation:**

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01e28fb1f0dbce38ca</li>
        <li>Upwork Job ID: 1699314253921251328</li>
        <li>Last Price Increase: 2023-09-13</li>
    </ul>
</details>

**Comment by jliexpensify** [comment] 2023-09-06 06:50
Wow, yes can definitely reproduce!

**Comment by saifali069** [comment] 2023-09-06 12:43
Proposal

Problem Statement
The issue at hand pertains to the incorrect order of notifications in the Expensify app. When messages are sent from one user to another, the notifications are not being received in the expected chronological order. This disrupts the natural flow of communication within the app.

Root Cause Analysis
The root cause of this problem lies in the current notification handling process. Currently, all notification requests are sent to the server in rapid succession. As a result, the server processes these requests asynchronously, leading to notifications being delivered to the recipient in a seemingly random order. This behavior deviates from the sender's original message order.

Proposed Solution
To address this issue effectively, we recommend the following changes:

Introduce Delay: Modify the Android app to incorporate a minor delay when sending notifications to the server. By introducing this delay, we aim to mitigate the asynchronous handling of requests, ensuring that notifications are processed and delivered in the order they were originally sent by the sender.
Alternative Solutions (Optional)
While investigating this issue, we considered alternative solutions. However, after careful analysis, it was determined that introducing a delay in the notification sending process is the most practical and effective approach to resolving the problem. Other alternatives explored included modifying server-side processing and message queuing mechanisms, but these were deemed less efficient and more complex to implement.

**Comment by imranaalam** [comment] 2023-09-07 04:52
---

### Problem Statement:
Notifications from the Expensify app are not always displayed in the intended order on the client device. This can lead to a confusing user experience, as more recent notifications might appear before earlier ones.

---

### Root Cause:
1. **Lack of Sequential Identifiers**: The current push notification handling mechanism does not consider the sequence of notifications. Notifications are processed as they arrive, and if there's any delay in the network or the processing of earlier notifications, later notifications might be displayed first.
2. **Server-Side Ordering**: It's uncertain if the server sends notifications in a strict sequence. Variabilities in how the server sends notifications or how they're routed through push services can affect the order in which they're received on the client side.

---

### Proposed Solution:
Leverage a promise-based mechanism to ensure notifications are processed and displayed in the correct order:

1. **Buffered Notifications**: Store incoming notifications in a buffer.
2. **Promise Queue**: Queue notifications as tasks instead of processing them immediately. Each task will be a promise that processes a notification.
3. **Processing Chain**: Chain the promises to execute sequentially, ensuring the order of processing.
4. **Error Handling**: To prevent any error from disrupting the entire promise chain, integrate proper error handling using `async/await` with `try/catch`.

**Code Implementation**:

```javascript
let bufferedNotifications = [];
let promiseChain = Promise.resolve();  // Start with a resolved promise as the base of the chain

function pushNotificationEventCallback(notificationEvent) {
    const { pushPayload } = notificationEvent;
    const timestampOrSeqNum = pushPayload.timestamp || pushPayload.sequenceNumber;

    // Check for duplicates
    if (bufferedNotifications.some(notif => notif.notification.id === pushPayload.id)) {
        return;  // Skip processing this notification
    }

    // Add the notification processing as a new link in the promise chain
    promiseChain = promiseChain.then(async () => {
        try {
            // Store the notification in the buffer
            bufferedNotifications.push({
                timestampOrSeqNum: timestampOrSeqNum,
                notification: pushPayload
            });

            // Sort the buffered notifications
            bufferedNotifications.sort((a, b) => a.timestampOrSeqNum - b.timestampOrSeqNum);

            // If the buffer gets too large, process and display the notifications
            if (bufferedNotifications.length > BUFFER_SIZE_LIMIT) {
                displayNotifications();
            }
        } catch (error) {
            console.error("Error processing the notification:", error);
        }
    });
}

function displayNotifications() {
    // Display notifications from the buffer
    console.log(bufferedNotifications);
    
    // Clear the buffer after display
    bufferedNotifications = [];
}
```

---

### Alternative Solution:
1. **Direct Handling with Timestamps/Sequence Numbers**: Instead of buffering notifications, process them immediately as they arrive. Use their timestamps or sequence numbers to determine if they should be displayed immediately or held back waiting for any missing notifications. This approach minimizes memory usage but might introduce complexities in handling out-of-order arrivals.
2. **Server-Side Adjustments**: Collaborate with the backend team to ensure notifications are sent in a strict sequence. Implement server-side mechanisms to confirm delivery or resend missing notifications, potentially reducing the likelihood of out-of-order arrivals.
3. **Custom Notification UI**: Implement a custom in-app notification UI to have greater control over the order and display of notifications. Handle any out-of-order scenarios before presenting them to the user.

---

**Comment by jliexpensify** [comment] 2023-09-14 02:51
Bump @Ollyws for reviews!

**Comment by jliexpensify** [comment] 2023-09-18 23:59
Bumping @Ollyws for reviews. If you're unable to review, let me know and I can reassign another C+.

**Comment by jliexpensify** [comment] 2023-09-20 01:47
Hi @cead22 - hoping you could [confirm](https://github.com/Expensify/App/issues/26834#issuecomment-1725488011) that this is an `Internal` issue to be worked on? Thanks!

**Comment by cead22** [comment] 2023-09-20 02:38
I think we should close this issue. Push notifications aren't guaranteed to be delivered in the order they're sent to apple/google. Moreover, this is an edge case that is unlikely to be experienced while using the app normally because usually there is some time from the moment you send a chat to the next.

Give that, this is more a feature request than a bug imo. 

As an aside, it would be good if the video showed the full reproduction steps (cc @lanitochka17), and if we're just sending 1, 2, 3, ... in full speed, then it reinforces that this is an edge case that isn't reflective of the normal use of the app.

Please reopen if you disagree, including the video showing the full reproduction steps

**Closed by cead22** 2023-09-20 02:38 UTC
Labels: Engineering, Daily, Internal, Help Wanted, Bug

**Comment by mvtglobally** [comment] 2023-09-21 03:36
Issue not reproducible during KI retests. (First week)
