### ISSUE TITLE
IOU - Error message appears when decline the request money

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#14548] opened 2023-01-25 15:49 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Go to URL https://staging.new.expensify.com/
2. Login with gmail account
3. Account A requests money from account B
4. In incognito windows log in to Account B and decline the request for money

## Expected Result:
No error message when declined the request money

## Actual Result:
Error message appears when decline the request money

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [ ] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 1.2.59.1

**Reproducible in staging?:** Yes

**Reproducible in production?:** No

**If this was caught during regression testing, add the test name, ID and link from TestRail:**

**Email or phone of affected tester (no customers):**

**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Notes/Photos/Videos:** Any additional supporting documentation

![image (3)](https://user-images.githubusercontent.com/93399543/214609521-08a3eda1-245f-4210-a495-15c9de97d48f.png)
![request money 2501](https://user-images.githubusercontent.com/93399543/214609525-af4f304c-346b-4683-a24f-049c5e392bac.JPG)

https://user-images.githubusercontent.com/93399543/214609531-221025cd-a1ef-4edb-874e-2d0b3b21fcfd.mp4

**Expensify/Expensify Issue URL:**

**Issue reported by:** Applause - Internal team

**Slack conversation:**

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by mountiny** [comment] 2023-01-25 16:11
This is not specifically a deploy blocker, this will be resolved once Auth PR https://github.com/Expensify/Auth/pull/7440 will get deployed.

We should however not deploy to production before the Auth is deployed I assume

**Comment by dangrous** [comment] 2023-01-25 17:18
Okay great, so I can just hold for now, and retest once Auth is deployed?

**Comment by mountiny** [comment] 2023-01-25 17:18
yes 🙌

**Comment by kbecciv** [comment] 2023-01-25 17:59
@dangrous Can you please confirm if this is the same root of cause when settling by PayPal/ elsewhere?
Or we need to log a separate issue for that?

https://user-images.githubusercontent.com/93399543/214644900-193b19ee-96e0-459a-b173-06e553dd044e.mp4

**Comment by mountiny** [comment] 2023-01-25 21:23
@kbecciv Yes, I think thats the same root cause. 

@dangrous you should be able to restest now I believe, the Auth PR is deployed

**Comment by dangrous** [comment] 2023-01-25 21:59
Cool! Worked for me - no error message appeared
![Screenshot 2023-01-25 at 16 59 05](https://user-images.githubusercontent.com/5487802/214700976-3aac2c48-a875-4a4f-bd25-0d679e091464.png)

**Comment by dangrous** [comment] 2023-01-25 22:01
I just checked using "Settled up elsewhere" and it seems to be okay as well.

However I realize for both I had to open another chat and come back for user A to see the "settled up" or "declined" message. @mountiny do you know if that is a separate bug or do we need to investigate that here

**Comment by roryabraham** [comment] 2023-01-25 22:49
> However I realize for both I had to open another chat and come back for user A to see the "settled up" or "declined" message. @mountiny do you know if that is a separate bug or do we need to investigate that here

Separate issue – but let's make sure we report it. In the meantime I'm demoting this from deploy blocker.

@dangrous do you mind reporting that bug separately in #expensify-bugs and then closing this issue when you're done?

**Comment by mountiny** [comment] 2023-01-26 10:57
@dangrous confirmed this is fixed now. 

Did you mean that you dont see the declined message in the second account? 
<img width="864" alt="image" src="https://user-images.githubusercontent.com/36083550/214818588-90908f7f-d09c-4092-8f06-7f0a24908445.png">


It worked fine for me on the account I declined the request from it was added optimistically immediately.

In terms of the issue you can see in the screen shot, the message is correctly showing in the LHN but it dod not autopopulate to the report screen. This is however a bug which is reported now and we are trying to find some good reproduction steps since it seems like its not happening everytime.

Here is the issue https://expensify.slack.com/archives/C049HHMV9SM/p1674669337825539

I think we can close this one now

**Closed by mountiny** 2023-01-26 10:57 UTC
Labels: Engineering, Daily

**Comment by dangrous** [comment] 2023-01-26 14:16
@mountiny yeah - it DID show up in the LHN but not in the report screen until I switched to another chat and back. To confirm, I don't need to report this?
