### ISSUE TITLE
Thread - Thread report name is parent message owner's name when originates from group chat

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#39497] opened 2024-04-03 13:56 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.59-0
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**If this was caught during regression testing, add the test name, ID and link from TestRail:** N/A
**Issue reported by:** Applause - Internal Team

## Action Performed:
1. Log in to New Expensify
2. Create group chat
3. Send a message in the chat
4. Hover over the message > click on Reply in thread

## Expected Result:
Thread report name should be the thread parent message

## Actual Result:
Thread report name is the parent message owner's name

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [ ] Android: mWeb Chrome
- [x] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details> 

https://github.com/Expensify/App/assets/78819774/704b4302-8c04-4fd0-ac49-73e424baa713

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by lanitochka17** [comment] 2024-04-03 13:57
We think that this bug might be related to #vip-vsp

**Comment by lanitochka17** [comment] 2024-04-03 13:57
@kevinksullivan  FYI I haven't added the External label as I wasn't 100% sure about this issue. Please take a look and add the label if you agree it's a bug and can be handled by external contributors

**Comment by bernhardoj** [comment] 2024-04-03 16:54
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
The thread created from a group chat doesn't show the parent message as the report name.

### What is the root cause of that problem?
When it's a group chat, we use `getGroupChatName` to get the name.
https://github.com/Expensify/App/blob/2b592a2f93af827afa6ca0b438efab2235935249/src/pages/home/HeaderView.tsx#L92

The group chat condition checks for the chat type whether it's group or not.
https://github.com/Expensify/App/blob/2b592a2f93af827afa6ca0b438efab2235935249/src/pages/home/HeaderView.tsx#L79

A thread will always inherit the chat type of its parent, this happens on every type of report, so inside the thread, `isGroupChat()` is still true.

This doesn't happen before when we still use the old condition to check for group chat (`isDeprecatedGroupDM`) because it excludes thread chat.
https://github.com/Expensify/App/blob/2b592a2f93af827afa6ca0b438efab2235935249/src/libs/ReportUtils.ts#L5312

The `getGroupChatName` will return the participants name sorted alphabetically with a limit, but the logic to show the parent message for a thread is in `getReportName`.

### What changes do you think we should make in order to solve the problem?

We can move the group chat condition to `getReportName` to have a single place of the report name logic. This way, the thread parent message will be prioritized based on the current logic of `getReportName`.
https://github.com/Expensify/App/blob/2b592a2f93af827afa6ca0b438efab2235935249/src/libs/ReportUtils.ts#L2845-L2929

We will add a new case for group chat at the bottom.
```
if (isGroupChat(report) || isDeprecatedGroupDM(report)) {
    formattedName = getGroupChatName(report?.participantAccountIDs ?? [], shouldApplyLimitForGroupChat);
}
```

And replace this
https://github.com/Expensify/App/blob/2b592a2f93af827afa6ca0b438efab2235935249/src/pages/home/HeaderView.tsx#L92

to:
`const title = ReportUtils.getReportName(reportHeaderData, undefined, true);`

We need to apply this in OptionRowLHN, ReportSettingsPage, and potentially other places that I haven't discovered yet.

### What alternative solutions did you explore? (Optional)
Return false in `isGroupChat` if it's a thread.

**Comment by kevinksullivan** [comment] 2024-04-05 23:06
asking about where this fits


https://expensify.slack.com/archives/C05RECHFBEW/p1712358384520919

**Comment by marcaaron** [comment] 2024-04-06 02:50
I'll help take a look at this on Monday.

**Comment by marcaaron** [comment] 2024-04-10 02:05
Testing this locally against https://github.com/Expensify/App/pull/39757 and it appears to be fixed so going to assign myself here. We've already got @s77rt helping on the C+ review so adding them here too.

**Comment by marcaaron** [comment] 2024-04-16 00:49
Waiting for the next deploy, but this one should be fixed now.

**Closed** 2024-04-23 19:20 UTC
Labels: Reviewing, Daily, Bug
