### ISSUE TITLE
[HOLD for payment 2023-11-21] [HOLD for payment 2023-11-17] [$500] Android - Attachments-Password protected file preview is not shown

### ISSUE THREAD

**Issue by izarutskaya** [Expensify/App#30977] opened 2023-11-07 11:22 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.3.96-0
**Reproducible in staging?:** Y
**Reproducible in production?:** N
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** Applause-Internal Team
**Slack conversation:** @

## Action Performed:
1. Launch app
2. Tap on a report
3. Tap plus icon near compose and select "Add attachment"
4. Select any password protected pdf from "Choose document"

## Expected Result:
The preview of password protected pdf must be displayed.

## Actual Result:
The preview of password protected pdf is not shown.

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [ ] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

https://github.com/Expensify/App/assets/115492554/2390829a-fb0f-4370-9bfa-a6a11ff58425

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01a37e828ffc622d7c</li>
        <li>Upwork Job ID: 1721850741098602496</li>
        <li>Last Price Increase: 2023-11-07</li>
    </ul>
</details>

**Comment by izarutskaya** [comment] 2023-11-07 11:24
Not reproducible in production

https://github.com/Expensify/App/assets/115492554/2f7733ee-ff23-438f-b112-0b11da07b183

**Comment by danieldoglas** [comment] 2023-11-07 12:35
@situchan thanks for finding it so fast. Looks like the original contributor is already checking it https://github.com/Expensify/App/pull/30050#issuecomment-1798408019

**Comment by Beamanator** [comment] 2023-11-09 17:59
FYI hopefully the final PR to fix this was merged [here](https://github.com/Expensify/App/pull/31130), and is being CP'd to staging now

**Comment by MitchExpensify** [comment] 2023-11-13 02:09
*Payment summary*:

No payment due here as this is a regression

**Comment by MitchExpensify** [comment] 2023-11-16 01:03
Do we need BZ steps here @burczu ?

**Comment by burczu** [comment] 2023-11-16 08:14
@MitchExpensify I think we do not need it here - it was fixed by the PR fixing regression of another issue.

**Closed** 2023-11-17 02:31 UTC
Labels: External, Engineering, Weekly, Help Wanted, Awaiting Payment, Bug
