### ISSUE TITLE
[HOLD for payment 2023-07-12] [$1000] mWeb - Modified magic code link redirects to Welcome screen with first place of magic code green

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#20169] opened 2023-06-05 14:00 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Open NewDot app
2. On the log in screen, enter a new account email
3. Navigate to the email inbox and open the validate email and copy the link
4. Modify link to staging and change a single character of URL
5. Navigate to the compiled link

## Expected Result:
Magic code boxes should be in red. And I assume "Magic code is incorrect" should be more focused or even in the header of the page. Instead of "Didn't receive a code" there should be a "Request a new code" link.

## Actual Result:
First place of magic code is green, however all the rest 5 are red. Header of the screen is still "Welcome back...", no sign "Magic code is incorrect". Instead of "Request a new code" link there is still "Didn't receive a code" link, however it is obvious from error message that link was received and used.

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [ ] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 1.3.26.3

**Reproducible in staging?:** yes

**Reproducible in production?:** n/a

**If this was caught during regression testing, add the test name, ID and link from TestRail:**

**Email or phone of affected tester (no customers):**

**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/93399543/f5166a22-4467-430d-8800-6bd657756b49

**Expensify/Expensify Issue URL:**

**Issue reported by:** Applause - Internal Team

**Slack conversation:**

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01248e0e8338f0924d</li>
        <li>Upwork Job ID: 1665829720115789824</li>
        <li>Last Price Increase: 2023-06-25</li>
    </ul>
</details>

**Comment by kbecciv** [comment] 2023-06-05 14:33
Adding Deploy Blocker Label, because production did not have green at the start, and there was a different issue that it said "incorrect 2fa" for a modified login for new account.

https://github.com/Expensify/App/assets/93399543/dad01744-cd08-43a7-90a9-37439cacf5ae

**Comment by alexpensify** [comment] 2023-06-05 16:48
To clarify, step 4, `Modify link to staging and change a single character of URL`. Are you saying to remove a number or character after the URL is `https://staging.`? For example, the URL is `https://staging.new.expensify.com/v1/14` but change it to `https://staging.new.expensify.com/v1/15`. Is that correct?

**Comment by roryabraham** [comment] 2023-06-05 18:39
I am demoting this from Deploy Blocker to regular bug b/c, while this bug exists on staging and not prod, it's replacing an existing production bug, and it's not any worse than what we had before. Also, I think this is an edge case that real users are unlikely to encounter.

> Modify link to staging and change a single character of URL

I'm assuming this refers to changing a single character in the validateCode (last) portion of the URL?

**Comment by Beamanator** [comment] 2023-06-05 21:15
This looks like it should be workable externally 👍

**Comment by alexpensify** [comment] 2023-06-05 21:33
@Beamanator were you able to replicate? I didn't apply the label yet because step 4 needs clarification.

**Comment by Beamanator** [comment] 2023-06-05 22:33
Oooh sorry @alexpensify - I removed Help Wanted b/c I haven't actually tried replicating 😬

**Comment by alexpensify** [comment] 2023-06-05 23:43
All good!

**Comment by alexpensify** [comment] 2023-06-07 20:35
@kbecciv - when you get a chance, you please share feedback for this question: https://github.com/Expensify/App/issues/20169#issuecomment-1577136791

Thanks!

**Comment by alexpensify** [comment] 2023-06-09 22:09
I've reviewed Rory's feedback and think that this one should be closed. It's an edge case that is extremely rare.

**Comment by roryabraham** [comment] 2023-06-13 01:34
Hmmm ... while I said above that this is an edge case, I do think it's a valid bug that we should fix. I just didn't think the new behavior was worse than what was already on production, so didn't want to block deploys on it. It's not that extreme of an edge case for a user to enter the wrong magic code or click on the wrong magic link (i.e: an older one)

**Comment by alexpensify** [comment] 2023-06-13 15:57
@roryabraham thanks for clarify, if you feel like this should be reopened then do you have feedback here: 

>To clarify, step 4, Modify link to staging and change a single character of URL. Are you saying to remove a number or character after the URL is https://staging.? For example, the URL is https://staging.new.expensify.com/v1/14 but change it to https://staging.new.expensify.com/v1/15. Is that correct?

I need to confirm the replication step because it's not clear in the description.

**Comment by roryabraham** [comment] 2023-06-13 19:00
Yeah, I'm quite certain that they meant changing the validateCode in the URL like you described

**Comment by alexpensify** [comment] 2023-06-15 23:25
I'll need to test this one again then.

**Comment by alexpensify** [comment] 2023-06-17 17:27
Alright, I tested on Android and confirm if you take the link. Edit the last character of the link and try to follow the link the first code is still in green, not red. 

![image](https://github.com/Expensify/App/assets/8107070/44f109cb-db72-4eb3-9c73-b11633c3b2d7)

**Comment by Beamanator** [comment] 2023-06-20 11:05
Hmm either I'm bad at math or melvin is... this was 1 week old as of 2 days ago, and 2 weeks old as of 15 hours ago? :fry:

**Comment by Beamanator** [comment] 2023-06-20 11:05
But yes @rushatgabhane please do review proposals soon if you can 🙏

**Comment by alexpensify** [comment] 2023-06-22 18:52
@rushatgabhane - any thoughts on the latest response here? Thank you!

**Comment by alexpensify** [comment] 2023-06-23 15:55
No update

**Comment by alexpensify** [comment] 2023-06-26 04:09
Not overdue, we are waiting for a review here.

**Comment by alexpensify** [comment] 2023-06-27 19:41
Awesome, thank you @HezekielT for the news!

**Comment by alexpensify** [comment] 2023-06-29 22:23
Reassigning another `bug` team member, I'm going OOO until Monday, July 10, and will take it back then if it's not closed by then. 

Required action from the 🐛 team:  Check on the PR state and it might be ready for payment late next week.

**Comment by Beamanator** [comment] 2023-07-03 08:40
@NicMendonca / @alexpensify - FYI I was out Friday so I couldn't review - looks like this PR may have been ready & merged w/in 3 days if I had been working, so this may still qualify for the speed bonus

**Comment by MariaHCD** [comment] 2023-07-06 06:53
Just noting that the solution [here](https://github.com/Expensify/App/pull/21724) caused a regression: https://github.com/Expensify/App/issues/22258 (which has since been fixed. Thanks, @HezekielT!)

**Comment by alexpensify** [comment] 2023-07-10 21:09
Alright, removing the other 🐛 team member. I'm back online and see that this is our current state: 

Prepare for payment and review @MariaHCD's comment

**Comment by alexpensify** [comment] 2023-07-12 22:40
I need more time to review the proposed payments based on @MariaHCD's feedback. I'll complete my review tomorrow.

**Comment by alexpensify** [comment] 2023-07-13 21:32
@rushatgabhane - I think tomorrow the regression clears for https://github.com/Expensify/App/issues/22258. Can you please confirm and then I can continue with the payment process? Thanks!

**Comment by alexpensify** [comment] 2023-07-14 18:55
Waiting for the regession confirmation

**Comment by alexpensify** [comment] 2023-07-16 16:41
@MariaHCD - I need some help here, can you please confirm that we cleared the regression period for https://github.com/Expensify/App/issues/22258, and then I can continue with the payment process here? Thanks!

**Comment by MariaHCD** [comment] 2023-07-17 06:10
@alexpensify Yes, I believe the regression period is over and payments can be processed here.

**Comment by rushatgabhane** [comment] 2023-07-17 06:29
made a manual request for $500 https://staging.new.expensify.com/r/5687801944251726

it'll be paid by Anu or Jason

**Comment by alexpensify** [comment] 2023-07-17 20:29
Upwork Payment Link will be: https://www.upwork.com/jobs/~017f81a4814fafb02a

**Comment by alexpensify** [comment] 2023-07-17 20:31
@HezekielT - I've prepared the payment process in Upwork. Due to the regression period, there will be no bonus here and there is a payment reduction.

**Comment by alexpensify** [comment] 2023-07-18 00:16
@HezekielT - I've asked the team to review my calculations and will follow up tomorrow. I would like to be extra sure here before completing the process.

**Comment by alexpensify** [comment] 2023-07-18 19:57
@HezekielT - I updated the payment for this one. I appreciate your patience here.

**Comment by alexpensify** [comment] 2023-07-18 20:01
@rushatgabhane - when you get a chance, can you please complete the checklist? After, we can close this one out: 

https://github.com/Expensify/App/issues/20169#issuecomment-1622147559

Thanks!

**Comment by alexpensify** [comment] 2023-07-20 21:07
@rushatgabhane - any update on completing the checklist, so we can close this one out? Thanks!

**Comment by alexpensify** [comment] 2023-07-21 19:42
@anmurali - we are on hold for C+ payment and will give the 🟢 as soon as the checklist has been completed.

**Comment by rushatgabhane** [comment] 2023-07-23 13:38
WIP ⚠️ 

1. The PR that introduced the bug has been identified. Link to the PR:

2. The offending PR has been commented on, pointing out the bug it caused and why, so the author and reviewers can learn from the mistake. Link to comment:

3. A discussion in #expensify-bugs has been started about whether any other steps should be taken (e.g. updating the PR review checklist) in order to catch this type of bug sooner. Link to discussion:

4. Determine if we should create a regression test for this bug.

5. If we decide to create a [regression test](https://github.com/Expensify/App/blob/main/contributingGuides/REGRESSION_TEST_BEST_PRACTICES.md) for the bug, please propose the regression test steps to ensure the same bug will not reach production again

**Comment by alexpensify** [comment] 2023-07-23 15:50
Thank you @rushatgabhane! @anmurali all set for payment here. I'm going to close this GH since all actions have been completed.

**Closed by alexpensify** 2023-07-23 15:50 UTC
Labels: External, Engineering, Daily, Awaiting Payment, Bug
