### ISSUE TITLE
[HOLD] Question: When marking an old chat as unread should the text in LHN update to show the old chat that was marked unread (it shows the most recent)?

### ISSUE THREAD

**Issue by mvtglobally** [Expensify/App#11045] opened 2022-09-16 04:12 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Mark an old (not newest...) chat as unread from someone
2. Observe text in LHN under the persons bolded name

## Expected Result:
The chat that was marked unread should be the text shows

## Actual Result:
The most recent chat is shown

## Workaround:
Unknown 

## Platform:

Where is this issue occurring?

- Desktop App

**Version Number:** 1.2.0-5
**Reproducible in staging?:** Y 
**Reproducible in production?:** Y 
**Email or phone of affected tester (no customers):** 
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation 

https://user-images.githubusercontent.com/43995119/190555092-d1f28831-3b95-4af9-b765-c8f274779d5d.mp4

**Expensify/Expensify Issue URL:** 
**Issue reported by:** @mallenexpensify 
**Slack conversation:** https://expensify.slack.com/archives/C01GTK53T8Q/p1663266153019799

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by nkuoch** [comment] 2022-09-16 09:41
Not sure if it can be external - marking internal first so someone can take a deeper look

**Comment by marcaaron** [comment] 2022-09-16 17:21
This is and has always been the expected behavior ?

**Comment by mallenexpensify** [comment] 2022-09-16 19:10
I don't think it makes common sense for it to be expected behavior.   The purpose of marking a message as unread is because it's important (for some reason, right?) so that message should be the one shown. 

I can see where the _idea_ of expected behavior would come from though.  For new messages that are sent that aren't read, we show the most recent, not the first unread
<img width="738" alt="image" src="https://user-images.githubusercontent.com/22508304/190712763-6b8929d2-e672-4e42-9d08-05c07994fab9.png">

So... I guess there are a few questions
1. Does showing the most recent chat in LHN make the most sense for new chats?
2. Does showing the most recent chat in LHN make the most sense for a chat that's already been read but then marked as unread?
3. Do new unread and marked unread need function the exact same way?  

Curious of your thoughts @marcaaron and @nkuoch before, potentially, opening up to more 👀 in #expensify-open-source

**Comment by marcaaron** [comment] 2022-09-16 22:47
>I don't think it makes common sense for it to be expected behavior. The purpose of marking a message as unread is because it's important (for some reason, right?) so that message should be the one shown.

Feel free to open it up for more opinions. Personally, I think the purpose of the chat preview is to show you the most recent thing and this seems to be very consistent with how every other chat app I use works.

**Comment by mallenexpensify** [comment] 2022-09-19 19:39
I see both sides... 
I'm trying to think through examples of _real world_ usage, ie mobile-only user, consumer, payments, expenses, ??? and I'm unsure what messages _might_ be included in those that someone _might_ want to mark as unread.  I'm going to assign to me for now, put this on hold and label monthly for now.   I _could_ take a poll in #expensify-open-source but I'd prefer to have examples before doing so.  

Thanks for feedback @marcaaron

**Comment by marcaaron** [comment] 2022-09-21 16:56
I'm gonna drop this from the WhatsApp quality project since I don't think it's a critical enhancement or bug.

**Comment by mallenexpensify** [comment] 2022-10-25 00:58
Gonna close cuz it's not actionable now, we can reopen later if needed/wanted

**Closed by mallenexpensify** 2022-10-25 00:58 UTC
Labels: Monthly, Planning, Overdue, Bug
