### ISSUE TITLE
Android - Split - Input field remains 0 when resetting split amount when the field is focused

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#41938] opened 2024-05-09 17:38 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.72-0
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**If this was caught during regression testing, add the test name, ID and link from TestRail:** N/A
**Issue reported by:** Applause - Internal Team

## Action Performed:
1. Launch New Expensify app
2. Go to group chat
3. Go to + > Split expense
4. Enter amount > Next
5. On confirmation page, tap on the split amount field and clear the field
6. Dismiss the keyboard, and the input field will remain focused
7. Tap Reset

## Expected Result:
The input field which is focused will show the original split amount

## Actual Result:
The input field still remains 0 when resetting split amount when the field is focused

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [ ] Android: mWeb Chrome
- [x] iOS: Native
- [ ] iOS: mWeb Safari
- [ ] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details> 

https://github.com/Expensify/App/assets/78819774/b828f1ba-e9b5-492e-9cbd-92dbb9d423ed

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by lanitochka17** [comment] 2024-05-09 17:39
@joekaufmanexpensify  FYI I haven't added the External label as I wasn't 100% sure about this issue. Please take a look and add the label if you agree it's a bug and can be handled by external contributors

**Comment by lanitochka17** [comment] 2024-05-09 17:39
We think that this bug might be related to #vip-split

**Comment by mananjadhav** [comment] 2024-05-09 18:50
## Proposal

### Please re-state the problem that we are trying to solve in this issue.

The split amount reset doesn't work if the field is focused. While the issue title mentions only 0, it could be any value.


### What is the root cause of that problem?

In the `MoneyRequestAmountInput`, we have a check in the following line

https://github.com/Expensify/App/blob/974f6b58e0acdebd1f97e8c712df0c7a267b9470/src/components/MoneyRequestAmountInput.tsx#L181-L186

which returns early when the current text input is focused `textInput.current?.isFocused()`. This causes the early return and we don't end up calling `setCurrentAmount`.


### What changes do you think we should make in order to solve the problem?


We need to retain `textInput.current?.isFocused()` because if we type and the amount keeps changing, then `setCurrentAmount` will cause flickers and frequent formatting of the amount while the user types. Hence, instead of returning early when the text input is focused, we should add a debounce to the method to execute it with a delay. This will ensure that the `setCurrentAmount` will be called but only when the user stops typing.


### What alternative solutions did you explore? (Optional)

**Reminder:** Please use plain English, be brief and avoid jargon. Feel free to use images, charts or pseudo-code if necessary. Do not post large multi-line diffs or write walls of text. Do not create PRs unless you have been hired for this job.

**Comment by nkdengineer** [comment] 2024-05-10 09:23
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
- The input field still remains 0 when resetting split amount when the field is focused

### What is the root cause of that problem?
- We have inconsistent behavior on web and native when focusing on any input and then clicking on "Reset".

- On web: Clicking on "Reset" button will blur the input, which leads to the below condition will return ```false``` (```textInput.current?.isFocused(): false```):
https://github.com/Expensify/App/blob/5730ba4dced381adc473e502f675e7cf4e974a19/src/components/MoneyRequestAmountInput.tsx#L182
so the amount is reset.

- On native: Clicking on "Reset" button will not blur the input, which leads to the below condition will return ```true``` (```textInput.current?.isFocused(): true```):
https://github.com/Expensify/App/blob/5730ba4dced381adc473e502f675e7cf4e974a19/src/components/MoneyRequestAmountInput.tsx#L182
so the amount is not reset.

### What changes do you think we should make in order to solve the problem?
- If the expected behavior is ```The input field still remains 0 when resetting split amount when the field is focused```, we should update this:
https://github.com/Expensify/App/blob/5730ba4dced381adc473e502f675e7cf4e974a19/src/components/OptionsList/BaseOptionsList.tsx#L223
to:
```
                        <PressableWithFeedback onMouseDown={(e) => {
                                e.preventDefault();
                            }} ... />
```
- We can apply the above change conditionally.
### What alternative solutions did you explore? (Optional)
- NA

**Comment by nkdengineer** [comment] 2024-05-10 17:44
I updated [proposal](https://github.com/Expensify/App/issues/41938#issuecomment-2104266347)

**Comment by joekaufmanexpensify** [comment] 2024-05-13 14:03
Will triage today

**Comment by joekaufmanexpensify** [comment] 2024-05-13 22:21
I don't think this is really a bug. Every other field in the app I tested works like this if you manually dismiss the keyboard. If you tap on the field again, we open the keyboard again. Closing as this doesn't seem to be a bug IMO.

**Closed by joekaufmanexpensify** 2024-05-13 22:21 UTC
Labels: Daily, Bug

**Comment by nkdengineer** [comment] 2024-05-14 02:40
@joekaufmanexpensify There is an inconsistency between the android-web and android-native:

1. In android web, click on 'Reset' will reset the amount.

2. In android native, click on 'Reset' will not reset the amount

Do you think it is a bug? Pls help check when you have a chance.

**Comment by joekaufmanexpensify** [comment] 2024-05-14 17:30
Could you clarify what you mean by clicking on "reset"?

**Comment by nkdengineer** [comment] 2024-05-15 06:35
I mean the "Reset" button in step 7:


<img width="839" alt="Screenshot 2024-05-15 at 13 34 42" src="https://github.com/Expensify/App/assets/161821005/b71b1cd6-7fe9-48c6-a264-f5a77d01e96a">

**Comment by nkdengineer** [comment] 2024-06-01 03:00
@joekaufmanexpensify Do you have any feedback about [this](https://github.com/Expensify/App/issues/41938#issuecomment-2122816517)?

**Comment by joekaufmanexpensify** [comment] 2024-06-04 17:25
When you click out of the field that is 0, is it resetting then? It was for me when I had tested it previously. So it is resetting, the field was just not live updating.
