### ISSUE TITLE
[$1000] Chat - Cursor does not remain the same place when Edit message

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#25413] opened 2023-08-17 15:16 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Go to staging.new.expensify.com.
2. Send a message that includes several emojis
3. Edit the message with the several emojis
4. Remove some emoji and click on emoji picker inside the edit box
5. Add new emoji

## Expected Result:
New emoji should be added in field where the cursor was pointed

## Actual Result:
Cursor does not remain the same place when Edit message. New emoji is added at the end of the message instead on the place where the cursor was last pointed

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [x] Windows / Chrome 
- [ ] MacOS / Desktop

**Version Number:** 1.3.55-0

**Reproducible in staging?:** Yes

**Reproducible in production?:** No

**If this was caught during regression testing, add the test name, ID and link from TestRail:**

**Email or phone of affected tester (no customers):**

**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/78819774/3ed8f8c5-b3ad-4495-bf2f-18e249bdf915

**Expensify/Expensify Issue URL:**

**Issue reported by:** Applause - Internal Team
**Slack conversation:**

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01b02b907f187853cd</li>
        <li>Upwork Job ID: 1692313936551825408</li>
        <li>Last Price Increase: 2023-08-17</li>
<li>Automatic offers: </li>
<ul>
<li>Nikhil-Vats | Contributor | 26187092</li>
<li>situchan | Contributor | 26187097</li>
</ul></li>
    </ul>
</details>

**Comment by getusha** [comment] 2023-08-17 17:13
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
Cursor is not remaining on it's place when inserting emoji
### What is the root cause of that problem?
there is a prop to enable the calculation of the caret position, but in recent migration to function component the default value of the prop is set to false
https://github.com/expensify/App/commit/fb0ef9981c7d9272d9b2e9bd794c18874ca36be9#diff-224d9ca075668f353172108020027fb452485426ce8263e0070e71442a642297R131

which will cause `renderElementForCaretPosition` not to be rendered

https://github.com/Expensify/App/blob/9474292519b470e1f047dfa445b386eca80cef05/src/components/Composer/index.js#L450C25-L450C25

### What changes do you think we should make in order to solve the problem?


We should add `shouldCalculateCaretPosition` prop to `Composer` inside `ReportActionItemMessageEdit`component
### What alternative solutions did you explore? (Optional)

**Comment by situchan** [comment] 2023-08-17 17:20
> there is a prop to enable the calculation of the caret position, but in recent migration to function component the default value of the prop is set to false

@getusha `shouldCalculateCaretPosition` was already false before function migration. If your root cause is correct, do you know why it didn't happen before?

**Comment by getusha** [comment] 2023-08-17 17:28
@situchan updated my proposal explaining the root cause further
https://github.com/Expensify/App/issues/25413#issuecomment-1682668110

**Comment by getusha** [comment] 2023-08-17 17:56
@Nikhil-Vats  when `textRef` is null it means it's not rendered and `shouldCalculateCaretPosition` is false which makes your proposal same as mine with slight style change.

**Comment by getusha** [comment] 2023-08-17 18:18
Example: added this check

![Screenshot 2023-08-17 at 9 17 10 PM](https://github.com/Expensify/App/assets/75031127/d29f5e94-3f8a-4cea-9132-7942603b7659)

and we you can confirm the execution is stopped right after assigning selectionValue
![Screenshot 2023-08-17 at 9 17 43 PM](https://github.com/Expensify/App/assets/75031127/a8585daa-e1c3-419c-b535-c4ded80895b7)

**Comment by perunt** [comment] 2023-08-17 18:20
Hey guys, it was initially my fault when I migrated this component. So here is my proposal-fix

```
    const addCursorPositionToSelectionChange = (event) => {
        const selectionValue = {start: 0, end: 0, positionX: 0, positionY: 0};
        if (shouldCalculateCaretPosition) {
            // we do flushSync to make sure that the valueBeforeCaret is updated before we calculate the caret position to receive a proper position otherwise we will calculate position for the previous state
            flushSync(() => {
                setValueBeforeCaret(event.target.value.slice(0, event.nativeEvent.selection.start));
                setCaretContent(getNextChars(value, event.nativeEvent.selection.start));
            });
            selectionValue.positionX = textRef.current.offsetLeft - CONST.SPACE_CHARACTER_WIDTH;
            selectionValue.positionY = textRef.current.offsetTop;
        }

        selectionValue.start = event.nativeEvent.selection.start;
        selectionValue.end = event.nativeEvent.selection.end;

        onSelectionChange({
            nativeEvent: {
                selection: selectionValue,
            },
        });
        setSelection(selectionValue);
    };

**Comment by perunt** [comment] 2023-08-17 18:22
The issue is reproducible because the `onSelectionChange` has never fired. Also, position calculation fields should be defined only when the prop `onSelectionChange` is true

**Comment by perunt** [comment] 2023-08-17 18:25
https://github.com/Expensify/App/assets/48593211/9634ee58-5329-4545-b09f-d8592c5bcebe

**Comment by getusha** [comment] 2023-08-17 18:26
>The issue is reproducible because the onSelectionChange has never fired

@perunt yes, i think the reason behind that is we are trying to access null value. your solution is also equivalent to mine [here](https://github.com/Expensify/App/issues/25413#issuecomment-1682668110)

**Comment by perunt** [comment] 2023-08-17 18:51
Yes, you are right, it has the same root
But with a few points
- for now, edit input shouldn't use shouldCalculateCaretPosition as if used for future inline autosuggestion features and use flushSync, which is quite expensive from a performance perspective
- we shouldn't react to `textRef.current` but `shouldCalculateCaretPosition.`
- also, we shouldn't skip calling `setSelection.` (it's from another proposal, but I need to mention it here)

For the one whose proposal will be chosen, please ensure that `positionX` and `positionY` will come without delay in one frame. It is essential, thanks.

**Comment by neil-marcellini** [comment] 2023-08-17 19:57
I don't understand the root cause explained in @getusha's [proposal](https://github.com/Expensify/App/issues/25413#issuecomment-1682668110). I like @Nikhil-Vats' root cause explanation and [proposal](https://github.com/Expensify/App/issues/25413#issuecomment-1682706494) better. Thanks for your thoughts @perunt. Do you suggest any changes to @Nikhil-Vats' proposal?

Does that sound good @situchan? The root cause is the most important part of the proposal so that's why I prefer the other proposal.

**Comment by getusha** [comment] 2023-08-17 20:00
@neil-marcellini the root cause is that we are trying to access a key from a ref which has a value of null.
the execution stops here, showed an example: https://github.com/Expensify/App/issues/25413#issuecomment-1682754041

**Comment by situchan** [comment] 2023-08-17 20:05
@getusha's root cause is correct (thought not sure why console doesn't show error).

Regarding solution, I am fine either way. One proposes to pass filtered custom event always, while another one proposes to pass raw event when `shouldCalculateCaretPosition` is false.

**Comment by getusha** [comment] 2023-08-17 20:21
I explained that the solution is equivalent to mine and your proposal didn't explain why it's not executing `onSelectionChange` in the root cause https://github.com/Expensify/App/issues/25413#issuecomment-1682749448

**Comment by getusha** [comment] 2023-08-17 21:10
> (thought not sure why console doesn't show error).

@situchan @neil-marcellini the reason it's not throwing an error is a bug from react-native-web

https://github.com/necolas/react-native-web/blob/ef95fc0c2b40cc0d3743df4b56485a16a8442e5f/packages/react-native-web/src/exports/TextInput/index.js#L328-L337

it's contained in a try and catch block, which prevents the error from being shown. if you change the catch block to log the error inside  `node_modules/@expensify/react-native-web/dist/exports/TextInput/index.js`, you can see what the actual error is underneath.

![Screenshot 2023-08-18 at 12 08 08 AM](https://github.com/Expensify/App/assets/75031127/7693f327-d097-47c5-a940-e2cca8f611a3)

**Comment by neil-marcellini** [comment] 2023-08-17 23:16
Ok @situchan is the C+ and @Nikhil-Vats will be implementing it. I'm also removing the blocker label because it's a small regression.

**Comment by getusha** [comment] 2023-08-18 01:31
It's quite disappointing decision after I identified the correct Root cause https://github.com/Expensify/App/issues/25413#issuecomment-1682987165, while the selected lacks the correct root cause and has the same proposal as mine. @neil-marcellini i respect your decision 🙂

**Comment by neil-marcellini** [comment] 2023-09-22 02:35
I'll get Jason on it. It's best to message him directly in NewDot.

**Comment by JmillsExpensify** [comment] 2023-09-25 08:50
Thanks for reaching out. Catching up and processing payments.

**Comment by JmillsExpensify** [comment] 2023-09-25 08:51
Payment summary:

 - Issue reporter: N/A
 - Contributor: @Nikhil-Vats $1,500 (incl. urgency bonus)
 - Contributor+: @situchan $1,500 (incl. urgency bonus).

**Comment by JmillsExpensify** [comment] 2023-09-25 08:57
Contributor payment issued. @situchan do you mind completing the BZ checklist before I issue payment?

**Comment by situchan** [comment] 2023-09-25 10:06
I have offer accepted already - https://github.com/Expensify/App/issues/25413#issuecomment-1683098010

**Comment by situchan** [comment] 2023-09-25 10:14
- [x] The PR that introduced the bug has been identified. Link to the PR: https://github.com/Expensify/App/pull/23359
- [x] The offending PR has been commented on, pointing out the bug it caused and why, so the author and reviewers can learn from the mistake. Link to comment: https://github.com/Expensify/App/pull/23359#issuecomment-1733367979
- [x] A discussion in #expensify-bugs has been started about whether any other steps should be taken (e.g. updating the PR review checklist) in order to catch this type of bug sooner. Link to discussion: N/A
- [x] Determine if we should create a regression test for this bug.
- [x] If we decide to create a [regression test](https://github.com/Expensify/App/blob/main/contributingGuides/REGRESSION_TEST_BEST_PRACTICES.md) for the bug, please propose the regression test steps to ensure the same bug will not reach production again.

This was caught by Applause team, which means always exists in Testrail.
So no need further regression test.

**Comment by JmillsExpensify** [comment] 2023-09-25 21:58
Great thanks! I don't see any outstanding contracts for you for this job, so I went ahead and extended one.

**Comment by JmillsExpensify** [comment] 2023-10-08 14:09
My records are showing that everyone has been paid for this issue. Closing! Please reach out if that's incorrect.

**Closed by JmillsExpensify** 2023-10-08 14:09 UTC
Labels: Reviewing, External, Engineering, Weekly, Bug
