### ISSUE TITLE
Pressing "Connect bank account" navigates to personal information step - reported by @Puneet-here

### ISSUE THREAD

**Issue by mvtglobally** [Expensify/App#11316] opened 2022-09-27 04:07 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Go to bank account > add info > company step > personal information > save
2. Dismiss the modal by pressing cross
3. Now go to workspace and visit different pages where "connect bank account" button is present
4. Click on "connect bank account" button
5. Try this few times

## Expected Result:
It should take you to continue with the setup page

## Actual Result:
Sometimes the pressing the connect bank account takes you to the step where you left and sometimes it takes you to continue with the setup page
It's random, sometimes it navigates you to the start over page and sometimes in the middle of some step, It doesn't matter if you are closing the bank page by going back or by pressing the dismiss.

## Workaround:
unknown 

## Platform:

Where is this issue occurring?

- Web
- iOS
- Android
- Desktop App
- Mobile Web

**Version Number:** 1.2.3-0
**Reproducible in staging?:** Y 
**Reproducible in production?:** Y
**Email or phone of affected tester (no customers):** 
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation 

https://user-images.githubusercontent.com/43995119/192429603-aaaf6559-e063-442c-a1c1-24457b6de871.mov

https://user-images.githubusercontent.com/43995119/192429617-381e32b4-ea21-4f54-b2b0-6c42d0bd0195.mov

**Expensify/Expensify Issue URL:** 
**Issue reported by:** @Puneet-here
**Slack conversation:** https://expensify.slack.com/archives/C01GTK53T8Q/p1662749815463499

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by joekaufmanexpensify** [comment] 2022-09-27 13:13
Not able to reproduce in Web. Discussing further [here](https://expensify.slack.com/archives/C01GTK53T8Q/p1664284363930899?thread_ts=1662749815.463499&cid=C01GTK53T8Q).

**Comment by joekaufmanexpensify** [comment] 2022-09-27 14:13
Discussed in the above thread and I'm still not able to reproduce. However, the contributor who reported this is still able to reproduce, and we're both using production web on Mac. 

Re-adding the triage label to see if a secondary reviewer is able to reproduce!

**Comment by JmillsExpensify** [comment] 2022-09-28 20:58
Let me jump in and try to reproduce.

**Comment by joekaufmanexpensify** [comment] 2022-09-28 21:47
Thanks!

**Comment by joekaufmanexpensify** [comment] 2022-09-29 18:52
Pending reproduction.

**Comment by joekaufmanexpensify** [comment] 2022-09-30 17:49
Same.

**Comment by JmillsExpensify** [comment] 2022-10-03 18:51
Yes, I was able to reproduce this issue. These are my reproduction steps, which I'm going to add to the issue description above for clarity.

1. Create a workspace (or use an existing one without a bank account setup)
2. Click either `Issue Cards` or `Reimburse expenses` or `Connect bank account`
3. Enter the information up until personal information and save
4. Exit the workspace modal (X in the top right)
5. Go back to the same workspace
6. Tap `Reimburse expenses` and you'll see the option to continue your setup (or start over)
7. Tap `Connect bank account` and you'll see the option to continue your setup (or start over)
8. Tap `Issue Cards` and you see `Connect bank account` instead of the option to continue setup (or start over)

@joekaufmanexpensify are you sure you're unable to reproduce using these steps?

**Comment by joekaufmanexpensify** [comment] 2022-10-03 21:25
Just went through these steps again and I am able to follow what you listed above through step 8. However, when you click `Connect bank account` in step 8, does it bring you directly to the `Personal information` step?

For me, I go `Issue cards` > `Connect bank account` > and then I have both options of `Continue with setup` and `Start over`, which seems correct to me. Clicking `Continue with setup` then brings me to the `Personal information`, which also seems like expected behavior. 

So I'm specifically unable to reproduce what's shown in the video above where clicking `Issue cards` > `Connect bank account` goes directly to the `Personal information` step.

**Comment by JmillsExpensify** [comment] 2022-10-03 21:37
Ah gotcha! Thanks @joekaufmanexpensify we are making progress in trying to figure this one out. So yes, I agree with this part specifically. 

>For me, I go Issue cards > Connect bank account > and then I have both options of Continue with setup and Start over, which seems correct to me. Clicking Continue with setup then brings me to the Personal information, which also seems like expected behavior

**Comment by JmillsExpensify** [comment] 2022-10-03 21:38
That said, I think we still have a bug on our hands, as steps 6-8 should all take you directly to `Continue with setup`. Right now, only steps 6-7 do. Do you agree with that? If so, we can update the OP.

**Comment by joekaufmanexpensify** [comment] 2022-10-03 22:12
Hm, should `Reimburse expenses` and `Issue cards` go directly to `Continue with setup`?

I was thinking they don't be design, as there's relevant information on the intermediary step for both. For `Reimburse expenses`, it's accessing the mileage rate, etc. And for `Issue cards`, it's viewing benefits about the Expensify Card. 

I agree that step 7 in your list is expected though, as that's a more direct way to access the `Connect bank account` button tucked within `Reimburse expenses` and `Issue cards`.

**Comment by JmillsExpensify** [comment] 2022-10-03 22:35
> And for Issue cards, it's viewing benefits about the Expensify Card.

Oh interesting, I hadn't considered this. I was thinking that if you had started your bank account setup and didn't finish it, that you didn't need to be sold on the card. That said, I can see your point that it's kind of debatable which is right, and that means it's not truly a bug either. 

Ok so I think I'm with you then. There isn't really a bug for this flow. I'm good with closing.

**Comment by JmillsExpensify** [comment] 2022-10-03 22:36
Whoops, mean to leave the closing to you, though also curious for Applause and @Puneet-here to chime in and see if they are still able to reproduce on 1.2.10-0.

**Comment by joekaufmanexpensify** [comment] 2022-10-04 13:24
Sounds good, thanks!

**Comment by Puneet-here** [comment] 2022-10-05 19:09
Hi, I think this is a bug because the behaviour is not consistent even when using the same button to navigate. Example: Sometimes "connect bank account" button at issue cards page navigates to the step where you left and sometimes it takes you to the page with option to start over or continue with the setup.

https://user-images.githubusercontent.com/101883770/194142134-8a9a9eb6-4926-43ec-8bbd-6a0ae0f1356c.mov

cc: @JmillsExpensify @joekaufmanexpensify

**Comment by JmillsExpensify** [comment] 2022-10-06 18:26
Woah ok yeah, thanks @Puneet-here for the second video. It's clear now to me as well. @joekaufmanexpensify who is taking the first test run?

**Comment by JmillsExpensify** [comment] 2022-10-06 18:26
Let's also re-open this in the meantime.

**Comment by Puneet-here** [comment] 2022-10-06 18:43
I tried it on latest staging at web. It's hard to repro because sometimes you will get navigated to some middle step and sometimes to the start over option page. You have to keep trying to repro this.

**Comment by joekaufmanexpensify** [comment] 2022-10-06 20:18
I'll give it another try now!

**Comment by joekaufmanexpensify** [comment] 2022-10-06 20:25
I still can't reproduce. I tried a different combination of options like 10 times and still getting directed to the page with `Continue with setup` and `Start over` every time I click ` Connect bank account`, which is expected. I haven't been able to reproduce jumping directly from `Connect bank account` > `Personal information`. 

![2022-10-06_16-21-34 (1)](https://user-images.githubusercontent.com/54866469/194411530-78b1b899-979f-4408-8fec-a2c47422427f.gif)

@Puneet-here Is there a certain number of times you had to click `Connect bank account` to reproduce?

**Comment by Puneet-here** [comment] 2022-10-06 20:46
Sorry for not commenting this earlier, I was refreshing the page everytime before clicking the button, so it took me 4-5 tries.

**Comment by joekaufmanexpensify** [comment] 2022-10-07 12:58
Even with refreshing the page each time, I still can't reproduce on my end. I see `Continue with setup` every time I click `Connect bank account`. I think we'd need to be able to successfully reproduce the bug to proceed. 

@JmillsExpensify you want to give it another try?

**Comment by Puneet-here** [comment] 2022-10-07 20:14
I think I have found the steps to repro this more easliy.

1. Decrease the screen size so that you don't see the LHN
2. Go to workspace > issue cards > connect bank account 
3. Check what page is opening > dismiss the page and refresh and repeat the steps again

https://user-images.githubusercontent.com/101883770/194645484-56fcc4d9-a056-49c5-b7a9-7d320362e840.mov

**Comment by joekaufmanexpensify** [comment] 2022-10-10 12:02
Not overdue, going to try to reproduce this morning.

**Comment by JmillsExpensify** [comment] 2022-10-10 13:43
Ok cool, that sounds good!

> Check what page is opening > dismiss the page and refresh and repeat the steps again

Regarding this part though, I struggle a bit whether we should spend time on this bug given this specific reproduction step. The mainline case is that you don't dismiss the page, refresh and then repeat the steps again. This is hard for us to reproduce, so I also don't think it's a priority. I think I'd still be in favor of closing.

**Comment by joekaufmanexpensify** [comment] 2022-10-10 18:36
Agreed. I don't think a user is going to complete these steps, given it involves several potential refreshes. Further, following the new reproduction steps above, I still can't reproduce on my end. 

I'm going to close for now!

**Closed by joekaufmanexpensify** 2022-10-10 18:36 UTC
Labels: Daily
