### ISSUE TITLE
[HOLD for payment 2024-12-05] Android - Group - Start group button on confirmation page has extra bottom margin

### ISSUE THREAD

**Issue by IuliiaHerets** [Expensify/App#53190] opened 2024-11-27 07:45 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 9.0.67-1
**Reproducible in staging?:** Y
**Reproducible in production?:** N
**If this was caught on HybridApp, is this reproducible on New Expensify Standalone?:** Y
**Email or phone of affected tester (no customers):** applausetester+232803@applause.expensifail.com
**Issue reported by:** Applause Internal Team

## Action Performed:
Precondition:
- Device navigation is buttons instead of swipe gestures.

1. Launch ND or hybrid app.
2. Go to FAB > Start chat.
3. Tap Add to group next to any user.
4. Tap Next.

## Expected Result:
Start group button on confirmation page will not have extra bottom margin

## Actual Result:
Start group button on confirmation page has extra bottom margin.

This issue is not reproducible if device navigation uses swipe gestures.

## Workaround:
Unknown

## Platforms:

- [x] Android: Standalone
- [x] Android: HybridApp
- [ ] Android: mWeb Chrome
- [ ] iOS: Standalone
- [ ] iOS: HybridApp
- [ ] iOS: mWeb Safari
- [ ] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

https://github.com/user-attachments/assets/2f12dd2c-ba9c-4577-a21b-cfe67048be05

 </details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Issue Owner</summary>Current Issue Owner: @twisterdotcom</details>

**Comment by MariaHCD** [comment] 2024-11-27 09:40
Seems like there are a few deploy blockers related to the way buttons appear in Android. Clarifying in the issue linked above ^

**Comment by twisterdotcom** [comment] 2024-11-27 10:26
Should we close this or HOLD on https://github.com/Expensify/App/issues/53161#issuecomment-2503379049?

**Comment by MariaHCD** [comment] 2024-11-27 10:48
Assigning @kirillzyusko since this also looks to be a regression from the edge-to-edge PR

**Comment by MariaHCD** [comment] 2024-11-27 10:49
@kirillzyusko could you comment here so I can assign you?

**Comment by kirillzyusko** [comment] 2024-11-27 10:50
Sure, feel free to assign me on this issue 👋

**Comment by kirillzyusko** [comment] 2024-11-27 13:43
Can we assign @chrispader on this?

He is working on this ticket at the moment

**Comment by chrispader** [comment] 2024-11-27 13:59
commenting for assignment!

**Comment by mountiny** [comment] 2024-11-28 13:01
Confirmed this was fixed in the 67-8

<img width="433" alt="image" src="https://github.com/user-attachments/assets/486178c7-54b2-4095-b88f-587592378b79">

**Comment by mountiny** [comment] 2024-11-29 09:21
Payment for @allroundexperts handled elsewhere.

No regression test needed as it was a challenging new feature flag for android and these small styling issues are temporary

**Closed by mountiny** 2024-11-29 09:21 UTC
Labels: Engineering, Weekly, Awaiting Payment, Bug
