### ISSUE TITLE
[HOLD] Web - Wrong URL if participant detail page in default room is closed @aneequeahmad

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#10989] opened 2022-09-14 14:06 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Go to staging.new.expensify.com and log in with any account
2. Click on any default room (workspace room)
3. Click on header to open details page > settings > go back by clicking back button >
4. Click on members > any member.
5. Click on close button

## Expected Result:
URL should be r/reportId

## Actual Result:
URL is /r/reportId/details

## Workaround:
Unknown

## Platform:

Where is this issue occurring?

- Web
- iOS
- Android
- Desktop App
- Mobile Web

**Version Number:** 1.2.0.0

**Reproducible in staging?:** Yes

**Reproducible in production?:** Yes
 
**Email or phone of affected tester (no customers):** any

**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Notes/Photos/Videos:** Any additional supporting documentation

https://user-images.githubusercontent.com/93399543/190176503-5c92f0d5-677f-4ec4-964a-f9713dc6266b.mov

**Expensify/Expensify Issue URL:** 

**Issue reported by:** @aneequeahmad

**Slack conversation:** https://expensify.slack.com/archives/C01GTK53T8Q/p1661463319371319

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by grgia** [comment] 2022-09-15 13:11
Setting to external. Note similar issues in comment above!

**Comment by JmillsExpensify** [comment] 2022-09-21 15:46
Sorry ya'll. Missed this in the shuffle. Upwork job is here: https://www.upwork.com/jobs/~01b51a6599d08a678a

**Comment by JmillsExpensify** [comment] 2022-09-26 14:03
Actually, I missed a comment from @parasharrajat in a related issue https://github.com/Expensify/App/issues/10939. I'm going to go ahead and close out the related Upwork job as well as this issue in favor of the existing, older issue linked.

**Comment by JmillsExpensify** [comment] 2023-06-26 20:22
Opening this back up now that the navigation refactor is done.

**Comment by JmillsExpensify** [comment] 2023-07-05 12:40
Still working on testing the remaining issues.

**Comment by mountiny** [comment] 2023-07-06 02:50
I agree with your findings, seems to be fixed now.

**Comment by JmillsExpensify** [comment] 2023-07-12 13:26
Ok cool! I'll add this to fixed and we can issue payment once all issues are tested.

**Comment by JmillsExpensify** [comment] 2023-07-19 13:56
Still working through all the testing issues.

**Comment by JmillsExpensify** [comment] 2023-07-24 22:42
Putting this back on hold for internal tracking

**Comment by JmillsExpensify** [comment] 2023-08-02 04:29
Competing priorities.

**Comment by JmillsExpensify** [comment] 2023-08-08 03:28
Same same. I'm going to look for some help on this one!

**Comment by JmillsExpensify** [comment] 2023-08-16 13:56
Still trying to make time. Low priority.

**Comment by luacmartins** [comment] 2023-08-23 16:16
on hold, not overdue

**Comment by JmillsExpensify** [comment] 2023-08-23 16:52
What he said.

**Comment by JmillsExpensify** [comment] 2023-08-30 05:42
Same

**Comment by JmillsExpensify** [comment] 2023-09-07 02:05
Same

**Comment by luacmartins** [comment] 2023-09-19 00:53
I agree. Closing.

**Comment by aneequeahmad** [comment] 2023-09-19 08:21
@luacmartins i think reporting bonus payment is pending for this task

**Comment by luacmartins** [comment] 2023-09-20 02:11
Oh sorry I missed this. Reopening issue. @JmillsExpensify can you help with report bonus payment?

**Comment by aneequeahmad** [comment] 2023-09-22 23:03
@JmillsExpensify any update on payment ?

**Comment by JmillsExpensify** [comment] 2023-09-25 22:22
@aneequeahmad Would you mind re-testing this issue, including video, and comment confirming whether the issue still persists?

**Comment by aneequeahmad** [comment] 2023-10-03 05:45
@JmillsExpensify This issue isn’t reproducible. Fixed in production. I think time to close this issue.

**Comment by JmillsExpensify** [comment] 2023-10-10 17:36
@aneequeahmad similar to your other reported issues, can you please retest this issue with the exception of the last step and confirm that all is good? At that point we can get you paid for reporting what we've since fixed.

**Comment by aneequeahmad** [comment] 2023-10-10 19:15
@JmillsExpensify this issue is fixed and doesn't exist in production. We are good to close this and issue payment. Thanks

**Comment by JmillsExpensify** [comment] 2023-10-12 19:28
Can you please leave a video confirming? Thanks

**Comment by JmillsExpensify** [comment] 2023-10-16 12:33
Once we get a final test confirmation, we can close this one out.

**Comment by JmillsExpensify** [comment] 2023-10-24 17:40
Still waiting on final test confirmation

**Comment by aneequeahmad** [comment] 2023-11-17 02:39
@JmillsExpensify Sorry for the delay. Here is the test confirmation video. All the `Actions are performed` as stated in repro steps [here](https://github.com/Expensify/App/issues/10989#:~:text=Action%20Performed%3A,on%20close%20button)

https://github.com/Expensify/App/assets/36359331/3266ee0d-c088-4c87-aba3-5177047e40c4

**Comment by aneequeahmad** [comment] 2023-11-23 23:37
@JmillsExpensify lets close this issue as well confirmation video is attached. Thanks

**Comment by JmillsExpensify** [comment] 2023-11-24 16:11
Nice, thank a bunch! That looks great. Closing this out on the Upwork side via payment.

**Comment by JmillsExpensify** [comment] 2023-11-24 16:14
Offer sent. Please accept so I can issue payment.

**Comment by aneequeahmad** [comment] 2023-11-24 17:44
@JmillsExpensify accepted the offer. Thanks for mentioning

**Comment by JmillsExpensify** [comment] 2023-11-24 18:00
All paid out. Thanks!

**Closed by JmillsExpensify** 2023-11-24 18:00 UTC
Labels: External, Engineering, Monthly, Improvement
