### ISSUE TITLE
[$1000] WebP image loads every time while opening in preview

### ISSUE THREAD

**Issue by kavimuru** [Expensify/App#19369] opened 2023-05-22 02:32 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:

1. Go to any chat
2.  send any webp image
3. open image in full window 2-3 times

## Expected Result: 
should show loading for first rime same as other imaged\s
## Actual Result: 
image loads every time

## Workaround:
Can the user still use Expensify without this being fixed? Have you informed them of the workaround?

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [x] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 1.3.16-6
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/43996225/89620dfa-2718-4df1-b0ee-029f829d169d

https://github.com/Expensify/App/assets/43996225/97fa74f9-b8d5-4326-87e1-f8b5cb7e91c8

**Expensify/Expensify Issue URL:**
**Issue reported by:** @gadhiyamanan 
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1684400068777829

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~019f3d2f9c9afc9a99</li>
        <li>Upwork Job ID: 1660698798274568192</li>
        <li>Last Price Increase: 2023-05-29</li>
    </ul>
</details>

**Comment by abekkala** [comment] 2023-05-22 17:27
From Slack: https://expensify.slack.com/archives/C01SKUP7QR0/p1684768175300849?thread_ts=1684767732.056779&cid=C01SKUP7QR0
it is doing 4 requests (2 fail?!?!?) when you open the image:
<img width="1005" alt="Screenshot 2023-05-22 at 12 27 30 PM" src="https://github.com/Expensify/App/assets/11966460/37bf952b-f54e-4982-9be5-194ff2031d97">

**Comment by Naveen3Singh** [comment] 2023-05-24 15:14
## Proposal

### Please re-state the problem that we are trying to solve in this issue.

Webp images aren't stored in the browser cache and are reloaded every time.

### What is the root cause of that problem?

The root cause of this problem is that the response header for webp images always contains `'Cache-Control: no-cache, no-store'`, preventing them from being stored in the cache.

<details>
<Summary>Bad webp response header (https://new.expensify.com)</Summary>

<img src="https://github.com/Expensify/App/assets/36371707/f669cd44-645e-45ea-ab02-dc09a396ebab" width=600 />

</details>


### What changes do you think we should make in order to solve the problem?

- Modify the response header for webp images to include `'Cache-Control: public, max-age=put_expiry_here'`. This will allow the browser to cache the webp images and serve them from the cache for subsequent requests.
- Set the Content-Type header to image/webp for webp images. Currently, this header is not set, and explicitly setting it will ensure proper handling of the image format.

<details>
<Summary>Good webp response header (https://staging.new.expensify.com)</Summary>

<img src="https://github.com/Expensify/App/assets/36371707/40e0b8ee-8e57-4feb-8cdf-47f61831013e" width=600 />

</details>

### What alternative solutions did you explore? (Optional)

Setting `Cache-Control` manually in the request header like this:
```javascript
<RNImage
    {...forwardedProps}
    source={{
        uri: source.uri,
        headers: {
            'Cache-Control': 'max-age=3600, immutable'
        }
    }}
/>
```

The server continued to return `no-cache` for webp images. Therefore, modifying the response header on the server side is the recommended approach to address the caching issue.

**Comment by s77rt** [comment] 2023-05-24 21:34
@Naveen3Singh Thanks for the proposal. Your RCA is correct. Looks like this will be handled internally.

cc @srikarparsi

**Comment by s77rt** [comment] 2023-05-29 11:56
Not overdue. This should be internal. cc @srikarparsi ^

**Comment by srikarparsi** [comment] 2023-05-31 02:35
Thanks @s77rt, will take this over.

**Comment by mvtglobally** [comment] 2023-05-31 04:08
Issue not reproducible during KI retests. (First week)

**Comment by srikarparsi** [comment] 2023-05-31 18:52
Agree, I'm not able to reproduce this issue with this image I downloaded from [here](https://www.gstatic.com/webp/gallery/1.webp). @abekkala, I believe we can close out this issue and reopen it if the issues resurfaces.

**Comment by kavimuru** [comment] 2023-05-31 20:26
@srikarparsi It's reproducible in iOS and Android for jpg image also. Do you need a separate ticket?

Uploading Record_2023-05-31-23-12-46_4f9154176b47c00da84e32064abf1c48.mp4…

**Comment by sakluger** [comment] 2023-06-01 16:27
@s77rt @Naveen3Singh is this other issue the same or similar root cause? It seems like the same same issue, but only for jpg files on iOS and Android native apps.

**Comment by s77rt** [comment] 2023-06-01 17:44
@sakluger I don't think they have the same root cause. This issue's root cause is internal (server response). The other seems related to other factors (I guess it's related to react-native-fast-image).

**Comment by abekkala** [comment] 2023-06-02 12:10
@srikarparsi I was able to reproduce this as well.

**Comment by srikarparsi** [comment] 2023-06-02 16:06
I agree @s77rt. I think we should close out this issue in favor of this [issue](https://github.com/Expensify/App/issues/19920) since they're more or less unrelated. I'll close it out for now but if there's anything left to do for this or the issue resurfaces, feel free to reopen it.

**Closed by srikarparsi** 2023-06-02 16:06 UTC
Labels: Daily, Internal, Help Wanted, Bug
