### ISSUE TITLE
[$250] RHN throws error if tags are deleted by admin while member is selecting.

### ISSUE THREAD

**Issue by carlosmiceli** [Expensify/App#48822] opened 2024-09-09 19:49 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:*v9.0.30-19*
**Reproducible in staging?:*Y*
**Reproducible in production?:*Y*
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:*Carlos Miceli*
**Slack conversation:**

## Action Performed:
- Logged into NewDot as the admin of a workspace in one window and a member in another.
- Go to workspace settings as admin.
- Go to the tags section
- Make sure there are tags on the workspaces
- As a member, open a report's tags in that workspace.
- As an admin, delete all of the tags.

## Expected Result:
There should be an "there are no tags yet" message.

## Actual Result:
Workspace member sees an error view in the RHN instead.

## Workaround:
Unknown.

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

https://github.com/user-attachments/assets/444e3dcc-b6e1-4c9e-b68a-1178abdf3217

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~021833231500737320464</li>
        <li>Upwork Job ID: 1833231500737320464</li>
        <li>Last Price Increase: 2024-09-16</li>
<li>Automatic offers: </li>
<ul>
<li>FitseTLT | Contributor | 103987322</li>
</ul></li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @parasharrajat</details>

**Comment by FitseTLT** [comment] 2024-09-09 19:56
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
RHN throws error if tags are deleted by admin while member is selecting.

### What is the root cause of that problem?
We show not found page when there are non enabled options here
https://github.com/Expensify/App/blob/1b479b0602158fea8eb427fb215a14a18926c58f/src/pages/iou/request/step/IOURequestStepTag.tsx#L80-L81
### What changes do you think we should make in order to solve the problem?

We should implement empty state component as we did for category step page here
https://github.com/Expensify/App/blob/1b479b0602158fea8eb427fb215a14a18926c58f/src/pages/iou/request/step/IOURequestStepCategory.tsx#L171-L174
### What alternative solutions did you explore? (Optional)

**Comment by FitseTLT** [comment] 2024-09-10 09:42
Sorry forgot to notify [Updated](https://github.com/Expensify/App/issues/48822#issuecomment-2338962669)

But note that my last update is hours before the other proposal above

**Comment by FitseTLT** [comment] 2024-09-10 14:34
> Ok. thanks everyone for the proposal and suggestions. I am inclined to implement a similar page like category selection.
> 
> @FitseTLT Looks like you are suggesting a couple more changes and some of them are enhancements.
> 
> Could you please structure your proposal in parts and clean it a bit?

@parasharrajat I have organized my [proposal](https://github.com/Expensify/App/issues/48822#issuecomment-2338962669) as per your request 👍

**Comment by carlosmiceli** [comment] 2024-09-16 16:41
Sorry to miss this, assigned to @FitseTLT !

**Comment by FitseTLT** [comment] 2024-09-18 19:16
@carlosmiceli
We already have a copy for `Edit tag` `Editar etiqueta` but I need the plural form for the button text `Edit tags` and Google translate is suggesting `Editar etiquetas` Can u confirm?

**Comment by carlosmiceli** [comment] 2024-09-18 19:17
@FitseTLT That's correct!

**Comment by abekkala** [comment] 2024-10-11 14:25
### PAYMENT SUMMARY OCT 11

Fix: @FitseTLT [$250] [OFFER](https://www.upwork.com/nx/wm/offer/103987322)
PR Review: @parasharrajat [$250] payment via NewDot

**Comment by abekkala** [comment] 2024-10-11 14:26
@FitseTLT payment sent and contract ended - thank you! 🎉

**Comment by abekkala** [comment] 2024-10-11 14:28
**BugZero Checklist:** The PR fixing this issue has been merged! The following checklist ([instructions](https://stackoverflow.com/c/expensify/questions/14574)) will need to be completed before the issue can be closed:

- [ ] [@parasharrajat] The PR that introduced the bug has been identified. Link to the PR:

- [ ] [@parasharrajat] The offending PR has been commented on, pointing out the bug it caused and why, so the author and reviewers can learn from the mistake. Link to comment:

- [ ] [@parasharrajat] A discussion in #expensify-bugs has been started about whether any other steps should be taken (e.g. updating the PR review checklist) in order to catch this type of bug sooner.

- [ ] [@parasharrajat] Determine if we should create a regression test for this bug.

- [ ] [@parasharrajat] If we decide to create a regression test for the bug, please propose the [regression test](https://github.com/Expensify/App/blob/main/contributingGuides/REGRESSION_TEST_BEST_PRACTICES.md) steps to ensure the same bug will not reach production again.

- [ ] [@abekkala] Link the GH issue for creating/updating the regression test once above steps have been agreed upon:

**Comment by abekkala** [comment] 2024-10-14 08:57
### PAYMENT SUMMARY

- Fix: @FitseTLT [$250] Paid!
- PR Review: @parasharrajat [$250] payment via NewDot

**Closed by abekkala** 2024-10-14 08:57 UTC
Labels: Reviewing, External, Weekly, Bug

**Comment by JmillsExpensify** [comment] 2024-12-16 10:16
$250 approved for @parasharrajat
