### ISSUE TITLE
[HOLD for payment 2024-03-29] [$500] mWeb - Scan - Camera on Scan tab on mweb uses ultrawide camera lens instead of regular lens

### ISSUE THREAD

**Issue by izarutskaya** [Expensify/App#29484] opened 2023-10-12 19:53 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** v1.3.83-5

**Reproducible in staging?:** Y

**Reproducible in production?:** N

**If this was caught during regression testing, add the test name, ID and link from TestRail:**

**Email or phone of affected tester (no customers):**

**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Expensify/Expensify Issue URL:**

**Issue reported by:** Applause-Internal Team

**Slack conversation:** @

## Action Performed:
Precondition: The device used should be a Samsung with ultrawide lens (Samsung to ensure reproducibility). Able to reproduce with SG Note 10+, SG Z Fold 4, SG M52.

1. Go to staging.new.expensify.com
2. Go to + > Request money > Scan.
3. Allow camera permission if not yet.
4. Compare the difference of the camera preview on Android app.
5. Compare the difference on camera native app by switching between ultrawide lens and regular lens.

## Expected Result:
The camera lens used on Scan tab on mweb should be the regular lens, as it does on Android native app.

## Actual Result:
The camera lens used on Scan tab on mweb is ultrawide lens.

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [x] Android: mWeb Chrome
- [ ] iOS: Native
- [x] iOS: mWeb Safari
- [ ] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos
<details>
<summary>Android: Native</summary>

</details>

<details>
<summary>Android: mWeb Chrome</summary>

https://github.com/Expensify/App/assets/115492554/ed6f1c3f-85aa-43c2-9cc4-f2e9136b3430

</details>

<details>
<summary>iOS: Native</summary>

</details>

<details>
<summary>iOS: mWeb Safari</summary>

https://github.com/Expensify/App/assets/115492554/00a457d2-ebf3-4a76-9cfa-c3df72627bbf

</details>

<details>
<summary>MacOS: Chrome / Safari</summary>

</details>

<details>
<summary>MacOS: Desktop</summary>

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01cfe35a5937765358</li>
        <li>Upwork Job ID: 1712557251832860672</li>
        <li>Last Price Increase: 2023-10-19</li>
<li>Automatic offers: </li>
<ul>
<li>aimane-chnaif | Reviewer | 27364648</li>
<li>tienifr | Contributor | 27364649</li>
</ul></li>
    </ul>
</details>

**Comment by izarutskaya** [comment] 2023-10-12 19:55
Camera capture is not available on Prod
![Screenshot_20231012-200952_Chrome](https://github.com/Expensify/App/assets/115492554/b42adda7-5566-40b0-8f71-8003dadd9ee9)

**Comment by srikarparsi** [comment] 2023-10-12 20:08
Hey @AndrewGable, do you think you could take a look at this when you get a chance. I believe this originates from this [PR](https://github.com/Expensify/App/pull/28411), not sure if this should remain a blocker or if it can be addressed in a follow up PR.

**Comment by AndrewGable** [comment] 2023-10-12 20:35
Seems OK for a follow up cc @MitchExpensify  @JmillsExpensify @kevinksullivan

**Comment by AndrewGable** [comment] 2023-10-13 16:38
Seems like this is possible: https://github.com/mozmorris/react-webcam/issues/47#issuecomment-314884057

We are open for proposals on this one!

**Comment by lukemorawski** [comment] 2023-10-17 15:02
@tienifr Can you provide any examples/screenshots/data that the last device returned by the `enumerateDevices()` would be the medium focal length lens. Preferably from couple of devices?

**Comment by bfitzexpensify** [comment] 2023-10-17 19:08
How does @tienifr's [propsal](https://github.com/Expensify/App/issues/29484#issuecomment-1762758348) look @aimane-chnaif?

**Comment by danielrvidal** [comment] 2023-10-18 03:02
@tienifr can you please make sure to provide the examples/screenshots/data that the last device returned by the enumerateDevices() would be the medium focal length lens. Preferably from couple of devices?

This is a high priority issue that we need to make sure is updated quickly. Thanks!

**Comment by bfitzexpensify** [comment] 2023-10-19 20:21
@aimane-chnaif any luck with those approaches @tienifr shared?

**Comment by mvtglobally** [comment] 2023-10-27 00:44
Issue not reproducible during KI retests. (First week)

**Comment by srikarparsi** [comment] 2024-02-12 02:07
Cool sounds good whats the eta looking like now @tienifr?

**Comment by bfitzexpensify** [comment] 2024-02-12 02:33
Bumping the priority on this one

**Comment by bfitzexpensify** [comment] 2024-02-14 04:45
How's this one tracking @tienifr?

**Comment by bfitzexpensify** [comment] 2024-02-21 04:56
Looks like we're in the final testing stages here

**Comment by bfitzexpensify** [comment] 2024-03-04 00:57
Still testing the [PR](https://github.com/Expensify/App/pull/30460) on all platforms

**Comment by bfitzexpensify** [comment] 2024-03-06 23:23
How's this one going @tienifr?

**Comment by bfitzexpensify** [comment] 2024-03-15 09:00
@aimane-chnaif looks like this one is back to you for testing

**Comment by srikarparsi** [comment] 2024-03-20 19:17
It does look like this [PR](https://github.com/Expensify/App/pull/30460) is causing the regression. @rlinoz asked if @aimane-chnaif or @tienifr can take a look but if they're not available in the next couple of hours I'll go ahead with a revert PR for now to resolve the blocker.

**Comment by bfitzexpensify** [comment] 2024-03-28 22:04
Switching to daily so I action payment tomorrow.

**Comment by bfitzexpensify** [comment] 2024-04-01 20:31
Payments are complete. @aimane-chnaif please complete the BZ checklist - thank you!

**Comment by bfitzexpensify** [comment] 2024-04-05 13:55
Bump here @aimane-chnaif

**Comment by bfitzexpensify** [comment] 2024-05-13 13:02
OK, just running through this one myself since Aimane is still OOO. 

**BugZero Checklist:** The PR fixing this issue has been merged! The following checklist ([instructions](https://stackoverflow.com/c/expensify/questions/14574)) will need to be completed before the issue can be closed:

- [ ] The PR that introduced the bug has been identified. Link to the PR: https://github.com/Expensify/App/pull/28411
- [ ] The offending PR has been commented on, pointing out the bug it caused and why, so the author and reviewers can learn from the mistake. Link to comment: https://github.com/Expensify/App/issues/29484#issuecomment-1760297970
- [ ] A discussion in #expensify-bugs has been started about whether any other steps should be taken (e.g. updating the PR review checklist) in order to catch this type of bug sooner. Link to discussion: N/A
- [ ] Determine if we should create a regression test for this bug. N/A - this was caught during testing for the other PR, and the flow is a common one (Scan on mweb). No additional test needed. 
- [ ] If we decide to create a regression test for the bug, please propose the [regression test](https://github.com/Expensify/App/blob/main/contributingGuides/REGRESSION_TEST_BEST_PRACTICES.md) steps to ensure the same bug will not reach production again. N/A
- [ ] Link the GH issue for creating/updating the regression test once above steps have been agreed upon: N/A

**Closed by bfitzexpensify** 2024-05-13 13:02 UTC
Labels: External, Engineering, Daily, Awaiting Payment, Bug
