### ISSUE TITLE
[HOLD for payment 2023-10-30] [HOLD for payment 2023-10-27] [$250] Chat -  First row emojis are skipped

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#30083] opened 2023-10-20 14:38 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.3.87.8
**Reproducible in staging?:** y
**Reproducible in production?:** n
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:**@s-alves10
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1697753213411739

## Action Performed:
1. Open ND and log in with any account
2. Open any chat and tap emoji button in the main composer to open EmojiPicker
3. Type any characters in search input(for example, he)
4. Press arrow down key several times and try to highlight first row emojis by pressing arrow down or arrow left keys
5. Verify that first row emojis are skipped

## Expected Result:
First row emojis can be highlighted by arrow keys

## Actual Result:
First row emojis are skipped

## Workaround:
Unknown 

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [x] Android: mWeb Chrome
- [ ] iOS: Native
- [x] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos
<details>
<summary>Android: Native</summary>

</details>

<details>
<summary>Android: mWeb Chrome</summary>

 

https://github.com/Expensify/App/assets/93399543/dc25c542-8c6f-4657-a3ce-4bfb9b6e5f53

</details>

<details>
<summary>iOS: Native</summary>

</details>

<details>
<summary>iOS: mWeb Safari</summary>

 

https://github.com/Expensify/App/assets/93399543/3761a3b6-799c-4c61-a834-ed003589dd85

 
</details>

<details>
<summary>MacOS: Chrome / Safari</summary>

 

https://github.com/Expensify/App/assets/93399543/3f547a69-2e5d-4d19-b815-04234655e215

https://github.com/Expensify/App/assets/93399543/c6e8f526-c6bb-48c7-ba6d-7881b5d7adf8

</details>

<details>
<summary>MacOS: Desktop</summary>

 

https://github.com/Expensify/App/assets/93399543/aa52de5f-5931-4bb4-98b1-7171589adff6

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01ed51d25e4548ec9f</li>
        <li>Upwork Job ID: 1715386754082848768</li>
        <li>Last Price Increase: 2023-10-20</li>
<li>Automatic offers: </li>
<ul>
<li>fedirjh | Reviewer | 27296434</li>
<li>s-alves10 | Contributor | 27296440</li>
</ul></li>
    </ul>
</details>

**Comment by s-alves10** [comment] 2023-10-20 14:43
## Proposal
### Please re-state the problem that we are trying to solve in this issue.
Can't highlight first row emojis by arrow keys when searching emojis in Emoji Picker
### What is the root cause of that problem?
When moving highlight by arrow keys, we check the bound by the following code
https://github.com/Expensify/App/blob/18acd82f40153fc1e5091aea3217c532142e500e/src/components/EmojiPicker/EmojiPickerMenu/index.js#L257
https://github.com/Expensify/App/blob/18acd82f40153fc1e5091aea3217c532142e500e/src/components/EmojiPicker/EmojiPickerMenu/index.js#L271
When searching emojis, `firstNonHeaderIndex.current` should be 0 because there are no spaces or headers.
But this value is updated by https://github.com/Expensify/App/blob/18acd82f40153fc1e5091aea3217c532142e500e/src/components/EmojiPicker/EmojiPickerMenu/index.js#L364-L379 every time its dependency changes
https://github.com/Expensify/App/blob/18acd82f40153fc1e5091aea3217c532142e500e/src/components/EmojiPicker/EmojiPickerMenu/index.js#L374
That is, `updateFirstNonHeaderIndex` function is called with the entire emojis every time highlight index is changed. So the value of `firstNonHeaderIndex.current` becomes 8
This is the root cause
### What changes do you think we should make in order to solve the problem?
`updateFirstNonHeaderIndex` function should be called with the entire emojis only on mount and when search input is empty.
We do this when search input is empty here
https://github.com/Expensify/App/blob/18acd82f40153fc1e5091aea3217c532142e500e/src/components/EmojiPicker/EmojiPickerMenu/index.js#L180
Remove [this line](https://github.com/Expensify/App/blob/18acd82f40153fc1e5091aea3217c532142e500e/src/components/EmojiPicker/EmojiPickerMenu/index.js#L374) and call the function on mount
```
    useEffect(() => {
        updateFirstNonHeaderIndex(emojis.current);
    }, []);
```
This works as expected
### What alternative solutions did you explore? (Optional)

**Comment by kbecciv** [comment] 2023-10-20 14:46
Proposal by:@s-alves10
Slack conversation: https://expensify.slack.com/archives/C049HHMV9SM/p1697753213411739

## Proposal
### Please re-state the problem that we are trying to solve in this issue.
Can't highlight first row emojis by arrow keys when searching emojis in Emoji Picker
### What is the root cause of that problem?
When moving highlight by arrow keys, we check the bound by the following code
https://github.com/Expensify/App/blob/18acd82f40153fc1e5091aea3217c532142e500e/src/components/EmojiPicker/EmojiPickerMenu/index.js#L257
https://github.com/Expensify/App/blob/18acd82f40153fc1e5091aea3217c532142e500e/src/components/EmojiPicker/EmojiPickerMenu/index.js#L271
When searching emojis, `firstNonHeaderIndex.current` should be 0 because there are no spaces or headers.
But this value is updated by https://github.com/Expensify/App/blob/18acd82f40153fc1e5091aea3217c532142e500e/src/components/EmojiPicker/EmojiPickerMenu/index.js#L364-L379 every time its dependency changes
https://github.com/Expensify/App/blob/18acd82f40153fc1e5091aea3217c532142e500e/src/components/EmojiPicker/EmojiPickerMenu/index.js#L374
That is, `updateFirstNonHeaderIndex` function is called with the entire emojis every time highlight index is changed. So the value of `firstNonHeaderIndex.current` becomes 8
This is the root cause
### What changes do you think we should make in order to solve the problem?
`updateFirstNonHeaderIndex` function should be called with the entire emojis only on mount and when search input is empty.
We do this when search input is empty here
https://github.com/Expensify/App/blob/18acd82f40153fc1e5091aea3217c532142e500e/src/components/EmojiPicker/EmojiPickerMenu/index.js#L180
Remove [this line](https://github.com/Expensify/App/blob/18acd82f40153fc1e5091aea3217c532142e500e/src/components/EmojiPicker/EmojiPickerMenu/index.js#L374) and call the function on mount
```
    useEffect(() => {
        updateFirstNonHeaderIndex(emojis.current);
    }, []);
```
This works as expected
### What alternative solutions did you explore? (Optional)

**Comment by mountiny** [comment] 2023-10-20 15:18
Lowering the amount since this is lower value bug and accessibility feature as well which we dont technically support yet

**Comment by s-alves10** [comment] 2023-10-20 16:05
@fedirjh 

PR is ready for review https://github.com/Expensify/App/pull/30092

**Comment by situchan** [comment] 2023-10-20 16:48
@s-alves10 what's offending PR?

**Comment by s-alves10** [comment] 2023-10-20 16:54
Looks like https://github.com/Expensify/App/pull/29241 is related

**Comment by AndrewGable** [comment] 2023-10-31 22:50
@joekaufmanexpensify - Can you pay out? Thanks

**Comment by joekaufmanexpensify** [comment] 2023-11-01 13:28
Sure!

**Comment by joekaufmanexpensify** [comment] 2023-11-01 13:34
@s-alves10 $425 sent and contract ended!

**Comment by joekaufmanexpensify** [comment] 2023-11-01 13:35
@fedirjh $375 sent and contract ended!

**Comment by joekaufmanexpensify** [comment] 2023-11-01 13:35
Upwork job closed.

**Comment by joekaufmanexpensify** [comment] 2023-11-01 13:35
Closing as this is all set. Thanks everyone!

**Closed by joekaufmanexpensify** 2023-11-01 13:35 UTC
Labels: External, Engineering, Daily, Awaiting Payment, Bug
