### ISSUE TITLE
Extra margin below the header and above the expense information when viewing an expense

### ISSUE THREAD

**Issue by m-natarajan** [Expensify/App#44490] opened 2024-06-26 16:58 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:**  9.0.2-0
**Reproducible in staging?:** Yes
**Reproducible in production?:** Yes
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** @shawnborton 
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1719404177176039

## Action Performed:
1. Launch the app
2. Go to expense report details
3. Scroll the page down
## Expected Result:
No extra margin below header and expense details
## Actual Result:
Extra margin below header and expense details
## Workaround:
Unknown
## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [x] iOS: Native
- [ ] iOS: mWeb Safari
- [ ] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

https://github.com/Expensify/App/assets/38435837/f68560db-1b6e-4d1f-b3bc-5144bccd8fda

https://github.com/Expensify/App/assets/38435837/759b7d35-9be0-4ac4-848e-fdae54a7c8b9

Add any screenshot/video evidence

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by etCoderDysto** [comment] 2024-06-26 18:09
Same root cause with https://github.com/Expensify/App/issues/44434#event-13297000293

**Comment by shawnborton** [comment] 2024-06-26 18:09
Interesting, the video that @m-natarajan posted doesn't actually have the bug. Maybe we need more clear reproduction steps here...

**Comment by etCoderDysto** [comment] 2024-06-26 18:12
No problem 🙌

**Comment by anmurali** [comment] 2024-07-08 16:42
Closing this as a dupe of https://github.com/Expensify/App/issues/44434

**Closed by anmurali** 2024-07-08 16:42 UTC
Labels: Daily, Overdue, Bug
