### ISSUE TITLE
[HOLD for payment 2024-03-08] Implement Tiered Business Bank Account flow

### ISSUE THREAD

**Issue by mountiny** [Expensify/App#22901] opened 2023-07-14 16:20 UTC
This is an implementation issue for the `Tiered bank account setup flow in NewDot` internal [project](https://github.com/Expensify/Expensify/issues/289050), design doc can be found [here](https://docs.google.com/document/d/1t8_Fn93LSSU4gG4z7WRt8IFcpSGK4TIe4QamdcTXjxE/edit?usp=sharing).

All the details will be added to this issue once the implementation will be ready to start.

cc @gedu

**Comment by gedu** [comment] 2023-07-14 16:25
Hey Edu from Callstack

**Comment by anmurali** [comment] 2023-08-09 15:33
Still in review. @gedu there's several sections (Manual tests, automated tests, rollout plan) that you still need to finish for this doc to be done!

**Comment by anmurali** [comment] 2023-08-15 14:58
@gedu bump on this. Were you able to get those sections completed?

**Comment by anmurali** [comment] 2023-08-24 17:53
Asked for an update here[https://expensify.slack.com/archives/C03UK30EA1Z/p1692899559737029?thread_ts=1691159840.865099&cid=C03UK30EA1Z](url)

**Comment by gedu** [comment] 2023-08-24 18:15
I've provided more comprehensive information on how to approach this UI/UX migration, concentrating on elaborating on new components and how to manage navigation, states, and so forth. 
I initiated the Manual Test section, and I'm only left with the final step. Later, I'll proceed with Automated tests.

**Comment by gedu** [comment] 2023-08-25 18:02
Added one more step, and asked some questions about some steps

**Comment by gedu** [comment] 2023-08-29 11:35
@anmurali I added the Manual, Automated and Rollout sections.
There are some questions.

**Comment by gedu** [comment] 2023-09-08 09:30
@anmurali Did you have the chance to review the new sections?

**Comment by anmurali** [comment] 2023-09-25 16:14
Not yet @gedu - I think you also need all the same engineering reviewers to go back through it. So tagging @ryanschaffer @johnmlee101 @joekaufmanexpensify and @joelbettner on that. Please skim through your comments in the doc and make sure we addressed them and resolve? Also we added manual and automated tests, a rollout plan for your review. 
https://docs.google.com/document/d/1t8_Fn93LSSU4gG4z7WRt8IFcpSGK4TIe4QamdcTXjxE/edit?usp=sharing

**Comment by anmurali** [comment] 2023-10-04 12:05
No update.

**Comment by anmurali** [comment] 2023-10-24 22:01
We are now implementing this as part of #wave6-collect-category-tag-submitters-07nov23

**Comment by gedu** [comment] 2023-10-25 07:59
I start creating the issues to start working on this

**Comment by gedu** [comment] 2023-10-27 18:38
Issues created and added into the Document

**Comment by anmurali** [comment] 2024-01-02 23:54
Tracking the first part of this update [here](https://expensify.slack.com/archives/C03UK30EA1Z/p1702052381388209)

**Comment by mountiny** [comment] 2024-02-07 09:56
Assigned @nkuoch and @MariaHCD so they get the credits for reviewing the PR as well 🙌 thanks for help!

**Comment by joekaufmanexpensify** [comment] 2024-02-15 14:47
I have [this one](https://github.com/Expensify/App/issues/35768) where the android app is crashing when setting up a VBA that feels related to this. LMK if you agree!

**Comment by mountiny** [comment] 2024-02-15 16:04
@joekaufmanexpensify The PR was just merged and the issue was reported 2 weeks ago. Could Applause try to retest now after the refactor?

**Comment by joekaufmanexpensify** [comment] 2024-02-15 16:47
Ah, interesting. I didn't realize that was the only PR for this one. I see mine is actually a dupe of another too. So going to close in favor of that one.

**Comment by trjExpensify** [comment] 2024-02-20 23:57
👋 coming from [this issue](https://github.com/Expensify/App/issues/35780#issuecomment-1952539326). 

I suspect some regression test scripts need to be passed over to the Applause to update/add/remove based on the new refactored flow. Who's taking care of that for this project? Let's make sure when this is shipped we do that, so we don't have outdated flows and expected behaviour for the VBBA flow.

**Comment by trjExpensify** [comment] 2024-02-21 00:57
Amazing, thanks!

**Comment by mountiny** [comment] 2024-03-04 16:34
This project spanned couple of months and lots of discussions along the way, testing and QA as well as a follow up PRs. I propose we will pay $5000 for this project to @shubham1206agra given the PRs listed. They have also been removed from the c+ team for some time so they can focus on these changes which meant they were not assigned more work.

Thats why I think the price is appropriate for their work

**Comment by akinwale** [comment] 2024-03-04 16:57
@mountiny As discussed, here are the PRs I have reviewed for the project.

**Main PR**
https://github.com/Expensify/App/pull/34498

**Follow-up PRs**
https://github.com/Expensify/App/pull/36472
https://github.com/Expensify/App/pull/37025
https://github.com/Expensify/App/pull/37032

**Regressions fixed by external contributors**
https://github.com/Expensify/App/pull/36573
https://github.com/Expensify/App/pull/36585
https://github.com/Expensify/App/pull/36589
https://github.com/Expensify/App/pull/36621
https://github.com/Expensify/App/pull/36763

**Comment by mountiny** [comment] 2024-03-04 17:04
As discussed before for @akinwale [here](https://expensify.slack.com/archives/C02NK2DQWUX/p1705493547470639?thread_ts=1705417387.447289&cid=C02NK2DQWUX), we have proposed $1500 for the review of the PR and since he has helped with all the regressions too, I think no penalty should be imposed as it was large PR.

So $1500 for @akinwale for their help on this project.

**Comment by mountiny** [comment] 2024-03-08 13:24
Summary:
- @shubham1206agra $5000 for shepherding this entire project as C+
- @akinwale $2000 for reviewing the main PR and helping with the follow up issues as C+

The breakdown of the PRs is above

@anmurali this is ready for payment

**Comment by anmurali** [comment] 2024-03-08 19:13
Offers sent to @akinwale ([here](https://www.upwork.com/nx/wm/offer/101286233)) and @shubham1206agra ([here](https://www.upwork.com/nx/wm/offer/101286273))

**Comment by akinwale** [comment] 2024-03-09 00:10
> Offers sent to @akinwale ([here](https://www.upwork.com/nx/wm/offer/101286233)) and @shubham1206agra ([here](https://www.upwork.com/nx/wm/offer/101286273))

@anmurali Accepted. Thanks.

**Comment by anmurali** [comment] 2024-03-13 14:42
Yes. @shubham1206agra - ping here when you're ready for us to process it. 
@akinwale is paid.

**Closed** 2024-05-15 14:03 UTC
Labels: Reviewing, Daily, NewFeature, Awaiting Payment
