### ISSUE TITLE
[HOLD for payment 2024-06-21] [$250] mWeb - Chat - Quote markdown is not applied

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#43180] opened 2024-06-06 15:06 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.82-1
**Reproducible in staging?:** Y
**Reproducible in production?:** N
**If this was caught during regression testing, add the test name, ID and link from TestRail:** N/A
**Issue reported by:** Applause - Internal Team

## Action Performed:
1. Go to https://staging.new.expensify.com/home
2. Tap on report
3. Enter >hsjd
4. Send the message

## Expected Result:
Quote markdown must be applied

## Actual Result:
Quote markdown is not applied

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [x] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [ ] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details> 

https://github.com/Expensify/App/assets/78819774/53cb9fa1-12a0-43ac-82fa-4cc25eb52589

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~0162a44a8fd308afd5</li>
        <li>Upwork Job ID: 1798839739922152623</li>
        <li>Last Price Increase: 2024-06-06</li>
<li>Automatic offers: </li>
<ul>
<li>ishpaul777 | Contributor | 102639567</li>
</ul></li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @anmurali</details>

**Comment by lanitochka17** [comment] 2024-06-06 15:07
@bondydaa  FYI I haven't added the External label as I wasn't 100% sure about this issue. Please take a look and add the label if you agree it's a bug and can be handled by external contributors

**Comment by lanitochka17** [comment] 2024-06-06 15:09
We think that this bug might be related to #vip-vsp

**Comment by roryabraham** [comment] 2024-06-06 19:02
If this is indeed the new expected behavior, then react-native-live-markdown needs to be updated such that it's using the new rule. Because right now it's confusing that the markdown processing in the composer is different than what we show in the chat. I think this is a legitimate blocker.

**Comment by roryabraham** [comment] 2024-06-06 19:04
Other option would be to revert https://github.com/Expensify/App/pull/42387

**Comment by luacmartins** [comment] 2024-06-06 21:34
I think reverting https://github.com/Expensify/App/pull/42387 might not be a good solution since there's at least another PR that depends on it https://github.com/Expensify/App/pull/42504

**Comment by luacmartins** [comment] 2024-06-06 21:38
TBH I think we should have a full regression test on https://github.com/Expensify/react-native-live-markdown/pull/360, so I'm not sure that we should push it forward and CP a package bump in App. So that leaves us with adding a patch or demoting this to NAB since we know the root cause and will have a fix out soon

**Comment by luacmartins** [comment] 2024-06-06 22:09
Discussing our options [here](https://expensify.slack.com/archives/C07J32337/p1717709967644529), let's try to go with:

- Include https://github.com/Expensify/expensify-common/pull/691 in react-native-live-markdown via a patch

Making this external for the time being so we can get some contributor eyes to work on the solution above

**Comment by tomekzaw** [comment] 2024-06-07 06:21
Hey, fyi we're already bumping `expensify-common` in `react-native-live-markdown` to 2.0.10 here:
* https://github.com/Expensify/react-native-live-markdown/pull/360

**Comment by tomekzaw** [comment] 2024-06-07 09:03
@BartoszGrajdek will submit a PR that bumps `react-native-live-markdown` to `0.1.82` that should resolve this bug.

**Comment by tomekzaw** [comment] 2024-06-07 09:21
This will not be straightforward as it's not sufficient to just patch expensify-common in react-native-live-markdown; one also needs to re-bundle `react-native-live-markdown-parser.js` (pretty large file) and perhaps include it as patch as well.

I recommend bumping react-native-live-markdown to 0.1.82 as this solves multiple problems at once.

**Comment by BartoszGrajdek** [comment] 2024-06-07 11:33
Here's the PR bumping the version of `react-native-live-markdown`

**Comment by mountiny** [comment] 2024-06-09 21:26
Noting from @ShridharGoel this might have not been fixed completely yet in native @kavimuru can you please retest?

**Comment by BartoszGrajdek** [comment] 2024-06-17 09:56
Yes this should be fixed now. There was a problem with different versions of `expensify-common` in `react-native-live-markdown` and `E/App`. Can we close this one? cc @mountiny @thienlnam

**Comment by luacmartins** [comment] 2024-06-17 15:35
Yea, we can close since this is fixed.

**Comment by anmurali** [comment] 2024-07-10 13:30
Paid.

**Closed by anmurali** 2024-07-10 13:30 UTC
Labels: Reviewing, External, Engineering, Daily, Awaiting Payment, Bug
