### ISSUE TITLE
Profile - Data is not loaded when go back online after page resetting with “Troubleshooting”

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#36601] opened 2024-02-15 16:09 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** v1.4.42-1
**Reproducible in staging?:** y
**Reproducible in production?:** n
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** Applause - Internal Team
**Slack conversation:**

**Issue found when executing PR** https://github.com/Expensify/App/pull/35306
## Action Performed:
1. Go to https://staging.new.expensify.com/
2. Login
3. Go offline
4. Go to Profile -> About -> Troubleshoot
5. Press "Reset and refresh"
6. Confirm the modal
7. Go to home screen and verify skeleton is displayed
8. Go online
9. Wait and verify the data is loaded

## Expected Result:
Data is loaded when go back online

## Actual Result:
Data is not loaded when go back online. Data is loaded after relogin.

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [x] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

https://github.com/Expensify/App/assets/93399543/b977000f-566c-4fe7-a691-046174e2de01

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by rlinoz** [comment] 2024-02-15 16:23
I can reliably reproduce, the screen was just added in this PR https://github.com/Expensify/App/pull/35306, but since it is not a main feature I don't think we should block on it.

@TMisiukiewicz, would you be able to take a look at this?

**Comment by Beamanator** [comment] 2024-02-15 16:23
I don't think this is a deploy blocker either, since this is a Troubleshooting page that is pretty new, thoughts @rlinoz ?

**Comment by Beamanator** [comment] 2024-02-15 16:23
Oh it sounds like we agree! 😅 👍

**Comment by TMisiukiewicz** [comment] 2024-02-16 07:38
Just compared staging vs dev and noticed that on dev, the `OpenApp` API call is in pending state, and gets called again when back online. However, on staging this API call fails instantly when offline, and is not called again when back online 🤔

**Comment by rlinoz** [comment] 2024-02-19 13:52
@TMisiukiewicz were you able to identify why?

**Comment by TMisiukiewicz** [comment] 2024-02-20 07:33
@rlinoz unfortunately not yet, will look more into that once I'm done with my current tasks

**Comment by rlinoz** [comment] 2024-02-21 16:34
Should I add the help wanted label or are we looking at issues related to Troubleshooting somewhere?

cc: @techievivek @TMisiukiewicz

**Comment by TMisiukiewicz** [comment] 2024-02-23 14:40
@rlinoz sorry for late response, I probably missed the notification. In the meantime there was another report for this issue created (#37116), however I am still working on some other stuff so I should have some time to dig into this issue next week

**Comment by trjExpensify** [comment] 2024-02-26 12:10
I don't think we need both of these issues open then do we? Shall we close this in favour of the one Tomasz is assigned to now?

**Comment by rlinoz** [comment] 2024-02-26 13:19
They seem like different issues, but if @TMisiukiewicz thinks this is gonna be solved when we fix the other one, then I agree we can close this.

**Comment by TMisiukiewicz** [comment] 2024-02-28 07:35
Let's keep this open for now, as they might be different issues

**Comment by TMisiukiewicz** [comment] 2024-02-28 12:42
Yes, please assign me 👍

**Comment by TMisiukiewicz** [comment] 2024-03-04 08:09
@rlinoz I just tried it again a few times and each time it worked fine. One time it took pretty much lot of time to get the response from `OpenApp`, but in the end it loaded correctly. Could you take a look how does it work on your end?

**Comment by rlinoz** [comment] 2024-03-04 15:57
Yep, it seems that it is working now.

I'm gonna close this one then, thanks!

**Closed by rlinoz** 2024-03-04 15:57 UTC
Labels: Engineering, Weekly
