### ISSUE TITLE
[HOLD for Payment 2024-10-07][$250] [Search v2.2] Hide mobile Search nav button + status tabs on scrollDown, but reveal on scrollUp

### ISSUE THREAD

**Issue by luacmartins** [Expensify/App#48019] opened 2024-08-26 18:22 UTC
**Problem**
On mobile, the Search page occupies a lot of fixed space between the top workspace switcher, the page navigation button, the status tabs, and the bottom fixed tabs. This doesn't lave a whole lot of vertical space remaining to view the expenses page.

**Solution:**
Let's make it so that the nav button and status tabs scroll the page with the content, but are revealed as soon as the user scrolls back up. Here is a rough prototype of the action: 

https://github.com/user-attachments/assets/1e7f7599-6990-454c-9846-f95c98c42a2f

Note that in the prototype, we're scrolling the button + tabs back into view at the same speed as the content, but I could see where it might even make sense to just animate that area back in as soon as we detect "one scroll" going back up.

cc @Expensify/design @luacmartins for visibility. I think this is good #wave-control polish. 
<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01ee6fbdd84bda73a1</li>
        <li>Upwork Job ID: 1828223707737004666</li>
        <li>Last Price Increase: 2024-08-27</li>
<li>Automatic offers: </li>
<ul>
<li>rayane-djouah | Contributor | 103694364</li>
</ul></li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @kadiealexander</details>

**Comment by nkdengineer** [comment] 2024-08-27 03:09
@luacmartins Can you share the video in OP again, I can't see it in the OP.

**Comment by sachinsiddhu112** [comment] 2024-08-27 04:05
I am unable to see provided video or screenshot.Please provide a video or screenshot of issue.

**Comment by SzymczakJ** [comment] 2024-08-27 10:31
Hey! I’m Jakub Szymczak from Software Mansion, an expert agency, and I’d like to work on this issue!

**Comment by SzymczakJ** [comment] 2024-08-28 09:51
When working on this issue I got one thought concerning StatusBar during **selection mode**. I think we shouldn't show it during selection mode:
1. When clicking on anything on status bar Selection mode is cancelled

https://github.com/user-attachments/assets/e0d1c53a-1a56-440c-99a4-57774180e709


2. We have already hidden **filters button** and **Type selector**, so it doesn't make sense to give user option to choose Status
3. It's cluttering the screen
I could remove StatusBar from selection mode and put this change in PR that would be linked to this task
WDYT @luacmartins

**Comment by shawnborton** [comment] 2024-08-28 11:23
Yeah, I think I agree with that. cc @Expensify/design for thoughts there too, but what you laid out above makes sense to me.

**Comment by SzymczakJ** [comment] 2024-08-28 13:42
How do you guys like it? @dannymcclain @shawnborton @luacmartins 

https://github.com/user-attachments/assets/09e7ae47-6b65-4f6c-abca-40eae1addf26

**Comment by dannymcclain** [comment] 2024-08-28 14:04
Once again, totally agree with all of Shawn's comments.

I think it should scroll away at the same pace as the content when you're at the top, but when you're scrolled down and scroll back up, I do think it should come in with a snappier animation than the regular scroll since we're showing it "in the middle" of a list of item. And then if you scroll down again (without going all the way to the top) I think it would be okay for it to go away with a bit more juice than the normal scroll (since again, it's not really in its home/resting place). Does that make any sense at all?? 😅 😵‍💫

**Comment by SzymczakJ** [comment] 2024-08-28 14:41
> Right now it seems like we are just hiding that area as soon as we detect a single scroll, is that correct?

Yeah, that's how it's currently implemented, as it's the easier solution and I wanted to know your opinion. I'll try to adjust to your comments, but doing so is pretty hard, because of the limitations of SelectionList, which we are forced to use(the outcome may be laggy or not so smooth).
Anyway I'll ping you when I have some new!

**Comment by SzymczakJ** [comment] 2024-08-29 09:54
https://github.com/user-attachments/assets/280f89c7-dad9-4d4a-b788-25b1c63d2cb2

This is what I managed to come up with:
1. When user scrolls down the tab is hiding with the same speed as the user scrolls.
2. When user scrolls up the drawer is put up to full height at a constant speed
WDYT @dannymcclain @shawnborton

**Comment by shawnborton** [comment] 2024-08-29 12:12
Feels solid to me! I would get rid of the gap below the status tabs though, and have that be part of the gap on top of the rows, if that makes sense.

**Comment by shawnborton** [comment] 2024-08-29 13:23
Yup! Perhaps we could keep the padding but reduce it to 8px or something - mostly just thinking that we had too much padding below it previously and it felt a bit clunky?

**Comment by dannymcclain** [comment] 2024-08-29 13:36
>mostly just thinking that we had too much padding below it previously and it felt a bit clunky?

Yeah I agree. I like your suggestion of trying 8px to see what that's like. We just need a _little_ bit of separation.

**Comment by SzymczakJ** [comment] 2024-08-30 08:10
<img width="415" alt="Screenshot 2024-08-30 at 10 10 24" src="https://github.com/user-attachments/assets/f4b72a9c-c213-4d34-bad8-f777dcc50856">
Reduced padding to 8 and I think it looks neat 😃

**Comment by shawnborton** [comment] 2024-08-30 11:14
Can you share a video of that?

**Comment by SzymczakJ** [comment] 2024-08-30 15:47
https://github.com/user-attachments/assets/fed4b798-52af-4574-a204-f4c07764f4a9
Here you go

**Comment by shawnborton** [comment] 2024-08-30 15:49
Cool, I think we just need to add some padding back to the top of the rows so that we get a larger gap between the status tabs and the rows:
![CleanShot 2024-08-30 at 11 48 24@2x](https://github.com/user-attachments/assets/227a5965-8077-47c5-8327-bf66b51f32ea)

Let me know if that makes sense. We probably need to add like 12px there to make up for the 12px we shaved off from the tabs area.

**Comment by SzymczakJ** [comment] 2024-08-30 16:02
Are talking about something like this?

https://github.com/user-attachments/assets/e1b7cd59-5e12-45b3-b805-bfdf9875fdc3

**Comment by shawnborton** [comment] 2024-08-30 16:04
Yup, that spacing looks correct.

**Comment by SzymczakJ** [comment] 2024-09-03 12:15
There was a need for small refactor, but this should be ready for C+ review tomorrow!

**Comment by luacmartins** [comment] 2024-10-01 23:38
PR was merged

**Comment by kadiealexander** [comment] 2024-10-07 00:34
**BugZero Checklist:** The PR fixing this issue has been merged! The following checklist ([instructions](https://stackoverflow.com/c/expensify/questions/14574)) will need to be completed before the issue can be closed:

- [ ] [@rayane-djouah] The PR that introduced the bug has been identified. Link to the PR:
- [ ] [@rayane-djouah] The offending PR has been commented on, pointing out the bug it caused and why, so the author and reviewers can learn from the mistake. Link to comment:
- [ ] [@rayane-djouah] A discussion in #expensify-bugs has been started about whether any other steps should be taken (e.g. updating the PR review checklist) in order to catch this type of bug sooner. Link to discussion:
- [ ] [@rayane-djouah] Determine if we should create a regression test for this bug.
- [ ] [@rayane-djouah] If we decide to create a regression test for the bug, please propose the [regression test](https://github.com/Expensify/App/blob/main/contributingGuides/REGRESSION_TEST_BEST_PRACTICES.md) steps to ensure the same bug will not reach production again.
- [ ] [@kadiealexander] Link the GH issue for creating/updating the regression test once above steps have been agreed upon:

**Comment by kadiealexander** [comment] 2024-10-07 00:43
Payouts due:

- [ ] Contributor+: $250 @rayane-djouah ([Offer link](https://www.upwork.com/nx/wm/offer/103694364))

Upwork job is [here](https://www.upwork.com/jobs/~021839048305434680628).

**Closed** 2024-10-07 21:24 UTC
Labels: External, Daily, NewFeature, Awaiting Payment
