### ISSUE TITLE
[$500] Web - App doesn't handle double slashes in URL

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#30628] opened 2023-10-31 12:21 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.3.93.0
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** @dhanashree-sawant
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1694502293450659

## Action Performed:
1. Open the app
2. Open settings->share code
3. Add one more slash before settings in URL
4. Open anything now throughout the app and observe that app does not change the URL to that page

## Expected Result:
App should handle double slashes in URL like other websites do eg: slack

## Actual Result:
 App does not handle double slashes in URL properly and keeps the URL same always even on visiting any other page

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos
<details>
<summary>Android: Native</summary>

</details>

<details>
<summary>Android: mWeb Chrome</summary>

</details>

<details>
<summary>iOS: Native</summary>

</details>

<details>
<summary>iOS: mWeb Safari</summary>

</details>

<details>
<summary>MacOS: Chrome / Safari</summary>

 

https://github.com/Expensify/App/assets/93399543/4c348df0-c388-4def-9217-94c7549551e4

https://github.com/Expensify/App/assets/93399543/6f05765b-b976-493a-9cf4-ef4b094c9a9f

</details>

<details>
<summary>MacOS: Desktop</summary>

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01ebb02d6f26172072</li>
        <li>Upwork Job ID: 1719328775561465856</li>
        <li>Last Price Increase: 2023-10-31</li>
    </ul>
</details>

**Comment by FitseTLT** [comment] 2023-10-31 13:57
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
App doesn't auto fix double slashes in url
### What is the root cause of that problem?
Double slash auto-fixer hasn't been handle in our custom naviagtor 
### What changes do you think we should make in order to solve the problem?

We need to add code that fix double slashes in our url in CustomRouter `getHydratedState` function
So change this code 
https://github.com/Expensify/App/blob/main/src/libs/Navigation/AppNavigator/createCustomStackNavigator/CustomRouter.js#L76C10-L83C1
to 
```
  }
            fixDoubleSlash(partialState);
            const state = stackRouter.getRehydratedState(partialState, {routeNames, routeParamList});
            return state;
        },
    };
}

function fixDoubleSlash(obj) {
    const routes = obj?.routes || [];
    for (const route of routes) {
        if (route.path) {
            route.path = route.path.replaceAll('//', '/');
        }
        if (route.state) deepChangePath(route.state);
    }
}
```
## Proposal

### Please re-state the problem that we are trying to solve in this issue.

### What is the root cause of that problem?

### What changes do you think we should make in order to solve the problem?


### What alternative solutions did you explore? (Optional)
### What alternative solutions did you explore? (Optional)

**Comment by rakshitjain13** [comment] 2023-10-31 14:29
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
Web - App doesn't handle double slashes in URL
### What is the root cause of that problem?
Extra Slashes are not been converted to single slash in ```CustomRouter.js```
### What changes do you think we should make in order to solve the problem?
We have to introduce a new function that replaces all continuous '/' to single '/'
```
function fixExtraSlash(obj) {
    if (obj && obj.routes) {
        obj.routes = obj.routes.map((route) => {
            if (route.path) {
                route.path = route.path.replace(/\/+/g, '/');
            }
            if (route.state) {
                fixExtraSlash(route.state);
            }
            return route;
        });
    }
    return obj;
}
```

Use this function in the below code 
https://github.com/Expensify/App/blob/48daec812cb850466bf810983728ccf5ed63ed9d/src/libs/Navigation/AppNavigator/createCustomStackNavigator/CustomRouter.js#L65-L82

as

```
  partialState = fixExtraSlash(partialState);
  const state = stackRouter.getRehydratedState(partialState, {routeNames, routeParamList});
   return state;
```


### What alternative solutions did you explore? (Optional)

NA

**Comment by eh2077** [comment] 2023-11-02 14:09
## Proposal

### Please re-state the problem that we are trying to solve in this issue.

Web - App doesn't handle double slashes in URL.

### What is the root cause of that problem?

When open App by deeplink with path starts with double slashes, like

```
https://dev.new.expensify.com:8082//settings/shareCode
```

`window.history.replaceState(state, '', '//settings/shareCode')` returns error because the third parameter `url` starts with double slashes, see

<img width="1431" alt="image" src="https://github.com/Expensify/App/assets/117511920/25996ac9-e4b7-4ff3-bbb9-9273d9f84e78">

According to the error stack, we can debug to figure out the execution path

1. Construct navigation root state from path of deeplink, see line 253 of `useLinking.js`
2. Get focused route from root state, see line 260 of `useLinking.js`
3. Get path, `//settings/shareCode` , from method `getPathForRoute`, see line 261 and 225 of `useLinking.js`

<img width="1439" alt="image" src="https://github.com/Expensify/App/assets/117511920/b76cdf9d-10e5-443e-be25-4ccc8fc8c0a0">

<img width="1217" alt="image" src="https://github.com/Expensify/App/assets/117511920/5f629616-9724-42ef-acb0-f2e14664c8c0">

<img width="1219" alt="image" src="https://github.com/Expensify/App/assets/117511920/b663a5fa-43d3-4ab7-9475-5ef66e21ddb2">

<img width="1217" alt="image" src="https://github.com/Expensify/App/assets/117511920/d0ec7054-76b4-4713-a90f-dfb348a765f1">

So the root cause of this issue is that when construsting the root state of navigation, we don't sanitize the path by replacing multiple slashes with `/`.

See more details in 

`node_modules/@react-navigation/native/lib/commonjs/useLinking.js`

`node_modules/@react-navigation/native/lib/commonjs/createMemoryHistory.js`

`node_modules/@react-navigation/core/src/getStateFromPath.tsx`

### What changes do you think we should make in order to solve the problem?

Based on the RCA above, we should normalise the path for deeplink, like, `https://dev.new.expensify.com:8082//settings/shareCode`, before creating state from the path.

To achieve it, we can add method `getStateFromPath` to `linkingConfig.js` and sanitise path by replacing multiple slashes with one slash.

In https://github.com/Expensify/App/blob/main/src/libs/Navigation/linkingConfig.js, we can import

```js
import {getStateFromPath as RNGetStateFromPath} from '@react-navigation/native';
```

and add

```js
    getStateFromPath: (path, options) => {
        // Replace multiple slash (//) with single ones
        const normalizedPath = path.replace(/\/+/g, '/');
        return RNGetStateFromPath(normalizedPath, options);
    },
```

after this line

https://github.com/Expensify/App/blob/becbeb63bc032f4760702c73c04ce31d90c31885/src/libs/Navigation/linkingConfig.js#L428

See demo

https://github.com/Expensify/App/assets/117511920/16800355-1910-4645-813c-f560ab2d226a

### What alternative solutions did you explore? (Optional)

Based on the main solution, we can also have a more general solution to normalise the url, like using https://github.com/sindresorhus/normalize-url

**Comment by isabelastisser** [comment] 2023-11-02 20:14
Hey @jjcoffee, can you please review the proposals? Thanks!

**Comment by jjcoffee** [comment] 2023-11-03 14:36
I'm unsure of the value of fixing this as it seems more like a case of deliberately trying to break the app that wouldn't happen in any normal use case. 

That being said the first three proposals (@FitseTLT, @rakshitjain13 and @DylanDylann) also don't have particularly satisfying RCAs that deal with the core issue of the URL not changing once you continue navigating after entering a double slash URL.

**Comment by isabelastisser** [comment] 2023-11-06 16:46
Thanks for the context @jjcoffee! Closing.

**Closed by isabelastisser** 2023-11-06 16:46 UTC
Labels: External, Daily, Help Wanted, Overdue, Bug

**Comment by eh2077** [comment] 2023-11-07 00:14
@isabelastisser While I think it's worth fixing because as long as we open the app with common deeplink, like https://new.expensify.com//settings, the address bar URL will fail to update when navigating to other pages. I meant we can polish the case if a user occasionally types double slashes to open the settings page. 

By having this fix, will also make the Navigation feature of App more robust as we have many use cases of navigating to a page by path.

cc @jjcoffee

**Comment by jjcoffee** [comment] 2023-11-07 08:34
@eh2077 Feel free to raise a thread on Slack to gather broader consensus that this should be fixed.
