### ISSUE TITLE
[HOLD for payment 2023-01-19] Removing a member from the workspace removes their name from the LHN as well

### ISSUE THREAD

**Issue by kavimuru** [Expensify/App#13858] opened 2022-12-28 16:57 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:

1. Sign in with User A
2. Go to Settings > Workspaces > New workspace
3. Go to Manage members and invite User B
4. Sign out and sign in with User B
5. Send a message to the invited workspace room
6. Sign out and sign in with User A again
7. Observe the last message on LHN with the user's name (e.g. User B: Hello)
8. Go to Settings > Workspace > Manage members
9. Remove User B
10. Observe the last message in LHN does not have the removed user's name anymore

## Expected Result:
User's name is displayed on LHN's last message

## Actual Result:
User's name is removed from LHN's last message

## Workaround:
unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [ ] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 1.2.44-0
**Reproducible in staging?:** y
**Reproducible in production?:** y
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** 

https://user-images.githubusercontent.com/43996225/209846399-6bb0f032-d169-45ad-9a19-a75792a4cebd.mov

https://user-images.githubusercontent.com/43996225/209846414-ff1fec8d-0c53-4f20-a3a6-9de9cad26adf.mp4

**Expensify/Expensify Issue URL:**
**Issue reported by:** @adeel0202 
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1672128343068489

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~011695e41797943f1c</li>
        <li>Upwork Job ID: 1610435363220934656</li>
        <li>Last Price Increase: 2023-01-04</li>
    </ul>
</details>

**Comment by laurenreidexpensify** [comment] 2023-01-03 13:43
I'm checking in Slack to see if we think this is a bug

**Comment by laurenreidexpensify** [comment] 2023-01-03 13:52
https://expensify.slack.com/archives/C049HHMV9SM/p1672753922529399

**Comment by yuwenmemon** [comment] 2023-01-04 20:53
Okay, so the issue here is that we remove the PersonalDetail of the workspace member once we remove them. So thus, once we try and grab the `lastActorDetails` [here](https://github.com/Expensify/App/blob/ae0a7b6a02c8743b98e4991c036cc4d169b16a8f/src/libs/SidebarUtils.js#L253) we come up with `null`.

I think the simplest option would be to include `lastActorDetails` as a part of the report itself, rather than having to grab them from the `personalDetailsMap`.

Another option, which would be a bit jankier, would be to use the `lastActorEmail` instead of their Display Name if we don't have their details in the `personalDetailsMap`, but I think this is kind of unexpected behavior as well:
<img width="414" alt="Screenshot 2023-01-04 at 12 52 47 PM" src="https://user-images.githubusercontent.com/4741899/210647783-3a485297-a279-431b-8bc1-38f64435e9c2.png">

cc @tgolen for your thoughts on that since I see you all over the blame for this.

**Comment by tgolen** [comment] 2023-01-05 00:11
Why do we remove the personal details when removing them from the
workspace? Do we need to do that and is it necessary? Can we just keep it
there instead?

**Comment by yuwenmemon** [comment] 2023-01-05 01:28
Ah, great question. This made me realize we're actually using an unnecessarily filtered personal details map [here](https://github.com/Expensify/App/blob/ae0a7b6a02c8743b98e4991c036cc4d169b16a8f/src/libs/SidebarUtils.js#L219).

**Comment by laurenreidexpensify** [comment] 2023-01-11 11:56
On Staging

**Comment by laurenreidexpensify** [comment] 2023-01-19 10:57
@yuwenmemon final steps are all yours

**Comment by yuwenmemon** [comment] 2023-01-19 18:02
Done! Closing this out!

**Comment by eVoloshchak** [comment] 2023-01-23 19:15
Also pinging here since I'm eligible for the payment for reviewing https://github.com/Expensify/App/pull/14008

**Comment by yuwenmemon** [comment] 2023-01-24 19:13
@laurenreidexpensify can you handle?

**Comment by mallenexpensify** [comment] 2023-02-01 02:34
@adeel0202 @eVoloshchak can you please accept the job and reply here once you have? 
https://www.upwork.com/jobs/~011695e41797943f1c

**Comment by eVoloshchak** [comment] 2023-02-01 12:58
Offer accepted

**Comment by mallenexpensify** [comment] 2023-02-01 17:27
@adeel0202 ($250 for reporting) and @eVoloshchak ($1000 for C+) have been paid, checklist is ✅ above so closing

**Closed by mallenexpensify** 2023-02-01 17:27 UTC
Labels: Reviewing, Engineering, Daily, Internal, Awaiting Payment, Bug
