### ISSUE TITLE
Distance - "Out of pocket" and "Company spend" appear in report after changing distance

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#35194] opened 2024-01-25 21:52 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** v1.4.32-2
**Reproducible in staging?:** y
**Reproducible in production?:** n
**If this was caught during regression testing, add the test name, ID and link from TestRail:** https://expensify.testrail.io/index.php?/tests/view/4237772
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** Applause - Internal Team
**Slack conversation:**

## Action Performed:
1, Go to workspace chat.
2. Create a distance request.
3. Navigate to request details page.
4. Click Distance.
5. Change the distance.
6. Return to expense report.

## Expected Result:
There will be no "Out of pocket" and "Company spend" in the expense report.

## Actual Result:
"Out of pocket" and "Company spend" appear in the expense report after changing distance.

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [x] Android: mWeb Chrome
- [x] iOS: Native
- [x] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

https://github.com/Expensify/App/assets/93399543/ed160802-90b1-4310-9eac-f7f50899aba6

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by kbecciv** [comment] 2024-01-25 21:52
We think that this bug might be related to #wave6-collect-submitters
CC @greg-schroeder

**Comment by yuwenmemon** [comment] 2024-01-26 01:09
Damn... I can't even get to that page to edit the distance 😱 
![Screenshot 2024-01-25 at 5 09 07 PM](https://github.com/Expensify/App/assets/4741899/0c0b5a2d-a3e8-4e20-84b3-8bb8230a4486)

**Comment by yuwenmemon** [comment] 2024-01-26 01:11
@aldo-expensify Would you be able to take a look at this one? It seems related to https://github.com/Expensify/App/pull/34107

**Comment by yuwenmemon** [comment] 2024-01-26 01:13
Oh wait, seems like you are on top of it in another issue: https://github.com/Expensify/App/issues/35178#issuecomment-1911229178

**Comment by aldo-expensify** [comment] 2024-01-26 01:57
Investigating...

**Comment by aldo-expensify** [comment] 2024-01-26 01:57
ahh this is a duplicate of https://github.com/Expensify/App/issues/35178, it is the same root cause

**Comment by yuwenmemon** [comment] 2024-01-26 01:58
Heh yes sorry that's what I was trying to say 😅

**Closed by aldo-expensify** 2024-01-26 01:57 UTC
Labels: DeployBlockerCash, Engineering, Hourly

**Comment by aldo-expensify** [comment] 2024-01-26 01:58
> Damn... I can't even get to that page to edit the distance 😱 ![Screenshot 2024-01-25 at 5 09 07 PM](https://private-user-images.githubusercontent.com/4741899/299851956-0c0b5a2d-a3e8-4e20-84b3-8bb8230a4486.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDYyMzQzODksIm5iZiI6MTcwNjIzNDA4OSwicGF0aCI6Ii80NzQxODk5LzI5OTg1MTk1Ni0wYzBiNWEyZC1hM2U4LTRlMjAtODRiMy04YmI4MjMwYTQ0ODYucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDEyNiUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDAxMjZUMDE1NDQ5WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9NDE0YzI5YzEyNjY2NmM3NjEzMDViYmVjZGY5MTNhOTQxMmNkOWJkZGIwNmFmMTg3M2FlNGFhMjUxOTY4YTJlZiZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.1P1f1JsCSK_98SX6lloUFQ73ue8uWZ8_mdGVjWOy1yU)

I also experienced this one while testing, I wonder if it is new problem or if it is in production. From what I remember, this happened right after creating the distance request when I tried to edit the locations.

**Comment by aldo-expensify** [comment] 2024-01-26 02:00
> Heh yes sorry that's what I was trying to say 😅

True, I read your comment poorly

**Comment by aldo-expensify** [comment] 2024-01-26 02:02
> Damn... I can't even get to that page to edit the distance 😱

Reproduced in production too, the steps are:

1. Create distance request
2. Without reloading the page, go to the distance request transaction
3. Try to edit the distance -> fail
