### ISSUE TITLE
[$250] Deeplink – Previous conversation opens for a moment when navigate via non-existing link

### ISSUE THREAD

**Issue by izarutskaya** [Expensify/App#39914] opened 2024-04-09 11:04 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:**v1.4.61-0
**Reproducible in staging?:** Y
**Reproducible in production?:** N
**If this was caught during regression testing, add the test name, ID and link from TestRail:** https://expensify.testrail.io/index.php?/tests/view/4480382
**Email or phone of affected tester (no customers):** ponikarchuks+68424@gmail.com
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Issue reported by:** Applause-Internal team

## Action Performed:
1. Go to https://staging.new.expensify.com/
2. Log in.
3. Open any chat
4. Navigate via non-existing link https://staging.new.expensify.com/anything
5. Go back using arrow
6. Navigate via non-existing link https://staging.new.expensify.com/anything
again

## Expected Result:
“Hmm... it's not here” page opens when navigate via non-existing link

## Actual Result:
Previous conversation opens for a moment and then “Hmm... it's not here” page when navigate via non-existing link

## Workaround:
Can the user still use Expensify without this being fixed? Have you informed them of the workaround?

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [x] Android: mWeb Chrome
- [ ] iOS: Native
- [x] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

https://github.com/Expensify/App/assets/115492554/fc07d234-174d-4d0d-ac2c-8d3dddac2374

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01dc60681d78995448</li>
        <li>Upwork Job ID: 1777681979216637952</li>
        <li>Last Price Increase: 2024-04-23</li>
    </ul>
</details>

**Comment by mountiny** [comment] 2024-04-09 12:55
This does not seem like a blocker to me, no detriment to user experience

Going to export this to see if some proposals can fix it though

**Comment by ikevin127** [comment] 2024-04-09 20:27
# Proposal

### Please re-state the problem that we are trying to solve in this issue

Previous conversation opens for a moment when navigating to a non-existing URL (not found page).

### What is the root cause of that problem?

The root cause comes from [this logic](https://github.com/Expensify/App/blob/c50ae1790cabdb7ea0a0be872718d07b74c9ff4c/src/libs/Navigation/AppNavigator/ReportScreenIDSetter.ts#L65-L95) within the `ReportScreenIDSetter` component.

**What's happening exactly ?**

The above-referenced useEffect logic sets the `reportID` of the last accessed report in the route params, **before navigation to a non-existing page is initiated resulting in the not found page**.

**How does this happen ?**
1. The [first if](https://github.com/Expensify/App/blob/c50ae1790cabdb7ea0a0be872718d07b74c9ff4c/src/libs/Navigation/AppNavigator/ReportScreenIDSetter.ts#L67-L74) of the useEffect checks if `route?.params?.reportID` exists -> when navigating to a non-existing page, `route?.params?.reportID` will be `undefined`.
2. The first if is skipped-> the [second if](https://github.com/Expensify/App/blob/c50ae1790cabdb7ea0a0be872718d07b74c9ff4c/src/libs/Navigation/AppNavigator/ReportScreenIDSetter.ts#L76-L94) comes into play and sets the `reportID` of the last accessed report in the route params -> this is why we're navigated to the last accessed report before we're shown the not found page.

### What changes do you think we should make in order to solve the problem?

We have to delay the setting the last accessed reportID in the route params. To do this we can wrap the [final if](https://github.com/Expensify/App/blob/c50ae1790cabdb7ea0a0be872718d07b74c9ff4c/src/libs/Navigation/AppNavigator/ReportScreenIDSetter.ts#L92-L94) of the useEffect with `InteractionManager.runAfterInteractions` which adds just the right amount of delay, but **still sets the last accessed reportID in the route params (this is crucial for maintaining the current logic)**.

**Code changes:**
```ts
    InteractionManager.runAfterInteractions(() => {
        if (!reportID) {
            return;
        }
        navigation.setParams({reportID: String(reportID)});
    });
 ```

By doing this we're basically delaying setting the last accessed reportID in the route params, which won't navigate to the report first -> allowing the not found page to be displayed. Upon closing (or going back) the not found page, the user will be navigated to the last accessed report since the call to set the last accessed reportID in the params was made (with delay).

This means we will see the loading skeleton in the central pane then the not found page, instead of seeing / opening the report and only after that seeing the not found page.

### Videos (before / after)

<details>
<summary>MacOS: Chrome / Safari</summary>

| Before | After |
| ------------- | ------------- |
| <video src="https://github.com/Expensify/App/assets/56457735/2d59c01c-79d2-4d2e-bebe-fc93f965a5d0"> | <video src="https://github.com/Expensify/App/assets/56457735/b6e3bf21-03f8-48b4-b8e3-4181a3406d67"> |

</details>

**Comment by mountiny** [comment] 2024-04-09 21:36
Thanks! That looks good to me but curious for a review from @abdulrahuman5196 too. Thanks!

**Comment by ikevin127** [comment] 2024-04-11 15:09
**abdulrahuman5196** [from (Slack)](https://expensify.enterprise.slack.com/archives/C02NK2DQWUX/p1712847847130359):
> Hi Team, I will be working on lesser capacity for next 2 weeks. I will un-assign myself from issues if I am unable to handle. Also feel free to re-assign if you see any issue delayed because of me.

cc @mountiny

**Comment by abdulrahuman5196** [comment] 2024-04-11 15:12
I will work on this issue in my morning

**Comment by abdulrahuman5196** [comment] 2024-04-12 13:40
Checking now.

**Comment by abdulrahuman5196** [comment] 2024-04-12 15:45
I am not seeing this issue in staging. Let me know if i need to do anything else to repro.


https://github.com/Expensify/App/assets/46707890/d671da3c-cd87-41e8-a616-ffd97c8fc68c

**Comment by ikevin127** [comment] 2024-04-12 16:25
Looks like the issue is gone, not reproducible anymore.
We can ask for a double-check from the testing team and close if confirmed.

**Comment by mountiny** [comment] 2024-04-15 18:13
waiting for a retest

**Comment by kevinksullivan** [comment] 2024-04-29 21:59
Unable to reproduce, so I'm closing out!

**Closed by kevinksullivan** 2024-04-29 21:59 UTC
Labels: External, Engineering, Weekly, Help Wanted, Bug, retest-weekly
