### ISSUE TITLE
[HOLD for payment 2023-06-05] [$1000] Assign task- 404 error in the console appears when create a task

### ISSUE THREAD

**Issue by mvtglobally** [Expensify/App#19134] opened 2023-05-17 18:27 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Go to URL https://staging.new.expensify.com/
2. Login
3. Go to any #announce
4. Create a task

## Expected Result:
No errors in console

## Actual Result:
404 error in the console appears

## Workaround:
unknown 

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [X] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** v1.3.15-4
**Reproducible in staging?:** Y 
**Reproducible in production?:** Y 
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation 

![Bug6058823_Untitled](https://github.com/Expensify/App/assets/43995119/efbefcb9-364d-430e-ad90-ab94151f9160)

https://github.com/Expensify/App/assets/44479856/5fb0d74a-b670-4f99-ae2b-4233ac98669d

**Expensify/Expensify Issue URL:**
**Issue reported by:** Applause - Internal Team
**Slack conversation:**

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~012e1b763b4e7b70a1</li>
        <li>Upwork Job ID: 1658927033624666112</li>
        <li>Last Price Increase: 2023-05-19</li>
    </ul>
</details>

**Comment by conorpendergrast** [comment] 2023-05-17 20:02
Yep, reproduced! 

<img width="1440" alt="image" src="https://github.com/Expensify/App/assets/5802477/fecd50a7-a6a2-4385-a9c2-c9c567642fdc">

**Comment by conorpendergrast** [comment] 2023-05-17 20:06
@thienlnam I think this should be over to you! I'll label it Internal to get the ball rolling, and will also then assign you too

**Comment by conorpendergrast** [comment] 2023-05-17 20:06
If I'm wrong, let me know!

**Comment by thienlnam** [comment] 2023-05-19 19:10
The error is with AuthenticatePusher, not sure why that is showing up. The EditTask command should now be on production and so that error shouldn't be happening anymore

**Comment by thienlnam** [comment] 2023-05-19 19:11
I think we can have this external for someone to investigate

**Comment by phuchoang23** [comment] 2023-05-20 10:12
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
Assign task- 404 error in the console appears when create a task

### What is the root cause of that problem?
404 error is come from this API to authorize Pusher when our App need to subscribe to a socket channel.
<img width="696" alt="Screenshot 2023-05-20 at 16 03 44" src="https://github.com/Expensify/App/assets/9639873/2381b4a6-f186-4fc5-9b18-620b7fba6b0c">

I suspect the API to create Task (+ report) is not finished yet, then we navigate to taskReport in [this line](https://github.com/Expensify/App/blob/737862677811acc2b05c68209a56ecd58bee59f3/src/libs/actions/Task.js#L152)
The ReportScreen will load and it triggers this line to subscribe to private socket channels of the report
https://github.com/Expensify/App/blob/737862677811acc2b05c68209a56ecd58bee59f3/src/pages/home/report/ReportActionsView.js#L230-L233
=> Can cause 404 error because the create Task API is not finished yet (report is not created yet)

<details>
<summary>Screenshots when navigate to a newly chatReport and a  newly taskReport</summary>

- **newly taskReport**
<img width="696" alt="Screenshot 2023-05-20 at 14 19 10" src="https://github.com/Expensify/App/assets/9639873/c290ad52-ffc3-42c3-93ab-35e01d2f9a0c">

- **newly chatReport**
<img width="684" alt="Screenshot 2023-05-20 at 16 20 20" src="https://github.com/Expensify/App/assets/9639873/35ab4a6d-eddb-4e4c-94a1-17f378bc1fb3">

</details>

### What changes do you think we should make in order to solve the problem?
To solve this problem we need to ensure the taskReport is created successfully before subscribe to its private channels

**More details:**
We need to follow this condition:
https://github.com/Expensify/App/blob/737862677811acc2b05c68209a56ecd58bee59f3/src/pages/home/report/ReportActionsView.js#L225-L229
That means when build optimisticTaskReport data, we need to add `pendingFields.createChat` with  `CONST.RED_BRICK_ROAD_PENDING_ACTION.ADD` (and `isOptimisticReport: true` so it won't trigger OpenReport API when it's not ready).
```JS
                pendingFields: {
                    createChat: CONST.RED_BRICK_ROAD_PENDING_ACTION.ADD,
                },
                isOptimisticReport: true,
```
And reset those fields in `successData`.

We used this trick in some other places:
- [IOU chat](https://github.com/Expensify/App/blob/737862677811acc2b05c68209a56ecd58bee59f3/src/libs/actions/IOU.js#L433-L435)
- [ExpenseChats](https://github.com/Expensify/App/blob/main/src/libs/actions/Policy.js#L283-L284)
- [Normal report](https://github.com/Expensify/App/blob/737862677811acc2b05c68209a56ecd58bee59f3/src/libs/actions/Report.js#L379-L382)

Result:
<img width="688" alt="Screenshot 2023-05-20 at 16 10 17" src="https://github.com/Expensify/App/assets/9639873/19bebdd2-7cf1-4111-b83b-e9022d51ffed">

**Comment by conorpendergrast** [comment] 2023-05-22 09:16
Unassigning @laurenreidexpensify as I'm already assigned as BugZero

**Comment by conorpendergrast** [comment] 2023-05-23 10:23
[Asked in Slack](https://expensify.slack.com/archives/C02NK2DQWUX/p1684837412603729)

**Comment by thienlnam** [comment] 2023-05-23 18:25
Awesome - looks great thanks!

**Comment by phuchoang23** [comment] 2023-05-24 00:29
PR will ready in a couple hour

**Comment by phuchoang23** [comment] 2023-05-24 14:33
@aimane-chnaif @thienlnam  [PR](https://github.com/Expensify/App/pull/19513) is ready to review

**Comment by conorpendergrast** [comment] 2023-05-24 14:45
Checking that in [our internal Slack channel](https://expensify.slack.com/archives/C01SKUP7QR0/p1684939534851299)

**Comment by phuchoang23** [comment] 2023-05-24 14:51
look fine now. Thanks for supporting

**Comment by conorpendergrast** [comment] 2023-05-26 13:48
PR reviewed and on Staging

**Comment by conorpendergrast** [comment] 2023-06-06 19:51
Argh, Upwork isn't letting me hire on the existing job. I'll have to create new ones - tomorrow!

**Comment by conorpendergrast** [comment] 2023-06-07 12:35
Looks like this was merged in less than 3 business days, so adding a 50% urgency bonus for C and C+

**Comment by conorpendergrast** [comment] 2023-06-07 12:38
@aimane-chnaif contract sent via Upwork
@phuchoang23 Can you reply here with your Upwork profile URL please?

**Comment by conorpendergrast** [comment] 2023-06-07 13:49
I will shortly send the contract, yes!

**Comment by conorpendergrast** [comment] 2023-06-07 14:38
@phuchoang23 Paid!

**Comment by conorpendergrast** [comment] 2023-06-07 14:40
Alright, just [the BugZero checklist here](https://github.com/Expensify/App/issues/19134#issuecomment-1567590558)

**Comment by phuchoang23** [comment] 2023-06-08 02:19
@conorpendergrast Thanks 👍

**Comment by conorpendergrast** [comment] 2023-06-09 18:59
@aimane-chnaif Bump on [the BugZero checklist here](https://github.com/Expensify/App/issues/19134#issuecomment-1567590558) please!

**Comment by conorpendergrast** [comment] 2023-06-12 12:22
Got it. Sounds like we're all done. Closing, thanks all!

**Closed by conorpendergrast** 2023-06-12 12:22 UTC
Labels: External, Daily, Overdue, Awaiting Payment, Bug
