### ISSUE TITLE
Web - Room -Transition between Workspaces and Room is sluggish

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#33102] opened 2023-12-14 17:52 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.13.0
**Reproducible in staging?:** Y
**Reproducible in production?:** N 
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** Applause - Internal Team
**Slack conversation:**

## Action Performed:
Precondition: User is not a part of any workspace
1. Click FAB > Start chat
2. Go to Room
3. Click Learn more
4. Click back button

## Expected Result:
The transition between Workspaces and Room is smooth

## Actual Result:
The transition between Workspaces and Room is sluggish

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [x] Android: mWeb Chrome
- [ ] iOS: Native
- [x] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details> 

https://github.com/Expensify/App/assets/78819774/9455dafe-60d9-4c98-a026-4429dbb338fb

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by marcochavezf** [comment] 2023-12-14 20:55
I will be afk for one hour aprox, and will continue testing when I come back

**Comment by abzokhattab** [comment] 2023-12-14 21:03
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
Transitions between Tabs become laggy after a few clicks

### What is the root cause of that problem?

In the [new chat selector page](https://github.com/Expensify/App/blob/e87d35d8af177df33c4fdfbf221ead732efec310/src/pages/NewChatSelectorPage.js#L39-L57) we use the `TabSelector` component  as a prop inside the `OynxTabNavigator` component 

This `TabSelector` gets rerendered everytime we click on a tab so after some clicks, the transitions become very slow.

This issue affects all components that use the `TabSelector`

1. `NewChatSelectorPage`
2. `MoneyRequestSelectorPage
3. `IOURequestStartPage`

### What changes do you think we should make in order to solve the problem?

we need to use `React.memo` on the `TabSelectorItem`:
 
to do so we need to add this line:

```js
    const MemoizedTabSelectorItem = React.memo(TabSelectorItem);
```

and change this 
https://github.com/Expensify/App/blob/fa87f8bb98aa960f71584e188cbaee5c091bb0f0/src/components/TabSelector/TabSelector.js#L131
to 
```js
<MemoizedTabSelectorItem
```

**Comment by situchan** [comment] 2023-12-14 21:06
The root cause already exists in production so I don't think this is blocker.
Dupe of https://github.com/Expensify/App/issues/31190

**Comment by marcochavezf** [comment] 2023-12-14 23:16
Oh interesting, thanks @situchan, after reviewing the other issue I agree this is a dupe and not a blocker. I will close it out in favor of https://github.com/Expensify/App/issues/31190

**Closed by marcochavezf** 2023-12-14 23:16 UTC
Labels: DeployBlockerCash, Engineering, Hourly
