### ISSUE TITLE
[WAITING ON EUGENE] [$1000] Cursor jumps to next position when we use ',' in request money when language is English (or if using '.' in Spanish)

### ISSUE THREAD

**Issue by kavimuru** [Expensify/App#23933] opened 2023-07-31 16:13 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Open the app
2. Ensure that app language is English
3. Click on plus and click on request money / split bill
4. Add any amount, try to insert ',' (comma) in 2nd last or 3rd last position, app doesn't insert a cursor but jumps positions
5. Try to insert any other symbol like '=,+,|,?' in 2nd last or 3rd last position and app won't allow the symbol to insert but will keep the cursor position same
6. Switch to Spanish language mode.
7. Try to insert '.' (period) in 2nd last or 3rd last position and observe that app will jump the cursor one position ahead every time if the language is set to Spanish
## Expected Result: 
App should not change cursor position when we try to insert ',' in amount for English language OR '.' in amount for Spanish language in request money / split bill
## Actual Result: 
App changes cursor position when we try to insert ',' in amount for English language OR '.' in amount for Spanish language in request money / split bill

## Workaround:
Can the user still use Expensify without this being fixed? Have you informed them of the workaround?

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [x] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 1.3.47-3
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/43996225/ad83a9fc-21f8-462b-a7da-025dfe9093ba

https://github.com/Expensify/App/assets/43996225/c0adb229-0aff-4663-8dec-02684e0998d1

**Expensify/Expensify Issue URL:**
**Issue reported by:** @dhanashree-sawant
**Slack conversation:**  https://expensify.slack.com/archives/C049HHMV9SM/p1690268210124929

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01b976c4c3347bca34</li>
        <li>Upwork Job ID: 1686553611490000896</li>
        <li>Last Price Increase: 2023-08-09</li>
<li>Automatic offers: </li>
<ul>
<li>samh-nl | Contributor | 26109224</li>
<li>dhanashree-sawant | Reporter | 26109226</li>
</ul></li>
    </ul>
</details>

**Comment by jliexpensify** [comment] 2023-08-01 01:27
@kavimuru can you re-test on v1.3.48-0? I can't seem to enter a comma when requesting money or splitting a bill.

**Comment by jliexpensify** [comment] 2023-08-01 22:39
@samh-nl can you share a video? I can't get a cursor to show at all on my end :(

**Comment by kavimuru** [comment] 2023-08-02 01:31
@jliexpensify Here is the video.

https://github.com/Expensify/App/assets/43996225/e44cb2a1-9f50-48fc-b4fd-9b54a816388f

**Comment by servesh-chaturvedi** [comment] 2023-08-02 03:19
Hi, any particular reason for not using [International number format](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Intl/NumberFormat) for the amount?

**Comment by Surojd** [comment] 2023-08-02 04:49
## Proposal
 
**Please re-state the problem that we are trying to solve in this issue.**
Cursor jumps to next position when we use ',' in request money when language is English (or if using '.' in Spanish)


### What is the root cause of that problem?
The non-comma-stripped amount is used to update the cursor location before the comma is removed.
Because of this, the new cursor location is determined by the wrong (longer) value, causing it to advance to the following point.


[App/src/pages/iou/steps/MoneyRequestAmountPage.js](https://github.com/Expensify/App/src/pages/iou/steps/MoneyRequestAmountPage.js#L315-L318
 
```

 setAmount((prevAmount) => { 
     setSelection((prevSelection) => getNewSelection(prevSelection, prevAmount.length, newAmountWithoutSpaces.length)); 
     return stripCommaFromAmount(newAmountWithoutSpaces); 
 }); 
```
### What changes do you think we should make in order to solve the problem?
We should use the stripped amount for updating the cursor position, e.g.:

```
 const strippedAmount = stripCommaFromAmount(newAmountWithoutSpaces);
setSelection((prevSelection) => getNewSelection(prevSelection, prevAmount.length, strippedAmount.length));
return strippedAmount;
 
```
This also fixes it for the Spanish scenario.

### What alternative solutions did you explore? (Optional)
N/A


### Proof Video

https://github.com/Expensify/App/assets/10323306/02e7faeb-ff9c-47c4-be99-c5737dd5a09e

**Comment by Surojd** [comment] 2023-08-02 04:50
Contributor details
Expensify account email: [surojsmiling@gmail.com](mailto:surojsmiling@gmail.com)
Upwork Profile Link: https://www.upwork.com/freelancers/surojd

**Comment by Surojd** [comment] 2023-08-02 05:26
Contributor details
Your Expensify account email: surojsmiling@gmail.com
Upwork Profile Link: https://www.upwork.com/freelancers/surojd

**Comment by Surojd** [comment] 2023-08-02 05:28
## Proposal
 
**Please re-state the problem that we are trying to solve in this issue.**
Cursor jumps to next position when we use ',' in request money when language is English (or if using '.' in Spanish)


### What is the root cause of that problem?
The non-comma-stripped amount is used to update the cursor location before the comma is removed.
Because of this, the new cursor location is determined by the wrong (longer) value, causing it to advance to the following point.


[App/src/pages/iou/steps/MoneyRequestAmountPage.js](https://github.com/Expensify/App/src/pages/iou/steps/MoneyRequestAmountPage.js#L315-L318
 
```

 setAmount((prevAmount) => { 
     setSelection((prevSelection) => getNewSelection(prevSelection, prevAmount.length, newAmountWithoutSpaces.length)); 
     return stripCommaFromAmount(newAmountWithoutSpaces); 
 }); 
```
### What changes do you think we should make in order to solve the problem?
We should use the stripped amount for updating the cursor position, e.g.:

```
 const strippedAmount = stripCommaFromAmount(newAmountWithoutSpaces);
setSelection((prevSelection) => getNewSelection(prevSelection, prevAmount.length, strippedAmount.length));
return strippedAmount;
 
```
This also fixes it for the Spanish scenario.

### What alternative solutions did you explore? (Optional)
N/A


### Proof Video

https://github.com/Expensify/App/assets/10323306/02e7faeb-ff9c-47c4-be99-c5737dd5a09e

**Comment by jliexpensify** [comment] 2023-08-06 23:06
Bump @0xmiroslav - there are a few proposals to review!

**Comment by jliexpensify** [comment] 2023-08-10 01:35
Going to reassign this one.

**Comment by jliexpensify** [comment] 2023-08-10 01:36
Hi @eVoloshchak - can you help us out here? I've just reassigned and you're the lucky C+, cheers!

**Comment by eVoloshchak** [comment] 2023-08-10 19:18
@samh-nl's [proposal](https://github.com/Expensify/App/issues/23933#issuecomment-1658745658) was the first to correctly identify the root cause and propose a fix, looks good to me, I think we should proceed with it

🎀👀🎀 C+ reviewed!

**Comment by danieldoglas** [comment] 2023-08-14 09:47
@samh-nl assigned!

**Comment by eVoloshchak** [comment] 2023-08-17 11:53
@samh-nl, could you open the PR when you have time?  Thanks

**Comment by danieldoglas** [comment] 2023-08-21 15:19
> What would you recommend for testing mobile, use the keys present on the number pad?

If in mobile we can't see those, it's ok to show just our custom number pad and that it works normally.

**Comment by jliexpensify** [comment] 2023-09-06 02:37
Payment summary:

- Bug Reporter: @dhanashree-sawant $250
- Contributor: @samh-nl $1000
- C+: @eVoloshchak $1000 (New.Dot payment)

[Upwork job](https://www.upwork.com/jobs/~01b976c4c3347bca34)

@eVoloshchak can you complete the checklist? Thanks!

**Comment by jliexpensify** [comment] 2023-09-07 02:34
Bumping @eVoloshchak to complete the checklist please!

**Comment by jliexpensify** [comment] 2023-09-08 02:00
Paid in Upoworks, job removed. @eVoloshchak friendly bump to complete the checklist before we issue you payment, thanks!

**Comment by eVoloshchak** [comment] 2023-09-08 06:14
- The PR that introduced the bug has been identified. Link to the PR: https://github.com/Expensify/App/pull/23979
- The offending PR has been commented on, pointing out the bug it caused and why, so the author and reviewers can learn from the mistake. Link to comment: https://github.com/Expensify/App/pull/23979/files#r1319408939
- A discussion in #expensify-bugs has been started about whether any other steps should be taken (e.g. updating the PR review checklist) in order to catch this type of bug sooner. Link to discussion: It's a fairly simple bug, I don't think an additional discussion is necessary

**Comment by eVoloshchak** [comment] 2023-09-08 06:17
**Regression Test Proposal**

1. Click on the FAB -> Request money
2. Enter 10.00
3. Move the cursor near the start
4. Press comma and dot (web/desktop) or press the comma/dot in the number pad (mobile)
5. Verify that the cursor does not move
6. Go to Settings > Preferences > Language and change language to Spanish
7. Click on the FAB
8. Click on Request money
9. Enter 10,00
10. Move the cursor near the start
11. Press comma and dot (web/desktop) or press the comma/dot in the number pad (mobile)
12. Verify that the cursor does not move

**Do we agree 👍 or 👎**

**Comment by JmillsExpensify** [comment] 2023-09-10 10:14
Reviewed the details for @eVoloshchak. $1,000 approved for payment via NewDot based on BZ summary.

**Closed** 2023-09-10 11:25 UTC
Labels: External, Engineering, Daily, Overdue, Awaiting Payment, Bug
