### ISSUE TITLE
[HOLD for payment 2023-05-25] [$1000] 2FA code does not submit when user refreshes sign in page.

### ISSUE THREAD

**Issue by kavimuru** [Expensify/App#18505] opened 2023-05-05 19:59 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:

1. Pre requisite: 2FA must be enabled.
2. Go to ND.
3. Enter your email, click on Sign In.
4. Enter the magic code. See that you will be shown the 2FA code input next.
5. Refresh the page.
6. Enter the 2FA code.
7. Notice that you are unable to enter the code.

## Expected Result: 
User should be able to enter the 2FA code even if they refresh the page.
## Actual Result: 
Unable to submit 2FA code if page is refreshed.
## Workaround:
Can the user still use Expensify without this being fixed? Have you informed them of the workaround?

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [x] Android / Chrome
- [] iOS / native
- [x] iOS / Safari
- [x] MacOS / Chrome / Safari
- [x] MacOS / Desktop

**Version Number:** 1.3.11.4 
**Reproducible in staging?:** y
**Reproducible in production?:**  y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation

https://user-images.githubusercontent.com/43996225/236557527-7275774c-908c-403f-898e-e05c73e4f688.mp4

https://user-images.githubusercontent.com/43996225/236557533-d9d29eab-a132-4aa6-9b54-3c7750f8322b.mp4

**Expensify/Expensify Issue URL:**
**Issue reported by:** @Prince-Mendiratta 
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1683268611061139

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01d663093b8fe6de5e</li>
        <li>Upwork Job ID: 1654592573388144640</li>
        <li>Last Price Increase: 2023-05-08</li>
    </ul>
</details>

**Comment by joekaufmanexpensify** [comment] 2023-05-05 20:55
Reproduced on web. This def feels like a bug.

**Comment by joekaufmanexpensify** [comment] 2023-05-05 21:05
Given this relates to either passwordless or 2FA, thinking this will need to be internal.

**Comment by joekaufmanexpensify** [comment] 2023-05-05 21:17
Hm, not sure why this didn't assign an internal engineer too.

**Comment by joekaufmanexpensify** [comment] 2023-05-05 21:18
@tgolen thinking this one needs to be internal, but LMK if that's not the case, and happy to swap to external!

**Comment by tgolen** [comment] 2023-05-08 13:20
I agree that this likely isn't an internal issue and can be handled by a contributor and we can start evaluating proposals.

**Comment by tgolen** [comment] 2023-05-08 13:21
@Prince-Mendiratta do you know if this is a regression or if it's always been this way?

**Comment by joekaufmanexpensify** [comment] 2023-05-08 16:18
@Christinadobrzyn not sure why the external label added a second bug zero assignee, but I can keep this one, so unassigned you!

**Comment by tgolen** [comment] 2023-05-09 13:34
OK, thank you! I have changed it from Bug to NewFeature to reflect that it's new functionality that needs to be built. I think the proposal from @Prince-Mendiratta makes sense and the resulting logic would be very clear. @sobitneupane what do you think?

**Comment by sobitneupane** [comment] 2023-05-10 10:00
[Proposal](https://github.com/Expensify/App/issues/18505#issuecomment-1536801268) from @Prince-Mendiratta looks good to me.

🎀👀🎀 C+ reviewed
cc: @tgolen

**Comment by tgolen** [comment] 2023-05-10 17:52
@joekaufmanexpensify you have the 🟢 to hire @Prince-Mendiratta for this.

**Comment by joekaufmanexpensify** [comment] 2023-05-10 18:53
Sounds good!

**Comment by NikkiWines** [comment] 2023-05-11 13:38
> Anyways, it looks like sending just the 2FA code to the backend will not work, we need to send the magic code as well for it to work properly. @tgolen Can you please look into this and confirm if this is indeed the case?

This is correct, you need to send both 👍

**Comment by joekaufmanexpensify** [comment] 2023-05-24 19:05
Since there was a new feature issue, there's no reporting bonus on this one.

**Comment by joekaufmanexpensify** [comment] 2023-05-24 19:07
Further, given this was not a bug, there is no BZ checklist to complete.

**Comment by joekaufmanexpensify** [comment] 2023-05-24 19:07
@Prince-Mendiratta offer sent!

**Comment by joekaufmanexpensify** [comment] 2023-05-24 19:08
@sobitneupane offer sent!

**Comment by joekaufmanexpensify** [comment] 2023-05-24 22:13
In relation to the speed bonus comment [here](https://github.com/Expensify/App/issues/18505#issuecomment-1553490542), I discussed this internally, and confirmed that new feature issues are not eligible for speed bonus. We appreciate the urgency on this issue though!

**Comment by joekaufmanexpensify** [comment] 2023-05-24 22:13
I'll issue payment tomorrow.

**Comment by joekaufmanexpensify** [comment] 2023-05-25 12:58
@Prince-Mendiratta $1,000 sent and contract ended!

**Comment by joekaufmanexpensify** [comment] 2023-05-25 12:59
New feature implemented, and all payment issued. Closing as this is all set. Thanks everyone!

**Comment by joekaufmanexpensify** [comment] 2023-05-25 15:04
Generally, my understanding is if we previously did not build something, then adding it in the future would be considered a new feature, rather than a bug. I'd defer to @tgolen though, as Tim added the new feature label here.

**Comment by sobitneupane** [comment] 2023-05-25 15:16
I agree with @Prince-Mendiratta. It's a bug. The issue here is "After 2FA page is refreshed, clicking Sign in button doesn't trigger `onpress` event". The bug was present in following code:

https://github.com/Expensify/App/blob/aa6bd411a4122bb72ce25cde206dffb7bb7f7697/src/pages/signin/ValidateCodeForm/BaseValidateCodeForm.js#L166-L169

**Comment by tgolen** [comment] 2023-05-25 15:23
Yes, this can get very pedantic about what is a bug and what is a new feature. Let's say you have some validation rules on an input, but there was a validation case that was missed in the original code (maybe like max-length). Is that a bug, or is it a new feature to add the new validation? It could be said either way depending on how you look at it. I think this is similar. I will not fight either way on this one.

**Comment by joekaufmanexpensify** [comment] 2023-05-26 20:45
Got it, thanks for chiming in! I'm fine to treat this one as a bug as well, given the expected behavior is that you'd always be able to enter a 2FA code.

**Comment by joekaufmanexpensify** [comment] 2023-05-26 20:47
That means on top of what was already paid, we need to pay: 

- @Prince-Mendiratta - $750 ($250 for reporting the bug, and $500 for the speed bonus on the PR.) 
- @sobitneupane - $500 for speed bonus on the PR.

**Comment by joekaufmanexpensify** [comment] 2023-05-26 20:49
Created new upwork job post, as i closed the other one: https://www.upwork.com/jobs/~01b5934799e03b4e73

**Comment by joekaufmanexpensify** [comment] 2023-05-26 20:50
@Prince-Mendiratta offer sent for $750!

**Comment by joekaufmanexpensify** [comment] 2023-05-26 20:50
@sobitneupane offer sent for $500!

**Comment by joekaufmanexpensify** [comment] 2023-05-26 20:52
Added additional assignee as I'm OOO next week (through June 5th). The bug is fixed here, all we need to do is pay the two payments listed [here](https://github.com/Expensify/App/issues/18505#issuecomment-1564930424). 

We're paying these as we belatedly decided this was a bug (rather than new feature), so we need to pay the speed bonus, and reporting bonus.

**Comment by tgolen** [comment] 2023-05-30 05:40
Not overdue and waiting for payments.

**Comment by twisterdotcom** [comment] 2023-05-30 23:01
All paid out.

**Closed by twisterdotcom** 2023-05-30 23:01 UTC
Labels: External, Engineering, Daily, Awaiting Payment, Bug
