### ISSUE TITLE
Two self DMs are appearing in the LHN

### ISSUE THREAD

**Issue by m-natarajan** [Expensify/App#44756] opened 2024-07-03 01:00 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 9.0.3-6
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** @shubham1206agra 
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1719848628407209

## Action Performed:
1. open app
2. observe the LHN
## Expected Result:
Chat shouldn't be duplicated
## Actual Result:
2 self DMs 
2 expensify chat appears
## Workaround:
unknown
## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

https://github.com/Expensify/App/assets/38435837/e54b2da2-dd84-42d7-97ad-e99ad3e27861

![image (41)](https://github.com/Expensify/App/assets/38435837/5f8f3cbb-5be4-4279-b098-149708998e21)

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by mallenexpensify** [comment] 2024-07-03 22:08
Might be a dupe of https://github.com/Expensify/App/issues/44783

**Comment by puneetlath** [comment] 2024-07-08 21:49
@shubham1206agra can you share what you see in Onyx for the two duplicate reports?

**Comment by puneetlath** [comment] 2024-07-16 17:38
@shubham1206agra bump! Are you still experiencing this and if so can you share what you have in Onyx for the two reports?

**Comment by puneetlath** [comment] 2024-07-23 19:49
@shubham1206agra are you still able to repro this in any other account? I'm not able to, so I'm curious if it was a one-off issue or something re-occurring.

**Comment by puneetlath** [comment] 2024-07-29 14:28
I'm going to close this out as it doesn't seem to be happening any longer. Let me know if I'm mistaken in that @shubham1206agra and I can reopen.

**Closed by puneetlath** 2024-07-29 14:28 UTC
Labels: Daily, Overdue, Bug
