### ISSUE TITLE
[HOLD for payment 2022-09-02] [$250] The unpin tooltip is clipped on Desktop

### ISSUE THREAD

**Issue by mvtglobally** [Expensify/App#9331] opened 2022-06-07 04:16 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Open any chat
2. Pin 
3. hover over the pin icon 

## Expected Result:
Text should be visible 

## Actual Result:
Text is not visible when hover over unpin 

## Workaround:
Can the user still use Expensify without this being fixed? Have you informed them of the workaround?

## Platform:

Where is this issue occurring?

- Desktop App

**Version Number:** 1.1.71-0
**Reproducible in staging?:** Y 
**Reproducible in production?:** Y 
**Email or phone of affected tester (no customers):** 
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation 
<img width="175" alt="Screen Shot 2022-06-03 at 10 23 14 AM" src="https://user-images.githubusercontent.com/43995119/172294796-aa8ef2de-a5de-4261-a1f8-b95fe22079dd.png">

**Upwork URL:** https://www.upwork.com/jobs/~010348882227b38f44
**Issue reported by:** @Tushu17 
**Slack conversation:** https://expensify.slack.com/archives/C01GTK53T8Q/p1654273654678949

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by Tushu17** [comment] 2022-06-07 16:30
Hey, I've reported this bug before on [slack](https://expensify.slack.com/archives/C01GTK53T8Q/p1652971168939839).

**Comment by luacmartins** [comment] 2022-06-08 00:04
@mvtglobally can you update the issue reporter to @Tushu17, since he mentioned it first? Thank you!

**Comment by arosiclair** [comment] 2022-06-08 01:58
Clear instructions and seems like low-hanging fruit for a contributor. Marking as external.

**Comment by trjExpensify** [comment] 2022-06-09 13:58
Job posted to upwork here: https://www.upwork.com/jobs/~010348882227b38f44

**Comment by mananjadhav** [comment] 2022-06-10 21:45
@stitesExpensify, Yeah, the issue is if the tooltip is open and we change the text, its width doesn't change. @sobitneupane's proposal looks good. 

@sobitneupane While I appreciate the spontaneous solutions, please wait for the issue to get triaged before posting the proposals. 

🎀 👀 🎀 
C+ reviewed

**Comment by stitesExpensify** [comment] 2022-06-10 22:07
I agree that @sobitneupane proposal looks good!

**Comment by sobitneupane** [comment] 2022-06-14 02:43
> @sobitneupane did you apply to the job here? https://www.upwork.com/jobs/~010348882227b38f44

Applied.

**Comment by mananjadhav** [comment] 2022-06-16 07:19
@sobitneupane Do you have any PR for me to look at for this one?

**Comment by adeel0202** [comment] 2022-06-29 12:43
The fix for this bug has been deployed to production but I'm still able to reproduce this on Safari. Shall I report it on slack or just reporting here is enough?
cc: @stitesExpensify @mananjadhav

**Comment by stitesExpensify** [comment] 2022-06-29 16:28
Hm that's not great.. @sobitneupane can you confirm this is fixed on safari, and create a fix if it is not? In the mean time we will hold on payment @trjExpensify

**Comment by stitesExpensify** [comment] 2022-06-29 16:29
Thanks for bringing this up @adeel0202

**Comment by trjExpensify** [comment] 2022-06-29 16:30
Removed the label and edited the title for the time being.

**Comment by mananjadhav** [comment] 2022-06-30 19:26
It looks there is an impact due to the change. It fixed the cropping issue of the tooltip , just wraps the text on two lines. When I tested I presumed it must be because the tooltip is at the extreme right of the window. But now that I've checked an existing pinned item tooltip, it is on one line.

**Comment by mananjadhav** [comment] 2022-07-05 19:05
@sobitneupane Were you able to check the above messages?

**Comment by mananjadhav** [comment] 2022-07-20 20:57
@sobitneupane Did you get a chance to look at this?

**Comment by mananjadhav** [comment] 2022-07-24 16:46
@sobitneupane Quick reminder. @stitesExpensify Will wait for 1-2 days else I'll raise a fix for this issue.

**Comment by trjExpensify** [comment] 2022-08-18 12:00
@mananjadhav @sobitneupane @stitesExpensify what's going on with this issue, it's a tad unclear on the next steps?

**Comment by mananjadhav** [comment] 2022-08-18 14:27
@trjExpensify Thanks for the bump. We haven't heard from @sobitneupane  and I guess its a small fix, let me raise a PR for the fix by today/tomorrow.

**Comment by trjExpensify** [comment] 2022-08-18 15:52
Thank you, @mananjadhav.

**Comment by mananjadhav** [comment] 2022-08-23 22:43
@stitesExpensify @trjExpensify PR Raised.

**Comment by sobitneupane** [comment] 2022-09-01 11:25
Thanks @mananjadhav for handling the issue. I was away last two months. And Sorry for the inconvenience.

**Comment by adeel0202** [comment] 2022-09-05 09:01
Hi, I reported the bug [here](https://github.com/Expensify/App/issues/9331#issuecomment-1169933927) when it was supposed to be fixed and was in production. Am I eligible for the reporting bonus?
cc: @stitesExpensify @trjExpensify

**Comment by trjExpensify** [comment] 2022-09-05 09:20
Okay, can I get some clarity over what's due here and to whom? Here's my take.. 

$250 - @sobitneupane for the fix 
$250 - @Tushu17 for the original reporting 
$250 - @mananjadhav for C+ 
$250 - @adeel0202 for reporting the safari issue 

Let me know if that's correct and I'll raise a new job on Upwork because the previous one has lapsed, and no contracts were started here.

**Comment by mananjadhav** [comment] 2022-09-05 09:23
@trjExpensify There was a regression on the issue, which should deduct the amount for C+, but I would appreciate if can add an exception for this one as I put additional efforts in fixing the regression myself.

**Comment by trjExpensify** [comment] 2022-09-05 09:27
Yeah, you fixed it, so I kept that in. 👍 

Okay, job is here to apply everyone: https://www.upwork.com/jobs/~01e6c7617b3537f422

**Comment by trjExpensify** [comment] 2022-09-05 12:54
@mananjadhav & @adeel0202 - paid! 
@sobitneupane - offer sent
@Tushu17 - waiting for you to apply.

**Comment by trjExpensify** [comment] 2022-09-05 13:10
@sobitneupane - paid.

**Comment by trjExpensify** [comment] 2022-09-06 10:26
@Tushu17 - offer sent.

**Comment by Tushu17** [comment] 2022-09-06 12:00
@trjExpensify offer accepted. Thank you.

**Comment by trjExpensify** [comment] 2022-09-06 13:57
@Tushu17 - paid. Closing this out! 🎉

**Closed by trjExpensify** 2022-09-06 13:57 UTC
Labels: Reviewing, Exported, External, Engineering, Daily, Awaiting Payment
