### ISSUE TITLE
[HOLD for payment 2024-07-22] [HOLD for payment 2024-07-17] [$250] [FT] Add deeplinks to workspace editor in the onboarding checklist tasks

### ISSUE THREAD

**Issue by LLPeckham** [Expensify/App#44017] opened 2024-06-19 16:24 UTC
**Problem:** In the onboarding checklist for new users on New Expensify, there are a handful of directions on each task that require a member to switch between the task's instructions and actually getting to the place in the product that the instructions mention. 

**Solution:** Let's add a deeplink directly to the member's workspace editor so that they can more easily follow the instructions and skip a few steps to get the task completed. 

**Context:** 
To get to the screen(s) we want to add deeplinks to: A new user signs up, selects "Manage my team's expenses" in the intent selection modal >  enters their business name in "where do you work" > Enters their name in "what's your name" > clicks "Get Started" on the onboarding video modal > Then, the user is shown the onboarding checklist. There are 3 tasks that require navigating to the workspace editor where we would add a deeplink directly to the member's workspace. 

**Where the deeplink should go:**
The three onboarding tasks that should include a deeplink: "Set up categories", "Add expense approvals", and "Invite your team"

As you can see in the screenshot attached below, step 2 for each of the 3 tasks mentioned above is where we can include a deeplink to the workspace editor: 

2. Go to Workspaces > [your workspace] `[your workspace]` should be where the deeplink to the workspace editor is located. Also, note that the link should be using the production URL. 

<img width="758" alt="Screenshot 2024-06-19 at 4 12 41 PM" src="https://github.com/Expensify/App/assets/6799061/1b808735-5bbc-44db-90db-f2382450fd84">

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~0142e3df4eaf0fbe54</li>
        <li>Upwork Job ID: 1803466601509407666</li>
        <li>Last Price Increase: 2024-06-19</li>
<li>Automatic offers: </li>
<ul>
<li>shubham1206agra | Reviewer | 102855462</li>
<li>nkdengineer | Contributor | 102855466</li>
</ul></li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @johncschuster</details>

**Comment by nkdengineer** [comment] 2024-06-19 17:35
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
We want to add deeplinks to workspace editor in the onboarding checklist tasks

### What is the root cause of that problem?
This is a new feature

### What changes do you think we should make in order to solve the problem?

Here're the locations we need to add the deep link:
- https://github.com/Expensify/App/blob/de66757deda02a556923a991bd7715134d94c47e/src/CONST.ts#L3917
- https://github.com/Expensify/App/blob/de66757deda02a556923a991bd7715134d94c47e/src/CONST.ts#L3934
- https://github.com/Expensify/App/blob/de66757deda02a556923a991bd7715134d94c47e/src/CONST.ts#L3951

We use the same way as in https://github.com/Expensify/App/blob/de66757deda02a556923a991bd7715134d94c47e/src/CONST.ts#L3902 where we extrapolate the deep link into the description

First we update the `description` [here](https://github.com/Expensify/App/blob/de66757deda02a556923a991bd7715134d94c47e/src/CONST.ts#L3911) to be a function that will allow a `workspaceLink` param
```
description: ({workspaceLink}: {workspaceLink: string}) => 
```

Then in https://github.com/Expensify/App/blob/de66757deda02a556923a991bd7715134d94c47e/src/CONST.ts#L3917, add the deeplink to the appropriate place. Based on the OP it looks like `*Workspaces* > [your workspace]` will be the text content of the deeplink (this can be changed easily upon request)
```
`2. Go to [*Workspaces* > [your workspace]](${workspaceLink}).\n` +
```

We need to make the `onboardingPolicyID` available as data [here](https://github.com/Expensify/App/blob/de66757deda02a556923a991bd7715134d94c47e/src/pages/OnboardingPersonalDetails/BaseOnboardingPersonalDetails.tsx#L196)
```
onboardingPolicyID: {
    key: ONYXKEYS.ONBOARDING_POLICY_ID,
},
```
(can use `useOnyx` too)
Then pass the `onboardingPolicyID` to [here](https://github.com/Expensify/App/blob/de66757deda02a556923a991bd7715134d94c47e/src/pages/OnboardingPersonalDetails/BaseOnboardingPersonalDetails.tsx#L56)

Now we can construct the deep link and put to the `workspaceLink` of the description, in [there](https://github.com/Expensify/App/blob/de66757deda02a556923a991bd7715134d94c47e/src/libs/actions/Report.ts#L3176)
```
workspaceLink: `${CONFIG.EXPENSIFY.NEW_EXPENSIFY_URL}${ROUTES.WORKSPACE_INITIAL.getRoute(onboardingPolicyID)}`,
```

### What alternative solutions did you explore? (Optional)

**Comment by mountiny** [comment] 2024-06-20 21:51
@shubham1206agra Yes, I believe this should be available for external contributors. correct me if I am wrong but we have
- policyID of the policy created during onboarding
- We can set the text optimistically such that the backend respects it and creates the description based on that
- this way we can include a correct deeplink

**Comment by Julesssss** [comment] 2024-06-21 09:24
> Triggered auto assignment to @Julesssss, see https://stackoverflow.com/c/expensify/questions/7972 for more details.

Ignoring, @mountiny is the assigned engineer here.

**Comment by mountiny** [comment] 2024-06-24 13:43
@nkdengineer can you please raise a PR?

**Comment by johncschuster** [comment] 2024-06-24 20:42
This isn't overdue. It was just assigned to @nkdengineer

**Comment by nkdengineer** [comment] 2024-06-25 02:30
I'll raise PR soon

**Comment by nkdengineer** [comment] 2024-06-25 04:07
@shubham1206agra this [PR](https://github.com/Expensify/App/pull/44367) is ready for review

**Comment by johncschuster** [comment] 2024-07-10 13:54
Acknowledged! I will pay this out after the regression threshold is crossed 👍

**Comment by johncschuster** [comment] 2024-07-16 13:38
@mountiny I noticed in the PR that the fix seemed to be deployed _again_ to prod (first deploy: July 10, second deploy: July 15). Do I need to wait until the 22nd to pay this out, or am I safe to release payment on July 17?

**Comment by johncschuster** [comment] 2024-07-17 14:31
Ah, it looks like our deploy process may be broken ([Slack](https://expensify.slack.com/archives/C01SKUP7QR0/p1721171565737339)). I'm issuing payment today.

**Comment by johncschuster** [comment] 2024-07-17 14:32
I've issued payment to @nkdengineer. @shubham1206agra, can you please accept the linked job above so I can issue payment to you? Thank you!

**Comment by johncschuster** [comment] 2024-07-18 13:50
Thank you! I've just issued payment. Do you think we need a regression test suite for this? If so, can you propose one?

**Closed** 2024-07-19 14:43 UTC
Labels: External, Daily, Planning, NewFeature, Awaiting Payment
