### ISSUE TITLE
[$1000] Web - User avatar is still shown after thread reply has been removed after being flagged

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#22072] opened 2023-07-02 20:01 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:

1. Send a message from account A to account B
2. Reply in thread from account B
3. Go over to account A and click on the reply button > click the flag icon
4. Flag the comment sent from account B as `harassment` and wait for the comment to be removed
5. Go back to the original chat and observe the reply button

## Expected Result:
The reply button and the avatar should be removed since Account B's reply has been removed after flagging

## Actual Result:
The 1 Reply message and the avatar is still being shown after being removed because of being flagged

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [X] Android / native
- [X] Android / Chrome
- [X] iOS / native
- [X] iOS / Safari
- [x] MacOS / Chrome / Safari
- [X] MacOS / Desktop

**Version Number:** 1.3.35-5
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/93399543/f8a60f61-1b19-4676-b8db-aefb91c898da

https://github.com/Expensify/App/assets/93399543/d1547512-bc9a-471c-bb9d-32d90c125b10

<img width="1164" alt="image" src="https://github.com/Expensify/App/assets/51066321/36fd9bad-2374-43e1-a11a-3a7a2d6d2c6d">

**Expensify/Expensify Issue URL:**
**Issue reported by:** @Nathan-Mulugeta

**Slack :** https://expensify.slack.com/archives/C049HHMV9SM/p1688210429646659

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01300081e9977f4be7</li>
        <li>Upwork Job ID: 1677450382203498496</li>
        <li>Last Price Increase: 2023-07-14</li>
    </ul>
</details>

**Comment by Christinadobrzyn** [comment] 2023-07-05 20:57
I can reproduce but I think it's related to https://github.com/Expensify/App/issues/21497

Holding until regression in https://github.com/Expensify/App/issues/21497 is fixed to see if this is resolved.

**Comment by ygshbht** [comment] 2023-07-08 15:45
![image](https://github.com/Expensify/App/assets/65986357/098937df-c45c-4242-9c1e-35ad24df8283)
FIle `ReportActionItem.js`. This data that is fetched from backend will have to updated by the backend to exlude message that are flagged. Or if frontend only solution is required. I can fetch the child report and then figure out what data to show.

**Comment by Christinadobrzyn** [comment] 2023-07-10 20:59
Reviewing and receiving proposals! cc @Santhosh-Sellavel

**Comment by Santhosh-Sellavel** [comment] 2023-07-11 21:32
@ygshbht Can you write a formal proposal please

**Comment by 0rdep** [comment] 2023-07-13 22:33
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
The user's avatar is still displayed in thread replies even after messages have been deleted.

### What is the root cause of that problem?
Endpoint `/api?command=OpenReport` returns the accountID of the deleted message User on `childOldestFourAccountIDs` even after the message is deleted.

### What changes do you think we should make in order to solve the problem?
If we can´t change backend code to filter out the accountIds that are not in the thread anymore, we can add a new method to get the accountIds for a specific report thread on https://github.com/Expensify/App/blob/main/src/libs/ReportActionsUtils.js
```
/**
 *
 * @param {String} reportID
 * @returns {Number[]}
 */
function getThreadAccountIds(reportID) {
    const threadActions = lodashGet(allReportActions, [reportID]);
    const chatActions = _.filter(
        threadActions,
        (action) => action.actionName === CONST.REPORT.ACTIONS.TYPE.ADDCOMMENT && !isPendingRemove(action) && action.actorAccountID !== CONST.ACCOUNT_ID.CONCIERGE,
    );

    return _.uniq(_.map(chatActions, (action) => action.actorAccountID));
}
```

And use it on ReportActionItem.js
https://github.com/Expensify/App/blob/22b9aa44406880bae1432552be3466337f3490ba/src/pages/home/report/ReportActionItem.js#L340
Change to:
`const oldestFourAccountIDs = ReportActionsUtils.getThreadActors(props.action.childReportID).slice(0, 4);`

### What alternative solutions did you explore? (Optional)
Do the change on backend code to fix `childOldestFourAccountIDs` field on report, filtering out accountIds that are not in the thread anymore.

**Comment by 0rdep** [comment] 2023-07-13 22:35
Contributor details
Your Expensify account email: pedro.p.santos@outlook.com.br
Upwork Profile Link: https://www.upwork.com/freelancers/~0172e10cd6c14a9a95

**Comment by Santhosh-Sellavel** [comment] 2023-07-14 16:07
I think the change in the backend is the way to go here based on this [proposal](https://github.com/Expensify/App/issues/22072#issuecomment-1635001495). 

Marking reviewed to get a CME

C+ Reviewed
🎀 👀 🎀

**Comment by Santhosh-Sellavel** [comment] 2023-07-14 16:09
@srikarparsi

I think the change in the backend is the way to go here, Let us know your thoughts on this [proposal](https://github.com/Expensify/App/issues/22072#issuecomment-1635001495.) too. Thanks!

**Comment by Christinadobrzyn** [comment] 2023-07-14 18:30
I'm going to be ooo until August 31st so going to unassign and assign a new teammate. 

At this time, we're receiving and reviewing proposals and maybe accepting this https://github.com/Expensify/App/issues/22072#issuecomment-1636071202

**Comment by srikarparsi** [comment] 2023-07-17 08:41
Thanks @Santhosh-Sellavel and @0rdep! The backend change seems like the right approach to me as well but I will look more into the code tomorrow and update the issue.

**Comment by srikarparsi** [comment] 2023-07-20 03:38
Working on familiarizing myself with the backend code with threads. Should have a draft PR up by end of week.

**Comment by Santhosh-Sellavel** [comment] 2023-07-23 20:14
Not overdue waiting for @srikarparsi

**Comment by srikarparsi** [comment] 2023-07-25 03:54
Looked over the test steps and I agree that this should be a backend fix. I should have a PR out on Wednesday.

**Comment by srikarparsi** [comment] 2023-07-27 07:04
Hey! Worked on this a little today and will test/push tomorrow.

**Comment by zanyrenney** [comment] 2023-07-31 09:41
Thanks @srikarparsi - what is the latest on this for this week please?

**Comment by srikarparsi** [comment] 2023-07-31 22:21
Tested and investigated more and found out that it's not a problem with the user avatar but rather the [hasReplies](https://github.com/Expensify/App/blob/main/src/pages/home/report/ReportActionItem.js#L370) line. I'm looking into a fix in Auth since the childVisibleActionCount should be 0 if there's only one comment and it's been reported.

https://github.com/Expensify/App/assets/48188732/f4f2074c-aa5d-46ba-b9fb-756629a33552

**Comment by srikarparsi** [comment] 2023-08-03 20:54
Auth PR deployed, web pr reviewed and needs to get merged.

**Comment by srikarparsi** [comment] 2023-08-09 05:03
Tested on production and it looks good. This is ready to be closed out @Christinadobrzyn if there is no payment needed

https://github.com/Expensify/App/assets/48188732/ea6b50d4-702f-40c4-9649-2792d483d622

**Comment by Nathan-Mulugeta** [comment] 2023-08-09 05:34
Reporting bonus has not been processed yet.

**Comment by Nathan-Mulugeta** [comment] 2023-08-10 08:34
Hey @Christinadobrzyn can payment be processed for this issue? Thanks

**Comment by Christinadobrzyn** [comment] 2023-08-10 15:33
@Santhosh-Sellavel can you confirm you're paid through New Expensify? If that's true, I'll close out the Upwork job posting and this GH.

**Comment by Christinadobrzyn** [comment] 2023-08-10 23:44
Thanks for confirming @Santhosh-Sellavel - updated the payment [here](https://github.com/Expensify/App/issues/22072#issuecomment-1673459469)

Closing the job in Upwork and this GH. Feel free to let me know if I'm missing anything!

**Closed by Christinadobrzyn** 2023-08-10 23:44 UTC
Labels: Engineering, Daily, Internal, Bug
