### ISSUE TITLE
[$500] Distance-In receipt, finish address shown is different from the address entered

### ISSUE THREAD

**Issue by izarutskaya** [Expensify/App#31613] opened 2023-11-21 11:05 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.1-4
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** Applause-Internal Team
**Slack conversation:** @

## Action Performed:
1. Launch app
2. Tap on a workspace
3. Tap plus near compose----Request money
4. Tap Distance
5. Enter Duplicate(same)start and finish waypoints
6. Tap add stop
7. Enter a different address
8. Tap add stop again
9. Add same "add stop" address which is entered in step 7
10. Tap next
11. Tap distance amount
12. Tap distance request created to open distance request details page
13. Tap receipt
14. Note the waypoints displayed in receipt page

## Expected Result:
The waypoints entered while creating distance request must be displayed in receipt.

## Actual Result:
In receipt page, the finish address shown is different from the address entered while creating distance request.

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [x] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

https://github.com/Expensify/App/assets/115492554/eb7b4b9d-e1d7-41bb-b521-8408090dba1e

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~019b70146b213c00f1</li>
        <li>Upwork Job ID: 1726919846086856704</li>
        <li>Last Price Increase: 2023-11-21</li>
    </ul>
</details>

**Comment by DylanDylann** [comment] 2023-11-21 11:17
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
Distance-In receipt, finish address shown is different from the address entered
### What is the root cause of that problem?
In this case, the optimistic data waypoints  will be: A->A->B->B
The data is returned from BE will be: A->B

When we merge data from BE to ONYX we are using MERGE method, so that the result will be: A->B->B->B (Because BE only return 2 waypoints so that we only update 2 first waypoints to ONYX)


### What changes do you think we should make in order to solve the problem?
I suggest 2 ways:
1. We need to clean the waypoint in optimistic data, If user enter A->A->B->B, we only should update A->B to ONYX 
2. When receiving data waypoint from BE, we need to update totally (using SET instead of MERGE)

### What alternative solutions did you explore? (Optional)

**Comment by rushatgabhane** [comment] 2023-11-21 12:29
I think https://github.com/Expensify/App/issues/29895 should be reopened because that is where we first approved @rojiphil's [proposal](https://github.com/Expensify/App/issues/29895#issuecomment-1792954251).

But it was closed incorrectly

**Comment by tobyjsullivan** [comment] 2023-11-21 22:15
## Proposal

### Please re-state the problem that we are trying to solve in this issue.

The order of waypoints is not preserved correctly when a money request is created with manual route including duplicate consecutive waypoints.

A simplified reproduction case can include just three waypoints:

1. San Fransisco, CA
2. San Fransisco, CA
3. San Diego, CA

The resulting request receipt will show different waypoints:

1. San Fransisco, CA
2. San Diego, CA
3. San Diego, CA

### What is the root cause of that problem?

The list of waypoints differ between the optimistic transaction data and the saved transaction data. These waypoints are saved in an object instead of an array which causes the merge process to mangle the route when the final collection has fewer keys than the original. 

Specifically, for my example above, the original waypoint includes three waypoints of which two are duplicated:

```json
{
    "waypoint0": { "lat": 37.7749295, "lng": -122.4194155, "address": "San Francisco, CA, USA", "name": "San Francisco" },
    "waypoint1": { "lat": 37.7749295, "lng": -122.4194155, "address": "San Francisco, CA, USA", "name": "San Francisco" },
    "waypoint2": { "lat": 32.715738, "lng": -117.1610838, "address": "San Diego, CA, USA", "name": "San Diego" }
}
```

However, the [waypoints are deduplicated](https://github.com/Expensify/App/blob/da549c0a45edb23fbe9616a9ce21915f291eabe4/src/libs/actions/IOU.js#L666) before saving via the `CreateDistanceRequest` API command.

```json
{
    "waypoint0": { "lat":37.7749295, "lng":-122.4194155, "address":"San Francisco, CA, USA", "name":"San Francisco" },
    "waypoint1": { "lat":32.715738, "lng":-117.1610838, "address":"San Diego, CA, USA", "name":"San Diego" }
}
```

Finally, these values are merged without deleting the extraneous waypoint property, resulting in the last waypoint being duplicated.

```json
{
    "waypoint0": { "lat": 37.7749295, "lng": -122.4194155, "address": "San Francisco, CA, USA", "name": "San Francisco" },
    "waypoint1": { "lat": 32.715738, "lng": -117.1610838, "address": "San Diego, CA, USA", "name": "San Diego" },
    "waypoint2": { "lat": 32.715738, "lng": -117.1610838, "address": "San Diego, CA, USA", "name": "San Diego" }
}
```

It looks like this incorrect merging behaviour has been in place since https://github.com/Expensify/App/pull/26591 which initially introduced waypoint correction.

### What changes do you think we should make in order to solve the problem?

The following multi-part proposal is designed to remove complexity from the overloaded `TransactionUtils.getValidWaypoints()`. This is accomplished by decomposing that helper function, fixing waypoints earlier in the workflow, and blocking users from creating requests with duplicate waypoints in the first place.

**Part 1: Refactor waypoint utils into granular helpers**

The existing implementation of `TransactionUtils.getValidWaypoints(waypoints)` is used in two places which each need and do slightly different things. This causes it to be overloaded.

* The [`createDistanceRequest()` action](https://github.com/Expensify/App/blob/da549c0a45edb23fbe9616a9ce21915f291eabe4/src/libs/actions/IOU.js#L666) needs a clean set of waypoints, excluding blank waypoints.
* [`MoneyRequestParticipantsPage`](https://github.com/Expensify/App/blob/da549c0a45edb23fbe9616a9ce21915f291eabe4/src/pages/iou/steps/MoneyRequstParticipantsPage/MoneyRequestParticipantsPage.js#L67-L68) counts the number of non-empty, non-repeated waypoints to ensure there are at least two.

These use cases can be served by removing `getValidWaypoints(waypoints)` and replacing it with the following set of simplified utils:
* `TransactionUtils.removeEmptyWaypoints(waypoints) => WaypointCollection`
* `TransactionUtils.removeRepeatedWaypoints(waypoints) => WaypointCollection`
* `TransactionUtils.countDistinctWaypoints(waypoints) => number`

Note that the first two functions are composable and would be used to implement the third.

**Part 2: Stop removing repeated waypoints**

Removing repeated waypoints from a report seems like an unintended side effect of #26591 reusing `TransactionUtils.getValidWaypoints()`. There's no indication that silently removing duplicates was intended. By contrast, an error message to the user when editing a report. The UX during report creation should be made consistent (this is covered in Part 4).

Instead, we can replace the [call in this line](https://github.com/Expensify/App/blob/da549c0a45edb23fbe9616a9ce21915f291eabe4/src/libs/actions/IOU.js#L666) to use the new `TransactionUtils.removeEmptyWaypoints(waypoints)` mentioned in Part 1.

**Part 3: Remove empty waypoints earlier in the workflow**

The workflow to create a distance-based request includes multiple steps:
* Step 1: Tap "Request Money"
* Step 2: Tap the "Distance" tab (conditional)
* Step 3: Add a waypoint (repeat for each waypoint)
* Step 4: Tap "Next" to navigate to the participant selection screen.
* Step 5: Tap on the Participant (e.g., Workspace name). Navigates to the confirmation screen.
* Step 6: Tap "Request $xx.xx" to create the request.

The waypoints are currently cleaned at Step 6; however, this is later in the workflow than is ideal. Instead, empty waypoints should be removed in Step 4, when the "Next" button is first tapped. This can be accomplished by expanding the [callback 
in `NewDistanceRequestPage`](https://github.com/Expensify/App/blob/da549c0a45edb23fbe9616a9ce21915f291eabe4/src/pages/iou/NewDistanceRequestPage.js#L60) to remove empty waypoints and update the transaction. 

Note: this is where we would also fix the initial waypoint merging issue. This can be fixed by setting unused waypoint keys to `null`.

**Part 4: Present an error message to users when duplicate waypoints exist** (Optional)

An error message is presented to users when editing a money request. This same error message should be displayed when creating a request.

<img width="688" alt="image" src="https://github.com/Expensify/App/assets/1534986/b4628cb4-030f-401e-81bb-9aeeb1a0b4c0">

### What alternative solutions did you explore? (Optional)

* Fix only the waypoint merging. However, this did not resolve the fundamental complexity in `TransactionUtils.getValidWaypoints()` and was unsatisfying.
* Refactor `TransactionUtils.getValidWaypoints()` to remove overloading and complexity but continue to silently remove duplicate waypoints when creating the final transaction. However, I do not like that this keeps duplicate and empty waypoints in the transaction for longer than necessary. Instead, it seems invalid waypoints should be detected and cleaned as early as possible.
* Silently remove invalid waypoints earlier in the workflow. This is inconsistent with the behavior when editing a request. As such, I recommend displaying the same error message at the same step to make the workflows consistent.
* Stop removing duplicate waypoints altogether. Instead, they can be left in place and only discounted when checking a route has two or more steps in [`MoneyRequestParticipantsPage`](https://github.com/Expensify/App/blob/da549c0a45edb23fbe9616a9ce21915f291eabe4/src/pages/iou/steps/MoneyRequstParticipantsPage/MoneyRequestParticipantsPage.js#L67-L68). In fact, I personally prefer this alternative approach as I don't see a technical reason that duplicate waypoints need to be removed at all. However, based on the current behaviour, I can only assume there is a product requirement for doing so.

**Comment by tobyjsullivan** [comment] 2023-11-21 22:18
Contributor details
Your Expensify account email: expensify.dev@computomatic.com
Upwork Profile Link: https://www.upwork.com/freelancers/~0176782daf3ef21895

**Comment by conorpendergrast** [comment] 2023-11-23 21:39
Closing in favour of https://github.com/Expensify/App/issues/29895, thanks for the context!

**Closed by conorpendergrast** 2023-11-23 21:39 UTC
Labels: External, Daily, Help Wanted, Overdue, Bug
