### ISSUE TITLE
[$500] Connect Bank account - Crash when completed adding BA manually

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#28811] opened 2023-10-04 13:27 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Open the app
2. Login with any account
3. Go to Settings -> Workspaces -> Open any WS
4. Tap on Bank account -> Confirm the changing currency to USD -> Connect manually
5. Complete process adding BA manually using the "Pending State Withdrawal Account" credentials

## Expected Result:
No crash when completed adding BA manually

## Actual Result:
Crash when completed adding BA manually

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android / native
- [ ] Android / Chrome
- [x] iOS / native
- [ ] iOS / Safari
- [ ] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 1.3.77-3

**Reproducible in staging?:** Yes

**Reproducible in production?:** N/a

**If this was caught during regression testing, add the test name, ID and link from TestRail:**

**Email or phone of affected tester (no customers):**

**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/78819774/40de2d4d-59fe-43d6-80d6-702710d071ab

**Expensify/Expensify Issue URL:**

**Issue reported by:** Applause - Internal Team

**Slack conversation:**

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~019ebda629d7c18f15</li>
        <li>Upwork Job ID: 1709642119622356992</li>
        <li>Last Price Increase: 2023-10-11</li>
<li>Automatic offers: </li>
<ul>
<li>Pujan92 | Contributor | 27024773</li>
</ul></li>
    </ul>
</details>

**Comment by Pujan92** [comment] 2023-10-04 13:46
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
App crash for Validate screen in bank account setup flow

### What is the root cause of that problem?
Seems `testId` is set to undefined as we don't have value `displayName` here.
https://github.com/Expensify/App/blob/24aa7c12c269796008f6a96ae153fbd8ced5b43b/src/pages/ReimbursementAccount/ValidationStep.js#L134

<img width="1440" alt="Screenshot 2023-10-04 at 19 13 21" src="https://github.com/Expensify/App/assets/14358475/414c776f-ef8e-46e9-8d5f-c15b214c450c">


### What changes do you think we should make in order to solve the problem?
Set displayName which won't pass undefined to `testId`.

`ValidationStep.displayName = 'ValidationStep';`

https://github.com/Expensify/App/blob/24aa7c12c269796008f6a96ae153fbd8ced5b43b/src/pages/ReimbursementAccount/ValidationStep.js#L230-L232

**Comment by joekaufmanexpensify** [comment] 2023-10-04 16:45
@srikarparsi will you have a chance to look into this today?

**Comment by srikarparsi** [comment] 2023-10-04 18:46
Hey @Pujan92, I'm not able to reproduce this error for some reason but I see your screenshot and you're right in the ValidationStep and many others don't have DisplayName set. Will you have time to work on this today?

**Comment by Pujan92** [comment] 2023-10-04 18:48
I am also not seeing the crash but I can work for fixing the display name set part today.

**Comment by srikarparsi** [comment] 2023-10-04 18:49
Awesome thanks, let me know when you have the PR ready to review.

**Comment by srikarparsi** [comment] 2023-10-04 18:50
@ArekChr, unassigning you as I can review the PR.

**Comment by Pujan92** [comment] 2023-10-04 20:18
@srikarparsi Plz review the [PR](https://github.com/Expensify/App/pull/28853) once.

**Comment by srikarparsi** [comment] 2023-10-04 20:21
Thanks @Pujan92, looks good, adding in the checklist

**Comment by mountiny** [comment] 2023-10-04 22:30
After discussion in [slack thread](https://expensify.slack.com/archives/C01GTK53T8Q/p1696457634586479?thread_ts=1696426623.583819&cid=C01GTK53T8Q), I am demoting this to normal bug as no contributor was able to reproduce actually.

This can still be an issue though so leaving this open

**Comment by joekaufmanexpensify** [comment] 2023-10-05 18:05
@Pujan92 I see you closed your PR in favor of https://github.com/Expensify/App/issues/28334 . Does that mean this issue is a dupe, and we can close it?

**Comment by Pujan92** [comment] 2023-10-05 18:07
No @joekaufmanexpensify, my findings were not directly related to this issue. Based on that we have reopened this issue for contributors, so I believe we should not close this issue yet.

**Comment by joekaufmanexpensify** [comment] 2023-10-05 18:10
Ah, okay got it.

**Comment by joekaufmanexpensify** [comment] 2023-10-06 17:39
I was able to reproduce. Discussing[ here.](https://expensify.slack.com/archives/C01GTK53T8Q/p1696613971679269?thread_ts=1696426623.583819&cid=C01GTK53T8Q)

**Comment by joekaufmanexpensify** [comment] 2023-10-09 14:06
Not overdue

**Comment by joekaufmanexpensify** [comment] 2023-10-10 20:42
Applause was able to reproduce as well

**Comment by joekaufmanexpensify** [comment] 2023-10-13 22:40
Pending proposals

**Comment by srikarparsi** [comment] 2023-10-16 08:48
Still pending proposals

**Comment by mvtglobally** [comment] 2023-10-17 15:11
Issue not reproducible during KI retests. (First week)

**Comment by joekaufmanexpensify** [comment] 2023-10-17 15:17
I'll try to reproduce today again. If I can't I will close!

**Closed** 2023-10-17 15:26 UTC
Labels: External, Engineering, Daily, Help Wanted, Bug
