### ISSUE TITLE
Web - IOU - Numbers added after decimal point are appearing preceding the decimal point

### ISSUE THREAD

**Issue by kavimuru** [Expensify/App#10928] opened 2022-09-09 16:44 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Go to staging.new.expensify.com and login
2. Select a group and select option "Split bill"
3. Enter a decimal point and then numbers

## Expected Result:
Numbers are added after the decimal point

## Actual Result:
Numbers are added before the decimal point, user can't add decimal amount
(Same scenario with Request money and Send money as well)

## Workaround:
Unknown

## Platform:

Where is this issue occurring?

- Web

**Version Number:** v1.1.99-2
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**Email or phone of affected tester (no customers):**

**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** 

<video src="https://user-images.githubusercontent.com/43996225/189400001-29b542be-da5f-409f-81e5-1c23afb5d59e.mp4" width=300 controls/>

**Expensify/Expensify Issue URL:** 
**Issue reported by:** Applause internal team
**Slack conversation:** 

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by techievivek** [comment] 2022-09-12 07:35
@eVoloshchak Is this in any way related to your changes?

**Comment by eVoloshchak** [comment] 2022-09-12 07:48
> @eVoloshchak Is this in any way related to your changes?

Yes, I think it's a regression from https://github.com/Expensify/App/pull/10028. I'll be able to revert the PR and verify this in ±14 hours.

**Comment by eVoloshchak** [comment] 2022-09-15 18:14
> @eVoloshchak Any updates on this one?

Sorry, having trouble with free time
It is related to https://github.com/Expensify/App/pull/10028 simply because this PR introduced adding preceding zero if the user entered the decimal point, so it was an edge case I missed in this PR
Somehow this doesn't happen if you have currency after the amount 

https://user-images.githubusercontent.com/9059945/190479209-51313e2a-aa94-4cf1-9447-f41a77ba9293.mov

I'll look into this on the weekend

**Comment by eVoloshchak** [comment] 2022-09-15 18:34
> Could this be related to #10147?

I don't think so, this PR changed only the [updateAmountNumberPad](https://github.com/Expensify/App/blob/916452af6f4d4b83dc3d77efd00203c53be4eeb8/src/pages/iou/steps/IOUAmountPage.js#L164) method (the one used for on-screen keyboard), while this bug is on `Web`, so the problem is with [updateAmount](https://github.com/Expensify/App/blob/916452af6f4d4b83dc3d77efd00203c53be4eeb8/src/pages/iou/steps/IOUAmountPage.js#L197) method, which was unchanged in `#10147`

**Comment by eVoloshchak** [comment] 2022-09-15 18:48
Now that I think about it more, yes, it could be related to `#10147`. It introduced some changes to the TextInput, mainly the `selection` being controlled by state, there could be bugs associated with this
I'll check it, thank you

**Comment by eVoloshchak** [comment] 2022-09-18 14:23
I checked it, https://github.com/Expensify/App/pull/10147 was the PR that caused this, thanks @parasharrajat for pointing this out.

**Solution:**
This is a controlled input, but currently in [updateAmount](https://github.com/Expensify/App/blob/916452af6f4d4b83dc3d77efd00203c53be4eeb8/src/pages/iou/steps/IOUAmountPage.js#L197) we update `amount`, but don't update the `selection`. Let's fix that 

```diff
updateAmount(text) {
    this.setState((prevState) => {
        const amount = this.addLeadingZero(this.replaceAllDigits(text, this.props.fromLocaleDigit));
+       const selection = this.getNewSelection(prevState.selection, prevState.amount.length, amount.length);
        return this.validateAmount(amount)
-            ? {amount: this.stripCommaFromAmount(amount)}
+            ? {amount: this.stripCommaFromAmount(amount), selection}
            : prevState;
    });
}
```

https://user-images.githubusercontent.com/9059945/190911888-7d83dc58-b25e-4680-964b-4e74aea813a3.mov

**Comment by techievivek** [comment] 2022-09-19 07:45
Just checked with the team on how we need to handle this. I will put the updates here. Thanks

**Comment by rushatgabhane** [comment] 2022-09-19 08:09
I'll work on the RCA

**Comment by techievivek** [comment] 2022-09-19 10:00
I just discussed it with the team and since this is a clear case of regression we would want @eVoloshchak to push a PR fixing this.

**Comment by eVoloshchak** [comment] 2022-09-19 10:01
If the solution I proposed looks good to you, I can push a PR

**Comment by rushatgabhane** [comment] 2022-09-19 10:04
@eVoloshchak yea, let's do it!

**Comment by techievivek** [comment] 2022-09-21 06:17
@eVoloshchak Hi, have you pushed a PR fixing it?

**Comment by eVoloshchak** [comment] 2022-09-21 18:37
> @eVoloshchak Hi, have you pushed a PR fixing it?

PR is up

**Comment by mvtglobally** [comment] 2022-10-18 11:17
Issue not reproducible during KI retests. (First week)

**Comment by mvtglobally** [comment] 2022-10-24 18:29
Issue not reproducible during KI retests. (Second week)

**Comment by mvtglobally** [comment] 2022-11-03 02:59
Issue not reproducible during KI retests. (Third week) @techievivek Are we ok to close this one?

**Comment by techievivek** [comment] 2022-11-03 05:10
Sorry, I agree we can close this now.

**Closed by techievivek** 2022-11-03 05:10 UTC
Labels: Reviewing, Engineering, Weekly, Bug
