### ISSUE TITLE
BUG: DEV - Loading animation shows on Concierge chat reported by @mdneyazahmad

### ISSUE THREAD

**Issue by kavimuru** [Expensify/App#12081] opened 2022-10-23 17:02 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:

1. Open app in dev mode
2. Select chat with Concierge
3. Observe the animation before the start of the chat section

## Expected Result:
Loading animation is not shown

## Actual Result:
Loading animation is shown

## Platform:

Where is this issue occurring?

- Web

**Version Number:** v1.2.17-4 DEV
**Reproducible in staging?:** Needs reproduction
**Reproducible in production?:** Needs reproduction
**Email or phone of affected tester (no customers):** 
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** 
<img width="1440" alt="Screenshot 2022-10-18 at 9 54 56 AM" src="https://user-images.githubusercontent.com/43996225/197405256-786eee0d-87d5-41b5-ba07-39d5e4fa910e.png">

**Expensify/Expensify Issue URL:** 
**Issue reported by:** @mdneyazahmad
**Slack conversation:** https://expensify.slack.com/archives/C01GTK53T8Q/p1666068031056799

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by greg-schroeder** [comment] 2022-10-26 13:01
I can't reproduce this because I don't have access to a Dev instance, so I'm going to tag Eng to try to repro

**Comment by srikarparsi** [comment] 2022-11-01 02:17
I'm not able to reproduce this issue. I tried creating a new account too but don't see the loading indicator for the concierge chat. Is this still happening @mdneyazahmad @kavimuru?

**Comment by kavimuru** [comment] 2022-11-01 12:30
@srikarparsi I can't check in Dev. So I added `Needs reproduction` label. @mdneyazahmad has to answer for the clarification.

**Comment by mdneyazahmad** [comment] 2022-11-01 13:36
There is also an interesting similar issue. In this case the image attachment appears before the beginning of the message.

<img width="1202" alt="Screenshot 2022-10-31 at 10 40 11 AM" src="https://user-images.githubusercontent.com/77761491/199246103-0dbc0763-285c-40e5-abac-25e147413194.png">

But after I cleared the site data. Everything comes back to normal. So, it is not reproducible now.

**Comment by srikarparsi** [comment] 2022-11-01 19:10
cool, closing the issue for now. Please reopen if you're able to reproduce it later.

**Closed by srikarparsi** 2022-11-01 19:10 UTC
Labels: Engineering, Daily, Needs Reproduction, Bug
