### ISSUE TITLE
[$500] Chat - The user is able to scroll through the suggestion list

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#27866] opened 2023-09-20 14:07 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Login to any account.
2. Open any chat that has a long chat history.
3. Type "@" followed by the search keyword in the compose field.
4. Ensure that the suggestion list ONLY returns a FEW results so that the scroll bar doesn't appear.
5. Long-press on any item in the suggestion list and scroll up/down.
6. Observation: The content behind the suggestion list scrolls.

## Expected Result:
The content behind the suggestion list should not scroll.

## Actual Result:
The user is able to scroll through the suggestion list, causing the chat behind it to scroll.

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [x] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [x] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 1.3.72.6
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/93399543/fdc59ab8-f91a-4321-82af-d0f5a3da8f4a

https://github.com/Expensify/App/assets/93399543/8dcb3a2f-cbd3-4802-95b0-cdc80081764d

**Expensify/Expensify Issue URL:**
**Issue reported by:** @tranvantoan-qn
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1695140320778399

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01c3091e29ea2936a7</li>
        <li>Upwork Job ID: 1704497441979785216</li>
        <li>Last Price Increase: 2023-10-11</li>
    </ul>
</details>

**Comment by trjExpensify** [comment] 2023-09-21 11:47
Assigned second, dropping off.

**Comment by lschurr** [comment] 2023-09-25 08:15
@0xmiroslav could you review the proposal on this one?

**Comment by lschurr** [comment] 2023-09-29 08:50
Are we still waiting on new proposals @0xmiroslav? Or has this one been fixed with that PR?

**Comment by lschurr** [comment] 2023-10-02 12:02
Still waiting on proposals.

**Comment by lschurr** [comment] 2023-10-04 16:03
Is this bug still happening @0xmiroslav @s-alves10?

**Comment by lschurr** [comment] 2023-10-09 16:52
Looks like we're still waiting on proposals.

**Comment by s-alves10** [comment] 2023-10-13 13:23
The videos are telling something a little different
video 1: scrolling background content through suggestion list
video 2: scrolling while suggestion list is opened

I'm a little bit confused.
Please help me have a clear understanding. Thank you

**Comment by lschurr** [comment] 2023-10-16 15:49
Just to clarify @0xmiroslav - we're still waiting on proposals to fix a slightly different bug than what was originally reported here?

**Comment by lschurr** [comment] 2023-10-19 15:50
Could you start a slack convo about this one @0xmiroslav?

**Comment by lschurr** [comment] 2023-10-23 15:24
Going to close this one as it's a minor bug for now.

**Comment by lschurr** [comment] 2023-11-30 23:48
Still waiting for proposals.

**Comment by lschurr** [comment] 2023-12-06 00:24
Waiting on proposals.

**Comment by lschurr** [comment] 2023-12-07 23:43
Asking CallStack if they can help - https://expensify.slack.com/archives/C03UK30EA1Z/p1701992570029619

**Comment by keisyrzk** [comment] 2023-12-08 09:20
I have tried in mac chrome and android chrome and it seems to work as intended. Please look at the videos provided below.

Android chrome
https://github.com/Expensify/App/assets/18525360/a2d597db-4369-4a35-8526-279871cac844

MacOS chrome
https://github.com/Expensify/App/assets/18525360/d4ea91e1-5411-474c-8e3a-0b959a2445e2

**Comment by artus9033** [comment] 2023-12-08 15:15
Hi, I'm Artur from Callstack - expert contributor group - and I would like to help with this issue.
I'm able to reproduce after reverting the 'fix' - thanks @0xmiroslav

**Comment by artus9033** [comment] 2023-12-08 16:37
I see, perfect - thanks for the clarification

**Comment by artus9033** [comment] 2023-12-11 16:39
Sure @lschurr, I have the cause and am working on a proposal. It should be there by Wednesday.

**Comment by artus9033** [comment] 2023-12-13 22:18
Update: still working on a proposal

**Comment by artus9033** [comment] 2023-12-14 17:05
No update yet

**Comment by artus9033** [comment] 2023-12-15 12:38
## Proposal

### Please re-state the problem that we are trying to solve in this issue.

Scrolling the mentions popup window above the composer results in scrolling the chat history behind that popup. Currently, the behaviour is suppressed by a tricky [workaround](https://github.com/Expensify/App/pull/28389/files#diff-f21ab41633352a4b56d9a4c7207994e0d1bee3c56aaab19a81196ac5c24f9aceR945) that always makes the list view actively scrollable by modifying its style so that always the contents are of larger height than the height of the list. This makes the list intercept and consume all touch requests, but causes the list to be always-scrollable.
As described [here](https://github.com/Expensify/App/issues/27866#issuecomment-1761496971) by @0xmiroslav, the fix is only to be applied to Android native.

### What is the root cause of that problem?

The root cause, as described in #27140, is that apparently the Android platform RN implementation of a scroll view passes through scroll interaction events to the components behind it when it is positioned absolutely and is not actively scrollable (i.e., the contained items do not overflow their scrollable wrapper).

### What changes do you think we should make in order to solve the problem?


Intercepting the interaction events with the popup and consuming them (in a way that does not cause bubbling to other components / passing through to elements behind) would prevent the chat history component from receiving them, thus from scrolling.
A viable way to do that would be to wrap the contents inside a GestureHandler that would listen both to Pan and Fling gestures to consume them natively, passing them only to its children.

### What alternative solutions did you explore? (Optional)

Passing scroll / responder / touch-move callbacks to the scrollable list, however that did not help; stopPropagation() is of no help either, probably since this the events look like "passing through" the absolute positioned element, rather than being bubbled up the tree.

**Comment by lschurr** [comment] 2023-12-18 15:43
@0xmiroslav could you take a look at this one?

**Comment by lschurr** [comment] 2023-12-22 19:36
Bump @0xmiroslav

**Comment by lschurr** [comment] 2023-12-28 18:31
Just clarifying, are you saying we should not fix the bug or we should wait for other proposals @0xmiroslav?

**Comment by lschurr** [comment] 2024-01-01 19:52
Waiting on proposals.

**Comment by lschurr** [comment] 2024-01-03 16:33
Any ideas on this @0xmiroslav @artus9033? Should we start a Slack convo seeking more help?

**Comment by lschurr** [comment] 2024-01-05 18:24
Pinged @artus9033 in Slack - https://expensify.slack.com/archives/C03UK30EA1Z/p1704479067110369?thread_ts=1701992570.029619&cid=C03UK30EA1Z

**Comment by artus9033** [comment] 2024-01-08 09:50
Hi @lschurr, just wanted to say that Kuba @MrRefactor from Callstack will handle it from here instead of me

**Comment by MrRefactor** [comment] 2024-01-09 07:50
Hi @lschurr, I'm taking this issue from @artus9033

**Comment by lschurr** [comment] 2024-01-11 23:24
Any progress on this one yet @MrRefactor?

**Comment by lschurr** [comment] 2024-01-15 06:59
Thanks! Do you expect an update this week?

**Comment by MrRefactor** [comment] 2024-01-15 07:04
Hi @lschurr! Yes, I definitely want to post a proposal this week.

**Comment by MrRefactor** [comment] 2024-01-16 17:43
not overdue

**Comment by MrRefactor** [comment] 2024-01-19 13:44
> The bug was fixed in #27140 but they added [workaround](https://github.com/Expensify/App/pull/28389/files#diff-f21ab41633352a4b56d9a4c7207994e0d1bee3c56aaab19a81196ac5c24f9aceR945), not fixing the real root cause.
> 
> They decreased height (which was correct) by `borderWidth`.
> 
> Now this caused regression of suggestion list content scrollable even though there are only a few items.
> 
>  Screen.Recording.2023-10-13.at.3.08.58.PM.mov 
> We should revert that change and fix the real root cause - `In android, when nested scroll view doesn't have enough content to scroll, scroll gesture applies to parent scroll view`

so as I understand after reverting workaround we can see the expected behaviour on other platforms than android - if the suggestion list is less than 5 elements, we shouldn't be able to scroll it, but adding the additional height taken from borderWidth makes it scrollable. 
In that case I agree that we should revert the workaround, and add android only solution that will prevent scrolling the content behind the suggestion list. Right now I have issues connected to building the android app on the newest main branch due to the change of version of react native, but after resolving those I will check native android app and report findings.

CC: @lschurr @0xmiroslav

**Comment by MrRefactor** [comment] 2024-01-22 13:09
hi @0xmiroslav I've checked scenario with removing the workaround and leaving it only on android and there are the results:
As for mobile web, I can see that after reverting the workaround there is an issue connected to scroll on iOS - videos attached. 


https://github.com/Expensify/App/assets/32591413/2a9c3524-c034-4af9-8fa9-526edaf5a493


https://github.com/Expensify/App/assets/32591413/4b13090b-cf88-412f-9fe1-2c9f1e7a07c7

**Comment by MrRefactor** [comment] 2024-01-22 14:17
## Proposal
 ### Please re-state the problem that we are trying to solve in this issue.
 Scrolling the mentions popup window above the composer results in scrolling the chat history behind that popup. Currently, the behaviour is suppressed by a tricky [workaround](https://github.com/Expensify/App/pull/28389/files#diff-f21ab41633352a4b56d9a4c7207994e0d1bee3c56aaab19a81196ac5c24f9aceR945) that always makes the list view actively scrollable by modifying its style so that always the contents are of larger height than the height of the list. This makes the list intercept and consume all touch requests, but causes the list to be always-scrollable. As described [here](https://github.com/Expensify/App/issues/27866#issuecomment-1761496971) by @0xmiroslav, the fix is only to be applied to Android native. After the investigation, it seems that the bug is also occurring on mobile safari.

 ### What is the root cause of that problem?
 The root cause, as described in #27140, is that apparently the Android platform RN implementation of a scroll view passes through scroll interaction events to the components behind it when it is positioned absolutely and is not actively scrollable (i.e., the contained items do not overflow their scrollable wrapper). The bug is also visible on iOSMobileSafari.
 
 ### What changes do you think we should make in order to solve the problem?
Removing the [workaround](https://github.com/Expensify/App/pull/28389/files#difff21ab41633352a4b56d9a4c7207994e0d1bee3c56aaab19a81196ac5c24f9aceR945) for all platforms but native android and mobileSafari on iOS can solve the issue with always-scrollable list.
 
 ### What alternative solutions did you explore? (Optional)

**Comment by MrRefactor** [comment] 2024-01-22 14:17
CC: @lschurr @0xmiroslav

**Comment by francoisl** [comment] 2024-01-23 19:36
👍 @MrRefactor feel free to go ahead with your suggestion. Let's just make sure to add a comment about why we need to keep the workaround on Android and iOS Safari, if there isn't one already. Thanks!

**Comment by MrRefactor** [comment] 2024-01-23 20:04
> 👍 @MrRefactor feel free to go ahead with your suggestion. Let's just make sure to add a comment about why we need to keep the workaround on Android and iOS Safari, if there isn't one already. Thanks!

Hi! I will try to open pr tomorrow

**Comment by mallenexpensify** [comment] 2024-01-24 03:49
@Santhosh-Sellavel reassigning, please take over as C+. If you don't have bandwidth, unassign yourself. Thanks

Also.. there wasn't an internal or external label here so I added/removed External

**Comment by MrRefactor** [comment] 2024-01-29 09:58
Not overdue, posting today

**Comment by lschurr** [comment] 2024-01-31 16:29
Any update on this one @MrRefactor?

**Comment by MrRefactor** [comment] 2024-02-01 08:54
Hi! [PR](https://github.com/Expensify/App/pull/35319) is ready to be reviewed

**Comment by Santhosh-Sellavel** [comment] 2024-02-13 20:41
@mallenexpensify I am planning on OOO please assign a new C+ here to continue the review.

**Comment by situchan** [comment] 2024-02-13 21:47
I'd like to continue reviewing [PR](https://github.com/Expensify/App/pull/35319)

**Comment by francoisl** [comment] 2024-02-13 22:39
Assigned you @situchan

**Comment by MrRefactor** [comment] 2024-02-26 09:51
[PR](https://github.com/Expensify/App/pull/35319) merged 5 days ago!

CC: @lschurr

**Comment by lschurr** [comment] 2024-02-26 19:40
Thanks @MrRefactor - Typically the payment date is set for 7 days after the change is deployed to production. Is this one that doesn't need to be deployed @francoisl?

**Comment by francoisl** [comment] 2024-02-26 22:15
No, it still needs to be deployed to production. It was just [deployed](https://github.com/Expensify/App/pull/35319#issuecomment-1965271990) to staging 1 hour ago. We had a merge/deploy freeze last week, hence the delayed deploy.

**Comment by lschurr** [comment] 2024-02-26 22:55
Great, thanks for checking!

**Comment by francoisl** [comment] 2024-03-14 01:14
Yes we can issue payments now @lschurr and then close this.

**Comment by lschurr** [comment] 2024-03-18 15:37
Ah sorry I missed this. I'll take care of payments today.

**Comment by lschurr** [comment] 2024-03-19 17:39
Payment summary:

- Contributor: @MrRefactor (agency - no payment needed)
- Contributor+: @situchan $500 (to be paid in Upwork)

**Comment by lschurr** [comment] 2024-03-19 17:43
@situchan - sent offer: https://www.upwork.com/nx/wm/offer/101468767

**Comment by lschurr** [comment] 2024-03-19 17:58
This is complete.

**Closed by lschurr** 2024-03-19 17:58 UTC
Labels: Engineering, Daily, Bug

**Comment by tranvantoan-qn** [comment] 2024-03-19 18:03
@lschurr I'm eligible for a reporting bonus as well :D

**Comment by lschurr** [comment] 2024-03-19 19:43
Oh wow, you're right! This is an old one. I sent an offer via Upwork @tranvantoan-qn: https://www.upwork.com/nx/wm/offer/101471120

**Comment by tranvantoan-qn** [comment] 2024-03-19 20:14
Thank you!
I have accepted the offer

**Comment by lschurr** [comment] 2024-03-19 20:28
All set.
