### ISSUE TITLE
[$250] Task – Hidden assignee appears in LHN when assign task without assignee to yourself

### ISSUE THREAD

**Issue by m-natarajan** [Expensify/App#44205] opened 2024-06-22 13:47 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 9.0.1-0
**Reproducible in staging?:** y
**Reproducible in production?:** n
**If this was caught during regression testing, add the test name, ID and link from TestRail:** n/a
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** applause internal team
**Slack conversation:**

## Action Performed:
1. Go to https://staging.new.expensify.com/
2. Log in
3. Open any chat
4. Create a task without assignee
5. Open task details and assign it to yourself
6. Find task in LHN

## Expected Result:
Assignee name appears in LHN

## Actual Result:
Hidden assignee appears in LHN

## Workaround:
unknown
## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [x] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

https://github.com/Expensify/App/assets/38435837/8e8d0ccd-dcf2-4184-9049-755418b312b2

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~012e2bf84563d514ee</li>
        <li>Upwork Job ID: 1804545733497236627</li>
        <li>Last Price Increase: 2024-06-22</li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @rushatgabhane</details>

**Comment by m-natarajan** [comment] 2024-06-22 13:48
@carlosmiceli FYI I haven't added the External label as I wasn't 100% sure about this issue. Please take a look and add the label if you agree it's a bug and can be handled by external contributors

**Comment by m-natarajan** [comment] 2024-06-22 13:48
We think that this bug might be related to  #vip-vsb

**Comment by carlosmiceli** [comment] 2024-06-22 16:05
Can't reproduce in dev and quite an edge case. Opening for contributors to fix.

**Comment by robert-westenberger** [comment] 2024-06-22 21:52
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
Instead of the task assignee's name appearing in the LHN, `@Hidden` shows instead.

### What is the root cause of that problem?
The piece of text is rendered by this line in OptionRowLHN

https://github.com/Expensify/App/blob/425804aa005c6299ff0f59ff596764c429e19abd/src/components/LHNOptionsList/OptionRowLHN.tsx#L245

`optionItem` is a prop from `OptionRowLHNData`, building it via `SidebarUtils.getOptionData`

https://github.com/Expensify/App/blob/425804aa005c6299ff0f59ff596764c429e19abd/src/components/LHNOptionsList/OptionRowLHNData.tsx#L42-L50

That function sets the alternateText attribute using `TaskUtils.getTaskReportActionMessage`, accessing the `text` attribute on it's return value

https://github.com/Expensify/App/blob/425804aa005c6299ff0f59ff596764c429e19abd/src/libs/SidebarUtils.ts#L351

All that does is call `getReportActionText` from `ReportActionUtils.ts`

https://github.com/Expensify/App/blob/425804aa005c6299ff0f59ff596764c429e19abd/src/libs/TaskUtils.ts#L33

That function passes the report action's `message.html` (or `message[0].html` if message is an array) to the Expensimark parser's htmlToText method.

https://github.com/Expensify/App/blob/425804aa005c6299ff0f59ff596764c429e19abd/src/libs/ReportActionsUtils.ts#L1125-L1133

That method uses this `userMention` rule, which relies upon an `extras` value to be passed to it containing a `accountID` -> `name` map to inject names into parsed text. If one isn't found, the string "@Hidden" is injected.

https://github.com/Expensify/expensify-common/blob/e6fe884e56d64df8ab2157d92fe2de6b1f6a91d5/lib/ExpensiMark.ts#L732-L743

So we're actually calling ExpensiMark's parseHtmlToText twice. 

The first time it's called  we don't pass it the accountID -> name map
https://github.com/Expensify/App/blob/425804aa005c6299ff0f59ff596764c429e19abd/src/libs/ReportActionsUtils.ts#L1132

When we render the OptionRowLHN component, the component receives the already parsed text, but the component is calling `parseHtmlToText` itself..

https://github.com/Expensify/App/blob/425804aa005c6299ff0f59ff596764c429e19abd/src/components/LHNOptionsList/OptionRowLHN.tsx#L245

But this one is importing it from the OnyxAwareParser

https://github.com/Expensify/App/blob/425804aa005c6299ff0f59ff596764c429e19abd/src/components/LHNOptionsList/OptionRowLHN.tsx#L23

The onyx aware parser also uses ExpensiMark's `htmlToText` method, but it wraps that method and passes the accountID -> name map for the parser to use and inject the name with.

https://github.com/Expensify/App/blob/425804aa005c6299ff0f59ff596764c429e19abd/src/libs/OnyxAwareParser.ts#L49
### What changes do you think we should make in order to solve the problem?

We can change this line 
https://github.com/Expensify/App/blob/425804aa005c6299ff0f59ff596764c429e19abd/src/libs/SidebarUtils.ts#L351

to instead return the raw HTML instead of the parsed text
```typescript
result.alternateText = ReportUtils.formatReportLastMessageText(TaskUtils.getTaskReportActionMessage(lastAction).html);
```

This is fine because the only place the `alternateText` is ultimately used, it gets parsed anyway.. but during that parse, the parser gets the accountID -> name map it needs to inject the username into the parsed piece of text from the onyx store.

### What alternative solutions did you explore? (Optional)
With my proposal, the expensimark parser is still called twice, pointlessly.... we just aren't accessing the parse result anymore from `SidebarUtils.getOptionData`. Currently looking into a way to see if we can remove that redundant call to parser.htmlToText

**Comment by tsa321** [comment] 2024-06-23 02:11
## Proposal

### Please re-state the problem that we are trying to solve in this issue.

Task – assigned to @Hidden when last message is edited assignee.

### What is the root cause of that problem?

In the newly created function:

https://github.com/Expensify/App/blob/4dc1710ea72daaa44875e24ea0f71056b33ed8ef/src/libs/ReportActionsUtils.ts#L1129-L1133

we don't use OnyxAwareParser:

https://github.com/Expensify/App/blob/4dc1710ea72daaa44875e24ea0f71056b33ed8ef/src/libs/OnyxAwareParser.ts#L43-L50

So the parsed text from html will fails to parse mentioned user name.

### What changes do you think we should make in order to solve the problem?

We should use the OnyxAwareParser in the getReportActionText above. and if we want to modify the mentioned user account into user name, we can pass parameter to the parseHtmlToText, wheter we want username or user email account.

**Comment by carlosmiceli** [comment] 2024-06-25 18:48
Still waiting for proposal reviews by @rushatgabhane.

**Comment by rushatgabhane** [comment] 2024-06-26 02:18
@robert-westenberger's [proposal](https://github.com/Expensify/App/issues/44205#issuecomment-2184201504) LGTM
🎀 👀 🎀

**Comment by robert-westenberger** [comment] 2024-06-26 14:20
@carlosmiceli @rushatgabhane hey carlos and rushat, how do i get invited to the expensify open source slack channel? I emailed contributors@expensify.com with the subject Slack Channel Invites as described [here](https://github.com/Expensify/App/blob/2b5dd26ed1c07cb8b799f767fab1ec5d99759e43/contributingGuides/CONTRIBUTING.md#slack-channels) but I never got any response.

**Comment by robert-westenberger** [comment] 2024-06-26 15:10
Also @carlosmiceli @rushatgabhane this issue is no longer reproducible. It looks like it was fixed with this PR https://github.com/Expensify/App/pull/44365

**Comment by carlosmiceli** [comment] 2024-06-27 22:40
@puneetlath this would be good to close then, right?

**Comment by puneetlath** [comment] 2024-06-28 14:28
Sounds good, let's close it.

**Closed by puneetlath** 2024-06-28 14:28 UTC
Labels: External, Engineering, Daily, Bug
