### ISSUE TITLE
[$1000] IOS - Receiving notifications from OldDot reports on NewDot

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#21541] opened 2023-06-25 20:26 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Logged into new dot (mobile)
2. Logged into old dot
3. Sent report for approval on old dot
4. The approver added a comment on that report
5. Notification arrived in new dot

## Expected Result:
Notification should have arrived only on old dot app

## Actual Result:
Notification arrived in new dot app

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [x] iOS / native
- [ ] iOS / Safari
- [ ] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 1.3.32.5
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856

https://github.com/Expensify/App/assets/93399543/d90750f2-4b9f-423c-9740-37d17a86500f

https://github.com/Expensify/App/assets/93399543/ab1b9936-46e1-4fb1-9f5c-1137a83b3ebf

**Notes/Photos/Videos:** Any additional supporting documentation
**Expensify/Expensify Issue URL:**
**Issue reported by:** Daniel Silva
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1687167636232139

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~017ca86be03a017b8d</li>
        <li>Upwork Job ID: 1673452633924894720</li>
        <li>Last Price Increase: 2023-06-30</li>
    </ul>
</details>

**Comment by mallenexpensify** [comment] 2023-06-26 22:07
Unable to reproduce, @kbecciv , can you outline the steps you took to reproduce? 
Thx

**Comment by kbecciv** [comment] 2023-06-28 12:12
Hello @mallenexpensify!
Reproduction steps:
1. Install the NewDot app and OldDot app in your device
2. Log in with Account A in both apps
3. Navigate to staging.expensify.com and log in with account B
4. Sent report for approval on to account A and log out
5.  Navigate to staging.expensify.com and log in with Account B
5. Account B added a comment in Olddot on that report 
6. Account A will receive a notification on NewDot

I hope I did not miss anything!

**Comment by mallenexpensify** [comment] 2023-06-30 02:32
I can't reproduce :(
Just spent 20 mins trying to 
<img width="848" alt="image" src="https://github.com/Expensify/App/assets/22508304/5bf88876-641b-49b4-af83-6617fe4216e4">

@rushatgabhane can you see if you can reproduce please?

**Comment by mallenexpensify** [comment] 2023-07-05 23:05
@danieldoglas , sending this back to you since you reported it and myself and @rushatgabhane are unable to reproduce.

**Comment by danieldoglas** [comment] 2023-07-06 16:13
I can't simulate this as well anymore. It is possible it was fixed on another unrelated change. I think we can close this.

**Closed by danieldoglas** 2023-07-06 16:13 UTC
Labels: Daily, Internal, Bug
