### ISSUE TITLE
[HOLD for payment 2024-02-20] [Wave 8] [Ideal Nav] Back navigation issues

### ISSUE THREAD

**Issue by hayata-suenaga** [Expensify/App#35626] opened 2024-02-02 03:01 UTC
## Action Performed:

There are several issues reported that have to do with the back navigation and wrong navigation animations. I listed those issues below.

~~### Issue 1:~~
~~1. Make sure you're on a mobile phone or on a browser with a smaller width~~
~~2. Make sure that the test account has at least one workspace~~
~~3. Click on the Settings icon 🔧 on the bottom tab > Workspaces > Select a workspace~~

~~video ->  https://github.com/Expensify/App/pull/33280#issuecomment-1921860615~~

### Issue 2:
1. Make sure you're on a mobile phone or on a browser with a smaller width
2. Click the Chat button on the bottom tab
3. Select a chat/report
5. Go back
6. Confirm that the Chat List page opens from the right when the page should close to the left (watch the video)
7. Click the Settings (🔧) button on the bottom tab
8. Confirm that the Setting page opens from the right when the page should not animate. Only the part above the bottom tab should change without animation.

https://github.com/Expensify/App/assets/98560306/ac15026d-e47f-471a-bc73-9b7645884a53

### Issue 3:
1. Click the `Settings` button on the bottom tab > Workspaces
2. Click the back button (left chevron icon)
3. Confirm that the Chat List page opens from the right when the Workspace List page should close to left to go back to the Settings page

https://github.com/Expensify/App/assets/98560306/cfb693cb-e8cd-4cd5-9704-2c39c3dc1cfd

### Issue 4:
1. Test this on a browser. Shrink the window width.
2. Visit https://dev.new.expensify.com:8082/settings/preferences
3. Press the back button on the header (left chevron icon next to Preferences)
4. The app navigates to the Chats page when it should navigate back to the Settings page.

video -> https://github.com/Expensify/App/pull/33280#issuecomment-1921882304

### Other related issues
- https://github.com/Expensify/App/issues/35669
- https://github.com/Expensify/App/issues/35689
- https://github.com/Expensify/App/issues/35697
- https://github.com/Expensify/App/issues/35703
- https://github.com/Expensify/App/issues/35756
- https://github.com/Expensify/App/issues/35729
- https://github.com/Expensify/App/issues/35969
- https://github.com/Expensify/App/issues/35965
- https://github.com/Expensify/App/issues/36040
- https://github.com/Expensify/App/issues/36035 (might be partially related)

## Workaround:
N/A

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [x] Android: mWeb Chrome
- [x] iOS: Native
- [x] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

vides are attached above.

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by adamgrzybowski** [comment] 2024-02-02 11:14
Hi! Working on it!

**Comment by hayata-suenaga** [comment] 2024-02-02 17:08
@adamgrzybowski I added several reported issues that probably related to the back navigation to the original post. Please go through them and let me know if there are issues that should be addressed separately from this issue.

**Comment by hayata-suenaga** [comment] 2024-02-02 17:21
@adamgrzybowski can you also check if [this issue](https://github.com/orgs/Expensify/projects/94/views/2?pane=issue&itemId=51963694) can also be fixed by the solution you're thinking about?

**Comment by CortneyOfstad** [comment] 2024-02-02 18:58
Heads up @adamgrzybowski @hayata-suenaga ^^^

**Comment by hayata-suenaga** [comment] 2024-02-02 19:52
Closed the issue linked above 🙇

**Comment by hayata-suenaga** [comment] 2024-02-02 23:26
@GandalfGwaihir this issue will be handled by an engineer from an expert agency. However, thank you for your proposal.

**Comment by hayata-suenaga** [comment] 2024-02-02 23:26
This is another instance of back navigation issue: https://github.com/Expensify/App/issues/35736#issuecomment-1924898853

**Comment by johncschuster** [comment] 2024-02-03 21:59
Related: https://github.com/Expensify/App/issues/35669

**Comment by hayata-suenaga** [comment] 2024-02-04 05:17
# If you find any back navigation related issues, please add your issue to the `Other related issues` section in the original post of this issue. 🙇 

![Screenshot 2024-02-03 at 9 17 48 PM](https://github.com/Expensify/App/assets/98560306/5a571f53-5dd5-4415-9683-fafab2591e54)

**Comment by CortneyOfstad** [comment] 2024-02-05 19:21
@hayata-suenaga when there are that many similar issues, what is the next step here? Have not come across a similar scenario via BugZero before, so just wanted to confirm next steps. Thanks!

**Comment by hayata-suenaga** [comment] 2024-02-05 23:25
@CortneyOfstad I apologize for all the notifications you're getting for this issue 🙇 

We're tracking all regressions from this PR [here](https://github.com/orgs/Expensify/projects/94/views/2). We expected we will have quite a lot of regressions, and these regressions are tracked on the GH project board. We will do this kind of stuff when we merge a big feature branch (code). 👍

**Comment by adamgrzybowski** [comment] 2024-02-06 12:43
Hey @hayata-suenaga I'm continuing to search for the best solution. 

I went through the issues in the description of the PR and it looks like the first one:

> Issue 1:
Make sure you're on a mobile phone or on a browser with a smaller width
Make sure that the test account has at least one workspace
Click on the Settings icon 🔧 on the bottom tab > Workspaces > Select a workspace
video -> https://github.com/Expensify/App/pull/33280#issuecomment-1921860615

Is not actually related to the go back. It's related [to this issue ](https://github.com/Expensify/App/issues/35610)

I can't reproduce the issue 2 and 3.

Still can reproduce the issue 4.

I will check out the rest.

**Comment by hayata-suenaga** [comment] 2024-02-06 18:03
Adam, thank you for checking through the issues. I removed (i.e. strikethrough-ed the case 1) and moved it to [this issue](https://github.com/orgs/Expensify/projects/94/views/2?pane=issue&itemId=51963600).

**Comment by situchan** [comment] 2024-02-07 18:10
@hayata-suenaga another ones: #36040, #36035

**Comment by hayata-suenaga** [comment] 2024-02-07 19:00
@muas19 thank you for letting us know about the issue, but that issue is a separate one from this one

**Comment by getusha** [comment] 2024-02-08 09:03
It is almost impossible to go back from workspace settings without reloading

Is this related @hayata-suenaga @adamgrzybowski 

https://github.com/Expensify/App/assets/75031127/0be64152-1836-401b-9e82-1cda6a05fe65

**Comment by adamgrzybowski** [comment] 2024-02-08 12:58
> this is a bit confusing, Settings page should open from the right with animation or just open without any animation?

The behavior you recorded is as expected. No animation for switching between bottom tabs.

> It is almost impossible to go back from workspace settings without reloading

Not sure why impossible. Do you have any specific case? The back button may not be exactly right in that case though. There is a ticket for that https://github.com/Expensify/App/issues/35610

https://github.com/Expensify/App/assets/67908363/32602d28-9d05-4f33-94df-fcd496e7f233

**Comment by hayata-suenaga** [comment] 2024-02-13 18:37
⬆️ This regression was already known.

**Comment by getusha** [comment] 2024-02-14 14:36
@hayata-suenaga could you assign me here for C+ payment?

**Comment by hayata-suenaga** [comment] 2024-02-14 17:17
@getusha reviewed [this PR](https://github.com/Expensify/App/pull/36050)

**Comment by CortneyOfstad** [comment] 2024-02-20 15:11
For some reason the Upwork Job link just links back to the top of this GH, so linking it here — https://www.upwork.com/jobs/~0194f5dc425897c3e9. 

@getusha I've sent you an offer. Let me know once you accept and I can get that paid ASAP. Thanks!

**Comment by getusha** [comment] 2024-02-20 15:14
@CortneyOfstad accepted, thank you!

**Comment by CortneyOfstad** [comment] 2024-02-20 15:42
Perfect — I completed payment to @getusha and updated the payment summary above. Regression test is already known, so this is all set! Closing this as completed

**Closed by CortneyOfstad** 2024-02-20 15:42 UTC
Labels: Daily, Awaiting Payment, Bug
