### ISSUE TITLE
[$500] Email addresses and Timezones are exposed to anonymous users when they open the user's profile avatar

### ISSUE THREAD

**Issue by m-natarajan** [Expensify/App#36251] opened 2024-02-09 15:39 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___
Email addresses and Timezones are exposed to anonymous users when they open the user's profile avatar**Version Number:**
**Reproducible in staging?:** v1.4.39-0
**Reproducible in production?:** Yes
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** @fedirjh 
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1707432052448279

## Action Performed:
1.Log out and navigate to a public room. eg https://staging.new.expensify.com/r/8292963527436014 or https://staging.new.expensify.com/r/2376199970894587
2.Click on the user avatar to open the profile view for the user.
3.Click on the avatar to open the attachment modal for the avatar.
4.Close the avatar and verify that the email address and timezone is exposed.
## Expected Result:
Email addresses and Timezones should be hidden to anonymous
## Actual Result:
Email addresses and Timezones are exposed to anonymous users
## Workaround:
Unknown
## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

https://github.com/Expensify/App/assets/38435837/7ff5f47b-b434-47b6-91d7-6639e5480c5d

https://github.com/Expensify/App/assets/38435837/5639b2f5-e6b5-499b-b19d-09b179cebec0

https://github.com/Expensify/App/assets/38435837/1484af0d-0a72-4147-8472-9941c0cb2a94

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01e6bac91f22797a08</li>
        <li>Upwork Job ID: 1755979827735597056</li>
        <li>Last Price Increase: 2024-02-16</li>
    </ul>
</details>

**Comment by FitseTLT** [comment] 2024-02-09 15:43
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
Email addresses and Timezones are exposed to anonymous users when they open the user's profile avatar

### What is the root cause of that problem?
We miss the check as in here
https://github.com/Expensify/App/blob/b9aada861c4e740a422a44c4c13c245382b1f082/src/pages/ProfilePage.js#L191-L192
### What changes do you think we should make in order to solve the problem?

We miss the check as in here
https://github.com/Expensify/App/blob/b9aada861c4e740a422a44c4c13c245382b1f082/src/pages/ProfilePage.js#L228-L229

### What alternative solutions did you explore? (Optional)

**Comment by missbond2017** [comment] 2024-02-11 07:06
`https://dev.new.expensify.com:8082/api?command=OpenPublicProfilePage`

Backend API issue, but right now, it's fixed on dev ENV.
And it couldn't reproduce.

**Comment by askavyblr** [comment] 2024-02-12 10:48
**Proposal**

**Please re-state the problem that we are trying to solve in this issue.**

Email addresses and Timezones are exposed to anonymous users when they open the user's profile avatar

**What is the root cause of that problem?**
need to add isAnonymousUser condition 

What changes do you think we should make in order to solve the problem?

Add Condition for below lines {Session.isAnonymousUser() ? (

[[App/src/pages/ProfilePage.js](https://github.com/Expensify/App/blob/b9aada861c4e740a422a44c4c13c245382b1f082/src/pages/ProfilePage.js#L191)](https://github.com/Expensify/App/blob/287613ea925964f66753892daaa3a779d61d0e2d/src/pages/ProfilePage.js#L191C1-L217C92)

What alternative solutions did you explore? (Optional)

**Comment by adelekennedy** [comment] 2024-02-13 22:56
I can reproduce - this seems like something we should address soon, @eVoloshchak can you review the proposals above?

**Comment by eVoloshchak** [comment] 2024-02-14 13:31
I do agree with @missbond2017's [conclusion](https://github.com/Expensify/App/issues/36251#issuecomment-1937455249) on this one, this should be handled on the back end. 
If this is a security concern, then simply hiding (not displaying) this data on the front end doesn't resolve it. This data is still passed from back end to front end, you could monitor network requests and still access it, even if it isn't displayed. 

I think the correct way is to make changes to the back end, it should filter the response based on the current user (so if it's an anonymous user, BE doesn't return user details such as email, timezone, etc)
@adelekennedy, could you make this internal please?

**Comment by adelekennedy** [comment] 2024-02-15 16:13
@m-natarajan I'm unable to reproduce this - I can see yuwen's information when I go to the [announce room](https://staging.new.expensify.com/r/8292963527436014) (which is expected) but can't see any any anonymous users info any more. Are you able to reproduce?

**Comment by adelekennedy** [comment] 2024-02-16 16:29
Okay! So this expected behavior for any Expensify employee but not other anonymous users - I can't reproduce it with anonymous users anymore so added retest weekly as this might have been resolved, @m-natarajan if you can still reproduce let us know!

**Comment by mallenexpensify** [comment] 2024-02-19 20:02
Coming from [here](https://expensify.slack.com/archives/C049HHMV9SM/p1708371910239629), I've added this to #vip-vsb. @fedirjh mentioned they were able to reproduce .  I _think_ the issue might have to do with caching or cookies.  i logged out from a test account this morn and when I logged back in to view a public room https://new.expensify.com/r/6776919265133947 , I had existing chats in LHN when I shouldn't have (not intending to conflate bugs, it might be related though).  

Tag me if you need me to try to retest @adelekennedy (who I think is off today)

**Comment by trjExpensify** [comment] 2024-02-19 20:32
>@fedirjh mentioned they were able to reproduce

@fedirjh can you confirm the email address of the account you clicked as an anon to reproduce this? From the OP of the issue that shows Yuwen's account being clicked, that's expected because he's an expensify.com user, and our details are available publicly to everyone -- same goes for team.expensify.com users. 

As for the example with someone on the applause.expensifail.com domain though, that user should not have been. But neither @puneetlath nor I could reproduce that where it was raised in Slack.

**Comment by trjExpensify** [comment] 2024-02-19 23:18
>@trjExpensify I retested, and it seems that the bug was addressed for non expensify.com users. I still observe Yuwen's account as anonymous, but this seems to be the expected behavior.

Yes, that's expected that as an anon you can see `expensify.com` and `team.expensify.com` details in profile. 👍

**Comment by puneetlath** [comment] 2024-02-20 16:13
It sounds like we can close this then, yeah?

**Closed** 2024-02-20 16:22 UTC
Labels: External, Daily, Help Wanted, Overdue, Bug, retest-weekly
