### ISSUE TITLE
Android - Hybrid app - For task completion, sound is not heard

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#51039] opened 2024-10-17 16:07 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 9. 0.50-0
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**If this was caught on HybridApp, is this reproducible on New Expensify Standalone?:** Y
**If this was caught during regression testing, add the test name, ID and link from TestRail:** N/A
**Issue reported by:** Applause - Internal Team

## Action Performed:
1. Launch app
2. Open a chat which had task created
3. Open the task
4. Mark as complete

## Expected Result:
For task completion, sound must be heard

## Actual Result:
For task completion, sound is not heard

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Standalone
- [x] Android: HybridApp
- [ ] Android: mWeb Chrome
- [ ] iOS: Standalone
- [ ] iOS: HybridApp
- [ ] iOS: mWeb Safari
- [ ] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

<details>
  <summary>Add any screenshot/video evidence</summary>

  
</details> 

https://github.com/user-attachments/assets/54961e03-8588-475d-aeef-ed4a6aaf69fe

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by Christinadobrzyn** [comment] 2024-10-18 04:37
Another Android HybridApp that can't be tested in Browserstack - asking the team what we should do with these issues while HybridApp isn't in Browserstack - https://expensify.slack.com/archives/C01SKUP7QR0/p1729226215766189?thread_ts=1729058100.280669&cid=C01SKUP7QR0

**Comment by Christinadobrzyn** [comment] 2024-10-21 05:40
Still discussing what to do with this hybridapp bugs - https://expensify.slack.com/archives/C01SKUP7QR0/p1729226215766189?thread_ts=1729058100.280669&cid=C01SKUP7QR0

**Comment by Christinadobrzyn** [comment] 2024-10-22 03:34
Sounds like we are currently marking these as Internal for engineering review.  I'm not able to reproduce this sound issue in other platforms.

**Comment by Christinadobrzyn** [comment] 2024-10-23 06:55
I think we can just close this - asking the team - https://expensify.slack.com/archives/C06ML6X0W9L/p1729666490891549

**Comment by Christinadobrzyn** [comment] 2024-10-24 01:59
This can be closed based on the discussion with the team.

**Closed by Christinadobrzyn** 2024-10-24 01:59 UTC
Labels: Daily, Internal, Bug, Hot Pick
