### ISSUE TITLE
[$500]  Focus on edit when keyboard shortcut is open using CTRL+J

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#29610] opened 2023-10-14 15:24 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.3.84.0
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** @dhanashree-sawant
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1697207528874409

## Action Performed:
1. Open the app
2. Open any report
3. Send any message
4. Edit the message
5. Remove all text from message and press enter, it should open delete popup
6. Press CTRL+J/CMD+J and observe that keyboard shortcut is opened but we can type in edit message

## Expected Result:
App should not keep focus on edit message when we open keyboard shortcut using CTRL+J

## Actual Result:
App keeps focus on edit message even when we open keyboard shortcut using CTRL+J

## Workaround:
Unknown 

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos
<details>
<summary>Android: Native</summary>

</details>

<details>
<summary>Android: mWeb Chrome</summary>

</details>

<details>
<summary>iOS: Native</summary>

</details>

<details>
<summary>iOS: mWeb Safari</summary>

</details>

<details>
<summary>MacOS: Chrome / Safari</summary>

https://github.com/Expensify/App/assets/93399543/2df06034-7739-412a-bb19-61f532c83ca7

https://github.com/Expensify/App/assets/93399543/c9e61d27-34df-4cb5-af98-0c168b1d71b4

https://github.com/Expensify/App/assets/93399543/f09d4920-ede7-45f2-bff7-3744d1f710ef

</details>

<details>
<summary>MacOS: Desktop</summary>

 

https://github.com/Expensify/App/assets/93399543/ebd5e85a-8b35-4dee-98ef-1107b47fc517

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~0141276117edef8487</li>
        <li>Upwork Job ID: 1713214201330978816</li>
        <li>Last Price Increase: 2023-10-28</li>
<li>Automatic offers: </li>
<ul>
<li>situchan | Contributor | 27503041</li>
<li>dhanashree-sawant | Reporter | 27503043</li>
</ul></li>
    </ul>
</details>

**Comment by abdel-h66** [comment] 2023-10-14 15:24
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
When the delete comment modal is open, opening the right-hand navigation put the focus back on the comment edit field.  

### What is the root cause of that problem?
When the delete modal is canceled, it will automatically call the `onClose` callback that does the following: 

```js
InteractionManager.runAfterInteractions(() => textInputRef.current.focus())
```

So, in summary, the Right-hand navigation when opened it dismisses any open modals, causing that `onCancel` callback to be triggered. In our case it puts the focus back on the Text input. 



### What changes do you think we should make in order to solve the problem?

Since I could not find a way to differentiate between the modal being closed by the user, or by Navigation, I decided to check for the active route when the action occurs. 

So by checking if the active route is actual report using 
```js
    const isReportRoute = Navigation.getActiveRoute().includes(`/r/${props.reportID}`)
```

We can then blur the text input whenever the route is not a report. 

```js

    useEffect(() => {
        if(isReportRoute) {
            return;
        }

        textInputRef.current.blur()
    }, [isReportRoute])
    
```




### What alternative solutions did you explore? (Optional)

I tried to update the `onClose` callback to this 

```js
    const handleOnDeleteModalCancel = useCallback(() => {
        if(!isReportRoute) {
            return;
        }
        InteractionManager.runAfterInteractions(() => textInputRef.current.focus());
    }, [isReportRoute])
```

This didn't work due to the fact that the modal is closed before the route changes. Meaning `isReportRoute` will always be true. 


N/A

**Comment by getusha** [comment] 2023-10-14 15:32
@abdel-h66 @ArekChr just to drop a note here, we shouldn't use `InteractionManager` it will cause bugs after we upgrade react-native-web to the latest version, we experienced issues like this one https://github.com/Expensify/App/pull/24482#issuecomment-1748632679.

**Comment by abdel-h66** [comment] 2023-10-14 15:40
Does it mean we are dropping the `InteractionManager`  @getusha  ? That was coming from the original implem by the way.

**Comment by getusha** [comment] 2023-10-14 15:47
@abdel-h66 we have to, most of the time its solving issues because it wraps the callback passed in setTimeout, now it uses a task queue which is not ideal to handle input focus.

**Comment by anmurali** [comment] 2023-10-24 20:00
@ArekChr this is waiting on you to pick a proposal

**Comment by ArekChr** [comment] 2023-10-25 08:33
I'm confirming that we don't want to use `InteractionManager` still waiting for more proposals.

**Comment by abdel-h66** [comment] 2023-10-25 09:04
@ArekChr In my proposal, the `InteractionManager` was not an addition of mine and it’s not the root cause. The code there is to show the definition of the onClose() that's being called.

**Comment by ArekChr** [comment] 2023-10-25 10:35
@abdel-h66 understood, thanks! Could you provide links to the files associated with the code changes mentioned in your proposal? You've included snippets of code, but it's challenging to understand the context without the file references. Thank you!

**Comment by ArekChr** [comment] 2023-10-31 12:03
@garrettmknight Hello, I am wrapping up some urgent matters today, and I will be OOO from tomorrow to Monday. Can we assign another C+ here so as not to block the task?

**Comment by situchan** [comment] 2023-10-31 12:13
I am interested in reviewing this

**Comment by DylanDylann** [comment] 2023-11-03 09:54
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
- Focus on edit when keyboard shortcut is open using CTRL+J

### What is the root cause of that problem?
- When canceling the delete modal, it will call the onClose callback function ```() => InteractionManager.runAfterInteractions(() => textInputRef.current.focus())```:
https://github.com/Expensify/App/blob/414d5913999f69d83ab08b6ae6e03325c9ede549/src/pages/home/report/ReportActionItemMessageEdit.js#L314
to focus on the composer.
- So when user press CTRL/CMD + j the confrim modal is closed and the text input of the edit report action will be focused.
### What changes do you think we should make in order to solve the problem?
- Generally, we need to blur the edit composer when the screen report screen loses focus.
- We already have the [useAutoFocus](https://github.com/Expensify/App/blob/414d5913999f69d83ab08b6ae6e03325c9ede549/src/hooks/useAutoFocusInput.js) hook used to automatically focus on the input when the screen is focused.
- Based on the ```useAutoFocus``` idea, we can create the ```useAutoBlur``` hook used to automatically blur the input when the screen lose focus. The main idea is adding:
```
    useFocusEffect(
        useCallback(() => {
            return () => {
           setTimeout(() => {
                        ReportActionComposeFocusManager.editComposerRef.current.blur();
                    }, CONST.ANIMATED_TRANSITION);
            };
        }, [ ]),
    );
```
to
[Composer](https://github.com/Expensify/App/blob/414d5913999f69d83ab08b6ae6e03325c9ede549/src/components/Composer/index.js)
### What alternative solutions did you explore? (Optional)
- NA

### Result

[Screencast from 03-11-2023 16:53:33.webm](https://github.com/Expensify/App/assets/141406735/d747e3cd-2a78-4385-ac74-6c8944a4569f)

**Comment by garrettmknight** [comment] 2023-11-03 11:06
@situchan go for it!

**Comment by situchan** [comment] 2023-11-06 15:51
I think proposed solutions are workaround. We need to prevent ahead focusing on edit composer, not blurring after wrongly focused.

**Comment by DylanDylann** [comment] 2023-11-06 16:34
@situchan justed updated [my proposal](https://github.com/Expensify/App/issues/29610#issuecomment-1792147069) in section **What alternative solutions did you explore? (Optional)**, please help check when you have a chance.

**Comment by DylanDylann** [comment] 2023-11-07 01:51
@situchan just updated my [proposal](https://github.com/Expensify/App/issues/29610#issuecomment-1792147069) in section **What alternative solutions did you explore? (Optional)**

**Comment by situchan** [comment] 2023-11-10 14:08
Evaluating updated proposal

**Comment by situchan** [comment] 2023-11-14 15:25
Not overdue

**Comment by situchan** [comment] 2023-11-20 15:03
sure, reviewing today

**Comment by DylanDylann** [comment] 2023-11-21 03:38
@situchan Also please help check my updated [proposal](https://github.com/Expensify/App/issues/29610#issuecomment-1792147069), in section **What alternative solutions did you explore? (Optional)**

**Comment by situchan** [comment] 2023-11-27 17:42
updating today

**Comment by situchan** [comment] 2023-11-28 13:02
Not overdue

**Comment by anmurali** [comment] 2023-11-29 04:56
Not overdue.

**Comment by situchan** [comment] 2023-12-04 18:58
evaluating latest proposal

**Comment by anmurali** [comment] 2023-12-06 01:56
Bumped @situchan on Slack

**Comment by tsa321** [comment] 2023-12-06 02:24
@situchan the `Modal.willAlertModalBecomeVisible(false);` already moved by other PR.
So just to summarize my current change:

in `ReportActionItemMessageEdit.js`:

```diff
-   ReportActionContextMenu.showDeleteModal(props.reportID, props.action, true, deleteDraft, () => InteractionManager.runAfterInteractions(() => textInputRef.current.focus()));
+   ReportActionContextMenu.showDeleteModal(props.reportID, props.action, true, deleteDraft);

```

just remove the callback.

**Comment by situchan** [comment] 2023-12-13 11:29
can everyone update proposals based on latest codebase?

**Comment by anmurali** [comment] 2023-12-13 15:01
not overdue, waiting on updated proposals

**Comment by DylanDylann** [comment] 2023-12-13 15:50
@situchan Update my [proposal](https://github.com/Expensify/App/issues/29610#issuecomment-1792147069)

**Comment by tsa321** [comment] 2023-12-13 23:45
@situchan Updated my [proposal](https://github.com/Expensify/App/issues/29610#issuecomment-1780939581)

**Comment by situchan** [comment] 2023-12-18 18:39
reviewing updated proposals

**Comment by anmurali** [comment] 2023-12-19 21:12
@situchan what's the verdict?

**Comment by situchan** [comment] 2023-12-25 11:15
I will provide update this week

**Comment by anmurali** [comment] 2024-01-02 23:58
@situchan can you please update this issue?

**Comment by situchan** [comment] 2024-01-02 23:59
Just back from holidays. I will provide update by tomorrow

**Comment by situchan** [comment] 2024-01-08 17:22
@tsa321's [proposal](https://github.com/Expensify/App/issues/29610#issuecomment-1780939581) works fine to me.
@DylanDylann have you found any issue with this solution of removing onCancel callback?

**Comment by DylanDylann** [comment] 2024-01-08 17:27
@situchan My [solution](https://github.com/Expensify/App/issues/29610#issuecomment-1792147069) does not contain "removing onCancel callback". Please give me more details. Thanks

**Comment by situchan** [comment] 2024-01-08 17:28
I prefer simple solution to introducing new flag

**Comment by DylanDylann** [comment] 2024-01-08 17:29
@situchan Ah, I see. Let me check again if the solution "removing onCancel callback" have any issue

**Comment by DylanDylann** [comment] 2024-01-08 17:54
@situchan I just checked the solution that you mentioned [here](https://github.com/Expensify/App/issues/29610#issuecomment-1881516149). It works well on chrome but does not work on android native. Can you help double check

**Comment by situchan** [comment] 2024-01-08 18:11
Good find. Seems like that callback was intentionally added for native.

**Comment by tsa321** [comment] 2024-01-09 05:46
@situchan Should we limit the use of the callback for native only?

**Comment by situchan** [comment] 2024-01-09 07:13
It's unusual case but we enabled shortcut on native as well.

**Comment by anmurali** [comment] 2024-01-10 02:24
Actively working on picking a proposal. Not overdue.

**Comment by situchan** [comment] 2024-01-15 11:08
ok so we should not remove onCancel callback.
Now @DylanDylann's proposal is remaining, which I am still evaluating to find any regressions.

**Comment by anmurali** [comment] 2024-01-16 20:35
Still working on identifying proposals.

**Comment by tsa321** [comment] 2024-01-16 23:43
@situchan How about my original [proposal](https://github.com/Expensify/App/issues/29610#issuecomment-1780939581), in the archive section:

When RHN / right panel is opened the onyx modal isVisible value will be true and we already have this useEffect based on onyx modal:

https://github.com/Expensify/App/blob/414d5913999f69d83ab08b6ae6e03325c9ede549/src/pages/home/report/ReportActionItemMessageEdit.js#L136-L138

we could use this useEffect to add this lines of code:
```javascript
if(modal.isVisible || modal.willAlertModalBecomeVisible) {
       textInputRef.current.blur();
}
```
before or after `InputFocus.composerFocusKeepFocusOn`.

**Comment by situchan** [comment] 2024-01-22 22:08
@tsa321 it will still focus first and then blur manually, which doesn't fix the root cause, right?

**Comment by anmurali** [comment] 2024-01-22 22:45
Still discussing proposals.

**Comment by anmurali** [comment] 2024-01-30 00:14
(Solution is being discussed)

**Comment by tsa321** [comment] 2024-01-30 01:48
> How about removing onCancel callback for web only?

@situchan That is what I said [here](https://github.com/Expensify/App/issues/29610#issuecomment-1882448233):

> @situchan Should we limit the use of the callback for native only?

Let me test...

**Comment by tsa321** [comment] 2024-01-31 03:23
@situchan we could add a library function, something like: `focusEditTextInputAfterCancelDelete` with `.native.ts` and `.index.ts` and only focus the textinput in `native.ts` file.
Or we could use `DeviceCapabilities.hasHoverSupport()` check in the onCancel callback to determine whether we should focus the edittextInput or not.

**Comment by situchan** [comment] 2024-02-02 12:50
@tsa321 ok, please update proposal. I will do final test and approve

**Comment by tsa321** [comment] 2024-02-02 15:06
### Proposal

@situchan I have updated my [proposal](https://github.com/Expensify/App/issues/29610#issuecomment-1780939581)

**Comment by situchan** [comment] 2024-02-06 15:29
@tsa321's [proposal](https://github.com/Expensify/App/issues/29610#issuecomment-1780939581) looks good to me.
🎀 👀 🎀 C+ reviewed

**Comment by tsa321** [comment] 2024-02-07 12:49
Thank you, my plan is to submit a PR within three days.

**Comment by anmurali** [comment] 2024-02-08 16:15
@tsa321 is working on this PR

**Comment by anmurali** [comment] 2024-02-16 16:20
Deployed yesterday. Adding a BZ backup to handle payments here as I will be OOO

**Comment by hayata-suenaga** [comment] 2024-02-26 15:35
[deployed to production two weeks ago](https://github.com/Expensify/App/pull/36195#issuecomment-1945393555)

please handle the payments when you have time 🙇

**Comment by hayata-suenaga** [comment] 2024-02-28 16:27
waiting for payment

**Comment by hayata-suenaga** [comment] 2024-03-01 19:21
melvin, we're just waiting for payment

**Comment by situchan** [comment] 2024-03-01 19:23
@hayata-suenaga please remove `Reviewing` label. This will make overdue and bump BZ in a timely manner

**Comment by hayata-suenaga** [comment] 2024-03-01 19:33
ah I didn't realize the tag is still attached. thank you @situchan!

**Comment by hayata-suenaga** [comment] 2024-03-12 20:46
waiting for payment

**Comment by zanyrenney** [comment] 2024-03-13 12:31
Didn't realise if this was waiting on me or @anmurali

**Comment by zanyrenney** [comment] 2024-03-13 12:32
@tsa321 is the non-agency contributor who authored the PR and @situchan is the C+ who reviewed the PR.

**Comment by zanyrenney** [comment] 2024-03-13 12:33
**payment summary**
paid $500 @situchan

**Comment by zanyrenney** [comment] 2024-03-13 12:33
@tsa321 is not hired on the upwork job, can they link their upwork profile please? I can't find them and this job is now closed so we will need to issue a payment separately.

**Comment by zanyrenney** [comment] 2024-03-13 12:34
I've done one of the payments, just waiting on @tsa321 ^

**Comment by tsa321** [comment] 2024-03-14 00:47
@zanyrenney my upwork profile is : https://www.upwork.com/freelancers/~01bfc26d267bade652
Thank you

**Comment by dhanashree-sawant** [comment] 2024-03-15 18:11
Hi @zanyrenney, whenever you are available, can you check if this issue is eligible for reporting bonus?

**Comment by zanyrenney** [comment] 2024-03-19 17:31
no reporting bonus.

**Comment by zanyrenney** [comment] 2024-03-19 17:31
@tsa321 I asked you to apply for the job - please apply on the job posting on upwork.

**Comment by anmurali** [comment] 2024-03-19 21:46
Since this is chat focussed bug, I am putting this in #vip-vsb.

**Comment by tsa321** [comment] 2024-03-19 23:36
@zanyrenney Do you mean this upwork job: https://www.upwork.com/jobs/~0141276117edef8487 ?
It says `this job is no longer available`...

**Comment by tsa321** [comment] 2024-03-29 22:44
cc @zanyrenney

**Comment by hayata-suenaga** [comment] 2024-04-01 15:04
Zany has been OOO. She will come back online this week. Please wait a little bit for that 🙇 @tsa321

**Comment by zanyrenney** [comment] 2024-04-02 14:34
Hi @tsa321 I have just sent you a manual offer for the job, please accept.

**Comment by zanyrenney** [comment] 2024-04-02 14:34
@hayata-suenaga thanks for the message above, appreciate it! <3

**Comment by tsa321** [comment] 2024-04-03 00:53
Thank you @zanyrenney , I have accepted the offer

**Comment by hayata-suenaga** [comment] 2024-04-12 19:15
waiting for payment

**Comment by tsa321** [comment] 2024-04-19 23:27
cc: @zanyrenney

**Closed** 2024-04-29 17:15 UTC
Labels: Engineering, Weekly, Internal, Overdue, Bug

**Comment by dhanashree-sawant** [comment] 2024-05-01 10:44
Hi @zanyrenney @hayata-suenaga,  is it eligible for reporting bonus?
