### ISSUE TITLE
[$500] Desktop - Avatar isn't showing in the chat row until clicking into that row

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#29460] opened 2023-10-12 15:22 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.3.80.1
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** @kevinksullivan 
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1697055821976289

## Action Performed:
1. Sent a DM message to ~20 customers via our internal compose tool
2. Logged in
3. Saw the DMs

## Expected Result:
All DMs would have the avatar of the person I am speaking with in the row

## Actual Result:
 Some of the DMs didn't show an avatar until clicking into that DM

## Workaround:
Unknown 

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [ ] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos
<details>
<summary>Android: Native</summary>

</details>

<details>
<summary>Android: mWeb Chrome</summary>

</details>

<details>
<summary>iOS: Native</summary>

</details>

<details>
<summary>iOS: mWeb Safari</summary>

</details>

<details>
<summary>MacOS: Chrome / Safari</summary>

</details>

<details>
<summary>MacOS: Desktop</summary>

 
![image](https://github.com/Expensify/App/assets/93399543/bed85757-e000-4348-976c-e74e5a1f5940)

http://g.recordit.co/96JvXGqDgK.gif

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~016c1d1ffb1e39b663</li>
        <li>Upwork Job ID: 1712488974749863936</li>
        <li>Last Price Increase: 2023-11-02</li>
    </ul>
</details>

**Comment by stephanieelliott** [comment] 2023-10-17 01:50
Seeing as this applies to the Compose tool this will need to be internal.

**Comment by stephanieelliott** [comment] 2023-10-20 00:35
Not overdue, forgot I to also add Engineering label. 

Just want to check first though -- @situchan do you agree that this needs an internal engineer to make BE changes?

**Comment by situchan** [comment] 2023-10-24 11:15
@stephanieelliott I think we should fix this in frontend.

**Comment by stephanieelliott** [comment] 2023-10-25 23:04
Ah ok, thanks @situchan, adjusting labels.

**Comment by stephanieelliott** [comment] 2023-10-30 16:31
Not overdue, awaiting proposals.

**Comment by stephanieelliott** [comment] 2023-10-31 22:01
Still awaiting proposals.

**Comment by barttom** [comment] 2023-11-06 12:06
Hi! I'm Bartek from Callstack and would to work in this issue. I'm gonna start to debug this and I'll be back with a proposal ASAP.

**Comment by barttom** [comment] 2023-11-06 12:59
Could You just explain what is 'internal compose tool'? 
Just wonder if I'm able to reproduce that by sending messages from. the app
@situchan @stephanieelliott

**Comment by situchan** [comment] 2023-11-06 13:04
I am not sure. @kevinksullivan or @stephanieelliott may have answer.

**Comment by stephanieelliott** [comment] 2023-11-06 21:51
Hey @kevinksullivan are you referring to the Compose tool in Concierge? Or are you referring to sending a group DM in newdot?

**Comment by barttom** [comment] 2023-11-07 15:56
@kevinksullivan please send more information on how You send these 20s messages. That  helps me to reproduce the issue ;)

**Comment by stephanieelliott** [comment] 2023-11-07 16:51
Looking at the thread in Slack, this seems to be our internal composer tool. As discussed there we should move this back to internal! 

https://expensify.slack.com/archives/C049HHMV9SM/p1697055821976289

**Comment by puneetlath** [comment] 2023-11-07 16:54
Does this affect the users receiving the messages? Or just our internal employees?

**Comment by stephanieelliott** [comment] 2023-11-07 17:26
@puneetlath it affects the message sender only - so only our internal employees in this case!

**Comment by puneetlath** [comment] 2023-11-07 23:11
Ok got it. Seems not super urgent then. 

And when you sign out and sign back in, are the avatars in the LHN? My guess is that we don't send a pusher update which is why this is the case.

**Comment by puneetlath** [comment] 2023-11-10 22:07
@stephanieelliott just a friendly bump on the question above when you have a chance.

**Comment by stephanieelliott** [comment] 2023-11-13 18:40
Just tested @puneetlath -- yep, the avatars populate in the LHN on signout/signin!

**Comment by stephanieelliott** [comment] 2023-11-21 05:50
Hey @puneetlath what do you think about this one -- worth fixing? If yes, does it need to be fixed internally or is there a portion we can make external?

**Comment by puneetlath** [comment] 2023-11-21 05:55
I'm thinking that it's not worth fixing right now since it only affects internal employees. What do you think?

**Comment by stephanieelliott** [comment] 2023-11-21 05:59
I agree, esp considering it doesn't affect functionality. Let's close it for now!

**Closed by stephanieelliott** 2023-11-21 05:59 UTC
Labels: Engineering, Weekly, Internal, Bug
