### ISSUE TITLE
[$250] VBA -URL is shown on bottom left corner when `Fix the error ` is hovered reported by @huzaifa-99

### ISSUE THREAD

**Issue by kavimuru** [Expensify/App#12692] opened 2022-11-12 02:45 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:

1. Navigate to /bank-account/BankAccountStep
2. Click on the first field, and then click outside, just to blur the field and force the validation error to be shown
3. Notice that an error label appears before submit button with blue coloured “fix the errors” text inside the label
4. Hover on “fix the errors” text
5. Notice it shows url address on bottom/left corner of the browser with the current url address set

## Expected Result: 
The label “fix-the-errors” should not show url-address when hovered

## Actual Result: 
“fix-the-errors” label is showing the current url as address on bottom-left screen corner when hovered

## Workaround:
unknown

## Platform:

Where is this issue occurring?

- Web

**Version Number:** 1.2.27-3
**Reproducible in staging?:** y
**Reproducible in production?:** y
**Email or phone of affected tester (no customers):** 
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** 

https://user-images.githubusercontent.com/43996225/201452993-388bb712-3673-4a28-822c-43aeb6623b99.mp4
<img width="960" alt="Untitled" src="https://user-images.githubusercontent.com/43996225/201453033-780c7592-7027-4c2c-8758-d1d51bf7f40e.png">

**Expensify/Expensify Issue URL:** 
**Issue reported by:** @huzaifa-99
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1668124426446149

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by hungvu193** [comment] 2022-11-12 17:29
<b>Proposal</b>
In our current `TextLink.js` component, we are using the href props, that's why we see the bottom left url when the cursor hovered it.
https://github.com/Expensify/App/blob/0d653cad15c32150c302ac12dc0acdbca1ece18b/src/components/TextLink.js#L60-L66
<b>Solution</b>
 To make it didn't show the bottom left url when hovered we can pass `undefined` as href prop. In some case, we need to use the `TextLink.js` but we didn't pass the href (like in this issue), we need to defined the props default value.
```diff
        <Text
            style={[styles.link, ...additionalStyles]}
            accessibilityRole="link"
-           href={props.href} 
+           href={props.href ? props.href : undefined}
            onPress={openLink}
            onKeyDown={openLinkIfEnterKeyPressed}
        >
            {props.children}
        </Text>
```

Result:

https://user-images.githubusercontent.com/16502320/201486937-76c1a004-234a-4c51-a42f-4210b25e22b1.mov

**Comment by huzaifa-99** [comment] 2022-11-13 20:35
### Proposal
The issue has origins in `FormAlertWrapper`. We are using a `TextLink` there which display the current url when hovered
https://github.com/Expensify/App/blob/1b375ed3d3a7e1e42d8e746cb0e6f205ee0a3786/src/components/FormAlertWrapper.js#L59-L64

Since we are not passing an actual link/href prop, this `TextLink` can be replaced with a normal `Text` component and adding link styles
```js
<Text
    style={[styles.label, styles.link]}
    onPress={props.onFixTheErrorsLinkPressed}
>
    {props.translate('common.fixTheErrors')}
</Text>
```
which fixes the bug

### Demo

https://user-images.githubusercontent.com/68777211/201543329-45528a86-b6fb-464f-8f39-8376afd4be4e.mp4

**Comment by huzaifa-99** [comment] 2022-11-13 20:44
I thought we are not handling `accessibility` as discussed [here](https://expensify.slack.com/archives/C01GTK53T8Q/p1668197149475149)

**Comment by huzaifa-99** [comment] 2022-11-13 20:57
### Updated Proposal (original https://github.com/Expensify/App/issues/12692#issuecomment-1312815631)
If not breaking accessibility is a concern than we can wrap the `Text` in a `Pressable` and add the press callback there. And since it will be nested inside a `Text` it might break wrapping on native, so we can wrap it in a `View`. 

Basically replacing this whole block 
https://github.com/Expensify/App/blob/1b375ed3d3a7e1e42d8e746cb0e6f205ee0a3786/src/components/FormAlertWrapper.js#L57-L66 with
```js
<View style={{ flexDirection: 'row' }}>
    <Text style={[styles.formError, styles.mb0]}>
        {`${props.translate('common.please')} `}
    </Text>
    <Pressable onPress={props.onFixTheErrorsLinkPressed}>
        <Text style={[styles.label, styles.link]}>
            {props.translate('common.fixTheErrors')}
        </Text>
    </Pressable>
    <Text style={[styles.formError, styles.mb0]}>
        {` ${props.translate('common.inTheFormBeforeContinuing')}.`}
    </Text>
</View>
```  
This also achieves the same result but accessibility is not broken

**Comment by hungvu193** [comment] 2022-11-14 11:33
> ```js
> link
> ```

This will cause an error console on web, you need to make sure there's no console error happened with your solution.

**Comment by huzaifa-99** [comment] 2022-11-14 12:24
@hungvu193 i see no console errors specific to this change. Can you please describe a little more? Thanks

---

@mdneyazahmad yes still reproducible on `v1.2.27-3`

**Comment by huzaifa-99** [comment] 2022-11-14 13:57
Hm strange, I don't get this error. Can you please expand the log to see the stack trace. Thanks in advance

For a reference please see this demo (ignore the 30x git file changes in my vscode, they are just console logs)

https://user-images.githubusercontent.com/68777211/201677553-68c0b9a6-d274-4065-b93d-6e8f85a394bb.mp4

**Comment by hungvu193** [comment] 2022-11-14 14:41
@huzaifa-99 Sure, here you are
<img width="1099" alt="Screen Shot 2022-11-14 at 21 40 52" src="https://user-images.githubusercontent.com/16502320/201688254-42f7fae8-2e31-4add-b3fa-4c9a370b96a3.png">

**Comment by huzaifa-99** [comment] 2022-11-14 14:52
@hungvu193 I see where the problem is.

In your video demo, you are using this code
```
<Pressable 
    style={[styles.label, styles.link]}
    onPress={props.onFixTheErrorsLinkPressed}
>    
    {props.translate('common.fixTheErrors')}
</Pressable>
```
but in your comment [here](https://github.com/Expensify/App/issues/12692#issuecomment-1313540500), it was different. That's why you get the error because `{props.translate('common.fixTheErrors')}` should be wrapped in a `Text` element

Again see my proposal [here](https://github.com/Expensify/App/issues/12692#issuecomment-1312819881) for the correct code block

**Comment by zanyrenney** [comment] 2022-11-14 17:44
The job listing is here: https://www.upwork.com/jobs/~01bd917604edb70bce

**Comment by zanyrenney** [comment] 2022-11-15 13:31
Hey @aldo-expensify - let me know what you think of these proposals and who we should hire.

**Comment by parasharrajat** [comment] 2022-11-15 14:38
I am checking it...

**Comment by parasharrajat** [comment] 2022-11-15 17:12
I do not consider this an issue. Why do we think this is an issue? an empty href value is completely valid just like `href="#"`. 

So `href=""` and `href="#"` is valid. It does not break anything for the user. @aldo-expensify Do you think we should fix it?

**Comment by aldo-expensify** [comment] 2022-11-16 00:37
I'm pretty undecided about this, thoughts:

- Agree with that this is not necessarily an "issue", but I think the link showing in the corner has no value and if it can be removed easily without "workarounds", I think it is better to not have it.
- This has a very low ROI
- I tested the [proposal](https://github.com/Expensify/App/issues/12692#issuecomment-1313948756) by @mdneyazahmad, and it does seem to work without breaking accessibility (tab navigation still works)

If the [proposal](https://github.com/Expensify/App/issues/12692#issuecomment-1313948756) doesn't break other stuff, I think it would be fine to proceed with it, but it worries me a bit because it touches the default value for a prop of a widely used component.

If the mentioned proposal breaks something or doesn't work well, I think we should just close this issue because it is not worth spending more time for such low ROI

@parasharrajat what are your thoughts on the the [proposal](https://github.com/Expensify/App/issues/12692#issuecomment-1313948756)?

**Comment by JmillsExpensify** [comment] 2022-11-16 04:33
> If the mentioned proposal breaks something or doesn't work well, I think we should just close this issue because it is not worth spending more time for such low ROI

For what it's worth, this is where I'm at. If we can't come up with a proposal without side-effects, then I think we should close this issue.

**Comment by parasharrajat** [comment] 2022-11-16 20:21
I checked and It seems that `defaultValue` of null does not break the tab navigation. @mdneyazahmad can you confirm that this change won't break anything?

**Comment by aldo-expensify** [comment] 2022-11-16 20:24
@mdneyazahmad 
In case it is of use, I found the following places where `TextLink` is used without passing `href`:

https://github.com/Expensify/App/blob/e79e484e6cb60b2c18b2aa7d559fe0a0349a084f/src/components/PDFView/PDFInfoMessage.js#L32-L34
https://github.com/Expensify/App/blob/e79e484e6cb60b2c18b2aa7d559fe0a0349a084f/src/pages/ReimbursementAccount/ACHContractStep.js#L250-L252
https://github.com/Expensify/App/blob/e79e484e6cb60b2c18b2aa7d559fe0a0349a084f/src/pages/ReimbursementAccount/ACHContractStep.js#L257-L260
https://github.com/Expensify/App/blob/e79e484e6cb60b2c18b2aa7d559fe0a0349a084f/src/pages/ReimbursementAccount/ValidationStep.js#L139-L141
https://github.com/Expensify/App/blob/e79e484e6cb60b2c18b2aa7d559fe0a0349a084f/src/pages/workspace/bills/WorkspaceBillsFirstSection.js#L58-L62

It would be good to at least test that things don't break in these places (not sure if I missed one)

**Comment by hungvu193** [comment] 2022-11-17 02:12
@parasharrajat how about the undefined href props as I mentioned.

**Comment by hungvu193** [comment] 2022-11-17 02:47
> @hungvu193 your question on the [proposal](https://github.com/Expensify/App/issues/12692#issuecomment-1312533798)
> 
> `href: undefined` as a default value also seems to work fine without breaking accessibility (at least tab navigation seems to work fine for me). `href: undefined` and `href: null` seems to achieve equivalent results, and I'm leaning toward `undefined` because that is closer to the value we would see if the prop was not provided.
> 
> The following part of the proposal I don't think it makes sense to implement here:
> 
> <img alt="image" width="531" src="https://user-images.githubusercontent.com/87341702/202341746-683ac3d5-dc4f-47c5-b083-8f51b452b1aa.png">
> 
> I feel like I may be missing something because of the accessibility concerns raised earlier, I haven't noted this problems, but maybe I'm not testing this correctly.

Yeah, I gave 2 options in my proposal, check the props or give it defaultValue, I also prefer defaultProps so we don't need to update it anywhere else.

**Comment by parasharrajat** [comment] 2022-11-17 12:32
I don't know what was wrong the last time I checked, using `undefined` default value was breaking Tabbing on the `fix the errors` link. 

But now, it is working fine. @hannojg Can you please confirm https://github.com/Expensify/App/issues/12692#issuecomment-1317623554 https://github.com/Expensify/App/issues/12692#issuecomment-1317619029?

**Comment by hannojg** [comment] 2022-11-17 12:40
_confused_, I haven't touched any of the code of was working on this issue 😅 are you sure you mean me?

**Comment by parasharrajat** [comment] 2022-11-17 15:05
Lol, sorry @hannojg. Tagged the wrong guy. Its @hungvu193.

**Comment by hungvu193** [comment] 2022-11-17 15:24
> 

Just check, it's working fine with undefined props. Also we can reference in react-native-web documentation [here](https://necolas.github.io/react-native-web/docs/text/):
```
href: ?string
If href is defined, the view is rendered as an anchor tag pointing to this URL.
```

<img width="1680" alt="Screen Shot 2022-11-17 at 22 16 36" src="https://user-images.githubusercontent.com/16502320/202486212-85026b7b-1ade-438d-ab49-2cbc67321c05.png">

<img width="1658" alt="Screen Shot 2022-11-17 at 22 17 51" src="https://user-images.githubusercontent.com/16502320/202486202-14e69c29-8d10-4d18-8ec6-2a4ce01bfffd.png">

**Comment by parasharrajat** [comment] 2022-11-17 18:17
@hungvu193 's [proposal](https://github.com/Expensify/App/issues/12692#issuecomment-1312533798) option 2 looks good to me. They were first so let's go with it. 

Thanks, everyone. 

cc: @aldo-expensify 

:ribbon: :eyes: :ribbon:  C+ reviewed

**Comment by aldo-expensify** [comment] 2022-11-17 21:23
Thanks @parasharrajat !

I tested quickly using `undefined` as default value for `href` (this [proposal](https://github.com/Expensify/App/issues/12692#issuecomment-1312533798)). I tested in Web Chrome, Web Safari and Desktop, didn't see any bug caused by this and the tab navigation continued working.

Assigning to @hungvu193

**Comment by hungvu193** [comment] 2022-11-18 02:58
[PR](https://github.com/Expensify/App/pull/12858) is ready for review guys 👀

**Comment by zanyrenney** [comment] 2022-11-21 15:37
@aldo-expensify could you please review the PR and let me know what you think!

**Comment by aldo-expensify** [comment] 2022-11-21 18:43
I'll review today. @parasharrajat if you have some time today, please review too :)

**Comment by parasharrajat** [comment] 2022-11-21 18:54
yeah, I am just adding the screenshots.

**Comment by aldo-expensify** [comment] 2022-11-21 18:55
Thanks!

**Comment by hungvu193** [comment] 2022-11-22 02:30
> The job listing is here: https://www.upwork.com/jobs/~01bd917604edb70bce

@zanyrenney I've just applied.

**Comment by zanyrenney** [comment] 2022-11-24 12:15
I am having troubles logging in to Upwork just now: 
<img width="1151" alt="2022-11-24_12-15-07" src="https://user-images.githubusercontent.com/56830058/203782208-191ce641-b959-42c6-99a2-19b12eae521c.png">

I'll hire you when I get it sorted, sorry @hungvu193

**Comment by hungvu193** [comment] 2022-11-24 12:19
> I am having troubles logging in to Upwork just now: <img alt="2022-11-24_12-15-07" width="1151" src="https://user-images.githubusercontent.com/56830058/203782208-191ce641-b959-42c6-99a2-19b12eae521c.png">
> 
> I'll hire you when I get it sorted, sorry @hungvu193

no worries :)

**Comment by zanyrenney** [comment] 2022-11-24 12:32
Ah glad to know it isn't just me 😅

**Comment by zanyrenney** [comment] 2022-11-24 13:15
I got back in and have hired you @hungvu193 - let me know if you have any further questions :)

**Comment by hungvu193** [comment] 2022-11-24 13:35
> I got back in and have hired you @hungvu193 - let me know if you have any further questions :)

Thank you, I accepted your offer :)

**Comment by huzaifa-99** [comment] 2022-11-24 14:07
@zanyrenney am I eligible for reporting on this?

**Comment by zanyrenney** [comment] 2022-11-28 14:39
Hired contributors, waiting on the reviews @aldo-expensify @parasharrajat

**Comment by parasharrajat** [comment] 2022-11-28 14:59
PR deployed to PROD 5 days back. https://github.com/Expensify/App/pull/12858#issuecomment-1325784980

**Comment by zanyrenney** [comment] 2022-11-29 16:35
Waiting until the 7 days and then we will be ready for payment.

**Comment by zanyrenney** [comment] 2022-12-02 10:22
sent the payment to you both on upwork @hungvu193 @huzaifa-99 - any questions, lmk!

**Comment by hungvu193** [comment] 2022-12-02 10:25
@zanyrenney Since the PR was merged within 3 days, Can I have the bonus as well?

**Comment by parasharrajat** [comment] 2022-12-04 15:05
@zanyrenney Could you please send me offer for C+?

**Comment by aldo-expensify** [comment] 2022-12-08 22:33
Friendly bump @zanyrenney

**Comment by zanyrenney** [comment] 2022-12-12 17:20
have also extended the contract to you @parasharrajat - please accept it so I can pay it out. 

@hungvu193 bonus has been paid.

**Comment by zanyrenney** [comment] 2022-12-15 18:37
@parasharrajat paid, inc bonus! closing this issue out now as everyone has been paid.

**Closed by zanyrenney** 2022-12-15 18:37 UTC
Labels: External, Daily, Overdue, Bug
