### ISSUE TITLE
[HOLD for payment 2023-11-06] [HOLD for payment 2023-11-02] [$500] Login - Email address does not remain when refresh Magic Code page and hit Go back button

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#29192] opened 2023-10-10 14:03 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.3.80-0

**Reproducible in staging?:** Yes

**Reproducible in production?:** Yes

**If this was caught during regression testing, add the test name, ID and link from TestRail:**

**Email or phone of affected tester (no customers):**

**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Expensify/Expensify Issue URL:**

**Issue reported by:** Applause - Internal Team

**Slack conversation:**

## Action Performed:
1. Navigate to staging.new.expensify.com
2. Enter e-mail address & click Sign in button
3. Refresh the page
4. Hit Go back button

## Expected Result:
Once added, e-mail address should remain after refreshing Magic Code page and hit Go back button

## Actual Result:
Email address does not remain when refresh Magic Code page and hit Go back button

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [x] Android: mWeb Chrome
- [ ] iOS: Native
- [x] iOS: mWeb Safari
- [x] Windows: Chrome 
- [ ] MacOS: Desktop

## Screenshots/Videos
<details>
<summary>Android: Native</summary>

</details>

<details>
<summary>Android: mWeb Chrome</summary>

</details>

<details>
<summary>iOS: Native</summary>

</details>

<details>
<summary>iOS: mWeb Safari</summary>

</details>

<details>
<summary>Windows: Chrome </summary>

 

https://github.com/Expensify/App/assets/78819774/8a2752c8-4a34-42d6-ad30-c430b453ed5d

</details>

<details>
<summary>MacOS: Desktop</summary>

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~0181306db2b58c51f7</li>
        <li>Upwork Job ID: 1714251654275936256</li>
        <li>Last Price Increase: 2023-10-17</li>
<li>Automatic offers: </li>
<ul>
<li>fedirjh | Reviewer | 27339710</li>
<li>bernhardoj | Contributor | 27339711</li>
</ul></li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @zanyrenney</details>

**Comment by sonialiap** [comment] 2023-10-17 12:06
Reproducible

**Comment by sonialiap** [comment] 2023-10-17 12:07
I'm OOO Oct 16-23. Adding leave buddy

Status: looking for proposals

**Comment by leijia322** [comment] 2023-10-18 00:21
The root cause of this problem is that the login input value is stored in a simple state using the code provided and when the web app is refreshed, the value stored in this state is cleared.

To solve this issue and retain the login input after a web app refresh, you can use a different approach by saving and retrieving the login data from a more persistent storage location. One possible solution is to store the login input data in a client-side storage like localStorage or a cookie. This way, even if the web app is refreshed, the login data can be retrieved from the client-side storage and populated back into the input field when the user returns to the login form.

**Comment by leijia322** [comment] 2023-10-18 00:27
Contributor details
My Expensify account email: leijia322@gmail.com
Upwork Profile Link: https://www.upwork.com/freelancers/~019ec726f12bc9ad91

**Comment by rahimiam** [comment] 2023-10-18 19:16
Proposed Solution
To address this, we can pass the credentials as props to the LoginForm. I've written the necessary code changes and tested them locally, and they appear to resolve the issue.

Next Steps
If this solution aligns with the project's direction, I'm ready to create a pull request for a more thorough review. Please let me know how we should proceed.

Contributor details
My Expensify account email: irahimiam@gmail.com
Upwork Profile Link: https://www.upwork.com/freelancers/~01e7d8746987c01ca7

**Comment by rahimiam** [comment] 2023-10-18 19:27
Proposed Solution
To address this, we can pass the credentials as props to the LoginForm. I've written the necessary code changes and tested them locally, and they appear to resolve the issue.

Next Steps
If this solution aligns with the project's direction, I'm ready to create a pull request for a more thorough review. Please let me know how we should proceed.

Contributor details
My Expensify account email: [irahimiam@gmail.com](mailto:irahimiam@gmail.com)
Upwork Profile Link: https://www.upwork.com/freelancers/~01e7d8746987c01ca7

**Comment by rahimiam** [comment] 2023-10-20 12:21
## Proposal
[Updated](https://github.com/Expensify/App/issues/29192#issuecomment-1769184988)

**Comment by marcochavezf** [comment] 2023-10-24 00:20
Thanks @fedirjh, the proposal LGTM too, assigning @bernhardoj 🚀

**Comment by zanyrenney** [comment] 2023-10-25 13:39
Not sure why I am assigned to this, removing as @sonialiap is the assignee who has done all the work here!

**Comment by sonialiap** [comment] 2023-11-06 11:14
@fedirjh review + bonus = $750 - paid ✔️ 
@bernhardoj fix + bonus = $750 - paid ✔️

**Comment by sonialiap** [comment] 2023-11-06 11:14
@fedirjh please complete the checklist https://github.com/Expensify/App/issues/29192#issuecomment-1784624336

**Closed** 2023-11-10 17:27 UTC
Labels: External, Daily, Overdue, Awaiting Payment, Bug
