### ISSUE TITLE
[$500] Web - Infinite loader appears when navigate to restricted links

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#34800] opened 2024-01-19 13:52 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.27-0
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** Applause - Internal Team
**Slack conversation:**

## Action Performed:
1. Log in to staging.new.expensify.com
2. Navigate to each of the following links
https://staging.new.expensify.com/r/6821704960193694/details
https://staging.new.expensify.com/r/6821704960193694/participants
https://staging.new.expensify.com/r/6821704960193694/settings

## Expected Result:
User should be redirected to a blank conversation with a message indicating that the user doesn't have access in web and to LHN in mobile view

## Actual Result:
"Hmm it is not here..." page appear but there is Infinite loader on RHN

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details> 

https://github.com/Expensify/App/assets/78819774/a4340729-0540-4c0e-be1c-b5d11ae2f036

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by shahinyan11** [comment] 2024-01-19 14:41
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
Web - Infinite loader appears when navigate to restricted links
### What is the root cause of that problem?
The pages are wrapped in `WithReportOrNotFound` which has condition to show `NotFoundPage`. 
### What changes do you think we should make in order to solve the problem?
We should change to not display the NotFoundPage. To do that we can change this line with below code
```
 return Navigation.goBack(ROUTES.REPORT_WITH_ID_DETAILS.getRoute(props.report?.reportID))
```

### What alternative solutions did you explore? (Optional)

**Comment by DylanDylann** [comment] 2024-01-22 06:33
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
- Web - NotFoundPage appears when navigating to restricted links
### What is the root cause of that problem?
- **The behavior mentioned in this issue no longer appeared. The latest behavior is that, the NotFoundPage displayed in the RHN instead of Infinite loader**
- The NotFoundPage displayed because we had a logic below:
https://github.com/Expensify/App/blob/a3856f728adbff0ea855505a3a1f4d861d781c72/src/pages/home/report/withReportOrNotFound.tsx#L56-L59
- As we can see, when the [shouldShowNotFoundPage](https://github.com/Expensify/App/blob/a3856f728adbff0ea855505a3a1f4d861d781c72/src/pages/home/report/withReportOrNotFound.tsx#L43) is ```true```, the NotFoundPage is displayed.
### What changes do you think we should make in order to solve the problem?
- If we want "User should be redirected to a blank conversation with a message indicating that the user doesn't have access in web and to LHN in mobile view", we just need to add the useEffect to [withReportOrNotFound](https://github.com/Expensify/App/blob/a3856f728adbff0ea855505a3a1f4d861d781c72/src/pages/home/report/withReportOrNotFound.tsx):
```
                    useEffect(() => {
                    if (shouldShowNotFoundPage) {
                        Navigation.goBack();
                    }
                }, [shouldShowNotFoundPage]);
```
- Then, update:
https://github.com/Expensify/App/blob/a3856f728adbff0ea855505a3a1f4d861d781c72/src/pages/home/report/withReportOrNotFound.tsx#L48-L50
to (to avoid rendering FullScreenLoadingIndicator or NotFoundPage when animating transition) :
````diff
+              if (shouldShowNotFoundPage) {
                    return null;
                }
````

### What alternative solutions did you explore? (Optional)

- NA

**Comment by DylanDylann** [comment] 2024-01-22 06:36
@trjExpensify Can you confirm the expected behavior in this issue. Is this "User should be redirected to a blank conversation with a message indicating that the user doesn't have access in web and to LHN in mobile view" ?

**Comment by cubuspl42** [comment] 2024-01-22 09:35
@DylanDylann

> * The behavior mentioned in this issue no longer appeared (fixed in [issue](https://github.com/Expensify/App/issues/34466)). The latest behavior is that, the NotFoundPage displayed in the RHN instead of Infinite loader

Thanks for investigating this!

@trjExpensify 

We definitely need to update the issue (or even close it) based on these findings

**Comment by trjExpensify** [comment] 2024-01-22 15:10
>The behavior mentioned in this issue no longer appeared (fixed in https://github.com/Expensify/App/issues/34466). The latest behavior is that, the NotFoundPage displayed in the RHN instead of Infinite loader

Does that mean someone will see two "NotFound" errors? 

<img width="806" alt="image" src="https://github.com/Expensify/App/assets/16232057/ed2518dc-7064-41fe-a165-3ddfb872197c">

**Comment by DylanDylann** [comment] 2024-01-22 18:34
@trjExpensify Yes. It is the current behavior

**Comment by DylanDylann** [comment] 2024-01-23 08:39
@trjExpensify FYI, In staging:
![Screenshot from 2024-01-23 15-39-19](https://github.com/Expensify/App/assets/141406735/5e76c9b9-d31f-4f79-a6c1-63554765f458)

**Comment by trjExpensify** [comment] 2024-01-23 11:03
Got it, thanks! So we've come across the "double Hmm..." in the workspace settings in the new ideal nav we're working on, and opted for a full page error on desktop instead ([ref](https://github.com/Expensify/App/issues/34234)). @shawnborton @dannymcclain @dubielzyk-expensify I wonder if we want to do the same here? 

It's slightly different insofar as the main pane (chat) and request money flow (RHP) are not accessible, but the Chats list (LHN) still is. Equally, the main pane is not in focus. 

If we're okay with leaving this as is, then I agree we can close out this issue as the infinite spinners as reported are resolved.

**Comment by trjExpensify** [comment] 2024-01-23 14:55
Ah wait.. these are links are for any given room's details, members and settings pages in the LHN. 

```
- https://staging.new.expensify.com/r/6821704960193694/details
- https://staging.new.expensify.com/r/6821704960193694/participants
- https://staging.new.expensify.com/r/6821704960193694/settings
```

If we do what you're suggesting, when you click one of these links won't we end up:

1. opening the RHP while we figure out you don't have access
2. immediately close it so you're back in the room with the one NotFound error

Equally, how do we handle if someone has access to the chat in question, but not a particular page in its settings? The main pane chat shouldn't result in NotFound, only the applicable RHP setting page, right?

Overall, I think we probably leave this as it is. Though @lanitochka17, perhaps you can shed some light on where this bug report came from in the test suite.

**Comment by DylanDylann** [comment] 2024-01-23 17:44
> Equally, how do we handle if someone has access to the chat in question, but not a particular page in its settings? The main pane chat shouldn't result in NotFound, only the applicable RHP setting page, right?

@trjExpensify  Currently, we do not have this case. User do not have access to ```/r/:reportID/details```, ```/r/:reportID/participants```, ```/r/:reportID/settings``` only if user do not have access to ```/r/:reportID``` and vice versa

**Comment by trjExpensify** [comment] 2024-01-23 18:16
Right, so I'm questioning if it's really worth adding that code as a condition here? We've established we independently need a NotFound page on the main chat page, and the RHP for when you have access to the room but not certain settings pages. 

So given that we have this dynamic, and it's not a case where it warrants a full page NotFound error like the ref [here](https://github.com/Expensify/App/issues/34800#issuecomment-1905804985), I'm inclined to do nothing. Happy for a second opinion from the design team tagged though!

**Comment by trjExpensify** [comment] 2024-01-23 18:50
Alrighty, closing it out!

**Closed by trjExpensify** 2024-01-23 18:50 UTC
Labels: External, Daily, Help Wanted, Bug
