### ISSUE TITLE
Public channel - Can not login via Google SSO to a public channel

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#27937] opened 2023-09-21 12:28 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Go to https://new.expensify.com/r/5408450846930023
2. Click om Sign in
3. Click on Google
4. Select an account to sign in

## Expected Result:
User is signed in to Expensify

## Actual Result:
An error message is shown and user is still logged out

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [x] Android / Chrome
- [ ] iOS / native
- [x] iOS / Safari
- [x] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 1.3.72-6

**Reproducible in staging?:** Yes

**Reproducible in production?:** Yes

**If this was caught during regression testing, add the test name, ID and link from TestRail:**

**Email or phone of affected tester (no customers):**

**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/78819774/cb265679-eb1b-4a5b-9c59-57057be2bdb7

**Expensify/Expensify Issue URL:**

**Issue reported by:** Applause - Internal Team

**Slack conversation:**

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~019ae7b315de0f271b</li>
        <li>Upwork Job ID: 1705134681028284416</li>
        <li>Last Price Increase: 2023-09-22</li>
    </ul>
</details>

**Comment by joekaufmanexpensify** [comment] 2023-09-22 08:19
Reproduced!

**Comment by b4s36t4** [comment] 2023-09-22 10:58
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
Public channel - Can not login via Google SSO to a public channel 
### What is the root cause of that problem?

Well the way we handle Signing parts of the application is different from flow we're doing in this issue.

When we open any public room `openReport` command sends us temporary session token, in which we merge that token with Onyx.

> We have session token saved in Onyx.

Now when we try to login via google we are sending `authToken` + `token` (from google) backend Auth Layer should be confusing on what to because `authToken` is for the API which are authenticated but we're sending both from frontend (one need to login, one say we're authenticated :/)

> Why it doesn't happen with nrml auth flow?

Because we skip `authToken` param from `BeginSignIn` command API & that `BeginSignIn` replace the old session token (if any) with latest token received from backend.

### What changes do you think we should make in order to solve the problem?

When sending `SignInWithGoogle` API we need to omit two params (`email` & `authToken`) which we're adding here in this function https://github.com/Expensify/App/blob/a07bb1537063122b481722573c382f4a42fc9a22/src/libs/Network/enhanceParameters.js#L24

1. Omit `authToken`

We need to add `SignInWithGoogle` to this function https://github.com/Expensify/App/blob/a07bb1537063122b481722573c382f4a42fc9a22/src/libs/Network/enhanceParameters.js#L13-L15 so that `authToken` parameter would skipped for this request

2. Return `email` param if we're coming from `SignInWithGoogle` command. https://github.com/Expensify/App/blob/a07bb1537063122b481722573c382f4a42fc9a22/src/libs/Network/enhanceParameters.js#L47

> Same changes should apply for Apple Auth As well (not tested though), but 100% sure 99% these are the only changes required for apple auth well.


**Points to Note Before**

1. On Apple login All the reports of logged in account won't appear, because backend not sending all the onyx data that it sends for `SigninUser` for command.

2. On Refresh App asks user to login again, there is already an existing issue thinking to close (internally handling it).



### What alternative solutions did you explore? (Optional)

Backend could handle this edge case if `token` and `authToken` coming form params, that's a solution.

**Comment by b4s36t4** [comment] 2023-09-22 10:58
@aimane-chnaif Friendly bump ^^ on above proposal :)

**Comment by joekaufmanexpensify** [comment] 2023-09-25 04:19
Still pending review of proposal

**Comment by joekaufmanexpensify** [comment] 2023-09-26 09:36
@aimane-chnaif mind taking a look at the proposal here?

**Comment by joekaufmanexpensify** [comment] 2023-09-28 06:43
Bumped in Slack

**Comment by b4s36t4** [comment] 2023-09-28 07:35
@aimane-chnaif #27198 I think there are few other issues (maybe 2-3) but this can do the work.

**Comment by b4s36t4** [comment] 2023-09-28 07:44
> do we currently support Google / Apple sign in from anonymous user in backend?

Is there any difference between nrml login & with ThirdParty logins?

**Comment by b4s36t4** [comment] 2023-09-28 07:56
@aimane-chnaif But why?

> On Refresh, App asks user to login again, there is already an existing issue thinking to close (internally handling it).

for this issue? or any other reason?

**Comment by b4s36t4** [comment] 2023-09-28 08:17
Yes, also this requires backend changes as well as I mentioned backend is not sending all onyx data on login. Either we need to call ReconnectApp command or backend should solve this.

**Comment by joekaufmanexpensify** [comment] 2023-09-29 06:51
@aimane-chnaif do you think this will be fixed by the issue you referenced above?

**Comment by joekaufmanexpensify** [comment] 2023-09-29 07:36
Got it, okay. I will put on hold for that issue!

**Comment by joekaufmanexpensify** [comment] 2023-10-02 21:19
Held

**Comment by b4s36t4** [comment] 2023-10-04 22:06
@joekaufmanexpensify @aimane-chnaif That issue is closed. can you guys approve the proposal now?!

**Comment by joekaufmanexpensify** [comment] 2023-10-16 14:53
@aimane-chnaif bump for when you have a sec?

**Comment by b4s36t4** [comment] 2023-10-16 15:01
I will check and update.

**Comment by b4s36t4** [comment] 2023-10-16 15:06
@aimane-chnaif Nope, it's working fine. I think we're good to go with this one.

**Comment by joekaufmanexpensify** [comment] 2023-10-23 14:36
Agreed! I can still reproduce this one. @aimane-chnaif are we good to sign off on this proposal?

**Comment by b4s36t4** [comment] 2023-11-06 06:17
@aimane-chnaif there is an issue with sso login with new domain setup. 

Can you try accessing the login via localhost?

Remove host property in webpack.dev.js and make server as http instead of https and restart the webpack and try again. 

It. Should work.

**Comment by b4s36t4** [comment] 2023-11-06 08:56
@aimane-chnaif I'm just wondering the about the internal switch, internal is for the real issue or google login not working?

**Comment by b4s36t4** [comment] 2023-11-06 08:57
https://expensify.slack.com/archives/C01GTK53T8Q/p1699015686548139?thread_ts=1698686381.655959&cid=C01GTK53T8Q

if it's about not able to login with google, it's just an update with google settings. We've updated the localhost with domain which third-party signin is not configured.

**Comment by b4s36t4** [comment] 2023-11-06 09:02
Ok, understood. But I feel backend changes are not required here.

I think excluding the particular command `SignInWithGoogle` is what should we do, that's what we're doing with normal login. the only thing I feel a work-around is removing email from the parameters conditionally.

I request you to check the things again, I feel backend is nothing related to this issue.

**Comment by b4s36t4** [comment] 2023-11-06 09:10
Yes, it works same as normal signin by just doing the two changes.

**Comment by joekaufmanexpensify** [comment] 2023-11-13 14:53
@srikarparsi will you have a chance to look into this this week?

**Comment by joekaufmanexpensify** [comment] 2023-11-20 14:12
Pending review from @srikarparsi

**Comment by joekaufmanexpensify** [comment] 2023-11-27 15:01
@srikarparsi mind taking a look at [this](https://github.com/Expensify/App/issues/27937#issuecomment-1794358371) and whether you think this is a backend issue?

**Comment by joekaufmanexpensify** [comment] 2023-12-04 16:16
Bumped Srikar 1:1

**Comment by srikarparsi** [comment] 2023-12-05 09:47
Hi! Sorry, It's finals period at school and I've been meaning to look at this but don't have too much familiarity with Google SSO and have been a bit busy with tests. I spent some time looking through the code today though and also think that this is a backend fix. I'll check again tomorrow to make sure the backend change won't affect any other sign ins, mark this internal, and take it from there

**Comment by b4s36t4** [comment] 2023-12-07 09:42
> Also @b4s36t4, do you think you could clarify step 2 of your proposal. Why do we need to remove email from the parameters conditionally?

If we send `email` parameter that's not working. Maybe backend is expecting a list of parameters only. I tried just excluding the token param i.e step 1 still it didn't worked. Maybe sending email in params make the request logged in kind? not sure.

**Comment by joekaufmanexpensify** [comment] 2023-12-18 14:53
Still pending further discussion

**Comment by joekaufmanexpensify** [comment] 2023-12-21 16:49
Same

**Comment by joekaufmanexpensify** [comment] 2024-01-01 17:43
@srikarparsi is the next step here for you to work on the backend changes?

**Comment by joekaufmanexpensify** [comment] 2024-01-08 14:24
Pending input from @srikarparsi

**Comment by joekaufmanexpensify** [comment] 2024-01-15 15:21
Bump @srikarparsi mind confirming here if the next step for [this one](https://github.com/Expensify/App/issues/27937#issuecomment-1849022478) is your backend changes?

**Comment by joekaufmanexpensify** [comment] 2024-01-22 15:12
Bumped Srikar 1:1

**Comment by srikarparsi** [comment] 2024-01-22 17:24
Hi! Yes, [this](https://github.com/Expensify/App/issues/27937#issuecomment-1849022478) would be the backend change I need to make. And on the frontend, we would need to exclude Google and Apple Sign in. I'll get started on this tomorrow and should have a PR by the end of the week.

**Comment by joekaufmanexpensify** [comment] 2024-01-29 15:03
Great. TY! LMK if anything comes up you need help with as you work on the PR.

**Comment by joekaufmanexpensify** [comment] 2024-02-05 14:45
@srikarparsi is the PR still pending here?

**Comment by srikarparsi** [comment] 2024-02-09 03:52
Just retested since I saw some changes made to SSO and it looks like its working now. Closing this out but @joekaufmanexpensify if you notice anything not working please re-open and I can take a look.

**Closed by srikarparsi** 2024-02-09 03:52 UTC
Labels: Weekly, Internal, Bug
