### ISSUE TITLE
[HOLD for payment 2023-09-29] 🟢 [$500] BUG: [distance] request confirmation offline doesn't show TBD

### ISSUE THREAD

**Issue by neil-marcellini** [Expensify/App#26537] opened 2023-09-01 22:48 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Run App on latest main branch (for now)
2. Sign in with an account on the distance requests beta (or enable all betas)
3. Go offline
4. Click green plus, request money
5. Enter start and finish addresses
6. Click next
7. Click show more to see all fields

## Expected Result:
The distance request amount should show as TBD. The distance field should use TBD for values that aren't available. 

From the design doc:
>On this page we will render the PendingMapView without any text. We will set a hasRoute variable based on whether transaction.routes is empty. If we don’t have a route then we can skip all [calculations based on the distance](https://docs.google.com/document/d/16Q9sE-991CZ4wUcalOs_U-qyEEza_C9tZwj6G5lHUp0/edit#bookmark=id.lnkp303iwesj) and set the amount to “TBD”.

> We’ll also pass hasRoute to the translation function for displaying the distance row so that it sets “TBD” as the distance when we don’t have a route.

Additionally, after going back online we should fetch the route so that the values can be filled in.

## Actual Result:
The amount and miles show as 0

## Workaround:
Ignore it

## Platforms:

Which of our officially supported platforms is this issue occurring on?
All
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [ ] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** Unreleased
**Reproducible in staging?:** Not yet
**Reproducible in production?:** Not yet
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):** None
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Originally reported by 
[@situchan](https://expensify.slack.com/team/U04MF8KAANP)
 in a [PR review here](https://github.com/Expensify/App/pull/25707#pullrequestreview-1606168005)
**Expensify/Expensify Issue URL:** None
**Issue reported by:** @situchan 
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1693608145841629

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01a9f623a65b6c37a2</li>
        <li>Upwork Job ID: 1697743255361699840</li>
        <li>Last Price Increase: 2023-09-01</li>
<li>Automatic offers: </li>
<ul>
<li>Ollyws | Reviewer | 26513871</li>
<li>paultsimura | Contributor | 26513873</li>
<li>situchan | Reporter | 26513874</li>
</ul></li>
    </ul>
</details>

**Comment by pradeepmdk** [comment] 2023-09-01 22:56
@neil-marcellini  can give me more details on Expected Result because linked docs is private

**Comment by neil-marcellini** [comment] 2023-09-01 22:58
I included all the details I can. The linked part isn't important.

**Comment by paultsimura** [comment] 2023-09-01 23:37
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
In Offline mode, the MoneyRequestConfirmationList in Distance request should show "TBD" for amount and distance instead of 0.0

Also, the route should be recalculated on coming back online

### What is the root cause of that problem?
1. For "TBD" – there is no handling of the "has no route" case, so the value defaults to 0.
2. For the route recalculation – the isOffline is not handled on the `MoneyRequestConfirmationList` page, so the route doesn't recalculate inside the transaction on the network state change.

### What changes do you think we should make in order to solve the problem?
1. Add the `const doesRouteExist = lodashHas(transaction, 'routes.route0.geometry.coordinates');` variable and handle the `formattedAmount` accordingly: `if (!doesRouteExist && shouldCalculateDistanceAmount)` – return "TBD" and skip calculations; Same goes for the distance.

2. Add the `useNetwork()` to handle the `isOffline` change. On its change, call `Transaction.getRoute(...) if !doesRouteExist`




### What alternative solutions did you explore? (Optional)

**Comment by b4s36t4** [comment] 2023-09-02 07:58
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
[distance] request map is cut off after going online
### What is the root cause of that problem?

Considerably there are two problems here.

1. To show TBD.

Even though we don't have access to how much distance the ride is we're still calculating the distance amount here https://github.com/Expensify/App/blob/7217a18a78ec2b01a45267f476fd95ed0cde0fb0/src/libs/DistanceRequestUtils.js#L72 in this function which is returning odd amount.

We can return "TBD" if the `distanceInMiles` is `0`.

> The usage of this function is getting refactored in other PR which could give us a way to do this in 
> `MoneyRequestConfirmationList` component itself. Above point is only for reference. Also we need to consider the network 
> status before just giving `TBD`

We can do same with `Amount` menu as well. Just some conditionals within `MoneyRequestConfirmationList` component.

2. Getting Values when going back to online.

On `MoneyRequestConfirmationList` we're rendering the map and when we go offline in money request page we'll call `GetRoutes` command which will return us the route and distance etc which we use to calculate distance and then amount based on it.

But while creating if we're offline we won't be having it so the route will be null even if go online which require us to close the modal and go up again.



### What changes do you think we should make in order to solve the problem?

To fix this we need to do two changes.

Here in this `useEffect` https://github.com/Expensify/App/blob/7217a18a78ec2b01a45267f476fd95ed0cde0fb0/src/components/DistanceRequest.js#L154

we need update the logic as below 

```jsx

if ((isOffline && _.isEmpty(waypoints)) || !shouldFetchRoute) {
    return;
}

```

Which will refetch the request if there are waypoints and we've updated our online status.

But this only requires us to come back to the first page again, which won't be the case everytime.

To update the `routes` inside `ConfirmedRoute` we also need to call the `GetRoute` command there as well.

```jsx

    useEffect(() => {
        // If the network is offline or we have the coordinate we don't need to call the api again.
        if (isOffline || !_.isEmpty(coordinates)) return;
        Transaction.getRoute(transaction.transactionID, waypoints);
    }, [coordinates, isOffline, transaction.transactionID, waypoints]);

```

### What alternative solutions did you explore? (Optional)
NA

@neil-marcellini Please review the proposal. Sorry for the ping if you're not going to review :)

**Comment by b4s36t4** [comment] 2023-09-04 18:13
@Ollyws I think the changes I mentioned for `DistanceRequest` is already being implemented/being reviewed for proposals in another issue. At this moment we don't re-fetch route when we do move to online from offline. At this moment we use the map at 2 places. DistanceRequest and ConfirmedRoute.

**Comment by b4s36t4** [comment] 2023-09-04 18:14
If we go online at `ConfirmedRoute` component (I think it's confirmation page) we don't fetch route again, which requires the user to navigate back again to Distance Route tab and them move again to the confirmation page to see the updated route and the amount to be replaced with TBD.

**Comment by b4s36t4** [comment] 2023-09-04 18:16
<img width="360" alt="Screenshot 2023-09-04 at 11 45 26 PM" src="https://github.com/Expensify/App/assets/59088937/773eb747-9c51-442a-84e1-36d6cb6eca7b">

This is the page we want to show TBD and the values, if we don't fetch the route here when the user become online this page doesn't we update values instantly and show?? But with the first proposal we only solve it at the distance screen. But with my solution we fix it in both places. And results are instantly updated.

Let me know if you need more context. Thanks!!

**Comment by paultsimura** [comment] 2023-09-04 18:20
I actually found a better solution for the issue without overcomplicating things with `_.isEmpty(waypoints)`:

https://github.com/Expensify/App/blob/447d2169845a3304bd6be1be05fd80a958191ca5/src/components/DistanceRequest.js#L92

Replace this line with:
```
const doesRouteExist = !lodashIsNil(lodashGet(transaction, 'routes.route0.geometry.coordinates', null));
```

We already do almost all we need to trigger re-fetch, it's just the logic for checking the doesRouteExist is incorrect, because `lodashHas(transaction, 'routes.route0.geometry.coordinates')` returns true even if `routes.route0.geometry.coordinates === {}`

**Comment by b4s36t4** [comment] 2023-09-04 18:37
@Ollyws Please watch this video to understand the context of my proposal.

https://github.com/Expensify/App/assets/59088937/a177e610-d7eb-4e03-9144-fa9e6431d9e5

And fetch route when we're back online is being raised in other PR.

**Comment by neil-marcellini** [comment] 2023-09-05 19:27
I like the [proposal](https://github.com/Expensify/App/issues/26537#issuecomment-1703516680) from @paultsimura. It's clear and simple. We can iron out any details in the PR. I'm going to assign him now for urgency @Ollyws.

**Comment by b4s36t4** [comment] 2023-09-05 19:59
@neil-marcellini but when we come online again in confirmation page we're not fetching the route, and it stills show TBD even if the user is online. User has to go-back again to Distance Request page and continue again. Doesn't that cause a regression again? This https://github.com/Expensify/App/issues/26537#issuecomment-1705609476 video explains the issue.

Right now we're showing `0` right after we implement TBD it still shows TBD.

**Comment by b4s36t4** [comment] 2023-09-05 20:00
Also fetching route when we go to online is being implemented here https://github.com/Expensify/App/issues/26589#issuecomment-1706989115.

**Comment by paultsimura** [comment] 2023-09-05 20:08
Just to sum up my approach, I'm working on this issue using the mix of [my initial proposal](https://github.com/Expensify/App/issues/26537#issuecomment-1703516680) for TBD, and [this addition](https://github.com/Expensify/App/issues/26537#issuecomment-1705598895) for the route refetch.

To illustrate that it does cover both cases, I'm attaching the videos.

Case 1. Re-fetching on the "Confirmation" page:
https://github.com/Expensify/App/assets/12595293/3c050840-c802-4161-9855-e134602d5bcf

Case 2: Re-fetching on the "Request" page:
https://github.com/Expensify/App/assets/12595293/e97504e9-d7c0-497e-87c3-0ef77c756b4c

**Comment by pradeepmdk** [comment] 2023-09-06 00:41
@paultsimura  the route prefetch is a different issue I am already working on that going Raise the PR Now

**Comment by paultsimura** [comment] 2023-09-06 06:49
@pradeepmdk The route prefetch was a part of this issue from the beginning as well.

> Additionally, after going back online we should fetch the route so that the values can be filled in.

I'm sorry this affected your issue. Let the C+ team decide what to do with it...

**Comment by paultsimura** [comment] 2023-09-06 06:50
@neil-marcellini since this issue is rather urgent, could you please assist with adding the "Waiting for copy" label (if applicable here) and escalating [this translation discussion](https://expensify.slack.com/archives/C01GTK53T8Q/p1693944607891839)?

**Comment by paultsimura** [comment] 2023-09-06 10:07
> @neil-marcellini since this issue is rather urgent, could you please assist with adding the "Waiting for copy" label (if applicable here) and escalating [this translation discussion](https://expensify.slack.com/archives/C01GTK53T8Q/p1693944607891839)?

@Ollyws maybe you could help with this if you're online atm.?

**Comment by neil-marcellini** [comment] 2023-09-11 18:40
Sounds like we got the translation thing resolved. I'm requesting review from design for [the PR](https://github.com/Expensify/App/pull/26836) since we're changing the UI around a fair amount for the offline flow. I've requested some changes so let's wait until those updates are made.

**Comment by neil-marcellini** [comment] 2023-09-11 18:41
For design reference please check out what we have mocked up in the [offline section](https://docs.google.com/document/d/16Q9sE-991CZ4wUcalOs_U-qyEEza_C9tZwj6G5lHUp0/edit#heading=h.6sl1v3n46ngm) of the distance requests doc so far.

**Comment by paultsimura** [comment] 2023-09-19 06:33
Please also take into consideration the translations and copies waiting times + [this comment](https://github.com/Expensify/App/pull/26836#issuecomment-1716398756).

**Comment by paultsimura** [comment] 2023-10-04 12:27
Hey @Ollyws @neil-marcellini, should the payment for this issue happen after the Regression Test is approved and added?
Otherwise it's a friendly bump 🙂 ☝️

**Comment by mountiny** [comment] 2023-10-06 17:21
cc @garrettmknight bump for the payments

**Comment by neil-marcellini** [comment] 2023-10-06 18:13
Not overdue, waiting for payment

**Comment by garrettmknight** [comment] 2023-10-09 18:19
My bad, y'all.

**Summary of payments for this issue:**
- urgency bonus: no
- Reporter: @situchan - $50 paid via Upwork 
- Contributor: @paultsimura - $500 paid via Upwork
- Reviewer: @Ollyws - $500 paid via Upwork

**Comment by garrettmknight** [comment] 2023-10-09 18:21
Closing!

**Closed by garrettmknight** 2023-10-09 18:21 UTC
Labels: External, Daily, Design, Awaiting Payment, Bug
