### ISSUE TITLE
[HOLD for payment 2024-01-11] [HOLD for payment 2024-01-09] [$500]  IOU - When adding a receipt to a manual IOU, the error "Receipt missing details" appears

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#33786] opened 2023-12-29 21:46 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.20-0
**Reproducible in staging?:** Y
**Reproducible in production?:** N
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** Applause - Internal Team
**Slack conversation:**

## Action Performed:
1. Open New Expensify app
2. Log in with any account
3. Click on FAB > Request Money > Manual
4. Input an amount and click Next
5. Enter/select an option for the request
6. Click on the three-dot menu at the top right
7. Click on "Add Receipt"
8. Click on "Choose File" and Select an image
9. Complete the request

## Expected Result:
No error should appear when adding a receipt to a manual IOU

## Actual Result:
When adding a receipt to a manual IOU, the error "Receipt missing details" appears

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [x] Android: mWeb Chrome
- [x] iOS: Native
- [x] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details> 

https://github.com/Expensify/App/assets/78819774/8b1ac679-2945-4963-aa5b-4e395f9ebc86

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~014720a73c52b8fa9d</li>
        <li>Upwork Job ID: 1740860349188747264</li>
        <li>Last Price Increase: 2023-12-29</li>
<li>Automatic offers: </li>
<ul>
<li>paultsimura | Contributor | 28077743</li>
<li>situchan | Contributor | 28080992</li>
</ul></li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @CortneyOfstad</details>

**Comment by joelbettner** [comment] 2023-12-29 22:21
@situchan @waterim I think this might be happening because of [this PR](https://github.com/Expensify/App/pull/32486), but I'm not entirely sure.

**Comment by situchan** [comment] 2023-12-29 22:21
cc: @mountiny

**Comment by mountiny** [comment] 2023-12-29 22:22
Yeah Someone can try to reproduce, then revert on main and repro again to confirm, I am fixing some issues and we we have weekend to resolve, its been quite complicated Pr so ideally we fix this instead of reverting

**Comment by unicorndev-727** [comment] 2023-12-29 22:30
## Proposal
from: @unicorndev-727
### Please re-state the problem that we are trying to solve in this issue.
When adding a receipt to a manual IOU, the error "Receipt missing details" appears
### What is the root cause of that problem?
The root cause is that we don't have merchat in transaction here.
https://github.com/Expensify/App/blob/595bf4075988c0b64cb0db1e37694284637fbea2/src/libs/TransactionUtils.ts#L149

### What changes do you think we should make in order to solve the problem?
We need to update this part `isMerchantMissing(transaction)` above.
### What alternative solutions did you explore? (Optional)
  N/A

**Comment by paultsimura** [comment] 2023-12-29 22:42
## Proposal

### Please re-state the problem that we are trying to solve in this issue.


### What is the root cause of that problem?
We have added extra validations for the missing merchant on transactions with receipt, but did not consider the fact that manual requests can have receipts as well without requiring the merchant.

### What changes do you think we should make in order to solve the problem?
We should persist the following 2 parameters into the transaction when creating the request:

https://github.com/Expensify/App/blob/422f173dd5e0c75e8147be2183509fd1fc70733a/src/CONST.ts#L1177-L1186

This will give us more fine-grained control over the behavior of different types of transactions.

After it, we should make use of `transaction.isScan` to check for the missing fields instead of `hasReceipt(transaction)` (as manual requests can have receipts too, and they don't require the SmartScan-required fields) here:

https://github.com/Expensify/App/blob/3ba6f555f9b09cf18b4ea7daa773a3a17d7bd45a/src/libs/TransactionUtils.ts#L415-L420


### What alternative solutions did you explore? (Optional)

**Comment by mountiny** [comment] 2023-12-29 22:51
To clarify the expected behaviour here, the problem is about the fact this is P2P IOU request and in this case we do not require the merchant with the receipt (different case for workspace chats in which case this error is correct)

So I think the solution here is just to see if the parent report is expense type and only then show this violation

**Comment by Tony-MK** [comment] 2023-12-29 23:08
## Proposal

### Please re-state the problem that we are trying to solve in this issue.

### What is the root cause of that problem?

The `hasMissingSmartscanFields` has returned false because the transaction does not have a merchant because it is a manual IOU.

### What changes do you think we should make in order to solve the problem?

Change the `hasMissingSmartscanFields` function to something like this.

```
 Boolean(transaction && hasReceipt(transaction) && !isDistanceRequest(transaction) && !isReceiptBeingScanned(transaction) && ((isExpenseReport(parentReport) && !isPolicyExpenseChat(parentReport)) || areRequiredFieldsEmpty(transaction))

```

**Comment by unicorndev-727** [comment] 2023-12-29 23:39
@mountiny 
I update [proposal](https://github.com/Expensify/App/issues/33786#issuecomment-1872372749) and added the result video.

**Comment by joelbettner** [comment] 2023-12-30 00:33
@Tony-MK I like your proposal because `areRequiredFieldsEmpty` is used in several different places, so moving the logic into that method will prevent us from having to keep logic updated everywhere it is called.

We will just need to import `ReportUtils` into the `TransactionUtils.ts` file in order to be able to call `isExpenseReport`, and then we will also need to make some changes to `isExpenseReport` so it can take a report object or a reportID (see `ReportUtils.isMoneyRequest` as an example).

**Comment by Tony-MK** [comment] 2023-12-30 05:43
Kindly review my [updated prospal](https://github.com/Expensify/App/issues/33786#issuecomment-1872383846) because I just read the comment above and thought maybe it would be better to use the `getRootParentReport` rather than `getParentReport`. 

Thoughts?

**Comment by Tony-MK** [comment] 2023-12-30 05:50
Kindly review my [updated prospal](https://github.com/Expensify/App/issues/33786#issuecomment-1872383846) because I just read the comment above and thought maybe it would be better to use the `getRootParentReport` rather than `getParentReport`. 
Could you help me with feedback? Thanks

**Comment by mountiny** [comment] 2023-12-31 09:34
I do feel like all the proposals are quite good, @paultsimura seems the simplest but is there going to be the dependency cycle in your solutions?

**Comment by paultsimura** [comment] 2023-12-31 10:43
> is there going to be the dependency cycle in your solutions?

There shouldn't be, since all the fields will be on the same `transaction` object.
However, I think we'll need the BE changes as well in order to persist the `transaction.iouType` not only optimistically when creating the request.
But as for me, this change is quite useful and worth adding.

**Comment by mountiny** [comment] 2023-12-31 12:05
I dont think we need that, all thats needed is the fact if the expense is on group or personal policy, which in exchange can be checked by the report type.

Are you able to make a PR with a that fix and verify there are no dependency cycles?

**Comment by paultsimura** [comment] 2023-12-31 23:34
Got you @mountiny. Sure thing, I will put up a testing branch in the morning and will update about the dependency cycle. But from what I see, there shouldn't be any👌

**Comment by paultsimura** [comment] 2024-01-01 12:07
@mountiny here's the testing branch, no dependency cycles:

https://github.com/paultsimura/Expensify/blob/093e8a4b1a49397814d790b1221e7a9da4fdfd47/src/libs/TransactionUtils.ts#L422-L431

**Comment by joelbettner** [comment] 2024-01-01 20:16
@paultsimura I think that PR looks good. @mountiny what do you think? I'd like to get this up and tested ASAP so we don't continue to block the deploy.

**Comment by shubham1206agra** [comment] 2024-01-02 15:57
@paultsimura's [proposal](https://github.com/Expensify/App/issues/33786#issuecomment-1872376391) looks good.

🎀 👀 🎀 C+ reviewed

**Comment by marcaaron** [comment] 2024-01-02 19:17
Can we assign @paultsimura and get a PR up? What's the ETA for this getting fixed?

**Comment by paultsimura** [comment] 2024-01-02 19:18
> What's the ETA for this getting fixed?

I can spin up the PR within an hour.

**Comment by marcaaron** [comment] 2024-01-02 19:42
Chatted with @joelbettner off issue. Sounds good @paultsimura. Thanks!

**Comment by marcaaron** [comment] 2024-01-02 23:20
Ok solution is on staging now. So I think we can remove this blocker.

**Comment by joelbettner** [comment] 2024-01-02 23:22
I QA'd it on staging and it is working:
<img width="592" alt="image" src="https://github.com/Expensify/App/assets/13264774/f10071a8-92de-4dc7-86d2-4bc8c97a8030">
<img width="1269" alt="image" src="https://github.com/Expensify/App/assets/13264774/3d709b4a-eb97-4900-bcea-58cf329c7f8d">

**Comment by paultsimura** [comment] 2024-01-02 23:49
@joelbettner I think this shouldn't be closed yet?

**Comment by Tony-MK** [comment] 2024-01-09 22:28
Hey everyone,

Advice by @mountiny, this comment is a continuation of this [slack](https://expensify.slack.com/archives/C01GTK53T8Q/p1704836802870409?thread_ts=1704835156.974889&cid=C01GTK53T8Q) discussion.

Below are the [PR](https://github.com/Expensify/App/pull/33850) changes meant the fix this issue from his [Proposal](https://github.com/Expensify/App/issues/33786#issuecomment-1872376391).

https://github.com/Expensify/App/blob/ff95c0cca0e647bdf0d0170d353c50e72a0a1a81/src/libs/TransactionUtils.ts#L33-L38

https://github.com/Expensify/App/blob/ff95c0cca0e647bdf0d0170d353c50e72a0a1a81/src/libs/TransactionUtils.ts#L159-L161

Also, here are the suggestions for my [proposal](https://github.com/Expensify/App/issues/33786#issuecomment-1872383846)'s alternative solution A presented.

> ### What alternative solutions did you explore? (Optional)
> **Option A** Just like in `IOU.js`, `TaskUtil.ts`, `ReportUtils.ts`, and many others, we can connect to the onyx and get only parent reports from `ONYXKEYS.COLLECTION.REPORT`. Then, store them in an array in `TransactionUtils.js` like such: `let allReports: OnyxCollection<Report>`.
> 
> The last action for both options A and B will be checking if is an expense report with `parentReport?.type === CONST.REPORT.TYPE.EXPENSE`.

**Comment by mountiny** [comment] 2024-01-09 22:38
Note for @CortneyOfstad I think @paultsimura did not do this intentionally but in Slack mentioned he is happy to split the reward for fairness. In that case we can pay $250 each for @paultsimura and @Tony-MK 

$500 to @situchan

**Comment by CortneyOfstad** [comment] 2024-01-11 17:07
@Tony-MK sent you a proposal — please let me know once you accept so I can get that paid to you 👍 

@paultsimura — paid you $250 per the comment above via Upwork

@situchan — paid you $500 via Upwork

**Comment by Tony-MK** [comment] 2024-01-11 17:57
Thanks, @CortneyOfstad . I accepted the offer.

**Comment by CortneyOfstad** [comment] 2024-01-11 18:05
Paid! 

## Payment Summary

Contributor that fixed the issue — @paultsimura paid $250 via Upwork; @Tony-MK paid $250 via Upwork 
Contributor+ that helped on the issue and/or PR — @situchan paid $500 via Upwork

**Comment by CortneyOfstad** [comment] 2024-01-11 18:05
@situchan any updates on the checklist above? TIA!

**Comment by situchan** [comment] 2024-01-11 18:11
- [x] The PR that introduced the bug has been identified. Link to the PR: https://github.com/Expensify/App/pull/32486#issuecomment-1887704145
- [x] The offending PR has been commented on, pointing out the bug it caused and why, so the author and reviewers can learn from the mistake. Link to comment: https://github.com/Expensify/App/pull/32486
- [x] A discussion in #expensify-bugs has been started about whether any other steps should be taken (e.g. updating the PR review checklist) in order to catch this type of bug sooner. Link to discussion: N/A
- [x] Determine if we should create a regression test for this bug.
- [x] If we decide to create a [regression test](https://github.com/Expensify/App/blob/main/contributingGuides/REGRESSION_TEST_BEST_PRACTICES.md) for the bug, please propose the regression test steps to ensure the same bug will not reach production again.

This was deploy blocker. Caught during regression testing so no need another one.

**Comment by CortneyOfstad** [comment] 2024-01-11 18:13
Perfect! Closing!

**Closed by CortneyOfstad** 2024-01-11 18:13 UTC
Labels: External, Engineering, Daily, Awaiting Payment, Bug
