### ISSUE TITLE
[$500] Chat - Secondary login chat after redirecting to primary login -redirects user to Concierge chat

### ISSUE THREAD

**Issue by izarutskaya** [Expensify/App#30062] opened 2023-10-20 09:32 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** v1.3.87-1
**Reproducible in staging?:** Y
**Reproducible in production?:** N
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** Applause-Internal Team
**Slack conversation:** @

## Action Performed:
Preconditions:

1. Prepare an account that has a secondary login assigned
2. Log in with another account and start a conversation with the primary login of the account from step 1
3. Send some messages in the conversation

Steps:

1. Log in with the account that has the conversation with the user that has 2 logins
2. Click on FAB
3. Click on New Chat
4. Search for the Secondary login of the account

## Expected Result:
User should be redirected to the conversation with the primary login email

## Actual Result:
After redirecting to the conversation with the primary login email - User is redirected to Concierge chat

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [x] Android: mWeb Chrome
- [x] iOS: Native
- [ ] iOS: mWeb Safari
- [ ] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos
<details>
<summary>Android: Native</summary>

https://github.com/Expensify/App/assets/115492554/7f66a542-e462-4a1f-b93f-9b89c21363e5

</details>

<details>
<summary>Android: mWeb Chrome</summary>

https://github.com/Expensify/App/assets/115492554/135a6c1d-537a-4b7f-9b9c-b82ea3f5ca98

</details>

<details>
<summary>iOS: Native</summary>

</details>

<details>
<summary>iOS: mWeb Safari</summary>

</details>

<details>
<summary>MacOS: Chrome / Safari</summary>

</details>

<details>
<summary>MacOS: Desktop</summary>

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01a0a518407b385be4</li>
        <li>Upwork Job ID: 1715300080774799360</li>
        <li>Last Price Increase: 2023-11-24</li>
<li>Automatic offers: </li>
<ul>
<li>dukenv0307 | Contributor | 27865503</li>
</ul></li>
    </ul>
</details>

**Comment by izarutskaya** [comment] 2023-10-20 09:33
Not reproducible in production

https://github.com/Expensify/App/assets/115492554/723995dc-9f3b-47c3-bad5-51c9b138b8ce

**Comment by mountiny** [comment] 2023-10-20 12:56
This needs to be fixed, but its also an edge case flow we should not hold deploy for imho

**Comment by mountiny** [comment] 2023-10-20 17:44
I have decreased the price to $250 because I believe this is a minor edge case flow issue hence it is not as important as some other issues. If @JmillsExpensify @MariaHCD disagree, or there will be no proposals after a while, price can be adjusted at any time

**Comment by JmillsExpensify** [comment] 2023-10-24 22:54
Working through proposals

**Comment by JmillsExpensify** [comment] 2023-11-01 15:21
Still aiming for more proposals

**Comment by MariaHCD** [comment] 2023-11-07 14:22
We're still looking for proposal here

**Comment by MariaHCD** [comment] 2023-11-10 14:46
Increasing the bounty since we haven't had any proposals here for a while.

**Comment by Tony-MK** [comment] 2023-11-11 05:08
## Proposal

### Please re-state the problem that we are trying to solve in this issue.

Secondary login chat after redirecting to primary login -redirects user to Concierge chat

### What is the root cause of that problem?

The `ReportScreen` has to re-render a minimum of two times because of `firstRenderRef`. Read the two snippets below from the [NavigationRoot.js](https://github.com/Expensify/App/blob/fcee2073f096ad60dd9f30c536342de7d3893282/src/libs/Navigation/NavigationRoot.js) and [ReportScreen.js](https://github.com/Expensify/App/blob/fcee2073f096ad60dd9f30c536342de7d3893282/src/pages/home/ReportScreen.js#L301-L305) files to further illustrate the effects of the width of the screen.

https://github.com/Expensify/App/blob/fcee2073f096ad60dd9f30c536342de7d3893282/src/libs/Navigation/NavigationRoot.js#L62-L74

https://github.com/Expensify/App/blob/fcee2073f096ad60dd9f30c536342de7d3893282/src/pages/home/ReportScreen.js#L301-L305

Devices with large screen widths re-render one additional time, which allows `report.reportID` to become present, thus being able to produce the expected result. Here is a snippet to explain the possibilities of `report.reportID` being unavailable.

https://github.com/Expensify/App/blob/fcee2073f096ad60dd9f30c536342de7d3893282/src/pages/home/ReportScreen.js#L238-L241

Finally, the root cause of the problem is that, in this specific case, devices with small screen widths only re-render twice because `report.reportID` is not present. This will make the logic below navigate the Concierge chat because, in this situation, `prevReport.parentReportID` doesn't have a value.

https://github.com/Expensify/App/blob/fcee2073f096ad60dd9f30c536342de7d3893282/src/pages/home/ReportScreen.js#L307-L331

### What changes do you think we should make in order to solve the problem?

To produce the expected result accurately, we should try to re-render the page for small devices so they mimic the control flow of the larger devices. Therefore, adding an additional condition in this [`useEffect`](https://github.com/Expensify/App/blob/fcee2073f096ad60dd9f30c536342de7d3893282/src/pages/home/ReportScreen.js#L300) hook to force the function to run one more time for small devices should solve the problem. This will ensure that `report.reportID` is present to allow the fragile logic in the hook to perform as intended without changing it.

**Comment by MariaHCD** [comment] 2023-11-13 08:59
@allroundexperts what do you think of the above proposal?

**Comment by JmillsExpensify** [comment] 2023-11-24 18:15
@allroundexperts mind providing feedback on the proposal?

**Comment by allroundexperts** [comment] 2023-11-26 23:46
Thanks for your proposal @Tony-MK. I think that rendering twice on smaller screens to make sure that `reportId` is available is sort of flaky. Going through @dukenv0307's [proposal](https://github.com/Expensify/App/issues/30062#issuecomment-1773705850) again, I think its less flakier as it would just isolate the check to policy rooms only. Let's go with there proposal.

🎀 👀 🎀 C+ reviewed

**Comment by JmillsExpensify** [comment] 2023-11-29 00:16
PR forcoming

**Comment by JmillsExpensify** [comment] 2023-12-13 05:30
It looks like the automation failed for this issue. Payment summary:

- Issue reporter: QA
- Contributor: $500 @dukenv0307 
- Contributor+: $500 @allroundexperts

**Comment by JmillsExpensify** [comment] 2023-12-13 05:31
@allroundexperts mind completing the BZ checklist as well?

**Comment by allroundexperts** [comment] 2023-12-19 10:59
## Checklist
1. https://github.com/Expensify/App/pull/27966
2. https://github.com/Expensify/App/pull/27966/files#r1431221038
3. I don't think that a Slack conversation is required here since this was a un-intentional miss.
4. A regression test would be helpful. The steps given in the OP look clear enough to me.

**Comment by JmillsExpensify** [comment] 2023-12-29 17:29
Contributor paid out, so closing this issue. @allroundexperts please request payment via Expensify when you get a chance!

**Closed by JmillsExpensify** 2023-12-29 17:29 UTC
Labels: Reviewing, External, Engineering, Weekly, Bug

**Comment by JmillsExpensify** [comment] 2024-01-24 23:56
$500 payment to @allroundexperts based on [this comment](https://github.com/Expensify/App/issues/30062#issuecomment-1853294643).
