### ISSUE TITLE
[$500] Theme - Upload photo icon remains white in light mode

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#33316] opened 2023-12-19 21:40 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.14-1
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** Applause - Internal Team
**Slack conversation:**

## Action Performed:
Precondition: App is in light mode
1. Go to Settings
2. Go to Profile

## Expected Result:
Upload photo icon will change in light mode

## Actual Result:
Upload photo icon remains white in light mode (same as dark mode)

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [x] Android: mWeb Chrome
- [x] iOS: Native
- [x] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details> 

![Bug6320237_1703016741459!Screenshot_2023-12-20_at_00 13 02](https://github.com/Expensify/App/assets/78819774/2ee0ec5d-b930-4450-b14d-a8db60b8650e)

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01d35a7c365cf9b6d8</li>
        <li>Upwork Job ID: 1737226519301242880</li>
        <li>Last Price Increase: 2023-12-19</li>
<li>Automatic offers: </li>
<ul>
<li>situchan | Reviewer | 28071203</li>
<li>ZhenjaHorbach | Contributor | 28071204</li>
<li>hoangzinh | Contributor | 28077945</li>
</ul></li>
    </ul>
</details>

**Comment by yh-0218** [comment] 2023-12-19 23:30
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
Theme - Upload photo icon remains white in light mode
### What is the root cause of that problem?
https://github.com/Expensify/App/blob/8a283f0e1fa292fe1a18c673b3e44fc5c4ad915a/src/components/AvatarWithImagePicker.js#L320-L325

We are using `theme.textLight` to fill icon.
https://github.com/Expensify/App/blob/8a283f0e1fa292fe1a18c673b3e44fc5c4ad915a/src/styles/theme/themes/light.ts#L50
We are using white color for white theme.
This make error.
### What changes do you think we should make in order to solve the problem?
We need to change this.
```
textLight: colors.productLight900
```
why?
https://github.com/Expensify/App/blob/8a283f0e1fa292fe1a18c673b3e44fc5c4ad915a/src/styles/theme/themes/dark.ts#L49-L50


### What alternative solutions did you explore? (Optional)

**Comment by razvanb96** [comment] 2023-12-20 14:55
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
Upload photo camera Icon remains white while in light mode

### What is the root cause of that problem?
The color of the Icon is hardcoded to the light version of it

### What changes do you think we should make in order to solve the problem?
Change the fill of that icon to another value that is aware of the theme selected. By doing this it will automatically change between the light and dark versions

### What alternative solutions did you explore? (Optional)
Not needed as this would align to other parts of the codebase

**Comment by narefyev91** [comment] 2023-12-21 07:59
Proposal from @ZhenjaHorbach looks good to me https://github.com/Expensify/App/issues/33316#issuecomment-1863514818
All proposal are the same - and here will be easy fix - @ZhenjaHorbach was a first one. Thank you all
🎀 👀 🎀 C+ reviewed

**Comment by narefyev91** [comment] 2023-12-21 08:10
> @narefyev91, I think the first correct solution is mine. Can you pls check and confirm with the design team.

Hey! Your solution is the same as all contributors wrote before - the issue is that fill for icon every time will be in white. And to fix it - we need to use different theme prop - to make it consistently between dark and light theme.

**Comment by narefyev91** [comment] 2023-12-21 08:16
> I pointed out the correct variable that is being used in other places for icons.

For sure - but picking proposal is not only about 'correct value' - it's a full composition of root case and steps to fix that. Which value should be picked or creating a new set of theme's or searching for correct value in the same places or pinging design team to check - all this should be done during PR raising. In any case we will wait final decision from @lakchote

**Comment by yh-0218** [comment] 2023-12-21 16:58
hi, @narefyev91 Could you check my [proposal](https://github.com/Expensify/App/issues/33316#issuecomment-1863613654)?

**Comment by garrettmknight** [comment] 2023-12-27 18:51
Relabling to get new C+ and internal engineers

**Comment by garrettmknight** [comment] 2023-12-27 18:51
@situchan can you give this a look when you get a chance?

**Comment by garrettmknight** [comment] 2023-12-27 18:55
@roryabraham can you take a look at this one and assign @ZhenjaHorbach if you think it's good?

**Comment by situchan** [comment] 2023-12-27 19:14
@Expensify/design do you agree to use `theme.text`? (productDark900 (#E7ECE9) in dark mode, productLight900 (#002E22) in light mode)

<img alt="avatar_with_image_picker_dark" width="96" src="https://private-user-images.githubusercontent.com/85894871/292126496-2936be0a-13f5-4ff1-b05d-eab4a49b3399.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDM3MDQxMjcsIm5iZiI6MTcwMzcwMzgyNywicGF0aCI6Ii84NTg5NDg3MS8yOTIxMjY0OTYtMjkzNmJlMGEtMTNmNS00ZmYxLWIwNWQtZWFiNGE0OWIzMzk5LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzEyMjclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjI3VDE5MDM0N1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTdiM2E0NDk4YTVkYWNiNjBlNGFhZWE1ZTgxYjc4NmRlNTQwZGJmNmRiMzgxNjY3OWRiNDZiMTQxZTU2YWQzMWYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.c708X9sLfbMojoGMdc0gKDBlyU0nfRLrdbxwiHlN3D0"> <img alt="avatar_with_image_picker_light_1" width="98" src="https://private-user-images.githubusercontent.com/85894871/292126502-cf625a89-57c8-4e09-9356-12e45c63ba98.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDM3MDQxMjcsIm5iZiI6MTcwMzcwMzgyNywicGF0aCI6Ii84NTg5NDg3MS8yOTIxMjY1MDItY2Y2MjVhODktNTdjOC00ZTA5LTkzNTYtMTJlNDVjNjNiYTk4LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzEyMjclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjI3VDE5MDM0N1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTNkMjYyN2I4ODIyMDc2OTlkZmNmNDRlNTE3MjZlYWRmZWQyMGY2MDQ3MjZmZWMzNDU1NzNjYTNiOGJlZGJiYmImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.q3Dr2EkkyjtmN35bO8WRspnuaq_bTfSKpe4aU6huAhU">

**Comment by yh-0218** [comment] 2023-12-27 19:42
hi, @situchan Do you think `textLight: colors.white` this is right?

**Comment by situchan** [comment] 2023-12-27 19:56
> hi, @situchan Do you think `textLight: colors.white` this is right?

it's weird but intentional for now

**Comment by situchan** [comment] 2023-12-27 19:59
I agree with original C+'s [recommendation](https://github.com/Expensify/App/issues/33316#issuecomment-1865818100).
I think we can deprecate `theme.inverse` as it's exactly same as `theme.text`

cc: @roryabraham

**Comment by dubielzyk-expensify** [comment] 2024-01-02 04:17
I believe we should use `button` for the background circle and `text` for the icon:

![image](https://github.com/Expensify/App/assets/145416827/3c119cfb-894b-44f9-98c2-20e1a5b286a6)

Please feel free to correct me @Expensify/design. By using `button` and `text` it should flip nicely between dark and light mode

**Comment by shawnborton** [comment] 2024-01-02 08:50
I kinda think we should just follow our standard button patterns here and always use color.icon for the icon, and color.button for the button BG. Thoughts on something like that?

**Comment by shawnborton** [comment] 2024-01-02 09:25
`buttonDefaultBG` would be what we'd use for the default button background.

**Comment by shawnborton** [comment] 2024-01-02 09:35
That feels consistent with all of our buttons, so that would be my vote.

**Comment by dannymcclain** [comment] 2024-01-02 13:54
Just added [a similar comment to this issue](https://github.com/Expensify/App/issues/33146#issuecomment-1874052181). I think right now in the product this button deviates from our standard styles, but I don't see any reason why that should be the case. I'm all for making it follow the standard primary button styles.

**Comment by roryabraham** [comment] 2024-01-02 22:02
I'm going to reassign this from @situchan do @hoangzinh because I know @situchan has a number of higher-priority issues on his plate.

**Comment by dubielzyk-expensify** [comment] 2024-01-02 23:17
I agree with you, Danny. Best using button + icon colors

**Comment by roryabraham** [comment] 2024-01-18 06:25
Agree, not sure why the automation didn't work here...

@garrettmknight this is ready for payment

**Comment by garrettmknight** [comment] 2024-01-18 21:05
Sorry about that - just paid both of you out.

**Closed by garrettmknight** 2024-01-18 21:05 UTC
Labels: External, Engineering, Daily, Awaiting Payment, Bug
