### ISSUE TITLE
[HOLD for payment 2024-10-10] [$250] Bank Account - "Please provide a valid email" error is not dismissed when navigating back

### ISSUE THREAD

**Issue by IuliiaHerets** [Expensify/App#49129] opened 2024-09-12 18:50 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** v9.0.33-1
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**Email or phone of affected tester (no customers):** gibethlehem.@gmail.com
**Issue reported by:** Applause Internal Team

## Action Performed:
1. Log in to an account
2. Create a workspace > Enable Workflow > Connect bank account > Connect online with plaid
3. continues the flow until you reached "Company website" page
4. Click on "Next" button with out entering an email. Notice error is shown.
5. Navigate back to "Tax" > Click next. Notice "Please provide a valid email" is shown
6. Navigate back

## Expected Result:
"Please provide a valid email" error is not shown

## Actual Result:
"Please provide a valid email" error is shown even after navigating back to other pages.

## Workaround:
Unknown

## Platforms:

- [ ] Android: Native
- [x] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

https://github.com/user-attachments/assets/5584ae4c-14da-4efa-8c4c-320b772883b3

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~021838748303382636901</li>
        <li>Upwork Job ID: 1838748303382636901</li>
        <li>Last Price Increase: 2024-09-25</li>
<li>Automatic offers: </li>
<ul>
<li>allgandalf | Reviewer | 104202965</li>
</ul></li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @anmurali</details>

**Comment by IuliiaHerets** [comment] 2024-09-12 18:50
@anmurali  FYI I haven't added the External label as I wasn't 100% sure about this issue. Please take a look and add the label if you agree it's a bug and can be handled by external contributors

**Comment by blimpich** [comment] 2024-10-02 17:48
Removed reviewing label as the PR for this issue was reverted. I'm about to go on vacation so I will not be able to help with the fix until I'm back on October 14th. @anmurali if we want this out sooner than that, can you reassign this to another engineer?

**Comment by mallenexpensify** [comment] 2024-10-03 22:29
Looks like there was a regression from[ this PR](https://github.com/Expensify/App/pull/49957) , please review before paying @anmurali 
- https://github.com/Expensify/App/issues/50086

**Comment by mallenexpensify** [comment] 2024-10-12 00:21
Contributor: @twilight294 due $250 via Upwork
Contributor+: @allgandalf paid $250 via Upwork.  

Apologies for the delay @twilight294 , can you please apply for the job, then we'll hire and pay? 
https://www.upwork.com/jobs/~021844895880907146867

Thx

**Comment by mallenexpensify** [comment] 2024-10-16 15:57
Apologies @twilight294 , I just invited you to the job, can you accept then I'll pay?
In the 3+ years we've been working with Upwork, I haven't encountered the issue you're experiencing.

**Comment by mallenexpensify** [comment] 2024-10-16 16:06
I think it's hard for newer freelancers in Upwork.  And, for working with us, once you've been hired for 1 job it's a LOT easier to find and hire you for future jobs.  Can you please accept the job and reply here once you have? 
https://www.upwork.com/jobs/~021844895880907146867

**Comment by mallenexpensify** [comment] 2024-10-16 16:36
Thanks @twilight294 , you've been paid.  Payment breakdown updated above too. 

Test case created too
- https://github.com/Expensify/Expensify/issues/436636

🚀

**Closed by mallenexpensify** 2024-10-16 16:36 UTC
Labels: External, Daily, Awaiting Payment, Bug
