### ISSUE TITLE
[$500] iOS - Chat - The screen flashes when I tap on "Delete comment"

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#33312] opened 2023-12-19 21:06 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.14.0
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** Applause - Internal Team
**Slack conversation:**

## Action Performed:
1. Navigate to https://staging.new.expensify.com/
2. Make a workspace
3. Go offline
4. Write any text in the #announce room
5. Delete any text

## Expected Result:
There shouldn't be any flashing

## Actual Result:
The screen flashes when I tap on "Delete comment". The keyboard appears for a very short time and disappears

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [x] Android: mWeb Chrome
- [x] iOS: Native
- [x] iOS: mWeb Safari
- [ ] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details> 

https://github.com/Expensify/App/assets/78819774/5586a04d-c050-4468-8c2d-8f70ed38850c

 
[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01766b41eca1f7098c</li>
        <li>Upwork Job ID: 1737217847599263744</li>
        <li>Last Price Increase: 2024-02-21</li>
    </ul>
</details>

**Comment by mananjadhav** [comment] 2023-12-20 02:22
I think this should probably get resolved with https://github.com/Expensify/App/issues/32970

**Comment by CortneyOfstad** [comment] 2024-01-02 18:32
Not overdue

**Comment by mananjadhav** [comment] 2024-01-10 05:07
The linked PR didn't fix this and we're open for proposals here.

**Comment by mananjadhav** [comment] 2024-01-29 00:39
Open for proposals.

**Comment by CortneyOfstad** [comment] 2024-01-31 18:34
^^^ can ignore that as the linked PR was not successful. 

Added `help wanted` to get some proposals rolling

**Comment by CortneyOfstad** [comment] 2024-02-06 15:33
@lanitochka17 can we confirm the issue is still happening? I just want to double check since this issue has been open for a while 👍

**Comment by lanitochka17** [comment] 2024-02-07 15:46
Issue is still reproducible on the latest build 1.4.38-0


https://github.com/Expensify/App/assets/78819774/42a0d260-7e2b-48ab-bbb6-8c221b10f5b5

**Comment by CortneyOfstad** [comment] 2024-02-14 14:05
Thank you @lanitochka17!

**Comment by CortneyOfstad** [comment] 2024-02-15 19:03
This falls under VIP-VSB and still can see the flashing despite the latest app upgrade. So strange, so getting eyes on this!

**Comment by CortneyOfstad** [comment] 2024-02-15 19:05
^^^ not sure what the heck happened, but I changed one tag and everything went insane 🙃

**Comment by CortneyOfstad** [comment] 2024-02-22 18:56
Reached out to Callstack [here](https://expensify.enterprise.slack.com/archives/C03UK30EA1Z/p1708628197921189)

**Comment by rezkiy37** [comment] 2024-02-23 15:58
Hi, I’m Michael (Mykhailo) from Callstack and I would like to work on this issue.

**Comment by quinthar** [comment] 2024-02-25 08:31
I'm not sure I understand the issue -- I watched the video, but can you clarify what you mean by "flash"?  I don't see a problem.

**Comment by rezkiy37** [comment] 2024-02-26 11:18
I agree with a [comment](https://github.com/Expensify/App/issues/33312#issuecomment-1962856456) above. I tried to reproduce the bug on a real IOS device, simulator and Android emulator. I haven't seen any flashes. I attach a couple videos. 

<details><summary>Videos</summary>
<p>

https://github.com/Expensify/App/assets/57314631/a229dec0-4e31-4df4-8456-dd204ccdce4f


https://github.com/Expensify/App/assets/57314631/2cdc6c66-b134-4d04-b728-43b4697e9329

</p>
</details>

**Comment by CortneyOfstad** [comment] 2024-02-28 14:48
Not able to recreate on my side either so going to close this 👍 

Thanks for the additional testing @mvtglobally and @rezkiy37!

**Closed by CortneyOfstad** 2024-02-28 14:48 UTC
Labels: External, Weekly, Bug
