### ISSUE TITLE
[$500] Tag - "no longer valid" initially appears for Tag when request with a valid tag is created

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#34804] opened 2024-01-19 14:45 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.28-0
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** Applause - Internal Team
**Slack conversation:**

## Action Performed:
Precondition:
- User is an employee of Collect workspace on Old Dot which has tags
1. Go to workspace chat and open manual request page
2. Enter amount > Next > Show more
3. Click Tag and select a tag
4. Create the request
5. Immediately open request details page
6. Return to expense report and go to request details page again

## Expected Result:
Since the selected tag is existing and valid, "no longer valid" will not appear on Tag row

## Actual Result:
"no longer valid" appears on Tag row when the request details page is visited immediately after requesting it. It disappears when revisiting the page

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [x] Android: mWeb Chrome
- [x] iOS: Native
- [x] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details> 

https://github.com/Expensify/App/assets/78819774/efa096ff-282f-4cd9-8a9a-7e55a648770b

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~014d7530b698dd531e</li>
        <li>Upwork Job ID: 1748356015802679296</li>
        <li>Last Price Increase: 2024-01-19</li>
    </ul>
</details>

**Comment by lanitochka17** [comment] 2024-01-19 14:46
[#wave6-collect-submitters](https://expensify.enterprise.slack.com/archives/C02MW39LT9N)

**Comment by cead22** [comment] 2024-01-19 16:45
I think there was a network request that failed in there, notice how the compose box is gone in the screenshot. Also, being able to selected a tag that isn't in the policy means you don't have the updated tags on the client, so we're either not sending the update, or the network failed there too. Can this be reproduced reliably?

<img width="798" alt="image" src="https://github.com/Expensify/App/assets/165133/43d6fc23-9d02-4a28-93ea-958253f4e161">

**Comment by miljakljajic** [comment] 2024-01-23 17:07
@lanitochka17 is this still reproducible for you? I tried but I wasn't able to get up a tag list even though the collect workspace had tags on it. I was working in staging. Can anyone provide some more detail in the repro steps? (sorry!)

**Comment by lanitochka17** [comment] 2024-01-24 19:23
@miljakljajic Hello
Still reproducible on v1.4.31-4
Immediately open request details page

https://github.com/Expensify/App/assets/78819774/b4c5f235-00b6-40a2-84be-fbe6391c6e16

**Comment by cead22** [comment] 2024-01-25 19:57
It looks like going into the thread failed again, and I'm pretty sure it's the same issue as this one https://github.com/Expensify/App/issues/33114, which will be fixed as part of this issue https://github.com/Expensify/App/issues/31411, so closing

**Closed by cead22** 2024-01-25 19:57 UTC
Labels: External, Daily, Help Wanted, Bug
