### ISSUE TITLE
[$500] Scan Request - Green dot appears in LHN of WS chat of admin while employee's request is scanning

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#36156] opened 2024-02-08 15:13 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.38-3
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**If this was caught during regression testing, add the test name, ID and link from TestRail:** https://expensify.testrail.io/index.php?/tests/view/4287262
**Email or phone of affected tester (no customers):** u.onyeukwu94+0208@gmail.com
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** Applause - Internal Team
**Slack conversation:**

## Action Performed:
1. As Admin(User A) invite any employee(User B) to WS
2. As User B send a scan request in WS chat
3. Observe WS chat in LHN of User A

## Expected Result:
There is no indication that there is a scan request scanning

## Actual Result:
Green is shown in LHN of WS chat

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details> 

https://github.com/Expensify/App/assets/78819774/8dbe5400-2f42-4ac7-b615-2e5fb33d0602

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01e63ab91176fbaf7b</li>
        <li>Upwork Job ID: 1755610698275532800</li>
        <li>Last Price Increase: 2024-02-29</li>
    </ul>
</details>

**Comment by lanitochka17** [comment] 2024-02-08 15:14
We think that this bug might be related to #wave5
CC @dylanexpensify

**Comment by Tony-MK** [comment] 2024-02-10 03:00
## Proposal

### Please re-state the problem that we are trying to solve in this issue.

A green dot appears in LHN of the WS chat of admin while the employee's request is scanning.

### What is the root cause of that problem?

The `requiresAttentionFromCurrentUser` function determines to show the green dot.

The function will return true if `hasOutstandingChildRequest` is `true`.

When a receipt is scanned, `hasOutstandingChildRequest` is `true` only for the admin.

Even if the admin did not create the transaction.

https://github.com/Expensify/App/blob/1b060129b537a206fdf170239809ad8520ebffd4/src/libs/ReportUtils.ts#L1792-L1795

Therefore, the admin will see the green dot when scanning is in progress.

### What changes do you think we should make in order to solve the problem?


Let's edit the condition to notify the admin when at least one transaction is ready for action.

If all transactions are receipts, check if at least one of the receipts has completed scanning.

Therefore, the condition should look like the pseudo-code similar to the one below.

```
if (
    optionOrReport.hasOutstandingChildRequest && 
    !TransactionUtils.getAllReportTransactions(
     getIOUReport(optionOrReport.reportID)
    ).every(
       (trans) => TransactionUtils.isReceipt(trans) && 
         TransactionUtils.isReceiptBeingScanned(trans)
    )
) 
```

Optionally, we can check if all the scans were also not created by the admin to ignore the green dot. I didn't this statement in the pseudo-code as it is optional.

Lastly, we should apply the same condition to other places which need attention.

**Comment by alexpensify** [comment] 2024-02-16 00:05
I started a discussion here: 

https://expensify.slack.com/archives/C01GTK53T8Q/p1708041900703759

--- 

Heads up, I will be OOO tomorrow but will catch up in the thread next week. Thanks!

**Comment by alexpensify** [comment] 2024-02-23 00:05
I bumped the 🧵 again in Slack.

**Comment by alexpensify** [comment] 2024-02-27 00:59
No update in the 🧵

**Comment by mvtglobally** [comment] 2024-02-27 15:48
Issue not reproducible during KI retests. (First week)

**Comment by alexpensify** [comment] 2024-03-01 02:01
Yep! Closing this one.

**Closed by alexpensify** 2024-03-01 02:01 UTC
Labels: External, Engineering, Daily, Help Wanted, Bug
