### ISSUE TITLE
[$250] Tapping to watch a video in a public room, it goes to a previous image rather than playing the video

### ISSUE THREAD

**Issue by m-natarajan** [Expensify/App#41958] opened 2024-05-09 21:35 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.72-1
**Reproducible in staging?:** Yes
**Reproducible in production?:** Yes
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** @danielrvidal 
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1715278682891739

## Action Performed:

1. Navigate to https://new.expensify.com/r/6879144773653084 on a new account on mobile Chrome
2. Browse the room as guest
3. Navigate to a video and tap play icon to watch the video

## Expected Result:
Selected video plays
## Actual Result:
 Instead of displaying the video, it is showing an image that was shared previous in the post.  If I scroll to the right of the image files I can successfully watch the video.
## Workaround:
Unknown
## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [x] iOS: Native
- [ ] iOS: mWeb Safari
- [ ] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

https://github.com/Expensify/App/assets/38435837/019e747c-7b1f-47df-a90c-d8eaa5d4db17

https://github.com/Expensify/App/assets/38435837/5f796be1-1b25-43fc-9dbc-ceb8a3849f05

[logs-2024-05-09 18_12_51.442.txt](https://github.com/Expensify/App/files/15267859/logs-2024-05-09.18_12_51.442.txt)

Add any screenshot/video evidence

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~0167d7b36965243244</li>
        <li>Upwork Job ID: 1792935001914122240</li>
        <li>Last Price Increase: 2024-06-11</li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @muttmuure</details>

**Comment by muttmuure** [comment] 2024-05-15 07:39
Looking at this today

**Comment by DylanDylann** [comment] 2024-05-24 03:22
Looking for proposal

**Comment by DylanDylann** [comment] 2024-05-28 02:24
Waiting on proposal

**Comment by DylanDylann** [comment] 2024-05-28 18:09
@muttmuure  Should we consider adjusting the bounty to get more attention?

**Comment by samilabud** [comment] 2024-05-31 19:20
I can't reproduce the bug, can you still reproduce it?

https://github.com/Expensify/App/assets/5216036/42f04c8c-36d6-44f0-8735-926e23958328

Version Number: 1.4.78-3

**Comment by DylanDylann** [comment] 2024-06-04 09:04
I also can't reproduce anymore

https://github.com/Expensify/App/assets/141406735/f9a8475d-145b-43b0-b647-a3f751022134

@danielrvidal Tag you to confirm because you reported this bug.

@muttmuure Or please add re-test label to get eyes from the QA team

**Comment by muttmuure** [comment] 2024-06-05 14:29
Catching up from OOO

**Comment by muttmuure** [comment] 2024-06-07 14:52
Added retest label

**Comment by muttmuure** [comment] 2024-06-07 14:59
Not overdue

**Comment by DylanDylann** [comment] 2024-06-11 04:50
@muttmuure Let's close this one

**Closed** 2024-06-11 16:11 UTC
Labels: External, Daily, Help Wanted, Overdue, Bug, retest-weekly
