### ISSUE TITLE
[Hold for payment 2024-04-30][$250] Workspace switcher - Expensify is no longer bolded and missing RBR after refreshing the page

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#39928] opened 2024-04-09 13:12 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:**
**Reproducible in staging?:**
**Reproducible in production?:**
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:**
**Slack conversation:**

## Action Performed:
Precondition:
- There are a few workspaces with RBR (can be invoked by creating scan request with invalid receipt).

1. Go to staging.new.expensify.com
2. Open the workspace switcher.
3. Select Expensify in the list (if not selected).
4. Refresh the page.

## Expected Result:
After refreshing the page,
- the selected Expensify should remain bolded in the list
- RBR will remain next to the workspaces that have it

## Actual Result:
After refreshing the page,
- the selected Expensify is not longer bolded in the list
- RBRs disappear

## Workaround:
n/a

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [x] Android: mWeb Chrome
- [ ] iOS: Native
- [x] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

https://github.com/Expensify/App/assets/93399543/c30b86f8-61c7-4721-99cb-88fcee05f1f2

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01d57cfb7d1d01cfcd</li>
        <li>Upwork Job ID: 1777718400311140352</li>
        <li>Last Price Increase: 2024-04-09</li>
<li>Automatic offers: </li>
<ul>
<li>eh2077 | Reviewer | 0</li>
<li>ikevin127 | Contributor | 0</li>
</ul></li>
    </ul>
</details>

**Comment by kbecciv** [comment] 2024-04-09 13:12
We think that this bug might be related to #vip-vsb

**Comment by kbecciv** [comment] 2024-04-09 13:12
@lschurr I haven't added the External label as I wasn't 100% sure about this issue. Please take a look and add the label if you agree it's a bug and can be handled by external contributors

**Comment by FitseTLT** [comment] 2024-04-09 13:34
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
Workspace switcher - Expensify is no longer bolded and missing RBR after refreshing the page

### What is the root cause of that problem?
These functions are returning empty object because the moment they are called `allReports` is not popuplated
https://github.com/Expensify/App/blob/ad9b5d7a2ee54ad6379538b84c322fc29b2a6adb/src/pages/WorkspaceSwitcherPage.tsx#L66-L67
### What changes do you think we should make in order to solve the problem?

We have many options to solve it we can remove the memo and make it like this
```
    const brickRoadsForPolicies = getWorkspacesBrickRoads();
    const unreadStatusesForPolicies = getWorkspacesUnreadStatuses();
```
But most appropriately we need to subscribe to reports collection and a pass it as a param to both functions and calculated based on that value so that it will be calculated and updated correctly
### What alternative solutions did you explore? (Optional)

**Comment by FitseTLT** [comment] 2024-04-09 13:40
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
Workspace switcher - Expensify is no longer bolded and missing RBR after refreshing the page

### What is the root cause of that problem?
These functions are returning empty object because the moment they are called `allReports` (which is a global scoped var populated with withonyx) is not popuplated
https://github.com/Expensify/App/blob/ad9b5d7a2ee54ad6379538b84c322fc29b2a6adb/src/pages/WorkspaceSwitcherPage.tsx#L66-L67
https://github.com/Expensify/App/blob/ad9b5d7a2ee54ad6379538b84c322fc29b2a6adb/src/libs/WorkspacesSettingsUtils.ts#L25-L26
### What changes do you think we should make in order to solve the problem?


But most appropriately we need to subscribe to reports collection in `WorkspaceSwitcherPage` and a pass `allReports` as a param to both functions and calculated based on that value so that it will be calculated and updated correctly
```
    const brickRoadsForPolicies = useMemo(() => getWorkspacesBrickRoads(allReports), [allReports]);
    const unreadStatusesForPolicies = useMemo(() => getWorkspacesUnreadStatuses(allReports), [allReports]);
```

### What alternative solutions did you explore? (Optional)
We have many options to solve it we can remove the memo and make it like this
```
    const brickRoadsForPolicies = getWorkspacesBrickRoads();
    const unreadStatusesForPolicies = getWorkspacesUnreadStatuses();
```

**Comment by FitseTLT** [comment] 2024-04-09 14:11
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
Workspace switcher - Expensify is no longer bolded and missing RBR after refreshing the page

### What is the root cause of that problem?
These functions are returning empty object because the moment they are called (on first render)`allReports` (which is a global scoped var populated with withonyx) is not popuplated
https://github.com/Expensify/App/blob/ad9b5d7a2ee54ad6379538b84c322fc29b2a6adb/src/pages/WorkspaceSwitcherPage.tsx#L66-L67
https://github.com/Expensify/App/blob/ad9b5d7a2ee54ad6379538b84c322fc29b2a6adb/src/libs/WorkspacesSettingsUtils.ts#L25-L26
### What changes do you think we should make in order to solve the problem?


We need make our calculation depend on a component cycle variable (`prop`), i.e. subscribe to reports collection in `WorkspaceSwitcherPage` and a pass `allReports` as a param to both functions and calculated based on that value so that it will be calculated and updated correctly
```
    const brickRoadsForPolicies = useMemo(() => getWorkspacesBrickRoads(allReports), [allReports]);
    const unreadStatusesForPolicies = useMemo(() => getWorkspacesUnreadStatuses(allReports), [allReports]);
```

### What alternative solutions did you explore? (Optional)
We have many options to solve it we can remove the memo and make it like this
```
    const brickRoadsForPolicies = getWorkspacesBrickRoads();
    const unreadStatusesForPolicies = getWorkspacesUnreadStatuses();
```

**Comment by ikevin127** [comment] 2024-04-09 17:27
# Proposal

### Please re-state the problem that we are trying to solve in this issue

After refreshing the page:
- the selected **Expensify** is not longer bolded in the list
- RBRs disappear from the other workspaces

### What is the root cause of that problem?

We're memoizing the `brickRoadsForPolicies` and `unreadStatusesForPolicies` [here](https://github.com/Expensify/App/blob/ad9b5d7a2ee54ad6379538b84c322fc29b2a6adb/src/pages/WorkspaceSwitcherPage.tsx#L66-L67).

The two functions coming from `WorkspacesSettingsUtils` are using `allReports` which is populated via `Onyx.connect` in the action file (outside of any component lifecycle) and additionally it has `waitForCollectionCallback` set to `true` which means: `If set to true, it will return the entire collection to the callback as a single object.`

Because this is not instant, it causes the memoized functions to always return the data from when `allReports` is not populated yet, hence `brickRoadsForPolicies` and `unreadStatusesForPolicies` don't contain any data -> causing:
- the selected **Expensify** to not longer have the bold text style
- RBRs disappear from the other workspaces

### What changes do you think we should make in order to solve the problem?

> [!important]
> We want to preserve the memoization because `brickRoadsForPolicies` and `unreadStatusesForPolicies` can contain a lot of data and we don't want to recalculate both functions with every render (unnecessarily).

Therefore I propose adding the `reports` prop from the bottom of the component via `withOnyx` then pass `reports` to both useMemo's dependency array. The change will look like this:

```ts
    const brickRoadsForPolicies = useMemo(() => getWorkspacesBrickRoads(), [reports]);
    const unreadStatusesForPolicies = useMemo(() => getWorkspacesUnreadStatuses(), [reports]);
```

By doing this we make sure that we only recalculate the functions when `reports` change which is exactly the equivalent of `allReports` from `WorkspacesSettingsUtils` [here](https://github.com/Expensify/App/blob/4f673576491af54296014b7595e6ad5017fdb60e/src/libs/WorkspacesSettingsUtils.ts#L22-L26) -> so when it changes there, our memoized functions will recalculate, we'll get the data and our issue will be fixed.

### Videos (before / after)

<details>
<summary>MacOS: Chrome / Safari</summary>

| Before | After |
| ------------- | ------------- |
| <video src="https://github.com/Expensify/App/assets/56457735/e1e71f9e-d7ef-4d26-9fa2-456e331b51e4"> | <video src="https://github.com/Expensify/App/assets/56457735/c5e82e15-b3e1-4737-a9bb-3d5b9f233d26"> |

</details>

**Comment by Skakruk** [comment] 2024-04-10 17:30
## Proposal

### Please re-state the problem that we are trying to solve in this issue.

After refreshing the page:

- the selected Expensify is not longer bolded in the list
- RBRs disappear from the other workspaces

### What is the root cause of that problem?

Both of the functions are memorized 

https://github.com/Expensify/App/blob/342b16dceaa277ae00e689eca06639f1759f7c56/src/pages/WorkspaceSwitcherPage.tsx#L66-L67

and will not retrieve new data coming from Onyx.connect 

https://github.com/Expensify/App/blob/b394f3d7803cf14df71dbcdee56860af14de0194/src/libs/WorkspacesSettingsUtils.ts#L22-L26

### What changes do you think we should make to solve the problem?

I propose to wrap `Onyx.connect`, `getWorkspacesBrickRoads()` and `getWorkspacesUnreadStatuses()` in separate custom hooks. 

Both of them will be similar. We subscribe to connection callback, setting the internal state for retrieved data.
_Pseudocode_

```
const [state, setState] = useState();
useEffect(() => {
    const connectionID = Onyx.connect(...., callback: (val) => setState(val));
    return () => Onyx.disconnect(connectionID);
}, []);
```

Then we can process the retrieved data (process brick data or determine unread status) and memorize it.

Later, in `WorkspaceSwitcherPage.tsx` we use those hooks, replacing existing ones. So that data is already memoized.

```
const unreadStatusesForPolicies = useUnreadStatusesForPolicies();
```

In this case, we are getting the correct information about reports and policies immediately. No matter if it's on web app start or later in use when we receive updates on reports.


### What alternative solutions did you explore? (Optional)

**Comment by ikevin127** [comment] 2024-04-10 23:41
## Updated [proposal](https://github.com/Expensify/App/issues/39928#issuecomment-2045740587)
- added alternative solution motivated by recent developments / addition of `useOnyx` hook within `react-native-onyx` and first usage within PR: https://github.com/Expensify/App/pull/38924

**Comment by eh2077** [comment] 2024-04-11 04:47
Reviewing proposals

**Comment by eh2077** [comment] 2024-04-11 06:10
Thank you all for your proposals!

@ikevin127 's [proposal](https://github.com/Expensify/App/issues/39928#issuecomment-2045740587) looks good me. I agree with their RCA and their alternative solution to use the new hook `useOnyx`.

🎀👀🎀 C+ reviewed

**Comment by Skakruk** [comment] 2024-04-11 09:40
While debugging this issue, I spotted a bug with `userWorkspaces` list, that `WorkspaceSwitcherPage` always display workspace names in bold styles, no matter if there are any unread messages or not.

<img width="368" alt="Screenshot 2024-04-11 at 12 38 58" src="https://github.com/Expensify/App/assets/1768919/04340add-96bc-4f85-9810-4609008be18a">

It's because `UserListItem` expects `item` to have property `isBold`, 

https://github.com/Expensify/App/blob/1eb3065587c0544f712fed4c9fda828da1b99a41/src/components/SelectionList/UserListItem.tsx#L120

but we provide property `boldStyle`

https://github.com/Expensify/App/blob/479efd67a4e634d34d391f0c489690be517152f5/src/pages/WorkspaceSwitcherPage.tsx#L136

Changing line to `isBold: hasUnreadData(policy?.id) ?? false,` fixes the issue

<img width="370" alt="Screenshot 2024-04-11 at 12 39 55" src="https://github.com/Expensify/App/assets/1768919/07924b94-dbb7-4195-a85d-86ca552a83b1">

**Comment by eh2077** [comment] 2024-04-11 13:21
> @eh2077 I really disagree with your choice because the selected proposal doesn't have any significant difference in RCA and also solution than [mine](https://github.com/Expensify/App/issues/39928#issuecomment-2045280100) which was proposed way before the selected one. Using a `useOnyx` over `withOnyx` is a tiny implementation detail, infact which we are just only starting to use, and that can be easily negotiated in PR stage. Please reconsider your review. cc @iwiznia

@FitseTLT Thanks for your comment. I would definitely vote for your proposal if useOnyx were just a new syntactic sugar, but it's not. It eliminates the UI transition. So, I tend to stick to my original decision.

**Comment by eh2077** [comment] 2024-04-11 13:23
@Skakruk Thank you for sharing your finding!

**Comment by ikevin127** [comment] 2024-04-12 18:22
@iwiznia All good for assignment here based on https://github.com/Expensify/App/issues/39928#issuecomment-2048988197 and https://github.com/Expensify/App/issues/39928#issuecomment-2049682309 ?
I noticed you 👍 the second one yesterday!

**Comment by ikevin127** [comment] 2024-04-12 22:01
PR https://github.com/Expensify/App/pull/40197 is ready for review! 🎉

**Comment by ikevin127** [comment] 2024-04-25 02:39
⚠️ Automation failed here -> this should be on **Hold for payment [2024-04-30]** according to yesterday's production deploy from https://github.com/Expensify/App/pull/40197#issuecomment-2073663568.

**Comment by lschurr** [comment] 2024-04-25 15:18
Thanks @ikevin127!

**Comment by lschurr** [comment] 2024-04-30 15:24
Payment summary:

- Contributor: @ikevin127 $250 (paid in Upwork)
- Contributor+: @eh2077 $250 (paid in Upwork)

**Closed by lschurr** 2024-04-30 15:24 UTC
Labels: Reviewing, External, Weekly, Awaiting Payment, Bug
