### ISSUE TITLE
Web - Payments - Console error after opening Transfer Balance page by link from PR

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#19647] opened 2023-05-26 01:30 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Issue found when executing PR** https://github.com/Expensify/App/pull/19184

## Action Performed:
1. Sign out of NewDot if needed
2. Sign in with any account
3. Enter https://staging.new.expensify.com/settings/payments/transfer-balance
in the URL bar and hit enter

## Expected Result:
No console error is expected

## Actual Result:
Console error after opening Transfer Balance page by link from PR

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [x] Chrome / Chrome 
- [ ] MacOS / Desktop

**Version Number:** 1.3.18.1

**Reproducible in staging?:** yes

**Reproducible in production?:** n/a

**If this was caught during regression testing, add the test name, ID and link from TestRail:**

**Email or phone of affected tester (no customers):**

**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Notes/Photos/Videos:** Any additional supporting documentation

https://platform.applause.com/services/links/v1/external/83761a1c8393993223b649b64ce52102c9bd7494713ef59f5724bc38082b7d9e

**Expensify/Expensify Issue URL:**

**Issue reported by:** Applause - Internal Team

**Slack conversation:**

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by mallenexpensify** [comment] 2023-05-30 23:04
Able to reproduce
Error I see in console
> Unrecognized Content-Security-Policy directive 'prefetch-src'.

I think it might have to do with a user not having a bank account connected, therefore there is nothing to show for `/transfer-balance` and the "Transfer Balance" text/button don't show up in `Payments` 

@NikkiWines thoughts on how we should be handle this?

**Comment by PauloGasparSv** [comment] 2023-05-31 12:15
I think this error is known and was also reported here https://github.com/Expensify/App/issues/18533 (which was discussed recently [here](https://expensify.slack.com/archives/C049HHMV9SM/p1684741192618239)).

I'm also seeing that error in Staging in the authentication screen right + the "You appear to be offline." message:
<img width="1316" alt="image" src="https://github.com/Expensify/App/assets/6564265/2ba16b67-3caf-4b94-8197-233a702168d8">

**Comment by NikkiWines** [comment] 2023-06-02 00:25
Yeah, it looks like it's tied to issue @PauloGasparSv linked above - it doesn't seem to be specific to the transfer balance page - going to any page (on staging or prod) directly by URL prompts the same console error

<img width="757" alt="Screenshot 2023-06-01 at 17 16 45" src="https://github.com/Expensify/App/assets/16747822/ac659e19-f66f-46b2-8ae4-92e89591e170">

> I can see a prefetch CSP for the https://staging.new.expensify.com/ html fetch, I wonder if that is what is causing the problem. If the error stops happening (it looks like it usually does that) I'll double check that page's CSP header.

I think you're right, as Justin mentioned in slack `prefetch-src` is [deprecated](https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Content-Security-Policy/prefetch-src), so if it's showing up in our requests then it's not surprising we're seeing this console error.

**Comment by NikkiWines** [comment] 2023-06-05 19:03
@marcaaron do you think we should follow suit and close this issue, since you previously closed [the same issue](https://github.com/Expensify/App/issues/18533) back in May?

**Comment by marcaaron** [comment] 2023-06-06 02:55
yea sorry, as long as PDFs are working on all the platforms I'd have trouble justifying spending much time on this. It's really like a "NewDot Monthly" - if that was a real thing... 😄

**Comment by NikkiWines** [comment] 2023-06-08 01:16
Great, thanks @marcaaron! Going to close this out then 🙇

**Closed by NikkiWines** 2023-06-08 01:16 UTC
Labels: Engineering, Daily, Overdue, Bug
