### ISSUE TITLE
[$1000] Workspace - Settings - Chat Report is not in Spanish

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#19473] opened 2023-05-23 18:38 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Go to staging dot on chrome
2. Change language to Spanish
3. Create a workspace
4. Go to announce and send any message
5. Reply in the same thread
6. Click on the top bar and click on share code
7. Notice that Chat Report is not translated into Spanish

## Expected Result:
Chat Report should be in Spanish

## Actual Result:
Chat Report is not in Spanish

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [ ] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 1.3.17.0

**Reproducible in staging?:** yes

**Reproducible in production?:** yes

**If this was caught during regression testing, add the test name, ID and link from TestRail:**

**Email or phone of affected tester (no customers):**

**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/93399543/8de662ee-2f94-4863-81c1-f4383bc22291

**Expensify/Expensify Issue URL:**

https://github.com/Expensify/App/assets/93399543/aadc7177-7ae7-43e5-929e-e179ffcd33f1

**Issue reported by:** @priya-zha

**Slack conversation:**https://expensify.slack.com/archives/C049HHMV9SM/p1684419466036929

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01e9a2e8d3fb164e6d</li>
        <li>Upwork Job ID: 1661470659467784192</li>
        <li>Last Price Increase: 2023-05-31</li>
    </ul>
</details>

**Comment by dukenv0307** [comment] 2023-05-25 02:12
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
Workspace - Settings - Chat Report is not in Spanish
### What is the root cause of that problem?


We are using report.reportName to display title in QR Code Page
https://github.com/Expensify/App/blob/4d6a25fa9eb308a442866030688f6e1612d7a299/src/pages/ShareCodePage.js#L61

Thid field is not translated from BE
<img width="324" alt="Screenshot 2023-05-25 at 09 06 44" src="https://github.com/Expensify/App/assets/129500732/64a71d50-1df1-410b-bf90-227b8e1aba20">
### What changes do you think we should make in order to solve the problem?
In en.js and es.js we should define a new field like chatReport like this
IN en.js : chatReport: 'Chat Report'
IN es.js : chatReport: 'Informe de chat' (need to confirm with design team)

and then from BE update field reportName of these report  to key chatReport
### What alternative solutions did you explore? (Optional)

**Comment by abekkala** [comment] 2023-05-26 13:05
@rushatgabhane what do you think of the proposals that have come in?

**Comment by abekkala** [comment] 2023-05-29 19:21
@rushatgabhane have you had a chance to review the proposals?

**Comment by abekkala** [comment] 2023-06-02 16:00
@youssef-lr do you agree that this isn't a priority and to close?

**Comment by youssef-lr** [comment] 2023-06-06 01:55
@rushatgabhane how about a quick check if the report's name == `Chat Report` then translate it, if not keep the original `reportName`. A bit hacky right?

**Comment by youssef-lr** [comment] 2023-06-06 02:43
Ok then. Closing until we figure out backend translations. Thanks everyone!

**Closed by youssef-lr** 2023-06-06 02:43 UTC
Labels: External, Daily, Help Wanted, Bug
