### ISSUE TITLE
When creating a group with a concierge, the icon is displayed in the old style.

### ISSUE THREAD

**Issue by kavimuru** [Expensify/App#13110] opened 2022-11-28 23:28 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
 1. Go to https://staging.new.expensify.com/
and login
2. Create a new chat with Concierge

## Expected Result:
The Concierge icon should be in the new format (with a green triangle)

## Actual Result:
When creating a group with a concierge, the icon is displayed in the old format.

## Workaround:
unknown

## Platform:

Where is this issue occurring?

- Web
- iOS
- Android
- Desktop App
- Mobile Web

**Version Number:** 1.2.33-1
**Reproducible in staging?:** Y
**Reproducible in production?:**  (New feature)
**Email or phone of affected tester (no customers):** 
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** 

<img src="https://user-images.githubusercontent.com/43996225/204402020-e1421ee5-f540-4642-a57f-c1a2bfbec273.jpg" width="40%" height="40%">

**Expensify/Expensify Issue URL:** 
**Issue reported by:** Applause internal team
**Slack conversation:** 

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

## Upwork Automation - Do Not Edit
- Upwork Job URL: https://www.upwork.com/jobs/~01aeb420f5c4a00dfc
- Upwork Job ID: 1597444782925869056

**Comment by hungvu193** [comment] 2022-11-29 03:36
<b>Proposal</b>
Inside ReportActionItemSingle, I notice that we are still using the old Concierge icon image url so that's why this issue happend
<img width="938" alt="Screen Shot 2022-11-29 at 10 34 49" src="https://user-images.githubusercontent.com/16502320/204432393-d0037d40-55d1-4cf1-9896-bc9073c24104.png">
<b>Solution </b>
We need to update the icon url to new Concierge icon url, also add new condition to make it detect that's Concierge.
```javascript
  const {avatar, displayName, login} = props.personalDetails[props.action.actorEmail] || {};
    const avatarUrl = (props.action.automatic || props.action.actorEmail === CONST.EMAIL.CONCIERGE)
        ? CONST.CONCIERGE_ICON_URL
        // Use avatar in personalDetails if we have one then fallback to avatar provided by the action
        : (avatar || props.action.avatar);
```

**Comment by JmillsExpensify** [comment] 2022-11-29 04:12
I can reproduce the issue, though building on what @hungvu193 post above, what's interesting is that as soon as you mouse over any message, the new avatar is applied. Here's a screenshot for reference. 

![Screenshot 2022-11-28 at 22 11 34](https://user-images.githubusercontent.com/1127863/204436963-d2d18e69-7f5e-4a6e-8feb-896890071263.png)

**Comment by JmillsExpensify** [comment] 2022-11-29 04:17
I'll go ahead and apply the external label, though I'd like to see commentary from @NikkiWines, as she was on the original PR and probably has the best context. Thanks!

**Comment by sobitneupane** [comment] 2022-11-29 06:27
Looks like changes is needed in backend. `api?command=OpenReport` is returning https://d2k5nsl2zxldvw.cloudfront.net/images/icons/concierge_2021.png as avatar in reportActions. 
```
{
	"1": {
		"person": [
			{
				"type": "TEXT",
				"style": "strong",
				"text": "Concierge"
			}
		],
		"actorEmail": "concierge@expensify.com",
		"actorAccountID": 8392101,
		"message": [
			{
				"type": "COMMENT",
				"html": "👋 Welcome to Expensify! I'm Concierge. Is there anything I can help with? Click the + icon on the homescreen to explore the features you can use.",
				"text": "👋 Welcome to Expensify! I'm Concierge. Is there anything I can help with? Click the + icon on the homescreen to explore the features you can use.",
				"isEdited": false
			}
		],
		"originalMessage": {
			"html": "👋 Welcome to Expensify! I'm Concierge. Is there anything I can help with? Click the + icon on the homescreen to explore the features you can use."
		},
		"avatar": "https://d2k5nsl2zxldvw.cloudfront.net/images/icons/concierge_2021.png",
		"created": "2022-09-21 06:12:08.178",
		"timestamp": 1663740728,
		"automatic": false,
		"sequenceNumber": 1,
		"actionName": "ADDCOMMENT",
		"shouldShow": true,
		"clientID": "",
		"reportActionID": "2154625890648324009"
	}
}
```

**Comment by hungvu193** [comment] 2022-11-29 06:56
@sobitneupane yeah I saw that too, I also saw that piece of code I mentioned was there since 18 months ago. Should we keep that or fix this issue from backend?

**Comment by mollfpr** [comment] 2022-11-29 07:40
We mainly use the avatar from `personalDetails`, and the avatar from the report actions as a fallback. The avatar from `personalDetails` is the newest and is set to the `avatarUrl`. I think updating the API response will not resolve this issue.

<img width="643" alt="Screen Shot 2022-11-29 at 14 30 43" src="https://user-images.githubusercontent.com/25520267/204466108-9e374a80-4b67-424a-a06d-7f137ce4b02b.png">

---

The question is:
- Why the `avatarUrl` is changed from `.../concierge_2022.png` to `.../concierge_2021.png` while the avatar from `personalDetails` still has the latest avatar?
- Why does the avatar shows the correct image after hovering the chat message?

<img width="641" alt="Screen Shot 2022-11-29 at 14 32 55" src="https://user-images.githubusercontent.com/25520267/204467555-b7d77813-605a-4fc1-854d-b417514fd22d.png">

**Comment by sobitneupane** [comment] 2022-11-29 08:09
@mollfpr You may have noticed that `avatarHighResolutions` needs to be updated as well.

**Comment by mollfpr** [comment] 2022-11-29 08:14
>@mollfpr You may have noticed that avatarHighResolution needs to be updated as well.

@sobitneupane I couldn't understand what you mean. Could you elaborate more?

**Comment by sobitneupane** [comment] 2022-11-29 09:57
>  Could you elaborate more?

@mollfpr I am just letting you know that avatarHighResolution in personalDetails also contains https://d2k5nsl2zxldvw.cloudfront.net/images/icons/concierge_2021.png which is not expected.

To answer your questions:
> Why the avatarUrl is changed from .../concierge_2022.png to .../concierge_2021.png while the avatar from personalDetails still has the latest avatar?

Resopnse from api?command=OpenApp also contains https://d2k5nsl2zxldvw.cloudfront.net/images/icons/concierge_2021.png as avatar.

<img width="1439" alt="Screenshot 2022-11-29 at 15 05 28" src="https://user-images.githubusercontent.com/25876548/204489581-6db725ac-03eb-46ef-adb4-1b2ab0c641bf.png">

So, when [Onyx] set()  is called for key: personalDetails properties, avatarURL changes to ../concierge_2021.png
<img width="431" alt="Screenshot 2022-11-29 at 15 20 31" src="https://user-images.githubusercontent.com/25876548/204495376-f40048fa-7f0b-4ed8-8666-57b9c4014042.png">

> Why does the avatar shows the correct image after hovering the chat message?

On hovering the chat message, `ReportActionItemSingle` re-renders and gets the correct value from the updated personal Details.

I am not sure when and where `personalDetails` gets updated to have `concierge_2022.png` as avatar, as server is not returning it. I guess somewhere in the frontend `CONST.CONCIERGE_ICON_URL` is used to update personalDetails in onyx.

**Comment by mollfpr** [comment] 2022-11-29 10:09
Thanks! Yeah, I just find out too about the response from `api?command=OpenApp`. Since we already implement `CONST.CONCIERGE_ICON_URL` to update the concierge avatar, we could fix this issue in the App.

Any thoughts @yuwenmemon @JmillsExpensify?

**Comment by JalalMitali** [comment] 2022-11-29 12:51
Hello 👋 I still have the old concierge icon even on main chats page ( iOS simulator )

**Comment by mollfpr** [comment] 2022-11-29 16:26
@hungvu193 Your [proposal](https://github.com/Expensify/App/issues/13110#issuecomment-1330031545) did fix the issue, but I am more inclined to fix why `ReportActionItemSingle` didn't show the latest concierge `personalDetails`.

<img width="1426" alt="Screen Shot 2022-11-29 at 23 25 56" src="https://user-images.githubusercontent.com/25520267/204585771-fa5a1017-f691-464f-8536-36543c839868.png">

**Comment by hungvu193** [comment] 2022-11-29 16:58
@mollfpr damn, I found a very funny bug in this line:
```javascript
const {avatar, displayName, login} = props.personalDetails[props.action.actorEmail] || {};
```
The values of `props.personalDetails[props.action.actorEmail]` has `avatar`: https://d2k5nsl2zxldvw.cloudfront.net/images/icons/concierge_2022.png
But when I tried to console.log the `avatar` value from destructuring it returned: https://d2k5nsl2zxldvw.cloudfront.net/images/icons/concierge_2021.png

<img width="510" alt="Screen Shot 2022-11-29 at 23 57 19" src="https://user-images.githubusercontent.com/16502320/204593351-80a35f60-0379-4799-9770-e50d984dca73.png">

**Comment by mollfpr** [comment] 2022-11-29 17:01
@hungvu193 Yup, that makes me confuse at first 🤣

**Comment by hungvu193** [comment] 2022-11-29 17:02
@mollfpr but look at the preview, the avatar is 2021, so now I'm confused with myself :|
<img width="502" alt="Screen Shot 2022-11-30 at 00 02 26" src="https://user-images.githubusercontent.com/16502320/204594442-f4222d34-b9dd-44f7-889f-ef8077a3a47b.png">

**Comment by JmillsExpensify** [comment] 2022-11-29 17:08
I saw the same thing for hover [in this comment](https://github.com/Expensify/App/issues/13110#issuecomment-1330052097).

**Comment by hungvu193** [comment] 2022-11-29 17:21
Yeah.
But again the issue here's the way` avatarUrl`'s calculated:
```javascript
    const avatarUrl = props.action.automatic
        ? `${CONST.CLOUDFRONT_URL}/images/icons/concierge_2019.svg`

        // Use avatar in personalDetails if we have one then fallback to avatar provided by the action
        : (avatar || props.action.avatar);
```
<img width="510" alt="Screen Shot 2022-11-30 at 00 18 09" src="https://user-images.githubusercontent.com/16502320/204597909-8ab850fa-1c3d-4137-a12e-3fd76c0a1ada.png">

`props.action.automatic` is false even with Concierge message, so the condition always return `(avatar || props.action.avatar)`, so if we fix the condition, we don't need to care about the weird rendering.

**Comment by NikkiWines** [comment] 2022-11-30 03:31
Oops, yep definitely missed this when updating the avatar. 

Some potentially helpful context: concierge@expensify.com will have the old (2021) avatar in the `personalDetails` because we want to maintain the old avatar for www.expensify.com. There are a lot more places to update the avatar on that site, it was simplest to maintain the old avatar in the personalDetails and overwrite it only for new.expensify.com.

**Comment by JmillsExpensify** [comment] 2022-11-30 03:40
Super helpful. Curious for your take: Should we keep this external given the theories above, or should we include this as part of PR polish and take internal?

**Comment by yuwenmemon** [comment] 2022-11-30 15:08
I think @hungvu193's proposal would be _fine_ based on what @NikkiWines is saying.

However, I'm also noticing that since we grab Personal Details on App Init, we do indeed have "App-only" logic in PHP that's sending over the personal details and could probably replace the avatar there. @NikkiWines what do you think?

**Comment by NikkiWines** [comment] 2022-11-30 19:56
Nice, yeah that sounds great to me @yuwenmemon 👍

**Comment by yuwenmemon** [comment] 2022-11-30 20:35
All right, assigning myself and taking this internal then.

**Comment by JmillsExpensify** [comment] 2022-12-01 05:40
Because the issue requires updating the API, this issue is internal and requires access to a private repo. Removed the bounty from the title and closed out the Upwork job as well.

**Comment by JmillsExpensify** [comment] 2022-12-05 14:01
Linked PR is merged and internal, so once that hits production, this issue should close out automatically.

**Comment by yuwenmemon** [comment] 2022-12-09 21:33
Oh, since this was cross repo it didn't close out when it got deployed to prod. Closing this out now! This has been on prod for a few days

**Comment by hungvu193** [comment] 2022-12-10 04:17
Is it deployed to new.expensify.com? I'm still able to reproduce it

**Comment by mollfpr** [comment] 2022-12-10 10:09
@yuwenmemon @JmillsExpensify The issue is still there on staging and production.

**Comment by yuwenmemon** [comment] 2022-12-12 17:40
Interesting, will take a look!

**Comment by mollfpr** [comment] 2022-12-13 15:55
@yuwenmemon 

The response from API is still using the old concierge image avatar.

<img width="654" alt="Screen Shot 2022-12-13 at 22 54 34" src="https://user-images.githubusercontent.com/25520267/207381114-b9e47a2d-e3c6-4490-8ed9-4b699d0f26df.png">

**Comment by yuwenmemon** [comment] 2022-12-13 19:22
@mollfpr Yes I have an internal PR open!

**Comment by JmillsExpensify** [comment] 2022-12-19 01:50
Circling back on this issue when I return on Tuesday.

**Comment by yuwenmemon** [comment] 2022-12-21 16:18
The associated internal PR has been deployed to prod: https://github.com/Expensify/Web-Expensify/pull/35814

Closing!

**Comment by hungvu193** [comment] 2022-12-22 02:26
I'm not sure if this is deployed to staging, still can reproduce it!
<img width="1680" alt="Screen Shot 2022-12-22 at 09 25 39" src="https://user-images.githubusercontent.com/16502320/209041621-358fed14-7d41-461a-ba33-e24fa467a65c.png">
Version: v1.2.43-1

**Comment by mollfpr** [comment] 2022-12-22 05:06
Also reproducible on production `v1.2.42-2` Web. I can't reproduce it on mWeb iOS Chrome.


https://user-images.githubusercontent.com/25520267/209061029-0bf43fa9-f196-42d5-ac46-76bef5d487f8.mov

**Comment by hungvu193** [comment] 2022-12-22 06:38
I still can reproduce on IOS![image](https://user-images.githubusercontent.com/16502320/209072758-03177838-be07-4754-8109-c5f382b0ce03.png)

**Comment by yuwenmemon** [comment] 2022-12-22 17:41
Hmmm... Curious. I guess there's somewhere else in the API where the old Avatar is getting sent from.

**Comment by yuwenmemon** [comment] 2022-12-22 17:47
@hungvu193 I updated that lone remaining Avatar in the PR above but that's not going to fix the issue since we're not dealing with an `automatic: true` action with that opening `👋 Hey there, I'm Concierge!` message.

**Comment by hungvu193** [comment] 2022-12-23 00:00
> <b>Proposal</b>
> 
> Inside ReportActionItemSingle, I notice that we are still using the old Concierge icon image url so that's why this issue happened
> 
> <img width="938" alt="Screen Shot 2022-11-29 at 10 34 49" src="https://user-images.githubusercontent.com/16502320/204432393-d0037d40-55d1-4cf1-9896-bc9073c24104.png">
> 
> <b>Solution </b>
> 
> We need to update the icon url to new Concierge icon url, also add new condition to make it detect that's Concierge.
> 
> ```diff
> 
> -    const avatarUrl = props.action.automatic
> 
> -       ? `${CONST.CLOUDFRONT_URL}/images/icons/concierge_2019.svg`
> 
> -
> 
> -        // Use avatar in personalDetails if we have one then fallback to avatar provided by the action
> 
> -       : (avatar || props.action.avatar);
> 
> +    const avatarUrl = (props.action.automatic || props.action.actorEmail === CONST.EMAIL.CONCIERGE)
> 
> +        ? CONST.CONCIERGE_ICON_URL
> 
> +       // Use avatar in personalDetails if we have one then fallback to avatar provided by the action
> 
> +       : (avatar || props.action.avatar);
> 
> ```
> 
> I wonder why we need the `props.action.automatic`, can we remove it too? I checked the log and see even with Concierge, the `props.action.automatic` is still `false`.
> 
> 
> 
> 
> 
> 
> 
> https://user-images.githubusercontent.com/16502320/204432846-cf9c9a57-aa83-4a10-b404-a709d6d6e093.mov
> 
> 
> 
> 

@yuwenmemon Yeah because in most cases, prop.automatic is always false, let update as my proposal here with a check when email is Concierge

**Comment by mollfpr** [comment] 2022-12-23 01:42
@yuwenmemon are we `External` this issue?

**Comment by JmillsExpensify** [comment] 2022-12-23 16:49
Good question. If we are, then we would need to create another issue. I'll leave the decision to @yuwenmemon though.

**Comment by JmillsExpensify** [comment] 2022-12-27 19:45
@yuwenmemon is OOO this week, so I'm removing the daily and we can align on next steps when he returns.

**Comment by yuwenmemon** [comment] 2023-01-03 18:57
I'm back! @hungvu193 I see what you're saying. My one concern is that this would be a "band-aid" fix that masks the true reason why we're seeing the old icon in the first place.

**Comment by hungvu193** [comment] 2023-01-04 03:43
@yuwenmemon the root cause is that the `api?command=OpenReport` is still returning the 2021 icon.
So I think the decision is yours, we can keep up with the front end check that we already have or we will fix this in the backend 😄 
<img width="966" alt="Screen Shot 2023-01-04 at 10 41 27" src="https://user-images.githubusercontent.com/16502320/210480435-4c3dc480-0c70-4fd7-94a5-d7b084cd4adf.png">

**Comment by JmillsExpensify** [comment] 2023-01-11 05:30
Looks like this issue will re-close again once the Web PR hits production. That should happen tomorrow.

**Comment by JmillsExpensify** [comment] 2023-01-17 05:16
Closing as the linked PR has hit production.

**Closed by JmillsExpensify** 2023-01-17 05:16 UTC
Labels: Reviewing, Weekly, Internal, Bug
