### ISSUE TITLE
[$500] Android- Attachment - Image clicked from Whatsapp zoomed too much in preview

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#26086] opened 2023-08-28 14:17 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Click and send a image to any user in Whatsapp
2. Open any report
3. Send image clicked from Whatsapp as attachment
4. Observe the how much is the image zoomed

## Expected Result:
The image preview should be displayed properly.

## Actual Result:
The image preview is zoomed too much.

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [ ] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 1.3.57.5
**Reproducible in staging?:** n/a
**Reproducible in production?:** n/a
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/93399543/1d3fb95e-c5be-422c-920b-8f4bdb36af7d

**Expensify/Expensify Issue URL:**
**Issue reported by:** krishna2323
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1692464365619889

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~0170c628d9805f4ad5</li>
        <li>Upwork Job ID: 1701870392946663424</li>
        <li>Last Price Increase: 2023-09-20</li>
    </ul>
</details>

**Comment by JmillsExpensify** [comment] 2023-09-07 02:05
Hmm, I agree that we should treat copied images, and just as importantly, we should show cropped images equivalently. Though for clarity, is this only the case for WhatsApp images or can you reproduce more generally. If WhatsApp only, I don't think that counts as a bug, as it's just one app (sure a very popular one). If this is possible more generally for all images, I think we should address

**Comment by situchan** [comment] 2023-09-25 10:33
I don't like altering `resizeMode` prop which will cause regression.

I think this is still awaiting proposals

**Comment by situchan** [comment] 2023-10-10 22:02
Still awaiting proposals

**Comment by JmillsExpensify** [comment] 2023-10-16 17:40
Review awaiting proposal.

**Comment by miljakljajic** [comment] 2023-10-19 12:31
@situchan give the updated comment a review when you have the chance!

**Comment by situchan** [comment] 2023-10-24 06:50
@Krishna2323 there's no state change in `resizeMode` prop. It's always fixed as "cover"
We should fix the real root cause. As width and height are correctly set, "cover" should look same as "contain".
So let's try to fix without altering `resizeMode` prop value.
React Image already works fine. So issue is definitely in react-native-fast-image repo.
Ideal solution would be to fix upstream. If not possible, we can at least apply patch.

**Comment by JmillsExpensify** [comment] 2023-10-24 18:08
So what's the take-away here. I think after the above discussion, I'm inclined to close the issue.

**Comment by situchan** [comment] 2023-10-25 08:13
yes, I think this is worth of fixing. Kind of bad user experience.

**Comment by situchan** [comment] 2023-10-25 08:14
@Krishna2323 please share demo video. It's flickering for me.

**Comment by situchan** [comment] 2023-10-25 08:16
Adding key prop is workaround. If the root cause is in "no re-render", we should fix that ideally.
As you can test, it doesn't happen when width/height are set manually (when size is already determined before render)

**Comment by situchan** [comment] 2023-10-25 08:21
@Krishna2323 I didn't mean to set size manually as a solution. It's just for you to test.

**Comment by situchan** [comment] 2023-10-25 12:28
@Krishna2323 can you share code diff you tested with?

**Comment by situchan** [comment] 2023-10-29 16:25
@Krishna2323 tested. That works but still workaround.
Can you try to fix upstream? We can apply more patch [here](https://github.com/Expensify/App/blob/main/patches/react-native-fast-image%2B8.6.3.patch) if needed.

**Comment by JmillsExpensify** [comment] 2023-11-01 15:25
Still working through the potential solution.

**Comment by situchan** [comment] 2023-11-07 08:52
@Krishna2323 what do you need? As I said, it happens on all images


https://github.com/Expensify/App/assets/108292595/61b9291e-02bc-4baa-9fe8-0357a6338a66

**Comment by situchan** [comment] 2023-11-14 15:24
still looking for ideal solution

**Comment by situchan** [comment] 2023-11-22 12:59
Expert agency might help this issue

**Comment by JmillsExpensify** [comment] 2023-11-24 17:08
Do we know which agency is interested in picking this up?

**Comment by situchan** [comment] 2023-11-28 13:01
Maybe callstack

**Comment by situchan** [comment] 2023-11-28 14:34
If it's old RN issue, I was fine to apply workaround. But this obviously came from react-native-fast-image

**Comment by JmillsExpensify** [comment] 2023-12-06 04:44
Still discussing

**Comment by JmillsExpensify** [comment] 2023-12-13 05:13
Same

**Comment by JmillsExpensify** [comment] 2023-12-27 23:38
Same

**Comment by situchan** [comment] 2024-01-06 21:10
@Krishna2323 we're no longer using react-native-fast-image but expo-image

**Comment by situchan** [comment] 2024-01-18 11:31
@Krishna2323 did you check already?

**Comment by situchan** [comment] 2024-01-18 13:39
ok so it's 100% issue from react-native-fast-image package.

@JmillsExpensify let's close

**Closed** 2024-01-31 03:27 UTC
Labels: Engineering, Weekly, Internal, Overdue, Bug
