### ISSUE TITLE
[HOLD for 41962] [$250] Expense - Unable to load previous expenses with error after deleting invalid distance request

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#42942] opened 2024-05-31 17:26 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.78-0
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**If this was caught during regression testing, add the test name, ID and link from TestRail:** https://expensify.testrail.io/index.php?/tests/view/4581396
**Issue reported by:** Applause - Internal Team

## Action Performed:
1. Go to staging.new.expensify.com
2. Go to workspace chat that has more than one request
3. Go offline
4. Create a distance expense consisting of invalid waypoints (add random characters as waypoints)
5. Go online
6. Go to transaction thread of the invalid distance request
7. Click 3-dot menu > Delete
8. Delete the expense
9. When redirected to expense report, refresh the page

## Expected Result:
The previous expenses in the report will show up without issue

## Actual Result:
The expense report shows skeleton preview. There is an error saying "There was an error loading more messages.". Clicking Try again button does not show the previous expenses

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [x] Android: mWeb Chrome
- [x] iOS: Native
- [x] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details> 

https://github.com/Expensify/App/assets/78819774/b0594140-c810-4f3e-b641-36a6e0aee8ad

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01ffa5d3b0fde1f87e</li>
        <li>Upwork Job ID: 1796604729456631808</li>
        <li>Last Price Increase: 2024-06-21</li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @mananjadhav</details>

**Comment by lanitochka17** [comment] 2024-05-31 17:27
@isabelastisser  FYI I haven't added the External label as I wasn't 100% sure about this issue. Please take a look and add the label if you agree it's a bug and can be handled by external contributors

**Comment by isabelastisser** [comment] 2024-05-31 18:08
I can reproduce this.

**Comment by badeggg** [comment] 2024-06-01 03:18
Hi, maybe this is a stupid question. But why my app has no 'distance' option, did I miss something?
<img width="924" alt="image" src="https://github.com/Expensify/App/assets/10908996/9b72c51c-e077-47f5-8aa6-8a536ca39e37">

**Comment by 4c656f** [comment] 2024-06-01 15:15
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
The expense report shows skeleton preview. There is an error saying "There was an error loading more messages.". Clicking Try again button does not show the previous expenses

### What is the root cause of that problem?
The issue is caused by a deleted distance request, which breaks the continuity of the reports in:

https://github.com/Expensify/App/blob/0cb2dc052f01b6a024ac872ad8bf628159fe7873/src/libs/ReportActionsUtils.ts#L361-L364
 This is due to the deleted report not having a previousReportActionID and appearing first in the list.
https://github.com/Expensify/App/blob/0cb2dc052f01b6a024ac872ad8bf628159fe7873/src/libs/ReportActionsUtils.ts#L693
deleted report is not filtered out because shouldIncludeInvisibleActions set to true in https://github.com/Expensify/App/blob/0cb2dc052f01b6a024ac872ad8bf628159fe7873/src/pages/home/ReportScreen.tsx#L742
### What changes do you think we should make in order to solve the problem?
change shouldIncludeInvisibleActions to false in https://github.com/Expensify/App/blob/0cb2dc052f01b6a024ac872ad8bf628159fe7873/src/pages/home/ReportScreen.tsx#L742

**Comment by 4c656f** [comment] 2024-06-01 15:20
Contributor details
Your Expensify account email: tarabrinleonid@gmail.com
Upwork Profile Link: https://www.upwork.com/freelancers/~01a75dd8e0067c3e4a

**Comment by isabelastisser** [comment] 2024-06-04 03:18
@mananjadhav, what are the next steps here? Can you please review the proposal above? Thanks!

**Comment by mananjadhav** [comment] 2024-06-04 03:45
I'll check the issue and the proposal today.

**Comment by mananjadhav** [comment] 2024-06-04 13:49
@4c656f the `shouldIncludeInvisibleActions` has several other checks and not just deleted. Don't you think it'll have an impact on the other listings?

**Comment by isabelastisser** [comment] 2024-06-07 17:16
Any updates @mananjadhav ?

**Comment by mananjadhav** [comment] 2024-06-07 17:33
Still waiting for proposals. The earlier proposal might cause regressions.

**Comment by isabelastisser** [comment] 2024-06-10 18:38
Not overdue.

https://github.com/Expensify/App/issues/42942#issuecomment-2155251684

**Comment by isabelastisser** [comment] 2024-06-13 00:27
@mananjadhav, do you have any ideas on how to move this forward?

**Comment by isabelastisser** [comment] 2024-06-14 16:43
@mananjadhav bump on my comment above.

**Comment by isabelastisser** [comment] 2024-06-17 14:35
@mananjadhav bump on my comment above: https://github.com/Expensify/App/issues/42942#issuecomment-2159048113

I will also DM you for visibility.

**Comment by mananjadhav** [comment] 2024-06-17 14:46
@isabelastisser can we bump the price or ask if any agency member is available to pick this ?

**Comment by isabelastisser** [comment] 2024-06-17 16:12
@mananjadhav I posted this here: https://expensify.slack.com/archives/C01GTK53T8Q/p1718640722815069

**Comment by jacobkim9881** [comment] 2024-06-17 17:10
This can be solved by [this PR](https://github.com/Expensify/App/pull/41962) as the issue occurred for breaking continuity of report actions. Though continuity is broken, skeleton loading or the error message doesn't occurred in the PR.

**Comment by isabelastisser** [comment] 2024-06-18 14:14
@mananjadhav @jacobkim9881, can you please clarify? Does this mean that this already created[ PR ](https://github.com/Expensify/App/pull/41962)will solve the issue report here? Can this issue be closed? Thanks!

**Comment by jacobkim9881** [comment] 2024-06-18 15:17
@mananjadhav  @isabelastisser The skeleton preview of the issue has occurred on several issues. It's for [infinite GetOlderActions calls](https://github.com/Expensify/App/issues/41254) caused by shorted array from `getContinuousReportActionChain`. In `getContinuousReportActionChain` report actions are shorted for losing some by sorting one by one, which causes repeating loading older chats. In the issue deleted request could be lost. 

[From the PR](https://github.com/Expensify/App/pull/41962) new function `getContinuousChain` will replace `getContinuousReportActionChain`.

**Comment by isabelastisser** [comment] 2024-06-20 20:16
@mananjadhav can you please follow up on the comment above? Thanks!

**Comment by mananjadhav** [comment] 2024-06-21 12:41
I am not 100% if it will be resolved with the linked PR. I think we should keep this open and wait for proposals.

**Comment by isabelastisser** [comment] 2024-07-12 17:43
@mananjadhav, are we still holding this?

**Comment by isabelastisser** [comment] 2024-07-15 17:45
Bump @mananjadhav

**Comment by mananjadhav** [comment] 2024-07-16 22:07
@isabelastisser I tested this a few times and I couldn't reproduce the original issue.

https://github.com/user-attachments/assets/bea2632f-48f2-4128-bbfe-7dc0e1da504d

@lanitochka17 Can you please retest this on staging?

**Comment by isabelastisser** [comment] 2024-07-18 18:25
@lanitochka17, can you please retest this? Thanks!

**Comment by lanitochka17** [comment] 2024-07-20 13:14
Issue is not reproducible on the latest build 9.0.10-2

https://github.com/user-attachments/assets/b0381801-9910-4656-b1a4-471d2ef43d46

**Comment by isabelastisser** [comment] 2024-07-29 14:06
Thanks, @lanitochka17! Closing this.

**Closed by isabelastisser** 2024-07-29 14:06 UTC
Labels: External, Weekly, Help Wanted, Bug
