### ISSUE TITLE
[$1000] Deleting thread replies showing thread title for a while

### ISSUE THREAD

**Issue by kavimuru** [Expensify/App#19352] opened 2023-05-20 19:22 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:

1. Open a chat
2. Send a message to the user
3. Clicked on "Reply in thread" and reply 2,3 on the thread
4. Edit Thread title/message
5. Now delete the last thread reply one by one

## Expected Result:
Deleting thread replies message should not displayed thread title for a while
## Actual Result:
Deleting thread replies showing thread title for a while
## Workaround:
Can the user still use Expensify without this being fixed? Have you informed them of the workaround?

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [x] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 1.3.16.5
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/43996225/4c858c64-9518-44d3-b27f-f6e21c02c741

https://github.com/Expensify/App/assets/43996225/ea3ed220-04c9-49a5-bb47-c09ccb9d1c31

**Expensify/Expensify Issue URL:**
**Issue reported by:** @ayazhussain79 
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1684358266982189

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~0134fe88a3ecfbf83e</li>
        <li>Upwork Job ID: 1661107080114233344</li>
        <li>Last Price Increase: 2023-06-06</li>
    </ul>
</details>

**Comment by miljakljajic** [comment] 2023-05-23 08:36
I am OOO so I will re-assign this

**Comment by miljakljajic** [comment] 2023-05-23 08:37
Apologies for the delay in reviewing, I've been at EC3.

**Comment by strepanier03** [comment] 2023-05-24 23:47
@techievivek and @0xmiroslav - Can you both check these other GH and see if you agree that all three GHs have the same root cause?

If they have the same root cause then should we merge these three into one GH? 

@allroundexperts has posted a proposal that solves all three in one.

Context [here](https://expensify.slack.com/archives/C01SKUP7QR0/p1684782807958219) for Vivek.

**Comment by abekkala** [comment] 2023-05-26 19:41
@techievivek and @0xmiroslav just a friendly bump in regards to Sheena's message above! 

Can you address that please?

**Comment by techievivek** [comment] 2023-05-29 11:19
Sorry for the delay in reviewing(I was ooo in the last few days), the root cause for both issues appears to be similar and happens only when the thread title gets updated( if we look at the above proposal @allroundexperts has mentioned that this happens only when we first update the thread report title and then make changes to the thread messages). And the fix for both issues also seems to be similar so I suggest we merge this with the other issue.

**Comment by techievivek** [comment] 2023-06-01 05:59
Not overdue. @strepanier03 @abekkala I have shared my thoughts above in the comment, and I think we should just merge all the issue into one.

**Comment by abekkala** [comment] 2023-06-04 18:48
Yeah, let's get these merged. 
@strepanier03 you mentioned 

> should we merge these three into one GH?

But only listed two: this one (https://github.com/Expensify/App/issues/19352)  and then yours #https://github.com/Expensify/App/issues/19348

Is there another one? Should we just use the first one created for moving forward?

**Comment by abdulrahuman5196** [comment] 2023-06-05 08:05
@abekkala  I think we can use https://github.com/Expensify/App/issues/19348 (I think its the first one). We also completed C+ review there - https://github.com/Expensify/App/issues/19348

**Comment by abekkala** [comment] 2023-06-06 11:46
Yes, that one is the first one so we can use that one moving forward.

**Comment by Beamanator** [comment] 2023-06-06 20:36
I hired @allroundexperts in https://github.com/Expensify/App/issues/19348, so I think we can go ahead and close this one out

**Closed** 2023-06-07 13:09 UTC
Labels: External, Daily, Help Wanted, Bug
