### ISSUE TITLE
[HOLD for payment 2023-09-07] [$250] IOS-Extra margin below save Paypal account button

### ISSUE THREAD

**Issue by m-natarajan** [Expensify/App#26038] opened 2023-08-27 14:54 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. go to Settings > Wallet
2. click on Add payment method button
3. choose PayPal.me
4. check the margin below save Paypal account button
## Expected Result:
margin below should be consistant (margin should be same as Add payment method button)
## Actual Result:
Extra margin below save Paypal account button
## Workaround:
Unknown
## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [x] iOS / native
- [ ] iOS / Safari
- [ ] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 1.3.57-5
**Reproducible in staging?:** Yes
**Reproducible in production?:** Yes
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation

![simulator_screenshot_D06372E0-A7B1-4C5E-A37A-CE658B19E50F](https://github.com/Expensify/App/assets/38435837/b9fef908-dac8-477a-9d7b-33f0e6e49dfc)
![simulator_screenshot_5A7F3437-CEA6-4C03-B614-9D2A3FC71243](https://github.com/Expensify/App/assets/38435837/25890304-d27b-4dd0-910f-d145efc306d9)

https://github.com/Expensify/App/assets/38435837/b7f2b533-3943-467e-9c3f-465133192d24

https://github.com/Expensify/App/assets/38435837/c0417b1c-dcf1-4fae-8e54-98415453a9fc

**Expensify/Expensify Issue URL:**
**Issue reported by:** @gadhiyamanan
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1692436650144409

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01ce109fb6a5b9d89b</li>
        <li>Upwork Job ID: 1696095129923731456</li>
        <li>Last Price Increase: 2023-08-28</li>
<li>Automatic offers: </li>
<ul>
<li>s77rt | Reviewer | 26376347</li>
<li>b4s36t4 | Contributor | 26376349</li>
<li>gadhiyamanan | Reporter | 26376352</li>
</ul></li>
    </ul>
</details>

**Comment by b4s36t4** [comment] 2023-08-27 15:24
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
IOS-Extra margin below save Paypal account button
### What is the root cause of that problem?
The issue is that we have wrapped `AddPayPalMePage` with `ScreenWrapper` which add some bottom padding which is adding extra padding.
### What changes do you think we should make in order to solve the problem?

We need to add `includeSafeAreaPaddingBottom` here in this component https://github.com/Expensify/App/blob/c16995257c738761206ea07645e863ee717ecbc0/src/pages/settings/Wallet/AddPayPalMePage.js#L71 which will solve this issue.
### What alternative solutions did you explore? (Optional)
NA

<img width="454" alt="Screenshot 2023-08-27 at 8 51 24 PM" src="https://github.com/Expensify/App/assets/59088937/1a9ac957-0b8a-42c5-9766-58f1ef86dfa5">

**Comment by s77rt** [comment] 2023-08-28 11:29
@b4s36t4 Thanks for the proposal. Your RCA is correct and the solution looks good.

🎀 👀 🎀 C+ reviewed
[Link to proposal
](https://github.com/Expensify/App/issues/26038#issuecomment-1694695292)

**Comment by s77rt** [comment] 2023-08-28 11:31
@AnshuAgarwal24 This is a bug and not a functional migration issue. A proposal is required here.

**Comment by b4s36t4** [comment] 2023-08-28 14:03
@hoangzinh I'm sorry what I meant is to use `includeSafeAreaPaddingBottom` use this to remove the padding while I forget to have `false` but if you see my screen it is what I meant.

**Comment by stitesExpensify** [comment] 2023-08-28 16:05
@b4s36t4 do you know why this only affects iOS when the file is not platform specific?

**Comment by b4s36t4** [comment] 2023-08-28 16:44
we're using `paddingBottom` from `SafeAreaConsumer` which seems to be returning extra padding only for extra large iOS devices like iOS 14 and those devices.

**Comment by s77rt** [comment] 2023-08-31 16:35
- The PR that introduced the bug has been identified: https://github.com/Expensify/App/pull/23360
- The offending PR has been commented on: https://github.com/Expensify/App/pull/23360#discussion_r1311904843
- A discussion in #expensify-bugs has been started: Not needed. We already have a documented [FORMS.md](https://github.com/Expensify/App/blob/main/contributingGuides/FORMS.md#safe-area-padding) to prevent this kind of bugs
- Determine if we should create a regression test for this bug: No

**Comment by greg-schroeder** [comment] 2023-09-08 22:35
Processing payments

**Comment by greg-schroeder** [comment] 2023-09-08 23:08
Payments complete, no regression test needed. Closing.

**Closed by greg-schroeder** 2023-09-08 23:08 UTC
Labels: External, Weekly, Awaiting Payment, Bug
