### ISSUE TITLE
[$500] Removing very last message from any conversation or any workspace showing  __fake__  into sidebar page - reported by dhairyasenjaliya

### ISSUE THREAD

**Issue by mvtglobally** [Expensify/App#11273] opened 2022-09-26 04:27 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Go to any new workspace/conversation
2. Remove all the messages
3. Go back to Sidebare page (main chat page)
4. Notice you will see weird __fake__ text right below the name

## Expected Result:
Message should be cleared and need to show workspace name or blank

## Actual Result:
Currently after deleting last message from any conversation/workspace its showing weird text showing as  __fake__

## Workaround:
unknown 

## Platform:

Where is this issue occurring?

- Web
- iOS
- Android
- Desktop App
- Mobile Web

**Version Number:** 1.2.3-0
**Reproducible in staging?:** Y 
**Reproducible in production?:** Y
**Email or phone of affected tester (no customers):** 
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation 
<img width="1440" alt="Screenshot 2022-08-31 at 8 16 59 PM" src="https://user-images.githubusercontent.com/43995119/192193744-a60c7ba3-7fcc-4946-9057-11980a1f84ef.png">

https://user-images.githubusercontent.com/43995119/192193745-ef0d5ef2-4d4d-4e61-987e-d9ea58092726.mov

**Expensify/Expensify Issue URL:**   
**Issue reported by:** dhairyasenjaliya
**Slack conversation:** https://expensify.slack.com/archives/C01GTK53T8Q/p1661957756825579

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by kevinksullivan** [comment] 2022-09-27 22:17
https://www.upwork.com/jobs/~01c57edb4e56fb0d60

**Comment by kevinksullivan** [comment] 2022-09-27 22:17
@dhairyasenjaliya please apply for the reporting bonus. Thanks!

**Comment by dhairyasenjaliya** [comment] 2022-09-28 02:57
@kevinksullivan job seems to be private

**Comment by kevinksullivan** [comment] 2022-09-29 14:41
@dhairyasenjaliya should be good now?

**Comment by dhairyasenjaliya** [comment] 2022-09-29 14:47
hm still same error @kevinksullivan

**Comment by kevinksullivan** [comment] 2022-09-29 14:53
What is the error you message receive? I'm not familiar with anyone having an issue here.

**Comment by dhairyasenjaliya** [comment] 2022-09-29 15:02
<img width="746" alt="Screenshot 2022-09-29 at 8 32 20 PM" src="https://user-images.githubusercontent.com/47522946/193067678-a99d51dd-0b0f-4e3f-b8ee-9047e7a9f93c.png">
@kevinksullivan

**Comment by kevinksullivan** [comment] 2022-10-03 15:38
Hm what is your name on upwork? I will try and invite you.

**Comment by kevinksullivan** [comment] 2022-10-03 15:39
Ah apologies @dhairyasenjaliya . It looks like I had the wrong visibility setting. You should be all set now!

**Comment by dhairyasenjaliya** [comment] 2022-10-03 15:41
No issues done now :)  @kevinksullivan

**Comment by kevinksullivan** [comment] 2022-10-10 14:18
Ah I missed the external tag on this, apologies.

**Comment by kevinksullivan** [comment] 2022-10-10 14:39
@thienlnam should we be reopening the previous issue (https://github.com/Expensify/App/issues/8361) to investigate this?

**Comment by thienlnam** [comment] 2022-10-11 02:32
It was closed many months ago, so we can treat this as a new bug at this point.  

cc @MonilBhavsar / @rushatgabhane Let's make sure to have the contributor also add an automated test for this change (if external).  We keep having this regression and can easily prevent it in the future

**Comment by kevinksullivan** [comment] 2022-10-12 16:17
Doubled

**Comment by MonilBhavsar** [comment] 2022-10-17 07:07
I'm also unable to reproduce the issue. For individual chats, it seems to be working fine, but for policy rooms, it displays last sender's email (which I think should default to Workspace name or domain name)

<img width="1792" alt="Screenshot 2022-10-17 at 12 29 40 PM" src="https://user-images.githubusercontent.com/32012005/196110841-54b2cdf4-4c50-4aaf-b348-cf646c90c41b.png">


@mvtglobally can you please check and confirm. Thank you!

**Comment by MonilBhavsar** [comment] 2022-10-27 12:40
@mvtglobally could you please retest and confirm https://github.com/Expensify/App/issues/11273#issuecomment-1280386876

**Comment by MonilBhavsar** [comment] 2022-11-07 12:12
Bumping to daily.
@mvtglobally we need to retest this issue 🙏

**Comment by kevinksullivan** [comment] 2022-11-14 20:38
Also can't reproduce. Paying out @dhairyasenjaliya for reporting and closing this out.

**Closed by kevinksullivan** 2022-11-14 20:38 UTC
Labels: External, Daily, Help Wanted, Overdue, Bug
