### ISSUE TITLE
[$250] iOS- Public room - App crashes when scrolling through #new-expensify-feedback & #exfy-roadmap

### ISSUE THREAD

**Issue by IuliiaHerets** [Expensify/App#48296] opened 2024-08-29 20:28 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 9.0.26.3
**Reproducible in staging?:** Y
**Reproducible in production?:** N 
**If this was caught during regression testing, add the test name, ID and link from TestRail:** https://expensify.testrail.io/index.php?/tests/view/4903900
**Issue reported by:** Applause Internal Team

## Action Performed:
1. Log out of the app
2. Go to the public rooms #new-expensify-feedback or #exfy-roadmap using a deeplink https://staging.new.expensify.com/r/6776919265133947
3. Scroll up to the beginning

## Expected Result:
User is able to scroll through the public room history

## Actual Result:
The app crashes while scrolling

## Workaround:
Unknown

## Platforms:

- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [x] iOS: Native
- [ ] iOS: mWeb Safari
- [ ] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos
[2809_crash.txt](https://github.com/user-attachments/files/16805608/2809_crash.txt)

https://github.com/user-attachments/assets/63c85de7-8c9e-43bb-b65c-b9bf0bebc3bb

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~021833932522517823124</li>
        <li>Upwork Job ID: 1833932522517823124</li>
        <li>Last Price Increase: 2024-09-25</li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @Pujan92</details>

**Comment by robertjchen** [comment] 2024-08-29 21:38
Attempting to reproduce locally 👀

**Comment by robertjchen** [comment] 2024-08-29 23:37
Can anyone else reproduce this? I can't seem to do it in the iOS emulator. 

Command to open via deeplink:
```
xcrun simctl openurl booted "new-expensify:///r/6776919265133947"
```

**Comment by robertjchen** [comment] 2024-09-03 17:56
not reproducible and no other reports

**Comment by IuliiaHerets** [comment] 2024-09-11 18:14
QA team can reproduce this issue in the latest build, build - v9.0.32-3

https://github.com/user-attachments/assets/e9b26b00-a1f3-45f4-ae83-59e3b50c7baf

**Comment by isabelastisser** [comment] 2024-09-13 17:23
Waiting for proposals.

**Comment by Pujan92** [comment] 2024-09-14 14:04
I am not able to reproduce this crash. @IuliiaHerets can you plz confirm one more time plz?

**Comment by IuliiaHerets** [comment] 2024-09-14 17:32
@Pujan92 QA team checking and still can repro the crash, build - 9.0.35

https://github.com/user-attachments/assets/64e35df5-41c1-42d2-a3bb-b18c8af32337

**Comment by isabelastisser** [comment] 2024-09-17 19:10
Waiting for proposals.

**Comment by robertjchen** [comment] 2024-09-26 08:49
Closing this out for now, can't seem to reproduce this issue as well and there haven't been any other bug reports 🤔

**Closed by robertjchen** 2024-09-26 08:49 UTC
Labels: External, Engineering, Weekly, Help Wanted, Bug
