### ISSUE TITLE
[$500] Web - Navigating to Search by keyboard shortcut when the "Update Workspace currency to USD"  Modal is open Does not close the modal

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#27277] opened 2023-09-12 18:09 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Open any workspace in which currency is not default to USD
2. Click Threedot then "Delete Workspace",Confirm Modal will be visible,
3.  Press CMD+K/CMD+SHIFT+K, note here before navigating the Modal closes
4. Click bank account, "Update Workspace currency to USD"  Modal  will be visible.
5. Press CMD+K/CMD+SHIFT+K.

## Expected Result:
Modal should close before navigation.

## Actual Result:
 Modal Remains open and app navigates to search.

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [ ] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 1.3.68.12
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/93399543/f2f2268c-55f4-4c4b-9995-9ffd4896a3e6

https://github.com/Expensify/App/assets/93399543/97aea7fe-055d-4377-b471-5788d2726f7b

**Expensify/Expensify Issue URL:**
**Issue reported by:** @ishpaul777
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1694263008212129

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~0152ef93375eec0d1f</li>
        <li>Upwork Job ID: 1701659303722033152</li>
        <li>Last Price Increase: 2023-09-12</li>
    </ul>
</details>

**Comment by ishpaul777** [comment] 2023-09-12 18:10
## Proposal
### Problem Statement
When user is Navigated to search using keyboard shortcuts, the attachement Modal is not closed and navigation gets broken.

### Root Cause
The root cause is when keyboard shortcut is triggered we call Modal.close(() => callback), here modal.close is dependent on the onClose prop which we pass in Modal component. But in this case we have 2 Modals in stack of  a
### Solution
Conditionally rendering the any of the ConfirmModal in WorkspaceInitialPage would solve the issue

**Comment by situchan** [comment] 2023-09-13 09:40
@tienifr's [proposal](https://github.com/Expensify/App/issues/27277#issuecomment-1717119064) looks good to me.
🎀 👀 🎀 C+ reviewed

**Comment by marcaaron** [comment] 2023-09-13 22:44
Hmm I am really unsure sure about this proposal. It seems like there is something wrong with the implementation of the modal component itself. 

First, why is it overwriting the callback? That seems like a strange hack to me.

@tienifr Can you try to put the problem into your own words now that you've investigated it? I don't think repeating the title of the issue is sufficient. It feels like there is some kind of deeper design flaw related to modals if this bug can easily be introduced again in the future.

**Comment by marcaaron** [comment] 2023-09-13 22:44
@situchan please find a suitable proposal and tag me back in when this is ready for review.

**Comment by marcaaron** [comment] 2023-09-18 05:41
Honestly, it's all kind of unclear. 

>So we can easily realize that we can not face with race condition here

I'm not realizing it. Can you walk us through it? You are describing the different states in the code. But not really describing _why_ it works the way that it does. It particular, I find it strange that we are losing the callback and why `useCallback()` fixes it.

**Comment by situchan** [comment] 2023-09-20 03:33
Not reproducible really. @tienifr do you know which PR fixed this?

**Comment by strepanier03** [comment] 2023-09-21 22:17
We good to close this one out then?

**Comment by situchan** [comment] 2023-09-22 00:12
> We good to close this one out then?

yes

**Comment by strepanier03** [comment] 2023-09-22 19:49
Gotcha, thanks for confirming. Closing now.

**Closed by strepanier03** 2023-09-22 19:49 UTC
Labels: External, Daily, Help Wanted, Bug
