### ISSUE TITLE
[HOLD #23143] Dev: Web  - App crashes when deleting an image while the image is opened

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#23896] opened 2023-07-30 20:34 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Open a tab where user A is signed in
2. Send an image to user B
3. Open a tab where user B is signed in
4. Open the sent image
5. Switch to the tab where user A is signed in
6. Delete the sent image
7. Observe the behavior on the tab where user B is signed

## Expected Result:
 Image preview carousel should close

## Actual Result:
App crashes

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [x] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** Dev 1.3.47-2
**Reproducible in staging?:** no
**Reproducible in production?:** no
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/93399543/d93b2f65-592b-4f5c-b23b-62f1f3d63020

**Expensify/Expensify Issue URL:**
**Issue reported by:** @Natnael-guchima
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1690627861170639

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by ygshbht** [comment] 2023-07-31 08:40
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
The problem is that when an image attachment is deleted by User A while it's opened in the view of User B, the app crashes. This is not the expected behavior. The image preview carousel should close when the image gets deleted.

### What is the root cause of that problem?
The root cause of the problem is that when an attachment is deleted, it becomes a null value. Any subsequent attempts to access its properties such as source or URL results in an error, causing the app to crash.

### What changes do you think we should make in order to solve the problem?
A solution could be to check if the attachment exists before trying to display it or accessing its properties. This can be achieved by adding optional chaining (the question mark syntax) to the attachment variable when accessing its properties. Similarly, for `onCarouselAttachmentChange`, we can add a condition to verify if attachment exists before navigation. The modifications will look like the following:

```
setSource(attachment?.source);
setFile(attachment?.file);
setIsAuthTokenRequired(attachment?.isAuthTokenRequired);
onCarouselAttachmentChange(attachment);
```
```
onCarouselAttachmentChange={(attachment) => {
    if (attachment) {
        const route = ROUTES.getReportAttachmentRoute(reportID, attachment.source);
        Navigation.navigate(route);
    }
}}
```

This will ensure that even if the attachment is null, accessing its properties won't cause the application to crash and the modal will close gracefully.

We can also manually call Navigation.dismissModal to close the modal if the attachment is no longer present or show an error that this attachment has been deleted in the modal iteself

**Comment by ygshbht** [comment] 2023-07-31 09:49
## Proposal

[Edit](https://github.com/Expensify/App/issues/23896#issuecomment-1657925971)

Even though I've already suggested that we should dismiss the modal if the attachment is not present, I would like to further argue that the functionality of `dismissModal `and `onNavigate `is not best placed inside the `createInitialState `function.

https://github.com/Expensify/App/blob/8cdb506e97e8382f4bc55b0f48784f576fbb2789/src/components/AttachmentCarousel/createInitialState.js#L14-L64

A more suitable location would be within the `AttachmentCarousel `that listens for changes in `reportActions `like so:

https://github.com/Expensify/App/blob/8cdb506e97e8382f4bc55b0f48784f576fbb2789/src/components/AttachmentCarousel/index.js#L51-L56

We can modify this to:

```
useEffect(() => {
    const initialState = createInitialState(props);

    if (initialState.page === -1){
       return Navigation.dismissModal();
    }

    props.onNavigate(attachments[page]);

    setPage(initialState.page);
    setAttachments(initialState.attachments);
    // eslint-disable-next-line react-hooks/exhaustive-deps
}, [props.reportActions]);
```

This approach brings several benefits:

1. **Consistency**: Keeping side effects such as navigation or modal display changes out of utility functions like `createInitialState `ensures they remain pure and only depend on their input.

2. **Clarity and Isolation**: Having these side effects in the component's `useEffect `makes the logic easier to follow. All the state changes and side effects are happening in one place, which also simplifies debugging.

<details>
<summary>Original proposal</summary>
<br/>

![image](https://github.com/Expensify/App/assets/65986357/b4d009ea-b5d3-449d-8c28-d1039da230cc)

</details>

**Comment by ahmedGaber93** [comment] 2023-07-31 13:12
This issue is regression from #21334.
And will fix by one of 
- #22261
- #21334

**Comment by puneetlath** [comment] 2023-07-31 19:38
Thanks @ahmedGaber93. I'm going to go ahead and close this issue out then. Appreciate the help in triaging.

**Comment by Natnael-Guchima** [comment] 2023-07-31 20:08
@ahmedGaber93 hmm, this issue is only reproducible on staging. And the[ fixing PR](https://github.com/Expensify/App/pull/23143) you have linked is two weeks old. I am having hard time understanding how the pr you have linked can fix an issue that doesn't exist when it was created unless the pr is amended to do so.

**Comment by Natnael-Guchima** [comment] 2023-08-01 04:17
@puneetlath this issue is a regression of https://github.com/Expensify/App/issues/21334, and is only found on staging and not reproducible on production. The fixing PR @ahmedGaber93 shared is two weeks old pr which is created before this bug was introduced, I am not sure how that pr can fix this issue unless it is amended to do so. I think it is a good idea to keep this issue open and see if a resolution for this issue comes from the offending PR as this comment suggests https://github.com/Expensify/App/issues/22261#issuecomment-1658928502

**Comment by puneetlath** [comment] 2023-08-01 17:29
Cool, I'll leave it open and on hold and we can see if that PR fixes it.

**Comment by Natnael-Guchima** [comment] 2023-08-01 17:51
Thanks for the quick reply Puneet. The issue is fixed and deployed to staging now. Here is the fixing PR https://github.com/Expensify/App/pull/23988

**Comment by puneetlath** [comment] 2023-08-02 17:45
Ok so this issue should just be closed out then, is that right?

**Comment by Natnael-Guchima** [comment] 2023-08-02 17:47
Yes, we can close this👍

**Comment by puneetlath** [comment] 2023-08-02 17:50
Cool, thanks!

**Closed by puneetlath** 2023-08-02 17:50 UTC
Labels: Weekly, Needs Reproduction, Bug
