### ISSUE TITLE
[$1000] Scrolling on Android/Android Mobile Web doesn't have decelerating behavior like on iOS

### ISSUE THREAD

**Issue by jasperhuangg** [Expensify/App#11241] opened 2022-09-23 16:55 UTC
## Action Performed:
1. Navigate to any report or the LHN.
2. Scroll up or down.

## Expected Result:
Scrolling should decelerate when you lift your thumb off the screen.

## Actual Result:
Scrolling stops immediately when you lift your thumb off the screen.

## Workaround:
N/A

## Platform:

Where is this issue occurring?

- Android
- Mobile Web

**Version Number:** v1.2.4-2
**Reproducible in staging?:** Yes
**Reproducible in production?:** Yes
**Email or phone of affected tester (no customers):** 
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation
**Expensify/Expensify Issue URL:** 
**Issue reported by:** @quinthar 
**Slack conversation:** 

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by laurenreidexpensify** [comment] 2022-09-25 18:02
@jasperhuangg co-assigning to you to check link to the regression as above, thanks

**Comment by laurenreidexpensify** [comment] 2022-09-28 07:31
@jasperhuangg bump ^^

**Comment by laurenreidexpensify** [comment] 2022-10-03 12:39
Asked in Slack [here](https://expensify.slack.com/archives/C01GTK53T8Q/p1664795837866269) @mountiny suggested next step is to add Eng label to move forward to External

**Comment by alex-mechler** [comment] 2022-10-03 20:01
Looks good to go to external, might be nice to get a video comparing ios to android though

**Comment by Santhosh-Sellavel** [comment] 2022-10-03 20:08
Due to Limited Availability unassigning this one. Can you reapply the external label to get another C+ assigned thanks!

**Comment by laurenreidexpensify** [comment] 2022-10-04 09:33
https://www.upwork.com/jobs/~01c693f5f951f62330

**Comment by Julesssss** [comment] 2022-10-04 09:38
Awaiting proposals. There's probably a prop of some sort that needs to be flipped, as this is the default behavior for Android scroll views

**Comment by Uros787** [comment] 2022-10-04 23:03
### Proposal

There is a property called decelerationRate which sets the decleration rate of scroll on ios or android. Reading the [Documentation](https://reactnative.dev/docs/scrollview#decelerationrate) we can see that we can set 'normal' | 'fast' | number
My recommendation is that we go with normal, so that way we don't mess with already existing decleration on IOS but just add a decleration on Android

We should add decelerationRate property on FlatList in [LHNOptionsList.js](https://github.com/Expensify/App/blob/main/src/components/LHNOptionsList/LHNOptionsList.js)


On line 89
`<FlatList
                    decelerationRate="normal"`
                    https://github.com/Expensify/App/blob/1a42cf8a48bcb51b7b469f342a3f122de7aaef34/src/components/LHNOptionsList/LHNOptionsList.js#L88

Also in [ReportActionsList.js](https://github.com/Expensify/App/blob/main/src/pages/home/report/ReportActionsList.js)
Line 176
`<InvertedFlatList
                    decelerationRate="normal"`
                    https://github.com/Expensify/App/blob/1a42cf8a48bcb51b7b469f342a3f122de7aaef34/src/pages/home/report/ReportActionsList.js#L175

**Comment by Uros787** [comment] 2022-10-05 06:33
I went to sleep on this proposal I left yesterday, I guess I should've seen that it's normal by default.

Let me propose something like this.
Let's utilize Platform from react native, and write code like this:
`decelerationRate={Platform.OS === 'android' ? 0.998 : 'normal'}`

**Why 0.998?**
That is a default deceleration on iOS, that way we can mimic the deceleration on both platforms

**Comment by Uros787** [comment] 2022-10-05 07:41
@rushatgabhane is there a way for contributors to access slack?

**Comment by Julesssss** [comment] 2022-10-05 10:01
> I don't think we should change the deceleration rate from the default value on Android.

Yeah, I agree 100%. Android's RecyclerView (native version of FlatList) will decelerate by default. Something is preventing this and I'd like to see a solution that addresses this instead of applying a workaround.

**Comment by Julesssss** [comment] 2022-10-14 15:40
@laurenreidexpensify could you please double the bounty. Thanks

**Comment by laurenreidexpensify** [comment] 2022-10-21 16:05
Sorry @Julesssss was OOO and this got lost in the mix. Will double now.

**Comment by Julesssss** [comment] 2022-10-31 10:28
Thanks, we're still awaiting proposals

**Comment by laurenreidexpensify** [comment] 2022-11-01 12:25
price doubled

**Comment by quinthar** [comment] 2022-11-05 00:47
Agreed this seems to have been fixed  I can reproduce either.

**Comment by laurenreidexpensify** [comment] 2022-11-07 12:20
Confirmed on my device - Pixel 4 - issue no longer reproducible. @Julesssss you 👍 to close this?

**Comment by Julesssss** [comment] 2022-11-07 13:04
Yep, thanks all.

**Comment by Julesssss** [comment] 2022-11-07 13:04
@laurenreidexpensify please close the UpWork issue 🙂

**Closed by Julesssss** 2022-11-07 13:04 UTC
Labels: External, Engineering, Weekly, Improvement, Help Wanted, Bug
