### ISSUE TITLE
[$500]  Scan - Chat header is disabled when creating a Scan request with a user with no prior chat

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#29563] opened 2023-10-13 13:18 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.3.83-10

**Reproducible in staging?:** Yes

**Reproducible in production?:** Yes

**If this was caught during regression testing, add the test name, ID and link from TestRail:**

**Email or phone of affected tester (no customers):**

**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Expensify/Expensify Issue URL:**

**Issue reported by:** Applause - Internal Team

**Slack conversation:**

## Action Performed:
1. Go to staging.new.expensify.com
2. Go to + > Request money > Scan > Upload a file
3. Select a user that has no prior chat
4. Complete the Scan request
5. Click on the chat header

## Expected Result:
User is able to click on the chat header

## Actual Result:
User is able to click on the chat header

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] Windows: Chrome 
- [ ] MacOS: Desktop

## Screenshots/Videos
<details>
<summary>Android: Native</summary>

</details>

<details>
<summary>Android: mWeb Chrome</summary>

</details>

<details>
<summary>iOS: Native</summary>

</details>

<details>
<summary>iOS: mWeb Safari</summary>

</details>

<details>
<summary>Windows: Chrome >/summary>

  

https://github.com/Expensify/App/assets/78819774/873023f3-4487-4d8f-8075-113e28deaf5f

</details>

<details>
<summary>MacOS: Desktop</summary>

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01c8cfe24e2dd984c7</li>
        <li>Upwork Job ID: 1715171416379404288</li>
        <li>Last Price Increase: 2023-11-06</li>
    </ul>
</details>

**Comment by s-alves10** [comment] 2023-10-13 13:39
I'm not able to reproduce this issue

**Comment by CortneyOfstad** [comment] 2023-10-16 13:05
I wasn't able to recreate this either — @lanitochka17 can we confirm if the issue is still taking place? Thanks!

**Comment by CortneyOfstad** [comment] 2023-10-18 19:28
Bump @lanitochka17 ^^^

**Comment by CortneyOfstad** [comment] 2023-10-18 20:17
I am heading OoO until Oct. 25, so reassigning BZ to see if they can get this to be recreated, or get confirmation that we can close this 👍

**Comment by mallenexpensify** [comment] 2023-10-18 23:26
Also unable to reproduce via Browserstack, windows, chrome
<img width="575" alt="image" src="https://github.com/Expensify/App/assets/22508304/f4b6ce7f-1fda-4ac6-a1f2-721799ee14a2">


<img width="1110" alt="image" src="https://github.com/Expensify/App/assets/22508304/dbe25b82-f094-43c1-b205-5bbfc899408c">

Can you please try to reproduce @lanitochka17 ?  If you're unable to, will you close plz?

**Comment by lanitochka17** [comment] 2023-10-19 13:02
@mallenexpensify Hello 
Issue is still reproduce with Scan and Manual request on :expensify: account


https://github.com/Expensify/App/assets/78819774/76c54bc1-9fd4-44d9-adbf-dde76f76f186

On Gmail, initially, the header is disabled, but not after a few seconds

https://github.com/Expensify/App/assets/78819774/31a7c6e9-28e6-4970-bcc6-6666170d526f

**Comment by mallenexpensify** [comment] 2023-10-20 01:02
@rushatgabhane do you have a PC to test with? If so, can you please see if you can reproduce? 
I don't have a PC handy. Thx

**Comment by mallenexpensify** [comment] 2023-10-20 22:58
Was able to reproduce, was this
> initially, the header is disabled, but not after a few seconds

So, at least for my instance, there's just a delay. 
@rushatgabhane do you think this can be external?

https://github.com/Expensify/App/assets/22508304/a81c6ed9-0d25-479c-9491-4b8bd5834cb6

**Comment by DylanDylann** [comment] 2023-10-24 01:13
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
Scan - Chat header is disabled when creating a Scan request with a user with no prior chat

### What is the root cause of that problem?
https://github.com/Expensify/App/blob/112061b732fec0273fb619ca53a4fd98496c4615/src/pages/home/HeaderView.js#L204
The App will disable the header if the participant is optimistic data
### What changes do you think we should make in order to solve the problem?
remove this condition
### What is the root cause of that problem?
https://github.com/Expensify/App/blob/112061b732fec0273fb619ca53a4fd98496c4615/src/pages/home/HeaderView.js#L204

### What alternative solutions did you explore? (Optional)

**Comment by CortneyOfstad** [comment] 2023-10-25 19:06
@mallenexpensify I am back from OoO, so I can take this back over — thanks for holding down the fort while I was gone!

**Comment by DylanDylann** [comment] 2023-10-26 04:01
@rushatgabhane I also saw https://github.com/Expensify/App/pull/24091. After applying my solution, I can't reproduce https://github.com/Expensify/App/pull/24091

**Comment by CortneyOfstad** [comment] 2023-11-06 16:37
@rushatgabhane @lanitochka17 any updates here? Thanks!

**Comment by DylanDylann** [comment] 2023-11-06 18:58
@CortneyOfstad Firstly, I think we should confirm what is expected because I see it seems conflict with this PR https://github.com/Expensify/App/pull/23802

**Comment by CortneyOfstad** [comment] 2023-11-09 18:59
Let me check get some internal eyes on this to confirm @DylanDylann — thanks!

**Comment by CortneyOfstad** [comment] 2023-11-09 19:00
@tgolen it appears that the "issue" might be expected behavior based on the comment [here](https://github.com/Expensify/App/issues/29563#issuecomment-1795948758). Can you confirm? TIA!

**Comment by tgolen** [comment] 2023-11-09 22:17
Yeah, that is how I interpret it as well. Sounds like we can close this as `works as expected`.

**Closed by tgolen** 2023-11-09 22:17 UTC
Labels: External, Engineering, Daily, Help Wanted, Bug
