### ISSUE TITLE
[HOLD for payment 2023-09-29] [HOLD for payment 2023-09-27] [$1000] App does not cancel 'Connect online with plaid' request on opening get assistance

### ISSUE THREAD

**Issue by kavimuru** [Expensify/App#23888] opened 2023-07-30 19:05 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Open the app
2. Open settings
3. Open workspaces and open any workspace
4. Open bank account
5. Click on 'Connect online with plaid' and while loading, click on get assistance icon in header
6. Observe that even though user have selected to open new page, app still opens next step of 'Connect online with plaid'
## Expected Result: 
App should cancel 'Connect online with plaid' request if we open another page before it is loaded OR App should disable other buttons when loading for 'Connect online with plaid'
## Actual Result: 
App does not cancel 'Connect online with plaid' request and displays next step even though user have already opened another page

## Workaround:
Can the user still use Expensify without this being fixed? Have you informed them of the workaround?

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [x] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 1.3.47-2
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/43996225/37add4ad-91a3-4356-bcca-521d857bf951

https://github.com/Expensify/App/assets/43996225/5b1a4a07-3e35-442d-8dd5-e3daa0202238

**Expensify/Expensify Issue URL:**
**Issue reported by:** @dhanashree-sawant
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1690625251424159

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~0107644af3ed1e8537</li>
        <li>Upwork Job ID: 1686474836563587072</li>
        <li>Last Price Increase: 2023-08-22</li>
    </ul>
</details>

**Comment by CortneyOfstad** [comment] 2023-07-31 17:05
@kavimuru I wasn't able to recreate this. Can we confirm this issue is still happening?

**Comment by dhanashree-sawant** [comment] 2023-07-31 17:26
Hi @CortneyOfstad, I cross checked and was still able to recreate, can you let me know what you see on clicking get assistance icon after clicking on 'Connect online with Plaid'?

**Comment by CortneyOfstad** [comment] 2023-08-01 20:29
I was able to get this to recreated, so getting eyes on it. Also I'm heading OoO until 8/14 so reassigning BZ to keep an eye on things while I'm out 👍

**Comment by slafortune** [comment] 2023-08-10 21:14
@abdulrahuman5196 do you have thoughts on this proposal?

**Comment by abdulrahuman5196** [comment] 2023-08-13 09:34
@slafortune I think we need to confirm on the expected behaviour before checking on proposals.

Even in the OP it is not clear 

>App should cancel 'Connect online with plaid' request if we open another page before it is loaded OR App should disable other buttons when loading for 'Connect online with plaid'


What do we want to do? Cancel plaid request? Disable help buttons? or do something else?

Could you kindly let us know on the expected behaviour?

**Comment by CortneyOfstad** [comment] 2023-08-14 16:04
@abdulrahuman5196 I'm back from OoO, so stepping in for Stevie here! 

In regards to the Plaid cancellation, it should just revert the request for connecting to plaid and bring it back to the beginning option where they can select that option again. I don't think we need to disable any buttons per se, but just basically have them start over again.

Does that make sense?

**Comment by Pujan92** [comment] 2023-08-16 14:13
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
App does not cancel 'Connect online with plaid' request on opening get assistance

### What is the root cause of that problem?
We are not checking whether the parent component is in the focus or not before redirecting/opening the plaid setup.
https://github.com/Expensify/App/blob/7f13cdd9f5ade3aed50827084aa49b5e3a6496e1/src/components/PlaidLink/index.js#L48

### What changes do you think we should make in order to solve the problem?
As a general solution, I suggest doing the below changes.

1. In the `PlaidLink` component use `withNavigationFocus` for getting the `isFocused` state. Or we can consider using this in the parent component(eg. AddPlaidBankAccount in this scenario) and pass it to `PlaidLink`.

2. Check the `isFocused` prop val for preventing the `open` func call and execute `props.onExit` in `PlaidLink` component.
https://github.com/Expensify/App/blob/7f13cdd9f5ade3aed50827084aa49b5e3a6496e1/src/components/PlaidLink/index.js#L48
```
        if (!props.isFocused) {
            props.onExit();
            return;
        }

        open();
```

<details>
<summary>Result</summary>

https://github.com/Expensify/App/assets/14358475/3b5b4543-4e5a-44a1-a2c6-2e9e931e4b10
</details>

**Comment by kosmydel** [comment] 2023-08-18 13:50
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
When we press the assistance button while connecting with Plaid, we are still redirected to Plaid.

### What is the root cause of that problem?
`PlaidLink` continue to work in the background, despite the fact it is not focused anymore. We should unmount it / navigate back when the user enters the assistance page.

### What changes do you think we should make in order to solve the problem?
When the `AddPlaidBankAccount` loses focus **and** if the _Plaid_ is still loading, we should call the `onExitPlaid()` function to navigate back.

In the [`AddPlaidBankAccount`](https://github.com/Expensify/App/blob/3b2f852fdae21cf034c7ca559a612aefa10f52a8/src/components/AddPlaidBankAccount.js) file we should add something like this:
```javascript
useFocusEffect(
    useCallback(() =>
        () => {
            if (plaidBankAccounts.length)  {
                return;
            }
            // It will be called only when the component loses focus AND still is in the loading screen.
            onExitPlaid();
        }
    , []),
);
```


### What alternative solutions did you explore? (Optional)
We can hide the assistance button when we are loading Plaid.
Going to update you with more details soon...

**Comment by CortneyOfstad** [comment] 2023-08-18 14:00
@abdulrahuman5196 any thoughts on the proposal's above?

**Comment by CortneyOfstad** [comment] 2023-08-21 13:36
Bump @abdulrahuman5196 ^^^

**Comment by abdulrahuman5196** [comment] 2023-08-28 09:47
REviewing now

**Comment by abdulrahuman5196** [comment] 2023-08-28 09:49
>In regards to the Plaid cancellation, it should just revert the request for connecting to plaid and bring it back to the beginning option where they can select that option again. I don't think we need to disable any buttons per se, but just basically have them start over again.

@CortneyOfstad I am assuming this means, when they press assistance button, plaid request should stop in background.

**Comment by abdulrahuman5196** [comment] 2023-08-28 14:03
@ginsuma 's proposal here
The component has changed to functional component, can you update your proposal accordingly? And I am not sure if its best to exit the plaid in componentDidUpdate. But I am not sure on this, Will check again on updated proposal

**Comment by abdulrahuman5196** [comment] 2023-08-28 14:03
@Tony-MK 's proposal here https://github.com/Expensify/App/issues/23888#issuecomment-1667508745 there isn't much information on how they would achieve the functionality mentioned.

**Comment by abdulrahuman5196** [comment] 2023-08-28 14:04
@Pujan92 's proposal here https://github.com/Expensify/App/issues/23888#issuecomment-1680698803. It only works for web(index.js). Can you update the solution involving native as well?

**Comment by kosmydel** [comment] 2023-08-28 14:14
> @kosmydel On the proposal here [#23888 (comment)](https://github.com/Expensify/App/issues/23888#issuecomment-1683951403)
> 
> > // It will be called only when the component loses focus AND still is in the loading screen.
> 
> I think this is one of the implementation details required to approve the proposal. Can you add the information on the same in your proposal?

I've added an explanation for that in [my proposal](https://github.com/Expensify/App/issues/23888#issuecomment-1683951403).

In short, if the _Plaid_ hasn't returned the `plaidBankAccounts` list yet, we can assume it is still loading.

**Comment by Pujan92** [comment] 2023-08-28 14:19
> @Pujan92 's proposal here [#23888 (comment)](https://github.com/Expensify/App/issues/23888#issuecomment-1680698803). It only works for web(index.js). Can you update the solution involving native as well?

@abdulrahuman5196 [updated](https://github.com/Expensify/App/issues/23888#issuecomment-1680698803)

**Comment by CortneyOfstad** [comment] 2023-08-31 13:44
@abdulrahuman5196 some of the proposals have been updated above for your review ^^^

**Comment by abdulrahuman5196** [comment] 2023-09-04 16:37
@ginsuma 's proposal here https://github.com/Expensify/App/issues/23888#issuecomment-1657243651 looks good and works well. All other proposals here are similar in nature.

🎀 👀 🎀
C+ Reviewed

**Comment by tylerkaraszewski** [comment] 2023-09-05 16:03
Looks fine to me.

**Comment by CortneyOfstad** [comment] 2023-09-08 13:48
Bump @tylerkaraszewski and @abdulrahuman5196 on the above ^^^ TIA!

**Comment by abdulrahuman5196** [comment] 2023-09-29 07:27
>The PR that introduced the bug has been identified. Link to the PR:
The offending PR has been commented on, pointing out the bug it caused and why, so the author and reviewers can learn from the mistake. Link to comment:
A discussion in #expensify-bugs has been started about whether any other steps should be taken (e.g. updating the PR review checklist) in order to catch this type of bug sooner. Link to discussion:

Not a regression.

>Determine if we should create a regression test for this bug.

Yes.

>If we decide to create a regression test for the bug, please propose the regression test steps to ensure the same bug will not reach production again.


1) Open the app
2) Open settings
3) Open workspaces and open any workspace
4) Open bank account
5) Click on 'Connect online with plaid' and while loading, click on get assistance icon in header.
6) Verify that the app doesn't open the next step of 'Connect online with plaid'.


@CortneyOfstad

**Comment by CortneyOfstad** [comment] 2023-09-29 12:51
Thanks @abdulrahuman5196! Creating the regression test now and will get these paid!

**Comment by CortneyOfstad** [comment] 2023-09-29 13:37
So the payment breakdown looks to be:

@ginsuma (as the contributor) — $1000
@abdulrahuman5196 (as C+) — $1000
@dhanashree-sawant (as reporter) — $250

I couldn't see if this qualified for the 50% bonus — can you confirm @tylerkaraszewski?

**Comment by CortneyOfstad** [comment] 2023-10-03 14:07
@tylerkaraszewski bump on the payment question [here](https://github.com/Expensify/App/issues/23888#issuecomment-1740911560) — TIA!

**Comment by CortneyOfstad** [comment] 2023-10-03 20:48
Thank you @aimane-chnaif! Handling the payment now!

**Comment by CortneyOfstad** [comment] 2023-10-03 20:56
@dhanashree-sawant sent you a proposal in Upwork!

@ginsuma and @abdulrahuman5196 — do you both get paid in Upwork or NewDot?

**Comment by abdulrahuman5196** [comment] 2023-10-04 00:55
@CortneyOfstad with upwork.

**Comment by dhanashree-sawant** [comment] 2023-10-04 04:18
Thanks @CortneyOfstad, I have acccepted the offer.

**Comment by CortneyOfstad** [comment] 2023-10-04 14:37
Arlight @dhanashree-sawant you have been paid in Upwork, so you are all set!

@ginsuma and @abdulrahuman5196 — I've sent offers to both of you in Upwork! Please let me know once you accept so we can get those paid ASAP. Thanks again for your patience with this!

**Comment by abdulrahuman5196** [comment] 2023-10-04 15:01
@CortneyOfstad Its 500$ for both C+ and contributor since there was a regression.

**Closed** 2023-10-04 15:07 UTC
Labels: Daily, Internal, Awaiting Payment, Bug
