### ISSUE TITLE
[HOLD #22332] Web -  In-consistent right margin after avatar on the request money chat

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#21528] opened 2023-06-25 16:07 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Open the App and Login.
2. Request money from a workspace.
3. Open the created chat report.

## Expected Result:
The spacing between avatar and user's email / name should be consistent.

## Actual Result:
 The spacing between avatar and user's email / name is more for the subscript avatar.

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [x] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 1.3.32.5
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation

![Screenshot 2023-06-19 at 10 28 26 AM (1)](https://github.com/Expensify/App/assets/93399543/eff11e25-6556-4ae5-bfc8-8cb673e3cc2f)

![image (95)](https://github.com/Expensify/App/assets/93399543/cd775238-34d5-47f3-81b0-3ec6d0396dbc)

**Expensify/Expensify Issue URL:** 
**Issue reported by:** Sibtain Ali
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1687152667921079

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by kbecciv** [comment] 2023-06-25 16:07
## Proposal
### Please re-state the problem that we are trying to solve in this issue.
Spacing between avatar and name is inconsistent
### What is the root cause of that problem?
The root cause of this issue is that SubscriptAvatar component by default adds a margin right. This causes an extra margin to appear.
### What changes do you think we should make in order to solve the problem?

We need to add noMargin prop [here](https://github.com/allroundexperts/Expensify/blob/41249bf76ec359463a2cdb66c3c0b93b3be9dec2/src/components/AvatarWithDisplayName.js#L73).
### What alternative solutions did you explore? (Optional)
None
**Reminder:** Please use plain English, be brief and avoid jargon. Feel free to use images, charts or pseudo-code if necessary. Do not post large multi-line diffs or write walls of text. Do not create PRs unless you have been hired for this job.

**Comment by Nikhil-Vats** [comment] 2023-06-26 07:23
@thienlnam is updating the design for this page. So, does this bug still need to be fixed?

**Comment by abekkala** [comment] 2023-06-30 15:59
@Christinadobrzyn Reassigning for Sabbatical 

___

### CURRENT STATUS: 

- Issue Reported By: @allroundexperts
- Assigned for Fix: TBD, may not be needed
- Assigned C+: TBD, may not be needed

On HOLD as 20844 may resolve this one!

**Comment by Christinadobrzyn** [comment] 2023-07-03 17:07
Moving to weekly since this is on Hold for https://github.com/Expensify/App/issues/20844

**Comment by Christinadobrzyn** [comment] 2023-07-12 00:30
Still on hold for https://github.com/Expensify/App/issues/20844

**Comment by thienlnam** [comment] 2023-07-12 17:50
Holding PR has been deployed to production - can we see if this is still reproducible?

**Comment by Christinadobrzyn** [comment] 2023-07-14 19:31
The screenshot in the OP doesn't show where the spacing is inconsistent. I don't know if this is fixed or now, asking qa if they can help - https://expensify.slack.com/archives/C9YU7BX5M/p1689363050971649

**Comment by thienlnam** [comment] 2023-07-17 18:41
Actually, this will be resolved in these PRs

https://github.com/Expensify/App/pull/22484 / https://github.com/Expensify/App/pull/22562

**Comment by thienlnam** [comment] 2023-07-17 18:42
Appears we had an issue for this here https://github.com/Expensify/App/issues/22332

**Comment by tjferriss** [comment] 2023-07-18 16:49
Thanks @Christinadobrzyn. I'll keep an eye on those PRs.

**Comment by tjferriss** [comment] 2023-07-24 22:44
@thienlnam it looks like the linked PRs have been merged. I'm having a hard time seeing the difference in the spacing from the original issue, but I think this might be fixed now. What do you think?

**Comment by thienlnam** [comment] 2023-07-24 22:50
Yeah I think this is probably fixed now

**Closed** 2023-07-24 23:20 UTC
Labels: Engineering, Daily, Bug
