### ISSUE TITLE
[$250] Room - Continue button becomes unresponsive when try to login via deep link

### ISSUE THREAD

**Issue by IuliiaHerets** [Expensify/App#49253] opened 2024-09-16 10:12 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 9.0.34-2
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**If this was caught during regression testing, add the test name, ID and link from TestRail:** https://expensify.testrail.io/index.php?/tests/view/4962361&group_by=cases:section_id&group_id=229066&group_order=asc
**Email or phone of affected tester (no customers):** gocemate+a2133@gmail.com
**Issue reported by:** Applause Internal Team

## Action Performed:
1. Logout of New Expensify if logged in
2. Navigate to the following link - https://staging.new.expensify.com/r/6776919265133947
3. Click on Join button
4. Add email address
5. Click Continue

## Expected Result:
Continue button should response

## Actual Result:
Continue button becomes unresponsive

## Workaround:
Unknown

## Platforms:

- [x] Android: Native
- [x] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

https://github.com/user-attachments/assets/06e418bd-b39e-423f-a7af-9411415c0e7a

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~021837011332462278943</li>
        <li>Upwork Job ID: 1837011332462278943</li>
        <li>Last Price Increase: 2024-09-27</li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @eVoloshchak</details>

**Comment by IuliiaHerets** [comment] 2024-09-16 10:13
@stephanieelliott  FYI I haven't added the External label as I wasn't 100% sure about this issue. Please take a look and add the label if you agree it's a bug and can be handled by external contributors

**Comment by mkzie2** [comment] 2024-09-17 12:34
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
- Continue button becomes unresponsive

### What is the root cause of that problem?
When pressing on "Continue" button in sign in modal, it calls:

https://github.com/Expensify/App/blob/1e8d80e850af52e60ec0fefbe11553cc196e8fee/src/libs/actions/Session/index.ts#L420

The read API is only called if the networkRequestQueue's length in onyx is 0.

In case of this bug, before we click on "Continue", the networkRequestQueue's length in onyx greater than 0, so the Continue button seems to become unresponsive.
### What changes do you think we should make in order to solve the problem?
Add ```isDisabled={networkRequestQueue.length > 0}```
to [FormAlertWithSubmitButton](https://github.com/Expensify/App/blob/1e8d80e850af52e60ec0fefbe11553cc196e8fee/src/pages/signin/LoginForm/BaseLoginForm.tsx#L290) will disable the Continue button when the networkRequestQueue's length is greater than 0.

We can also display additional messages such as "Some existing requests are running; cannot sign in now."

### What alternative solutions did you explore? (Optional)

In [this](https://github.com/Expensify/App/blob/1e8d80e850af52e60ec0fefbe11553cc196e8fee/src/libs/actions/Session/index.ts#L419), we can call ```PersistedRequests.clear()```.

**Comment by stephanieelliott** [comment] 2024-09-24 09:10
Hey @eVoloshchak there are some proposals here, can you review when you get.a sec?

**Comment by stephanieelliott** [comment] 2024-09-25 19:24
> Hey @eVoloshchak there are some proposals here, can you review when you get.a sec?

Bump on this @eVoloshchak

**Comment by stephanieelliott** [comment] 2024-09-30 06:11
Hey @eVoloshchak can you review please?

**Comment by stephanieelliott** [comment] 2024-10-03 22:53
Ok, I am going to reassign this since we haven't heard from @eVoloshchak. Posted for someone else to pick this up here: https://expensify.slack.com/archives/C02NK2DQWUX/p1727996021416879

**Comment by stephanieelliott** [comment] 2024-10-03 23:02
@hungvu193 is gonna pick up the C+ role on this one!

**Comment by hungvu193** [comment] 2024-10-03 23:44
Thanks for assigning. I'll review proposals today!

**Comment by hungvu193** [comment] 2024-10-04 06:50
@mkzie2 can you still reproduce this issue?

**Comment by mkzie2** [comment] 2024-10-04 07:32
@hungvu193 After this [PR](https://github.com/Expensify/App/pull/48057), the loading indicator is displayed instead of "unresponsive". So the original bug cannot be reproduced anymore.

**Comment by hungvu193** [comment] 2024-10-04 07:33
So I think we can close this one?

**Comment by mkzie2** [comment] 2024-10-04 07:54
Clicking the 'Continue' button triggers the BeginSignIn API. The root cause of the issue is that when the button is clicked, and there are 10 pending write APIs, the BeginSignIn API doesn't execute immediately. Instead, it waits for all 10 pending APIs to complete successfully. 

Previously, the 'Continue' button appeared unresponsive during this time, as there was no immediate feedback. 
However, we now display a loading indicator during this delay. 

Despite this, BeginSignIn still waits for the 10 write APIs to finish. Do you think this is an issue that needs to be addressed? @hungvu193

**Comment by hungvu193** [comment] 2024-10-04 08:20
> However, we now display a loading indicator during this delay.

I think this is expected. Showing a loading indicator is way more better than unresponsive.

**Closed** 2024-10-04 22:32 UTC
Labels: External, Daily, Bug
