### ISSUE TITLE
[$1000]  IOU - User A username got replaced with user B username on negative IOU request

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#23270] opened 2023-07-20 12:37 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Open staging.new.expensify.com
2. From user A, request an IOU from user B
3. From user B, request the same amount of IOU to user B (to create a negative IOU amount
4. From either users, click on the negative IOU request to open details page

## Expected Result:
Correct username and avatar to be displayed in header

## Actual Result:
Username of user B will be replaced by username of user A while keeping the correct avatar of user B

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [x] iOS / Safari
- [x] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 1.3.43.0

**Reproducible in staging?:** Yes

**Reproducible in production?:** Yes

**If this was caught during regression testing, add the test name, ID and link from TestRail:**

**Email or phone of affected tester (no customers):**

**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/78819774/5b3a0ba0-cd33-4e82-9ed3-5869ad784981

![Bug6135186_Screen_Shot_2023-07-20_at_3 06 29_PM](https://github.com/Expensify/App/assets/78819774/3ab39811-06b3-42a6-9083-0cbd28660106)

![Bug6135186_Screen_Shot_2023-07-20_at_3 06 08_PM](https://github.com/Expensify/App/assets/78819774/932c04e7-ee0a-45a7-a0c0-294e40d5d670)

**Expensify/Expensify Issue URL:**

**Issue reported by:** Applause - Internal Team

**Slack conversation:**
<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~018c79b247da5bf53c</li>
        <li>Upwork Job ID: 1684640677027917824</li>
        <li>Last Price Increase: 2023-08-10</li>
    </ul>
</details>

**Comment by mateocole** [comment] 2023-07-25 16:01
@bondydaa can you try reproducing this in a dev environment?

**Comment by bondydaa** [comment] 2023-07-26 20:16
😅 why? were you not able to reproduce it?

**Comment by NicMendonca** [comment] 2023-07-27 19:03
reproducible

<img width="293" alt="image" src="https://github.com/Expensify/App/assets/24947345/9f384179-99de-4720-87dd-9c1b7e1e7f1f">

<img width="311" alt="image" src="https://github.com/Expensify/App/assets/24947345/1018d757-537e-414f-bdc5-df50129d6051">

<img width="316" alt="image" src="https://github.com/Expensify/App/assets/24947345/c169513d-4157-4fd3-b77c-0a14855554c1">

**Comment by NicMendonca** [comment] 2023-08-01 21:12
@eVoloshchak bump on reviewing this proposal ^^

**Comment by eVoloshchak** [comment] 2023-08-03 15:43
@Nodebrute, the design for HeaderWithBackButton has changed slightly (it isn't yet on `new.expensify`, but you can already see it in the latest main). Your proposal doesn't resolve the issue now, could you update it please?

> First it's important to understand what we are expecting here
For me, I think the header should display the email of the person who is the actor of the parent report action. For example, if the following user is the actor of this action, then the header should have the name of this user.

That's correct

**Comment by eVoloshchak** [comment] 2023-08-06 20:59
@Nodebrute, this doesn't resolve the issue for me, notice the name is still incorrect

https://github.com/Expensify/App/assets/9059945/971d5aaa-2da9-45ca-b420-cbbb33a78429

> it looks like this issue does not exist, but only in the UI.

Not sure I understand, could you elaborate please?

**Comment by ShogunFire** [comment] 2023-08-08 19:00
I don't reproduce, is there something to do in particular apart from having negative iou ?
![image](https://github.com/Expensify/App/assets/19537677/f64c3cef-e33f-4614-9838-bf720c80f689)

**Comment by NicMendonca** [comment] 2023-08-10 14:56
I don't remember a specific quirk! I followed OP's video. 

@lanitochka17 any advice?

**Comment by NicMendonca** [comment] 2023-08-14 14:04
@lanitochka17 bump ^

**Comment by lanitochka17** [comment] 2023-08-15 15:23
Issue is not reproducible with Build 1.3.54-7

https://github.com/Expensify/App/assets/78819774/4a374e45-90f3-492a-bec0-8e9a2081607e

**Comment by NicMendonca** [comment] 2023-08-15 21:28
great! closing!

**Closed by NicMendonca** 2023-08-15 21:28 UTC
Labels: External, Engineering, Daily, Help Wanted, Bug
