### ISSUE TITLE
[HOLD for payment 2023-06-19] [$1000] Settings - Changing the profile picture offline shows the semi-transparent background to the camera icon.

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#19723] opened 2023-05-28 00:07 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Open App
2. Turn off the internet
3. Go to Settings > Profile > Press on Avatar > Upload photo > Choose from gallery > Select any image
4. Observe the camera icon

## Expected Result:
The camera Icon background should not display semi-transparent, so the user can not show the part of the profile picture behind the camera icon.

## Actual Result:
The camera icon background showing semi-transparent, and we can see the part of the profile picture

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [ ] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 1.3.19.2

**Reproducible in staging?:** yes

**Reproducible in production?:** yes

**If this was caught during regression testing, add the test name, ID and link from TestRail:**

**Email or phone of affected tester (no customers):**

**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/93399543/8c37671d-406b-4b95-9e17-99a6e6bc74d3

![icon-semi-transparent](https://github.com/Expensify/App/assets/93399543/2eb54b0a-a554-4385-b24b-f63ae5eb3091)

**Expensify/Expensify Issue URL:**

**Issue reported by:** @jayeshmangwani 

**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1684759100069759

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~0116b54fd9df3818de</li>
        <li>Upwork Job ID: 1664585952596090880</li>
        <li>Last Price Increase: 2023-06-02</li>
    </ul>
</details>

**Comment by jayeshmangwani** [comment] 2023-05-28 04:49
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
Changing the profile picture offline shows the semi-transparent background to the camera icon on the Android

### What is the root cause of that problem?
On Android, when we apply opacity to a parent, all of its children will inherit the opacity, context is here in the [issue](https://github.com/Expensify/App/issues/15283#issuecomment-1439413441)


### What changes do you think we should make in order to solve the problem?
We need to pass [needsOffscreenAlphaCompositing](https://reactnative.dev/docs/view#needsoffscreenalphacompositing) prop to the OfflineWithFeedback parent Of the AvatarWithImagePicker Component here so that Android can align with other platforms and child does not inherit the opacity
https://github.com/Expensify/App/blob/cb4f7c99aac03385dc93311842177d04d7796857/src/pages/settings/Profile/ProfilePage.js#L94-L98
`
    needsOffscreenAlphaCompositing
`

Adding this prop will cause a UI issue in Android where the camera will be cut from the bottom due to negative styling in the absolute View
```
smallAvatarEditIcon: {
    position: 'absolute',
    right: -4,
    bottom: -4,
},
```

The icon will cut 4 pixels from the bottom, and We can solve this by adding a 4-pixel bottom margin to AvatarWithImagePicker Component as we do in the WorkspaceSettingsPage page https://github.com/Expensify/App/blob/58dd3c8077e0ba3f2443a91dc17b334736f6e3da/src/pages/workspace/WorkspaceSettingsPage.js#L129   here we need to add `style={[styles.mb1]}` 
https://github.com/Expensify/App/blob/58dd3c8077e0ba3f2443a91dc17b334736f6e3da/src/pages/settings/Profile/ProfilePage.js#L100-L107

and need to reduce the top margin from the next Component in the View to make it even, here instead style={[styles.mt4]} need to use style={[styles.mt3]} https://github.com/Expensify/App/blob/58dd3c8077e0ba3f2443a91dc17b334736f6e3da/src/pages/settings/Profile/ProfilePage.js#L110



### What alternative solutions did you explore? (Optional)
none

**Comment by muttmuure** [comment] 2023-06-01 17:50
I think that this is expected - this has come up a couple of times so just checking @shawnborton, is the camera icon meant to become partially transparent when you go offline?

**Comment by shawnborton** [comment] 2023-06-02 10:00
Hmm I'm actually not sure, @trjExpensify my offline expert buddy - do we make buttons at reduced opacity when offline? if so, I guess this is right but it does not look great.

**Comment by jayeshmangwani** [comment] 2023-06-02 10:29
@shawnborton @muttmuure  iOS looks like the attached image, user avatar, and the camera icon opacity is reduced, but on iOS camera icon is not semi-transparent IMO this is the expected behavior that should be on Android too, but Android is not looking good

iOS

![Simulator Screen Shot - iPhone 14 - 2023-06-02 at 15 54 27](https://github.com/Expensify/App/assets/35371050/6cfead87-5a78-4053-a14a-4dbc4f8a311f)

**Comment by trjExpensify** [comment] 2023-06-02 10:35
Only the image should be at 50% opacity when it's in the "pending create" state here. There's nothing pending or preventing you from clicking the camera icon > removing the pending new avatar or uploading a new one.

**Comment by muttmuure** [comment] 2023-06-02 10:40
OK that makes sense to me and it sounds like it's an oversight that we're rendering it on Android like that.

**Comment by muttmuure** [comment] 2023-06-02 10:47
<img width="608" alt="image" src="https://github.com/Expensify/App/assets/46995600/3802e09a-68c7-4358-b34e-4334ca696cf4">

Lol now I can't reproduce this in Browserstack on Android.

**Comment by muttmuure** [comment] 2023-06-02 10:49
Asking what device @jayeshmangwani is using in Slack

**Comment by muttmuure** [comment] 2023-06-02 10:52
Oh I can't reproduce because I followed the steps wrong haha

**Comment by muttmuure** [comment] 2023-06-02 10:53
<img width="417" alt="image" src="https://github.com/Expensify/App/assets/46995600/ca78971e-5cde-4e97-acca-c9f0864859bf">

I've reproduced this now

**Comment by jayeshmangwani** [comment] 2023-06-02 11:03
> Only the image should be at 50% opacity when it's in the "pending create" state here. There's nothing pending or preventing you from clicking the camera icon > removing the pending new avatar or uploading a new one, so why would it be at 50% opacity to signal that you can't interact with it?

@trjExpensify Should we update the expected result in this GH issue to Avatar should have 50% opacity, and the camera icon has 100% opacity? Or do we have to create a new GH issue for that?

**Comment by trjExpensify** [comment] 2023-06-02 11:43
>@trjExpensify Should we update the expected result in this GH issue to Avatar should have 50% opacity, and the camera icon has 100% opacity? Or do we have to create a new GH issue for that?

Sure, we should be fixing that here definitely. The camera icon shouldn't be translucent and should be at 100% opacity.

**Comment by jayeshmangwani** [comment] 2023-06-02 12:43
@0xmiroslav Yes alternative solutions of the Updated Proposal meet the new expected behavior

**Comment by muttmuure** [comment] 2023-06-06 12:49
Just waiting for @johnmlee101 to give the go ahead for a PR. Should be an easy one

**Comment by johnmlee101** [comment] 2023-06-06 14:58
yeah makes sense!

**Comment by johnmlee101** [comment] 2023-06-06 14:58
@jayeshmangwani go with the alternative solution

**Comment by jayeshmangwani** [comment] 2023-06-06 18:34
[PR](https://github.com/Expensify/App/pull/20288) is ready for review

cc: @johnmlee101 @0xmiroslav

**Comment by muttmuure** [comment] 2023-06-12 23:43
Deployed to staging, not on prod yet

**Comment by muttmuure** [comment] 2023-06-21 08:44
@0xmiroslav and @jayeshmangwani both invited to apply.

@jayeshmangwani gets reporter and contributor bonuses because he did both

**Comment by muttmuure** [comment] 2023-06-21 08:56
Offer made to @jayeshmangwani

**Comment by jayeshmangwani** [comment] 2023-06-21 09:38
@muttmuure PR merged within 3 days so this is eligible for a 50% bonus

**Comment by jayeshmangwani** [comment] 2023-06-23 06:25
> PR merged within 3 days so this is eligible for a 50% bonus

@muttmuure Can you please confirm this, then I can accept the offer

**Comment by muttmuure** [comment] 2023-06-26 10:13
Everyone is paid, no regression test needed. 

@jayeshmangwani $1750
@0xmiroslav $1500

**Closed by muttmuure** 2023-06-26 10:13 UTC
Labels: External, Daily, Overdue, Awaiting Payment, Bug
