### ISSUE TITLE
[Awaiting Checklist Completion] [$2000] Blank Page Displayed when Copying and Pasting URL next  to Original URL and Reloading with Enter Key

### ISSUE THREAD

**Issue by kavimuru** [Expensify/App#22507] opened 2023-07-09 02:15 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Open any chat.
2. Copy the URL and paste it parallel to the original URL.
3. Press Enter to reload the page and observe that a blank page is displayed.
## Expected Result: 
When copying and pasting the URL parallel to the original URL and reloading with the Enter key, only one URL should be selected and a blank page should not be displayed. (I used Slack as an example)
## Actual Result: 
When copying and pasting the URL parallel to the original URL and reloading with the Enter key, a blank page is displayed instead of the expected content.

## Workaround:
Can the user still use Expensify without this being fixed? Have you informed them of the workaround?

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [x] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 1.3.38-2
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/43996225/f3dfdd05-c245-405f-ae76-c981adf07f22

https://github.com/Expensify/App/assets/43996225/f5ae2f0a-d6c1-43c7-af0c-2fac64802e55

**Expensify/Expensify Issue URL:**
**Issue reported by:** @tewodrosGirmaA
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1688830034011059

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~0189ab7cbca3720a13</li>
        <li>Upwork Job ID: 1679175204333420544</li>
        2023-07-25<li>Automatic offers: </li>
<ul>
<li>tewodrosGirmaA | Reporter | 25853284</li>
</ul></li>
    </ul>
</details>

**Comment by twisterdotcom** [comment] 2023-07-12 17:02
Okay, so the point is that we should resolve to this page that we see when you click "back":
<img width="792" alt="image" src="https://github.com/Expensify/App/assets/9133401/1d1104d2-b283-45c2-ac37-48de3e230269">

And not hang on this page:
<img width="797" alt="image" src="https://github.com/Expensify/App/assets/9133401/4f4abf62-eeab-475f-b8db-181bb2614c4f">

When we see an error right? That makes sense.

**Comment by twisterdotcom** [comment] 2023-07-12 17:05
It's weird that GitHub can render this though right?

<img width="1862" alt="image" src="https://github.com/Expensify/App/assets/9133401/e1fbd363-988d-4805-92c8-c685facd263f">

I think _if_ rendering the page and ignoring the following characters is possible, we should do that. Let's see what C+ thinks.

**Comment by twisterdotcom** [comment] 2023-07-12 17:06
@rushatgabhane - what do you think? Should we just resolve to the nice error page or is it feasible to actually load the correct page here.

Also, don't waste too much time because this is an insanely edge case bug. So making it weekly.

**Comment by Talha345** [comment] 2023-07-12 18:12
@twisterdotcom Github cannot always resolve the page,e.g if you try to reproduce withe URL of this issue it gives a 404.
I would suggest just to just show the 404 page instead of trying to resolve to the original URL beacuse you never know what URL combinations can be possible with this.

![image](https://github.com/Expensify/App/assets/36226639/9affd53b-fade-41bb-b8c6-07b8c7c3650f)

**Comment by Talha345** [comment] 2023-07-12 21:26
## Proposal

### Please re-state the problem that we are trying to solve in this issue.

If the original URL is appended to itself and accessed directly, a blank page is shown and the app freezes.

### What is the root cause of that problem?

According to the current logic, the URL in this issue is not sanitized properly and hence the report ID is not calculated correctly [here](https://github.com/Expensify/App/blob/main/src/ROUTES.js#L174) which leads to this blank screen ultimately.

### What changes do you think we should make in order to solve the problem?

There are 2 solutions to this as @twisterdotcom suggested:

1. We sanitize the URL [here](https://github.com/Expensify/App/blob/main/src/libs/ReportUtils.js#L2259) like:

```
const invalidUrlRegex = /^(https?:\/\/[^\s]+?)(https?:\/\/[^\s]+)/;
if (invalidUrlRegex.test(route)){
     route = route.replace(invalidUrlRegex, '$1');
}
```
This will just open the correct page by sanitizing the URL.

2. We show the 404 page by identifying the URL as invalid using the Regex from point 1.

I personally think showing the correct page would make more sense.

**Comment by Talha345** [comment] 2023-07-14 10:49
@rushatgabhane I agree with you that handling all edge cases will make code hard to maintain, therefore I suggested the solution to fix the issue in this particular case.

Also the current issue is only happening for a reports member route and not for other routes in the system.For e.g if you open something like https://new.expensify.com/settingshttps://new.expensify.com/settings,it will show the not found page, so I think at least we should make the behaviour consistent throughout the system.

**Comment by Talha345** [comment] 2023-07-14 10:53
@twisterdotcom @rushatgabhane I tried to reproduce it now and I am unable to do it now.Maybe some other change fixed it already.


https://github.com/Expensify/App/assets/36226639/cc29c76e-bc45-4c85-8eae-ee19e5474359

**Comment by twisterdotcom** [comment] 2023-07-14 10:54
Yeah, I mean part of me does just think any end user is holding it wrong if they do this.

Any other appendage, we show the error on the report route:
<img width="1092" alt="image" src="https://github.com/Expensify/App/assets/9133401/7946a81f-6686-4ca8-8248-ff0855a71982">

In fact, what I find odd really is that the LHN just isn't loaded when you append another URL, but I do see we load the error actually now:
<img width="1092" alt="image" src="https://github.com/Expensify/App/assets/9133401/9082acdb-b784-4911-8fd0-be4d7b37de15">

**Comment by twisterdotcom** [comment] 2023-07-14 10:55
I think the only weird thing is the lack of LHN. Any ideas about that?

**Comment by Talha345** [comment] 2023-07-14 14:06
@twisterdotcom @rushatgabhane I did some digging and it boils down to how the navigation logic is handled [here](https://github.com/Expensify/App/blob/main/src/libs/Navigation/linkTo.js#L43-L91).

When some random text is added it becomes a part of the route and `action.type` is set to `REPLACE` which is then passed on [here](https://github.com/Expensify/App/blob/main/src/libs/Navigation/linkTo.js#L86C1-L90).

On the other hand, when a link is appended action.type is set to 'PUSH' which results in no LHN being shown.

I would suggest to not make changes at such a lower level and would propose to use my original solution again which will just sanitize the URL in this scenario before passing it down to the navigation logic and the correct report page will be displayed.

**Comment by twisterdotcom** [comment] 2023-07-17 10:26
@rushatgabhane I have to think this makes sense now. We correctly show the error in every instance other than this specific one, so targeting just this specific instance with a fix makes sense.

**Comment by Talha345** [comment] 2023-07-20 08:56
@twisterdotcom is there any process in place on how to proceed here because @rushatgabhane has been MIA?

**Comment by rushatgabhane** [comment] 2023-07-20 09:15
@twisterdotcom i still think this issue should be closed 😅

**Comment by Talha345** [comment] 2023-07-20 12:23
@rushatgabhane @twisterdotcom  Let me reiterate once again.As mentioned previously, we correctly show the error in every instance other than this specific one.

For e.g:

https://new.expensify.com/settingshttps://new.expensify.com/settings --> Not Found
https://new.expensify.com/settings/shareCodehttps://new.expensify.com/settings/shareCode --> Not Found

Only for a report member route like the one below the error happens and previously it showed a blank page and now it redirects to https://new.expensify.com/r/8521307206478388https%3A and shows Not Found.

https://new.expensify.com/r/8521307206478388https://new.expensify.com/r/8521307206478388

Also I do not get your point that we should fix the root cause because in this case the cause I mentioned in my original proposal is actually the root cause.

Let me walk you through what happens when a deep link with report ID is opened in our app:

1. This [line](https://github.com/Expensify/App/blob/main/src/Expensify.js#L165) get executed which calls the `openReportFromDeepLink` method [here](https://github.com/Expensify/App/blob/main/src/libs/actions/Report.js#L1680) which in turn calls this method [here](https://github.com/Expensify/App/blob/main/src/libs/ReportUtils.js#L2326) and you can clearly see that this method already has a few regex to sanitize the link.

My solution [here](https://github.com/Expensify/App/issues/22507#issuecomment-1633234080) was to add the following code block [here](https://github.com/Expensify/App/blob/main/src/libs/ReportUtils.js#L2330) and pre-santize the URL for before passing it on to further regex and returning the route.

```
const invalidUrlRegex = /^(https?:\/\/[^\s]+?)(https?:\/\/[^\s]+)/;
if (invalidUrlRegex.test(route)){
     route = route.replace(invalidUrlRegex, '$1');
}
```

In my opinion, this is a totally valid solution and not a workaround.

**Comment by Talha345** [comment] 2023-07-24 21:53
@twisterdotcom @rushatgabhane any update on this?

**Comment by depak379mandal** [comment] 2023-07-25 07:18
@kavimuru Can I work on this?
I got a proposal on upwork. If this task is occupied, I can start with introductory task. So you can get my code quality and review that. Let me know.

**Comment by depak379mandal** [comment] 2023-07-25 07:22
Contributor details
Your Expensify account email: deepak379mandal@gmail.com
Upwork Profile Link: https://www.upwork.com/freelancers/deepakm18

**Comment by twisterdotcom** [comment] 2023-07-25 08:21
@depak379mandal - @kavimuru is from our QA team, they simply triage and create the issues reported in our #expensify-bugs room Slack environment. Always address any questions you have to the assignees on the issues please.

You must submit a proposal in GitHub and it will be reviewed by @rushatgabhane.

**Comment by twisterdotcom** [comment] 2023-07-25 08:22
Going to raise the bounty on this one.

**Comment by dantastisk** [comment] 2023-07-25 13:16
## Proposal

### Please re-state the problem that we are trying to solve in this issue.

We are showing a wrong/wonky error page when appending a report page url to itself

### What is the root cause of that problem?

The problem is the following function checking for the boolean/truthy value of the third segment of the route when split by '/' in order to determine whether it is a subReportPageRoute. The 2 consecutive slashes in '...http://...' is what's causing the unexpected behaviour. You will see similar cases if you append anything else with 2 consecutive slashes (like //example).

https://github.com/Expensify/App/blob/beebb67612cea0201f4fb1b6b17840cb5893d754/src/ROUTES.js#L173-L189

### What changes do you think we should make in order to solve the problem?

To fix the issue we should simply check if pathSegments.length > 2 instead, like so:

```js
        return {
            reportID: lodashGet(pathSegments, 1),
            isSubReportPageRoute: pathSegments.length > 2,
        };
```

### What alternative solutions did you explore? (Optional)

Alternatively we can check for the truthy value like currently OR/AND compare the string to a list of valid subReportPages, but I believe this will introduce unnecessary maintenance-trouble.


https://github.com/Expensify/App/assets/48072523/02198a6c-e460-44e4-aa59-de9d81b6a1cb

**Comment by rushatgabhane** [comment] 2023-07-25 16:48
> You will see similar cases if you append anything else with 2 consecutive slashes (like //example)

oh nice find!

> To fix the issue we should simply check if pathSegments.length > 2 instead, like so:

@dantastisk could you please explain your proposal in simple words? I need help understanding your proposal

**Comment by Talha345** [comment] 2023-07-25 17:19
@rushatgabhane While @dantastisk's solution works, it is more of a workaround because you see `pathSegments` holds the result of the route splitted by `/`.So, e.g:

1. In case of http://localhost:8080/r/3050448180853096http://localhost:8080/r/3050448180853096,  `pathSegments = ['r', '3050448180853096http:', '', 'localhost:8080', 'r', '3050448180853096']`

2.In case of http://localhost:8080/r/3050448180853096, `pathSegments = ['r', '3050448180853096']`

The solution works because if pathSegments.length > 2 then the calling function treats it as a subReportRoute such as settings, details etc and then redirects to the respective component pages which can been seen [here](https://github.com/Expensify/App/blob/main/src/libs/ReportUtils.js#L2412-L2419) but if you see the above array the `pathSegment[1]` item still has http appended to the report ID.Therefore ,in my opinion it is a workaround

**Comment by dantastisk** [comment] 2023-07-25 18:04
@rushatgabhane pathSegments is an array of the route split at each occurence of '/' like the example given by @Talha345 above:
```js
'http://localhost:8080/r/3050448180853096http://localhost:8080/r/3050448180853096' ->
pathSegments = ['r', '3050448180853096http:', '', 'localhost:8080', 'r', '3050448180853096']
```
 isSubReportPageRoute is set to false if the second entry of this array evaluates to false when cast to a Boolean because of this line:
```js
isSubReportPageRoute: Boolean(lodashGet(pathSegments, 2))
```

If the string has '//' directly following the report id, the second entry of the array will be an empty string like in the given example and will therefore evaluate to false. So to clarify from my proposal '//' has to be the first occurrence of '/' following the report id.

So as for your scenarios it doesn't matter how many times '//' occurs, what matters is that it can't be the first occurrence of '/' after the report id.

I do not agree with @Talha345's statement above. If we wanted to show the actual report, we would have to retrieve the report ID from an endless pool of possible inputs which is simply not possible without hackish solutions. It is a better solution to show a consistent and properly formatted error when faced with what is in fact a "wrong" link.

To quote the great Jamie Zawinski:

_Some people, when confronted with a problem, think "I know, I'll use regular expressions." Now they have two problems._

**Comment by Talha345** [comment] 2023-07-25 18:35
@dantastisk Just to clarify, I absolutely hate regular expressions in general. 😅

**Comment by twisterdotcom** [comment] 2023-07-27 22:05
>It is a better solution to show a consistent and properly formatted error when faced with what is in fact a "wrong" link.

I agree with this @dantastisk. @rushatgabhane I think we should go with that.

**Comment by twisterdotcom** [comment] 2023-07-31 08:36
@rushatgabhane let me know if you can't get to this and I'll reassign somebody tomorrow if not.

**Comment by rushatgabhane** [comment] 2023-07-31 08:42
> If the string has '//' directly following the report id, the third entry of the array will be an empty string like in the given example and will therefore evaluate to false. So to clarify from my proposal '//' has to be the first occurrence of '/' following the report id.

> So as for your scenarios it doesn't matter how many times '//' occurs, what matters is that it can't be the first occurrence of '/' after the report id.

sounds good. thanks for the explanation @dantastisk 
your proposal tests well https://github.com/Expensify/App/issues/22507#issuecomment-1649828706

C+ reviewed 🎀 👀 🎀

**Comment by dantastisk** [comment] 2023-07-31 09:05
PR coming today!

**Comment by dantastisk** [comment] 2023-07-31 15:54
PR ready for review https://github.com/Expensify/App/pull/23931 @rushatgabhane

**Comment by twisterdotcom** [comment] 2023-08-14 09:54
@rushatgabhane please complete the checklist.

**Comment by rushatgabhane** [comment] 2023-08-14 18:43
Created a manual request here - https://staging.new.expensify.com/r/2058131871720982

**Comment by JmillsExpensify** [comment] 2023-08-16 03:28
Reviewed the details for @rushatgabhane. This is approved for payment in NewDot based on the BZ summary above.

**Closed** 2023-08-16 09:33 UTC
Labels: External, Engineering, Weekly, Bug
