### ISSUE TITLE
Explore moving the network reconnection logic to the View part of the application

### ISSUE THREAD

**Issue by cead22** [Expensify/App#8610] opened 2022-04-12 20:41 UTC
**Problem**
The current reconnection logic requests a lot of unnecessary data (like for views that aren’t even mounted) which decreases app performance (this is a well-known problem on Android)
**Solution**
Reconnection logic will be moved to the view part of the application.
- An HOC will be built that will be used for fetching the data a component needs, when it needs it
    - The HOC will listen for a network reconnection event NetworkConnection.onReconnect()
    - Every component using this HOC will get a method to fetch data: this.props.fetchData()
    - This method will be automatically called from onComponentMount() from the HOC
    - This method will also be triggered when the network reconnects
    - This method will be responsible for requesting data from the API and storing it in the state of the component
- This means that only mounted components (ie. currently visible components) will refresh their data on reconnect
- All generic reconnection callbacks will be removed from the existing code (fetchPersonalDetails() and fetchAllReports())

@tgolen @marcaaron @iwiznia looking for guidance, what do you suggest are the next steps here?

**Comment by tgolen** [comment] 2022-04-12 20:52
I think that sounds like a good plan!

As for next steps, this feels like it would probably be good to go through WN. I bet the doc will be small, so it will probably go pretty quickly. We can narrow down the exact details for each of those points in the detailed section.

As for exploring the exact solution, I would suggest getting familiar with an HOC and how it works. They are all defined in our code in files prefixed with `with`. https://github.com/Expensify/App/blob/aac57d37c29c0d8d8fa6261f6a50c69295e966cd/src/components/withEnvironment.js is a great simple example.

This one has quite a few more features: https://github.com/Expensify/App/blob/195891f1e12b7c6d92dd6ff2efe045bbd8bcc1be/src/components/withLocalize.js

As always, the official docs on HOCs is advisable too: https://reactjs.org/docs/higher-order-components.html

**Comment by marcaaron** [comment] 2022-04-12 21:42
>requests a lot of unnecessary data (like for views that aren’t even mounted) which decreases app performance (this is a well-known problem on Android)

Is there a reproduction somewhere for this and/or can we benchmark it somehow? Intuitively this problem statement makes sense, but we should be able to:

- call out which reconnection callbacks are unnecessary (there are not that many)
- describe how app performance is affected and to what severity

I would recommend we do this before discussing any solutions. It's hard for me to think of alternatives to this problem because it sounds like the problem is "we are requesting data we don't need". Is it true? Which data do we request that's not needed?

**Comment by iwiznia** [comment] 2022-04-18 14:32
I totally agree with @marcaaron's comments. The problem sounds real but:
- Are we really loading data we don't need? If so, which data?
- How/why does the performance decrease due to loading more data exactly?

Also, assuming we go through with this, is there any concern that some very common pieces of data that are used in many views would get downloaded many times? ie: assume we have 5 mounted components that need the user's personal details. When we come back online, we download that once only, but with this new system the 5 different components would load the same data 5 times in a row.

**Comment by tgolen** [comment] 2022-04-20 19:03
That's a really good point, @iwiznia about multiple components making the same request. I hadn't considered that. Maybe we can de-dupe the requests somehow...

**Comment by tgolen** [comment] 2022-04-20 19:04
I think getting more crisp on the current problem is the right place to start for now, and then we can discuss the solution later once we know exactly what (or IF) the problem is.

**Comment by cead22** [comment] 2022-04-20 23:09
@tgolen any suggestions for how to go about that? Should we first verify whether we're making unnecessary requests for views that aren't mounted, or is that already confirmed?

**Comment by tgolen** [comment] 2022-04-21 20:23
> verify whether we're making unnecessary requests for views that aren't mounted

To help clarify this a little more, nothing in the reconnection logic is connected to views right now (mounted or unmounted) from what I know. So, I think we just need to determine first if the reconnection requests are:

- unnecessary
- leading to performance problems (like a bunch of re-rendering, or a bunch of JSON parsing, or something else)

If we can't determine that either of the above are a problem, then we can probably just close this out. Here's how I would do it (and have done it in the past).

1. Load up the site
2. Open the dev console > network tab and clear it out
3. Switch to another tab for a little bit
4. Switch back to the app
5. See which network connections were made and see if you can track them down to what is triggering them
6. Record a JS performance profile of the same interaction and then try to see if there is a bunch of blocking or max CPU for a long time (sorry, this is really more of an artform than something that can be explained)

**Comment by cead22** [comment] 2022-04-26 21:07
Slapping the planning label on this one since we don't have any action items right now and still need to confirm whether this is a problem

**Comment by cead22** [comment] 2022-06-13 16:57
No update

**Closed** 2022-07-15 14:10 UTC
Labels: Monthly, Improvement, Planning, Overdue, Not a priority
