### ISSUE TITLE
Attachment – Unable to play/pause taping on the video screen center in a fullscreen mode

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#39622] opened 2024-04-04 15:59 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.60-1
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**If this was caught during regression testing, add the test name, ID and link from TestRail:** N/A
**Email or phone of affected tester (no customers):** ponikarchuks+315324@gmail.com
**Issue reported by:** Applause - Internal Team

## Action Performed:
1. Go to https://staging.new.expensify.com/
2. Log in
3. Go to any chat and send video
4. Open the video in a fullscreen mode
5. Tap on the video screen center some times

## Expected Result:
Able to play/pause taping on the video screen center in a fullscreen mode

## Actual Result:
Unable to play/pause taping on the video screen center in a fullscreen mode

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [ ] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details> 

https://github.com/Expensify/App/assets/78819774/911d7625-94e0-4552-b83a-6bb10c6883dc

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by lanitochka17** [comment] 2024-04-04 16:00
@Christinadobrzyn  FYI I haven't added the External label as I wasn't 100% sure about this issue. Please take a look and add the label if you agree it's a bug and can be handled by external contributors

**Comment by lanitochka17** [comment] 2024-04-04 16:00
We think that this bug might be related to #vip-vsp

**Comment by Christinadobrzyn** [comment] 2024-04-05 07:51
I can't reproduce this - when clicking on a video (around the middle) the video stops (I can also see the 'pause' and 'play' icons changing. 

https://github.com/Expensify/App/assets/51066321/aa842533-c2f0-433d-9205-e182438a3868

I also can't clearly see this happening in the OP video. Since it's affecting one platform (I think we should close this for now)

**Closed by Christinadobrzyn** 2024-04-05 07:51 UTC
Labels: Daily, Bug
