### ISSUE TITLE
[HOLD for payment 2024-10-08] [$125] iOS&Android - Profile - No skeleton placeholder on avatar while app is loading

### ISSUE THREAD

**Issue by IuliiaHerets** [Expensify/App#49526] opened 2024-09-20 11:17 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 9.0.38-0
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**Issue was found when executing this PR:** https://github.com/Expensify/App/pull/48517
**Email or phone of affected tester (no customers):** applausetester+kh010901@applause.expensifail.com
**Issue reported by:** Applause Internal Team

## Action Performed:
1. Launch New Expensify app.
2. Go to Account settings > Troubleshoot.
3. Tap Clear cache and restart.
4. Tap Reset and refresh.
5. Go to Profile while app is loading (or go offline after reset and refresh app if the app loads too fast).

## Expected Result:
There will be skeleton placeholder on avatar while app is loading (mweb behavior).

## Actual Result:
There is no skeleton placeholder on avatar while app is loading.

## Workaround:
Unknown

## Platforms:

- [x] Android: Native
- [ ] Android: mWeb Chrome
- [x] iOS: Native
- [ ] iOS: mWeb Safari
- [ ] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

https://github.com/user-attachments/assets/f54ff833-9250-4a85-8f0a-47cd2d0efb4d

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~021838053262759557407</li>
        <li>Upwork Job ID: 1838053262759557407</li>
        <li>Last Price Increase: 2024-09-23</li>
<li>Automatic offers: </li>
<ul>
<li>suneox | Reviewer | 104110948</li>
<li>abzokhattab | Contributor | 104110949</li>
</ul></li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @suneox</details>

**Comment by IuliiaHerets** [comment] 2024-09-20 11:17
@greg-schroeder  FYI I haven't added the External label as I wasn't 100% sure about this issue. Please take a look and add the label if you agree it's a bug and can be handled by external contributors

**Comment by kaushiktd** [comment] 2024-09-23 06:16
## Proposal
### Please re-state the problem that we are trying to solve in this issue.

iOS&Android - Profile - No skeleton placeholder on avatar while app is loading

### What is the root cause of that problem?

For `SkeletonViewContentLoader` in react-content-loader, the `width` property is required for the skeleton to load. However, the width property is not set [here](https://github.com/Expensify/App/blob/ad3bf76e0f3dbe4fab0cf0573502fd4500c49bfd/src/components/AvatarSkeleton.tsx#L15-L21).

### What changes do you think we should make in order to solve the problem?
You need to add `width` property to `SkeletonViewContentLoader` component. You can set custom width [here](https://github.com/Expensify/App/blob/ad3bf76e0f3dbe4fab0cf0573502fd4500c49bfd/src/components/AvatarSkeleton.tsx#L15-L21).

<details>
<summary>ScreenShot</summary>


https://drive.google.com/file/d/1RTV-6YVzYawYKzlt7lhDVrmUtQJwA6uD/view?usp=sharing
</details>

**Comment by suneox** [comment] 2024-09-23 06:29
@abzokhattab [proposal](https://github.com/Expensify/App/issues/49526#issuecomment-2363736049) LGTM

🎀 👀 🎀 C+ reviewed

**Comment by suneox** [comment] 2024-09-26 18:53
@abzokhattab Could you please provide an ETA for the PR?

**Comment by greg-schroeder** [comment] 2024-09-27 19:43
Thanks for the update @abzokhattab!

**Comment by greg-schroeder** [comment] 2024-10-01 01:58
Nice! Merged and on staging - awaiting deploy to prod

**Comment by greg-schroeder** [comment] 2024-10-03 01:32
Deployed 10/1 - regression period is 10/8

**Comment by greg-schroeder** [comment] 2024-10-08 21:16
Payment summary:

Contributor: @abzokhattab - $125 - Paid via Upwork
C+: @suneox - $125 - Paid via Upwork

**Closed** 2024-10-08 21:17 UTC
Labels: External, Weekly, Overdue, Awaiting Payment, Bug
