### ISSUE TITLE
[$250] [P2P Distance] Split - Incorrect amount & distance behavior when changing distance on confirm page offline

### ISSUE THREAD

**Issue by IuliiaHerets** [Expensify/App#47048] opened 2024-08-08 09:48 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** v9.0.18-1
**Reproducible in staging?:** Y
**Reproducible in production?:** N
**Email or phone of affected tester (no customers):** applausetester+kh050806@applause.expensifail.com
**Issue reported by:** Applause Internal Team

## Action Performed:
1. Go to staging.new.expensify.com
2. Go to group chat.
3. Click + > Split expense > Distance.
4. Enter waypoints > Next.
5. On confirmation page, go offline.
6. Click Distance.
7. Change distance by swapping position and save it.

## Expected Result:
- Amount field will be empty.
- Distance field will change to Pending.
- Split input will be 0.00.

## Actual Result:
Amount, Distance and split inputs change to a very big value.

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [x] Android: mWeb Chrome
- [x] iOS: Native
- [x] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

https://github.com/user-attachments/assets/492ce2d4-1320-4063-ad04-7561063a3efd

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~016482e5c32e2edfad</li>
        <li>Upwork Job ID: 1823019084308686776</li>
        <li>Last Price Increase: 2024-09-02</li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @carlosmiceli</details>

**Comment by IuliiaHerets** [comment] 2024-08-08 09:48
We think that this bug might be related to #vip-split

**Comment by bernhardoj** [comment] 2024-08-08 11:11
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
The distance, amount, and individual split share changes to a very big value.

### What is the root cause of that problem?
From the expected result, the 1st (Amount field will be empty) and 2nd problem (Distance field will change to Pending) is the same root cause as https://github.com/Expensify/App/issues/46952 and is currently being handled in https://github.com/Expensify/App/pull/46964.

For the 3rd problem (Split input will be 0.00), even after we fix the 1st and 2nd, the split amount still won't be 0 when the distance amount is 0 because we only update the individual split amount if the distance amount (`amount`) is truth (> 0).
https://github.com/Expensify/App/blob/9c7c4a1cb9405f64c31c03c4f1fa33c0c041dac0/src/components/MoneyRequestConfirmationList.tsx#L345-L348

### What changes do you think we should make in order to solve the problem?
If we want to update the individual split amount to 0 when the distance amount is 0, then we need to remove the `amount` check here.
https://github.com/Expensify/App/blob/9c7c4a1cb9405f64c31c03c4f1fa33c0c041dac0/src/components/MoneyRequestConfirmationList.tsx#L345-L348

However, I notice that when we create the split distance while offline with the pending distance, the request will always fail and also, the participant is only the current user because we don't include participants with 0 split amount.
https://github.com/Expensify/App/blob/9c7c4a1cb9405f64c31c03c4f1fa33c0c041dac0/src/libs/actions/IOU.ts#L4053
https://github.com/Expensify/App/blob/9c7c4a1cb9405f64c31c03c4f1fa33c0c041dac0/src/pages/iou/request/step/IOURequestStepConfirmation.tsx#L342-L352
https://github.com/Expensify/App/blob/9c7c4a1cb9405f64c31c03c4f1fa33c0c041dac0/src/libs/actions/IOU.ts#L4062-L4066

I tried to always include the participant even when the amount is 0, but it still fails.

Maybe we can disable the confirmation button if the distance amount is 0.

**Comment by Julesssss** [comment] 2024-08-08 12:05
Not treating this as a blocker. While annoying it should be rare and has an obvious workaround.

**Comment by bernhardoj** [comment] 2024-08-14 11:58
I think you need the p2p distance beta permission.

**Comment by bernhardoj** [comment] 2024-08-14 13:35
Yes, but it's the same error when you do it with the current user as the only participant.

**Comment by Julesssss** [comment] 2024-08-20 16:53
Sorry, I need to delay this answer, I don't have time to investigate this currently 😭

**Comment by greg-schroeder** [comment] 2024-08-27 05:44
I'm going to open [this](https://github.com/Expensify/App/issues/47048#issuecomment-2288833759) up for discussion to the greater team as Jules doesn't have bandwidth

**Comment by Julesssss** [comment] 2024-08-27 10:06
I took another look and the 'Maybe we can disable the confirmation button if the distance amount is 0.' suggestion is the best we currently have We'll get back to this after an internal discussion

**Comment by neil-marcellini** [comment] 2024-08-27 18:07
After reviewing everything here I think it makes sense for us to make an exception for offline distance requests. If it's a distance request and the amount is 0 because fetching the route is pending, then allow split participants to be 0. Maybe we would show the rows as empty in that case in the same way that we show the amount as being empty for offline distance requests?

Do we still get a backend error if we send all split participants with $0 amounts? Glancing at the backend code I think it won't work as is, because although we will fetch the route and compute the amount, we're never going to update the splits data based on that, and then Auth will [throw an error](https://github.com/Expensify/Auth/blob/72ddf3b22243e7e770b4763346c7c9c32a12243e/auth/lib/Transaction.cpp#L3889-L3892) while validating the splits. We'll need to split the amount across the participants somewhere [around here in Web-E](https://github.com/Expensify/Web-Expensify/blob/98b344e16b70141eaf860c8fb893f252d3db3e2e/lib/TransactionAPI.php#L1992). I'm realizing that also means that we can only do even splits while offline, but I think that's a reasonable limitation.

**Comment by carlosmiceli** [comment] 2024-09-04 17:01
I'll take this one.

**Comment by mvtglobally** [comment] 2024-09-09 04:12
Issue not reproducible during KI retests. (First week)

**Comment by greg-schroeder** [comment] 2024-09-09 06:30
Thoughts on next steps here @carlosmiceli?

**Comment by carlosmiceli** [comment] 2024-09-09 13:51
I haven't been able to start this one yet, let's check with @neil-marcellini. Should we continue testing this, or close it?

**Comment by neil-marcellini** [comment] 2024-09-11 19:51
Yes what do you think about [this plan](https://github.com/Expensify/App/issues/47048#issuecomment-2313205578)? We can discuss more 1:1

**Comment by neil-marcellini** [comment] 2024-09-11 20:21
> Issue not reproducible during KI retests. (First week)

I disagree. The result is slightly different but this flow is still broken.


https://github.com/user-attachments/assets/f4ac32a4-60ad-4877-b95b-984962f1a7e5

**Comment by mvtglobally** [comment] 2024-09-13 16:40
Issue not reproducible during KI retests. (Second week)

**Comment by neil-marcellini** [comment] 2024-09-13 18:23
@mvtglobally why do you say it's not reproducible? I just found that it was reproducible [yesterday](https://github.com/Expensify/App/issues/47048#issuecomment-2344630586). Did it get fixed in a day? I doubt it. Would you please include a video of your test?

**Comment by carlosmiceli** [comment] 2024-09-17 11:18
Should get started on it today.

**Comment by greg-schroeder** [comment] 2024-09-18 18:39
Thanks for the update @carlosmiceli!

**Comment by carlosmiceli** [comment] 2024-09-18 19:03
@neil-marcellini How do I get location working? I already gave access.

<img width="1615" alt="Screenshot 2024-09-18 at 4 02 46 PM" src="https://github.com/user-attachments/assets/431f247a-5a4a-4255-a3f5-7039b7c81954">

**Comment by carlosmiceli** [comment] 2024-09-25 14:04
Was OOO, will try to work on it this week after I deal with some backlog.

**Comment by greg-schroeder** [comment] 2024-09-27 19:40
Okay Thanks @carlosmiceli!

**Comment by greg-schroeder** [comment] 2024-10-01 02:16
Closing as #vip-split is now closed/archived/paused - let me know if you disagree @carlosmiceli 

context: https://expensify.slack.com/archives/C05RECHFBEW/p1727723167802139

**Closed by greg-schroeder** 2024-10-01 02:16 UTC
Labels: Engineering, Weekly, Improvement, Internal, Bug
