### ISSUE TITLE
Allow the app to work without storage in extreme cases where it fails completely

### ISSUE THREAD

**Issue by marcaaron** [Expensify/App#29403] opened 2023-10-12 00:24 UTC
# Problem

There are documented cases where IndexedDB _appears_ to completely fail to spin up space for the app to use. The app won't work at all when this happens. Most recently this happened to @davidcardoza [here](https://github.com/Expensify/Expensify/issues/325358) (sorry, internal).

The error we saw in the JS console was :

```
Internal error opening backing store for indexedDB.open
```

We then get stuck in a spot where since the IndexedDB store doesn't work basically nothing works.

# Solution

While we aim to have the app work offline and provide a good return experience with some data and request persistence. If the app can't save anything to storage at all it should still work. If we run into a serious error like this - we should gracefully degrade the experience.

# Bonus quest

Actually, figure out why exactly all the IndexedDB errors happen...

**Comment by marcaaron** [comment] 2023-10-16 23:35
@chrispader should I assign you to this issue? I think it should be fairly straightforward of a change.

**Comment by chrispader** [comment] 2023-10-17 14:53
Yes, you can assign me! 👍

**Comment by marcaaron** [comment] 2023-10-18 00:38
🤙

**Comment by chrispader** [comment] 2023-10-23 14:42
Just finished the E2E encryption library, so i have more time to work on this now! Looking at this this week 👍

**Comment by marcaaron** [comment] 2023-10-31 01:32
@chrispader any thoughts?

**Comment by chrispader** [comment] 2023-11-03 16:28
Sorry for the delay again 🥴 I can look into this over the weekend, though if this has high priority, you might want assign it to somebody else @marcaaron 

Still pretty busy with other tasks unfortunately

**Comment by chrispader** [comment] 2023-11-09 14:52
Going to look into this tmrw! For real!

**Comment by chrispader** [comment] 2023-11-13 15:11
> Most recently this happened to @davidcardoza [here](https://github.com/Expensify/Expensify/issues/325358) (sorry, internal).

@marcaaron is there any other information about this specific incident or any other reproduction steps?

No worries if not, i should still be able to adapt the app for this issue without actually getting any errors from `IndexedDB`

**Comment by chrispader** [comment] 2023-11-13 16:52
I have a couple of thoughts and proposals for this problem after my initial investigation:

The error that @davidcardoza experienced is supposedly thrown by [`createStore` function call](https://github.com/Expensify/react-native-onyx/blob/2fe9b570e8049ae2379c02916f2440923d08c496/lib/storage/providers/IDBKeyVal.js#L21) in the web storage provider implementation `IDBKeyVal`. On native, this could also happen similarly in the the `SQLiteStorage` provider.

These errors will essentially be thrown at bundle start time (when `Onyx` get's imported the first time), since we're already trying to establish the storage instance by then.

# Questions

To which degree should the app still work reliably? There are certainly a lot of screens/components/flows that rely on the data that's set with `Onyx.set` or `Onyx.merge` to be written to the storage or at least the cache.

Is the idea behind this issue to essentially just omit storage persistence in general and only rely on cache for these extreme cases? If so, we there are some approaches we could go for:

# Possible solutions

## Optimistically creating storage instances

We can try to create/connet to the storage instance - `idb-keyval` store on web and `SQLiteStorage` DB on native - at bundle start time, but not throw an error. When functions like `Onyx.set`/`Onyx.merge`/`Onyx.get` later try to access this data from storage and the storage instance couldn't be created, we'll simply return the value from cache.

All of this could be done inside `react-native-onyx` without the need to adapt anything in the app really.

## Initial Onyx initialisation

In order to safely provide a backup solution for when the storage initialisation is not working, we could add a "initialisation phase" in `Onyx`, which will create the local storage instance and if failing, this will give us the chance to omit the storage and only rely on cache.

In this context, i was thinking of adding something a function like `initOnyx` (there's already `Onyx.init` though).

## Error handling directly in the app

I think this might be the least favourable and most difficult approach, since we use Onyx in lots of places and functions like `Onyx.set`/`Onyx.merge` will already handle the errors from the storage layer, which could lead to [Onyx trying to evict from storage](https://github.com/Expensify/react-native-onyx/blob/2fe9b570e8049ae2379c02916f2440923d08c496/lib/Onyx.js#L1084) or further [throwing and logging errors when getting data](https://github.com/Expensify/react-native-onyx/blob/2fe9b570e8049ae2379c02916f2440923d08c496/lib/Onyx.js#L144)

**Comment by chrispader** [comment] 2023-11-21 14:36
cc @marcaaron @tgolen

**Comment by tgolen** [comment] 2023-11-21 16:06
@chrispader My first thoughts are much the same as yours, and I will expand on a few other things that I thought of.

We already have `setMemoryOnlyKeys`, which we actually set from the API side when there is a large account (it's determined from the payload size of `ReconnectApp` and if it is over a certain amount, like 50mb, then the API will turn on memory only keys). You can see the code for that here: https://github.com/Expensify/App/blob/bf04cd76b4e7f0d76d17be645898ce2ea3391b9d/src/libs/Middleware/SaveResponseInOnyx.ts#L22-L29

I know that `setMemoryOnlyKeys` isn't perfect, but this is maybe the chance we need to make it more robust and handle this case where disk storage is unavailable and everything needs to be handled in memory. I wonder if we need a third data provider for Onyx which would be an "in memory storage provider" and we could switch over to that when the disk storage providers aren't available? That's roughly the same thing as just always falling back to the cache, but it makes it more of a first-class solution, whereas the cache is kind of a hidden feature currently.

It might be nice to have a hybrid approach where Onyx is only using memory storage, and then the App displays a global banner like "There could be degraded performance, blah blah" to let the user know that something isn't quite right.

I don't think I'm totally following your thinking for `initOnyx`, but maybe if it was called `initOnyxStorageProviders` (if I understand it correctly), then that might be a route to go as well. I'm not sure how that would change what happens on app load though. Would all Onyx read/write requests get queued until storage is initialized?

**Comment by marcaaron** [comment] 2023-11-22 01:14
Good thoughts! But sorry I did not quite understand the practical differences between the first two proposals @chrispader. 

If we can't initialize the store or run into some other error where the app can't reliably recover then the simplest approach is to just "give up" on reading or writing things (for the life of the JS executing) and use the cache instead. This will force the user to have to log in again if they start a new JS session - but at least the app will work for them.

For the design we have at the moment, the most straightfoward approach is to assume all writes are "mission critical". If one fails then the app cache and storage layer will be out of sync. Does the app recover OK from that? Do we ever want that situation to happen? Without doing a deeper dive, I'd assume unexpected things could happen and the answer is no to both.

>I know that setMemoryOnlyKeys isn't perfect, but this is maybe the chance we need to make it more robust and handle this case where disk storage is unavailable and everything needs to be handled in memory

This is an interesting idea @tgolen. Right now, we have the app pass specific keys. But we could also give the option to use Onyx without persistence by passing a wildcard key like `*`.

Quick shout that this feature was removed and never reimplemented AFAICT in [this PR](https://github.com/Expensify/react-native-onyx/pull/293/files).

We can see the original code and how it is intended to work [here](https://github.com/Expensify/react-native-onyx/pull/270/files) if we want to reimplement it.

>I wonder if we need a third data provider for Onyx which would be an "in memory storage provider" and we could switch over to that when the disk storage providers aren't available?

That's interesting too. Onyx, at this point, feels more like a memory cache solution that is able to persist with a storage provider. Having a "provider" that just returns resolved promises for all the methods makes sense to me.

Do we want to fix "memory only keys"?

>App displays a global banner like "There could be degraded performance, blah blah" to let the user know that something isn't quite right.

The worst of it is that they will have to log in again if they background the app and call OpenApp again.

So, maybe we should decide on if we are OK with having to re-login? Or if we need some other solution. There are alternate options here to store credentials e.g. `localStorage`, the keychain, etc. If we do that the user might not even know that anything is wrong - they'd just be relying on the cache for mostly everything and when they restart the app they'll need to do an `OpenApp`.

**Comment by chrispader** [comment] 2023-11-27 15:47
Going through the discussion and start the implementation tmrw!

**Comment by chrispader** [comment] 2023-12-07 14:29
Started extracting the memory-only persistence part out of the `OnyxCache`, so that we can use it as a separate and "always-working" storage provider.

In the end, the memory-only provider is basically the same as the current mock, which also simplifies this.

**Comment by chrispader** [comment] 2023-12-07 14:30
My idea, was to fallback to memory-only provider if the native/web storage provider fails to initialize, as @marcaaron and @tgolen suggested.

Also looking into the current `setMemoryOnlyKeys` logic, and see what we can improve/extend here.

**Comment by chrispader** [comment] 2023-12-14 13:54
Working on this now!

**Comment by chrispader** [comment] 2023-12-26 12:33
Still working on this PR!

I've mostly extracted all the functionality from `OnyxCache` to a standalone `MemoryOnlyProvider`. Currently i am working on a `MultiStorage` component, which lets us define an array of storage providers with a certain order/priorities. This way, we're able to fallback to the `MemoryOnlyProvider` in case a storage couldn't be initialized and additionally, we can potentially have more than one (platform) storage provider simultaneously.

**Comment by chrispader** [comment] 2023-12-26 19:08
A new possibility with this approach could also be, that we can fallback to another (first-class) storage provider, in case one fails. So we can fallback to a different storage solution, like use `AsyncStorage` in case `SQLite` fails or use some sort of "cookie" store if there are problems with `IDBKeyVal`

**Comment by tgolen** [comment] 2023-12-26 19:53
While that sounds like a good possibility for the future, let's just keep the scope as simple as we need to for this and not over-engineer anything for now. I'm not sure that we need the `MultiStorage` interface at all right now.

**Comment by chrispader** [comment] 2023-12-26 20:33
> While that sounds like a good possibility for the future, let's just keep the scope as simple as we need to for this and not over-engineer anything for now. I'm not sure that we need the `MultiStorage` interface at all right now.

Yes, sure. The extra "fallback" storages are only theoretical. Though what i wanted to achieve with this PR is to basically remove `OnyxCache` completely and handle cache the same as the other storage providers.

Just finished my implementation of this interface. Next steps are just to replace/remove any calls to `OnyxCache` and make sure to maintain the functionality

You can take a look at the current status here: https://github.com/Expensify/react-native-onyx/pull/439

**Comment by chrispader** [comment] 2023-12-27 11:33
> While that sounds like a good possibility for the future, let's just keep the scope as simple as we need to for this and not over-engineer anything for now. I'm not sure that we need the `MultiStorage` interface at all right now.

Actually, you have a point here. I'm going to keep the current implementation of `OnyxCache` in the library for now and just fallback to the `MemoryOnlyProvider`, in case the native storage solution doesn't work.

In a follow-up PR, we can think about removing `OnyxCache` totally, because it's rather redundant, if we just always use the `MemoryOnlyProvider`

**Comment by tgolen** [comment] 2023-12-27 15:30
Does that mean that if the fallback MemoryOnlyProvider is active, then
there will essentially be two in-memory caches?

**Comment by chrispader** [comment] 2023-12-28 10:25
> Does that mean that if the fallback MemoryOnlyProvider is active, then there will essentially be two in-memory caches?

Yes, that was my idea for now. This second `MemoryOnlyProvider` though would only be activated if the main platform storage fails to initialize. If everything works, Onyx would behave just as usual.

The reason for this design is that we can easily replace `OnyxCache` and always enable the `MemoryOnlyProvider` as the "first" storage solution

**Comment by marcaaron** [comment] 2023-12-29 21:36
I think we had some different ideas about what a memory storage provider would do. My initial interpretation (and the PR I expected to see) was that The "memory only provider" would essentially noop and do "nothing".

**Comment by chrispader** [comment] 2024-01-08 12:23
> I think we had some different ideas about what a memory storage provider would do. My initial interpretation (and the PR I expected to see) was that The "memory only provider" would essentially noop and do "nothing".

I understand what you mean. With the new design from the PR we can easily achieve this, by...

- adapting the `MemoryOnlyProvider` to just do nothing and noop (for now)
- create a temporary new provider, that just does nothing at all.

The ultimate idea - and the reason for this new design - is to completely replace `OnyxCache` with this new `MemoryOnlyProvider` as the first/top-priority storage.

This would basically reflect the same behaviour as Onyx is designed right now. For a lot of operations we just set/get/check in the cache and already resolve the operation. Other operations (like `merge`) just update both cache and storage simultaneously. This is what the new design also achieves, though in a more generic way and with the ability to also add additional storage providers.

So the question now is, whether we want to go for this new design at all? I feel like having this unified and clean interface for storage providers is a big improvement and let's us adapt storage solutions more easily in the future.

**Comment by tgolen** [comment] 2024-01-08 15:43
I like the overall thought, but can you explain "create a temporary new provider, that just does nothing at all." more? I'm not sure I understand what this would be or why it's necessary.

**Comment by chrispader** [comment] 2024-01-08 15:47
> I like the overall thought, but can you explain "create a temporary new provider, that just does nothing at all." more? I'm not sure I understand what this would be or why it's necessary.

With this design, instead of adding a second `MemoryOnlyProvider` as fallback which actually stores/retrieves data (and therefore will double the memory footprint) i can just create a storage provider with the same interface, which will just be `() => Promise.resolve()` for every operation.

**Comment by chrispader** [comment] 2024-01-08 15:56
> > I like the overall thought, but can you explain "create a temporary new provider, that just does nothing at all." more? I'm not sure I understand what this would be or why it's necessary.
> 
> With this design, instead of adding a second `MemoryOnlyProvider` as fallback which actually stores/retrieves data (and therefore will double the memory footprint) i can just create a storage provider with the same interface, which will just be `() => Promise.resolve()` for every operation.
> 
> This way, the `Onyx` layer will still succeed because we act as if everything works fine, but in reality, it's only relying on cache...
> 
> I would need to check though, if this is currently doable with all operations in `Onyx.js`

i added the `NoopProvider` here just for showing what i mean: https://github.com/margelo/react-native-onyx/blob/%40chrispader/memory-only-provider/lib/storage/providers/NoopProvider.js

**Comment by marcaaron** [comment] 2024-01-08 20:30
>The ultimate idea - and the reason for this new design - is to completely replace OnyxCache with this new MemoryOnlyProvider as the first/top-priority storage.

While having the cache replaced by a "provider" could be interesting, it doesn't seem to significantly improve the current situation. Too much complexity could also make the code less accessible. So, I'd encourage us to just focus on addressing the issue without assuming that we may need more than that.

That said, if the rest of the team is on board, I don't want to create a roadblock here. Just wanted to share my reservations as I'm still having trouble fully supporting the extra changes.

Here's what I'd do:

- Create a provider that does nothing - basically like a mock provider, but without an internal cache
- Leave the cache as it is
- When storage fails in a way where it can't be recovered switch the storage provider to the provider that noops
- Don't chain providers together in an array. Just switch them out when a unrecoverable error happens.

**Comment by chrispader** [comment] 2024-01-19 13:12
Updated the PR to only contain logic to fallback to the `NoopProvider` and left an explanation here: https://github.com/Expensify/react-native-onyx/pull/439#issuecomment-1900389149

**Comment by marcaaron** [comment] 2024-01-19 20:17
Left a few comments. Seeing as this issue has been unresolved for a while - I would love to maybe revisit a high level analysis of the "problem" (as experienced by users) that we are trying to solve and then a proposal on how it will be fixed (or what other changes to expect) so we can maybe all agree on _what_ we are doing here before spending time on additional reviews?

**Comment by marcaaron** [comment] 2024-01-19 20:19
e.g. unpacking this statement for a second:

>The error that @davidcardoza experienced is presumably thrown by [createStore function call](https://github.com/Expensify/react-native-onyx/blob/2fe9b570e8049ae2379c02916f2440923d08c496/lib/storage/providers/IDBKeyVal.js#L21) in the web storage provider implementation IDBKeyVal

Are we sure that's where the error gets thrown?

**Comment by chrispader** [comment] 2024-01-23 17:37
> Are we sure that's where the error gets thrown?

No we aren't 100%, you're right. I didn't find lots of substantial proof/reason for this error. Anyway, i updated the PR to also handle errors during runtime (after initialization)

**Comment by chrispader** [comment] 2024-04-02 20:41
@tgolen @marcaaron i think we can close this out since the split-up PRs by @kirillzyusko have been merged?

**Comment by tgolen** [comment] 2024-04-02 20:51
I think you're right! I'll close it out.

**Closed by tgolen** 2024-04-02 20:51 UTC
Labels: Monthly
