### ISSUE TITLE
[HOLD for payment 2023-07-05] [$1000] Contact Method -  Email already exist message appears for a second on click of add button

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#20610] opened 2023-06-12 18:12 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Go to settings > profile > contact method
2. Click on new contact method
3. Enter any email and click on Add

## Expected Result:
Email already exist message appears for a second when go to previous screen

## Actual Result:
Should not show email already exist message

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android / native
- [ ] Android / Chrome
- [x] iOS / native
- [ ] iOS / Safari
- [ ] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 1.3.26.1

**Reproducible in staging?:** yes

**Reproducible in production?:** yes

**If this was caught during regression testing, add the test name, ID and link from TestRail:**

**Email or phone of affected tester (no customers):**

**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/93399543/066df17e-aafa-41bc-a0cb-458d526f9600

https://github.com/Expensify/App/assets/93399543/96e16c42-0d94-4686-b22b-566fb3668fd9

**Expensify/Expensify Issue URL:**

**Issue reported by:** @gadhiyamanan

**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1686204823445989

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~012a68d826980a204b</li>
        <li>Upwork Job ID: 1668596757704597504</li>
        <li>Last Price Increase: 2023-06-13</li>
    </ul>
</details>

**Comment by bfitzexpensify** [comment] 2023-06-13 12:30
Reproduced.

**Comment by s-alves10** [comment] 2023-06-13 18:06
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
`Contact Method already exists` message appears for a second when click add button in new contact method page

### What is the root cause of that problem?

When click add button, `User.addNewContactMethodAndNavigate` function is called and `loginList` props is changed inside it. This causes re-render of the `NewContactMethodPage` and `validate` function is newly created. This changes the onValidate of `Form` component and triggers `validate` function again. loginList has already the contact method just input and this is the root cause of the issue.

### What changes do you think we should make in order to solve the problem?

Place the `validate` function inside `useCallback` and set the dependency list to empty array []. Ignoring `props.loginList` is safe because `NewContactMethodPage` is re-mounted every time and `loginList` doesn't change during its lifecycle.

```
    const validate = useCallback((values) => {
        ...
    }, [])
```

This works perfect.

<details>
    <summary>Result</summary>

https://github.com/Expensify/App/assets/126839717/42f3a32b-8ecf-4ab2-a1a5-d5bbe6e18b41


</details>

**Note**:
I found some issues in `NewContactMethodPage` and `Form` component though they are not the bugs. 
`getPhoneLogin` and `validateNumber` function in the `NewContactMethodPage` component isn't needed to be placed inside the component. This causes the both functions instantiated every time component is rendered and have negative impact on performance.
Also refs are not needed to be put in the dependency list because they remains the same over the lifetime of the component.

### What alternative solutions did you explore? (Optional)

**Comment by bfitzexpensify** [comment] 2023-06-16 07:22
@aimane-chnaif please take a look at @s-alves10's proposal when you get a chance - thanks!

**Comment by bfitzexpensify** [comment] 2023-06-19 06:37
Bump @aimane-chnaif

**Comment by aldo-expensify** [comment] 2023-06-21 20:46
Removing @marcochavezf as I think he was assigned in the old process.

**Comment by aldo-expensify** [comment] 2023-06-21 20:46
Assigned to @allroundexperts !

**Comment by bfitzexpensify** [comment] 2023-07-05 10:55
Offers sent out @aimane-chnaif @allroundexperts @gadhiyamanan 

@aimane-chnaif, please complete the BZ checklist when you get a chance - thanks!

**Comment by bfitzexpensify** [comment] 2023-07-06 08:57
Agreed on not needing a regression test step. @gadhiyamanan please accept the reporting job offer on Upwork. Once that's paid out, we'll be all done here.

**Comment by gadhiyamanan** [comment] 2023-07-06 08:59
@bfitzexpensify accepted, thanks!

**Comment by bfitzexpensify** [comment] 2023-07-06 09:01
Thanks. OK, all done here, closing this one out - thanks everyone!

**Closed by bfitzexpensify** 2023-07-06 09:01 UTC
Labels: External, Daily, Awaiting Payment, Bug
