### ISSUE TITLE
Web - Сonsole error on click of connect online with plaid button

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#23194] opened 2023-07-19 20:29 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Create workspace if not created
2. Click on Workspaces in setting in left panel
3. Choose Reimbursement
4. Click the Connect bank account button
5. Click the Connect online with Plaid

## Expected Result:
Verify that it redirect to plaid portal and no error is displayed in console

## Actual Result:
Error displayed in console

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [x] MacOS / Chrome
- [ ] MacOS / Desktop

**Version Number:** 1.3.42.26

**Reproducible in staging?:** Yes

**Reproducible in production?:** Yes

**If this was caught during regression testing, add the test name, ID and link from TestRail:**

**Email or phone of affected tester (no customers):**

**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/78819774/2809ffd1-6b7f-44ad-98f3-c2f6fa1fe593

**Expensify/Expensify Issue URL:** 

**Issue reported by:** Applause - Interanal Team

**Slack conversation:**

**Comment by JmillsExpensify** [comment] 2023-07-26 03:42
I'm actually not able to reproduce this issue.

**Comment by JmillsExpensify** [comment] 2023-08-01 05:22
I still couldn't reproduce. Closing.

**Closed by JmillsExpensify** 2023-08-01 05:22 UTC
Labels: Daily, Overdue, Bug
