### ISSUE TITLE
BUG: Console error while navigating to workspace - reported by @aneequeahmad

### ISSUE THREAD

**Issue by mvtglobally** [Expensify/App#11902] opened 2022-10-17 09:35 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Open settings page
2. Click on any workspace.
3. Navigate to Manage members 
4. Try to add members in workspace who has same profile image/icon

## Expected Result:
No console errors should display

## Actual Result:
Console error displayed 

## Workaround:
unknown 
## Platform:

Where is this issue occurring?

- Web

**Version Number:** 1.2.1-0
**Reproducible in staging?:** need repro
**Reproducible in production?:** need repro 
**Email or phone of affected tester (no customers):** 
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation 

https://user-images.githubusercontent.com/43995119/196143593-5eb32599-c271-465e-a206-8e2e30d6da03.mov

**Expensify/Expensify Issue URL:** 
**Issue reported by:** @aneequeahmad
**Slack conversation:** https://expensify.slack.com/archives/C01GTK53T8Q/p1661464019269279

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by muttmuure** [comment] 2022-10-19 12:58
I've reported this [here](https://expensify.slack.com/archives/C01GTK53T8Q/p1666184222105079)

**Comment by muttmuure** [comment] 2022-10-19 12:59
This should be weekly because we can't add engineering until we reproduce the problem

**Comment by muttmuure** [comment] 2022-10-19 13:32
Hm, can't reproduce

**Comment by mallenexpensify** [comment] 2022-11-04 14:48
Unable to reproduce on Chrome v1.2.23-9, closing

https://user-images.githubusercontent.com/22508304/200003979-59c59e12-3dc1-4339-9680-0631d7648aee.mp4

@mvtglobally or @aneequeahmad please comment if I'm doing something wrong or if you're able to repro.

**Closed by mallenexpensify** 2022-11-04 14:48 UTC
Labels: Daily, Needs Reproduction, Bug
