### ISSUE TITLE
Chat - "Back arrow" works with delay for chat opened from room member's list

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#23412] opened 2023-07-22 20:22 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Open iOS app
2. Open a room (with at least 1 more member in it)
3. Tap on room nam to invoke room details page
4. Tap on members
5. Tap on a member other than yourself
6. Tap on "message "member name""
7. Tap on back arrow in the top left

## Expected Result:
User is immediately transferred to the room page

## Actual Result:
Back arrow works with delay - user is transferred to the room page in 7-13 seconds

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [x] iOS / native
- [ ] iOS / Safari
- [ ] MacOS /  Safari
- [ ] MacOS / Desktop

**Version Number:** 1.3.44.0

**Reproducible in staging?:** Yes

**Reproducible in production?:** No

**If this was caught during regression testing, add the test name, ID and link from TestRail:**

**Email or phone of affected tester (no customers):**

**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/78819774/3fcab446-25ac-4920-aebb-305e04d68abf

**Expensify/Expensify Issue URL:**

**Issue reported by:** Applause - Internal Team

**Slack conversation:**

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by mountiny** [comment] 2023-07-24 13:55
I cannot repro cc @lanitochka17 @isagoico @kavimuru Can you please double check if you can still repro?

**Comment by lanitochka17** [comment] 2023-07-24 15:57
@mountiny Issue is not reproduced. Build 1.3.44.0
Iphone 14 Pro Max/ios16.5

https://github.com/Expensify/App/assets/78819774/9e9588f9-1a1f-4693-90c8-edb7dd31571b

**Comment by marcaaron** [comment] 2023-07-24 18:50
Interesting so - since this is not reproducible anymore I think we can remove the blocker. Though - I feel like there might be some performance issue happening here. Can we test out how this works when the room has a lot of members or a lot of chats? _Something_ happened to make this slow. And a reported lag of 7-13 seconds is fairly serious.

**Comment by marcaaron** [comment] 2023-07-24 18:53
One thing that I'd recommend we do here is add timing logs and maybe try to figure out some way to alert when this is really slow. Also would be good to include additional params like number of comments on the chat they are navigating back to, number of members in the chat, etc.

**Comment by sakluger** [comment] 2023-07-25 01:02
I'm not the right person to help reproduce this. As an AM, my app is incredibly slow in lots of scenarios.

I do like the idea to add timing logs to find slow processes in general.

**Comment by sakluger** [comment] 2023-07-27 23:39
It seems that we can't reproduce this and we're working on a bunch of other changes to improve performance, so I'm going to close this issue out for now.

**Closed by sakluger** 2023-07-27 23:39 UTC
Labels: Daily, Overdue, Bug
