### ISSUE TITLE
Paypal option is missing when user edit and delete old Paypal username in offline mode

### ISSUE THREAD

**Issue by kavimuru** [Expensify/App#23419] opened 2023-07-23 16:39 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. go to setting > payments
2. click on add payment method option
3. select Paypal option
4. add Paypal  account
5. go to offline
6. click on Paypal account and choose edit option
7. edit Paypal username
8. delete Paypal account
9. go back to online
## Expected Result: 
Paypal option does not show even after reload the page
## Actual Result:
 should show Paypal option

## Workaround:
Can the user still use Expensify without this being fixed? Have you informed them of the workaround?

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [x] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 1.3.44-0
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/43996225/7f19af7c-8201-4da6-a54b-ecb550ab623a

https://github.com/Expensify/App/assets/43996225/fa75755d-df6a-460e-9e08-508e4004333a

**Expensify/Expensify Issue URL:**
**Issue reported by:** @gadhiyamanan 
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1690011725952869

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by joekaufmanexpensify** [comment] 2023-07-24 12:31
Yep, agreed. Closing as this is a dupe of https://github.com/Expensify/App/issues/22064

**Closed by joekaufmanexpensify** 2023-07-24 12:31 UTC
Labels: Daily, Bug
