### ISSUE TITLE
Web - user's mail address is shown instead of group workspace name in tooltip

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#21434] opened 2023-06-23 17:40 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Go to settings -> workspace-> create new workspace
2. Add/ invite a new user say " user !" to the newly created workspace
3. Notice on LHN, "user 1" avatar is shown in joint with a rectangular workspace avatar
4. Hover over the rectangular workspace avatar
5. Notice that on tooltip, user 1's mail address is shown.

## Expected Result:
On hover over the workspace avatar, corresponding workspace details should be shown on tooltip

## Actual Result:
 User's mail address is shown instead of group workspace name in tooltip

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [x] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 1.3.28-5 

**Reproducible in staging?:** y

**Reproducible in production?:** y

**If this was caught during regression testing, add the test name, ID and link from TestRail:**

**Email or phone of affected tester (no customers):**

**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/93399543/bf8e6dd4-5ef1-4551-bb91-2daedd39b9d1

https://github.com/Expensify/App/assets/93399543/0cfc6f69-2938-4198-b9a1-89965f6bfd4f

**Expensify/Expensify Issue URL:**

**Issue reported by:** @ashimsharma10

**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1686932000215219

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by shawnborton** [comment] 2023-06-23 18:54
Hmm I don't think this is actually a bug. Thoughts @JmillsExpensify @trjExpensify ? The tldr; is that with our new avatar style that shows user avatar with a small workspace icon in the corner, I would expect that whole area to show a tooltip for the user and not the avatar. I mean we could try to make it so that hovering over the user part is the user's tooltip, and over the workspace avatar is the workspace tooltip... but I think I would just close this out.

**Comment by alitoshmatov** [comment] 2023-06-23 19:16
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
Web - user's mail address is shown instead of group workspace name in tooltip
### What is the root cause of that problem?
https://github.com/Expensify/App/blob/66915aca0ba378607298c9d9740e8bfdcb4ea50f/src/components/SubscriptAvatar.js#L72
We are setting avatar container position to absolute which is making parent view's height 0. That is why tooltip is not working.
### What changes do you think we should make in order to solve the problem?
We should apply styles to `View` component which wraps `Avatar` component. We should just need to move styles from avatar's `containerStyles` to parent View's style 

Also we should update user, avatar to use `UserDetailsTooltip` to keep up with new design
### What alternative solutions did you explore? (Optional)

**Comment by alitoshmatov** [comment] 2023-06-23 19:19
@shawnborton it looks like this feature was implemented but there was small mistake which prevented it from actually working.

**Comment by trjExpensify** [comment] 2023-06-23 20:13
>The tldr; is that with our new avatar style that shows user avatar with a small workspace icon in the corner, I would expect that whole area to show a tooltip for the user and not the avatar. I mean we could try to make it so that hovering over the user part is the user's tooltip, and over the workspace avatar is the workspace tooltip... but I think I would just close this out.

I agree, I think the whole area should be for the user.

**Comment by ashimsharma10** [comment] 2023-06-24 13:11
Might not be a bug tho. 
But as a new feature, showing tooltip for workspace wouldn't be that bad either, I think

**Comment by CortneyOfstad** [comment] 2023-06-26 13:55
Reviewing the thread, and to confirm, we feel that this is not a bug and can be closed? TIA!

**Comment by CortneyOfstad** [comment] 2023-06-29 12:39
Bump on my above comment

**Comment by shawnborton** [comment] 2023-06-29 16:30
Yeah, I think we can close this one out.

**Closed** 2023-06-30 15:16 UTC
Labels: Daily, NewFeature, Bug
