### ISSUE TITLE
[PAID] Android & iOS - Distance - Icon in the center button is off-centered

### ISSUE THREAD

**Issue by m-natarajan** [Expensify/App#44074] opened 2024-06-20 12:37 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.86-0
**Reproducible in staging?:** y
**Reproducible in production?:** n
**If this was caught during regression testing, add the test name, ID and link from TestRail:** N/A
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** Applause internal team
**Slack conversation:**

## Action Performed:
1. Launch New Expensify app.
2. Go to FAB > Submit expense > Distance.

## Expected Result:
The icon in the center button will be centered.

## Actual Result:
The icon in the center button is off-centered.

## Workaround:
unknown
## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [ ] Android: mWeb Chrome
- [x] iOS: Native
- [ ] iOS: mWeb Safari
- [ ] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos
![Bug6519287_1718879892057!IMG_B050280F63D0-1](https://github.com/Expensify/App/assets/38435837/dbb42d4c-62f2-461f-91aa-6486a8f81d50)

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Issue Owner</summary>Current Issue Owner: @strepanier03</details>

**Comment by m-natarajan** [comment] 2024-06-20 12:41
@mountiny FYI I haven't added the External label as I wasn't 100% sure about this issue. Please take a look and add the label if you agree it's a bug and can be handled by external contributors

**Comment by m-natarajan** [comment] 2024-06-20 12:42
We think that this bug might be related to #wave-collect - Release 1

**Comment by neonbhai** [comment] 2024-06-20 13:15
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
Android & iOS - Distance - Icon in the center button is off-centered

### What is the root cause of that problem?
We have an extra margin applied to the icon here

https://github.com/Expensify/App/blob/9a6019a4525422618cb0258da0549dd83cbc605c/src/components/MapView/MapView.tsx#L239-L245

which isn't compensated for in this centered icon here:
https://github.com/Expensify/App/blob/9a6019a4525422618cb0258da0549dd83cbc605c/src/components/Button/index.tsx#L245





### What changes do you think we should make in order to solve the problem?
We will pass `styles.ml1` as `iconStyles` [here](https://github.com/Expensify/App/blob/9a6019a4525422618cb0258da0549dd83cbc605c/src/components/MapView/MapView.tsx#L239-L2450):

```jsx
iconStyles={styles.ml1}
```

**Comment by mountiny** [comment] 2024-06-20 15:37
I think this is coming from https://github.com/Expensify/App/pull/43452 @truph01

**Comment by truph01** [comment] 2024-06-20 17:35
@mountiny Sure. I am checking it

**Comment by mountiny** [comment] 2024-06-20 20:25
for now I have created a draft with the suggestion from @neonbhai going to test it on the adhoc build https://github.com/Expensify/App/pull/44117

**Comment by mountiny** [comment] 2024-06-24 08:44
$50 to @neonbhai for providing the solution

**Comment by neonbhai** [comment] 2024-07-01 20:03
@strepanier03 bump to finish payment here according to https://github.com/Expensify/App/issues/44074#issuecomment-2185943149 and close the issue!

**Comment by strepanier03** [comment] 2024-07-02 19:04
### Payment Summary

- [ ] $50 to @neonbhai via Upwork ([offer](https://www.upwork.com/nx/wm/offer/102963226))

**Comment by neonbhai** [comment] 2024-07-02 19:12
Thank you @strepanier03. Accepted the offer!

**Closed** 2024-07-02 21:33 UTC
Labels: Engineering, Daily, Awaiting Payment, Bug
