### ISSUE TITLE
[$1000] Creating thread of a message in pinned workspace channel automatically pins the thread

### ISSUE THREAD

**Issue by kavimuru** [Expensify/App#19489] opened 2023-05-23 20:49 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:

1. send a message in pinned workspace channel
2. reply in thread
3. see the thread in LHN

## Expected results: 
should maintain consistency in both chat and workspace channel
## Actual results: 
creating thread of a message in pinned workspace channel automatically pins the thread, same doesn't happen for a normal pinned chat, no consistency is there

## Workaround:
Can the user still use Expensify without this being fixed? Have you informed them of the workaround?

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [x] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 1.3.17-0
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/43996225/d397e55e-9b68-45cf-b7ce-68ceb66e3fa4

https://github.com/Expensify/App/assets/43996225/01d49528-2d73-47f5-90ac-0acfc5890f15

**Expensify/Expensify Issue URL:**
**Issue reported by:** @chiragxarora
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1684603831084649

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01d85ae4e803e87e01</li>
        <li>Upwork Job ID: 1661396483858509824</li>
        <li>Last Price Increase: 2023-06-07</li>
    </ul>
</details>

**Comment by bfitzexpensify** [comment] 2023-05-24 15:39
Reproduced

**Comment by dukenv0307** [comment] 2023-05-25 04:37
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
Creating thread of a message in workspace channel automatically pins the thread
### What is the root cause of that problem?
When create a optimistic chat report for new thread we set `isPinned` is true if `reportName` is admin room. So that a thread that is created from a message of workspace admin is automatically pins
https://github.com/Expensify/App/blob/7a42755a79737314edf702ce17bf0647dd8c41fb/src/libs/ReportUtils.js#L1569

### What changes do you think we should make in order to solve the problem?
Because we need to set `isPinned` as `true` for workspace admin chat, we should add a flag `isThread` with the default value is `false` in `buildOptimisticChatReport` to know report being created is a thread or not
```
function buildOptimisticChatReport(
    participantList,
    reportName = CONST.REPORT.DEFAULT_REPORT_NAME,
    chatType = '',
    policyID = CONST.POLICY.OWNER_EMAIL_FAKE,
    ownerEmail = CONST.REPORT.OWNER_EMAIL_FAKE,
    isOwnPolicyExpenseChat = false,
    oldPolicyName = '',
    visibility = undefined,
    notificationPreference = CONST.REPORT.NOTIFICATION_PREFERENCE.ALWAYS,
    parentReportActionID = '',
    parentReportID = '',
    isThread = false,
)
```

Update this line to: `isPinned: reportName === CONST.REPORT.WORKSPACE_CHAT_ROOMS.ADMINS && !isThread,`. 

https://github.com/Expensify/App/blob/7a42755a79737314edf702ce17bf0647dd8c41fb/src/libs/ReportUtils.js#L1569

And then in `navigateToAndOpenChildReport` function, call `buildOptimisticChatReport` function with isThread parameter is `true`:
```
const newChat = ReportUtils.buildOptimisticChatReport(
      formattedUserLogins,
      lodashGet(parentReportAction, ['message', 0, 'text']),
      '',
      CONST.POLICY.OWNER_EMAIL_FAKE,
      CONST.POLICY.OWNER_EMAIL_FAKE,
      false,
      '',
      undefined,
      CONST.REPORT.NOTIFICATION_PREFERENCE.ALWAYS,
      parentReportAction.reportActionID,
      parentReportID,
      true
  );
```
https://github.com/Expensify/App/blob/7a42755a79737314edf702ce17bf0647dd8c41fb/src/libs/actions/Report.js#L456
### What alternative solutions did you explore? (Optional)

**Comment by brianlee1025** [comment] 2023-05-25 04:48
## Proposa

### Please re-state the problem that we are trying to solve in this issue.
Threads that are generated from pinned chat channel are not automatically pinned.

### What is the root cause of that problem?

The issue happens while creating a new child report here.
https://github.com/Expensify/App/blob/7a42755a79737314edf702ce17bf0647dd8c41fb/src/libs/actions/Report.js#L456C1-L468

As you can see below, the isPinned config is only check if the report is a workspace type regardless of the report pinned status.
https://github.com/Expensify/App/blob/7a42755a79737314edf702ce17bf0647dd8c41fb/src/libs/ReportUtils.js#L1569

### What changes do you think we should make in order to solve the problem?
Adding one additional checking during buildOptimisticChatReport as shown below. By doing so, it will always follow the pinned status of parent report. 
`isPinned: reportName === CONST.REPORT.WORKSPACE_CHAT_ROOMS.ADMINS || isReportPinned(parentReportID),`

where by the isReportPinned looks something like this,

`` `function isReportPinned(reportID) {
return lodashGet(allReports, `${ONYXKEYS.COLLECTION.REPORT}${reportID}.isPinned`, false);
}` ``

### What alternative solutions did you explore? (Optional)
N/A

**Comment by bfitzexpensify** [comment] 2023-05-29 07:44
@eVoloshchak couple of proposals for you to review

**Comment by eVoloshchak** [comment] 2023-05-30 16:59
I think we need to clarify what is the expected behavior here

1. Creating a thread in pinned channel/chat automatically pins the thread
2. Created thread isn't pinned no matter if parent channel/chat was pinned or not

@pecanoro, could you chime in on this, please?

**Comment by pecanoro** [comment] 2023-05-30 17:51
@eVoloshchak Sure, let me ask internally what's the expected behaviour!

**Comment by pecanoro** [comment] 2023-06-02 14:17
Ok, we decided that the correct behaviour is 2: "Created thread isn't pinned no matter if parent channel/chat was pinned or not"

**Comment by eVoloshchak** [comment] 2023-06-06 18:18
Reviewing the proposals tomorrow

**Comment by pecanoro** [comment] 2023-06-07 14:58
@eVoloshchak Don't forget to review the proposals when you have some time today!

**Comment by eVoloshchak** [comment] 2023-06-07 21:36
@eh2077's [proposal](https://github.com/Expensify/App/issues/19489#issuecomment-1573880404) looks good to me
Looks like both @eh2077 and @dukenv0307 have posted similar updated proposals that are only a couple of minutes apart, but @eh2077 was first
Btw, how do we implement the backend changes? 

🎀👀🎀 C+ reviewed!
@pecanoro

**Comment by eh2077** [comment] 2023-06-08 01:41
> > We can also set isPinned to false in this line
> 
> @eVoloshchak @eh2077's proposal set `isPinned` to false in this line but I think it shouldn't always to be false and the RCA should be both FE and BE implement wrong.
> 
> https://github.com/Expensify/App/blob/7a42755a79737314edf702ce17bf0647dd8c41fb/src/libs/ReportUtils.js#L1569

I meant when creating a thread report based on the contextual.

**Comment by pecanoro** [comment] 2023-06-08 13:58
I will fix the back end and @eh2077 can fix the optimistic action on the App repo.

**Comment by chiragxarora** [comment] 2023-06-08 15:39
https://github.com/Expensify/App/assets/54641656/6a8ca860-5d56-498d-a739-c30b7ca18d9c

just checked in both staging and prod, bug is present

**Comment by pecanoro** [comment] 2023-06-08 15:46
I tried on main (dev) and it seems to be working just fine. I will retest again.

**Comment by abekkala** [comment] 2023-06-08 16:12
Ok - @pecanoro Stevie was not able to recreate

**Comment by pecanoro** [comment] 2023-06-08 16:35
I can replicate this on staging and production, but no matter how much I try on dev, I think the bug is gone.

**Comment by pecanoro** [comment] 2023-06-08 16:35
So let's hold until the next back-end deploy and we can confirm.

**Comment by pecanoro** [comment] 2023-06-12 17:04
Ok, I can reproduce this still on staging. I wonder though why I can't on dev. Either way, let's continue with the proposed plan

**Comment by chiragxarora** [comment] 2023-06-12 17:07
Has the backend had a recent release?

**Comment by bfitzexpensify** [comment] 2023-06-13 11:41
@eh2077 please let us know when the PR is ready for review! Thanks

**Comment by eh2077** [comment] 2023-06-13 13:02
> @eh2077 please let us know when the PR is ready for review! Thanks

@bfitzexpensify I should but I just tested on **_dev_** branch and found that I can't reproduce it, see below video FYI


https://github.com/Expensify/App/assets/117511920/1b64e3ca-6137-4bfb-bd56-5e044315c059


@pecanoro I just reproduced it on latest dev, see below video FYI


https://github.com/Expensify/App/assets/117511920/35bd5ca0-86b3-4cc7-80db-56ec00240fec

Below is my preference setting without enabling `Use Staging Server`

<img width="100" alt="Screenshot 2023-06-13 at 8 57 49 PM" src="https://github.com/Expensify/App/assets/117511920/e84e7699-fdda-4496-be9c-566cdf17d09e">

If you can also reproduce it on dev today, can I just wait for backend fix and check the optimistic action on App again later?

**Comment by pecanoro** [comment] 2023-06-14 00:41
> f you can also reproduce it on dev today, can I just wait for backend fix and check the optimistic action on App again later?

Yeah, I will take another look at the back-end again and see if I can reproduce since without being able to reproduce, I am having a hard time figuring out where it's getting pinned haha

**Comment by eh2077** [comment] 2023-06-15 02:35
https://github.com/Expensify/App/issues/20777 is similar to this one

**Comment by spcheema** [comment] 2023-06-15 02:44
@pecanoro backend is returning 'isPinned: true' due to that it's happening.

**Comment by pecanoro** [comment] 2023-06-16 22:58
I had a pretty busy week so I am fixing this next week, we will count the bounty after I have a PR merged for the back-end.

**Comment by pecanoro** [comment] 2023-06-21 00:34
Looking into this again tomorrow or Thursday!

**Comment by pecanoro** [comment] 2023-06-28 00:49
I started looking into this today again, I will have an update hopefully tomorrow!

**Comment by pecanoro** [comment] 2023-06-30 18:13
I swear I can't reproduce this on my dev but it still happens on staging.

**Comment by pecanoro** [comment] 2023-06-30 18:30
Nvm everyone, I finally saw the problem, I could not reproduce it on dev because this only happens for non-Expensify domains.

**Comment by pecanoro** [comment] 2023-06-30 19:12
Created an internal PR to fix the problem in our back-end!

**Comment by pecanoro** [comment] 2023-07-06 17:45
Internal fixed has been deployed, do we need any front-end changes?

**Comment by eh2077** [comment] 2023-07-07 02:58
@pecanoro I can't reproduce it on main anymore. I also tested offline mode and it works well too. So, I think we don't frontend fix.

cc @eVoloshchak

**Comment by bfitzexpensify** [comment] 2023-07-10 12:28
Hey @eh2077 and @eVoloshchak — even though we went with a back-end fix here, we appreciate your contribution here in identifying the root cause, so we'd like to pay you a bonus of $250 for the help. 

@eh2077, please apply at https://www.upwork.com/jobs/~0149c464ecb6badead. @eVoloshchak, you can also apply there if you'd like — I know you've been getting paid via New Dot so feel free to request payment there if you want.

**Comment by bfitzexpensify** [comment] 2023-07-10 12:34
Yes, sorry @chiragxarora - please also apply at https://www.upwork.com/jobs/~0149c464ecb6badead

**Comment by bfitzexpensify** [comment] 2023-07-10 13:20
Sweet. @eh2077 invited you. 

@chiragxarora accepted and paid out.

**Comment by eh2077** [comment] 2023-07-10 13:37
@bfitzexpensify  Accepted the offer, thanks!

**Comment by eVoloshchak** [comment] 2023-07-10 16:56
Thanks!
Requested the payment via NewDot

**Comment by bfitzexpensify** [comment] 2023-07-11 08:38
Sweet. OK, we're all done here, thanks for the help everyone. Closing this out.

**Closed by bfitzexpensify** 2023-07-11 08:38 UTC
Labels: Reviewing, Daily, Internal, Bug
