### ISSUE TITLE
[$500] Workspace - Two different IOUs are created

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#35961] opened 2024-02-06 21:18 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.37.0
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** Applause - Internal Team
**Slack conversation:**

**Issue found when executing PR** https://github.com/Expensify/App/pull/34092
## Action Performed:
1. Create a workspace
2. Open the workspace chat
3. Create a distance split IOU from the composers + button with any destinations
4. Open both IOU details

## Expected Result:
There should be only one IOU
The map should be visible

## Actual Result:
Two different IOUs appeared.
The map isn't showing on any of them

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [x] Android: mWeb Chrome
- [x] iOS: Native
- [x] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details> 

https://github.com/Expensify/App/assets/78819774/b5f867ab-e033-4e14-bc9b-d52cd8853d12

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01e854e11c780c2016</li>
        <li>Upwork Job ID: 1754978018595680256</li>
        <li>Last Price Increase: 2024-02-27</li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @neil-marcellini</details>

**Comment by lanitochka17** [comment] 2024-02-06 21:19
We think that this bug might be related to #wave6
CC @greg-schroeder

**Comment by nebiyuelias1** [comment] 2024-02-07 08:51
Can't repro this bug. I can see the map.

**Comment by rojiphil** [comment] 2024-02-07 11:06
## Proposal

### Please re-state the problem that we are trying to solve in this issue.

When `Split bill` is used in a Workspace Chat, distance money request can be generated which creates inconsistency. 

### What is the root cause of that problem?

[Here](https://github.com/Expensify/App/blob/f6ba751301d6a6f4e5faa092e615d49fb02d2746/src/pages/iou/request/IOURequestStartPage.js#L114), we check if `distance` request tab should be shown. And, currently, we show the `distance` request tab for Workspace Chat (aka policy expense chat). However, we allow generating split bill requests for only `manual` and `scan` request types. Since we can attempt split bill generation via the menu option for workspace chats, we do not check if the `ioutType` is `split` for workspace chats. I think this is the root cause.

### What changes do you think we should make in order to solve the problem?

We can solve this problem by not showing the `Distance` tab when `iouType` is of `split` type like this [here](https://github.com/Expensify/App/blob/f6ba751301d6a6f4e5faa092e615d49fb02d2746/src/pages/iou/request/IOURequestStartPage.js#L114).

    const shouldDisplayDistanceRequest = (isExpenseChat && iouType !== CONST.IOU.TYPE.SPLIT) || isExpenseReport || isFromGlobalCreate;

### What alternative solutions did you explore? (Optional)

Alternatively, if we want to support generation of split bill request for `distance` request type, we will have to update `createTransaction` [here](https://github.com/Expensify/App/blob/f6ba751301d6a6f4e5faa092e615d49fb02d2746/src/pages/iou/request/step/IOURequestStepConfirmation.js#L240) for the case of `distance request type and `split` as iou type which is currently missing. Also, I think BE changes may be required as we are adding a new feature. Also, other FE changes would be required. Based on the feedback on this, we can decide on further steps.

**Comment by rojiphil** [comment] 2024-02-07 11:13
@laurenreidexpensify @greg-schroeder 

Can we confirm the expected behavior here? 
Unlike the mentioned expected behavior in OP, it looks like we should not be showing the `distance` tab when the `split bill` is initiated via the menu. 
The reason why I think so is that we do not have any support for generating split bills for `distance` requests. 
Instead, we only support split bills for `manual` and `scan` request types.

**Comment by laurenreidexpensify** [comment] 2024-02-15 16:42
I have done a really poor job of reviewing this properly due to competing priorities - I will be looking at this in depth tomorrow (Fri 16 Feb) and confirming how we move it forward, and how it overlaps with Wave 6

**Comment by laurenreidexpensify** [comment] 2024-02-16 18:32
Hey @rojiphil - I checked with the team and we support bill splits for distance requests, just like any other expense.

**Comment by laurenreidexpensify** [comment] 2024-02-19 17:30
Another quick point here @rojiphil - we should be showing the map

**Comment by laurenreidexpensify** [comment] 2024-02-19 17:30
@eVoloshchak can you take a look at the proposal above? thanks

**Comment by laurenreidexpensify** [comment] 2024-02-23 16:32
@rojiphil bump if you have a chance to do that update to your proposal :)

**Comment by rojiphil** [comment] 2024-02-23 16:35
> @rojiphil bump if you have a chance to do that update to your proposal :)

Apologies for the delay. I will update the proposal today

**Comment by rojiphil** [comment] 2024-02-23 20:15
## Proposal

[Updated](https://github.com/Expensify/App/issues/35961#issuecomment-1931809353) to support split bill generation for distance requests in workspace chats
cc @eVoloshchak

**Comment by rojiphil** [comment] 2024-02-23 20:27
> There should be only one IOU

@laurenreidexpensify
As I understand, we generate two previews for split bills.  So, I am not sure why OP expects only one IOU here.
Maybe this came up as we show only one preview initially for scan requests until the scanning operation completes in the server following which the split bill generation is completed. But distance requests do not have an intermediate step like this. 
What do you think about this?

**Comment by rojiphil** [comment] 2024-02-27 16:56
Seems like this issue also falls within the larger plan of P2P-Distance requests-Frontend [here](https://docs.google.com/document/d/15GQhipcqOJ69MbFA54KRUcWxjICURHYcfTlAb3eaVEQ/edit)
So curious to know what you think of the [proposal](https://github.com/Expensify/App/issues/35961#issuecomment-1931809353) here as this issue also needs BE support. 
cc @neil-marcellini @koko57

**Comment by laurenreidexpensify** [comment] 2024-02-29 05:33
@neil-marcellini could you take a look - https://github.com/Expensify/App/issues/35961#issuecomment-1967119690 -thanks

**Comment by laurenreidexpensify** [comment] 2024-03-04 05:33
@neil-marcellini adding you for feedback on https://github.com/Expensify/App/issues/35961#issuecomment-1967119690

**Comment by neil-marcellini** [comment] 2024-03-04 19:26
@laurenreidexpensify thanks for assigning me, that makes it way more visible! I think that we should close this issue, given that we **do not** actually support splits for distance requests yet. We're building that out with the [P2P distance requests project](https://github.com/orgs/Expensify/projects/73/views/10), and once that's done it will work properly.


The reason the option shows in app now is that we figured it wasn't worth the effort to hide the option given that we'll make it work soon. That's a bit controversial and I'm open to hiding split for distance until it's working.

**Closed** 2024-03-05 05:31 UTC
Labels: External, Engineering, Daily, Help Wanted, Bug
