### ISSUE TITLE
Web -  Add new payment method popover overlaps button after deleting PayPal id

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#26001] opened 2023-08-26 18:22 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Go to settings -> payments
2. Add a paypal payment method.
3. Click on the paypal method.
4. Position the cursor over the add payment method button
5. Press enter to delete
6. Immediately, click on add new payment button (within 2 seconds)

## Expected Result:
 The add payment method list should be displayed above the button.

## Actual Result:
The add payment method lost overlaps with the button due to paypal option.

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [x] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 1.3.57.5
**Reproducible in staging?:** n/a
**Reproducible in production?:** n/a
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/93399543/38e21852-da8c-473c-b0f7-ebf775748090

**Expensify/Expensify Issue URL:**
**Issue reported by:** @esh-g
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1690648417605749

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by akinwale** [comment] 2023-08-27 06:43
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
The add new payment method popover overlaps when the confirm delete dialog is shown for the PayPal payment method.

### What is the root cause of that problem?
There is no logic to either block the payment method list from showing, or to hide the confirm dialog after clicking the add payment method button.

### What changes do you think we should make in order to solve the problem?
Two options.

Solution 1
Hide the confirm delete dialog if the user clicks the add payment method button.

Solution 2
Do not display the payment methods list if the confirm delete dialog is visible when a user clicks on the add payment method button.

### What alternative solutions did you explore? (Optional)
None.

**Comment by AmjedNazzal** [comment] 2023-08-28 16:23
## Proposal

### Please re-state the problem that we are trying to solve in this issue.

Web - Add new payment method popover overlaps button after deleting PayPal id

### What is the root cause of that problem?

We are facing a similar issue as we did before, the reason this is happening is react-native's onLayout which is a great thing to use for certain areas but it doesn't handle updates to components well as it's pretty slow, so what is happening here is that it's not updating the popoverHeight quickly enough for the position of the popover to be calculated correctly. essentially the calculation is happening using the popoverHeight that was calculated before paypal option was added back into the list.

https://github.com/Expensify/App/blob/08c2f5dc656674cdf62bff467edccf49238e277e/src/components/PopoverWithMeasuredContent.js#L151-L153

### What changes do you think we should make in order to solve the problem?

What we can do is adding a fallback calculation code in case onLayout doesn't update quickly enough to avoid having these issues.

We can add ref to keep track of updates in the popoverHeight and the length of the list.

```javascript
const prevPopoverHeightRef = useRef(popoverHeight);
const prevChildrenLengthRef = useRef(lodashGet(props, 'children.props.children[1].length', 0));
```
We then can implement the manual fallback calculation and ref updating in the adjustedAnchorPosition function.

```javascript
const childrenLength = lodashGet(props, 'children.props.children[1].length', 0);
if (prevPopoverHeightRef.current === popoverHeight && childrenLength !== prevChildrenLengthRef.current) {
    if(props.anchorRef.current){
        const fallbackMargin = lodashGet(props, 'anchorRef.current.attributeStyleMap.size', 0);
        const childHeight = lodashGet(props, 'anchorRef.current.offsetHeight', 0);;
        const fallbackHeight = (childHeight + fallbackMargin) * childrenLength + fallbackMargin;
        setPopoverHeight(fallbackHeight);
    }
}
prevPopoverHeightRef.current = popoverHeight;
prevChildrenLengthRef.current = childrenLength;
```

### Result

https://github.com/Expensify/App/assets/74202751/d8d00edf-4282-454d-89d3-19fbeb6dc645

**Comment by stephanieelliott** [comment] 2023-08-29 15:26
I'm either not able to reproduce this, or it's only occurring at certain browser dimensions. 

But also: 

> Position the cursor over the add payment method button
> Press enter to delete
> Immediately, click on add new payment button (within 2 seconds)

This portion feels extremely edge-case. Realistically, no one is going to be adding and deleting payment methods in rapid succession like that, and especially so considering it's PayPal (which is hardly used in Expensify, so much so that it was sunsetted on olddot). So gonna close this, I don't think it's worth prioritizing at this time.

**Closed by stephanieelliott** 2023-08-29 15:26 UTC
Labels: Daily, Needs Reproduction, Overdue, Bug
