### ISSUE TITLE
[HOLD for payment 2023-10-05] [$500] Category IOU - Two categories are highlighted in the search result when only one is selected

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#27354] opened 2023-09-13 14:14 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___
**Issue found when executing PR** https://github.com/Expensify/App/pull/26501
## Action Performed:
1. Go to staging.new.expensify.com
2. Go to the workspace chat as the invited member
3. Go to + > Request money
4. Enter an amount > Next
5. Select Insurance
6. Click on the Category
7. On the search field, type C

## Expected Result:
Only the selected category, which is Insurance, is highlighted

## Actual Result:
Both Home office and Insurance are highlighted

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android / native
- [x] Android / Chrome
- [x] iOS / native
- [x] iOS / Safari
- [x] MacOS / Chrome / Safari
- [x] MacOS / Desktop

**Version Number:** 1.3.69-0

**Reproducible in staging?:** Yes

**Reproducible in production?:** No

**If this was caught during regression testing, add the test name, ID and link from TestRail:**

**Email or phone of affected tester (no customers):**

**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/78819774/badbec38-31fc-4dbb-b475-798050624f24

**Expensify/Expensify Issue URL:**

**Issue reported by:** Applause - Internal Team

**Slack conversation:**

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01b3dde11988e4b011</li>
        <li>Upwork Job ID: 1701985281591398400</li>
        <li>Last Price Increase: 2023-09-13</li>
    </ul>
</details>

**Comment by bondydaa** [comment] 2023-09-13 15:45
whoops sorry for the noise adele, i added a bunch of labels at once and think i hit a race condition.

**Comment by Pluto0104** [comment] 2023-09-13 15:50
how can I reproduce this on dev? I have tried to change Permission file but it's not working.

**Comment by ishpaul777** [comment] 2023-09-13 15:53
Category is a beta feature @bondydaa, can you add my email to beta list, so I can investigate further?

> email- ishpaul207@gmail.com

**Comment by Pujan92** [comment] 2023-09-13 15:54
I think related to this [PR](https://github.com/Expensify/App/pull/26501)

**Comment by bondydaa** [comment] 2023-09-13 16:14
going to remove help wanted for now until we are clear if that PR will fix or not, maybe we include a fix there or decide to fix in a new one.

**Comment by bondydaa** [comment] 2023-09-13 16:48
okay looks like b/c this is behind a beta we'll have @rezkiy37 handle these then https://expensify.slack.com/archives/C01GTK53T8Q/p1694623628867629?thread_ts=1694621414.765469&cid=C01GTK53T8Q

**Comment by rezkiy37** [comment] 2023-09-13 16:49
Hi, I’m Michael (Mykhailo) from Callstack and I would like to work in this issue, because I am the author of [the broken PR](https://github.com/Expensify/App/pull/26501).

**Comment by rezkiy37** [comment] 2023-09-14 18:40
Working on the issue. Trying to have a proper initial focus index for all scenarios for the categories list.

**Comment by rezkiy37** [comment] 2023-09-28 09:16
Are we going to close this issue?

**Comment by bondydaa** [comment] 2023-09-28 09:18
it should close once the PR is fully deployed to prod, looks like it's only on staging right now?

**Comment by rezkiy37** [comment] 2023-09-28 11:07
> it should close once the PR is fully deployed to prod, looks like it's only on staging right now?

Got it. Yep, looks like it is only on staging now.

**Comment by anmurali** [comment] 2023-10-11 02:47
No one needs to be paid here. @burczu can you please add a regression test plan?

**Comment by burczu** [comment] 2023-10-17 06:20
**BugZero Checklist:** The PR fixing this issue has been merged! The following checklist ([instructions](https://stackoverflow.com/c/expensify/questions/14574)) will need to be completed before the issue can be closed:

* [x]  [@burczu] The PR that introduced the bug has been identified. Link to the PR: https://github.com/Expensify/App/pull/26501
* [x]  [@burczu] The offending PR has been commented on, pointing out the bug it caused and why, so the author and reviewers can learn from the mistake. Link to comment: Not necessary, it was fixed by the author of the original PR itself.
* [x]  [@burczu] A discussion in #expensify-bugs has been started about whether any other steps should be taken (e.g. updating the PR review checklist) in order to catch this type of bug sooner. Link to discussion: n/a
* [x]  [@burczu] Determine if we should create a regression test for this bug.
* [x]  [@burczu] If we decide to create a regression test for the bug, please propose the [regression test](https://github.com/Expensify/App/blob/main/contributingGuides/REGRESSION_TEST_BEST_PRACTICES.md) steps to ensure the same bug will not reach production again.
* [ ]  [@anmurali] Link the GH issue for creating/updating the regression test once above steps have been agreed upon:

**Closed** 2023-10-24 21:50 UTC
Labels: External, Engineering, Daily, Overdue, Awaiting Payment, Bug
