### ISSUE TITLE
[HOLD for payment 2023-10-23] [$1000] Feature request: Unable to add multiple emails at once as members to a workspace

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#26242] opened 2023-08-29 19:12 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Go to staging.new.expensify.com
2. Log in with any account
3. Add multiple emails at once as members to a workspace

## Expected Result:
Allow for multiple emails addresses to be added at once when inviting new members to a workspace.

## Actual Result:
Unable to add multiple emails at once as members to a workspace

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [x] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 1.3.58.0
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation

![image (20)](https://github.com/Expensify/App/assets/93399543/fc320073-5da1-4f2d-920d-9c4bb856ab72)

**Expensify/Expensify Issue URL:**
**Issue reported by:** @mallenexpensify 
**Slack conversation:** https://expensify.slack.com/archives/C01GTK53T8Q/p1692837155454539

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~017b2a4652d665e512</li>
        <li>Upwork Job ID: 1699456983730249728</li>
        <li>Last Price Increase: 2023-09-26</li>
    </ul>
</details>

**Comment by akinwale** [comment] 2023-08-30 03:47
# Proposal

### Please re-state the problem that we are trying to solve in this issue.
Unable to add multiple emails at once as members to a workspace using the search input.

### What is the root cause of that problem?
None. This is a new feature.

### What changes do you think we should make in order to solve the problem?
We can update the `getOptions` method in [OptionListUtils](https://github.com/Expensify/App/blob/main/src/libs/OptionsListUtils.js) to be able to parse and handle a searchValue which contains a delimiter (in this case a comma). If there is a delimiter present, find all the matching results using an or match and display them in the list. Optionally, automatically check all the options in the list, so that the Invite button can be activated straight away.

### What alternative solutions did you explore? (Optional)
None.

**Comment by maddylewis** [comment] 2023-08-31 18:04
pinged Matt about this here - https://expensify.slack.com/archives/C01GTK53T8Q/p1693505035975329?thread_ts=1692837155.454539&cid=C01GTK53T8Q

**Comment by jasperhuangg** [comment] 2023-09-05 17:35
> #2958

So it seems that the PR I did wasn't to allow searching for multiple emails. That just allows us to search for chat names with commas inside them. That's for the search page, which is separate from the issue we're talking about here.

**Comment by mallenexpensify** [comment] 2023-09-06 05:00
Sorry for the delay. Without knowing much about the code, I think it's more common that people, especially companies (who pay us!), will want to add multiple users at once vs someone searching for emails or room names with commas in them (if they're even related, Jasper's comment above makes it sound like they're not). 

I can see this not being a quick/easy fix that should be thoroughly thought through before implementing.  I think it's common for people to add multiple emails by having a comma in between each but maybe there's another/better way?  Maybe we would have a tooltip or similar letting people know who to add multiples?

**Comment by Juggernaut-98** [comment] 2023-09-06 17:20
@mananjadhav  After going through the code I realized that the issue is with how we are checking validity of search values. From what I have observed we are not properly spliting the search values in SearchPage.js. With proper splitting we can make this work.
Do let me know if more information is needed or if my solution seems like something that could work. I would send a porposal on upwork. :)

**Comment by Juggernaut-98** [comment] 2023-09-06 17:24
Contributor details
@mananjadhav After going through the code I realized that the issue is with how we are checking validity of search values. From what I have observed we are not properly spliting the search values in SearchPage.js. With proper splitting we can make this work.
Do let me know if more information is needed or if my solution seems like something that could work. I would send a porposal on upwork. :)

Your Expensify account email: tayyab.athar.saleem@gmail.com
Upwork Profile Link: https://www.upwork.com/freelancers/~017b88118348aa48c8

**Comment by mananjadhav** [comment] 2023-09-07 19:22
Let's hold all proposals till we finalize the expected behavior. I also think we should create the chip design for multiple emails. Something on these lines to avoid confusion about multiple email addresses.

cc - @maddylewis  @mallenexpensify @shawnborton 

<img width="587" alt="image" src="https://github.com/Expensify/App/assets/3069065/82e63623-bad8-4b23-8c95-83f4a0dcfa38">

**Comment by shawnborton** [comment] 2023-09-08 13:43
Hmm I don't think we need a "chip" design - why not just show the relevant result rows based on what the user inputs into the search box? Like if you entered `shawn@expensicorp.com, danny@expensicorp.com`, then I would imagine we would return both of those rows below?

cc @JmillsExpensify @trjExpensify @Expensify/design for thoughts here

**Comment by maddylewis** [comment] 2023-09-11 13:29
bumped - https://expensify.slack.com/archives/C01GTK53T8Q/p1694438955171939?thread_ts=1692837155.454539&cid=C01GTK53T8Q

**Comment by trjExpensify** [comment] 2023-09-11 15:23
I'll leave @mananjadhav to be the decider on that!

**Comment by maddylewis** [comment] 2023-09-12 14:58
@mananjadhav - let us know what you think - https://github.com/Expensify/App/issues/26242#issuecomment-1714017291

**Comment by mananjadhav** [comment] 2023-09-12 17:43
I agree with the approach. Thanks for clarifying. @Juggernaut-98 Can you work on your proposal a bit? I don't see any details, technical info, files we'll change, what would we be the delimiter, etc.

**Comment by maddylewis** [comment] 2023-09-14 18:21
@mananjadhav - let us know what you think about @Juggernaut-98's updated proposal - thx!

**Comment by maddylewis** [comment] 2023-09-18 18:16
bump on proposal review @mananjadhav - ty!

**Comment by mananjadhav** [comment] 2023-09-21 17:54
Apologies for the delay I didn't see the updated proposal. @Juggernaut-98 for some reason I still find the proposal incomplete. Generally I don't ask for the videos in the proposals, but either you could detail out the implementation with the file names, core logic change? or you can upload a video that your change works?

**Comment by maddylewis** [comment] 2023-09-26 14:39
updated price since there are still no satisfactory proposals after 4 weeks.

**Comment by Samueljh1** [comment] 2023-09-26 14:51
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
When inviting new members to a workspace, we can only invite one at a time.

### What is the root cause of that problem?
The handlers and code in WorkspaceInvitePage.js only have logic that support inviting one member at a time.

### What changes do you think we should make in order to solve the problem?
Update single-user state variable `userToInvite` to an array, and update all handling logic to support multiple users (e.g., foreach invited emails when updating the list view instead of updating a single item).

### What alternative solutions did you explore? (Optional)
N/A

**Comment by Samueljh1** [comment] 2023-09-28 08:48
@maddylewis bump

**Comment by maddylewis** [comment] 2023-09-29 17:03
@mananjadhav - will you take a look at the above proposal when you have a chance - ty!

**Comment by maddylewis** [comment] 2023-10-02 13:38
@mananjadhav - bump on proposal review! lmk if you don't have the bandwidth and i can tag someone else in to review this one.

**Comment by mananjadhav** [comment] 2023-10-02 14:46
@Samueljh1's proposal [here](https://github.com/Expensify/App/issues/26242#issuecomment-1735705251) looks fine to me. 

🎀 👀 🎀 C+ reviewed.

**Comment by Samueljh1** [comment] 2023-10-02 16:43
> @Samueljh1's proposal [here](https://github.com/Expensify/App/issues/26242#issuecomment-1735705251) looks fine to me. I also think we should restrict this to Workspace invite for the timebeing. Will work out the kinks in the PR.
> 
> 🎀 👀 🎀 C+ reviewed.
> 
> Apologies @maddylewis I was OOO.

Hi, will my contribution not be honoured if this is being reviewed internally?

**Comment by mananjadhav** [comment] 2023-10-02 16:46
@Samueljh1 Our process is that C+ member (selected external contributors) review the proposal and then an internal engineer is assigned. Once they also prefer the shortlisted solution, they assign the issue to the contributor (in this case you).

Then the contributor starts working on the PR. Checkout these contributing guidelines [here](https://github.com/Expensify/App/blob/main/contributingGuides/CONTRIBUTING.md).

**Comment by francoisl** [comment] 2023-10-02 17:47
Looks good to me, let's go with your proposal @Samueljh1.

**Comment by Samueljh1** [comment] 2023-10-03 11:52
> Looks good to me, let's go with your proposal @Samueljh1.

Great, do I need to accept an upwork invite?

**Comment by francoisl** [comment] 2023-10-03 17:23
Hm looks like the automation for the job assignment might not have worked, let me try that again..

**Comment by francoisl** [comment] 2023-10-06 21:08
@Samueljh1 were you able to apply to the Upwork job in the comment just above?

**Comment by Samueljh1** [comment] 2023-10-06 21:31
> @Samueljh1 were you able to apply to the Upwork job in the comment just above?

Yes, apologies, I missed the bot message with the invite.

**Comment by Samueljh1** [comment] 2023-10-07 00:13
@francoisl PR submitted

**Comment by mananjadhav** [comment] 2023-10-10 10:41
I'll reviewing this today/tomorrow.

**Comment by Samueljh1** [comment] 2023-10-12 08:12
> Based on my calculations, the pull request did not get merged within 3 working days of assignment. Please, check out my computations here:
> 
> * when @Samueljh1 got assigned: 2023-10-03 17:26:08 Z
> * when the PR got merged: 2023-10-12 00:20:31 UTC
> * days elapsed: 6
> 
> On to the next one 🚀

@francoisl do you think I could get an allowance here as the bot failed to assign me correctly? I submitted the PR a few hours after seeing the assignment on my side.

**Comment by mananjadhav** [comment] 2023-10-12 13:32
@Samueljh1 Looks like we have a [regression here](https://github.com/Expensify/App/issues/29435), can you please take this up and fix this please?

**Comment by Samueljh1** [comment] 2023-10-12 14:06
> @Samueljh1 Looks like we have a [regression here](https://github.com/Expensify/App/issues/29435), can you please take this up and fix this please?

Fix PR here: https://github.com/Expensify/App/pull/29445

**Comment by Samueljh1** [comment] 2023-10-23 23:34
> @Samueljh1 , can you please accept the job and reply here once you have?  
> 
> https://www.upwork.com/jobs/~017b2a4652d665e512
> 
> 
> 
> Also... got a kick out of this ridiculousness of a title
> 
> <img width="1114" alt="image" src="https://github.com/Expensify/App/assets/22508304/a43bf8a7-bbcf-435b-b8fc-4c6e3f236a50">
> 
> 

Haha, all done, thanks. Not sure what happened there 😂😂

**Comment by mananjadhav** [comment] 2023-10-24 18:17
@mallenexpensify Can you please post the payout summary so that I can raise a request on NewDot?

**Comment by mallenexpensify** [comment] 2023-10-24 21:27
When reviewing the PR I didn't see anything that showed there was regression.  I think scrolled further up on this issue to see the comment.  So... 

ssue reporter: N/A, internal... me! 
Contributor: @Samueljh1 paid $1000 via Upwork, I'm requesting a $500 refund 
Contributor+: @mananjadhav is due $500 via NewDot

**Comment by Samueljh1** [comment] 2023-10-24 21:53
> When reviewing the PR I didn't see anything that showed there was regression.  I think scrolled further up on this issue to see the comment.  So... 
> 
> 
> 
> ssue reporter: N/A, internal... me! 
> 
> Contributor: @Samueljh1 paid $1000 via Upwork, I'm requesting a $500 refund 
> 
> Contributor+: @mananjadhav is due $500 via NewDot 
> 
> 
> 
> 

We were told the issue was not handled as a regression as it was identified and fixed right away?

**Comment by JmillsExpensify** [comment] 2023-10-25 16:58
What's the take away here? Holding on approving payment until we align.

**Comment by maddylewis** [comment] 2023-10-26 00:13
@francoisl - could you help us clarify whether or not this issue was handled as a regression? https://github.com/Expensify/App/issues/26242#issuecomment-1778067523

once we hear from Franc, I will post a payment summary.

**Comment by francoisl** [comment] 2023-10-26 00:47
The issue was caught on staging as a deploy blocker, and a fix was cherry-picked. Does this count as a regression in terms of payment? I don't remember.

**Comment by mallenexpensify** [comment] 2023-10-26 20:26
From [CONTRIBUTING.md](https://github.com/Expensify/App/blob/main/contributingGuides/CONTRIBUTING.md#regressions)
> If a PR causes a regression at any point within the regression period (starting when the code is merged and ending 168 hours (that's 7 days) after being deployed to production):
>
> - payments will be issued 7 days after all regressions are fixed (ie: deployed to production)
>- a 50% penalty will be applied to the Contributor and [Contributor+](https://github.com/Expensify/App/blob/main/contributingGuides/HOW_TO_BECOME_A_CONTRIBUTOR_PLUS.md) for each regression on an issue
> - the assigned Contributor and [Contributor+](https://github.com/Expensify/App/blob/main/contributingGuides/HOW_TO_BECOME_A_CONTRIBUTOR_PLUS.md) are not eligible for the 50% urgency bonus

The [PR was merged on 10/11](https://github.com/Expensify/App/pull/29044#event-10625456042). The [PR to fix the regression](https://github.com/Expensify/App/pull/29445) was created on 10/12 so the reduction in the job price should be enacted. 

That said, @Samueljh1 , if you're able to link to a discussion where it said the reduction wasn't going to be in effect, that'd be taken into consideration.

**Comment by Samueljh1** [comment] 2023-10-26 21:59
> From [CONTRIBUTING.md](https://github.com/Expensify/App/blob/main/contributingGuides/CONTRIBUTING.md#regressions)
> 
> > If a PR causes a regression at any point within the regression period (starting when the code is merged and ending 168 hours (that's 7 days) after being deployed to production):
> 
> >
> 
> > - payments will be issued 7 days after all regressions are fixed (ie: deployed to production)
> 
> >- a 50% penalty will be applied to the Contributor and [Contributor+](https://github.com/Expensify/App/blob/main/contributingGuides/HOW_TO_BECOME_A_CONTRIBUTOR_PLUS.md) for each regression on an issue
> 
> > - the assigned Contributor and [Contributor+](https://github.com/Expensify/App/blob/main/contributingGuides/HOW_TO_BECOME_A_CONTRIBUTOR_PLUS.md) are not eligible for the 50% urgency bonus
> 
> 
> 
> The [PR was merged on 10/11](https://github.com/Expensify/App/pull/29044#event-10625456042). The [PR to fix the regression](https://github.com/Expensify/App/pull/29445) was created on 10/12 so the reduction in the job price should be enacted. 
> 
> 
> 
> That said, @Samueljh1 , if you're able to link to a discussion where it said the reduction wasn't going to be in effect, that'd be taken into consideration. 
> 
> 
> 
> 
> 
> 

The relevant comment is linked, quoting: 'We will just need to pay $50 to gadhiyamanan for reporting otherwise this was handled as a regression'.

Thanks.
https://github.com/Expensify/App/issues/29435#issuecomment-1760109234

**Comment by mananjadhav** [comment] 2023-10-27 18:25
Apologies I have been having trouble with my connectivity.

> We will just need to pay $50 to gadhiyamanan for reporting otherwise this was handled as a regression.

@Samueljh1 This means there won't be any additional payout for the issue, but to be handled as a regression. Hence there would be a deduction. And considering it reached staging and was a deploy blocker it is definitely a reason for the payout deduction.

cc - @mallenexpensify

**Comment by Samueljh1** [comment] 2023-10-27 18:45
> Apologies I have been having trouble with my connectivity.
> 
> 
> 
> > We will just need to pay $50 to gadhiyamanan for reporting otherwise this was handled as a regression.
> 
> 
> 
> @Samueljh1 This means there won't be any additional payout for the issue, but to be handled as a regression. Hence there would be a deduction. And considering it reached staging and was a deploy blocker it is definitely a reason for the payout deduction.
> 
> 
> 
> cc - @mallenexpensify 

Ok, thanks for clarifying.

**Comment by maddylewis** [comment] 2023-10-28 03:05
## Payments
- [ ] Reporting bonus - N/A (internal)
- [ ] Contributor - @Samueljh1 - $500 (paid $1k via Upwork / requested $500 refund)
- [ ] C+ - @mananjadhav - $500 (via NewDot)

**Comment by maddylewis** [comment] 2023-10-28 03:07
@mananjadhav - will you confirm where we are with this checklist - ty https://github.com/Expensify/App/issues/26242#issuecomment-1765329795

**Comment by Samueljh1** [comment] 2023-10-28 14:39
> ## Payments
> 
> - [x] Reporting bonus - N/A (internal)
> 
> - [x] Contributor - @Samueljh1 - $500 (paid $1k via Upwork / requested $500 refund)
> 
> - [x] C+ - @mananjadhav - $500 (via NewDot)

$500 refund approved

**Comment by JmillsExpensify** [comment] 2023-11-01 18:04
$500 payment for @mananjadhav approved based on [this summary](https://github.com/Expensify/App/issues/26242#issuecomment-1783677709).

**Comment by mallenexpensify** [comment] 2023-11-02 00:59
Quick question then I'll close.  @francoisl @mananjadhav @Samueljh1 , if we wanted to replicate this for adding multiple email address to a room, how similar would it be to the work that was done here?

**Comment by Samueljh1** [comment] 2023-11-02 17:31
> Quick question then I'll close.  @francoisl @mananjadhav @Samueljh1 , if we wanted to replicate this for adding multiple email address to a room, how similar would it be to the work that was done here? 
> 
> 
> 
> 

I expect it to be very similar. I'd be happy to work on this as a separate issue.

**Comment by mallenexpensify** [comment] 2023-11-02 23:58
Thanks @Samueljh1 , I'm discussing internally, I'll tag you in the new GH for the new feature request if/when it gets created.

**Comment by mallenexpensify** [comment] 2023-11-03 19:28
@Samueljh1 tagged ya over here...
- https://github.com/Expensify/App/issues/30874

**Comment by mallenexpensify** [comment] 2023-12-19 02:09
Did this reverted because we didn't address how to show error messages?

**Comment by mallenexpensify** [comment] 2023-12-20 16:59
@francoisl @mananjadhav @Samueljh1 Did this reverted because we didn't address how to show error messages?

**Comment by quinthar** [comment] 2023-12-26 02:30
Let's pause work on this until we settle having a unified design here: https://expensify.slack.com/archives/C01GTK53T8Q/p1703557793897069?thread_ts=1703360093.158969&cid=C01GTK53T8Q

**Comment by maddylewis** [comment] 2023-12-28 14:53
hiya @garrettmknight - nothing actionable on your end atm. i left BZ a couple of months ago but was waiting for some solid next steps on this one before un-assigning myself. 

it sounds like we're going to pause on this feature until some additional details are worked out - https://github.com/Expensify/App/issues/26242#issuecomment-1869205116

**Comment by garrettmknight** [comment] 2023-12-29 16:28
This is actively being redesigned with Groups so I'm going to close. We can reopen if it's still behaving unexpectedly once we update.

**Closed by garrettmknight** 2023-12-29 16:28 UTC
Labels: External, Engineering, Weekly, NewFeature, Awaiting Payment, Bug

**Comment by mallenexpensify** [comment] 2025-08-13 21:49
fwiw... this was partially fixed/built.  The only way to add multiple users to a workspace is via a spreadsheet.  

<img width="497" height="429" alt="Image" src="https://github.com/user-attachments/assets/0c20b2a9-d8a6-4043-a003-b29b1aa7ac61" />

<img width="472" height="157" alt="Image" src="https://github.com/user-attachments/assets/bfc88e98-28fd-4898-8187-3d45557cec79" />

I don't think it's ideal to ask people to use another tool in order to add emails.  When I paste a list into Slack (albeit into a room vs workspace) I instantly get this

<img width="784" height="258" alt="Image" src="https://github.com/user-attachments/assets/d03f4b28-e689-4e2d-ad90-92d939cf991f" />
