### ISSUE TITLE
iOS - Close account - When entering email in the default contact method field it gets highlighted

### ISSUE THREAD

**Issue by kavimuru** [Expensify/App#9461] opened 2022-06-14 20:50 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Launch App and login with any account
2. Navigate to Settings > Security
3. Enter the email in the input and click/tap on "close account"

## Expected Result:
The entered email should not be highlighted.

## Actual Result:
When I enter an email it is highlighted.

## Workaround:
Visual

## Platform:

Where is this issue occurring?

- iOS
- Mobile Web

**Version Number:** 1.1.77.2

**Reproducible in staging?:** Y

**Reproducible in production?:** Y

**Email or phone of affected tester (no customers):** 

**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Notes/Photos/Videos:**

https://user-images.githubusercontent.com/43996225/173686046-05c74675-1bab-4628-bcd8-c5017ad0082f.mp4
![Bug5609779_ios_1406-close_acount](https://user-images.githubusercontent.com/43996225/173686061-b84ce55f-147f-4e58-8c64-3a5895411989.jpg)

**Expensify/Expensify Issue URL:** 

**Issue reported by:** Applause internal team

**Slack conversation:** 

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by arosiclair** [comment] 2022-06-15 20:53
Not sure what the issue is here. Is there something stopping you from entering a full email? @mvtglobally

**Comment by mvtglobally** [comment] 2022-06-15 20:58
@arosiclair, you can enter the email, but in the past it wasn't highlighted while typing. Not sure if this is a low issue or by design now.

**Comment by arosiclair** [comment] 2022-06-17 20:39
I believe this is just behavior from the iOS keyboard not our app. I was able to reproduce this and can confirm this isn't impacting user's ability to type an email and close their account so I'll close this as not an issue.

**Closed by arosiclair** 2022-06-17 20:39 UTC
Labels: Engineering, Daily
