### ISSUE TITLE
[$500] Scan - Unable to proceed with Scan request using a CSV file

### ISSUE THREAD

**Issue by izarutskaya** [Expensify/App#31811] opened 2023-11-24 10:17 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___
**Issue found when executing PR:** https://github.com/Expensify/App/pull/29790

**Version Number:** v1.4.3-0
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** Applause-Internal Team
**Slack conversation:** @

## Action Performed:
1. Navigate to staging.new.expensify.com.
2. Open any chat.
3. Click + > Request money > Scan.
4. Create a Scan request with a CSV file.

## Expected Result:
User is able to create a Scan request with a CSV file.

## Actual Result:
User is unable to create a Scan request with a CSV file. It shows error 'This filetype is not allowed'.

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [x] Android: mWeb Chrome
- [x] iOS: Native
- [x] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

https://github.com/Expensify/App/assets/115492554/b73e6fd0-9632-4942-9560-c68e97b48a60

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~014c65653fce87c138</li>
        <li>Upwork Job ID: 1727994855185854464</li>
        <li>Last Price Increase: 2023-11-24</li>
    </ul>
</details>

**Comment by DylanDylann** [comment] 2023-11-24 10:19
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
 Scan - Unable to proceed with Scan request using a CSV file

### What is the root cause of that problem?
We don't allow uploading csv file
### What changes do you think we should make in order to solve the problem?
add csv file to ALLOWED_RECEIPT_EXTENSIONS CONST

### What alternative solutions did you explore? (Optional)

**Comment by s-alves10** [comment] 2023-11-24 10:27
## Proposal

### Please re-state the problem that we are trying to solve in this issue.

Unable to create a scan IOU request using a csv file

### What is the root cause of that problem?

We don't allow csv file types now
https://github.com/Expensify/App/blob/a2fc32bbfb8d5917e83134568187529d488812e2/src/CONST.ts#L55

### What changes do you think we should make in order to solve the problem?

I think we need to list all allowed file types here
Except csv, I think we can add `docx`, `xlsx`, `xls`, `tar`, `gz`, `eml`, `md`, etc

**Note**: Backend fix might be needed

### What alternative solutions did you explore? (Optional)

**Comment by situchan** [comment] 2023-11-24 10:29
We can close this as not bug. This is already aligned with backend validation  - https://github.com/Expensify/App/issues/29960#issue-1951962561

**Closed** 2023-11-27 20:29 UTC
Labels: External, Daily, Help Wanted, Overdue, Bug
