### ISSUE TITLE
[HOLD for payment 2024-03-20] [$500] Chat - Two Modals Open Simultaneously During Text Editing

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#36381] opened 2024-02-12 21:47 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___
 
**Version Number:** 1.4.40-0
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** Applause - Internal Team
**Slack conversation:**

## Action Performed:
1, Go to the conversation.
2, Write a message.
3, Hover over the message, click "more," modal opens.
4, Press the up arrow key, enabling editing.
5, Clear all text and press Enter.
6, Notice two modals open; the first should close before the second, as when clicking "save."

## Expected Result:
Upon pressing Enter, the first opened modal should close.

## Actual Result:
Two models open simultaneously, and the first one does not close upon pressing Enter.

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

https://github.com/Expensify/App/assets/93399543/da427517-2f3a-4234-85ff-700113032081

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01cf48132d330e8d95</li>
        <li>Upwork Job ID: 1757159506265567232</li>
        <li>Last Price Increase: 2024-02-26</li>
<li>Automatic offers: </li>
<ul>
<li>hoangzinh | Reviewer | 0</li>
<li>jeremy-croff | Contributor | 0</li>
</ul></li>
    </ul>
</details>

**Comment by LouzirMohamedAziz** [comment] 2024-02-12 23:11
## Proposal

### Please re-state the problem that we are trying to solve in this issue.

Two Modals Open Simultaneously During Text Editing

### What is the root cause of that problem?

missing action to hide the opened modals before calling the showDeleteModal() Within the function ReportActionItemMessageEdit at: 318
src/pages/home/report/ReportActionItemMessageEdit.tsx as shown in the following condition: 

        // When user tries to save the empty message, it will delete it. Prompt the user to confirm deleting.
        if (!trimmedNewDraft) {
            textInputRef.current?.blur();
            ReportActionContextMenu.showDeleteModal(
                reportID,
                action,
                true,
                deleteDraft,
                // eslint-disable-next-line @typescript-eslint/no-misused-promises
                () => InteractionManager.runAfterInteractions(() => textInputRef.current?.focus()),
            );
            return;
        }

### What changes do you think we should make in order to solve the problem?

add the missing call the hideContextMenu() to hide all the active menus before performing showDeleteModal() as follow: 

        // When user tries to save the empty message, it will delete it. Prompt the user to confirm deleting.
        if (!trimmedNewDraft) {
            textInputRef.current?.blur();
            ReportActionContextMenu.**hideContextMenu();**
            ReportActionContextMenu.showDeleteModal(
                reportID,
                action,
                true,
                deleteDraft,
                // eslint-disable-next-line @typescript-eslint/no-misused-promises
                () => InteractionManager.runAfterInteractions(() => textInputRef.current?.focus()),
            );
            return;
        }


### What alternative solutions did you explore? (Optional)
N/A

**Comment by LouzirMohamedAziz** [comment] 2024-02-12 23:13
Contributor details
Your Expensify account email: medaziz.louzir@gmail.com
Upwork Profile Link: https://www.upwork.com/freelancers/~01e79d820f07753bfe

**Comment by LouzirMohamedAziz** [comment] 2024-02-13 00:25
## Proposal
[Updated] https://github.com/Expensify/App/issues/36381#issuecomment-1939761450

**Comment by jeremy-croff** [comment] 2024-02-13 04:10
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
We show two open popovers in this experience

### What is the root cause of that problem?
We are not unfocusing the composer when clicking the Context Menu three dots item. So composer keeps focus, and listens to the keyboard events.

### What changes do you think we should make in order to solve the problem?
I reviewed what we do when we add an attachment. On that button press we explicitly blur the Composer.
We can do the same for the context menu item.
On the click of the menu item here:
https://github.com/Expensify/App/blob/1f1867a0a969c91e2169603b33ea272067428504/src/pages/home/report/ContextMenu/ContextMenuActions.tsx#L474
if we call:
`ReportActionComposeFocusManager?.composerRef?.current?.blur();`
We will take the focus away from the composer.
And now the keyboard events will work on the popover menu items.

### What alternative solutions did you explore? (Optional)

**Comment by askavyblr** [comment] 2024-02-13 09:59
### Proposal

**Please re-state the problem that we are trying to solve in this issue.

Two models open simultaneously, and the first one does not close upon pressing Enter.

**What is the root cause of that problem?**

Need to hide opened modals before showing Delete Model

**What changes do you think we should make in order to solve the problem?**

https://github.com/Expensify/App/blob/0593b456657e1461ed970b690da1706b5c2b9f57/src/pages/home/report/ContextMenu/PopoverReportActionContextMenu.tsx#L271-L280

Need to add **setIsPopoverVisible(false);** 

**What alternative solutions did you explore? (Optional)

[Screencast from 13-02-24 03:18:25 PM IST.webm](https://github.com/Expensify/App/assets/125897912/9446a56d-16dc-4d09-b56b-a56bd8749899)

**Comment by CortneyOfstad** [comment] 2024-02-14 16:54
@hoangzinh any thoughts on the proposals above? Thanks!

**Comment by CortneyOfstad** [comment] 2024-02-20 17:14
Sorry, was OoO yesterday! Reviewing now!

**Comment by CortneyOfstad** [comment] 2024-02-20 17:28
@hoangzinh so I have been diving into this, and we don't unfocus the field when we click on anything else, but we do remove the cursor in other instances like clicking the emoji option as below:

<img width="1190" alt="Screenshot 2024-02-20 at 11 24 00 AM" src="https://github.com/Expensify/App/assets/10926327/766e21bf-3ea1-4de7-8d47-7b166133bb73">

<img width="1190" alt="Screenshot 2024-02-20 at 11 25 25 AM" src="https://github.com/Expensify/App/assets/10926327/8fad6ada-3ddd-49ac-b818-73c32ff5a397">

Do you feel that is a reasonable alternative? I feel that this is more in-line with other aspects of new.expensify, but interested to hear your thoughts!

**Comment by CortneyOfstad** [comment] 2024-02-21 14:50
@hoangzinh I disagree, as we do not unfocus anything at this time. Other apps do not do this functionality, so I feel as though having it unfocus for the sake of unfocusing isn't worth the time. 

However, if you feel strongly about this, I do recommend bringing it to the team to discuss as we can dive in further!

**Comment by CortneyOfstad** [comment] 2024-02-23 17:38
@hoangzinh No worries! I should have explained this a bit better. My reasoning for not unfocusing is that we do not do this with other aspects currently, so essentially having to change all of those actions to unfocus to make this situation work seems like not a high priority. I would rather we adjust this situation to match the others (not unfocusing, but rather just removing the cursor in the text field). 

However, if you feel strongly that we should change the other aspects (emoji selection, etc) then I do recommend posting in #open-source for the team to discuss as a whole.

**Comment by CortneyOfstad** [comment] 2024-02-26 15:01
> I'm confusing this one. Doesn't removing the cursor in the text field mean unfocusing in this situation? I'm understanding they're the same. By unfocus the text field, we remove the cursor in this case.

@hoangzinh — I was under the impression these were two different actions, but if you are reference `unfocusing` as in removing the cursor, then we are on the same page here 👍 

Thank you for clarifying further!

**Comment by jeremy-croff** [comment] 2024-02-28 03:30
> Another hint for you. I recall that if we focus on another element, the browser will unfocus the currently active element. But in our codebase, there is a logic somewhere that prevents that behavior in this case.

I spent another few hours trying out different things but concluded the following:

If we check how the add attachment flow works in the composer
It calls the blur specifically [here:](https://github.com/Expensify/App/blob/98461f987e08e1ee977bd60f4974513b84b3c93d/src/pages/home/report/ReportActionCompose/ReportActionCompose.js#L240)  in order to achieve the same we are trying to achieve here.

Since we don't have any focused input on the "Menu" popover click, perhaps we should follow the previous pattern as well, as they both open a modal with menu items.

**Comment by jeremy-croff** [comment] 2024-02-28 14:03
> One doubt: I see that edit composer is blurred when follow same repro step. Why does this happen on main composer only?

This is what is blurring the edit composer: https://github.com/Expensify/App/blob/3389b90e6b2877e8ee0640e67771a63d47391737/src/pages/home/report/ReportActionItemMessageEdit.tsx#L438

**Comment by jeremy-croff** [comment] 2024-02-28 14:10
I can review more, maybe the question is why is edit calling the blur but the main compose not? since the man compose doesn't fire off their onBlur

**Comment by jeremy-croff** [comment] 2024-02-29 00:55
@hoangzinh Can you clarify if you want me to implement the accepted proposal? Or to further check into it.

**Comment by jeremy-croff** [comment] 2024-02-29 04:31
@hoangzinh 
I apologize for any delay in further driving clarity into the RCA. It was like finding needles in the haystack.
To further drive clarity in the RCA:

The code [here](https://github.com/Expensify/App/blob/3e74ddf0d2b408faa270ff243cf333065b177a87/src/components/BaseMiniContextMenuItem.tsx#L67) prevent the blur event propagation from occuring when we click the hover menu buttons like reactions, or three dot menu. This should prevent it for both main and edit composer. 

But why does the edit composer still call onBlur?
In this same file where we stop the blur event from propagating, we have code to call blur IF the composer and edit composer is not focused. However when breaking at https://github.com/Expensify/App/blob/3e74ddf0d2b408faa270ff243cf333065b177a87/src/components/BaseMiniContextMenuItem.tsx#L53 we uncover that `ReportActionComposeFocusManager.isEditFocused()` evaluates to false even though the edit composer IS focused. This allows the code to execute the blur action on edit composer.  

Why is  `ReportActionComposeFocusManager.isEditFocused() always evaluating as false? Well do a global search for https://github.com/search?q=repo%3AExpensify%2FApp%20editComposerRef&type=code and observe it's never set. Can of worms?

We can use this information to make some decisions:
1. Start setting the editComposerRef to fix that bug
+
2. Exclude only the three dot menu from preventing event propgation, but make the emoji reactions still prevent it to keep composer focus (need to look into what this would look like code wise)


 Or go with the original proposal to just forcibly call blur on the three dot and not touch the rest.

**Comment by jeremy-croff** [comment] 2024-03-02 17:35
> Good catch @jeremy-croff. Can you share more about how can we `bubble up the click event only for thee three-dot menu`?

So we could pass a prop from the ContextMenuActions to BaseMiniContextMenuItem,
So that we can handle the blur on a per action basis.

i.e.:
1.  in the menu item action object, we can add a prop for shouldPreventDefaultEvent: false
2. we can pass it through until it reaches BaseMiniContextMenuItem
3. we only call e.preventDefault if shouldPreventDefaultEvent is true [here](https://github.com/Expensify/App/blob/3e74ddf0d2b408faa270ff243cf333065b177a87/src/components/BaseMiniContextMenuItem.tsx#L67)
4. shouldPreventDefaultEvent defaults to true if it's not passed from other actions to maintain existing behaviour

And for this proposal I would need a decision whether or not we need to set editComposerRef, or if we can treat it as a seperate ticket (And I'll gladly write the proposal for that!). The user impact is that when in an edit composer, clicking on reaction emojis in other rows it loses focus on the edit composer when it shouldn't.

**Comment by jeremy-croff** [comment] 2024-03-02 17:37
> @jeremy-croff The reason for #1 https://github.com/Expensify/App/pull/34091/files#r1446614575. But I agree we should fix it.

Great find :P

**Comment by jeremy-croff** [comment] 2024-03-04 16:26
> Hi @jeremy-croff, I think your solution works. But I'm comparing it with our existing pattern in Expensify codebase. For example
> 
> https://github.com/Expensify/App/blob/4231ac90a8f6efa0249c925a06adbb9ef4d7a54a/src/pages/home/report/ReportActionItemMessageEdit.tsx#L440-L443
> 
> We check based on the target ID. Or [here](https://github.com/Expensify/App/blob/4231ac90a8f6efa0249c925a06adbb9ef4d7a54a/src/pages/iou/steps/MoneyRequestAmountForm.tsx#L106-L117). Is it possible to apply this targetID approach in our case? What do you think about this targetID approach and your approach using additional props?

Will give an update later, had a couple minutes for initial thoughts but want to spend more time after my office work.

quick thoughts are that  shouldPreventDefault prop is also a pattern used in places: https://github.com/search?q=repo%3AExpensify%2FApp+shouldPreventDefault&type=code

When reviewing which is better I want to look at the usage of the https://github.com/Expensify/App/blob/3e74ddf0d2b408faa270ff243cf333065b177a87/src/components/BaseMiniContextMenuItem.tsx#L49C13-L49C38 and if it makes sense to pass in IDs, and can be done so from the actual menu actions, cause otherwise it's a bit of a detached code that might be hard to trace.

**Comment by jeremy-croff** [comment] 2024-03-04 18:04
Thank you @hoangzinh for this collaboration, and helping getting a deeper understanding of the problem with your guidance.

**Comment by bondydaa** [comment] 2024-03-07 01:28
thanks for getting all that resolved, I had thought we might do that on the PR sorry, that's why I'd assigned before.

@jeremy-croff you're still going to spin up a PR right?

**Comment by jeremy-croff** [comment] 2024-03-07 01:36
@bondydaa Yes, thank you!
Just opened the draft and testing. Will have the checklist completed in an hour or so.

**Comment by CortneyOfstad** [comment] 2024-03-11 17:50
@jeremy-croff any update on the PR? Thanks!

**Comment by jeremy-croff** [comment] 2024-03-11 17:55
> @jeremy-croff any update on the PR? Thanks!

It's merged! :)

**Comment by CortneyOfstad** [comment] 2024-03-20 19:08
@hoangzinh can you complete the checklist by EOD? Thanks!

**Comment by CortneyOfstad** [comment] 2024-03-20 19:11
## Payment Summary

- @hoangzinh — paid $500 via Upwork
- @jeremy-croff — paid $500 via Upwork

**Comment by CortneyOfstad** [comment] 2024-03-21 13:52
Thanks @hoangzinh!

**Closed by CortneyOfstad** 2024-03-21 13:52 UTC
Labels: External, Engineering, Daily, Bug
