### ISSUE TITLE
[$500] The account number is masked and you can't move forward with VBA flow - Reported by @Puneet-here

### ISSUE THREAD

**Issue by mvtglobally** [Expensify/App#11318] opened 2022-09-27 04:15 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:

1. Go to bank account > add info > company step > personal information
2. Dismiss the modal by pressing cross
3. Now go to workspace > "connect bank account" > continue with the setup
4. Now keep going back until you reach page with routing number & account number
5. Now try pressing save and continue

## Expected Result:
The account number shouldn't be masked or if we mask it we should let user save & continue

## Actual Result:
The account number is masked and you can't save & continue

## Workaround:
unknown 

## Platform:

Where is this issue occurring?

- Web
- iOS
- Android
- Desktop App
- Mobile Web

**Version Number:** 1.2.3-0
**Reproducible in staging?:** Y
**Reproducible in production?:** need repro PROD creds
**Email or phone of affected tester (no customers):** 
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation 

https://user-images.githubusercontent.com/43995119/192430432-c7ffbc95-1a20-44ff-a799-2d219c996fb2.mov

**Upwork job URL:** https://www.upwork.com/jobs/~01eb5ae98c2c497e8f
**Issue reported by:** @Puneet-here

**Slack conversation:** https://expensify.slack.com/archives/C01GTK53T8Q/p1662750530375309

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by Christinadobrzyn** [comment] 2022-09-27 04:46
Ooh, that looks like a good one to fix

**Comment by aldo-expensify** [comment] 2022-09-29 20:40
I'm not being able to reproduce this, instructions feel a bit incomplete too:

- This is while adding a bank account in a workspace (business bank account), right? If that is the case, please add it in the steps
- I tested adding a business bank account (in the workspace) using plaid and manual, reaching the Personal information step and then going back with the arrow. In neither case I saw the numbers masked

@mvtglobally Can you help me with clarifying the reproduction steps? thanks :)

**Comment by Puneet-here** [comment] 2022-09-29 20:44
> This is while adding a bank account in a workspace (business bank account), right? If that is the case, please add it in the steps

Yes, you have to add the bank account at workspace and after reaching the personal details page you have dismiss the modal as suggested in the step 2.
Now go at workspace > connect bank account > continue with setup > go back till routing page

**Comment by aldo-expensify** [comment] 2022-09-29 23:56
I'm still not able to reproduce this, not in dev and neither in staging. I don't get the account numbers masked. I tried again using plaid and manual input of the account numbers. I close the modal when I get the verification thing from Onfido (after entering the personal details: name, last name, etc).

Any idea of what I may be missing?

**Comment by aldo-expensify** [comment] 2022-10-03 17:13
@Puneet-here 👋 can you confirm if this is still happening and if you reproduce it, give me the exact steps to reproduce it? Thanks

**Comment by Puneet-here** [comment] 2022-10-03 20:42
> @Puneet-here 👋 can you confirm if this is still happening and if you reproduce it, give me the exact steps to reproduce it? Thanks

I was able to see the masked account number but couldn't find the exact step, I will let you know after testing again.

**Comment by Puneet-here** [comment] 2022-10-05 18:40
> @Puneet-here 👋 can you confirm if this is still happening and if you reproduce it, give me the exact steps to reproduce it? Thanks

I found that when you log out and login again then this is reproducible every time.

1. Go to workspace > connect bank account > chose an option > add info > company step > personal information
2. Dismiss the modal by pressing cross
3. Sign out and sign in again
4. Go to workspace > connect bank account > continue with the setup
5. Start going back

Earlier it was happening without signing out, we just had to dismiss the modal.

I think after logging out it seeing masked account number could be intentional.

**Comment by Puneet-here** [comment] 2022-10-06 06:08
@aldo-expensify, please reopen and apply external label to get a CM on this for reporting compensation.

**Comment by aldo-expensify** [comment] 2022-10-06 06:22
Removing @thesahindia as this was already solved... just adding `External`  to handle compensation from reporting the issue

**Comment by aldo-expensify** [comment] 2022-10-06 06:24
hmm, it seems like it [failed](https://github.com/Expensify/App/issues/11318#issuecomment-1269398030) to assign someone because everyone is out of office.. hehe

Lets try again tomorrow?

**Comment by Puneet-here** [comment] 2022-10-06 06:45
> Lets try again tomorrow?

Yeah, no worries. We can settle it tomorrow.

**Comment by michaelhaxhiu** [comment] 2022-10-07 12:41
>hmm, it seems like it https://github.com/Expensify/App/issues/11318#issuecomment-1269398030 to assign someone because everyone is out of office.. hehe

PS, not quite true 😄  -- I think GH webhooks were just failing yesterday for a period of time.

@aldo-expensify just to clarify, only a bug reporting bonus is due to @Puneet-here ?

**Comment by michaelhaxhiu** [comment] 2022-10-07 12:45
Ah I see now... this was reported by @Puneet-here and then we fixed it **internally** via https://github.com/Expensify/App/pull/11616.

Ok yes, only a bug reporting bonus is due in this case to @Puneet-here ($250). cc @maddylewis

**Comment by maddylewis** [comment] 2022-10-07 12:45
thanks for confirming @michaelhaxhiu! i will complete this today.

**Comment by Puneet-here** [comment] 2022-10-07 13:04
> Ok yes, only a bug reporting bonus is due in this case to @Puneet-here ($250). cc @maddylewis

I think the compensation should be $500. I had reported this issue ([here](https://expensify.slack.com/archives/C01GTK53T8Q/p1662750530375309)) and a deploy blocker yesterday ([here](https://expensify.slack.com/archives/C01GTK53T8Q/p1664994310748019)) both were unrelated and valid bugs and were fixed in https://github.com/Expensify/App/pull/11616

**Comment by maddylewis** [comment] 2022-10-07 15:17
@aldo-expensify @michaelhaxhiu - will you confirm those details for me ^^^

**Comment by luacmartins** [comment] 2022-10-07 16:08
>@aldo-expensify @michaelhaxhiu - will you confirm those details for me ^^^

@maddylewis that is correct. The compensation should be $500 for the two issues reported as @Puneet-here mentioned!

**Comment by aldo-expensify** [comment] 2022-10-07 16:55
hmm, but as far as I know, we never got to triage / reproduce the issue reported in slack: https://expensify.slack.com/archives/C01GTK53T8Q/p1664994310748019. If it had been triaged, there could have been a chance of it getting closed because of being the same as this one.

**Comment by michaelhaxhiu** [comment] 2022-10-07 17:19
Spoke more with @aldo-expensify 1:1 and while this feels like both bugs were similarly related, I think there's a case to be made for treating them separately. Let's pay out $500 total for both this time.

**Comment by Puneet-here** [comment] 2022-10-07 18:26
> Job link - https://www.upwork.com/jobs/~01eb5ae98c2c497e8f
> 
> I invited you to the job @Puneet-here

I have applied.

**Comment by michaelhaxhiu** [comment] 2022-10-07 18:55
Done deal, closing.

**Closed by michaelhaxhiu** 2022-10-07 18:55 UTC
Labels: External, Engineering, Daily
