### ISSUE TITLE
 iOS - Workspace plan - Nothing happens when selecting Collect plan and tapping Save button

### ISSUE THREAD

**Issue by IuliiaHerets** [Expensify/App#54523] opened 2024-12-24 12:38 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 9.0.78-0
**Reproducible in staging?:** Yes
**Reproducible in production?:** N/A - new feature, doesn't exist in prod
**If this was caught on HybridApp, is this reproducible on New Expensify Standalone?:** Yes, reproducible on both
**If this was caught during regression testing, add the test name, ID and link from TestRail:** Exp
**Email or phone of affected tester (no customers):** applausetester+zm80@applause.expensifail.com
**Issue reported by:** Applause Internal Team
**Device used:** iPhone 15 Pro Max / iOS 18.2
**App Component:** Workspace Settings

## Action Performed:
1. Launch ND or hybrid app.
2. Paste the link of a Collect workspace (https://dev.new.expensify.com:8082/settings/workspaces/45B622CFE5215E99/profile/plan) in any chat.
3. Tap on the link.
4. Select Control, save and upgrade the workspace.
5. Go back to the chat.
6. Tap on the same link.
7. Select Collect and tap Save.

## Expected Result:
User should be able to change to Collect plan.

## Actual Result:
Nothing happens when selecting Collect plan and tapping Save button.

## Workaround:
Unknown

## Platforms:
- [ ] Android: Standalone
- [ ] Android: HybridApp
- [ ] Android: mWeb Chrome
- [ ] iOS: Standalone
- [x] iOS: HybridApp
- [x] iOS: mWeb Safari
- [ ] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

https://github.com/user-attachments/assets/f364f41b-9211-4442-bd15-c7a33a682675

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by IuliiaHerets** [comment] 2024-12-24 12:41
Tester found the issue by exploratory, but we have a related [PR](https://github.com/Expensify/App/pull/53343)

**Comment by jasperhuangg** [comment] 2024-12-24 21:13
Also unable to reproduce, I think we can close this out for now.

**Closed by jasperhuangg** 2024-12-24 21:13 UTC
Labels: DeployBlockerCash, Engineering, Hourly, Bug
