### ISSUE TITLE
[HOLD for payment 2023-07-05] [$1000] delete message functionality not working for first message in thread

### ISSUE THREAD

**Issue by kavimuru** [Expensify/App#19363] opened 2023-05-22 00:44 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:

1. Go to any chat
2. send any message
3. go to thread
4. delete first message

## Expected Result: 
should delete message
## Actual Result: 
nothing happens on delete message
## Workaround:
Can the user still use Expensify without this being fixed? Have you informed them of the workaround?

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [x] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 1.3.16-6
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/43996225/7133f555-713f-44f2-8605-f5fffc4bd06f

https://github.com/Expensify/App/assets/43996225/436dd665-881b-4ecb-af00-e785417919ae

**Expensify/Expensify Issue URL:**
**Issue reported by:** @gadhiyamanan 
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1684386596805889

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~0161928def73a1c305</li>
        <li>Upwork Job ID: 1661027515886391296</li>
        <li>Last Price Increase: 2023-06-06</li>
    </ul>
</details>

**Comment by tienifr** [comment] 2023-05-22 08:27
I think this will be fixed by https://github.com/Expensify/App/pull/18638. Let's hold up.

**Comment by tienifr** [comment] 2023-05-22 12:24
## Proposal

### Please re-state the problem that we are trying to solve in this issue.

Delete parent message in thread is not working.

### What is the root cause of that problem?

Currently deleting the first (parent) message in thread does not delete the root message in parent report. Deleting a message in parent report also deletes it in the child report while it's not true on the other hand.

### What changes do you think we should make in order to solve the problem?

1. Add a new argument `parentReportID` to `deleteCommentReport` action.

```javascript
function deleteReportComment(reportID, reportAction, parentReportID)
```

2. And within `deleteCommentReport` action if there's `parentReportID`, use it as `reportID`:

```
const parameters = {
        reportID: parentReportId || reportID,
        reportActionID: reportAction.reportActionID,
};
```

3. Need to add new props to (BaseReportActionContextMenu)[https://github.com/Expensify/App/blob/main/src/pages/home/report/ContextMenu/BaseReportActionContextMenu.js] to let user pass the `parentReportID`

### What alternative solutions did you explore? (Optional)

NA

**Comment by zanyrenney** [comment] 2023-05-22 15:51
I'm not sure, @tienifr @kavimuru this is not reproducible for me on staging just now 
![2023-05-22_16-50-31](https://github.com/Expensify/App/assets/56830058/b5a498cf-6784-4a4a-a79a-354c68b577dd)

**Comment by zanyrenney** [comment] 2023-05-22 15:51
Can you re-do the reproduction steps to be clearer? When I try this the outcome is not what you are experiencing.

**Comment by gadhiyamanan** [comment] 2023-05-22 16:00
@zanyrenney nothing happened when I try to delete the first message in the thread

Steps: 
1. Go to any chat
2. send any message
3. click on reply in thread option
4. Go to that thread 
5. try to delete the first message

https://github.com/Expensify/App/assets/54790231/44458465-d5a1-43ff-888d-b41d97d70401

**Comment by zanyrenney** [comment] 2023-05-23 15:12
Cool, thanks yep i can repro: 
![2023-05-23_16-11-15 (1)](https://github.com/Expensify/App/assets/56830058/cda7c06f-418c-4f1c-bf2c-a59a1b7bb6a3)

**Comment by zanyrenney** [comment] 2023-05-25 17:25
Going OOO and this is pretty active so needs management by bug0 team member, as per the [new process ](https://expensify.slack.com/archives/CK49UADB9/p1684182291511799)to stay assigned but assign another team member, please can you keep a watch of this. I am OOO until 8th June. Thanks!

**Comment by cristipaval** [comment] 2023-05-29 16:32
> Do we think it's duplicated with #19078 🤔

I think so! @aimane-chnaif Could you please also confirm?

**Comment by cristipaval** [comment] 2023-06-01 21:20
> validating @tienifr's [proposal](https://github.com/Expensify/App/issues/19363#issuecomment-1557129231)

I am not sure I get this. You are saying that this proposal seems good to you?

**Comment by cristipaval** [comment] 2023-06-05 18:56
> @cristipaval should we fix all actions to the first (parent) message in thread report as well in this GH?
> 
> * add/remove reaction
> * edit message
> * mark as unread (this seems working)

Yes, it looks like the root cause is similar for all these use cases and we should fix them all in one shot as they are already identified here.

**Comment by cristipaval** [comment] 2023-06-08 19:54
Asked [internally](https://expensify.slack.com/archives/C03U7DCU4/p1686252235817569) for help as I am not very familiar with the threads.

**Comment by cristipaval** [comment] 2023-06-12 09:31
It makes sense 👍

**Comment by zanyrenney** [comment] 2023-06-19 09:47
hey @aimane-chnaif please can you review the PR? cc @cristipaval Thanks!

**Comment by zanyrenney** [comment] 2023-06-22 14:04
Hey, I am heading OOO shortly, so assigning another bug0 team member to help watch over this issue whilst I am OOO.

**Comment by sakluger** [comment] 2023-06-26 23:41
Sent contracts to everyone through Upwork.

**Comment by zanyrenney** [comment] 2023-07-05 11:05
Hey @sakluger this posting looks closed to me so I can't complete the payments. Can you confirm the upwork job you sent the offers too / did you already complete the payment? 
<img width="662" alt="2023-07-05_12-05-05" src="https://github.com/Expensify/App/assets/56830058/3899eb2d-2733-4e11-86c9-7f10b61d7a1a">

**Comment by sakluger** [comment] 2023-07-05 17:34
@zanyrenney I sent contracts outside of the original Upwork post since it was already closed. I'll handle payment today.

**Comment by sakluger** [comment] 2023-07-05 17:43
Thanks @aimane-chnaif for completing the BZ checklist - I created an issue to update our regression tests based on your recommendation.

Everyone has been paid out now, thanks!

**Closed by sakluger** 2023-07-05 17:43 UTC
Labels: External, Daily, Awaiting Payment, Bug

**Comment by cristipaval** [comment] 2023-07-12 16:40
> Based on [#19363 (comment)](https://github.com/Expensify/App/issues/19363#issuecomment-1608793187), as PR fixed multiple issues at the same time and given efforts made for the ultimate solution, that would be much appreciated if we're eligible for some more comp. cc: @cristipaval @sakluger

This is something that @sakluger as BZ team member can answer.
