### ISSUE TITLE
[HOLD for payment 2024-10-24] Render Error in android emulator

### ISSUE THREAD

**Issue by mountiny** [Expensify/App#50713] opened 2024-10-14 10:22 UTC
### Problem

Coming from [here](https://github.com/Expensify/App/pull/45327#discussion_r1794093817)

One way to get this warning is - in the development emulator:
Not a steps that a regular user could follow:
1. Open App
1. Go to the settings page
1. Overwrite the hasCompletedGuidedSetupFlowSelector(onboarding function to return false
![image](https://github.com/user-attachments/assets/9fdd5d8a-4732-4458-b785-f0292bac0953)

this is mainly developer experience improvement as it is misleading and slowing down the developers if they run into issues like this

### Solution

Make sure we cannot run into this warning

<details><summary>Issue Owner</summary>Current Issue Owner: @strepanier03</details>

**Comment by mountiny** [comment] 2024-10-14 10:22
SWM will work on this

**Comment by adamgrzybowski** [comment] 2024-10-14 10:27
Hi, I will take care of that 👋

**Comment by mountiny** [comment] 2024-10-14 10:37
thanks!

**Comment by s77rt** [comment] 2024-10-14 11:25
Checking this again, I'm not exactly sure how I reproduced the bug but either way making the function platform specific should do

**Comment by mountiny** [comment] 2024-10-15 02:39
$125 to @s77rt as it was just an emulator DX improvement

**Comment by strepanier03** [comment] 2024-10-15 23:02
Looks like the PR went to staging so once it's on prod I'll set a start timer on the payment hold.

**Comment by s77rt** [comment] 2024-10-20 10:44
- The PR that introduced the bug has been identified: https://github.com/Expensify/App/pull/45327
- The offending PR has been commented on: https://github.com/Expensify/App/pull/45327#discussion_r1794093817
- A discussion in #expensify-bugs has been started: Not needed
- Determine if we should create a regression test for this bug: No

**Comment by s77rt** [comment] 2024-10-24 18:37
It's $125 ^

**Comment by strepanier03** [comment] 2024-10-25 03:12
@s77rt - Okay, I've updated the price in the payment summary above and I see your checklist [responses](https://github.com/Expensify/App/issues/50713#issuecomment-2424835945). Feel free to request in New Expensify.

**Comment by JmillsExpensify** [comment] 2024-10-25 11:41
$125 approved for @s77rt

**Comment by strepanier03** [comment] 2024-10-25 17:26
This is all paid, closing now.

**Closed by strepanier03** 2024-10-25 17:26 UTC
Labels: Daily, Awaiting Payment, Bug
