### ISSUE TITLE
[HOLD FOR 45043] [$250] Report - "Uploading attachment..." message disappears after restarting the app in offline

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#45338] opened 2024-07-12 13:36 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 9.0.6-2
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**If this was caught during regression testing, add the test name, ID and link from TestRail:** https://expensify.testrail.io/index.php?/tests/view/4695551
**Email or phone of affected tester (no customers):** sustinov@applausemail.com
**Issue reported by:** Applause - Internal Team

## Action Performed:
1. Open New Expensify app
2. Navigate to any conversation
3. Turn off the Internet
4. Send an image to the conversation
5. Reload the application(⇧-⌘-R)
6. Return to the conversation with the sent attachment
7. Turn on the Internet

## Expected Result:
The message "Uploading attachment..." should be visible in the conversation after reloading the app in offline mode

## Actual Result:
"Uploading attachment..." message disappears in the conversation after reloading the application in offline mode

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [ ] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details> 

https://github.com/user-attachments/assets/bde2a3ce-518a-47f4-88ab-28aebdca8632

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01c0c3582f7d243cde</li>
        <li>Upwork Job ID: 1812449609428388373</li>
        <li>Last Price Increase: 2024-07-21</li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @rushatgabhane</details>

**Comment by lanitochka17** [comment] 2024-07-12 13:37
@bfitzexpensify  FYI I haven't added the External label as I wasn't 100% sure about this issue. Please take a look and add the label if you agree it's a bug and can be handled by external contributors

**Comment by lanitochka17** [comment] 2024-07-12 13:37
We think that this bug might be related to #vip-vsp

**Comment by tsa321** [comment] 2024-07-15 03:50
## Proposal

### Please re-state the problem that we are trying to solve in this issue.

"Uploading attachment..." message disappears after restarting the app in offline

### What is the root cause of that problem?

The problem arises because when users add attachments while offline, the optimistic report action fails to be saved in Onyx. This issue comes from a recent update in react-native-onyx, specifically in `utils.js` (In [this PR](https://github.com/Expensify/react-native-onyx/pull/563)), where the `mergeObject` function was modified. The change replaced the usage of `Object.keys` with a `for (key in object)` loop when merging objects. This changes causes the `attachmentInfo` object, which undergoes merging, to include additional fields, as shown in the screenshots below:

- **Using `for...in` loop:**
  ![Screenshot 2024-07-15 at 10 18 51 _ed](https://github.com/user-attachments/assets/7a56ad1e-82ef-45c7-9472-b674a40acf71)

- **Using `Object.keys`:**
  ![Screenshot 2024-07-15 at 10 23 39](https://github.com/user-attachments/assets/95f114a5-3de8-47e0-8c4c-0fc5d4289234)

The attachmentInfo includes `arrayBuffer`, `slice function`, `stream function`, etc, which will make Onyx to fail when merging the optimistic report action, resulting in an error in the ss below:

### What changes do you think we should make in order to solve the problem?

To resolve this issue, we can revert the mergeObject of utils.js to use `Object.keys` to retrieve the keys of the source and target objects during merging. Below are the reverted code snippets for both the target and source:

```javascript
// Reverted code for the target:
const targetKeys = Object.keys(targetObject);
for (let i = 0; i < targetKeys.length; ++i) {
    const key = targetKeys[i];
    ...
}

// Reverted code for the source:
const sourceKeys = Object.keys(source);
for (let i = 0; i < sourceKeys.length; ++i) {
    const key = sourceKeys[i];
    const sourceValue = source?.[key];
    ...
}
```











When user add attachment when offline, the optimistic report action is failed to be saved in onyx.
This is because of recent [PR](https://github.com/Expensify/react-native-onyx/pull/563) in react native onyx which make changes in `mergeObject` of [utils.js](https://github.com/Expensify/react-native-onyx/pull/563/files#diff-98e56006aa8453a29bc2b8bc8e6f718b3f17ba66470f3a52a5dc5bd643482e70). 

The changes is from using `Object.keys` of source and target object into using `for (key in the object)` when merging the object. This will make  the object of `attachmentInfo` that will be merged contains other fields like in the screen shoot below. Here is the comparison:

Using for key in object:
![Screenshot 2024-07-15 at 10 18 51 _ed](https://github.com/user-attachments/assets/7a56ad1e-82ef-45c7-9472-b674a40acf71)

Using Object.keys:
![Screenshot 2024-07-15 at 10 23 39](https://github.com/user-attachments/assets/95f114a5-3de8-47e0-8c4c-0fc5d4289234)

This will make the onyx fails to merge the optimistic reportAction. Here is the error ss:


 

### What changes do you think we should make in order to solve the problem?

We should revert back to using Object.keys to retrieve the keys of source and target object.

The reverted code of the target:

```javascript
const targetKeys = Object.keys(targetObject);
for (let i = 0; i < targetKeys.length; ++i) {
    const key = targetKeys[i];
```

The reverted code of the source:

```javascript
const sourceKeys = Object.keys(source);
for (let i = 0; i < sourceKeys.length; ++i) {
   const key = sourceKeys[i];
   const sourceValue = source?.[key];
```

###

**Comment by nkdengineer** [comment] 2024-07-15 03:53
This issue can be fixed [here](https://github.com/Expensify/App/pull/45043).

**Comment by rushatgabhane** [comment] 2024-07-17 07:39
@nkdengineer cool, we will hold on your PR

**Comment by rushatgabhane** [comment] 2024-07-26 02:17
same on hold

**Comment by kavimuru** [comment] 2024-08-12 23:10
Not reproducible

https://github.com/user-attachments/assets/d22e7990-e502-40c7-8e88-f15ec74aa053

**Comment by bfitzexpensify** [comment] 2024-08-13 08:24
Awesome, let's close this out.

**Closed by bfitzexpensify** 2024-08-13 08:24 UTC
Labels: External, Weekly, Help Wanted, Bug
