### ISSUE TITLE
Web - Chat - Chat not auto scrolled to the bottom when scrolling up and submitting expense

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#51492] opened 2024-10-25 18:52 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 9.0.54-0
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**If this was caught on HybridApp, is this reproducible on New Expensify Standalone?:** N/A
**If this was caught during regression testing, add the test name, ID and link from TestRail:** https://expensify.testrail.io/index.php?/tests/view/5136024&group_by=cases:section_id&group_order=asc&group_id=306202
**Issue reported by:** Applause - Internal Team

## Action Performed:
1. Open the staging.new.expensify.com website
2. Open any chat with large history of messages
3. Tap on "+" and select "Submit Expense"
4. Complete the expense creation flow
5. Delete the just created expense
6. Scroll to the top of the chat
7. Tap on "+" and select "Submit Expense"
8. Complete the expense creation flow
9. Once redirected to the chat, verify you are redirected to the bottom, to the new created expense

## Expected Result:
When scrolling up the chat and submitting an expense, the user should be navigated to the bottom again, to the new created expense

## Actual Result:
The chat is not auto scrolled to the bottom, when submitting an expense while scrolled up in the conversation, if another expense was deleted before in the same chat

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Standalone
- [ ] Android: HybridApp
- [ ] Android: mWeb Chrome
- [ ] iOS: Standalone
- [ ] iOS: HybridApp
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

<details>
  <summary>Add any screenshot/video evidence</summary>

  
</details> 

https://github.com/user-attachments/assets/23583abf-0e51-4465-86f3-7fb5c258c2b7

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by FitseTLT** [comment] 2024-10-25 21:16
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
Web - Chat - Chat not auto scrolled to the bottom when scrolling up and submitting expense

### What is the root cause of that problem?
When the expense is deleted from the chat report the `lastVisibleActionCreated` timestamp of the chat report should be updated to the last visible action's created timestamp but the BE is not updating it so here
https://github.com/Expensify/App/blob/a86ee35a6c9706d8acb35202acb4cdaa1cc769e7/src/pages/home/report/ReportActionsList.tsx#L345-L352
scrollToBottom will fail(early returns) because `hasNewestReportActionRef` will be false because the lastVisibleActionCreated is pointing to the created timestamp of the deleted `ReportPreview` action which is not visible.
### What changes do you think we should make in order to solve the problem?

Ideally this should be fixed in BE as I discussed it ^.
But we can also fix it in FE as the report actions deleted are not removed from `sortedReportActions` list we can change this 
https://github.com/Expensify/App/blob/a86ee35a6c9706d8acb35202acb4cdaa1cc769e7/src/pages/home/report/ReportActionsList.tsx#L286
```
    const hasNewestReportAction = sortedVisibleReportActions.at(0)?.created === lastVisibleActionCreated || sortedReportActions.at(0)?.created === lastVisibleActionCreated;

```
### What alternative solutions did you explore? (Optional)

**Comment by joekaufmanexpensify** [comment] 2024-10-28 15:42
Will triage today

**Comment by joekaufmanexpensify** [comment] 2024-10-28 22:18
I can reproduce this sometimes. But not everytime. Further, when I could reproduce it, going out of the chat and back in solves it. It also only seems to happen if there are no other expenses. If there's two, and you delete one, it works fine adding the second. 

I also don't think it will be super common that someone creates an expense, is moved to the bottom of the chat, immediately deletes it, scrolls up, and tries to create another expense. 

Given this one doesn't seem to be super consistently reproducible, and is a somewhat niche flow, I think we should close for now and re-prioritize if any actual customers experience this. LMK if anyone disagrees.

**Closed by joekaufmanexpensify** 2024-10-28 22:18 UTC
Labels: Daily, Bug
