### ISSUE TITLE
[PAID] [LOW] [Splits] [$500]  IOU - The user's name is displayed twice on the LHN after receiving payment

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#34525] opened 2024-01-15 18:50 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.25-1
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** Applause - Internal Team
**Slack conversation:**

## Action Performed:
1. Log in with User A and open User B's chat
2. Go to request money and enter the amount and completing the flow
3. Click on created IOU
4. Log in with User B from another browser and open User A's chat.
5. Click on IOU and then click on "Pay elsewhere"
6. After paying send a message in IOU and delete it
7. Go back to User A's account
8. Notice in LHN the user's name is displayed twice after deleting the last message

## Expected Result:
The user's name should be displayed once in the LHN

## Actual Result:
The user's name appears twice on the LHN after receiving payment

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [x] Android: mWeb Chrome
- [x] iOS: Native
- [x] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details> 

https://github.com/Expensify/App/assets/78819774/d72822b1-7d42-4a7f-8096-1966858c5cce

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01a34a9fdde701015a</li>
        <li>Upwork Job ID: 1746968111315644416</li>
        <li>Last Price Increase: 2024-02-07</li>
    </ul>
</details>

**Comment by Ykumar1415** [comment] 2024-01-15 19:40
I tried to reproduce this issue and  followed below steps 
Log in with User A and open User B's chat
Go to request money and enter the amount and completing the flow
Click on created IOU
Log in with User B from another browser and open User A's chat.
Click on IOU and then click on "Pay elsewhere"
After paying send a message in IOU and delete it
Go back to User A's account
Notice in LHN the user's name is displayed twice after deleting the last message

found the same error .

**Comment by FitseTLT** [comment] 2024-01-15 21:00
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
The user's name is displayed twice on the LHN after receiving payment

### What is the root cause of that problem?
When we delete a comment it is not deleted from the report action list of the report but only the `message.0.html` is reset to empty therefore so the last report action here will be wrongly set to this deleted message which hasn't been removed from the list
https://github.com/Expensify/App/blob/a4e3ae2546882b0971ed80e6ce0fd4c6b85cf956/src/libs/SidebarUtils.ts#L348-L349
### What changes do you think we should make in order to solve the problem?

We need to filter deleted comment report actions here so that we will not wrongly set a deleted comment report action as the last report action of the report
https://github.com/Expensify/App/blob/a4e3ae2546882b0971ed80e6ce0fd4c6b85cf956/src/libs/SidebarUtils.ts#L37-L38
```
        lastReportActions[reportID] = actionsArray.filter((action) => !(action.message?.[0].type === 'COMMENT' && action.message?.[0].html === ''))[actionsArray.length - 1];

```
or
We can also filter out deleted comments from `ReportActionsUtils.getSortedReportActions`
### What alternative solutions did you explore? (Optional)

**Comment by strepanier03** [comment] 2024-01-18 22:02
Working on repro'ing and tying to a wave/VIP. Will update when able.

**Comment by strepanier03** [comment] 2024-01-26 20:55
I'm going to close this out for now and if we can repro this we can reopen it.

**Comment by FitseTLT** [comment] 2024-01-26 20:57
Yes I did repoduce it on latest main now @strepanier03 

https://github.com/Expensify/App/assets/38649957/678b27a4-bfb6-4ffb-a8b8-cc359a606b7e

**Comment by FitseTLT** [comment] 2024-01-29 13:28
@strepanier03 This is still reproducible, only need to take a close note to the steps. ^

**Comment by strepanier03** [comment] 2024-01-30 18:00
@FitseTLT - Thanks for confirming, I did follow the repro steps closely and still cannot repro this so I'll ask another team member to test as well.

**Comment by FitseTLT** [comment] 2024-02-01 12:41
@parasharrajat Can U please check and confirm that this reproducible in latest main? 🙏

**Comment by strepanier03** [comment] 2024-02-05 18:39
Thanks @parasharrajat - Any update on the proposals?

**Comment by situchan** [comment] 2024-02-08 17:52
Taking this over as C+ from https://expensify.slack.com/archives/C02NK2DQWUX/p1707413964286239

**Comment by s77rt** [comment] 2024-02-13 00:15
@situchan Are you still the C+ here?

**Comment by situchan** [comment] 2024-02-13 02:31
yes, was waiting for assignment
cc: @strepanier03

**Comment by situchan** [comment] 2024-02-15 19:33
Thanks. reviewing proposals

**Comment by strepanier03** [comment] 2024-02-20 18:06
Any update on proposals @situchan?

**Comment by situchan** [comment] 2024-02-20 18:20
I am not able to reproduce on main

**Comment by situchan** [comment] 2024-02-26 16:45
updating today

**Comment by zboutchyard** [comment] 2024-03-13 23:35
does this issue still exist? Looks like there was a PR merged, but upwork just posted a job for this a few minutes ago.

**Comment by strepanier03** [comment] 2024-03-13 23:35
@situchan and @dukenv0307 - I have hired you both to the job in Upwork, please accept and I'll pay out today or more likely tomorrow morning. 

@situchan - Please complete the [checklist](https://github.com/Expensify/App/issues/34525#issuecomment-1981855545) and I'll finish up your payment once I have that and can do the reg test (if we need one).

**Comment by strepanier03** [comment] 2024-03-14 20:47
@dukenv0307 - Paid out! 

I'll keep an eye open for the checklist @situchan.

**Comment by situchan** [comment] 2024-03-14 20:55
Not able to find the exact offending PR as there were several refactors on LHN last message logic.
We can skip regression test as this was caught by QA team.

**Comment by strepanier03** [comment] 2024-03-15 16:43
Thanks @situchan, I'll update the checklist and finish this up.

**Comment by strepanier03** [comment] 2024-03-15 16:49
All set, contract closed. Thanks everyone!

**Closed by strepanier03** 2024-03-15 16:49 UTC
Labels: Engineering, Daily, Internal, Awaiting Payment, Bug
