### ISSUE TITLE
[HOLD for payment 2024-05-06] [$500] Chat - Missing 'Leave Thread' Button Offline in Self DM Thread

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#39618] opened 2024-04-04 15:08 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:**
**Reproducible in staging?:**
**Reproducible in production?:**
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:**
**Slack conversation:**

## Action Performed:
1. Click the search bar.
2. Type 'you' to start a self-DM.
3. Set status to offline.
4. Send a message and reply within the thread.
5. Click the three dots in the top right corner and observe the absence of the "Leave Thread" button.

## Expected Result:
The "Leave Thread" button should be present in the offline status within the thread of a self-DM.

## Actual Result:
When offline and within the thread of a self DM, after sending and replying to messages, the "Leave Thread" button is not available in the dropdown menu.

## Workaround:
n/a

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [x] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

https://github.com/Expensify/App/assets/93399543/3a83ef31-a477-4f90-b6e8-cbd5b8406d0b

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~0151b5f9abaa17e0bf</li>
        <li>Upwork Job ID: 1777699805163249664</li>
        <li>Last Price Increase: 2024-05-08</li>
<li>Automatic offers: </li>
<ul>
<li>shubham1206agra | Reviewer | 0</li>
</ul></li>
    </ul>
</details>

**Comment by kbecciv** [comment] 2024-04-04 15:09
We think that this bug might be related to v1.4.60-1

**Comment by nkdengineer** [comment] 2024-04-04 15:47
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
- Chat - Missing 'Leave Thread' Button Offline in Self DM Thread
### What is the root cause of that problem?
- When creating a thread in selfDM, we use ```chatType: "selfDM"``` in the optimistic data. And we do not display "Leave" button if report is selfDM, that leads to the bug
### What changes do you think we should make in order to solve the problem?
- We should not set ```chatType: "selfDM"``` in optimistic data if the parent report is selfDM

### What alternative solutions did you explore? (Optional)

- NA

**Comment by sonialiap** [comment] 2024-04-09 14:07
Moving to External

**Comment by sonialiap** [comment] 2024-04-09 14:07
@shubham1206agra what do you think of the proposal above?

**Comment by puneetlath** [comment] 2024-04-09 17:06
Hm, I'm confused. Should you be able to leave a thread in the selfDM? Can you do it when online? [This logic](https://github.com/Expensify/App/blob/5cb1d90f6625f846cddafe1448bacb6d4071f62a/src/pages/home/HeaderView.tsx#L147) makes it seem like no. 

cc @thienlnam

**Comment by puneetlath** [comment] 2024-04-09 17:31
Ok got it. Then what is this line for? https://github.com/Expensify/App/blob/5cb1d90f6625f846cddafe1448bacb6d4071f62a/src/pages/home/HeaderView.tsx#L147

**Comment by sonialiap** [comment] 2024-05-02 13:32
@puneetlath since you're BZ, could you please handle payment since it becomes due while I'm OOO (I'm OOO 2024-05-03 to 2024-05-06). If you don't get to it, I'll handle it on the 7th

**Comment by sonialiap** [comment] 2024-05-07 17:11
Payment summary:

- @shubham1206agra $250 - offer sent - please complete the [checklist](https://github.com/Expensify/App/issues/39618#issuecomment-2083832104) 
- @nkdengineer $250 - offer sent


https://www.upwork.com/ab/applicants/1777699805163249664/offers

**Comment by sonialiap** [comment] 2024-05-08 17:06
This issue was opened on the 4th and the change went into effect on the 5th. I agree, $500 it is. I'll update the offers 

<img width="994" alt="image" src="https://github.com/Expensify/App/assets/17131195/e6cd76f5-e213-4097-8799-e70bd51332e7">

**Comment by sonialiap** [comment] 2024-05-08 17:06
@shubham1206agra bump to complete the checklist ;)

**Comment by sonialiap** [comment] 2024-05-09 22:23
@nkdengineer please accept the offer in Upwork

**Comment by nkdengineer** [comment] 2024-05-10 18:56
> @nkdengineer please accept the offer in Upwork

@sonialiap It looks like the offer was for the wrong amount ($250), could you help double check, thanks 🙇

**Comment by sonialiap** [comment] 2024-05-10 19:08
@nkdengineer could you confirm if you're seeing the correct total in the amount on the offer? (I did not update the job title)

<img width="1369" alt="image" src="https://github.com/Expensify/App/assets/17131195/db2be465-4f99-4888-ab07-fc576fcca0d1">

**Comment by nkdengineer** [comment] 2024-05-13 16:03
@sonialiap Ah I see, all good, offer accepted 🙇

**Comment by sonialiap** [comment] 2024-05-13 18:12
👍 payment completed

**Closed by sonialiap** 2024-05-13 18:12 UTC
Labels: External, Daily, Awaiting Payment, Bug
