### ISSUE TITLE
[Payment due 8-18][$250] Group - Users with an external domain are displayed as Hidden in the group list

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#48464] opened 2024-09-03 12:25 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 9.0.27-0
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**If this was caught during regression testing, add the test name, ID and link from TestRail:** https://expensify.testrail.io/index.php?/tests/view/4909728
**Email or phone of affected tester (no customers):** sustinov@applausemail.com
**Issue reported by:** Applause - Internal Team

## Action Performed:
1. Open NewExpensify app
2. Log in to the new HT account
3. Create a group chat with two users [bob@domain.com](mailto:bob@domain.com)
and [alice@domain.com](mailto:alice@domain.com)
4. Open the list of members of the created group

## Expected Result:
Users with an external domain should be displayed by email or name in a group list

## Actual Result:
Users with an external domain are displayed as Hidden in the group list

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [x] iOS: Native
- [ ] iOS: mWeb Safari
- [ ] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details> 

https://github.com/user-attachments/assets/52a75928-874e-4436-9e93-c634b093af07

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~0181038d02cba6971d</li>
        <li>Upwork Job ID: 1831023091657812719</li>
        <li>Last Price Increase: 2024-09-03</li>
<li>Automatic offers: </li>
<ul>
<li>jjcoffee | Contributor | 103800323</li>
<li>nkdengineer | Contributor | 103829257</li>
</ul></li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @jjcoffee</details>

**Comment by lanitochka17** [comment] 2024-09-03 12:26
@Christinadobrzyn  FYI I haven't added the External label as I wasn't 100% sure about this issue. Please take a look and add the label if you agree it's a bug and can be handled by external contributors

**Comment by brad-isbell** [comment] 2024-09-03 15:46
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
Users with an external domain should be displayed by email or name in a group list
### What is the root cause of that problem?
The problem is [here](https://github.com/Expensify/App/blob/f270b0479a6abea9c44e89f8426ca66028c03fbb/src/libs/PersonalDetailsUtils.ts#L53). If a participant does not have a displayName it defaults to the text "Hidden".
### What changes do you think we should make in order to solve the problem?
We can simply check if the participant has either a displayName or an email ( eg: login ).
The new version will be :
```javascript
let displayName = passedPersonalDetails?.displayName ?? passedPersonalDetails?.login ?? '';
```
### What alternative solutions did you explore? (Optional)

Result:
<img width="374" alt="image" src="https://github.com/user-attachments/assets/ba034658-2c3e-41f2-bafb-ee954bc3d574">

**Comment by Christinadobrzyn** [comment] 2024-09-03 17:34
I can reproduce this. This `Hidden` user has been going on for a while. I don't know if we have another GH related to resolving this - I don't see one. I'm assuming this is a BE fix but adding external for a C+ review first.

**Comment by Christinadobrzyn** [comment] 2024-09-03 17:36
Side note: I'm going to be ooo 9/4-9/10. Adding a BZ teammate to monitor this - @abekkala this is brand new and I'm not sure if this needs to be external or internal so I first added a C+ to review. TY!

**Comment by jjcoffee** [comment] 2024-09-04 08:16
Thanks for the [proposal](https://github.com/Expensify/App/issues/48464#issuecomment-2326859728) @brad-isbell! 

Unfortunately I don't think this will entirely solve the issue here as I think for some reason the BE clears out certain emails from `personalDetailsList`, so there would be no value for `passedPersonalDetails?.login`. I see this, for example, if I log out and back in, the list of group members changes so that Bob & Alice are both `Hidden` with no email at all in their profiles. Weirdly if I invite a new user to the group chat and sign in with that user, I see all the emails displaying normally.

**Comment by nkdengineer** [comment] 2024-09-04 08:48
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
Users with an external domain are displayed as Hidden in the group list

### What is the root cause of that problem?
The `hidden` is displayed as expected because the personal detail has no `login` and `displayName` fields and `firstName`, `lastName` are empty strings. But we have a bug in the video of OP that is report participant detail page doesn't display `Hidden` as we did in `ReportParticipantPage`

The problem is here we only use `details.displayName` without falling back to `Hidden` as we do in [here](https://github.com/Expensify/App/blob/562d7b48226247253625b9ac1fd45266cb53eda8/src/pages/ReportParticipantsPage.tsx#L87)
https://github.com/Expensify/App/blob/562d7b48226247253625b9ac1fd45266cb53eda8/src/pages/ReportParticipantDetailsPage.tsx#L56


### What changes do you think we should make in order to solve the problem?
We should use `getDisplayNameOrDefault` function as we do in `ReportParticipantsPage` and also use `displayName` as the condition to check whether we should show the display name or not. Or we can remove this condition because we always fallback into hidden

```
const displayName = PersonalDetailsUtils.getDisplayNameOrDefault(details);
{!!(displayName ?? '') && (
    <Text
        style={[styles.textHeadline, styles.pre, styles.mb6, styles.w100, styles.textAlignCenter]}
        numberOfLines={1}
    >
        {displayName}
    </Text>
)}
```

https://github.com/Expensify/App/blob/562d7b48226247253625b9ac1fd45266cb53eda8/src/pages/ReportParticipantDetailsPage.tsx#L94


### What alternative solutions did you explore? (Optional)

**Comment by jjcoffee** [comment] 2024-09-05 12:14
@nkdengineer Do you see these users as hidden immediately? I only see it after signing out and back in, otherwise I see hidden _and_ the email address.

> Weirdly if I invite a new user to the group chat and sign in with that user, I see all the emails displaying normally.

I'd also like to see this explained. I'm leaning towards this being a BE issue, as I don't see why these emails specifically should be hidden for the user who added them to the group.

**Comment by jjcoffee** [comment] 2024-09-05 12:52
@nkdengineer Thanks, I see what you mean now! I agree the participant detail page should be fixed so that it doesn't show an empty string, but I think the BE is also incorrectly removing the email in these cases so I think that needs to be sorted too.

Let's go with @nkdengineer's [proposal](https://github.com/Expensify/App/issues/48464#issuecomment-2328278002) to fix up the empty name on the participant details page. We also need a potential BE fix if these emails are not supposed to be `Hidden`.

:ribbon::eyes::ribbon: C+ reviewed

**Comment by Christinadobrzyn** [comment] 2024-09-11 17:31
monitoring the PR - https://github.com/Expensify/App/pull/48681

**Comment by Christinadobrzyn** [comment] 2024-09-16 20:59
PR merged 4 days ago so adding a payment due date to this GH. https://github.com/Expensify/App/pull/48681

Payouts due:

- [ ] Contributor: $250 @nkdengineer (Upwork - https://www.upwork.com/nx/wm/workroom/38330876/overview)
- [ ] Contributor+: $250 @jjcoffee (Upwork - https://www.upwork.com/nx/wm/workroom/38275996/overview)

**Comment by jjcoffee** [comment] 2024-09-17 10:44
- The PR that introduced the bug has been identified. Link to the PR: https://github.com/Expensify/App/pull/39639
- The offending PR has been commented on, pointing out the bug it caused and why, so the author and reviewers can learn from the mistake. Link to comment: https://github.com/Expensify/App/commit/9dba74f24da04664948197aaca3681c85a236216#r146817794
- A discussion in #expensify-bugs has been started about whether any other steps should be taken (e.g. updating the PR review checklist) in order to catch this type of bug sooner. Link to discussion: N/A - this type of thing would be hard to catch in standard PR testing imo
- Determine if we should create a regression test for this bug. **Yes**
- If we decide to create a [regression test](https://github.com/Expensify/App/blob/main/contributingGuides/REGRESSION_TEST_BEST_PRACTICES.md) for the bug, please propose the regression test steps to ensure the same bug will not reach production again.

**Regression Test Proposal**

1. Create a group chat with two users ([bob@domain.com](mailto:bob@domain.com) and [alice@domain.com](mailto:alice@domain.com))
2. Open the list of members of the created group
3. Tap on one of the added users to open the participant details page
4. Verify that either the user's name, email or `Hidden` is displayed below the avatar (not an empty space)

Do we agree 👍 or 👎

**Comment by Christinadobrzyn** [comment] 2024-09-19 14:57
Ah thanks for the nudge @jjcoffee! 

Regression test - https://github.com/Expensify/Expensify/issues/429387
Payment is initiated in Upwork based on this summary - https://github.com/Expensify/App/issues/48464#issuecomment-2354023086

Closing!

**Closed by Christinadobrzyn** 2024-09-19 14:57 UTC
Labels: Reviewing, External, Weekly, Awaiting Payment, Bug
