### ISSUE TITLE
[HOLD for payment 2024-06-05] [$250] [Track Tax] Unable to save tax amount which is below the limit for scan request

### ISSUE THREAD

**Issue by m-natarajan** [Expensify/App#41434] opened 2024-05-01 18:05 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.69-0
**Reproducible in staging?:** y
**Reproducible in production?:** no 
**If this was caught during regression testing, add the test name, ID and link from TestRail:** n/a
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** Applause internal team 
**Slack conversation:**

## Action Performed:
Precondition:
- Workspace has a few tax rates.

1. Go to staging.new.expensify.com
2. Go to workspace chat.
3. Submit a scan expense with a valid receipt.
4. After the scanning is complete, go to transaction thread.
5. Click Tax.
6. Change to a different (non-zero) tax rate.
7. Click Tax amount.
8. Enter any tax amount as long as it is below the limit.
9. Save it.

## Expected Result:
App will save the tax amount as long as it is below the limit.

## Actual Result:
App is unable to save the tax amount. Error "Maximum tax amount is MYR 0.00" shows up.

## Workaround:
unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [x] Android: mWeb Chrome
- [x] iOS: Native
- [x] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

https://github.com/Expensify/App/assets/38435837/39bfc331-5ece-48b5-8fef-707bb4ae56df

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~0147258a467490a0c2</li>
        <li>Upwork Job ID: 1785767395280666624</li>
        <li>Last Price Increase: 2024-05-01</li>
<li>Automatic offers: </li>
<ul>
<li>shubham1206agra | Reviewer | 0</li>
<li>Nodebrute | Contributor | 0</li>
</ul></li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @isabelastisser</details>

**Comment by m-natarajan** [comment] 2024-05-01 18:11
@isabelastisser FYI I haven't added the External label as I wasn't 100% sure about this issue. Please take a look and add the label if you agree it's a bug and can be handled by external contributors.

**Comment by m-natarajan** [comment] 2024-05-01 18:11
We think this bug might be related to #wave-collect - Release 1

**Comment by blimpich** [comment] 2024-05-01 18:22
@Krishna2323 @Ollyws looks like it might be related to https://github.com/Expensify/App/pull/41264. Can you take a look?

**Comment by blimpich** [comment] 2024-05-01 20:24
Chatted in slack [here](https://expensify.slack.com/archives/C01GTK53T8Q/p1714592123942889), going to treat this as a separate issue.

**Comment by blimpich** [comment] 2024-05-01 21:05
Not a blocker I think, though I am a little on the fence here. I think that since collect in new dot is still new and this seems more like a polish item it can be considered not a blocker.

**Comment by Nodebrute** [comment] 2024-05-02 08:57
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
Unable to save tax amount which is below the limit for scan request
### What is the root cause of that problem?
Here we are passing taxAmount which we are getting from `getTaxAmount` and we are passing `transaction`.
https://github.com/Expensify/App/blob/1c651a1ac7c6af25df9459861ba4128e8d50e2fb/src/pages/iou/request/step/IOURequestStepTaxAmountPage.tsx#L153


In  `getTaxAmount` we return early if we don't have amount. In case of scan the transaction.amount will be 0 and this function will return early.
https://github.com/Expensify/App/blob/1c651a1ac7c6af25df9459861ba4128e8d50e2fb/src/pages/iou/request/step/IOURequestStepTaxAmountPage.tsx#L38-L40
### What changes do you think we should make in order to solve the problem?

We should add a check if transaction.amount is 0 then check for modifiedAmount

We can do something like this 
```
// If neither `amount` nor `modifiedAmount` is present, return early
 if (!transaction?.amount && !transaction?.modifiedAmount) {
        return;
    }
```
### What alternative solutions did you explore? (Optional)
Instead of passing transaction to the getTaxAmount function, we can use transactionDetails here and adjust the code.

**Comment by isabelastisser** [comment] 2024-05-07 21:47
Bump @blimpich to review the proposal and assign @Nodebrute. Thanks!

**Comment by isabelastisser** [comment] 2024-06-05 18:43
Hey, @shubham1206agra, please complete the BZ list above. Thanks!

**Comment by isabelastisser** [comment] 2024-06-05 18:47
Payment processed in Upwork for @Nodebrute!

@shubham1206agra, your offer is still pending in Upwork. Please accept it and I will process the payment. Thanks!

**Comment by isabelastisser** [comment] 2024-06-06 19:24
Bumo @shubham1206agra to accept the offer in Upwork.

Closing.

**Closed by isabelastisser** 2024-06-06 19:24 UTC
Labels: External, Engineering, Daily, Awaiting Payment, Bug

**Comment by isabelastisser** [comment] 2024-06-07 10:13
Hey @shubham1206agra, can you please complete the checklist? Thanks!

https://github.com/Expensify/App/issues/41434#issuecomment-2136927457
