### ISSUE TITLE
[HOLD for payment 2023-06-15] [$1000] The cursor does not move to the next line after pressing Shift+Enter while using the mention feature.

### ISSUE THREAD

**Issue by kavimuru** [Expensify/App#19624] opened 2023-05-25 19:10 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:

1. Go to any chat.
2. Type "@" and press Shift+Enter.
3. Notice that instead of moving to the next line, the user is selected from the popup.

## Expected Result: 
The cursor should move to the next line when Shift+Enter is pressed.
## Actual Result: 
The cursor does not move to the next line when Shift+Enter is pressed. Instead, the first option from the popup is selected when using the mention feature.
NOTE: Same happening with emoji too

## Workaround:
Can the user still use Expensify without this being fixed? Have you informed them of the workaround?

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [x] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 1.3.18-2
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/43996225/d26a5aee-163d-4acf-8c08-5a4634e4664d

https://github.com/Expensify/App/assets/43996225/f9bffdae-0e8b-4d25-8403-b832903f83f6

**Expensify/Expensify Issue URL:**
**Issue reported by:** @usmantariq96
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1684834428858769

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01830e384c4fcaaa98</li>
        <li>Upwork Job ID: 1663633838374625280</li>
        <li>Last Price Increase: 2023-05-30</li>
    </ul>
</details>

**Comment by dukenv0307** [comment] 2023-05-26 02:11
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
The cursor does not move to the next line after pressing Shift+Enter while using the mention feature
### What is the root cause of that problem?
https://github.com/Expensify/App/blob/21fefdb19cd7262f9caaad132d30ea426426f017/src/pages/home/report/ReportActionCompose.js#L796-805
If the suggestion is open and we click Enter, we will insert the suggestion into the composer (even if Enter is triggered with another button)

### What changes do you think we should make in order to solve the problem?
https://github.com/Expensify/App/blob/21fefdb19cd7262f9caaad132d30ea426426f017/src/pages/home/report/ReportActionCompose.js#L796
Here we should add a condition !e.shiftKey like this
```
 if (((e.key === CONST.KEYBOARD_SHORTCUTS.ENTER.shortcutKey && !e.shiftKey) || e.key === CONST.KEYBOARD_SHORTCUTS.TAB.shortcutKey) && suggestionsExist) {

```

### What alternative solutions did you explore? (Optional)
NA

**Comment by twisterdotcom** [comment] 2023-05-30 19:49
Okay, making it external: https://expensify.slack.com/archives/C049HHMV9SM/p1685126834069999?thread_ts=1684834428.858769&cid=C049HHMV9SM

**Comment by code0406** [comment] 2023-06-01 05:21
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
The cursor does not move to the next line when Shift+Enter is pressed (when suggestions and emoji panels are opened.)

### What is the root cause of that problem?
Because it was not processed in the KEY event module.

### What changes do you think we should make in order to solve the problem?
We should consider the "Shift" key-pressed event in the current key event module.

### What alternative solutions did you explore? (Optional)
I've checked and confirmed it 100%. 
I shared the video that I fixed this issue.

https://github.com/Expensify/App/assets/108268728/6fe771a3-a7f1-4c06-9e99-733045d946a7

**Comment by code0406** [comment] 2023-06-01 05:24
Contributor details
Your Expensify account email: d842443@gmail.com
Upwork Profile Link: https://www.upwork.com/freelancers/~01b5053339c1ddbe12

**Comment by mollfpr** [comment] 2023-06-01 07:22
>Because it was not processed in the KEY event module.

@code0406 Which key do you mean?

**Comment by code0406** [comment] 2023-06-01 07:25
> > Because it was not processed in the KEY event module.
> 
> @code0406 Which key do you mean?

I will share the screenshot. 
This is the code part to be fixed for the issue. 
![image](https://github.com/Expensify/App/assets/108268728/e09d62f1-0b94-48ec-bb7d-3c9bcb0ebd93)

If you need, I will share the code diff. 
Thank you.

**Comment by code0406** [comment] 2023-06-01 07:32
> > Because it was not processed in the KEY event module.
> 
> @code0406 Which key do you mean?

The current code is almost perfect. 
So we don't need to change or clear any data. 

1. just check the Shift Key pressed case, 
2. call the useful function that was implemented already. 

That's all.

**Comment by mollfpr** [comment] 2023-06-01 07:32
@dhairyasenjaliya Thanks. I almost forget there’s another proposal above.

**Comment by code0406** [comment] 2023-06-01 12:51
## Proposal
[Updated]https://github.com/Expensify/App/issues/19624#issuecomment-1571358607

**Comment by mollfpr** [comment] 2023-06-01 16:26
```
e.key === CONST.PLATFORM_SPECIFIC_KEYS.SHIFT && e.key === CONST.KEYBOARD_SHORTCUTS.ENTER.shortcutKey && suggestionsExist
```

@dhairyasenjaliya Is it possible that `e.key` has both value shift and enter simultaneously?

**Comment by mollfpr** [comment] 2023-06-01 16:31
```js
         if (e.key === CONST.PLATFORM_SPECIFIC_KEYS.SHIFT && e.key === CONST.KEYBOARD_SHORTCUTS.ENTER.shortcutKey && suggestionsExist) {
            e.preventDefault();
            if (suggestionsExist) {
                this.resetSuggestions();
            } else if (this.comment.length > 0) {
                this.updateComment('', true);
            }
            return;
        }


```

@dhairyasenjaliya Could you elaborate on the above diff from your proposal? I didn't find it needs.

**Comment by mollfpr** [comment] 2023-06-01 17:18
Thanks @dhairyasenjaliya. Could you update your proposal accordingly with the above comment?

**Comment by mollfpr** [comment] 2023-06-01 17:35
@cristipaval the proposal from @dhairyasenjaliya looks good to me!

🎀 👀 🎀 C+ reviewed!

**Comment by code0406** [comment] 2023-06-01 17:35
@mollfpr 

I shared the detail code here again. and updated my proposal, too. https://github.com/Expensify/App/issues/19624#issuecomment-1571358607

1. Check if the "Shift" key is pressed in Emoji, suggestion cases. Other cases are working well. 
if (e.shiftKey) //detect the shift key pressed

2. if the key was pressed, then skip the Emoji, and suggestion actions and close the panel.
if (e.shiftKey)
    this.setShouldShowSuggestionsMenuToFalse();
    
 Please feel free to ask anything else. 
 Thank you.

**Comment by mollfpr** [comment] 2023-06-01 17:38
Sorry @dukenv0307, your solution is the same, and @dhairyasenjaliya proposes it first.

**Comment by code0406** [comment] 2023-06-01 17:46
😄 . 
@mollfpr 
You can see the best solution(optimized) here. https://github.com/Expensify/App/issues/19624#issuecomment-1571358607
Added only 4 lines for the 2 cases(Emoji, Suggestions). 
💯

**Comment by mollfpr** [comment] 2023-06-01 17:59
> Because it was not processed in the KEY event module.

@code0406 Your root cause does not explain the problem and how the issue produces, and I'd still stand by the choice.

**Comment by mollfpr** [comment] 2023-06-01 18:00
> ALL NEW PROPOSALS MUST BE DIFFERENT FROM EXISTING PROPOSALS. The difference should be important, meaningful or considerable.

@dukenv0307 @dhairyasenjaliya

**Comment by code0406** [comment] 2023-06-01 18:05
> > Because it was not processed in the KEY event module.
> 
> @code0406 Your root cause does not explain the problem and how the issue produces, and I'd still stand by the choice.

I just updated the content now. 
Please check it again. I am sure 100% it's the perfect solution.
Thank you. 

https://github.com/Expensify/App/issues/19624#issuecomment-1571358607

**Comment by mollfpr** [comment] 2023-06-01 18:06
@dukenv0307 No worries 👍

**Comment by code0406** [comment] 2023-06-01 18:08
@mollfpr , did you check my quote? 
https://github.com/Expensify/App/issues/19624#issuecomment-1572548707

**Comment by mollfpr** [comment] 2023-06-01 18:13
> Refrain from leaving additional comments until someone from the Contributor-Plus team and / or someone from Expensify provides feedback on your proposal (do not create a pull request yet).

@code0406 I already reviewed all the proposals and made the choice. So please wait until @cristipaval has a second thought.

**Comment by code0406** [comment] 2023-06-02 20:33
@mollfpr , @cristipaval 
How are you? Still no update for this issue?

**Comment by twisterdotcom** [comment] 2023-06-05 10:05
@cristipaval bump on this please.

**Comment by cristipaval** [comment] 2023-06-05 11:11
> @cristipaval the proposal from @dhairyasenjaliya looks good to me!
> 
> 🎀 👀 🎀 C+ reviewed!

Thanks @mollfpr !

@dhairyasenjaliya you're all set.

**Comment by twisterdotcom** [comment] 2023-06-06 22:53
Oooh! Merged.

**Comment by twisterdotcom** [comment] 2023-06-15 17:00
Okay, I confess I'm a little confused here folks. Is there any penalty for the regression at all?

**Comment by twisterdotcom** [comment] 2023-06-15 17:03
Sorry folks, I've been getting this all day:
<img width="947" alt="image" src="https://github.com/Expensify/App/assets/9133401/7aa05995-6257-4e4f-b993-13ebe2e37706">

**Comment by twisterdotcom** [comment] 2023-06-19 15:35
https://github.com/Expensify/Expensify/issues/293145

**Closed by twisterdotcom** 2023-06-19 15:35 UTC
Labels: External, Daily, Awaiting Payment, Bug
