### ISSUE TITLE
[$500]  Deeplinks - Public room conversation opened when tapped on user share profile deeplink

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#31239] opened 2023-11-11 17:35 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.3.98.0
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** Applause - Internal Team
**Slack conversation:**

## Action Performed:
1. Open app
2. Sign Out
3. Paste this link in other app (messenger or notes) https://staging.new.expensify.com/r/3504895439653267
4. Click on the deeplink from previous step
5. Once app opened and public room displayed as a guest click on Sign In button
6. Sign In with valid account
7. Click back button to navigate to LHN
8. Kill the app
9. Paste this link in other app (messenger or notes) https://staging.new.expensify.com/a/15548487
10. Click on the deeplink from previous step

## Expected Result:
User profile should be displayed

## Actual Result:
Public room conversation opened

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [ ] Android: mWeb Chrome
- [x] iOS: Native
- [ ] iOS: mWeb Safari
- [ ] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

https://github.com/Expensify/App/assets/93399543/2a4fb900-4a1d-43c1-aad0-1854337f7f8e

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01f7fa12128d4cc313</li>
        <li>Upwork Job ID: 1723394105381797888</li>
        <li>Last Price Increase: 2023-11-11</li>
    </ul>
</details>

**Comment by erquhart** [comment] 2023-11-11 21:10
Related, maybe same rca: https://github.com/Expensify/App/issues/31150

**Comment by sudhakar-s** [comment] 2023-11-12 20:14
**Please re-state the problem that we are trying to solve in this issue.**
Universal deeplinking for profile page

**What is the root cause of that problem?**

Noticed that as of today, current implementation for universal linking seems to be only supporting chat report and no other pages([Ref](https://github.com/Expensify/App/blob/main/src/Expensify.js#L181)). so links starts with `https://*.new.expensify `aka universal linking only supports chat report which may not be the case for traditional deeplinking(starts with `new-expensify://*`).

Addressing this issue might mean, setting up universal deeplinking support similar to [linkingConfig](https://github.com/Expensify/App/blob/main/src/libs/Navigation/linkingConfig.js#L8) by extending  Linking.getInitialURL(). 

What should be the next step here if this is known limitation?

**Comment by sudhakar-s** [comment] 2023-11-12 20:27
Contributor details
Your Expensify account email: s.sudhakar.engineer@gmail.com
Upwork Profile Link: https://www.upwork.com/freelancers/~015764c2295330a830

**Comment by getusha** [comment] 2023-11-15 14:27
The proposal made by @dukenv0307 looks good and the root cause and the solution makes sense to me!
https://github.com/Expensify/App/issues/31239#issuecomment-1807199905

🎀 👀 🎀 C+ reviewed

**Comment by getusha** [comment] 2023-11-19 04:50
I checked https://github.com/Expensify/App/issues/31239#issuecomment-1812931346 and it's the current behavior on staging/main.

IMHO it makes sense if the public room opens after i killed the app then reopened it and i am not confident removing the current behavior. @dukenv0307's proposal will fix this issue while keeping that behavior. 

@bernhardoj to know whether we should remove this behavior or not could you raise this to `expensify-open-source` i am happy to re-consider after confirmation.

**Comment by getusha** [comment] 2023-11-19 11:05
@bernhardoj I don't understand how the issue is similar to this behavior. The bug is when you open the app from deep link not when reopening, which definitely should be fixed.

**Comment by getusha** [comment] 2023-11-19 12:41
>Wrong, it also happens by opening it normally. It doesn't matter how you open it.

It does matter, if i am opening a link for specific chat i want that specific chat to open, if i am opening the app directly without any link and it happens that's the expected behavior and not a bug for now.

**Comment by sudhakar-s** [comment] 2023-11-19 16:28
Newbie here!.  As per the issue description, issue seems to be related to universal deeplink not working for profile page(CMIIW) - [I have replied here in details](https://github.com/Expensify/App/issues/31239#issuecomment-1807227342)

> why should a user be brought back to the last opened public room when they reopen the app?

I thought this could be product ask.

**Comment by getusha** [comment] 2023-11-19 17:05
>I don't know if we are on the same page but every statement doesn't make sense to me.

> Idk why but it feels like you are very afraid of my proposal 😅

@bernhardoj As I said, in my opinion, it makes sense for the app to open the public room I recently accessed when I reopen the app, after having accessed the room anonymously, clicked sign in and then closing the app.
However, if I open the app by clicking on a specific link to a specific page (profile page in this case) and it instead opens the recently accessed public room, this would be considered a bug. that's my opinion and it is why i suggested you to raise this to `expensify-open-source`

> Now, let's say everything you said is correct. Then, what would you say with this case:
>* Log out
>* Open public room
>* Press sign in
>* Close the app
>* Deeplink to ANOTHER public room

@dukenv0307 could you confirm if this case is handled in your proposal?

> Again, why should a user be brought back to the last opened public room when they reopen the app? Why only public room? Why only when logged out? Why only after they press sign in? Is it a very special room? 

Let's keep our conversation civil 🙂. We can discuss this matter in more depth if you raise it on `expensify-open-source`. It seems like there might be an assumption that I'm not fully understanding your concern and the expected outcome. Therefore, it would be better if you could address this issue. Can you confirm if you're able to do so? Otherwise, I can get the conversation started.

**Comment by greg-schroeder** [comment] 2023-11-26 20:08
Let's chill out a bit here and wait for @MariaHCD to come back this week and take a look/weigh in. 👍

**Comment by mvtglobally** [comment] 2023-11-30 06:06
Issue not reproducible during KI retests. (First week)

**Comment by MariaHCD** [comment] 2023-12-04 15:04
Waiting on @kbecciv to confirm that this is still reproducible.

**Comment by kbecciv** [comment] 2023-12-04 20:54
Issue is not reproduced

https://github.com/Expensify/App/assets/93399543/c89f2d08-6ce8-48c0-9296-e59e009e20a1

**Comment by greg-schroeder** [comment] 2023-12-07 19:42
Okay, perhaps we can close this then?

**Comment by getusha** [comment] 2023-12-08 04:13
I think the majority opinion is to do nothing since either way will work https://expensify.slack.com/archives/C01GTK53T8Q/p1700580479451839?thread_ts=1700455132.577509&cid=C01GTK53T8Q https://expensify.slack.com/archives/C01GTK53T8Q/p1700584101131529?thread_ts=1700455132.577509&cid=C01GTK53T8Q when reopening the app, as of this issue it is not reproducible anymore when we open the app from a link to specific page, i'd say to do nothing.

**Closed** 2023-12-11 10:03 UTC
Labels: Engineering, Daily, Internal, Overdue, Bug

**Comment by MariaHCD** [comment] 2023-12-11 11:46
I think the issue is definitely a bit niche and I don't think it's worth the effort to fix it, IMHO. So I agree with @greg-schroeder's decision to close this.
