### ISSUE TITLE
[HOLD for payment 2024-03-25] [Wave Collect] [Workflows] "Delayed Submissions" toggle does not toggle off unless backed out for Collect Policy

### ISSUE THREAD

**Issue by kavimuru** [Expensify/App#38198] opened 2024-03-13 05:36 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.51-0
**Reproducible in staging?:** y
**Reproducible in production?:** n
**If this was caught during regression testing, add the test name, ID and link from TestRail:** N/A
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** applause internal team
**Slack conversation:**

## Action Performed:
1. Access staging.new.expensify.com
2. Sign into a collect policy WS Admin account
3. Go to workspace setting > Workflows
4. Toggle ON "Delay Submissions" then attempt to Toggle OFF

## Expected Result:
User should be able to Toggle on and off with no problems

## Actual Result:
The Toggle off does not work, the user must back out and return to see the toggle turn off

## Workaround:
unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [x] iOS: Native
- [x] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

https://github.com/Expensify/App/assets/43996225/d2e5ecf8-42e2-49e8-8fb2-f7588b649395

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Issue Owner</summary>Current Issue Owner: @trjExpensify</details>

**Comment by kavimuru** [comment] 2024-03-13 05:36
@MonilBhavsar FYI I haven't added the External label as I wasn't 100% sure about this issue. Please take a look and add the label if you agree it's a bug and can be handled by external contributors.

**Comment by ahmedGaber93** [comment] 2024-03-13 06:06
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
"Delayed Submissions" toggle does not toggle off unless backed out for Collect Policy

### What is the root cause of that problem?
we always return harvesting.enable = true in `optimisticData`
https://github.com/Expensify/App/blob/ce3da4efec9861e29e07b3f7319c82d7cdcd6cac/src/libs/actions/Policy.ts#L436-L449
### What changes do you think we should make in order to solve the problem?
we need to change harvesting.enable  in `optimisticData` to be 
```javascript
harvesting: {
  // enabled: true, 
  enabled,
},
```

### What alternative solutions did you explore? (Optional)

**Comment by MonilBhavsar** [comment] 2024-03-13 07:24
Commented in the offending PR https://github.com/Expensify/App/pull/37441/files#r1522658153

**Comment by mountiny** [comment] 2024-03-13 10:57
@MonilBhavsar happy to take over this one since I have worked with Michal on that change

**Comment by mountiny** [comment] 2024-03-13 10:58
Since this is not really out there for customers, demoting from a blocker

**Comment by mountiny** [comment] 2024-03-13 11:02
Assigning @DylanDylann to fix this issue as part of Wave Collect with urgency

**Comment by zanyrenney** [comment] 2024-03-21 18:21
The only thing remaining is the payout. This just a note to say that I am OOO now until April 2nd, reassigning a BZ team member to help while I am OOO.

**Comment by DylanDylann** [comment] 2024-03-25 04:34
BugZero Checklist: The PR fixing this issue has been merged! The following checklist ([instructions](https://stackoverflow.com/c/expensify/questions/14574)) will need to be completed before the issue can be closed:

 [@DylanDylann] The PR that introduced the bug has been identified. Link to the PR: https://github.com/Expensify/App/pull/37441
 [@DylanDylann] The offending PR has been commented on, pointing out the bug it caused and why, so the author and reviewers can learn from the mistake. Link to comment: https://github.com/Expensify/App/pull/37441/files#r1522658153
 [@DylanDylann] A discussion in #expensify-bugs has been started about whether any other steps should be taken (e.g. updating the PR review checklist) in order to catch this type of bug sooner. Link to discussion: **NA**
 [@DylanDylann] Determine if we should create a regression test for this bug. **No**
 [@DylanDylann] If we decide to create a [regression test](https://github.com/Expensify/App/blob/main/contributingGuides/REGRESSION_TEST_BEST_PRACTICES.md) for the bug, please propose the regression test steps to ensure the same bug will not reach production again.


### Regression Test Proposal (If the internal engineer determines that we should create a regression test)

1. Sign into a collect policy WS Admin account
2. Go to workspace setting > Workflows
3. Toggle ON "Delay Submissions" then attempt to Toggle OFF
4. Verify that we can Toggle on and off with no problems


Do we agree 👍 or 👎

**Comment by s77rt** [comment] 2024-03-25 14:29
No payment is due for me here. I'm assigned in https://github.com/Expensify/App/issues/37373 where payment will be handled

**Comment by trjExpensify** [comment] 2024-03-25 15:18
Cool, sounds good. Thanks for declining! @DylanDylann paid!

**Closed by trjExpensify** 2024-03-25 15:18 UTC
Labels: Engineering, Daily, Awaiting Payment, Bug
