### ISSUE TITLE
[HOLD for payment 2024-03-04] [$500] iOS-Chat not scrolled to bottom if delete last message by edit > clear comment > apply changes

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#35835] opened 2024-02-05 16:31 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.36-1
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** Applause - Internal Team
**Slack conversation:**

## Action Performed:
1. Log in to New Expensify
2. Navigate to a chat with a few messages
3. Hold last message
4. Tap Edit message
5. Clear compose box
6. Tap apply changes

## Expected Result:
The edited message should be deleted, and chat history should be scrolled to the very bottom

## Actual Result:
The edited message is deleted, but chat history is not scrolled to the bottom. There is one or two messages below

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [x] iOS: Native
- [ ] iOS: mWeb Safari
- [ ] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details> 

https://github.com/Expensify/App/assets/78819774/e65ca9fe-7706-4622-b0e2-4df2792d7ffc

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01a3b81b8f8d63b5f3</li>
        <li>Upwork Job ID: 1754543250858106880</li>
        <li>Last Price Increase: 2024-02-05</li>
<li>Automatic offers: </li>
<ul>
<li>jeremy-croff | Contributor | 0</li>
</ul></li>
    </ul>
</details>

**Comment by jeremy-croff** [comment] 2024-02-06 06:27
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
We don't presreve the scroll position after deleting a message through the edit flow.

### What is the root cause of that problem?
Only in IOS, we are maintaing focus on the composer. So the keyboard shows up during edit, shifts the scroll. After delete, we don't have the keyboard, and the scroll position is lost. On other platforms we focus the composer and the keyboard gets shown again, preserving the scroll.

### What changes do you think we should make in order to solve the problem?
We have a nice utility to preserve the scroll
`reportScrollManager.scrollToIndex(index, false);`

Using this utility after the delete draft here: https://github.com/Expensify/App/blob/500dd0949123ae1cd7b84211c0093f3c832d6775/src/pages/home/report/ReportActionItemMessageEdit.tsx#L298
will preserve the correct scroll position and address this issue. 

But how do we reconcile the logic with the existing scroll listeners on keyboard hide?
I looked closely at the conditions for the existing  reportScrollManager.scrollToIndex(index, false); here https://github.com/Expensify/App/blob/500dd0949123ae1cd7b84211c0093f3c832d6775/src/pages/home/report/ReportActionItemMessageEdit.tsx#L293-L297
And confirmed that this will run when scrolled all the way to the bottom, and when edited a message to a new message.
By removing the boundaries when that runs, and always running that, it will ensure the messages are always visible. In both that use case, and this use case.



### What alternative solutions did you explore? (Optional)#
- Focus the composer and show keyboard after edit on IOS as well.
- Or specific logic to call  reportScrollManager.scrollToIndex(index, false); when deleting the message in the edit flow

**Comment by HarshMohanSason** [comment] 2024-02-06 22:41
Did you try using the scrollToEnd() method provided by the ScrollView component?

**Comment by jeremy-croff** [comment] 2024-02-06 23:16
> Did you try using the scrollToEnd() method provided by the ScrollView component? That should solve this case if all you need to do is to just scroll at the bottom each time a message edit was successful.

You don't want want to scroll down if you are editing something in history.

**Comment by HarshMohanSason** [comment] 2024-02-07 01:10
> > Did you try using the scrollToEnd() method provided by the ScrollView component? That should solve this case if all you need to do is to just scroll at the bottom each time a message edit was successful.
> 
> You don't want want to scroll down if you are editing something in history.
I meant call the function after the delete is completed by setting a flag to know if it has been finished or not. 

The solutions you have provided where "Or specific logic to call reportScrollManager.scrollToIndex(index, false); when deleting the message in the edit flow". You can try using a trigger function which is called whenever the keyboard is opened so it saves that position. Then you can have something like

```
const getSavedScrollPosition = () => {
    return savedScrollPosition;
  };
  
  and then use this savedScrollPosition in your logic
  
   if (index === 0) { 
     const keyboardDidHideListener = Keyboard.addListener('keyboardDidHide', () => { 
         const scrollPos = getSavedScrollPosition() 
         //use this to scroll. 
         keyboardDidHideListener.remove(); 
     }); 
  
```

**Comment by jeremy-croff** [comment] 2024-02-07 02:57
> > > Did you try using the scrollToEnd() method provided by the ScrollView component? That should solve this case if all you need to do is to just scroll at the bottom each time a message edit was successful.
> > 
> > 
> > You don't want want to scroll down if you are editing something in history.
> 
> I meant call the function after the delete is completed by setting a flag to know if it has been finished or not.
> 
> The solutions you have provided where "Or specific logic to call reportScrollManager.scrollToIndex(index, false); when deleting the message in the edit flow". You can try using a trigger function which is called whenever the keyboard is opened so it saves that position. Then you can have something like
> 
> ```
> const getSavedScrollPosition = () => {
>     return savedScrollPosition;
>   };
>   
>   //and then use this savedScrollPosition in your logic
>   
>    if (index === 0) { 
>      const keyboardDidHideListener = Keyboard.addListener('keyboardDidHide', () => { 
>          const scrollPos = getSavedScrollPosition();
>          //use this to scroll. 
>          keyboardDidHideListener.remove(); 
>      }); 
>   
> ```

I'm trying to understand, but the root cause of the current IOS bug is that the existing scroll is not working because keyboardDidHide actually never occurs. Since the composer doesn't get refocused. That's why I proposed to either call a scroll to current position after delete, or focus on the composer.

**Comment by stephanieelliott** [comment] 2024-02-08 21:30
Hey @allroundexperts would you mind weighing in on the proposals here?

**Comment by NikkiWines** [comment] 2024-02-10 03:37
Yep, agreed - let's go with consistency 👍

**Comment by jeremy-croff** [comment] 2024-02-10 04:29
> ReportActionItemMessageEdit.tsx

Could you help confirm if we want the composer to also auto focus on open of the report? This is common logic at the moment, shared with the edit flow. Other devices are auto focusing but the consideration with IOS is that it will open the keyboard.

I think it makes sense - because otherwise you could go from a state of not having composer focused, to deleting an comment in edit and then focusing the composer. If we enforced consistency, we would auto focus the composer on report load, and maintain it after actions like delete.

This is actually not new logic, but just letting the existing logic run as is and removing the exclusion for touch devices not to focus.

I think originally IOS was changed to not autofocus because it seemed jarring to have the keyboard.

**Comment by jeremy-croff** [comment] 2024-02-10 22:52
While developing I identified a one liner that addressed this issue:

updating ```export default setShouldShowComposeInputKeyboardAwareBuilder('keyboardWillHide'); ```
to ```export default setShouldShowComposeInputKeyboardAwareBuilder('keyboardDidHide');```

Will fix this issue as it removes the keyboard at the right time so the scroll doesnt get pushed back.

**Comment by jeremy-croff** [comment] 2024-02-13 04:14
@allroundexperts I'm looking for approval on the information above. I have a draft PR open and can finalize the checklist if this looks good.

**Comment by jeremy-croff** [comment] 2024-02-14 01:12
@allroundexperts bumping this.

**Comment by allroundexperts** [comment] 2024-02-14 07:42
That's fine @jeremy-croff. Please open the PR so I can test it.

**Comment by jeremy-croff** [comment] 2024-02-14 13:13
> That's fine @jeremy-croff. Please open the PR so I can test it.

I have opened the draft for review so you can test it.
I will be in office, but at the end of my day in approx 12 hrs I can go through the checklist thoroughly and test.

**Comment by jeremy-croff** [comment] 2024-02-15 14:28
Expecting to continue work on this in 12 hours

**Comment by jeremy-croff** [comment] 2024-02-16 02:08
Ready for review!

**Comment by stephanieelliott** [comment] 2024-02-19 23:28
Hey @allroundexperts looks like this is waiting on your review!

**Comment by stephanieelliott** [comment] 2024-02-27 02:46
PR was deployed to staging

**Comment by stephanieelliott** [comment] 2024-03-05 01:19
This was deployed to prod on 2/28, seems the automation didn't work so am updating manually

**Comment by stephanieelliott** [comment] 2024-03-06 23:57
Summarizing payment on this issue: 

 - Contributor: @jeremy-croff $500 PAID via Upwork 
 - Contributor+: @allroundexperts $500 Please request via ND 
 
 Upwork job is here: [https://www.upwork.com/jobs/~1737876297360310272"](https://www.upwork.com/jobs/~01a3b81b8f8d63b5f3)

**Closed by stephanieelliott** 2024-03-06 23:57 UTC
Labels: Reviewing, External, Weekly, Bug

**Comment by JmillsExpensify** [comment] 2024-03-12 02:47
$500 approved for @allroundexperts based on summary.
