### ISSUE TITLE
[$500]  Profile settings - Zipcode is not auto-fill in personal details

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#30470] opened 2023-10-26 22:56 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.3.91-6
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** Applause - Internal Team
**Slack conversation:**

## Action Performed:
1. Navigate to Staging.new.expensify.com
2. Go to settings > Profile
3. Click Personal details
4. Click Address
5. Start typing in the street field: Briar Forest Drive

## Expected Result:
Поля формы заполняются автоматически

## Actual Result:
Поле почтового индекса не заполняется автоматически для всех адресов

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] Windows: Chrome 
- [ ] MacOS: Desktop

## Screenshots/Videos
<details>
<summary>Android: Native</summary>

</details>

<details>
<summary>Android: mWeb Chrome</summary>

</details>

<details>
<summary>iOS: Native</summary>

</details>

<details>
<summary>iOS: mWeb Safari</summary>

</details>

<details>
<summary>Windows: Chrome </summary>

  
![Bug6251976_1698333919666!zip_code](https://github.com/Expensify/App/assets/78819774/4e41117f-3e2f-4873-889d-7d9449097ddc)

</details>

<details>
<summary>MacOS: Desktop</summary>

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01470ad9066a9db994</li>
        <li>Upwork Job ID: 1717676496205910016</li>
        <li>Last Price Increase: 2023-10-26</li>
    </ul>
</details>

**Comment by yakupafsin** [comment] 2023-10-27 00:15
## Proposal


### Please re-state the problem that we are trying to solve in this issue.

On the address entry page, when users search for 'Briar Forest Drive,' the Zip/Postcode field doesn't automatically populate.

### What is the root cause of that problem?

This issue arises because we rely on the Google Places API to retrieve address information. Google Maps may not consistently provide postcodes for certain street addresses due to the complexity of long streets where different sides have different postcodes.

### What changes do you think we should make in order to solve the problem?

To address this problem, we can improve the user experience by doing the following:

- Check the data received from the Google API and identify cases where a street lacks a postcode.
- When a postcode is unavailable, present the street with a list of nearby building numbers to users.
- Users can then select the closest building number to their desired location, and the Google API will provide the postcode associated with that building.
- This way, users can still obtain postcode information even if it's not directly linked to the street itself.

### What alternative solutions did you explore? (Optional)

We considered randomly selecting a building number from the user's chosen address and retrieving the postcode associated with that building. However, this solution might not be transparent to the user and could lead to confusion, so it's not recommended.

<details open>
<summary>MacOs: Chrome</summary>
<br>

![Screenshot 2023-10-27 at 01 05 34](https://github.com/Expensify/App/assets/66640310/fcc6967a-a53a-4f29-bd5c-ca65720c5561)
![Screenshot 2023-10-27 at 01 03 41](https://github.com/Expensify/App/assets/66640310/376b9517-f3bc-4f4c-a2a3-be291876c128)
![Screenshot 2023-10-27 at 01 07 05](https://github.com/Expensify/App/assets/66640310/fb295375-6939-4123-839b-ac6f25d98318)
![Screenshot 2023-10-27 at 01 07 19](https://github.com/Expensify/App/assets/66640310/b7fe6294-1834-4080-b58f-31b4f0f0bacb)


</details>

**Comment by chahedmoetaz** [comment] 2023-10-27 01:34
I'm happy to help you write code to fix the Zipcode auto-fill issue in the Expensify application, I can provide you with a generic example of what the fix might look like in a JavaScript context.

 Here's a simplified example of how you might address the issue:

```javascript
// Sample JavaScript code to fix Zipcode auto-fill issue

// 1. Identify the Zipcode field element by its ID or other selector.
const zipcodeField = document.getElementById('zipcode');

// 2. Define a function to retrieve the user's Zipcode from a data source.
function getZipcodeFromDataSource(userId) {
    // Replace this with your actual code to fetch Zipcode data.
    // You may need to make an API request to a server to retrieve the Zipcode.
    // Example:
    // const response = await fetch(`/api/getZipcode?userId=${userId}`);
    // const data = await response.json();
    // return data.zipcode;
}

// 3. Add an event listener to trigger the auto-fill when the user's details are entered.
document.getElementById('personalDetailsForm').addEventListener('submit', async (event) => {
    event.preventDefault();

    // 4. Retrieve the user's ID or other identifier (e.g., email or username).
    const userId = getUserID(); // Implement this function as per your user authentication logic.

    if (userId) {
        // 5. Fetch the Zipcode data from the data source.
        const zipcode = await getZipcodeFromDataSource(userId);

        // 6. Auto-fill the Zipcode field with the retrieved data.
        zipcodeField.value = zipcode;
    }
});
```

In this simplified example:

1. We select the Zipcode field element.
2. We define a function (`getZipcodeFromDataSource`) to fetch the Zipcode from a data source.
3. We add an event listener to the user's details form submission.
4. We retrieve the user's identifier (e.g., user ID).
5. We fetch the Zipcode data based on the user's identifier.
6. We auto-fill the Zipcode field with the retrieved data.

The key is to ensure that you can fetch the Zipcode data reliably from the data source and populate it in the correct field within the Expensify application.

**Comment by puneetlath** [comment] 2023-10-27 13:17
I think we should close this. If the issue is that Google Maps API isn't returning a postcode for these addresses, then I think it's fine to just have the user enter it.

**Closed by puneetlath** 2023-10-27 13:17 UTC
Labels: External, Daily, Help Wanted, Bug

**Comment by yakupafsin** [comment] 2023-10-27 13:19
@puneetlath I would do the same thing if I were facing the same problem in my app :) . I shared my proposal just to provide an option.

**Comment by puneetlath** [comment] 2023-10-27 13:55
Appreciate that @yakupafsin!
