### ISSUE TITLE
[$250] Android - Taxes - Cursor is placed before the value when reopening saved value

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#39081] opened 2024-03-27 16:47 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.57-2
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**If this was caught during regression testing, add the test name, ID and link from TestRail:** N/A
**Issue reported by:** Applause - Internal Team

**Issue found when executing PR** https://github.com/Expensify/App/pull/38733
## Action Performed:
Precondition:
- User is admin of Collect workspace
1. Go to staging.new.expensify.com
2. Go to Profile > Workspaces > Collect workspace
3. Go to Taxes > Add rate > Value
4. Enter any value and save it
6. Tap Value again

## Expected Result:
Cursor is placed behind the value

## Actual Result:
Cursor is placed in front of the value. Sometimes it appears behind the value

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [ ] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details> 

https://github.com/Expensify/App/assets/78819774/92f43526-549a-43cf-8d7b-de7644b2ab7f

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01515a93e0ea4bae26</li>
        <li>Upwork Job ID: 1774175994999578624</li>
        <li>Last Price Increase: 2024-05-07</li>
    </ul>
</details>

**Comment by lanitochka17** [comment] 2024-03-27 16:47
@MitchExpensify  FYI I haven't added the External label as I wasn't 100% sure about this issue. Please take a look and add the label if you agree it's a bug and can be handled by external contributors

**Comment by abzokhattab** [comment] 2024-03-30 23:12
Not reproducible on main in my case:


https://github.com/Expensify/App/assets/59809993/d3da0e06-f5a5-4a53-9311-712ca89c26aa

**Comment by MitchExpensify** [comment] 2024-04-01 18:03
Proposals ready for you @cubuspl42

**Comment by kmbcook** [comment] 2024-04-02 20:13
@cubuspl42 below Profile and Members you should also see Categories, Tags, and More Features. Taxes are under More Features. My collect workspace was created on old dot. I don't know if that makes a difference.

**Comment by cubuspl42** [comment] 2024-04-03 11:26
I thought "owner" and "admin" are the same. You can see that I'm the owner on the screenshots.

**Comment by cubuspl42** [comment] 2024-04-03 15:48
I found a solution; see [this Slack message](https://expensify.slack.com/archives/C01GTK53T8Q/p1712145016871939?thread_ts=1712143766.644779&cid=C01GTK53T8Q). I'll see if I can reproduce this issue now.

**Comment by cubuspl42** [comment] 2024-04-08 09:33
@lanitochka17 @MitchExpensify I can't reproduce, [same as in this comment.](https://github.com/Expensify/App/issues/39081#issuecomment-2028491692). I tested on latest `main`.

**Comment by cubuspl42** [comment] 2024-04-08 12:55
@Krishna2323 Actually, before we resume discussing your proposal, could you stick to the proposal template and fix the markdown of your proposal? Currently, I can see something like this:

![image](https://github.com/Expensify/App/assets/2590174/f8a9c09b-7bdc-4d33-8896-f9e9b5a4b6f8)

First, "Result" and "Optional" aren't valid H3 headers from the proposal template, second, "Result" doesn't seem to render. Possibly, the same information could be provided in a H4 header, or in a separate GH comment.

**Comment by lanitochka17** [comment] 2024-04-09 16:53
@cubuspl42 More difficult to reproduce it now, but it exists. Need to go to the page many times now.


https://github.com/Expensify/App/assets/78819774/1ac0914e-469e-4acc-addd-88431d5ded3f

**Comment by MitchExpensify** [comment] 2024-04-09 21:41
Waiting on @cubuspl42 to check out the latest updated proposal

**Comment by cubuspl42** [comment] 2024-04-10 09:54
I'll run the app on my old physical Galaxy S8 to see if I can reproduce. It will help during testing, but as a plan B we could go forward without me reproducing, as we have double confirmation that the bug still occurs.

**Comment by cubuspl42** [comment] 2024-04-11 07:06
[There are some building issues](https://expensify.slack.com/archives/C01GTK53T8Q/p1712746783190519) on Android, but I'll try working it around.

**Comment by cubuspl42** [comment] 2024-04-12 08:09
[This fix](https://github.com/Expensify/App/pull/40102) for Android is now merged, I'm now building the app again

**Comment by cubuspl42** [comment] 2024-04-12 10:27
I built and launched the app on my Galaxy S8, but I couldn't reproduce even after trying many times.

@Krishna2323 What's the motivation for these updates? What are the pros and cons of your multiple solutions?

**Comment by cubuspl42** [comment] 2024-04-17 10:51
Okey, focusing on the solution details itself: it doesn't make me excited. It feels hackish, as we're working around a bug very deep in the React Native core in the amount picker component.

Could we, maybe, handle it in our in-house `TextInput` component? If we have to work a bug around, I'd like to do that:
- In the right place, as low-level as possible
- Only on the platforms that require it
- With a comment explaining what we're doing and why, perfectly with a link to an upstream issue

**Comment by cubuspl42** [comment] 2024-04-22 08:43
@Krishna2323 Do you think you could sketch an updated solution based on this feedback? Alternatively, you could challenge some of my points.

**Comment by mallenexpensify** [comment] 2024-04-23 23:51
@hoangzinh reassigning, please take over as C+. If you don't have bandwidth, unassign yourself. Thanks

**Comment by MitchExpensify** [comment] 2024-04-29 21:08
Not overdue, actively being worked on and the ball is in @hoangzinh 's court to consider @Krishna2323 's response above

**Comment by MitchExpensify** [comment] 2024-05-01 13:59
Friendly bump @hoangzinh

**Comment by mvtglobally** [comment] 2024-05-01 14:01
Issue not reproducible during KI retests. (First week)

**Comment by MitchExpensify** [comment] 2024-05-05 10:59
Friendly bump @Krishna2323

**Comment by lanitochka17** [comment] 2024-05-09 12:42
Issue is still reproducible 


https://github.com/Expensify/App/assets/78819774/6437d8ca-c156-46da-93ab-7baa1487fa34

**Comment by MitchExpensify** [comment] 2024-05-12 16:56
Good idea @hoangzinh , shared here https://expensify.slack.com/archives/C02NK2DQWUX/p1715532975658179

**Comment by mananjadhav** [comment] 2024-05-12 18:11
I couldn't reproduce it at my end on physical Android device, prod 1.4.71-6. @lanitochka17 Could you share some details on your device and the app version?

**Comment by mananjadhav** [comment] 2024-05-13 04:23
Was able to reproduce this on my Android emulator. @MitchExpensify Can you add the `Help Wanted` label.

**Comment by mvtglobally** [comment] 2024-05-13 14:04
Issue not reproducible during KI retests. (Second week)

**Comment by mananjadhav** [comment] 2024-05-13 19:38
@mvtglobally I am able to reproduce it on my emulator.


https://github.com/Expensify/App/assets/3069065/1c42d183-d9d0-406c-8258-6cda42c7d0fb

**Comment by MitchExpensify** [comment] 2024-05-15 03:48
Given this is such minor issue, isolated to Android, and we're having trouble replicating it I don't think this is worth our time

**Closed by MitchExpensify** 2024-05-15 03:48 UTC
Labels: External, Daily, Bug
