### ISSUE TITLE
QR share profile picture and display name disappears after changing default contact method

### ISSUE THREAD

**Issue by kavimuru** [Expensify/App#19308] opened 2023-05-19 19:31 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:

1. Log in to account A on desktop and go to share code page
2. Log in to account A on another device (mobile) and change the display name
3. Notice the display name on the QR page also updates
4. Add a secondary contact method on the other device (mobile) and verify it
5. Set the secondary contact method as default contact method
6. Notice the change on desktop on the QR share page

## Expected Result:
The profile picture in the middle of the QR should not disappear and the display name should not disappear
## Actual Result:
The display name and the profile picture in the middle of the QR code both disappear.

## Workaround:
Can the user still use Expensify without this being fixed? Have you informed them of the workaround?

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [x] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 1.3.16-5
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/43996225/dcbcdc4a-c534-400e-b56f-2af5ded8833b

https://github.com/Expensify/App/assets/43996225/51cd3c1a-b485-45e3-a054-5b736dae8505

https://github.com/Expensify/App/assets/43996225/4b486892-3949-4242-b016-ab4e38f229b4

**Expensify/Expensify Issue URL:**
**Issue reported by:** @nathan-mulugeta
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1684313125238249

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~018c1f82fae3362a2b</li>
        <li>Upwork Job ID: 1663037136036069376</li>
        <li>Last Price Increase: 2023-05-29</li>
    </ul>
</details>

**Comment by johncschuster** [comment] 2023-05-20 08:41
Reassigning while I'm at EC3 so this can be actioned with urgency

**Comment by kevinksullivan** [comment] 2023-05-23 20:37
Hm, was OOO so I'm not certain why I was assigned here. Looking into it.

**Comment by kevinksullivan** [comment] 2023-05-23 20:41
> This "bug" occurs on a supported platform (ensure Platforms in OP are ✅)

Asking about this in the slack thread but otherwise looks like a legitimate bug.

**Comment by kevinksullivan** [comment] 2023-05-25 00:27
Alright, getting an engineering take here since I didn't get comments in slack on whether or not this is a backend change.

**Comment by kevinksullivan** [comment] 2023-05-25 00:27
@techievivek curious for your take on @huzaifa-99 's comment

https://github.com/Expensify/App/issues/19308#issuecomment-1559921750

**Comment by techievivek** [comment] 2023-05-29 04:18
Yes, I just reproduced this locally, and this definitely is a backend issue, as we don't seem to send the required data whenever `SetContactMethodAsDefault` gets used to update the default login.

**Comment by techievivek** [comment] 2023-05-29 05:22
Removing @0xmiroslav as this requires access to backend code.

**Comment by techievivek** [comment] 2023-06-06 07:11
PR is in review. I am going to test this some more and bump Alex B for another round of review.

**Comment by kevinksullivan** [comment] 2023-06-14 15:58
@techievivek what's the latest?

**Comment by techievivek** [comment] 2023-06-15 06:36
@kevinksullivan This is deployed to PROD, do we need to pay the reporting bonus here?

**Comment by kevinksullivan** [comment] 2023-06-16 14:40
ah yes, good call. @Nathan-Mulugeta sent an offer for reporting. Let me know when you accept and I can pay it out. 

https://www.upwork.com/jobs/~01d19402554a9f935a

**Comment by kevinksullivan** [comment] 2023-06-16 14:53
Payment sent, all set here.

**Closed by kevinksullivan** 2023-06-16 14:53 UTC
Labels: Reviewing, Engineering, Daily, Internal, Bug
