### ISSUE TITLE
[HOLD for payment 2024-10-29][$125] [Search v1.2] - Admin can delete employee's expenses in Search page

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#46762] opened 2024-08-03 14:34 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 9.0.16-0
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**If this was caught during regression testing, add the test name, ID and link from TestRail:** N/A
**Issue reported by:** Applause - Internal Team

## Action Performed:
Precondition:
- Admin and employee are in the same workspace
1. Go to staging.new.expensify.com
2. [Employee] Submit an expense in the workspace chat
3. [Admin] Go to Search
4. [Admin] Select the expense submitted by employee via checkbox
5. [Admin] Click on the dropdown

## Expected Result:
Delete option should not be available for admin in Search because Delete option is not present for admin in the transaction thread

## Actual Result:
Delete option is available for admin in Search when Delete option is not present for admin in the transaction thread

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [x] Android: mWeb Chrome
- [x] iOS: Native
- [x] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence
 
 
https://github.com/user-attachments/assets/291cb75b-d6c5-4712-aee4-200d9f0800a4

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~018f10851e4c993906</li>
        <li>Upwork Job ID: 1821118379211606096</li>
        <li>Last Price Increase: 2024-10-29</li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @Pujan92</details>

**Comment by lanitochka17** [comment] 2024-08-03 14:35
We think that this bug might be related to #wave-control

**Comment by lanitochka17** [comment] 2024-08-03 14:36
@dylanexpensify  FYI I haven't added the External label as I wasn't 100% sure about this issue. Please take a look and add the label if you agree it's a bug and can be handled by external contributors

**Comment by MuaazArshad** [comment] 2024-08-03 17:06
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
Admin can delete employee's expenses in Search page
### What is the root cause of that problem?
We are not adding the check `isActionCreator` here
https://github.com/Expensify/App/blob/459759d55963091c708d7271c29e0f95f3add658/src/components/Search/SearchPageHeader.tsx#L211
### What changes do you think we should make in order to solve the problem?

We should check if the current user is action creator we can do something like this
```
        const shouldShowDeleteOption = !isOffline && selectedTransactionsKeys.every((id) => selectedTransactions[id].canDelete) && isActionCreator(selectedTransactions);
```
### What alternative solutions did you explore? (Optional)

**Comment by MuaazArshad** [comment] 2024-08-03 18:07
Contributor details
Your Expensify account email: mooeez.arshad@gmail.com
Upwork Profile Link: https://www.upwork.com/freelancers/~017994bec44c81b9d0

**Comment by dylanexpensify** [comment] 2024-08-05 09:38
reviewing today!

**Comment by dylanexpensify** [comment] 2024-08-07 09:37
Made external

**Comment by Pujan92** [comment] 2024-08-13 18:10
@dylanexpensify Can you plz help to decide the expected behavior?

Are expenses can be deleted by admin from both places?

**Comment by MuaazArshad** [comment] 2024-08-16 16:35
@Pujan92 @dylanexpensify bump!

**Comment by Pujan92** [comment] 2024-08-21 20:11
Bump @dylanexpensify for https://github.com/Expensify/App/issues/46762#issuecomment-2286836845 :)

**Comment by MuaazArshad** [comment] 2024-09-05 16:17
@Pujan92 @dylanexpensify bump!

**Comment by dylanexpensify** [comment] 2024-09-06 18:36
My apologies team! Confirming behavior now!

**Comment by dylanexpensify** [comment] 2024-09-09 20:36
Confirmed, expenses can be deleted in both locations

**Comment by Pujan92** [comment] 2024-09-10 11:40
Based on the desired behavior of allowing deleting an expense from both the places for admin, we can proceed with @daledah's [proposal](https://github.com/Expensify/App/issues/46762#issuecomment-2268152523) which matches with the required changes.

🎀👀🎀 C+ reviewed

**Comment by luacmartins** [comment] 2024-09-13 15:06
FYI we reverted the [PR](https://github.com/Expensify/App/pull/48998) linked to this issue since that was not the expected behavior. I'm keeping this issue open since we need to instead remove the `Delete` option from the Search page. That is a backend issue though.

**Comment by luacmartins** [comment] 2024-09-13 15:20
@stitesExpensify if you're looking into this, this is the function that'd need to be udpdated - https://github.com/Expensify/Auth/blob/d32ccbadf39bccec15bbdb426649015a2a4cc845/auth/lib/Transaction.cpp#L3142-L3167

**Comment by luacmartins** [comment] 2024-09-17 22:29
@stitesExpensify that's not the expected behavior. See this convo - https://expensify.slack.com/archives/C06ML6X0W9L/p1726235265572009

**Comment by stitesExpensify** [comment] 2024-09-24 22:40
No update, i have been focused on travel

**Comment by stitesExpensify** [comment] 2024-09-27 22:18
@luacmartins do you have any bandwidth to pick this up since you know what needs to be done? I am not going to be able to prioritize this any time soon

**Comment by luacmartins** [comment] 2024-09-30 13:26
Sure, I can take this

**Comment by dylanexpensify** [comment] 2024-10-03 11:35
TY @luacmartins!

**Comment by dylanexpensify** [comment] 2024-10-07 12:14
On @luacmartins's radar

**Comment by luacmartins** [comment] 2024-10-09 17:48
No updates yet, gonna try to work on it this week.

**Comment by luacmartins** [comment] 2024-10-15 23:42
No updates yet, gonna try to work on it this week.

**Comment by luacmartins** [comment] 2024-10-16 23:08
PR in review

**Comment by dylanexpensify** [comment] 2024-10-17 20:36
Hey @sonialiap! I'm heading out on parental leave so reassigning this! TY! 🙇‍♂️

**Comment by Pujan92** [comment] 2024-10-29 05:38
@luacmartins @stitesExpensify I would like to just confirm whether we are eligible for any compensation here because based on the initial confirmation of requirements we proceeded and merged the PR.

**Comment by luacmartins** [comment] 2024-10-29 16:14
Sure, but I think it'd be 50% of the amount since it technically caused a regression.

**Comment by Pujan92** [comment] 2024-10-29 17:26
Agree @luacmartins, Thanks!

@sonialiap can you plz post payment summary

**Comment by sonialiap** [comment] 2024-10-30 11:00
Payment summary:
- @Pujan92 $125 via NewDot
- @daledah $125 offer sent in [upwork](https://www.upwork.com/ab/applicants/1851579672302776703/offers)

**Comment by sonialiap** [comment] 2024-11-04 10:19
BugZero Checklist: The PR fixing this issue has been merged! The following checklist ([instructions](https://stackoverflow.com/c/expensify/questions/14574)) will need to be completed before the issue can be closed:
-  [@Pujan92] The PR that introduced the bug has been identified. Link to the PR:
-  [@Pujan92] The offending PR has been commented on, pointing out the bug it caused and why, so the author and reviewers can learn from the mistake. Link to comment:
-  [@Pujan92] A discussion in #expensify-bugs has been started about whether any other steps should be taken (e.g. updating the PR review checklist) in order to catch this type of bug sooner. Link to discussion:
-  [@Pujan92] Determine if we should create a regression test for this bug.
-  [@Pujan92] If we decide to create a regression test for the bug, please propose the [regression test](https://github.com/Expensify/App/blob/main/contributingGuides/REGRESSION_TEST_BEST_PRACTICES.md) steps to ensure the same bug will not reach production again.
-  [[@sonialiap](https://github.com/sonialiap)] Link the GH issue for creating/updating the regression test once above steps have been agreed upon:

**Comment by garrettmknight** [comment] 2024-11-06 12:01
@Pujan92 can you complete the checklist?

**Comment by Pujan92** [comment] 2024-11-06 13:35
@garrettmknight We don't need a checklist here as the expected behavior has been changed and PR for this is reverted, BE fix only required.

**Comment by garrettmknight** [comment] 2024-11-06 13:45
$125 approved for @Pujan92

**Closed** 2024-11-07 09:04 UTC
Labels: Daily, Internal, Awaiting Payment, Bug
