### ISSUE TITLE
[$500] Bank- In offline, after tapping start over, options are greyed out and no page is opened

### ISSUE THREAD

**Issue by izarutskaya** [Expensify/App#29171] opened 2023-10-10 11:47 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.3.80-0

**Reproducible in staging?:** Y

**Reproducible in production?:** Y

**If this was caught during regression testing, add the test name, ID and link from TestRail:**

**Email or phone of affected tester (no customers):**

**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Expensify/Expensify Issue URL:**

**Issue reported by:** Applause-Internal Team

**Slack conversation:** @

## Action Performed:
1. Launch app
2. Tap profile
3. Tap Workspaces
4. Tap any Workspace
5. Tao bank account
6. Tap Connect manually
7. Complete the flow step 1-connect bank account, step 2-company information and tap save &continue
8. From profile information page, tap app back button and navigate to settings page
9. Tap preferences
10. Toggle on forced offline
11. Tap back button
12. Tap Workspaces--Workspace--bank account
13. Tap Start over
14. Tap Yes, start over

## Expected Result:
The starting "connect bank account" page must be shown.

## Actual Result:
In offline, after tapping start over, both options
"Continue with set up" and "start over" are greyed out and no page is opened to start over and connect bank account.
On Web, tapping on " yes, start over" button does not trigger any action.

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [x] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos
<details>
<summary>Android: Native</summary>

https://github.com/Expensify/App/assets/115492554/6d1d90d8-095b-4f78-af06-c7837f3b6964

</details>

<details>
<summary>Android: mWeb Chrome</summary>

</details>

<details>
<summary>iOS: Native</summary>

</details>

<details>
<summary>iOS: mWeb Safari</summary>

</details>

<details>
<summary>MacOS: Chrome / Safari</summary>

https://github.com/Expensify/App/assets/115492554/3bc25fb6-ade8-4acf-8918-bf47b704f7a8

</details>

<details>
<summary>MacOS: Desktop</summary>

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01b0871c84faa3211c</li>
        <li>Upwork Job ID: 1711710099550969856</li>
        <li>Last Price Increase: 2023-10-17</li>
    </ul>
</details>

**Comment by lanitochka17** [comment] 2023-10-14 15:30
Hello Does this also apply to the login page? Or is this a separate problem?
![Screenshot_20231014-185150_New Expensify](https://github.com/Expensify/App/assets/78819774/b5ae073e-4ed8-4bd2-b3b9-4f55491c0d19)

**Comment by strepanier03** [comment] 2023-10-16 21:19
@lanitochka17 - I'm unsure, you might want to post in Slack.

**Comment by strepanier03** [comment] 2023-10-16 21:23
Running through these reproduction steps I do not have the Start Over option unless I toggle off Force Online. With Force Online toggled on, I see:

<img width="1440" alt="image" src="https://github.com/Expensify/App/assets/10925636/392b1705-bd03-4908-90fb-9939ba901d25">

With it toggled off I see:
<img width="1440" alt="image" src="https://github.com/Expensify/App/assets/10925636/e5528dd1-a79a-42f2-b198-f0698d46a92e">

----

@izarutskaya - If you run through the steps again, are you seeing what I'm seeing or still the option to start over while forced offline?

**Comment by izarutskaya** [comment] 2023-10-18 09:33
Hi @strepanier03, I don't see option `start over` too on Android and Web.

https://github.com/Expensify/App/assets/115492554/df4d11b3-3a0a-4db6-8608-8ac36a6499e1

https://github.com/Expensify/App/assets/115492554/9f294d4a-50e4-448b-bd60-1662347981cc

**Comment by strepanier03** [comment] 2023-10-19 23:08
Thanks @izarutskaya. I think I'm going to close this because you need to be online to start over and when online it's working as expected for me. 

Do you disagree? If there is a different problem here that's fine, we can update the OP comment.

**Comment by strepanier03** [comment] 2023-10-24 14:47
I'm going to close this GH for now. We can always reopen and update the OP comment/title if we need to.

**Closed by strepanier03** 2023-10-24 14:47 UTC
Labels: External, Daily, Needs Reproduction, Help Wanted, Overdue, Bug
