### ISSUE TITLE
Settings - Share code - Share button is non functional

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#19041] opened 2023-05-16 17:00 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Issue found when executing PR** https://github.com/Expensify/App/pull/18636 

## Action Performed:
1. Launch the app and login,
2. Go to  Personal Profile Settings menu
3. Tap the "Show QR Code" button under your profile name and picture
4. Verify that you see two menu items: Share and Download
5. Tap on Share button

## Expected Result:
Share button is functional

## Actual Result:
Share button is non functional

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [x] MacOS / Chrome / Safari
- [x] MacOS / Desktop

**Version Number:** 1.3.14.4

**Reproducible in staging?:** Yes

**Reproducible in production?:** New feature

**If this was caught during regression testing, add the test name, ID and link from TestRail:**

**Email or phone of affected tester (no customers):**

**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Notes/Photos/Videos:** Any additional supporting documentation

![18636 Desktop (2)](https://github.com/Expensify/App/assets/93399543/e8699cb7-dc44-4cba-a5e3-cad6bf95d88a)

**Expensify/Expensify Issue URL:**

**Issue reported by:** Applause - Internal Team and @natnael-guchima

**Slack conversation:**

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~0154212e434bfba80a</li>
        <li>Upwork Job ID: 1660439185885417472</li>
        <li>Last Price Increase: 2023-05-22</li>
    </ul>
</details>

**Comment by therealsujitk** [comment] 2023-05-16 17:20
This is not a bug, It actually copies the link to clipboard, perhaps it shouldn't be called **Share** or, maybe a feedback message saying the link has been copied to clipboard?

**Comment by Natnael-Guchima** [comment] 2023-05-16 17:52
> This is not a bug, It actually copies the link to clipboard, perhaps it shouldn't be called **Share** or, maybe a feedback message saying the link has been copied to clipboard? or maybe it's called **Share** because the authors are planning to change the functionality in future.

According to the slack discussion [here](https://expensify.slack.com/archives/C049HHMV9SM/p1684154588458859?thread_ts=1684154588.458859&cid=C049HHMV9SM), I think the plan is to go with changing the arrow icon with copy to clipboard icon.

**Comment by Natnael-Guchima** [comment] 2023-05-17 08:15
This [PR](https://github.com/Expensify/App/pull/18946) seems to fix this issue. But this issue is not appropriately linked to the fixing PR

**Comment by kadiealexander** [comment] 2023-05-19 01:13
Thanks for flagging that PR @Natnael-Guchima, this behaviour is now fixed:

https://github.com/Expensify/App/assets/59587260/f5c978c8-c468-41b0-981d-6a0fae0051ee

Closing this issue!

**Comment by Natnael-Guchima** [comment] 2023-05-19 03:27
You are welcome @kadiealexander. I am not paid for the original reporting though 😕. I think the discussion to change the icon from an arrow icon to copy clipboard was first triggered by my report here https://expensify.slack.com/archives/C049HHMV9SM/p1684154588458859?thread_ts=1684154588.458859&cid=C049HHMV9SM. 

Thanks.

**Comment by mountiny** [comment] 2023-05-19 09:55
@kadiealexander yep I think @Natnael-Guchima was first to note this bug so we should pay them for reporting it. Reopening to handle the payment. thank you!

**Comment by kadiealexander** [comment] 2023-05-22 00:15
Added the internal label to spin up an Upwork job.

**Comment by kadiealexander** [comment] 2023-05-22 01:15
@Natnael-Guchima sent you an offer, please let me know when you accept.

**Comment by Natnael-Guchima** [comment] 2023-05-22 03:27
I have accepted the offer, @kadiealexander. Thanks.

**Comment by kadiealexander** [comment] 2023-05-22 03:36
Paid! Thanks @Natnael-Guchima

**Closed by kadiealexander** 2023-05-22 03:36 UTC
Labels: Daily, Awaiting Payment, Bug
