### ISSUE TITLE
[HOLD for payment 2024-11-20] [$250] Expense-Expense preview is hidden briefly when returning to expense report via header subtitle

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#49741] opened 2024-09-25 20:00 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 9.0.40-0
**Reproducible in staging?:** Y
**Reproducible in production?:** N
**If this was caught during regression testing, add the test name, ID and link from TestRail:** N/A
**Email or phone of affected tester (no customers):** applausetester+kh230901@applause.expensifail.com
**Issue reported by:** Applause - Internal Team

## Action Performed:
1. Go to staging.new.expensify.com
2. Go to DM
3. Submit at least two expenses to the user
4. Go to transaction thread of the first expense
5. Click on the header subtitle link to go back to expense report

## Expected Result:
The second expense preview will show instantly after returning to expense report via header subtitle (production behavior)

## Actual Result:
The second expense preview is hidden briefly after returning to expense report via header subtitle

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [x] Android: mWeb Chrome
- [x] iOS: Native
- [x] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details> 

https://github.com/user-attachments/assets/e1087dab-4a1b-4535-817f-34e0dff15c91

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~021839062492993280361</li>
        <li>Upwork Job ID: 1839062492993280361</li>
        <li>Last Price Increase: 2024-10-30</li>
<li>Automatic offers: </li>
<ul>
<li>huult | Contributor | 104757569</li>
</ul></li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @RachCHopkins</details>

**Comment by lanitochka17** [comment] 2024-09-25 20:00
We think that this bug might be related to #wave-collect - Release 1

**Comment by francoisl** [comment] 2024-09-25 21:59
I also notice a short delay on production, albeit shorter than on staging. Roughly like 50ms on production, and 200ms on staging. 
It doesn't look like there's any API call happening when returning to the parent report, so it's probably not due to anything changing in Onyx.

There's nothing that stands out in the checklist so I'm going to open this up for proposals. Doesn't seem worthy of blocking though.

**Comment by mkzie2** [comment] 2024-09-26 08:11
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
The second expense preview is hidden briefly after returning to expense report via header subtitle

### What is the root cause of that problem?
1. The expense preview is hidden briefly

`loadNewerChats` is called with a delay here because we wrapped it in `InteractionManager.runAfterInteractions` and `requestAnimationFrame`

https://github.com/Expensify/App/blob/2d0d4e9618970547e8a42886f0a34b37526022e1/src/pages/home/report/ReportActionsList.tsx#L617-L619

That leads `isFirstLinkedActionRender` ref being updated to `false` after more delay [here](https://github.com/Expensify/App/blob/2d0d4e9618970547e8a42886f0a34b37526022e1/src/pages/home/report/ReportActionsView.tsx#L317)

https://github.com/Expensify/App/blob/2d0d4e9618970547e8a42886f0a34b37526022e1/src/pages/home/report/ReportActionsView.tsx#L395

As a result, it takes more time to change `reportActions` from `[preview1]` (`isFirstLinkedActionRender.current` is `true`) to `[preview1, preview 2]` (`isFirstLinkedActionRender` is changed to `false`)

https://github.com/Expensify/App/blob/2d0d4e9618970547e8a42886f0a34b37526022e1/src/pages/home/report/ReportActionsView.tsx#L232-L234

2. This happens every time we click on the header subtitle of the transaction thread report

We use `goBack` with `shouldEnforceFallback` as `true` to ensure we navigate to the previous report instead of going back. Then because it's a new screen in the stack, this bug happens as the reason at the point 1.

https://github.com/Expensify/App/blob/2d0d4e9618970547e8a42886f0a34b37526022e1/src/components/ParentNavigationSubtitle.tsx#L47
### What changes do you think we should make in order to solve the problem?
1. If we agree that it's not a bug we can do nothing here since this change is added [here](https://github.com/Expensify/App/pull/49477) to fix another bug. If not, we should remove this change and find another solution to fix the issue related to this change.

https://github.com/Expensify/App/blob/2d0d4e9618970547e8a42886f0a34b37526022e1/src/pages/home/report/ReportActionsList.tsx#L617-L619

2. To prevent the flicker when clicking on the header subtitle, we should use `Navigation.isNavigationReady` here instead of passing `shouldEnforceFallback` param as `true`

```
Navigation.isNavigationReady().then(() => {
    Navigation.goBack(ROUTES.REPORT_WITH_ID.getRoute(parentReportID, parentReportActionID));
});
```

https://github.com/Expensify/App/blob/2d0d4e9618970547e8a42886f0a34b37526022e1/src/components/ParentNavigationSubtitle.tsx#L47

### What alternative solutions did you explore? (Optional)

**Comment by francoisl** [comment] 2024-10-01 22:19
@fedirjh are you available to review the proposal above please?

**Comment by mkzie2** [comment] 2024-10-03 14:01
> However, the second option in your solution won't work if we deep link to the transaction report first and then navigate back to the expense report.

@fedirjh This case will not work because in this case it's the first time the expense report is rendered and as I mentioned in the RCA, this bug will happen.

https://github.com/Expensify/App/blob/2d0d4e9618970547e8a42886f0a34b37526022e1/src/pages/home/report/ReportActionsList.tsx#L617-L619

**Comment by ikevin127** [comment] 2024-10-03 20:01
@fedirjh Thanks for the ping!

> Should we just leave things as they are and close this issue since the behavior exists in production

I'd vote for close since there was always a small delay in this case. However:

> The delay caused by `InteractionManager.runAfterInteractions` combined with `requestAnimationFrame` can vary depending on the device's performance and current load. However, in general:
>
> - `InteractionManager.runAfterInteractions` queues work to run after all ongoing interactions (like gestures or animations) are completed. The exact timing depends on when the ongoing interactions finish, which can vary but typically happens immediately after the current interaction finishes.
>
> - `requestAnimationFrame` schedules the callback to be executed on the next repaint, which is typically around 16.67 milliseconds on a 60Hz display (since the screen refreshes every 16.67ms).
>
> So the total delay would be roughly the time it takes for the current interactions to complete plus one frame delay (around 16.67ms). In most cases, the combined delay will be in the range of 16.67ms to a few hundred milliseconds, depending on how long the interactions take to finish.

Given this, if it's really important to have 0 delay and the expense preview show instantly, I agree that the logic should be adjusted and our PR considered a regression 👍

**Comment by huult** [comment] 2024-10-04 00:20
@ikevin127 May I ask if a final decision has been made on that case?

**Comment by ikevin127** [comment] 2024-10-04 00:22
♻️ We're awaiting on a decision from the people assigned to this issue.

**Comment by francoisl** [comment] 2024-10-05 01:09
Hm but reverting the PR would mean reintroducing the issue it fixed.

Let's keep this open for now and see if anyone can come up with an alternative solution that avoids the delay without having to revert https://github.com/Expensify/App/pull/49477.

**Comment by huult** [comment] 2024-10-09 04:48
## Proposal

### Please re-state the problem that we are trying to solve in this issue.

Expense preview is hidden briefly when returning to expense report via header subtitle

### What is the root cause of that problem?

We delayed 'onStartReached' until the initial 'sortedVisibleReportActions' data was applied and the page finished rendering, which caused a delay in displaying the expense report

https://github.com/Expensify/App/blob/6556e9a31ad3433a2d9471d0ad1029919c549c55/src/pages/home/report/ReportActionsList.tsx#L618

### What changes do you think we should make in order to solve the problem?

To resolve this issue, we need to apply a delay to onStartReached for the Search case while keeping the logic unchanged for other cases.

```diff
  const onStartReached = useCallback(() => {
-        InteractionManager.runAfterInteractions(() => requestAnimationFrame(() => loadNewerChats(false)));
+        const loadChats = () => loadNewerChats(false);

+        if (isSearchTopmostCentralPane()) {
+            InteractionManager.runAfterInteractions(() => requestAnimationFrame(loadChats));
+        } else {
+            loadChats();
+        }
+    }, [loadNewerChats]);
```

<summary>
<details>POC

https://github.com/user-attachments/assets/5170b6ce-db3a-453c-9377-b743014cc867

</details>
</summary>

**Comment by huult** [comment] 2024-10-15 01:18
@fedirjh Could you please review [my proposal](https://github.com/Expensify/App/issues/49741#issuecomment-2401309190)?

**Comment by francoisl** [comment] 2024-10-18 22:37
@fedirjh can you review [this proposal](https://github.com/Expensify/App/issues/49741#issuecomment-2401309190) please?

**Comment by wildan-m** [comment] 2024-10-25 02:38
## Proposal

### Please re-state the problem that we are trying to solve in this issue.

Expense preview briefly hides when returning to expense report via header subtitle.

### What is the root cause of that problem?

When there is linked comment, we load newer chat. This will cause layout shift since the highlighted report action is near CreatedAction / Welcome Text.

### What changes do you think we should make in order to solve the problem?
If there is linked reportActionID, we should pending the loadNewerChat until user interact with the list, we can define interact by `onTouch`, `onScroll` and `onWheel` event.

Create new `hasInteracted` state, prevent load newer chat if user not interacted and we have linked report
```tsx

    const [hasInteracted, setHasInteracted] = useState(false);

    const onStartReached = useCallback(() => {
        if(!hasInteracted && linkedReportActionID !== '-1')
        {
            return;
        }

        InteractionManager.runAfterInteractions(() => {
            requestAnimationFrame(() => {
                loadNewerChats(false);
            });
        });
    }, [loadNewerChats]);

```

If linkedreportaction exists, load newerchat at the time user start to interact

```tsx

    const handleInteraction = () => {
        if (hasInteracted) {
            return;
        }
        setHasInteracted(true);

        if(!linkedReportActionID || linkedReportActionID === '-1')
        {
            return;
        }
        loadNewerChats(false);
    };
```

put handleInteraction in `trackVerticalScrolling`, `onTouchStart`, `onWheel`
```tsx

                <InvertedFlatList
                    onScroll={trackVerticalScrolling}
                    onTouchStart={handleInteraction}
                    onWheel={handleInteraction}

```
[Branch for this solution](https://github.com/Expensify/App/compare/main...wildan-m:wildan/fix/49741-don't-load-chat-unless-user-interact?expand=1)

### What alternative solutions did you explore? (Optional)
N/A

**Comment by wildan-m** [comment] 2024-10-29 03:54
@fedirjh My proposal causes scrolling regression with many chats, jumping to the bottom data. Please disregard it.

**Comment by huult** [comment] 2024-10-29 13:32
@fedirjh Yes, we need the first patch to fix issue [#48808](https://github.com/Expensify/App/issues/48808)

**Comment by wildan-m** [comment] 2024-10-29 14:02
FYI this issue also occurred when we refresh the page, not only by klicking
header link

**Comment by huult** [comment] 2024-10-29 14:24
> @huult Yes, I was unable to reproduce the bug after removing the patch. Would you mind trying to replicate it on your side?
@fedirjh  Same as you, I am unable to reproduce this issue anymore after deleting it, but I think we should still keep it to be safer and reduce regression testing.

**Comment by francoisl** [comment] 2024-11-05 20:10
Hm that's a tough one.
I tested @huult's solution and it works fine for me, so I think I'm leaning towards moving forward with the proposal. There's also a good point that reverting would possibly risk reintroducing some different issues we're not necessarily aware of right now.

So @huult, feel free to send a PR for your [proposal](https://github.com/Expensify/App/issues/49741#issuecomment-2401309190). Thanks!

**Comment by huult** [comment] 2024-11-06 01:57
Thank you all. I will create a pull request after the issue I asked about in the Slack group is resolved. [https://expensify.slack.com/archives/C01GTK53T8Q/p1730857949391549](https://expensify.slack.com/archives/C01GTK53T8Q/p1730857949391549)

**Comment by huult** [comment] 2024-11-22 16:26
@RachCHopkins @francoisl Sorry, I still have not received the payment. Can you help me check? Maybe we have an issue with Upwork?

**Comment by francoisl** [comment] 2024-11-26 18:07
@RachCHopkins are you available to help with the payments here please?

**Comment by RachCHopkins** [comment] 2024-11-27 00:21
I sure am! Sorry guys, my fancy zap malfunctioned and I didn't see the ping! I'll get this sorted out asap.

**Comment by RachCHopkins** [comment] 2024-11-27 00:25
Payment Summary:

- Contributor: @huult to be paid $250 via Upwork
- Contributor+: @fedirjh to be paid $250 via NewDot Manual Request

Upwork job [here](https://www.upwork.com/jobs/~021839062492993280361)

**Closed** 2024-11-27 00:26 UTC
Labels: External, Engineering, Daily, Awaiting Payment

**Comment by garrettmknight** [comment] 2024-12-10 12:28
$250 approved for @fedirjh
