### ISSUE TITLE
IOU - Uploading a receipt with >24MB freezes the app for a while

### ISSUE THREAD

**Issue by m-natarajan** [Expensify/App#46882] opened 2024-08-06 12:59 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___
Found when validating https://github.com/Expensify/App/pull/45448
**Version Number:** 9.0.17-0
**Reproducible in staging?:** y
**Reproducible in production?:** n
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):** nathanmulugetatesting+881@gmail.com
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** Applause internal team
**Slack conversation:**

## Action Performed:
1. Navigate to staging.new.expensify.com
2. Submit an expense to a user or a workspace
3. Open the expense detail and click on the add receipt button
4. Upload a picture with size > 24MB

## Expected Result:
The app quickly closes the RHP and shows navigates to the expense details page (which is the behavior seen for smaller file sizes), or the app should show a loading spinner
## Actual Result:
The app freezes for a while when reducing the file size and clicking on anything is not functional

## Workaround:
unknown
## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [x] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [X] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

https://github.com/user-attachments/assets/2974513b-a6fc-4cea-b478-21221fd0b2cd

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by dangrous** [comment] 2024-08-06 13:16
I thiiiink I agree that this is not a blocker - I believe before the latest deploy you just couldn't upload images greater than 24mb, so this is better than that.

However, we should probably have @luacmartins @nkdengineer @shubham1206agra take a look since it's the new functionality [they introduced](https://github.com/Expensify/App/issues/44084).

I'm going to demote this, but keep as daily.

**Comment by luacmartins** [comment] 2024-08-06 14:28
@nkdengineer @shubham1206agra could you please take a look?

**Comment by nkdengineer** [comment] 2024-08-06 14:49
@luacmartins The reason is the resize function takes a long time with the large image. Then I don't think it's a bug.

If we want to improve this case, we can display a loading while the image is uploading. What do you think?

cc @shubham1206agra

**Comment by luacmartins** [comment] 2024-08-07 07:36
Agreed! Let's add a loading indicator while things are processing.

**Comment by nkdengineer** [comment] 2024-08-07 08:46
@shubham1206agra The PR is [here](https://github.com/Expensify/App/pull/46944).

cc @luacmartins Please help look at the screenshot and let me know your thoughts.

**Comment by dangrous** [comment] 2024-08-16 14:15
I think this went to prod 8/12 but the automation didn't fire. If everything looks good, we can work to close out on 8/19.

Will we need payment for this? or is it regression/followup from https://github.com/Expensify/App/issues/44084

**Comment by nkdengineer** [comment] 2024-08-16 14:19
Yes, no payment is required here. It's an improvement from https://github.com/Expensify/App/issues/44084

**Comment by dangrous** [comment] 2024-08-19 14:30
Awesome! closing out then.

**Closed by dangrous** 2024-08-19 14:30 UTC
Labels: Reviewing, Engineering, Weekly, Bug
