### ISSUE TITLE
Login - Error "Couldn't retrieve account details, please try to sign in again." during login

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#38676] opened 2024-03-20 13:49 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.55-0
**Reproducible in staging?:**  Y
**Reproducible in production?:** N
**If this was caught during regression testing, add the test name, ID and link from TestRail:** N/A
**Issue reported by:** Applause - Internal Team

## Action Performed:
1. Go to staging.new.expensify.com.
2. Log in with the following Expensifail account:
- [applausetester+031824fish@applause.expensifail.com](mailto:applausetester+031824fish@applause.expensifail.com)

- [applausetester+uo110@applause.Expensifail.com](mailto:applausetester+uo110@applause.Expensifail.com)

- [applausetester+190302su@applause.expensifail.com](mailto:applausetester+190302su@applause.expensifail.com)

- [applausetester+kh200301@applause.expensifail.com](mailto:applausetester+kh200301@applause.expensifail.com)

For Gmail:
- [u.onyeukwu94@gmail.com](mailto:u.onyeukwu94@gmail.com)

## Expected Result:
User will be able to log in without issue

## Actual Result:
Error "Couldn't retrieve account details, please try to sign in again." shows up when submitting the email.
This issue happens with all Expensifail and Gmail accounts and not specific to the accounts above. On production, there is no login issue

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [x] Android: mWeb Chrome
- [x] iOS: Native
- [x] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details> 

<img width="1440" alt="Bug6420493_1710941716488!staging" src="https://github.com/Expensify/App/assets/78819774/e41a5f1f-ec37-4c14-8ded-b26f2b3620ee">

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by lanitochka17** [comment] 2024-03-20 13:50
@danieldoglas  FYI I haven't added the External label as I wasn't 100% sure about this issue. Please take a look and add the label if you agree it's a bug and can be handled by external contributors

**Comment by lanitochka17** [comment] 2024-03-20 13:51
We think that this bug might be related to #vip-vsp

**Comment by kavimuru** [comment] 2024-03-20 14:06
@shubham1206agra Are you not able to reproduce with any of those accounts? Our QA team is not able to sign in with many test  accounts, but we shared few of them in the report though.

**Comment by danieldoglas** [comment] 2024-03-20 14:12
@kavimuru this is only happening in staging?

**Comment by danieldoglas** [comment] 2024-03-20 14:15
Thanks for that @shubham1206agra . Can you look send me the headers of that request that failed? 

@kavimuru @lanitochka17 if you have those too, it would be great.

**Comment by danieldoglas** [comment] 2024-03-20 14:26
Thanks @shubham1206agra!

@kavimuru @lanitochka17 this should be fixed now!

**Comment by danieldoglas** [comment] 2024-03-20 14:27
Let me know if you still face issues.

**Comment by danieldoglas** [comment] 2024-03-20 17:08
Closing this one for now

**Closed by danieldoglas** 2024-03-20 17:08 UTC
Labels: Engineering, Daily

**Comment by kavimuru** [comment] 2024-03-20 18:13
@danieldoglas Testers are not facing this issue. Sorry for the late reply.
