### ISSUE TITLE
[Awaiting Payment 26th Sept] [CRITICAL] Update the free trial badge to display Start a free trial badge when we create a workspace for a user

### ISSUE THREAD

**Issue by danielrvidal** [Expensify/App#48217] opened 2024-08-28 20:26 UTC
**Proposal**: Update the free trial badge to display `Start a free trial` badge when we create a workspace for a user

**Problem**: Users don't really have a sense of urgency when it comes to configuring and using their workspace on creating it. Users also do not know right now that their workspace is a paid feature unless (1) a free trial starts, which does not happen till a user creates an expense on the workspace, which triggers the 7-day free trial to start that includes a badge on Concierge and in the Settings - Subscription tab says `Free Trial: 7 days left` or 2) they navigate to Settings -Subscription and learn about paid plans. 

**Solution**: Show a `Start a free trial` badge on Concierge DM and in Settings - Subscriptions tab (LHN) when the workspace is first created. 
1. We already show this badge on Settings - Subscriptions tab itself when the workspace is first created. Leave that as is.
2. When a user takes a billable action on that workspace, we currently show a `Free trial: X days left` in both the Concierge DM and Settings - Subscription tab (LHN). Keep this also as is. I.e. update the `Start a free trial` to `Free trial: X days left` when billable action is taken, which officially starts the free trial clock. 

When a workspace is created, and there is no billable activity yet
![image](https://github.com/user-attachments/assets/878c1f80-8f2a-49da-9cc7-9063eb80e6fb)

![image](https://github.com/user-attachments/assets/9205c1ae-7386-4ad7-bd3b-5fc4f3a3744e)

Send a notification but lag this notification by a full minute so it isn't sent between the onboarding tasks itself
![image](https://github.com/user-attachments/assets/19fe1a23-d087-4ed0-a0e0-805e73361492)

<details><summary>Issue Owner</summary>Current Issue Owner: @trjExpensify</details>

**Comment by anmurali** [comment] 2024-08-28 23:37
I think @neonbhai is on the right track. I updated the mockups for clarity in the issue description. @rojiphil @chiragsalian - can you both take a quick review?

**Comment by rojiphil** [comment] 2024-08-29 05:19
> I updated the mockups for clarity in the issue description. @rojiphil @chiragsalian - can you both take a quick review?

Yeah. It makes sense to display pre trial status in LHN and header of the chat used for onboarding. 
Looks like this can be done in FE without any need of BE support by depending on `shouldShowPreTrialBillingBanner` and the presence of any paid policies. 
@abzokhattab proposal looks more complete to me as we need to show the pre trial status only if there are any paid policies.
@chiragsalian What do you think?

**Comment by chiragsalian** [comment] 2024-08-30 01:06
Correct yeah BE is not needed for this the FE has all the information and i imagine its the same condition as when we determine to show subscription tab and then showing start a free trial banner in subscription page.

Reviewing @abzokhattab proposal,
> disable the automatic start of the free trial.

I don't follow this. Currently and after the changes to solve this issue free trial will not start when a workspace is created. 
Just to be clear, the issue here is to show a banner "Start a free trial" when workspace is created, it wont actually start a free trial.

> Create PolicyUtils.getNumberOfPolicies which returns the policies count.

This doesn't feel right or rather precise to me. Yeah like rojiphil mentioned we need to check paid policies. So a helper function like `hasPaidPolicy` makes more sense to me that would short circuit/return immediately when it finds the first paid policy would be better.

Infact i would suggest using whatever logic the subscription tab uses to show itself so that our logic stays consistent with it. And looking at that code its [here](https://github.com/Expensify/App/blob/4e7461ea064ce85addceb044f89c09d9d73190ec/src/pages/home/sidebar/AllSettingsScreen.tsx#L53) which looks at if [NVP_PRIVATE_SUBSCRIPTION](https://github.com/Expensify/App/blob/4e7461ea064ce85addceb044f89c09d9d73190ec/src/pages/home/sidebar/AllSettingsScreen.tsx#L34) exists. So yeah using that looks even simpler because that NVP is set only when a workspace is created.

Also @danielrvidal / @anmurali, about this part,
> Show a Start a free trial badge on Concierge DM 

I think that's incorrect and the "Start a free trial badge" should be on whichever chat the user was onboarded with. Since that will contain the onboarding message. 
When the free trial begins for such users the free trial badge will be on the Expensify DM and not Concierge
![image](https://github.com/user-attachments/assets/5f25e7eb-86e4-4e9f-a43b-a18776a2945b)

So it makes sense to keep having the badge in the same location as the onboarding chat otherwise it would jump around which is ugly.

**Comment by anmurali** [comment] 2024-08-30 20:09
@chiragsalian - we're removing the Expensify DM and streamlining onboarding tasks always to Concierge, hence that description

**Comment by chiragsalian** [comment] 2024-08-30 20:14
Ah okay then perfect 👍 lets use Concierge and not worry about onboarding chat reportID

**Comment by danielrvidal** [comment] 2024-08-30 22:54
Good clarification though!

**Comment by rojiphil** [comment] 2024-09-02 19:25
> Infact i would suggest using whatever logic the subscription tab uses to show itself so that our logic stays consistent with it. And looking at that code its [here](https://github.com/Expensify/App/blob/4e7461ea064ce85addceb044f89c09d9d73190ec/src/pages/home/sidebar/AllSettingsScreen.tsx#L53) which looks at if [NVP_PRIVATE_SUBSCRIPTION](https://github.com/Expensify/App/blob/4e7461ea064ce85addceb044f89c09d9d73190ec/src/pages/home/sidebar/AllSettingsScreen.tsx#L34) exists. So yeah using that looks even simpler because that NVP is set only when a workspace is created.

Yeah. While using `NVP_PRIVATE_SUBSCRIPTION` seems simpler to me too, we can also use `useSubscriptionPlan` as referred to in the updated [proposal](https://github.com/Expensify/App/issues/48217#issuecomment-2316265641) if we want to keep our logic strictly consistent with show/hide of `Subscription` option in LHN for `Settings`. But I do not see the need to define another utility function i.e. `hasPaidPolicy` as we can directly make use of `useSubscriptionPlan`. Otherwise, the primary solution in @abzokhattab updated  [proposal](https://github.com/Expensify/App/issues/48217#issuecomment-2316265641) LGTM. 
@chiragsalian What do you think?

**Comment by chiragsalian** [comment] 2024-09-03 18:46
> But I do not see the need to define another utility function i.e. hasPaidPolicy as we can directly make use of useSubscriptionPlan

I agree

> we can also change the new hasPaidPolicy to getOwnerPaidPolices so that it returns the paid policies that are owned by the user ... then we call this function in the useSubscriptionPlan as well

I don't follow this comment. useSubscriptionPlan already checks for paid policies that are owned by the user. If i have misunderstood you can you explain this with a snippet.

**Comment by chiragsalian** [comment] 2024-09-03 19:59
Your suggestion works. But i guess my original question (and even roji's) is why bother with a new hasPaidPolicy/getOwnedPaidPolicies when we could only just reuse useSubscriptionPlan. But as i think about this more i prefer your getOwnedPaidPolicies instead of useSubscriptionPlan since it eliminates the extra overhead to iterate and check for any control policies. So yeah i like getOwnedPaidPolicies. 

Let's go with that. The rest of your proposal LGTM as well. Feel free to create the PR @abzokhattab.

**Comment by mallenexpensify** [comment] 2024-09-03 21:12
Added `NewFeature` to create the Upwork job but that doesn't appear to have worked. Also, I thought someone on the design team was assigned once `NewFeature` was added. ¯\_(ツ)_/¯

**Comment by danielrvidal** [comment] 2024-09-09 20:48
Still working through the PR listed above. Constant progress is being made.

**Comment by rojiphil** [comment] 2024-09-10 07:51
@danielrvidal @anmurali While the OP of this issue has not explicitly stated to display `Your trial has ended` in LHN for Onboarding chat and `Subscription` option, the PR includes  this implementation. In a way, this also adds a sense of urgency to become a paid customer but I just wanted to cross-check if this is fine.  

https://github.com/user-attachments/assets/b275b3fd-35b1-4f8f-a3f9-1910a372eaf0

**Comment by dannymcclain** [comment] 2024-09-10 13:55
>I don't mind that, but it wasn't in the scope of the original design nor solves our problem stated in the OP really, so I'm hesitant to add it willy nilly.

I feel the same. Would love to get @dubielzyk-expensify's thoughts about it!

**Comment by dubielzyk-expensify** [comment] 2024-09-11 00:43
Agree with Tom and Danny here

**Comment by trjExpensify** [comment] 2024-09-11 01:25
Kewwwl, let's leave that off then @rojiphil.

**Comment by rojiphil** [comment] 2024-09-11 05:06
> let's leave that off then @rojiphil.

Yeah. It's better to leave it as that's the consensus. 

@abzokhattab Since the implementation mentioned [here](https://github.com/Expensify/App/issues/48217#issuecomment-2339925511) is not required, let us remove this from the PR. Thanks.

**Comment by danielrvidal** [comment] 2024-09-20 19:37
Woo! Just tested it and it looks great!
<img width="1314" alt="image" src="https://github.com/user-attachments/assets/ea0e8c35-8f0a-44fb-a213-d4ad50040125">

**Comment by trjExpensify** [comment] 2024-09-23 16:49
Nicee! Updated the title to reflect the payment hold.

**Comment by trjExpensify** [comment] 2024-09-25 16:18
Payment will be due tomorrow.

**Comment by trjExpensify** [comment] 2024-09-25 16:18
Can we get a regression test for this please, @rojiphil?

**Comment by rojiphil** [comment] 2024-09-26 01:50
> Can we get a regression test for this please, @rojiphil?

@trjExpensify Sure, the regression test is as follows:.

1. Sign in with a new account.
2. Complete the onboarding process using `Track and Budget Expenses`
3. In the onboarding Concierge report, validate that the LHN and the header do not display the free trial badge
4. Click on Settings->Workspaces->New Workspace and create a new workspace.
5. Verify that the LHN for Concierge report, report header for Concierge report, and the subscription tab inside the account settings display the `Start a free trial` message.
6. Submit a new expense to the workspace.
7. Verify that the LHN for Concierge report, report header for Concierge report, and the subscription tab inside the account settings display the `Free trial: 7 days left!` message.

**Comment by trjExpensify** [comment] 2024-09-26 22:52
Excellent, issue created! 

Payments as follows: 

- $250 to @rojiphil for the C+ review
- $250 to @abzokhattab for the fix

Offers sent!

**Comment by chiragsalian** [comment] 2024-09-26 23:07
Payment increase to 500 sounds fair to me. I let tom make the final decision and handle the payment.

**Comment by trjExpensify** [comment] 2024-09-26 23:22
Amended, paid @abzokhattab.

**Comment by rojiphil** [comment] 2024-09-27 02:15
> * $500 to @rojiphil for the C+ review

@trjExpensify Accepted offer. Thanks.

**Comment by trjExpensify** [comment] 2024-09-27 09:38
Paid, closing!

**Closed by trjExpensify** 2024-09-27 09:38 UTC
Labels: External, Daily, NewFeature, Awaiting Payment
