### ISSUE TITLE
[HOLD for payment 2023-06-21] [$1000] Web - Room - Visibility subtitle is wrong for public room

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#20127] opened 2023-06-03 17:59 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Click on + icon
2. Choose new room option
3. Enter room name
4. Choose visibility as public and check subtitle below the dropdown (Anyone can find this room) 
5. Click on create room button
6. Go to room
7. Click on header to see Details
8. Go to Settings and check text in Visibility section

## Expected Result:
For public room text should be  Anyone can find this room

## Actual Result:
Wrong text shows(People invited to this room can find it)

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [x] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 1.3.23.6

**Reproducible in staging?:** yes

**Reproducible in production?:** yes

**If this was caught during regression testing, add the test name, ID and link from TestRail:**

**Email or phone of affected tester (no customers):**

**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/93399543/740e0b98-904b-46cd-a1d9-5b9a7385f985

![Screenshot 2023-05-31 at 3 12 02 PM](https://github.com/Expensify/App/assets/93399543/0520f563-07c1-4203-8865-a732ee62b238)

https://github.com/Expensify/App/assets/93399543/e4750120-1018-4231-a6fd-7a3f1a4536ea

**Expensify/Expensify Issue URL:**

**Issue reported by:** @gadhiyamanan

**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1685526019865179

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01005cb0382b9b4e71</li>
        <li>Upwork Job ID: 1666314654139772928</li>
        <li>Last Price Increase: 2023-06-07</li>
    </ul>
</details>

**Comment by gadhiyamanan** [comment] 2023-06-03 17:59
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
Visibility subtitle is wrong for public room
### What is the root cause of that problem?
no condition added for public room description
https://github.com/Expensify/App/blob/efb1463625ba784999dce58dec0faa9163e33e0b/src/pages/settings/Report/ReportSettingsPage.js#L204-L208
### What changes do you think we should make in order to solve the problem?
use ```{this.props.translate(`newRoomPage.${this.props.report.visibility}Description`)}``` instead of below condition same as `WorkspaceNewRoomPage.js`
https://github.com/Expensify/App/blob/efb1463625ba784999dce58dec0faa9163e33e0b/src/pages/settings/Report/ReportSettingsPage.js#L204-L208
### What alternative solutions did you explore? (Optional)
None

**Comment by JmillsExpensify** [comment] 2023-06-07 05:21
Yeah, I'm able to reproduce this one. Opening it up for proposal/reviews

![Screenshot 2023-06-06 at 23 21 30](https://github.com/Expensify/App/assets/1127863/151e06e3-38f7-4e2e-8cef-b3681a01b1c7)

**Comment by tungmt** [comment] 2023-06-07 08:20
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
Visibility description is wrong for public room.

### What is the root cause of that problem?
Current visibility description only either restricted or private.

```
<Text style={[styles.textLabelSupporting, styles.mt1]}>
        p.{this.props.report.visibility === CONST.REPORT.VISIBILITY.RESTRICTED
           ? this.props.translate('newRoomPage.restrictedDescription')
           : this.props.translate('newRoomPage.privateDescription')}
</Text>
```

### What changes do you think we should make in order to solve the problem?
Solution 1: Use switch to get the correct description

```
visibilityDescription(visibility) {
        switch (visibility) {
            case CONST.REPORT.VISIBILITY.RESTRICTED:
                return this.props.translate('newRoomPage.restrictedDescription');
            case CONST.REPORT.VISIBILITY.PRIVATE:
                return this.props.translate('newRoomPage.privateDescription');
            default:
                return this.props.translate('newRoomPage.publicDescription');
        }
    }
```

```
<Text style={[styles.textLabelSupporting, styles.mt1]}>
     {this.visibilityDescription(this.props.report.visibility)}
</Text>
```



Solution 2: Use one more check condition

```
<Text style={[styles.textLabelSupporting, styles.mt1]}>
        {this.props.report.visibility === CONST.REPORT.VISIBILITY.RESTRICTED
                  ? this.props.translate('newRoomPage.restrictedDescription')
                     : (this.props.report.visibility === CONST.REPORT.VISIBILITY.PRIVATE ?
                               this.props.translate('newRoomPage.privateDescription')
                               : this.props.translate('newRoomPage.publicDescription')
                       )
       }
</Text>
```

### What alternative solutions did you explore? (Optional)

**Comment by maxim-abuzarov** [comment] 2023-06-07 10:42
## Proposal
### Please re-state the problem that we are trying to solve in this issue.
Visibility subtitle is wrong for public room

### What is the root cause of that problem?
There are no condition added for public room description.
https://github.com/Expensify/App/blob/79f18eca86c35fca8055e7036ca2d449ad34f85a/src/pages/settings/Report/ReportSettingsPage.js#L202-L206

### What changes do you think we should make in order to solve the problem?
The easiest way is to change 
```
{this.props.report.visibility === CONST.REPORT.VISIBILITY.RESTRICTED 
         ? this.props.translate('newRoomPage.restrictedDescription') 
         : this.props.translate('newRoomPage.privateDescription')} 
```
to
``
{this.props.translate(`newRoomPage.${this.props.report.visibility}Description`)}
``

**Comment by maxim-abuzarov** [comment] 2023-06-07 10:51
```
Contributor details
Your Expensify account email: maksim.abuzarov@yandex.ru
Upwork Profile Link: https://www.upwork.com/freelancers/~01697caeeda3411355
```

**Comment by JmillsExpensify** [comment] 2023-06-08 03:37
@abdulrahuman5196 thoughts on these proposals?

**Comment by abdulrahuman5196** [comment] 2023-06-08 13:47
@JmillsExpensify  Thank you for checking up.

@gadhiyamanan's proposal here https://github.com/Expensify/App/issues/20127#issuecomment-1575100645 looks good. All other proposals present here are the same with minor variations so choosing the first proposal.

🎀👀🎀
C+ Reviewed

cc: @madmax330

**Comment by JmillsExpensify** [comment] 2023-06-09 03:28
Ok great, thanks! @madmax330 You good with this approach? If so, let's get the contributor assigned and put this in motion. 🙌🏼

**Comment by madmax330** [comment] 2023-06-09 06:23
Yeah looks good to me

**Comment by gadhiyamanan** [comment] 2023-06-09 06:48
@abdulrahuman5196 @madmax330 [PR](https://github.com/Expensify/App/pull/20500) is ready for review

**Comment by abdulrahuman5196** [comment] 2023-06-21 15:53
>The PR that introduced the bug has been identified. Link to the PR:
The offending PR has been commented on, pointing out the bug it caused and why, so the author and reviewers can learn from the mistake. Link to comment:
A discussion in #expensify-bugs has been started about whether any other steps should be taken (e.g. updating the PR review checklist) in order to catch this type of bug sooner. Link to discussion:

Doesn't seem to be regression. It seems to be a miss from the original page implementation itself and we haven't noticed before the bug report - https://github.com/Expensify/App/pull/16910

>Determine if we should create a regression test for this bug.
[@abdulrahuman5196] If we decide to create a [regression test](https://github.com/Expensify/App/blob/main/contributingGuides/REGRESSION_TEST_BEST_PRACTICES.md) for the bug, please propose the regression test steps to ensure the same bug will not reach production again.

No. I don't think a regression test would be beneficial for this minor issue.

**Comment by abdulrahuman5196** [comment] 2023-06-23 15:25
Gentle ping on payment processing for this issue @JmillsExpensify

**Comment by madmax330** [comment] 2023-06-26 10:34
bump @JmillsExpensify

**Comment by JmillsExpensify** [comment] 2023-06-27 04:46
Thanks for your patience, summarizing payouts for this issue:

 - Issue reporter: @gadhiyamanan $250
 - Contributor: @gadhiyamanan $1,500
 - Contributor+: @abdulrahuman5196 $1,500

Upwork job [is here](https://www.upwork.com/jobs/~01005cb0382b9b4e71). I'll issue bonus on final payout.

**Comment by gadhiyamanan** [comment] 2023-06-27 04:49
@JmillsExpensify accepted, thanks!

**Comment by abdulrahuman5196** [comment] 2023-06-27 04:49
Thank you @JmillsExpensify. Accepted the upwork offer.

**Comment by JmillsExpensify** [comment] 2023-06-28 18:16
Closing this, please comment if anything is outstanding.

**Closed by JmillsExpensify** 2023-06-28 18:16 UTC
Labels: External, Daily, Awaiting Payment, Bug
