### ISSUE TITLE
[$500]  Room - @expensify.sms suffix appears after invitation & disappears after opening user avatar

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#35089] opened 2024-01-24 18:54 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.31-2
**Reproducible in staging?:** Y
**Reproducible in production?:** N
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** Applause - Internal Team
**Slack conversation:**

## Action Performed:
1. Go to a room
2. Click on the room header > Members > Invite
3. Invite via phone number
4. Return to the main chat
5. Click on the phone number in the invite notification
6. Note that it shows @expensify.sms
7. Click on the avatar
8. Close the avatar

## Expected Result:
@expensify.sms should remain (behavior on production)

## Actual Result:
@expensify.sms suffix disappears after opening user avatar

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [x] Android: mWeb Chrome
- [ ] iOS: Native
- [x] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details> 

https://github.com/Expensify/App/assets/78819774/ae6e4857-b41a-4369-a934-86face6fb545

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01bcbbe2d08d76f86e</li>
        <li>Upwork Job ID: 1752445825076850688</li>
        <li>Last Price Increase: 2024-03-19</li>
<li>Automatic offers: </li>
<ul>
<li>dukenv0307 | Contributor | 0</li>
</ul></li>
    </ul>
</details>

**Comment by thienlnam** [comment] 2024-01-25 05:48
Not sure if this was an intentional update or not. But doesn't seem to need to be a blocker

**Comment by tylerkaraszewski** [comment] 2024-02-16 19:46
Ideally yes, we should fix this everywhere.

**Comment by tylerkaraszewski** [comment] 2024-02-26 20:14
No proposals so far, huh?

**Comment by tylerkaraszewski** [comment] 2024-02-29 17:48
@aimane-chnaif what do you think?

**Comment by tylerkaraszewski** [comment] 2024-03-14 21:26
This is blocked on backend changes that haven't really been prioritized so far.

**Comment by mvtglobally** [comment] 2024-03-20 03:16
Issue not reproducible during KI retests. (First week)

**Comment by tylerkaraszewski** [comment] 2024-03-29 18:22
Discussion here about how to fix the backend issue: https://expensify.slack.com/archives/C03TQ48KC/p1711403191153639

**Comment by tylerkaraszewski** [comment] 2024-04-08 23:51
I'm making this weekly because it's like my 3rd priority right now.

**Comment by tylerkaraszewski** [comment] 2024-04-22 22:22
I should be able to look into this this week.

**Comment by tylerkaraszewski** [comment] 2024-05-02 22:48
I did not. Maybe next week.

**Comment by tylerkaraszewski** [comment] 2024-05-13 18:24
This has been sitting for months. I am closing it.

**Closed by tylerkaraszewski** 2024-05-13 18:24 UTC
Labels: External, Engineering, Weekly, Overdue
