### ISSUE TITLE
[HOLD #39616] [Track Tax] Expense request with tax amount higher than the tax rate limit can be created

### ISSUE THREAD

**Issue by izarutskaya** [Expensify/App#39703] opened 2024-04-05 12:03 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.60-8
**Reproducible in staging?:** Y
**Reproducible in production?:** N
**Found when validating PR:** https://github.com/Expensify/App/pull/33927
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Issue reported by:** Applause-Internal team

## Action Performed:
Precondition:
- Collect workspace has tax rates.
- Workspace Currency Default has 20% tax.
- Foreign Currency Default has 10% tax.

1. Go to staging.new.expensify.com
2. Go to Collect workspace chat.
3. Start manual request flow using foreign currency.
4. In confirmation page, click Show more.
5. Keep the default tax rate, where it applies Workspace Currency Default (20%).
6. Click Tax amount.
7. Manually edit the tax amount to within 10% to 20% tax amount.
8. Create the request.
9. Go to transaction thread.
10. Note that tax rate changes to Foreign Currency Default with 10% tax.
11. Note the tax amount.

## Expected Result:
In the transaction thread, the tax amount should readjust to the maximum limit of Foreign Currency Default (10%).

## Actual Result:
In the transaction thread, the tax amount does not readjust to the maximum limit of Foreign Currency Default (10%).
It still shows the tax amount entered during the creation (Step 7), which is higher than the maximum limit of Foreign Currency Default (10%).

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [x] Android: mWeb Chrome
- [x] iOS: Native
- [x] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

https://github.com/Expensify/App/assets/115492554/9d1239aa-4690-45d8-b186-d0503fb0df85

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by izarutskaya** [comment] 2024-04-05 12:04
@kevinksullivan I haven't added the External label as I wasn't 100% sure about this issue. Please take a look and add the label if you agree it's a bug and can be handled by external contributors.

**Comment by izarutskaya** [comment] 2024-04-05 12:04
We think this issue might be related to the #collect project.

**Comment by MonilBhavsar** [comment] 2024-04-05 13:02
Demoting from deploy blocker as issue lies on server side

**Comment by MonilBhavsar** [comment] 2024-04-08 12:39
Putting this on HOLD for so client can send correct taxAmount param https://github.com/Expensify/App/issues/39616

**Comment by MonilBhavsar** [comment] 2024-04-11 09:54
on HOLD

**Comment by MonilBhavsar** [comment] 2024-04-22 06:25
Still on HOLD

**Comment by kevinksullivan** [comment] 2024-04-29 22:00
Agree with wave-collect here.

**Comment by kevinksullivan** [comment] 2024-04-29 22:00
Still on hold for https://github.com/Expensify/App/issues/39616

**Comment by kevinksullivan** [comment] 2024-05-09 21:53
@MonilBhavsar still looks like this is held?

**Comment by MonilBhavsar** [comment] 2024-05-10 06:48
Yes, correct. Very close for the other PR to merge, retest this and hopefully close this issue

**Comment by MonilBhavsar** [comment] 2024-05-13 09:20
We've merged the PR and this issue is not reproducible on main. So closing

**Closed by MonilBhavsar** 2024-05-13 09:20 UTC
Labels: Engineering, Weekly, Bug
