### ISSUE TITLE
[Awaiting payment 21-12-23] [$1000] Duplicate room name error doesn't appear if you aren't a member of the original room

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#21747] opened 2023-06-27 21:09 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Go to staging.new.expensify.com
2. Create a workspace 
3. Now create a `New room` and choose the workspace you created 
4. Click the room header and leave the room
5. Now create a `New room` again using the same name of the room you just left and the same workspace you selected for the first room

## Expected Result:
The room name field should have an in-line error message upon losing focus of that field 

## Actual Result:
You're allowed to proceed to create the room and run into an error after the creation attempt. We suspect this has something to do with the check for a duplicate room existing being limited to rooms you are a member of, not the workspace you are trying to create the room on. 

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android / native
- [x] Android / Chrome
- [x] iOS / native
- [x] iOS / Safari
- [x] MacOS / Chrome / Safari
- [x] MacOS / Desktop

**Version Number:** 1.3.32-5
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/93399543/aa39727a-e159-4185-aba7-9eea714d546a

https://github.com/Expensify/App/assets/93399543/abdcad2e-e3fc-48aa-988d-d13fa9556c8b

**Expensify/Expensify Issue URL:**
**Issue reported by:** @priya-zha
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1687680050819699

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01cbde78f15d909ff4</li>
        <li>Upwork Job ID: 1675822342302105600</li>
        <li>Last Price Increase: 2023-07-10</li>
<li>Automatic offers: </li>
<ul>
<li>esh-g | Contributor | 27774680</li>
<li>priya-zha | Reporter | 27774681</li>
</ul></li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @jasperhuangg</details>

**Comment by trjExpensify** [comment] 2023-06-30 17:32
Okay, so I actually don't think the user should be getting this far in the flow if the room name is a dupe. When you're still a member of a room, we show an in-line error: 
![image (7)](https://github.com/Expensify/App/assets/16232057/468770a0-0133-4c9c-b8e2-ea182dcc3586)

But here, when you leave the room we don't do that. We let you continue on and error out on creation. So I think we should be showing a error message in-line the room name field if the room has a dupe name on the workspace you've selected. That would avoid this scenario.

**Comment by trjExpensify** [comment] 2023-07-03 11:02
Okay, updated the OP following the discussion [in thread](https://expensify.slack.com/archives/C049HHMV9SM/p1687680050819699). 

CC: @MitchExpensify

**Comment by trjExpensify** [comment] 2023-07-05 22:27
Awaiting proposals. @dukenv0307 not sure if you want to modify yours given the expected behaviour.

**Comment by trjExpensify** [comment] 2023-07-10 11:35
>@trjExpensify Let's bump this on slack to get more eyes on this?

Bump where? We can chat more in [the thread](https://expensify.slack.com/archives/C049HHMV9SM/p1687680050819699) if you want though to discuss the best approach or clarify the intention. Thanks!

**Comment by trjExpensify** [comment] 2023-07-12 21:51
Okay, let's do that to get internal engineering eyes on it.

**Comment by trjExpensify** [comment] 2023-07-17 13:42
@thienlnam, did you look at this yet?

**Comment by thienlnam** [comment] 2023-07-17 18:17
I have not, thanks for the ping

Just to get some clarification here @allroundexperts, the API call will succeed in this case? 

It seems like it should just not let you create the room, since the room still exists and we haven't removed it even if you leave it

**Comment by trjExpensify** [comment] 2023-07-18 22:54
Bump on the question @allroundexperts! Let's get this over the line before it hits WAQ.

**Comment by thienlnam** [comment] 2023-07-19 22:13
> That's not what we want here. The API call should succeed but the response it returns should be changed.

I'm not quite following this.

Watching the original video in the post I think this is expected behavior. The user created a public room, left it (the room still exists BTW), and so when you try to create another room with the same name it fails. That seems expected - you can't have all knowledge of room names because you also just can't see private rooms so this will fail in the BE. What's the problem here?

**Comment by thienlnam** [comment] 2023-07-19 22:21
> But here, when you leave the room AND then try and create a new room with the same name, we don't do that. We let you continue on and error out on creation. So I think we should be showing a error message in-line the room name field if the room has a dupe name on the workspace you've selected.

If this is the expected response, we should be able to fix this in the front-end by checking all rooms in the workspace? But I'm saying this is still going to be a problem with private rooms so I still feel like we can do nothing here

**Comment by trjExpensify** [comment] 2023-07-19 22:33
Here's [the thread](https://expensify.slack.com/archives/C049HHMV9SM/p1687680050819699) @thienlnam!

**Comment by thienlnam** [comment] 2023-07-19 22:51
Added a comment to that thread - https://expensify.slack.com/archives/C049HHMV9SM/p1689807082171029?thread_ts=1687680050.819699&cid=C049HHMV9SM, we might want to revisit this

**Comment by trjExpensify** [comment] 2023-07-24 11:00
Okay, so we're going to hold this on the [user created rooms](https://github.com/Expensify/Expensify/issues/290783) doc to introduce the ability to find rooms you aren't a member of on your workspace, as we'll likely need to use that here. 

CC: @MitchExpensify - can you add this issue wherever works best for you in the tracker so it's accounted for?

**Comment by MitchExpensify** [comment] 2023-07-24 19:04
CC: @MitchExpensify - can you add this issue wherever works best for you in the tracker so it's accounted for?

Done! Added to the main project tracking issue

**Comment by trjExpensify** [comment] 2023-08-02 16:41
Excellent. Thanks!

**Comment by trjExpensify** [comment] 2023-08-14 10:00
No change.

**Comment by trjExpensify** [comment] 2023-08-22 13:30
Same! Waiting on the linked project. :)

**Comment by trjExpensify** [comment] 2023-09-01 11:00
Still awaiting the doc to get through review :)

**Comment by trjExpensify** [comment] 2023-09-11 11:32
Detailed design doc is in review.

**Comment by jasperhuangg** [comment] 2023-09-14 23:47
It seems like we’d have to fundamentally remove the front-end error checking since it doesn't seem like this check is something we can perform optimistically with the data we have in the front-end.

The check in Auth [here](https://github.com/Expensify/Auth/blob/main/auth/command/CreatePolicyRoom.cpp#L88-L93) has access to all the rooms on the policy. However the check in the front-end would only have access to rooms that are in the user's Onyx store, i.e. rooms they're a member of.

**Comment by MitchExpensify** [comment] 2023-09-15 17:46
@thienlnam mind providing a summary of where we stand with proposals here?

**Comment by trjExpensify** [comment] 2023-09-20 11:30
Hm, Jasper.. how do we show policy rooms they aren't a member of in search?

**Comment by thienlnam** [comment] 2023-09-22 04:42
I'll re-assign to @jasperhuangg since he's working on the linked held issue

**Comment by trjExpensify** [comment] 2023-10-02 14:54
@jasperhuangg @MitchExpensify not sure why Melv moved this to `daily`, but `weekly` held on the linked issue makes sense to me still. 

Equally, would be good to firm up on how and where it's being addressed.

**Comment by jasperhuangg** [comment] 2023-10-03 23:32
@esh-g Ah got it, I didn't realize we had a new form system for error messages. I'll get a PR up. We can work on the front-end proposal assuming that the error will exist in the form as expected. Thanks for clarifying.

**Comment by jasperhuangg** [comment] 2023-10-03 23:38
@esh-g I think for now we should use the errors that are already being passed back by the back-end in `ONYXKEYS::COLLECTION_REPORT<reportID> => errorFields => addWorkspaceRoom`. I'm not seeing anywhere in the back-end where we're storing errors into these form keys yet.

**Comment by esh-g** [comment] 2023-10-04 10:48
@jasperhuangg We are doing it for the `AddDebitCard` page here:

<img width="473" alt="Screenshot 2023-10-04 at 3 44 09 PM" src="https://github.com/Expensify/App/assets/77237602/2fc10bb3-d42b-4636-bca1-896a53f00284">

But still if we want to show the generic error message on failure, let me know because I can draft a proposal for that because the error that is being set in the report itself isn't accessible while setting the failure data for the API write and I don't think we want to use a `.then` promise method to run after the request and check the `report` for errors...

**Comment by trjExpensify** [comment] 2023-10-06 19:22
@jasperhuangg how can this be worked on ahead of figuring on allowing people to discover rooms on their workspace that they aren't necessarily a member of yet?

**Comment by trjExpensify** [comment] 2023-10-09 10:58
Same question as above, Melv.

**Comment by MitchExpensify** [comment] 2023-10-09 22:52
Friendly bump on[ this Q](https://github.com/Expensify/App/issues/21747#issuecomment-1751302061) from @trjExpensify , @jasperhuangg

**Comment by trjExpensify** [comment] 2023-10-12 16:20
Same, @jasperhuangg can you shed any light on that question?

**Comment by jasperhuangg** [comment] 2023-10-17 20:56
Got it! If that's the case then I'm convinced that we need back-end changes to set the form error.

**Comment by trjExpensify** [comment] 2023-10-23 13:12
Thanks, @jasperhuangg. Can you link that PR here?

**Comment by MitchExpensify** [comment] 2023-10-28 21:58
Friendly bump for your catch up @jasperhuangg

**Comment by trjExpensify** [comment] 2023-10-30 10:27
Yup, I think @jasperhuangg you mentioned an issue [here](https://github.com/Expensify/App/issues/21747#issuecomment-1767167615) a couple of weeks ago but I can't see it?

**Comment by trjExpensify** [comment] 2023-11-02 00:36
Bump again.

**Comment by jasperhuangg** [comment] 2023-11-02 18:00
Hey! Just catching up here. I wasn't able to create a PR for this yet, apologies for the delay. I created an issue for it [here](https://github.com/Expensify/Expensify/issues/332760)

**Comment by trjExpensify** [comment] 2023-11-06 11:31
Okay cool, it's unassigned, will you be taking that BE issue on? Also, should we update the hold of this issue to point to that issue for more accuracy of the chain of dependencies?

**Comment by pecanoro** [comment] 2023-11-07 21:04
Hey guys, so I am adding the error in the back-end, the same way as `addDebitCardForm` but it seems it's not being handled properly in the front-end. Is it part of the issue to start handling in the form or am I missing some context in this issue?

![image](https://github.com/Expensify/App/assets/6474442/cc8e7296-4d93-4d24-8641-5c8032115b97)

**Comment by esh-g** [comment] 2023-11-08 11:05
Yes, we would need to update the `newRoomForm` to not be enabled offline and then prevent the room from being created optimistically

**Comment by pecanoro** [comment] 2023-11-08 15:45
@esh-g Ok, so the update to Onyx I mentioned [here](https://github.com/Expensify/App/issues/21747#issuecomment-1800115658) is good, right? And then you guys can work with that in the front-end. Any other change I need to make in the back-end?

**Comment by trjExpensify** [comment] 2023-11-08 16:08
>to not be enabled offline 

what does that mean exactly?

**Comment by esh-g** [comment] 2023-11-08 16:11
@trjExpensify We would have to wait for a response from the API to check for the error, my exact meaning was not dismissing the modal immediately and wait to see if the API request succeeds, which it does not do currently. I'll draft a whole proposal based on @pecanoro's change to the backend (which I think is all that is needed)

**Comment by esh-g** [comment] 2023-11-08 16:25
@trjExpensify @jasperhuangg  Could you please confirm that this is the behaviour we want?
https://github.com/Expensify/App/assets/77237602/5f5d3828-f308-4754-a32a-d653c17ee404

**Comment by trjExpensify** [comment] 2023-11-08 16:52
I think we want it to work exactly as it does in the case where you are still a member of the room and try and use a dupe name: 


https://github.com/Expensify/App/assets/16232057/8ecfd47e-5f78-4b76-a5e2-bbe4c55bf4e4

**Comment by esh-g** [comment] 2023-11-08 17:07
@trjExpensify Does the attached video look alright?

https://github.com/Expensify/App/assets/77237602/885b666e-2358-4a83-aaf9-e77d55437ea6

If this is the behaviour we want, we need to edit the backend failure response to be something like this (@pecanoro) :
```js
{
      onyxMethod: Onyx.METHOD.MERGE,
      key: ONYXKEYS.FORMS.NEW_ROOM_FORM,
      value: {
          errorFields: {
              roomName: ErrorUtils.getMicroSecondOnyxError("Room already exists or some other error")
          }
      },
  },
```

**Comment by pecanoro** [comment] 2023-11-08 17:34
Sure! @jasperhuangg Can you confirm so I can make the changes on my PR?

**Comment by esh-g** [comment] 2023-11-08 17:38
I think it would be best to wait and see the result of [this discussion in slack](https://expensify.slack.com/archives/C01GTK53T8Q/p1699462796464829) before making any changes though...

**Comment by esh-g** [comment] 2023-11-08 18:21
# Proposal

## What change should be made on front-end?
1. We should add the `isLoading` state for the form by in the optimistic data of `Report.addPolicyReport` here:
https://github.com/Expensify/App/blob/24f306c9575212c4c4557a2ce5f102ce97c99a41/src/libs/actions/Report.js#L1572
```js
{
    onyxMethod: Onyx.METHOD.MERGE,
    key: ONYXKEYS.FORMS.NEW_ROOM_FORM,
    value: {isLoading: true},
},
```

2. Set `isLoading` to `false` in `successData` and `failureData`.

3. Remove the dismiss modal call here:
https://github.com/Expensify/App/blob/24f306c9575212c4c4557a2ce5f102ce97c99a41/src/libs/actions/Report.js#L1634

4. We need to create a function `clearNewRoomFormErrorAndSubmit` to clear the error when opening the form:
```js
function clearNewRoomFormErrorAndSubmit() {
    Onyx.set(ONYXKEYS.FORMS.NEW_ROOM_FORM, {
        isLoading: false,
        errorFields: {},
    });
}
```

5. In the `WorkspaceNewRoomPage`, we can add a use effect to call the above function:
```js
useEffect(() => {
    clearNewRoomFormErrorAndSubmit();
}, []);
```

6. In the `WorkspaceNewRoomPage` we need to add the `formData` key in the `withOnyx` HOC:
```js
formData: {
    key: ONYXKEYS.FORMS.NEW_ROOM_FORM
}
```

7. We need to add a `useEffect` to dismiss the modal if there are no errors:
```js
useEffect(() => {
    if (wasLoading && !props.formData.isLoading && _.isEmpty(props.formData.errorFields)) {
        Navigation.dismissModal();
    }
}, [props.formData]);
```
```js
const wasLoading = usePrevious(props.formData.isLoading);
```

**Additional Change**
With the above changes, on successful room creation, we are not able to be redirected to the created room because the navigation step has been moved from `Report.js` to the `WorkspaceNewRoomPage` so, to rectify that, instead of building the `optimistic` policy room report in the `addPolicyReport` function,  we can create the `optimistic` report in the `submit` function here itself:
https://github.com/Expensify/App/blob/49f730f534703e119bd01605960b6a113e99b07c/src/pages/workspace/WorkspaceNewRoomPage.js#L96-L99
And then pass the optimistic report to the `addPolicyReport` function. This way, we can store `reportID` of the newly created policy room via component state and redirect to it instead of just dismissing modal (in step 7)

**Comment by jasperhuangg** [comment] 2023-11-09 21:03
> Sure! @jasperhuangg Can you confirm so I can make the changes on my PR?

I think the error you included in your PR is enough, I think `Room already exists or some other error` is a bit strange. In the future if we think we need to change the error message again, I can create a followup.

**Comment by esh-g** [comment] 2023-11-10 02:01
@jasperhuangg That is not the error message from backend... I just put it as a placeholder for the actual error message to give you an idea of how it would look. Moreover, the question is whether we set form.errors or form.errorFields.roomName

**Comment by trjExpensify** [comment] 2023-11-13 14:01
Looks like we're making progress here. One outstanding question for @jasperhuangg directly above!

**Comment by jasperhuangg** [comment] 2023-11-15 17:02
@pecanoro recently put up a PR that should set those errors in the back-end, thanks!

It seems like that PR was recently deployed to staging @esh-g

**Comment by esh-g** [comment] 2023-11-21 18:44
@jasperhuangg I have tested [my proposal](https://github.com/Expensify/App/issues/21747#issuecomment-1802421014) with the backend change that was done and it works just as expected.
https://github.com/Expensify/App/assets/77237602/e08e9480-5ac8-4a55-b8a3-78c552798990

Feel free to assign me and I can raise a PR!

**Comment by jasperhuangg** [comment] 2023-11-21 19:57
@esh-g awesome, let's move forward with your proposal! thanks :)

**Comment by esh-g** [comment] 2023-11-21 21:26
PR is here: https://github.com/Expensify/App/pull/31655

cc @jasperhuangg @allroundexperts

**Comment by esh-g** [comment] 2023-12-21 17:33
@trjExpensify @jasperhuangg Could we get the payment for this processed before the holidays? Thanks!
Seems like since this is still marked as hold so the payment automation date didn't happen...

**Comment by trjExpensify** [comment] 2023-12-21 18:15
Confirming payments: 

- $1000 to @esh-g for the fix
- $1000 to @allroundexperts for the C+ review
- $50 to @priya-zha  for the bug report (predates the programme changes). 

Settled up with @esh-g and @priya-zha. @allroundexperts you can request. Closing!

**Closed by trjExpensify** 2023-12-21 18:15 UTC
Labels: Reviewing, External, Engineering, Weekly, Bug

**Comment by JmillsExpensify** [comment] 2024-01-24 23:48
$1,000 payment to @allroundexperts based on comment above.
