### ISSUE TITLE
 DEV - Console Error On Opening New Group From Green Button

### ISSUE THREAD

**Issue by kavimuru** [Expensify/App#13450] opened 2022-12-08 23:36 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Actions Performed:

1. Open App
2. Click On Green Plus Button
3. Select New Group

## Expected Result:
Console Error Shouldn’t Appear

## Actual Result:
Console Error Appears

## Workaround:
unknown

## Platform:

Where is this issue occurring?

- iOS

**Version Number:** 1.2.36-2
**Reproducible in staging?:** Dev bug
**Reproducible in production?:** Dev bug
**Email or phone of affected tester (no customers):** 
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** 

https://user-images.githubusercontent.com/43996225/206589298-dfd4853b-b9ce-4202-9d36-c1aebaf9ccee.mov

**Expensify/Expensify Issue URL:** 
**Issue reported by:** @syedsaroshfarrukhdot 
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1670464750367709

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by syedsaroshfarrukhdot** [comment] 2022-12-08 23:39
Proposal :-

We need to change reports: PropTypes.objectOf(reportPropTypes).isRequired in  NewChatPage.js to reports: PropTypes.shape({
        reportPropTypes : reportPropTypes,
    }).isRequired,

After Fix :-

https://user-images.githubusercontent.com/81307212/206589480-320566bb-e90f-4979-ab52-46177ac9aa00.mov

**Comment by sonialiap** [comment] 2022-12-12 15:03
I'm not able to reproduce this on `iPhone 14 v1.2.36`. Browserstack does not have an iOS version of `1.2.36-2` only Android.

Closing because I cannot reproduce. Please reopen if you believe this is still an issue

**Closed by sonialiap** 2022-12-12 15:03 UTC
Labels: Daily, Needs Reproduction, Overdue, Bug

**Comment by aneequeahmad** [comment] 2022-12-13 21:04
@sonialiap, This is also reproducible on Web app dev `main` branch.

- It is also reproducible on latest `v1.2.38-5`.

- I have reported this bug on August 26th [here](https://expensify.slack.com/archives/C01GTK53T8Q/p1661461669649729) and Nov 9th [here](https://expensify.slack.com/archives/C01GTK53T8Q/p1667960050528709) and on December 3rd [here](https://expensify.slack.com/archives/C049HHMV9SM/p1670042979231039). IMO i'm eligible for the reporting bonus.

Here are the reproduction steps.
**Action performed:**

1- Open web app in loggedIn state.
2- Click on settings > workspaces.
3- Click on any workspace already created(if it doesn’t exist create a new workspace and repeat the steps from 1 to 3)

**Expected Result:**

 No console error.

**Actual Result:** 

Console error: Failed prop type: Invalid prop `reports.report_1926234218899039.reportID` of type `number` supplied to `WorkspaceInitialPage`, expected `string` at WorkspaceInitialPage.
 
 This error exist on these files as well.

- MainDrawerNavigatior.js, 
- NewChatPage.js, 
- SearchPage.js, 
- SearchbarLinks.js, 
- IOUParticipantsRequest.js, 
- IOUParticipantsSplit.js, 
- WorkspaceInitialPage.js, 
- WorkspaceNewRoomPage.js

**Comment by aneequeahmad** [comment] 2022-12-13 21:14
### **PROPOSAL**

**Problem:** 

Some of the file mentioned [here](https://github.com/Expensify/App/issues/13450#:~:text=string%20at%20WorkspaceInitialPage.-,This%20error%20exist%20on%20these%20files%20as%20well.,WorkspaceNewRoomPage.js,-Write) have Proptypes defined as `reports: PropTypes.objectOf(reportPropTypes)` but the reportPropTypes already defined as `export default PropTypes.shape({…..})`


**Solution:**

This line in each of the [files](https://github.com/Expensify/App/issues/13450#:~:text=string%20at%20WorkspaceInitialPage.-,This%20error%20exist%20on%20these%20files%20as%20well.,WorkspaceNewRoomPage.js,-Write) 
https://github.com/Expensify/App/blob/41785c751ca8b833a6a375dd55f5aa64a3c9347c/src/libs/Navigation/AppNavigator/MainDrawerNavigator.js#L20

 should be `reports: reportPropTypes` as `reportPropTypes` is already defined as `export default PropTypes.shape({…..})` in file `pages/reportPropTypes`.
