### ISSUE TITLE
[$250] Advanced approval - Unable to add additional approver

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#48095] opened 2024-08-27 14:31 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 9.0.25-1
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**If this was caught during regression testing, add the test name, ID and link from TestRail:** N/A
**Email or phone of affected tester (no customers):** applausetester+kh050806@applause.expensifail.com
**Issue reported by:** Applause - Internal Team

## Action Performed:
1. Go to staging.new.expensify.com
2. Go to Workspace settings > Workflows
3. Click on the default workflow
4. Click Additional approver
5. Add another member or admin as the second approver
6. Click Save

## Expected Result:
Second approver will be assigned successfully

## Actual Result:
Second approver disappears from the default workflow. Unable to add a second approver

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [x] Android: mWeb Chrome
- [x] iOS: Native
- [x] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details> 

https://github.com/user-attachments/assets/1fe21833-8fba-46bb-ad29-534cf7afd89e

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~013521c3f7e7ed658f</li>
        <li>Upwork Job ID: 1828507692431612427</li>
        <li>Last Price Increase: 2024-08-27</li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @allroundexperts</details>

**Comment by lanitochka17** [comment] 2024-08-27 14:32
We think that this bug might be related to #wave-control

**Comment by FitseTLT** [comment] 2024-08-27 16:09
## Proposal

### Please re-state the problem that we are trying to solve in this issue.

Advanced approval - Unable to add additional approver

### What is the root cause of that problem?
We are showing Additional approver menu item wheter the approval workflow is default or not
https://github.com/Expensify/App/blob/0fd1de0f279fffba0129484801942c3bddb148da/src/pages/workspace/workflows/approvals/ApprovalWorkflowEditor.tsx#L153
But the BE is not allowing additional approvals for default workflow
### What changes do you think we should make in order to solve the problem?

Only display the additional approver menu if it is not default
```
{!approvalWorkflow.isDefault && (
                    <MenuItemWithTopDescription
                        description={translate('workflowsCreateApprovalsPage.additionalApprover')}
```
### What alternative solutions did you explore? (Optional)

**Comment by adelekennedy** [comment] 2024-08-27 18:59
https://github.com/user-attachments/assets/13059eab-3eff-44a9-8dd9-c3e60aca46a7
I'm getting the same on v9.0.25-8

**Comment by mkzie2** [comment] 2024-08-28 04:16
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
Second approver disappears from the default workflow. Unable to add a second approver

### What is the root cause of that problem?
When we only have one workflow, the workspace's `approvalMode` is `BASIC`, and adding the additional approval isn't successful.

If we add another workflow and then add additional approval for the default workflow, this bug doesn't happen.


### What changes do you think we should make in order to solve the problem?
We should hide the additional approver section in `ApprovalWorkflowEditor` and display the not found page on `WorkspaceWorkflowsApprovalsApproverPage` if the `approvalMode` is not `ADVANCE`

- Hide the additional approver section in `ApprovalWorkflowEditor`

```
{policy?.approvalMode === CONST.POLICY.APPROVAL_MODE.ADVANCED && (
    <MenuItemWithTopDescription
        description={translate('workflowsCreateApprovalsPage.additionalApprover')}
        onPress={addAdditionalApprover}
        shouldShowRightIcon
        wrapperStyle={styles.sectionMenuItemTopDescription}
        errorText={approvalWorkflow?.errors?.additionalApprover ? translate(approvalWorkflow.errors.additionalApprover) : undefined}
        brickRoadIndicator={approvalWorkflow?.errors?.additionalApprover ? CONST.BRICK_ROAD_INDICATOR_STATUS.ERROR : undefined}
    />
)}
```
https://github.com/Expensify/App/blob/071f11ce1012db7d07eb750d74f58b552eba6144/src/pages/workspace/workflows/approvals/ApprovalWorkflowEditor.tsx#L158-L160

- display the not found page on `WorkspaceWorkflowsApprovalsApproverPage`

```
const shouldShowNotFoundView =
    (isEmptyObject(policy) && !isLoadingReportData) ||
    !PolicyUtils.isPolicyAdmin(policy) ||
    PolicyUtils.isPendingDeletePolicy(policy) ||
    (policy?.approvalMode !== CONST.POLICY.APPROVAL_MODE.ADVANCED);
```
https://github.com/Expensify/App/blob/071f11ce1012db7d07eb750d74f58b552eba6144/src/pages/workspace/workflows/approvals/WorkspaceWorkflowsApprovalsApproverPage.tsx#L83

### What alternative solutions did you explore? (Optional)
NA

**Comment by mkzie2** [comment] 2024-08-29 03:09
Updated [proposal](https://github.com/Expensify/App/issues/48095#issuecomment-2314206092)
Update the condition to show the not found page.

**Comment by blazejkustra** [comment] 2024-08-29 13:20
We think it is a backend issue, related to https://github.com/Expensify/App/issues/48027 - let's hold for now.

**Comment by tgolen** [comment] 2024-08-29 17:06
This is going to be fixed with the same backend fix I am making for https://github.com/Expensify/App/issues/48027 so I am going to assign this to me and take it internal. I don't think making and frontend changes will be necessary for this (but let's analyze it again once the backend fix is out).

**Comment by tgolen** [comment] 2024-08-30 15:52
See daily update [here](https://github.com/Expensify/App/issues/48027#issuecomment-2321717714).

**Comment by blazejkustra** [comment] 2024-09-04 07:38
It should be fixed now 👌 Let's verify and close this issue, thank you!

**Comment by adelekennedy** [comment] 2024-09-04 16:02
just tested and this is resolved! No payment due here, closing

**Closed by adelekennedy** 2024-09-04 16:02 UTC
Labels: Reviewing, Daily, Internal, Bug
