### ISSUE TITLE
[HOLD for payment 2023-10-10] [$500] Settings - Profile - User is able to delete default contact method, result in error

### ISSUE THREAD

**Issue by izarutskaya** [Expensify/App#26773] opened 2023-09-05 12:54 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Login with any account in 2 tabs.
2. From first tab, open settings => profile => contact methods, choose the secondary contact method, press Delete.
3. From second tab, open settings => profile => contact methods, choose the secondary contact method,  press `Set As Default`.
4. From the first tab, press Delete.
5. Observer the contact method field.

## Expected Result:
User shouldn't be able to delete default contact method.

## Actual Result:
User is able to delete default contact method, result in error

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [x] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** v1.3.63-0

**Reproducible in staging?:** Y

**Reproducible in production?:** Y

**If this was caught during regression testing, add the test name, ID and link from TestRail:**

**Email or phone of affected tester (no customers):**

**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/115492554/80a79d67-da11-45c9-bfca-15570bb94b3c

https://github.com/Expensify/App/assets/115492554/6542239b-16f6-4f14-b47b-a32495e9d421

**Expensify/Expensify Issue URL:**

**Issue reported by:** @hungvu193

**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1693283217118959

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~011a89cd5b6cb92262</li>
        <li>Upwork Job ID: 1699163308725714944</li>
        <li>Last Price Increase: 2023-09-12</li>
<li>Automatic offers: </li>
<ul>
<li>Ollyws | Reviewer | 26653028</li>
<li>hungvu193 | Reporter | 26653029</li>
</ul></li>
    </ul>
</details>

**Comment by izarutskaya** [comment] 2023-09-05 12:54
## Proposal from @hungvv193
### Please re-state the problem that we are trying to solve in this issue.
User is able to delete default contact method, result in error
### What is the root cause of that problem?
In current `ContactMethodDetailsPage`, we don't a have logic to hide the delete modal or prevent user from deleting the current contact method even it's default contact methods once modal is opened.
### What changes do you think we should make in order to solve the problem?
Solution 1:
Add an `useEffect` inside `ContactMethodDetailsPage`, if current contact method is default contact method and Confirm Modal is opened, we should hide the modal.
Solution 2:
Disabled the `Yes, continue` button if current contact method is default contact method.
### What alternative solutions did you explore? (Optional)
N/A

**Comment by s-alves10** [comment] 2023-09-05 13:13
I think this issue is related to both backend and frontend
The backend should return error when a user tries to delete his default contact method. This is possible for sure
The frontend should show error message like "You can't delete your default contact method" when press `Yes` button

**Comment by lukemorawski** [comment] 2023-09-13 10:31
this is Lucas from Callstack. Happy to work on that!

**Comment by abekkala** [comment] 2023-09-13 13:21
@Ollyws I didn't see any movement on this since last week so I pulled in someone to get this one fixed and finished.

**Comment by lukemorawski** [comment] 2023-09-14 15:16
@abekkala Can't reproduce the bug anymore. Look like there might some changes on the BE. The state of the contact list is now synchronised using WS/Onyx. After deleting the contact method from step 1., it disappears on the second device. This is actually what it was supposed to be :) Please check.

**Comment by izarutskaya** [comment] 2023-09-15 20:35
@lukemorawski I can still reproduce it.
Build v1.3.70-5

https://github.com/Expensify/App/assets/115492554/f7eac272-3e76-4d56-a24d-d86c1a5aa8ff

**Comment by lukemorawski** [comment] 2023-09-18 09:02
@izarutskaya ok, will have a look again in moment :)

**Comment by lukemorawski** [comment] 2023-09-19 09:04
Think I got it working. Preparing the PR today.

**Comment by abekkala** [comment] 2023-10-04 19:30
### PAYMENTS FOR OCT 10

- @hungvu193 (Reporter) [$50]
- @lukemorawski does not require payment (Callstack)
- @Ollyws (Reviewer) [$500] no bonus, please complete checklist above

**Comment by abekkala** [comment] 2023-10-10 14:44
@hungvu193 payment made [$50] and contract ended - thank you! 🎉

**Comment by abekkala** [comment] 2023-10-10 14:44
@Ollyws payment made [$500] and contract ended - thank you! 🎉

**Comment by abekkala** [comment] 2023-10-10 14:45
closing

**Closed by abekkala** 2023-10-10 14:45 UTC
Labels: External, Daily, Awaiting Payment, Bug
