### ISSUE TITLE
Workspace - Workspace avatar is different when viewed in full screen mode

### ISSUE THREAD

**Issue by izarutskaya** [Expensify/App#41387] opened 2024-05-01 07:31 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.69-0
**Reproducible in staging?:** Y
**Reproducible in production?:** N
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Issue reported by:** Applause-Internal team

## Action Performed:
1. Go to staging.new.expensify.com
2. Go to Account settings > Workspaces.
3. Create a new workspace.
4. Go to workspace chat.
5. Click on the chat header.
6. Click on the workspace avatar.

## Expected Result:
Workspace avatar will be the same when viewed in full screen mode.

## Actual Result:
Workspace avatar is different when viewed in full screen mode.

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [x] Android: mWeb Chrome
- [x] iOS: Native
- [x] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

https://github.com/Expensify/App/assets/115492554/b8abe80c-59d1-4262-8dc3-ea606bcb0ee0

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by izarutskaya** [comment] 2024-05-01 07:32
@sakluger I haven't added the External label as I wasn't 100% sure about this issue. Please take a look and add the label if you agree it's a bug and can be handled by external contributors.

**Comment by izarutskaya** [comment] 2024-05-01 07:32
We think this issue might be related to the #collect project.

**Comment by cristipaval** [comment] 2024-05-01 11:39
Assigning @grgia and @rushatgabhane as the reviewers of the offending PRs

**Comment by grgia** [comment] 2024-05-01 11:40
Another regression @nkdengineer @rushatgabhane https://github.com/Expensify/App/pull/39637

**Comment by grgia** [comment] 2024-05-01 11:41
This one actually isnt a regression, closing

**Comment by grgia** [comment] 2024-05-01 11:47
Not a regression, it's the same on prod @dragnoir

**Comment by grgia** [comment] 2024-05-01 11:48
@dragnoir my bad I looked at the wrong video 😂 

@nkdengineer this should be fixed as a follow up to your PR cc @rushatgabhane

**Comment by sakluger** [comment] 2024-05-02 16:26
Commenting for when I come back to review later - Because this is a regression from https://github.com/Expensify/App/pull/39637, there will be no additional payment required.

**Comment by sakluger** [comment] 2024-05-07 21:35
This is being fixed in this PR: https://github.com/Expensify/App/pull/41485

**Comment by sakluger** [comment] 2024-05-13 09:26
The PR is still in review.

**Comment by sakluger** [comment] 2024-05-15 22:49
PR was merged! Not deployed yet.

**Comment by sakluger** [comment] 2024-05-16 21:06
@puneetlath assigning you to help watch this issue while I'm OOO through May 31. Could you please handle payment if needed? The issue was just merged, so it likely will need to be paid out before I return.

I'll for some reason the issue is still open when I return, I'll take it back over.

**Comment by rushatgabhane** [comment] 2024-05-22 08:09
PR merged last week but not on staging yet

**Comment by sakluger** [comment] 2024-06-04 00:00
Removed @puneetlath since I'm back from OOO.

Sounds like we still just need to wait for the PR to be deployed. May be a bit longer with the current freeze.

**Comment by sakluger** [comment] 2024-06-12 18:57
PR was deployed to prod! Closing.

**Closed by sakluger** 2024-06-12 18:57 UTC
Labels: Engineering, Weekly, Overdue, Bug
