### ISSUE TITLE
[HOLD for payment 2022-05-20] [$500] when selecting multiple lines on a message, sometimes the lines that aren't the first aren't highlighted

### ISSUE THREAD

**Issue by mvtglobally** [Expensify/App#8421] opened 2022-04-01 03:09 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Send to someone text below
There are a bunch of wizard type tools online you can use to create the SPF and DMARC records:
https://www.spf-record.com/generator
https://dmarcian.com/dmarc-record-wizard/
2. Highlight to Copy 

## Expected Result:
it should highlight all copied text 

## Actual Result:
It only highlights the first line 

## Workaround:
unknown 

## Platform:

Where is this issue occurring?

- Web
- Desktop App

**Version Number:** 1.1.49-0
**Reproducible in staging?:** Y 
**Reproducible in production?:** Y 
**Email or phone of affected tester (no customers):** 
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation 
![image - 2022-03-31T230719 017](https://user-images.githubusercontent.com/43995119/161187632-22e83551-f62a-4bf2-aa98-08d11894b77b.png)

**Expensify/Expensify Issue URL:** 
**Issue reported by:** @cead22 
**Slack conversation:** https://expensify.slack.com/archives/C01GTK53T8Q/p1648079660103259

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by deetergp** [comment] 2022-04-04 18:41
This is something a contributor could work on.

**Comment by bfitzexpensify** [comment] 2022-04-05 05:01
upwork [posting](https://www.upwork.com/jobs/~01b625ea8e603fbe10)

**Comment by jayeshmangwani** [comment] 2022-04-06 19:31
https://github.com/Expensify/App/blob/0d5285c39d491da1517240447df43a8034058c7b/src/pages/home/report/ReportActionItemFragment.js#L103-L105

if we replace comment with div tag in RenderHTML, then this issue is not happening, I am not sure if we have any reason for using comment tag here.

https://user-images.githubusercontent.com/35371050/162053864-22749069-53b0-47a4-9da6-c4f504aca3e6.mov


above video is reference when we have used div tag

**Comment by Santhosh-Sellavel** [comment] 2022-04-07 18:19
@jayeshmangwani 
I would really care to know why the `<comment>` tag is causing the issue.

Also, refer to the GH Post, links were underlined.
<img width="888" alt="Screenshot 2022-04-07 at 11 47 15 PM" src="https://user-images.githubusercontent.com/85645967/162270173-c9558b7b-8643-4f2c-b44c-85bae72d86bb.png">

And In your video, the underline styles are missing for the links.

**Comment by bfitzexpensify** [comment] 2022-04-14 03:02
doubled price to $500

**Comment by mountiny** [comment] 2022-04-14 20:23
I am going ooo for 5 weeks so I am re-assigning some CME issues assigned to me. This one still awaits a proposal! Thank you for your help @deetergp!

**Comment by mollfpr** [comment] 2022-04-16 16:46
## Proposal

### **Why**
We use `AnchorRenderer > AnchorForCommentsOnly > BaseAnchorForCommentsOnly` to render anchor tag of html message and inside `BaseAnchorForCommentsOnly`, we use `PressableWithSecondaryInteraction` to wrap the anchor tag we want to render with `LongPressGestureHandler`. For some reason the anchor tag we want to render is has wrap with `user-select: none`. It's either from `react-native-gesture-handler` or `react-native-web` behaviour.
<img width="1211" alt="Screen Shot 2022-04-16 at 23 22 01" src="https://user-images.githubusercontent.com/25520267/163683329-eae29bd8-95a7-4195-a0c1-4fa5cbfdc1d6.png">

For regular text, is already have `user-select: text` style.
<img width="1216" alt="Screen Shot 2022-04-16 at 23 39 04" src="https://user-images.githubusercontent.com/25520267/163683682-f7248463-0ae7-4124-b60b-a4a728f9dc7e.png">


### **How**
The solution I suggest adding style `userSelect: 'text'` to `BaseHTMLEngineProvider` and `BaseAnchorForCommentsOnly`.

The reason I add the style in here `BaseHTMLEngineProvider` is to override the style `user-select: none` that come from `ReportActionItem` that return children wrapped with `PressableWithSecondaryInteraction`.

For this `BaseAnchorForCommentsOnly` I add to set the style to anchor tag itself.

**The full changes will be**
https://github.com/Expensify/App/blob/6c53be1ea7a022e8a5e788cc7e7efd62c4573474/src/components/HTMLEngineProvider/BaseHTMLEngineProvider.js#L39
```diff
- const defaultViewProps = {style: {alignItems: 'flex-start'}};
+ const defaultViewProps = {style: {alignItems: 'flex-start', userSelect: 'text'}};
```
https://github.com/Expensify/App/blob/6c53be1ea7a022e8a5e788cc7e7efd62c4573474/src/components/AnchorForCommentsOnly/BaseAnchorForCommentsOnly/index.js#L75
```diff
-                            style={StyleSheet.flatten(this.props.style)}
+                            style={StyleSheet.flatten({...this.props.style, 'userSelect': 'text'})}
```

### **Result**

#### Web

https://user-images.githubusercontent.com/25520267/163683864-c0f5e595-e2d8-42c3-bc68-aa288dcffd28.mov

#### Desktop
https://user-images.githubusercontent.com/25520267/163683882-6811503d-0855-4855-a233-553c6689f7fd.mov

**Comment by mountiny** [comment] 2022-04-16 18:08
@mollfpr Could you confirm everything works well on mobile with longpress on the link? No weird text selection behaviour?

**Comment by mollfpr** [comment] 2022-04-16 20:18
For mobile, I think everything should be fine since the updated style for `BaseAnchorForCommentsOnly` is not targeting the native platform.

https://user-images.githubusercontent.com/25520267/163689866-eca05376-ef07-4689-892a-308d9fc40ed5.mov

---

For mWeb we have an issue.

https://user-images.githubusercontent.com/25520267/163689956-74b6c12b-3d16-449a-9a83-ded7942bee77.mov

In this case we can add a condition when to applied the styles.
https://github.com/Expensify/App/blob/6c53be1ea7a022e8a5e788cc7e7efd62c4573474/src/components/AnchorForCommentsOnly/BaseAnchorForCommentsOnly/index.js#L75
```diff
+        const styleUserSelect = canUseTouchScreen() || this.props.isSmallScreenWidth ? {} : {userSelect: 'text'};

-                            style={StyleSheet.flatten(this.props.style)}
+                            style={StyleSheet.flatten({...this.props.style, ...styleUserSelect})}
```

https://user-images.githubusercontent.com/25520267/163690138-08bfa25b-9e85-4506-b9c5-935997843523.mp4


cc @mountiny

**Comment by mountiny** [comment] 2022-04-16 20:24
Thanks for the update @mollfpr, I will let Santosh and Scott handle this issue 🙌

**Comment by deetergp** [comment] 2022-04-19 22:00
@mollfpr's proposal looks pretty straight forward. Let's go with that 👍

**Comment by mollfpr** [comment] 2022-04-22 00:42
Hi @deetergp should I wait @Santhosh-Sellavel review? Or I can raise the PR now?

**Comment by Santhosh-Sellavel** [comment] 2022-04-22 01:30
@deetergp or @bfitzexpensify 

LGTM as well!

Let's assign @mollfpr this issue.

@mollfpr feel free to Raise PR!

**Comment by mollfpr** [comment] 2022-04-23 08:13
PR raise!

cc @deetergp @Santhosh-Sellavel

**Comment by bfitzexpensify** [comment] 2022-05-19 00:35
Hey @mollfpr - no regressions yet, so preparing to pay this one out on the 20th. Can you apply to the Upwork post [here](https://www.upwork.com/jobs/~018d0cfacbcb843fbc) please? Thanks!

**Comment by bfitzexpensify** [comment] 2022-05-20 07:30
I've tried to pay this out multiple times today with no success - I just get an Upwork growl saying an error occurred. 

Reassigning this to someone in America.

**Comment by laurenreidexpensify** [comment] 2022-05-20 13:31
@mollfpr @Santhosh-Sellavel Upwork was being weird with the payment - can you please accept the most recent offer I sent over and we can get this paid out. 

(somehow there are two postings live on the system 🙃)

**Comment by mollfpr** [comment] 2022-05-20 13:44
@laurenreidexpensify accepted!

**Comment by laurenreidexpensify** [comment] 2022-05-20 14:15
great @mollfpr I issued you payment now as a $500 bonus, as for some reason it was coming up as an hourly rate option, but we pay by project.

**Comment by Santhosh-Sellavel** [comment] 2022-05-20 16:36
Yes, there are two offers for this job, declined one of them as a duplicate!

**Comment by laurenreidexpensify** [comment] 2022-05-23 09:27
@Santhosh-Sellavel sorry for delay, payment issued 👍🏽

**Closed by laurenreidexpensify** 2022-05-23 09:27 UTC
Labels: Reviewing, Exported, External, Engineering, Daily, Awaiting Payment
