### ISSUE TITLE
[$1000] Thread image not displaying in preview,replied image showing instead of thread image on preview

### ISSUE THREAD

**Issue by kavimuru** [Expensify/App#19351] opened 2023-05-20 19:20 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:

1. Open a chat
2. Send an image to the user
3. Click on "Reply in thread" after sending the image
4. Click to preview the image.
5. Reply with another image under this thread
6. Open the thread image to preview

## Expected Result:
The thread image should be displayed in the preview.
## Actual Result:
The thread image is not displaying in the preview, the replied image is shown instead.
## Workaround:
Can the user still use Expensify without this being fixed? Have you informed them of the workaround?

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android / native
- [x] Android / Chrome
- [x] iOS / native
- [x] iOS / Safari
- [x] MacOS / Chrome / Safari
- [x] MacOS / Desktop

**Version Number:** 1.3.16.5
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/43996225/7577c453-a3e9-4102-8db1-60d36307ec8b

https://github.com/Expensify/App/assets/43996225/32150c56-03a2-49ac-9cc8-7856ee9176b7

**Expensify/Expensify Issue URL:**
**Issue reported by:** @ayazhussain79 
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1684362156850139

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~0197381e0514019279</li>
        <li>Upwork Job ID: 1660728167585943552</li>
        <li>Last Price Increase: 2023-07-26</li>
    </ul>
</details>

**Comment by greg-schroeder** [comment] 2023-05-22 18:31
Reviewing

**Comment by greg-schroeder** [comment] 2023-05-22 19:23
@allroundexperts thanks for the context! I'd say go ahead and apply for each related issue accordingly if you have a fix that works.

**Comment by dukenv0307** [comment] 2023-05-23 08:39
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
Image that is first message of the thread is not displaying in preview
### What is the root cause of that problem?
In `ReportScreen`, first message of thread is parentReportAction, but in preview it get all action of childReportAction that doesn't contain first message of thread. So that in preview, first message of thread is not displayed
https://github.com/Expensify/App/blob/6946beb6219c87df11cc8f81bb6c31ed8e732373/src/components/AttachmentCarousel/index.js#L167
### What changes do you think we should make in order to solve the problem?
If we apply @allroundexperts proposal, it will display all attachment of parentReport and I think it's not expected.
So that, we should get all actions of the report and get the parentReportAction of this report that is first message if it is a thread. 
Here is my suggestion to do it: 
1. In `AttachmentModal`, subscribe `report` with `reportID` props from ONYX. Use `ReportUtils.isThread(this.props.report)` to check this report is thread or not. Then, pass `parentReportID` and `report` props into `AttachmentCarousel`
https://github.com/Expensify/App/blob/6946beb6219c87df11cc8f81bb6c31ed8e732373/src/components/AttachmentModal.js#L282
2. In `AttachmentCarousel `, add two props are `parentReportID` and `report` and subcribe `parentReportActions` with `parentReportID` from ONYX.
3. In `makeInitialState` function, we should check if parentReportID is not empty that means the report is a thread, we will add parentReportAction that is first message of the thread to `actions`:
```
if (this.props.parentReportID) {
    actions = [...actions, this.props.parentReportActions[`${this.props.report.parentReportActionID}`]]
}
```
https://github.com/Expensify/App/blob/6946beb6219c87df11cc8f81bb6c31ed8e732373/src/components/AttachmentCarousel/index.js#L167
### What alternative solutions did you explore? (Optional)

**Comment by greg-schroeder** [comment] 2023-05-24 20:34
>@greg-schroeder @Gonals What's the expected behaviour here? Should the left and right arrows appear in the carousel when the thread title image is opened?

I'm not actually sure to be honest - can you confirm @Gonals?

**Comment by strepanier03** [comment] 2023-05-24 23:46
@Gonals @0xmiroslav - Can you both check these other GH and see if you agree that all three GHs have the same root cause?

Context [here](https://expensify.slack.com/archives/C01SKUP7QR0/p1684782807958219).

**Comment by greg-schroeder** [comment] 2023-05-29 13:18
Bump @Gonals @0xmiroslav on the above comment from Sheena!

**Comment by dukenv0307** [comment] 2023-05-29 13:36
@Gonals  @0xmiroslav This issue has the same root cause with other issues that are mentioned above but If we apply proposal of @allroundexperts, in preview it will display all attachment of parent report like this video

[Screencast from 29-05-2023 20:34:37.webm](https://github.com/Expensify/App/assets/129500732/fc08a801-2498-48f5-b220-5a51f1a0352d)

**Comment by Gonals** [comment] 2023-06-02 09:51
Seems like @dukenv0307 is right. 
I think the identified root cause is correct, but we need to refine the fix to avoid unwanted behavior

**Comment by Gonals** [comment] 2023-06-02 10:16
@0xmiroslav, can you take a look at the proposed solutions? I'll try to review them on Monday

**Comment by greg-schroeder** [comment] 2023-06-05 15:23
>I think we should hold this until https://github.com/Expensify/App/issues/19352, https://github.com/Expensify/App/issues/19348 are resolved. The solution implemented for this issue will depend on how previous mentioned issues are fixed.

If that's true then we should hold, otherwise we're just going to muddy the waters

**Comment by greg-schroeder** [comment] 2023-06-13 16:16
One of those issues was closed, we're just holding for #19348 now

**Comment by greg-schroeder** [comment] 2023-06-17 00:00
#19348 is closed, but we didn't fix it directly - asked in the related thread about what to do with this issue: https://expensify.slack.com/archives/C01GTK53T8Q/p1686960033027559?thread_ts=1686259969.958099&cid=C01GTK53T8Q

**Comment by greg-schroeder** [comment] 2023-06-20 19:19
bumped thread

**Comment by chiragsalian** [comment] 2023-06-22 18:02
My two cents:
1. This GH issue does not need to be on HOLD for [#19352](https://github.com/Expensify/App/issues/19352), or [#19348](https://github.com/Expensify/App/issues/19348).
2. But it should be on HOLD for https://github.com/Expensify/App/issues/18451 only because the carousel logic is changing and I want to avoid duplicate work since there might be overlap.
3. I like @dukenv0307 solution i.e., if its a thread then add the parentAction to the list of action.
4. My only suggestion would to remember to add it to the start and not the end i.e.,
```
actions = [this.props.parentReportActions[`${this.props.report.parentReportActionID}`], ...actions]
```
(unless the order is reversed for some reason)
5. But either way, IMO we should hold on https://github.com/Expensify/App/issues/18451 because its moving the attachment carousel to a route so i feel like we should accept proposals once that code is live since the applied solution could be different. (not just merged cause i want QA to confirm its stable on staging)

**Comment by greg-schroeder** [comment] 2023-06-23 01:39
Thanks @chiragsalian - held for #18451

**Comment by greg-schroeder** [comment] 2023-06-30 07:26
Still on hold

**Comment by greg-schroeder** [comment] 2023-07-08 00:26
Same as above

**Comment by greg-schroeder** [comment] 2023-07-11 02:58
Hold issue deployed, awaiting regression period

**Comment by greg-schroeder** [comment] 2023-07-18 09:46
Still holding for linked issue

**Comment by greg-schroeder** [comment] 2023-07-25 18:11
Okay #18451 is closed, removing hold. Per @chiragsalian's [comment](https://github.com/Expensify/App/issues/19351#issuecomment-1603097613), we're now at this step:

>But either way, IMO we should hold on https://github.com/Expensify/App/issues/18451 because its moving the attachment carousel to a route so i feel like we should accept proposals once that code is live since the applied solution could be different. (not just merged cause i want QA to confirm its stable on staging)

I think this is now essentially re-open to proposals now that the new logic is in place for the carousel

**Comment by greg-schroeder** [comment] 2023-07-25 18:29
All right lemme give it a test

**Comment by greg-schroeder** [comment] 2023-07-27 08:59
closing this as it was fixed!

**Closed by greg-schroeder** 2023-07-27 08:59 UTC
Labels: External, Daily, Help Wanted, Bug

**Comment by ayazhussain79** [comment] 2023-07-27 09:13
@greg-schroeder am i eligible for reporting bonus ?

**Comment by greg-schroeder** [comment] 2023-07-27 11:35
Sent you an offer for reporting @ayazhussain79

**Comment by ayazhussain79** [comment] 2023-07-27 11:50
@greg-schroeder offer accepted, Thank you
