### ISSUE TITLE
Category-"Add category" modal opens when clicking on a category with the name "new"

### ISSUE THREAD

**Issue by izarutskaya** [Expensify/App#43554] opened 2024-06-12 12:14 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** v1.4.82-0
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**If this was caught during regression testing, add the test name, ID and link from TestRail:** https://expensify.testrail.io/index.php?/runs/view/21740&group_by=cases:section_id&group_order=asc&group_id=292474
**Email or phone of affected tester (no customers):** berhanesarah.testing+hddfdfhfjjtt@gmail.com
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Issue reported by:** Applause-Internal team

## Action Performed:
1. Navigate to the workspace settings of the collect policy
2. Click on categories
3. Click on "+ Add category"
4. Enter "new" as a category name
5. Click on the added category in the categories list

## Expected Result:
User is able to see the details and options of the added category

## Actual Result:
The "Add category" modal opens when the category is clicked

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [x] Android: mWeb Chrome
- [ ] iOS: Native
- [x] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

https://github.com/Expensify/App/assets/115492554/ffcdd07e-6d63-4a96-b98b-d30c88324d3b

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by izarutskaya** [comment] 2024-06-12 12:14
We think this issue might be related to the #collect project.

**Comment by bernhardoj** [comment] 2024-06-12 12:49
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
The new category page opens when we click on a category named 'new'.

### What is the root cause of that problem?
When we click on a category named 'new', the route path will be `/settings/workspaces/{policyID}/categories/new` which is the same route as the new category page., so the new category page is shown.
https://github.com/Expensify/App/blob/05f85cb1a120dc25c22a648a4f9c85848372ba18/src/ROUTES.ts#L679-L682

### What changes do you think we should make in order to solve the problem?

Update the route for the individual category settings page. We can update it to
```
route: 'settings/workspaces/:policyID/categories/:categoryName/settings',
getRoute: (policyID: string, categoryName: string) => `settings/workspaces/${policyID}/categories/${encodeURIComponent(categoryName)}/settings` as const,
```

Or any route pattern that the team wants.

**Comment by joekaufmanexpensify** [comment] 2024-06-12 14:00
I can reproduce this, but this is a very niche bug. `New` doesn't really feel like a category to me in and of itself. I am very skeptical as to whether any customers would actually experience this.

**Comment by joekaufmanexpensify** [comment] 2024-06-12 14:00
Going to close this for now. This doesn't feel worth prioritizing now. Let's see if any actual customers experience this before deciding to fix.

**Closed by joekaufmanexpensify** 2024-06-12 14:00 UTC
Labels: Daily, Bug
