### ISSUE TITLE
[HOLD for payment 2024-04-15] HIGH: [Polish] [$500] Indented text does not appear correctly in the quotes

### ISSUE THREAD

**Issue by m-natarajan** [Expensify/App#38156] opened 2024-03-12 17:46 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.50-5
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** @quinthar 
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1710210821899179

## Action Performed:
1. open any report
2. Send the message with indent
  - No indent
        - Indented 4
3. Send the same with quotes markdown 
> - No indent
 >     - Indented 4

## Expected Result:
Should appear with indent inside  the quote

## Actual Result:
Appears without an indent

## Workaround:
unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

https://github.com/Expensify/App/assets/38435837/b2314eec-ea3c-416d-81a2-1e160dbefc36

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01496b08c675a55851</li>
        <li>Upwork Job ID: 1767894299145392128</li>
        <li>Last Price Increase: 2024-03-13</li>
<li>Automatic offers: </li>
<ul>
<li>s77rt | Contributor | 0</li>
<li>tienifr | Contributor | 0</li>
</ul></li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @laurenreidexpensify</details>

**Comment by hayes102** [comment] 2024-03-14 12:40
Actually i am not sure if this is a bug, seems like the current behaviour is the expected result in the tests written in this PR https://github.com/Expensify/expensify-common/pull/654/files

**Comment by nebiyuelias1** [comment] 2024-03-14 13:58
>       Actually i am not sure if this is a bug, seems like the current behaviour is the expected result in the tests written in this PR https://github.com/Expensify/expensify-common/pull/654/files
I says even in the comments.

**Comment by ikevin127** [comment] 2024-03-15 02:48
# Proposal

### Please re-state the problem that we are trying to solve in this issue

Indented text comment inside quotes is formatted without indentation once posted.

### What is the root cause of that problem?

Issue https://github.com/Expensify/App/issues/17504 and [`expensify-common #521`](https://github.com/Expensify/expensify-common/pull/521) PR introduced the [`formatTextForQuote`](https://github.com/Expensify/expensify-common/blob/dc8ea983f9e06308cdb9151a9cdfa82bd11502e1/lib/ExpensiMark.js#L837) function which uses `trim()` twice when formatting each quote line within the [`modifyTextForQuote`](https://github.com/Expensify/expensify-common/blob/dc8ea983f9e06308cdb9151a9cdfa82bd11502e1/lib/ExpensiMark.js#L775) function.

The issue with this is that regardless of the quote line containing indent (empty spaces) + text or just indentation without any text -> the trimming always removes the indentation.

### What changes do you think we should make in order to solve the problem?

> [!note]
> From the functionality implemented by the PR mentioned in RCA we can note that the `formatTextForQuote` function is using `trim()` twice:
> 1. [`row.substr(4).trim()`](https://github.com/Expensify/expensify-common/blob/dc8ea983f9e06308cdb9151a9cdfa82bd11502e1/lib/ExpensiMark.js#L840) to remove any empty spaces after `&gt;` (quote symbol) is removed.
> 2. [`textToFormat.trim()`](https://github.com/Expensify/expensify-common/blob/dc8ea983f9e06308cdb9151a9cdfa82bd11502e1/lib/ExpensiMark.js#L843) to remove leading / trailing line breaks ("\n") after map and `join('\n')` method.
>
> This means that it is paramount for us to make sure we keep the `trim()` for empty quote lines while we remove trimming for quote lines which are not empty, containing any of:
> - indent + text (our issue)
> - indent + text + indent
> - text

To implement this we require changes in two parts of the logic:

1. Within the `modifyTextForQuote` function where we check if the line contains quote [here](https://github.com/Expensify/expensify-common/blob/dc8ea983f9e06308cdb9151a9cdfa82bd11502e1/lib/ExpensiMark.js#L793-L796) -> we change the logic to:
```ts
if (Str.startsWith(textSplitted[i], '&gt;') && !insideCodefence) {
    // we remove "&gt;" (quote symbol) and trim
    const textContent = textSplitted[i].substring(4).trim();
    // if trimmed text content is empty return it, otherwise return original quote line
    const formattedLine = !textContent ? textContent : textSplitted[i];
    // append each quote line to textToFormat (similar to old code)
    textToFormat += `${formattedLine}\n`; 

    // textToFormat += `${textSplitted[i]}\n`; <- removed old code line
}
```
by doing this we keep trimming of the empty quote lines.

2. Within the `formatTextForQuote` function, we only remove the [first `trim()` instance](https://github.com/Expensify/expensify-common/blob/dc8ea983f9e06308cdb9151a9cdfa82bd11502e1/lib/ExpensiMark.js#L840). This ensures that for quote lines which are not empty (have text or indent + text) we keep the indentation.

> [!caution]
> It is important that we keep the [second `trim()`](https://github.com/Expensify/expensify-common/blob/dc8ea983f9e06308cdb9151a9cdfa82bd11502e1/lib/ExpensiMark.js#L842-L843) since that is not part of our issue's RCA and it was put there for a good reason: removal of leading / trailing line breaks ("\n") after map and `join('\n')` method.

### Videos

<details>
<summary>MacOS: Chrome / Safari</summary>

| Before | After |
| ------------- | ------------- |
| <video src="https://github.com/Expensify/App/assets/56457735/b0190467-de31-4e69-93c9-c17af4e79184"> | <video src="https://github.com/Expensify/App/assets/56457735/9e62685c-73dd-46cd-a338-7e2a283ab2d0"> |

</details>

**Comment by s77rt** [comment] 2024-03-17 16:41
Taking this as C+

**Comment by s77rt** [comment] 2024-03-17 17:39
@abzokhattab Thanks for the proposal. Your RCA is not correct. Disabling the [white spaces rules](https://github.com/Expensify/expensify-common/blob/dc8ea983f9e06308cdb9151a9cdfa82bd11502e1/lib/ExpensiMark.js#L466) is not something we want here and the way it's fixing this bug is only a side effect.

**Comment by s77rt** [comment] 2024-03-17 17:44
@tienifr Thanks for the proposal. Your RCA is correct. However the solution seems to have issues with nested quotes (and other failing tests) e.g. 

```
> > > Hello my
> > beautiful
> world
```

| Expected | Received |
|----------|----------|
|      <img width="251" alt="Screenshot 2024-03-17 at 6 42 51 PM" src="https://github.com/Expensify/App/assets/16493223/1603f923-21fa-42e8-8788-a24625690ec4">    |       <img width="251" alt="Screenshot 2024-03-17 at 6 42 58 PM" src="https://github.com/Expensify/App/assets/16493223/f6e954ac-70d3-4aaf-81c7-f5d1612b89ba">   |

**Comment by s77rt** [comment] 2024-03-17 17:50
@ikevin127 Thanks for the proposal. Your RCA is about right, though the linked PR is not the offending PR (the trim functionality was already there). I didn't go deep into analyzing your solution but it seems to have the same issue as in @tienifr's solution - bug outlined in the above comment ^

**Comment by s77rt** [comment] 2024-03-18 21:15
@abzokhattab Thanks for the update. The RCA is correct. Regarding the solution, the failing tests should be addressed (not all of them need to be updated - some are actually bugs) e.g. sending `> hello` should not have a leading space


Expected:
<img width="270" alt="Screenshot 2024-03-18 at 6 58 25 PM" src="https://github.com/Expensify/App/assets/16493223/35c4360e-95b0-46e2-aa59-b63c7abc8949">
<img width="270" alt="Screenshot 2024-03-18 at 7 00 17 PM" src="https://github.com/Expensify/App/assets/16493223/e07184a4-dcb8-446a-9a1e-acaa9982d0ac">

Received:
<img width="270" alt="Screenshot 2024-03-18 at 6 58 16 PM" src="https://github.com/Expensify/App/assets/16493223/8d88cb6b-8694-46f4-a965-aec1b2682c7e">
<img width="270" alt="Screenshot 2024-03-18 at 7 00 29 PM" src="https://github.com/Expensify/App/assets/16493223/6e522981-f4cd-4c9d-9a5e-f6667396aa9b">

**Comment by s77rt** [comment] 2024-03-18 21:33
@tienifr Thanks for the update. I found this edge case failing, not sure if it's worth addressing

```
>  # h1
> b
> c
```

Regardless the solution seems a little complicated (adding 3 more regex), can't we just remove the trim function and investigate why the other tests are failing?

**Comment by badeggg** [comment] 2024-03-19 07:38
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
Indented text in a quote is not showing correctly

### What is the root cause of that problem?
I think the root cause is simple, we simply trim leading and trailing spaces on every line in the quote.
[here](https://github.com/Expensify/expensify-common/blob/7bfd55f0ce75a37423119029fde58cfbe57086d9/lib/ExpensiMark.js#L839-L840)

### What changes do you think we should make in order to solve the problem?
Change line 
```
            let textToFormat = textToCheck.split('\n').map(row => row.substr(4).trim()).join('\n');
```
to:
```
            let textToFormat = textToCheck.split('\n').map(row => {
                let ret = row.substr(4);
                let trimed = ret.trimStart();
                const num = (ret.length - trimed.length) % 4;
                ret = ret.slice(num).trimEnd()
                return ret;
            }).join('\n');

```

### What alternative solutions did you explore? (Optional)
N/A

**Comment by badeggg** [comment] 2024-03-19 07:57
A little explanation(details) about my [proposal](https://github.com/Expensify/App/issues/38156#issuecomment-2006123806):
1. `row => row.substr(4).trim()` causing leading spaces and trailing spaces of all lines in a quote be removed, which is not actually what we need can since causing the issue
2. I believe what we really need is to trim all tailing spaces while remove as least leading spaces as possible to make the number of remaining leading spaces is multiple of 4 (let's say we want 4 spaces as an indentation, it can be 2 of course)
3. 
```
            row => {
                let ret = row.substr(4);
                let trimed = ret.trimStart();
                const num = (ret.length - trimed.length) % 4;
                ret = ret.slice(num).trimEnd()
                return ret;
            }
```
this code block is just a implementation of point 2
4. `substr` method is deprecated based on [mdn doc](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/String/substr), so I recommend change it to `slice`

**Comment by s77rt** [comment] 2024-03-19 21:05
@abzokhattab Thanks for the update. Unfortunately the solution is too complex (more regex and more loops).

**Comment by s77rt** [comment] 2024-03-19 21:08
@tienifr I would still prefer to avoid any additional regex. The trim was added as a feature (unwanted feature it appears). Removing that functionality should not increase the complexity.

**Comment by s77rt** [comment] 2024-03-19 21:15
@badeggg Thanks for the proposal. Your RCA is correct. The solution looks good to me 👍. We don't have any specific indent size, we can just limit the leading to trim to 1 char at most (substr 5 at most).

```js
let textToFormat = textToCheck.split('\n').map(row => row.substr(row[4] == " " ? 5 : 4).trimEnd()).join('\n');
```

🎀 👀 🎀 C+ reviewed
[Link to proposal](https://github.com/Expensify/App/issues/38156#issuecomment-2006123806)

**Comment by s77rt** [comment] 2024-03-19 21:16
@Julesssss Please assign me as C+ here as well

**Comment by laurenreidexpensify** [comment] 2024-03-20 10:44
@s77rt ignore false positive above, adding you as C+

@Julesssss please confirm Contributor assignment - https://github.com/Expensify/App/issues/38156#issuecomment-2008148585 thanks

**Comment by Julesssss** [comment] 2024-03-20 11:02
Thanks all

**Comment by Julesssss** [comment] 2024-03-20 12:08
Ah I see, thanks for pointing that out. @badeggg I'll unassign you for now while we rethink.

**Comment by hayes102** [comment] 2024-03-20 12:19
@Julesssss I want to contribute with you on this But one important aspect that might affect the solution is whether we should imitate how github deals with `#` and the spaces after the quote or or not because this will greatly impact the solution

**Comment by s77rt** [comment] 2024-03-21 04:26
@tienifr Thanks for catching the regression. Regarding the updated solution:
1. Trimming spaces before `>`: Can we avoid the try-undo approach, we are always trimming the text then check if it's a nested quote, if it's not we ignore the trim. Do you think we can know beforehand if we need to trim 1 char or trim all IOW how can we know if we are inside a nested quote. Had two ideas:
    1. Use indexOf or lastIndexOf to locate `>` -- lost train of thoughts 😅 
    2. Update the quote regex so that nested quotes are replaces at once -- not really sure but same idea ^ get the index of the last matched group (`>` char)
2. Trimming redundant new lines at the start: I think the regex is only needed for [this case](https://github.com/Expensify/App/issues/38156#issuecomment-2009418224) right? This case should not be considered because you can't send a message with leading spaces in the first place thus you can't be quoting such a message 


Overall the solution looks good to me

**Comment by badeggg** [comment] 2024-03-21 04:27
I have [updated my proposal](https://github.com/Expensify/App/issues/38156#issuecomment-2006123806)

**Comment by s77rt** [comment] 2024-03-21 04:30
@hayes102 As a rule of thumb, go with the easiest. We use a custom markdown flavor. As long as we fix this bug with no regressions (and no change in other behaviours) we should be good to proceed.

**Comment by badeggg** [comment] 2024-03-21 04:31
1. for case 
```
>           Hello
>     Hi 
```
that because we remove quote block start and end spaces [here](https://github.com/Expensify/expensify-common/blob/7bfd55f0ce75a37423119029fde58cfbe57086d9/lib/ExpensiMark.js#L842-L843), while what we want to do is only remove leading and trailing line breaks.

2. for case
```
>    >    > Hello
>    >  world
> Hi  
```
I think we should only handle `> ` case(only one space after >)

**Comment by s77rt** [comment] 2024-03-21 04:33
@badeggg Thanks for the update. For the second case you mentioned, it's something that currently works, we should not break that.

**Comment by badeggg** [comment] 2024-03-21 05:39
I have [updated my proposal](https://github.com/Expensify/App/issues/38156#issuecomment-2006123806)
>  For the second case you mentioned, it's something that currently works, we should not break that.
```
>    >    > Hello
>    >  world
> Hi  
```
If then, change line 
```
            let textToFormat = textToCheck.split('\n').map(row => row.substr(4).trim()).join('\n');
```
to:
```
            let textToFormat = textToCheck.split('\n').map(row => row.slice(4).replace(/\s*(&gt;)/, '$1').trimEnd()).join('\n');
```
which will remove leading &gt; and then leading spaces if the spaces are followed by `&gt;`

**Comment by badeggg** [comment] 2024-03-21 05:44
and **will not** remove indent spaces if they are not followed by `&gt;`

**Comment by badeggg** [comment] 2024-03-21 06:26
- By the way, I really think we should just `slice(4)` rather than `slice(row[4] == " " ? 5 : 4)` at 
```
            let textToFormat = textToCheck.split('\n').map(row => row.slice(row[4] == " " ? 5 : 4).replace(/\s*(&gt;|#)/, '$1').trimEnd()).join('\n');
```
(some test cases need amending)
- And, sorry for the bunch of small comment editing if that's annoying

**Comment by s77rt** [comment] 2024-03-21 22:39
@tienifr Regarding trimming the leading/trailing empty lines, the current process is as follow:
1. textToCheck is exploded to an array
2. array elements are joined to form textToFormat
3. textToFormat is trimmed

Can we explore changing the process to:
1. textToCheck is exploded to an array
2. array elements are filtered by removing empty strings (only for leading and trailing elements)
3. array elements are joined to form textToFormat


That way we won't have to do any post process on textToFormat

**Comment by s77rt** [comment] 2024-03-21 22:44
@badeggg That solution is basically same as what @tienifr proposed. Also we want to avoid regex and use text manipulation when possible

**Comment by s77rt** [comment] 2024-03-21 23:38
@abzokhattab Can we keep the logic in the same loop? (inside `.map` or `.reduce`)

**Comment by badeggg** [comment] 2024-03-22 06:46
I [have updated my proposal](https://github.com/Expensify/App/issues/38156#issuecomment-2006123806)
Add an alternative solution, which is simpler:
- `slice(4)` rather than `slice(row[4] == " " ? 5 : 4)`, this change needs amend some failing tests, which should be amended
- use regexp's lookahead assertion feature, which is more intuitive
- use one regexp to get rid of leading and trialing line breaks

Change two lines code, I can't see any elegant solution.

**Comment by s77rt** [comment] 2024-03-22 19:36
@abzokhattab, @tienifr, @badeggg Thank you all for your work here. All the solutions follow the same approach and they are petty much the same. If we go with that approach we'd go with @tienifr's solution being the first working regression-free solution. That being said I still think we need to dive a little deeper, for instance why do we need to trim spaces between nested quotes? Shouldn't we update the code to accept such cases instead of preventing them? (It may be worth to check `modifyTextForQuote` logic)

**Comment by s77rt** [comment] 2024-03-24 17:52
@tienifr Let's go with the first proposal and discuss improvements in the PR

🎀 👀 🎀 C+ reviewed
[Link to proposal](https://github.com/Expensify/App/issues/38156#issuecomment-1997117676)

**Comment by laurenreidexpensify** [comment] 2024-03-25 14:20
@Julesssss all yours to review ^^

**Comment by laurenreidexpensify** [comment] 2024-03-27 11:29
@tienifr what do you think the ETA for a draft PR is? Thanks

**Comment by quinthar** [comment] 2024-03-30 06:07
Who are we waiting on to review?

**Comment by Julesssss** [comment] 2024-04-02 10:46
Bumped PRs for merges and comment resolution

**Comment by Julesssss** [comment] 2024-04-02 15:37
Expensify-Common library PR merged. I'm taking https://github.com/Expensify/App/pull/39207 off hold

**Comment by s77rt** [comment] 2024-04-10 20:52
- The PR that introduced the bug has been identified: Not applicable. We just want a different behaviour now
- The offending PR has been commented on: n/a
- A discussion in #expensify-bugs has been started: n/a
- Determine if we should create a regression test for this bug: No. We have added tests to ensure this won't break

**Comment by Julesssss** [comment] 2024-04-11 16:56
Awaiting payment

**Comment by laurenreidexpensify** [comment] 2024-04-15 12:53
Payment Summary: 

- C+ $500 @s77rt paid via Upwork 
- Contributor $500 @tienifr paid via Upwork

**Closed** 2024-04-15 12:54 UTC
Labels: External, Daily, Awaiting Payment, Bug
