### ISSUE TITLE
Request money - Text cursor is jump when typing

### ISSUE THREAD

**Issue by kavimuru** [Expensify/App#26336] opened 2023-08-30 20:29 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Click FAB button
2. Click request money
3. Quickly input, Observe that the text cursor after each input jumps forward and then back.
## Expected Result: 
Text cursor is not jumping
## Actual Result: 
Text cursor jumps

## Workaround:
Can the user still use Expensify without this being fixed? Have you informed them of the workaround?

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [x] iOS / native
- [ ] iOS / Safari
- [ ] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:**
**Reproducible in staging?:** needs reproduction
**Reproducible in production?:** needs reproduction
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/43996225/6eb1facd-8a45-4ca8-807b-0f9c61a5d6c5

**Expensify/Expensify Issue URL:**
**Issue reported by:**  @namhihi237 
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1692600491724349

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by jayeshmangwani** [comment] 2023-08-30 21:12
@Christinadobrzyn It seems like a duplicate of this [issue](https://github.com/Expensify/App/issues/15856)

**Comment by jayeshmangwani** [comment] 2023-08-30 21:12
@Christinadobrzyn It seems like a duplicate of this [issue](https://github.com/Expensify/App/issues/15856)

**Comment by Christinadobrzyn** [comment] 2023-09-04 14:43
Thanks @jayeshmangwani! I'll close in favour of the other GH.

**Comment by Christinadobrzyn** [comment] 2023-09-05 19:32
waiting confirmation from https://github.com/Expensify/App/issues/15856

**Comment by Christinadobrzyn** [comment] 2023-09-07 19:24
I can reproduce this but still waiting confirmation if this will be fixed with https://github.com/Expensify/App/issues/15856

**Comment by Christinadobrzyn** [comment] 2023-09-11 20:32
Dupe confirmed https://github.com/Expensify/App/issues/15856#issuecomment-1712824216 

Closing without action

**Closed by Christinadobrzyn** 2023-09-11 20:32 UTC
Labels: Daily, Overdue, Bug
