### ISSUE TITLE
[$250] Expense - Color gradient of the background image in expense report is broken

### ISSUE THREAD

**Issue by izarutskaya** [Expensify/App#42135] opened 2024-05-14 09:14 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.73-1
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Issue reported by:** Applause-Internal team

## Action Performed:
1. Go to staging.new.expensify.com
2. Go to any DM.
3. Submit two expenses.
4. Click on the expense preview.

## Expected Result:
Background image will show color gradient.

## Actual Result:
Color gradient of the background image is broken.

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [x] Android: mWeb Chrome
- [x] iOS: Native
- [x] iOS: mWeb Safari
- [ ] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

https://github.com/Expensify/App/assets/115492554/f8c6ed53-0185-44bb-925e-84188435a546

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~016b8a02fcf04bc496</li>
        <li>Upwork Job ID: 1800285742152901110</li>
        <li>Last Price Increase: 2024-09-02</li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @situchan</details>

**Comment by izarutskaya** [comment] 2024-05-14 09:15
We think this issue might be related to the #collect project.

**Comment by strepanier03** [comment] 2024-05-21 21:46
Blocked on testing this. After I create my two expenses I can't move forward due to a different behavior. 

Will come back to this to test again.

**Comment by strepanier03** [comment] 2024-05-29 21:22
Will have an update soon, sites a bit rough now and I can't load in.

**Comment by strepanier03** [comment] 2024-06-10 21:53
All right, back from OoO all last week, working on this again.

**Comment by situchan** [comment] 2024-06-13 06:13
@gijoe0295 thanks for the proposal. The root cause is not accurate. And I don't like your solution to reduce image height.

**Comment by situchan** [comment] 2024-06-17 19:08
Awaiting proposals

**Comment by situchan** [comment] 2024-06-25 16:46
No satisfactory proposals yet

**Comment by situchan** [comment] 2024-07-23 21:22
@strepanier03 kind bump https://github.com/Expensify/App/issues/42135#issuecomment-2189445723

**Comment by strepanier03** [comment] 2024-09-03 17:27
I'll try to repro as well. If it turns out neither of us can, I'll close this.

**Comment by strepanier03** [comment] 2024-09-03 17:34
Also unable to repro any longer. I'm going to close this out and we can reopen if it surfaces again.

**Closed by strepanier03** 2024-09-03 17:34 UTC
Labels: External, Monthly, Help Wanted, Bug
