### ISSUE TITLE
[Violations] [MEDIUM] IOU - The disabled category message does not disappear immediately after the change is made

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#34541] opened 2024-01-15 22:11 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.25-1
**Reproducible in staging?:** Y
**Reproducible in production?:** N
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** Applause - Internal Team
**Slack conversation:**

## Action Performed:
Preconditions:
In OldDot under admin, create a Collect group policy, enable Categories, add 3 Categories, add an employee to the policy.
1. Open https://staging.new.expensify.com/
2. Log in to the employee's account
3. Tap on the green plus button (FAB)
4. Select Request money
5. Select any currency and amount
6. Click next
7. Choose a WS room
8. Click on "Show more"
9. In the "Category" section, select any category
10. Complete the IOU
11. Open https://staging.expensify.com/
12. Log in to the admin account
13. Navigate to the Collect group policy settings
14. In the category tab, disable the employee's selected category from step 9
15. In the employee's account in ND, open the IOU details.
16. Click on the category field
17. Select an enabled category

## Expected Result:
The message about a disabled category should immediately disappear after selecting an enabled category

## Actual Result:
The disabled category message does not disappear immediately after selecting an enabled category

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [x] Android: mWeb Chrome
- [x] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details> 

https://github.com/Expensify/App/assets/78819774/18737e22-f5da-4c97-a0f6-735a5ce7674d

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by mountiny** [comment] 2024-01-16 00:28
Not a blocker, new feature

**Comment by paultsimura** [comment] 2024-01-16 10:07
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
The `categoryOutOfPolicy` violation message doesn't disappear on the category change.

### What is the root cause of that problem?
We do not optimistically remove the category violation when updating the Money Request's category.

### What changes do you think we should make in order to solve the problem?
When editing a money request, if the changes contain category, along with updating the recently used category, we should remove the category violation from this transaction's Onyx entry: `${ONYXKEYS.COLLECTION.TRANSACTION_VIOLATIONS}${transactionID}`
https://github.com/Expensify/App/blob/c13c497d48ff46974cb7a6a800f6f5007abca5ee/src/libs/actions/IOU.js#L2342-L2352

### What alternative solutions did you explore? (Optional)

**Comment by mountiny** [comment] 2024-01-16 11:21
@cead22 is making lots of changes to violations like this so we should be ware we dont waste energy and money on something that will be changed by his work

**Comment by cead22** [comment] 2024-01-16 16:38
> **Concern:** IMO, it's quite risky to operate an Onyx entry that holds an array, because it doesn't support the `MERGE` operation properly. It's worth thinking of using an Object for them in Onyx, this will enable better control over the specific violations.
> Asked to clarify here: https://expensify.slack.com/archives/C01GTK53T8Q/p1705400084950499

Thanks for raising this in expensify-open-source. For context, this was discussed quite a bit and we landed on using the array because this array is primarily set from the backend, and the violations array is never too big that it should cause performance issues. That said, we do set some violations from the front end in `ViolationUtils.getViolationsOnyxData`

I'm going to move this issue to the violations project and take it internally with Infinite Red

cc @lindboe @trevor-coleman please comment for assignment

**Comment by cead22** [comment] 2024-01-19 00:58
I believe this is the same issue as https://github.com/Expensify/Expensify/issues/361948, but I'll make sure and get them resolved

**Comment by lindboe** [comment] 2024-01-19 01:09
@cead22 this should be covered by https://github.com/Expensify/App/issues/31093, right?

**Comment by cead22** [comment] 2024-01-19 20:44
For categories and tags, yes, but for amount for instance, no. We have some backend commands updating money requests that should be sending down the updated violation data, and they currently aren't

**Comment by luacmartins** [comment] 2024-01-23 16:15
Just FYI that we have this potentially dupe issue - https://github.com/Expensify/App/issues/34945

**Comment by cead22** [comment] 2024-01-24 14:07
I'll look into this today

**Comment by cead22** [comment] 2024-01-24 14:58
Started a [convo](https://expensify.slack.com/archives/C03SDMF9YJ2/p1706107270591929) in reliable updates to brainstorm good ways to solve this

**Comment by lanitochka17** [comment] 2024-01-25 22:46
The same behavior with tag

https://github.com/Expensify/App/assets/78819774/06a880ea-0d9d-4235-855e-f4fc998c4544

Should I post this bug as new or should it be related to this one?

**Comment by cead22** [comment] 2024-01-25 23:24
We discussed this in slack, and the problem is more complex than I originally thought, so it'll take a bit to solve thi

**Comment by youssef-lr** [comment] 2024-01-29 13:55
@cead22 this seems related https://expensify.slack.com/archives/C049HHMV9SM/p1706531475509869

**Comment by cead22** [comment] 2024-02-10 00:55
No updates yet

**Comment by cead22** [comment] 2024-02-21 00:14
No updates

**Comment by cead22** [comment] 2024-04-01 21:03
No update on this one, though I agree with it being polish

**Comment by cead22** [comment] 2024-05-06 22:24
I'm not sure if this is reproducible anymore (and the site is kinda shaky right now to test), but I think this is mostly something we'll need to take into account when moving violations to auth.

Specifically, we need to make sure that when changes are made to policies -- and other things that can affect violations like domain security groups, that we somehow update the affected transactions and their corresponding violations in real-time in all clients

**Comment by JmillsExpensify** [comment] 2024-05-20 21:45
Noted, should we move this issue out of #wave-control then? Or keep it here, pending the completion of 1:1:1 for violations in #newdot-quality?

**Comment by cead22** [comment] 2024-05-21 01:52
Up to you -- you probably know better. I'm good with either

**Comment by cead22** [comment] 2024-06-07 19:17
In the doc to implement violations in auth we're discussing whether re-fetching violations, which will be necessary in some cases like this (as well as others) so violations update in real-time.

If we agreed on leaving that out of scope for that project, I'll close this, and we can solve these issues as they come up when user start experiencing them

**Comment by cead22** [comment] 2024-06-10 21:40
We have no pushback on leaving this out of the scope of that doc, so closing this

**Closed by cead22** 2024-06-10 21:40 UTC
Labels: Engineering, Monthly
