### ISSUE TITLE
[HOLD 2024-09-25] [$125]  Report fields - Not here page appears briefly after deleting the list value

### ISSUE THREAD

**Issue by izarutskaya** [Expensify/App#44815] opened 2024-07-04 10:38 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 9.0.4-0
**Reproducible in staging?:** Yes
**Reproducible in production?:** Yes
**Found when validating PR :** https://github.com/Expensify/App/pull/44275
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Issue reported by:** Applause-Internal team

## Action Performed:
1. Go to staging.new.expensify.com
2. Go to workspace settings > Report fields.
3. Tap Add field.
4. Tap Type > Select List.
5. Tap List values.
6. Tap Add value.
7. Add a value and save it.
8. Tap on the added value.
9. Delete it.

## Expected Result:
Not here page will not appear after deleting the list value.

## Actual Result:
Not here page appears (it slides away quickly) after deleting the list value.

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [ ] Android: mWeb Chrome
- [x] iOS: Native
- [ ] iOS: mWeb Safari
- [ ] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

https://github.com/Expensify/App/assets/115492554/27a36bc4-8f8c-40f1-b865-d83dd1ad00cd

![Bug6532660_1720061216644!IMG_C83C24EE03F1-1](https://github.com/Expensify/App/assets/115492554/8e4eb57b-015b-4582-a890-325a6263c405)

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Issue Owner</summary>Current Issue Owner: @shubham1206agra</details>
<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~010d8fadf7c03f3196</li>
        <li>Upwork Job ID: 1814752832262695876</li>
        <li>Last Price Increase: 2024-08-24</li>
<li>Automatic offers: </li>
<ul>
<li>shubham1206agra | Reviewer | 103199939</li>
<li>nkdengineer | Contributor | 103694254</li>
</ul></li>
    </ul>
</details>

**Comment by izarutskaya** [comment] 2024-07-04 10:39
@puneetlath FYI I haven't added the External label as I wasn't 100% sure about this issue. Please take a look and add the label if you agree it's a bug and can be handled by external contributors.

**Comment by izarutskaya** [comment] 2024-07-04 10:39
We think this issue might be related to the #collect project.

**Comment by danieldoglas** [comment] 2024-07-04 15:13
This is not a deploy blocker because the feature is under beta. @mountiny do you wanna assign this one for yourself?

**Comment by mountiny** [comment] 2024-07-04 22:31
I am managing this project so going to take over this issue to make sure it gets fixed. Thanks for helping!

**Comment by mountiny** [comment] 2024-07-08 19:15
@rezkiy37 @waterim who can take this one on?

**Comment by waterim** [comment] 2024-07-08 19:16
This one was fixed in delete as I remeber, will test tomorrow

**Comment by mountiny** [comment] 2024-07-08 19:29
Nice, added reviewing label but can you also please test and link the pr to this issue and add the test steps there? Thanks!

**Comment by puneetlath** [comment] 2024-07-18 20:49
@waterim @mountiny I'm not really following what is happening in this issue. Mind giving an update?

**Comment by waterim** [comment] 2024-07-18 20:50
This one was fixed in another issue

**Comment by puneetlath** [comment] 2024-07-18 20:51
Ah ok. So should we just close this out?

**Comment by mountiny** [comment] 2024-07-19 23:59
I will ask QA to retest

**Comment by mountiny** [comment] 2024-07-20 00:00
https://expensify.slack.com/archives/C9YU7BX5M/p1721433611664079

**Comment by m-natarajan** [comment] 2024-07-20 15:35
Tester is able to reproduce in the latest staging build. Same steps as mentioned in the OP. 

https://github.com/user-attachments/assets/8bf8cdbb-02a5-47f9-a9ef-17f646ea3475

**Comment by mountiny** [comment] 2024-07-20 20:04
Thanks for confirming, looking for proposals from the community

**Comment by nkdengineer** [comment] 2024-07-22 10:29
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
Not here page appears (it slides away quickly) after deleting the list value.

### What is the root cause of that problem?
When we delete the field value, the `currentValueName` will be an empty string, and then the not found page appears briefly before we go back to the previous page.

https://github.com/Expensify/App/blob/e3ebeffb55c2a20ee890061f23e3e0f37d32290e/src/pages/workspace/reportFields/ReportFieldsValueSettingsPage.tsx#L62-L65
### What changes do you think we should make in order to solve the problem?
We should create a state to check if we're deleting the field value we will not display the not found page

```
const [isDeleting, setIsDeleting] = useState(false);
if ((!currentValueName && !isDeleting) || hasAccountingConnections) {
    return <NotFoundPage />;
}
const deleteListValueAndHideModal = () => {
    if (reportFieldID) {
        ReportField.removeReportFieldListValue(policyID, reportFieldID, [valueIndex]);
    } else {
        ReportField.deleteReportFieldsListValue([valueIndex]);
    }

    setIsDeleteTagModalOpen(false);
    setIsDeleting(true);
    Navigation.goBack();
};
```

### What alternative solutions did you explore? (Optional)
Or we can only display the not found page if the default value of this field value is empty
```
const defaultReportFieldValue = useRef(() => {
    if (reportFieldID) {
        const reportFieldKey = ReportUtils.getReportFieldKey(reportFieldID);

        return Object.values(policy?.fieldList?.[reportFieldKey]?.values ?? {})?.[valueIndex] ?? '';
    } 
        return formDraft?.listValues?.[valueIndex] ?? '';
})
if ((!defaultReportFieldValue.current) || hasAccountingConnections) {
    return <NotFoundPage />;
}
```

**Comment by mountiny** [comment] 2024-07-22 22:33
@shubham1206agra @rushatgabhane can you please review the proposal?

**Comment by rushatgabhane** [comment] 2024-07-23 01:22
@nkdengineer what if we do not show Not found page in any case?

**Comment by nkdengineer** [comment] 2024-07-23 02:49
@rushatgabhane If we do not show the not found page, the page will display the form when we open the page with an invalid `valueIndex` or `reportFieldID` or this value is deleted in other platforms.

**Comment by rushatgabhane** [comment] 2024-07-26 02:14
> We should create a state to check if we're deleting the field value we will not display the not found page

how will we set the `isDeleting` state back to false?

**Comment by nkdengineer** [comment] 2024-07-26 02:48
> how will we set the isDeleting state back to false? Or how will we know that the onyx action has completed?

@rushatgabhane This state will only update to `true` when we delete the report field to prevent the not found page is displayed. And we don't need to update this back to `false` because we will navigate to another page after deleting.

**Comment by mountiny** [comment] 2024-07-29 20:34
Can we just navigate when deleting and accept that if user goes back it would show not found page, i think that would be fine

**Comment by rushatgabhane** [comment] 2024-07-29 20:50
@mountiny i agree with you. We should close the issue

**Comment by puneetlath** [comment] 2024-08-02 14:58
>@mountiny i agree with you. We should close the issue

Wait, we still need to implement what @mountiny said [here](https://github.com/Expensify/App/issues/44815#issuecomment-2256862723) right?

**Comment by mvtglobally** [comment] 2024-08-03 04:09
Issue not reproducible during KI retests. (First week)

**Comment by puneetlath** [comment] 2024-08-05 18:39
@mountiny @rushatgabhane mind confirming if anything needs to be done here?

**Comment by rushatgabhane** [comment] 2024-08-05 21:12
we can close this issue

**Comment by mountiny** [comment] 2024-08-08 00:59
@lanitochka17 can you please retest this? Is the not found page showing when the list option is deleted? Or when User goes back after deleting it?

**Comment by mountiny** [comment] 2024-08-12 00:11
Bump here @kavimuru @lanitochka17

**Comment by kavimuru** [comment] 2024-08-14 13:39
@mountiny able to reproduce the bug. 
 List value editor changes to not found page after deleting it while it is dismissing

https://github.com/user-attachments/assets/198288cc-4609-43ea-9d94-61f2daa7668b

**Comment by rezkiy37** [comment] 2024-08-14 15:37
@mountiny, it happens very quickly during the navigation animation. I will take the issue to fix 🙂 

<img width="540" alt="Screenshot 2024-08-14 at 17 36 09" src="https://github.com/user-attachments/assets/9a128e3d-998f-4fbd-b536-a546ce6836d9">

**Comment by rezkiy37** [comment] 2024-08-14 15:37
Hi, I’m Michael (Mykhailo) from Callstack and I would like to work on this issue.

**Comment by nkdengineer** [comment] 2024-08-14 15:58
@rezkiy37 What do you think about my proposal [here](https://github.com/Expensify/App/issues/44815#issuecomment-2242626570)? We can have another option is to use `usePrevious` hook for `currentValueName` and only display the not found page if both the previous value and the current value is empty.

**Comment by rezkiy37** [comment] 2024-08-16 10:18
@nkdengineer hey! 
The [proposal](https://github.com/Expensify/App/issues/44815#issuecomment-2242626570) makes sense to me. However, I am not a C+ reviewer. So @shubham1206agra @rushatgabhane can you please review the proposal?

**Comment by mountiny** [comment] 2024-08-21 19:29
@shubham1206agra Do you agree with the proposal from @nkdengineer ?

**Comment by rezkiy37** [comment] 2024-08-26 09:06
@shubham1206agra bump.

**Comment by mountiny** [comment] 2024-08-27 00:00
Thanks for confirming

**Comment by mountiny** [comment] 2024-09-21 07:51
@puneetlath the automstion failed, tjis is ready for payment, updated the issue

$125 to both @nkdengineer and @shubham1206agra

**Comment by puneetlath** [comment] 2024-09-21 21:32
@nkdengineer has been paid. 

@shubham1206agra offer here: https://www.upwork.com/nx/wm/offer/104071274. Please ping me when you've accepted.

**Comment by puneetlath** [comment] 2024-09-22 19:22
All paid. Thanks everyone!

**Closed by puneetlath** 2024-09-22 19:22 UTC
Labels: External, Engineering, Daily, Awaiting Payment, Bug
