### ISSUE TITLE
[$500] Unexpected Redirection to DM with Concierge Instead of #admins Chat When Selecting Setup Specialist Option

### ISSUE THREAD

**Issue by johncschuster** [Expensify/App#32128] opened 2023-11-28 14:37 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** v1.4.3-11
**Reproducible in staging?:** No
**Reproducible in production?:** Yes
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):** dcardoza@Expensify.com
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** @davidcardoza 
**Slack conversation: https://expensify.slack.com/archives/C03U7DCU4/p1700167866247689**

## Action Performed:

1. Created an Account [davidexpensifytesting@gmail.com](https://www.expensify.com/_support/?supportEmail=davidexpensifytesting%40gmail.com&comment=better%20supportal%20issue%20nubmer%3A%20338729&location=_support/)
2. Created a workspace
3. Selected the 'Setup Specialist' option in the LHN under Support.
4. Closed the NewDot application.
5. Navigated back to Expensify.com
6. Selected the 'Setup Specialist' option in the LHN under Support.
7. Redirected to a NewDot DM with Concierge.

## Expected Result:
Expectation to be redirected to the #admins chat when selecting the option to chat with a Setup Specialist.

## Actual Result:
Instead of being directed to the #admins chat, was placed into a Direct Message with Concierge.

## Workaround:
Currently, no workaround is identified. The user's expectation to enter the #admins chat when selecting the Setup Specialist option is not met.

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [ ] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~012157b2ec7d06ca6e</li>
        <li>Upwork Job ID: 1729509966477643776</li>
        <li>Last Price Increase: 2023-12-19</li>
    </ul>
</details>

**Comment by junsupark94** [comment] 2023-11-29 17:36
Is there a way to create fake Expensify card transactions so I can try to reproduce this bug?

**Comment by johncschuster** [comment] 2023-12-04 21:43
No worries, @junsupark94! I've done that _many_ many times 😅

**Comment by jjcoffee** [comment] 2023-12-06 08:24
Waiting for proposals.

**Comment by keisyrzk** [comment] 2023-12-13 06:07
@davidcardoza @johncschuster 
could you please explain how to select `'Setup Specialist' option in the LHN under Support.` please?
There is no video attached to the issue. Could you please add some so we could see exact steps to reproduce?

**Comment by jjcoffee** [comment] 2023-12-13 09:47
I _think_ the implication that the first steps are in newDot might be incorrect, as there isn't any Setup Specialist option or a Support menu in the LHN on newDot. 

Though I can't reproduce this specific issue of being redirected to concierge, I do get redirected to a not found page. Here's what I'm doing:

1. You need an account that has access to oldDot and that has at least one workspace created in newDot
2. Login to oldDot
3. Switch to a workspace that was created on newDot
4. Select the 'Setup Specialist' option in the LHN under Support

https://github.com/Expensify/App/assets/27287420/1890800d-cc9b-4f0d-bd6d-f35861aceb90

**Comment by DylanDylann** [comment] 2023-12-14 06:41
@jjcoffee I think this bug is not related to new dot. We should add internal label

**Comment by jjcoffee** [comment] 2023-12-14 13:52
Agreed, there's an `exitTo` param in the link that `oldDot` generates, that for me points to a report that I don't have access to. I guess the redirecting to concierge has a similar root cause. Let's make this internal @johncschuster.

**Comment by johncschuster** [comment] 2023-12-18 15:28
@davidcardoza It looks like this might be an issue with OldDot. I'm OOO Monday, December 18 (today) through Tuesday, January 2, so I won't be able to push to advocate for this bug. Would you mind raising this up internally so we can get it fixed?

If this issue is open when I'm back from OOO, I'll take it back over. Thank you!

**Comment by mvtglobally** [comment] 2023-12-21 16:10
Issue not reproducible during KI retests. (First week)

**Comment by Beamanator** [comment] 2023-12-22 07:41
Happily moving to be internal, not working on this for now since last tests were not reproducible

**Comment by Beamanator** [comment] 2023-12-27 17:46
Same as ^

**Comment by davidcardoza** [comment] 2024-01-04 03:30
I can't seem to reproduce this again. I am going to go ahead and close.

**Closed by davidcardoza** 2024-01-04 03:30 UTC
Labels: Engineering, Weekly, Internal, Bug
