### ISSUE TITLE
[HOLD for payment 2023-09-06] [$1000] After deleting the last thread message, the 'completed task' message briefly appears in English instead of Spanish

### ISSUE THREAD

**Issue by kavimuru** [Expensify/App#24231] opened 2023-08-07 18:16 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Go to Settings > Preferences > Language
2. Select the Spanish language
3. Go back and open a chat
4. Go to the "Assign task" section
5. Enter a title and create the task
6. Click on the ‘Mark as done’ button
7. Send a thread message after that
8. Now delete the thread message
9. Observe that the LHN shows the 'completed task' message in English for a while
## Expected Result:
After deleting the last thread message, the 'completed task' message should be displayed in Spanish consistently
## Actual Result:
When deleting the thread message, the 'completed task' message briefly appears in English before switching to Spanish
## Workaround:
Can the user still use Expensify without this being fixed? Have you informed them of the workaround?

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [x] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 1.3.50.3
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/43996225/9e423338-b5ce-4a8b-bf33-abfebaab616c

https://github.com/Expensify/App/assets/43996225/7fbab530-8c27-4dc9-b2da-280aa1b00ef8

**Expensify/Expensify Issue URL:**
**Issue reported by:** @ayazhussain79 
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1690910046289219

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01ee84b5eaf49507dc</li>
        <li>Upwork Job ID: 1690148058207748096</li>
        <li>Last Price Increase: 2023-08-18</li>
<li>Automatic offers: </li>
<ul>
<li>DanutGavrus | Contributor | 26241879</li>
</ul></li>
    </ul>
</details>

**Comment by DanutGavrus** [comment] 2023-08-07 18:16
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
After deleting the last thread message, the completed task message briefly appears in English instead of Spanish.

### What is the root cause of that problem?
In `OptionRowLHN`, we show the `optionItem.alternateText`. The `optionItem` comes from `SidebarUtils.getOptionData` method which sets the **alternateText**. 
https://github.com/Expensify/App/blob/e555022ef97cec4ddbc39283c0d537d6366a2a49/src/libs/SidebarUtils.js#L307-L318
1. It uses the *translate* method, but the problem is that when we delete the last action, we do not filter it out. So, first time `getOptionData` runs with the action which has pending delete, it does not trigger any of the ifs, and gets to the `result.alternateText = lastMessageTextFromReport.length > 0 ? lastMessageText : Localize.translate(preferredLocale, 'report.noActivityYet')` which sets the text the **lastMessageText** which is *Completed task: title*.
2. After that action gets deleted, the second run runs with the appropriate action and triggers the if in which the *translate* method is used, and actually returns the Spanish text now.

### What changes do you think we should make in order to solve the problem?
We should filter out the actions from [here](https://github.com/Expensify/App/blob/e555022ef97cec4ddbc39283c0d537d6366a2a49/src/libs/SidebarUtils.js#L33-L36) which have pending delete in them such that the `getOptionData` method will run with the appropriate action from the start, and will actually trigger the if in which the *translate* method is used:
```js
const reportActionsForDisplay = _.filter(
    actionsArray,
    (reportAction, actionKey) => ReportActionsUtils.shouldReportActionBeVisible(reportAction, actionKey) && reportAction.actionName !== CONST.REPORT.ACTIONS.TYPE.CREATED && reportAction.pendingAction !== CONST.RED_BRICK_ROAD_PENDING_ACTION.DELETE // <-- added last condition
);
```

**Comment by alexpensify** [comment] 2023-08-09 20:21
This one is on my testing list.

**Comment by alexpensify** [comment] 2023-08-11 23:49
I've tested and confirmed that the English version appears after you delete the comment. It's almost like a flash and it appears for a short period of time. @parasharrajat when you get a chance, please review if the proposal will fix this issue.

**Comment by ShogunFire** [comment] 2023-08-13 15:37
## Proposal

### Please re-state the problem that we are trying to solve in this issue.

When we delete the only comment in a task that is completed, the translation of Task completed in the LHN is in english for a moment

### What is the root cause of that problem?

I agree with the root cause found by @DanutGavrus here: https://github.com/Expensify/App/issues/24231#issuecomment-1668371433

We are not filtering out the deleted action so the text that is chosen is the field lastMessageText

### What changes do you think we should make in order to solve the problem?

We can't filter out all the deleted actions because when we delete a message that is also a thread parent we want to show Message Deleted in the LHN.
We need to filter out the deleted actions that are not parent thread, we can use the method isDeletedParentAction to verify.


### What alternative solutions did you explore? (Optional)

Updating lastMessageText with the right translation but we would need to verify that it is updated at the right times for example when we change languages

**Comment by ShogunFire** [comment] 2023-08-13 15:39
Sorry, I wanted to make a more different proposal but hey maybe I am preventing a regression... I am ok with sharing the bounty ahah

**Comment by DanutGavrus** [comment] 2023-08-14 07:01
Hi, @ShogunFire! I tried reproducing the issue you mentioned with https://github.com/Expensify/App/issues/24231#issuecomment-1668371433, but I was not able. Could you please provide some steps, or a short video? Thanks!

**Comment by ShogunFire** [comment] 2023-08-14 08:31
Sorry the issue never happens, it was all in my head ^^ Deleting my proposal because I am self conscious now

**Comment by DanutGavrus** [comment] 2023-08-15 08:24
@parasharrajat Luckily, you are the C+ here and were also the reviewer of [this PR](https://github.com/Expensify/App/pull/16606) where you've really done a great job reviewing that! You mentioned in [this comment](https://github.com/Expensify/App/pull/16606#issuecomment-1489379797) *"It should not be created and Closed."*, and the [reponse](https://github.com/Expensify/App/pull/16606#issuecomment-1496121393) was *"Seems like `ReportActionsUtils.getSortedReportActionsForDisplay` already sorts and filters out deleted messages and closed state messages, only necessary to filter out for the created state."*. Do you remember if there was a reason for not adding `action.actionName !== CONST.REPORT.ACTIONS.TYPE.CREATED` [here](https://github.com/BeeMargarida/App/blob/aa3b4ca937db04b3a41bc27538f1325f88689e51/src/libs/ReportActionsUtils.js#L192)?

I tried moving both checks for the **action.actionName** and the **reportAction.pendingAction** from [here](https://github.com/Expensify/App/blob/main/src/libs/SidebarUtils.js#L34) into our present `shouldReportActionBeVisible` [method](https://github.com/Expensify/App/blob/main/src/libs/ReportActionsUtils.js#L334) and https://github.com/Expensify/App/issues/15711, [this Slack bug](https://expensify.slack.com/archives/C049HHMV9SM/p1679682026812889) & https://github.com/Expensify/App/issues/24231 are not reproducible, but I would not want to create a new Issue. 😁

cc: @mountiny I think you may have context over this as I see your were also a reviewer of that PR.

Would you two say it's safe to move **actionName** check and to add the new **pendingAction** check directly into the **shouldReportActionBeVisible** method? Thank you in advance!

```js
if (reportAction.actionName === CONST.REPORT.ACTIONS.TYPE.CLOSED || reportAction.actionName === CONST.REPORT.ACTIONS.TYPE.CREATED) {
    return false;
}
```

```js
if (isPendingRemove(reportAction) || reportAction.pendingAction === CONST.RED_BRICK_ROAD_PENDING_ACTION.DELETE) {
    return false;
}
```

**Comment by hayata-suenaga** [comment] 2023-08-18 17:04
@DanutGavrus ?

**Comment by DanutGavrus** [comment] 2023-08-21 08:59
@hayata-suenaga I think that we should keep the code from the Proposal as is. If we add the condition for the `pendingAction` inside `shouldReportActionBeVisible` offline deleted messages disappear instead of displaying as strikethrough.

**Comment by hayata-suenaga** [comment] 2023-08-21 14:49
okay then I'm assigning @DanutGavrus

**Comment by DanutGavrus** [comment] 2023-08-23 07:10
@parasharrajat 
PR ready for review: https://github.com/Expensify/App/pull/25743

**Comment by DanutGavrus** [comment] 2023-08-25 07:22
@hayata-suenaga PR got merged only ~1h after the bonus deadline 😔. C+ approved changes ~18h before it got merged. Is there any chance we are eligible for the bonus in this case? 😁 Thank you!

**Comment by hayata-suenaga** [comment] 2023-08-25 14:33
@alexpensify 

contributor assignment: 
<img width="200" alt="Screenshot 2023-08-25 at 7 31 12 AM" src="https://github.com/Expensify/App/assets/98560306/f1dac51e-db6a-4f2f-9621-9b0d77179d01">

C+ approval
<img width="200" alt="Screenshot 2023-08-25 at 7 31 53 AM" src="https://github.com/Expensify/App/assets/98560306/ebea15a1-678d-4726-b8a7-40eeb2e76142">

My approval
<img width="200" alt="Screenshot 2023-08-25 at 7 32 36 AM" src="https://github.com/Expensify/App/assets/98560306/96e4863d-cf53-4f96-8f1d-2d161afa2154">

**Comment by DanutGavrus** [comment] 2023-09-06 10:37
Hi, @alexpensify! Based on the previous comments, is the bonus applicable? Thank you!

**Comment by alexpensify** [comment] 2023-09-06 22:25
Here is the payment summary: 

-  External issue reporter @ayazhussain79 $250 
-  Contributor that fixed the issue @DanutGavrus $1500
-  Contributor+ that helped on the issue and/or PR @parasharrajat $1500

Upwork Job: https://www.upwork.com/jobs/~01ee84b5eaf49507dc

*If applicable, the bonuses will be applied on the final payment 

Extra Notes regarding payment: I think we should apply the bonus here based on these notes: https://github.com/Expensify/App/issues/24231#issuecomment-1693460592

**Comment by alexpensify** [comment] 2023-09-06 22:34
Payments have been prepared in Upwork for @ayazhussain79 and @DanutGavrus. Please accept and I can complete the required process. 

@parasharrajat request in Chat 

@hayata-suenaga can you approve the regression test, so I can complete the next steps? 

Thanks!

**Comment by ayazhussain79** [comment] 2023-09-06 22:36
@alexpensify Offer accepted. Thank you!

**Comment by DanutGavrus** [comment] 2023-09-07 10:39
@alexpensify Offer accepted. Thanks!

**Comment by alexpensify** [comment] 2023-09-07 22:54
Everyone has been paid via Upwork.

**Comment by alexpensify** [comment] 2023-09-08 23:17
@hayata-suenaga - let me know if you agree with the regression test and I can create that GH.

**Comment by hayata-suenaga** [comment] 2023-09-11 01:45
@alexpensify I agree with the regression test 🙇 sorry for the delay in response

**Comment by alexpensify** [comment] 2023-09-12 22:36
Thanks, I'm OOO until Thursday and will create the regression test then.

**Comment by alexpensify** [comment] 2023-09-15 18:43
Closing - QA test request has been created for this one.

**Closed by alexpensify** 2023-09-15 18:43 UTC
Labels: External, Daily, Overdue, Awaiting Payment, Bug

**Comment by JmillsExpensify** [comment] 2023-10-12 22:15
$1,500 payment approved for @parasharrajat based on BZ summary.
