### ISSUE TITLE
[HOLD for payment 2024-10-30] [$250] Bank Account - "Please provide a valid website" error is shown

### ISSUE THREAD

**Issue by IuliiaHerets** [Expensify/App#50103] opened 2024-10-02 19:10 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** v9.0.43-2
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**Issue was found when executing this PR:** https://github.com/Expensify/App/pull/49957
**Email or phone of affected tester (no customers):** gibethlehem@gmail.com
**Issue reported by:** Applause Internal Team

## Action Performed:
1. Log in to an account
2. Create a workspace > Enable Workflow > Connect bank account > Connect online with plaid
3. Continues the flow until you reached "Company website" page
4. Write invalid email
5. Click "next"
6. After the error is show, clear the invalid email and go back.
7. Return to "Company website" page

## Expected Result:
"Please provide a valid website" error is not shown

## Actual Result:
"Please provide a valid website" error is shown and it is not dismissed even after navigating back

## Workaround:
Unknown

## Platforms:

- [ ] Android: Native
- [x] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

https://github.com/user-attachments/assets/d476d2c7-58d4-416e-ba6b-6e00a1e641f0

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~021842647294027107619</li>
        <li>Upwork Job ID: 1842647294027107619</li>
        <li>Last Price Increase: 2024-10-05</li>
<li>Automatic offers: </li>
<ul>
<li>ishpaul777 | Reviewer | 104403869</li>
</ul></li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @anmurali</details>

**Comment by IuliiaHerets** [comment] 2024-10-02 19:11
@anmurali  FYI I haven't added the External label as I wasn't 100% sure about this issue. Please take a look and add the label if you agree it's a bug and can be handled by external contributors

**Comment by mkzie2** [comment] 2024-10-03 01:27
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
- "Please provide a valid website" error is shown and it is not dismissed even after navigating back

### What is the root cause of that problem?
- The company website has company tax as its previous step.

- When we start the bank account until reach company tax. Now click the "Next" button will call ```UpdateCompanyInformationForBankAccount``` with ```website``` data is `""`. There is no error returned by BE here.

- Then, it redirects to company website. Here when we type something like "https://123" and then reset to "https://", it saved ```website: https://" to the ```reimbursementAccountDraft```.

- Then we go back to company tax page. Here, if we click "Next" button, it will call ```UpdateCompanyInformationForBankAccount``` with ```website``` data is `"https://"` and it is invalid value and as a result, BE returns onyx error: 

```
{
    "onyxMethod": "merge",
    "key": "reimbursementAccount",
    "value": {
        "errors": {
            "1727918521418387": "Please provide a valid Website"
        }
    }
}
```

- So the "Please provide a valid Website" error message is shown.
### What changes do you think we should make in order to solve the problem?
- When we are in company website page and go back, we need to clear the ```reimbursementAccountDraft.website``` if its value is ```https://```.

- So in [here](https://github.com/Expensify/App/blob/3b15d846bbe591631f05604fd6a512c2acbd6247/src/pages/ReimbursementAccount/BusinessInfo/substeps/WebsiteBusiness.tsx#L28) we introduce a ref ```const websiteRef = useRef()``` to keep track the company website input. Then add ```onChangeText={(t) => (websiteRef.current = t)}``` to [InputWrapper](https://github.com/Expensify/App/blob/3b15d846bbe591631f05604fd6a512c2acbd6247/src/pages/ReimbursementAccount/BusinessInfo/substeps/WebsiteBusiness.tsx#L64).

- Finally, add cleanup function:

```
    useEffect(() => {
        return () => {
            if (defaultWebsiteExample === websiteRef.current) {
                BankAccounts.addBusinessWebsiteForDraft(null);
            }
        };
    }, []);
```
### What alternative solutions did you explore? (Optional)

**Comment by mkzie2** [comment] 2024-10-03 01:39
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
- "Please provide a valid website" error is shown and it is not dismissed even after navigating back

### What is the root cause of that problem?
- The company website is a step that occurs after the company tax step.

- When starting the bank account setup and reaching the company tax page, clicking the "Next" button triggers the UpdateCompanyInformationForBankAccount function, passing the website data as "". No error is returned by the backend here.

- Next, it redirects to the company website page. If you input something like "https://123" and then reset it to "https://", the system saves website: "https://" in the reimbursementAccountDraft.

- When navigating back to the company tax page, clicking the "Next" button again triggers UpdateCompanyInformationForBankAccount with the website data as "https://", which is an invalid value. As a result, the backend returns an Onyx error:

```
{
    "onyxMethod": "merge",
    "key": "reimbursementAccount",
    "value": {
        "errors": {
            "1727918521418387": "Please provide a valid Website"
        }
    }
}
```

- So the "Please provide a valid Website" error message is shown.
### What changes do you think we should make in order to solve the problem?
- When we are in company website page and go back, we need to clear the ```reimbursementAccountDraft.website``` if its value is ```https://```.

- So in [here](https://github.com/Expensify/App/blob/3b15d846bbe591631f05604fd6a512c2acbd6247/src/pages/ReimbursementAccount/BusinessInfo/substeps/WebsiteBusiness.tsx#L28) we introduce a ref ```const websiteRef = useRef()``` to keep track the company website input. Then add ```onChangeText={(t) => (websiteRef.current = t)}``` to [InputWrapper](https://github.com/Expensify/App/blob/3b15d846bbe591631f05604fd6a512c2acbd6247/src/pages/ReimbursementAccount/BusinessInfo/substeps/WebsiteBusiness.tsx#L64).

- Finally, add cleanup function:

```
    useEffect(() => {
        return () => {
            if (defaultWebsiteExample === websiteRef.current) {
                BankAccounts.addBusinessWebsiteForDraft(null);
            }
        };
    }, []);
```
### What alternative solutions did you explore? (Optional)

- The above useEffect can be:

```
    useEffect(() => {
        return () => {
            if (!ValidationUtils.isValidWebsite(values.website)) {
                BankAccounts.addBusinessWebsiteForDraft(null);
            }
        };
    }, []);
```

**Comment by Gajendra-Gupta** [comment] 2024-10-07 13:54
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
Bank Account - "Please provide a valid website" error is shown
### What is the root cause of that problem?
Error is not clearing at the time of previous page.
https://github.com/Expensify/App/blob/3b15d846bbe591631f05604fd6a512c2acbd6247/src/pages/ReimbursementAccount/BusinessInfo/BusinessInfo.tsx#L111-L113
### What changes do you think we should make in order to solve the problem?
Code should be like this
```
 } else {
 FormActions.clearErrorFields(formId);
 FormActions.clearErrors(formId); 
     prevScreen(); 
 }
```

### What alternative solutions did you explore? (Optional)

**Comment by techievivek** [comment] 2024-10-14 07:29
Not overdue, issue is assigned to @mkzie2

**Comment by anmurali** [comment] 2024-11-06 01:40
@ishpaul777 is paid
@mkzie2 - your offer is [here](https://www.upwork.com/nx/wm/offer/104760809)

**Comment by mkzie2** [comment] 2024-11-07 04:48
> @mkzie2 - your offer is [here](https://www.upwork.com/nx/wm/offer/104760809)

@anmurali I accepted, it can be paid out and closed

**Closed** 2024-11-12 02:51 UTC
Labels: External, Daily, Overdue, Awaiting Payment, Bug
