### ISSUE TITLE
[HOLD for checklist] [$1000] Web -  Pressing the Pin/Unpin option from the LHN context menu does not refocus the composer.

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#21861] opened 2023-06-29 11:51 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Open App and go to any chat
2. On LHN, Right click on any user's chat to Open the context menu
3. Press Pin/Unpin option

## Expected Result:
After pressing on the pin/unpin then composer should be refocused, as the same happens After pressing on the mark as read/unread option from the LHN context menu

## Actual Result:
After Pressing the pin/unpin option, Composer is not refocused.

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [x] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 1.3.33-4
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/93399543/ecea8b4f-585a-4984-8f5a-3e57c39946b8

https://github.com/Expensify/App/assets/93399543/a5631da0-d0cd-4975-b0ef-870d618dad1f

**Expensify/Expensify Issue URL:**
**Issue reported by:** @jayeshmangwani
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1687938349897719

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01fc6f96ae79d98073</li>
        <li>Upwork Job ID: 1674685137307795456</li>
        <li>Last Price Increase: 2023-07-07</li>
    </ul>
</details>

**Comment by kbecciv** [comment] 2023-06-29 11:52
## Proposal
from @jayeshmangwani

### Please re-state the problem that we are trying to solve in this issue.
Pressing the Pin/Unpin option from the LHN context menu does not refocus the composer

### What is the root cause of that problem?
On press of the Pin and Unpin buttons we only hide the Context Menu, we do not call the refocus of the Composer.

https://github.com/Expensify/App/blob/94e265653f83505e581e99ac0ec0d3ea30e23998/src/pages/home/report/ContextMenu/ContextMenuActions.js#L300-L302

https://github.com/Expensify/App/blob/94e265653f83505e581e99ac0ec0d3ea30e23998/src/pages/home/report/ContextMenu/ContextMenuActions.js#L313-L315

### What changes do you think we should make in order to solve the problem?
When we press the Pin and Unpin buttons, then we need to call the ReportActionComposeFocusManager.focus, like same, we do for Mark As Read button


Need to update this code at these two places

```javascript
    hideContextMenu(false); // OLD
    hideContextMenu(true, ReportActionComposeFocusManager.focus); // NEW
```
https://github.com/Expensify/App/blob/94e265653f83505e581e99ac0ec0d3ea30e23998/src/pages/home/report/ContextMenu/ContextMenuActions.js#L313-L315

https://github.com/Expensify/App/blob/94e265653f83505e581e99ac0ec0d3ea30e23998/src/pages/home/report/ContextMenu/ContextMenuActions.js#L300-L302

**Comment by jayeshmangwani** [comment] 2023-06-29 11:54
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
Pressing the Pin/Unpin option from the LHN context menu does not refocus the composer

### What is the root cause of that problem?
On press of the Pin and Unpin buttons we only hide the Context Menu, we do not call the refocus of the Composer.

https://github.com/Expensify/App/blob/94e265653f83505e581e99ac0ec0d3ea30e23998/src/pages/home/report/ContextMenu/ContextMenuActions.js#L300-L302

https://github.com/Expensify/App/blob/94e265653f83505e581e99ac0ec0d3ea30e23998/src/pages/home/report/ContextMenu/ContextMenuActions.js#L313-L315

### What changes do you think we should make in order to solve the problem?
When we press the Pin and Unpin buttons, then we need to call the ReportActionComposeFocusManager.focus, like same, we do for Mark As Read button


Need to update this code at these two places

```javascript
    hideContextMenu(false); // OLD
    hideContextMenu(true, ReportActionComposeFocusManager.focus); // NEW
```
https://github.com/Expensify/App/blob/94e265653f83505e581e99ac0ec0d3ea30e23998/src/pages/home/report/ContextMenu/ContextMenuActions.js#L313-L315

https://github.com/Expensify/App/blob/94e265653f83505e581e99ac0ec0d3ea30e23998/src/pages/home/report/ContextMenu/ContextMenuActions.js#L300-L302

**Comment by greg-schroeder** [comment] 2023-06-30 07:43
Reproduced, seems like it should match the Read/Unread behavior to me

**Comment by abdulrahuman5196** [comment] 2023-06-30 14:38
@greg-schroeder  I have doubts on the requirements. I agree we have to improve the experience with consistency here, but wanted to confirm on the expectation.
The current `Mark as unread` in LHN works like if we use it on any chat the current open is getting focused not the chat which we marked as unread.

So pin/unpin any LHN item should focus current composer? Is this what we want?

**Comment by greg-schroeder** [comment] 2023-07-04 11:50
@abdulrahuman5196 Hmm. I mean I think it should, right? To me it feels more natural that the composer is focused after the LHN action is complete - when nothing is focused it doesn't feel right. And so I think it should be the currently selected chat, yes.

Do you not agree?

**Comment by greg-schroeder** [comment] 2023-07-07 08:09
bump on the above

**Comment by abdulrahuman5196** [comment] 2023-07-07 17:13
@greg-schroeder Agree on the above - https://github.com/Expensify/App/issues/21861#issuecomment-1620101062

Then as per the expectation @jayeshmangwani 's proposal here https://github.com/Expensify/App/issues/21861#issuecomment-1613003863 looks good and works well.

🎀 👀 🎀
C+ Reviewed

cc: @greg-schroeder

**Comment by abdulrahuman5196** [comment] 2023-07-07 17:13
🎀 👀 🎀 C+ reviewed

**Comment by abdulrahuman5196** [comment] 2023-07-07 17:15
Sorry. @cristipaval The c+ reviewed comment was pasted twice which assigned you as a reviewer.

**Comment by abdulrahuman5196** [comment] 2023-07-07 17:22
@Beamanator  C+ approved comment is here https://github.com/Expensify/App/issues/21861#issuecomment-1625707231

**Comment by Beamanator** [comment] 2023-07-10 09:47
I agree with the problem & solution 👍 

@greg-schroeder can we make sure this gets into Test Rail or something? :D I keep seeing these types of issues pop up, which means we probably don't have this flow in test rail right?

**Comment by jayeshmangwani** [comment] 2023-07-10 11:51
[PR](https://github.com/Expensify/App/pull/22549) is ready for review

cc: @abdulrahuman5196

**Comment by greg-schroeder** [comment] 2023-07-11 03:02
> I agree with the problem & solution 👍
> 
> @greg-schroeder can we make sure this gets into Test Rail or something? :D I keep seeing these types of issues pop up, which means we probably don't have this flow in test rail right?

Certainly. @abdulrahuman5196 let's make sure when completing the checklist for this issue that we definitely add a robust regression test in testrail

**Comment by greg-schroeder** [comment] 2023-07-21 21:35
Payments complete. Just looking for the checklist to be completed cc @abdulrahuman5196 

Let's keep https://github.com/Expensify/App/issues/21861#issuecomment-1628609690 in mind as well

**Comment by abdulrahuman5196** [comment] 2023-07-22 13:51
@greg-schroeder Thank you for quickly processing the payment. Sorry for the delay. Completed checklist now.

>The PR that introduced the bug has been identified. Link to the PR:
The offending PR has been commented on, pointing out the bug it caused and why, so the author and reviewers can learn from the mistake. Link to comment:
A discussion in #expensify-bugs has been started about whether any other steps should be taken (e.g. updating the PR review checklist) in order to catch this type of bug sooner. Link to discussion:

This was not present during initial implementation of PIn/Unpin option. Made the a comment on the same - https://github.com/Expensify/App/pull/16079#issuecomment-1646588413

>Determine if we should create a regression test for this bug.

Yes

>If we decide to create a [regression test](https://github.com/Expensify/App/blob/main/contributingGuides/REGRESSION_TEST_BEST_PRACTICES.md) for the bug, please propose the regression test steps to ensure the same bug will not reach production again.


1) Open App and go to any chat
2) On LHN, Right click on any user's chat to Open the context menu
3) Press Pin/Unpin option
4) Verify that after pressing on the pin/unpin composer should be refocused

**Comment by greg-schroeder** [comment] 2023-07-25 18:20
Thanks @abdulrahuman5196! Taking care of filing that and closing this out.

**Closed by greg-schroeder** 2023-07-25 18:20 UTC
Labels: External, Daily, Overdue, Bug
