### ISSUE TITLE
[$500] Chat - Mention suggestions doesn't popup between special characters like "__" or "~~"

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#28753] opened 2023-10-03 21:20 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Open any report
2. Type "~~" first and then move cursor in between them
3. Type @
4. Observe mention suggestions doesn't popup

## Expected Result:
Mention suggestions should popup.

## Actual Result:
Mention suggestions doesn't popup.

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android / native
- [x] Android / Chrome
- [x] iOS / native
- [x] iOS / Safari
- [x] MacOS / Chrome / Safari
- [x] MacOS / Desktop

**Version Number:** 1.3.77.2
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/93399543/8120ec57-5bec-4a10-80de-6c1cbac97a3d

https://github.com/Expensify/App/assets/93399543/6c91df11-e65a-4070-8a79-e0c83199a2d3

https://github.com/Expensify/App/assets/93399543/c7ec7448-5303-4ad7-81e8-3623639805d1

**Expensify/Expensify Issue URL:**
**Issue reported by:** @Krishna2323 
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1696276572247999

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01f136e024c3582511</li>
        <li>Upwork Job ID: 1709317632314040320</li>
        <li>Last Price Increase: 2023-10-10</li>
    </ul>
</details>

**Comment by kbecciv** [comment] 2023-10-03 21:21
Proposal by: @Krishna2323
Slack conversation: https://expensify.slack.com/archives/C049HHMV9SM/p1696276572247999

### Proposal

### Please re-state the problem that we are trying to solve in this issue.
User suggestions doesn't popup between "~~" & "__"

### What is the root cause of that problem?
We are not extracting words correctly from `leftString` in `SuggestionMention`, but we are doing it correctly in `SuggestionEmoji` file.

**_`SuggestionMention:`_**
https://github.com/Expensify/App/blob/a4b3669ea310f637638445b3c61c99f52871dfcf/src/pages/home/report/ReportActionCompose/SuggestionMention.js#L202 

**_`SuggestionEmoji:`_**
https://github.com/Expensify/App/blob/a4b3669ea310f637638445b3c61c99f52871dfcf/src/pages/home/report/ReportActionCompose/SuggestionEmoji.js#L21

### What changes do you think we should make in order to solve the problem?
We should extract works from `leftString` just like we are doing in  `SuggestionEmoji`.

`const words = leftString.slice(0, selectionEnd).split(CONST.REGEX.SPECIAL_CHAR_OR_EMOJI);`

We also need to adjust `commentAfterAtSignWithMentionRemoved`, otherwise it will replace a character just after it.

**_Current Code:_**
https://github.com/Expensify/App/blob/a4b3669ea310f637638445b3c61c99f52871dfcf/src/pages/home/report/ReportActionCompose/SuggestionMention.js#L81

**_Updated Code:_**
`const commentAfterAtSignWithMentionRemoved = value.slice(selection.end).replace(CONST.REGEX.MENTION_REPLACER, '');`

### Result

https://github.com/Expensify/App/assets/85894871/be9df719-6de4-42d5-8d61-25ae44893e80

**Comment by Christinadobrzyn** [comment] 2023-10-03 23:18
I can reproduce, a similar(ish) report here - https://github.com/Expensify/App/issues/28754 I wonder if these can be fixed with the same root. @Ollyws let me know what you think!

**Comment by Christinadobrzyn** [comment] 2023-10-06 17:47
Just to confirm what to do next with this GH. Should it stay open or can it be closed?

**Comment by Christinadobrzyn** [comment] 2023-10-10 17:53
Oh that's a good point @parasharrajat! 

Do I have this right? 

re: https://github.com/Expensify/App/issues/24226
- This [PR](https://github.com/Expensify/App/pull/28045#issuecomment-1743444462) was deployed to production on Oct 2nd. 
- This [PR](https://github.com/Expensify/App/pull/28045#issuecomment-1743444462)  is to prohibit popup mentions when there isn't a space between @ and another text/symbol. 

VS. 

- This GH was reported on Oct 3. 
- This GH is to have popup mentions whenever @ is used, independent of spacing (right?)

So they are conflicting, correct? 

I guess since we decided on https://github.com/Expensify/App/issues/24226 behaviour, this GH isn't a bug (as @thesahindia and @akamefi202 mentioned).

**Comment by Christinadobrzyn** [comment] 2023-10-11 20:14
Gonna close this but feel free to reopen if you think we're missing something.

**Closed by Christinadobrzyn** 2023-10-11 20:14 UTC
Labels: External, Daily, Help Wanted, Bug
