### ISSUE TITLE
[$500]  IOU Report - User is sent to blinking/flashing screen after opening sent IOR request

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#30282] opened 2023-10-24 17:17 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.3.90-1

**Reproducible in staging?:** Yes

**Reproducible in production?:** No

**If this was caught during regression testing, add the test name, ID and link from TestRail:**

**Email or phone of affected tester (no customers):**

**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Expensify/Expensify Issue URL:**

**Issue reported by:** Applause - Internal Team

**Slack conversation:**

## Action Performed:
1. Using two accounts, using User A, send IOU request to User B
2. Using User B, open IOU preview and click on individual request(Red Dot appears with report on LHN)
3. Log out and back in User B and open request

## Expected Result:
User is able to open request and view IOU details

## Actual Result:
Blinking page is shown after clicking on report
"Hmm, nothing is here" occurs on occasion instead of blinking page or red dot in LHN

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [x] Android: mWeb Chrome
- [x] iOS: Native
- [x] iOS: mWeb Safari
- [x] Windows: Chrome 
- [x] MacOS: Desktop

## Screenshots/Videos
<details>
<summary>Android: Native</summary>

  

https://github.com/Expensify/App/assets/78819774/23008d7a-3ed4-4ccc-a5ff-7e35f6229c35

</details>

<details>
<summary>Android: mWeb Chrome</summary>

 

https://github.com/Expensify/App/assets/78819774/2560a869-394c-4dfe-96c1-1800c6c0dad1

</details>

<details>
<summary>iOS: Native</summary>

</details>

<details>
<summary>iOS: mWeb Safari</summary>

</details>

<details>
<summary>MacOS: Chrome / Safari</summary>

 

https://github.com/Expensify/App/assets/78819774/11b552ec-4119-4d7b-a1a7-a8f8617f23b6

</details>

<details>
<summary>MacOS: Desktop</summary>

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~0134567ff2a3f3bab0</li>
        <li>Upwork Job ID: 1716926610572148736</li>
        <li>Last Price Increase: 2023-10-31</li>
    </ul>
</details>

**Comment by AndrewGable** [comment] 2023-10-24 17:40
Can you reproduce @greg-schroeder ?

**Comment by AndrewGable** [comment] 2023-10-24 19:24
I think @danielrvidal says he is seeing this in production, can you confirm @lanitochka17 ?

**Comment by AndrewGable** [comment] 2023-10-24 21:16
Demoting to normal bug as [this is happening on production according to this](https://github.com/Expensify/App/issues/30282#issuecomment-1777886411)!

**Comment by Jenemark** [comment] 2023-10-25 07:54
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
The application blinks when clicking report on the LHN, the indicator also turns red.

### What is the root cause of that problem?
The root cause seems to be on the side of OnyxData, when running the app in localhost it works as expected.
Can also be tested by copying the curl for the HTTP request and changing [staging](https://staging.new.expensify.com/) with your localhost:8082. (Do this in Postman, Insomnia, etc...) The http always seems to fail on non localhost. Even if the page is actually showing, the response body returns with an error.

The error body from the HTTP response:

```{
	"code": 666,
	"jsonCode": 404,
	"type": "Expensify\\Libs\\Error\\ExpError",
	"UUID": "b9114bf5-a67c-44a3-b0f3-b4a27fab05f2",
	"message": "Policy does not exist or you do not have access. Try refreshing the page.",
	"title": "Policy Inaccessible",
	"data": {
		"onyxData": [
			{
				"onyxMethod": "merge",
				"key": "report_4361403564968695",
				"value": {
					"errorFields": {
						"createChat": {
							"1698219760662790": "Policy does not exist or you do not have access. Try refreshing the page."
						}
					}
				}
			}
		]
	},
	"htmlMessage": "",
	"onyxData": [
		{
			"onyxMethod": "merge",
			"key": "report_4361403564968695",
			"value": {
				"errorFields": {
					"createChat": {
						"1698219760662790": "Policy does not exist or you do not have access. Try refreshing the page."
					}
				}
			}
		}
	],
	"requestID": "81b8d2ff582e10b1-CPH"
}```

### What changes do you think we should make in order to solve the problem?
This could be a certificate or policy issue on the backend endpoint not allowing access from the staging/production. Without having access to the backend an actual fix for this will be hard to implement.

### What alternative solutions did you explore? (Optional)

**Comment by hungvu193** [comment] 2023-10-27 09:36
Here's the issue about retry logic and I think it's being handled here:
https://github.com/Expensify/App/issues/13667

**Comment by greg-schroeder** [comment] 2023-10-27 16:50
@hungvu193 are you suggesting we hold for the linked issue?

**Comment by hungvu193** [comment] 2023-10-27 16:51
> @hungvu193 are you suggesting we hold for the linked issue?

I believe so, but can you please post this issue into that thread, just to confirm.

**Comment by AndrewGable** [comment] 2023-10-31 22:49
Any updates here @hoangzinh or @greg-schroeder ? Thanks

**Comment by AndrewGable** [comment] 2023-11-06 23:08
Marking internal for now!

**Comment by greg-schroeder** [comment] 2023-11-09 11:30
This is internal now as it's a BE issue, Expensify engineer will work on shortly

**Comment by greg-schroeder** [comment] 2023-11-13 09:32
Same as above

**Comment by AndrewGable** [comment] 2023-11-16 21:09
I'll look at it soon-ish, I want to make sure it still happens before digging into too deep.

**Comment by mvtglobally** [comment] 2023-11-18 04:31
Issue not reproducible during KI retests. (First week)

**Comment by greg-schroeder** [comment] 2023-11-21 18:22
Ah, I think you're right.

**Comment by greg-schroeder** [comment] 2023-11-21 18:22
I'm going to close, then.

**Closed by greg-schroeder** 2023-11-21 18:22 UTC
Labels: Engineering, Daily, Internal, Bug
