### ISSUE TITLE
[$500] [Wave 6: Workspace Chats] There’s no offline next steps banner, just blank.

### ISSUE THREAD

**Issue by Christinadobrzyn** [Expensify/App#33450] opened 2023-12-21 20:52 UTC
**Slack conversation:** https://expensify.slack.com/archives/C02MW39LT9N/p1703191424265509?thread_ts=1703187017.215259&cid=C02MW39LT9N

## Action Performed:

1. As the member, go to NewDot
2. Go to global create (`+`) > Request money > enter an amount > confirm
2. Navigate to the expense report view
3. Go offline
4. Tap the `Submit` button
• Verify the report is optimistically submitted :white_check_mark:
• Verify the text in the next steps banner updates to: “The details of the next steps will update when you’re back online.” :x:
7. Go back online
• Verify the report is submitted successfully :white_check_mark:
• Verify the next steps banner text updates to: “Waiting for %approverName% to review these expenses” :white_check_mark:

## Expected Result:

There should be an offline message about next steps for a report "The details of the next steps will update when you’re back online.”"

## Actual Result:

There's no offline message

## Screenshots/Videos

<img width="921" alt="image" src="https://github.com/Expensify/App/assets/51066321/fc5f1003-9eb2-4a6f-b355-ef638ed47b9a">

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~014e89ba23323a2eac</li>
        <li>Upwork Job ID: 1742850033352990720</li>
        <li>Last Price Increase: 2024-01-04</li>
    </ul>
</details>

**Comment by dylanexpensify** [comment] 2024-01-04 10:06
sorry, was ooo! confirmed!

**Comment by rojiphil** [comment] 2024-01-04 11:18
## Proposal

### Please re-state the problem that we are trying to solve in this issue.

There are no offline `next steps` banner. 

### What is the root cause of that problem?

This is a new feature. 
Currently, `Next Step` banner is displayed only through `reportNextStep_` onyx entries sent from BE as shown below.

![Screenshot 2024-01-04 at 4 18 40 PM](https://github.com/Expensify/App/assets/3004659/aec19761-3b3b-44b5-80b6-0cade350fd96)
 
We do not optimistically create these when expense reports are submitted offline for collect workspaces. 

### What changes do you think we should make in order to solve the problem?

We can optimistically generate a minimal version of `reportNextStep_` Onyx entry that contains the message “The details of the next steps will update when you’re back online.”

We can make this change within `submitReport` by adding this to `optimisticData` [here](https://github.com/Expensify/App/blob/dc3e19bdcc95023d74cd7fdd433f6208707eaaf8/src/libs/actions/IOU.js#L3055)

### What alternative solutions did you explore? (Optional)

**Comment by bernhardoj** [comment] 2024-01-04 11:43
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
If we submit the expense report while offline, we don't see any next step banner.

### What is the root cause of that problem?
This is more like a new feature. When we submit a report, we optimistically clear the next step, 
https://github.com/Expensify/App/blob/dc3e19bdcc95023d74cd7fdd433f6208707eaaf8/src/libs/actions/IOU.js#L3139-L3144
and the BE is supposed to give us a new next step, but currently, it only happens after we reopen the report.

Now, we want to show a next step banner while offline telling the user that the next step will be shown after going back online.

### What changes do you think we should make in order to solve the problem?

The strategy is, that if we are offline and the current next step is empty, we want to show the "pending" next step.
```
(apply below changes to MoneyReportHeader)
const shouldShowPendingNextStep = isOffline && _.isEmpty(nextStepProp.message);
const nextStep = shouldShowPendingNextStep ? NextStepUtils.getPendingNextStep() : nextStepProp;
```

The next step utils new function will look like this:
```
function getPendingNextStep(): ReportNextStep {
    return {
        type: null,
        message: [{text: "The details of the next steps will update when you’re back online."}]
    };
}
```

**Comment by mountiny** [comment] 2024-01-04 17:01
I am going to close this one in favour of more general optimistic next steps https://github.com/Expensify/App/issues/28771 issue

There is many granular things which need to be updated for the next steps so no reason to keep it separate

**Closed by mountiny** 2024-01-04 17:01 UTC
Labels: External, Daily, Help Wanted, Bug
