### ISSUE TITLE
[HOLD for payment 2024-01-03] [HOLD for payment 2024-01-02] The new search component is slower and animation to open it isn’t smooth

### ISSUE THREAD

**Issue by m-natarajan** [Expensify/App#33326] opened 2023-12-19 22:49 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.14.1
**Reproducible in staging?:** y
**Reproducible in production?:** n
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** @puneetlath 
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1703015444761109

## Action Performed:
1. Open app
2. Tap search button

## Expected Result:
Search page opens without delay and animation is smooth

## Actual Result:
The new search component seems to be a little slower. The animation to open it isn’t smooth and it just feels a little sluggish

## Workaround:
unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [x] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

https://github.com/Expensify/App/assets/38435837/7a83dee4-a4f6-458e-b76f-418a6cebc379

https://github.com/Expensify/App/assets/38435837/8a4841c0-110e-403a-8277-c6528c4de5ce

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by jasperhuangg** [comment] 2023-12-20 05:34
@deetergp it seems the PR you linked only adds a new Search component to the storybook, and not the actual app, so I'm doubtful as to whether that is the cause.

**Comment by jasperhuangg** [comment] 2023-12-20 05:38
I suspect https://github.com/Expensify/App/pull/33218 is related, since it has to do with the animation of opening the left hand search pane.

**Comment by jasperhuangg** [comment] 2023-12-21 00:54
This was actually fixed by this revert: https://github.com/Expensify/App/pull/33297 closing

**Comment by deetergp** [comment] 2023-12-21 01:03
A lot of the changes from

**Comment by jasperhuangg** [comment] 2023-12-21 01:04
@deetergp I was wrong, I think it might have actually been caused by us moving the Search Page to the LHN

**Comment by deetergp** [comment] 2023-12-21 01:09
Should we revert it then? Did you check out the performance of both staging and prod? They really don't feel that different to me. Neither seem slower than they've ever been to me.

**Comment by jasperhuangg** [comment] 2023-12-21 01:14
@deetergp there's a pretty distinct delay on staging when you first open the search page (it needs to be on a fresh tab, so if it isn't happening for you close the tab and reopen it)


https://github.com/Expensify/App/assets/31285285/767df482-5343-4202-b574-b8cfefcc2701

**Comment by jasperhuangg** [comment] 2023-12-21 01:29
I have no idea why this is happening–I'm going to remove the deploy blocker label for now but this is definitely something we need to fix.

**Comment by mountiny** [comment] 2023-12-21 09:59
This PR should have helped a bit but its not the root cause https://github.com/Expensify/App/pull/33399

@kacper-mikolajczak is looking into this issue too

**Comment by marcaaron** [comment] 2023-12-21 18:43
One idea... could be because we are not doing the `isEquals()` checks anymore. Possibly we are calculating the options too many times.

https://github.com/Expensify/App/blob/ab3d0e876e311ed1ce3cd859ad6dd77a5d8e3cdf/src/pages/SearchPage.js#L70-L75

Now we have this which could be too aggressive:

https://github.com/Expensify/App/blob/0a6c4e787afb665655c5e9b05eabcdfee11ae7f2/src/pages/SearchPage.js#L80-L82

**Comment by sakluger** [comment] 2023-12-21 18:51
FYI, search is unusable for me right now in NewDot. The whole app freezes for like 30 seconds after I click the search icon or click Command+K, then another 15-30 before I can type. Then when I click on a result, it sometimers goes to the wrong chat.

I tried searching with the Developer Network tab open. Nothing shows up while it's frozen, then after it loads, it doesn't show anything helpful, mostly just `api?command=Ping` commands and some images. Here's what loaded in Network after around a minute or more once the search finally loaded:

![image](https://github.com/Expensify/App/assets/5997400/20d98ab4-b5d3-4107-9f06-140bc81cfd1b)

I think we should consider reverting whatever may have caused this, my NewDot is basically bricked.

**Comment by situchan** [comment] 2023-12-21 18:53
Seems like offending PR was found and being reverted here - #33438

**Comment by mountiny** [comment] 2023-12-22 16:29
This is still an issue, seems like we have narrowed it down for changes in the phone number regex

**Comment by mountiny** [comment] 2023-12-27 16:25
This can be closed now I think

**Closed by mountiny** 2023-12-27 16:25 UTC
Labels: Engineering, Weekly, Awaiting Payment, Bug
