### ISSUE TITLE
[$250] New Room -  Incorrect error message is displayed for the empty field under room name.

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#12482] opened 2022-11-04 19:47 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Issue found when executing PR** https://github.com/Expensify/App/pull/12184

## Action Performed:
1.Go to staging.new.expensify.com
2. Log in with expensifail account
3. Click on Fub menu
4. Select New Room
5. Click Save
6. Check error messages under Room name

## Expected Result:
Correct error message is displayed for the empty field under room name.

## Actual Result:
Incorrect error message is displayed for the empty field under room name.

## Workaround:
Unknown

## Platform:

Where is this issue occurring?

- Web
- iOS
- Android
- Desktop App
- Mobile Web

**Version Number:** 1.2.24.0

**Reproducible in staging?:** Yes

**Reproducible in production?:** Yes

**Email or phone of affected tester (no customers):** 

**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Notes/Photos/Videos:** Any additional supporting documentation

![image (28)](https://user-images.githubusercontent.com/93399543/200062280-c9fe32d3-4bec-4702-afaa-f867eed9d743.png)

**Expensify/Expensify Issue URL:** 

**Issue reported by:** Applause - Internal Team

**Slack conversation:** 

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by zanyrenney** [comment] 2022-11-07 17:57
@kbecciv - please can you clarify what you mean by the FUB menu, I don't know what that is.

**Comment by kbecciv** [comment] 2022-11-07 17:58
Green plus button in LHN

**Comment by zanyrenney** [comment] 2022-11-11 10:43
I'm ooo but this doesn't seem urgent so will get to it when I am back on Monday.

**Comment by nurlanmen502** [comment] 2022-11-14 17:41
![image](https://user-images.githubusercontent.com/117958168/201728781-2c782c1a-8282-4ece-aecb-daaac206b130.png)
How could we create "Room"?
I am unable to see "Room" when click FUB button.

**Comment by zanyrenney** [comment] 2022-11-14 17:51
Going to look into this more tomorrow.

**Comment by nurlanmen502** [comment] 2022-11-14 21:06
@kbecciv can you upload video instead of screenshot?
I am unable to re-produce on my dev.

**Comment by kbecciv** [comment] 2022-11-14 21:09
Please check the video.

https://user-images.githubusercontent.com/93399543/201766022-c27084ee-2029-4341-acb9-0586ba682e75.mp4

**Comment by peterklamka** [comment] 2022-11-15 00:10
@kbecciv could I get expensifail account for testing?

**Comment by Santhosh-Sellavel** [comment] 2022-11-15 00:49
This doesn't require expensifail account, please check readme understand about our app codebase, you will get to know what to do!

**Comment by devenus98** [comment] 2022-11-15 19:05
@Santhosh-Sellavel Yes, I updated Permissions.js and was able to create "New Room", but I can't reproduce issue.
@kbecciv this issue happens always?

**Comment by kbecciv** [comment] 2022-11-15 21:38
@devenus98 Yes, every time for domain (expensifail) accounts.

**Comment by mountiny** [comment] 2022-11-15 22:15
I cannot repro on my account 
<img width="374" alt="image" src="https://user-images.githubusercontent.com/36083550/202036321-6a060d3c-7a50-4c82-8387-2a142a7181e0.png">

@kbecciv it might be that this room already exists from some past testing on your domain. Can you try with account with a new domain?

**Comment by mountiny** [comment] 2022-11-15 22:15
Removing Help wanted in the meantime

**Comment by mountiny** [comment] 2022-11-17 18:44
Same with new account, same with my expensify account. 
<img width="377" alt="image" src="https://user-images.githubusercontent.com/36083550/202531566-28dd9dfa-53fb-4a90-965d-f836abe84591.png">


I cannot reproduce so closing this.

**Closed by mountiny** 2022-11-17 18:44 UTC
Labels: External, Daily, Bug
