### ISSUE TITLE
[$250] Chat - Contacts with no display name appear on top after searching for member during IOU flow

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#39642] opened 2024-04-04 19:07 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.60-5
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**If this was caught during regression testing, add the test name, ID and link from TestRail:** N/A*
**Issue reported by:** Applause - Internal Team

## Action Performed:
1. Go to staging.new.expensify.com and log in with Expensifail account that has many contacts
2. Go to FAB > Request money > Manual
3. Enter amount
4. Search for a member using search field > Select the member. (Important step)
5. On confirmation page, close the RHP
6. Go to FAB > Start chat

## Expected Result:
The contact list in Step 6 will have the same list as Step 4

## Actual Result:
There are contacts with blank display name on top of the list

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [x] Android: mWeb Chrome
- [x] iOS: Native
- [x] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details> 

https://github.com/Expensify/App/assets/78819774/086224bb-2312-40e7-b52d-fbcdc8113b83

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01d4e2c2f15597586e</li>
        <li>Upwork Job ID: 1776072508499795968</li>
        <li>Last Price Increase: 2024-04-05</li>
<li>Automatic offers: </li>
<ul>
<li>rayane-djouah | Reviewer | 0</li>
</ul></li>
    </ul>
</details>

**Comment by lanitochka17** [comment] 2024-04-04 19:07
@jliexpensify  FYI I haven't added the External label as I wasn't 100% sure about this issue. Please take a look and add the label if you agree it's a bug and can be handled by external contributors

**Comment by lanitochka17** [comment] 2024-04-04 19:07
We think that this bug might be related to #vip-vsp

**Comment by jliexpensify** [comment] 2024-04-05 02:20
This should be in #collect as it deals with Workspace Requests.

The actual bug itself is the fact that some emails show up without names:

![image](https://github.com/Expensify/App/assets/30815269/ce2fb39c-655c-402c-a2fd-fc622b1df2c6)

Whereas they should always show up with bold names, even if it's just an email:

![image](https://github.com/Expensify/App/assets/30815269/ccf52e36-8579-4218-8485-0fe90de379ac)

**Comment by trjExpensify** [comment] 2024-04-05 12:46
Weird. Anyone got an RCA on which PR has introduced this? I would think it must be a problem with the OptionSelector everywhere we use it.

**Comment by VickyStash** [comment] 2024-04-05 13:14
Hi, I'm Viktoryia from Callstack - expert contributor group - and I would like to work on this issue.

**Comment by trjExpensify** [comment] 2024-04-05 14:22
Done!

**Comment by VickyStash** [comment] 2024-04-05 15:23
## Proposal
### Please re-state the problem that we are trying to solve in this issue.
Contacts with no display name appear on top of the list after searching for member during IOU flow.
### What is the root cause of that problem?
The root problem seems to be in [READ_COMMANDS.SEARCH_FOR_REPORTS](https://github.com/Expensify/App/blob/c871dfd1848e14489ee0995d7db566fd1f81704c/src/libs/actions/Report.ts#L2872) api call inside [searchForReports](https://github.com/Expensify/App/blob/c871dfd1848e14489ee0995d7db566fd1f81704c/src/libs/actions/Report.ts#L2847) function.
After mentioned api request is called `displayName` for some users turns into `' '`, which make them to be shown at the top of the contacts list with empty text.
### What changes do you think we should make in order to solve the problem?
The `SearchForReports` API needs to be fixed in order to retrieve the correct data. Specifically, `displayName` field of the user’s personal data must always contain its display name instead of `' '`.

### Screenshots / recordings
Video recording of the search with/without [READ_COMMANDS.SEARCH_FOR_REPORTS](https://github.com/Expensify/App/blob/c871dfd1848e14489ee0995d7db566fd1f81704c/src/libs/actions/Report.ts#L2872) api call commented:

https://github.com/Expensify/App/assets/23176449/da1c4989-ddb6-411b-bf14-8484634d7abf


Screenshots of user personal details before/after calling mentioned API call:
![image (3)](https://github.com/Expensify/App/assets/23176449/254dfe6b-a843-4dfe-9354-f16291635551)
![image (4)](https://github.com/Expensify/App/assets/23176449/b40991a5-f9bd-494a-aeee-2c108126204e)

**Comment by jliexpensify** [comment] 2024-04-07 21:52
Done, cheers!

**Comment by jliexpensify** [comment] 2024-04-10 01:09
Thank you @rayane-djouah!

**Comment by jliexpensify** [comment] 2024-04-13 00:38
Not overdue

**Comment by jliexpensify** [comment] 2024-04-16 04:41
Hi @VickyStash - any ETA's you can share? Thanks!

**Comment by VickyStash** [comment] 2024-04-16 07:25
@jliexpensify Since it seems to be a back-end [issue](https://github.com/Expensify/App/issues/39642#issuecomment-2041549368), it should be fixed internally. So I guess an internal engineer should be assigned. Thank you!

**Comment by jliexpensify** [comment] 2024-04-16 10:17
Got it, so did you want to continue to be assigned this issue then @VickyStash?

**Comment by VickyStash** [comment] 2024-04-16 10:37
@jliexpensify No need I believe, so I've unassigned myself

**Comment by jliexpensify** [comment] 2024-04-19 01:45
Not overdue, waiting on an engineer.

**Comment by jliexpensify** [comment] 2024-04-22 23:11
Not overdue

**Comment by jliexpensify** [comment] 2024-05-03 04:14
Not overdue!

**Comment by chiragsalian** [comment] 2024-05-09 22:56
oh odd, the code for this went live 2 weeks back. Closing the issue since it should be resolved now.

**Closed by chiragsalian** 2024-05-09 22:56 UTC
Labels: Reviewing, Engineering, Daily, Internal, Bug
