### ISSUE TITLE
[HOLD 2023-10-16] [$125] mweb/Safari - Composer - Cursor does not moved to a new line in the composer when tapped on the "return"

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#28501] opened 2023-09-29 15:42 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___
**Issue found when executing PR** https://github.com/Expensify/App/pull/27490
## Action Performed:
1. Open https://staging.new.expensify.com/
2. Tap on any listed conversation in LHN
3. Tap on the composer box
4. Write any words
5. Tap on the "return" button on keayboard

## Expected Result:
Cursor should be moved to a new line

## Actual Result:
Nothing happened. The cursor remains on the same line

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [x] iOS / Safari
- [ ] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 1.3.75-0

**Reproducible in staging?:** Yes

**Reproducible in production?:** No 

**If this was caught during regression testing, add the test name, ID and link from TestRail:**

**Email or phone of affected tester (no customers):**

**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/78819774/3c0ce33f-5d9f-43cf-990b-d36000dc60f3

**Expensify/Expensify Issue URL:**

**Issue reported by:** Applause - Internal Team

**Slack conversation:**

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01a307034471edf3f5</li>
        <li>Upwork Job ID: 1713885684306395136</li>
        <li>Last Price Increase: 2023-10-16</li>
    </ul>
</details>

**Comment by lanitochka17** [comment] 2023-09-29 19:12
The issue is not reproducible with a 1.3.75.3 build

https://github.com/Expensify/App/assets/78819774/99ef0a7b-b8c3-4aa3-8b3c-adc8a7bea678

**Comment by chiragsalian** [comment] 2023-09-29 20:36
i cannot reproduce either, closing issue.

**Comment by abdulrahuman5196** [comment] 2023-10-01 12:06
@chiragsalian / @trjExpensify I am able to reproduce the issue in staging itself. Could you kindly check and re-open this issue?

**Comment by mountiny** [comment] 2023-10-01 14:11
Still repro on the latest staging
https://github.com/Expensify/App/assets/36083550/016386c5-15a7-4b85-8e36-c380dded46fa

**Comment by mountiny** [comment] 2023-10-01 14:12
@abdulrahuman5196 @bernhardoj have you got fixes on tour mind? Or offending pr?

**Comment by abdulrahuman5196** [comment] 2023-10-02 11:04
@bernhardoj 

Your proposal here works fine. But I don't think it is the proper fix. 

>The simplest solution is to set the initial value of type back to undefined.

Same for the alternative solution as well.

>: props.isVisible && (invisibleView)

We shouldn't even come to this place(children rendering) if the popover is not rendered.


AFAIK, The popover layout will only happen if user clicks to show popover. In First layout, an invisible view will be rendered to calculate size, followed by proper renders of popovers.
If as you the `BaseReportActionContextMenu` is swallowing the enter key newly, we should find why and fix the same?

I know you had tried to explain the same here. But could point to how this happens? I am not seeing any rendering logic changes based on isVisible param in the PR.

>Before this https://github.com/Expensify/App/pull/27221, when PopoverWithMeasuredContent isVisible is false, BaseReportActionContextMenu is hidden (not rendered). But that's not the case now.


Do Let me know if I am missing something.

**Comment by OlimpiaZurek** [comment] 2023-10-02 11:56
Checked changes from this [PR ](https://github.com/Expensify/App/pull/27221) and have the same finding as in the proposal  Setting the `type` as `string` instead of `undefined` causes this issue, so to fix is we should set the initial value of `type` back to `undefined`.

**Comment by mountiny** [comment] 2023-10-02 13:23
Thanks @bernhardoj I have asked @OlimpiaZurek as a PR author to raise a fix PR but given we will use your solution, we will reward you 25% of standard bounty so $125

**Comment by trjExpensify** [comment] 2023-10-02 14:24
Assigning @bernhardoj to the issue to keep track of that for when this is ready for payment.

**Comment by mountiny** [comment] 2023-10-02 14:33
Assigning myself for mnagement and handling the PR review

**Comment by trjExpensify** [comment] 2023-10-13 17:11
What's the dealio here? We're ready to pay @bernhardoj $125 for this?

**Comment by mountiny** [comment] 2023-10-15 12:38
Yep I think we are good to pay, the checklist is not needed I think, it was already clearly identified what pr was this regression from and the author has addressed it using fix provided by @bernhardoj

**Comment by trjExpensify** [comment] 2023-10-16 11:53
(needed a job created in Upwork, removing @situchan).

**Comment by trjExpensify** [comment] 2023-10-16 11:54
@bernhardoj sent you an offer for $125!

**Comment by trjExpensify** [comment] 2023-10-16 17:29
Paid!

**Closed by trjExpensify** 2023-10-16 17:29 UTC
Labels: Reviewing, Engineering, Daily, Internal, Awaiting Payment, Bug
