### ISSUE TITLE
[HOLD for payment 2022-11-11] [$1500] some emojis are not displayed correctly as they should be - reported by Karim mostafa

### ISSUE THREAD

**Issue by mvtglobally** [Expensify/App#10356] opened 2022-08-11 18:30 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1- open app
2- Type emoji's keyword in the chat box
3- observe the shape of the emoji appeared

## Expected Result:
Emojis should appear in the normal shapes as they are supposed to

## Actual Result:
Emojis appeared in different shape than they are supposed to

## Workaround:
unknown 

## Platform:

Where is this issue occurring?

- Web
- iOS
- Android
- Desktop App
- Mobile Web

**Version Number:** 1.1.88-0
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**Email or phone of affected tester (no customers):** 
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation

https://user-images.githubusercontent.com/43995119/184213098-5b1b9d1d-efae-4df8-a304-634fa58f3a6d.mp4

![IMG-20220720-WA0003](https://user-images.githubusercontent.com/43995119/184213101-3935736e-dff1-42a6-9559-99a1c621a4e9.jpg)

**Expensify/Expensify Issue URL:** 
**Issue reported by:** @Karim-30 (Karim mostafa)
**Slack conversation:** https://expensify.slack.com/archives/C01GTK53T8Q/p1658404495570899

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by aldo-expensify** [comment] 2022-08-12 01:34
At least for them moment, https://github.com/Expensify/App/pull/9551 is not solving it:

![Screen Shot 2022-08-11 at 6 31 32 PM](https://user-images.githubusercontent.com/87341702/184268858-90c543fe-298e-414c-87c0-e3efd98c9432.png)
![Screen Shot 2022-08-11 at 6 31 42 PM](https://user-images.githubusercontent.com/87341702/184268860-25d3009b-cca4-4faa-932d-2aba73dc1807.png)

This can be reproduced in Chrome / web (macos). I have no idea where these emojis come from, are they characters in the font we use?

**Comment by bfitzexpensify** [comment] 2022-08-12 17:49
@parasharrajat #9123 is referencing a particular subset of emoji problems (skin tone), but if I'm understanding correctly, you're saying that it will address this problem too?

**Comment by aldo-expensify** [comment] 2022-08-12 18:04
I got the feeling that it was something different. This happens even in chrome and I think it is coming from the hardcoded list of emojis in this file: https://github.com/Expensify/App/blob/e3c8897a5f7f870cce04e62fc433acb68f371dbe/assets/emojis.js#L8779-L8784

I tested manually changing the symbol, and I saw it changing in the app.

**Comment by thesahindia** [comment] 2022-08-12 19:04
https://github.com/Expensify/App/issues/9123 has two issues in it.
1. Hand emoji at emoji picker shows as black and white
2. Some emojis look different at windows/Ubuntu because they need some system specific font. 

This one is same as 2 but the system is different so we will need another font for this (Apple Color Emoji)

**Comment by bfitzexpensify** [comment] 2022-08-15 15:06
Great, thanks for the explanation!

Upwork job [here](https://www.upwork.com/jobs/~01b36c9e071c2d7400)
Reporting job [here](https://www.upwork.com/jobs/~01f988031fcc199a9d) - please apply to this @Karim-30

**Comment by Karim-30** [comment] 2022-08-15 23:40
### Proposal

By replacing the incorrect emojis inside `App/assets/emojis.js` with the correct emojis (see the attached `emojis.txt`), all Emojis will appear in the correct shapes in Safari, Firefox.

![safari](https://user-images.githubusercontent.com/108357004/184733339-3150f00f-26a3-4878-a337-d092d34eb7aa.png)

![firefox](https://user-images.githubusercontent.com/108357004/184733351-32dd065d-701f-40b9-83b7-2c25296854a5.png)

but in Chrome all Emojis will appear in the correct shapes except these 8 arrow emojis.

![chrome](https://user-images.githubusercontent.com/108357004/184733473-2cadaa29-6752-449b-a797-80d54599f407.png)

to solve these 8 emojis we will need to change the `fontFamily` for some components from `GTAmericaExp-Regular` to `sans-serif` or `roboto` as the following : 

in `src/styles/fontFamily/index.js`:

```diff
    MONOSPACE_BOLD: 'GTAmericaExpMono-Bd',
    MONOSPACE_BOLD_ITALIC: 'GTAmericaExpMono-BdIt',
+   SANS_SERIF: 'sans-serif',
```

in `src/styles/styles.js` : 
```diff

    baseTextInput: {
-       fontFamily: fontFamily.GTA,
+       fontFamily: fontFamily.SANS_SERIF,
        fontSize: variables.fontSizeNormal,
        lineHeight: variables.fontSizeNormalHeight,
        color: themeColors.text,


    textLabelSupporting: {
-       fontFamily: fontFamily.GTA,
+       fontFamily: fontFamily.SANS_SERIF,
        fontSize: variables.fontSizeLabel,



   textInputCompose: addOutlineWidth({
        backgroundColor: themeColors.componentBG,
        borderColor: themeColors.border,
        color: themeColors.text,
-       fontFamily: fontFamily.GTA,
+       fontFamily: fontFamily.SANS_SERIF,
        fontSize: variables.fontSizeNormal,
        borderWidth: 0,


    emojiText: {
-       fontFamily: fontFamily.GTA_BOLD,
+       fontFamily: fontFamily.SANS_SERIF,
        textAlign: 'center',
```

in `src/pages/home/report/ReportActionItemFragment.js` : 
```diff
 import canUseTouchScreen from '../../../libs/canUseTouchscreen';
 import compose from '../../../libs/compose';
+import fontFamily from '../../../styles/fontFamily';


                    <Text
                        selectable={!canUseTouchScreen() || !props.isSmallScreenWidth}
-                       style={EmojiUtils.containsOnlyEmojis(props.fragment.text) ? styles.onlyEmojisText : undefined}
+                       style={[{fontFamily: fontFamily.SANS_SERIF}, EmojiUtils.containsOnlyEmojis(props.fragment.text) ? styles.onlyEmojisText : undefined]}
                    >
```

Result : 

https://user-images.githubusercontent.com/108357004/184735747-cadeb0b8-5ad2-4cd7-8834-a9e2acd03e88.mov


Don't forget to replace `App/assets/emojis.js` content with the attached file content.
[emojis.txt](https://github.com/Expensify/App/files/9340552/emojis.txt)

**Comment by mananjadhav** [comment] 2022-08-18 04:38
@Karim-30 I don't think changing the font family is an option here.

**Comment by bfitzexpensify** [comment] 2022-08-22 12:17
Doubled to $500

**Comment by Puneet-here** [comment] 2022-08-23 04:39
Is there a reason for not adding `Apple Color Emoji` as mentioned here https://github.com/Expensify/App/issues/10356#issuecomment-1213429783.

**Comment by tgolen** [comment] 2022-08-23 09:29
I vote we stay away from a sprite-based approach. I think it results in
more maintenance than is worth it.

**Comment by mananjadhav** [comment] 2022-08-23 10:29
Agreed with `no sprite approach`.

**Comment by bfitzexpensify** [comment] 2022-08-30 08:49
Doubled to $1000

**Comment by mvtglobally** [comment] 2022-08-30 15:25
Issue not reproducible during KI retests. (First week)

**Comment by bfitzexpensify** [comment] 2022-09-02 10:04
@mananjadhav proposal above for you to review

**Comment by mananjadhav** [comment] 2022-09-02 18:24
Thanks for the bump @bfitzexpensify.

@Puneet-here While your proposed solution might work to replace the emojis with the relevant symbols, it lacks details on:

1. Which source are you going to rely on? I am not very confident with emojipedia.org emojis (this feedback is from my experience of atleast 1-1.5 years back)
2. How will you identify the problematic emojis?
3. Is there a way to test his reliably?

**Comment by Puneet-here** [comment] 2022-09-02 18:54
> @Puneet-here While your proposed solution might work to replace the emojis with the relevant symbols, it lacks details on:
> 
> 1. Which source are you going to rely on? I am not very confident with emojipedia.org emojis (this feedback is from my experience of atleast 1-1.5 years back)

I tried it and haven't seen any problem for the emojis I tried to fix so far, we can use it as I will be checking every emoji so in case some emoji doesn't work I can get that emoji from some other place. We can get the emojis from other sources like:- https://github.com/github/gemoji/blob/master/db/emoji.json

> 2. How will you identify the problematic emojis?

I will check every individual emoji at different platforms.

> 3. Is there a way to test this reliably?

I can create the list of problematic emojis and share it so that we can just replace all the emojis at emojis.js with them to test it.

**Comment by mananjadhav** [comment] 2022-09-03 18:16
>> How will you identify the problematic emojis?
> I will check every individual emoji at different platforms.

@Puneet-here Considering the number of emojis to be checked? Can we either list down the problematic emojis or have a programmatic way to identify the problematic emojis?

**Comment by Puneet-here** [comment] 2022-09-03 18:46
> Considering the number of emojis to be checked? Can we either list down the problematic emojis or have a programmatic way to identify the problematic emojis?

I don't think there's a programmatic way, I will list them down manually.

**Comment by bfitzexpensify** [comment] 2022-09-06 07:46
@mananjadhav do you think the manual approach is fine or should we try to find another solution?

**Comment by mananjadhav** [comment] 2022-09-06 08:42
@bfitzexpensify I started an internal thread [here](https://expensify.slack.com/archives/C02NK2DQWUX/p1662447325583099). I've tagged you.

**Comment by tgolen** [comment] 2022-09-13 15:43
Trying to wrap up the thread in Slack today so we can keep moving here.

**Comment by mananjadhav** [comment] 2022-09-14 10:11
So we've discussed this internally and here's the conclusion.

1. Instead of fixing some emojis, we've decided to update our datasource to also include Emoji 13 (and if possible Emoji 14) characters
2. I've evaluated a couple of datasources and so far Gemoji is closest to what we need (it's biggest shortcoming is missing Emoji 14 characters)
3. We don't want to update the structure of our format at the moment.
4. We don't want to break any existing feature (like Frequently used emojis).

**Here's what we'll need from the proposal:**
1. A working script which sources data from Gemoji to our format similar to [this](https://github.com/Expensify/App/blob/9a98116600f697d920f594db3bc3ab9dec5d2d29/assets/emojis.js#L3-L27). This doesn't include creating any API to auto connect. Reading from a JSON dump to populating our `assets/emojis.js` should be fine. 
2. All emojis to be rendered in symbol(emoji) representation on all platforms. None of them should be text representation.
3. An automated test that verifies that all the emojis are in Emoji representation and not the Text representation, so that when we add any new emoji, the same issue doesn't crop up.
4. All existing features working as expected, viz., Skin tone, Frequently used emojis, search emojis, categorization of the emojis, and UI related items like navigation, selection, hover, etc. @tgolen / @mvtglobally  can share if we maintain any internal regression suite here. For frequently used emojis, it could be that problematic emojis won't show up. That's fine and is expected.

------

@Puneet-here Because you were the one finding the Gemoji datasource and also with the closest proposal of replacing the emojis, I am going to give you a dibs on this one for 2 days. If we don't get a proposal from you, then we'll be open for proposals from others.

----

@tgolen @bfitzexpensify  Feel free to add/correct if I've missed anything.

**Comment by mananjadhav** [comment] 2022-09-16 13:28
@Puneet-here Quick bump here.

--- 

Open for proposals.

**Comment by Puneet-here** [comment] 2022-09-16 19:47
> @Puneet-here Quick bump here.

Sorry, I didn't get the time to look into this. I will try in the morning.

**Comment by akshayasalvi** [comment] 2022-09-18 09:11
**Proposal**

I checked the requirements and the Gemoji dataset. Following is what I propose for the code.

1. Take a dump of gemoji data as json
2. Run the script mentioned below 
3. Copy data json to our src/assets/emojis.js file.

I also found that we can add `alias` to our dataset for future use. Also, I have merged keywords from our old dataset to new dataset so that we don't lose keywords. For example, `🙈` has 6-7 keywords in our dataset, but gemoji has only 3 keywords.

```
const _ = require("lodash");
const emojiData = require('./gemoji.json');
const oldEmojiData = require('./emoji.js');
const fs = require('fs');

const emojisGroupedByCategory = _.groupBy(emojiData, 'category');
const oldEmojiMap = _.keyBy(oldEmojiData, 'code');

const emojisList = [];
for(let category in emojisGroupedByCategory) {
    let categoryName = category.replace(' & ', 'And');
    categoryName = categoryName.charAt(0).toLowerCase() + categoryName.slice(1);
    emojisList.push({
        code: categoryName,
        header: true
    });
    const emojisPerCategory = emojisGroupedByCategory[category];
    for(let i = 0; i < emojisPerCategory.length; i++) {
        const emoji = emojisPerCategory[i];
        let keywords = emoji.tags;
     
        if(oldEmojiMap[emoji.emoji]) {
            keywords = keywords.concat(oldEmojiMap[emoji.emoji].keywords);
        }
        const emojiRow = {
            code: emoji.emoji,
            aliases: emoji.aliases,
            keywords: _.uniq(keywords)
        };
        emojisList.push(emojiRow);
    }
};

let data = JSON.stringify(emojisList);
fs.writeFileSync('new-emoji.json', data);
```

About the tests I tried but there is no pattern from which we can identify if our emoji has no text representation, But I compared the dataset and I found the different emojis, I can add a test

```
const problematicEmojis = ["◀", ...];
for(let i = 0; i < problematicEmojis.length; i++) {
    const isColoredEmoji = /fe0e$/.test(problematicEmojis[i]);
}
```

**Comment by bfitzexpensify** [comment] 2022-09-19 09:51
reassigning as I head ooo for 2 weeks

**Comment by tgolen** [comment] 2022-09-19 15:08
@akshayasalvi Thanks for the updated proposal. The script looks mostly good to me, but let's not worry about `alias` for now. If we decide to use it in the future, we can incorporate it at that time.

Are you sure there is nothing that will work for automatically detecting the emoji's? I don't think the test you mention would be worth it to add since it only contains a hard-coded list and wouldn't detect anything outside of that.

**Comment by mananjadhav** [comment] 2022-09-20 04:09
@tgolen I took sometime to check if something can be done in an automated way.  I couldn't find. Generally the text emojis end with `fe0e` unicode or nothing. So emojis like 😀  don't have text representation so when `fe0e` doesn't exist we don't know if it is ⚰️  or 😀  type emojis.

Checked @akshayasalvi's proposal. It looks good. The only thing is:
1. You're merging the keywords that is a good idea, but the ones you said don't match, we'll lose keywords?
2. @tgolen If we're removing alias, should we add them to `keywords`?

**Comment by akshayasalvi** [comment] 2022-09-20 11:12
Thank you for reviewing the proposal @tgolen. I couldn't find a way to automate this. This python package https://github.com/carpedm20/emoji/ uses unicode scraping for the emojis, but if we're using a source like gemoji then it won't make sense for us to scrap the records.

@mananjadhav I can try and add the keywords manually. There are some 150 odd ones, or a script to match the keywords may be.

**Comment by mananjadhav** [comment] 2022-09-20 11:15
Yes @akshayasalvi we can take a look at those and see if we're missing any keywords.

**Comment by tgolen** [comment] 2022-09-20 14:02
> If we're removing alias, should we add them to keywords?

This would probably be a good idea, yeah. I could go for that.

Thanks for the additional thoughts on testing 👍 I guess there is no real automated way to go about it for now, so let's not have any automated testing be part of the proposal. It would maybe be good to think about adding some manual test cases to try and cover our bases at some point for our QA testing team.

**Comment by akshayasalvi** [comment] 2022-09-22 02:48
@tgolen @mananjadhav Can I start with the PR?

**Comment by mananjadhav** [comment] 2022-09-22 02:58
You have my 🟢 for this @akshayasalvi but let @tgolen confirm once.

**Comment by Puneet-here** [comment] 2022-09-22 12:42
AFAICS the script will remove the skin tones.

**Comment by akshayasalvi** [comment] 2022-09-22 12:56
You're right @Puneet-here, here's the piece of code that takes care of it. I've given a working example of the code and not the full script. Something on the lines of. In the PR I'll be testing the skin tones, frequently used emojis as pointed out earlier in the requests.

```
   if(emoji. skin_tones)  {
        emojiRow.types = ['1f3fb', '1f3fc', '1f3fd', '1f3fe',  '1f3ff'].map(skinTone => String.fromCodePoint(`${emoji.code}{skinTone}`));
   }
```

**Comment by mananjadhav** [comment] 2022-09-22 13:03
Thanks for the comment @Puneet-here. 

That works @akshayasalvi  and `String.fromCodePoint` will need them to be unicode but we can handle that in the PR.

**Comment by tgolen** [comment] 2022-09-22 14:45
🟢 from me! @MitchExpensify you can officially hire them in upwork if you haven't yet.

**Comment by MitchExpensify** [comment] 2022-09-22 20:26
Great! @akshayasalvi Please accept my invite to the [Upwork Job](https://www.upwork.com/jobs/~01b36c9e071c2d7400) and I will officially hire you, thanks!

**Comment by akshayasalvi** [comment] 2022-09-26 08:53
I am working on this issue and completed partially. There's an issue with some emojis when I add skin tone to them. So working that out.

**Comment by akshayasalvi** [comment] 2022-09-28 04:54
@mananjadhav I did, and I found that the issue exists with only Male/Female version of some odd 14-16 Emojis. I am going to update those and add up here.

**Comment by akshayasalvi** [comment] 2022-09-30 08:37
I fixed the problematic emojis, I am verifying if there's any random one left. Testing the rest of the changes. PR should be ready for review by weekend or Monday.

**Comment by mvtglobally** [comment] 2022-10-03 20:12
Issue not reproducible during KI retests. (First week)

**Comment by akshayasalvi** [comment] 2022-10-10 19:10
Draft PR is already raised. I am currently testing all the features. It should be ready for review in 1-2 days.

**Comment by mvtglobally** [comment] 2022-10-11 12:56
Issue not reproducible during KI retests. (Second week)

**Comment by mvtglobally** [comment] 2022-10-18 11:15
Issue not reproducible during KI retests. (Third week) @tgolen @MitchExpensify  Are we ok to close this?

**Comment by tgolen** [comment] 2022-10-18 14:24
@akshayasalvi are you still working on this? What is the status of your PR? Can you still reproduce the original problem?

**Comment by akshayasalvi** [comment] 2022-10-20 03:04
Yes @tgolen I am working on it. I haven't been able to sync the main branch because it results in conflicts every time. I am just updating the final emoji list, keep a copy and then update it. I'll raise the full PR by tomorrow.

**Comment by tgolen** [comment] 2022-10-27 14:42
@akshayasalvi Did you get a chance to get that PR started?

**Comment by akshayasalvi** [comment] 2022-10-31 06:07
@tgolen I created a second PR after all the fixes, but we have a new field in the emojis.js that is currently used for searching the PR. `name` is used in the emojis for searching and older dataset didn't have. I am working on the changes of the PR, to add the name. It is most similar to `alias` in gemoji.

**Comment by MitchExpensify** [comment] 2022-10-31 23:20
@puneetlath is there guidance I'm missing on completing a BugZero checklist? Thank you https://stackoverflow.com/c/expensify/questions/14574

**Comment by puneetlath** [comment] 2022-11-03 13:27
@MitchExpensify started a discussion on it here: https://expensify.slack.com/archives/C01SKUP7QR0/p1667427593134589

**Comment by MitchExpensify** [comment] 2022-11-04 16:05
Nice! Will keep an eye out for an answer to [that SO](https://stackoverflow.com/c/expensify/questions/14574)

**Comment by MitchExpensify** [comment] 2022-11-04 18:52
Made a note to pay on my calendar!

**Comment by puneetlath** [comment] 2022-11-04 19:13
@MitchExpensify SO is updated.

**Comment by akshayasalvi** [comment] 2022-11-07 06:40
@tgolen Can I please request to increase the compensation for this one by some amount?

I didn't factor in the changes to process the emojis and refactor of the Tests. I know the tests are to be part of the PR, but the new emojis did break the current test, and I cleaned up some of the unwanted to code while fixing the tests not related to the change.

Would be great if you can consider the request.

**Comment by MitchExpensify** [comment] 2022-11-07 14:01
@mananjadhav, following these instructions - Mind pointing to me to the PR that cause this bug?  Thank you

**Comment by mananjadhav** [comment] 2022-11-07 14:30
@MitchExpensify This has been a problem since the inception. What I mean is our emoji datasource didn't support them since the beginning. https://github.com/Expensify/App/pull/1991 here's the PR when we added the previous emojis with the emoji picker.

**Comment by MitchExpensify** [comment] 2022-11-07 14:48
@puneetlath "A discussion in #contributor-plus has been started about whether any other steps should be taken (e.g. updating the PR review checklist) in order to catch this type of bug sooner."

Curious for your thoughts as I try to follow these instructions, the [PR that introduced the emoji picker](https://github.com/Expensify/App/pull/1991) didn't have a C+ or CME. Does it still make sense to post in #contributor-plus in a similar manner tagging internal engineers involved? Thank you!

**Comment by tgolen** [comment] 2022-11-07 15:44
> Can I please request to increase the compensation for this one by some amount?

I can appreciate that there was more work required to complete this than was figured in the original proposal. However, I was pretty disappointed that it took almost a month to get the PR created for this.

You originally said on Sep 30:

> PR should be ready for review by weekend or Monday.

The PR was taken out of draft and marked ready to review on Oct. 30 and there was a gap of nearly a month where the branch didn't have any commits.

If the work would have been done with greater urgency, I would be OK doubling the price of this issue, but due to the solution taking so long to get to completion, I am only approving a $500 increase to the price of this issue to a total of $1500.

**Comment by mananjadhav** [comment] 2022-11-07 16:18
@akshayasalvi Few points of feedback in addition to @tgolen mentioned.

1. While we understand conflicts arise, and if you see any impeding PR pushing frequent updates which causes you to resolve conflicts, just highlight so that we can put this on Hold.
2. As @tgolen mentioned, there was a long gap between commits, if you're going OOO or not working then please inform. Communication goes a long way in setting up expectations.
3. I also saw some commits with misses in the script, so if you felt you're stuck somewhere, clarify, and we can 
4. Ideally we're looking for longer relationships with the contributors, so we don't want bad experiences neither for you or ourselves. Always remember two rules: `Get shit done` and `Don't ruin it for everyone else`

Thank you so much for taking it to the finish line! Appreciate that you refactored some of the code.

**Comment by MitchExpensify** [comment] 2022-11-08 15:46
Making a note for myself:

- Reporting payment will be issued via [this Upwork Job](https://www.upwork.com/jobs/~012833548929001c7e)
- C+ and Contributor payment will be issued via [this Upwork Job](https://www.upwork.com/jobs/~01b36c9e071c2d7400)

**Comment by mananjadhav** [comment] 2022-11-11 06:35
@MitchExpensify I am already hired for this job with this [link](https://www.upwork.com/nx/wm/workroom/31566647/overview). When I click on the link you've shared it says Job no longer available.

I am guessing it's the same link, but still fyi.

**Comment by MitchExpensify** [comment] 2022-11-13 16:23
@mananjadhav Yes all set! Issuing payment now

**Comment by MitchExpensify** [comment] 2022-11-13 17:24
@Karim-30 mins accepting [the offer here](https://www.upwork.com/jobs/~018b71c2e42d0be244)? Thank you!

**Comment by MitchExpensify** [comment] 2022-11-13 17:31
Paid @mananjadhav & @akshayasalvi ! Thank you!

**Comment by mananjadhav** [comment] 2022-11-14 03:47
Thanks @MitchExpensify

**Comment by Karim-30** [comment] 2022-11-14 08:42
@MitchExpensify Accepted the offer, Thanks.

**Comment by Karim-30** [comment] 2022-11-15 11:34
@tgolen I got paid, we can close it.

**Comment by mvtglobally** [comment] 2022-11-16 02:09
Issue not reproducible during KI retests. (First week)

**Comment by MitchExpensify** [comment] 2022-11-16 19:03
[Conversation started in #contributor-plus here](https://expensify.slack.com/archives/C02NK2DQWUX/p1668625306086319)

**Closed** 2022-11-16 19:04 UTC
Labels: External, Engineering, Daily, Help Wanted, Awaiting Payment, Bug
