### ISSUE TITLE
[$500] Web - Chat - Context menu emoji picker vanishes if resize the window

### ISSUE THREAD

**Issue by izarutskaya** [Expensify/App#33787] opened 2023-12-29 21:53 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___
**Found when executing PR:** https://github.com/Expensify/App/pull/33537

**Version Number:** v1.4.20-0
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** Applause-Internal team
**Slack conversation:** @

## Action Performed:
1. Login to ND Expensify
2. Open a conversation
3. Right click on a row/message to open the context menu
4. Open the emoji picker (+Add reaction)
5. Resize the window
6. Verify the emoji picker position is moved correctly/stayed in the same place

## Expected Result:
Emoji picker position in Context menu is moved correctly/stayed in the same place

## Actual Result:
Emoji picker position in Context menu vanishes as soon as window is resized

Note: I guess the issue is not caused by PR, but it is related though.

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

https://github.com/Expensify/App/assets/115492554/b2ff11ad-ca2e-41d2-8e88-1d96162fe2fa

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~0110541f71f2b5036f</li>
        <li>Upwork Job ID: 1740853591428820992</li>
        <li>Last Price Increase: 2023-12-29</li>
    </ul>
</details>

**Comment by aim-salam** [comment] 2023-12-30 00:11
## Proposal

### Please re-state the problem that we are trying to solve in this issue.

Web - Chat - Context menu emoji picker vanishes if resize the window

### What is the root cause of that problem?

The statement want to ` hideEmojiPicker()` when screen was small. But `!isSmallScreenWidth` show opposite value.

https://github.com/Expensify/App/blob/b1c68830cbdee4ac8840d7dabbef87d362304a19/src/components/EmojiPicker/EmojiPicker.js#L140-L143

### What changes do you think we should make in order to solve the problem?

`!isSmallScreenWidth` into `isSmallScreenWidth`


### What alternative solutions did you explore? (Optional)

**Comment by bernhardoj** [comment] 2023-12-30 05:28
I think this is intentional https://github.com/Expensify/App/pull/22792

**Comment by kaushiktd** [comment] 2024-01-02 10:22
### Please re-state the problem that we are trying to solve in this issue.
Web - Chat - Context menu emoji picker vanishes if resize the window

### What is the root cause of that problem? 
The current implementation of the Emoji Picker component is causing visibility issues based on screen size conditions. The code utilizes the `isSmallScreenWidth` variable to determine the visibility of the Emoji Picker on different screen sizes.

### What changes do you think we should make in order to solve the problem? 
 
The existing conditional logic for showing or hiding the Emoji Picker based on screen size conditions is causing inconsistencies in visibility. Specifically, the condition
```
 if (isEmojiPickerVisible && !isSmallScreenWidth) {
                    hideEmojiPicker();
       }
hides the picker on larger screens, while
 if (isEmojiPickerVisible && isSmallScreenWidth) {
                    hideEmojiPicker();
                }
```
hides it on smaller screens. Additionally, retrieving the anchor element using `getEmojiPopoverAnchor()` returns a null value, causing unexpected behavior in the picker's positioning.  `showEmojiPicker()` causing the Emoji Picker to be stuck in the top-left corner due to the null value returned by `getEmojiPopoverAnchor()` so that won't work either.

if we remove this code, it works perfectly fine,

```
 if (isEmojiPickerVisible && isSmallScreenWidt) {
                    hideEmojiPicker();
                } 
```
### Video:-
https://drive.google.com/file/d/1Jc_qyjs11bd7Ih-wjbVY8urdpiHRC_X_/view?usp=sharing

**Comment by peterdbarkerUK** [comment] 2024-01-03 12:34
I agree this is intentional, closing!

**Closed by peterdbarkerUK** 2024-01-03 12:34 UTC
Labels: External, Daily, Help Wanted, Overdue, Bug
