### ISSUE TITLE
[HOLD for payment 2023-09-18] [$1000] Web -  Thread - No space between message and compose box when sender leave thread

### ISSUE THREAD

**Issue by izarutskaya** [Expensify/App#25461] opened 2023-08-18 10:12 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. go to any chat
2. send any message and click on reply in thread option
3. send message in thread
4. from receiver side go to thread
5. from sender side leave thread

## Expected Result:
Should be some space between message and compose box

## Actual Result:
No space between message and compose box

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [x] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** v1.3.55-4

**Reproducible in staging?:** Y

**Reproducible in production?:** Y

**If this was caught during regression testing, add the test name, ID and link from TestRail:**

**Email or phone of affected tester (no customers):**

**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/115492554/654675db-7d21-44ce-9e23-44bde88b3576

https://github.com/Expensify/App/assets/115492554/48b77b89-a0cf-4d0d-a40e-25e0ca4fa1cd

**Expensify/Expensify Issue URL:**

**Issue reported by:** @gadhiyamanan

**Slack conversation:**https://expensify.slack.com/archives/C049HHMV9SM/p1691496184324319

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01007c19ea2483982e</li>
        <li>Upwork Job ID: 1696437995377553408</li>
        <li>Last Price Increase: 2023-08-29</li>
    </ul>
</details>

**Comment by Pujan92** [comment] 2023-08-18 10:44
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
No margin/padding between last message and composer when sender leaves thread

### What is the root cause of that problem?
We are not rerendering the `ReportActionsView` on particinpants change, that won't rerenders `ReportActionsList` which is responsible for adding the bottom padding if required when we are not showing the RecipientLocalTime. That is causing this issue and not adding bottom padding dynamically.
https://github.com/Expensify/App/blob/d4490726ca1f6cc340b3c03044fd8c2ca350fdb8/src/pages/home/report/ReportActionsList.js#L166

### What changes do you think we should make in order to solve the problem?
We need to add a check either for `participantAccountIDs` or `participants` length within `arePropsEqual` function here. That will rerender the component if the lengths are not same and allow the bottom padding if needed.
https://github.com/Expensify/App/blob/d4490726ca1f6cc340b3c03044fd8c2ca350fdb8/src/pages/home/report/ReportActionsView.js#L379

**Comment by ShogunFire** [comment] 2023-08-19 16:37
I don't see the pusher message in the console but something seems weird, when I put a breakpoint, one of the participant of the parent report is removed but not the thread report. I believe this one is backend

**Comment by slafortune** [comment] 2023-08-22 16:58
I'll get some engineering eyes
![image](https://github.com/Expensify/App/assets/11725910/5ab11992-bde3-47b9-bc76-154a6b491da6)
When the other person left the thread we are not showing the timestamp, in this case we need to provide some space/gap between last message and composer. Currently last message and composer don’t have any gap for this scenario.

**Comment by Gonals** [comment] 2023-08-23 10:54
Sure. @shawnborton, any preference on the size of that space? 😁

**Comment by Pujan92** [comment] 2023-08-23 12:12
Just sharing the issue screenshot

<img width="1440" alt="Screenshot 2023-08-23 at 17 41 50" src="https://github.com/Expensify/App/assets/14358475/d47ebc98-a1c6-4888-b7e0-caa5be921e38">

**Comment by shawnborton** [comment] 2023-08-23 12:16
We should take a consistent look at this everywhere, not just threads. 

I think a good rule would be that if there is no timezone information, there should always be 8px of margin above the compose box. 

If there is a timezone information, we should display 8px of margin above and below the timezone. 

And this should be the case for all chats as a consistent, global style - not specific to threads or group chats or anything like that.

**Comment by Pujan92** [comment] 2023-08-23 12:21
We already have the logic for that(show space when timezone isn't been shown) but specific to this scenario we are not rerendering the component when participants get updated. Showing timezone depends on that factor too. cc: @Gonals

**Comment by Gonals** [comment] 2023-08-29 08:21
Given the info, marking this as external!

**Comment by jjcoffee** [comment] 2023-08-30 15:29
Sorry got caught up in higher priority reviews today, will review the proposals tomorrow!

**Comment by jjcoffee** [comment] 2023-08-31 15:02
@Pujan92's [proposal](https://github.com/Expensify/App/issues/25461#issuecomment-1683722876) LGTM! It has the correct RCA and the solution makes the most sense to me (as the logic for adding padding is already in `ReportActionsList`, it's just not running).

:ribbon::eyes::ribbon: C+ reviewed

**Comment by Gonals** [comment] 2023-09-04 11:10
> @Pujan92's [proposal](https://github.com/Expensify/App/issues/25461#issuecomment-1683722876) LGTM! It has the correct RCA and the solution makes the most sense to me (as the logic for adding padding is already in `ReportActionsList`, it's just not running).
> 
> 🎀👀🎀 C+ reviewed

Sounds good!

**Comment by jjcoffee** [comment] 2023-09-04 16:49
@tienifr Sorry, I did have a look over your [proposal](https://github.com/Expensify/App/issues/25461#issuecomment-1697138912) and gave it a sort of stealth review when I said:

> the logic for adding padding is already in ReportActionsList, it's just not running

I'm erring on the side of we probably added padding there for good reason, and your proposal was to move it to `ReportActionCompose`. I also don't think re-rendering on `report.participantAccountIDs` is necessarily a particularly bad thing in this case.

**Comment by Pujan92** [comment] 2023-09-05 12:55
@jjcoffee [PR](https://github.com/Expensify/App/pull/26770) is ready for review!

**Comment by jjcoffee** [comment] 2023-09-05 14:47
@Pujan92 Thanks, reviewing tomorrow!

**Comment by slafortune** [comment] 2023-09-08 18:57
@jjcoffee are you able to get to this?

Reassigning a BZ member, I am out on sabbatical

**Comment by puneetlath** [comment] 2023-09-14 13:52
@jjcoffee friendly reminder on the checklist so that we can pay on Monday.

**Comment by jjcoffee** [comment] 2023-09-14 14:19
- [x] The PR that introduced the bug has been identified. Link to the PR: **N/A - padding was already there, the component just wasn't re-rendering.**
- [x] The offending PR has been commented on, pointing out the bug it caused and why, so the author and reviewers can learn from the mistake. Link to comment: **N/A**
- [x] A discussion in #expensify-bugs has been started about whether any other steps should be taken (e.g. updating the PR review checklist) in order to catch this type of bug sooner. Link to discussion: https://expensify.slack.com/archives/C049HHMV9SM/p1694701144755569
- [x] Determine if we should create a regression test for this bug. **I don't think this is impactful enough to need a regression test**
- [x] If we decide to create a [regression test](https://github.com/Expensify/App/blob/main/contributingGuides/REGRESSION_TEST_BEST_PRACTICES.md) for the bug, please propose the regression test steps to ensure the same bug will not reach production again. **N/A**

**Comment by Gonals** [comment] 2023-09-22 06:07
I think we are all done here, right?

**Comment by puneetlath** [comment] 2023-09-22 07:30
Just need to pay. @Pujan92 @gadhiyamanan can you apply to the job? https://www.upwork.com/jobs/~01007c19ea2483982e

**Comment by gadhiyamanan** [comment] 2023-09-22 07:33
@puneetlath applied, thanks!

**Comment by Pujan92** [comment] 2023-09-22 08:08
Applied :)

**Comment by puneetlath** [comment] 2023-09-24 09:15
All paid. Thanks everyone!

**Closed by puneetlath** 2023-09-24 09:15 UTC
Labels: External, Engineering, Daily, Awaiting Payment, Bug
