### ISSUE TITLE
[HOLD for payment 2023-10-31] [HOLD for payment 2023-10-30] IOU - Bank account and Debit card modal appears on the left of Pay with Expensify button

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#30130] opened 2023-10-21 17:21 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.3.88-3
**Reproducible in staging?:** Yes
**Reproducible in production?:** No
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** Applause - Internal Team
**Slack conversation:**

**Issue found when executing PR** https://github.com/Expensify/App/pull/29902
## Action Performed:
Precondition: User A has requested money in USD from User B
1. As User B, go to 1:1 DM with User A
2. Select Pay with Expensify from the dropdown in IOU preview
3. Click on Pay with Expensify button

## Expected Result:
The Bank account and Debit card modal appears above Pay with Expensify button

## Actual Result:
The Bank account and Debit card modal appears on the left of Pay with Expensify button

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] Windows: Chrome
- [x] MacOS: Desktop

## Screenshots/Videos
<details>
<summary>Android: Native</summary>

</details>

<details>
<summary>Android: mWeb Chrome</summary>

</details>

<details>
<summary>iOS: Native</summary>

</details>

<details>
<summary>iOS: mWeb Safari</summary>

</details>

<details>
<summary>Windows: Chrome </summary>

 

https://github.com/Expensify/App/assets/78819774/496bad6c-4d97-4c2b-9931-a186d35544e0

</details>

<details>
<summary>MacOS: Desktop</summary>

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by Pujan92** [comment] 2023-10-21 18:58
Dupe of https://github.com/Expensify/App/pull/29361 and PR is open for it

**Comment by thienlnam** [comment] 2023-10-22 01:01
If this is a dupe of that, it should be reproducible in production as well right?

**Comment by mountiny** [comment] 2023-10-22 21:48
<img width="490" alt="image" src="https://github.com/Expensify/App/assets/36083550/52fbafc1-5f0d-4c33-96af-17e7b7059170">
fixed

**Comment by bfitzexpensify** [comment] 2023-10-31 23:04
I think we can close this and use https://github.com/Expensify/App/issues/29332 as the payment/BZ checklist issue (since that has activity by the contributor and C+) - that make sense @deetergp @luacmartins?

**Comment by deetergp** [comment] 2023-11-02 00:29
Makes sense to me @bfitzexpensify

**Closed** 2023-11-02 22:17 UTC
Labels: Engineering, Daily, Awaiting Payment, Bug
