### ISSUE TITLE
[HOLD for payment 2024-11-21] [$250] Inbox showing GBR when there’s a report with RBR

### ISSUE THREAD

**Issue by m-natarajan** [Expensify/App#50927] opened 2024-10-16 17:27 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 9.0.49-0
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught on HybridApp, is this reproducible on New Expensify Standalone?:**
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** @pac-guerreiro 
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1728665408536049

## Action Performed:

1. Make sure there is at least a report with GBR and another with a RBR
2. Select a report which hasn’t a RBR indicator
3. Go to Troubleshoot, then click on Clear cache and restart
4. Go back to Inbox and check that the Inbox is showing a GBR indicator
5. Open the report that has the RBR indicator then refresh the page

## Expected Result:
Should have same logic that should display RBR in inbox

## Actual Result:
The inbox indicator doesn’t show an updated color until the page is refreshed and it shows the wrong color until a report is fully loaded

## Workaround:
unknown
## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Standalone
- [ ] Android: HybridApp
- [ ] Android: mWeb Chrome
- [ ] iOS: Standalone
- [ ] iOS: HybridApp
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

https://github.com/user-attachments/assets/287d512e-03f5-4ff2-80fd-8e590c91596e

https://github.com/user-attachments/assets/791a3300-0f7a-49dc-b7f5-f1d004ce0958

<details>
  <summary>Add any screenshot/video evidence</summary>

  
</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~021847128366508796109</li>
        <li>Upwork Job ID: 1847128366508796109</li>
        <li>Last Price Increase: 2024-10-18</li>
<li>Automatic offers: </li>
<ul>
<li>mkhutornyi | Reviewer | 104590221</li>
<li>truph01 | Contributor | 104590223</li>
</ul></li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @alexpensify</details>

**Comment by FitseTLT** [comment] 2024-10-16 21:25
## Proposal

### Please re-state the problem that we are trying to solve in this issue.

Inbox showing GBR when there’s a report with RBR

### What is the root cause of that problem?
We are only recalculating chat tab rbr value for transactionViolation and activeWorkspaceID changes here
https://github.com/Expensify/App/blob/4a25c36e50b58ef9e5ba8b63cf32132f95a0b005/src/libs/Navigation/AppNavigator/createCustomBottomTabNavigator/BottomTabBar.tsx#L72-L73
But inside [getChatTabBrickRoad](https://github.com/Expensify/App/blob/4a25c36e50b58ef9e5ba8b63cf32132f95a0b005/src/libs/WorkspacesSettingsUtils.ts#L132-L138) we use the status of allReports to calculate the value of rbr. But, allReports will not be available immediately after a user clears caches/onyx data so the rbr value will be calculated without the list of reports which will result wrong value and there is no recalculation held when the reports are loaded in onyx so it will remain green until we reload the page

### What changes do you think we should make in order to solve the problem?

We should subscribe to reports collection and use it in the calculation of rbr value 
https://github.com/Expensify/App/blob/4a25c36e50b58ef9e5ba8b63cf32132f95a0b005/src/libs/Navigation/AppNavigator/createCustomBottomTabNavigator/BottomTabBar.tsx#L69-L73
https://github.com/Expensify/App/blob/4a25c36e50b58ef9e5ba8b63cf32132f95a0b005/src/libs/Navigation/AppNavigator/createCustomPlatformStackBottomTabNavigator/BottomTabBar.tsx#L76-L79
```
    const [allReports] = useOnyx(ONYXKEYS.COLLECTION.REPORT);
    const [chatTabBrickRoad, setChatTabBrickRoad] = useState<BrickRoad>(getChatTabBrickRoad(activeWorkspaceID, allReports));

    useEffect(() => {
        setChatTabBrickRoad(getChatTabBrickRoad(activeWorkspaceID,allReports));
    }, [activeWorkspaceID, transactionViolations,allReports]);
```
https://github.com/Expensify/App/blob/4a25c36e50b58ef9e5ba8b63cf32132f95a0b005/src/libs/WorkspacesSettingsUtils.ts#L122-L123
```
function getChatTabBrickRoad(policyID?: string, allReportsParam): BrickRoad | undefined {
    const allReports = allReportsParam ?? ReportConnection.getAllReports();
   
```
It's not a must to use the useOnyx allreports data in `getChatTabBrickRoad` to fix the issue; only adding `allReports` to useEffect's dependency suffices, but I think it is generally accepted approach to use it
### What alternative solutions did you explore? (Optional)

**Comment by pac-guerreiro** [comment] 2024-10-17 07:25
I just want to clarify that there are two problems here:

1. inbox indicator is not updated in realtime
2. Inbox indicator is green when there are reports with RBR until at least one RBR is opened manually by the user

**Comment by truph01** [comment] 2024-10-17 09:42
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
Inbox has no GBR or RBR indicator until the page is refreshed

### What is the root cause of that problem?
- Currently, in the logic to get the RBR for policy, we do not consider the transaction violation and report violations as we did when display RBR in LHN:

https://github.com/Expensify/App/blob/77a37a101ee8776f9570842e32329ecb98deb94b/src/libs/WorkspacesSettingsUtils.ts#L66-L78
### What changes do you think we should make in order to solve the problem?
- We should add the logic to cover the violations in:
https://github.com/Expensify/App/blob/77a37a101ee8776f9570842e32329ecb98deb94b/src/libs/WorkspacesSettingsUtils.ts#L64

```
    const parentReportActions = reportActions?.[`${ONYXKEYS.COLLECTION.REPORT_ACTIONS}${report?.parentReportID}`];
    const parentReportAction = parentReportActions?.[report?.parentReportActionID ?? '-1'];
    const shouldDisplayViolations = ReportUtils.shouldDisplayTransactionThreadViolations(report, allTransactionViolations, parentReportAction);
    const shouldDisplayReportViolations = ReportUtils.isReportOwner(report) && ReportUtils.hasReportViolations(report.reportID);
    const hasViolations = shouldDisplayViolations || shouldDisplayReportViolations;    
    if (hasViolations) {
        doesReportContainErrors = CONST.BRICK_ROAD_INDICATOR_STATUS.ERROR;
    }
```

- And then update:

https://github.com/Expensify/App/blob/bcc62638a21ccbe717fb25abb983aac86672a8a2/src/libs/Navigation/AppNavigator/createCustomBottomTabNavigator/BottomTabBar.tsx#L71-L73

```
    const report = useOnyx(ONYXKEYS.COLLECTION.REPORT);
    const reportActions = useOnyx(ONYXKEYS.COLLECTION.REPORT_ACTIONS);
    const [chatTabBrickRoad, setChatTabBrickRoad] = useState<BrickRoad>(getChatTabBrickRoad(activeWorkspaceID));

    useEffect(() => {
        setChatTabBrickRoad(getChatTabBrickRoad(activeWorkspaceID));
    }, [activeWorkspaceID, transactionViolations, report, reportActions]);
```

to make sure the reports, reportActions data are updated immediately.
### What alternative solutions did you explore? (Optional)

**Comment by alexpensify** [comment] 2024-10-18 04:12
@mkhutornyi - can you please identify if this proposal will fix this issue? Thanks! 

## Heads up, I will be offline until Tuesday, October 22, 2024, and will not actively watch over this GitHub during that period.

If this GitHub requires an urgent update, please ask for help in the #expensify-open-source Slack Room. If the inquiry can wait, I'll review it when I return online.

**Comment by FitseTLT** [comment] 2024-10-18 17:46
The issue is very similar to https://github.com/Expensify/App/issues/50364

**Comment by truph01** [comment] 2024-10-18 22:56
As mentioned by @pac-guerreiro, this bug is to fix:

> Inbox indicator is green when there are reports with RBR until at least one RBR is opened manually by the user

**Comment by truph01** [comment] 2024-10-22 20:50
> can you please explain why the bug is gone after at least one RBR is opened manually in RCA?

As you can see, we are only considering the case the report is one transaction report:
https://github.com/Expensify/App/blob/77a37a101ee8776f9570842e32329ecb98deb94b/src/libs/WorkspacesSettingsUtils.ts#L66-L78

And because the one transaction report data can only be available after we call OpenReport for the expense report, so the bug is gone after at least one RBR is opened.

**Comment by truph01** [comment] 2024-10-22 20:57
> Are you saying that this bug happens only when one transaction report has RBR

No, that's not what I meant. To clarify, the bug occurs in both cases—whether it's a single transaction report or not. However, when it's a single transaction report, the bug disappears after visiting the expense report page, which is what we are discussing.

**Comment by truph01** [comment] 2024-10-22 21:02
> ok so if it's not a single transaction report, bug won't disappear even after refresh?

Yes.  If it's not a single transaction report, bug won't disappear even after refresh or visit any RBR report.

**Comment by alexpensify** [comment] 2024-10-28 15:44
@truph01 - any update for the PR here? Thanks!

**Comment by alexpensify** [comment] 2024-11-07 21:46
Update: PR is in review!

**Comment by alexpensify** [comment] 2024-11-22 01:22
Payouts due: 2024-11-21

- [ ] Contributor: $250 @truph01 
- [ ] Reviewer: $250 @mkhutornyi 

Upwork job is [here](https://www.upwork.com/jobs/~021847128366508796109).

**Comment by alexpensify** [comment] 2024-11-22 01:26
Everyone has been paid via Upwork. @mkhutornyi - can you please complete the checklist and confirm if there is a regression test? Thanks!

**Comment by alexpensify** [comment] 2024-11-25 19:53
Closing

**Closed by alexpensify** 2024-11-25 19:53 UTC
Labels: External, Daily, Overdue, Awaiting Payment, Bug
