### ISSUE TITLE
[$1000] Web - There is extra top padding/spacing on below listed pages between header and content

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#23496] opened 2023-07-24 17:24 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Login to ND
2. Navigate below listed pages
3. Notice there should be no extra top padding on below pages :
Priority mode page
PayPal page
ContactMethodsPage
ContactMethodDetailsPage
app download link
about page
Member page
ReimbursementAccountPage

## Expected Result:
No extra top padding should be there between header and content

## Actual Result:
There is extra top padding/spacing on below listed pages between header and content

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [x] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 1.3.44.0
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation

![Screenshot 2023-07-21 at 1 10 16 PM](https://github.com/Expensify/App/assets/93399543/330660e7-9607-4f7a-bd59-c692a01d7512)

**Expensify/Expensify Issue URL:**
**Issue reported by:** @dhairyasenjaliya
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1689925198870889

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~0173c93ed53e3f292e</li>
        <li>Upwork Job ID: 1683580769086390272</li>
        <li>Last Price Increase: 2023-08-14</li>
    </ul>
</details>

**Comment by kbecciv** [comment] 2023-07-24 17:25
### Proposal  

### Please re-state the problem that we are trying to solve in this issue. 

- Consistency: Priority mode has extra top padding between header and content

### What is the root cause of that problem?

- The root cause is we have added `marginVertical` that add top margin as well  
- Also have found in-consistency on other few pages like PayPal page , contact method page , app download link, about page that we can address here 

### What changes do you think we should make in order to solve the problem?
  
- As per this GH report I have added only for `Priority mode` but I have also found on different pages we should addressed that here

**Priority mode page**

- On below line we should remove `styles.mv4` and add `styles.mb4` or `styles.pb4`

https://github.com/Expensify/App/blob/a97ca9b2092c56e7d237e13e56a649cf08993090/src/pages/settings/Preferences/PriorityModePage.js#L46

**Additional affected pages below**

**PayPal page**

- On below line we should remove `styles.p5` and add `styles.pb5` and also add `styles.ph5` (optionally we can switch to `mb5` and `mh5`)

https://github.com/Expensify/App/blob/a97ca9b2092c56e7d237e13e56a649cf08993090/src/pages/settings/Payments/AddPayPalMePage.js#L70

**ContactMethodsPage**

- On below line we should remove `styles.mv3` and add `styles.mb3` or `styles.pb3`

https://github.com/Expensify/App/blob/a97ca9b2092c56e7d237e13e56a649cf08993090/src/pages/settings/Profile/Contacts/ContactMethodsPage.js#L120


**ContactMethodDetailsPage**

- On below line we should  remove `styles.mv3` and add `styles.mb3` or `styles.pb3`

https://github.com/Expensify/App/blob/a97ca9b2092c56e7d237e13e56a649cf08993090/src/pages/settings/Profile/Contacts/ContactMethodDetailsPage.js#L273

- On below line we should  remove `styles.mt3` 

https://github.com/Expensify/App/blob/a97ca9b2092c56e7d237e13e56a649cf08993090/src/pages/settings/Profile/Contacts/ContactMethodDetailsPage.js#L240

- On below line we should  remove `styles.mv3` and add `styles.mb3` or `styles.pb3`

https://github.com/Expensify/App/blob/a97ca9b2092c56e7d237e13e56a649cf08993090/src/pages/settings/Profile/Contacts/ContactMethodDetailsPage.js#L234

**app download link**

- On below line we should remove  `styles.mt5`

https://github.com/Expensify/App/blob/a97ca9b2092c56e7d237e13e56a649cf08993090/src/pages/settings/AppDownloadLinks.js#L63

**about page**

- On `styles.pageWrapper` we should remove `padding:20` and add `pb5` and `ph5`

https://github.com/Expensify/App/blob/a97ca9b2092c56e7d237e13e56a649cf08993090/src/pages/settings/AboutPage/AboutPage.js#L81

**Note: If we have any other affected pages we should tackle on PR** 

### What alternative solutions did you explore? (Optional)

- We can define global style and add desired `marginBottom` or `paddingBottom` to the affected pages

**Comment by MitchExpensify** [comment] 2023-07-24 19:35
@kbecciv mind outlining what padding is expected?

<img width="657" alt="image" src="https://github.com/Expensify/App/assets/36425901/f817c71a-f5ee-47fd-8ed6-f342081c20d2">

**Comment by kbecciv** [comment] 2023-07-24 20:07
@MitchExpensify Sorry about that, updated correctly.

**Comment by MitchExpensify** [comment] 2023-07-24 20:51
No worries! @kbecciv, thanks for the update.

**Comment by MitchExpensify** [comment] 2023-07-30 15:55
@aimane-chnaif how do these existing proposals look to you?

**Comment by shawnborton** [comment] 2023-08-02 15:03
Hmm do we really want absolutely zero padding there on the top of each page? Maybe we standardize with just 12px of top padding.

**Comment by shawnborton** [comment] 2023-08-02 15:17
I'm not sure if I agree though, that's why those pages currently have padding - sometimes it looks nicer if we have just a little bit of separation from the header above. Maybe we can just close this one out entirely actually and not worry about it?

**Comment by MitchExpensify** [comment] 2023-08-02 20:23
Not overdue, Melvin. Active discussion is happening here

**Comment by MitchExpensify** [comment] 2023-08-09 19:46
> hey @aimane-chnaif do you think any of the pages need to remove extra spacing on this https://github.com/Expensify/App/issues/23496#issuecomment-1658705540 or just closed as per this comment https://github.com/Expensify/App/issues/23496#issuecomment-1662402851

@aimane-chnaif friendly bump on this latest Q

**Comment by shawnborton** [comment] 2023-08-14 13:13
If we do anything, I think we should standardize on having 12px of padding below the page header component everywhere.

**Comment by MitchExpensify** [comment] 2023-08-21 20:08
@dhairyasenjaliya it looks like @aimane-chnaif responded to your last question [here](https://github.com/Expensify/App/issues/23496#issuecomment-1683858878). Anything else needed to keep moving this forward?

**Comment by MitchExpensify** [comment] 2023-08-25 22:48
> @dhairyasenjaliya it looks like @aimane-chnaif responded to your last question https://github.com/Expensify/App/issues/23496#issuecomment-1683858878. Anything else needed to keep moving this forward?

Friendly bump @dhairyasenjaliya

**Comment by MitchExpensify** [comment] 2023-08-29 04:48
@aimane-chnaif What do you recommend to keep this moving along? Seems we're stuck at this point

**Comment by MitchExpensify** [comment] 2023-08-30 03:52
Thank you @dhairyasenjaliya , that would be great! 👍

**Comment by Skalakid** [comment] 2023-09-04 08:25
Hey I’m Michał from Software Mansion, an expert agency, and I will help close this issue out 😄

**Comment by Skalakid** [comment] 2023-09-04 08:43
@aimane-chnaif is there any reason why we omitted the @kbecciv proposal? Also, it's worth noticing that  https://github.com/Expensify/App/issues/23496#issuecomment-1648309510 and https://github.com/Expensify/App/issues/23496#issuecomment-1648310048 are the same 😅

**Comment by Skalakid** [comment] 2023-09-04 09:24
## Proposal

### Please re-state the problem that we are trying to solve in this issue.

Some of the pages in our app have additional top padding between the header and content

### What is the root cause of that problem?

The padding below the header wasn't standardized and while creating other pages some of them added padding and some of them didn't

### What changes do you think we should make in order to solve the problem?


According to https://github.com/Expensify/App/issues/23496#issuecomment-1677291551 we should standardize 12px padding below the header. To do that we should add `styles.mb3` in HeaderWithBackButton

https://github.com/Expensify/App/blob/53ac4eeed813b1ea355081622dad8a07e4a9539e/src/components/HeaderWithBackButton/index.js#L55

Thanks to this change all pages will have a 12px margin below the header, so the spacing will be standardized. Instead of a margin, we can use padding (`styles.pb3`). However, I think in this case margin will be more accurate since changing the shape of the `HeaderWithBackButton` isn't needed. We only want to add spacing.


After this change, we should remove additional top paddings/margins inside of:
- Priority mode page
- PayPal page
- ContactMethodsPage
- ContactMethodDetailsPage
- App download link
- About page
- WorkspaceMembersPage
- ReimbursementAccountPage

**Comment by MitchExpensify** [comment] 2023-09-05 11:19
How do all the latest proposals and comments look to your @aimane-chnaif ?

**Comment by Skalakid** [comment] 2023-09-11 11:34
@aimane-chnaif you're right, I forgot to address your [comment](https://github.com/Expensify/App/issues/23496#issuecomment-1683858878) about ScrollViews. I can't think of any solution that will solve it automatically for ever page. I think in this situation we can either manually go threw every page and add `paddingTop: 12` for every component under `HeaderWithBackButton` + write style guidelines for creating new pages. Or go with https://github.com/Expensify/App/issues/23496#issuecomment-1704919795 and manually add `{ marginTop: -12, paddingTop: 12 }` for every ScrollView below `HeaderWithBackButton`

**Comment by Skalakid** [comment] 2023-09-14 13:09
@marcochavezf bump

**Comment by marcochavezf** [comment] 2023-09-15 13:05
Sorry guys, given that from a design point of view this is not a problem and there's no general solution, I'm leaning towards closing the issue. I agree that the padding looks nicer and I don't find a reason to change it. We can re-open if someone disagrees with a counterargument.

**Closed by marcochavezf** 2023-09-15 13:05 UTC
Labels: Daily, Internal, Overdue, Bug
