### ISSUE TITLE
[$500] IOU - User cannot enter an amount like 0.XX, starting with separator [ . ] without 0

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#9389] opened 2022-06-09 22:46 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Launch the app
2. Log n with any account
4. Tap on "Green plus button"
5. Start entering an amount like 0.XX without entering 0, as in all calculators, starting with the separator [ . ]

## Expected Result:
You can enter an amount like 0.XX without entering 0 - .XX

## Actual Result:
User cannot enter an amount like 0.XX without entering 0. In this case, you will enter XX instead of .XX

## Workaround:
Uknown

## Platform:

Where is this issue occurring?

- Web
- iOS
- Android
- Desktop App
- Mobile Web

**Version Number:** 1.1.75.1

**Reproducible in staging?:** Yes

**Reproducible in production?:** Yes

**Email or phone of affected tester (no customers):** any

**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Notes/Photos/Videos:** Any additional supporting documentation

https://user-images.githubusercontent.com/93399543/172957712-95030deb-9ce9-49bc-afa2-468219f2aed4.mp4

**Expensify/Expensify Issue URL:** 

**Issue reported by:** Applause - Internal Team

**Slack conversation:** 

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by alex-mechler** [comment] 2022-06-09 23:14
Looks god to go external!

**Comment by sobitneupane** [comment] 2022-06-10 04:43
Is it expected to show .12 or 0.12 when user enters .12?
<img width="441" alt="Screen Shot 2022-06-10 at 10 10 31" src="https://user-images.githubusercontent.com/25876548/172990213-4f665fc4-8148-4cbc-8813-80a28fd97a97.png">
<img width="441" alt="Screen Shot 2022-06-10 at 10 10 38" src="https://user-images.githubusercontent.com/25876548/172990216-217a67a1-ec91-4c61-b243-d5afc47eccef.png">

### Proposal:

**To achieve .12, we need to update regex as**
https://github.com/Expensify/App/blob/1997b1cb6e55809fac2c578d6aaf5b1f9bc3e8a4/src/pages/iou/steps/IOUAmountPage.js#L121-L124
```diff
    validateAmount(amount) {
-        const decimalNumberRegex = new RegExp(/^\d+(,\d+)*(\.\d{0,2})?$/, 'i');
+        const decimalNumberRegex = new RegExp(/^(\.\d{0,2})$|^\d+(,\d+)*(\.\d{0,2})?$/, 'i');
        return amount === '' || (decimalNumberRegex.test(amount) && this.calculateAmountLength(amount) <= CONST.IOU.AMOUNT_MAX_LENGTH);
    }
```
Also, we need to add `isNaN(parseFloat(this.state.amount)` condition in `isDisabled` prop in Next `Button`

**TO achieve 0.12, we need to update text in `updateAmount()`**
https://github.com/Expensify/App/blob/1997b1cb6e55809fac2c578d6aaf5b1f9bc3e8a4/src/pages/iou/steps/IOUAmountPage.js#L165-L172
```diff
    updateAmount(text) {
+        text = text === "." ? "0." : text
        this.setState((prevState) => {
            const amount = this.replaceAllDigits(text, this.props.fromLocaleDigit);
            return this.validateAmount(amount)
                ? {amount: this.stripCommaFromAmount(amount)}
                : prevState;
        });
    }
```

**Comment by thesahindia** [comment] 2022-06-10 05:48
I don't think it's a bug. It's a feature request and it should be raised on slack so that we can decide if it's really needed.

**Comment by parasharrajat** [comment] 2022-06-10 08:31
Good point @thesahindia. I agree.

**Comment by parasharrajat** [comment] 2022-06-15 17:41
I am fine to deal with this change in this issue. The main question is do we need this change. If yes, let's move forward.

**Comment by stephanieelliott** [comment] 2022-06-16 00:29
Cool. Yeah, I do think this feels sub-premium and is something we should change. 

Posted to Upwork here: https://www.upwork.com/jobs/~0113a7f5cc68f234cc

@parasharrajat, can you review the proposal [here](https://github.com/Expensify/App/issues/9389#issuecomment-1151933481) when you get a chance?

**Comment by rushatgabhane** [comment] 2022-06-16 12:19
> Is it expected to show .12 or 0.12 when user enters .12?

`0.12` would break form guidelines by modifying the user input.

So `.12` sounds good to me!

**Comment by parasharrajat** [comment] 2022-06-23 17:50
Allowing the user to enter `.12` Will be problematic. This is not a valid number and we can't modify the user input while he is typing. 

I think we don't need to change this.

**Comment by stephanieelliott** [comment] 2022-06-23 19:19
Why is this not a valid number? `.12` is a fraction of a whole dollar (or relevant currency). There are definitely use cases where someone would create an IOU for an amount that is less than a whole dollar. 

May be helpful to get additional opinions on this, I posted it to Slack for discussion: https://expensify.slack.com/archives/C01GTK53T8Q/p1656011822536519

@parasharrajat can you jump in that Slack thread and lend some more context into why this would be problematic?

**Comment by parasharrajat** [comment] 2022-06-24 21:44
Ok, we finalized that it would be great to have the following.

1. Start with 0 always.
2. As soon as user types any number other than 0, 0 on the screen is replaced with that.
3. If user types a `.` , UI would become `0.` .

@sobitneupane What do you think?

**Comment by sobitneupane** [comment] 2022-06-27 10:41
Few questions:
1. What is the expected amount when user types another 0? (0 or 00)
2. What if user presses backspace? (0 or '')

**Comment by parasharrajat** [comment] 2022-06-27 15:14
1. It will become 0.00. 
2. 0 is just representational. Real value does not have to do anything with this.

Now it's on you to suggest different approaches.

**Comment by sobitneupane** [comment] 2022-06-28 08:59
> 1\. It will become 0.00.

You got me wrong.
Initially, we will be showing "0". What if user types or presses another 0? Will it be just "0" or "00"?

> 2\. 0 is just representational. Real value does not have to do anything with this.

Does it mean, 0 is just a placeholder?

**Comment by parasharrajat** [comment] 2022-06-28 19:08
> Does it mean, 0 is just a placeholder?

That said, I am open to hearing different solutions. One might be just be working with a placeholder.

> Initially, we will be showing "0". What if the user types or presses another 0? Will it be just "0" or "00"?

It totally depends on how we implement this. But I think it would be 0.

1. Start with 0. 
2. Pressing 0 keeps zero.
3. Pressing . adds 0.
4. Pressing any non-zero number replaces 0.

**Comment by rushatgabhane** [comment] 2022-06-30 01:41
> But as you mentioned before, it might be against the guidelines "Input should not be modified".

@sobitneupane that's a good catch. But we're treating this as an exception ([slack](https://expensify.slack.com/archives/C01GTK53T8Q/p1656017709523529?thread_ts=1656011822.536519&cid=C01GTK53T8Q))

> I think the better approach will be to allow ".12" as the guidelines also suggest [Instead we will format and clean the user input internally before using the value](https://github.com/Expensify/App/blob/main/FORMS.md#modifying-user-input-on-change)

In general, we don't like this idea because you could mistake .12 cents as 12 dollars ([slack](https://expensify.slack.com/archives/C01GTK53T8Q/p1656015512332769?thread_ts=1656011822.536519&cid=C01GTK53T8Q))

**Comment by rushatgabhane** [comment] 2022-06-30 01:46
@sobitneupane @parasharrajat I think this is a good case where we poll the placeholder and non-placeholder approach on Slack. Videos would be nice :)

**Comment by sobitneupane** [comment] 2022-06-30 15:49
> In general, we don't like this idea because you could mistake .12 cents as 12 dollars ([slack](https://expensify.slack.com/archives/C01GTK53T8Q/p1656015512332769?thread_ts=1656011822.536519&cid=C01GTK53T8Q))

@rushatgabhane
> And the flip side of that is you if you were not paying attention, if we are ignoring the separator you could easily send $12 instead of the 12 cents you intended

I think she is talking about the present situation here. At present, when user types ".12" only "12" is typed as we are ignoring the separator.

> No, I think this would be adhering to the form guidelines, right?  i.e. if you input .12, we should treat it as 12 cents .
Right now if you input  .12 we are modifying it by ignoring the . and treating the input as  $12.

([slack](https://expensify.slack.com/archives/C01GTK53T8Q/p1656015110751979?thread_ts=1656011822.536519&cid=C01GTK53T8Q))

**Comment by parasharrajat** [comment] 2022-06-30 16:21
Good points @rushatgabhane. I can raise that poll but I don't see any proposal on the non-placeholder(real 0 value) approach so I am currently not sure of the complexity and feasibility of that solution.

**Comment by parasharrajat** [comment] 2022-07-04 09:47
Please share your point of view on https://expensify.slack.com/archives/C01GTK53T8Q/p1656927815193059.

**Comment by parasharrajat** [comment] 2022-07-12 12:38
Ok, we have a conclusion on slack.

> Pressing `.` shows `0.` on the screen.


Please bring your proposals for the above behavior.

**Comment by mdneyazahmad** [comment] 2022-07-12 13:10
@parasharrajat do you think my [proposal](https://github.com/Expensify/App/issues/9389#issuecomment-1173468282) does the same thing?

**Comment by parasharrajat** [comment] 2022-07-12 13:28
It is incomplete.

**Comment by stephanieelliott** [comment] 2022-07-13 15:51
Reassigning this as I am going OOO, thanks @adelekennedy!

**Comment by eVoloshchak** [comment] 2022-07-13 21:23
**Proposal:**
We can extend [stripCommaFromAmount](https://github.com/Expensify/App/blob/bc7be6fe7c8f424bd921b490823cd0cd4a842e08/src/pages/iou/steps/IOUAmountPage.js#L132) (will probably need a different name), since it gets called for both cases: when user uses on-screen keyboard and when using device keyboard

```javascript
  stripCommaFromAmount(amount) {
      let formattedAmount = amount.replace(/,/g, '');
      if (formattedAmount === '.') {
          formattedAmount = '0.'
      }
      return formattedAmount;
  }
```

And we will also need to change both `updateAmount` and `updateAmountNumberPad` so they call `stripCommaFromAmount` before validating the amount
```diff
updateAmountNumberPad(key) {
    // Backspace button is pressed
    if (key === '<' || key === 'Backspace') {
        if (this.state.amount.length > 0) {
            this.setState(prevState => ({
                amount: prevState.amount.slice(0, -1),
            }));
        }
        return;
    }

    this.setState((prevState) => {
-       const amount = `${prevState.amount}${key}`;
-       return this.validateAmount(amount) ? {amount: this.stripCommaFromAmount(amount)} : prevState;
+       const amount = this.stripCommaFromAmount(`${prevState.amount}${key}`);
+       return this.validateAmount(amount) ? {amount} : prevState;
    });
}
```

```diff
updateAmount(text) {
    this.setState((prevState) => {
-       const amount = this.replaceAllDigits(text, this.props.fromLocaleDigit);
-       return this.validateAmount(amount)
-           ? {amount: this.stripCommaFromAmount(amount)}
-           : prevState;
+       const amount = this.stripCommaFromAmount(this.replaceAllDigits(text, this.props.fromLocaleDigit));
+       return this.validateAmount(amount) ? {amount} : prevState;
    });
}
```

**Result:**

https://user-images.githubusercontent.com/9059945/178838630-9ac4a03b-cbe5-4100-acca-9f6a563b97c0.mp4

**Comment by parasharrajat** [comment] 2022-07-13 22:28
Good catch @eVoloshchak. Yes, we need to update both `updateAmount and updateAmountNumberPad`. 

One for NumberPad and the other for the keyboard. But I don't think updating [stripCommaFromAmount](https://github.com/Expensify/App/blob/bc7be6fe7c8f424bd921b490823cd0cd4a842e08/src/pages/iou/steps/IOUAmountPage.js#L132) is a good idea. Instead, you can create a common method and use it.


This was missing from https://github.com/Expensify/App/issues/9389#issuecomment-1173468282 and *2 in https://github.com/Expensify/App/issues/9389#issuecomment-1151933481. 


I like the proposal from @eVoloshchak.


cc: @chiragsalian  

:ribbon: :eyes: :ribbon:  C+ reviewed

**Comment by adelekennedy** [comment] 2022-07-14 18:57
@eVoloshchak it looks like the job in Upwork expired, do you mind applying [here](https://www.upwork.com/ab/applicants/1547656178856574976/job-details)?

**Comment by parasharrajat** [comment] 2022-07-14 20:39
That URL is internal.

**Comment by eVoloshchak** [comment] 2022-07-14 20:44
> That URL is internal. Try https://upwork.com/jobs/~0107a668eb4a2cca3d/?link=title&n=0

This one works, thanks. It had the wrong price, I entered the correct one when submitting a proposal

**Comment by eVoloshchak** [comment] 2022-07-20 10:19
Opened a PR

**Comment by mvtglobally** [comment] 2022-08-09 04:38
Issue not reproducible during KI retests. (First week)

**Comment by eVoloshchak** [comment] 2022-08-12 09:32
This should have been paid yesterday, but I've failed to link the issue correctly, so the title isn't updated (will not happen again). And my proposal on Upwork is still pending

**Comment by mvtglobally** [comment] 2022-08-16 04:46
Issue not reproducible during KI retests. (Second week)

**Comment by adelekennedy** [comment] 2022-08-16 20:04
hired ✅

**Comment by adelekennedy** [comment] 2022-08-18 23:40
done and done

**Closed by adelekennedy** 2022-08-18 23:40 UTC
Labels: Reviewing, Exported, External, Engineering, Weekly
