### ISSUE TITLE
Email - email notification with the unread messages and IOU is not received

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#46121] opened 2024-07-24 13:48 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 9.0.11-2
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**If this was caught during regression testing, add the test name, ID and link from TestRail:** https://expensify.testrail.io/index.php?/tests/view/4757038
**Email or phone of affected tester (no customers):** gibethlehem@gmail.com
**Issue reported by:** Applause - Internal Team

## Action Performed:
1. Navigate to a 1:1 conversation with a user you have email inbox access - must be a main email address without the + iteration
2. Send some messages
3. Wait 10 minutes

## Expected Result:
Repeat step 1&2 for IOU email notification

## Actual Result:
User should receive a email notification with the unread messages of a chat and money request if the conversation has not been read in >10min

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details> 

<img width="1419" alt="56 03_PM" src="https://github.com/user-attachments/assets/71c6295b-8dfb-4b6b-b716-903c87a91533">

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by lanitochka17** [comment] 2024-07-24 13:49
@OfstadC  FYI I haven't added the External label as I wasn't 100% sure about this issue. Please take a look and add the label if you agree it's a bug and can be handled by external contributors

**Comment by lanitochka17** [comment] 2024-07-24 13:49
We think that this bug might be related to #vip-vsp

**Comment by MariaHCD** [comment] 2024-07-25 06:37
This is likely related to https://github.com/Expensify/Expensify/issues/215522

@lanitochka17 do you have the reportIDs of the reports you were supposed to get an email notification for?

**Comment by m-natarajan** [comment] 2024-07-27 20:22
Issue not reproducible by the tester.

**Comment by OfstadC** [comment] 2024-07-30 12:08
I'll try to reproduce again tomorrow when i'm back online - if not, I think we'll want to close this out ?

**Comment by OfstadC** [comment] 2024-08-01 20:25
I'm not able to reproduce - i'll set to weekly and try again next week

**Comment by MariaHCD** [comment] 2024-08-08 12:55
Oh, I believe this was related to our staging jobs [not being processed from Jul 24th - Jul 25th](https://expensify.slack.com/archives/C094TGUTZ/p1721866524892169). This should be resolved now.

However, if it happens again, it is might be related to https://github.com/Expensify/Expensify/issues/215522

**Comment by OfstadC** [comment] 2024-08-08 15:04
Thanks @MariaHCD ❤️  ! - Going to close for now since this is likely resolved as it isn't currently reproducible 😅

**Closed by OfstadC** 2024-08-08 15:04 UTC
Labels: Weekly, Bug
