### ISSUE TITLE
[$500] IOU - When we change category of manual request, a small shake can be seen

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#29877] opened 2023-10-18 16:30 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.3.86-0
**Reproducible in staging?:** Yes
**Reproducible in production?:** No
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** Applause - Internal Team
**Slack conversation:**

## Action Performed:
1. Go to https://staging.new.expensify.com/
2. Tap a Workspace chat
3. Tap plus icon near compose
4. Tap request money---Manual
5. Enter an amount
6. Tap next
7. Tap show more
8. Select a category
9. Tap Request
10. Tap on IOU created
11. Tap on IOU again to open IOU details page
12. Tap category and select some other category other than selected

## Expected Result:
When we change category of manual request, a small shake must not be seen

## Actual Result:
When we change category of manual request, a small shake can be seen

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [x] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos
<details>
<summary>Android: Native</summary>

</details>

<details>
<summary>Android: mWeb Chrome</summary>

 

https://github.com/Expensify/App/assets/78819774/2611046d-3d76-4eab-8e79-41a42a19cf6e

</details>

<details>
<summary>iOS: Native</summary>

</details>

<details>
<summary>iOS: mWeb Safari</summary>

</details>

<details>
<summary>MacOS: Chrome / Safari</summary>

</details>

<details>
<summary>MacOS: Desktop</summary>

 

https://github.com/Expensify/App/assets/78819774/cc725e71-9061-4893-932e-c942cac3da4e

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~0164196a630a5ccb5f</li>
        <li>Upwork Job ID: 1714699123316404224</li>
        <li>Last Price Increase: 2023-11-08</li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @muttmuure</details>

**Comment by neil-marcellini** [comment] 2023-10-18 17:31
I'm taking a look now

**Comment by neil-marcellini** [comment] 2023-10-18 17:39
I confirmed that it's not reproducible on production, but is on staging. However, it's a very minor bug so IMO we shouldn't block deploy on it. I'll check to see if the deployer agrees.

production


https://github.com/Expensify/App/assets/26260477/4469a6b7-62dc-4d16-8ad4-fa7fe10a97c6


staging


https://github.com/Expensify/App/assets/26260477/7c558898-3724-4da4-9211-1d2db62226c9

**Comment by neil-marcellini** [comment] 2023-10-18 17:44
@francoisl is the deployer and agrees [here](https://expensify.slack.com/archives/C07J32337/p1697650986633029?thread_ts=1697649556.402009&cid=C07J32337) (internally) that we can polish this later. I'm removing the blocker and making it external.

**Comment by neil-marcellini** [comment] 2023-10-23 17:54
Not overdue, waiting for proposals.

**Comment by brunovjk** [comment] 2023-10-24 12:38
@neil-marcellini I can't reproduce. In fact, I don't find a 'category' option, either when creating request
local:
![local](https://github.com/Expensify/App/assets/95647348/36b41805-3590-43e9-8bab-4b8bd0e09442)
staging:
![stag](https://github.com/Expensify/App/assets/95647348/34a1701e-ce0f-4221-bd5a-2afe0dcff9ab)

Do you have any idea what I could be doing wrong? Thanks.

**Comment by brunovjk** [comment] 2023-10-25 18:29
I can not reproduce

**Comment by neil-marcellini** [comment] 2023-10-31 17:50
Bump @muttmuure

**Comment by muttmuure** [comment] 2023-11-02 11:20
Having trouble getting into expensifail.com to test this because 2FA is required

**Comment by muttmuure** [comment] 2023-11-03 11:32
Still reproducible on staging

**Comment by erquhart** [comment] 2023-11-08 18:23
A duplicate was opened and has an accepted proposal: #30218

**Comment by muttmuure** [comment] 2023-11-14 21:11
Closing in favor of the other one

**Closed by muttmuure** 2023-11-14 21:10 UTC
Labels: External, Engineering, Daily, Help Wanted, Overdue, Bug
