### ISSUE TITLE
[HOLD for Payment 2024-08-22] [$250] Submit expense - Tabs disappear when changing from Scan to Distance via SHIFT+TAB

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#43719] opened 2024-06-13 18:21 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.83-0
**Reproducible in staging?:** Y
**Reproducible in production?:** N 
**If this was caught during regression testing, add the test name, ID and link from TestRail:** https://expensify.testrail.io/index.php?/tests/view/4626993
**Issue reported by:** Applause - Internal Team

## Action Performed:
1. Go to staging.new.expensify.com
2. Go to FAB > Submit expense
3. Go to Scan
4. Click on empty area on the RHP (like the empty header area)
5. Press SHIFT+TAB

## Expected Result:
Nothing will happen

## Actual Result:
RHP changes to Distance flow, and tabs (Manual, Scan, Distance) are missing

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details> 

https://github.com/Expensify/App/assets/78819774/d86b3e9c-7d57-4722-b6ae-547be8e690f1

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~0112bb5e5d8d723e7f</li>
        <li>Upwork Job ID: 1801340710232481793</li>
        <li>Last Price Increase: 2024-07-18</li>
<li>Automatic offers: </li>
<ul>
<li>rayane-djouah | Reviewer | 103221643</li>
<li>dominictb | Contributor | 103221644</li>
</ul></li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @rayane-djouah</details>

**Comment by lanitochka17** [comment] 2024-06-13 18:21
@tgolen  FYI I haven't added the External label as I wasn't 100% sure about this issue. Please take a look and add the label if you agree it's a bug and can be handled by external contributors

**Comment by lanitochka17** [comment] 2024-06-13 18:22
We think that this bug might be related to #vip-vsp

**Comment by tgolen** [comment] 2024-06-13 19:47
I'm demoting this one and assigning to external.

**Comment by tsa321** [comment] 2024-06-13 23:59
cannot reproduce in main. Offending PR: https://github.com/Expensify/App/pull/39520

**Comment by studentofcoding** [comment] 2024-06-14 10:22
Not produceable on Production and local

**Comment by vishnu-karuppusamy** [comment] 2024-06-14 13:56
## Proposal
### Please re-state the problem that we are trying to solve in this issue.
Pressing SHIFT+TAB on the top section of the RHP updates the contents of the RHP.

### What is the root cause of that problem?

- The current implementation has a common FocusTrap wrapper (`ScreenWrapper`) for all three screens (Manual, Scan & Distance).

```typescript
{* Common wrapper for all the three screens *}
<ScreenWrapper
    includeSafeAreaPaddingBottom={false}
    shouldEnableKeyboardAvoidingView={false}
    shouldEnableMinHeight={DeviceCapabilities.canUseTouchScreen()}
    headerGapStyles={isDraggingOver ? [styles.receiptDropHeaderGap] : []}
    testID={IOURequestStartPage.displayName}
>
    {({safeAreaPaddingBottomStyle}) => (
        <DragAndDropProvider
            setIsDraggingOver={setIsDraggingOver}
            isDisabled={selectedTab !== CONST.TAB_REQUEST.SCAN}
        >
            <View style={[styles.flex1, safeAreaPaddingBottomStyle]}>
                <HeaderWithBackButton
                    title={tabTitles[iouType]}
                    onBackButtonPress={navigateBack}
                />
                {iouType !== CONST.IOU.TYPE.SEND && iouType !== CONST.IOU.TYPE.PAY && iouType !== CONST.IOU.TYPE.INVOICE ? (
                    <OnyxTabNavigator
                        id={CONST.TAB.IOU_REQUEST_TYPE}
                        onTabSelected={resetIOUTypeIfChanged}
                        tabBar={TabSelector}
                    >
                        <TopTab.Screen name={CONST.TAB_REQUEST.MANUAL}>
                            {() => (
                                <IOURequestStepAmount
                                    shouldKeepUserInput
                                    route={route}
                                />
                            )}
                        </TopTab.Screen>
                        <TopTab.Screen name={CONST.TAB_REQUEST.SCAN}>{() => <IOURequestStepScan route={route} />}</TopTab.Screen>
                        {shouldDisplayDistanceRequest && <TopTab.Screen name={CONST.TAB_REQUEST.DISTANCE}>{() => <IOURequestStepDistance route={route} />}</TopTab.Screen>}
                    </OnyxTabNavigator>
                ) : (
                    <IOURequestStepAmount route={route} />
                )}
            </View>
        </DragAndDropProvider>
    )}
</ScreenWrapper>
``` 

- When a click is made on the top empty area on the RHP (like the empty header area), the focus gets initiated on the common FocusTrap wrapper. Pressing SHIFT+TAB focuses the last element on the DOM tree which is the `Next` button of the Distance screen. (In the issue repro video, we can observe that the `Next` button of the Distance screen is focused)
![image](https://github.com/Expensify/App/assets/133900001/783a31c4-b8f0-4773-85e5-ec09c826aef9)

- Because of the translating nature of the Tabs component `OnyxTabNavigator`, the tabs (Manual, Scan, Distance) are translated to the left by `750px` when the `Next` button of the Distance screen is focused. This is the reason behind missing of the tabs.

### What changes do you think we should make in order to solve the problem?

- Instead of having a common focus trap wrapper for all the screens, let's wrap each screen individually. By this approach, the focus of a screen remains trapped within the screen itself.

```typescript
<TopTab.Screen name={CONST.TAB_REQUEST.MANUAL}>
    {() => (
        <ScreenWrapper
            includeSafeAreaPaddingBottom={false}
            shouldEnableKeyboardAvoidingView={false}
            shouldEnableMinHeight={DeviceCapabilities.canUseTouchScreen()}
            headerGapStyles={isDraggingOver ? [styles.receiptDropHeaderGap] : []}
            testID={IOURequestStartPage.displayName}
        >
            {() => (
                <IOURequestStepAmount
                    shouldKeepUserInput
                    route={route}
                />
            )}
        </ScreenWrapper>
    )}
</TopTab.Screen>
``` 

### What alternative solutions did you explore? (Optional)

We can fix this issue also by not rendering the contents of other screens i.e. when the `Manual` screen is in view, the contents of the Split & Distance screens shouldn't be rendered.

**Comment by vishnu-karuppusamy** [comment] 2024-06-14 13:58
Contributor details
Your Expensify account email: vishnu566662@gmail.com
Upwork Profile Link: https://www.upwork.com/freelancers/~01fded0233eaf38db6

**Comment by OfstadC** [comment] 2024-06-17 18:01
@rayane-djouah could you please provide an update here by EOD?

**Comment by tsa321** [comment] 2024-06-18 03:44
## Proposal

### Please re-state the problem that we are trying to solve in this issue.

tab key navigation is broken in create IOU request RHP

### What is the root cause of that problem?

In IOURequestStartPage we disable tab key navigation by this code:

https://github.com/Expensify/App/blob/b33542383ac2cb8ea1e922aa12dd2265efccd0ab/src/pages/iou/request/IOURequestStartPage.tsx#L79-L92

Then when iouerqueststartpage rendered, all tab screen content are also rendered, which make tab key navigation jump to other tab screen.

###  What changes do you think we should make in order to solve the problem?

We must remove the code above that preventing tab key navigation.

Then in here:

https://github.com/Expensify/App/blob/b33542383ac2cb8ea1e922aa12dd2265efccd0ab/src/pages/iou/request/IOURequestStartPage.tsx#L154-L163

We return the content of tab screent to null if selectedTab isn't properly addressed for their screen name.

**Comment by tsa321** [comment] 2024-06-18 23:06
@rayane-djouah I am sorry there must be an error when I beautify the code.

please try this code:
```javascript
<TopTab.Screen name={CONST.TAB_REQUEST.MANUAL}>
        {() => (selectedTab === CONST.TAB_REQUEST.MANUAL) ? (
            <IOURequestStepAmount
                shouldKeepUserInput
                route={route}
            />
        ) : null}
    </TopTab.Screen>
    <TopTab.Screen name={CONST.TAB_REQUEST.SCAN}>{() => (selectedTab === CONST.TAB_REQUEST.SCAN) ? <IOURequestStepScan route={route} /> : null}</TopTab.Screen>
    {shouldDisplayDistanceRequest && <TopTab.Screen name={CONST.TAB_REQUEST.DISTANCE}>{() => selectedTab === CONST.TAB_REQUEST.DISTANCE ? <IOURequestStepDistance route={route} /> : null}</TopTab.Screen>}
```

**Comment by vishnu-karuppusamy** [comment] 2024-06-19 11:01
@rayane-djouah thanks for the reply. Please find the below explanation for the questions raised.

> Could you clarify the cause of the current incorrect TAB navigation behavior on these "request start" pages? When the TAB key is pressed on the Manual tab, the focus is stuck on the "Next" button, and it does not shift to the tab switching buttons, currency switcher, or the back button. Additionally, when clicking on another tab and then pressing the TAB key, the focus is stuck on that tab button (e.g., the Distance button).

> In contrast, the tab navigation works correctly in the assign task flow as seen here:

Irrespective of the pages, the TAB navigation behavior remains the same i.e. pressing TAB will move focus to the next interactive element in the DOM tree and SHIFT+TAB will move focus to the previous interactive element. 
In `assign task` flow, all the interactive elements (back button, title & description input and next button) are in the same DOM tree. Hence the TAB navigation behaviour works as expected.

In the `request start` pages, all the tabs content (Manuel, Split & Distance) are rendered simultaneously in the same DOM tree. So the TAB navigation behavior follows the below order.

1. RHP's header back button
2. All the tabBars buttons (Manual, Split & Distance)
3. Interactive elements in the Manual tab such as currency selection dropdown, amount input field & `Next` button.
4. Interactive elements in the Split tab such as `choose file` button & so on.
5. Interactive elements in the Distance tab such as Start & Stop menu items, Mapbox & `Next` button.

**Issue root cause explanation:**
- Clicking in the RHP header area activates the `focus-trap` within the RHP.
- Pressing TAB focuses the first element in the above order i.e. RHP's header back button.
- Pressing SHIFT+TAB moves focus to the previous interactive element in the above order i.e. from the first interactive element (RHP's header back button) to the last interactive element (`Next` button of the Distance tab).
![image](https://github.com/Expensify/App/assets/133900001/1475d333-4831-4a52-8600-1333ceee3580)

In-order to have correct TAB navigation behavior, I've updated the initial proposal as follows.

- Since the TAB navigation focus is already handled by `focus-trap` library, we can remove the below code block.
```typescript
useFocusEffect(
    useCallback(() => {
        const handler = (event: KeyboardEvent) => {
            if (event.code !== CONST.KEYBOARD_SHORTCUTS.TAB.shortcutKey) {
                return;
            }
            event.preventDefault();
            event.stopPropagation();
        };
        KeyDownPressListener.addKeyDownPressListener(handler);

        return () => KeyDownPressListener.removeKeyDownPressListener(handler);
    }, []),
);
``` 

- The fix for the issue is to only include the interactive elements of the focussed tab in the TAB navigation behavior order i.e. when the `Manual` tab is selected, the interactive elements of the Split & Distance tab should be removed from the TAB navigation tree by visually hiding them.
```typescript
<OnyxTabNavigator
    id={CONST.TAB.IOU_REQUEST_TYPE}
    onTabSelected={resetIOUTypeIfChanged}
    tabBar={TabSelector}
>
    <TopTab.Screen name={CONST.TAB_REQUEST.MANUAL}>
        {(props) => (
            <View style={{visibility: props?.navigation?.isFocused() ? 'visible' : 'hidden', flex: 1}}>
                <IOURequestStepAmount
                    shouldKeepUserInput
                    route={route}
                />
            </View>
        )}
    </TopTab.Screen>
    <TopTab.Screen name={CONST.TAB_REQUEST.SCAN}>
        {(props) => (
            <View style={{visibility: props?.navigation?.isFocused() ? 'visible' : 'hidden', flex: 1}}>
                <IOURequestStepScan route={route} />
            </View>
        )}
    </TopTab.Screen>
    {shouldDisplayDistanceRequest && (
        <TopTab.Screen name={CONST.TAB_REQUEST.DISTANCE}>
            {(props) => (
                <View style={{visibility: props.navigation.isFocused() ? 'visible' : 'hidden', flex: 1}}>
                    <IOURequestStepDistance route={route} />
                </View>
            )}
        </TopTab.Screen>
    )}
</OnyxTabNavigator>
``` 
With the above update, the contents of all the tabs are never re-rendered and only the visible elements are included in the TAB navigation tree.

**Comment by tsa321** [comment] 2024-06-19 12:21
@vishnu-karuppusamy I think what you suggested above is similar to my proposal and it is really different with your original proposal.

**Comment by vishnu-karuppusamy** [comment] 2024-06-19 16:24
> @vishnu-karuppusamy - The idea of setting the `hidden` style to tab screen content if it's not focused is working correctly, but I think that there is a better solution than that. I think that the a better solution is to use focus trap functionality to fix this issue.
> 
> @vishnu-karuppusamy - I dont't understand something in your proposal: `IOURequestStepAmount`, `IOURequestStepScan`, and `IOURequestStepDistance` all have a `ScreenWrapper` under the hood, I don't see why we need to wrap them with a `ScreenWrapper`.

Yes, I'm aware that `IOURequestStepAmount`, `IOURequestStepScan`, and `IOURequestStepDistance` all have a `ScreenWrapper` under the hood. But the RHP's header section and the tab button (Manual, Split & Distance) are not a part of each page's TAB navigation DOM tree.

**Comment by vishnu-karuppusamy** [comment] 2024-06-22 06:59
## Proposal
[Updated](https://github.com/Expensify/App/issues/43719#issuecomment-2168110266)

@rayane-djouah Updated the below sections:
1. What changes do you think we should make in order to solve the problem?
2. What alternative solutions did you explore? (Optional)

**Comment by tsa321** [comment] 2024-06-22 08:45
@rayane-djouah: If, for example (just for example) the alternative proposal from @vishnu-karuppusamy is accepted, I would argue based on:

https://github.com/Expensify/App/blob/b021195b864211efbaaefe188226b2830b91b7d8/contributingGuides/CONTRIBUTING.md

> After you reproduce the issue, complete the [proposal template here](https://github.com/Expensify/App/blob/b021195b864211efbaaefe188226b2830b91b7d8/contributingGuides/PROPOSAL_TEMPLATE.md) and post it as a comment in the corresponding GitHub issue (linked in the Upwork job).
> Note: Before submitting a proposal on an issue, be sure to read any other existing proposals. ALL NEW PROPOSALS MUST BE DIFFERENT FROM EXISTING PROPOSALS. The difference should be important, meaningful or considerable.

The alternative solution differs significantly from his initial proposal and closely aligns with mine.

**Comment by OfstadC** [comment] 2024-06-25 16:57
Friendly bump @rayane-djouah 😃

**Comment by vishnu-karuppusamy** [comment] 2024-06-26 03:52
> @vishnu-karuppusamy - `ScreenWrapper` should be included on all pages by our guidelines, Also removing `ScreenWrapper` from `IOURequestStartPage` causes the elements behind the right-hand panel to be focusable:
> 
> Video
>  Screen.Recording.2024-06-26.at.1.18.50.AM.mov 
> Also, I didn't understand the purpose of the other proposed changes.

@rayane-djouah with the proposed updates, the common `ScreenWrapper` for all the tabs is removed. But each tab has its own `ScreenWrapper` which is enabled.

The major difference from the initial proposal is that we are utilizing the prop `containerElements` from the `focus-trap-react` library. In the proposal the fix is only applied for the `IOURequestStartPage`, if needed, I can propose the same for the chat page as well.

https://github.com/Expensify/App/assets/133900001/932f99fe-a5d2-407f-b994-be0f1043e821

**Comment by vishnu-karuppusamy** [comment] 2024-06-26 03:55
> @vishnu-karuppusamy - I dont't understand something in your proposal: `IOURequestStepAmount`, `IOURequestStepScan`, and `IOURequestStepDistance` all have a `ScreenWrapper` under the hood, I don't see why we need to wrap them with a `ScreenWrapper`.

@rayane-djouah Based on your previous reply, I thought you suggested removing the wrapping `ScreenWrapper` if it's unnecessary.

**Comment by OfstadC** [comment] 2024-07-01 15:42
Any update @rayane-djouah ? 😃

**Comment by OfstadC** [comment] 2024-07-09 15:04
@rayane-djouah Sorry for the delay here as I was OoO. I've added this to Wave Collect and will update once we have a priority there.

**Comment by OfstadC** [comment] 2024-07-09 15:05
Cool it Melvin 😅

**Comment by trjExpensify** [comment] 2024-07-09 15:53
^^ Dammit, the sidepane jumped as I was trying to click the project. 😂

**Comment by OfstadC** [comment] 2024-07-11 16:06
I imagine a "Polish" doesn't need to be increased, but curious your thoughts @trjExpensify 😄

**Comment by trjExpensify** [comment] 2024-07-11 20:21
> I imagine a "Polish" doesn't need to be increased, but curious your thoughts @trjExpensify 😄

Agree.

**Comment by vishnu-karuppusamy** [comment] 2024-07-17 04:00
https://github.com/Expensify/App/issues/43719#issuecomment-2168110266

@rayane-djouah Updated the below sections:

What changes do you think we should make in order to solve the problem?
What alternative solutions did you explore? (Optional)

**Comment by OfstadC** [comment] 2024-07-18 13:21
Good timing @rayane-djouah - I was just typing a bump 😅 - Thanks you for updating! 😃

**Comment by mvtglobally** [comment] 2024-07-19 03:21
Issue not reproducible during KI retests. (First week)

**Comment by vishnu-karuppusamy** [comment] 2024-07-21 08:33
I would like to re-assist the solutions proposed as both the solutions proposed such as hiding the in-active tabs and the use of `containerElements` prop in the focus-trap-react were proposed initially by me.

@rayane-djouah could you please confirm the above statement?

cc: @OfstadC

**Comment by tgolen** [comment] 2024-07-22 17:06
I think we should try to have tab navigation anywhere we can, so if it's
possible to re-enable tab navigation (it sounds like it), then I think we
should do it. I'll wait for ^ question to be resolved before doing anything
here though.

**Comment by OfstadC** [comment] 2024-08-01 20:23
Any update here @dominictb @rayane-djouah ? 😃

**Comment by OfstadC** [comment] 2024-08-21 16:32
Thanks @rayane-djouah - since the automation failed. I'll posted the checklist below 😄 

- [ ] The PR that introduced the bug has been identified. Link to the PR:
- [ ] The offending PR has been commented on, pointing out the bug it caused and why, so the author and reviewers can learn from the mistake. Link to comment:
- [ ] A discussion in #expensify-bugs has been started about whether any other steps should be taken (e.g. updating the PR review checklist) in order to catch this type of bug sooner. Link to discussion:
- [ ] Determine if we should create a regression test for this bug.
- [ ] If we decide to create a regression test for the bug, please propose the regression test steps to ensure the same bug will not reach production again.

**Comment by OfstadC** [comment] 2024-08-22 19:12
# Payment Summary:
- @rayane-djouah paid $250 via Upwork
- @dominictb paid $250 via Upwork

**Closed** 2024-08-22 19:13 UTC
Labels: Reviewing, External, Engineering, Weekly, Bug
