### ISSUE TITLE
[$500] Welcome message received twice when joining the room and again when the role changed

### ISSUE THREAD

**Issue by m-natarajan** [Expensify/App#37258] opened 2024-02-27 03:29 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:**
**Reproducible in staging?:** needs reproduction
**Reproducible in production?:** needs reproduction
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** @kadiealexander 
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1708647751662189

## Action Performed:
1. Log in to OldDOt as user A
2. Create a collect workspace
3. Add user B as an employee
4. Log in to NewDot as user A
5. Create a room under the workspace created in step 2 and invite B
6. Log in as user B and confirm there is a welcome message in the room invited by user A
7. In OldDot update the user B role to `Workspace admin` from `employee` logging in as user A

## Expected Result:
User B should not see a 2nd welcome message in the room

## Actual Result:
There is a 2nd welcome message received for user B

## Workaround:
unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence
![Screen Shot 2024-02-26 at 10 24 42 PM](https://github.com/Expensify/App/assets/38435837/1685e6a4-1c10-487b-abc5-a52e4c4946f5)

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~0169f2e49ea854c33a</li>
        <li>Upwork Job ID: 1762319126210408448</li>
        <li>Last Price Increase: 2024-03-19</li>
    </ul>
</details>

**Comment by dylanexpensify** [comment] 2024-02-28 09:00
Nice - pending proposals!

**Comment by dylanexpensify** [comment] 2024-03-06 10:44
Apologies, I've been OOO sick, but getting to this today! @srikarparsi can you confirm the proposal and BE need?

**Comment by srikarparsi** [comment] 2024-03-07 08:08
Hey @dylanexpensify! Yes, this does look like this needs a BE change. Do you think you could check if there's a wave/vip it fits into. I'm working on two wave issues currently so will probably not be able to pick this up but maybe a volunteer would be willing?

**Comment by srikarparsi** [comment] 2024-03-11 08:56
Unassigning myself as I won't be able to work on this this week.

**Comment by dylanexpensify** [comment] 2024-03-13 10:07
Yes please @hoangzinh!!

**Comment by dylanexpensify** [comment] 2024-03-13 10:20
Could not reproduce this time, @kadiealexander @hoangzinh can you confirm if you can?

**Comment by pecanoro** [comment] 2024-03-15 20:28
@dylanexpensify Does this go under some specific wave? This is probably the regression of something

**Comment by dylanexpensify** [comment] 2024-03-18 21:09
@pecanoro yeah this belongs to #wave-collect I'd say! Or VIP-VSB, but confirming

**Comment by pecanoro** [comment] 2024-03-19 18:03
I was discussing this with @srikarparsi and we are not sure if the internal engineer has to fix it or the BZ member has to post in the corresponding wave issue to find a volunteer. Because of that, I am assigning back to @srikarparsi and I will ask in Slack.

**Comment by srikarparsi** [comment] 2024-03-20 03:13
Thanks @pecanoro for posting about the BZ process [here](https://expensify.slack.com/archives/C03TQ48KC/p1710872479950229)! @dylanexpensify do you think you could check see if there's any volunteers available to work on this? My plate is currently pretty full right now so I think I'll only be able to get to this late next week or the week after. But I do think it needs to be fixed internally.

**Comment by dylanexpensify** [comment] 2024-03-20 11:44
@srikarparsi I can do!

**Comment by dylanexpensify** [comment] 2024-03-20 14:29
[Posted here!](https://expensify.slack.com/archives/C066HJM2CAZ/p1710944974646309)

**Comment by dylanexpensify** [comment] 2024-03-25 19:51
bumped again

**Comment by dylanexpensify** [comment] 2024-03-29 13:18
Waiting for internal

**Comment by dylanexpensify** [comment] 2024-04-09 08:19
Will bump again today

**Comment by dylanexpensify** [comment] 2024-04-12 16:37
Not a huge priority yet

**Comment by dylanexpensify** [comment] 2024-04-15 10:51
Same as above, waiting for someone to take

**Comment by dylanexpensify** [comment] 2024-04-24 20:35
@m-natarajan can you repro still?

**Comment by dylanexpensify** [comment] 2024-04-29 10:14
Bump @m-natarajan

**Comment by dylanexpensify** [comment] 2024-05-01 07:42
Bump @m-natarajan

**Comment by dylanexpensify** [comment] 2024-05-07 11:19
Bump @m-natarajan

**Comment by dylanexpensify** [comment] 2024-05-14 12:33
@lanitochka17 can you check for us here, please?

**Comment by lanitochka17** [comment] 2024-05-15 00:42
@dylanexpensify I am not able to reproduce this issue on the latest build 1.4.73-7

![image](https://github.com/Expensify/App/assets/78819774/1111a8ed-3d23-4dbe-a3f8-e7e3dff8ecce)

but if someone has a reproduction, I’ll write again

**Comment by lanitochka17** [comment] 2024-05-17 13:26
@dylanexpensify The second tester also could not reproduce the error because No welcome message in the room. 
(expensifail and gmail account)


https://github.com/Expensify/App/assets/78819774/d879ef95-a610-4a13-a910-b878c1966a49


https://github.com/Expensify/App/assets/78819774/6a1b5988-8d88-4e50-96fa-daf51f6c929a

**Closed** 2024-05-21 20:22 UTC
Labels: External, Engineering, Daily, Internal, Overdue, Bug
