### ISSUE TITLE
[$500] Distance - Unable/Error to set distance rate if there are 8 or more leading zeros placed in the value

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#28650] opened 2023-10-02 20:12 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Open ND app -> Settings -> Workspaces -> Reimbursement
2. Open distance rate from "Track Distance"
3. Place 8 zeroes than 1 in the field
4. Observer the result (User is unable to save the rate)

## Expected Result:
App should parse the leading zeros and save the rate

## Actual Result:
App should parse the leading zeros and save the rate

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android / native
- [x] Android / Chrome
- [x] iOS / native
- [x] iOS / Safari
- [x] MacOS / Chrome / Safari
- [x] MacOS / Desktop

**Version Number:** 1.3.76.0
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/93399543/07306338-a580-4784-bb72-2d4c95114528

https://github.com/Expensify/App/assets/93399543/517bbfba-53a6-4b11-b0f9-b5bcbdc8b4ab

https://github.com/Expensify/App/assets/93399543/5e3d12f8-89ba-48c8-a666-f5cbfce400b6

https://github.com/Expensify/App/assets/93399543/1d603fa6-698f-47b0-807e-957e1b48353a

https://github.com/Expensify/App/assets/93399543/3f3d76f0-500c-4783-8c3e-81636940b383

https://github.com/Expensify/App/assets/93399543/b109163f-d0c5-4de7-ba64-9da7152b9eb2

https://github.com/Expensify/App/assets/93399543/a77592b8-ebc7-4296-813a-0d258d334fa1

**Expensify/Expensify Issue URL:**
**Issue reported by:** @ufumerfarooq
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1696248962827629

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~0104aa1f7dbb253748</li>
        <li>Upwork Job ID: 1708938053846368256</li>
        <li>Last Price Increase: 2023-10-02</li>
    </ul>
</details>

**Comment by rakshitjain13** [comment] 2023-10-02 20:14
## Proposal
### Please re-state the problem that we are trying to solve in this issue.
Unable/Error to set distance rate if there are 8 or more leading zeros placed in the value
### What is the root cause of that problem?
In ````src/pages/workspace/reimburse/WorkspaceRateAndUnitPage.js```` in validate function, the regex function to check rate is causing the issue .https://github.com/Expensify/App/blob/a4b3669ea310f637638445b3c61c99f52871dfcf/src/pages/workspace/reimburse/WorkspaceRateAndUnitPage.js#L137
Here above condition says that the total number of digits on the left side of the decimal should be of max 8 digits and on the right max 3 digits.
### What changes do you think we should make in order to solve the problem?
We have to parse the string to float first so that we can remove the leading zeros and trailing zeroes of the decimal part .
Like 0000000043.4250000 => 43.425 .
For the above solution, we have to add another line in the code before validation . i.e.
```
         // parse value.rate
        values.rate = parseFloat(values.rate).toString();
        const rateValueRegex = RegExp(String.raw`^-?\d{0,8}([${getPermittedDecimalSeparator(decimalSeparator)}]\d{1,3})?$`, 'i');
        if (!rateValueRegex.test(values.rate) || values.rate === '') {
            errors.rate = 'workspace.reimburse.invalidRateError';
        } else if (parseFloat(values.rate) <= 0) {
            errors.rate = 'workspace.reimburse.lowRateError';
        }
```
### What alternative solutions did you explore? (Optional)
We can also change the regex function to change from 8 to 12 digits on max left side digits from decimal.
```
        const rateValueRegex = RegExp(String.raw`^-?\d{0,12}([${getPermittedDecimalSeparator(decimalSeparator)}]\d{1,3})?$`, 'i');
```

**Comment by paultsimura** [comment] 2023-10-03 13:41
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
The workspace rate doesn't allow 8+ leading zeros

### What is the root cause of that problem?
We limit the number of digits before the separator to 8:

https://github.com/Expensify/App/blob/bddd367fb0856c975ebee92d9bd54fe5f08a3d85/src/pages/workspace/reimburse/WorkspaceRateAndUnitPage.js#L137

### What changes do you think we should make in order to solve the problem?
In the validation RegExp, we should ignore the leading zeros while counting the digits before the separator.

```diff
    validate(values) {
        const errors = {};
        const decimalSeparator = this.props.toLocaleDigit('.');
+       const rateValueRegex = RegExp(String.raw`^-?0*\d{0,8}([${getPermittedDecimalSeparator(decimalSeparator)}]\d{1,3})?$`, 'i');
-       const rateValueRegex = RegExp(String.raw`^-?\d{0,8}([${getPermittedDecimalSeparator(decimalSeparator)}]\d{1,3})?$`, 'i');
        if (!rateValueRegex.test(values.rate) || values.rate === '') {
            errors.rate = 'workspace.reimburse.invalidRateError';
        } else if (parseFloat(values.rate) <= 0) {
            errors.rate = 'workspace.reimburse.lowRateError';
        }
        return errors;
    }
```

### What alternative solutions did you explore? (Optional)

**Comment by bfitzexpensify** [comment] 2023-10-03 18:01
This is an extreme edge case - I can't imagine why someone would add 8 leading zeroes. I can see someone adding one or two, but considering it already parses correctly for 7 or less zeroes, I don't think this is something we need to address. I'm going to close this one out.

**Closed by bfitzexpensify** 2023-10-03 18:01 UTC
Labels: External, Daily, Help Wanted, Bug
