### ISSUE TITLE
[$1000] "Start a call" icon is hidden in Concierge message reply thread when new notification arrives.

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#21581] opened 2023-06-26 16:00 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Click on the plus sign.
2. Select "New Chat" and search for a new email.
3. Hover over the Concierge message and go to Reply Threads.
4. The "Start a call" icon is hidden in the right corner when a new

## Expected Result:
The "Start a call" icon should be visible in the reply thread when a new Concierge message notification arrives.

## Actual Result:
The "Start a call" icon is hidden in the reply thread of the Concierge message when a new notification arrives.

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [x] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 1.3.32.5
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/93399543/2167d60e-297d-45e5-b8f6-0efccf2f6473

https://github.com/Expensify/App/assets/93399543/3cf2e1eb-9511-4c46-a12f-bfaeb4e411af

**Expensify/Expensify Issue URL:**
**Issue reported by:** @tewodrosGirmaA
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1687435466604789

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01fe0835cd624917ac</li>
        <li>Upwork Job ID: 1673371309895467008</li>
        <li>Last Price Increase: 2023-06-26</li>
    </ul>
</details>

**Comment by s77rt** [comment] 2023-06-26 22:55
@lschurr I don't think this is a bug. This seems to be the expected behaviour. The call option should be available on Concierge only if you have a guide for your account. Can you please confirm the same?

**Comment by lschurr** [comment] 2023-06-26 23:35
Yep I agree @s77rt. Let's close this one.

**Closed by lschurr** 2023-06-26 23:35 UTC
Labels: External, Daily, Help Wanted, Bug
