### ISSUE TITLE
[$250] Android - Chat - Emoji list in the emoji picker is misaligned

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#34522] opened 2024-01-15 17:48 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.25-2
**Reproducible in staging?:** Y
**Reproducible in production?:** N
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** Applause - Internal Team
**Slack conversation:**

## Action Performed:

Precondition: User account has a few emojis in the emoji recently used history

1. Go to any chat
2. Open emoji picker

## Expected Result:
Emoji list in the emoji picker is aligned properly

## Actual Result:
Emoji list in the emoji picker is misaligned

## Workaround:
Unknown

## Platforms:

So far we have been only able to reproduce in specific devices:
- Samsung Galaxy Note 10+
- Pixel 7 Pro

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native (only specific devices, see list above)
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [ ] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details> 

https://github.com/Expensify/App/assets/78819774/55e64faa-cb81-4164-8943-70257fa15df9

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~0142f3abb24fd4c0ef</li>
        <li>Upwork Job ID: 1746982665813213184</li>
        <li>Last Price Increase: 2024-02-05</li>
<li>Automatic offers: </li>
<ul>
<li>s77rt | Reviewer | 0</li>
</ul></li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @JmillsExpensify</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @JmillsExpensify</details>

**Comment by mountiny** [comment] 2024-01-15 19:49
@lanitochka17 @kavimuru  is this reliable report across android devices?

**Comment by aldo-expensify** [comment] 2024-01-15 21:34
I'm failing to reproduce in Android native.

**Comment by mountiny** [comment] 2024-01-16 12:25
@lanitochka17 @kavimuru @mvtglobally Can you please retest again/ add better reproduction steps if still repro under some specific ocnditions? thanks

**Comment by lanitochka17** [comment] 2024-01-16 16:54
@mountiny Issue is still reproducible on the latest build v.1.4.25-7 with a new account. There is no specific conditions.
Samsung Galaxy Note 10+ / Android 12


https://github.com/Expensify/App/assets/78819774/f0b594af-e420-4b4b-a960-9a8efe872531

**Comment by lanitochka17** [comment] 2024-01-16 16:55
https://github.com/Expensify/App/assets/78819774/2d7297fe-e246-4e40-91b4-8f2e37b2950e

**Comment by aldo-expensify** [comment] 2024-01-16 19:15
I tested with the account applausetester+kh170101@applause.expensifail.com (same account used [here](https://github.com/Expensify/App/issues/34522#issuecomment-1894136136)) in staging in Android native, and couldn't reproduce:

![Screenshot_20240116-161237](https://github.com/Expensify/App/assets/87341702/cb500cec-03cb-4235-946f-38a865f86a28)


I'm guessing that this can only be reproduced in very specific devices like: Samsung Galaxy Note 10+ / Android 12

**Comment by mountiny** [comment] 2024-01-16 23:42
@lanitochka17 can you update the op with the specific device and os version? 

Ideally we can know how common this is, if its an outlier we can close but i think we should try to confirm that somehow

@mvtglobally could your team please check this on various android devices and versions?

**Comment by samilabud** [comment] 2024-01-17 00:05
> @lanitochka17 can you update the op with the specific device and os version?
> 
> Ideally we can know how common this is, if its an outlier we can close but i think we should try to confirm that somehow
> 
> @mvtglobally could your team please check this on various android devices and versions?

I tried in v1.4.25-9:
<img width="362" alt="image" src="https://github.com/Expensify/App/assets/5216036/00c7ba2d-8cf9-4541-8366-9de17a4cfd6e">

**Comment by samilabud** [comment] 2024-01-17 14:16
> @samilabud which phone or simulator did you use to reproduce this?

I use this:
<img width="244" alt="image" src="https://github.com/Expensify/App/assets/5216036/c9946148-85b7-4d93-818e-ad37977b41c5">
But everything seems to be related to small resolutions.

**Comment by aldo-expensify** [comment] 2024-01-17 17:30
Reproduced with Pixel 7 Pro simulator:
<img width="414" alt="image" src="https://github.com/Expensify/App/assets/87341702/fea2cb69-7cd8-42f9-b9b6-7f87bacaa897">

**Comment by aldo-expensify** [comment] 2024-01-17 17:51
@mountiny we have two different devices where we can reproduce this, do you know where do we draw the line of donothing vs fix? @samilabud found a way to fix it [here](https://github.com/Expensify/App/issues/34522#issuecomment-1894713210), maybe we should go with that and leave a comment in the fix so it doesn't get removed

**Comment by mountiny** [comment] 2024-01-18 02:26
@aldo-expensify I think if the solution is simple then we can go ahead, from the proposal it seems quite simple as this makes the app look quite bad when it occurs to the user

I would say we do nothing if the solution would be some really bad/ complicated workaround

**Comment by marcaaron** [comment] 2024-01-18 18:48
Just dropping this here to see whatever fix for this ends up fixing [this other issue reported recently](https://expensify.slack.com/archives/C049HHMV9SM/p1705547392860459).

**Comment by s77rt** [comment] 2024-01-19 02:22
@samilabud Thanks for the proposal. I have few questions 

> when the resolution is small the Header and Emojis are too close and the header is mixed with the emojis and get misaligned

Why this seem only to happen on Android? I tried doing the same on mWeb and changing the resolution did not have any effect


> Right now we are using exactly the same windowWidth that comes from the hook [useWindowDimensions](https://github.com/Expensify/App/blob/1bcccc6669fddc41597980ca97fa1cb4350efb54/src/components/EmojiPicker/EmojiPickerMenu/BaseEmojiPickerMenu.js#L113) but we are adding a horizontal padding to the container that makes the estimated calculation erroneous, this causes the strange behavior to occur

In that case shouldn't omitting `contentContainerStyle` fix the bug?

**Comment by samilabud** [comment] 2024-01-19 03:56
> @samilabud Thanks for the proposal. I have few questions
> 
> > when the resolution is small the Header and Emojis are too close and the header is mixed with the emojis and get misaligned
> 
> Why this seem only to happen on Android? I tried doing the same on mWeb and changing the resolution did not have any effect
> 
> > Right now we are using exactly the same windowWidth that comes from the hook [useWindowDimensions](https://github.com/Expensify/App/blob/1bcccc6669fddc41597980ca97fa1cb4350efb54/src/components/EmojiPicker/EmojiPickerMenu/BaseEmojiPickerMenu.js#L113) but we are adding a horizontal padding to the container that makes the estimated calculation erroneous, this causes the strange behavior to occur
> 
> In that case shouldn't omitting `contentContainerStyle` fix the bug?

Hey, thanks for checking out, as far I can see this is not happening in web becase we are using different render function for each one, [this is for android](https://github.com/Expensify/App/blob/7c27f51a2f28cd83604008ddb7b0aee0f7635202/src/components/EmojiPicker/EmojiPickerMenu/index.native.js#L81) and [this is for web](https://github.com/Expensify/App/blob/7c27f51a2f28cd83604008ddb7b0aee0f7635202/src/components/EmojiPicker/EmojiPickerMenu/index.js#L329).

Regarding to the second question that was my first attempt, but it seems that for the [FlashList](https://github.com/Expensify/App/blob/main/src/components/EmojiPicker/EmojiPickerMenu/BaseEmojiPickerMenu.js) component we need exactly the same size than the estimated one:
https://github.com/Expensify/App/blob/1bcccc6669fddc41597980ca97fa1cb4350efb54/src/components/EmojiPicker/EmojiPickerMenu/BaseEmojiPickerMenu.js#L136-L137

**Comment by s77rt** [comment] 2024-01-20 19:48
@samilabud Although your solution works, I still don't understand why it works. We are probably fixing one resolution and breaking another. I think we are missing something here. Perhaps this is a bug in FlashList?

> as far I can see this is not happening in web becase we are using different render function for each one

Even if we render the same components still not able to reproduce on mWeb

> but it seems that for the [FlashList](https://github.com/Expensify/App/blob/main/src/components/EmojiPicker/EmojiPickerMenu/BaseEmojiPickerMenu.js) component we need exactly the same size than the estimated one

I don't think that's the case. I can even go with `paddingHorizontal: 80` and get it to work

**Comment by samilabud** [comment] 2024-01-20 21:56
> @samilabud Although your solution works, I still don't understand why it works. We are probably fixing one resolution and breaking another. I think we are missing something here. Perhaps this is a bug in FlashList?
> 
> > as far I can see this is not happening in web becase we are using different render function for each one
> 
> Even if we render the same components still not able to reproduce on mWeb
> 
> > but it seems that for the [FlashList](https://github.com/Expensify/App/blob/main/src/components/EmojiPicker/EmojiPickerMenu/BaseEmojiPickerMenu.js) component we need exactly the same size than the estimated one
> 
> I don't think that's the case. I can even go with `paddingHorizontal: 80` and get it to work

Got it I'm going to try to reproduce it on the web, but yesterday when I was doing another proposal I saw the same happening in a IPad when switching from landscape to portrait.

BTW I was looking deeper I saw in the official documentation the next explanation of the parameter [numColumns](https://reactnative.dev/docs/flatlist#numcolumns) maybe it will make more sense to you for my current solution:
`Multiple columns can only be rendered with horizontal={false} and will zig-zag like a flexWrap layout. Items should all be the same height - masonry layouts are not supported.`

**Comment by s77rt** [comment] 2024-01-21 18:04
@samilabud Thanks. Let's continue the investigation here 🔍 Also if possible try to reproduce the bug on any IOS device that have same resolution as Pixel 7 Pro or Galaxy Note 10+ (if there is any)

**Comment by samilabud** [comment] 2024-01-21 19:54
> @samilabud Thanks. Let's continue the investigation here 🔍 Also if possible try to reproduce the bug on any IOS device that have same resolution as Pixel 7 Pro or Galaxy Note 10+ (if there is any)

I have tried in Iphone 15 (2556 x 1179 Pixel) and Iphone SE (1334 x 750 pixels) it is reproducible in both:

https://github.com/Expensify/App/assets/5216036/96f34f72-4952-473a-9afa-04ee13a18617

https://github.com/Expensify/App/assets/5216036/c57fc49a-d371-4921-ad19-0296f55b56d4


However to resolve the bug in this platform we had to increase one point (to what I said in my proposal) the margin top in emojiHeaderContainer:
https://github.com/Expensify/App/blob/eb47b90a81f4c898a6aba728fe9abbeddfa82f2f/src/styles/index.ts#L1902-L1907

I mean it works with:
```
emojiHeaderContainer: {
            backgroundColor: theme.componentBG,
            display: 'flex',
            height: CONST.EMOJI_PICKER_HEADER_HEIGHT,
            justifyContent: 'center',
            marginTop: 2,
        }
```

**Comment by s77rt** [comment] 2024-01-22 14:31
@samilabud Increasing the margin does not make any sense. The fact that we needed to add 1px on some devices and 2px on others indicates that this is only a workaround that somehow fixes the bug.

**Comment by samilabud** [comment] 2024-01-22 14:57
> @samilabud Increasing the margin does not make any sense. The fact that we needed to add 1px on some devices and 2px on others indicates that this is only a workaround that somehow fixes the bug.

Got it thanks 👍

**Comment by s77rt** [comment] 2024-01-25 18:29
Not overdue. Still looking for proposals

**Comment by s77rt** [comment] 2024-01-29 18:12
Not overdue. Still looking for proposals

**Comment by dragnoir** [comment] 2024-01-29 19:16
Will not be fixed with PR https://github.com/Expensify/App/pull/34581?

**Comment by s77rt** [comment] 2024-01-30 07:35
@dragnoir I don't see how that PR is related to this issue

**Comment by s77rt** [comment] 2024-02-01 22:19
Still looking for proposals...

**Comment by s77rt** [comment] 2024-02-05 14:39
Not overdue. Still looking for proposals

**Comment by JmillsExpensify** [comment] 2024-02-07 16:33
Still looking for proposals.

**Comment by dragnoir** [comment] 2024-02-10 14:29
## Proposal

### Please re-state the problem that we are trying to solve in this issue.

Emoji icons are not aligned as it should be.

### What is the root cause of that problem?

The issue is with this prop
https://github.com/Expensify/App/blob/aadf04769b5fe181c5c01dea1f30c1e4b02bb3e2/src/components/EmojiPicker/EmojiPickerMenu/BaseEmojiPickerMenu.js#L137

The `width` value is set with a wrong value, `392.72727272727275` when I tested 

To test this root cause, just remove `estimatedListSize` prop and the issue will disappear.

### What changes do you think we should make in order to solve the problem?

We need to set the width inside estimatedListSize to a round value, 
```js
const  roundedWindowWidth  =  Math.floor(windowWidth);

<FlashList
  estimatedListSize={{height:  flattenListWrapperStyle.height, width: roundedWindowWidth}}
/>
```

and to make this work perfectly, we set the width to the set of the parent view

```js
<View  style={[listWrapperStyle, { width: roundedWindowWidth }]}>
<FlashList
  ref={forwardedRef}
```
This will not only fix the issue but also fix the lagging on the UI.

**Note**: the code above is a quick demo, for sure we need to add the `isSmallScreenWidth` condition. More dfetails can be handleld throw PR.

### What alternative solutions did you explore? (Optional)

A better solution is to pass the `height` and the `width` to `estimatedListSize` od the `FlatList` component throw a parent component. Using `useWindowDimensions` inside `BaseEmojiPickerMenu` will just force more re-rendering. We alredy calculated the window dimention on parent component.

**Comment by s77rt** [comment] 2024-02-10 17:26
@dragnoir Thanks for the proposal. Your RCA is correct. The solution looks good to me 👍 

🎀 👀 🎀 C+ reviewed
[Link to proposal](https://github.com/Expensify/App/issues/34522#issuecomment-1937020655)

**Comment by s77rt** [comment] 2024-02-12 19:31
Not `Internal`. We have an [agreed proposal](https://github.com/Expensify/App/issues/34522#issuecomment-1937077391)

**Comment by aldo-expensify** [comment] 2024-02-12 21:04
I'm not being able to reproduce this anymore in Pixel 7 Pro:

**main**
<img width="300" alt="image" src="https://github.com/Expensify/App/assets/87341702/1eeb0c4a-c0af-4584-984d-7ae3563ad89e">

**staging:**
<img width="300" alt="image" src="https://github.com/Expensify/App/assets/87341702/0e4fc747-505e-4c24-9820-71c3454509ae">


Can someone confirm if this is still reproducible?

**Comment by s77rt** [comment] 2024-02-13 00:06
@aldo-expensify Try on native not web

**Comment by aldo-expensify** [comment] 2024-02-13 02:41
@s77rt you are right, reproduced in native. Assigning @dragnoir then.

**Comment by aldo-expensify** [comment] 2024-02-16 02:08
@dragnoir 👋 , when do you think you can create a PR with the fix?

**Comment by dragnoir** [comment] 2024-02-16 11:52
PR ready https://github.com/Expensify/App/pull/36674

**Comment by dragnoir** [comment] 2024-03-01 10:12
Payment will be automatically handled?

**Comment by dragnoir** [comment] 2024-03-06 08:04
@s77rt when do you think payment will be released? Seem automation not working here!

**Comment by s77rt** [comment] 2024-03-06 12:54
@dragnoir Right, Melvin been away for a while. I think this is due payment now cc @JmillsExpensify

**Comment by dragnoir** [comment] 2024-03-11 08:58
@JmillsExpensify friendly reminder :)

**Comment by s77rt** [comment] 2024-03-18 22:19
@aldo-expensify Please remove the `Reviewing` label and move this to `Daily`

**Comment by aldo-expensify** [comment] 2024-03-18 23:01
> @aldo-expensify the job is removed from upwork and I have not been paid. Can you pls check!

I don't think I have access, @JmillsExpensify should be able to check

**Comment by JmillsExpensify** [comment] 2024-03-23 19:57
Please reach out to me via DM when the payment automation fail. I'm on hundreds of issues, so it's real hard to get to these in a timeline manner when that failure happens.

**Comment by JmillsExpensify** [comment] 2024-03-23 19:59
Payment summary: 

 - Contributor: @dragnoir $250
 - Contributor+: @s77rt 

Offer sent to contributor and C+ has been paid out.

**Comment by JmillsExpensify** [comment] 2024-03-24 02:44
Thanks! All contributors paid via Upwork.

**Closed by JmillsExpensify** 2024-03-24 02:44 UTC
Labels: External, Engineering, Daily, Bug
