### ISSUE TITLE
Company cards - "What's the Amex delivery file name" is missing a question mark

### ISSUE THREAD

**Issue by IuliiaHerets** [Expensify/App#49046] opened 2024-09-12 08:25 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 9.0.33-1
**Reproducible in staging?:** Y 
**Reproducible in production?:** N/A - new feature, doesn't exist in prod
**Issue was found when executing this PR:** https://github.com/Expensify/App/pull/48119
**Email or phone of affected tester (no customers):** applausetester+kh090901@applause.expensifail.com
**Issue reported by:** Applause Internal Team

## Action Performed:
Precondition:
- Company cards feature is enabled.

1. Go to https://staging.new.expensify.com/settings/workspaces/policyID/company-cards/add-card-feed
2. Select AMEX.
3. Click Next.

## Expected Result:
The sentence "What's the Amex delivery file name" should have a question mark.

## Actual Result:
The sentence "What's the Amex delivery file name" is missing a question mark.

The sentence "What's the Mastercard distribution ID" (Mastercard) is also missing the question mark.

## Workaround:
Unknown

## Platforms:

- [x] Android: Native
- [x] Android: mWeb Chrome
- [x] iOS: Native
- [x] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

https://github.com/user-attachments/assets/defea037-4b69-4713-9d5c-878770194ce3

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by IuliiaHerets** [comment] 2024-09-12 08:26
We think that this bug might be related to #wave-control

**Comment by mkzie2** [comment] 2024-09-12 08:28
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
The sentence "What's the Amex delivery file name" is missing a question mark.

### What is the root cause of that problem?

This copy is not correct

https://github.com/Expensify/App/blob/2830add7516b97c39d5c16ab5d1af8ab048f25c3/src/languages/en.ts#L2828

### What changes do you think we should make in order to solve the problem?

Add question mark to the copy.

**Comment by ChavdaSachin** [comment] 2024-09-12 08:32
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
The sentences "What's the Amex delivery file name" and "What's the Mastercard distribution ID" (Mastercard) is missing a question mark.

### What is the root cause of that problem?
- Its not included in `en.ts` file
### What changes do you think we should make in order to solve the problem?
- include `?` at both place
https://github.com/Expensify/App/blob/2830add7516b97c39d5c16ab5d1af8ab048f25c3/src/languages/en.ts#L2828
https://github.com/Expensify/App/blob/2830add7516b97c39d5c16ab5d1af8ab048f25c3/src/languages/en.ts#L2832

### What alternative solutions did you explore? (Optional)

**Reminder:** Please use plain English, be brief and avoid jargon. Feel free to use images, charts or pseudo-code if necessary. Do not post large multi-line diffs or write walls of text. Do not create PRs unless you have been hired for this job.

**Comment by grgia** [comment] 2024-09-12 10:21
Demoting from a deploy blocker, should be fixed by @waterim

**Comment by waterim** [comment] 2024-09-12 10:23
Company cards are under NO QA label

**Comment by ChavdaSachin** [comment] 2024-09-12 10:25
Additionally I have found we are missing a `?` here as well
https://github.com/Expensify/App/blob/2830add7516b97c39d5c16ab5d1af8ab048f25c3/src/languages/es.ts#L566
please fix along.

**Comment by waterim** [comment] 2024-09-12 10:30
@joekaufmanexpensify Should it be closed as Company cards is under NO QA label?

**Comment by koko57** [comment] 2024-09-12 10:30
+ not a deploy blocker as it's under beta

**Comment by joekaufmanexpensify** [comment] 2024-09-12 12:28
Yeah, let's close for now. This feature is still in implementation. We're going to start comprehensive manual testing soon, but any QA now is premature.

**Closed by joekaufmanexpensify** 2024-09-12 12:28 UTC
Labels: Engineering, Daily, Bug
