### ISSUE TITLE
[HOLD for payment 2024-10-24] [$250] iOS - IOU - The details of a single IOU are not displayed until you scroll up

### ISSUE THREAD

**Issue by IuliiaHerets** [Expensify/App#47584] opened 2024-08-16 18:25 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 9.0.21-0
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**If this was caught during regression testing, add the test name, ID and link from TestRail:** https://expensify.testrail.io/index.php?/tests/view/4864475
**Email or phone of affected tester (no customers):** sustinov@applausemail.com
**Issue reported by:** Applause Internal Team

## Action Performed:
1. Open New Expensify app
2. Log in with a new HT account
3. Send any IOU to a user with whom you have not had a previous expense.
4. Open the sent IOU
5. Scroll up the details
6. Close the application (kill)
7. Open the app
8. Repeat steps 3-5 several times
## Expected Result:
IOU details should be automatically displayed when the IOU is opened

## Actual Result:
The details of a single IOU are not displayed until you scroll up

## Workaround:
Unknown

## Platforms:

- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [x] iOS: Native
- [ ] iOS: mWeb Safari
- [ ] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

https://github.com/user-attachments/assets/209d9758-40f6-401c-9c00-1afe7677b869

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~010724ba54874de1b6</li>
        <li>Upwork Job ID: 1826197658645316035</li>
        <li>Last Price Increase: 2024-09-04</li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @zanyrenney</details>

**Comment by IuliiaHerets** [comment] 2024-08-16 18:25
We think that this bug might be related to #vip-bills

**Comment by IuliiaHerets** [comment] 2024-08-16 18:25
@zanyrenney z FYI I haven't added the External label as I wasn't 100% sure about this issue. Please take a look and add the label if you agree it's a bug and can be handled by external contributors

**Comment by zanyrenney** [comment] 2024-08-19 16:36
hey @IuliiaHerets can you explain what a HT account is please?

**Comment by IuliiaHerets** [comment] 2024-08-19 21:52
@zanyrenney High traffic account, but the issue also repro with a regular Expensifail account too

**Comment by zanyrenney** [comment] 2024-08-21 10:00
Adding external for more support here.

**Comment by s77rt** [comment] 2024-08-26 19:53
Not overdue. Still looking for proposals

**Comment by s77rt** [comment] 2024-08-30 18:08
Same ^

**Comment by zanyrenney** [comment] 2024-09-02 10:06
https://expensify.slack.com/archives/C01GTK53T8Q/p1725271582824419

**Comment by s77rt** [comment] 2024-09-02 13:13
Not overdue. Looking for proposals

**Comment by muttmuure** [comment] 2024-09-03 14:51
Is this still happening?

**Comment by muttmuure** [comment] 2024-09-03 15:03
I can reproduce this

**Comment by kubabutkiewicz** [comment] 2024-09-03 17:28
I am Jakub from Callstack - expert contributor group. I’d like to work on this job

**Comment by s77rt** [comment] 2024-09-03 21:41
@muttmuure or @zanyrenney please assign @kubabutkiewicz ^

**Comment by zanyrenney** [comment] 2024-09-04 16:26
assigned @kubabutkiewicz as requested.

**Comment by kubabutkiewicz** [comment] 2024-09-09 09:23
Hi I created a PR to fix that issue, the problem was that in a component responsible for displaying iou details we were using double `withOnyx` and that was creating a double wrapper around that component and one of those wrappers were blocking displaying correct ui sometimes. I switched `withOnyx` to `useOnyx` which have better performance and its not creating any additional wrappers around components.

**Comment by wildan-m** [comment] 2024-10-01 00:20
Looks like the PR merged, but I still able to reproduce the issue when deleting one of two money request from another device


https://github.com/user-attachments/assets/4e4a59ef-e5b1-4ad2-ba8b-649f6c76b60f

**Comment by kubabutkiewicz** [comment] 2024-10-02 06:38
Yes, I will be able to @s77rt

**Comment by kubabutkiewicz** [comment] 2024-10-07 14:12
Hey hey, I was able to find what is the issue 
https://github.com/Expensify/App/blob/78e484f41e5fb5fa3f8827d2b4aea0ba55b581e4/src/components/InvertedFlatList/BaseInvertedFlatList/index.tsx#L21-L23
Issue is here, when the issue occur `autoscrollToTopThreshold` prop is not set to true. I am checking now why this is happening as this is only happening on iOS

**Comment by kubabutkiewicz** [comment] 2024-10-08 16:12
@s77rt I created a [PR](https://github.com/Expensify/App/pull/50433) for fixing this issue. It was actually happening on all platforms.

**Comment by s77rt** [comment] 2024-10-20 10:29
- The PR that introduced the bug has been identified: https://github.com/Expensify/App/pull/30269
- The offending PR has been commented on: https://github.com/Expensify/App/pull/30269#discussion_r1807765010
- A discussion in #expensify-bugs has been started: Not needed
- Determine if we should create a regression test for this bug: No, and this already seems coming from a regression test

**Comment by zanyrenney** [comment] 2024-10-24 08:46
**payment summary**

@s77rt requires payment through NewDot Manual Requests - please request $250 for this issue
@kubabutkiewicz does not require payment (Contractor) - no payment required.

**Comment by tgolen** [comment] 2024-10-24 16:33
Reopening so @zanyrenney can complete the regression checklist. Can you please copy @s77rt's answers to the checklist and then finish it up?

**Comment by zanyrenney** [comment] 2024-10-24 17:49
BugZero Checklist: The PR fixing this issue has been merged! The following checklist ([instructions](https://stackoverflow.com/c/expensify/questions/14574)) will need to be completed before the issue can be closed:

- [ ] The PR that introduced the bug has been identified: https://github.com/Expensify/App/pull/30269
- [ ] The offending PR has been commented on: https://github.com/Expensify/App/pull/30269#discussion_r1807765010
- [ ] A discussion in #expensify-bugs has been started: Not needed
- [ ] Determine if we should create a regression test for this bug: No, and this already seems coming from a regression test

**Comment by zanyrenney** [comment] 2024-10-24 17:50
Ah, my understanding was the contributor does the checklist as there is no regression test here @tgolen ? I've done it above now but I've always thought that was the case as their name is next to the checkboxes.

**Comment by zanyrenney** [comment] 2024-10-24 20:41
I added the checklist again above, and the payment summary is also above. I think we now are good to close.

**Closed by zanyrenney** 2024-10-24 20:41 UTC
Labels: External, Daily, Awaiting Payment, Bug
