### ISSUE TITLE
[HOLD for payment 2024-12-16] [$250] Tasks - App goes back to main chat or LHN when editing a task's description

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#47671] opened 2024-08-19 21:21 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 9.0.22-5
**Reproducible in staging?:** Y
**Reproducible in production?:** N
**If this was caught during regression testing, add the test name, ID and link from TestRail:** https://expensify.testrail.io/index.php?/tests/view/4872853
**Email or phone of affected tester (no customers):** gatantm+82@gmail.com
**Issue reported by:** Applause - Internal Team

## Action Performed:
1. Go to any chat and create a task
2. Open the task and click on description
3. Make any edits > Save

## Expected Result:
The task is saved and user stays on task view

## Actual Result:
The user is returned back to the LHN on mobile or the chat that the task was in. The same happens on the name field after the description was edited once

Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details> 

https://github.com/user-attachments/assets/c2ec4dc9-6750-4fc5-82cb-589a0634c0de

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~0135f56d92cfd4346d</li>
        <li>Upwork Job ID: 1826020469224260035</li>
        <li>Last Price Increase: 2024-10-15</li>
<li>Automatic offers: </li>
<ul>
<li>tsa321 | Contributor | 104546362</li>
</ul></li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @getusha</details>

**Comment by lanitochka17** [comment] 2024-08-19 21:22
We think that this bug might be related to #vip-vsp

**Comment by bernhardoj** [comment] 2024-08-20 06:00
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
The main chat opens after editing task description.

### What is the root cause of that problem?
When we edit the task, we notify the report that a new action has been added.
https://github.com/Expensify/App/blob/80236f5bd80086950344eb10aa89c174bf7c923e/src/libs/actions/Task.ts#L568-L569

It will trigger `scrollToBottomForCurrentUserAction` and if `hasNewestReportActionRef` is false, then we navigate to the self-report to clear the `reportActionID` params.
https://github.com/Expensify/App/blob/80236f5bd80086950344eb10aa89c174bf7c923e/src/pages/home/report/ReportActionsList.tsx#L362-L372

After editing the task, we call `dismissModal` to close the RHP.
https://github.com/Expensify/App/blob/80236f5bd80086950344eb10aa89c174bf7c923e/src/pages/tasks/TaskDescriptionPage.tsx#L55-L58

In `dismissModal`, if the target report ID is the same as the topmost report ID, which is true in our case, we simply pop the current screen.
https://github.com/Expensify/App/blob/80236f5bd80086950344eb10aa89c174bf7c923e/src/libs/Navigation/dismissModalWithReport.ts#L70-L72

So, the first navigate to the self-report already closes the RHP and the `dismissModal` calls pop which brings us back to the parent report.

Even though this happens after my [PR](https://github.com/Expensify/App/pull/46724) where I add the navigate to self-report logic, but we already guard it with `hasNewestReportActionRef` condition. So, the real issue here is, why is `hasNewestReportActionRef` false?

The issue is both FE and BE. `hasNewestReportAction` compares the last report action `created` with the report `lastVisibleActionCreated`.
https://github.com/Expensify/App/blob/80236f5bd80086950344eb10aa89c174bf7c923e/src/pages/home/report/ReportActionsList.tsx#L295

In FE, we optimistically add the update task description system message, but we don't update the `lastVisibleActionCreated`.
https://github.com/Expensify/App/blob/80236f5bd80086950344eb10aa89c174bf7c923e/src/libs/actions/Task.ts#L505-L524

For the BE issue, looks like the BE doesn't consider the update task system message `created` as the report `lastVisibleActionCreated`.
<img width="696" alt="Screenshot 2024-08-20 at 13 40 36" src="https://github.com/user-attachments/assets/6efdad97-a532-43c4-9efe-4c1b67d8b017">

From the screenshot above, we can see that after the EditTask is completed, there are 2 reports onyx data. The first one contains the correct `lastVisibleActionCreated` but the second one contains the wrong `lastVisbibleActionCreated` (it contains the report CREATED action `created` value).

This makes `hasNewestReportActionRef` always false even if we fix it optimistically because when `scrollToBottomForCurrentUserAction` is called, the optimistic data is not merged yet, so `hasNewestReportActionRef` is still false because the report `lastVisibleActionCreated` from the BE is wrong.

### What changes do you think we should make in order to solve the problem?

The fix must be done for both BE and FE. The BE needs to return the correct `lastVisibleActionCreated`. In FE, we can optimistically update the report `lastVisibleActionCreated` in `editTask` to be the same as the edit task system message `created`. `buildOptimisticEditedTaskFieldReportAction` will accept a `created` param to be used as the `created` value.
```
const created = DateUtils.getDBTime();
const editTaskReportAction = ReportUtils.buildOptimisticEditedTaskFieldReportAction({title, description}, created);
const optimisticData: OnyxUpdate[] = [
    {
        onyxMethod: Onyx.METHOD.MERGE,
        key: `${ONYXKEYS.COLLECTION.REPORT}${report.reportID}`,
        value: {
            ...,
            lastVisibleActionCreated: created,
        },
    },
];
```

**Comment by deetergp** [comment] 2024-08-20 14:59
I think this blocker may be a result of this PR from yesterday's staging deploy https://github.com/Expensify/App/pull/47209

**Comment by bernhardoj** [comment] 2024-08-20 16:13
It's actually happening after my PR https://github.com/Expensify/App/pull/46724, but the root cause is actually an existing issue coming from both BE and FE optimistic data issues which is why I posted a proposal for this one.

**Comment by nkdengineer** [comment] 2024-08-21 10:53
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
The user is returned back to the LHN on mobile or the chat that the task was in. The same happens on the name field after the description was edited once

### What is the root cause of that problem?
When we edit the task title, we will dismiss the modal 

https://github.com/Expensify/App/blob/685bb4c7bbaa2ef332896de5cace193edb9c6a51/src/pages/tasks/TaskTitlePage.tsx#L55

But before that, we have a logic to that will trigger `scrollToBottomForCurrentUserAction` [here](https://github.com/Expensify/App/blob/685bb4c7bbaa2ef332896de5cace193edb9c6a51/src/pages/home/report/ReportActionsList.tsx#L360-L372)
https://github.com/Expensify/App/blob/685bb4c7bbaa2ef332896de5cace193edb9c6a51/src/libs/actions/Task.ts#L568

In the normal case, we will scroll to the bottom but in this case `hasNewestReportActionRef` is `false` because we don't update `lastVisibleActionCreated` of the task report in optimistic data, and BE also returns the wrong `created` of the task report then we will navigate to the task report before we dismiss the modal. These actions are called almost simultaneously when the task report is removed from the stack navigator.

It doesn't happen when we update the assignee because we wrap the dismiss logic in `InteractionManager.runAfterInteractions`. But when we edit the assignee, `lastVisibleActionCreated` is also not updated in optimistic data
https://github.com/Expensify/App/blob/685bb4c7bbaa2ef332896de5cace193edb9c6a51/src/pages/tasks/TaskAssigneeSelectorModal.tsx#L200-L204


https://github.com/user-attachments/assets/a11b32be-40b2-48c9-bb83-e4eae74e9212



### What changes do you think we should make in order to solve the problem?

On the FE side, we should update `lastVisibleActionCreated` of task report when we edit the task title, and description here. We can simply update this to `editTaskReportAction.created` instead of adding new `created` param

```
lastVisibleActionCreated: editTaskReportAction.created
```
https://github.com/Expensify/App/blob/685bb4c7bbaa2ef332896de5cace193edb9c6a51/src/libs/actions/Task.ts#L513-L515

and the same when editing the task assignee here

```
lastVisibleActionCreated: editTaskReportAction.created,
```

https://github.com/Expensify/App/blob/685bb4c7bbaa2ef332896de5cace193edb9c6a51/src/libs/actions/Task.ts#L578

OPTIONAL: We can also wrap dismiss modal in `InteractionManager.runAfterInteractions` as we do for task assignee page

https://github.com/Expensify/App/blob/685bb4c7bbaa2ef332896de5cace193edb9c6a51/src/pages/tasks/TaskTitlePage.tsx#L55
### What alternative solutions did you explore? (Optional)
NA

**Comment by deetergp** [comment] 2024-08-23 16:13
@getusha We've got a good number of proposals here for you to review 🎉

**Comment by getusha** [comment] 2024-08-25 21:39
Reviewing, i will update today

**Comment by getusha** [comment] 2024-08-25 21:52
@nkdengineer your proposal looks pretty much alike @bernhardoj's except a very small detail.

**Comment by getusha** [comment] 2024-08-25 21:52
@bernhardoj can we test this without the BE change?

**Comment by bernhardoj** [comment] 2024-08-26 02:49
> can we test this without the BE change?

@getusha We can do it while offline, but the first edit will still navigate to the main chat because the current report `lastReadTime` and `lastVisbibleActionCreated` (from OpenReport) are still not matched. 2nd edit and onward won't navigate to the main chat anymore.

**Comment by nkdengineer** [comment] 2024-08-26 02:52
> 
@nkdengineer your proposal looks pretty much alike @bernhardoj's except a very small detail.



@getusha 

1. My proposal mentioned why this bug only happens when we change the title or description but doesn't when we change the assignee

2. I also mentioned that `lastVisibleActionCreated` is not updated when we change the assignee. That can prevent the chat from scrolling to the bottom when we change the assignee as expected behavior [here](https://github.com/Expensify/App/pull/39390).

3. The way I update the `lastVisibleActionCreated` in optimistic data is also different

**Comment by getusha** [comment] 2024-09-04 09:52
I'll update today

**Comment by getusha** [comment] 2024-09-10 09:00
This fell through the cracks, reviewing it today

**Comment by getusha** [comment] 2024-09-10 09:15
@nkdengineer do you have any insights on why we need `Navigation.dismissModal(report?.reportID); `? I am inclined to just remove it but would like to explore the root cause.

**Comment by nkdengineer** [comment] 2024-09-10 09:27
@getusha As with other flows, we need `Navigation.dismissModal(report?.reportID)` to dismiss the modal and go back to the current report after we complete and call the API. The current problem in this case is `hasNewestReportAction` is wrong when we edit task title/description then this logic [here](https://github.com/Expensify/App/blob/e96b0382e602a02b00f4bb8a9aabf405eed96c76/src/pages/home/report/ReportActionsList.tsx#L359-L362) is called unexpectedly which causes this bug. It also causes another bug that the chat doesn't scroll to the bottom if we edit the assignee the second time. So I don't think we should remove `Navigation.dismissModal(report?.reportID)` logic. Instead we should update optimistic data to make `hasNewestReportAction` is correct.

**Comment by getusha** [comment] 2024-09-16 06:04
@nkdengineer could you please specify in your proposal if there'll be any BE changes?

**Comment by nkdengineer** [comment] 2024-09-16 06:47
@getusha Updated [proposal](https://github.com/Expensify/App/issues/47671#issuecomment-2301760721) with the require BE change. The problem here is `OpenReport` API returns a different `lastVisibleActionCreated` from `EditTask` API.

https://github.com/user-attachments/assets/45b70d08-0758-43ca-abf9-7d863a535568

**Comment by deetergp** [comment] 2024-09-17 00:53
> cc @deetergp Could you confirm the expected behavior https://github.com/Expensify/App/issues/47671#issuecomment-2340578426.

I don't know off the top of my head whether that is intended, so I have [asked](https://expensify.slack.com/archives/C03U7DCU4/p1726534385066859) in our #product room and will let you know.

**Comment by nkdengineer** [comment] 2024-09-17 04:19
@deetergp For the context, it's expected from this [PR](https://github.com/Expensify/App/pull/39390).

**Comment by deetergp** [comment] 2024-09-17 17:54
Ah, nice find @nkdengineer, thanks for sharing 👍 cc @tsa321

**Comment by deetergp** [comment] 2024-09-18 16:46
After a bit of [internal discussion](https://expensify.slack.com/archives/C03U7DCU4/p1726534385066859) in our #product channel, we've agreed that jumping to the bottom of the convo after editing the task is the incorrect behavior, so if we wanted to address that here, that would be great!

@lanitochka17 Apparently there is an Applause [test rail case](https://expensify.testrail.io/index.php?/runs/view/20318&group_by=cases:section_id&group_order=asc&group_id=291935) that indicates that we _should_ be jumping to the end of the chat? If that exists, let's update it to reflect that we _should not_ be jumping to the end after editing. Thanks!

**Comment by getusha** [comment] 2024-09-23 06:35
Reviewing

**Comment by getusha** [comment] 2024-09-23 06:41
@tsa321 i am no longer able to reproduce the issue, could you check?

https://github.com/user-attachments/assets/92c39da8-29b0-4429-b179-4d38d0e31a09

**Comment by getusha** [comment] 2024-09-29 20:17
Trying to reproduce

**Comment by getusha** [comment] 2024-09-30 06:56
@tsa321 I think your alternative solution is the most ideal.
seems like we already have a parameter called `isFromCurrentUser` which i think we can use for this case @tsa321.
could you share a test branch for this?

**Comment by mvtglobally** [comment] 2024-10-05 03:08
Issue not reproducible during KI retests. (First week)

**Comment by deetergp** [comment] 2024-10-07 23:54
I am going to set this to weekly and hope that it gets marked as not reproducible next week. If it does, I will close it.

**Comment by deetergp** [comment] 2024-10-11 00:53
Well dang. Moving back to Daily. 

@getusha, care to weigh in on @tsa321's [comment](https://github.com/Expensify/App/issues/47671#issuecomment-2383392836)?

**Comment by deetergp** [comment] 2024-11-06 18:21
PR review is ongoing.

**Comment by sakluger** [comment] 2024-12-17 17:56
Hey @getusha, please complete the BZ checklist so we can close out this issue. Please copy/paste the BugZero Checklist from [here](https://raw.githubusercontent.com/Expensify/App/main/contributingGuides/BUGZERO_CHECKLIST.md) into a new comment on this GH and complete it.

**Comment by sakluger** [comment] 2024-12-17 18:05
Summarizing payment on this issue:

Contributor: @tsa321 $250, paid via Upwork
Contributor+: @getusha $250, please finish BZ checklist, then request payment via NewDot

**Comment by getusha** [comment] 2024-12-18 02:43
# BugZero Checklist:

- [x] **[Contributor]** Classify the bug:

<details>
<summary>Bug classification</summary>


Source of bug:
  - [x] 1a. Result of the original design (eg. a case wasn't considered)
  - [ ] 1b. Mistake during implementation
  - [ ] 1c. Backend bug
  - [ ] 1z. Other:

Where bug was reported:
  - [ ] 2a. Reported on production (eg. bug slipped through the normal regression and PR testing process on staging)
  - [x] 2b. Reported on staging (eg. found during regression or PR testing)
  - [ ] 2d. Reported on a PR
  - [ ] 2z. Other:

Who reported the bug:
  - [ ] 3a. Expensify user
  - [ ] 3b. Expensify employee
  - [ ] 3c. Contributor
  - [x] 3d. QA
  - [ ] 3z. Other:

</details>

- [x] **[Contributor]** The offending PR has been commented on, pointing out the bug it caused and why, so the author and reviewers can learn from the mistake.

    Link to comment: https://github.com/Expensify/App/pull/39390

- [x] **[Contributor]** If the regression was CRITICAL (e.g. interrupts a core flow) A discussion in [#expensify-open-source](https://app.slack.com/client/E047TPA624F/C01GTK53T8Q) has been started about whether any other steps should be taken (e.g. updating the PR review checklist) in order to catch this type of bug sooner.

    Link to discussion: N/a

- [x] **[Contributor]** If it was decided to create a regression test for the bug, please propose the [regression test](https://github.com/Expensify/App/blob/main/contributingGuides/REGRESSION_TEST_BEST_PRACTICES.md) steps using the template below to ensure the same bug will not reach production again.

- [ ] **[BugZero Assignee]** Create a GH issue for creating/updating the regression test once above steps have been agreed upon.

    Link to issue:

## Regression Test Proposal

### Test:


1. Go to any chat and create a task.
2. Open the task report.
3. Send 10 messages.
4. Edit the task description and save it.
5. Verify that the app doesn't navigate to another report and that the task report doesn't automatically scroll to the bottom.
Edit the task title.
6. Verify that the app doesn't navigate to another report and that the task report doesn't automatically scroll to the bottom.
7. Repeat the steps with the title and assignee

We need to remove this test rail as well https://expensify.testrail.io/index.php?/runs/view/20318&group_by=cases:section_id&group_order=asc&group_id=291935

Do we agree 👍 or 👎

**Comment by sakluger** [comment] 2024-12-18 05:50
Thanks!

**Closed by sakluger** 2024-12-18 05:50 UTC
Labels: External, Engineering, Daily, Awaiting Payment

**Comment by garrettmknight** [comment] 2025-01-29 21:08
$250 approved for @getusha
