### ISSUE TITLE
[$500] Web - When a user changes their profile status, the app brings you to the end of the conversation.

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#33110] opened 2023-12-14 18:48 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.13.0
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** Applause - Internal Team
**Slack conversation:**

## Action Performed:
1. Launch the app
2. Log in with any account
3. Open the 1:1 conversation
4. Scroll to the middle
5. Go to the seating - Profile - Status
6. Change the status

## Expected Result:
When a user changes their profile status, the app should stay in the same conversation position

## Actual Result:
When a user changes their profile status, the app brings you to the end of the conversation

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] Windows: Chrome 
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details> 

https://github.com/Expensify/App/assets/78819774/ee3d0bca-c0d6-44bf-b25c-b58b619fffd4

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~017a47704cf8762519</li>
        <li>Upwork Job ID: 1735371288086798336</li>
        <li>Last Price Increase: 2024-01-04</li>
    </ul>
</details>

**Comment by shubham1206agra** [comment] 2023-12-14 18:53
I feel like this will be fixed here https://github.com/Expensify/App/pull/31670

**Comment by FitseTLT** [comment] 2023-12-14 19:42
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
When a user changes their profile status, the app brings you to the end of the conversation.

### What is the root cause of that problem?
Currently we are `popingToTop` after saving a profile status as we set `setShouldPopAllStateOnUP` here
https://github.com/Expensify/App/blob/904cf5635b819971b7b24bc78c3e516beea21239/src/pages/home/sidebar/AvatarWithOptionalStatus.js#L32-L39
so the page is unnecessarily reloading and the report screen is scrolled to bottom creating a disturbing user experience and I think we should avoid this unnecessary reloading.
### What changes do you think we should make in order to solve the problem?

We can just `pop` instead of `popToTop` here
https://github.com/Expensify/App/blob/904cf5635b819971b7b24bc78c3e516beea21239/src/pages/settings/Profile/CustomStatus/StatusPage.js#L72-L73
### What alternative solutions did you explore? (Optional)

**Comment by mananjadhav** [comment] 2023-12-17 19:00
@lanitochka17 Is this still reproducible? I can't seem to be able to reproduce this.


https://github.com/Expensify/App/assets/3069065/b41edb60-cd42-4574-b87f-de999df16454

**Comment by FitseTLT** [comment] 2023-12-17 19:16
@mananjadhav could it be because of this commit ??
![image](https://github.com/Expensify/App/assets/38649957/11f17b6f-7362-46b1-a3df-19df2d5e9ae2)

**Comment by mananjadhav** [comment] 2023-12-17 19:20
@FitseTLT I don't think so. The linked commit is not merged, but used as a part of the proposal.

**Comment by FitseTLT** [comment] 2023-12-17 19:26
@mananjadhav Now it is opening another report when I save status. Before 3 days it was reloading the current report. Odd!!

**Comment by puneetlath** [comment] 2023-12-18 16:46
I am able to reproduce it @mananjadhav. However, I don't think this needs to be a deploy blocker.

**Comment by lanitochka17** [comment] 2023-12-18 17:51
Hello
It directed to Concierge chat after changing the status

https://github.com/Expensify/App/assets/78819774/b6e4f835-3561-4341-8c04-2f7b05a0bbc7

**Comment by DylanDylann** [comment] 2023-12-19 18:57
it is dupe. Link issue https://github.com/Expensify/App/issues/33002

> Hello It directed to Concierge chat after changing the status
> 
>  Recording.5719.mp4

it is dupe. Link issue https://github.com/Expensify/App/issues/33002

**Comment by DylanDylann** [comment] 2023-12-19 18:58
This maybe is dupe https://github.com/Expensify/App/issues/33002

**Comment by DylanDylann** [comment] 2023-12-19 19:08
This one was handled in https://github.com/Expensify/App/issues/30509 but I don't know why we removed it in https://github.com/Expensify/App/pull/24620

**Comment by puneetlath** [comment] 2023-12-21 16:57
@mananjadhav thoughts?

**Comment by quinthar** [comment] 2023-12-26 01:54
Actually this worked a little different for me (but is still broken):
- updating my status didn't change the scroll position of my current chat
- But *clearing* my status switched me to an entirely different random chat

**Comment by DylanDylann** [comment] 2023-12-26 18:57
@quinthar As I mentioned in [this](https://github.com/Expensify/App/issues/33110#issuecomment-1863330492), just need to restore the logic that was removed before

**Comment by mananjadhav** [comment] 2023-12-27 13:21
I'll check the proposals today.

**Comment by DylanDylann** [comment] 2023-12-28 17:22
@mananjadhav As I mentioned in the [proposal](https://github.com/Expensify/App/issues/33110#issuecomment-1863330492), just need to restore the [PR](https://github.com/Expensify/App/pull/31051)

**Comment by bernhardoj** [comment] 2023-12-28 18:32
If we reuse https://github.com/Expensify/App/pull/31051, https://github.com/Expensify/App/issues/33002 will be reintroduced

**Comment by DylanDylann** [comment] 2023-12-28 18:47
@bernhardoj 
- I agree with you. But before I just consider this [issue](https://github.com/Expensify/App/issues/33110) is the regression when we implement the [PR](https://github.com/Expensify/App/pull/24620), so restoring the change will make sense.
- @mananjadhav I just updated the [proposal](https://github.com/Expensify/App/issues/33110#issuecomment-1863330492) to fix both the issue  [33110](https://github.com/Expensify/App/issues/33110), [33002](https://github.com/Expensify/App/issues/33002)

**Comment by puneetlath** [comment] 2024-01-02 16:54
@mananjadhav can you take a look at the updated proposals?

**Comment by mananjadhav** [comment] 2024-01-04 13:51
Will take a look at the proposals tomorrow.

**Comment by mananjadhav** [comment] 2024-01-04 19:56
I reviewed the proposals and I am on the fence between @suneox's [proposal](https://github.com/Expensify/App/issues/33110#issuecomment-1859227251) and @DylanDylann 's [proposal](https://github.com/Expensify/App/issues/33110#issuecomment-1863330492).


I don't think we should be having multiple routes for the same page @bernhardoj.

I think the behavior in https://github.com/Expensify/App/issues/33002 should be to always close the RHP in case the page is reloaded. We can't know (and we shouldn't care) if the page was opened from profile page or clicking directly from status icon. 

If we think we want to retain the behavior in https://github.com/Expensify/App/issues/33002, then @DylanDylann's proposal makes sense, else I am inclined to choose @suneox's proposal.

🎀 👀 🎀 C+ reviewed.

**Comment by DylanDylann** [comment] 2024-01-05 00:51
@mananjadhav Please note that the behavior in #33002 also exists in a lot of sections in our app. There are a lot of issues created to fix similar bugs

**Comment by mananjadhav** [comment] 2024-01-10 05:06
Yeah I agree. I think both the behaviors exist. Hence I've asked @puneetlath to confirm once.

**Comment by mananjadhav** [comment] 2024-01-12 19:21
quick bump @puneetlath

**Comment by puneetlath** [comment] 2024-01-16 21:01
I think I prefer @suneox's solution rather than creating new URL params. Let's try that.

**Comment by DylanDylann** [comment] 2024-01-16 21:31
@puneetlath the selected proposal leads to the regression [here](https://github.com/Expensify/App/issues/33002)

**Comment by mananjadhav** [comment] 2024-01-20 20:43
quick bump @puneetlath? I think @suneox is waiting for the offer.

**Comment by quinthar** [comment] 2024-01-22 00:39
Is this still happening?  I can't reproduce it.

**Comment by mananjadhav** [comment] 2024-01-25 08:15
I can reproduce it as well. @suneox you're already assigned, but I would let @puneetlath confirm as you were waiting for the offer from him.

**Comment by DylanDylann** [comment] 2024-01-25 08:31
- @mananjadhav Though the proposal has been selected, I think we need to make sure the proposal does not encounter any regression at the time it is selected. Can you check comment [here](https://github.com/Expensify/App/issues/33110#issuecomment-1894543878)? 

- @suneox Do you have solution to solve it?

**Comment by DylanDylann** [comment] 2024-01-25 10:58
@suneox Maybe the reproduce steps in your video is not the same as [this](https://github.com/Expensify/App/issues/33110#issuecomment-1894543878)

**Comment by mananjadhav** [comment] 2024-02-02 19:47
I'll review the PR on the weekend.

**Comment by DylanDylann** [comment] 2024-02-06 05:18
@suneox I can see the bug in your video screenshot or did I miss something? Pls help correct me

**Comment by DylanDylann** [comment] 2024-02-06 05:36
@suneox Oh sorry because I did not mention the expected behavior. Here is the steps:
1. Go to app.
2. Open different chat reports.
3. Click on the status on the top left.
4. Reload the page.
5. Click on the back button.
Actual: The profile modal opens
Expected: The profile modal closes

**Comment by DylanDylann** [comment] 2024-02-06 06:07
- @suneox
> You have provided a reference issue and then you changed the expected behavior.

 - I do not change the expected behavior. The reproduce steps in [here](https://github.com/Expensify/App/issues/33002) is not the same as the one I mentioned [above](https://github.com/Expensify/App/issues/33110#issuecomment-1928819200). 

- Generally, the expected is that, clicking on back button will bring user to the previous screen

**Comment by DylanDylann** [comment] 2024-02-06 06:43
> The reproduce step do not include reload step.

I mentioned it in step 4

> so how about your the expected behavior on you issue https://github.com/Expensify/App/issues/33002 when reload?

I think the expected is: clicking on back button will bring user to the previous screen

**Comment by DylanDylann** [comment] 2024-02-06 06:52
@suneox Sure. FYI, there was a similar issue https://github.com/Expensify/App/issues/30509

**Comment by puneetlath** [comment] 2024-02-20 21:30
@mananjadhav what are your thoughts on this issue?

**Comment by mananjadhav** [comment] 2024-02-21 00:05
I checked the PR, but I'll check all the comments today.

**Comment by puneetlath** [comment] 2024-02-22 15:46
@mananjadhav bump!

**Comment by mananjadhav** [comment] 2024-02-25 17:58
Was unwell past few days, will get to this by tomorrow.

**Comment by puneetlath** [comment] 2024-03-01 21:06
@mananjadhav any update?

**Comment by mananjadhav** [comment] 2024-03-05 16:52
There was substantial delay from my side to review the comments. But I don't think this is still reproducible anymore. We don't have a Profile modal, we have the Profile page. Opening the status shows the Profile page, moving away from the report page. Reloading the page should go back to the Profile page, so I think this is working as expected.

@lanitochka17 Can you confirm if this is still reproducible at your end? 

https://github.com/Expensify/App/assets/3069065/a3538e30-bb40-4734-aa35-e424eb7b4ecc

**Comment by mvtglobally** [comment] 2024-03-06 01:00
Since the page goes to profile, it resets back to the bottom. If the expectation is to reset, than issue is no longer applicable, 
https://github.com/Expensify/App/assets/43995119/f3d7fd48-fee3-40ca-81e1-6056812f6813

**Comment by mananjadhav** [comment] 2024-03-10 18:47
@puneetlath What should we do here?

**Comment by puneetlath** [comment] 2024-03-14 16:52
I think we should close this out. The original bug isn't there anymore and I think what is shown in @mvtglobally's video is fine. 

Thanks for your input everyone!

**Comment by puneetlath** [comment] 2024-04-18 17:02
Reopening this since the work was completed, so there should be some payment made.

**Comment by puneetlath** [comment] 2024-05-04 16:46
Ok, I've reviewed the thread/PR and I think that @suneox is due compensation since they did do the work they were hired for, though we didn't end up using it. 

I think @mananjadhav is due 50% compensation since they did partial work, but did not review/test the PR. 


Payment summary: 
C - @suneox - $500 - to be paid via Upwork
C+ - @mananjadhav $250 - to be paid via NewDot


@suneox can you please send me a link to your upwork profile? 
@mananjadhav please request on NewDot.

**Comment by mananjadhav** [comment] 2024-05-04 16:51
Thanks @puneetlath

**Comment by JmillsExpensify** [comment] 2024-05-04 17:12
$250 approved for @mananjadhav

**Comment by puneetlath** [comment] 2024-05-04 17:23
Np y'all. Thanks for your patience. @suneox offer is here: https://www.upwork.com/nx/wm/offer/102163593

Please ping me on the issue when you've accepted it.

**Comment by puneetlath** [comment] 2024-05-04 17:37
Ok all paid. Thanks y'all!

**Closed by puneetlath** 2024-05-04 17:37 UTC
Labels: Reviewing, Engineering, Weekly, Internal, Bug
