### ISSUE TITLE
[HOLD for payment 2023-08-17] [$1000] Web - Country suggestion does not work with head or trail space

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#23727] opened 2023-07-27 11:21 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Go to Settings > Profile > Personal details > Home address > Country
2. Type any name with head or trail space

## Expected Result:
Should show country suggestion if there is head or trail space

## Actual Result:
Country suggestion does not work with head or trail space

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [x] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:**1.3.45-8
**Reproducible in staging?:** y
**Reproducible in production?:** new feature
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/93399543/ba19fc2a-7981-4c41-8072-286e7fb4d7ff

https://github.com/Expensify/App/assets/93399543/cfc1aef6-1d8a-4ac9-9751-5ca7eca932de

**Expensify/Expensify Issue URL:**
**Issue reported by:** @gadhiyamanan
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1690379902974339

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01918263d8bfff6b0e</li>
        <li>Upwork Job ID: 1684585153238552576</li>
        <li>Last Price Increase: 2023-08-03</li>
<li>Automatic offers: </li>
<ul>
<li>gadhiyamanan | Reporter | 25935145</li>
</ul></li>
    </ul>
</details>

**Comment by danieldoglas** [comment] 2023-07-27 15:21
This doesn't need to be a deploy blocker, so removing the hourly/deployblockercash labels and adding bug

**Comment by danieldoglas** [comment] 2023-07-27 15:22
Also adding External for this.

**Comment by danieldoglas** [comment] 2023-07-27 15:23
Removing myself from the issue for now until there are proposals.

**Comment by b4s36t4** [comment] 2023-07-27 15:34
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
Web - Country suggestion does not work with head or trail space
### What is the root cause of that problem?

https://github.com/Expensify/App/blob/ac74ab9cb25a55e2d042feee24846d5cb7155239/src/components/CountryPicker/CountrySelectorModal.js#L36 Here in this function snippet we're doing filtering the countries based on the searchValue.

We're trimming the searchValue but not doing the filter based on the `trimmedSearchValue` even though we're having and checking for the trimmed value.

Because of the not trimmed value we're not getting any results

### What changes do you think we should make in order to solve the problem?
Changing this https://github.com/Expensify/App/blob/ac74ab9cb25a55e2d042feee24846d5cb7155239/src/components/CountryPicker/CountrySelectorModal.js#L42 line to like this

```jsx
return _.filter(data, (country) => country.text.toLowerCase().includes(trimmedSearchValue.toLowerCase()));
```
should work perfect

### What alternative solutions did you explore? (Optional)
NA

**Comment by danieldoglas** [comment] 2023-07-31 19:08
@eVoloshchak can you please review the proposals?

**Comment by JmillsExpensify** [comment] 2023-08-02 04:06
@eVoloshchak mind reviewing the proposals?

**Comment by marcaaron** [comment] 2023-08-03 21:03
Sounds good to me. Main thing to remember with this one is that we should never modify the input of the user. As long as we leave what the user enters in the text input and return better results then I am 👍 on the proposal.

**Comment by marcaaron** [comment] 2023-08-07 17:58
Looks like @eVoloshchak will be reviewing today.

**Comment by marcaaron** [comment] 2023-08-09 20:28
This was merged ahead of schedule. Not overdue 😄

**Comment by eVoloshchak** [comment] 2023-08-17 11:39
- The PR that introduced the bug has been identified. Link to the PR: That's how it was implemented initially in https://github.com/Expensify/App/pull/21049, I wouldn't call it a regression, more of a feature/polish that wasn't implemented at the time
- The offending PR has been commented on, pointing out the bug it caused and why, so the author and reviewers can learn from the mistake. Link to comment: N/A
- A discussion in #expensify-bugs has been started about whether any other steps should be taken (e.g. updating the PR review checklist) in order to catch this type of bug sooner. Link to discussion: https://expensify.slack.com/archives/C049HHMV9SM/p1692272320271749

**Comment by eVoloshchak** [comment] 2023-08-17 11:41
**Regression Test Proposal**

1. Go to settings > profile > personal details > home address
2. Go to the country selector
3. Try out different searches with/without 1 or more than 1 spaces in the start, middle or end of the search term -- Verify that it works
4. Try out different searches with a search term with/without brackets ex: `Myanmar (Burma), Cocos (Keeling) Islands` -- Verify that it works
5. Try out different searches with a search term with/without dots ex: `St. Lucia, U.S Virgin Islands` -- Verify that it works
6. Try out different searches with a search term with/without dashes ex: `Congo - Kinshasa, Congo - Brazzaville, Timor-Leste` -- Verify that it works
7. Try out different searches with a search term with/without ampersand ex: `St. Kitts & Nevis, St. Vincent & Grenadines` -- Verify that it works
8. Try out different searches with a search term with/without single quote ex: Côte d'Ivoire -- Verify that it works
9. Try out different searches with country code ex: `AF -> Afganistan, US -> United States, DZ -> Argeliz` -- Verify that it works

**Do we agree 👍 or 👎**

**Comment by JmillsExpensify** [comment] 2023-08-17 15:32
Payment summary for this issue: 
 - Issue reporter: @gadhiyamanan $250
 - Contributor: @huzaifa-99 $1,500 (incl. urgency bonus)
 - Contributor+: @eVoloshchak $1,500 (incl. urgency bonus)

Upwork is here: https://www.upwork.com/jobs/~01918263d8bfff6b0e. I've extended contracts to issue reporter and contributor. 

@eVoloshchak You payment has been reviewed and approved for NewDot.

**Comment by JmillsExpensify** [comment] 2023-08-17 15:41
Paid out both issue reporter and contributor. Will close this issue out once I add the regression issue and process payment in NewDot.

**Comment by marcaaron** [comment] 2023-08-29 22:49
I think one can be closed? But feel free to reopen if there's anything left to do here.

**Closed by marcaaron** 2023-08-29 22:49 UTC
Labels: External, Engineering, Weekly, Overdue, Awaiting Payment, Bug
