### ISSUE TITLE
[$500] Public Room - Whisper message is marked as unread after navigating back from a thread

### ISSUE THREAD

**Issue by isagoico** [Expensify/App#36815] opened 2024-02-19 19:30 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.42.0

**Reproducible in staging?:** Yes 
**Reproducible in production?:** Yes

**Issue reported by:** Applause -Internal team
**Slack conversation:** Found while executing tests for https://expensify.slack.com/archives/C9YU7BX5M/p1708359665549809

## Action Performed:
1. Log out if logged in.
2. Go to https://staging.new.expensify.com/r/6776919265133947
3. Scroll up.
4. Click New message button that appears - _Now the whisper is marked as read_
6. Go to any thread.
7. Click on the subtitle on the header to return to main chat.
8. Scroll down to the latest message if needed

## Expected Result:
The message should stay marked as read unless the user manually marks it as unread. 

## Actual Result:
The whisper message is marked as Unread - the new message line marker is displayed on top of the whisper message. 

## Workaround:
N/A

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [x] Android: mWeb Chrome
- [x] iOS: Native
- [x] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

https://github.com/Expensify/App/assets/44479856/8067e7e9-5184-40c2-b099-be247f643aac

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~010dd22acc72ffe315</li>
        <li>Upwork Job ID: 1765237239514411008</li>
        <li>Last Price Increase: 2024-03-06</li>
    </ul>
</details>

**Comment by JmillsExpensify** [comment] 2024-03-06 04:45
I'm not super clear why the external label didn't get added before, so adding now.

**Comment by rlinoz** [comment] 2024-03-06 12:37
Yeah, I think this got fixed by https://github.com/Expensify/App/issues/35740.

Couldn't reproduce with the steps in the issue.

**Comment by JmillsExpensify** [comment] 2024-03-13 04:43
Ah maybe that's the case. That issue is a more specific case. Closing out regardless.

**Closed by JmillsExpensify** 2024-03-13 04:43 UTC
Labels: External, Engineering, Daily, Help Wanted, Bug
