### ISSUE TITLE
Android - The transition back does not occur immediately after pressing the Back button.

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#13797] opened 2022-12-22 20:40 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Issue found when executing PR** https://github.com/Expensify/App/pull/13670

## Action Performed:
1. Launch the app
2. Enter a new email address
3. Tab button Back

## Expected Result:
By pressing the Back button, the transition back to the login page should be quick

## Actual Result:
The transition back does not occur immediately after pressing the Back button.

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?

- [ ] Android / app

**Version Number:** 1.243.1

**Reproducible in staging?:** Yes

**Reproducible in production?:** n/a

**Email or phone of affected tester (no customers):**

**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Notes/Photos/Videos:** Any additional supporting documentation

https://user-images.githubusercontent.com/93399543/209221904-1982679d-27e1-4180-ada4-1291b3c0c6b4.mp4

**Expensify/Expensify Issue URL:**

**Issue reported by:** Applause - Internal Team

**Slack conversation:**

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by slafortune** [comment] 2023-01-10 21:34
Sorry for the delay, not sure why weekly had gotten add and why I didn't notice it!
Hey @kbecciv Are you still able to recreate this?

**Comment by kbecciv** [comment] 2023-01-11 16:00
Unable to reproduce the issue with latest build 1.2.52.4


https://user-images.githubusercontent.com/93399543/211854616-248456c8-1d5a-401b-9345-2b0d2e6c41c6.mp4

**Comment by puneetlath** [comment] 2023-01-12 23:23
@slafortune this issue is now 3 weeks old. There is one more week left before this issue <a href='https://stackoverflowteams.com/c/expensify/questions/15233/15234#15234'>breaks WAQ</a> and will need to go internal. What needs to happen to get a PR in review this week? Please create a thread in #expensify-open-source to discuss. Thanks!

**Comment by luacmartins** [comment] 2023-01-16 21:34
It seems like Applause is unable to [reproduce](https://github.com/Expensify/App/issues/13797#issuecomment-1379024647) on 1.2.52.4. I also couldn't reproduce anymore. Gonna close this issue. Please reopen if it happens again.

**Closed by luacmartins** 2023-01-16 21:34 UTC
Labels: Weekly, Bug
