### ISSUE TITLE
[$1000] The mini context menu hides when the last comment of a new chat is copied on Safari

### ISSUE THREAD

**Issue by kavimuru** [Expensify/App#18664] opened 2023-05-09 18:26 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:

1. Open the app in Safari browser
2. Click on the search icon
3. Enter any email with which you don't have any chat history
4. Click on the email to start the chat
5. Send any comments
6. Hover over the last comment
7. Click on Copy to clipboard icon

## Expected Result:
The mini context menu doesn't hide
## Actual Result:
The mini context menu hides

## Workaround:
Can the user still use Expensify without this being fixed? Have you informed them of the workaround?

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [x] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 1.3.12.0
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/43996225/a20d7d50-24dd-4a1d-9b80-4ddcdfe387f2

https://github.com/Expensify/App/assets/43996225/3414b0eb-00c0-4cba-8692-9b0b21c5665a

**Expensify/Expensify Issue URL:**
**Issue reported by:** @adeel0202 
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1683297242361699

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~0142123b8c491008a1</li>
        <li>Upwork Job ID: 1656309577984794624</li>
        <li>Last Price Increase: 2023-05-17</li>
    </ul>
</details>

**Comment by kushu7** [comment] 2023-05-09 20:19
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
TextArea getting focused when we click copy to clipboard.
### What is the root cause of that problem?
We are getting `Composer` as ancorNode here when we use `window.getSelection()` while copying last message.
`isComposer` is set to `true`. 
https://github.com/Expensify/App/blob/b7300273da1b6862dd9df75ebe0fa526bf7f2d11/src/libs/Clipboard/index.js#L31-L33

and here we try to set back selection to `Composer`. so that field gets focused resulting closing of `ContextMenuActions`
https://github.com/Expensify/App/blob/b7300273da1b6862dd9df75ebe0fa526bf7f2d11/src/libs/Clipboard/index.js#L64-L68

### What changes do you think we should make in order to solve the problem?

To fix this we can avoid `setSelectionRange` on safari desktop browser.

` 
 if (Browser.isMobileSafari()) {
      firstAnchorChild.setSelectionRange(originalSelection.start, originalSelection.end, originalSelection.direction);
   }
`


https://github.com/Expensify/App/assets/31707153/57cdb9f2-f1b7-49d1-8c54-ab0f04433fef



### What alternative solutions did you explore? (Optional)
NA

**Comment by NicMendonca** [comment] 2023-05-10 14:24
asking clarification here: https://expensify.slack.com/archives/C049HHMV9SM/p1683728665329569?thread_ts=1683297242.361699&cid=C049HHMV9SM

**Comment by NicMendonca** [comment] 2023-05-10 14:43
More info: https://expensify.slack.com/archives/C049HHMV9SM/p1683729730901239?thread_ts=1683297242.361699&cid=C049HHMV9SM

**Comment by NicMendonca** [comment] 2023-05-10 14:45
I understand this now. Agree we should fix to keep it consistent across platforms

**Comment by kushu7** [comment] 2023-05-10 14:53
[My proposal above](https://github.com/Expensify/App/issues/18664#issuecomment-1540838270)

**Comment by dukenv0307** [comment] 2023-05-11 10:13
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
 The mini context menu hides when the last comment of a new chat is copied on Safari
### What is the root cause of that problem?
https://github.com/Expensify/App/blob/1d951e6812a30376eaed21ee792c370626e82d89/src/libs/Clipboard/index.js#L31-L34
We are checking if firstAnchorChild is HTMLTextAreaElement we will focus on it
https://github.com/Expensify/App/blob/1d951e6812a30376eaed21ee792c370626e82d89/src/libs/Clipboard/index.js#L64-L68

But when clicking Copy to Clipboard Icon, `selection.anchorNode` is wrong. `selection.anchorNode` is **the below node** instead of the current node, `selection.anchorNode` is correct when only holding the mouse and moving. It is the reason why when clicking Copy to Clipboard Icon on the last comment, `selection.anchorNode` will be the main composer (**the below node**) and isComposer is true
### What changes do you think we should make in order to solve the problem?
https://github.com/Expensify/App/blob/1d951e6812a30376eaed21ee792c370626e82d89/src/libs/Clipboard/index.js#L33
Here, we should add one more condition
const isComposer = firstAnchorChild instanceof HTMLTextAreaElement && selection.type === 'Range';
Because when clicking Copy to Clipboard Icon, selection.type === 'Caret';

### What alternative solutions did you explore? (Optional)

### Result 


https://github.com/Expensify/App/assets/129500732/e7bf2221-1b65-48f4-9804-70d207d4e021

**Comment by robertjchen** [comment] 2023-05-15 10:40
Thanks for all the proposals so far, we will evaluate this week.

**Comment by NicMendonca** [comment] 2023-05-17 20:22
@robertjchen any update here?

**Comment by dukenv0307** [comment] 2023-05-20 09:25
@parasharrajat Thanks for your explanation. I just updated [proposal](https://github.com/Expensify/App/issues/18664#issuecomment-1543722829) as your suggestion and test again. It works well
One small question, could we always call document.activeElement.blur() at the beginning of SetHTMLSync function and don't need more params

**Comment by dukenv0307** [comment] 2023-05-22 07:21
I just tested again and saw that we couldn't implement like this
> Could we always call document.activeElement.blur() at the beginning of SetHTMLSync function and don't need more params
Because if we always call document.activeElement.blur() at the beginning of SetHTMLSync, the composer also be blurred when the user holds the mouse and presses Cmd+C. So please ignore that.

**Comment by dukenv0307** [comment] 2023-05-22 07:32
@parasharrajat  In [my proposal](https://github.com/Expensify/App/issues/18664#issuecomment-1543722829), there are 2 solutions to fix this issue. Both solutions work well. But I prefer the main solution
 
> In both setHtml and setHTMLSync functions, we can define new param is called blurActiveinput. At the beginning of SetHTMLSync, we will call document.activeElement.blur() if blurActiveinput is true.

Because It makes sense that the composer should be blurred immediately after user click out like behavior in other places

**Comment by NicMendonca** [comment] 2023-05-23 08:35
Going OOO until June 5th so assigning a buddy to this GH to watch over the issue. I'll pick it back up when I am back from OOO if this is still open.

**Comment by robertjchen** [comment] 2023-05-23 14:21
Thanks for the discussions here, I agree with the main solution as well! 👍 

@tjferriss could you please proceed with hiring @dukenv0307 for this task? Thanks!

**Comment by dukenv0307** [comment] 2023-05-25 04:33
@parasharrajat I can't reproduce this bug on staging and the latest main (1.3.17-1). I am trying to check why this bug is resolved

**Comment by dukenv0307** [comment] 2023-05-25 10:38
Updated: [This PR](https://github.com/Expensify/App/pull/18782) caused a crash app. Then you fix it by [this commit](https://github.com/Expensify/App/commit/0397b5aef0648e79f0b71a1f2f295b03995ecce0)
This commit also fixes this bug

**Comment by tjferriss** [comment] 2023-05-28 04:13
I'm also not able to reproduce this bug so I'm going to close the issue.

**Comment by dukenv0307** [comment] 2023-05-28 05:29
@tjferriss  Should contributors be eligible for compensation in this issue. The solution provided was valid and the process of reviewing the pull request had already begun. However, due to subsequent changes, the solution became outdated.
cc @parasharrajat

**Comment by tjferriss** [comment] 2023-05-31 05:49
Yes, agreed. @parasharrajat @adeel0202 I have sent you both an offer in Upworks for the job.

@dukenv0307 I couldn't find you in Upworks. Can you please apply here: https://www.upwork.com/jobs/~0142123b8c491008a1

**Comment by tjferriss** [comment] 2023-06-02 01:56
Reporting bonus paid to @adeel0202 

Waiting on @parasharrajat and @dukenv0307 to accept offers to be paid. Then we can close the issue.

**Comment by robertjchen** [comment] 2023-06-05 03:22
waiting on @dukenv0307

**Comment by robertjchen** [comment] 2023-06-08 02:25
Thanks all, I think this can be closed.

**Comment by NicMendonca** [comment] 2023-06-08 21:31
I've paid everyone out! 🎉 thank you!

**Closed by NicMendonca** 2023-06-08 21:31 UTC
Labels: Daily, Internal, Bug
