### ISSUE TITLE
[$500] [DISTANCE] LOW: Distance IOU - Addresses are cleared after navigating between address and confirmation page

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#28913] opened 2023-10-05 13:12 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___
**Issue found when executing PR** https://github.com/Expensify/App/pull/26307
## Action Performed:
1. Go to https://staging.new.expensify.com/
2. Go to + > Request money > Distance
3. Enter start and finish address, then proceed all the way to the confirmation screen
4. Return back to the Distance address page
5. Proceed to the final confirmation page
6. Back to Distance address page

## Expected Result:
The addresses that are entered are preserved

## Actual Result:
The addresses that are entered are cleared

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android / native
- [x] Android / Chrome
- [x] iOS / native
- [x] iOS / Safari
- [x] MacOS / Chrome / Safari
- [x] MacOS / Desktop

**Version Number:** 1.3.78-0

**Reproducible in staging?:** Yes

**Reproducible in production?:** Yes

**If this was caught during regression testing, add the test name, ID and link from TestRail:**

**Email or phone of affected tester (no customers):**

**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/78819774/fb80e4bd-92d9-467f-bc3a-23e4fb850bc2

**Expensify/Expensify Issue URL:**

**Issue reported by:** Applause - Internal Team

**Slack conversation:**

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01e02f1e0185235867</li>
        <li>Upwork Job ID: 1735782081162653696</li>
        <li>Last Price Increase: 2023-12-15</li>
    </ul>
</details>

**Comment by kosmydel** [comment] 2023-10-05 14:56
Hey, I checked it since it was found when checking [my PR](https://github.com/Expensify/App/pull/26307). Just want to say, that this issue also occurs in production, so it's probably not related to my PR.

**Video**

https://github.com/Expensify/App/assets/104823336/bd87cd4a-c874-4bb5-9d3c-f39f857c5e02

**Comment by AmjedNazzal** [comment] 2023-10-05 16:15
## Proposal

### Please re-state the problem that we are trying to solve in this issue.

Distance IOU - Addresses are cleared after navigating between address and confirmation page

### What is the root cause of that problem?

In multiple places through the money request components we are using the following logic: 

```javascript
const shouldReset = props.iou.id !== moneyRequestId;
if (shouldReset) {
    IOU.resetMoneyRequestInfo(moneyRequestId);
}
```

This logic becomes problematic when IOU.navigateToNextPage is being called by the navigateToNextPage function and in MoneyRequestParticipantsPage as it repetedly checks shouldReset within it's useEffect but the issue here is that these two don't always have access to the updated reportID and so when the user chooses where the distance request will be shared, iou.id becomes "request" + the reportID but for the components I mentioned since they don't have access to that reportID the value of moneyRequestId will remain just "request" and so they will call IOU.resetMoneyRequestInfo  

### What changes do you think we should make in order to solve the problem?

We can either make some changes to make sure that these components are having the most recent reportID or we can add a safeguard check to make sure that a reportID does indeed exist before checking if it equals iou.id


In MoneyRequestParticipantsPage: 

```javascript
if(reportID.current){
    const moneyRequestId = `${iouType.current}${reportID.current}`;
    const shouldReset = iou.id !== moneyRequestId && !isNewReportIDSelectedLocally.current;
    if (shouldReset) {
    IOU.resetMoneyRequestInfo(moneyRequestId);
    }
}
```

In IOU.navigateToNextPage:

```javascript
if(report.reportID){
    if (shouldReset) {
        resetMoneyRequestInfo(moneyRequestID);
    }
}
```

There are a bunch of other possible options we can do here but the general idea is to not allow calling resetMoneyRequestInfo unless we do some control regarding reportID

### Result

https://github.com/Expensify/App/assets/74202751/f26a1bb3-ed9d-48b9-b8cb-e573d856a12f

**Comment by neil-marcellini** [comment] 2023-10-05 21:56
I think this will be fixed by https://github.com/Expensify/App/issues/26538#top, so I'm holding it on that.

**Comment by johncschuster** [comment] 2023-10-13 20:13
Still holding

**Comment by johncschuster** [comment] 2023-10-13 20:13
Shall we bump to Weekly while we wait, @neil-marcellini?

**Comment by johncschuster** [comment] 2023-10-16 20:38
Bumping to Weekly

**Comment by johncschuster** [comment] 2023-10-25 14:01
Still holding

**Comment by johncschuster** [comment] 2023-11-07 21:55
No update. We're still holding on https://github.com/Expensify/App/issues/26538#top

**Comment by johncschuster** [comment] 2023-11-22 22:18
Still holding

**Comment by johncschuster** [comment] 2023-12-01 22:17
Still holding

**Comment by dylanexpensify** [comment] 2023-12-14 19:54
off hold @johncschuster! 🎉

**Comment by johncschuster** [comment] 2023-12-15 22:01
I will be OOO starting Monday, December 18, and will return Tuesday, January 2.

**Current status:** 
This issue was _just_ taken off hold and assigned to a C+ member to start reviewing proposals.

If this issue is open when I'm back from OOO, I'll take it back over. Thank you!

**Comment by paultsimura** [comment] 2023-12-16 08:27
Not reproducible after the IOU flow refactoring

**Comment by AmjedNazzal** [comment] 2023-12-17 14:03
This has been resolved using `underscore` from `DefinitelyTyped`

**Comment by jjcoffee** [comment] 2023-12-18 09:34
@muttmuure We can close this!

**Comment by johncschuster** [comment] 2023-12-18 15:36
I happened to be traipsing through to finish up my OOO checklist. I'll go ahead and close it. Thanks, @jjcoffee!

**Closed by johncschuster** 2023-12-18 15:36 UTC
Labels: External, Daily, Help Wanted, Bug, Distance
