### ISSUE TITLE
[HOLD for payment 2023-10-05] [$500] Dev: Web - Trailing Newlines are not trimmed on the  My Note page.

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#27596] opened 2023-09-16 19:08 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Open the App and Create a workspace. If not created
2. Go to #admins
3. Click on header > Private notes > My note
4. Press on Notes
5. Add 3-4 newlines before the actual message; Press Save

## Expected Result:
Trailing Newlines should be trimmed on the My Note page.

## Actual Result:
Trailing Newlines are not trimmed on the My Note page, and it shows the empty lines on it.

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [x] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** Dev 1.3.70.5
**Reproducible in staging?:** n 
**Reproducible in production?:** n
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/93399543/f0d9be97-4d65-4837-88a3-5e2b5f77a91f

**Expensify/Expensify Issue URL:**
**Issue reported by:** @jayeshmangwani
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1694787278356809

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01a1c9388800197ffc</li>
        <li>Upwork Job ID: 1703123699888500736</li>
        <li>Last Price Increase: 2023-09-16</li>
<li>Automatic offers: </li>
<ul>
<li>jayeshmangwani | Contributor | 26743629</li>
<li>jayeshmangwani | Reporter | 26743630</li>
</ul></li>
    </ul>
</details>

**Comment by ahmedGaber93** [comment] 2023-09-16 19:08
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
Dev - Trailing Newlines are not trimmed on the  My Note page.
### What is the root cause of that problem?
we trim the `privateNote` only on amount in `useState` defaul value
https://github.com/Expensify/App/blob/76c1559fb3fbee1d07c8f210b522b63edd03920e/src/pages/PrivateNotes/PrivateNotesEditPage.js#L63

and not trim it when save 
https://github.com/Expensify/App/blob/76c1559fb3fbee1d07c8f210b522b63edd03920e/src/pages/PrivateNotes/PrivateNotesEditPage.js#L69-L76

### What changes do you think we should make in order to solve the problem?
we need to trim the `privateNote` before saving 
```javascript
const editedNote = parser.replace(privateNote.trim()); 
```

https://github.com/Expensify/App/blob/76c1559fb3fbee1d07c8f210b522b63edd03920e/src/pages/PrivateNotes/PrivateNotesEditPage.js#L69-L76
### What alternative solutions did you explore? (Optional)
N/A

**Comment by kbecciv** [comment] 2023-09-16 19:09
Proposal by: @jayeshmangwani
Slack conversation: https://expensify.slack.com/archives/C049HHMV9SM/p1694787278356809

## Proposal

### Please re-state the problem that we are trying to solve in this issue.
Trailing Newlines are not trimmed on the  My Note page.

### What is the root cause of that problem?
We are not trimming Private Note Value on Private Notes page, before passing the privateNote value to the API 

### What changes do you think we should make in order to solve the problem?
We should trim the privateNote Value here before passing to the API

https://github.com/Expensify/App/blob/76c1559fb3fbee1d07c8f210b522b63edd03920e/src/pages/PrivateNotes/PrivateNotesEditPage.js#L69-L70

```javascreipt
    const editedNote = parser.replace(privateNote.trim());
```

### What alternative solutions did you explore? (Optional)
none

**Comment by jayeshmangwani** [comment] 2023-09-16 20:25
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
Trailing Newlines are not trimmed on the  My Note page.

### What is the root cause of that problem?
We are not trimming Private Note Value on Private Notes page, before passing the privateNote value to the API 

### What changes do you think we should make in order to solve the problem?
We should trim the privateNote Value here before passing to the API

https://github.com/Expensify/App/blob/76c1559fb3fbee1d07c8f210b522b63edd03920e/src/pages/PrivateNotes/PrivateNotesEditPage.js#L69-L70

```javascript
const editedNote = parser.replace(privateNote.trim());
```

**Note** [This](https://github.com/Expensify/App/issues/27596#issuecomment-1722296099) was my proposal that I had added on [Slack](https://expensify.slack.com/archives/C049HHMV9SM/p1694890662671819?thread_ts=1694787278.356809&cid=C049HHMV9SM), so I am commenting on GH, too.

### What alternative solutions did you explore? (Optional)
none

**Comment by burczu** [comment] 2023-09-18 11:47
I've just reviewed all the proposals - they are all the same (and correct), but in fact [the one](https://github.com/Expensify/App/issues/27596#issuecomment-1722309122) from @jayeshmangwani was the first (he posted in [the slack thread](https://expensify.slack.com/archives/C049HHMV9SM/p1694787278356809) first, then @kbecciv posted it for him [here](https://github.com/Expensify/App/issues/27596#issuecomment-1722296099), and then he posted it here himself), so we should proceed with it.

🎀 👀 🎀 C+ reviewed

**Comment by jayeshmangwani** [comment] 2023-09-19 06:11
PR is ready for review
cc: @burczu

**Comment by iamjey6** [comment] 2023-09-21 02:40
@burczu friendly bump for review

**Comment by jayeshmangwani** [comment] 2023-09-21 04:14
@burczu friendly bump for review

**Comment by jayeshmangwani** [comment] 2023-10-06 07:03
@garrettmknight today payment will released so I want to ask if the urgency bonus be considered ?, though PR merged on 4th day but PR was raised after few hours I've assigned but C+ reviewed on 4th day,  TIA

**Assigned 6:44 AM** 
<img width="766" alt="Screenshot 2023-10-05 at 11 48 25 PM" src="https://github.com/Expensify/App/assets/35371050/ea0cb8c0-c050-4f6c-b93a-a7ae4e0e5441">


**PR raised 11:32 AM , Same day**
<img width="1030" alt="Screenshot 2023-10-05 at 11 48 39 PM" src="https://github.com/Expensify/App/assets/35371050/0737ef5e-a3c8-4963-87c7-89c472ea4637">

**Comment by garrettmknight** [comment] 2023-10-09 18:00
@jayeshmangwani the urgency bonus is based on the PR getting merged so this one didn't make it.

**Summary of payments:**
- urgency bonus? no
- Reporter: @jayeshmangwani $50 paid via Upwork
- Contributor: @jayeshmangwani $500 paid via Upwork
- Contributor+: N/A

Upwork job: https://www.upwork.com/jobs/~01a1c9388800197ffc

**Comment by kbecciv** [comment] 2023-10-14 14:08
Issue is reproducible on build 1.3.84.0

https://github.com/Expensify/App/assets/93399543/8051633f-d8f1-4769-be95-00471a1d51b8

**Comment by jayeshmangwani** [comment] 2023-10-14 14:16
@kbecciv Video you have attached is an expected behavior; we do not trim new lines between the notes. We trim if the note message has new lines at the start or end of the message

**Comment by jayeshmangwani** [comment] 2023-10-18 16:33
@namhihi237  is right [here](https://github.com/Expensify/App/issues/27596#:~:text=%2C%20I%20think%20it%27s%20another%20issue%20and%20caused%20by%20another%20PR); this is another issue caused by another PR. It used to work during existng issue's PR merge, but resurfaced after this [PR](https://github.com/Expensify/App/pull/29149). It looks like this is a regression from this [issue](https://github.com/Expensify/App/issues/28599).

cc: @burczu @MariaHCD

**Comment by MariaHCD** [comment] 2023-10-23 12:03
Okay, I don't have the most context on if that other issue caused this issue so I've asked here: https://github.com/Expensify/App/issues/28599#issuecomment-1775041682

**Comment by MariaHCD** [comment] 2023-10-25 14:31
Looks like it is indeed a regression from the other issue: https://github.com/Expensify/App/issues/28599#issuecomment-1775865180

I think we can close this one out.

**Closed by MariaHCD** 2023-10-25 14:31 UTC
Labels: External, Daily, Overdue, Awaiting Payment
