### ISSUE TITLE
[HOLD #16923] IOU - Tooltip of username and back button slides when modal is closed/opened

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#25403] opened 2023-08-17 14:29 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Open the staging web app
2. Go to any chat
3. Click on the + button > Request money
4. Enter an amount
5. Click on the user profile in the To field
6. Click on the back " <" button on the user profile

## Expected Result:
At step5, username tooltip should not slide with the modal opening and position should be fixed
At step 6, back button tooltip should not slide with closing the modal and the position should be fixed

## Actual Result:
At step5, username tooltip slides away once the profile modal is opened
At step 6, back button tooltip slides away to the right once profile modal is closed

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [x] MacOS / Safari
- [ ] MacOS / Desktop

**Version Number:** 1.3.55-0

**Reproducible in staging?:** Yes

**Reproducible in production?:** Yes

**If this was caught during regression testing, add the test name, ID and link from TestRail:**

**Email or phone of affected tester (no customers):**

**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/78819774/4d3e6bf9-ebaa-4e12-805f-6550b0a1f35e

https://github.com/Expensify/App/assets/78819774/d628e7a7-5d8d-4914-86a4-5faa6acda91d

**Expensify/Expensify Issue URL:**

**Issue reported by:** Applause - Internal Team

**Slack conversation:**

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by ShogunFire** [comment] 2023-08-17 18:50
## Proposal

### Please re-state the problem that we are trying to solve in this issue.

The tooltip slides with animation 

### What is the root cause of that problem?

We hide the tooltip onHoverOut.
I think on safari since we don't move the mouse, onHoverOut is not called so the tooltip doesn't hide and follows the component that is sliding because of the animation

### What changes do you think we should make in order to solve the problem?

In Tooltip, we can subscribe to the navigation event transitionStart and when it fires we can hide the tooltip (without animation)


### What alternative solutions did you explore? (Optional)

**Comment by ShogunFire** [comment] 2023-08-17 20:43
After testing my proposal, it seems like transitionStart is not always firing for some reason, maybe we could create our own event in linkTo method

**Comment by sonialiap** [comment] 2023-08-18 09:02
Following this [SO](https://stackoverflowteams.com/c/expensify/questions/8836) adding assignee while I'm OOO until Wednesday. I can take the issue back when I return

**Comment by alexpensify** [comment] 2023-08-18 20:34
Thank you for flagging, I've updated this one to be on hold

**Comment by alexpensify** [comment] 2023-08-23 17:57
Weekly Update: On Hold

**Comment by alexpensify** [comment] 2023-08-30 21:30
@sonialiap - I think you are back. Would you like to take this one back? Thanks!

**Comment by alexpensify** [comment] 2023-09-06 22:09
Weekly Update: On Hold

**Comment by alexpensify** [comment] 2023-09-12 22:33
Weekly Update: Should be ready for review again soon.

**Comment by alexpensify** [comment] 2023-09-20 04:53
@sonialiap - this one is ready for assignment again. I think you are online, so I'm removing myself from this one.

**Comment by sonialiap** [comment] 2023-09-25 04:41
I cannot reproduce this issue any longer. Closing ✅

**Closed by sonialiap** 2023-09-25 04:41 UTC
Labels: Daily, Overdue, Bug
