### ISSUE TITLE
[$500] Web - Partial scroll to upper member on selecting member on invite member

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#27867] opened 2023-09-20 14:19 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Open the app
2. Open settings->workspaces->any workspace->members->invite
3. Scroll to bottom and click on any user
4. Again scroll to bottom and click any user, observe that now it scrolls half way above to first selected user

## Expected Result:
App should either scroll back to top or should stop scroll above selected user to display selected user in top and user above it shouldn't be visible

## Actual Result:
App scrolls half way to upper user making current selected user visible and above selected user half visible

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [ ] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 1.3.72.6
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/93399543/1f2c08b1-43bc-40dd-b4f7-21e3f026bc94

https://github.com/Expensify/App/assets/93399543/c4d85cf9-ac20-4a61-b2f8-03559d6aed83

**Expensify/Expensify Issue URL:**
**Issue reported by:** @dhanashree-sawant
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1695142928514269

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01d4817e59f5fb70c4</li>
        <li>Upwork Job ID: 1704500577760190464</li>
        <li>Last Price Increase: 2023-09-27</li>
    </ul>
</details>

**Comment by s-alves10** [comment] 2023-09-20 14:42
This is a regression of [this PR](https://github.com/Expensify/App/pull/27692)

**Comment by lcsvcn** [comment] 2023-09-20 15:05
@s-alves10 it is fixed already? Should this issue be closed?

**Comment by s-alves10** [comment] 2023-09-20 15:08
@lcsvcn 

I'm sorry. I mislinked the PR.

**Comment by nahoma123** [comment] 2023-09-20 15:34
How do you join their slack or their "stackoverflowteams" accounts ?

**Comment by lcsvcn** [comment] 2023-09-20 15:44
@nahoma123 https://github.com/Expensify/App/blob/main/contributingGuides/CONTRIBUTING.md#slack-channels

**Comment by nahoma123** [comment] 2023-09-20 20:07
Contributor details
Your Expensify account email: nahomasnake12@gmail.com
Upwork Profile Link: https://www.upwork.com/freelancers/~019fafc6834461e494

**Comment by joekaufmanexpensify** [comment] 2023-09-21 08:31
@peterdbarkerUK you were the second BZ assignee here, and it doesn't need two, so I'm happy to keep this one!

**Comment by joekaufmanexpensify** [comment] 2023-09-21 08:44
I don't think this is a bug. We don't scroll to the top, as when the list gets longer, scrolling to the top means potentially not being able to see the most recent selection. 

Further, I don't think we stop the scroll after the most recently added user, since that doesn't make it obvious that there are others on the list. 

Going to sense check this in Slack, but I'm inclined to close this, as I think this is intentional.

**Comment by joekaufmanexpensify** [comment] 2023-09-22 08:03
Got it. I don't think that comment is conflicting with what we do now personally. We are scrolling to the selected item. We are just showing a part of the item above it so it's clear that there are items above it.

**Comment by joekaufmanexpensify** [comment] 2023-09-25 04:19
Not overdue. Going to take a closer look at this today

**Comment by joekaufmanexpensify** [comment] 2023-09-26 09:43
Hm, @allroundexperts curious for your thoughts on this? I still kinda feel like since what exists now works, it's not really worth making any changes since this is such a minor issue.

**Comment by joekaufmanexpensify** [comment] 2023-09-27 06:33
Still pending further discussion

**Comment by joekaufmanexpensify** [comment] 2023-09-28 06:38
Bumped in Slack

**Comment by joekaufmanexpensify** [comment] 2023-09-29 07:41
Thanks for the input! I still think it's best to close this one. Specifically, because there's no impact to the user experience. What exists now works. It does look ever so slightly different with larger font size, but it still works there too. So I don't think this warrants any changes. 

If anyone feels strongly that we should proceed here, LMK, and happy to bring this one to Slack for discussion!

**Closed by joekaufmanexpensify** 2023-09-29 07:41 UTC
Labels: External, Daily, Help Wanted, Bug
