### ISSUE TITLE
[$500] Unable to cancel or go back when the image is loading - Reported by @adeel0202

### ISSUE THREAD

**Issue by mvtglobally** [Expensify/App#8849] opened 2022-05-02 06:30 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Go to any chat
2. Open any attached image
3. Press the cancel icon or back button to go back when the image is loading

## Expected Result:
User should be able to go back even when the image is loading

## Actual Result:
User cannot go back when the image is loading

## Workaround:
unknown 

## Platform:

Where is this issue occurring?

- iOS
- Android

**Version Number:** 1.1.57-0
**Reproducible in staging?:** Y 
**Reproducible in production?:** Y 
**Email or phone of affected tester (no customers):** 
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation 

https://user-images.githubusercontent.com/43995119/166193504-11051d9d-f646-4663-bbd5-3ebd156d5872.mp4

**Expensify/Expensify Issue URL:** 
**Issue reported by:** @adeel0202
**Slack conversation:** https://expensify.slack.com/archives/C01GTK53T8Q/p1649873846197949

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

[this job](https://www.upwork.com/jobs/~01bfdda0e13c3bd3ea)

**Comment by joelbettner** [comment] 2022-05-02 18:37
I agree this would be a nice improvement.

**Comment by jboniface** [comment] 2022-05-03 19:31
[post here](https://www.upwork.com/jobs/~01bfdda0e13c3bd3ea)

**Comment by jayeshmangwani** [comment] 2022-05-05 20:31
issue is happening in this file
```src/components/ImageView/index.native.js``` 

and reason is react-native-image-size  package, 


https://github.com/Expensify/App/blob/ec828a22f031f646b19af819a27c70512a881712/src/components/ImageView/index.native.js#L8

it is blocking touchable until the getSize function does not resolve values,
 

https://github.com/Expensify/App/blob/ec828a22f031f646b19af819a27c70512a881712/src/components/ImageView/index.native.js#L71

and solution is that we can use react native core [Image.getsize](https://reactnative.dev/docs/image#getsize)
Image.getSize(this.props.url, (width, height) => {

this package was added in this PR, I am not sure about that this package is mandatory or we can directly use Image.getSize
[#6442](https://github.com/Expensify/App/pull/6442)

**Comment by jboniface** [comment] 2022-05-11 21:01
@chiragsalian and @rushatgabhane it looks like there is a proposal here for review

**Comment by chiragsalian** [comment] 2022-05-11 21:03
Isn't rushat OOO for a while? If so i think we should reassign to another C+ to do the first proposal review.

**Comment by rushatgabhane** [comment] 2022-05-11 21:04
@jboniface I'm OOO till May 14. Please assign @mananjadhav as per this thread. Thanks!!

https://expensify.slack.com/archives/C02NK2DQWUX/p1652282380139939?thread_ts=1652277963.845719&cid=C02NK2DQWUX

**Comment by chiragsalian** [comment] 2022-05-11 22:24
Reassigned

**Comment by mananjadhav** [comment] 2022-05-12 19:08
Thanks for your proposal @jayeshmangwani. Let me check why this dependency was added.

@iwiznia @aswin-s Any specific reason we added this dependency `react-native-image-size` instead of default `Image.getSize`? when we added [6442](https://github.com/Expensify/App/pull/6442)

**Comment by mananjadhav** [comment] 2022-05-15 17:20
> Any specific reason we added this dependency react-native-image-size instead of default Image.getSize? when we added

@aswin-s @iwiznia Can you help with the above comment?

**Comment by eVoloshchak** [comment] 2022-05-15 19:27
@mananjadhav 
As per [this](https://github.com/Expensify/App/issues/5193#issuecomment-974754218) comment:
> to support high resolution images (above 2048px) on Android, replace built in Image component with [FastImage](https://github.com/DylanVann/react-native-fast-image) and measure image dimensions using [react-native-image-size](https://www.npmjs.com/package/react-native-image-size).

**Comment by mananjadhav** [comment] 2022-05-15 19:54
Thanks for the comment @eVoloshchak. I read through the history of the issues. I get we're using `react-native-image-size` to get the `Image.getSize` function.  But we're trying to remove it here, so just want to ensure we don't break anything. Please bear with me for 1 day, or I'll get this checked internally.

**Comment by iwiznia** [comment] 2022-05-17 11:55
According to [this comment](https://github.com/Expensify/App/issues/5193#issuecomment-974397005):
>  It works just as expected on the iOS platform and we get the actual image width and height in the response. But on Android the story is completely different. On Android, ReactNative makes use of the Fresco image library under the hood to implement the Image component. And Fresco automatically downsamples the image if its dimension is above 2048px. So even though it downloads the original image, the one that gets rendered in Image component will be a downsampled version of the original image. This is done to improve ui performance and prevent memory leaks. The side effect of this downsampling is that the reported width and height will be much less than the original image and the displayed image also loses its sharpness. Result, a blurred picture.

**Comment by mananjadhav** [comment] 2022-05-17 18:41
Thanks for the comment @iwiznia.  @eVoloshchak. So if we remove `react-native-image-size`, it would cause the other issue to break. Any other solutions in mind?

**Comment by mallenexpensify** [comment] 2022-06-01 16:31
@chiragsalian @mananjadhav any reason this shouldn't be doubled? Looks like it should but want to double check since I'm new here

**Comment by mananjadhav** [comment] 2022-06-02 19:45
> As for removing react-native-image-size, have we ever tried react native core [Image.getsize](https://reactnative.dev/docs/image#getsize)

@chiragsalian Yeah, @jayeshmangwani's proposal is to use  the react native core `Image.getSize`, but it seems the package was added in another issue and would break it if we remove the package. https://github.com/Expensify/App/issues/8849#issuecomment-1128776039 So I am looking for a solution that either solves with this package or uses `Image.getSize` and doesn't break the old issue.

**Comment by phuongpt** [comment] 2022-06-03 00:40
https://user-images.githubusercontent.com/4443583/171761435-bb0c229f-7658-4bd1-84ab-46ca2d080704.mp4
I have a fix for this issue, the main reason is running a heavy native task is blocking JS UI on Android, so I created a new thread for that. Here are the main points of this fix:
* This issue happens only on Android
* Still keep using: `react-native-image-size` -> doesn't break other things
* But have to change  `react-native-image-size` native, so It's still a binary change
* Does the team prefer using `patch-package` or forking the 3rd library for the fix

**Comment by mananjadhav** [comment] 2022-06-03 21:04
@phuongpt I like your idea of fixing the `react-native-image-size`. We can fork the 3rd party library and also send a PR upstream for the fix. This way we can contribute back to the open-source community and others can benefit from your fix. You can elaborate on the intended changes and we can take a look. Does that sound okay?

**Comment by phuongpt** [comment] 2022-06-04 00:08
OK, sounds good. @mananjadhav.

**Comment by mananjadhav** [comment] 2022-06-08 22:13
@phuongpt While this looks fine for Android, what about iOS?

**Comment by phuongpt** [comment] 2022-06-08 23:02
@mananjadhav As I mentioned above this issue happens only on Android. It works normally on iOS. 
Couple comments above also mentioned it.

**Comment by mananjadhav** [comment] 2022-06-08 23:20
> this issue happens only on Android.

@phuongpt I missed your comment, and I can confirm that this works fine in iOS. @phuongpt Can you confirm your change doesn't break the other issue tagged in the above comments? Once you confirm I feel we're good here.

> Couple comments above also mentioned it.

These were not related to this issue.  

----


@chiragsalian @phuongpt's proposal here https://github.com/Expensify/App/issues/8849#issuecomment-1145474798 of adding the fix to `react-native-image-size` looks good to me. Running it on a separate thread will make it non-blocking on the UI. What do you think? 

🎀 👀 🎀
C+ reviewed

**Comment by phuongpt** [comment] 2022-06-08 23:27
Yes @mananjadhav I confirm.

**Comment by chiragsalian** [comment] 2022-06-08 23:55
I think the Proposal LGTM as well. 
Feel free to create a PR @phuongpt and @jeremyhollmexpensify feel free to hire him for his work 🙇

**Comment by phuongpt** [comment] 2022-06-09 01:49
@mallenexpensify please verify my proposal on Upwork, thank you.

**Comment by mallenexpensify** [comment] 2022-06-09 23:12
Hired @phuongpt , @adeel0202 and @mananjadhav can you also apply https://www.upwork.com/jobs/~01458d590c1e09df99
Thanks

**Comment by phuongpt** [comment] 2022-06-10 03:34
@mananjadhav @chiragsalian looks like I'm lacking permission to push a branch, please help to resolve it, thank you.
![Screen Shot 2022-06-10 at 10 27 02](https://user-images.githubusercontent.com/4443583/172985012-274e378e-15c0-409a-bb81-c34c08401812.png)

**Comment by adeel0202** [comment] 2022-06-10 06:36
@mallenexpensify, do I apply to the same upwork job or will there be a separate job for reporting?

**Comment by mananjadhav** [comment] 2022-06-10 09:50
@phuongpt I am a little confused about what we're trying here. 
Steps to merge this would be:
- @mananjadhav or @chiragsalian to help you with creating a forked version of the `react-native-image-size`. This shouldn't stop you from testing your changes and moving the PR
- You submit the PR to the newly forked repo of Expensify
- You fork `Expensify/App.git` into your repo, where you update the package.json with the dependency
- Test your changes locally on all the platforms (and also take screenshots/videos)
- Submit the PR for `Expensify/App`
- Fill in the GH PR body with the checklist and the relevant screenshot/videos.

@chiragsalian Feel free to add if I am missing anything. Also, I am not sure I have access to create a forked repo in `Expensify` workspace. Can you help with this, please?

**Comment by phuongpt** [comment] 2022-06-10 10:09
@mananjadhav got it, please let me know when we have a forked version of the `react-native-image-size` for `Expensify`, thank you.

**Comment by mallenexpensify** [comment] 2022-06-13 20:25
@adeel0202 please apply/accep the same job, if it states a higher price than the $250 for reporting I will adjust when I pay.  Thx

**Comment by adeel0202** [comment] 2022-06-14 06:39
@mallenexpensify I have applied, thanks.

**Comment by phuongpt** [comment] 2022-06-14 23:55
@chiragsalian Could you please create a forked version of
https://github.com/eXist-FraGGer/react-native-image-size
for Expensify?

**Comment by mananjadhav** [comment] 2022-06-16 07:08
> @chiragsalian Could you please create a forked version of https://github.com/eXist-FraGGer/react-native-image-size for Expensify?

@chiragsalian Bump ^ I don't have permissions to create one.

**Comment by chiragsalian** [comment] 2022-06-17 22:34
I also don't have permissions to create one but i've created an issue so that the correct person can fork it.

**Comment by chiragsalian** [comment] 2022-06-21 18:52
Yes looks like the fork was created here - https://github.com/Expensify/react-native-image-size
Does that look alright?

**Comment by mananjadhav** [comment] 2022-06-21 18:55
Yeah looks alright to me. @phuongpt Can you please raise a PR for this and update once done? We can now move forward with this one.

**Comment by phuongpt** [comment] 2022-06-22 03:40
@mananjadhav could you please review https://github.com/Expensify/App/pull/9526, thanks.

**Comment by chiragsalian** [comment] 2022-06-30 17:18
Yup, just reviewed and merged it 🙂

**Comment by laurenreidexpensify** [comment] 2022-07-06 15:59
Bumping back to weekly as the external labee confused melv

**Comment by laurenreidexpensify** [comment] 2022-07-11 13:45
Merged and on staging, should hit prod this week

**Comment by mananjadhav** [comment] 2022-07-15 22:25
This is in production but its title wasn't updated.

**Comment by phuongpt** [comment] 2022-07-20 10:40
@mallenexpensify seems this task is already done, could you please verify this job on Upwork, thanks.

**Comment by mananjadhav** [comment] 2022-07-20 20:54
> @mallenexpensify seems this task is already done, could you please verify this job on Upwork, thanks.

@laurenreidexpensify Quick bump. The regression period is complete. PR was deployed 8 days back.  For some reason title wasn't updated.

**Comment by laurenreidexpensify** [comment] 2022-07-26 13:22
@mananjadhav @phuongpt so sorry here. For context Matt was unexpectedly offline and the messages in Upwork were going to him, not me. I was out for a few days so only saw this now. 

@phuongpt has been paid, and @mananjadhav as soon as you accept job in Upwork will issue to you.

Again sorry folks, when teh automation failed this got lost!

**Comment by adeel0202** [comment] 2022-07-26 13:24
@laurenreidexpensify, I'm also expecting the reporting bonus.

**Comment by mananjadhav** [comment] 2022-07-26 13:28
No worries @laurenreidexpensify. Thanks for helping out here. I've accepted

**Comment by adeel0202** [comment] 2022-07-26 13:33
While you're at it, @laurenreidexpensify please check the comment on [this issue](https://github.com/Expensify/App/issues/8934#issuecomment-1155118468) too. I have been expecting reporting bonus for that issue as well but haven't got any response for many weeks 😄

**Comment by laurenreidexpensify** [comment] 2022-07-26 13:42
oh gosh we've lost the plot on this one 😹 on it @adeel0202 - offer sent, thanks for your patience and sorry for all the chaos here!!

**Comment by adeel0202** [comment] 2022-07-26 13:43
No worries 😂 accepted the offer for this one.

**Comment by phuongpt** [comment] 2022-07-26 13:44
Thank you @laurenreidexpensify!

**Comment by laurenreidexpensify** [comment] 2022-07-26 13:46
Okay everyone is paid :) We done :) Thanks folks

**Closed by laurenreidexpensify** 2022-07-26 13:46 UTC
Labels: Reviewing, Exported, External, Engineering, Daily, Improvement
