### ISSUE TITLE
[HOLD FOR #49931][$250]  Expensify card - Deactivated card re-appears again (occasionally)

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#51045] opened 2024-10-17 17:14 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 9.0.50-1
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**If this was caught on HybridApp, is this reproducible on New Expensify Standalone?:** N/A
**If this was caught during regression testing, add the test name, ID and link from TestRail:**https://expensify.testrail.io/index.php?/cases/view/3272221
**Issue reported by:** Applause - Internal Team

## Action Performed:
Precondition: expensifail account. Workspace with enabled Expensify card feature and added VBA.
1. Go to WS > Expensify card
2. Issue card for a user (Physical or Virtual)
3. Click on added card > Deactivate card > Deactivate

## Expected Result:
Card disappeared

## Actual Result:
Sometimes card re-appeared and user has to deactivate it again

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Standalone
- [ ] Android: HybridApp
- [ ] Android: mWeb Chrome
- [ ] iOS: Standalone
- [ ] iOS: HybridApp
- [ ] iOS: mWeb Safari
- [ ] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

<details>
  <summary>Add any screenshot/video evidence</summary>

  
</details> 

https://github.com/user-attachments/assets/ca2aa1e3-c9cc-40f6-8ffa-b188f8df3003

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~021847105131344829604</li>
        <li>Upwork Job ID: 1847105131344829604</li>
        <li>Last Price Increase: 2024-10-18</li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @abdulrahuman5196</details>

**Comment by lanitochka17** [comment] 2024-10-17 17:14
@jliexpensify  FYI I haven't added the External label as I wasn't 100% sure about this issue. Please take a look and add the label if you agree it's a bug and can be handled by external contributors

**Comment by Gitstar-OC** [comment] 2024-10-17 17:25
Hey, How can I get acess to solve this issues I have asked for various issues and some chats are discusses on slack and some on stackoverflow. I have send an email before couple of weeks but still not got any reply. Any other way to get reply faster or solve this issues ?

**Comment by jliexpensify** [comment] 2024-10-18 02:41
@abdulrahuman5196 @lanitochka17 from what I'm seeing, the cards are getting deactivated but there's a lag.

**Comment by mkzie2** [comment] 2024-10-18 08:46
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
Sometimes card re-appeared and user has to deactivate it again

### What is the root cause of that problem?
After we create a card, `GetMissingOnyxMessages` API is called and the queue is paused [here](https://github.com/Expensify/App/blob/d1f6190f6503fea55d16ca9e66ea7d70788bad23/src/libs/actions/OnyxUpdates.ts#L151) and the `CreateExpensifyCard`'s Onyx data is pushed to `queuedOnyxUpdates`. After the queue is unpaused, because there is no other write API in the queue, the Onyx above isn't updated to OnyxDB, and the `queuedOnyxUpdates` has old data.

<img width="690" alt="Screenshot 2024-10-18 at 15 36 05" src="https://github.com/user-attachments/assets/d4883255-9909-4df2-bb2f-7a4a00b3b3d2">


https://github.com/Expensify/App/blob/d1f6190f6503fea55d16ca9e66ea7d70788bad23/src/libs/Network/SequentialQueue.ts#L34

That is why the added card isn't shown immediately after `CreateExpensifyCard` API is complete, it's only shown after  `OpenPolicyExpensifyCardsPage` API is called again.


After we deactivate the card, the `queuedOnyxUpdates` is updated to OnyxDB [here](https://github.com/Expensify/App/blob/d1f6190f6503fea55d16ca9e66ea7d70788bad23/src/libs/Network/SequentialQueue.ts#L174) which includes the old card data of `CreateExpensifyCard` API.

This is the RCA of this issue

### What changes do you think we should make in order to solve the problem?
When the queue is unpaused here, we should update `queuedOnyxUpdates` to OnyxDB if `numberOfPersistedRequests` is `0`

```
if (numberOfPersistedRequests === 0) {
    flushOnyxUpdatesQueue();
}
```
https://github.com/Expensify/App/blob/d1f6190f6503fea55d16ca9e66ea7d70788bad23/src/libs/Network/SequentialQueue.ts#L190
### What alternative solutions did you explore? (Optional)

**Comment by DylanDylann** [comment] 2024-10-22 04:47
The same RCA with https://github.com/Expensify/App/issues/49931

**Comment by jliexpensify** [comment] 2024-10-22 04:52
Thanks @DylanDylann - will pop this issue on HOLD for now.

**Comment by jliexpensify** [comment] 2024-11-14 09:43
Still on hold

**Comment by aldo-expensify** [comment] 2024-11-30 01:54
I'm making the backend PR ready for review: https://github.com/Expensify/Auth/pull/13168

**Comment by DylanDylann** [comment] 2024-12-09 07:34
@jliexpensify This issue has already been fixed


https://github.com/user-attachments/assets/4cc7725a-b811-4958-b5d5-0bdd5e9dbdb7

**Comment by jliexpensify** [comment] 2024-12-09 22:32
Nice, thank you! Lets close this out.

**Closed by jliexpensify** 2024-12-09 22:32 UTC
Labels: External, Monthly, Bug
