### ISSUE TITLE
Clicking on `chat with your specialist` navigates to LHN instead of #admins

### ISSUE THREAD

**Issue by kavimuru** [Expensify/App#13690] opened 2022-12-19 16:01 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:

1. Create new user
2. Create new workspace, user will get notification
3. kill the app and remove it from background
4. click on notification
5. it will navigate to concierge chat
6. click on chat with your specialist

## Expected Result: 
should navigate to chat screen with expensify specialist

## Actual Result : 
navigate to LHN

## Workaround:
done

## Platform:

Where is this issue occurring?

- Android

**Version Number:** 1.2.41-1
**Reproducible in staging?:** y
**Reproducible in production?:** y
**Email or phone of affected tester (no customers):** 
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** 

https://user-images.githubusercontent.com/43996225/208468030-10305a5e-fa55-4bae-af2c-3536e0b4e80d.mp4

https://user-images.githubusercontent.com/43996225/208467855-78815a17-e274-4370-9134-5db86952663f.mp4

**Expensify/Expensify Issue URL:** 
**Issue reported by:** @gadhiyamanan 
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1671280857859059

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by marcochavezf** [comment] 2023-01-03 01:42
Grabbing this one

**Comment by marcochavezf** [comment] 2023-01-03 01:43
Not overdue

**Comment by marcochavezf** [comment] 2023-01-03 17:56
Tested on Android v1.2.47-0 and locally using `main` branch and works fine. Probably this was fixed recently, I think we can close this one.

https://user-images.githubusercontent.com/6829422/210413364-2cb1b703-4baa-499e-abb1-0f7bfdbfc94b.mp4

**Comment by marcochavezf** [comment] 2023-01-04 21:44
Seems we need to [close the app](https://expensify.slack.com/archives/C049HHMV9SM/p1672769325221179?thread_ts=1671280857.859059&cid=C049HHMV9SM) to reproduce the issue. I'm going to re-test again.

**Comment by marcochavezf** [comment] 2023-01-10 00:30
I was able to reproduce this one on production (by closing the app and tapping on the notification). I'm going to continue working on this one locally.

**Comment by trjExpensify** [comment] 2023-01-10 14:14
Closing this, it's a dupe. Comment in the thread if you want to discuss it further!

**Closed by trjExpensify** 2023-01-10 14:14 UTC
Labels: Daily, Bug

**Comment by marcochavezf** [comment] 2023-01-10 16:32
Yeah it makes sense to close this one after reading the discussion in the other one. Closing it.

**Comment by marcochavezf** [comment] 2023-01-10 16:34
Lol the other closed message didn't appear until I commented.
