### ISSUE TITLE
Card - Entering amount $55666666.52 and tapping next all errors are not displayed to proceed

### ISSUE THREAD

**Issue by IuliiaHerets** [Expensify/App#52033] opened 2024-11-05 12:29 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 9.0.57-3
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**Issue reported by:** Applause Internal Team

## Action Performed:
1. Launch app
2. Login with account with expensify card enabled with bank account added, and few members invited in workspace
3. Go to workspace settings
4. Tap expensify card
5. Tap issue card - physical card - monthly - next
6. Enter an big amount $55666666.52
7. Tap next
8. Note error shown - please enter an amount less than $21474836
9. Delete digits before decimal
10. Now note error "please enter an whole dollar amount before continuing" shown

## Expected Result:
Entering amount $55666666.52 and tapping next, both error please enter an amount less than $21474836 &"please enter an whole dollar amount before continuing" must be shown

## Actual Result:
Entering amount $55666666.52 and tapping next all errors are not displayed to proceed. Only one error "please enter an amount less than $21474836" displayed and after correcting this other error displayed "please enter an whole dollar amount before continuing".

## Workaround:
Unknown

## Platforms:

- [x] Android: Standalone
- [x] Android: HybridApp
- [x] Android: mWeb Chrome
- [ ] iOS: Standalone
- [ ] iOS: HybridApp
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

https://github.com/user-attachments/assets/3b05e378-12fa-4f95-a716-9aa5cec71f5a
  
</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by bernhardoj** [comment] 2024-11-05 14:21
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
The OP expects that both error messages that state to enter a whole dollar amount and enter an amount less than the limit will be shown. I think one error message should be shown at a time, but the "enter a whole dollar amount" should be prioritized.

### What is the root cause of that problem?
We started to add the maximum amount validation in this [PR](https://github.com/Expensify/App/pull/50985). However, the validation error overrides any previous validation error found.
https://github.com/Expensify/App/blob/b9149456da0d57536587e8cfa30ec207cf96f6fe/src/pages/workspace/expensifyCard/issueNew/LimitStep.tsx#L50-L60
https://github.com/Expensify/App/blob/b9149456da0d57536587e8cfa30ec207cf96f6fe/src/pages/workspace/expensifyCard/WorkspaceEditCardLimitPage.tsx#L90-L100

### What changes do you think we should make in order to solve the problem?

We need to update the validation logic so it only sets the limit error if both previous validation passes.

```
if (!Number(values.limit)) {
    errors.limit = translate('iou.error.invalidAmount');
} else if (!Number.isInteger(Number(values.limit))) {
    errors.limit = translate('iou.error.invalidIntegerAmount');
} else if (Number(values.limit) > CONST.EXPENSIFY_CARD.LIMIT_VALUE) {
    errors.limit = translate('workspace.card.issueNewCard.cardLimitError');
}
```

**Comment by CortneyOfstad** [comment] 2024-11-12 22:08
I'm going to be honest, this is a very niche error and the parameters are too specific to consider it an active bug. Because of that, I am going to close this.

**Closed by CortneyOfstad** 2024-11-12 22:08 UTC
Labels: Daily, Overdue, Bug
