### ISSUE TITLE
[$250] Log out - URL in sign in page is ../settings/troubleshoot after logging out

### ISSUE THREAD

**Issue by m-natarajan** [Expensify/App#43057] opened 2024-06-04 19:03 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.79-2
**Reproducible in staging?:** y
**Reproducible in production?:** n
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** Applause internal team
**Slack conversation:** 

## Action Performed:
1. Go to staging.new.expensify.com
2. Go to Account settings > Troubleshoot.
3. Log out.
4. Note that URL in sign in page.

## Expected Result:
URL in sign in page should be staging.new.expensify.com

## Actual Result:
URL in sign in page is https://staging.new.expensify.com/settings/troubleshoot
after logging out.
The URL could be report URL other than https://staging.new.expensify.com/settings/troubleshoot
after logging out.
## Workaround:
unknown
## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [x] Android: mWeb Chrome
- [ ] iOS: Native
- [x] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

https://github.com/Expensify/App/assets/38435837/fd35c554-0b6f-4b8e-937d-2a1da1e29ec5

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~0100e267e9dc04f517</li>
        <li>Upwork Job ID: 1798115131297120256</li>
        <li>Last Price Increase: 2024-06-04</li>
<li>Automatic offers: </li>
<ul>
<li>getusha | Reviewer | 102613522</li>
<li>dominictb | Contributor | 102613525</li>
</ul></li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @getusha</details>

**Comment by m-natarajan** [comment] 2024-06-04 19:04
@tgolen FYI I haven't added the External label as I wasn't 100% sure about this issue. Please take a look and add the label if you agree it's a bug and can be handled by external contributors

**Comment by m-natarajan** [comment] 2024-06-04 19:04
We think that this bug might be related to  #vip-vsb

**Comment by tgolen** [comment] 2024-06-04 22:11
I am removing the deploy blocker label since this is an edge case flow. I'm also marking it as `external` to have it investigated further.

**Comment by gorvk** [comment] 2024-06-05 06:09
Hi, I would like to work on this issue. 
I found the root cause and I think It is related to navigation after user sign out from InitialSettingsPage

**Comment by bernhardoj** [comment] 2024-06-05 06:13
Reverting https://github.com/Expensify/App/pull/42465 solves the issue for me.

**Comment by gorvk** [comment] 2024-06-05 06:25
> 📣 @gorvk! 📣 Hey, it seems we don’t have your contributor details yet! You'll only have to do this once, and this is how we'll hire you on Upwork. Please follow these steps:
> 
> 1. Make sure you've read and understood the [contributing guidelines](https://github.com/Expensify/App/blob/main/contributingGuides/CONTRIBUTING.md).
> 2. Get the email address used to login to your Expensify account. If you don't already have an Expensify account, create one [here](https://new.expensify.com/). If you have multiple accounts (e.g. one for testing), please use your main account email.
> 3. Get the link to your Upwork profile. It's necessary because we only pay via Upwork. You can access it by logging in, and then clicking on your name. It'll look like [this](https://www.upwork.com/freelancers/~01ca8ad8ce36b9eceb). If you don't already have an account, sign up for one [here](https://www.upwork.com/nx/signup/?dest=home).
> 4. Copy the format below and paste it in a comment on this issue. Replace the placeholder text with your actual details.
>    ![Screen Shot 2022-11-16 at 4 42 54 PM](https://user-images.githubusercontent.com/30609178/231263719-a8a3b7d3-36a0-4d7f-8ad4-cebe1f560fa4.png)
>    Format:
> 
> ```
> Contributor details
> Your Expensify account email: <REPLACE EMAIL HERE>
> Upwork Profile Link: <REPLACE LINK HERE>
> ```

Contributor details
Expensify account email: dev.gouravk@gmail.com
Upwork Profile Link: https://www.upwork.com/freelancers/~01c682f3611e8d2f4d

**Comment by gorvk** [comment] 2024-06-05 06:26
> Reverting #42465 solves the issue for me.

@bernhardoj on reverting, will it not reopen the app crashing issue related #42465 PR ?

**Comment by gorvk** [comment] 2024-06-05 08:22
> Can u guys reproduce this on latest main? I couldn't reproduce it.

I was also confused at first, and after debugging it is reproducible on staging.new.expensify.com

**Comment by bernhardoj** [comment] 2024-06-05 10:30
The video is not exactly the same as in OP as it would be long to log out and log in twice, but you can see the URL path stays but is fixed after removing the patched code.


https://github.com/Expensify/App/assets/50919443/4ab496a3-6d77-487c-bd72-44b9861d8217

**Comment by getusha** [comment] 2024-06-05 11:33
Since the offending PR is still on the regression period @dominictb and @ishpaul777 handle this.

**Comment by getusha** [comment] 2024-06-18 12:45
Handled by @ishpaul777 and @dominictb as a regression

**Closed** 2024-08-07 19:59 UTC
Labels: Reviewing, External, Engineering, Monthly, Bug
