### ISSUE TITLE
Bug: Mark as unread not being synced on web and mobile app platforms @chauchausoup

### ISSUE THREAD

**Issue by kavimuru** [Expensify/App#11514] opened 2022-10-02 00:04 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:

1. Go to any chat on web
2. Press Mark as unread
3. Check mobile app LHN

## Expected Result:
Mark as unread should have been synced in mobile app too from web.

## Actual Result:
 Mobile apps doesn’t shows BOLD headline in chat users

## Workaround:
Unknown

## Platform:

Where is this issue occurring?

- Web
- iOS
- Android

**Version Number:** 1.2.11-0
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**Email or phone of affected tester (no customers):** 
**Logs:** https://stackoverflow.com/c/expensify/questions/4856

https://user-images.githubusercontent.com/43996225/193432493-f804c1da-f90d-4a1a-8da2-081283a9b442.MP4

![image](https://user-images.githubusercontent.com/43996225/193432494-57e99c4c-4e99-4ece-b31a-8eee8e902674.png)

**Notes/Photos/Videos:** 
**Expensify/Expensify Issue URL:** 
**Issue reported by:** @chauchausoup
**Slack conversation:** https://expensify.slack.com/archives/C01GTK53T8Q/p1664606700652429

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by stephanieelliott** [comment] 2022-10-04 15:29
Was able to repro!

**Comment by mountiny** [comment] 2022-10-04 19:40
Gonna look tomorrow

**Comment by mountiny** [comment] 2022-10-05 08:10
Discussed this with Marc and albeit it is not instantaneous, it works after a while when the chats sync, I have confirmed that. I dont think this is something super valuable to work on right now since it works with some delay which depends on when the app syncs new chats. Gonna close this one out.

**Closed by mountiny** 2022-10-05 08:10 UTC
Labels: Engineering, Daily

**Comment by chauchausoup** [comment] 2022-10-13 03:58
@mountiny here at my end not even a time delay but the issue is there even on multiple refresh of both web and mobile platforms. 
Don't you think thats a bug, that even on refreshing both platforms multiple times the mark as unread is not being synced ?

**Comment by mountiny** [comment] 2022-10-13 10:01
@chauchausoup I wasnt able to reproduce unfortunately :/ for me it syncs fine after couple seconds. However, this can depend on internet speed I am sure.

Additionally we have an internal initiative which will refactor how the logic of unread (amongst other things) works so I would prefer not to dig into this, until that is done. And we also reworking how notifications are handled which might also touch this codebase.

Once the project is finished, we can come back to these and see how consistent they are to reproduce

**Comment by chauchausoup** [comment] 2022-10-20 04:35
@mountiny similar issue is being recognized by internal testers too in here: https://github.com/Expensify/App/issues/11951

**Comment by mountiny** [comment] 2022-10-20 20:46
Hmm I think the issue you have linked is quite different than this one
