### ISSUE TITLE
[$500] Thread – Draft message disappears after page view finishes loading.

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#31705] opened 2023-11-22 14:21 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.2.0
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** Applause - Internal Team
**Slack conversation:**

## Action Performed:
1. Go to https://staging.new.expensify.com/
2. Log in with any account that has access to a workspace
3. Go to global create > request money > choose a workspace > confirm
4. Click on the report preview component in the workspace chat to access the report view
5. Right click on the request preview component and select "Reply in thread"
6. Start typing quickly before the skeleton UI finishes loading the request view
7. Once loaded, observe the message disappears. 

## Expected Result:
Draft message should remain in the compose box.

## Actual Result:
Draft message disappears after the request page view loads.

## Workaround:
Wait until it loads before typing. 

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [x] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

https://github.com/Expensify/App/assets/93399543/8023e808-0c85-4734-a821-7868eee4f77b

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~019569b231b07825eb</li>
        <li>Upwork Job ID: 1727331482736373760</li>
        <li>Last Price Increase: 2023-11-22</li>
    </ul>
</details>

**Comment by FitseTLT** [comment] 2023-11-22 14:43
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
Draft of message disappears after Thread page loads
### What is the root cause of that problem?
This is because as we open thread page it rerenders main compose so it's content is empty not the value it had on previous report
### What changes do you think we should make in order to solve the problem?

We have to disable typing input into the compose while the page is transitioning into thread page to avoid confusion for the user.
### What alternative solutions did you explore? (Optional)

**Comment by esh-g** [comment] 2023-11-22 15:54
# Proposal

## Please re-state the problem
Thread – Draft of message disappears after Thread page upload.

## What is root cause?
There are two issue here:
1. The IOU child report is not being generated optimistically unlike threads for a comment.
2. The composer allows setting the draft even though the `reportID` is `0`.

Unlike normal comments, `IOU` actions have a `childReportID` that is set by the backend when the action is created (we don't generate it optimistically). This means that if we create a request online and then go offline and click on the request, we are greeted with an infinite loading screen

https://github.com/Expensify/App/assets/77237602/33c3e6ac-4129-43ce-b6ed-288d5367e6a2

## What changes should be made to fix this?

### Options for first issue
**Option 1**
The backend should not generate the child report for the request as it is not generated on the front-end and the backend should not return the `childReportID` field so that it can be generated optimistically in the front-end when required.

**Option 2**
Instead of generating the child report on the backend, we can add the `childReportID` on the front-end itself and build the child report optimistically for every money request in the `IOU.getMoneyRequestInformation()` method itself.

<hr />

### Solution for second issue

We can pass the `report` to the `ReportFooter` even when the report is not loaded here from the route itself:
https://github.com/Expensify/App/blob/fc14a3f3535e5050421c8f99b5bb5425db81fbb0/src/pages/home/ReportScreen.js#L452
```js
<ReportFooter isReportReadyForDisplay={false} report={{reportID: getReportID(route)}} />

```
This prevents the need for adding any additional prop as well.

**Comment by trjExpensify** [comment] 2023-11-23 18:57
Interesting! I can reproduce this reliably!

**Comment by trjExpensify** [comment] 2023-11-27 11:03
Awaiting your input @thesahindia!

**Comment by trjExpensify** [comment] 2023-12-11 11:03
@puneetlath bump on the secondary proposal review here please!

**Comment by puneetlath** [comment] 2023-12-13 16:35
Sorry for the delay, but I'm having a bit of a hard time wrapping my head around this. Is this understanding correct: 

1. When you create a request while online, the back-end returns the child report associated with that request
2. If you click "reply in thread" on the reportAction in the workspace chat you are taken to the child report
3. When you create a request while offline, we create an optimistic reportAction in the workspace chat
4. If you click "reply in thread" on the reportAction in the workspace chat, we create an optimistic thread report, which ends up getting overwritten by the back-end when we come online

Is that a proper understanding of the issue?

**Comment by esh-g** [comment] 2023-12-13 16:38
Yes @puneetlath... basically the BE sends the `childReportID` for the report. Which means we cannot generate the `childReport` optimistically on the front-end. If the backend doesn't send `childReportID`, we would be able to optimistically generate it online.

**Comment by esh-g** [comment] 2023-12-13 16:53
@puneetlath When we create a new money request online, the backend returns a `childReportID` associated with that report action.

This means that there is no `childReport` for the money request action that exists on the front-end. It is only the `childReportID` on the report. So when we go offline and try to go to the thread of the money request action, the `navigateToAndOpenChildReport` function is executed.
https://github.com/Expensify/App/blob/5125df61bb6a95af6349760ba5d8bf23d51a16e2/src/libs/actions/Report.ts#L718-L724
And as you can see, is the `childReportID` exists, it directly navigates to the report ID instead of creating an optimistic one because the `childReport` data doesn't actually exist on the front-end.


Here are some corrections for the points you provided:

1. The backend doesn't return `child report`, it only returns `childReportID` for the money action.
2. When clicking "reply in thread" offline, we are taken to the report ID but there is no data. If online, the `OpenReport` API request is made and we get the data.
3. When creating the request offline, `childReportID` is not generated until we click on "reply in thread"
4. There is no overwriting taking place the front-end doesn't generate the optimistic report at all.

**Comment by trjExpensify** [comment] 2023-12-18 12:40
@puneetlath does that clear things up for you?

**Comment by trjExpensify** [comment] 2023-12-21 18:03
Awaiting @puneetlath's input.

**Comment by puneetlath** [comment] 2023-12-28 22:52
It does clear things up. However, I _thought_ we were changing things as part of the violations project so that the transaction threads (child reports) are created optimistically with the expense. Am I remembering that correctly @cead22?

**Comment by cead22** [comment] 2023-12-29 00:08
Yes, this sounds similar to https://github.com/Expensify/App/issues/33114 which will get fixed by https://github.com/Expensify/App/pull/32461/files, but not quite the same, and it sounds like we should generate optimistic `childReportID` and send that with RequestMoney

If the `childReportID` we're talking about here is the same as `transactionThreadReportID`, then this might be the exact the same issue, and it should be fixed by that PR

Let me know if that clears things up, or if I misunderstood

**Comment by puneetlath** [comment] 2024-01-02 18:27
What do y'all think @thesahindia @esh-g?

**Comment by esh-g** [comment] 2024-01-04 12:36
@puneetlath The issue @cead22 mentioned seems to be the second option in my proposal! We are generating the `transactionThread` optimistically on the front-end.
<img width="810" alt="Screenshot 2024-01-04 at 6 03 24 PM" src="https://github.com/Expensify/App/assets/77237602/457f50c1-75cd-46b7-bc90-d2136765ea70">

So we also need to set the `childReportID` to the `transactionThreadReportID` on the front-end which I think should be handled in that issue...

And as for the second issue, that the composer is still active even when report is loading, should be the only thing left to handle here!

**Comment by trjExpensify** [comment] 2024-01-08 11:44
@puneetlath you good with this?

**Comment by trjExpensify** [comment] 2024-01-12 00:27
So @esh-g are we saying we still need this issue to tackle the below:

>And as for the second issue, that the composer is still active even when report is loading, should be the only thing left to handle here!

And further, we should still hold it on https://github.com/Expensify/App/pull/32461/files?

**Comment by puneetlath** [comment] 2024-01-12 21:27
I think yes, let's put it on hold for that and then re-visit after that is done.

**Comment by trjExpensify** [comment] 2024-01-15 10:17
Sounds good, done!

**Comment by trjExpensify** [comment] 2024-01-29 20:09
Still held.

**Comment by puneetlath** [comment] 2024-02-07 17:35
Still on hold.

**Comment by trjExpensify** [comment] 2024-02-19 11:53
@puneetlath @cdanwards #32461 has been closed. Should we be held on a new PR now, is it this https://github.com/Expensify/App/pull/35449?

**Comment by cead22** [comment] 2024-02-19 18:42
Yes, I updated the title

**Comment by puneetlath** [comment] 2024-02-28 14:52
Looks like that PR was merged. Does that mean we can take this off hold?

**Comment by trjExpensify** [comment] 2024-02-28 21:52
Yup! I think it's #vip-vsb this one as threads related, so popping it there while we look into it again. 

Can anyone reproduce? I tried on prod and I was able to get a slow enough load of an expense thread to repro it, but on staging I haven't been able to run into a slow enough load to be able to. CC: @esh-g

**Comment by esh-g** [comment] 2024-03-05 12:26
@trjExpensify The problem still is present. It just happens if you have really slow internet or you are offline and then go online.


https://github.com/Expensify/App/assets/77237602/3b2557ed-5b1a-4350-a6e3-6b612fd13164

**Comment by esh-g** [comment] 2024-03-05 12:42
# Proposal

## What is the root cause of the problem?
The root cause is that when creating a money request offline, we generate an optimistic transaction report but when the money request is actually created after going online, the optimistic report is no longer relevant as the report that backend returns has an entirely new id and basically the optimistic report never gets created on the backend, thus we see the composer disappear when we go online as it generates an `Auth OpenReport` error.

https://github.com/Expensify/App/assets/77237602/7120efa4-0938-44c0-a23b-cc9dfdf7a154


I think this was done as a compromise to have an optimistic report to show until it was created on the backend. But this leads to issues like messages sent on the optimistic report being deleted as well.

## What changes should be made to fix this?
We should disable the composer for the optimistic transaction report because if the optimistic report never exists on the backend, it should never be able to be written to by the user. Therefore, we can hide the composer if there is a pending create action on the money report the same way we do if there is a pending delete action here:
https://github.com/Expensify/App/blob/9411a08168d53df44a957fd8bb86fd9a363b25b4/src/libs/ReportUtils.ts#L4518-L4521
<img width="318" alt="Screenshot 2024-03-05 at 6 11 49 PM" src="https://github.com/Expensify/App/assets/77237602/0aa55980-dc4e-403d-801f-b98fa67fd46b">

This would disable the composer for the optimistic report just like it does when we go online so that the user isn't sending messages to a report that will never have any existence on the backend.

**Comment by esh-g** [comment] 2024-03-05 12:43
The problem I think has changed a little from it's root cause... So I think a new solution as proposed above is needed.

**Comment by trjExpensify** [comment] 2024-03-07 12:13
Oh wow, so the composer disappears completely as well? 

>We should disable the composer for the optimistic transaction report because if the optimistic report never exists on the backend, it should never be able to be written to by the user.

I don't really like the sound of that. To the user, they should be able to comment on reports when offline with no difference.

**Comment by cead22** [comment] 2024-03-08 01:23
The childReportID issue should get fixed by this PR https://github.com/Expensify/App/pull/37232. Once that's fixed, will we still be saving drafts on reportID 0?

**Comment by trjExpensify** [comment] 2024-03-11 10:53
Ah, at that point the draft message nor the composer would disappear? 🤔 Should we wait for that PR to be done and retest this then?

**Comment by trjExpensify** [comment] 2024-03-14 00:55
Hit prod 5 hours ago. @esh-g we're ready for a re-test.

**Comment by trjExpensify** [comment] 2024-03-18 10:35
Bump, @esh-g. If you think this issue is still present, do let us know! In the meantime, I'm going to add the retest weekly label for Applause.

**Comment by trjExpensify** [comment] 2024-03-25 11:22
Awaiting the Applause retest.

**Comment by mvtglobally** [comment] 2024-03-28 04:28
Issue not reproducible during KI retests. (First week)

**Comment by puneetlath** [comment] 2024-03-28 14:55
Sounds like this is no longer happening so I'm going to close. Feel free to let me know if I'm mistaken!

**Closed by puneetlath** 2024-03-28 14:55 UTC
Labels: Engineering, Daily, Internal, Overdue, Bug, retest-weekly
