### ISSUE TITLE
Web- [Deleted message] thread is created if account B replies in thread for the welcome message before the welcome message shows up on account A

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#22255] opened 2023-07-05 10:50 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
Prerequisite: Go to developer tools and throttle the network to simulate slow network
1. Create two new accounts (account A and account B)
2. Copy account B's email
3. Go to account A and create a workspace
4. Go to announce room and click on header
5. Click on settings > welcome message > type any welcome message
6. Go to settings > workspace > members > invite
7. Paste account B's email and click on next and invite
8. Go to account B before the welcome message shows up on account A's announce room and hover over the welcome message and click on reply in thread
9. Type something and send in the thread
10. Go to account A and observe the LHN

## Expected Result:
 [Deleted message] thread should not be created on the LHN

## Actual Result:
[Deleted message] thread gets created if user replies in thread on the welcome message before it shows up on account A's announce room.

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [x] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 1.3.36-2
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/93399543/46917364-9bb5-4922-8638-e2cc4ebeb2a4

https://github.com/Expensify/App/assets/93399543/e3f63d74-9ab7-4bf3-8a46-e77a15dd576c

**Expensify/Expensify Issue URL:**
**Issue reported by:**  @Nathan-Mulugeta
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1688453281149029

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by sakluger** [comment] 2023-07-10 20:47
I think this has basically the same root cause as https://github.com/Expensify/App/issues/21156. Once we fix that other issue, the workspace admin will no longer have visibility on welcome messages to other users, so this issue should no longer occur. Closing this one out.

**Closed by sakluger** 2023-07-10 20:47 UTC
Labels: Daily, Overdue, Bug

**Comment by Nathan-Mulugeta** [comment] 2023-07-13 07:28
Hey @sakluger I think [#21156](https://github.com/Expensify/App/issues/21156)  has been closed as being not a bug, so what does that leave this issue with?
