### ISSUE TITLE
[$500] Desktop deploys always give a "false negative"

### ISSUE THREAD

**Issue by m-natarajan** [Expensify/App#35629] opened 2024-02-02 04:13 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:**
**Reproducible in staging?:** needs reproduction
**Reproducible in production?:** needs reproduction
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** @roryabraham 
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1706831827428559

## Action Performed:
*Prerequisite:* You have the desktop app and there's an update available, but you haven't been notified of it yet. Note that you can download a `.dmg` for an older app version from the [GitHub Release](https://github.com/Expensify/App/releases). Then:
1. Go to the `New Expensify` menu, and click `Check for updates`

## Expected Result: 
A modal pops up that says an update is available. You can click on a button in the modal to update the app.

## Actual Result: 
A modal pops up that says you're up to date. A few moments later, you receive a notification saying that an update is available. You can click on the notification to update.

## Workaround:
unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [ ] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~0153d36244ff9ed9b3</li>
        <li>Upwork Job ID: 1813344570140106347</li>
        <li>Last Price Increase: 2024-09-06</li>
    </ul>
</details>

**Comment by laurenreidexpensify** [comment] 2024-02-08 10:56
Waiting for weekly retesting for reproduction

**Comment by laurenreidexpensify** [comment] 2024-02-13 12:06
Waiting for retesting

**Comment by laurenreidexpensify** [comment] 2024-02-16 17:07
Asking in Slack https://expensify.slack.com/archives/C9YU7BX5M/p1708103233932099 if this was confirmed as reprocudible

**Comment by laurenreidexpensify** [comment] 2024-02-19 17:31
For Testing h/t @roryabraham - 

> You can reproduce it on-demand by installing an older version of the desktop app. I realize that we don't leave build artifacts on the GitHub Releases, which makes it harder to get older app versions. Going to make an issue for that

**Comment by laurenreidexpensify** [comment] 2024-02-22 10:19
Waiting for reproduction

**Comment by laurenreidexpensify** [comment] 2024-02-22 12:21
Waiting for reproduction

**Comment by roryabraham** [comment] 2024-02-24 17:07
@laurenreidexpensify this new feature idea would make this much easier to test: https://github.com/Expensify/App/issues/36758

**Comment by mvtglobally** [comment] 2024-02-27 16:12
QA is unable to verify this to confirm if issue is reproducible or no. This needs a build pushed and checked which is a bit complex to catch in the right moment

**Comment by roryabraham** [comment] 2024-02-28 01:05
ok, we'll put this on HOLD for https://github.com/Expensify/App/issues/36758, which will make this easier to test.

It's also necessary for testing https://github.com/Expensify/App/issues/37349, so I think it needs to be prioiritized soon

**Comment by laurenreidexpensify** [comment] 2024-03-04 06:17
Still held on #36758

**Comment by mvtglobally** [comment] 2024-03-05 04:56
It seems as this Issue is reproducible during KI retests. 
https://github.com/Expensify/App/assets/43995119/b47d33f4-c9b6-4df9-9caf-8328dc2801d6

**Comment by laurenreidexpensify** [comment] 2024-03-11 11:00
Still held on https://github.com/Expensify/App/issues/36758

**Comment by laurenreidexpensify** [comment] 2024-03-21 17:39
Still held on https://github.com/Expensify/App/issues/36758

**Comment by laurenreidexpensify** [comment] 2024-04-02 11:56
Still held on https://github.com/Expensify/App/issues/36758

**Comment by laurenreidexpensify** [comment] 2024-04-08 11:28
Still held on https://github.com/Expensify/App/issues/36758

**Comment by laurenreidexpensify** [comment] 2024-04-22 12:36
Still held on https://github.com/Expensify/App/issues/36758

**Comment by laurenreidexpensify** [comment] 2024-04-29 11:00
Still held on https://github.com/Expensify/App/issues/36758

**Comment by laurenreidexpensify** [comment] 2024-05-14 10:21
Still held on https://github.com/Expensify/App/issues/36758

**Comment by laurenreidexpensify** [comment] 2024-05-20 12:37
Still held on https://github.com/Expensify/App/issues/36758

**Comment by laurenreidexpensify** [comment] 2024-05-28 09:48
Still held on https://github.com/Expensify/App/issues/36758

**Comment by laurenreidexpensify** [comment] 2024-06-07 13:09
Still held on https://github.com/Expensify/App/issues/36758

**Comment by laurenreidexpensify** [comment] 2024-06-10 11:00
Still held on https://github.com/Expensify/App/issues/36758

**Comment by laurenreidexpensify** [comment] 2024-06-18 10:57
@kadiealexander reassigning this one while I am on parental leave. TLDR is that you just need to check in every so often and confirm that https://github.com/Expensify/App/issues/36758 is still in progress. 

It also might be worth checking in with @roryabraham if we still require this to be open, or if it's worth closing at this point. Thanks!

**Comment by kadiealexander** [comment] 2024-06-24 01:09
@roryabraham do you think this needs to stay open?

**Comment by roryabraham** [comment] 2024-07-15 16:48
I think so. I created https://github.com/Expensify/App/issues/36758 on Friday to start making progress on this.

**Comment by roryabraham** [comment] 2024-07-16 22:46
Taking this off HOLD since https://github.com/Expensify/App/issues/36758 is done

**Comment by hungvu193** [comment] 2024-07-19 03:07
Waiting for proposals.

**Comment by hungvu193** [comment] 2024-07-23 02:51
Still waiting for proposals

**Comment by roryabraham** [comment] 2024-07-27 07:33
There are some instructions on [testing electron auto-update](https://github.com/Expensify/App/blob/59a07d6b8ba20b13cdaf5e3dc388a8bc8f33f61e/desktop/README.md#testing-electron-auto-update), though I'm not sure how up-to-date they are. They also require a paid apple developer account.

**Comment by hungvu193** [comment] 2024-07-30 02:31
> There are some instructions on [testing electron auto-update](https://github.com/Expensify/App/blob/59a07d6b8ba20b13cdaf5e3dc388a8bc8f33f61e/desktop/README.md#testing-electron-auto-update), though I'm not sure how up-to-date they are. They also require a paid apple developer account.

Can you ask someone internal if these docs are up to date, I have a paid apple account so I can give it a try

**Comment by roryabraham** [comment] 2024-07-31 19:44
> Can you ask someone internal if these docs are up to date

I don't think anyone will know the answer. Best way to find out is to try

**Comment by hungvu193** [comment] 2024-08-02 02:19
Cool. I'm gonna try it this weekend.

**Comment by hungvu193** [comment] 2024-08-06 02:33
Not overdue. Still trying to setup Minio

**Comment by hungvu193** [comment] 2024-08-08 02:33
Little update, I can setup Minio locally, but when I tried to push a build to Min.IO, I got this error below even though I had `Developer ID Application` certificate installed on my laptop.
 
<img width="1046" alt="Screenshot 2024-08-08 at 09 30 55" src="https://github.com/user-attachments/assets/adc91bcb-be41-490d-9c66-eec22d63ca89">

**Comment by hungvu193** [comment] 2024-08-16 03:07
Still no luck. This probably needs an internal engineer.

**Comment by hungvu193** [comment] 2024-08-20 02:00
Same here

> Still no luck. This probably needs an internal engineer.

**Comment by hungvu193** [comment] 2024-08-24 01:20
No update

**Comment by kadiealexander** [comment] 2024-08-28 06:28
@roryabraham do you think this is still an issue?

**Comment by kadiealexander** [comment] 2024-08-28 06:29
@roryabraham do you think this is still an issue?

**Comment by roryabraham** [comment] 2024-08-29 04:56
well now we can have Applause retest this one. requested retest: https://expensify.slack.com/archives/C9YU7BX5M/p1724907395238649

also, don't think it needs to be daily

**Comment by roryabraham** [comment] 2024-09-04 17:58
bumped applause in slack

**Comment by mvtglobally** [comment] 2024-09-09 04:05
Issue not reproducible during KI retests. (First week)

**Comment by kadiealexander** [comment] 2024-09-09 07:39
@roryabraham should we close this one?

**Comment by roryabraham** [comment] 2024-09-09 22:07
Yep, let's close it out since it's no longer reproducible

**Closed by roryabraham** 2024-09-09 22:07 UTC
Labels: External, Engineering, Weekly, Help Wanted, Bug
