### ISSUE TITLE
[$1000] Assigning Task - Blank Detail Page Appears After Assigning Tasks, but Content Displays Properly When URL is Copied and Pasted

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#24387] opened 2023-08-10 19:37 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Click on the plus sign, then choose "Assign Tasks"
2. Add a title, assignee, share location, and confirm the tasks
3. Click on the header and observe the appearance of a blank detail page on the right side
4. Copy the URL and paste it into another tab
5. Notice that the copied URL correctly displays the email of the assignee with a hidden subtitle

## Expected Result:
After assigning the task and clicking on the header, the detail page should display the assignee's email with a hidden subtitle. without copy and paste the URL in new tabs

## Actual Result:
Clicking on the header after assigning tasks results in a blank detail page being displayed, which is unexpected. However, when copying the URL and pasting it into another tab, the detail page correctly shows the email of the assignee with a hidden subtitle. This inconsistency can be confusing for users

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [ ] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 1.3.52.5

**Reproducible in staging?:** Y

**Reproducible in production?:** Y

**If this was caught during regression testing, add the test name, ID and link from TestRail:**

**Email or phone of affected tester (no customers):**

**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/78819774/b2951695-5288-46e8-af49-6df26e6233b2

https://github.com/Expensify/App/assets/78819774/5ae469a3-f03c-415a-9f2e-ebe8cd1e4295

**Expensify/Expensify Issue URL:**

**Issue reported by:** @tewodrosGirmaA

**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1691135424057809

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01a5a2ed6e94d1f50e</li>
        <li>Upwork Job ID: 1696694563815759872</li>
        <li>Last Price Increase: 2023-08-30</li>
    </ul>
</details>

**Comment by Pluto0104** [comment] 2023-08-11 06:06
## Proposal
### Please re-state the problem that we are trying to solve in this issue.
Clicking on the header after assigning tasks results in a blank detail page being displayed, which is unexpected. However, when changing another tab, the detail page correctly shows the email of the assignee with a hidden subtitle.

### What is the root cause of that problem?
It is possible that we may have the empty `participantAccountIDs` array yet in Onyx yet e.g. we navigated to a URL for an accessible report that is not stored locally yet.

### What changes do you think we should make in order to solve the problem?
If `props.report.participantAccountIDs` is not empty, then the report has been stored locally and nothing more needs to be done. If it's empty, then we need to fetch the report from the API.

For example:
```
useEffect(() => {
    if ((participantAccountIDs && participantAccountIDs.length > 0) || !reportID || !managerID) {
        return;
    }
    Report.openReport(reportID);
}, [participantAccountIDs, reportID, managerID]);
```

### What alternative solutions did you explore? (Optional)
N/A

### Result

https://github.com/Expensify/App/assets/136573674/29b29a9f-0459-4c55-896f-cc05aa736097

**Comment by StevenKKC** [comment] 2023-08-11 06:36
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
Blank Detail Page Appears After Assigning Tasks, but Content Displays Properly When URL is Copied and Pasted.

### What is the root cause of that problem?
If we create a task, `Task.createTaskAndNavigate` is called, and in this function generates the task report.
https://github.com/Expensify/App/blob/dd0d98fa6868bba60e81bfdf66e5cdf7d2adaa37/src/libs/actions/Task.js#L47-L49
But in `ReportUtils.buildOptimisticTaskReport`, does not set the task report's `participantAccountIDs`.
https://github.com/Expensify/App/blob/dd0d98fa6868bba60e81bfdf66e5cdf7d2adaa37/src/libs/ReportUtils.js#L2205-L2217
App sends `CreateTask` API and navigates to the task report.
But `CreateTask` API returns the task report that has not `participantAccountIDs` field.

![Screenshot 2023-08-11 023333](https://github.com/Expensify/App/assets/131836113/b9faf087-01aa-4f53-8387-41f858727e2e)

If we click the task header, `ReportUtils.navigateToDetailsPage` is called, and in this function, we navigates to the pariticipant page, since report's `participantAccountIDs` is empty.
https://github.com/Expensify/App/blob/dd0d98fa6868bba60e81bfdf66e5cdf7d2adaa37/src/libs/ReportUtils.js#L1451
Therefore the blank detail page is displayed.

If url is copied and pasted, `OpenReport` API is called again, and in this time, `OpenReport` returns non-empty `participantAccountIDs`, so navigates to the task assignee profile page.
So content displays properly.

### What changes do you think we should make in order to solve the problem?
We can set the optimistic task report's `participantAccountIDs` to `assigneeAccountID` if task assignee is selected.
```js
    participantAccountIDs: assigneeAccountID !== 0 ? [assigneeAccountID] : [],
```
### What alternative solutions did you explore? (Optional)
None.

**Comment by mallenexpensify** [comment] 2023-08-23 15:50
@tewodrosGirmaA is this an example of the site not updating dynamically?

**Comment by mallenexpensify** [comment] 2023-08-30 01:22
@jjcoffee , can you review the above and provide thoughts/feedback.  I'm not an engineer so I'm unsure about the specifics of 'updating dynamically'.   It seems like the details section populates at some point in the future but not immediately. Thx

**Comment by tewodrosGirmaA** [comment] 2023-08-30 14:39
Hello@jjcoffee , this issue occurs when we try to add a new email that is not in our contact list. However, in the latest build, we are unable to add new emails to both assignee and share somewhere. This issue has been resolved with the recent update, which includes several changes. Previously, adding a new email to share somewhere caused this problem, but now it's not possible to add new emails to share somewhere or assignee, and as a result, this issue has been resolved with the fix. Thank you for asking

**Comment by jjcoffee** [comment] 2023-08-30 14:41
@tewodrosGirmaA Thanks for the details, that's really helpful! @mallenexpensify I think we can close this out.

**Comment by mallenexpensify** [comment] 2023-09-05 00:32
Thanks @jjcoffee and @tewodrosGirmaA , closing!

@tewodrosGirmaA if you can find the PR that fixed this issue then show that your bug report came before the associated bug report for the PR, you'd be due compensation.  Here's the date of your report

<img width="411" alt="image" src="https://github.com/Expensify/App/assets/22508304/be73ca8c-ef2d-4e0f-a0bc-ba8fe87d71a8">

**Closed by mallenexpensify** 2023-09-05 00:32 UTC
Labels: External, Engineering, Daily, Help Wanted, Overdue, Bug

**Comment by tewodrosGirmaA** [comment] 2023-09-16 09:21
Hello @mallenexpensify, I tried my best, but I am not able to find the PR, Thank you
