### ISSUE TITLE
Save button is overlapped in mWeb Safari

### ISSUE THREAD

**Issue by kavimuru** [Expensify/App#23331] opened 2023-07-21 03:36 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Login with any account.
2. Go to settings => security => change password, swipe from left to right to go back.
3. Go to 2FA page, swipe from left to right to go back.
4. Repeat step 2,3 few times.
5. Notice that Save button is overlapped.
## Expected Result: 
Save button should be overlapped
## Actual Result: 
Save button is overlapped.

## Workaround:
Can the user still use Expensify without this being fixed? Have you informed them of the workaround?

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [x] iOS / Safari
- [ ] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 1.3..42-25
**Reproducible in staging?:** needs reproduction , applause unable to reproduce
**Reproducible in production?:** needs reproduction
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/43996225/b762e33e-210f-4fbd-9ea7-ff65a67fddff

**Expensify/Expensify Issue URL:**
**Issue reported by:** @hungvu193 
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1689780260665849

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by isabelastisser** [comment] 2023-07-24 19:07
I believe this is an expected result on the web. I can't reproduce it on the app. Closing!

**Closed by isabelastisser** 2023-07-24 19:07 UTC
Labels: Daily, Needs Reproduction, Overdue, Bug
