### ISSUE TITLE
[LOW] [Splits] [$500] Mweb/Chrome - Scan request created using corrupt pdf displays incorrect error message

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#34032] opened 2024-01-05 15:33 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.22
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** Applause - Internal Team
**Slack conversation:**

**Issue found when executing PR** https://github.com/Expensify/App/pull/32562
## Action Performed:
1. Go to https://staging.new.expensify.com/
2. Tap fab --- Request money ---Scan
3. Upload a corrupt pdf
4. Tap request
5. Note no error displayed for uploading corrupt pdf
6. Tap on created scan request
7. Enter all fields required

## Expected Result:
Scan request created using corrupt pdf must display correct error message

## Actual Result:
Scan request created using corrupt pdf displays incorrect error message " unexpected error while making request"

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [x] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [ ] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details> 

https://github.com/Expensify/App/assets/78819774/ced0a150-a83f-4cdf-b11f-71cce6e66f35

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~019826bd315885912e</li>
        <li>Upwork Job ID: 1743294656335773696</li>
        <li>Last Price Increase: 2024-04-16</li>
    </ul>
</details>

**Comment by codebycarlos** [comment] 2024-01-05 16:26
I can't replicate this on my android mobile (I get the error post upload as expected). Could you please share the file?

I believe the receipt is validated here.

https://github.com/Expensify/App/blob/393f2bec9a6a1d9f3affa18207e6b735274d1c2f/src/pages/iou/ReceiptSelector/index.js#L102-L120

It relies entirely on the metadata, without checking content. So differences in how the mobile operating system interprets the metadata could lead to these corrupted PDFs getting through..

**Comment by FlorianWueest** [comment] 2024-01-05 16:40
## Proposal

### Please re-state the problem that we are trying to solve in this issue: 
Corrupt pdfs can be uploaded as a receipt - and the error message is generic. 

### What is the root cause of that problem?
There's no specific pdf checking logic to determine whether the file is corrupted. Currently, we only check for size parameters and required extensions: 

We check it here: 
https://github.com/Expensify/App/blob/fa533cea7d1b3c177ef698a4de6f90fe4a5c3362/src/pages/iou/ReceiptSelector/index.js#L102-L120

With those parameters:
https://github.com/Expensify/App/blob/fa533cea7d1b3c177ef698a4de6f90fe4a5c3362/src/CONST.ts#L51-L60

### What changes do you think we should make in order to solve the problem?
Either install front-end checks (render the pdf using 'react-pdf' and 'react-native-pdf'), to check for file corruption. Or adjust the `genericEditFailureMessage` to be more meaningful in the case of corrupted pdf file.

**Comment by samilabud** [comment] 2024-01-06 20:03
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
Mweb/Chrome - Scan request created using corrupt pdf displays incorrect error message

### What is the root cause of that problem?
We are not checking if the PDF file is corrupted/valid file before uploading in the next components:
https://github.com/Expensify/App/blob/main/src/pages/iou/request/step/IOURequestStepScan/index.js
https://github.com/Expensify/App/blob/main/src/pages/iou/request/step/IOURequestStepScan/index.native.js

### What changes do you think we should make in order to solve the problem?
We should validate the PDF before uploading the file in the previously mentioned files and show an error message if PDF is corrupted.

Based on our current PDF libraries:

https://github.com/Expensify/App/blob/0c351a4534f0bfb8278f2fa9b8c0a10187b6c8bb/src/components/PDFView/index.js#L6

Create a function to check the integrity of the file:
```
import {pdfjs} from 'react-pdf/dist/esm/entry.webpack';

const checkPdfIntegrity = async (file, fileExtension) =>
    new Promise((resolve, reject) => {
        if (fileExtension !== CONST.IOU.FILE_TYPES.PDF) {
            return resolve({success: true});
        }
        const fileReader = new FileReader();
        fileReader.onload = async (event) => {
            const arrayBuffer = event.target && event.target.result;

            if (arrayBuffer) {
                try {
                    const loadingTask = pdfjs.getDocument(event.target.result);
                    const pdfDocument = await loadingTask.promise;
                    resolve({success: true, document: pdfDocument});
                } catch (error) {
                    resolve({success: false});
                }
            }
        };

        fileReader.onerror = (error) => {
            // eslint-disable-next-line prefer-promise-reject-errors
            reject({success: false, error});
        };

        fileReader.readAsArrayBuffer(file);
    });
```

Then inside of validateReceipt functions:

```
 const isValidPDF = await checkPdfIntegrity(file, fileExtension);

        if (!isValidPDF.success) {
            setUploadReceiptError(true, 'attachmentPicker.attachmentCorruptedError', 'attachmentPicker.pdfCorruptedError');
            return false;
        }
```
Also, we should add this last strings to languages files like: https://github.com/Expensify/App/blob/main/src/languages/en.ts
eg:
```
attachmentPicker: {
      .
      .
      .
        attachmentCorruptedError: 'Attachment is corrupted',
        pdfCorruptedError: 'The PDF file is corrupted',
    },
```
**This could be the result:**

https://github.com/Expensify/App/assets/5216036/66335445-2983-43c0-b3e2-21ab24184b25

**Comment by Christinadobrzyn** [comment] 2024-01-07 22:55
Hey @situchan could you check if this [GH](https://github.com/Expensify/App/issues/34068) is a duplicate - thanks!

**Comment by situchan** [comment] 2024-01-07 23:16
> Hey @situchan could you check if this [GH](https://github.com/Expensify/App/issues/34068) is a duplicate - thanks!

yes, it's a dupe

**Comment by sonialiap** [comment] 2024-01-10 09:46
@situchan what do you think of the above proposals?

**Comment by situchan** [comment] 2024-01-12 16:01
proposals in review

**Comment by sonialiap** [comment] 2024-01-15 11:46
@situchan any update on your review? :)

**Comment by situchan** [comment] 2024-01-18 11:17
Everyone proposed solution for web only. This happens on native as well.
Still awaiting proposals.


https://github.com/Expensify/App/assets/108292595/69f40913-c2f3-4eba-bc38-2e3a1171c90c

**Comment by situchan** [comment] 2024-01-18 11:18
@sonialiap can we clarify the expected behavior here?

Should we prevent uploading corrupted pdf in advance?

**Comment by sonialiap** [comment] 2024-01-18 13:04
Can we identify a corrupted pdf when the user attempts to upload it? If yes, I think that would be the best time to flag it so that the user doesn't have to wait for us to process the pdf and then tell them it didn't work.

**Comment by sonialiap** [comment] 2024-01-23 12:34
@situchan what do you think of the updated proposal? https://github.com/Expensify/App/issues/34032#issuecomment-1898598514

**Comment by sourcecodedeveloper** [comment] 2024-01-23 12:43
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
Uploading corrupt pdf does not show any error message. The scan request does not display any error message and tries to process corrupt pdf.
### What is the root cause of that problem?
When the user uploads corrupt pdf, the attachment should be flagged and error message display before 

### What changes do you think we should make in order to solve the problem?
Add onError handler for AttachmentPicker for web and native.

https://github.com/Expensify/App/blob/0bdbfbbc5ffa8a247f348abe777819eb44b8db1a/src/components/AttachmentPicker/index.js#L78
https://github.com/Expensify/App/blob/0bdbfbbc5ffa8a247f348abe777819eb44b8db1a/src/components/AttachmentPicker/index.native.js#L209

const onError = useRef();

For web, pdfjs is able to test load pdf and if corrupted pdf is loaded, the onError ref can call onError handler.
```
const {fileExtension} = FileUtils.splitExtensionFromFileName(lodashGet(file, 'name', ''));
if(fileExtension.toLowerCase() === "pdf" && onError.current){
    pdfjs.getDocument(file.uri).promise.then((result)=>{
        onPicked.current(file);
    }).catch((e)=>{
        if(onError.current)
        {
            onError.current(e);
        }
    })
}
else
{
    onPicked.current(file);
}
```
For native, pdfjs is not available so need to use PDF component from react-native-pdf for testing if the pdf is corrupted or valid.

For Native:

import PDF from 'react-native-pdf';
Add refs 
```
const onError = useRef();
```

Add onError handler to OpenPicker
https://github.com/Expensify/App/blob/0bdbfbbc5ffa8a247f348abe777819eb44b8db1a/src/components/AttachmentPicker/index.native.js#L209
```
const open = (onPickedHandler, onCanceledHandler = () => {}, onErrorHandler) => {
    completeAttachmentSelection.current = onPickedHandler;
    onError.current = onErrorHandler;
    onCanceled.current = onCanceledHandler;
    setIsVisible(true);
};
```
The react-native-pdf componet can hidden so the PDF component is not visible to the user.
```
<View style={styles.invisible}>
    <PDF
        source={{ uri: pdfUrl }}
        onError={(err) => {
            if(onError.current)
            {
                onError.current(err);
            }
        }}
        onLoadComplete={(e) => {
            getDataForUpload(fileDataRef.current)
                .then((result) => {
                    completeAttachmentSelection.current(result);
                })
                .catch((error) => {
                    showGeneralAlert(error.message);
                    throw error;
                });
        }}
    >
    </PDF>
</View>
```

### What alternative solutions did you explore? (Optional)

**Comment by sourcecodedeveloper** [comment] 2024-01-23 13:01
@situchan pdfjs can only be used for web, for native need to use 'react-native-pdf'. [Proposal](https://github.com/Expensify/App/issues/34032#issuecomment-1905981516) ready for review.

**Comment by sourcecodedeveloper** [comment] 2024-01-23 14:34
@situchan I have attached [proposal](https://github.com/Expensify/App/issues/34032#issuecomment-1905981516) which also resolves https://github.com/Expensify/App/issues/34322. The error message for corrupted pdf should be shown early in the AttachmentPicker rather than in the onPicked handler setReceiptAndNavigate. pdfjs can only be used for web, for native need to use 'react-native-pdf'.

**Comment by situchan** [comment] 2024-01-26 16:09
Thanks. I will evaluate them. Eta early next week

**Comment by situchan** [comment] 2024-01-29 14:39
Still evaluating

**Comment by sonialiap** [comment] 2024-01-31 17:15
@situchan checking in on the proposals, how are they looking?

**Comment by situchan** [comment] 2024-02-07 15:13
Still discussing solutions

**Comment by sourcecodedeveloper** [comment] 2024-02-07 16:53
@situchan I can try to summarize the approach taken in [proposal](https://github.com/Expensify/App/issues/34032#issuecomment-1905981516) and then please ask which area of the proposal is unclear. 
Instead of using setReceiptAndNavigate and relying on validateReceipt function, I have would be adding an onError handler to openPicker. Using onError handler allows to catch corrupt pdf as early as the user selected the corrupt pdf in attachmentpicker.
https://github.com/Expensify/App/blob/0bdbfbbc5ffa8a247f348abe777819eb44b8db1a/src/components/AttachmentPicker/index.js#L78

The openPicker already has handler for onPicked and onCancelled. I would be adding an onError handler for handling corrupt pdfs. The onError handler approach applies to both web and native and I have provide poc videos to demonstrate.
The approach is to notify the user early enough if the pdf is corrupt. The ideal point would in the onChange event handler of AttachmentPicker, when the user picks the pdf.
https://github.com/Expensify/App/blob/0bdbfbbc5ffa8a247f348abe777819eb44b8db1a/src/components/AttachmentPicker/index.js#L39
```
const {fileExtension} = FileUtils.splitExtensionFromFileName(lodashGet(file, 'name', ''));
if(fileExtension.toLowerCase() === "pdf" && onError.current){
    pdfjs.getDocument(file.uri).promise.then((result)=>{
        onPicked.current(file);
    }).catch((e)=>{
        if(onError.current)
        {
            onError.current(e);
        }
    })
}
else
{
    onPicked.current(file);
}
```

**Comment by situchan** [comment] 2024-02-09 18:49
Thanks. I will provide feedback on Monday

**Comment by situchan** [comment] 2024-02-13 13:32
@ishpaul777 I tested your solution but I am always getting this error even if real PDF

`Error: Setting up fake worker failed: "Cannot load script at: https://dev.new.expensify.com:8082/main-0b8622007d0da8b91730.bundle.worker.js".
    at eval (pdf.js:1907:36)`

**Comment by sonialiap** [comment] 2024-02-15 22:06
Still looking for proposals

**Comment by situchan** [comment] 2024-02-15 22:48
sure. I will provide feedback asap

**Comment by situchan** [comment] 2024-02-19 15:20
evaluating latest proposal

**Comment by sonialiap** [comment] 2024-02-21 20:55
@situchan what is your opinion about the latest proposal?

**Comment by sonialiap** [comment] 2024-02-26 12:38
@situchan bumping your review of the proposals

**Comment by situchan** [comment] 2024-02-26 16:20
@ishpaul777 thanks for the demo.
Web solution looks good but not native solution. I don't think we should apply that workaround.

**Comment by situchan** [comment] 2024-03-04 14:42
still awaiting proposals

**Comment by sonialiap** [comment] 2024-03-07 12:40
Moving it back to external

**Comment by sonialiap** [comment] 2024-03-12 11:30
Asking Callstack if they're like this issue https://expensify.slack.com/archives/C03UK30EA1Z/p1710242080342589

**Comment by kubabutkiewicz** [comment] 2024-03-13 12:24
Hi, I'm Jakub from Callstack - expert contributor group - and I would like to take a look at this issue.

**Comment by kubabutkiewicz** [comment] 2024-03-14 11:46
@sonialiap @lanitochka17 Is this bug still happening? 
I am trying to reproduce this and I am not getting any error at all. Maybe @lanitochka17 are you able to provide me a file which you were using?  

https://github.com/Expensify/App/assets/25230417/ad9d26a5-efea-4d58-8299-43729acca089

https://github.com/Expensify/App/assets/25230417/8ee89452-06c5-4b86-94e4-90dfbbef9add

**Comment by kubabutkiewicz** [comment] 2024-03-15 18:05
Hi @sonialiap I will be ooo next week, I left an update to the team about my research of this issue.

**Comment by TomaszFrackowiak** [comment] 2024-03-18 10:17
@sonialiap - Hey, would like you to know that @pac-guerreiro is taking over this issue, while @kubabutkiewicz ooo.

**Comment by sonialiap** [comment] 2024-03-19 11:03
Sounds good, thanks Tomasz

**Comment by sonialiap** [comment] 2024-03-26 18:36
@pac-guerreiro adding you as an assignee

**Comment by sonialiap** [comment] 2024-03-26 18:38
Actually, GH isn't letting me assign @pac-guerreiro. @TomaszFrackowiak ideas on why that is?

**Comment by arielgreen** [comment] 2024-03-27 02:30
@pac-guerreiro can you please comment on this issue so we can assign you?

@sonialiap it won't let you assign someone unless they've commented :)

**Comment by TomaszFrackowiak** [comment] 2024-03-27 10:40
@sonialiap Hey, @pac-guerreiro has invested in this issue and has some findings. He will pass them on to @kubabutkiewicz , who has returned from ooo and will continue working on this issue.

**Comment by mallenexpensify** [comment] 2024-04-01 16:25
@situchan is out OOO, reassigning a C+ via the auto-assigner for fairness.

**Comment by kubabutkiewicz** [comment] 2024-04-02 16:08
Hi, I have a working solution for web , desktop and android, tomorrow will work on iOS and when I have everything I will post a proposal 😄

**Comment by kubabutkiewicz** [comment] 2024-04-05 19:44
hi, I managed to get it also work on iOS, on Monday will prepare proposal 😄

**Comment by kubabutkiewicz** [comment] 2024-04-09 10:08
## Proposal

### Please re-state the problem that we are trying to solve in this issue.

When in money request -> scan, and uploading a pdf file which is corrupted we are allowing user to move through whole flow till we upload file on the backend. We would like to show error as soon as possible to not waste time of users.

### What is the root cause of that problem?

There is no logic implemented in the code for checking if pdfs are corrupted.

### What changes do you think we should make in order to solve the problem?

To accomplish this on the web and desktop we can use library called pdfjs which a web-standard for working with pdfs.
We can create a function isValidPdf in 

https://github.com/Expensify/App/blob/ce06355873778a69c78e40e0f33e4648f3462826/src/pages/iou/request/step/IOURequestStepScan/index.js#L178-L196which

```
    const isValidPdfFile = (file) =>
        new Promise((resolve) => {
            pdfjs
                .getDocument(file.uri || '')
                .promise.then(() => resolve(true))
                .catch(() => resolve(false));
        });
```
On the native side things are trickier because there is no standard with working with pdfs. After research I couldn't find and solution in react-native world so I decided to go with creating native modules. For android  code can look like this

```
 public static boolean isPdfCorrupted(String filePath) {
        try {
            // Read the content of the PDF file into a byte array
            File file = new File(filePath);
            byte[] buffer = new byte[(int) file.length()];
            FileInputStream fis = new FileInputStream(file);
            fis.read(buffer);
            fis.close();

            // Check if the PDF file starts with the "%PDF" header
            String pdfHeader = new String(buffer, 0, 4);
            return !pdfHeader.equals("%PDF");
        } catch (IOException e) {
            // Handle IO errors
            e.printStackTrace();
            return true; // Treat IO errors as corrupted PDF files
        }
    }

    @ReactMethod
    public void checkPdf(String name, Callback callback) {
        if (PdfUtils.isPdfCorrupted(name)) {
            // Handle the case where the PDF file is corrupted
            callback.invoke(false);
        } else {
            // Proceed with processing the PDF file
            // For example, display the PDF file to the user
            callback.invoke(true);
        }
    }
```

For iOS we don't need any external library we can create function like that


```
RCT_EXPORT_METHOD(checkPdf:(NSString *)fileurl callback: (RCTResponseSenderBlock)callback)
{
  NSURL *url = [NSURL URLWithString:fileurl];
  NSFileManager *fileManager = [NSFileManager defaultManager];
      NSData *ns = [NSData dataWithContentsOfURL:url];
      BOOL fileExists = [fileManager fileExistsAtPath:[url path]];
      BOOL isPDF = NO;
      if ([ns length] >= 1024) 
      {
          uint8_t pdfBytes[] = { 0x25, 0x50, 0x44, 0x46 };
          NSData *pdfHeader = [NSData dataWithBytes:pdfBytes length:4];
          NSRange range = [ns rangeOfData:pdfHeader options:NSDataSearchAnchored range:NSMakeRange(0, 1024)];
          if (range.length > 0)
          {
            callback(@[@YES]);
          }
          else
          {
            callback(@[@NO]);
          }
      }
}
```

And in our codebase use it here 

https://github.com/Expensify/App/blob/ce06355873778a69c78e40e0f33e4648f3462826/src/pages/iou/request/step/IOURequestStepScan/index.native.js#L166-L183

the code would look like that

```
 const validateReceipt = (file) =>
        new Promise((resolve) => {
            CheckPDFDocument.checkPdf(file.uri, (isCorrect) => {
                const {fileExtension} = FileUtils.splitExtensionFromFileName(lodashGet(file, 'name', ''));
                if (!isCorrect) {
                    Alert.alert(translate('attachmentPicker.wrongFileType'), translate('attachmentPicker.notAllowedExtension'));
                    resolve(false);
                }

                if (!CONST.API_ATTACHMENT_VALIDATIONS.ALLOWED_RECEIPT_EXTENSIONS.includes(fileExtension.toLowerCase())) {
                    Alert.alert(translate('attachmentPicker.wrongFileType'), translate('attachmentPicker.notAllowedExtension'));
                    resolve(false);
                }

                if (lodashGet(file, 'size', 0) > CONST.API_ATTACHMENT_VALIDATIONS.MAX_SIZE) {
                    Alert.alert(translate('attachmentPicker.attachmentTooLarge'), translate('attachmentPicker.sizeExceeded'));
                    resolve(false);
                }

                if (lodashGet(file, 'size', 0) < CONST.API_ATTACHMENT_VALIDATIONS.MIN_SIZE) {
                    Alert.alert(translate('attachmentPicker.attachmentTooSmall'), translate('attachmentPicker.sizeNotMet'));
                    resolve(false);
                }
                resolve(true);
            });
        });
```

### What alternative solutions did you explore? (Optional)
We can change a little bit a UI for the first step in the flow of adding scan while requesting a money and add preview of the document/image and use PDFView component and then if we cant display the preview of the pdf/image we would know that there is something wrong with the file

**Comment by rushatgabhane** [comment] 2024-04-09 16:07
@kubabutkiewicz 's proposal LGTM! 

The native code is really easy to read and understand, so I don't mind us creating a native module to check for valid PDFs

**Comment by rushatgabhane** [comment] 2024-04-09 16:07
🎀👀🎀

**Comment by luacmartins** [comment] 2024-04-09 16:55
@kubabutkiewicz I see that your proposal suggests using a lib for web and building our own code for ios/android. I'm pretty sure that if we go ahead with the new lib request, people are gonna veto it in favor of writing our own for web too. Could you explore writing our own method for web as well?

**Comment by kubabutkiewicz** [comment] 2024-04-10 07:41
@luacmartins actually this lib is already added to our project , so no need to add new one 😄 `pdfjs` is used in `react-pdf` and we can use it like that `import {pdfjs} from 'react-pdf';`

**Comment by luacmartins** [comment] 2024-04-10 20:51
Ah interesting. In that case the proposal looks good then.

**Comment by luacmartins** [comment] 2024-04-15 16:22
@kubabutkiewicz do you have an ETA for the PR?

**Comment by kubabutkiewicz** [comment] 2024-04-15 16:34
Yes, I think tomorrow will be ready, today was reviewed internally, I will make adjustments and when approved internally I will open to external review

**Comment by kubabutkiewicz** [comment] 2024-04-16 13:29
Hi I noticed on latest main that there is a bug that even when I am uploading pdf which is not corrupted I am getting error that file is corrupted and I think its related to this https://github.com/Expensify/App/pull/40162 PR

**Comment by rushatgabhane** [comment] 2024-04-18 21:40
> because of that I cant test newest changes

thank you. let's hold on https://github.com/Expensify/App/pull/40471#pullrequestreview-2009965278

**Comment by kubabutkiewicz** [comment] 2024-04-26 13:59
Hi, just wanted to inform that I will be OOO from 29.04 to 05.05.

**Comment by mvtglobally** [comment] 2024-05-01 13:59
Issue not reproducible during KI retests. (First week)

**Comment by luacmartins** [comment] 2024-05-01 14:43
Seems like https://github.com/Expensify/App/pull/40471#pullrequestreview-2009965278 may have fixed the issue. Gonna close it since it's no longer reproducible. Please reopen if this is still happening.

**Closed by luacmartins** 2024-05-01 14:43 UTC
Labels: Reviewing, External, Weekly, Help Wanted, Bug
