### ISSUE TITLE
[$1000] Manage members - Unable to add a new line in the invite message

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#22026] opened 2023-07-01 19:41 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Click on your avatar
2. Go to Workspaces tab
3. Select any workspace
4. Go to Members tab
5. Click Invite button
6. Select any user and click Next
7. Click on the Message input
8. Add new line

## Expected Result:
The user should have the ability to add a new line to the invite message.

## Actual Result:
The user cannot add a new line to the invite message.

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [x] iOS / Safari
- [x] MacOS / Chrome / Safari
- [x] MacOS / Desktop

**Version Number:** 1.3.35-5
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/93399543/eeb802f2-16ce-4b44-a6ff-a978b01bf988

https://github.com/Expensify/App/assets/93399543/7578fada-aa4c-4f1f-84a4-80064a3063d6

https://github.com/Expensify/App/assets/93399543/a20c8a01-1e17-4cc2-8f8e-580ac671446b

**Expensify/Expensify Issue URL:**
**Issue reported by:** @mejed-alkoutaini
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1688215985480649

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~017d2a659b9fc3186d</li>
        <li>Upwork Job ID: 1675657280951508992</li>
        <li>Last Price Increase: 2023-07-03</li>
    </ul>
</details>

**Comment by jliexpensify** [comment] 2023-07-03 00:05
No issues with adding a new line on Android (Pixel 3a) on Chrome, or on the Android app:

![image](https://github.com/Expensify/App/assets/30815269/cc871603-da83-4a21-bbe2-922041b232c9)

However, I can repro on MacOS Chrome - so it feels like it might be a desktop issue?

**Comment by s-alves10** [comment] 2023-07-03 00:16
Dupe of https://github.com/Expensify/App/issues/18419

**Comment by jliexpensify** [comment] 2023-07-03 00:27
Thanks you @s-alves10, guess I should have also searched `Enter`!

**Closed by jliexpensify** 2023-07-03 00:27 UTC
Labels: External, Daily, Help Wanted, Bug
