### ISSUE TITLE
[Awaiting Payment][$1000] Web - Workspace - Concierge opens and #admin with WS settings close after coming from OD

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#23566] opened 2023-07-25 17:02 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Issue found when executing PR** https://github.com/Expensify/App/pull/22619

## Action Performed:
1. Go to staging.expensify.com
2. Log in with a new Gmail account.
3. Go to Settings > Policies > Group > New Policy.

## Expected Result:
User is navigated to #admins page report and also to the workspace details on the right.

## Actual Result:
User is navigated to #admins page report and also to the workspace details on the right for a few seconds, then Concierge chat opens and workspace details panel closes.

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [x] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 1.3.45-3
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/93399543/57050d43-5976-4e33-8601-b5406cff36a9

**Expensify/Expensify Issue URL:**
**Issue reported by:** Applause - Internal Team
**Slack conversation:**

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01c12a52f499c32c9c</li>
        <li>Upwork Job ID: 1684298824142127104</li>
        <li>Last Price Increase: 2023-08-02</li>
    </ul>
</details>

**Comment by StefanNemeth** [comment] 2023-07-27 14:31
## Proposal

### Please re-state the problem that we are trying to solve in this issue.

When a new user is creating a new group on staging.expensify.com (Settings > Policies > Group), we want them to be redirected to #admins page report and open workspace details instead of just showing the Concierge chat.

### What is the root cause of that problem?

The root cause of the problem is that for new users the function `Welcome.show` displays the Workspace chat after logging in for the first time (which happens AFTER the admin chat is opened). This chat only exists briefly due to optimistic data when calling `Policy.createWorkspace`. When actually opening the workspace chat, the user is "redirected" to the Concierge chat as the chat does not exist.

### What changes do you think we should make in order to solve the problem?

Within the `Welcome.show` functionality we could check whether the `openOnAdminRoom` parameter is set and not open the workspace chat in that case.

### What alternative solutions did you explore? (Optional)
As an alternative we could check whether the user is already on a report page and not redirect if that is the case.

**Comment by StefanNemeth** [comment] 2023-07-27 14:33
Contributor details
Your Expensify account email: me@stefannemeth.com
Upwork Profile Link: https://www.upwork.com/freelancers/~018932ede2567df655

**Comment by sobitneupane** [comment] 2023-07-28 09:22
Thanks for the proposal @StefanNemeth. Can you please add permalinks to reference the code in our App. Also, more explanation of the solution and root cause analysis will be appreciated.

**Comment by StefanNemeth** [comment] 2023-07-28 09:37
@sobitneupane Sure, I updated the proposal. I hope it is reasonable.

**Comment by garrettmknight** [comment] 2023-07-31 10:37
@sobitneupane can you give the updated proposal a look when you get the chance?

**Comment by sobitneupane** [comment] 2023-08-02 07:27
Thanks for the update @StefanNemeth.

Were you able to reproduce the issue? I cannot reproduce the issue on my end.

https://github.com/Expensify/App/assets/25876548/2814e563-4412-4d5e-b1e2-4f6722a5c1b8

Did you test the solution of the issue?

**Comment by garrettmknight** [comment] 2023-08-02 08:56
@sobitneupane just tested and it's still happening. You've got to signup with a brand new gmail account on OD for it to happen.

**Comment by StefanNemeth** [comment] 2023-08-02 09:58
@sobitneupane I could reproduce the issue. It can only be reproduced when you create a new account on staging.expensify.com and follow the steps from above without ever going to new.staging.expensify.com so that `isFirstTimeNewExpensifyUser` is true.

I tested the solution and it worked.

**Comment by sobitneupane** [comment] 2023-08-02 17:24
Thanks for the updated @StefanNemeth.

> I tested the solution and it worked.

I am having some issues while trying to test it. When I open a new policy from staging.expensify.com, it redirects to staging.new.expensify.com. So, I was unable to test the local change. How did you test it?

**Comment by StefanNemeth** [comment] 2023-08-02 17:57
> I am having some issues while trying to test it. When I open a new policy from staging.expensify.com, it redirects to staging.new.expensify.com. So, I was unable to test the local change. How did you test it?

@sobitneupane I went to `staging.expensify.com` and just when it redirected me to `staging.new.expensify.com` I copied the URL, closed the tab and used the URL params for my local environment.

https://github.com/Expensify/App/assets/5003405/861e3d56-847a-494c-8c5c-51ef3d1f54c1

**Comment by StefanNemeth** [comment] 2023-08-04 15:14
> Oh It's so difficult to test it.

It's easier when you put this in your console within DevTools. It will override `window.open` and log the destination URL instead of opening it within a new tab.

```javascript
window.open = () => {
    const debugWindow = {};

    Object.defineProperty(debugWindow, "location", {
      set(newLocation) {
        console.log("Destination url", newLocation);
      },
    });

    return debugWindow;
};
```

> Can we be sure that user is first directed to Admin page when `openOnAdminRoom` is set on params? Where can we find the related code to open admin report? As we will be preventing navigation to Workspace chat when openOnAdminRoom is set on params, I am just trying to confirm that we don't leave users on limbo.

That is already the case. The current issue is that is user is redirect away from the admin page afterwards. See the current implementation:

https://github.com/Expensify/App/blob/6730662b0c89c0f32045e57273ff39e0d78661a7/src/libs/actions/App.js#L210-L227

**Comment by garrettmknight** [comment] 2023-08-07 16:45
@sobitneupane I know you're on limited hours today/tomo, just flagging this for a response when you get back.

**Comment by sobitneupane** [comment] 2023-08-09 11:23
@StefanNemeth 
Thanks for the update.

[Proposal](https://github.com/Expensify/App/issues/23566#issuecomment-1653743006) from @StefanNemeth looks good to me.

🎀 👀 🎀 C+ reviewed

**Comment by dangrous** [comment] 2023-08-09 16:22
Cool, that looks great to me!

My only potential question is will we introduce any regressions by moving the check for the admin room above the other checks in `findLastAccessedReport` but as long as we do a good job testing the PR we should be okay! We should see if we can figure out any flows where we would have openOnAdminRoom but not actually want to / be able to do that.

**Comment by dangrous** [comment] 2023-08-16 15:36
Hey @kbecciv can you let us know what's in the TestRail for this flow? Specifically - once the #admins chat is opened after the workspace settings window is closed, should the new user pop up (the FAB) be open? I think probably not, but I wasn't sure if we have that listed somewhere. Thanks!

**Comment by dangrous** [comment] 2023-08-25 15:45
Hey @StefanNemeth, thanks for checking! So in this case there won't be a bonus since the issue was being pretty steadily updated and worked on throughout that time period. But, there's always next time! And, don't be shy to ping or bump issues if you're blocked, too - we won't mind.

**Comment by dangrous** [comment] 2023-08-25 15:47
Unrelated, it looks like this was merged to prod on 8/23, so I think we can expect payment on 8/30 if all goes well. I'm not sure why Melvin keeps dropping the ball.

**Comment by kbecciv** [comment] 2023-08-26 13:52
Hello @dangrous ! Coming back from OOO, let me find the TR link and steps for this issue.

**Comment by kbecciv** [comment] 2023-08-26 14:00
Issue is coming from PR https://github.com/Expensify/App/pull/22619 on Test 3 step 6

![image](https://github.com/Expensify/App/assets/93399543/b8573be6-7006-4b4d-a382-3f690ec92cb6)

**Comment by dangrous** [comment] 2023-08-28 14:40
Okay great! That's helpful to confirm we did the right thing. Sorry to bother you while you were OOO!

**Comment by dangrous** [comment] 2023-08-30 19:32
@garrettmknight double check my math but I believe we're ready to go for payment here (Melvin is not cooperating) since this was deployed to prod on 8/23

**Comment by garrettmknight** [comment] 2023-09-04 10:23
Yep, just noticed a rash of this type of issues where Melv missed them. On it!

**Comment by garrettmknight** [comment] 2023-09-04 10:23
BugZero Checklist: The PR fixing this issue has been merged! The following checklist ([instructions](https://stackoverflow.com/c/expensify/questions/14574)) will need to be completed before the issue can be closed:

- [ ]  [@sobitneupane] The PR that introduced the bug has been identified. Link to the PR:
- [ ]  [@sobitneupane] The offending PR has been commented on, pointing out the bug it caused and why, so the author and reviewers can learn from the mistake. Link to comment:
- [ ]  [@sobitneupane] A discussion in #expensify-bugs has been started about whether any other steps should be taken (e.g. updating the PR review checklist) in order to catch this type of bug sooner. Link to discussion:
- [ ]  [@sobitneupane] Determine if we should create a regression test for this bug.
- [ ]  [@sobitneupane] If we decide to create a [regression test](https://github.com/Expensify/App/blob/main/contributingGuides/REGRESSION_TEST_BEST_PRACTICES.md) for the bug, please propose the regression test steps to ensure the same bug will not reach production again.
- [ ]  [@garrettmknight] Link the GH issue for creating/updating the regression test once above steps have been agreed upon:

**Comment by garrettmknight** [comment] 2023-09-04 10:29
**Summary of payments for this issue:**

#urgency bonus? No
Reporter: N/A
Contirbutor: @StefanNemeth - $1000
Contributor+: @sobitneupane - $1000

Upwork job: https://www.upwork.com/jobs/~01c12a52f499c32c9c

**Comment by garrettmknight** [comment] 2023-09-04 12:49
Paid!

**Comment by sobitneupane** [comment] 2023-09-05 17:33
> BugZero Checklist: The PR fixing this issue has been merged! The following checklist ([instructions](https://stackoverflow.com/c/expensify/questions/14574)) will need to be completed before the issue can be closed:
> 
> * [ ]   [@sobitneupane] The PR that introduced the bug has been identified. Link to the PR:

This is an old issue and was probably introduced by [this PR](https://github.com/Expensify/App/pull/8855#issue-1223104164)
> * [ ]   [@sobitneupane] The offending PR has been commented on, pointing out the bug it caused and why, so the author and reviewers can learn from the mistake. Link to comment:

https://github.com/Expensify/App/pull/8855#issue-1223104164
> * [ ]   [@sobitneupane] A discussion in #expensify-bugs has been started about whether any other steps should be taken (e.g. updating the PR review checklist) in order to catch this type of bug sooner. Link to discussion:


> * [ ]   [@sobitneupane] Determine if we should create a regression test for this bug.

yes
> * [ ]   [@sobitneupane] If we decide to create a [regression test](https://github.com/Expensify/App/blob/main/contributingGuides/REGRESSION_TEST_BEST_PRACTICES.md) for the bug, please propose the regression test steps to ensure the same bug will not reach production again.

**Comment by sobitneupane** [comment] 2023-09-05 17:41
**Regression Test Proposal**

1. Go to staging.expensify.com and login with a new account
2. Go to Settings > Policies > Group
3. Select Free Policy
4. Verify that User is navigated to #admins page report with workspace details on RHP.

Do we agree 👍 or 👎

**Comment by dangrous** [comment] 2023-09-05 17:50
I might modify very slightly:

1. Go to staging.expensify.com and login with a new account
2. Go to Settings > Policies > Group
3. Select Free Policy
4. Verify that User is navigated to #admins page report with workspace details open in the RHP.
5. Verify that closing the RHP puts the user in the #admins report.

Just to make that last bit a little more clear

**Comment by sobitneupane** [comment] 2023-09-05 18:00
Requested payment on newDot.

https://github.com/Expensify/App/issues/23566#issuecomment-1705016402

**Comment by JmillsExpensify** [comment] 2023-09-10 11:01
$1,000 payment approved via NewDot based on BZ summary.

**Comment by JmillsExpensify** [comment] 2023-09-10 11:01
Leaving this issue open for the regression test.

**Comment by garrettmknight** [comment] 2023-09-13 11:37
Done!

**Closed by garrettmknight** 2023-09-13 11:37 UTC
Labels: External, Daily, Overdue, Awaiting Payment, Bug
