### ISSUE TITLE
[$1000] Web - When deleting a message, you cannot use arrows to toggle between "Delete" and "Cancel"

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#21640] opened 2023-06-26 20:23 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Write a message on composer and send it
2.  Edit it by pressing arrow key up and delete the entire message and hit enter
3. A modal opens asking if you want to confirm the deletion
4.  Hit left arrow to attempt to cancel the message

## Expected Result:
In the delete box, you cannot select the `cancel` button with arrows

## Actual Result:
Message gets deleted because you cannot focus the `cancel` button with arrow keys.

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [ ] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 1.3.32.5
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/93399543/23ea2cc9-eca4-4026-b20c-9e10fd4bce1f

https://github.com/Expensify/App/assets/93399543/3acd6bc7-8c8e-4d36-80c4-46d1ea056e7d

**Expensify/Expensify Issue URL:**
**Issue reported by:** @dan1d
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1687483418798109

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~018188fb2901398792</li>
        <li>Upwork Job ID: 1675046551407325184</li>
        <li>Last Price Increase: 2023-07-08</li>
    </ul>
</details>

**Comment by jfquevedol2198** [comment] 2023-06-26 22:17
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
Web - When deleting a message I cannot move to cancel with arrows

### What is the root cause of that problem?
`Delete` button has `pressOnEnter` props. Although focus is changed to `Cancel` button, `Cancel` button will not clicked by clicking `Enter` key.
https://github.com/Expensify/App/blob/98bb603a89fe0323d503157961c7f4fbfe0db45b/src/components/ConfirmContent.js#L66-L73

### What changes do you think we should make in order to solve the problem?
Remove `pressOnEnter` props

```javascript
<Button
    success={props.success}
    danger={props.danger}
    style={[styles.mt4]}
    onPress={props.onConfirm}
    text={props.confirmText || props.translate('common.yes')}
/>
```

### What alternative solutions did you explore? (Optional)
N/A

**Comment by jfquevedol2198** [comment] 2023-06-26 22:42
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
Web - When deleting a message I cannot move to cancel with arrows

### What is the root cause of that problem?
`Delete` button has `pressOnEnter` props, but `Cancel` button doesn't have it. So, although focus is changed to `Cancel` button, `Cancel` button will not clicked by clicking `Enter` key.
https://github.com/Expensify/App/blob/98bb603a89fe0323d503157961c7f4fbfe0db45b/src/components/ConfirmContent.js#L66-L73

### What changes do you think we should make in order to solve the problem?
Remove `pressOnEnter` from `Delete` button

```javascript
<Button
    success={props.success}
    danger={props.danger}
    style={[styles.mt4]}
    onPress={props.onConfirm}
    text={props.confirmText || props.translate('common.yes')}
/>
)}
```

### What alternative solutions did you explore? (Optional)
N/A

**Comment by alexpensify** [comment] 2023-06-28 23:04
I will test soon

**Comment by alexpensify** [comment] 2023-06-29 22:48
Reassigning another bug team member, I'm going OOO until Monday, July 10, and will take it back if it's still open by my return date.

Required action from the 🐛 team: I've run out of time and haven't tested this one yet. This GH needs testing to confirm if it's a bug, check if it's a dupe, and then assign the applicable labels. Thank you!

**Comment by jliexpensify** [comment] 2023-07-01 07:37
I can repro, but the original issue steps aren't clear and don't specifically focus on the issue. I've edited it now.

**Comment by jliexpensify** [comment] 2023-07-01 07:40
@eVoloshchak - I found this other issue: https://github.com/Expensify/App/issues/20954

It seems similar, would you say this is a dupe? Cheers.

**Comment by eVoloshchak** [comment] 2023-07-02 20:33
> I found this other issue: https://github.com/Expensify/App/issues/20954
It seems similar, would you say this is a dupe? Cheers.

@jliexpensify, they are related, but this one is a separate issue. 
I agree with @hoangzinh's [comment](https://github.com/Expensify/App/issues/21640#issuecomment-1616471286), this is a feature request. 
It's possible to navigate between buttons using traditional Tab navigation, but this issue specifies using arrow buttons. 
Can you confirm we want to apply arrow navigation to this modal? Thanks

**Comment by jliexpensify** [comment] 2023-07-02 22:10
Awesome, thanks for weighing in @eVoloshchak and @hoangzinh - I'll query this one with our team internally!

**Comment by jliexpensify** [comment] 2023-07-04 04:23
No response, and I'm headed OOO for a couple of days. Have bumped the Slack thread and will update when I get back. This isn't an urgent bug, it's more of a feature request so it's all good to wait a bit.

**Comment by jliexpensify** [comment] 2023-07-09 22:01
Ok, I didn't receive any response to my Slack thread. Given that this is a [feature request](https://github.com/Expensify/App/issues/21640#issuecomment-1616471286), I'm going to close this in favour of working on actual, current bugs.

**Closed by jliexpensify** 2023-07-09 22:01 UTC
Labels: External, Daily, Help Wanted, Bug

**Comment by alexpensify** [comment] 2023-07-10 21:11
Thank you @jliexpensify for the help here
