### ISSUE TITLE
iOS - Attachments - Not possible to attach photo from the Gallery which was taken with Live mode off

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#12014] opened 2022-10-19 21:59 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
Preconditions: Settings --> Camera --> Formats --> should be set to "High Efficiency"
1. Open Native iOS Camera App
2. Turn off the Live Photo mode and take the photo
3. Open the NewDot App and try to upload previous photo from the Gallery

## Expected Result:
The user user should be able to upload photos from Gallery without any issues

## Actual Result:
Photo preview is available, but at the last strep format error appears.

## Workaround:
Unknown

## Platform:

Where is this issue occurring?

- iOS

**Version Number:** 1.2.18.2

**Reproducible in staging?:** Yes

**Reproducible in production?:** Yes

**Email or phone of affected tester (no customers):** 

**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Notes/Photos/Videos:** Any additional supporting documentation

https://user-images.githubusercontent.com/93399543/196812712-44faba5b-b346-4b5e-9179-7cf183d30a3e.mp4

**Expensify/Expensify Issue URL:** 

**Issue reported by:** Applause - Internal Team

**Slack conversation:** 

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by Beamanator** [comment] 2022-10-24 09:00
Interesting! We have a related issue about attachment types that I will look for, but this seems weird b/c the image filename ends with `.jpg` which is definitely allowed 🤔  I thinkkkkk this needs to be internal

**Comment by Beamanator** [comment] 2022-11-02 16:50
Trying to get someone to take over for me, got too many other issues on my plate atm

**Comment by Beamanator** [comment] 2022-11-07 08:09
Pinged in #bug-zero for a CME to take over since I don't own a physical iPhone

**Comment by Beamanator** [comment] 2022-11-07 08:50
@MonilBhavsar  volunteered to take over 🙏

**Comment by JmillsExpensify** [comment] 2022-11-07 19:03
This needs a BZ member, so adding myself.

**Comment by mvtglobally** [comment] 2022-11-09 03:40
Issue not reproducible during KI retests. (First week)

**Comment by JmillsExpensify** [comment] 2022-11-10 04:57
Ok, I just re-tested and we're talking about this same issue in multiple places. This is a dupe of https://github.com/Expensify/App/issues/12459. I'm closing this issue.

**Closed by JmillsExpensify** 2022-11-10 04:57 UTC
Labels: Engineering, Weekly, Internal
