### ISSUE TITLE
QBO - Multi tag - "Required" is not aligned correctly under Status column

### ISSUE THREAD

**Issue by m-natarajan** [Expensify/App#42066] opened 2024-05-13 13:39 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.73-0
**Reproducible in staging?:** y
**Reproducible in production?:** no
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** Applause internal team
**Slack conversation:**

## Action Performed:
Precondition:
- Workspace is connected to QBO.
- Classes and Customers/Projects are imported from Import settings.

1. Go to staging.new.expensify.com
2. Go to workspace settings.
3. Go to Tags.
4. Click Settings.
5. Toggle on "Members must tag all spend".

## Expected Result:
"Required" will align correctly under Status column.

## Actual Result:
"Required" is not aligned correctly under Status column.

## Workaround:
unknown
## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [x] Android: mWeb Chrome
- [x] iOS: Native
- [x] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

https://github.com/Expensify/App/assets/38435837/d1a48fdf-80c3-42ae-b321-b7a071f8954d

<img src="https://github.com/Expensify/App/assets/38435837/6866f6cf-44c9-4601-997b-997ee500d336" width="40%" height="40%">

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by m-natarajan** [comment] 2024-05-13 13:40
@isabelastisser FYI I haven't added the External label as I wasn't 100% sure about this issue. Please take a look and add the label if you agree it's a bug and can be handled by external contributors

**Comment by m-natarajan** [comment] 2024-05-13 13:40
We think that this bug might be related to #wave-collect - Release 1

**Comment by rlinoz** [comment] 2024-05-13 14:18
Hmm it looks like it is working as intended, we don't have the caret so it gets right aligned, but I will ask in Slack.

**Comment by rlinoz** [comment] 2024-05-13 14:24
But anyway, we don't need to block on this, removing the label.

**Comment by s77rt** [comment] 2024-05-13 16:19
Working on it

**Comment by s77rt** [comment] 2024-05-13 16:52
[PR](https://github.com/Expensify/App/pull/42089) is ready for review

**Comment by ikevin127** [comment] 2024-05-23 00:23
⚠️ **Automation failed**: This was deployed to **production** today [here](https://github.com/Expensify/App/pull/42089#issuecomment-2125963747), therefore should be **[HOLD for Payment 2024-05-29]** and have `Awaiting Payment` label.

cc @isabelastisser @rlinoz

**Comment by rlinoz** [comment] 2024-05-23 14:51
Hmm not sure if payment is due since this was a fix to the original PR https://github.com/Expensify/App/pull/41351

**Comment by s77rt** [comment] 2024-05-23 22:47
Correct since this is a regression no payment is due

**Comment by rlinoz** [comment] 2024-05-24 13:43
Thanks, closing then!

**Closed by rlinoz** 2024-05-24 13:43 UTC
Labels: Reviewing, Engineering, Weekly, Bug
