### ISSUE TITLE
[HOLD for payment 2023-09-20] [$500] IOU - "/edit/subdirectory" from the amount page shows blank RHP

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#26014] opened 2023-08-26 22:18 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Open any chat
2. Open any request money room ( request one if there is no previous requests )
3. Open the Money request room
4. Open the details room of one request
5. Click on the amount to open the amount page
6. Now go and modify the url to end with "/edit/subdirectory", you can add any subdirectory you want except "amount"

## Expected Result:
1. Redirect the user to the previous room. ( this is what happened when you try to open the "/edit/amount" from a deleted request room )
2. Display the  "Hmm... it's not here" page

## Actual Result:
A blank RHP is opened

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [x] Windows / Chrome 
- [ ] MacOS / Desktop

**Version Number:** 1.3.57-5

**Reproducible in staging?:** Yes

**Reproducible in production?:** Yes

**If this was caught during regression testing, add the test name, ID and link from TestRail:**

**Email or phone of affected tester (no customers):**

**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Notes/Photos/Videos:** Any additional supporting documentation

[Screencast from 18-08-23 02_51_16 (1).webm](https://github.com/Expensify/App/assets/78819774/3ccf9d83-dda7-484d-a5d6-2b299c6c21b1)

https://github.com/Expensify/App/assets/78819774/aab22910-bcfe-4150-81e8-967c2e475bd2

**Expensify/Expensify Issue URL:**

**Issue reported by:** @Ahmed-Abdella

**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1692317384241769

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01480fed14ee7c9bd7</li>
        <li>Upwork Job ID: 1696159404102758400</li>
        <li>Last Price Increase: 2023-08-28</li>
<li>Automatic offers: </li>
<ul>
<li>dukenv0307 | Contributor | 26400484</li>
<li>Ahmed-Abdella | Reporter | 26400485</li>
</ul></li>
    </ul>
</details>

**Comment by LuckyBoy1004** [comment] 2023-08-28 16:44
Contributor details
Your Expensify account email: <yuriividni@gmail.com>
Upwork Profile Link: <[REPLACE LINK HERE](https://www.upwork.com/freelancers/~01546af8ef2728dfd3)>

**Comment by LuckyBoy1004** [comment] 2023-08-28 16:47
Contributor details
Your Expensify account email: [yuriividni@gmail.com](mailto:yuriividni@gmail.com)
Upwork Profile Link: <[REPLACE LINK HERE](https://www.upwork.com/freelancers/~01546af8ef2728dfd3)>

**Comment by LuckyBoy1004** [comment] 2023-08-28 16:57
Contributor details
Your Expensify account email: <yuriividni@gmail.com>
Upwork Profile Link: <https://www.upwork.com/freelancers/~01546af8ef2728dfd3>

**Comment by LuckyBoy1004** [comment] 2023-08-28 16:59
Contributor details
Your Expensify account email: <yuriividni@gmail.com>
Upwork Profile Link: <https://www.upwork.com/freelancers/~01546af8ef2728dfd3>

**Comment by davewish** [comment] 2023-08-28 17:08
###  Proposal 

### Please re-state the problem that we are trying to solve in this issue.
 "/edit/subdirectory" from the amount page shows blank RHP

### What is the root cause of that problem?
when  `editField` becomes invalid  or does not exist  `EDIT_REQUEST_FIELD` field ,  `null` is returned 
 https://github.com/Expensify/App/blob/ed8f3e62ae9ea6eeab57664a60b37813f0c090ee/src/pages/EditRequestPage.js#L171

###  What changes do you think we should make in order to solve the problem?

  When  `editField`. is invalid ,  we  should return 
`return  <NotFoundPage/>;`
### What alternative solutions did you explore? (Optional)

We should return ` return <FullPageNotFoundView shouldShow/>;`

**Comment by davewish** [comment] 2023-08-28 17:11
Contributor details
Your Expensify account email: dvwish9214@gmail.com
Upwork Profile Link: https://www.upwork.com/freelancers/~01e47e5f2122786310

**Comment by LuckyBoy1004** [comment] 2023-08-28 17:14
Contributor details
Your Expensify account email: yuriividni@gmail.com
Upwork Profile Link: https://www.upwork.com/freelancers/~01546af8ef2728dfd3

**Comment by maddylewis** [comment] 2023-08-29 13:08
bumping @thesahindia - lmk if you have the bandwidth for this one. otherwise, i can reach out to another C+ to get the proposals reviewed. thanks!

**Comment by bondydaa** [comment] 2023-09-06 23:02
noting some of the timing here since this is getting held up due to me missing the reivew notification and feature freeze

assigned:
<img width="532" alt="image" src="https://github.com/Expensify/App/assets/4073354/c940b427-e026-4577-a0f8-334e36fb95bf">

approved by C+
<img width="933" alt="image" src="https://github.com/Expensify/App/assets/4073354/1436489f-b82a-44a8-a065-11f949381fcd">

Approved by me today and will merge after feature freeze is over.

**Comment by bondydaa** [comment] 2023-09-11 18:44
Pretty sure @dukenv0307 should qualify for the merged within 3 days bonus since had I not missed the notifications and the feature freeze I would have merged after @thesahindia has approved on Aug 31 which was within 3 business days if I'm not mistake.

**Comment by maddylewis** [comment] 2023-09-18 18:59
moving to daily since payment is coming up

**Comment by maddylewis** [comment] 2023-09-21 13:30
i will get payments processed today. 

@thesahindia bump on the checklist - ty!

**Comment by maddylewis** [comment] 2023-09-22 02:05
### Payments
- [ ] @thesahindia ($500 via NewDot)
- [ ] @dukenv0307 ($500 via Upwork)
- [ ] @Ahmed-Abdella ($50 via Upwork)

**Comment by Ahmed-Abdella** [comment] 2023-09-22 02:53
@maddylewis It is actually 250$ for reporting bonus?

**Comment by maddylewis** [comment] 2023-09-22 14:03
paid

**Comment by Ahmed-Abdella** [comment] 2023-09-26 14:40
@maddylewis  this didn't happen it is just 250$

![Screenshot from 2023-09-26 17-39-37](https://github.com/Expensify/App/assets/77763699/5c301834-6fbd-4fa2-998d-025a9a50e539)

**Comment by maddylewis** [comment] 2023-09-29 14:33
im still not following -- you are listed as the reporter of the bug on this issue. you are not assigned as the Contributor or the C+. 

@bondydaa am i missing something? 
<img width="741" alt="image" src="https://github.com/Expensify/App/assets/38016013/fadfd9b6-0eb1-434b-b4ec-5575fd7c63e8">
<img width="694" alt="image" src="https://github.com/Expensify/App/assets/38016013/77445d8c-0a94-49ee-9de3-3efcbf9eec73">
<img width="300" alt="image" src="https://github.com/Expensify/App/assets/38016013/454acf3a-fee0-4157-9823-5fbd9a6722dd">

**Comment by Ahmed-Abdella** [comment] 2023-09-29 15:20
@maddylewis we are OK. I am just the reporter. You didn't miss anything.

**Comment by Ahmed-Abdella** [comment] 2023-09-29 15:26
> ### Payments
> - [x] @thesahindia ($1000 via NewDot)
> - [x] @dukenv0307 ($1000 via Upwork)
> - [x] @Ahmed-Abdella ($250 via Upwork)

This payments checks was  50 for reporting bonus at first I just wanted to clarify that it should be 250 in those checks. That is it nothing more but everything is OK.

**Comment by maddylewis** [comment] 2023-10-02 13:28
@Ahmed-Abdella - okay i gotcha! 

yep, after August 30, the reporting bonus is $50. But, bc you reported this on August 26, you qualified for the old reporting bonus amount ($250).

**Comment by maddylewis** [comment] 2023-10-05 20:34
oh oh you're talking about this comment where bondy clarified that this is actually eligible for the bonus - https://github.com/Expensify/App/issues/26014#issuecomment-1709236118

got it 👍

**Comment by maddylewis** [comment] 2023-10-05 20:35
@dukenv0307 - do i owe you $500 bonus?

**Comment by Ahmed-Abdella** [comment] 2023-10-05 23:51
@maddylewis 

I'm not entirely certain, but it seems like there might be something wrong here. This issue should be 500$ not 1000$ as per this [comment](https://github.com/Expensify/App/issues/26014#issuecomment-1695746830), because it was an edge case, and it is [$500] in the title. So I think the fixing payment should be 500$ + ( 250$ urgency bonus ) = 750$.

So the payment  should be :
750$ @dukenv0307 
750$ @thesahindia 
250$ for reporting bonus ( And I received this payment )

**Comment by maddylewis** [comment] 2023-10-07 19:40
-  @thesahindia ($750 via NewDot)
-  @dukenv0307 ($750 via Upwork)
-  @Ahmed-Abdella ($250 via Upwork)

**Comment by maddylewis** [comment] 2023-10-07 19:41
ok sent @dukenv0307 $250 bonus ($750 total). closing!

**Closed by maddylewis** 2023-10-07 19:41 UTC
Labels: External, Daily, Awaiting Payment, Bug

**Comment by JmillsExpensify** [comment] 2023-10-25 17:07
$750 payment approved for @thesahindia based on [this comment](https://github.com/Expensify/App/issues/26014#issuecomment-1751802684).
