### ISSUE TITLE
[HOLD for payment 2023-06-28] [$1000] Web - Split Bill - Profile picture still shows avatar on a new split money page

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#20118] opened 2023-06-03 15:07 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Open NewDot staging on web chrome.
2. Create a workspace (if you don't already have one). Invite a second member to the workspace. 
3. Go to the workspace's announce room. 
5. Split a bill between the two workspace members. 
6. Click the bill split from within the announce room (so it opens the RHN with the details of the bill split.)
7. Click the settings tab and change your profile image. 
8. Go back to the announce room, click into the bill split, and notice that your old profile image is display in the details page. 

## Expected Result:
Profile picture should be updated on a new split money page

## Actual Result:
Profile picture still shows avatar on a new split money page

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [x] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 1.3.22.0

**Reproducible in staging?:** n/a

**Reproducible in production?:** n/a

**If this was caught during regression testing, add the test name, ID and link from TestRail:**

**Email or phone of affected tester (no customers):**

**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/93399543/af62a462-2350-4325-a493-57f36d5ef618

**Expensify/Expensify Issue URL:**

**Issue reported by:** @avi-shek-jha

**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1685417843739759

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~015e350d1e95099cb9</li>
        <li>Upwork Job ID: 1665846988733915136</li>
        <li>Last Price Increase: 2023-06-12</li>
    </ul>
</details>

**Comment by joekaufmanexpensify** [comment] 2023-06-05 22:23
I can reproduce this. Interestingly, the profile image in the LHN and in the settings tab is also not updating right away after changing it. Although both do update after refreshing the session. Whereas the image on the bill split detailed page does not. 

Uploading 2023-06-05_18-15-42.mp4…

**Comment by joekaufmanexpensify** [comment] 2023-06-05 22:23
https://github.com/Expensify/App/assets/54866469/1e372f58-22d4-4750-9052-e63b0cc09c7b

**Comment by joekaufmanexpensify** [comment] 2023-06-06 20:18
Sounds good, thanks @parasharrajat !

**Comment by joekaufmanexpensify** [comment] 2023-06-07 21:14
@parasharrajat are we good to proceed with either of these proposals?

**Comment by joekaufmanexpensify** [comment] 2023-06-08 18:27
Bumped proposals in slack [here](https://expensify.slack.com/archives/C02NK2DQWUX/p1686248824186689)

**Comment by bernhardoj** [comment] 2023-06-11 12:01
Sharing my opinion:

I think @dukenv0307 2nd proposal looks better. Filtering personalDetails (especially in HT account) doesn't sounds good.

**Comment by bernhardoj** [comment] 2023-06-12 09:59
Ah, you're right. I totally forgot about that 🤦

**Comment by joekaufmanexpensify** [comment] 2023-06-12 17:57
@flodnv thoughts on proceeding with [this proposal](https://github.com/Expensify/App/issues/20118#issuecomment-1584702801)?

**Comment by flodnv** [comment] 2023-06-12 18:22
Option 1 from @dukenv0307's proposal looks good to me, and

>So shoud we get payeePersonalDetails by personalDetails[reportAction.actorEmail] instead of using filter function.

Yes

**Comment by joekaufmanexpensify** [comment] 2023-06-20 21:38
Hm, not overdue. PR is waiting to be deployed to prod.

**Comment by joekaufmanexpensify** [comment] 2023-06-26 13:33
This one did not qualify for speed bonus, so we need to issue the following payments: 

- @dukenv0307 - $1,000 
- @parasharrajat - $1,000
- @avi-shek-jha - $250

**Comment by joekaufmanexpensify** [comment] 2023-06-26 13:35
@parasharrajat offer sent for $1,000!

**Comment by joekaufmanexpensify** [comment] 2023-06-26 13:40
@avi-shek-jha offer sent for $250!

**Comment by joekaufmanexpensify** [comment] 2023-06-26 13:41
@parasharrajat Could you please complete your portion of the BZ checklist when you have a chance? Thanks!

**Comment by joekaufmanexpensify** [comment] 2023-06-26 14:03
Hm, were we waiting for that PR though? I see this PR was being reviewed concurrently to the one you referenced. And [one comment](https://github.com/Expensify/App/pull/20573#issuecomment-1593474114) about it, but it didn't seem to me like we were holding on it. Unless I am not understanding correctly. 

And it seems like we [were still actively working on this PR](https://github.com/Expensify/App/pull/20573#issuecomment-1593683333) when the other one you referenced got merged, rather than this one being done, and just waiting for the other one to merge. So I'd still say no speed bonus here. But LMK if you're thinking about this differently!

**Comment by joekaufmanexpensify** [comment] 2023-06-27 20:24
As soon as the bug-zero checklist is complete here, we'll be all set to issue payment tomorrow!

**Comment by joekaufmanexpensify** [comment] 2023-06-27 21:20
Sounds good, thanks! I will create the regression test issue tomorrow.

**Comment by flodnv** [comment] 2023-06-28 18:09
I think the regression test sounds good as long as QA agrees it's not too niche... 👍

**Comment by joekaufmanexpensify** [comment] 2023-06-28 19:42
Sounds good. Added regression test issue above. BZ checklist is now complete!

**Comment by joekaufmanexpensify** [comment] 2023-06-28 19:44
All set to issue payment here! @parasharrajat I know your payment is held right now, but going to issue the others.

**Comment by joekaufmanexpensify** [comment] 2023-06-28 19:46
@dukenv0307 $1,000 sent and contract ended!

**Comment by joekaufmanexpensify** [comment] 2023-06-28 19:47
@avi-shek-jha $250 sent and contract ended!

**Comment by joekaufmanexpensify** [comment] 2023-06-28 19:49
Leaving this open until we are all set to pay @parasharrajat

**Comment by joekaufmanexpensify** [comment] 2023-06-30 17:28
Held pending being able to pay rajat.

**Comment by joekaufmanexpensify** [comment] 2023-07-03 13:13
Not overdue. Pending being able to issue payment here.

**Comment by joekaufmanexpensify** [comment] 2023-07-05 12:53
Payment to rajat still on hold. Bumped in Slack.

**Comment by joekaufmanexpensify** [comment] 2023-07-10 14:03
Still on hold

**Comment by joekaufmanexpensify** [comment] 2023-07-17 13:13
[Bumped in Slack ](https://expensify.slack.com/archives/C02NK2DQWUX/p1689599617076879)

**Comment by joekaufmanexpensify** [comment] 2023-08-02 19:34
Closing for now, since all that's left is NewDot payment (which has been requested)!

**Closed by joekaufmanexpensify** 2023-08-02 19:34 UTC
Labels: External, Weekly, Awaiting Payment, Bug

**Comment by JmillsExpensify** [comment] 2023-08-02 23:48
Reviewed details for @parasharrajat. These details are accurate based on summary from Business Reviewer and are now approved for payment in NewDot.
