### ISSUE TITLE
Workspace - "Report no longer exists" error appears when deleting WS if member created a thread

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#40362] opened 2024-04-17 16:35 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.62-13
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**If this was caught during regression testing, add the test name, ID and link from TestRail:** N/A
**Issue reported by:** Applause - Internal Team

## Action Performed:
1. Navigate to staging.new.expensify.com
2. As User A create a workspace and invite User B
3. As User B go to announce room of the invited workspace and send a message
4. As User B, click Reply in Thread of the message sent on step 3 and send a message inside the thread
5. As User A delete the workspace created on step 2

## Expected Result:
Workspace gets deleted

## Actual Result:
"Report no longer exists" error appears after a while

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details> 

https://github.com/Expensify/App/assets/78819774/0be3f0e9-a30a-4118-bf77-3b91a157740c

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~016a4d244191ab6c33</li>
        <li>Upwork Job ID: 1783746269156757504</li>
        <li>Last Price Increase: 2024-04-26</li>
    </ul>
</details>

**Comment by lanitochka17** [comment] 2024-04-17 16:36
@Christinadobrzyn  FYI I haven't added the External label as I wasn't 100% sure about this issue. Please take a look and add the label if you agree it's a bug and can be handled by external contributors

**Comment by lanitochka17** [comment] 2024-04-17 16:37
We think that this bug might be related #wave-collect - Release 1

**Comment by Christinadobrzyn** [comment] 2024-04-22 01:45
not sure if this root cause might be related to - https://github.com/Expensify/App/issues/40404

User A - c.dobrzyn+34@expensifail.com
workspace InviteTest
User B - c.dobrzyn+56@expensifail.com

I can reproduce this - here's what it looks like after the workspace is deleted

<img width="1710" alt="image" src="https://github.com/Expensify/App/assets/51066321/9abf3d47-f64e-4800-8076-e269f5e3f64e">

I think this might need to be internal but gonna see if we can fix it as external. I think this is part of vip-vsb collect rooms.

**Comment by hungvu193** [comment] 2024-04-25 03:43
This is BE issue

<img width="299" alt="Screenshot 2024-04-25 at 10 41 45" src="https://github.com/Expensify/App/assets/16502320/f497f9b3-4191-4005-9a3c-988429d45202">

**Comment by Christinadobrzyn** [comment] 2024-04-29 09:54
added internal labels - I'll try to find someone to grab this

**Comment by Christinadobrzyn** [comment] 2024-05-02 09:09
@hungvu193 can you retest? I'm not able to reproduce this.

**Comment by hungvu193** [comment] 2024-05-02 09:18
> @hungvu193 can you retest? I'm not able to reproduce this.

Server is down for me. I'll check it in a while.

**Comment by hungvu193** [comment] 2024-05-02 09:53
Yeah, I can't reproduce this anymore. I think we can close it

**Closed** 2024-05-03 05:48 UTC
Labels: Daily, Internal, Help Wanted, Bug, Hot Pick
