### ISSUE TITLE
[$250] Navigation - Navigating back from Group Name page takes you to settings

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#45812] opened 2024-07-20 00:44 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 9.0.9-5
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**If this was caught during regression testing, add the test name, ID and link from TestRail:** N/A
**Email or phone of affected tester (no customers):** dave0123seife@gmail.com
**Issue reported by:** Applause -Internal Team

## Action Performed:
1. Create a group chat
2. Click on group chat header > Group Name
3. Refresh page
4. Click the back button on top

## Expected Result:
Navigated back to the details page

## Actual Result:
Navigated from group name page to the Settings page

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details> 

https://github.com/user-attachments/assets/5ebd6179-7546-47d0-b78f-e4387a3b87d3

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~0161510c9ca070bc11</li>
        <li>Upwork Job ID: 1816208685407209961</li>
        <li>Last Price Increase: 2024-07-24</li>
<li>Automatic offers: </li>
<ul>
<li>nyomanjyotisa | Contributor | 103342040</li>
</ul></li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @puneetlath</details>

**Comment by MitchExpensify** [comment] 2024-07-22 17:01
I am on parental leave, reassigning

**Comment by puneetlath** [comment] 2024-08-28 21:33
Looks like this is ready to pay. 

I've paid @nyomanjyotisa. @eVoloshchak can you do the checklist?

**Comment by eVoloshchak** [comment] 2024-09-02 15:23
- The PR that introduced the bug has been identified. Link to the PR: https://github.com/Expensify/App/pull/39757
- The offending PR has been commented on, pointing out the bug it caused and why, so the author and reviewers can learn from the mistake. Link to comment: https://github.com/Expensify/App/pull/39757/files#r1741062297
- A discussion in #expensify-bugs has been started about whether any other steps should be taken (e.g. updating the PR review checklist) in order to catch this type of bug sooner. Link to discussion: this is a pretty straightforward issue, I don't think an additional discussion is needed

**Regression Test Proposal**

1. Create a group chat
2. Click on group the chat header > Group Name
3. Refresh the page
4. Click the back button on top
5. Verify that you're navigated back to the details page


**Do we agree 👍 or 👎**

**Comment by puneetlath** [comment] 2024-09-03 19:13
Payment summary: 
- C - $250 - @nyomanjyotisa - paid via Upwork
- C+ - 250 - @eVoloshchak - to be paid via NewDot

Thanks everyone!

**Closed by puneetlath** 2024-09-03 19:13 UTC
Labels: Reviewing, External, Monthly, Bug

**Comment by JmillsExpensify** [comment] 2024-09-05 23:09
$250 approved for @eVoloshchak
