### ISSUE TITLE
[$500] unable to submit report, "unexpected error" appears

### ISSUE THREAD

**Issue by m-natarajan** [Expensify/App#35936] opened 2024-02-06 18:11 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:**
**Reproducible in staging?:** needs reproduction
**Reproducible in production?:** needs reproduction
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** @luacmartins 
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1706246633750589

## Action Performed:
1. Create an expense report as employee
2. Submit the report
## Expected Result:
Able to submit with no errors
## Actual Result:
Requested approver not on workspace RequestID 84b6517d4fb061e2-YVR. Unexpected error, please try again error message

NOTE: After sometime the message shows as concierge submitted the report and `submit` button disappears
## Workaround:
unknown
## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence
![Screenshot 2024-01-25 at 10 22 16 PM](https://github.com/Expensify/App/assets/38435837/a64241c2-3a54-4f26-b0a9-a221e01829ad)
![Screenshot 2024-01-26 at 9 06 09 AM](https://github.com/Expensify/App/assets/38435837/27a83fa0-7967-4836-8cbc-54e6daf22a1a)

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~0153368e03926bacdf</li>
        <li>Upwork Job ID: 1757798001786544128</li>
        <li>Last Price Increase: 2024-02-21</li>
    </ul>
</details>

**Comment by johncschuster** [comment] 2024-02-14 16:05
This _might_ be a backend issue, but I'm not positive. @mollfpr, would you mind taking a look?

**Comment by mollfpr** [comment] 2024-02-14 16:13
Yeah, that seems to be a backend issue but I'll have a look.

**Comment by mollfpr** [comment] 2024-02-16 19:41
Sorry for the delay, I'll get the test in the morning!

**Comment by mvtglobally** [comment] 2024-02-21 02:22
Issue not reproducible during KI retests. (First week)

**Comment by johncschuster** [comment] 2024-02-23 21:59
I'll apply the re-test label for one more week. If the behavior is not reproducible after that, let's close the issue.

**Comment by mvtglobally** [comment] 2024-02-27 15:06
Issue not reproducible during KI retests. (First week)

**Comment by luacmartins** [comment] 2024-02-27 15:56
I think we can close this. Please reopen if it happens again.

**Closed by luacmartins** 2024-02-27 15:56 UTC
Labels: External, Engineering, Daily, Needs Reproduction, Help Wanted, Bug, retest-weekly
