### ISSUE TITLE
[$1000] Once 2FA is set up (with Authenticator) and see the "Success!" screen, you're able to navigate back

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#20546] opened 2023-06-09 19:08 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
Precondition - User doesn't have 2FA setup
1. Open mobile app or desktop app
2. Tap on Profile icon
3. Tap on "Security"
4. Tap on "Two-factor authentication"
5. Tap on Copy codes / Download the codes
6. Tap on "Next"
7. Generate-Insert authenticator code
8. Tap on "Next"
9. Tap on "Back" arrow
10. Tap on "Back" arrow
11. Tap on "Copy codes" / Download

## Expected Result:
After properly setting up 2FA, a user SHOULD NOT be able to go back. We should end the flow once we see the "Success!" screen.

## Actual Result:
After setting up 2FA and seeing the "Success!" screen, users can go back.

At step 9, the user lands in the recovery codes tab, but recovery codes field is empty. When user taps on "Copy codes" nothing is copied. When user taps on "Download" - Nothing is downloaded. In Web - a text document is downloaded with a word "undefined" inside. None of these should happen!

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android / native
- [x] Android / Chrome
- [x] iOS / native
- [ ] iOS / Safari
- [x] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 1.3.26.1

**Reproducible in staging?:** Yes 

**Reproducible in production?:** Yes

**If this was caught during regression testing, add the test name, ID and link from TestRail:**

**Email or phone of affected tester (no customers):**

**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Notes/Photos/Videos:** Any additional supporting documentation

![Bug6087200_photo_2023-06-09_22-54-52](https://github.com/Expensify/App/assets/78819774/e6d23fbd-2a94-4546-9ec7-1e833dec70e8)

https://github.com/Expensify/App/assets/78819774/866ffaa1-0c52-4391-9792-fe8777883715

**Expensify/Expensify Issue URL:**

**Issue reported by:** Applause - Internal Team

**Slack conversation:**

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~0129603f889c33dd60</li>
        <li>Upwork Job ID: 1668993853088313344</li>
        <li>Last Price Increase: 2023-06-14</li>
    </ul>
</details>

**Comment by jliexpensify** [comment] 2023-06-13 00:59
I can recreate this on Staging, but I'm checking if this is intended behaviour - as you shouldn't be able to access recovery codes after you set up 2FA (the flow always dictates you should download them before you set up 2FA).

Thread - https://expensify.slack.com/archives/C01SKUP7QR0/p1686617834615589

**Comment by jliexpensify** [comment] 2023-06-13 04:20
After a solid discussion with @bondydaa (our resident 2FA expert), I'm assigning him this GH and re-writing this issue.

The TL;DR here is that once a user sets up 2FA, they shouldn't have the ability to go back, so we should actually fix this flow in New Expensify.

**Comment by jliexpensify** [comment] 2023-06-13 23:18
Bump @bondydaa for a review of my re-writes in the GH! Then this can go to External. Thanks!

**Comment by bondydaa** [comment] 2023-06-14 14:49
Any proposal should include how we will prevent a user from going back in the 2FA set up process. Your options are fully set up 2FA or bail out at any point and fully restart.

**Comment by jliexpensify** [comment] 2023-06-14 23:17
@bondydaa I had a quick read of the other issue, I think (?) it solves this one too. We could close this one in favour of https://github.com/Expensify/App/issues/19496, right?

**Comment by jliexpensify** [comment] 2023-06-18 22:18
Checked the other thread, @bondydaa has responded.  

Just checking - we could close this one in favour of https://github.com/Expensify/App/issues/19496, right?

**Comment by bondydaa** [comment] 2023-06-21 14:05
👍

**Closed by bondydaa** 2023-06-21 14:05 UTC
Labels: External, Daily, Help Wanted, Bug
