### ISSUE TITLE
[$500] Chat - After selecting"three" emoji, selecting "bowing man" or any emoji misplace "3" emoji

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#28203] opened 2023-09-26 00:30 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Launch app
2. Tap any report
3. Tap on emoji picker in compose
4.Search by typing "Th"
5.Select "three" emoji
6.Again tap on emoji picker and search by typing "Th"
7.Select green "bowing_man

## Expected Result:
After selecting"three" emoji, selecting "bowing man" or any emoji must not misplace "three" emoji

## Actual Result:
After selecting"three" emoji, selecting "bowing man" or any emoji misplace "three" emoji. After placing second emoji after "three" emoji, it can be seen "3" letter left to second emoji and "three" emoji background at right of second emoji

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android / native
- [ ] Android / Chrome
- [x] iOS / native
- [ ] iOS / Safari
- [ ] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 1.3.74-1

**Reproducible in staging?:** Yes

**Reproducible in production?:** Yes

**If this was caught during regression testing, add the test name, ID and link from TestRail:**

**Email or phone of affected tester (no customers):**

**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/78819774/f002e01f-d0a7-4474-b014-29ca10e81057

**Expensify/Expensify Issue URL:**

**Issue reported by:** Applause - Internal Team

**Slack conversation:**

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~013744e6d8e5e17813</li>
        <li>Upwork Job ID: 1706608667456933888</li>
        <li>Last Price Increase: 2023-09-26</li>
    </ul>
</details>

**Comment by bfitzexpensify** [comment] 2023-09-26 09:56
Reproduced, but only via Android native - seems like it's working as expected on iOS native for me

https://github.com/Expensify/App/assets/38236554/49ee205e-d5c0-4efe-93fb-999de0d767b9

**Comment by bfitzexpensify** [comment] 2023-09-28 16:34
OK, looks like https://github.com/Expensify/App/issues/26879 is being addressed via https://github.com/Expensify/App/issues/26709, and I suspect this will too, so closing this out.

**Closed by bfitzexpensify** 2023-09-28 16:34 UTC
Labels: External, Daily, Help Wanted, Overdue, Bug
