### ISSUE TITLE
Desktop - Login - "Please enter an email" message overlaps with the "Continue" button

### ISSUE THREAD

**Issue by IuliiaHerets** [Expensify/App#50062] opened 2024-10-02 13:31 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 9.0.43-0
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**Issue reported by:** Applause Internal Team

## Action Performed:
1. Navigate to https://staging.new.expensify.com/
2. Click on anywhere on the page to trigger the field validation error
3. Hover over the "Continue" button

## Expected Result:
There shouldn't be any overlapping and only one button should be showing.

## Actual Result:
"Please enter an email" message overlaps with the "Continue" button. "Continue" button doubles after hovering over it.

## Workaround:
Unknown

## Platforms:

- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [ ] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

https://github.com/user-attachments/assets/3aaca06d-dda1-432d-ab02-09154ed176c5

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Issue Owner</summary>Current Issue Owner: @jayeshmangwani</details>

**Comment by IuliiaHerets** [comment] 2024-10-02 13:31
@bfitzexpensify  FYI I haven't added the External label as I wasn't 100% sure about this issue. Please take a look and add the label if you agree it's a bug and can be handled by external contributors

**Comment by Tony-MK** [comment] 2024-10-07 17:28
Hey

**Comment by jayeshmangwani** [comment] 2024-10-08 06:14
There's no proposal here, and I’m unable to reproduce the issue. @bfitzexpensify, are you able to reproduce it?

**Comment by bfitzexpensify** [comment] 2024-10-08 07:52
Asking QA to retest

**Comment by kavimuru** [comment] 2024-10-08 16:50
Not reproducible

https://github.com/user-attachments/assets/b4b77303-4856-45e2-8db1-92ab82781027

**Comment by bfitzexpensify** [comment] 2024-10-08 16:50
Cool, ok, let's close this for the moment then

**Closed by bfitzexpensify** 2024-10-08 16:50 UTC
Labels: External, Daily, Help Wanted, Bug
