### ISSUE TITLE
[Awaiting Payment 2024-09-19][$250] [HIGH] Invoicing V1 - Archive B2B invoice room when the receiver workspace is deleted

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#47170] opened 2024-08-09 14:33 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 9.0.18-7
**Reproducible in staging?:** Y
**Reproducible in production?:** N
**If this was caught during regression testing, add the test name, ID and link from TestRail:** N/A
**Email or phone of affected tester (no customers):** applausetester+kh050806@applause.expensifail.com
**Issue reported by:** Applause - Internal Team

## Action Performed:
Precondition:
- User A is an admin of his workspace
- User B is an admin of his workspace
1. Go to staging.new.expensify.com
2. [User A] Send an invoice to User B
3. [User B] Go to invoice chat
4. [User B] Click pay button > Pay the invoice as business > Pay elsewhere
5. [User B] Delete all the workspaces
6. [User A] Send another invoice
7. [User A] Click on the invoice preview

## Expected Result:
Send invoice option should be hidden for User A because User B is no longer an admin of his workspace

## Actual Result:
User A can still send invoice to User B after User B deletes all the workspaces, which results in error.

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [x] Android: mWeb Chrome
- [x] iOS: Native
- [x] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details> 

https://github.com/user-attachments/assets/909d1f4c-e62b-487d-ab1d-50421fc3471b

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01903a726126738169</li>
        <li>Upwork Job ID: 1829110835274275153</li>
        <li>Last Price Increase: 2024-08-29</li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @</details>

**Comment by rlinoz** [comment] 2024-08-09 14:42
@lanitochka17 do you have the prod behavior by any chance?

**Comment by rlinoz** [comment] 2024-08-09 15:03
Hmmm did we just add the pay as business to invoices?

**Comment by rlinoz** [comment] 2024-08-09 15:06
We added it here https://github.com/Expensify/App/pull/44970, I think we should do something on the backend, let me check if we are already planning something.

**Comment by rlinoz** [comment] 2024-08-09 15:11
There is a section for it in the doc, but I don't see an issue for it. Anyway I am removing the Web-E deploy blocker label then.

**Comment by rlinoz** [comment] 2024-08-09 15:14
Asked in Slack https://expensify.slack.com/archives/CSL3XBCCR/p1723216392276109

**Comment by cristipaval** [comment] 2024-08-16 14:10
Work in progress

**Comment by cristipaval** [comment] 2024-08-19 10:39
Same, WIP.

**Comment by cristipaval** [comment] 2024-08-20 21:08
^Auth PR up for review

**Comment by cristipaval** [comment] 2024-08-22 11:11
PR still in review

**Comment by cristipaval** [comment] 2024-08-26 09:49
Just resolved the conflicts in the [Auth PR](https://github.com/Expensify/Auth/pull/12147).

**Comment by cristipaval** [comment] 2024-08-28 18:47
@VickyStash do you think you could work on this issue and do the App changes needed when the b2b room is archived?

**Comment by cristipaval** [comment] 2024-08-28 18:48
Also, @jjcoffee would you like to be assigned as the C+ for it?

**Comment by rezkiy37** [comment] 2024-08-28 19:05
Hi, I am Michael (Mykhailo) from Callstack, an expert agency and I can work on this issue.

**Comment by jjcoffee** [comment] 2024-08-29 07:31
@cristipaval Sure, I'd be happy to!

**Comment by jjcoffee** [comment] 2024-08-29 09:41
Just to note that I found a similar issue whilst testing [another](https://github.com/Expensify/App/pull/47862#issuecomment-2317086139) invoice rooms PR even if using the FAB to send an invoice personally to User B, the invoice will get added to User B's archived workspace invoice room.

1. [User A] Send an invoice to User B (who has no workspaces)
2. [User B] Pay invoice as business
3. [User B] Delete created workspace
4. [User A] Send another invoice to User B
5. Note there is an API request error: `A record already exists with this ID`, the request shows the same `invoiceRoomReportID` for the room created in (2).

**Comment by rezkiy37** [comment] 2024-08-29 10:33
> Just to note that I found a similar issue whilst testing [another](https://github.com/Expensify/App/pull/47862#issuecomment-2317086139) invoice rooms PR. If using the FAB to send an invoice personally to User B (so not using the inline `+` to send to the workspace directly), the invoice will get added to User B's archived workspace invoice room.
> 
> 1. [User A] Send an invoice to User B (who has no workspaces)
> 2. [User B] Pay invoice as business
> 3. [User B] Delete created workspace
> 4. [User A] Send another invoice to User B
> 5. Note there is an API request error: `A record already exists with this ID`, the request shows the same `invoiceRoomReportID` for the room created in (2).

@jjcoffee  This bug is not replicable, because User B cannot pay as a business in the current main or staging. https://github.com/Expensify/App/pull/47862 introduces this feature. cc @VickyStash 

<details><summary>Details</summary>


https://github.com/user-attachments/assets/a10fbc94-cfbc-4f08-b4c2-e288897f6f1d



</details>

**Comment by rezkiy37** [comment] 2024-08-29 10:41
I tested the bug and it is not replicable if the users are online and have a stable internet connection. The room was archived immediately once I deleted the workspace. 


<details><summary>Details</summary>

<img width="857" alt="Archived" src="https://github.com/user-attachments/assets/7f5e2034-624d-4f31-a536-fe61dca8367a">

<img width="852" alt="No policy" src="https://github.com/user-attachments/assets/c170f51b-476d-4f7d-be4f-60381b175678">

</details> 

I could reproduce the "bug" when User A is offline. It is expected because User A does not receive the latest updates until User A goes online. 

<details><summary>Details</summary>

https://github.com/user-attachments/assets/e9cb6b8d-c135-4163-9f16-6540b0a52746

</details> 

However, I tried to test the same flow with expense submission and I have the same error message when User A is offline.

<details><summary>Details</summary>

https://github.com/user-attachments/assets/098e470f-8813-42cf-b76b-016c5d0d755b

</details> 

So I would say that this is not a bug and this behavior is correct. WDYT @cristipaval?

**Comment by rezkiy37** [comment] 2024-08-29 10:57
> > Just to note that I found a similar issue whilst testing [another](https://github.com/Expensify/App/pull/47862#issuecomment-2317086139) invoice rooms PR. If using the FAB to send an invoice personally to User B (so not using the inline `+` to send to the workspace directly), the invoice will get added to User B's archived workspace invoice room.
> > 
> > 1. [User A] Send an invoice to User B (who has no workspaces)
> > 2. [User B] Pay invoice as business
> > 3. [User B] Delete created workspace
> > 4. [User A] Send another invoice to User B
> > 5. Note there is an API request error: `A record already exists with this ID`, the request shows the same `invoiceRoomReportID` for the room created in (2).
> 
> @jjcoffee This bug is not replicable, because User B cannot pay as a business in the current main or staging. #47862 introduces this feature. cc @VickyStash
> 
> Details

The bug is replicable in staging, **but** only if user B already has a workspace to pay as a business. This logic is presented in staging. 

<details><summary>Details</summary>

<img width="880" alt="Screenshot 2024-08-29 at 12 53 53" src="https://github.com/user-attachments/assets/c0073a83-65d8-4a9d-8e9f-d46129c37fca">

<img width="1218" alt="Screenshot 2024-08-29 at 12 50 24" src="https://github.com/user-attachments/assets/ae206a30-6d42-4fa1-bb9f-5928be128d6e">

</details>

**Comment by cristipaval** [comment] 2024-08-29 10:58
@rezkiy37, sorry for the lack of context. I fixed the original bug in the backend.

**Comment by rezkiy37** [comment] 2024-08-29 11:06
> So you need to:
> 
> 1. Send an invoice to a user who is an admin of their primary workspace
> 2. Pay as business (so that the invoice room is upgraded to b2b)
> 3. Now the receiver deletes the workspace and the invoice room is archived
> 4. The sender now opens the invoice room (which is archived).
> 5. The App crashes

@cristipaval  The staging does not crash for me, but I can send invoices to the archived invoice room. I will fix this because the app attaches the incorrect `reportID`. 

<details><summary>Details</summary>
<p>


https://github.com/user-attachments/assets/3bc7d1d1-351b-498a-9196-bd4bed85727a


https://github.com/user-attachments/assets/45831def-a31b-4630-974c-d9d2edec82e2



</p>
</details>

**Comment by rezkiy37** [comment] 2024-08-29 15:16
@jjcoffee Yes, I am fixing it in the scope of the upcoming PR.

**Comment by rezkiy37** [comment] 2024-09-02 14:37
Discussing with @cristipaval in [Slack](https://callstack-hq.slack.com/archives/C06SPA2JTPC/p1725266561775799?thread_ts=1724871025.002419&cid=C06SPA2JTPC).

**Comment by rezkiy37** [comment] 2024-09-03 16:23
Hey!
I will be OOO from 04.09 (_afternoon_) till 09.09. I will continue to work on this one once I am back.

**Comment by isabelastisser** [comment] 2024-09-03 18:33
Thanks for the update!

**Comment by rezkiy37** [comment] 2024-09-04 07:15
Hey! 
I've opened the PR (https://github.com/Expensify/App/pull/48275) for review because the app's side is ready. One small backend improvement left. Discussion in [Slack](https://callstack-hq.slack.com/archives/CSL3XBCCR/p1725317870925789).

**Comment by jjcoffee** [comment] 2024-09-10 07:52
@isabelastisser Looks like @cristipaval is on parental leave at the moment, is it possible to get another engineer assigned to review the PR?

**Comment by isabelastisser** [comment] 2024-09-10 19:28
@rlinoz, any chance you can review the PR since Cristi is on leave? TIA!

**Comment by rlinoz** [comment] 2024-09-10 19:35
Sure, on it.

**Comment by rlinoz** [comment] 2024-09-13 12:51
This has been deployed to prod https://github.com/Expensify/App/pull/48275#issuecomment-2347262503

**Comment by jjcoffee** [comment] 2024-09-19 14:28
Since this is a `CRITICAL` feature for invoicing, I believe it also qualifies for $500 compensation, as on the other critical [invoicing](https://github.com/Expensify/App/issues/40438#issuecomment-2296189448) issues I worked on. cc @isabelastisser

**Comment by jjcoffee** [comment] 2024-09-19 14:34
**Regression Test Proposal**

1. User A: Send an invoice to user B.
2. User B: Open the invoice and select to `Pay as business`. The invoice room will be upgraded to a B2B invoice room.
3. User B: Delete the workspace.
4. User A and User B: Open the invoice room and verify that the footer message is `This chat is no longer active because ${policyName} is no longer an active workspace.`
5. User A: Send another invoice to user B from the same workspace.
6. User A and user B: Verify that the app creates a new invoice room.

Do we agree 👍 or 👎

**Comment by isabelastisser** [comment] 2024-09-19 15:00
Thanks, @jjcoffee! Offer sent in Upwork.

**Comment by isabelastisser** [comment] 2024-09-19 15:05
All set!

**Closed by isabelastisser** 2024-09-19 15:05 UTC
Labels: External, Engineering, Weekly, Awaiting Payment, Bug

**Comment by jjcoffee** [comment] 2024-09-19 15:13
@isabelastisser Offer accepted, thanks!
