### ISSUE TITLE
[$500] Workspace - In #announceroom, split bill reports display as loading for workspace members.

### ISSUE THREAD

**Issue by izarutskaya** [Expensify/App#27154] opened 2023-09-11 14:27 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Login with user A's account.
2. Open workspace
3. Invite user B to the workspace.
4. Open the #announceroom chat.
5. Spilt bill with workspace members
6. Login with user B's account.
7. Open the #announceroom chat in B's workspace.
8. Notice that the split bill reports are stuck on the loading screen for workspace members.

## Expected Result:
after splitting bills, the split bill report should not be displayed as loading for workspace members.

## Actual Result:
 after splitting the bill, the split bill report is displayed as loading for workspace members.

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [x] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** v1.3.67-1

**Reproducible in staging?:** Y

**Reproducible in production?:** Y

**If this was caught during regression testing, add the test name, ID and link from TestRail:**

**Email or phone of affected tester (no customers):**

**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/115492554/95fb7e7c-18e2-4046-8b3d-9f01a36bc3d8

https://github.com/Expensify/App/assets/115492554/d21c0e7c-cd3d-4310-b845-5a2e016b0c4f

**Expensify/Expensify Issue URL:**

**Issue reported by:** @Ad-eeb

**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1693924728887059

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01100fea2e9b78b3b8</li>
        <li>Upwork Job ID: 1701244048739500032</li>
        <li>Last Price Increase: 2023-09-25</li>
<li>Automatic offers: </li>
<ul>
<li>situchan | Contributor | 26874200</li>
<li>Ad-eeb | Reporter | 26874202</li>
</ul></li>
    </ul>
</details>

**Comment by alitoshmatov** [comment] 2023-09-11 15:48
Backend is not sending transaction data.

Here inside `originalMessage` there is a `IOUTransactionID` but this data is not sent from pusher.
<img width="742" alt="Screenshot 2023-09-11 at 20 47 08" src="https://github.com/Expensify/App/assets/59907218/fca8c543-afb3-4bc1-a105-914849dfc145">

**Comment by adelekennedy** [comment] 2023-09-14 06:31
@abdulrahuman5196 should this be internal?

**Comment by adelekennedy** [comment] 2023-09-18 09:05
@abdulrahuman5196 bump on the above

**Comment by salonikumawat28** [comment] 2023-09-20 17:38
I looked into this issue and it seems like there needs to be changes in BE as well.
Here is an explanation:
When Person1 create split bill for 2 persons(Person1 and Person2), 3 transaction ids are there in total:
1. Split transaction id representing the overall split
https://github.com/Expensify/App/blob/5ec6105d3b849565c48f1187c78c051fda5e02c6/src/libs/actions/IOU.js#L1013-L1018
3. Transaction id for person1 - As person1 only created the split, we dont create the transaction id in the client side. BE returns the transaction id for person1 in response.
https://github.com/Expensify/App/blob/5ec6105d3b849565c48f1187c78c051fda5e02c6/src/libs/actions/IOU.js#L880
5. Transaction id for person2 - For all other persons involved in split, we add all the data including transaction id:
https://github.com/Expensify/App/blob/5ec6105d3b849565c48f1187c78c051fda5e02c6/src/libs/actions/IOU.js#L994-L1007

When we send the API.write request, as response BE sends a new transaction id for person1 but incorrectly marks the split transaction id as the original transaction id of person1. Split transaction id is lost in BE because of this corruption. Here is snippet of example request payload and response which shows this problem:
```
REQUEST:

reportID: 2675033063704124
amount: 130000
splits: [{"email":"545saloni+3@gmail.com","accountID":15694778,"amount":65000},{"email":"545saloni+4@gmail.com","accountID":15705003,"amount":65000,"iouReportID":"6189850050239895","chatReportID":"7536945066043077","transactionID":"1898044165078485633","reportActionID":"4880171455368989281","createdChatReportActionID":"7280778505637454476","createdIOUReportActionID":"3788054532130349476","reportPreviewReportActionID":"6883759768728262211"}]
currency: GBP
transactionID: 2381798152516133750
reportActionID: 3602112367821823958
policyID: 57A98B2EBCCAEEAD
apiRequestType: write
email: 545saloni+3@gmail.com
```

and:
```
RESPONSE:

{
    "jsonCode": 200,
    "requestID": "809bd0a7fc3e886e-LHR",
    "onyxData": [
        {
            "onyxMethod": "merge",
            "key": "transactions_1898044165078485633",
            "value": {
                "amount": 65000,
                "category": "",
                "comment": {
                    "comment": "",
                    "originalTransactionID": "2381798152516133750",
                    "source": "split"
                },
                "created": "2023-09-20 17:33:43",
                "currency": "GBP",
                "filename": "",
                "merchant": "Request",
                "modifiedAmount": 0,
                "modifiedCreated": "",
                "modifiedCurrency": "",
                "modifiedMerchant": "",
                "receipt": [],
                "reportID": "6189850050239895",
                "tag": "",
                "transactionID": "1898044165078485633"
            }
        }
    ]
}
```

Other clients never gets the split transaction id. Even the same person1 when logs out and logs in, they will no longer see split transaction id. Announce rooms shows the overall split transaction. So we see the issue in announce room.

**Comment by adelekennedy** [comment] 2023-09-21 10:18
added the engineering label by mistake - at ease @dangrous

**Comment by adelekennedy** [comment] 2023-09-21 10:20
bumped in Slack

**Comment by situchan** [comment] 2023-09-25 16:07
It seems no C+ assigned here. I can help this move forward.

**Comment by adelekennedy** [comment] 2023-09-26 01:36
just assigned you @situchan

**Comment by adelekennedy** [comment] 2023-09-29 05:29
@situchan I think we only have the one proposal above to review

**Comment by situchan** [comment] 2023-09-29 07:19
I don't see any former proposal yet.
@salonikumawat28 can you please follow proposal template so you should re-state title, explain the correct root cause and suggest solution.
I don't think this happens only on #announce room but all group chats where split bill is applicable.

**Comment by salonikumawat28** [comment] 2023-10-02 09:39
@situchan I didn't give formal proposal because I think the changes needs to be in backend. I explained the reasoning behind it in my comment above. I have [updated](https://github.com/Expensify/App/issues/27154#issuecomment-1728172346) my comment above to make it more clear.

**Either the changes should be in backend and if so, the issue should be internal. Otherwise, its possible that we are not creating the API request as backend expects.** For the latter case, can you point me where to find the API schema of `SplitBill` so that I can make sure we are making correct API request.

**Comment by adelekennedy** [comment] 2023-10-02 09:44
update above

**Comment by situchan** [comment] 2023-10-09 11:28
@salonikumawat28 are you still able to reproduce this?

**Comment by situchan** [comment] 2023-10-12 11:53
> @salonikumawat28 are you still able to reproduce this?

bump ^

**Comment by salonikumawat28** [comment] 2023-10-13 07:41
@situchan Sorry for late response. I can still reproduce this. I tried it on `staging.new.expensify.com`

**Comment by adelekennedy** [comment] 2023-10-16 19:25
Still is reproducible, but @situchan re-reading this how big of a problem is this? There's been so little movement here I think we should close and pay out some percentage for reviewing proposals

**Comment by situchan** [comment] 2023-10-16 19:51
I think this bug cannot be be simply ignored.
@youssef-lr should backend send transaction data in pusher?

**Comment by adelekennedy** [comment] 2023-10-19 15:48
@youssef-lr bump on the above!

**Comment by youssef-lr** [comment] 2023-10-23 21:28
@adelekennedy sorry I missed your ping.

> I think this bug cannot be be simply ignored.
@youssef-lr should backend send transaction data in pusher?

Correct @situchan, this is a duplicate of https://github.com/Expensify/App/issues/27200 which I have created a backend PR for. So I'll be closing this one.

**Closed by youssef-lr** 2023-10-23 21:28 UTC
Labels: Engineering, Daily, Internal, Overdue, Bug
