### ISSUE TITLE
[HOLD for payment 2024-06-03] Onboarding - Task description from onboarding is not rendered with mark down

### ISSUE THREAD

**Issue by m-natarajan** [Expensify/App#42351] opened 2024-05-17 18:18 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.74-4
**Reproducible in staging?:** y
**Reproducible in production?:** no
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** Applause internal team
**Slack conversation:**

## Action Performed:
1. Go to staging.new.expensify.com
2. Log in with a new Gmail account.
3. During onboarding, click "Manage my team's expenses".
4. Complete the onboarding.
5. In Concierge chat, click "Meet your setup specialist".

## Expected Result:
The task description will be rendered in mark down.

## Actual Result:
The task description is not rendered in mark down.
This issue is only reproduced from onboarding, not reproducible when manually creating a task with marked down description.
## Workaround:
unknown
## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [x] Android: mWeb Chrome
- [x] iOS: Native
- [x] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

https://github.com/Expensify/App/assets/38435837/c17da754-7be1-4918-b5b3-21b7d1d077c8

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Issue Owner</summary>Current Issue Owner: @puneetlath</details>

**Comment by m-natarajan** [comment] 2024-05-17 18:19
@puneetlath FYI I haven't added the External label as I wasn't 100% sure about this issue. Please take a look and add the label if you agree it's a bug and can be handled by external contributors

**Comment by m-natarajan** [comment] 2024-05-17 18:19
We think that this bug might be related to  #vip-vsb

**Comment by thienlnam** [comment] 2024-05-18 01:13
Looks like it might be from https://github.com/Expensify/App/pull/40625

**Comment by bernhardoj** [comment] 2024-05-18 04:17
PR is [here](https://github.com/Expensify/App/pull/42359) 

cc: @abdulrahuman5196

**Comment by abdulrahuman5196** [comment] 2024-06-04 19:44
@puneetlath We can close this. Seems to be a regression fix.

**Closed** 2024-06-04 19:45 UTC
Labels: Engineering, Daily, Overdue, Awaiting Payment, Bug
