### ISSUE TITLE
[HOLD for payment 2024-07-22] [HOLD for payment 2024-07-17] Report fields - "title" report field shows up and app crashes when clicking on checkbox.

### ISSUE THREAD

**Issue by m-natarajan** [Expensify/App#44797] opened 2024-07-04 03:11 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 9.0.4.0
**Reproducible in staging?:** y
**Reproducible in production?:** no, new feature
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** applause internal team
**Slack conversation:**

## Action Performed:
1. Go to staging.new.expensify.com
2. Go to Account settings.
3. Create a new workspace.
4. Quickly go to More features and enable Report fields.
5. Note that "title" report field appears. (might need to repeat Step 3 to 5 a few times)
6. Click on the "title" checkbox.

## Expected Result:
"title" report field will not show up and app will not crash when clicking on the checkbox.

## Actual Result:
"Title" report field shows up and app crashes when clicking on the checkbox.

## Workaround:
unknown
## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [x] Android: mWeb Chrome
- [x] iOS: Native
- [x] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

[Bug6532499_1720042271423!crash.txt](https://github.com/user-attachments/files/16092871/Bug6532499_1720042271423.crash.txt)

https://github.com/Expensify/App/assets/38435837/d9889ff0-d203-48ef-91b0-1ff627be6b6a

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Issue Owner</summary>Current Issue Owner: @slafortune</details>

**Comment by m-natarajan** [comment] 2024-07-04 03:12
@slafortune FYI I haven't added the External label as I wasn't 100% sure about this issue. Please take a look and add the label if you agree it's a bug and can be handled by external contributors

**Comment by m-natarajan** [comment] 2024-07-04 03:12
We think that this bug might be related to #vip-vsb

**Comment by mountiny** [comment] 2024-07-04 10:05
@rezkiy37 @waterim Can you please check this out?

**Comment by waterim** [comment] 2024-07-04 10:07
Hello, Im Artem from Callstack and would like to help with this issue as it was my filter and it should be adjusted

**Comment by mountiny** [comment] 2024-07-04 10:20
@nyomanjyotisa thanks for the proposal, but this feature is being worked on by Callstack and its behind beta, since their PR has caused this regression, they will work on the fix

**Comment by waterim** [comment] 2024-07-04 17:06
@mountiny This one will be addressed [here](https://github.com/Expensify/App/pull/44493)

**Comment by mountiny** [comment] 2024-07-04 22:36
@waterim thanks, I have linked the PR to this issue

**Comment by slafortune** [comment] 2024-07-18 15:54
@rushatgabhane @shubham1206agra can you please complete the checklist?

**Comment by mountiny** [comment] 2024-07-19 23:54
@slafortune this is a new feature and we are handling all these cases as part of the report fields configuration project so I think we can close this issue now, payments are done per project

**Closed by mountiny** 2024-07-19 23:54 UTC
Labels: Engineering, Daily, Awaiting Payment, Bug
