### ISSUE TITLE
[ON HOLD] [$500] Split - Error above split button disappears when merchant is not entered

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#35667] opened 2024-02-02 14:08 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.3.45-5
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**If this was caught during regression testing, add the test name, ID and link from TestRail:** https://expensify.testrail.io/index.php?/tests/view/4264387
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** Applause - Internal Team
**Slack conversation:**

## Action Performed:
1, Go to workspace chat
2. Click + > Split bill
3. Create a bill split with an invalid receipt
4. When the scanning fails, click on the split preview
5. Click Amount
6. Enter amount and save

## Expected Result:
The error above split button will remain as not all the required fields (Merchant) are entered

## Actual Result:
The error above split button disappears when merchant is not entered

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [x] Android: mWeb Chrome
- [x] iOS: Native
- [x] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details>  

https://github.com/Expensify/App/assets/78819774/ebe8ed04-5b58-4386-a13e-9edc3f616478

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01e2368e0550fbbb4b</li>
        <li>Upwork Job ID: 1753420140902309888</li>
        <li>Last Price Increase: 2024-02-23</li>
    </ul>
</details>

**Comment by lanitochka17** [comment] 2024-02-02 14:09
We think that this bug might be related to [#vip-split-p2p-chat-groups](https://expensify.enterprise.slack.com/archives/C05RECHFBEW)

**Comment by bernhardoj** [comment] 2024-02-02 14:38
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
The required fields error disappears after we update the amount of a failed split bill.

### What is the root cause of that problem?
One of the condition for the error to show is the transaction missing required fields data.
https://github.com/Expensify/App/blob/8f5889874f36735a66f55efc7522bd67c2173d3e/src/components/MoneyRequestConfirmationList.js#L282
https://github.com/Expensify/App/blob/8f5889874f36735a66f55efc7522bd67c2173d3e/src/libs/TransactionUtils.ts#L167-L169

The merchant is only required if it's an expense request and it should be true for our case. It checks the report from the transaction reportID, but in the split case, the report ID is a constant of -2.

https://github.com/Expensify/App/blob/8f5889874f36735a66f55efc7522bd67c2173d3e/src/libs/actions/IOU.js#L1418-L1421

This is because a split request doesn't have an IOU report.

So, the expense request check is always false and updating the amount is enough to remove the required fields error message. 
### What changes do you think we should make in order to solve the problem?

Instead of relying on the transaction report ID, we can pass the value from the params.

```
areRequiredFieldsEmpty(transaction, isFromExpenseReport)
```

https://github.com/Expensify/App/blob/8f5889874f36735a66f55efc7522bd67c2173d3e/src/components/MoneyRequestConfirmationList.js#L282

and we can pass props.isPolicyExpenseChat as the value.

_or we can keep the parent report type check and the new param, so we will rely on 2 values_

**Comment by alexpensify** [comment] 2024-02-02 22:25
@abdulrahuman5196 when you get a chance, let us know if this proposal will fix this issue. Thanks!

**Comment by abdulrahuman5196** [comment] 2024-02-05 13:54
Will work on review today

**Comment by alexpensify** [comment] 2024-02-06 00:21
Thank you!

**Comment by alexpensify** [comment] 2024-02-07 23:50
@abdulrahuman5196 - any news about these proposals?

**Comment by abdulrahuman5196** [comment] 2024-02-08 19:39
Hi, Sorry for the delay. Will take care of this in my morning or will re-assign tomorrow night.

**Comment by alexpensify** [comment] 2024-02-09 17:59
Thank you for the update!

**Comment by abdulrahuman5196** [comment] 2024-02-12 05:55
Reviewing now

**Comment by abdulrahuman5196** [comment] 2024-02-12 06:13
@lanitochka17 @alexpensify I am seeing a different behaviour now. I don't get any error initially and only merchant shows error and the split option is disabled. The split option stays disabled until I enter the amount and merchant information.

Does the OP expectation apply here as well? Like we should show the error message until split button is disabled for some error scenario?



https://github.com/Expensify/App/assets/46707890/3f9557ee-f045-4765-be50-dfb82130100e



cc: @bernhardoj Kindly do check and update the proposal if required.

**Comment by bernhardoj** [comment] 2024-02-12 10:02
When the scan fails, the BE now sends a DELETED state instead of SCANFAILED.

<img width="353" alt="image" src="https://github.com/Expensify/App/assets/50919443/0041052e-8d89-4a28-b9bd-5a90b5e3ee3f">

So, the condition here always fails.
https://github.com/Expensify/App/blob/55af216a88233694e1e45117eeb0ff2ddde82480/src/components/MoneyRequestConfirmationList.js#L282

But you can still see the issue where the merchant field shows an error but the error doesn't show above the split button

**Comment by alexpensify** [comment] 2024-02-12 16:31
@abdulrahuman5196 - should we start a discussion in the Slack room to confirm the process for this one?

**Comment by mvtglobally** [comment] 2024-02-13 04:58
Issue not reproducible during KI retests. (First week)

**Comment by abdulrahuman5196** [comment] 2024-02-14 18:33
@alexpensify  yes. We should check internally

**Comment by alexpensify** [comment] 2024-02-14 19:22
Will do! I'll start one soon.

**Comment by alexpensify** [comment] 2024-02-15 23:59
@abdulrahuman5196 - Since this one didn't appear in recent retests and you noticed a difference in behaviors. I'm going to put this one on hold and we can confirm next week if we should close.

**Comment by alexpensify** [comment] 2024-02-23 00:05
Still on hold

**Comment by alexpensify** [comment] 2024-02-28 00:30
I'm going to close since this issue appears to have stopped.

**Closed by alexpensify** 2024-02-28 00:30 UTC
Labels: External, Weekly, Help Wanted, Bug

**Comment by alexpensify** [comment] 2024-03-05 18:02
I checked and this notice is related to https://github.com/Expensify/App/issues/34916#issuecomment-1905293484 -- not this GH. No action is required here.
