### ISSUE TITLE
Group member's name appears in the "Assign to me" section

### ISSUE THREAD

**Issue by m-natarajan** [Expensify/App#36779] opened 2024-02-19 01:15 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:**
**Reproducible in staging?:** needs reproduction
**Reproducible in production?:** needs reproduction
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** @jamesdeanexpensify 
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1708034273291579
 
## Action Performed:
1. Create a group chat with 2 more members
2. Have lots chats in the group
3. Tap + Assign task 
4. Enter title
5. In the confirm task page tap Assignee
6. Observe the invite page 

## Expected Result:
Only creator's details should appear in "assign to me" section

## Actual Result:
Group member's name appears 

## Workaround:
unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [x] iOS: Native
- [ ] iOS: mWeb Safari
- [ ] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence
![image](https://github.com/Expensify/App/assets/38435837/dbe21d21-2eac-4ba1-99ee-193131157e4b)

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by kevinksullivan** [comment] 2024-02-21 23:07
@jamesdeanexpensify have you seen this again? I can't reproduce on my end, using group chats with lotsa previous messages.

**Comment by jamesdeanexpensify** [comment] 2024-02-22 01:46
Oh nice! I don't see it anymore. That's great. Should we close this out for now?

**Comment by kevinksullivan** [comment] 2024-02-22 19:07
yup, let's close until we see it again!

**Closed by kevinksullivan** 2024-02-22 19:07 UTC
Labels: Daily, Needs Reproduction, Bug
