### ISSUE TITLE
[Closed & Archived] Use private_isArchived instead of report state/status to determine archived behavior in App

### ISSUE THREAD

**Issue by srikarparsi** [Expensify/App#45658] opened 2024-07-18 04:16 UTC
We want to separate archived behavior from closed state/status. To do this, we introduced a new rNVP private_isArchived in the backend. Currently this is being sent in the reports Onyx collection but in the future this will be stored in a new reportsNameValuePairs collection.

We need to start using the private_isArchived rNVP instead of the closed state/status in the frontend

More info about temporarily using the report collection instead of creating the reportNameValuePairs collection [here](https://expensify.slack.com/archives/C036QM0SLJK/p1721204584528099?thread_ts=1721057168.923999&cid=C036QM0SLJK)

**Comment by hungvu193** [comment] 2024-07-18 06:32
@srikarparsi  Since I reviewed linked PR, can you please assign me to this issue?

**Comment by srikarparsi** [comment] 2024-07-19 20:00
Hi @Christinadobrzyn! @hungvu193 helped review this [PR](https://github.com/Expensify/App/pull/45568), do you think you could help with payment whenever you get a chance?

**Comment by Christinadobrzyn** [comment] 2024-07-22 19:26
hi! Yes, happy to pay this out - just checking as a deploy blocker is showing. Is that accurate for this job? 

@hungvu193 are you paid through Upwork?

**Comment by hungvu193** [comment] 2024-07-23 02:56
> hi! Yes, happy to pay this out - just checking as a deploy blocker is showing. Is that accurate for this job?

It's not a blocker however it's still in debate (https://github.com/Expensify/App/issues/45829#issuecomment-2241764314)
> 
> @hungvu193 are you paid through Upwork?

I'll request on ND 😄

**Comment by srikarparsi** [comment] 2024-07-23 04:07
> hi! Yes, happy to pay this out - just checking as a deploy blocker is showing. Is that accurate for this job?

Thanks! We should pay @hungvu193 the full amount for reviewing because we will most likely close out both the blockers as expected behavior based on this [thread](https://expensify.slack.com/archives/C01GTK53T8Q/p1721483271237909).

**Comment by Christinadobrzyn** [comment] 2024-07-23 22:55
Sounds good! Thank you @srikarparsi and @hungvu193! 

Payment summary: 

Payouts due:

- Contributor+: $250 @hungvu193 (paid through NewDot)

Do we need a regression test?

**Comment by srikarparsi** [comment] 2024-07-23 23:02
The current tests cover this since this is just a refactor. So we should be good here :)

**Comment by Christinadobrzyn** [comment] 2024-07-23 23:06
Awesome! Thanks @srikarparsi! 

This is ready for payment based on this [payment summary](https://github.com/Expensify/App/issues/45658#issuecomment-2246439263). 

Since payment is only in NewDot, we can close this whenever is best.

**Comment by Christinadobrzyn** [comment] 2024-07-25 19:11
I'm going to close this out, but let me know if we need to keep it open for any reason!

**Closed by Christinadobrzyn** 2024-07-25 19:11 UTC
Labels: Reviewing, Daily, Bug

**Comment by hungvu193** [comment] 2024-07-30 03:30
Requested on ND

**Comment by JmillsExpensify** [comment] 2024-07-30 18:50
$250 approved for @hungvu193
