### ISSUE TITLE
[C+ Checklist Needs Completion] [$250] Send invoice - Workspaces in sender list are not arranged in alphabetical order

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#41340] opened 2024-04-30 15:05 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.68-0
**Reproducible in staging?:** Y 
**Reproducible in production?:** N
**If this was caught during regression testing, add the test name, ID and link from TestRail:** N/A
**Issue reported by:** Applause - Internal Team

## Action Performed:
Precondition:
- User has several workspaces with custom workspace name
- The workspaces are renamed randomly (eg, first workspace is renamed to R and second workspace is renamed to A, instead of first workspace is renamed to A and the second workspace is renamed to R)
1. Go to staging.new.expensify.com
2. Go to FAB > Send invoice.
3. Enter amount and select participant.
4. In confirmation page, click on the workspace.
Applause's Workspace -> C
Applause's Workspace 1 -> A
Applause's Workspace 2 -> B

## Expected Result:
The workspaces will be arranged in alphabetical order

## Actual Result:
The workspaces will be arranged in alphabetical order

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [x] Android: mWeb Chrome
- [x] iOS: Native
- [x] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details> 

https://github.com/Expensify/App/assets/78819774/9c272caf-0deb-4d74-bccc-902dfd2e0125

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01cb4574300d46ea26</li>
        <li>Upwork Job ID: 1785371086797258752</li>
        <li>Last Price Increase: 2024-05-07</li>
<li>Automatic offers: </li>
<ul>
<li>akinwale | Reviewer | 0</li>
<li>ShridharGoel | Contributor | 0</li>
</ul></li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @greg-schroeder</details>

**Comment by lanitochka17** [comment] 2024-04-30 15:07
@AndrewGable  FYI I haven't added the External label as I wasn't 100% sure about this issue. Please take a look and add the label if you agree it's a bug and can be handled by external contributors

**Comment by cristipaval** [comment] 2024-04-30 15:12
#vip-billpay related. Definitely not a blocker, not even sure if this is a bug, cc @danielrvidal

**Comment by danielrvidal** [comment] 2024-04-30 20:25
Solid clean-up, marking this as low as I don't think it's material to actually using it.

**Comment by danielrvidal** [comment] 2024-05-01 04:48
Confirmed the order should be alphabetical btw!

**Comment by AndrewGable** [comment] 2024-05-02 21:55
@akinwale - Let me know what you think

**Comment by akinwale** [comment] 2024-05-05 10:10
After reviewing the proposals, I believe we can move forward with @ShridharGoel's [proposal](https://github.com/Expensify/App/issues/41340#issuecomment-2085884963), since it takes into account that the selected workspace should always be prioritised as the first workspace, before sorting the rest below in alphabetical order.

🎀👀🎀 C+ reviewed.

**Comment by greg-schroeder** [comment] 2024-05-09 05:46
Bump @AndrewGable can you confirm the contributor assignment [here](https://github.com/Expensify/App/issues/41340#issuecomment-2094736955)?

**Comment by greg-schroeder** [comment] 2024-05-22 00:22
[PR](https://github.com/Expensify/App/pull/42048) is still in review

**Comment by greg-schroeder** [comment] 2024-06-13 22:33
Processing

**Comment by greg-schroeder** [comment] 2024-06-13 22:33
Payment summary:

Contributor: @ShridharGoel - $250 - paid via Upwork
C+: @akinwale - $250 - paid via Upwork

**Comment by greg-schroeder** [comment] 2024-06-13 22:34
@akinwale can you take care of [the checklist](https://github.com/Expensify/App/issues/41340#issuecomment-2152283616) so we can close this out? Thanks!

**Comment by akinwale** [comment] 2024-06-16 01:14
> * [x]  [@akinwale] The PR that introduced the bug has been identified. Link to the PR:
> * [x]  [@akinwale] The offending PR has been commented on, pointing out the bug it caused and why, so the author and reviewers can learn from the mistake. Link to comment:
> * [x]  [@akinwale] A discussion in #expensify-bugs has been started about whether any other steps should be taken (e.g. updating the PR review checklist) in order to catch this type of bug sooner. Link to discussion:

Not exactly a regression. This is more of a feature which wasn't specifically implemented.

> * [x]  [@akinwale] Determine if we should create a regression test for this bug.
> * [x]  [@akinwale] If we decide to create a regression test for the bug, please propose the [regression test](https://github.com/Expensify/App/blob/main/contributingGuides/REGRESSION_TEST_BEST_PRACTICES.md) steps to ensure the same bug will not reach production again.

**Regression Test Steps**
1. Launch the Expensify app.
2. Click on the global create FAB and select Send Invoice.
3. Specify an amount and select a participant.
4. Click on the workspace on the confirmation page.
5. Verify that the currently selected workspace is at the top of the list.
6. Verify that the other workspaces below the selected workspace are arranged in alphabetical order.

Do we agree 👍 or 👎?

**Comment by akinwale** [comment] 2024-06-16 01:14
> @akinwale can you take care of [the checklist](https://github.com/Expensify/App/issues/41340#issuecomment-2152283616) so we can close this out? Thanks!

@greg-schroeder Done!

**Comment by greg-schroeder** [comment] 2024-06-17 02:07
Thanks! filing regression test and closing

**Closed by greg-schroeder** 2024-06-17 02:07 UTC
Labels: External, Engineering, Daily, Overdue, Awaiting Payment, Bug
