### ISSUE TITLE
[HOLD for payment 2023-11-22] [$500] iOS - Members - When scrolling members WS list goes under the "background image"

### ISSUE THREAD

**Issue by izarutskaya** [Expensify/App#30428] opened 2023-10-26 11:34 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Issue found when executind PR:** https://github.com/Expensify/App/pull/30171
**Version Number:** 1.3.91-0
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** Applause-Internal Team
**Slack conversation:** @

## Action Performed:
rerequisites:
A WS must be created in the account

Steps:
1. Open New Expensify app
2. Log in with an expensifail account
3. Navigate to the WS settings
4. Navigate to Members
5. Invite 4 members
6. In the Members section, scroll through the list of members

## Expected Result:
When scrolling through members, the WS list should not be missing or cut off

## Actual Result:
When scrolling members WS list goes under the "background image"

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [x] iOS: Native
- [ ] iOS: mWeb Safari
- [ ] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos
<details>
<summary>Android: Native</summary>

</details>

<details>
<summary>Android: mWeb Chrome</summary>

</details>

<details>
<summary>iOS: Native</summary>

https://github.com/Expensify/App/assets/115492554/37eeddab-79c8-4d97-af5f-90a2824395cf

</details>

<details>
<summary>iOS: mWeb Safari</summary>

</details>

<details>
<summary>MacOS: Chrome / Safari</summary>

</details>

<details>
<summary>MacOS: Desktop</summary>

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01c024409da152917d</li>
        <li>Upwork Job ID: 1717505060463128576</li>
        <li>Last Price Increase: 2023-11-02</li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @adelekennedy</details>

**Comment by esh-g** [comment] 2023-10-26 12:31
# Proposal

## Please re-state the problem we are trying to solve
iOS - Members - When scrolling members WS list goes under the background content.

## What is the root cause of this problem?
The root cause is that the height of the `SectionList` is limited to the content it has, therefore, when we scroll, it gets cut off at the edges.

Moreover, we allow the list on `iOS` to 'bounce' which means that we are able to scroll past the content which is not what we do for android and web.

## What changes should be made to fix this?
We should add the prop `bounces={false}` to be more consistent with other platforms to the `SectionList` here:
https://github.com/Expensify/App/blob/414d5913999f69d83ab08b6ae6e03325c9ede549/src/components/SelectionList/BaseSelectionList.js#L418

This means that we are not able to scroll under the header part as well.

**Comment by hungvu193** [comment] 2023-10-26 17:01
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
When scrolling in members page, user list get cut off at the bottom.
### What is the root cause of that problem?
We're using `BaseSectionList` for our WorkspaceMembersPage, and it has style `styles.flexGrow0`, it will make the list only take its available space, however in IOS the `bounce` is true by default, so the list can be scroll up and down in its space, which caused the issue.
https://github.com/Expensify/App/blob/9e50be49a4831bb5d7699e5032cbc3487f956f16/src/components/SelectionList/BaseSelectionList.js#L437
### What changes do you think we should make in order to solve the problem?

Change the style of `SectionList` to `styles.flexGrow1` or `styles.flex1` to make it fill all the available space.
### What alternative solutions did you explore? (Optional)
N/A

**Comment by adelekennedy** [comment] 2023-10-30 17:32
@0xmiroslav a few proposals to review above

**Comment by esh-g** [comment] 2023-11-03 17:35
@0xmiroslav Shouldn't we disable the bounce if there are not enough items? Because even after that solution, we would be able to drag the menu item below the upper part of the UI...

**Comment by pecanoro** [comment] 2023-11-03 21:22
Sounds good, assigning @bernhardoj

**Comment by adelekennedy** [comment] 2023-11-22 19:26
payday!

**Payouts due:**
Contributor: $500 @bernhardoj 
Contributor+: $500 @0xmiroslav 

I sent you a manual request on Upwork!

Upwork job is [here](https://www.upwork.com/jobs/~01c024409da152917d).

**Comment by pecanoro** [comment] 2023-11-27 15:54
@adelekennedy Can we close this one? 😄

**Comment by adelekennedy** [comment] 2023-11-27 17:08
@0xmiroslav is the bugzero checklist complete?

**Closed** 2023-11-27 17:19 UTC
Labels: External, Daily, Awaiting Payment, Bug

**Comment by adelekennedy** [comment] 2023-12-18 16:32
@bernhardoj missed that - just ended the contract
