### ISSUE TITLE
[$1000] Task title briefly changes to "Chat Report" for User B after User A sends the first message in the newly-created task chat

### ISSUE THREAD

**Issue by kavimuru** [Expensify/App#24460] opened 2023-08-11 20:56 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Log into two accounts on Chrome (one may have to be in an incognito browser).
2. Open a chat with "User B" and click on the "+" in the composer.
3. Choose "Assign task", add a title, set "User B" as the assignee, and then click on the big green button that says "Confirm task".
4. Send a message in the newly-created task chat while observing "User B's" main chat with you.
## Expected Result: 
The task title remains the same in "User B's" main chat with you.
## Actual Result: 
The task title briefly changes to "Chat Report" in "User B's" main chat with you.

## Workaround:
Can the user still use Expensify without this being fixed? Have you informed them of the workaround?

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [x] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:**
**Reproducible in staging?:** needs reproduction
**Reproducible in production?:** needs reproduction
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/43996225/d5d0f7bc-2dd9-44b4-a29e-17f0f6a9da6c

**Expensify/Expensify Issue URL:**
**Issue reported by:** @Victor-Nyagudi 
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1691071965161749

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01e2799b14e4189cb2</li>
        <li>Upwork Job ID: 1691736520970010624</li>
        <li>Last Price Increase: 2023-08-16</li>
    </ul>
</details>

**Comment by tymatein** [comment] 2023-08-16 09:35
Cannot reproduce on staging and on dev 7f13cdd9f5 (Mac OS Chrome/Safari)

**Comment by greg-schroeder** [comment] 2023-08-16 10:08
Hmm. Perhaps it was fixed by something else?

**Comment by greg-schroeder** [comment] 2023-08-18 08:25
I think this is fixed and was likely a duplicate report accordingly.

**Closed by greg-schroeder** 2023-08-18 08:25 UTC
Labels: External, Daily, Needs Reproduction, Help Wanted, Bug
