### ISSUE TITLE
[$250] WS - App crashes when changing workspace ID to invalid ID while distance rate RHP is open

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#40481] opened 2024-04-18 16:57 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.63-0
**Reproducible in staging?:** y
**Reproducible in production?:** y
**Issue found when executing PR:** https://github.com/Expensify/App/pull/36409
**Issue reported by:** Applause - Internal Team

## Action Performed:
1. Navigate to staging.new.expensify.com
2. Create a workspace
3. Click on More features and turn on distance rates
4. Open Distance rates settings
5. Click on one distance rate to open the RHP
6. Click on the URL and change the workspace ID to an invalid set of strings

## Expected Result:
Not found view renders

## Actual Result:
App crashes

## Workaround:
n/a

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [x] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

https://github.com/Expensify/App/assets/93399543/0021b055-11ac-4d34-bcee-e091ad358efb

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~012a487426fc875ae6</li>
        <li>Upwork Job ID: 1781338802987253760</li>
        <li>Last Price Increase: 2024-04-19</li>
<li>Automatic offers: </li>
<ul>
<li>ishpaul777 | Reviewer | 0</li>
<li>Nodebrute | Contributor | 0</li>
</ul></li>
    </ul>
</details>

**Comment by kbecciv** [comment] 2024-04-18 16:58
We think that this bug might be related to #wave-collect - Release 1

**Comment by kbecciv** [comment] 2024-04-18 16:58
@bfitzexpensify FYI I haven't added the External label as I wasn't 100% sure about this issue. Please take a look and add the label if you agree it's a bug and can be handled by external contributors.

**Comment by Nodebrute** [comment] 2024-04-18 17:40
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
 App crashes when changing workspace ID to invalid ID while distance rate RHP is open 
### What is the root cause of that problem?
We need to improve our usage of optional chaining in this file, as currently, many values are left undefined [PolicyDistanceRateDetailsPage.tsx](https://github.com/Expensify/App/blob/fdca69cb3ae1cf73784e829333ae50dbfc71cb38/src/pages/workspace/distanceRates/PolicyDistanceRateDetailsPage.tsx)
### What changes do you think we should make in order to solve the problem?

We should do proper optional chaining in this file.
For example 
```    const rate = customUnit?.rates[rateID] ?? 0;
const currency = rate?.currency ?? CONST.CURRENCY.USD;
const canDeleteRate = Object.values(customUnit?.rates ?? {}).filter((distanceRate) => distanceRate?.enabled).length > 1 || !rate?.enabled;
const canDisableRate = Object.values(customUnit?.rates ?? {}).filter((distanceRate) => distanceRate?.enabled).length > 1;
```
### What alternative solutions did you explore? (Optional)

**Comment by minhbac333studyus** [comment] 2024-04-22 02:27
I see the same issue on Setting of Distance Rate Page ( crash instead NOT FOUND)

**Comment by minhbac333studyus** [comment] 2024-04-22 04:43
**Proposal Response**
**Problem Restatement**
The core issue was with the handling of potentially undefined properties when accessing nested data structures in JavaScript. The application encountered errors when trying to access rates by rateID within a potentially undefined customUnit object, leading to crashes or unexpected behaviors when the URL parameters were manually altered to non-existent IDs.

**Root Cause**
The root cause was improper handling of optional chaining and default values in a deeply nested data structure. Before the fix, the code did not properly fall back to default values when intermediate objects (customUnit or rates) were undefined. This led to attempts to access properties on undefined, resulting in runtime errors.

**Proposed Changes**
The changes implemented involved using optional chaining (?.) and nullish coalescing (??) operators to safely access nested properties and ensure defaults are used when data is missing. This approach prevents errors by ensuring that every level of property access is checked for nullity before proceeding to the next level:

```
const rate = customUnit?.rates[rateID] ?? {};
const currency = rate.currency ?? CONST.CURRENCY.USD;
const canDeleteRate = Object.values(customUnit?.rates ?? {}).filter((distanceRate) => distanceRate.enabled).length > 1 || !rate.enabled;
const canDisableRate = Object.values(customUnit?.rates ?? {}).filter((distanceRate) => distanceRate.enabled).length > 1;

```
Alternatives Explored
Error Boundary Handling: Implementing error boundaries to catch and handle errors in specific parts of the component tree. This would prevent the entire app from crashing but wouldn't solve the root cause.

**Comment by bfitzexpensify** [comment] 2024-04-22 16:26
Proposals ready for review @ishpaul777

**Comment by minhbac333studyus** [comment] 2024-04-24 14:25
Contributor details
Your Expensify account email: minhbacdev@gmail.com
Upwork Profile Link: https://www.upwork.com/freelancers/~01bc62fec324269a7e

**Comment by Nodebrute** [comment] 2024-04-26 19:25
I'll raise a PR soon.

**Comment by Nodebrute** [comment] 2024-04-29 20:45
@ishpaul777 Sorry for the delay. I'm working on it, and it will be ready in a few hours.

**Comment by Nodebrute** [comment] 2024-04-30 04:44
@ishpaul777 Hey, the [PR](https://github.com/Expensify/App/pull/41293) is ready for review.

**Comment by AndrewGable** [comment] 2024-05-20 21:41
Seems like there is one more instance of this: https://github.com/Expensify/App/pull/41293#issuecomment-2116120179

Can we add this as a follow up to this issue and make a new PR with the fix? Thanks!

**Comment by sobitneupane** [comment] 2024-05-23 06:51
We addressed the issue in https://github.com/Expensify/App/pull/42502 PR

**Comment by bfitzexpensify** [comment] 2024-05-30 22:56
OK, seems like if this is resolved via https://github.com/Expensify/App/pull/42502, which is connected to https://github.com/Expensify/App/issues/41594, then we can close this out.

**Closed by bfitzexpensify** 2024-05-30 22:56 UTC
Labels: Reviewing, External, Weekly, Bug

**Comment by bfitzexpensify** [comment] 2024-05-30 23:08
Gotcha - offers sent @Nodebrute @ishpaul777

**Comment by bfitzexpensify** [comment] 2024-05-31 10:32
Payments complete.
