### ISSUE TITLE
[HOLD for payment 2024-08-09] [$250] Draft disappears from the LHN when clicking away after starting a thread

### ISSUE THREAD

**Issue by m-natarajan** [Expensify/App#45543] opened 2024-07-17 00:39 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 9.0.8-0
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** @rafecolton 
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1721142729468189

## Action Performed:
1. Create a group as user A with user B and user C
2. Send a message to group as user A
3. Start a thread as user B 
4. Without joining click away
## Expected Result:
Draft should stay in the LHN
## Actual Result:
Draft disappear from the LHN
## Workaround:
unknown
## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

https://github.com/user-attachments/assets/1d37cbe9-7a7b-4684-8c7c-ef5ab5f0d8c6

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~011241d6b36d075893</li>
        <li>Upwork Job ID: 1815808765453560667</li>
        <li>Last Price Increase: 2024-07-23</li>
<li>Automatic offers: </li>
<ul>
<li>mkhutornyi | Reviewer | 103252123</li>
<li>nkdengineer | Contributor | 103252124</li>
</ul></li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @abekkala</details>

**Comment by nkdengineer** [comment] 2024-07-17 06:54
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
Draft disappear from the LHN

### What is the root cause of that problem?
The thread report has `notificationPreference` as `hidden`. If we don't open this thread or this thread is not pinned, it's hidden in LHN because we early return here.

https://github.com/Expensify/App/blob/9c509a0e6363adaeb6cbb8c377ed6ff98b85dc65/src/libs/SidebarUtils.ts#L136
https://github.com/Expensify/App/blob/9c509a0e6363adaeb6cbb8c377ed6ff98b85dc65/src/libs/SidebarUtils.ts#L137-L139

### What changes do you think we should make in order to solve the problem?
If the report has a draft comment `shouldOverrideHidden` should be `true`. We should use `hasValidDraftComment` to check whether the report has a draft comment or not.

```
const shouldOverrideHidden = hasErrorsOtherThanFailedReceipt || isFocused || isSystemChat || report.isPinned || hasValidDraftComment(report.reportID);
```

https://github.com/Expensify/App/blob/9c509a0e6363adaeb6cbb8c377ed6ff98b85dc65/src/libs/SidebarUtils.ts#L136

Then the check `shouldReportBeInOptionList` can be called and everything works well because we already have the check for draft comment in this function

https://github.com/Expensify/App/blob/9c509a0e6363adaeb6cbb8c377ed6ff98b85dc65/src/libs/ReportUtils.ts#L5486-5487
### What alternative solutions did you explore? (Optional)
We can return early if the report has a draft comment before this line

```
if (hasValidDraftComment(report.reportID)) {
    reportsToDisplay.push(report);
    return;
}
```
https://github.com/Expensify/App/blob/9c509a0e6363adaeb6cbb8c377ed6ff98b85dc65/src/libs/SidebarUtils.ts#L136

**Comment by abekkala** [comment] 2024-07-30 15:08
not yet merged

**Comment by abekkala** [comment] 2024-08-02 13:21
### PAYMENT SUMMARY FOR AUG 09

- Fix: @nkdengineer [$250] [Offer](https://www.upwork.com/nx/wm/offer/103252124)
- PR Review: @mkhutornyi [$250] [Offer](https://www.upwork.com/nx/wm/offer/103252123)
Please complete checklist above

**Comment by abekkala** [comment] 2024-08-08 18:18
not overdue payment is tomorrow

**Comment by abekkala** [comment] 2024-08-09 13:01
@nkdengineer and @mkhutornyi - payments have been sent and contracts ended - thank you! 🎉

**Closed by abekkala** 2024-08-09 13:01 UTC
Labels: External, Daily, Awaiting Payment, Bug
