### ISSUE TITLE
[$500] Bank account - Error "You must accept the terms" shows up when the terms are accepted

### ISSUE THREAD

**Issue by izarutskaya** [Expensify/App#38862] opened 2024-03-23 12:14 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.56-0
**Reproducible in staging?:** Y
**Reproducible in production?:** N
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Issue reported by:** Applause-Internal team

## Action Performed:
1. Go to staging.new.expensify.com.
2. Go to Profile > Workspaces > any workspace.
3. Go to Bank account.
4. Click Click Connect online with Plaid.
5. Proceed with the setup.
6. In the final step (terms and agreements), click Save & continue.
7. Click Save & continue again.
8. Close the RHP.
9. Click Bank account.

## Expected Result:
At the final step, after checking all terms and agreement, user will be able to set up bank account successfully.

## Actual Result:
At the final step, after checking all terms and agreement, clicking on Save & continue button shows the error "You must accept the terms".
In Step 11, after closing bank account setup and reopening bank account RHP, the bank account is added successfully.

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [x] Android: mWeb Chrome
- [x] iOS: Native
- [x] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

https://github.com/Expensify/App/assets/115492554/e4d8b000-d800-466f-ac81-0eb3f1a629f7

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~0171463c8654b8a151</li>
        <li>Upwork Job ID: 1772699947694186497</li>
        <li>Last Price Increase: 2024-04-02</li>
<li>Automatic offers: </li>
<ul>
<li>fedirjh | Contributor | 0</li>
</ul></li>
    </ul>
</details>

**Comment by izarutskaya** [comment] 2024-03-23 12:15
@muttmuure I haven't added the External label as I wasn't 100% sure about this issue. Please take a look and add the label if you agree it's a bug and can be handled by external contributors.


We think this issue might be related to the #wave-control.

**Comment by izarutskaya** [comment] 2024-03-23 12:18
Production


https://github.com/Expensify/App/assets/115492554/ee55fc7b-9850-4087-aba7-97a71023fafa

**Comment by godofoutcasts94** [comment] 2024-03-23 13:54
This is the regression from this issue - https://github.com/Expensify/App/pull/34413

**Comment by godofoutcasts94** [comment] 2024-03-23 13:58
yes I am sure of it. This is the main cause because after that there has been no change in that file after January.

**Comment by flodnv** [comment] 2024-03-25 18:14
So @godofoutcasts94 you are able to reproduce in production?

**Comment by godofoutcasts94** [comment] 2024-03-25 18:35
Yes but in the final step, I am getting that error but when I check all the `terms and conditions` checkboxes and click on `Save & Continue`, the error is displaying but when I close the `RHP` and click on `Bank Account`, then the bank account is added and getting displayed with name and selected bank

**Comment by godofoutcasts94** [comment] 2024-03-25 18:37
If you need a working video of I can share with you as well @flodnv

**Comment by flodnv** [comment] 2024-03-25 18:46
Yes please

**Comment by godofoutcasts94** [comment] 2024-03-25 19:19
@flodnv I used `connect with plaid` and this video is of the final steps of it.

https://github.com/Expensify/App/assets/158435970/92192f41-56d0-48f4-95da-29970bf14429

**Comment by flodnv** [comment] 2024-03-25 21:07
@godofoutcasts94 I'm confused because your video is on dev (not prod) and is not showing the same exact flow as the original video.

**Comment by flodnv** [comment] 2024-03-25 21:14
Thanks for pointing that out, I agree that was not the same test. Asking for a retest here: https://expensify.slack.com/archives/C01GTK53T8Q/p1711401274700469?thread_ts=1711394653.352709&cid=C01GTK53T8Q

**Comment by flodnv** [comment] 2024-03-25 21:20
Ok but @godofoutcasts94 is showing the bug exists on dev, no? What makes us think it does not exist on production?

**Comment by amyevans** [comment] 2024-03-25 22:29
Testing locally on the `production` branch, I am still unable to successfully complete the form (albeit the exact error message is a bit different - not sure if that is meaningful and/or if I followed the exact same test steps?):

https://github.com/Expensify/App/assets/7277067/ecf4bf21-bb1b-472a-8a39-f3d6486dc100

But based on what I see at least I don't think this needs to be a deploy blocker

**Comment by godofoutcasts94** [comment] 2024-03-26 05:17
Hey @amyevans! did you have a look at this [comment's](https://github.com/Expensify/App/issues/38862#issuecomment-2018736189) video

**Comment by amyevans** [comment] 2024-03-26 18:59
> Hey @amyevans! did you have a look at this https://github.com/Expensify/App/issues/38862#issuecomment-2018736189 video

I see the video yes, but I'm not clear what point you are trying to make, sorry. If you have a proposal, mind laying it out using the template so that it is easier to digest?

<hr>

Also going to add the External label to get a C+ assigned.

**Comment by muttmuure** [comment] 2024-04-02 19:27
under discussion

**Comment by muttmuure** [comment] 2024-04-12 11:34
@fedirjh question for you: https://github.com/Expensify/App/issues/38862#issuecomment-2042605859

**Comment by muttmuure** [comment] 2024-04-16 17:55
@fedirjh bump

**Comment by muttmuure** [comment] 2024-04-17 10:17
OK, I think we can close it out as an edge case for now.

**Comment by muttmuure** [comment] 2024-04-17 10:18
Thanks for taking another look

**Comment by kbecciv** [comment] 2024-05-09 18:13
Reopening the issue for a second chance as the QA team is still encountering the problem.

https://github.com/Expensify/App/assets/93399543/d9c155d8-7281-4a39-a6c2-607fdf7e5617

**Comment by muttmuure** [comment] 2024-06-12 10:02
Making Daily

**Comment by muttmuure** [comment] 2024-06-19 10:07
@fedirjh are you able to take a look at the repro steps [here](https://github.com/Expensify/App/issues/38862#issuecomment-2151941746)?

**Comment by muttmuure** [comment] 2024-07-12 15:56
Not overdue

**Comment by mvtglobally** [comment] 2024-07-19 03:24
Issue not reproducible during KI retests. (First week)

**Comment by muttmuure** [comment] 2024-07-25 10:55
Closing as not reproducible

**Closed by muttmuure** 2024-07-25 10:55 UTC
Labels: External, Engineering, Weekly, Overdue, Bug, retest-weekly
