### ISSUE TITLE
[Awaiting checklist completion] [$250] IOS - Launch app - Header in Home page is missing briefly when app is launched

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#42639] opened 2024-05-27 15:08 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:**  1.4.76-0
**Reproducible in staging?:** Y
**Reproducible in production?:** N
**If this was caught during regression testing, add the test name, ID and link from TestRail:** N/A
**Issue reported by:** Applause - Internal Team

## Action Performed:
1. Kill New Expensify app
2. Launch New Expensify app

## Expected Result:
Header in Home page will appear as soon as app is launched

## Actual Result:
Header in Home page is missing briefly when app is launched

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [x] iOS: Native
- [ ] iOS: mWeb Safari
- [ ] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details> 

https://github.com/Expensify/App/assets/78819774/9000383d-6cb7-4bcc-831b-25bbdbb387ba

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~0140411e66768d8abb</li>
        <li>Upwork Job ID: 1795453007863173120</li>
        <li>Last Price Increase: 2024-05-28</li>
<li>Automatic offers: </li>
<ul>
<li>DylanDylann | Reviewer | 102495294</li>
<li>bernhardoj | Contributor | 102495296</li>
</ul></li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @twisterdotcom</details>

**Comment by lanitochka17** [comment] 2024-05-27 15:09
@hayata-suenaga  FYI I haven't added the External label as I wasn't 100% sure about this issue. Please take a look and add the label if you agree it's a bug and can be handled by external contributors

**Comment by lanitochka17** [comment] 2024-05-27 15:09
We think that this bug might be related to #vip-vsp

**Comment by hayata-suenaga** [comment] 2024-05-27 17:38
let me check if we want to fix this or not 😄

**Comment by bernhardoj** [comment] 2024-05-28 05:39
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
The home header is missing briefly.

### What is the root cause of that problem?
The header/top bar is wrapped with a withOnyx that subscribed to policy and session.
https://github.com/Expensify/App/blob/2514f2988eb26858d30fa501c0040b1f8fc2e239/src/libs/Navigation/AppNavigator/createCustomBottomTabNavigator/TopBar.tsx#L87-L94

If one of the data is not ready yet, withOnyx will return null, so nothing is rendered.

This happens after this [PR](https://www.github.com/Expensify/App/pull/42335) where it updates `useActiveWorkspaceFromNavigationState` to return undefined when there is no active workspace instead of an empty string. It's to fix an issue where if it's an empty string (policy_), it will fetch the whole collection, but now it's undefined (policy_undefined).

### What changes do you think we should make in order to solve the problem?

As withOnyx is deprecated now, we can replace it with useOnyx hook.

Or if we still want to use withOnyx, we can set initial value for the policy onyx to an empty object.

**Comment by adamgrzybowski** [comment] 2024-05-28 08:32
I looked at this solution with @WojtekBoman and it makes sense to us

**Comment by luacmartins** [comment] 2024-05-28 13:44
@bernhardoj are you available to work on a solution for this?

**Comment by luacmartins** [comment] 2024-05-28 13:52
Nice! Assigned you to it @bernhardoj

**Comment by bernhardoj** [comment] 2024-05-28 14:21
PR is ready

cc: @DylanDylann

**Comment by kavimuru** [comment] 2024-05-28 19:21
Issue is not reproducible 

https://github.com/Expensify/App/assets/43996225/08386e1b-e6ec-4440-8f7d-e5ad87bc7594

**Comment by twisterdotcom** [comment] 2024-05-28 20:31
It is on staging.

**Comment by twisterdotcom** [comment] 2024-06-05 16:53
Payment Summary:

- @bernhardoj paid $250 [here](https://www.upwork.com/nx/wm/offer/102495296) (Contributor)
- @DylanDylann paid $250 [here](https://www.upwork.com/nx/wm/offer/102495294) (Reviewer)

@DylanDylann please complete the checklist.

**Comment by DylanDylann** [comment] 2024-06-05 18:14
BugZero Checklist: The PR fixing this issue has been merged! The following checklist ([instructions](https://stackoverflow.com/c/expensify/questions/14574)) will need to be completed before the issue can be closed:

 [@DylanDylann] The PR that introduced the bug has been identified. Link to the PR: **NA**
 [@DylanDylann] The offending PR has been commented on, pointing out the bug it caused and why, so the author and reviewers can learn from the mistake. Link to comment: **NA**
 [@DylanDylann] A discussion in #expensify-bugs has been started about whether any other steps should be taken (e.g. updating the PR review checklist) in order to catch this type of bug sooner. Link to discussion: **NA**
 [@DylanDylann] Determine if we should create a regression test for this bug. **Yes**
 [@DylanDylann] If we decide to create a [regression test](https://github.com/Expensify/App/blob/main/contributingGuides/REGRESSION_TEST_BEST_PRACTICES.md) for the bug, please propose the regression test steps to ensure the same bug will not reach production again.


Regression Test Proposal

1. (Web/Desktop/mWeb) Refresh the app (iOS/Android) Close the app and reopen the app
2. Verify the header/top bar of the home page/LHN is shown immediately


Do we agree 👍 or 👎

**Closed** 2024-06-06 12:18 UTC
Labels: External, Engineering, Daily, Bug
