### ISSUE TITLE
[HOLD for payment 2023-09-06] [$1000] skeleton ui does not show when contact are loading

### ISSUE THREAD

**Issue by izarutskaya** [Expensify/App#25888] opened 2023-08-24 20:03 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. go to Settings > Workspaces >members
2. click on invite button

## Expected Result:
skeleton ui should show while contacts are loading

## Actual Result:
contact appears after 1 second and does not show skeleton ui

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [x] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** v1.3.57-2

**Reproducible in staging?:** Y

**Reproducible in production?:** N

**If this was caught during regression testing, add the test name, ID and link from TestRail:**

**Email or phone of affected tester (no customers):**

**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/115492554/65b8e927-5702-4979-948a-76ea3ea8fd11

https://github.com/Expensify/App/assets/115492554/06cbad82-0bd3-4837-998e-ca76a4a5a9ba

**Expensify/Expensify Issue URL:**

**Issue reported by:** @Gadhiyamanan

**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1692777344552489

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01f892a2c55733ea89</li>
        <li>Upwork Job ID: 1695095374712561664</li>
        <li>Last Price Increase: 2023-08-25</li>
    </ul>
</details>

**Comment by Pujan92** [comment] 2023-08-24 20:25
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
No skeleton on workspace invite page

### What is the root cause of that problem?
While migrating from `OptionSelector` to `SelectionList` we haven't used the prop `showLoadingPlaceholder` seems the cause of the issue.

### What changes do you think we should make in order to solve the problem?
Use `showLoadingPlaceholder` for `SelectionList` in the `WorkspaceInvitePage` with the conditions which we are using earlier.
```
showLoadingPlaceholder={!didScreenTransitionEnd || !OptionsListUtils.isPersonalDetailsReady(props.personalDetails)}
```

**Comment by hayata-suenaga** [comment] 2023-08-25 15:26
Confirmed this is only on staging

**Comment by hayata-suenaga** [comment] 2023-08-25 15:27
@ntdiary can you review @Pujan92's proposal?

**Comment by roryabraham** [comment] 2023-08-25 16:36
@hayata-suenaga Deploy blockers should not be made external. Even if you leverage a contributor to implement the solution, these should be hourly issues and higher priority than anything else. So we just can't afford to the wait for the standard proposal + review process. If you're trying to focus on something else, you need to find an internal volunteer to take over.

**Comment by Pujan92** [comment] 2023-08-25 16:49
Let me know in case I need to raise a PR for this or will be taken care internally. Thanks!

**Comment by hayata-suenaga** [comment] 2023-08-25 16:58
assigned @Pujan92

**Comment by hayata-suenaga** [comment] 2023-08-25 16:59
please open a PR 🙇

**Comment by tjferriss** [comment] 2023-08-30 04:47
The PR was merged in under three days so contributor and C+ are eligible for the bonus.

**Comment by gadhiyamanan** [comment] 2023-09-01 04:34
Applied to upwork job

**Comment by tjferriss** [comment] 2023-09-05 19:15
@gadhiyamanan I've hired you in Upworks.

@aimane-chnaif can you please get started on the checklist?

**Comment by hayata-suenaga** [comment] 2023-09-14 07:14
I think this issue is waiting for payment. Not overdue

**Comment by tjferriss** [comment] 2023-09-16 22:26
@aimane-chnaif @Pujan92 I've sent you both an offer via Upworks for payment.

**Comment by hayata-suenaga** [comment] 2023-09-21 08:28
waiting for the offer to be accepted

**Comment by Pujan92** [comment] 2023-09-21 09:02
> @aimane-chnaif @Pujan92 I've sent you both an offer via Upworks for payment.

@tjferriss Accepted!

**Comment by tjferriss** [comment] 2023-09-25 05:14
@aimane-chnaif I just accepted your offer. @Pujan92 I just paid you.

**Comment by tjferriss** [comment] 2023-09-26 07:26
Everyone has been paid

**Closed by tjferriss** 2023-09-26 07:26 UTC
Labels: Engineering, Daily, Awaiting Payment, Bug
