### ISSUE TITLE
[C+ Checklist Needs Completion] [$1000] Web – Workspace – Tooltip remains visible for a short period of time even after closing an image

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#21529] opened 2023-06-25 16:15 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Open any Workspace.
2. Click on "reply in thread" next to any message.
3. Click on the avatar to open the "Details" view.
4. Click on "Members."
5. Click on a user.
6. Click on the avatar.
7. Click on the cross button to close the image.
8. Notice that the tooltip remains visible for a short period of time even after the image is closed.

## Expected Result:
The tooltip should disappear immediately, just like in other cases.

## Actual Result:
The tooltip remains visible for a short period of time even after the image is closed.

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [x] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 1.3.29-0
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/93399543/595dd183-6538-403a-ac56-46a157ed3d28

https://github.com/Expensify/App/assets/93399543/f913a1e9-773d-4db6-8962-8a935c76a70f

**Expensify/Expensify Issue URL:**
**Issue reported by:** @usmantariq96
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1687155625576929

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01613281d3becb92a0</li>
        <li>Upwork Job ID: 1674113232405966848</li>
        2023-07-21<li>Automatic offers: </li>
<ul>
<li>fedirjh | Reviewer | 25856645</li>
<li>ginsuma | Contributor | 25856646</li>
</ul></li>
    </ul>
</details>

**Comment by greg-schroeder** [comment] 2023-06-28 17:51
I reproduced this and I don't see any duplicate issues... there are some related tooltip bugs like the tooltip not responding for links (https://github.com/Expensify/App/issues/21605), but nothing about the tooltip staying present for like a little bit after it should disapper.

**Comment by DrLoopFall** [comment] 2023-06-28 20:45
## Proposal

### Please re-state the problem that we are trying to solve in this issue.

The tooltip is visible for a short period after closing a Modal (used to show the image)

### What is the root cause of that problem?

The Modal opens/closes with a small fade(for desktop) animation, during which the tooltip remains visible since the cursor is still hovering over the close/other buttons.

### What changes do you think we should make in order to solve the problem?

We can use React `Context` and pass `isVisible` from `BaseModal` to all the tooltips inside the Modal if the Modal is not visible then hide the tooltip.

somewhere
```js
const ModalContext = React.createContext({
    isModalClosed: false,
});
```
in `BaseModal.js`
```js
<ModalContext.Provider value={{ isModalClosed: !this.props.isVisible }} >
```

in `Tooltip/index.js`
```js
const {isModalClosed} = useContext(ModalContext)

// show tooltip only if !isModalClosed
```

### What alternative solutions did you explore? (Optional)

Or we can use create a `Context` for `Tooltip` like,

```js
const TooltipContext = React.createContext({
    canShowTooltip: true,
});
```

<details>

<summary>Result</summary>

https://github.com/Expensify/App/assets/120749263/c7160fcd-5843-49e3-8bd7-e167ee3fa639

</details>

**Comment by greg-schroeder** [comment] 2023-06-30 07:33
Thoughts on this proposal @fedirjh ?

**Comment by DrLoopFall** [comment] 2023-07-05 16:51
When the modal(image popup) is closed, the modal is not removed immediately, it fades out, while fading out the modal is still mounted/visible with less opacity, so the close button is still present(barely visible since it's fading out), hence the tooltip also remains visible.

**Comment by greg-schroeder** [comment] 2023-07-10 19:00
@fedirjh sorry, where do we stand on this one? Are we still waiting for completed proposals?

**Comment by greg-schroeder** [comment] 2023-07-15 16:55
Okay - sounds like we're waiting for more proposals here

**Comment by greg-schroeder** [comment] 2023-07-17 20:45
Awaiting proposals - might toss over to CS or SWM

**Comment by greg-schroeder** [comment] 2023-07-21 09:48
Going to double the bounty

**Comment by himanshuragi456** [comment] 2023-07-21 10:10
## Proposal

### Please re-state the problem that we are trying to solve in this issue.

"Close" tooltip stays visible for a moment after modal closes on Profile Image.

### What is the root cause of that problem?

The issue arises from the fact that animations, such as fading effects when unmounting, don't remove components from the DOM instantly. As a result, the tooltip associated with the close button persists for a fraction of a second after the modal has closed.

### What changes do you think we should make in order to solve the problem?

We may propose an effective solution to automatically hide the Tooltip when its target element disappears. By detecting modal visibility and introducing trigger actions (hideTooltip()) for the Tooltip, we can ensure a seamless and user-friendly experience.
In this case, we can handle all modal tooltips including this issue.

https://github.com/Expensify/App/blob/7fea760c2bb7556815aaca2d61861bd1cf39d6b1/src/components/Tooltip/index.js#L18-L21

### What alternative solutions did you explore? (Optional)

Exploring

**Comment by devanshu-josh** [comment] 2023-07-21 10:14
## Proposal

### Please re-state the problem that we are trying to solve in this issue.

"Close" tooltip stays visible for a moment after modal closes on Profile Image.

### What is the root cause of that problem?

The issue arises from the fact that animations, such as fading effects when unmounting, don't remove components from the DOM instantly. As a result, the tooltip associated with the close button persists for a fraction of a second after the modal has closed.

### What changes do you think we should make in order to solve the problem?

We may propose an effective solution to automatically hide the Tooltip when its target element disappears. By detecting modal visibility and introducing trigger actions (hideTooltip()) for the Tooltip, we can ensure a seamless and user-friendly experience.
In this case, we can handle all modal tooltips including this issue.

https://github.com/Expensify/App/blob/7fea760c2bb7556815aaca2d61861bd1cf39d6b1/src/components/Tooltip/index.js#L18-L21

### What alternative solutions did you explore? (Optional)

Exploring

**Comment by crazy-coding** [comment] 2023-07-21 10:18
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
"Close" tooltip stays visible for a moment after modal closes on keyboard shortcuts modal screen

### What is the root cause of that problem?
The `Tooltip` component enhances user experience by incorporating hover action and seamless animations for visibility and invisibility. When the user unhovers or clicks on the close button, the tooltip gracefully disappears with a smooth animation even though the target object is already disappeared.

### What changes do you think we should make in order to solve the problem?
One effective approach entails concealing the `HeaderWithBackButton` component through the `AttachmentModal`'s visibility property, utilizing the `this.state.isModalOpen` attribute.
https://github.com/JediWattson/App/blob/3066281875c43d91cbf6261f2570aa2a3e5002b0/src/components/AttachmentModal.js#L264-L270

### What alternative solutions did you explore? (Optional)
We may propose an effective solution to automatically hide the Tooltip when its target element disappears. By detecting modal visibility and introducing trigger actions (`hideTooltip()`) for the `Tooltip`, we can ensure a seamless and user-friendly experience.
In this case, we can handle all modal tooltips including this issue.
https://github.com/Expensify/App/blob/7fea760c2bb7556815aaca2d61861bd1cf39d6b1/src/components/Tooltip/index.js#L18-L21

**Comment by daanish-shaikh** [comment] 2023-07-21 12:18
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
Even after closing the modal, the tooltip is still visible.

### What is the root cause of that problem?
Content within the modal gets removed from the Dom tree only after the modal closing animation is done and in case of fadeOut animation, content is faded out but still attached in Dom tree hence `Close` tooltip is visible even after all modal content is hidden.

### What changes do you think we should make in order to solve the problem?
We will need to remove the close button completely from the Dom tree before closing the modal (starting the closing modal animation).
1. Add `showCloseButton` state variable with the initial value as `true`.
```
const [showCloseButton, setShowCloseButton] = useState(true);
```
2. Modify `closeModal()`, [here.](https://github.com/Expensify/App/blob/main/src/components/AttachmentModal.js#L279).
```
const closeModal = useCallback(() => {
    setShowCloseButton(false);
    setIsModalOpen(false);
}, []);
```
3. Modify `onModalShow()`, [here](https://github.com/Expensify/App/blob/main/src/components/AttachmentModal.js#L299).
```
onModalShow={() => {
    setShowCloseButton(true);
    props.onModalShow();
    setShouldLoadAttachment(true);
}}
```
4. Add check for `showCloseButton` state in `shouldShowCloseButton` prop of `<HeaderWithBackButton>` component, [here](https://github.com/Expensify/App/blob/main/src/components/AttachmentModal.js#L315).
```
shouldShowCloseButton={!props.isSmallScreenWidth && showCloseButton}
```

**Comment by proshir** [comment] 2023-07-21 13:18
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
After closing the complete modal (using keyboard shortcut (Esc) or using close button ) the "Close" tooltip stays visible for a moment. This issue is observed in various modals such as the profile detail picture modal or preview modal. ( Attachment Modal)
### What is the root cause of that problem?
The root cause of the problem is that the tooltip's visibility is not directly tied to the modal's closing animation. When the modal starts its closing animation, the tooltip remains visible because it is still being triggered by the hover state of the "Close" button inside the modal. The tooltip is not aware of the modal's closing animation, so it does not hide immediately when the animation starts.

To address this issue, we need to establish a mechanism to hide the tooltip as soon as the modal's closing animation starts. This can be achieved by adding a callback or event listener in the modal that notifies the tooltip to hide itself when the closing animation begins. By doing so, the tooltip's visibility will be synchronized with the modal's state changes, and it will hide as soon as the modal's closing animation starts, providing a smoother and more intuitive user experience.
As we said, with the following method, we can make the tooltip hide when the closing animation starts with the keyboard shortcut or anything else.
### What changes do you think we should make in order to solve the problem?
First, we create the ```showtooltips``` variable in the ```AttachmentModal``` . This variable is the communication way of the model with the tooltips.
```
function AttachmentModal(props) {
    const [showTooltips, setShowTooltips] = useState(true);
    ...
}
```
And now we change the following two functions. With this, when the model is opened, the tooltips will be displayed again, and when the model is closed for any reason, the tooltips will lose their display ability and close (with animation).
```
  const closeModal = useCallback(() => {
      setShowTooltips(false);
      setIsModalOpen(false);
  }, []);

  /**
   *  open the modal
   */
  const openModal = useCallback(() => {
      setShowTooltips(true);
      setIsModalOpen(true);
  }, []);
```
Now, for the tooltips of each section, we transfer the mentioned variable, for example, in this section we have:
```
<HeaderWithBackButton
      showTooltips={showTooltips}
   ....
/>
```
And for the tooltip we add this prop:
```
<Tooltip text={translate('common.close')} showTooltips={showTooltips}>
```
So, in the componentDidUpdate function, which is called after every change, we can easily reach our result with the following change:
‍‍‍‍‍‍‍‍```
componentDidUpdate(prevProps) {
    if (prevProps.showTooltips !== this.props.showTooltips) {
        if (!this.props.showTooltips) {
            this.hideTooltip();
        }
    }
    ...
}
```
Again, with this solution, all tooltips, whether in the file preview or profile detail, are closed with animation, and in my opinion, it is the best solution.

**Comment by devanshu-josh** [comment] 2023-07-24 02:51
@greg-schroeder gently bump here
cc: @fedirjh

**Comment by greg-schroeder** [comment] 2023-07-26 21:16
Awaiting proposal review

**Comment by himanshuragi456** [comment] 2023-07-31 10:41
quick question @fedirjh: the selected proposal existed even before we doubled the bounty, so will this be eligible for a double bounty? and why did we attract more proposals by doubling the bounty when the ideal solution was already there?
cc: @greg-schroeder

**Comment by greg-schroeder** [comment] 2023-07-31 11:50
Couldn't have said it better myself, thanks @fedirjh

**Comment by greg-schroeder** [comment] 2023-08-02 10:35
PR review underway

**Comment by Nathan-Mulugeta** [comment] 2023-08-11 05:42
Hey guys I think I have reported such issue [here](https://github.com/Expensify/App/issues/23320) a month before this issue was reported. I retested the issue I have reported and it has been fixed now. I think the RCA might have been the same. @greg-schroeder can you take a look at this and let me know if this makes me eligible for the reporting bonus? Thanks.

**Comment by Nathan-Mulugeta** [comment] 2023-08-22 07:54
Hey @greg-schroeder, could you pleaste take a look at [this comment?](https://github.com/Expensify/App/issues/21529#issuecomment-1674237044)

**Comment by greg-schroeder** [comment] 2023-08-23 06:46
Price is $1k per this comment for posterity: https://github.com/Expensify/App/issues/21529#issuecomment-1658145309

**Comment by greg-schroeder** [comment] 2023-08-23 06:50
Payments/offers made. All that's left is the checklist @fedirjh

**Comment by usmantariq96** [comment] 2023-08-23 06:53
@greg-schroeder offer accepted.

**Comment by greg-schroeder** [comment] 2023-08-23 06:53
Sorry for the confusion @Nathan-Mulugeta. We do our best to keep the process as fair as possible, but multiple reports can happen when we have a lot of reviewers/reports streaming through, and the definition of a bug is fluid. We generally only pay out one reporter.

**Comment by Nathan-Mulugeta** [comment] 2023-08-23 06:55
Hey @greg-schroeder , yes I understand that only one bug reporter is paid. But I know that the original bug reporter/the one reported first gets paid. My report precedes this one. Could you check that out. Thanke

**Comment by usmantariq96** [comment] 2023-08-23 07:03
Dear @Nathan-Mulugeta 
I cross checked the reports and found out the I reported the issue 2 months ago and your report was issued 1 month ago.
so I don't think you are the original bug reporter.

For your reference please find below images.
![image](https://github.com/Expensify/App/assets/127622389/788d9a3a-38a6-4bbf-9b99-12e28048df91)
![image](https://github.com/Expensify/App/assets/127622389/f314e09e-73ed-4ee1-ab22-06bf2761e62a)

**Comment by Nathan-Mulugeta** [comment] 2023-08-23 07:08
OMG 😯, I am so sorry, I don't know how I got the report dates mixed up. I thought mine was the one reported on Jun 19th. So sorry again for bothering you all.

**Comment by greg-schroeder** [comment] 2023-08-24 02:21
No worries!

**Comment by greg-schroeder** [comment] 2023-08-28 10:00
Filing test, closing

**Closed by greg-schroeder** 2023-08-28 10:00 UTC
Labels: External, Engineering, Daily, Overdue, Awaiting Payment, Bug
