### ISSUE TITLE
[HOLD for payment 2024-03-14] [$250] iOS - Image - Maximum zoom is applied after zooming out

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#37248] opened 2024-02-27 02:11 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.44-0
**Reproducible in staging?:** Y
**Reproducible in production?:** N
**If this was caught during regression testing, add the test name, ID and link from TestRail:** https://expensify.testrail.io/index.php?/tests/view/4345659
**Email or phone of affected tester (no customers):** vdargentotest+ios022624@gmail.com
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** Applause - Internal Team
**Slack conversation:**

## Action Performed:
Pre-requisite: the user must be logged in
1. Go to any chat
2. Send an image
3. Tap on the image preview
4. Zoom in until you can not zoom more
5. Double tap on the image to zoom out
6. Try to zoom in with 2 fingers

## Expected Result:
The image should be zoomed in a bit

## Actual Result:
The maximum zoom is applied to the image

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [x] iOS: Native
- [ ] iOS: mWeb Safari
- [ ] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details> 

https://github.com/Expensify/App/assets/78819774/a1290223-f4c6-4479-b3ca-e62290222162

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~013893bd4f5612ab60</li>
        <li>Upwork Job ID: 1762299502083756032</li>
        <li>Last Price Increase: 2024-02-27</li>
<li>Automatic offers: </li>
<ul>
<li>paultsimura | Reviewer | 0</li>
<li>andreasnw | Contributor | 0</li>
</ul></li>
    </ul>
</details>

**Comment by lanitochka17** [comment] 2024-02-27 02:12
We think that this bug might ### be related to #vip-vsp
CC @quinthar

**Comment by youssef-lr** [comment] 2024-02-27 04:03
cc @andreasnw @eVoloshchak I think this is related to https://github.com/Expensify/App/pull/35931

**Comment by andreasnw** [comment] 2024-02-27 05:20
hi @youssef-lr ,

I don't believe this bug appeared recently (regression) as it can also be seen in the older version v1.4.43-2 (before my pr).
![Simulator Screenshot - iPhone 14 - 2024-02-27 at 12 10 06](https://github.com/Expensify/App/assets/60419079/31b7955f-c26b-4cd5-8137-0ee331286a8e)

https://github.com/Expensify/App/assets/60419079/7ed44b41-1267-44d7-99d1-c794267e0656

This seems to be a separate issue. We can fix it by setting pinchScale.value to 1 whenever a double tap occurs. I'm happy to take care of this if you assign it to me.

POC after resetting pinchScale.value to 1:

https://github.com/Expensify/App/assets/60419079/38ca8da2-91ee-4464-afbe-807068507683

**Comment by youssef-lr** [comment] 2024-02-27 05:34
Hmm seems like this is not a deploy blocker then, I can reproduce on the previous version which is in production now. I'll quickly try to find the offending PR and get back to you @andreasnw.

**Comment by shahinyan11** [comment] 2024-02-29 11:48
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
iOS - Image - Maximum zoom is applied after zooming out
### What is the root cause of that problem?
We do not reset `pinchScale.value` after double tap in [reset](https://github.com/Expensify/App/blob/cb58503cbb254648c46525b81e8fc96521c19178/src/components/MultiGestureCanvas/index.tsx#L116C11-L116C16) function
### What changes do you think we should make in order to solve the problem?
Add `pinchScale.value = withSpring(1, SPRING_CONFIG);` on [this](https://github.com/Expensify/App/blob/cb58503cbb254648c46525b81e8fc96521c19178/src/components/MultiGestureCanvas/index.tsx#L127) line 

### What alternative solutions did you explore? (Optional)

**Comment by shahinyan11** [comment] 2024-02-29 13:03
> P.S. Let's add `pinchScale.value = 1` here as well for the non-animated reset:

I updated my proposal and then saw your comment. I agree with you

**Comment by paultsimura** [comment] 2024-02-29 13:27
Unfortunately, @andreasnw, you didn't post a formal proposal, so I didn't even notice your suggestion while reviewing the issue.
According to our contribution guidelines, @shahinyan11 was the first to post a Proposal, and he has the right to be assigned here, but I'll let @youssef-lr make a final decision here.

**Comment by shahinyan11** [comment] 2024-02-29 14:46
@andreasnw I didn't even notice that you wrote anything about fixing the problem. I understand your concern, but if you provided a proposal with necessary format, I would see it and not waste extra time finding and fixing problem.

**Comment by youssef-lr** [comment] 2024-03-04 14:08
Sorry folks but @andreasnw has still described the issue and offered the correct fix in their comment. It was a reply to me so it didn't have the proper format. I think it's fair to have this assigned to them still. Also, given the simple change, I'm adjusting the price slightly.

**Comment by andreasnw** [comment] 2024-03-04 18:57
PR ready for review https://github.com/Expensify/App/pull/37692

**Comment by slafortune** [comment] 2024-03-14 20:09
Testrail added here - https://github.com/Expensify/Expensify/issues/379000
@paultsimura - Paid
@andreasnw - Paid

**Closed by slafortune** 2024-03-14 20:09 UTC
Labels: External, Engineering, Daily, Awaiting Payment
