### ISSUE TITLE
[HOLD for payment 2023-08-08] [$1000] Dev: Web - Message is not center aligned vertically

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#23350] opened 2023-07-21 11:49 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Open any chat and focus on composer
2. Send any message
3. Hover message and observe hovered background

## Expected Result:
Message is center aligned vertically

## Actual Result:
Message is not center aligned vertically

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [x] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** Dev 1.3.43-4
**Reproducible in staging?:** n/a
**Reproducible in production?:** n/a
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation

![bug](https://github.com/Expensify/App/assets/93399543/0d44e630-9419-430c-a748-18e782a3d206)

**Expensify/Expensify Issue URL:**
**Issue reported by:** @situchan 
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1689880642291459

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01e8cf36b803aa7592</li>
        <li>Upwork Job ID: 1683865114924675072</li>
        <li>Last Price Increase: 2023-07-25</li>
    </ul>
</details>

**Comment by alitoshmatov** [comment] 2023-07-21 12:02
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
Web - Message is not center aligned vertically
### What is the root cause of that problem?
We are still rendering component which is responsible for showing emoji reactions and it has some padding applied to it
### What changes do you think we should make in order to solve the problem?
We should add condition and render `ReportActionItemEmojiReactions` only if report action has an reaction:
https://github.com/Expensify/App/blob/8dcad168d11a71424b6ffd7fa30fd1770c0165d5/src/pages/home/report/ReportActionItem.js#L361
We can add  condition  like this: `_.isEmpty(props.emojiReactions)`

### What alternative solutions did you explore? (Optional)

**Comment by Pujan92** [comment] 2023-07-21 12:14
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
Chat Message is not aligned center vertically

### What is the root cause of that problem?
As `ReportActionItemEmojiReactions` we are rendering without having the reactions also causing the issue of top margin of 8px.
https://github.com/Expensify/App/blob/041d6400d0909812d8423c5f19d1092dd347a040/src/pages/home/report/ReportActionItem.js#L361
https://github.com/Expensify/App/blob/041d6400d0909812d8423c5f19d1092dd347a040/src/components/Reactions/ReportActionItemEmojiReactions.js#L71-L73

### What changes do you think we should make in order to solve the problem?
Only render the `View` for `ReportActionItemEmojiReactions` when we have the reactions for the message.

```
{!_.isEmpty(props.emojiReactions) && <View style={draftMessageRightAlign}>
```

https://github.com/Expensify/App/blob/041d6400d0909812d8423c5f19d1092dd347a040/src/pages/home/report/ReportActionItem.js#L360

**Comment by situchan** [comment] 2023-07-21 14:23
Proposal from [slack](https://expensify.slack.com/archives/C049HHMV9SM/p1689884643633869?thread_ts=1689880642.291459&cid=C049HHMV9SM) (@kbecciv missed pasting)

## Proposal
### Please re-state the problem that we are trying to solve in this issue.
Chat message is not center aligned vertically
### What is the root cause of that problem?
Issue happens on this line:
https://github.com/Expensify/App/blob/bc7f68962a2251fd51d5eba1da24cafd90dd790d/src/components/Reactions/ReportActionItemEmojiReactions.js#L73
So even if no reactions to show, 8px is always added
### What changes do you think we should make in order to solve the problem?
Early return null if totalReactionCount = 0
For this, we should run _map code first to calculate totalReactionCount earlier than return null

**Comment by anmurali** [comment] 2023-07-24 15:05
I am OOO for 10 days. Rotating the assigner.

**Comment by Abdelalim03** [comment] 2023-07-25 22:02
I would like to work on this issue
I'll ensure it'll be well aligned

**Comment by Abdelalim03** [comment] 2023-07-25 22:24
Contributor details
Your Expensify account email: ka_atoui@esi.dz
Upwork Profile Link: https://www.upwork.com/freelancers/~0107b91299bb95fd39

**Comment by Abdelalim03** [comment] 2023-07-25 22:25
Contributor details
Your Expensify account email: alloumaat03@gmail.com
Upwork Profile Link: https://www.upwork.com/freelancers/~0107b91299bb95fd39

**Comment by Santhosh-Sellavel** [comment] 2023-07-26 01:08
Straight forward one so going with the first [proposal](https://github.com/Expensify/App/issues/23350#issuecomment-1645472924)  to where I can infer the idea! Pretty much all proposals are similar. 

So let's go with @alitoshmatov here!

C+ Reviewed
🎀 👀 🎀 

@samh-nl Please refrain from modifying the proposal extensively. I see your proposal has multiple edits and the first version and last version is a completely different.

**Comment by Santhosh-Sellavel** [comment] 2023-07-26 01:11
I missed one it seems wait @pecanoro

**Comment by Santhosh-Sellavel** [comment] 2023-07-26 01:20
Actually, @situchan's [proposal](https://github.com/Expensify/App/issues/23350#issuecomment-1645674474) is a bit better than the rest.

> For this, we should run _map code first to calculate totalReactionCount earlier than return null

We don't need to do that, instead, we check props.emojiReactions isEmpty and return null

C+ Reviewed
🎀 👀 🎀

**Comment by Santhosh-Sellavel** [comment] 2023-07-26 01:21
Sorry @alitoshmatov!

**Comment by situchan** [comment] 2023-07-26 01:42
@Santhosh-Sellavel we cannot check `props.emojiReactions isEmpty` because of this line:
https://github.com/Expensify/App/blob/e32ff5e90fc5b70a802610d2401270f8c4ee03a1/src/components/Reactions/ReportActionItemEmojiReactions.js#L84-L86

What happens if `sortedReactions` is not empty and all return early here?
Then it will cause regression of showing only count and no reactions.

**Comment by alitoshmatov** [comment] 2023-07-26 04:09
@Santhosh-Sellavel Isn't it better just not to render the `ReportActionItemEmojiReactions` component?

**Comment by pecanoro** [comment] 2023-07-26 08:48
I think the problem is that messages are taking up a lot of space, right? I think I saw a discussion about this somewhere. I will take a look in Slack since it might be duplicate.

**Comment by pecanoro** [comment] 2023-07-26 08:57
@situchan You mentioned this bug is a regression of this PR (https://github.com/Expensify/App/pull/17996)? Can you confirm?

**Comment by pecanoro** [comment] 2023-07-26 09:00
@situchan Also, let me know if I am following correctly, in your proposal, you will be removing the gap, right?

**Comment by pecanoro** [comment] 2023-07-26 09:48
Hmm, I just think it was not intended to have that much space between messages, that's why I think we should remove the extra space instead of centering.

**Comment by shawnborton** [comment] 2023-07-26 16:34
Basically there should be no bug payout, we should figure out whoever introduced this and ask them to kindly fix it.

**Comment by situchan** [comment] 2023-07-26 16:36
https://github.com/Expensify/App/pull/17996 which caused regression is fairly big PR.
This is minor style issue and I can raise PR as soon as assigned.

**Comment by shawnborton** [comment] 2023-07-26 16:37
cc @stitesExpensify can you please take a look at this?

**Comment by Santhosh-Sellavel** [comment] 2023-07-26 17:43
Ah this a regression, sorry I missed that!

**Comment by Santhosh-Sellavel** [comment] 2023-08-02 20:40
This was handled as a regression cc: @stitesExpensify please take care of the checklist!

**Comment by stitesExpensify** [comment] 2023-08-02 22:08
done

**Comment by situchan** [comment] 2023-08-13 17:32
@bfitzexpensify sorry for late. reporting bonus is missing here

**Comment by situchan** [comment] 2023-10-08 14:22
> @bfitzexpensify sorry for late. reporting bonus is missing here

bump ^

**Comment by bfitzexpensify** [comment] 2023-10-09 14:05
Reopening this to action today

**Comment by bfitzexpensify** [comment] 2023-10-09 22:36
Offer sent @situchan

**Comment by bfitzexpensify** [comment] 2023-10-10 17:59
OK, payment complete, we can close this out again.

**Closed by bfitzexpensify** 2023-10-10 17:59 UTC
Labels: External, Daily, Needs Reproduction, Help Wanted, Awaiting Payment, Bug
