### ISSUE TITLE
[HOLD for payment 2024-04-15] [$250] mWeb - Task - Assigned to email id is cut off in task details page

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#38691] opened 2024-03-20 17:09 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.55
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**If this was caught during regression testing, add the test name, ID and link from TestRail:** N/A
**Issue reported by:** Applause - Internal Team

## Action Performed:
1. Go to https://staging.new.expensify.com/home
2. Tap on a report
3. Tap plus icon --- assign task
4. Enter title and tap next
5. Tap confirm task
6. Open the task to open task details page
7. Tap assignee
8. Select long email id without username

## Expected Result:
Assigned to email id must be fully visible in task details page

## Actual Result:
Assigned to email id is cut off in task details page

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [x] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [ ] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details> 

https://github.com/Expensify/App/assets/78819774/7e216adb-842e-4fbc-873e-c26feb2fe63c

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01e143012ae57472ed</li>
        <li>Upwork Job ID: 1773479387196997632</li>
        <li>Last Price Increase: 2024-03-28</li>
<li>Automatic offers: </li>
<ul>
<li>dukenv0307 | Reviewer | 0</li>
<li>Krishna2323 | Contributor | 0</li>
</ul></li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @mallenexpensify</details>

**Comment by lanitochka17** [comment] 2024-03-20 17:10
@mallenexpensify  FYI I haven't added the External label as I wasn't 100% sure about this issue. Please take a look and add the label if you agree it's a bug and can be handled by external contributors

**Comment by lanitochka17** [comment] 2024-03-20 17:10
We think that this bug might be related to #vip-vsp

**Comment by mallenexpensify** [comment] 2024-03-24 20:40
Checking on internally.  Not a high priority to get this fixed
https://expensify.slack.com/archives/C03TME82F/p1711312813672779

**Comment by mallenexpensify** [comment] 2024-03-28 22:37
Adding to #vip-vsb because it's not related to money.  It should be Polish there. @dukenv0307 this seems like it can be `External`, do you agree?

**Comment by Frey0-0** [comment] 2024-03-28 22:54
@mallenexpensify can I fix this issue with a PR for free without applying on upwork?

**Comment by mountiny** [comment] 2024-03-31 20:53
Watch out for applying the styles to the lower level components, it might introduce regressions

**Comment by mountiny** [comment] 2024-04-16 20:13
Should be ready to be paid $250 to @Krishna2323 and to @dukenv0307

**Comment by mallenexpensify** [comment] 2024-04-17 15:05
Thanks @dukenv0307 , closing

**Closed by mallenexpensify** 2024-04-17 15:05 UTC
Labels: External, Daily, Awaiting Payment, Bug
