### ISSUE TITLE
[Awaiting Payment March 20th] [$500] Report - The conversation scrolls to the beginning when you open the settings menu

### ISSUE THREAD

**Issue by izarutskaya** [Expensify/App#35763] opened 2024-02-03 21:34 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.36-0
**Reproducible in staging?:** Y
**Reproducible in production?:** N
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** Applause-Internal Team
**Slack conversation:**

## Action Performed:
1. Open https://staging.new.expensify.com/
2. Log in under your HT account A
3. Navigate to a conversation with more messages
4. Scroll to the top of your conversation history so that the last message is not visible
5. Open settings via avatar
6. Close the setting via the "Back" arrow

## Expected Result:
When you close the settings menu, the conversation should not restart and scroll back to the beginning.

## Actual Result:
The conversation scrolls to the beginning when you open the settings menu

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

https://github.com/Expensify/App/assets/115492554/3f6eb2b3-3f74-4d7b-b6e5-278cd8e79c66

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~0154928522b8004b1d</li>
        <li>Upwork Job ID: 1753894702380920832</li>
        <li>Last Price Increase: 2024-03-18</li>
<li>Automatic offers: </li>
<ul>
<li>akinwale | Reviewer | 0</li>
</ul></li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @trjExpensify</details>

**Comment by izarutskaya** [comment] 2024-02-03 21:36
We think that this bug might be related to #vip-vsb 
CC @quinthar

**Comment by sahilnagpal26** [comment] 2024-02-04 03:06
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
The conversation scrolls to the beginning when you open the settings menu

### What is the root cause of that problem?
This happens because when we press the back button, we call 
closeFullScreen which leads to this state https://github.com/Expensify/App/blob/3ab4e6e12d9ff38e69493321f0d31f032481b373/src/pages/settings/InitialSettingsPage.js#L347
### What changes do you think we should make in order to solve the problem?

We can instead use `Navaigation.dismissModal` on the press of the back button.
<img width="704" alt="Screenshot 2024-02-04 at 8 35 38 AM" src="https://github.com/Expensify/App/assets/137272892/5e4913f2-dc00-4f10-9873-43336b99ddba">

https://github.com/Expensify/App/blob/3ab4e6e12d9ff38e69493321f0d31f032481b373/src/libs/Navigation/Navigation.ts#L54-L60

### What alternative solutions did you explore? (Optional)

**Comment by mountiny** [comment] 2024-02-05 13:27
This does not need to be a blocker, user is not limited in use of the app

@akinwale please review the proposals once you will have time, thank you

**Comment by akinwale** [comment] 2024-02-06 08:26
@sahilnagpal26's [proposal](https://github.com/Expensify/App/issues/35763#issuecomment-1925562218) correctly identifies the root cause and the suggested solution is valid.

🎀👀🎀 C+ reviewed.

**Comment by sahilnagpal26** [comment] 2024-02-06 15:23
@akinwale As this is going to be my first contribution. I wanted to understand what should be my next action here? Should I create a PR For the same.

**Comment by akinwale** [comment] 2024-02-06 15:55
@sahilnagpal26 You will be assigned to the issue, but you can go ahead and create the PR so that you can get all the first-timer tasks done (signing the CLA, etc).

**Comment by neil-marcellini** [comment] 2024-02-06 22:16
> @sahilnagpal26's [proposal](https://github.com/Expensify/App/issues/35763#issuecomment-1925562218) correctly identifies the root cause and the suggested solution is valid.
> 
> 🎀👀🎀 C+ reviewed.

@sahilnagpal26 It seems like the solution probably works given that it's easy to test, but does it have unwanted side effects? I think the root cause analysis needs a lot more explanation. Why is `Navigation.closeFullScreen()` not the right approach? Why is it causing the report to scroll back to the latest message?

I want to make sure I understand this, given that I don't have much experience with our navigation system. Please edit your proposal and let me know when it's updated. Please refrain from creating a PR until you are assigned by an internal engineer.

**Comment by sahilnagpal26** [comment] 2024-02-08 23:35
## Proposal
[Updated](https://github.com/Expensify/App/issues/35763#issuecomment-1925562218)

**Comment by neil-marcellini** [comment] 2024-02-09 18:02
I will review the updated proposal today

**Comment by situchan** [comment] 2024-02-09 18:10
@adamgrzybowski can confirm if solution is fine

**Comment by neil-marcellini** [comment] 2024-02-10 00:03
@sahilnagpal26 thank you for updating your proposal with a better root cause explanation. It makes sense to me. However, I don't think your explanation of the solution is correct, regarding why openReport is not called.

> This internally invokes [StackActions.pop()](https://github.com/Expensify/App/blob/3ab4e6e12d9ff38e69493321f0d31f032481b373/src/libs/Navigation/dismissModal.ts#L15-L34). In this case when ReportScreen component is rendered, we already have the report prop. So, when [ReportActionsView](https://github.com/Expensify/App/blob/3ab4e6e12d9ff38e69493321f0d31f032481b373/src/pages/home/ReportScreen.js#L556C38-L564) which internally invokes [openReportIfNecessary](https://github.com/Expensify/App/blob/3ab4e6e12d9ff38e69493321f0d31f032481b373/src/pages/home/report/ReportActionsView.js#L105-L113). As [props.report.isOptimisticReport](https://github.com/Expensify/App/blob/3ab4e6e12d9ff38e69493321f0d31f032481b373/src/pages/home/report/ReportActionsView.js#L108) is true, it simply returns without invoking [Report.openReport(reportID)](https://github.com/Expensify/App/blob/3ab4e6e12d9ff38e69493321f0d31f032481b373/src/pages/home/report/ReportActionsView.js#L112) and hence the scroll is maintained.


It doesn't make sense that the report is optimistic. I think StackActions.pop() is popping the settings page, without popping/unmounting the report screen behind it, so the ReportScreen does not call openReportIfNecessary when it re-mounts here.
https://github.com/Expensify/App/blob/04795f9915e39edda75f7613030c7a3bf4e5cfed/src/pages/home/report/ReportActionsView.js#L115-L118

Maybe @adamgrzybowski can provide a more in depth explanation, but for now I'm happy with the current explanation and you can start on the PR.

**Comment by adamgrzybowski** [comment] 2024-02-12 12:10
Hey @hayata-suenaga isn't that a duplicate? https://github.com/Expensify/App/issues/35602 It looks similar to me

**Comment by situchan** [comment] 2024-02-12 12:16
Looks similar but accepted solution here doesn't fix https://github.com/Expensify/App/issues/35602

**Comment by adamgrzybowski** [comment] 2024-02-12 12:31
The `dismissModal` should be ok in that case. 

But there is one related problem. For some reason `pop()` is much slower than the `popToTop()`. 

I agree that we want to use `pop()` but not sure if we want to switch to it before fixing the performance problem. I'm currently looking into this

If I remember correctly @mountiny noticed the performance problem when we were working on the draft PR for ideal nav. Maybe he have some thought on this topic

**Comment by hayata-suenaga** [comment] 2024-02-12 16:01
> Hey @hayata-suenaga isn't that a duplicate? https://github.com/Expensify/App/issues/35602 It looks similar to me

The referenced issue pertains to the position of the chat list on the Left Hand Navigation (LHN), not the list of chat messages. While the issues may look similar, the solution for the linked issue does not resolve the problem described here.

**Comment by anmurali** [comment] 2024-02-16 15:23
Rotated the label since I will be OOO till 29th! I can take it back when I return!

**Comment by anmurali** [comment] 2024-02-16 15:25
Rotated the label since I will be OOO till 29th! I can take it back when I return! Thank you @trjExpensify

**Comment by trjExpensify** [comment] 2024-02-16 15:40
Lucky, lucky me! :) All good, looks like we're waiting for the PR to hit prod so we can start the clock on payment.

**Comment by situchan** [comment] 2024-02-20 15:06
This caused multiple regressions above ^

**Comment by sahilnagpal26** [comment] 2024-02-21 20:17
Hey team, what is exactly happening here? Is the solution breaking something?

**Comment by trjExpensify** [comment] 2024-02-21 22:47
yep, this PR was reverted as you can see here: https://github.com/Expensify/App/pull/36936

In that PR there are two issues that were flagged as deploy blockers as a result of the PR. So those need to be fixed in order to proceed with a new PR.

**Comment by trjExpensify** [comment] 2024-02-27 12:19
@sahilnagpal26 @akinwale what are the next steps here, and who's progressing them? Thanks!

**Comment by neil-marcellini** [comment] 2024-03-01 23:18
bump @sahilnagpal26. Would you please post a new proposal including the root cause of the regressions and an update solution?

**Comment by sahilnagpal26** [comment] 2024-03-05 01:58
@trjExpensify I will be working on this. Let me submit the proposal again for the same.

**Comment by trjExpensify** [comment] 2024-03-06 12:43
Please do, let's keep the urgency on this!

**Comment by trjExpensify** [comment] 2024-03-11 11:08
@sahilnagpal26 can we get an update and ETA from you, please?

**Comment by sahilnagpal26** [comment] 2024-03-13 18:51
@trjExpensify I am trying to figure out a solution, however, its taking time longer than I expected.

**Comment by trjExpensify** [comment] 2024-03-13 18:58
Appreciate the update. If you need to brainstorm, please do feel encouraged to use the #expensify-open-source channel and tag a few people that have been involved in the original PR(s).

**Comment by adamgrzybowski** [comment] 2024-03-14 14:20
@sahilnagpal26 Make sure that you have the newest changes. There were some changes related to the navigation in [this PR ](https://github.com/Expensify/App/pull/37421)

**Comment by trjExpensify** [comment] 2024-03-18 10:51
@sahilnagpal26 do you have a plan to address the issues this week?

**Comment by adamgrzybowski** [comment] 2024-03-18 12:16
@trjExpensify Something to check, but I think this issue may no longer exist after the release of ideal-nav-v2. At least I can't reproduce it.

**Comment by trjExpensify** [comment] 2024-03-19 13:51
Oh, good point! Because we've moved the settings page to the avatar in the bottom tab, we don't push a "full screen" modal on top of the chats list anymore with the recent changes, right? So then I think the question evolves to:

When you switch between the bottom tabs, should your scroll position in the chat be maintained? It doesn't look like that's the case on staging, but I think you would want that. 

https://github.com/Expensify/App/assets/16232057/b4f90d6e-f0fc-4634-b16d-273ef2cdb081

Equally, I think you want your scroll position to be maintained when switching between two chats though, but it also seems like that's not working either:

https://github.com/Expensify/App/assets/16232057/20a192e5-00d7-4399-b1c5-e07fb13a4028

@roryabraham @mountiny @luacmartins @JmillsExpensify, am I missing something (maybe comment linking related?) as to why maintaining the scroll position inside the chat might not be working? 🤔

**Comment by adamgrzybowski** [comment] 2024-03-19 14:10
@trjExpensify When we switch chats -> settings -> chats the second time we see a chat screen it is a different component than the first time we saw it. Event if it is the same report. 

This is done to achieve the desired history pattern in the browser.

The disadvantage of this solution is that because the scroll position is saved on the screen, it is reset after such navigation

If you would go back twice in the browser after that you would see that the initial scroll position is still there.


To solve similar problem for the BottomTabNavigator I created this [PR](https://github.com/Expensify/App/pull/38161#issuecomment-2003952663)
It use global context to have consistent scroll position between different screen components with the same params.

I think this solution potentially could be extended to cover the report screen cases.

**Comment by trjExpensify** [comment] 2024-03-19 14:36
Ah okay cool, so we have an issue for that PR to progress it. Would be good if it's extendable to cover the report screen cases, but we can look into that over there. 

Okay, so I think we can move to close this issue out now. We do need to settle up with @sahilnagpal26 & @akinwale for the initial work prior to the app changes. 

Payment summary as follows:

$125 to @sahilnagpal26 for the fix 
$125 to @akinwale for the C+ review

Two regressions ([1](https://github.com/Expensify/App/issues/36900), [2](https://github.com/Expensify/App/issues/36888)) came out of [the PR](https://github.com/Expensify/App/pull/36309), so deducted accordingly for each one per the [contributor guidelines](https://github.com/Expensify/App/issues/36888).

@akinwale, let me know I didn't miss anything on the above, and I'll go ahead and issue payments. 👍

**Comment by akinwale** [comment] 2024-03-19 14:40
@trjExpensify https://github.com/Expensify/App/issues/36888 was already a known issue prior to the PR being submitted as the performance problem was identified beforehand ([context](https://github.com/Expensify/App/issues/35763#issuecomment-1938592030)), so I think one regression deduction applies here.

**Comment by adamgrzybowski** [comment] 2024-03-19 15:55
@trjExpensify 

> Ah okay cool, so we have an issue for that PR to progress it. Would be good if it's extendable to cover the report screen cases, but we can look into that over there.

I would merge the PR for scroll on the HOME page and ask somebody from SWM to use this code to create similar solution for the report screen scroll. 

Do you want to create and issue for that?

**Comment by trjExpensify** [comment] 2024-03-20 18:19
>@trjExpensify https://github.com/Expensify/App/issues/36888 was already a known issue prior to the PR being submitted as the performance problem was identified beforehand (https://github.com/Expensify/App/issues/35763#issuecomment-1938592030), so I think one regression deduction applies here.

Ah okay, got it. Cool, updated the payment summary. Offers sent to you both!

**Comment by akinwale** [comment] 2024-03-20 18:20
@trjExpensify Accepted. Thanks!

**Comment by trjExpensify** [comment] 2024-03-20 18:21
>@trjExpensify with the chats I guess it depends, you can see Slack keeps the position. WhatsApp desktop does not though, I think we can explore how to solve this but we need to make sure it will solve well and would not hurt performance even if we would store the position for many reports (or put some limit on 10 latest visited reports for example.)

Yeah, maybe we can bring this out for a discussion in somewhere like #vip-vsb to decide what we want to do. I agree we don't want to take a performance hit, but I do think keeping the position will be desirable when we use this a lot for all of our business chat purposes where you're switching a lot.

**Comment by trjExpensify** [comment] 2024-03-20 18:22
> @trjExpensify Accepted. Thanks!

Paid!

**Comment by trjExpensify** [comment] 2024-03-22 13:41
@sahilnagpal26 waiting for you to accept the offer.

**Comment by trjExpensify** [comment] 2024-03-25 11:11
@sahilnagpal26 paid. Closing!

**Closed by trjExpensify** 2024-03-25 11:11 UTC
Labels: External, Engineering, Daily, Overdue, Awaiting Payment, Bug
