### ISSUE TITLE
[$500] Split  - "Tab Highlight" is not centered in Split bill flow

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#34524] opened 2024-01-15 18:35 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.25-1
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** Applause - Internal Team
**Slack conversation:**

## Action Performed:
1. Access staging.new.expensify.com or open the Desktop app
2. Sign into a valid account
3. Create a group chat
4. Click on plus icon > split bill
5. Enter amount to go to confirm page
6. Click on checkbox of one member
7. Click on "Tab" and highlight the checkbox

## Expected Result:
User expects the checkbox to be centered when highlighted

## Actual Result:
The checkbox is completely off center and slightly cuts off the circular checkbox

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details> 

<img width="1440" alt="Bug6343268_1705341012689!Highlighted_check_box_" src="https://github.com/Expensify/App/assets/78819774/722f62ab-9b84-4441-8f36-6ac3ad142fe9">

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01d2bb24f7d4def822</li>
        <li>Upwork Job ID: 1746964433022115840</li>
        <li>Last Price Increase: 2024-01-15</li>
    </ul>
</details>

**Comment by bernhardoj** [comment] 2024-01-16 03:43
Dupe of https://github.com/Expensify/App/issues/32400

**Comment by abdulrahuman5196** [comment] 2024-01-22 11:12
> Dupe of #32400

@miljakljajic We should put this issue on hold, referring to #32400

**Comment by miljakljajic** [comment] 2024-01-22 14:39
No problem - we can close and re-open if it is still an issue once https://github.com/Expensify/App/issues/32400 is resolved.

**Closed by miljakljajic** 2024-01-22 14:39 UTC
Labels: External, Daily, Help Wanted, Bug
