### ISSUE TITLE
Chat-Sign * is not displayed in the message if this message consists only of emojis

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#20017] opened 2023-06-02 00:22 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Go to URL https://staging.new.expensify.com/
2. Login with any account
3. Go to any chat
2. Send message that consists of only three emojis
3. Click Edit message
4. Add some * between emojis

## Expected Result:
If we consider * as a markdown (bold), then it does nothing for emoticons and it need to be displayed in the message (as in Slack for example).

## Actual Result:
Sign * is not displayed in the message if this message consists only of emojis

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android / native
- [x] Android / Chrome
- [x] iOS / native
- [x] iOS / Safari
- [x] MacOS / Chrome / Safari
- [x] MacOS / Desktop

**Version Number:** 1.3.22.0

**Reproducible in staging?:** Yes

**Reproducible in production?:** Yes

**If this was caught during regression testing, add the test name, ID and link from TestRail:**

**Email or phone of affected tester (no customers):**

**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/78819774/4d910fe1-ab36-4939-9295-5d1927e924d9

**Expensify/Expensify Issue URL:**

**Issue reported by:** Applause - Internal Team

**Slack conversation:**

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by eh2077** [comment] 2023-06-02 03:13
## Proposal

### Please re-state the problem that we are trying to solve in this issue.

`*` is not displayed in the message if this message consists only of emojis.

### What is the root cause of that problem?

The root cause of this issue is that we render bold syntax for text consists only of emojis. For example input

```
*😄*😄*😄*
```

is translated into html

```html
<strong>😄</strong>😄<strong>😄</strong>
```

### What changes do you think we should make in order to solve the problem?

To fix this issue, we should skip rendering bold syntax if the text only consists of emojis. To achieve this, we can define a new regex `EMOJIS_ALL` after this [line](https://github.com/Expensify/expensify-common/blob/925e62744f784a92c3ad8947aabfc21c93bec221/lib/CONST.jsx#L340) 

```js
EMOJIS_ALL: /^([\p{Extended_Pictographic}\u200d\u{1f1e6}-\u{1f1ff}\u{1f3fb}-\u{1f3ff}\u{e0020}-\u{e007f}\u20E3\uFE0F]|[#*0-9]\uFE0F?\u20E3)*$/gu,
```

to check if text consists of only emojis. And check if the text part of bold syntax contains emojis only in the [replacement method](https://github.com/Expensify/expensify-common/blob/925e62744f784a92c3ad8947aabfc21c93bec221/lib/ExpensiMark.js#L193)

We change it

```js
replacement: (match, g1) => (g1.includes('<pre>') || this.containsNonPairTag(g1) ? match : `<strong>${g1}</strong>`),
```

to

```js
replacement: (match, g1) => {
    // We remove spaces in g1 before test regex EMOJIS_ALL
    if (g1.replace(/\s/g, '').match(CONST.REG_EXP.EMOJIS_ALL)) {
        return match;
    }
    return g1.includes('<pre>') || this.containsNonPairTag(g1) ? match : `<strong>${g1}</strong>`;
},
```

By doing so, we won't render bold syntax for input

```
*😄*😄*😄*
```

and won't break existing unit test cases of expensify-common.

If you want to verify more corner cases of this issue, below test cases will be helpful

```
*😄😄😄*
```

```
*😄😄 😄*
```

```
*😄😄😄
😄😄😄*
```

`italic` and `strikethrough` rule have similar issue, so we can apply same fix for them as well.

### What alternative solutions did you explore? (Optional)

N/A

**Comment by alexpensify** [comment] 2023-06-02 20:23
I'll test soon

**Comment by alexpensify** [comment] 2023-06-04 16:10
@mountiny and @aimane-chnaif -- Based on this GH: https://github.com/Expensify/App/issues/14676#issuecomment-1571973632 I think we should close this GH. We are planning to not allow formating, right? Please let me know if I'm wrong and we can keep this one open.

**Comment by mountiny** [comment] 2023-06-05 13:25
yes, I think we can close this super narrow usecase

**Closed by mountiny** 2023-06-05 13:25 UTC
Labels: Daily, Bug
