### ISSUE TITLE
[HOLD for payment 2023-07-21] [$1000] Long Pressing on reply opens the context menu for the ReportPreview action.

### ISSUE THREAD

**Issue by kavimuru** [Expensify/App#21292] opened 2023-06-22 02:42 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Open a DM with any user.
2. Send a Money request.
3. Long Press on the `reply 1` on the preview of money request in the DM.
4. Observe the behaviour.
## Expected Result: 
It should not open the context menu on the IOU Preview like other platforms.
## Actual Result: 
It opens the context menu on Android chrome but other platforms does not open it.
## Workaround:
Can the user still use Expensify without this being fixed? Have you informed them of the workaround?

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [x] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [ ] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 1.3.30-5
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/43996225/786779b0-e447-4d98-a53d-4bcd45304da1

https://github.com/Expensify/App/assets/43996225/d6c65fd2-00ba-4731-8853-26187925b9ae

**Expensify/Expensify Issue URL:**
**Issue reported by:** @parasharrajat 
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1686834876030139

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~0164ddcb49f1eae0da</li>
        <li>Upwork Job ID: 1672146114797383680</li>
        <li>Last Price Increase: 2023-07-07</li>
    </ul>
</details>

**Comment by ShogunFire** [comment] 2023-06-25 00:14
I don't think this is a bug, it acts this way for any comment and long pressing on mobile is the equivalent of right clicking on other platforms which also open the context menu. @eVoloshchak  am I missing something ?

**Comment by bfitzexpensify** [comment] 2023-06-26 07:02
@ShogunFire is right, I didn't realise that was the way to right-click on an Android. The behaviour is the same, and I don't think it opening the context menu the same way as right-clicking elsewhere on the message does is unexpected. I agree this isn't a bug and I'm going to close this out.

**Comment by bfitzexpensify** [comment] 2023-06-26 10:44
>Right-click and long-press are two different gestures. We can also have a long press on the web if we want.

Huh, I didn't know this! I thought they were the same thing. Appreciate the clarification. Given that, I agree that this is in fact a bug. Let's reopen.

**Comment by ShogunFire** [comment] 2023-06-26 12:39
@parasharrajat Sorry, I hadn't tried on android and ios so I agree that there is an inconsistency. However long press and right clicks are handled by the same component and are calling the same method in PressableWithSecondaryInteraction so I still think they should act the same. Can you confirm the expected behaviour ? Should we show the contextmenu or not on mweb/android/ios and under what condition ? Should we only disable it for thread preview ?

**Comment by ShogunFire** [comment] 2023-06-26 15:01
## Proposal

### Please re-state the problem that we are trying to solve in this issue.

On mobile web the context menu appears when we long press "x replies" line whereas on android and ios it doesn't

### What is the root cause of that problem?

For android and ios we don't handle the long press event here:

https://github.com/Expensify/App/blob/e6c4b4e2f0bf9f42e57bebdd7720ee776ab6c93a/src/pages/home/report/ReportActionItemThread.js#L42-L48

So when we long press nothing happens (because this Pressable has the priority on the PressableWithSecondaryInteraction present in ReportActionItem)

The reason the context menu still shows when we long press on mobile web is because here:
https://github.com/Expensify/App/blob/1e308ca7eb8771acc468d8dde45a770c435c1b66/src/components/PressableWithSecondaryInteraction/index.js#L27

We add a listener on the contextmenu event and this contextmenu event fires on long press on mobile web. 

This listener is not removed by PressableWithoutFeedback so it still fires


### What changes do you think we should make in order to solve the problem?

I have 3 solutions depending on what we want:

1) If we don't want to show the contextmenu on long press on mobile web we have to remove the listener on contextmenu in PressableWithoutFeedback if we are on touchscreen

2) If we want we can also change the condition here 
https://github.com/Expensify/App/blob/1e308ca7eb8771acc468d8dde45a770c435c1b66/src/pages/home/report/ReportActionItem.js#L453

to prevent the contextMenu when the item has a thread and we are on touchscreen but this will prevent the context menu on the whole item and not just the "x replies" line.


3) If we want to show the contextmenu when we long press on android and ios what we could do is add a  boolean props to BaseGenericPressable that says that we should propagate the longclick event here

https://github.com/Expensify/App/blob/1e308ca7eb8771acc468d8dde45a770c435c1b66/src/components/Pressable/GenericPressable/BaseGenericPressable.js#L67C24-L67C24

because right now it doesn't propagate the event if we don't have a prop onLongPress (we could also pass an empty onLongPress but that's a little weird)

### What alternative solutions did you explore? (Optional)

**Comment by bfitzexpensify** [comment] 2023-06-29 06:35
@eVoloshchak proposal from @ShogunFire ready for review when you get a chance

**Comment by ShogunFire** [comment] 2023-06-29 18:14
@eVoloshchak To be honest I haven't tried my proposals, I think we should know exactly what is the expected behaviour because I am not sure the behaviour on android and ios was intentional.

**Comment by eVoloshchak** [comment] 2023-07-02 20:20
@ShogunFire, expected result - is the same behavior on all platforms (i.e. it should show context menu on long press, as it does on mWeb Chrome)

> If we want to show the contextmenu when we long press on android and ios what we could do is add a boolean props to BaseGenericPressable that says that we should propagate the longclick event, because right now it doesn't propagate the event if we don't have a prop onLongPress (we could also pass an empty onLongPress but that's a little weird)

Could you elaborate on that more please? Why is working fine on mWeb Chrome?

**Comment by ShogunFire** [comment] 2023-07-02 21:49
## Proposal
[Updated](https://github.com/Expensify/App/issues/21292#issuecomment-1607669678)

**Comment by ShogunFire** [comment] 2023-07-02 21:51
@eVoloshchak 
> Could you elaborate on that more please? Why is working fine on mWeb Chrome?
On mWeb chrome it doesn't use the long press event to fire the secondaryinteraction it uses the context menu event that is fired by browsers.

And sorry my first proposal was wrong I haven't found a way to propagate the long press event between pressable

**Comment by eVoloshchak** [comment] 2023-07-06 16:28
@ShogunFire
> pass a new prop onSecondaryInteraction to ReportActionItemThread like this

I think that's the correct approach, updated proposal looks much better
> Then in ReportActionItemThread replace the PressableWithoutFeedback by a PressableWithSecondaryInteraction and pass it the function like this

Is there a reason for that? `PressableWithoutFeedback` seems to have an `onLongPress` handler already

**Comment by ShogunFire** [comment] 2023-07-06 22:27
@eVoloshchak If I remember correctly it was because with PressableWithoutFeedback  the long press was also working for web  and desktop which we don't want

**Comment by eVoloshchak** [comment] 2023-07-10 14:31
>  the long press was also working for web and desktop 

We need long press to work for mobile web, we can figure out the exact component during the review

Yeah, let's proceed with @ShogunFire's proposal!
cc: @bfitzexpensify 
🎀👀🎀 C+ reviewed!

**Comment by ShogunFire** [comment] 2023-07-11 18:46
Ready for review

**Comment by ShogunFire** [comment] 2023-07-23 16:46
Hello @kavimuru I have accepted the job on upwork, can you make the final paiement ? Thanks

**Comment by bfitzexpensify** [comment] 2023-07-24 12:21
Payment made. @parasharrajat and @eVoloshchak are both receiving payments via New Dot. @eVoloshchak a reminder to complete the BZ checklist when you get a chance

**Comment by eVoloshchak** [comment] 2023-07-25 16:05
- The PR that introduced the bug has been identified. Link to the PR: while this was technically caused by https://github.com/Expensify/App/pull/18274 (the PR in which thread component was created), it just surfaced the limitation of Pressable, not caused the bug in the first place

- The offending PR has been commented on, pointing out the bug it caused and why, so the author and reviewers can learn from the mistake. Link to comment: N/A

- A discussion in #expensify-bugs has been started about whether any other steps should be taken (e.g. updating the PR review checklist) in order to catch this type of bug sooner. Link to discussion: this is a fairly simple bug, not sure if an additional discussion is needed here

- Determine if we should create a regression test for this bug
Is it easy to test for this bug? Yes
Is the bug related to an important user flow? No
Is it an impactful bug? No
The bug has a very low impact, doesn't break the usage of the app, I don't think we should add a regression test

**Comment by JmillsExpensify** [comment] 2023-07-27 03:57
@bfitzexpensify Can you please summarize the appropriate individual payments for all parties involved in this issue? This is holding up @eVoloshchak's and @parasharrajat's NewDot payments. More information on this compliance process [in Slack](https://expensify.slack.com/archives/C01SKUP7QR0/p1690321157273869).

**Comment by bfitzexpensify** [comment] 2023-07-27 12:49
Sure, @JmillsExpensify these are the payments due:

@parasharrajat - $250 reporting payment
@eVoloshchak - $1500 for C+ and #urgency bonus 
@ShogunFire  - $1500 for contributor and #urgency bonus (paid via upwork ✅)

**Comment by bfitzexpensify** [comment] 2023-07-27 12:50
Agreed with your reasoning re: not needing a regression test @eVoloshchak. We're good to close this out - thanks for the work everyone!

**Closed by bfitzexpensify** 2023-07-27 12:50 UTC
Labels: External, Engineering, Daily, Awaiting Payment, Bug

**Comment by JmillsExpensify** [comment] 2023-07-27 22:51
Reviewed details for @parasharrajat and @eVoloshchak. This is accurate based on summary from Business Reviewer and approved for payment in NewDot.
