### ISSUE TITLE
[CSV Export] [$250] Expense - "exported to CSV" system message from Old Dot is grayed out when opened in thread

### ISSUE THREAD

**Issue by IuliiaHerets** [Expensify/App#47487] opened 2024-08-15 07:55 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** v9.0.20-6
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**If this was caught during regression testing, add the test name, ID and link from TestRail:** Exp https://expensify.testrail.io/index.php?/tests/view/4859054
**Email or phone of affected tester (no customers):** applausetester+kh050806@applause.expensifail.com
**Issue reported by:** Applause Internal Team

## Action Performed:
1. Go to staging.new.expensify.com
2. Go to workspace chat.
3. Submit an expense and pay it.
4. Go to Old Dot.
5. Open the report from Step 3.
6. Export the report to CSV on Old Dot.
7. Go back to New Dot and open the expense report.
8. Right click on "exported to CSV" system message > Reply in thread.

## Expected Result:
The thread report for "exported to CSV" system message will not gray out when opened in thread.

## Actual Result:
The thread report for "exported to CSV" system message grays out when opened in thread. The composer is hidden and LHN report is grayed out with RBR.

## Workaround:
Unknown

## Platforms:

- [x] Android: Native
- [x] Android: mWeb Chrome
- [x] iOS: Native
- [x] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

https://github.com/user-attachments/assets/d48e2229-0401-49d3-87bf-b8fcaa251b56

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01b73023c08c503365</li>
        <li>Upwork Job ID: 1824271785837230517</li>
        <li>Last Price Increase: 2024-08-23</li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @aimane-chnaif</details>

**Comment by IuliiaHerets** [comment] 2024-08-15 07:56
We think that this bug might be related to #wave-collect - Release 1

**Comment by IuliiaHerets** [comment] 2024-08-15 07:56
@stephanieelliott  FYI I haven't added the External label as I wasn't 100% sure about this issue. Please take a look and add the label if you agree it's a bug and can be handled by external contributors

**Comment by stephanieelliott** [comment] 2024-08-16 02:27
I suspected the chat was greyed out due to `no activity yet` but these messages show up as normal in other contexts ([example](https://expensify.slack.com/archives/C036QM0SLJK/p1718278472811379?thread_ts=1718278037.278499&cid=C036QM0SLJK)). So this does seem like a bug

**Comment by sandipanghos** [comment] 2024-08-18 14:40
**Proposal**
Please re-state the problem that we are trying to solve in this issue.
"exported to CSV" system message from Old Dot is grayed out when opened in thread 


**What is the root cause of that problem?**
each rowItem in sidebar is checking opacity using the condition "**needsOpacity**"
https://github.com/Expensify/App/blob/62722e8bc636f1be2e2c9e8e980aac93b76804c9/src/components/OfflineWithFeedback.tsx#L88
 in **OfflineWithFeedback** component and applying "opacity:styles.offlineFeedback.pending" which is value 0.5.
condition . https://github.com/Expensify/App/blob/62722e8bc636f1be2e2c9e8e980aac93b76804c9/src/components/OfflineWithFeedback.tsx#L129

this causes the rowitem "exported to CSV" to be grayed out as opacity :0.5 is applied
[
<img width="896" alt="Screenshot 2024-08-18 at 7 50 10 PM" src="https://github.com/user-attachments/assets/bef437e6-7db3-4e01-9ab0-f2fe1a30f83f">
](url)




**What changes do you think we should make in order to solve the problem?**
We can add in  **shouldDisableOpacity={true}** in  **OptionRowLHN**  component in line no 142 to force the disabling the opacity

` <OfflineWithFeedback
            pendingAction={optionItem.pendingAction}
            errors={optionItem.allReportErrors}
            shouldShowErrorMessages={false}
            needsOffscreenAlphaCompositing
            shouldDisableOpacity={true}
        >`

**Result** 
the video of the fixed
https://drive.google.com/file/d/1XbDIZEk2z2sLZFX9MlassZXTil-7JD9G/view?usp=sharing

**Comment by sandipanghos** [comment] 2024-08-18 14:55
@aimane-chnaif @stephanieelliott stephanieelliott
hi
 this is my first proposal . Let me know if fix you approve or any problem in proposal template.
at first time while posting the proposal got dismissed as the template was not followed. so i added proposal again.
Hope this is following guideline.
Can i add proposal again if dismissed once?

**Comment by sandipanghos** [comment] 2024-08-18 14:58
## Proposal


### Please re-state the problem that we are trying to solve in this issue.
"exported to CSV" system message from Old Dot is grayed out when opened in thread 

### What is the root cause of that problem?

each rowItem in sidebar is checking opacity using the condition "**needsOpacity**"
 in **OfflineWithFeedback** component and applying "opacity:styles.offlineFeedback.pending" which is value 0.5.

this causes the rowitem "exported to CSV" to be grayed out as opacity :0.5 is applied
[
<img width="896" alt="Screenshot 2024-08-18 at 7 50 10 PM" src="https://github.com/user-attachments/assets/bef437e6-7db3-4e01-9ab0-f2fe1a30f83f">
](url)

### What changes do you think we should make in order to solve the problem?
We can add this prop  **shouldDisableOpacity={true}** in  component **OfflineWithFeedback**  in **OptionRowLHN.tsx**  in line no 142 to force the disabling the opacity
<img width="754" alt="Screenshot 2024-08-18 at 8 19 17 PM" src="https://github.com/user-attachments/assets/3b359608-a977-4e17-9c73-c634baa94c6a">


### What alternative solutions did you explore? (Optional)


**Result** 
the video of the fixed
https://drive.google.com/file/d/1XbDIZEk2z2sLZFX9MlassZXTil-7JD9G/view?usp=sharing

**Comment by sandipanghos** [comment] 2024-08-18 15:04
## Proposal


### Please re-state the problem that we are trying to solve in this issue.
"exported to CSV" system message from Old Dot is grayed out when opened in thread 

### What is the root cause of that problem?

each rowItem in sidebar is checking opacity using the condition "**needsOpacity**"
 in **OfflineWithFeedback** component and applying "opacity:styles.offlineFeedback.pending" which is value 0.5.

this causes the rowitem "exported to CSV" to be grayed out as opacity :0.5 is applied
[
<img width="896" alt="Screenshot 2024-08-18 at 7 50 10 PM" src="https://github.com/user-attachments/assets/bef437e6-7db3-4e01-9ab0-f2fe1a30f83f">
](url)

### What changes do you think we should make in order to solve the problem?
We can add this prop  **shouldDisableOpacity={true}** in  component **OfflineWithFeedback**  in **OptionRowLHN.tsx**  in line no 142 to force the disabling the opacity
<img width="754" alt="Screenshot 2024-08-18 at 8 19 17 PM" src="https://github.com/user-attachments/assets/3b359608-a977-4e17-9c73-c634baa94c6a">


### What alternative solutions did you explore? (Optional)


**Result** 
the video of the fixed
https://drive.google.com/file/d/18laltS3zlKJ1bEG-rXWSBnDeURYkG8tL/view?usp=sharing

![Uploading Screenshot 2024-08-18 at 8.33.59 PM.png…]()

**Comment by sandipanghos** [comment] 2024-08-19 21:43
> @sandipanghos thanks for the proposal. Your RCA isn't correct.

Please review the updated RCA. I have edited it. Where it is incorrect? is it the format is wrong or the logic is not proper?

**Comment by tushar-a-b** [comment] 2024-08-21 10:36
This is a backend issue since we are getting error from backend when we click on `Reply in thread` only for message `exported this report to CSV` we get when we export from `OD`, refer below image: 

<img width="1680" alt="Screenshot 2024-08-21 at 5 33 43 AM" src="https://github.com/user-attachments/assets/f62e9c9d-5cc2-4241-860d-e3c46d631911">

since we have error we are showing RBR and applying opacity below: 
Opacity: 

https://github.com/Expensify/App/blob/685bb4c7bbaa2ef332896de5cace193edb9c6a51/src/components/OfflineWithFeedback.tsx#L83
https://github.com/Expensify/App/blob/685bb4c7bbaa2ef332896de5cace193edb9c6a51/src/components/OfflineWithFeedback.tsx#L88
https://github.com/Expensify/App/blob/685bb4c7bbaa2ef332896de5cace193edb9c6a51/src/components/OfflineWithFeedback.tsx#L128-L131

RBR: 
https://github.com/Expensify/App/blob/685bb4c7bbaa2ef332896de5cace193edb9c6a51/src/components/LHNOptionsList/OptionRowLHN.tsx#L263-L271

**Comment by NikkiWines** [comment] 2024-08-22 20:55
I'll take a look at this issue next week

**Comment by trjExpensify** [comment] 2024-08-26 13:21
CC: @rlinoz for vis as well 👀

**Comment by rlinoz** [comment] 2024-08-26 14:35
Hmm in OldDot we use a different command but they seem to have the same logic when adding the report action.. anyway let me know if I can help @NikkiWines

**Comment by rlinoz** [comment] 2024-08-26 15:50
Talked to Nikki and I am taking over this one

**Comment by stephanieelliott** [comment] 2024-08-28 00:49
PR was merged to main

**Comment by stephanieelliott** [comment] 2024-09-04 02:33
PR was deployed to Auth (production/authrock). Seems like both the PR and review were internal, so no payment due here? Please comment if I missed someone though!

**Closed by stephanieelliott** 2024-09-04 02:33 UTC
Labels: Reviewing, Weekly, Internal, Bug
