### ISSUE TITLE
[$250] [FT] Onboarding flow: Ensure inviteTeam task is auto-marked as complete once action has been taken 

### ISSUE THREAD

**Issue by CherylWalsh** [Expensify/App#44397] opened 2024-06-25 14:42 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:**
**Reproducible in staging?:** YES
**Reproducible in production?:** YES
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:**
**Slack conversation:** https://expensify.slack.com/archives/C036QM0SLJK/p1717780152087829

## Action Performed:
Presentation page [here](https://docs.google.com/presentation/d/1G59R6tjWiAKUQqp_52tHNcbYvgcc8QvQYPhUeQPzcPw/edit#slide=id.g2e33672ab10_0_155)

- Onboarding flow was completed on staging.new.expensify.com 

- Onboarding flow was for "manage my team expenses" intent. 

- Onboarding checklist had multiple tasks 

- On Web: All tasks had to manually marked as completed in order to 'complete' the onboarding 
- On Mobile: Most tasks were auto-marked as completed except for 'Invite my team" task.  

- All tasks for web/mobile should be auto-marked as complete when an action has been taken. 

## Expected Result:

Once an action was taken, tasks should be auto-checked as completed, without the user having to manually mark them as complete. 

## Actual Result:

For each of the tasks, once an action has been taken and you're back to the onboarding checklist page, they will be in the 'incomplete' state unless you mark them as complete. 

## Workaround:
Can the user still use Expensify without this being fixed? Have you informed them of the workaround?
The workaround is to manually mark them off, but we want them auto-marked off. 

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [x] Android: mWeb Chrome
- [x] iOS: Native
- [x] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

Here is the list of tasks: 
![Screenshot 2024-06-25 at 15 46 03](https://github.com/Expensify/App/assets/58196921/48242384-66d1-43b8-a171-851c6f15788c)

If you need them to be crossed off, you need to check the box on each task so they are 'marked as complete' 
![Screenshot 2024-06-25 at 15 48 22](https://github.com/Expensify/App/assets/58196921/4744635f-508b-4e39-8a33-6fc83cefc1fd)

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~0114bd93f0716778b1</li>
        <li>Upwork Job ID: 1805616622117918962</li>
        <li>Last Price Increase: 2024-07-02</li>
    </ul>
</details>

**Comment by LLPeckham** [comment] 2024-06-25 14:46
Screenshot from iOS mobile app flow -- The only task that doesn't auto-mark as complete is the `Invite your team` task (as opposed to the web flow where most of the tasks are not auto-marked as complete) 

<img width="1047" alt="Screenshot 2024-06-25 at 3 45 28 PM" src="https://github.com/Expensify/App/assets/6799061/1724449d-fce5-4dd5-b45a-ba4174893311">

**Comment by CherylWalsh** [comment] 2024-06-25 14:54
@joekaufmanexpensify I'm not on bug zero so I apologise for not knowing the answer here. But is this 'internal' or 'external'? It's definintely a bug I'm just not sure what label to use.

**Comment by joekaufmanexpensify** [comment] 2024-06-25 14:58
Seems like a frontend issue, so I would expect it to be external.

**Comment by diegohosilver** [comment] 2024-06-25 16:08
_Split an expense_ seems to work in web (stage). It takes a few seconds but eventually the task is checked.

https://github.com/Expensify/App/assets/20136219/790ed7c9-45b5-4868-9f9e-559e0c5d93b0

**Comment by diegohosilver** [comment] 2024-06-25 16:09
Contributor details
Your Expensify account email: diegohosilver@gmail.com
Upwork Profile Link:[ ](https://www.upwork.com/freelancers/~019c1574289b92da37)

**Comment by diegohosilver** [comment] 2024-06-25 16:10
Contributor details
Your Expensify account email: diegohosilver@gmail.com
Upwork Profile Link: https://www.upwork.com/freelancers/~019c1574289b92da37

**Comment by diegohosilver** [comment] 2024-06-25 21:07
> _Split an expense_ seems to work in web (stage). It takes a few seconds but eventually the task is checked.
> 
>  evidence.720.mov

After further testing I see the same results in dev and staging (web) and the ios app. The _Invite your team_ is not being checked, but the rest are.

![Screenshot 2024-06-25 at 5 31 52 PM](https://github.com/Expensify/App/assets/20136219/e9fa05a4-5f5e-4c8a-9278-fb6a5254b82a)
![Screenshot 2024-06-25 at 5 32 02 PM](https://github.com/Expensify/App/assets/20136219/a435ac54-06d6-4b75-8c1e-5c8b64fba7ad)
![msg132086238-286456](https://github.com/Expensify/App/assets/20136219/c449b0b0-e153-4e73-b3bc-32833f2f84ba)

**Comment by nyomanjyotisa** [comment] 2024-06-26 01:46
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
Ensure all tasks are getting auto-marked as complete once action has been taken
Invite your time not auto-marked as complete once action has been taken

### What is the root cause of that problem?
There is no the following onyxData on either AddMembersToWorkspace or GetMissingOnyxMessages request response, so the Invite your time is not auto-marked as complete.
especially the childStateNum: 2 & childStatusNum: 3 that will be mark the task as completed

```
        }
            "key": "reportActions_[id]",
            "onyxMethod": "merge",
            "value": {
                "[reportActionID]": {
                    "childCommenterCount": 0,
                    "childLastActorAccountID": null,
                    "childLastMoneyRequestComment": null,
                    "childLastReceiptTransactionIDs": null,
                    "childLastVisibleActionCreated": "",
                    "childMoneyRequestCount": null,
                    "childOldestFourAccountIDs": "",
                    "childRecentReceiptTransactionIDs": null,
                    "childReportName": "Invite your team",
                    "childReportNotificationPreference": null,
                    "childStateNum": 2,
                    "childStatusNum": 3,
                    "childType": "task",
                    "childVisibleActionCount": 0
                }
            }
        }
```

### What changes do you think we should make in order to solve the problem?
This requires BE fix to include the above onyxData on the first AddMembersToWorkspace request response
And after the BE fix, I will check it again and fix it accordingly if needed

### What alternative solutions did you explore? (Optional)
N/A

**Comment by diegohosilver** [comment] 2024-06-26 01:49
@CherylWalsh I'm confident this is not a frontend issue. After several hours of debugging I found out that the `inviteTeam` task will not get updated after calling `AddMembersToWorkspace` endpoint.

I tried in different environments and even grabbed a commit from a month ago to see if this was a regresssion bug. All of them produced the same results.

As @nyomanjyotisa mentioned, this is def a backend issue

**Comment by joekaufmanexpensify** [comment] 2024-06-26 14:24
@allroundexperts do you agree this needs to be a BE fix?

**Comment by allroundexperts** [comment] 2024-06-26 14:58
Yes, this seems like a backend fix. However, shouldn't we handle the offline case? When the members are added to a workspace, should we optimistically complete the `inviteTeam` task?

**Comment by joekaufmanexpensify** [comment] 2024-06-28 15:25
>However, shouldn't we handle the offline case? When the members are added to a workspace, should we optimistically complete the inviteTeam task? If so, then we might need a frontend change as well.

For this, do you mean if someone completes one of these tasks while offline, optimistically mark the task as completed until they come back online?

**Comment by allroundexperts** [comment] 2024-06-28 15:27
Yes. That is what I mean.

**Comment by joekaufmanexpensify** [comment] 2024-07-01 13:59
Yeah, I would think we'd want this to work offline.

**Comment by allroundexperts** [comment] 2024-07-02 08:51
Reviewing again today.

**Comment by allroundexperts** [comment] 2024-07-03 19:46
Thanks for the update @nyomanjyotisa. Your updated [proposal](https://github.com/Expensify/App/issues/44397#issuecomment-2190376050) looks good to me!

🎀 👀 🎀 C+ reviewed

**Comment by joekaufmanexpensify** [comment] 2024-07-03 20:01
We're having an internal discussion [here](https://expensify.slack.com/archives/C036QM0SLJK/p1720010178538849?thread_ts=1719848162.761009&cid=C036QM0SLJK) about maybe only doing the backend portion of this. So let's hold off on assigning anyone for now until we resolve that.

**Comment by joekaufmanexpensify** [comment] 2024-07-08 15:09
We discussed this internally, and landed on not needing to make the other tasks optimistic. That wasn't originally in scope for this feature. All we need to focus on is fixing the auto-complete for `inviteTeam`, which should be the backend portion.

**Comment by joekaufmanexpensify** [comment] 2024-07-08 15:09
@rlinoz any interest in taking that backend piece, or should we look for another volunteer?

**Comment by joekaufmanexpensify** [comment] 2024-07-08 15:09
@rlinoz any interest in taking that backend piece, or should we look for another volunteer?

**Comment by mountiny** [comment] 2024-07-08 17:00
Coming from Slack, I can help fix the be inviteTeam task

**Comment by joekaufmanexpensify** [comment] 2024-07-09 14:08
@nyomanjyotisa We appreciate your time putting together a proposal. Since we decided not to move forward with making these tasks work optimistically at this time, you would not be compensated here, per our [contributing guidelines](https://github.com/Expensify/App/blob/main/contributingGuides/CONTRIBUTING.md). Let me know if you have any questions.

**Comment by joekaufmanexpensify** [comment] 2024-07-09 14:09
Auth PR is merged. @mountiny was that the only PR needed for this one? If so, I think we might be good to go here.

**Comment by mountiny** [comment] 2024-07-09 20:20
Yeah that should be the only PR needed to fix the autocompletion not working, the optimistic autocompletion is not implemented, just noting

**Comment by joekaufmanexpensify** [comment] 2024-07-09 20:33
Sweet, sounds good! The PR was deployed so closing this for now. TY everyone!

**Closed by joekaufmanexpensify** 2024-07-09 20:33 UTC
Labels: Reviewing, External, Weekly, Help Wanted, Bug
