### ISSUE TITLE
[$500] "Go back to home page" in LHN doesn't work when WS deleted from secondary device

### ISSUE THREAD

**Issue by kavimuru** [Expensify/App#36266] opened 2024-02-09 16:34 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.39-0
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** applause internal team
**Slack conversation:**

## Action Performed:
Prerequisite: Main and secondary devices logged in to the same user in New Expensify
1. [Main device] Create new Workspace
2. [Main device] Navigate to Members
3. [Secondary device] Delete Workspace created in Main device
4. [Main device] Click on "Go back to home page" in LHN

## Expected Result:
User should be redirected to Workspaces settings.

## Actual Result:
Nothing happens when user clicks on "Go back to home page" in LHN

## Workaround:
unknown
## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

https://github.com/Expensify/App/assets/43996225/361a1114-e588-4d3d-873d-4515b9ac4fd5

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~0170390297c07d44ce</li>
        <li>Upwork Job ID: 1755993628416561152</li>
        <li>Last Price Increase: 2024-02-16</li>
    </ul>
</details>

**Comment by kavimuru** [comment] 2024-02-09 16:36
We think that this bug might be related to #wave8-collect-admins

**Comment by jeremy-croff** [comment] 2024-02-09 18:45
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
The Go back to home page link is not taking you back home

### What is the root cause of that problem?
The link actions is defined to dismiss the modal it's expected to be in. The Component is FullPageNotFoundView

### What changes do you think we should make in order to solve the problem?
We updated the link action from `onLinkPress = () => Navigation.dismissModal()` to` () => Navigation.goBack(ROUTES.HOME) `
This way the action semantically matches the user text

### What alternative solutions did you explore? (Optional)

**Comment by godofoutcasts94** [comment] 2024-02-09 19:30
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
 "Go back to home page" in LHN doesn't work when WS deleted from 
### What is the root cause of that problem?

The link actions is defined to dismiss the modal it's expected to be in. The Component is FullPageNotFoundView. however we are not in a modal. This is part of navigation previous navigation changes.

In the `FullPageNotFoundView.tsx`, file i.e. here 

https://github.com/Expensify/App/blob/e6147ae106bb2686f7e755dd885af598b4239bdd/src/components/BlockingViews/FullPageNotFoundView.tsx#L55

we, are dismissing `modal`, instead of doing that, we need to route back to `Workspace Settings` Page.

### What changes do you think we should make in order to solve the problem?

To do that, or to move to `Workspace Settings` page. We need to add 

```
    onLinkPress = () => Navigation.goBack(ROUTES.SETTINGS_WORKSPACES),

```
So, that we are routed to `Workspace Settings` Page
Working Video of the Solution

- Before
<img width="1470" alt="Screenshot 2024-02-10 at 12 58 27 AM" src="https://github.com/Expensify/App/assets/158435970/b9542875-c3d9-4807-8e3a-23fd9ccd67e4">

- After 

Uploading Screen Recording 2024-02-10 at 12.58.42 AM.mov…

### What alternative solutions did you explore? (Optional)
N/A

**Comment by godofoutcasts94** [comment] 2024-02-09 19:31
Updated Proposal [](https://github.com/Expensify/App/issues/36266#issuecomment-1936488023) as video was not getting uploaded

**Comment by godofoutcasts94** [comment] 2024-02-09 19:33
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
 "Go back to home page" in LHN doesn't work when WS deleted from 
### What is the root cause of that problem?

In the `FullPageNotFoundView.tsx`, file i.e. here 

https://github.com/Expensify/App/blob/e6147ae106bb2686f7e755dd885af598b4239bdd/src/components/BlockingViews/FullPageNotFoundView.tsx#L55

we, are dismissing `modal`, instead of doing that, we need to route back to `Workspace Settings` Page.

### What changes do you think we should make in order to solve the problem?

To do that, or to move to `Workspace Settings` page. We need to add 

```
    onLinkPress = () => Navigation.goBack(ROUTES.SETTINGS_WORKSPACES),

```
So, that we are routed to `Workspace Settings` Page
Working Video of the Solution

- Before
<img width="1470" alt="Screenshot 2024-02-10 at 12 58 27 AM" src="https://github.com/Expensify/App/assets/158435970/b9542875-c3d9-4807-8e3a-23fd9ccd67e4">

- After 

https://github.com/Expensify/App/assets/158435970/ccfa4485-5960-4698-aba9-2ea90f9d207a

### What alternative solutions did you explore? (Optional)
N/A

**Comment by jeremy-croff** [comment] 2024-02-09 19:36
###Please re-state the problem that we are trying to solve in this issue.
The Go back to home page link is not taking you back home

##What is the root cause of that problem?
The link actions is defined to dismiss the modal it's expected to be in. The Component is FullPageNotFoundView. however we are not in a modal. This is part of navigation previous navigation changes.

##What changes do you think we should make in order to solve the problem?
If we want to navigate back to the workspace settings.

##We should update the link action from onLinkPress = () => Navigation.dismissModal() to() => Navigation.goBack(ROUTES.SETTINGS_WORKSPACES)
and add a new notFound link text with copy to navigate back. "Go back to the settings page" or anything determined by design. ( and spanish )

What alternative solutions did you explore? (Optional)

**Comment by godofoutcasts94** [comment] 2024-02-09 19:40
@jeremy-croff Just wanted to draw attention that, he updated his new proposal after, I have put mine

**Comment by jeremy-croff** [comment] 2024-02-09 19:46
> @jeremy-croff Just wanted to put it that, he just updated his new proposal after, I have put mine.

I added a second proposal for navigating to settings, since I believe yours is lacking. Instead of updated the original, to accurately reflect the order and not take advantage of you!

**Comment by godofoutcasts94** [comment] 2024-02-09 19:51
> > @jeremy-croff Just wanted to put it that, he just updated his new proposal after, I have put mine.
> 
> I added a second proposal for navigating to settings, since I believe yours is lacking. Instead of updated the original, to accurately reflect the order and not take advantage of you!

My proposal is lacking or not that should be rather decided by Expensify / Proposal Reviewing Team, but for the matter of fact, I believe that inital comments on the second proposal speaks something different, but I am not here to take up or hold any things against anyone. As the the reviewers think is right. I will accept it.

**Comment by jeremy-croff** [comment] 2024-02-09 20:07
> > > @jeremy-croff Just wanted to put it that, he just updated his new proposal after, I have put mine.
> > 
> > 
> > I added a second proposal for navigating to settings, since I believe yours is lacking. Instead of updated the original, to accurately reflect the order and not take advantage of you!
> 
> My proposal is lacking or not that should be rather decided by Expensify / Proposal Reviewing Team, but for the matter of fact, I believe that inital comments on the second proposal speaks something different, but I am not here to take up or hold any things against anyone. As the the reviewers think is right. I will accept it.

I have posted a second proposal after yours that is different from my original one because I am unsure of the expected behaviour to go back home, as the current text indicates, or if should go back to work space settings, like the github issue expects.
In the case that it should be workspace settings, i wanted to write a proposal seperately because it will be handled differently. This is independent of your proposal. If your proposal's solution matched mine I would've not posted mine.

My second proposal is different from yours, as we would avoid regression for a commonly re-used screen, as hardcoding a navigation action to settings ( like you proposed ) is specific to this flow, but not other error screens. I hope you agree that this is a key difference in our proposals and it is listed after yours, so no worry about first come first serve. This is purely a matter of solution chosen. 

I did not edit/add an alternative solution to my first proposal, precisely to respect the order and give you the first proposal regarding navigating to workspace-settings.

**Comment by DylanDylann** [comment] 2024-02-11 08:35
Hi everyone, I see that we have **two not-found pages in this case:**
1. Not found page on LHN
2. Not found page on the main screen

https://github.com/Expensify/App/assets/141406735/1a7c35c2-61be-46b5-b028-17df0b1f7c8c

The expected should be: When the user clicks "Go back to home page" on each of them, the App will redirect to the Workspace Setting page totally like this 

<img width="1440" alt="Screenshot 2024-02-11 at 15 31 10" src="https://github.com/Expensify/App/assets/141406735/5b429bcd-0bca-4129-9d0c-66d5b711f7bb">


Some contributors suggest that we should change the subtitle on both Not Found Page from "Go back to home page" to another one like "Go back to workspace setting page". But I think It fine to keep the old one 

@Expensify/design  Could you help to confirm the expected?

**Comment by godofoutcasts94** [comment] 2024-02-11 08:45
@DylanDylann, my solution doesn't focus on changing the subtitle or anything. My solution more focuses on 

> Hi everyone, I see that we have **two not-found pages in this case:**
> 
>     1. Not found page on LHN
> 
>     2. Not found page on the main screen
> 
> 
> Screen.Recording.2024-02-11.at.15.27.27.mov
> 
> The expected should be: When the user clicks "Go back to home page" on each of them, the App will redirect to the Workspace Setting page totally like this
> <img alt="Screenshot 2024-02-11 at 15 31 10" width="1440" src="https://private-user-images.githubusercontent.com/141406735/303907006-5b429bcd-0bca-4129-9d0c-66d5b711f7bb.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDc2NDA4NjksIm5iZiI6MTcwNzY0MDU2OSwicGF0aCI6Ii8xNDE0MDY3MzUvMzAzOTA3MDA2LTViNDI5YmNkLTBiY2EtNDEyOS05ZDBjLTY2ZDViNzExZjdiYi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMjExJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDIxMVQwODM2MDlaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1hZDc2Njk3YjliMmJiZTc0NDg1NzIwNmY0NDgzYjM0MjFkZjJhNzg5M2Q5MDMxZGY4NmNkMjlmODkxMjZjNjNmJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.InIHjRkKTASWDPBUW-0vrtsdNKKFpTFeFRZrfsG6vDQ">
> 
> Some contributors suggest that we should change the subtitle on both Not Found Page from "Go back to home page" to another one like "Go back to workspace setting page". But I think It fine to keep the old one
> 
> @Expensify/design Could you help to confirm the expected?

@DylanDylann, My solution doesn't focuses on changing the **subtitle** on the page from **"Go back to home page"** to 
**"Go back to workspace setting page"**. Rather my solution focuses more on redirection to `Workspace Settings Page`. 
Wherever you click among the **two not-found pages**:

```
1. Not found page on LHN.
2. Not found page on the main screen.
```

In both the cases you will be redirected to `Workspace Settings Page`. If you need more clarity I can share a detailed video of my solution the thread.

**Comment by DylanDylann** [comment] 2024-02-11 08:49
@godofoutcasts94 Where do you apply this change
```
    onLinkPress = () => Navigation.goBack(ROUTES.SETTINGS_WORKSPACES),

```

**Comment by godofoutcasts94** [comment] 2024-02-11 08:55
> @godofoutcasts94 Where do you apply this change
> 
> ```
>     onLinkPress = () => Navigation.goBack(ROUTES.SETTINGS_WORKSPACES),
> ```

I am planning to apply this change here (that's just an idea maybe I can be right or wrong. Just wanted more clarity if I am wrong as well)  : 

https://github.com/Expensify/App/blob/bfae5b2cb8aa0731dc49745be942cf985cdaf5bc/src/components/BlockingViews/FullPageNotFoundView.tsx#L55

**Comment by jeremy-croff** [comment] 2024-02-11 15:41
Depending on which way the copy goes my proposal still holds, but will have to follow copy guidance. Main focus of my proposal is to use the Navigation stack to go back to the non error screen, so that this screen generically goes back. With a fallback to HOME if there is no stack.

**Comment by MitchExpensify** [comment] 2024-02-13 21:35
Not overdue, progressing

**Comment by DylanDylann** [comment] 2024-02-15 09:29
@Expensify/design Please help to check my comment [here](https://github.com/Expensify/App/issues/36266#issuecomment-1937474130)

**Comment by shawnborton** [comment] 2024-02-15 13:35
First of all, I think we are fixing this view so that only one "Not found" view can show at all times. Is that right?

Second, we could just use something way more generic like "Get me out of here" for the link.

**Comment by shawnborton** [comment] 2024-02-15 13:47
Good question. I feel like if we are able to, it's nice to just navigate back one step to where they were before. Otherwise I guess the Chats page is the true homepage of the app.

**Comment by godofoutcasts94** [comment] 2024-02-15 13:51
> Good question. I feel like if we are able to, it's nice to just navigate back one step to where they were before. Otherwise I guess the Chats page is the true homepage of the app.

So, I think we can redirect back to Workspace Settings page. Right?

**Comment by godofoutcasts94** [comment] 2024-02-15 14:03
> First of all, I think we are fixing this view so that only one "Not found" view can show at all times. Is that right?
> 
> Second, we could just use something way more generic like "Get me out of here" for the link.

<img width="1470" alt="Screenshot 2024-02-15 at 7 32 08 PM" src="https://github.com/Expensify/App/assets/158435970/a4b165f3-5f79-4ef7-9544-47303c3378a1">

CC - @shawnborton is this something that you want but with 1 view right ?

**Comment by shawnborton** [comment] 2024-02-15 14:06
Yup!

**Comment by dannymcclain** [comment] 2024-02-15 14:17
`:my_two_cents:` I think the link could probably just be "Go back" but I don't feel super strongly. Otherwise I totally agree with Shawn and the full screen not found is lookin' good.

**Comment by godofoutcasts94** [comment] 2024-02-15 14:17
> First of all, I think we are fixing this view so that only one "Not found" view can show at all times. Is that right?
> 
> Second, we could just use something way more generic like "Get me out of here" for the link.

Hey @shawnborton can we have a mockup to show what needs to be implemented in step 1 i.e. a complete "Not Found" Page ?

**Comment by shawnborton** [comment] 2024-02-15 14:18
I like the simplicity of just "Go back"

Also cc @trjExpensify - aren't we fixing the double "Not found" pages somewhere else, or is this a different issue?

**Comment by godofoutcasts94** [comment] 2024-02-15 14:22
> I like the simplicity of just "Go back"
> 
> Also cc @trjExpensify - aren't we fixing the double "Not found" pages somewhere else, or is this a different issue?

<img width="1470" alt="Screenshot 2024-02-15 at 7 51 42 PM" src="https://github.com/Expensify/App/assets/158435970/5ac95d9e-58f4-4460-bd47-d9d0a7770ef0">

**Comment by trjExpensify** [comment] 2024-02-15 16:46
>Also cc @trjExpensify - aren't we fixing the double "Not found" pages somewhere else, or is this a different issue?

@shawnborton https://github.com/Expensify/App/issues/34234 @kosmydel is still working on it.

**Comment by trjExpensify** [comment] 2024-02-15 17:22
Yeah, I think this will conflict with @kosmydel's PR in that regard - but maybe he can confirm: https://github.com/Expensify/App/pull/36409

**Comment by godofoutcasts94** [comment] 2024-02-16 06:03
> Yeah, I think this will conflict with @kosmydel's PR in that regard - but maybe he can confirm: #36409

I also think the main focus on this issue should be more on Navigation, rather the "Not Found" page as after going through the comments I can see that those things are taken care of in this : [#36409](https://github.com/Expensify/App/pull/36409). So please suggest @trjExpensify what should we do?

**Comment by DylanDylann** [comment] 2024-02-16 10:11
I agree that we should focus on navigation on this issue. 

Currently, we have **two not-found pages in this case:**
1. Not found page on LHN
2. Not found page on the main screen

https://github.com/Expensify/App/assets/141406735/1a7c35c2-61be-46b5-b028-17df0b1f7c8c

This is my suggestion for the expected of this issue: When the user clicks "Go back to home page" on **one of two not-found pages**, the App will redirect to the Workspace Setting page totally like this 

<img width="1440" alt="Screenshot 2024-02-11 at 15 31 10" src="https://github.com/Expensify/App/assets/141406735/5b429bcd-0bca-4129-9d0c-66d5b711f7bb">

@trjExpensify What do you think about my suggestion?

**Comment by trjExpensify** [comment] 2024-02-16 13:29
Yeah, let's just focus on the goBack bug here and @kosmydel will be fixing the "double" not found error pages.

**Comment by godofoutcasts94** [comment] 2024-02-16 13:47
Hey @trjExpensify and @DylanDylann . please review this [video](https://github.com/Expensify/App/issues/36266#issuecomment-1946195306) and if it is fine then, I will update the proposal.

**Comment by trjExpensify** [comment] 2024-02-16 14:06
That video is using a full page modal, which we've just mentioned is being fixed elsewhere?

**Comment by godofoutcasts94** [comment] 2024-02-16 14:13
> That video is using a full page modal, which we've just mentioned is being fixed elsewhere?

Oops! Sorry! My bad please review this one.

**Comment by trjExpensify** [comment] 2024-02-16 15:01
Cool, I think we're leaning towards just "Go back" for that: 

>I like the simplicity of just "Go back"

**Comment by godofoutcasts94** [comment] 2024-02-16 16:19
Is this the desired result ? @trjExpensify @DylanDylann 

Uploading Screen Recording 2024-02-16 at 9.46.32 PM.mp4…

**Comment by MitchExpensify** [comment] 2024-02-18 23:45
Do you think this is wave 8 worthy given its focus on an admin action on workspaces (which will all be Collect when we deprecate free)?  @zanyrenney

**Comment by DylanDylann** [comment] 2024-02-19 09:37
@codinggeek2023  I think the same behavior also should be applied when user click on the "Go back" in the main screen 

<img width="813" alt="Screenshot 2024-02-19 at 16 35 47" src="https://github.com/Expensify/App/assets/141406735/c6d70b1d-bb9a-4217-9118-be3ea3fae26b">

cc @trjExpensify

**Comment by godofoutcasts94** [comment] 2024-02-19 09:42
> @codinggeek2023 I think the same behavior also should be applied when user click on the "Go back" in the main screen
> 
> <img alt="Screenshot 2024-02-19 at 16 35 47" width="813" src="https://private-user-images.githubusercontent.com/141406735/305901042-c6d70b1d-bb9a-4217-9118-be3ea3fae26b.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDgzMzU3MzUsIm5iZiI6MTcwODMzNTQzNSwicGF0aCI6Ii8xNDE0MDY3MzUvMzA1OTAxMDQyLWM2ZDcwYjFkLWJiOWEtNDIxNy05MTE4LWJlM2VhM2ZhZTI2Yi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMjE5JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDIxOVQwOTM3MTVaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1mY2Y1OTQyODdmYzcyN2Q0MTMwNmYzMTBkYmE1ZWEwM2YwMzM5ZGJiYmU1ZGZiMzQxYWI0YTU4Y2RkMTU5YjIzJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.bUPXFUGJP0hnpGm6qe6e8R1EwNdTFzksByLIVd0VO20">
> cc @trjExpensify

Sorry @DylanDylann that's the above screenshot is not of @codinggeek2023. It is of mine. @godofoutcasts94

**Comment by trjExpensify** [comment] 2024-02-19 11:02
>Do you think this is wave 8 worthy given its focus on an admin action on workspaces (which will all be Collect when we deprecate free)? @zanyrenney

Yeah, this is wave8 -- an issue born from ideal nav.

**Comment by DylanDylann** [comment] 2024-02-19 11:04
@godofoutcasts94 Sorry, It is my mistake. Please update the proposal to cover the case as mentioned [here](https://github.com/Expensify/App/issues/36266#issuecomment-1952052521)

**Comment by godofoutcasts94** [comment] 2024-02-19 11:43
> @godofoutcasts94 Sorry, It is my mistake. Please update the proposal to cover the case as mentioned [here](https://github.com/Expensify/App/issues/36266#issuecomment-1952052521)

Sure! Updated proposal will be ready in sometime for review.

**Comment by kosmydel** [comment] 2024-02-19 12:07
This one will be fixed in [this PR](https://github.com/Expensify/App/pull/36409):


https://github.com/Expensify/App/assets/104823336/523428a2-5148-4811-867a-91dd2f3dd59f

**Comment by godofoutcasts94** [comment] 2024-02-19 12:46
> Here you are:
> 
>  members-button.mov

@trjExpensify and @DylanDylann is this the required behaviour?

**Comment by godofoutcasts94** [comment] 2024-02-19 13:07
Updated [Proposal](https://github.com/Expensify/App/issues/36266#issuecomment-1936491999)

**Comment by trjExpensify** [comment] 2024-02-19 14:55
Yeah, I think @kosmydel has resolved this issue by the looks of things. So @DylanDylann, this can be closed right?

**Comment by trjExpensify** [comment] 2024-02-19 20:35
Cool, sounds good!

**Closed by trjExpensify** 2024-02-19 20:35 UTC
Labels: External, Daily, Help Wanted, Bug
