### ISSUE TITLE
[HOLD for payment 2023-08-10] [HOLD for payment 2023-08-08] Pressing Enter key on Split bill page doesn't navigate to next step

### ISSUE THREAD

**Issue by kavimuru** [Expensify/App#23950] opened 2023-07-31 19:23 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Click on 'FAB' menu
2. Click on 'Split bill' button
3. Enter amount & press 'Enter' key
## Expected Result: 
User should be navigated to the next step
## Actual Result: 
User is not navigated to the next step

## Workaround:
Can the user still use Expensify without this being fixed? Have you informed them of the workaround?

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [x] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 1.3.48-0
**Reproducible in staging?:** y
**Reproducible in production?:** n
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/43996225/05a0531a-66e2-407a-b832-fdc084a64671

https://github.com/Expensify/App/assets/43996225/0ddafca2-2b55-4658-b8f4-f18b2c8e37cf

**Expensify/Expensify Issue URL:**
**Issue reported by:** @natnael-guchima
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1690829632233769

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by getusha** [comment] 2023-07-31 20:36
@marcaaron did some debugging, i think the root cause of this issue is from onyx, the update of the amount is delayed and initially it's 0 so it will navigate us back from `MoneyRequestParticipantsPage` here:

https://github.com/Expensify/App/blob/1fa4b723d8ef649afa56780b52ef453a39bbc9fc/src/pages/iou/steps/MoneyRequstParticipantsPage/MoneyRequestParticipantsPage.js#L77-L79

and there is onyx version upgrade 5 days ago deployed to staging `NoQA] Perf/onyx upgrade use cache directly #23749`

**Comment by Pujan92** [comment] 2023-07-31 20:37
@hannojg This seems to persist after react-native-onyx change https://github.com/Expensify/App/pull/23749 https://github.com/Expensify/react-native-onyx/pull/280 , cache logic(cahcedState) implementation might be the cause for this. With the earlier version `1.0.52` issue is not reproducible.

**Comment by getusha** [comment] 2023-07-31 20:38
@Pujan92 what a coincidence! 😄

**Comment by marcaaron** [comment] 2023-07-31 21:53
>@Pujan92 what a coincidence! 😄

@getusha Is that sarcasm? If so, not sure if I understood you properly or what the "coincidence" you are referring to is. Thanks!

**Comment by getusha** [comment] 2023-07-31 21:56
>@getusha Is that sarcasm? If so, not sure if I understood you properly or what the "coincidence" you are referring to is. Thanks!

@marcaaron  It's just that @Pujan92 and i commented almost the exact same time.

**Comment by hannojg** [comment] 2023-08-01 09:13
I am currently running into an issue where I can't open the split bill page due to this crash. is it just me or everyone?

![Screenshot 2023-08-01 at 11 12 53](https://github.com/Expensify/App/assets/16821682/bc3e0e78-1ecd-4104-812a-47d7642ce8cf)

**Comment by hannojg** [comment] 2023-08-01 09:20
Try creating a new fresh account in a new browser instance. I think the crash is reproducible

**Comment by Beamanator** [comment] 2023-08-01 09:43
Ya that looks like this issue: https://github.com/Expensify/App/issues/23951

**Comment by hannojg** [comment] 2023-08-01 10:19
Okay, however with these changes, there is still the issue that when pressing the Enter-Key, 
1. You will open a second instance of the same page (split bill)
2. On the second press you get to the next page

There was a separate issue for that, not sure if that's also due to the onyx changes will double check!

**Comment by hannojg** [comment] 2023-08-01 10:21
- https://github.com/Expensify/App/issues/23962

**Comment by hannojg** [comment] 2023-08-01 13:46
Fixed also with this PR:

- https://github.com/Expensify/App/pull/23996

**Comment by Beamanator** [comment] 2023-08-01 16:12
Looks like this was fixed by https://github.com/Expensify/App/pull/24003! Not a deploy blocker anymore

**Comment by Natnael-Guchima** [comment] 2023-08-11 18:46
Hello @marcaaron, no reporting bonus is issued here.

**Comment by Natnael-Guchima** [comment] 2023-08-14 10:54
A gentle bump for reporting payment @isabelastisser

**Comment by isabelastisser** [comment] 2023-08-14 16:39
@Natnael-Guchima I sent you an offer in Upwork now. Please accept it and I will process the payment. Thanks!

**Closed by isabelastisser** 2023-08-14 16:39 UTC
Labels: Engineering, Daily, Overdue, Awaiting Payment, Bug

**Comment by Natnael-Guchima** [comment] 2023-08-14 16:43
I have accepted the offer. Thanks @isabelastisser
