### ISSUE TITLE
Web - User receives an error message when adding Manual Bank account

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#11770] opened 2022-10-12 17:58 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:1
1. Access staging.new,expensify.com
2. Sign into a valid account
3. Click Profile > Workspace > Connect a bank account
4. Select Connect Manually and proceed with the setup flow until the end

## Expected Result:
The user expects to be redirected to a validation flow where the modal asks for 3 amounts of test transactions

## Actual Result:
The user can not add the account manually and receives an error message

## Error message:
Oops! An unexpected error occurred while trying to verify your information. Please verify it and try again

## Workaround:
Unknown

## Platform:

Where is this issue occurring?

- Web
- iOS
- Android
- Desktop App
- Mobile Web

**Version Number:** 1.2.13.3

**Reproducible in staging?:** Yes

**Reproducible in production?:** n/a

**Email or phone of affected tester (no customers):** any

**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Notes/Photos/Videos:** Any additional supporting documentation

https://user-images.githubusercontent.com/93399543/195414644-82328b7b-5959-4b2b-89d9-02a1cb3949e2.mp4

**Expensify/Expensify Issue URL:** 

**Issue reported by:** Applause - Internal Team
_
**Slack conversation:** 

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by tgolen** [comment] 2022-10-12 19:51
@kbecciv What was the email for the account which you reproduced that in?

**Comment by tgolen** [comment] 2022-10-12 20:05
I am not able to reproduce this. When I select the terms on that last step, I continue on with the onfido flow like normal:

![image](https://user-images.githubusercontent.com/1228807/195437305-0bc106a9-c403-4737-94a9-a61efc5d392a.png)

**Comment by kbecciv** [comment] 2022-10-12 20:19
@tgolen Here is credentials: emilio.utest+403@gmail.com/Emilio98.
Let me know and we will re-test the issue.

**Comment by tgolen** [comment] 2022-10-12 20:40
I'm seeing a few things in the logs that look like it might begin to show the problem, I don't really know what they mean though:

```
Setup is not complete because externalAPIResponses['requestorIdentityKBA'] is missing
```
thrown from [here](https://github.com/Expensify/Auth/blob/0424844b6d847d569b248adc550330214106bc6b/auth/lib/BankAccount.cpp#L2373)

```
[BankAccountSetup] [mobile] BankAccountAPI - Bank account still in Setup state after ACHContract step??? ~~ bankAccountID: '1727643'
```
thrown from [here](https://github.com/Expensify/Web-Secure/blob/8dfecbffdfa2575b228dfeafb4965776b5ef1ce5/lib/BankAccountAPI.php#L1372)

@nkuoch @ctkochan22 do you have any ideas what could lead to this or if this is indeed a deploy blocker?

**Comment by tgolen** [comment] 2022-10-12 20:42
I also see the same exact error at nearly the same time on two different staging servers:
![image](https://user-images.githubusercontent.com/1228807/195443713-e86cdc2b-9dc7-46e7-a0fe-22cdde4f1be3.png)

**Comment by nkuoch** [comment] 2022-10-12 20:47
This should be fixed once https://github.com/Expensify/Web-Expensify/pull/35108/files reaches prod... right @MariaHCD ? Sorry I'm starting to be ooo til the end of the week

**Comment by tgolen** [comment] 2022-10-12 20:49
OK, thank you! [These logs](https://www.expensify.com/_devportal/tools/logSearch/#sort=asc&size=10000&query=email%3A%22emilio.utest%2B403%40gmail.com%22%20AND%20timestamp%3A%5B2022-10-12T16%3A45%20TO%202022-10-12T16%3A47%5D) also look super strange (just looking at logs in the few requests before the error occurred).

![image](https://user-images.githubusercontent.com/1228807/195444964-38613f71-55fd-4f28-b392-72b9ec13cc38.png)

That seems like an excessive use of Onyx

**Comment by nkuoch** [comment] 2022-10-12 21:01
> That seems like an excessive use of Onyx

I think I know how to improve it. I'll work on it once I'm back. Created [an issue](https://github.com/Expensify/App/issues/11777) so I don't forget.

**Comment by yuwenmemon** [comment] 2022-10-13 04:38
Tested, and verified this was fixed by the PR above. Closing! ✅

**Closed by yuwenmemon** 2022-10-13 04:38 UTC
Labels: DeployBlockerCash, Engineering, Hourly
