### ISSUE TITLE
[HOLD for payment 2024-11-14] [$250] Can't edit the participant amounts on the confirmation page.

### ISSUE THREAD

**Issue by m-natarajan** [Expensify/App#51802] opened 2024-10-31 15:10 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 9.0.56-0
**Reproducible in staging?:** y
**Reproducible in production?:** n
**If this was caught on HybridApp, is this reproducible on New Expensify Standalone?:** Stand alone, Hybrid is not updated yet
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** @rayane-djouah 
**Slack conversation** (hyperlinked to channel name): https://expensify.slack.com/archives/C049HHMV9SM/p1730291235500129

## Action Performed:

1. Start a group
2. Split money (e.g 9000)
3. Enter the value in the BNP
4. Click continue
5. Try to edit the split amount

## Expected Result:
Able to edit the participants amounts
## Actual Result:
Unable to edit
## Workaround:
unknown
## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Standalone
- [ ] Android: HybridApp
- [ ] Android: mWeb Chrome
- [ ] iOS: Standalone
- [ ] iOS: HybridApp
- [ ] iOS: mWeb Safari
- [ ] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

<details>
  <summary>Add any screenshot/video evidence</summary>

https://github.com/user-attachments/assets/20d6bd20-8032-4221-824c-36fb7af95469

  
</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~021852097521924704037</li>
        <li>Upwork Job ID: 1852097521924704037</li>
        <li>Last Price Increase: 2024-10-31</li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @jliexpensify</details>

**Comment by mkzie2** [comment] 2024-10-31 15:45
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
Unable to edit

### What is the root cause of that problem?
It comes from https://github.com/Expensify/App/pull/51202

The amount regex doesn't accept commas character

https://github.com/Expensify/App/blob/72163109c2fbc82d16f444d52b7e2a25f32bed43/src/components/MoneyRequestAmountInput.tsx#L277

https://github.com/Expensify/App/blob/72163109c2fbc82d16f444d52b7e2a25f32bed43/src/libs/MoneyRequestUtils.ts#L43-L47
### What changes do you think we should make in order to solve the problem?
We should update this function with another param, `isAllowCommas,` whose default value is `false`, and introduce a new prop, `isAllowCommas,` with the same default value in `MoneyRequestAmountInput`.

if `isAllowCommas` is true, we should return the regex that allows the commas

```
/**
 * Get amount regex string
 */
function amountRegex(decimals: number, amountMaxLength: number = CONST.IOU.AMOUNT_MAX_LENGTH, isAllowCommans = false): string {
    const amountRegexWithoutDecimals = isAllowCommans ? `(?:\\d{1,3})(?:,\\d{3}){0,${Math.floor((amountMaxLength - 1) / 3)}}$|^\\d{1,${amountMaxLength}}` : `\\d{0,${amountMaxLength}}`;
    return decimals === 0
        ? `^${amountRegexWithoutDecimals}$` // Don't allow decimal point if decimals === 0
        : `^${amountRegexWithoutDecimals}(?:(?:\\.|\\,)\\d{0,${decimals}})?$`; // Allow the decimal point and the desired number of digits after the point
}
```

https://github.com/Expensify/App/blob/72163109c2fbc82d16f444d52b7e2a25f32bed43/src/libs/MoneyRequestUtils.ts#L43-L47


Update this line to pass `isAllowCommans` prop

```
const regex = useMemo(() => MoneyRequestUtils.amountRegex(decimals, undefined, isAllowCommans), [decimals]);
```
https://github.com/Expensify/App/blob/72163109c2fbc82d16f444d52b7e2a25f32bed43/src/components/MoneyRequestAmountInput.tsx#L277

After that we can pass `isAllowCommans={true}` here
https://github.com/Expensify/App/blob/224b633c284fd32e928684010084c587627d5e9a/src/components/MoneyRequestConfirmationList.tsx#L548
### What alternative solutions did you explore? (Optional)

**Comment by chiragsalian** [comment] 2024-10-31 21:17
Nice thanks same root cause as that issue. I also don't feel like its a blocker similar to the other issue since its currently an issue only on android.

**Comment by helmerdavila** [comment] 2024-11-01 05:02
1. Issue is probably caused due some event after you enter the amount
2. When you try to edit it, some side effect might be blocking the validation of the amount being entered, in the component connected to Android.
3. I will look into reproducing the error and be sure that if a validation / side effect is triggered, should be handled properly, allowing to the customer to edit the value.
4. Pending to test: Compare the behavior within iOS devices.

**Comment by helmerdavila** [comment] 2024-11-01 05:05
Contributor details
Your Expensify account email: helmerdev@proton.me
Upwork Profile Link: https://www.upwork.com/freelancers/helmerd2

**Comment by jliexpensify** [comment] 2024-11-01 09:08
Hi @helmerdavila - please review our [Contributing .MD](https://github.com/Expensify/App/blob/main/contributingGuides/CONTRIBUTING.md) and write a proper proposal in the correct format, in order to be reviewed. Thanks!

**Comment by s77rt** [comment] 2024-11-01 11:41
Reverting the PR

**Comment by jliexpensify** [comment] 2024-11-08 02:04
@mollfpr just to confirm: no payments needed here as its a [regression?](https://github.com/Expensify/App/issues/51802#issuecomment-2451741068)

**Comment by mollfpr** [comment] 2024-11-08 02:05
>@mollfpr just to confirm: no payments needed here as its a https://github.com/Expensify/App/issues/51802#issuecomment-2451741068

@jliexpensify Yes!

**Comment by jliexpensify** [comment] 2024-11-08 02:08
Thanks! I assume no checklist needed either?

**Comment by mollfpr** [comment] 2024-11-08 02:09
Yes, it shouldn't need a checklist.

**Comment by jliexpensify** [comment] 2024-11-14 05:29
Great thanks, closing this one!

**Closed by jliexpensify** 2024-11-14 05:29 UTC
Labels: External, Engineering, Weekly, Help Wanted, Awaiting Payment, Bug
