### ISSUE TITLE
[HOLD for payment 2023-07-21] [$1000] [mWeb] room name is out of box

### ISSUE THREAD

**Issue by kavimuru** [Expensify/App#20494] opened 2023-06-09 02:17 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. logout if you are already logged in
2. go to the public room which has long name (like  https://staging.new.expensify.com/r/409586300939335 )
## Expected Result: 
room name should not be out of box
## Actual Result: 
room name out of box

## Workaround:
Can the user still use Expensify without this being fixed? Have you informed them of the workaround?

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [x] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [ ] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 1.3.26-1
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation

<img src="https://github.com/Expensify/App/assets/43996225/8cdd709a-c30f-44b1-96e3-315a2a647b2e" width="40%" height="40%">

<img src="https://github.com/Expensify/App/assets/43996225/471af91c-e33c-4490-8c72-3ccbfd59623a" width="40%" height="40%">

**Expensify/Expensify Issue URL:**
**Issue reported by:** @gadhiyamanan 
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1685971297162419

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01fbf308fce24031bc</li>
        <li>Upwork Job ID: 1667202731087081472</li>
        <li>Last Price Increase: 2023-06-16</li>
    </ul>
</details>

**Comment by shawnborton** [comment] 2023-06-09 16:46
It looks like "Join in on the discussion" is not using the correct brand font. 

And yeah, I agree it looks weird, here is what it should look like: 
![image](https://github.com/Expensify/App/assets/2319350/36d5e502-561f-4bbc-9181-a284fc29d8b3)


The button should float all the way to the right edge.

**Comment by shawnborton** [comment] 2023-06-09 16:46
It also looks like we aren't using the correct background color for the BG of the card, and there should be more space between the room/title/description and bottom logo/etc on the mobile view.

**Comment by shawnborton** [comment] 2023-06-12 06:52
I think for this screenshot here:
<img width="806" alt="image" src="https://github.com/Expensify/App/assets/2319350/fb3ea293-ad93-4a07-9c6a-e8deae7e8716">


We should use a different breakpoint and make that use the "mobile view" where we see this style:
<img width="463" alt="image" src="https://github.com/Expensify/App/assets/2319350/dbd2a17d-2716-445a-ac1f-de98d7fba458">

Also, @allroundexperts @marcochavezf - it looks like that PR linked above completely missed the design review process, what exactly happened there? Can you create an issue for some follow ups please? For example, the colors are not correct and at the mobile view, the logo is not left-aligned:
![image](https://github.com/Expensify/App/assets/2319350/1d876fb7-df0a-467f-ad24-86576db768ed)

**Comment by Christinadobrzyn** [comment] 2023-06-12 17:57
Not overdue, still working on proposals!

**Comment by marcochavezf** [comment] 2023-06-13 17:17
Yeah, I rushed to get the anonymous user implementation done by a deadline and forgot to go through the design process, my apologies. I will create a new follow-up issue to fix the design.

**Comment by marcochavezf** [comment] 2023-06-14 18:28
> what is scope to fix here as there's separate issue created?

Let's focus here on the room name issue. The other issue is for a more general styling fix.

**Comment by Pujan92** [comment] 2023-06-16 17:04
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
room name is out of box and sign in button wrong position

### What is the root cause of that problem?
Seems flex properties are not assigned properly to the elements which is causing the issue.

### What changes do you think we should make in order to solve the problem?
Instead of `row-wrap` we can assign flex direction row/column based on the `isSmallScreenWidth`. Below changes are required.

- Set flex direction based on the screen width and remove flex styles from class `anonymousRoomFooter` https://github.com/Expensify/App/blob/469596a91ad32b9f176ddc35a622cf063a0a2641/src/components/AnonymousReportFooter.js#L28
`<View style={[styles.anonymousRoomFooter, props.isSmallScreenWidth ? styles.flexColumn : styles.flexRow]}>`
https://github.com/Expensify/App/blob/469596a91ad32b9f176ddc35a622cf063a0a2641/src/styles/styles.js#L2224-L2231

- Add `styles.flex1` to first view which will grow/shrink based on the available width
https://github.com/Expensify/App/blob/469596a91ad32b9f176ddc35a622cf063a0a2641/src/components/AnonymousReportFooter.js#L29
`<View style={[styles.flexRow, styles.flex1]}>`

- Set `styles.justifyContentBetween` to the second view to allow signin button to be most right when screen is small
https://github.com/Expensify/App/blob/469596a91ad32b9f176ddc35a622cf063a0a2641/src/components/AnonymousReportFooter.js#L36
`<View style={[styles.flexRow, styles.alignItemsCenter, styles.justifyContentBetween]}>`

### Result

https://github.com/Expensify/App/assets/14358475/db8f6512-1aed-41d9-b603-52c17c221000

**Comment by Christinadobrzyn** [comment] 2023-07-03 22:07
Still on hold for https://github.com/Expensify/App/pull/20884

**Comment by srikarparsi** [comment] 2023-07-10 17:31
Thanks @0xmiroslav! Assigning you to the issue @hungvu193

**Comment by Christinadobrzyn** [comment] 2023-07-14 19:40
I'm going to be ooo until August 31st so going to unassign and assign a new teammate. 

At this time, we're reviewing the PR and pending payment

@0xmiroslav do we need a regression test for this?

**Comment by bfitzexpensify** [comment] 2023-07-17 09:20
Sure @Christinadobrzyn, can do

**Comment by bfitzexpensify** [comment] 2023-07-19 08:25
Payment due on Friday - @eVoloshchak, reminder to complete the BZ checklist when you can

**Comment by Christinadobrzyn** [comment] 2023-08-28 21:35
hey @0xmiroslav just checking in, is this good to pay?

**Comment by Christinadobrzyn** [comment] 2023-09-29 21:35
Moving back to monthly, feel free to keep us in the loop @0xmiroslav!

**Comment by Christinadobrzyn** [comment] 2023-10-31 20:44
hey @0xmiroslav just checking on this! I think you said you're tracking these payments so can I close this?

**Closed** 2023-10-31 22:22 UTC
Labels: External, Monthly, Awaiting Payment, Bug
