### ISSUE TITLE
[$500] Chat - Text partially cut for last text on paste of long text

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#28847] opened 2023-10-04 17:47 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Open the app
2. Open any report
3. Type in multiline text which just triggers scroll and copy it or copy similar length text from any other source
4. Paste it in composer and observe that last line text is displayed partially cut

## Expected Result:
App should scroll to bottom to ensure that pasted text is displayed fully

## Actual Result:
App should scroll to bottom to ensure that pasted text is displayed fully

## Workaround:
Unknown 

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [x] MacOS / Chrome / Safari
- [x] MacOS / Desktop

**Version Number:** 1.3.77.5
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/93399543/b521839d-a5e2-44f1-bcd4-8dbef8105f6b

https://github.com/Expensify/App/assets/93399543/ffc88f15-9843-498e-98df-60d11795b427

https://github.com/Expensify/App/assets/93399543/c1597894-497a-4a5d-bf78-9faac8d2b1cf

https://github.com/Expensify/App/assets/93399543/707debe4-9dff-4ae1-a0c1-f8a3f1c4d5a6

**Expensify/Expensify Issue URL:**
**Issue reported by:** @dhanashree-sawant
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1696347080023239

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01f1d1d117c4970023</li>
        <li>Upwork Job ID: 1709626352655679488</li>
        <li>Last Price Increase: 2023-10-11</li>
    </ul>
</details>

**Comment by saiKumarGanji** [comment] 2023-10-04 18:33
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
On paste of long text which triggers scroll, the text is getting partially cut, instead of displaying until the bottom

### What is the root cause of that problem?
The textarea element on paste is not scrolling entirely down, which results in partial text cut

### What changes do you think we should make in order to solve the problem?
When we copy into textarea, we can catch the copy event and set the textarea scroll to the bottom using js dom methods

### What alternative solutions did you explore? (Optional)
NA

**Comment by nebiyuelias1** [comment] 2023-10-04 19:29
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
When pasting a very long text, the composer is not scrolled all the way to the bottom. It's scrolled partially. But it seems this happens only for edge cases. If the text is substantially long it's scrolled fully.
### What is the root cause of that problem?
It seems the Composer was refactored into a FC with [this](https://github.com/Expensify/App/pull/23359) PR. Inside the [updateNumberOfLines](https://github.com/Expensify/App/blob/96c6c51155b97036975d891d629b7818bd976663/src/components/Composer/index.js#L350) function. It seems the author used a workaround of setting height to 0 first and then to auto, and it seems it's having a jumping effect. But it doesn't guarantee it will be scrolled all the way.
### What changes do you think we should make in order to solve the problem?
To ensure it's scrolled all the way to the bottom we can include something like the following inside the [updateNumberOfLines](https://github.com/Expensify/App/blob/96c6c51155b97036975d891d629b7818bd976663/src/components/Composer/index.js#L350) function to make sure it will always be scrolled all the way to the bottom:
`textInput.current.scrollTop = textInput.current.scrollHeight;`


### What alternative solutions did you explore? (Optional)

**Comment by nebiyuelias1** [comment] 2023-10-10 07:02
> I don't think it's correct. Your proposal could lead to a regression bug where a user is typing somewhere in the middle of the composer, and tries to copy and paste something then it would scroll to the end of the composer instead of staying focused in the end of pasting text.

But after doing some tests on the staging environment, it seems that's what is happening even with the current implementation. So I don't think it will be a regression. But what other problem could my proposal create? It's a very strange issue because when the text you're pasting is greater than **numberOfLines + 2**, it's being scrolled without no problem.

**Comment by nebiyuelias1** [comment] 2023-10-11 16:55
> @nebiyuelias1 take a look at my recording before and after applying your proposal. The composer jumps every time I paste a text
> 
> https://github.com/Expensify/App/assets/9639873/8899c7a3-c9d8-4de1-9bfd-af982af3f1f3
> 
> 

Ok thank you for showing me the problem. Well what if I actually do the manual scrolling only when pasting text? Do you think that will solve the problem?

**Comment by nebiyuelias1** [comment] 2023-10-11 18:53
> btw @lschurr can you reproduce this bug? I couldn't, it works normally from my end
> 
>  Screen.Recording.2023-10-11.at.23.51.19.mov

That's probably because you've added a multiline text with more than 17 rows. This bug happens only when you have 17 lines of text. The default behavior of HTML textarea is consistent with the partial problem we have. I just couldn't figure out where we're actually manually scrolling.

**Comment by nebiyuelias1** [comment] 2023-10-11 19:49
@hoangzinh you can look [this pr](https://github.com/Expensify/App/issues/8663) from the past. Basically, they tried changing the focus of the element and as a result, the browser automatically scrolls the content. But the browser's behavior is not always consistent it seems. It will have a partial scroll on text content that is not very large. So I don't see any other way to fix this issue other than manually scrolling it ourselves. But making sure our scrolling code only happens for pasting events. The pr basically removed the change I was suggesting because it had unintended side effects like the one you described.

**Comment by nebiyuelias1** [comment] 2023-10-14 04:02
@hoangzinh The text is not partially cut anymore. It's just that the scrollbar is not scrolled all the way to the bottom. When this issue was first created the problem was that the text was being partially cut but I'm no longer observing that behavior. So I feel like we might have wasted time on this issue. You can probably close it.

**Comment by lschurr** [comment] 2023-10-16 15:51
Going to close!

**Closed by lschurr** 2023-10-16 15:51 UTC
Labels: External, Daily, Help Wanted, Overdue, Bug
