### ISSUE TITLE
[HOLD] [$1000] LHN - After deleting message, the conversation displays in LHN top instead of bottom

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#23999] opened 2023-08-01 14:15 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Launch app
2. Tap on new chat
3. Enter email address of user with whom you are going have new conversation first time
4. Enter and send a message
5. Delete the message
6. Navigate back to LHN to see the conversation in bottom
7. Go to device settings
8. Delete app cache
9. Launch the app

## Expected Result:
After deleting message from new conversation, the user conversation must display in LHN bottom

## Actual Result:
After deleting message from new conversation, the user conversation displays in LHN top instead of bottom after deleting cache and launching the app

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [ ] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 1.3.48.0

**Reproducible in staging?:** Yes

**Reproducible in production?:** Yes

**If this was caught during regression testing, add the test name, ID and link from TestRail:**

**Email or phone of affected tester (no customers):**

**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/78819774/0acf0434-c153-4ddd-80f8-f0e3d3b8ca77

**Expensify/Expensify Issue URL:**

**Issue reported by:** Applause - Internal Team

**Slack conversation:**

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~012052a7b390ee262d</li>
        <li>Upwork Job ID: 1686859556902330368</li>
        <li>Last Price Increase: 2023-08-09</li>
    </ul>
</details>

**Comment by adelekennedy** [comment] 2023-08-02 21:48
I can reproduce but I'm not sure this is a bug - even if you deleted the message I'd think it would remain at the top of the conversations because it was the last activity. I'm going to test it in IOS and see what that behavior is

**Comment by zanyrenney** [comment] 2023-08-07 17:30
hey @sobitneupane what are your thoughts on this proposal please?

**Comment by sobitneupane** [comment] 2023-08-09 03:30
Sorry for the delay. Going to review it today.

**Comment by sobitneupane** [comment] 2023-08-09 12:59
Thanks for the [proposal](https://github.com/Expensify/App/issues/23999#issuecomment-1663161816) @tienifr 

> >After deleting message from new conversation, the user conversation must display in LHN bottom
>
> The OP expected result seems to be incorrect.
>
>The correct expectation should be: After deleting message from the newest created conversation, the user conversation should still display at the top since it's the latest report created (It initially displays at the top as well when you first created it).

I kind of agree with your reasoning (report with latest action, i.e. report creation action). But looking at the code and based on what backend returns(lastVisibleActionCreated empty), it looks like it was an intended behavior to not show the report at the top.

@tienifr Those reports are again show at the top after clearing the cache. What's the reason?

**Comment by zanyrenney** [comment] 2023-08-14 11:22
bump @sobitneupane on next steps please?

**Comment by MonilBhavsar** [comment] 2023-08-17 13:26
Reviewing this proposal

**Comment by zanyrenney** [comment] 2023-08-21 11:17
Any update on the review @MonilBhavsar ?

**Comment by MonilBhavsar** [comment] 2023-08-22 09:57
I think this will be fixed by backend only. I have got the draft PR up and it does seem to fix it https://github.com/Expensify/Auth/pull/8526

**Comment by MonilBhavsar** [comment] 2023-08-24 14:51
It flickers a bit, so I think you're right. We'll need a client side change


Uploading Screen Recording 2023-08-24 at 8.20.28 PM.mov…

**Comment by MonilBhavsar** [comment] 2023-08-29 08:42
Will switch back. Yet to figure out failing cases in draft PR

**Comment by zanyrenney** [comment] 2023-08-31 11:06
@tienifr i have assigned you to the issue.

**Comment by sobitneupane** [comment] 2023-08-31 16:54
@tienifr 
Let's wait for the update from @MonilBhavsar before proceeding further.

**Comment by zanyrenney** [comment] 2024-09-11 09:17
Hey @MonilBhavsar Please can you ensure you update this issue with what you're working on that is deemed higher priority than this. It's okay to punt issues if you are working on more important work but it's really important that you communicate that here so we can understand and make adjustments if needed.

**Comment by MonilBhavsar** [comment] 2024-09-12 06:35
Sorry for missing this out. This is not a priority at the moment and we can close this

**Closed by MonilBhavsar** 2024-09-12 06:35 UTC
Labels: Reviewing, Engineering, Monthly, Internal, Not a priority, Bug

**Comment by zanyrenney** [comment] 2024-10-02 09:15
Payment summary

After discussions in Slack, we have agreed to pay out 50% of this due to the work done on the PR.

$500 due to @tienifr please request from ND as I see you are registered with newdot payments.

**Comment by zanyrenney** [comment] 2025-01-10 09:24
oh sure! thanks for letting me know
