### ISSUE TITLE
[HOLD for payment 2023-07-21] [$2000] Web - Quick actions menu is below the welcome message when user invited to a room

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#19836] opened 2023-05-30 17:53 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
Pre-req: open the latest version of Safari browser on iOS mac. Then make the browser full screen mode.
1. From Account A, make a room (public)
2. Set the Welcome message that has a word wrapped in backticks, as the following:
```
Hello
```
3. Copy the link to the room
4. Copy the link to safari and join from account B.
5. Post a message
6. Hover on the message

## Expected Result:
The quick actions menu should be displayed on top of the upper welcome message

## Actual Result:
The quick actions menu is cut off due to the welcome message on safari

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [x] MacOS / Safari
- [ ] MacOS / Desktop

**Version Number:** 1.3.20.1

**Reproducible in staging?:** yes

**Reproducible in production?:** yes

**If this was caught during regression testing, add the test name, ID and link from TestRail:**

**Email or phone of affected tester (no customers):**

**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/93399543/ce0228de-c743-414d-a45f-b446efb4badc

**Expensify/Expensify Issue URL:**

**Issue reported by:** @esh-g 

**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1685176705589209

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01c2648eb123a606dc</li>
        <li>Upwork Job ID: 1664832387031658496</li>
        <li>Last Price Increase: 2023-06-26</li>
    </ul>
</details>

**Comment by sethraj14** [comment] 2023-05-30 22:42
@michaelhaxhiu  @esh-g Unable to reproduce this issue, but found another issue while debugging this issue. 

Welcome message shows empty spaces and does not trim the message.

![Screenshot 2023-05-31 at 4 09 58 AM](https://github.com/Expensify/App/assets/14844259/aedf7d6f-9e1a-45cd-a954-f67795fd18d6)

This can be fixed using this proposal - 

## Proposal

### Please re-state the problem that we are trying to solve in this issue.

Empty space in the welcome message.

### What is the root cause of that problem?

There is not trimming of welcome message.

### What changes do you think we should make in order to solve the problem?

We should trim the Welcome message before saving in this function - 
```javascript
    const submitForm = useCallback(() => {
        Report.updateWelcomeMessage(props.report.reportID, props.report.welcomeMessage, welcomeMessage.trim());
    }, [props.report.reportID, props.report.welcomeMessage, welcomeMessage]);

``` 

This will trim the welcome message and will not show empty messages.

### What alternative solutions did you explore? (Optional)

**Comment by esh-g** [comment] 2023-06-01 17:21
@sethraj14 Are you on Safari?

**Comment by sethraj14** [comment] 2023-06-01 20:18
@esh-g Yes tried on safari as well.

**Comment by michaelhaxhiu** [comment] 2023-06-02 21:57
Hmm this is an issue with backticks it seems 🤔. @esh-g did you manage to reproduce without backticks or only when those are used?

**Comment by esh-g** [comment] 2023-06-03 02:49
@michaelhaxhiu I was able to repro with backticks only..

**Comment by HaiderKeshwani** [comment] 2023-06-03 06:24
Hi,
I think this could be an issue due to z-index. Maybe increasing the z-index of the quick actions of the below message can solve it, or even decreasing the Welcome message z-index can also work.

**Comment by HaiderKeshwani** [comment] 2023-06-03 06:34
Contributor details
Your Expensify account email: haider619.hk@gmail.com
Upwork Profile Link: https://www.upwork.com/freelancers/~017c967b928c091725

**Comment by sethraj14** [comment] 2023-06-03 10:54
Finally able to reproduce the issue, it is only happening in a safari full-screen mode. Very specific and also happens intermittently, if you hover back and forth a few times over the welcome message and new message, the issue sometimes disappears. 

FYI @mananjadhav @esh-g @michaelhaxhiu

**Comment by michaelhaxhiu** [comment] 2023-06-05 15:58
Yep I think I was full screen when I reproduced (a lucky accident lol) and didn't notice it was a pre-requisite. Thanks for testing @sethraj14. I updated the GH body to include this detail.

This bug is still valid and worth fixing, in case you want to make a proposal.

**Comment by michaelhaxhiu** [comment] 2023-06-08 21:50
@mananjadhav mentioned he was unwell in slack and OOO. Let's give it 1-2 more days here for him to chime in. 

Otherwise I can re-assign the label to get another C+ to take his place. Thanks for patience!

**Comment by michaelhaxhiu** [comment] 2023-06-08 21:50
Note: if we don't like any existing proposals, remind me to double the price

**Comment by mananjadhav** [comment] 2023-06-09 01:16
Okay I thought we are waiting for more proposals after the reproduction steps changed. I’ll review them today.

**Comment by mananjadhav** [comment] 2023-06-09 17:36
@michaelhaxhiu I don't see any valid proposals so far. I think we should double this. Sorry for the delay. Been playing catchup all day.

**Comment by mananjadhav** [comment] 2023-06-14 20:10
@michaelhaxhiu quick bump on doubling this.

Still open for proposals.

**Comment by deetergp** [comment] 2023-06-14 23:17
@michaelhaxhiu I think @mananjadhav is right, let's double the price.

**Comment by michaelhaxhiu** [comment] 2023-06-19 18:46
doubled price. I will try to reproduce later today or tomorrow just to be sure this is still a bug

**Comment by developerdavi** [comment] 2023-06-19 19:59
working as expected here

![image](https://github.com/Expensify/App/assets/31714350/745b227e-3858-4c7e-80f4-892cc98e6c66)

**Comment by mananjadhav** [comment] 2023-06-20 20:52
I am unable to reproduce this on staging. @michaelhaxhiu Are you able to reproduce this? I've tried on Safari 16.4 Full Screen mode.

**Comment by ShogunFire** [comment] 2023-06-26 00:41
I can also reproduce and without full screen @mananjadhav , I put the video here if that can help:

https://github.com/Expensify/App/assets/19537677/048fa693-d502-43fe-aef9-4ab5e3eda189

Also when I open the dev tool the problem disapear so I think it has to do with the height of the page, maybe zoomig out like @ginsuma said will help

**Comment by deetergp** [comment] 2023-06-26 22:46
I am also not able to reproduce it on staging.

**Comment by deetergp** [comment] 2023-06-26 23:17
I take that back, I was able to reproduce it on Staging, but it is specific to the Safari browser. I couldn't reproduce it in Chrome.

**Comment by koko57** [comment] 2023-06-28 08:15
Hi! I’m Agata from Callstack, an expert agency, and I would like to help close this issue out. I've checked @ginsuma proposal and it's working here, but I'm not really convinced with the root cause, I think it's correct in some way but does it really explain this strange behavior? I also experienced the problem disappearing/reappearing when I opened dev tools or changed the window height.



https://github.com/Expensify/App/assets/28020445/cb7aa324-c458-431d-a8a3-93f196ea5f8b



I also wonder why it happens for the third message here but it doesn't for the second one
![Screenshot 2023-06-28 at 09 14 59](https://github.com/Expensify/App/assets/28020445/2bab85a0-7cda-4bcb-94e9-cb6fdd2090f7)

**Comment by koko57** [comment] 2023-06-28 10:22
thanks for the explaination @ginsuma! I asked, because the first message (without the backticks) is also wrapped in a view with r-transform class. So I guess it's rather something with the backticks message?

![Screenshot 2023-06-28 at 12 20 36](https://github.com/Expensify/App/assets/28020445/f926603f-599d-4c28-b224-e66bd7461b5a)

**Comment by michaelhaxhiu** [comment] 2023-07-03 22:48
How is this coming along?

**Comment by koko57** [comment] 2023-07-04 07:10
I think that @ginsuma proposal is good and now the root cause is clear to me. What do you think?

**Comment by mananjadhav** [comment] 2023-07-04 20:45
While I couldn't reproduce this on my side, but the codepen and the explanation was helpful. Thanks for being persistent on this one @ginsuma. I agree we can assign their proposal.

🎀 👀 🎀  C+ Reviewed.

**Comment by flodnv** [comment] 2023-07-05 11:09
I'm confused why I got assigned, but I reviewed everything and it looks good, thanks!

**Comment by flodnv** [comment] 2023-07-05 11:13
Melvin, go home, you're drunk.

---

📣 @ginsuma You have been assigned to this job!
Please apply to the [Upwork job](https://www.upwork.com/jobs/~01c2648eb123a606dc) and leave a comment on the Github issue letting us know when we can expect a PR to be ready for review 🧑‍💻
Once you apply to this job, your Upwork ID will be stored and you will be automatically hired for future jobs!
Keep in mind: [Code of Conduct](https://github.com/Expensify/App/blob/main/CODE_OF_CONDUCT.md) | [Contributing](https://github.com/Expensify/App/blob/main/contributingGuides/CONTRIBUTING.md) 📖

**Comment by michaelhaxhiu** [comment] 2023-07-12 20:52
😂

**Comment by mananjadhav** [comment] 2023-07-20 14:35
Because this is a very platform specific change, and with a specific scenario (full-screen), I don't think we can link it to any offending PR. 

Neither I am sure if we should be adding `Full Screen Safari`,  to the checklist? . Lastly, I think we don't need a regression test for this scenario? Open to feedback here.  @michaelhaxhiu @deetergp wdyt?

**Comment by michaelhaxhiu** [comment] 2023-07-21 19:26
Pay day on a friday 😸! Summary:

- [ ] @esh-g External issue reporter $250
- [ ] Contributor that fixed the issue $2000
- [X] @mananjadhav Contributor+ that helped on the issue and/or PR - paid via newDot $2000

**Comment by michaelhaxhiu** [comment] 2023-07-21 19:30
New upwork job link (last one expired) - https://www.upwork.com/jobs/~010aae0f1247cf26f2

**Comment by michaelhaxhiu** [comment] 2023-07-21 19:32
@ginsuma & @esh-g can you please apply for this job? I can't find your upwork profiles

**Comment by mananjadhav** [comment] 2023-07-21 19:34
I accidentally only raised for 1500. Adding another request of 500.

**Comment by esh-g** [comment] 2023-07-22 01:46
@michaelhaxhiu Applied on upwork! This is my profile: https://www.upwork.com/freelancers/tanyag4

**Comment by anmurali** [comment] 2023-07-23 07:03
Approved $1500 + $500 for this job

**Comment by michaelhaxhiu** [comment] 2023-07-24 12:49
Just waiting for @esh-g to accept my offer and then I can pay/close this.

**Comment by esh-g** [comment] 2023-07-24 13:09
@michaelhaxhiu Thanks! I accepted the offer

**Closed** 2023-07-24 13:14 UTC
Labels: Engineering, Daily, Internal, Awaiting Payment, Bug
