### ISSUE TITLE
[HOLD for payment 2024-12-17]  Profile - Invalid second contact method is added and displayed as ready to verify.

### ISSUE THREAD

**Issue by IuliiaHerets** [Expensify/App#53819] opened 2024-12-10 09:26 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 9.0.73-0
**Reproducible in staging?:** Yes
**Reproducible in production?:** No
**If this was caught on HybridApp, is this reproducible on New Expensify Standalone?:** Yes, reproducible on both
**If this was caught during regression testing, add the test name, ID and link from TestRail:** https://expensify.testrail.io/index.php?/tests/view/5320066&group_by=cases:section_id&group_order=asc&group_id=229064
**Email or phone of affected tester (no customers):** ibellicotest+86@gmail.com
**Issue reported by:** Applause Internal Team

## Action Performed:
1. Open the Expensify app.
2. Tap on "Settings" and select "Profile"
3. Open the "Contact Method" tab.
4. Tap on "New Contact Method"
5. Complete with an Email with an existing account.
6. Wait for the magic code to be received and type it.
7. Verify that an error message is displayed, showing that the account can´t be added as contact method.
8. Close the error message and tap on the arrow on the top left corner.
9. Verify that the account wasn´t added as second contact method.

## Expected Result:
Invalid Email or Email with existing account, shouldn´t be added as secondary contact method after the error message is closed.

## Actual Result:
After the user receives and closes an error message, showing that an account can´t be added as contact method, the account is added anyway and is displayed as ready to verify. The user receives a magic code to verify the account, but all the codes received are rejected.

## Workaround:
Unknown

## Platforms:
- [x] Android: Standalone
- [x] Android: HybridApp
- [x] Android: mWeb Chrome
- [ ] iOS: Standalone
- [ ] iOS: HybridApp
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

https://github.com/user-attachments/assets/07acfb78-0018-4ca2-9b48-89c913a2da06

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Issue Owner</summary>Current Issue Owner: @sakluger</details>

**Comment by MonilBhavsar** [comment] 2024-12-10 10:30
Commented on the suspicious PR https://github.com/Expensify/App/pull/53462

**Comment by Shahidullah-Muffakir** [comment] 2024-12-10 12:46
Issue still produceable after reverting the PR.

https://github.com/user-attachments/assets/22087e2e-e154-4317-a8ad-d4a3e58ca1f1

**Comment by MonilBhavsar** [comment] 2024-12-10 13:11
Strange, I cannot reproduce it now on staging

**Comment by MonilBhavsar** [comment] 2024-12-10 13:12
@thesahindia could you mention your steps? anything different?

**Comment by MonilBhavsar** [comment] 2024-12-10 13:50
I am checking the same :)
I am not able to reproduced this consistently, not sure why 🤔

**Comment by MonilBhavsar** [comment] 2024-12-10 14:02
Thank you for checking!

**Comment by mkzie2** [comment] 2024-12-10 14:50
@MonilBhavsar I can create a fix now.

**Comment by MonilBhavsar** [comment] 2024-12-10 15:04
Appreciate it, thank you! @brunovjk are you available to review it?

**Comment by brunovjk** [comment] 2024-12-10 15:05
yes

**Comment by brunovjk** [comment] 2024-12-10 15:07
Thanks @thesahindia and @MonilBhavsar for dealing with it. @mkzie2 I've been investigating and haven't found a solution yet, if you do please raise a PR, I'll test it now :D

**Comment by mkzie2** [comment] 2024-12-10 15:09
@MonilBhavsar Created a draft [here](https://github.com/Expensify/App/pull/53864). Can you please assign @brunovjk here before I open this PR to prevent assigning a random C+?

**Comment by MonilBhavsar** [comment] 2024-12-10 15:14
Assigned

**Comment by mkzie2** [comment] 2024-12-10 15:18
@brunovjk The PR is ready.

> prevent assigning a random C+?

@MonilBhavsar We should assign C+ to the issue to prevent that. 😅

**Comment by luacmartins** [comment] 2024-12-10 19:00
Fixed in staging. Removing blocker lable

**Comment by MonilBhavsar** [comment] 2024-12-11 05:17
We can close this. This was handled as a regression. Thank you all for taking care of this 🙌

**Closed by MonilBhavsar** 2024-12-11 05:17 UTC
Labels: Engineering, Weekly, Awaiting Payment, Bug
