### ISSUE TITLE
[$250] Send invoice - Changing the room name in workspace invoice sends the report to skeleton view

### ISSUE THREAD

**Issue by m-natarajan** [Expensify/App#41270] opened 2024-04-30 00:51 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.68-0
**Reproducible in staging?:** Yes
**Reproducible in production?:** No (New feature)
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** Applause internal team
**Slack conversation:**

## Action Performed:
1. Go to staging.new.expensify.com
2. Go to FAB > Send invoice.
3. Enter amount and select a participant.
4. Create the invoice.
5. Click on the workspace chat header.
6. Go to Settings > Room name.
7. Edit the room name and save it.
## Expected Result:
App will not turn to skeleton.

## Actual Result:
Changing the room name in workspace invoice sends the report to skeleton view.
## Workaround:
Unknown
## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [X] Android: mWeb Chrome
- [ ] iOS: Native
- [X] iOS: mWeb Safari
- [X] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

https://github.com/Expensify/App/assets/38435837/9923f60a-f57b-4398-8675-87c7a1b92332

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01079d9f6791e60b87</li>
        <li>Upwork Job ID: 1785202638406352896</li>
        <li>Last Price Increase: 2024-04-30</li>
    </ul>
</details>

**Comment by m-natarajan** [comment] 2024-04-30 00:52
We think this bug might be related to #wave-collect - Release 1

**Comment by m-natarajan** [comment] 2024-04-30 00:53
@muttmuure FYI I haven't added the External label as I wasn't 100% sure about this issue. Please take a look and add the label if you agree it's a bug and can be handled by external contributors.

**Comment by robertjchen** [comment] 2024-04-30 07:00
Though not ideal, it does not appear to be a serious deploy blocker and can be addressable by external contributors 👍

**Comment by bernhardoj** [comment] 2024-04-30 14:13
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
Changing room name in an invoice report makes the report turns to skeleton loader view.

### What is the root cause of that problem?
First of all, we are not supposed to be able to rename the invoice report. When we rename it, a new RENAMED (You renamed this room from ...) action is optimistically added. When the API request is completed, it breaks the [getContinuousReportActionChain](https://github.com/Expensify/App/blob/main/src/libs/ReportActionsUtils.ts#L307) logic. `getContinuousReportActionChain` will build the chain of report actions based on `previousReportActionID`. If the current action `previousReportActionID` doesn't match the previous action ID, then the chain stops there.

In our case, the RENAMED action doesn't have `previousReportActionID`, so the chain only includes the RENAMED action. This only happens after the API request is completed because `getContinuousReportActionChain` will always include a pending action item and start the check from the non-pending action item.

This doesn't happen when we rename a chat room because the API request will give us the `previousReportActionID` for the RENAMED action.

### What changes do you think we should make in order to solve the problem?

Hide/disable the room name field when it's an invoice chat.
https://github.com/Expensify/App/blob/b62bbbb36c295760293be81487e7bde842374d28/src/pages/settings/Report/ReportSettingsPage.tsx#L34-L38

```
!ReportUtils.isInvoiceRoom(report)
```

**Comment by cristipaval** [comment] 2024-04-30 14:53
This is #vip-billpay

**Comment by danielrvidal** [comment] 2024-04-30 19:37
Yup, marking this as Critical as you should not be able to edit the room name. @ishpaul777 can you please prirotize this one to be reviewed and then picked up asap. It's needed for our release.

**Comment by cristipaval** [comment] 2024-04-30 20:47
Closing in favor of [this one](https://github.com/Expensify/App/issues/41280) where we hide the fields that we do not want in the Settings page

**Closed by cristipaval** 2024-04-30 20:47 UTC
Labels: External, Engineering, Daily, Help Wanted, Bug
