### ISSUE TITLE
 Link message is flagged automatically

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#21158] opened 2023-06-20 20:43 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Open any chat
2. Send message containing any link (i.e. google.com)

## Expected Result:
Message is not flagged

## Actual Result:
Message is flagged

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android / native
- [x] Android / Chrome
- [x] iOS / native
- [x] iOS / Safari
- [x] MacOS / Chrome / Safari
- [x] MacOS / Desktop

**Version Number:** v1.3.27-6

**Reproducible in staging?:** n/a

**Reproducible in production?:** n/a

**If this was caught during regression testing, add the test name, ID and link from TestRail:**

**Email or phone of affected tester (no customers):**

**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Notes/Photos/Videos:** Any additional supporting documentation

![Screenshot 2023-06-14 at 4 01 22 PM](https://github.com/Expensify/App/assets/93399543/2716fc59-515f-4b63-a19f-551947cf079c)

**Expensify/Expensify Issue URL:**

**Issue reported by:** @0xmiroslav

**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1686751233326789

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01d03d5e3bc2c73d61</li>
        <li>Upwork Job ID: 1671929806780641280</li>
        <li>Last Price Increase: 2023-06-22</li>
    </ul>
</details>

**Comment by kbecciv** [comment] 2023-06-20 20:44
internal PR: https://github.com/Expensify/Web-Expensify/pull/37833

**Comment by avi-shek-jha** [comment] 2023-06-21 05:16
@MitchExpensify @kbecciv I reported the same issue on June 02 and it was closed saying it's not a bug and it wasn't reproducible. https://github.com/Expensify/App/issues/20054

**Comment by MitchExpensify** [comment] 2023-06-22 00:18
Thanks @avi-shek-jha, closing for the same reason

**Comment by thienlnam** [comment] 2023-06-22 17:14
Ah, we actually ended up fixing this internally from this bug report - so this is valid for a reporting payment! cc @MitchExpensify

**Comment by thienlnam** [comment] 2023-06-22 17:15
Adding the internal label so you can hire them to that job when you get back from OOO

**Comment by MitchExpensify** [comment] 2023-06-23 09:26
Thanks @thienlnam! Paid > Closing

**Closed by MitchExpensify** 2023-06-23 09:26 UTC
Labels: Daily, Internal, Bug
