### ISSUE TITLE
[Waiting for payment] [$500] IOU description is removed when a number is entered without letters 

### ISSUE THREAD

**Issue by kavimuru** [Expensify/App#26665] opened 2023-09-04 13:37 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Request money.
2. Open IOU and Click on description.
3. Set 123456789 to the description.
## Expected Result: 
The value 123456789 should be set to the description.
## Actual Result: 
The value 123456789 is not set to the description.

## Workaround:
Can the user still use Expensify without this being fixed? Have you informed them of the workaround?

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [x] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 1.3.62-4
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/43996225/d8f1c331-b7c5-4d60-8df5-4637d688c080

https://github.com/Expensify/App/assets/43996225/adc85bb8-38d6-45fa-92b1-b156fb0a5d1d

**Expensify/Expensify Issue URL:**
**Issue reported by:** @tewodrosGirmaA from https://github.com/Expensify/App/issues/26005#issuecomment-1780725854
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1692977518330889

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01e31d67a403139803</li>
        <li>Upwork Job ID: 1701524140104798208</li>
        <li>Last Price Increase: 2023-09-12</li>
    </ul>
</details>

**Comment by BhuvaneshPatil** [comment] 2023-09-04 13:49
## Proposal

### Please re-state the problem that we are trying to solve in this issue.

### What is the root cause of that problem?
this happens because we set success data like this here - 
https://github.com/Expensify/App/blob/f8858d33d5d62f9d55eac4bd3ae0f0d875cf0004/src/libs/actions/Task.js#L439-L451

here description is being treated as falsy value (in case of zero), and we setting that as null

### What changes do you think we should make in order to solve the problem?
We shall use `reportDescription` that we have created above in same method (`editTaskAndNavigate`) to set the value.

I am checking that's the case for title as well

### What alternative solutions did you explore? (Optional)

**Comment by sonialiap** [comment] 2023-09-12 09:09
Reproducible, affects all numbers

<img width="593" alt="image" src="https://github.com/Expensify/App/assets/17131195/aa2d2ef5-7827-40c2-b2cd-2fc942204315">

Stops dropping the description after the description is edited to contain a letter and is saved

But, if you 
1. edit and replace description with a letter, save
2. edit the description and replace letter with a number
3. observe that the number is dropped and the report comment says that the description was removed

<img width="1179" alt="image" src="https://github.com/Expensify/App/assets/17131195/05e8b03f-b5b2-4419-90b3-629d3818d6f2">

Following edits with numbers in description behave as expected

<img width="1190" alt="image" src="https://github.com/Expensify/App/assets/17131195/1bd56719-574b-4487-aa2f-8ed62ccc27c4">

https://github.com/Expensify/App/assets/17131195/cfb88d00-a206-4954-bb14-6a5124f3067d

**Comment by sonialiap** [comment] 2023-09-18 09:15
@situchan what do you think of the above proposal?

**Comment by situchan** [comment] 2023-09-18 09:51
I agree this is BE issue.
🎀 👀 🎀 to assign engineer

**Comment by Julesssss** [comment] 2023-09-19 01:30
I'm not sure we should care if this is just happening to comments of `0` to be honest.

**Comment by Julesssss** [comment] 2023-09-19 01:30
I'd say we should close this.

**Comment by paultsimura** [comment] 2023-09-19 05:31
@Julesssss is I'm not mistaken, this happens if we enter any number of any length (without letters) in the description. 

https://github.com/Expensify/App/issues/26665#issuecomment-1715322610

**Comment by Julesssss** [comment] 2023-09-19 07:06
Ah my bad, I didn't read @sonialiap's full report. Updated the reproduction steps. 

I'm dropping the priority.

**Comment by Julesssss** [comment] 2023-09-26 01:30
> What needs to happen to get a PR in review this week?

This is impossible. I cannot unassign and nobody has spare time. it will have to wait until the wave projects are under control.

**Comment by mvtglobally** [comment] 2023-09-28 03:18
Issue not reproducible during KI retests. (First week)

**Comment by Julesssss** [comment] 2023-10-23 11:14
This is important rto fix, but it's going to have to wait for a while. We're all really busy atm.

**Comment by tewodrosGirmaA** [comment] 2023-10-26 09:20
Hello guys, this issue is a duplicate of one that I previously reported on GitHub at https://github.com/Expensify/App/issues/26005. I believe that @mountiny is currently working on it. I reported this issue on August 26th.

**Comment by mountiny** [comment] 2023-10-28 13:19
Updated the reporter

**Comment by rlinoz** [comment] 2023-11-20 13:33
This is fixed already, I think it is pending payment?

I don't know why the automation wasn't triggered.

cc:  @sonialiap

**Comment by tewodrosGirmaA** [comment] 2023-12-28 14:12
Hello @rlinoz @sonialiap I have yet to receive payment

**Comment by tewodrosGirmaA** [comment] 2024-01-17 16:38
@mountiny @Julesssss  I have not received payment as of yet

**Comment by Julesssss** [comment] 2024-01-17 16:46
Ah sorry, our automation seemed to fail here.

**Comment by Julesssss** [comment] 2024-01-17 16:47
@sonialiap could you please pay out @tewodrosGirmaA when you have a moment, please?

**Comment by sonialiap** [comment] 2024-02-26 13:04
Apologies @tewodrosGirmaA, this was on monthly and I didn't see it

Original issue was created [Aug 26](https://github.com/Expensify/App/issues/26005). It was confirmed [here](https://github.com/Expensify/App/issues/26005#issuecomment-1781107714) as the original report which means tewodrosGirmaA needs to be compensated as the reporter. 

Report bonus value change was announced on [Aug 30](https://expensify.slack.com/archives/C01GTK53T8Q/p1693424078129649). The original issue was opened on Aug 26 which means this report qualifies for the old bonus amount of $250.

**Payment summary:**
- @tewodrosGirmaA reporting issue $250 - offer sent

**Comment by tewodrosGirmaA** [comment] 2024-02-26 13:05
@sonialiap I accept it , Thank you

**Comment by sonialiap** [comment] 2024-02-26 13:15
Paid ✔️

**Closed by sonialiap** 2024-02-26 13:15 UTC
Labels: Reviewing, Engineering, Daily, Internal, Not a priority, Bug
