### ISSUE TITLE
[HOLD for payment 2024-01-02] [HOLD for payment 2023-12-28] [$500] Implement Left Hand Nav

### ISSUE THREAD

**Issue by hayata-suenaga** [Expensify/App#32939] opened 2023-12-12 18:02 UTC
As part of the Ideal Nav overhaul, implement the new Left Hand Panel and Left Hand Navigator according to the requirements specified in [the design doc](https://docs.google.com/document/d/1VnEf2ThbbiQj0kx9KnAihF0DWf50s2Bn_MztEyEwtjg/edit).

Parent Issue: https://github.com/Expensify/App/issues/32689

<details><summary>Issue Owner</summary>Current Issue Owner: @WojtekBoman</details>
<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~015fa44a44c1c98c39</li>
        <li>Upwork Job ID: 1737583619451142144</li>
        <li>Last Price Increase: 2023-12-20</li>
    </ul>
</details>

**Comment by hayata-suenaga** [comment] 2023-12-12 18:15
@WojtekBoman from Software Mansion is going to work on this issue 🎉

**Comment by WojtekBoman** [comment] 2023-12-13 08:25
Comment for the assignment

**Comment by adamgrzybowski** [comment] 2023-12-20 18:02
@hayata-suenaga This was merged and can be closed.

**Comment by hayata-suenaga** [comment] 2023-12-20 19:23
assinged @s77rt as the C+ for this issue for the payment for PR review

**Comment by alexpensify** [comment] 2023-12-20 21:06
@hayata-suenaga was there an agreement set for the price or is this a standard payment of $500? Thanks!

**Comment by alexpensify** [comment] 2023-12-20 21:11
Flagging the 7-day hold period will end on Thursday, December 28, 2023 and I can proceed forward with the payment process. I will be OOO next week but will try to get everything ready to avoid more delays.

**Comment by hayata-suenaga** [comment] 2023-12-20 21:13
yes the standard C+ review amount should be applied to this issue 🙇

**Comment by alexpensify** [comment] 2023-12-20 21:25
@s77rt - to prepare for the payment process, please apply for the job here:

https://www.upwork.com/jobs/~015fa44a44c1c98c39

I'm OOO starting on Friday and want to make sure that this one is ready for payment next week. Thanks!

**Comment by s77rt** [comment] 2023-12-21 11:51
@alexpensify Applied! Thanks!

**Comment by alexpensify** [comment] 2023-12-23 03:08
Here is the payment summary: 

-  External issue reporter - N/A 
-  Contributor that fixed the issue - N/A 
-  Contributor+ that helped on the issue and/or PR - @s77rt 

Upwork Job: https://www.upwork.com/jobs/~015fa44a44c1c98c39

Extra Notes regarding payment: Heads up, I'm OOO until January 4, but I will log in on Friday, December 29 to complete this payment process pending no regression. I've confirmed that @s77rt is a pending hire, so all set here for the payment date.

**Comment by s77rt** [comment] 2023-12-26 11:45
I don't think we require a regression test here since the expected behavior is unlikely to unexpectedly change

**Comment by alexpensify** [comment] 2023-12-29 18:22
Closing - Thank you everyone for your patience here. I've completed the payment process in Upwork and closed this job. 

Happy New Year!

**Closed by alexpensify** 2023-12-29 18:22 UTC
Labels: External, Daily, NewFeature, Awaiting Payment
