### ISSUE TITLE
:pencil2: in Left Hand Nav (LHN) for draft messages is being removed and draft isn't showing after signing out/in.

### ISSUE THREAD

**Issue by mvtglobally** [Expensify/App#11099] opened 2022-09-19 05:53 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Create a couple draft chats
2. Sign out then sign in again

## Expected Result:
Previous drafts to show at top of LHN with :pencil2: 

## Actual Result:
Drafts and :pencil2: aren't showing. (and.. the previously pinned chats don't show at top)

## Workaround:
unknown 

## Platform:

Where is this issue occurring?

- Web
- iOS
- Android
- Desktop App
- Mobile Web

**Version Number:** 1.2.1-0
**Reproducible in staging?:** Y 
**Reproducible in production?:** Y 
**Email or phone of affected tester (no customers):** 
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation 

https://user-images.githubusercontent.com/43995119/190956791-7dea3fa1-3d45-4f34-a900-2eacb5c2148d.mp4

**Expensify/Expensify Issue URL:** 
**Issue reported by:** @mallenexpensify 
**Slack conversation:** https://expensify.slack.com/archives/C01GTK53T8Q/p1662679736719709

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by mallenexpensify** [comment] 2022-09-19 15:20
@mvtglobally were you able to reproduce this?  I'm gonna hold off assigning engineering/Carlos til we know it's reproducible since the 'unread' update from Marc last week might have fixed it

**Comment by mallenexpensify** [comment] 2022-09-23 21:54
@mvtglobally can you see if you're able to reproduce, thanks

**Comment by mvtglobally** [comment] 2022-09-26 05:55
@mallenexpensify Consistently repro 

https://user-images.githubusercontent.com/43995119/192203256-95ccacb5-3bef-4c32-9cfd-4f6791a4923f.mp4

**Comment by mallenexpensify** [comment] 2022-09-26 22:52
Thanks @mvtglobally , @cead22 sending back to you for engineering triage since you were initially assigned

**Comment by cead22** [comment] 2022-09-28 21:50
Are you sure the intended design is to be able to see the drafts after you sign out? I think clearing those drafts when signing out makes sense, because otherwise that means keeping this info in local storage, when imo that shouldn't be available after signing out because if somebody else uses the device and checks local storage they can access these drafts

**Comment by mallenexpensify** [comment] 2022-09-29 17:51
Yes, I think it should be the intended design to be able to see drafts, even after signing out.  ie. imagine if you signed out, or got signed out, of gmail and all your draft emails were gone.

**Comment by cead22** [comment] 2022-09-29 18:26
Ok, that would be new feature, cause we'd need to store the drafts in the database instead of just in local storage. I agree for email that feature is super valuable. I'm not convinced it is for chat

**Comment by mallenexpensify** [comment] 2022-09-30 00:56
@cead22 , guessing this needs to be internal, right?

**Comment by cead22** [comment] 2022-09-30 16:36
If we go with the back end database storing these, yes. If we store them in local storage, no. But I think we should do the former

**Comment by MitchExpensify** [comment] 2022-10-19 21:57
I can reproduce this. Following [these instructions](https://expensify.slack.com/archives/C01GTK53T8Q/p1666110686295819?thread_ts=1666110643.035949&cid=C01GTK53T8Q) I'm labelling Engineering

**Comment by puneetlath** [comment] 2022-10-21 17:41
I agree that this is a new feature, not a bug. Storing drafts in the db so they can be cross-device (and persist across sessions) isn't the current intended behavior. I'm going to close this as this doesn't seem like an important feature right now and we have plenty of bugs to focus on. Feel free to reopen if you disagree.

**Closed by puneetlath** 2022-10-21 17:41 UTC
Labels: Engineering, NewFeature
