### ISSUE TITLE
Expense - Logo in Share code for transaction thread is not Expensify logo

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#45827] opened 2024-07-20 13:44 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 9.0.10-2
**Reproducible in staging?:** Y
**Reproducible in production?:** N
**If this was caught during regression testing, add the test name, ID and link from TestRail:** N/A
**Issue reported by:** Applause - Internal Team

**Issue found when executing PR** https://github.com/Expensify/App/pull/39072
## Action Performed:
1. Go to staging.new.expensify.com
2. Go to DM with no unsettled expense
3. Submit an expense
4. Click on the expense preview
5. Click report header > Share
6. Note that the logo in share code is Expensify logo
7. Create another expense
8. Go to transaction thread
9. Click report header > Share

## Expected Result:
Logo in Share code for transaction thread is Expensify logo

## Actual Result:
Logo in Share code for transaction thread is not Expensify logo, It follows the individual policy avatar

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [x] Android: mWeb Chrome
- [x] iOS: Native
- [x] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details> 

https://github.com/user-attachments/assets/22ce232b-d900-4216-9df1-ca6571aae025

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by mountiny** [comment] 2024-07-21 20:27
@Kicu @grgia @blazejkustra @luacmartins @sobitneupane Seems like this might be coming from your PR https://github.com/Expensify/App/pull/39072 can you have a look please?

Ultimately I think this could be demoted as its a minor UI issue that does not block the user

**Comment by Kicu** [comment] 2024-07-22 07:12
Hey thanks for calling us. Yes this is definitely coming from my PR https://github.com/Expensify/App/pull/39072

However you can take a look at this comment from @shawnborton https://github.com/Expensify/App/pull/39072#issuecomment-2236052607

Who suggested we move forward with switching the current expectation of using expensify logo to using the same logo as in header.
Now the app is not yet 100% ready to do this (we need 1 more PR) but there are parts of the app that will already show the avatar, so I think this should be deemed a not bug.
Please comment on this @shawnborton

**Comment by shawnborton** [comment] 2024-07-22 07:46
Correct, this is not a bug - we want to move towards a world where the avatar found in the share code always matches either the user's avatar, the workspace avatar, or the avatar found in the chat header. I can close this out, this is not a deploy blocker.

**Comment by shawnborton** [comment] 2024-07-22 07:46
@Kicu what are next steps to make this work everywhere though? Do we have that spelled out anywhere, and do we need a new issue to track this? Happy to make one if so, just let me know!

**Closed by shawnborton** 2024-07-22 07:46 UTC
Labels: DeployBlockerCash, Engineering, Hourly

**Comment by Kicu** [comment] 2024-07-22 07:49
I believe the main thing I need is a new issue defined be someone so that I can get assigned to it.
I don't think I need any detailed definition other than "make the avatar inside QR code the same as in header".

The issue would also be a place to discuss any edge cases that might arise while doing that (I'm not yet sure simple this task will be, probably simple-to-mid-complex).

**Comment by shawnborton** [comment] 2024-07-22 07:57
Sounds good, I'll make the new issue now.
