### ISSUE TITLE
[$500] Receipt - Background options are not selectable on replace popup

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#28090] opened 2023-09-24 15:56 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Open the app
2. Open any distance/ receipt request money page
3. Click on image
4. Click on 3 dots to open replace popup
5. Observe that now 3 dots, close button in background are not selectable

## Expected Result:
 App should keep background options selectable behind replace popup as we have kept for all the popup throughout the app

## Actual Result:
Background options are not selectable on replace popup

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [x] MacOS / Chrome / Safari
- [x] MacOS / Desktop

**Version Number:** 1.3.73.0
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/93399543/d80cbd14-6d51-45ce-a39f-78fa589d9a8a

https://github.com/Expensify/App/assets/93399543/d3390aa4-0226-4b97-8519-381ba8252fad

**Expensify/Expensify Issue URL:**
**Issue reported by:** @dhanashree-sawant
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1695377989579209

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01be00e6a7b15320bb</li>
        <li>Upwork Job ID: 1705974598901944320</li>
        <li>Last Price Increase: 2023-09-24</li>
    </ul>
</details>

**Comment by miljakljajic** [comment] 2023-09-25 02:44
this is a dupe of #28088 and was created afterwards. Closing.

**Closed by miljakljajic** 2023-09-25 02:44 UTC
Labels: External, Daily, Help Wanted, Bug

**Comment by dhanashree-sawant** [comment] 2023-10-16 13:33
Hi @NicMendonca, @miljakljajic, @abdulrahuman5196 the marked issue is on staging and live but the following issue is still reproducible, can we open this again?
