### ISSUE TITLE
[HOLD for payment 2024-08-01] [$250] [QBO Export] "Export" button is present in paid expense thread details and does not show export options

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#45609] opened 2024-07-17 13:48 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 9.0.8-1
**Reproducible in staging?:** Y
**Reproducible in production?:** N
**If this was caught during regression testing, add the test name, ID and link from TestRail:** N/A
**Issue reported by:** Applause - Internal Team

**Issue found when executing PR** https://github.com/Expensify/App/pull/44170
## Action Performed:
Precondition:
- Workspace is connected to QBO
1. Go to staging.new.expensify.com
2. Go to workspace chat
3. Submit two expenses
4. Go to expense report
5. Click Pay elsewhere
6. Click on the report header
7. Click Export
8. Note that it shows export options
9. Go to transaction thread of any paid expenses
10. Click on the report header
11. Click Export

## Expected Result:
In step 11, "Export" option should not be present in individual expense report

## Actual Result:
In step 11, "Export" option is present in individual expense report, and it does not show Export options even though the expenses are paid (inconsistent with behavior in Step 8)

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [x] Android: mWeb Chrome
- [x] iOS: Native
- [x] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details> 

https://github.com/user-attachments/assets/86016d1b-bc96-4ec2-b59c-d084268e000d

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~018ed70d69a1b863ab</li>
        <li>Upwork Job ID: 1813938049866208668</li>
        <li>Last Price Increase: 2024-07-18</li>
<li>Automatic offers: </li>
<ul>
<li>rojiphil | Reviewer | 103171595</li>
</ul></li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @johncschuster</details>

**Comment by lanitochka17** [comment] 2024-07-17 13:49
We think that this bug might be related to #wave-collect - Release 1

**Comment by trjExpensify** [comment] 2024-07-17 15:18
The description of this issue is a little confusing. An "individual expense report" (A.k.a "one expense report") would have the export option in Details. An individual expense on an expense report should not.

**Comment by arosiclair** [comment] 2024-07-17 18:34
> The description of this issue is a little confusing. An "individual expense report" (A.k.a "one expense report") would have the export option in Details. An individual expense on an expense report should not.

Yeah that makes sense to me too. I removed the blocker since this is a brand new feature and not a critical issue.

**Comment by arosiclair** [comment] 2024-07-17 18:34
@kosmydel you have bandwidth to clean this up? We just need to hide the Export option for transaction threads.

**Comment by kosmydel** [comment] 2024-07-18 13:21
> @kosmydel you have bandwidth to clean this up? We just need to hide the Export option for transaction threads.

I've prepared [a draft of PR.](https://github.com/Expensify/App/pull/45678) I should be able to complete the checklist and videos tomorrow.

**Comment by johncschuster** [comment] 2024-08-01 14:08
@rojiphil can you please complete the BZ Checklist when you have a moment?

**Comment by rojiphil** [comment] 2024-08-01 14:12
@johncschuster I did not review this. 
@hungvu193 reviewed the PR.

**Comment by hungvu193** [comment] 2024-08-01 14:17
Yes I reviewed the PR, we can close it

**Comment by hungvu193** [comment] 2024-08-01 14:18
No payment needed btw

**Comment by hungvu193** [comment] 2024-08-01 14:19
I assume that this one will be treated as a regression right? @trjExpensify

**Closed** 2024-08-02 14:04 UTC
Labels: External, Daily, Awaiting Payment, Bug
