### ISSUE TITLE
Android - Track Expenses - Infinite loading on Reports when tracked distance expense is present

### ISSUE THREAD

**Issue by IuliiaHerets** [Expensify/App#54154] opened 2024-12-14 12:06 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 9.0.76-0
**Reproducible in staging?:** Yes
**Reproducible in production?:** Yes
**If this was caught on HybridApp, is this reproducible on New Expensify Standalone?:** Yes
**If this was caught during regression testing, add the test name, ID and link from TestRail:** https://github.com/Expensify/App/pull/54073
**Email or phone of affected tester (no customers):** N/A
**Issue reported by:** Applause Internal Team
**Device used:** Samsung S23FE/ Android 14
**App Component:** Search

## Action Performed:
Prerequisites:
User logged in with a new Gmail account.

Steps:
1. Go to selfDM
2. Create a tracked distance request
3. Open the Reports page

## Expected Result:
The tracked distance expense is displayed on the Reports page after a few seconds and its details page is properly populated without error messages.

## Actual Result:
Infinite loading on the Reports page when a tracked distance expense is present. Sometimes the track expense is displayed after a long while and when tapping it, the details page is empty with an error message.

## Workaround:
Unknown

## Platforms:
- [x] Android: Standalone
- [x] Android: HybridApp
- [ ] Android: mWeb Chrome
- [ ] iOS: Standalone
- [ ] iOS: HybridApp
- [ ] iOS: mWeb Safari
- [ ] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

https://github.com/user-attachments/assets/d710cb78-9cd0-4276-a87b-faec964bf31f

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by CyberAndrii** [comment] 2024-12-16 20:25
This issue has the same root cause as https://github.com/Expensify/App/issues/45086. Will be fixed by [my proposal](https://github.com/Expensify/App/issues/45086#issuecomment-2546639916) if it gets accepted

**Comment by slafortune** [comment] 2024-12-19 19:54
going to close this as a duplicate

**Closed by slafortune** 2024-12-19 19:54 UTC
Labels: Daily, Overdue, Bug
