### ISSUE TITLE
[HOLD for payment 2023-07-21] [$1000] Web -  Heading after quote is not rendering

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#21846] opened 2023-06-28 21:44 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Go a chat and add a comment
```
> quote
# heading
```
2. Notice that heading is displayed in plain text

## Expected Result:
Heading should be rendered

## Actual Result:
Markdown heading syntax is not rendering

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [x] iOS / Safari
- [x] MacOS / Chrome / Safari
- [x] MacOS / Desktop

**Version Number:** 1.3.32-5
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/93399543/8626f832-2e3e-4705-9f42-59b82d7d7172
https://github.com/Expensify/App/assets/93399543/7f95a2a1-6c96-4a48-afbe-712edae38043

**Expensify/Expensify Issue URL:**
**Issue reported by:** @eh2077
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1687921581684809

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01e498007bd2f0de5b</li>
        <li>Upwork Job ID: 1674345101139329024</li>
        <li>Last Price Increase: 2023-07-06</li>
    </ul>
</details>

**Comment by code0406** [comment] 2023-06-29 01:33
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
heading in the new line in "quote" section is not formatted. 

### What is the root cause of that problem?
The root cause is in this function. 
ReportUtils.getParsedComment / ExpensiMark.replace()

The replace function applies rules to convert the text as HTML.(convert markdown characters to HTML tags)
![replace1](https://github.com/Expensify/App/assets/108268728/fff8783d-94b1-4620-884b-b7dd25aa5078)

There are several rules.(not all markdown, ex: There is no heading2, heading3 rules, etc)
![rules](https://github.com/Expensify/App/assets/108268728/66833915-a5f8-42e3-9a3f-8788bd8687bf)

Reason1: 
<blockquote> is applied to only the first line.
image1 is the sample text, image2 is the replaced text. so the heading text in the 2nd line is outside of the blockquote.

![1](https://github.com/Expensify/App/assets/108268728/6e6637f6-75c4-4df0-aed5-30fe3716a56c)
![2](https://github.com/Expensify/App/assets/108268728/2b0be007-184d-4e4f-9cda-93dd7690fb10)

Reason2: 
heading1 rule does not work by lines(regarding the new line tags)
It means:  Even if we fix the reason1, it will have an issue still like the example.
When sending this text **"> # heading1\n# heading again"**, it should be replaced like 
**"<blockquote><h1>heading1</h1><br/><h1>heading again</h1></blockquote>"**
but the result is: 
![line](https://github.com/Expensify/App/assets/108268728/149d14cb-5c30-40d7-9c5c-32535e4396fe)


### What changes do you think we should make in order to solve the problem?
So the solution has 2 steps:

Step1( for reason1) - 
if the blockquote ">" should be applied on the multiline text, then we should apply the "new line" rule before applying the <blockquote> rule. So <blockquote> should wrap the full text, not the first line. 

Step2(for reason2) - heading1 rule should consider a new line tag.

### What alternative solutions did you explore? (Optional)
N/A

**Comment by conorpendergrast** [comment] 2023-06-29 09:11
I reproduced on OSX desktop and  too. Given that this is markdown, we can probably assume it's affecting all platforms.

**Comment by conorpendergrast** [comment] 2023-06-29 09:16
I see [this previous discussion](https://github.com/Expensify/App/issues/18211), but it doesn't look entirely similar as that was for whitespace on a single line (and this is multi-line, where only one is a block quote)

**Comment by code0406** [comment] 2023-06-29 09:38
Please check my proposal kindly. 
https://github.com/Expensify/App/issues/21846#issuecomment-1612307209
Thank you.

**Comment by s77rt** [comment] 2023-06-29 18:23
@spcheema Thanks for the proposal. Your RCA is about right. The new line seems to be lost in `modifyTextForQuote` but not in `formatTextForQuote`, not a blocker though. However I think the solution can be improved. Can't we just move the `heading1` rule to be before `quote`? This will make the input that we pass to `modifyTextForQuote` already have the heading tag handled and avoid the problem.

**Comment by s77rt** [comment] 2023-06-29 18:25
@code0406 Thanks for the proposal. I don't think your RCA is correct:
> `<blockquote>` is applied to only the first line.

This is expected, the blockquote will only be applied to lines that start with `>`, for new lines if they don't start with `>` then the block quote tag won't be applied.

**Comment by code0406** [comment] 2023-06-29 21:15
> @code0406 Thanks for the proposal. I don't think your RCA is correct:
> 
> > `<blockquote>` is applied to only the first line.
> 
> This is expected, the blockquote will only be applied to lines that start with `>`, for new lines if they don't start with `>` then the block quote tag won't be applied.

okay. if that is the requirement, I can skip the new line tag problem. 
let me update my comment. 

I have a question to clarify. Even though the second line is not blockquote, should the heading1 style be formatted?
Looking forward to hearing from you. 
Thank you.

**Comment by s77rt** [comment] 2023-06-30 00:10
@code0406 
> Even though the second line is not blockquote, should the heading1 style be formatted?


Yes, we should always format such styles, this has nothing to do whether the text is inside a quote or not. Please update your proposal and tag me again.

**Comment by s77rt** [comment] 2023-06-30 00:12
@spcheema Oops we just inverted the bug :sweat_smile:. I don't think we should go with option 1 for now, it's better to find a solution that does not involve making one rule aware of the other, let's make that our last resort solution. Please update your proposal and tag me again.

**Comment by code0406** [comment] 2023-06-30 01:27
## Proposal
[Updated]https://github.com/Expensify/App/issues/21846#issuecomment-1612307209

@s77rt

**Comment by code0406** [comment] 2023-06-30 01:28
> @code0406
> 
> > Even though the second line is not blockquote, should the heading1 style be formatted?
> 
> Yes, we should always format such styles, this has nothing to do whether the text is inside a quote or not. Please update your proposal and tag me again.

Perfect. all clear now. 
I updated my comment. and tagged you. 
Thank you.

**Comment by s77rt** [comment] 2023-06-30 05:45
@code0406 Thanks for the update but your RCA is still incorrect.

**Comment by code0406** [comment] 2023-06-30 05:56
> @code0406 Thanks for the update but your RCA is still incorrect.

sorry about it, I think. I submitted the best solution including the video where the issue was fixed.

**Comment by s77rt** [comment] 2023-06-30 06:24
@spcheema Thanks for the update. The suggested solution also makes one rule aware of the other. Maybe we have better chances fixing the edge case after changing the order of rules.

**Comment by s77rt** [comment] 2023-06-30 06:26
@code0406 I'm referring to the root cause of the problem, it was not updated. Besides the solution of changing the order of rules is not complete as we have some edge cases where parsing does not work as intended as highlighted by @spcheema here https://github.com/Expensify/App/issues/21846#issuecomment-1613895345.

**Comment by s77rt** [comment] 2023-06-30 07:32
@spcheema I understand the solution, just looking for more alternatives. I see that the `heading1` rule also captures the newline `\n`. Maybe we can remove that and adjust what needs to be adjusted accordingly e.g. `# hi\n` should still be parsed as `<h1>hi<\h1>` and not `<h1>h1<\h1><br />`

**Comment by code0406** [comment] 2023-06-30 07:40
> @code0406 I'm referring to the root cause of the problem, it was not updated. Besides the solution of changing the order of rules is not complete as we have some edge cases where parsing does not work as intended as highlighted by @spcheema here [#21846 (comment)](https://github.com/Expensify/App/issues/21846#issuecomment-1613895345).

![image](https://github.com/Expensify/App/assets/108268728/92a743e5-4b36-43b5-816d-df4915905ef5)
as you can see here. I explained the reason(root cause) here. 

If you didn't check it. then I can update it. add the text in the first line.

**Comment by s77rt** [comment] 2023-06-30 08:12
@code0406 I don't see how that's correct, the new line is not replaced with `</blockquote>`. The new line char is just lost in `modifyTextForQuote` where `textToCheck` is split on newlines (and we don't add it back building `replacedText`).

**Comment by s77rt** [comment] 2023-06-30 08:19
@spcheema The heading rule captures the new line, that's why `# hi\n` is parsed as `<h1>hi</h1>`. That's intended but cause a problem in case we want to go with the switch order of rules approach.

What I meant to say is that there may be this approach to explore
1. Change order of rules, `heading1` before `quote`
2. Make the heading rule not capture the newline i.e. change regex to: `/^# +(?! )((?:(?!<pre>|\n|\r\n).)+)/gm` (this will fix the mentioned edge cases)
3. But now we have a regression  `# hi\n` is parsed as `<h1>hi</h1><br />` which is an unwanted behaviour

**Comment by code0406** [comment] 2023-06-30 08:26
> @code0406 I don't see how that's correct, the new line is not replaced with `</blockquote>`. The new line char is just lost in `modifyTextForQuote` where `textToCheck` is split on newlines (and we don't add it back building `replacedText`).

ah, I understand what was missed. 
Let me explain why it's the root cause. 
![image](https://github.com/Expensify/App/assets/108268728/246f1d9c-56cf-4292-85a8-188439901cd3)

The reportComment where the new line tag "\n" was changed is from "ReportUtils.buildOptimisticAddCommentReportAction()" function.
![image](https://github.com/Expensify/App/assets/108268728/3998d30d-3792-4e16-9d96-befb69897de5)

and it is from ExpensiMark().replace() function like this:
![image](https://github.com/Expensify/App/assets/108268728/135aacf3-4230-46e1-bdd0-09ddada8c22a)

this function applies the rules. 
![image](https://github.com/Expensify/App/assets/108268728/6a32ed96-fab0-4a2d-b796-fdc7e7aedc52)

the order of rules is like this: 
![image](https://github.com/Expensify/App/assets/108268728/aca94c04-f6ad-485c-b643-ee8797f08005)
'quote' and 'heading1', and it is applied by the order in the for loop. 

so the new line tag "\n" was replaced with "</blockquote>".
This is the root cause. So I shared the fixed video. It proves my root cause is right. 

I hope this is clear to understand. 
Looking forward to hearing from you. 
Thank you.

**Comment by s77rt** [comment] 2023-06-30 13:59
@code0406 Thanks for the update. I still don't think that's the correct root cause. Even if the proposed solution is okay, this does not necessary mean that the root cause is correct. But again the solution does not work well with cases like: `> a\n# da\n> test`

**Expected:**
`<blockquote>a</blockquote><h1>da</h1><blockquote>test</blockquote>`

**Got:**
`<blockquote>a</blockquote><h1>da</h1>&gt; test`

**Comment by s77rt** [comment] 2023-06-30 14:03
@spcheema That was just an approach that I suggested to explore hoping for it to be an inspiration for better solutions. I think  we are still looking for better solutions here.

**Comment by code0406** [comment] 2023-06-30 14:04
> @code0406 Thanks for the update. I still don't think that's the correct root cause. Even if the proposed solution is okay, this does not necessary mean that the root cause is correct. But again the solution does not work well with cases like: `> a\n# da\n> test`
> 
> **Expected:** `<blockquote>a</blockquote><h1>da</h1><blockquote>test</blockquote>`
> 
> **Got:** `<blockquote>a</blockquote><h1>da</h1>&gt; test`

So I suggested an alternative solution. Of course, we should update the regex in the rules. but I think the root cause based on the current code is right.

**Comment by s77rt** [comment] 2023-06-30 14:25
@code0406 I think the alternative solution is suggested by @spcheema already. For now we are looking for better solutions

**Comment by code0406** [comment] 2023-06-30 14:26
> @code0406 I think the alternative solution is suggested by @spcheema already. For now we are looking for better solutions

okay. I will share the better solution soon.

**Comment by s77rt** [comment] 2023-06-30 19:42
@spcheema 
> I believe checking next tag is heading a better approach

I'm sorry, can you please clarify which approach is that exactly?

**Comment by s77rt** [comment] 2023-06-30 22:31
@spcheema This results in extra `<br />`, testing with `> a\n# da\n> test`

**Expected:**
`<blockquote>a</blockquote><h1>da</h1><blockquote>test</blockquote>`

**Got:**
`<blockquote>a</blockquote><br /><h1>da</h1><blockquote>test</blockquote>`

**Comment by code0406** [comment] 2023-06-30 23:13
> > @code0406 Thanks for the update. I still don't think that's the correct root cause. Even if the proposed solution is okay, this does not necessary mean that the root cause is correct. But again the solution does not work well with cases like: `> a\n# da\n> test`
> > **Expected:** `<blockquote>a</blockquote><h1>da</h1><blockquote>test</blockquote>`
> > **Got:** `<blockquote>a</blockquote><h1>da</h1>&gt; test`
> 
> So I suggested an alternative solution. Of course, we should update the regex in the rules. but I think the root cause based on the current code is right.

I found a good solution in my direction. 
Let me share the detail. Meanwhile, please check the fixed screen in the following video.
Thank you.

https://drive.google.com/file/d/1W0G2M_mPHwImeS5lNQUXv9mQjNNxNsFT/view?usp=sharing

**Comment by code0406** [comment] 2023-06-30 23:33
> > @code0406 Thanks for the update. I still don't think that's the correct root cause. Even if the proposed solution is okay, this does not necessary mean that the root cause is correct. But again the solution does not work well with cases like: `> a\n# da\n> test`
> > **Expected:** `<blockquote>a</blockquote><h1>da</h1><blockquote>test</blockquote>`
> > **Got:** `<blockquote>a</blockquote><h1>da</h1>&gt; test`
> 
> So I suggested an alternative solution. Of course, we should update the regex in the rules. but I think the root cause based on the current code is right.

Please check my solution again. I explained it more detail. 
https://github.com/Expensify/App/issues/21846#issuecomment-1612307209

Thank you.

**Comment by s77rt** [comment] 2023-07-01 11:08
@code0406 Thanks for the update. I think that solution is more complicated than it should be.

**Comment by s77rt** [comment] 2023-07-01 18:25
@spcheema Thanks for the update. I think if we want to add new rules to take care of the extra `<br />` then the switch order solution is cleaner since it does not make one rule aware of the other.

1. Move `heading1` rule to be before `quote`
2. Modify `heading1` rule to not capture the newline: `/^# +(?! )((?:(?!<pre>|\n|\r\n).)+)/gm`
3. Add `replaceh1br` and `replacebrh1` rules (pretty similar to `replacepre` and `replacebr`)

___

I have also being checking with altering the heading regex approach. It's a one line change solution that works but I think it's better to avoid that approach for now. Also I'm not sure how well the lookbehind assertion is supported

```js
/(?<=<\/blockquote>|^)# +(?! )((?:(?!<pre>|\n|\r\n).)+)\n?/gm
```

**Comment by code0406** [comment] 2023-07-01 23:40
> @code0406 Thanks for the update. I think that solution is more complicated than it should be.

just need to change the rule order, and update 2 lines.
1. change rule order (heading1->qoute)
2. do not remove the "\n" tag in the heading1 rule. 
3. do not add the "\n" tag in the modifyTextForQuote function. 

Explained enough reason. 
That's all. 
Thank you for your considering my solution.

**Comment by s77rt** [comment] 2023-07-02 13:19
@code0406 I don't think we should modify `heading1` rule the way you did, we don't need to add the line break on every match (it will cause unnecessary line breaks), we should just remove it from the regex not to be captured. Also I would prefer to keep `modifyTextForQuote` untouched, it feels awkward to have this function check for `<h1>` tag.

**Comment by s77rt** [comment] 2023-07-02 13:35
@spcheema Thanks, that should do it. But let's try get this even better. Maybe we can explore another solution that does not involve adding new rules.

**Comment by s77rt** [comment] 2023-07-02 23:53
@spcheema I understand that. Usually such regex issues can be fixed in many ways, the best way often requires an out of the box thinking, I just don't want to miss that :sweat_smile: but we have good solutions already so we will most likely choose a solution this week.

Can you please add the "modify heading1 regex to conditionally capture the new line" approach to your proposal (in alternative solutions section)

**Comment by code0406** [comment] 2023-07-03 09:53
> @code0406 I don't think we should modify `heading1` rule the way you did, we don't need to add the line break on every match (it will cause unnecessary line breaks), we should just remove it from the regex not to be captured. Also I would prefer to keep `modifyTextForQuote` untouched, it feels awkward to have this function check for `<h1>` tag.

It's a perfect solution based on the logic and principle of the "heading1 regex", modifyTextForQuote, and heading1 ui panel format. Let me consider a more look-good approach.

**Comment by s77rt** [comment] 2023-07-04 16:26
@code0406 and @spcheema Thank you for your continuous work here. I think we can go with @spcheema's [proposal](https://github.com/Expensify/App/issues/21846#issuecomment-1612228425).

:ribbon: :eyes: :ribbon: C+ reviewed

**Comment by cead22** [comment] 2023-07-07 01:01
This was just assigned to contributors, so it's not overdue

**Comment by cead22** [comment] 2023-07-10 20:37
> @cead22 @s77rt PR is up for review [Expensify/expensify-common#557](https://github.com/Expensify/expensify-common/pull/557)

@spcheema this is merged now

**Comment by s77rt** [comment] 2023-07-15 18:16
- The PR that introduced the bug has been identified: This existed since day one https://github.com/Expensify/expensify-common/pull/468
- The offending PR has been commented on: https://github.com/Expensify/expensify-common/pull/468#discussion_r1264522145
- A discussion in #expensify-bugs has been started: I don't think this is needed here, the automatic tests should be enough to prevent such bugs.
- Determine if we should create a regression test for this bug: No

**Comment by conorpendergrast** [comment] 2023-07-21 23:20
I will check in on is one, and confirm before paying. I'm OoO on Monday and Tuesday, and will be back to this on Wednesday 26th with confirmation

**Comment by cead22** [comment] 2023-07-26 00:29
Not overdue per @conorpendergrast 's update above

**Comment by conorpendergrast** [comment] 2023-07-26 08:26
@cead22 and I agree with an exception here as the C and C+ acted with urgency. 

Everyone has been paid accordingly, and contracts ended. We're all done, thanks!

**Closed by conorpendergrast** 2023-07-26 08:26 UTC
Labels: External, Daily, Awaiting Payment, Bug
