### ISSUE TITLE
[Search v1] - "Delete" option appears for paid expenses for submitter

### ISSUE THREAD

**Issue by m-natarajan** [Expensify/App#44802] opened 2024-07-04 03:53 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___
Issue found when validating #44385
**Version Number:** 9.0.4-0
**Reproducible in staging?:** y
**Reproducible in production?:** no 
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** Applause internal team
**Slack conversation:**

## Action Performed:
- User as a submitter has at least one paid expense.

1. Go to staging.new.expensify.com
2. Go to Search > Expenses.
3. Click on the checkbox of the paid expense.
4. Click on the dropdown button.

## Expected Result:
"Delete" option will not appear for paid expenses.

## Actual Result:
"Delete" option appears for paid expenses, and nothing happens when deleting it.
As a result, user cannot bulk delete the expenses when both paid and unpaid expenses are selected.

## Workaround:
unknown
## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [x] Android: mWeb Chrome
- [x] iOS: Native
- [x] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

https://github.com/Expensify/App/assets/38435837/056aee1b-4408-41d9-93fd-508971e89b6a

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by m-natarajan** [comment] 2024-07-04 03:55
@kadiealexander FYI I haven't added the External label as I wasn't 100% sure about this issue. Please take a look and add the label if you agree it's a bug and can be handled by external contributors

**Comment by m-natarajan** [comment] 2024-07-04 03:55
We think that this bug might be related to  #vip-vsb

**Comment by nkdengineer** [comment] 2024-07-04 09:17
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
"Delete" option appears for paid expenses, and nothing happens when deleting it.
As a result, user cannot bulk delete the expenses when both paid and unpaid expenses are selected.

### What is the root cause of that problem?
We show the delete option if `itemsToDelete` is not an empty array and the `itemsToDelete` is filtered out from `selectedItemsKeys` by checking `item.canDelete`. But after the transaction is paid, `item.canDelete` still `true`. And then the delete option still appears if we only selected the paid expense.

https://github.com/Expensify/App/blob/a84f68eeb1f72d0ca3308a4bdc9dc78e59a46d2e/src/components/Search/SearchPageHeader.tsx#L50-L55
### What changes do you think we should make in order to solve the problem?
We should filter out the item here if it's paid by checking `item.action` is `CONST.SEARCH.ACTION_TYPES.PAID` or not.
```
const itemsToDelete = selectedItemsKeys.filter((id) => selectedItems[id].canDelete && item.action !== CONST.SEARCH.ACTION_TYPES.PAID); 
```

https://github.com/Expensify/App/blob/a84f68eeb1f72d0ca3308a4bdc9dc78e59a46d2e/src/components/Search/SearchPageHeader.tsx#L50

And I think BE also need to update `canDelete` of transaction item to false when it's paid.
### What alternative solutions did you explore? (Optional)
NA

**Comment by luacmartins** [comment] 2024-07-04 20:44
This should be fixed on the backend, since the backend has all the information to decide if a transaction can be deleted or not.

**Comment by kadiealexander** [comment] 2024-07-09 02:24
Not overdue!

**Comment by luacmartins** [comment] 2024-07-11 22:43
PR up

**Comment by kadiealexander** [comment] 2024-07-16 04:59
@luacmartins looks like we can close this, yeah?

**Comment by luacmartins** [comment] 2024-07-16 15:20
Yea, I confirmed the fix in staging
![Screenshot 2024-07-16 at 9 20 45 AM](https://github.com/user-attachments/assets/3ddb643e-92bd-4ec8-b3b3-aa115d1dfe1e)

**Closed** 2024-07-16 15:20 UTC
Labels: Engineering, Daily, Internal, Bug
