### ISSUE TITLE
[Awaiting C+ payment confo] [HOLD for payment 2023-10-12] [$1000] The avatar located in the header of the Money Request/Owes chat is not opening on click.

### ISSUE THREAD

**Issue by kavimuru** [Expensify/App#19342] opened 2023-05-20 14:17 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:

1. Requested money from a user, which created a new report for that request.
2. Clicked on the avatar in the header of the Money Request/Owes chat.
3. Observed that clicking on the avatar does not open it, despite the expected behavior of avatars opening on click in other chats.

## Expected Result: 
When the avatar positioned in the header is clicked, it should open.
## Actual Result: 
The avatar positioned in the header cannot be opened when clicked.

## Workaround:
Can the user still use Expensify without this being fixed? Have you informed them of the workaround?

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android / native
- [x] Android / Chrome
- [x] iOS / native
- [x] iOS / Safari
- [x] MacOS / Chrome / Safari
- [x] MacOS / Desktop

**Version Number:** 1.3.16.5
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/43996225/b909744b-6f2a-447e-a590-672ce5717d60

https://github.com/Expensify/App/assets/43996225/24ef35e7-a82f-4f54-9485-47732cf8f20e

**Expensify/Expensify Issue URL:**
**Issue reported by:** @usmantariq96
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1684347603337849

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~0156545f23df45ccab</li>
        <li>Upwork Job ID: 1660793182204600320</li>
        <li>Last Price Increase: 2023-05-29</li>
    </ul>
</details>

**Comment by PrashantMangukiya** [comment] 2023-05-20 14:18
## Proposal

Posting proposal early as per new [guidelines](https://github.com/Expensify/App/blob/main/contributingGuides/CONTRIBUTING.md#propose-a-solution-for-the-job)

### Please re-state the problem that we are trying to solve in this issue.
The avatar located in the header of the Money Request/Owes chat is not opening on click.

### What is the root cause of that problem?
**1) Money request payer header**  is rendering via `<HeaderWithCloseButton>` component at line 91 as shown below.
https://github.com/Expensify/App/blob/737862677811acc2b05c68209a56ecd58bee59f3/src/components/MoneyRequestHeader.js#L91-L92

Eventually `src/components/HeaderWithCloseButton.js` is rendering ` <AvatarWithDisplayName>` via code below:
https://github.com/Expensify/App/blob/737862677811acc2b05c68209a56ecd58bee59f3/src/components/HeaderWithCloseButton.js#L170-L174

We can see there is no pressable used with AvatarWithDisplayName. So it will not open details page when clicked.


**2) Money request payee** header render via line 120 as shown code below:
https://github.com/Expensify/App/blob/737862677811acc2b05c68209a56ecd58bee59f3/src/components/MoneyRequestHeader.js#L120-L125

This is also not using pressable,  so it will not open details page when clicked. 

**So this is the root cause the problem that both payer and payee header not clickable.**

### What changes do you think we should make in order to solve the problem?
To solve this we have to wrap Payer and Payee header text with Pressable.

**1) How to make Payer header clickable:** 
From `App/src/components/MoneyRequestHeader.js` we have to pass new prop as `onAvatarWithDisplayPress`  to `HeaderWithCloseButton` component as shown code below.

```javascript
<HeaderWithCloseButton
   shouldShowAvatarWithDisplay 
    onAvatarWithDisplayPress={() => {
        Navigation.navigate(ROUTES.getDetailsRoute(moneyRequestReport.ownerEmail))
    }}
    ...
/>
```

Thereafter within `src/components/HeaderWithCloseButton.js` wrap `<AvatarWithDisplayName>` at line 170 with Pressable and set `onPress` to `this.props.onAvatarWithDisplayPress`  as shown code below:

```javascript
{this.props.shouldShowAvatarWithDisplay && (
    <Pressable onPress={this.props.onAvatarWithDisplayPress}>
        <AvatarWithDisplayName
            ...
        />
    </Pressable>
)}
``` 

**2) How to make Payee header clickable:** 
Within `src/components/MoneyRequestHeader.js` at line 120 wrap Text component with pressable as shown below:

```javascript
<Pressable
    onPress={() => {
        Navigation.navigate(ROUTES.getDetailsRoute(moneyRequestReport.managerEmail))
    }}
>
    <Text
        ...
    >
        {payeeName}
    </Text>
</Pressable>
``` 

So this will make both Payer and Payee clickable as shown in result video.


### What alternative solutions did you explore? (Optional)
None

<details>
<summary>Result</summary>

https://github.com/Expensify/App/assets/7823358/b56deb12-882d-46b3-8b8e-87f40efade97

</details>

**Comment by mountiny** [comment] 2023-05-24 12:52
I am not sure honestly, I think we should allow this as its bringing confusing inconsistency to the user if they can click on this in other places in the app. Also it should not be any problem from the coding perspective I believe.

**Comment by Julesssss** [comment] 2023-05-24 13:46
I think both of these statements are true: 
- Because the profile image is not clickable, this is not a bug
- A valid feature request is to make the avatar clickable

**Comment by mountiny** [comment] 2023-05-24 13:48
I would say it was just an oversight from our initial implementation but we can call it a feature request 😂

**Comment by strepanier03** [comment] 2023-05-24 22:33
@mountiny @Julesssss - I'm good with that approach. I can't find much documentation about how the BZ should handle feature requests in E/App, so in this case can we let proposals roll in and choose the one that works or does this need to be handled internally?

**Comment by Julesssss** [comment] 2023-05-25 07:50
Hey @strepanier03, yeah the process is pretty much identical from here on. 

@fedirjh please go ahead with proposal review when you're ready.

**Comment by trjExpensify** [comment] 2023-05-25 18:21
Should the iouReport / expenseReport details page by the member's details page just like a DM though? 🤔 

I think we should do nothing here for the time being. 1) it's a feature request 2) this might not be the correct path, for which we should have a wider discussion as we progress and add more functionality surrounding expense/iouReports in NewDot. Things like; can you adjust your notification preferences for an expense/iouReport, like a room? Can you see a list of everyone the report is shared with? Can you share it with others? All of which would make sense to live in the details pane of the iou/expenseReport like room settings do. 

CC: @JmillsExpensify

**Comment by mountiny** [comment] 2023-05-26 00:08
regarding the details panel, you can do it in the parent DM or workspace chat, so I think this part makes sense to add. But we can discuss more for sure.

**Comment by trjExpensify** [comment] 2023-05-26 14:45
>regarding the details panel, you can do it in the parent DM or workspace chat, so I think this part makes sense to add.

What does "do it" mean? I'm more so talking about whether the content of the details pane for an expense/iouReport should = that of a DM.

**Comment by mountiny** [comment] 2023-05-26 16:18
I am only talking about clicking on the payer/payee email and opening their details, thats unrelated to the reports details

**Comment by mountiny** [comment] 2023-05-29 09:37
@fedirjh lets wait to clarify this with @trjExpensify

**Comment by trjExpensify** [comment] 2023-05-30 21:15
>I am only talking about clicking on the payer/payee email and opening their details, thats unrelated to the reports details

@mountiny in any other chat header, clicking anywhere takes you to the report's details page? So we're saying in this instance of an expense/iouReport, if you click on the avatar only it takes you to an individual's details page, and conceivably outside of that to the report's details page if we add one? Also, if you click on the payer in an expenseReport (which is the workspaceName), what do we show as the details for email, local time, message etc?

With the ongoing discussions about refining the chat headers across report types as well, I still think we do nothing here for now and revisit it more broadly.

**Comment by strepanier03** [comment] 2023-06-01 23:33
@mountiny - What do you think? I think it makes sense to do nothing here until we finish the ongoing discussion about the chat headers because we might fix this and then have to change it to accommodate the outcomes of those discussion.

**Comment by mountiny** [comment] 2023-06-02 00:25
Valid points, thanks, lets wait for narrowing down the headers discussions and then we can go from there!

**Comment by grgia** [comment] 2023-06-05 13:45
Going to add Hold label while header discussions are ongoing

**Comment by strepanier03** [comment] 2023-06-05 22:38
Since this is on Hold I moved it to Weekly. We can relabel once the discussions are done. If someone thinks we should keep it daily feel free to change it back.

**Comment by strepanier03** [comment] 2023-06-13 20:14
@trjExpensify - I am leaving on sabbatical and this is on hold so I am reassigning to a new BZ team member. For now this is just monitoring until the status changes. 

Thank you!

**Comment by grgia** [comment] 2023-06-19 11:11
@trjExpensify now that the headers have been decided on, should we still hold on this issue? I personally think that all the avatars in header should follow the pattern of opening the details page for their prospective user.

**Comment by JmillsExpensify** [comment] 2023-06-19 16:02
> Can you adjust your notification preferences for an expense/iouReport, just like a room? (i.e the default being immediately, but the ability to change it to mute or daily and suppress being notified of new messages, requests getting added to the report etc).
> Can you see a list of everyone the report is shared with? (i.e a members list for everyone the report is shared with)
> Can you share it with others? (i.e QR code for iou/expenseReports and copyURL function)

Agree, I think the answer to all of these is a yes. The last two in particular already exist on OldDot, and I don't think we want to deprecate that functionality on NewDot.

**Comment by trjExpensify** [comment] 2023-06-21 22:26
Cool, so we need to mock up how that looks really as a next step here. 

**Details page:** 
1. use's the expense/iouReport avatar
2. underneath in bold is the report title 
3. The parent chat is in supporting text font i.e "from <parent-report>" 

**Settings:**
1. remove welcome message
2. remove "who can post"

**Share code page**
1. bold is the report title 
2. The parent chat is in supporting text font i.e "from <parent-report>" 

Anything else?

**Comment by shawnborton** [comment] 2023-06-26 15:16
Hmm not sure if we have one central place for this in Figma, but I'm happy to help you create anything - just tag me in a file somewhere and I can drop some mocks in.

**Comment by trjExpensify** [comment] 2023-07-05 18:02
Cool, made a start on this. Got most of the way for the expenseReport, just need the QR graphic for the `Share code` page, so I can illustrate the changes on that. Tagged yah!

**Comment by trjExpensify** [comment] 2023-07-05 21:26
Alright, here we go [based on this](https://github.com/Expensify/App/issues/19342#issuecomment-1601759336).

![image](https://github.com/Expensify/App/assets/16232057/a4ab8f25-0d84-449e-9536-c7259f055160)

**Comment by trjExpensify** [comment] 2023-07-17 12:46
Where do we want to go from here on this issue. Is this perhaps one that should come after @grgia has finished the work on the new iou/expenseReport headers?

**Comment by trjExpensify** [comment] 2023-07-26 11:51
Neat, so with those through the door I think we can proceed here. To put a full recap together to finalise this:

**UI**

![image](https://github.com/Expensify/App/assets/16232057/a4ab8f25-0d84-449e-9536-c7259f055160)

**Details page:**
- use's the same avatar as the expense/iouReport
- underneath in bold is the report title, just like the first line in the new expense/iouReport headers i.e "%workspaceName owes %reportTotalAmount%"
- The parent chat is in supporting text font, just like the second line in the new expense/iouReport headers i.e "From %parentChat% in %workspaceName%"

**Settings page:**
- `Notify me about new messages` pushes to the notification preferences page.
- remove welcome message row
- remove "who can post" row
- `Name` field is read-only
- `Workspace` field is read-only

Note: I'm having second thoughts on extending the "room" notification preferences of immediately/daily/mute to expense/iouReports without more consideration? (CC: @mountiny @JmillsExpensify). I wonder if that's a bit of a larger initiative that we should decouple from this. Like, for example, you don't have those preferences on DMs currently either - maybe those should all come together separately and for now we just don't show this row in this iou/expenseReport details page.

**Share code page:**
- For an expenseReport:
   - The avatar is the green Expensify avatar, just like the QR code other rooms right now. 
   - In bold within the QR code is the report title, just like the first line in the new expense/iouReport headers i.e "%workspaceName owes %reportTotalAmount%".
   - The workspace name is in supporting text font for an expenseReport i.e `Duraflame`
- For an iouReport:
  - The avatar is the green Expensify avatar, just like the QR code on other rooms right now. 
  - In bold within the QR code is the report title, just like the first line in the new expense/iouReport headers i.e "%payerName% owes %reportTotalAmount%".
  - The displayName of the two participants of the DM the iouReport is shared in is in supporting text font for an iouReport i.e `Tom & Shawn` (and fall back on primaryLogin if no displayName is set). 

We all good with that?

Sidebar, @fedirjh don't suppose you fancy taking this on when we're ready?

**Comment by mountiny** [comment] 2023-07-26 12:30
> I wonder if that's a bit of a larger initiative that we should decouple from this. Like, for example, you don't have those preferences on DMs currently either - maybe those should all come together separately and for now we just don't show this row in this iou/expenseReport details page.

I think the notification settings would deserve its own discussion in general and holistic approach I agree.

**Comment by trjExpensify** [comment] 2023-07-27 11:16
Yeah, I'm thinking the same. In which case the settings page for now would just be the read-only `Name` and `Workspace` fields. :)

**Comment by trjExpensify** [comment] 2023-08-07 09:42
Cool, so let's move this on to a PR. I'm removing the `help wanted` label as @fedirjh I saw your thumbs up. Can you proceed with a PR based on [this final rundown](https://github.com/Expensify/App/issues/19342#issuecomment-1651655981)? 👍

**Comment by trjExpensify** [comment] 2023-08-14 10:26
@fedirjh bump on the above. Can we get a PR up, please?

**Comment by trjExpensify** [comment] 2023-09-11 11:55
PR is in review melvin, chiiill. Should be unheld now after the merge freeze.

**Comment by trjExpensify** [comment] 2023-10-13 17:19
Okay, so by my calculations: 

- $1000 to @fedirjh for the review
- $1000 to @usmantariq96 for the PR 

Everyone agree? Let me know and I'll start settling up! :)

**Comment by trjExpensify** [comment] 2023-10-16 11:36
Ah yes, [this PR](https://github.com/Expensify/App/pull/24533) for ref. Cool, amended. 

- Offers sent to @fedirjh & @usmantariq96.
- @allroundexperts can request.

**Comment by trjExpensify** [comment] 2023-10-16 11:56
@fedirjh paid!

**Comment by usmantariq96** [comment] 2023-10-16 15:59
@trjExpensify offer accepted
Thanks

**Comment by trjExpensify** [comment] 2023-10-18 21:11
Perfect!

**Closed by trjExpensify** 2023-10-18 21:11 UTC
Labels: External, Daily, NewFeature, Awaiting Payment

**Comment by JmillsExpensify** [comment] 2023-10-23 16:44
$1,000 payment approved for @allroundexperts based on [this summary](https://github.com/Expensify/App/issues/19342#issuecomment-1761879829).
