### ISSUE TITLE
IOS - Connect Bank Account - Reset button non functional in calendar while adding bank account

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#12449] opened 2022-11-03 21:04 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Launch the app and login
2. Go to Profile > Workspace > Connect a bank account > Connect manually
3. Enter a valid routing number and account number
4. Click save & continue
5. On company information page, click save & continue without selecting the incorporation date (clear the date first if already selected) or use a future date
6. Click on the calendar icon
7. Click reset

## Expected Result:
Date selected should be reset to current date

## Actual Result:
Reset button non functional

## Workaround:
Unknown

## Platform:

Where is this issue occurring?

- iOS

**Version Number:** 1.2.23.7

**Reproducible in staging?:** Yes

**Reproducible in production?:** Yes

**Email or phone of affected tester (no customers):** 

**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Notes/Photos/Videos:** Any additional supporting documentation

https://user-images.githubusercontent.com/93399543/199833859-bff2772e-1448-4a71-b31b-d72b3aec25a8.mp4

**Expensify/Expensify Issue URL:** 

**Issue reported by:** Applause - Internal Team

**Slack conversation:** 

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by hungvu193** [comment] 2022-11-04 05:43
<b>Proposal</b>
Current reset action on date picker always return the `initialValue`, and every time the picker was showed, the `initialValue` was updated to the current  date picker value, that why when we press `Reset` nothing happened.

<b>Solution</b>
Reset to today every time user preset reset by changing the `reset` function inside `DatePicker/index.ios`:

```diff
    reset() {
-        this.setState({selectedDate: this.initialValue});
+        this.setState({selectedDate: new Date()});
    }
```

Result:

https://user-images.githubusercontent.com/16502320/199898871-127f85e8-4766-429e-bd17-0eb503e4ffc8.mov

**Comment by MitchExpensify** [comment] 2022-11-04 16:35
I can't seem to reproduce:

https://user-images.githubusercontent.com/36425901/200028064-bbca832d-666a-4e94-a7ee-45b7492391b3.MP4

**Comment by hungvu193** [comment] 2022-11-05 04:50
> I can't seem to reproduce:
> 
> 
> 
> https://user-images.githubusercontent.com/36425901/200028064-bbca832d-666a-4e94-a7ee-45b7492391b3.MP4
> 
> 
> 
> 

You need to select a value first, after that press Reset

**Comment by hungvu193** [comment] 2022-11-07 14:09
> I gave that a try here and still can't reproduce:
> 
>  RPReplay_Final1667826863.MP4

Because you select the value for the date picker is today, that's why it always reset to today when you press `Reset`.
Let try again with the following step:
1. Click on Datepicker and choose a value that difference with today (ie: 1/1/2010), press `Done`.
2. Click on Datepicker again and press `Reset`.

**Comment by MitchExpensify** [comment] 2022-11-07 14:28
Got it! Thanks for helping me reproduce it:

https://user-images.githubusercontent.com/36425901/200334312-e3a1651d-faac-4756-887c-5ad3d0287c7d.MP4

This feels super expected. It is resetting to the last saved date each time reliably which seems fine. I'll ask in Slack if others agree

**Comment by MitchExpensify** [comment] 2022-11-07 14:33
[Asked the room here](https://expensify.slack.com/archives/C01GTK53T8Q/p1667831588058479)

**Comment by mvtglobally** [comment] 2022-11-09 03:45
Issue not reproducible during KI retests. (First week)

**Comment by MitchExpensify** [comment] 2022-11-14 17:10
Nobody jumped in with a second opinion so I'm going with my take on this issue - It is expected > Closing

**Closed by MitchExpensify** 2022-11-14 17:10 UTC
Labels: Daily, Overdue, Bug
