### ISSUE TITLE
[$1000] Cursor is clickable in SignIn page but non-clickable in 2FA Magic Code Next case

### ISSUE THREAD

**Issue by kavimuru** [Expensify/App#19706] opened 2023-05-26 23:11 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:

1. Go to "Settings."
2. Click on "Security."
3. Select "Two-factor authentication."
4. On the "Step 2: Verify" page, when hovering over the "Next" button, the cursor turns to 'not-allowed' until the correct magic code is entered.
5. Now Sign out.
6. Notice the "Sign in" button when hovered doesn’t turn to 'not-allowed' until the correct magic code is entered.

 
## Expected Result: 
In both cases, the cursor should either be clickable or display 'not-allowed'.

## Actual Result: 
On the "Sign in" page, the cursor does not show the 'not-allowed' symbol, but in the case of 2FA, it does show, which makes it inconsistent.

## Workaround:
Can the user still use Expensify without this being fixed? Have you informed them of the workaround?

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [x] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 1.3.19-2
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/43996225/3d67874c-4407-4706-b085-bf2d6a00d938

https://github.com/Expensify/App/assets/43996225/205f9e25-5359-4428-a4d1-cab9d2276b88

**Expensify/Expensify Issue URL:**
**Issue reported by:** @usmantariq96
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1684652267526309

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01bd19108f6a21953a</li>
        <li>Upwork Job ID: 1663264742966722560</li>
        <li>Last Price Increase: 2023-05-29</li>
    </ul>
</details>

**Comment by ahmedGaber93** [comment] 2023-05-26 23:34
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
Cursor is clickable in Singin page but non-clickable in 2FA Magic Code Next case
### What is the root cause of that problem?
on VerifyPage.js the button next has prop `isDisabled=true`, so it always displayed as a disabled.

https://github.com/Expensify/App/blob/57ff85bfdfea37aeda8deb246b4cc7abd38b1236/src/pages/settings/Security/TwoFactorAuth/VerifyPage.js#L131-L136

another note is the button "next" doesn't do any job, it just UI without `onPress` prop, and the form will submit when MagicCodeInput onFulfill 

https://github.com/Expensify/App/blob/37163b099b57cc996657a62a4afc1110dff3ed65/src/pages/settings/Security/TwoFactorAuth/TwoFactorAuthForm/BaseTwoFactorAuthForm.js#L79


### What changes do you think we should make in order to solve the problem?
remove button "next" or keep it and remove isDisabled. 

### What alternative solutions did you explore? (Optional)

**Comment by Web95Dev** [comment] 2023-05-29 19:42
Analyze the current codebase and identify the components that need to be migrated to React Native.
Develop a plan for the migration process, including a timeline and milestones.
Create a new React Native project and integrate it with the existing codebase.
Migrate the identified components to React Native, ensuring that they are fully functional and compatible with all platforms.
Test the migrated components on all platforms to ensure that they meet the required standards.
Submit the code for review and merge it into the main codebase.

**Comment by sonialiap** [comment] 2023-05-29 21:40
@allroundexperts looks like we have a few proposals, what are your thoughts on them?

**Comment by jasperhuangg** [comment] 2023-06-01 05:09
Not really sure this is a bug that needs our attention right now. I say we can go ahead and close this out as it doesn't really affect user experience.

**Closed by jasperhuangg** 2023-06-01 05:09 UTC
Labels: External, Daily, Help Wanted, Bug
