### ISSUE TITLE
[$500] Android - Attachment - Taken image cannot be fully seen in chat composer

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#31719] opened 2023-11-22 16:05 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.2.0
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** Applause - Internal Team
**Slack conversation:**

## Action Performed:
1. Open New expensify app
2. Navigate to any conversation
3. Tap on + button from chat composer> Add attachment> Take photo> Send

## Expected Result:
Preview of the taken image should be visible in full size, just like screenshot

## Actual Result:
Taken image from device camera cannot be fully seen in chat composer. It is enlarged

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [ ] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

https://github.com/Expensify/App/assets/93399543/163587c3-72ce-448e-8c52-9a743272feb7

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01f86fe396311bc86f</li>
        <li>Upwork Job ID: 1727357578653110272</li>
        <li>Last Price Increase: 2023-11-22</li>
    </ul>
</details>

**Comment by situchan** [comment] 2023-11-22 16:17
Dupe of #26086

**Comment by MitchExpensify** [comment] 2023-11-23 19:14
Closing because dupe

**Closed by MitchExpensify** 2023-11-23 19:14 UTC
Labels: External, Daily, Help Wanted, Bug
