### ISSUE TITLE
[HOLD for payment 2023-08-01] [$1000] dev:  Inconsistency in showing task description when the number of rows increases

### ISSUE THREAD

**Issue by kavimuru** [Expensify/App#22493] opened 2023-07-08 18:27 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Create a task
2. Click description
3. Text: 1 to 7 each number each row => save
4. Observe that description only sees a part that can't be scrolled
5. Click description, clear previous description
6. Text long message => save
7. Observe that 3 dots are added to the description and can be scrolled
## Expected Result:
 There must be consistency in showing description when the number of rows increases
## Actual Result: 
How to show description is different when the number of rows increases

## Workaround:
Can the user still use Expensify without this being fixed? Have you informed them of the workaround?

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [x] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** DEV
**Reproducible in staging?:**  dev only
**Reproducible in production?:** dev only
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/43996225/df976d2b-7189-49f5-9d40-53291b34ea44

**Expensify/Expensify Issue URL:**
**Issue reported by:** @namhihi237 
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1688800884991609

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~0116467439890d0404</li>
        <li>Upwork Job ID: 1679117287040221184</li>
        <li>Last Price Increase: 2023-07-12</li>
    </ul>
</details>

**Comment by mananjadhav** [comment] 2023-07-12 17:25
Looping in @shawnborton. I don't see this as a real value issue as I don't see we'll be adding numeric list only for the description.

But one minor thing that's off is if we have a large description, we show `ellipses`, but the content is scrollable. I think that's intentional? But I am not sure. If that's the case, we should just close this one out.

**Comment by shawnborton** [comment] 2023-07-12 17:28
Hmm this seems very strange. cc @jasperhuangg @thienlnam I forget where we landed with truncating the description row, but now I am wondering if we should never truncate description at all.

**Comment by thienlnam** [comment] 2023-07-12 17:40
I don't remember either, but I thought we standardized on like 3 rows or something. I agree we could not truncate so that you could view the entire description without having to push to page to edit

**Comment by tranvantoan-qn** [comment] 2023-07-13 17:15
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
Unable to view full task's description when the task is completed

### What is the root cause of that problem?
We always set the maximum number of lines for the description to be 3, regardless of whether the task is completed or not.
https://github.com/Expensify/App/blob/8923cb0c558b8e9e57a64cf01292c8434e6a4b6f/src/components/ReportActionItem/TaskView.js#L108

### What changes do you think we should make in order to solve the problem?
Add a condition to check if the task is completed. If it is completed, we won't limit the maximum number of lines by using `Number.MAX_VALUE. `

So the users can view full description

Note that we must set some value for `numberOfLinesTitle` attribute, otherwise it will be set to 1 by default

```javascript 

            <MenuItemWithTopDescription
                description={props.translate('task.description')}
                title={props.report.description || ''}
                onPress={() => Navigation.navigate(ROUTES.getTaskReportDescriptionRoute(props.report.reportID))}
                shouldShowRightIcon={isOpen}
                disabled={!isOpen}
                wrapperStyle={[styles.pv2]}
                numberOfLinesTitle={isCompleted ? Number.MAX_VALUE : 3}
                shouldGreyOutWhenDisabled={false}
            />

``` 

### What alternative solutions did you explore? (Optional)
N/A

**Comment by laurenreidexpensify** [comment] 2023-07-17 15:46
@shawnborton / @mananjadhav is the steer here that we are still going to fix this?

**Comment by mananjadhav** [comment] 2023-07-17 19:26
Both the proposals are identical for the revised expected results. But @namhihi237's proposal posted the solution first and hence I think we'll use theirs.

While I tag an internal engineer by reviewing the proposals, @shawnborton and () I think we should set a limit for the description to atleast a few 100 characters. This would definitely hit some limit on the API and then be reported as a bug.

🎀 👀 🎀 C+ reviewed.

**Comment by laurenreidexpensify** [comment] 2023-07-19 12:57
@shawnborton @stitesExpensify can you address @mananjadhav 's comment [here](https://github.com/Expensify/App/issues/22493#issuecomment-1638741795) when you have a mo, thanks!

**Comment by stitesExpensify** [comment] 2023-07-19 20:55
I think we can deal with the limit when we hit it, we don't need to fix that right now.

@namhihi237 proposal looks good to me!

**Comment by mananjadhav** [comment] 2023-07-20 14:11
@spcheema Apologies for not responding sooner.  For me the most important change was to remove the `numberOfLines`.  We do work out the kinks in the PR.  Based on what I saw in the history, etc. @namhihi237 pointed that out first.

> So it acceptable that C++ assume things you will do. That's strange and weird.
> Please test the changes locally before making a decision.

I am not keen on modifying the `styles.preWrap`. I should've clarified. But please have patience for the team to respond before jumping to conclusions, in case you need any clarifications

cc - @stitesExpensify

**Comment by mananjadhav** [comment] 2023-07-29 19:49
This is more like a feature request, hence we don't have a tagged PR.

But I think we should a regression test here, so that we don't end up adding length restriction on the desscription.

1. Open FAB, click on `Assign Task`
2. Create a task with a long description (about more than 2-3 paragraphs)
3. Open task detail and verify that can view the whole description without any ellipses.


@laurenreidexpensify Please note this PR had a regression, hence the payout will be deducted an there is no timeline bonus.

**Comment by laurenreidexpensify** [comment] 2023-08-01 12:46
Payment Summary: 

- External issue reporter @namhihi237 $250 paid in Upwork
- Contributor that fixed the issue @namhihi237 $1000 paid in Upwork
- Contributor+ that helped on the issue and/or PR $1000 Eligible for manual request @mananjadhav

**Comment by mananjadhav** [comment] 2023-08-01 12:58
> Please note this PR had a regression, hence the payout will be deducted and there is no timeline bonus.

@laurenreidexpensify There would be a deduction of 500 in this PR. The actual payout for me and @namhihi237 is $500.

**Comment by JmillsExpensify** [comment] 2023-08-01 18:54
Yes agreed. Mind updating your summary @laurenreidexpensify?

**Comment by laurenreidexpensify** [comment] 2023-08-02 09:45
Updated Payment Summary:

- External issue reporter @namhihi237 $250 paid in Upwork
- Contributor that fixed the issue @namhihi237 $500 paid in Upwork (Expensify has requested $500 refund for overpayment) 
- Contributor+ that helped on the issue and/or PR $500 Eligible for manual request @mananjadhav

**Closed by laurenreidexpensify** 2023-08-02 09:45 UTC
Labels: External, Daily, Awaiting Payment, Bug

**Comment by JmillsExpensify** [comment] 2023-08-02 16:33
Reviewed details for @mananjadhav. These details are accurate based on summary from Business Reviewer and are now approved for payment in NewDot.
