### ISSUE TITLE
[HOLD for payment 2023-10-23] [$500] [Feature Request] Pressing back while writing notes makes text disappear

### ISSUE THREAD

**Issue by kavimuru** [Expensify/App#28599] opened 2023-10-02 11:33 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Go to a contacts DM
2. Click on Private Note
3. Click on  My Note
4. Type something (don't save)
5. press the back button
6. click on My Note again.
7. Verify that the draft note you wrote has disappeared
## Expected Result: 
The note should not disappear
## Actual Result: 
The note disappears and we see a blank input page
## Workaround:
Can the user still use Expensify without this being fixed? Have you informed them of the workaround?

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [x] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:**
**Reproducible in staging?:**
**Reproducible in production?:**
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation

[Screencast from 19-09-23 01_16_24 AM IST.webm](https://github.com/Expensify/App/assets/43996225/e31a1536-6b6e-4764-8950-dc9af25fc38c)

**Expensify/Expensify Issue URL:**
**Issue reported by:** @Someshwar-Tripathi
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1695047398155859

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~012d86d9fa187b7292</li>
        <li>Upwork Job ID: 1708808891588886528</li>
        <li>Last Price Increase: 2023-10-02</li>
<li>Automatic offers: </li>
<ul>
<li>DylanDylann | Contributor | 27097407</li>
</ul></li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @johncschuster</details>

**Comment by DylanDylann** [comment] 2023-10-02 11:33
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
- [Inconsistency] Pressing back while writing notes makes text disappear

### What is the root cause of that problem?
- Currently, we do not have the logic "save as draft" for private notes like the message compose, so pressing back while writing notes makes the text disappear

### What changes do you think we should make in order to solve the problem?
- We can create the logic to save the private notes as draft for each reports as we do with the message composer:
1. Create the collection PRIVATE_NOTES_DRAFT: 'privateNotesDraft_' to store the draft private note for each report.
2. Create savePrivateNotesDraft(reportID, note) function to save the draft private note to local storage:
```
function privateNotesDraft(reportID, note) {
    Onyx.merge(`${ONYXKEYS.COLLECTION.PRIVATE_NOTES_DRAFT}${reportID}`, note);
}
```
3. The onChangeText here https://github.com/Expensify/App/blob/76c1559fb3fbee1d07c8f210b522b63edd03920e/src/pages/PrivateNotes/PrivateNotesEditPage.js#L118-L131 will become:
```
 onChangeText={(text) => {
                                    privateNotesDraft(reportID, text)
                                    setPrivateNote(text)
                                }}
```
Also, we can consider applying debounce to savePrivateNotesDraft
### What alternative solutions did you explore? (Optional)
- NA

**Comment by techievivek** [comment] 2023-10-02 11:36
Taking over this an engineer as I worked on the implementing the private notes feature so I will able to add some value here.

**Comment by techievivek** [comment] 2023-10-02 11:40
Quick question: What will be the behaviour if we edit multiple private notes? Would a single draft value handle all the edits or for each private notes we create unique draft to store it's value?

**Comment by DylanDylann** [comment] 2023-10-02 11:46
> Taking over this as an engineer(CME) as I worked on implementing the private notes feature so I will able to add some value here

As I mentioned in my proposal, for each private notes we create a unique draft to store it`s value like what we did with compose

**Comment by johncschuster** [comment] 2023-10-05 20:45
@techievivek what do you think about the above?

**Comment by techievivek** [comment] 2023-10-06 08:43
@DylanDylann OK, great, that sounds like a plan. Thanks

**Comment by techievivek** [comment] 2023-10-06 08:44
@robertKozik can you please review the above proposals, thanks.

**Comment by jeet-dhandha** [comment] 2023-10-06 15:52
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
- Feature Save Draft Private Note.

### What is the root cause of that problem?
- New Feature

### What changes do you think we should make in order to solve the problem?
- Create an action in `Report.js`.

```js
function saveReportPrivateNoteDraft(reportID, note, accountID) {
    // Save the draft private note to Onyx
    // Added accountID to the key to make it unique for each user. 
    // As there can be multiple users in a report (Group / Admin / Rooms)
    Onyx.merge(`${ONYXKEYS.COLLECTION.REPORT_PRIVATE_NOTE_DRAFT}${reportID}${accountID}`, note);
}
```

- We will use similar implementaion as [getDraftComment.ts](https://github.com/Expensify/App/blob/main/src/libs/ComposerUtils/getDraftComment.ts) to get the draft private note.

- We will update `onChangeText` of `PrivateNotesEditPage` to save the draft private note.
```js
<TextInput
    {...rest}
    onChangeText={(text) => {
        saveReportPrivateNoteDraft(reportID, text, session.accountID);
        setNoteText(text);
    }}
/>
```

- Then we will update the `savePrivateNote` function to clear the draft private note.

- Finally we will update the `useState` of `PrivateNotesEditPage` to get the draft private note.

```diff
const parser = new ExpensiMark();
+ const draftPrivateNot = useRef(getDraftPrivateNote(report.reportID, route.params.accountID));
const [privateNote, setPrivateNote] = useState(
-    parser.htmlToMarkdown(lodashGet(report, ['privateNotes', route.params.accountID, 'note'], '')).trim()
+    draftPrivateNot.current || parser.htmlToMarkdown(lodashGet(report, ['privateNotes', route.params.accountID, 'note'], '')).trim()
);
```

### What alternative solutions did you explore? (Optional)
- N/A

**Comment by robertKozik** [comment] 2023-10-06 19:44
Hi @techievivek! I've checked the existing proposals, and the one from @DylanDylann looks good and it was the first one which described whole process of implementing this new feature, so I think we can go for it. As for the debounce suggestion, I'm all for it - we don't need excessive onyx calls.

🎀 👀 🎀 C+ reviewed

**Comment by techievivek** [comment] 2023-10-09 09:37
Not overdue, just assigned the job to @DylanDylann

**Comment by techievivek** [comment] 2023-10-09 09:38
@neonbhai Can you please follow the instructions from the comments here https://github.com/Expensify/App/issues/28599#issuecomment-1752652121, so we automate the process next time for you.

**Comment by DylanDylann** [comment] 2023-10-10 09:26
@robertKozik this [PR](https://github.com/Expensify/App/pull/29149) ready for review

**Comment by MariaHCD** [comment] 2023-10-23 12:03
@DylanDylann @techievivek @robertKozik 👋🏼 mind taking a look at this: https://github.com/Expensify/App/issues/27596#issuecomment-1768924985

We think the PR here caused an issue with trailing newlines not being trimmed on the `My Note` page

**Comment by robertKozik** [comment] 2023-10-23 19:14
Thanks for heads up @MariaHCD I've briefy checked our PR and I think as well that our PR reintroduced this problem.

@DylanDylann It looks like this line is flawed https://github.com/Expensify/App/pull/29149/files#r1369162805

**Comment by robertKozik** [comment] 2023-12-05 13:49
Hey! I think the regression pointed before was fixed almost a month ago in this PR https://github.com/Expensify/App/pull/30357.
Automation seems to didn't catch this

**Comment by DylanDylann** [comment] 2024-01-02 09:43
@johncschuster Could you help to process this issue?

**Comment by johncschuster** [comment] 2024-01-24 16:27
Sorry, I missed this! I'll process this later today!

**Comment by johncschuster** [comment] 2024-01-24 19:34
Ok, I'm back.

@robertKozik I'm a bit confused – are you saying in [this comment](https://github.com/Expensify/App/issues/28599#issuecomment-1840830348) that the regression was already fixed?

**Comment by DylanDylann** [comment] 2024-01-25 04:27
@johncschuster The regression fixed long time ago

**Comment by techievivek** [comment] 2024-01-30 09:02
Not overdue, @johncschuster can you please take a look at the above comment.

**Comment by johncschuster** [comment] 2024-02-02 22:31
I've issued payment to @Someshwar-Tripathi. I think we can close this up! Please let me know if I've missed anything!

**Closed by johncschuster** 2024-02-02 22:31 UTC
Labels: External, Daily, NewFeature, Awaiting Payment
