### ISSUE TITLE
[$500] Task - Unable to copy task complete/reopen message

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#27884] opened 2023-09-20 19:23 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___
**Issue found when executing PR** https://github.com/Expensify/App/pull/27119
## Action Performed:
1. Go to staging.new.expensify.com
2. Go to any task report
3. Complete the task and then reopen it
4. Right click on the task completion or reopening message > Copy to clipboard
5. Paste it in the composer

## Expected Result:
The copied task message is pasted

## Actual Result:
The copied task message is not pasted. The message is not copied at all

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android / native
- [x] Android / Chrome
- [x] iOS / native
- [x] iOS / Safari
- [x] MacOS / Chrome / Safari
- [x] MacOS / Desktop

**Version Number:** 1.3.72-6

**Reproducible in staging?:** Yes

**Reproducible in production?:** Yes

**If this was caught during regression testing, add the test name, ID and link from TestRail:**

**Email or phone of affected tester (no customers):**

**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/78819774/cff9b7c5-cf87-4e79-82b6-601322c20fe5

**Expensify/Expensify Issue URL:**

**Issue reported by:** Applause - Internal Team

**Slack conversation:**

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~0181f1cb78999beeb1</li>
        <li>Upwork Job ID: 1706863200146464768</li>
        <li>Last Price Increase: 2023-09-27</li>
    </ul>
</details>

**Comment by lcsvcn** [comment] 2023-09-20 19:42
# Proposal
## Please re-state the problem that we are trying to solve in this issue
The copied task message is pasted

## What is the root cause of that problem?
The cause of the problem is that we need to wrap the `TaskAction` is not using the `CopyTextToClipboard`, where other text are using it.

## What changes do you think we should make in order to solve the problem?
We need to wrap the text with the `CopyTextToClipboard` component. Similar on what is done here:
https://github.com/Expensify/App/blob/4c207ec07ce4d0b3ca3cc4a6f90b02524b4b440f/src/pages/iou/ReceiptSelector/index.js#L118-L121

So at this part, we need to wrap the report action message with the component above, that way it is know that needs to be copied:
https://github.com/Expensify/App/blob/4c207ec07ce4d0b3ca3cc4a6f90b02524b4b440f/src/components/ReportActionItem/TaskAction.js#L23-L25

## What alternative solutions did you explore? (Optional)

**Comment by anmurali** [comment] 2023-09-27 02:47
Yep, can reproduce

**Comment by BhuvaneshPatil** [comment] 2023-09-27 04:18
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
Unable to copy task complete/reopen message, when we try to copy the message of task complete/reopen we are not able to copy it, it does nothing.

### What is the root cause of that problem?
The error for this is that when we copy the message using context menu action (that appears when we hover over it), ti calls onPress method here - 
https://github.com/Expensify/App/blob/d7ad30519d9632201bc711dc8a7f840cc0a8e153/src/pages/home/report/ContextMenu/ContextMenuActions.js#L184-L189

We are getting `reportAction` empty here. That's why it's not able to set the data.

The reason we are getting reportActions empty is how we are retrieving data from ONYX  here - 
https://github.com/Expensify/App/blob/d7ad30519d9632201bc711dc8a7f840cc0a8e153/src/pages/home/report/ContextMenu/BaseReportActionContextMenu.js#L186-L192

For the task completed and reopen action we don't have `taskReportActions` with originalReportID.

We need to use `reportID` for that.

### What changes do you think we should make in order to solve the problem?
- when we get `reportActions` from ONYX we shall get reportActions for both originalReportID and reportID. This will ensure that we have all the report actions and we don't break anything.
- We can use `getReportAction()` method here to get the reportAction in case we have empty reportAction
   https://github.com/Expensify/App/blob/d7ad30519d9632201bc711dc8a7f840cc0a8e153/src/pages/home/report/ContextMenu/BaseReportActionContextMenu.js#L57-L62



### What alternative solutions did you explore? (Optional)
We can directly use `reportID` instead of `originalReportID` but I don't think that would be appropriate here.

**Comment by s77rt** [comment] 2023-09-28 03:48
@lcsvcn Thanks for the proposal. I don't think your RCA is correct. We have the `MiniReportActionContextMenu` inside `ReportActionItem` which handles the mini context menu actions including the copy action.

**Comment by s77rt** [comment] 2023-09-28 03:48
@BhuvaneshPatil Thanks for the proposal. Your RCA makes sense but I don't think we got into the real root cause. As for the solutions: getting report actions for both `originalReportID` and `reportID` or when the report action is empty is a workaround. Using `reportID` instead of `originalReportID` will cause regressions (we will basically revert the use of `originalReportID`).

**Comment by s77rt** [comment] 2023-09-28 03:49
@tienifr Thanks for the proposal. Your RCA is almost correct except I don't think the bug is on `getOriginalReportID`.
> The problem is the condition in [here](https://github.com/Expensify/App/blob/9aea8ec3c8a1c7b24696b928e48abcbfb8dbbcc4/src/libs/ReportUtils.js#L3440) matches Task report actions like complete, reopen as well, since those report actions also have childReportID equals to the Task thread reportID.

This seems to describe the real root cause and I think those report actions should not have `childReportID` in the first place since they are not the parent of that report id. This seems to be a backend issue.

🎀 👀 🎀 C+ reviewed
Need engineer review for a backend bug: Task report actions such as `TASKREOPENED` and `TASKCOMPLETED` have `childReportID` set but they should not. Those report action do not have a child.

**Comment by s77rt** [comment] 2023-10-02 14:25
Not overdue. I think this is waiting for @cead22's input ^

**Comment by s77rt** [comment] 2023-10-04 16:41
@cead22 ^

**Comment by cead22** [comment] 2023-10-05 19:26
Sorry I was sick during the beginning of the week. Looking at the database, I don't see childReportID set for those reportActions, so maybe we're adding it somewhere between when we read from the DB and when we send them to the client

```
created                  reportID          accountID  action         message                                                                                                                                      reportActionID
-----------------------  ----------------  ---------  -------------  -------------------------------------------------------------------------------------------------------------------------------------------  -------------------
2023-09-20 16:08:13.885  4560512847563664  15706656   CREATED                                                                                                                                                     4575512956458859574
2023-09-20 16:08:23.820  4560512847563664  15706656   TASKCOMPLETED  {"html":"completed task: This is a task","lastModified":"2023-09-20 16:08:23.820","taskReportID":4560512847563664,"title":"This is a task"}  3988533150657800252
2023-09-20 16:08:30.051  4560512847563664  15706656   TASKREOPENED   {"html":"reopened task: This is a task","lastModified":"2023-09-20 16:08:30.051","taskReportID":4560512847563664,"title":"This is a task"}   7815431572565715359
```

**Comment by cead22** [comment] 2023-10-05 22:00
I think I found the spot where we're adding this

**Comment by cead22** [comment] 2023-10-05 22:04
@s77rt just to confirm, we can label this as internal since there's nothing to be fixed on the front end, right?

**Comment by s77rt** [comment] 2023-10-05 23:44
@cead22 Yes!

**Comment by cead22** [comment] 2023-10-06 02:43
@MariaHCD it looks like you added childReportID for those actions as part of this PR https://github.com/Expensify/Auth/pull/8140. Can you look into this bug please?

**Comment by MariaHCD** [comment] 2023-10-06 16:19
I think my PR title for https://github.com/Expensify/Auth/pull/8140 is a bit misleading 😅  That PR didn't add any child details to the task report, it added the parent details for the task report. So when I wrote `child`, I meant the task report itself (which is the child of the parent chat report).

**Comment by MariaHCD** [comment] 2023-10-06 16:20
In any case, I think the `childReportID` is being returned in Report::GetChats specifically when building the report action list [here](https://github.com/Expensify/Auth/blob/741f6eecb1fd8f2bcbb623e48944fc4966b63f85/auth/lib/Report.cpp#L5579-L5580). I see it's being returned in the response of OpenReport:

<img width="969" alt="Screenshot 2023-10-06 at 8 11 02 PM" src="https://github.com/Expensify/App/assets/12268372/b60bfe95-4fda-4b4b-b594-3ab60ae7a225">

**Comment by MariaHCD** [comment] 2023-10-06 16:21
@cristipaval could you clarify if we meant to set the `childReportID` for task report actions? 

<img width="792" alt="Screenshot 2023-10-06 at 8 18 49 PM" src="https://github.com/Expensify/App/assets/12268372/0159044c-26ad-4c5c-890b-e2cad943c75b">

**Comment by MariaHCD** [comment] 2023-10-09 14:35
@cristipaval mentioned he'd take a look here today 🙏🏼

**Comment by cristipaval** [comment] 2023-10-10 12:16
This is not reproducible anymore. Could someone confirm?

Also, @MariaHCD, FWIW: the code that blames me was added last week, whereas this issue was opened three weeks ago. I just moved that logic that was the same in multiple places to a separate reusable function.

**Comment by s77rt** [comment] 2023-10-10 15:01
Still reproducible. I can still see the `childReportID` added to the `TASKREOPENED`/`TASKCOMPLETED` report actions.

<img width="1719" alt="Screenshot 2023-10-10 at 3 57 25 PM" src="https://github.com/Expensify/App/assets/16493223/2a64e269-67f3-495b-8160-82c1f047039c">

**Comment by MariaHCD** [comment] 2023-10-23 12:12
cc: @thienlnam if you have any context around why the `childReportID` is included in the TASKREOPENED / TASKCOMPLETED report actions: https://github.com/Expensify/App/issues/27884#issuecomment-1755639719

**Comment by thienlnam** [comment] 2023-10-23 18:13
That shouldn't be happening, the code that adds those reportActions doesn't include a childReportID
https://github.com/Expensify/Auth/blob/53aea0415eddf80a82db5283ace0162feba26a19/auth/lib/Report.cpp#L5828-L5845

I wonder if it's happening via the FE? Or if this is still reproducible with a new task report

**Comment by MariaHCD** [comment] 2023-10-25 14:37
Still seeing it on new task reports 🤔 

<img width="1714" alt="Screenshot 2023-10-25 at 6 35 06 PM" src="https://github.com/Expensify/App/assets/12268372/a5220d52-e8f0-4bce-b360-8bb1462eac61">

It seems to me that we're deliberately setting the childReportID to the task reportID [here](https://github.com/Expensify/Auth/blob/741f6eecb1fd8f2bcbb623e48944fc4966b63f85/auth/lib/Report.cpp#L5579-L5580)?

**Comment by thienlnam** [comment] 2023-10-25 21:56
Ahhh yes, so this was only meant to be added to the ADD_COMMENT reportActions not these other task actions. I can update it so that happens

Context: You can assign a task to an infinite number of people, and they might not have access to the parent report of the task so they get a reportAction in the DM between the owner and the assignee with a link to the task report. The childReportID is added to those to make sure they all link to the same task report.

**Comment by MariaHCD** [comment] 2023-10-30 07:35
Heads up, @s77rt, the backend fix was deployed to production. Can we retest? Thanks!

**Comment by s77rt** [comment] 2023-10-30 08:59
@MariaHCD It's fixed! 🚀

**Comment by MariaHCD** [comment] 2023-10-30 09:10
Nice, thanks! I don't think any payments are required or anything else is needed from engineering? So we should be good to close this one out.

**Closed by MariaHCD** 2023-10-30 09:10 UTC
Labels: Engineering, Daily, Internal, Bug
