### ISSUE TITLE
Search - selfDM is not shown in search

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#51471] opened 2024-10-25 14:19 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 9.0.54-0
**Reproducible in staging?:** Y
**Reproducible in production?:** N
**If this was caught on HybridApp, is this reproducible on New Expensify Standalone?:** Y
**If this was caught during regression testing, add the test name, ID and link from TestRail:** https://expensify.testrail.io/index.php?/tests/view/5131233
**Issue reported by:** Applause - Internal Team

## Action Performed:
1. Login with an applause email
2. Search for selfDM

## Expected Result:
SelfDM is shown in the search result

## Actual Result:
SelfDM is not shown in the search result for a private domain.

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Standalone
- [ ] Android: HybridApp
- [x] Android: mWeb Chrome
- [x] iOS: Standalone
- [x] iOS: HybridApp
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

<details>
  <summary>Add any screenshot/video evidence</summary>

  
</details> 

https://github.com/user-attachments/assets/d21b2e87-1852-4086-900a-098768df54bd

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by luacmartins** [comment] 2024-10-25 18:38
Left a comment on [this PR](https://github.com/Expensify/App/pull/51332#issuecomment-2438566013) that's potentially related

**Comment by hannojg** [comment] 2024-10-28 08:36
![Screenshot 2024-10-28 at 09 35 46](https://github.com/user-attachments/assets/2f2da866-0946-4cca-bbcc-555322d4c90b)

hm, will try to reproduce differently, but i can't seem to reproduce on dev:

![Screenshot 2024-10-28 at 09 35 46](https://github.com/user-attachments/assets/a39c9d66-528d-401d-b472-02d858419cf4)

**Comment by hannojg** [comment] 2024-10-28 08:39
hm no, i just can't reproduce it, neither on staging. I don't think this related to the mentioned PR

**Comment by Beamanator** [comment] 2024-10-28 15:12
I could find the selfDM in search if I type `(you)` so I wonder if we should call this NAB?

**Comment by luacmartins** [comment] 2024-10-28 18:02
I think this is a sorting priority issue. Try creating many chat reports (threads) that match the search term. In the example I posted in [Slack](https://expensify.slack.com/archives/C01GTK53T8Q/p1729884504372159?thread_ts=1729866015.909199&cid=C01GTK53T8Q), all the results seem to match the search input, but all the threads are prioritized above the "main" self-dm report

**Comment by Beamanator** [comment] 2024-10-29 08:07
Ooh now I can see it easily - I wonder if this was fixed by the revert that @luacmartins recommended [here](https://github.com/Expensify/App/issues/51471#issuecomment-2438567473)?

**Comment by Beamanator** [comment] 2024-10-29 08:27
as mentioned in slack [here](https://expensify.slack.com/archives/C01GTK53T8Q/p1730190416025389?thread_ts=1729866015.909199&cid=C01GTK53T8Q), this was fixed!

**Comment by stitesExpensify** [comment] 2024-10-29 23:04
I do not have time to dig on that with travel right now. I'm going to close since it is fixed

**Closed by stitesExpensify** 2024-10-29 23:04 UTC
Labels: Engineering, Hourly, Overdue
