### ISSUE TITLE
 IOU - The corrupted PDF is smartscanned

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#38846] opened 2024-03-22 22:05 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.56.0
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**If this was caught during regression testing, add the test name, ID and link from TestRail:** N/A
**Issue reported by:** Applause - Internal Team

**Issue found when executing PR** https://github.com/Expensify/App/pull/38397
## Action Performed:
1. Navigate to FAB - Request money - Scan
2. Upload a corrupted PDF
3. Click on the IOU

## Expected Result:
Smartscanning shouldn't begin.

## Actual Result:
The corrupted PDF is smartscanned

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details> 

https://github.com/Expensify/App/assets/78819774/7f4fbecd-be3e-41ef-96ee-f2ad95711f1e

[Corrupted PDF (1).pdf](https://github.com/Expensify/App/files/14729022/Corrupted.PDF.1.pdf)

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by lanitochka17** [comment] 2024-03-22 22:06
@alexpensify  FYI I haven't added the External label as I wasn't 100% sure about this issue. Please take a look and add the label if you agree it's a bug and can be handled by external contributors

**Comment by alexpensify** [comment] 2024-03-26 00:28
Ok, I'll add to my testing list

**Comment by alexpensify** [comment] 2024-03-27 19:49
No update yet

**Comment by alexpensify** [comment] 2024-03-29 16:51
Closing - this is a dupe of https://github.com/Expensify/App/issues/38845

**Closed by alexpensify** 2024-03-29 16:51 UTC
Labels: Daily, Bug
