### ISSUE TITLE
[HOLD for payment 2024-04-15] [$500] Self  - DM - App returns to previous conversation instead of self-DM after leaving self-DM thread

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#38689] opened 2024-03-20 17:05 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.55-0
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**If this was caught during regression testing, add the test name, ID and link from TestRail:** N/S
**Issue reported by:** Applause - Internal Team

## Action Performed:
1. Go to staging.new.expensify.com
2. Go to 1:1 DM
3. Send a message, reply in thread and leave thread
4. Note that user is redirected to 1:1 DM in Step 2
5. Click the Search icon in the LGN > type 'you' > start a self DM
6. Send a message, reply in thread and leave thread

## Expected Result:
After leaving thread, app will return to self-DM

## Actual Result:
After leaving thread, app returns to a previous conversation before self-DM

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [x] Android: mWeb Chrome
- [x] iOS: Native
- [x] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details> 

https://github.com/Expensify/App/assets/78819774/eddcef7c-8b6d-49cd-8f78-f286f583a87e

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~016b6d3e4e9cf9c054</li>
        <li>Upwork Job ID: 1770633111502032896</li>
        <li>Last Price Increase: 2024-03-21</li>
<li>Automatic offers: </li>
<ul>
<li>abzokhattab | Contributor | 0</li>
</ul></li>
    </ul>
</details>

**Comment by lanitochka17** [comment] 2024-03-20 17:06
We think that this bug might be related to #vip-vsp

**Comment by lanitochka17** [comment] 2024-03-20 17:06
@Christinadobrzyn  FYI I haven't added the External label as I wasn't 100% sure about this issue. Please take a look and add the label if you agree it's a bug and can be handled by external contributors

**Comment by nkdengineer** [comment] 2024-03-20 18:27
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
- Self - DM - App returns to previous conversation instead of self-DM after leaving self-DM thread
### What is the root cause of that problem?
- In [here](https://github.com/Expensify/App/blob/399077f6091ce5f559eb597fbcfeae47f1ba97bb/src/pages/home/HeaderView.tsx#L147), we allow user to leave in case of selfDM 's thread.
- And when leaving room, we do not include the selfDM in [here](https://github.com/Expensify/App/blob/873b8d0fb85bd4778c9264524d51cf8ca2dc2090/src/libs/actions/Report.ts#L2348), that leads to the bug.
### What changes do you think we should make in order to solve the problem?
- We should not allow user to leave the selftDM 's thread. We can do it by update [this](https://github.com/Expensify/App/blob/399077f6091ce5f559eb597fbcfeae47f1ba97bb/src/pages/home/HeaderView.tsx#L147) to:
```
    const outerMostReportID = last(getAllAncestorReportActionIDs(report).reportIDs)
    const isSelfDMThread = ReportUtils.isSelfDM(getReport(outerMostReportID))
    const canJoinOrLeave = !isSelfDMThread && !isSelfDM && (isChatThread || isUserCreatedPolicyRoom || canLeaveRoom);
```
### What alternative solutions did you explore? (Optional)
- NA

**Comment by Christinadobrzyn** [comment] 2024-03-21 02:06
I can recreate this based on the steps in the OP - I think this can be external and part of vip-vsb

**Comment by Christinadobrzyn** [comment] 2024-03-22 03:44
we have some proposals to review when you have a chance @Santhosh-Sellavel!

**Comment by Santhosh-Sellavel** [comment] 2024-03-25 17:53
@abzokhattab's [proposal](https://github.com/Expensify/App/issues/38689#issuecomment-2010145294) looks good and straight-forward!

C+ Reviewed
🎀 👀 🎀

**Comment by nkdengineer** [comment] 2024-03-25 17:55
@luacmartins @Santhosh-Sellavel  Should we hide the "Leave" option in case of selfDM?

**Comment by nkdengineer** [comment] 2024-03-25 18:21
Yeah, I mean that selfDM 's threads. Because, self DM is the spot for private notes, only current users can access it, and its thread as well. So I think the "leave" or "join" options in self-DM are redundant

**Comment by luacmartins** [comment] 2024-03-25 19:00
Yea, agreed that we should hide those buttons for selfDM threads too.

**Comment by thienlnam** [comment] 2024-03-26 01:10
Yeah that's correct - you can't invite anyone to the self-DM itself, but you are able to for child reports (tasks, chat reports, etc)

**Comment by nkdengineer** [comment] 2024-03-26 02:21
@thienlnam So what do you think about [comment](https://github.com/Expensify/App/issues/38689#issuecomment-2018699680)?

**Comment by luacmartins** [comment] 2024-03-26 02:57
Oh I didn't realize that. In that case, yes we should show the button for others to be able to leave the threads

**Comment by Christinadobrzyn** [comment] 2024-03-28 06:37
Just a heads up that I'm going to be ooo on Friday and Monday for Easter. I'll check in on this on Tuesday when I'm back.

**Comment by Santhosh-Sellavel** [comment] 2024-03-28 15:04
> @abzokhattab's [proposal](https://github.com/Expensify/App/issues/38689#issuecomment-2010145294) looks good and straight-forward!
> 
> C+ Reviewed 🎀 👀 🎀

@luacmartins Can we proceed here?

**Comment by luacmartins** [comment] 2024-04-01 16:22
@abzokhattab what's the ETA for the PR?

**Comment by abzokhattab** [comment] 2024-04-01 16:35
will be ready today thanks @luacmartins for the ping.

**Comment by abzokhattab** [comment] 2024-04-03 07:35
[The PR](https://github.com/Expensify/App/pull/39476) is ready. please have a look and let me know if you have any comments.

**Comment by Christinadobrzyn** [comment] 2024-04-08 06:11
PR is under review

**Comment by Christinadobrzyn** [comment] 2024-04-11 03:21
Payouts due:

- [ ] Contributor: $500 @abzokhattab (Upwork offer here - https://www.upwork.com/nx/wm/workroom/36815600/overview)
- [ ] Contributor+: $500 @Santhosh-Sellavel (in NewDot) 

Upwork job is [here](https://www.upwork.com/jobs/~016b6d3e4e9cf9c054).

@Santhosh-Sellavel do we need a regression test for this?

**Comment by Santhosh-Sellavel** [comment] 2024-04-17 16:38
**BugZero Checklist:** The PR fixing this issue has been merged! The following checklist ([instructions](https://stackoverflow.com/c/expensify/questions/14574)) will need to be completed before the issue can be closed:

* [x]  [@Santhosh-Sellavel] The PR that introduced the bug has been identified. Link to the PR: https://github.com/Expensify/App/pull/31097/files#r1569141794
* [x]  [@Santhosh-Sellavel] The offending PR has been commented on, pointing out the bug it caused and why, so the author and reviewers can learn from the mistake. Link to comment: https://github.com/Expensify/App/pull/31097/files#r1569141794
* [x]  [@Santhosh-Sellavel] A discussion in #expensify-bugs has been started about whether any other steps should be taken (e.g. updating the PR review checklist) in order to catch this type of bug sooner. Link to discussion: N/A Should have been caught based on the checklist
* [x]  [@Santhosh-Sellavel] Determine if we should create a regression test for this bug. N/A As this basic should be part of tests already we won't need a separate reg tests here
* [x]  [@Santhosh-Sellavel] If we decide to create a regression test for the bug, please propose the [regression test](https://github.com/Expensify/App/blob/main/contributingGuides/REGRESSION_TEST_BEST_PRACTICES.md) steps to ensure the same bug will not reach production again. N/A
* [ ]  [@Christinadobrzyn] Link the GH issue for creating/updating the regression test once above steps have been agreed upon:

**Comment by Christinadobrzyn** [comment] 2024-04-22 04:39
awesome! no regression test is needed. Closing this. Let me know if I missed anything. 

[Payment summary](https://github.com/Expensify/App/issues/38689#issuecomment-2048862877) here for @Santhosh-Sellavel payment through NewDot.

**Closed by Christinadobrzyn** 2024-04-22 04:39 UTC
Labels: External, Daily, Overdue, Awaiting Payment, Bug

**Comment by JmillsExpensify** [comment] 2024-05-31 04:30
$500 approved for @Santhosh-Sellavel
