### ISSUE TITLE
[$1500] Android - Text input in the compose box disappears/reappears erratically when typing a message immediately after launching the app  

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#28562] opened 2023-10-01 14:04 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. App must be killed (by OS or manually)
2. Receive chat message
3. Tap notification, app opens to message
4. Start typing
5. Some of the input is lost
6. Sometimes the lost input reappears _(variable report of this step happening or not)_

High traffic accounts are seeing the same problem without the need to start the flow from a notification with the App killed. The theory being that an account with less data in it requires the additional processing that occurs when opening the app from a notification. On a high traffic account the following steps can reproduce the same issue, so let's make sure the solution is tested on this case as well:

1. Switch to a chat with a lot of history
2. Start typing immediately
3. After a couple seconds, it will throw out the last second of typing (so if you typed "abcdefghijklmnop" it would revert back to "abcdef").
4. This is especially infuriating with voice recognition, as it just stops and throws it out.
5. The cursor is also often left in a strange place (eg, at the start of the text)
6. Sometimes it'll do this multiple times
7. Sometimes the missing part will reappear

## Expected Result:
Text input in the composer should not disappear/reappear erratically

## Actual Result:
Some of the text input in the composer is lost (and at times reappears)

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [ ] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 1.3.75.2
**Reproducible in staging?:** Y
**Reproducible in production?:** 
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/10736861/10832e8d-1484-46a4-9c26-9eef07c31712

**Expensify/Expensify Issue URL:**
**Issue reported by:** @quinthar
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1695961777795579

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~011231f7b639cb80f1</li>
        <li>Upwork Job ID: 1708842016088723456</li>
        <li>Last Price Increase: 2023-10-16</li>
    </ul>
</details>

**Comment by trjExpensify** [comment] 2023-10-02 13:07
Confirming a couple of things in the thread. Haven't been able to repro myself yet on Android using browserstack.

**Comment by Julesssss** [comment] 2023-10-02 13:21
I can reproduce on Android, but ONLY when the app is killed (by user or OS):

- App must be killed
- Receive chat message
- Tap notification, app opens to message
- I start typing
- Some of the input is lost -- it's removed even though it was previously shown


https://github.com/Expensify/App/assets/10736861/10832e8d-1484-46a4-9c26-9eef07c31712

_^ added to description_

**Comment by trjExpensify** [comment] 2023-10-02 13:50
Niceeee! So I think your repro sounds pretty consistent with DB's bug report. The one diff is that it's unclear if DB's doesn't reappear ever:

>sometimes when I go to chat I will type a message and then it will disappear, and then it might reappear later like a second later. This all happens inside the compose box, typically right after I open a chat It feels like the app is still trying to figure something out or do some kind of delayed rendering or something, and so if I open a chat and then immediately start writing a message, that message might act funny in the composed boxville clear and repopulate itself erratically.

I'm going to add that to the issue OP so it's captured, and move this on to be looked into `external`. Perhaps when we're ready with a PR we can provide a branch build to David to re-test.

**Comment by Julesssss** [comment] 2023-10-04 09:46
It might be possible that it occurs on iOS too. Not sure that anyone has tried to reproduce on iOS yet.

**Comment by trjExpensify** [comment] 2023-10-04 10:16
Yeah, feel free to try iOS as well. I wasn't able to repro myself, but Android device for sure is where the bug report is coming from.

**Comment by trjExpensify** [comment] 2023-10-06 19:23
@burczu are you interested in this one?

**Comment by burczu** [comment] 2023-10-09 06:57
Hey @trjExpensify! Sorry, I was focused on other issues... I think I'll ask on Slack if any other C+ would like to take this over from me, because I have quite a lot on me right now and I don't have access to Android device - even if this is reproducible on iOS too, I won't be able to test the solution on all the environments.

**Comment by burczu** [comment] 2023-10-09 07:01
@trjExpensify Please assign @allroundexperts instead of me - he is eager to work on this issue.

**Comment by trjExpensify** [comment] 2023-10-09 18:44
Indeed we are! It has been a week now, so upped the bounty to $1k!

**Comment by burczu** [comment] 2023-10-10 06:18
@trjExpensify Regarding this comment: https://github.com/Expensify/App/issues/28562#issuecomment-1752438815 plase assign @allroundexperts instead of me - he will take this over from me as C+. Thank you

**Comment by trjExpensify** [comment] 2023-10-10 18:38
>@trjExpensify Regarding this comment: https://github.com/Expensify/App/issues/28562#issuecomment-1752438815 plase assign @allroundexperts instead of me - he will take this over from me as C+. Thank you

Done!

**Comment by Julesssss** [comment] 2023-10-13 15:36
Awaiting proposals

**Comment by trjExpensify** [comment] 2023-10-16 17:01
Bumping the price on this again!

**Comment by mvtglobally** [comment] 2023-10-17 15:17
Issue not reproducible during KI retests. (First week)

**Comment by trjExpensify** [comment] 2023-10-18 21:32
Amazinnnng! Assigning you.

**Comment by quinthar** [comment] 2023-10-20 22:46
I can reproduce this reliably, if anybody needs me to do anything.

**Comment by arthurmfgtab** [comment] 2023-10-23 15:51
Thanks @trjExpensify , I just posted [here](https://callstack-hq.slack.com/archives/C05LX9D6E07/p1698076162737049?thread_ts=1697709370.156129&cid=C05LX9D6E07) that I'm struggling on getting push notifications on an emulator, not sure if any extra configuration is required for that

**Comment by Julesssss** [comment] 2023-10-24 07:48
Installing an AdHoc build onto an emulator, or physical device should make this easier

**Comment by Julesssss** [comment] 2023-10-30 08:54
Ignoring Melvin as this is not really an external issue anymore.

**Comment by trjExpensify** [comment] 2023-10-30 13:25
Right, we have the issue assigned to @arthurmfgtab from Callstack melv. On that note, @arthurmfgtab can you provide us with an update please?

**Comment by Julesssss** [comment] 2023-11-01 13:46
Bumping @arthurmfgtab for an update

**Comment by arthurmfgtab** [comment] 2023-11-06 09:33
Hey, I was able to replicate the issue and plan to open a PR today o/

**Comment by Julesssss** [comment] 2023-11-08 15:06
Hey @arthurmfgtab, did you manage to open the PR?

**Comment by trjExpensify** [comment] 2023-11-13 14:17
Bump @arthurmfgtab can you share PR here please?

**Comment by arthurmfgtab** [comment] 2023-11-14 10:25
Hey guys, sorry for the delay, I got catch up on another Android task
I just got back to it but failed to receive PNs on a real Android device :/. I'll reach out for help to get that done today!

**Comment by Julesssss** [comment] 2023-11-15 16:18
Discussion has moved to [Slack](https://expensify.slack.com/archives/C05LX9D6E07/p1700059002891709?thread_ts=1697709370.156129&cid=C05LX9D6E07)

**Comment by Julesssss** [comment] 2023-11-20 15:22
Hey @arthurmfgtab, any updates for this issue?

**Comment by arthurmfgtab** [comment] 2023-11-21 10:27
Posted an update [here](https://callstack-hq.slack.com/archives/C05LX9D6E07/p1700561722318379?thread_ts=1697709370.156129&cid=C05LX9D6E07)

**Comment by trjExpensify** [comment] 2023-11-27 10:58
Can we get to the bottom of this issue this week? 

From the discussion @Julesssss had these two suggestions to look into: 

>We should check the parent components to see exactly which props can trigger a refresh
>but if this can be proven to only occur on Android then maybe a callback from the native Android InputView behaves slightly differently to the other platforms and that’s whats causing the issue or second refresh

**Comment by trjExpensify** [comment] 2023-11-29 16:57
@muttmuure - let me know if there's a replacement for this lined up.

**Comment by rinej** [comment] 2023-11-30 11:44
Hello I am Tomasz Lesniakiewicz from Callstack - expert contributor group. I'd like to take it over this issue.

**Comment by Julesssss** [comment] 2023-11-30 11:52
Sounds good! Thanks

**Comment by rinej** [comment] 2023-12-01 15:06
Hello, I am adding some update on the issue:

- I could not reproduce the issue on both android real device and on emulator (attaching videos)
- I used [tomasz.lesniakiewicz@callstack.com](mailto:tomasz.lesniakiewicz@callstack.com) email - I used that form to make it high traffic - https://docs.google.com/forms/d/e/1FAIpQLScpiS0Mo-HA5xHPsvDow79yTsMBgF0wjuqc0K37lTK5fheB8Q/viewform

- I will continue investigating components <**ComposerWithSuggestions** /> and <**Composer**/> , it is the place where we update the input data, however it might be hard to investigate it without being able to reproduce the issue

- Also our performance team did a great job on the <**ComposerWithSuggestions** /> improvements, which should improve overall performance on the chat input, it might also fix the current issue 
    - here ->  https://github.com/Expensify/App/issues/26347 (it's already merged)
    - and here -> https://github.com/Expensify/App/pull/30168 (on going PR)
    


Video recordings:

https://github.com/Expensify/App/assets/2650904/6e522575-26a3-49c9-9754-6b310ec9e8e6

https://github.com/Expensify/App/assets/2650904/0f6719f0-d7c1-472e-ab95-6c79ea904380

**Comment by rinej** [comment] 2023-12-06 14:07
Hello @Julesssss @trjExpensify, could you confirm whether the issue still persists? If so, could you specify the device and account on which it occurs? 

I created two high-traffic users, generated a long chat thread with some attachments, and couldn't reproduce the issue🤔

I will continue the investigation, but your input would be very helpful. Thanks!

**Comment by rinej** [comment] 2023-12-07 14:31
Hello, I was able to simulate and reproduce the issue, here are some findings and potential solutions:

 ### Problem


https://github.com/Expensify/App/assets/2650904/cb0023f8-aafc-48e5-8276-de52b940192a



When user types fast in the input on the Report screen, some characters disappear from time to time (in the above example, I continuously entered the word "testing").

This was difficult to reproduce because it only occurs on Android and specifically on high-traffic accounts. However, we can reproduce the issue every time on Android  by modifying the code and changing the debouncing time to a very low value, such as 0 or 100 in the method in **ComposerWithSuggestions**:

```js
const debouncedSaveReportComment = useMemo(
        () =>
            _.debounce((selectedReportID, newComment) => {
                Report.saveReportComment(selectedReportID, newComment || '');
            }, 0), // HERE replaced 1000 to 0
        [],
    );
```

### What causes the issue?

In the **SilentCommentUpdater** component, we have a hook that calls the updateComment when a comment from Onyx and the comment from the input are different:

```js
useEffect(() => {
  // Value state does not have the same value as comment props when the comment gets changed from another tab.
  // In this case, we should synchronize the value between tabs.
  const shouldSyncComment = prevCommentProp !== comment && value !== comment

  // As the report IDs change, make sure to update the composer comment as we need to make sure
  // we do not show incorrect data in there (ie. draft of message from other report).
  if (preferredLocale === prevPreferredLocale && report.reportID === prevReportId && !shouldSyncComment) {
      return;
  }

  updateComment(comment);
}, [prevCommentProp, prevPreferredLocale, prevReportId, comment, preferredLocale, report.reportID, updateComment, value, commentRef]);
```

According to comments in the codebase , it is necessary to synchronize comment drafts on different tabs in the browser.

When the debounce on **SaveReportAction** is too low, there is a misalignment, and the comment in Onyx is different from the value in the input. Then the above method is called, and the value from current input is replaced with the comment from Onyx.

### Solutions

1. We can increase the debounce time in **debouncedSaveReportComment**, for example, from 1000 to 3000 – this should help, although we will never be sure if the bug won't return on weaker devices.
2. We can remove the entire debounce in the **Report.saveReportComment** – this also fixes the issue, although I’m not sure if it will affect performance in other cases.
3. In the **SilentCommentUpdater** component, we can add a check to perform the verification only when it is on the web ( assuming the tabs synchronization is not necessary on mobiles)

```js
const shouldSyncComment = isWeb && prevCommentProp !== comment && value !== comment
```

**Comment by allroundexperts** [comment] 2023-12-10 19:40
@rinej Thanks for your in depth explanation. It makes a lot of sense now. Here are my thoughts regarding your proposed solution:
1. I think increasing the time would just be a workaround where we'll be hiding the issue instead of fixing it.
2. Removing it completely would hit performance. I'm not too inclined towards doing that.
3. I think that the third option is the most viable here. Let's simply not add code to native which won't be used. Problem solved.

Let me know if you agree @Julesssss @trjExpensify. If so, we can proceed to a PR!

**Comment by Julesssss** [comment] 2023-12-11 09:45
Amazing, thanks for the detailed explanation!

I agree that three is the best option.

**Comment by rinej** [comment] 2023-12-11 11:54
@Julesssss @allroundexperts thanks for the feedback!

@aimane-chnaif I was able to reproduce it on device and emulator only by lowering the debounce duration in the code

```js
const debouncedSaveReportComment = useMemo(
        () =>
            _.debounce((selectedReportID, newComment) => {
                Report.saveReportComment(selectedReportID, newComment || '');
            }, 0), // HERE replaced 1000 to 0
        [],
    );
```

I know it is not perfect for QA because it requires code changes; however, I wasn't able to reproduce it on a device or emulator without simulating it by removing some optimization techniques

**Comment by Julesssss** [comment] 2023-12-11 12:08
Lets move forward with a PR. Does anyone dissagree?

Once the PR is raised I'll build an AdHoc APK for @quinthar to test out 🤞

**Comment by rinej** [comment] 2023-12-11 14:09
@Julesssss here is the draft PR with the proposed solution:
https://github.com/Expensify/App/pull/32799

Are you able to create APK based on that PR? If yes please let me know how the testing went :)

**Comment by Julesssss** [comment] 2023-12-11 15:17
@rinej yep I just started the [build](https://github.com/Expensify/App/actions/runs/7169505983).

**Comment by Julesssss** [comment] 2023-12-11 16:27
I asked @quinthar to give the AdHoc build a test, lets see how it goes🤞

**Comment by rinej** [comment] 2023-12-12 13:53
@Julesssss thanks! @quinthar please let us know after you test it 🤞

**Comment by quinthar** [comment] 2023-12-15 22:08
I haven't tested it yet, but I actually haven't been experiencing it much on the current staging release either.  Performance on Android has *massively* improved, and it seems like some kind of performance related race condition.  So I'm trying to first reproduce it on the "control" version before testing the ad hoc build -- but I'm having trouble seeing it on the control (which is amazing!)

So for this change, is it a good change either way?  Does it have any negative side effects?  If you think this change is a good one with no negative side effects, then I think we should just ship it anyway, even if it's "merely" more defensive.

**Comment by Julesssss** [comment] 2023-12-18 09:22
David said he hasn't been experiencing this lately, which is good news. Perhaps other perf improvements have resolved this separately. 

Regardless, let's move forward with this further perf improvement PR.

**Comment by rinej** [comment] 2023-12-18 14:26
Great to hear that! Recently there were many performance improvements :) 

I will prepare the PR for review!

**Comment by muttmuure** [comment] 2024-01-10 20:55
@trjExpensify I think we need to pay @allroundexperts for this one and then we can close it?

**Comment by allroundexperts** [comment] 2024-01-10 20:57
That's correct. Can you write a payment summary and close this?

**Comment by trjExpensify** [comment] 2024-01-10 22:55
Ah, the automation didn't run. But it only [hit prod two days ago](https://github.com/Expensify/App/pull/32799#issuecomment-1882428928), so we've still got 5 days of the regression period to wait out no?

In the meantime, what did we learn from this and what can we do to minimise a regression here again? Is there any guidance we can provide based on the RCA for future development to help? Thanks!

**Comment by trjExpensify** [comment] 2024-01-17 18:27
Bump on the Q above!

**Comment by allroundexperts** [comment] 2024-01-21 23:10
@trjExpensify I think the main take away here is to be more mindful about adding code that won't necessarily be useful on other platforms. I think this was too edgy of a case to create a general guideline upon. This was also very difficult to test, so a regression test doesn't make sense either.

**Comment by Julesssss** [comment] 2024-01-22 09:07
Yeah I agree with @allroundexperts. This was hard to reproduce, even with high traffic accounts.

**Comment by trjExpensify** [comment] 2024-01-23 10:52
>I think the main take away here is to be more mindful about adding code that won't necessarily be useful on other platforms.

Do we surface this anywhere in like the Style.md or PR checklist? Increasing the visibility of avoiding platform specific deviations seems like it's worthwhile if not!

**Comment by allroundexperts** [comment] 2024-01-29 00:29
> Do we surface this anywhere in like the Style.md or PR checklist? Increasing the visibility of avoiding platform specific deviations seems like it's worthwhile if not!

I'm not sure if those contain this already. If not, then I think it won't hurt adding this.

**Comment by allroundexperts** [comment] 2024-01-30 22:39
@trjExpensify @Julesssss Can we please have a payment summary here?

**Comment by trjExpensify** [comment] 2024-01-30 22:46
Okay cool, I see we have this in the [PR review guidelines](https://github.com/Expensify/App/blob/main/contributingGuides/PR_REVIEW_GUIDELINES.md#code-patterns-to-improve) so we do surface this!

>Platform-specific solutions should not be applied to more platforms than necessary

Payment summary: 

- $1,500 to @allroundexperts for the C+ review 
- @rinej's payment will be handled elsewhere. 

With that, closing it out!

**Closed by trjExpensify** 2024-01-30 22:46 UTC
Labels: Reviewing, Engineering, Monthly, Internal, Bug

**Comment by JmillsExpensify** [comment] 2024-01-30 23:15
$1,500 approved for @allroundexperts based on summary above.
