### ISSUE TITLE
[$500] Search - The money sender account is not displayed in Search list

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#34753] opened 2024-01-18 18:56 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.27-0
**Reproducible in staging?:** Y 
**Reproducible in production?:** Y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** Applause - Internal Team
**Slack conversation:**

## Action Performed:
1. Login as User A
2. Navigate to any conversation
3. Request money from user B
4. User B opens Search

## Expected Result:
he money sender account should be displayed in Search list

## Actual Result:
The money sender account is not displayed in Search list

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [x] Android: mWeb Chrome
- [x] iOS: Native
- [x] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details> 

https://github.com/Expensify/App/assets/78819774/21bcbccd-13c9-4524-9279-5ab80cef1dbc

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01729475796b42e2bc</li>
        <li>Upwork Job ID: 1748056809109458944</li>
        <li>Last Price Increase: 2024-01-25</li>
    </ul>
</details>

**Comment by lanitochka17** [comment] 2024-01-18 18:57
[#vip-vsb](https://expensify.enterprise.slack.com/archives/C066HJM2CAZ)

**Comment by bernhardoj** [comment] 2024-01-19 09:58
This is easily reproducible when starting a new chat.

When starting a new chat, BE returns an empty `visibleChatMemberAccountIDs`,
https://github.com/Expensify/App/blob/2a03320a054f0d9a28cffc1ee96fdde78700218a/src/libs/OptionsListUtils.js#L1401

and because it's always empty, the title is empty.
https://github.com/Expensify/App/blob/2a03320a054f0d9a28cffc1ee96fdde78700218a/src/libs/OptionsListUtils.js#L491-L492
https://github.com/Expensify/App/blob/2a03320a054f0d9a28cffc1ee96fdde78700218a/src/components/OptionRow.tsx#L150

_we previously used `participantAccountIDs` before gets migrated [here](https://github.com/Expensify/App/pull/30863)_

**Comment by stephanieelliott** [comment] 2024-01-23 03:34
Thanks @bernhardoj -- do you have a proposal for fixing it 🙏😀

**Comment by bernhardoj** [comment] 2024-01-23 03:38
@stephanieelliott I think it should be fixed on the BE

**Comment by Santhosh-Sellavel** [comment] 2024-01-25 18:06
@stephanieelliott can you add internal please?

**Comment by stephanieelliott** [comment] 2024-01-25 20:24
Adjusted labels!

**Comment by Santhosh-Sellavel** [comment] 2024-01-27 17:08
I'm unavailable next week, Please assign a new C+ Issue here if required while I am away, thanks!

cc: @stephanieelliott

**Comment by mvtglobally** [comment] 2024-01-30 04:59
Issue not reproducible during KI retests. (First week)

**Comment by stephanieelliott** [comment] 2024-01-31 22:43
Oh, I'm not able to repro this either. Seems like it was either temporary or was fixed.

**Closed by stephanieelliott** 2024-01-31 22:43 UTC
Labels: Daily, Internal, Help Wanted, Overdue, Bug, retest-weekly
