### ISSUE TITLE
[HOLD for payment 2022-08-01] [$250] Web - New Room - Drop down is opened again after use the Enter Key to create a new room

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#9741] opened 2022-07-06 14:05 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/docs/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Go to staging.new.expensify.com
2. Log in with expensifail account
3. Click on Fub menu - New Room
4. Type any room and use Enter Key
5. Select any Workspace and use Enter Key
6. Select any Visibility option and use Enter Key

## Expected Result:
Drop down should not open again after use Enter Key

## Actual Result:
 Drop down is opened again after use the Enter Key to create a new room

## Workaround:
Unknown

## Platform:

Where is this issue occurring?

- Web
- iOS
- Android
- Desktop App
- Mobile Web

**Version Number:** 1.1.79.17

**Reproducible in staging?:** Yes

**Reproducible in production?:** Yes

**Email or phone of affected tester (no customers):** any expensifail account

**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Notes/Photos/Videos:** Any additional supporting documentation

https://user-images.githubusercontent.com/93399543/177569162-20fc1535-a758-418c-98e0-95f3eb62c59d.mp4

**Expensify/Expensify Issue URL:** 

**Issue reported by:** Applause - Internal Team

**Slack conversation:** 

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by MariaHCD** [comment] 2022-07-07 13:10
Unable to reproduce on staging or on local on a mac:

https://user-images.githubusercontent.com/12268372/177779089-c4fc4e40-926a-43b8-916e-f9b28b862f7c.mp4

But I am able to reproduce the issue on a windows device.

**Comment by MitchExpensify** [comment] 2022-07-07 22:23
[Upwork Job](https://www.upwork.com/jobs/~0185ef423c729acb49)

**Comment by eVoloshchak** [comment] 2022-07-08 18:19
**Proposal:**
When user presses `Enter` (when [this](https://github.com/Expensify/App/blob/0fcc4920dbc0e0b7658e80541367acf8a2e4ff57/src/components/Button.js#L158) listener fires), we need to call `event.preventDefault()` so the browser will not handle this event and dropdown will stay closed
```diff
this.unsubscribe = KeyboardShortcut.subscribe(shortcutConfig.shortcutKey, (e) => {
    if (!this.props.isFocused || this.props.isDisabled || this.props.isLoading || (e && e.target.nodeName === 'TEXTAREA')) {
        return;
    }
+   e.preventDefault();
    this.props.onPress();
}, shortcutConfig.descriptionKey, shortcutConfig.modifiers, true, false, this.props.enterKeyEventListenerPriority, false);
```

Before:

https://user-images.githubusercontent.com/9059945/178048452-c221df2d-d62d-418e-9b6d-f01dac054079.mp4

After:

https://user-images.githubusercontent.com/9059945/178048508-08b773e7-1a4a-4e5d-a710-7e6e54ee875e.mp4

**Comment by mananjadhav** [comment] 2022-07-15 22:46
I tested this on Desktop. I am not able to reproduce this on Mac, but once on Windows. @eVoloshchak's proposal looks good. 

🎀 👀 🎀 C+ reviewed

cc - @marcochavezf

**Comment by mvtglobally** [comment] 2022-07-26 03:56
Issue not reproducible during KI retests. (First week)

**Comment by MitchExpensify** [comment] 2022-07-26 21:42
Reminder to pay on August 1st assuming no regressions

**Comment by mvtglobally** [comment] 2022-08-02 04:01
Issue not reproducible during KI retests. (Second week)

**Comment by MitchExpensify** [comment] 2022-08-02 15:40
Paid @eVoloshchak, just waiting on @mananjadhav to accept the offer to process C+ payment then we'll close this out

**Comment by mananjadhav** [comment] 2022-08-02 16:49
> just waiting on @mananjadhav to accept the offer 

Done @MitchExpensify

**Comment by MitchExpensify** [comment] 2022-08-03 09:25
Paid and contracts ended, thanks everyone!

**Closed by MitchExpensify** 2022-08-03 09:25 UTC
Labels: Exported, External, Engineering, Weekly, Awaiting Payment
