### ISSUE TITLE
[HOLD for payment 2023-01-30] Text on Button "I'll settle up elsewhere" on Send Money page not changing to new selected language

### ISSUE THREAD

**Issue by kavimuru** [Expensify/App#14305] opened 2023-01-13 22:14 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:

1. Go to Send Money page
2. Observe text on Button "I'll settle up elsewhere"
3. Change language in another session
4. Observe the button text

This is also happening for Request Money and Split Bill.

## Expected Result:
Button Text should be changed to new selected language

## Actual Result:
Button Text is not changing to new selected language

## Workaround:
unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?

- [ ] MacOS / Chrome / Safari

**Version Number:** 1.2.54-2
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** 

https://user-images.githubusercontent.com/43996225/212429014-862904b1-c29e-44e0-bbdc-a9e4cdec0fa8.mp4

https://user-images.githubusercontent.com/43996225/212429046-05af733e-bf16-415e-8449-51d4cbc2e5f1.mov

**Expensify/Expensify Issue URL:**
**Issue reported by:** @varshamb 
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1673625563488099

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~0178704fa9566b2264</li>
        <li>Upwork Job ID: 1615134087607455744</li>
        <li>Last Price Increase: 2023-01-16</li>
    </ul>
</details>

**Comment by mateocole** [comment] 2023-01-16 14:28
Going to have an engineer confirm we can make an upwork job for this

**Comment by luacmartins** [comment] 2023-01-20 21:32
PR in staging

**Comment by luacmartins** [comment] 2023-01-25 02:32
PR hit prod yesterday!

**Comment by mateocole** [comment] 2023-02-01 01:16
Alright, for payment, can apply here: https://www.upwork.com/jobs/~0178704fa9566b2264

**Comment by varshamb** [comment] 2023-02-01 03:39
@mateocole Offere for reporting?

**Comment by mateocole** [comment] 2023-02-02 12:15
@varshamb yes, can you apply on the upwork job

**Comment by varshamb** [comment] 2023-02-02 16:20
@mateocole I didn't find upwork job to apply.

**Comment by varshamb** [comment] 2023-02-05 07:30
> @varshamb yes, can you apply on the upwork job

@mateocole No offere recieved on Upwork yet.

**Comment by luacmartins** [comment] 2023-02-08 16:01
It seems like we are still waiting on payments here

**Comment by mateocole** [comment] 2023-02-09 16:21
Alright apologies, @Santhosh-Sellavel has been paid, @varshamb try here: https://www.upwork.com/jobs/~0178704fa9566b2264

**Comment by varshamb** [comment] 2023-02-10 01:52
> Alright apologies, @Santhosh-Sellavel has been paid, @varshamb try here: https://www.upwork.com/jobs/~0178704fa9566b2264

@mateocole Applied!

**Comment by varshamb** [comment] 2023-02-10 02:24
@mateocole the offer you shared is for 1000$, I am eligible for reporting bonus only!

**Comment by mallenexpensify** [comment] 2023-02-11 00:07
Thanks @varshamb , I updated the job and hired you for $250. can you please accept the job and reply here once you have?

**Comment by varshamb** [comment] 2023-02-11 01:32
@mallenexpensify Offer accepted. Thanks .

**Comment by mallenexpensify** [comment] 2023-02-13 23:49
Paid @varshamb $250, thanks for reporting! 
@Santhosh-Sellavel , can you please complete the top four below?  

BugZero Checklist: The PR fixing this issue has been merged! The following checklist ([instructions](https://stackoverflow.com/c/expensify/questions/14574)) will need to be completed before the issue can be closed:

- [ ] The PR that introduced the bug has been identified. Link to the PR:
- [ ] The offending PR has been commented on, pointing out the bug it caused and why, so the author and reviewers can learn from the mistake. Link to comment:
- [ ] A discussion in #expensify-bugs has been started about whether any other steps should be taken (e.g. updating the PR review checklist) in order to catch this type of bug sooner. Link to discussion:
- [ ] Propose [regression test](https://github.com/Expensify/App/blob/main/contributingGuides/REGRESSION_TEST_BEST_PRACTICES.md) steps to ensure the same bug will not reach production again.
- [ ] A [regression test](https://expensify.testrail.io/index.php?/dashboard) has been added or updated so that the same bug will not reach production again. Link to the GH issue for creating the test here:

**Comment by Santhosh-Sellavel** [comment] 2023-02-14 00:48
Regression Steps

Bug: The button text "I'll settle up elsewhere" is not translated on send money confirmation page.

Proposed Test Steps:
1. Open the App on 2 devices logged in to the same account
2. In device A, navigate to + > Send money > Enter Amount > Select participant`
3. Note the text of the confirmation button
4. In device B, navigate to Settings > Preferences and change the selected language
5. In device A, verify that the confirmation button was translated accordingly
6. In device A, select a different option in the dropdown button and repeat steps 4-5

**Comment by Santhosh-Sellavel** [comment] 2023-02-14 00:55
@luacmartins 
I believe this is the PR https://github.com/Expensify/App/pull/6651 can you please check off the next two?

**Comment by luacmartins** [comment] 2023-02-14 12:54
I actually think [this is the one](https://github.com/Expensify/App/pull/3866), since it introduced both `defaultButtonOption` in the constructor that was later refactored in the PR you linked above and storing the text in state.

**Comment by luacmartins** [comment] 2023-02-14 13:04
>Propose [regression test](https://github.com/Expensify/App/blob/main/contributingGuides/REGRESSION_TEST_BEST_PRACTICES.md) steps to ensure the same bug will not reach production again.
I don't think that we are adding regression tests for translations at this point. So I don't think we need to do anything for this. Let me know if that's not the case and I can write test steps.

**Comment by luacmartins** [comment] 2023-02-14 13:04
@mallenexpensify BZ checklist is completed!

**Comment by Santhosh-Sellavel** [comment] 2023-02-14 22:01
@luacmartins Yes, that has precedence. Thanks for sorting it out here!

**Comment by mallenexpensify** [comment] 2023-02-15 20:11
Thanks @Santhosh-Sellavel and @luacmartins .   
 
> Bug: The button text "I'll settle up elsewhere" is not translated on send money confirmation page.

I'm on the fence between adding details to a test case in TestRail or to the testing guidelines.  The reason to add to the guidelines would be if languages should update in all instances on the app and not just this one.  

Checking on in #qa
https://expensify.slack.com/archives/C9YU7BX5M/p1676491850603969

**Comment by mallenexpensify** [comment] 2023-02-15 22:55
We're not creating test cases for language related issues now so I created a [section in the Testing Guideline docs ](https://docs.google.com/document/d/1UaWlcieiwLnsKfeKw7iwLF7vgYRmdw_-K8OcY5aPBRU/edit)for `Language - Spanish`

**Closed by mallenexpensify** 2023-02-15 22:55 UTC
Labels: Reviewing, Engineering, Daily, Internal, Bug
