### ISSUE TITLE
[HOLD for payment 2024-08-01] Thread – Join button reappears in header when try to join thread after leave it

### ISSUE THREAD

**Issue by m-natarajan** [Expensify/App#45828] opened 2024-07-20 13:46 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:**  v9.0.10-2
**Reproducible in staging?:** yes
**Reproducible in production?:** no, new feature
**If this was caught during regression testing, add the test name, ID and link from TestRail:** https://expensify.testrail.io/index.php?/tests/view/4747620
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** Applause Internal Team
**Slack conversation:**

## Action Performed:
1. Go to https://staging.new.expensify.com/
2. Log in
3. Open chat with user B
4. Send a message
5. Right click and select Reply in thread
6. Send a comment in the thread
7. Click on header
8. Click on Leave thread
9. Click on Join thread button on the header

## Expected Result:
Join button disappears, user joined to thread

## Actual Result:
Join button reappears, user is not joined to thread

## Workaround:
unknown
## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [x] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

https://github.com/user-attachments/assets/d471df36-419e-48e7-b30e-fc226f6bbbf2

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Issue Owner</summary>Current Issue Owner: @CortneyOfstad</details>

**Comment by mountiny** [comment] 2024-07-22 11:56
@bernhardoj @akinwale Seems like this might be related to https://github.com/Expensify/App/pull/45136 maybe we should revert the PR  and cover these newly found edge cases

**Comment by francoisl** [comment] 2024-07-22 16:20
Confirmed that it comes from https://github.com/Expensify/App/pull/45370/ as suggested [here](https://github.com/Expensify/App/pull/45136#issuecomment-2241983263) by reverting it locally.

/cc  @dominictb @thesahindia if you can think of a fix. In the meantime I'll prepare a revert CP just in case.

**Comment by CortneyOfstad** [comment] 2024-07-31 13:49
No payment is needed as this was internal and a C+ was not assigned due to comment [here](https://github.com/Expensify/App/pull/45921#issuecomment-2243549151). Closing!

**Closed by CortneyOfstad** 2024-07-31 13:49 UTC
Labels: Engineering, Weekly, Awaiting Payment, Bug
