### ISSUE TITLE
[HOLD for payment 2024-01-22] HIGH: (Comment linking: step 1) 'maintainVisibleContentPosition' doesn't works with the large list

### ISSUE THREAD

**Issue by perunt** [Expensify/App#32634] opened 2023-12-07 08:19 UTC
**Version Number:**
**Reproducible in staging?:**
**Reproducible in production?:**
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:**
**Slack conversation:**

## Action Performed:
Case 1 (correct)
1. Create a list with the 50 elements. You can use Report Actions for items
2. Set to FlatList:
```
maintainVisibleContentPosition={{
            minIndexForVisible: 0,
        }}
```

3. Using `onStartReached` add 50 items

---------------------------------------------
Case 2 (wrong)
1. Create a list with the 50 elements. You can use Report Actions for items
2. Set to FlatList:
```
maintainVisibleContentPosition={{
            minIndexForVisible: 0,
        }}
``` 
3. Using `onStartReached` add 100 items

## Expected Result:
In the both cases, you won't see any changes after adding new items, so the reportActions don't move in the viewport

## Actual Result:

1. In the first case, you won't see any changes after adding new items, so the reportActions don't move in the viewport
2. In the second case, you would see slides after adding new elements to FlatList. 

## Workaround:
Can the user still use Expensify without this being fixed? Have you informed them of the workaround?

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [x] Android: mWeb Chrome
- [x] iOS: Native
- [x] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

EXPO snack: https://snack.expo.dev/@tarasperun/add-items-onsatartreached

https://github.com/Expensify/App/assets/48593211/76c9f2f0-f1eb-4fd9-9895-d7526ce7b8a1

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by perunt** [comment] 2023-12-07 09:02
@roryabraham mentioned you to be aware of this bug, which we are currently tackling

**Comment by janicduplessis** [comment] 2023-12-07 23:10
Update: found the problem, opened a PR to fix upstream, will patch in Expensify app next and verify the fix. https://github.com/facebook/react-native/pull/41846

**Comment by isabelastisser** [comment] 2023-12-08 18:09
@roryabraham @perunt is there anything urgent I need to do here?

**Comment by roryabraham** [comment] 2023-12-09 23:08
Nothing for you to work on for now @isabelastisser – I'll let you know if any payments need to be issued

**Comment by roryabraham** [comment] 2023-12-12 18:45
Looks like the upstream PR has been merged and is included in 0.73-stable just about 15 minutes ago, but has not yet been included in a release. We are [working separately to upgrade to RN 0.73](https://github.com/Expensify/App/pull/31558), so may need to include this commit as a patch unless a new upstream release is created before we merge that 0.73 upgrade

**Comment by perunt** [comment] 2023-12-13 09:41
We have a PR for this at https://github.com/Expensify/App/pull/32843. We need to test it on the web as well, and then we can merge it.

**Comment by isabelastisser** [comment] 2023-12-15 18:03
Not overdue. Testing PR.

**Comment by isabelastisser** [comment] 2023-12-18 17:46
Any updates here?

**Comment by perunt** [comment] 2023-12-21 14:35
It was reviewed and approved

**Comment by roryabraham** [comment] 2023-12-24 00:48
There was some activity from reviewers in the PR: https://github.com/Expensify/App/pull/32843#issuecomment-1867910424

**Comment by situchan** [comment] 2024-01-23 19:51
I may take responsible for BZ Checklist since I reviewed [PR](https://github.com/Expensify/App/pull/32843)

I think we can skip checklist here.
No regression. The bug was in upstream. Not able to catch in E/App until comment linking is live.

**Comment by isabelastisser** [comment] 2024-01-23 19:52
Thanks @situchan !

**Comment by situchan** [comment] 2024-01-23 19:52
@isabelastisser I am eligible for payment though not assigned here

**Closed** 2024-01-23 19:52 UTC
Labels: Daily, Awaiting Payment, Bug

**Comment by isabelastisser** [comment] 2024-01-23 19:54
To confirm, you acted as the C+ and the payment should be $500 in Upwork? @situchan

**Comment by situchan** [comment] 2024-01-23 19:55
yes

**Comment by isabelastisser** [comment] 2024-01-23 20:06
Payment summary:

@situchan C+. [PR review. ](https://github.com/Expensify/App/pull/32843) Upwork job link [here.](https://www.upwork.com/nx/wm/offer/100587126)
