### ISSUE TITLE
Android - Composer - Expand button does not appear when reopening chat with long draft

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#47224] opened 2024-08-12 12:15 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 9.0.19-0
**Reproducible in staging?:** Y
**Reproducible in production?:** N
**If this was caught during regression testing, add the test name, ID and link from TestRail:** N/A
**Email or phone of affected tester (no customers):** applausetester+kh050806@applause.expensifail.com
**Issue reported by:** Applause - Internal Team

## Action Performed:
1. Launch New Expensify app
2. Go to chat
3. Enter text long enough until expand button appears
4. Return to LHN
5. Open the chat in Step 3

## Expected Result:
Expand button will appear next to the composer

## Actual Result:
Expand button does not appear next to the composer until anything is typed in the composer

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [ ] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details> 

https://github.com/user-attachments/assets/cb43bf60-2218-44db-b164-5e887258cc1c

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by rlinoz** [comment] 2024-08-12 13:17
Not a backend issue.

**Comment by rlinoz** [comment] 2024-08-12 13:24
I think this is related to https://github.com/Expensify/App/pull/46796, but I don't think it is worth blocking on this.

**Comment by rlinoz** [comment] 2024-08-12 13:32
Removing the deploy blocker label because this is an edge case and typing in the composer shows up the expand button again.

**Comment by hannojg** [comment] 2024-08-14 08:50
Okay, will work on a fix today!

**Comment by hannojg** [comment] 2024-08-14 10:05
@kirillzyusko is helping with this ticket!

**Comment by kirillzyusko** [comment] 2024-08-14 12:02
Yep, feel free to assign it to me!

**Comment by kirillzyusko** [comment] 2024-08-29 16:44
I prepared a fix https://github.com/Expensify/App/pull/47449

But since we updated RN to the latest version (0.75) earlier - this bug is not reproducible anymore:

https://github.com/user-attachments/assets/6c35dd38-4356-493e-89d0-233afb558b3c

@rlinoz @hannojg @lanitochka17 what are the next steps then? Should we re-test this issue on latest `main` and if it's not reproducible, then close the issue and close the PR?

**Comment by hannojg** [comment] 2024-09-04 07:46
> Should we re-test this issue on latest main and if it's not reproducible, then close the issue and close the PR?

Yes, that sounds right!

**Comment by rlinoz** [comment] 2024-09-09 18:00
Yep, just tested it in the latest app version and it works fine, let's close this one.

**Closed** 2024-09-09 18:02 UTC
Labels: Reviewing, Engineering, Weekly
