### ISSUE TITLE
[HOLD for payment 2022-09-07] [$250] Android/iOS - "Connect to bank" transition is not smooth and can see previous details reported by @thesahindia 

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#8541] opened 2022-04-07 16:54 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
Pre-Condition: Have a workspace created
1. Open the New Expensify app on iOS
2. Sign into an applause.expensify.com account
3. Tap on the "Profile" icon
4. Tap on the workspace
5. Tap on any tab that has "Connect to bank" (For example: Issue cards, reimburse expenses, etc)
6. Tap on "Connect bank account"

## Expected Result:
The user expects a smooth transition when tapping on "Connect bank account"

## Actual Result:
When tapping on this link, the transaction shows momentarily information from the previous page

## Workaround:
Unknown

## Platform:

Where is this issue occurring?

- iOS
- Android

**Version Number:** 1.1.52.0

**Reproducible in staging?:** Yes

**Reproducible in production?:** Yes

**Email or phone of affected tester (no customers):** n/a

**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Notes/Photos/Videos:** Any additional supporting documentation

https://user-images.githubusercontent.com/93399543/162256390-0b11be38-31d2-4024-aee4-ba4d57de1d35.mp4

**Expensify/Expensify Issue URL:** 

**Issue reported by:** Applause / @thesahindia 

**Slack conversation:** https://expensify.slack.com/archives/C01GTK53T8Q/p1649070836326089

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by thesahindia** [comment] 2022-04-07 18:50
Is this eligible for the reporting bonus as I had reported it on [slack](https://expensify.slack.com/archives/C01GTK53T8Q/p1649070836326089)

Also here's a slowed down video -

https://user-images.githubusercontent.com/83179295/162275250-2d24b696-c829-4f0c-9ff3-5a7bf8472a8f.mp4

**Comment by laurenreidexpensify** [comment] 2022-04-08 11:56
https://www.upwork.com/jobs/~0152eb6f4ed4ed19c4

**Comment by laurenreidexpensify** [comment] 2022-04-08 11:58
ugh the autoassigners were being janky! apols all. I am OOO next week and was reassigning a Contributor Manager Team sub (Jeremy) to look out for proposals next week while I am out.

**Comment by dharmik** [comment] 2022-04-13 14:39
@parasharrajat   @jboniface @iwiznia 

Proposal:

FileName: `WorkspaceInitialPage.js`

Solution: Example: Page0 ==> Page1 ==> Page2
Cause: From Page0 to refirect to Page1 and check conditions and move to Page2 this cause transition issue so we can check that condition in Page0 it self.

```diff
+ import lodashGet from 'lodash/get';
+ import BankAccount from '../../libs/models/BankAccount';                 
```

```diff
+  this.getShouldShowPage = this.getShouldShowPage.bind(this);
    this.state = {
        isDeleteModalOpen: false,
    };
```

```diff
+    getShouldShowPage() {
+       const state = lodashGet(this.props.reimbursementAccount, 'achData.state');
+        return lodashGet(this.props.reimbursementAccount, 'achData.bankAccountID') && state !== +BankAccount.STATE.OPEN;
+    }                 
```

```diff
-                action: () => Navigation.navigate(ROUTES.getWorkspaceBankAccountRoute(policy.id)),
+                action: () => {
+                    if(this.getShouldShowPage()){
+                        Navigation.navigate(ROUTES.getWorkspaceBankAccountRoute(policy.id))
+                    } else {
+                        Navigation.navigate(ROUTES.getBankAccountRoute());
+                    }   
+                },
```

**Comment by jboniface** [comment] 2022-04-15 20:23
@iwiznia @parasharrajat bump for proposal review

**Comment by parasharrajat** [comment] 2022-04-15 22:09
Missed it. I will get back to it asap.

**Comment by jboniface** [comment] 2022-04-21 20:31
bump again

**Comment by parasharrajat** [comment] 2022-04-21 20:37
Damn! not again. Sorry! I will review this first thing tomorrow.

**Comment by parasharrajat** [comment] 2022-04-26 17:49
Sorry, reviewing in 20 mins.

**Comment by parasharrajat** [comment] 2022-04-26 18:51
Ok, I see the problem now. 

@dharmik your proposal is lacking step 5 from the steps. `Tap on any tab that has "Connect to bank" (For example: Issue cards, reimburse expenses, etc)`. 

It says to go to any page where this "Connect to bank" is available and fix the issue in all those places.

**Comment by iwiznia** [comment] 2022-05-06 12:29
@dharmik are you going to update your proposal with @parasharrajat's suggestions?

**Comment by dharmik** [comment] 2022-05-06 12:38
Yes, i will plan to do it today or tomorrow.

**Comment by parasharrajat** [comment] 2022-05-16 15:57
Open to proposals.

**Comment by parasharrajat** [comment] 2022-05-17 11:39
Can we think of a solution where we do not have to duplicate the code? Proposal can be improved.

**Comment by iwiznia** [comment] 2022-05-27 12:36
Still waiting for a proposal here.

**Comment by dharmik** [comment] 2022-05-27 13:30
Updated Proposal @parasharrajat 

added new file: WorkSpaceUtils.js for common method 
```diff
+import lodashGet from 'lodash/get';
+import BankAccount from '../../libs/models/BankAccount'; 
+import Navigation from '../../libs/Navigation/Navigation';
+/**
+* If we have an open bank account or no bank account at all then we will immediately redirect the user to /bank-account +to display the next step
+*
+* @returns {Boolean}
+*/
+function getShouldShowPage(props, nextPage, defaultPage) {
+    const state = lodashGet(props.reimbursementAccount, 'achData.state');
+    const isShowPage =  lodashGet(props.reimbursementAccount, 'achData.bankAccountID') && state !== +BankAccount.STATE.OPEN;
+    if (isShowPage) {
+       Navigation.navigate(nextPage)
+    } else {
+        Navigation.navigate(defaultPage)
+    }
+}  

+export {
+    getShouldShowPage,
+};

```

Updated File: WorkspaceInitialPage.js
```diff
import * as PolicyActions from '../../libs/actions/Policy';
+import * as WorkSpaceUtils from './WorkSpaceUtils';

             {
                 translationKey: 'workspace.common.bankAccount',
                 icon: Expensicons.Bank,
-                action: () => Navigation.navigate(ROUTES.getWorkspaceBankAccountRoute(policy.id)),
+                action: () => WorkSpaceUtils.getShouldShowPage(this.props, ROUTES.getWorkspaceBankAccountRoute(policy.id), ROUTES.getBankAccountRoute()),
             },

```

same above changes done in below files
WorkspaceReimburseView.js
WorkspaceTravelNoVBAView.js
WorkspaceInvoicesNoVBAView.js

**Comment by parasharrajat** [comment] 2022-05-27 14:51
Waiting for a few days for different(better) proposals.

**Comment by dharmik** [comment] 2022-05-27 18:17
Let's find some **WET** code.

**Comment by parasharrajat** [comment] 2022-05-30 14:36
Thanks for the proposal. I need to confirm something internally. Will finalize this soon..https://expensify.slack.com/archives/C02NK2DQWUX/p1653921306765089

**Comment by mallenexpensify** [comment] 2022-06-02 17:57
It's because a proposal was submitted so it's daily until C+/Rajat reviews it (ie. it's working as intended)

**Comment by jboniface** [comment] 2022-06-02 18:21
oh neat, I didn't know!

**Comment by parasharrajat** [comment] 2022-06-09 12:50
Thanks @dharmik and @jayeshmangwani for proposals. Both of those approaches will work fine. But we decided to go with @dharmik 's [proposal](https://github.com/Expensify/App/issues/8541#issuecomment-1139621541) due the reason that global Onyx subscription is more expensive then some extra function calls. 

cc: @iwiznia 

:ribbon: :eyes: :ribbon:  C+ reviewed

**Comment by iwiznia** [comment] 2022-06-09 18:58
Looks good. @jboniface let's hire @dharmik

**Comment by jboniface** [comment] 2022-06-20 14:13
Sorry, I think I must have missed a bunch of email notifications, since I have a lot of overdue with last activity on the same day (which I didn't see until now).

**Comment by jboniface** [comment] 2022-06-20 14:15
@dharmik you can use this job to apply, the original one expired https://www.upwork.com/jobs/~016f4893b49ecbf949

**Comment by mallenexpensify** [comment] 2022-06-29 16:23
@dharmik Can you please apply to the Upwork job and confirm in a comment here once you have? Thx 
 https://www.upwork.com/jobs/~016f4893b49ecbf949

**Comment by dharmik** [comment] 2022-07-05 18:24
@mallenexpensify Applied on upwork

**Comment by parasharrajat** [comment] 2022-07-09 01:58
@dharmik Could you please update us on when will you submit the PR?

**Comment by dharmik** [comment] 2022-07-11 18:07
Actually, I am facing compile issue so I am trying to fixing that. That issue is only compile in iOS. @iwiznia

**Comment by iwiznia** [comment] 2022-07-11 20:27
ok, if you are stuck, you can always try to post in the slack channel and ask for help.

**Comment by dharmik** [comment] 2022-07-12 03:46
@iwiznia It's related to my internal pod and arch so I will update today any how.

**Comment by dharmik** [comment] 2022-07-14 05:51
@iwiznia  Just for update, I am able to compile it. Working on PR.

**Comment by iwiznia** [comment] 2022-07-18 17:16
Seems we have a draft one, so I assume we are close to being ready?

**Comment by mvtglobally** [comment] 2022-07-19 03:19
Issue not reproducible during KI retests. (First week)

**Comment by iwiznia** [comment] 2022-07-22 00:58
PR in review

**Comment by dharmik** [comment] 2022-07-26 03:28
I will do it in this week. Last week there is another proposal so will do it in this week.

**Comment by parasharrajat** [comment] 2022-07-29 15:04
Let's open this issue to others its been 40 days since the PR is pending for this issue.

**Comment by iwiznia** [comment] 2022-08-05 16:45
Yeah, @dharmik I've unassigned you. @puneetlath what do we need to do in upwork?
Also, to anyone else here, this is up for grabs again, only thing needed is implementation, since the proposal is already approved.

**Comment by dharmik** [comment] 2022-08-05 17:32
@iwiznia PR link [https://github.com/Expensify/App/pull/9948](https://github.com/Expensify/App/pull/9948)

**Comment by iwiznia** [comment] 2022-08-08 09:16
ok

**Comment by puneetlath** [comment] 2022-08-10 20:53
How's this one going? It has been a while.

**Comment by puneetlath** [comment] 2022-08-15 14:58
Looks like we've had some progress on the PR. Are we getting closer?

**Comment by puneetlath** [comment] 2022-08-23 16:49
Looks like the PR is getting closer. Let's try to get this over the finish line asap. It has been dragging for a long time.

**Comment by puneetlath** [comment] 2022-08-29 08:43
It has been C+ approved, so we're finally getting closer.

**Comment by puneetlath** [comment] 2022-09-08 11:41
@parasharrajat @thesahindia @dharmik sent you all hiring offers in Upwork.

**Comment by iwiznia** [comment] 2022-09-12 10:49
Not overdue

**Comment by puneetlath** [comment] 2022-09-12 13:16
@dharmik can you please accept the Upwork offer so that we can pay you out and close this issue.

**Comment by dharmik** [comment] 2022-09-13 04:28
@puneetlath Accepted.

**Comment by puneetlath** [comment] 2022-09-13 13:08
All paid! Thanks everyone.

**Closed by puneetlath** 2022-09-13 13:08 UTC
Labels: Exported, External, Engineering, Daily, Awaiting Payment
