### ISSUE TITLE
[$500]  Scan - __ fake __ is displayed as owner of the system generated message for failed scanning

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#30134] opened 2023-10-21 21:30 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.3.88-3
**Reproducible in staging?:** Yes
**Reproducible in production?:** Yes
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** Applause - Internal Team
**Slack conversation:**

**Issue found when executing PR** https://github.com/Expensify/App/pull/27494
## Action Performed:
1. Go to staging.new.expensify.com
2. Create a Scan request using a receipt with no merchant
3. Wait for it to fail
4. When it fails, open the IOU details page

## Expected Result:
The system generated message for 'Receipt scanning failed' should be assigned with an appropriate user

## Actual Result:
__ fake __ is displayed as the owner of the system generated message for 'Receipt scanning failed

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [x] Android: mWeb Chrome
- [x] iOS: Native
- [x] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos
<details>
<summary>Android: Native</summary>

</details>

<details>
<summary>Android: mWeb Chrome</summary>

</details>

<details>
<summary>iOS: Native</summary>

</details>

<details>
<summary>iOS: mWeb Safari</summary>

</details>

<details>
<summary>MacOS: Chrome / Safari</summary>

 
![Bug6245666_1697907464384!Receipt_with_no_merchant](https://github.com/Expensify/App/assets/78819774/f0422c47-3564-4bbb-abd6-fa3d5a37f2a2)

https://github.com/Expensify/App/assets/78819774/e2e98def-1b4e-4271-9171-fa46fb5975da

</details>

<details>
<summary>MacOS: Desktop</summary>

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01fb00b2dc10f94a59</li>
        <li>Upwork Job ID: 1715843159501512704</li>
        <li>Last Price Increase: 2023-10-28</li>
    </ul>
</details>

**Comment by wlegolas** [comment] 2023-10-21 23:41
Hello!

I was doing my investigation to generate my proposal but in my RCA I understood that the problem is more related to the backend than the frontend, for this reason, I didn't create a proposal, but to help resolve this issue I'll put below the result related to my RCA

# Results from my RCA

When creating a Scan request using a receipt with no merchant, and occurs an error, the backend returns the report action with the "**0**" value in the `actorAccountID`.  And this value is important to extract the actor information in the `personalDetailsList`.

![image](https://github.com/Expensify/App/assets/698363/cb208a82-a528-43c4-99ac-9035045a9cad)

Inside the `ReportActionItemSingle` component, is extracted the `displayName` from the personal list using the `actorAccountID` from the action report (in this case the value is "**0**"):

https://github.com/Expensify/App/blob/dcb698f5c844d40af4bdf89b10dd98ca215e8a4b/src/pages/home/report/ReportActionItemSingle.js#L90C1-L92C73

There is the variable `personArray` that will have the array with the person's information, there is a condition to generate the person's information, if the variable `displayName` has a value, will create an array with the `displayName` as the text, otherwise, will be used the information `person` from the action (that is this the issue case)

https://github.com/Expensify/App/blob/dcb698f5c844d40af4bdf89b10dd98ca215e8a4b/src/pages/home/report/ReportActionItemSingle.js#L136C1-L143C31

In this case, the `ReportActionItemSingle` component is using the `person` from the action, and if you see in the image above, the "**person**" property inside the action has the text "**__fake__**".

I hope this helps.

**Comment by wlegolas** [comment] 2023-10-22 11:36
Hello @lanitochka17, could you share a receipt with a merchant, please?

**Comment by laurenreidexpensify** [comment] 2023-10-24 13:50
@Ollyws what do you think of the proposals above?

**Comment by mallenexpensify** [comment] 2023-10-27 17:07
Posted the below in [an internal room](https://expensify.slack.com/archives/C05RECHFBEW/p1698426241362899?thread_ts=1698251312.069319&cid=C05RECHFBEW)
> Are `undefined &` and `_fake_` correlated-enough that, for the issue above, we want to do something to inc or consider `undefined &` ? Right now it's not mentioned in the GH, I'm going to ask there too and link to here.

@neil-marcellini I added the engineering label for bonus 👀, in case the two are related and we're able to expedite getting this fixed, check the link above for the discussion, which is more about `undefined &`  than `_fake_`

**Comment by neil-marcellini** [comment] 2023-10-27 18:29
@Gonals may I re-assign this to you? I believe you recently implemented this.

**Comment by laurenreidexpensify** [comment] 2023-10-30 11:19
@neil-marcellini @Gonals can you review and confirm above thanks?

**Comment by Gonals** [comment] 2023-10-30 11:36
I am fairly sure this is caused by us using an invalid account. AKA: `notifications@expensify.com` (which should be the account posting this) does not exist or is in a weird state. Checking from supportal, it seems it was originally created in a closed state, so my bet is that `Account::getID` is not getting it correctly.

In dev, passing a valid account there fixes the problem, so I don't think we need any frontend changes. 

Auth PR incoming

**Comment by mvtglobally** [comment] 2023-11-09 21:00
Issue not reproducible during KI retests. (First week)

**Comment by Gonals** [comment] 2023-11-10 11:26
This should be fixed already

**Closed by Gonals** 2023-11-10 11:26 UTC
Labels: Reviewing, Engineering, Weekly, Internal, Help Wanted, Bug
