### ISSUE TITLE
Secure your account is not opening

### ISSUE THREAD

**Issue by m-natarajan** [Expensify/App#24438] opened 2023-08-11 16:09 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Go to any workspace(if not have any please create) and go to workspace setting
2. Go to the Bank account
3. then select Connect Manually
4. Enter all details and verify details and reach validate Bank account page
5. Now, click on secure your account button
## Expected Result:
The link should open properly
## Actual Result:
The link is not opening.
## Workaround:
UnKnown
## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [x] iOS / native
- [ ] iOS / Safari
- [ ] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:**1.3.53-1
**Reproducible in staging?:** No
**Reproducible in production?:** No
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/38435837/1c9a73b8-289e-4e54-9b15-d61ee30dca33
**Expensify/Expensify Issue URL:**
**Issue reported by:** @niravkakadiya25
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1691139785266599

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by MitchExpensify** [comment] 2023-08-13 17:00
Getting stuck at the onfido step, will try again ASAP

**Comment by MitchExpensify** [comment] 2023-08-21 19:43
i am still stuck at the OnFido step to reproduce this properly, asking in the Slack thread how others are testing this https://expensify.slack.com/archives/C049HHMV9SM/p1691139785266599

**Comment by MitchExpensify** [comment] 2023-08-21 19:58
![IMG_569C434B6AF6-1](https://github.com/Expensify/App/assets/36425901/dd1e37af-3149-410c-a1e6-fea0f04b2671)

Ok I got to the link and it seems to be working fine

**Comment by MitchExpensify** [comment] 2023-08-21 19:59
Closing

**Closed by MitchExpensify** 2023-08-21 19:59 UTC
Labels: Daily, Needs Reproduction, Bug
