### ISSUE TITLE
[$500] Distance - EReceipt thumbnail is not clickable when distance request is edited offline

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#37344] opened 2024-02-27 20:03 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.44-6
**Reproducible in staging?:** Y
**Reproducible in production?:** N
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** Applause - Internal Team
**Slack conversation:**

## Action Performed:
1. Go to staging.new.expensify.com
2. Go to workspace chat
3. Create a distance request
4. Go to request details page
5. Go offline
6. Click Distance
7. Add a waypoint and save it
8. Click on the receipt thumbnail

## Expected Result:
User will be able to open EReceipt when distance request is edited offline (production behavior)

## Actual Result:
EReceipt thumbnail is not clickable when distance request is edited offline

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [x] Android: mWeb Chrome
- [x] iOS: Native
- [x] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details> 

https://github.com/Expensify/App/assets/78819774/ebf41488-15ad-4f4f-97ad-50add4443896

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01e647aab2a32331ae</li>
        <li>Upwork Job ID: 1762569075317325824</li>
        <li>Last Price Increase: 2024-02-27</li>
<li>Automatic offers: </li>
<ul>
<li>paultsimura | Reviewer | 0</li>
<li>shubham1206agra | Reviewer | 0</li>
<li>aimane-chnaif | Contributor | 0</li>
</ul></li>
    </ul>
</details>

**Comment by lanitochka17** [comment] 2024-02-27 20:04
We think that this bug might be related to #wave5
CC @dylanexpensify

**Comment by Tony-MK** [comment] 2024-02-27 20:23
## Proposal

### Please re-state the problem that we are trying to solve in this issue.

Distance - EReceipt thumbnail is not clickable when distance request is edited offline

### What is the root cause of that problem?

We are showing the `PendingMapView` when the `thumbnail` is not present. 

https://github.com/Expensify/App/blob/13e294488351680ffd3c1a86a985a0b0e2b2f801/src/components/DistanceEReceipt.tsx#L57-L61

Futhermoew, in [`DistanceEReceipt`](https://github.com/Expensify/App/blob/13e294488351680ffd3c1a86a985a0b0e2b2f801/src/components/DistanceEReceipt.tsx#L29), uses the [`getThumbnailAndImageURIs`](https://github.com/Expensify/App/blob/13e294488351680ffd3c1a86a985a0b0e2b2f801/src/libs/ReceiptUtils.ts#L49-L51) function but does not only uses the `thumbnail` and not `image`.

https://github.com/Expensify/App/blob/13e294488351680ffd3c1a86a985a0b0e2b2f801/src/components/DistanceEReceipt.tsx#L29

Furthermore, in the [`getThumbnailAndImageURIs`](https://github.com/Expensify/App/blob/13e294488351680ffd3c1a86a985a0b0e2b2f801/src/libs/ReceiptUtils.ts#L49-L51) function, does not return thumbnail when transaction has an E receipt.

https://github.com/Expensify/App/blob/13e294488351680ffd3c1a86a985a0b0e2b2f801/src/libs/ReceiptUtils.ts#L49-L51


### What changes do you think we should make in order to solve the problem?


In the [`getThumbnailAndImageURIs`](https://github.com/Expensify/App/blob/13e294488351680ffd3c1a86a985a0b0e2b2f801/src/libs/ReceiptUtils.ts#L49-L51) function, change the condition above to return the image as the thumbnail.

### What alternative solutions did you explore? (Optional)

In [`DistanceEReceipt`](https://github.com/Expensify/App/blob/13e294488351680ffd3c1a86a985a0b0e2b2f801/src/components/DistanceEReceipt.tsx#L29), check if the image is also present to use it use it of `thumbnail`.

**Comment by paultsimura** [comment] 2024-02-27 20:53
It's caused by https://github.com/Expensify/App/pull/34133.
@shubham1206agra could you please take a look? We should make the `ConfirmedRoute` clickable when using it here:

https://github.com/Expensify/App/blob/069efefa7b550bb7b5325f108b96a52cc6a1e896/src/components/ReportActionItem/MoneyRequestView.tsx#L256-L258

**Comment by thienlnam** [comment] 2024-02-27 22:14
Thanks @paultsimura - Assigned @shubham1206agra / @aimane-chnaif so they can address this when they are back online

Removing the deploy blocker since the way it works right now is still fine and doesn't need to block deploy

**Comment by paultsimura** [comment] 2024-02-29 10:59
> This might be ideal behaviour as an optimistic EReceipt with a map component might be a little challenging to implement (especially download), and EReceipt might be useless if all the fields show TBD in this case.

The `date` and, most importantly, `waypoints` won't be TBD. IMO, if the map view is difficult to attach, we should at least show the `PendingMapView` in the `EReceipt`, like we used to:

<img width="484" alt="image" src="https://github.com/Expensify/App/assets/12595293/a3098f6b-af90-467b-88e1-8cd201c1f8c7">

**Comment by paultsimura** [comment] 2024-03-04 17:35
@thienlnam what should we do with this one?

**Comment by thienlnam** [comment] 2024-03-04 19:55
cc @neil-marcellini Do you have a preference of how we should handle this?

**Comment by neil-marcellini** [comment] 2024-03-04 20:24
I like @paultsimura's idea. We should handle it in the same way that we handle viewing the distance request eReceipt when creating a distance request offline, with the PendingMapView.

**Comment by paultsimura** [comment] 2024-03-11 12:44
@thienlnam based on the discussion above, as we've agreed that this indeed should be fixed, should it be fixed as a regression within the regression period?
If not – I would love to be assigned back as a C+ here.

**Comment by paultsimura** [comment] 2024-03-11 13:20
> This still comes under the regression period, as it was reported under that period.

That's why I wanted to double-check because this issue's been open for quite a while already.
If it won't be fixed as a regression, I think it would be fair to go through a regular External process allowing Contributors to post proposals as usual.

**Comment by thienlnam** [comment] 2024-03-11 18:42
Since this comes directly from a PR and was opened within the time period, let's have that handled as a regression. We wouldn't issue payment for this so please handle it with @aimane-chnaif.

**Comment by paultsimura** [comment] 2024-03-11 18:43
Ok, unassigning myself 👍

**Comment by thienlnam** [comment] 2024-04-16 19:43
Going to adjust to a monthly since this is not urgent

**Comment by thienlnam** [comment] 2024-05-18 01:22
This is an edge case and not a priority - going to just close it

**Closed by thienlnam** 2024-05-18 01:22 UTC
Labels: External, Engineering, Monthly, Overdue
