### ISSUE TITLE
Chat switcher searching should combine terms with AND, not OR

### ISSUE THREAD

**Issue by kavimuru** [Expensify/App#19243] opened 2023-05-19 00:32 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Click on search 
2. Enter 2 search terms (e.g garrett jason)
 
## Expected Result:
Search result should narrow down with both search terms (garrett AND Jason)
## Actual Result:
Result appears for garrett OR Jason
## Workaround:
Can the user still use Expensify without this being fixed? Have you informed them of the workaround?

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [x] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 1.3.16-3
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation
![image (4)](https://github.com/Expensify/App/assets/43996225/d3e6448f-0b87-4c09-9a50-702c8d41737c)
![image (3)](https://github.com/Expensify/App/assets/43996225/30b249ed-d043-4035-8db3-1158298b31ad)
![image (2)](https://github.com/Expensify/App/assets/43996225/10faa55b-a726-4d1a-847c-3b51c7c457f1)
<img width="960" alt="1" src="https://github.com/Expensify/App/assets/43996225/9290389d-5922-487a-b375-50a8479f2aea">

**Expensify/Expensify Issue URL:**
**Issue reported by:** @quinthar 
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1684294471474399

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by dukenv0307** [comment] 2023-05-19 05:11
## Proposal

### Please re-state the problem that we are trying to solve in this issue.

Chat switcher searching result should narrow down with both search terms 

### What is the root cause of that problem?

Currently when searching search input value will `spilt` by `'  '` in function `isSearchStringMatch`

### What changes do you think we should make in order to solve the problem?


Function `isSearchStringMatch` is used at chat switcher search and workspace member search. If we want to combine terms with AND in the both search, we will remove `spilt`  by `'  '` in function.  Or if we just want to combine terms with AND in only chat switcher search, we can handle it by adding param `isWorkspaceMemberSearch`

### What alternative solutions did you explore? (Optional)
NA

**Comment by LiaKim07** [comment] 2023-05-19 06:56
**Proposal**
Please re-state the problem that we are trying to solve in this issue.
Chat switcher searching should combine terms with AND, not OR

**What is the root cause of that problem?**

![image](https://github.com/Expensify/App/assets/93604038/ede59336-e25d-4592-83ec-baae223e64c8)


**What changes do you think we should make in order to solve the problem?**
We should replace _.some by _.every

**Comment by LiaKim07** [comment] 2023-05-19 07:45
![image](https://github.com/Expensify/App/assets/93604038/dfc71846-075f-4b9d-a31a-866e8c7e4e51)
![image](https://github.com/Expensify/App/assets/93604038/d47a5707-4d7b-48f4-9629-9855063c9034)

**Comment by mountiny** [comment] 2023-05-19 10:59
Sorry guys, I am going to close this one off, we are currently working on a new search which will be refactored and all the behaviour is designed there, here is a front end issue for that if you want to keep track of the project https://github.com/Expensify/App/issues/19248#issuecomment-1554357248

**Closed by mountiny** 2023-05-19 10:59 UTC
Labels: Daily, Bug
