### ISSUE TITLE
[PAUSED][$250]  Web - Unable to create a split expense with a large number of room members

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#42562] opened 2024-05-23 21:04 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.75-0
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**If this was caught during regression testing, add the test name, ID and link from TestRail:** N/A
**Issue reported by:** Applause - Internal Team

**Issue found when executing PR** https://github.com/Expensify/App/pull/41077
## Action Performed:
1. Log in with a new expensifail account
2. Create a workspace
3. Create a room
4. Invite 30 expensifail users
5. Navigate to the room
6. Create a manual split expense with a large number
7. Set the priority to "Most recent"
8. Open any of the created chats from the LHN

## Expected Result:
I should be able to create the split expense without any errors

## Actual Result:
Unable to create a split expense with a large number of room members with a new account. For the new chats I get "Unexpected error creating this chat, please try again later." error. For the split in the room, I get "Unexpected error submitting this expense. Please try again later." error
I also get a "Failed to load resource: the server responded with a status of 403 ()" console error

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details> 

https://github.com/Expensify/App/assets/78819774/498c791c-b77f-4fee-996a-c1a98cf5d55a

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01cb679b7ebce4149e</li>
        <li>Upwork Job ID: 1798422926054946284</li>
        <li>Last Price Increase: 2024-07-31</li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @sobitneupane</details>

**Comment by lanitochka17** [comment] 2024-05-23 21:05
@slafortune  I haven't added the External label as I wasn't 100% sure about this issue. Please take a look and add the label if you agree it's a bug and can be handled by external contributors

**Comment by lanitochka17** [comment] 2024-05-23 21:05
We think that this bug might be related to #vip-split

**Comment by slafortune** [comment] 2024-05-23 22:07
on vacation until June 4th - reassigning this.

**Comment by slafortune** [comment] 2024-05-23 22:10
Sounds like I'll readd myself to this as well and take it back on the 4th.  I didn't add myself back to any that have been assigned where I was unable to look at them at all.

> Hey @slafortune , as an fyi for OOO re-assignments, you're supposed to add an additional assignee, but stay assigned so you can take the issue back over once you're back from OOO (assuming it's still open). Here's the [relevant SO](https://stackoverflowteams.com/c/expensify/questions/8836) where the process is outlined.
> 
> I'm going to re-add you to the issue, but happy to tackle it while you're OOO!

**Comment by nkdengineer** [comment] 2024-05-24 04:43
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
Unable to create a split expense with a large number of room members with a new account. For the new chats I get "Unexpected error creating this chat, please try again later." error. For the split in the room, I get "Unexpected error submitting this expense. Please try again later." error
I also get a "Failed to load resource: the server responded with a status of 403 ()" console error

### What is the root cause of that problem?

When we invite new user to the room, `report?. participants` still contains optimistic accountID and then when we create a split expense, we set the `participants` incorrectly here which makes `SplitBill` API fails


https://github.com/Expensify/App/blob/8375abea3a377e7416404addde255b6ac8530a9b/src/libs/actions/IOU.ts#L6511-L6514
### What changes do you think we should make in order to solve the problem?
We should use the same way as we do to get the member in `RoomMembersPage` [here](https://github.com/Expensify/App/blob/8375abea3a377e7416404addde255b6ac8530a9b/src/pages/RoomMembersPage.tsx#L170-L176) to get the correct participants of the report

```
const chatReportOtherParticipants = ReportUtils.getVisibleChatMemberAccountIDs(report?.reportID ?? '0').flatMap((accountID) => {
    const pendingMember = report?.pendingChatMembers?.findLast((member) => member.accountID === accountID.toString());
    return !pendingMember || pendingMember.pendingAction !== CONST.RED_BRICK_ROAD_PENDING_ACTION.DELETE ? accountID : [];
});
```
https://github.com/Expensify/App/blob/8375abea3a377e7416404addde255b6ac8530a9b/src/libs/actions/IOU.ts#L6511-L6514
### What alternative solutions did you explore? (Optional)
NA

**Comment by slafortune** [comment] 2024-06-05 18:33
Looks like we were both out - sorry for the delay!

**Comment by sobitneupane** [comment] 2024-06-07 08:24
Thanks for the proposal @nkdengineer

So, the issue arises if there is any new member(no previous interaction) in the room, right?

Actions Performed should be:

1. Log in
2. Create a workspace
3. Create a room
4. Invite a user with whom you have no previous interaction
5. Navigate to the room
6. Create a manual split expense
7. Open any of the created chats from the LHN

**Comment by sobitneupane** [comment] 2024-06-10 04:42
@saracouto @slafortune Should I hold the proposal review for now? The status of the issue is Paused and priority is monthly.

**Comment by nkdengineer** [comment] 2024-06-12 09:14
@saracouto Why we add `Monthly` label here?

**Comment by slafortune** [comment] 2024-06-13 21:25
Since we are not actively working on VIP split right now, things related are paused.  Rather than closing all the GH's, they are being updated to Monthly so Melvin doesn't get too obnoxious!  Once this is in focus again, it will move from Monthly to Daily, and the priority will be updated at that time as well.  Probably best to focus on anything that isn't monthly/paused.

**Comment by slafortune** [comment] 2024-07-11 13:37
still paused

**Comment by sobitneupane** [comment] 2024-07-12 06:35
https://github.com/Expensify/App/issues/42562#issuecomment-2222966163

**Comment by mvtglobally** [comment] 2024-07-19 03:20
Issue not reproducible during KI retests. (First week)

**Comment by slafortune** [comment] 2024-07-31 16:09
Paused and not recreated in the last test - let's close this!

**Closed by slafortune** 2024-07-31 16:09 UTC
Labels: External, Monthly, Help Wanted, Bug
