### ISSUE TITLE
[HOLD for payment 2024-04-09] [$500] Weird pop up when hit `esc` key immediately, after clicking `uparrow` to edit the last message

### ISSUE THREAD

**Issue by m-natarajan** [Expensify/App#38483] opened 2024-03-18 15:34 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:**
**Reproducible in staging?:** needs reproduction 
**Reproducible in production?:** needs reproduction
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** @iwiznia 
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1710538564054589

## Action Performed:
1. Open any chat 
2. hit `up arrow` key to edit the last message 
3. Immediately hit `esc`key

## Expected Result:
Edit action should cancel and no pop up to edit the message

## Actual Result:
Edit box reappears after a second
NOTE: This is happening occasionally

## Workaround:
unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~019e21e5668d684c41</li>
        <li>Upwork Job ID: 1770530705295687680</li>
        <li>Last Price Increase: 2024-03-20</li>
<li>Automatic offers: </li>
<ul>
<li>ntdiary | Reviewer | 0</li>
</ul></li>
    </ul>
</details>

**Comment by slafortune** [comment] 2024-03-18 18:57
Unable to reproduce - will test again this week a bit.

**Comment by slafortune** [comment] 2024-03-20 18:02
still unable to reproduce - closing

**Comment by iwiznia** [comment] 2024-03-20 18:17
I got it today, this is certainly not fixed

**Comment by iwiznia** [comment] 2024-03-20 18:17
I am reproducing it as we speak

**Comment by slafortune** [comment] 2024-03-20 18:30
Cool!  Can you record it and give more details?  I am not able to

https://github.com/Expensify/App/assets/11725910/8ccd4459-cc5c-4500-a9f9-e3021c56845f

**Comment by iwiznia** [comment] 2024-03-20 18:33
Yep, here you go:
https://github.com/Expensify/App/assets/521248/bffa0b23-dcf4-4864-b306-8d5ca219813c

**Comment by slafortune** [comment] 2024-03-21 12:36
not sure why a C+ wasn't added - I'll have to play with the labels applied

**Comment by roitman-g** [comment] 2024-03-21 19:31
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
When clicking up arrow key (to edit the last message) and escape (to cancel editing the last message), the popup to edit the message appears back again after a second. Issue is easy to reproduce this way - go to some chat (chat 1), go to another chat (chat 2), return back to the exact previous chat 1, after this the issue is constant and not occasional. And if you keep repeating it long enough sometimes the popup is not closable at all.

### What is the root cause of that problem?
The debounced function that saves the draft is not being cancelled when the component (ReportActionItemMessageEdit) unmounts.

### What changes do you think we should make in order to solve the problem?
Instead of cancelling the debounced function when deleting the draft, it is a better way to cancel it when the component unmounts - this solves all the issues I stated in re-state of the proposal section and everything works smoothly. 



### What alternative solutions did you explore? (Optional)
N/A

**Comment by roitman-g** [comment] 2024-03-21 19:48
Contributor details
Your Expensify account email: roitman2580@gmail.com
Upwork Profile Link: https://www.upwork.com/freelancers/~01068c5dfd8b9232a5

**Comment by roitman-g** [comment] 2024-03-24 12:32
I submitted the proposal on upwork yesterday, but still was not hired. Is there something I need to do on my end for this?

**Comment by roitman-g** [comment] 2024-03-26 19:38
Also, I requested to be invited to a slack group and did get any invite. Could anyone help me with this? I already have code and can submit the pull request.

**Comment by slafortune** [comment] 2024-03-26 20:29
@roitman-g I don't see an email from you to the contributors@expensify.com inbox, what email did you use?

Before submitting any PR, you must propose a solution within the related GH issue. Add the proposal as an issue comment, and it will be reviewed by our team. You must receive explicit approval on a proposal before submitting a PR.

**Comment by roitman-g** [comment] 2024-03-26 20:36
@slafortune I used grigory.roitman@gmail.com.

I submitted the proposal and melvin-bot replied that I had been assigned this job in the github issue, does this mean it is approved?

**Comment by slafortune** [comment] 2024-03-26 20:43
found it!  Just replied, I can get you invited once I hear back.

Yep!  @ntdiary is the C+ who reviewed and commented [here](https://github.com/Expensify/App/issues/38483#issuecomment-2015348152) suggesting you for the job.  Then our internal engineer @aldo-expensify assigned you. 

Then Melvin gave further direction 
Please apply to the [Upwork job](https://www.upwork.com/jobs/~019e21e5668d684c41) and leave a comment on the Github issue letting us know when we can expect a PR to be ready for review 🧑‍💻
Once you apply to this job, your Upwork ID will be stored and you will be automatically hired for future jobs!

Be sure to read these, as they both have valuable information.
Keep in mind: [Code of Conduct](https://github.com/Expensify/App/blob/main/CODE_OF_CONDUCT.md) | [Contributing](https://github.com/Expensify/App/blob/main/contributingGuides/CONTRIBUTING.md) 📖

**Comment by roitman-g** [comment] 2024-03-26 21:02
@slafortune thank you for inviting me in slack. 
I already applied for the job on Upwork, but still was not hired though.

**Comment by slafortune** [comment] 2024-03-26 21:06
The action of hiring does not happen right away, it typically happens once the issue moves to a payment state in the 7 holding days for any regressions.  The slack invite may take a bit more time than I thought, but we'll get that addressed as soon as possible.  

You won't need that to complete this job, but feel free to shout here if you have questions or issues that do need to be asked/addressed via slack.

**Comment by slafortune** [comment] 2024-03-26 21:06
You're next step is comment on the Github issue letting us know when we can expect a PR to be ready for review 🧑‍💻

**Comment by roitman-g** [comment] 2024-03-26 21:18
@slafortune sorry for my misunderstanding. Does this mean my next step is to submit the PR and then link it here saying it is ready for the review? Or just state when I will post it? If so I can make the PR ready for the review in the next two hours.

**Comment by roitman-g** [comment] 2024-03-26 22:46
PR ready for review https://github.com/Expensify/App/pull/39027

**Comment by roitman-g** [comment] 2024-03-28 16:07
@slafortune I still was not invited to the slack channel, could you tell me when I can approximately expect to be invited if it is possible?

**Comment by roitman-g** [comment] 2024-04-08 14:18
@slafortune @ntdiary is there any help needed from my end right now?

**Comment by slafortune** [comment] 2024-04-08 18:04
@roitman-g thanks, nothing else!  I just sent an offer, I will pay that tomorrow.

**Comment by roitman-g** [comment] 2024-04-08 19:04
@slafortune thank you! could you also invite me to the slack channel?

**Comment by roitman-g** [comment] 2024-04-09 18:09
@slafortune thank you very much!

**Comment by slafortune** [comment] 2024-04-10 16:42
Paid!

**Closed by slafortune** 2024-04-10 16:42 UTC
Labels: External, Daily, Awaiting Payment, Bug
