### ISSUE TITLE
Android - Chat - When offline, if a user requests money and then deletes the message, the page keeps loading

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#38844] opened 2024-03-22 22:01 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.56.0
**Reproducible in staging?:** y
**Reproducible in production?:** n
**If this was caught during regression testing, add the test name, ID and link from TestRail:** https://expensify.testrail.io/index.php?/tests/view/4447619
**Issue reported by:** Applause - Internal Team

## Action Performed:
1. Launch app
2. Tap on a new 1:1 report
3. Go offline
4. Send a message
5. Delete the message
6. Note the message is striked and no skeleton loading in the page
7. Tap plus icon and request money
8. Complete the request money flow
9. Send a message
10. Delete the message
11. Now note the page behaviour

## Expected Result:
When offline, after requesting money, if a user sends and deletes a message, the deleted message should be struck through, and the rest of the messages on the page should display without any issues.

## Actual Result:
When offline, after requesting money, if a user sends and deletes a message, the deleted message is struck through. However, the above messages and the entire page keep loading, displaying a skeleton.

## Workaround:
n/a

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [ ] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

https://github.com/Expensify/App/assets/93399543/81c40e0e-e69d-41f5-ba3d-9a0d297e72a8

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by kbecciv** [comment] 2024-03-22 22:02
We think that this bug might be related to #vip-vsb

**Comment by NikkiWines** [comment] 2024-03-23 01:45
When testing on dev, this behavior is reproducible for me on web as well. @kbecciv can you confirm if this is specific to Android of a regression across all platforms

**Comment by NikkiWines** [comment] 2024-03-23 02:24
I have a suspicion that this is tied to the changes added by https://github.com/Expensify/App/pull/30269. It also seems like similar behavior to another existing blocker https://github.com/Expensify/App/issues/38781.

@roryabraham looks like you have context for both the PR and the associated blocker, thoughts?

**Comment by roryabraham** [comment] 2024-03-23 03:12
Yeah, looks quite possibly like the same root cause. Let's [CP](https://expensify.enterprise.slack.com/archives/C07J32337/p1711160712866259) and retest.

**Comment by bernhardoj** [comment] 2024-03-23 07:39
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
The other messages disappear and the skeleton shows when deleting a message.

### What is the root cause of that problem?
The other messages disappear because `getContinuousReportActionChain` only includes some of the messages.
https://github.com/Expensify/App/blob/191d9326cd6cdbdc76d24ddf09f8a2f5fe6295ec/src/libs/ReportActionsUtils.ts#L307-L308

When calculating the `endIndex`, we check whether the current action `previousReportActionID` is the same as the previous action `previousReportActionID`.
https://github.com/Expensify/App/blob/191d9326cd6cdbdc76d24ddf09f8a2f5fe6295ec/src/libs/ReportActionsUtils.ts#L283-L292

However, a newly optimistic added action doesn't have `previousReportActionID` yet, so the condition always fails.

The initial value of `endIndex` (and `startIndex`) is calculated here by finding the index of the action that the `pendingAction` value is not `add`,
https://github.com/Expensify/App/blob/191d9326cd6cdbdc76d24ddf09f8a2f5fe6295ec/src/libs/ReportActionsUtils.ts#L268

and because we delete the first action, the pending action is updated to delete, so the `endIndex` value is 0.

### What changes do you think we should make in order to solve the problem?

Based on this comment, the reason we check for pending action add is that the action doesn't have the `previousReportActionID` value yet which we rely on the BE to give us the value.
https://github.com/Expensify/App/blob/191d9326cd6cdbdc76d24ddf09f8a2f5fe6295ec/src/libs/ReportActionsUtils.ts#L297-L298

But as mentioned above, when deleting the message, the pending action value is overwritten. The cause of the issue is the same as [this one](https://github.com/Expensify/App/issues/32529) where we rely on the pending action, but it's overwritten. To overcome the issue, we introduce a new property called `isOptimisticAction`.

So, the solution is to replace the pending action check with `isOptimisticAction`.
https://github.com/Expensify/App/blob/191d9326cd6cdbdc76d24ddf09f8a2f5fe6295ec/src/libs/ReportActionsUtils.ts#L268

```ts
index = sortedReportActions.findIndex((obj) => !obj.isOptimisticAction);
```

https://github.com/Expensify/App/blob/191d9326cd6cdbdc76d24ddf09f8a2f5fe6295ec/src/libs/ReportActionsUtils.ts#L301

```ts
sortedReportActions[startIndex - 1]?.isOptimisticAction ||
```

### What alternative solutions did you explore? (Optional)
Optimistically set `previousReportActionID` to a new action, but doesn't sound good because it's possible the action list is not in order when the app is still loading or while offline.

**Comment by bernhardoj** [comment] 2024-03-23 07:41
The issue still happens, please check my proposal for the solution.

**Comment by roryabraham** [comment] 2024-03-23 08:39
@bernhardoj I like your alternate solution better - it seems like optimistic actions could be seamlessly integrated into the chain by setting the `previousReportActionID` to be the ID of the newest action on a report whenever creating a new one optimistically.

**Comment by roryabraham** [comment] 2024-03-25 18:06
> doesn't sound good because it's possible the action list is not in order when the app is still loading or while offline

Not sure I'm following the concern here @bernhardoj

**Comment by roryabraham** [comment] 2024-03-25 23:55
This will be fixed by https://github.com/Expensify/App/pull/38968. I do think including `previousReportActionID` in optimistic actions is a better solution, but too big a refactor to CP

**Comment by bernhardoj** [comment] 2024-03-26 02:47
> Not sure I'm following the concern here @bernhardoj

So, I'm thinking of 2 cases where the optimistic `previousReportActionID` could be wrong.

1. When you open a chat that the report actions are not loaded yet (empty, 0 length). In this case, the first optimistic comment `previousReportActionID` would be empty.
2. When you open a chat that has incomplete/outdated report actions

**Comment by roryabraham** [comment] 2024-03-26 22:47
> When you open a chat that the report actions are not loaded yet (empty, 0 length). In this case, the first optimistic comment previousReportActionID would be empty

That's actually a very good point

**Comment by roryabraham** [comment] 2024-03-26 23:27
verified that this is fixed on staging, going to close it out now.

**Closed by roryabraham** 2024-03-26 23:27 UTC
Labels: Reviewing, DeployBlockerCash, Engineering, Hourly
