### ISSUE TITLE
[$250]  Web - VBA - When selecting "Saving" account, it switches to "Checking" in Connect Bank Account

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#8640] opened 2022-04-14 02:14 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
Pre-Condition workspace is created but the user doesn't have a bank account connected to the account
1. Access www.staging.new.expensify.com
2. Log into a valid applause.expensifail.com account and Enable the Staging server
3. Tap on the "Profile" icon and head to the users "workspace"
4. Tap on "Connect to bank"
5. Tap "Connect online with Plaid"
6. Tap on "Wells Fargo" bank and enter correct credentials (user_good and pass_good)
7. On the "Success" page, click "Continue"
8. In the "Choose an account dropdown", select the "Savings" option

## Expected Result:
User expects that after clicking "Savings" account in the drop down menu that this is what will show up

## Actual Result:
The user clicks "Savings" account but the dropdown menu changes to "Checking" account every time on a fresh flow.

## Workaround:
Unknown

## Platform:

Where is this issue occurring?

- Web
- Mobile Web

**Version Number:** 1.1.55.0

**Reproducible in staging?:** Yes

**Reproducible in production?:** N/A ( unable to check VBA flow in Prod)

**Email or phone of affected tester (no customers):** n/a

**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Notes/Photos/Videos:** Any additional supporting documentation

https://user-images.githubusercontent.com/93399543/163300356-d898a384-ae96-495c-9627-5edd6e3d5f7b.mp4

**Expensify/Expensify Issue URL:** 

**Issue reported by:** Applause

**Slack conversation:** 

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by deetergp** [comment] 2022-04-14 18:03
Seems like a prime candidate for the external contributor pool.

**Comment by adelekennedy** [comment] 2022-04-18 18:04
[internal](https://www.upwork.com/ab/applicants/1516115336226508800/job-details)
[external](https://www.upwork.com/jobs/~0155a79153e7cd22b9)

**Comment by wildanmuhlis2** [comment] 2022-04-26 07:28
@mvtglobally, is it possible to reproduce it as an external contributor?

It is always redirected to the live site instead of asking for sandbox cred.

the same issue raised [here](https://expensify.slack.com/archives/C01GTK53T8Q/p1649949322758349).

**Comment by parasharrajat** [comment] 2022-04-26 15:58
Pinged the slack thread.

**Comment by wildanmuhlis2** [comment] 2022-04-26 23:15
@parasharrajat sure, I've followed the slack thread and it resolved by using staging env and enabling the secure staging server option.
<img width="379" alt="Screen Shot 2022-04-27 at 06 07 55" src="https://user-images.githubusercontent.com/11847279/165407760-a4ad3b6d-f0ca-4357-8073-3ae87570a62e.png">

**Comment by wildanmuhlis2** [comment] 2022-04-26 23:36
@kbecciv  seems this issue has resolved in v1.1.57-0

https://user-images.githubusercontent.com/11847279/165409634-35613010-743f-45d1-bd39-4e153af18cae.mp4

**Comment by parasharrajat** [comment] 2022-04-28 14:36
Great. @mvtglobally Could you please retest this one?

**Comment by mvtglobally** [comment] 2022-05-03 03:54
Issue not reproducible during KI retests. (First week)

**Comment by adelekennedy** [comment] 2022-05-06 22:10
are we ready to close this?

**Comment by mvtglobally** [comment] 2022-05-10 04:29
Issue not reproducible during KI retests. (Second week)

**Comment by adelekennedy** [comment] 2022-05-13 16:36
Since this wasn't reproducible for two weeks do we still keep this open @chiragsalian?

**Comment by chiragsalian** [comment] 2022-05-13 16:45
Yeah i think the issue is resolved. Closing it. Feel free to reopen if it reoccurs.

**Closed by chiragsalian** 2022-05-13 16:45 UTC
Labels: Exported, External, Engineering, Weekly, Improvement, Help Wanted
