### ISSUE TITLE
[HOLD for payment 2023-10-09] [$500] Border appears for the User avatar on the Money request page header.

### ISSUE THREAD

**Issue by kavimuru** [Expensify/App#26361] opened 2023-08-31 01:14 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Open any chat and request Money ( make sure it works by avoiding the bugs around the IOU feature Now ) and Open it, you could Open any existing money request message
3. Notice the avatars on the money request header
4. May be you will need to zoom in to notice it clearly
## Expected Result: 
The avatar shouldn't have any border.
- Or to be more accurate, The border color for avatar should match the background color, to be invisible and style the both participants avatar like we want
## Actual Result: 
The user avatar has a border.
- The  avatar border has a different shade of green, creating a border effect. The border appears because we should give it a boder color that matches the background color to be invisible and gave us the style we want for both participants avatars. Like the avatars in money request message in the main chat.

## Workaround:
Can the user still use Expensify without this being fixed? Have you informed them of the workaround?

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [x] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 1.3.59-1
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation

![Screenshot from 2023-08-23 03-10-56](https://github.com/Expensify/App/assets/43996225/0cdd2134-79be-4ae4-b42d-e31976dba9b3)

[Screencast from 22-08-23 04_37_03.webm](https://github.com/Expensify/App/assets/43996225/f080e159-f722-408b-a3b8-df4c520793cb)

![Snip - (103) New Expensify - Google Chrome](https://github.com/Expensify/App/assets/43996225/5b9c7ae6-5b07-4518-afea-ccba944c8557)

**Expensify/Expensify Issue URL:**
**Issue reported by:** @Ahmed-Abdella
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1692669808539929

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~013384dd572fef261e</li>
        <li>Upwork Job ID: 1699883091268702208</li>
        <li>Last Price Increase: 2023-09-07</li>
<li>Automatic offers: </li>
<ul>
<li>bernhardoj | Contributor | 26665036</li>
<li>Ahmed-Abdella | Reporter | 26665037</li>
</ul></li>
    </ul>
</details>

**Comment by s-alves10** [comment] 2023-08-31 03:42
This looks like an intended behavior

**Comment by s-alves10** [comment] 2023-08-31 03:42
## Proposal

### Please re-state the problem that we are trying to solve in this issue.

Border appears for the second user avatar on the money request page header

### What is the root cause of that problem?

We have [AvatarWithDisplayName](https://github.com/Expensify/App/blob/main/src/components/AvatarWithDisplayName.js) component in [HeaderWithBackButton of MoneyReportHeader](https://github.com/Expensify/App/blob/c20c3870ee46d6788de554be27706e9898638904/src/components/MoneyReportHeader.js#L87C14-L87C34)

We're setting the second avatar style here in the `AvatarWithDisplayName` component
https://github.com/Expensify/App/blob/c20c3870ee46d6788de554be27706e9898638904/src/components/AvatarWithDisplayName.js#L115

This is the root cause

### What changes do you think we should make in order to solve the problem?

We can pass `secondAvatarStyle` props with value [] to the `MultipleAvatars` component in `AvatarWithDisplayName` component
```
        <MultipleAvatars
            icons={icons}
            size={props.size}
            secondAvatarStyle={[]}
        />
```

This works fine

Note: We can add additional props for setting second avatar style in the `AvatarWithDisplayName` component

<details>
    <summary>Result</summary>

![image](https://github.com/Expensify/App/assets/126839717/df1126c2-bb7e-400c-9676-7a6f49ebc52f)

</details>


### What alternative solutions did you explore? (Optional)

**Comment by joekaufmanexpensify** [comment] 2023-08-31 23:50
I agree there is a border, but not sure that this is actually a bug. Further, you can only really notice the border when significantly zoomed in, like this: 

<img width="1104" alt="image" src="https://github.com/Expensify/App/assets/54866469/9eb7ccc3-fc00-48d3-8503-6508a54950d2">

When you're at normal zoom, it just distinguishes between the two avatars, which makes me think this may be required. 

<img width="1511" alt="image" src="https://github.com/Expensify/App/assets/54866469/59fd8b08-cee4-4f50-afcd-35243d400719">

I'm inclined to do nothing here, but curious what @shawnborton thinks?

**Comment by shawnborton** [comment] 2023-09-01 11:57
Yeah, that border should match the background color. @grgia I think this was part of the avatar changes you made, are you able to follow up and fix this one quickly?

**Comment by joekaufmanexpensify** [comment] 2023-09-01 19:49
Cool cool, sounds good.

**Comment by joekaufmanexpensify** [comment] 2023-09-04 17:47
Not overdue

**Comment by joekaufmanexpensify** [comment] 2023-09-05 20:37
@grgia Curious how you want to proceed [with this](https://github.com/Expensify/App/issues/26361#issuecomment-1702633129). If you don't have the bandwidth, just LMK, and I'll make this external!

**Comment by joekaufmanexpensify** [comment] 2023-09-07 20:31
Chatted with Georgia, and we're going to make this one external!

**Comment by PiyushChandra17** [comment] 2023-09-08 07:14
## Proposal


### Please re-state the problem that we are trying to solve in this issue.
The avatar shouldn't have any border

### What is the root cause of that problem?
In [AvatarWithDisplayName.js](https://github.com/Expensify/App/blob/main/src/components/AvatarWithDisplayName.js#L115), 

```secondAvatarStyle={[StyleUtils.getBackgroundAndBorderStyle(themeColors.highlightBG)]}```

We are not using correct shade of green, hence this is the root cause.


### What changes do you think we should make in order to solve the problem?
We need to apply this change, replace `highlightBG` with `borderFocus` or `splashBG` since both uses `colors.green` in `AvatarWithDisplayName` component. This should solve the problem.

```
<MultipleAvatars
                icons={icons}
                size={props.size}
                secondAvatarStyle={[StyleUtils.getBackgroundAndBorderStyle(themeColors.borderFocus)]}
/>

```

### What alternative solutions did you explore? (Optional)
NA

### Screenshot:
<img width="155" alt="Screenshot 2023-09-08 at 12 18 19 PM" src="https://github.com/Expensify/App/assets/47579287/d2d87850-27c6-477a-bd02-a17dde2459cf">

**Comment by PiyalAhmed** [comment] 2023-09-08 10:26
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
After creating a money request, if we open it, in the header, there is a border on the top avater (seconderyAvetar). And the border is of highlighted(Different color than the background). Where the expectation is, the border color should match the background color.

### What is the root cause of that problem?
In [AvatarWithDisplayName.js](https://github.com/Expensify/App/blob/main/src/components/AvatarWithDisplayName.js#L115) file,

There the secondAvaterStyle is set to ```themeColors.highlightBG```
For this style, the border color is not same as the component background color.

### What changes do you think we should make in order to solve the problem?

We can just set the secondAvaterStyle to ```themeColors.componentBG``` 
This will solve the problem.

The end result will look like this
![image](https://github.com/Expensify/App/assets/43670583/c546a907-44fd-4d33-b593-ddd0e49c1ceb)
### What alternative solutions did you explore? (Optional)
NA

**Comment by PiyalAhmed** [comment] 2023-09-08 10:30
Contributor details
Your Expensify account email: piyal.salamence@gmail.com
Upwork Profile Link: https://www.upwork.com/freelancers/~0197f7733019ff4f22

**Comment by joekaufmanexpensify** [comment] 2023-09-08 19:16
@ArekChr mind taking a look at the proposal here?

**Comment by Ahmed-Abdella** [comment] 2023-09-11 00:55
Hey @joekaufmanexpensify @shawnborton @ArekChr , the same issue is in the IOU distance room header, and I think they should be fixed the same way
1. request money using distance
2. choose the workspace
3. open the IOU room and notice the header
4. the workspace avatar border is still visible
![Screenshot from 2023-09-11 03-47-47](https://github.com/Expensify/App/assets/77763699/184d1256-a0b7-4255-99a0-35137ad5b5d5)

**Comment by ArekChr** [comment] 2023-09-11 13:31
@joekaufmanexpensify Yes, I will make sure of this during the PR checklists and QA tests

**Comment by ArekChr** [comment] 2023-09-12 10:02
@bernhardoj you are right, you suggested a similar change first. We should proceed with your proposal. 

@bernhardoj @s-alves10 Please send a new message if you're making significant edits to your original proposals. This will help keep everyone on the same page and avoid confusion.

**Comment by joekaufmanexpensify** [comment] 2023-09-12 19:07
Pending internal engineering sign off.

**Comment by joekaufmanexpensify** [comment] 2023-09-13 21:11
@grgia mind signing off on the proposal here when you have a sec?

**Comment by grgia** [comment] 2023-09-14 02:24
Assigning @bernhardoj

**Comment by joekaufmanexpensify** [comment] 2023-09-25 02:59
I think this one is pending internal review from @grgia

**Comment by joekaufmanexpensify** [comment] 2023-10-02 21:20
@ArekChr mind taking care of the checklist this week?

**Comment by ArekChr** [comment] 2023-10-03 11:48
- [x] Link to the PR: no PR has been identified.
- [x] Link to comment: n/a
- [x] Link to discussion: n/a
- [x] Determine if we should create a regression test for this bug: I don’t think we need to add a regression test here.

**Comment by joekaufmanexpensify** [comment] 2023-10-09 20:38
BZ checklist is complete, all set to issue payment. The PR was not merged within 3 business days. However, @ArekChr approved the PR within 3 business days (on 2023-09-18), and then the internal engineer assigned merged it a bit later on 2023-09-25. Because the delay was on us internally, this still qualifies for a speed bonus. This means we need to pay: 

- @bernhardoj $750 - $500 for PR, and $250 speed bonus (paid via Upwork). 
- @Ahmed-Abdella - $50 for reporting (paid via Upwork). 
- @ArekChr - payment is handled separately.

**Comment by joekaufmanexpensify** [comment] 2023-10-09 20:40
@bernhardoj $750 sent and contract ended!

**Comment by joekaufmanexpensify** [comment] 2023-10-09 20:41
@Ahmed-Abdella $50 sent and contract ended!

**Comment by joekaufmanexpensify** [comment] 2023-10-09 20:42
Upwork job closed.

**Comment by joekaufmanexpensify** [comment] 2023-10-09 20:42
Bug is fixed, BZ checklist complete, and all payment issued. Closing as this is all set. Thanks everyone!

**Closed by joekaufmanexpensify** 2023-10-09 20:42 UTC
Labels: External, Daily, Awaiting Payment, Bug

**Comment by Ahmed-Abdella** [comment] 2023-10-10 00:40
Hi, @joekaufmanexpensify @ArekChr I just noticed that this issue is reproducible in the new UI for the LHN. the border appears for the IOU page row in the LHN, check stage to see this, Just click on any IOU row in the LHN to activate the background color and the border will appear.

![Screenshot from 2023-10-10 03-33-16](https://github.com/Expensify/App/assets/77763699/783a2a5e-f13f-4e44-a34a-d5d197f4cc35)
