### ISSUE TITLE
[$250] mWeb - Chat  - Entering spade and diamond makes spade symbol smaller in compose

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#47675] opened 2024-08-19 21:29 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 9.0.22
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**If this was caught during regression testing, add the test name, ID and link from TestRail:** https://expensify.testrail.io/index.php?/tests/view/4871799
**Issue reported by:** Applause - Internal Team

## Action Performed:
1. Go to https://staging.new.expensify.com/home
2. Tap on a chat
3. Enter ♡◇

## Expected Result:
Entering spade and diamond must not make spade symbol smaller in compose

## Actual Result:
Entering spade and diamond makes spade symbol smaller in compose

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [x] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [ ] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details> 

https://github.com/user-attachments/assets/b665b265-c628-4559-80d1-1e9b19f74e7b

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01aa453839e3c5dec4</li>
        <li>Upwork Job ID: 1826736805004685557</li>
        <li>Last Price Increase: 2024-09-19</li>
    </ul>
</details>

**Comment by lanitochka17** [comment] 2024-08-19 21:30
We think that this bug might be related to #vip- vsp

**Comment by johncschuster** [comment] 2024-09-05 21:03
@mollfpr can you review the proposal above when you get a moment?

**Comment by wildan-m** [comment] 2024-09-10 04:44
## Proposal

### Please re-state the problem that we are trying to solve in this issue.

Entering a spade and diamond in chat makes the spade symbol smaller when composing messages in mWeb.

### What is the root cause of that problem?

We are adding some unlisted symbol as emoji ♡ and excluding others ◇, This create inconsistencies.

https://github.com/Expensify/App/blob/6334d36a049d01cfa9a445f3747125d79a00bc98/src/CONST.ts#L2335-L2337

https://github.com/Expensify/expensify-common/blob/e14dff64438b19fc9b6aa6937502b64870e0be86/lib/CONST.ts#L365

### What changes do you think we should make in order to solve the problem?

Emoji and non-emoji text were handled differently. If the text consisted only of emoji, the font size and line height could vary, and hovering over an emoji would trigger a pop-up. Unknown symbols might be classified under `Extended_Pictographic`, leading to inconsistencies and unexpected outcomes.

Changing `Extended_Pictographic` to `Emoji_Presentation` in the regex is [recommended to only treat typical emojis](https://github.com/colinhacks/zod/discussions/2848#discussioncomment-7218695).

```tsx
        // eslint-disable-next-line max-len, no-misleading-character-class
        EMOJI: /[\p{Emoji_Presentation}\u200d\u{1f1e6}-\u{1f1ff}\u{1f3fb}-\u{1f3ff}\u{e0020}-\u{e007f}\u20E3\uFE0F]|[#*0-9]\uFE0F?\u20E3/gu,
        // eslint-disable-next-line max-len, no-misleading-character-class
        EMOJIS: /[\p{Emoji_Presentation}](\u200D[\p{Emoji_Presentation}]|[\u{1F3FB}-\u{1F3FF}]|[\u{E0020}-\u{E007F}]|\uFE0F|\u20E3)*|[\u{1F1E6}-\u{1F1FF}]{2}|[#*0-9]\uFE0F?\u20E3/gu,
```
And also in expensify-common

Slack seems to treat characters in `Emoji_Presentation` differently than unknown symbols in `Extended_Pictographic` or other symbols.

Quick test:


https://github.com/user-attachments/assets/955699d7-346c-413e-a412-fa879a3c23d4


### What alternative solutions did you explore? (Optional)
Only treat differently for character that matches registered emojis
assets/emojis/common.ts

rough snippet:

```tsx
// Step 1: Define the list of Unicode code points
const codePoints = [
    0x1F600, // 😀
    0x1F601, // 😁
    0x1F602, // 😂
    0x1F603, // 😃
    0x1F604, // 😄
    0x1F605, // 😅
    0x1F606, // 😆
    0x1F607, // 😇
    0x1F608, // 😈
    0x1F609, // 😉
    // Add more code points as needed
];

// Step 2: Convert each code point to its hexadecimal representation
const hexCodePoints = codePoints.map(cp => cp.toString(16).toUpperCase());

// Step 3: Create a regex pattern that matches any of these code points
const regexPattern = `\\u{${hexCodePoints.join('}|\\u{')}}`;

// Step 4: Create the regex object
const regex = new RegExp(regexPattern, 'u');

console.log(regex); // Output: /\u{1F600}|\u{1F601}|\u{1F602}|\u{1F603}|\u{1F604}|\u{1F605}|\u{1F606}|\u{1F607}|\u{1F608}|\u{1F609}/u
```

**Comment by johncschuster** [comment] 2024-09-12 21:56
Bumped in Slack for proposal review

**Comment by mollfpr** [comment] 2024-09-17 09:50
@tsa321 I tried your proposal but the diamond text size still shows small.

I agree with the @wildan-m [proposal](https://github.com/Expensify/App/issues/47675#issuecomment-2339598879), treating non-emoji text the same as regular text.

![Screenshot_20240917_164748_Chrome](https://github.com/user-attachments/assets/28f8a5a1-0791-4f10-b24e-9ed8e4143cc6)

@johncschuster Could you confirm if the above result can be the expected result here?

**Comment by wildan-m** [comment] 2024-09-17 10:08
@mollfpr if the font size is the same, then the remaining factor is font-family

**Comment by johncschuster** [comment] 2024-09-19 22:08
> @johncschuster Could you confirm if the above result can be the expected result here?

Honestly,this feels like such a small edge case. I'm not passionate about it.

@Expensify/design do you feel passionate about this one? If you have a preference for how these symbols should look, please chime in!

**Comment by dubielzyk-expensify** [comment] 2024-09-19 23:34
Yeah, it looks to me like it's treating the space as a emoji and making it bigger but the diamond as text. 

Still, I don't even think this worth fixing. Doesn't feel broken and I really don't see anyone running into this and being confused. But keen to hear what the other @Expensify/design(ers) think

**Comment by wildan-m** [comment] 2024-09-19 23:46
I think it's worth fixing try to submit this love symbol ♡ and hover the symbol, the pop up will show with empty pop up. That's one of unexpected outcome from current regex.

**Comment by shawnborton** [comment] 2024-09-20 06:46
I think this is such an edge case, I say we just close it.

**Closed by shawnborton** 2024-09-20 06:46 UTC
Labels: External, Daily, Help Wanted, Bug
