### ISSUE TITLE
Distance tax - Distance rate with non-zero tax rate shows 0% rate when submitting next expense

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#43137] opened 2024-06-05 18:20 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4-79-2
**Reproducible in staging?:** Y
**Reproducible in production?:** Y 
**If this was caught during regression testing, add the test name, ID and link from TestRail:** N/A
**Issue reported by:** Applause - Internal Team

**Issue found when executing PR** https://github.com/Expensify/App/pull/42909
## Action Performed:
Precondition:
- Track Tax distance is enabled on Old Dot
- Workspace has a few distance rates and the distance rates are associated with tax rates
1. Go to staging.new.expensify.com
2. Go to workspace chat
3. Submit a distance expense with distance rate that has non-zero tax rate (so that this distance rate will be the default one when creating the next distance expense)
4. Go to workspace chat
5. Go to + > Submit expense > Distance
6. Enter waypoints > Next
7. Note that the tax rate for the distance in Step 3 becomes tax exempt (0%)
8. Change to another distance rate and change again back to the same distance rate in Step 8
9. Note that the distance rate only shows the correct tax rate after reselecting distance rate

## Expected Result:
In Step 7, the selected distance rate should show the correct tax rate when creating another distance expense

## Actual Result:
In Step 7, the selected distance rate should show the incorrect tax rate (it shows tax exempt 0%) when creating another distance expense
It only shows the correct tax rate when reselecting the distance rate (Step 8)

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [x] Android: mWeb Chrome
- [x] iOS: Native
- [x] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details> 

https://github.com/Expensify/App/assets/78819774/a4aebacb-5d47-44b1-b613-7fcefac28269

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by lanitochka17** [comment] 2024-06-05 18:21
@joekaufmanexpensify  FYI I haven't added the External label as I wasn't 100% sure about this issue. Please take a look and add the label if you agree it's a bug and can be handled by external contributors

**Comment by bernhardoj** [comment] 2024-06-06 07:33
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
The distance tax rate isn't set automatically.

### What is the root cause of that problem?
When we select a distance rate, we also update the tax rate here.
https://github.com/Expensify/App/blob/90dee7accae79c49debf30354c160cab6c52c423/src/pages/iou/request/step/IOURequestStepDistanceRate.tsx#L80-L89

But we don't do the same when initializing it. The app will currently only initialize the distance rate.
https://github.com/Expensify/App/blob/90dee7accae79c49debf30354c160cab6c52c423/src/components/MoneyRequestConfirmationList.tsx#L241-L249

So the tax rate will always be the default one.

### What changes do you think we should make in order to solve the problem?

Initialize the tax rate too when the page is initialized.
```
useEffect(() => {
    if (!customUnitRateID) {
        return;
    }
    const distanceUnit = PolicyUtils.getCustomUnit(policy);
    const customUnitID = distanceUnit?.customUnitID;
    if (policy?.customUnits && customUnitID && shouldShowTax) {
        const policyCustomUnitRate = policy?.customUnits[customUnitID].rates[customUnitRateID];
        const taxRateExternalID = policyCustomUnitRate.attributes?.taxRateExternalID ?? '';
        const taxAmount = CurrencyUtils.convertToBackendAmount(DistanceRequestUtils.calculateTaxAmount(policy, transaction, customUnitRateID));
        IOU.setMoneyRequestTaxAmount(transactionID, taxAmount, true);
        IOU.setMoneyRequestTaxRate(transactionID, taxRateExternalID);
    }
}, [customUnitRateID, isPolicyExpenseChat, policy, isDistanceRequest, transaction, transactionID]);
```

_maybwe weh should move it to a util function_

**Comment by joekaufmanexpensify** [comment] 2024-06-06 20:53
I followed the reproduction steps above, and can't reproduce this. We are using the correct tax rate when I create the second expense, rather than defaulting to $0. 

https://github.com/Expensify/App/assets/54866469/1c746cbc-fbc0-49df-af32-4e056d17bead

**Comment by joekaufmanexpensify** [comment] 2024-06-06 20:54
Gonna close this out for now since it doesn't appear to be reproducible, but LMK if there is some other way to reproduce this, and happy to take another look

**Closed by joekaufmanexpensify** 2024-06-06 20:54 UTC
Labels: Daily, Bug
