### ISSUE TITLE
[$500] mweb - Room - Inviting a contact with (++) in mail id in public room displays message flagged

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#35550] opened 2024-02-01 13:32 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.34
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**If this was caught during regression testing, add the test name, ID and link from TestRail:** https://expensify.testrail.io/index.php?/tests/view/4257186
**Email or phone of affected tester (no customers):** applausetester++0411km@applause.expensifail.com
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** Applause - Internal Team
**Slack conversation:**

## Action Performed:
1. Go to https://staging.new.expensify.com/
2. Tap fab--- Start chat
3. Tap room
4. Enter all fields
5. Select visibility as "public"
6. Tap create room
7. Enter @ in compose
8. Select a contact with 2 plus(++) in email id from user suggestion list eg:[applausetester++0411km@applause.expensifail.com](mailto:applausetester++0411km@applause.expensifail.com)
9. Send the message

## Expected Result:
When we invite a contact with 2 plus(++) in email id from user suggestion list eg:[applausetester++0411km@applause.expensifail.com](mailto:applausetester++0411km@applause.expensifail.com)
in public room, "your message has been flagged" must not be shown.

## Actual Result:
When we invite a contact with 2 plus(++) in email id from user suggestion list eg:[applausetester++0411km@applause.expensifail.com](mailto:applausetester++0411km@applause.expensifail.com)
in public room, "your message has been flagged" is shown.

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [x] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details>  

https://github.com/Expensify/App/assets/78819774/60029bce-6c9b-42a7-b72b-0357dc358e8f

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01441c2e6853d873ac</li>
        <li>Upwork Job ID: 1753048615726497792</li>
        <li>Last Price Increase: 2024-02-01</li>
    </ul>
</details>

**Comment by pc11000** [comment] 2024-02-01 14:37
where is the flagging done? do contributors also can get access to the stackoverflow expensify?

**Comment by cjoshi-zeals** [comment] 2024-02-01 16:07
I am not able to reproduce issue

![Screenshot 2024-02-01 at 9 36 11 PM](https://github.com/Expensify/App/assets/91712307/bd8d27cf-ea51-403c-9ea8-a544eac92e6d)

**Comment by ijmalik** [comment] 2024-02-01 16:19
Contributor details
Your Expensify account email: ijmalik@gmail.com
Upwork Profile Link: https://www.upwork.com/freelancers/~0111172c8e8a5b3f55

**Comment by WestDon** [comment] 2024-02-02 11:20
Looks like it needs to be fixed on the server side because we sending just a comment  <mention-user>@applausetester++0411km@applause.expensifail.com</mention-user> and it return this your message has been flagged

**Comment by ijmalik** [comment] 2024-02-04 20:02
**Please re-state the problem that we are trying to solve in this issue.**
A message indicating "Your message has been flagged" is displayed when we invite a contact with email like applausetester++0411km@applause.expensifail.com in public room.

**What is the root cause of that problem?**
The system flags any email that appears spammy. The inclusion of two plus signs (++) is unnecessary. For instance:
"abcwwwweeeeeennnn333333n55555555555555555yyyyyyyyyyyyyyyyyyggghhjjjjjjjy@teeeest.com"
"devid+1000000dddfffff3333ddddddddddddddddddqqqqqqqqqqq3333336666@gmail.com"

**What changes do you think we should make in order to solve the problem?**
![image](https://github.com/Expensify/App/assets/2220885/aadd5426-1fcd-4f33-9f14-d951adf6653b)

**Comment by ijmalik** [comment] 2024-02-05 16:43
@fedirjh Yes, I also think that it is the expected behavior.

**Comment by lschurr** [comment] 2024-02-05 16:44
I agree - let's close this one. Thanks!

**Closed by lschurr** 2024-02-05 16:44 UTC
Labels: External, Daily, Help Wanted, Bug
