### ISSUE TITLE
Task - Close error does not clear red dot on LHN

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#29687] opened 2023-10-16 16:04 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.3.84.4
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** @namhihi237
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1697424844642799

## Action Performed:
1. Open 2 users on 2 browsers
2. Both users open chat together
3. User A create a task
4. Both users open task report
5. User B force offline mode
6. User A complete task
7. User B complete task
8. User B turn on network
9. User B click close error, Observe that LHN does not clear the red dot

## Expected Result:
LHN clear red dot when user B close error

## Actual Result:
LHN does not clear red dot when user B close error

## Workaround:
Unknown 

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [x] Android: mWeb Chrome
- [x] iOS: Native
- [x] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos
<details>
<summary>Android: Native</summary>

 

https://github.com/Expensify/App/assets/93399543/0c625a8f-2547-4748-8b03-9163aacd5d7c

</details>

<details>
<summary>Android: mWeb Chrome</summary>

 

https://github.com/Expensify/App/assets/93399543/3fe53c16-90f5-445e-bfb8-482839647657

</details>

<details>
<summary>iOS: Native</summary>

 

https://github.com/Expensify/App/assets/93399543/8549c6e5-9d8e-43a1-a373-62d011e3e01b

</details>

<details>
<summary>iOS: mWeb Safari</summary>

 

https://github.com/Expensify/App/assets/93399543/cd3d4b04-f95c-4681-be75-a0c1929082be

</details>

<details>
<summary>MacOS: Chrome / Safari</summary>

 

https://github.com/Expensify/App/assets/93399543/9c69a187-0dd6-41dc-8db6-9245e3daeeca

https://github.com/Expensify/App/assets/93399543/15adaa6b-64de-4061-ad8f-9b01f55df35e

</details>

<details>
<summary>MacOS: Desktop</summary>

 

https://github.com/Expensify/App/assets/93399543/47d2c40c-2acb-499d-bebe-955b7572f9d6

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by akamefi202** [comment] 2023-10-16 21:25
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
Close error does not clear red dot on LHN.

### What is the root cause of that problem?
https://github.com/Expensify/App/blob/62a8821ed6d1be44040571df9dd33ac75070b0cd/src/libs/actions/ReportActions.ts#L30-L34

If the user clicks "Close" button of the error message, `clearReportActionErrors` function clears `errors` field of the relevant report action from onyx data.

![Screenshot from 2023-10-17 04-48-21](https://github.com/Expensify/App/assets/53784473/75f74123-4a88-4f9d-80cc-8b753988e58d)

But it doesn't clear error information from onyx data of the task report.

https://github.com/Expensify/App/blob/62a8821ed6d1be44040571df9dd33ac75070b0cd/src/libs/SidebarUtils.js#L289-L290

https://github.com/Expensify/App/blob/62a8821ed6d1be44040571df9dd33ac75070b0cd/src/components/LHNOptionsList/OptionRowLHN.js#L117

https://github.com/Expensify/App/blob/62a8821ed6d1be44040571df9dd33ac75070b0cd/src/components/LHNOptionsList/OptionRowLHN.js#L267-L268

Because of this, we see red dot although the user closed error message in the task report screen.

### What changes do you think we should make in order to solve the problem?
We need to clear error information from onyx data of the task report too.
We should add code for this inside `clearReportActionErrors` function and this is the required change from `FE`.

But currently, report action data & error data of task report don't have any keys & values to be related each other.
So I think `BE` requires some change too.

![Screenshot from 2023-10-17 05-07-21](https://github.com/Expensify/App/assets/53784473/9fddc404-99f2-4c73-a972-fa58f5b1535a)

Above screenshot is response data of `CompleteTask` request if an error occurs like this issue.
The only decisive key of error information is the timestamp value. (1697485026264145)

I think we need to save this value to onyx data of the relevant report action, by returning from `BE`.
For example, `BE` could return below data additionally as response.
```
{
	key: "reportActions_6495543636766578",
	onyxMethod: "merge",
	value: {
		4354318888897513223: {
			reportErrorTimestamp: 1697485026264145
		}
	}
}
```

As a result, we would be able to remove correct error information by checking `reportErrorTimestamp` field of report action data.

### What alternative solutions did you explore? (Optional)

**Comment by ikevin127** [comment] 2023-10-16 21:56
# Proposal

## Please re-state the problem that we are trying to solve in this issue

Clearing report action error does not clear corresponding LHN red dot error.

## What is the root cause of that problem?

This happens due to the fact that `clearReportActionErrors` currently **only** clears the `reportAction` key by setting it to null which clears the chat text error:

https://github.com/Expensify/App/blob/fe40f63532dd6bfb47355ef7110c0cfcb9af6624/src/libs/actions/ReportActions.ts#L15-L20

but then **returns**. In order for the red dot to be removed we need to clear the actual `report` error key `errorFields` called `completeTask` which allows that red dot to be displayed because the error is not cleared.

## What changes do you think we should make in order to solve the problem?

Within the `clearReportActionErrors` function I would add the Onyx.merge() that would also clear the `errorFields` key called `completeTask` by setting it to null.

```diff
    if (reportAction.pendingAction === CONST.RED_BRICK_ROAD_PENDING_ACTION.ADD) {
        // Delete the optimistic action
        Onyx.merge(`${ONYXKEYS.COLLECTION.REPORT_ACTIONS}${originalReportID}`, {
            [reportAction.reportActionID]: null,
        });

        // Delete red dot on LHN error after clearing reportAction error
+       Onyx.merge(`${ONYXKEYS.COLLECTION.REPORT}${originalReportID}`, {
+           errorFields: {completeTask: null},
+       });

        // If there's a linked transaction, delete that too
        const linkedTransactionID = ReportActionUtils.getLinkedTransactionID(originalReportID, reportAction.reportActionID);
        if (linkedTransactionID) {
            Onyx.set(`${ONYXKEYS.COLLECTION.TRANSACTION}${linkedTransactionID}`, null);
        }

        return;
    }
```

and will also add type to `Report.ts` -> `type Report` in order for setting `errorFields: {completeTask: null}` not to throw type error:

```
errorFields?: unknown;
```

### Result:

<details>
<summary>MacOS: Chrome / Safari</summary>

https://github.com/Expensify/App/assets/56457735/30bb45b5-934d-4149-a4ec-765b78fe7880

</details>

**Comment by ikevin127** [comment] 2023-10-17 13:24
### Updated [proposal](https://github.com/Expensify/App/issues/29687#issuecomment-1765339265)
- added a more detailed explanation as to what's the root cause of the problem

**Comment by abdulrahuman5196** [comment] 2023-10-18 14:41
Reviewing now

**Comment by abdulrahuman5196** [comment] 2023-10-23 12:04
Sorry got a high priority issue last time and couldn't review. Will review the issue today.

**Comment by lschurr** [comment] 2023-10-25 17:03
Bump on reviewing these @abdulrahuman5196

**Comment by abdulrahuman5196** [comment] 2023-10-25 18:20
Sorry for the delay. REviewing now

**Comment by abdulrahuman5196** [comment] 2023-10-25 18:49
I am not seeing this issue anymore. I am not even getting error on step 7 and 8.

>User B complete task
>User B turn on network

@lschurr Could you kindly check if you are able to repro the issue anymore?

**Comment by ikevin127** [comment] 2023-10-25 22:00
Looks like the issue was fixed from the BE side because it doesn't throw 403 anymore.

**Comment by abdulrahuman5196** [comment] 2023-10-30 12:53
@lschurr To check this https://github.com/Expensify/App/issues/29687#issuecomment-1779859569

**Comment by lschurr** [comment] 2023-10-30 16:37
It sounds like this was fixed with a backend changing. Going to close.

**Closed by lschurr** 2023-10-30 16:37 UTC
Labels: External, Daily, Help Wanted, Bug
