### ISSUE TITLE
[$500] Desktop - Notifications - Notification was not shown when user received the first message in a new chat

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#34876] opened 2024-01-22 13:00 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.28-0
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:** https://expensify.testrail.io/index.php?/tests/view/4206591&group_by=cases:section_id&group_order=asc&group_id=295000
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** Applause - Internal Team
**Slack conversation:**

## Action Performed:
Precondition: there should not be the existing conversation between users
1. Open app on the main testing device
2. From the secondary account, which does not have a conversation with the main testing device account, send a message to the main testing device.

## Expected Result:
The notification should be shown when first message was received in a new chat

## Actual Result:
Notification was not shown when user received the first message in a new chat

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [ ] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

https://github.com/Expensify/App/assets/93399543/033afda3-701f-4d22-a600-8df02db9aaf6

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01f42ec145a22f6147</li>
        <li>Upwork Job ID: 1749416702776217600</li>
        <li>Last Price Increase: 2024-01-29</li>
    </ul>
</details>

**Comment by kbecciv** [comment] 2024-01-22 13:01
We think that this bug might be related to #vip-vsb
CC @quinthar

**Comment by subhampanja2** [comment] 2024-01-22 16:26
Working fine for me. 
<img width="1437" alt="Screenshot 2024-01-22 at 9 54 41 PM" src="https://github.com/Expensify/App/assets/98098639/617784ea-a62d-4780-928d-8a7ef46ddbb6">

<img width="1440" alt="Screenshot 2024-01-22 at 9 55 57 PM" src="https://github.com/Expensify/App/assets/98098639/be1cf249-f131-4797-8fb0-7f630b0ec5c3">


I did exactly same as mentioned.
how to reproduce it ?

**Comment by cubuspl42** [comment] 2024-01-30 09:18
I don't have high expectations of this being fixed externally (if at all).

**Comment by WestDon** [comment] 2024-01-30 17:45
## Proposal
### Please re-state the problem that we are trying to solve in this issue
No notification for newly created channel from one account to another
### What is the root cause of that problem?
The problem is with wrong data coming from pusher when creating channel
### What changes do you think we should make in order to solve the problem?
We need check and update server code to make sure property in report with name **notificationPreference** correct -'always', now its coming 'daily' that is incorrect and cancel notification for that report
What alternative solutions did you explore? (Optional)
-

**Comment by WestDon** [comment] 2024-01-30 17:49
Contributor details
Your Expensify account email: andrei.vaschuk94@gmail.com
Upwork Profile Link: https://www.upwork.com/freelancers/~016e3bd7b5d3e067ce

**Comment by miljakljajic** [comment] 2024-02-02 10:40
posted in our internal VSB channel - I'll see about whether we can work on this one externally or not

**Comment by quinthar** [comment] 2024-02-03 23:52
Sounds great, adding it to VSB as LOW.

**Comment by miljakljajic** [comment] 2024-02-27 15:38
Should we increase the bounty for this one?

**Comment by cubuspl42** [comment] 2024-02-28 08:40
🎀 👀 🎀

**Comment by cubuspl42** [comment] 2024-02-28 08:44
@flodnv

I would say that these glitches result from the overall Expensify notification architecture, which is unlikely to be solved externally. On the other hand, I don't have much faith in this being fixed internally **either** because of the priorities and "lack of hands".

Shouldn't we just close this?

**Comment by miljakljajic** [comment] 2024-03-01 16:49
@flodnv what do you think?

**Comment by flodnv** [comment] 2024-03-04 20:04
It's part of the roadmap as low priority. It can stay as such for a few months which is not a problem.

**Comment by TheRealKraytonian** [comment] 2024-03-08 15:39
I will try and tackle this for $1000? I want 2 weeks to do it?

**Comment by TheRealKraytonian** [comment] 2024-03-11 08:38
Contributor details
Your Expensify account email: kraytonianmedia@gmail.com
Upwork Profile Link: (https://www.upwork.com/freelancers/~01639918f2e1bb6b6a)

**Comment by TheRealKraytonian** [comment] 2024-03-11 08:39
lets do this :)

**Comment by cubuspl42** [comment] 2024-03-11 08:43
This specific issue is marked "Internal" and is not open for proposals.

**Comment by TheRealKraytonian** [comment] 2024-03-11 20:45
How can I gain access to the slack?

**Comment by TheRealKraytonian** [comment] 2024-03-13 01:05
I emailed news I believe and heard nothing back

**Comment by cubuspl42** [comment] 2024-03-13 09:07
Please wait patiently; this is a human-managed process. In the meantime, find an issue open for proposals that you'd like to work on. Slack access won't give you much on its own. Let's not hijack this thread anymore, this is an internal issue and the comments should be related to it.

Preferably, you should hide your comments in this thread as "off-topic".

**Closed** 2024-05-17 18:23 UTC
Labels: Engineering, Monthly, Internal, Bug
