### ISSUE TITLE
[HOLD for payment 2024-02-15] [$500] Task - Task assigned to "Hidden" does not show "Hidden" as assignee in main chat

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#34052] opened 2024-01-05 18:43 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.22-0
**Reproducible in staging?:** Y
**Reproducible in production?:** N
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** Applause - Internal Team
**Slack conversation:**

**Issue found when executing PR** https://github.com/Expensify/App/pull/29730
## Action Performed:
1. Go to FAB > Assign task
2. Enter title > Next
3. Click Assignee
4. Enter a valid email with no display name that is registered on ND but has no chat history with the user
(use [yonghongkok2+03011@gmail.com](mailto:yonghongkok2+03011@gmail.com)
)
5. Create the task

## Expected Result:
The task preview in the main chat will show "Hidden" as the assignee

## Actual Result:
The task preview in the main chat does not show "Hidden" as the assignee

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [x] Android: mWeb Chrome
- [x] iOS: Native
- [x] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details> 

https://github.com/Expensify/App/assets/78819774/402b5d37-cf71-43b8-93b7-7c4629a9368a

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01e3fabdb897c1d05d</li>
        <li>Upwork Job ID: 1744829796306513920</li>
        <li>Last Price Increase: 2024-01-16</li>
<li>Automatic offers: </li>
<ul>
<li>hoangzinh | Contributor | 28116810</li>
<li>dukenv0307 | Contributor | 28117853</li>
</ul></li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @stephanieelliott</details>

**Comment by unicorndev-727** [comment] 2024-01-05 18:49
## Proposal
from: @unicorndev-727
### Please re-state the problem that we are trying to solve in this issue.

### What is the root cause of that problem?
The root cause is that we didn't use getDisplaynameForParticipant here. https://github.com/Expensify/App/blob/7ae1ec7e74b908e6340bccaf7e42b0345d766711/src/components/ReportActionItem/TaskPreview.js#L99
### What changes do you think we should make in order to solve the problem?
We should use getDisplayNameForParticipant.
### What alternative solutions did you explore?
N/A

**Comment by mvtglobally** [comment] 2024-01-07 04:56
Still repro on build 1.4.22-2 


https://github.com/Expensify/App/assets/43995119/758dc055-c041-49b3-b976-73adfa83f8df

**Comment by thienlnam** [comment] 2024-01-08 03:11
Don't think this needs to be a blocker, but we should fix this

**Comment by stephanieelliott** [comment] 2024-01-10 20:16
Hey @parasharrajat a few proposals here for you to review!

**Comment by stephanieelliott** [comment] 2024-01-16 22:25
Hey @parasharrajat any feedback on these proposals?

**Comment by stephanieelliott** [comment] 2024-01-19 19:13
@parasharrajat are you able to review this proposal, or should we reassign?

**Comment by stephanieelliott** [comment] 2024-01-23 03:28
Posted in #contributor-plus to try and recruit a new C+: https://expensify.slack.com/archives/C02NK2DQWUX/p1705980495003879

**Comment by stephanieelliott** [comment] 2024-01-23 03:31
@hoangzinh is gonna jump in to help us as C+ on this one -- we've got a couple proposals in the scrollback which need review!

**Comment by tgolen** [comment] 2024-01-23 16:45
I like the proposal from @dukenv0307 also, including the optional cleanup to make the display logic consistent.

**Comment by stephanieelliott** [comment] 2024-01-30 04:44
PR is still under review, looks like @hoangzinh is working through the checklist

**Comment by stephanieelliott** [comment] 2024-02-06 05:43
PR is still under active, seems like we are wrapping up though!

**Comment by stephanieelliott** [comment] 2024-02-08 07:00
PR is on staging!

**Comment by stephanieelliott** [comment] 2024-02-16 07:13
^^ was tested and found to be NAB!

**Comment by stephanieelliott** [comment] 2024-02-16 07:15
Summarizing payment on this issue: 

 - Contributor: @dukenv0307 $500, paid via Upwork 
 - Contributor+: @hoangzinh $500, paid via Upwork 
 
 Upwork job is here: https://www.upwork.com/jobs/~1737876297360310272"

**Closed by stephanieelliott** 2024-02-16 07:15 UTC
Labels: External, Engineering, Daily, Awaiting Payment, Bug
