### ISSUE TITLE
Expense - Banner shows user email/name first, then "You" instead of "You" directly

### ISSUE THREAD

**Issue by IuliiaHerets** [Expensify/App#49484] opened 2024-09-19 18:49 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 9.0.38-1
**Reproducible in staging?:** Y
**Reproducible in production?:** N/A - new feature, doesn't exist in prod
**Issue was found when executing this PR:** https://github.com/Expensify/App/pull/49315
**Email or phone of affected tester (no customers):** applausetester+kh010901@applause.expensifail.com
**Issue reported by:** Applause Internal Team

## Action Performed:
1. Go to staging.new.expensify.com
2. Go to workspace chat.
3. Submit an expense.
4. Go to expense report.

## Expected Result:
The banner will directly display "You" in "Waiting for You's expense(s) to..."

## Actual Result:
The banner shows user email (or name if there is custom name) first, then "You" in "Waiting for You's expense(s) to..."

## Workaround:
Unknown

## Platforms:

- [x] Android: Native
- [x] Android: mWeb Chrome
- [x] iOS: Native
- [x] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

https://github.com/user-attachments/assets/6276b6e3-ea54-48fa-a5eb-e6c1e73191cd

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by IuliiaHerets** [comment] 2024-09-19 18:49
We think that this bug might be related to #wave-collect - Release 1

**Comment by FitseTLT** [comment] 2024-09-19 18:55
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
Expense - Banner shows user email/name first, then "You" instead of "You" directly

### What is the root cause of that problem?
We are always displaying the display name whether or not the reimburser is the current user here
https://github.com/Expensify/App/blob/885d6f49aa922d372d6007b12fe768e4705a18a5/src/libs/NextStepUtils.ts#L101
### What changes do you think we should make in order to solve the problem?

We should change it to
```
    const reimburserDisplayName = reimburserAccountID === currentUserAccountID ? 'You' : ReportUtils.getDisplayNameForParticipant(reimburserAccountID);

```
### What alternative solutions did you explore? (Optional)

**Comment by FitseTLT** [comment] 2024-09-19 19:05
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
Expense - Banner shows user email/name first, then "You" instead of "You" directly

### What is the root cause of that problem?
We are always displaying the display name whether or not the reimburser is the current user here
https://github.com/Expensify/App/blob/885d6f49aa922d372d6007b12fe768e4705a18a5/src/libs/NextStepUtils.ts#L101
### What changes do you think we should make in order to solve the problem?

We should change it to
```
    const reimburserDisplayName = reimburserAccountID === currentUserAccountID ? 'You' : ReportUtils.getDisplayNameForParticipant(reimburserAccountID);

```
We need a similar fix for `nextApproverDisplayName` [here](https://github.com/Expensify/App/blob/885d6f49aa922d372d6007b12fe768e4705a18a5/src/libs/NextStepUtils.ts#L98)
We can apply similar fixes [here](https://github.com/Expensify/App/blob/885d6f49aa922d372d6007b12fe768e4705a18a5/src/libs/NextStepUtils.ts#L97) if needed for other next step status.
### What alternative solutions did you explore? (Optional)

**Comment by FitseTLT** [comment] 2024-09-19 19:07
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
Expense - Banner shows user email/name first, then "You" instead of "You" directly

### What is the root cause of that problem?
We are always displaying the display name whether or not the reimburser is the current user here
https://github.com/Expensify/App/blob/885d6f49aa922d372d6007b12fe768e4705a18a5/src/libs/NextStepUtils.ts#L97
### What changes do you think we should make in order to solve the problem?

We should change it to
```
    const ownerDisplayName = ownerAccountID === currentUserAccountID ? 'You' : ReportUtils.getDisplayNameForParticipant(ownerAccountID);

```
We need a similar fix for `nextApproverDisplayName` [here](https://github.com/Expensify/App/blob/885d6f49aa922d372d6007b12fe768e4705a18a5/src/libs/NextStepUtils.ts#L98) and reimburser [here](https://github.com/Expensify/App/blob/885d6f49aa922d372d6007b12fe768e4705a18a5/src/libs/NextStepUtils.ts#L101)
We can apply similar fixes [here](https://github.com/Expensify/App/blob/885d6f49aa922d372d6007b12fe768e4705a18a5/src/libs/NextStepUtils.ts#L97) if needed for other next step status.
### What alternative solutions did you explore? (Optional)

**Comment by FitseTLT** [comment] 2024-09-19 19:13
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
Expense - Banner shows user email/name first, then "You" instead of "You" directly

### What is the root cause of that problem?
We are always displaying the display name whether or not the owner is the current user here
https://github.com/Expensify/App/blob/885d6f49aa922d372d6007b12fe768e4705a18a5/src/libs/NextStepUtils.ts#L97
### What changes do you think we should make in order to solve the problem?

We should change it to
```
    const ownerDisplayName = ownerAccountID === currentUserAccountID ? 'You' : ReportUtils.getDisplayNameForParticipant(ownerAccountID);

```
We need a similar fix for `nextApproverDisplayName` [here](https://github.com/Expensify/App/blob/885d6f49aa922d372d6007b12fe768e4705a18a5/src/libs/NextStepUtils.ts#L98) and reimburser [here](https://github.com/Expensify/App/blob/885d6f49aa922d372d6007b12fe768e4705a18a5/src/libs/NextStepUtils.ts#L101)
### What alternative solutions did you explore? (Optional)

**Comment by FitseTLT** [comment] 2024-09-19 19:32
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
Expense - Banner shows user email/name first, then "You" instead of "You" directly

### What is the root cause of that problem?
We are always displaying the display name whether or not the owner is the current user here
https://github.com/Expensify/App/blob/885d6f49aa922d372d6007b12fe768e4705a18a5/src/libs/NextStepUtils.ts#L139
### What changes do you think we should make in order to solve the problem?

We should change it to
https://github.com/Expensify/App/blob/885d6f49aa922d372d6007b12fe768e4705a18a5/src/libs/NextStepUtils.ts#L139
```
                        text: ownerAccountID === currentUserAccountID ? 'Your' : `${ownerDisplayName}'s`,

```
We need to change
https://github.com/Expenisyf/App/blob/885d6f49aa922d372d6007b12fe768e4705a18a5/src/libs/NextStepUtils.ts#L117
```
                        text: ownerAccountID === currentUserAccountID ? 'You' : ownerDisplayName,

```
We need a similar fix for  reimburser [here]
https://github.com/Expensify/App/blob/885d6f49aa922d372d6007b12fe768e4705a18a5/src/libs/NextStepUtils.ts#L101
```
    const reimburserDisplayName = reimburserAccountID === currentUserAccountID ? 'You' : ReportUtils.getDisplayNameForParticipant(reimburserAccountID);

```
  and for `nextApproverDisplayName` [here](https://github.com/Expensify/App/blob/885d6f49aa922d372d6007b12fe768e4705a18a5/src/libs/NextStepUtils.ts#L98) we can update getNextApproverDisplayName to return `You` when the approver is the current user
### What alternative solutions did you explore? (Optional)

**Comment by srikarparsi** [comment] 2024-09-19 20:08
Awesome thanks! Will check back once this gets gets CPed

**Comment by grgia** [comment] 2024-09-19 20:23
Just triggered CP for https://github.com/Expensify/App/pull/49482 
[Progress on build here](https://github.com/Expensify/App/actions/runs/10948326809)

**Comment by srikarparsi** [comment] 2024-09-19 21:38
This has been fixed with [this PR](https://github.com/Expensify/App/pull/49482):

<img width="1139" alt="image" src="https://github.com/user-attachments/assets/7f186c93-4532-487b-a720-3633cbe90c35">

Going to close this out. Also @grgia do you know if there's plans to make the "Your" lowercase?

**Closed** 2024-09-19 22:33 UTC
Labels: DeployBlockerCash, Engineering, Hourly, Bug
