### ISSUE TITLE
[HOLD for payment 2023-08-01] [$1000] Dev: Web - Reaction does not work for first message of thread

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#22235] opened 2023-07-05 00:45 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Go to any chat
2. Hover on any message and click `reply in thread` option
4. In the thread, try to react on the first message

## Expected Result:
Reaction should be able to be applied

## Actual Result:
Reaction does not work

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [x] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 1.3.36-2 DEV
**Reproducible in staging?:** n/a
**Reproducible in production?:** n/a
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/93399543/eb25ff28-7fec-42a6-bf85-d2fb78a59b94

**Expensify/Expensify Issue URL:**
**Issue reported by:** @gadhiyamanan
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1688456691034579

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~019314fb87cf5420e8</li>
        <li>Upwork Job ID: 1676593895120011264</li>
        <li>Last Price Increase: 2023-07-05</li>
    </ul>
</details>

**Comment by cubuspl42** [comment] 2023-07-05 07:55
Reproduced

**Comment by jeet-dhandha** [comment] 2023-07-05 14:23
This is a regression of above linked issue.

**Comment by jeet-dhandha** [comment] 2023-07-05 14:24
PR For Fix: https://github.com/Expensify/App/pull/22270

**Comment by jeet-dhandha** [comment] 2023-07-05 14:28
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
- This was a regression of my previous issue.

### What is the root cause of that problem?
- Instead of report ID we need to access orignal reportID, which is of the parent. 

### What changes do you think we should make in order to solve the problem?
- We will use already existing function `getOriginalReportID(reportID, action)` to get the original report ID. And also change the reportActionID to the `action` as it was before.

### What alternative solutions did you explore? (Optional)
- N/A

**Comment by neil-marcellini** [comment] 2023-07-05 17:12
I would like to CME because I approved [the PR](https://github.com/Expensify/App/pull/21933) that caused this regression 🙃. @aimane-chnaif I like  @dukenv0307's proposal https://github.com/Expensify/App/issues/22235#issuecomment-1621285983.

**Comment by jeet-dhandha** [comment] 2023-07-05 17:27
I like to clear my wrecked code myself. So no worries my fellow frontier man @neil-marcellini.

**Comment by jeet-dhandha** [comment] 2023-07-05 17:44
@aimane-chnaif A question do we need to provide `All videos` everytime ?

**Comment by cubuspl42** [comment] 2023-07-05 17:51
As I wasn't sure if we have a formal process for it, I [asked on Slack](https://expensify.slack.com/archives/C01GTK53T8Q/p1688579375594329) if we should proceed with proposal selection here, or should this be closed in favor of a follow-up PR by the author of the original PR which introduced a regression.

**Comment by cubuspl42** [comment] 2023-07-05 17:57
@neil-marcellini 

> I like @dukenv0307's proposal [#22235 (comment)](https://github.com/Expensify/App/issues/22235#issuecomment-1621285983).

Although I understand that that's the code that was worked on in the PR that introduced the regression, what do you think about [my root cause analysis](https://github.com/Expensify/App/issues/22235#issuecomment-1621360204)?

Is it actually correct to pass report **A** and a report action from report **B** (a different report) to `ReportActionItem`?

From my perspective, the essence of the issue does _not_ lie in the  `toggleEmojiReaction` function, which is exactly the reason why the problem was easy to overlook during the review of the original PR.

**Comment by cubuspl42** [comment] 2023-07-05 18:11
@aimane-chnaif I understand. But it doesn't discard my proposal, right?

I understand that there might be some "traps" there, but if the overall reasoning is sound, it's an argument _for_ my proposal, not against it.

**Comment by stitesExpensify** [comment] 2023-07-05 19:46
@johncschuster Can we put this issue on hold for a bit? I'm trying to get [this pr](https://github.com/Expensify/App/pull/17996) merged which is going to touch the same code, and I don't want to accidentally revert any work done here

**Comment by johncschuster** [comment] 2023-07-06 13:54
@stitesExpensify sure thing! I'll put this on hold and downgrade to weekly.

**Comment by neil-marcellini** [comment] 2023-07-20 19:41
I'm confused. Let's discuss [on Slack](https://expensify.slack.com/archives/C01GTK53T8Q/p1689882049082489).

**Comment by johncschuster** [comment] 2023-08-01 23:20
### Summary for payments (will be updating shortly):
 External issue reporter - @gadhiyamanan - $250
 Contributor that fixed the issue - @jeet-dhandha
 Contributor+ that helped on the issue and/or PR - @aimane-chnaif

**Comment by neil-marcellini** [comment] 2023-08-04 23:55
not overdue

**Comment by neil-marcellini** [comment] 2023-08-07 18:25
Bump @johncschuster

**Comment by johncschuster** [comment] 2023-08-07 21:40
Thanks for the bump! I'll work on getting payment issued shortly!

**Comment by neil-marcellini** [comment] 2023-08-09 22:08
Not overdue on my side

**Comment by johncschuster** [comment] 2023-08-14 21:57
Eep! I'm sorry I let this one slip! Working on payment now!

**Comment by neil-marcellini** [comment] 2023-08-28 16:39
Now that we have a specific issue for payment I'm going to close this.

**Closed by neil-marcellini** 2023-08-28 16:39 UTC
Labels: External, Daily, Help Wanted, Overdue, Awaiting Payment, Bug
