### ISSUE TITLE
[HOLD for payment 2023-02-02] [$2000] Messages with itallic, bold and other formatting have lesser height than messages without them

### ISSUE THREAD

**Issue by kavimuru** [Expensify/App#13807] opened 2022-12-22 23:21 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:

1. Action Performed:
2. Open the app
3. Go to any chat
4. Write a message with 1 or 2 lines & send
5. Write the same message but use some formatting like *bold* in one of those lines & send
6. compare the heights of both messages and you'll notice the difference

## Expected Result:
The height should be more than or equal to the unformatted message but not less

## Actual Result:
Formatted message has lesser height than the unformatted message

## Workaround:
unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [ ] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 1.2.43-1
**Reproducible in staging?:** y 
**Reproducible in production?:** y
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** 

https://user-images.githubusercontent.com/43996225/209241274-8a46df8c-ab43-43ab-9ade-bac5af590163.mp4

<img width="960" alt="invalid workspace" src="https://user-images.githubusercontent.com/43996225/209241293-a02a0d20-3a74-4555-8888-2931d9159eee.png">

**Expensify/Expensify Issue URL:**
**Issue reported by:** @daraksha-dk 
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1671730788385549

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~010e5153b44f3c8eac</li>
        <li>Upwork Job ID: 1606321056386064384</li>
        <li>Last Price Increase: 2022-12-30</li>
    </ul>
</details>

**Comment by puneetlath** [comment] 2022-12-23 16:00
@Expensify/design can I get your perspective on this?

**Comment by shawnborton** [comment] 2022-12-23 16:03
Regular | Italic
----- | -----
<img width="348" alt="image" src="https://user-images.githubusercontent.com/2319350/209364507-038ef704-8823-48ed-86db-65d1a939bc01.png"> | <img width="350" alt="image" src="https://user-images.githubusercontent.com/2319350/209364457-58cc284a-2626-449d-90e3-b2c2207043e1.png">

Looks like we just need to make sure the `lineHeight: 20` is applied to all of the message styles, not just regular. So yeah, this is a bug and should be a very simple fix.

**Comment by tienifr** [comment] 2022-12-23 16:10
#Proposal

##Problem
If the comment is rendered by HTML, we will not set lineheight in style

##Solution
we add lineheight into comments that are rendered by HTML 
In https://github.com/Expensify/App/blob/bbec27295163843ca702aba289e4174d9669eda7/src/components/HTMLEngineProvider/BaseHTMLEngineProvider.js#L36

```diff
-         mixedUAStyles: {whiteSpace: 'pre'},
+        mixedUAStyles: {whiteSpace: 'pre', lineHeight: variables.lineHeightXLarge},
```

## Result


https://user-images.githubusercontent.com/113963320/209305651-d4890eeb-90cd-48c3-9482-6e5b6305d9c1.mov

**Comment by Pujan92** [comment] 2022-12-23 16:10
**Proposal**

Apply the `lineHeight` 20 to the renderer tags `em, del, strong`. If we apply to renderer `body` tag only for generic solution it applies to all block elements which isn't seems to be required for other tags. 

```diff
diff --git a/src/styles/styles.js b/src/styles/styles.js
index dd1496ea1..7fc9f2743 100644
--- a/src/styles/styles.js
+++ b/src/styles/styles.js
@@ -58,16 +58,19 @@ const webViewStyles = {
         em: {
             fontFamily: fontFamily.EXP_NEUE,
             fontStyle: 'italic',
+            lineHeight: variables.fontSizeNormalHeight,
         },
 
         del: {
             textDecorationLine: 'line-through',
             textDecorationStyle: 'solid',
+            lineHeight: variables.fontSizeNormalHeight,
         },
 
         strong: {
             fontFamily: fontFamily.EXP_NEUE,
             fontWeight: 'bold',
+            lineHeight: variables.fontSizeNormalHeight,
         },
 
         a: link,
```

**Comment by daraksha-dk** [comment] 2022-12-23 16:10
# Proposal
This is happening because we aren't applying line height for HTML rendered messages. It can be fixed by adding the line-height after https://github.com/Expensify/App/blob/main/src/styles/styles.js#L138
Eg.
`lineHeight: variables.fontSizeNormalHeight,`

**Comment by Pujan92** [comment] 2022-12-23 16:21
> **Proposal**
> 
> Apply the `lineHeight` 20 to the renderer tags `em, del, strong`. If we apply to renderer `body` tag only for generic solution it applies to all block elements which isn't seems to be required for other tags.

Eg. for anchor, code, ... tags `lineHeight` is not 20px in the original message and should not be for the renderer message too.

https://user-images.githubusercontent.com/14358475/209366898-0f74db42-3d5b-4c20-84a9-15f451fe80d6.mov

**Comment by wildan-m** [comment] 2022-12-27 09:27
### Proposal

### Root Cause

A comment with formatting rendered inside `RenderHTML`  not react `Text` component. `<comment>` tag inside `RenderHTML` doesn't specify line height by default.

### Solution

According to this comment:
https://github.com/Expensify/App/blob/f2a01fdb22c254e6e87dc32013ff9cd72c54e080/src/styles/styles.js#L52-L56

We can modify default comment style here:

```diff
diff --git a/src/styles/styles.js b/src/styles/styles.js
index 9fe3b62345..81b56458cb 100644
--- a/src/styles/styles.js
+++ b/src/styles/styles.js
@@ -129,6 +129,9 @@ const webViewStyles = {
             fontSize: variables.fontSizeLarge,
             marginBottom: 8,
         },
+        comment: {
+            lineHeight: variables.fontSizeNormalHeight,
+        }
     },
```

**Comment by mananjadhav** [comment] 2022-12-27 16:01
Sorry for the delay folks, I am travelling and I'll only be able to review these by tomorrow.

**Comment by wildan-m** [comment] 2022-12-27 22:49
Missed one thing, we should also add line-height if the chat reply source come from email (`email-comment`)

### Proposal (Updated)

### Root Cause

A comment with formatting rendered inside `RenderHTML`  not react `Text` component. `<comment>` and `<email-comment>` tag inside `RenderHTML` doesn't specify line height by default.

### Solution

According to this comment:
https://github.com/Expensify/App/blob/f2a01fdb22c254e6e87dc32013ff9cd72c54e080/src/styles/styles.js#L52-L56

We can modify the default `comment`/`email-comment` style here:

```diff
diff --git a/src/styles/styles.js b/src/styles/styles.js
index 9fe3b62345..0caa861b35 100644
--- a/src/styles/styles.js
+++ b/src/styles/styles.js
@@ -129,6 +129,12 @@ const webViewStyles = {
             fontSize: variables.fontSizeLarge,
             marginBottom: 8,
         },
+        comment: {
+            lineHeight: variables.fontSizeNormalHeight,
+        },
+        'email-comment': {
+            lineHeight: variables.fontSizeNormalHeight,
+        },
     },
 
     baseFontStyle: {
```

**Comment by mananjadhav** [comment] 2023-01-02 06:18
I was OOO for last week, I'll get to the review by today-tomorrow.

**Comment by mananjadhav** [comment] 2023-01-04 13:53
Went through all the proposals today. I am checking the HTML renderer and I'll update with my feedback in 1-2 hours.

Sorry for the delay folks, thanks for your patience here.

**Comment by mananjadhav** [comment] 2023-01-04 15:02
I went through the proposals and I also ran them against different styles. I have two questions for @shawnborton / @puneetlath / @Expensify/design. 

- We would want to put these line heights to the email comments too right?
- And the line height will apply to all the text in all the comments right?  or do we have any exceptions (code blocks, links, etc.?)

Based on my checks so far I think @wildan-m's proposal [here](https://github.com/Expensify/App/issues/13807#issuecomment-1366227786) should cover all the cases including the email case.

**Comment by s77rt** [comment] 2023-01-04 19:42
@mananjadhav Although @wildan-m 's solution seems to work I think it will create future regressions when trying to render a text with a fontSize that is bigger than 20px.

Currently the biggest font size we render in the messages seems to be 17px (`fontSizeLarge`) in a header message (markdown) so it's hard to catch any regression in this state.

You can test the future regression by setting the fontSize here https://github.com/Expensify/App/blob/main/src/styles/styles.js#L129 to 50px or so...

Same regression applies to the rest of the proposals.

___

No proposal is valid yet.

**Comment by mananjadhav** [comment] 2023-01-04 20:07
Thanks for the insights @s77rt. But I am not sure if we should be worried about future increase of the font-size for the time being. We might even revisit the line height too when we try to increase the font-size. We would also probably set the line-height to specific block renders in case we need that capability.

But now that's it is raised, I am going to let @shawnborton and @puneetlath comment on this.

**Comment by s77rt** [comment] 2023-01-04 20:14
@mananjadhav I think things will get messy when we combine multiple tags e.g. header with strikethrough.

**Comment by shawnborton** [comment] 2023-01-05 08:52
Yeah, I'm not too worried about the larger font sizes in the message text... for example, the h1 style - we can and should add a line height directly to that element. 

I think 20px should be used for everything, including email comments. That being said, is there a way to just wrap the comment area with something that will give children chat messages a line height of 20px rather than needing to make sure each child element has that style applied individually?

**Comment by wildan-m** [comment] 2023-01-05 09:40
@shawnborton, yeah, that's possible. line-height is an inherited property, adding `lineHeight: variables.lineHeightNormal` to `chatContentScrollView` will make all child line heights follow their parent's line-height by default.

Since it will affect all children, If we need to implement it this way we need to perform intensive tests.

```diff
diff --git a/src/styles/styles.js b/src/styles/styles.js
index 82e9ca8f2..16765fc71 100644
--- a/src/styles/styles.js
+++ b/src/styles/styles.js
@@ -1272,6 +1272,7 @@ const styles = {
      chatContentScrollView: {
          flexGrow: 1,
          justifyContent: 'flex-start',
          paddingVertical: 16,
+        lineHeight: variables.lineHeightNormal,
     },
 
     // Chat Item
```

**Comment by s77rt** [comment] 2023-01-05 09:43
@wildan-m That affects way more items than intended. @daraksha-dk proposal above does exactly @shawnborton is asking for.

But we are still having some formatting issues (my previous comment)

**Comment by wildan-m** [comment] 2023-01-05 09:55
@s77rt can you send me your test case? did you send these links in separate chat submissions or single submission?

*[1](http://google.com/)*
*[2](http://google.com/)*
*[3](http://google.com/)*

**Comment by s77rt** [comment] 2023-01-05 10:11
I have no idea what I have tried 😅

This is the case I'm talking about (in a one line message)
```
# *[1](http://google.com/)*
# *[2](http://google.com/)*
# *[3](http://google.com/)*
```

But apparently it's working fine, sorry for the false alert. 

@wildan-m any reasons we should go with your proposal instead of @daraksha-dk ?

**Comment by wildan-m** [comment] 2023-01-05 10:16
@s77rt I don't know which one is desired.

@shawnborton if we need to make `lineHeight: variables.lineHeightNormal` the default value for the entire app text, then we can go with @daraksha-dk, but if this is only scoped for message contents, then you can consider my proposal. cheers.

**Comment by puneetlath** [comment] 2023-01-06 01:16
@mananjadhav thoughts?

**Comment by mananjadhav** [comment] 2023-01-06 18:03
> I think 20px should be used for everything, including email comments

@shawnborton do you mean everywhere? Across the app? AboutPage, Workspace Invite pages, etc. ? The only reason I didn't go ahead with @daraksha-dk's proposal is because the `baseFontStyles` is something that will impact non chat screens as well. Can you confirm once?

If the scope is to only restrict this to the chat screens, I am still going ahead with @wildan-m's proposal. But if it is App-wide then we'll need a better proposal to cover that.

**Comment by mananjadhav** [comment] 2023-01-06 20:46
> The only other place where baseFontStyle is being used is on line.95 which is undefined 

Thanks for highlighting this. Yeah that was an oversight from my side. Considering both the `baseFontStyle` are different, it makes sense to use your proposal @daraksha-dk.

> > I think 20px should be used for everything, including email comments

> @shawnborton do you mean everywhere? Across the app? AboutPage, Workspace Invite pages, etc. ?

I'll still wait for @shawnborton to confirm if we want to set this anywhere else in the App apart from the messages.

Thank you for the patience here.

**Comment by s77rt** [comment] 2023-01-06 21:02
Just wanted to add that the `RenderHTML` is also used on other places besides the chat such as `src/components/FormAlertWrapper.js` and `src/components/Banner.js`

No a problem in my opinion since are also defining the font size there it makes sense to define the line height as well.

**Comment by shawnborton** [comment] 2023-01-08 18:15
I don't think I would make **everything** in the app use `lineHeight: 20` just yet. For now, let's just start by using that as the default line height for chat messages.

**Comment by mananjadhav** [comment] 2023-01-08 18:37
Thanks for the confirmation @shawnborton.

I think then @daraksha-dk's proposal [here](https://github.com/Expensify/App/issues/13807#issuecomment-1364079871) makes sense. @daraksha-dk quick feedback on when you share proposals you should share the permalink of the actual line you're modifying and not outside the given block. Because here it is confusing whether you'll put `lineHeight`, inside the `baseFontStyles` or outside. Also avoid using words like `e.g.` for the code changes you proposal.  Once again, thanks for the patience here.


@puneetlath all yours.

**Comment by wildan-m** [comment] 2023-01-09 00:54
### Proposal (Alternative)

Hi, we should make the text behavior between Expensify's `Text` component and `RenderHTML` `Text` element consistent, right?

If we check our custom `Text` component, then we'll notice that the `lineHeight` is added conditionally when the `componentStyle.fontSize === variables.fontSizeNormal`

https://github.com/Expensify/App/blob/a53b274c7091aa25c1cccb8cab578967061b66fb/src/components/Text.js#L61-L63

### Solution
We can replace `react-native-render-html`'s Text component with Expensify's custom Text component.

setting `baseStyle` will not work, since we have to detect the current text `fontSize`.

We can create a custom text renderer that will override `Text` component inside `RenderHTML`

We can apply this custom renderer to our custom tags. 
```
    comment: TextRenderer,
    'email-comment': TextRenderer,
    'muted-text': TextRenderer,
```

if required, we can apply it globally to all [HTML text formatting tags](https://www.w3schools.com/html/html_formatting.asp) and heading tags.

cc: @mananjadhav, @puneetlath 
### Required Changes

```diff
diff --git a/src/components/HTMLEngineProvider/HTMLRenderers/index.js b/src/components/HTMLEngineProvider/HTMLRenderers/index.js
index 4b9d0fc85..37c80203e 100644
--- a/src/components/HTMLEngineProvider/HTMLRenderers/index.js
+++ b/src/components/HTMLEngineProvider/HTMLRenderers/index.js
@@ -3,6 +3,7 @@ import CodeRenderer from './CodeRenderer';
 import EditedRenderer from './EditedRenderer';
 import ImageRenderer from './ImageRenderer';
 import PreRenderer from './PreRenderer';
+import TextRenderer from './TextRenderer';
 
 /**
  * This collection defines our custom renderers. It is a mapping from HTML tag type to the corresponding component.
@@ -16,4 +17,7 @@ export default {
     // Custom tag renderers
     edited: EditedRenderer,
     pre: PreRenderer,
+    comment: TextRenderer,
+    'email-comment': TextRenderer,
+    'muted-text': TextRenderer,
 };
```

TextRenderer.js
```
import _ from 'underscore';
import React from 'react';
import htmlRendererPropTypes from './htmlRendererPropTypes';
import Text from '../../Text';
import  { getNativePropsForTNode, splitBoxModelStyle } from 'react-native-render-html';

const TextRenderer = (props) => {
    const nativeProps = getNativePropsForTNode(props);

    // We split wrapper and inner styles
    // "boxModelStyle" corresponds to border, margin, padding and backgroundColor
    const {boxModelStyle, otherStyle: textStyle} = splitBoxModelStyle(props.style);


    const defaultRendererProps = _.omit(nativeProps, ['style']);
    // This is equivalent to a TDefaultRenderer which `Text` is replaced
    // with custom Expensify `Text` component 
    return <Text style={{...boxModelStyle, ...textStyle}} {...defaultRendererProps}/>;
};

TextRenderer.propTypes = htmlRendererPropTypes;
TextRenderer.displayName = 'TextRenderer';

export default TextRenderer;
```

**Comment by wildan-m** [comment] 2023-01-09 18:37
@daraksha-dk, sorry for my unclear sentence, I mean I can't find a way to make conditional styling by using `baseStyle`.

> @wildan-m, can you share any instances where it's not working?

No actual example with the current `RenderHTML` usage. All `RenderHTML` usage currently uses fontSizeNormal.

But, if we look at this conditional line-height addition, then if there is `comment` item that use font with non-normal size, then they shouldn't have line height by default.

https://github.com/Expensify/App/blob/a53b274c7091aa25c1cccb8cab578967061b66fb/src/components/Text.js#L61-L63

Consider this test case using `baseStyle`:

<details><summary>Image 1 - Rendered with text component, font size normal, line height added with 20px</summary>
<img width="1488" alt="Screenshot 2023-01-10 at 00 56 14" src="https://user-images.githubusercontent.com/11847279/211379368-fb2dea18-f83b-41b6-8d10-17258d20d315.png">
</details>

<details><summary>Image 2 - Rendered with RenderHTML, font size normal, line height added with 16px</summary>
<img width="1487" alt="Screenshot 2023-01-10 at 00 57 26" src="https://user-images.githubusercontent.com/11847279/211380107-22b45dd6-c1cb-4292-964c-4aa52d1efd81.png">
</details>

1st issue:
Notice that the line height value added is different`fontSizeNormal: getValueUsingPixelRatio(15, 21)` behaves differently when passed through RenderHTML and when we use it through `<Text>` component. If we hardcode the value (e.g. 20px), then they have the same value

<details><summary>Image 3 - Rendered with text component, font size large, line height: normal</summary>
<img width="1494" alt="Screenshot 2023-01-10 at 00 51 14" src="https://user-images.githubusercontent.com/11847279/211380317-034d08d4-54a6-4ef0-8318-0165c669c40b.png">
</details>

<details><summary>Image 4 - Rendered with RenderHTML, font size large, line height: 16 px</summary>
<img width="1488" alt="Screenshot 2023-01-10 at 00 53 44" src="https://user-images.githubusercontent.com/11847279/211380559-0035875f-e3ec-4f93-b08f-3ace762ac865.png">
</details>

2nd issue:
In Image 3, conditional logic works as expected, the line-height value is `normal`, it means `<Text>` component doesn't add any lineHeight value

When we use RenderHTML (Image 4), the lineHeight keeps 16px. It's expected because we are not set any conditional styling there, and it makes the styling behaviour inconsistent


### Complete test case

<details>
  <summary>Test Case 1 fontSizeNormal</summary>

```diff
diff --git a/src/components/Header.js b/src/components/Header.js
index a69317122..6339b218b 100644
--- a/src/components/Header.js
+++ b/src/components/Header.js
@@ -5,6 +5,7 @@ import _ from 'underscore';
 import styles from '../styles/styles';
 import Text from './Text';
 import EnvironmentBadge from './EnvironmentBadge';
+import RenderHTML from './RenderHTML';
 
 const propTypes = {
     /** Title of the Header */
@@ -30,8 +31,16 @@ const Header = props => (
     <View style={[styles.flex1, styles.flexRow]}>
         <View style={styles.mw100}>
             <Text numberOfLines={2} style={[styles.headerText, styles.textLarge, ...props.textStyles]}>
-                {props.title}
+                    {props.title}
             </Text>
+
+            <Text style={styles.textNormal}>
+                Rendered with Text Component
+            </Text>
+
+            <RenderHTML html={`<p>Rendered With RenderHTML</p>`} />
+
+
             {/* If there's no subtitle then display a fragment to avoid an empty space which moves the main title */}
             {_.isString(props.subtitle)
                 ? Boolean(props.subtitle) && <Text style={[styles.mutedTextLabel]} numberOfLines={1}>{props.subtitle}</Text>
diff --git a/src/styles/styles.js b/src/styles/styles.js
index 47ca20888..6dc55944d 100644
--- a/src/styles/styles.js
+++ b/src/styles/styles.js
@@ -129,6 +129,7 @@ const webViewStyles = {
         p: {
             marginTop: 0,
             marginBottom: 0,
+            fontSize: variables.fontSizeNormal,
         },
         h1: {
             fontSize: variables.fontSizeLarge,
@@ -141,6 +142,7 @@ const webViewStyles = {
         fontSize: variables.fontSizeNormal,
         fontFamily: fontFamily.EXP_NEUE,
         flex: 1,
+        lineHeight: variables.lineHeightNormal,
     },
 };
 
@@ -258,6 +260,10 @@ const styles = {
         fontSize: variables.fontSizeExtraSmall,
     },
 
+    textNormal: {
+        fontSize: variables.fontSizeNormal,
+    },
+
     textLarge: {
         fontSize: variables.fontSizeLarge,
     },
```
</details>
<details><summary>Test case 2 fontSizeLarge</summary>

```diff
diff --git a/src/components/Header.js b/src/components/Header.js
index a69317122..b49575f6a 100644
--- a/src/components/Header.js
+++ b/src/components/Header.js
@@ -5,6 +5,7 @@ import _ from 'underscore';
 import styles from '../styles/styles';
 import Text from './Text';
 import EnvironmentBadge from './EnvironmentBadge';
+import RenderHTML from './RenderHTML';
 
 const propTypes = {
     /** Title of the Header */
@@ -30,8 +31,16 @@ const Header = props => (
     <View style={[styles.flex1, styles.flexRow]}>
         <View style={styles.mw100}>
             <Text numberOfLines={2} style={[styles.headerText, styles.textLarge, ...props.textStyles]}>
-                {props.title}
+                    {props.title}
             </Text>
+
+            <Text style={styles.textLarge}>
+                Rendered with Text Component
+            </Text>
+
+            <RenderHTML html={`<p>Rendered With RenderHTML</p>`} />
+
+
             {/* If there's no subtitle then display a fragment to avoid an empty space which moves the main title */}
             {_.isString(props.subtitle)
                 ? Boolean(props.subtitle) && <Text style={[styles.mutedTextLabel]} numberOfLines={1}>{props.subtitle}</Text>
diff --git a/src/styles/styles.js b/src/styles/styles.js
index 47ca20888..6df2eebaa 100644
--- a/src/styles/styles.js
+++ b/src/styles/styles.js
@@ -129,6 +129,7 @@ const webViewStyles = {
         p: {
             marginTop: 0,
             marginBottom: 0,
+            fontSize: variables.fontSizeLarge,
         },
         h1: {
             fontSize: variables.fontSizeLarge,
@@ -141,6 +142,7 @@ const webViewStyles = {
         fontSize: variables.fontSizeNormal,
         fontFamily: fontFamily.EXP_NEUE,
         flex: 1,
+        lineHeight: variables.lineHeightNormal,
     },
 };
 
@@ -258,6 +260,10 @@ const styles = {
         fontSize: variables.fontSizeExtraSmall,
     },
 
+    textNormal: {
+        fontSize: variables.fontSizeNormal,
+    },
+
     textLarge: {
         fontSize: variables.fontSizeLarge,
     },

```

</details>

**Comment by puneetlath** [comment] 2023-01-12 19:22
@mananjadhav thoughts?

**Comment by puneetlath** [comment] 2023-01-12 23:23
@puneetlath @mananjadhav this issue is now 3 weeks old. There is one more week left before this issue <a href='https://stackoverflowteams.com/c/expensify/questions/15233/15234#15234'>breaks WAQ</a> and will need to go internal. What needs to happen to get a PR in review this week? Please create a thread in #expensify-open-source to discuss. Thanks!

**Comment by mananjadhav** [comment] 2023-01-16 04:22
Apologies for the delay here, I'll check this today.

**Comment by thesahindia** [comment] 2023-01-16 14:12
Coming from https://github.com/Expensify/App/issues/14261. Just looked into the proposals and I think updating `baseFontStyle` is a better Idea. I think it will also handle the future cases if we introduce something new.

**Comment by mananjadhav** [comment] 2023-01-16 15:40
Thanks for the detailed feedback and proposal @wildan-m. I think we would keep things straight forward right now and not get into conditional formatting. @shawnborton did already mention we should ignore the `Header` and `###`.

@puneetlath I think we're good with @daraksha-dk's proposal.

**Comment by puneetlath** [comment] 2023-01-16 18:15
I agree with that. I think this has been a great discussion that has helped us have confidence in that solution. Thanks to all involved! 

@daraksha-dk please let us know when you think you can have a PR up and ready for review.

**Comment by mananjadhav** [comment] 2023-01-18 02:53
Thanks @daraksha-dk, I'll test this today.

**Comment by puneetlath** [comment] 2023-01-30 18:18
@mananjadhav would you be able to help with narrowing down the cause for this bug?

**Comment by mananjadhav** [comment] 2023-02-01 19:30
@puneetlath I did attempt to check the offending PR, but I couldn't find one. The line-heights have not been consistent since a long time (probably since the beginning). I did check out previous versions of HTML renderer and the difference in the line heights exist in every iteration.

**Comment by puneetlath** [comment] 2023-02-01 23:08
Yeah makes sense. I think this has been the case from the beginning.

**Comment by puneetlath** [comment] 2023-02-01 23:11
Looks like the last job expired. @mananjadhav @daraksha-dk can you apply to this one? https://www.upwork.com/jobs/~01cf8518969fbebe7f

**Comment by mananjadhav** [comment] 2023-02-02 02:31
Applied @puneetlath

**Comment by puneetlath** [comment] 2023-02-02 17:20
Sent both hiring offers. 

For the record, I will be giving 50% bonus on this one. The PR was ready, just didn't get merged in time due to me being OOO.

**Comment by mananjadhav** [comment] 2023-02-02 17:23
Thanks @puneetlath

**Closed** 2023-02-02 17:31 UTC
Labels: External, Weekly, Awaiting Payment, Bug
