### ISSUE TITLE
[$1000] Web – Inconsistent order of items in FAB (New) and Actions in composer.

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#22365] opened 2023-07-06 18:50 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Open any chat
2. Click the “Actions” plus sign in composer
3. Notice that the order of items are from top “Request Money”, “Send Money” & “Assign Task”.
4. Now click FAB “New” on left side.
5. Notice that the order of items that are present in the composer too, are from top “Send Money”, “Request Money” & “Assign Task”.

## Expected Result:
The order of items should be consistent in both cases to maintain uniformity.

## Actual Result:
Inconsistent order of items in FAB (New) and Actions in composer.

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [x] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 1.3.37-2
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation
![1](https://github.com/Expensify/App/assets/93399543/8d1155fc-862e-42dc-8b94-2807ec8bb506)
![2](https://github.com/Expensify/App/assets/93399543/32d9fdfd-8640-41a5-a98f-27eb23d31531)

https://github.com/Expensify/App/assets/93399543/d110e702-a80e-4c15-907e-e8911a97992d

**Expensify/Expensify Issue URL:**
**Issue reported by:** @usmantariq96
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1688634881745739

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~0186ae3955d5311248</li>
        <li>Upwork Job ID: 1679469922899808256</li>
        <li>Last Price Increase: 2023-07-13</li>
    </ul>
</details>

**Comment by dylanexpensify** [comment] 2023-07-10 09:42
Will review today!

**Comment by dylanexpensify** [comment] 2023-07-12 08:42
Reviewing today, got caught up sorry!

**Comment by narefyev91** [comment] 2023-07-13 13:14
Proposal from @namhihi237 looks good to me https://github.com/Expensify/App/issues/22365#issuecomment-1624164996
🎀 👀 🎀 C+ reviewed

**Comment by integrITsolutions** [comment] 2023-07-13 18:49
### **Proposal**

**Please re-state the problem that we are trying to solve in this issue.**

The order of items in the Composer FAB and the Report Options is not the same

**What is the root cause of that problem?**

The item order for FAB button is defined [here](https://github.com/Expensify/App/blob/29caf708887752310a796c66d76db6656c8ee951/src/pages/home/sidebar/SidebarScreen/FloatingActionButtonAndPopover.js#L175C1-L175C33)

The possible Options in the Report are defined as object [here](https://github.com/Expensify/App/blob/29caf708887752310a796c66d76db6656c8ee951/src/pages/home/report/ReportActionCompose.js#L387C9-L387C9). These options are mapped against the function ReportUtils.getMoneyRequestOptions. 
The order of items for the Option pane is therefore determined by the order of returned options of this function [here](https://github.com/Expensify/App/blob/29caf708887752310a796c66d76db6656c8ee951/src/libs/ReportUtils.js#L2258C4-L2258C4).

The entries of the returned array of allowed Options are in different order than the Option list specified for the Composer FAB, resulting in inconsistent appearance. 

**What changes do you think we should make in order to solve the problem?**

Updating the function ReportUtils.getMoneyRequestOptions to return the Option array in order of the FAB Options. 

Result:


https://github.com/Expensify/App/assets/139258421/348514c1-fcb4-4ef2-8840-7388d0a70372

**Comment by integrITsolutions** [comment] 2023-07-13 20:57
Contributor details
Your Expensify account email: [development@integritsol.de](mailto:development@integritsol.de)
Upwork Profile Link: https://www.upwork.com/freelancers/~01ec3e40c95bfc76c9?viewMode=1

**Comment by integrITsolutions** [comment] 2023-07-13 20:59
Contributor details
Your Expensify account email: development@integritsol.de
Upwork Profile Link: https://www.upwork.com/freelancers/~01ec3e40c95bfc76c9

**Comment by PauloGasparSv** [comment] 2023-07-15 12:26
Hey @dylanexpensify @narefyev91 I'm going OOO for 2 weeks (starting on July 17th, back on July 31st) so can we re-assign this to another engineer?

**Comment by narefyev91** [comment] 2023-07-17 07:37
🎀 👀 🎀 C+ reviewed

**Comment by narefyev91** [comment] 2023-07-17 07:58
@dhairyasenjaliya you are right - i think @mountiny we can close this one

**Comment by mountiny** [comment] 2023-07-17 14:22
Actually not sure if that is important, going to go ahead and close this one out

**Closed by mountiny** 2023-07-17 14:22 UTC
Labels: External, Daily, Help Wanted, Bug
