### ISSUE TITLE
Web - Workspace name overflows when too long on report detail page

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#22894] opened 2023-07-14 14:26 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Create a workspace
2. Update long name workspace
3. Go #admin room
4. Click header of room, observed that the workspace name is overflowing

## Expected Result:
The name of the workspace is not overflowed

## Actual Result:
Workspace name is overflowing

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [x] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 1.3.40-5
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/93399543/fb42b1a2-dee7-4c32-9fb1-9cf844e65f1c

https://github.com/Expensify/App/assets/93399543/e033b5ff-bbce-45eb-86ad-563dce8c862f

**Expensify/Expensify Issue URL:**
**Issue reported by:** @namhihi237
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1689288910992129

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by kbecciv** [comment] 2023-07-14 14:27
## Proposal
by: @namhihi237
### Please re-state the problem that we are trying to solve in this issue.
The name of the workspace is not overflowed
### What is the root cause of that problem?
We haven't styled it in case the workspace name is too long.
https://github.com/Expensify/App/blob/2454ea88b15ec4bb6216a2b61acb294b9573fb20/src/pages/ReportDetailsPage.js#L159-L168
### What changes do you think we should make in order to solve the problem?
We can do the same [WorkspaceInitialPage](https://github.com/Expensify/App/blob/2454ea88b15ec4bb6216a2b61acb294b9573fb20/src/pages/workspace/WorkspaceInitialPage.js#L230C36-L243C76)
```javascript
<PressableWithoutFeedback
   style={[ styles.w100]}
>
    <Text
        numberOfLines={1}
        style={[styles.alignSelfCenter, styles.pre]}
    >
       {chatRoomSubtitleText}
    </Text>
</PressableWithoutFeedback>
```
### What alternative solutions did you explore? (Optional)
We can show full name and drop line if we need show full

**Comment by zaitsev1** [comment] 2023-07-15 16:39
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
The issue you're trying to solve involves a parent container with certain styles and a child element with text that goes beyond the boundaries of the parent. 

### What is the root cause of that problem?
The `align-items: center;` property aligns the child elements vertically within the parent container along the cross-axis, which in the case of `flex-direction: column;` is the horizontal axis.

When you remove `align-items: center;` the default behavior is applied, which is `align-items: stretch;`. This causes the child elements to stretch horizontally to fill the width of the parent container, including any extra space.

By adding `align-items: center;`, the child elements are centered along the horizontal axis, and they no longer stretch to fill the parent's width. This can result in the text within the child element extending beyond the parent's boundaries if the text is wider than the available space.

### What changes do you think we should make in order to solve the problem?

To prevent the child text from overflowing, you can either remove `...flex.alignItemsCenter` here:

https://github.com/Expensify/App/blob/b9508b616f3a7229365c8bd7280fd1e34cfd2f9b/src/styles/styles.js#L2160-L2165


https://github.com/Expensify/App/assets/32131367/cc2dfbb5-5b56-4fbd-bf31-fa346dcfe768

**Comment by flaviadefaria** [comment] 2023-07-17 11:51
Closing as this is a dupe.

**Closed by flaviadefaria** 2023-07-17 11:51 UTC
Labels: Daily, Overdue, Bug
