### ISSUE TITLE
[ON HOLD #47203] [HIGH] [$500] mWeb - Composer-App crashes/freezes when pasting copied image inside the compose box

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#36909] opened 2024-02-20 15:36 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.43.0
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:** https://expensify.testrail.io/index.php?/tests/view/4331256
**Issue reported by:** Applause - Internal Team

## Action Performed:
1. Go inside your device gallery and copy an image to your clipboard
2. Open ND app and click inside the compose box and hold down until you see the option to paste
3. Click on paste
4. While the app is stuck try to interact with the app (for example try to close the keyboard, click inside the compose box or anywhere)

## Expected Result:
App should function normally and paste the image

## Actual Result:
App freezes and then crashes eventually

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [ ] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

https://github.com/Expensify/App/assets/93399543/c64d8936-b87c-432b-96bd-2d7351334738

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~0131dabafc5db30095</li>
        <li>Upwork Job ID: 1761017840885219328</li>
        <li>Last Price Increase: 2024-08-21</li>
    </ul>
</details>

**Comment by kbecciv** [comment] 2024-02-20 15:36
@CortneyOfstad I haven't added the External label as I wasn't 100% sure about this issue. Please take a look and add the label if you agree it's a bug and can be handled by external contributors.

**Comment by CortneyOfstad** [comment] 2024-02-23 13:18
Thanks @kbecciv! I've been diving into this and I think that this could be handled by an external contrubutor 👍

**Comment by CortneyOfstad** [comment] 2024-02-23 13:21
@eh2077 Please let me know if you have any concerns about this potentially being a BE Issue, and we can get that tags switched. From what I could see, it appears not to be, but would love fresh eyes just in case 👍

**Comment by eh2077** [comment] 2024-02-23 13:25
@CortneyOfstad Yeah, this is most likely an issue from frontend.

**Comment by CortneyOfstad** [comment] 2024-02-26 15:29
Posted in VIP-VSB [here](https://expensify.enterprise.slack.com/archives/C066HJM2CAZ/p1708961346874919)

**Comment by CortneyOfstad** [comment] 2024-02-28 17:05
Going to reach out to CallStack to see if someone can take this on 👍

**Comment by CortneyOfstad** [comment] 2024-02-28 17:08
Post to CS [here](https://expensify.slack.com/archives/C03UK30EA1Z/p1709140075724409)

**Comment by eh2077** [comment] 2024-03-05 09:44
@badeggg Thanks for looking into this! I think the photo app is [Samsung Gallery](https://galaxystore.samsung.com/prepost/000005627043).

**Comment by eh2077** [comment] 2024-03-05 09:49
@CortneyOfstad I found that, according to the video, the issue happens in `Android: native` platform. Kindly help to edit the issue if needed.

**Comment by kacper-mikolajczak** [comment] 2024-03-05 11:31
Hi @CortneyOfstad 👋 I am Kacper from Callstack team and I would like to investigate the issue! 🔧

**Comment by kacper-mikolajczak** [comment] 2024-03-05 17:45
As a follow-up on **freezing behaviour**, I could not replicate that on my end. 

@kbecciv Could you share more specific info about device you've encountered the bug on? Tomorrow I can ask a colleague with different physical devices to test it as well to see if it is device-specific.

**Comment by eh2077** [comment] 2024-03-06 07:16
@kacper-mikolajczak Thanks for your investigation! I also tested it on iOS App and mobile Safari and below are the summary comparison about the image pasting feature. Android videos are from @kacper-mikolajczak 's comment.

|   | Video | Has paste option? | Able to paste image? |
| ------------- | ------------- | ------------- | ------------- |
| Android App | <video height="100" src="https://private-user-images.githubusercontent.com/62747088/310125614-68ccf88e-f92d-4244-900d-756b1958328d.mov?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDk3MDc3OTcsIm5iZiI6MTcwOTcwNzQ5NywicGF0aCI6Ii82Mjc0NzA4OC8zMTAxMjU2MTQtNjhjY2Y4OGUtZjkyZC00MjQ0LTkwMGQtNzU2YjE5NTgzMjhkLm1vdj9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMDYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzA2VDA2NDQ1N1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWM2ZjgwNTdiNWNjNTNiMjI2NmYyMGZjYzI0MTQ2NDY1MTRlNDc4OGQ1YTU2MGEwNTk3NGFkMjMxMjZiNzQ5YzcmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.EEv072sjOf9JjrPKquUeJ4YIEEDKMEaiLJggNENhstk">  | Yes | No |
| Android mobile Chrome | <video height="100" src="https://private-user-images.githubusercontent.com/62747088/310128150-2a3586ba-68bb-4cd0-88de-6516eb1fd459.mov?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDk3MDc3OTcsIm5iZiI6MTcwOTcwNzQ5NywicGF0aCI6Ii82Mjc0NzA4OC8zMTAxMjgxNTAtMmEzNTg2YmEtNjhiYi00Y2QwLTg4ZGUtNjUxNmViMWZkNDU5Lm1vdj9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMDYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzA2VDA2NDQ1N1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTZlZDNmOWFmZDUzNzc4Y2I2Mjk0ZDFiMjMzMzJiNjlmMGM1ZDYxZWUwNmIwODlkOTRjY2Y0Y2RlZTEyOWQzOGMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.VOnX4w_wiywOYlIHHEkL5rJoFBEJTEIeMzkmamOeidc">| Yes | Yes |
| iOS App | <video height="100" src="https://github.com/Expensify/App/assets/117511920/1b83e7da-c60e-40d7-a2aa-fc9bfd386b1c"> | No | No |
| iOS mobile Safari (with video of Simulator) | <video height="100" src="https://github.com/Expensify/App/assets/117511920/086a41e6-bca5-4d6f-941c-ee0a91803188"> | Yes | Yes |
| iOS mobile Safari (Physical device) | NA | No | No |

**Comment by eh2077** [comment] 2024-03-06 07:27
@CortneyOfstad One thing is clear - In native platforms (iOS and Android), pasting image to composer isn't explicitly supported in our codebase. So I guessed the crash only happens on specific type of Android device.

**Comment by mountiny** [comment] 2024-03-07 09:50
@kacper-mikolajczak i would say that from perspective of cross platform consistency we should make the native apps work the same as web

How complicated is to achieve it?

**Comment by kacper-mikolajczak** [comment] 2024-03-07 18:26
Hi @mountiny 👋 

Currently RN core `TextInput` component does not support file pasting functionality. There is an [old PR](https://github.com/facebook/react-native/pull/22794) where the discussion was held and they concluded it should not be part of the core.

One of the open source alternatives I found is the [react-native-paste-input](https://github.com/mattermost/react-native-paste-input) library which does exactly what is says - extends basic TextInput with paste functionality. 

After implementing it in POC it seems fine. Please keep in mind I have not tested it thoroughly enough and we should consider other aspects when replacing core components with their third-party counterparts (like lifespan, compatibility and DX)

Here are the recordings on iOS:

https://github.com/Expensify/App/assets/62747088/69d59b43-8276-46e4-8e25-ef6c93d8f031

and Android platforms:

https://github.com/Expensify/App/assets/62747088/f6620b6d-8dcb-4265-80d7-e5c672e76f8e


Let me know what you think 🔧

**Comment by mountiny** [comment] 2024-03-08 17:39
@kacper-mikolajczak thank you! I would say that if we need to bring new library for this we can omit this for now to focus on other initiatives.

**Comment by mountiny** [comment] 2024-03-08 17:41
So otherwise we confirmed this works and does not crash or freeze on web or mweb? Only on native this feature does not exist yet

**Comment by kacper-mikolajczak** [comment] 2024-03-11 08:11
@mountiny That's correct

**Comment by eh2077** [comment] 2024-03-11 10:03
> So otherwise we confirmed this works and does not crash or freeze on web or mweb? Only on native this feature does not exist yet

@mountiny Yeah, per my test on simulator and physical device, I also didn't find crash or freeze issue on web or mweb.

**Comment by mountiny** [comment] 2024-03-11 14:29
Waiting for resolution of the discussion whether we will want to bring this to feature parity even given its not straightforward or skip for now

**Comment by eh2077** [comment] 2024-03-14 07:44
Not overdue, we're waiting for the resolution of internal discussion.

**Comment by mountiny** [comment] 2024-03-15 14:14
Discussed with @trjExpensify too, for now I think we can close this, its not that often used feature and we can spend our time in better manner now so closing and we can reopen once we ready to implement this

**Comment by lanitochka17** [comment] 2024-08-14 13:38
Issue is still reproducible on the latest build 9.0.20-2

https://github.com/user-attachments/assets/cfdf3e77-978d-4b0b-ab05-48151ed05e94

**Comment by eh2077** [comment] 2024-08-14 15:32
Did https://github.com/Expensify/App/issues/41239 solve this issue?

**Comment by CortneyOfstad** [comment] 2024-08-19 14:01
Still waiting for https://github.com/Expensify/App/pull/47203 to hit production, so going to put this on-hold

**Comment by CortneyOfstad** [comment] 2024-08-21 18:05
Okay, botify is sick, so the move to production was done manually without an update to the PR. It went into Production 2 days, ago so the 7-day wait period is over on Aug. 26!

**Comment by mvtglobally** [comment] 2024-08-23 12:06
Issue not reproducible during KI retests. (First week)

**Comment by CortneyOfstad** [comment] 2024-08-26 13:39
The hold period for production has been completed so this can be closed!

**Closed by CortneyOfstad** 2024-08-26 13:39 UTC
Labels: External, Engineering, Daily, Help Wanted, Overdue, Bug

**Comment by s77rt** [comment] 2024-08-26 19:48
Let's keep this one open, it seems to be reproducible on Samsung devices only. cc @ahmedGaber93 can you please confirm this is still reproducible from your end

**Comment by ahmedGaber93** [comment] 2024-08-28 01:55
> can you please confirm this is still reproducible from your end

It reproduced on production, and I will retest the latest main branch today.

**Comment by ahmedGaber93** [comment] 2024-08-29 10:20
@s77rt The feature itself is not working with me on android (on both emulator and real device) after RN upgrading to 0.75.2.


https://github.com/user-attachments/assets/b996f1e1-db0b-4039-b1a5-f9bba951628e

**Comment by s77rt** [comment] 2024-08-29 10:35
@ahmedGaber93 Can you try remove the `node_modules/react-native` folder and reinstall, it's possible that the patch is not being applied in your case

**Comment by ahmedGaber93** [comment] 2024-08-29 10:41
> Can you try remove the node_modules/react-native folder and reinstall, it's possible that the patch is not being applied in your case

@s77rt Yes, I already did that before the build. And I think the patch is applied correctly because it works fine on iOS

**Comment by s77rt** [comment] 2024-08-30 20:50
@ahmedGaber93 The patch fix https://github.com/Expensify/App/pull/48370

**Comment by ahmedGaber93** [comment] 2024-09-02 16:40
> can you please confirm this is still reproducible from your end

@s77rt Yes, it still reproduced
