### ISSUE TITLE
[$1000] Inconsitent navigation between mobile back button and app back button

### ISSUE THREAD

**Issue by kavimuru** [Expensify/App#22683] opened 2023-07-11 20:00 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Open the app
2. Open any report
3. Send any workspace card link which you don't have access to eg: https://staging.new.expensify.com/workspace/B805344AD61EAEF58/card
4. It should display 'Hmm its not here' page, user back button provided by app and observe that it opens workspaces list -> settings and then back
5. Again click on link, on 'Hmm its not here' page, use back button of your device and observe that it goes back to chat
## Expected Result: 
App should maintain consistency between device back button navigation and app back button navigation
## Actual Result: 
On opening card page of workspace which we don't have access, app does not maintain consistency between device back button navigation and app back button navigation
## Workaround:
Can the user still use Expensify without this being fixed? Have you informed them of the workaround?

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [x] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [ ] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 1.3.39-5
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/43996225/8a7b530b-9757-4aa2-b948-860051efdb64

https://github.com/Expensify/App/assets/43996225/a5b50b92-4d95-4988-95f1-be777aea2084

**Expensify/Expensify Issue URL:**
**Issue reported by:** @dhanashree-sawant
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1689087227900569

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~016b63fbafa9a57cb7</li>
        <li>Upwork Job ID: 1679157221242437632</li>
        <li>Last Price Increase: 2023-07-12</li>
    </ul>
</details>

**Comment by rojiphil** [comment] 2023-07-12 21:12
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
For the mentioned steps, the device back button navigation and app back button navigation must behave consistently. In this case, app back button must behave like device back button.

### What is the root cause of that problem?
The root cause of the problem is that we are forcefully navigating to fallback route when the RightModalNavigator does not have state and routes within.

### What changes do you think we should make in order to solve the problem?
Let the actual active route index be returned instead of setting it to 0. 
The following changes can be made in [navigation.js](https://github.com/Expensify/App/blob/03740c42ad316c082794027b11d7a7c7fef7e84a/src/libs/Navigation/Navigation.js#L65C1-L67C6) so that `navigationRef.current.goBack` gets called so that app back button and device back button behave consistently.

```
-    if (route.name === NAVIGATORS.RIGHT_MODAL_NAVIGATOR) {
-        return 0;
-    }
```

### What alternative solutions did you explore? (Optional)

**Comment by mountiny** [comment] 2023-07-13 21:54
This is expected behaviour. the UP button in top left corner is not same as browser back button

I am going to close this issue out

**Closed by mountiny** 2023-07-13 21:54 UTC
Labels: External, Daily, Help Wanted, Overdue, Bug
