### ISSUE TITLE
[HOLD #34692] [VIP-VSB] [$500] Web - Task - Empty user shows up on share somewhere list

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#36492] opened 2024-02-14 14:34 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.41.0
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:** https://expensify.testrail.io/index.php?/tests/view/4311499
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** Applause - Internal Team
**Slack conversation:**

## Action Performed:
1. Navigate to https://staging.new.expensify.com/a/14931991
2. Click on Message with share code tests
3. Click on FAB > Assign tasks > Give title > Click on share somewhere
4. Observe the list of users

## Expected Result:
Share code tests account should be shown with its avatar and its name

## Actual Result:
Share code tests account shows up with an empty name

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

https://github.com/Expensify/App/assets/93399543/3e0a2c01-fb1f-445c-a61d-71223d254bb3

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01b7f4ea28196d6fab</li>
        <li>Upwork Job ID: 1757775322633478144</li>
        <li>Last Price Increase: 2024-02-14</li>
    </ul>
</details>

**Comment by kbecciv** [comment] 2024-02-14 14:34
We think that this bug might be related #vip-vsb
CC @quinthar

**Comment by strepanier03** [comment] 2024-02-15 00:25
Repro'd 
<img width="750" alt="image" src="https://github.com/Expensify/App/assets/10925636/49e948bd-5006-4031-ba05-6214f5bac9b6">

**Comment by Tony-MK** [comment] 2024-02-17 02:16
## Proposal

### Please re-state the problem that we are trying to solve in this issue.

### What is the root cause of that problem?

The `accountIDs` array is taken from the `report.visibleChatMemberAccountIDs` and it is empty.

https://github.com/Expensify/App/blob/3ab4e6e12d9ff38e69493321f0d31f032481b373/src/libs/OptionsListUtils.ts#L1457

In the [`createOption`](https://github.com/Expensify/App/blob/6b4246158acd8d202e83668313630fa14b24fedb/src/libs/SidebarUtils.ts#L260), the `getPersonalDetailsForAccountIDs` function returns empty string since a `login` value was not returned from the backend.

https://github.com/Expensify/App/blob/3ab4e6e12d9ff38e69493321f0d31f032481b373/src/libs/OptionsListUtils.ts#L1492-L1497

Therefore, the `getPersonalDetailsForAccountIDs` function returns empty.

https://github.com/Expensify/App/blob/3ab4e6e12d9ff38e69493321f0d31f032481b373/src/libs/OptionsListUtils.ts#L632

### What changes do you think we should make in order to solve the problem?


Instead of using `report.visibleChatMemberAccountIDs` for `accountIDs` over [here](https://github.com/Expensify/App/blob/6b4246158acd8d202e83668313630fa14b24fedb/src/libs/OptionsListUtils.ts#L1466)
        
This solution borrows from the `SidebarUtils` component.

https://github.com/Expensify/App/blob/6b4246158acd8d202e83668313630fa14b24fedb/src/libs/SidebarUtils.ts#L260

```
const accountIDs = report.participantAccountIDs ?? [];
```

### What alternative solutions did you explore? (Optional)

Return the user as part of `report.visibleChatMemberAccountIDs` from the backend on `OpenReport`.

**Comment by Tony-MK** [comment] 2024-02-17 02:17
@s77rt, I believe this issue is related to https://github.com/Expensify/App/issues/35679.

**Comment by s77rt** [comment] 2024-02-17 11:56
🎀 👀 🎀 Internal. User initiated reports have empty `visibleChatMemberAccountIDs`. When you start a chat with a new user or a new group I expected `visibleChatMemberAccountIDs` to be same as `participantAccountIDs`.

**Comment by bondydaa** [comment] 2024-02-19 18:07
tested again since we've had a few new releases since it was created and am still able to reproduce 
![image](https://github.com/Expensify/App/assets/4073354/dc1b68ea-29bf-4062-92d1-7b30997553f9)

**Comment by bondydaa** [comment] 2024-02-19 22:53
@s77rt can you link to where the API call is made that isn't properly returning `visibleChatMemberAccountIDs` so I can try and track down exactly where or what might have changed?

**Comment by s77rt** [comment] 2024-02-19 23:30
@bondydaa It's OpenReport (also related to `notificationPreference`)

https://github.com/Expensify/App/assets/16493223/06f1b05f-c18d-4377-85ae-439e1ba3bff8

**Comment by s77rt** [comment] 2024-02-22 21:33
@bondydaa Did you mean to assign an internal engineer here?

**Comment by strepanier03** [comment] 2024-02-26 18:00
Thanks @bondydaa - I'll keep following along for updates.

**Comment by strepanier03** [comment] 2024-03-01 04:29
@bondydaa - Any update on the internal discussion?

**Comment by bondydaa** [comment] 2024-03-01 21:22
hmm interestingly I came across this PR that was merged & deployed back in December 2023 which looks like it's made it so that OpenReport is returning the same thing for both `visibleChatMemberAccountIDs` and `participantAccountIDs`

https://github.com/Expensify/Web-Expensify/pull/40002/

<img width="1586" alt="image" src="https://github.com/Expensify/App/assets/4073354/5bdab7ff-ebc1-409d-b5ad-ffaf973213d0">

So it seems like the API returns these properly.

I noticed in the video from https://github.com/Expensify/App/issues/36492#issuecomment-1953272962 that you were offline first so is it possibly something with some optimistic data on the client getting set incorrect at first?

**Comment by bondydaa** [comment] 2024-03-01 21:23
cc @rlinoz maybe you might have some insights here since you wrote that PR, I don't think you did anything wrong in it I'm just a little lost here.

**Comment by rlinoz** [comment] 2024-03-04 16:29
Maybe this got fixed in the last deploy?  Or am I doing something different?
https://github.com/Expensify/App/assets/5201282/f7183357-4094-4649-b977-69fca833cbcf

**Comment by s77rt** [comment] 2024-03-04 17:08
@rlinoz Indeed for that case it seems fixed, I'm getting both `participantAccountIDs` and `visibleChatMemberAccountIDs` as expected.

<img width="690" alt="Screenshot 2024-03-04 at 6 00 54 PM" src="https://github.com/Expensify/App/assets/16493223/b0e5f33d-625e-4892-acbf-2e84acb973ac">


However for the case described here https://github.com/Expensify/App/issues/36492#issuecomment-1953272962 still facing same bug

<img width="690" alt="Screenshot 2024-03-04 at 6 02 51 PM" src="https://github.com/Expensify/App/assets/16493223/0bcdfe5d-ee35-4179-9325-d052e07ff065">

I think we should have `visibleChatMemberAccountIDs` same as `participantAccountIDs` when initiating a new chat / group, right?

**Comment by rlinoz** [comment] 2024-03-04 17:15
It should, yes.

But for [this other issue](https://github.com/Expensify/App/issues/34933#issuecomment-1944754254) that seems to have the same root cause we decided to wait for some refactoring that is happening on participants

**Comment by s77rt** [comment] 2024-03-04 17:22
@rlinoz Ah cool! Then we should either hold this on https://github.com/Expensify/Expensify/issues/341000 or just close it

**Comment by rlinoz** [comment] 2024-03-05 14:43
Let's hold on that

**Comment by strepanier03** [comment] 2024-03-13 22:41
Got it, thanks all.

**Comment by strepanier03** [comment] 2024-03-27 00:03
Hold PR still open.

**Comment by strepanier03** [comment] 2024-04-16 22:20
@s77rt - I noticed the PR this was deployed and closed for another GH that is currently on hold, https://github.com/Expensify/Expensify/issues/383292. 

Can you take a quick peek and confirm that I should update the title for our GH to be on hold for 383292 now? I believe it is based on the fields that GH is going to be removing.

**Comment by rlinoz** [comment] 2024-04-17 12:52
I think we should HOLD on https://github.com/Expensify/App/issues/34692 which will update to the new format, sounds good?

**Comment by strepanier03** [comment] 2024-04-17 21:10
Sounds great @rlinoz thanks for weighing in and suggesting it. I'll update the title now.

**Comment by s77rt** [comment] 2024-04-28 01:56
Still on hold

**Comment by s77rt** [comment] 2024-05-06 09:18
Same ^

**Comment by s77rt** [comment] 2024-05-17 16:50
Let's close this, issue no longer reproducible.

**Comment by s77rt** [comment] 2024-05-27 20:01
@strepanier03 We can close this

**Closed** 2024-05-27 20:08 UTC
Labels: Weekly, Internal, Help Wanted, Bug
