### ISSUE TITLE
[Search v2.2] Deleted message changes to empty content with (edited) in Search - Chat page

### ISSUE THREAD

**Issue by IuliiaHerets** [Expensify/App#48810] opened 2024-09-09 18:31 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 9.0.31-0
**Reproducible in staging?:** Y
**Reproducible in production?:** N/A
**Email or phone of affected tester (no customers):** applausetester+kh010901@applause.expensifail.com
**Issue reported by:** Applause Internal Team

## Action Performed:
1. Go to staging.new.expensify.com
2. Go to DM.
3. Send a message.
4. Go to Search > Chat.
5. Go to Sent.
6. Click on the message sent in Step 3.
7. Send another message in report RHP.
8. Delete the first message sent in Step 3.

## Expected Result:
The deleted message will be removed from Search - Chat page.

## Actual Result:
The deleted message changes to empty content with (edited) in Search - Chat page.

## Workaround:
Unknown

## Platforms:

- [ ] Android: Native
- [x] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

https://github.com/user-attachments/assets/e890fb95-b2d0-4e4e-9d59-9bc9da3b0620

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by IuliiaHerets** [comment] 2024-09-09 18:31
We think that this bug might be related to #wave-control

**Comment by etCoderDysto** [comment] 2024-09-09 18:46
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
Search - Deleted message changes to empty content with (edited) in Search - Chat page
### What is the root cause of that problem?
We are not checking if a `reportAction` is deleted before adding it to `reportActionItems`
https://github.com/Expensify/App/blob/61ee515eb384ed07d70c2d982f27ca46477eed5a/src/libs/SearchUtils.ts#L203-L209
### What changes do you think we should make in order to solve the problem?
We should check if a report action is deleted before adding it to `reportActionItems`
```javascript
const isDeleted = isDeletedAction(reportAction);
if (!isDeleted) {
        const from = data.personalDetailsList?.[reportAction.accountID];
       reportActionItems.push({
      ...reportAction,
      from,
      formattedFrom: from?.displayName ?? from?.login ?? '',
      date: reportAction.created,
      keyForList: reportAction.reportActionID,
     });
}
```
### What alternative solutions did you explore? (Optional)

**Comment by luacmartins** [comment] 2024-09-09 18:55
I'll take this since it's part of Search. cc @shubham1206agra @ikevin127

**Comment by luacmartins** [comment] 2024-09-09 22:21
CPing fix

**Comment by luacmartins** [comment] 2024-09-09 22:54
Fixed in staging.

**Closed** 2024-09-09 22:54 UTC
Labels: Reviewing, Engineering, Weekly, Bug
