### ISSUE TITLE
[HOLD for payment 2024-06-28] [$250] Android - Onboarding - Onboarding modal can be dismissed by tapping back button or swiping

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#40963] opened 2024-04-25 09:48 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.65-5
**Reproducible in staging?:** y
**Reproducible in production?:** new feature
**Issue reported by:** Applause - Internal team

## Action Performed:
1. Open the app and log in with a new account
2. After the onboarding modal appears, swipe left (Pixel) or use the device back button

## Expected Result:
The modal is still open and not dismissed

## Actual Result:
The onboarding modal is dismissed

## Workaround:
n/a

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [ ] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

https://github.com/Expensify/App/assets/93399543/71c5af89-d4c1-4efc-981f-0127389df246

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~013838a59a378265e1</li>
        <li>Upwork Job ID: 1785688303987118080</li>
        <li>Last Price Increase: 2024-05-15</li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @zanyrenney</details>

**Comment by kbecciv** [comment] 2024-04-25 09:48
We think that this bug might be related to #vip-vsb

**Comment by kbecciv** [comment] 2024-04-25 09:49
@zanyrenney FYI I haven't added the External label as I wasn't 100% sure about this issue. Please take a look and add the label if you agree it's a bug and can be handled by external contributors.

**Comment by zanyrenney** [comment] 2024-04-29 16:30
trying to figure out if this is desired.

**Comment by zanyrenney** [comment] 2024-04-29 16:30
@dubielzyk-expensify can you clarify?

**Comment by dubielzyk-expensify** [comment] 2024-04-30 04:03
Great find. You're not supposed to be able to dismiss the modal so this is a bug 👍

**Comment by zanyrenney** [comment] 2024-05-01 15:10
Thanks @dubielzyk-expensify ⭐

**Comment by zanyrenney** [comment] 2024-05-01 15:10
adding the external label/

**Comment by skyweb331** [comment] 2024-05-01 15:54
@zanyrenney 
so if user does not complete the onboarding, user should be stuck in onboarding modal?
For now, I am working on https://github.com/Expensify/App/issues/40876#issuecomment-2084638160 which is blocking onboarding modal when user has completed it and it seems like this is vice-versa.

If so, I will submit the proposal.

**Comment by zanyrenney** [comment] 2024-05-07 13:15
As per @dubielzyk-expensify above, you're not supposed to be able to dismiss this. So you're correct they should be "stuck" in onboarding modal I think.

@dubielzyk-expensify that does seem a bit restrictive, so just checking that is correct?

**Comment by zanyrenney** [comment] 2024-05-10 16:11
bump @dubielzyk-expensify please could you let me know?

**Comment by dubielzyk-expensify** [comment] 2024-05-12 22:12
> @dubielzyk-expensify that does seem a bit restrictive, so just checking that is correct?

Yes that is correct. There's a whole internal thread about it, but basically boils down to this is key information for users to have a good experience on Expensify. This is the only place we use this pattern and it's not considered uncommon outside of Expensify in terms of modal behavior.

**Comment by zanyrenney** [comment] 2024-05-14 10:20
Hey @skyweb331 

@zanyrenney
so if user does not complete the onboarding, user should be stuck in onboarding modal?

Yes, that is correct. Please do submit your proposal for this here? We'd love to have you work on it! Thanks

cc @sobitneupane

**Comment by skyweb331** [comment] 2024-05-14 19:11
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
Block onboarding modal dismiss on android by back or swipe
### What is the root cause of that problem?
All expensify modals can be dismissed by back button.

### What changes do you think we should make in order to solve the problem?
Need to block native back action for android. Similar to https://github.com/Expensify/App/blob/main/src/pages/Search/useCustomBackHandler/index.android.ts

### What alternative solutions did you explore? (Optional)
n/a

**Comment by zanyrenney** [comment] 2024-05-15 08:44
@sobitneupane please review the proposal

**Comment by sobitneupane** [comment] 2024-05-15 09:57
Thanks for your proposal @skyweb331 

Can you please elaborate your proposal.

**Comment by skyweb331** [comment] 2024-05-15 10:07
@sobitneupane [proposal](https://github.com/Expensify/App/issues/40963#issuecomment-2110967570) updated.

**Comment by sobitneupane** [comment] 2024-05-19 09:04
Thanks for the update @skyweb331 

Your proposal will handle the hardware back button press but will it also handle swipe left gesture? Should we disable the swipe gesture for the Onboarding Screen? Can you please test proposal both on back button and swipe left gesture?

**Comment by skyweb331** [comment] 2024-05-19 17:44
@sobitneupane 
You are right. My proposal is to block hardware back button, not swiping.
To block swiping, need to add `gestureEnabled: false` for Stack.Screen. Will update proposal if you want it.

**Comment by sobitneupane** [comment] 2024-05-20 03:25
Thanks for the [update](https://github.com/Expensify/App/issues/40963#issuecomment-2119311179) @skyweb331

> Will update proposal if you want it.

Yes, please.

> New contributors are limited to working on one job at a time, however experienced contributors may work on numerous jobs simultaneously.

As per the contributing guidelines, new contributor can only work on one issue at a time. 

Please let me know if you are assigned to a closed issue or an open issue with the `Awaiting payment` label.

**Comment by skyweb331** [comment] 2024-05-20 03:49
@sobitneupane Proposal updated as you suggested.

And my assigned Issue is https://github.com/Expensify/App/issues/40876 and its [PR](https://github.com/Expensify/App/pull/42087) is already approved. Not sure if I have to wait until it is deployed...

**Comment by sobitneupane** [comment] 2024-05-20 04:20
@skyweb331 You should be assigned to a closed issue or an open issue with the `Awaiting payment` label. Please let me know once the PR is deployed to production.

**Comment by skyweb331** [comment] 2024-05-20 04:36
OK. I will wait for my PR is merged. Meanwhile, I will work on this issue and prepare the PR...

**Comment by zanyrenney** [comment] 2024-05-21 09:19
adding @skyweb331 to the issue

**Comment by skyweb331** [comment] 2024-05-23 21:40
@MelvinBot I am working on this and will submit the PR soon.

**Comment by skyweb331** [comment] 2024-05-28 05:21
I will submit the PR today. Working on preparing QA videos.

**Comment by zanyrenney** [comment] 2024-06-27 15:03
making daily to action tomorrow

**Comment by zanyrenney** [comment] 2024-06-28 12:47
@skyweb331 looks like you never accepted the job so can't pay this out.

**Comment by zanyrenney** [comment] 2024-06-28 12:47
Job now closed (as been almost 2 months) resending another offer

**Comment by zanyrenney** [comment] 2024-06-28 12:50
cannot find a "skyweb" on UW: 
![2024-06-28_13-49-46](https://github.com/Expensify/App/assets/56830058/89489248-62dd-4473-8104-caaa3fc6f7b8)

**Comment by skyweb331** [comment] 2024-06-28 14:25
@zanyrenney please send an offer to this: https://www.upwork.com/freelancers/~019e5171478d2a22f7

**Comment by zanyrenney** [comment] 2024-07-01 18:16
not overdue - waiting on @skyweb331 to accept

**Comment by zanyrenney** [comment] 2024-07-02 08:01
Payment Summary
[Upwork Job](https://www.upwork.com/jobs/~013838a59a378265e1)

ROLE: @skyweb331 paid $250 via Upwork (LINK)
Reviewer: @sobitneupane owed $250 via NewDot - please request!

**Closed by zanyrenney** 2024-07-02 08:01 UTC
Labels: External, Daily, Awaiting Payment, Bug

**Comment by JmillsExpensify** [comment] 2024-07-29 22:30
$250 approved for @sobitneupane
