### ISSUE TITLE
[$500] Android - User allowed to paste text in BNP page for a second

### ISSUE THREAD

**Issue by kavimuru** [Expensify/App#34319] opened 2024-01-11 07:55 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.24-0
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** Applause internal team
**Slack conversation:**

## Action Performed:
1. Launch app
2. Tap fab----Request money/send money
3. In BNP, paste text in amount field

## Expected Result:
User must not be allowed to paste text in BNP page for a second.

## Actual Result:
User is allowed to paste text in BNP page for a second.

## Workaround:
unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [ ] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

https://github.com/Expensify/App/assets/43996225/8909149c-13b2-4f08-9463-a51ad74acd0e

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~014d093bb089ba85dd</li>
        <li>Upwork Job ID: 1745353862937509888</li>
        <li>Last Price Increase: 2024-01-11</li>
    </ul>
</details>

**Comment by unicorndev-727** [comment] 2024-01-11 08:17
## Proposal
from: @unicorndev-727
### Please re-state the problem that we are trying to solve in this issue.
### What is the root cause of that problem?
The root cause is that shouldUpdateSelection is initially true so that setSelection works at first loading in MoneyRequestAmountForm.
https://github.com/Expensify/App/blob/7ae1ec7e74b908e6340bccaf7e42b0345d766711/src/pages/iou/steps/MoneyRequestAmountForm.js#L90
### What changes do you think we should make in order to solve the problem?
We need to set shouldUpdateSelection to false.
### What alternative solutions did you explore?
N/A

**Comment by DylanDylann** [comment] 2024-01-11 09:39
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
- User allowed to paste text in BNP page for a second
### What is the root cause of that problem?
- When we paste the text, all the text will be put to the input field for a while, it is the default behavior of the native device. 
### What changes do you think we should make in order to solve the problem?
- Once we long press on the text input, we should clear the Clipboard if it contain the invalid amount.
- For example, update:
https://github.com/Expensify/App/blob/7ae1ec7e74b908e6340bccaf7e42b0345d766711/src/pages/iou/steps/MoneyRequestAmountForm.js#L279
to:
```
// Pseudo code
<TextInputWithCurrencySymbol onFocus={()=> {
if(!MoneyRequestUtils.validateAmount(Clipboard.getString()) Clipboard.setString('')
}}
```

### What alternative solutions did you explore? (Optional)

- NA

**Comment by shahinyan11** [comment] 2024-01-11 11:13
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
User allowed to paste text in BNP page for a second
### What is the root cause of that problem?
It is the behavior of react-native `TextInput`
### What changes do you think we should make in order to solve the problem?
1. Add function shoulHideContexMenu
```
const shoulHideContexMenu = useCallback(async () => {
     const currentClipboard = await Clipboard.getString()
     return !MoneyRequestUtils.validateAmount(currentClipboard, decimals)
},[]}
```
2. Add prop to `TextInputWithCurrencySymbol`
contextMenuHidden={shoulHideContexMenu()}

### What alternative solutions did you explore? (Optional)

**Comment by DylanDylann** [comment] 2024-01-11 16:52
@fedirjh My proposal does not "disable pasting for native", can you help check again or mention, what section in my proposal lead to your opinion bellow:

>  I don't think we should disable pasting for native

**Comment by DylanDylann** [comment] 2024-01-11 17:12
@fedirjh Let me know if you need my help to test the solution

**Comment by shahinyan11** [comment] 2024-01-11 17:57
> @shahinyan11 Your proposal didn't worked for me , even when `contextMenuHidden` is set to `true` , I am still able to elect the text and trigger the context menu.

Are you done all 5 steps ?

**Comment by DylanDylann** [comment] 2024-01-11 19:58
@fedirjh After investigating, I think that my [proposal](https://github.com/Expensify/App/issues/34319#issuecomment-1886724930) is just workaround. So I think we need to hire the proposal that uses the native code, or we can consider closing this one because it is a minor issue

**Comment by shahinyan11** [comment] 2024-01-11 20:11
@fedirjh 

https://github.com/Expensify/App/assets/46921547/9c111486-a08b-45e3-ac99-b967bc2b5f7f

**Comment by DylanDylann** [comment] 2024-01-12 03:01
@shahinyan11 Suppose that the contextMenuHidden works as you expected. But I think that, the context menu contains not only the "Paste" button. but also the "Copy", "Cut", ... So if we hide the context menu, we also can not interact with the rest buttons

**Comment by CortneyOfstad** [comment] 2024-01-22 15:23
> @DylanDylann I totally agrees with you , any solution beside native code is just a workaround.
> @CortneyOfstad Should we close ?


Sorry for the delay here — I think we can close in this scenario 👍

**Closed by CortneyOfstad** 2024-01-22 15:23 UTC
Labels: Reviewing, External, Weekly, Help Wanted, Bug
