### ISSUE TITLE
[$500] Distance - Start waypoint page opens Not here page

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#32718] opened 2023-12-08 14:31 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.10-0
**Reproducible in staging?:** Y
**Reproducible in production?:** Y 
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** Applause - Internal Team
**Slack conversation:**

## Action Performed:
1. Go to staging.new.expensify.com
2. Click + > Request money
3. Very quickly, go to Scan > Distance > Start

## Expected Result:
Start waypoint page is opened

## Actual Result:
Not here page is opened
This issue is easily reproduced if the device is slightly slow

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [x] Android: mWeb Chrome
- [ ] iOS: Native
- [x] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details> 

https://github.com/Expensify/App/assets/78819774/4339913a-183a-4bef-b77f-16231b3bdb45

https://github.com/Expensify/App/assets/78819774/de8220bc-be5c-4112-a362-609141d0400f

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~017c415f5aed7a38c4</li>
        <li>Upwork Job ID: 1733132137808777216</li>
        <li>Last Price Increase: 2023-12-08</li>
    </ul>
</details>

**Comment by ZhenjaHorbach** [comment] 2023-12-08 15:13
Can't reproduce on the last main

As far as I can tell by comparing dev with staging
Routes have been changed in this PR
https://github.com/Expensify/App/pull/28618

Perhaps this is why it no longer reproduces

**Comment by Christinadobrzyn** [comment] 2023-12-08 16:42
I can't reproduce this on any of the platforms in the OP. 

@bernhardoj and @zukilover how were you able to reproduce this issue? If yes, what were you doing differently from the steps in the OP?

**Comment by shubham1206agra** [comment] 2023-12-08 16:58
@Christinadobrzyn Just switch tabs quickly for a while. When you see tab switching getting sluggish, just go to the first waypoint

**Comment by Christinadobrzyn** [comment] 2023-12-11 20:25
I still can't get this to work - I can't find an environment that has a connectivity that allows me to slow down the page load enough to get this error. 

I'm still not sure this needs to be fixed at this time - as it affects a limited population of users - @parasharrajat what do you think?

**Comment by shubham1206agra** [comment] 2023-12-12 01:51
@Christinadobrzyn There has been a refactor of the money request flow recently. I will try to repro this again. If not, we can close this out.

**Comment by shubham1206agra** [comment] 2023-12-12 03:45
@Christinadobrzyn This seems to be fixed. Please close this issue.

**Closed** 2023-12-12 19:52 UTC
Labels: External, Daily, Needs Reproduction, Help Wanted, Bug
