### ISSUE TITLE
Adding emoji by text in edit shifts cursor

### ISSUE THREAD

**Issue by kavimuru** [Expensify/App#25526] opened 2023-08-19 12:54 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Open the app
2. Open any report
3. Send any message
4. Edit the message
5. At the end, add any emoji using text eg: `:joy:` (colon joy colon)
6. Observe that cursor shifts position to few characters back

## Expected Result: 
Cursor should be at the end after adding emoji in edit message

## Actual Result: 
Cursor shifts few characters before after adding emoji in edit message

## Workaround:
Can the user still use Expensify without this being fixed? Have you informed them of the workaround?

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [x] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 1.3.55.2
**Reproducible in staging?:** y
**Reproducible in production?:** n
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/43996225/67cb5c62-494a-4798-9463-477203eff009

https://github.com/Expensify/App/assets/43996225/679a8e30-9d04-4ecf-b4d8-d951e7db06d0

**Expensify/Expensify Issue URL:**
**Issue reported by:** @dhanashree-sawant
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1692436446568749

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by conorpendergrast** [comment] 2023-08-21 09:35
I can reproduce this on Safari on v1.3.55-7 (not on OSX desktop though). 

Does seem pretty similar to https://github.com/Expensify/App/issues/25413, so I think we're ok to downgrade to Daily as a result. 

@stitesExpensify Can you check and confirm, and we'll close this out as a dupe of https://github.com/Expensify/App/issues/25413?

**Comment by mountiny** [comment] 2023-08-21 14:01
[Confirmed](https://expensify.slack.com/archives/C01GTK53T8Q/p1692626048525029?thread_ts=1692626032.825079&cid=C01GTK53T8Q) this is fixed in main so I am removing the label and I think we can actually close this issue without reporting bonus as the root cause was already fixed by another report.

**Closed by mountiny** 2023-08-21 14:01 UTC
Labels: Engineering, Daily, Bug
