### ISSUE TITLE
[$250] Web - Chat - Message marked as new after reading it and scrolling up and down the conversation

### ISSUE THREAD

**Issue by IuliiaHerets** [Expensify/App#50318] opened 2024-10-06 19:56 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** v9.0.45-2
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**If this was caught during regression testing, add the test name, ID and link from TestRail:** https://expensify.testrail.io/index.php?/tests/view/5050520
**Issue reported by:** Applause Internal Team

## Action Performed:
1. Open https://staging.new.expensify.com/
2. Open the chat with long history.
3. Scroll up until last messages are not visible.
4. Send a message.
5. Verify the chat scrolls to the bottom. The message is marked New.
6. Scroll up and down a few times, click the "New message" button.

## Expected Result:
The "New" mark for the message is dismissed after reading the message and scrolling up and down the conversation.

## Actual Result:
The message remains marked as new after reading it and scrolling up and down the chat conversation.

## Workaround:
Unknown

## Platforms:

- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

https://github.com/user-attachments/assets/dd0cdac4-a4b4-4f93-b3a3-5a1aae0baed3
  
</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~021843398922657090244</li>
        <li>Upwork Job ID: 1843398922657090244</li>
        <li>Last Price Increase: 2024-10-07</li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @paultsimura</details>

**Comment by IuliiaHerets** [comment] 2024-10-06 19:57
@lschurr  FYI I haven't added the External label as I wasn't 100% sure about this issue. Please take a look and add the label if you agree it's a bug and can be handled by external contributors

**Comment by shijir0927** [comment] 2024-10-08 03:46
## Proposal
---
### Please re-state the problem that we are trying to solve in this issue.
Message remains marked as new after reading it by clicking on "New messages" floating button and scrolling up and down the chat conversation.

### What is the root cause of that problem?
The first bug which is the "New messages" floating button not marking the new message as read was caused by `scrollToBottomAndMarkReportAsRead` function not fully marking the new report as read as we are missing the second argument when calling `Report.readNewestAction(report.reportID);`. Without the second argument being `true`, it doesn't emit `readNewestAction_${report_id}` event.

https://github.com/Expensify/App/blob/bcc62638a21ccbe717fb25abb983aac86672a8a2/src/pages/home/report/ReportActionsList.tsx#L418

As for scrolling to the bottom of the message list not marking the message as read, currently, there is no logic tied to handling new messages as read in `trackVerticalScrolling` function.

### What changes do you think we should make in order to solve the problem?
Explicitly dispatching `readNewestAction_${reportID}` event with
 ```ruby
Report.readNewestAction(report.reportID, true);
``` 
fixes our issue for the floating button. 

Also, we can add a new logic to mark the unread message as read when there is an unread message and we are scrolled to the bottom of the chat. 
```ruby
    const handleUnreadReportWhenScrolledToTheBottom = () => {
        if (scrollingVerticalOffset.current <= 0 && !!unreadMarkerReportActionID) {
            Report.readNewestAction(report.reportID, true);
        }
    }

    const trackVerticalScrolling = (event: NativeSyntheticEvent<NativeScrollEvent>) => {
        scrollingVerticalOffset.current = event.nativeEvent.contentOffset.y;
        handleUnreadFloatingButton();
        handleUnreadReportWhenScrolledToTheBottom();
        onScroll?.(event);
    };
```

test branch: https://github.com/shijir0927/App/commit/6e13ded04029f9e389a66e4d0e3f0222aef856fc

fixed state video: 

https://github.com/user-attachments/assets/0db72524-7b42-4a76-96b6-51da2b2cd4cf



### What alternative solutions did you explore? (Optional)
With more debugging, we can try to find out what state and where exactly we are ending up in this buggy situation but with bunch of different useEffects happening at the same time in this component making the event cycle pretty complex, I decided to focus on fixing the outcome rather than preventing the code to never reach this state.

**Comment by MonilBhavsar** [comment] 2024-10-08 12:10
👍 
I just tried but could not reproduce the issue as in video - new marker line appearing after sending a message. Do you please mind checking while we're here

**Comment by MonilBhavsar** [comment] 2024-10-10 07:27
Yes, we created a new issue. So closing this one out. Thanks all!

**Closed by MonilBhavsar** 2024-10-10 07:27 UTC
Labels: External, Daily, Help Wanted, Bug
