### ISSUE TITLE
[$500] RBR doesn't show up on LHN and Report/Expense preview when there is violation(s) with the expense report.

### ISSUE THREAD

**Issue by m-natarajan** [Expensify/App#37639] opened 2024-03-01 20:44 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.46-0
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** @hayata-suenaga 
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1709230047147289

## Action Performed:
1. As A, create a new control workspace on Old Expensify 
2. Run the script to access the workspace in ND
`p = Policy.getCurrent();
p.policy.isPolicyExpenseChatEnabled = "true";
p.save();`
3. Configure some violations to require Category/tag
4. Invite user B as employee and user C as Approver
5. Sign in as user B in ND and create an expense report in the workspace created in step 1
6. Submit the report to approver
7. Sign in as user C in ND
8. Look at the LHN and see if there is any violation RBRfor the money request sent by user B
9. Open the expense details and see if there is any violation RBR appears

## Expected Result:
RBR should be displayed in the LHN and expense details

## Actual Result:
RBR doesn't show up on LHN and Report/Expense preview when there is violation(s) with the expense report

## Workaround:
unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

https://github.com/Expensify/App/assets/38435837/220bc93c-8642-4046-84a1-63c19f33adbb

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~0135cc12979416295b</li>
        <li>Upwork Job ID: 1767297509513805824</li>
        <li>Last Price Increase: 2024-03-18</li>
    </ul>
</details>

**Comment by johncschuster** [comment] 2024-03-05 21:35
Trying to figure out which wave to tie this to (if any).

**Comment by kmbcook** [comment] 2024-03-12 20:21
This method is called in components/LHNOptionsList/OptionRowLHNData to determine if an item in LHN has violations.
https://github.com/Expensify/App/blob/bca05057648c01f265d8eeac9553f4568e635187/src/libs/ReportUtils.ts#L4099-L4114

In this part of that method it appears that if the current user is not the submitter of the item, the item should not have violations. Is that true? Is the app intentionally designed to not show RBR in LHN for users who did not submit the report?
https://github.com/Expensify/App/blob/bca05057648c01f265d8eeac9553f4568e635187/src/libs/ReportUtils.ts#L4107-L4109

**Comment by johncschuster** [comment] 2024-03-14 21:43
I'm checking in [Slack](https://expensify.slack.com/archives/C06ML6X0W9L/p1709674907966189) how best to prioritize this one within our release schedule

**Comment by johncschuster** [comment] 2024-03-18 21:15
Looks like we really need to keep the priority high on this one. I'll go drum up some proposals.

**Comment by johncschuster** [comment] 2024-03-21 13:30
Looking for more proposals.

**Comment by johncschuster** [comment] 2024-03-21 14:34
[Raised in Slack](https://expensify.slack.com/archives/C01GTK53T8Q/p1711031640899469)

**Comment by Victor-Nyagudi** [comment] 2024-03-21 21:00
> Configure some violations to require Category/tag

How do I do this?

> Invite user B as employee and user C as Approver

**Comment by Victor-Nyagudi** [comment] 2024-03-21 21:08
> 3. Configure some violations to require Category/tag

How do I do this? My account has the violations beta enabled after asking in Slack.  Do I just toggle the option for "People must categorize expenses"?

> 4. Invite user B as employee and user C as Approver

I only see the option to invite a member as a workspace admin, auditor, or employee. How do I invite a user as an approver?

> 6. Submit the report to approver

The video shows a section on OD that says 'Submits to' but that column doesn't exist for me after creating the control policy on OD. How do I explicitly submit a report to a member?

I also have the red banner saying:

```
Your billing information is out of date. Please [update your billing information](https://staging.expensify.com/settings#payments).
```

It's happened twice before, but I got help from Slack. Is there anyway to fix this permanently so I don't have to keep asking for help in Slack? 

I believe it also prevents me from submitting any expenses because I just got an error when trying to do so.

**Comment by johncschuster** [comment] 2024-03-22 16:55
This was discussed in [Slack](https://expensify.slack.com/archives/C01GTK53T8Q/p1711031640899469) and it turns out this is expected behavior.

![cleanshot_2024-03-22_at_09 55 49_2x](https://github.com/Expensify/App/assets/5579997/13cb1c25-ffea-4cba-9a1f-6c6d3e7641ea)

Closing!

**Closed by johncschuster** 2024-03-22 16:55 UTC
Labels: External, Daily, Help Wanted, Bug
