### ISSUE TITLE
[$1000] There is a noticeable lag before chat turns from Unread to Read in the LHN for IOU reports/threads

### ISSUE THREAD

**Issue by kavimuru** [Expensify/App#19444] opened 2023-05-23 13:54 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:

1. Send a money request from account A to account B
2. Open the newly created IOU thread from account B and notice the Unread status change to read on LHN

## Expected Result:
The change from the Unread state to Read should happen instantly just as user clicks on the report on LHN
## Actual Result:
There is a noticeable lag happening before the report changes from Unread to read in the LHN

## Workaround:
Can the user still use Expensify without this being fixed? Have you informed them of the workaround?

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [x] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 1.3.16.3
**Reproducible in staging?:** Needs reproduction
**Reproducible in production?:** Needs reproduction
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/43996225/fc7c9361-3777-4525-9567-2706ea961122

**Expensify/Expensify Issue URL:**
**Issue reported by:** @nathan-mulugeta
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1684481982104969
 
[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01aeb277d858be7b5c</li>
        <li>Upwork Job ID: 1661333788252942336</li>
        <li>Last Price Increase: 2023-05-31</li>
    </ul>
</details>

**Comment by namhihi237** [comment] 2023-05-25 08:27
Hi team, can I resolve this task?

**Comment by namhihi237** [comment] 2023-05-25 08:31
ok Thank @Nathan-Mulugeta

**Comment by namhihi237** [comment] 2023-05-25 08:33
Contributor details
Your Expensify account email: trungnam23799@gmail.com
Upwork Profile Link: https://www.upwork.com/freelancers/namletrung

**Comment by mollfpr** [comment] 2023-05-25 13:57
Thanks @namhihi237 for the proposal! Could you attach a video result?

**Comment by namhihi237** [comment] 2023-05-25 14:10
## Proposal
[Updated](https://github.com/Expensify/App/issues/19444#issuecomment-1562915309)

**Comment by namhihi237** [comment] 2023-05-25 14:24
> Thanks @namhihi237 for the proposal! Could you attach a video result?

@mollfpr I had added video results on the proposal.

**Comment by zanyrenney** [comment] 2023-05-25 17:31
Going OOO and this is pretty active so needs management by bug0 team member, as per the [new process ](https://expensify.slack.com/archives/CK49UADB9/p1684182291511799)to stay assigned but assign another team member, please can you keep a watch of this. I am OOO until 8th June. Thanks!

**Comment by zanyrenney** [comment] 2023-05-25 17:32
ugh sorry i unassigned @lschurr accidentally.

**Comment by lschurr** [comment] 2023-05-26 16:40
@mollfpr could you review the updated proposal?

**Comment by mollfpr** [comment] 2023-05-26 16:48
Thanks for the ping @lschurr 

> However, this process, including the re-rendering time, may cause a slight delay. As a result, updates might not be instantaneous and the application could appear slower.

@namhihi237 I feel like the root cause is not complete. Why it’s working fine with regular report?

**Comment by c3024** [comment] 2023-05-27 12:03
## Proposal

### Please re-state the problem that we are trying to solve in this issue.

There is a noticeable lag for chat to change from unread to read in LHN for IOU reports

### What is the root cause of that problem?

In [App/src/pages/home/sidebar/SidebarLinks.js](https://github.com/Expensify/App/blob/12d2f3c89de6c0271ae90760de816e198d3e9025/src/pages/home/sidebar/SidebarLinks.js#LL223C1-L224C16)

[Lines 224 to 226](https://github.com/Expensify/App/blob/12d2f3c89de6c0271ae90760de816e198d3e9025/src/pages/home/sidebar/SidebarLinks.js#LL223C1-L224C16)

```
 if (ReportUtils.isIOUReport(report)) {
        return null;
    }

```
returns `null` for `IOUReports` and prevents updating `lastReadTime`. `lastReadTime` is empty. Since `isUnread` returns `lastReadTime < lastVisibleActionCreated`,  it does not change from `false` to `true`

### What changes do you think we should make in order to solve the problem?

Remove this from Lines 224 to 226 of `SidebarLinks.js`
```
 if (ReportUtils.isIOUReport(report)) {
        return null;
    }

```
Then it IOU reports do not return `null` right away and the `lastReadTime` is updated and `isUnread` changes to `false`.

### What alternative solutions did you explore? (Optional)

Retain the conditional but change the statement to 
```
if (lodashGet(SidebarUtils.getOptionData(lodashGet(report, 'reportID')), 'lastReadTime') && ReportUtils.isIOUReport(report)) {
            return null;
        }

```
or

```
if (!lodashGet(SidebarUtils.getOptionData(lodashGet(report, 'reportID')), 'isUnread') && ReportUtils.isIOUReport(report)) {
            return null;
        }
```

When `isUnread` is true or `lastReadTime` is empty, the conditional is `falsy` then `lastReadTime` is updated from the following `return` statement.

**Comment by mollfpr** [comment] 2023-05-27 15:49
Thanks @c3024! I still have some questions.

> returns null for IOUReports and prevents updating lastReadTime. lastReadTime is empty. Since isUnread returns lastReadTime < lastVisibleActionCreated, it does not change from true to false

I don't think this is true. `lastReadTime` is not empty, because we set the value optimistically on the `OpenReport` API. If the `chatReportSelector` prevents the iou report from re-render, why does the IOU report re-render eventually?

**Comment by mollfpr** [comment] 2023-05-27 16:02
Also, the text style unread on request money and send money has different behavior. In the request money report, the unread style is not disappearing even after opening the report.

https://github.com/Expensify/App/assets/25520267/f690053c-c2be-42f7-b740-b9158934a544

**Comment by c3024** [comment] 2023-05-28 04:46
> Thanks @c3024! I still have some questions.
> 
> > returns null for IOUReports and prevents updating lastReadTime. lastReadTime is empty. Since isUnread returns lastReadTime < lastVisibleActionCreated, it does not change from true to false
> 
> I don't think this is true. `lastReadTime` is not empty, because we set the value optimistically on the `OpenReport` API. If the `chatReportSelector` prevents the iou report from re-render, why does the IOU report re-render eventually?

Thanks @mollfpr . 
You are right. If the `lastReadTime` field exists it would have a value.

I think a new `OptionRowLHN` initially has no field of `lastReadTime`. It can get the `lastReadTime` from `chatReportSelector` or from the `openReport` call from `Report` in `componentDidMount` or `componentDidUpdate` in `ReportActionsView`. When `chatReportSelector` returns `null`, it gets the value from the `openReport`.

Returning `null` from `chatReportSelector` for IOU reports appears to be the reason for not updating status from `unRead` to `read` because just removing the line `selector: chatReportSelector` from  

[Line 291 - 300 from src/pages/home/sidebar/SidebarLinks.js](https://github.com/Expensify/App/blob/12d2f3c89de6c0271ae90760de816e198d3e9025/src/pages/home/sidebar/SidebarLinks.js#LL291C1-L300C11)

```
withOnyx({
        // Note: It is very important that the keys subscribed to here are the same
        // keys that are subscribed to at the top of SidebarUtils.js. If there was a key missing from here and data was updated
        // for that key, then there would be no re-render and the options wouldn't reflect the new data because SidebarUtils.getOrderedReportIDs() wouldn't be triggered.
        // This could be changed if each OptionRowLHN used withOnyx() to connect to the Onyx keys, but if you had 10,000 reports
        // with 10,000 withOnyx() connections, it would have unknown performance implications.
        chatReports: {
            key: ONYXKEYS.COLLECTION.REPORT,
            selector: chatReportSelector,
        },
```

fixes this issue.

**Comment by lschurr** [comment] 2023-05-29 23:55
@mollfpr could you review this last post?

**Comment by mollfpr** [comment] 2023-06-01 06:52
Thanks @c3024; you're right this was fixed there.

@lschurr We can complete this, I just test it with the latest main.

**Comment by Nathan-Mulugeta** [comment] 2023-06-01 06:54
> If #19644 fixes this issue I think I am eligible for reporting bonus, according to the [guidlines](https://github.com/Expensify/App/blob/main/contributingGuides/CONTRIBUTING.md#:~:text=If%20the%20bug%20is%20fixed%20by%20a%20PR%20that%20is%20not%20associated%20with%20your%20bug%20report%2C%20then%20you%20will%20not%20be%20eligible%20for%20the%20corresponding%20compensation%20unless%20you%20can%20find%20the%20PR%20that%20fixed%20it%20and%20prove%20your%20bug%20report%20came%20first.) since this issue came first before the PR, am I right? 
> 
> > If the bug is fixed by a PR that is not associated with your bug report, then you will not be eligible for the corresponding compensation unless you can find the PR that fixed it and prove your bug report came first.

Hey guys, what do you think of this?

**Comment by mollfpr** [comment] 2023-06-01 06:56
@Nathan-Mulugeta I believe you will be compensated. @lschurr will handle that.

**Comment by lschurr** [comment] 2023-06-01 15:01
Cool, so the bug is fixed and we just need to compensate @Nathan-Mulugeta for reporting, correct?

**Comment by Nathan-Mulugeta** [comment] 2023-06-01 15:10
Just applied @lschurr

**Comment by lschurr** [comment] 2023-06-01 15:32
Great, payment issued. I think we can close this one out.

**Closed by lschurr** 2023-06-01 15:32 UTC
Labels: External, Daily, Help Wanted, Bug
