### ISSUE TITLE
Search - Status bar is not preserved and selection is cleared when going from Inbox to Search

### ISSUE THREAD

**Issue by IuliiaHerets** [Expensify/App#47670] opened 2024-08-19 20:55 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___
 
**Version Number:** v9.0.22-5
**Reproducible in staging?:** Y
**Reproducible in production?:** N
**Email or phone of affected tester (no customers):** applausetester+kh1681@applause.expensifail.com
**Issue reported by:** Applause Internal Team

## Action Performed:
Precondition:
- Account has expenses in Outstanding or Paid tabs.

1. Launch New Expensify app.
2. Go to Search.
3. Go to Outstanding.
4. Long press on the expense > Select.
5. Go to Inbox.
6. Go back to Search.

## Expected Result:
App will open Outstanding tab with the selection preserved when going from Search to Inbox and back to Search.

## Actual Result:
App opens All tab with the selection cleared when going from Search to Inbox and back to Search.

## Workaround:
Unknown

## Platforms:

- [x] Android: Native
- [x] Android: mWeb Chrome
- [x] iOS: Native
- [ ] iOS: mWeb Safari
- [ ] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

https://github.com/user-attachments/assets/c5e998e7-3922-438c-a900-1a341e4da0b3

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by IuliiaHerets** [comment] 2024-08-19 20:55
We think that this bug might be related to #wave-collect - Release 1

**Comment by marcaaron** [comment] 2024-08-19 22:09
Not deploy blocker worthy IMO.

**Comment by bernhardoj** [comment] 2024-08-20 04:42
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
The status bar selected item isn't preserved after switching to another bottom tab. This only happens on the small screen.

### What is the root cause of that problem?
When we press the search bottom tab, we call `getCurrentSearchParams` to get the search params from the existing search bottom tab or central pane in the nav stack, then pass it to the new search screen.
https://github.com/Expensify/App/blob/44a751679b1f0162c2de8d57db6eb63cc9dafce9/src/libs/Navigation/AppNavigator/createCustomBottomTabNavigator/BottomTabBar.tsx#L91-L95
https://github.com/Expensify/App/blob/44a751679b1f0162c2de8d57db6eb63cc9dafce9/src/libs/SearchUtils.ts#L297-L312

This works well on large screen, but not on small screen.

When we go to the search page, the nav stack looks like this:
small: [BottomTab: [Home, SearchBottomTab], SearchCentralPane]
large: [BottomTab: [Home, SearchBottomTab], Report, SearchCentralPane]

Both the search bottom tab and central pane holds the search query (q) params. When we change the status to paid, for example, the query params is only updated to the search central pane.
https://github.com/Expensify/App/blob/44a751679b1f0162c2de8d57db6eb63cc9dafce9/src/components/Search/SearchStatusBar.tsx#L137

On the large screen, when we go back to home, the nav stack becomes:
[BottomTab: [Home, SearchBottomTab, Home], Report, SearchCentralPane, Report]

`SearchCentralPane` is still in the stack with the status query params, so, when we switch back to the search page, `getCurrentSearchParams` will return the query params with the previous status selected.

But on the small screen, going back to home will pop the search central pane out.
small: [BottomTab: [Home, SearchBottomTab, Home]]

https://github.com/Expensify/App/blob/44a751679b1f0162c2de8d57db6eb63cc9dafce9/src/libs/Navigation/linkTo/index.ts#L180-L184

So, when we switch back to the search page, `getCurrentSearchParams` will return the query params from `SearchBottomTab` which contains the old status query.

### What changes do you think we should make in order to solve the problem?

We need to update the bottom tab params too when selecting the status.
https://github.com/Expensify/App/blob/44a751679b1f0162c2de8d57db6eb63cc9dafce9/src/components/Search/SearchStatusBar.tsx#L137

```
const searchBottomTabKey = getTopmostBottomTabRoute(navigationRef.getRootState() as State<RootStackParamList>)?.key;
Navigation.setParams({q: item.query});
Navigation.setParams({q: item.query}, searchBottomTabKey);
```

We need to update `getTopmostBottomTabRoute` to return the bottom tab key too.
https://github.com/Expensify/App/blob/44a751679b1f0162c2de8d57db6eb63cc9dafce9/src/libs/Navigation/getTopmostBottomTabRoute.ts#L18
```
{... , key: topmostBottomTabRoute.key}
```

**Comment by Kicu** [comment] 2024-08-20 07:47
I'm also interested in whether this is really a bug? the act of navigating to another screen changes a lot of things and we do reset some things in Search.
Also I don't think anyone was expecting that the selection state persists.

**Comment by luacmartins** [comment] 2024-08-20 13:49
This is intended. Closing this issue.

**Closed by luacmartins** 2024-08-20 13:49 UTC
Labels: Engineering, Daily, Bug

**Comment by bernhardoj** [comment] 2024-08-20 15:22
Maybe we can at least persists the selected status bar so it's consistent between web and small screen.
https://github.com/user-attachments/assets/e4a58712-d940-4a8e-be3a-d8b3bdb33ccf

**Comment by luacmartins** [comment] 2024-08-20 19:07
I think the idea is to always reset the user. They can use saved searches (coming in v2.3) to navigate to any custom filters they have if they want to.
