### ISSUE TITLE
[$500] Room mention - Room mention is highlighted when different room is created from whisper

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#42637] opened 2024-05-27 14:48 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.76
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**If this was caught during regression testing, add the test name, ID and link from TestRail:** N/A
**Issue reported by:** Applause - Internal Team

**Issue found when executing PR** https://github.com/Expensify/App/issues/40857
## Action Performed:
1. Go to staging.new.expensify.com
2. Go to any room
3. Mention a non-existing room (#hello) and send it
4. Edit the message in Step 3 and add another word right behind the room mention (#helloworld)
5. Save the edit
6. Click Yes on the whisper room creation message

## Expected Result:
The new room mention in edit message in Step 4 will not be highlighted because the mentioned room is different from the room created from the whisper

## Actual Result:
The first half of the room mention is highlighted when the room mention is different

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [x] Android: mWeb Chrome
- [x] iOS: Native
- [x] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details> 

https://github.com/Expensify/App/assets/78819774/72c34807-6fe8-4325-8382-78249d5c5b3d

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01c628cdc0c39c744f</li>
        <li>Upwork Job ID: 1798161042106114048</li>
        <li>Last Price Increase: 2024-08-05</li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @allgandalf</details>

**Comment by lanitochka17** [comment] 2024-05-27 14:49
We think that this bug might be related to #vip-vsp

**Comment by anmurali** [comment] 2024-06-05 01:13
This seems like an edge case so I am going to make it a medium priority bug but if we get someone to fix it, great!

**Comment by NJ-2020** [comment] 2024-06-20 04:20
I think the issue is from the backend.

When we mentionned non-created room, the Concierge Expensify will ask the user to create the room because it doesn't exist. So when we edit the comment and change the room name, and click yes (before asking us to create room) to concierge expensify, the bot doesn't change the room name from updated comment.  For example: The bot asking to create room1 but when we changed the room name to room12, the bot doesn't update the room name.  So, when we click yes, the bot will wrap the room1 text only and do not wrap the `2` last character inside mention-room tag

But for the functionlity wraping text in the mention room tag is on the backend not on the frontend

**Comment by anmurali** [comment] 2024-07-08 19:52
Raised it to $500.

**Comment by huult** [comment] 2024-07-09 14:49
## Proposal

### Please re-state the problem that we are trying to solve in this issue.

The first half of the room mention is highlighted when the room mention is different

### What is the root cause of that problem?

We called an API to update a comment. I saw that the text was updated, but the last message HTML `mention-report` did not update yet. We then called `ResolveActionableReportMentionWhisper` to resolve the action report mention whisper with the report action ID, but it used the old, not updated text, causing the issue.

### What changes do you think we should make in order to solve the problem?

Check the `UpdateComment` API to see why the text did not update

### What alternative solutions did you explore? (Optional)

**Comment by FitseTLT** [comment] 2024-07-19 18:49
BE issue

**Comment by b4s36t4** [comment] 2024-07-19 20:17
I feel this issue is backend.

I'm not sure how backend is resolving the whisper message, we're receiving a new reportAction i.e whisper message with a param `reportNames` with the mention we've done. After we update the comment we're not receiving or updating the whisper message when we click `yes` for whisper message we're just sending the `reportActionID` for the whisper message.

I think we should update the whisper reportAction with the newly updated comment.

Maybe a new API call calling from frontend or backend directly can update the whisper report-action using the `updateComment` method itself.

**Comment by b4s36t4** [comment] 2024-07-24 13:03
@allgandalf hope you read the comments above, we think it's backend issue. Are you confident this can be solved from frontend that's why you're waiting for proposals or is there any other reason?!

**Comment by anmurali** [comment] 2024-08-06 03:14
This is on VIP VSB, which itself is paused at the moment. So let's close this issue for now and reopen down the line when we're prioritizing chat.

**Closed by anmurali** 2024-08-06 03:14 UTC
Labels: External, Daily, Help Wanted, Overdue, Bug
