### ISSUE TITLE
[HOLD for payment 2024-10-10] HOLD on #49532 [$250] Close account - Continue button becomes dysfunctional after closing an Expensifail account

### ISSUE THREAD

**Issue by IuliiaHerets** [Expensify/App#48941] opened 2024-09-10 20:58 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 9.0.31-12
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**Email or phone of affected tester (no customers):** applausetester+nl564@applause.expensifail.com
**Issue reported by:** Applause Internal Team

## Action Performed:
1. Sign up with a new Expensifail account on staging.new.expensify.com
2. Create a workspace
3. Close the account
4. Try to sign in with another account

## Expected Result:
Continue button takes user to the magic code page

## Actual Result:
Continue button stops working

## Workaround:
Unknown

## Platforms:

- [x] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

https://github.com/user-attachments/assets/47284513-d9be-41db-ae24-74ca2fe42686

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~021836048383075873170</li>
        <li>Upwork Job ID: 1836048383075873170</li>
        <li>Last Price Increase: 2024-09-17</li>
<li>Automatic offers: </li>
<ul>
<li>jjcoffee | Reviewer | 104042768</li>
<li>dominictb | Contributor | 104042769</li>
</ul></li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @muttmuure</details>

**Comment by IuliiaHerets** [comment] 2024-09-10 20:59
@muttmuure  FYI I haven't added the External label as I wasn't 100% sure about this issue. Please take a look and add the label if you agree it's a bug and can be handled by external contributors

**Comment by jjcoffee** [comment] 2024-09-17 15:20
Thanks for the [proposal](https://github.com/Expensify/App/issues/48941#issuecomment-2342484790) @dominictb!

> we call API update automatic timezone [here](https://github.com/Expensify/App/blob/1e8d80e850af52e60ec0fefbe11553cc196e8fee/src/libs/Navigation/AppNavigator/AuthScreens.tsx#L156), we don't check whether the current user account ID is available or not.

I'm not sure I understand why we call this only in this situation (closing an account), can you clarify that? It sounds almost like there's something missing when we close the account (e.g. some Onyx value that isn't being reset).

I'm also a bit confused overall on your RCA, are you saying that the `networkRequestQueue` never empties because the `updateAutomaticTimezone` call is returning an error and therefore retrying and clogging up the queue indefinitely?

**Comment by jjcoffee** [comment] 2024-09-18 14:46
> the currentAccountID is not cleared, it still stores the session.accountID value when we did not close account.

Isn't this the overall RCA here then? If we update `currentAccountID` once the account is deleted, it sounds like the issue would be solved. Or is there some reason for not doing that?

**Comment by jjcoffee** [comment] 2024-09-19 07:45
Sounds good! Let's go with @dominictb's [proposal](https://github.com/Expensify/App/issues/48941#issuecomment-2342484790), probably following the idea to set `currentAccountID` to `-1` (we may tweak this on the PR if necessary).

:ribbon::eyes::ribbon: C+ reviewed

**Comment by jjcoffee** [comment] 2024-09-20 10:18
@dominictb Hmm yeah I get the same on staging.

**Comment by jjcoffee** [comment] 2024-09-23 14:51
@dominictb Maybe you can try reverting the PR mentioned [here](https://github.com/Expensify/App/issues/49532#issuecomment-2367644133) in order to keep things moving on this?

**Comment by muttmuure** [comment] 2024-09-25 16:44
Not overdue

**Comment by jjcoffee** [comment] 2024-10-10 14:55
- The PR that introduced the bug has been identified. Link to the PR: https://github.com/Expensify/App/pull/23631/ (this seems like the ultimate source)
- The offending PR has been commented on, pointing out the bug it caused and why, so the author and reviewers can learn from the mistake. Link to comment: https://github.com/Expensify/App/pull/23631/files#r1795617216
- A discussion in #expensify-bugs has been started about whether any other steps should be taken (e.g. updating the PR review checklist) in order to catch this type of bug sooner. Link to discussion: N/A - closing account needed to be tested
- Determine if we should create a regression test for this bug. **Yes**
- If we decide to create a [regression test](https://github.com/Expensify/App/blob/main/contributingGuides/REGRESSION_TEST_BEST_PRACTICES.md) for the bug, please propose the regression test steps to ensure the same bug will not reach production again.

**Regression Test Proposal**

1. Sign up with a new account.
2. Close the account
3. With DevTools or logging open, try to sign in with another account. 
4. Verify there is no UpdateAutomaticTimezone call in the logs.
5. Verify that the continue button works normally, moving to the magic code page without any delay.

Do we agree 👍 or 👎

**Comment by jjcoffee** [comment] 2024-10-11 15:30
@muttmuure Friendly bump for payment, thanks! :pray:

**Closed** 2024-10-17 13:25 UTC
Labels: External, Daily, Overdue, Awaiting Payment, Bug
