### ISSUE TITLE
[$125] mWeb/Chrome - Scan - Flash icon appears then disappears in Scan tab

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#29442] opened 2023-10-12 13:41 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.3.83-1

**Reproducible in staging?:** Yes

**Reproducible in production?:** No. New feature on staging.

**If this was caught during regression testing, add the test name, ID and link from TestRail:**

**Email or phone of affected tester (no customers):**

**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Expensify/Expensify Issue URL:**

**Issue reported by:** Applause - Internal Team

**Slack conversation:**

## Action Performed:
1. Go to staging.new.expensify.com
2. Go to + > Request money > Scan
3. Give camera permission if not yet

## Expected Result:
Depending on whether flash is supported, the flash icon should either appear or not appear at all

## Actual Result:
When the Scan tab is first opened, the camera flash icon on the bottom right corner appears and then disappears

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [x] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [ ] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos
<details>
<summary>Android: Native</summary>

</details>

<details>
<summary>Android: mWeb Chrome</summary>

 

https://github.com/Expensify/App/assets/78819774/5aba5da8-10db-4285-8398-fb7f9c070d90

</details>

<details>
<summary>iOS: Native</summary>

</details>

<details>
<summary>iOS: mWeb Safari</summary>

</details>

<details>
<summary>MacOS: Chrome / Safari</summary>

</details>

<details>
<summary>MacOS: Desktop</summary>

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~019c363d1d939d77a1</li>
        <li>Upwork Job ID: 1712523919628128256</li>
        <li>Last Price Increase: 2023-10-12</li>
    </ul>
</details>

**Comment by mountiny** [comment] 2023-10-12 17:44
@hungvu193 is this regression from something?

**Comment by jasperhuangg** [comment] 2023-10-12 18:49
@mountiny @hungvu193 This appears to be a bug introduced from https://github.com/Expensify/App/pull/28411, specifically from [here](https://github.com/Expensify/App/pull/28411/files#diff-f2a35a2c175ff0433ef5de834e5e81ad53e89383a267027a8ea3980ebfc99700R243-R245)

Wouldn't say it's a regression just a bug that wasn't caught during testing since this behavior didn't exist before on mWeb

**Comment by AndrewGable** [comment] 2023-10-12 19:04
IMO this isn't a blocker and just something @lukemorawski can fix as a follow up

**Comment by yakupafsin** [comment] 2023-10-13 00:54
PROPOSAL (UPWORK)

In this situation, there are two straightforward solutions.

**Solution 1**: Make the default value of "isTorchAvailable" "false." This is a quick and easy solution, but it may result in a slight delay for users who have granted torch permissions.

However, I propose an alternative solution to address this issue.

**Solution 2**: Introduce an additional variable called "indicator" with a default value of "true." When we gather information about the availability of the torch, set "isTorchAvailable" to either true or false, and set "indicator" to the opposite of "isTorchAvailable." This allows us to determine whether we have received the necessary data and are ready to display the screen.

I've chosen this approach to keep the code concise.

When the user opens the camera, we will display an Activity Indicator that covers the full screen to hide the background, based on this condition: `if (isTorchAvailable === indicator)`.

For example:

```javascript
//...
const [isTorchAvailable, setIsTorchAvailable] = useState(true);
const [indicator, setIndicator] = useState(true);
//...
//...
<NavigationAwareCamera
  // ...
  // ...
  onTorchAvailability={(availability) => { setIsTorchAvailable(availability); setIndicator(!isPageLoaded); }}
  // ...
/>
//..
//..
//..
const mobileCameraView = () => {
  if (isTorchAvailable === indicator) {
    // Show the indicator
  } else {
    // Show the rest of the screen
  }
}

**Comment by yakupafsin** [comment] 2023-10-13 01:00
Contributor details
Your Expensify account email: yakupafsin422@gmail.com
Upwork Profile Link: https://www.upwork.com/freelancers/yakupa13

**Comment by cubuspl42** [comment] 2023-10-13 07:40
@yakupafsin In the future, stick to the proposal template. Be sure to read the [contributing guidelines](https://github.com/Expensify/App/blob/main/contributingGuides/CONTRIBUTING.md).

In the context of this issue, I think we're not looking for proposals right now, as @lukemorawski might just fix this in a follow-up.

**Comment by lukemorawski** [comment] 2023-10-13 12:17
@cubuspl42 Fixed the issue, creating a PR for that.

**Comment by mvtglobally** [comment] 2023-10-27 00:44
Issue not reproducible during KI retests. (First week)

**Comment by cubuspl42** [comment] 2023-10-27 09:01
I asked a question on https://github.com/Expensify/App/pull/29569 to classify the state of this issue

**Comment by mvtglobally** [comment] 2023-11-18 04:29
Issue not reproducible during KI retests. (Second week)

**Comment by mvtglobally** [comment] 2023-11-23 05:24
Issue not reproducible during KI retests. (Third week)

**Comment by kadiealexander** [comment] 2023-11-24 01:08
@allroundexperts @AndrewGable I also can't reproduce this, should we close it?

**Comment by allroundexperts** [comment] 2023-11-26 21:06
Yes, I think its safe to close this @kadiealexander.

**Closed** 2023-11-27 18:24 UTC
Labels: Reviewing, External, Monthly, Help Wanted, Bug
