### ISSUE TITLE
[HOLD for payment 2024-07-24] [$250]  Public room - User is able to leave public room when user is not logged in

### ISSUE THREAD

**Issue by izarutskaya** [Expensify/App#43404] opened 2024-06-10 17:20 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.81-3
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Issue reported by:** Applause-Internal team

## Action Performed:
1. Go to staging.new.expensify.com
2. Log out if logged in.
3. Navigate to public room link.
4. Click on the public room chat header.
5. Click Leave.

## Expected Result:
Login modal will open.

## Actual Result:
User is able to leave the public room, and the public room reappears.

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [x] Android: mWeb Chrome
- [x] iOS: Native
- [x] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

https://github.com/Expensify/App/assets/115492554/66258cfc-f7f9-4d83-b8fb-38cfaaae2c1c

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~012198a597d90e1a9d</li>
        <li>Upwork Job ID: 1800460939784883037</li>
        <li>Last Price Increase: 2024-06-11</li>
<li>Automatic offers: </li>
<ul>
<li>situchan | Reviewer | 102730618</li>
<li>codinggeek2023 | Contributor | 102730619</li>
<li>truph01 | Contributor | 102895803</li>
</ul></li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @greg-schroeder</details>

**Comment by izarutskaya** [comment] 2024-06-10 17:20
We think this issue might be related to the #vip-vsb

**Comment by Tony-MK** [comment] 2024-06-11 08:43
## Proposal

### Please re-state the problem that we are trying to solve in this issue.

Workspace - Error page when navigating to Workspace Join link after leaving the workspace

### What is the root cause of that problem?

The root cause of the problem is that in the `ReportDetailsPage` we use the `ReportUtils.canLeaveChat` function instead of the `ReportUtils.canLeaveRoom` function.

https://github.com/Expensify/App/blob/65db65069390cdd9fd386e087b6d8eed94ee22b0/src/pages/ReportDetailsPage.tsx#L207

### What changes do you think we should make in order to solve the problem?


Change the code snippet above and use the `ReportUtils.canLeaveRoom` function as shown below.

```
if (isGroupChat || (isChatRoom && ReportUtils.canLeaveRoom(report, isPolicyEmployee))) 
```

**Comment by TheGithubDev** [comment] 2024-06-11 11:17
### **Proposal**

### **Please re-state the problem that we are trying to solve in this issue:**
The problem is that an anonymous (not logged in) user can leave a public room by clicking the "Leave" button in the public room chat header. Instead of being prompted to log in, the user is able to leave the room, and the public room reappears.

### **What is the root cause of that problem?**
The root cause of this problem is that the leave action is not correctly checking for the user's authentication status before executing. The logic to handle the leave action does not verify if the user is logged in, allowing anonymous users to perform actions that should be restricted to authenticated users.

### **What changes do you think we should make in order to solve the problem?**
To address this issue, we need to:
1. **Add Authentication Check:**
   - Before executing the leave action, verify if the user is authenticated. If not, prompt the user to log in.

_Example of changes:_

1. **Add Authentication Check:**
- Update the leave action handler to include an authentication check. If the user is not logged in, show the login modal instead of allowing the leave action to proceed.

   ```javascript
   const handleLeaveRoom = () => {
       if (!isUserLoggedIn()) {
           showLoginModal();
           return;
       }

       // Proceed with the leave room action
       leavePublicRoom();
   };

   <Button onPress={handleLeaveRoom}>Leave</Button>
   

### **What alternative solutions did you explore?**
- Restricting UI elements: Instead of checking authentication in the leave action handler, we can disable or hide the "Leave" button for anonymous users.

- **Server-Side Validation:** We can implement server-side validation to ensure that only authenticated users can perform the leave action, adding an extra layer of security.

- **Different User Experience:** Also, by redirecting anonymous users to a different user experience flow where they can't see the "Leave" option at all, focusing instead on encouraging them to log in.

Please note that the above explanation outlines only the technical approach I plan to take. After my proposal is accepted, I will submit the finalized solution or code as mentioned.

Regards.

**Comment by truph01** [comment] 2024-06-11 18:05
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
User is able to leave the public room, and the public room reappears.

### What is the root cause of that problem?
When the user views the room before logged in, they are essentially "anonymous" users. So they're technically not part of the room yet, that's also the reason for the `Join the discussion.` CTA at the bottom of the public report.
<img width="262" alt="Screenshot 2024-06-12 at 12 53 37 AM" src="https://github.com/Expensify/App/assets/170341821/fe4837b7-ecc2-4c0d-9eca-19a2db670eb4">

So the anonymous user should only be able to join the room, not leave the room.

### What changes do you think we should make in order to solve the problem?

We should hide `Leave` button and show `Join` button for public room if the user is viewing anonymously.

1. In [canLeaveChat](https://github.com/Expensify/App/blob/81caf9878c4edf205bdb7f3df5b8fbb45220537e/src/libs/ReportUtils.ts#L6810), add the early return `false` if it's public room and the user is anonymous
```
if (isPublicRoom(report) && Session.isAnonymousUser()) {
    return false;
}
```
This will make sure the button is hidden in both the `ReportDetailsPage` and `HeaderView` of the report
<img width="329" alt="Screenshot 2024-06-12 at 1 05 15 AM" src="https://github.com/Expensify/App/assets/170341821/26bf2d3a-7ed7-4dc3-abfc-c7a39c8a19b2">

2. In [canJoinChat](https://github.com/Expensify/App/blob/81caf9878c4edf205bdb7f3df5b8fbb45220537e/src/libs/ReportUtils.ts#L6782), add early return `true` if it's public room and the user is anonymous
```
if (isPublicRoom(report) && Session.isAnonymousUser()) {
    return true;
}
```
<img width="291" alt="Screenshot 2024-06-12 at 1 04 45 AM" src="https://github.com/Expensify/App/assets/170341821/5c3782b7-a811-4993-874f-801241faf491">

### What alternative solutions did you explore? (Optional)
NA

**Comment by garrettmknight** [comment] 2024-06-13 13:38
@situchan can you have a look at these when you get chance? Thanks!

**Comment by situchan** [comment] 2024-06-13 19:12
> Login modal will open.

This is the expected result.

@codinggeek2023's [proposal](https://github.com/Expensify/App/issues/43404#issuecomment-2159156470) makes sense but I [asked author](https://github.com/Expensify/App/pull/41823/files#r1638759919) why `isAnonymousAction` was set to true before approving.

**Comment by situchan** [comment] 2024-06-13 19:18
Let's go with @codinggeek2023's [proposal](https://github.com/Expensify/App/issues/43404#issuecomment-2159156470)!
🎀👀🎀 C+ reviewed

**Comment by truph01** [comment] 2024-06-14 09:41
> Login modal will open.

@situchan I don't think this is the expected result. When the user views the public room as an anonymous user, the user isn't yet a part of the public room, so why should there be a `Leave` button?

There's also a `Join this discussion` CTA in the chat footer, it'd be confusing to the users to see both `Join` and `Leave` CTA on the same room.
<img width="262" alt="338693344-fe4837b7-ecc2-4c0d-9eca-19a2db670eb4" src="https://github.com/Expensify/App/assets/170341821/f8f53e76-2312-4c82-9369-69e318abc9d6">

@MonilBhavsar Could we postpone assignment until the expected result is clear? Thank you

**Comment by MonilBhavsar** [comment] 2024-06-14 09:56
Hmm, that's a good point 🤔 
@codinggeek2023 please hold

**Comment by situchan** [comment] 2024-06-17 04:33
> > Login modal will open.
> 
> @situchan I don't think this is the expected result. When the user views the public room as an anonymous user, the user isn't yet a part of the public room, so why should there be a `Leave` button?
> 
> There's also a `Join this discussion` CTA in the chat footer, it'd be confusing to the users to see both `Join` and `Leave` CTA on the same room. <img alt="338693344-fe4837b7-ecc2-4c0d-9eca-19a2db670eb4" width="262" src="https://private-user-images.githubusercontent.com/170341821/339718999-f8f53e76-2312-4c82-9369-69e318abc9d6.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTg1OTg5NzIsIm5iZiI6MTcxODU5ODY3MiwicGF0aCI6Ii8xNzAzNDE4MjEvMzM5NzE4OTk5LWY4ZjUzZTc2LTIzMTItNGM4Mi05MzY5LTY5ZTMxOGFiYzlkNi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNjE3JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDYxN1QwNDMxMTJaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT00YzViNDI1MzM0YmQ5ZmJkMzc3YzlmMDQ4MmVmYTdhZmZlZmJmMDYxNmY2NjkzZmM5NTkxZjMxMjJmOTgwZDZiJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.G_lc_g-hGiTprUgA8kmW-Uulq_B8FVKhWikaEm3f2EM">

@Expensify/design what do you think is the expected behavior?

**Comment by shawnborton** [comment] 2024-06-17 06:21
Yeah I don't know why we would show the "Leave" option if you were viewing a publicly viewable room that you weren't a member of. @JmillsExpensify @grgia maybe this was an oversight from the Details revamp project? Thoughts?

**Comment by truph01** [comment] 2024-06-24 08:40
@JmillsExpensify @grgia friendly bump on [this question](https://github.com/Expensify/App/issues/43404#issuecomment-2172378950), TIA

**Comment by grgia** [comment] 2024-06-24 09:54
@truph01 I agree this is an oversight. We shouldn't show the leave option if the user is not a member.

**Comment by truph01** [comment] 2024-06-24 17:35
@grgia Thanks for helping 🥇 

> @truph01 I agree this is an oversight. We shouldn't show the leave option if the user is not a member.

@situchan [My proposal](https://github.com/Expensify/App/issues/43404#issuecomment-2161335002) is doing just this, shall we go with it?

**Comment by situchan** [comment] 2024-06-24 17:37
@MonilBhavsar shall we reassign @truph01?

**Comment by truph01** [comment] 2024-06-24 17:48
Hey @eucool I don't think that'd be fair because our solutions are totally different.

And I believe @MonilBhavsar already told to [hold](https://github.com/Expensify/App/issues/43404#issuecomment-2167679309) so you didn't have to continue with the PR before the requirement is confirmed.

**Comment by truph01** [comment] 2024-06-25 18:54
> @MonilBhavsar shall we reassign @truph01?

@MonilBhavsar Friendly bump on [reassignment](https://github.com/Expensify/App/issues/43404#issuecomment-2187082122), thanks

**Comment by MonilBhavsar** [comment] 2024-06-27 05:39
Apologies for oversight in initial review. Since @truph01 proposal fixes the issue in an expected way, we'll assign them.
Thanks for understanding!

**Comment by truph01** [comment] 2024-06-27 18:12
@situchan PR https://github.com/Expensify/App/pull/44560 is ready

**Comment by garrettmknight** [comment] 2024-07-24 18:15
**Payment summary:**
- Contributor: @truph01 $250 paid via upwork
- Reviewer: @situchan $250 paid via upwork


@situchan can you fill out the checklist when you get a chance?

**Comment by garrettmknight** [comment] 2024-07-24 18:17
@greg-schroeder just handing this one off while I'm OOO - only awaiting the checklist. If it doesn't get done by the time I'm back I'll pick back up. Thanks!

**Comment by situchan** [comment] 2024-07-24 19:02
- [x] The PR that introduced the bug has been identified. Link to the PR: https://github.com/Expensify/App/pull/40529
- [x] The offending PR has been commented on, pointing out the bug it caused and why, so the author and reviewers can learn from the mistake. Link to comment: https://github.com/Expensify/App/pull/40529/files#r1690295516
- [x] A discussion in #expensify-bugs has been started about whether any other steps should be taken (e.g. updating the PR review checklist) in order to catch this type of bug sooner. Link to discussion: N/A

**Regression Test Proposal**
1. Log out if logged in.
2. Navigate to public room link.
3. Verify that "Join" button is displayed in the top right.
4. Click on the public room chat header.
6. Verify that there is no "Leave" button.

**Comment by greg-schroeder** [comment] 2024-07-24 22:55
Adding regression test 👍

**Closed by greg-schroeder** 2024-07-24 22:55 UTC
Labels: External, Daily, Awaiting Payment, Bug
