### ISSUE TITLE
[SMARTSCAN] [$500] MEDIUM: Update the workspace chat report preview component when a receipt scan completes

### ISSUE THREAD

**Issue by trjExpensify** [Expensify/App#26830] opened 2023-09-05 21:51 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
_Prerequisite: Use the example receipt provided below, because it will likely hit an image parser and complete super fast to test this._ 

1. Create a workspace on staging.new.expensify.com
2. Invite a member to it 
3. As the member, sign-in and navigate to your workspace chat on the workspace
4. Upload a receipt
5. Observe the "Receipt scan in progress..." report preview component 
6. Give it 15-30s or so to finish scanning
7. Navigate away from the workspace chat (i.e tap `<` to the LHN or click the report preview component)
8. Navigate back to the workspace chat

## Expected Result:
The report preview component should update with the receipt data automatically without needing to navigate away and back to the chat

## Actual Result:
The report preview component does not update

## Workaround:
Yes, as described above to navigate away and back. 

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [x] iOS / native
- [x] iOS / Safari
- [x] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** `v1.3.64-0`
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):** 
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** 

mWeb safari reproduction: 
https://github.com/Expensify/App/assets/16232057/019912f4-8c89-415f-92c6-8f1f363a033e

iOS native app reproduction:
https://github.com/Expensify/App/assets/16232057/2fa42280-be97-49d9-a62a-5de4699bf94c

Mac Chrome reproduction: 
https://github.com/Expensify/App/assets/16232057/13172aa7-0abe-435e-aa24-8e25e9225077

Example receipt to use: 
![SaaStr Sept4th Test Receipt](https://github.com/Expensify/App/assets/16232057/ccba8535-7403-4c9a-9afc-71ca140b3b12)

**Expensify/Expensify Issue URL:**
**Issue reported by:** @trjExpensify 
**Slack conversation:** [Internal](https://expensify.slack.com/archives/C057F53HR40/p1693947466270379?thread_ts=1693945772.531259&cid=C057F53HR40)

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

CC: @Gonals @MariaHCD @JmillsExpensify @dylanexpensify 
<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01eae90794b2b26fd4</li>
        <li>Upwork Job ID: 1699178450385817600</li>
        <li>Last Price Increase: 2023-10-02</li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @MariaHCD</details>

**Comment by s-alves10** [comment] 2023-09-06 13:10
This looks like a backend issue
When money request with receipt is finished, it returns the transaction with `{receipt: {state: SCANREADY}`
When scan is completed, this state is changed to `SCANCOMPLETE`. We need to receive pusher event for this scan status change, but no pusher event is received.
This is the root cause

**Comment by imranaalam** [comment] 2023-09-06 18:02
**Problem Statement**:  
Users who upload a receipt to a workspace chat encounter an issue where the "Receipt scan in progress..." preview doesn't automatically update to display the receipt data after the scan completes. The expected behavior is for this update to happen automatically, but users currently have to navigate away and return to the chat to see the updated data.

**Root Cause**:  
1. **Pusher Event Absence**: The application is designed to await a Pusher event to signal when the scan status transitions to `SCANCOMPLETE`. Our investigation suggests that this Pusher event isn't being received as anticipated.
2. **State Management & Rendering**: The `ReportPreview` component is closely tied to the Onyx state. If there's an inconsistency in how Onyx updates its state or if the component doesn't re-render in response to state changes, it can lead to the observed issue. The sections of code, especially those using `isReceiptBeingScanned()` and other related utilities, play a crucial role in this process.

**Proposed Solution**:  
1. **Pusher Event Logging**: Establish comprehensive logging for all incoming Pusher events. This action will confirm whether the `SCANCOMPLETE` event is getting lost in transit or not being sent at all.
2. **Backend Verification**: Delve deeper into the backend, ensuring that it's programmed to send the `SCANCOMPLETE` event. The backend should be reviewed to ascertain that the event emission process is flawless.
3. **Onyx State Checks**: Scrutinize the sections of the codebase where the Onyx state related to receipt scanning is adjusted. This scrutiny will ensure that the state updates appropriately after each receipt scan.
4. **Forced Component Refresh**: As a diagnostic tool, introduce a mechanism, even if temporary, to force the `ReportPreview` component to refresh at regular intervals. This approach can help clarify if the issue lies in the component's re-rendering mechanism or in the state management/data flow. 
```javascript
const [, forceUpdate] = useReducer(x => x + 1, 0);

useEffect(() => {
    const interval = setInterval(() => {
        forceUpdate();
    }, 5000);

    return () => clearInterval(interval);
}, []);
```

**Alternative Solution**:  
Should the Pusher event issue be confirmed, contemplate the initiation of a polling mechanism. This mechanism will carry out periodic checks on the receipt's state until its status reaches `SCANCOMPLETE`. While this might introduce some performance overhead compared to the real-time push mechanism, it can act as a temporary fix. However, the optimal long-term solution would be to rectify the Pusher event's emission and reception process.

**Comment by MonstaBug** [comment] 2023-09-06 18:03
The problem is scanning is async (on the backend) and we don't know when the scanning has been completed.
It worked when you switch between reports/chat because it refetchs the report data and then knows it has been completed.

So we either do polling or use pusher

**Comment by trjExpensify** [comment] 2023-09-11 11:02
@0xmiroslav @Gonals @MariaHCD, what do you think about this one. Should we take it internal?

**Comment by MariaHCD** [comment] 2023-09-13 03:56
Hmm, we already have a pusher event in the backend to update the transaction data in Onyx once the receipt scan is complete [here](https://github.com/Expensify/Web-Expensify/blob/e52adcddcdf860791fb123dde7c2f14301fef0d4/lib/ReceiptAPI.php#L551-L588)

Can we get the receiptID, perhaps there's something else we can find via the logs

**Comment by trjExpensify** [comment] 2023-09-13 11:45
Sure! Here's a fresh one with receiptID: `657488558` 

https://github.com/Expensify/App/assets/16232057/536f8afa-33bd-48d4-b205-28a0fb7268ed

**Comment by imranaalam** [comment] 2023-09-13 14:06
in case 1, 2 and 3 are ruled out as in https://github.com/Expensify/App/issues/26830#issuecomment-1708853270 then
no.4 can be tried i.e. 

Forced Component Refresh: As a diagnostic tool, introduce a mechanism, even if temporary, to force the ReportPreview component to refresh at regular intervals. This approach can help clarify if the issue lies in the component's re-rendering mechanism or in the state management/data flow.

**Comment by imranaalam** [comment] 2023-09-13 15:06
### Problem Statement:
Users who upload a receipt to a workspace chat encounter an issue where the "Receipt scan in progress..." preview doesn't automatically update to display the receipt data after the scan completes. Users currently have to navigate away and then return to the chat to see the updated data.

### Root Cause:
1. **Linked Transaction Retrieval**: The function `TransactionUtils.getLinkedTransaction` is pivotal for fetching the transaction details. If this function encounters delays or inconsistencies in retrieving transaction details, it can lead to discrepancies in the UI.
2. **State Management & Memoization**: The `OptionRowLHNData` component uses memoization to optimize rendering. If the variables it depends on, like `fullReport` or `linkedTransaction`, don't update correctly, the memoized value may not reflect the most recent state.
3. **Scanning State Determination**: The function `TransactionUtils.isReceiptBeingScanned` determines if a receipt is in the scanning process. If this function's logic isn't accurate or if the data it depends on isn't updated in real-time, it could lead to the observed issue.

### Proposed Solution:
1. **Data Verification**: Thoroughly inspect the `TransactionUtils.getLinkedTransaction` and `ReportActionsUtils.getParentReportAction` functions to ensure they always fetch accurate data.
2. **State Management Review**: In the `OptionRowLHNData` component, review the memoization logic. Ensure that all dependent variables are updating correctly. Introduce logging mechanisms to track these updates.
3. **Scanning State Check**: Deep dive into the `TransactionUtils.isReceiptBeingScanned` function. Ensure its logic correctly determines the scanning state. Verify where and how the data, determining the scanning state, gets updated.
4. **Enhanced Error Handling**: Strengthen error handling mechanisms. Implement comprehensive logging to capture any missing or inconsistent data.

### Alternative Solution:
1. **State Management Overhaul**: If the root cause is deeply embedded in the state management system or the memoization logic, consider revamping the state management strategy. This could involve moving away from memoization or using a different state management library.
2. **Backend Polling**: If real-time updates prove challenging, contemplate initiating a polling mechanism. This mechanism will periodically check the receipt's state until its status is `SCANCOMPLETE`. This can act as a temporary solution until the core issues are addressed.

**Comment by dylanexpensify** [comment] 2023-09-13 18:38
@MariaHCD were you able to find anything from @trjExpensify's [post](https://github.com/Expensify/App/issues/26830#issuecomment-1717469895)?

**Comment by s-alves10** [comment] 2023-09-14 00:10
I verified again that frontend doesn't receive the pusher event.
Can anyone check this?

**Comment by MariaHCD** [comment] 2023-09-14 06:45
Checking the [logs](https://www.expensify.com/_devportal/tools/logSearch/#query=request_id:(%22SIkoAQ%22)+AND+timestamp:[2023-09-13T10:42:31.939Z+TO+2023-09-13T12:42:31.939Z]&index=logs_expensify-024263) from @trjExpensify's test:

```
SIkoAQ | virt2.sjc | 2023-09-13 11:42:31 939 | tom@expensify.com | Hit - Updating transaction after applying rules ~~ transactionID: '2584992638075293377'
SIkoAQ | virt2.sjc | 2023-09-13 11:42:31 939 | tom@expensify.com | Hit - Updating transaction on a free policy expense report or IOU ~~ transactionID: '2584992638075293377'
SIkoAQ | virt2.sjc | 2023-09-13 11:42:31 939 | tom@expensify.com | Bedrock\Client - Starting a request ~~ command: 'EditMoneyRequest' clusterName: 'auth' headers: '[authToken: '<REDACTED>' transactionID: '2584992638075293377' modifiedExpenseReportActionID: '0' created: '2023-09-07' amount: '2000' currency: 'USD' comment: '' merchant: 'SaaStr Cantina' idempotent: '1' commitCount: '20765590422' requestID: 'SIkoAQ' lastIP: '' writeConsistency: 'ASYNC' priority: '500' timeout: '290000' logParam: 'we@dont.know']'
```

Looks like we definitely sent the data for the transactions key via pusher:

```
SIkoAQ | virt2.sjc | 2023-09-13 11:42:32 233 | tom@expensify.com | Expensify\Onyx - Sending command response via Pusher ~~ 0: '[onyxMethod: 'merge' key: 'transactions_2584992638075293377']'

SIkoAQ | virt2.sjc | 2023-09-13 11:42:32 349 | tom@expensify.com | Bedrock\Client - Starting a request ~~ command: 'InsertOnyxUpdates' clusterName: 'auth' headers: '[onyxData: '[0: '[updates: '[0: '[onyxMethod: 'merge' key: 'transactions_2584992638075293377' value: '[amount: '-2000' date: '2023-09-07' merchant: 'SaaStr Cantina' currency: 'USD' receipt: '[receiptID: '657488558' source: 'https://www.expensify.com/receipts/w_9c37363057a594c401dd7fb0d87ad4e971d0ec27.png' state: 'SCANCOMPLETE']']']']' accounts: '[0: '281396']']']' idempotent: '1' logParam: 'tom@expensify.com' commitCount: '20765590473' requestID: 'SIkoAQ' lastIP: '127.0.0.1' writeConsistency: 'ASYNC' priority: '500' timeout: '290000']'

SIkoAQ | virt2.sjc | 2023-09-13 11:42:32 391 | tom@expensify.com | [push] Push_Service - Sending chunked event ~~ name: 'multipleEvents' channel: 'private-encrypted-user-accountID-281396' data: '[lastUpdateID: '5441835' previousUpdateID: '5441832' updates: '[0: '[data: '[0: '[key: 'transactions_2584992638075293377' onyxMethod: 'merge' value: '[amount: '-2000' currency: 'USD' date: '2023-09-07' merchant: 'SaaStr Cantina' receipt: '[receiptID: '657488558' source: 'https://www.expensify.com/receipts/w_9c37363057a594c401dd7fb0d87ad4e971d0ec27.png' state: 'SCANCOMPLETE']']']']' eventType: 'onyxApiUpdate']']']'
```

**Comment by MariaHCD** [comment] 2023-09-14 06:46
> I verified again that frontend doesn't receive the pusher event.

@s-alves10 how are you verifying that the frontend doesn't receive the pusher event?

**Comment by s-alves10** [comment] 2023-09-14 07:18
I verified by log

**Comment by s-alves10** [comment] 2023-09-14 07:56
@MariaHCD 

Will you check if the `accountID` is correct from the log?

**Comment by MariaHCD** [comment] 2023-09-14 08:01
Just checked, the accountID in the channel we're sending to (`channel: 'private-encrypted-user-accountID-281396'` in https://github.com/Expensify/App/issues/26830#issuecomment-1718855492) definitely belongs to @trjExpensify

**Comment by trjExpensify** [comment] 2023-09-14 13:03
>Wasn't able to reproduce the issue on MacOS/Chrome on staging:

In the video of yours @MariaHCD you navigate to the expense report to wait for it to complete. If you stay on the workspace chat for a bit the report preview component should update but, but you'll notice in mine I have to navigate from it to get it to update. Here it is on MacOS Chrome: 

https://github.com/Expensify/App/assets/16232057/d7333f04-4a3e-4710-aedf-f19eef5107b4

**Comment by Gonals** [comment] 2023-09-15 02:46
It is not immediate, as parsing takes a little bit (more on staging/prod, as there are, potentially, many receipts, each of which creates a job with competing priorities), but this is working fine for me on dev, and the component is updated a few seconds after the job is completed, which is the expected behavior 🤷

**Comment by MariaHCD** [comment] 2023-09-15 07:20
> If you stay on the workspace chat for a bit the report preview component should update

Oh, interesting, I tested again and remained on the workspace chat. Definitely saw that it did not update the report preview 🤔


https://github.com/Expensify/App/assets/12268372/b9ec5fb9-4bdb-4a01-b496-cde34297bf62

@s-alves10 @0xmiroslav Can you double check if the transaction in Onyx is being updated with the receipt details as expected? Because we're definitely sending the transaction data via pusher in the backend and our logs do show the same as well. I wonder if it is the App that isn't rendering the updated transaction in the ReportPreview component [here](https://github.com/Expensify/App/blob/e884a5a4ef044d86a27d8cfbffe2e2e6a87099ff/src/components/ReportActionItem/ReportPreview.js#L121)?

**Comment by s-alves10** [comment] 2023-09-15 07:22
@MariaHCD 

No, the frontend doesn't receive the pusher events and so onyx transaction is not updated.

**Comment by MariaHCD** [comment] 2023-09-15 07:24
Would you mind giving me the email address that you tested with?

**Comment by s-alves10** [comment] 2023-09-15 07:37
I just ran a test with sangar.work1028+009@gmail.com

**Comment by MariaHCD** [comment] 2023-09-15 07:44
We definitely sent the pusher data for the Onyx key `transactions_1078602410102294240` 🤔 @s-alves10 can you confirm that was the Onyx data you checked?

```
x3T6ok | virt1.rno | 2023-09-15 07:26:43 237 | sangar.work1028+009@gmail.com | [push] Push_Service - Sending event ~~ channel: '[0: 'private-encrypted-user-accountID-14942190' 1: 'private-encrypted-user-accountID-14868802']' eventName: 'onyxApiUpdate' eventData: '[{"onyxMethod":"merge","key":"transactions_1078602410102294240","value":{"amount":-2000,"date":"2023-09-04","merchant":"SaaStr Cantina","currency":"USD","receipt":{"receiptID":658015732,"source":"https:\/\/www.expensify.com\/receipts\/w_f7f7171539b192e2ab2d0717e2fb9ee076681237.png","state":"SCANCOMPLETE"}}}]'

x3T6ok | virt1.rno | 2023-09-15 07:26:43 237 | sangar.work1028+009@gmail.com | [push] Push_Service - Sending chunked event ~~ channel: '[0: 'private-encrypted-user-accountID-14942190' 1: 'private-encrypted-user-accountID-14868802']' eventName: 'onyxApiUpdate' eventData: '[{"onyxMethod":"merge","key":"transactions_1078602410102294240","value":{"amount":-2000,"date":"2023-09-04","merchant":"SaaStr Cantina","currency":"USD","receipt":{"receiptID":658015732,"source":"https:\/\/www.expensify.com\/receipts\/w_f7f7171539b192e2ab2d0717e2fb9ee076681237.png","state":"SCANCOMPLETE"}}}]' chunkSize: '1'
```

**Comment by s-alves10** [comment] 2023-09-15 08:10
Let me check again

**Comment by s-alves10** [comment] 2023-09-15 08:38
Really strange. Frontend doesn't receive any events and transaction receipt status isn't updated.
The frontend does receive other events like message

**Comment by MariaHCD** [comment] 2023-09-18 08:53
Yeah, definitely weird. I'll try pointing my dev App to the staging API and see if the issue still occurs.

**Comment by trjExpensify** [comment] 2023-09-18 09:57
Thanks, @MariaHCD!

**Comment by MariaHCD** [comment] 2023-09-19 10:11
Focused on https://github.com/Expensify/Expensify/issues/316043 today. Getting to this tomorrow.

**Comment by MariaHCD** [comment] 2023-09-20 09:04
Tested the app locally while pointing to the staging API. And I do think there is some discrepancy between the Onyx data sent via Pusher after the scan completes and the Onyx data that is set once the report is opened 🤔 Specifically for the amount, merchant and currency fields.

Left: transaction Onyx data sent via Pusher after the scan is complete, Right: transaction Onyx data once OpenReport is called:

<img width="1410" alt="Screenshot 2023-09-20 at 4 47 59 PM" src="https://github.com/Expensify/App/assets/12268372/d3923f41-51b2-4131-b489-e64088a5b4b7">


Internal [logs](https://www.expensify.com/_devportal/tools/logSearch/#query=request_id:(%22fyWlII%22)+AND+timestamp:[2023-09-20T07:40:08.216Z+TO+2023-09-20T09:40:08.216Z]&index=logs_expensify-024373):

```
[updates: '[0: '[data: '[0: '[key: 'transactions_8138414820431815831' onyxMethod: 'merge' value: '[amount: '-2000' currency: 'USD' date: '2023-09-08' merchant: 'SaaStr Cantina (E)' receipt: '[receiptID: '659128384' source: 'https://www.expensify.com/receipts/w_75fe0ca9dfa7c03ca8c9f56da25bac00ec2bc099.png' state: 'SCANCOMPLETE']']']']' eventType: 'onyxApiUpdate']']' lastUpdateID: '14726669' previousUpdateID: '14726358']
```

**Comment by MariaHCD** [comment] 2023-09-20 09:05
@Gonals once the scan is complete and when we update the transactions Onyx key [here](https://github.com/Expensify/Web-Expensify/blob/9233378a27f36ed7e1fb140e3557e6de2f8d2e61/lib/ReceiptAPI.php#L551-L568), shouldn't we be setting the modifiedAmount, modifiedCurrency, modifiedMerchant fields instead of the amount, currency and merchant fields?

**Comment by MariaHCD** [comment] 2023-09-20 09:46
So two things potentially:
1. In the API, we should be setting the modifiedAmount, modifiedCurrency, modifiedMerchant fields [here](https://github.com/Expensify/Web-Expensify/blob/9233378a27f36ed7e1fb140e3557e6de2f8d2e61/lib/ReceiptAPI.php#L551-L568)
2. We might also need to update the `total` field in the report Onyx key since we use that in the report preview [here](https://github.com/Expensify/App/blob/3b821aa7e2418e1a9f4d710331e62d370e5fa5d3/src/components/ReportActionItem/ReportPreview.js#L110) so it seems like the amount doesn't update after the scan completes because we don't send the updated total in the Onyx data [here](https://github.com/Expensify/Web-Expensify/blob/9233378a27f36ed7e1fb140e3557e6de2f8d2e61/lib/ReceiptAPI.php#L551-L568)

Going to continue testing/investigating tomorrow.

**Comment by MariaHCD** [comment] 2023-09-21 04:48
Got a draft backend PR in place, I'll do some more testing.

**Comment by MariaHCD** [comment] 2023-09-25 06:48
Pushed the backend PR out for review. We can also test it on staging once it is deployed.

**Comment by MariaHCD** [comment] 2023-10-02 05:06
Backend PR was deployed. I tested on staging and the report preview is updated after the scan is complete:

https://github.com/Expensify/App/assets/12268372/9f30db92-c520-4a1a-b213-2755e7ab040e

However, I noticed two things:
1. The updated transaction details are actually pushed to Onyx pretty quickly but the changes take a while to show in the report preview. Could it be that the ReportPreview component isn't updating when the new transaction details are available? cc: @0xmiroslav 

<img width="1715" alt="Screenshot 2023-10-02 at 9 01 35 AM" src="https://github.com/Expensify/App/assets/12268372/01f0521d-c9c1-485e-b926-d12af4de44e3">

2. The report total was sent by the API as `0` so the report preview isn't showing the correct amount. Looking into this one. (internal [logs](https://www.expensify.com/_devportal/tools/logSearch/#query=request_id:(%22ffyqIs%22)+AND+timestamp:[2023-10-02T03:36:50.428Z+TO+2023-10-02T05:36:50.428Z]&index=logs_expensify-024563))

```
ffyqIs | virt1.sjc | 2023-10-02 04:36:50 561 | maria+2@expensifail.com | [push] Push_Service - Sending chunked event ~~ name: 'multipleEvents' channels: '[0: 'private-encrypted-user-accountID-8910926']' data: '[updates: '[0: '[data: '[0: '[key: 'transactions_7076274334862224452' onyxMethod: 'merge' value: '[modifiedAmount: '-2000' modifiedCreated: '2023-09-08' modifiedCurrency: 'USD' modifiedMerchant: 'SaaStr Cantina (E)' receipt: '[receiptID: '662139566' source: 'https://www.expensify.com/receipts/w_74b4d517c431235930da8283113164f8deefbabd.png' state: 'SCANCOMPLETE']']']' 1: '[key: 'report_3732056035654371' onyxMethod: 'merge' value: '[total: '0']']']' eventType: 'onyxApiUpdate']']' lastUpdateID: '19261406' previousUpdateID: '19261404']'
```

**Comment by trjExpensify** [comment] 2023-10-02 16:13
Ah, I think we can add `Reviewing` `Internal` and remove `Help Wanted` right, Maria?

**Comment by trjExpensify** [comment] 2023-10-03 12:14
Chill, Melv. We have PRs in review.

**Comment by MariaHCD** [comment] 2023-10-04 14:49
Continuing to look into this, specifically why the API isn't updating the report total in Onyx: https://github.com/Expensify/Web-Expensify/pull/38930#issuecomment-1742407366

**Comment by MariaHCD** [comment] 2023-10-05 15:48
Exploring a different approach for updating the report total, will test tomorrow:
- https://github.com/Expensify/Auth/pull/8860
- https://github.com/Expensify/Web-Expensify/pull/39087

**Comment by MariaHCD** [comment] 2023-10-06 08:37
Tests worked as expected. PRs are out for review:
- https://github.com/Expensify/Auth/pull/8860
- https://github.com/Expensify/Web-Expensify/pull/39087

**Comment by MariaHCD** [comment] 2023-10-11 09:14
PRs are merged, waiting on deploys so I can retest on staging

**Comment by mvtglobally** [comment] 2023-10-12 03:48
Issue not reproducible during KI retests. (First week)

**Comment by MariaHCD** [comment] 2023-10-18 12:27
I'll retest to see if this is still an issue

**Comment by kevinksullivan** [comment] 2023-10-19 15:19
Still seeing this issue and discussing here

https://expensify.slack.com/archives/C05RECHFBEW/p1697645050707899

**Comment by dylanexpensify** [comment] 2023-10-30 11:59
@0xmiroslav can you specify exactly what data the frontend needs, but isn't currently receiving from the API? Might help narrow this down

**Comment by dylanexpensify** [comment] 2023-11-07 16:46
bump @0xmiroslav

**Comment by kevinksullivan** [comment] 2023-11-14 00:12
Hi @0xmiroslav , still waiting on an update here. Can you please provide one?

**Comment by s-alves10** [comment] 2023-11-15 08:04
@0xmiroslav 

I think this is a backend only issue.

Fixing bug 2 or bug 3 would solve the bug 1 as well
We need 2 pusher events to update iou report and report preview action

**Comment by MariaHCD** [comment] 2023-11-15 11:46
Thanks, @0xmiroslav! I'm specifically looking into your suggestion of fixing bug 3 which is to ensure the Onyx data for the iouReport receives the updated total.

I think I see the issue. My backend fix [here](https://github.com/Expensify/Web-Expensify/pull/39087) missed accounting for the parser flow. Internals [logs](https://www.expensify.com/_devportal/tools/logSearch/#query=request_id:(%22erxsTJ%22)+AND+timestamp:[2023-11-15T05:14:28.106Z+TO+2023-11-15T07:14:28.106Z]&index=logs_expensify-025320). Fix here: https://github.com/Expensify/Web-Expensify/pull/39709, I don't know if there's a way to test it on dev so I can test once it's on staging.

**Comment by trjExpensify** [comment] 2023-11-22 13:10
@MariaHCD were you able to verify this latest backend fix?

**Comment by MariaHCD** [comment] 2023-11-27 06:58
Retested again today; looks like we sent the onyx data via pusher but seems like the frontend didn't receive it 😕 

Full internal [logs](https://www.expensify.com/_devportal/tools/logSearch/#query=request_id:(%22PudLU8%22)+AND+timestamp:[2023-11-27T05:44:49.752Z+TO+2023-11-27T07:44:49.752Z]&index=logs_expensify-025498):

- We sent the updated transaction and receipt data:

```
PudLU8 | 2023-11-27 06:44:50 178 | maria+1@expensifail.com | virt1.lax | src_unknown | [push] Push_Service - Sending event ~~ channel: '[0: 'private-encrypted-user-accountID-8977189' 1: 'private-encrypted-user-accountID-8910926']' eventName: 'onyxApiUpdate' eventData: '[{"onyxMethod":"merge","key":"transactions_463187291062335652","value":{"modifiedAmount":-2000,"modifiedCreated":"2023-09-08","modifiedMerchant":"SaaStr Cantina (E)","modifiedCurrency":"USD","receipt":{"receiptID":675977467,"source":"https:\/\/www.expensify.com\/receipts\/w_268e912cf8b5fbf74b2eee441ac4f2a5ba0c75f0.png","state":"SCANCOMPLETE"}}}]'
```

But it wasn't reflected in the frontend Onyx DB, the receipt state was still SCANREADY when it was already completed:

<img width="1722" alt="Screenshot 2023-11-27 at 10 52 16 AM" src="https://github.com/Expensify/App/assets/12268372/1cedc631-d937-4c6c-aefb-ca136c027a49">


- We also sent the updated report total:

```
PudLU8 | 2023-11-27 06:44:50 128 | maria+1@expensifail.com | virt1.lax | src_unknown | [push] Push_Service - Sending event ~~ channel: '[0: 'private-encrypted-user-accountID-8910926' 1: 'private-encrypted-user-accountID-8977189']' eventName: 'onyxApiUpdate' eventData: '[{"onyxMethod":"merge","key":"report_2891693584086895","value":{"total":-6000}}]'
```

But on the frontend the report total was not updated:

<img width="1724" alt="Screenshot 2023-11-27 at 10 52 29 AM" src="https://github.com/Expensify/App/assets/12268372/00601bef-79f4-40ca-8e74-010c84815c46">


Seems like something is going wrong with Pusher? Going to have to investigate further.

**Comment by dylanexpensify** [comment] 2023-11-30 19:20
Any updates here @MariaHCD? 🙇

**Comment by MariaHCD** [comment] 2023-12-06 11:40
From the discussion in Slack, we haven't identified any obvious issues, the pusher events are being sent successfully but not received. Will have to investigate further.

**Comment by MariaHCD** [comment] 2023-12-12 13:32
I was retesting this again today and it looks like the Onyx update was received by the App as expected:

For the requestor: The report preview is updated as expected - 

https://github.com/Expensify/App/assets/12268372/c2e97bcd-f1a0-4dbc-bb23-3c937dfaa2a1

**Comment by MariaHCD** [comment] 2023-12-12 13:33
However, for the payer: I see that the App is receiving the updated transaction data but the report preview isn't being updated, it only updates once the page is reloaded / the report is reopened -


https://github.com/Expensify/App/assets/12268372/a0e4fb0f-c387-4be7-bf3b-e18894fda4e8

@0xmiroslav @s-alves10 any ideas why the updated transaction data isn't being applied for the payer / workspace admin?

**Comment by MariaHCD** [comment] 2023-12-13 10:45
After digging into ^ some more, I think the since the report was a whisper, it was not present in the Onyx data for the payer/admin so when the API sends the [updated report total](https://github.com/Expensify/Web-Expensify/pull/39709), we do not have the complete data to show the report preview. So, the API should send the whole updated report instead of just the updated report total. I'll work on the PRs for this today.

**Comment by MariaHCD** [comment] 2023-12-14 14:32
Pushed both PRs out for review;
- https://github.com/Expensify/Auth/pull/9423
- https://github.com/Expensify/Web-Expensify/pull/40057

**Comment by kevinksullivan** [comment] 2023-12-22 18:05
@MariaHCD is this all set now that those PRs are merged + deployed?

**Comment by MariaHCD** [comment] 2024-01-01 11:57
Retested this since the relevant PRs were deployed and looks to work better now, the report preview takes a few seconds to update:

https://github.com/Expensify/App/assets/12268372/388c051f-fe76-480a-a006-a900a4a55b91

I think we can close this out but feel free to reopen if this still isn't working well.

**Comment by MariaHCD** [comment] 2024-01-04 10:39
@0xmiroslav @s-alves10 Looks like we're still having an issue with the total not being updated in the ReportPreview after the scan completes:

https://github.com/Expensify/App/assets/12268372/5a41011c-40fb-4a20-b8f3-4a70071ca709

The pusher update is definitely sent from the backend and received as shown in the console logs. The total was updated for the IOU report in Onyx. But it looks like the App didn't update the report preview. So could it be that the ReportPreview component not updating the total when the pusher event is received?

<img width="1726" alt="Screenshot 2024-01-04 at 2 25 58 PM" src="https://github.com/Expensify/App/assets/12268372/c1ab7131-abd7-493c-ac15-8ce4376ab162">

**Comment by MariaHCD** [comment] 2024-01-04 11:11
Although, it looks like we should be calculating the totalDisplaySpend using the total from the IOU report in Onyx:

https://github.com/Expensify/App/blob/d4c3e63956e9c14838592172c7e0e8596b0814cf/src/components/ReportActionItem/ReportPreview.js#L141

So I'm not sure why that doesn't seem to be working 100% correctly. My test on dev worked as expected:

https://github.com/Expensify/App/assets/12268372/6c13e1b0-4771-4ef2-af51-8c661c44b342

**Comment by s-alves10** [comment] 2024-01-05 08:35
@MariaHCD 

The current logic for calculating `totalDisplaySpend` is here
https://github.com/Expensify/App/blob/2d455bfb820b13fc83a5dd4057f19516faf2f238/src/libs/ReportUtils.ts#L1714-L1734

In our example, `nonReimbursableSpend + totalSpend` is equal to `0` and so `totalDisplaySpend` and `reimbursableSpend` would be 0

Can you please explain why `nonReimbursableSpend` is `2000` in this case? What does that mean?

**Comment by MariaHCD** [comment] 2024-01-08 14:30
Oh, interesting, so it seems when displayed correctly, the report total is set to the correct amount and nonReimbursableTotal is set at 0:

<img width="1719" alt="Screenshot 2024-01-08 at 6 28 56 PM" src="https://github.com/Expensify/App/assets/12268372/47317ef6-8318-4ae7-ab9c-37d09046913e">

Not familiar with where/why we set nonReimbursableTotal in the backend, but I'll take a closer look.

**Comment by MariaHCD** [comment] 2024-01-09 13:56
Notes for myself:
- Logs: https://www.expensify.com/_devportal/tools/logSearch/#query=request_id:(%22QEywtx%22)+AND+timestamp:[2024-01-04T09:21:27.059Z+TO+2024-01-04T11:21:27.059Z]&index=logs_expensify-026121
- Current theory is that since we're fetching the newly updated report in [postProcess](https://github.com/Expensify/Auth/blob/cd8c7537a676543f9fb2abc152680d2613fb5a47/auth/command/EditMoneyRequest.cpp#L461-L465), the update totals are not reflected correctly in the command response

**Comment by MariaHCD** [comment] 2024-01-25 11:13
The backend fixes were deployed to production a while ago so I retested this today and looks to be working better:


https://github.com/Expensify/App/assets/12268372/dae7a3af-48a4-4ce6-99d8-22288d6b7747


https://github.com/Expensify/App/assets/12268372/532fea1a-ac76-425b-a0e1-57a9c65a1eeb

**Closed by MariaHCD** 2024-01-25 11:13 UTC
Labels: Reviewing, Daily, Internal, Bug, SmartScan
