### ISSUE TITLE
[HOLD for payment 2024-11-05] [$250] mWeb -Chat - Cursor of compose box appears through options after long pressing message

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#50661] opened 2024-10-11 16:35 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 9.0.48-0
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**If this was caught during regression testing, add the test name, ID and link from TestRail:** N/A
**Email or phone of affected tester (no customers):** applausetester+uo1010@applause.expensifail.com
**Issue reported by:** Applause - Internal Team

## Action Performed:
1. Login to staging.new.expensify.com and open any chat with previous conversation
2. Tap on compose box into focus and make cursor appear
3. Long press a previously sent message

## Expected Result:
Options shown after long pressing message should be shown cleanly

## Actual Result:
Cursor of compose box is seen through options

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [x] iOS: mWeb Safari
- [ ] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

<details>
  <summary>Add any screenshot/video evidence</summary>

  
</details> 

https://github.com/user-attachments/assets/69d04a44-73ba-4a73-a8e4-9d3a32c50d1b

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~021845658365332298555</li>
        <li>Upwork Job ID: 1845658365332298555</li>
        <li>Last Price Increase: 2024-10-21</li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @adelekennedy</details>

**Comment by QichenZhu** [comment] 2024-10-12 10:31
## Proposal

### Please re-state the problem that we are trying to solve in this issue.

The caret in the composer appears above the report action context menu.

### What is the root cause of that problem?

In Safari, the caret is visible when the `Composer` is focused, even if the `Composer` is underneath other elements.

The `Composer` is focused because the context menu doesn't pass an `initialFocus` attribute to its focus trap.

https://github.com/Expensify/App/blob/e4969b22e7dbb1f6a200cc587ced4ab665415c0e/src/pages/home/report/ContextMenu/BaseReportActionContextMenu.tsx#L287

It then uses the default value `false`, which prevents any initial focus when the trap activates.

https://github.com/Expensify/App/blob/e4969b22e7dbb1f6a200cc587ced4ab665415c0e/src/components/FocusTrap/FocusTrapForModal/index.web.tsx#L7

### What changes do you think we should make in order to solve the problem?

We could set `initialFocus` to the element we want to focus by default in the context menu, or use `document.body` if we don’t have a specific element.

```TSX
<FocusTrapForModal active={!isMini} initialFocus={document.body}>
```

### What alternative solutions did you explore? (Optional)

N/A

**Comment by hungvu193** [comment] 2024-10-14 07:46
Thanks for your proposal @QichenZhu.
About your main solution, it will add initial focus to the first element of the modal (the first emoji).

https://github.com/user-attachments/assets/b8845980-81bd-4079-8539-3d3310c5c7fe

About the alternative solution, can you elaborate a little bit more about it?
`
Then explicitly set initialFocus to false in other places in the repo where we want to prevent initial focus.
`

**Comment by hungvu193** [comment] 2024-10-14 09:16
I think even when our `initialFocus` is `document.body`, I still can see the first emoji has outline. Can you check again?

> ## Proposal
> [Updated](https://github.com/Expensify/App/issues/50661#issuecomment-2408514358)
> 
> @hungvu193 Thanks for your review. If focusing the first emoji is unacceptable, we can focus `document.body` instead. Can you test if this is more acceptable?
> 
> The alternative solution changes the default `initialFocus` and affects some other instances, so we need to traverse the repo and manually set their `initialFocus` to the old default value `false`. The result will be the same as the main solution.

**Comment by QichenZhu** [comment] 2024-10-14 11:50
> I think even when our initialFocus is document.body, I still can see the first emoji has outline. Can you check again?

@hungvu193 Thanks for your time. Agreed that both `document.body` and `() => undefined` have the emoji outline issue. So I removed the `document.body` method and kept the `() => undefined` method for now.

I will revisit this issue if no better proposals come up.

**Comment by QichenZhu** [comment] 2024-10-15 08:40
@shoibsq Please format your proposal according to the [contributing guidelines](https://github.com/Expensify/App/blob/main/contributingGuides/CONTRIBUTING.md).

**Comment by hungvu193** [comment] 2024-10-16 02:20
Thanks for your proposals @shoibsq, I don't think your RCA is correct. This issue is only reproducible after we added `focus-trap-react`, adding `blur()` on showing overflow menu or forcing repaint composer feel like a workaround to me.

**Comment by CyberAndrii** [comment] 2024-10-16 16:43
Not reproducible anymore
v9.0.49-1

**Comment by hungvu193** [comment] 2024-10-17 02:47
Still reproducible on latest main.

https://github.com/user-attachments/assets/6721b5ef-44e4-4316-9ed6-610cd9f6a3ba

**Comment by hungvu193** [comment] 2024-10-17 02:48
Looking for proposals!

**Comment by CyberAndrii** [comment] 2024-10-17 16:26
## Proposal

### Please re-state the problem that we are trying to solve in this issue.

Caret of the compose box appears through the context menu after long-pressing a message

### What is the root cause of that problem?

> Still reproducible on latest main.

You're right - https://github.com/Expensify/App/pull/47621 was supposed to fix this but it was fixed only for text messages. This issue still exists when long pressing over transaction/photo/etc previews

<details>
<summary>Video</summary>

https://github.com/user-attachments/assets/8ecf2cfb-043e-4360-aa70-4bbbc070ff50

</details>

As discussed in https://github.com/Expensify/App/issues/44042, this is a platform related issue.

When long-pressing on a text message, `showContextMenu(...)` gets called from here

https://github.com/Expensify/App/blob/62302d5cacb2ff307b2e3a2bfc267a858a79bb4d/src/pages/home/report/ReportActionItem.tsx#L345

For previews (e.g., transaction/photo), it is called from here

https://github.com/Expensify/App/blob/20b7017e450689e1326ca64f7cecaeeb3346c19a/src/components/ShowContextMenuContext.ts#L56

The mentioned PR added a call to `blur()` only for the first case.

### What changes do you think we should make in order to solve the problem?

To make it work in all cases, we should move this line

https://github.com/Expensify/App/blob/62302d5cacb2ff307b2e3a2bfc267a858a79bb4d/src/pages/home/report/ReportActionItem.tsx#L342

into this function

https://github.com/Expensify/App/blob/62302d5cacb2ff307b2e3a2bfc267a858a79bb4d/src/pages/home/report/ContextMenu/ReportActionContextMenu.ts#L126-L147

```diff
 const show = () => {
+    ReportActionComposeFocusManager.blurAll();
     contextMenuRef.current?.showContextMenu(
     type,
...
```

If we don't want to apply this to all popups, we can add it here instead:

https://github.com/Expensify/App/blob/20b7017e450689e1326ca64f7cecaeeb3346c19a/src/components/ShowContextMenuContext.ts#L56

**Comment by hungvu193** [comment] 2024-10-21 01:52
Thanks for proposals everyone. I'll review again today

**Comment by hungvu193** [comment] 2024-10-22 09:45
@CyberAndrii I still can reproduce this issue with your solution, please checkout this testcase:
<details><summary>Testcase</summary>

https://github.com/user-attachments/assets/c6aef677-228d-4a65-87d0-b8f5a5ec671d


</details>

@bernhardoj Can you confirm if this diff match your solution? TIA

```diff
diff --git a/src/pages/home/report/ContextMenu/BaseReportActionContextMenu.tsx b/src/pages/home/report/ContextMenu/BaseReportActionContextMenu.tsx
index 5dbc38a4197..98f2b9dd921 100755
--- a/src/pages/home/report/ContextMenu/BaseReportActionContextMenu.tsx
+++ b/src/pages/home/report/ContextMenu/BaseReportActionContextMenu.tsx
@@ -110,7 +110,7 @@ function BaseReportActionContextMenu({
 }: BaseReportActionContextMenuProps) {
     const StyleUtils = useStyleUtils();
     const {translate} = useLocalize();
-    const {shouldUseNarrowLayout} = useResponsiveLayout();
+    const {shouldUseNarrowLayout, isSmallScreenWidth} = useResponsiveLayout();
     const menuItemRefs = useRef<MenuItemRefs>({});
     const [shouldKeepOpen, setShouldKeepOpen] = useState(false);
     const wrapperStyle = StyleUtils.getReportActionContextMenuStyles(isMini, shouldUseNarrowLayout);
@@ -284,7 +284,7 @@ function BaseReportActionContextMenu({
 
     return (
         (isVisible || shouldKeepOpen) && (
-            <FocusTrapForModal active={!isMini}>
+            <FocusTrapForModal active={!isMini && !isSmallScreenWidth}>
                 <View
                     ref={contentRef}
                     style={wrapperStyle}
diff --git a/src/pages/home/report/ContextMenu/PopoverReportActionContextMenu.tsx b/src/pages/home/report/ContextMenu/PopoverReportActionContextMenu.tsx
index fd48971ea5a..3a4c8beb56c 100644
--- a/src/pages/home/report/ContextMenu/PopoverReportActionContextMenu.tsx
+++ b/src/pages/home/report/ContextMenu/PopoverReportActionContextMenu.tsx
@@ -336,7 +336,7 @@ function PopoverReportActionContextMenu(_props: unknown, ref: ForwardedRef<Repor
                 shoudSwitchPositionIfOverflow={shoudSwitchPositionIfOverflow}
             >
                 <BaseReportActionContextMenu
-                    isVisible
+                    isVisible={isPopoverVisible}
                     type={typeRef.current}
                     reportID={reportIDRef.current}
                     reportActionID={reportActionIDRef.current}


```

**Comment by bernhardoj** [comment] 2024-10-22 10:47
You need to add 
```
onActivate: () => { 
    (document?.activeElement as HTMLElement)?.blur(); 
}, 
```

to FocusTrapForModal too.

**Comment by hungvu193** [comment] 2024-10-22 14:09
Thanks for the info. @bernhardoj 's [proposal](https://github.com/Expensify/App/issues/50661#issuecomment-2422967440) looks good and tested well.

🎀 👀 🎀 C+ reviewed

**Comment by bernhardoj** [comment] 2024-10-23 08:12
PR is ready

cc: @hungvu193

**Comment by bernhardoj** [comment] 2024-11-06 03:30
Requested in ND.

**Comment by hungvu193** [comment] 2024-11-06 03:33
- [x] The PR that introduced the bug has been identified. Link to the PR: https://github.com/Expensify/App/pull/43743
- [x] The offending PR has been commented on, pointing out the bug it caused and why, so the author and reviewers can learn from the mistake. Link to comment: https://github.com/Expensify/App/pull/43743/files#r1830344198
- [x] Determine if we should create a regression test for this bug: Yes

**Regression test:**
1. Go to any report.
2. Send a few messages.
3. Focus on the composer then long press on any message to open context menu.
4. Verify that Cursor shouldn't appear on context menu.

Do we 👍 or  👎 ?

**Comment by garrettmknight** [comment] 2024-11-06 11:49
$250 approved for @hungvu193

**Comment by JmillsExpensify** [comment] 2024-11-07 09:04
$250 approved for @bernhardoj

**Comment by JmillsExpensify** [comment] 2024-11-07 09:05
Also @adelekennedy for posterity can you fill out and confirm the payment summary above.

**Comment by adelekennedy** [comment] 2024-11-08 18:21
Payouts due:

- [ ] Reviewer: @hungvu193 owed $250 via NewDot

- [ ] Reviewer: @bernhardoj owed $250 via NewDot

**Closed** 2024-11-08 18:22 UTC
Labels: External, Daily, Awaiting Payment, Bug
