### ISSUE TITLE
[HOLD for payment 2022-12-20] [$1000] Android - Login - The transition after enter email and click "Continue" occurs with a jerk

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#13044] opened 2022-11-25 16:02 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Open the App
2. Enter the email on the email field
3. Click "Continue"

## Expected Result:
There should be no jerks in the transition

## Actual Result:
The transition after enter email and click "Continue" occurs with a jerk

## Workaround:
Unknown

## Platform:

Where is this issue occurring?

- Android

**Version Number:** 1.2.31.8

**Reproducible in staging?:** Yes

**Reproducible in production?:** Yes

**Email or phone of affected tester (no customers):** 

**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Notes/Photos/Videos:** Any additional supporting documentation

https://user-images.githubusercontent.com/93399543/204021611-88c055f7-10cf-4f1c-8bb1-d7551305f5d9.mp4

**Expensify/Expensify Issue URL:** 

**Issue reported by:** Applause - Internal Team

**Slack conversation:** 

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

## Upwork Automation - Do Not Edit
- Upwork Job URL: https://www.upwork.com/jobs/~01ef7c83ea1ccdd30c
- Upwork Job ID: 1597187869778264064

**Comment by laurenreidexpensify** [comment] 2022-11-28 11:16
- This is bug
- I have reproduced on my handset
- This isn't a duplicate
- The write up is complete

Sending to Upwork

**Comment by Someone-here** [comment] 2022-11-28 13:15
Yes, I'm trying to replicate and it is smooth on android API 33

**Comment by kbecciv** [comment] 2022-11-28 14:34
@railway17 Device info

![Screenshot_20221128-093317_Settings](https://user-images.githubusercontent.com/93399543/204303887-e5e7f2ea-667f-4a7c-8453-9537a84cba6c.jpg)

**Comment by aitoraznar** [comment] 2022-11-28 14:43
Proposal

My proposal is to not hide the keyboard when pressing "Continue" button. I found the line in which the keybaord is forced to be hidden. 

I also tested that the magic link and forgot password pages are shown. Also it works better in iOS.

```diff --git a/src/pages/signin/SignInPage.js b/src/pages/signin/SignInPage.js
index 574e96e6ca..1cf2472b49 100644
--- a/src/pages/signin/SignInPage.js
+++ b/src/pages/signin/SignInPage.js
@@ -68,8 +68,7 @@ class SignInPage extends Component {
         // Show the resend validation link form if
         // - A login has been entered
         // - AND is not validated or password is forgotten
-        const shouldShowResendValidationLinkForm = this.props.credentials.login
-            && (!this.props.account.validated || this.props.account.forgotPassword);
+        const shouldShowResendValidationLinkForm = this.props.credentials.login && showLoginForm === false && showPasswordForm === false;
 
         const welcomeText = shouldShowResendValidationLinkForm
             ? ''```

**Comment by railway17** [comment] 2022-11-28 17:46
### Proposal

#### 1. Reproducible.
I could reproduce this issue in smaller devices as I mentioned before:
The smaller,  the easier reproducible like below video.
https://www.loom.com/share/a55a68a30c7d4bd6b6813c2a703735f9. (My emulators are Galaxy Nexus 4.65", Pixel 3a 5.6" (_similar to @kbecciv 's testing device size_), Pixel 4)

#### 2. Why issue reproduced?
It is why Keyboard is hidden when submitting the LoginForm by `blurOnSubmit` (like @aitoraznar mentioned above).

#### 3. How to resolve?
Actually, I don't think we should change the `shouldShowResendValidationLinkForm` like @aitoraznar suggested because this variable is also used for `shouldShowWelcomeText` and `ResendValidationForm`.

We can just remove `blueOnSubmit` prop from `LoginForm` like below:
```diff
                     so that password managers can access the values. Conditionally rendering these components will break this feature. */}
-                    <LoginForm isVisible={showLoginForm} blurOnSubmit={shouldShowResendValidationLinkForm} />
+                    <LoginForm isVisible={showLoginForm} 
+                        // blurOnSubmit={shouldShowResendValidationLinkForm} 
+                    />
                     <PasswordForm isVisible={showPasswordForm} />
                     {shouldShowResendValidationLinkForm && <ResendValidationForm />}
```
I checked also the `blurOnSubmit` in `LoginForm`.  It is only used to force email input blur, but focus will be moved to password input when `PasswordForm` is loaded by the code that is written in `componentDidMount` of this component.
Result will like below:
https://www.loom.com/share/c59ed59611e941e59aa74ea10d62e71b

**Comment by huzaifa-99** [comment] 2022-11-28 18:33
### Proposal
We are always hiding the keyboard when going from `LoginForm` to `PasswordForm` screen. The reason why we are hiding keyboard has roots in this PR https://github.com/Expensify/App/pull/7604. 

In #7604 we added a change to hide keyboard when going from `LoginForm` to `ResetValidationForm` screen (creating a new account) which is a nice thing, but this change also made the keyboard hidden when going from `LoginForm` to `PasswordForm` screen.

So we only need to hide the keyboard when going from `LoginForm` to `ResetValidationForm` screen (when a new account is being created). To do that we can make these changes

```diff
     // Show the resend validation link form if
         // - A login has been entered
@@ -83,7 +87,7 @@ class SignInPage extends Component {
                 >
                     {/* LoginForm and PasswordForm must use the isVisible prop. This keeps them mounted, but visually hidden
                     so that password managers can access the values. Conditionally rendering these components will break this feature. */}
-                    <LoginForm isVisible={showLoginForm} blurOnSubmit={shouldShowResendValidationLinkForm} />
+                    <LoginForm isVisible={showLoginForm} blurOnSubmit={this.props.account.validated === false} />
                     <PasswordForm isVisible={showPasswordForm} />
                     {shouldShowResendValidationLinkForm && <ResendValidationForm />}
                 </SignInPageLayout>
```

The `this.props.account.validated` is `false` for a new account. The changes above will work for both redirections `Loginform -> PasswordForm` and `LoginForm -> ResendValidationForm`

### Demo

https://user-images.githubusercontent.com/68777211/204353695-599f3061-2e0c-4072-a84c-98a894011f57.mp4

**Comment by thesahindia** [comment] 2022-11-28 18:46
@huzaifa-99

**Comment by JmillsExpensify** [comment] 2022-11-29 17:57
I don't think this form is affected by passwordless, because you still need to enter your email address to sign-up for the app. So it's going to still exist. I think this is a pretty cosmetic bug but worth fixing if the corresponding solution is also straightforward.

**Comment by huzaifa-99** [comment] 2022-11-30 23:33
> > I think we should close this issue because we are going #passwordless
> 
> @thesahindia that's true. But the fix is really [easy](https://github.com/Expensify/App/issues/13044#issuecomment-1329560350) and affects a core flow of the app.
> 
> @JmillsExpensify do you think we should close this issue?

@rushatgabhane I am not sure if my proposal is accepted? (as you linked it in the comment)

**Comment by aitoraznar** [comment] 2022-12-01 10:38
Hi @rushatgabhane. 

The main goal of my work is always to fix the issue taking into account small improvement we can apply on the way. The selected proposal would work but it is not the best for the forahead of the project.

My proposal not only fixes this issue but also makes the code more clear than before. It makes more clear the case of when each screen should be shown and the `blurOnSubmit` is using a meaningful variable that is used in other parts of the code.

Cheers.

**Comment by pecanoro** [comment] 2022-12-01 16:12
@rushatgabhane I agree with you, it's the best proposal IMO. Though @huzaifa-99  instead of `this.props.account.validated === false`, you can simply do `!this.props.account.validated`.

**Comment by huzaifa-99** [comment] 2022-12-01 16:16
Hi @pecanoro. Hm, `!this.props.account.validated` was also passing when `validated` was `undefined` so just to be sure it is a non validated account (new account) I added a equality check for `false`

**Comment by huzaifa-99** [comment] 2022-12-01 16:24
@pecanoro applied on Upwork, PR will be up soon

**Comment by laurenreidexpensify** [comment] 2022-12-02 09:21
Offers sent in Upwork to @rushatgabhane @huzaifa-99

**Comment by laurenreidexpensify** [comment] 2022-12-05 12:25
still in review

**Comment by pecanoro** [comment] 2022-12-12 20:07
PR was merged, not overdue!

**Comment by laurenreidexpensify** [comment] 2022-12-20 11:33
Paid. Will start a regression test convo shortly.

**Comment by laurenreidexpensify** [comment] 2022-12-21 15:33
Regression testing is already covered [here](https://expensify.testrail.io/index.php?/cases/view/1971199&group_by=cases:section_id&group_order=asc&display_deleted_cases=0&group_id=229043)

**Closed** 2022-12-21 15:34 UTC
Labels: Reviewing, External, Daily, Awaiting Payment, Bug
