### ISSUE TITLE
[$500] LHN - "No activity yet message showed in LHN rooms with conv history after coming back online

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#30392] opened 2023-10-25 21:06 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.3.91-0
**Reproducible in staging?:** Yes
**Reproducible in production?:** Yes
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** Applause - Internal Team
**Slack conversation:**

## Action Performed:
1. Create a new applause.expensifail account on staging.new.expensify.com
2. Disable the internet connection in the device
3. Tap on the green plus button (FAB) and create a new Workspace
4. Navigate to LHN
5. Enter any of the new rooms and send some messages
6. Go back online

## Expected Result:
Last send message into workspace rooms should be visible in LHN when come back online

## Actual Result:
"No activity yet" message showed in LHN under workspace rooms

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [x] iOS: mWeb Safari
- [ ] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos
<details>
<summary>Android: Native</summary>

</details>

<details>
<summary>Android: mWeb Chrome</summary>

 

</details>

<details>
<summary>iOS: Native</summary>

</details>

<details>
<summary>iOS: mWeb Safari</summary>

 

https://github.com/Expensify/App/assets/78819774/63af195a-14d1-436e-9092-00ed120fd731

</details>

<details>
<summary>MacOS: Chrome / Safari</summary>

</details>

<details>
<summary>MacOS: Desktop</summary>

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~014dee0189b20922e7</li>
        <li>Upwork Job ID: 1717286481120063488</li>
        <li>Last Price Increase: 2023-11-01</li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @youssef-lr</details>

**Comment by alexpensify** [comment] 2023-10-26 17:14
@s77rt - do you agree with this feedback from @bernhardoj?

**Comment by s77rt** [comment] 2023-10-26 20:04
@alexpensify Yes! That makes sense to me. I have asked if that change was intended [here](https://github.com/Expensify/App/pull/29568#discussion_r1373755918). cc @youssef-lr

**Comment by youssef-lr** [comment] 2023-10-27 17:29
Yeah this looks like a regression from my PR. I added this change for the case of split bills that contain a receipt, the other participant receives a last message text from the backend which says "split $0.0" when the receipt is still being scanned, even though this last message is actually a whisper to the creator of the split. So I think proper way is to get it fixed in the backend and we can revert my change at line 306.

**Comment by s77rt** [comment] 2023-10-30 09:00
Should this be internal in that case?

**Comment by s77rt** [comment] 2023-11-01 16:33
Not overdue. Maybe internal? ^

**Comment by alexpensify** [comment] 2023-11-01 18:47
@youssef-lr can you check if we should take this internal and edit the tags here? Thanks!

**Comment by youssef-lr** [comment] 2023-11-01 20:25
Going to take this internal and assign it to myself

**Comment by alexpensify** [comment] 2023-11-03 16:45
Sounds good @youssef-lr, I'm going to assign you the primary role in this GH.

**Comment by youssef-lr** [comment] 2023-11-09 19:25
I'm planning to work on this this week.

**Comment by youssef-lr** [comment] 2023-11-13 19:38
Planning to get to this tomorrow.

**Comment by youssef-lr** [comment] 2023-11-15 05:20
I sadly didn't get around to working on this and I'm going OOO tomorrow. I think for now we can revert this [change](https://github.com/Expensify/App/issues/30392#issuecomment-1780469569) which should fix this issue, we can work on fixing the backend issue afterwards.

**Comment by alexpensify** [comment] 2023-11-16 20:47
Ok, we will wait for you to get back from OOO.

**Comment by alexpensify** [comment] 2023-11-29 19:43
Still waiting on @youssef-lr here, no update.

**Comment by alexpensify** [comment] 2023-12-06 18:57
@youssef-lr are you able to pick this one back up?

**Comment by youssef-lr** [comment] 2023-12-12 22:47
@alexpensify fixing this one in the backend turned out to be a bit complicated, I'm afraid fixing the query might significantly slow it down, I'm going to double check in eng-chat

**Comment by alexpensify** [comment] 2023-12-13 23:08
Thanks for the update!

**Comment by youssef-lr** [comment] 2023-12-22 08:55
I'm exploring an alternative solution, will report back here next week!

**Comment by alexpensify** [comment] 2023-12-23 18:48
Thank you @youssef-lr! 

**Heads up, I will be offline from Friday, December 22, to Thursday, January 4, 2024. I will not be actively watching over this GitHub during that period. If anything urgent is needed here, please ask for help in the #expensify-open-source Slack Room-- thanks!**

**Comment by youssef-lr** [comment] 2024-01-02 22:07
No update yet, I'm still on it. I should have an update by EOW.

**Comment by youssef-lr** [comment] 2024-01-15 01:15
It seems like the change we were planning to make is already in main, and still does not solve the issue. This seems like an issue with Onyx updates. I'm gonna keep investigating, but I think it's a low priority right now as the reproduction steps may not happen much in real world scenarios.

**Comment by youssef-lr** [comment] 2024-01-31 18:16
No update yet.

**Comment by youssef-lr** [comment] 2024-02-12 22:17
I haven't managed to get to this yet. I'm focusing on higher priority issues.

**Comment by youssef-lr** [comment] 2024-02-22 01:02
No update yet, still a low priority.

**Comment by youssef-lr** [comment] 2024-02-28 02:33
Same.

**Comment by youssef-lr** [comment] 2024-03-11 14:13
No update yet.

**Comment by youssef-lr** [comment] 2024-03-20 02:31
Same.

**Comment by youssef-lr** [comment] 2024-04-03 14:43
No update yet

**Comment by youssef-lr** [comment] 2024-04-18 21:49
Same.

**Comment by youssef-lr** [comment] 2024-05-01 00:20
No update yet.

**Comment by youssef-lr** [comment] 2024-05-09 20:10
No update yet, still a low priority.

**Comment by alexpensify** [comment] 2024-05-17 16:47
## Heads up, I will be offline until Tuesday, May 28, 2024, and will not actively watch over this GitHub during that period.

If anything urgent is needed here, please ask for help in the #expensify-open-source Slack Room-- thanks!

**Comment by youssef-lr** [comment] 2024-05-21 20:55
No update yet.

**Comment by youssef-lr** [comment] 2024-06-05 18:13
Same.

**Comment by youssef-lr** [comment] 2024-06-19 21:54
No update, probably worth retesting this it might have been resolved.

**Comment by youssef-lr** [comment] 2024-07-01 20:13
Couldn't reproduce this anymore, closing!

**Closed by youssef-lr** 2024-07-01 20:13 UTC
Labels: Engineering, Weekly, Internal, Overdue, Bug
