### ISSUE TITLE
iOS - QBD - The user isn't logged into OD after tapping on the link to fix the connection

### ISSUE THREAD

**Issue by IuliiaHerets** [Expensify/App#49386] opened 2024-09-18 12:24 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 9.0.37-0
**Reproducible in staging?:** Y
**Reproducible in production?:** N/A - new feature, doesn't exist in prod
**Issue was found when executing this PR:** https://github.com/Expensify/App/pull/48759
**Issue reported by:** Applause Internal Team

## Action Performed:
1. ND on web: Navigate to https://staging.new.expensify.com/
2. ND on web: Log in with a new Gmail account
3. ND on web: Create a workspace
4. ND on web: Navigate to OD by clicking on Account settings - Domains
5. OD on web: Navigate to Settings - Workspaces - "Created workspace name" - Connections
6. OD on web: Upgrade the WS to Collect with the lock icon next to "QuickBooks Desktop"
7. OD on web: Click on QuickBooks Desktop - Connect to QuickBooks Desktop - Connect to QuickBooks Desktop
8. OD on web: Attempt to connect to QuickBooks Desktop (the connection will fail)
9. iOS: Log off from OD on your default web browser
10. ND on IOS: Log in with the Gmail account used in steps 1-8
11. ND on iOS: Navigate to Account settings - Workspaces - "Created workspace name" - Accounting
12. ND on iOS: Tap on the link that takes you to OD

## Expected Result:
The user should be logged into OD and be taken to the page with the issue.

## Actual Result:
The user isn't logged into OD after tapping on the link to fix the connection issue. OD is logged in on Android and Mac.

## Workaround:
Unknown

## Platforms:

- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [x] iOS: Native
- [ ] iOS: mWeb Safari
- [ ] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

https://github.com/user-attachments/assets/12605ff2-4fa2-4bc4-a68e-3ece6b0a49a0

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by IuliiaHerets** [comment] 2024-09-18 12:24
We think that this bug might be related to #wave-collect - Release 1

**Comment by dylanexpensify** [comment] 2024-09-18 13:29
reviewing

**Comment by arosiclair** [comment] 2024-09-18 13:40
This is a brand new error message we just added in https://github.com/Expensify/App/pull/48759 so I'm leaning towards not blocking on this.

I agree the link should sign you in automatically though. @daledah @puneetlath can you take a look?

**Comment by dylanexpensify** [comment] 2024-09-18 13:40
@IuliiaHerets I can't reproduce as no button to take to OD via step 11. https://github.com/user-attachments/assets/309c5be9-2b85-4a47-a5c6-8ee4e0639ae0

**Comment by dylanexpensify** [comment] 2024-09-18 13:41
@arosiclair I don't even see a button to take me to ND here. Is this behind beta?

**Comment by dylanexpensify** [comment] 2024-09-18 13:41
See link above w/screen recording

**Comment by puneetlath** [comment] 2024-09-18 15:15
I don't think this needs to be a blocker. It's a new thing we added to make the error message more clear and we can handle making it log in on follow up. How do we do that elsewhere?

**Comment by arosiclair** [comment] 2024-09-18 16:22
Cool just demoted. Assigning you to follow up @puneetlath.

**Comment by IuliiaHerets** [comment] 2024-09-18 19:19
@dylanexpensify I believe that you used nit a latest build, it is a new feature, so this error message available only on the build 37-0 and higher

**Comment by puneetlath** [comment] 2024-09-20 14:59
I don't think we really expect policy editing on OldDot to work well on mobile well, so I feel like we should just close this. Please comment or reopen if you disagree.

**Closed by puneetlath** 2024-09-20 14:59 UTC
Labels: Daily, Bug
