### ISSUE TITLE
[$250] Negative amount displayed in Pay with Expensify Dropdown Button and Confirm payment amount Modal

### ISSUE THREAD

**Issue by m-natarajan** [Expensify/App#42325] opened 2024-05-16 22:21 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.74-4
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** @ikevin127 
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1715813045792699

## Action Performed:
Prerequisite : Have one existing account (A)  and one newly created account (B)

1. Login as new user (B) in a browser
2. On the “What do you want to do today?” modal choose “Manage my team's expenses” and Continue.
3, Input business name and Continue.
4. Input First and Last Name and Continue.
5. On the “Welcome” modal click Get Started.
6. Log in as an existing user (A) in incognito or in another browser
7. Click FAB > Submit expense > Manual > enter any amount and select the user B
8. Create one more IOU with user B to have 2 expenses report
9. Hold one of the expenses
10. Login to user B account and look for the IOU request from user A (If the report with the existing user does not show-up in LHN then click FAB > Start chat > Input existing user email and start a chat)
11. Once the chat opens, we should see the two report expenses requested by the existing user with the “Pay with Expensify” green dropdown button.
12. Click on the report preview showing “2 expenses” at the bottom in order to see the two expenses.
Notice that the report header “Pay with Expensify” green dropdown button shows negative amount like `-$7.00`.
13. Click on the “Pay with Expensify” green dropdown arrow button and notice that both options are showing negative amount.
After clicking on the dropdown arrow button > Select “Pay elsewhere”.
14. Click on the header “Pay elsewhere” button and notice that the “Confirm what to pay” modal also shows negative amount for both options.
## Expected Result:
-Report header  “Pay with Expensify” green dropdown button shows  the amount as positive amount 
-Clicking  on the header “Pay elsewhere” button “Confirm what to pay” modal also shows positive amount for both options.

## Actual Result:

- Notice that the report header “Pay with Expensify” green dropdown button shows negative amount like `-$7.00`.
- Click on the “Pay with Expensify” green dropdown arrow button and notice that both options are showing negative amount.
- After clicking on the dropdown arrow button > Select “Pay elsewhere”.
- Click on the header “Pay elsewhere” button and notice that the “Confirm what to pay” modal also shows negative amount for both options.

## Workaround:
unknown
## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence
![Screenshot 2024-05-10 at 21 54 05](https://github.com/Expensify/App/assets/38435837/52b7b6b3-379c-43c5-bfc1-9ceed272e304)

![Screenshot 2024-05-10 at 21 53 52](https://github.com/Expensify/App/assets/38435837/146925c0-1f3f-441a-9c15-facfbae5ff35)

https://github.com/Expensify/App/assets/38435837/a9a56919-16d4-4320-b4d8-159d256cc0c5

https://github.com/Expensify/App/assets/38435837/3b939592-6fea-49b7-9310-ae0bd73ce4ab

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01cc7f63f52440c4db</li>
        <li>Upwork Job ID: 1800107311798006347</li>
        <li>Last Price Increase: 2024-06-17</li>
<li>Automatic offers: </li>
<ul>
<li>alitoshmatov | Reviewer | 102858943</li>
<li>dominictb | Contributor | 102858945</li>
</ul></li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @zanyrenney</details>

**Comment by ikevin127** [comment] 2024-05-16 22:45
To me this looks BE-related if we look at the transaction amounts (see C+ [Slack 🧵](https://expensify.slack.com/archives/C02NK2DQWUX/p1715403954198329)) being a positive number, considering it should be negative as that's how we store it in BE and since we have logic [here](https://github.com/Expensify/App/blob/e8ae3c5acedf0e6788dc574c7b6f3043ca37092a/src/libs/TransactionUtils.ts#L282-L306), [here](https://github.com/Expensify/App/blob/e8ae3c5acedf0e6788dc574c7b6f3043ca37092a/src/libs/TransactionUtils.ts#L347-L353) and other places in FE in order to make it positive.

> [!note]
> If this is BE related, I'd look at the “What do you want to do today?” Modal -> “Manage my team's expenses” flow.

But could also be some mix-up on the FE, not entirely sure 🤔

**Comment by zanyrenney** [comment] 2024-05-20 17:44
Thanks for adding these thoughts @ikevin127 !

**Comment by zanyrenney** [comment] 2024-05-20 17:47
checking here - https://expensify.slack.com/archives/C01GTK53T8Q/p1716227156290099

**Comment by zanyrenney** [comment] 2024-05-24 15:51
Seeing as this is a BE issue and noone has volunteered for it in slack. I think we should reopen if we encounter this via a real user flow rather than the slightly complex reproduction steps above.

**Comment by lanitochka17** [comment] 2024-05-27 19:51
Issue is still reproducible on the latest build 1.4.76-2


https://github.com/Expensify/App/assets/78819774/e76f33be-0243-4fbb-acac-f96aff6f879e

**Comment by zanyrenney** [comment] 2024-06-10 10:06
Been OOO, this reopened whilst I was out.

**Comment by zanyrenney** [comment] 2024-06-10 10:06
As it's still reproducible, assigning external.

**Comment by zanyrenney** [comment] 2024-06-12 09:56
@alitoshmatov please can you review the proposal?

**Comment by zanyrenney** [comment] 2024-06-17 14:29
bump @alitoshmatov please review the proposal?

**Comment by zanyrenney** [comment] 2024-06-17 14:31
bumped in open source: https://expensify.slack.com/archives/C01GTK53T8Q/p1718634671704649

**Comment by alitoshmatov** [comment] 2024-06-18 10:03
_This issue is reproducable without any additional steps. You just need to hold one of the iou transactions and receiving user sees total amount as negative_


To expand more I do agree with @ikevin127 's take [here](https://github.com/Expensify/App/issues/42325#issuecomment-2116321980)

It looks like we are treating expense amount as negative numbers in multiple instances, also this [comment](https://github.com/Expensify/App/blob/a451de460c45611f64bcd06961afb78b4e2f3c9b/src/libs/ReportUtils.ts#L3883) indicates the same conclusion. 

But this positive amount is working completely fine when using iou normally without holding any transaction.

Before we proceed we should make clear expected values here, @zanyrenney we internal engineer to look at this comments and answer to the following question:
- Are `total` and `unheldTotal` values positive or negative values?
 
<img width="548" alt="Screenshot 2024-06-18 at 3 02 13 PM" src="https://github.com/Expensify/App/assets/59907218/bc269914-c99f-4aee-b57c-0b5c2ec649f2">

**Comment by alitoshmatov** [comment] 2024-06-23 19:30
@dominictb Oh I see, I understand now. I confused iou and expense reports with each other. I was focused on 1:1 chats and testing `iou` report only. I forgot to test workspace chats where `expanse` reports are created.

**Comment by alitoshmatov** [comment] 2024-06-23 19:30
We can go with @dominictb 's [proposal](https://github.com/Expensify/App/issues/42325#issuecomment-2157971423)

C+ reviewed 🎀 👀 🎀

**Comment by blimpich** [comment] 2024-06-24 17:34
This confused me for a minute and I had to read through the discussions and look at the code for awhile but it does make sense to me that this is a frontend issue. Appears that we overlooked this particular scenario when implementing the hold functionality for reports.

**Comment by alitoshmatov** [comment] 2024-06-27 20:44
@blimpich Can you elaborate, which part you think we have a problem. Is this the fact that amounts are in negative when in expanse reports and positive in iou reports? 

Should we pause PR or go on with proposed solution?

**Comment by blimpich** [comment] 2024-06-27 21:16
Go with the proposed solution, sorry, my comment was worded poorly. When I say "we overlooked" I don't mean you and @dominictb, I mean the original implementors of this code that we are now fixing.

Please proceed forward with the proposed solution.

**Comment by blimpich** [comment] 2024-07-22 19:22
Did we ever pay out for this issue? @zanyrenney can you make sure we paid for the work done here? I think maybe the automation failed?

**Comment by alitoshmatov** [comment] 2024-07-26 10:47
The PR was deployed to production on july [16th](https://github.com/Expensify/App/pull/44439#issuecomment-2229331244)

**Comment by alitoshmatov** [comment] 2024-08-01 08:16
We can complete the payment and close the issue

cc: @blimpich @zanyrenney

**Comment by alitoshmatov** [comment] 2024-09-03 17:33
@blimpich @zanyrenney

Bump

**Comment by blimpich** [comment] 2024-09-03 17:44
Sorry for the delay @alitoshmatov!

@zanyrenney can we get payment completed and close out this issue soon?

**Comment by zanyrenney** [comment] 2024-09-04 16:18
Sure thing @blimpich - on it now.

**Comment by zanyrenney** [comment] 2024-09-04 16:20
**Payment summary**

paid @alitoshmatov  $250 via upwork
paid @dominictb $250 via upwork.

**Closed by zanyrenney** 2024-09-04 16:20 UTC
Labels: External, Daily, Awaiting Payment, Bug
