### ISSUE TITLE
[HOLD for payment 2024-05-16] [$250] mWeb - BA - Buttons are not visible at first glance on Onfido terms page

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#40941] opened 2024-04-24 21:00 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.65-4
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**If this was caught during regression testing, add the test name, ID and link from TestRail:** https://expensify.testrail.io/index.php?/tests/view/4507599
**Email or phone of affected tester (no customers):** applausetester+vd_mweb042424@applause.expensifail.com
**Issue reported by:** Applause - Internal Team

## Action Performed:
Pre-requisite: the user must be logged in, have created a collect Workspace and have enabled Workflows
1. Go to Workspace > Workflows > Connect bank account
2. Select "Connect manually" and use the testing routing number and account number
3. On Personal info page, enter "First" and "Last" for first name and last name
4. Enter any other information on the rest of the Personal info pages and confirm
5. On the Onfido terms page, verify the "Accept" and "Do not accept" buttons are not visible at first glance
6. Scroll down the text to the bottom, verify that the buttons are not visible yet
7. Scroll down the page by scrolling from the bottom of the page (under the text)
8. Verify the buttons are now visible.

## Expected Result:
The buttons should be completely visible at first glance

## Actual Result:
The buttons are hidden until the user scrolls down the page

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [x] iOS: mWeb Safari
- [ ] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details> 

https://github.com/Expensify/App/assets/78819774/393445d5-da79-4941-9cb2-5db5165386e2

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01a29e77d6361f0ee0</li>
        <li>Upwork Job ID: 1783556114373173248</li>
        <li>Last Price Increase: 2024-04-25</li>
<li>Automatic offers: </li>
<ul>
<li>samilabud | Contributor | 0</li>
</ul></li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @garrettmknight</details>

**Comment by lanitochka17** [comment] 2024-04-24 21:00
@garrettmknight  FYI I haven't added the External label as I wasn't 100% sure about this issue. Please take a look and add the label if you agree it's a bug and can be handled by external contributors

**Comment by garrettmknight** [comment] 2024-04-25 17:54
Reproduced - I think this is an important bug to fix to enable users to connect bank accounts.

**Comment by skyweb331** [comment] 2024-04-26 22:56
I tried to reproduce but for me, Step 3 is not ONFIDO, how can I see it?

**Comment by samilabud** [comment] 2024-04-26 22:57
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
mWeb - BA - Buttons are not visible at first glance on Onfido terms page

### What is the root cause of that problem?
We are using embedded content (OnFido) to load the terms, this comes with iframes that are out of our control, the first iframe comes with a height of 100% this is the root cause of why the content of the first iframe (the terms) is the only visible thing here, this is the cause of the double scroll bar.

### What changes do you think we should make in order to solve the problem?
We should use Javascript to get the viewPortHeight when the page load, later select the first iframe (the terms content) and specify the 80% of the getted height and set this one to the mentioned iframe, this modification should be done in [Onfido component](https://github.com/Expensify/App/blob/main/src/components/Onfido/index.tsx) inside the useEffect that already exist, like:

```
useEffect(() => {
        const onfidoOut = baseOnfidoRef.current?.onfidoOut;

        const observer = new MutationObserver(() => {
            const fidoRef = baseOnfidoRef.current;
            if (fidoRef) {
                // eslint-disable-next-line @typescript-eslint/no-unnecessary-type-assertion
                const onfidoSdk = fidoRef.querySelector('#onfido-sdk > iframe') as HTMLElement | null;
                if (onfidoSdk) {
                    const viewportHeight = window.innerHeight; // Get the viewport height
                    const desiredHeight = viewportHeight * 0.8;
                    onfidoSdk.style.height = `${desiredHeight}px`;
                }
            }
        });
        if (baseOnfidoRef.current) {
            observer.observe(baseOnfidoRef.current, {attributes: false, childList: true, subtree: true});
        }

        if (!onfidoOut) {
            return;
        }

        onfidoOut.tearDown();

        // Clean up function to remove the observer when component unmounts
        return () => {
            observer.disconnect();
        };
    }, []);
```
**Below some tests:**
Android mWeb test:

https://github.com/Expensify/App/assets/5216036/86e8a706-021c-4ade-9767-7244766c47ca

Mac Chrome test:

https://github.com/Expensify/App/assets/5216036/18a58cc5-7731-45c2-ab95-d14846d124c7

**Comment by mananjadhav** [comment] 2024-04-29 09:31
I think @samilabud's proposal will work. What I am not sure is should we be using `querySelector` this way.

🎀 👀 🎀 C+ reviewed.

**Comment by garrettmknight** [comment] 2024-04-29 11:41
@mananjadhav can you give this proposal a review when you get a chance?

**Comment by luacmartins** [comment] 2024-04-29 16:24
Solution LGTM.

**Comment by garrettmknight** [comment] 2024-05-13 16:40
Went to prod 5 days ago, updating.

**Comment by garrettmknight** [comment] 2024-05-16 18:57
**Payment Summary:**
- @samilabud - $250 paid via Upwork
- @mananjadhav - $250 - offer outstanding in Upwork

**Comment by mananjadhav** [comment] 2024-05-16 19:26
@garrettmknight I'll be raising my request on NewDot. Just the payout summary will suffice.

**Comment by garrettmknight** [comment] 2024-05-16 19:31
Sounds good - can you complete the checklist before raising the request? Thanks!

**Comment by mananjadhav** [comment] 2024-05-16 19:33
Sure. We don't have any offending PR for this one. This was due to onFido an external dependency and how iframe layouts work. Assuming that this test already exists, I don't think we need a regression test for this one.

**Comment by JmillsExpensify** [comment] 2024-05-19 14:02
Based on the above, $250 approved for @mananjadhav

**Comment by garrettmknight** [comment] 2024-05-20 18:04
All good, closing

**Closed by garrettmknight** 2024-05-20 18:04 UTC
Labels: External, Daily, Awaiting Payment, Bug
