### ISSUE TITLE
[$250] BUG: When image is uploading, text typed in compose box disappears when image finishes uploading

### ISSUE THREAD

**Issue by kavimuru** [Expensify/App#11491] opened 2022-10-01 00:50 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:

1. Send an image to a test account
2. Immediately after, while the image is uploading, start typing text in the compose box

## Expected Result:
The text to stay in the compose box once image is finished uploading

## Actual Result:
Text disappears once image is uploaded

## Workaround:
unknown

## Platform:

Where is this issue occurring?

- Desktop App

**Version Number:** 1.2.11-0
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**Email or phone of affected tester (no customers):** 
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** 

https://user-images.githubusercontent.com/43996225/193376563-a574b2fa-2c57-45a5-8edd-ca2eee2de0b4.mp4
https://user-images.githubusercontent.com/43996225/193376564-bceb7aa0-d5af-4dd9-a408-a117cda46b85.mp4

**Expensify/Expensify Issue URL:** 
**Issue reported by:** @mallenexpensify 
**Slack conversation:** https://expensify.slack.com/archives/C01GTK53T8Q/p1664500797574529

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by NicMendonca** [comment] 2022-10-03 11:57
Keeping my assignment for contributor management cc @cead22 (once you add `external`)

**Comment by tienifr** [comment] 2022-10-05 16:15
# Proposal

## Problem
Originally, reportID is string.
When we add comment or add attachment, the result is returned from API updated the reportID as number. Pls look at evidence below

<img width="404" alt="Screen Shot 2022-10-05 at 22 35 00" src="https://user-images.githubusercontent.com/113963320/194109715-5171e1f8-9093-4738-906f-002405d93f25.png">

That make `this.props.report.reportID === prevProps.report.reportID` is false and then trigger function `this.updateComment(this.props.comment);`. At that time, `this.props.comment` is empty as default
=> text typed in compose box disappears

https://github.com/Expensify/App/blob/f710d78315fba055625278a1f7e20f9db6d08014/src/pages/home/report/ReportActionCompose.js#L182-L187

## Solution

We'll use this.props.reportID instead of this.props.report.reportID because reportID is converted to string  when we pass to `ReportActionCompose`

https://github.com/Expensify/App/blob/f710d78315fba055625278a1f7e20f9db6d08014/src/pages/home/report/ReportFooter.js#L94-L100

In https://github.com/Expensify/App/blob/f710d78315fba055625278a1f7e20f9db6d08014/src/pages/home/report/ReportActionCompose.js#L182-L187

```diff
-        if (this.props.report.reportID === prevProps.report.reportID) {
+        if (this.props.reportID === prevProps.reportID) {

```

https://user-images.githubusercontent.com/113963320/194109824-d80c031a-ed94-463d-bd09-c2ea54b0b6a4.mp4

**Comment by NicMendonca** [comment] 2022-10-05 16:42
job posting: https://www.upwork.com/jobs/~0150e2e60ca2565c8b

**Comment by youssef-lr** [comment] 2022-10-07 14:47
Can't reproduce this in staging anymore, there was a server-side fix [here](https://github.com/Expensify/Web-Expensify/pull/35072) that potentially solves this.

**Comment by thesahindia** [comment] 2022-10-07 15:02
@NicMendonca, let's close this.

**Closed** 2022-10-07 15:52 UTC
Labels: External, Engineering, Daily, Improvement, Help Wanted

**Comment by mallenexpensify** [comment] 2022-10-08 00:21
Also can't repro
