### ISSUE TITLE
[HOLD for payment 2023-10-30] [$500] API - 404 Returns On AuthenticatePusher API

### ISSUE THREAD

**Issue by m-natarajan** [Expensify/App#29116] opened 2023-10-09 18:45 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.3.79-3
**Reproducible in staging?:** Yes
**Reproducible in production?:** Yes
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** @ufumerfarooq
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1696624674221279

## Action Performed:
1. Open ND App
2. Login
3. Open Developer Tools -> Navigate to Network Tab
4. Observe Results (There is 404 error on ?AuthenticatePusher api and on carefully observing the request base url, it's "https://staging.expensify.com/" not "https://staging.new.expensify.com/")
5. Go to Console tab and observer results (There is related CORS error for this)
## Expected Result:
200 OK response should be received
## Actual Result:
404 NOT FOUND received
## Workaround:
Unknown
## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos
<details>
<summary>Android: Native</summary>

</details>

<details>
<summary>Android: mWeb Chrome</summary>

</details>

<details>
<summary>iOS: Native</summary>

</details>

<details>
<summary>iOS: mWeb Safari</summary>

</details>

<details>
<summary>MacOS: Chrome / Safari</summary>

https://github.com/Expensify/App/assets/38435837/59f8b537-09c2-4137-938f-1907f63fce68

https://github.com/Expensify/App/assets/38435837/ac9ea732-bbb0-468e-858d-be0a69f578c3

</details>

<details>
<summary>MacOS: Desktop</summary>

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01eb77836e6080236f</li>
        <li>Upwork Job ID: 1711452980972335104</li>
        <li>Last Price Increase: 2023-10-09</li>
<li>Automatic offers: </li>
<ul>
<li>fedirjh | Reviewer | 27184951</li>
</ul></li>
    </ul>
</details>

**Comment by shaan147** [comment] 2023-10-09 19:09
How do i run the app on windows? Or is it only for Mac?

**Comment by shaan147** [comment] 2023-10-09 19:20
Contributor details
Your Expensify account email: shaanemustafa8@gmail.com
Upwork Profile Link: https://www.upwork.com/freelancers/~01ca8ad8ce36b9eceb

**Comment by shaan147** [comment] 2023-10-09 19:21
Contributor details
Your Expensify account email: shaanemustafa8@expensify.com
Upwork Profile Link: https://www.upwork.com/freelancers/~01ca8ad8ce36b9eceb

**Comment by ufumerfarooq** [comment] 2023-10-09 19:31
@shaan147 this is producing on web. You can visit staging.new.expensify.com to reproduce

**Comment by phoenixxbasit** [comment] 2023-10-09 19:45
I was able to reproduce the issue but if I reload the same page again the same url endpoint is showing 200 Status.

**Comment by 5war00p** [comment] 2023-10-09 21:35
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
API - 404 Returns On AuthenticatePusher API 
### What is the root cause of that problem?

We have two events which we are subscribing for pusher.

1. subscribeToReportTypingEvents
2. subscribeToReportLeavingEvents

These two functions are responsible for subscribing to pusher here in this file https://github.com/Expensify/App/blob/38f15163860d669975cd9f0167944ebd09e0be38/src/libs/actions/Report.js

If we observe this issue only happens in case of login only because the channel name is invalid which is returning 404.

https://github.com/Expensify/App/blob/38f15163860d669975cd9f0167944ebd09e0be38/src/pages/home/ReportScreen.js#L342-L352 in this snippet is responsible for subscribing but we're not checking weather the reportID is empty (at mounting time / no reports available at login so it takes a bit time till OpenApp command completes).

Also we have another issue where we're type-casing null as string in this line https://github.com/Expensify/App/blob/38f15163860d669975cd9f0167944ebd09e0be38/src/pages/home/ReportScreen.js#L130 which makes checking !!reportID everytime true as we're having reportID as a string

### What changes do you think we should make in order to solve the problem?

Update getReportID function to return following 

jsx
return String(lodashGet(route, 'params.reportID', '')) || null;


> If we're worried about the regressions or following up issues that might can cause from reportID being null we can depend on report.reportID which is also reliable here in this situation.

Return if reportID is empty in useEffect block here in this snippet

https://github.com/Expensify/App/blob/38f15163860d669975cd9f0167944ebd09e0be38/src/pages/home/ReportScreen.js#L342-L352

> Or Handler conditionally



### What alternative solutions did you explore? (Optional)
NA

**Comment by conorpendergrast** [comment] 2023-10-12 13:18
@fedirjh One proposal to review here!

**Comment by marcochavezf** [comment] 2023-10-13 18:28
Thanks @fedirjh for the review, assigning @5war00p 🚀 

I think `return String(lodashGet(route, 'params.reportID', ''));` would be enough since it would return always an empty string and `!!reportID` would return false if that's the case

**Comment by ufumerfarooq** [comment] 2023-10-13 19:21
Applied on upwork

**Comment by 5war00p** [comment] 2023-10-13 21:24
@fedirjh @marcochavezf Raised PR: https://github.com/Expensify/App/pull/29590

**Comment by conorpendergrast** [comment] 2023-10-24 19:26
Waiting until 2023-10-30 due to the regression

**Comment by conorpendergrast** [comment] 2023-10-31 20:46
Paying this tomorrow!

**Comment by conorpendergrast** [comment] 2023-11-06 11:55
Sorry for the delay here! 

Payouts due:

Issue Reporter: $50 @ufumerfarooq - [Offer](https://www.upwork.com/nx/wm/offer/27538787)
Contributor: $500 - 50% regression = $250 @5war00p - [Offer](https://www.upwork.com/nx/wm/offer/27538778)
Contributor+: $500 - 50% regression = $250 @fedirjh - [Contract](https://www.upwork.com/nx/wm/workroom/35208751/overview)

Eligible for 50% #urgency bonus? No - due to [regression penalty](https://github.com/Expensify/App/issues/29116#issuecomment-1768994924)

Upwork job is [here](https://www.upwork.com/jobs/~01eb77836e6080236f).

**Comment by 5war00p** [comment] 2023-11-06 12:07
@conorpendergrast  offer accepted.

**Comment by ufumerfarooq** [comment] 2023-11-06 12:15
@conorpendergrast offer accepted

**Comment by conorpendergrast** [comment] 2023-11-06 12:17
Both paid, contracts ended. Closing out, thanks everyone

**Closed by conorpendergrast** 2023-11-06 12:17 UTC
Labels: External, Daily, Awaiting Payment, Bug
