### ISSUE TITLE
[$1000] The cursor is displayed as pointer on the archived room banner text

### ISSUE THREAD

**Issue by kavimuru** [Expensify/App#13452] opened 2022-12-09 00:06 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Actions Performed:

1. Go to any archived room
2. Hover over the “This chat room has been archived.” text

## Expected Result:
Standard cursor is displayed as the text is not pressable

## Actual Result:
Pointer/hand cursor is displayed

## Workaround:
unknown

## Platform:

Where is this issue occurring?

- Web

**Version Number:** 1.2.37-0
**Reproducible in staging?:** y
**Reproducible in production?:** y
**Email or phone of affected tester (no customers):** 
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** 

https://user-images.githubusercontent.com/43996225/206592286-a3cb14d8-3ab3-4e27-8840-dcbeb9aed0b6.mp4

https://user-images.githubusercontent.com/43996225/206592298-d1bd5185-a558-4007-bee5-005e42f753c9.mov

**Expensify/Expensify Issue URL:** 
**Issue reported by:** @adeel0202 
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1670521824762439

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01776d53155c170045</li>
        <li>Upwork Job ID: 1601274785687920640
<li>Last Price Increase: 2022-12-12</li></li>
    </ul>
</details>

**Comment by syedsaroshfarrukhdot** [comment] 2022-12-09 00:50
### Proposal :-

We need to pass `pointerEventsNone` to `text`

```diff
diff --git a/src/components/Banner.js b/src/components/Banner.js
index 3b5a8d66e..6e7558eb8 100644
--- a/src/components/Banner.js
+++ b/src/components/Banner.js
@@ -12,6 +12,7 @@ import * as StyleUtils from '../styles/StyleUtils';
 import getButtonState from '../libs/getButtonState';
 import Tooltip from './Tooltip';
 import withLocalize, {withLocalizePropTypes} from './withLocalize';
+import pointerEventsNone from '../styles/pointerEventsNone';
 
 const propTypes = {
     /** Text to display in the banner. */
@@ -76,7 +77,7 @@ const Banner = props => (
                     {
                         props.shouldRenderHTML
                             ? <RenderHTML html={props.text} />
-                            : <Text style={[...props.textStyles]} onPress={props.onPress}>{props.text}</Text>
+                            : <Text style={[...props.textStyles, pointerEventsNone]} onPress={props.onPress}>{props.text}</Text>
                     }
```

### After Fix:-

https://user-images.githubusercontent.com/81307212/206597492-88b6c8f7-629a-439f-bdb3-8edf955ec417.mov

**Comment by syedsaroshfarrukhdot** [comment] 2022-12-09 04:05
### Update Proposal

As we need onPress In Some Situations We Can Take A New Props `hidePointer` in `ArchivedReportFooter` to pass in `Banner.js`

```diff
diff --git a/src/components/ArchivedReportFooter.js b/src/components/ArchivedReportFooter.js
index c271b0f8c..d05f0441a 100644
--- a/src/components/ArchivedReportFooter.js
+++ b/src/components/ArchivedReportFooter.js
@@ -71,6 +71,7 @@ const ArchivedReportFooter = (props) => {
             })}
             shouldRenderHTML={archiveReason !== CONST.REPORT.ARCHIVE_REASON.DEFAULT}
             shouldShowIcon
+            hidePointer={archiveReason === CONST.REPORT.ARCHIVE_REASON.DEFAULT}
         />
     );
 };

diff --git a/src/components/Banner.js b/src/components/Banner.js
index 3b5a8d66e..b6393f1cc 100644
--- a/src/components/Banner.js
+++ b/src/components/Banner.js
@@ -38,6 +38,9 @@ const propTypes = {
     // eslint-disable-next-line react/forbid-prop-types
     textStyles: PropTypes.arrayOf(PropTypes.object),
 
+    /** Should this component show the pointer? */
+    hidePointer: PropTypes.bool,
+
     ...withLocalizePropTypes,
 };
 
@@ -76,6 +79,7 @@ const Banner = props => (
                     {
                         props.shouldRenderHTML
                             ? <RenderHTML html={props.text} />
+                            : props.hidePointer ? <Text style={[...props.textStyles]}>{props.text}</Text> 
                             : <Text style={[...props.textStyles]} onPress={props.onPress}>{props.text}</Text>
                     }
                 </View>
```



After Fix :- 

https://user-images.githubusercontent.com/81307212/206621586-507e335c-45a1-426d-950f-83196b089af0.mov

**Comment by jatinsonijs** [comment] 2022-12-09 18:29
Proposal
We can simply remove default prop (passing function) which is creating issue
[/src/components/Banner.js](url)
<img width="830" alt="Screenshot 2022-12-09 at 11 57 51 PM" src="https://user-images.githubusercontent.com/114683042/206768514-cc5d5377-8cb0-4dd2-89c0-e854fd1a71bb.png">

**Comment by jayeshmangwani** [comment] 2022-12-09 20:22
### Proposal

we should pass the pointernone style from the footer component 

https://github.com/Expensify/App/blob/a75a01e710f4035ccd3e4ea0e6c9bc1be04d863f/src/components/ArchivedReportFooter.js#L66-L74
```diff
+             textStyles={[styles.pointerEventsNone]}
```

#### after applying the fix


https://user-images.githubusercontent.com/35371050/206789659-304cadd5-94b3-46b5-9849-c401db207f6e.mov

**Comment by priyeshshah11** [comment] 2022-12-10 03:47
## Proposal

### Problem

The `onPress` && `onClose` props have an empty anonymous function as its default value, thus the text shows the pointer on the hover event.

### Solution 1

Set both `onPress` && `onClose` props' default values to `undefined` in Banner.js

```diff
--- a/src/components/Banner.js
+++ b/src/components/Banner.js
@@ -45,53 +45,56 @@ const defaultProps = {
     shouldRenderHTML: false,
     shouldShowIcon: false,
     shouldShowCloseButton: false,
-    onClose: () => {},
-    onPress: () => {},
+    onClose: undefined,
+    onPress: undefined,
     containerStyles: [],
     textStyles: [],
 };
```

### Solution 2: Addition to Solution 1

I think we should not highlight the banner if it is not clickable, as highlighting (i.e. changing the background colour on hover) indicates to the user as if it is clickable. This might be a question for the design time to confirm.

```diff
 const Banner = props => (
     <Hoverable>
-        {isHovered => (
-            <View style={[
+        {(isHovered) => {
+            const isClickable = props.onClose || props.onPress;
+            return (
+                <View style={[

-                isHovered ? styles.activeComponentBG : styles.hoveredComponentBG,
+                    isClickable && isHovered ? styles.activeComponentBG : styles.hoveredComponentBG,

Optional: as this might be a question for the design time to whether highlight the icon or not.
-                            <Icon
-                                src={Expensicons.Exclamation}
-                                fill={StyleUtils.getIconFillColor(getButtonState(isHovered))}
+                                <Icon
+                                    src={Expensicons.Exclamation}
+                                    fill={StyleUtils.getIconFillColor(getButtonState(isClickable && isHovered))}
```

https://user-images.githubusercontent.com/38547776/206827613-a69927fb-0d5f-4099-9cef-379e6332f8ae.mov


@Santhosh-Sellavel @puneetlath

**Comment by jatinsonijs** [comment] 2022-12-10 06:27
**Proposal 2**
If we want to remove hover effect also we can add enabled prop in Hoverable component. With this it will also remove unnecessary listener and usable on another area also where we may face same issue. **So combine with my above solution** we can do 

```diff
diff --git a/src/components/Banner.js b/src/components/Banner.js
index 3b5a8d66e3..bfb066fa8c 100644
--- a/src/components/Banner.js
+++ b/src/components/Banner.js
@@ -46,13 +46,13 @@ const defaultProps = {
     shouldShowIcon: false,
     shouldShowCloseButton: false,
     onClose: () => {},
-    onPress: () => {},
+    onPress: undefined,
     containerStyles: [],
     textStyles: [],
 };
 
 const Banner = props => (
-    <Hoverable>
+    <Hoverable enabled={!!props.onPress}>
         {isHovered => (
             <View style={[
                 styles.flexRow,
diff --git a/src/components/Hoverable/hoverablePropTypes.js b/src/components/Hoverable/hoverablePropTypes.js
index 07b8a8741e..2978a6c7f1 100644
--- a/src/components/Hoverable/hoverablePropTypes.js
+++ b/src/components/Hoverable/hoverablePropTypes.js
@@ -22,10 +22,14 @@ const propTypes = {
 
     // If the mouse clicks outside, should we dismiss hover?
     resetsOnClickOutside: PropTypes.bool,
+
+    /** Should hover able enabled */
+    enabled: PropTypes.bool,
 };
 
 const defaultProps = {
     absolute: false,
+    enabled: true,
     containerStyles: [],
     onHoverIn: () => {},
     onHoverOut: () => {},
diff --git a/src/components/Hoverable/index.js b/src/components/Hoverable/index.js
index f06ed56027..5b24529322 100644
--- a/src/components/Hoverable/index.js
+++ b/src/components/Hoverable/index.js
@@ -21,6 +21,10 @@ class Hoverable extends Component {
     }
 
     componentDidMount() {
+        if (!this.props.enabled) {
+            return;
+        }
+
         document.addEventListener('mousedown', this.resetHoverStateOnOutsideClick);
 
         // we like to Block the hover on touch devices but we keep it for Hybrid devices so
@@ -82,6 +86,10 @@ class Hoverable extends Component {
     }
 
     render() {
+        if (!this.props.enabled) {
+            return null;
+        }
+
         if (this.props.absolute && React.isValidElement(this.props.children)) {
             return React.cloneElement(React.Children.only(this.props.children), {
                 ref: (el) => {

```

**Comment by Santhosh-Sellavel** [comment] 2022-12-11 17:31
Thanks, everyone!

I straight away gave 👎  to proposals that could break something, and other proposals are being considered. But before moving forward let's confirm what's the expectation here.

@Expensify/design 

https://user-images.githubusercontent.com/85645967/206918939-b79adfda-30a4-4d6a-bb1f-07e09043d1ee.mov

On archived workspace chats, we show a banner and related messages. Based on the implementation the banner click doesn't have any actions. Showing clickable pointer is an issue will be removed, additionally, should we keep the hover effect or not?

cc: @puneetlath

**Comment by shawnborton** [comment] 2022-12-12 02:58
Yeah, I'm not entirely sure why this banner has a cursor or why it has a hover state. I would think it would just show as a banner with no interactive elements unless we put some kind of explicit link in there (almost like a growl might have).

**Comment by shawnborton** [comment] 2022-12-12 02:59
Also, I wonder if we want to just make this one internal since @srikarparsi is already working on an issue related to this component: https://github.com/Expensify/App/issues/13373

**Comment by jatinsonijs** [comment] 2022-12-12 04:19
Banner is using on 2 places one shown in issue another as below SS. Here on press text its navigate to another screen. I just displayed it by changing condition.
<img width="378" alt="Screenshot 2022-12-12 at 9 43 01 AM" src="https://user-images.githubusercontent.com/114683042/206959735-aaae37f6-7c37-4975-91a7-2e370f9d75c8.png">

**Comment by srikarparsi** [comment] 2022-12-12 04:27
yeah I can take this one but what do you think @puneetlath since a lot of people have been working on this issue? Also, @shawnborton, do we want a [hover state](https://github.com/Expensify/App/issues/13452#issuecomment-1345612149)? I don't really think we should have one since it indicates that it's clickable but just wanted to check?

**Comment by Santhosh-Sellavel** [comment] 2022-12-12 16:02
@srikarparsi Are you gonna handle this internally? Let me know so that we can decide on making a hiring decision here.

cc: @puneetlath

**Comment by srikarparsi** [comment] 2022-12-12 22:21
Hey @Santhosh-Sellavel, could you please review the current set of proposals and if something looks good, we'll go with it.
But if none of them work, I'll take this internally for urgency.

**Comment by Santhosh-Sellavel** [comment] 2022-12-12 23:23
@srikarparsi 
We have it here already @priyeshshah11 proposal [here](https://github.com/Expensify/App/issues/13452#issuecomment-1345047043) its simple and straightforward looks good to me!

**Comment by jatinsonijs** [comment] 2022-12-13 12:36
@Santhosh-Sellavel just want to ask you for improve my future proposal. I hope you don't mind.

https://github.com/Expensify/App/issues/13452#issuecomment-1344627596

I have proposed this solution with root case and solution for the mentioned problem. and haven't added onClose: undefined bcz we already have props for to show close button when needed (**shouldShowCloseButton**). so there is very less chance onClose was not provided with **shouldShowCloseButton** exist.
Another point show hover effect or not is personal choice which is discussion point. for disabled like design I can understand must not show hover effect. but here is the just information text which is not indicate any action to perform.

**Comment by Santhosh-Sellavel** [comment] 2022-12-13 14:19
@puneetlath @srikarparsi We have a solution here, but I'll reconfirm the hire here later today to make a fair decision!

**Comment by priyeshshah11** [comment] 2022-12-13 14:25
> @Santhosh-Sellavel just want to ask you for improve my future proposal. I hope you don't mind.
> 
> [#13452 (comment)](https://github.com/Expensify/App/issues/13452#issuecomment-1344627596)
> 
> I have proposed this solution with root case and solution for the mentioned problem. and haven't added onClose: undefined bcz we already have props for to show close button when needed (**shouldShowCloseButton**). so there is very less chance onClose was not provided with **shouldShowCloseButton** exist. Another point show hover effect or not is personal choice which is discussion point. for disabled like design I can understand must not show hover effect. but here is the just information text which is not indicate any action to perform.

I think we don't even need `shouldShowCloseButton` as we need/have `onClose` based on which we should show/hide the close button. I can't think of a usecase where we would supply `onClose` and set `shouldShowCloseButton=false`

**Comment by priyeshshah11** [comment] 2022-12-13 14:40
@jatinsonijs I think your proposal will only solve the cursor issue but not the hoverable state issue which is what the design team wants fixed as well, but I'll leave it up to the team to assess.

**Comment by jatinsonijs** [comment] 2022-12-13 14:45
> @jatinsonijs I think your proposal will only solve the cursor issue but not the hoverable state issue which is what the design team wants fixed as well, but I'll leave it up to the team to assess.

Yes @priyeshshah11 I also state same in my comment its only fix mentioned issue at starting. Plz don't take it otherwise I just want to understand process how they choose proposal. I don't have any problem if they don't want to choose mine. Its their choice.

**Comment by priyeshshah11** [comment] 2022-12-13 14:51
@jatinsonijs Yeah no worries 👍 I am also very new to this so I might not be 100% correct but based on what I have seen I think the way it works is that the most complete, unique solutions are chosen.

**Comment by Santhosh-Sellavel** [comment] 2022-12-13 16:14
@jatinsonijs I understand your feelings because I too had a similar experience in the past. Well, we will have more jobs, lets focus on the other open jobs!

While writing a proposal, you should explain the root cause and why/how your solution addresses them with a brief explanation. Including screenshots/recordings or other supporting documents to ensure your proposal works or why it's the best approach. Ask questions first if you don't understand the issue or to know about the expected outcome and add your suggestions. Good luck mate!

**Comment by jatinsonijs** [comment] 2022-12-13 16:24
No problem @Santhosh-Sellavel, Thank you for your suggestions. I will definitely consider it in my next proposal.

**Comment by priyeshshah11** [comment] 2022-12-13 20:03
Thanks! @puneetlath @Santhosh-Sellavel 
I have applied to the upwork job and aim to get the PR up by EOD today/tomorrow. Just waiting to perform thorough testing after the login issue is fixed.

**Comment by puneetlath** [comment] 2022-12-14 22:49
Great thanks! @Santhosh-Sellavel will you be able to review tomorrow? 

Also @adeel0202 can you apply to the job for the reporting bonus?

**Comment by Santhosh-Sellavel** [comment] 2022-12-14 23:21
@puneetlath Will review it shortly!

**Comment by JmillsExpensify** [comment] 2022-12-22 18:58
@puneetlath heads up, this PR already hit production. Looks like the GH automation didn't trigger for the regression period, though it started yesterday.

**Comment by JmillsExpensify** [comment] 2022-12-28 20:15
@puneetlath You want me to jump in and help move this one forward?

**Comment by priyeshshah11** [comment] 2022-12-29 12:17
@JmillsExpensify @puneetlath [This PR](https://github.com/Expensify/App/pull/13576#issuecomment-1362198885) was merged within 3 days and was released to production a week ago. I believe it has passed the 7 days so just waiting for the payment to be finalised

**Comment by priyeshshah11** [comment] 2023-01-02 10:27
> @JmillsExpensify @puneetlath [This PR](https://github.com/Expensify/App/pull/13576#issuecomment-1362198885) was merged within 3 days and was released to production a week ago. I believe it has passed the 7 days so just waiting for the payment to be finalised

@JmillsExpensify @puneetlath any updates on this please?

**Comment by JmillsExpensify** [comment] 2023-01-02 13:04
Just assigned myself to help out. Based on the linked PR, this PR is eligible for a 50% bonus. That means that the following payouts are due:

 - Issue reporter: @adeel0202 - $250
 - Contributor: @priyeshshah11 - $1,500 (1k + 50% bonus)
 - Contributor+: @Santhosh-Sellavel - $1,500 (1k + 50% bonus)

**Comment by JmillsExpensify** [comment] 2023-01-02 13:06
Based on the above, I've just paid out @priyeshshah11 and @Santhosh-Sellavel. @adeel0202 Contract for reporting has been shared.

**Comment by JmillsExpensify** [comment] 2023-01-02 13:07
Update: All contractors are now paid out! Sorry for the delay.

**Comment by JmillsExpensify** [comment] 2023-01-02 13:08
@puneetlath I don't see a BZ checklist for this one. Mind chiming in on the regression/convo parts of that list?

**Comment by priyeshshah11** [comment] 2023-01-02 13:28
> Update: All contributors are now paid out! Sorry for the delay.

Thanks! 😄 @JmillsExpensify

**Comment by puneetlath** [comment] 2023-01-05 01:15
- [ ] The PR that introduced the bug has been identified. Link to the PR:
- [ ] The offending PR has been commented on, pointing out the bug it caused and why, so the author and reviewers can learn from the mistake. Link to comment:
- [ ] A discussion in #expensify-bugs has been started about whether any other steps should be taken (e.g. updating the PR review checklist) in order to catch this type of bug sooner. Link to discussion:
- [ ] A [regression test](https://expensify.testrail.io/index.php?/dashboard) has been added or updated so that the same bug will not reach production again. Link to the GH issue for creating the test here:

**Comment by JmillsExpensify** [comment] 2023-01-11 05:13
Are we good to close this one out?

**Comment by puneetlath** [comment] 2023-01-11 18:25
Yep!

**Closed by puneetlath** 2023-01-11 18:25 UTC
Labels: Reviewing, External, Daily, Bug
