### ISSUE TITLE
[$250] iOS - Split - Confirmation page does not scroll down when the input field is focused

### ISSUE THREAD

**Issue by izarutskaya** [Expensify/App#42139] opened 2024-05-14 09:26 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.73-1
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Issue reported by:** Applause-Internal team

## Action Performed:
1. Launch New Expensify app.
2. Go to FAB > Split expense.
3. Enter amount > Next.
4. Select many users (so that the confirmation page will be scrollable).
5. On confirmation page, without scrolling, tap on the split amount input next to user at the bottom.

## Expected Result:
When the input is focused, the page will scroll down to show the input in focus.

## Actual Result:
When the input is focused, the page does not scroll down to show the input in focus.

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [x] iOS: Native
- [ ] iOS: mWeb Safari
- [ ] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

https://github.com/Expensify/App/assets/115492554/6c8617e1-7eaf-49cc-b824-5a8050318832

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01c6f78c6b4248b82b</li>
        <li>Upwork Job ID: 1790472103412912128</li>
        <li>Last Price Increase: 2024-05-14</li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @jayeshmangwani</details>

**Comment by izarutskaya** [comment] 2024-05-14 09:27
We think this issue might be related to the #vip-split.

**Comment by abzokhattab** [comment] 2024-05-14 20:06
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
Confirmation page does not scroll down when the input field is focused
### What is the root cause of that problem?
 
the [textinput](https://github.com/Expensify/App/blob/51901d788cdfd70ae7ef051dfdc4e20cff4e68cd/src/components/AmountTextInput.tsx#L63) that is used inside the participants of the confirmation page doesn't scroll because its not wrapped with 
`KeyboardAvoidingView`
### What changes do you think we should make in order to solve the problem?

we should wrap the `TextInput` with `KeyboardAvoidingView`

**Comment by abzokhattab** [comment] 2024-05-14 21:13
I am not able to reproduce it on main, am i missing any steps? 

https://github.com/Expensify/App/assets/59809993/5cac0cb7-99be-49d1-8dd2-9d9232b9f850

**Comment by ryjennings** [comment] 2024-05-15 00:18
Proposal to fix:

I wonder if this is some sort of a timing issue. I notice focus is given to the text field, but the scroll view doesn't scroll to the field until a second after the keyboard is displayed. It would be nice if the scroll happened while the keyboard was animating in. I would test to make sure the appropriate content offset is being sent to the scroll view and that `setContentOffset` or `scrollRectToVisible` (whichever way the animation is happening) is called at the appropriate time.

**Comment by ryjennings** [comment] 2024-05-15 00:23
Contributor details
Your Expensify account email: ryjennings@gmail.com
Upwork Profile Link: https://www.upwork.com/freelancers/~01ce52e61a893ac0b7

**Comment by izarutskaya** [comment] 2024-05-17 10:05
It not reproducible now
Build 1.4.74-4

https://github.com/Expensify/App/assets/115492554/81855f0e-27dc-4201-ad04-9a62d88db001

**Comment by jayeshmangwani** [comment] 2024-05-17 13:19
Issue is [not reproducible](https://github.com/Expensify/App/issues/42139#issuecomment-2117210201) now

**Comment by isabelastisser** [comment] 2024-05-17 19:06
Thanks @jayeshmangwani . Closing this!

**Closed by isabelastisser** 2024-05-17 19:06 UTC
Labels: External, Daily, Help Wanted, Bug
