### ISSUE TITLE
[$250] Onboarding- After finishing "onboarding" and switching to DM, an error appears in the console

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#40458] opened 2024-04-18 14:30 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** v1.4.63-0
**Reproducible in staging?:** y
**Reproducible in production?:** n
**Issue reported by:** Applause - Internal Team
**Issue found when executing PR:** https://github.com/Expensify/App/pull/40328

## Action Performed:
Prerequisites:
There must be at least one conversation in the account. Enable the console.

Step:
1. Open https://staging.new.expensify.com/onboarding
2. Fill in the required data
3. Click the "Continue" button
4. Select "Track business spend for taxes"
5. Click the "Continue" button
6. Navigate to any existing conversation

## Expected Result:
After completing "onboarding" and switching to DM, no errors should appear in the console

## Actual Result:
After finishing "onboarding" and switching to DM, an error appears in the console

## Workaround:
n/a

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

https://github.com/Expensify/App/assets/93399543/0dd5da72-a3c0-4966-8f1c-0a09f97aed37

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~017d01cb735c28a1cd</li>
        <li>Upwork Job ID: 1780977474718523392</li>
        <li>Last Price Increase: 2024-05-02</li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @mananjadhav</details>

**Comment by kbecciv** [comment] 2024-04-18 14:30
We think that this bug might be related to #vip-vsb

**Comment by tgolen** [comment] 2024-04-18 15:11
This is not a blocker. Removing the label and sending this to external to investigate a fix.

**Comment by bernhardoj** [comment] 2024-04-19 16:52
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
The console error shows after closing the onboarding video and switch to another report.

### What is the root cause of that problem?
When the video player is mounted, `currentVideoPlayerRef` will be set to the onboarding video ref. When we close it and switch to another report, we are trying to stop the video (and other things).
https://github.com/Expensify/App/blob/48f64d000f61811d603934212cfd494592c35037/src/components/VideoPlayerContexts/PlaybackContext.tsx#L85-L90
https://github.com/Expensify/App/blob/48f64d000f61811d603934212cfd494592c35037/src/components/VideoPlayerContexts/PlaybackContext.tsx#L75-L77

Because the `currentVideoPlayerRef` still hold the onboarding video player ref that is already destroyed, we got the console error. I previously fix this console error in my PR [here](https://github.com/Expensify/App/pull/37772), but looks like the code was removed

### What changes do you think we should make in order to solve the problem?

We need to clear the `currentVideoPlayerRef` when the video player is unmounted and `shouldUseSharedVideoElement` is false, basically the same solution I did before.
```
useEffect(() => {
    shouldUseSharedVideoElementRef.current = shouldUseSharedVideoElement;
}, [shouldUseSharedVideoElement]);

useEffect(
    () => () => {
        if (shouldUseSharedVideoElementRef.current) {
            return;
        }
        // If it's not a shared video player, clear the video player ref.
        currentVideoPlayerRef.current = null;
    },
    [currentVideoPlayerRef],
);
```

We can even call `resetVideoPlayerData` so it clears the `currentlyPlayingURL` so we can remove this code.
https://github.com/Expensify/App/blob/48f64d000f61811d603934212cfd494592c35037/src/components/VideoPlayer/BaseVideoPlayer.tsx#L206-L218

**Comment by mananjadhav** [comment] 2024-04-23 19:41
Will review this tomorrow.

**Comment by tgolen** [comment] 2024-04-25 13:06
@mananjadhav Can you please take a look at this one soon?

**Comment by mananjadhav** [comment] 2024-04-25 13:09
I looked through the proposals yesterday. I'll test them today and confirm if one of them is good to go.

**Comment by mananjadhav** [comment] 2024-04-25 23:29
I was checking this and I am unable to reproduce this on staging as well as latest main.

https://github.com/Expensify/App/assets/3069065/dfb3f54a-c24d-43df-ac80-8e038f921268

**Comment by bernhardoj** [comment] 2024-04-26 03:33
It's already fixed in https://github.com/Expensify/App/pull/40132

**Comment by skyweb331** [comment] 2024-04-26 04:28
This means, this bug is duplicated??? :(

**Comment by mananjadhav** [comment] 2024-05-01 19:46
@kbecciv Can you please confirm if this is still reproducible.

**Comment by tgolen** [comment] 2024-05-06 15:57
It sounds like this can be closed since it's already fixed. Please reopen if anyone is able to reproduce it.

**Closed by tgolen** 2024-05-06 15:57 UTC
Labels: External, Engineering, Daily, Help Wanted, Bug
