### ISSUE TITLE
[HOLD for payment 2024-11-21] [$250] Skip onboarding screen with company size if signupQualifier is VSB

### ISSUE THREAD

**Issue by carlosmiceli** [Expensify/App#51750] opened 2024-10-30 16:30 UTC
When signing up as a company between 1-9 employees, the user is redirected to New Expensify and is welcomed by the onboarding flow. However the first thing we ask them after they open new expensify, is how big a company they want to set up. This is redundant and makes for a bad first impression.

Let's select 1-10 employees by default for signups with the 'vsb' signnpQualifier NVP and start the onboarding flow in the accounting software section. Let's also make sure that whatever logic is triggered by selecting 1-10 also occurs (before displaying the onboarding modal) for these signups.

Select this:
![Screenshot 2024-10-30 at 12 48 09 PM](https://github.com/user-attachments/assets/22d5b25f-9cc4-4032-a48b-818353b9d7ea)

Skip this screen (but keep the choice logic):
![Screenshot 2024-10-30 at 1 23 29 PM](https://github.com/user-attachments/assets/819a6335-0e1f-447c-ad5e-23dee83b5abb)

This should be the first screen they see in the modal:
![Screenshot 2024-10-30 at 1 25 44 PM](https://github.com/user-attachments/assets/1e3fc4b0-18e2-4fa2-a2d4-2623bc72a966)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~021851663004588841867</li>
        <li>Upwork Job ID: 1851663004588841867</li>
        <li>Last Price Increase: 2024-10-30</li>
<li>Automatic offers: </li>
<ul>
<li>nkdengineer | Contributor | 104676448</li>
</ul></li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @greg-schroeder</details>

**Comment by Shahidullah-Muffakir** [comment] 2024-10-30 17:58
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
if user selected company size in the OD, we are still showing the company size selecting modal in the onboarding flow
### What is the root cause of that problem?
improvement 
### What changes do you think we should make in order to solve the problem?
change this: 
https://github.com/Expensify/App/blob/084b1047e8f090a63eb4eb99ab89d13f267bbe8b/src/libs/actions/Welcome/OnboardingFlow.ts#L58C4-L61C6
to this: 

  ```
  if (isVsb) {
        Onyx.set(ONYXKEYS.ONBOARDING_PURPOSE_SELECTED, CONST.ONBOARDING_CHOICES.MANAGE_TEAM);
        Welcome.setOnboardingCompanySize(onboardingCompanySize.MICRO);
       
        return `/${ONBOARDING_ACCOUNTING.route}`;
    }
```

**Comment by nkdengineer** [comment] 2024-10-30 18:01
## Proposal

### Please re-state the problem that we are trying to solve in this issue.

Skip onboarding screen with company size if signupQualifier is VSB
### What is the root cause of that problem?

This is an improvement
### What changes do you think we should make in order to solve the problem?
If it's vsb, we should return the onboarding accounting route and set the `companySize`as `1-10` and we also need to create a new WS if the onboardingPolicyID doesn't exist 

```
if (isVsb) {
    Onyx.set(ONYXKEYS.ONBOARDING_PURPOSE_SELECTED, CONST.ONBOARDING_CHOICES.MANAGE_TEAM);
    Onyx.set(ONYXKEYS.ONBOARDING_COMPANY_SIZE, CONST.ONBOARDING_COMPANY_SIZE.MICRO);
    if (!onboardingPolicyID) {
          const {adminsChatReportID, policyID} = Policy.createWorkspace(undefined, true, '', Policy.generatePolicyID(), CONST.ONBOARDING_CHOICES.MANAGE_TEAM);
          Welcome.setOnboardingAdminsChatReportID(adminsChatReportID);
          Welcome.setOnboardingPolicyID(policyID);
      }
    return `/${ROUTES.ONBOARDING_ACCOUNTING.route}`;
}
```
https://github.com/Expensify/App/blob/1adb6c661cfd71f0d7bac082c4a372793083c704/src/libs/actions/Welcome/OnboardingFlow.ts#L58

OPTIONAL: We can move the logic creating the WS to the accounting page if `onboardingPolicyID` doesn't exist.
### What alternative solutions did you explore? (Optional)

**Comment by mzdev0** [comment] 2024-10-30 18:15
## Proposal

### Please re-state the problem that we are trying to solve in this issue.

Skip onboarding screen with company size if signupQualifier is VSB

### What is the root cause of that problem?

improvement

### What changes do you think we should make in order to solve the problem?

we need to change the code here:
https://github.com/Expensify/App/blob/1adb6c661cfd71f0d7bac082c4a372793083c704/src/libs/actions/Welcome/OnboardingFlow.ts#L54-L61
```
if (isVsb) {
    Onyx.set(ONYXKEYS.ONBOARDING_PURPOSE_SELECTED, CONST.ONBOARDING_CHOICES.MANAGE_TEAM);
    Onyx.set(ONYXKEYS.ONBOARDING_COMPANY_SIZE, CONST.ONBOARDING_COMPANY_SIZE.MICRO);
    if (!onboardingPolicyID) {
          const {adminsChatReportID, policyID} = Policy.createWorkspace(undefined, true, '', Policy.generatePolicyID(), CONST.ONBOARDING_CHOICES.MANAGE_TEAM);
          Welcome.setOnboardingAdminsChatReportID(adminsChatReportID);
          Welcome.setOnboardingPolicyID(policyID);
      }
    return `/${ROUTES.ONBOARDING_ACCOUNTING.route}`;
}
```

and then remove the employee selection from here:
https://github.com/Expensify/App/blob/47b8525756602b794e88d1e9fc5e3aef04689c1d/src/libs/Navigation/AppNavigator/Navigators/OnboardingModalNavigator.tsx#L55-L58

### What alternative solutions did you explore? (Optional)

**Comment by D-01576** [comment] 2024-10-31 05:54
## Proposal

### Please re-state the problem that we are trying to solve in this issue.

The current onboarding flow for users with `signupQualifier` set to `VSB` includes a screen to select company size, which we want to skip.

### What is the root cause of that problem?

The onboarding flow does not bypass the company size selection screen for `VSB` users, which creates an unnecessary step.

### What changes do you think we should make in order to solve the problem?

If `isVsb` is `true`, we should:
1. Set the `OnboardingPurposeSelected` to `Manage Team`.
2. Set the `OnboardingCompanySize` to `Micro`.
3. Create a new Workspace if `onboardingPolicyID` is not set.

The updated code block from lines [58 to 61](https://github.com/Expensify/App/blob/084b1047e8f090a63eb4eb99ab89d13f267bbe8b/src/libs/actions/Welcome/OnboardingFlow.ts#L58C4-L61C6) should look like this:

```javascript
if (isVsb) {
    Onyx.set(ONYXKEYS.ONBOARDING_PURPOSE_SELECTED, CONST.ONBOARDING_CHOICES.MANAGE_TEAM);
    Welcome.setOnboardingCompanySize(CONST.ONBOARDING_COMPANY_SIZE.MICRO);
    if (!onboardingPolicyID) {
        const {adminsChatReportID, policyID} = Policy.createWorkspace(
            undefined,
            true,
            '',
            Policy.generatePolicyID(),
            CONST.ONBOARDING_CHOICES.MANAGE_TEAM
        );
        Welcome.setOnboardingAdminsChatReportID(adminsChatReportID);
        Welcome.setOnboardingPolicyID(policyID);
    }
    return `/${ROUTES.ONBOARDING_ACCOUNTING.route}`;
}
```
### What alternative solutions did you explore? (Optional)

**Comment by jayeshmangwani** [comment] 2024-10-31 09:02
@carlosmiceli 'Help Wanted' label was removed here—I assume this was a mistake and that we want this issue fixed by an external contributor?

**Comment by jayeshmangwani** [comment] 2024-10-31 09:10
@D-01576 How does your proposal differ from the ones above https://github.com/Expensify/App/issues/51750#issuecomment-2447954731 and https://github.com/Expensify/App/issues/51750#issuecomment-2447974007?

**Comment by jayeshmangwani** [comment] 2024-10-31 09:17
> We cannot remove the page entirely, as we still need it for users who aren’t coming from OD

@mzdev0 We cannot remove the page entirely, as we still need it for users who aren’t coming from OD

**Comment by jayeshmangwani** [comment] 2024-10-31 09:24
> Note that this change is not enough, we should also hide the back button on the accounting page if we have already selected this as the user shouldn't be able to change the employee count if she is the VSB

@twilight2294  I feel that this is a thing that can be done in the PR and would have been caught when testing, so I feel that @nkdengineer Proposal is sufficient here

**Comment by jayeshmangwani** [comment] 2024-10-31 09:25
We can go with @nkdengineer’s [proposal](https://github.com/Expensify/App/issues/51750#issuecomment-2447954731) here.

🎀 👀 🎀 C+ reviewed

**Comment by jayeshmangwani** [comment] 2024-10-31 10:09
Whatever! I don’t think this needs to be in the proposal

**Comment by carlosmiceli** [comment] 2024-10-31 16:37
Ok, scratch that Matt, we've decided not to hide the back button so there won't be any extra work/value there.

**Comment by anmurali** [comment] 2024-11-05 01:29
@nkdengineer @carlosmiceli - I want to confirm that we're actually auto selecting 1-10 in the `How many employees do you have` step and going directly to the accounting step. In other words, we're still storing `introSelected.companySize : "1-10"` right?

**Comment by carlosmiceli** [comment] 2024-11-05 02:37
Yup! We're setting that value as well.

**Comment by greg-schroeder** [comment] 2024-11-11 20:31
Review is ongoing for linked PR

**Comment by jayeshmangwani** [comment] 2024-11-20 11:09
# BugZero Checklist:

- [x] **[Contributor]** Classify the bug:

<details>
<summary>Bug classification</summary>


Source of bug:
  - [ ] 1a. Result of the original design (eg. a case wasn't considered)
  - [ ] 1b. Mistake during implementation
  - [ ] 1c. Backend bug
  - [x] 1z. Other: Improvement on Ongoing Onboarding Designs

Where bug was reported:
  - [x] 2a. Reported on production
  - [ ] 2b. Reported on staging (deploy blocker)
  - [ ] 2c. Reported on both staging and production
  - [ ] 2d. Reported on a PR
  - [ ] 2z. Other:

Who reported the bug:
  - [ ] 3a. Expensify user
  - [x] 3b. Expensify employee
  - [ ] 3c. Contributor
  - [ ] 3d. QA
  - [ ] 3z. Other:

</details>

- [x] **[Contributor]** The offending PR has been commented on, pointing out the bug it caused and why, so the author and reviewers can learn from the mistake.

    Link to comment: N/A - New Feature

- [x] **[Contributor]** If the regression was CRITICAL (e.g. interrupts a core flow) A discussion in [#expensify-open-source](https://app.slack.com/client/E047TPA624F/C01GTK53T8Q) has been started about whether any other steps should be taken (e.g. updating the PR review checklist) in order to catch this type of bug sooner.

    Link to discussion: N/A

- [x] **[Contributor]** If it was decided to create a regression test for the bug, please propose the [regression test](https://github.com/Expensify/App/blob/main/contributingGuides/REGRESSION_TEST_BEST_PRACTICES.md) steps using the template below to ensure the same bug will not reach production again.

### Regression Test Proposal

1. Navigate to https://staging.expensify.com/.
2. Choose **Manage expenses for a small team** and enter a new email or phone number.
3. Log in with that new user.
4. Verify that the **How many employees** screen is skipped on New Dot.
5. Press the Back button and confirm that 1-10 employees is preselected.


**Do we agree 👍 or 👎**

**Comment by greg-schroeder** [comment] 2024-11-20 21:43
Payment summary:

Contributor: @nkdengineer - Upwork
C+: @jayeshmangwani - $250 - Manual request via ND

---

Regression test filed: https://github.com/Expensify/Expensify/issues/446445

**Closed by greg-schroeder** 2024-11-20 21:43 UTC
Labels: External, Daily, Improvement, Awaiting Payment, Bug

**Comment by garrettmknight** [comment] 2024-11-26 14:28
$250 approved for @jayeshmangwani
