### ISSUE TITLE
[$500] Personal details- Legal last name validation error only after start typing first name

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#23901] opened 2023-07-30 20:57 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Click on Avatar, go to details
2. Click personal details go to legal name
3. Select cursor on first name, don’t type anything
4. Now go to last name, observe validation error for first name
5. Don’t type anything in last name and go to first name
6. Observe validation error is not coming for last name
7. Start typing in first name,

## Expected Result:
Validation should happen as soon as cursor leaves field

## Actual Result:
 Validation is happening when cursor is on another field and start typing

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [x] iOS / native
- [ ] iOS / Safari
- [x] MacOS / Chrome / Safari
- [ ] MacOS / Desktop
 
**Version Number:** 1.3.47-3
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/93399543/f4f97ee9-1c86-4940-af50-45097517eb82

https://github.com/Expensify/App/assets/93399543/e69fbe6a-f755-490d-92ab-0b463902d9be

**Expensify/Expensify Issue URL:**
**Issue reported by:** @premsjce
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1690637799355469

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01f467d1827a62e969</li>
        <li>Upwork Job ID: 1695736788219748352</li>
        <li>Last Price Increase: 2023-08-31</li>
    </ul>
</details>

**Comment by s-alves10** [comment] 2023-07-30 21:00
Dupe of https://github.com/Expensify/App/issues/23780

**Comment by sakluger** [comment] 2023-08-01 15:55
@s-alves10 thanks for your comment! I doubt I would have found that PR otherwise.

**Comment by kbecciv** [comment] 2023-08-26 15:08
Hey @s-alves10! I think your mention duplicate is not related to above issue, can you please check again,. Thank you in advance.

**Comment by sakluger** [comment] 2023-08-28 18:31
@situchan mind checking if that issue you linked is actually a dupe? Upon closer inspection, it doesn't look like it is.

**Comment by sakluger** [comment] 2023-08-31 22:45
I'm going to add the external label to this one - @situchan let me know if we missed anything and it is actually a duplicate.

**Comment by napster125** [comment] 2023-09-01 00:01
I can't reproduce this issue.

**Comment by situchan** [comment] 2023-09-01 00:14
I am not able to reproduce. Confirming on [slack](https://expensify.slack.com/archives/C049HHMV9SM/p1690637799355469)

**Comment by situchan** [comment] 2023-09-01 00:30
Confirmed not reproducible by bug reporter.
@sakluger let's close as fixed already

**Closed** 2023-09-01 22:53 UTC
Labels: External, Daily, Help Wanted, Bug
