### ISSUE TITLE
[$500] Android - IOU-Tapping hold request, cursor is shown but keypad is not opened

### ISSUE THREAD

**Issue by izarutskaya** [Expensify/App#37279] opened 2024-02-27 11:33 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.44
**Reproducible in staging?:** Y
**Reproducible in production?:** N
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** Applause-Internal Team

## Action Performed:
1. Launch app
2. Tap 1:1 report
3. Create request money
4. Tap IOU to open details page
5. Tap 3 dots on top
6. Tap hold request

## Expected Result:
Tapping hold request, cursor is shown similarly keypad must be opened.

## Actual Result:
Tapping hold request, cursor is shown but keypad is not opened.

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [ ] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

https://github.com/Expensify/App/assets/115492554/b93abb62-df2e-4365-9b37-deedc5fed124

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~012dbcf06cfb05e557</li>
        <li>Upwork Job ID: 1762440810179457024</li>
        <li>Last Price Increase: 2024-02-27</li>
    </ul>
</details>

**Comment by izarutskaya** [comment] 2024-02-27 11:34
We think that this bug might be related to #vip-bills
CC @davidcardoza

**Comment by situchan** [comment] 2024-02-27 13:26
@izarutskaya can you please test again on production android app with the same android device where you reproduced bug on staging build?

**Comment by ikevin127** [comment] 2024-02-27 14:08
# Proposal

### Please re-state the problem that we are trying to solve in this issue

When the HoldReasonPage opens, the input is looks like it's focused but the keyboard doesn't show up.

### What is the root cause of that problem?

I was not able to find any offending PR within the [deploy checklist](https://github.com/Expensify/App/issues/37224), so I'm assuming this was not caused by the latest deploy.

This being said, the root cause of why the keyboard does not open on Android even though the input looks like it's focused (we see focused styles and the cursor) is because the focus is called when the component is not completely ready, most likely because of the navigation transition. I can confirm this since in rare cases, the keyboard does show-up (randomly) and I think this varies due to individual device thread load.

This is the logic that handles the autofocus on mount on native platforms, [see code block](https://github.com/Expensify/App/blob/cfa0ae37156208ebecdc6b2126464ec462271b76/src/components/TextInput/BaseTextInput/index.native.tsx#L85-L99).

### What changes do you think we should make in order to solve the problem?

Within the native specific code block mentioned above we can observe that we already have logic implemented to delay the focusing on mount via `shouldDelayFocus`.

So within the HoldReasonPage we should pass `shouldDelayFocus` as true to the [input component here](https://github.com/Expensify/App/blob/cfa0ae37156208ebecdc6b2126464ec462271b76/src/pages/iou/HoldReasonPage.tsx#L81-L90), under / above the existing `autoFocus` prop.

Since this alone would still not show the keyboard 100% of the time (depending on individual device thread load), I suggest wrapping the focus call from within the existing `shouldDelayFocus` timeout with `InteractionManager.runAfterInteractions` - this way besides the timeout's 300ms delay, we add the interactions delay too. This ensures the keyboard will show 100% of the time.

**Changed code:**

```ts
if (shouldDelayFocus) {
    const focusTimeout = setTimeout(() => {
        InteractionManager.runAfterInteractions(() => input.current?.focus()); // <- this line
    }, CONST.ANIMATED_TRANSITION);
    return () => clearTimeout(focusTimeout);
}
```

### Videos

<details>
<summary>Android: Native</summary>

| Before | After |
| ------------- | ------------- |
| <video src="https://github.com/Expensify/App/assets/56457735/1ec06fe9-b4bb-45bc-8154-54fc8fd5b907"> | <video src="https://github.com/Expensify/App/assets/56457735/17ac7898-23ee-4f2b-ab64-c0ba4e91fead"> |

</details>

**Comment by rlinoz** [comment] 2024-02-27 15:02
Even if we cannot reproduce this in prod, since we still can get the keyboard to show up, because of this I will remove the deploy blocker label.

**Comment by situchan** [comment] 2024-02-27 15:43
yup, @Krishna2323 proposed first [here](https://github.com/Expensify/App/issues/36948#issuecomment-1955100173)

**Comment by situchan** [comment] 2024-02-27 15:44
Ah sorry I just completed review. It was weekly and @Krishna2323 bumped me on slack so I already planned review today

**Comment by situchan** [comment] 2024-02-27 16:04
I understand why this was marked as deploy blocker.
On both staging and prod, sometimes keyboard shows and sometimes not, even on same device.
Mostly auto focus doesn't work in android without timeout. Maybe it accidentally worked when QA team tested on production app.

**Comment by ikevin127** [comment] 2024-02-27 16:38
I agree that @neonbhai's solution goes by the [docs](https://github.com/Expensify/App/blob/main/contributingGuides/STYLE.md#how-do-i-auto-focus-a-textinput-using-usefocuseffect), but in this case the TextInput [`shouldDelayFocus`](https://github.com/Expensify/App/blob/cfa0ae37156208ebecdc6b2126464ec462271b76/src/components/TextInput/BaseTextInput/index.native.tsx#L85-L99) logic doesn't work as expected because of the navigation transition delay and I think fixing that as suggested by my proposal [here](https://github.com/Expensify/App/issues/37279#issuecomment-1966632703) is a more holistic approach instead of using the  `useAutoFocusInput` hook in every component where the issue occurs.

What do you guys think ?

cc @rlinoz @ishpaul777 @situchan

**Comment by situchan** [comment] 2024-02-27 16:43
@ikevin127 `useAutoFocusInput` is not using TextInput [shouldDelayFocus](https://github.com/Expensify/App/blob/cfa0ae37156208ebecdc6b2126464ec462271b76/src/components/TextInput/BaseTextInput/index.native.tsx#L85-L99) logic at all.
The solution is actually combined with `autoFocus` prop removal.

**Comment by situchan** [comment] 2024-02-27 16:51
`useFocusEffect` approach is what we already discussed and landed on - https://expensify.slack.com/archives/C01GTK53T8Q/p1694660990479979

If you have better approach, please raise discussion on slack and get votes.

**Comment by rlinoz** [comment] 2024-02-28 12:23
I think we should hold this in favor of https://github.com/Expensify/App/issues/36948 since the proposal was first posted there.

Do you agree @situchan @ishpaul777 ?

**Comment by izarutskaya** [comment] 2024-02-29 14:03
Production video

https://github.com/Expensify/App/assets/115492554/686f54d3-ca15-4f1e-bf17-240e03e638ae

**Comment by rlinoz** [comment] 2024-03-01 17:48
Moving to weekly since it is on HOLD

**Comment by rlinoz** [comment] 2024-03-11 12:22
PR of the other issue is in draft.

**Comment by rlinoz** [comment] 2024-03-19 20:29
PR of the other issue is in draft.

**Comment by rlinoz** [comment] 2024-04-01 14:08
Other PR is deployed and fixed this one as expected, so closing.

**Closed by rlinoz** 2024-04-01 14:08 UTC
Labels: External, Engineering, Weekly, Help Wanted, Overdue, Bug
