### ISSUE TITLE
[HOLD for payment 2024-07-24] Policy category - Add GL Code

### ISSUE THREAD

**Issue by Gonals** [Expensify/App#44255] opened 2024-06-24 12:55 UTC
From the [design doc](https://docs.google.com/document/d/1dkS0mceibjUCMErQ1mWgUHjdHH0Ti_39DvgntRG-sws/edit#bookmark=id.qyclhfsfwutq):

```
settings/workspaces/{policyID}/categories/{categoryName}/gl-code -> CategoryGLCodePage
- Parameter: categoryName, the name of the category for which we are updating the GL code.
- Calls UpdateCategoryGLCode
policyID
categoryName - the name of the category for which we are updating the GL code.
glCode - the updated GL code for the category.
The pendingAction for the OfflineWithFeedback component will be policyCategory.pendingFields?.glCode

```

<details><summary>Issue Owner</summary>Current Issue Owner: @Christinadobrzyn</details>

**Comment by Gonals** [comment] 2024-06-24 12:59
@rushatgabhane will be working on this

**Comment by rushatgabhane** [comment] 2024-06-26 12:58
PR here: https://github.com/Expensify/App/pull/43149

**Comment by Christinadobrzyn** [comment] 2024-07-02 19:55
monitoring PR - https://github.com/Expensify/App/pull/43149

**Comment by Christinadobrzyn** [comment] 2024-07-09 16:20
Update for Melvin - monitoring PR - https://github.com/Expensify/App/pull/43149

**Comment by Christinadobrzyn** [comment] 2024-07-16 23:22
PR in staging - https://github.com/Expensify/App/pull/43149 

@Gonals do we need to be concerned about this comment - https://github.com/Expensify/App/issues/44255#issuecomment-2229783919

**Comment by rushatgabhane** [comment] 2024-07-16 23:30
@Christinadobrzyn no, that is part of plan.
We are replacing it with `Upgrade flow`

**Comment by Christinadobrzyn** [comment] 2024-07-23 19:19
I don't think we need a regression test since this is a new feature, correct @rushatgabhane?

Payouts due:

- [ ] Contributor+: $250 @rushatgabhane (paid in NewDot)

**Comment by Christinadobrzyn** [comment] 2024-07-24 19:22
Payment day is here - payment summary - https://github.com/Expensify/App/issues/44255#issuecomment-2248619739

I don't think we need a regression test for this since it's a new feature but let me know @rushatgabhane!

**Comment by rushatgabhane** [comment] 2024-07-26 01:57
@Christinadobrzyn this will need a regression steps because we want to avoid future bugs.

**Comment by rushatgabhane** [comment] 2024-07-26 01:57
Please assign @shubham1206agra as they were the C+ for the PR.

I was the PR author

**Comment by JmillsExpensify** [comment] 2024-07-26 03:07
$250 approved for @rushatgabhane

**Comment by Christinadobrzyn** [comment] 2024-07-26 18:10
Just checking on this - https://github.com/Expensify/App/issues/44255#issuecomment-2251824144

@shubham1206agra should you be paid for this as well? If yes, are you paid through Upwork or NewDot?

Can you create a regression test?

**Comment by Christinadobrzyn** [comment] 2024-07-26 18:32
Thanks @shubham1206agra - here's the upwork offer - https://www.upwork.com/nx/wm/offer/103283703

Are you happy with these as the regression test steps: 

1. Go to a collect policy
2. Go to category page
3. Select any category
4. Verify that you see GL Code
5. Verify that you can set a GL Code in the text input.
6. Verify that clicking save sets the GL Code and navigates you back

**Comment by Christinadobrzyn** [comment] 2024-07-29 16:07
Regression test here - https://github.com/Expensify/Expensify/issues/416064

Paid @shubham1206agra in Upwork. Payment summary here - https://github.com/Expensify/App/issues/44255#issuecomment-2248619739

Closing!

**Closed by Christinadobrzyn** 2024-07-29 16:07 UTC
Labels: Daily, NewFeature, Overdue, Awaiting Payment
