### ISSUE TITLE
[$50] Onboarding - Deeplink in concierge chat doesn't navigate to the correct screen within the app

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#50648] opened 2024-10-11 13:42 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 9.0.48-0
**Reproducible in staging?:** Y
**Reproducible in production?:** N
**If this was caught during regression testing, add the test name, ID and link from TestRail:** N/A
**Email or phone of affected tester (no customers):** htad26+dfhjkdsghg@gmail.com
**Issue reported by:** Applause - Internal Team

## Action Performed:
1. Go to staging.new.expensify.com
2. Sign up with a new Gmail account
3. Select "Manage my team's expenses" on onboarding modal > Select employee amount > Next
4. Choose any integration > Next > Complete the onboarding
5. Once logged in navigate to the workspace created > + icon > Submit expense > Manual > Enter any amount > Finish the flow
6. This will trigger a start of a free trial
7. Navigate to concierge chat > Click on the hyperlink "#admins" in the "start of a free trial" system message

## Expected Result:
The app should generate a link with a staging URL and should redirect to the correct screen within the app

## Actual Result:
The app generates a link with a production URL and redirects to production

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

<details>
  <summary>Add any screenshot/video evidence</summary>

  
</details> 

https://github.com/user-attachments/assets/4148cef7-74a6-4d49-94eb-439dc8939e5d

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~021844750386942511406</li>
        <li>Upwork Job ID: 1844750386942511406</li>
        <li>Last Price Increase: 2024-11-01</li>
<li>Automatic offers: </li>
<ul>
<li>situchan | Reviewer | 104675132</li>
<li>nkdengineer | Contributor | 104675134</li>
</ul></li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @situchan</details>

**Comment by lakchote** [comment] 2024-10-11 14:42
Not reproducible in dev.

I don't think this should be a blocker since when the deploy checklist hits production, the deeplink URL in Concierge chat will be correct.

**Comment by nkdengineer** [comment] 2024-10-11 20:51
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
The app generates a link with a production URL and redirects to production

### What is the root cause of that problem?
In [here](https://github.com/Expensify/App/blob/e4969b22e7dbb1f6a200cc587ced4ab665415c0e/src/libs/actions/Link.ts#L155), we are checking has the same origin, it mean in staging we can not open link with the origin `new.expensify.com`

https://github.com/Expensify/App/blob/e4969b22e7dbb1f6a200cc587ced4ab665415c0e/src/libs/actions/Link.ts#L155

https://github.com/Expensify/App/blob/e4969b22e7dbb1f6a200cc587ced4ab665415c0e/src/libs/actions/Link.ts#L174-L181

### What changes do you think we should make in order to solve the problem?


We can remove `hasSameOrigin` in this [condition](https://github.com/Expensify/App/blob/e4969b22e7dbb1f6a200cc587ced4ab665415c0e/src/libs/actions/Link.ts#L174-L181)


### What alternative solutions did you explore? (Optional)

https://github.com/user-attachments/assets/85f7dbc4-49c8-468b-aa6b-d0098e5fc633

**Comment by situchan** [comment] 2024-10-15 07:35
`hasSameOrigin` check was added on purpose.
@nkdengineer can you please find out PR which added this check and confirm your solution doesn't cause any regression?

**Comment by saraSwiti001** [comment] 2024-10-15 17:01
**Please re-state the problem that we are trying to solve in this issue.)**
The Concierge chat message for the 7-days trial contains an internal app link that does not take into account the request https origin. 

**What is the root cause of that problem?**

This is a BE problem, the content of this specific automated message is from the backend where it's constructed with an explicit href for the anchor tag that equals to the production url which is new.expensify.com instead of the staging or the development (It happens on both). 

The Front-End apps are just displaying what they're getting (which make sense as these messages should be generated on the backend and displayed as is) and for this message we are getting the production url. 

The server is not taking into account the origin of the https request instead it's treating all users as if they're coming from production, maybe even this specific message is fixed for all users. 

![Screenshot 2024-10-15 at 7 32 06 PM](https://github.com/user-attachments/assets/125000f7-5e38-47f7-8035-72f68fd13c14)

**What changes do you think we should make in order to solve the problem?**
The server should take into account the origin of the https request and create the dynamic reference links accordingly. 

**What alternative solutions did you explore? (Optional)**
removing hasSameOrigin check, though opening hrefs that are intended for production on none-production environments doesn't sound correct too, we should open the link exactly as we are getting it from the backend, in order to avoid any edge cases, that's why removing hasSameOrigin is not a great idea too. Actually the current behavior makes sense the most, as the link is for the front end app is an "External link" just like any other external url that is being generated during the chat, a link that does not have the same origin as the application, which should be opened externally in a new tab just as is. 

One final note to mention is that after this message, neither the user nor the Concierge chat can regenerate the same href style (Imbedding the url within a text) for example writing "GOOGLE" but enabling a redirection to "www.google.com" when pressing the word.

**Comment by nkdengineer** [comment] 2024-10-15 18:31
@situchan I think we should confirm what is expected here, do we want to be redirected to another origin when we click on a link or we only want to do that with staging environments? cc @lakchote

**Comment by lakchote** [comment] 2024-10-16 09:01
> @situchan I think we should confirm what is expected here, do we want to be redirected to another origin when we click on a link or we only want to do that with staging environments? cc @lakchote

We should not introduce staging specific logic.

@nkdengineer could you please answer this question from @situchan:
> @nkdengineer can you please find out PR which added this check and confirm your solution doesn't cause any regression?

**Comment by nkdengineer** [comment] 2024-10-16 17:02
> can you please find out PR which added this check and confirm your solution doesn't cause any regression?

@situchan @lakchote  it is added in this [PR](https://github.com/Expensify/App/pull/30664/files) and I confirm that it will not cause any regression as expected in the OP of the issue

**Comment by situchan** [comment] 2024-10-16 18:18
@nkdengineer no, it's not. That PR just moved logic from [here](https://github.com/Expensify/App/pull/30664/files#diff-810e7a5e5e8692ea5ea69e3b593e7e6abb3992e2682a7aaf89c8615db6840d83L30)

**Comment by nkdengineer** [comment] 2024-10-18 03:49
@situchan It was first added in this [PR](https://github.com/Expensify/App/pull/24483). please check again

**Comment by lakchote** [comment] 2024-10-21 06:20
@situchan could you please answer @nkdengineer's [comment](https://github.com/Expensify/App/issues/50648#issuecomment-2421275436)?

**Comment by situchan** [comment] 2024-10-21 18:31
reviewing

**Comment by situchan** [comment] 2024-10-21 19:22
@nkdengineer removing `hasSameOrigin` will cause [regression](https://github.com/Expensify/App/issues/22523)

**Comment by nkdengineer** [comment] 2024-10-24 19:11
@situchan @lakchote  as this [issue](https://github.com/Expensify/App/issues/22523) and expected in the OP so we only want to redirect to another origin with staging environment, right?

**Comment by lakchote** [comment] 2024-10-25 05:53
The functionality we want is:

Given an #admins link in a system message related to a free trial
I'm redirected to the #admins room without opening a new URL (deeplink).

But I'd like to have a solution where _no specific staging_ environment code is written e.g we don't want to check if we're on staging, the solution should abstract that.

**Comment by situchan** [comment] 2024-10-28 06:10
No viable solution yet

**Comment by nkdengineer** [comment] 2024-10-29 19:26
@lakchote Since the report link in the start free trial is the production link, I have two options with two behavior

1. If we want to open it in the new tab and log in with the correct account if we're in another environment, we can use `openExternalLinkWithToken` if `internalNewExpensifyPath` exists and `hasSameOrigin` is `false`

https://github.com/Expensify/App/blob/e4969b22e7dbb1f6a200cc587ced4ab665415c0e/src/libs/actions/Link.ts#L190

2. If we want to open it without a new tab we should return the URL with the format `%baseURL${internalPath}` then frontend can replace it with the current `environmentURL`

https://github.com/Expensify/App/blob/0b547fc290371f80091e79b74ed5caf1120351bd/src/libs/ReportActionsUtils.ts#L752

**Comment by lakchote** [comment] 2024-10-30 10:54
Since it's a deeplink, redirecting to the correct room without opening a tab is expected.

@situchan what do you think of option #2 from @nkdengineer?

**Comment by situchan** [comment] 2024-10-30 21:16
Option 2 sounds good to me

**Comment by lakchote** [comment] 2024-10-31 08:29
I like option #2 too, @nkdengineer let's go with that.

**Comment by nkdengineer** [comment] 2024-10-31 08:51
```
{
    "actionName": "ADDCOMMENT",
    "actorAccountID": 8392101,
    "avatar": "https://d1wpcgnaa73g0y.cloudfront.net/894b50e60056c966d12216005fbcacec8ce5a2c0.png",
    "created": "2024-10-31 08:32:45.660",
    "lastModified": "2024-10-31 08:32:45.660",
    "message": [
        {
            "type": "COMMENT",
            "html": "<h1>You’ve started a free trial!</h1><br />Welcome to your free 7-day trial of Expensify <emoji>🎉</emoji> Use it to continue exploring your workspace's benefits, including tracking expenses, reimbursing employees, managing company spend, and more.<br /><br />If you have any questions, chat with your dedicated Setup Specialist in <a href=\"https://new.expensify.com/r/8468742852675408\" target=\"_blank\" rel=\"noreferrer noopener\">#admins</a>. Enjoy!",
            "text": "You’ve started a free trial!\n\nWelcome to your free 7-day trial of Expensify 🎉 Use it to continue exploring your workspace's benefits, including tracking expenses, reimbursing employees, managing company spend, and more.\n\nIf you have any questions, chat with your dedicated Setup Specialist in #admins. Enjoy!",
            "isEdited": false,
            "whisperedTo": [],
            "isDeletedParentAction": false,
            "deleted": "",
            "reactions": []
        }
    ],
    "originalMessage": {
        "html": "<h1>You’ve started a free trial!</h1><br />Welcome to your free 7-day trial of Expensify <emoji>🎉</emoji> Use it to continue exploring your workspace's benefits, including tracking expenses, reimbursing employees, managing company spend, and more.<br /><br />If you have any questions, chat with your dedicated Setup Specialist in <a href=\"https://new.expensify.com/r/8468742852675408\" target=\"_blank\" rel=\"noreferrer noopener\">#admins</a>. Enjoy!",
        "isNewDot": true,
        "lastModified": "2024-10-31 08:32:45.660"
    },
    "person": [
        {
            "type": "TEXT",
            "style": "strong",
            "text": "Expensify Concierge"
        }
    ],
    "reportActionID": "4424774399671986900",
    "shouldShow": true,
    "timestamp": 1730363565,
    "reportActionTimestamp": 1730363565660,
    "automatic": false,
    "whisperedToAccountIDs": []
}
```

@lakchote This will require the BE change that will change the `https://new.expensify.com` in admin room href to `%baseURL`

When it's done I will create an FE PR to update `replaceBaseURLInPolicyChangeLogAction` and accept the concierge action because now we're only doing this logic with `policyChangeLogAction`

https://github.com/Expensify/App/blob/0b547fc290371f80091e79b74ed5caf1120351bd/src/libs/ReportActionsUtils.ts#L737-L740

**Comment by lakchote** [comment] 2024-11-01 06:32
I've discussed about the issue internally.

Given that's an automated message in concierge for a free trial, it'd really only affect applause and internal employees (even then it'd be an edge case),

We've decided to not fix that because it only affects staging. Though you should be compensated for the work done so far @nkdengineer @situchan, that's why I'm proposing a $50 payment for each of you.

Assigning a BZ member to issue payment, and then I'll close the issue.

**Comment by lakchote** [comment] 2024-11-01 06:33
@trjExpensify please see [my comment](https://github.com/Expensify/App/issues/50648#issuecomment-2451378475) just above, thanks!

**Comment by trjExpensify** [comment] 2024-11-01 10:47
Cool, payment summary as follows: 

- $50 to @situchan 
- $50 to @nkdengineer 

Let me know when you have accepted the pending offers that have already been sent. Then I'll adjust and settle.

**Comment by trjExpensify** [comment] 2024-11-07 20:39
@situchan, paid. @nkdengineer, waiting for you to accept [the offer](https://www.upwork.com/nx/wm/offer/104675134).

**Comment by lakchote** [comment] 2024-11-11 07:33
> @situchan, paid. @nkdengineer, waiting for you to accept [the offer](https://www.upwork.com/nx/wm/offer/104675134).

^ @nkdengineer did you accept the offer?

**Comment by nkdengineer** [comment] 2024-11-11 07:57
@lakchote I just did, thanks

**Comment by trjExpensify** [comment] 2024-11-12 01:10
Paid, closing!

**Closed by trjExpensify** 2024-11-12 01:10 UTC
Labels: External, Engineering, Daily, Overdue, Awaiting Payment, Bug
