### ISSUE TITLE
[HOLD for payment 2024-01-05] [$500] Prohibit the use of defaultProps in ts functional components

### ISSUE THREAD

**Issue by roryabraham** [Expensify/App#33197] opened 2023-12-16 02:13 UTC
### Problem
Our TypeScript guidelines state that functional components should use prop destructuring instead of `defaultProps`, but it's still possible for developers who don't know that to try and use `defaultProps`. In the worst case, that means we'll have inconsistent patterns for default props in our TS functional components. In a more typical case, the development cycle is slowed because we have to request changes during review and wait for the developer to make those changes.

### Solution
Set up an ESLint rule that prohibits the use of `defaultProps` in TypeScript functional components, and directs developers to use prop destructuring instead. To be clear, this means that `defaultProps` _should_ be allowed:

- in JavaScript files
- in TS files that contain class components (there should not be many of these, but some may exist)
    - it's not ideal if we have to suppress the linter to make this case work, but it's an option.
<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01e2d42d1ab75ab97a</li>
        <li>Upwork Job ID: 1735845538188914688</li>
        <li>Last Price Increase: 2023-12-20</li>
<li>Automatic offers: </li>
<ul>
<li>alitoshmatov | Reviewer | 28063449</li>
<li>ishpaul777 | Contributor | 28063450</li>
</ul></li>
    </ul>
</details>

**Comment by roryabraham** [comment] 2023-12-16 02:14
Adjusting the bounty for this to $250

**Comment by Tony-MK** [comment] 2023-12-16 02:28
@roryabraham, Is it possible for me to work on this issue? If so, do I need a proposal? Thanks 😄

**Comment by samilabud** [comment] 2023-12-16 03:19
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
Prohibit the use of defaultProps in ts functional components

### What is the root cause of that problem?
Our TypeScript guidelines state that functional components should use prop destructuring instead of defaultProps.

### What changes do you think we should make in order to solve the problem?
We should modify the file [.eslintrc.js ](https://github.com/Expensify/App/blob/main/.eslintrc.js), adding a new rule like:
```
rules: {
    'no-default-props': ['error', { allowDefaultProps: true }],
  },

```
Then we can create a file/rule called eslint-rules/no-default-props.js with a content like:

```
module.exports = {
  meta: {
    type: 'problem',
    docs: {
      description: 'Prohibit the use of defaultProps in TypeScript/JS functional components.',
    },
    schema: [
      {
        type: 'object',
        properties: {
          allowDefaultProps: {
            type: 'boolean',
            default: false,
          },
        },
        additionalProperties: false,
      },
    ],
  },
  create: function (context) {
    const allowDefaultProps = context.options[0]?.allowDefaultProps || false;

    return {
      FunctionDeclaration(node) {
        if (!allowDefaultProps && node.returnType && node.returnType.typeAnnotation.type === 'TSFunctionType') {
          const defaultProps = node.body.body.find(
            (item) =>
              item.type === 'TSPropertySignature' &&
              item.key.name === 'defaultProps' &&
              item.typeAnnotation &&
              item.typeAnnotation.type === 'TSTypeAnnotation'
          );

          if (defaultProps) {
            context.report({
              node: defaultProps,
              message: 'Use prop destructuring instead of defaultProps in TypeScript functional components.',
            });
          }
        }
      },
    };
  },
};
```
Finally, we should include our rules in ESLint configuration file like:

```
overrides: [
  {
    files: ['*.ts', '*.tsx'],
    rules:{
     '@typescript-eslint/no-default-props': ['error', { allowDefaultProps: true }],
    'eslint-rules/no-default-props': ['error', { allowDefaultProps: true }],
    },
 }
  ],

```

**Comment by harshcut** [comment] 2023-12-16 03:32
I think we can directly use this ESLint rule https://github.com/jsx-eslint/eslint-plugin-react/blob/master/docs/rules/require-default-props.md#rule-options.

```
...
"react/require-default-props": [<enabled>, {
  "forbidDefaultForRequired": <boolean>,
  "classes": "defaultProps" | "ignore",
  "functions": "defaultProps" | "defaultArguments" | "ignore"
  // @deprecated Use `functions` option instead.
  "ignoreFunctionalComponents": <boolean>,
}]
...
```

- `enabled`: for enabling the rule. 0=off, 1=warn, 2=error. Defaults to 0.
- `forbidDefaultForRequired`: optional boolean to forbid prop default for a required prop. Defaults to false.
- `classes`: optional string to determine which strategy a class component uses for defaulting props. Defaults to "defaultProps".
- `functions`: optional string to determine which strategy a functional component uses for defaulting props. Defaults to "defaultProps".
- `ignoreFunctionalComponents`: optional boolean to ignore this rule for functional components. Defaults to false. Deprecated, use functions instead.

This will resolve to:

```
...
"react/require-default-props": [2, {
  "classes": "defaultProps",
  "functions": "defaultArguments",
}]
...
```

**Comment by harshcut** [comment] 2023-12-16 03:37
Contributor details
Your Expensify account email: harshskarande@gmail.com
Upwork Profile Link: https://www.upwork.com/freelancers/~0174e25cfa3809f980

**Comment by ibrahimbhat** [comment] 2023-12-16 14:56
Contributor details
Your Expensify account email: mohamedibrahim35@gmail.com
Upwork Profile Link: https://www.upwork.com/freelancers/~017a73cdd3a1687db4

**Comment by abekkala** [comment] 2023-12-19 18:49
I'm going ooo until Jan 02. But will keep this assigned to me so that I can process payment after the PR is deployed to prod, and waiting period has passed. I'll be checking in on the progress while ooo.

@ishpaul777  Fix $250 [Offer link](https://www.upwork.com/nx/wm/offer/28063450)
@alitoshmatov PR Review $250 [Offer link](https://www.upwork.com/nx/wm/offer/28063449)

**Comment by abekkala** [comment] 2023-12-19 21:04
Omg, why mevlin. Sorry @strepanier03 I don't know why it unassigned you.

**Comment by roryabraham** [comment] 2023-12-20 20:03
Adjusting the bounty back to $500

**Comment by roryabraham** [comment] 2023-12-24 00:47
PR merged, back to E/App PR now

**Comment by roryabraham** [comment] 2023-12-28 00:32
I did not use any C+ services in the course of this issue, so I'm removing @alitoshmatov's assignment here

**Comment by roryabraham** [comment] 2023-12-29 21:49
No regression tests needed here

**Comment by abekkala** [comment] 2024-01-04 17:45
### PAYMENTS FOR JAN 05

- @ishpaul777 Fix **$500** [Offer link](https://www.upwork.com/nx/wm/offer/28063450)
- @alitoshmatov PR Review **$500** [Offer link](https://www.upwork.com/nx/wm/offer/28063449)

**Comment by alitoshmatov** [comment] 2024-01-05 07:54
@abekkala no need payment for me since I did not review the PR

**Comment by abekkala** [comment] 2024-01-08 14:19
@alitoshmatov ah yes, I do see that now. Thank you!

**Comment by abekkala** [comment] 2024-01-08 14:23
@ishpaul777 $500 payment sent and contract ended - thank you! 🎉 
<img width="1071" alt="Screenshot 2024-01-08 at 8 22 49 AM" src="https://github.com/Expensify/App/assets/11966460/38b1a957-9465-49a1-ab73-f1376a380a8c">

**Closed by abekkala** 2024-01-08 14:23 UTC
Labels: External, Daily, NewFeature, Awaiting Payment
