### ISSUE TITLE
[$500] mWeb - Auto-fill appears for a brief moment in Abracadabra/Here's your magic code screen

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#34699] opened 2024-01-18 01:38 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.26-1
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** Applause - Internal Team
**Slack conversation:**

## Action Performed:
1. Navigate to staging.new.expensify.com
2. Start the sign-in flow by entering an email
3. Go to the email and locate the magic code link > copy the link
4. Open a new tab and navigate to the staging link
5. Verify the "Abracadabra, you're logged in."

## Expected Result:
Auto-fill shouldn't appear on the Abracadabra/Here's your magic code screen

## Actual Result:
Auto-fill appears for a brief moment in Abracadabra/Here's your magic code screen

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [x] iOS: mWeb Safari
- [ ] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details> 

https://github.com/Expensify/App/assets/78819774/14ba011b-1c39-44b3-a70f-b5379368aeaa

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~013401609f515ba854</li>
        <li>Upwork Job ID: 1747795583960612864</li>
        <li>Last Price Increase: 2024-01-25</li>
    </ul>
</details>

**Comment by lanitochka17** [comment] 2024-01-18 01:39
[#wave9-collect-signup](https://expensify.enterprise.slack.com/archives/C05NJ4SLBMF)

**Comment by situchan** [comment] 2024-01-18 04:47
Dupe of #32683

**Comment by Santhosh-Sellavel** [comment] 2024-01-25 18:13
cc: @MitchExpensify Seems dupe of https://github.com/Expensify/App/issues/32683 please close this one.

**Closed** 2024-01-27 01:40 UTC
Labels: External, Daily, Help Wanted, Bug
