### ISSUE TITLE
Chat - “Paste and Match Style”, “Paste as plain text”, Shift+Option+Cmd+V doesn't remove markdown

### ISSUE THREAD

**Issue by kavimuru** [Expensify/App#31805] opened 2023-11-23 23:04 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.3.0
**Reproducible in staging?:** y
**Reproducible in production?:** n
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** Applause internal team
**Slack conversation:**

## Action Performed:
1. Go to staging.new.expensify.com or open Desktop App
2. Login with any account
3. Open any chat
4. Copy message with markdown
5. Paste it using “Paste and Match Style”, “Paste as plain text” for Desktop or Shift+Option+Cmd+V for Web

## Expected Result:
Copied message pasted with markdown removed

## Actual Result:
“Paste and Match Style”, “Paste as plain text”, Shift+Option+Cmd+V doesn't remove markdown

## Workaround:
unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

https://github.com/Expensify/App/assets/43996225/33b05b3a-ab82-44f0-bf94-2ce0c043cd61

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by luacmartins** [comment] 2023-11-23 23:21
Probably coming from https://github.com/Expensify/App/pull/31619

**Comment by goldendragon430** [comment] 2023-11-24 07:55
Hi

**Comment by FitseTLT** [comment] 2023-11-24 09:27
> Probably coming from #31619

Yeah, confirmed. 
So @robertKozik @flodnv it looks like the simple fix of setting markdown on the plain text of the clipboard doesn't work so I have got two options:
1. To make only `PrivateNote` (a module) handle code paste by sharing same code used in `Compose`.
2. Make kind of `TextInput` module (or update the already exiting one) that handle code paste (html) that will be shared everywhere we use a text input that should have code paste feature.

**Comment by flodnv** [comment] 2023-11-24 15:47
Honestly I don't know what's best, maybe for now we just revert that PR

**Comment by luacmartins** [comment] 2023-11-24 18:23
Agreed. Revert PR here - https://github.com/Expensify/App/pull/31852

**Comment by luacmartins** [comment] 2023-11-27 17:48
We reverted this PR and the issue is no longer reproducible. Closing this issue in favor of the original one - https://github.com/Expensify/App/issues/29806

**Closed** 2023-11-27 17:48 UTC
Labels: Engineering, Hourly, Overdue, Bug
