### ISSUE TITLE
iOS Production Deploy Failure

### ISSUE THREAD

**Issue by roryabraham** [Expensify/App#4978] opened 2021-09-01 01:43 UTC
We need to investigate and fix this deploy failure: https://github.com/Expensify/App/runs/3479417738

**Comment by roryabraham** [comment] 2021-09-01 01:47
In the meantime, I've manually submitted `1.0.90-2`

**Comment by roryabraham** [comment] 2021-09-01 04:25
Sorry, originally meant to assign this to you @AndrewGable

**Comment by AndrewGable** [comment] 2021-09-01 15:21
I think this failed because the step didn't run, which I believe is a known issue with releases, the tag has to include the code merged. So we need to wait until we deploy production once more to fully test the new production fix.

**Comment by roryabraham** [comment] 2021-09-02 00:07
Reopening, we saw the same failure today: https://github.com/Expensify/App/runs/3490379202

**Comment by AndrewGable** [comment] 2021-09-02 17:35
Ok so this time the code did actually run, but it just didn't work. Progress!

**Comment by AndrewGable** [comment] 2021-09-02 17:45
It looks like the version was actually set correctly from what I was expecting it to be set

<img width="673" alt="Screen Shot 2021-09-02 at 11 44 41 AM" src="https://user-images.githubusercontent.com/2838819/131891915-da61a160-770c-4f8b-bc45-efd4d88526a6.png">

But maybe fastlane is expecting something different than that format. Looking into it!

**Comment by AndrewGable** [comment] 2021-09-02 18:55
I can reproduce this locally with `1.0.92.0` as well. I am thinking the `build_number` needs to be something else 🤔

**Comment by AndrewGable** [comment] 2021-09-02 20:29
Issue 1: We were not including the `app_version` key. Now including `app_version: ENV["VERSION"]` in deliver will create a release.

<img width="1380" alt="Screen Shot 2021-09-02 at 2 29 07 PM" src="https://user-images.githubusercontent.com/2838819/131911759-a19e6e08-5c80-4530-9f38-b73632652ad0.png">

Issue 2: Now I am seeing a new error: `[14:23:59]: Build number: 1.0.92.0 does not exist`

**Comment by AndrewGable** [comment] 2021-09-02 21:27
Really confusing error.. The build number does exist, but Fastlane cannot find it. I'm trying to debug the fastlane response right now.

**Comment by AndrewGable** [comment] 2021-09-02 22:06
Ok so.. This is weird.. When I set the `app_version` to `1.0.92.0` it fails. But when I set it to `1.0.92` it will work!

**Comment by AndrewGable** [comment] 2021-09-02 22:06
Now trying to fix this new error..

```
[16:06:06]: Making sure the latest version on App Store Connect matches '1.0.92'...
[16:06:07]: '1.0.92' is the latest version on App Store Connect
[16:06:07]: Detected languages: ["default", "en-US"]
[16:06:07]: Finished the upload to App Store Connect
[16:06:07]: Selecting existing build-number: 1.0.92.0
[16:06:08]: Selecting build 1.0.92 (1.0.92.0)...
[16:06:09]: Successfully selected build
[16:06:12]: Successfully updated IDFA declarations on App Store Connect
+---------------+----------------+
|          Lane Context          |
+---------------+----------------+
| PLATFORM_NAME | ios            |
| LANE_NAME     | ios production |
+---------------+----------------+
[16:06:13]: The request cannot be fulfilled because of the state of another resource. - Submit for review errors found.
The provided entity is missing a required attribute - You must provide a value for the attribute 'whatsNew' with this request
```

**Comment by AndrewGable** [comment] 2021-09-02 22:17
Ok cool finally got all the flags set correctly! Going to clean up the code and submit a PR

<img width="1049" alt="Screen Shot 2021-09-02 at 4 16 40 PM" src="https://user-images.githubusercontent.com/2838819/131923380-2778ea88-8721-4ead-9d99-8f3a63036100.png">
<img width="1398" alt="Screen Shot 2021-09-02 at 4 16 32 PM" src="https://user-images.githubusercontent.com/2838819/131923387-2d52a210-2574-493c-abcc-fd8020bc492b.png">

**Comment by botify** [comment] 2021-09-03 00:14
:hand: This PR was not deployed to staging yet because QA is ongoing. It will be automatically deployed to staging after the next production release.

**Closed** 2021-09-03 00:13 UTC
Labels: Engineering, Daily, Improvement

**Comment by botify** [comment] 2021-09-03 01:31
🚀 [Deployed](https://github.com/Expensify/App/actions/runs/1196336036) to staging by @roryabraham in version: 1.0.92-1 🚀

 platform | result 
 ---|--- 
🤖 android 🤖|success ✅ 
🖥 desktop 🖥|success ✅
🍎 iOS 🍎|failure ❌ 
🕸 web 🕸|success ✅

**Comment by botify** [comment] 2021-09-04 00:02
🚀 [Deployed](https://github.com/Expensify/App/actions/runs/1199734951) to production by @roryabraham in version: 1.0.93-1 🚀

 platform | result 
 ---|--- 
🤖 android 🤖|success ✅ 
🖥 desktop 🖥|success ✅
🍎 iOS 🍎|success ✅ 
🕸 web 🕸|success ✅
