### ISSUE TITLE
[HOLD for payment 2024-01-04] [HOLD for payment 2024-01-03] [$500] Android - Modal thumbnail is not displayed for workspace manual request

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#33591] opened 2023-12-26 14:01 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.17-1
**Reproducible in staging?:** y
**Reproducible in production?:** n
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** Applause - Internal Team
**Slack conversation:**

**Issue found when executing PR** https://github.com/Expensify/App/pull/33347

## Action Performed:
1. Launch app
2. Tap on a Workspace chat
3. Tap plus icon ---- Request money ----- Manual
4. Enter an amount
5. Tap next
6. Tap show more
7. Select a category
8. Tap request
9. Tap on the new request created to open detail page

## Expected Result:
Modal thumbnail must be displayed for workspace manual request.

## Actual Result:
Modal thumbnail is not displayed for workspace manual request.

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [ ] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

https://github.com/Expensify/App/assets/93399543/d0913e33-b9b8-475b-afb0-bb591ac3bb10

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~0160d858d1b98fe7ed</li>
        <li>Upwork Job ID: 1739767395487518720</li>
        <li>Last Price Increase: 2023-12-26</li>
<li>Automatic offers: </li>
<ul>
<li>c3024 | Reviewer | 28070428</li>
<li>mkhutornyi | Contributor | 28070429</li>
</ul></li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @JmillsExpensify</details>

**Comment by marcochavezf** [comment] 2023-12-26 21:54
Thanks for the proposal @mkhutornyi, can you create a PR with the solution in the next few hours?

**Comment by marcochavezf** [comment] 2023-12-26 21:57
Ok great, assigning you

**Comment by mountiny** [comment] 2023-12-26 22:24
Thanks @marcochavezf feel free to request a CP in Slack once PR is merged!

**Comment by mountiny** [comment] 2023-12-26 22:45
@mkhutornyi Whats your ETA?

**Comment by mountiny** [comment] 2023-12-26 22:52
We might need to reduce the reward then 😄

**Comment by marcochavezf** [comment] 2024-01-04 21:37
Hi @c3024, could you complete the bz checklist?

**Comment by c3024** [comment] 2024-01-05 15:30
**BugZero Checklist:** The PR fixing this issue has been merged! The following checklist ([instructions](https://stackoverflow.com/c/expensify/questions/14574)) will need to be completed before the issue can be closed:

* [x]  [@c3024] The PR that introduced the bug has been identified. Link to the PR: #30905 
* [x]  [@c3024] The offending PR has been commented on, pointing out the bug it caused and why, so the author and reviewers can learn from the mistake. Link to comment: https://github.com/Expensify/App/pull/30905/files#r1443009438
* [x]  [@c3024] A discussion in #expensify-bugs has been started about whether any other steps should be taken (e.g. updating the PR review checklist) in order to catch this type of bug sooner. Link to discussion: NA. This was caused due to a new library expo-image used for images. So such discussion has no benefit.
* [x]  [@c3024] Determine if we should create a regression test for this bug. No, the bug was identified in staging testing
* [x]  [@c3024] If we decide to create a regression test for the bug, please propose the [regression test](https://github.com/Expensify/App/blob/main/contributingGuides/REGRESSION_TEST_BEST_PRACTICES.md) steps to ensure the same bug will not reach production again. NA

**Comment by marcochavezf** [comment] 2024-01-09 20:17
Checklist completed, only payment is pending

**Comment by marcochavezf** [comment] 2024-01-17 20:08
Hi @JmillsExpensify, could you handle the payment for @mkhutornyi as contributor and @c3024 as C+ reviewer?

**Comment by JmillsExpensify** [comment] 2024-01-24 03:12
Sure thing! Payment summary:

 - Issue reporter: QA
 - Contributor: @mkhutornyi $500
 - Contributor+: @c3024 $500

**Comment by JmillsExpensify** [comment] 2024-01-24 03:13
Everyone is paid out. Closing the issue.

**Closed by JmillsExpensify** 2024-01-24 03:13 UTC
Labels: External, Engineering, Daily, Awaiting Payment, Bug
