### ISSUE TITLE
[$500] Unread line appears on previous message when money request paid or requested.

### ISSUE THREAD

**Issue by kavimuru** [Expensify/App#26663] opened 2023-09-04 13:28 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Request money to account B
2. Observe the unread line on request report
3. Pay from account B
4. Request money again to account B
5. Observe the unread indicator
6. Pay from account B
7. Observe the unread indicator
8. Request money to account B
9. Observe the unread indicator
## Expected Result: 
The unread indicator should be on the latest message.
## Actual Result: 
The unread indicator is not on the latest message.
## Workaround:
Can the user still use Expensify without this being fixed? Have you informed them of the workaround?

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [x] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 1.362-4
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/43996225/82b23311-0a22-41ff-9212-e3379b1168c3

https://github.com/Expensify/App/assets/43996225/49847bdb-c271-4eb7-8659-4542bd350467

**Expensify/Expensify Issue URL:**
**Issue reported by:** @krishna2323
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1692993587476099

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~0136e06c7af01df233</li>
        <li>Upwork Job ID: 1698706376487473152</li>
        <li>Last Price Increase: 2023-09-11</li>
    </ul>
</details>

**Comment by Tony-MK** [comment] 2023-09-04 18:21
@kavimuru Issue title has a spelling error (reuested -> requested)

**Comment by Tony-MK** [comment] 2023-09-04 18:26
## Proposal

### Please re-state the problem that we are trying to solve in this issue.

Unread line appears on previous message when money request paid or requested.

### What is the root cause of that problem?

The `ReportActionItem` component has the propType of `shouldDisplayNewMarker`. The propType needs to be `false` to not render the `UnreadActionIndicator` component but it memorizes the previous `shouldDisplayNewMarker` value which is `true` and doesn't change.

https://github.com/Expensify/App/blob/d2bdaece9151c8c65d3b4bc4c9578be663f1950d/src/pages/home/report/ReportActionItem.js#L560

### What changes do you think we should make in order to solve the problem?

Delete the line below, to make the report component not render `UnreadActionIndicator` because the `shouldDisplayNewMaker` will be `false` after rerender.
https://github.com/Expensify/App/blob/d2bdaece9151c8c65d3b4bc4c9578be663f1950d/src/pages/home/report/ReportActionItem.js#L654

**Comment by astrohunter62** [comment] 2023-09-04 19:34
Why is it a bug?

**Comment by laurenreidexpensify** [comment] 2023-09-07 09:31
@narefyev91 bump for review thanks

**Comment by devrari** [comment] 2023-09-07 12:02
@narefyev91  I think this is an error from  backend, 
I  can see lastReadTime  is  not getting updated properly , and still points  to last message. 
command=RequestMoney Response  I  can see Onyx Merge LastReadTime is not coming  as proper.
<img width="1680" alt="Screenshot 2023-09-07 at 17 23 55" src="https://github.com/Expensify/App/assets/4333876/f1e860de-a036-4108-83c6-9de2d02cfc26">

<img width="1680" alt="Screenshot 2023-09-07 at 17 25 53" src="https://github.com/Expensify/App/assets/4333876/fc591692-2b2a-4bb0-a798-b71b3f04b029">

**Comment by narefyev91** [comment] 2023-09-07 16:43
@laurenreidexpensify Sorry - i'm on EU React native conference - will take a look on Monday - but seems to me - it maybe really API issue as @devrari mentioned - because indicator rely on some API data
`shouldDisplayNewMarker = isCurrentMessageUnread && !isMessageUnread(nextMessage, report.lastReadTime);`

**Comment by laurenreidexpensify** [comment] 2023-09-12 10:02
@narefyev91 have you had a moment to look yet? thanks

**Comment by narefyev91** [comment] 2023-09-12 10:03
Hey @laurenreidexpensify it's a BE issue - we need to make it internal

**Comment by laurenreidexpensify** [comment] 2023-09-13 08:57
@luacmartins this internal as a back end issue

**Comment by luacmartins** [comment] 2023-09-14 01:45
PR up - https://github.com/Expensify/Auth/pull/8689

**Comment by laurenreidexpensify** [comment] 2023-10-05 10:58
@luacmartins do we need to issue payments for this one? just realised it's been merged for 3 weeks 😅

**Comment by luacmartins** [comment] 2023-10-05 16:19
Thanks for raising this! Yes, we should issue payment for reporting bonus and then we can close this out!

**Comment by laurenreidexpensify** [comment] 2023-10-13 13:21
@Krishna2323 job sent in Upwork 👍

**Comment by laurenreidexpensify** [comment] 2023-10-13 13:22
https://www.upwork.com/en-gb/nx/wm/offer/27179717

**Comment by laurenreidexpensify** [comment] 2023-10-13 13:31
Payment Summary:

- bug reporter @Krishna2323 $50 paid in Upwork

**Closed by laurenreidexpensify** 2023-10-13 13:31 UTC
Labels: Reviewing, Engineering, Daily, Internal, Bug
