### ISSUE TITLE
[HOLD for payment 2022-11-02] [$250] BUG: App crashes after signing in while trying to open profile details URL reported by @adeel0202

### ISSUE THREAD

**Issue by kavimuru** [Expensify/App#11547] opened 2022-10-03 19:00 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:

1. Launch the app on web browser, sign in as User A
2. Open User B's profile
3. Copy the URL from the address bar that contains User B's email, ie. `https://new.expensify.com/details?login=manager.haxhiu%40expensicorp.com`
4. Open incognito mode of the browser
5. Paste the copied URL in the address bar and hit enter
6. Enter your email or phone number and press Continue
7. Enter your password and press Sign in

## Expected Result:
User signs in and the profile is displayed

## Actual Result:
User signs in and the app crashes

## Workaround:
Can the user still use Expensify without this being fixed? Have you informed them of the workaround?

## Platform:

Where is this issue occurring?

- Web

**Version Number:** 
**Reproducible in staging?:** 
**Reproducible in production?:** 
**Email or phone of affected tester (no customers):** 
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** 

https://user-images.githubusercontent.com/43996225/193657120-4ac7b39b-d282-4ee1-8e5c-495ff03a2e29.mov

https://user-images.githubusercontent.com/43996225/193657214-31e4d6f3-3152-4f53-b26a-e4963673859d.mp4

**Expensify/Expensify Issue URL:** 
**Issue reported by:** @adeel0202
**Slack conversation:** https://expensify.slack.com/archives/C01GTK53T8Q/p1664816204626559

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by parasharrajat** [comment] 2022-10-03 20:56
It may be because the contact does not exist on that account. I had a previous issue for this one which was closed for low priority. I will post the link later.

**Comment by adeel0202** [comment] 2022-10-04 06:12
@parasharrajat, the contact does exist on that account. In fact, it crashes even when both the accounts are same. Please check the first video, both the accounts are the same in the video.

**Comment by mallenexpensify** [comment] 2022-10-04 23:07
@parasharrajat please drop the link in if you find.  I'll check back to test later this week

**Comment by mallenexpensify** [comment] 2022-10-10 16:21
Sorry @cead22 , I applied `Engineering` before testing. 
I'm unable to reproduce in firefox or chrome, both in private/incognito.

@kavimuru can you see if you're able to reproduce? @adeel0202 can try too plz?

**Comment by adeel0202** [comment] 2022-10-10 16:52
@mallenexpensify yup, still able to reproduce.

https://user-images.githubusercontent.com/13783842/194916587-760dcb95-4491-4496-ab7f-5e4331704384.mp4

**Comment by mallenexpensify** [comment] 2022-10-10 22:32
Thanks @adeel0202 .  Took me a lil bit but I was able to reproduce, updated the OP to be more clear and title too. 
The majority of the time, if someone were to copy a profile link, it's be the report, ie https://new.expensify.com/r/91318393 vs clicking on the user's avatar to open the details *then* copy that link, ie. https://new.expensify.com/details?login=manager.haxhiu%40expensicorp.com. 

@cead22 back to you for more 👀 .     Let me know if you have questions too

**Comment by cead22** [comment] 2022-10-10 23:27
Labeled demolition because of the clear repro steps, but @Beamanator if you think this can be solved by a contributor, feel free to label External

**Comment by kavimuru** [comment] 2022-10-10 23:57
@mallenexpensify I am able to reproduce too.

https://user-images.githubusercontent.com/43996225/194969496-cd77b772-2601-4924-b7a8-3820ad8da860.mp4

**Comment by Beamanator** [comment] 2022-10-11 09:17
@sobitneupane idk how but I unassigned kavimuru & it accidentally unassigned you, so I just reassigned you as C+ & opened this up for proposals 👍

**Comment by mallenexpensify** [comment] 2022-10-11 21:22
Job Posted, @sobitneupane and @adeel0202 , please apply
https://www.upwork.com/jobs/~01d020bdebc25b53b6

@sobitneupane , can you please review @aimane-chnaif 's proposal above? Thx

**Comment by sobitneupane** [comment] 2022-10-12 14:49
@aimane-chnaif 
>After this fix, infinite loading shows on this page (if user is not in contacts list), which is the same behavior as when open deep link with logged in already

Can you please explain what you mean here?

**Comment by sobitneupane** [comment] 2022-10-12 15:34
@aimane-chnaif's [Proposal](https://github.com/Expensify/App/issues/11547#issuecomment-1274426698) looks good to me.

cc: @Beamanator 

🎀👀🎀 C+ reviewed

**Comment by Beamanator** [comment] 2022-10-24 11:15
PR merged 4 days ago 👍

**Comment by Beamanator** [comment] 2022-11-04 11:51
@mallenexpensify looks like payment is due here 👍

**Comment by mallenexpensify** [comment] 2022-11-04 15:59
Thanks @Beamanator , apologies for the delay. 
Everyone should be hired, can you please accept and comment on this issue when you have? 
https://www.upwork.com/jobs/~01d020bdebc25b53b6

@adeel0202 @aimane-chnaif @sobitneupane

**Comment by mallenexpensify** [comment] 2022-11-04 18:49
All paid $250/ea.  Thanks!

**Closed by mallenexpensify** 2022-11-04 18:49 UTC
Labels: External, Engineering, Daily, Demolition, Awaiting Payment, Bug
