### ISSUE TITLE
[HOLD for payment 2024-12-20] [$125] iOS - Chat - Emoji picker has no space to dismiss when searching for an emoji

### ISSUE THREAD

**Issue by IuliiaHerets** [Expensify/App#53218] opened 2024-11-27 15:17 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 9.0.67-1
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**If this was caught on HybridApp, is this reproducible on New Expensify Standalone?:** Y
**If this was caught during regression testing, add the test name, ID and link from TestRail:** https://expensify.testrail.io/index.php?/cases/view/2654739
**Email or phone of affected tester (no customers):** gatantm+88@gmail.com
**Issue reported by:** Applause Internal Team

## Action Performed:
1. Launch Expensify and Go to any chat
2. Tap on the emoji icon
3. Tap on the search bar on the emoji picker

## Expected Result:
There's a bit of space so a user can dismiss the picker without needing to make search results fewer or add an emoji

## Actual Result:
Describe what actually happenedOn the iPhone 12 mini there's not enough space on the top of the emoji picker when making a search to dismiss it. User needs to either add an emoji or first tap on an empty area of the picker to dismiss the keyboard and then tap to exit the picker.
Also the picker is slightly overlap by the time and status bar

## Workaround:
Unknown

## Platforms:

- [ ] Android: Standalone
- [ ] Android: HybridApp
- [ ] Android: mWeb Chrome
- [x] iOS: Standalone
- [x] iOS: HybridApp
- [ ] iOS: mWeb Safari
- [ ] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

https://github.com/user-attachments/assets/93f3d80b-dad9-446c-a2ce-2d8c92472f1d
  
</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~021861826366793735200</li>
        <li>Upwork Job ID: 1861826366793735200</li>
        <li>Last Price Increase: 2024-12-04</li>
<li>Automatic offers: </li>
<ul>
<li>huult | Contributor | 105266175</li>
</ul></li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @trjExpensify</details>

**Comment by FitseTLT** [comment] 2024-11-27 15:50
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
iOS - Chat - Emoji picker has no space to dismiss when searching for an emoji

### What is the root cause of that problem?
We are already making the maxHeight to be 95% for the popoverInnerContainer 
https://github.com/Expensify/App/blob/084a711842d6be379b18491ebe2cc6b48280006e/src/styles/index.ts#L1848
and calculating the max height for the emoji list accordingly here
https://github.com/Expensify/App/blob/084a711842d6be379b18491ebe2cc6b48280006e/src/components/EmojiPicker/EmojiPickerMenu/useEmojiPickerMenu.ts#L31
but we haven't considered the case when the keyboard is open
### What changes do you think we should make in order to solve the problem?

The maxHeight should be set to 95% of the windowHeight - keyboardHeight. we can use `useKeyboardState` to get the current keyboardHeight and update maxHeight values for both cases mentioned above.
### What alternative solutions did you explore? (Optional)

**Comment by huult** [comment] 2024-11-27 16:22
## Proposal

### Please re-state the problem that we are trying to solve in this issue.

Emoji picker has no space to dismiss when searching for an emoji

### What is the root cause of that problem?

We have set the maxHeight for BaseEmojiPickerMenu to windowHeight * 0.95.

https://github.com/Expensify/App/blob/9cae202fec631e82fb8fdfe8c661047cb3fccdce/src/components/EmojiPicker/EmojiPickerMenu/useEmojiPickerMenu.ts#L31

But when `maxHeight` is less than `height`, the content respects `maxHeight`, but the view's height still takes the value of `height`. Native views do not inherently enforce `maxHeight` constraints. While `maxHeight` is a CSS property respected by web-based rendering engines, native app layout systems prioritize explicit dimensions like height. Without explicitly calculating and setting the `height`, the view may expand beyond the intended bounds, leading to layout inconsistencies.

For example: 

The calculated listStyle is {"height": 300, "maxHeight": 87}
The red line in the image is 87, and the green line is 300, as described above

- <img width="349" alt="Screenshot 2024-11-27 at 23 14 45" src="https://github.com/user-attachments/assets/371edb51-0575-4e8d-9fc1-193064140404">

### What changes do you think we should make in order to solve the problem?

To resolve this issue, we need to compute the `height`. If `maxHeight` is less than `height`, then we set `maxHeight` equal to `height`, something like this:

```diff
// src/components/EmojiPicker/EmojiPickerMenu/index.native.tsx#L119
+    const computedHeight = listStyle.maxHeight ? Math.min(listStyle.height, listStyle.maxHeight) : listStyle.height;
// src/components/EmojiPicker/EmojiPickerMenu/index.native.tsx#L128
         <BaseEmojiPickerMenu
              isFiltered={isListFiltered}
              headerEmojis={headerEmojis}
              scrollToHeader={scrollToHeader}
              listWrapperStyle={[
                  listStyle,
                  {
                      width: Math.floor(windowWidth),
+                      height: computedHeight,
                  },
              ]}
              ref={emojiListRef}
              data={filteredEmojis}
              renderItem={renderItem}
              extraData={[filteredEmojis, preferredSkinTone]}
              stickyHeaderIndices={headerIndices}
              alwaysBounceVertical={filteredEmojis.length !== 0}
          />
```

This is an example change. We will discuss the calculation inside the hook and where to place it in the pull request

https://github.com/Expensify/App/blob/9cae202fec631e82fb8fdfe8c661047cb3fccdce/src/components/EmojiPicker/EmojiPickerMenu/useEmojiPickerMenu.ts#L31

<details>
<summary>POC</summary>

</details>

### What alternative solutions did you explore? (Optional)

**Comment by trjExpensify** [comment] 2024-11-27 17:35
This is pretty minor and specific to a 4+ year old device. Dropping the price.

**Comment by hungvu193** [comment] 2024-11-28 08:43
Thanks @huult, I don't think your RCA is correct. I can reproduce this issue on iPhone SE, even when the maxHeight is bigger than actual height. Apply your diff also didn't the bug btw.

<img width="1047" alt="Screenshot 2024-11-28 at 15 43 41" src="https://github.com/user-attachments/assets/31a3544c-3aad-4379-8227-8b5bcb27aa22">

**Comment by huult** [comment] 2024-11-28 16:01
## [Proposal updated](https://github.com/Expensify/App/issues/53218#issuecomment-2504292030)

- Add new RCA
- Add new solution
- Add poc on iPhone SE

@hungvu193 Sorry, I've updated the RCA and solution. Can you help me check it again?

**Comment by trjExpensify** [comment] 2024-12-06 13:34
@hungvu193 thoughts on the proposal?

**Comment by hungvu193** [comment] 2024-12-06 13:36
I'll rereview this weekend

**Comment by hungvu193** [comment] 2024-12-09 04:25
Thanks @huult 's [proposal here](https://github.com/Expensify/App/issues/53218#issuecomment-2504292030) looks good and tests well!

🎀 👀 🎀

**Comment by huult** [comment] 2024-12-13 18:22
I tried to revert my pull request, but the crash issue still occurred. I think it’s not related to this ticket.

https://github.com/user-attachments/assets/f0d9a0d7-a411-493b-92c9-7ad57d5ba522

**Comment by trjExpensify** [comment] 2024-12-19 12:07
👋 @hungvu193 let's get the checklist for tomorrow!

**Comment by hungvu193** [comment] 2024-12-20 04:00
# BugZero Checklist:

- [ ] **[Contributor]** Classify the bug:

<details>
<summary>Bug classification</summary>


Source of bug:
  - [ ] 1a. Result of the original design (eg. a case wasn't considered)
  - [ ] 1b. Mistake during implementation
  - [ ] 1c. Backend bug
  - [ ] 1z. Other:

Where bug was reported:
  - [ ] 2a. Reported on production (eg. bug slipped through the normal regression and PR testing process on staging)
  - [ ] 2b. Reported on staging (eg. found during regression or PR testing)
  - [ ] 2d. Reported on a PR
  - [ ] 2z. Other:

Who reported the bug:
  - [ ] 3a. Expensify user
  - [ ] 3b. Expensify employee
  - [ ] 3c. Contributor
  - [ ] 3d. QA
  - [ ] 3z. Other:

</details>

- [ ] **[Contributor]** The offending PR has been commented on, pointing out the bug it caused and why, so the author and reviewers can learn from the mistake.

    Link to comment:

- [ ] **[Contributor]** If the regression was CRITICAL (e.g. interrupts a core flow) A discussion in [#expensify-open-source](https://app.slack.com/client/E047TPA624F/C01GTK53T8Q) has been started about whether any other steps should be taken (e.g. updating the PR review checklist) in order to catch this type of bug sooner.

    Link to discussion:

- [ ] **[Contributor]** If it was decided to create a regression test for the bug, please propose the [regression test](https://github.com/Expensify/App/blob/main/contributingGuides/REGRESSION_TEST_BEST_PRACTICES.md) steps using the template below to ensure the same bug will not reach production again.

<details>
<summary>Regression Test Proposal Template</summary>


- [ ] **[BugZero Assignee]** Create a GH issue for creating/updating the regression test once above steps have been agreed upon.

    Link to issue:

## Regression Test Proposal
### Precondition:


-

### Test:


1.

Do we agree 👍 or 👎


</details>

**Comment by trjExpensify** [comment] 2024-12-20 12:26
Thanks! This was caught with [this existing regression test](https://expensify.testrail.io/index.php?/cases/view/2654739) for the emoji picker, so I think we're good on a standalone test. 

Payment summary as follows:

- $125 to @hungvu193 for the c+ review (go ahead and request!)
- $125 to @huult for the PR 

Paid, closing!

**Closed by trjExpensify** 2024-12-20 12:26 UTC
Labels: External, Daily, Awaiting Payment, Bug

**Comment by garrettmknight** [comment] 2025-01-07 18:32
$250 approved for @hungvu193
