### ISSUE TITLE
[$500] Edit private note form doesn't submit by enter key

### ISSUE THREAD

**Issue by m-natarajan** [Expensify/App#28860] opened 2023-10-04 20:31 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Open a report that has the private note option
2. Click on the header > Private notes
3. Select a private note to open the edit page
4. Edit the private note and press enter key
## Expected Result: 
The private note should be saved and go back to the previous page
## Actual Result: 
The input adds a new line

## Workaround:
unknown 
## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [x] MacOS / Chrome / Safari
- [x] MacOS / Desktop

**Version Number:** 1.3.77-5
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/38435837/b1d8e259-db93-4d60-b4f3-6a9023667312

https://github.com/Expensify/App/assets/38435837/b5062afb-b3d6-4a58-a5f8-8dfacdb595af

https://github.com/Expensify/App/assets/38435837/5e238552-2eea-41a2-9fc7-3261d4e5faff

**Expensify/Expensify Issue URL:**
**Issue reported by:** @dukenv0307
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1696405348401729

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01114e9ac4dbe61472</li>
        <li>Upwork Job ID: 1709667574583115776</li>
        <li>Last Price Increase: 2023-10-11</li>
    </ul>
</details>

**Comment by m-natarajan** [comment] 2023-10-04 20:32
## Proposal by @dukenv0307 
### Please re-state the problem that we are trying to solve in this issue.
Edit private note form doesn't submit by pressing enter key
### What is the root cause of that problem?
We don't add `submitOnEnter` prop to allow the submission of the form by pressing the enter key
https://github.com/Expensify/App/blob/447d87e9204578ccaf5c8e3a6887b97de531457e/src/pages/PrivateNotes/PrivateNotesEditPage.js#L142
We should add `submitOnEnter` prop to the text input to make the form can be submitted by pressing enter key
https://github.com/Expensify/App/blob/447d87e9204578ccaf5c8e3a6887b97de531457e/src/pages/PrivateNotes/PrivateNotesEditPage.js#L142
### What alternative solutions did you explore? (Optional)
NA
### Result
[Screencast from 04-10-2023 15:19:04.webm](https://github.com/Expensify/App/assets/129500732/ac9fe34c-20b3-4b53-b3e5-7f16369149f3)

**Comment by alitoshmatov** [comment] 2023-10-04 21:11
Looks like it is intended behavior. Since notes might be multiline

**Comment by ayazalavi** [comment] 2023-10-05 01:08
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
Enter button is not submitting privates notes form.

### What is the root cause of that problem?
Root cause of the problem is we have policy about when form should be submitted on pressing enter and when we should add a new line on pressing shift+enter. There is prop for multiline inputs that allow us to handle form like this

https://github.com/Expensify/App/blob/6d86d5aecc47096bffdfbf59dcaefcb5dd0a0509/src/components/TextInput/baseTextInputPropTypes.js#L89

it is not added

### What changes do you think we should make in order to solve the problem?
Add **`submitOnEnter={!Browser.isMobile()}`** prop here 

https://github.com/Expensify/App/blob/6d86d5aecc47096bffdfbf59dcaefcb5dd0a0509/src/pages/PrivateNotes/PrivateNotesEditPage.js#L142

Above change will ensure that enter behavior gets updated for desktop browsers and for mobile apps only.

### What alternative solutions did you explore? (Optional)
N/A

**Comment by cubuspl42** [comment] 2023-10-05 09:12
@ayazalavi Does it do any harm to add `submitOnEnter` for mobile browsers too? Don't we support a rare but possible scenario like an Android phone/tablet with a Bluetooth hardware keyboard + mobile Chrome?

**Comment by cubuspl42** [comment] 2023-10-05 09:27
[I asked also on Slack](https://expensify.slack.com/archives/C01GTK53T8Q/p1696497981826819)

**Comment by ayazalavi** [comment] 2023-10-05 09:28
@cubuspl42, I believe this form submission behavior is intended for platforms other than mobile browsers. Mobile browsers have different form submission behavior due to the lack of implementation for interactions between soft keyboards and HTML forms in the app. Please take a look at this issue for more information: [Link to Issue #28569](https://github.com/Expensify/App/issues/28569).

**Comment by puneetlath** [comment] 2023-10-13 16:21
I agree with @cubuspl42 and I believe this page is being revamped anyways, so let's close this for now.

**Closed by puneetlath** 2023-10-13 16:21 UTC
Labels: External, Daily, Help Wanted, Overdue, Bug
