### ISSUE TITLE
[HOLD for payment 2023-06-30] [$1000] App crashes on pasting the public room URL again after navigating back

### ISSUE THREAD

**Issue by kavimuru** [Expensify/App#20825] opened 2023-06-15 13:42 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Go to staging dot on web chrome
2. Create a public room
3.Send a message in the room (important step)
4. Copy the URL of the room and paste it in a new incognito window (without signing in)
5. Click on reply thread icon of the message and notice that it navigates you to the sign in window.
6. Now click on back button for the browser and see that a empty window page is seen. Now again paste the URL and hit enter
7. Result: See that the app crashes

## Expected Result: 
App should not crash on pasting the public room URL again after navigating back
## Actual Result: 
App crashes on pasting the public room URL again after navigating back

## Workaround:
Can the user still use Expensify without this being fixed? Have you informed them of the workaround?

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [x] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 1.3.28-3
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/43996225/b90d865d-b50f-4863-a0b1-1b6c7589c0ef

https://github.com/Expensify/App/assets/43996225/228cf161-6175-4aac-89da-419fbfa444d8

**Expensify/Expensify Issue URL:**
**Issue reported by:** @avi-shek-jha
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1686715971306539

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~0127842e1a6b2e7f94</li>
        <li>Upwork Job ID: 1669713173384228864</li>
        <li>Last Price Increase: 2023-06-16</li>
    </ul>
</details>

**Comment by daordonez11** [comment] 2023-06-15 19:53
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
Web app crashes when user inputs again the URL after going back from sign in page
### What is the root cause of that problem?
After opening the second time the React Navigation library returns an undefined state, which is sent to `updateSavedNavigationStateAndLogRoute`
### What changes do you think we should make in order to solve the problem?
Instead of having guards in the children methods I recommend having the guard in the parent NavigationRoot.js:
```javascript
const updateSavedNavigationStateAndLogRoute = (state) => {
        if (!state) {
            return
        }
        navigationStateRef.current = state;
        props.updateCurrentReportId(state);
        parseAndLogRoute(state);
    };
```

Video of the solution working:
[Mobile Browser - 14_6_2023, 14_55_36.webm](https://github.com/Expensify/App/assets/13544910/ba396d63-a7b7-4a2a-b6dd-b9c65ee77674)
[New Recording - 14_6_2023, 14_54_41.webm](https://github.com/Expensify/App/assets/13544910/cfb30cdd-61a3-4a9e-ba57-19ccb0d469cb)

### What alternative solutions did you explore? (Optional)
I began trying a guard in getTopmostReportId but diving into the origin of the issue it is better to use it in the parent in  case any additional method is used in updateSavedNavigationStateAndLogRoute 
We can also validate with Software Mansion and check if the behavior of receiving and undefined state from the library is correct.

**Comment by sonialiap** [comment] 2023-06-16 14:26
Reproducible. Moving to external

Thanks @daordonez11, I'm going to let the C+ review the proposals 👍

**Comment by sonialiap** [comment] 2023-06-16 14:29
@mollfpr there was some discussion in slack that may influence how you think we should handle this - [thread](https://expensify.slack.com/archives/C049HHMV9SM/p1686715971306539)

**Comment by daordonez11** [comment] 2023-06-16 14:36
Indeed it might @mountiny , yet there might be other scenarios where state is undefined that we don't know yet, and since #20558 was on hold I created a solution specific to avoid the app crash. Since react navigator returns de hydratedState I'm not sure if other scenario could trigger it. Still having the guard in `updateSavedNavigationStateAndLogRoute ` might be safer for the future

**Comment by mountiny** [comment] 2023-06-19 08:20
Assigning this once since its navigation related.

**Comment by mountiny** [comment] 2023-06-19 11:18
@hungvu193 thanks for your proposal, but i think @daordonez11 solution is more broad/ general and can cover more cases of this error, so I am going with his proposal.

**Comment by daordonez11** [comment] 2023-06-19 18:51
@mountiny I already have a draft PR with both guards. Do you want me to keep them both? Or only have  `updateSavedNavigationStateAndLogRoute`. I will do some tests but I can have the PR ready for check by today EOD

**Comment by mountiny** [comment] 2023-06-19 20:17
@daordonez11 We can discuss this in the PR, sorry I think have got a bit lost in the issues so I am not sure what two guards you are referring it. Lets use whichever will solve more problems we have or will be more general solution.

**Comment by daordonez11** [comment] 2023-06-19 21:42
Hey there @mountiny PR Ready: https://github.com/Expensify/App/pull/20772

**Comment by mountiny** [comment] 2023-06-20 17:41
Thanks!

**Comment by mountiny** [comment] 2023-06-21 10:33
@daordonez11 congrats on your first merged PR 🎉

**Comment by daordonez11** [comment] 2023-06-21 11:54
Thanks @mountiny 💪🏼 first step on my way to C+ and help building expensify

**Comment by mollfpr** [comment] 2023-06-29 03:06
> [@mollfpr] The PR that introduced the bug has been identified. Link to the PR:

https://github.com/Expensify/App/pull/16581

> [@mollfpr] The offending PR has been commented on, pointing out the bug it caused and why, so the author and reviewers can learn from the mistake. Link to comment:

https://github.com/Expensify/App/pull/16581/files#r1246040157

> [@mollfpr] A discussion in #expensify-bugs has been started about whether any other steps should be taken (e.g. updating the PR review checklist) in order to catch this type of bug sooner. Link to discussion:

This is a regression for our navigation reboot, so the regression step should be enough.

> [@mollfpr] Determine if we should create a regression test for this bug.
[@mollfpr] If we decide to create a [regression test](https://github.com/Expensify/App/blob/main/contributingGuides/REGRESSION_TEST_BEST_PRACTICES.md) for the bug, please propose the regression test steps to ensure the same bug will not reach production again.

1. Go to staging dot on web chrome
2. Create a public room
3. Send a message in the room (important step)
4. Copy the URL of the room and paste it into a new incognito window (without signing in)
5. Click on the reply thread icon of the message and notice that it navigates you to the sign-in window.
6. Now click on the back button for the browser and see that an empty window page is seen. Now again, paste the URL and hit enter
7. **Verify** the app is not crash
8. 👍 or 👎

**Comment by sonialiap** [comment] 2023-07-03 13:31
Timeline:
June 14 9:57pm opened
June 21 12:27pm merged
Days: about 3.5
No merge bonus

**Comment by sonialiap** [comment] 2023-07-03 13:40
@avi-shek-jha offer sent for report
@daordonez11 offer sent for fix
@mollfpr offer sent for review

**Comment by daordonez11** [comment] 2023-07-03 13:51
Hey @sonialiap isn't urgency bonus based assignation? I was assigned on Wednesday 19 and merged by Friday 21 it took only 2 business days. I think it does apply in this case.

**Comment by mountiny** [comment] 2023-07-04 14:28
@sonialiap the bonus should apply here, would you be able to update the contracts please? thanks!

**Comment by sonialiap** [comment] 2023-07-05 15:05
Thanks for the correction. The bonus is applied on top of the contract so no need to amend them. Issuing payment with the bonus now ⏳ 💰

**Comment by sonialiap** [comment] 2023-07-05 15:07
@daordonez11 please accept the offer. Bonus is applied during payment after the offer has been accepted :)

**Closed** 2023-07-05 17:12 UTC
Labels: External, Daily, Awaiting Payment, Bug
