### ISSUE TITLE
[$500] Workspace - Incorrect primary login displayed after merge with other account

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#32127] opened 2023-11-28 14:33 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.4.0
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** Applause - Internal Team
**Slack conversation:**

## Action Performed:
Precondition: all accounts should be expensifail
1. Log in as Account A and create a workspace
2. Create a Workspace
3. Invite other existing accounts B and C to the workspace
4. Send some messages in the #Announce room and in the workspace chat for the 2 users you have access to
5. Remove the account C from the workspace
6. Navigate to OldDot and Log in with account B
7. Merge the account B with the account C (that was just removed from the workspace)
8. Navigate back to the new expensifail app and Log In with account B
9. Tap on Search Icon and write the created workspace name in step 2 e.g. "Workspace 28"
10. Tap on the archived workspace
11. Repeat step 9-10

## Expected Result:
Primary login should be displayed in header, search page and conversation

## Actual Result:
Incorrect primary login displayed [MERGED_0@applausetester+omd60@applause.expensifail.com](mailto:MERGED_0@applausetester+omd60@applause.expensifail.com)

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [x] Android: mWeb Chrome
- [x] iOS: Native
- [x] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

https://github.com/Expensify/App/assets/93399543/520adc13-8cb7-44ea-9a76-f41a60fdb4d7

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~0145c4b7f08b9c57c0</li>
        <li>Upwork Job ID: 1729508760867057664</li>
        <li>Last Price Increase: 2023-11-28</li>
<li>Automatic offers: </li>
<ul>
<li>paultsimura | Contributor | 28016143</li>
</ul></li>
    </ul>
</details>

**Comment by paultsimura** [comment] 2023-11-28 23:15
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
After merging accounts, the login with "MERGED_0" prefix is displayed in multiple places.

### What is the root cause of that problem?
This happens because after merging accounts, the other one's login gets a "MERGED_0" prefix prepended, and we do not handle this in many places as we do here:

https://github.com/Expensify/App/blob/eece94181783429ae41256a86652b70221f26bc3/src/pages/home/report/ReportActionItemSingle.js#L86

### What changes do you think we should make in order to solve the problem?
We should update the corresponding places to use `.replace(CONST.REGEX.MERGED_ACCOUNT_PREFIX, '')`.




### What alternative solutions did you explore? (Optional)

**Comment by allroundexperts** [comment] 2023-12-01 01:52
@paultsimura's [proposal](https://github.com/Expensify/App/issues/32127#issuecomment-1830908739) has the correct RCA and the solution looks good to me as well. Let's go with them!

🎀 👀 🎀 C+ reviewed

**Comment by conorpendergrast** [comment] 2023-12-05 14:42
@roryabraham waiting on your review [of the proposal](https://github.com/Expensify/App/issues/32127#issuecomment-1830908739), please!

**Comment by roryabraham** [comment] 2023-12-09 02:21
Proposal looks good, and I like the ideas of consolidating this into `PersonalDetailsUtils.getDisplayNameOrDefault` 👍🏼

**Comment by conorpendergrast** [comment] 2023-12-11 12:02
Looks like the PR has just been started here!

**Comment by paultsimura** [comment] 2023-12-11 15:32
Thanks. The PR is ready for review: https://github.com/Expensify/App/pull/32792

**Comment by roryabraham** [comment] 2024-01-03 23:13
Uh oh, let's move this back to weekly. The [PR](https://github.com/Expensify/App/pull/32792) was merged yesterday

**Comment by paultsimura** [comment] 2024-01-09 12:36
The PR was deployed to prod, automation here didn't work: https://github.com/Expensify/App/pull/32792#issuecomment-1882428901

**Comment by paultsimura** [comment] 2024-01-16 08:53
@conorpendergrast this is due payment today.
The automation didn't work on deployment: https://github.com/Expensify/App/pull/32792#issuecomment-1882428901

**Comment by conorpendergrast** [comment] 2024-01-16 09:05
@paultsimura Thanks for flagging that! Moving to daily to pay today

**Comment by conorpendergrast** [comment] 2024-01-16 13:36
Payouts:

- [x] Contributor: $500 @paultsimura - [contract](https://www.upwork.com/nx/wm/offer/28016143)
- Contributor+: $500 @allroundexperts via manual request

Upwork job is [here](https://www.upwork.com/jobs/~0145c4b7f08b9c57c0).

**Comment by conorpendergrast** [comment] 2024-01-16 13:40
Manually posting this as Melvin didn't do it: 

**BugZero Checklist:** The PR fixing this issue has been merged! The following checklist ([instructions](https://stackoverflow.com/c/expensify/questions/14574)) will need to be completed before the issue can be closed:

- [ ] [@allroundexperts] The PR that introduced the bug has been identified. Link to the PR:
- [ ] [@allroundexperts] The offending PR has been commented on, pointing out the bug it caused and why, so the author and reviewers can learn from the mistake. Link to comment:
- [ ] [@allroundexperts] A discussion in #expensify-bugs has been started about whether any other steps should be taken (e.g. updating the PR review checklist) in order to catch this type of bug sooner. Link to discussion:
- [ ] [@allroundexperts] Determine if we should create a regression test for this bug.
- [ ] [@allroundexperts] If we decide to create a regression test for the bug, please propose the [regression test](https://github.com/Expensify/App/blob/main/contributingGuides/REGRESSION_TEST_BEST_PRACTICES.md) steps to ensure the same bug will not reach production again.
- [ ] [@conorpendergrast] Link the GH issue for creating/updating the regression test once above steps have been agreed upon:

**Comment by conorpendergrast** [comment] 2024-01-19 15:06
@allroundexperts Bump on the C+ checklist please!

**Comment by allroundexperts** [comment] 2024-01-21 22:54
## Checklist
1. https://github.com/Expensify/App/pull/14779
2. https://github.com/Expensify/App/pull/14779/files#r1461189881
3. N/A
4. A regression test would be helpful here. The test steps given in the OP look good to me and can be used to create the regression test.

**Comment by conorpendergrast** [comment] 2024-01-22 10:28
Sounds good! QA test request created: https://github.com/Expensify/Expensify/issues/362457

That's all folks, thanks!

**Closed by conorpendergrast** 2024-01-22 10:28 UTC
Labels: External, Daily, Awaiting Payment, Bug

**Comment by JmillsExpensify** [comment] 2024-01-30 22:14
$500 approved for @allroundexperts based on [this comment](https://github.com/Expensify/App/issues/32127#issuecomment-1893758047).
