### ISSUE TITLE
Onboarding - Video is not dismissed after refreshing the page

### ISSUE THREAD

**Issue by izarutskaya** [Expensify/App#39920] opened 2024-04-09 12:00 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.61-0
**Reproducible in staging?:** Y
**Reproducible in production?:** N
**Found when validating PR :** https://github.com/Expensify/App/pull/37733
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Issue reported by:** 

## Action Performed:
1. Go to staging.new.expensify.com/onboarding.
2. Enter name > Next.
3. Select an option > Next.
4. When the video is playing, refresh the page.

## Expected Result:
On page refresh the onboarding video disappears, even if user did not close it explicitly (PR step 18).

## Actual Result:
After refreshing the page, the onboarding video does not disappear.

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [x] Android: mWeb Chrome
- [ ] iOS: Native
- [x] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

https://github.com/Expensify/App/assets/115492554/ac5a169f-8160-48ad-971d-5a20b38aa1f4

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by izarutskaya** [comment] 2024-04-09 12:01
@kadiealexander I haven't added the External label as I wasn't 100% sure about this issue. Please take a look and add the label if you agree it's a bug and can be handled by external contributors.

**Comment by izarutskaya** [comment] 2024-04-09 12:01
We think this issue might be related to the #collect project.

**Comment by mountiny** [comment] 2024-04-09 14:18
Not a blocker as this is not accessible for the new users, I am helping with this project now so taking over

**Comment by Julesssss** [comment] 2024-04-09 14:22
Excellent 👍

**Comment by cdOut** [comment] 2024-04-09 14:36
Hi, I'm Tymoteusz from Software Mansion, the expert agency, and I will work on this issue.

**Comment by cdOut** [comment] 2024-04-11 10:03
> I reported this bug during PR review, and it appears that we changed behavior here [#37733 (comment)](https://github.com/Expensify/App/pull/37733#issuecomment-1995484889)

@shawnborton Is this still the way we want to go forward with this one? If yes then we can close this issue and if we want to go back to the previous implementation then I have a solution ready to be pushed.

**Comment by shawnborton** [comment] 2024-04-11 10:07
Yeah, I thought we decided that refreshing the page is the same as accessing the current page URL, and if the current page url is for showing a video, then it makes sense that refreshing would show the video again. Maybe I am missing something though? Cc @Expensify/design for a gut check, but seems like we can close this one.

**Comment by dannymcclain** [comment] 2024-04-11 14:43
> Yeah, I thought we decided that refreshing the page is the same as accessing the current page URL, and if the current page url is for showing a video, then it makes sense that refreshing would show the video again. Maybe I am missing something though? Cc @Expensify/design for a gut check, but seems like we can close this one.

Totally agree. I remember us deciding this in Slack. This looks like expected behavior to me and I think we can close.

**Comment by dubielzyk-expensify** [comment] 2024-04-11 23:37
I'm aligned with that. We also wanted the potential ability to link to this video which is why this is good as is. 

Worth noting that even if people land on this video after having just seen it, there's no real damage in that :)

**Comment by kadiealexander** [comment] 2024-04-12 04:39
Agree with everyone here, closing the issue!

**Closed by kadiealexander** 2024-04-12 04:39 UTC
Labels: Engineering, Daily, Bug
