### ISSUE TITLE
[HOLD for payment 2024-10-25] Debug Mode - "Has RBR" is not shown for report that has RBR in LHN

### ISSUE THREAD

**Issue by IuliiaHerets** [Expensify/App#50403] opened 2024-10-08 12:17 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** v9.0.46-1
**Reproducible in staging?:** Y
**Reproducible in production?:** Unable to check Prod. There is no debug option in prod
**Issue was found when executing this PR:** https://github.com/Expensify/App/pull/48442
**Email or phone of affected tester (no customers):** applausetester+ds@applause.expensifail.com
**Issue reported by:** Applause Internal Team

## Action Performed:
1. Enable "Debug mode" in troubleshoot
2. On home page, open a chat report from LHN that has a RBR
3. Click on the header of the chat you just opened, then click on Debug

## Expected Result:
On the Details tab, "Has RBR" is shown in "Visible in LHN" for report that has RBR in LHN

## Actual Result:
On the Details tab, "Has GBR" is shown instead of "Has RBR" in "Visible in LHN" for report that has RBR in LHN. For reports that has GBR "has GBR" is shown.

## Workaround:
Unknown

## Platforms:

- [ ] Android: Native
- [x] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

https://github.com/user-attachments/assets/69c47d39-1eeb-4181-863a-0cbeab91a13c

 
</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Issue Owner</summary>Current Issue Owner: @adelekennedy</details>

**Comment by mountiny** [comment] 2024-10-08 12:50
No need to be a deploy blocker because this feature is a troubleshooting tool

**Comment by mountiny** [comment] 2024-10-08 12:52
@pac-guerreiro @DylanDylann Can you have a look please?

**Comment by pac-guerreiro** [comment] 2024-10-08 13:10
@IuliiaHerets thanks for the bug report!

I missed the translation for hasRBR 😅 I'll add it and open a PR to fix this in the next hour or so 😄

**Comment by pac-guerreiro** [comment] 2024-10-17 12:04
@mountiny 

I made a mistake while resolving merge conflicts so this issue still persists. Is it okay if I resolve it here - https://github.com/Expensify/App/pull/50831 ?

**Comment by DylanDylann** [comment] 2024-10-18 08:08
@pac-guerreiro What is the mistake that you mentioned above?

**Comment by pac-guerreiro** [comment] 2024-10-18 08:20
@DylanDylann 

Nevermind, I got the merge conflict on https://github.com/Expensify/App/pull/50831 and had to change the logic a bit for this fix to work there! I just thought that I had missed something on this issue during the final rebase with main, but that's not the case!

**Comment by adelekennedy** [comment] 2024-10-28 03:58
Payouts due:

- [ ] Reviewer: $250 @DylanDylann [Offer sent!](https://www.upwork.com/nx/wm/offer/104621051)

**Comment by adelekennedy** [comment] 2024-10-30 03:24
@DylanDylann bump also on the checklist

**Comment by DylanDylann** [comment] 2024-10-30 03:28
BugZero Checklist: The PR fixing this issue has been merged! The following checklist ([instructions](https://stackoverflow.com/c/expensify/questions/14574)) will need to be completed before the issue can be closed:

 [@DylanDylann] The PR that introduced the bug has been identified. Link to the PR: https://github.com/Expensify/App/pull/48442
 [@DylanDylann] The offending PR has been commented on, pointing out the bug it caused and why, so the author and reviewers can learn from the mistake. Link to comment: Just discussed with the author
 [@DylanDylann] A discussion in #expensify-bugs has been started about whether any other steps should be taken (e.g. updating the PR review checklist) in order to catch this type of bug sooner. Link to discussion: **NA**
 [@DylanDylann] Determine if we should create a regression test for this bug. **Yes**
 [@DylanDylann] If we decide to create a [regression test](https://github.com/Expensify/App/blob/main/contributingGuides/REGRESSION_TEST_BEST_PRACTICES.md) for the bug, please propose the regression test steps to ensure the same bug will not reach production again.


Regression Test Proposal

1. Enable Debug mode in troubleshoot
2. On home page, open a chat report from LHN that has a RBR
3. Click on the header of the chat you just opened, then click on Debug
4. On the Details tab, Has RBR is shown in Visible in LHN for report that has RBR in LHN

Do we agree 👍 or 👎

**Closed** 2024-11-06 21:45 UTC
Labels: Engineering, Daily, Overdue, Awaiting Payment, Bug
