### ISSUE TITLE
Report stuck in a loop

### ISSUE THREAD

**Issue by garrettmknight** [Expensify/App#51945] opened 2024-11-04 10:58 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Slack conversation:** https://expensify.slack.com/archives/C06ML6X0W9L/p1730394986131059

## Action Performed:

1. Andrew approves the report forwards to Garrett
2. Garrett tries to approve the report in ND, error
3. Garrett tries to approve the report in OD, can only approve and forward

## Expected Result:
Report should have been final approved by Garrett

## Actual Result:
Report is reassigned to Andrew for further approval?

## Workaround:
None, we're in an endless loop.

## Platforms:
All

## Screenshots/Videos

A bunch of data is in the slack thread.

**Comment by marcochavezf** [comment] 2024-11-05 03:19
Today I prioritized a deploy blocker and a #stability issue, tomorrow I will prioritize this one

**Comment by marcochavezf** [comment] 2024-11-06 02:00
I'm still investigating, I created a PR with an automated to try to reproduce the bug locally https://github.com/Expensify/Auth/pull/13052

**Comment by marcochavezf** [comment] 2024-11-06 23:42
[PR](https://github.com/Expensify/Auth/pull/13052) in review

**Comment by greg-schroeder** [comment] 2024-11-11 20:31
Linked PR merged -> deployed

**Comment by greg-schroeder** [comment] 2024-11-11 20:32
Looks like this done! Closing, but please reopen if there's more to be done that I'm missing.

**Closed by greg-schroeder** 2024-11-11 20:32 UTC
Labels: Reviewing, Weekly, Internal, Bug
