### ISSUE TITLE
[HOLD for payment 2023-09-20] [$500] Web -  Inconsistency - Magic Code Max Limit Reached error Message has extra margin top

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#26911] opened 2023-09-06 20:55 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Sign out from app
2. Try to log in with a account with. which Max limit for Magic code sent is reached

## Expected Result:
 "Max limit for Magic code sent is reached" Error message has consistent margin top as other error messages

## Actual Result:
Magic Code Max Limit Reached error Message has extra margin top

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [x] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 1.3.64.2
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/93399543/5757447a-c122-4b98-af06-3e2c4ae6f06b

https://github.com/Expensify/App/assets/93399543/5631ee0f-3d9b-4164-a4e9-aaa6decc93ab

**Expensify/Expensify Issue URL:**
**Issue reported by:** @ishpaul777
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1693638585825509

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~016c12eafb3388a3e0</li>
        <li>Upwork Job ID: 1699540582657310720</li>
        <li>Last Price Increase: 2023-09-06</li>
<li>Automatic offers: </li>
<ul>
<li>ishpaul777 | Reporter | 26535445</li>
</ul></li>
    </ul>
</details>

**Comment by ahmedGaber93** [comment] 2023-09-06 20:55
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
 Inconsistency - Magic Code Max Limit Reached error Message has extra margin top
### What is the root cause of that problem?
The two errors are not displayed in the same place, and every place has different margin.
The Max Limit Reached error is displayed here and have `styles.mt5`.
https://github.com/Expensify/App/blob/9701fbe5ec24bf5031da390075b2a9fb125b3ce3/src/pages/signin/LoginForm/BaseLoginForm.js#L238

The invalid email error is displayed here and have `styles.mt2`
https://github.com/Expensify/App/blob/9701fbe5ec24bf5031da390075b2a9fb125b3ce3/src/pages/signin/LoginForm/BaseLoginForm.js#L215
### What changes do you think we should make in order to solve the problem?
We need to apply the same margin `styles.mt2` in the two places.
1. change `styles.mt5` to `styles.mt2` here
https://github.com/Expensify/App/blob/9701fbe5ec24bf5031da390075b2a9fb125b3ce3/src/pages/signin/LoginForm/BaseLoginForm.js#L233
2. The style `styles.mt2` will fix the error margin top, but also will decrease the Button margin top because it's applied to the wrapped View, so we need to fix the Button margin top by adding extra `styles.mt3`.
For that we will add new prop `buttonStyle` in FormAlertWithSubmitButton.js and use it [here](https://github.com/Expensify/App/blob/9701fbe5ec24bf5031da390075b2a9fb125b3ce3/src/components/FormAlertWithSubmitButton.js#L82) and [here](https://github.com/Expensify/App/blob/9701fbe5ec24bf5031da390075b2a9fb125b3ce3/src/components/FormAlertWithSubmitButton.js#L90) and pass it with `styles.mt3`


### What alternative solutions did you explore? (Optional)
we can instead show the same error in the same place `errorText={formErrorText || serverErrorText}` here
https://github.com/Expensify/App/blob/9701fbe5ec24bf5031da390075b2a9fb125b3ce3/src/pages/signin/LoginForm/BaseLoginForm.js#L215

**Comment by kbecciv** [comment] 2023-09-06 20:56
Proposal by: @ishpaul777
Slack conversation: https://expensify.slack.com/archives/C049HHMV9SM/p1693638585825509

## Proposal
###  Problem
Error Message from server has extra margin top than other error messages

### Root Cause
The server error is shown as part of [FormAlertWithSubmitButton] while the general validation is shown with [TextInput](https://github.com/Expensify/App/blob/main/src/pages/signin/LoginForm/BaseLoginForm.js#L215C1-L216C1) Margin of [Parent View](https://github.com/Expensify/App/blob/main/src/pages/signin/LoginForm/BaseLoginForm.js#L233C1-L234C1) is applied to error message

### Changes
Conditionally applying padding to [Parent View](https://github.com/Expensify/App/blob/main/src/pages/signin/LoginForm/BaseLoginForm.js#L233C1-L234C1) will solve the issue.

```
<View style={[_.isEmpty(serverErrorText) ? styles.mt5 : {}]}>
```

**Comment by ishpaul777** [comment] 2023-09-06 21:55
HII @lschurr, @burczu is OOO for 2 days -  https://github.com/Expensify/App/issues/24497#issuecomment-1708326890

**Comment by lschurr** [comment] 2023-09-06 22:03
Great! Assigning to you @allroundexperts

**Comment by ishpaul777** [comment] 2023-09-06 22:12
> Conditionally applying ~~padding~~ to Parent View will solve the issue.

A small correction for my proposed changes - padding🚫 margin✅

**Comment by ishpaul777** [comment] 2023-09-06 22:39
one more change with proposal

function FormAlertWithSubmitButton(props) {
    const buttonMarginStyle = [_.isEmpty(props.footerContent) ? {} : styles.mb3, _.isEmpty(props.message) ? {} : styles.mt3];

**Comment by ishpaul777** [comment] 2023-09-06 22:47
## Proposal
### Problem
Error Message from server has extra margin top than other error messages

### Root Cause
The server error is shown as part of [FormAlertWithSubmitButton] while the general validation is shown with [TextInput](https://github.com/Expensify/App/blob/main/src/pages/signin/LoginForm/BaseLoginForm.js#L215C1-L216C1) Margin of [Parent View](https://github.com/Expensify/App/blob/main/src/pages/signin/LoginForm/BaseLoginForm.js#L233C1-L234C1) is applied to error message

### Changes
Conditionally applying margin to [Parent View](https://github.com/Expensify/App/blob/main/src/pages/signin/LoginForm/BaseLoginForm.js#L233C1-L234C1) will solve the issue.
```
<View style={[_.isEmpty(serverErrorText) ? styles.mt5 : {}]}>
```

error text already has a margin bottom of 12px, we will add a margin top of 8px to  buttonMarginStyle in [FormAlertWithSubmitButton]()
```jsx
    const buttonMarginStyle = [_.isEmpty(props.footerContent) ? {} : styles.mb3, _.isEmpty(props.message) ? {} : styles.mt2];
```

**Comment by RaheesAhmed** [comment] 2023-09-07 02:55
Sorry i have written the wrong Issue thats why i removed the pyll request

**Comment by RaheesAhmed** [comment] 2023-09-07 02:58
Contributor details
Your Expensify account email: allandriodtricks@gmail.com
Upwork Profile Link: https://www.upwork.com/freelancers/~01d7b5ac3b1f1b3985

**Comment by RaheesAhmed** [comment] 2023-09-07 04:03
Proposal for Magic Code Max Limit Reached error Message has extra margin top fixes #26922 

**Please re-state the problem that we are trying to solve in this issue.**
The problem is related to inconsistent margin-top values for different error messages in the Expensify App. Specifically, the "Max Limit Reached" error message has a different margin-top (styles.mt5) compared to other error messages like "Invalid email," which uses styles.mt2.

**What is the root cause of that problem?**
The root cause of the problem is the inconsistent usage of margin-top styles in the BaseLoginForm.js file. The "Max Limit Reached" error message is styled with styles.mt5, while other error messages use styles.mt2.

**What changes do you think we should make in order to solve the problem?**
To solve the problem, the margin-top style for the "Max Limit Reached" error message should be changed from styles.mt5 to styles.mt2 in the BaseLoginForm.js file. This will make it consistent with other error messages.

**What alternative solutions did you explore? (Optional)**
An alternative solution could be to introduce a new prop in FormAlertWithSubmitButton.js that allows for dynamic styling of the error messages. However, this might be an over-engineered solution for a simple styling issue.

**Comment by RPSanchez** [comment] 2023-09-07 05:05
@RaheesAhmed 
https://github.com/Expensify/App/blob/46e6e202029924025148f6db6be2b378fd3e96e9/contributingGuides/PROPOSAL_TEMPLATE.md?plain=1#L12

**Comment by ishpaul777** [comment] 2023-09-07 11:19
@allroundexperts  please Correct me if i am wrong, according to selected propsal, I think there is still inconsistency
- genral validation error has margin top of 8px. when error shows error has 8px of margin top.
- server error has margin top of 8px, 8px added to Parent View. when server error shows margin top 8+8= 16 px

<img width="1822" alt="Screenshot 2023-09-07 at 4 47 05 PM" src="https://github.com/Expensify/App/assets/104348397/11d023e2-d08b-4cef-9ab0-5e39c28c130b">

<img width="1822" alt="Screenshot 2023-09-07 at 4 47 16 PM" src="https://github.com/Expensify/App/assets/104348397/37bd835c-8338-4933-a713-4cf35c10c2cb">

**Comment by ishpaul777** [comment] 2023-09-07 14:11
have you implemented all changes from https://github.com/Expensify/App/issues/26911#issuecomment-1709104494.

**Comment by ishpaul777** [comment] 2023-09-07 14:14
bith have different margin bottom

<img width="394" alt="Screenshot 2023-09-07 at 7 39 25 PM" src="https://github.com/Expensify/App/assets/104348397/08f18551-3bf7-4ddf-a50d-762bffedad95">

<img width="256" alt="Screenshot 2023-09-07 at 7 42 55 PM" src="https://github.com/Expensify/App/assets/104348397/27a36e85-d0aa-4244-8dc4-211190c93105">

**Comment by ishpaul777** [comment] 2023-09-07 14:16
please implement second point and see difference in margin top https://github.com/Expensify/App/issues/26911#issuecomment-1709972033

**Comment by ishpaul777** [comment] 2023-09-07 14:45
https://github.com/Expensify/App/assets/104348397/132e3b98-8275-4a2b-a05b-81893278aaaf

I could be missing something, please let me know

**Comment by tylerkaraszewski** [comment] 2023-09-07 16:08
Assigned to @ishpaul777

**Comment by lschurr** [comment] 2023-09-18 02:37
Hi @allroundexperts - Can you review the checklist for this one?

**Comment by lschurr** [comment] 2023-09-19 01:55
That sounds good @allroundexperts - we don't need a regression test.

**Comment by lschurr** [comment] 2023-09-20 02:18
Payment summary:

- Bug reporter: @ishpaul777 $50
- Contributor: @ishpaul777 $750
- Contributor+: @allroundexperts (does not require payment)

**Comment by lschurr** [comment] 2023-09-20 02:22
@ishpaul777 it looks like only the bug reporter offer was sent, so I sent another offer for the PR - could you accept so that I can pay?

**Comment by lschurr** [comment] 2023-09-20 02:57
Ah, yep sorry @allroundexperts - I'll update that now!

**Comment by ishpaul777** [comment] 2023-09-20 05:26
Hi @lschurr, I accepted the offer!

**Comment by lschurr** [comment] 2023-09-20 05:33
Great, payments made to @ishpaul777 in Upwork. This is all finished.

**Closed by lschurr** 2023-09-20 05:33 UTC
Labels: External, Daily, Awaiting Payment, Bug

**Comment by JmillsExpensify** [comment] 2023-10-05 13:09
$750 payment approved for @allroundexperts based on BZ summary.
