### ISSUE TITLE
[Awaiting payment][$250] [Track Tax] Selected tax rate is not marked with green check mark

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#39709] opened 2024-04-05 12:23 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.60-8
**Reproducible in staging?:** y
**Reproducible in production?:** y
**Issue reported by:** Applause - Internal Team

## Action Performed:
Precondition:
- User is an employee of Collect workspace.
- The Collect workspace has at least 9 tax rates.
1. Go to staging.new.expensify.com
2. Go to workspace chat.
3. Go to FAB > Request money > Manual.
4. Enter amount > Next.
5. On confirmation page, click Show more > Tax.
6. Select a tax rate.
7. Open Tax list again.
8. Enter any term in search field and clear it.

## Expected Result:
The selected tax rate should be marked with a green check mark because it will confuse the users when there is no highlight and check mark on the selected tax rate in a long list of rates.

## Actual Result:
The selected tax rate is not marked with a green check mark. After clearing the search field, the selected item is not highlighted which will confuse the users.

## Workaround:
n/a

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [x] Android: mWeb Chrome
- [x] iOS: Native
- [x] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

https://github.com/Expensify/App/assets/93399543/8e71aa35-2c14-4d4c-8c76-b7b133ff3ef8

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~0179c138ca9de376f2</li>
        <li>Upwork Job ID: 1777731900689838080</li>
        <li>Last Price Increase: 2024-04-09</li>
<li>Automatic offers: </li>
<ul>
<li>hoangzinh | Reviewer | 0</li>
<li>FitseTLT | Contributor | 0</li>
</ul></li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @anmurali</details>

**Comment by kbecciv** [comment] 2024-04-05 12:24
@anmurali I haven't added the External label as I wasn't 100% sure about this issue. Please take a look and add the label if you agree it's a bug and can be handled by external contributors.

**Comment by FitseTLT** [comment] 2024-04-05 13:39
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
Taxes - Selected tax rate is not marked with green check mark

### What is the root cause of that problem?
We are not setting `isSelected` as true for selected option for the sections we are passing here
https://github.com/Expensify/App/blob/823e9c94604aba4aff5eaec9147a7d910987babf/src/components/TaxPicker.tsx#L63-L64

### What changes do you think we should make in order to solve the problem?

We should set `isSelected` as true in these two places
https://github.com/Expensify/App/blob/823e9c94604aba4aff5eaec9147a7d910987babf/src/libs/OptionsListUtils.ts#L1284-L1287
https://github.com/Expensify/App/blob/823e9c94604aba4aff5eaec9147a7d910987babf/src/libs/OptionsListUtils.ts#L1332-L1333
and change
https://github.com/Expensify/App/blob/823e9c94604aba4aff5eaec9147a7d910987babf/src/libs/OptionsListUtils.ts#L1279
```

    const enabledTaxRates = sortedTaxRates
        .filter((taxRate) => !taxRate.isDisabled)
        .map((taxRate) => ({...taxRate, isSelected: selectedOptions.some((option) => option.name === taxRate.modifiedName)}));
```

and then add here
https://github.com/Expensify/App/blob/823e9c94604aba4aff5eaec9147a7d910987babf/src/libs/OptionsListUtils.ts#L1266-L1267
```
        isSelected: !!taxRate.isSelected,

```

### What alternative solutions did you explore? (Optional)

**Comment by anmurali** [comment] 2024-04-09 16:14
Makes sense to fix this as it would be consistent with the design for other fields
<img width="423" alt="image" src="https://github.com/Expensify/App/assets/14225673/5fa2190c-8b29-4094-a2d7-7be97d77fac4">

**Comment by trjExpensify** [comment] 2024-04-10 16:42
CC: @MonilBhavsar this is related to the tax tracking project, not simplified collect configuration. Is it on your radar and being worked on somewhere else? If so, please close this issue!

**Comment by MonilBhavsar** [comment] 2024-04-11 17:02
We missed this small item. Let's do it here. I'll self assign and manage the issue. @hoangzinh let's select a proposal!

**Comment by MonilBhavsar** [comment] 2024-04-18 05:16
@FitseTLT any idea when the PR will be up?

**Comment by FitseTLT** [comment] 2024-04-18 08:55
PR will be up in 2 days

**Comment by MonilBhavsar** [comment] 2024-05-14 05:57
This is fixed by other PR as mentioned in https://github.com/Expensify/App/pull/40628#issuecomment-2103240888
I think we can close this

**Comment by FitseTLT** [comment] 2024-05-17 11:00
bump @anmurali for the payment. The PR was on the final review stage so Payment is due. Thx.

**Comment by FitseTLT** [comment] 2024-06-06 15:33
@anmurali Can u pls process the payment here, it is super ooooverdue?

**Comment by anmurali** [comment] 2024-06-21 01:57
everyone's been paid.

**Closed by anmurali** 2024-06-21 01:57 UTC
Labels: External, Daily, Awaiting Payment, Bug
