### ISSUE TITLE
IOU - Receipt error message not displaying after uploading corrupted PDF

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#45710] opened 2024-07-18 17:52 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 9.0.9-1
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**If this was caught during regression testing, add the test name, ID and link from TestRail:** N/A
**Issue reported by:** Applause - Internaln Team

**Issue found when executing PR** https://github.com/Expensify/App/pull/45574
## Action Performed:
1. Submit an expense without a receipt to any user
2. Open the transaction thread
3. Press the receipt empty thumbnail
4. Select a corrupted PDF
5. Wait for the receipt error upload to show
6. Dismiss the error
7. Verify that: receipt is returned as the previous value

## Expected Result:
Receipt error message should be displayed after uploading corrupted pdf

## Actual Result:
Receipt error message not displaying after uploading corrupted pdf

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details> 

https://github.com/user-attachments/assets/44808e04-570f-47a5-a6da-316122579968

[Corrupted_PDF__1_-2024-03-12_19_06_51.067-2024-05-02 15_47_19.368.pdf](https://github.com/user-attachments/files/16287074/Corrupted_PDF__1_-2024-03-12_19_06_51.067-2024-05-02.15_47_19.368.pdf)

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by lanitochka17** [comment] 2024-07-18 17:52
@sonialiap  FYI I haven't added the External label as I wasn't 100% sure about this issue. Please take a look and add the label if you agree it's a bug and can be handled by external contributors

**Comment by sonialiap** [comment] 2024-07-22 10:20
I think this one is or it almost a dupe of https://github.com/Expensify/App/issues/43645

**Closed by sonialiap** 2024-07-22 10:20 UTC
Labels: Daily, Overdue, Bug
