### ISSUE TITLE
 Profile - There is a black background when uploading a gif with a transparent background for a profile

### ISSUE THREAD

**Issue by izarutskaya** [Expensify/App#26094] opened 2023-08-28 15:16 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Open the website
2. Go to settings > Profile
3. Click avatar
4. Click the upload photo
5. Upload a gif file with gray background
6. Click save

## Expected Result:
The gif should keep its background color

## Actual Result:
There is a black background

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [x] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** v1.3.57-5

**Reproducible in staging?:** Y

**Reproducible in production?:** Y

**If this was caught during regression testing, add the test name, ID and link from TestRail:**

**Email or phone of affected tester (no customers):**

**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/115492554/95a2381f-143c-4be8-9cb5-bf1fe3f4fc91

https://github.com/Expensify/App/assets/115492554/6b6df858-5d88-4c20-b572-122f4508427b

**Expensify/Expensify Issue URL:**

**Issue reported by:** @misgana96

**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1691326066597079

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by StevenKKC** [comment] 2023-08-28 21:53
## Proposal

### Please state again the problem we are trying to solve in this issue.
There is a black background when uploading a gif with a transparent background for a profile.

### What is the cause of this issue?
When uploading a profile photo, app converts image.
If image type is `image/png` or `image/svg`, then transparency is preserved, otherwise transparency will be removed.
https://github.com/Expensify/App/blob/5813ac99a20745e92538b0bd909f71f0f074944b/src/components/AvatarCropModal/AvatarCropModal.js#L320-L333
So after upload a gif image, black background is displayed.
### What changes do you think we should make to solve the problem?
We should convert gif image to `image/png`.
```js
    const isTransparent = props.imageType.includes('image/svg') || props.imageType.includes('image/gif');
    const imageName = isTransparent ? 'fileName.png' : props.imageName;
    const imageType = isTransparent ? 'image/png' : props.imageType;
```
And then we should change avatar's `backgroundColor` style to `themeColors.transparent` in `StyleUtils.getAvatarStyle`.
https://github.com/Expensify/App/blob/5813ac99a20745e92538b0bd909f71f0f074944b/src/styles/StyleUtils.js#L124
For all avatar styles and subscript styles in `styles.js`, we should add or change `backgroundColor`.
### What alternative solutions have you investigated? (Optional)
None.

**Comment by mallenexpensify** [comment] 2023-09-04 02:56
@misgana96, can you please provide the gif file you used? I want to check to see if the background is actually grey or if it's transparent.  Thx. 

@michaelhaxhiu  I'm off this week, can you please keep 👀 on this then I'll snag it back on Monday?  Thx

**Comment by misgana96** [comment] 2023-09-04 05:28
@mallenexpensify 
![R (2)](https://github.com/Expensify/App/assets/48551032/fac0fd12-8d11-49f6-a442-f5eccfe081bb)
here is the gif file I had used

**Comment by mallenexpensify** [comment] 2023-09-11 05:43
Thanks @misgana96 , I think the expected behaviour is
> When a gif is uploaded with a blank background, it shouldn't show as black (or grey, even though it shows as grey when first uploaded). 

My guess is that, since the app background is black, the background for the gif is actually clear and that's why it shows a black.  Do you agree?  

Thanks @michaelhaxhiu for 👀

**Comment by misgana96** [comment] 2023-09-13 08:13
> Thanks @misgana96 , I think the expected behaviour is
> 
> > When a gif is uploaded with a blank background, it shouldn't show as black (or grey, even though it shows as grey when first uploaded).
> 
> My guess is that, since the app background is black, the background for the gif is actually clear and that's why it shows a black. Do you agree?
> 
> Thanks @michaelhaxhiu for 👀

@mallenexpensify Sorry for the late reply. Yes, I agree. When a GIF is uploaded with a blank background and it is converted to a jpeg without preserving transparency

**Comment by mallenexpensify** [comment] 2023-09-14 07:29
@dannymcclain , quick 👀 before I close. 
If a gif is uploaded with a blank background (or... any image file that we accept with a blank background), we should preserve the clear background, if possible.  Right?  ie. right now we only have dark mode so clear looks black.  But once we have light mode, clear should equal white (or whatever _light_ background color we use). 

Or... are there other standards for managing avatars that have clear background?

**Comment by dannymcclain** [comment] 2023-09-14 18:05
@mallenexpensify Yeah I would expect any image with a transparent background would maintain it's transparency. So I think I'm with you on all this. cc @shawnborton in case he has a different opinion.

Related: it seems like the actual `div` elements that hold the avatar image have background colors being set on them, which is I think where the background color behind the transparent images are coming from. We could always adjust _that_ color if we really want to.

**Comment by shawnborton** [comment] 2023-09-15 02:07
Yeah, two things here:
- I agree that we don't want to modify the uploaded image, so if it has a transparent background, let's keep it
- We purposely have a background color behind transparent avatars so maintain consistent with avatar shapes, otherwise those UI elements could feel broken

**Comment by dannymcclain** [comment] 2023-09-15 14:16
So @mallenexpensify, based on Shawn's comments it seems like this is not a bug and is actually expected/intended behavior.

**Comment by mallenexpensify** [comment] 2023-09-19 06:02
Thanks @dannymcclain and @shawnborton , closing

**Closed by mallenexpensify** 2023-09-19 06:02 UTC
Labels: Engineering, Daily, Design, Overdue, Bug
