### ISSUE TITLE
[$1000] Web - Thousands separator not changing from comma to dot in old Requests when switching language from English to Spanish

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#21898] opened 2023-06-29 20:40 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Click on the plus sign :heavy_plus_sign:
2. Select "Request" and enter the desired number, then click "Next"
3. Add an old email for a previous Request and click "Next"
4. Go to settings > preferences > change language interchangeably
5. Observe that the thousands separator changes from comma to dot interchangeably when switching languages, but only for new Requests. The old Requests do not change.

## Expected Result:
he thousands separator in old Requests should change from comma to dot interchangeably, separating the thousands for both old and new requested money.

## Actual Result:
In old Requests, the comma that separates the thousands does not change to a dot when switching language from English to Spanish. However, in new Requests, the comma changes to a dot to separate the thousands.

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [x] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 1.3.34-1
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/93399543/dba12068-6aa3-4af7-9efe-f65088e74145

https://github.com/Expensify/App/assets/93399543/dd78a321-f751-4a03-af23-6725ef81f329

**Expensify/Expensify Issue URL:**
**Issue reported by:** @tewodrosGirmaA
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1687970394952749

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~0118cf5fe22185358e</li>
        <li>Upwork Job ID: 1674686100700442624</li>
        <li>Last Price Increase: 2023-07-07</li>
    </ul>
</details>

**Comment by greg-schroeder** [comment] 2023-06-30 07:44
@kbecciv I can't see that slack link as it appears to be an applause link - is there a link for Expensify's slack instance?

**Comment by greg-schroeder** [comment] 2023-06-30 07:47
Oh, funny. Reproduced.

**Comment by alitoshmatov** [comment] 2023-06-30 10:29
I don't think this is a bug, since message itself is still in english and this messages are not translated when language is changed.

**Comment by tewodrosGirmaA** [comment] 2023-06-30 10:46
I didn't get your idea @alitoshmatov.

**Comment by greg-schroeder** [comment] 2023-07-04 11:50
Awaiting review by @eVoloshchak

**Comment by eVoloshchak** [comment] 2023-07-05 21:09
Reviewing tomorrow as a first priority

**Comment by eVoloshchak** [comment] 2023-07-06 15:44
I can't reproduce this due to an error when creating a split bill
<img width="535" alt="image" src="https://github.com/Expensify/App/assets/9059945/000effd5-a54f-4639-875c-7d251102a7f9">

@jjcoffee, thanks for the [investigation](https://github.com/Expensify/App/issues/21898#issuecomment-1614724295)

> This appears to be primarily a BE issue
Depending on how long a BE fix might take, we might want to fix this on the FE in the meantime

If we can fix this on the back end, let's do that. This isn't severe, so I don't think a temporary FE solution is needed

I'll try to reproduce this a bot later to make sure this is indeed a back end issue

**Comment by jjcoffee** [comment] 2023-07-06 15:58
@eVoloshchak I had a similar issue before, I needed to split a bill with a completely new user to work around it.

**Comment by greg-schroeder** [comment] 2023-07-10 19:01
Wait so is this a BE issue that needs to be `Internal`? @eVoloshchak

**Comment by eVoloshchak** [comment] 2023-07-10 22:34
@greg-schroeder 
I can't reproduce this issue, but looking at the code, I agree with @jjcoffee, this should be Internal

**Comment by greg-schroeder** [comment] 2023-07-11 03:02
Okay. Adjusting accordingly.

**Comment by greg-schroeder** [comment] 2023-07-11 03:06
Hey @AndrewGable - TLDR on this one: It seems the issue should be fixed on the BE per [the discussion above](https://github.com/Expensify/App/issues/21898#issuecomment-1614724295), prompting this to be switched to an `Internal` issue.

**Comment by AndrewGable** [comment] 2023-07-11 22:05
I don't think we are going to update the back end to fix this, if a request is sent in one locale, I do not think we should adjust it to a different locale after it's been settled up.

Please reopen if you disagree @greg-schroeder.

**Closed by AndrewGable** 2023-07-11 22:05 UTC
Labels: Engineering, Daily, Internal, Bug
