### ISSUE TITLE
[HOLD for payment 2023-08-08] [$1000] Web - App crashes after pressing Backspace/Delete key in Incorrect magic code page

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#23596] opened 2023-07-25 21:31 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. On login page, enter an email/phone number and click Continue
2. Enter WRONG Magic code
3. When the error is showing, hold the left-mouse button and drag over the Magic code field - (like we are selecting text BUT do not show the selection)
4. Press Backspace/Delete key on the keyboard

## Expected Result:
Application should not crash

## Actual Result:
Application crashes

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [x] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 1.3.45-1
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/93399543/862b74ff-dc88-4ae3-9323-4de6fb72e674

https://github.com/Expensify/App/assets/93399543/5f2838bd-99f6-4f4e-a585-fd2196eefc49

**Expensify/Expensify Issue URL:**
**Issue reported by:** @tranvantoan-qn
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1690254789469459

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~017414e8528c6cdd44</li>
        <li>Upwork Job ID: 1684228115617501184</li>
        2023-07-26<li>Automatic offers: </li>
<ul>
<li>s77rt | Reviewer | 25775610</li>
<li>Pujan92 | Contributor | 25775614</li>
<li>tranvantoan-qn | Reporter | 25775617</li>
</ul></li>
    </ul>
</details>

**Comment by kbecciv** [comment] 2023-07-25 21:32
**Proposal**:  @tranvantoan-qn
**Slack conversation**: https://expensify.slack.com/archives/C049HHMV9SM/p1690254789469459

## Proposal

### Please re-state the problem that we are trying to solve in this issue.
App crashes after pressing Backspace/Delete key in Incorrect magic code page

### What is the root cause of that problem?
After dragging, the `editIndex` will be undefined, making it unable to retrieve the object. Unfortunately, in the following code, we did not check for this scenario, which results in an app crash:
https://github.com/Expensify/App/blob/main/src/components/MagicCodeInput.js#L105


### What changes do you think we should make in order to solve the problem?
To prevent the crash, add the following condition:


```javascript

        if (inputRefs.current[editIndex]) { 
            inputRefs.current[editIndex].blur();    
        }
```

**Comment by CortneyOfstad** [comment] 2023-07-26 15:45
@s77rt we have a couple of proposals for your review above 👍 TIA!

**Comment by Pujan92** [comment] 2023-07-26 17:15
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
App crashes when we press Backspace/Delete after dragging the mouse from input box

### What is the root cause of that problem?
Once magic code has been fulfilled, we called `blurMagicCodeInput` which will set the focused index to undefined. It seems when we start dragging from the input box, it will execute the focus event of the text where we aren't setting the index which we are doing within onPress callback. As the dragged Text input is focused it will fire the `onKeyPress` when we press `Backspace` and that is causing the issue of calling the `blur` method on undefined.

https://github.com/Expensify/App/blob/75e737b91867e01f83b04e4c36e0d02328e5727a/src/components/MagicCodeInput.js#L184-L186

https://github.com/Expensify/App/blob/75e737b91867e01f83b04e4c36e0d02328e5727a/src/components/MagicCodeInput.js#L195-L200

### What changes do you think we should make in order to solve the problem?
We can remove onPress and shift its logic to onFocus method where we perform the below steps which will set the correct index when the drag starts with the input box.
https://github.com/Expensify/App/blob/75e737b91867e01f83b04e4c36e0d02328e5727a/src/components/MagicCodeInput.js#L197-L199

**Comment by s77rt** [comment] 2023-07-26 18:54
@tranvantoan-qn Thanks for the proposal. I don't think your RCA is correct.

> After dragging, the `editIndex` will be undefined

This does not seem to be the case, dragging does not affect the `editIndex`.

**Comment by s77rt** [comment] 2023-07-26 18:57
@huzaifa-99 Thanks for the proposal. Your RCA is not exactly right.

> when we drag over the whole input (important: without **focusing** any cell) ... and on **blur**

This is a contradiction, if the blur event occurs then the input is actually focused. The root cause here seems to be that even the input is actually focused we don't update the `MagicCodeInput` with such info.

**Comment by tranvantoan-qn** [comment] 2023-07-26 19:00
@s77rt It actually does in this case - please note that even though we were dragging, **the text selection must not be shown** - see my video at `0.05`

The issue won't happen if the text selection is showing like this:
<img width="440" alt="Explain" src="https://github.com/Expensify/App/assets/10254571/494daeac-decb-4fcd-a1b1-2bdb725ef018">

**Comment by s77rt** [comment] 2023-07-26 19:12
@Pujan92 Thanks for the proposal. Your RCA is the most correct here.

> It seems when we start dragging from the input box, it will execute the focus event of the text _**but**_ we aren't setting the index _(focus index / edit index)_

Your solution makes sense but I'm afraid it causes a regression (similar to an [old bug](https://github.com/Expensify/App/issues/18324)):
1. Start typing magic code
2. Switch tab
3. Back to tab
4. Notice the position of the input did change



https://github.com/Expensify/App/assets/16493223/9195108f-34b3-489f-b006-b24ec892d645

**Comment by tranvantoan-qn** [comment] 2023-07-26 19:15
My question with his solution is: If the issue is caused by the **onKeyPress** event, why did the crash only happen with **Backspace** or **Delete** key? and as mentioned "**only when the text selection is not showing**"

**Comment by s77rt** [comment] 2023-07-26 19:22
@tranvantoan-qn Thanks for the update, but I still don't think this is the root cause. The root cause is that when you try to drag, `onMouseDown` you will **focus** the input. But we don't take that focus event into account i.e. `MagicCodeInput` still thinks that no input is focused (`focusedIndex` is still `undefined`). Then the blur event will occur and `MagicCodeInput` will blur the input that it has but it does not have the correct values for `focusedIndex` and `editIndex`.

**Comment by s77rt** [comment] 2023-07-26 19:23
@tranvantoan-qn 

Crash only happens when text selection is not showing because in that case the text input won't be focused. You can verify and type `document.activeElement` in the console. Notice that the issue will only happen if the activeElement is the text input.

**Comment by s77rt** [comment] 2023-07-26 19:32
@huzaifa-99 How would that fix the root cause? We need to ensure the following:
As long as the input is focused i.e. as long as `document.activeElement` return a text input (from the magic input). The state `focusedIndex` should have the index of that input and not `undefined`.


The below image shows a scenario that should never exist
![Screenshot from 2023-07-26 20-26-44](https://github.com/Expensify/App/assets/16493223/806ab1e1-fb26-410d-958f-fb61559a2fb3)

**Comment by tranvantoan-qn** [comment] 2023-07-26 19:35
@s77rt Following your explanation, I saw that the activeElement is always pointed to the last field
![image](https://github.com/Expensify/App/assets/10254571/0a525294-2370-4a2e-8884-02042494a9d7)

**Comment by Pujan92** [comment] 2023-07-26 20:18
> Your solution makes sense but I'm afraid it causes a regression (similar to an [old bug](https://github.com/Expensify/App/issues/18324)):
> 
> 1. Start typing magic code
> 2. Switch tab
> 3. Back to tab
> 4. Notice the position of the input did change

@s77rt  I think it is bcoz on changing the text we are not actually focusing on those input boxes. For that, we do need to use `inputRefs.current[updatedFocusedIndex].focus();` by replacing this code here.

https://github.com/Expensify/App/blob/ecfbafe9f6f86e4b47150de41d41cf3118660669/src/components/MagicCodeInput.js#L227-L228

**Comment by s77rt** [comment] 2023-07-26 21:33
@huzaifa-99 I don't see how this is different than @Pujan92's proposal. Also there is no reason to add the `focusedIndex == -1` check.

**Comment by s77rt** [comment] 2023-07-26 21:45
@Pujan92 Thanks for the update. That makes sense, just instead of replacing the code let's just add the focus method call to be consist - That's how we handle the `ArrowLeft` key press. I think we can probably go ahead with that solution, just before doing so can you please confirm that `onPress` won't be needed especially for native.

**Comment by Pujan92** [comment] 2023-07-26 21:56
@s77rt In the onFocus we are going to update these so I think we don't need them separately here and based on that I suggested to replace here. I just tested for ios native and seems working fine without `onPress`.

**Comment by s77rt** [comment] 2023-07-26 22:11
@Pujan92 Right, that same code will be called through the callback. Can you please update your proposal to take into account that change?

**Comment by Pujan92** [comment] 2023-07-26 22:17
@s77rt updated.

**Comment by s77rt** [comment] 2023-07-26 22:22
@Pujan92 Thanks!

:ribbon: :eyes: :ribbon: C+ reviewed
[Link to proposal](https://github.com/Expensify/App/issues/23596#issuecomment-1652207788)

**Comment by CortneyOfstad** [comment] 2023-08-01 20:13
I'm heading OoO until 8/14, so reassigning BZ to keep an eye on it while I'm out 👍

**Comment by s77rt** [comment] 2023-08-03 11:21
- The PR that introduced the bug has been identified: https://github.com/Expensify/App/pull/16076
- The offending PR has been commented on: https://github.com/Expensify/App/pull/16076#discussion_r1283038812
- A discussion in #expensify-bugs has been started: I don't think this is needed, the bug was introduced on a commit that was meant to follow another approach, seems like a one time bug.
- Determine if we should create a regression test for this bug: No

**Comment by CortneyOfstad** [comment] 2023-08-14 15:46
I am back from OoO, so taking this back over. Thanks @s77rt for the review above!

**Comment by CortneyOfstad** [comment] 2023-08-14 15:55
Payments have been made!

@tranvantoan-qn was paid the reporting amount of $250
@Pujan92 and @s77rt were both paid $1,500 (contributor and C+ fee, plus bonus due to the PR being merged within 1 day of assignment).

Closing!

**Closed by CortneyOfstad** 2023-08-14 15:55 UTC
Labels: External, Daily, Awaiting Payment, Bug
