### ISSUE TITLE
[$1000] "__fake___" is displayed when clicking on "Mark as Complete" without selecting an assignee

### ISSUE THREAD

**Issue by kavimuru** [Expensify/App#21502] opened 2023-06-24 16:52 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Open the room chat
2. Navigate to the "Assign task" section in the room chat
3. Enter a title for the task and click on "Next" > "Confirm task"
4. Click on description then enter description and click on save
5. Click on "Mark as complete"
6. Go to the room chat
## Expected Result:
The user who created the task should have their email displayed when no assignee selected
## Actual Result:
When clicking on "Mark as Complete" without selecting an assignee, "__fake"__ is shown
## Workaround:
Can the user still use Expensify without this being fixed? Have you informed them of the workaround?

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [ ] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 1.3. 32-5
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/43996225/c03d1ba8-52d8-4be7-b7a9-9274e22cddd1

https://github.com/Expensify/App/assets/43996225/8cece480-a696-4d9c-9727-3a036f30c776

**Expensify/Expensify Issue URL:**
**Issue reported by:** @ayazhussain79 
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1687249560384329

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~013428f2d15bee366a</li>
        <li>Upwork Job ID: 1677054385495605248</li>
        <li>Last Price Increase: 2023-07-06</li>
    </ul>
</details>

**Comment by BhuvaneshPatil** [comment] 2023-06-24 17:57
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
"__fake___" is displayed when clicking on "Mark as Complete" without selecting an assignee

### What is the root cause of that problem?
The root cause of this problem originates here - 
https://github.com/Expensify/App/blob/820fa93ad1e799c12d8b639b98018b5350ea17af/src/components/ReportActionItem/TaskPreview.js#L61

Here - we are using `managerEmail` i.e. the task assignee
When we do `Mark as Done` for a task that is without assignee, the `managerEmail` is set to - `__fake__`
and thus being rendered
and we are not checking if the email is `__fake__` or not


### What changes do you think we should make in order to solve the problem?
For the task that doesn't have assignee
![image](https://github.com/Expensify/App/assets/27822551/a59dfb0a-ac8c-4026-8b04-e5ca4f1c4b36)

We have no `participantAccountIDs` list.

We can add this check before directly rendering the `managerEmail`, which will be `__fake__` if the task is marked as done.

What to show here instead of `__fake__` shall be discussed and decided.

This is the task that has assignee
![image](https://github.com/Expensify/App/assets/27822551/6ed61018-f376-46d0-af6b-94458e2625b1)


### What alternative solutions did you explore? (Optional)

**Comment by sonialiap** [comment] 2023-06-27 21:32
Will triage on wednesday

**Comment by sonialiap** [comment] 2023-06-28 14:59
I wonder if it got fixed in this issue https://github.com/Expensify/App/issues/21216

**Comment by sonialiap** [comment] 2023-06-28 15:01
Sounds like a PR was in review when both this issue and https://github.com/Expensify/App/issues/21216 were reported

PR: https://github.com/Expensify/App/issues/21216#issuecomment-1600976030

**Comment by ayazhussain79** [comment] 2023-06-28 16:25
You can also check the steps in this video :

https://github.com/Expensify/App/assets/56740856/c4539bd5-365f-4fc7-90b2-355bbec79b96

**Comment by abdulrahuman5196** [comment] 2023-06-29 10:29
@sonialiap I doubt if the PR mentioned would solve this issue. The PR was only expected to solve workspace chat requests where workspace is shown as actor.

**Comment by ayazhussain79** [comment] 2023-06-29 15:44
@sonialiap you can even reproduce it on chat here is the steps:

1. Open a chat
2. Go to the "Assign task"
3. Just enter title and create the task
4. After creating task edit the description 
5. After editing click on "Mark as done" Button
6. Go to the chat and check the check the created task 


https://github.com/Expensify/App/assets/56740856/96fc7413-d999-485e-807e-b4dd5a66c14b

**Comment by ayazhussain79** [comment] 2023-07-03 08:51
@sonialiap can you please check this one?

**Comment by abdulrahuman5196** [comment] 2023-07-03 13:20
This issue isn't reproducible in the latest main. Now we are not even showing the name, could have been some recent change.

**Comment by ayazhussain79** [comment] 2023-07-03 13:29
@mountiny @abdulrahuman5196 i can still reproduce it on lates main you can also reproduce it both steps: https://github.com/Expensify/App/issues/21502#issuecomment-1613437628

1. Open the room chat
2. Navigate to the "Assign task" section in the room chat
3. Enter a title for the task and click on "Next" > "Confirm task"
4. Click on description then enter description and click on save
5. Click on "Mark as complete"
6. Go to the room chat

Here is the result after taking lates pull from main

https://github.com/Expensify/App/assets/56740856/bc4afe0c-2525-46a0-8788-525e61768c5a

**Comment by ayazhussain79** [comment] 2023-07-03 13:32
You can reproduce it using these steps in room and also in 1:1 chat
please follow these steps:
**step 1 for 1:1 chat:**
https://github.com/Expensify/App/issues/21502#issuecomment-1613437628
**For room chat:**
Open the room chat
Navigate to the "Assign task" section in the room chat
Enter a title for the task and click on "Next" > "Confirm task"
Click on description then enter description and click on save
Click on "Mark as complete"
Go to the room chat

**Comment by abdulrahuman5196** [comment] 2023-07-03 17:53
@mountiny  Yes. Able to reproduce this issue. We should re-open this issue @sonialiap 

<img width="511" alt="Screenshot 2023-07-03 at 11 23 09 PM" src="https://github.com/Expensify/App/assets/46707890/f0bea023-d7d5-40ff-90ab-e88d30562b6c">

**Comment by ayazhussain79** [comment] 2023-07-05 18:49
@sonialiap can you please check this bug

**Comment by sonialiap** [comment] 2023-07-06 20:38
Sorry guys, was caught up in other issues. Thanks for the reproduction videos and the reopen. Triaging to external ⏭️

**Comment by BhuvaneshPatil** [comment] 2023-07-07 14:19
About https://github.com/Expensify/App/issues/21502#issuecomment-1605670167

We need to decide on the placeholder that we will be showing instead of `__fake__`.

**Comment by BhuvaneshPatil** [comment] 2023-07-09 19:16
@ayazhussain79 Can you confirm if it's has been fixed or not.

**Comment by Santhosh-Sellavel** [comment] 2023-07-09 19:39
Not Reproducible for me

**Comment by ayazhussain79** [comment] 2023-07-09 19:52
Not able to reproduce now

**Comment by sonialiap** [comment] 2023-07-12 14:53
I cannot reproduce any more either. Looks like this got resolved by another PR

**Closed by sonialiap** 2023-07-12 14:53 UTC
Labels: External, Daily, Help Wanted, Overdue, Bug
