### ISSUE TITLE
[HOLD for payment 2023-09-18] [HOLD for payment 2023-09-18] [$500]  iPad - Page layout is broken in the landscape position

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#26421] opened 2023-08-31 18:23 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Open Expensify App on iPad
2. Rotate iPad to landscape position
3. Check page layout

## Expected Result:

The layout is not broken

## Actual Result:
Page layout is broken in the landscape position

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [x] Apple iPad Pro / 16.6
- [ ] iOS / Safari
- [ ] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 1.3.60-1

**Reproducible in staging?:** Yes

**Reproducible in production?:** No

**If this was caught during regression testing, add the test name, ID and link from TestRail:**

**Email or phone of affected tester (no customers):**

**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/78819774/62a40a8a-169e-42e0-8ad4-1f7914835681

https://github.com/Expensify/App/assets/78819774/1318a9be-ff06-4328-a3a2-2fcf2f5cfff2

**Expensify/Expensify Issue URL:**

**Issue reported by:** Applause - Internal Team

**Slack conversation:**

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~0101818de2158784ec</li>
        <li>Upwork Job ID: 1699050423953772544</li>
        <li>Last Price Increase: 2023-09-06</li>
<li>Automatic offers: </li>
<ul>
<li>shubham1206agra | Contributor | 26559347</li>
</ul></li>
    </ul>
</details>

**Comment by luacmartins** [comment] 2023-08-31 18:36
This is not one of our officially supported platforms so I'll demote it to NAB

**Comment by mountiny** [comment] 2023-08-31 18:48
yeah this is from https://github.com/Expensify/App/pull/22437 but this is not supported platform right now, curious that the rotation is not locked in

**Comment by roryabraham** [comment] 2023-09-01 16:14
We actually don't support landscape mode either. Maybe for now we should just make sure to disable landscape mode on iPad (I think it's disabled on iOS already?)

Long-term I would rather support iPad and landscape but I agree it's not a priority yet

**Comment by dangrous** [comment] 2023-09-01 16:33
I just tested and it looks like portrait is messed up too, at least on a simulator. But if we're okay with just having this open in the background (I'd rather not fully close it) until we have bandwidth, that's fine by me

<img width="887" alt="Screenshot 2023-09-01 at 12 06 40" src="https://github.com/Expensify/App/assets/5487802/f64c106b-a6e0-44c9-a591-2fa0bef274ab">

**Comment by mountiny** [comment] 2023-09-01 18:29
@dangrous I think this is because the screen is so wide it thinks its wide screen and puts in that layout.

We should probably force the narrow layout in ipad and disable landscape, this can be external

**Comment by mountiny** [comment] 2023-09-06 09:09
I am a bit unsure about this bug as blocking the landspace and catching if its ipad portrait would mean lots of weird logic.

Ideally we look into fixing the styles in native apps @adamgrzybowski what was the main reason we could not make the styles work for native?

**Comment by adamgrzybowski** [comment] 2023-09-06 09:17
If I remember correctly, there were some style properties used that are available on the web but not for native platforms. I think that `position: fixed` and `overflow: visible` may be the main suspect. 

But overflow visible should be available for the iOS. I could check if there is any way we could make it work for iOS. For Android it may be harder but I guess that wide screen android is a marginal usecase

**Comment by shubham1206agra** [comment] 2023-09-06 17:23
## Proposal
### Please re-state the problem that we are trying to solve in this issue.

iPad - Page layout is broken in the landscape position

### What is the root cause of that problem?

This is due to changes from https://github.com/Expensify/App/pull/22437, and we have different styling for native devices, which have glitches due to being in `isMediumScreenWidth` or `isLargeScreenWidth`.

### What changes do you think we should make in order to solve the problem?

We can disable landscape mode for the iPad. For this, remove the following lines
https://github.com/Expensify/App/blob/c2dab6ea63e0802888e32de3cc36fa15bfb706b8/ios/NewExpensify/Info.plist#L120-L121

For Android, convert all `<bool name="portrait_only">false</bool>` to `<bool name="portrait_only">true</bool>` in orientation.xml file

According to this comment https://github.com/Expensify/App/issues/26421#issuecomment-1703169556,
We will only use a narrow layout activated when `isSmallScreenWidth` is true.

So, in this case, we will force `isMediumScreenWidth` or `isLargeScreenWidth` to false for native devices and make it `isSmallScreenWidth`.

### Result

<img width="706" alt="Screenshot 2023-09-06 at 10 52 43 PM" src="https://github.com/Expensify/App/assets/58412969/12818225-16b7-4b9c-ba25-fed41883ebbc">

### What alternative solutions did you explore? (Optional)

**Comment by mountiny** [comment] 2023-09-08 07:38
@dangrous sorry for jumping in but I will move this forwards as it seems Apple might be rejecting the app because of the iPad layout issue

@shubham1206agra are you able to make the PR over the next hours? Lets only allow portrait mode in tablet, that is even if the `isSmallScreenWidth` would be false because of how large the ipad screen is

**Comment by mountiny** [comment] 2023-09-08 07:42
well its  a bit random as it seems they are not testing this everytime but now they did and they will probably keep testing each new release. We could also quickly disable the listing for ipad, so they dont test ipad until we fix the styling

**Comment by dangrous** [comment] 2023-09-08 13:34
Eep! Glad we caught this, thanks for stepping in @mountiny.

> We could also quickly disable the listing for ipad, so they dont test ipad until we fix the styling

Should we just do this anyway, if we're not supporting the platform? Do we need a separate issue?

**Comment by mountiny** [comment] 2023-09-11 08:33
I think this should be sorted for now, but we still need to actually fix the layout in the landscape so making this Help Wanted still

**Comment by mountiny** [comment] 2023-09-11 08:50
Yeah but I think we might want to still fix this for ipad, I am not sure. 
But yeah maybe its not something we should focus on, will remove the label and lets just pay out and close this

**Comment by abekkala** [comment] 2023-09-14 19:28
### PAYMENTS FOR SEPT 18
* Issue reported by: Applause 
* Selected Proposal for fix: @shubham1206agra [$500] + [$250 PR bonus] 
* C+ Review: @rushatgabhane  [$500] + [$250 PR bonus]

**Comment by abekkala** [comment] 2023-09-19 14:38
@shubham1206agra payment sent and contract ended. Thank you! 🎉 
<img width="611" alt="Screenshot 2023-09-19 at 9 38 33 AM" src="https://github.com/Expensify/App/assets/11966460/1b9ab687-5529-4813-ba79-64c6b9de39fa">

**Comment by abekkala** [comment] 2023-09-19 14:39
@rushatgabhane have you manually requested your payment in EChat yet?

**Comment by abekkala** [comment] 2023-09-25 08:10
@rushatgabhane can you confirm if you've requested payment yet?

**Closed** 2023-09-25 08:23 UTC
Labels: External, Engineering, Daily, Awaiting Payment

**Comment by JmillsExpensify** [comment] 2023-10-07 15:07
$750 payment approved for @rushatgabhane based on BZ summary.
