### ISSUE TITLE
[$500] Scan - Scan request contacts page on refresh showing previous scan page.

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#34836] opened 2024-01-19 19:59 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.28
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** Applause - Internal Team
**Slack conversation:**

## Action Performed:
1. Go to https://staging.new.expensify.com/
2. Tap fab --- Request money --- Manual
3. Enter an amount
4. Tap next
5. Note contacts are displayed
6. Now refresh the page
7. Note, user remains on same Contacts page
8. Tap back
9. Select scan
10. Upload a photo
11. Note contacts are displayed
12. Now refresh the page

## Expected Result:
On refreshing contacts page in manual request and Scan request, must show the same contacts page again

## Actual Result:
On refreshing contacts page in manual request, remains on same page but scan request contacts page on refresh showing previous scan page

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [x] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details> 

https://github.com/Expensify/App/assets/78819774/76f4a0b4-ad6b-4816-9262-635c7c23cb79

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01a17b25f99e9da79f</li>
        <li>Upwork Job ID: 1748435113377615872</li>
        <li>Last Price Increase: 2024-01-26</li>
    </ul>
</details>

**Comment by MitchExpensify** [comment] 2024-01-21 16:51
Reproduced and seems unique

**Comment by MitchExpensify** [comment] 2024-01-21 16:54
I'm thinking this is a nice to have for #vip-split

**Comment by getusha** [comment] 2024-01-25 11:23
Asked for another c+ to take over, due to limited bandwidth.
https://expensify.slack.com/archives/C02NK2DQWUX/p1706181777058709

**Comment by alitoshmatov** [comment] 2024-01-25 11:35
I could take over this issue

**Comment by DylanDylann** [comment] 2024-01-27 04:26
ref: https://github.com/Expensify/App/issues/28320#issuecomment-1745133984

**Comment by alitoshmatov** [comment] 2024-01-29 09:35
Take a look at it tonight

**Comment by alitoshmatov** [comment] 2024-01-30 18:53
@HezekielT Thank you for your proposal, I don't think storing whole file in Onyx is a good idea.

> ref: [#28320 (comment)](https://github.com/Expensify/App/issues/28320#issuecomment-1745133984)

Based on above reference I think it is logical to keep the current behavior considering it is an edge case. What do you think @MitchExpensify

**Comment by MitchExpensify** [comment] 2024-01-31 01:33
ah yes, good shout - Closing. @lanitochka17 do we need to update Testrail to avoid this getting flagged again? Thanks

**Closed by MitchExpensify** 2024-01-31 01:33 UTC
Labels: External, Daily, Help Wanted, Overdue, Bug
