### ISSUE TITLE
Wallet - Left side bar is LHN instead of Settings after adding a bank account

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#39827] opened 2024-04-08 14:46 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.61-0
**Reproducible in staging?:** Y
**Reproducible in production?:** N
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:**
**Slack conversation:**

**Issue found when executing PR** https://github.com/Expensify/App/pull/39038
## Action Performed:
1. Go to staging.new.expensify.com
2. Go to Profile > Wallet
3. Add /add-bank-account-refactor to the URL and navigate to it
4. Add a bank wallet

## Expected Result:
After adding a bank account, the left side bar and the right screen will open settings page

## Actual Result:
After adding a bank account, the left side bar is LHN, while the right screen is Wallet page

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details> 

https://github.com/Expensify/App/assets/78819774/88a8dd49-78be-4420-89c6-dbc1835bc0d2

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by lanitochka17** [comment] 2024-04-08 14:47
@rlinoz  FYI I haven't added the External label as I wasn't 100% sure about this issue. Please take a look and add the label if you agree it's a bug and can be handled by external contributors

**Comment by rlinoz** [comment] 2024-04-08 14:55
Looking at the videos in the original PR it looks like it is working as intended, maybe @mountiny or @shawnborton can confirm?

**Comment by shawnborton** [comment] 2024-04-08 14:59
Hmm I don't think anyone would directly access the page called `/add-bank-account-refactor ` - that might just be something temporary as we work through all of the styles here? Definitely curious for @mountiny 's take but I have a feeling we can close this one out?

**Comment by c3024** [comment] 2024-04-08 15:14
I think we map the central pane to RHP in these cases for deeplink cases. In this case by adding
```js
SCREENS.SETTINGS.ADD_BANK_ACCOUNT_REFACTOR,
```
here
https://github.com/Expensify/App/blob/dd30d137b485482bb8e4c61700b58d2e03683124/src/libs/Navigation/linkingConfig/CENTRAL_PANE_TO_RHP_MAPPING.ts#L35

Also, this route being sub-part of wallet shouldn't this be in `WALLET` here
https://github.com/Expensify/App/blob/dd30d137b485482bb8e4c61700b58d2e03683124/src/SCREENS.ts#L70
instead of directly in `SETTINGS` here
https://github.com/Expensify/App/blob/dd30d137b485482bb8e4c61700b58d2e03683124/src/SCREENS.ts#L35

**Comment by mountiny** [comment] 2024-04-08 15:21
@rlinoz thanks for the ping

This is not used flow yet and its middle of development hence the special route. We can close this

@koko57 will address this in the future work, the page needs to be added to the correct mapping

**Closed by mountiny** 2024-04-08 15:21 UTC
Labels: Engineering, Hourly

**Comment by koko57** [comment] 2024-04-08 15:28
yes, it's temporary as the refactor is being worked on - I'll take care of that in one of the following PRs

cc @mountiny @shawnborton
