### ISSUE TITLE
Troubleshoot page has blue color status bar

### ISSUE THREAD

**Issue by m-natarajan** [Expensify/App#44484] opened 2024-06-26 16:30 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 9.0.2-0
**Reproducible in staging?:** Yes
**Reproducible in production?:** Yes
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** @ishpaul777 
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1719384828744689

## Action Performed:
1. Go to staging.new.expensify.com
2. Tap Settings > Trouble shoot

## Expected Result:
Status bar should be same color as other pages with animation
## Actual Result:
Troubleshoot page has blue color status bar
## Workaround:
Unknown
## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [x] iOS: mWeb Safari
- [ ] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

https://github.com/Expensify/App/assets/38435837/5390ecc3-96d7-4024-8b89-8a74e4f92a9a

<img src="https://github.com/Expensify/App/assets/38435837/9a439440-ca44-4f3f-a10f-85b453364cc0" width="40%" height="40%">

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by isabelastisser** [comment] 2024-06-27 17:43
I cannot recreate this issue in staging or prod. Closing.

**Closed by isabelastisser** 2024-06-27 17:43 UTC
Labels: Daily, Bug

**Comment by isabelastisser** [comment] 2024-06-27 17:57
I can't reproduce this on Safari either:

<img width="1253" alt="image" src="https://github.com/Expensify/App/assets/31258516/900fdaae-22b0-45b6-afd3-4e8acc9bdb1d">

**Comment by isabelastisser** [comment] 2024-06-27 18:22
I see, I'm not sure if this should be considered a bug. I don't think we should change it. @shawnborton, what's your opinion here? The blue bar actually calls to switch to the New Expensify mobile app on Safari, I like it.

**Comment by shawnborton** [comment] 2024-06-27 18:25
We're already taking care of this one here: https://github.com/Expensify/App/pull/44048

So we can just keep this one closed!
