### ISSUE TITLE
[$1000] Provide reasonable defaults for all instances where we try to access a parent report that doesn't exist

### ISSUE THREAD

**Issue by jasperhuangg** [Expensify/App#29108] opened 2023-10-09 17:25 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** v1.3.79-3
**Reproducible in staging?:** yes
**Reproducible in production?:** yes
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** @JmillsExpensify 
**Slack conversation:** N/A

## Action Performed:
1. As accountA, mention accountB in a thread in a room that they don't have access to.
2. As accountB, try to open that thread.
3. Notice the app crashes

## Expected Result:
The App shouldn't crash, and you should be able to view the thread.

## Actual Result:
The App crashes because the parentReport is `undefined` [here](https://github.com/Expensify/App/blob/ccce49e93cff504b0035fd8b7f57e5ca4985700f/src/libs/ReportUtils.js#L856). We need to provide a reasonable default so that doesn't happen.

We should also search the codebase for any other instances where we may be accessing a `parentReport` that's `undefined` and fix those as well. A good proposal will find other instances where this may happen.

## Workaround:
N/A

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos
https://github.com/Expensify/App/assets/31285285/867afbd8-2cd6-4e34-b1d5-ba807b0e1581

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~0199b3acca3ca06afe</li>
        <li>Upwork Job ID: 1711432848480976896</li>
        <li>Last Price Increase: 2023-10-16</li>
    </ul>
</details>

**Comment by cead22** [comment] 2023-10-10 00:29
@jasperhuangg @puneetlath this looks like a simple update, do you agree, and would it make sense to decrease the bounty to $250?

**Comment by chamysoftware** [comment] 2023-10-10 07:48
@jasperhuangg, how does accountB access the thread? It does not show up in accountB's Left Hand Navigation.

**Comment by puneetlath** [comment] 2023-10-13 15:54
It shows up for me. 

Here's me mentioning someone in a thread: 
<img width="571" alt="image" src="https://github.com/Expensify/App/assets/1371996/7249e6f3-a010-4b3f-a36c-95c1df3fff43">

Here's that thread showing up in their LHN: 
<img width="731" alt="image" src="https://github.com/Expensify/App/assets/1371996/fad01273-cddd-4795-a683-eb7c8bf54162">

Here's what I see when they try to open that thread: 
<img width="1265" alt="Screenshot 2023-10-13 at 11 53 57 AM" src="https://github.com/Expensify/App/assets/1371996/9b21f148-e188-4a9a-9e5d-629e846d0b70">

**Comment by JmillsExpensify** [comment] 2023-10-16 15:54
I'm able to reproduce what Puneet sees above.

**Comment by puneetlath** [comment] 2023-10-16 17:10
Still waiting on proposals. This is an important flow for wave8, so going to adjust the bounty.

**Comment by akamefi202** [comment] 2023-10-18 12:30
Hi, everyone. May I ask about detailed reproduce steps of this issue?

**Comment by puneetlath** [comment] 2023-10-18 19:24
I think you're right and I believe @youssef-lr has pushed a back-end fix for this on staging.

**Comment by puneetlath** [comment] 2023-10-19 16:20
Closing since it looks like this is fixed.

**Closed by puneetlath** 2023-10-19 16:20 UTC
Labels: External, Daily, Help Wanted, Bug
