### ISSUE TITLE
[$250] MKT email test 1 Nov 4 - Nov 10 - Emails arrived with wrong subjects

### ISSUE THREAD

**Issue by IuliiaHerets** [Expensify/App#52120] opened 2024-11-06 15:40 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** v9.0.58-0
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**If this was caught during regression testing, add the test name, ID and link from TestRail:** https://expensify.testrail.io/index.php?/tests/view/5180841
**Issue reported by:** Appause Internal Team

## Action Performed:
1. Follow the instructions in TR: https://expensify.testrail.io/index.php?/runs/view/27311&group_by=cases:section_id&group_order=asc&group_id=327586
2. Wait 24h for the emails to arrive.
3. When emails arrive, check inbox for the subject.

## Expected Result:
Emails should arrive each having one of the following subjects:
- "Track and budget expenses"
- "Manage your team's expenses with Expensify"
- "Have a business expense? Get paid back with Expensify"
- "Split bills with friends in Expensify"

## Actual Result:
Emails arrived, all to their designated accounts, but all with the same wrong subject: "Business? Personal? Now it's both."

## Workaround:
Unknown

## Platforms:

- [ ] Android: Standalone
- [ ] Android: HybridApp
- [ ] Android: mWeb Chrome
- [ ] iOS: Standalone
- [ ] iOS: HybridApp
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

https://github.com/user-attachments/assets/17e784c6-e1ce-4d1e-8492-f339208aeebc

 
</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~021855906169398383700</li>
        <li>Upwork Job ID: 1855906169398383700</li>
        <li>Last Price Increase: 2024-11-11</li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @cristipaval</details>

**Comment by VictoriaExpensify** [comment] 2024-11-11 09:30
Agree this looks like a problem that we should fix

**Comment by YashasVaidya** [comment] 2024-11-11 14:03
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
Marketing test emails are arriving with a single incorrect subject line, "Business? Personal? Now it's both," instead of the intended subject lines. 

### What is the root cause of that problem?
The marketing email system seems to be defaulting to a hardcoded subject line. Since this occurs across all email types, this suggests a system-wide configuration issue rather than a template-specific problem. The email subject line selection logic appears to be either bypassing the intended template variations or defaulting to a fallback value at a global level.

### What changes do you think we should make in order to solve the problem?
We should:
1. Debug the email template subject line selection process to identify where the fallback subject is being used
2. Add error logging to understand which template is being selected
3. Modify the subject line assignment logic to ensure proper mapping
4. Add validation to prevent unintended default subject usage

### What alternative solutions did you explore? (Optional)
Considered adding subject line overrides at the delivery level, but this would mask rather than fix the root cause. Also considered a full rewrite of the email template system but determined this would be unnecessarily broad in scope.

**Comment by YashasVaidya** [comment] 2024-11-11 14:05
Contributor details
Your Expensify account email: YashasV@gatech.edu
Upwork Profile Link: https://www.upwork.com/freelancers/~01e497aef3d9b5a081

**Comment by cristipaval** [comment] 2024-11-18 09:43
@Beamanator, I know you're working on a project to consolidate email notifications. Do you think this issue is related to it and it will be fixed with your project?

**Comment by Beamanator** [comment] 2024-11-18 10:13
Oofda My project w/ James is https://github.com/Expensify/Expensify/issues/421536 which is just about sending the correct links (NewDot vs OldDot) in the emails - i wonder if you're thinking about https://github.com/Expensify/Expensify/issues/435128?

**Comment by VictoriaExpensify** [comment] 2024-11-28 02:37
Switching this to internal

**Comment by VictoriaExpensify** [comment] 2024-11-28 02:45
Hmm there was also this [PR](https://github.com/Expensify/Web-Expensify/pull/44516) which fixed the subject line for one specific scenario ([when paying report for removed member](https://github.com/Expensify/Web-Expensify/pull/44516#top)). It won't have resolved this issue, but it may be useful

**Comment by VictoriaExpensify** [comment] 2024-12-02 11:15
@cristipaval - have you had a chance to look at this?

**Comment by VictoriaExpensify** [comment] 2024-12-05 02:51
@cristipaval any change of an update on this one?

**Comment by cristipaval** [comment] 2024-12-05 13:09
I haven't had a chance to investigate this yet. I'll try to allocate some time this week.

**Comment by VictoriaExpensify** [comment] 2024-12-09 10:09
Not overdue

**Comment by cristipaval** [comment] 2024-12-13 12:11
> Expensify/Expensify#452816

Hey @VictoriaExpensify, I doubt these 2 issues have the same root cause.

**Comment by marcochavezf** [comment] 2024-12-13 15:56
Ah the subject was changed [here](https://github.com/Expensify/Web-Expensify/pull/43475/files#diff-63fe6fba328c214b4b9ab535f767b51cc0fd002810d3698537d9a65b0e6efeb8), I already updated the test case in TR https://expensify.testrail.io/index.php?/tests/view/5180841

**Closed by marcochavezf** 2024-12-13 15:56 UTC
Labels: Daily, Internal, Bug
