### ISSUE TITLE
[$500] Web - Profile Preview - Clicking on browser back button closes both preview and profile modal

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#33419] opened 2023-12-21 15:42 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** v1.4.15-4
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** Applause - Internal Team
**Slack conversation:**

## Action Performed:
1. Log into ND
2. Open a chat
3. Click on Header
4. Click on Avatar
5. Click on close icon
5. Open the avatar preview again by clicking on avatar
6. Click on browser back button
7. Compare the results

## Expected Result:
Browser back button should only close the preview

## Actual Result:
Browser back button closes the preview and also closes the modal

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

https://github.com/Expensify/App/assets/93399543/aeb2c29a-3542-425e-9082-a3e554e9b750

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~0129a1b8c63a557ca7</li>
        <li>Upwork Job ID: 1737861016407846912</li>
        <li>Last Price Increase: 2023-12-21</li>
    </ul>
</details>

**Comment by paultsimura** [comment] 2023-12-21 15:50
## Proposal

### Please re-state the problem that we are trying to solve in this issue.

### What is the root cause of that problem?

This is happening because when opening the photo, the URL remains the same, therefore navigating back just brings us to the whole other page back in history.

### What changes do you think we should make in order to solve the problem?

We can alter the logic of viewing the profile picture to work as a separate page (have a different URL), similar to what we do with attachments.

It may be `https://new.expensify.com/a/***/photo`.

The same should be done for the "My Profile" picture preview.

### What alternative solutions did you explore? (Optional)

**Comment by syed-mushahid** [comment] 2023-12-21 17:46
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
When click on back button the app moves to previous page and closes both profile view modal and profile picture view modal. 

### What is the root cause of that problem?

The profile picture view modal and the profile view modal both are on same url like https://new.expensify.com/a/8392101 so when click on back it will re direct to previous page and both modals closes as none of them was on previous url.

### What changes do you think we should make in order to solve the problem?

when the modal of view profile picture opens in the same handler we can push the url of current page in the url history  like this    ` history.pushState(null, null, window.location.href);` so when user will click on back button in his browser then he will be again redirected to the same page but this time as the page loads again then the profile view modal will be keep open but the profile picture modal will be closed.
 

### What alternative solutions did you explore? (Optional)

**Reminder:** Please use plain English, be brief and avoid jargon. Feel free to use images, charts or pseudo-code if necessary. Do not post large multi-line diffs or write walls of text. Do not create PRs unless you have been hired for this job.

**Comment by syed-mushahid** [comment] 2023-12-21 17:49
Contributor details
Your Expensify account email: syedmk600@gmail.com
Upwork Profile Link: [<REPLACE LINK HERE>](https://www.upwork.com/freelancers/~011d667dc6dca1164b)

**Comment by CortneyOfstad** [comment] 2023-12-21 18:40
@thesahindia any thoughts on the proposals above? Thank you!

**Comment by CortneyOfstad** [comment] 2024-01-02 19:43
Sorry for the delay here — was OoO for the holidays. Closing!

**Closed by CortneyOfstad** 2024-01-02 19:43 UTC
Labels: External, Daily, Help Wanted, Overdue, Bug
