### ISSUE TITLE
[HOLD for payment 2022-11-29] [$2000][Image] Attachments uploaded via camera lose their rotation, appears sideways.

### ISSUE THREAD

**Issue by kavimuru** [Expensify/App#11854] opened 2022-10-14 16:54 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:

1. Go to a DM
2. Tap plus in chat
3. Choose “add an attachment”
4. Chose “take a photo”
5. Take your photo, save

## Expected Result:
Uploaded image should be in the same orientation

## Actual Result:
All uploaded photos lose their orientation and are rotated 90 degrees to the left

## Workaround:
unknown

## Platform:

Where is this issue occurring?

- iOS

**Version Number:** 1.2.15-2
**Reproducible in staging?:** y
**Reproducible in production?:** y
**Email or phone of affected tester (no customers):** 
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** 

https://user-images.githubusercontent.com/43996225/195900439-cb259355-2f1b-45a5-bf87-3096a4b86252.MP4
<img src="https://user-images.githubusercontent.com/43996225/195900590-5429ba0d-a59b-4258-aafd-68c8f29f8435.PNG" width="40%" height="40%">

**Expensify/Expensify Issue URL:** 
**Issue reported by:** @JmillsExpensify 
**Slack conversation:** https://expensify.slack.com/archives/C01GTK53T8Q/p1665704504033759

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by JmillsExpensify** [comment] 2022-10-14 17:28
@arielgreen I'm going to take this one from you if you don't mind! 😄

**Comment by JmillsExpensify** [comment] 2022-10-17 11:44
Having trouble accessing Upwork at the moment, though I'll get to this one asap.

**Comment by JmillsExpensify** [comment] 2022-10-17 14:22
Actually I'm getting ahead of myself. I think this should be external but I'll quickly confirm with an Engineer to ensure that others agree.

**Comment by JmillsExpensify** [comment] 2022-10-17 14:24
@NikkiWines I imagine we can look for the orientation someone in the image metadata, so it's simply a matter of making sure we respect that orientation post upload. Do you agree?

**Comment by NikkiWines** [comment] 2022-10-17 17:47
I'd imagine it varies depending on what time of image but from looking at a couple of different types (.heic, .tiff, .jpg, screenshot) it looks like the orientation is occasionally provided: 

.heic
<img width="306" alt="image" src="https://user-images.githubusercontent.com/16747822/196246373-6eaab2b6-57d1-4468-857b-d35425571764.png">

.tiff
<img width="304" alt="image" src="https://user-images.githubusercontent.com/16747822/196246369-334dba0f-48fe-4b9b-9d74-cea3301c494a.png">

.jpeg 
<img width="306" alt="image" src="https://user-images.githubusercontent.com/16747822/196246765-4877b018-fc61-4a0e-892d-0f63d781cdc2.png">

taking a screenshot of another image
<img width="283" alt="image" src="https://user-images.githubusercontent.com/16747822/196246531-30025602-3ade-41eb-b16c-437e3744f3d2.png">

Wouldn't be a fool proof method to identifying orientation but we could most likely check to see if the orientation is present and modify the image based on that. I think this is a fine issue for `External`

**Comment by mountiny** [comment] 2022-10-17 18:05
Hmm this is odd issue and definitely feels like this must have worked before, maybe another regression which made it to production 😬 

@kavimuru @mvtglobally can you confirm if you have a testRail case for this thing? ie taking a picture and uploading it and making sure all looks correct (resolution and orientation)

**Comment by JmillsExpensify** [comment] 2022-10-26 17:33
> @kavimuru @mvtglobally can you confirm if you have a testRail case for this thing? ie taking a picture and uploading it and making sure all looks correct (resolution and orientation)

@kavimuru @mvtglobally I wanted to circle back on @mountiny's comment above. Do either you know if this a potential regression or never worked? I kind of think it never worked, but I'm not certain either. 

Still waiting for proposals in any case.

**Comment by JmillsExpensify** [comment] 2022-10-27 20:38
Ok, cool. I think this is pretty important, so I'm going to immediately raise the price to $1000.

**Comment by JmillsExpensify** [comment] 2022-11-01 19:04
@Beamanator Before I raise the price of this again, I kind of think this is an image bug that fits within the scope of your project. What do you think?

**Comment by Beamanator** [comment] 2022-11-02 10:40
@JmillsExpensify thanks for tagging me! I added this bug to my [tracker](https://github.com/Expensify/App/issues/10894) to keep an eye on it, but I don't think it needs to be put on hold since it's not related to caching - I would say go ahead and double and keep this one open to work on 👍

**Comment by JmillsExpensify** [comment] 2022-11-02 14:26
Sounds good! 

Contributors - please make sure to post your proposal in this issue. Then when we get there, the Upwork job is here: https://www.upwork.com/jobs/~01a08d6a4623670c83.

**Comment by mallenexpensify** [comment] 2022-11-02 20:46
Snagged from ya @JmillsExpensify since I'm managing the `[Image]` tracking issue. 
- https://github.com/Expensify/App/issues/11854

**Comment by hellohublot** [comment] 2022-11-03 08:46
### Proposal
I also encountered this problem in my project

https://github.com/react-native-image-picker/react-native-image-picker/blob/7490cc493737cd03f881cddeddbac28d43987534/ios/ImagePickerManager.m#L121-L134
####  Solution A
Use `4.8.4`, It's work fine in my project
````diff
- "react-native-image-picker": "^4.8.5",
+ "react-native-image-picker": "^4.8.4",
````
#### Solution B
Wait for https://github.com/react-native-image-picker/react-native-image-picker/pull/2036 to be merged, then we update to the next version 4.11.0
````diff
- "react-native-image-picker": "^4.8.5",
+ "react-native-image-picker": "^4.11.0",
````
#### Solution C
In the https://github.com/react-native-image-picker/react-native-image-picker/pull/2006, he pointed out that `UIImageJPEGRepresentation` and `UIImageJPEGRepresentation` return larger files, but this is maybe related to `albums`, not related to  `camera`, should not create `a new NSData`, so I want to create a `npx patch` to remove it
```diff
-       CFMutableDataRef imageData = CFDataCreateMutable(NULL, 0);
-       CGImageDestinationRef destination = CGImageDestinationCreateWithData(imageData, kUTTypeJPEG, 1, NULL);
-       CGImageDestinationAddImage(destination, image.CGImage, NULL);
-       CGImageDestinationFinalize(destination);
-       CFRelease(destination);
-       data = (__bridge NSData *)imageData;
```

Waiting for your suggestions and choices

**Comment by sobitneupane** [comment] 2022-11-03 12:11
Thank you @hellohublot for your findings.

I believe we prefer approach of solving the issue upstream (soultion B of the [proposal](https://github.com/Expensify/App/issues/11854#issuecomment-1301793683)). But https://github.com/react-native-image-picker/react-native-image-picker/pull/2036 has not received much attention from maintainer. 

I am not sure of the process when something has to be solved upstream. Your thoughts @mountiny ?

**Comment by mountiny** [comment] 2022-11-03 12:32
I agree we would prefer to fix this in the upstream. I have commented in the PR tagging the maintainer. I think in the past, he responded quite quickly but let;s see.

1. I think in the mean time if rolling back one minor version to `4.8.4` fixes this, we should go ahead and do that.
2. Keep an eye/make a follow up tracking issue to wait for the aforementioned fix being released upstream and update the package to that version.

Can we confirm there are not bad consequences of downgrading to 4.8.4? I would assume no, but we need to make sure. cc @sobitneupane @hellohublot

**Comment by sobitneupane** [comment] 2022-11-04 04:31
@hellohublot Will you be able to confirm the following?
> Can we confirm there are not bad consequences of downgrading to 4.8.4?

**Comment by hellohublot** [comment] 2022-11-04 04:55
Yes, from some of the links below, you can see that we submitted the fix to 4.8.4 in order to fix the image file being too large

https://github.com/Expensify/App/issues/9424

https://github.com/react-native-image-picker/react-native-image-picker/pull/2006

https://github.com/react-native-image-picker/react-native-image-picker/compare/v4.8.4...v4.8.5#diff-e80fbe0919b9194e068e83807bd44a593c476cc4a9b787c284ec3283445d163cL121-L166

https://github.com/Expensify/App/pull/10297



So I also agree that we wait for the https://github.com/react-native-image-picker/react-native-image-picker/pull/2036 to be merged and the release of the new version, or we adopt before then
````diff
- "react-native-image-picker": "^4.8.5",
+ "react-native-image-picker": "git+https://github.com/GiovanniVisentiniCasavo/react-native-image-picker#39b3cc24653655e0a0c7b9ec38248cbed2b54112",
````

**Comment by sobitneupane** [comment] 2022-11-04 05:16
So, the issue with downgrading to 4.8.4 is https://github.com/Expensify/App/issues/9424. 

I don't think it's good idea to use the following as it is yet to be tested and approved.
>
```diff
- "react-native-image-picker": "^4.8.5",
+ "react-native-image-picker": "git+https://github.com/GiovanniVisentiniCasavo/react-native-image-picker#39b3cc24653655e0a0c7b9ec38248cbed2b54112",
```

**Comment by hellohublot** [comment] 2022-11-04 05:33
Yes, we'd better do some more testing on this library, I'll also investigate and follow up on this pull request, and then stably upgrade to 4.11.0

**Comment by mountiny** [comment] 2022-11-04 09:51
We can also make our own fork of that library. Let's see if the maintainer in the repo will respond.

**Comment by mountiny** [comment] 2022-11-07 10:58
Ok, we might want to either fork this or apply a patch of that PR since this is quite high-value issue and we cannot rely on the maintainer to merge/release this.

**Comment by JmillsExpensify** [comment] 2022-11-08 05:25
Agree with that.

**Comment by mountiny** [comment] 2022-11-08 11:26
I have reached out to the maintainer, we are happy to support them as the package i very useful for us. I will give this couple of days (maintaining our own fork is quite a bit of overhead so better to avoid this if we can, they have been active in previous months).

**Comment by mountiny** [comment] 2022-11-11 10:42
Still no response from the maintainer. If nothing comes up til next week, I think we should try to use patch using that PR. Maintaining our fork might be overkill for this one PR.

**Comment by trjExpensify** [comment] 2022-11-11 12:29
Sounds good!

**Comment by mountiny** [comment] 2022-11-13 06:28
@hellohublot Hello! The maintainer has kindly responded and merged the PR and released a new version 🎉 

Do you want to take this job and update the package version and do all the testing?

**Comment by hellohublot** [comment] 2022-11-13 07:33
@mountiny Excellent, I am glad to accept this job, I will do a lot of tests of this library

**Comment by mountiny** [comment] 2022-11-14 10:28
@hellohublot You have been assigned now, please raise the PR with the changes and videos of testing if possible, I assume you might need to test on a physical device though.

@sobitneupane do you have iPhone to test this?

**Comment by trjExpensify** [comment] 2022-11-14 12:14
👋 @mountiny you marked this one as `Reviewing`, can you link the PR? 

@JmillsExpensify - I can't seem to access [this job on Upwork](https://www.upwork.com/jobs/~01a08d6a4623670c83) to view proposals/offers/hires etc. Can you take care of hiring @hellohublot & @sobitneupane, please?

**Comment by mountiny** [comment] 2022-11-14 13:29
Sorry that must have been fat-fingering, still waiting for @hellohublot for the PR. Feel free to link a draft as well 🙌

**Comment by JmillsExpensify** [comment] 2022-11-14 18:43
> @JmillsExpensify - I can't seem to access [this job on Upwork](https://www.upwork.com/jobs/~01a08d6a4623670c83) to view proposals/offers/hires etc. Can you take care of hiring @hellohublot & @sobitneupane, please?

Huh, not sure how to explain that. I've gone ahead and sent an offer to @sobitneupane since we've worked together before. @hellohublot to make sure we hire the right profile in Upwork, can you apply here: https://www.upwork.com/jobs/~01a08d6a4623670c83.

**Comment by sobitneupane** [comment] 2022-11-15 13:18
> @sobitneupane do you have iPhone to test this?

@mountiny Yes, I have.

**Comment by mountiny** [comment] 2022-11-15 17:04
@hellohublot I think unit tests are not required here unless this would be easy to achieve, not sure how one does unit tests about taking a picture.

We will add a regression test specifically for this so QA will always check the camera features work as expected.

**Comment by hellohublot** [comment] 2022-11-16 08:39
Hi. I have created a PR: https://github.com/Expensify/App/pull/12765, please help me to check

**Comment by mountiny** [comment] 2022-11-16 09:44
PR is in a review.

**Comment by trjExpensify** [comment] 2022-11-22 21:40
@hellohublot - quick bump [on this please](https://github.com/Expensify/App/issues/11854#issuecomment-1314214908) to apply to the job on Upwork so we're ready to issue payment.

**Comment by hellohublot** [comment] 2022-11-23 04:05
@trjExpensify OK, I have submitted it on upwork, my username is also 'hellohublot, Thanks

**Comment by trjExpensify** [comment] 2022-11-23 23:42
I can't see that on [this upwork job](https://www.upwork.com/jobs/~01a08d6a4623670c83), are you sure you sent it on the right one? 

<img width="1123" alt="image" src="https://user-images.githubusercontent.com/16232057/203664220-c928cc2c-724e-4459-b3c8-4308997b410b.png">

**Comment by hellohublot** [comment] 2022-11-24 02:44
@trjExpensify https://www.upwork.com/freelancers/~01509ca2c74bfc7073 
Sorry, this one.

**Comment by trjExpensify** [comment] 2022-11-24 18:10
Thanks, but can you click [this link](https://www.upwork.com/jobs/~01a08d6a4623670c83) and apply to the job? When I search for your profile, I can't find you.

**Comment by hellohublot** [comment] 2022-11-24 20:48
@trjExpensify ![image](https://user-images.githubusercontent.com/20135674/203860952-0176ec6b-d5f0-45fa-81ad-c37192b225e9.png)But I have already applied and cannot reapply

**Comment by hellohublot** [comment] 2022-11-25 18:38
@trjExpensify Maybe you can try to search "hublot", if you still can't find me, it is estimated that this job can only hire one person, please help to try to create another job, Thanks

**Comment by trjExpensify** [comment] 2022-11-29 14:50
Okay, payment is due today. @hellohublot you've been hired for another job since, so I've been able to locate you via that. Not sure why your application for this one hasn't been received - but I've sent you an offer. I've also applied the 50% bonus for merging the PR within 3 days. 

@sobitneupane - settled up for C+ 👍

**Comment by trjExpensify** [comment] 2022-11-29 15:12
As for the checklist: 

- The PR has been identified
- I've commented on it 
- We don't have a regression test for uploading an attachment via `Take Photo` which would have caught this one far sooner than we did. Created an issue to [add one here](https://github.com/Expensify/Expensify/issues/245321).

**Comment by trjExpensify** [comment] 2022-11-29 15:42
Cool, I've now settled up with @hellohublot. Closing!

**Closed by trjExpensify** 2022-11-29 15:42 UTC
Labels: Reviewing, External, Engineering, Daily, Improvement, Awaiting Payment, Bug
