### ISSUE TITLE
[HOLD for payment 2023-11-22] IOS - Send message -  Label not show on tab selector

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#29611] opened 2023-10-14 15:29 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** Dev v1.3.83-10
**Reproducible in staging?:** n
**Reproducible in production?:** n
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** @namhihi237
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1697210216244469

## Action Performed:
1. Click FAB button
2. Click send message
3. Observe that the label on the tab selector does not appear

## Expected Result:
It show label on selector tab

## Actual Result:
The label on the selector does not appear

## Workaround:
Unknown 

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [x] iOS: Native
- [ ] iOS: mWeb Safari
- [ ] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos
<details>
<summary>Android: Native</summary>

</details>

<details>
<summary>Android: mWeb Chrome</summary>

</details>

<details>
<summary>iOS: Native</summary>

 
![Screenshot 2023-10-13 at 22 17 05](https://github.com/Expensify/App/assets/93399543/1eeae19d-b850-4655-8be0-492015e85a89)

</details>

<details>
<summary>iOS: mWeb Safari</summary>

</details>

<details>
<summary>MacOS: Chrome / Safari</summary>

</details>

<details>
<summary>MacOS: Desktop</summary>

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01a781f41a1aa70899</li>
        <li>Upwork Job ID: 1713215578534891520</li>
        <li>Last Price Increase: 2023-10-14</li>
    </ul>
</details>

**Comment by ikevin127** [comment] 2023-10-14 16:50
## Proposal
### Please re-state the problem that we are trying to solve in this issue.
It show label on selector tab icon and label.

### What is the root cause of that problem?

It is a regression from PR https://github.com/Expensify/App/pull/27660 because of the styles migration where `tabOpacity` function is updated to return an object.
 
It used to return just a number and that value was set for the opacity prop but now we are trying to set an object for the opacity prop.

Example of `TabLabel` and `TabIcon`:

https://github.com/Expensify/App/blob/fe282b45cb13e01519282ccc023e5bfbd7714158/src/components/TabSelector/TabLabel.js#L28-L31

https://github.com/Expensify/App/blob/fe282b45cb13e01519282ccc023e5bfbd7714158/src/components/TabSelector/TabIcon.js#L29-L35

### What changes do you think we should make in order to solve the problem?
Pass the opacity object(activeOpacity, inactiveOpacity) directly to `TabLabel` and `TabIcon` components.

https://github.com/Expensify/App/blob/fe282b45cb13e01519282ccc023e5bfbd7714158/src/components/TabSelector/TabLabel.js#L28
would become:
```js
<Animated.View style={[activeOpacity]}>
```

Suggesting this because we're already using an object for `tabBackground` function.

Will also update the default prop values to empty objects here:

https://github.com/Expensify/App/blob/fe282b45cb13e01519282ccc023e5bfbd7714158/src/components/TabSelector/TabLabel.js#L19-L23

**Comment by Pujan92** [comment] 2023-10-14 17:08
Same RCA with https://github.com/Expensify/App/issues/29602#issuecomment-1762923960

**Comment by kubabutkiewicz** [comment] 2023-10-14 20:06
Created [PR](https://github.com/Expensify/App/pull/29629) per request from @situchan

**Comment by mountiny** [comment] 2023-10-15 18:47
The pr author resolved this, thanks!

**Comment by strepanier03** [comment] 2023-10-24 18:39
@mountiny - Can we close this or do we owe money to someone? I'm not 100% sure but it looks like perhaps this can just be closed.

**Comment by mountiny** [comment] 2023-10-25 20:42
@strepanier03 yeah I think we only need to pay the reporter @namhihi237 $50 thank you!

**Comment by mountiny** [comment] 2023-11-21 22:17
Sorry the automation failed I have updated this

**Comment by strepanier03** [comment] 2023-11-27 19:07
@namhihi237 - I've sent the offer and will check this later today to pay out.

**Comment by strepanier03** [comment] 2023-11-28 22:41
All right, paid out via Upwork and contract closed. Pretty sure this is good to close so going to do that. Feel free to reopen if I did that too soon.

**Closed by strepanier03** 2023-11-28 22:41 UTC
Labels: External, Daily, Awaiting Payment, Bug
