### ISSUE TITLE
[HOLD for payment 2023-08-16] [$1000] On request money report clicking the down arrow on options to pay with expensify hides the entire button

### ISSUE THREAD

**Issue by kavimuru** [Expensify/App#23140] opened 2023-07-18 22:25 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Login to ND (account should have permission to pay with Expensify)
2. Navigate to any request money report (if there is non then on user A request money to user B then login to user B to access request money report)
3. On request money report there should be a drop down button -> click on down arrow
4. Notice the dropdown option hides the `pay with expensify button`
## Expected Result: 
On opening the drop menu should not hide the button
## Actual Result: 
On opening the drop menu it hides the entire button

## Workaround:
Can the user still use Expensify without this being fixed? Have you informed them of the workaround?

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [x] MacOS / Chrome / Safari
- [x] MacOS / Desktop

**Version Number:** 1.3.41-2
**Reproducible in staging?:**  Needs reproducion (Pay with expensify only for USD)
**Reproducible in production?:** Needs reproduction
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/43996225/afa61ddf-a7f0-4452-acf0-b13586f4e88d

**Expensify/Expensify Issue URL:**
**Issue reported by:** @dhairyasenjaliya 
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1689595589459449

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01f871dc05dbdb8459</li>
        <li>Upwork Job ID: 1682166781314084864</li>
        2023-07-27<li>Automatic offers: </li>
<ul>
<li>situchan | Reviewer | 25854538</li>
<li>Nikhil-Vats | Contributor | 25854540</li>
<li>dhairyasenjaliya | Reporter | 25854542</li>
</ul></li>
    </ul>
</details>

**Comment by kavimuru** [comment] 2023-07-18 22:25
### Proposal
### Please re-state the problem that we are trying to solve in this issue.
On request money report clicking the down arrow on options to pay with expensify hides the entire button
### What is the root cause of that problem?
The root cause is we are passing wrong `vertical` `anchorAlignment` on `ButtonWithDropdownMenu` that makes menu to over laps with button and hide under it
### What changes do you think we should make in order to solve the problem?
We need to pass correct `vertical``anchorAlignment` that shows menu on bottom of the button without hiding that
Currently we are passing `ANCHOR_ORIGIN_VERTICAL.BOTTOM` instead of that ew just need to pass `ANCHOR_ORIGIN_VERTICAL.TOP` on below line
https://github.com/Expensify/App/blob/25c8ae5212f433ea7679ba4bd040c79f151a282a/src/components/ButtonWithDropdownMenu.js#L122
### What alternative solutions did you explore? (Optional)
N/A

**Comment by sakluger** [comment] 2023-07-19 00:27
Asking in the Slack threadabout reproduction.

**Comment by Nikhil-Vats** [comment] 2023-07-19 10:08
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
In IOU Report, when caret/arrow/dropdown button is clicked in settlement button in header, the main button gets hidden behind the popover menu.
### What is the root cause of that problem?
We are using the wrong vertical alignment for the popover menu here. It should be `TOP` not `BOTTOM`.
https://github.com/Expensify/App/blob/9508dfafb2c666893df65acc1289ff37839406cc/src/components/ButtonWithDropdownMenu.js#L122

Also, there is no padding here which we are using on other pages -
https://github.com/Expensify/App/blob/9508dfafb2c666893df65acc1289ff37839406cc/src/components/KYCWall/BaseKYCWall.js#L72

### What changes do you think we should make in order to solve the problem?
We need to change line 122 to -
```javascript
vertical: CONST.MODAL.ANCHOR_ORIGIN_VERTICAL.TOP,
```

Also, to add the consistent padding of `8px`, we need to change line 69 from -
https://github.com/Expensify/App/blob/9508dfafb2c666893df65acc1289ff37839406cc/src/components/ButtonWithDropdownMenu.js#L67-L70

```javascript
vertical: y + h + 8,
```

We should make a constant for this `8px` in CONST.js and then use it here and in other files.
Design team provided there approval on this `8px` padding [here](https://github.com/Expensify/App/issues/21259#issuecomment-1610148333).
### What alternative solutions did you explore? (Optional)
NA

<details>
<summary>
Result -
</summary>

Current state -

<img width="342" alt="image" src="https://github.com/Expensify/App/assets/31413407/c4c59e12-3688-43ad-9dcb-76250ae3f5eb">


Position changed Without padding -

<img width="344" alt="Screenshot 2023-07-19 at 3 33 48 PM" src="https://github.com/Expensify/App/assets/31413407/ddc268d2-bfc6-47b2-95ba-4d82b3475c53">

Position changed with padding -

<img width="342" alt="image" src="https://github.com/Expensify/App/assets/31413407/e2ee3071-9aa7-4976-a898-b372e02e86a7">

</details>

**Comment by sakluger** [comment] 2023-07-20 23:12
I was able to reproduce this and it's definitely a bug!

**Comment by situchan** [comment] 2023-07-24 21:48
There are cases where `BOTTOM` is needed. i.e. `ReportPreview`.
So no satisfactory proposals yet.

**Comment by situchan** [comment] 2023-07-24 22:04
ok, that's just an example. What about MoneyRequestConfirmationList?
It shows button at the footer so dropdown menu might be overlapped with window bottom edge

**Comment by Julesssss** [comment] 2023-07-25 08:26
Yeah, I think it's fine because it's still a dropdown menu, we just happen to show it above the button instead of on-top or below.

**Comment by sakluger** [comment] 2023-07-27 23:22
@situchan mind checking on @Nikhil-Vats's updated proposal?

**Comment by situchan** [comment] 2023-07-31 09:54
@Nikhil-Vats thanks for considering padding. [proposal](https://github.com/Expensify/App/issues/23140#issuecomment-1641805777) looks good to me.
🎀 👀 🎀 C+ reviewed

**Comment by greg-schroeder** [comment] 2023-08-01 14:40
FYI: We've closed https://github.com/Expensify/App/issues/22505 as a dupe of this issue. Let's make sure the solution extends to the `ThreeDotsMenu` as well

**Comment by Julesssss** [comment] 2023-08-07 14:20
<img width="713" alt="Screenshot 2023-08-07 at 15 19 30" src="https://github.com/Expensify/App/assets/10736861/e8347907-1777-4dfa-b8f7-c6a23fe88d3e">

The PR was ready to merge within 3 days, but I was OOO. Bonus should apply.

**Comment by sakluger** [comment] 2023-08-17 04:49
- Paid @dhairyasenjaliya $250 for the bug report
- Paid @Nikhil-Vats $1500 as the Contributor (with efficiency bonus 🎉 )

@Nikhil-Vats as soon as you finish the BugZero checklist I can complete your payment as well. Thanks!

**Comment by situchan** [comment] 2023-08-17 04:52
No PR caused regression. I'd say this is minor UI improvement than bug so no regression test is needed

**Comment by sakluger** [comment] 2023-08-17 18:36
Thanks @situchan! I completed payment via Upwork.

**Closed by sakluger** 2023-08-17 18:36 UTC
Labels: External, Daily, Awaiting Payment, Bug
