### ISSUE TITLE
[HOLD on E/E #308026] [$1000] Web -  Archived Room Messages Editable Through Thread Reply

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#23595] opened 2023-07-25 21:21 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
There is no button to edit comments in an archived room (A room with deleted workspace) which means users should not be able to edit messages once a room has been archived. But from inside the thread, there is a way to bypass this and edit comments.
Note- Choose an old test account with archived rooms (a deleted workspace with room with messages- if you do not have one,  create a room > send a message > delete the workspace)
1. Try to edit the message from the main page
2. Verify you can see the edit button when you hover over the message
3. Now, click on reply to the thread. This will take you to the thread.
4. Attempt to edit the message. Verify it is successful.
5. Go to the main room page and verify that you can see the edited message

## Expected Result:
Don't allow users to create thread from messages in archived room.

## Actual Result:
Editing messages from a archived room was possible even though no direct ‘Edit comment’ button is available

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [x] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [x] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 1.3.44.0
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/93399543/91a5591e-73e4-436a-8dc4-de321bf4f973

https://github.com/Expensify/App/assets/93399543/3e68e37e-236a-4f9b-a76c-1d527b3c42d0

**Expensify/Expensify Issue URL:**
**Issue reported by:** @avi-shek-jha
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1690249413252109

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01b5ef8f9b65180ce9</li>
        <li>Upwork Job ID: 1686005681509642240</li>
        <li>Last Price Increase: 2023-08-14</li>
    </ul>
</details>

**Comment by jscardona12** [comment] 2023-07-26 01:56
## Proposal
### Please re-state the problem that we are trying to solve in this issue.
Archived room messages editable through threads

### What is the root cause of that problem?
The root cause of the issue is that that the threads of the Acrhived Report haven't been archived.

### What changes do you think we should make in order to solve the problem?
We should archive the Threads Reports if the Parent is archived as well.
in [ReportScreen.js](https://github.com/Expensify/App/blob/e32ff5e90fc5b70a802610d2401270f8c4ee03a1/src/pages/home/ReportScreen.js#L145C1-L160C6) in componentDidMount we should add the following lines:

            const parentArchived = ReportUtils.isArchivedRoom(ReportUtils.getParentReport(this.props.report)); 
            if(parentArchived) {
                 Report.archiveReport(this.props.report);
           }

and in [Report.js]() add a new function archiveReport to updatet the report and Archive it:

    function archiveReport(report) {
      const statusNum = CONST.REPORT.STATUS.CLOSED;
      const stateNum = CONST.REPORT.STATE_NUM.SUBMITTED;
      API.write(
          'archiveReport',
          {
              statusNum,
              stateNum
          },
          {
              optimisticData: [
                  {
                      onyxMethod: Onyx.METHOD.MERGE,
                      key: `${ONYXKEYS.COLLECTION.REPORT}${report.reportID}`,
                      value: {
                          statusNum,
                          stateNum,
                      },
                  },
              ], 
          },
      );
     }

###Solution Working

https://github.com/Expensify/App/assets/16781411/38f11eca-d745-4c2d-ae38-ca8e63cb2702

**Comment by michaelhaxhiu** [comment] 2023-07-31 13:29
Going external. @sobitneupane we have 2 proposals above already 🐰

**Comment by michaelhaxhiu** [comment] 2023-08-02 23:18
friendly bump - @sobitneupane Can you take a look at the proposals above?

**Comment by sobitneupane** [comment] 2023-08-03 08:27
@michaelhaxhiu IMO, we should not allow user to create a thread from the archived report. 

We are already archiving a pre-existing thread if parent report is archived. But we are allowing to create new thread if a thread doesn't exist.

**Comment by jscardona12** [comment] 2023-08-03 11:22
@sobitneupane in the tests that I made we are not archiving the existing thread you can still keep adding messages to that thread. That's why my Proposal is to detect it needs to be archive and mark it so.

**Comment by sobitneupane** [comment] 2023-08-03 11:29
@jscardona12 It might have been updated.

https://github.com/Expensify/App/assets/25876548/30397d09-c06e-41ea-a53f-ee6159a45d99

**Comment by jscardona12** [comment] 2023-08-03 13:08
## Proposal
### Please re-state the problem that we are trying to solve in this issue.
Archived room messages editable through threads

### What is the root cause of that problem?
The root cause of the issue is that that we should not allow user to create a thread from the archived report.

### What changes do you think we should make in order to solve the problem?
We should hide the "reply on thread"optionn if the chat is archived.
in [ContextMenuActions.js](https://github.com/Expensify/App/blob/e32ff5e90fc5b70a802610d2401270f8c4ee03a1/src/pages/home/report/ContextMenu/ContextMenuActions.js#L122-L123) : i the shouldShow fucntion add `!isArchivedRoom` to the validation

            shouldShow: (type, reportAction, isArchivedRoom, betas, anchor, isChronosReport, reportID) =>
            type === CONTEXT_MENU_TYPES.REPORT_ACTION && reportAction.actionName === CONST.REPORT.ACTIONS.TYPE.ADDCOMMENT && !ReportUtils.isThreadFirstChat(reportAction, reportID) && !isArchivedRoom,


###Solution Working

**Comment by michaelhaxhiu** [comment] 2023-08-03 17:41
@sobitneupane I agree with your conceptually. Do you think the GH needs to be updated to clarify that?

I felt like the Expected Result conveys it decently? What do you think:
>Unable to edit message

**Comment by sobitneupane** [comment] 2023-08-04 07:06
@michaelhaxhiu 
We can update it to something like:

Don't allow users to create thread from messages in archived room.

**Comment by michaelhaxhiu** [comment] 2023-08-04 16:07
Cool, more specific is better. I'm won over 😄

**Comment by michaelhaxhiu** [comment] 2023-08-04 16:09
Note: I'm preparing to go OOO for ~2 weeks and need a BZ buddy to watch over this in the meantime. 🙏

**Next step:** Please ensure that we push this forward, and double price by 8/8 if there are no winning proposal in the next week.

Thanks in advance @twisterdotcom, I can take this back when I get back if it's not complete by then!

**Comment by sobitneupane** [comment] 2023-08-09 03:49
@twisterdotcom I don't think it should be internal. Going to review proposals shortly.

**Comment by sobitneupane** [comment] 2023-08-09 12:06
Thanks for the update @jscardona12. Your proposal looks good to me. 

So, even if the message has pre-existing thread, we won't be showing "Reply in thread" option in context menu, right? I think it makes sense because user can navigate to the pre-existing thread even without the option?

> in the tests that I made we are not archiving the existing thread you can still keep adding messages to that thread. That's why my Proposal is to detect it needs to be archive and mark it so.

@jscardona12 You were right [here](https://github.com/Expensify/App/issues/23595#issuecomment-1663806420). We are archiving only threads in user created room but not in default room(i.e, #announce and #admins). I believe that's an issue. Can you please trace why the behavior in default room is different from that user created room? I don't think that was intentional move. I feel like it is something that should be handled in backed.

**Comment by jscardona12** [comment] 2023-08-09 13:34
@sobitneupane Exactly, the user won't be able to create new threads, but still will be able to navigate through the exisiting ones.

I will open an slack copnversation to see if someone knows about this. but agreed that scenario should be handled the same way as the orther rooms.

**Comment by twisterdotcom** [comment] 2023-08-09 14:42
Okay, good discussion in Slack. Let's archive all rooms and threads in those rooms when a workspace is archived, not just user created ones.

**Comment by jscardona12** [comment] 2023-08-09 15:18
Hi @sobitneupane @twisterdotcom, the archive part should be handled in the backend, but the fact that the create thread is still available when chat is archive is an error that we can solve in this issue in the frontend. Can we proceed with the [Proposal ](https://github.com/Expensify/App/issues/23595#issuecomment-1663955285)approach?

**Comment by sobitneupane** [comment] 2023-08-14 09:40
Thanks for the update @jscardona12.

>  Can you please trace why the behavior in default room is different from that user created room?

@jscardona12 Can you please trace why frontend is acting differently for default room? I mean what different data is being received from the backend, so, threads are not archived in the default room.

**Comment by jscardona12** [comment] 2023-08-14 12:07
Hi @sobitneupane, oh sure. as i stated in my first [proposal (https://github.com/Expensify/App/issues/23595#issuecomment-1650855329), the params `stateNum` and `statusNum` are in 0 on the default rooms, they need to be in 2 to be set as archive. 

Default Thread Rooms: 
<img width="1919" alt="Screenshot 2023-08-14 at 7 05 45 AM" src="https://github.com/Expensify/App/assets/16781411/e427fe52-6a2f-4e6d-a670-6370578d97b8">


Created Thread Rooms.  
<img width="1915" alt="Screenshot 2023-08-14 at 7 06 37 AM" src="https://github.com/Expensify/App/assets/16781411/a9cde53c-8acb-40a7-bc7b-8d51e4d4aa9e">

**Comment by mvtglobally** [comment] 2023-08-16 20:42
Issue not reproducible during KI retests. (First week)

**Comment by jscardona12** [comment] 2023-08-18 19:23
Hey, so after the discussions in slack @JmillsExpensify and @twisterdotcom decided that this would be manage [internally] (https://expensify.slack.com/archives/C01GTK53T8Q/p1692032103980409?thread_ts=1691588243.915289&channel=C01GTK53T8Q&message_ts=1692032103.980409) so I was wondering since I help finding the RC and with the thread and definition if i apply for a 25% contribution?

cc: @sobitneupane

**Comment by michaelhaxhiu** [comment] 2023-09-20 16:11
Yes I think 25% is reasonable for the effort invested here. 

Let's pay and close this one, since we'll finalize it internally

Bug reporting bonus: @avi-shek-jha $250
Contributor: 25% of bounty for help moving issue forward (it'll be fixed internally at the end) $250 @jscardona12 
C+: same pay as contributor $250

**Comment by michaelhaxhiu** [comment] 2023-09-20 16:14
Can yall apply to this job please? https://www.upwork.com/jobs/~01754e75ae0b52c715

**Comment by avi-shek-jha** [comment] 2023-09-20 17:22
> Can @avi-shek-jha and @jscardona12 apply to this job please? https://www.upwork.com/jobs/~01754e75ae0b52c715
> 
> Comment here after you've done so.

I have applied. Thank you.

**Comment by jscardona12** [comment] 2023-09-20 18:54
> Can @avi-shek-jha and @jscardona12 apply to this job please? https://www.upwork.com/jobs/~01754e75ae0b52c715
> 
> Comment here after you've done so.

Thax @michaelhaxhiu! i have applied

**Comment by michaelhaxhiu** [comment] 2023-09-20 20:03
Even though you applied and I hired, Upwork is ridiculous so I need you to accept once more, lol. Tell me when it's done or emoji react here 🙏

**Comment by jscardona12** [comment] 2023-09-20 21:22
@michaelhaxhiu already accepted! Thx!

**Comment by avi-shek-jha** [comment] 2023-09-20 22:01
> Even though you applied and I hired, Upwork is ridiculous so I need you to accept once more, lol. Tell me when it's done or emoji react here 🙏

Accepted. Thanks

**Comment by sobitneupane** [comment] 2023-09-25 05:04
Requested payment on newDot.

https://github.com/Expensify/App/issues/23595#issuecomment-1728048693

**Comment by JmillsExpensify** [comment] 2023-09-28 00:59
$250 payment approved for @sobitneupane based on BZ summary.

**Comment by michaelhaxhiu** [comment] 2023-09-28 12:27
All set!

**Closed by michaelhaxhiu** 2023-09-28 12:27 UTC
Labels: Monthly, Internal, Bug

**Comment by jscardona12** [comment] 2023-09-28 18:39
@michaelhaxhiu i still haven't received the payment through Upwork. can you help me with that?

**Comment by michaelhaxhiu** [comment] 2023-09-28 19:07
strange, I thought it was paid but you are correct. Sorry about that. Paid now 👍
