### ISSUE TITLE
 Amount is not localized on IOU Details page, LHN and Report

### ISSUE THREAD

**Issue by kavimuru** [Expensify/App#14476] opened 2023-01-23 18:00 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:

1. Request Money - Click on Green Badge (Top Right)
2. Observe Amount in IOU Details Page, LHN and Report page

## Expected Result:
Amount should be localized (ex: for Spanish 100,90 and in English 100.90)

## Actual Result:
Amount is not localized in report page and IOU details page

## Workaround:
unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?

- [ ] MacOS / Chrome / Safari

**Version Number:** 1.2.58-0
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** 
<img width="638" alt="Screenshot 2023-01-20 at 10 17 43 PM" src="https://user-images.githubusercontent.com/43996225/214114787-c9f8d8e3-a89c-42d6-b485-743589e03aa2.png">

https://user-images.githubusercontent.com/43996225/214114792-bc6983fb-09da-40e8-8672-ae74dafdfa9a.mov

https://user-images.githubusercontent.com/43996225/214114896-4b9c5ff6-3dff-4f35-8e85-c9e1a4ee9606.mp4

**Expensify/Expensify Issue URL:**
**Issue reported by:** @varshamb 
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1674233388653609

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by strepanier03** [comment] 2023-01-23 20:40
### Bug0 Triage Checklist
_Note: see [this SO](https://stackoverflow.com/c/expensify/questions/14418) for more information._
- [ ] The "bug" is actually a bug 
- [ ] The bug is not a duplicate report of an existing GH.
  - If it is, close the GH and add any novel details to the original GH instead 
- [ ] The bug is reproducible, following the reproduction steps.
  - [ ] If the GH doesn’t have steps to reliably reproduce the bug and you figure it out, then please add them.
  - [ ] If you’re unable to reproduce the bug, add the `Needs reproduction` label. 
  - [ ] Comment on the issue outlining the steps you took to try to reproduce the bug, your results and tag the issue reporter and the Applause QA member who created the issue. Ask them to clarify reproduction steps and/or to check the reproduction steps again. Close issue. 
- [ ] The GH template is filled out as fully as possible
  - The GH body and title are clear (ie. could an external contributor understand it and work on it?) 
- [ ] The GH was created by an Expensify employee or a QA tester 
- [ ] If the bug is an OldDot issue, you should decide whether it is widespread enough to justify fixing or it is better to wait for reunification. If it’s better to wait, close the GH & provide this justification 
- [ ] If there's a link to Slack, check the discussion to see if we decided not to fix it 
- [ ] Decide if the GH should be resolved by an External contributor or Internal engineer, add the appropriate label

**Comment by strepanier03** [comment] 2023-01-23 21:01
Testing this and going to raise a question about the expected behavior. I see that we're localizing in most places but in the original chat comment for the request and the request history we aren't. 

<img width="890" alt="2023-01-23_12-45-10" src="https://user-images.githubusercontent.com/10925636/214149052-812a428c-63c2-4d11-9046-a0e47604c70f.png">
<img width="535" alt="2023-01-23_12-47-11" src="https://user-images.githubusercontent.com/10925636/214149043-99e21442-e1e2-4820-8675-cd401a6bd0c7.png">

**Comment by strepanier03** [comment] 2023-01-23 21:55
We're going to close this as a not a bug. The behavior being experienced here is expected at this time and it relies on internationalization to be completed on the backend.

**Closed by strepanier03** 2023-01-23 21:55 UTC
Labels: Daily, Bug
