### ISSUE TITLE
Android - Chat - App crashes after creating different chats back to back

### ISSUE THREAD

**Issue by IuliiaHerets** [Expensify/App#51131] opened 2024-10-19 18:41 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 9.0.51-1
**Reproducible in staging?:** Y
**Reproducible in production?:** N
**If this was caught on HybridApp, is this reproducible on New Expensify Standalone?:** Y
**Issue reported by:** Applause Internal Team

## Action Performed:

1. Open the Expensify app.
2. Tap on the FAB.
3. Tap on "Start Chat"
4. Create a new chat (Group, individual, room).
5. Repeat steps a few more times.
6. Verify all the new chats are created properly and the app keeps working smoothly.

## Expected Result:
The app should continue to work smoothly while the user creates new chats back to back.

## Actual Result:
The app crashes after the user creates a few chats back to back.

## Workaround:
Unknown

## Platforms:

- [x] Android: Standalone
- [x] Android: HybridApp
- [ ] Android: mWeb Chrome
- [ ] iOS: Standalone
- [ ] iOS: HybridApp
- [ ] iOS: mWeb Safari
- [ ] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos
[1910_2.txt](https://github.com/user-attachments/files/17446929/1910_2.txt)

https://github.com/user-attachments/assets/b9b3a8a6-1c3d-4f6b-aad3-643ac767dd28

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by IuliiaHerets** [comment] 2024-10-19 18:42
We think that this bug might be related to #wave-collect - Release 1

**Comment by JmillsExpensify** [comment] 2024-10-21 08:02
This is not related to #wave-collect but the app crashing is worrying, so we should look into this one.

**Comment by francoisl** [comment] 2024-10-21 17:16
So far I can't reproduce on the standalone app, going to test with HybridApp.

**Comment by francoisl** [comment] 2024-10-21 20:43
Still trying to build HybridApp in dev, it's extremely slow and I keep running into different errors...

In the meantime I found you can reproduce by just opening and closing the new chat menu multiple times in a row, no need to actually create chats.
So far the diff of recent changes doesn't help understand why the app freezes like this.

**Comment by yuwenmemon** [comment] 2024-10-22 00:40
Closing: https://expensify.slack.com/archives/C9YU7BX5M/p1729557218232369?thread_ts=1729554748.866629&cid=C9YU7BX5M

**Closed by yuwenmemon** 2024-10-22 00:40 UTC
Labels: DeployBlockerCash, Engineering, Daily, Bug
