### ISSUE TITLE
Search - Pay button for held expenses is gray in wide layout, and green in narrow layout

### ISSUE THREAD

**Issue by IuliiaHerets** [Expensify/App#53905] opened 2024-12-11 10:22 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 9.0.74-0
**Reproducible in staging?:** Yes
**Reproducible in production?:** No
**If this was caught on HybridApp, is this reproducible on New Expensify Standalone?:** Yes, reproducible on both
**If this was caught during regression testing, add the test name, ID and link from TestRail:** Exp
**Email or phone of affected tester (no customers):** applausetester+kh1311020@applause.expensifail.com
**Issue reported by:** Applause Internal Team

## Action Performed:
1. Go to staging.new.expensify.com
2. Go to workspace chat.
3. Submit two expenses.
4. Hold one of the expenses.
5. Note that the pay button is gray in main chat and expense report.
6. Go to Search > Outstanding.
7. Note that the pay button is also gray.
8. Switch the layout to narrow layout.

## Expected Result:
The pay button for held expenses should be gray in narrow layout.

## Actual Result:
The pay button for held expenses is gray in wide layout, and green in narrow layout.

## Workaround:
Unknown

## Platforms:
- [x] Android: Standalone
- [x] Android: HybridApp
- [x] Android: mWeb Chrome
- [x] iOS: Standalone
- [x] iOS: HybridApp
- [x] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

https://github.com/user-attachments/assets/b7ad5b66-5455-460a-b983-38c0d9be82c7

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by bernhardoj** [comment] 2024-12-11 10:35
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
Pay button becomes green back when screen is resized to small.

### What is the root cause of that problem?
When the screen is large, we pass the `shouldUseSuccessStyle` correctly.
https://github.com/Expensify/App/blob/c1454f772b8b780e015c01c1bffc4669d5383a78/src/components/SelectionList/Search/ReportListItem.tsx#L204-L214

For for small screen, we forgot to pass `shouldUseSuccessStyle`.
https://github.com/Expensify/App/blob/c1454f772b8b780e015c01c1bffc4669d5383a78/src/components/SelectionList/Search/ReportListItem.tsx#L166-L177

### What changes do you think we should make in order to solve the problem?

Pass `shouldUseSuccessStyle` to `ExpenseItemHeaderNarrow`.
```
shouldUseSuccessStyle={!hasHeldExpenses}
```

### What specific scenarios should we cover in automated tests to prevent reintroducing this issue in the future?

N/A

**Comment by cristipaval** [comment] 2024-12-11 10:50
[This](https://github.com/Expensify/App/pull/53117) seems to be the offending PR. Checking to see if the author is available for a fix in the next few hours

**Comment by luacmartins** [comment] 2024-12-11 15:49
Yes, this is a regression from https://github.com/Expensify/App/pull/53117 cc @NJ-2020 @mananjadhav

**Comment by mananjadhav** [comment] 2024-12-11 16:00
Yes. I already raised a PR and CP to staging.

**Comment by luacmartins** [comment] 2024-12-12 01:17
This is fixed in staging. Closing

**Closed by luacmartins** 2024-12-12 01:17 UTC
Labels: Reviewing, Engineering, Weekly, Bug
