### ISSUE TITLE
[$1000] IOU - Total amount is flashing 3 times after back online

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#12792] opened 2022-11-16 19:23 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Issue found when executing PR** https://github.com/Expensify/App/pull/12488

## Action Performed:
1. Launch the app
2. Log in with any account
3. Send a money request in USD while being online, e.g. $100.
4. Send a second money request in a different currency, e.g. 100 AED.
5. Go offline, cancel the request in AED
6. Go online.

## Expected Result:
The total is updated correctly without changing 3 times

## Actual Result:
Total amount is flashing 3 times after back online

## Workaround:
Unknown

## Platform:

Where is this issue occurring?

- Web
- iOS
- Android
- Desktop App
- Mobile Web

**Version Number:** 1.2.28.1

**Reproducible in staging?:** Yes

**Reproducible in production?:** Yes

**Email or phone of affected tester (no customers):** 

**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Notes/Photos/Videos:** Any additional supporting documentation

https://user-images.githubusercontent.com/93399543/202274520-8ecec063-c9b0-497c-8a9b-259696553888.MP4

**Expensify/Expensify Issue URL:** 

**Issue reported by:** Applause - Internal Team

**Slack conversation:** 

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

## Upwork Automation - Do Not Edit
- Upwork Job URL: https://www.upwork.com/jobs/~01ef6af9374cf4e5ec
- Upwork Job ID: 1594786436731285504

**Comment by maddylewis** [comment] 2022-11-17 13:58
Managing a BUG issue:
- [ ] The bug is not a duplicate report of an existing GH (close the GH and add any novel details to the original GH instead).
- [ ] The bug is reproducible, following the reproduction steps 

- If the GH doesn’t have steps to reliably reproduce the bug and you figure it out, then please add them
- If you’re unable to reproduce the bug:
- Add the Needs reproduction label.
- Comment on the issue outlining the steps you took to try to reproduce the bug, and your results
- Tag the issue reporter and the Applause QA member who created the issue. Ask them to clarify the reproduction steps and/or to check the reproduction steps again. 
- Close issue.


- [ ] The GH template is filled out as fully as possible -- this means the GH body and title are clear (ie. could an external contributor understand it and work on it?)
- [ ] The GH was created by an Expensify employee or a QA tester.
- [ ] If the bug is an OldDot issue, you should decide whether it is widespread enough to justify fixing or if it is better to wait for reunification.
-  If it’s better to wait, close the GH & provide this justification.

- [ ] If there is a Slack link in the OP of the GH (i.e. from #expensify-open-source), review that for more info and check for any discussion about NOT fixing the issue.
- If we decide against the job in Slack convo, link to the Slack conversation in the GH and close the GH with the reason from the Slack convo.
- If the Slack discussion isn't resolved, jump in and push the Slack conversation until we get a consensus on next steps with the GH.


- [ ] Decide if the GH should be resolved by an External contributor or Internal engineer:
- Add the External label if you think it can be worked on by a contributor. Any small, contained, front-end issue in the E/App repo can be handled by contributors.
- Add the Internal label if you think it has to be worked on by an internal Expensify engineer (i.e. backend issues or server-side changes)
- If it’s an issue that is reproducible, has clear reproducible steps, and is Internal, then label it as Demolition
- If unsure, you can apply the Engineering label to auto-assign an internal engineer. They will help decide if it should have the External or Internal label.

_BUG GHs should remain Daily until closed or until the associated PR has been deployed to production and the GH title has been updated with "[HOLD for payment]" where payment is due in 7 days if no regressions._

**Comment by maddylewis** [comment] 2022-11-21 20:16
This issue is mentioned here - https://github.com/Expensify/App/issues/12779.

Added external label to get a fix proposed 👍

**Comment by trjExpensify** [comment] 2022-11-21 20:33
@youssef-lr @mountiny the root cause of this is the same as [this issue](https://github.com/Expensify/App/issues/12781#top), isn't it? 

I don't think we should have separate issues up for this, as we [discuss and look at finding a resolution](https://expensify.slack.com/archives/C01GTK53T8Q/p1668998655170269) to optimistic foreign currency requests.

**Comment by mountiny** [comment] 2022-11-21 23:30
Yes I agree, we should probably keep https://github.com/Expensify/App/issues/12781#top open as there is already lots of discussion. Removing the help wanted for now so contirbutors dont necesarily spend time on this once, this is better to be internal and I think we should close this issue in favour of the linked one.

And make sure that the testing steps from this one are covered in PR fixing https://github.com/Expensify/App/issues/12781#top as well.

@trjExpensify or @youssef-lr if you agree, please feel free to close this issue.

**Comment by trjExpensify** [comment] 2022-11-21 23:49
I agree with that. Will leave this open for @maddylewis, so she can kill the Upwork job when she gets a sec.

**Comment by pufferdev0807** [comment] 2022-11-22 00:05
This is very challengeable problem.
I am very interested about this problem.
Could I work in backend and mobile project?

**Comment by pufferdev0807** [comment] 2022-11-22 00:06
Also could I join your dev slack channel?
pufferdev0807@gmail.com (This is my email address)

**Comment by pufferdev0807** [comment] 2022-11-22 00:12
I've some questions for this issue.
Please contact me asap.

**Comment by mountiny** [comment] 2022-11-22 00:12
Hey @pufferdev0807! Our back end is not open source at the moment, however, you can find all the information about how to contibute to this app or how to get access to the slack channel here https://github.com/Expensify/App/blob/main/contributingGuides/CONTRIBUTING.md

Thank you!

**Comment by mountiny** [comment] 2022-11-22 00:13
For this particular issue, it is better to be handled internally @pufferdev0807. Feel free to look at issues with `Help Wanted` label

**Comment by jasperhuangg** [comment] 2022-11-22 16:51
I can help out with this one! I have experience working on these types of bugs

**Comment by mountiny** [comment] 2022-11-22 16:53
@jasperhuangg check out the linked issue, I think the fix might be tightly connected. Noting just ot make sure the efforts are not duplicated.

**Comment by maddylewis** [comment] 2022-11-22 16:56
and then i'll let @jasperhuangg confirm that https://github.com/Expensify/App/issues/12781#top is a dupe and Jasper will work on a fix over there before closing the issue.

**Comment by jasperhuangg** [comment] 2022-11-22 19:49
I'm still trying to track down where each of the amounts are originating from. But I suspect this issue has something to do with some faulty optimistic data somewhere.

**Comment by jasperhuangg** [comment] 2022-11-22 20:00
One thing I am noticing is that the API command we call `RequestMoney` calls a function in PHP that doesn't seem to return a valid Onyx update, more discussion in [this thread](https://expensify.slack.com/archives/C03TQ48KC/p1669147036740159?thread_ts=1669138395.631579&cid=C03TQ48KC)

**Comment by mvtglobally** [comment] 2022-11-30 05:04
Issue not reproducible during KI retests. (First week)

**Comment by maddylewis** [comment] 2022-12-13 14:05
@youssef-lr - let me know where we're at with this checklist whenever you have a chance. thanks! 

>- [ ] [@Santhosh-Sellavel / @youssef-lr] The PR that introduced the bug has been identified. Link to the PR:
>- [ ] [@Santhosh-Sellavel / @youssef-lr] The offending PR has been commented on, pointing out the bug it caused and why, so the author and reviewers can learn from the mistake. Link to comment:
>- [ ] [@Santhosh-Sellavel / @youssef-lr] A discussion in #expensify-bugs has been started about whether any other steps should be taken (e.g. updating the PR review checklist) in order to catch this type of bug sooner. Link to discussion:
>- [ ] [@maddylewis] A [regression test](https://expensify.testrail.io/index.php?/dashboard) has been added or updated so that the same bug will not reach production again. Link to the GH issue for creating the test here:

**Comment by maddylewis** [comment] 2022-12-19 13:29
@youssef-lr + @Santhosh-Sellavel - can you provide an update on the status of this one? thanks!

**Comment by Santhosh-Sellavel** [comment] 2022-12-19 14:32
@youssef-lr Please check, I'm not aware of this. cc: @mountiny I saw you as reviewer.

**Comment by mountiny** [comment] 2022-12-19 14:36
cc @youssef-lr as engineer assigned to this.

**Comment by youssef-lr** [comment] 2022-12-19 15:01
@maddylewis Sorry I missed your comment, I'm gonna update the checklist right away.

**Comment by Santhosh-Sellavel** [comment] 2022-12-23 16:35
Unassign me as I did nothing here!

**Comment by maddylewis** [comment] 2022-12-27 14:29
@youssef-lr - just checking in here to make sure im not missing anything. lmk, if im good to move forward with adding a regression test and ill do that after the holiday break. thanks!

**Comment by mountiny** [comment] 2022-12-29 23:03
Removed the waiting payment label as that was a lie. 

@youssef-lr bumping the checklist 🙇

**Comment by mountiny** [comment] 2023-01-04 13:14
Assigning since Youssef should be ooo for 2 weeks so I will finish this one up later

**Comment by mountiny** [comment] 2023-01-05 13:41
I think this was not really a regression, we had discovered a new usecase for the IOUs. However, this because more clear after making all the IOUs optimistic and after this change https://github.com/Expensify/App/pull/12488

Commented on the PR https://github.com/Expensify/App/pull/12488#issuecomment-1372225638

I think there is no specific test to add to this situation. This is kind of related to any optimistic action and if when coming back online there is some odd behaviour that should be flagged by QA. Nothing to add here, I think we can close it

**Closed by mountiny** 2023-01-05 13:41 UTC
Labels: Reviewing, Engineering, Daily, Internal, Bug
