### ISSUE TITLE
[$500] Workspace - WS name and avatar not updated after changing name in settings

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#35588] opened 2024-02-01 20:25 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.35
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**If this was caught during regression testing, add the test name, ID and link from TestRail:** exploratory around https://github.com/Expensify/App/pull/35214
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** Applause - Internal Team
**Slack conversation:**

## Action Performed:
1. Open the app and log in
2. Create a workspace
3. Navigate to the workspace chat and request money
4. Tap the WS name above the expense preview or in the header
5. Tap "Workspace" > name of the WS
6. Change the name to something else
7. Go back to the Workspace chat

## Expected Result:
The new workspace name is displayed above the expense preview

## Actual Result:
The workspace is not updated, user has to return LHN and then open the WS chat or open the expense and go back to see the updated name

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [x] iOS: Native
- [ ] iOS: mWeb Safari
- [ ] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details> 

https://github.com/Expensify/App/assets/78819774/91d47de1-af65-468d-b6af-68fa45491f2d

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01789739c6d7bf62f5</li>
        <li>Upwork Job ID: 1753152667767562240</li>
        <li>Last Price Increase: 2024-02-01</li>
    </ul>
</details>

**Comment by FitseTLT** [comment] 2024-02-01 20:44
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
WS name and avatar not updated after changing name in settings

### What is the root cause of that problem?
We haven't considered `policyName` and `avatar` when memoizing `REportActionItem`
### What changes do you think we should make in order to solve the problem?

We need to re-render on`policyName` and `avatar` change so we need to considere on memoizing
### What alternative solutions did you explore? (Optional)

**Comment by Santhosh-Sellavel** [comment] 2024-02-02 19:49
Unable to reproduce this on dev

**Comment by zanyrenney** [comment] 2024-02-05 18:33
Can't repro either, i expect we fixed this in the Ideal Nav launch. Closing.

**Closed by zanyrenney** 2024-02-05 18:33 UTC
Labels: External, Daily, Help Wanted, Overdue, Bug
