### ISSUE TITLE
[$500] Web - Receiving an error when trying to add workspace members

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#26134] opened 2023-08-28 21:40 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Opened the desktop app
2. Selected the “SaaStr Annual 2023” Workspace
3. Clicked into Members
4. Attempted to add [speakers@saastrinc.com](mailto:speakers@saastrinc.com) [colleen@saastrinc.com](mailto:colleen@saastrinc.com) and received the error message (screenshot in :thread:)

## Expected Result:
Members should have been added with no issue.

## Actual Result:
Receive error message and cannot add members

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [x] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 1.3.56-4
**Reproducible in staging?:** n/a
**Reproducible in production?:** n/a
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation

![image (17)](https://github.com/Expensify/App/assets/93399543/9afacfdf-e3de-4e94-908b-5e018fe69a62)

**Expensify/Expensify Issue URL:**
**Issue reported by:** @RobertLadue 
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1692718658678559

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~012057fbaf92fe13cc</li>
        <li>Upwork Job ID: 1699603513976864768</li>
        <li>Last Price Increase: 2023-09-21</li>
    </ul>
</details>

**Comment by JmillsExpensify** [comment] 2023-09-07 02:00
Not sure what's going on here and I'm not able to reproduce. That said, I'm going to triage to the community to see if anyone else can get the same result.

**Comment by JmillsExpensify** [comment] 2023-09-13 08:09
@kbecciv Is QA able to reproduce this one? If not, I'm inclined to close it.

**Comment by mvtglobally** [comment] 2023-09-13 17:18
Issue not reproducible during KI retests. (First week)

**Comment by mvtglobally** [comment] 2023-09-28 03:14
Issue not reproducible during KI retests. (Second week)

**Comment by JmillsExpensify** [comment] 2023-10-10 22:55
Issue not reproducible for two weeks. Closing.

**Closed by JmillsExpensify** 2023-10-10 22:55 UTC
Labels: Engineering, Weekly, Internal, Needs Reproduction, Overdue, Bug
