### ISSUE TITLE
[$250] Web/Windows - New Chat/Group Chat- The search box is not cleared when pressing ALT + DELETE

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#10225] opened 2022-08-03 02:52 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Go to staging.new.expensify.com
2. Log in with account
3. Click on Fub menu - New Group
4. Use the arrow keys to go through the search results
5. With the focus somewhere in the middle of the list, update the search input such that there are no results
6. Press ALT + DELETE command

## Expected Result:
The search box is cleared when pressing ALT + DELETE

## Actual Result:
The search box is not cleared when pressing ALT + DELETE

## Workaround:
Unknown

## Platform:

Where is this issue occurring?

- Web
- iOS
- Android
- Desktop App
- Mobile Web

**Version Number:** 1.1.87.8

**Reproducible in staging?:** Yes

**Reproducible in production?:** Yes

**Email or phone of affected tester (no customers):** any

**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Notes/Photos/Videos:** Any additional supporting documentation

https://user-images.githubusercontent.com/93399543/182513848-82abf357-07be-42c4-8d9b-79b35a3cbe5c.mp4

**Expensify/Expensify Issue URL:** 

**Issue reported by:** Applause - Internal Team

**Slack conversation:** 

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by marcaaron** [comment] 2022-08-03 16:21
Hmm? Why would `alt + delete` clear the search box? Open to other perspectives on this, but doesn't seem like anyone is asking for this so it should not be a priority to fix. The user can `ctrl + a` then `delete` if they want to clear an input.

**Comment by kavimuru** [comment] 2022-08-04 12:42
@marcaaron We have a regression step `Verify that the search box is cleared when pressing "ALT + DELETE"`

**Comment by marcaaron** [comment] 2022-08-05 03:15
Interesting. Any more information about when it was added and why? This might help figure out what caused the regression.

**Comment by kevinksullivan** [comment] 2022-08-05 22:43
https://www.upwork.com/jobs/~016f63cd7edab2e672

**Comment by tgolen** [comment] 2022-08-08 16:12
Before getting proposals on this, I am in the same boat as @marcaaron. Where does the alt+delete test come from in the first place? It doesn't make very much sense. I tried some quick searching, but couldn't come up with anything.

**Comment by tgolen** [comment] 2022-08-09 22:08
Cool, I agree!

**Comment by isagoico** [comment] 2022-08-15 01:00
For context, the steps were discussed and added in this ticket https://github.com/Expensify/Expensify/issues/217359 - Maybe @roryabraham can give more info on the `ALT + DEL` function.

**Comment by roryabraham** [comment] 2022-08-15 16:50
Oh, my mistake. On macOS `option + del` is used to delete whole words at a time. This test looks like it's using a windows machine, and I'm not sure what the windows equivalent is. A platform-agnostic equivalent might be: "Highlight the current search query and press backspace to delete it all at once".

This QA step did not come from nowhere though, so I don't think we should just remove it. During our testing there was [a crash that was reproducible only when you deleted a whole word at a time](https://github.com/Expensify/App/issues/9671#issuecomment-1174032482).

**Comment by tgolen** [comment] 2022-08-22 14:33
OK, @isagoico what do you think about changing the test to this?

> Highlight the current search query and press backspace to delete it all at once

**Comment by tgolen** [comment] 2022-08-31 07:45
bump @isagoico ^

**Comment by isagoico** [comment] 2022-08-31 15:59
@tgolen My apologies I had missed the previous tag. TestRail has been updated to reflect this: 
> Highlight the current search query and press backspace to delete it all at once

**Comment by tgolen** [comment] 2022-09-01 07:06
OK, thank you! I'll close this out then.

**Closed by tgolen** 2022-09-01 07:06 UTC
Labels: Exported, External, Engineering, Weekly, Help Wanted
