### ISSUE TITLE
[OldDot Rules Migration] [Polish] [$250] Editing Approver offline does not gray out category but grays out Approver for other categories

### ISSUE THREAD

**Issue by IuliiaHerets** [Expensify/App#49009] opened 2024-09-11 17:22 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 9.0.32-1
**Reproducible in staging?:** Y
**Reproducible in production?:** N/A - new feature, doesn't exist in prod
**If this was caught during regression testing, add the test name, ID and link from TestRail:** Exp https://expensify.testrail.io/index.php?/tests/view/4948337
**Email or phone of affected tester (no customers):** applausetester+kh010901@applause.expensifail.com
**Issue reported by:** Applause Internal Team

## Action Performed:
Precondition:
- Rules are enabled.

1. Go to staging.new.expensify.com
2. Go to workspace settings > Categories.
3. Go offline.
4. Click on any category.
5. Click Approver.
6. Add any approver.
7. Close the RHP.
8. Note that the edited category is not grayed out.
9. Open a different category.
10. Note that Approver field is grayed out when it is not edited.

## Expected Result:
In Step 8. the edited category should be grayed out after modifying Approver field offline.
In Step 10, the Approver field for other categories should not gray out when the categories are untouched.

## Actual Result:
In Step 8. the edited category is not grayed out after modifying Approver field offline.
In Step 10, the Approver field for other categories is gray out when the categories are untouched.

## Workaround:
Unknown

## Platforms:

- [x] Android: Native
- [x] Android: mWeb Chrome
- [x] iOS: Native
- [x] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

https://github.com/user-attachments/assets/6038662c-3db5-4d81-be51-b5c0d5e3ba9c

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~021833957180531669064</li>
        <li>Upwork Job ID: 1833957180531669064</li>
        <li>Last Price Increase: 2024-09-11</li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @eh2077</details>

**Comment by luacmartins** [comment] 2024-09-11 18:08
Might be related to https://github.com/Expensify/App/pull/48171. cc @WojtekBoman @dukenv0307 @marcaaron

**Comment by luacmartins** [comment] 2024-09-11 19:50
@nkdengineer is this a regression from a recent PR?

**Comment by luacmartins** [comment] 2024-09-11 19:50
I'm gonna demote this from being a blocker since it's a minor issue.

**Comment by marcaaron** [comment] 2024-09-11 21:03
>In Step 8. the edited category should be grayed out after modifying Approver field offline.

Hmm I don't feel strongly that we need to do this tbh. Feels fine how it is now.

>In Step 10, the Approver field for other categories should not gray out when the categories are untouched.

This should be fixed.

**Comment by WojtekBoman** [comment] 2024-09-12 06:24
Hi! I can fix that as I'm the author of the PR that caused this regression

**Comment by dylanexpensify** [comment] 2024-09-18 10:46
Nice! Merged

**Comment by dylanexpensify** [comment] 2024-10-07 12:51
Payment summary:

Contributor+: @eh2077 $250 via NewDot

Please apply/request!

**Closed by dylanexpensify** 2024-10-07 12:51 UTC
Labels: Reviewing, External, Engineering, Weekly, Bug

**Comment by eh2077** [comment] 2024-10-10 15:43
Requested in NewDot

**Comment by JmillsExpensify** [comment] 2024-10-11 09:34
$250 approved for @ntdiary
