### ISSUE TITLE
Chat -  Starting a chat with a specific number directs to the "Hmm" page

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#37746] opened 2024-03-05 14:00 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.47.0
**Reproducible in staging?:** y
**Reproducible in production?:** n
**If this was caught during regression testing, add the test name, ID and link from TestRail:** https://expensify.testrail.io/index.php?/tests/view/4381890
**Issue reported by:** Applause - Internal Team

## Action Performed:
1. Launch app
2. Tap fab --- start chat
3. Enter and select +18183305298

## Expected Result:
Starting chat with specific number must not direct to hmm page.

## Actual Result:
Starting chat with specific number directs to hmm page.

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [x] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

https://github.com/Expensify/App/assets/93399543/40eb31cd-1171-43eb-b13a-32fc6968fb5d

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by kbecciv** [comment] 2024-03-05 14:01
We think that this bug might be related to #vip-vsb
CC @quinthar

**Comment by marcochavezf** [comment] 2024-03-05 18:30
I tried to reproduce it on production, and the expected behavior is to show the error inline:

<img width="1431" alt="Screenshot 2024-03-05 at 11 49 44 a m" src="https://github.com/Expensify/App/assets/6829422/edf2962d-9fb7-475c-8ce8-010b87082556">

For some reason we're not inserting the optimistic report in this case. Still investigating

**Comment by roryabraham** [comment] 2024-03-05 18:33
Also, why are we getting a 666 back from OpenReport?

**Comment by marcochavezf** [comment] 2024-03-05 19:25
Ah because we're [not allowing](https://github.com/Expensify/Web-Expensify/blob/d6d4a1cf54bd23747e06a8c4b5468e4ef0997803/lib/User/Utils.php#L541-L549) certain carriers

**Comment by marcochavezf** [comment] 2024-03-05 19:48
Hmm we're calling Onyx.set for the optimistic report two times and the second one is an empty object

<img width="792" alt="Screenshot 2024-03-05 at 1 47 45 p m" src="https://github.com/Expensify/App/assets/6829422/0afbd6a3-dc91-49cd-a9c5-74826ba29d0b">

**Comment by marcochavezf** [comment] 2024-03-05 23:08
This is the [offending PR](https://github.com/Expensify/App/pull/36713). After testing the revert we're not calling `OpenReport` two times and we load the optimistic chat, but we don't show the error after refreshing though:

<img width="1438" alt="Screenshot 2024-03-05 at 5 05 39 p m" src="https://github.com/Expensify/App/assets/6829422/921a16ce-c405-4f94-ab38-349266c1a7d4">

**Comment by marcochavezf** [comment] 2024-03-06 00:36
Fixed [here](https://github.com/Expensify/App/pull/37804)

**Comment by mvtglobally** [comment] 2024-03-06 02:55
Retested on v1.4.47-7 And seeing the error now 
![Screenshot 2024-03-05 at 9 54 29 PM](https://github.com/Expensify/App/assets/43995119/c5faa7d5-9fb6-4bbd-83f5-2f26fe104a2c)

**Comment by roryabraham** [comment] 2024-03-06 05:50
closing this as completed

**Closed by roryabraham** 2024-03-06 05:50 UTC
Labels: Reviewing, Engineering, Weekly
