### ISSUE TITLE
[$1000] Welcome message modal doest not have back button

### ISSUE THREAD

**Issue by kavimuru** [Expensify/App#19903] opened 2023-05-31 18:56 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1.Go to the chat
2.Send a message to user
3.Click on "Reply in thread"
4.Click on thread header > Settings > Welcome message

## Expected Result: 
Welcome message modal/popup should have back button
## Actual Result: 
Welcome message modal doest not have back button

## Workaround:
Can the user still use Expensify without this being fixed? Have you informed them of the workaround?

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [x] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [ ] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 1.3.21-2
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation

<img src="https://github.com/Expensify/App/assets/43996225/2aac28a3-f4c5-47da-89e2-2ec79d02da64" width="40%" height="40%">

https://github.com/Expensify/App/assets/43996225/aea64ab6-2d3a-4147-9118-eebae043dfef

https://github.com/Expensify/App/assets/43996225/29120f71-ae6e-4761-8c06-12b2140a3a8c

**Expensify/Expensify Issue URL:**
**Issue reported by:** @ayazhussain79 
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1685304337659739

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01dabd1979b66a6a86</li>
        <li>Upwork Job ID: 1664671847386869760</li>
        <li>Last Price Increase: 2023-06-02</li>
    </ul>
</details>

**Comment by ahmedGaber93** [comment] 2023-05-31 19:04
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
Welcome message modal doest not have back button.
### What is the root cause of that problem?
The `HeaderWithCloseButton` in ReportWelcomeMessagePage.js doesn't have prop `shouldShowBackButton` to show the back button.
https://github.com/Expensify/App/blob/12d2f3c89de6c0271ae90760de816e198d3e9025/src/pages/ReportWelcomeMessagePage.js#L60-L64

### What changes do you think we should make in order to solve the problem?
add prop `shouldShowBackButton` to `HeaderWithCloseButton` [here](https://github.com/Expensify/App/blob/12d2f3c89de6c0271ae90760de816e198d3e9025/src/pages/ReportWelcomeMessagePage.js#LL60C1-L60C1)

### What alternative solutions did you explore? (Optional)

**Comment by roryabraham** [comment] 2023-06-07 20:29
Thanks @Prince-Mendiratta @parasharrajat 🙇🏼

**Comment by roryabraham** [comment] 2023-06-08 07:57
I think we should pay out @Prince-Mendiratta for their time and then close this out since it's not going to be needed anymore.

**Comment by adelekennedy** [comment] 2023-06-16 03:42
@Prince-Mendiratta just sent you an offer on Upwork!

**Comment by ayazhussain79** [comment] 2023-06-16 06:17
@adelekennedy am i eligible for reporting bonus?

**Comment by roryabraham** [comment] 2023-06-17 02:02
@ayazhussain79 Sorry, the reporting bonus is only paid out when an issue is fixed, and this isn't fixed quite yet.

**Closed** 2023-06-19 18:48 UTC
Labels: Reviewing, External, Daily, Bug

**Comment by JmillsExpensify** [comment] 2023-07-27 23:23
@adelekennedy  Can you please summarize the appropriate individual payments for all parties involved in this issue? This is holding up @rushatgabhane's NewDot payments. More information on this compliance process [in Slack](https://expensify.slack.com/archives/C01SKUP7QR0/p1690321157273869).

**Comment by adelekennedy** [comment] 2023-07-28 05:13
Here is the payment summary:

External issue reporter: @ayazhussain79 $250
Contributor that fixed the issue: @Prince-Mendiratta  $1000
Contributor+ that helped on the issue and/or PR: @parasharrajat  $1000
Upwork Job: https://www.upwork.com/jobs/~01dabd1979b66a6a86


Extra Notes regarding payment:
done! @JmillsExpensify

**Comment by ayazhussain79** [comment] 2023-07-28 06:53
@adelekennedy offer accepted, Thank you

**Comment by ayazhussain79** [comment] 2023-07-28 16:13
what if a PR fixed this issue after i reported so why reporter is not eligible for reporting bonus

**Comment by JmillsExpensify** [comment] 2023-07-29 16:15
Reviewed details for @parasharrajat. These details are accurate based on summary from Business Reviewer and are now approved for payment in NewDot.
