### ISSUE TITLE
[$1000] Desktop - Freshly installed desktop app freezes while 2FA setup

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#21085] opened 2023-06-19 21:33 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
THE APPLICATION MUST BE FRESHLY INSTALLED.
1. Delete any previously installed desktop app ( new dot)
2. now reinstall the Application.
3. go to settings -> security
4. Go to 2FA
5. Copy/Download 2FA codes and hit next
6. Notice that the 2FA page freezes and is shown differently.

## Expected Result:
Smoothness in 2FA page while hitting next after copy/download codes.

## Actual Result:
Freshly installed desktop app freezes while 2FA setup.

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [ ] MacOS / Chrome / Safari
- [x] MacOS / Desktop

**Version Number:** 1.3.26-4

**Reproducible in staging?:** n/a

**Reproducible in production?:** n/a

**If this was caught during regression testing, add the test name, ID and link from TestRail:**

**Email or phone of affected tester (no customers):**

**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/93399543/4be18c32-0d15-4149-9093-65f70acbbcee

**Expensify/Expensify Issue URL:**

**Issue reported by:** @ashimsharma10

**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1686676091848689

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01e8c535ea052ceec1</li>
        <li>Upwork Job ID: 1671507113830830080</li>
        <li>Last Price Increase: 2023-06-21</li>
    </ul>
</details>

**Comment by abdulrahuman5196** [comment] 2023-06-23 15:15
@flaviadefaria  @sonialiap  This is dupe of https://github.com/Expensify/App/issues/21183

This issue(#21085) is the oldest but the newest one(#21183) got proposals and interaction. What should we do? Which one should we close?

Should we close this issue work on the issue where more interactions happened? And identify the first reporter.

**Comment by flaviadefaria** [comment] 2023-06-23 20:54
Thanks, @abdulrahuman5196 I'm checking internally on this and will update here soon.

**Comment by flaviadefaria** [comment] 2023-06-23 21:09
Closing this in favor of https://github.com/Expensify/App/issues/21183. I posted there that @ashimsharma10 should be compensated for reporting the bug.

**Closed by flaviadefaria** 2023-06-23 21:09 UTC
Labels: External, Daily, Needs Reproduction, Help Wanted, Bug
