### ISSUE TITLE
Infinite loading in the preview when uploading a corrupted image

### ISSUE THREAD

**Issue by kavimuru** [Expensify/App#20632] opened 2023-06-12 23:29 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Open any chat within the app.
2. Attach a corrupted file and observe the app reloading infinitely.

## Expected Result: 
When a user attaches a corrupted file as a messaging attachment, the app should display an error message informing the user that the file is corrupted and cannot be attached to the message.                                                                                        
 OR                                                                                                      - The app should prevent the corrupted file from being attached to the message, thus preventing the issue of the app reloading infinitely and causing inconvenience to users.
## Actual Result: 
The app reloads infinitely when a corrupted file is uploaded, causing inconvenience to users.

## Workaround:
Can the user still use Expensify without this being fixed? Have you informed them of the workaround?

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [x] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 1.3.26-3
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation
[screen-capture (63).webm](https://github.com/Expensify/App/assets/43996225/e489f1eb-98d8-48f4-8493-ddc5274c8b0c)

![download (1) (1)](https://github.com/Expensify/App/assets/43996225/4b58bbfa-f460-4b97-8953-257ad8ba05d3)

https://github.com/Expensify/App/assets/43996225/979bc606-b6f9-4952-8835-3fd84f4df333

**Expensify/Expensify Issue URL:**
**Issue reported by:** @tewodrosGirmaA
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1686146178831159

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by s-alves10** [comment] 2023-06-13 04:30
This looks like a dupe of https://github.com/Expensify/App/issues/19728

**Comment by Christinadobrzyn** [comment] 2023-06-13 19:06
Nice catch @s-alves10 asking - https://github.com/Expensify/App/issues/19728#issuecomment-1589872372

**Comment by Christinadobrzyn** [comment] 2023-06-13 20:41
Confirmed dupe https://github.com/Expensify/App/issues/19728#issuecomment-1589919821 Closing without action

**Closed by Christinadobrzyn** 2023-06-13 20:41 UTC
Labels: Daily, Bug
