### ISSUE TITLE
[HOLD for payment 2024-06-28] [$250] Taxes - Selected tax rate for Workspace currency default can be unselected which causes error

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#42854] opened 2024-05-30 17:50 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.77-8
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**If this was caught during regression testing, add the test name, ID and link from TestRail:** https://expensify.testrail.io/index.php?/tests/view/4584734
**Issue reported by:** Applause - Internal Team

## Action Performed:
1. Go to staging.new.expensify.com
2. Go to workspace settings
3. Go to Taxes (enable it if not enabled)
4. Click Settings
5. Click Workspace currency default
6. Click on the selected tax rate

## Expected Result:
App will not unselect the tax rate since Workspace currency default must have a tax rate

## Actual Result:
The selected tax rate is unselected which results in a blank tax rate created with error "Invalid tax for default currency". The error message cannot be dismissed too
After unselecting the tax rate, the tax rate is selected again

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [x] Android: mWeb Chrome
- [x] iOS: Native
- [x] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details> 

https://github.com/Expensify/App/assets/78819774/5f18281f-7bff-460d-bea9-70d23b465646

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01f0cd7866af3328d2</li>
        <li>Upwork Job ID: 1796250642764570624</li>
        <li>Last Price Increase: 2024-06-06</li>
<li>Automatic offers: </li>
<ul>
<li>DylanDylann | Contributor | 102691550</li>
<li>dominictb | Contributor | 102691783</li>
</ul></li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @isabelastisser</details>

**Comment by lanitochka17** [comment] 2024-05-30 17:51
@isabelastisser  FYI I haven't added the External label as I wasn't 100% sure about this issue. Please take a look and add the label if you agree it's a bug and can be handled by external contributors

**Comment by lanitochka17** [comment] 2024-05-30 17:52
We think that this bug might be related to #wave-collect - Release 1

**Comment by DylanDylann** [comment] 2024-06-03 10:27
@cretadn22 I appreciate your effort to make an RCA more correct. Your solution also similar to @Nodebrute and @Krishna2323 

I prefer @dominictb's [proposal](https://github.com/Expensify/App/issues/42854#issuecomment-2142207131) because this is the best pattern to fix this bug in all places. We can also apply this pattern to other pickers if it causes the same bug

🎀👀🎀 C+ reviewed

**Comment by DylanDylann** [comment] 2024-06-06 07:29
> because we sometimes need to deselect the option 

@Krishna2323 For TaxPicker, I don't see any case we need to deselect the option. Thus, I see that @dominictb's proposal makes sense for the TaxPicker. Let's wait for the thought from the internal engineer

**Comment by DylanDylann** [comment] 2024-06-11 04:52
@blimpich Bump on this one

**Comment by blimpich** [comment] 2024-06-11 17:36
Ugh, sorry about this, I accidentally cleared the assigned users from the issue and adding them back mistakenly assigned @DylanDylann as the contributor. My bad. I'm reviewing the discussions here right now. Whoever ends up getting assigned will still be assigned to the contract, I just messed up the automation.

**Comment by blimpich** [comment] 2024-06-11 17:49
Both @Krishna2323's and @dominictb are perfectly valid solutions I think. I lean towards @dominictb's because it allows future engineers more flexibility in how we solve problems like this. The truth is we could solve it either way, but I agree with @dominictb that this will likely help us avoid bugs like this in the future when people use the tax picker.

> Optionally, we should use the same pattern (always have onDismiss) for other Picker-style components and any we add in the future.

Lets leave this part for another day though. I don't think this is important enough to warrant refactoring all of our picker style components.

**Comment by blimpich** [comment] 2024-06-11 17:51
@dominictb please feel free to raise a PR 👍

And apologies this took me so long to get around to reviewing, got lost in my list of issues to look at somehow.

**Comment by DylanDylann** [comment] 2024-06-28 02:20
BugZero Checklist: The PR fixing this issue has been merged! The following checklist ([instructions](https://stackoverflow.com/c/expensify/questions/14574)) will need to be completed before the issue can be closed:

 [@DylanDylann] The PR that introduced the bug has been identified. Link to the PR: **NA**
 [@DylanDylann] The offending PR has been commented on, pointing out the bug it caused and why, so the author and reviewers can learn from the mistake. Link to comment: **NA**
 [@DylanDylann] A discussion in #expensify-bugs has been started about whether any other steps should be taken (e.g. updating the PR review checklist) in order to catch this type of bug sooner. Link to discussion: **NA**
 [@DylanDylann] Determine if we should create a regression test for this bug. **Yes**
 [@DylanDylann] If we decide to create a [regression test](https://github.com/Expensify/App/blob/main/contributingGuides/REGRESSION_TEST_BEST_PRACTICES.md) for the bug, please propose the regression test steps to ensure the same bug will not reach production again.


Regression Test Proposal
1. Go to the app
2. Go to workspace settings
3. Go to Taxes (enable it if not enabled)
4. Click Settings
5. Click Workspace currency default
6. Click on the selected tax rate
7. App will not unselect the tax rate since Workspace currency default must have a tax rate. No error happens
 

Do we agree 👍 or 👎

**Comment by isabelastisser** [comment] 2024-06-28 14:30
@blimpich, can you look at the test regression proposal above? Thanks!

**Comment by isabelastisser** [comment] 2024-06-29 00:53
The payments were processed un Upwork.

**Comment by isabelastisser** [comment] 2024-06-29 01:03
All set!

**Closed by isabelastisser** 2024-06-29 01:03 UTC
Labels: External, Daily, Awaiting Payment, Bug
