### ISSUE TITLE
[Ready for Payment][$250] Android - Chat - On sending attachment+text, on edit url is not shown as hyperlink

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#46491] opened 2024-07-30 12:00 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 9.0.14
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**If this was caught during regression testing, add the test name, ID and link from TestRail:** https://expensify.testrail.io/index.php?/tests/view/4787789
**Email or phone of affected tester (no customers):** N/A
**Issue reported by:** Applause - Internal Team

## Action Performed:
1. Launch app
2. Tap on a report
3. Enter a url + upload a image and send the message
4. Long press and edit the message sent
5. Enter a url and email id along with previous url entered and save the message

## Expected Result:
On sending attachment+text, on edit url must be shown as hyperlink

## Actual Result:
On sending attachment+text, on edit url is not shown as hyperlink

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [ ] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details> 

https://github.com/user-attachments/assets/f2e1f5c9-6203-42f9-873d-fd450f03bf91

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01a793178e3d46661b</li>
        <li>Upwork Job ID: 1821194033275560441</li>
        <li>Last Price Increase: 2024-08-07</li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @JmillsExpensify</details>

**Comment by lanitochka17** [comment] 2024-07-30 12:02
We think that this bug might be related to #vip-vsp

**Comment by JmillsExpensify** [comment] 2024-08-07 14:37
I'll open up this issue for proposal review since we have one already. If it's an easy fix we can address it. Otherwise, I think we should close the issue.

**Comment by getusha** [comment] 2024-08-09 02:13
@bernhardoj I don't see any issues after applying the change too.
But i noticed it's not adding the text before the link as alt attribute of the image

![Screenshot 2024-08-09 at 5 13 06 at night](https://github.com/user-attachments/assets/dfb131ad-5f26-4d01-8e3e-027c142aa8aa)

**Comment by getusha** [comment] 2024-08-09 02:14
Same issue on staging, do you think it's a bug and simple enough to handle it here?

**Comment by bernhardoj** [comment] 2024-08-09 02:25
I can repro that and the img tag itself has the alt attribute,
<img width="469" alt="Screenshot 2024-08-09 at 10 21 32" src="https://github.com/user-attachments/assets/fdcafa45-f663-48ac-bba0-fcb898e608c7">

but our ImageRenderer never uses that (not sure why). We can fix it by passing the alt as `accessibilityLabel` to the image.

**Comment by getusha** [comment] 2024-08-11 10:22
@bernhardoj the solution is working fine, but it's not highlighting the link in the composer if it's placed before the image.

![Screenshot 2024-08-11 at 1 21 20 in the afternoon](https://github.com/user-attachments/assets/bd632b57-2141-40eb-89d5-c0788e597a4c)

**Comment by bernhardoj** [comment] 2024-08-12 02:40
@getusha we would need to update the live markdown to use the new update from expensify-common. You can test it locally by updating `node_modules/@expensify/react-native-live-markdown/lib/parser/react-native-live-markdown-parser.js` and search for the "autolink" rule.

<img width="1086" alt="image" src="https://github.com/user-attachments/assets/b58e07b4-5be0-4ccc-870f-a1a8a2b3ed8c">

**Comment by getusha** [comment] 2024-08-14 09:37
@bernhardoj's [proposal](https://github.com/Expensify/App/issues/46491#issuecomment-2258503792) looks good to me.
🎀 👀 🎀 C+ Reviewed!

**Comment by dangrous** [comment] 2024-08-14 15:10
ah okay cool - if we don't have that bug anymore I'm fine with this fix. To double check, though, we should include testing steps for that issue as well as the issue raised here. Assigning!

**Comment by bernhardoj** [comment] 2024-08-15 11:47
expensify-common PR is ready

cc: @getusha

**Comment by dangrous** [comment] 2024-08-19 18:36
Not overdue, https://github.com/Expensify/expensify-common/pull/782 was just merged. I think we need an additional app PR to bump the version to 2.0.76 right?

**Comment by bernhardoj** [comment] 2024-08-20 06:50
We need to bump the version in live markdown first. I have opened the live markdown PR [here](https://github.com/Expensify/react-native-live-markdown/pull/455)

cc: @getusha

**Comment by dangrous** [comment] 2024-08-20 14:46
ah great, I'll take a look at that shortly and merge

**Comment by bernhardoj** [comment] 2024-08-21 03:04
The App PR is ready

cc: @getusha

**Comment by dangrous** [comment] 2024-09-04 14:24
This looks like it was affected by the missing automation on prod deploy. I think we're in the 7 day waiting period @JmillsExpensify? But not sure when it started.

**Comment by dangrous** [comment] 2024-09-09 13:38
I'm pretty sure this one has completed the 7-day regression period, but not 100%. @JmillsExpensify do you know if there's an easy way to confirm? There was discussion about this somewhere...

**Comment by dangrous** [comment] 2024-09-12 16:44
Now this is definitely ready to go.

**Comment by bernhardoj** [comment] 2024-09-24 13:35
Requested in ND.

**Comment by garrettmknight** [comment] 2024-09-25 16:45
**Payment Summary:**
- Contributor: @bernhardoj $250
- Reviewer: @getusha $250

**Comment by JmillsExpensify** [comment] 2024-09-25 17:04
$250 approved for @bernhardoj

**Comment by JmillsExpensify** [comment] 2024-09-26 18:59
@getusha do you mind filling out the BZ checklist?

**Comment by getusha** [comment] 2024-09-29 20:16
BugZero Checklist: The PR fixing this issue has been merged! The following checklist ([instructions](https://stackoverflow.com/c/expensify/questions/14574)) will need to be completed before the issue can be closed:

 [@] The PR that introduced the bug has been identified. Link to the PR: https://github.com/Expensify/expensify-common/pull/661
 [@] The offending PR has been commented on, pointing out the bug it caused and why, so the author and reviewers can learn from the mistake. Link to comment: **N/a**
 [@] A discussion in #expensify-bugs has been started about whether any other steps should be taken (e.g. updating the PR review checklist) in order to catch this type of bug sooner. Link to discussion: **N/a**
 [@] Determine if we should create a regression test for this bug. **No, i don't think this issue is impactful. it's more like an edge case.**
 [@] If we decide to create a regression test for the bug, please propose the [regression test](https://github.com/Expensify/App/blob/main/contributingGuides/REGRESSION_TEST_BEST_PRACTICES.md) steps to ensure the same bug will not reach production again. N/a

**Comment by JmillsExpensify** [comment] 2024-09-30 17:31
$250 approved for @getusha

**Comment by garrettmknight** [comment] 2024-10-02 14:56
$250 approved for @getusha

**Closed** 2024-10-08 10:12 UTC
Labels: Reviewing, External, Weekly, Bug
