### ISSUE TITLE
[HOLD for payment 2023-06-02] [$1000] LHN shows the current user's avatar

### ISSUE THREAD

**Issue by kavimuru** [Expensify/App#19034] opened 2023-05-16 16:31 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:

1. Open new Dot
2. Look at LHN

## Expected Result:
LHN should show list of chats as usual
## Actual Result:
LHN shows the current user's avatar for multiple users

## Workaround:
Can the user still use Expensify without this being fixed? Have you informed them of the workaround?

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [x] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 1.3.14-9
**Reproducible in staging?:** y
**Reproducible in production?:**
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/43996225/d96f3b9b-9c2c-439d-8f34-82582d37dbdd

<img width="960" alt="Untitled" src="https://github.com/Expensify/App/assets/43996225/9b8b0f7f-8dee-4c4e-9c91-1c583f0508b1">

**Expensify/Expensify Issue URL:**
**Issue reported by:** @nathan-mulugeta
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1684140397745389

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~011586e1e3fdb3b8d2</li>
        <li>Upwork Job ID: 1658933570626740224</li>
        <li>Last Price Increase: 2023-05-17</li>
    </ul>
</details>

**Comment by thienlnam** [comment] 2023-05-16 16:37
cc @mountiny @luacmartins This looks related to money requests

**Comment by isabelastisser** [comment] 2023-05-16 16:39
@thienlnam is this supposed to be HOURLY?

**Comment by thienlnam** [comment] 2023-05-16 16:40
Deploy blockers are always set as hourly so we can quickly unblock the deploy,  so this looks correct

**Comment by Nathan-Mulugeta** [comment] 2023-05-16 16:55
To make things a little more clear referring [this slack message](https://expensify.slack.com/archives/C049HHMV9SM/p1684254809821279?thread_ts=1684140397.745389&cid=C049HHMV9SM) could is helpful.

**Comment by tienifr** [comment] 2023-05-18 08:53
## Proposal

### Please re-state the problem that we are trying to solve in this issue.

IOU report LHN shows the wrong avatar.

### What is the root cause of that problem?

Currently we're getting icons based on `ownerEmail` while it should be `managerEmail`.

https://github.com/Expensify/App/blob/a5c47370e4367f652e3e0ccc4568e212abcd88f3/src/libs/SidebarUtils.js#L347

### What changes do you think we should make in order to solve the problem?

Change `ownerEmail` to `managerEmail`:

```javascript
result.icons = ReportUtils.getIcons(result.isTaskReport ? parentReport : report, personalDetails, ReportUtils.getAvatar(personalDetail.avatar, personalDetail.login))
```

### What alternative solutions did you explore? (Optional)

NA

### Result

![image](https://github.com/Expensify/App/assets/113963320/9dc450f6-b356-49b3-a049-89bfe86977e5)

**Comment by tienifr** [comment] 2023-05-19 05:40
Thanks for pointing that out, I've updated the proposal.

**Comment by mountiny** [comment] 2023-05-22 13:40
@tienifr feel free to raise a PR!

@thienlnam all yours

**Comment by isabelastisser** [comment] 2023-05-22 15:19
Not overdue!

**Comment by tienifr** [comment] 2023-05-22 17:30
The PR is ready for review! https://github.com/Expensify/App/pull/19392

**Comment by isabelastisser** [comment] 2023-06-05 14:27
Update:

- Issue reported by: @Nathan-Mulugeta
- C+ review: @thesahindia
- Proposal: [tienifr](https://github.com/tienifr)
- [Tienifr](https://github.com/tienifr)
- Assigned on May 22
- [Merged](https://github.com/Expensify/App/pull/19392) on May 24

The contributors were hired in Upwork; @tienifr, what's your Upwork profile? I can't find you there. Thanks!

**Comment by isabelastisser** [comment] 2023-06-07 19:53
Bump @thesahindia.

**Comment by isabelastisser** [comment] 2023-06-15 16:33
@thesahindia thanks for the context!

@tienifr I issued the payment in Upwork now. Thanks!

**Closed by isabelastisser** 2023-06-15 16:33 UTC
Labels: Reviewing, External, Engineering, Daily, Awaiting Payment, Bug
