### ISSUE TITLE
Web -IOU - Money sent is displayed in Account B after refresh the page

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#14625] opened 2023-01-27 15:43 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Go to staging.new.expensify.com
2. Log into newdot from two accounts at the same time (incognito and regular browser)
3. From account A, start a chat with account B
4. From account A request money from Account B
5. As account B, settle the request up using settle up elsewhere
6. Ac account A click +, Send Money to account B
7. Move to account B's screen. Confirm the Money sent is displayed correctly:

## Expected Result:
Money sent is displayed correctly without refresh the page.

## Actual Result:
Money sent is displayed in Account B after refresh the page

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?

- [ ] Web / Chrome

**Version Number:** 1.2.60.0

**Reproducible in staging?:** Yes

**Reproducible in production?:** Yes

**If this was caught during regression testing, add the test name, ID and link from TestRail:**

**Email or phone of affected tester (no customers):**

**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Notes/Photos/Videos:** Any additional supporting documentation

https://user-images.githubusercontent.com/93399543/215127254-af68c92a-d997-4bf3-8104-28b098270271.mp4

**Expensify/Expensify Issue URL:**

**Issue reported by:** Applause - Internal Team

**Slack conversation:**

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by adelekennedy** [comment] 2023-01-30 20:36
I can reproduce this! After doing a quick search I don't see a duplicate of this issue - I also think this can be external but want to check if I'm missing something

**Comment by adelekennedy** [comment] 2023-01-30 20:36
@dangrous check me on this - is the is a good `external` issue?

**Comment by dangrous** [comment] 2023-01-30 20:58
Hey! So I think this IS external BUT it's really a different bug that's still being investigated - see https://expensify.slack.com/archives/C049HHMV9SM/p1674669337825539 - you can see in the video above that it's the same thing, the updates (settling up, etc.) are being updated in the LHN but not in the main window. I'm not 100% sure where the actual bug has been reported or if it's just the discussion in Slack. cc @mountiny and @AndrewGable since you seem to be active in that thread.

**Comment by adelekennedy** [comment] 2023-01-30 22:11
aha!! This is super helpful, I'll hold on adding any labels to this for the moment and follow along in thread

**Comment by dangrous** [comment] 2023-02-06 16:58
Should we maybe put this on [HOLD] for now?

**Comment by dangrous** [comment] 2023-02-08 20:14
Unless you disagree, @adelekennedy, I'm going to go ahead and close this issue, in favor of the broader https://github.com/Expensify/App/issues/14765 which should solve this one as well. I'll make a note in that issue.

Since this was reported internally we don't need to worry about payment or anything either.

Feel free to reopen though if you feel that's better!

**Closed by dangrous** 2023-02-08 20:14 UTC
Labels: Engineering, Daily, Overdue, Bug
