### ISSUE TITLE
[$1000] strikethrough message is displayed with double strikes in inline codeblock

### ISSUE THREAD

**Issue by kavimuru** [Expensify/App#19486] opened 2023-05-23 19:59 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:

1. Open the app
2. Open any report
3. send strikethrough message in inline code block eg: ~`Test`~

## Expected Result: 
App should only display single strike on text when we send message within ~~ as it  normally does for all other type of text
## Actual Result: 
App displays double strike on text when we send single backtick inline codeblock inside ~~

## Workaround:
Can the user still use Expensify without this being fixed? Have you informed them of the workaround?

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android / native
- [x] Android / Chrome
- [x] iOS / native
- [x] iOS / Safari
- [x] MacOS / Chrome / Safari
- [x] MacOS / Desktop

**Version Number:** 1.3.17-0
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/43996225/5b7d4637-b224-44f6-9418-d5abd4661ffa

https://github.com/Expensify/App/assets/43996225/b0652eeb-3c80-464c-b48c-27ae4a975f49

**Expensify/Expensify Issue URL:**
**Issue reported by:** @dhanashree-sawant
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1684591177526859

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~017d3349f2ca4f1a37</li>
        <li>Upwork Job ID: 1663940475067867136</li>
        <li>Last Price Increase: 2023-06-07</li>
    </ul>
</details>

**Comment by bogoroh** [comment] 2023-05-24 03:08
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
There is a double strikethrough happening for codeblocks text blocks.

### What is the root cause of that problem?
This issue is caused because we're applying styling to a <Text /> component and the code block is rendering another <Text /> component that gets the same styling

### What changes do you think we should make in order to solve the problem?
https://github.com/Expensify/App/blob/d7cbeca1e04a838a8a79f22917aa0d55319a99c7/src/components/InlineCodeBlock/index.js#L12

We can actually remove the textStyle from here as it will get passed down to the child component and it will be applied there automatically.
<img width="526" alt="Screenshot 2023-05-23 at 10 06 35 PM" src="https://github.com/Expensify/App/assets/4615263/90a50495-3611-445e-85db-5c81e4cae3fc">


### What alternative solutions did you explore? (Optional)


**Reminder:** Please use plain English, be brief and avoid jargon. Feel free to use images, charts or pseudo-code if necessary. Do not post large multi-line diffs or write walls of text. Do not create PRs unless you have been hired for this job.

**Comment by isabelastisser** [comment] 2023-05-26 14:16
I will review this by EOD.

**Comment by isabelastisser** [comment] 2023-05-30 14:35
I will prioritize this today.

**Comment by isabelastisser** [comment] 2023-05-31 16:04
Reviewing this now.

**Comment by isabelastisser** [comment] 2023-06-02 20:26
not overdue!

**Comment by isabelastisser** [comment] 2023-06-07 16:31
@0xmiroslav any updates?

**Comment by isabelastisser** [comment] 2023-06-07 20:01
I'm reassigning ([SO](https://stackoverflowteams.com/c/expensify/questions/8836)) because I will be OOO until June 14. Thanks!

Once I return from OOO if the chore is still outstanding, I will take over any remaining action items.

**Comment by PauloGasparSv** [comment] 2023-06-09 20:24
Completely missed this, sorry for that!

> Thanks for the proposals everyone. @getusha's [proposal](https://github.com/Expensify/App/issues/19486#issuecomment-1570597501) looks good to me. Other proposals cause regressions - one breaks font, one breaks native
> 
> cc: @tgolen 🎀 👀 🎀 C+ reviewed

Thks @0xmiroslav, agreed!

**Comment by isabelastisser** [comment] 2023-06-15 17:02
taking this back!

**Comment by isabelastisser** [comment] 2023-06-15 17:16
Issue reported by: @dhanashree-sawant
C+ review: @0xmiroslav 
Proposal: @getusha 

I hired you in Upwork now, please accept it, and I will process the payment. Thanks!

**Comment by isabelastisser** [comment] 2023-06-16 17:19
The payments were processed, all set!

**Closed by isabelastisser** 2023-06-16 17:19 UTC
Labels: Reviewing, External, Daily, Bug
