### ISSUE TITLE
[HOLD for payment 2024-03-22] [$500] - MEDIUM - Workspace switcher - WS switcher resets to Expensify when creating a room under the same WS

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#37534] opened 2024-02-29 17:34 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.45-1
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** Applause - Internal Team
**Slack conversation:**

## Action Performed:
1. Go to staging.new.expensify.com
2. Open workspace switcher
3. Select a workspace
4. Go to FAB > Start chat > Room
5. Create a room under the same workspace in Step 2

## Expected Result:
The workspace switcher should be preserved when the room is created since it is under the same workspace

## Actual Result:
The workspace switcher resets to Expensify

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [x] Android: mWeb Chrome
- [x] iOS: Native
- [x] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details> 

https://github.com/Expensify/App/assets/78819774/e488a90c-0963-444f-8a8f-7d611f06248b

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01432a2ba6b78d56dc</li>
        <li>Upwork Job ID: 1764475541802258432</li>
        <li>Last Price Increase: 2024-03-11</li>
<li>Automatic offers: </li>
<ul>
<li>DylanDylann | Contributor | 0</li>
<li>gijoe0295 | Contributor | 0</li>
</ul></li>
    </ul>
</details>

**Comment by lanitochka17** [comment] 2024-02-29 17:36
@bfitzexpensify  FYI I haven't added the External label as I wasn't 100% sure about this issue. Please take a look and add the label if you agree it's a bug and can be handled by external contributors

**Comment by wildan-m** [comment] 2024-03-04 03:41
## Proposal

### Please re-state the problem that we are trying to solve in this issue.

 WS switcher resets to Expensify when creating a room under the same WS

### What is the root cause of that problem?

We are not properly redirect the user here:
https://github.com/Expensify/App/blob/d482a25fc9e9f37990c27c1d5906227eb6204cf2/src/libs/actions/Report.ts#L1830

### What changes do you think we should make in order to solve the problem?

Change 

https://github.com/Expensify/App/blob/d482a25fc9e9f37990c27c1d5906227eb6204cf2/src/libs/actions/Report.ts#L1830

To

```
    Navigation.navigate(ROUTES.REPORT_WITH_ID.getRoute(policyReport.reportID));
```

### What alternative solutions did you explore? (Optional)

**Comment by FitseTLT** [comment] 2024-03-04 09:47
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
MEDIUM - Workspace switcher - WS switcher resets to Expensify when creating a room under the same WS

### What is the root cause of that problem?
The already working logic of redirecting it to the correct route is not working as report we have created optimistically is not ready and `report` is empty object here
https://github.com/Expensify/App/blob/22cb01c968a53407f7a9d864bfba30f41366f6a0/src/libs/Navigation/Navigation.ts#L60-L61
### What changes do you think we should make in order to solve the problem?

To deal with this kind of situation for future too we should start accepting the `report` on `dismissModal` and we will pass the optimistically created report here 
https://github.com/Expensify/App/blob/22cb01c968a53407f7a9d864bfba30f41366f6a0/src/libs/actions/Report.ts#L1845-L1846
We can do that either by converting the `reportID` parameter into `reportOrID` and checking inside the function that if it is string it the reportID and we will fetch the report as we are already doing now
We are already using this logic as in here for e.g.
https://github.com/Expensify/App/blob/22cb01c968a53407f7a9d864bfba30f41366f6a0/src/libs/ReportUtils.ts#L627-L628
### What alternative solutions did you explore? (Optional)

**Comment by wildan-m** [comment] 2024-03-04 10:12
[Proposal Updated ](https://github.com/Expensify/App/issues/37534#issuecomment-1975643398)

add alternative proposal

**Comment by bfitzexpensify** [comment] 2024-03-06 00:52
Proposals ready for review when you get a moment @alitoshmatov - thank you!

**Comment by bfitzexpensify** [comment] 2024-03-08 03:58
Bump @alitoshmatov

**Comment by bfitzexpensify** [comment] 2024-03-12 05:31
Bumped in Slack

**Comment by DylanDylann** [comment] 2024-03-12 09:06
@gijoe0295's proposal looks good to me.
We also do the same thing here
https://github.com/Expensify/App/blob/da7697734c1f759786eba0a643a062b4e39a47ad/src/libs/actions/IOU.ts#L2364

🎀 👀 🎀 C+ reviewed

**Comment by robertjchen** [comment] 2024-03-12 09:16
Makes sense to me, let's move forward with @gijoe0295's proposal.

**Comment by nkdengineer** [comment] 2024-03-12 09:27
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
- WS switcher resets to Expensify when creating a room under the same WS
### What is the root cause of that problem?
- In [here](https://github.com/Expensify/App/blob/d482a25fc9e9f37990c27c1d5906227eb6204cf2/src/libs/Navigation/Navigation.ts#L60), we call dismissModal with report is empty, that leads to shouldOpenAllWorkspace in [here](https://github.com/Expensify/App/blob/d482a25fc9e9f37990c27c1d5906227eb6204cf2/src/libs/Navigation/dismissModalWithReport.ts#L46) return ```true``` 
### What changes do you think we should make in order to solve the problem?
- We need to make sure the ```report``` in [here](https://github.com/Expensify/App/blob/d482a25fc9e9f37990c27c1d5906227eb6204cf2/src/libs/Navigation/Navigation.ts#L60) is always fetched before calling ```originalDismissModalWithReport```.
- We can do it by creating a ```isReadyPromise``` in ReportUtils like the one below:
```
let waitingReportID: string = ''
let resolveIsReadyPromise: (args?: unknown[]) => void;
let isReadyPromise =(reportID: string)=> new Promise((resolve) => {
    waitingReportID = reportID
    resolveIsReadyPromise = resolve;
});

function checkRequiredData() {
    const targetReport = allReports?.[`${ONYXKEYS.COLLECTION.REPORT}${waitingReportID}`] ?? {};
    if(targetReport?.reportID){
        resolveIsReadyPromise();
    }
   
}
Onyx.connect({
    key: ONYXKEYS.COLLECTION.REPORT,
    waitForCollectionCallback: true,
    callback: (value) => {
        allReports = value
        checkRequiredData()
    },
});
```

- Then update:
https://github.com/Expensify/App/blob/d482a25fc9e9f37990c27c1d5906227eb6204cf2/src/libs/Navigation/Navigation.ts#L60-L61
to:
```
    ReportUtils.isReadyPromise(reportID).then(()=>{
        const report = getReport(reportID);
        originalDismissModalWithReport({reportID, ...report}, ref);
    })
```
### What alternative solutions did you explore? (Optional)
- NA

**Comment by nkdengineer** [comment] 2024-03-12 09:29
Sorry for my late. But the dismissModal function is used in a lot of cases in our app so I think we should fix in all cases rather than special case. We you help check my proposal above @DylanDylann  @robertjchen

**Comment by DylanDylann** [comment] 2024-03-22 03:07
BugZero Checklist: The PR fixing this issue has been merged! The following checklist ([instructions](https://stackoverflow.com/c/expensify/questions/14574)) will need to be completed before the issue can be closed:

 [@DylanDylann] The PR that introduced the bug has been identified. Link to the PR: NA
 [@DylanDylann] The offending PR has been commented on, pointing out the bug it caused and why, so the author and reviewers can learn from the mistake. Link to comment: NA
 [@DylanDylann] A discussion in #expensify-bugs has been started about whether any other steps should be taken (e.g. updating the PR review checklist) in order to catch this type of bug sooner. Link to discussion: **NA**
 [@DylanDylann] Determine if we should create a regression test for this bug. **Yes**
 [@DylanDylann] If we decide to create a [regression test](https://github.com/Expensify/App/blob/main/contributingGuides/REGRESSION_TEST_BEST_PRACTICES.md) for the bug, please propose the regression test steps to ensure the same bug will not reach production again.


Regression Test Proposal

1. Open workspace switcher
2. Select a workspace
3. Press FAB > Start chat > Room
4. Create a room under the same workspace in Step 2
5. Verify app does not switch to Expensify and navigates to the room

Do we agree 👍 or 👎

**Comment by bfitzexpensify** [comment] 2024-03-22 18:37
Payments complete, regression test proposed in https://github.com/Expensify/Expensify/issues/381542, we're all done here - thanks everyone!

**Closed by bfitzexpensify** 2024-03-22 18:37 UTC
Labels: External, Weekly, Awaiting Payment, Bug
