### ISSUE TITLE
[HOLD for payment 2023-07-12] [$1000]  2FA - When the "copy code" button is clicked, the download button moves.

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#21566] opened 2023-06-26 13:55 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Go to the "Settings" section.
2. Click on the "Security" option.
3. Click the "Two-factor authentication" feature.
4. Observe that when the "copy code" button is clicked, the download button moves.

## Expected Result:
When the "copy code" button is clicked, the "Download" and "copy code" buttons should not move. Instead they should remain fixed and only the internal data should change.

## Actual Result:
When the "copy code" button is clicked, the "Download" and "copy code" buttons move.

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [x] MacOS / Chrome / Safari
- [x] MacOS / Desktop

**Version Number:** 1.3.30-5
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/93399543/99923596-75fd-4ac6-9926-b47d89bb51af

https://github.com/Expensify/App/assets/93399543/0c07c30e-cba3-407a-a368-b84f7714ced3

**Expensify/Expensify Issue URL:**
**Issue reported by:** @usmantariq96
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1687421108931499

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~014f0d2000a41973c1</li>
        <li>Upwork Job ID: 1673451819177918464</li>
        <li>Last Price Increase: 2023-06-26</li>
    </ul>
</details>

**Comment by Pujan92** [comment] 2023-06-26 18:04
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
2FA copy codes page copy button width gets changed on click

### What is the root cause of that problem?
It seems we don't have provided the correct fixed width to the button and the button Section also gets overlapped to the padding area.

<img width="1437" alt="Screenshot 2023-06-26 at 11 08 35 PM" src="https://github.com/Expensify/App/assets/14358475/94064d8e-7c49-49a0-af11-303f0c493483">

### What changes do you think we should make in order to solve the problem?
As from the [slack discussion](https://expensify.slack.com/archives/C049HHMV9SM/p1687798932849009?thread_ts=1687421108.931499&cid=C049HHMV9SM) fixed-width needs to provide to these buttons and considering the spanish text it requires approx 140px width.

Below changes seems to be required for this.
1) Considering the 140px width of the buttons decrease the padding to restrict overlapping of the content to padding area
https://github.com/Expensify/App/blob/468dd6cd16ef1e19e289558268b42f869a337fd4/src/pages/settings/Security/TwoFactorAuth/CodesPage.js#L81

https://github.com/Expensify/App/blob/468dd6cd16ef1e19e289558268b42f869a337fd4/src/styles/styles.js#L2168-L2176

Update the padding in the order of `ph6`, `ph4` & `ph2`.

2) Provide a width 140px to these buttons
https://github.com/Expensify/App/blob/468dd6cd16ef1e19e289558268b42f869a337fd4/src/styles/styles.js#L2217-L2219

3) After giving more width the content doesn't look in the center, to fix that update `justifyContent: 'space-around'` for `twoFactorAuthCodesContainer`.
https://github.com/Expensify/App/blob/468dd6cd16ef1e19e289558268b42f869a337fd4/src/styles/styles.js#L2197

**Result**

https://github.com/Expensify/App/assets/14358475/86ac0ab2-ce1c-4d99-8ba9-04ba4b8af4b9

<img width="425" alt="Screenshot 2023-06-26 at 11 32 41 PM" src="https://github.com/Expensify/App/assets/14358475/0650006c-aae6-42e5-97d6-eefe914e3f15">


For `VerifyPage` we can also update the width to achieve the same(inspired by above proposal)

**Comment by s77rt** [comment] 2023-06-27 12:05
@namhihi237 Thanks for the proposal. You RCA is correct and the solution looks good to me.

:ribbon: :eyes: :ribbon: C+ reviewed

**Comment by s77rt** [comment] 2023-06-27 12:11
@Pujan92 Thanks for the proposal. Your RCA is not necessary wrong but we don't have to pass a fixed width, we already pass a min-width and we can just adjust that.

**Comment by Pujan92** [comment] 2023-06-27 12:13
Thanks @s77rt , I thought as we want to take out the moving effect we should provide the fixed width. Do you think other point of overlapping the button section makes sense?

**Comment by s77rt** [comment] 2023-06-27 12:24
@Pujan92 I think min-width is enough for this case, the fixed width could back fire if the content is too large, it's better to see the moving effect than the text being cut or being shown in two lines. Not that this case would ever happen just noting. I think it would be okay going either way. Yes the other point makes sense but it's unrelated to this issue.

**Comment by kevinksullivan** [comment] 2023-06-27 15:02
hi @namhihi237 please apply for the job in upwork when you get a chance

https://www.upwork.com/jobs/~014f0d2000a41973c1

**Comment by kevinksullivan** [comment] 2023-06-27 15:14
Sent the offer back @namhihi237

**Comment by s77rt** [comment] 2023-07-04 22:45
Not overdue. PR is merged and deployed to staging

**Comment by s77rt** [comment] 2023-07-05 19:18
- The PR that introduced the bug has been identified: This existed since day one https://github.com/Expensify/App/pull/18576
- The offending PR has been commented on: https://github.com/Expensify/App/pull/18576#discussion_r1253523856
- A discussion in #expensify-bugs has been started: I don't feel this is needed here. This is more like a UI improvement than being a bug
- Determine if we should create a regression test for this bug: No

**Comment by kevinksullivan** [comment] 2023-07-06 21:08
Will pay out after regression period.

**Comment by kevinksullivan** [comment] 2023-07-13 21:36
Paid @s77rt and @namhihi237 . @usmantariq96 sent offer for reporting. Lmk when you accept

**Comment by s77rt** [comment] 2023-07-13 22:15
@kevinksullivan This is not eligible for the 50% bonus. I have refunded the bonus.

**Comment by usmantariq96** [comment] 2023-07-14 03:16
@kevinksullivan Offer accepted.

**Comment by kevinksullivan** [comment] 2023-07-17 15:42
Thanks everyone. Paid @usmantariq96

**Closed by kevinksullivan** 2023-07-17 15:42 UTC
Labels: External, Daily, Overdue, Awaiting Payment, Bug
