### ISSUE TITLE
[HOLD ON #47482][$250] Workspace switcher - Filter is not consistently applied when creating workspace from switcher

### ISSUE THREAD

**Issue by IuliiaHerets** [Expensify/App#47482] opened 2024-08-15 06:27 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** v9.0.20-6
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**Email or phone of affected tester (no customers):** applausetester+kh050806@applause.expensifail.com
**Issue reported by:** Applause Internal Team

## Action Performed:
1. Go to staging.new.expensify.com
2. Open workspace switcher.
3. Select a workspace.
4. Go to Search and then back to Inbox.
5. Open workspace switcher.
6. Click on the Create workspace button.
7. Go back to Inbox.
8. Note that the workspace switcher is reset to Expensify.
9. Go to Search.
10. Note that the workspace switcher is still the workspace selected in Step 3.
11. Go back to Inbox.
12. Now the workspace switcher changes back to the workspace selected in Step 3.

## Expected Result:
The workspace switcher filter should be consistent when selecting a workspace and creating a new workspace from the workspace switcher.

## Actual Result:
In Step 8. after creating a new workspace from the workspace switcher, the filter resets to Expensify.
The filter is not reset in Search page in Step 10.
When returning from Search to Inbox (Step 12), the filter reverts to the one selected in Step 3.

## Workaround:
Unknown

## Platforms:

- [x] Android: Native
- [x] Android: mWeb Chrome
- [x] iOS: Native
- [x] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

https://github.com/user-attachments/assets/ee91535e-b6e6-4719-ab5f-0959e91bdb9a

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~0191bfdce4cbe61eaa</li>
        <li>Upwork Job ID: 1824021164684057828</li>
        <li>Last Price Increase: 2024-08-22</li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @shubham1206agra</details>

**Comment by IuliiaHerets** [comment] 2024-08-15 06:28
We think that this bug might be related to #wave-collect - Release 1

**Comment by IuliiaHerets** [comment] 2024-08-15 06:28
@jliexpensify  FYI I haven't added the External label as I wasn't 100% sure about this issue. Please take a look and add the label if you agree it's a bug and can be handled by external contributors

**Comment by jliexpensify** [comment] 2024-08-15 09:52
I can repro - essentially, when we use the Workspace switcher a second time, it should default to the newly created workspace. Is that correct @IuliiaHerets?

**Comment by BhuvaneshPatil** [comment] 2024-08-15 13:37
I am not able to reproduce it on latest main

**Comment by jliexpensify** [comment] 2024-08-15 23:01
Bump @shubham1206agra to double-check if this can still be reproduced + proposal reviews, thanks!

**Comment by jliexpensify** [comment] 2024-08-21 00:55
Bumping @shubham1206agra again

**Comment by jliexpensify** [comment] 2024-08-23 04:47
Hi @shubham1206agra - [bump on this!](https://github.com/Expensify/App/issues/47482#issuecomment-2292427033) Will also DM you.

**Comment by Kicu** [comment] 2024-08-26 13:24
Hello, I wanted to point out that I have a PR ready that will significantly change how filtering by policyID will work: https://github.com/Expensify/App/pull/47787

I'd suggest to do no work on this bug until ☝️ PR is merged, and most likely this bug will be fixed.

**Comment by jliexpensify** [comment] 2024-08-27 08:26
Done!

**Comment by jliexpensify** [comment] 2024-09-19 23:12
Looks like the other PR was deployed a while back, please retest @IuliiaHerets

**Comment by mvtglobally** [comment] 2024-10-05 03:07
Issue not reproducible during KI retests. (First week)

**Comment by mvtglobally** [comment] 2024-10-14 17:22
Issue not reproducible during KI retests. (Second week)

**Comment by jliexpensify** [comment] 2024-10-14 23:15
Awesome, thanks - closing!

**Closed by jliexpensify** 2024-10-14 23:15 UTC
Labels: External, Monthly, Help Wanted, Bug, retest-weekly
