### ISSUE TITLE
Onboarding - Onboarding modal disappears when navigate to home page

### ISSUE THREAD

**Issue by IuliiaHerets** [Expensify/App#47157] opened 2024-08-09 12:11 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 9.0.18-0
**Reproducible in staging?:** Y
**Reproducible in production?:** N
**If this was caught during regression testing, add the test name, ID and link from TestRail:** https://expensify.testrail.io/index.php?/tests/view/4837595&group_by=cases:section_id&group_order=asc&group_id=229043
**Email or phone of affected tester (no customers):** gocemate+a894@gmail.com
**Issue reported by:** Applause Internal Team

## Action Performed:
1. Sign in as a new gmail user
2. Verify the onboarding modal shows
3. During the onboarding modal navigate to staging.new.expensify.com/home

## Expected Result:
Onboarding modal should display even if the users navigate away or close/reopen the app if the user has not finished it.

## Actual Result:
Onboarding modal disappears when navigate to home page via link

## Workaround:
Unknown

## Platforms:

- [x] Android: Native
- [x] Android: mWeb Chrome
- [ ] iOS: Native
- [x] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

https://github.com/user-attachments/assets/6a75c79c-6d93-474f-a007-692acf443784

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by srikarparsi** [comment] 2024-08-09 17:46
This might be related to this [PR](https://github.com/Expensify/App/pull/46750). Going to revert and test. Also, this is should be frontend so removing the Deploy Blocker label.

**Comment by srikarparsi** [comment] 2024-08-09 18:11
That revert didn't fix it but I was looking around and this issue looks very related to this one [here](https://github.com/Expensify/App/issues/47054) and might be fixed by this [PR](https://github.com/Expensify/App/pull/47097). Asked in the PR

**Comment by srikarparsi** [comment] 2024-08-09 18:20
This is also the [issue](https://github.com/Expensify/App/pull/46559) I believe it might've come from so tagging @DylanDylann and @nkdengineer for visibility.

**Comment by srikarparsi** [comment] 2024-08-09 18:28
This [PR](https://github.com/Expensify/App/pull/47097) will fix this issue. Added a comment [explaining](https://github.com/Expensify/App/pull/47097#issuecomment-2278511690).

**Comment by srikarparsi** [comment] 2024-08-09 20:54
[PR](https://github.com/Expensify/App/pull/47097) merged, being [CPed](https://expensify.slack.com/archives/C07J32337/p1723236786458069)

**Comment by srikarparsi** [comment] 2024-08-12 08:14
Closing this issue since the [PR](https://github.com/Expensify/App/pull/47097) has been fixed and CPed. Payment is being taken care of in this [issue](https://github.com/Expensify/App/issues/47054). (Both issues have the same root cause). Please reopen if I missed something.

**Closed by srikarparsi** 2024-08-12 08:14 UTC
Labels: Engineering, Hourly, Overdue, Bug
