### ISSUE TITLE
[HOLD for payment 2023-02-01] mWeb - Connect Bank account - User can't procced with Chase credentials for special scenario

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#12123] opened 2022-10-25 15:41 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Log in with a applause.expensifail account (that does not have any bank account already added)
2. Enable staging Web secure server in Account Preferences if disabled
3. Navigate to the add bank account modal (Workspace settings > Add bank account)
4. Verify the Add bank account modal is displayed with 2 options to add bank accounts (Log in and Manual)
5. Select the Connect with plaid method to add a bank account
6. On the bank account list select "Chase"
7. You'll be redirected to the "First Platypus Bank"
8. Enter the credentials "user_good / pass_good"
10. If a verification is prompted - select mobile and enter "credentials_good" as the verification mode
11. Checkmark the "Plaid Checking" and "Plaid Saving"
12. Checkmark the 2 options under "additional information you want to share"
13. Click on continue

## Expected Result:
User is able to proceed with Chase credentials for special scenario

## Actual Result:
User can't procced with Chase credentials for special scenario

## Workaround:
Unknown

## Platform:

Where is this issue occurring?

- iOS - blocked to check due to KI
- Android - blocked to check due to KI
- Mobile Web

**Version Number:** 1.2.19.1

**Reproducible in staging?:** Yes

**Reproducible in production?:** n/a

**Email or phone of affected tester (no customers):** 

**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Notes/Photos/Videos:** Any additional supporting documentation

https://user-images.githubusercontent.com/93399543/197819378-dce5db31-1c86-4888-b5bc-3494a40cb5a9.mp4

**Expensify/Expensify Issue URL:** 

**Issue reported by:** Applause - Internal Team

**Slack conversation:** 

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by kbecciv** [comment] 2022-10-25 15:42
Please attached the link to TR for special scenario https://expensify.testrail.io/index.php?/cases/view/1971142

**Comment by PauloGasparSv** [comment] 2022-10-25 22:46
Having some trouble with VBA locally after clearing my db (want to try this locally), will debug this alongside another VBA issue tomorrow morning!

**Comment by PauloGasparSv** [comment] 2022-10-27 21:10
Still couldn't figure out this problem, will ask team for help tomorrow if I keep stuck!

**Comment by PauloGasparSv** [comment] 2022-10-31 19:20
Sorry @neil-marcellini, I think I missclicked the demolition label!

**Comment by PauloGasparSv** [comment] 2022-10-31 19:58
@kbecciv do you mind re-testing this so I can have a new request to take a look at LogSearch?

[My staging failed attempt looks completely different](https://staging.expensify.com/_devportal/tools/logSearch/#query=request_id:(%22762ed70728ce01d6-GRU%22)+AND+timestamp:[2022-10-31T18:36:31.077Z+TO+2022-10-31T20:36:31.077Z]&index=logs_expensify-019285) and locally I can get past the "Choose the account" screen.

**Comment by PauloGasparSv** [comment] 2022-11-03 19:32
@kbecciv just re-tested on my physical device in staging and I did not get the same behavior as the evidence video.

https://user-images.githubusercontent.com/6564265/199816865-e775dda9-a60a-4d74-8542-edb952bdc913.mp4

Can you re-test? And if it fails, can you send me the email of the applause.expensifail account you are using and in which vault it exists, cause I couldn't find it here.

**Comment by kbecciv** [comment] 2022-11-04 15:15
@PauloGasparSv Checking, update you shortly with results

**Comment by kbecciv** [comment] 2022-11-04 15:22
Re-tested with build 1.2.23.9 and had different behavior this time - directed me to log in page.
Credentials used: applausetester+1101abb2@applause.expensifail.com/Feya86Katya

https://user-images.githubusercontent.com/93399543/200011829-b544b92c-dc8f-4c2a-b14a-5be49baf2624.mp4

**Comment by PauloGasparSv** [comment] 2022-11-07 17:53
Still no updates for this today! Will try to get back on this tomorrow.

**Comment by PauloGasparSv** [comment] 2022-11-10 18:22
Still no updates. Asked if someone could take this over [yesterday on engineering-chat](https://expensify.slack.com/archives/C03TQ48KC/p1668022345280149) because I still couldn't find time to work on this : /

**Comment by PauloGasparSv** [comment] 2022-11-14 13:54
No updates!

**Comment by mvtglobally** [comment] 2022-11-16 02:21
Issue not reproducible during KI retests. (First week)

**Comment by PauloGasparSv** [comment] 2022-11-16 19:57
Still no updates from me here!

**Comment by PauloGasparSv** [comment] 2022-11-21 18:51
No updates here!

**Comment by PauloGasparSv** [comment] 2022-11-24 16:23
@kbecciv I could not reproduce the error, but there was a point where the flow was working for me but not on your tests.
Could you please test once again? I know you tested recently.

If the error stops I think we can close this.

**Comment by kbecciv** [comment] 2022-11-27 19:39
@PauloGasparSv Issue is reproduced with build 1.2.32.1

https://user-images.githubusercontent.com/93399543/204156064-0471dd42-58ea-4139-a47f-57e5b278bd37.mp4

**Comment by PauloGasparSv** [comment] 2022-11-28 14:50
Thks for all the help @kbecciv!!!
Pretty sure I'll have time to work on it this week :D

**Comment by PauloGasparSv** [comment] 2022-12-01 20:52
I'm super confused with this issue so far ahahha
Maybe the time of the tests can influence a bit on the result

I tested the connection on staging and it went well:

https://user-images.githubusercontent.com/6564265/205156651-9da9f771-6e9b-4933-9ec8-49c7e8ff3e9c.mov

But I'm investigating why it sends you to the routing number + account number screen, I don't think it should redirect there right?

**Comment by PauloGasparSv** [comment] 2022-12-02 18:52
@ctkochan22 @nkuoch I heard you might be able to help me, can someone take a look at this with me?

I'm not sure if this is the correct behavior for the Chase connection, it is not failing for me but it sends me to the first page of the manual VBA form. I tried debugging but I'm not very sure of how the Plaid connection works.

**Comment by nkuoch** [comment] 2022-12-05 14:44
> But I'm investigating why it sends you to the routing number + account number screen, I don't think it should redirect there right?

It should, because Chase is returning substitute account numbers, so we want to ask them for their real numbers instead.

**Comment by nkuoch** [comment] 2022-12-05 14:44
@kbecciv what email did you test the flow with when testing [here](https://github.com/Expensify/App/issues/12123#issuecomment-1328324392)? So I can maybe find something in the logs

**Comment by mvtglobally** [comment] 2022-12-05 21:26
@PauloGasparSv did you connect the issue on IOS or Android app? Can you please share the video or steps to connect it in Staging with the test data you used?

**Comment by PauloGasparSv** [comment] 2022-12-06 18:46
> @PauloGasparSv FWIW I can also reproduce on mWeb staging with Android. No problem with iOS mWeb though.

Forgot to mention! This confuses me because the error is happening on all platforms for me.

**Comment by PauloGasparSv** [comment] 2022-12-08 17:39
I think the connection errors have stopped, just tested a connection with Plaid on iOS chrome and another with Bank of America on desktop Web.
We are back at [this state](https://github.com/Expensify/App/issues/12123#issuecomment-1334430294).

<img width="200" src="https://user-images.githubusercontent.com/6564265/206523660-eb1cc524-cb7e-4b19-9211-abf23977b2fa.PNG"/>

> @kbecciv what email did you test the flow with when testing https://github.com/Expensify/App/issues/12123#issuecomment-1328324392? So I can maybe find something in the logs

Bump @kbecciv on this : )

**Comment by nkuoch** [comment] 2022-12-12 11:03
Bump @kbecciv

**Comment by kbecciv** [comment] 2022-12-12 14:40
@nkuoch Checking now, will update you shortly

**Comment by kbecciv** [comment] 2022-12-12 14:54
@nkuoch Credentials used:
applausetester+1031abb2@aaplause.expensifail.com/Feya86Katya
User cannot proceed with Chase credentials for special scenario - flow directed to Plaid again.

https://user-images.githubusercontent.com/93399543/207077013-beedb0aa-ae55-49c6-aae2-40c5619dee92.mp4

**Comment by PauloGasparSv** [comment] 2022-12-12 18:45
I'll test this again in my physical device and the Android emulator, but in the iOS Simulator I was able to proceed all the way to the routing and account number page.
I think the credentials had a missing p and an extra a in the email so here they are updated: `applausetester+1031abb2@applause.expensifail.com/Feya86Katya`

https://user-images.githubusercontent.com/6564265/207128426-0ab779ae-7c18-43ca-8aff-5baf256c5bf8.mov

**Comment by kbecciv** [comment] 2022-12-12 19:13
@PauloGasparSv Sorry, over typed the email, updated it

**Comment by nkuoch** [comment] 2022-12-13 09:39
@PauloGasparSv I can take over , I'm currently doing a refactoring of the flow and believe it will fix this too.

**Closed** 2023-02-06 11:19 UTC
Labels: Engineering, Weekly, Overdue, Awaiting Payment
