### ISSUE TITLE
[HOLD for payment 2024-02-14] [$500] Request Money - Previous currency is shown selected if edit Amount&Currency in Request Money

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#33608] opened 2023-12-26 18:41 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.17-1
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** Applause - Internal Team
**Slack conversation:**

## Action Performed:
1. Login to ND Expensify
2. Tap FAB button
3. Tap Request money
4. Select Manual tab
5. Select a currency and enter any amount
6. Tap Next
7. Select an attandee
8. When in final review page, click on Amount field to edit
9. Click on Currency and change to another one
10. Again click on Currency and verify if new selected currency is shown

## Expected Result:
Last selected currency should be shown while editing Request Money

## Actual Result:
Previous currency is shown selected if user changes it while editing Request Money

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [x] Android: mWeb Chrome
- [ ] iOS: Native
- [x] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

![image](https://github.com/Expensify/App/assets/93399543/c409237b-75d2-4cd3-ab2a-835e53939e4f)

https://github.com/Expensify/App/assets/93399543/1a0acf38-8c87-42de-bb9f-25eec97ce702

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~0137f820b6bde4b24a</li>
        <li>Upwork Job ID: 1739718074911305728</li>
        <li>Last Price Increase: 2023-12-26</li>
<li>Automatic offers: </li>
<ul>
<li>hoangzinh | Reviewer | 28076604</li>
<li>shubham1206agra | Contributor | 28076605</li>
</ul></li>
    </ul>
</details>

**Comment by FitseTLT** [comment] 2023-12-26 18:53
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
Request Money - Previous currency is shown selected if edit Amount&Currency in Request Money

### What is the root cause of that problem?
Now we are setting the currency in the route when a new currency is selected to use it in Amount form so there is no way we are getting the updated currency in IOUCurrencyStep
### What changes do you think we should make in order to solve the problem?

we should subscribe to the draft transaction and get the currency data from there
### What alternative solutions did you explore? (Optional)

**Comment by shubham1206agra** [comment] 2023-12-26 19:07
## Proposal
### Please re-state the problem that we are trying to solve in this issue

Request Money - Previous currency is shown selected if edit Amount&Currency in Request Money

### What is the root cause of that problem?

This PR https://github.com/Expensify/App/issues/32826 prohibits the change in `currency` in transaction draft when on confirm page.

### What changes do you think we should make in order to solve the problem?

Add new property `originalCurrency`, and restore it on pressing on back button only. And let `IOU.setMoneyRequestCurrency_temporaryForRefactor(transactionID, option.currencyCode);` run unconditionally

### What alternative solutions did you explore? (Optional)

**Comment by namhihi237** [comment] 2023-12-26 19:33
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
Currency is not updated when edit
### What is the root cause of that problem?
Currently, we get currency from the draft transaction, When we select from the list we don't save anywhere when slect row until we save on the `IOURequestStepAmount` screen.
### What changes do you think we should make in order to solve the problem?
We should pass the query current currency from `IOURequestStepAmount` when open `IOURequestStepCurrency` to show the currency selected before. We will priority show currency from url first and then the draft 

### What alternative solutions did you explore? (Optional)
N/A

**Comment by bfitzexpensify** [comment] 2023-12-28 15:52
Few proposals ready for review @hoangzinh

**Comment by aim-salam** [comment] 2023-12-28 20:58
## Proposal

### Please re-state the problem that we are trying to solve in this issue.

### What is the root cause of that problem?

### What changes do you think we should make in order to solve the problem?


### What alternative solutions did you explore? (Optional)

**Comment by aim-salam** [comment] 2023-12-28 21:06
## Proposal

### Please re-state the problem that we are trying to solve in this issue.

Previous currency is shown selected if edit Amount&Currency in Request Money

### What is the root cause of that problem?

```javascript

``` 

### What changes do you think we should make in order to solve the problem?


### What alternative solutions did you explore? (Optional)

**Comment by aim-salam** [comment] 2023-12-28 21:19
## Proposal

### Please re-state the problem that we are trying to solve in this issue.

Previous currency is shown selected if edit Amount&Currency in Request Money

### What is the root cause of that problem?

https://github.com/Expensify/App/blob/f8d75dcff7279448652e0681c4d8bffbcf49001a/src/pages/iou/request/step/IOURequestStepCurrency.js#L43C1-L43C39

```javascript

``` 

### What changes do you think we should make in order to solve the problem?


### What alternative solutions did you explore? (Optional)

**Comment by aim-salam** [comment] 2023-12-28 21:33
## Proposal

### Please re-state the problem that we are trying to solve in this issue.

Previous currency is shown selected if edit Amount&Currency in Request Money

### What is the root cause of that problem?

Somehow the changes of a new currency didn't update the property of currency in  transactionPropTypes

https://github.com/Expensify/App/blob/f8d75dcff7279448652e0681c4d8bffbcf49001a/src/pages/iou/request/step/IOURequestStepCurrency.js#L43

### What changes do you think we should make in order to solve the problem?

Instead of read currency value from ` transaction: {currency}, ` read currency value from previous page by adding new prop ` route: {
        params: {backTo, iouType, pageIndex, reportID, transactionID,currency},
    }`

https://github.com/Expensify/App/blob/f8d75dcff7279448652e0681c4d8bffbcf49001a/src/pages/iou/request/step/IOURequestStepCurrency.js#L51-L57




### What alternative solutions did you explore? (Optional)

**Comment by aim-salam** [comment] 2023-12-28 23:05
## Proposal

### Please re-state the problem that we are trying to solve in this issue.

Previous currency is shown selected if edit Amount&Currency in Request Money

### What is the root cause of that problem?

Somehow the changes of a new currency didn't update the property of currency in  transactionPropTypes

https://github.com/Expensify/App/blob/f8d75dcff7279448652e0681c4d8bffbcf49001a/src/pages/iou/request/step/IOURequestStepCurrency.js#L43

### What changes do you think we should make in order to solve the problem?

Instead of read currency value from ` transaction: {currency} ` only,  read currency value from both ` transaction: {currency}` and  previous page's prop ` route: {
        params: {backTo, iouType, pageIndex, reportID, transactionID, currency: previousPageCurrency},
    }`

https://github.com/Expensify/App/blob/f8d75dcff7279448652e0681c4d8bffbcf49001a/src/pages/iou/request/step/IOURequestStepCurrency.js#L51-L57


```Javascript 
function IOURequestStepCurrency({
    currencyList,
    route: {
        params: {backTo, iouType, pageIndex, reportID, transactionID,currency: previousPageCurrency}, //<=== added here
    },
  transaction: {currency: originalCurrency}, //<== changed here
}) {

    const currency = previousPageCurrency || originalCurrency; // <=== added here

```

got small changes from other files `IOURequestStepAmount.js` and `ROUTES.ts` that Im not include here.

https://github.com/Expensify/App/assets/142758714/f9b22da5-3ef7-44de-a571-83344963e645





### What alternative solutions did you explore? (Optional)

**Comment by shubham1206agra** [comment] 2023-12-29 07:35
@hoangzinh Proposal updated https://github.com/Expensify/App/issues/33608#issuecomment-1869723704

**Comment by FitseTLT** [comment] 2023-12-29 07:42
@hoangzinh I 'm really sorry for making your job difficult but the reason i didn't notify when updating was because there was no similar proposal on my last update as you can see from the snapshout my last update came 6 min before @namhihi237 commented 👍 
![image](https://github.com/Expensify/App/assets/38649957/919f2701-b2e7-4dc9-9153-e196b8de9d59)
![image](https://github.com/Expensify/App/assets/38649957/850eae94-ffae-418b-a110-6f84e5a8373f)

**Comment by aim-salam** [comment] 2023-12-29 08:08
@hoangzinh proposal updated

**Comment by aim-salam** [comment] 2023-12-29 14:47
@hoangzinh maybe it is the same approach, just different angle how do I present 😅.

Btw, thank you for your comment on my proposal though. It is my first time.

**Comment by shubham1206agra** [comment] 2023-12-29 15:54
> > Add new property originalCurrency, and use it to restore the currency on pressing on back button only.
> 
> Here is the ideal from proposal of @shubham1206agra. It will only restore the currency when click on back button. So this will not work if we open confirm page by deeplink when we're on amount page.
> 
> And my proposal already had the detail enough firstly after this proposal update the explaination.

@dukenv0307 I think the logic is pretty straight forward to my understanding, so I don't think I need to implement whole solution at once.

And didn't we store the whole transaction on draft here. So I don't know the problem here.

**Comment by shubham1206agra** [comment] 2023-12-29 16:24
> Your ideal will not work on this case
> 
>     1. From confirm page click on amount
> 
>     2. Click on currency and change the currency
> 
>     3. On amount page edit the link in the URL to go to confirm page.
> 
> 
> > It will only restore the currency when click on back button
> 
> You will only restore when clicking on back button so this case will not work.

First, I don't know if user will do this at all. And I am not understanding how your proposal will overcome this case.

**Comment by shubham1206agra** [comment] 2023-12-30 01:02
> > And then restore the currency if save method was never hit on this step during unmount method
> 
> @shubham1206agra your proposal suggests backup and restoring `originalCurrency` on mount & unmount lifecycle of `IOURequestStepAmount` component, don't you?

Yes

**Comment by techievivek** [comment] 2024-01-02 05:51
Not overdue. @hoangzinh, should we go forward with @shubham1206agra's proposal, or are there any concerning comments pending to be addressed before moving forward here?

**Comment by techievivek** [comment] 2024-01-02 05:51
Not overdue.

**Comment by aim-salam** [comment] 2024-01-03 03:15
@hoangzinh may I know why u reject the idea of `selectedCurrency` prop from route? I wonder because other page like `IOURequestStepAmount.js` also use the same approach.

https://github.com/Expensify/App/blob/5049f8c604c76bb6e87a70763c3363c4d6b243e7/src/pages/iou/request/step/IOURequestStepAmount.js#L48

**Comment by aim-salam** [comment] 2024-01-03 14:40
@hoangzinh I see. Thank you for the feedback. I'm seeking which part should I improve and learn.

**Comment by bfitzexpensify** [comment] 2024-01-05 20:50
@techievivek think this one is waiting for your review of https://github.com/Expensify/App/issues/33608#issuecomment-1872139894

**Comment by techievivek** [comment] 2024-01-08 08:25
Not overdue, draft PR is up.

**Comment by bfitzexpensify** [comment] 2024-01-08 12:54
Commenting to remove the overdue label, draft PR is up

**Comment by shubham1206agra** [comment] 2024-01-15 17:20
Still deciding the fix to the small Onyx bug in the issue.

**Comment by bfitzexpensify** [comment] 2024-02-14 04:55
Payments complete, @hoangzinh please complete the BZ checklist when you get a moment - thanks!

**Comment by bfitzexpensify** [comment] 2024-02-16 00:58
Thanks @hoangzinh. Agree with those regression steps - added via https://github.com/Expensify/Expensify/issues/370147. 

Let's close this one out.

**Closed by bfitzexpensify** 2024-02-16 00:58 UTC
Labels: External, Engineering, Daily, Awaiting Payment, Bug
