### ISSUE TITLE
[Payment due][$500] Clicking on workspace description does nothing

### ISSUE THREAD

**Issue by m-natarajan** [Expensify/App#36991] opened 2024-02-21 03:27 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.43-2
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** @puneetlath 
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1708458648024739

## Action Performed:
1. Login to app
2. Go to workspace settings as admin
3. Click on profile
4. Add a description
5. Go wo workspace chat
6. Click on the description in the header
## Expected Result:
Should open workspace description settings
## Actual Result:
Nothing happening
## Workaround:
unknown
## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

https://github.com/Expensify/App/assets/38435837/a205dde9-2b6e-4fa7-9177-9933fdcff3f2

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01ba64856c71c7f0c1</li>
        <li>Upwork Job ID: 1760144180944142336</li>
        <li>Last Price Increase: 2024-02-21</li>
<li>Automatic offers: </li>
<ul>
<li>shubham1206agra | Contributor | 0</li>
<li>dukenv0307 | Contributor | 0</li>
</ul></li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @kadiealexander</details>

**Comment by techievivek** [comment] 2024-02-21 06:03
@shubham1206agra I have assigned the GH to you. 🚀

**Comment by techievivek** [comment] 2024-02-21 06:57
I think what you have in video is expected.

**Comment by techievivek** [comment] 2024-02-21 06:59
Both proposals did point out the correct reason, but I find @dukenv0307's proposal to be more complete. So let's go forward with it.

**Comment by chiragsalian** [comment] 2024-02-23 19:49
removing blocked since the PR to fix the issue was CP-d and checked off the QA checklist.

**Comment by kadiealexander** [comment] 2024-03-12 03:41
Payouts due:

- [ ] Contributor: $500 @dukenv0307
- [ ] Contributor+: $500 @shubham1206agra

Upwork job is [here](https://www.upwork.com/jobs/~01ba64856c71c7f0c1).

**Comment by kadiealexander** [comment] 2024-03-12 03:42
**BugZero Checklist:** The PR fixing this issue has been merged! The following checklist ([instructions](https://stackoverflow.com/c/expensify/questions/14574)) will need to be completed before the issue can be closed:

- [ ] [@shubham1206agra] The PR that introduced the bug has been identified. Link to the PR:
- [ ] [@shubham1206agra] The offending PR has been commented on, pointing out the bug it caused and why, so the author and reviewers can learn from the mistake. Link to comment:
- [ ] [@shubham1206agra] A discussion in #expensify-bugs has been started about whether any other steps should be taken (e.g. updating the PR review checklist) in order to catch this type of bug sooner. Link to discussion:
- [ ] [@shubham1206agra] Determine if we should create a regression test for this bug.
- [ ] [@shubham1206agra] If we decide to create a regression test for the bug, please propose the [regression test](https://github.com/Expensify/App/blob/main/contributingGuides/REGRESSION_TEST_BEST_PRACTICES.md) steps to ensure the same bug will not reach production again.
- [ ] [@kadiealexander] Link the GH issue for creating/updating the regression test once above steps have been agreed upon:

**Comment by kadiealexander** [comment] 2024-03-12 03:42
@shubham1206agra please complete the checklist and accept the contract, thanks!

**Comment by kadiealexander** [comment] 2024-03-12 03:49
Sure thing, can you complete the checklist in the meantime?

**Comment by kadiealexander** [comment] 2024-04-08 00:48
Closing as agreed. Noting that @shubham1206agra has not been paid as per https://github.com/Expensify/App/issues/36991#issuecomment-1990089675

**Comment by kadiealexander** [comment] 2024-05-10 06:56
Payouts due:

- [ ] Contributor: $500 @shubham1206agra 

Upwork job is [here](https://www.upwork.com/jobs/~01d6b6fa20644c22d0).

**Closed** 2024-05-10 07:07 UTC
Labels: Reviewing, External, Engineering, Daily, Bug
