### ISSUE TITLE
 Room - Unable to leave public room

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#33010] opened 2023-12-13 20:26 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.12-0
**Reproducible in staging?:** Y
**Reproducible in production?:** N
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** Applause - Internal Team
**Slack conversation:**

## Action Performed:
1. Go to staging.new.expensify.com
2. Click FAB > Start chat > Room
3. Create a public room
4. Go to the public room
5. Click 3-dot menu > Leave
Note that user is unable to leave the room

## Expected Result:
User is able to leave the room

## Actual Result:
User is unable to leave the room. The room changes to Archived and back to normal

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [x] Android: mWeb Chrome
- [x] iOS: Native
- [x] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details> 

https://github.com/Expensify/App/assets/78819774/7a9db4a5-42bf-4c38-9ecc-c39941628613

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by hayata-suenaga** [comment] 2023-12-13 20:41
This is the response for the `LeaveRoom` command.

<img width="500" alt="Screenshot 2023-12-13 at 12 35 58 PM" src="https://github.com/Expensify/App/assets/98560306/3664ccee-d401-4ecc-a33b-d69a01a8d9a0">

This is the response for the `LeaveRoom` command on production

<img width="500" alt="Screenshot 2023-12-13 at 12 40 17 PM" src="https://github.com/Expensify/App/assets/98560306/06b9f53c-fa99-4004-8059-eeda6fbc4d81">

There seems no difference between the two responses, so the issue probably stem from the front end code change.

**Comment by hayata-suenaga** [comment] 2023-12-14 01:16
Yes I already pinged @blazejkustra. Meanwhile if you find a root cause, please feel free to make a fix PR for this @ishpaul777.

**Comment by hayata-suenaga** [comment] 2023-12-14 06:36
waiting for @blazejkustra

**Comment by Julesssss** [comment] 2023-12-14 10:46
Okay, so we still need to fix this, but it's occuring on production and not a blocker. checking it off the [checklist](https://github.com/Expensify/App/issues/32963).

**Comment by Julesssss** [comment] 2023-12-14 10:48
Okay, so we still need to fix this, but it's occuring on production `1.4.11-25` and not a blocker. checking it off the [checklist](https://github.com/Expensify/App/issues/32963): 


https://github.com/Expensify/App/assets/10736861/3218b22f-fcb6-46e7-9202-41ef4868c7b9

**Comment by Julesssss** [comment] 2023-12-14 10:50
Anyway, [this PR](https://github.com/Expensify/App/pull/33053) seems to resolve the issue 👍

**Comment by blazejkustra** [comment] 2023-12-14 10:56
@hayata-suenaga @Julesssss Sorry for late response I finished work yesterday, here is a [PR](https://github.com/Expensify/App/pull/33053) that should fix it. As this is a regression that originated from my TS migration [PR](https://github.com/Expensify/App/pull/28730/files), I fixed it without a proposal. If needed I can post one with more details, just let me know.

**Comment by hayata-suenaga** [comment] 2023-12-15 23:06
Because the PR has been merged, I'll close this issue

**Closed by hayata-suenaga** 2023-12-15 23:06 UTC
Labels: Reviewing, Engineering, Weekly
