### ISSUE TITLE
[$500] Violation error messages are not shown on the expenses for admin account

### ISSUE THREAD

**Issue by kavimuru** [Expensify/App#35031] opened 2024-01-24 06:02 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.30-0
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** @puneetlath 
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1706024549828789

## Action Performed:
1. Create a Collect policy on Newdot, if you do not have one already (steps [here](https://github.com/Expensify/App/pull/34127)) and add at least one non-admin member
2. As a member (non-admin) of the workspace, create an expense with violations
2. Log in as a admin
3. Open the expense report created in step 2 

## Expected Result:
violation error messages appear

## Actual Result:
No error message shown when login as admin

## Workaround:
Can the user still use Expensify without this being fixed? Have you informed them of the workaround?

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

https://github.com/Expensify/App/assets/43996225/f1fb2f8d-45e7-4623-89db-6b83e475d19e

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01431218f64ad15b55</li>
        <li>Upwork Job ID: 1750036395342786560</li>
        <li>Last Price Increase: 2024-01-31</li>
    </ul>
</details>

**Comment by kameshwarnayak** [comment] 2024-01-24 12:53
Unable to reproduce

**Comment by puneetlath** [comment] 2024-01-25 15:34
This happens to me consistently as the approver. Example reportID 563335175022642 from rocio@expensify.com. Transaction reportID 3206138938661089. 

<img width="806" alt="image" src="https://github.com/Expensify/App/assets/1371996/842b88db-7bc0-4be1-832c-db8addfa4266">

**Comment by stephanieelliott** [comment] 2024-01-30 04:53
Still waiting for proposals for this

**Comment by stephanieelliott** [comment] 2024-01-31 23:00
Posted in #expensify-swm to see if we can get an expert contrib to jump on this, since it's affecting us internally. https://expensify.slack.com/archives/C04878MDF34/p1706741963165049

**Comment by SzymczakJ** [comment] 2024-02-01 08:36
Hey! I’m Jakub Szymczak from Software Mansion, an expert agency, and I’d like to work on this issue!

**Comment by SzymczakJ** [comment] 2024-02-01 14:30
I lack information to reproduce this bug. I tried creating Workspace on new-dot but these workspaces don't have tag section. Additionally Category section seems to be not required because it doesn't show 'Missing category" error. How to create a workspace that has a required tag section and has a required category section? Below the screenshot of expense from workspace I created.
<img width="1543" alt="Screenshot 2024-02-01 at 15 29 33" src="https://github.com/Expensify/App/assets/88395093/f568f338-bd37-489d-86f3-0d5ec89208f7">

**Comment by stephanieelliott** [comment] 2024-02-04 18:13
Ah @SzymczakJ the Category and Tag features are only present on Collect workspaces, and not on free workspaces (which is what you created). 

I'll update the repro steps, but also adding the steps to create the Collect workspace here too. If you run into problems, let me know the email you're using and name of the test workspace so I can try and help! 

> 1. Create a collect policy in OldDot
> 2. Execute the following JS snippet in the OldDot policy to enable workspace chats creation:
> if (Url.getCurrentPageName()!="policy" ){ alert('Only run this snippet from a policy editor!'); } else { var p = Policy.getCurrent(); p.policy.isPolicyExpenseChatEnabled = "true"; p.save().done(function(){$.jGrowl('Workspace chat creation enabled!')}); }

**Comment by SzymczakJ** [comment] 2024-02-05 15:58
Great, I managed to reproduce the bug and I'm working to fix it.

**Comment by SzymczakJ** [comment] 2024-02-06 13:08
@stephanieelliott after some research I've found that every update of "request money"(for example change of tag) is triggering a Pusher update  that gives new data to UI. **All data (transaction data, report data, reportActions data, etc.) is sent through pusher except of transactionViolations data which is responsible for showing violation errors**, and that's why we have bugs like this one. **I don't have much knowledge about how Pusher works on backend, so I might be mistaken but I think that making Pusher send transactionViolation data when it changes on the backend would solve this issue.**

**Comment by puneetlath** [comment] 2024-02-06 17:32
cc @cead22 on the above.

**Comment by cead22** [comment] 2024-02-07 01:53
Yeah we need to send transaction violations to clients from backend commands like UpdateMoneyRequestAmountAndCurrency, which I have an issue for

**Comment by SzymczakJ** [comment] 2024-02-07 13:40
@cead22 could you notify me when transaction violations issue is completed? Then I would check if it solves this bug completely

**Comment by stephanieelliott** [comment] 2024-02-08 21:24
Bump @cead22, could you share that transaction violations issue here? Thinking we'll want to hold on that to see if the fix resolves this issue

**Comment by cead22** [comment] 2024-02-09 19:36
The issue is here https://github.com/Expensify/Expensify/issues/361948. I think we can close this issue since we have that one, and the problem in the description of this issue isn't accurate, since violations show for employees, not admins

**Closed by cead22** 2024-02-09 19:36 UTC
Labels: External, Daily, Bug
