### ISSUE TITLE
In magic code input holding down the backspace is not clearing all numbers

### ISSUE THREAD

**Issue by kavimuru** [Expensify/App#19632] opened 2023-05-25 21:24 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:

1. Sign out
2. Enter email
3. In magic code page, enter wrong numbers
4. Try to hold down backspace to remove numbers

## Expected Result:
All numbers should be removed when holding down.
## Actual Result:
When pressing down backspace, not all numbers are removed. Sometimes 1, or 2, or 3 numbers are removed at once.

## Workaround:
Can the user still use Expensify without this being fixed? Have you informed them of the workaround?

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android / native
- [x] Android / Chrome
- [x] iOS / native
- [x] iOS / Safari
- [ ] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 1.3.18-2
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/43996225/d1245a80-4efd-4cc0-8ca5-0adf5c762daa

https://github.com/Expensify/App/assets/43996225/1c768ce1-9cb1-42cb-8296-0f7a543a1e69

https://github.com/Expensify/App/assets/43996225/f828f9c5-a06b-4cf2-bd74-7f938e0b32c2

**Expensify/Expensify Issue URL:**
**Issue reported by:** @alitoshmatov
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1684864290565649

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by trjExpensify** [comment] 2023-05-26 21:32
I can also reproduce this on iOS native and mWeb (safari), so I think broadly a long press on backspace isn't working on mobile devices with a software keyboard.

I noticed this issue we closed recently: https://github.com/Expensify/App/issues/18377#issuecomment-1546762512 

@mananjadhav @mountiny @HarjotSingh8 for some additional input.

**Comment by mountiny** [comment] 2023-05-29 09:43
@trjExpensify @HarjotSingh8 I dont think this is a bug we need to spend time on. Users will usually autofill if using phone number or copy paste and works fine

I think we should do nothing and close this

**Comment by trjExpensify** [comment] 2023-05-30 18:07
That works for me.

**Closed by trjExpensify** 2023-05-30 18:07 UTC
Labels: Daily, Overdue, Bug
