### ISSUE TITLE
[HOLD for #29828] [$500] Scan - "Only visible to you" appears after adding Merchant and Amount to the scanning request

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#31135] opened 2023-11-09 15:54 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.3.97-2
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** Applause - Internal Team
**Slack conversation:**

## Action Performed:
1. Navigate to staging.new.expensify.com
2. Go to workspace chat > + > Request money > Scan
3. Create a Scan request
4. While it is still scanning, go to Scan request details page and enter Merchant and Amount manually
5. Return to expense report

## Expected Result:
"Only visible to you" will not show up because Smartscanning is stopped and user has entered manually the required information

## Actual Result:
"Only visible to you" shows up after manually entering Merchant and Amount

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [x] Android: mWeb Chrome
- [x] iOS: Native
- [x] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details> 

https://github.com/Expensify/App/assets/78819774/4ec140e2-b139-4157-acfb-60855e511d22

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01e973dc2edbfc1c22</li>
        <li>Upwork Job ID: 1722643740994412544</li>
        <li>Last Price Increase: 2023-11-09</li>
    </ul>
</details>

**Comment by kbecciv** [comment] 2023-11-09 16:08
Issue should be fixed https://github.com/Expensify/App/issues/29552, but reproducing again on build 1.3.97.0

**Comment by paultsimura** [comment] 2023-11-11 16:53
This is a BE issue: the selected [proposal](https://github.com/Expensify/App/issues/29552#issuecomment-1762630659) in https://github.com/Expensify/App/issues/29552 included a BE fix, which was apparently not implemented. FE-wise that issue was solved correctly.

**Comment by Victor-Nyagudi** [comment] 2023-11-12 10:09
The reproduction steps here are eerily similar to this other issue. 

- https://github.com/Expensify/App/issues/29828

This [comment](https://github.com/Expensify/App/issues/29828#issuecomment-1792298549) by @trjExpensify on the issue also mentions interrupting the receipt scan, so we could be looking at a dupe here, or maybe the two issues could be merged into one. 

cc: @artus9033 because they're actively working on the other issue.

**Comment by sonialiap** [comment] 2023-11-13 13:24
Nice catch, Victor, this looks suuuuper close to https://github.com/Expensify/App/issues/29828. 

The PR for that one is already up, just waiting for deploy. I'm hoping it solves the issue in this report but rather than close outright, I'm going to put this one on hold and see if I can reproduce the issue reported here once the PR is live.

**Comment by sonialiap** [comment] 2023-11-22 11:53
still on hold for https://github.com/Expensify/App/issues/29828

**Comment by sonialiap** [comment] 2023-12-01 14:26
still on hold for https://github.com/Expensify/App/issues/29828

**Comment by sonialiap** [comment] 2023-12-11 13:22
The PR for the hold issue has been merged and looks like #31135 issue can be tested. I will do so later this week

**Comment by sonialiap** [comment] 2023-12-15 14:38
I can't reproduce, looks like this is resolved ✔️

**Closed by sonialiap** 2023-12-15 14:38 UTC
Labels: External, Weekly, Help Wanted, Bug
