### ISSUE TITLE
[$500] Approve button not displayed by default in the dropdown

### ISSUE THREAD

**Issue by kavimuru** [Expensify/App#38612] opened 2024-03-19 16:24 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.54-0
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:** https://expensify.testrail.io/index.php?/tests/view/4433593
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** applause internal team
**Slack conversation:**

## Action Performed:
1. As an employee submit an expense report to workspace chat
2. Log in as the Admin of the workspace 
3. Navigate to the workspace chat of the employee who submitted the report
4. Observe the button in the report preview

## Expected Result:
`Approve` should be appearing by default in the button which has dropdown

## Actual Result:
`Pay Elsewhere` is displayed by default, user needs to click on drop down menu and then select Approve.

## Workaround:
unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

https://github.com/Expensify/App/assets/43996225/d39eb4fa-cca6-4d53-88c1-0bb57207fccd

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~0167219d0cf776ee3b</li>
        <li>Upwork Job ID: 1770252974466375680</li>
        <li>Last Price Increase: 2024-03-20</li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @mallenexpensify</details>

**Comment by kavimuru** [comment] 2024-03-19 16:24
We think this bug might be related to #wave-collect - Release 1

**Comment by kavimuru** [comment] 2024-03-19 16:25
@mallenexpensify FYI I haven't added the External label as I wasn't 100% sure about this issue. Please take a look and add the label if you agree it's a bug and can be handled by external contributors.

**Comment by mallenexpensify** [comment] 2024-03-20 00:56
Unable to reproduce, the steps in the OP aren't the most clear to me either.  @mananjadhav can you attempt reproduction? If you're able to, can you propose the steps and I'll update the OP? 
Thx

**Comment by mananjadhav** [comment] 2024-03-20 15:56
I am unable to send/request money on staging for my collect policy.  It is asking to update the billing info. Meanwhile, I just manually enabled the condition and I can Approve is in the dropdown.

<img width="1292" alt="image" src="https://github.com/Expensify/App/assets/3069065/aa4ed472-ac15-4820-aa72-9e4611aa8aa2">

**Comment by mananjadhav** [comment] 2024-03-20 15:57
If we plan to go ahead, I think @tienifr's [proposal](https://github.com/Expensify/App/issues/38612#issuecomment-2007629446) looks good to me. All the proposals have the correct RCA and on similar lines.

🎀 👀 🎀 C+ reviewed

**Comment by pecanoro** [comment] 2024-03-21 14:44
We can discuss the proposals once @mallenexpensify can get clarification on what's the expected order of these buttons

**Comment by Victor-Nyagudi** [comment] 2024-03-24 12:03
> I am unable to send/request money on staging for my collect policy. It is asking to update the billing info. Meanwhile, I just manually enabled the condition and I can Approve is in the dropdown.
> 
> <img alt="image" width="1292" src="https://private-user-images.githubusercontent.com/3069065/314571461-aa4ed472-ac15-4820-aa72-9e4611aa8aa2.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTEyODE4NDEsIm5iZiI6MTcxMTI4MTU0MSwicGF0aCI6Ii8zMDY5MDY1LzMxNDU3MTQ2MS1hYTRlZDQ3Mi1hYzE1LTQ4MjAtYWE3Mi05ZTQ2MTFhYThhYTIucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDMyNCUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDAzMjRUMTE1OTAxWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9NmRiZDEwOWJlNTYwYzQzMzY5MWU1ZTg4NGJjN2Y2MDYxNTJkMmRjYzEwMWJmMTg4NDk4MDQ2YjJmOGQwNGY0YyZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.LkJV6jI_5MLUa9qj87kncCq_S-8OpMYng40XjIi_VV8">

@mananjadhav How and where did you manually enable the condition to send/request money on collect policies when there was an error asking you to update your billing info?

**Comment by mallenexpensify** [comment] 2024-03-25 00:44
> I am a bit confused about the expected behavior when there is a preferred payment method

I am also a lil confused. If there is a preferred payment setup in Expensify then I'd imagine that the `Approve` button would show.  If there's not, I can see reasoning for `Pay Elsewhere` cuz approving would do anything.   

So... back to the OP, do we know if a bank account or preferred payment method is setup for the admin or user?

**Comment by pecanoro** [comment] 2024-03-26 19:20
@mallenexpensify Could you ask in product was the desired behaviour? I think neither of us is sure about the expected one

**Comment by mallenexpensify** [comment] 2024-03-27 00:08
Checking on in #qa to see if admin and/or user have bank accounts setup, since I think that would affect expected behaviour 
https://expensify.slack.com/archives/C9YU7BX5M/p1711498027841129

**Comment by mallenexpensify** [comment] 2024-03-27 16:25
From the[ post in #qa](https://expensify.slack.com/archives/C9YU7BX5M/p1711536819285399?thread_ts=1711498027.841129&cid=C9YU7BX5M)
> Neither have bank accounts set up.

I think that's why the expected behaviour **isn't** to show `Approve`.  We show `Pay elsewhere` because it's the only way for the user to get paid back.  If the default was `Approve`, then nothing would happen. Right?

**Comment by pecanoro** [comment] 2024-03-27 16:42
Approve is different from reimburse, a report can be approved a not reimbursed

**Comment by mallenexpensify** [comment] 2024-03-27 22:56
Checking in #expensify-open-source
https://expensify.slack.com/archives/C01GTK53T8Q/p1711580170798549

**Comment by mallenexpensify** [comment] 2024-03-28 19:16
Checking on internally in #qa.  Also, added to #wave-collect because it has to do with approving a payment and that'd first be encountered in that project.

**Comment by mallenexpensify** [comment] 2024-03-29 22:44
Ok! I got double confirmation that we do want to show `Approve`
@mananjadhav can you review the above and provide feedback? Thx

**Comment by mananjadhav** [comment] 2024-03-31 16:47
@mallenexpensify Just confirming we always want to show Approve first irrespective of the preferred payment options?

**Comment by mananjadhav** [comment] 2024-03-31 16:55
Thanks @GandalfGwaihir. I did go through the slack conversation, getting an explicit confirmation here.

**Comment by mallenexpensify** [comment] 2024-03-31 18:39
Confirming [in thread ](https://expensify.slack.com/archives/C01GTK53T8Q/p1711910348071089?thread_ts=1711580170.798549&cid=C01GTK53T8Q)cuz I'm not 100% sure. 

> > Just confirming we always want to show Approve first irrespective of the preferred payment options?
> 
> @Manan Jadhav asked the above. I believe this is :yes: but I'm not certain. If it is not , can drop a comment here or on the GH.  Thx

**Comment by mallenexpensify** [comment] 2024-04-02 21:52
From[ this thread in #expensify-open-source](https://expensify.slack.com/archives/C01GTK53T8Q/p1711580170798549)
>If the setup is:
  > Approvals = enabled
  > Make or track payments = disabled
Then they’d only see an Approve button.

and
> If they have approvals and payments enabled, and the same person is set at the approver and payer, then the default state of the split button would be for Pay and not Approve.

Checking on [in #qa again ](https://expensify.slack.com/archives/C9YU7BX5M/p1712094719663649?thread_ts=1711498027.841129&cid=C9YU7BX5M)to confirm what the testers setup is.

**Comment by mvtglobally** [comment] 2024-04-04 03:25
Issue not reproducible during KI retests. (First week)

**Comment by trjExpensify** [comment] 2024-04-04 18:20
I think this issue can be closed? 

>If they have approvals and payments enabled, and the same person is set at the approver and payer, then the default state of the split button would be for Pay and not Approve.

**Comment by mallenexpensify** [comment] 2024-04-06 00:18
I'm unsure about closing.  The problem I'm running into is that is that I can't find what the below default settings are. 
> Approvals = enabled or disabled
Make or track payments = enabled or disabled

I logged into my test account and tried to find the above in NewDot and OldDot for my collect workspace. I couldn't find either.  

Coming from [here in QA](https://expensify.slack.com/archives/C9YU7BX5M/p1712167702968019?thread_ts=1711498027.841129&cid=C9YU7BX5M)
>Collect policy created in OldDot and all the settings in NewDot were default one.
I guess the bug was reported before these features enabled in newdot
>  > Approvals = enabled or disabled
Make or track payments = enabled or disabled

> Approver and Payer are same person.

**Comment by trjExpensify** [comment] 2024-04-08 17:00
I'm not sure I'm following, sorry. If you're asking how to find these settings in NewDot:

1. Create a workspace (it now creates a `collect` workspace out the gate)
2. Go to the workspace settings (Avatar > Workspaces > click the workspace)
3. Click the "more features" page in the LHN > enable `Workflows`
4. Observe "Add approvals" and "Make or track payments" are disabled by default.

**Comment by mallenexpensify** [comment] 2024-04-10 00:09
Wow... that was a journey. Thanks for the help @trjExpensify and others.  I think my main issue was that I was trying to use a collect workspace from a couple months ago, I needed to create a brand new one. 

> If the setup is:
> Approvals = enabled
> Make or track payments = disabled
> Then they’d only see an Approve button.

Confirming this is the expected and actual behaviour
<img width="1197" alt="image" src="https://github.com/Expensify/App/assets/22508304/afd1e922-f9fa-4733-8312-fbb0542fdd73">

<img width="741" alt="image" src="https://github.com/Expensify/App/assets/22508304/eda946f1-f126-4fd5-848a-30cd1c561461">


Closing 🎉

**Closed by mallenexpensify** 2024-04-10 00:09 UTC
Labels: External, Daily, Help Wanted, Overdue, Bug
