### ISSUE TITLE
[HOLD for payment 2023-09-29] [$500] Web - App does not display address suggestion after clicking 'Fix the errors' link

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#27181] opened 2023-09-11 17:29 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Open the app
2. Click on plus and click on request money
3. Click on distance
4. Open Start/Finish
5. Type in any random text and click on Save
6. Focus back on input, remove the random text and type in text which will trigger suggestions eg: ind
7. When suggestion is open, click on 'Fix the errors' link
8. Observe that suggestion closes, try removing all text and rewrite text that will trigger suggestions and observe that suggestions are not displayed
9. Click in empty space below input to lose focus and again focus on input, observe that now suggestions work fine

## Expected Result:
Fix the errors link should not disable address suggestions

## Actual Result:
 Fix the errors link disables address suggestions in waypoint pages

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [ ] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 1.3.67.2
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/93399543/f1218605-7418-433a-b891-bd885d67ed2c

https://github.com/Expensify/App/assets/93399543/8091edd6-7f4d-4a0b-8521-a82d64de9142

**Expensify/Expensify Issue URL:**
**Issue reported by:** @dhanashree-sawant
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1694107628159709

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~017e44e8bf9e07ab26</li>
        <li>Upwork Job ID: 1701286801034104832</li>
        <li>Last Price Increase: 2023-09-18</li>
<li>Automatic offers: </li>
<ul>
<li>jjcoffee | Reviewer | 26745226</li>
<li>bernhardoj | Contributor | 26745229</li>
<li>dhanashree-sawant | Reporter | 26745230</li>
</ul></li>
    </ul>
</details>

**Comment by abdel-h66** [comment] 2023-09-11 20:48
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
Suggestions list disappears after clicking 'Fix the errors' link

### What is the root cause of that problem?
When clicking fix the errors link, the Text input does not seem to be blurred, as the `onBlur` is never trigerred.  Not sure if this is coming from the Autocomplete lib or something else. 

### What changes do you think we should make in order to solve the problem?

I have found a way to force the blur on the text input when calling `onFixTheErrorsLinkPressed`  
https://github.com/Expensify/App/blob/fd3a753b28e8ba08799160d45402a82035c556c5/src/components/Form.js#L421-L423

By checking if the input is focused, forcing it to go `onBlur` and then call the `focus()` method


```
                            // Focus the input after scrolling, as on the Web it gives a slightly better visual result
                            if (focusInput.focus && typeof focusInput.focus === 'function') {
                                if(focusInput.isFocused()) {
                                    focusInput.blur();
                                }
                                focusInput.focus();
                            }
```

### What alternative solutions did you explore? (Optional)
N/A

**Comment by jjcoffee** [comment] 2023-09-12 15:25
@abdel-h66 To avoid blindly adding fixes where we don't understand the root cause fully, I think it'd be useful to understand why the input is not blurred in this case. Otherwise we risk adding workarounds, rather than solid fixes.

@bernhardoj Hiding the list if we click outside the autocomplete element is the expected behaviour, so we wouldn't want to remove that! I see that clicking `Fix the errors` doesn't blur the input

**Comment by jjcoffee** [comment] 2023-09-15 13:55
@bernhardoj Thanks, that cleared things up for me!

Happy to go with @bernhardoj's [proposal](https://github.com/Expensify/App/issues/27181#issuecomment-1715397222)! The RCA is correct and the solution makes sense.

:ribbon::eyes::ribbon: C+ reviewed

**Comment by Beamanator** [comment] 2023-09-19 03:25
Sorry y'all, looking today!

**Comment by Beamanator** [comment] 2023-09-21 02:25
I didn't close it on purpose, I merged a PR and GH had some automation that auto-closed this :D So thanks for reopening @alexpensify ! 👍

**Comment by alexpensify** [comment] 2023-09-21 18:17
All good! We are back on track now.

**Comment by alexpensify** [comment] 2023-09-29 02:59
Here is the payment summary: 

-  External issue reporter @dhanashree-sawant $50
-  Contributor that fixed the issue @bernhardoj $750
-  Contributor+ that helped on the issue and/or PR @jjcoffee $750

Upwork Job: https://www.upwork.com/jobs/~017e44e8bf9e07ab26

*If applicable, the bonuses will be applied on the final payment 

Extra Notes regarding payment: There is a urgency bonus here and everyone has been paid in Upwork. 

@jjcoffee - please complete the checklist and we can close this GH. Thanks!

**Comment by jjcoffee** [comment] 2023-09-29 09:01
- The PR that introduced the bug has been identified. Link to the PR: https://github.com/Expensify/react-native-google-places-autocomplete/pull/1
- The offending PR has been commented on, pointing out the bug it caused and why, so the author and reviewers can learn from the mistake. Link to comment: https://github.com/Expensify/react-native-google-places-autocomplete/pull/1#issuecomment-1740548272
- A discussion in #expensify-bugs has been started about whether any other steps should be taken (e.g. updating the PR review checklist) in order to catch this type of bug sooner. Link to discussion: **N/A** - this would be a hard one to catch as it happens in pretty specific circumstances
- Determine if we should create a regression test for this bug. **Yes** - it's pretty bad if users can't enter an address.
- If we decide to create a [regression test](https://github.com/Expensify/App/blob/main/contributingGuides/REGRESSION_TEST_BEST_PRACTICES.md) for the bug, please propose the regression test steps to ensure the same bug will not reach production again. **see below**

**Comment by jjcoffee** [comment] 2023-09-29 09:05
**Regression Test Proposal**

1. Click on FAB and click on Request Money.
2. Click on distance.
3. Open Start/Finish.
4. Type in any text in the address input.
5. Press Save without selecting any address. You will get a form error.
6. Focus back on the address input and type some text to trigger suggestions.
7. Click on 'Fix the errors' link.
8. Verify that the suggestions stay open and you can continue typing to trigger further suggestions.

Do we agree 👍 or 👎

**Comment by jjcoffee** [comment] 2023-09-29 09:05
@alexpensify Checklist complete!

**Comment by Beamanator** [comment] 2023-10-02 14:42
Payment should happen soon, we are all coming back from a very busy week :D

**Comment by alexpensify** [comment] 2023-10-02 16:34
Everyone was paid last week - [here](https://github.com/Expensify/App/issues/27181#issuecomment-1740245980). @Beamanator - this GH is open because we need your approval for this regression test: 

https://github.com/Expensify/App/issues/27181#issuecomment-1740556308

**Comment by Beamanator** [comment] 2023-10-03 08:44
Aah i wasn't aware we were waiting on me, sorry :D Regression test looks good!

**Comment by alexpensify** [comment] 2023-10-04 16:42
Closing - the regression test request has been created, so going to close this out here.

**Closed by alexpensify** 2023-10-04 16:42 UTC
Labels: External, Daily, Awaiting Payment, Bug
