### ISSUE TITLE
[HOLD for payment 2023-06-01] [$1000] Mentions results does not close when we change focus

### ISSUE THREAD

**Issue by kavimuru** [Expensify/App#18879] opened 2023-05-12 22:25 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Open the app
2. Open any report
3. Add some text in beginning and add @ and type any letters to get mentions
4. shift focus to start of compose box and observe mentions results are still visible
5. Try same thing with emoji suggestion and observe that suggestions close when we shift focus

## Expected Result:
App should close mention results on shifting focus like it does for emoji suggestions

## Actual Result:
App does not close mention results on shifting focus

## Workaround:
Can the user still use Expensify without this being fixed? Have you informed them of the workaround?

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [x] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [x] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** v1.3.13-1
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/43996225/b97e16bb-cf25-4380-8737-a766fa9e9675

https://github.com/Expensify/App/assets/43996225/e7ff6f36-786c-43bb-96be-3153fd7bf158

**Expensify/Expensify Issue URL:**
**Issue reported by:** @dhanashree-sawant
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1683891760906869

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01f6abecc2436476a9</li>
        <li>Upwork Job ID: 1658751456085680128</li>
        <li>Last Price Increase: 2023-05-17</li>
    </ul>
</details>

**Comment by hungvu193** [comment] 2023-05-16 10:29
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
Mentions results does not close when we change focus
### What is the root cause of that problem?
We are checking if the current selection is smaller than 1 then early return here:
https://github.com/Expensify/App/blob/293f23b57be2bca3f3eb0af903d5e0c2894cb36a/src/pages/home/report/ReportActionCompose.js#L519-L521
When user moves cursor before "@" character, the selection end is now `0`, so the suggestion mentions isn't re-calculated which caused this issue.
### What changes do you think we should make in order to solve the problem?
In stead of early return here and do nothing, we should `resetSuggestion` then return:

```javascript
         if (this.state.selection.end < 1) {
            this.resetSuggestions();
            return;
        }
```

### What alternative solutions did you explore? (Optional)

**Comment by bfitzexpensify** [comment] 2023-05-17 08:28
Reproduced.

**Comment by Santhosh-Sellavel** [comment] 2023-05-17 17:32
Both proposals do not work, the suggestion list sometimes not closing

**Comment by Santhosh-Sellavel** [comment] 2023-05-17 17:48
Yeah I tried both!

**Comment by Santhosh-Sellavel** [comment] 2023-05-18 20:49
Sorry for the confusion @hoangzinh. Not sure why it was behaving weirdly yesterday. 
I tried testing this again, it looks good to me.

@hayata-suenaga 

Let's hire @hoangzinh for this one.

Let's go with resetSuggestions() that's the better approach!

Let me know your thoughts.

C+ Reviewed
👀 🎀 👀

**Comment by hungvu193** [comment] 2023-05-19 00:02
@Santhosh-Sellavel can you review my proposal? i suggested to use resetSuggestion()

**Comment by hungvu193** [comment] 2023-05-19 02:49
Yeah, that seems my mistake 😂 . Nevermind @hoangzinh  👍

**Comment by hayata-suenaga** [comment] 2023-05-19 17:54
@Santhosh-Sellavel thank you for the review. I'm assigning @hoangzinh for this issue

**Comment by bfitzexpensify** [comment] 2023-06-03 07:10
Another friendly bump @Santhosh-Sellavel, I can pay out the C+ contract once the checklist is complete. Thanks!

**Comment by Santhosh-Sellavel** [comment] 2023-06-03 19:19
> **BugZero Checklist:** The PR fixing this issue has been merged! The following checklist ([instructions](https://stackoverflow.com/c/expensify/questions/14574)) will need to be completed before the issue can be closed:
> 
> * [x]  [@Santhosh-Sellavel] The PR that introduced the bug has been identified. Link to the PR: https://github.com/Expensify/App/pull/18469
> * [x]  [@Santhosh-Sellavel] The offending PR has been commented on, pointing out the bug it caused and why, so the author and reviewers can learn from the mistake. Link to comment:  https://github.com/Expensify/App/pull/18469/files#r1215739274
> * [x]  [@Santhosh-Sellavel] A discussion in #expensify-bugs has been started about whether any other steps should be taken (e.g. updating the PR review checklist) in order to catch this type of bug sooner. Link to discussion: This should have been caught in PR Testing based on the checklist.
> * [x]  [@Santhosh-Sellavel] Determine if we should create a regression test for this bug. 
> * [x]  [@Santhosh-Sellavel] If we decide to create a regression test for the bug, please propose the [regression test](https://github.com/Expensify/App/blob/main/contributingGuides/REGRESSION_TEST_BEST_PRACTICES.md) steps to ensure the same bug will not reach production again.
> * [ ]  [@bfitzexpensify] Link the GH issue for creating/updating the regression test once above steps have been agreed upon:

Do we need Regression testing here @puneetlath? I think we don't need here let me know your thoughts and if you differ on anything above, thanks!

**Comment by hayata-suenaga** [comment] 2023-06-04 11:54
@Santhosh-Sellavel although if the same regression occurs it's likely the issue will be caught in other test suites, it will be a good idea to explicitly create a regression test for this

**Comment by bfitzexpensify** [comment] 2023-06-05 12:03
Heading OOO for this week. @johncschuster — we're almost done here, there are two steps remaining:

1. Once @Santhosh-Sellavel proposes the regression steps, we'll need to open an issue to have those added to Testrail
2. We'll then need to pay out @Santhosh-Sellavel via https://www.upwork.com/ab/applicants/1658751456085680128/job-details - he's already been hired. 

Thanks!

**Comment by johncschuster** [comment] 2023-06-05 15:34
Sounds good, @bfitzexpensify!

**Comment by Santhosh-Sellavel** [comment] 2023-06-05 15:44
### Regression Test Steps

1. Open any report
2. Add some text in beginning and add @ and type any letters to get mentions
3. Move cursor to start of compose box
4. Verify that mention suggestions is closed
5. Move cursor to mention text
6. Verify that mention suggestions is open

👍  or 👎 

cc: @hayata-suenaga

**Comment by johncschuster** [comment] 2023-06-06 14:10
Thanks, @puneetlath! Should we capture the suggested regressions steps above, or do we already have a suite of initial testing steps already written?

**Closed** 2023-06-06 14:15 UTC
Labels: External, Daily, Awaiting Payment, Bug
