### ISSUE TITLE
[HOLD for payment 2024-03-29] [$500] Android - IOU - The "Take a photo" background animation is stuck

### ISSUE THREAD

**Issue by kavimuru** [Expensify/App#36551] opened 2024-02-14 23:30 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.41-2
**Reproducible in staging?:** y
**Reproducible in production?:** n
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** applause internal team
**Slack conversation:**

## Action Performed:
1. Reinstall the app
2. Log in for the first time
3. Tap on FAB -> Request money -> Scan

## Expected Result:
The animation should be completed.

## Actual Result:
The "Take a photo" background animation is stuck.

## Workaround:
Can the user still use Expensify without this being fixed? Have you informed them of the workaround?

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [ ] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

https://github.com/Expensify/App/assets/43996225/95de4fc7-5235-4021-94d4-e754abb615cb

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01c2cca67bbda25bba</li>
        <li>Upwork Job ID: 1757910328375115776</li>
        <li>Last Price Increase: 2024-02-21</li>
<li>Automatic offers: </li>
<ul>
<li>mollfpr | Reviewer | 0</li>
<li>aswin-s | Contributor | 0</li>
</ul></li>
    </ul>
</details>

**Comment by marcaaron** [comment] 2024-02-14 23:49
Hmm I have no idea. Seems like it could be related to `expo-image`. The code where this is rendered is here:

https://github.com/Expensify/App/blame/0381d57ab7a127371cdea766e118ce0290be1eaf/src/pages/iou/request/step/IOURequestStepScan/index.native.js#L279-L285

With the most recent change to the file being in [this PR](https://github.com/Expensify/App/pull/35640) (which is on staging).

**Comment by marcaaron** [comment] 2024-02-14 23:58
Doesn't really seem related to those changes though. 

@kavimuru Can we try to re-test this on other Android devices? 

I am curious if this is an expo-image issue. 

cc @Beamanator I think this is not a blocker. The flow looks pretty good on Android without the animation so I think we can pursue a fix without blocking the deploy.

**Comment by marcaaron** [comment] 2024-02-15 00:04
FWIW I was able to repro this. But don't think it looks that bad so removed the blocker.

**Comment by aswin-s** [comment] 2024-02-15 00:18
## Proposal

### Please re-state the problem that we are trying to solve in this issue.

Navigation to RequestMoneyStartPage is stuck when camera permission is requested

### What is the root cause of that problem?

This is possibly related to https://github.com/Expensify/App/pull/35640 where we are requesting camera permission on page load.

https://github.com/Expensify/App/blob/d88bdf3edc766bf16fff7dd4ff9f6d7db20d427c/src/pages/iou/request/step/IOURequestStepScan/index.native.js#L139

However we are not waiting for the navigation animation to finish before requesting for camera permission. This causes the animation to freeze in between.

### What changes do you think we should make in order to solve the problem?


Run permission check only after screen animation is finished,
```tsx
// Check initial camera permission status
 InteractionManager.runAfterInteractions(() => {
   refreshCameraPermissionStatus(true);
 });
```
This ensures that screen animation is not interupted

### What alternative solutions did you explore? (Optional)

None

**Comment by ikevin127** [comment] 2024-02-15 09:40
If this is indeed a regression from PR https://github.com/Expensify/App/pull/35640 I think the PR author should handle the regression fix ♻️

**Comment by mollfpr** [comment] 2024-02-20 17:54
>I also check that the PR recordings on Android seem working just fine. @aswin-s What's the different in this issue?

Friendly bump @aswin-s

**Comment by aswin-s** [comment] 2024-02-21 16:13
@mollfpr Yes the linked PR doesn't seem to be the one causing the issue. However I notice that tapping on request money navigates to either Scan or Manual Request depending on last selection. This was not the original behaviour. Also the issue above seems to be device specific. For me, on first navigation the slide navigation animation is missing when I test on physical device.

**Comment by aldo-expensify** [comment] 2024-02-22 19:25
@aswin-s were you able to reproduce the issue? and, were you able to confirm that the [proposal](https://github.com/Expensify/App/issues/36551#issuecomment-1945132640) fixes it?

**Comment by brandonhenry** [comment] 2024-02-23 04:04
Is this still accepting proposals?

**Comment by aswin-s** [comment] 2024-02-23 06:48
> @aswin-s were you able to reproduce the issue? and, were you able to confirm that the [proposal](https://github.com/Expensify/App/issues/36551#issuecomment-1945132640) fixes it?

Not able to reproduce this anymore

**Comment by mollfpr** [comment] 2024-02-23 19:09
![Screenshot_1708715109](https://github.com/Expensify/App/assets/25520267/017262df-f528-4b0d-a618-6c8bd8647b08)

It reproduces on my emulator. `v1.4.43-14 Develop`.

**Comment by mollfpr** [comment] 2024-02-23 19:23
Adding `InteractionManager.runAfterInteractions` looks like resolves the issue.

>However we are not waiting for the navigation animation to finish before requesting for camera permission. This causes the animation to freeze in between.

I think it's better to use `CONST.ANIMATED_TRANSITION` for certainty animation timing.

**Comment by marcaaron** [comment] 2024-02-27 02:41
>I'm not sure about this, but my understanding is that @marcaaron stated this wasn't regression from that PR.

Sorry, I said it should not block the deploy not that it wasn't a regression. I do think we should assign it back to whoever caused it or at least ask them for help. But seeing as that PR was merged a month ago let's get a new one up from anyone.

@mollfpr Can we assign anyone yet?

**Comment by mollfpr** [comment] 2024-02-27 09:44
>However I notice that tapping on request money navigates to either Scan or Manual Request depending on last selection. This was not the original behaviour. Also the issue above seems to be device specific. For me, on first navigation the slide navigation animation is missing when I test on physical device.

@aswin-s I don't understand if the above statement is related to the root cause. Could you elaborate?

@marcaaron I am still unsure of the root cause of @aswin-s proposal. It is the screen stuck because the alert didn't wait for the animation screen to finish. But this results differently when the navigation tab is open on the manual request.

https://github.com/Expensify/App/assets/25520267/91c545ca-8922-42e5-9f64-2db609efd711

The animation screen is also stuck on the distance request.

https://github.com/Expensify/App/assets/25520267/68a36a3d-2d57-4703-8d6b-7bfb47a8470b

**Comment by aswin-s** [comment] 2024-02-27 10:55
@mollfpr I'm now able to consistently able to reproduce the bug in simulator. All I had to do was force stop the app and set camera permission to 'Always ask'.

Root cause for the issue is https://github.com/Expensify/App/issues/34750 itself. Before this PR camera permission was not requested on load. Rather permission was requested while tapping on the 'Continue' button on Permission message.

![image](https://github.com/Expensify/App/assets/6880914/01d3a8cd-2211-4fa4-aae1-71df303f1c6c)

The behaviour was modified to match web platform. More details in this thread and slack:
https://github.com/Expensify/App/issues/34750#issuecomment-1910964516
https://expensify.slack.com/archives/C01GTK53T8Q/p1706132155733569

After the PR permission dialog is shown on page load itself. And it is not waiting for screen animation to complete.


> I think it's better to use CONST.ANIMATED_TRANSITION for certainty animation timing.

Also I've verified that useFocusEffect instead of useEffect along with `InteractionManager.runAfterInteractions` fixes the above issue. If we use a fixed time like `CONST.ANIMATED_TRANSITION` we'll have to use a setTimeout instead. React-navigation itself suggests the [former method](https://reactnavigation.org/docs/use-focus-effect/#delaying-effect-until-transition-finishes).

I've [updated my proposal](https://github.com/Expensify/App/issues/36551#issuecomment-1945132640) to use `useFocusEffect` instead of a useEffect.

**Comment by aswin-s** [comment] 2024-02-27 10:57
Using useFocusEffect also ensures that the camera permission dialog is only shown when scan tab is active and not on manual request or location tabs.

**Comment by mollfpr** [comment] 2024-02-27 12:14
>It is the screen stuck because the alert didn't wait for the animation screen to finish. But this results differently when the navigation tab is open on the manual request.

I found a reason for this. The component scan request is rendered after the manual request, so that's still time for the manual request screen to finish the animation. However, this seems odd to me that we asking permission for a manual request.

The latest [proposal](https://github.com/Expensify/App/issues/36551#issuecomment-1945132640) from @aswin-s  looks good to me! I'm okay with using `useFocusEffect`, it also makes the permission show when the scan request tab is active and it seems recommended from the library.

🎀 👀 🎀 C+ reviewed!

**Comment by kevinksullivan** [comment] 2024-03-01 05:09
Moving forward with @aswin-s 's proposal

**Comment by aswin-s** [comment] 2024-03-04 11:56
@kevinksullivan this issue not assigned to me yet.

**Comment by aswin-s** [comment] 2024-03-04 11:57
oh sorry we're waiting for @marcaaron. Got confused there.

**Comment by mvtglobally** [comment] 2024-03-05 04:49
Issue not reproducible during KI retests. (First week)

**Comment by mollfpr** [comment] 2024-03-12 12:06
https://github.com/Expensify/App/assets/25520267/172fe8f8-dbd0-4bf8-9f39-0b83c732b51c

I still can see the screen stuck a little bit.

**Comment by mollfpr** [comment] 2024-04-01 19:30
> [@mollfpr] The PR that introduced the bug has been identified. Link to the PR:
 [@mollfpr] The offending PR has been commented on, pointing out the bug it caused and why, so the author and reviewers can learn from the mistake. Link to comment:

I don't think any PR is causing the issue.

> [@mollfpr] A discussion in #expensify-bugs has been started about whether any other steps should be taken (e.g. updating the PR review checklist) in order to catch this type of bug sooner. Link to discussion:

The regression step should be enough.

>[@mollfpr] Determine if we should create a regression test for this bug.
 [@mollfpr] If we decide to create a regression test for the bug, please propose the [regression test](https://github.com/Expensify/App/blob/main/contributingGuides/REGRESSION_TEST_BEST_PRACTICES.md) steps to ensure the same bug will not reach production again.

1. Reinstall the app on a native device
2. Log in for the first time
3. Tap on FAB -> Request money -> Scan
4. Verify that the screen transition animation is smooth and not interrupted in the middle by the camera permission dialog
5. 👍 or 👎 

---

@kevinksullivan Could you create the payment summary? Thank you!

**Comment by mollfpr** [comment] 2024-04-10 17:18
Friendly bump @kevinksullivan

**Comment by mollfpr** [comment] 2024-04-16 17:39
Friendly bump @kevinksullivan

**Comment by kevinksullivan** [comment] 2024-04-30 15:19
Payment summary:
- C+: @mollfpr - $500 (NewDot)
- Contributor: @aswin-s $500

**Closed by kevinksullivan** 2024-04-30 15:19 UTC
Labels: Engineering, Weekly, Internal, Awaiting Payment, Bug
