### ISSUE TITLE
Log in -  Deeplinks to Desktop App don’t work with any browser

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#26446] opened 2023-08-31 23:09 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Open Desktop App
2. Enter a new account and press Continue
3. Copy the Magic link from validation email and change it to staging
4. Open a new tab and navigate to the staging magic link
5. Verify the user is prompted to open the desktop app

## Expected Result:
The user can open the Desktop App using a deeplink from the browser

## Actual Result:
No prompt to open Desktop App. Deeplinks to Desktop App don’t work with any browser

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [x] MacOS / Chrome / Safari
- [x] MacOS / Desktop

**Version Number:** 1.3.60-1

**Reproducible in staging?:** Yes

**Reproducible in production?:** Yes

**If this was caught during regression testing, add the test name, ID and link from TestRail:**

**Email or phone of affected tester (no customers):**

**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/78819774/b362dcf6-d69f-4b33-bd52-72302bae753e

**Expensify/Expensify Issue URL:**

**Issue reported by:** Applause - Internal team

**Slack conversation:**

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by pradeepmdk** [comment] 2023-09-01 01:46
we already have this https://github.com/Expensify/App/issues/25790

**Comment by maddylewis** [comment] 2023-09-05 14:03
closing as dupe/intended behavior - https://github.com/Expensify/App/issues/25790#issuecomment-1701737460

**Closed by maddylewis** 2023-09-05 14:03 UTC
Labels: Daily, Overdue, Bug
