### ISSUE TITLE
[HOLD for payment 2024-02-15] [$500] Bank Account - On Test transactions page, invalid amount error displayed when value is less than 0.005

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#34535] opened 2024-01-15 20:53 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.25-1
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** Applause - Internal Team
**Slack conversation:**

## Action Performed:
Pre-requisite: user should be logged in and have created a workspace.
1. Go to Settings > Workspaces > Select a workspace > Bank account.
2. Select the Manual method to add a bank account.
3. Go trough the add back account flow until you reach the Test transactions page.
4. Try to enter a value less than 0.005 in the value fields.

## Expected Result:
The user should be able to enter any value amount.

## Actual Result:
The user can not enter values less than 0.005.

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [x] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

https://github.com/Expensify/App/assets/93399543/26c3ae11-a688-4a3b-a6ab-67a904181ccb

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~014e3048efb731d9bc</li>
        <li>Upwork Job ID: 1746999099054366720</li>
        <li>Last Price Increase: 2024-01-22</li>
<li>Automatic offers: </li>
<ul>
<li>akinwale | Reviewer | 28121605</li>
<li>tienifr | Contributor | 28121606</li>
</ul></li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @kevinksullivan</details>

**Comment by akinwale** [comment] 2024-01-22 08:41
Started a [Slack conversation](https://expensify.slack.com/archives/C01GTK53T8Q/p1705912856852199) to verify if this is worth fixing.

**Comment by akinwale** [comment] 2024-01-24 06:55
After reviewing the proposals, we can move forward with @tienifr's [proposal](https://github.com/Expensify/App/issues/34535#issuecomment-1893002132).

🎀👀🎀 C+ reviewed.

**Comment by amyevans** [comment] 2024-01-25 14:45
Thanks for raising in Slack @akinwale and I agree with where this landed. Let's move forward with the proposal from @tienifr

**Comment by anmurali** [comment] 2024-02-16 15:40
@akinwale can you please add regression test if applicable and complete that bug zero checklist?
I have processed payments but I am OOO till 29th. Once the BZ checklist and regression test is added, the backup BZ assignee can close this!

**Comment by kevinksullivan** [comment] 2024-02-22 19:13
Bump on the checklist @akinwale . Once that's handled I will pay this out.

**Comment by akinwale** [comment] 2024-02-22 19:16
> Bump on the checklist @akinwale . Once that's handled I will pay this out.

This is already paid. I will take care of the checklist in a bit.

**Comment by akinwale** [comment] 2024-02-27 03:30
> * [x]  [@akinwale] The PR that introduced the bug has been identified. Link to the PR:
> * [x]  [@akinwale] The offending PR has been commented on, pointing out the bug it caused and why, so the author and reviewers can learn from the mistake. Link to comment:
> * [x]  [@akinwale] A discussion in #expensify-bugs has been started about whether any other steps should be taken (e.g. updating the PR review checklist) in order to catch this type of bug sooner. Link to discussion:

Not a regression. This is more of an edge-case with the way JavaScript handles decimal values and rounding.

> * [x]  [@akinwale] Determine if we should create a regression test for this bug.
> * [x]  [@akinwale] If we decide to create a regression test for the bug, please propose the [regression test](https://github.com/Expensify/App/blob/main/contributingGuides/REGRESSION_TEST_BEST_PRACTICES.md) steps to ensure the same bug will not reach production again.

**Regression Test Steps**
1. Launch the Expensify app
2. Navigate to Workspaces > Select a workspace > Bank account
3. Select "Connect manually" to start the bank account flow
4. Go through the bank account flow until the Test transactions step
5. Enter any amount greater than `0.005`, but less than `0.01`.
6. Verify that the invalid amount error is displayed.
7. Enter any amount with two decimal places.
8. Verify that no error message is displayed.

Do we agree 👍 or 👎?

**Comment by amyevans** [comment] 2024-03-06 01:03
@kevinksullivan I think this one is ready for payment!

**Comment by amyevans** [comment] 2024-03-14 19:15
Ah wait, rereading the history it looks like this has been paid, so I'm going to close it out.

**Closed by amyevans** 2024-03-14 19:15 UTC
Labels: External, Weekly, Awaiting Payment, Bug
