### ISSUE TITLE
[P2P Activation] [CRITICAL] Web - "Pay with Expensify" button is prompting the user to choose bank account or debit card, when they already have an existing bank account linked to their account.

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#29714] opened 2023-10-16 20:42 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.3.84.9
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** @kevinksullivan 
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1697481375175609

## Action Performed:
1. User A: login, navigate to Settings > Wallet
2. User A: add personal bank account
3. User B: login, select Request money
4. User B: enter User A as the person you're requesting from
5. User A: Navigate to IOU from User B
6. User A: select Pay with Expensify

## Expected Result:
User A should go straight to Additional details step, rather than prompting the user to choose a bank account or debit card if they already have a connected payment method

## Actual Result:
User A is prompted to choose between bank account and debit card, even though they have a bank account added. Then, if they choose bank account, they're asked to add a new one.

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos
<details>
<summary>Android: Native</summary>

</details>

<details>
<summary>Android: mWeb Chrome</summary>

</details>

<details>
<summary>iOS: Native</summary>

</details>

<details>
<summary>iOS: mWeb Safari</summary>

</details>

<details>
<summary>MacOS: Chrome / Safari</summary>

 
![image (11)](https://github.com/Expensify/App/assets/93399543/1f27a5db-f0a8-40ad-b828-ad540096ccea)
![image (10)](https://github.com/Expensify/App/assets/93399543/fdd14f2c-492f-4fcc-bf45-ce0c2dfeba85)

https://github.com/Expensify/App/assets/93399543/f51248b7-08e5-434a-b55f-3da424e081d5

</details>

<details>
<summary>MacOS: Desktop</summary>

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01f0f7b78b540bf02c</li>
        <li>Upwork Job ID: 1714019025148497920</li>
        <li>Last Price Increase: 2023-10-16</li>
    </ul>
</details>

**Comment by kevinksullivan** [comment] 2023-10-16 22:04
Note: I am also seeing this issue when I try to make a payment while having an upgraded wallet and a bank account. 

![IMG_78B37CA61763-1](https://github.com/Expensify/App/assets/22508290/76d5faf5-f4c5-4eec-942d-9c30a9e7cf01)

**Comment by akinwale** [comment] 2023-10-17 12:11
> btw @kevinksullivan this issue is not ready for contributors, isn't it?

The Help Wanted label was actually removed so I guess not.

In any case, I have been unable to reproduce the issue on the latest main branch.

**Comment by MariaHCD** [comment] 2023-10-17 12:26
I tested on `main` as well. Adding a PBA and then trying to pay via the wallet opens the KYC flow as expected:

https://github.com/Expensify/App/assets/12268372/761e721d-8344-4a72-a641-2eadd7b35437

**Comment by MariaHCD** [comment] 2023-10-17 12:36
We use [PaymentUtils.hasExpensifyPaymentMethod](https://github.com/Expensify/App/blob/a456ef90fe1998d289a892a98578a9ab0f5a5f28/src/libs/PaymentUtils.ts#L20) to check if there's already a valid bank account. As far as I can see, the `isDefault` prop in the Onyx `bankAccountList` data is available so hasExpensifyPaymentMethod should work as expected. Doing some more testing.

**Comment by MariaHCD** [comment] 2023-10-17 12:44
Tested on desktop:

https://github.com/Expensify/App/assets/12268372/383fb8a3-9192-469a-80b0-24e4518c91c6

And android as well:

https://github.com/Expensify/App/assets/12268372/656edd6e-f2b6-4f9f-9b3e-f6e7a43e9b44

Seems to work as expected. Going to try on staging.

**Comment by MariaHCD** [comment] 2023-10-17 12:53
Same on staging, I was redirected to the KYC flow as expected (it's the last step because I started the KYC flow before):

https://github.com/Expensify/App/assets/12268372/e65021bb-d151-4129-b4cf-b75ea63baef5

**Comment by MariaHCD** [comment] 2023-10-17 13:45
Okay, I believe the `isDefault` is the correct property we should rely on here as per the backend code: https://github.com/Expensify/Web-Expensify/blob/40ccd2bbbfe54418d84343ced75616b8e64047b4/lib/BankAccountAPI.php#L1956

- `isDefault` refers to whether the bank account is linked to the wallet.
- `defaultCredit` refers to whether the bank account is the default deposit account for the user.

**Comment by MariaHCD** [comment] 2023-10-17 13:58
I think we can get the fix for this included in https://github.com/Expensify/App/issues/29320#issuecomment-1766477292

**Comment by MariaHCD** [comment] 2023-10-20 09:54
This one should be fixed by these FE and BE PRs:
- https://github.com/Expensify/App/pull/29915
- https://github.com/Expensify/Web-Expensify/pull/39205

I think we are good to close for. We can reopen if this is still an issue.

**Closed by MariaHCD** 2023-10-20 09:54 UTC
Labels: Daily, Bug
