### ISSUE TITLE
[HOLD for payment 2024-06-20] [HOLD for payment 2024-06-18] [$250] Chat - Compose box is hidden when editing multiple line break message

### ISSUE THREAD

**Issue by izarutskaya** [Expensify/App#40767] opened 2024-04-23 10:42 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** v1.4.64-0
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**If this was caught during regression testing, add the test name, ID and link from TestRail:** https://expensify.testrail.io/index.php?/tests/view/4503695
**Email or phone of affected tester (no customers):** vdargentotest+ios042224@gmail.com
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Issue reported by:** Applause-Internal team

## Action Performed:
Pre-requisite: user must be logged in.

1. Go to any chat.
2. Send a message with 10 line breaks.
3. Tap and hold on the recently sent message.
4. Tap on "Edit comment".
5. Verify the compose box is partially hidden, the chat does not auto-scroll to the bottom.

## Expected Result:
The page should auto-scroll to the bottom and the compose box should be fully visible without manual scroll.

## Actual Result:
The page is not auto-scrolled to the bottom, the compose box is partially hidden, manual scroll is required.

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [x] iOS: Native
- [ ] iOS: mWeb Safari
- [ ] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

https://github.com/Expensify/App/assets/115492554/b77f87b4-a964-4ebe-99c5-b41fdbde7b72

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~0179a22c17165154c1</li>
        <li>Upwork Job ID: 1782955414960959488</li>
        <li>Last Price Increase: 2024-05-29</li>
<li>Automatic offers: </li>
<ul>
<li>rojiphil | Reviewer | 102547928</li>
<li>suneox | Contributor | 102547931</li>
</ul></li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @trjExpensify</details>

**Comment by izarutskaya** [comment] 2024-04-23 10:42
We think this issue might be related to the #vip-vsb.

**Comment by trjExpensify** [comment] 2024-04-24 02:11
I can reproduce it. Couldn't find a recent issue, looks like @kosmydel fixed it once before here in Oct 2023: https://github.com/Expensify/App/pull/24502

**Comment by kosmydel** [comment] 2024-04-24 09:40
> I can reproduce it. Couldn't find a recent issue, looks like @kosmydel fixed it once before here in Oct 2023: #24502

The mentioned issue was related to mWeb only, not native. At first glance, the root cause of this issue is different.

**Comment by sword1202** [comment] 2024-04-26 10:47
If  there is multi lines text, it's impossible to edit on iPhone.

https://github.com/Expensify/App/assets/23204263/ddc288c3-d9b0-44b5-8633-e7d413762a63

**Comment by trjExpensify** [comment] 2024-04-27 12:44
@rojiphil are you going to review these proposals?

**Comment by rojiphil** [comment] 2024-04-27 13:04
> @rojiphil are you going to review these proposals?

@trjExpensify Yes. Will review and share an update today.

**Comment by rojiphil** [comment] 2024-04-27 20:09
> react-native-web doesn't implement [Keyboard event](https://github.com/necolas/react-native-web/blob/ef95fc0c2b40cc0d3743df4b56485a16a8442e5f/packages/react-native-web/src/exports/Keyboard/index.js#L13)

@tienifr  What are your thoughts on this concern?

**Comment by rojiphil** [comment] 2024-04-27 20:09
> runAfterInteractions can not make sure the keyboard is shown totally

@suneox  And what are your thoughts on this concern?

**Comment by trjExpensify** [comment] 2024-05-07 09:42
@rojiphil any feedback on [this](https://github.com/Expensify/App/issues/40767#issuecomment-2091230417)?

**Comment by rojiphil** [comment] 2024-05-08 04:05
> I think I have pointed out [the reason](https://github.com/Expensify/App/issues/40767#issuecomment-2077683868) i'm using these attributes based on a lot of places that also use it.

Just because it is used elsewhere does not necessarily mean we can use it here too. So I am still not convinced of the reasoning here.

**Comment by rojiphil** [comment] 2024-05-08 04:09
> This issue still happens when you edit the last item has multiple lines

@suneox As I understand from your comment [here](https://github.com/Expensify/App/issues/40767#issuecomment-2074084446), this problem happens only for the last item. So, why is this problem not observed for non-last items? Non-last items does not seem to need the support of `runAfterInteractions` and `requestAnimationFrame` to display edit box completely.

**Comment by trjExpensify** [comment] 2024-05-15 20:39
@rojiphil any feedback on the above?

**Comment by trjExpensify** [comment] 2024-05-20 10:52
Bump, @rojiphil. Can you take a look at that please?

**Comment by rojiphil** [comment] 2024-05-20 10:54
Sure. I will check this today and provide update.

**Comment by rojiphil** [comment] 2024-05-21 08:58
As mentioned earlier [here](https://github.com/Expensify/App/issues/40767#issuecomment-2082378622), we can reproduce the problem for the last item even when the keyboard is not shown. I also reconfirmed this with the latest main. So, I disagree with any RCA that uses the keyboard as the main reason for this issue. Also, resolving the issue with delay is not guaranteed to work all the time. So, I am looking for a solution that resolves the issue even when the keyboard is not shown on native devices. 

https://github.com/Expensify/App/assets/3004659/de736ffe-1d11-4bdb-9fd6-30cdd3afdb4f

**Comment by trjExpensify** [comment] 2024-05-21 18:48
Got it okay, so @suneox, maybe you have some other ideas on what the root cause of this is!

**Comment by trjExpensify** [comment] 2024-05-24 20:13
@rojiphil, thoughts?

**Comment by rojiphil** [comment] 2024-05-27 16:08
> In this case, this issue happens when we have multiple transitions run in the time (keyboard open, hide main composer, report item change to edit view and scroll to edit view) and my solution using runAfterInteractions and requestAnimationFrame also can handle this issue

@suneox What if any of the other transitions are initiated after the scroll operation? This would still cause our issue here. That is why resolving the issue with delay is not guaranteed always to work.  
Also, what has changed recently that started causing this issue? 
We still need to get to the root cause of this issue.

**Comment by trjExpensify** [comment] 2024-05-30 01:39
@suneox do you have any further insight on the root cause?

**Comment by rojiphil** [comment] 2024-05-31 11:11
> And could you please try my proposal?

I tested the solution and it seems to work. 
However, I am still on the fence if we want to use delay (via use of `runAfterInteractions` and `requestAnimationFrame`) as an approach to resolve this issue and as proposed in @sunnex [proposal](https://github.com/Expensify/App/issues/40767#issuecomment-2074073743). 
On one hand, theoretically,  there is always a faint chance for `scroll` to be initiated before other animations in which case this issue can get reproduced.
Whereas, on the other hand, we have used the delay pattern to address scroll issues [here](https://github.com/Expensify/App/blob/e915d369db27d9ac77871322c5b7b2515bc29b52/src/components/LHNOptionsList/LHNOptionsList.tsx#L206C1-L212C12) and [here](https://github.com/Expensify/App/blob/e915d369db27d9ac77871322c5b7b2515bc29b52/src/components/FlatList/index.tsx#L123C1-L133C18) and also in other situations like [here](https://github.com/Expensify/App/blob/e915d369db27d9ac77871322c5b7b2515bc29b52/src/pages/home/sidebar/SidebarLinks.tsx#L58C1-L62C12) and [here](https://github.com/Expensify/App/blob/e915d369db27d9ac77871322c5b7b2515bc29b52/src/libs/Navigation/setNavigationActionToMicrotaskQueue.ts#L9C1-L11C12). 
So, curious to know the thoughts of internal engineer too on this before we move ahead.
🎀👀🎀

**Comment by thienlnam** [comment] 2024-05-31 22:59
Thanks for the review, given the fact that this delay pattern seems to work fine in these other locations, I think we can also use it here as well

**Comment by trjExpensify** [comment] 2024-06-20 14:18
👋 checklist time, please!

**Comment by rojiphil** [comment] 2024-06-24 03:48
* [x]  [@rojiphil] The PR that introduced the bug has been identified. Link to the PR: [Offending PR](https://github.com/Expensify/App/pull/2320)
* [x]  [@rojiphil] The offending PR has been commented on, pointing out the bug it caused and why, so the author and reviewers can learn from the mistake. Link to comment: [Added comment](https://github.com/Expensify/App/pull/2320/files#r1650299399)
* [x]  [@rojiphil] A discussion in #expensify-bugs has been started about whether any other steps should be taken (e.g. updating the PR review checklist) in order to catch this type of bug sooner. Link to discussion: Not Required. Existing checklist is good enough to capture such issues.
* [x]  [@rojiphil] Determine if we should create a regression test for this bug. :  Given the spooky nature of this issue, it is better to have a regression test case to ensure this does not occur again.
* [x]  [@rojiphil] If we decide to create a regression test for the bug, please propose the [regression test](https://github.com/Expensify/App/blob/main/contributingGuides/REGRESSION_TEST_BEST_PRACTICES.md) steps to ensure the same bug will not reach production again. 
1. Go to any chat.
2. Send a message with 10 line breaks.
3. Tap and hold on the recently sent message.
4. Tap on "Edit comment".
5. Verify that the page auto-scrolls to the bottom and the compose box is fully visible without manual scroll.

**Comment by rojiphil** [comment] 2024-06-24 03:52
> 👋 checklist time, please!

@trjExpensify Completed BZ checklist and accepted the offer too. Thanks.

**Comment by trjExpensify** [comment] 2024-06-24 09:33
Thanks! Regression test issue created for Applause. 

Payment summary as follows: 

- $250 to @suneox for the fix 
- $250 to @rojiphil for the C+ review

Paid you both, closing!

**Closed by trjExpensify** 2024-06-24 09:33 UTC
Labels: External, Daily, Overdue, Awaiting Payment, Bug
