### ISSUE TITLE
[$500] App does not display proper result directly on inserting spanish letter in mention (works fine on search)

### ISSUE THREAD

**Issue by kavimuru** [Expensify/App#28749] opened 2023-10-03 20:49 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
Precondition: One of the user should have spanish l letter in display name
1. Open the app in mac safari/ mac chrome
2. Open any report
3. Click @ and insert spanish letter which any of the existing known user has in its display name (to directly insert that letter, long press on that letter in keyboard, it will display spanish option, select it using that option number)
4. Observe that app does not display proper results for that spanish letter, instead it displays results for its english equivalent
5. Copy that letter, erase it and paste after @
6. Observe that now app displays proper mention result
7. Try similarly in search i.e. open search, long and insert Spanish letter as mentioned in step 3 and observe that app displays correct results directly
## Expected Result: 
App should display results according to inserted Spanish letter as it does on search
## Actual Result: 
App does not display results according to inserted Spanish letter in mention

## Workaround:
Can the user still use Expensify without this being fixed? Have you informed them of the workaround?

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [x] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 1.3.77-2
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/43996225/0713e5d2-4642-4141-857e-85051eb695a6

https://github.com/Expensify/App/assets/43996225/8b256c5c-30ae-46a4-bf6e-8b88ec77bb52

**Expensify/Expensify Issue URL:**
**Issue reported by:** @dhanashree-sawant
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1695036943283459

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01c8bbf298d69a89ce</li>
        <li>Upwork Job ID: 1709309647610187776</li>
        <li>Last Price Increase: 2023-11-14</li>
    </ul>
</details>

**Comment by shubham1206agra** [comment] 2023-10-04 12:25
@tienifr Can you confirm this problem with the latest main?

**Comment by eVoloshchak** [comment] 2023-10-12 15:41
Not overdue, looks like this has been resolved (unable to reproduce)

**Comment by eVoloshchak** [comment] 2023-10-16 11:57
Not overdue, looks like this has been resolved (unable to reproduce)

**Comment by mvtglobally** [comment] 2023-10-17 15:18
Issue not reproducible during KI retests. (First week)

**Comment by eVoloshchak** [comment] 2023-10-20 08:37
Not overdue, let's wait for the second week of KI tests

**Comment by mvtglobally** [comment] 2023-10-27 00:47
Issue not reproducible during KI retests. (Second week)

**Comment by eVoloshchak** [comment] 2023-10-27 13:06
Not overdue, I think we can close this one since it's not reproducible 2 weeks in a row

**Comment by mvtglobally** [comment] 2023-11-02 03:33
Issue not reproducible during KI retests. (Third week)

**Comment by eVoloshchak** [comment] 2023-11-02 16:20
Not overdue, this one was resolved and can be closed

**Comment by eVoloshchak** [comment] 2023-11-06 15:37
Same as [above](https://github.com/Expensify/App/issues/28749#issuecomment-1791055477)
@kavimuru, could you close this one please?

**Comment by mvtglobally** [comment] 2023-11-09 21:02
Issue not reproducible during KI retests. (4th week)

**Comment by eVoloshchak** [comment] 2023-11-12 17:31
Not overdue, looks like the issue isn't reproducible anymore and can be closed
@kavimuru, could you close this one please?

**Comment by mvtglobally** [comment] 2023-11-18 04:33
Issue not reproducible during KI retests. (5th week) Closinf

**Closed by mvtglobally** 2023-11-18 04:33 UTC
Labels: External, Daily, Help Wanted
