### ISSUE TITLE
[HOLD for payment 2024-06-13] CRITICAL: GBR and Settlement button for the receiver on the invoice report preview

### ISSUE THREAD

**Issue by cristipaval** [Expensify/App#40437] opened 2024-04-18 13:20 UTC
# Part of the **Invoicing V0.2** project
Main issue: https://github.com/Expensify/Expensify/issues/341717
Doc section: [Invoicing V1](https://docs.google.com/document/d/1HhnjCVUVN8gw3vfxRA4jCXXQvuIfm1puMhzHoOKe5jY/edit#bookmark=id.1pnsna7h8vtu)
Project: [#vip-billpay](https://join.slack.com/share/enQtNjkzNDU4NTI3OTY4Ni03M2RlY2IwNzhjMDEzMGE1NjZmYmM5MGJmZDZmNTc4NjRhYmRlOWM4NzMzYmJmOGUyZDAzNWFiNTgyNjQ0YTg0)

# Feature Description
Implement the Settlement button on the invoice report preview in the invoice room, when the user is the individual receiver.

# Manual Test Steps

# Automated Tests

<details><summary>Issue Owner</summary>Current Issue Owner: @trjExpensify</details>

**Comment by trjExpensify** [comment] 2024-04-18 13:53
># Feature Description
>Implement the Settlement button on the 

😅 Heads up, man! I think you forgot to finish your sen

**Comment by cristipaval** [comment] 2024-04-18 14:16
DANG! Sorry

**Comment by trjExpensify** [comment] 2024-04-27 12:39
👋 @cristipaval what issue is this on hold for? We should update the title to make that dependency clear.

**Comment by cristipaval** [comment] 2024-04-28 19:51
this is part of the V0.2 which is held until the v0.1 is launched

**Comment by waterim** [comment] 2024-04-29 14:55
@cristipaval Should I take this asap as v1 was merged?

**Comment by cristipaval** [comment] 2024-05-06 12:29
@waterim yes please start working on this when the critical issues on the V0.1 are cleared

**Comment by cristipaval** [comment] 2024-05-07 23:58
^[Auth PR](https://github.com/Expensify/Auth/pull/10813) is ready for review. It enabled the GBR to the receiver on the invoice room in the LHN.

**Comment by cristipaval** [comment] 2024-05-09 07:48
We have a draft App PR^ 🙌

**Comment by VickyStash** [comment] 2024-05-31 14:18
**Updates:**
- addressed designers' feedback
- waiting for C+ review

**Comment by trjExpensify** [comment] 2024-06-03 20:07
PR is in active review, Melv.

**Comment by ikevin127** [comment] 2024-06-06 16:52
The regression message from [here](https://github.com/Expensify/App/issues/40437#issuecomment-2150914472) is false alarm and sorted out in https://github.com/Expensify/App/issues/43145#issuecomment-2152116938.

##

Regarding https://github.com/Expensify/App/issues/40437#issuecomment-2152297060, I reviewed PR as C+ and require compensation.

**Note:** Given the status of the issue is `Critical`, the bounty should be $500.

cc @trjExpensify

**Comment by trjExpensify** [comment] 2024-06-07 00:06
Assigned you to the issue to not lose track of that.

**Comment by ikevin127** [comment] 2024-06-13 16:42
@trjExpensify Offer accepted, thank you!

**Closed** 2024-06-14 12:09 UTC
Labels: Daily, NewFeature, Awaiting Payment
