### ISSUE TITLE
[HOLD for payment 2024-04-05] [$125] Offline indicator is not at bottom of page on Workflows, and Categories, Tags empty state

### ISSUE THREAD

**Issue by luacmartins** [Expensify/App#38807] opened 2024-03-22 14:47 UTC
## Problem
Offline indicator does not show at the bottom of the page on the Workflows page and for Categories and Tags when showing the empty list component

![Screenshot 2024-03-22 at 8 45 01 AM](https://github.com/Expensify/App/assets/22219519/50d5ad0b-dbb5-4574-b8f5-64c9b627cb41)
![Screenshot 2024-03-22 at 8 45 36 AM](https://github.com/Expensify/App/assets/22219519/7fd99fb8-7ed1-4e6a-b8c4-60c5b429ef06)
![Screenshot 2024-03-22 at 8 45 40 AM](https://github.com/Expensify/App/assets/22219519/8874ad8f-eecd-45f6-b88c-101a36765dd1)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01e4a7a9c86981e817</li>
        <li>Upwork Job ID: 1771187226329485312</li>
        <li>Last Price Increase: 2024-03-22</li>
<li>Automatic offers: </li>
<ul>
<li>GandalfGwaihir | Contributor | 0</li>
</ul></li>
    </ul>
</details>

**Comment by bernhardoj** [comment] 2024-03-22 14:51
I think this is a dupe of https://github.com/Expensify/App/issues/37721?

**Comment by askavyblr** [comment] 2024-03-22 15:57
## Proposal

### Please re-state the problem that we are trying to solve in this issue.

The offline indicator is not displayed at the bottom of the Workflows page, nor is it shown for Categories and Tags when the empty list component is presented.

### What is the root cause of that problem?

https://github.com/Expensify/App/blob/196ecde9032e573608a4da5144993c07ed72aeff/src/components/ScreenWrapper.tsx#L224-L226

Need to fix passing bottom

### What changes do you think we should make in order to solve the problem?

Need to fix passing bottom

### What alternative solutions did you explore? (Optional)

N/A

**Comment by luacmartins** [comment] 2024-03-22 19:10
I think we should cover the categories/tags page here since that's not covered in that issue

**Comment by luacmartins** [comment] 2024-03-22 19:11
Both @askavyblr and @GandalfGwaihir have pretty similar solutions so I'm gonna go with the first [proposal](https://github.com/Expensify/App/issues/38807#issuecomment-2015396576) by @askavyblr

**Comment by luacmartins** [comment] 2024-03-22 19:29
Thanks for pointing that out @GandalfGwaihir and sorry that I missed that! I'll assign you to the job!

**Comment by luacmartins** [comment] 2024-03-22 19:30
@askavyblr if you edit your proposal, you should post another comment mentioning that it was edited. From our [contributing guidelines](https://github.com/Expensify/App/blob/2b2a5232f3164fe3e327a2e55003eba95b3834c1/contributingGuides/CONTRIBUTING.md#L103):

>    - If you want to make an entirely new proposal or update an existing proposal, please go back and edit your original proposal, then post a new comment to the issue in this format to alert everyone that it has been updated:

**Comment by kadiealexander** [comment] 2024-04-05 03:35
@GandalfGwaihir please don't forget the checklist!

**Comment by luacmartins** [comment] 2024-04-05 14:22
This feature was in development at the time, so I don't think the checklist is applicable.

**Comment by kadiealexander** [comment] 2024-04-07 21:58
Payouts due:

- [ ] Contributor: $125 @GandalfGwaihir

Upwork job is [here](https://www.upwork.com/jobs/~01e4a7a9c86981e817).

**Closed** 2024-04-07 21:59 UTC
Labels: External, Daily, Awaiting Payment, Bug
