### ISSUE TITLE
Web - Inconsistent styling when selecting phone number with @ mention in chat.

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#21790] opened 2023-06-28 11:47 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Open any chat.
2. Type @ and select a phone number from the list.
3. Observe that the styling and properties are different from when selecting an email.

## Expected Result:
The styling and properties should be consistent when selecting a phone number or email with @ mention.

## Actual Result:
The styling and properties are not consistent when selecting a phone number with @ mention compared to selecting an email.

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [x] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 1.3.32-5
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/93399543/cf1b7886-5ebf-43df-969a-7e81312adac6

https://github.com/Expensify/App/assets/93399543/7244f1b8-3ad7-47ef-b119-49aec0f277e5

**Expensify/Expensify Issue URL:**
**Issue reported by:** @tewodrosGirmaA
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1687721109789049

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by Nikhil-Vats** [comment] 2023-06-28 13:21
dupe of https://github.com/Expensify/App/issues/21684. Only those phone numbers are not rendered as mentions which don't have accounts because they don't follow the format `phoneNumber@expensify.sms`

**Comment by bernhardoj** [comment] 2023-06-28 13:42
This is a known issue https://expensify.slack.com/archives/C01GTK53T8Q/p1683753105314829

cc: @puneetlath

**Comment by puneetlath** [comment] 2023-06-28 21:43
Yes this is a known bug and not something that we are currently going to fix. It will be fixed in the next iteration of mentions.

**Closed by puneetlath** 2023-06-28 21:43 UTC
Labels: Daily, Bug
