### ISSUE TITLE
[$250] Web - Track Expense - Receipt disappears when categorize IOU from Self DM

### ISSUE THREAD

**Issue by izarutskaya** [Expensify/App#43553] opened 2024-06-12 12:09 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.82-0
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**If this was caught during regression testing, add the test name, ID and link from TestRail:** https://expensify.testrail.io/index.php?/tests/view/4621286&group_by=cases:section_id&group_order=asc&group_id=309130
**Email or phone of affected tester (no customers):** gocemate+a223@gmail.com
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Issue reported by:** Applause-Internal team

## Action Performed:
1. Go to staging.new.expensify.com
2. Create workspace
3. Go to FAB> Track Expense> Finish the flow
4. Go to Self DM and click on Categorize it
5. Click on a existing workspace> Select any category
6. On + button add a receipt> Complete the flow
7. Go the IOU from Step 6 to open the detail page

## Expected Result:
Added receipt should remains on created request

## Actual Result:
Receipt is visible when create request and after a while it disappears

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

https://github.com/Expensify/App/assets/115492554/0a9c8d07-572e-457b-94a0-dd5c609f53e1

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~011d7985fdec28883a</li>
        <li>Upwork Job ID: 1810391532944755799</li>
        <li>Last Price Increase: 2024-07-15</li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @suneox</details>

**Comment by izarutskaya** [comment] 2024-06-12 12:09
We think this issue might be related to the  #vip-vsb

**Comment by Christinadobrzyn** [comment] 2024-06-13 02:46
Just a heads up - I'm going to be ooo until June 24th so going to reassign this to a teammate

**Comment by anmurali** [comment] 2024-06-18 21:09
I cannot reproduce this in Staging...

**Comment by anmurali** [comment] 2024-07-08 19:06
I can in fact reproduce it now on staging.

**Comment by anmurali** [comment] 2024-07-08 19:20
@thienlnam - would also appreciate you reviewing this issue to make sure a contributor can fix it.

**Comment by thienlnam** [comment] 2024-07-10 18:10
This looks like it is probably an internal issue

**Comment by anmurali** [comment] 2024-07-17 00:01
@thienlnam @suneox - is this BE or FE fix?

**Comment by thienlnam** [comment] 2024-07-17 00:05
This would be internal, but since this wave is paused it will unlikely be prioritized

**Comment by anmurali** [comment] 2024-08-06 02:16
I can reproduce it now and I actually think this should be in wave collect. This happens when a tracked expense is categorized and as a result is put on a policy. This could be a bottom up use case and we can't have the receipts disappearing!! @trjExpensify do you agree?

**Comment by trjExpensify** [comment] 2024-08-07 21:44
I don't think Track > categorise it is officially part of the bottom-up "CVP" flow. I agree we should fix it though, as it's not out of the realm of possibility someone goes down the track flow, realises they want categories, and hits this bug when upgrading to a collect workspace to access them. 

Going to move it into `Hot Picks`.

**Comment by trjExpensify** [comment] 2024-08-13 12:14
@thienlnam while you wait on Dan's PR for https://github.com/Expensify/App/issues/44615, can you look into this?

**Comment by anmurali** [comment] 2024-08-14 02:18
Not overdue. Waiting for @thienlnam to take a look.

**Comment by thienlnam** [comment] 2024-08-21 19:20
Auth PR merged, Web-E PR pending review once auth deployed

**Comment by thienlnam** [comment] 2024-09-05 18:27
All done

**Closed by thienlnam** 2024-09-05 18:27 UTC
Labels: Reviewing, Daily, Internal, Bug
