### ISSUE TITLE
[HOLD for payment 2022-12-02] [$1000] [Bug] Pressing escape when a popover is open closes the chat and the page gets stuck in the middle - reported by @Puneet-here

### ISSUE THREAD

**Issue by mvtglobally** [Expensify/App#11930] opened 2022-10-17 20:58 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Decrease the screen size
2. Go to any chat
3. Click on actions (the :heavy_plus_sign: sign at the left side of message input)
4. Press escape

## Expected Result:
Only the popover should be closed

## Actual Result:
The popover closes but the chat also gets closed and then it gets stuck in the middle of chat and chat list 
Also. 
On web staging v1.2.16-4 and when doing the steps, the popover did not close, the chat closed and user was not able to leave the popover (had the LHN on the background) and had to refresh the page to get to working state

Additionally, this should be resolved in the `About section --> Copy To Clipboard` page

## Workaround:
unknown 

## Platform:

Where is this issue occurring?

- Web
- Desktop App

**Version Number:** 1.2.15-0
**Reproducible in staging?:** Y 
**Reproducible in production?:** Y 
**Email or phone of affected tester (no customers):** 
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation 

https://user-images.githubusercontent.com/43995119/196281354-0293809b-28e1-4474-84d7-afa26c4b51f2.mov

**Expensify/Expensify Issue URL:** 
**Issue reported by:** @Puneet-here
**Slack conversation:** https://expensify.slack.com/archives/C01GTK53T8Q/p1663088510944699

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by adelekennedy** [comment] 2022-10-18 22:46
@mountiny was able to reproduce [here](https://expensify.slack.com/archives/C01GTK53T8Q/p1666132584850749?thread_ts=1663088510.944699&cid=C01GTK53T8Q)! I think this a real one

**Comment by Julesssss** [comment] 2022-10-19 09:24
Confirmed, opening up to contributors

**Comment by adelekennedy** [comment] 2022-10-19 19:14
[internal](https://www.upwork.com/ab/applicants/1582812256669855744/job-details)
[external](https://www.upwork.com/jobs/~01b6b1ff9794f23e74)

**Comment by chauchausoup** [comment] 2022-10-20 06:26
I think we can make use of [PopoverMenu](https://github.com/Expensify/App/blob/main/src/components/PopoverMenu/popoverMenuPropTypes.js) instead of Popover component in this section. The initial component already have Keyboard listeners embedded in it.

**Comment by chauchausoup** [comment] 2022-10-20 07:04
Also the issue is found on `About section --> Copy To Clipboard `Popover.

**Comment by Julesssss** [comment] 2022-10-20 09:43
Awaiting proposals

**Comment by roryabraham** [comment] 2022-10-24 10:08
This is a regression so let's please do an RCA and follow-up, ideally adding some automated test coverage to prevent this regression from happening again in the future.

**Comment by adelekennedy** [comment] 2022-10-27 15:11
What are the next steps to do an RCA? @Julesssss @eVoloshchak

**Comment by Julesssss** [comment] 2022-10-31 10:32
@adelekennedy could you please double the payment amount? Thanks!

**Comment by Julesssss** [comment] 2022-11-03 17:30
Hey @adelekennedy, bumping for bounty increase

**Comment by adelekennedy** [comment] 2022-11-08 05:35
doubled the price - @Julesssss @roryabraham from the comment [here](https://github.com/Expensify/App/issues/11930#issuecomment-1288776484) is this still an external issue? What are our next steps?

**Comment by Julesssss** [comment] 2022-11-08 11:30
Hey @adelekennedy, for now we're awaiting a proposal. Once we're settled on a solution the cause will likely become apparent. Then we'll make sure that tests are added in the PR.

**Comment by adelekennedy** [comment] 2022-11-09 00:32
kk - will keep doubling this!

**Comment by adelekennedy** [comment] 2022-11-10 21:07
we just hit the doubling mark

**Comment by adelekennedy** [comment] 2022-11-10 23:42
@isabelastisser reassigning to you while I'm gone to keep it doubling!

**Comment by richdev1124** [comment] 2022-11-11 00:43
@adelekennedy I reproduced issue, may I work for this issue too?

**Comment by Julesssss** [comment] 2022-11-11 10:43
> @adelekennedy I reproduced issue, may I work for this issue too?

@richdev1124 you'll need to submit a proposal first, and then get selected. Please see our [Contributing](https://github.com/Expensify/App/blob/main/contributingGuides/CONTRIBUTING.md) guides for more help.

**Comment by huzaifa-99** [comment] 2022-11-11 21:55
Are we handling accessibility (like using escape key)? I asked about this [here](https://expensify.slack.com/archives/C01GTK53T8Q/p1668197149475149)

**Comment by s77rt** [comment] 2022-11-12 22:06
### Proposal
```diff
diff --git a/node_modules/react-native-modal/dist/modal.d.ts b/node_modules/react-native-modal/dist/modal.d.ts
index b63bcfc..bd6419e 100644
--- a/node_modules/react-native-modal/dist/modal.d.ts
+++ b/node_modules/react-native-modal/dist/modal.d.ts
@@ -161,6 +161,7 @@ export declare class ReactNativeModal extends React.Component<ModalProps, State>
     getDeviceHeight: () => number;
     getDeviceWidth: () => number;
     onBackButtonPress: () => boolean;
+    handleEscape: (e: KeyboardEvent) => void;
     shouldPropagateSwipe: (evt: GestureResponderEvent, gestureState: PanResponderGestureState) => boolean;
     buildPanResponder: () => void;
     getAccDistancePerDirection: (gestureState: PanResponderGestureState) => number;
diff --git a/node_modules/react-native-modal/dist/modal.js b/node_modules/react-native-modal/dist/modal.js
index 80f4e75..fe028ab 100644
--- a/node_modules/react-native-modal/dist/modal.js
+++ b/node_modules/react-native-modal/dist/modal.js
@@ -75,6 +75,13 @@ export class ReactNativeModal extends React.Component {
             }
             return false;
         };
+        this.handleEscape = (e) => {
+            if (e.key === 'Escape') {
+                if (this.onBackButtonPress() === true) {
+                    e.stopImmediatePropagation();
+                }
+            }
+        };
         this.shouldPropagateSwipe = (evt, gestureState) => {
             return typeof this.props.propagateSwipe === 'function'
                 ? this.props.propagateSwipe(evt, gestureState)
@@ -454,9 +461,15 @@ export class ReactNativeModal extends React.Component {
             this.open();
         }
         BackHandler.addEventListener('hardwareBackPress', this.onBackButtonPress);
+        if (Platform.OS === 'web') {
+            document?.body?.addEventListener?.('keyup', this.handleEscape, true);
+        }
     }
     componentWillUnmount() {
         BackHandler.removeEventListener('hardwareBackPress', this.onBackButtonPress);
+        if (Platform.OS === 'web') {
+            document?.body?.removeEventListener?.('keyup', this.handleEscape, true);
+        }
         if (this.didUpdateDimensionsEmitter) {
             this.didUpdateDimensionsEmitter.remove();
         }
```

### Details
The issue is caused by a conflict between [react-navigation](https://github.com/Expensify/react-navigation/blob/react-navigation-drawer-v6.5.0-alpha1-gitpkg/src/views/DrawerView.tsx) and [react-native-modal](https://github.com/react-native-modal/react-native-modal/blob/v13.0.0/src/modal.tsx). react-navigation set a listener on keyup and captures the keyup for the `Escape` key to close the active drawer modal (chat in this case) and if so, it does not bubbles up thus stopping further events from execution including the react-native-modal. react-native-modal only uses `BackHandler` where react-navigation uses `BackHandler` and an extra keyup listener (the one just mentioned). In my proposal (patch), I added a similar listener of that of react-native, but this is not enough as the react-native listener is set first, the same issue will occur, that's why you can see a third parameter in the addEventListener and removeEventListener function calls, it's set to true to use capture instead of bubbling, which guarantees that key events will go first to the modal, and if so, we try to close the modal if it's open and close-able, if so we stopi mmediate propagation to prevent closing the chat drawer modal, else everything continues normally.

*PS: Don't forget to clear the cache (`rm -rf node_modules/.cache/`) if you want to apply the patch.*
*PS: I didn't submit a PR on react-native-modal because I think it's not their duty to follow react-navigation. I think a patch is the best thing to do here*
*PS: The solution can be applied on the BaseDrawerNavigator level without the need for the patch, but it's gonna need an additional logic check (is there a modal open or not). Since this is only related to modals, applying the fix on react-native-modal is the way to go*


https://user-images.githubusercontent.com/16493223/201496355-f83bd12f-1692-4b77-9407-fd0caec7f3bf.mp4

**Comment by Julesssss** [comment] 2022-11-14 12:17
Hey @s77rt. Thanks for the analysis and write-up.

The patch solution makes sense, but we avoid platform-specific logic, as explained [here](https://github.com/Expensify/App/blob/main/README.md#platform-specific-file-extensions). I'd be happy to review an updated proposal that applies this rule.  


____ 


Hey @huzaifa-99, we're definitely interested in solutions that align with accessibility. But we're not specifically focusing on this as a priority yet.

**Comment by s77rt** [comment] 2022-11-14 12:39
Hi @Julesssss 
I know the rules, but this is more specific to react-native-modal, this is a patch and won't be a part of the Expensify App code.

Suppose that the patch was applied to react-native-modal and you use the new patched react-native-modal, are you breaking the rules? because react-native-modal use that platform specific code and so react-navigation. Are we breaking the rules? I don't think so. Same thing applied here.

I'm asking to reconsider your decision

**Comment by Julesssss** [comment] 2022-11-14 17:17
Hey @s77rt. Good point, I'm actually not sure so I'm asking [here](https://expensify.slack.com/archives/C01GTK53T8Q/p1668446169315419) in slack for others' opinions.

**Comment by eVoloshchak** [comment] 2022-11-16 22:04
Looks like there's an [opinion](https://expensify.slack.com/archives/C01GTK53T8Q/p1668447245442219?thread_ts=1668446169.315419&cid=C01GTK53T8Q) about whether we should apply our code styling to library patches 

> I would probably say it should be written using the code style of the authors since we should be trying to get patches merged upstream.

I'll review and test @s77rt's proposal tomorrow

**Comment by Julesssss** [comment] 2022-11-17 09:59
@eVoloshchak yeah, that seems the correct plan to me 👍

**Comment by s77rt** [comment] 2022-11-17 17:27
@eVoloshchak Looks like you didn't clear the cache.

**Comment by eVoloshchak** [comment] 2022-11-17 18:07
You're right, weird, changes didn't take place until I cleared the cache and restarted the computer, even though it was hot reloading

@s77rt's proposal works well and looks good
🎀👀🎀 C+ reviewed!

@Julesssss, what should we do? Open a PR in `react-native-modal` or apply a patch?

**Comment by s77rt** [comment] 2022-11-17 18:09
@eVoloshchak Changes to node_modules are not a part of the hotload process, you have to clear node_modules/.cache and restart the app.

**Comment by eVoloshchak** [comment] 2022-11-17 18:12
Oh I see, thank you

**Comment by Julesssss** [comment] 2022-11-18 11:12
Lets go with the patch. As mentioned above, it seems unlikely that this will be accepted as an upstream RNModal PR

**Comment by s77rt** [comment] 2022-11-18 13:39
Applied in Upwork. (+50% Bonus)
[PR](https://github.com/Expensify/App/pull/12864) is ready.

**Comment by isabelastisser** [comment] 2022-11-21 14:06
Hey @Julesssss, did you create this job and hire @s77rt and @eVoloshchak in Upwork? Can you please share the job status links to this issue? Please let me know what steps I need to take moving forward. Thanks!

**Comment by Julesssss** [comment] 2022-11-22 11:21
> Hey @Julesssss, did you create this job and hire @s77rt and @eVoloshchak in Upwork?

Hey @isabelastisser, I've not created a job in UpWork as usually, the CM team does this.

**Comment by s77rt** [comment] 2022-11-22 11:25
@isabelastisser @Julesssss 
https://github.com/Expensify/App/issues/11930#issuecomment-1284460120

**Comment by Julesssss** [comment] 2022-11-22 14:55
Ah thanks. @isabelastisser do you have access to that UpWork job?

**Comment by isabelastisser** [comment] 2022-11-22 20:48
I do, @Julesssss ! @s77rt , can you please apply for that job at Upwork? Let me know when you do and I should be able to hire you there.

**Comment by s77rt** [comment] 2022-11-22 21:46
@isabelastisser I did already
https://github.com/Expensify/App/issues/11930#issuecomment-1320006228

**Comment by Julesssss** [comment] 2022-11-25 10:35
Merged, awaiting deployment to prod

**Comment by eVoloshchak** [comment] 2022-12-06 18:20
- The PR that introduced the bug has been identified. Link to the PR:

This is not something caused by our codebase, rather it's a conflict between [react-navigation](https://github.com/Expensify/react-navigation/blob/react-navigation-drawer-v6.5.0-alpha1-gitpkg/src/views/DrawerView.tsx) and [react-native-modal](https://github.com/react-native-modal/react-native-modal/blob/v13.0.0/src/modal.tsx)

**Comment by eVoloshchak** [comment] 2022-12-09 19:06
> A discussion in #expensify-bugs has been started about whether any other steps should be taken (e.g. updating the PR review checklist) in order to catch this type of bug sooner. Link to discussion:

https://expensify.slack.com/archives/C049HHMV9SM/p1670612750620769

**Comment by eVoloshchak** [comment] 2022-12-13 14:42
Friendly bump on the payment

And upwork job from [here](https://github.com/Expensify/App/issues/11930#issuecomment-1284460120) is expired

**Comment by isabelastisser** [comment] 2022-12-14 00:43
Hey @s77rt and @eVoloshchak, I reopened the job in Upwork and extended the contract to you. Please accept it so I can hire you and issue the payment ASAP. Thanks!

**Comment by s77rt** [comment] 2022-12-14 09:00
@isabelastisser Applied

**Comment by Puneet-here** [comment] 2022-12-14 12:09
@isabelastisser, I have applied on upwork for the reporting compensation.

**Comment by isabelastisser** [comment] 2022-12-14 12:18
Update: paid @Puneet-here and @eVoloshchak in Upwork.

@s77rt, you have a pending offer from me, please accept it first, and I will be able to take the next steps. I messaged you in Upwork with more instructions too. Thanks!

**Comment by isabelastisser** [comment] 2022-12-14 12:24
Update: paid @s77rt !

All set!

@Julesssss, is this task completed? Please let me know when I can close the issue.

> [@eVoloshchak / @Julesssss] A discussion in #expensify-bugs has been started about whether any other steps should be taken (e.g. updating the PR review checklist) in order to catch this type of bug sooner. Link to discussion:

**Closed** 2022-12-19 19:33 UTC
Labels: Reviewing, External, Engineering, Daily, Awaiting Payment, Bug
