### ISSUE TITLE
[HOLD for payment 2023-09-07] [$500] Web - Keyboard Delete Key Functions Incorrectly: Deletes in Wrong Direction and Has No Effect

### ISSUE THREAD

**Issue by izarutskaya** [Expensify/App#25578] opened 2023-08-21 12:41 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Go to FAB, then select "Request Money."
2. Input an amount (e.g., "123456").
3. Position the cursor between the second and third digit by clicking in that specific location.
4. Press the keyboard's delete key to erase characters (take note of the deletion direction).
5. Following two delete key presses (or after the left-sided numbers vanish), execute another delete key press, and observe the cursor's placement.

## Expected Result:
In step 4, the deletion should occur to the right of the cursor. During step 5, pressing the delete key should not cause the cursor to leap to the end of the amount. Conversely, if the intended deletion direction is to the left, and the cursor jumps to the amount's end, the delete key should still erase numbers to the left.

## Actual Result:
When pressing the keyboard's delete key, the numbers located to the left of the cursor are deleted. Once all left-sided numbers have been erased and the delete key is pressed again, the cursor jumps to the amount's end. After the cursor's relocation to the amount's end, the delete key ceases to remove numbers positioned to the cursor's left.

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [x] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:**  v1.3.55-7

**Reproducible in staging?:** Y

**Reproducible in production?:** Y

**If this was caught during regression testing, add the test name, ID and link from TestRail:**

**Email or phone of affected tester (no customers):**

**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/115492554/af37c557-64b4-47a7-aabe-9e20b18a967d

https://github.com/Expensify/App/assets/115492554/fd2e75fb-c016-4f8e-b20b-79d339ae9b23

**Expensify/Expensify Issue URL:**

**Issue reported by:** @Nathan-Mulugeta

**Slack conversation:**  https://expensify.slack.com/archives/C049HHMV9SM/p1691742018138099

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01f6bacb5a4e8eaf7a</li>
        <li>Upwork Job ID: 1694305640174825472</li>
        <li>Last Price Increase: 2023-08-23</li>
<li>Automatic offers: </li>
<ul>
<li>akinwale | Contributor | 26296415</li>
<li>Nathan-Mulugeta | Reporter | 26296416</li>
</ul></li>
    </ul>
</details>

**Comment by akinwale** [comment] 2023-08-21 13:02
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
Pressing Delete on the keyboard in the Request Money input field does not place the cursor correctly afterwards.

### What is the root cause of that problem?

### What changes do you think we should make in order to solve the problem?


### What alternative solutions did you explore? (Optional)

**Comment by trjExpensify** [comment] 2023-08-22 13:11
These are the supported platforms for accepted bug reports: 

>Android / native
>Android / Chrome
>iOS / native
>iOS / Safari
>MacOS / Chrome / Safari
>MacOS / Desktop

I see `MacOS / Chrome / Safari` was checked, but this is a Windows-only issue. There isn't an explicit `Delete` button on Mac to forward delete, and backspace is working as intended. As such, I think we close this one out as it isn't a focus as of now. Happy for a second opinion though! CC: @mountiny @s77rt

**Comment by akinwale** [comment] 2023-08-22 14:05
> These are the supported platforms for accepted bug reports:
> 
> > Android / native
> > Android / Chrome
> > iOS / native
> > iOS / Safari
> > MacOS / Chrome / Safari
> > MacOS / Desktop
> 
> I see `MacOS / Chrome / Safari` was checked, but this is a Windows-only issue. There isn't an explicit `Delete` button on Mac to forward delete, and backspace is working as intended. As such, I think we close this one out as it isn't a focus as of now. Happy for a second opinion though! CC: @mountiny @s77rt

I have a bit of a bias since I already posted a proposal, but I think this is worth fixing for a few reasons.
* Some users may be using a third-party keyboard with their Macs, and some do have a dedicated Delete key. I use a Keychron C2 mechanical keyboard with my Mac, for instance.
* It happens in all browsers, regardless of the running OS, so it can easily be reproduced on macOS as well.
* Apple Support also provides a list of [keyboard shortcuts](https://support.apple.com/en-us/HT201236) which includes shortcuts for forward delete (using Control-D, or Fn-Delete). There may be users who want to use these shortcuts if they do not have the key available on their keyboards.

**Comment by mountiny** [comment] 2023-08-22 14:45
Yeah I think this can be fixable for lower bounty $500 since its low priority as well

**Comment by trjExpensify** [comment] 2023-08-23 11:09
@narefyev91 👋 proposal ready for review [here](https://github.com/Expensify/App/issues/25578#issuecomment-1686288431).

**Comment by narefyev91** [comment] 2023-08-23 11:50
@trjExpensify @akinwale I was not able to reproduce it neither on staging no on main branch

https://github.com/Expensify/App/assets/28352309/bc95eccc-c24e-4478-ac70-8206c188aaba

**Comment by akinwale** [comment] 2023-08-23 11:58
> @trjExpensify @akinwale I was not able to reproduce it neither on staging no on main branch - i'm on Mac
> 
>  Screen.Recording.2023-08-23.at.14.48.25.mov

@narefyev91 You're performing a regular Backspace operation. The forward-delete operation can be performed using the one of the following:
1. A dedicated forward Delete key (marked as "Del" on non-Mac keyboards)
2. Fn-Delete keyboard shortcut on Mac
3. Ctrl+D keyboard shortcut on Mac

**Comment by akinwale** [comment] 2023-08-23 12:29
> @akinwale ok I see now - did you test your solution? Because using ctrl+d - removes items from the right side - instead of left

@narefyev91 Yes, I did test on all platforms. This is the expected behaviour. Ctrl+D (on Mac) does the same thing as Fn-Delete, which is forward delete (delete text to the right of the cursor). The current operation which works as expected is to delete text to the left of the cursor (Backspace on a Windows keyboard or the Delete key on a Mac keyboard).

> Also i'm wondering - did we have the same issue with old implementation? I did never see that we have some checks like nativeEvent.ctrlKey && key === 'd' - at old one

I added this extra check (which can be considered as a new feature) based on the documented keyboard shortcuts at https://support.apple.com/en-us/HT201236 (search for "Control-D"). This is only applicable on Macs.

**Comment by narefyev91** [comment] 2023-08-23 12:50
In any case - we can move to PR to start iterating and solve that
Let's move with @akinwale proposal
🎀 👀 🎀 C+ reviewed

**Comment by akinwale** [comment] 2023-08-24 06:22
@narefyev91 My [PR](https://github.com/Expensify/App/pull/25815) is ready for review. Thanks.

**Comment by codecoreminion** [comment] 2023-08-24 06:42
@narefyev91 My https://github.com/Expensify/App/pull/25815 is ready for review. Thanks.

**Comment by codecoreminion** [comment] 2023-08-29 03:03
🎯 ⚡️ Woah [@narefyev91](https://github.com/narefyev91) / [@akinwale](https://github.com/akinwale), great job pushing this forwards! ⚡️

The pull request got merged within 3 working days of assignment, so this job is eligible for a 50% #urgency bonus 🎉

when [@akinwale](https://github.com/akinwale) got assigned: 2023-08-24 03:57:49 Z
when the PR got merged: 2023-08-29 02:55:30 UTC
On to the next one 🚀

**Comment by Pujan92** [comment] 2023-08-29 18:45
I think regression https://expensify.slack.com/archives/C049HHMV9SM/p1693329205638489 from [here](https://github.com/Expensify/App/pull/25815) 
cc: @situchan

**Comment by akinwale** [comment] 2023-08-30 00:18
The crash is due to the `BaseTextInputWithCurrencySymbol`'s ref not being properly set in `TextInputWithCurrencySymbol/index.js` and `index.android.js`. Can be fixed by adding the following lines instead of just spreading the props:
``` 
{..._.omit(props, 'forwardedRef')}
ref={props.forwardedRef}
```

**Comment by trjExpensify** [comment] 2023-09-07 11:28
👋 @narefyev91 can you complete the checklist so we can proceed with payments please? 

Confirming those as follows: 

@Nathan-Mulugeta - $250 for the bug report
@akinwale - $500 for the fix

No #urgency bonus applied as per [here](https://github.com/Expensify/App/issues/25578#issuecomment-1698326535). 

Correct?

**Comment by situchan** [comment] 2023-09-07 14:43
Note: there was [regression of crash](https://github.com/Expensify/App/issues/25578#issuecomment-1697957224) which they fixed in 2nd [PR](https://github.com/Expensify/App/pull/26267)

**Comment by trjExpensify** [comment] 2023-09-11 11:42
>Note: there was https://github.com/Expensify/App/issues/25578#issuecomment-1697957224 which they fixed in 2nd https://github.com/Expensify/App/pull/26267

Ah, so the payment due to @akinwale is $250 for the regression correct @situchan?

**Comment by situchan** [comment] 2023-09-11 11:50
yes, in theory but watching video from checklist (both author and reviewer), crash didn't happen on iOS.
Maybe didn't test at the time of merge, after fixing conflict?

**Comment by trjExpensify** [comment] 2023-09-11 11:51
Cool, maybe @narefyev91 & @akinwale can clarify on that. :)

**Comment by trjExpensify** [comment] 2023-09-11 12:02
Okay, got it. Thanks for confirming! Payment of $250 sent :) 

closing this out :)

**Closed by trjExpensify** 2023-09-11 12:02 UTC
Labels: External, Weekly, Awaiting Payment, Bug
