### ISSUE TITLE
[CRITICAL] Opening attachment from email does not reliably open the attachment

### ISSUE THREAD

**Issue by mountiny** [Expensify/App#42676] opened 2024-05-27 22:16 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:**
**Reproducible in staging?:** Y
**Reproducible in production?:** Y 
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** @quinthar 
**Slack conversation:** https://expensify.slack.com/archives/C05LX9D6E07/p1716683200557169

## Action Performed:
Break down in numbered steps

1. Have two accounts, Alice and Bob
2. As Bob, have the app closed so you receive the messages through email (but be signed in)
3. As Alice, send some messages to Bob
4. As Alice, send pictures to Bob
5. As Bob, wait for the email
6. As Bob, click on the email picture

## Expected Result:
Describe what you think should've happened

The App should load with the image modal open and the picture shown there

## Actual Result:
Describe what actually happened

The modal is opened but the image does not actually load

## Workaround:
Can the user still use Expensify without this being fixed? Have you informed them of the workaround?

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [ ] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video ev

https://github.com/Expensify/App/assets/36083550/afd85bec-ecbf-45b9-b846-f61bcee2574e

idence

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Issue Owner</summary>Current Issue Owner: @thesahindia</details>

**Comment by Ahmed-Abdella** [comment] 2024-05-28 02:33
@mountiny Maybe you logged in expensify with different account.
for example:
your gmail is mounty@expensify.com and you are logged in Expensify as mounty+1@expensify.com.
in this case when you receive an attachment as for example mounty+2@expensify.com you will receive the mail at mounty@expensify.com but you can't  access it because you are logged in Expensify as mounty+1@expensify.com

**Comment by quinthar** [comment] 2024-05-28 03:17
Good question, but no, I'm logged in with the right account.  ~Again, if I repeat the same action multiple times, I get different results.~  UPDATE: I've tested this many times back to back, and even I can't reproduce it anymore.  Next time I see this I will capture a trace to make this more solvable.  Thanks for taking a look!

**Comment by quinthar** [comment] 2024-05-28 11:16
Actually @kidroca noticed that the `source` URL in the email isn't being URL encoded, which is probably what was causing it to break maybe for some images and not others?

**Comment by quinthar** [comment] 2024-05-28 11:25
original email is working... so closing again.

**Closed by quinthar** 2024-05-28 11:25 UTC
Labels: External, Daily, Help Wanted, Bug
