### ISSUE TITLE
[HOLD for payment 2024-06-03] [$500] mWeb - Attachment - "Failed to load PDF file" message only appears if I swipe the chat

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#32109] opened 2023-11-28 12:53 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.4.0
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** Applause - Internal Team
**Slack conversation:**

## Action Performed:
1. Navigate to https://staging.new.expensify.com/
2. Log in
3. Upload a corrupted PDF to any conversation
4. Swipe up

**PDF file** 
[Corrupted PDF.pdf](https://github.com/Expensify/App/files/13491020/Corrupted.PDF.pdf)

## Expected Result:
"Failed to load PDF file" should be visible without taking any actions.

## Actual Result:
"Failed to load PDF file" message only appears if I swipe the chat. An empty space blocks the view.

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [x] iOS: mWeb Safari
- [ ] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

https://github.com/Expensify/App/assets/93399543/17c4d70a-0567-45ac-b133-72c6c5c20f60

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~016eebac1c88fbedc0</li>
        <li>Upwork Job ID: 1729483719196209152</li>
        <li>Last Price Increase: 2023-12-19</li>
<li>Automatic offers: </li>
<ul>
<li>ishpaul777 | Contributor | 28089228</li>
</ul></li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @johncschuster</details>

**Comment by kbecciv** [comment] 2023-11-28 17:05
@ishpaul777 Sure, added under action performed.

![image](https://github.com/Expensify/App/assets/93399543/5bfadc0f-b95b-4fa2-b023-c2f7dbf3e2bc)

**Comment by shreyfirst** [comment] 2023-11-29 00:29
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
When uploading a corrupted PDF, the chat view will render an empty view (which takes up the entire screen), until an action/re-render is done such as scrolling up or clicking the text). This issue arises in the native iOS and Android platform (the provided video in OP was also in the native app also). 

### What is the root cause of that problem?
There is a state management issue in the native [PDFView](https://github.com/Expensify/App/blob/main/src/components/PDFView/index.native.js#L183C5-L196C6) component. The state variables `shouldAttemptPDFLoad` and `failedToLoadPDF` handle what to show to the user in this scenario, but they are not working as intended.

### What changes do you think we should make in order to solve the problem?
I will first attempt to debug which state variables are changing when, then make the appropriate changes to ensure that it shows "Failed to load PDF file" without you having to do any actions. This implementation of state variables for PDF load (excluding PDFs with passwords) relies on 3 conditions, whether it is OK to load, already failed, and if it's loading. I will see if simplifying these solves the problem.

**Comment by johncschuster** [comment] 2023-12-04 21:45
@parasharrajat, can you review @tienifr's proposal when you get a moment? Thank you!

**Comment by johncschuster** [comment] 2023-12-08 21:42
@parasharrajat bump! Can you review the changes when you get a moment?

**Comment by johncschuster** [comment] 2023-12-15 21:54
I will be OOO starting Monday, December 18, and will return Tuesday, January 2.

**Current status:** 
We're waiting on an update from @parasharrajat 
No proposals have been accepted yet

If this issue is open when I'm back from OOO, I'll take it back over. Thank you!

**Comment by miljakljajic** [comment] 2023-12-22 12:51
not overdue, still discussing

**Comment by johncschuster** [comment] 2024-01-02 22:21
Thanks for holding down the fort for me, @miljakljajic! I'll take this back over!

**Comment by johncschuster** [comment] 2024-01-02 22:22
@parasharrajat can you review the latest comments above? Are we good to more forward?

**Comment by johncschuster** [comment] 2024-01-18 22:34
PR is being worked on Melvin. Chill.

**Comment by shawnborton** [comment] 2024-03-12 12:33
Hmm I would think that if the thumbnail doesn't load, we use one of the fallback generic images you see on the right column of your screenshot above. Is that what you were thinking too?

**Comment by shawnborton** [comment] 2024-03-13 20:13
Oh interesting, that also makes sense to me, yeah. cc @Expensify/design for extra thoughts there too.

**Comment by dannymcclain** [comment] 2024-03-13 20:15
Yeah I'm down for that.

**Comment by yuwenmemon** [comment] 2024-04-03 21:03
Merged!

**Comment by johncschuster** [comment] 2024-05-28 13:47
# Payment Summary
C+ Reviewer: @parasharrajat - $500 - paid via Manual Requests
Contributor: @ishpaul777 - $500 - Paid via [Upwork](https://www.upwork.com/nx/wm/offer/28089228) (on June 3)

**Comment by johncschuster** [comment] 2024-06-03 13:48
@parasharrajat / @ishpaul777 can you complete the BZ Checklist above?

**Comment by johncschuster** [comment] 2024-06-05 13:40
Thanks for the regression test steps, @parasharrajat! Please send your Manual Request for payment (summary [above](https://github.com/Expensify/App/issues/32109#issuecomment-2135263863))

**Closed** 2024-06-05 13:40 UTC
Labels: External, Engineering, Daily, Awaiting Payment, Bug

**Comment by JmillsExpensify** [comment] 2024-06-11 18:38
$500 approved for @parasharrajat
