### ISSUE TITLE
Latest android release builds are instantly crashing due to JS errors

### ISSUE THREAD

**Issue by hannojg** [Expensify/App#51454] opened 2024-10-25 09:14 UTC
Slack thread: https://margelo.slack.com/archives/C05LX9D6E07/p1729847485394869

After releasing 9.0.54-0 we are experiencing constant crashes of the android app when build in release mode:

```
E  FATAL EXCEPTION: mqt_native_modules (Ask Gemini)
                                                                                                    Process: com.expensify.chat.e2edelta, PID: 27253
                                                                                                    com.facebook.react.common.JavascriptException: Error: Exception in HostFunction: Could not enqueue microtask because they are disabled in this runtime, js engine: hermes, stack:
                                                                                                    setImmediate@1:527723
                                                                                                    setDriver@1:1660584
                                                                                                    LocalForage@1:1659118
```

**Steps to reproduce:**

- Build the app for android in release mode and run
- Try to run the latest staging app from google play

**Comment by hannojg** [comment] 2024-10-25 09:14
@kirillzyusko can you comment here, so you can be assigned for this?

**Comment by kirillzyusko** [comment] 2024-10-25 09:27
Yes, sure
Commenting to be assigned to this task 👀

**Comment by mountiny** [comment] 2024-10-25 10:07
Sorry for the pings, i can handle it with @kirillzyusko

**Comment by kirillzyusko** [comment] 2024-10-25 11:32
Me and @WoLewicki figured out that this crash is caused by https://github.com/Expensify/App/pull/48160

At this point of time I don't think I can help here a lot so it's better to assign this issue to @WoLewicki 

@WoLewicki told me, that he will try to figure out, what exactly triggers a crash - if he'll be able to fix it he'll prepare a PR. If it takes a lot of time then he will simply disable bridgeless mode temporarily.

**Comment by hannojg** [comment] 2024-10-25 14:37
Did you figure what the root cause is, like why did turning it on caused this crash? Or is that something you're still working on understanding @WoLewicki ? (just very curious about this super weird bug)

**Comment by WoLewicki** [comment] 2024-10-25 15:22
Yeah, for now we managed to get to a point that:
- In bridgeless mode, `setImmediate` uses `queueMicrotask` under the hood: https://github.com/facebook/react-native/blob/143b9d172ca755e2457e8dfc6009eeef2475a4a1/packages/react-native/Libraries/Core/Timers/immediateShim.js#L44
- It triggers the exception here: https://github.com/facebook/hermes/blob/d964f6b125426f919ad30fb09ff09b9d5f041743/API/hermes/hermes.cpp#L1546 since it is not enabled in hermes.

It also happens on debug, but does not crash the app, that's why we didn't spot it since it's just a native crash. Now we are trying to understand why the flag for `queueMicrotask` is not enabled and if it should be at all.

**Comment by Beamanator** [comment] 2024-10-28 07:51
Requesting CP to get this fixed up, since the revert PRs have been merged:
- https://github.com/Expensify/App/pull/51489
- https://github.com/Expensify/Mobile-Expensify/pull/13253

**Comment by Beamanator** [comment] 2024-10-28 10:27
CP completed - @hannojg are you online to give it a test?

**Comment by hannojg** [comment] 2024-10-28 11:45
@kirillzyusko can you test please

**Comment by Beamanator** [comment] 2024-10-28 12:41
@kirillzyusko confirmed [here](https://expensify.slack.com/archives/C01GTK53T8Q/p1730119142006879?thread_ts=1729850746.015269&cid=C01GTK53T8Q) that the crash is not happening anymore!

**Comment by mountiny** [comment] 2024-10-28 12:43
Resolved

**Closed by mountiny** 2024-10-28 12:43 UTC
Labels: Engineering, Daily

**Comment by mountiny** [comment] 2024-10-28 12:47
To close the loop, we are going to look into re-enabling the bridgeless mode on android in the original issue https://github.com/Expensify/App/issues/48163

And also discussing [here](https://expensify.slack.com/archives/C04878MDF34/p1730119575801819?thread_ts=1729874239.681249&cid=C04878MDF34)
