### ISSUE TITLE
[Hold for payment] On the IOU message, the hover effect does not work after pressing Mark as unread

### ISSUE THREAD

**Issue by kavimuru** [Expensify/App#20686] opened 2023-06-13 15:44 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Open App and Go to any Chat
2. Press + from Composer > Request Money
3. Enter Any amount; Press the Next button > Press the Request button
3. Press on the requested money Thread message
4. Long press on the IOU message(Request Money Message). It will open the Context menu, and Press on Mark as unread
5. The context menu will close, and the mouse cursor will return to the IOU message.

## Expected Result: 
The hover effect(light green background) should be visible if Cursor is on the IOU message.
## Actual Result: 
The cursor is on the IOU message, but there is no Hover effect.
## Workaround:
Can the user still use Expensify without this being fixed? Have you informed them of the workaround?

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [x] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 1.3.27-2
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/43996225/a4a33c29-7ab1-429a-a2a1-560961b1ed1a

https://github.com/Expensify/App/assets/43996225/37d95dca-fa05-4b33-924f-68bf60e63a8e

**Expensify/Expensify Issue URL:**
**Issue reported by:** @jayeshmangwani 
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1686142659608929

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by sonialiap** [comment] 2023-06-18 19:33
I cannot reproduce. @jayeshmangwani is this still an issue?

https://github.com/Expensify/App/assets/17131195/2a2adc63-4bf3-4c95-bfd6-83f4f840e01b

**Comment by jayeshmangwani** [comment] 2023-06-19 05:06
@sonialiap Yes I am still able to reproduce this consistently

https://github.com/Expensify/App/assets/35371050/a22fe281-29c6-43ae-b82a-fefa21041b5c

**Comment by Tushu17** [comment] 2023-06-20 18:15
Hey, I reported this bug [here](https://expensify.slack.com/archives/C049HHMV9SM/p1683286164251049), and the issue was created [here](https://github.com/Expensify/App/issues/18519), but it was closed. I'm still able to repro this issue in staging as well as in production, So I think I should be considered as the original reporter.

**Comment by sonialiap** [comment] 2023-06-22 20:04
Are you guys testing on Windows computer? I'm wondering because neither Greg nor I can reproduce (we're both on Mac)

**Comment by Tushu17** [comment] 2023-06-25 20:27
Hi @sonialiap, this bug was fixed by [this PR](https://github.com/Expensify/App/pull/20561). The PR was merged 5 days ago to fix [this bug](https://github.com/Expensify/App/issues/16519). Is this eligible for the compensation. I think it still qualifies for the reporting compensation since it wasn't a duplicate issue and I have seen we provide compensation in such cases.

**Comment by sonialiap** [comment] 2023-06-26 12:33
Thanks Tushar! 

@jayeshmangwani offer sent for reporting the bug

**Comment by jayeshmangwani** [comment] 2023-06-26 12:37
> @jayeshmangwani offer sent for reporting the bug

Thanks for the offer, I have accepted

**Comment by Tushu17** [comment] 2023-06-26 13:07
> Thanks Tushar!
> 
> @jayeshmangwani offer sent for reporting the bug

I believe I should be compensated as the reporter of this bug since I reported it before @jayeshmangwani. You can read my comment [here](https://github.com/Expensify/App/issues/20686#issuecomment-1599281950).

> Hey, I reported this bug [here](https://expensify.slack.com/archives/C049HHMV9SM/p1683286164251049), and the issue was created [here](https://github.com/Expensify/App/issues/18519).

@jayeshmangwani Can you also check and confirm that I reported this bug first?

**Comment by sonialiap** [comment] 2023-06-29 17:25
Confirming with the team

**Comment by sonialiap** [comment] 2023-07-04 20:36
No answer yet

**Comment by sonialiap** [comment] 2023-07-06 10:36
@Tushu17 offer sent

**Comment by Tushu17** [comment] 2023-07-06 17:03
@sonialiap Offer accepted, Thank you.

**Comment by sonialiap** [comment] 2023-07-11 11:13
Was OOO, payment sent.

**Closed** 2023-07-11 11:14 UTC
Labels: Daily, Bug
