### ISSUE TITLE
Request money - Request view header is missing details

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#23269] opened 2023-07-20 12:30 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___
**Issue found when executing PR** https://github.com/Expensify/App/pull/22562
## Action Performed:
1. Open staging.new.expensify.com
2. Request IOU from user B
3. Open request view
5. Observe request header

## Expected Result:
Header details to appear without missing data

## Actual Result:
No header details; only username and avatar are displayed

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [x] Android / Chrome
- [ ] iOS / native
- [x] iOS / Safari
- [x] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 1.3.43.0

**Reproducible in staging?:** Yes

**Reproducible in production?:** Yes

**If this was caught during regression testing, add the test name, ID and link from TestRail:**

**Email or phone of affected tester (no customers):**

**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/78819774/34d2e74a-a1a8-499b-bd21-a8bb1b84d1c4

**Expensify/Expensify Issue URL:**

**Issue reported by:** Applause - Internal Team

**Slack conversation:**
<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01b1218ae0575ebba7</li>
        <li>Upwork Job ID: 1683452239429439488</li>
        <li>Last Price Increase: 2023-07-24</li>
    </ul>
</details>

**Comment by BhuvaneshPatil** [comment] 2023-07-20 14:03
bumping @neil-marcellini  - please have a look if changes for https://github.com/Expensify/App/issues/23102 causing this.

**Comment by trjExpensify** [comment] 2023-07-20 23:41
Hey @lanitochka17, the video in the OP doesn't match the steps listed. I can repro the bug though:

<img width="1511" alt="image" src="https://github.com/Expensify/App/assets/16232057/8ad238a9-ae45-4b1a-8cf3-d2cbc4a0f363">

CC: @grgia as well, it seems like something undid the work in your PR :)

**Comment by trjExpensify** [comment] 2023-07-24 11:17
@neil-marcellini, do we need to revert #23102 or what are the next steps here?

**Comment by grgia** [comment] 2023-07-24 11:26
checking if this will be fixed by https://github.com/Expensify/App/pull/22467/files

**Comment by grgia** [comment] 2023-07-24 11:57
Looks like the expense request avatars did get bonked, I'll fix them in the above PR

**Comment by grgia** [comment] 2023-07-24 12:57
I'm not sure what caused the header regression, still looking

**Comment by neil-marcellini** [comment] 2023-07-24 16:04
Thanks for taking this on @grgia! Did https://github.com/Expensify/App/issues/23102 cause the regression or something else?

**Comment by BhuvaneshPatil** [comment] 2023-07-24 19:28
I have tried debugging this and found the cause for this issue, I am submitting the proposal for the same. Let me know your thoughts

**Comment by BhuvaneshPatil** [comment] 2023-07-24 19:45
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
Request View header is missing details.

### What is the root cause of that problem?
We try to get the text below the name (in blue color) in `AvatarWithDisplayName`.


<img width="291" alt="Screenshot 2023-07-25 at 1 00 35 AM" src="https://github.com/Expensify/App/assets/27822551/139b5b78-5031-46c4-aca6-57d1bea3587d">

using `ReportUtils.getParentNavigationSubtitle()`, in case of Request Money it's IOU report - 
it falls into this condition - 

https://github.com/BhuvaneshPatil/App/blob/b7d17e0fd33b83e9fbd45146b6123b6323ece79e/src/libs/ReportUtils.js#L1193-L1197

As mentioned in the comment above function - 

https://github.com/BhuvaneshPatil/App/blob/b7d17e0fd33b83e9fbd45146b6123b6323ece79e/src/libs/ReportUtils.js#L1182C1-L1183C97

As the final report is IOU, we won't recursively calculate. This we return `displayName`

https://github.com/BhuvaneshPatil/App/blob/b7d17e0fd33b83e9fbd45146b6123b6323ece79e/src/libs/ReportUtils.js#L1194-L1196

This display name is empty. See below screenshot - 

<img width="634" alt="Screenshot 2023-07-25 at 1 06 58 AM" src="https://github.com/Expensify/App/assets/27822551/679b6490-15c7-4209-b399-73aa38e708b5">

I have tried testing this for multiple IOU reports, still the same.

Thus it doesn't the text in `AvatarWithDisplayNames`
https://github.com/BhuvaneshPatil/App/blob/b7d17e0fd33b83e9fbd45146b6123b6323ece79e/src/components/AvatarWithDisplayName.js#L93-L108

### What changes do you think we should make in order to solve the problem?
We shall change - 
```
rootReportName: lodashGet(report, 'displayName', ''),
```
to
```
rootReportName: lodashGet(report, 'displayName', '') || getReportName(report),
```

result - 
<img width="418" alt="Screenshot 2023-07-25 at 1 14 00 AM" src="https://github.com/Expensify/App/assets/27822551/3539bc55-9bae-42a8-9311-ab77f2c301d9">


### What alternative solutions did you explore? (Optional)

**Comment by trjExpensify** [comment] 2023-07-26 20:40
@grgia do we need to add the `reviewing` label here because of the linked PR: https://github.com/Expensify/App/issues/23269#issuecomment-1647769190

**Comment by grgia** [comment] 2023-07-27 12:27
Added reviewing label

**Comment by BhuvaneshPatil** [comment] 2023-07-27 17:08
Please have a look at [this](https://github.com/Expensify/App/issues/23269#issuecomment-1648508145). I understand that this is internal but It may give some direction for solution.

**Comment by trjExpensify** [comment] 2023-08-07 11:05
This was deployed a few days ago. The linked PR wasn't reviewed by C+ and this bug was reported by Applause, so I'm closing it out!

**Closed by trjExpensify** 2023-08-07 11:05 UTC
Labels: Reviewing, Daily, Internal, Bug
