### ISSUE TITLE
[$250] Web - Chat - When editing last message, edition composer is cut in half by main composer

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#49787] opened 2024-09-26 12:54 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 9.0.40-0
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**If this was caught during regression testing, add the test name, ID and link from TestRail:** https://expensify.testrail.io/index.php?/tests/view/5006320&group_by=cases:section_id&group_order=asc&group_id=292106
**Issue reported by:** Applause - Internal Team

## Action Performed:
1. Open the staging.new.expensify.com website
2. Open any chat with long history
3.Right click on the last sent message
4. Click on "Edit Message
5. Verify the edition composer, is fully visible

## Expected Result:
When editing the last sent message on a chat, the edition composer, should be fully visible

## Actual Result:
When the user edits the last message on a chat with long history, the edition composer, gets cutted in half by the main compose box

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details> 

https://github.com/user-attachments/assets/cc504784-8b07-4252-bd57-74e24c994df5

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~021843415078855833463</li>
        <li>Upwork Job ID: 1843415078855833463</li>
        <li>Last Price Increase: 2024-11-18</li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @abdulrahuman5196</details>

**Comment by lanitochka17** [comment] 2024-09-26 12:55
@VictoriaExpensify  FYI I haven't added the External label as I wasn't 100% sure about this issue. Please take a look and add the label if you agree it's a bug and can be handled by external contributors

**Comment by MuaazArshad** [comment] 2024-09-26 14:55
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
Web - Chat - When editing last message, edition composer is cutted in half by main composer
### What is the root cause of that problem?
We are currently using the built-in View component from React Native here.
https://github.com/Expensify/App/blob/b9f8b86ef5c3034c1387fa6c636b071bdaf3092e/src/pages/home/report/ReportActionItemMessageEdit.tsx#L499-L552

### What changes do you think we should make in order to solve the problem?

We should use ScrollView to ensure proper scrolling behaviour.
```
                <ScrollView style={[StyleUtils.getContainerComposeStyles(), styles.textInputComposeBorder]}>
                        <Composer
                            multiline
                            ref={(el: TextInput & HTMLTextAreaElement) => {
                                textInputRef.current = el;
                                if (typeof forwardedRef === 'function') {
                                    forwardedRef(el);
                                } else if (forwardedRef) {
                                    // eslint-disable-next-line no-param-reassign
                                    forwardedRef.current = el;
                                }
                            }}
                            id={messageEditInput}
                            onChangeText={updateDraft} // Debounced saveDraftComment
                            onKeyPress={triggerSaveOrCancel}
                            value={draft}
                            maxLines={shouldUseNarrowLayout ? CONST.COMPOSER.MAX_LINES_SMALL_SCREEN : CONST.COMPOSER.MAX_LINES} // This is the same that slack has
                            style={[styles.textInputCompose, styles.flex1, styles.bgTransparent]}
                            onFocus={() => {
                                setIsFocused(true);
                                InteractionManager.runAfterInteractions(() => {
                                    requestAnimationFrame(() => {
                                        reportScrollManager.scrollToIndex(index, true);
                                    });
                                });
                                setShouldShowComposeInputKeyboardAware(false);
                                // The last composer that had focus should re-gain focus
                                setUpComposeFocusManager();

                                // Clear active report action when another action gets focused
                                if (!EmojiPickerAction.isActive(action.reportActionID)) {
                                    EmojiPickerAction.clearActive();
                                }
                                if (!ReportActionContextMenu.isActiveReportAction(action.reportActionID)) {
                                    ReportActionContextMenu.clearActiveReportAction();
                                }
                            }}
                            onBlur={(event: NativeSyntheticEvent<TextInputFocusEventData>) => {
                                setIsFocused(false);
                                const relatedTargetId = event.nativeEvent?.relatedTarget?.id;
                                // eslint-disable-next-line @typescript-eslint/prefer-nullish-coalescing
                                if ((relatedTargetId && [messageEditInput, emojiButtonID].includes(relatedTargetId)) || EmojiPickerAction.isEmojiPickerVisible()) {
                                    return;
                                }
                                setShouldShowComposeInputKeyboardAware(true);
                            }}
                            onLayout={reportActionItemEventHandler.handleComposerLayoutChange(reportScrollManager, index)}
                            selection={selection}
                            onSelectionChange={(e) => setSelection(e.nativeEvent.selection)}
                            isGroupPolicyReport={isGroupPolicyReport}
                            shouldCalculateCaretPosition
                            onScroll={onSaveScrollAndHideSuggestionMenu}
                        />
                    </ScrollView>
```

### What alternative solutions did you explore? (Optional)

**Comment by VictoriaExpensify** [comment] 2024-09-30 10:09
I haven't had a chance to look at this yet, will take a look tomorrow

**Comment by VictoriaExpensify** [comment] 2024-10-02 21:55
Unable to reproduce this issue:

![Uploading 2024-10-03_07-53-12 (1).gif…]()

**Comment by VictoriaExpensify** [comment] 2024-10-02 21:56
@

**Comment by VictoriaExpensify** [comment] 2024-10-03 05:59
asking for a re-test https://expensify.slack.com/archives/C9YU7BX5M/p1727935116718019

**Comment by MuaazArshad** [comment] 2024-10-03 12:43
> @MuaazArshad - were you able to reproduce this?

Yes, and still reproducible.

https://github.com/user-attachments/assets/283cb1b4-4260-409e-8842-e21d1e0fcc91

**Comment by m-natarajan** [comment] 2024-10-04 13:51
Able to reproduce

https://github.com/user-attachments/assets/b2ce8122-b763-4c56-b94e-51707892916e

**Comment by abdulrahuman5196** [comment] 2024-10-09 18:17
I am unable to reproduce this issue. Any way to reproduce this reliabily?


https://github.com/user-attachments/assets/7cd658cb-9ab1-456e-8882-654817efced3

**Comment by abdulrahuman5196** [comment] 2024-10-17 13:07
@VictoriaExpensify gentle ping on this https://github.com/Expensify/App/issues/49787#issuecomment-2402983637

**Comment by abdulrahuman5196** [comment] 2024-10-23 17:42
> @VictoriaExpensify gentle ping on this [#49787 (comment)](https://github.com/Expensify/App/issues/49787#issuecomment-2402983637)

@VictoriaExpensify Gentle ping on this

**Comment by wildan-m** [comment] 2024-10-29 06:42
## Proposal

### Please re-state the problem that we are trying to solve in this issue.

When editing the last message in the web chat, the edition composer is cut in half by the main composer.

### What is the root cause of that problem?

When we press edit, the offset position of scroll is not perfectly pointed to the reportAction item, since the `ReportActionItem` and `ReportActionItemMessageEdit` might have different height this make the editor position might a little cut.

I can consistently reproduce the issue with the following step

1. Open the app
2. Create a message with 2 or more lines
3. Scroll to the top of text ensure 2nd and the last message content hidden
4. Right click on the last sent message
5. Click on "Edit Message

### What changes do you think we should make in order to solve the problem?
To ensure proper offset position while editing, scroll to the start of the edited report action when it's the last report action. It may be necessary to remove `index === 0` based on the desired outcome.

Modify this `useEffect`

https://github.com/Expensify/App/blob/db592c9c9f56a6ce8208b898c1e5ba1eb864aae8/src/pages/home/report/ReportActionItem.tsx#L267-L273

To 

```tsx

    useEffect(() => {
        if (prevDraftMessage !== undefined || draftMessage === undefined) {
            return;
        }

        if(index === 0)
        {
            InteractionManager.runAfterInteractions(() => {
                requestAnimationFrame(() => {
                    reportScrollManager.scrollToIndex(index);
                });
            })
        }

        focusComposerWithDelay(textInputRef.current)(true);
    }, [prevDraftMessage, draftMessage]);

```

Ensure proper scrolling functionality by using `runAfterInteractions` and `requestAnimationFrame`, which are also utilized in other sections.

**Result -- Before(left) - After(Right)** 

https://github.com/user-attachments/assets/31ec8044-01b1-4276-91a3-b339c27f6e53

[Branch for this solution](https://github.com/Expensify/App/compare/main...wildan-m:wildan/fix/49787-fix-last-message-postion-when-edit?expand=1)
### What alternative solutions did you explore? (Optional)
N/A

**Comment by wildan-m** [comment] 2024-10-29 06:43
> I am unable to reproduce this issue. Any way to reproduce this reliabily?

@abdulrahuman5196 you might find the answer in my proposal https://github.com/Expensify/App/issues/49787#issuecomment-2443338173

**Comment by VictoriaExpensify** [comment] 2024-10-29 10:13
I haven't been able to reproduce the issue. Applying the retest label

**Comment by wildan-m** [comment] 2024-10-30 02:57
@VictoriaExpensify can you test with this reproduction steps?

> I can consistently reproduce the issue with the following step
> 
> 1. Open the app
> 2. Create a message with 2 or more lines
> 3. Scroll to the top of text ensure 2nd and the last message content hidden
> 4. Right click on the last sent message
> 5. Click on "Edit Message

Reproduction video and result can be seen here https://github.com/Expensify/App/issues/49787#issuecomment-2443338173

**Comment by MuaazArshad** [comment] 2024-10-30 13:10
Able to reproduce using the provided steps.

https://github.com/user-attachments/assets/3d53c2fc-f26f-43a7-aa3b-0ba4d3ef7f96

**Comment by VictoriaExpensify** [comment] 2024-11-13 10:32
Yup, this is reproducible following the steps given. Let's move forward here

**Comment by abdulrahuman5196** [comment] 2024-11-13 18:37
Hi, I am still unable to repro the issue. I reached out in C+ channel if any one is able to repro this and takeover.
https://expensify.slack.com/archives/C02NK2DQWUX/p1731523034411719

**Comment by allroundexperts** [comment] 2024-11-13 18:51
I was able to reproduce. Will post a video shortly as well.

**Comment by allroundexperts** [comment] 2024-11-13 22:26
Was able to reproduce:

https://github.com/user-attachments/assets/dd02d9e3-74f5-42a0-87a7-5e0bac6e1a2a

**Comment by allroundexperts** [comment] 2024-11-13 22:27
@VictoriaExpensify Can you please assign this to me?

**Comment by abdulrahuman5196** [comment] 2024-11-14 11:18
@VictoriaExpensify Kindly assign this issue to @allroundexperts for takeover. Unassigned myself.

**Comment by mvtglobally** [comment] 2024-11-23 03:25
Issue not reproducible during KI retests. (First week)

**Comment by allroundexperts** [comment] 2024-11-24 22:42
This seems to have been fixed. I am unable to reproduce it any more.

**Comment by VictoriaExpensify** [comment] 2024-11-28 02:41
Closing this out as it's been resolved. Thanks all for your help!

**Closed by VictoriaExpensify** 2024-11-28 02:41 UTC
Labels: External, Daily, Overdue, Bug
