### ISSUE TITLE
[HOLD for payment 2023-08-24] [$2000] [ExpensifyHelp] Implement a search functionality on https://help.expensify.com

### ISSUE THREAD

**Issue by marcochavezf** [Expensify/App#23978] opened 2023-08-01 05:10 UTC
We want to enhance the user experience on our [help site](https://help.expensify.com) by integrating a search functionality. This will allow users to find specific information quickly and efficiently.

Our plan is to utilize [Google's Programmable Search Engine](https://developers.google.com/custom-search/docs/tutorial/introduction) for this task, as it is a reliable and easy-to-setup solution. Specifically, we'd like to use the XML configuration (https://developers.google.com/custom-search/docs/basics) rather than manual setup through the Google Control Panel UI. This will facilitate future changes by our engineering team through the usual pull request process.

In your proposal, please be sure to address the following key aspects:

- **Modification Plan**: Outline which files and what code of the ExpensifyHelp project will be modified to incorporate the search functionality.

- **Right-hand Panel Implementation**: Describe how the right-hand panel will be designed and implemented, and how it can be displayed and hidden. The right-hand panel should host the search bar and the results display.

- **Results Display**: Explain how the search results will be displayed in the right-hand panel. 

- **Programmable Search Engine Implementation**: Describe how the Programmable Search Engine will be implemented to only show results from https://help.expensify.com/.

The proposal doesn't actually require extensive detail, but it's a bonus if you provide it. We aim to confirm your familiarity with the [ExpensifyHelp code](https://github.com/Expensify/App/tree/main/docs#welcome-to-the-expensify-help-site) and ensure that you can carry out the implementation without issues.

Mockups:

![HelpDot](https://github.com/Expensify/App/assets/6829422/f2125ff8-3c57-4d57-ba84-975103e951d9)

![HelpDot-1](https://github.com/Expensify/App/assets/6829422/52e3abcb-3d0d-491b-9426-18acbd0c6643)

![HelpDot-2](https://github.com/Expensify/App/assets/6829422/08468fd2-b6aa-4a08-a174-d87d5b35d75e)

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~016883d3a09768972a</li>
        <li>Upwork Job ID: 1686243072505339904</li>
        <li>Last Price Increase: 2023-08-01</li>
    </ul>
</details>

**Comment by ishpaul777** [comment] 2023-08-01 05:12
Adding detail soon...

**Comment by marcochavezf** [comment] 2023-08-01 05:12
Changing the base payment to $2000 given the complexity of this implementation.

**Comment by payal-lathidadiya** [comment] 2023-08-01 06:06
This is Interesting. I'd like to work on this new feature implementation. 
I'll analyse in details and prepare a proposal.

**Comment by cubuspl42** [comment] 2023-08-01 07:22
@marcochavezf This may by a silly question, but where does the relevant source, configuration, etc. reside? I always believed that expensify.com is so-called "old dot" and external contributors don't have access to it.

**Comment by nzmsakib** [comment] 2023-08-01 07:44
Contributor details
Your Expensify account email: engrsakibcse@outlook.com
Upwork Profile Link: https://www.upwork.com/freelancers/~011df441739393295c

**Comment by aditygrg2** [comment] 2023-08-01 07:47
This seems cool!
Interested to contribute in this project. Would submit a proposal soon.

**Comment by aditygrg2** [comment] 2023-08-01 07:49
Contributor details
Your Expensify account email: adityagarg.1747@gmail.com
Upwork Profile Link: https://www.upwork.com/freelancers/~01889386d30b9647d6

**Comment by studentofcoding** [comment] 2023-08-01 07:53
# Proposal

## Modification Plan
* Add flex container to contain Logo & search icon button inside lhn-header container In default.html.
* Add toggleSidebarSearch() in assets/js/main.js, to handle the Search Sidebar.
* Add search-sidebar element into default.html & use `<div class="gcse-searchbox"></div>
            <div class="gcse-searchresults"></div>` into it
* Change the style of search-bar & result component to accommodate the template

### Right-hand Panel Implementation
* Using the Search button icon, but we can onkeypress event to a handler function into it also

### Results Display
Programmable Search Engine Implementation , we have to restrict the result to https://help.expensify.com/*

### Demo:
* POC of Search Sidebar functionality is live here (with the toggle sidebar function will be developed next): https://studentofcoding-expensify-docs-search.vercel.app/

cc: @marcochavezf

**Comment by saqixpro** [comment] 2023-08-01 08:40
Contributor details
Your Expensify account email: saqib@itdunya.com
Upwork Profile Link: https://www.upwork.com/freelancers/saqixpro

**Comment by aditygrg2** [comment] 2023-08-01 09:07
## Proposal

### Please re-state the problem that we are trying to solve in this issue.

Implementing search functionality on https://help.expensify.com

### What is the root cause of that problem?

This is a new improvement to provide better user experience.

### What changes do you think we should make in order to solve the problem?

## Modification Plan: 

The below paths are to be taken in reference to the https://expensify.com/help code i.e, inside the docs folder

1. Inside `lhn-header` div inside `default.html`, a search icon needs to be added.
2. The search bar div can be created in a different file, which can be included outside `lhn`
3. The design part including the backdrop and transitions of this needs to implemented in `_main.scss`
4. The toggle part of the right-panel is to be implemented in `main.js`

## Right-hand Panel Implementation: 

1. In the `default.html` file, a new `div` element containing a search bar will be introduced besides the existing "ExpensifyHelp" title. This `div` will be placed outside the element with the ID "lhn."
2. In the same `default.html` file, another `div` will be included outside the element with ID "lhn" to hold both the search bar and the content. Initially, this `div` will be hidden using the CSS class "negative-right" with the CSS property "right" set to "-100%."
3. The functionality to show and hide this `div` will be implemented in the `main.js` file. Specifically, when the user clicks the search bar, the "negative-right" class will be added to the `div`, causing it to slide into view from the right. Clicking on the `x` icon or outside the search div will remove the "negative-right" class, causing the `div` to slide out of view, returning to its initial hidden state.
4. The `main.js` file will handle the logic to toggle the visibility of the hidden `div` based on user interaction with the search bar.

## Results Display

1. The search results will contain a title and a short description which can be interpreted using GPSE
2. The CSS of it will already be managed on the RHP implementation as discussed above
3. If no results appear on this page for a user's query "Send a message button" can be shown as seen on the homepage of the Expensify help page.

Programmable Search Engine Implementation: 

1. The present sitemap is not good for search queries, so we might need to create a new sitemap for the Expensify help page on Google Search Console. This can be easily done by using sitemap creators online and improving that manually.
2. To just search for specific links, Annotations can be used that allow specific pages to be searched which can be implemented in a new `annotations.xml` file
3. We can use LLM models, to get some important synonyms and use BOOST, FILTER, and ELIMINATE to score the search results properly. General synonyms can be added in the initial run but this can be a major improvement for future versions.

### What alternative solutions did you explore? 
We might save search queries in the local storage of the user, so revisiting the help page will show the top 2-3 queries searched in history.

**Comment by payal-lathidadiya** [comment] 2023-08-01 15:24
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
Implement a search functionality on https://help.expensify.com

### What is the root cause of that problem?
This is a New feature requirement

### What changes do you think we should make in order to solve the problem?

#### Modification Plan: 
1. Create new Search engine project in `https://programmablesearchengine.google.com/`
2. Add a new section in default.html for sidebar container div to show right hand side overlay search panel.
3. Add new search button beside logo to trigger opening search panel.
4. Add below in <head> of default.html
    `<script async src="https://cse.google.com/cse.js?cx=<SEARCH_ENGINE_ID>"></script> `
    (we'd probably have to update CSP rule to allow script src from` https://www.cse.google.com` and other related resources and assets like external styles from cdn or sub domain sources)
5. Create new script function openSearchPanel() and closeSearchPanel() in `main.js` to handle visibility the search panel through styling.

#### Right-hand Panel Implementation: 

1. Add header with `Search` caption and close icon button.
2. Bind `closeSearchPanel()` with close icon button click to hide search panel.
3. Add `<div class="gcse-searchbox"></div> <div class="gcse-searchresults"></div>` into sidebar container section of default.html
4. Add required style in main.scss to customize search control and search result list as per expensify theme given in mocks.
5. We should add id to the right panel side bar container div and set style as `display: none` or `visibility: hidden`.
6. In `openSearchPanel` implement logic to show right side panel div.
7. Bind `openSearchPanel` with click event of search icon button beside logo

#### Results Display: 
No addition programming is required to trigger search logic and fetching/binding search result.

`<div class="gcse-searchresults"></div>` will display search result. only required CSS can be applied to show style look and feel as per expensify theme and mocks.

#### Programmable Search Engine Implementation: 

Programmable Search Engine should be configured only show results from https://help.expensify.com/.
Create below new annotations.xml file
```xml
<Annotations>
    <Annotation about="Expensify help" score="1.0">
        <Label name="_include_"/>
        <AdditionalData attribute="original_url" value="www.help.expensify.com/*"/>
    </Annotation>
</Annotations>
```

**Comment by saalimzafar** [comment] 2023-08-01 20:44
**Modification Plan:**
For the successful implementation of the search functionality, the following files in the ExpensifyHelp project will be modified:

1. `default.html` (located in the `_layouts` folder): We will modify this file to add the right-hand panel, which will contain the search bar and the container for displaying search results.

2. `styles.css` (located in the `assets/css` folder): CSS styles will be applied to this file to properly position and style the right-hand panel and the search bar for a visually appealing user interface.

3. `main.js` (located in the `assets/js` folder): In this file, we will implement JavaScript code to handle the search functionality. The code will manage user interactions, fetch search results from the Google Programmable Search Engine using the XML configuration, and dynamically update the right-hand panel with the retrieved search results.

**Right-hand Panel Implementation:**
- Design: The right-hand panel will be designed with a fixed position on the right side of the screen, ensuring it remains visible to users at all times.
- Display and Hidden: Initially, the right-hand panel will be hidden and can be displayed upon user interaction with the search bar or a dedicated search icon.

**Results Display:**
- Search Logic: User-entered search queries will be sent to the Google Programmable Search Engine using the XML configuration, and the engine will return relevant search results based on the query.
- Displaying Results: JavaScript DOM manipulation will be utilized to dynamically render the search results in the right-hand panel, presenting each result as a clickable link for users to access the relevant help articles.

**Programmable Search Engine Implementation:**
- XML Configuration: The XML configuration for the Google Programmable Search Engine will be set up using the control panel UI provided by Google. It will be configured to show results exclusively from the designated URL: https://help.expensify.com/.
- API Key: We will securely store and use an authorized API key in the JavaScript code to access the Programmable Search Engine.

**Conclusion:**
By implementing the proposed search functionality with Google's Programmable Search Engine, the ExpensifyHelp site will be equipped with a powerful and user-friendly search feature. Users will have a seamless experience finding specific information, thereby enhancing their overall satisfaction with the help site. The use of XML configuration ensures flexibility for future updates by the engineering team through standard pull request procedures, contributing to the continuous improvement of the ExpensifyHelp platform.

**Comment by kmwamasali** [comment] 2023-08-03 15:38
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
Implement a search functionality on https://help.expensify.com

### What is the root cause of that problem?
Expensify wants to enhance the user experience on our [help site](https://help.expensify.com/) by integrating a search functionality. This will allow users to find specific information quickly and efficiently.

### What changes do you think we should make in order to solve the problem?
### Modification Plan
- Modify the div block with class `lhn-header` in the `**_layouts/default.html**` file to add the search icon and add appropriate classes and id so it can be referenced by the JavaScript to trigger the Right-hand search & results panel
- Add search icon svg to `**assets/images**` 
- Modify the `**assets/js/main.js**` to include the logic to handle Right-hand Panel search and results
- Update `**_sass/main.css**` to include necessary styles according to design spec including styles for when RHP is displayed and when it's not visible
- Add a new include partial `**_includes/rhp-template.html**` to describe the frontmatter for the Right-hand Panel

### Right-hand Panel Implementation
- Modify/Add the necessary _**rhp-template**_ to describe the front matter for the panel search-bar and results list
- Use CSS styles for showing and hiding the panel
- Add an event listener to the _**main.js**_ to trigger the display and hiding of the panel by adding or removing the appropriate CSS class when the search or close buttons 

### Results Display
- Add an event listener to capture the keys entered in the search box and use a fetch or axios to submit to get the results
- Add JavaScript logic to filter the results data to only display title with link and description as required in design spec
- Display the results as an unordered list and add the necessary styles to match the design spec
- Add synonyms to the XML to like _money owed_, _repay debts_ ..etc and other common words that would help improve the search results

### Programmable Search Engine Implementation
- Specify in the Programmable Search Engine control panel that the search will be restricted to 10 sites or less
- Make requests to the appropriate Custom Search Site Restricted JSON API with the required parameter's
`https://www.googleapis.com/customsearch/v1/siterestrict?[parameters]`
- Use the Programmable Search XML Format and define the appropriate annotations

**Comment by sophiepintoraetz** [comment] 2023-08-03 23:18
@marcochavezf @eVoloshchak - seems like we have a few good proposals to start reviewing?

**Comment by marcochavezf** [comment] 2023-08-03 23:38
@eVoloshchak let me know if you can review the proposals soon. I can take a look at them tomorrow.

**Comment by marcochavezf** [comment] 2023-08-04 19:08
> @marcochavezf This may by a silly question, but where does the relevant source, configuration, etc. reside? I always believed that expensify.com is so-called "old dot" and external contributors don't have access to it.

@cubuspl42 ah this is for the Expensify help site, which is different from NewDot and OldDot, but the code resides in the [NewDot/docs](https://github.com/Expensify/App/tree/main/docs) folder

**Comment by marcochavezf** [comment] 2023-08-04 19:46
Wow there are some very good proposals here! And it's challenging to pick just one. Your efforts in crafting these proposals are truly appreciated. 

While many of them are detailed in implementation (something I greatly value), I'm inclined to choose [this one](https://github.com/Expensify/App/issues/23978#issuecomment-1659762731). It includes a POC, and even though this was not requested, I appreciate the additional effort taken to create and publish it.

Assigning @studentofcoding 🚀

**Comment by marcochavezf** [comment] 2023-08-04 19:51
> We can use LLM models, to get some important synonyms and use BOOST, FILTER, and ELIMINATE to score the search results properly. General synonyms can be added in the initial run but this can be a major improvement for future versions.

@aditygrg2 This is a good idea for a follow-up implementation! I invite you to post it as [idea](https://github.com/Expensify/App/blob/ebe6aeaaff68f552d9704997531a3b4a849b0b09/contributingGuides/CONTRIBUTING.md#posting-ideas) in the [expensify-open-source channel](https://expensify.slack.com/archives/C01GTK53T8Q) (or as [problem/solution statement](https://github.com/Expensify/App/blob/ebe6aeaaff68f552d9704997531a3b4a849b0b09/contributingGuides/HOW_TO_CREATE_A_PLAN.md)) after the implementation is done and tag me if you do.

**Comment by studentofcoding** [comment] 2023-08-05 05:52
Thanks @marcochavezf for the decision! As I'm a new Contributor, could you share where I can ask for the details on this? (some alignment, deadline, & procedure)

Meanwhile, I'll apply on Upwork today, & after all is clear, I'll Start developing right away Next Week.

Cheers!

**Comment by studentofcoding** [comment] 2023-08-05 06:06
Anyway, just applied to the job @marcochavezf

**Comment by aditygrg2** [comment] 2023-08-05 08:17
> > We can use LLM models, to get some important synonyms and use BOOST, FILTER, and ELIMINATE to score the search results properly. General synonyms can be added in the initial run but this can be a major improvement for future versions.
> 
> @aditygrg2 This is a good idea for a follow-up implementation! I invite you to post it as [idea](https://github.com/Expensify/App/blob/ebe6aeaaff68f552d9704997531a3b4a849b0b09/contributingGuides/CONTRIBUTING.md#posting-ideas) in the [expensify-open-source channel](https://expensify.slack.com/archives/C01GTK53T8Q) (or as [problem/solution statement](https://github.com/Expensify/App/blob/ebe6aeaaff68f552d9704997531a3b4a849b0b09/contributingGuides/HOW_TO_CREATE_A_PLAN.md)) after the implementation is done and tag me if you do.

Sure @marcochavezf Let's wait for this to be implemented.

**Comment by kmwamasali** [comment] 2023-08-05 08:54
@marcochavezf @studentofcoding 
I also thought I should point out that the chosen proposals incorrectly referenced using annotations instead of using custom search site API as stated in the docs. I assume correctness is also a factor and thought I should share the research.
https://developers.google.com/custom-search/v1/site_restricted_api

**Comment by marcochavezf** [comment] 2023-08-07 16:10
> Thanks @marcochavezf for the decision! As I'm a new Contributor, could you share where I can ask for the details on this? (some alignment, deadline, & procedure)
> 
> Meanwhile, I'll apply on Upwork today, & after all is clear, I'll Start developing right away Next Week.
> 
> Cheers!

Hi @studentofcoding, these are the [guidelines](https://github.com/Expensify/App/blob/ebe6aeaaff68f552d9704997531a3b4a849b0b09/contributingGuides/CONTRIBUTING.md#begin-coding-your-solution-in-a-pull-request) to start coding the solution.

**Comment by studentofcoding** [comment] 2023-08-07 16:36
Thanks @marcochavezf. I just want to follow up that the Upwork contract is still pending (not yet accepted) and have 1 questions regarding the Payment timeline

Hey guys I have some questions on the Payment timeline section

> Payment timeline all based on the day and timestamp the contributor has an accepted proposal and is assigned to the Github issue

Merged PR within 3 business days (72 hours) - 50% bonus

1. Whats the details on this timeline. Is it after PR is ready until merged, or when some contributor is selected up until PR is merged?
2. If we’re assigned on Friday and we are still waiting for Upwork contract to be approved, will it start counting after Upwork contract or when the contributor is assigned?

Thanks

**Comment by marcochavezf** [comment] 2023-08-07 16:45
> @marcochavezf @studentofcoding I also thought I should point out that the chosen proposals incorrectly referenced using annotations instead of using custom search site API as stated in the docs. I assume correctness is also a factor and thought I should share the research. It also helps avoid the daily query limit which might be important to a high traffic site https://developers.google.com/custom-search/v1/site_restricted_api

Oh thanks for pointing out that @kmwamasali, @studentofcoding thoughts about this? How much will the solution change with the custom search site API?

**Comment by studentofcoding** [comment] 2023-08-07 17:10
> > @marcochavezf @studentofcoding I also thought I should point out that the chosen proposals incorrectly referenced using annotations instead of using custom search site API as stated in the docs. I assume correctness is also a factor and thought I should share the research. It also helps avoid the daily query limit which might be important to a high traffic site https://developers.google.com/custom-search/v1/site_restricted_api
> 
> 
> 
> Oh thanks for pointing out that @kmwamasali, @studentofcoding thoughts about this? How much will the solution change with the custom search site API?

The only details change for this are on using 'fetch' and 'onKeyPress' to handle this. In which already delivered on the POC aswell @marcochavezf

**Comment by marcochavezf** [comment] 2023-08-07 17:10
> Thanks @marcochavezf. I just want to follow up that the Upwork contract is still pending (not yet accepted) and have 1 questions regarding the Payment timeline
> 
> > Payment timeline all based on the day and timestamp the contributor has an accepted proposal and is assigned to the Github issue
> 
> > Merged PR within 3 business days (72 hours) - 50% bonus
> 
> 1. Whats the details on this timeline. Is it after PR is ready until merged, or when some contributor is selected up until PR is merged?
> 2. If we’re assigned on Friday and we are still waiting for Upwork contract to be approved, will it start counting after Upwork contract or when the contributor is assigned?
> 
> Thanks

Ah the bonus is based on the time you're assigned. For "the contributor has an accepted proposal", we're referring to the C+ in this case. We're going to update the documentation to reflect this better.

**Comment by kmwamasali** [comment] 2023-08-07 17:14
@marcochavezf @studentofcoding glad to know my solution will be used for your benefit

**Comment by marcochavezf** [comment] 2023-08-07 18:15
> @marcochavezf @studentofcoding glad to know my solution will be used for your benefit

@kmwamasali I think we can arrange a little compensation for you if it's included in the PR. I was unfamiliar with the custom search site API, but it sounds like a good addition. We can discuss more about it after the PR is up.

**Comment by kmwamasali** [comment] 2023-08-07 18:36
@marcochavezf that sounds good, I will wait to see how it turns out

**Comment by marcochavezf** [comment] 2023-08-09 17:15
Hi @shawnborton, can we have your review for the UI changes [here](https://github.com/Expensify/App/pull/24299#issue-1842096282)?

**Comment by sophiepintoraetz** [comment] 2023-08-23 23:06
Payouts due:

Issue Reporter: $250 N/A (Marco created the issue)
Contributor: $2000 @studentofcoding 
Contributor+: $2000 N/A (Marco)

Eligible for 50% #urgency bonus? N

@marcochavezf - I think the original timeframe was in this comment [here](https://github.com/Expensify/App/issues/23978#issuecomment-1675471695) (5 days), right? So there's no penalty applied?

**Comment by sophiepintoraetz** [comment] 2023-08-23 23:16
Payment done - releasing payment
<img width="478" alt="image" src="https://github.com/Expensify/App/assets/42940078/dd7a80c6-e895-423d-929a-cb8d23fb111c">

**Closed by sophiepintoraetz** 2023-08-23 23:16 UTC
Labels: External, Daily, Improvement, Design, Awaiting Payment

**Comment by studentofcoding** [comment] 2023-08-24 02:25
> Payouts due:
> 
> 
> 
> Issue Reporter: $250 N/A (Marco created the issue)
> 
> Contributor: $2000 @studentofcoding 
> 
> Contributor+: $2000 N/A (Marco)
> 
> 
> 
> Eligible for 50% #urgency bonus? N
> 
> 
> 
> @marcochavezf - I think the original timeframe was in this comment [here](https://github.com/Expensify/App/issues/23978#issuecomment-1675471695) (5 days), right? So there's no penalty applied?

Yes it's on 5 days @sophiepintoraetz 

Thanks for approving
