### ISSUE TITLE
[$500] Android - When you click on 'account' and 'amount' right after each other, the amount value gets cut off

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#27259] opened 2023-09-12 14:52 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Open request money
2. Change the tab to manual
3. Enter amount and tap next
4. Tap on account then the amount immediately

## Expected Result:
The amount should preview the amount correctly without cutoff

## Actual Result:
The amount gets cut off on the right side for ~5 seconds

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [ ] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 1.3.68.12
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/93399543/3f5b8d87-10d5-469c-8de9-51f44669f65c

https://github.com/Expensify/App/assets/93399543/ee2b4afe-7ed1-4fc0-84db-0b788567ddea

**Expensify/Expensify Issue URL:**
**Issue reported by:** @jo-ui
**Slack conversation:**  https://expensify.slack.com/archives/C049HHMV9SM/p1694233345077489

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01912000cb3861249d</li>
        <li>Upwork Job ID: 1701609662613942272</li>
        <li>Last Price Increase: 2023-10-03</li>
    </ul>
</details>

**Comment by mercurystudio99** [comment] 2023-09-12 15:33
Hi, I checked the video. The problem is the width of the text including amount.
I think the width of the text is changed dynamically.
It is needed to fix the width
Thanks
Upwork freelancer

**Comment by ishpaul777** [comment] 2023-09-12 17:24
## Proposal

### Problem 
When you click on 'account' and 'amount' simultaneously, the amount value gets cut off

### Root Cause 
When the user clicks on one of the items, the delay before navigation occurs to take the user to the next screen, which allows the user to be able to click on another item. Result in a lag when switching screens
causing this issue.

### Changes
We can ignore all other actions when navigation is in progress, by using `useFocusEffect` in `MenuItemWithTopDescription`

```jsx
   const isNavigating = React.useRef(false);

    useFocusEffect( React.useCallback(() => {
        isNavigating.current = false;

        return () => {
            isNavigating.current = true;
        }
    }, []));


    return (
        <MenuItem
            // eslint-disable-next-line react/jsx-props-no-spreading
            {...props}
            onPress={() => {
                if (isNavigating.current) {
                    return;
                }
                props.onPress();
            }}
 />
```

**Comment by mercurystudio99** [comment] 2023-09-12 20:21
Contributor details
Your Expensify account email: mercurystudio99@gmail.com
Upwork Profile Link: https://www.upwork.com/freelancers/~0105f9a38c04b2f6d3

**Comment by mercurystudio99** [comment] 2023-09-12 20:30
I also think that the suggestion you mentioned is great.

**Comment by mallenexpensify** [comment] 2023-09-14 07:11
Couple things... 
1. I don't have an android phone and I can't tap two things at once if testing via browserstack, looking for help from BZ [here](https://expensify.slack.com/archives/C01SKUP7QR0/p1694675346508299)
2. @ArekChr are you able to reproduce?
3. I haven't come across any/many 'tap twice at once' issues.  I wonder if there is expected flows for any of these since the action isn't _normal_.   ie. if two taps equal two different actions, which one should be shows?

**Comment by mallenexpensify** [comment] 2023-09-14 07:25
Going to close, we don't have expected behaviours for tapping twice at the same time.

**Comment by jo-ui** [comment] 2023-09-14 07:35
@mallenexpensify It is not tapping twice at the same time, you just tap on the account and then tap on amount you don't have to be even quick that much see it on the video attached

**Comment by mallenexpensify** [comment] 2023-09-14 09:38
Thanks for the comment @jo-ui , I was able to reproduce, the amount gets cut off for ~5 seconds when you click the amount right after clicking the user. I'll update the title and OP. 
<img width="383" alt="image" src="https://github.com/Expensify/App/assets/22508304/560e3639-1c9d-4ffa-8d9b-92ee2cd7d873">
and

https://github.com/Expensify/App/assets/22508304/022cbc87-c9a0-4c11-a5b1-96336e03a683

@ArekChr can you provide any thoughts and also review the proposals above? Thx

**Comment by ArekChr** [comment] 2023-09-14 12:00
I'm wondering if this issue is connected to [another one we have](https://github.com/Expensify/App/issues/26628). Right now, the input width is set to increase by 2 pixels when the component mounts. This causes a problem if the initial width is zero. Maybe we should leave the width undefined when it's initially zero to avoid this issue. Perhaps we should put this on hold until the related issue is sorted out.

**Comment by mallenexpensify** [comment] 2023-09-15 03:13
@Julesssss asked to be assigned so.. I did :)
Thanks @ArekChr for the comment

**Comment by mallenexpensify** [comment] 2023-09-19 09:08
Removed `Help Wanted` and made this a weekly

**Comment by Julesssss** [comment] 2023-09-27 02:00
> think that the suggestion you mentioned is great.

Can you explain why please? I'd love to know if you had a better proposal

**Comment by Julesssss** [comment] 2023-09-27 02:02
Hey @ArekChr, could you please review [this](https://github.com/Expensify/App/issues/27259#issuecomment-1716139794) proposal?

**Comment by Julesssss** [comment] 2023-10-02 10:12
Bumping this @ArekChr

**Comment by mallenexpensify** [comment] 2023-10-02 16:49
@Julesssss I think I misunderstood, I thought you were going to be working on the PR.  I just readded `Help Wanted`. 
@ArekChr lelt us know if you're unable to review the proposal in the next 48 hours? Thx

**Comment by ArekChr** [comment] 2023-10-03 11:40
After merging https://github.com/Expensify/App/issues/26628 I'm not able to reproduce the amount cut-off issue.

**Comment by mallenexpensify** [comment] 2023-10-04 23:39
Also unable to reproduce via BrowserStack so closing, comment if ya disagree or are still able to repro.

**Closed by mallenexpensify** 2023-10-04 23:39 UTC
Labels: External, Engineering, Daily, Help Wanted, Bug
