### ISSUE TITLE
[$1000] IOS - Chat - Animation flickers when tap "Edit comment"

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#19506] opened 2023-05-24 01:24 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
Precondition - You sent a text message in chat
1. Open Expensify app
2. Open chat from precondition
3. Long press the message
4. Tap "Edit comment"

## Expected Result:
"Edit comment" field opens smoothly

## Actual Result:
"Edit comment" field opens with flickering every time user taps "Edit comment"

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [x] iOS / native
- [ ] iOS / Safari
- [ ] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 1.3.17.0

**Reproducible in staging?:** yes

**Reproducible in production?:** yes

**If this was caught during regression testing, add the test name, ID and link from TestRail:**

**Email or phone of affected tester (no customers):**

**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Notes/Photos/Videos:** Any additional supporting documentation

https://platform.applause.com/services/links/v1/external/fc29568ae756fdd57f819b60a231a75a3e49a477d21af90f83bf3202bfc71705

**Expensify/Expensify Issue URL:**

**Issue reported by:** Applause - Internal Team

**Slack conversation:**

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~016a782fbce054a064</li>
        <li>Upwork Job ID: 1661399230833754112</li>
        <li>Last Price Increase: 2023-05-24</li>
    </ul>
</details>

**Comment by lschurr** [comment] 2023-05-24 15:50
I was able to reproduce this on iOS.

**Comment by lschurr** [comment] 2023-05-26 21:52
Just waiting on proposals right @mountiny?

**Comment by mountiny** [comment] 2023-05-29 09:12
Correct

**Comment by koko57** [comment] 2023-05-29 10:13
Hi I'm Agata from Callstack - expert contributor group - maybe I could help with this one? 🙂

**Comment by koko57** [comment] 2023-05-30 09:22
Yesterday I was able to reproduce it both locally and on the production app (not sure what versions I had then 🫤, but I updated my fork yesterday morning). Today I updated my fork again and cannot reproduce it nor locally, neither on the 1.3.18-2 production version (the keyboard is opening everytime I want to edit the message, not like in the movie attached to the issue description)

prod - 1.3.18-2

https://github.com/Expensify/App/assets/28020445/0347040a-917d-4bb1-8cc4-a273ef831c53


dev - 1.3.20.-2

https://github.com/Expensify/App/assets/28020445/ad14a885-b3ea-4ac3-8ebe-41f7ecdbf8cb


the old version - for reference

https://github.com/Expensify/App/assets/28020445/ef876c2c-1d12-46e5-ae0d-4093aee49a59

**Comment by mountiny** [comment] 2023-05-30 10:57
Ok lets give this a week and see if we can reproduce then

**Comment by lschurr** [comment] 2023-06-12 17:53
@mountiny - thoughts on this one?

**Comment by mountiny** [comment] 2023-06-12 20:23
@koko57 @lschurr can we reproduce this now? If not, lets close this issue out, no payments are required.

**Comment by mountiny** [comment] 2023-06-12 20:26
Actually I could not replicate this, so I am going to close this, thanks everyone 🙇 
https://github.com/Expensify/App/assets/36083550/cde74221-e098-41b6-9111-f932e80924fd

**Closed by mountiny** 2023-06-12 20:26 UTC
Labels: External, Daily, Needs Reproduction, Bug
