### ISSUE TITLE
[$250] Android - QAB - In mWeb, merchant shown as "expense"&in Android unexpected error for QAB expense

### ISSUE THREAD

**Issue by IuliiaHerets** [Expensify/App#48238] opened 2024-08-29 07:18 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 9.0.25
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**If this was caught during regression testing, add the test name, ID and link from TestRail:** https://expensify.testrail.io/index.php?/tests/view/4898411
**Issue reported by:** Applause Internal Team

## Action Performed:
1. Launch site in both mweb and Android app
2. Tap fab -- submit an expense
3. Tap tab -- via QAB submit an expense
4. In mweb, open both expense and for Android wait few seconds

## Expected Result:
With any inconsistency and error user must be able to submit expense via QAB.

## Actual Result:
In mweb, merchant shown as "expense" in QAB via createe expense. In Android, QAB via created expense shows unexpected error.

## Workaround:
Unknown

## Platforms:

- [x] Android: Native
- [x] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [ ] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos
https://github.com/user-attachments/assets/dd5911f7-8496-422d-98bc-4b4fb601857e

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01095a4da6e8b969c0</li>
        <li>Upwork Job ID: 1830537395505788792</li>
        <li>Last Price Increase: 2024-09-02</li>
<li>Automatic offers: </li>
<ul>
<li>nkdengineer | Contributor | 103901378</li>
</ul></li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @rushatgabhane</details>

**Comment by IuliiaHerets** [comment] 2024-08-29 07:19
@twisterdotcom  FYI I haven't added the External label as I wasn't 100% sure about this issue. Please take a look and add the label if you agree it's a bug and can be handled by external contributors

**Comment by CyberAndrii** [comment] 2024-09-02 07:10
## Proposal

### Please re-state the problem that we are trying to solve in this issue.

Merchant is shown as "Expense" if the expense was created via the "Quick action" button

![image](https://github.com/user-attachments/assets/026b8842-8539-43ff-b99f-a2eae4c0cfe9)


### What is the root cause of that problem?

Expense created via `FAB > Submit expense` has the merchant property set to `CONST.TRANSACTION.PARTIAL_TRANSACTION_MERCHANT`.

Expense created via `FAB > Quick action > Submit expense` has the merchant property set to `CONST.TRANSACTION.DEFAULT_MERCHANT`.

Then in `MoneyRequestView` we decide whether the merchant name should be shown

https://github.com/Expensify/App/blob/3d8ee65e38db769eae56c9c7ee39f0597dff05ad/src/components/ReportActionItem/MoneyRequestView.tsx#L166

### What changes do you think we should make in order to solve the problem?

We need to add a check for `CONST.TRANSACTION.DEFAULT_MERCHANT` similar to how it's done in [other places](https://github.com/search?q=repo%3AExpensify%2FApp%20CONST.TRANSACTION.DEFAULT_MERCHANT&type=code)

```diff
diff --git a/src/components/ReportActionItem/MoneyRequestView.tsx b/src/components/ReportActionItem/MoneyRequestView.tsx
index 57c5c01da55..d2860bbd0fb 100644
--- a/src/components/ReportActionItem/MoneyRequestView.tsx
+++ b/src/components/ReportActionItem/MoneyRequestView.tsx
@@ -163,7 +163,10 @@ function MoneyRequestView({
         originalAmount: transactionOriginalAmount,
         originalCurrency: transactionOriginalCurrency,
     } = useMemo<Partial<TransactionDetails>>(() => ReportUtils.getTransactionDetails(transaction) ?? {}, [transaction]);
-    const isEmptyMerchant = transactionMerchant === '' || transactionMerchant === CONST.TRANSACTION.PARTIAL_TRANSACTION_MERCHANT;
+    const isEmptyMerchant =
+        transactionMerchant === '' ||
+        transactionMerchant === CONST.TRANSACTION.PARTIAL_TRANSACTION_MERCHANT ||
+        transactionMerchant === CONST.TRANSACTION.DEFAULT_MERCHANT;
     const isDistanceRequest = TransactionUtils.isDistanceRequest(transaction);
     const formattedTransactionAmount = transactionAmount ? CurrencyUtils.convertToDisplayString(transactionAmount, transactionCurrency) : '';
     const formattedOriginalAmount = transactionOriginalAmount && transactionOriginalCurrency && CurrencyUtils.convertToDisplayString(transactionOriginalAmount, transactionOriginalCurrency);
```

**Comment by CyberAndrii** [comment] 2024-09-02 07:12
My proposal doesn't cover the error on android part as it is being fixed in https://github.com/Expensify/App/issues/45086

**Comment by nkdengineer** [comment] 2024-09-02 14:56
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
In mweb, merchant shown as "expense" in QAB via createe expense. In Android, QAB via created expense shows unexpected error.

### What is the root cause of that problem?
- If we create a transaction with merchant is `(none)`, BE returns it as `(none)`.
- If we create a transaction with the merchant as an empty string, it's expected that BE returns it as `Expense`

The problem here is, that when we create a money request via QAB we pass the merchant as empty string [here](https://github.com/Expensify/App/blob/e60b8210a1f5a2471d8aa9d84d0e461774b791d6/src/pages/iou/request/step/IOURequestStepAmount.tsx#L230) and [here](https://github.com/Expensify/App/blob/e60b8210a1f5a2471d8aa9d84d0e461774b791d6/src/pages/iou/request/step/IOURequestStepAmount.tsx#L245) but we pass it as `(none)` [here](https://github.com/Expensify/App/blob/e60b8210a1f5a2471d8aa9d84d0e461774b791d6/src/pages/iou/request/step/IOURequestStepAmount.tsx#L204) and when we init the money request we also pass it as `(none)` [here](https://github.com/Expensify/App/blob/e60b8210a1f5a2471d8aa9d84d0e461774b791d6/src/libs/actions/IOU.ts#L346)



### What changes do you think we should make in order to solve the problem?
We should pass the merchant as `CONST.TRANSACTION.PARTIAL_TRANSACTION_MERCHANT` [here](https://github.com/Expensify/App/blob/e60b8210a1f5a2471d8aa9d84d0e461774b791d6/src/pages/iou/request/step/IOURequestStepAmount.tsx#L230) and [here](https://github.com/Expensify/App/blob/e60b8210a1f5a2471d8aa9d84d0e461774b791d6/src/pages/iou/request/step/IOURequestStepAmount.tsx#L245) by default as we do in other places. We also need to fix other QAB case that has a similar bug in `IOURequestStepScan` and `IOURequestStepDistance`


OPTIONAL: We can also add the check here to return `true` if the merchant is `Expense`.

https://github.com/Expensify/App/blob/e60b8210a1f5a2471d8aa9d84d0e461774b791d6/src/components/ReportActionItem/MoneyRequestView.tsx#L166
### What alternative solutions did you explore? (Optional)

**Comment by rushatgabhane** [comment] 2024-09-04 02:41
@CyberAndrii 's [proposal](https://github.com/Expensify/App/issues/48238#issuecomment-2323977143) LGTM because first

🎀 👀 🎀

**Comment by nkdengineer** [comment] 2024-09-04 02:48
@rushatgabhane Can you please check again, for consistent I think we should pass merchant as `CONST.TRANSACTION.PARTIAL_TRANSACTION_MERCHANT` when we create the money request via QAB.

**Comment by aldo-expensify** [comment] 2024-09-05 19:02
Waiting on @rushatgabhane to check the comment above before assigning

**Comment by rushatgabhane** [comment] 2024-09-09 16:23
> If we create a transaction with merchant is (none), BE returns it as (none).
If we create a transaction with the merchant as an empty string, it's expected that BE returns it as Expense

What @nkdengineer said here also makes sense and it feels closer to the root cause.  @aldo-expensify we can assign @nkdengineer

**Comment by aldo-expensify** [comment] 2024-09-10 17:08
> What @nkdengineer said here also makes sense and it feels closer to the root cause. @aldo-expensify we can assign @nkdengineer. 

After reading both proposals, I agree with you. Assigning @nkdengineer .

**Comment by aldo-expensify** [comment] 2024-09-10 17:08
noooooo

**Comment by nkdengineer** [comment] 2024-10-04 18:26
@twisterdotcom The PR was deployed to production. This is ready for payment.

**Comment by twisterdotcom** [comment] 2024-10-07 09:21
Payment Summary:

- @nkdengineer paid $250 via Upwork [here](https://www.upwork.com/nx/wm/workroom/38390338/overview) (Contributor)
- @rushatgabhane paid $250 via NewDot Requests (C+)

**Closed by twisterdotcom** 2024-10-07 09:21 UTC
Labels: Reviewing, External, Monthly, Bug

**Comment by garrettmknight** [comment] 2024-10-08 18:23
$250 approved for @rushatgabhane
