### ISSUE TITLE
 profile pic loading never stop even if swith to online

### ISSUE THREAD

**Issue by kavimuru** [Expensify/App#25985] opened 2023-08-26 01:58 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. go to any chat
2. change profile pic from receiver side
3. go offline
4. click on receiver email to see details and open profile pic
5. switch to online
## Expected Result: 
profile pic should be load on switch to online
## Actual Result: 
loading never stops

## Workaround:
Can the user still use Expensify without this being fixed? Have you informed them of the workaround?

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [x] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 1.3.57-5
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/43996225/424fc0ad-5f95-47dc-b7f8-77125cc3d512

https://github.com/Expensify/App/assets/43996225/a4a6eadf-cd82-4dc2-8d66-c4320a7bbacf

**Expensify/Expensify Issue URL:**
**Issue reported by:** @gadhiyamanan 
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1692181505642409

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by ygshbht** [comment] 2023-08-26 11:53
https://github.com/Expensify/App/issues/23817#issuecomment-1656708562

Addressing not the specific issue, but the root cause and its solution in the proposal below which will fix this issue as well

> ## Proposal
> ### Please re-state the problem that we are trying to solve in this issue.
> The problem at hand pertains to image display in the web app. Specifically, if an image has another image in reply in a thread, the app displays the image as blank when a user logs out, logs back in, goes offline, visits the thread and then comes back online. However, the image should load properly once the user is back online.
> 
> ### What is the root cause of that problem?
> The root cause of this problem is that the browser doesn't automatically reload the image once the network connection is reestablished. As such, despite the user being back online, the image remains blank on the thread.
> 
> ### What changes do you think we should make in order to solve the problem?
> To solve this issue, we need to ensure the image reloads once the network reconnects. One potential approach is to use a key prop on Image elements and increment a counter every time the network reconnects, prompting a re-render and thus, a reload of the image. However, due to a known [issue](https://github.com/facebook/react-native/issues/12606) with React Native, this approach might not always work as expected.
> 
> Alternatively, we could modify the image URL to include a cache-buster parameter like ?forceReloadAfterOffline=offline and ?forceReloadAfterOffline=online. This would force the browser to retrieve the image again once back online, bypassing the cache.
> 
> A third possible approach is to mimic the behaviour of other image elements that reload after network reconnects, such as Avatars. Their behaviour is likely to not load the image if there is no network, and display another placeholder element in place of the image. Once the network connection is reestablished, the image should then be displayed
> 
> https://github.com/Expensify/App/blob/eb020063789091eb2e3086b5b54af3ead8436645/src/components/Avatar.js#L64-L117
> 
>  https://github.com/Expensify/App/assets/65986357/26180e9b-4858-4ce0-898c-8dc12fc90a9e

**Comment by flaviadefaria** [comment] 2023-08-30 13:48
Indeed this looks like a dupe, thanks for pointing it out @hungvu193. Closing this.

**Closed by flaviadefaria** 2023-08-30 13:48 UTC
Labels: Daily, Overdue, Bug
