### ISSUE TITLE
[$1000] Profile - Expensify app vs notification Avatar mismatch

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#26053] opened 2023-08-28 01:53 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Login with user A on Android app (make sure notification is on for the app)
2. Login with user B on chrome browser
3. From User B on chrome, send a message to User A. This will trigger a notification.
4. Verify the avatar of User B on the notification does NOT match with the actual avatar

## Expected Result:
Avatar should be consistent over notifications

## Actual Result:
The notification has a different avatar than the actual one creating confusion

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [ ] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 1.3.57-5

**Reproducible in staging?:** Yes

**Reproducible in production?:** Yes

**If this was caught during regression testing, add the test name, ID and link from TestRail:**

**Email or phone of affected tester (no customers):**

**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/78819774/df3878ff-bb5e-47f1-9576-ba891296f461

https://github.com/Expensify/App/assets/78819774/05801a6f-a335-4d24-a926-8924a9313ec9

**Expensify/Expensify Issue URL:**

**Issue reported by:** @avi-shek-jha

**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1692482128809929

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~0185f8e3ae98dcabe1</li>
        <li>Upwork Job ID: 1702051950824742912</li>
        <li>Last Price Increase: 2023-09-19</li>
    </ul>
</details>

**Comment by dylanexpensify** [comment] 2023-08-29 08:48
reviewing today!

**Comment by dylanexpensify** [comment] 2023-08-31 08:57
On it now, apologies for delay

**Comment by dylanexpensify** [comment] 2023-09-04 10:16
Reviewing today while in the air! Currently taxi'd, will get to once I can hop on wifi! Sorry I didn't get to this last week, had head down on wave4 saastr

**Comment by dylanexpensify** [comment] 2023-09-11 10:28
Coming back from conference last week - updating today!

**Comment by dylanexpensify** [comment] 2023-09-13 20:09
Confirmed

**Comment by dylanexpensify** [comment] 2023-09-19 15:18
doubled for urgency

**Comment by b4s36t4** [comment] 2023-09-19 17:29
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
Profile - Expensify app vs notification Avatar mismatch
### What is the root cause of that problem?
The way we handle the icon for the Push notification is the issue. We use custom notification message style natively which helps us to gives the notification style we want.

In the code to show "avatar" property coming from the push-notification data.

https://github.com/Expensify/App/blob/5b4dee82a3634d73b9543474c5f298f1153460f9/android/app/src/main/java/com/expensify/chat/customairshipextender/CustomNotificationProvider.java#L182

Using this we fetch icon data, so to put into perspective `avatar` is the URL of image of the user. 

Why it's different to App from notification? because we handle the avatar differently inside the app ignoring the `avatar` that backend is sending.
ex: `https://d2k5nsl2zxldvw.cloudfront.net/images/avatars/default-avatar_7.png` is the avatar URL backend is sending so the app is showing same :)
### What changes do you think we should make in order to solve the problem?

We should update the avatar logic same as we do with applications.

https://github.com/Expensify/App/blob/ea5f461dc42844750529dbe6e285aeeae9c1c231/src/libs/UserUtils.js#L104-L114

We need to build same logic (maybe skipping olddot and newdot related logic or need help on how to figure out old vs newdot natively) to build the avatar URL instead of depending on the URL that is backend is sending, so that all app is sync with each other.


> Testing can be difficult, dev version of apps are not receiving any notifications (maybe I'm missing something not sure). 
### What alternative solutions did you explore? (Optional)
NA

**Comment by dylanexpensify** [comment] 2023-09-20 17:36
good question let me grab!

**Comment by dylanexpensify** [comment] 2023-09-20 17:36
@Gonals would you mind confirming if @ntdiary's [assumption](https://github.com/Expensify/App/issues/26053#issuecomment-1728166573) is correct?

**Comment by b4s36t4** [comment] 2023-09-20 18:01
I think this requires effort from backend & frontend as well. Because we highly rely on frontend based code approach for default icons... (probably 100% on frontend). Fixing this in backend & frontend app wide would make sense to resolve any future inconsistent behaviour  I feel.

**Comment by dylanexpensify** [comment] 2023-09-25 16:32
@Gonals seems we should fix this internally

**Comment by Gonals** [comment] 2023-09-26 03:41
Seems like it. I can test this when I have some time (that's likely two weeks from now 😅)

**Comment by dylanexpensify** [comment] 2023-09-28 18:17
Sounds good! Thanks!

**Comment by Gonals** [comment] 2023-10-02 08:23
I'll move it to weekly, then 😁

**Comment by Gonals** [comment] 2023-10-10 11:35
Turns out this is a dupe: https://github.com/Expensify/App/issues/23467

Closing!

**Closed by Gonals** 2023-10-10 11:35 UTC
Labels: Engineering, Weekly, Internal, Bug
