### ISSUE TITLE
Navigating to a particular chat crashes the app

### ISSUE THREAD

**Issue by m-natarajan** [Expensify/App#31088] opened 2023-11-09 00:15 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.3.97-0
**Reproducible in staging?:** needs reproduction
**Reproducible in production?:** needs reproduction
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** @marcaaron 
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1699484522735079

## Action Performed:
1. Open ND app
2. Navigate to the chat from another chat

## Expected Result:
App is not crashing

## Actual Result:
App crashes

## Workaround:
unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

![image](https://github.com/Expensify/App/assets/38435837/7586c74c-5eb1-4c3f-b80e-6450ade9c664)

![2023-11-08_13-01-02](https://github.com/Expensify/App/assets/38435837/22e1c42f-4e5a-48ab-bab7-295a49a33ff4)

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by Christinadobrzyn** [comment] 2023-11-10 22:08
I can't reproduce this. @marcaaron are you still seeing this issue? If yes, can you tell if it's related to specific chats or old/new chats?

**Comment by marcaaron** [comment] 2023-11-11 00:06
It's not happening anymore so I think we can close it.

**Closed by marcaaron** 2023-11-11 00:06 UTC
Labels: Daily, Bug
