### ISSUE TITLE
[HOLD for payment 2022-08-30] [$1000] Attachment -  Image file size gets doubled when uploaded from iOS @aswin-s

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#9424] opened 2022-06-13 14:22 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Launch the app
2. Go to a chat and upload an image from a mobile device.
3. Check the image size on device.
4. Now open the chat on recipient account in a web browser.
5. Open and download the received image.
5. Check the image file size. It is almost double the original file size

## Expected Result:
File size should be at least equal or less than the uploaded size.

## Actual Result:
Image file size gets doubled when uploaded from mobile.

## Workaround:
Can the user still use Expensify without this being fixed? Have you informed them of the workaround?

## Platform:

Where is this issue occurring?

- iOS

**Version Number:** 1.1.76.2

**Reproducible in staging?:** Yes

**Reproducible in production?:** Yes
 
**Email or phone of affected tester (no customers):** any

**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Notes/Photos/Videos:** Any additional supporting documentation

https://user-images.githubusercontent.com/93399543/173375263-f4877439-fdfd-4e4e-8c9b-1e45f03c6726.mp4

**Expensify/Expensify Issue URL:** 

**Issue reported by:** @aswin-s

**Slack conversation:** https://expensify.slack.com/archives/C01GTK53T8Q/p1654070862340069

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by yuwenmemon** [comment] 2022-06-28 19:02
Looks like the filesize is getting adjusted client-side:

https://user-images.githubusercontent.com/4741899/176261792-a07a6149-3991-48fd-9b15-c6faf754244f.mp4

**Comment by yuwenmemon** [comment] 2022-06-28 19:19
Anywhooo... Looks like since this is not a problem with the API we can have a contributor work on it. Curious to know what the issue is!

**Comment by kadiealexander** [comment] 2022-06-29 02:54
Posted to Upwork!

https://www.upwork.com/jobs/~01b7fcbbd791dc6c42
https://www.upwork.com/ab/applicants/1532271886227472384/job-details

**Comment by Santhosh-Sellavel** [comment] 2022-06-29 18:36
The problem seems to occur in iOS alone. Can we change platform section to iOS?

**Comment by Santhosh-Sellavel** [comment] 2022-06-30 01:51
It's fine on mWeb iOS too.

**Comment by mountiny** [comment] 2022-07-06 23:20
No proposals, @kadiealexander feel free to double the price on this one. Thanks!

**Comment by ntdiary** [comment] 2022-07-14 16:05
# Proposal
## cause 
this is also happening for png image in my test. 
And this problem is related to `UIImageJPEGRepresentation` and `UIImagePNGRepresentation` in two places.
these functions will change the image binary data when selecting and uploading.
One is in [react-native-image-picker](https://github.com/react-native-image-picker/react-native-image-picker/blob/eeca93864d9ea671a2e268f36936aafeab90cfe1/ios/ImagePickerManager.m#L134-L138):
```
// react-native-image-picker copy origin image data to a temp file with these functions and return its uri like:
// file:///xxx/Application/0582897B-9548-4507-8E9F-EFFE590EF37E/tmp/3C7FACA8-404B-4E90-B386-E32ED6203543.png
// (the temp file size has increased)
// ImagePickerManager.m
    if ([fileType isEqualToString:@"jpg"]) {
        data = UIImageJPEGRepresentation(image, [self.options[@"quality"] floatValue]);
    } else if ([fileType isEqualToString:@"png"]) {
        data = UIImagePNGRepresentation(image);
    }

```
another is in [react-native](https://github.com/facebook/react-native/blob/d2bc02491a916a242e427bb1c90cb66471c925f0/Libraries/Image/RCTImageLoader.mm#L1132-L1138):
```
// and then react-native use RCTImageLoader to convert the last file uri to binary data with these functions
// RCTImageLoader.mm
    if (RCTImageHasAlpha(image.CGImage)) {
      mimeType = @"image/png";
      imageData = UIImagePNGRepresentation(image);
    } else {
      mimeType = @"image/jpeg";
      imageData = UIImageJPEGRepresentation(image, 1.0);
    }
```
## solution
if we really want to keep original data, we need to avoid the conversion that happens in these two places.
for react-native-image-picker, can submit a PR with adding a option to keep origin data.
for react-native, can customize a new handler to deal the image upload.

## related
here are two related issues that have not been resolved:
https://github.com/react-native-image-picker/react-native-image-picker/issues/1894
https://github.com/facebook/react-native/issues/31641

I cloned the `react-native-image-picker` repository, and changed its example in `test` branch for test([here](https://github.com/ntdiary/react-native-image-picker/commit/6c8d0676407ee2bf1ea54195b49ac802e17e81b4)):
this is a png image:
<img src="https://user-images.githubusercontent.com/8579651/179020568-8a6673c2-b0e5-4f83-9cfd-8b5e21cc5490.png" 
width="200" />
in my test
run `node server.js` to prepare a simple server in `http://127.0.0.1:9999`
and then watch http and image packets with Wireshark
Origin image has one IDAT chunk, but `UIImagePNGRepresentation` converts it to many IDAT chunks
<img src="https://user-images.githubusercontent.com/8579651/179023472-ac1476d0-dfe9-4ca4-8ac2-c34b3f1e55b0.png" width="600" />
And if you save the file whose size has increased from the chat and upload again, the size won't increase again.

**Comment by mountiny** [comment] 2022-07-15 13:11
Waiting for a review from @Santhosh-Sellavel first

**Comment by Santhosh-Sellavel** [comment] 2022-07-15 15:58
@mountiny 
Evidently, it seems the issue exists in the libraries.

We are good to hire @ntdiary if the uplink PR is accepted.

**Comment by mountiny** [comment] 2022-07-15 23:12
Thanks @Santhosh-Sellavel. It would be great to see the changed in the libraries and that it actually fixes our problem first, but I appreciate this is a bit more involved problem.

@ntdiary it seems like this is your first issue you have been assigned to work on. I am very excited to have you on board! Please, feel free to refer to the Contributing guidelines if you have any [questions](https://github.com/Expensify/App/blob/main/contributingGuides/CONTRIBUTING.md). Feel free to message here or in Slack as well if you need help. @Santhosh-Sellavel and I will try to help you get this fixed.

I think the next steps would be ideally to make the necessary changes in the libraries locally and testing those changes in App if possible. That way we can make sure that the original problem of the attachement size being increased will indeed be fixed.

Thank you very much!

**Comment by ntdiary** [comment] 2022-07-16 14:50
Thank you for you suggestion @mountiny 😄
This is a small test video on Expensify App.

https://user-images.githubusercontent.com/8579651/179359868-b05d531a-e565-4803-8fb4-f7357be171e4.mov

maybe next I can try to report the above problem to the `react-native-image-picker'  repo and provide a way to fix it.
hope everything goes well

**Comment by mountiny** [comment] 2022-07-16 16:01
@ntdiary Thanks, yes please create an issue and upstream PR for the library if possible, hopefully, they will be happy with merging that solution. This is not critical bug so we can wait some time for them.

It seems like there is some error with your uploaded video, I cant seem to play it.

**Comment by Santhosh-Sellavel** [comment] 2022-07-17 16:31
@ntdiary We are unable to checkout the video in  https://github.com/Expensify/App/issues/9424#issuecomment-1186210544 Can you reshare the recording?

**Comment by ntdiary** [comment] 2022-07-18 10:22
Sorry, it can be played on my computer. Is it a problem with the mov format?
I uploaded it to youtube. 🙂
https://youtu.be/4kz8Mo02p6U

**Comment by mountiny** [comment] 2022-07-18 10:27
@ntdiary Great! I could play that (not sure why the original did not work). Happy to see it works, looking forward to review you PR, great job so far 🙌

**Comment by ntdiary** [comment] 2022-07-21 12:45
I've updated the issue in the `react-native-image-picker` repo a few times these days, but it seems that their maintainers are not very active, which may take us a little longer to fix this. 🙂

**Comment by mountiny** [comment] 2022-07-21 12:53
@ntdiary Yeah, it might take a bit, but that should be fine with us. However, looking at their [Contributing guidelines](https://github.com/react-native-image-picker/react-native-image-picker/blob/main/CONTRIBUTING.md), would you be able to just create a PR with the necessary changes and maybe show some tests. I think that would speed up the process! 

Thank you very much for this work!

**Comment by ntdiary** [comment] 2022-07-21 12:59
Thanks for the suggestion, I'll try it 😄

**Comment by kadiealexander** [comment] 2022-07-25 04:36
@ntdiary, @aswin-s and @Santhosh-Sellavel please don't forget to apply on [Upwork](https://www.upwork.com/jobs/~01b7fcbbd791dc6c42)!

**Comment by mountiny** [comment] 2022-07-25 10:20
@ntdiary how is it looking? feel free to link the PR here!

**Comment by ntdiary** [comment] 2022-07-25 10:28
https://github.com/react-native-image-picker/react-native-image-picker/pull/2006 🙂

**Comment by mountiny** [comment] 2022-08-02 15:12
Bumped the maintainer of the repo for a review 🤞

**Comment by Santhosh-Sellavel** [comment] 2022-08-05 20:14
Has melvin gone crazy?

**Comment by mountiny** [comment] 2022-08-05 20:16
No, this is a new feature when you comment linking an issue or PR in deployBlocker

**Comment by Santhosh-Sellavel** [comment] 2022-08-05 20:22
Ya but when this issue doesn't have any active or merged PR, notification doesn't make any sense.

**Comment by mountiny** [comment] 2022-08-08 08:42
@Santhosh-Sellavel That is true we cant really see if there is a linked PR to this issue, but I think we might want to look into this, maybe checking if the issue has `Awaiting Payment` label signalling the linked PR has been closed or is closed in general as internal issues wont have `Awaiting Payment`.

**Comment by mountiny** [comment] 2022-08-08 08:43
@ntdiary Your PR has been merged and released! 🎉 lets move ahead with testing this in our App :) thank you!

**Comment by ntdiary** [comment] 2022-08-08 14:50
Hi, @mountiny I've submitted a PR, please let me know if I'm not doing something right 😄

**Comment by mountiny** [comment] 2022-08-08 17:20
> Maybe let's use the Reviewing Label is common to internal or external right?

We are discussing this, the internal ones get closed when issue is merged.

**Comment by Santhosh-Sellavel** [comment] 2022-08-08 17:33
> We are discussing this, the internal ones get closed when the issue is merged.

Cool, we can ask melvin to reopen it if that's not a problem. Like it does for crash issues.

**Comment by kadiealexander** [comment] 2022-08-30 15:42
@aswin-s and @ntdiary have been paid, thank you!

@Santhosh-Sellavel please let me know once you've accepted the contract and I'll issue payment here too.

**Comment by Santhosh-Sellavel** [comment] 2022-08-30 23:28
Done @kadiealexander thanks!

**Closed** 2022-09-01 13:26 UTC
Labels: Reviewing, Exported, External, Engineering, Daily, Improvement, Awaiting Payment
