### ISSUE TITLE
[$250] Moving a user to an OldDot domain group with a preferred workspace puts them on the workspace chat beta

### ISSUE THREAD

**Issue by m-natarajan** [Expensify/App#46811] opened 2024-08-05 14:27 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 9.0.16-4
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** @muttmuure 
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1722600157187309

## Action Performed:
1. Be a workspace admin for a workspace and a domain admin for your domain
2. Create a "domain group" in Domains > Groups on Expensify Classic and set a Preferred Workspace for the domain group you created (the workspace you are an admin for)
3. On the Domain Members page, move user A to your new domain group.
4. As user A, create expenses and submit a report on the preferred workspace
5. As the workspace admin, navigate to New Expensify
## Expected Result:
Because the workspace chat beta is disabled (you can check this by running `Policy.getCurrent().policy.isPolicyExpenseChatEnabled` in your console with the workspace open on OldDot, no workspace chats are created in New Expensify for that workspace.
## Actual Result:
There is a workspace chat created for the report that user A just submitted.
## Workaround:
Can the user still use Expensify without this being fixed? Have you informed them of the workaround?

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [x] Android: mWeb Chrome
- [x] iOS: Native
- [x] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

https://github.com/user-attachments/assets/47d5d447-3ecf-42ee-bae8-de127c6b1800

Add any screenshot/video evidence

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01e7149bdde9a575ca</li>
        <li>Upwork Job ID: 1821180644925581221</li>
        <li>Last Price Increase: 2024-08-07</li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @rayane-djouah</details>

**Comment by rlinoz** [comment] 2024-08-08 21:02
PR is up!

**Comment by muttmuure** [comment] 2024-08-15 09:33
@rlinoz I'm still seeing a lot of workspace chats in my account despite the customer not being on the beta. Is this something we can look into in Slack (not here because of sensitive data?)

**Comment by rlinoz** [comment] 2024-08-16 16:14
@muttmuure started a thread [here](https://expensify.slack.com/archives/C05LX9D6E07/p1723722469695359)

**Comment by muttmuure** [comment] 2024-08-21 12:02
Added more examples in thread

**Comment by zanyrenney** [comment] 2024-09-04 16:21
how are we doing with this one @rlinoz

**Comment by muttmuure** [comment] 2024-09-04 16:59
We chatted about this and @puneetlath thinks that what I am seeing is actually expected behavior. I'm not convinced this isn't a bug

**Comment by rlinoz** [comment] 2024-09-12 12:45
From the last chat we had I think we are good on this one? I mean, we may still have problems with the LHN but the specific issue of creating new workspace chats for policies that don't have it enabled is gone?

**Comment by zanyrenney** [comment] 2024-09-13 15:32
Seeing as Matt thinks this is expected behaviour and you think this issue is not appearing Rodridgo, going t close this out. Feel free to reopen if either of you disagree.

**Closed by zanyrenney** 2024-09-13 15:32 UTC
Labels: Reviewing, Daily, Weekly, Internal, Bug, AutoAssignerNewDotQuality
