### ISSUE TITLE
Chat - Quoted multiline hyperlink message is inconsistent between live compose box and chat

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#47952] opened 2024-08-23 23:52 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 9.0.24-1
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**If this was caught during regression testing, add the test name, ID and link from TestRail:** https://expensify.testrail.io/index.php?/tests/view/4884114
**Email or phone of affected tester (no customers):** applausetester+vd_web082324@applause.expensifail.com
**Issue reported by:** Applause - Internal Team

## Action Performed:
1. Go to https://staging.new.expensify.com/
2. Log in
3. Go to any chat
4. Type a quoted multiline hyperlink message on compose box, like:
![qaz](https://github.com/user-attachments/assets/bb0f3f2f-5fd0-4832-8082-c8415741de8a)
5. Without sending the message, note that the live markdown feature is not displayed (as if quote markdown is not going to be applied)
6. Send the message.
7. Note that the message on the chat have quote markdown applied on the first line

## Expected Result:
Behavior on live markdown should be consistent with what is later displayed on the chat

## Actual Result:
Behavior on live markdown is not consistent with what is later displayed on the chat

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details> 

https://github.com/user-attachments/assets/b312ec06-17a3-4bac-96e9-da3c7880ac0f

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by lanitochka17** [comment] 2024-08-23 23:53
We think that this bug might be related to Live Markdown

**Comment by lanitochka17** [comment] 2024-08-23 23:53
@zanyrenney  FYI I haven't added the External label as I wasn't 100% sure about this issue. Please take a look and add the label if you agree it's a bug and can be handled by external contributors

**Comment by zanyrenney** [comment] 2024-08-25 18:30
I am OOO, reassigning. this also shouldn't have picked me, I have OOO set and this was assigned after that. 
![2024-08-25_19-29-06](https://github.com/user-attachments/assets/52fad7cc-6ea7-4499-98bf-02d8668b9426)

**Comment by anmurali** [comment] 2024-08-28 01:38
<img width="1025" alt="image" src="https://github.com/user-attachments/assets/5c3d55f5-1618-4ff5-9afb-75e47c309cec">
<img width="1034" alt="image" src="https://github.com/user-attachments/assets/8ae9ee34-5317-4364-af04-b116396ffe27">

Cannot reproduce.

**Closed by anmurali** 2024-08-28 01:38 UTC
Labels: Daily, Overdue, Bug
