### ISSUE TITLE
[HOLD for payment 2024-08-01] [Free trial] [$250] Not able to get rid of Expensify Chat with a GBR in the LHN

### ISSUE THREAD

**Issue by m-natarajan** [Expensify/App#44356] opened 2024-06-24 22:47 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 9.0.1-12
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** @iwiznia 
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1719247632996389

## Action Performed:
1. Open the app
2. Observe the notifications@expensify.com chat in the LHN with GBR
3. Click on it
## Expected Result:
GBR should be able to be removed
## Actual Result:
Unable to make that GBR  chat to disappear

ionatan@db2.sjc:~$ getreport.sh 1539158347903228
Report 1539158347903228 is Open
State: 0: Open Status: 0: Open
Report:
created,submitted,approved,reportID,accountID,managerID,reportName,state,total,currency,status
"2024-04-26 18:11:24",,,1539158347903228,0,,"Chat Report",0,0,USD,0

Submitter:
accountID,email
0,__fake__

SharedReports:
accountID,reportID,permissions
11665625,1539158347903228,"read, write"
2536717,1539158347903228,read

ReportActions:
created,reportID,accountID,action,message,reportActionID
"2024-04-26 18:11:24.111",1539158347903228,0,CREATED,"{""creatorAccountID"":2536717,""lastModified"":""2024-04-26 18:11:24.111""}",3522208189545905848

ReportNVPs:
reportID,name,value
1539158347903228,chatType,system
1539158347903228,expensify_policyID,_FAKE_
1539158347903228,lastReadTime_11665625,"2024-04-26 18:11:24.111"
1539158347903228,lastReadTime_2536717,"2024-04-26 18:11:24.111"
1539158347903228,type,chat
## Workaround:
unknown
## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

![image (23)](https://github.com/Expensify/App/assets/38435837/7cbdc65f-cbd6-4185-b262-f99580226c93)

![image (22)](https://github.com/Expensify/App/assets/38435837/1fc9c14a-f5ef-4240-8b5a-f1dd4607aba9)

![Snip - (7) New Expensify - Google Chrome](https://github.com/Expensify/App/assets/38435837/92bd56a9-4556-4508-8800-8e387a4ab2d2)

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~013e454a42dddd3d2f</li>
        <li>Upwork Job ID: 1807772836439607453</li>
        <li>Last Price Increase: 2024-07-15</li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @alexpensify</details>

**Comment by alexpensify** [comment] 2024-06-26 21:09
I followed up in the Slack convo to figure out if this should be internal or external.

**Comment by alexpensify** [comment] 2024-06-28 21:53
@OfstadC - The Slack 🧵 ([HERE](https://expensify.slack.com/archives/C049HHMV9SM/p1719247632996389)) concluded that there should be a live troubleshooting in Slack and then mark it as `External`.  This morning, I had to deal with one of my managed customers, and that issue took my attention. I will be OOO until Monday, July 8, and I ran out of time to host the Slack troubleshooting. I'm reassigning the issue to avoid more delays. Thanks!

**Comment by alexpensify** [comment] 2024-07-01 13:48
@CortneyOfstad - I'm going fully OOO now and noticed that another team member was running into this issue. I've assigned `external` but need help to keep pushing for proposals. Thanks!

**Comment by OfstadC** [comment] 2024-07-01 16:05
@alexpensify You tagged the wrong sister 😅 . I'm also largely OoO this week, but will try and get this tackled today before i'm out

**Comment by OfstadC** [comment] 2024-07-02 21:08
Looks like we are waiting on proposals here. I'm OoO starting tomorrow for a few days. I think this still needs a status from Wave Collect curator - so i'll bump in Slack 😃 . 

@kadiealexander is buddying for me if anything increases in priority while i'm out - but i'll be popping in occasionally

**Comment by OfstadC** [comment] 2024-07-02 21:11
https://expensify.slack.com/archives/C036QM0SLJK/p1719954648424619

**Comment by alexpensify** [comment] 2024-07-08 17:47
@OfstadC - whoops, my bad on tagging the wrong person. 🤦🏼 I'm back online and removing you from this GH. Thanks for your assistance here. 

--- 

We are waiting for proposals here. @nyomanjyotisa let me review again and share the steps.

**Comment by alexpensify** [comment] 2024-07-10 17:35
No update yet; waiting for proposals.

**Comment by mvtglobally** [comment] 2024-07-11 03:46
Issue not reproducible during KI retests. (First week)

**Comment by alexpensify** [comment] 2024-07-12 22:40
Since this isn't appearing in recent tests, I think we should close. I'll review more and confirm.

**Comment by alexpensify** [comment] 2024-07-15 18:46
No update yet, I need to review this week.

**Comment by chiragsalian** [comment] 2024-07-16 15:43
I'll take over the issue since i investigated and know how to tackle it.

**Comment by mvtglobally** [comment] 2024-07-19 03:14
Issue not reproducible during KI retests. (Second week)

**Comment by alexpensify** [comment] 2024-07-19 23:13
The PR is moving along through the required process.

**Comment by alexpensify** [comment] 2024-07-31 21:49
@suneox - I sent an offer via Upwork. Please accept and I can continue the payment process tomorrow. Thanks! 

https://www.upwork.com/jobs/~013e454a42dddd3d2f

**Comment by alexpensify** [comment] 2024-08-01 18:34
@suneox - thank you for your response. I'm going to close now and there is no payment summary here.

**Closed by alexpensify** 2024-08-01 18:34 UTC
Labels: Daily, Awaiting Payment, Bug
