### ISSUE TITLE
[$250] Android - Chat - Emoji keyboard can not be activated when no other character is added in chat box

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#41011] opened 2024-04-25 18:07 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.66-0
**Reproducible in staging?:** Y
**Reproducible in production?:** N
**If this was caught during regression testing, add the test name, ID and link from TestRail:** N/A
**Email or phone of affected tester (no customers):** gatantm@gmail.com
**Issue reported by:** Applause - Internal Team

## Action Performed:
The issue was detected on the following devices: Google Pixel 8 - Android 14, Google Pixel 6 - Android 14.
1. Launch the app and go to any chat/report
2. Using Gboard keyboard try to use the emoji keyboard without adding anything else in the text box

## Expected Result:
The native emoji keyboard is shown at any flow without issues

## Actual Result:
The native emoji keyboard is not shown if there's no other character already entered on the text field

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [ ] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details> 

https://github.com/Expensify/App/assets/78819774/01b4727f-8d0d-46d1-a7fb-5d43582bdd5b

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01f981538723950232</li>
        <li>Upwork Job ID: 1783601692500316160</li>
        <li>Last Price Increase: 2024-05-09</li>
    </ul>
</details>

**Comment by lanitochka17** [comment] 2024-04-25 18:07
@tylerkaraszewski  FYI I haven't added the External label as I wasn't 100% sure about this issue. Please take a look and add the label if you agree it's a bug and can be handled by external contributors

**Comment by lanitochka17** [comment] 2024-04-25 18:08
We think that this bug might be related to #vip-vsp

**Comment by lanitochka17** [comment] 2024-04-25 18:08
Production:

https://github.com/Expensify/App/assets/78819774/84ba024c-5bf5-4e62-8eb7-ea8306e14ff3

**Comment by tylerkaraszewski** [comment] 2024-04-25 20:59
I think we can add external to this.

**Comment by seanbashaw** [comment] 2024-04-26 08:44
Contributor details
Your Expensify account email: seanbshw@gmail.com
Upwork Profile Link: https://www.upwork.com/freelancers/~01f678064fae0b9928

**Comment by mountiny** [comment] 2024-04-26 11:34
I am demoting this from being  blocker as there is a workaround of posting some character or using the in-product emoji keyboard, also this seems to be repro only on some specific Android devices.

@seanbashaw thanks for the proposal. The changes you have linked are very old, but this seems to not be repro in production. Would you be able to highlight what change in recent release could have caused this regression?

**Comment by mountiny** [comment] 2024-04-26 11:35
Posted [here](https://expensify.slack.com/archives/C06BDSWLDPB/p1714131334000179) for help

**Comment by seanbashaw** [comment] 2024-04-27 00:06
@mountiny This logic still exist in the most recent version. The following function onChangeText shows this logic being implemented still. 
https://github.com/Expensify/App/blob/10fc359d9fdd1e05e03a4769e2a73f95e703be51/src/pages/home/report/ReportActionCompose/ComposerWithSuggestions/ComposerWithSuggestions.tsx#L547-L564
The following commit shows functionality being removed that could have been covered for android. 
https://github.com/Expensify/App/commit/b2ff88cd3d44870fdf7677ebb5302df9568d2951

**Comment by tylerkaraszewski** [comment] 2024-05-02 23:06
Doesn't seem like we do.

**Comment by mvtglobally** [comment] 2024-05-06 19:56
Issue not reproducible during KI retests. (First week)

**Comment by mvtglobally** [comment] 2024-05-13 14:14
Issue not reproducible during KI retests. (Second week)

**Comment by tylerkaraszewski** [comment] 2024-05-13 19:14
Closing because not reproducible.

**Closed by tylerkaraszewski** 2024-05-13 19:14 UTC
Labels: External, Engineering, Daily, Help Wanted, Overdue
