### ISSUE TITLE
Account - “Close account” button isn’t disabled if nothing is written in the second input

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#13065] opened 2022-11-26 23:40 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Log in as a Public domain account (e.g gmail) - this account will be closed so use a disposable account or create one for these tests
2. Navigate to Settings > Security
3. Tap on second input field and do not write anything on it

## Expected Result:
The "Close account" button is disabled if nothing is written in the second input

## Actual Result:
“Close account” button isn’t disabled if nothing is written in the second input

## Workaround:
Unkown

## Platform:

Where is this issue occurring?

- Web
- iOS
- Android
- Desktop App
- Mobile Web

**Version Number:** 1.2.32.1

**Reproducible in staging?:** Yes

**Reproducible in production?:** Yes

**Email or phone of affected tester (no customers):** 

**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Notes/Photos/Videos:** Any additional supporting documentation

![Screen Shot 2022-11-26 at 1 39 40 PM](https://user-images.githubusercontent.com/93399543/204112805-571457f7-fce4-4aa8-9b4b-661fc0f15c7a.png)

https://user-images.githubusercontent.com/93399543/204112806-2d674410-cd96-40b0-b74a-0b8e831e9e92.mp4

**Expensify/Expensify Issue URL:** 

**Issue reported by:** Applause - Internal Team

**Slack conversation:** 

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by thesahindia** [comment] 2022-11-27 06:34
Not a bug. It is expected.

**Comment by kbecciv** [comment] 2022-11-27 16:33
@thesahindia 
We are Failing step 6 in Test Rail https://expensify.testrail.io/index.php?/tests/view/2964249

![image](https://user-images.githubusercontent.com/93399543/204147818-de887388-5757-480e-84b2-742cf661116f.png)

**Comment by thesahindia** [comment] 2022-11-27 17:56
I think we need to update the steps.

cc: @Beamanator

**Comment by Beamanator** [comment] 2022-11-28 08:51
@thesahindia thanks for the ping! You're right, the steps need to be updated.

For the record, in [this comment](https://github.com/Expensify/App/issues/11341#issuecomment-1287347519) we decided it's fine & is now expected to show the form's "Close Account" button always, since we'll now show an error if the user clicks it w/out filling out their default login.

Also in that issue (https://github.com/Expensify/App/issues/11341) we got rid of the Close Account error modal, instead we show errors directly on the Close Account page.

So @kbecciv I'm sorry I didn't mention updating the Test steps on that issue, I will write the updated, official test steps soon 👍

**Comment by Beamanator** [comment] 2022-11-28 09:55
Ok it looks like we have 2 Test cases dealing with the Close Account page / flow:

[Security - Close Account (Public domain and Phone accounts)](https://expensify.testrail.io/index.php?/cases/view/1971045)

Edits:
1. Remove step `6. Verify the "Close account" button is disabled if nothing is written in the second input`
2. Add a case for:
    1. Without entering anything in the second input, click "Close Account"
    2. Verify you see an error message below the second input, telling the user they have enter their default contact method to close their account
    3. <img width="374" alt="Screen Shot 2022-11-28 at 11 51 13 AM" src="https://user-images.githubusercontent.com/3885503/204247515-08886d8d-871f-466c-b8c7-679ba5d8a38d.png">

[Login / Logout (Close Account) - Close Account (Logout)](https://expensify.testrail.io/index.php?/cases/view/1971127)

(doesn't need any updates)

@kbecciv can you please make the edits to the first linked test case above?

**Comment by lschurr** [comment] 2022-11-29 22:40
Next steps on @kbecciv for this one, correct?

**Comment by Beamanator** [comment] 2022-11-30 08:59
Yeppp ^

Oh following [this SO](https://stackoverflow.com/c/expensify/questions/363/364#364) I think I need to cc @Expensify/applauseleads & assign `applausebot`

**Comment by Beamanator** [comment] 2022-12-05 12:29
Bump @kbecciv / @Expensify/applauseleads

**Comment by isagoico** [comment] 2022-12-05 19:19
@Beamanator tests have been updated!
![image](https://user-images.githubusercontent.com/44479856/205724183-fb4d74b8-e586-48d5-b539-f18f34ffcd8e.png)

**Comment by Beamanator** [comment] 2022-12-06 08:42
Thanks for the updates @isagoico !

Also I thinkkkk we need to update the last point on both of those tests: There shouldn't be a `growl saying "Account closed successfully"` anymore, if my memory is correct... I believe the user is now logged out & there's a message on the sign-in page that says "Account closed successfully" with a green success dot - from this PR (https://github.com/Expensify/App/pull/11665)

**Comment by Beamanator** [comment] 2022-12-13 10:32
Perfect, thanks so much @isagoico ! Ready to close this out :D

**Closed by Beamanator** 2022-12-13 10:32 UTC
Labels: Weekly, Bug
