### ISSUE TITLE
[$500] IOS - The app flashes after selecting 'Copy to Clipboard'

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#30706] opened 2023-11-01 15:35 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.3.94.0
**Reproducible in staging?:**Y
**Reproducible in production?:**n/a
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:**Applause - Internal Team
**Slack conversation:**

**Issue found when executing PR** https://github.com/Expensify/App/pull/30085
## Action Performed:
1. Open the app in either MacOS Safari v17 and above or Safari on iPhone 15 and above
2. Go to any chat and right click/Long press on a chat message to view the context menu
3. Click/Press on Copy to clipboard

## Expected Result:
The app does not flash after selecting 'Copy to Clipboard'

## Actual Result:
The app flashes after selecting 'Copy to Clipboard'

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [ ] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details> 

https://github.com/Expensify/App/assets/78819774/ec665054-532d-4462-8c69-70b5b28acf14

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01d6cd889f3d0aa3a9</li>
        <li>Upwork Job ID: 1719740024722116608</li>
        <li>Last Price Increase: 2023-11-22</li>
    </ul>
</details>

**Comment by yh-0218** [comment] 2023-11-01 19:28
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
IOS - The app flashes after selecting 'Copy to Clipboard'
### What is the root cause of that problem?
This is visible effect of Modal disappearing.
Now we have Modal hide time issue on iOS and Android.
This make above issue
### What changes do you think we should make in order to solve the problem?
We need to fix Mobile animation issue when close Modal.

Then that effect will not appear `flashes`
Slow hide of Modal
This works well on iOS and Android
### What alternative solutions did you explore? (Optional)


https://github.com/Expensify/App/assets/65789015/1c9ac445-5b1a-4a88-a511-fc1dac856f6a

**Comment by bfitzexpensify** [comment] 2023-11-07 19:07
Either of those proposals look good @aimane-chnaif?

**Comment by bfitzexpensify** [comment] 2023-11-08 14:04
@aimane-chnaif - yes, that sounds correct to me

**Comment by ikevin127** [comment] 2023-11-08 14:29
I have to disagree, if we look at the OP video frame by frame we can see that the context menu closes before the backdrop does which cause that "flash" visual:

<details>
<summary>iOS: Native - Frame by frame "flash"</summary>

https://github.com/Expensify/App/assets/56457735/6b06cd1a-97c3-4877-978d-6a263efb7fc0

</details>

This is what I think the issue refers to, otherwise it would've said something along the lines of: "no animation when context menu closes".

Otherwise, allowing the context menu to animate-out does fix the visual issue but that will also add the same animation upon clicking on any other context menu item when the menu closes: Reply in thread, Subscribe to thread, Copy link, Mark as unread and Flag as offensive.

Which I'm not sure we want to do here because some of the items in the menu have different closing behaviour: in `ContextMenuActions` some delay the `hideContextMenu` and some don't.

If something changed and a transition-out animation is required when closing the menu no matter the menu item pressed, then dismiss this comment.

**Comment by bfitzexpensify** [comment] 2023-11-09 20:19
>I have to disagree, if we look at the OP video frame by frame we can see that the context menu closes before the backdrop does which cause that "flash" visual:
>
>This is what I think the issue refers to, otherwise it would've said something along the lines of: "no animation when context menu closes".

Good call @ikevin127 - I went frame-by-frame and I agree with this

> Otherwise, allowing the context menu to animate-out does fix the visual issue but that will also add the same animation upon clicking on any other context menu item when the menu closes: Reply in thread, Subscribe to thread, Copy link, Mark as unread and Flag as offensive.
> 
> Which I'm not sure we want to do here because some of the items in the menu have different closing behaviour: in ContextMenuActions some delay the hideContextMenu and some don't.

Also agree, I don't think we want to have the same animation across all actions

**Comment by bfitzexpensify** [comment] 2023-11-13 18:52
How do these proposals look @aimane-chnaif?

**Comment by bfitzexpensify** [comment] 2023-11-17 20:15
Bump on the questions in https://github.com/Expensify/App/issues/30706#issuecomment-1812751426 @lanitochka17 - thank you!

**Comment by yh-0218** [comment] 2023-11-17 20:53
hi, @bfitzexpensify how do you think about my proposal?

**Comment by bfitzexpensify** [comment] 2023-11-20 21:33
Hi @lanitochka17, clarifying questions:
1. can you please clarify what "flash" means here?
2. "IOS" is stated in issue title but attached video is android. Does it happen on native only or mWeb as well?

**Comment by mvtglobally** [comment] 2023-11-23 05:26
Issue not reproducible during KI retests. (First week)

**Comment by bfitzexpensify** [comment] 2023-11-23 22:45
OK, considering this has been identifed as not reproducible, I think we can close this for the moment.

**Closed by bfitzexpensify** 2023-11-23 22:45 UTC
Labels: External, Engineering, Daily, Help Wanted, Overdue, Bug
