### ISSUE TITLE
[HOLD for payment 2024-11-20] [$250] Inconsistency in displaying Search icon when returning to expenses opened from Search

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#51476] opened 2024-10-25 14:56 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 9.0.54-1
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**If this was caught on HybridApp, is this reproducible on New Expensify Standalone?:** N/A
**If this was caught during regression testing, add the test name, ID and link from TestRail:** N/A
**Issue reported by:** Applause - Internal Team

## Action Performed:
Precondition: Logged in to New Expensify on two devices with different accounts
1. [User B] Submit expense to user A
2. [User A] Tap on Search icon in the bottom
3. [User A] Tap on expense created in step 1
4. [User A] Tap on From link in the header
5. [User A] Tap on back arrow

## Expected Result:
Search icon should be displayed consistently

## Actual Result:
Search icon is not displayed in step 3., but it appears in step 5
Also, sometimes the icon appears when refreshing the page after step 3

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Standalone
- [ ] Android: HybridApp
- [x] Android: mWeb Chrome
- [ ] iOS: Standalone
- [ ] iOS: HybridApp
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

<details>
  <summary>Add any screenshot/video evidence</summary>

  
</details> 

https://github.com/user-attachments/assets/faa0ea73-aa94-49b7-bed6-d50d873da086

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~021850913269706139520</li>
        <li>Upwork Job ID: 1850913269706139520</li>
        <li>Last Price Increase: 2024-11-04</li>
<li>Automatic offers: </li>
<ul>
<li>nyomanjyotisa | Contributor | 104771832</li>
</ul></li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @isabelastisser</details>

**Comment by shahinyan11** [comment] 2024-10-25 15:20
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
Inconsistency in displaying Search icon when returning to expenses opened from Search
### What is the root cause of that problem? 
[Here](https://github.com/Expensify/App/blob/b7c1cfafecd03db14de4a4a30ac155fe4a7fb28b/src/components/MoneyReportHeader.tsx#L180C5-L180C54) we  check if the report opened in RHP to hide search icon.
### What changes do you think we should make in order to solve the problem?
If it is  not expected behavior we can delete this check and  always pass `shouldDisplaySearchRouter`  true [here](https://github.com/Expensify/App/blob/b7c1cfafecd03db14de4a4a30ac155fe4a7fb28b/src/components/MoneyReportHeader.tsx#L343C17-L343C42).

And if it is expected behavior then we should also check if screen is focused  [here](https://github.com/Expensify/App/blob/b7c1cfafecd03db14de4a4a30ac155fe4a7fb28b/src/components/MoneyReportHeader.tsx#L180C39-L180C53)
```
const isFocused = useIsFocused();

... 

isFocused && !isReportInRHP;
```

### What alternative solutions did you explore? (Optional)

**Comment by ChavdaSachin** [comment] 2024-10-25 16:03
## Proposal




### Please re-state the problem that we are trying to solve in this issue.

Inconsistency in displaying Search icon when returning to expenses opened from Search.



### What is the root cause of that problem?
- We purposefully hide search button, for header if report is open in RHP here.
https://github.com/Expensify/App/blob/b7c1cfafecd03db14de4a4a30ac155fe4a7fb28b/src/components/MoneyReportHeader.tsx#L180
- And here after coming back to report page from link - the report is no more part of RHP rather opens as a regular report.



### What changes do you think we should make in order to solve the problem?
- IMO here expected behavior should be - hide search button in RHP for web, but show search button even for RHP on mobile devices. 
- So add `isMobile()` check here.
https://github.com/Expensify/App/blob/b7c1cfafecd03db14de4a4a30ac155fe4a7fb28b/src/components/MoneyReportHeader.tsx#L180

And check in other parts of the app if we have any similar implementation and fix that as well.


### What alternative solutions did you explore? (Optional)




**Reminder:** Please use plain English, be brief and avoid jargon. Feel free to use images, charts or pseudo-code if necessary. Do not post large multi-line diffs or write walls of text. Do not create PRs unless you have been hired for this job.

**Comment by shahinyan11** [comment] 2024-10-25 16:16
## Proposal
[Updated](https://github.com/Expensify/App/issues/51476#issuecomment-2438107244). Made changes to make the thought expressed clearer and more understandable

**Comment by ChavdaSachin** [comment] 2024-10-25 16:17
## Proposal




### Please re-state the problem that we are trying to solve in this issue.
Inconsistency in displaying Search icon when returning to expenses opened from Search



### What is the root cause of that problem?
- We hide search button intentionally in case report is open in RHP here.
https://github.com/Expensify/App/blob/b7c1cfafecd03db14de4a4a30ac155fe4a7fb28b/src/components/MoneyReportHeader.tsx#L180
- So when report is first open from search router - it opens in RHP, and later navigating from link - it opens as general report screen which causes inconsistency.


### What changes do you think we should make in order to solve the problem?
- IMO expected behavior here should be - hide search button if report is open from RHP in web, and show search button even fro RHP on mobile devices. Coz for mobile devices RHP itself opens in main screen.
- Add `isMobile()` check here.
https://github.com/Expensify/App/blob/b7c1cfafecd03db14de4a4a30ac155fe4a7fb28b/src/components/MoneyReportHeader.tsx#L180




### What alternative solutions did you explore? (Optional)




**Reminder:** Please use plain English, be brief and avoid jargon. Feel free to use images, charts or pseudo-code if necessary. Do not post large multi-line diffs or write walls of text. Do not create PRs unless you have been hired for this job.

**Comment by FitseTLT** [comment] 2024-10-25 17:07
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
Inconsistency in displaying Search icon when returning to expenses opened from Search

### What is the root cause of that problem?
To display the search button we ensure that the report is not opened in RHP
https://github.com/Expensify/App/blob/a86ee35a6c9706d8acb35202acb4cdaa1cc769e7/src/components/MoneyRequestHeader.tsx#L68
The `isReportOpenInRHP` determines whether the report is open in RHP using the current navigation root state but the problem is `isReportInRHP` is updated every time there is a re-render so the value is determined on the navigation state at which the rerender happened so if current focused screen is not open in RHP when the re-calculation happened it will update the `isReportInRHP` false and when we navigate back to the report opened in RHP the value will not be updated and will hold the prev wrong value so it will show the search button for the report that was opened in search RHP, hence, the inconsistency.
### What changes do you think we should make in order to solve the problem?

We should calculate the isReportInRHP value once when the navigation is ready so we should:
```
const [isReportInRHP, setIsReportInRHP] = useState(true);
    useEffect(() => {
        Navigation.isNavigationReady().then(() => {
            setIsReportInRHP(isReportOpenInRHP(navigationRef?.getRootState()));
        });
    }, []);
```
We should do the same [here](https://github.com/FitseTLT/App/blob/a86ee35a6c9706d8acb35202acb4cdaa1cc769e7/src/components/MoneyReportHeader.tsx#L179) and [here](https://github.com/FitseTLT/App/blob/a86ee35a6c9706d8acb35202acb4cdaa1cc769e7/src/pages/home/HeaderView.tsx#L144)
### What alternative solutions did you explore? (Optional)

**Comment by isabelastisser** [comment] 2024-10-28 14:51
@muttmuure, how can I add this issue to [[#whatsnext] #quality](https://github.com/orgs/Expensify/projects/71)?

**Comment by hungvu193** [comment] 2024-10-29 09:04
I can't reproduce this one on latest main 🤔.  @isabelastisser  Can you reproduce this one?

https://github.com/user-attachments/assets/395f244f-e7cd-4924-b260-af819ab4c672

**Comment by hungvu193** [comment] 2024-10-30 02:05
> Based on OP the search icon should be displayed here:

The search icon shouldn't appear there because we opened the report from RHP.

**Comment by hungvu193** [comment] 2024-10-30 11:53
> Yeah right. However, RHP only exists on larger screens. On smaller screens, it behaves like a regular page. That’s why I proposed adding `isSmallScreenWidth` checks in [my proposal](https://github.com/Expensify/App/issues/51476#issuecomment-2438376737)

Yes. That was also my initial thoughts.

@isabelastisser Any thoughts?

**Comment by isabelastisser** [comment] 2024-11-04 21:13
@hungvu193, sorry for the delay! So, is this the expected behavior for the specific platform? Do you think we should close it then?

**Comment by hungvu193** [comment] 2024-11-05 08:48
> @hungvu193, sorry for the delay! So, is this the expected behavior for the specific platform? Do you think we should close it then?

RHP is only for large screen sizes. So I think we should show search icon for small screen size like mobiles and mobile web.

**Comment by isabelastisser** [comment] 2024-11-05 19:38
Got it! Thanks, @hungvu193! I agree that we can move forward with the recommendation here:

> Yeah right. However, RHP only exists on larger screens. On smaller screens, it behaves like a regular page. That’s why I proposed adding isSmallScreenWidth checks in https://github.com/Expensify/App/issues/51476#issuecomment-2438376737

**Comment by hungvu193** [comment] 2024-11-06 02:24
Cool. Let's go with @nyomanjyotisa 's [proposal](https://github.com/Expensify/App/issues/51476#issuecomment-2438376737)!
🎀 👀 🎀  C+ reviewed

**Comment by mvtglobally** [comment] 2024-11-08 15:27
Issue not reproducible during KI retests. (First week)

**Comment by hungvu193** [comment] 2024-11-20 06:29
# BugZero Checklist:

- [x] **[Contributor]** Classify the bug:

<details>
<summary>Bug classification</summary>


Source of bug:
  - [ ] 1a. Result of the original design (eg. a case wasn't considered)
  - [ ] 1b. Mistake during implementation
  - [ ] 1c. Backend bug
  - [x] 1z. Other: Improvement

Where bug was reported:
  - [x] 2a. Reported on production
  - [ ] 2b. Reported on staging (deploy blocker)
  - [ ] 2c. Reported on both staging and production
  - [ ] 2d. Reported on a PR
  - [ ] 2z. Other:

Who reported the bug:
  - [ ] 3a. Expensify user
  - [ ] 3b. Expensify employee
  - [ ] 3c. Contributor
  - [x] 3d. QA
  - [ ] 3z. Other:

</details>

- [x] **[Contributor]** The offending PR has been commented on, pointing out the bug it caused and why, so the author and reviewers can learn from the mistake.

    Link to comment: This is an improvement that we decided to improve after the discussion, there's no offending PR.

- [x] **[Contributor]** If the regression was CRITICAL (e.g. interrupts a core flow) A discussion in [#expensify-open-source](https://app.slack.com/client/E047TPA624F/C01GTK53T8Q) has been started about whether any other steps should be taken (e.g. updating the PR review checklist) in order to catch this type of bug sooner.

    Link to discussion: This is an small improvement, no need to create a slack convo.

- [x] **[Contributor]** If it was decided to create a regression test for the bug, please propose the [regression test](https://github.com/Expensify/App/blob/main/contributingGuides/REGRESSION_TEST_BEST_PRACTICES.md) steps using the template below to ensure the same bug will not reach production again.


## Regression Test:
1. Login with any account on your mobile.
2. Go to Search => Click to any expense.
3. Verify that there's Search icon.

Do we 👍  or 👎  ?

**Comment by garrettmknight** [comment] 2024-11-20 12:51
@isabelastisser can I get a payment summary when you get a chance?

**Comment by isabelastisser** [comment] 2024-11-20 15:41
Payment summary:

@hungvu193 requires payment through NewDot Manual Requests / C+ review $250 `PENDING`
@nyomanjyotisa paid in Upwork [automatic offer](https://www.upwork.com/nx/wm/offer/104771832) (Contributor) $250

**Comment by isabelastisser** [comment] 2024-11-20 15:45
All set!

**Closed by isabelastisser** 2024-11-20 15:45 UTC
Labels: External, Daily, Awaiting Payment, Bug

**Comment by garrettmknight** [comment] 2024-11-20 16:54
$250 approved for @hungvu193
