### ISSUE TITLE
[HOLD for payment 2024-03-20] [Violations] [$500] The optimistic transaction thread seems to be incorrect when scanning a receipt.

### ISSUE THREAD

**Issue by m-natarajan** [Expensify/App#33114] opened 2023-12-14 20:38 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

>[!important]
>This was supposed to be fixed in this [PR](https://github.com/Expensify/App/pull/35449), and even though we're sending the right optimistically generated values to the API after that PR, we're not setting the right reportID to navigate to from the report preview. 
>
>We think that can be accomplished with a change like this https://github.com/Expensify/App/pull/35449#issuecomment-1960558655

**Version Number:** 1.4.13-0
**Reproducible in staging?:** y
**Reproducible in production?:** y
**Issue reported by:** @mountiny 
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1702572514229909

## Action Performed:

1. Request money as a receipt
2. go quickly to the transaction thread

## Expected Result:
No error should show

## Actual Result:
you get error and you need to go to the parent and back down to the transaction thread which has different reportID

## Workaround:
Wait a few seconds before clicking into the transaction thread

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

![image (11)](https://github.com/Expensify/App/assets/38435837/76171e41-8ae3-4e7c-9a67-a1c368f739b5)

https://github.com/Expensify/App/assets/38435837/e8422814-ba13-4f2b-a287-e30928ad9537

https://github.com/Expensify/App/assets/38435837/d14ca5d5-c94e-4d73-8355-6cd864e9b387

https://github.com/Expensify/App/assets/165133/7b4cc495-5344-4f45-bf82-f5c464591132

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01c93082df6e0d8c71</li>
        <li>Upwork Job ID: 1761086287364259840</li>
        <li>Last Price Increase: 2024-02-23</li>
<li>Automatic offers: </li>
<ul>
<li>situchan | Contributor | 0</li>
<li>paultsimura | Contributor | 0</li>
</ul></li>
    </ul>
</details>

**Comment by cead22** [comment] 2024-01-19 00:09
HOLDing since I think this will be fixed by https://github.com/Expensify/App/issues/31411

**Comment by situchan** [comment] 2024-02-23 17:29
Happy to take this as C+ since I already have context

**Comment by cead22** [comment] 2024-02-23 17:53
Hmm, that didn't work as well as I hoped. @zanyrenney do you know how we can update this issue and the upwork job so that we can get proposals from contributors, and so that @situchan is the C+ assigned to review?

@ntdiary I assigned @situchan as the C+ since he reviewed the PR that was supposed to fix this

**Comment by cead22** [comment] 2024-02-23 18:10
@rayane-djouah can you please submit a proposal? The diff I shared there is what I found, but it'd be good to make sure that's actually the root cause of the issue, and check whether there are any other updates we need to make, or tests we can add

**Comment by paultsimura** [comment] 2024-02-23 18:10
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
The optimistic money request action redirects to an incorrect report

### What is the root cause of that problem?
Even though we are passing the correct thread IDs to the backend, we do not pass it to the optimistically created report action here:

https://github.com/Expensify/App/blob/690174f8f8326b68e6c67826455f76faed355c24/src/libs/actions/IOU.ts#L887-L903

### What changes do you think we should make in order to solve the problem?

We need to set the `childReportID` to the optimistic action:

```js
iouAction.childReportID = optimisticTransactionThread.reportID;
```

### What alternative solutions did you explore? (Optional)

**Comment by situchan** [comment] 2024-02-23 18:18
@paultsimura thanks for the proposal.
Can you please make sure that solution fixes all types of requests (manual, scan, distance)?
Also, test fully offline cases. (Make online after navigating to transaction detail page)

**Comment by paultsimura** [comment] 2024-02-23 18:56
Updated [the proposal](https://github.com/Expensify/App/issues/33114#issuecomment-1961778058) to cover the split & sendMoney requests as well.

**Comment by paultsimura** [comment] 2024-02-23 19:05
On a side note: seems like the SendMoneyElsewhere endpoint on the BE is not using the `transactionThreadReportID` param – we're sending it correctly, but the response comes with a Report with a different ID. This may need a BE change.

**Comment by cead22** [comment] 2024-02-23 20:23
@paultsimura good catch, it looks like that's the case for SendMoneyViaPaypal as well, right? I'll make an issue to update the backend for those two commands to accept `transactionThreadReportID` and `createdReportActionIDForThread`

**Comment by paultsimura** [comment] 2024-02-23 20:49
> that's the case for SendMoneyViaPaypal as well

I couldn't test the PayPal flow (do we have a test account?), but would assume you're right.

**Comment by paultsimura** [comment] 2024-02-26 23:19
Thanks. The PR is ready for review: https://github.com/Expensify/App/pull/37232

**Comment by paultsimura** [comment] 2024-02-27 08:33
False alert ☝️

**Comment by paultsimura** [comment] 2024-03-05 14:17
False alert ☝️

**Comment by zanyrenney** [comment] 2024-03-21 14:28
**Payment summary**
@paultsimura requires payment [automatic offer](https://www.upwork.com/nx/wm/offer/0) (Contributor) = PAID $500 ON UPWORK
@situchan requires payment [automatic offer](https://www.upwork.com/nx/wm/offer/0) (Contributor) PAID $500 ON UPWORK

**Closed by zanyrenney** 2024-03-21 14:28 UTC
Labels: External, Daily, Awaiting Payment, Bug
