### ISSUE TITLE
IOS - Contact list becomes empty after activating voice typing and deactivating it

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#54044] opened 2024-12-12 16:53 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 9.0.75-0
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**If this was caught on HybridApp, is this reproducible on New Expensify Standalone?:** Y
**If this was caught during regression testing, add the test name, ID and link from TestRail:** N/A
**Email or phone of affected tester (no customers):** nathanmulugetatesting+2434@gmail.com
**Issue reported by:** Applause - Internal Team
**Component** Left Hand Navigation (LHN)

## Action Performed:
1. Open IOS hybrid app
2. Tap on FAB > Start chat
4. While the input field is in focus tap on voice typing
5. Tap on it again to deactivate voice typing

## Expected Result:
The contact list shows recent and all contacts

## Actual Result:
The contact list becomes empty

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Standalone
- [ ] Android: HybridApp
- [ ] Android: mWeb Chrome
- [x] iOS: Standalone
- [x] iOS: HybridApp
- [ ] iOS: mWeb Safari
- [ ] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

<details>
  <summary>Add any screenshot/video evidence</summary>

  
</details> 

https://github.com/user-attachments/assets/cb12c457-3215-45d3-a0bf-a7a5e13db869

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by truph01** [comment] 2024-12-13 02:46
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
- The contact list becomes empty

### What is the root cause of that problem?
- The bug has been reported [here](https://github.com/facebook/react-native/issues/36521).

- When we deactivate voice typing, an additional ```U+FFFC``` is added to the end of input's value. It leads to the contact list becomes empty.
### What changes do you think we should make in order to solve the problem?
- We can update:
```
    const setValue = (newValue: string) => {
        let formattedValue = isMultiline ? newValue : newValue.replace(/\n/g, ' ');
        formattedValue = formattedValue.replace(/\uFFFC/g, '');
```

- It will remove the ```U+FFFC``` from the input value. We can consider only applying that removal if the platform is IOS.
https://github.com/Expensify/App/blob/10bfe9ab2895923c3f985d6529f6ff25809053e4/src/components/TextInput/BaseTextInput/index.native.tsx#L220-L221

### What specific scenarios should we cover in automated tests to prevent reintroducing this issue in the future?
- We can create the util function to get the formattedValue such as:

```
    const getFormattedText = (newValue)=>{
        let formattedValue = isMultiline ? newValue : newValue.replace(/\n/g, ' ');
        formattedValue = formattedValue.replace(/\uFFFC/g, '');
        return formattedValue
    }
```
and check if the input contains ```\uFFFC```, it should be removed from output.

### What alternative solutions did you explore? (Optional)

**Comment by joekaufmanexpensify** [comment] 2024-12-13 15:37
Ehhh, I am not convinced this is really worth doing anything about now. I can reproduce this, but if you type something in the search box, anything at all, the contacts appear again. It seems like the voice to text result is treated as a search result even when it's empty, so you just need to add something to bring about a different result. 

I'm not super convinced this will really come up frequently, if at all. As it is fairly intuitive that you just type in the box to see other results. 

I'm going to close this for now and we can revisit if actual customers report confusion about this. LMK if anyone disagrees with that!

**Closed by joekaufmanexpensify** 2024-12-13 15:37 UTC
Labels: Daily, Bug

**Comment by truph01** [comment] 2024-12-14 02:09
@joekaufmanexpensify I understand the low priority for now, but this issue could impact user experience significantly. When the contact list appears empty after voice typing, it’s not intuitive for users to know they just need to type something to restore it. This could lead to confusion or frustration, especially for first-time users or those relying on voice input. Fixing it now, with minimal effort, can prevent potential complaints later and ensure a smoother experience.

**Comment by joekaufmanexpensify** [comment] 2024-12-16 13:43
Hm, I am not sure I agree on the intuitiveness. I personally expect if someone sees empty search results, they're likely to either type something else, or navigate out and back into the page. Both of which resolve this. Further, I would be surprised if many/any customers intentionally experience this. In fact, the only real case I see for this is someone using voice to type by mistake because if there's any input there will be search results. In which case I'd expect them to type right after because they probably meant to be searching something with the keyboard. 

I still think we should wait and see if this impacts any customers and then fix it then, if so.
