### ISSUE TITLE
[$250] iOS - Expense - App crashes when opening Description and saving it a few times

### ISSUE THREAD

**Issue by izarutskaya** [Expensify/App#44437] opened 2024-06-26 10:01 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 9.0.2-0
**Reproducible in staging?:** Y
**Reproducible in production?:** N
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Issue reported by:** Applause-Internal team

## Action Performed:
1. Launch New Expensify app.
2. Go to FAB > Submit expense > Manual.
3. Submit a manual expense to any user.
4. Go to transaction thread.
5. Tap Description.
6. Tap Save.
7. Repeat Step 5 and 6 a few times.

## Expected Result:
App will not crash.

## Actual Result:
App crashes when opening Description and saving it a few times.

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [x] iOS: Native
- [ ] iOS: mWeb Safari
- [ ] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

https://github.com/Expensify/App/assets/115492554/acf639e4-60b1-4493-bee7-3b98dbbd9bc8

[Bug6524815_1719395555645!New_Expensify-2024-06-26-082221.txt](https://github.com/user-attachments/files/15986090/Bug6524815_1719395555645.New_Expensify-2024-06-26-082221.txt)

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~0183701f9c89311311</li>
        <li>Upwork Job ID: 1805978752685884090</li>
        <li>Last Price Increase: 2024-06-26</li>
<li>Automatic offers: </li>
<ul>
<li>brunovjk | Reviewer | 102888406</li>
</ul></li>
    </ul>
</details>

**Comment by izarutskaya** [comment] 2024-06-26 10:02
@lschurr I haven't added the External label as I wasn't 100% sure about this issue. Please take a look and add the label if you agree it's a bug and can be handled by external contributors.

**Comment by izarutskaya** [comment] 2024-06-26 10:02
We think this issue might be related to the #collect project.

**Comment by MonilBhavsar** [comment] 2024-06-26 13:22
able to reproduce

**Comment by MonilBhavsar** [comment] 2024-06-26 14:57
I'm able to reproduce on physical device and not on simulator. Client side logs didn't give much hints. Going to make it external

**Comment by MonilBhavsar** [comment] 2024-06-26 15:23
Some more insights from crashalytics 

This is indeed a deploy blocker as it started happening yesterday, and only happens on iOS

<img width="1316" alt="Screenshot 2024-06-26 at 8 50 44 PM" src="https://github.com/Expensify/App/assets/32012005/ea770e73-483a-4782-a569-f277e2f7043b">

Stack trace of the crash

<img width="631" alt="Screenshot 2024-06-26 at 8 51 56 PM" src="https://github.com/Expensify/App/assets/32012005/170dfe5f-88e6-45bd-bc04-31da387e1a8f">


The error seems to be coming from this line in react native animated library https://github.com/software-mansion/react-native-reanimated/blame/main/packages/react-native-reanimated/Common/cpp/Fabric/ReanimatedCommitMarker.cpp#L12
but I'm unable to connect the dots between that and recent deploys

**Comment by MonilBhavsar** [comment] 2024-06-26 16:00
I commented on the PR that seemed little sus to me https://github.com/Expensify/App/pull/43749

**Comment by rezkiy37** [comment] 2024-06-26 16:13
Hi, I’m Michael (Mykhailo) from Callstack and I would like to work on this issue.

**Comment by MonilBhavsar** [comment] 2024-06-26 16:15
Thanks Michael!

**Comment by rezkiy37** [comment] 2024-06-26 16:21
Yeah, I am taking a look at this issue tomorrow. If someone will find something earlier, feel free to post it here.

**Comment by brunovjk** [comment] 2024-06-26 20:00
> I'm able to reproduce on physical device and not on simulator.

I reproduced in simulator :D

https://github.com/Expensify/App/assets/95647348/0776975f-c9ac-402f-ae08-5bd21cd78b0e

**Comment by MonilBhavsar** [comment] 2024-06-27 04:50
Oh nice. Let me try. And that seems warning. That crash log should be different, no?

**Comment by rezkiy37** [comment] 2024-06-27 09:26
> > I'm able to reproduce on physical device and not on simulator.
> 
> I reproduced in simulator, after repeating steps 5 and 6 a few times
>  reproduce_44437.mov

It is not a crash, you have a warning. A real crash closes the app on a simulator as well.

**Comment by rezkiy37** [comment] 2024-06-27 10:18
I've downloaded builds before my PR (https://github.com/Expensify/App/pull/43749) and right after. I can confirm that the bug is not replicable on build 9.0.1-6. So please unassign me, since it is not a regression.

<details><summary>Details</summary>

![IMG_8835](https://github.com/Expensify/App/assets/57314631/df8739c9-70b3-4a10-9436-ae9009a219cd)

https://github.com/Expensify/App/assets/57314631/fddc97bb-bcf3-4433-98b4-e674dd101fe2

<img width="1195" alt="Screenshot 2024-06-27 at 12 09 54" src="https://github.com/Expensify/App/assets/57314631/0f336029-fa04-4d23-b100-44822a50c3d9">


</details>

**Comment by MonilBhavsar** [comment] 2024-06-27 14:37
Issue is being discussed here https://expensify.slack.com/archives/C01GTK53T8Q/p1719427158612849

**Comment by mountiny** [comment] 2024-06-27 17:07
CPing the PR, the PR will be validated on the checklist

**Comment by brunovjk** [comment] 2024-07-08 11:16
I think no payment is required for me here. @mountiny should I worry about the BZ checklist? Thanks.

**Comment by mountiny** [comment] 2024-07-08 11:31
@brunovjk no, I think that in fact, we can close this

**Comment by mountiny** [comment] 2024-07-08 11:32
I take it back, we should make sure we can get rid of the patch cc @tomekzaw @kirillzyusko what are the next steps to do that?

**Comment by kirillzyusko** [comment] 2024-07-08 16:12
@tomekzaw I think you need to debug that and figure out what is causing a crash?

I'm also admitting that the problem can be somewhere in `react-native-keyboard-controller` code (since it present in the callstack trace). If you discover something suspicious - feel free to reach out in Slack, I'll be happy to help you 🙌

**Comment by tomekzaw** [comment] 2024-07-08 19:55
Yep, I will investigate this.

**Comment by lschurr** [comment] 2024-07-10 15:49
I think this is wave-collect since it's expense related, but correct me if I'm wrong @mountiny

**Comment by mountiny** [comment] 2024-07-10 17:26
Yeah I think that works

**Comment by lschurr** [comment] 2024-07-18 22:07
How are we doing on this one @tomekzaw - are we holding on something?

**Comment by tomekzaw** [comment] 2024-07-19 05:57
@bartlomiejbloniarz is actively investigating this in Reanimated.

**Comment by tomekzaw** [comment] 2024-07-25 07:56
@bartlomiejbloniarz is still working on this.

**Comment by bartlomiejbloniarz** [comment] 2024-07-25 15:32
I was able to reproduce the issue in the 9.0.2 version of the App. The reason for this issue is that when a `TextInput` is removed during a `ShadowTree` commit, a Keyboard event is triggered. `react-native-keyboard-controller` listens to events using the reanimated `useEvent` hook, which synchronously (while still being inside the original commit) triggers another commit. It can happen that the first commit was also triggered by reanimated, which would break on of our assumptions -> that's why the `assert` was failing.

I spent some time trying to figure out if nested Shadow Tree commits should be allowed, but according to [this commit](https://github.com/facebook/react-native/commit/5f0435fb852cbb8abfe6cab77784ebddf1ad38ac), it seems that they are fine.

Hopefully we will have a fix for this issue merged soon, I have [prepared a PR to reanimated](https://github.com/software-mansion/react-native-reanimated/pull/6330) that should resolve it. From my tests it seems that newer versions of the Expensify App don't have this issue. I tried to reproduce it many times on main, but to no avail. If someone has reproduced the issue on newer version it would be good to know.

**Comment by lschurr** [comment] 2024-07-29 18:49
Looks like there is a draft PR up - any other update for now @bartlomiejbloniarz?

**Comment by bartlomiejbloniarz** [comment] 2024-07-30 13:22
I think that's all. The PR was merged. I tested the New Expensify App with these changes and everything worked fine.

**Comment by MonilBhavsar** [comment] 2024-07-31 09:03
Thank you for the help! 🙇 
I think we can revert the patch now

**Comment by tomekzaw** [comment] 2024-09-02 05:23
@bartlomiejbloniarz's PR https://github.com/software-mansion/react-native-reanimated/pull/6330 was merged and released in 3.15.0.

E/App now runs on Reanimated 3.15.1: https://github.com/Expensify/App/blob/main/package.json#L172

We can close this issue.

**Comment by brunovjk** [comment] 2024-09-02 13:43
Thank you very much @tomekzaw.
@izarutskaya, @MonilBhavsar can you confirm the [comment](https://github.com/Expensify/App/issues/44437#issuecomment-2323840056) above? Thanks

**Comment by MonilBhavsar** [comment] 2024-09-03 01:19
Sounds good. Let's close this. Thanks all for the help! 🚀

**Closed by MonilBhavsar** 2024-09-03 01:19 UTC
Labels: External, Engineering, Weekly, Bug
