### ISSUE TITLE
[$1000] mWeb - Request/Send Money Request/Send Money button is hidden by keyboard.

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#13795] opened 2022-12-22 18:59 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Go to staging.new.expensify.com
2. Log in with any account
3. Tap on Plus button
4. Select Request/Send Money
5. Put amount
6. Click Next Button

## Expected Result:
Request/Send Money button is not hidden by keyboard.

## Actual Result:
Request/Send Money button is hidden by keyboard.

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?

- [ ] Android / Chrome

**Version Number:** 1.2.43.1

**Reproducible in staging?:** Yes

**Reproducible in production?:** Yes

**Email or phone of affected tester (no customers):**

**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Notes/Photos/Videos:** Any additional supporting documentation

https://user-images.githubusercontent.com/93399543/209207328-6291aac5-1581-4da9-aa98-d4116e935aa6.mp4

**Expensify/Expensify Issue URL:**

**Issue reported by:** Applause - Internal Team

**Slack conversation:**

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01027fc55e9aab0d99</li>
        <li>Upwork Job ID: 1611358923710930944</li>
        <li>Last Price Increase: 2023-01-06</li>
    </ul>
</details>

**Comment by flaviadefaria** [comment] 2022-12-23 21:44
I'm going OoO today until January 9th and was assigned/reassigned multiple issues today but wasn't able to handle this one so I'm reassigning it.

**Comment by laurenreidexpensify** [comment] 2022-12-28 13:57
@kavimuru as a comparison can you include a recording of what this looks like in iOS or Android? How is this case handled there when it "Works"? Thanks!

**Comment by kavimuru** [comment] 2022-12-29 05:22
@laurenreidexpensify this is the behavior in Android. Button appears and it's not hidden.

https://user-images.githubusercontent.com/43996225/209906852-9948d0c0-1132-4ae5-aab3-dd67cecc3905.mp4

**Comment by laurenreidexpensify** [comment] 2023-01-03 13:57
And is this issue specifically happening on mWeb Android Chrome only, or was it reproducible on iOS mWeb too?

**Comment by laurenreidexpensify** [comment] 2023-01-06 11:02
Sorry this one fell off my radar - reviewing again today

**Comment by laurenreidexpensify** [comment] 2023-01-06 13:47
- [x] is a bug
- [x] Not a dupe but related issues:
- [x] Reproducible 
- [x] GH template complete
- [x]  Title and Body are clear 
- [x] Created by QA 
- [x] No Slack convo

**Comment by Prince-Mendiratta** [comment] 2023-01-06 14:16
I believe this is a dupe of #13491

**Comment by MariaHCD** [comment] 2023-01-09 08:25
I think this is a dupe of: https://github.com/Expensify/App/issues/10670

Thoughts, @laurenreidexpensify?

**Comment by laurenreidexpensify** [comment] 2023-01-09 13:19
oh that's a good catch @MariaHCD - didn't see that one in my checks. Agree and closing 👍🏽

**Closed by laurenreidexpensify** 2023-01-09 13:19 UTC
Labels: External, Daily, Help Wanted, Bug
