### ISSUE TITLE
[$1000] Message gets hidden after flagging as “Spam” and “Inconsiderate”.

### ISSUE THREAD

**Issue by kavimuru** [Expensify/App#20614] opened 2023-06-12 19:48 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1.	Open any report
2.	Flag a message as offensive
3.	Select “Spam” and “Inconsiderate”, (The description next to flag of both are “Sends anonymous warning and message is reported for review.”)
4.	Notice on selecting both of the flag options the message gets hidden.

## Expected Result: 
Message shouldn’t get hidden on selection of “Spam” and “Inconsiderate”.
## Actual Result: 
Message gets hidden on selection of “Spam” and “Inconsiderate”, whereas only sending anonymous warning and message is required.
## Workaround:
Can the user still use Expensify without this being fixed? Have you informed them of the workaround?

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [x] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 1.3.26-1
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/43996225/8d3fc309-7729-4abb-b22e-c5ae9f4da8e7

https://github.com/Expensify/App/assets/43996225/4a77b24a-ef17-4d5b-8fca-fbb1816ddfd3

**Expensify/Expensify Issue URL:**
**Issue reported by:** @usmantariq96
**Slack conversation:**  https://expensify.slack.com/archives/C049HHMV9SM/p1686130813221359

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~017a2e44a084dda5de</li>
        <li>Upwork Job ID: 1669226655341555712</li>
        <li>Last Price Increase: 2023-06-29</li>
    </ul>
</details>

**Comment by JmillsExpensify** [comment] 2023-06-15 06:12
Huh, yeah definitely odd. Opening this one up.

**Comment by JmillsExpensify** [comment] 2023-06-15 06:13
Also @usmantariq96, your report is only on Safari, but I'd expect this to occur on all platforms.

**Comment by Victor-Nyagudi** [comment] 2023-06-16 07:07
I'm not able to reproduce this on mobile or web after following the testing steps. 

The messages I get now are also different from what's shown in the second video by the applause tester.

![expensify-flagged-report-messages](https://github.com/Expensify/App/assets/79470910/7a0731ec-2c00-4cf3-a392-6a3623e69e5e)

The first flagged message is repeated when a message is flagged twice in the video, whereas when I do it, the second message is what's shown in the image above.

Tested this on staging `v1.3.28-5`.

@usmantariq96 (or anyone who sees this) could you kindly check again using the latest staging version and let me know if you still encounter this bug?

**Comment by JmillsExpensify** [comment] 2023-06-21 04:50
Huh, actually I'm also not able to reproduce this one now, and it's a feature that has been in active development, so all else equal, I think we should close this one now.

**Comment by JmillsExpensify** [comment] 2023-06-21 04:50
Essentially, this looks like a temporary issue that was already known at the time of reporting, because it's already been fixed.

**Comment by usmantariq96** [comment] 2023-06-21 04:55
@JmillsExpensify you are right currently it is not reproduceable.

Am I eligible for reporting bonus?

Thanks

**Comment by cristipaval** [comment] 2023-06-27 18:01
> Essentially, this looks like a temporary issue that was already known at the time of reporting, because it's already been fixed.

@JmillsExpensify does this mean that there's no pending payment and we can close the issue?

**Comment by cristipaval** [comment] 2023-06-30 11:47
I'll close the issue since it seems that the issue was fixed before it was reported.

**Closed by cristipaval** 2023-06-30 11:47 UTC
Labels: External, Daily, Help Wanted, Overdue, Bug
