### ISSUE TITLE
[$500] Web - Attachment - Unable to open popup "Enter the Password" using Enter Key

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#11354] opened 2022-09-27 20:20 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Go to staging.new.expensify.com
2. Log in with the account
3. Send PDF protected file
4. Click on PDF file
5. Use Tab key to navigate to Enter the Password name
6. Click Enter

## Expected Result:
Able to open popup "Enter the Password" using Enter Key

## Actual Result:
Unable to open popup "Enter the Password" using Enter Key

## Workaround:
Unknown

## Platform:

Where is this issue occurring?

- Web

**Version Number:** 1.2.7.2

**Reproducible in staging?:** Yes

**Reproducible in production?:** Yes

**Email or phone of affected tester (no customers):** any

**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Notes/Photos/Videos:** Any additional supporting documentation

https://user-images.githubusercontent.com/93399543/192626996-6a0aeb64-9e85-4c49-ba14-858d03545227.mp4

![Enter Key](https://user-images.githubusercontent.com/93399543/192627276-1f6cae41-3c08-4917-8a16-6edc46c5dd27.png)

**Expensify/Expensify Issue URL:** 

**Issue reported by:** Applause - Internal Team

**Slack conversation:** 

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by dhairyasenjaliya** [comment] 2022-09-28 15:06
**Proposal**

- Here for "**Enter the password**" we are using the `<TextLink>` component which is specially designed to open external links and has `accessibilityRole="link"` which is used to open external links on press enter 

- So for this issue use case we need to have a button component (Eg : TouchableOpacity, Pressable) that has actual `accessibilityRole="button"` which allows us to open the password page on pressing enter 

https://github.com/Expensify/App/blob/e5d766115babfe4fed51b97e8b7f65b6bec64f21/src/components/PDFView/PDFInfoMessage.js#L19-L38

- Need to modify and replace `<TextLink>` with `<TouchableOpacity>` inside `PDFInfoMessage.js` as per the below code snippet
- Also need to modify style as per current code which included in below code snippet


```
const PDFInfoMessage = props => (
    <View
        style={styles.alignItemsCenter}
    >
        <Icon
            src={Expensicons.EyeDisabled}
            width={variables.iconSizeSuperLarge}
            height={variables.iconSizeSuperLarge}
        />
        <Text style={[styles.h1, styles.mb3, styles.mt3]}>
            {props.translate('attachmentView.pdfPasswordForm.title')}
        </Text>
        <Text>{props.translate('attachmentView.pdfPasswordForm.infoText')}</Text>
        <View style={styles.flexRow}>
            <Text>
                {props.translate('attachmentView.pdfPasswordForm.beforeLinkText')}
            </Text>
            <TouchableOpacity
                onPress={props.onShowForm}
                style={[styles.link, styles.mh1]}

            >
                {` ${props.translate('attachmentView.pdfPasswordForm.linkText')} `}
            </TouchableOpacity>
            <Text>
                {props.translate('attachmentView.pdfPasswordForm.afterLinkText')}
            </Text>
        </View>

    </View>
);
```

**Results**

https://user-images.githubusercontent.com/47522946/192814776-e5032fb9-1522-49cf-be60-59b139656888.mov

**Comment by mallenexpensify** [comment] 2022-09-28 20:21
Job posted https://www.upwork.com/jobs/~0191c6efcfb886e0cf

**Comment by syedsaroshfarrukhdot** [comment] 2022-09-28 22:41
### Proposal

If we need to treat all LinkText to be opened on the keyboard enter press. Then we need to wrap Text in TextLink in a TouchableOpacity or I recommend creating a separate component for handling such cases.

https://github.com/Expensify/App/blob/e5d766115babfe4fed51b97e8b7f65b6bec64f21/src/components/TextLink.js#L36-L51

<img width="676" alt="Screen Shot 2022-09-29 at 3 05 56 AM" src="https://user-images.githubusercontent.com/81307212/192897340-933f46c0-6fe6-4f03-8a5f-083449e1f46e.png">

**OR**

If we even want to fix the issue only in PDFInfoMessage.js 

https://github.com/Expensify/App/blob/e5d766115babfe4fed51b97e8b7f65b6bec64f21/src/components/PDFView/PDFInfoMessage.js#L19-L38

We can replace TextLink with TouchableOpacity and style the TouchableOpacity by passing style={styles.link}

<img width="676" alt="Screen Shot 2022-09-29 at 3 18 14 AM" src="https://user-images.githubusercontent.com/81307212/192898786-1e3e4ed9-b165-4cb8-8b5a-9fdbe00ab460.png">

After My Code
<img width="676" alt="Screen Shot 2022-09-29 at 3 17 47 AM" src="https://user-images.githubusercontent.com/81307212/192898985-728284c9-4fbd-417d-9d54-eddca3987df0.png">

After Solution :- 

https://user-images.githubusercontent.com/81307212/192899373-44f91d93-059b-49b3-a963-0541089cf6a6.mov

**Comment by mallenexpensify** [comment] 2022-09-30 20:24
@kadiealexander auto-assigned to you, I'm going to be OOO for a month. Thx
@eVoloshchak can you @syedsaroshfarrukhdot 's proposal above please? https://github.com/Expensify/App/issues/11354#issuecomment-1261536595

**Comment by dhairyasenjaliya** [comment] 2022-10-01 03:52
Hello can you also review my proposal here https://github.com/Expensify/App/issues/11354#issuecomment-1261053137

**Comment by eVoloshchak** [comment] 2022-10-03 14:55
@dhairyasenjaliya's [proposal](https://github.com/Expensify/App/issues/11354#issuecomment-1261053137):
correctly identifies the root cause of the issue, thank you for thorough explanation

@syedsaroshfarrukhdot's [proposal](https://github.com/Expensify/App/issues/11354#issuecomment-1261536595):
extends on @dhairyasenjaliya's proposal, we definitely need to have this behavior for all of the TextLinks, so I think wrapping text in TextLink in a TouchableOpacity is a preferred approach.

**However**
Both proposals have an issue with vertical text alignment on mobile.
![Simulator Screen Shot - iPhone 12 - 2022-10-03 at 17 52 32](https://user-images.githubusercontent.com/9059945/193608347-516e5717-31ac-4f62-98a2-6c1b5e1b08e5.png)

Waiting for an updated proposal that addresses this issue

**Comment by dhairyasenjaliya** [comment] 2022-10-03 15:05
@eVoloshchak I think we shouldn't modify <TextLink> since this one is specific for links and i do think this works as except on external link on pressing enter here we have use case to just to enter form which is in our code base

**Comment by dhairyasenjaliya** [comment] 2022-10-03 15:26
hello @eVoloshchak I did check that we are using the `<TextLink>` component in many pages but here if we change to `<TextLink>` to use `<TouchableOpacity>` instead of `<Text>` then basically we will be adding `<TouchableOpacity>` inside `<Text>` which I think would be the not correct way for example below are just 3 examples how we are using `<TextLink>` in different pages and we have used this component 18 times  :

<img width="815" alt="Screenshot 2022-10-03 at 8 54 21 PM" src="https://user-images.githubusercontent.com/47522946/193615527-9f6b7774-efc8-4817-956b-fe530724790f.png">


<img width="813" alt="Screenshot 2022-10-03 at 8 54 51 PM" src="https://user-images.githubusercontent.com/47522946/193615653-b512d120-24a2-474f-8bff-085004cac36e.png">


<img width="816" alt="Screenshot 2022-10-03 at 8 55 12 PM" src="https://user-images.githubusercontent.com/47522946/193615726-e4aa6a13-5949-45a1-a6a9-181c02235c8a.png">

**Comment by eVoloshchak** [comment] 2022-10-03 17:59
> However if the team feels to change `<Text>` to `<TouchableOpacity>` then I will update proposal accordingly please let me know once you get chance

I'll post a discussion on Slack in a couple of hours.
Do you have ideas on how to fix the issue with alignment on mobile?

**Comment by dhairyasenjaliya** [comment] 2022-10-03 18:06
Sure will look into alignment on mobile

**Comment by syedsaroshfarrukhdot** [comment] 2022-10-03 19:09
Updated Proposal:- 

To fix the issue  of vertical alignment in mobile we need to do a refactoring of PDFInfoMessage.js 

Use below code snippet  in PDFInfoMessage.js 

### const PDFInfoMessage = props => (
    <View
        style={styles.alignItemsCenter}
    >
        <Icon
            src={Expensicons.EyeDisabled}
            width={variables.iconSizeSuperLarge}
            height={variables.iconSizeSuperLarge}
        />
        <Text style={[styles.h1, styles.mb3, styles.mt3]}>
            {props.translate('attachmentView.pdfPasswordForm.title')}
        </Text>
        <Text>{props.translate('attachmentView.pdfPasswordForm.infoText')}</Text>
        <View style={styles.flexRow}>
            <Text>
                {props.translate('attachmentView.pdfPasswordForm.beforeLinkText')}
            </Text>
            
            <TextLink onPress={props.onShowForm}>
                {` ${props.translate('attachmentView.pdfPasswordForm.linkText')} `}
            </TextLink>
           
            <Text>
                {props.translate('attachmentView.pdfPasswordForm.afterLinkText')}
            </Text>
        </View>

    </View>
);

if we need to add TouchableOpacity in all text link we can wrap TextLink.js in TouchableOpacity like this and it fixes all issues.

<img width="923" alt="Screen Shot 2022-10-04 at 12 06 17 AM" src="https://user-images.githubusercontent.com/81307212/193658605-24dc304b-9c63-4f00-8b00-906b97f78a8d.png">

Fix on Ios vertical alignment :- 
![Simulator Screen Shot - iPhone 13 Pro - 2022-10-04 at 00 08 29](https://user-images.githubusercontent.com/81307212/193658770-8d539f8d-be6d-4c71-a118-b2197bcc3f8d.png)

Fix on Ios vertical desktop/web  :- 
![Screen Shot 2022-10-04 at 12 08 50 AM](https://user-images.githubusercontent.com/81307212/193658813-9937ad7c-c6de-4400-9230-c1390a8f7fcb.png)

**Comment by syedsaroshfarrukhdot** [comment] 2022-10-03 19:40
> > However if the team feels to change `<Text>` to `<TouchableOpacity>` then I will update proposal accordingly please let me know once you get chance
> 
> I'll post a discussion on Slack in a couple of hours. Do you have ideas on how to fix the issue with alignment on mobile?

@dhairyasenjaliya @eVoloshchak We don't need to replace Text with TouchableOpacity we simply need to wrap Text Component in TextLink.js with TouchableOpacity as we can't pass strings directly to TouchableOpacity in ReactNative we always need to wrap strings in Text Component first.

Otherwise, we get this error on Mobile Platforms

![Simulator Screen Shot - iPhone 13 Pro - 2022-10-04 at 00 19 02](https://user-images.githubusercontent.com/81307212/193664134-b1bdabf3-2a80-45cf-a9f0-fb7ef8c2f964.png)

**Comment by eVoloshchak** [comment] 2022-10-03 22:57
Posted a question on slack 
https://expensify.slack.com/archives/C01GTK53T8Q/p1664835389118829

**Comment by mallenexpensify** [comment] 2022-10-04 18:22
@kadiealexander assigned myself and unassigned you cuz I'm NOT going to be OOO the next month ¯\_(ツ)_/¯

**Comment by mallenexpensify** [comment] 2022-10-10 16:37
Checking in our QA/Internal room for accessibility

**Comment by mallenexpensify** [comment] 2022-10-18 22:22
Didn't find much on my accessibility hunt.  Regardless of potential accessibility guidelines, tabbing to a box then clicking enter should be an option so we should fix this.  I doubled the price to $500 https://www.upwork.com/jobs/~0191c6efcfb886e0cf

**Comment by dhairyasenjaliya** [comment] 2022-10-19 03:24
**Proposal** 

- Continuing on the previous proposal as I mentioned we shouldn't wrap nested `<Text>`
- So I do find one more subtle way to handle this one we can add `onKeyDown` to the `<Text>` and listen to the `Enter` event once the user press enter we should open the form page 

- Creating `handleKeyDown` function

```
const handleKeyDown = (e, props) => {
    if (e.key !== 'Enter') {
        return;
    }e.preventDefault();
    if (props.onPress) {
        props.onPress();
        return;
    }

    Linking.openURL(props.href);
};
```

- Adding it to `<TextLink>` component 

```
const TextLink = (props) => {
    const additionalStyles = _.isArray(props.style) ? props.style : [props.style];
    return (
        <Text
            style={[styles.link, ...additionalStyles]}
            accessibilityRole="button"
            href={props.href}
            onKeyDown={(e) => { handleKeyDown(e, props); }}
            onPress={(e) => {
                e.preventDefault();
                if (props.onPress) {
                    props.onPress();
                    return;
                }

                Linking.openURL(props.href);
            }}
        >
            {props.children}
        </Text>
    );
};
```

**Result**

https://user-images.githubusercontent.com/47522946/196590144-483783ce-e6a8-45eb-93a4-04267dded83a.mov

cc @eVoloshchak, 
thank you for reminding almost forget this issue @mallenexpensify  :)

**Comment by eVoloshchak** [comment] 2022-10-19 19:01
I like @dhairyasenjaliya's proposal!
Not wrapping `Text` in another `View` is perfect, this would yield problems on native.
I think we can shrink down the code by using the same function for `onPress` and `onKeyDown`, so `TextLink` ends up looking something like this

```javascript
const TextLink = (props) => {
    const additionalStyles = _.isArray(props.style) ? props.style : [props.style];

    const handlePress = (e) => {
        e.preventDefault();
        if (props.onPress) {
            props.onPress();
            return;
        }

        Linking.openURL(props.href);
    };

    return (
        <Text
            onPress={handlePress}
            onKeyDown={(e) => {
                if (e.key !== 'Enter') {
                    return;
                }

                handlePress(e);
            }}
```

🎀👀🎀 C+ reviewed!
cc: @mallenexpensify

**Comment by dhairyasenjaliya** [comment] 2022-10-20 05:15
yeah was planning for the same since both are the same function thanx for the further input :)

**Comment by mallenexpensify** [comment] 2022-10-20 20:14
@tgolen can you please review @dhairyasenjaliya 's proposal https://github.com/Expensify/App/issues/11354#issuecomment-1283364164
Thx

**Comment by tgolen** [comment] 2022-10-23 17:45
The proposal looks good 👍

**Comment by dhairyasenjaliya** [comment] 2022-10-24 19:30
accepted

**Comment by mallenexpensify** [comment] 2022-10-25 01:13
Hired @eVoloshchak and @dhairyasenjaliya

**Comment by parasharrajat** [comment] 2022-11-04 20:09
Regression: I can reproduce this issue. 
Step: 
1. Click :heavy_plus_sign: on the composer. 
2. Click add attachment.
3. Select a locked PDF. 
4. On the attachment Modal. 
5. Tab over the  `enter the password` link. 
6. Press Enter. 
7. attachment is sent instead of showing the passwordForm.

**Comment by parasharrajat** [comment] 2022-11-08 17:02
we kind of take every failing case as regression. This should have been tested on the PR before merging.

**Comment by mallenexpensify** [comment] 2022-11-09 02:25
@isabelastisser Reassigning as I'm heading OOO for a month

**Comment by mvtglobally** [comment] 2022-11-09 03:34
Issue not reproducible during KI retests. (First week)

**Comment by isabelastisser** [comment] 2022-11-11 15:11
Reviewing this by EOD.

**Comment by parasharrajat** [comment] 2022-11-11 18:24
Bump @eVoloshchak https://github.com/Expensify/App/issues/11354#issuecomment-1304136387

**Comment by eVoloshchak** [comment] 2022-11-14 14:10
> Bump @eVoloshchak [#11354 (comment)](https://github.com/Expensify/App/issues/11354#issuecomment-1304136387)

This is something I should have caught when testing the PR

What should be my next steps here? Do an RCA?

**Comment by parasharrajat** [comment] 2022-11-15 23:51
@dhairyasenjaliya should create a PR to fix it. As we already know the Root issue, no RCA is needed.

@eVoloshchak You can start by reviewing their suggestions above.

**Comment by mvtglobally** [comment] 2022-11-16 02:15
Issue not reproducible during KI retests. (Second week)

**Comment by dhairyasenjaliya** [comment] 2022-11-16 03:45
> @dhairyasenjaliya should create a PR to fix it. As we already know the Root issue, no RCA is needed.
> 
> @eVoloshchak You can start by reviewing their suggestions above.

sure let's get this PR done

**Comment by eVoloshchak** [comment] 2022-11-16 17:01
> * If we are enabling accessibility we need to check if the component is focused and pressing enter should fire the necessary press event so removing `pressOnEnter` on `<Button>` solves the problem for [this](https://github.com/Expensify/App/issues/11354#issuecomment-1304136387) I'm not sure what should be the correct behavior after enabling accessible to `Enter the password`  maybe we need to ask team for this particular scenario

That means we lose the current behavior where the user is pressing enter while having nothing focused and the attachment is sent, correct?

**Comment by dhairyasenjaliya** [comment] 2022-11-17 18:10
> If we are removing it everywhere, this will resolve our issue

yup it will

**Comment by eVoloshchak** [comment] 2022-11-21 08:31
Looks like there is discussion in https://github.com/Expensify/App/issues/7968#issuecomment-1320879129, let's wait for the answer

**Comment by dhairyasenjaliya** [comment] 2022-11-21 17:13
@eVoloshchak similar issue just got closed thoughts 
https://github.com/Expensify/App/issues/7968#issuecomment-1322105351

**Comment by parasharrajat** [comment] 2022-11-21 17:22
If we already merged a PR that is supposed to fix this issue then I don't see a reason backing out now. Unless we hit a hard rock, we can try to fix the regression as well. Otherwise, if we are thinking of closing this one then the task is not complete.

**Comment by eVoloshchak** [comment] 2022-11-21 17:32
<img width="801" alt="image" src="https://user-images.githubusercontent.com/9059945/203120522-39203510-760b-41aa-99a9-639cd032c680.png">

Based on this we just need to set the `pressOnEnter` to `false`. But I'd say that being able to just press enter to send an attachment is great and we shouldn't remove it

I suppose we have a couple of options

- set the `pressOnEnter` to `false`
- set the `pressOnEnter` to `false` and focus the 'send' button when the modal is opened
- detect if `enter the password` link is focused, otherwise keep current behaviour

@parasharrajat, should I ask about this on slack?

**Comment by dhairyasenjaliya** [comment] 2022-11-21 17:54
@parasharrajat this issue is different to add onEnter key to `<TextLink>` which is working well(this PR) the only problem is when we have a button along with `pressOnEnter` at that time it overrides enter event and makes similar situation related here which i think is globally affect https://github.com/Expensify/App/issues/7968#issuecomment-1320879129

**Comment by parasharrajat** [comment] 2022-11-21 17:59
Yes, it might be considered different.

**Comment by eVoloshchak** [comment] 2022-11-21 18:07
Asking [here](https://expensify.slack.com/archives/C01GTK53T8Q/p1669054027301429)

**Comment by eVoloshchak** [comment] 2022-11-22 19:32
Got an [answer](https://expensify.slack.com/archives/C01GTK53T8Q/p1669058634323699?thread_ts=1669054027.301429&cid=C01GTK53T8Q):
> I would recommend we close or deprioritize this issue. Having the Enter button work perfectly in every scenario is a good long term goal, but feels like an accessibility feature we don’t need to prioritize for right now.

**Comment by isabelastisser** [comment] 2022-11-22 20:42
Per the comment above, I'm closing this issue.

**Comment by isabelastisser** [comment] 2022-11-22 21:05
I'm sorry, reopening this!

**Comment by isabelastisser** [comment] 2022-11-28 12:18
@eVoloshchak @parasharrajat , I'm trying to move this issue forward but I'm confused because of the additional issue mentioned [here ](https://expensify.slack.com/archives/C01GTK53T8Q/p1669054027301429):

- Was the original bug fixed?

- I see the job closed in Upwork, was it paid?

@tgolen , what's the progress on the PR?

> https://github.com/Expensify/App/issues/11354#issuecomment-1300665713

**Comment by dhairyasenjaliya** [comment] 2022-11-28 12:23
@isabelastisser yes the primary purpose of this PR was to add the onEnter event to `<TextLink>` which works well except for one condition where we have a button with 'onPressEnter` added which overrides the enter event of `<TextLink>`, so this particular case I think we have the conclusion to deprioritize since this is that particular condition is more of global and is part of keyboard accessibility 

- for me also hasn't been paid off yet

**Comment by isabelastisser** [comment] 2022-11-30 12:23
Update: 

- The original bug was fixed.
- We've decided to deprioritize the issue caused by fixing the original bug. Context[ here](https://expensify.slack.com/archives/C01GTK53T8Q/p1669058634323699?thread_ts=1669054027.301429&cid=C01GTK53T8Q).
- I've paid @eVoloshchak and @dhairyasenjaliya in Upwork now.
- The contract has been completed, and the Upwork post has been closed.
- No more actions are needed, so I'm closing this as completed!

**Closed by isabelastisser** 2022-11-30 12:23 UTC
Labels: External, Engineering, Daily, Bug
