### ISSUE TITLE
[$250] [Search v2.3] - Current name is not populated in the name field and it is not auto-focused

### ISSUE THREAD

**Issue by IuliiaHerets** [Expensify/App#49207] opened 2024-09-14 17:42 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 9.0.35-0
**Reproducible in staging?:** Y
**Reproducible in production?:** N/A - new feature, doesn't exist in prod
**Issue was found when executing this PR:** https://github.com/Expensify/App/pull/48566
**Email or phone of affected tester (no customers):** applausetester+kh010901@applause.expensifail.com
**Issue reported by:** Applause Internal Team

## Action Performed:
Precondition:
- User has saved a few searches.

1. Go to staging.new.expensify.com
2. Go to Search.
3. Click 3-dot menu next to a saved search > Rename.
4. Save a custom name.
5. Click 3-dot menu next to the same saved search > Rename.

## Expected Result:
The current name will be populated in the name field and it will auto-focused.

## Actual Result:
The current name is not populated in the name field and it is not auto-focused.

## Workaround:
Unknown

## Platforms:

- [x] Android: Native
- [x] Android: mWeb Chrome
- [x] iOS: Native
- [x] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

https://github.com/user-attachments/assets/0cb53f81-4ede-4fee-800b-2dbe24ceb0e4

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Issue Owner</summary>Current Issue Owner: @jayeshmangwani</details>
<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~021836684527709552516</li>
        <li>Upwork Job ID: 1836684527709552516</li>
        <li>Last Price Increase: 2024-09-19</li>
<li>Automatic offers: </li>
<ul>
<li>Nodebrute | Contributor | 104051960</li>
</ul></li>
    </ul>
</details>

**Comment by srikarparsi** [comment] 2024-09-14 21:04
Hi @lakchote or @luacmartins, do you think you could take a look at this whenever you have a chance? I think this comes from this [PR](https://github.com/Expensify/App/pull/48566)

**Comment by srikarparsi** [comment] 2024-09-14 21:07
I think the auto-focussed part has been reported [here](https://github.com/Expensify/App/pull/48566#issuecomment-2348780630)

**Comment by luacmartins** [comment] 2024-09-15 22:22
This is [known](https://github.com/Expensify/App/pull/48566#issuecomment-2350245989) and NAB. We're addressing it in a follow up

**Comment by jayeshmangwani** [comment] 2024-09-19 10:08
> We're addressing it in a follow up

@luacmartins @lakchote If we're going to address this in a follow-up, should we close the issue or assign it to the person who will tackle it?

**Comment by lakchote** [comment] 2024-09-19 12:57
@jayeshmangwani I'd like you to review Nodebrute's proposal [here](https://github.com/Expensify/App/issues/49207#issuecomment-2351082030).

Then I'll assign, if the proposal sounds good.

**Comment by jayeshmangwani** [comment] 2024-09-19 13:12
@lakchote We can go with @Nodebrute's [Proposal](https://github.com/Expensify/App/issues/49207#issuecomment-2351082030). Adding the `inputCallbackRef` to the `ref` of the `InputWrapper` and setting the `defaultValue` looks good.

**Comment by QasimBham** [comment] 2024-09-19 13:16
Proposal
Please re-state the problem that we are trying to solve in this issue.
Current name is not populated in the name field and it is not auto-focused

What is the root cause of that problem?
We are not autofocusing [this](https://github.com/Expensify/App/blob/0c618acc8b5a0b77eb27dfa049a18e3135c51c52/src/pages/Search/SavedSearchRenamePage.tsx#L58C17-L59C47) field and we are also not adding defaultValue

What changes do you think we should make in order to solve the problem?
We can use the state management for this. We can use the defaultValue = {name}. Other than this we can use the default state set to {name}. 
Optional: we can also pass value prop

What alternative solutions did you explore? (Optional)

**Comment by jayeshmangwani** [comment] 2024-09-20 05:53
@lakchote Nodebrute's proposal looks good to me. [What do you think](https://github.com/Expensify/App/issues/49207#issuecomment-2360951367)?

**Comment by lakchote** [comment] 2024-09-20 08:42
@Nodebrute's proposal LGTM.

**Comment by slafortune** [comment] 2024-09-23 16:01
not deployed yet

**Comment by jayeshmangwani** [comment] 2024-10-08 06:17
@slafortune PR has been in production for 2 weeks, and it's now ready for payment.

**Comment by slafortune** [comment] 2024-10-09 16:25
@jayeshmangwani - Role C+ - is not due payment Expert Contributor/Call Stack
@Nodebrute - Role Contributor - Paid $250 via Upworks

**Closed by slafortune** 2024-10-09 16:25 UTC
Labels: Reviewing, External, Engineering, Weekly, Bug

**Comment by jayeshmangwani** [comment] 2024-10-09 16:51
@slafortune Please update the summary, I am not an Expert Contributor; I am a C+.
