### ISSUE TITLE
mweb - Long press on image opens iOS shortcut to share, save or copy image

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#23193] opened 2023-07-19 20:22 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Go to any chat
2. Send an image attachment
3. Long press on the exact image not on that message area

## Expected Result:
It should just open Expensify menu

## Actual Result:
In Safari It shows iOS default options to share, save or copy image

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [x] iOS / Safari
- [ ] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 1.3.42-19
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/93399543/ececc8a1-7bf1-4b6c-a53a-5259da3427eb

![IMG_6545](https://github.com/Expensify/App/assets/93399543/c9f93ab7-bdd3-41e3-a272-ebc29da7ba09)

**Expensify/Expensify Issue URL:**
**Issue reported by:** @DinalJivani
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1689707604574439

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by s-alves10** [comment] 2023-07-19 21:37
Dupe of https://github.com/Expensify/App/issues/21344

**Closed** 2023-07-20 01:13 UTC
Labels: Daily, Bug
