### ISSUE TITLE
[HOLD for payment 2024-03-29] [MEDIUM] Distance - Unable to save manually entered address after selecting address from list

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#37640] opened 2024-03-01 20:49 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.46-0
**Reproducible in staging?:** Y 
**Reproducible in production?:** Y
**If this was caught during regression testing, add the test name, ID and link from TestRail:** https://expensify.testrail.io/index.php?/tests/view/4355973
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** Applause - Internal Team
**Slack conversation:**

## Action Performed:
Precondition:
- There are a few addresses in recent destination list
1. Go to staging.new.expensify.com
2. Go offline
3. Go to workspace chat
4. Open distance request page
5. Click Start
6. Select an address from the recent list and save it
7. Click Start again
8. Manually enter an address
9. Save it

## Expected Result:
The new address is saved

## Actual Result:
The new address is not saved

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [x] Android: mWeb Chrome
- [x] iOS: Native
- [x] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details>  

https://github.com/Expensify/App/assets/78819774/3d1407a2-8505-4ecb-91d0-71bedd813101

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~011597298ea5827798</li>
        <li>Upwork Job ID: 1763727574947143680</li>
        <li>Last Price Increase: 2024-03-02</li>
    </ul>
</details>

**Comment by lanitochka17** [comment] 2024-03-01 20:50
We think that this bug might be related to #wave5
CC @dylanexpensify

**Comment by lanitochka17** [comment] 2024-03-01 20:50
@greg-schroeder  FYI I haven't added the External label as I wasn't 100% sure about this issue. Please take a look and add the label if you agree it's a bug and can be handled by external contributors

**Comment by bernhardoj** [comment] 2024-03-02 04:38
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
Can't save an address while offline if there is already a previously selected address while online.

### What is the root cause of that problem?
The distance start and stop list shows either the waypoint name or address.
https://github.com/Expensify/App/blob/af68510ad375bc99679908ce26dafead3a8b3dc1/src/components/DistanceRequest/DistanceRequestRenderItem.tsx#L54

When we first select a suggested waypoint while online, we save both of the waypoint name and address.
https://github.com/Expensify/App/blob/af68510ad375bc99679908ce26dafead3a8b3dc1/src/pages/iou/request/step/IOURequestStepWaypoint.tsx#L143-L151

While offline, we also try to save both waypoint name and address.
https://github.com/Expensify/App/blob/af68510ad375bc99679908ce26dafead3a8b3dc1/src/pages/iou/request/step/IOURequestStepWaypoint.tsx#L116-L131

However, the waypoint name is always undefined because `values` is an object that contains the form data. The form data of the waypoint has only one input, which is the waypoint address. So, the previous waypoint address is overwritten, but not with the name.

### What changes do you think we should make in order to solve the problem?

While offline, we will never be able to get the address name, so to overwrite the previous waypoint name, we can just set `null` to the name.
```
name: null,
```

_this was previously fixed in https://github.com/Expensify/App/pull/33692_

**Comment by 5695mp** [comment] 2024-03-02 04:40
● Use State to Manage Address:

➢Define a state variable to store the address, let's call it address.
   Use the useState hook to manage the address state.
   
➢Update Address when Manually Entered:
  Update the address state when the user manually enters an address.
  
➢Select Address from List:
  When the user selects an address from the list, update the address state with the selected address.
  
➢Save the Address:
   Provide a button or trigger to save the address.
   When the save button is pressed, save the address state to your database or storage.

**Comment by Tony-MK** [comment] 2024-03-02 05:04
## Proposal

### Please re-state the problem that we are trying to solve in this issue.

Distance - Unable to save manually entered address after selecting an address from the list

### What is the root cause of that problem?

In the [`saveWaypoint`](https://github.com/Expensify/App/blob/af68510ad375bc99679908ce26dafead3a8b3dc1/src/libs/actions/Transaction.ts#L63) function, the onyx only merges the `waypoint.address` while the previous data the waypoint persists.

https://github.com/Expensify/App/blob/af68510ad375bc99679908ce26dafead3a8b3dc1/src/libs/actions/Transaction.ts#L64-L67

Therefore, when the user submits the new waypoint, `lng`, `lat`, and `address` will not be nullified but be reused.

https://github.com/Expensify/App/blob/f92b845aff8c030b2a3fd2c76c69d9e06bf101c8/src/pages/iou/request/step/IOURequestStepWaypoint.tsx#L123-L130

### What changes do you think we should make in order to solve the problem?


In the [`saveWaypoint`](https://github.com/Expensify/App/blob/af68510ad375bc99679908ce26dafead3a8b3dc1/src/libs/actions/Transaction.ts#L63) function, check if `lat` and `lng` are present in the waypoint to deleting `lat` and `lng` from the transaction's onyx waypoints.

To do this we can either use `Onyx.set` before or after `Onyx.merge` or create a condition in this [line](https://github.com/Expensify/App/blob/af68510ad375bc99679908ce26dafead3a8b3dc1/src/libs/actions/Transaction.ts#L67).

`!waypoint.lng || !waypoint.lng ? {lat: null, lng: null, ...waypoint} : waypoint`

I do not see a regression with leaving `waypoint.address`. 
Therefore, we can leave it but could remove it to deal with unknown edge cases.

**Comment by Tony-MK** [comment] 2024-03-02 20:33
Hi @parasharrajat, I believe we need remove `lat` and `lng` because the waypoint will then get added to [`recentWaypointAlreadyExists`](https://github.com/Expensify/App/blob/22cb01c968a53407f7a9d864bfba30f41366f6a0/src/libs/actions/Transaction.ts#L102-L107) if the condition illustrated below is not satistied.

https://github.com/Expensify/App/blob/22cb01c968a53407f7a9d864bfba30f41366f6a0/src/libs/actions/Transaction.ts#L90-L94

**Comment by abzokhattab** [comment] 2024-03-04 18:26
I see that the invalid address is already not returned as a recent address when online or offline


https://github.com/Expensify/App/assets/59809993/7005fe5b-3601-4632-9bd9-f8e1dbdce802

**Comment by Tony-MK** [comment] 2024-03-04 22:58
If the address is invalid, the waypoint will still be valid because the GPS coordinates from the previous valid waypoint are sent as a part of the waypoint in the `updateMoneyRequestDistance` request parameters.

![updateMoneyRequestDistance](https://github.com/Expensify/App/assets/22982173/fd1e2ae1-f96b-429d-b632-f0fb5b211c73)

Since the backend expects the `lat` and `lng` to be valid, we can verify the address offline. 

Hence, we have to remove the `lat` and `lng` for the backend to instead consider the waypoint as new and unverified.

***Notice that the GPS coordinates from the merged `modifiedWaypoints` are identical to the initial `waypoints`***

**1) Initial `waypoints` before editing `waypoint0` offline**

![Offline](https://github.com/Expensify/App/assets/22982173/95332645-4ff2-4762-bf59-2dd2f628cb1e)

**2) Merged `modifiedWaypoints` after going online**

![Online](https://github.com/Expensify/App/assets/22982173/e09ec3e1-adf2-4da9-9e11-fb87e7c0bfd9)

However, removing `lat` and `lng` will prevent an invalid address from being considered a valid waypoint.

**Comment by amyevans** [comment] 2024-03-06 17:17
Not overdue - just assigned

**Comment by amyevans** [comment] 2024-03-08 21:34
@abzokhattab what's a reasonable ETA to expect a PR?

**Comment by greg-schroeder** [comment] 2024-03-25 08:53
Payment pending, not overdue

**Comment by greg-schroeder** [comment] 2024-03-30 01:11
Processing

**Comment by greg-schroeder** [comment] 2024-03-30 01:14
Offer sent @abzokhattab

**Comment by greg-schroeder** [comment] 2024-03-30 01:14
@abzokhattab - C - $500
@parasharrajat - C+ - $500 (you can make a ND manual request)

**Comment by abzokhattab** [comment] 2024-03-30 01:15
Thank you ... just accepted the offer

**Comment by greg-schroeder** [comment] 2024-03-30 01:16
filed regression test, paying, closing

**Closed by greg-schroeder** 2024-03-30 01:16 UTC
Labels: External, Weekly, Awaiting Payment, Bug

**Comment by JmillsExpensify** [comment] 2024-06-11 18:42
$500 approved for @parasharrajat
