### ISSUE TITLE
DEV: Console warning on Requested Step at Connect Bank account.

### ISSUE THREAD

**Issue by kavimuru** [Expensify/App#14411] opened 2023-01-19 17:04 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Actions performed:

1. Go to settings.
2. Go to Any workspace, create a new one if none exists.
3. Go to Connect Bank account on the Workspace main page.
4. Follow Connect Manual flow until Personal information step

## Expected result:
No warning should be logged.

## Actual Result:
Prop type warning is logged.

## Workaround:
unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?

- [ ] iOS / native

**Version Number:** 
**Reproducible in staging?:** Needs reproduction
**Reproducible in production?:** Needs reproduction
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** 
`Warning: Failed prop type: The prop `reimbursementAccountDraft` is marked as required in `RequestorOnfidoStep`, but its value is `undefined`.
RequestorOnfidoStep@webpack-internal:///./src/pages/ReimbursementAccount/RequestorOnfidoStep.js:76:86
withOnyx@webpack-internal:///./node_modules/react-native-onyx/dist/web.development.js:2135:73
withLocalize(Component)
RequestorStep@webpack-internal:///./src/pages/ReimbursementAccount/RequestorStep.js:86:86
withOnyx@webpack-internal:///./node_modules/react-native-onyx/dist/web.development.js:2135:73
withLocalize(Component)
div
View<@webpack-internal:///./node_modules/@expensify/react-native-web/dist/exports/View/index.js:52:19
KeyboardAvoidingView
div
View<@webpack-internal:///./node_modules/@expensify/react-native-web/dist/exports/View/index.js:52:19
SafeAreaConsumer
ScreenWrapper@webpack-internal:///./src/components/ScreenWrapper/index.js:64:86
withNetwork(ScreenWrapper)
withOnyx@webpack-internal:///./node_modules/react-native-onyx/dist/web.de…
react_devtools_backend.js:4012:25`
**Expensify/Expensify Issue URL:**
**Issue reported by:** @parasharrajat 
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1674044222710599

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by adelekennedy** [comment] 2023-02-02 20:56
From @parasharrajat [in thread](https://expensify.slack.com/archives/C049HHMV9SM/p1674044222710599)
>This is a dev warning and It can't be reproduced on staging as we disable those logs on staging and PROD.
IMO, we should assign some Engineer to reproduce this first and if they can't then we can close it.

**Comment by AndrewGable** [comment] 2023-02-06 18:09
Cannot reproduce anymore.

**Closed by AndrewGable** 2023-02-06 18:09 UTC
Labels: Engineering, Daily, Needs Reproduction, Overdue, Bug
