### ISSUE TITLE
[HOLD for payment 2024-03-07] [$500] Video - Unable to adjust volume by clicking on any part of the volume slider

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#36952] opened 2024-02-20 21:19 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.43-3
**Reproducible in staging?:** Y
**Reproducible in production?:** N
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** Applause - Internal Team
**Slack conversation:**

## Action Performed:
1. Go to staging.new.expensify.com
2. Go to any chat
3. Upload a video
4. In the preview, click on the volume icon
5. Click on the volume slider to adjust

## Expected Result:
User should be able to adjust volume by clicking on any length of the volume slider

## Actual Result:
Video player volume does not respond until user holds and drags across the slider

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details> 

https://github.com/Expensify/App/assets/78819774/84dd709c-4bce-42fb-acef-e92a489dd448

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01ddb8fc91ce5926ec</li>
        <li>Upwork Job ID: 1760051536709566464</li>
        <li>Last Price Increase: 2024-02-20</li>
<li>Automatic offers: </li>
<ul>
<li>cubuspl42 | Reviewer | 0</li>
</ul></li>
    </ul>
</details>

**Comment by lanitochka17** [comment] 2024-02-20 21:20
We think that this bug might be related to #vip-vsp
CC @quinthar

**Comment by roryabraham** [comment] 2024-02-20 22:00
def-o related to https://github.com/Expensify/App/pull/30829

**Comment by roryabraham** [comment] 2024-02-20 22:32
I think that:

- since this is a bug with the new video player feature
- we're not planning to deploy NewDot to prod this week

we should let @Skalakid and SWM take point on fixing this issue. Making it a daily

**Comment by francoisl** [comment] 2024-02-20 22:38
cc @kowczarz

**Comment by kowczarz** [comment] 2024-02-21 09:44
I will take a look on this

**Comment by kowczarz** [comment] 2024-02-21 11:03
The root cause in this proposal is fine https://github.com/Expensify/App/issues/36952#issuecomment-1955161601, but composing is IMO an overkill. 
Instead I would add additional handler on begin pan event: 
```js
    const gestureEventHandler = (event) => {
        const val = Math.floor((1 - event.y / sliderHeight) * 100) / 100;
        volume.value = Math.min(Math.max(val, 0), 1);
     }
    const pan = Gesture.Pan()
        .onBegin((event) => {
            runOnJS(setIsSliderBeingUsed)(true);
            gestureEventHandler(event)
        })
        .onChange((event) => {
            gestureEventHandler(event);
        })
        .onEnd(() => {
            runOnJS(setIsSliderBeingUsed)(false);
        });
```

**Comment by roryabraham** [comment] 2024-02-27 08:41
[PR](https://github.com/Expensify/App/pull/37094) awaiting review from @cubuspl42

**Comment by garrettmknight** [comment] 2024-03-07 19:52
BugZero Checklist: The PR fixing this issue has been merged! The following checklist ([instructions](https://stackoverflow.com/c/expensify/questions/14574)) will need to be completed before the issue can be closed:

- [ ]  [@cubuspl42] The PR that introduced the bug has been identified. Link to the PR:
- [ ]  [@cubuspl42] The offending PR has been commented on, pointing out the bug it caused and why, so the author and reviewers can learn from the mistake. Link to comment:
- [ ]  [@cubuspl42] A discussion in #expensify-bugs has been started about whether any other steps should be taken (e.g. updating the PR review checklist) in order to catch this type of bug sooner. Link to discussion:
- [ ]  [@cubuspl42] Determine if we should create a regression test for this bug.
- [ ]  [@cubuspl42] If we decide to create a [regression test](https://github.com/Expensify/App/blob/main/contributingGuides/REGRESSION_TEST_BEST_PRACTICES.md) for the bug, please propose the regression test steps to ensure the same bug will not reach production again.
- [ ]  [@garrettmknight] Link the GH issue for creating/updating the regression test once above steps have been agreed upon:

**Comment by garrettmknight** [comment] 2024-03-07 19:53
@cubuspl42 all paid - can you complete the checklist?

**Comment by cubuspl42** [comment] 2024-03-08 09:32
- The PR that introduced the bug has been identified. Link to the PR:
    -  N/A; more like a new feature/case
- The offending PR has been commented on, pointing out the bug it caused and why, so the author and reviewers can learn from the mistake. Link to comment:
    - N/A
- A discussion in #expensify-bugs has been started about whether any other steps should be taken (e.g. updating the PR review checklist) in order to catch this type of bug sooner. Link to discussion:
    - No need for additional discussion
- Determine if we should create a regression test for this bug.
    - No
- If we decide to create a regression test for the bug, please propose the regression test steps to ensure the same bug will not reach production again.
    - N/A

**Closed** 2024-03-11 11:02 UTC
Labels: External, Engineering, Weekly, Awaiting Payment
