### ISSUE TITLE
[HOLD for payment 2024-01-11] [$500] Task - Task assignee list opens with deep link when user has no access to edit task

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#33296] opened 2023-12-19 15:26 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.14.0
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** Applause - Internal Team
**Slack conversation:**

## Action Performed:
Precondition:
- User is a member of the #announce workspace room in which a task is created and assigned to other user.
1. Log in as member of the workspace.
2. Go to #announce room.
3. Click on the task.
4. Add /assignee to the end of the link.
5. Select a different assignee.

## Expected Result:
Not here page opens.

## Actual Result:
Task assignee list opens.

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [x] Android: mWeb Chrome
- [x] iOS: Native
- [x] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

https://github.com/Expensify/App/assets/93399543/032635f8-42b0-445b-9c4f-bb89e19327b9

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01c0cdfb5367dcebe3</li>
        <li>Upwork Job ID: 1737132419534086144</li>
        <li>Last Price Increase: 2023-12-19</li>
<li>Automatic offers: </li>
<ul>
<li>dukenv0307 | Contributor | 28067679</li>
<li>c3024 | Contributor | 28072736</li>
</ul></li>
    </ul>
</details>

**Comment by FitseTLT** [comment] 2023-12-19 15:33
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
Task assignee list opens with deep link when user has no access to edit task

### What is the root cause of that problem?
We are not checking if the user `canModifyTask` as we do to enable the assignee menu item before rendering the `TaskAssigneeSelectorModal` assignee page
### What changes do you think we should make in order to solve the problem?

We need to navigate back if `canModifyTask` is false to a user or return not found page
### What alternative solutions did you explore? (Optional)

**Comment by BhuvaneshPatil** [comment] 2023-12-19 15:37
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
Task - Task assignee list opens with deep link when user has no access to edit task

### What is the root cause of that problem?
In this condition, even if we are checking for `!canModifyTask`, `!isOpen` will be false for open task and making `(!canModifyTask || !isOpen)` as false, and whole condition as false.
```js
const isTaskNonEditable = ReportUtils.isTaskReport(report) && (!canModifyTask || !isOpen);
```

### What changes do you think we should make in order to solve the problem?
We shall change this condition to somewhat this - 
```js
const isTaskNonEditable = ReportUtils.isTaskReport(report) &&  !canModifyTask &&  !isOpen;
```
This way we will ensure
that only open task and the user with enough permission will see the content.

### What alternative solutions did you explore? (Optional)

**Comment by yh-0218** [comment] 2023-12-19 16:33
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
Task - Task assignee list opens with deep link when user has no access to edit task
### What is the root cause of that problem?
We did get `report` as props of parent on `TaskAssigneeSelectorModal`
so `props.rootParentReportPolicy` is empty on `TaskAssigneeSelectorModal`
### What changes do you think we should make in order to solve the problem?
We can passed from `reportID` from param.
```js
rootParentReportPolicy: {
            key: ({route}) => {
                const report = ReportUtils.getReport(route.params.reportID)
                const rootParentReport = ReportUtils.getRootParentReport(report);
                return `${ONYXKEYS.COLLECTION.POLICY}${rootParentReport ? rootParentReport.policyID : '0'}`;
            },
            selector: (policy) => _.pick(policy, ['role']),
},
```
### What alternative solutions did you explore? (Optional)

**Comment by narefyev91** [comment] 2023-12-20 08:14
Proposal from @dukenv0307 looks good to me https://github.com/Expensify/App/issues/33296#issuecomment-1863051968
In case that we already have all reports at this page - no needs to have additional subscription to specific report from onyx
Let's just work with reports and reportId
🎀 👀 🎀 C+ reviewed

**Comment by lakchote** [comment] 2023-12-22 14:12
@dukenv0307's proposal LGTM 👍

**Comment by c3024** [comment] 2023-12-22 15:55
Taking this over.

**Comment by garrettmknight** [comment] 2023-12-29 16:30
@c3024 you're up!

**Comment by c3024** [comment] 2023-12-29 16:32
PR review done. Awaiting final approval for merge by @lakchote

**Comment by garrettmknight** [comment] 2023-12-29 17:02
Reassigning since @lakchote is out for parental leave.

**Comment by robertjchen** [comment] 2023-12-30 04:02
Merged!

**Comment by c3024** [comment] 2024-01-12 18:46
**BugZero Checklist:** The PR fixing this issue has been merged! The following checklist ([instructions](https://stackoverflow.com/c/expensify/questions/14574)) will need to be completed before the issue can be closed:

* [x]  [@c3024] The PR that introduced the bug has been identified. Link to the PR: #32165 
* [x]  [@c3024] The offending PR has been commented on, pointing out the bug it caused and why, so the author and reviewers can learn from the mistake. Link to comment: https://github.com/Expensify/App/commit/de9e6d4be3a367d9947ba2e2167e74e6669a5df0#r136920736
* [x]  [@c3024] A discussion in #expensify-bugs has been started about whether any other steps should be taken (e.g. updating the PR review checklist) in order to catch this type of bug sooner. Link to discussion: NA
* [x]  [@c3024] Determine if we should create a regression test for this bug. Yes
* [x]  [@c3024] If we decide to create a regression test for the bug, please propose the [regression test](https://github.com/Expensify/App/blob/main/contributingGuides/REGRESSION_TEST_BEST_PRACTICES.md) steps to ensure the same bug will not reach production again.

**Comment by c3024** [comment] 2024-01-12 18:55
### Regression test proposal
1. In the #announce room of a workspace W, create a task as User A and assign it to User B
2. Log in as User C (who is also a member of the workspace W)
3. Go to #announce room of the workspace W
4. Click on the task created at step 1
5. Add `/assignee` to the end of the URL and visit the URL
6. Verify that "Not here" page is displayed.

👍 or 👎

**Comment by garrettmknight** [comment] 2024-01-15 16:13
Everybody's paid and the QA issue is up. Closing!

**Closed by garrettmknight** 2024-01-15 16:13 UTC
Labels: External, Engineering, Daily, Overdue, Awaiting Payment, Bug
