### ISSUE TITLE
[$1000] Web - Country search input is cleared/reset when updating language on another device

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#23851] opened 2023-07-29 11:51 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Login to any account
2. Go to Settings -> Profile -> Persona details -> Home address -> Country
3. Type any text to search a country
4. Go to another device, login same account
5. Change to another language on this device

## Expected Result:
Country search input should be remain current search text  when updating language on another device

## Actual Result:
Country search input is cleared/reset when updating language on another device

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [x] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 1.3.47-2
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/93399543/c423bbad-3cb7-4738-a509-0dae15d9cfa8

https://github.com/Expensify/App/assets/93399543/22ba6407-8f89-4a22-b5a1-d6ebfa44013f

**Expensify/Expensify Issue URL:**
**Issue reported by:** @hoangzinh
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1690556043839129

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~016ec8ed64c16cfa11</li>
        <li>Upwork Job ID: 1694407216392552448</li>
        <li>Last Price Increase: 2023-08-23</li>
    </ul>
</details>

**Comment by kbecciv** [comment] 2023-07-29 11:52
**Proposal by**: @hoangzinh
**Slack conversation**: https://expensify.slack.com/archives/C049HHMV9SM/p1690556043839129

## Proposal
### Please re-state the problem that we are trying to solve in this issue.
Country search input is cleared/reset when updating language on another device
### What is the root cause of that problem?
In the CountryPicker, we have a `useEffect` that reset the search text value when `allCountries` is changed. `allCountries` is changed when preferred language changed => when preferred language changed it reset the search text value, in this case it will reset to an empty string.
https://github.com/Expensify/App/blob/28644a5ba4e824c5a7e09660b35b3170f614eaac/src/components/CountryPicker/index.js#L38-L40
### What changes do you think we should make in order to solve the problem?
I guess the `useEffect` above is used to set `search text value` when `props.value` is changed, then it will be used in the [CountrySelectorModal](https://github.com/Expensify/App/blob/28644a5ba4e824c5a7e09660b35b3170f614eaac/src/components/CountryPicker/index.js#L74)
So I think we can remove the [useEffect above](https://github.com/Expensify/App/blob/28644a5ba4e824c5a7e09660b35b3170f614eaac/src/components/CountryPicker/index.js#L38-L40) and call set `search text value` with `props.value` in the show picker modal callback here https://github.com/Expensify/App/blob/28644a5ba4e824c5a7e09660b35b3170f614eaac/src/components/CountryPicker/index.js#L42-L44

**Comment by alexpensify** [comment] 2023-07-31 22:56
Not overdue - I was assigned over the weekend and will test soon.

**Comment by alexpensify** [comment] 2023-08-02 18:38
There are some upcoming changes to the Country selector. I'm going to put it on hold to confirm if this behavior still happens when the update goes to production.

**Comment by alexpensify** [comment] 2023-08-08 23:04
I believe the options will become dropdown following this update: https://github.com/Expensify/App/issues/22018

**Comment by alexpensify** [comment] 2023-08-16 23:40
Thanks for flagging, I'll test again to confirm if we get the same experience now. @hoangzinh please test too and share if you get the same result as before.

**Comment by alexpensify** [comment] 2023-08-23 17:53
@allroundexperts - since this bug is reproducible, I'm moving it from the hold state. When you get a chance, please review the proposal to see if it will fix this issue. Thanks!

**Comment by alexpensify** [comment] 2023-08-30 22:22
@puneetlath - we need some feedback here, thanks!

**Comment by puneetlath** [comment] 2023-09-04 19:43
Hi, sorry, I know I'm coming into this super late, but I'm not sure I agree that this is a bug. Is this a real scenario, where a user would change their language preference on one device while actively using the product in another? 

And if they did, I don't think the user would be surprised to see the input cleared in that scenario. That behavior feels fine and normal to me. 

I know a lot of work has gone into this already, so my apologies, but my vote would be to close this issue.

**Comment by alexpensify** [comment] 2023-09-06 21:33
@puneetlath can we get your feedback again or should we move this to Slack for a bigger discussion?

**Comment by puneetlath** [comment] 2023-09-07 21:35
Does this have to be handled on an input-by-input basis? Or in other words, do the other inputs do what the proposal suggests? 

I would be down for a global solution. But if we have to handle each input individually and then remember to do it for every one going forward, I don't think this is worth our time just for the two tabs scenario.

**Comment by puneetlath** [comment] 2023-09-10 21:05
Ok got it, thanks for the clarifications. I'm going to go ahead and assign @hoangzinh as @allroundexperts suggested.

**Comment by puneetlath** [comment] 2023-09-11 15:32
Ah cool, that sounds good and works for me.

**Comment by puneetlath** [comment] 2023-09-11 16:42
Ah wow ok. Well thanks for your effort! Onto the next one.

**Comment by puneetlath** [comment] 2023-09-12 16:35
Hmm, yes I suppose your bug was reported first. Can you go ahead and apply to the job?

**Comment by alexpensify** [comment] 2023-09-12 22:14
I'm OOO until Thursday but will work on the required process when I return. The key is applying to the job. Thanks!

**Comment by puneetlath** [comment] 2023-09-13 14:04
All handled. Thanks y'all for all the effort.

**Closed by puneetlath** 2023-09-13 14:04 UTC
Labels: Daily, Internal, Bug

**Comment by alexpensify** [comment] 2023-09-14 16:18
Thanks @puneetlath -- no action on my end. The payment was sent via Upwork.
