### ISSUE TITLE
[HOLD for payment 2023-07-17] [$1000] Web - Mouse cursor is shown as hand icon (on a not clickable section) on who paid, split bill

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#21695] opened 2023-06-27 15:50 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Go to '+" -> new group -> select members
2.  Click create group
3. Now it should show a new group page
4. Go to ''+"  on new group page -> split bill -> type the amount -> next
5. Notice who paid? card section, the cursor is shown as the mouse pointer

## Expected Result:
The arrow cursor should be shown instead of mouse cursor as the who paid section ( where the user who paid is shown)

## Actual Result:
Mouse cursor is shown as hand icon (on a not clickable section) on who paid, split bill

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [x] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 1.3.30-5
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/93399543/f7b61150-3c9e-404e-a6ae-8cde0a2d9f59

https://github.com/Expensify/App/assets/93399543/181ad4d6-6f06-4ee2-899d-4b90304bca1b

**Expensify/Expensify Issue URL:**
**Issue reported by:** @ashimsharma10 
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1687527115940319

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~013377045cdf090308</li>
        <li>Upwork Job ID: 1673779406484242432</li>
        <li>Last Price Increase: 2023-06-27</li>
    </ul>
</details>

**Comment by Santhosh-Sellavel** [comment] 2023-06-27 22:20
@ginsuma Your proposal didn't work for me, please check again!

**Comment by Santhosh-Sellavel** [comment] 2023-06-27 22:43
Sorry for the confusion, my apologies it works. Something wrong with my setup. Working now.

**Comment by Santhosh-Sellavel** [comment] 2023-06-27 23:14
@ginsuma's Proposal looks good here. 

For CME
This issue raises minor concerns, 

On the confirmation page, while we create a SplitBill from a group chat, we will be able to unselect users from `Who was there? ` but in the flow where we create a SpiltBill from the FAB button, we will not be able to unselect anyone still we allow to click on all the users and will show the User Details page. I believe post this proposal we will not be able to click Who paid in FAB flow also, are we fine with that, or should exclude that?

C+ Reviewed
🎀 👀 🎀 

cc: @lschurr

**Comment by Santhosh-Sellavel** [comment] 2023-06-27 23:46
Cool @ginsuma, I'm not sure whether we want that, thanks anyway! Let's wait for @amyevans!

**Comment by amyevans** [comment] 2023-06-28 18:58
I'm not sure that disabling the `Who Paid` section is the way we should go from a design perspective (for instance, I could see an alternative being removing the circle/checkmark altogether). So I'd like @Expensify/design's eyes on it first before we proceed.

**Comment by Santhosh-Sellavel** [comment] 2023-06-28 18:59
Good call @amyevans!

**Comment by Santhosh-Sellavel** [comment] 2023-06-29 16:11
@shawnborton Can you confirm [this](https://github.com/Expensify/App/issues/21695#issuecomment-1612106446) works for you?

**Comment by shawnborton** [comment] 2023-06-29 16:34
Works for me!

**Comment by amyevans** [comment] 2023-06-29 17:14
Cool, assigning @ginsuma!

**Comment by amyevans** [comment] 2023-06-30 22:49
Heads up I'm OOO Mon/Tue next week.

**Comment by Santhosh-Sellavel** [comment] 2023-07-10 20:14
PR is Merged!

**Comment by lschurr** [comment] 2023-07-14 17:03
@ashimsharma10 @Santhosh-Sellavel @ginsuma - please apply for the job in Upwork here: https://www.upwork.com/jobs/~013377045cdf090308

**Comment by Santhosh-Sellavel** [comment] 2023-07-14 17:08
@lschurr Will collect on ND.

**Comment by ashimsharma10** [comment] 2023-07-14 17:12
@lschurr applied!

**Comment by lschurr** [comment] 2023-07-14 17:23
@Santhosh-Sellavel could you work on the checklist? Do we need a regression test?

**Comment by amyevans** [comment] 2023-07-14 17:32
Agreed!

**Comment by lschurr** [comment] 2023-07-14 17:35
Thanks all! I'll issue payments on Monday and close.

**Comment by lschurr** [comment] 2023-07-17 15:41
@ashimsharma10 - could you clarify what's going on in Upwork? Did you accept the offer?

**Comment by ashimsharma10** [comment] 2023-07-17 16:02
@lschurr it is shown "withdrawn offer". Can u please offer me again at https://www.upwork.com/freelancers/~018a92cf13e1e88eed.

**Comment by lschurr** [comment] 2023-07-17 16:23
Payments are sent. Closing.

**Closed by lschurr** 2023-07-17 16:23 UTC
Labels: External, Weekly, Awaiting Payment, Bug

**Comment by Santhosh-Sellavel** [comment] 2023-07-20 19:18
Requested for payment on ND.

**Comment by anmurali** [comment] 2023-07-23 07:39
Approved based on https://github.com/Expensify/App/issues/21695#issuecomment-1636173729
