### ISSUE TITLE
[Paid] [HOLD for payment 2023-10-31] [$500] [HIGH] [P2P ACTIVATION] GBR is not shown when a pending payment is waiting on the user to enable their wallet

### ISSUE THREAD

**Issue by kevinksullivan** [Expensify/App#30033] opened 2023-10-19 22:46 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

Coming from : https://expensify.slack.com/archives/C05RECHFBEW/p1697739357210919

And https://github.com/Expensify/App/pull/29430 is the relevant PR that will likely need to be revisited. 

## Action Performed:
1. Send an IOU from user without enabled wallet to another account with an enabled wallet
2. Pay the IOU from the other account

## Expected Result:
There should be a system message prompting the user to enable their wallet, and there should be a GBR in the chat for that user, since they have an outstanding action to collect the funds.

## Actual Result:
There is no GBR

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01d5e47fb869ecebeb</li>
        <li>Upwork Job ID: 1715313432707346432</li>
        <li>Last Price Increase: 2023-10-20</li>
<li>Automatic offers: </li>
<ul>
<li>situchan | Contributor | 27292792</li>
<li>b4s36t4 | Contributor | 27294338</li>
</ul></li>
    </ul>
</details>

**Comment by trjExpensify** [comment] 2023-10-20 10:07
I'll take over the BZ on this one. CC: @samh-nl @akinwale as we're discussing in [this thread](https://expensify.slack.com/archives/C01GTK53T8Q/p1697795982969879?thread_ts=1697788964.150409&cid=C01GTK53T8Q).

**Comment by techievivek** [comment] 2023-10-20 10:20
Let's also fix the double message coming from here: https://expensify.slack.com/archives/C01GTK53T8Q/p1697796531033319?thread_ts=1697788964.150409&cid=C01GTK53T8Q

**Comment by b4s36t4** [comment] 2023-10-20 10:21
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
GBR is not shown when a pending payment is waiting on the user to enable their wallet
### What is the root cause of that problem?

We have written a condition to show the GBR if there is any action needed from the user here in this line https://github.com/Expensify/App/blob/ca51f6ff762971bf785271a9958987653fa3f992/src/libs/ReportUtils.js#L1287

But if see the condition it's going to be false in case `isWaitingOnBankAccount` this being `true`. As the other user paid the amount we mark the property `hasOutStandIOU` as `false` which makes the conditional doesn't work.


### What changes do you think we should make in order to solve the problem?

We need to update the condition here https://github.com/Expensify/App/blob/ca51f6ff762971bf785271a9958987653fa3f992/src/libs/ReportUtils.js#L1287 as followed.

```jsx
if ((report.hasOutstandingIOU && report.ownerAccountID === currentUserAccountID) || report.isWaitingOnBankAccount) {
```

In this way if the user doesn't had setup a wallet we show GBR.



### What alternative solutions did you explore? (Optional)
NA

<img width="979" alt="Screenshot 2023-10-20 at 3 50 56 PM" src="https://github.com/Expensify/App/assets/59088937/a7de0b2a-4593-49d5-92d3-d63713a4a852">

**Comment by techievivek** [comment] 2023-10-20 10:24
We have two IOU actions when a user pays a money request via wallet(one for create and one for pay).

Create IOU action gets used for rendering the MoneyRequestAction from here: https://github.com/Expensify/App/blob/69cf29e32950f915ea888fe294dfdea6a9fabbb5/src/pages/home/report/ReportActionItem.js#L319

The reimbursememntQueued action gets used to show the enable wallet button and the system message informing we are waiting for the payee to enable their wallet/bank account.

The remaining IOU action(type:Pay) falls under else block here: https://github.com/Expensify/App/blob/69cf29e32950f915ea888fe294dfdea6a9fabbb5/src/pages/home/report/ReportActionItem.js#L414 and we show a different system message saying the payee needs to enable their bank account(because `isWaitingBankAccount` is set on the report.(Checkout the [getReportPreview](https://github.com/Expensify/App/blob/69cf29e32950f915ea888fe294dfdea6a9fabbb5/src/pages/home/report/ReportActionItemMessage.js#L46) method).

**Comment by situchan** [comment] 2023-10-20 11:20
@b4s36t4 the root cause is correct but the solution is wrong.
`isWaitingOnBankAccount` is true on both accounts. We should not show GBR on payer side

**Comment by situchan** [comment] 2023-10-20 11:20
@techievivek should we fix double message issue as well here and ask contributors update proposal?

**Comment by techievivek** [comment] 2023-10-20 11:21
Yes, please.

> @b4s36t4 the root cause is correct but the solution is wrong.
isWaitingOnBankAccount is true on both accounts. We should not show GBR on payer side

Good one. 👌

**Comment by b4s36t4** [comment] 2023-10-20 11:27
@situchan @techievivek Will update my proposal soon.

**Comment by b4s36t4** [comment] 2023-10-20 12:05
@situchan updated proposal for the first issue (GBR). Working on the double system message fix. Will update soon.

**Comment by b4s36t4** [comment] 2023-10-20 12:32
Updated the proposal to include the double system message as well.

**Comment by b4s36t4** [comment] 2023-10-20 12:33
@techievivek Just wondering about the double message system, do we want to show the wallet message or bank message?!

**Comment by trjExpensify** [comment] 2023-10-20 12:36
- Wallet message for an iouReport. 
- bank message for an expenseReport.

**Comment by trjExpensify** [comment] 2023-10-20 14:01
Do we have a PR to link here?

**Comment by b4s36t4** [comment] 2023-10-20 14:03
@trjExpensify Not yet, still working. Android build is a bit late.

**Comment by trjExpensify** [comment] 2023-11-02 00:46
👋 checklist time! Bump, @situchan.

**Comment by techievivek** [comment] 2023-11-06 10:48
Not overdue, gentle bump @situchan ^

**Comment by situchan** [comment] 2023-11-09 14:18
No regression. This is new feature.

I am not sure regression test is needed as it requires gold wallet which QA team doesn't have.

**Comment by trjExpensify** [comment] 2023-11-10 00:04
Interesting. @kevinksullivan @joekaufmanexpensify are their no wallet regression tests in the app?

**Comment by trjExpensify** [comment] 2023-11-10 00:06
Confirming payments as follows: 

@situchan $500 for C+ review
@b4s36t4 $500 for the bug fix.

**Comment by trjExpensify** [comment] 2023-11-10 00:08
Settled up with you both! Keeping open for a sec while we discuss [await this](https://github.com/Expensify/App/issues/30033#issuecomment-1804867308).

**Comment by b4s36t4** [comment] 2023-11-10 03:14
@trjExpensify isn't this also eligible for urgency bonus? We have a single pr for the both issues can you check please?

**Comment by trjExpensify** [comment] 2023-11-10 09:57
I don't think we double up the urgency bonus for every issue a PR is linked to. It's a bonus for moving forward the PR with urgency, so I applied it on the payment for the other issue. 👍

**Comment by joekaufmanexpensify** [comment] 2023-11-10 15:42
>are their no wallet regression tests in the app?

I see a few in testrail. I think the original P2P implementation was before we had standardized on the current regression testing system in Testrail. I bet the few that have been added were part of the #gold-wallets room/project.

**Comment by trjExpensify** [comment] 2023-11-13 14:24
Erm, I might be blind. Mind linking me to them?

**Comment by joekaufmanexpensify** [comment] 2023-11-14 15:40
>Erm, I might be blind. Mind linking me to them?

I see some in the `Edit IOUs and other tests` section: https://expensify.testrail.io/index.php?/suites/view/7722&group_by=cases:section_id&group_order=asc&display_deleted_cases=0&group_id=296079

**Comment by trjExpensify** [comment] 2023-11-14 15:44
Hm, weird place for them. Also, it's creating a `Wallet` via OldDot. 

>Log in with a new applause.expensifail account
>Navigate to OldDot > Account > Payments and add a Personal Bank account using the credentials shared below
>Verify you see a payment type for WALLET with a deposit status of "Silver"

**Comment by joekaufmanexpensify** [comment] 2023-11-14 18:23
Ah, interesting. Then, maybe there aren't really any for the NewDot P2P yet

**Comment by trjExpensify** [comment] 2023-11-14 23:25
Asked [here](https://expensify.slack.com/archives/C05R3DG0L4C/p1700004257744549) in the #gold-wallets channel.

**Comment by trjExpensify** [comment] 2023-11-20 16:59
Okay, put that on the radar of the gold wallets team. Going to close this out now.

**Closed by trjExpensify** 2023-11-20 16:59 UTC
Labels: External, Daily, Overdue, Awaiting Payment, Bug
