### ISSUE TITLE
mWeb - Copied check mark is placed to the left of "copied"  in share code inconsistent to the usual right side

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#22139] opened 2023-07-03 20:21 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Login to staging new dot
2. Go to setting and click on share code
3. Click on copy to url and observe the  :white_check_mark: mark appears to the left of "copied"
4. Go to reimbursements and observe that the :white_check_mark: mark is placed at the right of the copied document
6. Go to security>Two factor authentication and observe that the :white_check_mark: mark is placed next to copied when copying codes

## Expected Result:
Check mark placement should be consistent

## Actual Result:
Check mark placement is not consistent

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [x] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [ ] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 1.3.35-5
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation

![IMG_20230702_141846](https://github.com/Expensify/App/assets/93399543/c3830397-e14b-4c49-866c-e774dc10331e)
![IMG_20230702_141900](https://github.com/Expensify/App/assets/93399543/c6d1b724-2386-4da7-8eb2-7f1bc5a38d83)
![IMG_20230702_141916](https://github.com/Expensify/App/assets/93399543/ba3e62e1-fa90-49ca-8ecb-b199a515dc2e)

**Expensify/Expensify Issue URL:**
**Issue reported by:** @sofoniasN
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1688297288377259

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by AdekolaThanni** [comment] 2023-07-03 21:03
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
Inconsistencies with copied check mark position

### What is the root cause of that problem?
This is due to the rendering of a different component by the ShareCodePage which is this 
```
<ContextMenuItem
                            text={this.props.translate('qrCodes.copyUrlToClipboard')}
                            shouldShowRightIcon
                            icon={Expensicons.Copy}
                            successIcon={Expensicons.Checkmark}
                            successText={this.props.translate('qrCodes.copied')}
                            onPress={() => Clipboard.setString(url)}
                        />
```

But in other examples, like the reimbursement and QRcode page the copy to clipboard component is resultedly rendered by <PressableWithDelayToggle /> component

### What changes do you think we should make in order to solve the problem?
The <ContextMenuItem /> component in the ShareCodePage should be replaced with this

```
<PressableWithDelayToggle
            text={this.props.translate('qrCodes.copyUrlToClipboard')}
            tooltipText={this.props.translate('qrCodes.copyUrlToClipboard')}
            tooltipTextChecked={this.props.translate('qrCodes.copied')}
            icon={Expensicons.Copy}
            onPress={() => Clipboard.setString(url)}
        />
```

### What alternative solutions did you explore? (Optional)
None

**Comment by AdekolaThanni** [comment] 2023-07-03 21:05
Contributor details
Your Expensify account email: adekolathanni@gmail.com
Upwork Profile Link: https://www.upwork.com/freelancers/~0138ee1594d38a0775

**Comment by shawnborton** [comment] 2023-07-05 14:09
I think we can close this, we place the icon where it makes sense depending on the situation, we don't have a "always to the right" rule.

**Closed by shawnborton** 2023-07-05 14:09 UTC
Labels: Daily, Bug
