### ISSUE TITLE
[HOLD for payment 2022-08-30] [$250] Web - Announce room - User time zone is displayed after page refresh

### ISSUE THREAD

**Issue by kavimuru** [Expensify/App#10109] opened 2022-07-26 15:47 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Go to staging.new.expensify.com and login with expensifail account
2. Go to workspace and search for #announce
3. No time zone is above the compose box
4. Add a member to the workspace and go back to the announce room

## Expected Result:
Don't see the time zone of any users in default rooms

## Actual Result:
Time zone of that other user appears after refreshing the page

## Workaround:
unknown

## Platform:

Where is this issue occurring?

- Web
- iOS
- Android
- Desktop App
- Mobile Web

**Version Number:** 1.1.86-1
**Reproducible in staging?:**  y
**Reproducible in production?:** y
**Email or phone of affected tester (no customers):** applausetester+0725mn@applause.expensifail.com / Utest123 or Any expensifail account
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** 

https://user-images.githubusercontent.com/43996225/181051232-453cb042-de5d-4ffa-bde3-c25419358aac.mp4

**Expensify/Expensify Issue URL:** 
**Issue reported by:** Applause internal team
**Slack conversation:** 

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by puneetlath** [comment] 2022-07-26 17:29
Hm, I would expect that in the announce room (or any room for that matter), you would never see timezone info for another user above the chat box. I'm going to change the expected result accordingly.

**Comment by puneetlath** [comment] 2022-07-26 17:32
Internal upwork job: https://www.upwork.com/ab/applicants/1551983550045458432/job-details
External upwork job: https://www.upwork.com/jobs/~0107cf3501d9c01c60

**Comment by Santhosh-Sellavel** [comment] 2022-07-26 17:38
## Proposal
In this method add a check ! `isChatRoom(report)` would be enough.

https://github.com/Expensify/App/blob/92186e50db3d37064a07d0a5c9ddcf81df39d3ad/src/libs/ReportUtils.js#L319-L329

**Comment by Santhosh-Sellavel** [comment] 2022-08-02 19:53
@puneetlath Bump!

**Comment by puneetlath** [comment] 2022-08-05 14:50
@Santhosh-Sellavel yep, that seems like it would work. Let's do it.

**Comment by puneetlath** [comment] 2022-08-05 14:51
@Santhosh-Sellavel please apply to the upwork job as well.

**Comment by Santhosh-Sellavel** [comment] 2022-08-08 18:25
Sure will send a PR in a couple of days @puneetlath

**Comment by mananjadhav** [comment] 2022-08-10 17:34
I don't think we need C+ review on this as @Santhosh-Sellavel is a part of C+ team working on the PR.

**Comment by puneetlath** [comment] 2022-08-10 20:12
@mananjadhav @Santhosh-Sellavel as discussed [here](https://expensify.slack.com/archives/C02NK2DQWUX/p1660151841502539), let's go ahead and do the C+ review going forward, even if the PR submitter is a C+ themselves.

**Comment by Santhosh-Sellavel** [comment] 2022-08-22 08:47
PR is merged and waiting for deployment!

**Comment by mvtglobally** [comment] 2022-08-23 04:21
Issue not reproducible during KI retests. (First week)

**Comment by mananjadhav** [comment] 2022-08-23 04:29
@mvtglobally quick question for my knowledge. These KI Tests are performed on staging or some other environment?

**Comment by mvtglobally** [comment] 2022-08-23 04:51
Yes, we are running on Staging only once a week check.

**Comment by mananjadhav** [comment] 2022-08-23 04:53
The reason I asked is because two issues mention not reproducible during KI retests and both of them are not merged yet. So I am wondering 🤔 how come they got resolved automagically

**Comment by puneetlath** [comment] 2022-08-30 11:12
@mananjadhav @Santhosh-Sellavel sent you both hiring offers for the job through Upwork. Please accept when you have a chance so we can pay this out. Thanks!

**Comment by mvtglobally** [comment] 2022-08-30 15:22
Issue not reproducible during KI retests. (Second week)

**Comment by Santhosh-Sellavel** [comment] 2022-08-30 23:24
Done @puneetlath

**Comment by puneetlath** [comment] 2022-08-31 03:35
Paid!

**Closed by puneetlath** 2022-08-31 03:35 UTC
Labels: Exported, External, Engineering, Daily, Awaiting Payment
