### ISSUE TITLE
[$250] Bank account - Extra bottom margin below green button in Personal info page

### ISSUE THREAD

**Issue by izarutskaya** [Expensify/App#40770] opened 2024-04-23 10:55 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.64-0
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Issue reported by:** Applause-Internal team

## Action Performed:
1. Go to staging.new.expensify.com
2. Go to Account settings > Workspaces > any workspace.
3. Go to Workflows > Connect bank account.
4. Select Connect manually.
5. Check the bottom margin of green buttons between Bank info and Personal info page.

## Expected Result:
The bottom margin of green buttons between Bank info and Personal info page should be consistent.

## Actual Result:
There is extra bottom margin below green button in Personal info page.

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [x] Android: mWeb Chrome
- [x] iOS: Native
- [x] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

https://github.com/Expensify/App/assets/115492554/f67c1c29-9bc4-42f1-b152-04ea8a5b261d

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~0158b8cfab7164d0a3</li>
        <li>Upwork Job ID: 1785049311364366336</li>
        <li>Last Price Increase: 2024-05-28</li>
    </ul>
</details>

**Comment by izarutskaya** [comment] 2024-04-23 10:55
We think this issue might be related to the #vip-vsb.

**Comment by abzokhattab** [comment] 2024-04-23 11:26
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
inconsistency between the margin of the bank setup step and other steps  
### What is the root cause of that problem?
 
in the `BankInfo` step we dont set the `submitButtonStyles` like we do in all other steps
`

### What changes do you think we should make in order to solve the problem?

to preserve the consistency we need to add `submitButtonStyles` [here](https://github.com/Expensify/App/blob/861e7640d89500a2b5c6b5b95bfe9076175684a7/src/pages/ReimbursementAccount/BankInfo/substeps/Manual.tsx#L66) and [here](https://github.com/Expensify/App/blob/a3c3116d462f28518fbf0fd5f045be27f797039f/src/pages/ReimbursementAccount/BankInfo/substeps/Plaid.tsx#L74)

```js
            submitButtonStyles={[styles.mb0, styles.pb5]}
```

**Comment by abdulrahuman5196** [comment] 2024-05-01 15:25
@lukemorawski I assume this is being fixed somewhere?

**Comment by lukemorawski** [comment] 2024-05-06 08:53
@abdulrahuman5196 Hi. I'm not on Expensify team anymore. Not sure if it's going to be fixed in other PRs. This might have to be tackled separately. I will forward this to the rest of the team.

**Comment by abdulrahuman5196** [comment] 2024-05-07 12:11
> @abdulrahuman5196 Hi. I'm not on Expensify team anymore. Not sure if it's going to be fixed in other PRs. This might have to be tackled separately. I will forward this to the rest of the team.

Got it. Will review this separately

**Comment by abdulrahuman5196** [comment] 2024-05-10 14:43
@MrMuzyk Will this issue fix with this PR https://github.com/Expensify/App/pull/40912#issuecomment-2097814542

**Comment by abdulrahuman5196** [comment] 2024-05-15 10:04
> @MrMuzyk Will this issue fix with this PR [#40912 (comment)](https://github.com/Expensify/App/pull/40912#issuecomment-2097814542)

@MrMuzyk Gentle ping on this?

**Comment by abdulrahuman5196** [comment] 2024-05-22 20:00
> @abdulrahuman5196 Hi, sorry for such a late response. My PR didn't fix this as I wasn't aware that this place is broken as well. Do you want me to take care of that? I can see that we already have some proposals that seem to fix the issue.

Its fine, We can work in this issue separately

**Comment by slafortune** [comment] 2024-05-23 22:13
@abdulrahuman5196 are you saying that you've incorporated this issue in another fix?  If so, let's close this.

**Comment by slafortune** [comment] 2024-05-23 22:14
On vacation until June 4th so adding another BZ in the meantime.

**Comment by stephanieelliott** [comment] 2024-05-29 07:28
I'm not sure whether this has been fixed specifically or not, but seeing as it is a minor display inconsistency I am going to close this. It took me a few watches of the video to see it so I think the general end user probably will not notice it

**Closed by stephanieelliott** 2024-05-29 07:28 UTC
Labels: External, Daily, Help Wanted, Overdue, Bug
