### ISSUE TITLE
[$500] LHN - App crashes when money request is received on owned workspace

### ISSUE THREAD

**Issue by izarutskaya** [Expensify/App#31814] opened 2023-11-24 10:46 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.3-2
**Reproducible in staging?:** Y
**Reproducible in production?:** N
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** Applause-Internal Team
**Slack conversation:** @

## Action Performed:
Pre-requisite: user must be logged in, have created a workspace and invited user B to it.

1. As user A, go to LHN and wait there.
2. As user B, request money to the workspace owned by user A.
3. Verify user A.

## Expected Result:
There should be no errors on the user A side after receiving a money request on the workspace.

## Actual Result:
The app crashes when money request is received on the workspace.

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [x] Android: mWeb Chrome
- [ ] iOS: Native
- [x] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

https://github.com/Expensify/App/assets/115492554/7aebc481-5f9c-4430-9c50-5f473dfceb4d

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~0101b533aef941ae82</li>
        <li>Upwork Job ID: 1728002242984968192</li>
        <li>Last Price Increase: 2023-11-24</li>
    </ul>
</details>

**Comment by paultsimura** [comment] 2023-11-24 10:52
Regression from https://github.com/Expensify/App/pull/31061
https://github.com/Expensify/App/issues/30042#issuecomment-1792625104

**Comment by koko57** [comment] 2023-11-24 11:26
same root cause as in https://github.com/Expensify/App/issues/31803. The issue is being worked on

**Comment by danieldoglas** [comment] 2023-11-24 12:52
K, since it's a dupe (same root cause, at least) I'll remove deploy blocker on this one

**Comment by luacmartins** [comment] 2023-11-24 19:23
Closing since this is a dupe.

**Closed by luacmartins** 2023-11-24 19:23 UTC
Labels: Engineering, Daily, Bug
