### ISSUE TITLE
[$1000] Task has not been created but a new report has been created

### ISSUE THREAD

**Issue by kavimuru** [Expensify/App#20438] opened 2023-06-08 03:16 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Login account A and B on 2 device
2. With user A: Click button FAB => Assign task
3. Assign task for user B but not create task
4. Observe that the report is created at LHN in 2 accounts.
## Expected Result: 
Report chat generated after creating task
## Actual Result: 
Do not create tasks but still have reports generated on 2 accounts, confusing users.

## Workaround:
Can the user still use Expensify without this being fixed? Have you informed them of the workaround?

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [x] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 1.3.25-4
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/43996225/e4eea53d-ddec-49b1-8141-1108941e4d76

https://github.com/Expensify/App/assets/43996225/4d141e74-d743-456d-904e-c62d76225c69

**Expensify/Expensify Issue URL:**
**Issue reported by:** @namhihi237
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1685948374782249

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~0103c2f45c45e5d10b</li>
        <li>Upwork Job ID: 1666912726834180096</li>
        <li>Last Price Increase: 2023-06-15</li>
    </ul>
</details>

**Comment by abdulrahuman5196** [comment] 2023-06-12 18:52
@hungvu193 From the proposal here, I have an high level idea on what you are trying to do, but the proposal is lacking more information on changes required. Could you elaborate your proposal?

Information missing is,

1) When do you intend to use the `Report.openReport` if you don't call it at assignee selection? Does it change any existing usage?

One usage it will change is user-name won't be shown in the shareDestination if the assignee is doesn't have any chats with current user.
I assume you want to show the assignee details in this case, correct me if wrong
>we can use assignee when shareDestination is empty.

**Comment by abdulrahuman5196** [comment] 2023-06-14 14:54
@hungvu193 Any update on this? https://github.com/Expensify/App/issues/20438#issuecomment-1587892468

**Comment by abdulrahuman5196** [comment] 2023-06-14 14:58
@tienifr  I understood your reason for storing. But it won't be useful anyways is my concern.
For discussion,

>Why are we even currently creating the report when setting the assignee?

I think it is to show the name details on share somewhere section. (Correct me if wrong)

If just create optimistic report and store it in onyx, it still won't have the user name to use in share somewhere right? It will only have the assignee email/phone information. This is why I don't see any use of storing the optimistic report in onyx.

Let me know if i am missing something.

**Comment by abdulrahuman5196** [comment] 2023-06-14 15:30
@tienifr I understood the solution you are mentioning before itself. 

The reason the report is currently created on first place is to show the proper `displayDetails` on the share somewhere section. Like if the assignee didn't have any previous conversation with the current user we won't have the user's displayname.
https://github.com/Expensify/App/blob/78aa3bab34b305f9f3aa818ce501c6f133881200/src/libs/actions/Task.js#L447

But if we just store and pass optimistic report here as per suggestion, we won't get proper `displayDetails`, for example if my profile name is 'Abdul Profile' you won't get this information since it is just a optimistic report. 

https://github.com/Expensify/App/blob/78aa3bab34b305f9f3aa818ce501c6f133881200/src/pages/tasks/NewTaskPage.js#L97-L101




That's why regardless of the storage, if we don't call openReport we won't proper displayDetails. So I am currently more inclined towards @hungvu193  solution here where we can just show assignee details if there is no previous chat with user.

**Comment by abdulrahuman5196** [comment] 2023-06-15 18:02
@NicMendonca  are we fine with showing assignee details in the shareDestination in case of a previous user chat being unavailable? I think its fine, but wanted to confirm on the expected behaviour. If its fine, we can go with @hungvu193's proposal.
Kindly check and let us know on the expectation.

**Comment by abdulrahuman5196** [comment] 2023-06-18 16:49
@wildan-m  Thank you for the proposal. Kindly avoid posting large code diffs as per the guidelines. 
And the proposal is almost similar to existing proposal here https://github.com/Expensify/App/issues/20438#issuecomment-1581873961 where the contributor wants to show the assignee details in-case of report not applicable.

**Comment by abdulrahuman5196** [comment] 2023-06-18 16:58
Created a slack thread here @NicMendonca 
https://expensify.slack.com/archives/C01GTK53T8Q/p1687107429773479

**Comment by NicMendonca** [comment] 2023-06-20 21:54
@abdulrahuman5196 thank you for starting that convo!

The consensus in the thread was to `do nothing` so am going to close this

**Closed by NicMendonca** 2023-06-20 21:54 UTC
Labels: External, Daily, Help Wanted, Overdue, Bug
