### ISSUE TITLE
[$250] When pressing `Enter` in the amount page in submit expense flow the focus is on `back` button instead of on `Submit` button

### ISSUE THREAD

**Issue by m-natarajan** [Expensify/App#44956] opened 2024-07-08 13:09 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** v9.0.5-3
**Reproducible in staging?:** y 
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** @mountiny 
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1720438943674149

## Action Performed:

1. Go to Workspace chat
2. Start Submit Expense flow
3. Add amount
4. Press Enter
5. Notice that the confirmation page has the back button focused
6. Click Merchant + write some
7. Press Enter to confirm the Merchant
8. Again on the confirmation page, the back button is focused
9. Click enter
10. You are back on the Amount page

## Expected Result:
On the confirmation page, the Submit button should be highlighted/ focused
## Actual Result:
On the confirmation page, the  back button is highlighted/focused
## Workaround:
unknown
## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

https://github.com/Expensify/App/assets/38435837/9bda811d-41fe-4083-9b38-d3cac9b067f0

https://github.com/Expensify/App/assets/38435837/4ba444c7-0d20-432c-90da-1ddbf2befef2

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01637c01d053be30ae</li>
        <li>Upwork Job ID: 1810300384848703191</li>
        <li>Last Price Increase: 2024-07-08</li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @alitoshmatov</details>

**Comment by nkdengineer** [comment] 2024-07-08 13:29
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
On the confirmation page, the back button is highlighted/focused

### What is the root cause of that problem?
There was no previous logic to focus on the Submit button by default when entering a screen

### What changes do you think we should make in order to solve the problem?

In the `Button` component, add a prop `shouldFocusOnEnteringScreen`.

Add a `useFocusEffect` in `Button`, if `shouldFocusOnEnteringScreen` is `true`, trigger focus on the button by its inner ref.

When we use the Submit button in submit expense flow, pass `shouldFocusOnEnteringScreen={true}`. We can do this for other cases of Submit button too

### What alternative solutions did you explore? (Optional)

**Comment by bernhardoj** [comment] 2024-07-08 14:11
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
The back button is highlighted when going to the confirmation page using the keyboard.

### What is the root cause of that problem?
We have a focus trap and it will focus on the first focusable element, which is the back button.

### What changes do you think we should make in order to solve the problem?

We can make use of the focus trap initial focus. If we want to focus the submit button, here is the step:
1. Assign an ID to the button (we need to pass down the ID props down to the Button component)
https://github.com/Expensify/App/blob/e0ccba51a40d67283b658aeffa3040fb2eb45795/src/components/MoneyRequestConfirmationList.tsx#L737-L768

2. Pass `initialFocus` prop to ScreenWrapper which will be passed down further to `FocusTrapForScreens`
https://github.com/Expensify/App/blob/e0ccba51a40d67283b658aeffa3040fb2eb45795/src/components/ScreenWrapper.tsx#L244-L245
`<FocusTrapForScreens initialFocus={initialFocus}>`

3. Returns the `initalFocus` prop instead of undefined.
https://github.com/Expensify/App/blob/e0ccba51a40d67283b658aeffa3040fb2eb45795/src/components/FocusTrap/FocusTrapForScreen/index.web.tsx#L55-L60
`return initialFocus`

4. Pass the ID of the button as the selector to the confirmation page ScreenWrapper.
https://github.com/Expensify/App/blob/e0ccba51a40d67283b658aeffa3040fb2eb45795/src/pages/iou/request/step/IOURequestStepConfirmation.tsx#L543-L548
`initialFocus="#confirm"`

However, this won't work yet because the focus trap can't find the element with the assigned ID because `MoneyRequestConfirmationList` is wrapped with `withOnyx` and the render is delayed. We can take this chance to migrate the `withOnyx` to `useOnyx` of the `MoneyRequestConfirmationList`.

**Comment by mountiny** [comment] 2024-07-08 19:46
@alitoshmatov can you please review the proposals?

**Comment by s77rt** [comment] 2024-07-08 23:07
We can close this as dupe of https://github.com/Expensify/App/issues/43662

**Comment by mountiny** [comment] 2024-07-09 19:34
Thanks

**Closed by mountiny** 2024-07-09 19:34 UTC
Labels: Reviewing, External, Daily, Bug
