### ISSUE TITLE
[PAID] [$100] Expensify Card - "issued" starts with a lowercase i on shipping address message

### ISSUE THREAD

**Issue by izarutskaya** [Expensify/App#51386] opened 2024-10-24 07:45 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 9.0.53-0
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**If this was caught on HybridApp, is this reproducible on New Expensify Standalone?:**
**Found when validation PR** https://github.com/Expensify/App/pull/50660
**Email or phone of affected tester (no customers):** nathanmulugetatesting+1941@gmail.com
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Issue reported by:** Applause-Internal team

## Action Performed:
Pre-conditions: Bank account is connected and Expensify card is enabled on a collect workspace, a member is added.
1. Issue a physical card to a member
2. Sign in with the member's account
3. Go to the workspace chat

## Expected Result:
The shipping address message starts the word "issued" with an uppercase "I"

## Actual Result:
The shipping address message starts the word issued with a lowercase "i"

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Standalone
- [ ] Android: HybridApp
- [ ] Android: mWeb Chrome
- [ ] iOS: Standalone
- [ ] iOS: HybridApp
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

![Bug6643794_1729721351892!image](https://github.com/user-attachments/assets/7454877e-584b-478a-ac29-aa7b3e3bceca)

  
</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~021851735794863120022</li>
        <li>Upwork Job ID: 1851735794863120022</li>
        <li>Last Price Increase: 2024-10-30</li>
<li>Automatic offers: </li>
<ul>
<li>rojiphil | Reviewer | 104720935</li>
<li>nyomanjyotisa | Contributor | 104720937</li>
</ul></li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @strepanier03</details>

**Comment by izarutskaya** [comment] 2024-10-24 07:46
We think this issue might be related to the #collect project.

**Comment by strepanier03** [comment] 2024-10-28 23:24
I think this might be more suited for #quality, trying to figure out a way to test this now.

**Comment by D-01576** [comment] 2024-10-31 08:09
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
Expensify Card - "issued" starts with a lowercase i on shipping address message

### What is the root cause of that problem?
The lowercase "issued" originates from the translation file's text, which was mistakenly set with a lowercase letter at the start.

#### Relevant File and Lines
The translation entries are in [`App/src/languages/en.ts`](https://github.com/Expensify/App/blob/45cabbf/src/languages/en.ts)

```typescript
issuedCard: ({assignee}: AssigneeParams) => `issued ${assignee} an Expensify Card! The card will arrive in 2-3 business days.`,
issuedCardNoShippingDetails: ({assignee}: AssigneeParams) => `issued ${assignee} an Expensify Card! The card will be shipped once shipping details are added.`,
issuedCardVirtual: ({assignee, link}: IssueVirtualCardParams) => `issued ${assignee} a virtual ${link}! The card can be used right away.
```

### What changes do you think we should make in order to solve the problem?

To correct this, change "issued" to "Issued" in each of the relevant entries. This update should be made in both the English (en.ts) and TypeScript (ts) translation files.

### What alternative solutions did you explore? (Optional)

Alternatively, we could apply the existing startCase function to capitalize the first letter automatically. This could be done by using ${startCase("issued")} or applying startCase directly to the field where input is generated. This approach would allow for consistent capitalization without requiring manual adjustments for each translation entry.

```typescript
issuedCard: ({assignee}: AssigneeParams) => `${startCase("issued")} ${assignee} an Expensify Card! The card will arrive in 2-3 business days.`,
issuedCardNoShippingDetails: ({assignee}: AssigneeParams) => `${startCase("issued")} ${assignee} an Expensify Card! The card will be shipped once shipping details are added.`,
issuedCardVirtual: ({assignee, link}: IssueVirtualCardParams) => `${startCase("issued")} ${assignee} a virtual ${link}! The card can be used right away.
```

**Comment by rojiphil** [comment] 2024-11-01 16:35
@nyomanjyotisa [proposal](https://github.com/Expensify/App/issues/51386#issuecomment-2434566100) LGTM as that was the first one to identify the root cause and the texts in translation file that needs to be fixed. Initially, the proposal did miss mentioning the change in es translation file but that could have been easily found out during PR. 
🎀👀🎀 C+ reviewed

**Comment by robertjchen** [comment] 2024-11-03 17:33
👍 to @nyomanjyotisa 's solution. 

`startCase` is definitely cool, but somewhat overkill for this situation 😅

**Comment by D-01576** [comment] 2024-11-04 08:37
> [robertjchen](/robertjchen)

Thanks for reviewing my proposal; I will definitely try to be part of the Expensify as a contributor.

**Comment by rojiphil** [comment] 2024-11-05 18:04
> Sorry, even if it doesn't match the English version _exactly_, for the Spanish copy I would remove `¡` and `!`.
> 
> But just to be sure, can you confirm how all the copies (English/Spanish) would look and I can do one final review? Thanks!

@jamesdeanexpensify Here are the screenshots based on the latest main. What do you think?

![Screenshot 2024-11-05 at 11 31 49 PM](https://github.com/user-attachments/assets/7a2f08e7-df35-41d3-8051-3e703cfea710)

![Screenshot 2024-11-05 at 11 31 30 PM](https://github.com/user-attachments/assets/8974a933-06c5-46ef-8df6-3cc1d2bf7ce7)

**Comment by jamesdeanexpensify** [comment] 2024-11-05 18:12
For the Spanish copy, I would remove the exclamation marks and just end that first sentence with a period instead.

**Comment by rojiphil** [comment] 2024-11-05 18:19
> For the Spanish copy, I would remove the exclamation marks and just end that first sentence with a period instead.

Sure then. Let’s do this here cc @nyomanjyotisa  @robertjchen

**Comment by strepanier03** [comment] 2024-11-18 19:29
@rojiphil - I will check back later today for the checklist and pay out the contract once I have that and the reg test (if needed) submitted. 

@nyomanjyotisa - I've paid and closed your contract in Upwork, thanks!

**Comment by rojiphil** [comment] 2024-11-20 06:01
# BugZero Checklist:

- [x] **[Contributor]** Classify the bug:

<details>
<summary>Bug classification</summary>


Source of bug:
  - [x] 1a. Result of the original design (eg. a case wasn't considered)
  - [ ] 1b. Mistake during implementation
  - [ ] 1c. Backend bug
  - [ ] 1z. Other:

Where bug was reported:
  - [x] 2a. Reported on production
  - [ ] 2b. Reported on staging (deploy blocker)
  - [ ] 2c. Reported on a PR
  - [ ] 2z. Other:

Who reported the bug:
  - [ ] 3a. Expensify user
  - [x] 3b. Expensify employee
  - [ ] 3c. Contributor
  - [ ] 3d. QA
  - [ ] 3z. Other:

</details>

- [x] **[Contributor]** The offending PR has been commented on, pointing out the bug it caused and why, so the author and reviewers can learn from the mistake.

    [Link to comment](https://github.com/Expensify/App/pull/46281/files#r1849584373): 

- [x] **[Contributor]** If the regression was CRITICAL (e.g. interrupts a core flow) A discussion in [#expensify-open-source](https://app.slack.com/client/E047TPA624F/C01GTK53T8Q) has been started about whether any other steps should be taken (e.g. updating the PR review checklist) in order to catch this type of bug sooner.

    Link to discussion: Not Required. The existing checklist is good enough to capture such issues.

- [x] **[Contributor]** If it was decided to create a regression test for the bug, please propose the [regression test](https://github.com/Expensify/App/blob/main/contributingGuides/REGRESSION_TEST_BEST_PRACTICES.md) steps using the template below to ensure the same bug will not reach production again.

## Regression Test Proposal
### Precondition:
Set the language to Spanish

Steps:

1. Issue a physical card to a member
2. Sign in with the member's account
3. Go to the workspace chat
4. Verify that the exclamation marks in the first sentence have been replaced with a period

Do we agree 👍 or 👎

**Comment by rojiphil** [comment] 2024-11-20 06:05
> I will check back later today for the checklist and pay out the contract once I have that and the reg test (if needed) submitted.

@strepanier03 BZ checklist is completed. Also, I have accepted the offer. Thanks.

**Comment by strepanier03** [comment] 2024-11-21 01:53
Great, thanks @rojiphil - finishing up now.

**Comment by strepanier03** [comment] 2024-11-21 02:03
Okay, made the reg test, paid the contract and closed it. Closing this out. Thanks all!

**Closed by strepanier03** 2024-11-21 02:03 UTC
Labels: External, Daily, Awaiting Payment, Bug
