### ISSUE TITLE
[$500] mweb - Send money - Keypad is opened if you minimize the browser while text is highlighted on "Send Money" screen @evoloshchak

### ISSUE THREAD

**Issue by kavimuru** [Expensify/App#9254] opened 2022-05-31 13:13 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Navigate to "Send Money" screen
2. Enter a couple of digits
3. Select (highlight) digits in the input
4. Minimize the browser
5. Launch the browser

## Expected Result:
Nothing should happen, page stays the same

## Actual Result:
Keyboard is opened and the UI is mangled up

## Workaround:
Unknown
## Platform:

Where is this issue occurring?

- Mobile Web

**Version Number:** 1.1.69-1
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**Email or phone of affected tester (no customers):** 
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** 

https://user-images.githubusercontent.com/43996225/171181471-b8e5632a-49d9-4287-81e3-d13a525dc48b.mp4

**Expensify/Expensify Issue URL:** 
**Issue reported by:** @evoloshchak
**Slack conversation:** 

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by laurenreidexpensify** [comment] 2022-06-07 08:28
https://www.upwork.com/ab/applicants/1534089388255346688/job-details

**Comment by laurenreidexpensify** [comment] 2022-06-08 10:10
Hi @allroundexperts thanks for the proposal.

As a reminder, new contributors are limited to working on one job at a time, however experienced contributors may work on numerous jobs simultaneously.

It looks like you're already working on quite a few other jobs, so we're going to pass on your proposal on this one, but looking forward to seeing future proposals once you've had some solutions hit production! Thanks

**Comment by rushatgabhane** [comment] 2022-06-08 10:19
> If we don't want to block the keyboard on desktop, we can add this to mobile web only as well.

Besides, there isn't really a way to do this.

**Comment by allroundexperts** [comment] 2022-06-08 10:23
@laurenreidexpensify These are really a single line changes. Out of the 5 issues currently assigned to me, I have created 4 PRs already. I don't understand how this could be a problem.

**Comment by laurenreidexpensify** [comment] 2022-06-08 12:05
👋🏽 @allroundexperts for new contributors we consider the first few jobs as an internal QA check, and once we're confident the issues have hit prod with no regressions introduced then you'll be all good to pick up multiple jobs. This is just a one time thing, it just helps us all feel confident that the issues will be picked up efficiently from both parties. We're excited you're on board and picking up so many issues - excited to get you onto the other side and handling more issues when we've finished this initial onboarding period. Thanks!

**Comment by rushatgabhane** [comment] 2022-06-16 17:18
Waiting on proposals

**Comment by allroundexperts** [comment] 2022-06-17 21:46
@rushatgabhane Several of my issues are closed now. Please review my proposal!

**Comment by rushatgabhane** [comment] 2022-06-17 21:48
> Reviewed here https://github.com/Expensify/App/issues/9254#issuecomment-1149733504

@allroundexperts how will differentiate between web and mWeb?

**Comment by allroundexperts** [comment] 2022-06-17 21:54
@rushatgabhane By using user agent, we can easily distinguish web from mWeb.

**Comment by rushatgabhane** [comment] 2022-06-17 22:08
@allroundexperts with my very limited experience, i don't think that's very reliable. But I'm happy to be proven wrong.

> this.textInput.setNativeProps({disabled: true});

Also, won't this disable external keyboards?

**Comment by allroundexperts** [comment] 2022-06-17 22:09
@rushatgabhane It will. Isn't that what we need here?

**Comment by rushatgabhane** [comment] 2022-06-17 22:12
oh you must have misread, we wanna disable the virtual keyboard and not external keyboard.
By external keyboard I mean those Hardware keyboards connected via bluetooth to tablets/mobiles

**Comment by allroundexperts** [comment] 2022-06-17 22:14
If we need to allow external keyboard on mobile web, then I guess there's nothing we can do except to wait for Safari to improve its implementation of `inputMode`. As far as mobile web detection reliability is concerned, it's pretty reliable unless someone want's to explicitly meddle around with the user agent.

**Comment by rushatgabhane** [comment] 2022-06-20 13:39
@allroundexperts yeah, we should be mindful of external keyboards too especially since this issue itself is an edge case. Disabling external keyboards completely doesn't sound like the best idea. Please let me know if come up with an alternative approach

**Comment by Beamanator** [comment] 2022-06-20 17:37
Hmm so just catching up - currently it looks like we already only show the numberpad buttons on mobile & mobile web - using this logic: https://github.com/Expensify/App/blob/2ec4a1c775b318a19c391b9cc29372274e48d805/src/pages/iou/steps/IOUAmountPage.js#L229-L234

Would we be able to just disable the text input if `canUseTouchScreen` is true in that page?

**Comment by allroundexperts** [comment] 2022-06-20 17:46
@Beamanator For sure we can do that.

**Comment by allroundexperts** [comment] 2022-06-20 17:50
@rushatgabhane If that is fine, then I can update my proposal.

**Comment by Beamanator** [comment] 2022-06-20 23:48
Cool ya let's see if @rushatgabhane has any concerns with that approach 👍

**Comment by rushatgabhane** [comment] 2022-06-21 00:19
@Beamanator I don't think that's a good idea. External keyboards for iPads, and keyboard for a touchscreen laptop won't work

**Comment by Beamanator** [comment] 2022-06-21 03:47
Interesting so the case we're talking about now is if the user has an external keyboard connected but the UI is showing the number pad input with buttons right? In that case we would want the user to be able to use their keyboard to type numbers instead of only being able to touch the number pad?

What about this: don't render an input at all when showing the number pad, and react to key press (numbers only) when showing the number input

**Comment by rushatgabhane** [comment] 2022-06-21 18:46
> Interesting so the case we're talking about now is if the user has an external keyboard connected but the UI is showing the number pad input with buttons right? In that case we would want the user to be able to use their keyboard to type numbers instead of only being able to touch the number pad?

Exactly!

**Comment by rushatgabhane** [comment] 2022-06-21 18:53
> Another point: how annoying is this issue anyway? Can the keyboard be closed easily in the situation described in the OP? If so, maybe it's not worth trying to "fix" this

@Beamanator I'm in favor of closing this super edge case. You can easily close the keyboard by 
- tapping anywhere outside the text input on iOS
- back button to hide the keyboard on Android.

**Comment by eVoloshchak** [comment] 2022-06-21 20:10
**Proposal:**
We can just remove the selection when we detect that browser window isn't visible. 
We need to add the following to [IOUAmountPage.js](https://github.com/Expensify/App/blob/12e87447e0a1dcb5a8523e39865f559c6d6f3bb6/src/pages/iou/steps/IOUAmountPage.js#L71) `componentDidMount`
```javascript
  document.addEventListener('visibilitychange', () => {
      if (document.hidden) {
          this.textInput.blur();
      }
  });
```
Result:

https://user-images.githubusercontent.com/9059945/174888398-58a15e44-b24d-4c94-804f-4270cc477ee8.mp4

Additionally, if needed, we can save the selection when window is hidden and restore it when it gets visible again.

**Comment by Beamanator** [comment] 2022-06-22 16:25
@rushatgabhane do you mind considering the proposal ^ before we decide if we should close this?

**Comment by rushatgabhane** [comment] 2022-06-23 16:50
It'll be very annoying for the text input to be blurred when you come back from a different tab on _WEB_. So we could add this listener on mWeb only using `isSmallScreenWidth`.

Also, so `document` doesn't exist on native so we'll have to create seperate files.

**Comment by eVoloshchak** [comment] 2022-06-23 17:04
> It'll be very annoying for the text input to be blurred when you come back from a different tab on _WEB_. So we could add this listener on mWeb only using `isSmallScreenWidth`.

Sure thing

> Also, so `document` doesn't exist on native so we'll have to create seperate files.

Ok, I'll create platform-specific files for the [TextInputWithCurrencySymbol.js](https://github.com/Expensify/App/blob/12e87447e0a1dcb5a8523e39865f559c6d6f3bb6/src/components/TextInputWithCurrencySymbol.js)

**Comment by rushatgabhane** [comment] 2022-06-23 17:17
@Beamanator the best possible solution is to fix it in chrome by adding a prop which makes the browser respect custom keyboards.

Anyway, this would be just a hack. I think this is a really minor edge case with an easy workaround.

**Comment by laurenreidexpensify** [comment] 2022-06-27 09:12
Not overdue, waiting for @Beamanator's response to ^^

**Comment by Beamanator** [comment] 2022-06-27 12:53
@rushatgabhane thanks for your thoughts, I think I agree, since the workaround is super easy and the fix seems kinda ugly I'd say this is not really worth fixing at this point 👍

**Closed by Beamanator** 2022-06-27 12:53 UTC
Labels: Exported, External, Engineering, Daily, Help Wanted
