### ISSUE TITLE
[HOLD for payment 2024-01-25] [HOLD for payment 2024-01-03] Expense - Expense preview with a manual and ongoing scan does not show "x request, y scanning"

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#33512] opened 2023-12-22 17:35 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.16-3
**Reproducible in staging?:** Y
**Reproducible in production?:** N
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** Applause - Internal Team
**Slack conversation:**

## Action Performed:
1. Create a new workspace
2. Go to workspace chat
3. Create a manual request
4. Create a scan request

## Expected Result:
The expense preview in the workspace chat will show "x request, y scanning

## Actual Result:
The expense preview in the workspace chat just shows "Receipt", as if the receipt in the Scan request is part of the manual expense

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [x] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details> 

https://github.com/Expensify/App/assets/78819774/35660251-40b9-40ff-911c-d31cfdd12889

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by rlinoz** [comment] 2023-12-22 18:00
This is a regression from https://github.com/Expensify/App/pull/32469

**Comment by rlinoz** [comment] 2023-12-22 18:28
Opened a PR to fix it

**Comment by mountiny** [comment] 2023-12-25 22:06
PR is up and merged, but I dont think this needs to be CPed its a minor change so demoting this to not a blocker

**Comment by mountiny** [comment] 2023-12-26 21:29
Per this comment https://github.com/Expensify/App/issues/33576#issuecomment-1869731222 this is still failing on some platforms cc @kbecciv do you have more details?

**Comment by kbecciv** [comment] 2023-12-26 21:36
It failed on mWeb, Desktop and IOS app

https://github.com/Expensify/App/assets/93399543/9d5a19fd-c0f0-4505-8f74-0a164d1132bf

**Comment by mountiny** [comment] 2023-12-27 11:42
So the numbers are not correct but the text pattern is fine I think.

**Comment by rlinoz** [comment] 2024-01-03 12:30
@vitHoracek you mean it should be 2 requests, 1 scanning?

**Comment by mountiny** [comment] 2024-01-04 15:06
I am not sure if this is inclusive or exclusive

**Comment by mountiny** [comment] 2024-01-04 15:08
Asked here https://expensify.slack.com/archives/C05DWUDHVK7/p1704380865973509

**Comment by rlinoz** [comment] 2024-01-05 19:58
We decided that the message shall be changed to `2 requests, 1 scanning` when there are 3 requests and one of them are scanning.

I will work on that next week.

**Comment by rlinoz** [comment] 2024-01-08 21:00
Working on a PR, should be up tomorrow.

**Comment by rlinoz** [comment] 2024-01-18 13:22
@allroundexperts is due payment for reviewing the PR

**Comment by twisterdotcom** [comment] 2024-01-18 17:54
This would be on Jan 25 right? The automation should send offers to you both. But I will handle it then if not.

**Comment by rlinoz** [comment] 2024-01-22 12:17
Moving to weekly since it is on hold for payment.

**Closed** 2024-01-25 12:21 UTC
Labels: Engineering, Weekly, Awaiting Payment, Bug

**Comment by JmillsExpensify** [comment] 2024-01-30 19:50
$500 payment approved for @allroundexperts based on comment above.
