### ISSUE TITLE
[$250] Android - Track expense-Creating distance track expense, categorizing&submit shows error

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#42546] opened 2024-05-23 17:36 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.75
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**If this was caught during regression testing, add the test name, ID and link from TestRail:** N/A
**Issue reported by:** Applause - Internal Team

## Action Performed:
1. Launch app
2. Tap on self DM
3. Tap plus icon -- track expense - distance
4. Complete the flow and track expense
5. From concierge message, select "categorize it"
6. Select a Workspace and category and submit expense
7. Open the expense and wait few seconds

## Expected Result:
In self DM, creating distance track expense, categorizing&submit expense must not show error message

## Actual Result:
In self DM, creating distance track expense, categorizing&submit expense shows error message " Unexpected error submitting the expense. Please try again later"

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [ ] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details> 

https://github.com/Expensify/App/assets/78819774/9e4cf582-16ff-45d5-846b-7d1ffc633cb1

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~010f17fef36f00fae6</li>
        <li>Upwork Job ID: 1796201034426667008</li>
        <li>Last Price Increase: 2024-06-13</li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @abdulrahuman5196</details>

**Comment by lanitochka17** [comment] 2024-05-23 17:37
@isabelastisser  FYI I haven't added the External label as I wasn't 100% sure about this issue. Please take a look and add the label if you agree it's a bug and can be handled by external contributors

**Comment by isabelastisser** [comment] 2024-05-29 16:35
Reviewing.

**Comment by isabelastisser** [comment] 2024-05-29 16:41
I couldn't reproduce this. @lanitochka17, are you still experiencing this behavior?

**Comment by lanitochka17** [comment] 2024-05-29 17:21
I am not able to reproduce this issue with build 1.4.77-0



https://github.com/Expensify/App/assets/78819774/57e65d4a-4d53-407b-95ee-490c9d3a3361

**Comment by lanitochka17** [comment] 2024-05-29 17:38
@isabelastisser The tester who found this bug was able to reproduce it again. Maybe it has something to do with the location.

https://github.com/Expensify/App/assets/78819774/8ba63d42-d312-43ef-a830-6cbd33862c89

**Comment by abdulrahuman5196** [comment] 2024-06-04 19:05
no proposals yet

**Comment by isabelastisser** [comment] 2024-06-06 18:52
Waiting for proposals.

**Comment by isabelastisser** [comment] 2024-06-13 00:26
@abdulrahuman5196, do you have any ideas on how to move this forward? :

**Comment by isabelastisser** [comment] 2024-06-14 16:42
Bump @abdulrahuman5196 for an update on my question above. Can you still reproduce it?

**Comment by isabelastisser** [comment] 2024-06-17 14:26
I'll try to reproduce this now.

**Comment by isabelastisser** [comment] 2024-06-17 14:34
I cannot reproduce this either, based on [this comment](https://github.com/Expensify/App/issues/42546#issuecomment-2137939609), this might be a local issue. Closing!

**Closed by isabelastisser** 2024-06-17 14:34 UTC
Labels: External, Daily, Help Wanted, Overdue, Bug
