### ISSUE TITLE
Web - User can not join the room again if room visibility set to restricted

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#21907] opened 2023-06-29 21:22 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Go to the Workspaces > New workspace
2. Invite a user in it
3. Go back to the chat history
4. Go to the “New room” section
5. Enter room name and select a workspace you have created
6. Select visibility to “Restricted”
7. Click on “Create room”
8. Go to the room detail
9. Share code > Copy URL to clipboard
10. Go back to "Details"  Click on “Leave room” 
11. Open new tab and paste the copied URL

## Expected Result:
If a room's visibility is set to "public," user have the ability to join the room again after leaving. However, if the visibility is set to "Restricted," even if a user is the admin of the workspace, he cannot join the room

## Actual Result:
If the room visibility is set to "Restricted," and user is the workspace admin, will not be able to join the room again. Instead, he will see a message saying, "Hmm... it's not here,"

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [x] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 1.3.34-1
**Reproducible in staging?:** y 
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/93399543/0af89b03-1528-431b-9c08-b4f70b442b24

https://github.com/Expensify/App/assets/93399543/9a07f301-1bac-452e-bbc9-3d89dba14d33

**Expensify/Expensify Issue URL:**
**Issue reported by:** @ayazhussain79
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1687986369216439

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01b3d0be331fcef698</li>
        <li>Upwork Job ID: 1675901397811945472</li>
        <li>Last Price Increase: 2023-07-03</li>
    </ul>
</details>

**Comment by anmurali** [comment] 2023-07-03 16:16
A member of a workspace associated with a room should be able to reenter with the QR code after leaving.

**Comment by anmurali** [comment] 2023-07-06 01:47
I am not sure what BE is - asked in the Slack thread

**Comment by bondydaa** [comment] 2023-07-12 20:20
sorry haven't had a chance to dig in here yet

**Comment by bondydaa** [comment] 2023-07-12 20:23
@ayazhussain79 can you let me know the email(s) you were using to test this? I want to take a look at logs to see if there's any errors being thrown or see if those will point me in the right direction.

also cc @jasperhuangg I know you've worked a lot with the visibility stuff so just wondering if maybe you have any insights here.

**Comment by bondydaa** [comment] 2023-07-12 20:27
also dropping this to weekly, I don't think it needs daily updates.

**Comment by ayazhussain79** [comment] 2023-07-12 21:01
@bondydaa I have reproduced it again using the email address "hussainayaz79@gmail.com" and you can also check console log at the end 


https://github.com/Expensify/App/assets/56740856/c75c4511-0c4f-401e-ab37-930399671b02

**Comment by jasperhuangg** [comment] 2023-07-13 23:34
Not a bug! This is expected behavior that we're going to be fixing internally as part of the User Created Rooms Release doc (out soon!). Closing

**Closed by jasperhuangg** 2023-07-13 23:34 UTC
Labels: Engineering, Daily, Internal, Bug

**Comment by NikkiWines** [comment] 2023-09-25 06:48
@jasperhuangg is this still considered not a bug / expected behavior? Experienced this during offshore and @danieldoglas had to run a CQ to get me back into a restricted room even as a policy member

**Comment by NikkiWines** [comment] 2023-09-29 01:32
@jasperhuangg friendly bump here
