### ISSUE TITLE
[$2000] Copy paste simple text from microsoft word detects the text as image 

### ISSUE THREAD

**Issue by kavimuru** [Expensify/App#14232] opened 2023-01-12 01:08 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:

1. Open the app
2. Open any report
3. Open Microsoft Word and write anything in it
4. Copy and paste it in report chat and send

## Expected Result:
It should consider it as simple text

## Actual Result:
On mac chrome it considers the text as image

## Workaround:
unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?

- [ ] MacOS / Chrome

**Version Number:** v1.2.52-4
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** 

https://user-images.githubusercontent.com/43996225/211951688-f059a5bf-2a7c-41da-95a1-e14de7fa7a82.mov

https://user-images.githubusercontent.com/43996225/211951804-f9656f1a-322f-447f-ad3a-39bc6679ce62.mp4

**Expensify/Expensify Issue URL:**
**Issue reported by:** Dhanashree-Sawant
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1673453015471619

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~015a89f9e17a87633b</li>
        <li>Upwork Job ID: 1617627375450935296</li>
        <li>Last Price Increase: 2023-01-30</li>
    </ul>
</details>

**Comment by davidcardoza** [comment] 2023-01-23 20:56
I am able to reproduce
![2023-01-23_13-55-17 (1)](https://user-images.githubusercontent.com/6643649/214148126-f603cd96-c612-41d4-81c2-03aa3dd10787.gif)

**Comment by allroundexperts** [comment] 2023-01-23 23:45
## Proposal

### Issue
Whenever we copy anything from MS word, MS word sends multiple formats of the selection to the clipboard. These formats include:
1. Plain text
2. HTML
3. RTF
4. File (An png of the selection)

Ref:
<img width="310" alt="Screenshot 2023-01-24 at 4 36 12 AM" src="https://user-images.githubusercontent.com/30054992/214176937-bd464c8a-4c29-47d6-928a-bbe4648f3b5f.png">

In our code, we're checking for files in Clipboard at the very beginning. If Clipboard contains a file, all other types present in the Clipboard object are ignored as seen in the following:
https://github.com/Expensify/App/blob/ae66a7f019dda888390173a542b273d97042eaaa/src/components/Composer/index.js#L217

### Solution
There can be multiple solutions here.

1. We can modify our code such that Text/HTML takes greater precedence than a file if present.
```diff
diff --git a/src/components/Composer/index.js b/src/components/Composer/index.js
index 078376c15..4816141b7 100755
--- a/src/components/Composer/index.js
+++ b/src/components/Composer/index.js
@@ -210,13 +210,6 @@ class Composer extends React.Component {
         const {files, types} = event.clipboardData;
         const TEXT_HTML = 'text/html';
 
-        // If paste contains files, then trigger file management
-        if (files.length > 0) {
-            // Prevent the default so we do not post the file name into the text box
-            this.props.onPasteFile(event.clipboardData.files[0]);
-            return;
-        }
-
         // If paste contains HTML
         if (types.includes(TEXT_HTML)) {
             const pastedHTML = event.clipboardData.getData(TEXT_HTML);
@@ -265,6 +258,13 @@ class Composer extends React.Component {
             return;
         }
 
+        // If paste contains files, then trigger file management
+        if (files.length > 0) {
+            // Prevent the default so we do not post the file name into the text box
+            this.props.onPasteFile(event.clipboardData.files[0]);
+            return;
+        }
+
         const plainText = event.clipboardData.getData('text/plain');
         this.paste(Str.htmlDecode(plainText));
     }
```
2. Give user a choice to paste as whatever type they desire IF clipboard contains multiple types.
3. We can also do nothing here as the image contains a valid representation of all the content in MS word (which includes all the styling and formatting).

**Comment by jasperhuangg** [comment] 2023-01-25 04:17
> For reference, Slack gives html/text greater precedence over files in Clipboard.

Hey @allroundexperts! Thanks for the succinct and clear proposal! Can you explain how you know Slack gives greater precedence to these types of files?

**Comment by allroundexperts** [comment] 2023-01-25 11:09
@jasperhuangg You can just do the same test on Slack. Copy anything from MS Word. Then try pasting it in Slack. You'll note that Slack just pastes the text as HTML unlike Expensify.

**Comment by allroundexperts** [comment] 2023-01-27 16:23
@jasperhuangg @0xmiroslav Any update on my proposal?

**Comment by situchan** [comment] 2023-01-27 19:10
### **Proposal**

```diff
    handlePaste(event) {
        event.preventDefault();

        const {files, types} = event.clipboardData;
        const TEXT_HTML = 'text/html';

-       // If paste contains files, then trigger file management
-       if (files.length > 0) {
-           // Prevent the default so we do not post the file name into the text box
-           this.props.onPasteFile(event.clipboardData.files[0]);
-           return;
-       }
-
        // If paste contains HTML
        if (types.includes(TEXT_HTML)) {
            const pastedHTML = event.clipboardData.getData(TEXT_HTML);

            const domparser = new DOMParser();
            const embeddedImages = domparser.parseFromString(pastedHTML, TEXT_HTML).images;

            // If HTML has img tag, then fetch images from it.
            if (embeddedImages.length > 0 && embeddedImages[0].src) {
+               // If paste contains image as a file, then trigger file management
+               if (files.length > 0) { // or we can update this condition to `files.length === 1`
+                   this.props.onPasteFile(event.clipboardData.files[0]);
+                   return;
+               }

                // If HTML has emoji, then treat this as plain text.
                if (embeddedImages[0].dataset && embeddedImages[0].dataset.stringifyType === 'emoji') {
                    const plainText = event.clipboardData.getData('text/plain');
                    this.paste(Str.htmlDecode(plainText));
                    return;
                }
                fetch(embeddedImages[0].src)
                    .then((response) => {
                        if (!response.ok) { throw Error(response.statusText); }
                        return response.blob();
                    })
                    .then((x) => {
                        const extension = IMAGE_EXTENSIONS[x.type];
                        if (!extension) {
                            throw new Error(this.props.translate('composer.noExtensionFoundForMimeType'));
                        }

                        return new File([x], `pasted_image.${extension}`, {});
                    })
                    .then(this.props.onPasteFile)
                    .catch(() => {
                        const errorDesc = this.props.translate('composer.problemGettingImageYouPasted');
                        Growl.error(errorDesc);

                        /*
                        * Since we intercepted the user-triggered paste event to check for attachments,
                        * we need to manually set the value and call the `onChangeText` handler.
                        * Synthetically-triggered paste events do not affect the document's contents.
                        * See https://developer.mozilla.org/en-US/docs/Web/API/Element/paste_event for more details.
                        */
                        this.handlePastedHTML(pastedHTML);
                    });
                return;
            }

            this.handlePastedHTML(pastedHTML);
            return;
        }

+       // If paste contains files, then trigger file management
+       if (files.length > 0) {
+           // Prevent the default so we do not post the file name into the text box
+           this.props.onPasteFile(event.clipboardData.files[0]);
+           return;
+       }
+
        const plainText = event.clipboardData.getData('text/plain').replace(/\n\n/g, '\n');

        this.paste(Str.htmlDecode(plainText));
    }
```

**Comment by allroundexperts** [comment] 2023-01-27 19:15
### Updated code:

```diff
diff --git a/src/components/Composer/index.js b/src/components/Composer/index.js
index 5e00825c5a..487210b16f 100755
--- a/src/components/Composer/index.js
+++ b/src/components/Composer/index.js
@@ -214,7 +214,7 @@ class Composer extends React.Component {
         const TEXT_HTML = 'text/html';
 
         // If paste contains files, then trigger file management
-        if (files.length > 0) {
+        if (files.length > 0 && !event.clipboardData.getData(TEXT_HTML)) {
             // Prevent the default so we do not post the file name into the text box
             this.props.onPasteFile(event.clipboardData.files[0]);
             return;

```

**Comment by allroundexperts** [comment] 2023-01-28 20:04
### Update Proposal

This one handles several more edge cases. (SVG and CORS blocked images).

```diff
diff --git a/src/components/Composer/index.js b/src/components/Composer/index.js
index 5e00825c5a..da282a7c85 100755
--- a/src/components/Composer/index.js
+++ b/src/components/Composer/index.js
@@ -213,8 +213,8 @@ class Composer extends React.Component {
         const {files, types} = event.clipboardData;
         const TEXT_HTML = 'text/html';
 
-        // If paste contains files, then trigger file management
-        if (files.length > 0) {
+        // If paste contains files and no HTML, then trigger file management
+        if (files.length > 0 && !types.includes(TEXT_HTML)) {
             // Prevent the default so we do not post the file name into the text box
             this.props.onPasteFile(event.clipboardData.files[0]);
             return;
@@ -223,9 +223,14 @@ class Composer extends React.Component {
         // If paste contains HTML
         if (types.includes(TEXT_HTML)) {
             const pastedHTML = event.clipboardData.getData(TEXT_HTML);
-
             const domparser = new DOMParser();
-            const embeddedImages = domparser.parseFromString(pastedHTML, TEXT_HTML).images;
+            const parsedHTML = domparser.parseFromString(pastedHTML, TEXT_HTML);
+            if (parsedHTML.body.childNodes.length === 1 && parsedHTML.body.childNodes[0] === 'img' && files.length > 0) {
+                this.props.onPasteFile(event.clipboardData.files[0]);
+                return;
+            }
+
+            const embeddedImages = parsedHTML.images;
 
             // If HTML has img tag, then fetch images from it.
             if (embeddedImages.length > 0 && embeddedImages[0].src) {
```

**Comment by allroundexperts** [comment] 2023-01-30 14:48
@0xmiroslav In the updated proposal (https://github.com/Expensify/App/issues/14232#issuecomment-1407475708), image data is not being fetched again. As far as the private image link is concerned, that is working as well after the update.

https://www.loom.com/share/0f924e13059844e5afac68cdcee4d5ba

**Comment by allroundexperts** [comment] 2023-01-30 15:03
@0xmiroslav Yes, is that an issue?

**Comment by allroundexperts** [comment] 2023-01-30 15:07
@0xmiroslav Sounds good. Sorry for that!

**Comment by jasperhuangg** [comment] 2023-01-31 17:54
Hey @allroundexperts thank you for engaging in so much discussion and getting to a proposal that satisfies our requirements. You've been assigned!

**Comment by allroundexperts** [comment] 2023-02-01 01:26
@jasperhuangg @0xmiroslav Created the PR:
https://github.com/Expensify/App/pull/14713

**Comment by allroundexperts** [comment] 2023-02-01 17:13
@0xmiroslav @jasperhuangg kind reminder for PR review.

**Comment by jasperhuangg** [comment] 2023-02-02 20:41
Closing per https://expensify.slack.com/archives/C01GTK53T8Q/p1675369192212829?thread_ts=1674760715.010859&cid=C01GTK53T8Q

**Closed by jasperhuangg** 2023-02-02 20:41 UTC
Labels: Reviewing, External, Daily, Bug

**Comment by allroundexperts** [comment] 2023-02-02 20:53
@jasperhuangg Will I get any compensation for this?

**Comment by jasperhuangg** [comment] 2023-02-02 21:23
@allroundexperts Yes! You definitely deserve to be compensated–we are currently talking about this internally and I'll get back to you once the discussion has concluded.

**Comment by jasperhuangg** [comment] 2023-02-02 23:58
Hey @davidcardoza!

Can you please ensure that @allroundexperts gets compensated fully for his investigation of this issue? Since no PRs were merged we'll compensate $2000 without any bonuses.

The C+ contributor @0xmiroslav should also get compensated fully for their help with this issue, again without any bonuses.

**Comment by davidcardoza** [comment] 2023-02-03 00:57
@jasperhuangg I am OOO for a family medical emergency (posted in #social earlier today). I may not be back in office until Monday. If the payment is urgent can you please reassign to someone on the bug zero team?

**Comment by jasperhuangg** [comment] 2023-02-03 01:05
Seems like payment isn't urgent, so no worries.

And I hope everything is okay, sending positive thoughts your way!

**Comment by Beamanator** [comment] 2023-02-03 07:54
@jasperhuangg sorry to randomly jump in here :D I thinkkk we normally keep App issues open until payment has been sent to everyone, right? 🤔

**Comment by dhanashree-sawant** [comment] 2023-02-03 08:10
@davidcardoza Hope everything is okay, sending positive thoughts. 

Whenever you are back to work can you let me know if I would be compensated for reporting bonus?

**Comment by allroundexperts** [comment] 2023-02-09 23:46
@davidcardoza Any update here?

**Comment by davidcardoza** [comment] 2023-02-10 06:21
@0xmiroslav Contract sent
@allroundexperts Contract sent

**Comment by dhanashree-sawant** [comment] 2023-02-10 10:29
Hi @davidcardoza, kindly let me know about my query too.

**Comment by davidcardoza** [comment] 2023-02-11 02:23
@dhanashree-sawant Contract sent

**Comment by dhanashree-sawant** [comment] 2023-02-11 02:25
Okay great thanks, accepted the offer

**Comment by davidcardoza** [comment] 2023-02-14 01:41
All payments have been sent.
