### ISSUE TITLE
[HOLD for payment 2022-12-20] [$250] Offline default avatar doesn't update after connecting to the internet reported by @thesahindia

### ISSUE THREAD

**Issue by kavimuru** [Expensify/App#12712] opened 2022-11-14 16:49 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:

1. Login to an account which has more than 20 chats
2. Disconnect the internet connection
3. Navigate to search page
4. Scroll and select a chat with offline default avatar
5. Enable the internet connection

## Expected Result: 
The avatar should update and you should see the default colour avatar or custom image if the profile has one

## Actual Result: 
It doesn't update, you have to refresh the page

## Workaround:
unknown

## Platform:

Where is this issue occurring?

- Web
- iOS
- Android
- Desktop App
- Mobile Web

**Version Number:** 1.2.27-3
**Reproducible in staging?:** y
**Reproducible in production?:** y
**Email or phone of affected tester (no customers):** 
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** 

https://user-images.githubusercontent.com/43996225/201717877-f759f9e3-5236-4a71-a56c-afba76b870ec.mp4

https://user-images.githubusercontent.com/43996225/201717907-20f40de0-6a2e-42a8-aea6-a408d24b5d88.mp4

**Expensify/Expensify Issue URL:** 
**Issue reported by:** @thesahindia 
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1668379245649689

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

## Upwork Automation - Do Not Edit
- Upwork Job URL: https://www.upwork.com/jobs/~01cc0fb071a339c6f1
- Upwork Job ID: 1593592188567326720

**Comment by laurenreidexpensify** [comment] 2022-11-15 11:21
https://www.upwork.com/jobs/~014e5d71f901f2c73d

**Comment by hungvu193** [comment] 2022-11-15 12:06
<b>Proposal</b>
In `Avatar.js` component when internet connection is disconnected, the function `onError` called and set the state `imageError` to true, but when the internet back again, there was no function to make this state to false, that's why the avatar didn't update.
https://github.com/Expensify/App/blob/c19e245c77bd9fadc72a49560f27ff3036a4763b/src/components/Avatar.js#L65-L81

<b>Solution</b>
We need to add `componentDidUpdate` and check when ever the internet connection is back and decide to reload the avatar.

```diff
From c3a484470341280d6972e7464abc8f3ff77d5d90 Mon Sep 17 00:00:00 2001
From: Hans <visaocuoitroi193@gmail.com>
Date: Tue, 15 Nov 2022 19:05:55 +0700
Subject: [PATCH] make avatar update

---
 src/components/Avatar.js | 22 +++++++++++++++++++---
 1 file changed, 19 insertions(+), 3 deletions(-)

diff --git a/src/components/Avatar.js b/src/components/Avatar.js
index aa4f6dbf9..409e899e4 100644
--- a/src/components/Avatar.js
+++ b/src/components/Avatar.js
@@ -1,7 +1,8 @@
-import React, {PureComponent} from 'react';
+import React, {Component, PureComponent} from 'react';
 import {Image, View} from 'react-native';
 import PropTypes from 'prop-types';
 import _ from 'underscore';
+import lodashGet from 'lodash/get';
 import stylePropTypes from '../styles/stylePropTypes';
 import Icon from './Icon';
 import themeColors from '../styles/themes/default';
@@ -9,6 +10,8 @@ import CONST from '../CONST';
 import * as StyleUtils from '../styles/StyleUtils';
 import * as Expensicons from './Icon/Expensicons';
 import getAvatarDefaultSource from '../libs/getAvatarDefaultSource';
+import {withNetwork} from './OnyxProvider';
+import networkPropTypes from './networkPropTypes';
 
 const propTypes = {
     /** Source for the avatar. Can be a URL or an icon. */
@@ -29,6 +32,9 @@ const propTypes = {
 
     /** A fallback avatar icon to display when there is an error on loading avatar from remote URL. */
     fallbackIcon: PropTypes.func,
+
+    /** Props to detect online status */
+    network: networkPropTypes.isRequired,
 };
 
 const defaultProps = {
@@ -40,7 +46,7 @@ const defaultProps = {
     fallbackIcon: Expensicons.FallbackAvatar,
 };
 
-class Avatar extends PureComponent {
+class Avatar extends Component {
     constructor(props) {
         super(props);
         this.state = {
@@ -48,6 +54,16 @@ class Avatar extends PureComponent {
         };
     }
 
+    componentDidUpdate(prevProps) {
+        if (
+            lodashGet(prevProps.network, 'isOffline') === true && lodashGet(this.props.network, 'isOffline') === false
+        ) {
+            this.setState({imageError: false});
+        }
+
+        return false;
+    }
+
     render() {
         if (!this.props.source) {
             return null;
@@ -86,4 +102,4 @@ class Avatar extends PureComponent {
 
 Avatar.defaultProps = defaultProps;
 Avatar.propTypes = propTypes;
-export default Avatar;
+export default withNetwork()(Avatar);
-- 
2.31.0


```

**Comment by yuwenmemon** [comment] 2022-11-15 18:10
Hmmm... @hungvu193 I don't think that's the behavior we're looking for here. The image avatars should still stay even if you go offline. We shouldn't remove data that we already have if that makes sense.

In other words, we should only be recovering from the avatar "error state" - not purposefully sending it to an error state when we go offline. The error state should only come up if we've failed to grab the original avatar - does that make sense?

**Comment by hungvu193** [comment] 2022-11-16 02:53
> Hmmm... @hungvu193 I don't think that's the behavior we're looking for here. The image avatars should still stay even if you go offline. We shouldn't remove data that we already have if that makes sense.
> 
> In other words, we should only be recovering from the avatar "error state" - not purposefully sending it to an error state when we go offline. The error state should only come up if we've failed to grab the original avatar - does that make sense?

Makes sense, I think I need to implement `shouldComponentUpdate` to check that.

**Comment by hungvu193** [comment] 2022-11-16 03:32
@yuwenmemon 
<b>Updated proposal</b>
I updated the `shouldComponentUpdate` and `componentDidUpdate` to avoid redundant render.

```diff
From fa505d1945c9dd1bf79b57488dd2639a9228d8c1 Mon Sep 17 00:00:00 2001
From: Hans <visaocuoitroi193@gmail.com>
Date: Tue, 15 Nov 2022 19:05:55 +0700
Subject: [PATCH] make avatar update

---
 src/components/Avatar.js | 41 +++++++++++++++++++++++++++++++++++++---
 1 file changed, 38 insertions(+), 3 deletions(-)

diff --git a/src/components/Avatar.js b/src/components/Avatar.js
index aa4f6dbf9..2967fd454 100644
--- a/src/components/Avatar.js
+++ b/src/components/Avatar.js
@@ -1,7 +1,8 @@
-import React, {PureComponent} from 'react';
+import React, {Component, PureComponent} from 'react';
 import {Image, View} from 'react-native';
 import PropTypes from 'prop-types';
 import _ from 'underscore';
+import lodashGet from 'lodash/get';
 import stylePropTypes from '../styles/stylePropTypes';
 import Icon from './Icon';
 import themeColors from '../styles/themes/default';
@@ -9,6 +10,8 @@ import CONST from '../CONST';
 import * as StyleUtils from '../styles/StyleUtils';
 import * as Expensicons from './Icon/Expensicons';
 import getAvatarDefaultSource from '../libs/getAvatarDefaultSource';
+import {withNetwork} from './OnyxProvider';
+import networkPropTypes from './networkPropTypes';
 
 const propTypes = {
     /** Source for the avatar. Can be a URL or an icon. */
@@ -29,6 +32,9 @@ const propTypes = {
 
     /** A fallback avatar icon to display when there is an error on loading avatar from remote URL. */
     fallbackIcon: PropTypes.func,
+
+    /** Props to detect online status */
+    network: networkPropTypes.isRequired,
 };
 
 const defaultProps = {
@@ -40,7 +46,7 @@ const defaultProps = {
     fallbackIcon: Expensicons.FallbackAvatar,
 };
 
-class Avatar extends PureComponent {
+class Avatar extends Component {
     constructor(props) {
         super(props);
         this.state = {
@@ -48,6 +54,35 @@ class Avatar extends PureComponent {
         };
     }
 
+    shouldComponentUpdate(nextProps, nextState) {
+        if (
+            lodashGet(this.props.network, 'isOffline')
+                  && !lodashGet(nextProps.network, 'isOffline')
+        ) {
+            return true;
+        }
+        if (this.props.source !== nextProps.source) {
+            return true;
+        }
+        if (this.state.imageError !== nextState.imageError) {
+            return true;
+        }
+
+        return false;
+    }
+
+    componentDidUpdate(prevProps) {
+        if (!this.state.imageError) {
+            return;
+        }
+        if (
+            lodashGet(prevProps.network, 'isOffline') === true
+            && lodashGet(this.props.network, 'isOffline') === false
+        ) {
+            this.setState({imageError: false});
+        }
+    }
+
     render() {
         if (!this.props.source) {
             return null;
@@ -86,4 +121,4 @@ class Avatar extends PureComponent {
 
 Avatar.defaultProps = defaultProps;
 Avatar.propTypes = propTypes;
-export default Avatar;
+export default withNetwork()(Avatar);
-- 
2.31.0


```
Result:
https://user-images.githubusercontent.com/16502320/202076907-9e4b5e03-be16-4f11-bb51-01cd896e33a6.mov

**Comment by Emz27** [comment] 2022-11-16 10:42
### Proposal
- initially render both placeholder and user image. User avatar on top of the placeholder that acts as an overlay with transparent background so that the placeholder can be seen while the user avatar is still loading .Set userAvatarLoaded state on load of user avatar and this state will determine if we need to unmount the placeholder.


I suggest that we dont unmount the user avatar or use any offline handlers because it might be inaccurate at times and it just prevent the image native handler that resumes image loading when user restored the connection

**Comment by yuwenmemon** [comment] 2022-11-16 17:54
Thanks, @parasharrajat - Agreed. Assigning @hungvu193

**Comment by parasharrajat** [comment] 2022-11-16 19:13
I think we will not need `shouldComponentUpdate`. This will be cleared in the PR.

**Comment by hungvu193** [comment] 2022-11-17 00:48
Cool. I will create a PR and test it carefully

**Comment by yuwenmemon** [comment] 2022-11-17 00:55
Thanks, @hungvu193 and @parasharrajat - just a heads up that I'm going OOO until the 28th so hopefully @laurenreidexpensify will be able to help find another engineer to sign off and merge your PR when it's ready.

**Comment by hungvu193** [comment] 2022-11-17 04:03
https://github.com/Expensify/App/pull/12808 is ready for review.
Since we need to use the `withNetwork()` to reload the image, I still think we need the `shouldComponentUpdate` to control the render, I added more condition to prevent the redundant render.

**Comment by laurenreidexpensify** [comment] 2022-11-18 13:10
@nkuoch adding you for PR review to take over from Yuwen

**Comment by laurenreidexpensify** [comment] 2022-11-28 12:59
PR Is merged

**Comment by parasharrajat** [comment] 2022-11-28 15:00
Not yet merged. Still discussing some changes on the [PR](https://github.com/Expensify/App/pull/12808).

**Comment by parasharrajat** [comment] 2022-11-28 15:02
@hungvu193 Can you please answer my questions so that I can wrap up the discussion and merge this PR asap?

**Comment by hungvu193** [comment] 2022-11-28 15:03
@parasharrajat sure, I'll get back to you shortly

**Comment by yuwenmemon** [comment] 2022-12-05 18:32
@laurenreidexpensify We're in the process of reviewing the PR here: https://github.com/Expensify/App/pull/12808

**Comment by parasharrajat** [comment] 2022-12-09 07:37
Please hold the payment for this task until https://github.com/Expensify/App/pull/12808#issuecomment-1343956202 is done.

**Comment by laurenreidexpensify** [comment] 2022-12-20 11:22
@hungvu193 @parasharrajat @thesahindia apols, I thought I had hired everyone in Upwork already 🤦🏽‍♀️, have sent offers now and will issue payment as soon as accepted.

**Comment by hungvu193** [comment] 2022-12-20 11:23
@laurenreidexpensify I've accepted the offer

**Comment by laurenreidexpensify** [comment] 2022-12-22 14:54
Everyone has been paid, I'm downgrading this to weekly over the holidays so we can complete the outstanding steps in the new year when everyone is back online

**Comment by laurenreidexpensify** [comment] 2023-01-10 13:40
@nkuoch @parasharrajat bump [here](https://github.com/Expensify/App/issues/12712#issuecomment-1349863519) on completing these tasks

**Comment by laurenreidexpensify** [comment] 2023-01-11 13:43
Regression convo [here](https://expensify.slack.com/archives/C01SKUP7QR0/p1673358665588099)

**Closed** 2023-01-11 13:55 UTC
Labels: Reviewing, External, Weekly, Bug
