### ISSUE TITLE
[HOLD for payment 2023-10-27] [$1000] Web -  Number field gives an error and at the same time the send btn's background gets changed

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#23889] opened 2023-07-30 19:17 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Open website
2. Go to settings > Workspaces > Any workspace > Cards > Connect Bank Account
3. Reach 3rd step of Connect Bank Account
4. Go to Passport > Get Secure Link > Get link via sms
5. Type in wrong number and click on send button

## Expected Result:
 Number field gives an error and at the same time the send btn's background shouldn't get changed

## Actual Result:
Number field gives an error and at the same time the send btn's background gets changed

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [x] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 1.3.47-3
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation

![image (11)](https://github.com/Expensify/App/assets/93399543/2068fe22-595c-43e5-8b73-1a803e7beb6c)

https://github.com/Expensify/App/assets/93399543/2b360f88-0880-4b3c-be99-ebcb815c4ebe

**Expensify/Expensify Issue URL:**
**Issue reported by:** @muxriddinmuqimov77
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1690615896430559

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01cbbd9908c732f466</li>
        <li>Upwork Job ID: 1686053239255556096</li>
        <li>Last Price Increase: 2023-10-17</li>
<li>Automatic offers: </li>
<ul>
<li>situchan | Reviewer | 27261508</li>
<li>ginsuma | Contributor | 27261511</li>
<li>muxriddinmuqimov77 | Reporter | 27261515</li>
</ul></li>
    </ul>
</details>

**Comment by ishpaul777** [comment] 2023-07-31 17:18
Dupe of https://github.com/Expensify/App/issues/23074

ideally this should be fixed from Onfido side or have a customization option for disabled button.

**Comment by situchan** [comment] 2023-07-31 19:55
@lschurr Let's put this on hold for #23074

**Comment by b4s36t4** [comment] 2023-07-31 19:55
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
Web - Number field gives an error and at the same time the send btn's background gets changed
### What is the root cause of that problem?

Firstly I don't think this is a bug at all because if we clear the input button would get enabled again.

Alternatively if we think this is a bug here's the RCA.

This is an upstream bug of  `onfido-skd-ui` package. They're doing returning and disabling button once the number is in-valid which shouldn't be the case. They should just show the error return without disabling the button.
### What changes do you think we should make in order to solve the problem?
`onfido-sdk-ui`'s code is closed source, couldn't able to find any related code (maybe I'm dumb :P). 

1. We can either create an issue and let `onfido` team fix this issue (maybe they won't cause they feel it's not a bug).

2. We have the build version of `onfido` SDK which we can patch using `patch-package`, but what to update is here's the question.

I observed the code thoroughly and found out that they're disabling the button in two cases
    1. If the API call is loading
    2. If the phone number is invalid (which only update when we click on Send Link button)

Here 2nd point is the issue we can update the `disabled` prop to only `n` instead of `n||a`.

Here `n` means loading status of the API call, `a` means validation state of phone number.

I know this seems pretty weird fix but this is what I came up with :)
<img width="767" alt="Screenshot 2023-08-01 at 1 13 59 AM" src="https://github.com/Expensify/App/assets/59088937/d8c5977d-2f03-40c0-a515-9043909c4849">

### What alternative solutions did you explore? (Optional)
Maybe just wait till onfido does this on their own, or if I could get the repo which this code is hosted I could fix it upstream(depends on the decision from `onfido`).

**Comment by b4s36t4** [comment] 2023-07-31 20:05
We can observe the above code snippet here https://cdn.jsdelivr.net/npm/onfido-sdk-ui@12.4.0/lib/index.js
simply do CTRL + F -> `disabled:n||a`.

**Comment by lschurr** [comment] 2023-07-31 20:44
Thanks @situchan - on hold

**Comment by lschurr** [comment] 2023-08-09 20:26
This is on hold.

**Comment by lschurr** [comment] 2023-08-21 15:09
On hold.

**Comment by lschurr** [comment] 2023-09-11 15:22
On hold

**Comment by lschurr** [comment] 2023-09-21 00:18
On hold.

**Comment by lschurr** [comment] 2023-10-02 12:03
On hold.

**Comment by lschurr** [comment] 2023-10-10 15:44
On hold.

**Comment by b4s36t4** [comment] 2023-10-10 16:01
@lschurr why are we putting this on hold?

**Comment by lschurr** [comment] 2023-10-10 16:43
This has been on hold since July - https://github.com/Expensify/App/issues/23889#issuecomment-1659043671

cc @situchan

**Comment by situchan** [comment] 2023-10-10 16:53
The holding issue was also on hold for very long time. So I started considering another approach - https://github.com/Expensify/App/issues/23074#issuecomment-1752245401

**Comment by situchan** [comment] 2023-10-15 17:19
As onfido team will be unlikely to fix this after waiting many months, I think it's fine to apply patch ourselves.
So here, we can fix button background to match our app disabled color. And in https://github.com/Expensify/App/issues/23074, fix wrong position of loading icon.

**Comment by situchan** [comment] 2023-10-15 17:29
@lschurr if you agree, we can remove hold and wait for new proposals

**Comment by b4s36t4** [comment] 2023-10-15 17:54
Updated my proposal with some proofs that my RCA and solution is correct :)

**Comment by lschurr** [comment] 2023-10-16 19:13
Cool, let's do it. Can you review @b4s36t4's revised proposal @situchan?

**Comment by situchan** [comment] 2023-10-17 17:18
@ginsuma can you submit [your proposal](https://github.com/Expensify/App/issues/23074#issuecomment-1640136264) here?

**Comment by b4s36t4** [comment] 2023-10-17 17:22
@situchan I don't these two issues are similar may I know why you asked to submit proposal here?

**Comment by situchan** [comment] 2023-10-17 17:24
@b4s36t4 I don't like your proposal

**Comment by b4s36t4** [comment] 2023-10-17 18:01
> I don't like your proposal.

You could've asked me to update my proposal :). 

I have updated my proposal considering this issue, please check when you have time. 

> Ready to take other issue if you're feeling good about my proposal.

**Comment by situchan** [comment] 2023-10-18 11:14
@ginsuma's [proposal](https://github.com/Expensify/App/issues/23889#issuecomment-1768052180) looks good to me.
🎀 👀 🎀 C+ reviewed

**Comment by iwiznia** [comment] 2023-10-18 11:39
Proposal looks good, but the 2nd screenshot with the `Sending` message seems too close to the border on the right, no?
Can we do something to fix that too? Maybe make the button wider in general? cc @Expensify/design just to make sure that would be the correct approach

**Comment by situchan** [comment] 2023-10-18 11:46
> 2nd screenshot with the Sending message seems too close to the border on the right, no?

Oh well, there's already separate issue for that - https://github.com/Expensify/App/issues/23074
If we should fix here, then we can

**Comment by iwiznia** [comment] 2023-10-18 11:54
hmmmm aren't this and that issue duplicates?? Or at least very related... I think we should close one of them and unify them.

Thoughts @situchan @CortneyOfstad @lschurr?

**Comment by shawnborton** [comment] 2023-10-18 11:56
<img width="122" alt="CleanShot 2023-10-18 at 07 56 07@2x" src="https://github.com/Expensify/App/assets/2319350/26fe5f82-76e2-469b-931d-3e4475d10610">


Agree, would be nice if that content was centered within the button itself.

**Comment by shawnborton** [comment] 2023-10-18 12:03
If we think the bounty is too high we should feel comfortable backing it down to $500.

**Comment by situchan** [comment] 2023-10-18 12:07
Let's combine them and fix together here and close https://github.com/Expensify/App/issues/23074.
And old base price (before announcement) applies as this is very old issue.
If everyone agrees?

**Comment by iwiznia** [comment] 2023-10-18 12:09
I am fine with that

**Comment by situchan** [comment] 2023-10-18 14:30
<img width="350" alt="276287122-fc6f91d4-fe7d-4c73-a52e-46ad4baaf39f" src="https://github.com/Expensify/App/assets/108292595/cd021b51-681b-4d0a-97f6-fcf28aa9ee03">

LGTM cc: @shawnborton

**Comment by shawnborton** [comment] 2023-10-18 14:44
Nice!

**Comment by situchan** [comment] 2023-10-18 14:45
@iwiznia all yours!

**Comment by lschurr** [comment] 2023-10-26 05:48
Could you work on the checklist for this one @situchan?

**Comment by lschurr** [comment] 2023-10-26 05:49
Payment summary:

- Bug reporter: @muxriddinmuqimov77 $50
- Contributor: @ginsuma $750
- Contributor+: @situchan $750

**Comment by situchan** [comment] 2023-10-26 05:49
No regression. This is long existed UI issue from Onfido sdk.
Regression test also not applies here.

**Comment by situchan** [comment] 2023-10-26 05:53
> Hey @situchan. Who is gonna be eligible for reporter role for this isseu? Me or @MahmudjonToraqulov?

@muxriddinmuqimov77 Not sure about your question. I see that you're marked as reporter on both issues.

**Comment by muxriddinmuqimov77** [comment] 2023-10-26 09:24
@situchan And one more thing. I think the payment should be 250$ as it was
created before 30 August.

2023 okt 26, Pay, 10:53 Situ Chandra Shil ***@***.***>:

**Comment by lschurr** [comment] 2023-10-26 15:55
Oh you're right, payment should be the older structure. I'll update the payment summary.

**Comment by lschurr** [comment] 2023-10-27 17:07
@muxriddinmuqimov77 please accept the offer in Upwork so that we can pay and close. https://www.upwork.com/nx/wm/offer/27261515

**Comment by MahmudjonToraqulov** [comment] 2023-10-27 17:16
Accepted

2023 okt 27, Jum, 22:08 Lauren Schurr ***@***.***>:

**Comment by lschurr** [comment] 2023-10-27 17:29
All payments made in Upwork. Closing!

**Closed by lschurr** 2023-10-27 17:29 UTC
Labels: External, Daily, Awaiting Payment, Bug
