### ISSUE TITLE
[HOLD for payment 2024-07-02] Pay someone - App crashes after paying someone and opening chat header in transaction thread

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#44201] opened 2024-06-22 13:14 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 9.0.1-0
**Reproducible in staging?:** Y
**Reproducible in production?:** N 
**If this was caught during regression testing, add the test name, ID and link from TestRail:** N/A
**Issue reported by:** Applause - Internal Team

## Action Performed:
1. Go to staging.new.expensify.com
2. Go to any chat
3. Go to + > Pay <user>
4. Enter amount > Pay elsewhere
5. Immediately click on the expense preview and then the chat header after paying the money
6. Wait until the app crashes

## Expected Result:
App will not crash

## Actual Result:
App crashes after paying someone and opening chat header in transaction thread

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [x] Android: mWeb Chrome
- [x] iOS: Native
- [x] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details> 

https://github.com/Expensify/App/assets/78819774/7aca81b2-792a-4676-99eb-a0f18b80514e

[logs (2).txt](https://github.com/user-attachments/files/15936663/logs.2.txt)

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by lanitochka17** [comment] 2024-06-22 13:15
@dangrous  FYI I haven't added the External label as I wasn't 100% sure about this issue. Please take a look and add the label if you agree it's a bug and can be handled by external contributors

**Comment by ikevin127** [comment] 2024-06-23 17:25
cc @cdOut If this is indeed caused by our PR, looks like we missed adding the right fallback value there ^.

**Comment by dangrous** [comment] 2024-06-24 17:33
@ikevin127 @cdOut let us know when this is ready for a look!

**Comment by cdOut** [comment] 2024-06-24 17:48
@dangrous the PR is mentioned here and ready for review.

**Comment by ikevin127** [comment] 2024-06-24 17:53
PR was ✅ **Approved** - ready for final review & merge!

**Comment by cdOut** [comment] 2024-06-24 18:50
Fixed in [this PR](https://github.com/Expensify/App/pull/44279).

**Comment by dangrous** [comment] 2024-06-24 19:00
As noted on the other PR ^, this should be fixed by https://github.com/Expensify/App/pull/44279

**Comment by dangrous** [comment] 2024-07-03 09:57
Closing this out since payment will be handled in the other regression issue.

**Closed by dangrous** 2024-07-03 09:57 UTC
Labels: Engineering, Daily, Overdue, Awaiting Payment
