### ISSUE TITLE
[C+ Checklist Needs Completion] [$500] Web - App does not close Hmm its not here page on selecting current report from search

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#27580] opened 2023-09-16 15:41 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Open the app
2. Open any report
3. Trigger full page Hmm its not here page by visiting settings->workspace->any workspace->settings, copy the URL, remove 's' from the end and visit it.
4. Open search page by CTRL+K
5. Click on same report as opened in step 2
6. Observe that app still displays Full page 'Hmm its not here' page instead of report

## Expected Result:
App should close Full page 'Hmm its not here' page on selecting any report from search

## Actual Result:
App does not close Full page 'Hmm its not here' page on selecting same report as opened in background from search

## Workaround:
Unknown 

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [x] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 1.3.70.5
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/93399543/b1dd5f4b-5d0e-4305-95b5-83b383477cdc

https://github.com/Expensify/App/assets/93399543/3f421128-6714-43d6-b3f2-4fd9b63411d7

**Expensify/Expensify Issue URL:**
**Issue reported by:** @dhanashree-sawant
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1694765722471659

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01ba78cc3a004601db</li>
        <li>Upwork Job ID: 1703071612120547328</li>
        <li>Last Price Increase: 2023-10-07</li>
<li>Automatic offers: </li>
<ul>
<li>fedirjh | Reviewer | 27150714</li>
<li>s-alves10 | Contributor | 27150719</li>
<li>dhanashree-sawant | Reporter | 27150722</li>
</ul></li>
    </ul>
</details>

**Comment by abdel-h66** [comment] 2023-09-16 16:53
## Proposal

### Please re-state the problem that we are trying to solve in this issue.

Web - App does not close Hmm its not here page on selecting current report from search

### What is the root cause of that problem?
When the serach is opened on the current report.  We are just dissmissing the Search modal which makes sense because the report is already open using this 


### What changes do you think we should make in order to solve the problem?
When the not found page appear, we have the last route name equal to `NAVIGATORS.RIGHT_MODAL_NAVIGATOR`

https://github.com/Expensify/App/blob/76c1559fb3fbee1d07c8f210b522b63edd03920e/src/libs/Navigation/Navigation.js#L156

```
 if(targetReportID === getTopmostReportId(rootState) && lastRoute === NAVIGATORS.RIGHT_MODAL_NAVIGATOR) {
                navigationRef.current.dispatch({...StackActions.pop(2), target: rootState.key});
                return
            }
```
            

### What alternative solutions did you explore? (Optional)

N/A

**Comment by s-alves10** [comment] 2023-09-16 17:19
## Proposal

### Please re-state the problem that we are trying to solve in this issue.

App doesn't close not-found page when navigating to the not-found page and navigating back to the current report from search

### What is the root cause of that problem?

If user goes to the not-found page, the navigation stack has 3 navigators: `Home`, `CentralPanNavigator`(report), `not-found`. 
If the user opens the search report modal, the navigation stack has 4, `RightModalNavigator` is added to the end

https://github.com/Expensify/App/blob/76c1559fb3fbee1d07c8f210b522b63edd03920e/src/libs/Navigation/Navigation.js#L167-L175

In this case, `targetReportID` is the same as top-most reportID and so we pop the navigation stack once in line 174. That's why not-found page appears(not closed)

This is the root cause

### What changes do you think we should make in order to solve the problem?

We're assuming that we can go to the report by popping once from the RightModalNavigator. This is wrong. We need to generalize this

We can fix this issue by popping to central navigator
```
        if (targetReportID) {
            if (targetReportID !== getTopmostReportId(rootState)) {
                const state = getStateFromPath(ROUTES.getReportRoute(targetReportID));

                const action = getActionFromState(state, linkingConfig.config);
                action.type = 'REPLACE';
                navigationRef.current.dispatch(action);
            } else {
                const lastRouteIndex = rootState.routes.length - 1;
                const centralRouteIndex = _.findLastIndex(rootState.routes, route => route.name === NAVIGATORS.CENTRAL_PANE_NAVIGATOR);
                navigationRef.current.dispatch({...StackActions.pop(lastRouteIndex - centralRouteIndex), target: rootState.key});
            }
        } else {
            navigationRef.current.dispatch({...StackActions.pop(), target: rootState.key});
        }
```

This works fine

<details>
    <summary>Result</summary>


</details>


### What alternative solutions did you explore? (Optional)

**Comment by greg-schroeder** [comment] 2023-09-25 07:36
Awaiting proposal review @fedirjh

**Comment by greg-schroeder** [comment] 2023-09-28 07:34
Bump @fedirjh

**Comment by s-alves10** [comment] 2023-10-02 14:41
## Proposal
[Updated](https://github.com/Expensify/App/issues/27580#issuecomment-1722275079)

**Comment by greg-schroeder** [comment] 2023-10-04 16:01
Looks like we're working on updated proposals here?

**Comment by joelbettner** [comment] 2023-10-11 22:51
@fedirjh that sounds good to me. I'll assign @s-alves10 to this issue.

**Comment by s-alves10** [comment] 2023-10-12 00:41
@fedirjh 

PR is ready for review https://github.com/Expensify/App/pull/29404

**Comment by greg-schroeder** [comment] 2023-10-23 23:03
Processing

**Comment by greg-schroeder** [comment] 2023-10-23 23:19
Payments complete. @fedirjh just need you to complete the C+ checklist and we can close this out!

**Comment by greg-schroeder** [comment] 2023-10-27 16:47
filing regression test

**Closed by greg-schroeder** 2023-10-27 16:47 UTC
Labels: External, Engineering, Daily, Awaiting Payment, Bug
