### ISSUE TITLE
BUG: The invalid incorporation date error message doesn't hide after the initial date selection @adeel0202

### ISSUE THREAD

**Issue by kavimuru** [Expensify/App#11787] opened 2022-10-13 01:34 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:

1. Go to Profile > Workspace > Connect a bank account > Connect manually
2. Enter a valid routing number and account number
3. Click save & continue
4. On company information page, click save & continue without selecting the incorporation date (clear the date first if already selected)
5. Click on the calendar icon
6. Select any date (Observe the invalid date error is still there)
7. Click on the calendar icon again
8. Select any other date (Observe the invalid date error hides this time)

## Expected Result:
The error hides after the initial selection

## Actual Result:
The error doesn't hide after the initial selection, it hides after the second selection

## Workaround:
Unknown

## Platform:

Where is this issue occurring?

- Web
- iOS
- Android
- Desktop App
- Mobile Web

**Version Number:** 1.2.13-3
**Reproducible in staging?:** y
**Reproducible in production?:** y
**Email or phone of affected tester (no customers):** 
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** 

https://user-images.githubusercontent.com/43996225/195478378-3652fdfd-9c42-4ec4-8a70-084b49288f63.mov

https://user-images.githubusercontent.com/43996225/195478391-2d6ed09d-d0dc-4bbf-9d6f-410c179c3863.mp4

**Expensify/Expensify Issue URL:** 
**Issue reported by:** @adeel0202
**Slack conversation:** https://expensify.slack.com/archives/C01GTK53T8Q/p1665603979725659

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by strepanier03** [comment] 2022-10-13 03:59
Hmm, I'm having trouble reproducing this. Getting a spinner on staging when trying to load the _Connect a bank account_ page. 

Will circle back to this tomorrow.
![2022-10-12_20-58-06 (1)](https://user-images.githubusercontent.com/10925636/195496055-1ef181f4-6f71-484d-a0f8-1b7e3513adbf.gif)

**Comment by Puneet-here** [comment] 2022-10-13 10:57
### Proposal

add `this.clearErrors = inputKeys => ReimbursementAccountUtils.clearErrors(this.props, inputKeys);` after line 41
https://github.com/Expensify/App/blob/8aec877a678d09600e110e0fc7bc597e342ef342/src/pages/ReimbursementAccount/CompanyStep.js#L41
and use `this.clearErrors(['incorporationDate', 'incorporationDateFuture']);` at line 104 instead 
https://github.com/Expensify/App/blob/8aec877a678d09600e110e0fc7bc597e342ef342/src/pages/ReimbursementAccount/CompanyStep.js#L104

**Comment by strepanier03** [comment] 2022-10-15 00:14
Sending on to Eng to see if they can reproduce. I cannot get further in testing this process on staging and am stuck at a spinner. 

Eng, can you reproduce as part of your triage and then recommend fixing this or not?

**Comment by stitesExpensify** [comment] 2022-10-18 16:51
I am unable to reproduce this. 

https://user-images.githubusercontent.com/42391420/196494655-17633812-c666-420e-a787-a06ea1b6395a.mp4

**Comment by adeel0202** [comment] 2022-10-18 16:59
@stitesExpensify please follow the steps mentioned or follow the videos attached. You have to select the date from calendar that shows after clicking on the calendar icon, instead of entering the date manually.

**Comment by stitesExpensify** [comment] 2022-10-18 17:52
@eVoloshchak what do you think of @Puneet-here's proposal?

**Comment by stitesExpensify** [comment] 2022-10-20 21:41
@Puneet-here proposal looks good to me too! @muttmuure can you please create an upwork job so that they can apply?

**Comment by stitesExpensify** [comment] 2022-10-24 15:09
Bump @muttmuure :)

**Comment by muttmuure** [comment] 2022-10-27 15:47
Damn this wasn't showing in my K2 - sorry!

Job is posted [here](https://www.upwork.com/jobs/~01b83c7e308b91af23)

**Comment by Puneet-here** [comment] 2022-10-28 13:15
Hi @muttmuure, I have applied to the job. You can assign me now. I will raise the PR by tomorrow

**Comment by stitesExpensify** [comment] 2022-11-07 16:18
This PR was deployed to Production 3 days ago, I'm not sure why the payout countdown hasn't started yet

**Comment by muttmuure** [comment] 2022-11-09 13:10
I've paid @Puneet-here and @eVoloshchak - @adeel0202 can you apply to the job [here](https://github.com/Expensify/App/issues/11787#issuecomment-1293733175) so you can get paid

**Comment by muttmuure** [comment] 2022-11-11 17:23
Everyone has been paid, closing out. Great work everyone.

**Closed by muttmuure** 2022-11-11 17:23 UTC
Labels: External, Engineering, Weekly, Improvement, Bug
