### ISSUE TITLE
[HOLD for payment 2024-01-17] [$500] The request money preview does not change to "delete" after the request money has been deleted.

### ISSUE THREAD

**Issue by m-natarajan** [Expensify/App#30219] opened 2023-10-23 22:46 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.3.89-6
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** @ayazhussain79 
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1698086923136169

## Action Performed:
1. Open a chat
2. Go to the request money(Pay or delete them if you've requested before)
3. Enter a specific amount and send the request money
4. Navigate to the request money detail page
5. Click on the amount and change it
6. Click on the three-dot menu and add a receipt file
7. After adding the receipt, delete the requested money
8. Go back to the chat
## Expected Result:
The request money preview should change to "delete" after the request money has been deleted
## Actual Result: 
The request money preview does not change to "delete" after the request money has been deleted
Platforms: Tested on web
## Workaround:
unknown
## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [x] Android: mWeb Chrome
- [x] iOS: Native
- [x] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos
<details>
<summary>Android: Native</summary>

https://github.com/Expensify/App/assets/38435837/a178f91e-0484-4531-a94a-92f5f9a95f73

</details>

<details>
<summary>Android: mWeb Chrome</summary>

https://github.com/Expensify/App/assets/38435837/a365e5e4-6d94-46f1-a462-8d310c9a283a

</details>

<details>
<summary>iOS: Native</summary>

https://github.com/Expensify/App/assets/38435837/d92c69a4-fe7c-4991-be9e-a8c48bcae360

</details>

<details>
<summary>iOS: mWeb Safari</summary>

https://github.com/Expensify/App/assets/38435837/620897c1-2479-4fdc-954f-8d99306c78a9

</details>

<details>
<summary>MacOS: Chrome / Safari</summary>

https://github.com/Expensify/App/assets/38435837/bf63216f-99d9-47e1-9e7f-a00bfed23825

https://github.com/Expensify/App/assets/38435837/22131c17-7dc1-4d05-8820-368aa1d26973

</details>

<details>
<summary>MacOS: Desktop</summary>

https://github.com/Expensify/App/assets/38435837/5ef8b478-26c3-4082-a1ef-2c7e61389333

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01105d20ae33f4b56d</li>
        <li>Upwork Job ID: 1716586918273536000</li>
        <li>Last Price Increase: 2023-11-13</li>
    </ul>
</details>

**Comment by isabelastisser** [comment] 2023-10-25 19:31
Hey @allroundexperts, can you please review the proposals above? Thanks!

**Comment by rojiphil** [comment] 2023-10-27 09:58
## Proposal

### Please re-state the problem that we are trying to solve in this issue.

When the last money request is deleted from the IOU report, the corresponding report preview in chat report should change to [Deleted request] . While this is not required for the case where the IOU Report has no visible child actions (also the BE deletes the IOUReport and corresponding Report Preview in chat report), [Deleted request] needs to be displayed in scenarios where IOU Report has visible child actions. This is the problem we are trying to solve here.

### What is the root cause of that problem?

These are improvements over an existing implementation of money requests. 

### What changes do you think we should make in order to solve the problem?

To solve this problem, instead of displaying the usual `Report Preview` content, we can display [Deleted request] when there are visible actions but there are no money requests left in the IOU Report. We can make the changes like this [here](https://github.com/Expensify/App/blob/a44824d60485abc367eef120117b774e1f71370d/src/components/ReportActionItem/ReportPreview.js#L184C1-L184C1)

```
    const childVisibleActionCount = _.get(props, ['action', 'childVisibleActionCount'], 0);        
    const childMoneyRequestCount = _.get(props, ['action', 'childMoneyRequestCount'], 0);        
    if ((childVisibleActionCount > 0 && childMoneyRequestCount === 0) ) {
        return <RenderHTML html={`<comment>${props.translate('parentReportAction.deletedRequest')}</comment>`} />;
    }    
```

Additionally, LHN messages also need to be updated accordingly so that [Deleted request] is displayed. 

### What alternative solutions did you explore? (Optional)

**Comment by isabelastisser** [comment] 2023-10-30 18:00
hey @allroundexperts, can you please review the updated proposal above? Thanks!

**Comment by rojiphil** [comment] 2023-11-02 14:57
## Proposal

[Updated](https://github.com/Expensify/App/issues/30219#issuecomment-1782638616)
@allroundexperts 
Added test video section.
Kindly review

**Comment by isabelastisser** [comment] 2023-11-06 15:52
Hey @allroundexperts, what's the update here? Thanks!

**Comment by rojiphil** [comment] 2023-11-08 03:20
@allroundexperts 
I think we can take this issue further based on the [slack comment here](https://expensify.slack.com/archives/C01GTK53T8Q/p1699285833369879?thread_ts=1699251346.849569&cid=C01GTK53T8Q) 
What are your thoughts?

**Comment by isabelastisser** [comment] 2023-11-09 16:50
@allroundexperts, please provide an update!

**Comment by isabelastisser** [comment] 2023-11-10 18:48
@allroundexperts, please provide an update! Thanks!

**Comment by rojiphil** [comment] 2023-11-13 11:16
I think the bug description here refers to the [Deleted request] in the Chat Report. Isn't it so?

**Comment by isabelastisser** [comment] 2023-11-13 19:31
@allroundexperts, can you please follow up on the comments above and update this issue? Thanks!

**Comment by rlinoz** [comment] 2023-11-14 09:49
>1. When edit amount/description,... we should increase the childVisibleActionCount of parentReportAction

@tienifr you're proposing that this should be a backend fix?

**Comment by isabelastisser** [comment] 2023-11-16 17:32
@allroundexperts can you please clarify this[ comment](https://github.com/Expensify/App/issues/30219#issuecomment-1809166157)? Are you saying this issue can be closed because the fix will be handled [here?](https://github.com/Expensify/App/issues/26511.)

**Comment by isabelastisser** [comment] 2023-11-18 01:44
@tienifr @allroundexperts please follow up on the comment above. Thanks!

**Comment by rlinoz** [comment] 2023-11-20 13:30
I did a few tests and looks like we do handle those kinds of messages as unread messages, so I think it would make sense to count them as thread replies.

My concern is that we do have some automated test to ensure that doesn't happen, so I will try to get the opinion of someone internally.

**Comment by rlinoz** [comment] 2023-11-22 15:31
Just confirmed, a money request that has only changelogs should be deleted leaving no trace (i.e. no [Deleted Request], so I guess we need a different proposal here.

**Comment by rojiphil** [comment] 2023-11-22 17:23
## Proposal

### Please re-state the problem that we are trying to solve in this issue.

As per comment [here](https://github.com/Expensify/App/issues/30219#issuecomment-1822992789), the transaction should be completely removed if there are no comments within the transaction. Transaction should be completely removed even if only changelogs are present.

### What is the root cause of that problem?

When money request is deleted, we determine [here](https://github.com/Expensify/App/blob/b1f8bcca9d54b49ab88d2e7f0ba703cf57bee6fd/src/libs/actions/IOU.js#L2033) if the transaction thread should also be deleted. However, we are looking for length of last visible message using `getlastVisibleMessage` to determine if there are comments within the transaction thread. However, this is faulty as there could be `MODIFIEDEXPENSE` actions which would make the last visible message as non-empty. This will prevent the transaction thread to be deleted. I think this is the root cause. 

### What changes do you think we should make in order to solve the problem?

In order to solve the problem, we can check if IOU Report’s money request action has any valid `childVisibleActionCount` which is the true indicator of normal comments within the transaction thread. We can make the following change [here](https://github.com/Expensify/App/blob/b1f8bcca9d54b49ab88d2e7f0ba703cf57bee6fd/src/libs/actions/IOU.js#L2033)

    const shouldDeleteTransactionThread = transactionThreadID ? lodashGet(reportAction, 'childVisibleActionCount', 0) === 0 : false;


### What alternative solutions did you explore? (Optional)

**Comment by rlinoz** [comment] 2023-11-27 13:45
@allroundexperts could you take a look at the above proposal, please?

**Comment by isabelastisser** [comment] 2023-11-29 21:38
@allroundexperts please provide an update. Thanks!

**Comment by isabelastisser** [comment] 2023-11-30 20:37
Hey @allroundexperts, we have a new proposal!

**Comment by isabelastisser** [comment] 2023-12-04 17:00
Hey @allroundexperts can you please review the proposal and provide an update? Thanks!

**Comment by allroundexperts** [comment] 2023-12-05 01:14
I think we should not rely on filtering out the actions of a certain type as @tienifr suggested [here](https://github.com/Expensify/App/issues/30219#issuecomment-1833621766). This is because it would just lead to more and more filters being added conditionally down the road which will make the code less maintainable. I think that `childVisibleActionCount` serves our need just fine.

@rojiphil was the first to propose this change and I think we should go with there [proposal](https://github.com/Expensify/App/issues/30219#issuecomment-1823189501). At the same time, I think @tienifr did a great job in pointing out an [edge case](https://github.com/Expensify/App/issues/30219#issuecomment-1833621766) which @rojiphil did not cover in his proposal.

It seems fair to me if the bounty can be split evenly between the two. Let me know if both of your agree!

🎀 👀 🎀 C+ reviewed

**Comment by allroundexperts** [comment] 2023-12-05 01:43
I'm cool with it if @tienifr agrees.

**Comment by rojiphil** [comment] 2023-12-05 06:14
@tienifr 

I think it is not fair to judge what is straightforward and what is hard to discover and fix. This will only lead to endless debate without any conclusions. 

As I understand, my [proposal](https://github.com/Expensify/App/issues/30219#issuecomment-1823189501) is the first one to address the RCA and solution for the primary fix which has been approved. Whereas your proposal’s primary solution is completely different. But, I do agree that your alternate [proposal](https://github.com/Expensify/App/issues/30219#issuecomment-1833621766) brings up a related edge case. However, the RCA and the solution for the related edge case are completely different and it does not replace the RCA or solution in my proposal. Further, the related edge case is not a regression caused by my proposal. So, I think it is not fair to apply the mentioned precedent in this scenario.

@allroundexperts 

Since the related edge case has a completely different RCA and solution, maybe the solution is to increase the compensation to $750 with the split of @rojiphil($500) and @tienifr ($250). 
What are your thoughts on this?

**Comment by isabelastisser** [comment] 2023-12-05 16:42
I can be on board with this proposal. @allroundexperts, what's your opinion? Keep the compensation at $500 and split or increase it?

> Since the related edge case has a completely different RCA and solution, maybe the solution is to increase the compensation to $750 with the split of @rojiphil($500) and @tienifr ($250).
What are your thoughts on this?

**Comment by allroundexperts** [comment] 2023-12-05 16:51
I don't see any issue with this as well. Let's proceed with 500-250 if we can.

**Comment by isabelastisser** [comment] 2023-12-05 17:01
Sounds good; assigning both contributors.

**Comment by rojiphil** [comment] 2023-12-06 07:16
@allroundexperts  @rlinoz 

I think BE change is also required here to complete the fix. 

In the scenario with no transaction changelogs, the Money Request deletion will ensure that the BE also deletes the Transaction and associated IOU/Expense Report. However, in the scenario with only transaction changelogs (e.g. due to description change), the BE does not delete the Transaction and associated IOU/Expense on deletion of the last Money Request. 

Attaching test videos of both scenarios for reference:

<details>
<summary>WITH Transaction Changelogs - FAIL</summary>

https://github.com/Expensify/App/assets/3004659/9448d198-21a0-48f3-80e0-4d9b328af598

</details>

<details>
<summary>WITHOUT Transaction Changelogs - PASS</summary>

https://github.com/Expensify/App/assets/3004659/6c98ac92-1277-45de-b150-b8d48b4e2d29

</details>

**Comment by rlinoz** [comment] 2023-12-07 21:55
Yeah, the backend is sending "isDeletedParentAction": true` because of the changelogs, I will check on that.

**Comment by rlinoz** [comment] 2023-12-11 11:45
Still investigating.

**Comment by rlinoz** [comment] 2023-12-13 15:13
Figure this out in the backend, will open a PR today/tomorrow.

**Comment by rlinoz** [comment] 2023-12-14 13:22
Backend fix is deployed to production @rojiphil

**Comment by rojiphil** [comment] 2023-12-14 15:07
> Backend fix is deployed to production @rojiphil

Thanks @rlinoz for the update. 
I will start work on the FE and try to get the PR ready for review by this weekend.

**Comment by rojiphil** [comment] 2023-12-18 07:44
Update: 
While testing, I have found one more issue related to cancellation of task. The issue is mentioned [here](https://github.com/Expensify/App/pull/32543#issuecomment-1859690813).
For completeness, I have also included the fix for this in the PR.

Also, with the latest main, I ran into problems while testing Web Safari and Native Android platforms. 
I have also raised slack comment regarding the same [here](https://expensify.slack.com/archives/C01GTK53T8Q/p1702869444870729) and [here](https://expensify.slack.com/archives/C01GTK53T8Q/p1702883604941629). 
As soon as this is rectified, I will complete the testing and request for PR review.

**Comment by rlinoz** [comment] 2023-12-20 12:34
Apparently progress is being made in the PR, do we have any updates on the comment above @rojiphil ?

**Comment by rojiphil** [comment] 2024-01-17 05:29
> If no regressions arise, payment will be issued on 2024-01-17

@isabelastisser @rlinoz @allroundexperts 
Would it be fair to increase the compensation to $750 for @rojiphil (C Contributor) and @allroundexperts (C+ contributor) as this PR also fixes an additional issue (with a different root cause) [here](https://github.com/Expensify/App/pull/32543#issuecomment-1859690813). 
In all, we have fixed three different issues here.
What do you think?

**Comment by isabelastisser** [comment] 2024-01-18 17:09
We are discussing the payment amount [here.](https://expensify.slack.com/archives/C01SKUP7QR0/p1705597764372859)

**Comment by isabelastisser** [comment] 2024-01-19 13:28
Offers sent in Upwork.

Reviewer: @allroundexperts owed $750 via NewDot PENDING

**Comment by isabelastisser** [comment] 2024-01-19 13:28
@allroundexperts please complete the checklist above. Thanks!

**Comment by allroundexperts** [comment] 2024-01-21 23:26
## Checklist
1. https://github.com/Expensify/App/pull/19095
2. https://github.com/Expensify/App/pull/19095/files#r1461207158
3. N/A
4. A regression test would be useful here IMO. The steps given in the OP look good enough to me.

**Comment by isabelastisser** [comment] 2024-01-22 00:51
Thaks @allroundexperts!

**Closed by isabelastisser** 2024-01-22 00:51 UTC
Labels: Engineering, Daily, Internal, Awaiting Payment, Bug

**Comment by JmillsExpensify** [comment] 2024-01-30 22:13
$750 approved for @allroundexperts based on [this comment](https://github.com/Expensify/App/issues/30219#issuecomment-1900427912).
