### ISSUE TITLE
Hybrid - Android - Try new expensify option is not shown for new expensifail a/c on switching from new dot

### ISSUE THREAD

**Issue by IuliiaHerets** [Expensify/App#52881] opened 2024-11-21 10:45 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** V9. 0.65-1
**Reproducible in staging?:** Can't check
**Reproducible in production?:** Can't check
**If this was caught on HybridApp, is this reproducible on New Expensify Standalone?:** Y
**Issue reported by:** Applause Internal Team

## Action Performed:
1. Launch new dot app
2. Login with new expensifail account
3. Tap setting switch to expensify classic
4. Enter the same user id and login
5. Tap on menu

## Expected Result:
Try new expensify option must be shown for new expensifail a/c on switching from new dot to hybrid.

## Actual Result:
Try new expensify option is not shown for new expensifail a/c on switching from new dot to hybrid.

Note: With new gmail account, user can see "try new expensify" options following the same steps.

## Workaround:
Unknown

## Platforms:

- [ ] Android: Standalone
- [x] Android: HybridApp
- [ ] Android: mWeb Chrome
- [ ] iOS: Standalone
- [ ] iOS: HybridApp
- [ ] iOS: mWeb Safari
- [ ] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

https://github.com/user-attachments/assets/5b81dc06-1e77-426f-83e2-1d30d6b4ba4d

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by joekaufmanexpensify** [comment] 2024-11-21 17:01
@IuliiaHerets This is working for me on a new expensifail account. Going to close this for now, as this seems to be fine/not consistently reproducible. Please reopen if you can still consistently reproduce this, or if there is anything about the above steps that should be clarified to reproduce it. 

https://github.com/user-attachments/assets/a0a9a78a-aa48-45a7-b933-dee863d78b09

**Closed by joekaufmanexpensify** 2024-11-21 17:01 UTC
Labels: Daily, Bug
