### ISSUE TITLE
[HOLD for regression test steps][$1000] Web - Changing room name offline doesn't reflect in LHN until another chat/room opened

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#13457] opened 2022-12-09 00:27 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Issue found when executing PR** https://github.com/Expensify/App/pull/13189

## Action Performed:
1. Go to https://staging.new.expensify.com/
and login
2. Create a room
3. Go offline
4. Go to room settings
5. Change room name
6. Click Save

## Expected Result:
Room name should be updated through out the app

## Actual Result:
Room name is not updated in LHN until another chat/room opened

## Workaround:
Unknown

## Platform:

Where is this issue occurring?

- Web

**Version Number:** 1.2.37.0

**Reproducible in staging?:** Yes

**Reproducible in production?:** Yes

**Email or phone of affected tester (no customers):** 

**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Notes/Photos/Videos:** Any additional supporting documentation

https://user-images.githubusercontent.com/93399543/206594825-6252e965-0115-4343-843e-8112d1e79454.mp4

**Expensify/Expensify Issue URL:** 

**Issue reported by:** Applause - Internal Team

**Slack conversation:** 

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01b4df137e42b2ccf6</li>
        <li>Upwork Job ID: 1601251791178326016</li>
    </ul>
</details>

**Comment by tienifr** [comment] 2022-12-09 08:08
# Proposal

## Problem

In App/src/pages/home/sidebar/SidebarLinks.js
When a reportName of the report is updated. The SidebarLinks component isn't rendered


## Solution

In https://github.com/tienifr/App/blob/216bbe9ff3995264e08a542d618bcc1db12d946f/src/pages/home/sidebar/SidebarLinks.js#L205

we will update the reportName and then when reportName is updated, this component will rendered again and updated the lastest information 
```diff
const chatReportSelector = (report) => {
    if (ReportUtils.isIOUReport(report)) {
        return null;
    }
    return report && ({
        reportID: report.reportID,
        participants: report.participants,
        hasDraft: report.hasDraft,
        isPinned: report.isPinned,
        errorFields: {
            addWorkspaceRoom: report.errorFields && report.errorFields.addWorkspaceRoom,
        },
        maxSequenceNumber: report.maxSequenceNumber,
        lastReadSequenceNumber: report.lastReadSequenceNumber,
        lastMessageText: report.lastMessageText,
        lastActionCreated: report.lastActionCreated,
        iouReportID: report.iouReportID,
        hasOutstandingIOU: report.hasOutstandingIOU,
        statusNum: report.statusNum,
        stateNum: report.stateNum,
        chatType: report.chatType,
        policyID: report.policyID,
+        reportName: report.reportName,
    });
};
```

## Result

https://user-images.githubusercontent.com/113963320/206654970-11c018dc-cd81-40cd-8d72-7d912210d40d.mov

**Comment by tgolen** [comment] 2022-12-09 16:38
🟢 on the proposal from @tienifr. Without the report name being returned there, the LHN will never get updated when the name changes.

**Comment by mananjadhav** [comment] 2022-12-09 17:06
Good with @tienifr's proposal.

**Comment by neil-marcellini** [comment] 2022-12-09 18:34
It looks like this regression was introduced here https://github.com/Expensify/App/commit/d9da2507196128412a5015b4111ab1d448d0d813. I checkout out the parent commit https://github.com/Expensify/App/commit/15e57cd573d2e2651930d155c23cf7603f42147e and verified that the bug did not exist at that point. I think we already have a similar regression test, so we should add this specific case.

https://user-images.githubusercontent.com/26260477/206769223-f868b6ed-93ba-4be1-ad5c-5499a3e22cd2.mov

**Comment by mananjadhav** [comment] 2022-12-11 21:05
Thanks for the update @tienifr. Let's target to get it closed by Dec 12 itself to be eligible for 50% bonus.

**Comment by neil-marcellini** [comment] 2022-12-14 20:27
We're waiting on the fix to be deployed now.

**Comment by mananjadhav** [comment] 2022-12-22 17:52
@zanyrenney This is due for payout today along with the timeline bonus.

**Comment by mallenexpensify** [comment] 2022-12-24 00:27
Hired @tienifr and @mananjadhav can you please accept the job and reply here once you have?

**Comment by mananjadhav** [comment] 2022-12-24 02:51
Accepted @mallenexpensify

**Comment by tienifr** [comment] 2022-12-24 03:07
accepted, thanks @mallenexpensify

**Comment by mallenexpensify** [comment] 2022-12-26 23:49
@tienifr and @mananjadhav paid $1500/each.  Thanks for the quick fix 
Leaving open cuz @zanyrenney needs to add the regression test steps, I'll try to get to this week too.

**Comment by neil-marcellini** [comment] 2022-12-27 18:07
^ we're waiting on the regression tests. I'm commenting to remove the overdue label.

**Comment by neil-marcellini** [comment] 2022-12-29 18:49
Same

**Comment by mananjadhav** [comment] 2023-01-08 18:42
@zanyrenney Did you get a chance to look at the above comments on pending regression steps?

**Comment by zanyrenney** [comment] 2023-01-10 17:47
Sorry! this came in whilst I was OOO for the holidays (26th December). I will look at this now!

**Comment by zanyrenney** [comment] 2023-01-10 18:45
asking for a buddy check for the regression test here - https://expensify.slack.com/archives/C01SKUP7QR0/p1673376310955709?thread_ts=1673376258.732639&cid=C01SKUP7QR0

**Comment by mananjadhav** [comment] 2023-01-12 14:13
thanks for picking this up @zanyrenney.

**Comment by zanyrenney** [comment] 2023-01-20 15:37
Going to bump the QA channel for the regression test.

**Comment by zanyrenney** [comment] 2023-01-30 12:23
Bumped the issue again. https://github.com/Expensify/Expensify/issues/254153

**Comment by neil-marcellini** [comment] 2023-02-07 21:21
Looks like the regression tests were added. Have we paid everyone? If so I think we can close this.

**Closed** 2023-02-08 23:11 UTC
Labels: External, Weekly, Awaiting Payment, Bug
