### ISSUE TITLE
[HOLD for payment 2023-08-02] [$1000] The cursor position is not at the end of the message when editing the welcome message

### ISSUE THREAD

**Issue by kavimuru** [Expensify/App#21523] opened 2023-06-25 15:38 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:

1. Create a room
2. Go to the room details > settings and select "Welcome Message"
3. Enter a message and click on "Save"
4. Once again, click on the welcome message for editing

## Expected Result:
The cursor position should be at the end of the message when editing the welcome message

## Actual Result:
The cursor is at the start of the message

## Workaround:
Can the user still use Expensify without this being fixed? Have you informed them of the workaround?

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [x] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 1.3.32-5
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/43996225/4e8a7bd2-bb7c-4d97-8e15-aff3c7a54a6d

https://github.com/Expensify/App/assets/43996225/cc412ff3-863c-4dc3-84fe-07f8a2996595

**Expensify/Expensify Issue URL:**
**Issue reported by:** @ayazhussain79 
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1687255221337649

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01c431cd4d3b60ebff</li>
        <li>Upwork Job ID: 1674581546420617216</li>
        <li>Last Price Increase: 2023-07-14</li>
    </ul>
</details>

**Comment by sakluger** [comment] 2023-06-27 04:24
@Expensify/design do you think this is a bug? I'm leaning towards yes, but wanted a second opinion.

**Comment by shawnborton** [comment] 2023-06-27 10:52
Wow, what a find. Yeah, I guess it makes sense that the cursor starts off at the end as opposed to the beginning.

**Comment by sakluger** [comment] 2023-06-30 00:51
Alright let's do this thing. Adding the external label.

**Comment by fabriziobertoglio1987** [comment] 2023-07-03 13:04
Navigation.goBack unmounts the component and clears the state (value and selection)

https://reactnavigation.org/docs/navigation-lifecycle/#example-scenario
snack https://snack.expo.dev/@fabrizio.bertoglio/navigation-prop-reference-|-react-navigation
issue https://github.com/react-navigation/react-navigation/issues/1953

**Comment by shawnborton** [comment] 2023-07-03 13:14
Not overdue, still looking at proposals.

**Comment by mollfpr** [comment] 2023-07-03 14:54
@chiragxarora It has the same result as using `focusAndUpdateMultilineInputRange`, so I want to keep using it.

@hoangzinh The input needs to be focused after refreshing the page.

**Comment by mollfpr** [comment] 2023-07-05 04:34
Sorry for the delay. I'll review the proposals today 🙏

**Comment by mollfpr** [comment] 2023-07-10 03:48
> We can't also put welcomeMessageInputRef.current to useEffect dependency list because it's mutation variable so mutate it won't trigger re-render page => not recommended from React community.

@chiragxarora As mentioned by @hoangzinh we can't use the ref for the dependency in the `useEffect`. It will better we have a proposal that avoids that.

@hoangzinh I'm still inclined to use `onEntryTransitionEnd` and avoid the `setTimeout` usage for this issue.

**Comment by mollfpr** [comment] 2023-07-10 06:26
@hoangzinh I try your proposal quickly without the timeout, but we have some issues with the rendering of the next page.
 
https://github.com/Expensify/App/assets/25520267/3525599a-e435-494a-a20e-27aa41df6522

Is there any way we can avoid using a timeout?

**Comment by mollfpr** [comment] 2023-07-12 16:11
Sorry I got a problem with updating the NPM, I'll be posting an update in the morning.

**Comment by mollfpr** [comment] 2023-07-15 08:04
@hoangzinh I am interest in your alternative approach 1, but it's still not working on refreshing the browser.

**Comment by mollfpr** [comment] 2023-07-17 06:31
@hoangzinh I misplace the `welcomeMessageInputRef.current = el;` so that's why it's not working 😅

The alternative 1 in @hoangzinh [proposal](https://github.com/Expensify/App/issues/21523#issuecomment-1614625854) looks good to me!

🎀 👀 🎀 C+ reviewed!

**Comment by danieldoglas** [comment] 2023-07-18 14:25
https://github.com/Expensify/App/pull/22586 is in staging now, we should test it before we continue with the assignment for this issue.

**Comment by sakluger** [comment] 2023-07-18 18:31
I just tested on staging and confirmed that this bug is still reproduceable. @danieldoglas do you agree that we should assign @hoangzinh?

**Comment by jasperhuangg** [comment] 2023-07-18 22:24
Yep, https://github.com/Expensify/App/pull/22586 is unrelated to this issue, so we should continue with the triage process.

**Comment by sakluger** [comment] 2023-07-24 23:59
This one just got merged, thanks everyone! Looks like it was merged in 4 business days.

**Comment by sakluger** [comment] 2023-08-04 00:22
**Summarizing payouts for this issue:**

Bug reporter: @ayazhussain79 $250 (hired on Upwork)
Contributor: @hoangzinh $1000 (hired on Upwork)
Contributor+: @mollfpr $1000 (hired on Upwork)

Upwork job: https://www.upwork.com/jobs/~01c431cd4d3b60ebff

**Comment by sakluger** [comment] 2023-08-04 00:22
@ayazhussain79 I forgot to send you an offer previously, sorry about that! I just sent you a contract through Upwork, please let me know once you have accepted the offer.

**Comment by ayazhussain79** [comment] 2023-08-04 07:23
@sakluger offer accepted, Thank you

**Comment by sakluger** [comment] 2023-08-04 16:12
Thanks @ayazhussain79!

**Closed by sakluger** 2023-08-04 16:12 UTC
Labels: External, Engineering, Daily, Awaiting Payment, Bug
