### ISSUE TITLE
[Hold - #15992] All message boxes lose focusing when clicking on Report a bug link

### ISSUE THREAD

**Issue by izarutskaya** [Expensify/App#26353] opened 2023-08-30 22:38 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Open website > Settings > About > Click on Report a bug

## Expected Result:
All message boxes should not lose focusing when clicking on Report a bug link

## Actual Result:
All message boxes lose focusing when clicking on Report a bug link

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [x] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** v1.3.59-0

**Reproducible in staging?:** Y

**Reproducible in production?:** Y

**If this was caught during regression testing, add the test name, ID and link from TestRail:**

**Email or phone of affected tester (no customers):**

**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/115492554/27ef8686-cfe5-4fed-bd05-43f87d6d1d15

https://github.com/Expensify/App/assets/115492554/bc7047ea-718f-4c73-acd1-81082c8f2e7c

**Expensify/Expensify Issue URL:**

**Issue reported by:** @mahmudjontoraqulov

**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1692593482423179

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by alphaboss1104** [comment] 2023-08-31 02:05
## Proposal
### Please re-state the problem that we are trying to solve in this issue.

All message boxes lose focusing when clicking on Report a bug link

### What is the root cause of that problem?

When click on Report a bug the app navigate to the `Concierge` chat page.

https://github.com/Expensify/App/blob/c20c3870ee46d6788de554be27706e9898638904/src/libs/actions/Report.js#L1312

But there’s no explicit focus management after navigation, so focus is not automatically set to a specific field unless specified.
This is the root cause of this issue.

### What changes do you think we should make in order to solve the problem?

One approach is that add explicit focus management after navigation.
We can achieve this by using the `useEffect` hook in the `ReportActionCompose.js` to set the focus to the compose input when the component is mounted. This will ensure the compose input gets focus after navigation.

```js
    useEffect(() => {
        if (shouldFocusInputOnScreenFocus && shouldShowComposeInput) {
            focus();
        }
    }, [shouldFocusInputOnScreenFocus, shouldShowComposeInput]);
```

### What alternative solutions did you explore? (Optional)

**Comment by NicMendonca** [comment] 2023-08-31 17:04
@fedirjh do you think this is the same root cause of https://github.com/Expensify/App/issues/21401?

**Comment by NicMendonca** [comment] 2023-09-14 18:17
still holding

**Comment by NicMendonca** [comment] 2023-09-26 14:17
^^

**Comment by NicMendonca** [comment] 2023-10-05 21:04
https://github.com/Expensify/App/issues/15992 is monthly, so moving this to monthly

**Comment by NicMendonca** [comment] 2023-11-28 14:51
^^ waiting on https://github.com/Expensify/App/issues/15992

**Comment by NicMendonca** [comment] 2024-01-11 15:12
I'm going to close this for now because its so old. https://github.com/Expensify/App/issues/15992 is still open

**Closed by NicMendonca** 2024-01-11 15:12 UTC
Labels: Monthly, Overdue, Bug
