### ISSUE TITLE
[HOLD for payment 2023-10-09] [HOLD for payment 2023-10-6] [$500]  Request money - Extra 0 digit in the amount and app crashes when requesting money

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#28417] opened 2023-09-28 20:38 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___
Issue found when executing #27947
## Action Performed:
1. Launch New Expensify app
2. Tap + > Request money > Enter any amount > Next
3. Scroll down the list

## Expected Result:
In Step 2, there will be no extra digit in the amount when the amount is entered
In Step 3, app does not crash

## Actual Result:
In Step 2, an extra zero is present in the amount when the amount is entered
In Step 3, app crashes

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android / native
- [ ] Android / Chrome
- [x] iOS / native
- [ ] iOS / Safari
- [ ] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 1.3.75-0

**Reproducible in staging?:** Yes

**Reproducible in production?:** No

**If this was caught during regression testing, add the test name, ID and link from TestRail:**

**Email or phone of affected tester (no customers):**

**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/78819774/ed0235b0-3247-4284-b04b-f2c8ccbc18b8

[logs (2).txt](https://github.com/Expensify/App/files/12753752/logs.2.txt)

**Expensify/Expensify Issue URL:**

**Issue reported by:** Applause - Internal Team

**Slack conversation:**

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01a79e0073f0180ad2</li>
        <li>Upwork Job ID: 1707681379393409024</li>
        <li>Last Price Increase: 2023-09-29</li>
<li>Automatic offers: </li>
<ul>
<li>cubuspl42 | Contributor | 26963452</li>
</ul></li>
    </ul>
</details>

**Comment by pradeepmdk** [comment] 2023-09-28 23:17
due to this PR started crashing https://github.com/Expensify/react-native-onyx/pull/329/files

**Comment by tgolen** [comment] 2023-09-29 08:03
@ospfranco Do you think it's related? I'm not seeing the connection necessarily, but if it is related, can you come up with a fix?

**Comment by tgolen** [comment] 2023-09-29 08:03
@pradeepmdk Can you please share how you determined that was the PR?

**Comment by pradeepmdk** [comment] 2023-09-29 08:09
@tgolen when you go to request money it will throw the `setWithOnyxState`  error.
![Screenshot 2023-09-29 at 1 36 35 PM](https://github.com/Expensify/App/assets/16595846/43a681b0-2010-4a87-afd1-91a95e2376c8)

Note: @ospfranco started working on this 
https://github.com/Expensify/App/issues/28419#issuecomment-1740392217

**Comment by cubuspl42** [comment] 2023-09-29 09:43
Yes, it looks like it...

@dukenv0307 Are you available to submit a follow-up PR?

**Comment by cubuspl42** [comment] 2023-09-29 09:49
...and I overlooked that 🙈

**Comment by kbecciv** [comment] 2023-09-29 17:47
Issue is not reproduced on build 1.3.75.2

https://github.com/Expensify/App/assets/93399543/e4dd4a74-1114-4869-a2c8-c93a01b2b406

**Comment by kavimuru** [comment] 2023-09-29 21:02
@aimane-chnaif Yes, still the extra 0 is reproducible.

**Comment by mountiny** [comment] 2023-10-01 08:04
<img width="458" alt="image" src="https://github.com/Expensify/App/assets/36083550/cc2c576d-978c-45b1-b3f7-d0a7c1243f2e">

fixed in staging, no payment here since the authors of regression fixed it

**Comment by mountiny** [comment] 2023-10-01 08:44
25% so $125 to @dukenv0307 for the solution which was used cc @jliexpensify please, thanks!

**Comment by jliexpensify** [comment] 2023-10-03 03:19
Payment Summary [here](https://github.com/Expensify/App/issues/28417#issuecomment-1742008867)

Invited!

**Comment by jliexpensify** [comment] 2023-10-03 04:52
Paid, and job closed!

**Closed by jliexpensify** 2023-10-03 04:52 UTC
Labels: External, Engineering, Weekly, Awaiting Payment, Bug
