### ISSUE TITLE
[$500] IOU–Finished Receipt Scanning has whisper 'Only visible to you' if create it in new workspace

### ISSUE THREAD

**Issue by izarutskaya** [Expensify/App#42277] opened 2024-05-16 11:51 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** v1.4.74-1
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**If this was caught during regression testing, add the test name, ID and link from TestRail:** https://expensify.testrail.io/index.php?/tests/view/4562917
**Email or phone of affected tester (no customers):** applausetester+jp_e_category_1@applause.expensifail.com
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Issue reported by:** Applause-Internal team

## Action Performed:
1. Go to https://staging.new.expensify.com/
2. Log in as Employee of a new Collect workspace.
3. Navigate to the workspace chat
4. Select the option to Submit expense &gt; Scan receipt
5. Select the option to upload a receipt
6. Upload a receipt file
7. Click on Submit expense

## Expected Result:
Whisper 'Only visible to you' appears when receipt is scanning and disappears when scanning is finished

## Actual Result:
Whisper 'Only visible to you' appears only after scanning is finished and not disappears. Admin can’t see finished scanning.

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [x] Android: mWeb Chrome
- [ ] iOS: Native
- [x] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

https://github.com/Expensify/App/assets/115492554/ea735f3a-38d0-45f0-866c-e9db88f88bfd

![Bug6482398_1715839469282!Receipt_Example2](https://github.com/Expensify/App/assets/115492554/c5ee7fd2-9009-4dd5-bc58-1b021066a1b4)

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~0150a29c219ff1ecec</li>
        <li>Upwork Job ID: 1792357207472001024</li>
        <li>Last Price Increase: 2024-06-20</li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @sobitneupane</details>

**Comment by izarutskaya** [comment] 2024-05-16 11:53
We think this issue might be related to the #collect project.

**Comment by jliexpensify** [comment] 2024-05-20 00:51
This is a bug because logically, `only visible to you` should disappear after a successful SmartScan.

**Comment by jliexpensify** [comment] 2024-05-24 01:53
Waiting for proposals.

**Comment by sobitneupane** [comment] 2024-05-24 03:42
Waiting for proposals.

**Comment by sobitneupane** [comment] 2024-05-28 06:27
Waiting for proposals.

**Comment by sobitneupane** [comment] 2024-05-31 05:42
Waiting for proposals.

**Comment by jliexpensify** [comment] 2024-06-04 05:33
Hmm @sobitneupane @izarutskaya can you repro this? I tested on a Collect Workspace and scanned a receipt today and am not seeing the whisper anymore.

**Comment by jliexpensify** [comment] 2024-06-06 02:59
Not overdue, but can you repro this @sobitneupane @izarutskaya ?

**Comment by jliexpensify** [comment] 2024-06-06 03:18
Not overdue

**Comment by sobitneupane** [comment] 2024-06-06 16:06
@jliexpensify I can still reproduce the issue. The whisper "Only visible to you" appears after some time and remains visible even after the receipt is scanned.

https://github.com/Expensify/App/assets/25876548/ff23d967-1904-4a03-ba9c-a9834f1a8e09

**Comment by jliexpensify** [comment] 2024-06-07 00:40
Thanks, going to get this posted to the Open Source channel to try and grab someone!

**Comment by sobitneupane** [comment] 2024-06-11 06:21
Waiting on proposal.

**Comment by jliexpensify** [comment] 2024-06-13 23:33
Increased the bounty

**Comment by sobitneupane** [comment] 2024-06-14 07:14
Waiting on proposal.

**Comment by jp928** [comment] 2024-06-14 14:58
Proposal
Please re-state the problem that we are trying to solve in this issue.
Whisper 'Only visible to you' should disappear when scanning is finished

What is the root cause of that problem?
in the src/libs/ReportActionsUtils.ts::getWhisperedTo, the logic relies on `originalMessage`.
<img width="2013" alt="Screenshot 2024-06-15 at 12 58 15 AM" src="https://github.com/Expensify/App/assets/659612/d99cea5f-8930-4206-ab06-83c6fa967845">

What changes do you think we should make in order to solve the problem?
Update the function `getWhisperedTo` relies on `reportAction?.message` only

What alternative solutions did you explore? (Optional)
NA

**Comment by jliexpensify** [comment] 2024-06-18 03:07
Hi @sobitneupane we have our first proposal 😓 any thoughts?

**Comment by M00rish** [comment] 2024-06-18 12:16
**Please re-state the problem that we are trying to solve in this issue.**

Whisper 'Only visible to you' does not disappear when scanning is finished

**What is the root cause of that problem?**

when receipt is submitted the report is created optimistically, using `buildOptimisticIOUReportAction` function, since the receipt is still in `SCANREADY` or `SCANNING` state, the `whisperedTo` Array is assigned the current user ID.
https://github.com/Expensify/App/blob/8dea185bbc1431fb9c268a7ce74e1045d930cb0e/src/libs/ReportUtils.ts#L4096-L4104 but in [ReportActionItem](https://github.com/Expensify/App/blob/main/src/pages/home/report/ReportActionItem.tsx) there's no checking happening when the `transaction.receipt.state` changes and scanning is successful (or not) to re-render `ReportActionItem` and reflect changes

**What changes do you think we should make in order to solve the problem?**

in [ReportActionItem](https://github.com/Expensify/App/blob/main/src/pages/home/report/ReportActionItem.tsx) we should subscribe to changes in `Transaction.receipt.state` in  onyx so once the scanning is done we trigger the rendering of `ReportActionItem`  using `renderReportActionItem` with a  hook like useMemo to reflect changes in state

**What alternative solutions did you explore? (Optional)**
N/A

**Comment by sobitneupane** [comment] 2024-06-19 07:47
Thanks for your [proposal](https://github.com/Expensify/App/issues/42277#issuecomment-2175959493) @M00rish 

> there's no checking happening when the transaction.receipt.state changes and scanning is successful (or not) to re-render ReportActionItem and reflect changes

I am not sure if that's the case as the issue can still be reproduced after the page re-renders.

Can you please include pseudocode on how you will implement the solution you suggested.

**Comment by M00rish** [comment] 2024-06-19 21:24
actually, the issue is no longer reproducible on staging... it seems fixed I guess.

**Comment by jliexpensify** [comment] 2024-06-19 22:28
Oh nice - @M00rish did you manage to grab a video?

**Comment by M00rish** [comment] 2024-06-20 19:14
@jliexpensify not really if you still need it I might be able to make one tonight

**Comment by jliexpensify** [comment] 2024-06-25 02:51
@sobitneupane can you repro this any more? I can't seem to.

**Comment by sobitneupane** [comment] 2024-06-27 07:38
@jliexpensify I cannot reproduce the issue any longer.


https://github.com/Expensify/App/assets/25876548/f3977381-a1a1-4744-874c-647bcf3e63e1

**Comment by jliexpensify** [comment] 2024-06-27 08:09
Ok, lets close this!

**Closed by jliexpensify** 2024-06-27 08:09 UTC
Labels: External, Daily, Help Wanted, Bug
