### ISSUE TITLE
[HOLD #11768] mWeb-lands on wrong screen when pressing the back button from the attachment screen @gadhiyamanan

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#11372] opened 2022-09-28 15:58 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Go to staging.new.expensify.com
2. Log in with any account
3. Go to any chat
4. Click on any attachment
5. Press back button

## Expected Result:
Should navigate to chat screen

## Actual Result:
Navigate to home screen

## Workaround:
Unknown

## Platform:

Where is this issue occurring?

- Mobile Web

**Version Number:** 1.2.8.0

**Reproducible in staging?:** Yes

**Reproducible in production?:** Yes

**Email or phone of affected tester (no customers):** any

**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Notes/Photos/Videos:** Any additional supporting documentation

https://user-images.githubusercontent.com/93399543/192828067-768bb622-624c-4934-a720-15ed09992f93.mp4

**Expensify/Expensify Issue URL:** 

**Issue reported by:** @gadhiyamanan

**Slack conversation:** https://expensify.slack.com/archives/C01GTK53T8Q/p1663057441323579

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by thesahindia** [comment] 2022-09-28 16:19
Dupe of https://github.com/Expensify/App/issues/7010 and it was decided to close it (check the reason [here](https://github.com/Expensify/App/issues/7010#issuecomment-1018194823))

**Comment by alexpensify** [comment] 2022-09-28 20:22
Assigning to Engineering for the check if this one should be closed or give it another review. 

cc: @roryabraham and @stitesExpensify

**Comment by stitesExpensify** [comment] 2022-09-28 20:35
Hmm so the problem is that the attachment picker is not really a new page, it's the same page with a modal on it, so the back button is technically functioning correctly. IMO this is not a bug, it's user error. If they hit the `x` everything will work fine. The only reason it's confusing is because it _looks_ like a different page, but that's not something we want to fix right now IMO

**Comment by stitesExpensify** [comment] 2022-09-28 20:44
If we do want to fix this, we could artificially add the report page a second time to react-navigation, but that could also cause problems where the flow is:
1. Navigate to report
2. Hit add attachment
3. Click the x
4. Hit back button
5. You stay on the same page
6. Hit back again and you actually go back.

So we would need to artificially add it when you click "add attachment" and then remove it when you hit the "x". Again I think that's not worth it though, happy to hear other opinions

**Comment by roryabraham** [comment] 2022-09-29 17:35
cc @puneetlath because this is react-navigation related I'm thinking we should put it on HOLD pending the FT you're working on

**Comment by cristipaval** [comment] 2022-09-29 21:23
removed the assignment since I see you guys are already triaging it. Thanks!

**Comment by roryabraham** [comment] 2022-09-29 23:24
Putting this on HOLD and added to tracking issue: https://github.com/Expensify/Expensify/issues/221853

**Comment by slafortune** [comment] 2022-10-18 21:43
https://www.upwork.com/ab/applicants/1582487212083625984/job-details

**Comment by roryabraham** [comment] 2022-10-19 05:57
@slafortune It looks like you may have been a bit over-eager to create an Upwork job for this 🙂 

We only create Upwork jobs for issues that have been labelled `External`. This particular issue is on HOLD, so let's take the Upwork job down for now. Thanks!

**Comment by slafortune** [comment] 2022-10-19 19:10
Ah Shoot!  Yes, you are correct!  I removed it!  Also, way over-eager because I agree the back arrow should get you back to the previous page and selecting the X does close out the open attachment as expected.  What I was able to reproduce was on iPhone mobile web the back arrow locks up the app when an attachment is open.  But not true if you first close the attachment with the X.

https://user-images.githubusercontent.com/11725910/196782353-aaee87de-f719-4d4f-9952-bdcf0d6c289e.MP4

**Comment by puneetlath** [comment] 2022-10-21 17:37
Jason will be the BZ person for navigation issues, so assigning to him.

**Comment by JmillsExpensify** [comment] 2022-10-21 21:58
Assigning myself so that I can work with Puneet on the larger issue which is currently blocking this one.

**Comment by JmillsExpensify** [comment] 2022-10-21 21:59
And....I'm just seeing Puneet's comment above. Thanks Github.

**Comment by JmillsExpensify** [comment] 2022-10-26 17:16
Still on hold for the linked, larger initiative.

**Comment by JmillsExpensify** [comment] 2022-11-01 18:53
Still holding on the linked initiative. Also commented there to align on game plan and next steps.

**Comment by JmillsExpensify** [comment] 2022-11-16 05:11
Still on hold Melvin

**Comment by JmillsExpensify** [comment] 2022-11-22 07:09
Still held as we go through the design process.

**Comment by JmillsExpensify** [comment] 2022-11-27 06:29
On hold per the larger react navigation initiative.

**Comment by JmillsExpensify** [comment] 2022-12-05 13:40
Still on hold for the larger navigation re-write.

**Comment by JmillsExpensify** [comment] 2022-12-12 12:34
Still on hold for navigation.

**Comment by JmillsExpensify** [comment] 2022-12-19 01:43
Held on navigation revamp

**Comment by JmillsExpensify** [comment] 2022-12-27 20:13
Switching out the weekly for monthly given that the navigation project is large and has no ETA.

**Comment by JmillsExpensify** [comment] 2023-01-11 05:45
Still on hold for the navigation project.

**Comment by JmillsExpensify** [comment] 2023-02-14 06:17
Same same.

**Comment by JmillsExpensify** [comment] 2023-03-29 07:28
Still on hold.

**Comment by JmillsExpensify** [comment] 2023-05-03 05:01
Still on hold

**Comment by JmillsExpensify** [comment] 2023-06-07 05:04
Coming off hold very soon!

**Comment by mountiny** [comment] 2023-06-22 14:07
This is not its own screen so I dont think this will be fixed and I am not sure if we should be fixing it in terms of consistency wit desktop. There the attachment is also a modal and not its own page.

**Comment by JmillsExpensify** [comment] 2023-07-12 13:26
Ok cool, still aiming to get to this one this week.

**Comment by JmillsExpensify** [comment] 2023-08-16 13:56
Still trying to make time. Low priority.

**Comment by JmillsExpensify** [comment] 2023-10-10 18:03
Re-tested and this is now fixed.

**Comment by JmillsExpensify** [comment] 2023-10-10 18:05
@gadhiyamanan I just sent you an offer for reporting. Once you've accepted and been paid, we can close this one out.

**Comment by gadhiyamanan** [comment] 2023-10-11 02:57
@JmillsExpensify offer accepted, thanks!

**Comment by JmillsExpensify** [comment] 2023-10-11 14:39
Anytime. All paid out!

**Closed by JmillsExpensify** 2023-10-11 14:39 UTC
Labels: Engineering, Monthly, Bug
