### ISSUE TITLE
[$250] Chat - mWeb - Send button is activated only after entering a space

### ISSUE THREAD

**Issue by IuliiaHerets** [Expensify/App#49486] opened 2024-09-19 19:14 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 9.0.38-0
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**Issue reported by:** Applause Internal Team

## Action Performed:
1. Go to https://staging.new.expensify.com/home
2. Open a chat
3. Enter a text
4. Note send button not activated
5. Enter a space
6. Now note send button is activated

## Expected Result:
Send activated after entering few characters.

## Actual Result:
Send button is activated in mweb only after entering a space.
Issue occurs when using the device's own keyboard.

## Workaround:
Unknown

## Platforms:

- [ ] Android: Native
- [x] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [ ] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

https://github.com/user-attachments/assets/0b88bd41-2053-4f49-8b6d-5714b11b76f5

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~021836866672094965087</li>
        <li>Upwork Job ID: 1836866672094965087</li>
        <li>Last Price Increase: 2024-10-10</li>
<li>Automatic offers: </li>
<ul>
<li>allgandalf | Contributor | 104090050</li>
</ul></li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @allgandalf</details>

**Comment by IuliiaHerets** [comment] 2024-09-19 19:15
@zanyrenney  FYI I haven't added the External label as I wasn't 100% sure about this issue. Please take a look and add the label if you agree it's a bug and can be handled by external contributors

**Comment by mattmoreira** [comment] 2024-09-20 05:52
## Proposal

### Please re-state the problem that we are trying to solve in this issue.

Fix send button being activated only after entering a space on Chrome for Android

### What is the root cause of that problem?

When typing using Android's keyboard, only the `input` event is triggered, while pressing space or typing using an external keyboard activates the `textInput` event, which enables the send button.

That's likely caused by a difference on how `onChange` and `onChangeText` are handled by the `TextInput` component on web.

https://github.com/user-attachments/assets/fb813f1b-988d-4862-8919-aba2698f5358

### What changes do you think we should make in order to solve the problem?

Replace the usage of `onChangeText` by `onChange` on the line below:
https://github.com/Expensify/App/blob/main/src/pages/home/report/ReportActionCompose/ComposerWithSuggestions/ComposerWithSuggestions.tsx#L773

**Comment by mattmoreira** [comment] 2024-09-20 05:56
Contributor details

Your Expensify account email: matheus.moreira@pixelias.io
Upwork Profile Link: https://www.upwork.com/freelancers/~011382b37ba6ccea27?mp_source=share

**Comment by bondydaa** [comment] 2024-09-20 15:11
@paultsimura can you checkout the staging branch and production tags and confirm its reproducible there?

**Comment by mattmoreira** [comment] 2024-09-20 16:13
@bondydaa and @paultsimura, I had already reproduced the bug, please check my prior comment in thread where I issued a proposal on how to fix this.

**Comment by mattmoreira** [comment] 2024-09-20 19:14
@allgandalf I'll explain later why I proposed to use onChange instead of onChangeText.

Regarding why it happens only on Chrome for Android, I suspect it's related to the following issue that was reported on Chromium bug tracker:

https://issues.chromium.org/issues/41403652

**Comment by mattmoreira** [comment] 2024-09-21 05:50
Ok, now I'll provide more details answer:

### Why the issue only happens on Chrome for Android?

Chrome on Android uses Blink as a rendering engine, while for iOS, Chrome works basically as a reskinned version of Safari:
https://news.ycombinator.com/item?id=25850091

Also, according to [this](https://issues.chromium.org/issues/41081506#comment5) comment on Chromium's bug tracker, the `textInput` event is behaving as intended by not "committing" the new character until space is pressed, as the string might be changed by the autocorrector.

That doesn't happen on desktop because we use real keyboards for typing, while Gboard acts as an input method (IME), having complete control of when the string actually gets sent to the element.

### Why `onChangeText` is being used?

The biggest difference between `onChangeText` and `onChange` is that the first only returns the string that was input, while the latter returns the synthetic event, but both are triggered by the same event. So yes, you're correct, replacing `onChangeText` to `onChange` wouldn't solve the issue.

Also, it seems that the element is not actually an `input`, but rather a content editable `div`. This explains why the real `change` event wasn't used, as it doesn't work with `div`s.

### Are there any alternatives?

Another solution would be to use `onKeyPress` to identify when the element has changed, and then grab the new value using `innerText` on the target element.

https://stackoverflow.com/a/73238998

**Comment by klajdipaja** [comment] 2024-09-23 15:36
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
In the chat the send button is not enabled when the user starts typing on mobile browsers
### What is the root cause of that problem?
The root cause of the issue is mobile keyboard behavior's when text prediction is enabled. I have tested this one the mobile chrome browser with the google gBoard and Samsung keyboard on S22FE and only in the samsung keyboard I've been able to reproduce the issue. 
The Google keyboard generates when typing events with eventType=input and inputType=insertText.
The Samsung keyboard generates when typing events with eventType=input and inputType=insertCompositionText.
Due to the inputType being wrong in the event it is not being picked up by react with the onInput event which is what the `react-native-live-markdown` library use to expose the onChangeText.
We need to fix this in the live markdown library.


### What changes do you think we should make in order to solve the problem?
We can leverage the composition events to get the text by adding a listener to `onCompositionUpdate` in this line:
https://github.com/Expensify/react-native-live-markdown/blob/a70e8570658a3654aa34d7817188474890c1fe15/src/MarkdownTextInput.web.tsx#L688

The event would use an `updateComposition` function to update the text by calling the `onChangeText` function:

```
const updateComposition = useCallback(
      (e) => {
        handleOnChangeText(e);
      },
      [handleOnChangeText],
    );
    ```
### What alternative solutions did you explore? (Optional)

**Comment by bondydaa** [comment] 2024-09-23 15:53
dang it, that's what I was trying to avoid 🤦 guess i should have taken `external` off as well before try to re-assign?

**Comment by bondydaa** [comment] 2024-09-23 15:54
anyways @allgandalf you're the c+ assigned now, we can get the job stuff figured out when Zany is back tomorrow b/c now I'm not sure what I need to do.

**Comment by mattmoreira** [comment] 2024-09-23 16:17
> No hurry !! Still waiting for proper proposals

@allgandalf I tried to address [here](https://github.com/Expensify/App/issues/49486#issuecomment-2365015239) the points that were unclear, could you please provide me guidance on what other areas would you like to be clarified in my proposal?

**Comment by bernhardoj** [comment] 2024-09-24 12:31
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
Send button is only enabled when adding white space to the composer.

### What is the root cause of that problem?
The send button will be enabled if the `isCommentEmpty` state is false. We update the state inside the `updateComment` function.
https://github.com/Expensify/App/blob/accea60e318386b02971baab3a563160ce8259b5/src/pages/home/report/ReportActionCompose/ComposerWithSuggestions/ComposerWithSuggestions.tsx#L432-L434

`updateComment` is called from the composer `onChangeText`.
https://github.com/Expensify/App/blob/accea60e318386b02971baab3a563160ce8259b5/src/pages/home/report/ReportActionCompose/ComposerWithSuggestions/ComposerWithSuggestions.tsx#L509-L511

However, the `onChangeText` isn't called. This is because, in the live markdown component, if `compositionRef` is true, then we return early which never reaches the `onChangeText` calls.
https://github.com/Expensify/react-native-live-markdown/blob/a70e8570658a3654aa34d7817188474890c1fe15/src/MarkdownTextInput.web.tsx#L307-L316

`compositionRef` is true when we start typing, only if the auto-correct of the keyboard is enabled. It becomes false when we press space which ends the composition (it triggers onCompositionEnd event).

### What changes do you think we should make in order to solve the problem?

We need to trigger `onChangeText` even when `compositionRef` is true, the same we trigger selection change event (`updateSelection`).
https://github.com/Expensify/react-native-live-markdown/blob/a70e8570658a3654aa34d7817188474890c1fe15/src/MarkdownTextInput.web.tsx#L307-L315

```
if (compositionRef.current) {
  updateTextColor(divRef.current, parsedText);
  updateSelection(e, {
    start: newCursorPosition,
    end: newCursorPosition
  });
  if (onChangeText) {
    onChangeText(parsedText);
  }
  ...
```

**Comment by zanyrenney** [comment] 2024-09-26 11:14
@allgandalf are you able to review the proposal from @bernhardoj please?

**Comment by zanyrenney** [comment] 2024-09-26 11:14
Just an FYI I'll be OOO until Tuesday 1st, please reapply the bug label if this needs urgent action in my absence. Otherwise I will get to it when I return. Thanks!

**Comment by zanyrenney** [comment] 2024-10-04 13:15
added to the collect project as a key feature of admins needing to pay, is paying. Added to polish.

**Comment by bondydaa** [comment] 2024-10-07 20:08
@allgandalf any updates?

**Comment by bondydaa** [comment] 2024-10-10 16:56
just tested on staging and i don't see it, closing this out.

**Closed by bondydaa** 2024-10-10 16:56 UTC
Labels: External, Daily, Help Wanted, Overdue, Bug
