### ISSUE TITLE
[Hold for Payment] [$500] LHN - Red dot appears even if request is paid

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#28928] opened 2023-10-05 15:51 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Click on FAB icon and select request money option
2. Go to scan tab and add receipt
3. Select user and click on request button
4. Go to transaction thread and click on amount and enter amount
5. Which will show red dot because merchant name is pending
6. Pay that request
7. Check the LHN

## Expected Result:
Red dot appears

## Actual Result:
 Red dot should not appears if request is paid

## Workaround:
Unknown 

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android / native
- [x] Android / Chrome
- [x] iOS / native
- [x] iOS / Safari
- [x] MacOS / Chrome / Safari
- [x] MacOS / Desktop

**Version Number:** 1.3.78.0
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/93399543/e34be054-c3ac-4bcc-93c5-e2d93baf4225

https://github.com/Expensify/App/assets/93399543/e7c4a1c9-7d1b-4713-832a-fcd07ca3acf7

https://github.com/Expensify/App/assets/93399543/514660ab-c675-4d16-896c-e80377da4055

https://github.com/Expensify/App/assets/93399543/2acfd187-2bb4-4ed1-a201-ac7513fb40fb

https://github.com/Expensify/App/assets/93399543/a619b8e4-0b5b-47ed-a2fc-4b4eb5eddc3a

https://github.com/Expensify/App/assets/93399543/ccfa2c9c-82e2-42b4-be53-0bc5dddd09aa

https://github.com/Expensify/App/assets/93399543/bd12cc2b-9319-45cd-99f5-fe980356be82

**Expensify/Expensify Issue URL:**
**Issue reported by:** @gadhiyamanan
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1696495620605549

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by c3024** [comment] 2023-10-05 15:52
## Proposal
### Please re-state the problem that we are trying to solve in this issue.
Red dot does not disappear even after settling a money request.
### What is the root cause of that problem?
We are showing red dot when there are errors 
https://github.com/Expensify/App/blob/567c32e56a449100cebb83af560aa1fcb07daf09/src/components/ReportActionItem/ReportPreview.js#L196-L201
and when there are missing smartscan fields `hasErrors` is `true`. So the red indicator appears here. This is same for `MoneyRequestPreview` and `getAllReportErrors` of `OptionListUtils`.
### What changes do you think we should make in order to solve the problem?
We should check if the IOU is settled before checking if `hasErrors` is `true` and displaying the red dot.
So, we should change this here 
https://github.com/Expensify/App/blob/567c32e56a449100cebb83af560aa1fcb07daf09/src/components/ReportActionItem/ReportPreview.js#L196
to
```js
!iouSettled && hasErrors
```
We should change this here
https://github.com/Expensify/App/blob/567c32e56a449100cebb83af560aa1fcb07daf09/src/components/ReportActionItem/MoneyRequestPreview.js#L269-L274
to
```js
{!isSettled && hasFieldErrors && (
```
and
we should change this here
https://github.com/Expensify/App/blob/567c32e56a449100cebb83af560aa1fcb07daf09/src/libs/OptionsListUtils.js#L356-L359
to
```js
            const isSettled = ReportUtils.isSettled(iouReportID);
            // Instead of adding all Smartscan errors, let's just add a generic error if there are any. This
            // will be more performant and provide the same result in the UI
            if (!isSettled && ReportUtils.hasMissingSmartscanFields(iouReportID)) {
                _.extend(reportActionErrors, {smartscan: ErrorUtils.getMicroSecondOnyxError('report.genericSmartscanFailureMessage')});
```
so this does not add an error to the option row when the error is a missing smart scan field for a settled IOU.
### What alternative solutions did you explore? (Optional)

**Comment by DylanDylann** [comment] 2023-10-06 04:32
Maybe relate to this PR https://github.com/Expensify/App/pull/27494

**Comment by abdulrahuman5196** [comment] 2023-10-06 11:31
Taking a look now

**Comment by Gonals** [comment] 2023-10-09 10:42
> @Gonals Will this be fixed in the PR? - #27494

Probably

**Comment by abdulrahuman5196** [comment] 2023-10-09 11:37
@greg-schroeder Can we put this issue on hold for the https://github.com/Expensify/App/pull/27494?

**Comment by greg-schroeder** [comment] 2023-10-12 16:56
Holding

**Comment by greg-schroeder** [comment] 2023-10-19 00:58
Work continues on the hold PR

**Comment by greg-schroeder** [comment] 2023-10-27 16:53
Held PR deployed to prod

**Comment by greg-schroeder** [comment] 2023-10-27 16:55
Can anyone reproduce this now?

**Comment by gadhiyamanan** [comment] 2023-11-09 11:32
@greg-schroeder issue is still reproducible

**Comment by abdulrahuman5196** [comment] 2023-11-13 08:48
Hi, Will review again today, just back from weekend

**Comment by greg-schroeder** [comment] 2023-11-14 16:47
Okay thanks @abdulrahuman5196!

**Comment by abdulrahuman5196** [comment] 2023-11-20 16:16
Reviewing now.

**Comment by abdulrahuman5196** [comment] 2023-11-21 17:37
Ok I am also able to reproduce the issue still. need to check the old proposals again.

**Comment by abdulrahuman5196** [comment] 2023-11-22 10:43
@c3024 's proposal here https://github.com/Expensify/App/issues/28928#issuecomment-1749180573 looks good and works well. During PR stage we should try to create common function instead of making changes at different places.

I assume we want to hide the red dot everywhere when the request is paid like LHN, preview messages and other places if present. Correct me if wrong @greg-schroeder 

🎀 👀 🎀
C+ Reviewed

**Comment by abdulrahuman5196** [comment] 2023-11-22 11:03
> > function hasMissingSmartscanFields(transaction: Transaction): boolean {
> > return !ReportUtils.isSettled(transaction.reportID) && hasReceipt(transaction) && !isDistanceRequest(transaction) && !isReceiptBeingScanned(transaction) && areRequiredFieldsEmpty(transaction);
> > }
> 
> @abdulrahuman5196 My proposal update the change in the util function that will cover all places that we are using `hasMissingSmartscanFields`

Hi, I wouldn't be able to consider the proposal as a separate unique one, since its more like a PR optimization or PR level comments. So I have recommended the first proposal suggesting the fix.

**Comment by c3024** [comment] 2023-11-23 06:51
It has been a while since I posted this proposal but I don't think I added the part of moving `isSettled` to `hasMissingSmartScanFields` based on @dukenv0307's proposal.

But if the proposal of moving `isSettled` to `hasMissingSmartScanFields` function is considered significantly different enough from my initially posted proposal, feel free to assign @dukenv0307.

**Comment by abdulrahuman5196** [comment] 2023-11-24 08:24
The below is the first created proposal by @c3024 and I did check the history before approval the proposal from my end. And IMO as pointed out in before comments moving the suggested fix to common functions shouldn't count as a new proposal, it should be considered as PR optimizations. And on another point, when I suggested to use common function, I didn't mean to update `hasMissingSmartScanFields` but to create a new function(if not present) like `shouldShowRedIndicator` or something.

So I still stand by the approval provided here https://github.com/Expensify/App/issues/28928#issuecomment-1822524051. I would kindly request the contributors to hold the discussions since both sides have already raised the concerns and internal engineer is yet to check on the approval.


```

Proposal
Please re-state the problem that we are trying to solve in this issue.

Red dot does not disappear even after settling a money request.
What is the root cause of that problem?

We are showing red dot when there are errors
https://github.com/Expensify/App/blob/567c32e56a449100cebb83af560aa1fcb07daf09/src/components/ReportActionItem/ReportPreview.js#L196-L201
and when there are missing smartscan fields hasErrors is true. So the red indicator appears here. This is same for MoneyRequestPreview and getAllReportErrors of OptionListUtils.
What changes do you think we should make in order to solve the problem?

We should check if the IOU is settled before checking if hasErrors is true and displaying the red dot.
So, we should change this here
https://github.com/Expensify/App/blob/567c32e56a449100cebb83af560aa1fcb07daf09/src/components/ReportActionItem/ReportPreview.js#L196
to

!iouSettled && hasErrors

We should change this here
https://github.com/Expensify/App/blob/567c32e56a449100cebb83af560aa1fcb07daf09/src/components/ReportActionItem/MoneyRequestPreview.js#L269-L274
to

{!isSettled && hasFieldErrors && (

and
we should change this here
https://github.com/Expensify/App/blob/567c32e56a449100cebb83af560aa1fcb07daf09/src/libs/OptionsListUtils.js#L356-L359
to

            const isSettled = ReportUtils.isSettled(iouReportID);
            // Instead of adding all Smartscan errors, let's just add a generic error if there are any. This
            // will be more performant and provide the same result in the UI
            if (!isSettled && ReportUtils.hasMissingSmartscanFields(iouReportID)) {
                _.extend(reportActionErrors, {smartscan: ErrorUtils.getMicroSecondOnyxError('report.genericSmartscanFailureMessage')});

so this does not add an error to the option row when the error is a missing smart scan field for a settled IOU.
What alternative solutions did you explore? (Optional)
```

**Comment by aldo-expensify** [comment] 2023-11-24 19:21
Thanks @abdulrahuman5196 for handling this, and I agree with you.

Also, I don't think we should put the `isSettled` check inside `ReportUtils.hasMissingSmartscanFields` because I don't think that is the responsibility of that function, at least that is not what the name says. It is true that in the current usages we always check these two things, and if you want to centralize, I would suggest adding a new function that calls `ReportUtils.hasMissingSmartscanFields` and also checks for `isSettled`, but I don't think it is worth it.

**Comment by greg-schroeder** [comment] 2023-12-19 01:58
This was deployed to prod 2 weeks ago. The automation didn't pick this up for some reason 😅

**Comment by greg-schroeder** [comment] 2023-12-19 02:00
Reported by: @gadhiyamanan ($50)
Contributor: @c3024 ($500)
C+: @abdulrahuman5196 ($500)

**Comment by greg-schroeder** [comment] 2023-12-19 03:06
Offers sent to each of you. Please accept and I'll pay you out ASAP.

**Comment by c3024** [comment] 2023-12-19 03:10
Accepted

**Comment by abdulrahuman5196** [comment] 2023-12-19 05:04
Thank you @greg-schroeder Accepted the offer

**Comment by abdulrahuman5196** [comment] 2023-12-19 09:20
>The PR that introduced the bug has been identified. Link to the PR:
The offending PR has been commented on, pointing out the bug it caused and why, so the author and reviewers can learn from the mistake. Link to comment:
A discussion in #expensify-bugs has been started about whether any other steps should be taken (e.g. updating the PR review checklist) in order to catch this type of bug sooner. Link to discussion:

Doesn't seem to be a regression but an implementation miss.

>Determine if we should create a regression test for this bug.

Yes.

>If we decide to create a regression test for the bug, please propose the regression test steps to ensure the same bug will not reach production again.


1) Click on FAB -> Request Money -> Scan
2) Choose a receipt and input/select User B
3) Click "Request" to complete the request
4) Go to this transaction thread and click on amount and enter an amount
5) Red indicator appears now as the merchant field is empty
6) Pay that request from User B
7) Verify that no red indicators appear for report preview, LHN and the transaction thread for this request.

**Comment by greg-schroeder** [comment] 2023-12-20 00:38
Everyone has been paid, adding regression test and closing!

**Closed by greg-schroeder** 2023-12-20 00:38 UTC
Labels: Reviewing, External, Daily, Awaiting Payment, Bug
