### ISSUE TITLE
[HOLD for payment 2023-06-21] [$1000] DEV: console error on opening Share code of thread

### ISSUE THREAD

**Issue by kavimuru** [Expensify/App#19985] opened 2023-06-01 17:00 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. go to any chat
2. send any message
3. click on reply in thread option
4. click on header of thread to open details page
5. click on share code
## Expected Result: 
should not show any console error
## Actual Result: 
shows console error
## Workaround:
Can the user still use Expensify without this being fixed? Have you informed them of the workaround?

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [] Android / native
- [] Android / Chrome
- [] iOS / native
- [] iOS / Safari
- [x] MacOS / Chrome / Safari
- [] MacOS / Desktop

**Version Number:** 1.3.20.2
**Reproducible in staging?:** needs reproduction
**Reproducible in production?:** needs reproduction
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/43996225/c3088589-9257-4865-9502-4729093263a1

**Expensify/Expensify Issue URL:**
**Issue reported by:** @gadhiyamanan 
**Slack conversation:** 
https://expensify.slack.com/archives/C049HHMV9SM/p1685430101536709
[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~016f17d9321b19bf9c</li>
        <li>Upwork Job ID: 1666644239370522624</li>
        <li>Last Price Increase: 2023-06-08</li>
    </ul>
</details>

**Comment by situchan** [comment] 2023-06-01 17:13
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
Console error on Share code page from thread chat

### What is the root cause of that problem?
`string && <View />` here:
https://github.com/Expensify/App/blob/d661708d0aae864caeceb98801e921f07c0954a8/src/components/QRShare/index.js#L74-L75
This was introduced in #18636.
This checklist item was skipped during PR review:
- [ ]  I verified that the left part of a conditional rendering a React component is a boolean and NOT a string, e.g. `myBool && <MyComponent />`.

### What changes do you think we should make in order to solve the problem?
wrap with `_isEmpty` which is boolean:
```
!_.isEmpty(this.props.subtitle) &&
```

**Comment by sophiepintoraetz** [comment] 2023-06-02 05:20
This has been resolved as a part of https://github.com/Expensify/App/issues/18968 and the reporter paid. I am unable to reproduce.

**Comment by gadhiyamanan** [comment] 2023-06-02 05:34
@sophiepintoraetz this is different issue and reproducible in dev when user open share code of thread

**Comment by sophiepintoraetz** [comment] 2023-06-02 05:39
@gadhiyamanan I am unable to reproduce it - as mentioned before so there needs to be clearer reproduction steps in order to progress this through.


<img width="2624" alt="image" src="https://github.com/Expensify/App/assets/42940078/e2e64584-b619-4412-a013-a6aa53576fca">


https://github.com/Expensify/App/assets/42940078/35ecc5c6-a7a8-4ed3-b942-c4f3977e4047

**Comment by gadhiyamanan** [comment] 2023-06-02 05:57
steps are the same but it is reproducible only in the dev(main branch). I think you are checking in staging or Production that's why you are not able to reproduce
cc: @sophiepintoraetz 

https://github.com/Expensify/App/assets/54790231/74805e2d-13eb-4e82-9da6-c00dd02e957c

**Comment by sophiepintoraetz** [comment] 2023-06-07 04:37
@robertjchen - this is on dev and I think introduced from https://github.com/Expensify/App/issues/18630 - can you reproduce here? 🙏

**Comment by robertjchen** [comment] 2023-06-08 03:10
I was able to reproduce this 👍

**Comment by robertjchen** [comment] 2023-06-08 03:11
It was not introduced by https://github.com/Expensify/App/issues/18630 since that feature came out prior to threads, and is an isolated issue

**Comment by robertjchen** [comment] 2023-06-08 03:13
The fix I came to locally matches @situchan 's proposal (though I used `!!` instead of `!_.isEmpty`). Which approach is better? 🤔

**Comment by situchan** [comment] 2023-06-08 03:21
Either approach is fine but I recently noticed that PR reviewers recommend to use `!_.isEmpty` instead of `!!`.

**Comment by robertjchen** [comment] 2023-06-08 03:24
ok, perfect! cc: @mananjadhav for 👍 on proposed changes

**Comment by situchan** [comment] 2023-06-08 03:26
> It was not introduced by #18630 since that feature came out prior to threads, and so this is an isolated bug.

That might be true but root cause existed. Thread room reused that component which was implemented in #18630 and bug revealed on this line:

https://github.com/Expensify/App/pull/18636/files#diff-1e570d29d05a4d59c3ce4685186903bf1c83c3e8cfc66ba35708a6ffbc28c0edR82

**Comment by mananjadhav** [comment] 2023-06-08 03:57
Yes. The proposal looks good.

**Comment by sophiepintoraetz** [comment] 2023-06-12 18:11
@dylanexpensify - I just need you to action the payments once the regression period has passed (PR still going through QA so I think that will populate in the GH soon)
@gadhiyamanan - $250
@mananjadhav and @situchan = $1500

Job is here! https://www.upwork.com/jobs/~016f17d9321b19bf9c

**Comment by sophiepintoraetz** [comment] 2023-06-21 05:15
@gadhiyamanan and @situchan - contracts are with you! @mananjadhav - if you can go through the BZ checklist, I'll be able to release payment to you too.

**Comment by gadhiyamanan** [comment] 2023-06-21 05:17
@sophiepintoraetz accepted, thanks!

**Comment by situchan** [comment] 2023-06-21 06:43
@sophiepintoraetz the offer is not available anymore

**Comment by mananjadhav** [comment] 2023-06-21 11:17
The first instance when we added the `subtitle` prop was in this [PR](https://github.com/Expensify/App/pull/18636). 

I've added this [comment](https://github.com/Expensify/App/pull/18636/files#r1236818210) on the offending PR. 

> I verified that the left part of a conditional rendering a React component is a boolean and NOT a string, e.g. myBool && <MyComponent />.

We already have a checklist item here but we missed the particular condition in the code. I don't think any further updates are required and I don't think we need a regression test either.

cc - @sophiepintoraetz @robertjchen

**Comment by sophiepintoraetz** [comment] 2023-06-21 23:32
Thanks @mananjadhav - releasing payment!
>We also have an item in the checklist which was marked but we missed highlighting this one.

How did we miss highlighting it? Does it mean someone marked it off but it wsn't actually completed?

@situchan - sorry! I swear I sent the offer to you but I think Upwork was messing with me. You should have a new offer now.

**Comment by sophiepintoraetz** [comment] 2023-06-22 06:02
Payments all set so closing!

**Closed by sophiepintoraetz** 2023-06-22 06:02 UTC
Labels: External, Daily, Awaiting Payment, Bug
