### ISSUE TITLE
[HOLD for payment 2024-04-09] [$500] Can't focus on main composer after going back from thread

### ISSUE THREAD

**Issue by m-natarajan** [Expensify/App#38700] opened 2024-03-20 19:13 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.55-0
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** @dukenv0307 
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1710867598533239

## Action Performed:
1. Open a report
2. Send a message
3. Hover the message and tap on reply in thread
4. Click on the browser back button
5. Edit the message
6. Click on the main composer
## Expected Result: 
The main composer is focused
## Actual Result: 
The main composer is focused briefly and then the edit composer is focused again

## Workaround:
unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

https://github.com/Expensify/App/assets/38435837/f0aa4ab3-d5db-49e9-aa08-5aaa4f904c42

https://github.com/Expensify/App/assets/38435837/897e542a-046b-4101-84ce-09363da5e016

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01e69b6fd5125bc19c</li>
        <li>Upwork Job ID: 1770901457770471424</li>
        <li>Last Price Increase: 2024-03-21</li>
<li>Automatic offers: </li>
<ul>
<li>dukenv0307 | Reviewer | 0</li>
</ul></li>
    </ul>
</details>

**Comment by nkdengineer** [comment] 2024-03-20 23:30
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
The main composer is focused briefly and then the edit composer is focused again

### What is the root cause of that problem?
We have the logic the set the global ref for main composer here, it will be called when a report screen is mounted

https://github.com/Expensify/App/blob/ba0816bd4fd62dc5e7e013df3ef17b015e6c275a/src/pages/home/report/ReportActionCompose/ComposerWithSuggestions/ComposerWithSuggestions.tsx#L306

When we go to the thread, the parent report is in stack navigator  and it isn't unmounted. After going back by back button browser this is a old screen so `ReportActionComposeFocusManager.composerRef` still is the ref of thread's composer

https://github.com/Expensify/App/blob/ba0816bd4fd62dc5e7e013df3ef17b015e6c275a/src/pages/home/report/ReportActionCompose/ComposerWithSuggestions/ComposerWithSuggestions.tsx#L306

When we click on edit composer, we will save the ref in `InputFocus.composerFocusKeepFocusOn` function

https://github.com/Expensify/App/blob/ba0816bd4fd62dc5e7e013df3ef17b015e6c275a/src/pages/home/report/ReportActionItemMessageEdit.tsx#L139


and then if we click on main composer, the edit composer will be focused again by this logic here because `ReportActionComposeFocusManager.composerRef` still is the ref of thread's composer  leading `ReportActionComposeFocusManager.isFocused()` return `false` 
https://github.com/Expensify/App/blob/ba0816bd4fd62dc5e7e013df3ef17b015e6c275a/src/libs/actions/InputFocus/index.website.ts#L20-L26
### What changes do you think we should make in order to solve the problem?

In `ReportActionComposeFocusManager` we can store another field like `composerID` that is the report id of main composer and update it as reportID here.


https://github.com/Expensify/App/blob/ba0816bd4fd62dc5e7e013df3ef17b015e6c275a/src/pages/home/report/ReportActionCompose/ComposerWithSuggestions/ComposerWithSuggestions.tsx#L306


And then when we focus on a main composer, if the `composerID` now is different from the `reportID`, we will update the 

the `ReportActionComposeFocusManager.composerRef` as `composerRef` here.


https://github.com/Expensify/App/blob/ba0816bd4fd62dc5e7e013df3ef17b015e6c275a/src/pages/home/report/ReportActionCompose/ReportActionCompose.tsx#L307

### What alternative solutions did you explore? (Optional)
In `ReportActionCompose`, we can create a useEffect that will update `ReportActionComposeFocusManager.composerRef` if the focus state change from `false` to `true`

```
const prevIsFocusedScreen = usePrevious(isFocusedScreen);

useEffect(() => {
    if (!isFocusedScreen || prevIsFocusedScreen) {
        return;
    }

    ReportActionComposeFocusManager.composerRef.current = composerRef.current;

}, [isFocusedScreen, prevIsFocusedScreen])
```

**Comment by strepanier03** [comment] 2024-03-21 19:48
Got it, thanks @dukenv0307. I'm chatting about this internally before moving forward.

**Comment by strepanier03** [comment] 2024-03-21 19:54
I can recreate this following the steps and for consistency's sake we should have the same behavior as when you edit the message without going to "reply in thread" first.

**Comment by nkdengineer** [comment] 2024-03-22 15:57
@dukenv0307 
Thank for your feedback, I think that makes sense, we can update `composerRef` in this listener. So the update logic when the screen is focused can be centralized.

Updated proposal https://github.com/Expensify/App/issues/38700#issuecomment-2010901551

**Comment by NikkiWines** [comment] 2024-03-25 18:44
Nice, agreed the updated alternative solution looks good 👍

**Comment by nkdengineer** [comment] 2024-03-26 04:27
@dukenv0307 The PR is [here](https://github.com/Expensify/App/pull/38978)

**Comment by strepanier03** [comment] 2024-04-05 23:03
@stephanieelliott - This one is just waiting for payment hold to expire and payment to be handled. I'm going to be out of office until the 12th so I won't be able to handle this one for multiple days after payment is due. 

Thank you so much!

**Comment by strepanier03** [comment] 2024-04-05 23:06
@nkdengineer - Can you apply to this [job](https://www.upwork.com/jobs/~0146517131923bf267) or share your upwork profile so we can locate you and offer the contract? 

Thanks!

**Comment by proooooooooooooooooo** [comment] 2024-04-06 10:07
As a React Native developer, I understand the root cause of the issue and I am confident in my ability to resolve it. By updating the logic in the ReportActionComposeFocusManager, I can ensure that the global reference for the main composer is accurately maintained, even after navigating back from a thread. Additionally, I am well-versed in managing component focus and can implement the necessary changes to ensure that the main composer receives focus correctly. With my expertise, I am committed to addressing this issue effectively and providing a seamless user experience.

**Comment by proooooooooooooooooo** [comment] 2024-04-06 10:07
Based on the provided context, the problem we are trying to solve is the inability to focus on the main composer after navigating back from a thread. This occurs because the logic to set the global reference for the main composer is not updated when navigating back, causing the focus to remain on the thread's composer instead.

The root cause of this problem is that the global reference for the main composer (ReportActionComposeFocusManager.composerRef) is not updated when navigating back from a thread. This is because the parent report is not unmounted when navigating back, so the reference to the thread's composer remains unchanged.

To solve this problem, we can make changes in the ReportActionComposeFocusManager to store another field, such as composerID, which represents the report ID of the main composer. We can then update this field when focusing on a main composer. If the composerID differs from the current report ID, we update the ReportActionComposeFocusManager.composerRef to point to the main composer.

An alternative solution explored was to update the ReportActionComposeFocusManager.composerRef whenever the screen is focused. This involves updating the reference to the main composer in the focus event listener.

These solutions aim to ensure that the focus is correctly set on the main composer when navigating back from a thread, resolving the issue of being unable to focus on the main composer.

**Comment by stephanieelliott** [comment] 2024-04-15 22:12
One more bump before I close this -- @nkdengineer can you please share your Upwork profile so we can offer the contract and issue payment?

**Comment by nkdengineer** [comment] 2024-04-16 02:57
@stephanieelliott Sorry for the late, my Upwork profile here https://www.upwork.com/freelancers/~0134d0b74faef1a5ac.

**Comment by stephanieelliott** [comment] 2024-04-16 19:13
@nkdengineer I've extended the offer to you in Upwork, please accept: https://www.upwork.com/nx/wm/offer/101894314

**Comment by nkdengineer** [comment] 2024-04-17 06:33
@stephanieelliott I accepted it, thanks!

**Comment by stephanieelliott** [comment] 2024-04-18 13:50
All paid! See payment summary here: https://github.com/Expensify/App/issues/38700#issuecomment-2045920597

**Closed by stephanieelliott** 2024-04-18 13:50 UTC
Labels: External, Daily, Awaiting Payment, Bug
