### ISSUE TITLE
[$500] New chat - Default avatar does not match for new chat page and for chat page

### ISSUE THREAD

**Issue by izarutskaya** [Expensify/App#26083] opened 2023-08-28 13:50 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Open ND
2. Click on FAB > new chat > paste an email and start a chat with that contact
3. Click on FAB again and new chat
4. Paste the email you started a chat with earlier
5. Compare the default avatar you see on the new chat page with the chat you started with

## Expected Result:
Both default avatars should be the same

## Actual Result:
Different default avatars are seen

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [x] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:**  v1.3.57-5

**Reproducible in staging?:** Y

**Reproducible in production?:** Y

**If this was caught during regression testing, add the test name, ID and link from TestRail:**

**Email or phone of affected tester (no customers):**

**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/115492554/424a18b3-3a74-4213-a6cf-f7c3823d9934

https://github.com/Expensify/App/assets/115492554/cdf2199e-84ee-4ef7-b244-c6113818a3f5

**Expensify/Expensify Issue URL:**

**Issue reported by:** @Nathan-Mulugeta

**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1692042235315439

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~0115124794a3be899c</li>
        <li>Upwork Job ID: 1704780350206033920</li>
        <li>Last Price Increase: 2023-09-21</li>
    </ul>
</details>

**Comment by luacmartins** [comment] 2023-08-28 22:00
I believe this has the same root cause as https://github.com/Expensify/App/issues/25889

**Comment by stephanieelliott** [comment] 2023-08-29 15:31
Thanks @luacmartins. Let's put this on hold til https://github.com/Expensify/App/issues/25889 is merged to see if that resolves it.

**Comment by stephanieelliott** [comment] 2023-09-11 23:09
Still holding for https://github.com/Expensify/App/issues/25889

**Comment by luacmartins** [comment] 2023-09-21 00:14
@stephanieelliott the PR for https://github.com/Expensify/App/issues/25889 was deployed to prod last week. Can we retest this and make sure it's not happening anymore?

**Comment by Nathan-Mulugeta** [comment] 2023-09-21 07:51
@luacmartins  I just retested this and it has not been fixed. 
![image](https://github.com/Expensify/App/assets/111440031/0c71a759-d844-4a1a-8439-f75ed4fd9b6c)

**Comment by salonikumawat28** [comment] 2023-09-21 11:14
@tienifr 
Isn't this comment a problem?
[```
```](https://github.com/Expensify/App/blob/f39e93f119c7bb76a56fb7df28251d84a37b65bc/src/libs/OptionsListUtils.js#L1013-L1017)

**Comment by zukilover** [comment] 2023-09-21 14:14
## Proposal
### Please re-state the problem that we are trying to solve in this issue.
New chat - Default avatar does not match for new chat page and for chat page

### What is the root cause of that problem?
When we paste the recipient email in the first time, it creates an optimistic account with a specific ID and avatar.
By the time it is resolved from the backend, accountID for the recipient email is updated, thus updates the avatar as well.

https://github.com/Expensify/App/blob/ee023d8ab36dd722a465c89bf4edff1b8e79aadf/src/libs/actions/Report.js#L496-L502

In this case, we have 2 accounts with different accountIDs but the same email address.

<img width="600" alt="accounts" src="https://github.com/Expensify/App/assets/371291/d628d365-bc77-4b09-a240-0b67b193f9b0">


### What changes do you think we should make in order to solve the problem?
If we want to get the same avatar for the same email address (like Gravatar), I suggest that we take the avatar from the optimistic account creation as the reference. This is because it's the earliest data that is available to the user.

We can do so by trying to resolve accountID to the `personalDetails` that holds the same email address (the optimistic one), e.g.:

```
function getOptimisticAccountByID(accountID) {
    const matchedAccount = _.find(personalDetails, detail => detail.accountID === accountID)
    const optimisticAccount = _.find(personalDetails, detail => detail.displayName === matchedAccount?.displayName)
    return optimisticAccount
}
```

We can then resolve the appropriate avatar, e.g.:

```
const avatarAccount = PersonalDetailsUtils.getOptimisticAccountByID(accountID)
const avatarSource = UserUtils.getAvatar(avatarAccount?.avatar, avatarAccount?.accountID);
```

### What alternative solutions did you explore? (Optional)

N/A

**Comment by luacmartins** [comment] 2023-09-25 09:06
@robertKozik did you get a chance to look at the proposals above?

**Comment by robertKozik** [comment] 2023-09-25 09:17
Yeah I'm on it 👀 
@luacmartins Could you check the issue linked in the code comment provided [here](https://github.com/Expensify/App/issues/26083#issuecomment-1729359882)? II don't have access to it, and I'm unable to determine if it contains additional information that might be relevant to this issue.

**Comment by luacmartins** [comment] 2023-09-25 09:25
That issue only considers personalDetails as options in OptionsListUtils.getOptions if they have logins set, since not all personalDetails objects have logins set (if they are anonymous)

**Comment by luacmartins** [comment] 2023-09-28 06:37
bump @robertKozik

**Comment by stephanieelliott** [comment] 2023-09-29 05:29
Hey @robertKozik are you able to prioritize this?

**Comment by luacmartins** [comment] 2023-10-03 16:26
bumping @robertKozik

**Comment by stephanieelliott** [comment] 2023-10-04 00:57
It's been a while since we've heard from @robertKozik, posting in Slack to see if we can get another C+ on this. https://expensify.slack.com/archives/C02NK2DQWUX/p1696381024475039

**Comment by s77rt** [comment] 2023-10-04 01:06
Taking this as C+

**Comment by s77rt** [comment] 2023-10-04 01:09
Hmm, is this still reproducible? I can't reproduce from my end

**Comment by s77rt** [comment] 2023-10-04 18:34
I still can't reproduce. The avatar updates correctly from my end. @stephanieelliott Can you try after loging out/in.


https://github.com/Expensify/App/assets/16493223/963b0b0d-6b6d-4760-aab9-28dbb24c7f91

**Comment by Nathan-Mulugeta** [comment] 2023-10-05 07:19
I just retested this issue again and I can confirm this is no longer reproducible for me as well

**Comment by luacmartins** [comment] 2023-10-05 15:50
Ok so it seems like this issue shared a root cause with another issue and that has been fixed. So I think we're good to close this issue. Thanks everyone!

**Closed by luacmartins** 2023-10-05 15:50 UTC
Labels: Daily, Internal, Bug
