### ISSUE TITLE
[HOLD for payment 2022-10-03] [$250] Ellipsis is not showing up in medium screen width - reported by @Tushu17

### ISSUE THREAD

**Issue by mvtglobally** [Expensify/App#10510] opened 2022-08-24 03:34 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Open website in desktop.
2. resize the window to single page.
3. Go to chat > Send a long message.
4. Go to Homepage

## Expected Result:
It should show ellipsis for long message.

## Actual Result:
It doesn't show ellipsis.

## Workaround:
unknown 

## Platform:

Where is this issue occurring?

- Web
- Desktop App

**Version Number:** 1.1.88-0
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**Email or phone of affected tester (no customers):** 
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation

https://user-images.githubusercontent.com/43995119/186322898-77a683b7-37ba-4bdb-a4d6-3ab35013edcc.mov

**Expensify/Expensify Issue URL:** 
**Issue reported by:** @Tushu17
**Slack conversation:** https://expensify.slack.com/archives/C01GTK53T8Q/p1659542182865039 

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by SofiedeVreese** [comment] 2022-08-31 06:58
Should we reassign this one, given you'll be on Sabbatical soon?

**Comment by robertjchen** [comment] 2022-08-31 11:39
Thanks for the report- I was able to reproduce this issue locally. Going to open this up for our contributors to tackle 👍

**Comment by MitchExpensify** [comment] 2022-09-01 12:15
[Upwork Job](https://www.upwork.com/jobs/~0128cde2c904a18717)

**Comment by christianwen** [comment] 2022-09-01 16:57
# **Proposal**

## **Problem**
The issue is from the `src/CONST.js` where we're setting the `LAST_MESSAGE_TEXT_MAX_LENGTH` as 80 characters. That number is too low because when the app is in tablet mode (medium screen width as mentioned in the issue report), the width that the last message text occupies is around 700px. The width needed to render the last message (which is 80 characters maximum) is far lower than 700px, so to React Native, the truncated last message text totally fit in the Text component width, thus it doesn't append the ellipsis. 

## **Solution**
There're 2 solutions that I propose, it's dependent on whether we still want to keep the 'truncated last message text' optimization or not:
(The code below is only in the front-end code, I'll need help from someone from the internal team to modify the back-end code as well since I don't have access to the repo, the logic should be similar)

**1. We keep the last message text length as is without truncating it, when we save it to Onyx (and subsequently to our database)**

In `src/libs/ReportUtils.js`
```diff
function formatReportLastMessageText(lastMessageText) {
-    return String(lastMessageText).substring(0, CONST.REPORT.LAST_MESSAGE_TEXT_MAX_LENGTH);
+    return String(lastMessageText);
}
```
or we can remove the `formatReportLastMessageText` and its usage entirely if we don't need the encapsulation, because it no longer contains any custom logic

**2. We increase the `LAST_MESSAGE_TEXT_MAX_LENGTH`**
I don't really prefer this approach because it's really difficult to estimate how much would be the maximum length that the last message text will occupy. It depends on multiple parameters like the characters in the message (`i` and `W` has different width although both count as one character), the device that the user is using, custom font size, different languages, ...

We should only consider this if we really want to keep the max last message size (for optimization or some other reasons).
Based on my quick calculation the max length at around 200 characters should be good for most cases.

In `src/CONST.js`:
```diff
-LAST_MESSAGE_TEXT_MAX_LENGTH: 80,
+LAST_MESSAGE_TEXT_MAX_LENGTH: 200,
```

Issue fixed when implementing each of the above and set the network to offline (because back-end fix is also required so I turn off network to test first)

<img width="710" alt="Screen Shot 2022-09-01 at 23 53 46" src="https://user-images.githubusercontent.com/21312517/187970089-d6c44845-5419-4022-b9ae-a05db0fce959.png">

Please let me know if you have any concerns regarding the above proposal
Thanks!

**Comment by christianwen** [comment] 2022-09-02 02:01
@rushatgabhane 

> Solution # 1 will reintroduce issue https://github.com/Expensify/App/issues/6699
I see it's more like the fix for issue https://github.com/Expensify/App/issues/6699 introduced this problem. The assumption in that issue is `AlternativeText contains text of arbitrary length from the last message which is not really fully visible anywhere.
It unnecessary increase the storage and runtime memory.`, which is not the case since the alternativeText will be used almost fully in tablet screen width so it will cause bugs when we trim it. Also I see the memory leak that is mentioned in https://github.com/Expensify/App/issues/6699 was not fixed but rather ignored since it's more like a glitch that cannot be reproduced, as mentioned in https://github.com/Expensify/App/issues/6699#issuecomment-1005708868. So I think if we implement this solution, it will **not** cause the memory leak and it will fix the regression. This solution is not reintroducing any bug but rather undoing an optimization, which was based on an incorrect assumption and caused bug.

> Solution # 2 will not ellipse text when it's more than 200 characters, and also it'll require backend changes.
Agree with you on this since I still prefer the Solution 1. But `200 characters` is a quite long text that most likely will exceed the 800px breakpoint that we have for tablet, so it will still have the ellipsis. You can see in my screenshot in the above proposal, it's only 175 characters and I've already tried to make the character width as low as possible (by having all `i` character which has the smallest width), but in total that 175 characters still exceed the width of the tablet, and still have the ellipsis. So we should be safe in all usual cases, unless you're trying something weird like modifying the font size to be very very small, then this solution will fail. You can try to set max length to `200` characters and try to reproduce the problem in offline mode to confirm this. 
We should only consider this if Solution 1, for some reasons, cannot be accepted.

**Comment by ctkochan22** [comment] 2022-09-05 09:08
Taking a look at the proposal today. Thanks!

**Comment by MitchExpensify** [comment] 2022-09-06 16:26
Did you get a chance to check the proposal out @ctkochan22 ?

**Comment by MitchExpensify** [comment] 2022-09-12 10:06
Lil bump @ctkochan22

**Comment by ctkochan22** [comment] 2022-09-13 04:12
Hmmm solution 2 seems the best for right now. It doesn't seem like solution 1 would cause any sort of regression, but I don't like the idea that we are storing huge comments in the LHN when we don't need to. Although I agree that its a pretty minimal optimization. Let me ask the team tomorrow, cc someone else who worked on this prior

**Comment by ctkochan22** [comment] 2022-09-13 18:57
@rushatgabhane I appreciate your thoroughness in thinking through the proposal

**Comment by ctkochan22** [comment] 2022-09-14 22:25
Lets go with solution 2. @christianwen Can you write up the PR and test on all platforms please?

**Comment by christianwen** [comment] 2022-09-15 16:44
@ctkochan22 I'm preparing the PR, I've also applied for the Upwork job, please help accept my proposal on Upwork. My Upwork profile is https://www.upwork.com/freelancers/~01991fd5e5c11ef3ba
Thanks

**Comment by ctkochan22** [comment] 2022-09-15 16:53
@MitchExpensify

**Comment by ctkochan22** [comment] 2022-09-19 15:49
@MitchExpensify can we hire @christianwen pretty please

**Comment by MitchExpensify** [comment] 2022-09-21 01:42
Sorry for the delay, catching up from OOO last week! Hired @christianwen, @Tushu17, and invite sent to @rushatgabhane for eventual C+ payment

**Comment by christianwen** [comment] 2022-09-21 03:57
thanks @MitchExpensify 
@ctkochan22 PR created here https://github.com/Expensify/App/pull/11013 and requested you for review.
Also as mentioned in https://github.com/Expensify/App/issues/10510#issuecomment-1234543169, a back-end fix for the same constant is also required so that it will work in online mode (currently we need to turn off network to test the PR).
<img width="842" alt="Screen Shot 2022-09-21 at 10 55 39" src="https://user-images.githubusercontent.com/21312517/191410859-0eb2c720-2158-4052-a228-08bbbc26acc6.png">
Please help with this since I don't access to the back-end repo.
Thanks!

**Comment by rushatgabhane** [comment] 2022-09-21 19:43
PR seems okay, we should wait for backend changes before merging?
@ctkochan22

**Comment by MitchExpensify** [comment] 2022-10-06 18:56
Issuing payment now!

**Comment by MitchExpensify** [comment] 2022-10-06 19:01
Just waiting on you to accept @rushatgabhane before closing this out, thanks everyone!

**Comment by MitchExpensify** [comment] 2022-10-06 19:17
Done!

**Closed by MitchExpensify** 2022-10-06 19:17 UTC
Labels: Reviewing, External, Engineering, Daily, Help Wanted, Awaiting Payment
