### ISSUE TITLE
[HOLD for payment 2023-07-24] [$1000] Payments - App allows to add paypal account using deep link even if paypal account is already added

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#21642] opened 2023-06-26 20:26 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Open the app
2. Open settings
3. Open Payments
4. If Paypal account already added then remove it
5. Click on 'Add payment method' and click on Paypal
6. Now before adding and saving copy the URL (URL to copy is: https://staging.new.expensify.com/settings/payments/add-paypal-me) and then add any Paypal account
7. Observe that now Paypal account is added and we don't have  option to add/update Paypal account
8. Visit URL copied in step 6 from same user in same browser and observe that app allows to add Paypal account even though we already have Paypal account added

## Expected Result:
App should not allow to open the add Paypal account if we already have Paypal account added

## Actual Result:
App allows to open the add Paypal account using deep link even if we already have paypal account added

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [x] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [x] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 1.3.32.5
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/93399543/2d7be46d-0f2e-4759-bbc3-0df0a940195a

https://github.com/Expensify/App/assets/93399543/5268e6eb-d403-436e-bdbd-1ce74f033fdc

**Expensify/Expensify Issue URL:**
**Issue reported by:** @dhanashree-sawant
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1687489946571709

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01cb50065c59629ed0</li>
        <li>Upwork Job ID: 1673720842042441728</li>
        <li>Last Price Increase: 2023-07-04</li>
    </ul>
</details>

**Comment by jfquevedol2198** [comment] 2023-06-27 00:31
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
Payments - App allows to add paypal account using deep link even if paypal account is already added

### What is the root cause of that problem?
`Add Paypal` page doens't have validation whether or not  PaypalMe is already added.

### What changes do you think we should make in order to solve the problem?
If PaypalMe is already added, call to go back.

1. add propTypes in `AddPaypalPage` component
```javascript
const propTypes = {
    /** Account details for PayPal.Me */
    payPalMeData: paypalMeDataPropTypes,

    ...withLocalizePropTypes,
};

const defaultProps = {
    payPalMeData: {},
};
```
2. update `AddPaypalPage` component by adding `payPalMeData` by `withOnyx`
```javascript
export default compose(
    withLocalize,
    withOnyx({
        payPalMeData: {
            key: ONYXKEYS.PAYPAL,
        }
    }),
)(AddPayPalMePage);
```
3. add code to go previous page if PaypalMe is already added
```javascript
useEffect(() => props.payPalMeData.description && Navigation.goBack()
, [props.payPalMeData.description]);
```
<details><summary>Result</summary>

https://github.com/Expensify/App/assets/137529618/466e6544-30cc-4f70-b153-db0c546d869d

</details> 

### What alternative solutions did you explore? (Optional)
N/A

**Comment by lschurr** [comment] 2023-06-29 23:24
@eVoloshchak looks like we have a proposal for review.

**Comment by eVoloshchak** [comment] 2023-07-02 20:38
Yeah, I agree with @hungvu193's [proposal](https://github.com/Expensify/App/issues/21642#issuecomment-1608530234) on this one, we shouldn't just close the screen, we should give user the ability to update their PayPal account. At the very least (if _update PayPal account_ flow isn't necessary), we should show a message to user before closing the add PayPal screen

🎀👀🎀 C+ reviewed!

**Comment by lschurr** [comment] 2023-07-05 20:22
Ok great. We should assign @hungvu193 - is that correct @eVoloshchak?

**Comment by jfquevedol2198** [comment] 2023-07-05 22:21
@eVoloshchak  @lschurr 
My proposal was for resolving of this issue's expected behaviour. If this was not for preventing only entering of adding new paypal account in the case there is already added paypal account, I think we can do as follows:
Assume there is a paypal account to be already added.
1. entering on adding paypal screen by deep link
2. Textinput should be filled the original paypal account username
3. User update the username and click on `Save`
4. Original username should be updated
We don't need to have `Edit` button on modal.

**Comment by jfquevedol2198** [comment] 2023-07-06 11:29
My updated proposal doesn't include only your `Solution 1`, it includes to update Paypal username on the page with deep link `/add-paypal-me`

**Comment by jfquevedol2198** [comment] 2023-07-06 11:39
## [Updated Proposal]

### Please re-state the problem that we are trying to solve in this issue.
Payments - App allows to add paypal account using deep link even if paypal account is already added

### What is the root cause of that problem?
`Add Paypal` page doens't have validation whether or not  PaypalMe is already added.

### What changes do you think we should make in order to solve the problem?

1. If user visit by deep link (`/add-paypal-me`)
In this case, it won't only validate where or not Paypal is already added and return to `BasePaymentsPage`, and It will also try to update old Paypal account.
a. Entering on adding Paypal screen by deep link
b. Textinput should be filled the original paypal account username
c. User update the username and click on `Save`
d. Original paypal's username should be updated
Here is the video:

https://github.com/Expensify/App/assets/137529618/3d84815b-14d2-4081-a5e1-04e8e35ceaf9

3. If user wants to edit paypal account without deep link

<img width="439" alt="image" src="https://github.com/Expensify/App/assets/137529618/6c254848-121e-4a6e-be73-f00f3623d107">

We should have `Edit` button on above `Delete` button of modal, when click on `Edit` button, it will replay `1.b ~ 1.d`

### What alternative solutions did you explore? (Optional)

If PaypalMe is already added, call to go back.

1. add propTypes in `AddPaypalPage` component
```javascript
const propTypes = {
    /** Account details for PayPal.Me */
    payPalMeData: paypalMeDataPropTypes,

    ...withLocalizePropTypes,
};

const defaultProps = {
    payPalMeData: {},
};
```
2. update `AddPaypalPage` component by adding `payPalMeData` by `withOnyx`
```javascript
export default compose(
    withLocalize,
    withOnyx({
        payPalMeData: {
            key: ONYXKEYS.PAYPAL,
        }
    }),
)(AddPayPalMePage);
```
4. add code to go previous page if PaypalMe is already added
```javascript
useEffect(() => props.payPalMeData.description && Navigation.goBack(ROUTES.SETTINGS_PAYMENTS)
, [props.payPalMeData.description]);
```
<details><summary>Result</summary>

https://github.com/Expensify/App/assets/137529618/466e6544-30cc-4f70-b153-db0c546d869d

</details>

**Comment by lschurr** [comment] 2023-07-10 16:02
@eVoloshchak could you check this proposal?

**Comment by eVoloshchak** [comment] 2023-07-10 21:53
> Ok great. We should assign @hungvu193 - is that correct @eVoloshchak?

@lschurr, yeah, let's proceed with @hungvu193's proposal

**Comment by dhanashree-sawant** [comment] 2023-07-24 16:09
Thanks @lschurr, I have accepted the invite.

**Comment by lschurr** [comment] 2023-07-24 16:43
Great. Just waiting on @eVoloshchak and we can close this one out.

**Comment by eVoloshchak** [comment] 2023-07-25 16:44
@lschurr, this ended up being a feature request rather than a bug fix, so I don't think BZ checklist is applicable here
This also makes the original bug non-existent, so no regression test is needed

Requested the payment via NewDot

**Comment by lschurr** [comment] 2023-07-25 16:57
Perfect, thanks @eVoloshchak - closing this one out.

**Closed by lschurr** 2023-07-25 16:57 UTC
Labels: External, Daily, Awaiting Payment, Bug

**Comment by JmillsExpensify** [comment] 2023-07-27 03:58
@lschurr Can you please summarize the appropriate individual payments for all parties involved in this issue? This is holding up @eVoloshchak's NewDot payments. More information on this compliance process [in Slack](https://expensify.slack.com/archives/C01SKUP7QR0/p1690321157273869).

**Comment by JmillsExpensify** [comment] 2023-07-27 23:03
Reviewed details for @eVoloshchak. This is accurate based on summary from Business Reviewer and approved for payment in NewDot.
