### ISSUE TITLE
[HOLD] BUG: [mweb-safari] keyboard remains open while navigating back to LHN using fingers from right to left reported by @gadhiyamanan

### ISSUE THREAD

**Issue by kavimuru** [Expensify/App#11970] opened 2022-10-18 20:36 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:

1. Action performed:
2.  Open any conversation
3.  Open keyboard
4.  Close chat by swiping from left to right

## Expected Result:
keyboard should be closed

## Actual Result:
keyboard remains open

## Workaround:
unknown

## Platform:

Where is this issue occurring?

- Mobile Web - Safari

**Version Number:** v1.2.17-4
**Reproducible in staging?:** y
**Reproducible in production?:** y
**Email or phone of affected tester (no customers):** 
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** 

https://user-images.githubusercontent.com/43996225/196539070-780a6b4d-9ab4-495f-a592-f428a83e9986.MP4
https://user-images.githubusercontent.com/43996225/196539158-b33a7547-3df2-490d-ba7a-8766dcf6fb03.mp4

**Expensify/Expensify Issue URL:** 
**Issue reported by:** @gadhiyamanan
**Slack conversation:** https://expensify.slack.com/archives/C01GTK53T8Q/p1666117289545729

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by Nodirbek75** [comment] 2022-10-20 02:17
This issue can be solved by adding listener "beforeRemove" and inside function closing keyboard manually.

**Comment by Babur171** [comment] 2022-10-20 04:20
You can use KeyboardAvoidingView in scrollView. Then you solve this issue

**Comment by Babur171** [comment] 2022-10-22 11:35
@rushatgabhane can you share me your code?

**Comment by sakluger** [comment] 2022-11-01 06:28
Price doubled!

**Comment by s77rt** [comment] 2022-11-11 19:50
I can't reproduce, maybe it's fixed already?

**Comment by s77rt** [comment] 2022-11-16 15:02
### Proposal
```diff
diff --git a/src/libs/Navigation/Navigation.js b/src/libs/Navigation/Navigation.js
index e937e5015..8c484ce1e 100644
--- a/src/libs/Navigation/Navigation.js
+++ b/src/libs/Navigation/Navigation.js
@@ -1,6 +1,5 @@
 import _ from 'underscore';
 import lodashGet from 'lodash/get';
-import {Keyboard} from 'react-native';
 import {DrawerActions, getPathFromState, StackActions} from '@react-navigation/native';
 import Onyx from 'react-native-onyx';
 import Log from '../Log';
@@ -66,7 +65,6 @@ function openDrawer() {
     }
 
     navigationRef.current.dispatch(DrawerActions.openDrawer());
-    Keyboard.dismiss();
 }
 
 /**
diff --git a/src/libs/Navigation/NavigationRoot.js b/src/libs/Navigation/NavigationRoot.js
index 775d89f31..9dba24585 100644
--- a/src/libs/Navigation/NavigationRoot.js
+++ b/src/libs/Navigation/NavigationRoot.js
@@ -1,5 +1,6 @@
 import React from 'react';
 import PropTypes from 'prop-types';
+import {Keyboard} from 'react-native';
 import {NavigationContainer, DefaultTheme, getPathFromState} from '@react-navigation/native';
 import {useFlipper} from '@react-navigation/devtools';
 import Navigation, {navigationRef} from './Navigation';
@@ -60,7 +61,10 @@ const NavigationRoot = (props) => {
                     style={styles.navigatorFullScreenLoading}
                 />
             )}
-            onStateChange={parseAndLogRoute}
+            onStateChange={() => {
+                Keyboard.dismiss();
+                parseAndLogRoute();
+            }}
             onReady={props.onReady}
             theme={navigationTheme}
             ref={navigationRef}
```

### Details
The issue is more like a bug in Safari I suppose. The swipe gesture in Safari will trigger the browser back functionality. On chrome the browser back functionality also closes the keyboad. On Safari you have to do it yourself. Building on that we can simply call Keyboard.dismiss() on navigation change and since I see no case where the keyboard should stay open after navigation change I have put the logic on the root NavigationContainer.


https://user-images.githubusercontent.com/16493223/202214095-c611ee1d-4b99-42b8-9797-e2de7c3732b2.mp4


___

There is another similar issue which is more annoying that effects all the browsers (maybe native devices too) which is related to modals; Open any modal (e.g. Emoji Picker) press back button / swipe. The modal will stay there and will cause the app to be unusable. I do have a fix for that but I didn't include it in my above proposal; You can think that this can be solved using the same approach used here (on navigation change, close modal) but i have a better solution to fix the modal itself I have two proposals already that covers this https://github.com/Expensify/App/issues/10414#issuecomment-1314058212 and https://github.com/Expensify/App/issues/12521#issuecomment-1315059153

**Comment by s77rt** [comment] 2022-11-18 07:43
### Proposal (Updated)
```diff
diff --git a/src/libs/Navigation/Navigation.js b/src/libs/Navigation/Navigation.js
index e937e5015..8c484ce1e 100644
--- a/src/libs/Navigation/Navigation.js
+++ b/src/libs/Navigation/Navigation.js
@@ -1,6 +1,5 @@
 import _ from 'underscore';
 import lodashGet from 'lodash/get';
-import {Keyboard} from 'react-native';
 import {DrawerActions, getPathFromState, StackActions} from '@react-navigation/native';
 import Onyx from 'react-native-onyx';
 import Log from '../Log';
@@ -66,7 +65,6 @@ function openDrawer() {
     }
 
     navigationRef.current.dispatch(DrawerActions.openDrawer());
-    Keyboard.dismiss();
 }
 
 /**
diff --git a/src/libs/Navigation/NavigationRoot.js b/src/libs/Navigation/NavigationRoot.js
index 775d89f31..6b1c140a9 100644
--- a/src/libs/Navigation/NavigationRoot.js
+++ b/src/libs/Navigation/NavigationRoot.js
@@ -1,5 +1,6 @@
 import React from 'react';
 import PropTypes from 'prop-types';
+import {Keyboard} from 'react-native';
 import {NavigationContainer, DefaultTheme, getPathFromState} from '@react-navigation/native';
 import {useFlipper} from '@react-navigation/devtools';
 import Navigation, {navigationRef} from './Navigation';
@@ -60,7 +61,10 @@ const NavigationRoot = (props) => {
                     style={styles.navigatorFullScreenLoading}
                 />
             )}
-            onStateChange={parseAndLogRoute}
+            onStateChange={(state) => {
+                Keyboard.dismiss();
+                parseAndLogRoute(state);
+            }}
             onReady={props.onReady}
             theme={navigationTheme}
             ref={navigationRef}
```

### Update
I forgot to pass `state` to parseAndLogRoute function.

___

@rushatgabhane The IOUModal covers IOUAmount, IOUParticipants and IOUConfirm in one page and they are displayed based on the current step. Meaning IOUParticipants page -> IOUConfirmationPage does not introduce a navigation change thus the keyboard won't be dismissed. (Check src/pages/iou/IOUModal.js)

**Comment by marcaaron** [comment] 2022-11-21 23:11
Ah this looks related to the drawer navigator. I'd actually suggest we put it on HOLD pending the app navigation reboot.

**Comment by marcaaron** [comment] 2022-11-21 23:13
also seems kind of bad to dismiss the keyboard on every state change... I can think of some possibilities where we would not want to do that like going back to a previous page and focusing on an input (not sure if we do that anywhere but just saying it's quite the sledgehammer approach to this problem).

**Comment by marcaaron** [comment] 2022-11-21 23:16
@rushatgabhane let's wait for the reboot to fix this - it seems pretty minor.

@deetergp check out [the doc](https://docs.google.com/document/d/1cQ87HcDA9RrmBM4ch7PmlNi9N9ZP8abQuPF0gKYrxDE/edit) if you are curious about how the next navigation implementation will solve this problem

**Comment by s77rt** [comment] 2022-11-22 06:31
@marcaaron Going back a previous page will dismiss the keyboard then open it up for the input to be focused.
On Chrome, the keyboard will always be dismissed so we are actually matching the behaviour of Safari with Chrome.
I don't think the reboot will do anything about this because the back button does not go through any of the code it will simply call the browser's `history.back()` and the only way to catch it is via an event listener as in the proposed solution. I'm okay for the hold though.

**Comment by marcaaron** [comment] 2022-11-22 21:38
@s77rt We'll be sure to revisit this after we make the changes. Thanks for your thoughts!

**Comment by deetergp** [comment] 2022-11-28 19:35
Still on hold. Setting this to weekly till we take it off hold.

**Comment by JmillsExpensify** [comment] 2022-12-01 18:55
Taking this over as part of the broader App Navigation project.

**Comment by JmillsExpensify** [comment] 2022-12-05 13:33
Still on hold for the larger react navigation re-write.

**Comment by JmillsExpensify** [comment] 2022-12-12 12:32
Still on hold for the navigation re-write.

**Comment by JmillsExpensify** [comment] 2022-12-19 01:39
Still on hold for the navigation re-write.

**Comment by JmillsExpensify** [comment] 2022-12-27 20:01
Switched out weekly for monthly given that the navigation project is large and has no defined ETA.

**Comment by JmillsExpensify** [comment] 2023-01-11 05:39
Still on hold for the navigation project.

**Comment by JmillsExpensify** [comment] 2023-02-14 06:16
Same same.

**Comment by deetergp** [comment] 2023-03-21 18:20
Still in a holding pattern

**Comment by JmillsExpensify** [comment] 2023-03-28 12:47
Same same.

**Comment by deetergp** [comment] 2023-05-02 18:33
Still on hold.

**Comment by deetergp** [comment] 2023-06-03 00:00
MOTS (more of the same)

**Comment by JmillsExpensify** [comment] 2023-06-26 20:55
Alright, circling back on this one, I'm no longer able to reproduce. The keyboard consistently closes when going back to the LHN from a chat.

https://github.com/Expensify/App/assets/1127863/0dae424f-65d2-4ca2-8278-7b25125cf802

Accordingly, I think we're ready to pay @gadhiyamanan for reporting. If anyone disagrees or is able to achieve a different result, please comment in this issue. We'll be closing out payments later this week.

**Comment by deetergp** [comment] 2023-07-30 17:13
@JmillsExpensify Have we paid @gadhiyamanan for reporting? Can we close this one out?

**Comment by JmillsExpensify** [comment] 2023-08-01 05:52
Not yet, still working through issues. Though I will aim to circle back on this soon.

**Comment by deetergp** [comment] 2023-09-06 20:51
I believe we are still holding.

**Comment by JmillsExpensify** [comment] 2023-09-25 22:31
Alright, ready to close this out. @gadhiyamanan I've just send you an offer for reporting on Upwork.

**Comment by gadhiyamanan** [comment] 2023-09-26 02:16
@JmillsExpensify offer accepted, thanks!

**Comment by JmillsExpensify** [comment] 2023-10-08 14:11
All paid out! Thank you, closing.

**Closed by JmillsExpensify** 2023-10-08 14:11 UTC
Labels: External, Monthly, Bug
