### ISSUE TITLE
Android - Payments - The edited name of The PayPal method in offline mode is not grayed out

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#23282] opened 2023-07-20 15:37 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Open the App
2. Open with any account
3. Go to Settings -> Payments
4. Turn off the internet connection
5. Tap on the PayPal method -> Edit it -> Save

## Expected Result:
The edited name of The PayPal method in offline mode grayed out

## Actual Result:
The edited name of The PayPal method in offline mode is not grayed out
WS name that was edited offline grayed out.

## Workaround:
Uknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [ ] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 1.3.43-3
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/93399543/4c4f9c50-5e76-4a7d-a974-39fd528cb314

**Expensify/Expensify Issue URL:**
**Issue reported by:** Applause - Internal Team
**Slack conversation:**

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by alitoshmatov** [comment] 2023-07-20 15:55
## Proposal

### Please re-state the problem that we are trying to solve in this issue.

### What is the root cause of that problem?
We are not setting pending action in optimistic data 
### What changes do you think we should make in order to solve the problem?
In optimistic data of adding paypal account we should add pending action field to indicate it that it has action waiting for network
https://github.com/Expensify/App/blob/6d1f1f59f00cd12b305c4d579f90eae2eb5c387e/src/libs/actions/User.js#L496-L513
like so: `pendingAction: CONST.RED_BRICK_ROAD_PENDING_ACTION.ADD`

### What alternative solutions did you explore? (Optional)

**Comment by joekaufmanexpensify** [comment] 2023-07-21 12:57
Closing based on the discussion in the above thread, as this isn't a bug. Editing a paypal.me payment method works the same way offline as online, since all we validate is that the paypal.me username is >1 and <20 characters, and only numbers and letters. So no offline specific feedback is needed here.

**Closed by joekaufmanexpensify** 2023-07-21 12:57 UTC
Labels: Daily, Bug
