### ISSUE TITLE
[HOLD for payment 2024-12-20] [$250] Input lag and deletion issue in "Greater than" and "Less than" fields

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#51868] opened 2024-11-01 15:43 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 9.0.56-3
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**If this was caught on HybridApp, is this reproducible on New Expensify Standalone?:** Y
**If this was caught during regression testing, add the test name, ID and link from TestRail:** N/A
**Email or phone of affected tester (no customers):** applausetester+bm176@applause.expensifail.com
**Issue reported by:** Applause - Internal Team

**Issue found when executing PR** https://github.com/Expensify/App/pull/51202
## Action Performed:
1. Navigate to https://staging.new.expensify.com/
2. Go to Search > Filter > Total
3. In the Greater than field, try to type numbers quickly
4. Enter a few numbers and then attempt to delete all of them by tapping and holding the backspace key

## Expected Result:
When typing numbers quickly, the input should respond instantly, with no lag or delay. when holding down the backspace key, all characters should be deleted continuously without stopping until the field is empty

## Actual Result:
Typing numbers quickly in the "Greater than" field causes noticeable input lag, with some characters being skipped. when holding down the backspace key to delete all characters, only a few are removed, and the deletion process stops, leaving some characters in the field.

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Standalone
- [x] Android: HybridApp
- [ ] Android: mWeb Chrome
- [ ] iOS: Standalone
- [ ] iOS: HybridApp
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

<details>
  <summary>Add any screenshot/video evidence</summary>

  
</details> 

https://github.com/user-attachments/assets/5cfb4712-efe1-483e-a616-f6db7c076300

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~021859064491105055020</li>
        <li>Upwork Job ID: 1859064491105055020</li>
        <li>Last Price Increase: 2024-11-20</li>
<li>Automatic offers: </li>
<ul>
<li>rayane-djouah | Reviewer | 105000525</li>
</ul></li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @Christinadobrzyn</details>

**Comment by lanitochka17** [comment] 2024-11-01 15:44
We think that this bug might be related to #wave-control

**Comment by FitseTLT** [comment] 2024-11-01 15:47
This can be a regression from the linked pr tagging @s77rt

**Comment by s77rt** [comment] 2024-11-01 15:51
I'm not sure if it's a regression but I'm [reverting](https://github.com/Expensify/App/pull/51849) that PR. We can re-test after the revert

**Comment by Christinadobrzyn** [comment] 2024-11-04 03:49
Sounds good - @s77rt can you please keep us updated if we should restest this. Thanks!

**Comment by Christinadobrzyn** [comment] 2024-11-05 05:56
@s77rt looks like https://github.com/Expensify/App/pull/51849 is merged, can you retest and let me know if this is resolved?

**Comment by s77rt** [comment] 2024-11-05 07:50
@Christinadobrzyn It's not clear how to test the hybrid app. Let's wait for the PR to hit staging and ask applause to retest

**Comment by Christinadobrzyn** [comment] 2024-11-06 06:07
Sounds good - the PR is in staging so asking QA to test again - https://expensify.slack.com/archives/C9YU7BX5M/p1730873246313799

**Comment by Christinadobrzyn** [comment] 2024-11-07 07:03
Monitoring QA review

**Comment by Christinadobrzyn** [comment] 2024-11-08 04:53
bumping QA. https://expensify.slack.com/archives/C9YU7BX5M/p1731041562299329?thread_ts=1730873246.313799&cid=C9YU7BX5M

**Comment by Christinadobrzyn** [comment] 2024-11-11 05:26
Hi @s77rt Just a follow-up that QA reported this is still happening. 


https://github.com/user-attachments/assets/83a610fa-e6f3-4631-8ea3-baffe25c22b1


https://github.com/user-attachments/assets/7ac7ae9b-7c81-45f0-a161-0cec2d45e1fa

**Comment by s77rt** [comment] 2024-11-11 10:38
Right, this is `Internal` 👍

**Comment by Christinadobrzyn** [comment] 2024-11-13 06:23
Testing this, I can see the same thing happening in Safari. 

Is this even a bug? I feel like this might not be worth fixing right now. @s77rt do you think this is important to fix? It doesn't seem like it. 


https://github.com/user-attachments/assets/cf9ae045-29bd-42ff-a47c-6b3e3b0cf18f

**Comment by s77rt** [comment] 2024-11-13 09:47
I'm not able to reproduce the bug in Safari. The bug on the hybrid is worth investigation at least

**Comment by Christinadobrzyn** [comment] 2024-11-15 06:23
Asking SWM if they might be able to investigate this. https://expensify.slack.com/archives/C04878MDF34/p1731651775392719

**Comment by Christinadobrzyn** [comment] 2024-11-18 03:15
SWM is going to check schedules this week to see who has bandwidth this week to check this out.

**Comment by mateuuszzzzz** [comment] 2024-11-18 14:13
Hi @Christinadobrzyn! Is it confirmed at this point that the issue is exclusive to HybridApp?

It seems like it is also reproducible on standalone NewDot app:

> If this was caught on HybridApp, is this reproducible on New Expensify Standalone?: Y

**Comment by Christinadobrzyn** [comment] 2024-11-19 04:25
oh awesome! Thank you @mateuuszzzzz!

**Comment by mateuuszzzzz** [comment] 2024-11-19 12:59
Hi! I have an update. I updated branches to be up to date. It seems like on the latest main branches this bug is still reproducible on pure NewDot app. 

I suspect something might cause this regression to reappear, especially since we couldn’t reproduce it on the pure NewDot app yesterday

**Comment by Christinadobrzyn** [comment] 2024-11-20 02:42
Oh perfect! Thanks @mateuuszzzzz! Yes, let's move this external to free up your plate for other things. 

@rayane-djouah please see the [comment here](https://github.com/Expensify/App/issues/51868#issuecomment-2485651838) in terms of a fix - not sure if we need to be extra observant of a regression for this.

**Comment by 289Adam289** [comment] 2024-11-20 09:37
Hi! I am Adam from SWM, an expert agency, and I'd like to work on this.

**Comment by Christinadobrzyn** [comment] 2024-11-21 05:19
Hi @289Adam289! Thanks for joining us - @rayane-djouah what do you think is best? Should we take this to the team to dicsuss

**Comment by Christinadobrzyn** [comment] 2024-11-25 15:08
nudge @rayane-djouah for a [review and thoughts](https://github.com/Expensify/App/issues/51868#issuecomment-2489115925) - thanks!

**Comment by 289Adam289** [comment] 2024-11-25 16:42
I removed almost the entire app to confirm that the issue isn't due to a bug in React Native. I don't think it would be much of a help.
If needed, I can continue the investigation tomorrow and Wednesday to try to pinpoint the problem within the app.

**Comment by 289Adam289** [comment] 2024-11-28 17:52
Apologies for the delayed response. I was OOO on Tuesday and I got caught up with tasks related to `react-native-live-markdown`. However, I have made some progress in investigating this issue.

## Update:
After removing all patches and libraries directly connected to the keyboard. I then proceeded to remove sections of code to identify the root cause. I believe I have found the source of the bug - the `react-native-reanimated` library. Although I am not certain what specifically within reanimated is causing the issue, I have reached out to our open-source team that works on `reanimated` for further investigation. I will provide an update as soon as I have more information.

cc @rayane-djouah @Christinadobrzyn

**Comment by 289Adam289** [comment] 2024-12-02 17:07
## Update
I've discussed this issue with the `react-native-reanimated` team, and it turns out that the bug is more complex than it seems. The bug probably originates in React Native itself and is made visible by `react-native-reanimated`. The AutoCapitalization and the decimal-pad keyboard flags have the same bitwise value, which causes problems with the `setAutoCapitalize` method invoked on every keystroke after installing `ReanimatedCommitHook`. The ideal fix would involve an upstream PR in React Native and some internal changes in the `react-native-reanimated` library. Therefore, I would opt for a JS-only workaround I've proposed before for now.

I've checked, and the `DECIMAL_PAD` keyboard is used only three times in the app as stated by https://github.com/Expensify/App/issues/51868#issuecomment-2498485481. Replacing the keyboard type depending on the platform, with appropriate comments, should be sufficient while we wait for the fixes in React Native and `react-native-reanimated`. What do you think?
cc @rayane-djouah

**Comment by Christinadobrzyn** [comment] 2024-12-02 18:06
Amazing, thanks, @289Adam289! 

@rayane-djouah can you check this and let us know if this should be brought to the team or your thoughts? https://github.com/Expensify/App/issues/51868#issuecomment-2512185414

**Comment by 289Adam289** [comment] 2024-12-03 11:06
> @289Adam289 Does setting autoCapitalize TextInput's prop to a specific value fix this bug as a workaround?

To be honest I did not think about that. Passing down `autoCapitalize="words"` should help. Thanks to that `setAutoCapitalize` will not overwrite keyboard type.

**Comment by Christinadobrzyn** [comment] 2024-12-03 16:49
hey @techievivek when you're available can you review our options - If I understand these are our two options

1. https://github.com/Expensify/App/issues/51868#issuecomment-2512185414
2. https://github.com/Expensify/App/issues/51868#issuecomment-2514237595

Thanks!

**Comment by techievivek** [comment] 2024-12-05 15:26
I think we can proceed with the workaround for now, as fixing this upstream is likely to take a long time. For the solution, we can use `autoCapitalize="words"`, as it appears to be a platform-independent fix, right? However, we can also include a comment here.

**Comment by Christinadobrzyn** [comment] 2024-12-05 15:30
Awesome! Thanks @techievivek! Does this sound reasonable @rayane-djouah and @289Adam289?

**Comment by 289Adam289** [comment] 2024-12-05 15:31
Yeah, it is platform-independent workaround. Sounds good to me!

**Comment by 289Adam289** [comment] 2024-12-05 16:41
Should I start drafting a PR?

**Comment by techievivek** [comment] 2024-12-05 16:43
Yes, sure.

**Comment by Christinadobrzyn** [comment] 2024-12-09 23:46
monitoring PR https://github.com/Expensify/App/pull/53647

**Comment by Christinadobrzyn** [comment] 2024-12-17 16:16
Preparing for payment 

Contributor+: @rayane-djouah owed $250 via Upwork (https://www.upwork.com/nx/wm/offer/105000525)

**Comment by Christinadobrzyn** [comment] 2024-12-20 21:29
Payment day - payment summary here - https://github.com/Expensify/App/issues/51868#issuecomment-2541727144

Paid out- closing!

**Closed by Christinadobrzyn** 2024-12-20 21:29 UTC
Labels: External, Daily, Awaiting Payment, Bug
