### ISSUE TITLE
[Payment Due] [$500] Web - hovering on the Default currency list of workspace setting leaves the last hovered currency on focus

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#28041] opened 2023-09-22 18:39 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Open Settings
2. Click on workspace
3. Select a workspace
4. Click on Settings
5. Click on Default currency
6. Hover over the currency list and move the cursor off the list

## Expected Result:
The focus should be off when the cursor is moved out of the currency list

## Actual Result:
The focus stays on the last hovered currency when the cursor is moved out of the currency list

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [ ] Windows / Chrome
- [ ] MacOS / Desktop

**Version Number:** 1.3.73.0
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/93399543/6c62d416-e5e1-413b-b576-0a6744b9a078

https://github.com/Expensify/App/assets/93399543/1c7cbdad-6cec-440b-9240-bff0bb913cf2

**Expensify/Expensify Issue URL:**
**Issue reported by:** @jo-ui
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1695236188869459

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~0104c814b5c57b5f48</li>
        <li>Upwork Job ID: 1705290725148950528</li>
        <li>Last Price Increase: 2023-10-16</li>
    </ul>
</details>

**Comment by neg-0** [comment] 2023-09-23 01:44
I'm unable to reproduce this when running locally on macOS Chrome and Safari, or in staging on macOS Chrome and Safari. I'll try with Windows and see if I can reproduce it.

**Comment by burczu** [comment] 2023-09-25 12:34
I'm also unable to reproduce it on macOS with Safari, and as @dukenv0307 pointed out, it's the default behaviour on Windows, so I think we should perhaps re-think if this is a bug or not.

**Comment by burczu** [comment] 2023-09-29 11:31
@dukenv0307 I think making this consistent makes sense, but I think it's better to choose you alternative solution with `CurrencyPicker` modal instead of creating/using the whole page - what we have here is just a form input, so no need to keep navigation while refreshing the page etc.

That being said, if we agree it is a bug, I think we could choose [this proposal](https://github.com/Expensify/App/issues/28041#issuecomment-1732201275) to consider.

🎀 👀 🎀 C+ reviewed

**Comment by burczu** [comment] 2023-10-04 06:56
Good catch @dukenv0307! I agree that we should put this on hold because that future request should fix this issue.

**Comment by mvtglobally** [comment] 2023-10-05 03:07
Issue not reproducible during KI retests. (First week)

**Comment by burczu** [comment] 2023-10-20 06:49
@techievivek I can confirm that this bug does not occur anymore on `main` - we now use custom selector for workspace currency.

**Comment by techievivek** [comment] 2023-10-25 05:29
Ok, great. Thanks for looking into it.

**Comment by techievivek** [comment] 2023-11-30 07:23
Sorry, I missed the last ping. @peterdbarkerUK, do you have any thoughts here?  Originally, @dukenv0307 was assigned to work on this bug, and their proposal was chosen [here](https://github.com/Expensify/App/issues/28041#issuecomment-1740742519). However, due to a simultaneous refactoring effort, the issue was put on HOLD. Eventually, the problem was resolved through the refactoring, and we closed the GH. Should we be compensating the contributor here?

**Comment by techievivek** [comment] 2023-12-18 05:43
Gentle bump @peterdbarkerUK can you please review the compensation here? Thanks

**Comment by techievivek** [comment] 2024-01-02 05:49
Bumped @peterdbarkerUK in DM, we will soon review the compensation status here. Thanks

**Comment by peterdbarkerUK** [comment] 2024-01-04 15:44
Hey folks - I'm sorry, I missed this when I got sick right before the holidays. Going to discuss internally.

**Comment by peterdbarkerUK** [comment] 2024-01-05 15:07
Hey @dukenv0307 thank for raising this! 

I've looked into it and come out with the following timeline, would you agree this is about right? 

- Sep 22, issue posted.
- Sep 23, solution proposed.
- Sep 29, solution accepted.
- Oct 3, work begun on solution, PR resolving issue uncovered, solution placed on hold. 
- Oct 16 PR deployed, issue resolved.

**Comment by techievivek** [comment] 2024-01-15 07:03
Not overdue, @dukenv0307 gentle bump ^

**Comment by mountiny** [comment] 2024-01-15 14:32
Unassigned @burczu as no payment is required and they are not c+ anymore

**Comment by techievivek** [comment] 2024-01-29 07:42
Not overdue, @peterdbarkerUK, can you please review the compensation here? @dukenv0307 agreed with the above timeline https://github.com/Expensify/App/issues/28041#issuecomment-1878822042

**Comment by alexpensify** [comment] 2024-02-02 22:12
@dukenv0307 - sorry for the slow action here, I'm catching up and will complete this process on Monday. 

I see the timeline was agreed to here: https://github.com/Expensify/App/issues/28041#issuecomment-1878822042

I need to now figure out the payment breakdown and make sure there is an Upwork job for it.

**Comment by techievivek** [comment] 2024-02-05 13:15
@alexpensify, thanks for taking a look into it. To provide some context, @dukenv0307 initially proposed a solution for this GH issue, which was [approved](https://github.com/Expensify/App/issues/28041#issuecomment-1740742519) by @burczu(Callstack team). However, @dukenv0307 mentioned that a similar bug was being addressed concurrently, so we decided to put this solution on hold. Subsequently, after merging the hold PR, we discovered that the bug was [resolved](https://github.com/Expensify/App/issues/28041#issuecomment-1772180536).

As mentioned by @dukenv0307 [here](https://github.com/Expensify/App/issues/28041#issuecomment-1784456253), we encountered similar cases in the past, but the contributors were compensated in full. Please let me know if you want any help. Thanks 🙇

**Comment by alexpensify** [comment] 2024-02-05 23:55
Here is the payment summary: 

-  External issue reporter - N/A since the issue was addressed in another GH 
-  Contributor that fixed the issue - $500 @dukenv0307 for working on the PR 
-  Contributor+ that helped on the issue and/or PR - N/A since this issue was addressed in another GH and the C+ is part of Callstack

Upwork Job: https://www.upwork.com/jobs/~0104c814b5c57b5f48

**Comment by alexpensify** [comment] 2024-02-05 23:56
@dukenv0307 thanks again for your patience-- I've completed the process in Upwork. Closing!

**Closed by alexpensify** 2024-02-05 23:56 UTC
Labels: Daily, Internal, Bug
