### ISSUE TITLE
mWeb - Chat - Context menu not opened on long pressing a message

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#47659] opened 2024-08-19 19:19 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 9.0.22
**Reproducible in staging?:** Y
**Reproducible in production?:** N
**If this was caught during regression testing, add the test name, ID and link from TestRail:** N/A
**Email or phone of affected tester (no customers):** applausetester+14081alsn@applause.expensifail.com
**Issue reported by:** Applause - Internal Team

## Action Performed:
1. Launch site
2. Open a chat
3. Send a message
4. Long press the message and try ti open context menu

## Expected Result:
Context menu be opened on long pressing a message

## Actual Result:
Context menu not opened on long pressing a message

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [x] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [ ] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details> 

https://github.com/user-attachments/assets/ac76fce4-9075-478d-80c1-5942d8b4d4f5

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by lanitochka17** [comment] 2024-08-19 19:20
We think that this bug might be related to #vip-vsp

**Comment by luacmartins** [comment] 2024-08-20 13:44
Can't reproduce on the simulator, but we did reproduce on a physical device

**Comment by luacmartins** [comment] 2024-08-20 14:34
I created a revert of the PR above and will run adhoc builds to test it on a physical device.

**Comment by luacmartins** [comment] 2024-08-20 21:50
Fixed in staging. Closing.

**Closed by luacmartins** 2024-08-20 21:50 UTC
Labels: Reviewing, Engineering, Weekly
