### ISSUE TITLE
[$250]  iOS - Track expense - App crashes when opening receipt immediately after taking photo

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#45525] opened 2024-07-16 20:39 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 9.0.7-4
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**If this was caught during regression testing, add the test name, ID and link from TestRail:** https://expensify.testrail.io/index.php?/tests/view/4726931
**Issue reported by:** Applause - Internal Team

## Action Performed:
1. Launch New Expensify app
2. Go to self DM
3. Submit a track manual expense (without receipt)
4. Go to transaction thread
5. Tap on the receipt placeholder
6. Take a photo
7. Quickly tap on the receipt again after taking photo (crash occurs when the receipt is showing spinner)
8. Might need to repeat Step 3 to 7 if crash does not occur

## Expected Result:
App will not crash

## Actual Result:
App crashes

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [x] iOS: Native
- [ ] iOS: mWeb Safari
- [ ] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details> 

https://github.com/user-attachments/assets/b7e54bdd-e958-48f6-8ff8-4f52db70fbb7

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01bb867405e1f4dcc2</li>
        <li>Upwork Job ID: 1814074453026656927</li>
        <li>Last Price Increase: 2024-08-15</li>
    </ul>
</details>

**Comment by lanitochka17** [comment] 2024-07-16 20:43
@adelekennedy  FYI I haven't added the External label as I wasn't 100% sure about this issue. Please take a look and add the label if you agree it's a bug and can be handled by external contributors

**Comment by lanitochka17** [comment] 2024-07-16 20:43
We think that this bug might be related to #vip-vsp

**Comment by adelekennedy** [comment] 2024-07-16 22:57
@justinpersaud can this be worked on my an external engineer? My assumption is that this issue will need someone from Expensify to triage it first and then possibly open to an external contributor - what do you think?

**Comment by adelekennedy** [comment] 2024-07-18 23:06
reproduced!

**Comment by adelekennedy** [comment] 2024-08-05 23:23
still waiting for poropsals

**Comment by adelekennedy** [comment] 2024-08-05 23:24
still waiting for proposals

**Comment by adelekennedy** [comment] 2024-08-08 17:34
@shubham1206agra I'm sorry I missed your comment earlier! I'm not sure how to get the logs when testing on an actual mobile device - I can try on browserstack to see if that's repeatable

**Comment by adelekennedy** [comment] 2024-08-09 21:55
@lanitochka17 any help with logs here?

**Comment by lanitochka17** [comment] 2024-08-12 13:26
@adelekennedy 
[logs (2).txt](https://github.com/user-attachments/files/16582567/logs.2.txt)

**Comment by adelekennedy** [comment] 2024-08-12 22:02
Thank you @lanitochka17! @shubham1206agra

**Comment by adelekennedy** [comment] 2024-08-15 16:24
I'm closing this as we're not able to reproduce any more!

**Closed by adelekennedy** 2024-08-15 16:24 UTC
Labels: External, Daily, Help Wanted, Overdue, Bug
