### ISSUE TITLE
[HOLD for payment 2023-08-16] [$1000] mweb - Conversation - Login field is focused when sign out in offline mode

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#23797] opened 2023-07-28 14:35 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Login to NewDot
2. Disable the internet connection
3. Tap on a few chats in LHN
4. Tap Settings
5. Tap Sign out
6. Enable the internet connection

## Expected Result:
When Login page appear the login field should not be focused (cursor should not be shown on the input field)

## Actual Result:
The login field is focused (cursor is shown on the input field)

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [x] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [ ] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 1.3.44-0
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/93399543/9fa08dc1-f26b-435c-bdd0-cb79856aaf67

**Expensify/Expensify Issue URL:**
**Issue reported by:** Applause - Internal Team
**Slack conversation:**

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~012346a785d1fce53c</li>
        <li>Upwork Job ID: 1685011419766251520</li>
        <li>Last Price Increase: 2023-07-28</li>
<li>Automatic offers: </li>
<ul>
<li>hoangzinh | Contributor | 25890078</li>
</ul></li>
    </ul>
</details>

**Comment by CortneyOfstad** [comment] 2023-07-28 19:36
Was able to recreate — getting eyes on this

**Comment by donlaiq** [comment] 2023-07-30 00:00
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
Login field is focused every time the login screen is reached.

### What is the root cause of that problem?
The `ref={input}` attribute of the `TextInput` element on `App/src/pages/signin/LoginForm.js`.

### What changes do you think we should make in order to solve the problem?
At first sight, if it doesn't affect another part of the application, just removing it will solve the problem.


https://github.com/Expensify/App/assets/10087643/34b964fc-333f-470a-aa33-3f359e56fb63

**Comment by donlaiq** [comment] 2023-07-30 00:06
Contributor details
Your Expensify account email: donlaiq@gmail.com
Upwork Profile Link: https://www.upwork.com/freelancers/~017244f379211cb72b

**Comment by CortneyOfstad** [comment] 2023-08-01 20:22
@thesahindia any thoughts on the proposal above?

Also, I'm heading OoO until 8/14, so reassigning BZ to keep an eye on this while I'm out 👍

**Comment by CortneyOfstad** [comment] 2023-08-16 14:34
@thesahindia bump on the checklist above ^^^

**Comment by CortneyOfstad** [comment] 2023-08-18 13:58
Payment has been made to @hoangzinh and contract completed in UpWork! 

Bump @thesahindia on the checklist above so we can close this out 👍

**Comment by CortneyOfstad** [comment] 2023-08-21 13:36
Regression test has been linked above, so this can be closed! Thanks all1

**Closed by CortneyOfstad** 2023-08-21 13:36 UTC
Labels: External, Weekly, Awaiting Payment, Bug

**Comment by JmillsExpensify** [comment] 2023-08-24 05:32
Reviewed the details for @thesahindia. $1,500 approved for payment (equivalent to C) based on BZ summary above.
