### ISSUE TITLE
Web - OldDot transition tests - New workspace created when selecting free plan under Pricing from OldDot

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#13439] opened 2022-12-08 16:09 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Open staging.new.expensify.com and log out.
2. Navigate to OldDot and sign in with any account that has an existing Workspace.
3. Navigate to staging.expensify.com/pricing and select the "Free Plan".
4. Verify you're redirected to NewDot > Workspace settings of a pre-existing workspace.
5. Verify that you're logged in with the same account as in OldDot.
6. Tap on the back button and Verify that no Workspace was created.

## Expected Result:
No workspace should be created after executing above TC.

## Actual Result:
New workspace created when going to staging.expensify.com/pricing and selecting the "Free Plan" option.

## Workaround:
Unknown

## Platform:

Where is this issue occurring?

- Web

**Version Number:** 1.2.37.0

**Reproducible in staging?:** Yes

**Reproducible in production?:** Yes

**Email or phone of affected tester (no customers):** 

**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Notes/Photos/Videos:** Any additional supporting documentation

https://user-images.githubusercontent.com/93399543/206499247-e4e4b7b7-6f53-4329-a3d9-90c60a51ffa5.mp4

**Expensify/Expensify Issue URL:** 

**Issue reported by:** Applause - Internal Team

**Slack conversation:** 

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by kbecciv** [comment] 2022-12-08 16:11
QA team is failing TR steps https://expensify.testrail.io/index.php?/tests/view/2990706

![image](https://user-images.githubusercontent.com/93399543/206499677-d90bb0e1-8a52-41d5-bfd8-498d727d94bd.png)

**Comment by joekaufmanexpensify** [comment] 2022-12-08 21:34
@kbecciv Just to confirm, your most recent comment is just indicating that you think this is a regression right?

**Comment by joekaufmanexpensify** [comment] 2022-12-09 19:51
Triaging:

From this SO: https://stackoverflow.com/c/expensify/questions/14418
- [ ] **The "bug" is actually a bug**: 
- [ ] **The bug is not a duplicate report of an existing GH (close the GH and add any novel details to the original GH instead)**: 
- [ ] **The bug is reproducible, following the reproduction steps:**
- [ ] **If you're unable to reproduce the bug, add the _Needs reproduction_ label. Comment on the issue outlining the steps you took to try to reproduce the bug, your results and tag the issue reporter and the Applause QA member who created the issue. Ask them to clarify reproduction steps and/or to check the reproduction steps again. Close issue.**: 
- [ ] **The GH template is filled out as fully as possible -- this means the GH body and title are clear (ie. could an external contributor understand it and work on it?):** 
- [ ] **The GH was created by an Expensify employee or a QA tester:** 
- [ ] **If the bug is an OldDot issue, you should decide whether it is widespread enough to justify fixing or it is better to wait for reunification. If it's better to wait, close the GH & provide this justification:** 
- [ ] **If there's a link to Slack, check the discussion to see if we decided not to fix it:** 
- [ ] **Decide if the GH should be resolved by an External contributor or Internal engineer, add the appropriate label:**

**Comment by joekaufmanexpensify** [comment] 2022-12-09 19:52
I was able to reproduce this on web, as shown below. Given there is an existing regression test for this, I expect it is a bug. Although I am not too familiar with this flow, so validating in Slack before proceeding. 

![2022-12-09_14-49-37 (1)](https://user-images.githubusercontent.com/54866469/206785590-02e93e0f-3ddc-41bc-916f-2270e94bec51.gif)

**Comment by joekaufmanexpensify** [comment] 2022-12-09 20:11
Posted [here. ](https://expensify.slack.com/archives/C049HHMV9SM/p1670616670249929)

**Comment by joekaufmanexpensify** [comment] 2022-12-12 13:43
Not overdue.

**Comment by joekaufmanexpensify** [comment] 2022-12-13 16:01
Same.

**Comment by neil-marcellini** [comment] 2022-12-13 16:45
I'm happy to work on a fix for this if we decide that it's actually a problem.

**Comment by joekaufmanexpensify** [comment] 2022-12-13 18:57
This is expected behavior now, per this [discussion. ](https://expensify.slack.com/archives/C049HHMV9SM/p1670957850082509?thread_ts=1670616670.249929&cid=C049HHMV9SM) Closing!

**Closed by joekaufmanexpensify** 2022-12-13 18:57 UTC
Labels: Daily, Bug
