### ISSUE TITLE
[$250] Android - App crashes when returning to submit expense after it was uncomplete

### ISSUE THREAD

**Issue by m-natarajan** [Expensify/App#43374] opened 2024-06-10 14:29 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.81-1
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:** n/a
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** Applause internal team
**Slack conversation:**

## Action Performed:
1. Open mobile application
2. FAB > Submit expense
3. Distance > enter Start and Finish waypoints
4. Choose account or workspace (DO NOT submit request)
5. Open another application (e.g. mobile browser) for a while
6. Return to Expensify mobile application (wait until it reloads)
7. Repeat steps 2 and 3

## Expected Result:
Unsubmitted request closes after user navigated to another application.
User can start anew Submit expense request and finish it.

## Actual Result:
Application crashes.

## Workaround:
unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [ ] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

https://github.com/Expensify/App/assets/38435837/398453e6-5f18-47f8-9c01-8a9be320ecd7

[Bug6507433_1718009701451!logs-2024-06-10_08_53_14.511.txt](https://github.com/user-attachments/files/15774828/Bug6507433_1718009701451.logs-2024-06-10_08_53_14.511.txt)

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01e63c58c588ffca02</li>
        <li>Upwork Job ID: 1800236567983819613</li>
        <li>Last Price Increase: 2024-07-01</li>
<li>Automatic offers: </li>
<ul>
<li>shubham1206agra | Reviewer | 102979274</li>
</ul></li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @shubham1206agra</details>

**Comment by m-natarajan** [comment] 2024-06-10 14:30
@isabelastisser FYI I haven't added the External label as I wasn't 100% sure about this issue. Please take a look and add the label if you agree it's a bug and can be handled by external contributors

**Comment by isabelastisser** [comment] 2024-06-17 14:36
No proposals yet.

**Comment by isabelastisser** [comment] 2024-06-18 15:44
No proposals yet.

**Comment by isabelastisser** [comment] 2024-06-20 20:16
Still waiting for proposals.

**Comment by isabelastisser** [comment] 2024-06-24 15:37
No proposals yet.

**Comment by isabelastisser** [comment] 2024-06-25 17:23
@shubham1206agra I DM'd you for visibility.

**Comment by isabelastisser** [comment] 2024-06-26 23:39
@shubham1206agra were you able to test this? Thanks!

**Comment by isabelastisser** [comment] 2024-06-27 18:27
Asking in Slack: https://expensify.slack.com/archives/C03UK30EA1Z/p1719512815525039

**Comment by TMisiukiewicz** [comment] 2024-06-28 14:05
Hi, I'm Tomasz from Callstack and I'm looking into this issue. 

@shubham1206agra what device are you using for testing? For me, on a mid-tier device with 8gb of RAM, the issue was not reproducible, because the app was not killed in the background even once.

However, things were different on an emulator. Because of the Android memory management, the backgrounded app is being killed to free up resources for a foregrounded app. In this case I was able to reproduce it and catch the error:
<img width="340" alt="image" src="https://github.com/Expensify/App/assets/13985840/5658702f-215a-465d-bcbc-6e1768933f50">

Seems like in this particular scenario, somehow the app is not able to correctly render the map view again. I'm going to continue investigating it on Monday

**Comment by TMisiukiewicz** [comment] 2024-07-01 14:21
Still investigating. As comment [here](https://github.com/rnmapbox/maps/issues/3016#issuecomment-1698026290) says, looks like it's an upstream issue with `mapbox-maps-android` and the thrown error comes from this. Gonna continue investigating tomorrow

**Comment by TMisiukiewicz** [comment] 2024-07-02 13:56
I think I found a possible issue - looks like sometimes the Map View is rendered before the accessToken is set on the native side. I have the solution implemented but I need to do some more tests to see if it does not break anything on other platforms. If everything's fine, I'll share a proposal tomorrow 👍

**Comment by TMisiukiewicz** [comment] 2024-07-03 09:23
### Problem
The `MapView` component is rendered when `accessToken` is available. The `accessToken` needs to be set in the library and passed to its native dependency. There are situations where there is a race condition - a `MapView` component is being rendered because `accessToken` is already read from the Onyx, however it is not yet set on the native side.

### Solution
The `rnmapbox` library exposes `setAccessToken` function, which is required to call when using the library. This function returns a promise, so we can add an additional state and set it to `true` when access token is set in a library. If we switch from rendering the `MapView` when `accessToken` is available to when the  access token is set on the native side, we make sure it is not trying to render a Map before access token is set.

Create a draft PR #44767 with the required changes. Let me know your thoughts about the proposal, I can open it if you think this solution is good

**Comment by TMisiukiewicz** [comment] 2024-07-03 09:59
PR open ✅

**Comment by deetergp** [comment] 2024-07-03 19:56
You kinda jumped the gun there @TMisiukiewicz. You haven't been assigned to the issue yet, because an internal engineer needs to review proposal, and an Upwork job has not been created.

**Comment by isabelastisser** [comment] 2024-07-18 20:04
@shubham1206agra, can you please provide an update? Thanks!

**Comment by isabelastisser** [comment] 2024-08-08 14:55
@shubham1206agra, I sent you a new offer in Upwork.

Can you please clarify if we need to create a regression test? Thanks!

**Comment by isabelastisser** [comment] 2024-08-08 18:40
Thanks! The payment is processed.

All set.

**Closed by isabelastisser** 2024-08-08 18:40 UTC
Labels: Reviewing, External, Weekly, Bug
