### ISSUE TITLE
Part of LHN reloads when going back in browser history - @mdneyazahmad

### ISSUE THREAD

**Issue by mvtglobally** [Expensify/App#9708] opened 2022-07-05 17:55 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/docs/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Open app on web (https://new.expensify.com/)
2. Visit some reports
3. Click back button
4. Click forward button until you reach last page
5. Now press back button

## Expected Result:
It should not reload

## Actual Result:
Part of LHN reloads

## Workaround:
Can the user still use Expensify without this being fixed? Have you informed them of the workaround?

## Platform:

Where is this issue occurring?

- Web

**Version Number:** 1.1.79-0
**Reproducible in staging?:** Y 
**Reproducible in production?:** Y
**Email or phone of affected tester (no customers):** 
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation 

https://user-images.githubusercontent.com/43995119/177387415-c0b5ccfb-db73-4a34-a8b9-f3a24dbed4c9.mp4

**Expensify/Expensify Issue URL:** 
**Issue reported by:** @mdneyazahmad
**Slack conversation:** https://expensify.slack.com/archives/C01GTK53T8Q/p1655127317981849

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by flaviadefaria** [comment] 2022-07-05 18:08
I'm not sure that I get this one. Why would someone go back in browser history and if you go back then what would you expect to happen?

I'll add the engineering label for a second opinion.

**Comment by tgolen** [comment] 2022-07-05 21:48
@mdneyazahmad Why shouldn't it reload? I'd be kind of interested to understand why it appears to reload, but I don't think there is a problem with it reloading. I think the problem is that it's a flash of no content while it reloads. If we can prevent that flash, then I think everything is OK.

If there is a pretty simple solution to this, let's do it, but if it's going to be complex, I'd skip it.

**Comment by tgolen** [comment] 2022-07-19 20:14
No answer to my previous question, so I'm just going to close this.

**Closed by tgolen** 2022-07-19 20:14 UTC
Labels: Engineering, Daily, Overdue
