### ISSUE TITLE
[HOLD for payment 2023-12-12] Task - Assignee with custom avatar shows default avatar in the task report

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#31028] opened 2023-11-07 20:25 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** .3.96-5
**Reproducible in staging?:** Y
**Reproducible in production?:** N
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** Applause - Internal Team
**Slack conversation:**

**Issue found when executing PR** https://github.com/Expensify/App/pull/30515
## Action Performed:
1. Navigate to staging.new.expensify.com
2. Go to chat with user that has a custom avatar
3. Click + > Assign task
4. Create a task and assign the same user in Step 1 as assignee
5. Open the task report

## Expected Result:
The assignee in the task report shows the custom avatar

## Actual Result:
The assignee in the task report shows the default avatar instead of the custom avatar

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [x] Android: mWeb Chrome
- [x] iOS: Native
- [x] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details>  

https://github.com/Expensify/App/assets/78819774/6d7222dc-0994-4eea-8e7a-64c5fed991c2

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by abzokhattab** [comment] 2023-11-07 21:32
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
Task asignee with custom avator shows the default avatar in the task report view

### What is the root cause of that problem?
in the following line, the `props.personalDetails` is `undefined` because we dont connect to onyx to get the personal details object: 
https://github.com/Expensify/App/blob/5d45f0f6c86e97d4ae58ac167b6c162a610b817c/src/components/ReportActionItem/TaskView.js#L150
### What changes do you think we should make in order to solve the problem?
either by adding: 

```js
    const personalDetails = usePersonalDetails() ?? CONST.EMPTY_OBJECT;

```
and update the line above to use this const


OR by connecting to the onyx in the component:
```js
     withOnyx({
         personalDetails: {
             key: ONYXKEYS.PERSONAL_DETAILS_LIST,
         },
     }),
```

**Comment by isabelastisser** [comment] 2023-11-08 16:04
Hey @Li357, what's the next step here? Did you review the proposals above? Thanks!

**Comment by Li357** [comment] 2023-11-08 16:10
Both proposals had the correct RCA, so I'm going to go with @abzokhattab who was first. Can we make sure to do what @dukenv0307 suggest though, to use the hook everywhere we have the HOC withCurrentUserPersonalDetails? I think uniformity and moving to functional components is the goal here.

**Comment by puneetlath** [comment] 2023-11-08 17:57
Given this relates to tasks, I"m going to remove it as a deploy blocker. Let's still fix it asap though.

**Comment by abzokhattab** [comment] 2023-11-08 19:09
Here are the changes https://github.com/Expensify/App/pull/31076 will add the screenshots/tests and mark it as ready

**Comment by rushatgabhane** [comment] 2023-11-19 12:27
@abzokhattab is the PR ready for review? Please change the status

**Comment by abzokhattab** [comment] 2023-11-19 19:44
PR is ready

**Comment by abzokhattab** [comment] 2023-11-19 19:45
Also please note that the offer has not been sent yet

**Comment by isabelastisser** [comment] 2023-11-30 20:41
PR has not merged yet. I will create the offer when the payment is due.

**Comment by abzokhattab** [comment] 2023-12-01 13:41
hey @isabelastisser  the pr is deployed on staging

**Comment by isabelastisser** [comment] 2023-12-11 17:56
@abzokhattab, can you please complete the checklist above? 

Payment is due tomorrow.

**Comment by abzokhattab** [comment] 2023-12-12 05:22
Hi @isabelastisser I guess you meant @Li357 right?

**Comment by isabelastisser** [comment] 2023-12-12 13:44
@Li357 do you need to complete the checklist above?

**Comment by isabelastisser** [comment] 2023-12-13 18:48
Offer sent in Upwork.

**Comment by abzokhattab** [comment] 2023-12-13 21:13
Thanks @isabelastisser I don't think we need a regression test for this as the changes included minor refactoring.

**Comment by isabelastisser** [comment] 2023-12-14 18:05
Sounds good. All set!

**Closed by isabelastisser** 2023-12-14 18:05 UTC
Labels: Engineering, Daily, Awaiting Payment, Bug
