### ISSUE TITLE
[HOLD for payment 2024-02-07] [$500] Workplace - User is unable to return back to homepage after clicking “here” in Concierge chat

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#34456] opened 2024-01-12 17:48 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.24-4
**Reproducible in staging?:** Y
**Reproducible in production?:** No
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** Applause - Internal Team
**Slack conversation:**

## Action Performed:
1. Open any Workplace setting and select Bank account
2. Select "connect manually" and go through process until Concierge chat to validate bank account
3. In Concierge chat, click on "here" to review and make necessary changes
4. A "Hmm, its not here" page should display and click on "Go back to home page"

## Expected Result:
User should be directed to home page

## Actual Result:
User is sent back to Connect Bank Account page. Selecting back button on this page leads to a loop which sends user to the Workplace's setting page then immediately back to "Connect Bank Account"

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [ ] Android: mWeb Chrome
- [x] iOS: Native
- [ ] iOS: mWeb Safari
- [ ] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details> 

https://github.com/Expensify/App/assets/78819774/e97e726c-493d-4d51-bea7-d95e952cd394

https://github.com/Expensify/App/assets/78819774/1f5e453d-0305-4cff-8d8b-c5d7fa817dd0

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01056d0ac9c53002bf</li>
        <li>Upwork Job ID: 1746702570069852160</li>
        <li>Last Price Increase: 2024-01-22</li>
<li>Automatic offers: </li>
<ul>
<li>hoangzinh | Reviewer | 28120500</li>
<li>bernhardoj | Contributor | 28120501</li>
</ul></li>
    </ul>
</details>

**Comment by okhot** [comment] 2024-01-15 01:58
**Proposal**

**Problem re-statement:**

The identified issue revolves around users encountering a repetitive loop when attempting to navigate back using the back button, consistently landing them on the "Connect Bank Account" page. This loop takes them through the Workplace's setting page and back to "Connect Bank Account."

**Root Cause Analysis:**

The core problem stems from the omission of passing the onClick action for navigating to the home page when users encounter an unauthorized workspace. The Page not found view, responsible for displaying the workspace unauthorized page, lacks the necessary handling for users trying to return home. This absence results in an ongoing loop, creating frustration for the users.

**Recommended Course of Action:**

To tackle this issue effectively, it is suggested to include the onClick action for navigating to the home page in The Page not found view. This adjustment ensures that users, upon facing unauthorized access, are promptly redirected to the home page, breaking the loop.

**Comment by okhot** [comment] 2024-01-15 02:21
Contributor details
Your Expensify account email: arreyetta1jnr@gmail.com
Upwork Profile Link: https://www.upwork.com/freelancers/~01de3d646530efa373

**Comment by eh2077** [comment] 2024-01-15 03:34
## Proposal

### Please re-state the problem that we are trying to solve in this issue.

Workplace - User is unable to return back to homepage after clicking “here” in Concierge chat.

### What is the root cause of that problem?

The root cause of this issue is that we call 

https://github.com/Expensify/App/blob/a2864a077fd5d577021983ff77c658c9f2e43bab/src/components/BlockingViews/FullPageNotFoundView.tsx#L52

by default when clicking `Go back to home page`

As we don't pass `targetReportId` to method `dismissModal`, so it'll navigate to the previous Connect Bank Account page, see

https://github.com/Expensify/App/blob/a2864a077fd5d577021983ff77c658c9f2e43bab/src/libs/Navigation/dismissModal.ts#L48

### What changes do you think we should make in order to solve the problem?

To fix this issue, we can improve `FullPageNotFoundView.tsx` by 

1. Make property `onLinkPress` as optional in `FullPageNotFoundViewProps`

2. Change the default value of `onLinkPress` 

https://github.com/Expensify/App/blob/a2864a077fd5d577021983ff77c658c9f2e43bab/src/components/BlockingViews/FullPageNotFoundView.tsx#L52

to `undefined`, like

```js
onLinkPress = undefined,
```

3. Pass `onLinkPress` property to `BlockingView` by

```js
// if onLinkPress is defined, then return onLinkPress
// if onLinkPress is undefined, then return () => Navigation.goBack(ROUTES.HOME) if linkKey is 'notFound.goBackHome' else return () => Navigation.dismissModal()
onLinkPress={onLinkPress ?? linkKey === 'notFound.goBackHome' ? () => Navigation.goBack(ROUTES.HOME) : () => Navigation.dismissModal()}
```

Can also apply the above improvement at lower level in `BlockingView`.

### What alternative solutions did you explore? (Optional)

N/A

**Comment by situchan** [comment] 2024-01-15 03:52
what's the offending PR?

**Comment by bernhardoj** [comment] 2024-01-15 04:50
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
Pressing the go back to homepage in reimbursement account page not found view will reopen the bank account page.

### What is the root cause of that problem?
If we follow the navigation step from OP, we will get this navigation stack:
1. Open the bank account validation page. [RHP (validation step)]
2. Press Let's Chat which will open the concierge chat. [RHP (validation step), Concierge]
3. Press "here" which opens the not found bank account page. [RHP (validation step), Concierge, RHP (requestor, not found)]

When we press go back to the homepage or simply go back, the 2nd RHP will be unmounted and clear the bank account data.
https://github.com/Expensify/App/blob/a2864a077fd5d577021983ff77c658c9f2e43bab/src/pages/ReimbursementAccount/ReimbursementAccountPage.js#L278-L287

This triggers the `useEffect` for the first RHP that compares the step from params and the step from bank account data Onyx.
https://github.com/Expensify/App/blob/a2864a077fd5d577021983ff77c658c9f2e43bab/src/pages/ReimbursementAccount/ReimbursementAccountPage.js#L252
https://github.com/Expensify/App/blob/a2864a077fd5d577021983ff77c658c9f2e43bab/src/pages/ReimbursementAccount/ReimbursementAccountPage.js#L316-L335

And because the onyx data is cleared, the navigation logic above is triggered (BankAccountStep !== ValidationStep), making it impossible to leave the page.

This has the same root cause as https://github.com/Expensify/App/issues/21401 and also, we shouldn't clear the onyx data on unmount as it raises this [issue](https://github.com/Expensify/App/issues/31030) but was closed as not priority.

### What changes do you think we should make in order to solve the problem?

Dismiss the modal (RHP) before navigating to the concierge chat.

_I think we can have the same pattern as [navigateToAndOpenReport](https://github.com/Expensify/App/blob/a2864a077fd5d577021983ff77c658c9f2e43bab/src/libs/actions/Report.ts#L680-L682) by having a param `shouldDismissModal`_

**Comment by bernhardoj** [comment] 2024-01-15 04:51
I don't think it's a DB. I can reproduce this on prod too. I think the reason QA can't reproduce this on prod is, the link from concierge points to staging.
<img width="400" alt="image" src="https://github.com/Expensify/App/assets/50919443/1e9c072a-8c5e-485d-bd40-2cf7d06361d5">

**Comment by mountiny** [comment] 2024-01-15 10:37
No offending PR found so seems like repro in production. Not a blocker then, but we should fix this. @hoangzinh can you please triage the proposals? Thanks!

**Comment by abzokhattab** [comment] 2024-01-15 10:40
isnt this related to this issue? https://github.com/Expensify/App/issues/32856

**Comment by sonialiap** [comment] 2024-01-18 11:29
@hoangzinh how's the triage review going? Any looking promising for us to move forward with?

**Comment by sonialiap** [comment] 2024-01-22 15:06
@tienifr @eh2077 bumping hoangzinh's [question](https://github.com/Expensify/App/issues/34456#issuecomment-1898652305) above 😊

**Comment by bernhardoj** [comment] 2024-01-23 05:03
@hoangzinh any thoughts on my proposal?

**Comment by bernhardoj** [comment] 2024-01-24 03:25
Before:

https://github.com/Expensify/App/assets/50919443/a2f340e6-b4af-4b25-aa5a-03f91943f635

After:

https://github.com/Expensify/App/assets/50919443/5e44a20c-616a-415f-b15c-dc99206cbecc

**Comment by bernhardoj** [comment] 2024-01-24 07:08
The fallback routes to the workspace list
https://github.com/Expensify/App/blob/0efabc2b40fe845b13faa94ec508a6693167ede9/src/pages/ReimbursementAccount/ReimbursementAccountPage.js#L423-L425

I guess because we don't have the policy id on the params.

**Comment by bernhardoj** [comment] 2024-01-25 06:30
PR is ready

cc: @hoangzinh

**Comment by sonialiap** [comment] 2024-02-09 15:01
@hoangzinh reviewer - $500 paid ✔️  Please complete the [checklist](https://github.com/Expensify/App/issues/34456#issuecomment-1918255799)
@bernhardoj contributor - $500 paid ✔️

**Closed** 2024-02-14 16:42 UTC
Labels: External, Engineering, Daily, Overdue, Awaiting Payment, Bug
