### ISSUE TITLE
Workspace - Inconsistency with hovering styles

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#30952] opened 2023-11-07 03:02 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.3.96.0
**Reproducible in staging?:** y
**Reproducible in production?:** n
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** Applause - Internal team
**Slack conversation:**

## Action Performed:
Precondition: Have at least one workspace.

1. Navigate to staging.new.expensify.com.
2. Go to Settings.
3. Click on Workspaces.

## Expected Result:
There is no outline feedback around workspace avatars when clicking on Workspaces.

## Actual Result:
There is outline feedback around workspace avatars when clicking on Workspaces.

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [x] Android: mWeb Chrome
- [x] iOS: Native
- [x] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

https://github.com/Expensify/App/assets/93399543/4fa6469d-aed3-4c0b-ad2e-40f3ab7a9ee4

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by DylanDylann** [comment] 2023-11-07 03:30
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
Workspace - Outline feedback around workspace avatars when clicking on Workspaces 

### What is the root cause of that problem?
When displaying avatar we are using isHovered and pressed states of parent Component (Workspaces MenuItem) to get a style for it
### What changes do you think we should make in order to solve the problem?
We can wrap MultipleAvatars component by Hoverable and PressableWithSecondaryInteraction separately to get the correct state


### What alternative solutions did you explore? (Optional)
We can create new props called shouldApplyHoverAndPressStateToChildElement and we only pass isHovered and pressed states of parent Component to child element if shouldApplyHoverAndPressStateToChildElement is true

**Comment by situchan** [comment] 2023-11-07 07:03
@DylanDylann For deploy blockers, offending PR should be identified

**Comment by MonilBhavsar** [comment] 2023-11-07 11:24
Also hovering style on various workspace menu items is affected 


https://github.com/Expensify/App/assets/32012005/4536a69a-6a4d-408d-b1b6-470d5778e1b9


I'm leaning towards reverting that PR and coming up with new approach and testing plan

**Comment by MonilBhavsar** [comment] 2023-11-07 12:47
CP request here https://expensify.slack.com/archives/C07J32337/p1699361229767299

**Comment by mountiny** [comment] 2023-11-07 14:00
Fixed in staging, nobody needs to be paid, closing

**Closed by mountiny** 2023-11-07 14:00 UTC
Labels: Reviewing, Engineering, Weekly
