### ISSUE TITLE
[$500] Public Room - Anon User - Messages are not displayed real-time

### ISSUE THREAD

**Issue by isagoico** [Expensify/App#37211] opened 2024-02-26 16:05 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** v1.4.43-18

**Reproducible in staging?:** Yes 
**Reproducible in production?:** Yes

**Issue reported by:** Applause - Internal team

## Action Performed:

1. As a logged in user - Navigate to https://staging.new.expensify.com/r/5408450846930023
2. Open a incognito tab - Navigate to public room https://staging.new.expensify.com/r/5408450846930023 as Anon user
3. As the logged in user - Send some messages
4. View the chat as the incognito user

## Expected Result:
The messages should display real time for the anon user

## Actual Result:
The messages are not displayed real time. They appear only if the user does another action like navigating away from the conversation and back

## Workaround:
Navigating away or doing other actions will make the messages display.

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [x] Android: mWeb Chrome
- [x] iOS: Native
- [x] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

https://github.com/Expensify/App/assets/44479856/5370d870-7191-4fdd-a425-e9b287da2a6a

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01ebb6e68cf3e05187</li>
        <li>Upwork Job ID: 1763217314166697984</li>
        <li>Last Price Increase: 2024-08-02</li>
    </ul>
</details>

**Comment by isagoico** [comment] 2024-02-26 16:08
@zanyrenney I haven't added the External label yet. I'm almost sure this can be handled as 'External' but having confirmation first would be great.

**Comment by zanyrenney** [comment] 2024-02-29 14:58
yes, nice Isa @isagoico added!

**Comment by mananjadhav** [comment] 2024-03-04 18:02
Unable to reproduce this on Mac Chrome, and Safari. Same browsers, different browsers. I haven't checked other platforms. But do we have any specific preconditions @isagoico?

**Comment by zanyrenney** [comment] 2024-03-07 12:51
I also just did a round of testing and can't reproduce this. I'm going to close this out for now seeing as both of us can't reproduce, we can always reopen if we can see this is widely happening and reproducible!

**Comment by lanitochka17** [comment] 2024-07-19 15:08
Issue is still reproducible on the latest build 9.0.9-2
Edited message appears only after page refresh for public room anon user


https://github.com/user-attachments/assets/81de7dc3-446f-4813-bb7e-4b2a124814eb

**Comment by zanyrenney** [comment] 2024-07-22 14:44
Thanks @lanitochka17

**Comment by zanyrenney** [comment] 2024-07-22 14:44
@mananjadhav we're seeking proposals here.

**Comment by zanyrenney** [comment] 2024-07-24 20:26
Looking for proposals, bumped the thread in opensource.

**Comment by zanyrenney** [comment] 2024-08-01 10:16
Still no volunteers

**Comment by zanyrenney** [comment] 2024-08-01 10:21
dunno what is up with the channel i now can't see many comments at all -  https://expensify.slack.com/archives/C01GTK53T8Q/p1722507571743139

**Comment by mananjadhav** [comment] 2024-08-01 10:45
Can we rope in the expert agency to pick this up?

**Comment by zanyrenney** [comment] 2024-08-01 15:57
It's actually seems like a new dot quality issue as opposed to VIP VSB. I'm gonna post in that channel now.

**Comment by zanyrenney** [comment] 2024-08-01 16:02
Ah, looks like we have an autoassigner for this: **https://expensify.slack.com/archives/C05LX9D6E07/p1719337273306199?thread_ts=1718293036.755239&cid=C05LX9D6E07**

**Comment by arosiclair** [comment] 2024-08-02 19:37
Wow this issue has _all_ the labels

**Comment by arosiclair** [comment] 2024-08-02 19:57
@zanyrenney Just FYI - you should follow [this SO](https://stackoverflowteams.com/c/expensify/questions/19172) and run the issue by the curators in `#newdot-quality` before adding it to the project and using the auto assigner label. I think this probably wouldn't qualify since it's likely just coming from a temporary site outage.

**Comment by arosiclair** [comment] 2024-08-02 20:03
Realtime messages seem to be working on both staging and prod again so I'm just going to close this for now.

**Comment by IuliiaHerets** [comment] 2024-10-10 13:53
QA team can reproduce this issue in the latest build - v9.0.47-2 

https://github.com/user-attachments/assets/4debc133-c659-4d82-835c-db55e6b09f7d

**Comment by arosiclair** [comment] 2024-10-10 14:55
Realtime DMs are working in staging and production.

I am getting errors when trying to post messages to the [expensifail domain room](https://staging.new.expensify.com/r/75431276) ([logs](https://www.expensify.com/_devportal/tools/logSearch/#query=request_id:(%228d0762e0490a0c84-EWR%22)+AND+timestamp:[2024-10-10T13:44:05.152Z+TO+2024-10-10T15:44:05.152Z]&index=logs_expensify-030655)). The AddComment command throws an error but refreshing the page does show the message got posted:

```
Bedrock\Client - Starting a request ~~ command: 'GetRestrictedAuthToken' clusterName: 'auth' headers: '[email: 'bruceann.gomez@team.expensify.com' type: 'receiptUpload' validateCode: '<REDACTED>' partnerName: 'expensify.com' idempotent: '1' timeout: '' logParam: 'arosiclair@expensifail.com' urlToNewDot: 'https://staging.new.expensify.com/' shouldReadUsingThreads: '' shouldHandleOnyxUpdates: '1' isNewDotRequest: '1' clientUpdateID: '2343409203' maxNumberOfUpdates: '500' commitCount: '25162957782' requestID: '8d0762e0490a0c84-EWR' lastIP: '69.119.52.184' writeConsistency: 'ASYNC' priority: '500']'

bruceann.gomez@team.expensify.com request authtoken type = receiptUpload

Throwing exception with message: '404 Account not found' from auth/command/GetRestrictedAuthToken.cpp:136
```

Supportal tells me bruceann.gomez@team.expensify.com is indeed a closed account:
> Account with email bruceann.gomez@team.expensify.com and accountID 11283758 was closed on 2024-05-02.

I'm not sure why `AddComment` is resulting in a `GetRestrictedAuthToken` call for a different account (a closed one that fails). This might be the root of what QA is seeing.

**Comment by arosiclair** [comment] 2024-10-10 15:30
Okay here's the stack trace

```
Throw ExpException - 5a298b2fb32635da318ee93f6e1feeee ~~ message: '404 Account not found' exceptionMessage: 'Auth GetRestrictedAuthTokenByEmail returned an error' exceptionFile: '/git/releases/expensify.com/ffe4d3d/lib/Auth.php' exceptionLine: '132' exceptionCode: '404'
[trace] StackTrace start
[trace] 0/7. file '/git/releases/expensify.com/ffe4d3d/lib/Auth.php' function '_standardResponseHandler' line '2850'
[trace] 1/7. file '/git/releases/expensify.com/ffe4d3d/lib/AuthTokenManager.php' function 'getRestrictedAuthTokenByEmail' line '570'
[trace] 2/7. file '/git/releases/expensify.com/ffe4d3d/lib/AuthTokenManager.php' function 'getRestrictedAuthTokenByEmail' line '246'
[trace] 3/7. file '/git/releases/expensify.com/ffe4d3d/lib/ReportUtils.php' function 'getEmailToken' line '3760'
[trace] 4/7. file '/git/releases/expensify.com/ffe4d3d/lib/ReportUtils.php' function 'getAccountManagerInChat' line '466'
[trace] 5/7. file '/git/releases/expensify.com/ffe4d3d/lib/ReportAPI.php' function 'createChatbotInputIfNeeded' line '559'
[trace] 6/7. file '/git/releases/expensify.com/ffe4d3d/lib/ReportAPI.php' function 'addComment' line '407'
[trace] 7/7. file '/git/releases/expensify.com/ffe4d3d/api.php' function 'addCommentNewDot' line '779'
```

So we are attempting to escalate the chat to Concierge because there's a `team.expensify.com` user in it. I think that's normal for domain rooms, but this didn't work because the account manager closed their account. This is _not_ related to the issue QA reported since that was in a public room but I'll clean it up anyway.

**Comment by arosiclair** [comment] 2024-10-10 15:35
I was not able to reproduce in QA's public room: https://staging.new.expensify.com/r/2091104345528462. It can take several seconds to receive the message, but it is received eventually without a refresh.

https://github.com/user-attachments/assets/99f04bc2-58fc-4d33-8911-1101325646a1

Closing this out

**Closed by arosiclair** 2024-10-10 15:35 UTC
Labels: Daily, Internal, Bug, AutoAssignerNewDotQuality
