### ISSUE TITLE
[$500] IOU - IOU with hidden shows hmm not here &avatar beside IOU changes to green avatar

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#34839] opened 2024-01-19 21:18 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.28
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** Applause - Internal Team
**Slack conversation:**

## Action Performed:
1. Launch app
2. Tap fab --- Start chat
3. Enter +84387025654 and select the contact
4. Note conversation header changed as hidden
5. Tap plus icon near compose--- Request money--- manual
6. Enter an amount and tap next
7. Tap request
8. Note avatar displayed beside newly created IOU
9. Tap on newly created IOU to open IOU details page
10. Tap back button
11. Note in conversation page, beside IOU newly created, avatar changed to default green offline avatar
12. Tap on newly created IOU again to open IOU details page

## Expected Result:
Request money with specific "hidden" number user and opening IOU details page must not show "hmm not here" page and avatar beside newly created IOU must not change to green offline default avatar

## Actual Result:
Request money with specific "hidden" number user and opening IOU details page shows "hmm not here" page and avatar beside newly created IOU changes to green offline default avatar.

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [x] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details> 

https://github.com/Expensify/App/assets/78819774/d217d8f0-ad2d-4afe-ae2b-e3ed7e7eff24

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01a1cca1664f122e46</li>
        <li>Upwork Job ID: 1748454958646505472</li>
        <li>Last Price Increase: 2024-01-19</li>
    </ul>
</details>

**Comment by JeremyCroff** [comment] 2024-01-20 15:31
Clicking the IOU triggers a call for https://www.expensify.com/api?command=AuthenticatePusher.
This is returning a 404 for the hidden user.

Do you have steps to view the IOU succesfully on a hidden user? This will help determine if viewing IOUs for hidden users having problems is isolated to this user, or across the board.

It might be a service issue. The openReport call succesfully is able to retrieve the data for this user, so logic on back end should be compared.

**Comment by brunovjk** [comment] 2024-01-21 11:04
If I try variations like +8438702565**3** or +8438702565**5** I get the expected failure message: "The provided phone number does not match the country ...".
Why am I able to Start Chat with +84387025654 in the first place?

**Comment by bfitzexpensify** [comment] 2024-01-23 20:05
@situchan your thoughts on the comments above?

**Comment by bfitzexpensify** [comment] 2024-01-25 20:26
Bump on this one @situchan - thanks

**Comment by situchan** [comment] 2024-01-25 22:29
I agree it's backend issue.
It's mysterious that `+84387025653` and `+84387025654` behave differently from backend.
Getting engineer to take a look 🎀 👀 🎀

**Comment by bfitzexpensify** [comment] 2024-02-02 21:08
It sounds like things are behaving as expected for most numbers, but not OPs number.

@lanitochka17 have you been testing with +84387025654 for a while? I'm wondering if it's something specific to that number having been used in the past.

**Comment by bfitzexpensify** [comment] 2024-02-05 22:14
Bump on the question in https://github.com/Expensify/App/issues/34839#issuecomment-1924699042 @lanitochka17

**Comment by bfitzexpensify** [comment] 2024-02-07 03:05
Reviewing this again - given the problem is limited to a single phone number, and that phone number belongs to a tester and so wouldn't reflect typical usage, I think we can close this out.

**Closed by bfitzexpensify** 2024-02-07 03:05 UTC
Labels: External, Daily, Help Wanted, Bug
