### ISSUE TITLE
[$250] [CVP] Account is validated but still being asked to validate to add a VBBA

### ISSUE THREAD

**Issue by IuliiaHerets** [Expensify/App#49813] opened 2024-09-26 20:42 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 9.0.39-0
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**If this was caught during regression testing, add the test name, ID and link from TestRail:** https://expensify.testrail.io/index.php?/tests/view/4992364&group_by=cases:section_id&group_order=asc&group_id=283225
**Issue reported by:** Applause Internal Team

## Action Performed:
1. Open the app
2. Log in with a new Expensifail account
3. Create a workspace
4. Navigate to Workspace settings - More features
5. Enable "Workflows"
6. Navigate to Workflows - Connect bank account
7. Click on the note to open the process in a browser

## Expected Result:
The account is already validated so the message shouldn't appear.

## Actual Result:
Web page opened from the app asks to validate my expensifail account.
## Workaround:
Unknown

## Platforms:

- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [ ] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

https://github.com/user-attachments/assets/322db189-d400-4366-b830-a2d576647a7b

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~021841225609645325117</li>
        <li>Upwork Job ID: 1841225609645325117</li>
        <li>Last Price Increase: 2024-10-01</li>
<li>Automatic offers: </li>
<ul>
<li>suneox | Reviewer | 104246212</li>
</ul></li>
    </ul>
</details>

**Comment by IuliiaHerets** [comment] 2024-09-26 20:42
We think that this bug might be related to #wave-collect - Release 1

**Comment by IuliiaHerets** [comment] 2024-09-26 20:42
@muttmuure  FYI I haven't added the External label as I wasn't 100% sure about this issue. Please take a look and add the label if you agree it's a bug and can be handled by external contributors

**Comment by trjExpensify** [comment] 2024-10-01 21:15
I can repro this: 

<img width="1511" alt="image" src="https://github.com/user-attachments/assets/a9f4ee39-c457-4d02-af9b-e0f33f2e7ab6">


@deetergp & I are also running into it in this flow:

- Send an IOU to a user without an account
- Click the Pay button in the email 
- The user is signed in and the account is validated:

```
        },
        "domainControlled": false,
        "email": "<redacted>",
        "isApprovedAccountant": false,
        "isApprovedAccountantClient": false,
        "isUnapprovedAccountant": false,
        "personalPolicyID": "0BBDE5F6A57A234E",
        "samlRequired": false,
        "samlSupported": false,
        "subscribed": 1,
        "twoFactorAuthEnabled": false,
        "validated": true
```

but in onyx, `account.validated` is `false`

<img width="428" alt="image" src="https://github.com/user-attachments/assets/df9dae61-5072-4083-a04a-a9ca6a8e2039">

This is a critical viral flow, so we'd appreciate a quick turnaround on getting to the bottom of it! 

CC: @francoisl as I tagged you for eyes [here](https://expensify.slack.com/archives/C03TBKRSB/p1727816199146719?thread_ts=1726862231.127389&cid=C03TBKRSB).

**Comment by pasyukevich** [comment] 2024-10-02 09:19
Hi, I'm Eugene from Callstack - expert agency - and I would like to work on this issue.

**Comment by koko57** [comment] 2024-10-03 10:45
Hey! I'm Agata from Callstack and I would like to help with this issue 🙂

**Comment by trjExpensify** [comment] 2024-10-03 11:10
Wahoo, thanks!

**Comment by koko57** [comment] 2024-10-03 14:35
I've checked the reproduction steps and I could repro when I wasn't logged in the account - because we're not sending validated in the OpenApp response - shouldn't it be always true after the user logs in to their account with the magic code for the first time (or verify the account the other way)?
<img width="1497" alt="Screenshot 2024-10-03 at 21 25 07" src="https://github.com/user-attachments/assets/91e17af3-adb8-48ac-8338-85fb4da6d876">
<img width="1069" alt="Screenshot 2024-10-03 at 21 24 47" src="https://github.com/user-attachments/assets/5b04c3d4-4121-42a2-956e-ef935d20b542">
So if we're not getting validated - it's undefined and falsy - so we have the error displayed.

I couldn't reproduce the scenario that I was logged in and then validate turned to false, but I wasn't following the steps @trjExpensify mentioned, I will check it tomorrow.

**Comment by trjExpensify** [comment] 2024-10-03 15:33
>shouldn't it be always true after the user logs in to their account with the magic code for the first time (or verify the account the other way)?

Just so I'm clear, you're talking about this flow yeah? 

1. Sign up for a new account 
2. Get logged-in immediately, but unvalidated. 
3. Sign-out and back in to enter a magic code to validate the account (or otherwise validate the account with a magic code in some in product flow) 
4. Go to the workflows > connect bank account page 
5. Observe being prompted for validation still, when your account is validated at this point.

**Comment by koko57** [comment] 2024-10-04 09:17
@trjExpensify for the [flow](https://github.com/Expensify/App/issues/49813#issuecomment-2387090719) you were able to recreate this - I've just repro this and validated is false, because that's what we get from SigninUserWithLink. So if we want a new user to be validated when going from the link for the first time it also should be sent from the BE. 

<img width="642" alt="Screenshot 2024-10-04 at 16 01 01" src="https://github.com/user-attachments/assets/b13f5cf6-373b-41c7-a278-f22fa0f881ca">

But IMHO `validated: false` makes sense when entering the app from the link for the first time.

**Comment by koko57** [comment] 2024-10-04 09:29
for the case that is in the test steps - we don't send account with SinginWithShortLivedAuthToken or OpenApp, so as I've mentioned earlier we don't have the `validated` property sent with the `account` it's treated as falsy and the error is displayed.

As OpenApp call is always sent and we get the account with the response, I think the best option would be to send validated (either true or false) with this one.

**Comment by trjExpensify** [comment] 2024-10-04 19:37
>I've just repro this and validated is false, because that's what we get from SigninUserWithLink. So if we want a new user to be validated when going from the link for the first time it also should be sent from the BE.

@koko57 for that account in the screenshot have you since validated it or did you not touch it after going through this flow? Because when I look at that account, it's validated (as it should be) on the BE which lines up with the bug I'm seeing where onyx doesn't reflect that: 

```
        "domainControlled": false,
        "email": "agata.kosior+pay2@callstack.com",
        "isApprovedAccountant": false,
        "isApprovedAccountantClient": false,
        "isUnapprovedAccountant": false,
        "personalPolicyID": "7E43D6DD1B1B63EF",
        "samlRequired": false,
        "samlSupported": false,
        "subscribed": 1,
        "twoFactorAuthEnabled": false,
        "validated": true
```

**Comment by koko57** [comment] 2024-10-07 03:04
@trjExpensify yes, I validated it then

**Comment by trjExpensify** [comment] 2024-10-07 09:57
Cool, can you go through the flow again and don't validate, then send me the email address to check?

**Comment by koko57** [comment] 2024-10-07 11:10
@trjExpensify 
agata.kosior+testPay@callstack.com
<img width="1489" alt="Screenshot 2024-10-07 at 18 09 45" src="https://github.com/user-attachments/assets/cc7303c1-c340-458f-a7b8-9494fd9b1d1d">

**Comment by trjExpensify** [comment] 2024-10-07 11:38
Cool yeah, the account is validated on the backend: 

```
        },
        "canDowngrade": true,
        "closed": "",
        "created": "2024-10-07 11:08:43",
        "delegatedAccess": {
            "delegates": [],
            "delegators": []
        },
        "domainControlled": false,
        "email": "agata.kosior+testpay@callstack.com",
        "isApprovedAccountant": false,
        "isApprovedAccountantClient": false,
        "isUnapprovedAccountant": false,
        "personalPolicyID": "D2FCF31BDA823D00",
        "samlRequired": false,
        "samlSupported": false,
        "subscribed": 1,
        "twoFactorAuthEnabled": false,
        "validated": true
```

**Comment by trjExpensify** [comment] 2024-10-07 11:42
Looking at the code and tracing it back to inception ([internal convo ref](https://expensify.slack.com/archives/C03TBKRSB/p1727815913047459?thread_ts=1726862231.127389&cid=C03TBKRSB)), It's expected for the account to be validated if you're invited to Expensify and click one of the CTAs in the email.

**Comment by koko57** [comment] 2024-10-07 11:59
@trjExpensify So how it's possible that I have validated: false in Onyx (it was sent with SinginWithShortLivedAuthToken) - so so if the value changes after I get the response shouldn't we sent the new value with OpenApp?

**Comment by trjExpensify** [comment] 2024-10-07 20:11
@deetergp didn't you have a theory on that? 

>I bet we set validated: 1 in an onyx update in side of Account::reopen.

**Comment by trjExpensify** [comment] 2024-10-07 20:12
CC: @techievivek @NikkiWines for more eyes on this as it's a CVP issue and pretty urgent for us to resolve.

**Comment by NikkiWines** [comment] 2024-10-08 18:44
I don't have the bandwidth to handle this at the moment, but perhaps this is tied to [this discussion](https://expensify.slack.com/archives/C01GTK53T8Q/p1727977430648069?thread_ts=1727975887.413929&cid=C01GTK53T8Q) and the `validated` value for `User` vs `Account`

cc: @Beamanator

**Comment by deetergp** [comment] 2024-10-08 19:06
Ah, so I think I figured out out. We don't validate in `Account::reopen`, we do it in `SignInUnvalidatedUserForNewDotSession::process` but we never send onyx update when we change it. I think we just need to push an update to `account` key and then we'll have this resolved.

**Comment by trjExpensify** [comment] 2024-10-08 21:12
Niceee!

**Comment by deetergp** [comment] 2024-10-09 00:19
It turns out we can't send the onyx update from Auth because it's too early in the sign in process for the user to actually receive the update. The change has to be mad in Web, but was relatively easy.

**Comment by koko57** [comment] 2024-10-16 08:19
Is anything on the FE side needed to be done here? 🙂

**Comment by trjExpensify** [comment] 2024-10-16 14:24
Nope, I don't think so. Daniel re-tested it here: https://expensify.slack.com/archives/C07HPDRELLD/p1729031899739159?thread_ts=1729024865.063539&cid=C07HPDRELLD

We do have a somewhat related bug, but a proposal is in from Manan here: https://github.com/Expensify/App/issues/49576

**Comment by trjExpensify** [comment] 2024-10-22 09:18
Cool, closing!

**Comment by trjExpensify** [comment] 2024-11-01 11:27
Hm, interesting. @koko57 can you give it a re-test and confirm that?

**Comment by deetergp** [comment] 2024-11-06 18:18
Any word on the retest @koko57?

**Comment by koko57** [comment] 2024-11-07 01:07
@trjExpensify @deetergp Sorry I missed Tom's message as I was ooo that day. Will retest today

**Comment by koko57** [comment] 2024-11-07 03:05
The original problem is fixed, works ok:
https://github.com/user-attachments/assets/ece7e513-ab86-4c17-8ddc-fbf0d71b7068

But I've also checked if the validation error will be shown after creating a new account on the web (and not validating it) and the message is not shown:

<img width="1509" alt="Screenshot 2024-11-07 at 09 52 02" src="https://github.com/user-attachments/assets/2a2ed558-8448-4781-94a6-5bd375832f65">

I think in this case we want it shown, don't we?

I see that some changes were introduced by this PR https://github.com/Expensify/App/pull/51718. The message should be shown because there is a check for account.validated, but for some reason it doesn't.

I'll be working on refactoring the first step of enabling bank account https://github.com/Expensify/App/issues/50422 https://github.com/Expensify/App/issues/51799 - because there are many issues with this step, so I also can fix it there.

**Comment by koko57** [comment] 2024-11-07 03:10
And I've noticed that we have 2 ways of informing that the workspace currency is not set to USD

for the Expensify Card it looks like this:
<img width="1201" alt="Screenshot 2024-11-07 at 09 41 07" src="https://github.com/user-attachments/assets/272af320-56b3-400c-a00c-6f5ee68900d5">

and for the workflows:
<img width="1195" alt="Screenshot 2024-11-07 at 09 40 45" src="https://github.com/user-attachments/assets/89c7ec60-bb34-4f47-b466-054a4b91d640">

Is there any reason that for the workflows we have only this info in the RHP and we cannot do this in the modal like for ECard? Or should we make it consistent?

cc @shawnborton

**Comment by shawnborton** [comment] 2024-11-07 07:45
I don't think I have strong feelings here, but I always love airing on the side of consistency. cc @Expensify/design @trjExpensify for the quick check here as well.

For the connect bank flow, I assume what's happening is that you click on the connect bank account row and you immediately see the RHP with the message about currency? If it's really the first step in the flow like that, I don't see why it couldn't be a modal either to match the Expensify Card page.

**Comment by trjExpensify** [comment] 2024-11-07 13:25
Interestingly, in [the global reimbursement doc](https://docs.google.com/document/d/1Y4P7G9h0Easjcea7wyk52gKrNB9o1yTjpmJFYkrHDW4/edit?tab=t.0#bookmark=id.z3akz1kd2a7i), we decided not to show the "Connect bank account" row if the workspace currency isn't USD, GBP, EUR, AUD or CAD (supported currencies for global reimbursement): 

<img width="800" alt="image" src="https://github.com/user-attachments/assets/d87eb40e-3596-4c48-88bf-2d814175d12d">

We could pull that out to move forward with it for non-USD for now, and extend it to the other currencies when global reimbursement is implemented? CC: @madmax330 for vis.

**Comment by trjExpensify** [comment] 2024-11-07 13:29
>But I've also checked if the validation error will be shown after creating a new account on the web (and not validating it) and the message is not shown:

I'm not quite following this. Here's a test on staging web, am I missing something? 

https://github.com/user-attachments/assets/d9e1f425-9648-490c-ae18-7783cd50505b

**Comment by koko57** [comment] 2024-11-08 03:32
@trjExpensify aaah ok, because of this new feature we no longer have to display this message:
<img width="293" alt="Screenshot 2024-11-08 at 10 31 21" src="https://github.com/user-attachments/assets/114d6272-6ef8-47b9-a4b8-80706f6e83d3">
(I meant that this message is not displayed for the accounts that have not been validated)

**Comment by trjExpensify** [comment] 2024-11-08 09:25
Yep, exactly!

**Comment by trjExpensify** [comment] 2024-11-08 12:39
Great stuff! 

>We could pull that out to move forward with it for non-USD for now, and extend it to the other currencies when global reimbursement is implemented? CC: @madmax330 for vis.

@madmax330 let us know about the status of this one, and potentially expediting it for non-USD.

**Closed by trjExpensify** 2024-11-08 12:39 UTC
Labels: Reviewing, Daily, Internal, Bug
