### ISSUE TITLE
cardPagecardFetailsLoadingFailure error code for incorrect magic code on Card Reveal Details

### ISSUE THREAD

**Issue by IuliiaHerets** [Expensify/App#48997] opened 2024-09-11 16:18 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** v9.0.32-0
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**Email or phone of affected tester (no customers):** applausetester+en@applause.expensifail.com
**Issue reported by:** Applause Internal Team

## Action Performed:
1. Open the New Expensify app
2. Sign into a valid account
3. Go to Profile > Wallet > Expensify Card > Reveal Details
4. Input incorrect magic code

## Expected Result:
User expects to see "incorrect Magic code" message and the popup to stay open

## Actual Result:
User receives a "failure"(Seems like code) error message and the popup instantly closes

## Workaround:
Unknown

## Platforms:

- [x] Android: Native
- [x] Android: mWeb Chrome
- [x] iOS: Native
- [x] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

https://github.com/user-attachments/assets/e496aac4-cd74-488b-90d9-c48046844546

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by IuliiaHerets** [comment] 2024-09-11 16:18
@JmillsExpensify  FYI I haven't added the External label as I wasn't 100% sure about this issue. Please take a look and add the label if you agree it's a bug and can be handled by external contributors

**Comment by etCoderDysto** [comment] 2024-09-11 16:23
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
cardPagecardFetailsLoadingFailure error code for incorrect magic code on Card Reveal Details
### What is the root cause of that problem?
When the request fails, the API request is rejected with `cardPage.cardDetailsLoadingFailure`
https://github.com/Expensify/App/blob/762bffcfad4ca7c4553eabedde5a2ba47871bdb5/src/libs/actions/Card.ts#L210-L212
But we didn't fetch the translation content of the message here
https://github.com/Expensify/App/blob/762bffcfad4ca7c4553eabedde5a2ba47871bdb5/src/pages/settings/Wallet/ExpensifyCardPage.tsx#L134-L137
### What changes do you think we should make in order to solve the problem?
We should call translate method on the error message 
```
setCardsDetailsErrors((prevState) => ({
           ...prevState,
           [currentCardID]: translate(error),
```

### What alternative solutions did you explore? (Optional)

**Comment by etCoderDysto** [comment] 2024-09-11 16:27
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
cardPagecardFetailsLoadingFailure error code for incorrect magic code on Card Reveal Details
### What is the root cause of that problem?
When the request fails, the API request is rejected with `cardPage.cardDetailsLoadingFailure`
https://github.com/Expensify/App/blob/762bffcfad4ca7c4553eabedde5a2ba47871bdb5/src/libs/actions/Card.ts#L210-L212
But we didn't fetch the translation content of the message here
https://github.com/Expensify/App/blob/762bffcfad4ca7c4553eabedde5a2ba47871bdb5/src/pages/settings/Wallet/ExpensifyCardPage.tsx#L134-L137
### What changes do you think we should make in order to solve the problem?
We should call translate method on the error message 
```javascript
setCardsDetailsErrors((prevState) => ({
           ...prevState,
           [currentCardID]: translate(error),
```

### What alternative solutions did you explore? (Optional)

**Comment by etCoderDysto** [comment] 2024-09-16 18:32
I don't think this issue is no longer reproducible

**Comment by JmillsExpensify** [comment] 2024-09-18 15:14
Closing as a result.

**Closed by JmillsExpensify** 2024-09-18 15:14 UTC
Labels: Daily, Overdue, Bug
