### ISSUE TITLE
Request Money-  "Hmm not here" page displayed when opened IOU preview page

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#26170] opened 2023-08-29 10:55 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. open a any chat
2. click on "+" button
3. click on request money and select manual
4. enter an amount
5. click next > request
6. a money request message is sent
7. click on the sent message

## Expected Result:
There should be details page of request money.

## Actual Result:
"Hmm not here" page displayed when opened IOU preview page

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [x] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 1.3.58.0
**Reproducible in staging?:** n/a
**Reproducible in production?:** n/a
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/93399543/4dc83b1a-221b-42b2-a672-b290802d3ad2

**Expensify/Expensify Issue URL:**
**Issue reported by:** @niravkakadiya25
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1691659791942689

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by PrgrmrHarshShukla** [comment] 2023-08-29 11:11
Hey @kbecciv ,
In my opinion, one possibility can be that,
may be the request limit was crossed because of a lot of request in a short time.

What do you think about this?

**Comment by kbecciv** [comment] 2023-09-01 11:15
Hi @PrgrmrHarshShukla! It happens with non-existing user Only, IOU opens as expected for existing user. Please attach the video

https://github.com/Expensify/App/assets/93399543/338ef7a7-7bb4-4ac0-9c81-288d07f2204a

**Comment by michaelhaxhiu** [comment] 2023-09-07 19:37
I cant reproduce this on Chrome http://g.recordit.co/86kgmh0AhP.gif

should that be an affected platform?

<img width="548" alt="image" src="https://github.com/Expensify/App/assets/13206896/c8ba91cf-ed05-4720-976a-2426bc9976a2">


I'll try on mobile now

**Comment by michaelhaxhiu** [comment] 2023-09-07 20:03
Wow this whole flow is brely even doable on my android pixel. Like it's lagging at nearly every step. Feels like the performance is really bad 😱

**Comment by michaelhaxhiu** [comment] 2023-09-07 20:20
Also I can't reproduce on chrome newdot as mentioned above, so I'm going to close this.

**Closed by michaelhaxhiu** 2023-09-07 20:20 UTC
Labels: Daily, Needs Reproduction, Bug
