### ISSUE TITLE
[$250] [Search v2.3] Popup colors are incorrect

### ISSUE THREAD

**Issue by lakchote** [Expensify/App#49440] opened 2024-09-19 06:44 UTC
See https://github.com/Expensify/App/pull/48566#issuecomment-2350099164
<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~021836682888839715103</li>
        <li>Upwork Job ID: 1836682888839715103</li>
        <li>Last Price Increase: 2024-09-19</li>
<li>Automatic offers: </li>
<ul>
<li>ishpaul777 | Contributor | 104052106</li>
<li>jaydamani | Contributor | 104052748</li>
</ul></li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @mollfpr</details>

**Comment by jaydamani** [comment] 2024-09-19 13:23
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
Incorrect color in three dot menu

### What is the root cause of that problem?

Colors for three dot menu are incorrect

https://github.com/Expensify/App/blob/37bf6b2fef128786dfcd83257a56f56c0cd1eb3d/src/components/ThreeDotsMenu/index.tsx#L94

### What changes do you think we should make in order to solve the problem?


Use `theme.icon` as default and `theme.iconHovered` when icon is hovered instead.

**Comment by jaydamani** [comment] 2024-09-19 18:24
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
Incorrect color in three dot menu

### What is the root cause of that problem?

The popup comes from [ThreeDotMenu](https://github.com/Expensify/App/blob/49d1b0d85c53c51ff97875fe722f27575928d5c0/src/pages/Search/SavedSearchItemThreeDotMenu.tsx#L17) which renders [popOverMenu](https://github.com/Expensify/App/blob/49d1b0d85c53c51ff97875fe722f27575928d5c0/src/components/ThreeDotsMenu/index.tsx#L99). PopOverMenu does not pass [isPaneMenu](https://github.com/Expensify/App/blob/49d1b0d85c53c51ff97875fe722f27575928d5c0/src/components/PopoverMenu.tsx#L183) prop for MenuItem so the default icon color is `theme.icon` (green) and color on focus is `theme.iconMenu` (black). The colors are decided based on below logic (active means hovered).

https://github.com/Expensify/App/blob/main/src/styles/utils/index.ts#L1442-L1460

### What changes do you think we should make in order to solve the problem?

The colors come from common components so we can do one of the following:

#### Option 1
Only update the menu for saved search.

To do this, add isPaneMenu as prop to [ThreeDotMenu](https://github.com/Expensify/App/blob/49d1b0d85c53c51ff97875fe722f27575928d5c0/src/pages/Search/SavedSearchItemThreeDotMenu.tsx#L17) and [popOverMenu](https://github.com/Expensify/App/blob/49d1b0d85c53c51ff97875fe722f27575928d5c0/src/components/ThreeDotsMenu/index.tsx#L99) to pass it down to [MenuItem](https://github.com/Expensify/App/blob/49d1b0d85c53c51ff97875fe722f27575928d5c0/src/components/PopoverMenu.tsx#L183)

### Option 2
Update all pop-up menus in the app to be consitent.

Add isPaneMenu prop [here](https://github.com/Expensify/App/blob/49d1b0d85c53c51ff97875fe722f27575928d5c0/src/components/PopoverMenu.tsx#L183) or remove the logic from [here](https://github.com/Expensify/App/blob/main/src/styles/utils/index.ts#L1442-L1460) by updating to below. We can also remove isPaneMenu prop after this.

```js
    switch (buttonState) {
        case CONST.BUTTON_STATES.ACTIVE:
        case CONST.BUTTON_STATES.PRESSED:
            return theme.iconHovered;
        case CONST.BUTTON_STATES.COMPLETE:
            return theme.iconSuccessFill;
        case CONST.BUTTON_STATES.DEFAULT:
        case CONST.BUTTON_STATES.DISABLED:
        default:
            if (isMenuIcon) {
                return theme.iconMenu;
            }
            return theme.icon;
    }
```

**Comment by NaveedShaikh78** [comment] 2024-09-19 19:43
## Proposal

### Please re-state the problem that we are trying to solve in this issue

Popup colors are incorrect

### What is the root cause of that problem?

The deault value for menu item is wrong and but if we change the value it is not reflecting due to the changes
done #33280.
![issue1](https://github.com/user-attachments/assets/fedc59cb-9b51-46a4-9e99-4f4f15d3d2a0)
![issue2](https://github.com/user-attachments/assets/0062c0eb-1849-4d36-9558-cd169cbec28c)

### What changes do you think we should make in order to solve the problem?
[MenuItem.tsx](https://github.com/Expensify/App/blob/main/src/components/MenuItem.tsx) mak isPaneMenu flag to true

### What alternative solutions did you explore? (Optional)
Reverting the changes #33280. can fix the problem

**Comment by lakchote** [comment] 2024-09-20 08:54
Assigning @ishpaul777 since he's available to review now.

**Comment by lakchote** [comment] 2024-09-20 09:40
Let's go with option 1 @jaydamani as we don't want to introduce unwanted side effects in the app, as `isPaneMenu` must have been there for a reason.

**Comment by jaydamani** [comment] 2024-09-20 09:52
I will work on this over the weekend and raise PR by monday. Let me know if this needs to be done today.

**Comment by lakchote** [comment] 2024-09-20 12:12
> I received the offer. I will work on this over the weekend and raise PR by monday. Let me know if this needs to be done today.

@jaydamani if you could work on this today and raise a PR, that'd be _great_!

**Comment by jaydamani** [comment] 2024-09-21 15:56
Created PR [here](https://github.com/Expensify/App/pull/49569)

**Comment by jaydamani** [comment] 2024-10-10 13:39
@ishpaul777 @lakchote Payment is due here but this is not assigned to BZ team so, can you please help out here as I am not sure who to ping. Thanks for the help.

**Comment by lakchote** [comment] 2024-10-10 13:42
> @ishpaul777 @lakchote Payment is due here but this is not assigned to BZ team so, can you please help out here as I am not sure who to ping. Thanks for the help.

Done!

**Comment by joekaufmanexpensify** [comment] 2024-10-10 14:10
Happy to help with payment here! I see on the PR there was a regression, so will factor that into payment. We need to pay: 

- @jaydamani - $125 for PR via Upwork. 
- @ishpaul777 - $125 for C+ via Upwork.

**Comment by joekaufmanexpensify** [comment] 2024-10-10 14:12
@jaydamani $125 sent and contract ended!

**Comment by joekaufmanexpensify** [comment] 2024-10-10 14:12
@ishpaul777 $125 sent and contract ended!

**Comment by joekaufmanexpensify** [comment] 2024-10-10 14:13
Upwork job closed

**Comment by joekaufmanexpensify** [comment] 2024-10-10 14:13
All set, thanks everyone!

**Closed by joekaufmanexpensify** 2024-10-10 14:13 UTC
Labels: Reviewing, External, Engineering, Daily, Bug

**Comment by joekaufmanexpensify** [comment] 2024-10-10 18:37
Yeah, that second one is the one I was referring to, as it was called out as [a regression on the PR ](https://github.com/Expensify/App/pull/49569#issuecomment-2381043031), and then immediately fixed. Typically, any regression does trigger the penalty, but I am coming into this one late, so happy to defer to @lakchote or @luacmartins if they feel differently.

**Comment by luacmartins** [comment] 2024-10-10 23:49
I understand the situation, but I think we should stick to the rule on this one.
