### ISSUE TITLE
HOLD for #21977 [$1000] When an anonymous user copies a message, the app says "Copied", but it DOES NOT actually copy the message

### ISSUE THREAD

**Issue by kavimuru** [Expensify/App#22307] opened 2023-07-05 20:30 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Logout current user or open web app in private mode
2. Open any room as an anonymous user. SNH room for example: https://staging.new.expensify.com/r/5303403427249671
3. HOVER on any message and select “Copy to clipboard” option. Observer that:
- The app shows “Copied” - but it DOES NOT actually copy the message
- User is re-directed to login page
## Expected Result: 
The message should be actually copied (not just shown “Copied” label)
## Actual Result: 
The app says "Copied", but it DOES NOT actually copy the message and then redirects the user to the login page.

## Workaround:
Can the user still use Expensify without this being fixed? Have you informed them of the workaround?

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [x] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 1.3.7-2
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/43996225/1050adcd-aa0f-43dc-b288-292e049bc82c

**Expensify/Expensify Issue URL:**
**Issue reported by:** @tranvantoan-qn
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1688384968610059

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~011eb534d2568f9e9b</li>
        <li>Upwork Job ID: 1676700818736766976</li>
        <li>Last Price Increase: 2023-08-02</li>
    </ul>
</details>

**Comment by AdekolaThanni** [comment] 2023-07-05 21:51
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
The copy to clipboard does not copy text for anonymous user although it sends a copied signal before logging client out.

### What is the root cause of that problem?
The onPressAction triggers the interceptAnonymousUser which blocks the anonymous user from copying text to clipboard and then leading to a sign out.

https://github.com/Expensify/App/blob/cb7988c50ad048a40a62d7139b0ea44e186d6695/src/pages/home/report/ContextMenu/BaseReportActionContextMenu.js#L121


### What changes do you think we should make in order to solve the problem?
The change we can make in order to allow a user to copy text to the clipboard directly since we have no aim of signing them out if they are an anonymous user is to remove the actionless code of passing interceptAnonymousUser to the onPress function, instead, we pass the callback directly. Such as this

`onPress={() =>  contextAction.onPress(closePopup, payload)}`

### What alternative solutions did you explore? (Optional)
None

**Comment by yh-0218** [comment] 2023-07-06 20:30
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
The app says "Copied", but it DOES NOT actually copy the message and then redirects the user to the login page.
### What is the root cause of that problem?
We need to allow only "Copy" for AnonymousUser. not allow others like "Reply" and "Reaction"
The root cause of this problem is that "AnonymousUser" is redirected to "Signin Page" when click copy.

### What changes do you think we should make in order to solve the problem?
We need to add a flag to  "Copy" of `ContextMenuActions` to allow for "AnonymousUser" to copy text.
So we can make if user allow "copy" without "signin" and not allow "reply" without "signin".

https://github.com/Expensify/App/assets/65789015/7013cb7c-cab7-487b-bb45-51d08a888e62


### What alternative solutions did you explore? (Optional)

**Comment by Santhosh-Sellavel** [comment] 2023-07-06 20:33
@adelekennedy Please add a HOLD label here to the issue, we are working on fixing this holistically on #21977.

**Comment by adelekennedy** [comment] 2023-07-17 20:56
still holding on this

**Comment by adelekennedy** [comment] 2023-07-26 23:05
hold

**Comment by PauloGasparSv** [comment] 2023-08-01 21:51
Hey @adelekennedy @Santhosh-Sellavel sorry for the delay, I was OOO and got back this week : )

The fix from https://github.com/Expensify/App/issues/21977 worked and now the copy button is working fine for anonymous users! 

https://github.com/Expensify/App/assets/6564265/76b0c161-3d92-4201-b64d-01b0f956b0e2

I'm not sure if we need to compensate who reported this first but please feel free to close this!

**Comment by adelekennedy** [comment] 2023-08-01 22:18
Thank you! 

Payment Summary

**@tranvantoan-qn** - $250 for reporting bonus (paid via Upwork)

In this case I think only the reporting bonus is due because we put this on hold so quickly.

**Comment by adelekennedy** [comment] 2023-08-02 16:02
reporting paid out. closing this!

**Closed by adelekennedy** 2023-08-02 16:02 UTC
Labels: External, Weekly, Help Wanted, Bug
