### ISSUE TITLE
[$500] Workspace-In invite members page, selected option not remains ticked while revisiting page

### ISSUE THREAD

**Issue by izarutskaya** [Expensify/App#31358] opened 2023-11-15 12:02 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.3.99-0
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** Applause-Internal Team
**Slack conversation:** @

## Action Performed:
1. Launch app
2. Tap profile
3. Tap Workspaces---Workspace
4. Tap members
5. Select first member
6. Tap invite
7. Tap app's back button
8. Note selected option remains ticked on revisiting the page
9. Tap invite
10. Select any user
11. Tap back button
12. Tap invite

## Expected Result:
In find a member page, selected option remains ticked on revisiting. Similarly, in invite members page, the selected option must remain ticked while revisiting the page.

## Actual Result:
In find a member page, selected option remains ticked on revisiting but in invite members page, the selected option not remains ticked while revisiting the page.

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [x] Android: mWeb Chrome
- [x] iOS: Native
- [x] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

https://github.com/Expensify/App/assets/115492554/d4a2bde2-7f27-4b75-a62d-ea2e389fefa0

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01ca0a769bd69faeb3</li>
        <li>Upwork Job ID: 1724759796943212544</li>
        <li>Last Price Increase: 2023-11-15</li>
    </ul>
</details>

**Comment by esh-g** [comment] 2023-11-15 12:07
I think this is intentional as the the screen for invite is popped off the stack when it closes and the members screen never pops off

**Comment by s-alves10** [comment] 2023-11-15 12:19
I'm not sure if this is really a bug
Back to members page is a pop action and going to invite page is a push action.

**Comment by s-alves10** [comment] 2023-11-15 13:52
## Proposal

### Please re-state the problem that we are trying to solve in this issue.

Previously selected members doesn't remain when revisiting the workspace invite page

### What is the root cause of that problem?

Navigating back to the members page is a pop action of stack router. But revisiting the invite page is a push action and the `WorkspaceInvitePage` is remounted.

This is the root cause

### What changes do you think we should make in order to solve the problem?

The main idea is to store the temporary data to the onyx store. We have already `WORKSPACE_INVITE_MEMBERS_DRAFT` key for this

1. Add the below code to [Policy.js](https://github.com/Expensify/App/blob/8872311253a7b188e7a9c64b9482371432748de5/src/libs/actions/Policy.js#L55)
```
let allWorkspaceInviteMembersDraft;
Onyx.connect({
    key: ONYXKEYS.COLLECTION.WORKSPACE_INVITE_MEMBERS_DRAFT,
    waitForCollectionCallback: true,
    callback: (val) => (allWorkspaceInviteMembersDraft = val),
});

function getWorkspaceInviteMembersDraft(policyID) {
    return lodashGet(allWorkspaceInviteMembersDraft, `${ONYXKEYS.COLLECTION.WORKSPACE_INVITE_MEMBERS_DRAFT}${policyID}`, {});
}
```
2. Store members draft in [toggleOption](https://github.com/Expensify/App/blob/8872311253a7b188e7a9c64b9482371432748de5/src/pages/workspace/WorkspaceInvitePage.js#L169).
To do this
- Add the following utility function to the [WorkspaceInvitePage](https://github.com/Expensify/App/blob/main/src/pages/workspace/WorkspaceInvitePage.js)
```
    const saveWorkspaceInviteMembersDraft = (membersDraft) => {
        const invitedEmailsToAccountIDs = {};
        _.each(membersDraft, (option) => {
            const login = option.login || '';
            const accountID = lodashGet(option, 'accountID', '');
            if (!login.toLowerCase().trim() || !accountID) {
                return;
            }
            invitedEmailsToAccountIDs[login] = Number(accountID);
        });
        Policy.setWorkspaceInviteMembersDraft(props.route.params.policyID, invitedEmailsToAccountIDs);
    }
```

- Add the below code in [toggleOption](https://github.com/Expensify/App/blob/8872311253a7b188e7a9c64b9482371432748de5/src/pages/workspace/WorkspaceInvitePage.js#L180)
```
    saveWorkspaceInviteMembersDraft(newSelectedOptions);
```

- Add the following code [here](https://github.com/Expensify/App/blob/8872311253a7b188e7a9c64b9482371432748de5/src/pages/workspace/WorkspaceInvitePage.js#L102) to load the stored invite members draft
to
```
        const inviteMembersDraft = Policy.getWorkspaceInviteMembersDraft(props.route.params.policyID);
        _.each(inviteMembersDraft, (accountID, login) => {
            if (_.some(selectedOptions, (option) => option.login === login) || !_.has(detailsMap, login)) {
                return;
            }
            newSelectedOptions.push({...detailsMap[login], isSelected: true});
        });
```

This works as expected

<details>
    <summary>Result</summary>



</details>

### What alternative solutions did you explore? (Optional)
Instead of writing `getWorkspaceInviteMembersDraft` function, we can use withOnyx in `WorkspaceInvitePage` component as below
```
        invitedEmailsToAccountIDsDraft: {
            key: ({route}) => `${ONYXKEYS.COLLECTION.WORKSPACE_INVITE_MEMBERS_DRAFT}${route.params.policyID.toString()}`,
        },
```

**Comment by DylanDylann** [comment] 2023-11-15 18:01
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
- Feature request: Workspace-In invite members page, selected option not remains ticked while revisiting page
### What is the root cause of that problem?
- From "Find a member page" go to "Invite member page", the "Find a member page" is not unmounted and then go back to "Find a member page", the "Invite members page" is unmounted, that leads to the current behaviour
- I think it is a feature request rather than a bug. Before, we also had a plan that syncs the search input in "Find a member page" and "Invite member page".
### What changes do you think we should make in order to solve the problem?
- The flow "Find a member" >  "Invite a member" appears many times in our app, for example: workspace and room, and maybe in the future. So the behaviour should be consistent entire the app. We can do it by these below steps:
1. First, create a global object called ```memberActionManager``` to store the shared data. Its structure is like the below:
```
{
    workspace: {
        searchText: '',
        membersToInvite: []
    },
    room: {
        searchText: '',
        memberToInvite: []
    }
}
```
2. In [WorkspaceInvitePage](https://github.com/Expensify/App/blob/main/src/pages/workspace/WorkspaceInvitePage.js), adding the logic to update the initial value for the member to invite:
```
  useEffect(() => {
        if (!memberActionManager.workspace.membersToInvite) {
            return;
        }
        setSelectedOptions(memberActionManager.workspace.membersToInvite)
    }, []);
```
3. Then add the below logic to [toggleOption]:
(https://github.com/Expensify/App/blob/dd7a19bb4cb49c839e5131f6ca719c5122cdc8cc/src/pages/workspace/WorkspaceInvitePage.js#L169)
````diff
    const toggleOption = (option) => {
          setSelectedOptions(newSelectedOptions);
+        memberActionManager.workspace.membersToInvite = newSelectedOptions;

    };
````
4. Do the same with the room member flow.
### What alternative solutions did you explore? (Optional)
- NA

**Comment by bfitzexpensify** [comment] 2023-11-15 21:42
I agree that these are different actions, but consistency is something we should aim for, so I think we should address this. 

Couple of proposals ready for review @ntdiary

**Comment by bfitzexpensify** [comment] 2023-11-21 21:38
Thanks for that detailed explanation @ntdiary - I agree that by following your steps (which are most reasonable to assess consistency), then we can see that the behaviour is the same. I don't think we need to add draft states for either page. Given that, I'm going to close this as not a bug or something we need to address.

**Closed by bfitzexpensify** 2023-11-21 21:38 UTC
Labels: External, Daily, Help Wanted, Overdue, Bug
