### ISSUE TITLE
[HOLD for payment 2024-10-24] [$250] mWeb/Safari - Chat - Keyboard does not close when action menu opens

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#44042] opened 2024-06-19 20:31 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.85-6
**Reproducible in staging?:** Y
**Reproducible in production?:** Y 
**If this was caught during regression testing, add the test name, ID and link from TestRail:** N/A
**Email or phone of affected tester (no customers):** gibethlehem+3gmail.com
**Issue reported by:** Applause - Internal Team

## Action Performed:
1. Go to any chat
2. Click on the composer to bring the keyboard (if its not already open)
3. While the keyboard is open long press on a message to bring the action menu

## Expected Result:
The keyboard closes when the action menu is opened

## Actual Result:
The keyboard stays open when the action menu is opened

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [x] iOS: mWeb Safari
- [ ] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details> 

https://github.com/Expensify/App/assets/78819774/2497443c-14a8-4c30-86c0-f96de3c46c55

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~0174c82b024da104ac</li>
        <li>Upwork Job ID: 1805674432646033914</li>
        <li>Last Price Increase: 2024-08-13</li>
<li>Automatic offers: </li>
<ul>
<li>rojiphil | Reviewer | 103557667</li>
<li>dominictb | Contributor | 103557669</li>
</ul></li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @CortneyOfstad</details>

**Comment by lanitochka17** [comment] 2024-06-19 20:32
@CortneyOfstad  FYI I haven't added the External label as I wasn't 100% sure about this issue. Please take a look and add the label if you agree it's a bug and can be handled by external contributors

**Comment by lanitochka17** [comment] 2024-06-19 20:32
We think that this bug might be related to #vip-vsp

**Comment by CortneyOfstad** [comment] 2024-06-25 18:48
Sorry, was OoO!

Was able to recreate, so going to get eyes on this!

![IMG_1119](https://github.com/Expensify/App/assets/10926327/b352c046-960d-4388-a92b-e24959740405)

**Comment by muttmuure** [comment] 2024-06-27 10:06
This is not a #newdot-quality bug - the feature is not unreliable, slow or performing redundant or unexpected API calls, it just doesn't work as designed

**Comment by CortneyOfstad** [comment] 2024-07-01 18:25
Thanks for the clarification @muttmuure!

**Comment by CortneyOfstad** [comment] 2024-07-01 18:26
@rojiphil there is a proposal [here](https://github.com/Expensify/App/issues/44042#issuecomment-2191415145)!

**Comment by CortneyOfstad** [comment] 2024-07-03 16:58
@rojiphil any updates on the reviews? Please have these completed by EOD.

**Comment by rojiphil** [comment] 2024-07-03 18:11
@dominictb Thanks for the proposal. 

> getActiveInput is implemented for both native and web platform, but it's not the same as [this comment](https://github.com/Expensify/App/blob/0c20881a308244867119efa6196481b65bb81274/src/libs/ComposerFocusManager.ts#L35) so we can separate this function in 2 file index.ts and index.native.ts

I am not sure if I understand why we need to separate `getActiveInput` into two files. Especially since the keyboard gets closed on launching emoji picker as shown below even without this change. Can you please share more details on this?


https://github.com/Expensify/App/assets/3004659/58095810-5c07-4749-88fd-72399ee8524b

**Comment by rojiphil** [comment] 2024-07-09 16:32
> Can you review my proposal above ^? Thanks

@dominictb Sorry for the delay here. I will review your comments and provide an update sometime tomorrow my day.

**Comment by rojiphil** [comment] 2024-07-11 09:50
Regarding separating getActiveInput into two files, I may be missing something here. 
If you notice in the video below for iOS mWeb, the issue does not occur with eMoji picker but issue occurs for action menu. Why this difference?

https://github.com/Expensify/App/assets/3004659/93837ab3-6ede-4876-9b84-fbe6f93a58f3

**Comment by rojiphil** [comment] 2024-07-11 09:52
Also, why does the keyboard hide on Android mWeb whereas keyboard does not hide on iOS mWeb?

https://github.com/Expensify/App/assets/3004659/d0b9817d-e34c-48d5-94fb-dac31d0c10da

**Comment by CortneyOfstad** [comment] 2024-07-18 14:13
@rojiphil any additional feedback on the comment [here](https://github.com/Expensify/App/issues/44042#issuecomment-2227936339)?

**Comment by rojiphil** [comment] 2024-07-18 18:50
> I think it's the platform problem. On iOS, I can long press at any unresponsive place and the keyboard is not hidden. But on android it's hidden.

Hmm… Ok. Looks like an android specific issue and may be unrelated to this issue. Let us revisit this a little later.

**Comment by rojiphil** [comment] 2024-07-18 18:50
> After applying 2 updates as mentioned in my proposal, it works well. I believe it's the reason to add shouldEnableNewFocusManagement to blur the input.

@dominictb I am still curious to know about my comment [here](https://github.com/Expensify/App/issues/44042#issuecomment-2222505689) on why the eMoji picker works fine without the proposed changes as per your proposal. 
Can you please investigate on this?

**Comment by CortneyOfstad** [comment] 2024-07-22 19:13
@dominictb any update on the comment [here](https://github.com/Expensify/App/issues/44042#issuecomment-2237317594)?

**Comment by rojiphil** [comment] 2024-07-23 04:56
> > After applying 2 updates as mentioned in my proposal, it works well. I believe it's the reason to add shouldEnableNewFocusManagement to blur the input.
> 
> @dominictb I am still curious to know about my comment [here](https://github.com/Expensify/App/issues/44042#issuecomment-2222505689) on why the eMoji picker works fine without the proposed changes as per your proposal. Can you please investigate on this?

@dominictb I am particularly interested to know this. Can you please update on this?

**Comment by rojiphil** [comment] 2024-07-27 09:54
> -> we can't get the active input -> the logic to blur input [here](https://github.com/Expensify/App/blob/0c20881a308244867119efa6196481b65bb81274/src/libs/ComposerFocusManager.ts#L110) is not triggered

@dominictb I am not thoroughly convinced yet of the proposed solution. But maybe I am missing something. 
Anyway, as I understand, not triggering the blur of the composer is the root cause of this issue. If so, would it not be simpler to blur the composer if it is focused when we show popover [here](https://github.com/Expensify/App/blob/5e6527613d0f234fcb22507b878697a2bec356c5/src/pages/home/report/ReportActionItem.tsx#L346)?

**Comment by rojiphil** [comment] 2024-07-30 05:03
> Yes we can do that, but I think we already had the logic to do that

> we need to fix the bug at this place instead of making the workaround

@dominictb I think the new logic was originally added for emoji picker keyboard issue to ensure that the keyboard focus comes back on dismissing the emoji modal. 
However, the logic for bringing the focus back to composer for `ReportActionContextMenu` is managed by `ReportActionComposeFocusManager` as mentioned [here](https://github.com/Expensify/App/blob/df69c80229acdc510064d2671e2fdde8095a93a7/src/pages/home/report/ContextMenu/ContextMenuActions.tsx#L23). 
So, why is it a workaround to make use of  `ReportActionComposeFocusManager` for blurring the composer?

**Comment by wildan-m** [comment] 2024-07-31 07:03
@rojiphil Is the original issue not reproducible? The remaining issue is with long-pressing, right?

**Comment by wildan-m** [comment] 2024-07-31 07:37
## Proposal

### Please re-state the problem that we are trying to solve in this issue.

mWeb/Safari - Chat - Keyboard does not close when action menu opens

The original issue is not reproducible due to [changes in the three dots UI](https://github.com/Expensify/App/issues/44042#issuecomment-2222502179), but a similar issue occurs when long pressing the reportActionItem.

### What is the root cause of that problem?

In safari IOS, when we long pressing component, the keyboard will not automatically hide and we only intentionally blur the input focus in OptionRowLHN secondaryInteraction event

https://github.com/Expensify/App/blob/8e79c59615feb7de82e4aaa42d8b2297542f5b3b/src/components/LHNOptionsList/OptionRowLHN.tsx#L167-L170

### What changes do you think we should make in order to solve the problem?
Move this code:
https://github.com/Expensify/App/blob/8e79c59615feb7de82e4aaa42d8b2297542f5b3b/src/components/LHNOptionsList/OptionRowLHN.tsx#L167-L170

To the method that calls the popOver: `showPopover`, `showContextMenuForReport`, `showPopoverMenu`
e.g.


src/components/ShowContextMenuContext.ts
```tsx
function showContextMenuForReport(
    event: GestureResponderEvent | MouseEvent,
    anchor: ContextMenuAnchor,
    reportID: string,
    action: OnyxEntry<ReportAction>,
    checkIfContextMenuActive: () => void,
    isArchivedRoom = false,
) {
    if (!DeviceCapabilities.canUseTouchScreen()) {
        return;
    }

    // Ensure that we blur the composer when opening context menu, so that only one component is focused at a time
    if (DomUtils.getActiveElement()) {
        (DomUtils.getActiveElement() as HTMLElement | null)?.blur();
    }

```


[Branch for this solution.](https://github.com/Expensify/App/compare/main...wildan-m:App:wildan/fix/44042-blur-input-before-show-popover?expand=1)

### What alternative solutions did you explore? (Optional) 

When `onSecondaryInteraction` or `onLongPress` show a popOver,  add this code:

```
 if (DomUtils.getActiveElement()) {
                                (DomUtils.getActiveElement() as HTMLElement | null)?.blur();
                            }
```

For instance:
```tsx
                        onSecondaryInteraction={(event) => {
                            // Ensure that we blur the composer when opening context menu, so that only one component is focused at a time
                            if (DomUtils.getActiveElement()) {
                                (DomUtils.getActiveElement() as HTMLElement | null)?.blur();
                            }

                            showPopover(event);
                        }}

```

**Comment by rojiphil** [comment] 2024-07-31 09:35
@wildan-m Thanks for your proposal but I do not see the approach of your proposed solution anyway different than what's been discussed [here](https://github.com/Expensify/App/issues/44042#issuecomment-2254097505).

**Comment by rojiphil** [comment] 2024-07-31 09:36
> You mean using `ReportActionComposeFocusManager.composerRef.blur()` in

@dominictb Yes. Something like that but a helper called `blur` could help there.

**Comment by wildan-m** [comment] 2024-07-31 09:43
@rojiphil, my proposal is a sample implementation of the solution mentioned in [this comment](https://github.com/Expensify/App/issues/44042#issuecomment-2254097505). Has this solution already been officially proposed?

**Comment by wildan-m** [comment] 2024-07-31 09:54
@rojiphil I've also mentioned [existing similar pattern](https://github.com/Expensify/App/blob/8e79c59615feb7de82e4aaa42d8b2297542f5b3b/src/components/LHNOptionsList/OptionRowLHN.tsx#L167-L170) and suggest to move it to the inner method

**Comment by CortneyOfstad** [comment] 2024-07-31 13:01
Didn't mean to remove the bug label! Sorry Puneet!

**Comment by rojiphil** [comment] 2024-08-06 16:26
As the logic for bringing the focus back to composer for ReportActionContextMenu is managed by ReportActionComposeFocusManager as mentioned [here](https://github.com/Expensify/App/blob/df69c80229acdc510064d2671e2fdde8095a93a7/src/pages/home/report/ContextMenu/ContextMenuActions.tsx#L23), using `ReportActionComposeFocusManager` to blur makes sense to me.
@dominictb [proposal](https://github.com/Expensify/App/issues/44042#issuecomment-2191415145) with the alternate solution LGTM.
🎀👀🎀 C+ reviewed

**Comment by wildan-m** [comment] 2024-08-07 02:15
@rojiphil why limit the input to ReportActionComposeFocusManager.composerRef, when we should make the solution generic to any input field?  `(DomUtils.getActiveElement() as HTMLElement | null)?.blur()`

**Comment by rojiphil** [comment] 2024-08-08 04:48
> Why limit the input to ReportActionComposeFocusManager.composerRef, when we should make the solution generic to any input field?

@wildan-m Why do you think we need to make the solution generic to any input field? Making the solution generic could lead to possible regressions where the input field focus needs to be retained post context menu handling. 

And even if we have to make the solution generic, @dominictb primary solution makes more sense than yours. Focus management has been a tricky issue for a long time. So, why unnecessarily disturb the existing working system and invite possible regressions when ReportActionComposeFocusManager is already there? 

Alternatively, if the idea is to redesign the focus management, then it would be better to do away with ReportActionComposeFocusManager. But, I do not think that is the scope and intent of this issue. 

@cead22 can weigh in and conclude on the way ahead.

**Comment by wildan-m** [comment] 2024-08-08 06:49
> Making the solution generic could lead to possible regressions where the input field focus needs to be retained post context menu handling.

@rojiphil do you have reproducible steps to show that potential regression? I think it's expected to blur the focus from any element when new pop up appeared.

FYI, the selected proposal will not work for editing the message if it's not the main composer. A similar issue will arise when there is active text input and a component with a context menu on the same screen.

**Comment by wildan-m** [comment] 2024-08-08 06:51
> the selected proposal will not work for editing the message if it's not the main composer.


https://github.com/user-attachments/assets/c6627ef6-cc96-45b5-9b79-e5217e849e5f

**Comment by rojiphil** [comment] 2024-08-08 07:08
> the selected proposal will not work for editing the message if it's not the main composer.

@wildan-m Yes. That’s why I think `ReportActionComposeFocusManager` should be used here as that was designed to handle the blur and focus of `edit composer` and `main composer`. If this is not working as intended, some regression has caused this. But, this can be addressed in the PR stage.

**Comment by cead22** [comment] 2024-08-08 16:22
Correct me if I misunderstood
- @dominictb main proposal (ie, not the alternative) wouldn't solve the issue for the edit composer
- @dominictb alternative proposal solves it for the main composer and the edit composer
- It's possible that that proposal doesn't solve every case
- We could build a generic solution to try to handle every case automatically
- @wildan-m proposal would solve the issue on the edit composer, the main composer, and potentially other cases. That said, we haven't done a deep dive to see what those other cases would be
- @wildan-m proposal has the risk of breaking other places, due to the generic nature of the solution

If that's the case, I think @rojiphil 's concern about breaking other places of the app is valid, specially if we've had recurring issues with focus/blur

**Comment by rojiphil** [comment] 2024-08-08 19:24
> I think @rojiphil 's concern about breaking other places of the app is valid, specially if we've had recurring issues with focus/blur

@cead22  There are two main approaches here. 
1. A generic solution to blur any input field. 
2. A specific solution to blur edit composer and main composer.

The generic solution has the risk of breaking other places as we do not know if the focus is expected to remain in the input field after the context menu is dismissed. @dominictb main solution and @wildan-m proposal are both generic and has this risk.
Whereas the specific solution via ReportActionComposeFocusManager deals exclusively with blur and focus of edit composer and main composer thereby avoiding the risk of breaking other places in the app. @dominictb alternate solution is to use this approach.

**Comment by wildan-m** [comment] 2024-08-08 21:28
> @dominictb alternative proposal solves it for the main composer and the edit composer

no it is not working for edit

**Comment by wildan-m** [comment] 2024-08-08 21:34
> do you have reproducible steps to show that potential regression? I think it's expected to blur the focus from any element when new pop up appeared.

@rojiphil you haven't answered all of my question

> @wildan-m proposal has the risk of breaking other places, due to the generic nature of the solution
my solution adopted 

@cead22 my solution come from [the existing solution](https://github.com/Expensify/App/blob/8e79c59615feb7de82e4aaa42d8b2297542f5b3b/src/components/LHNOptionsList/OptionRowLHN.tsx#L167-L170) for other case. I don't see any issue from the implementation

**Comment by rojiphil** [comment] 2024-08-09 03:03
> > do you have reproducible steps to show that potential regression? I think it's expected to blur the focus from any element when new pop up appeared.
> 
> @rojiphil you haven't answered all of my question

@wildan-m I have already answered your question with the following. 

> Why do you think we need to make the solution generic to any input field? Making the solution generic could lead to possible regressions where the input field focus needs to be retained post context menu handling.
> 
> And even if we have to make the solution generic, @dominictb primary solution makes more sense than yours. Focus management has been a tricky issue for a long time. So, why unnecessarily disturb the existing working system and invite possible regressions when ReportActionComposeFocusManager is already there?
> 
> Alternatively, if the idea is to redesign the focus management, then it would be better to do away with ReportActionComposeFocusManager. But, I do not think that is the scope and intent of this issue.
> 

> Yes. That’s why I think `ReportActionComposeFocusManager` should be used here as that was designed to handle the blur and focus of `edit composer` and `main composer`. If this is not working as intended, some regression has caused this. But, this can be addressed in the PR stage.

And you already pointed out the regression related to `edit composer`. Shouldn't the `edit composer` retain the focus once the context menu action is handled? Isn't `ReportActionComposeFocusManager` designed to manage the blur and focus of `edit composer` and `main composer`? If so, shouldn't ReportActionComposeFocusManager be used to fix this issue? And if at all we want to go with the generic approach, why is your proposal better than the main solution of @dominictb?  Can you please address these questions first and we can take this further from there?

**Comment by wildan-m** [comment] 2024-08-09 03:11
@rojiphil @cead22 is there a case where we need to keep the previous focus input when a popover shown?

my solution advantage is already described [here](https://github.com/Expensify/App/issues/44042#issuecomment-2276211079).

> @wildan-m proposal would solve the issue on the edit composer, the main composer, and potentially other cases.

**Comment by rojiphil** [comment] 2024-08-09 04:36
> > @dominictb alternative proposal solves it for the main composer and the edit composer
> 
> @cead22 no it is not working for edit

This is already addressed [here](https://github.com/Expensify/App/issues/44042#issuecomment-2275105043)

**Comment by rojiphil** [comment] 2024-08-09 16:58
@cead22  So, based on this [comment here](https://github.com/Expensify/App/issues/44042#issuecomment-2276506083), the first decision to make is  a) Generic solution or b) Specific solution? 

If the specific solution approach is chosen, then @dominic’s alternative approach of using ReportActionComposeFocusManager is good enough. 

And if it is fine to blur any input field, the generic solution approach can be chosen. 
Here both @dominictb main solution and @wildan-m solution would fix the issue (i.e. both main composer and edit composer would work). @wildan-m solution seems like a hack, although the same pattern is used elsewhere. Whereas @dominictb main solution seems neater as that is a new pattern introduced elsewhere recently for focus management. But as bringing back the composer focus is managed by ReportActionComposeFocusManager, we can use the new focus management for only blurring purposes. 

This kindof summarizes the entire discussion here. 
What’s your choice?

**Comment by cead22** [comment] 2024-08-10 00:04
> And if it is fine to blur any input field,

How many places in the app would be affected? 

I ask because if there's many, then maybe this is a larger product discussion, not to mention the PR will need to test every possible place that could be affected

**Comment by rojiphil** [comment] 2024-08-11 19:20
> > And if it is fine to blur any input field,
> 
> How many places in the app would be affected?
> 
> I ask because if there's many, then maybe this is a larger product discussion, not to mention the PR will need to test every possible place that could be affected

@cead22 Well! I think that’s difficult to determine as the proposed generic approach is using `document.activeElement` which could be any active element (including the new ones added in the future) in the DOM. That seems pretty scary to me though.

**Comment by wildan-m** [comment] 2024-08-11 22:45
This is about defining the expected default behavior for context menus. When a context menu is displayed, which approach should we take?

(1) Should we blur the input by default and add specific conditional checks to retain focus only when necessary?
(2) Or should we avoid blurring any input by default, except when specific input fields focused?

**Comment by cead22** [comment] 2024-08-12 18:42
@rojiphil any thoughts on that last message from @wildan-m ^? 

Full disclosure, I'm leaning @dominictb 's more straightforward solution

**Comment by rojiphil** [comment] 2024-08-16 09:27
> This is about defining the expected default behavior for context menus. When a context menu is displayed, which approach should we take?

> any thoughts on that last message from @wildan-m ^

Sorry I missed this. This issue is specifically to do with blur/focus of the composer and we can keep it limited to this especially since there is an existing pattern around this. While the default behavior for context menus during display is an interesting topic for discussion, it seems like a project itself with a need for a wider consensus to apply in the entire project. You may want to initiate a separate discussion thread on Slack and take it from there.

**Comment by cead22** [comment] 2024-08-16 17:50
I agree, so I assigned @dominictb

**Comment by CortneyOfstad** [comment] 2024-09-11 15:35
@dominictb any update on the PR?

**Comment by rojiphil** [comment] 2024-10-24 17:52
* [x]  [@rojiphil] The PR that introduced the bug has been identified. Link to the PR: [Offending PR](https://github.com/Expensify/App/pull/18809)
* [x]  [@rojiphil] The offending PR has been commented on, pointing out the bug it caused and why, so the author and reviewers can learn from the mistake. Link to comment: [Added comment](https://github.com/Expensify/App/pull/18809/files#r1815488506)
* [x]  [@rojiphil] A discussion in #expensify-bugs has been started about whether any other steps should be taken (e.g. updating the PR review checklist) in order to catch this type of bug sooner. Link to discussion: Not Required. Existing checklist is good enough to capture such issues.
* [x]  [@rojiphil] Determine if we should create a regression test for this bug. : Yes. We can
* [x]  [@rojiphil] If we decide to create a regression test for the bug, please propose the [regression test](https://github.com/Expensify/App/blob/main/contributingGuides/REGRESSION_TEST_BEST_PRACTICES.md) steps to ensure the same bug will not reach production again. 

Steps:
Note: Tests are applicable only for native and mweb platforms.
1. Go to any chat
2. Click on the composer to bring the keyboard (if its not already open)
3. While the keyboard is open long press on a message to bring the action menu
4. Verify that the keyboard closes when the action menu is opened (Test 1)
5. Click and focus inside an editable message so that the keyboard is displayed.
6. While the keyboard is open long press on any other message to bring the action menu.
7. Verify that the keyboard closes when the action menu is opened (Test 2)

**Comment by rojiphil** [comment] 2024-10-24 17:53
@CortneyOfstad BZ Checklist is done.

**Comment by CortneyOfstad** [comment] 2024-10-28 17:47
Sorry for the delay here! 

@rojiphil – it looks like your offer expired back in September, so I issued you a new one [here](https://www.upwork.com/nx/wm/offer/104631325). Please let me know once you accept and I can get that paid ASAP. Thank you so much!

**Comment by rojiphil** [comment] 2024-10-28 17:48
> It looks like your offer expired back in September, so I issued you a new one [here](https://www.upwork.com/nx/wm/offer/104631325).

@CortneyOfstad Accepted offer. Thanks.

**Comment by CortneyOfstad** [comment] 2024-10-28 17:50
## Payment Summary

@dominictb — paid $250 via Upwork
@rojiphil — paid $250 via Upwork

## Regression Test

https://github.com/Expensify/Expensify/issues/439515

**Closed by CortneyOfstad** 2024-10-28 17:50 UTC
Labels: External, Daily, Awaiting Payment, Bug
