### ISSUE TITLE
[$1000] mweb - App does not refocus on compose box on message delete using edit mode on android chrome and app

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#22949] opened 2023-07-15 18:36 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Open the app
2. Open any report
3. Send any message
4. Edit the message and remove all text
5. Remove the text and click on green tick
6. In delete popup, click on delete and observe that app does not refocus on compose box (works fine on web chrome)

## Expected Result:
App should refocus on compose box on deleting message using edit mode as it does on web chrome

## Actual Result:
App does not refocus on compose box on deleting message using edit mode

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android / native
- [x] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [ ] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 1.3.41-1
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/93399543/ce9a7319-3a75-4350-b51e-3340943638aa

https://github.com/Expensify/App/assets/93399543/b8609c0a-0b08-4acb-a96d-edf148912784

**Expensify/Expensify Issue URL:**
**Issue reported by:** @dhanashree-sawant
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1689363436779099

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~010ac4c166c4d90b1e</li>
        <li>Upwork Job ID: 1681531735404843008</li>
        <li>Last Price Increase: 2023-12-02</li>
    </ul>
</details>

**Comment by tjferriss** [comment] 2023-07-17 17:38
I'm not able to reproduce the issue on the desktop app. The app correctly refocuses on the compose box.


https://github.com/Expensify/App/assets/8292562/f076ddf8-8099-4727-8370-ffa275e11fdf

**Comment by dhanashree-sawant** [comment] 2023-07-17 17:57
Hi @tjferriss, the issue is specifically on android chrome and android app, sorry for confusion, it is not on desktop app

**Comment by tjferriss** [comment] 2023-07-18 16:52
Thanks @allroundexperts. I've re-opened so we can investigate.

**Comment by tjferriss** [comment] 2023-07-19 05:10
Added external label

**Comment by tjferriss** [comment] 2023-07-24 23:00
@aimane-chnaif can you take a look at this latest proposal when you have the time?

**Comment by tjferriss** [comment] 2023-07-27 05:17
Waiting for proposals to be reviewed.

**Comment by tjferriss** [comment] 2023-08-01 22:11
@aimane-chnaif can you take a look at the proposals when you have the chance?

**Comment by tjferriss** [comment] 2023-08-03 18:44
Waiting on @aimane-chnaif to review the proposals.

**Comment by tjferriss** [comment] 2023-08-09 04:27
Waiting on @aimane-chnaif to review proposals, Melvin.

**Comment by tjferriss** [comment] 2023-08-10 20:06
We're waiting for proposals to be reviewed

**Comment by tjferriss** [comment] 2023-08-15 19:01
@bernhardoj thanks for referencing the tracking issue. I agree we should put this on hold for fixing the composer.

**Comment by tjferriss** [comment] 2023-08-21 19:34
This is on hold per https://github.com/Expensify/App/issues/15992

**Comment by tjferriss** [comment] 2023-08-28 22:10
Still on hold.

**Comment by tjferriss** [comment] 2023-09-11 22:56
Still on hold.

**Comment by tjferriss** [comment] 2023-09-25 07:55
Still on hold.

**Comment by tjferriss** [comment] 2023-10-04 05:28
Still holding

**Comment by tjferriss** [comment] 2023-10-11 04:40
@allroundexperts is this still reproducible on Android?

**Comment by tjferriss** [comment] 2023-10-30 04:46
Sounds good to me.

**Comment by tjferriss** [comment] 2023-11-10 21:58
@aimane-chnaif any updates here? I'm going to move this to off hold based on your previous comment.

**Comment by tjferriss** [comment] 2023-11-15 05:34
@aimane-chnaif any updates?

**Comment by tjferriss** [comment] 2023-11-20 17:08
@aimane-chnaif following once more, any update on this one?

**Comment by tjferriss** [comment] 2023-11-28 17:21
@aimane-chnaif any update here?

**Comment by tjferriss** [comment] 2023-12-05 05:33
I tend to agree with @aimane-chnaif synopsis above. I think we can safely close this issue and revisit it down the road.

**Closed by tjferriss** 2023-12-05 05:33 UTC
Labels: External, Engineering, Daily, Help Wanted, Overdue, Bug
