### ISSUE TITLE
[$500] Distance - Additional edit system messages are shown when request is created offline with edits

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#33671] opened 2023-12-27 21:23 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** v1.4.18-2
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** Applause - Internal Team
**Slack conversation:**

## Action Performed:
1. Go offline.
2. Create a distance request.
3. Go to the request details page.
4. Click description and enter one.
5. Click description again and enter a new one.
6. Go online.
7. Go back to expense report (because of the grayed out expense view bug).
8. Click on the distance expense.
Note that it shows additional edit system message that user did not perform.

## Expected Result:
Only the system message for description edit will be shown.

## Actual Result:
The system message also shows for amount change and category removal when neither have been performed at all.

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [x] Android: mWeb Chrome
- [x] iOS: Native
- [x] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

https://github.com/Expensify/App/assets/93399543/893f199a-8ca3-400d-a7b0-1173ed6f0efc

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01ba249cef3e37408f</li>
        <li>Upwork Job ID: 1740121158920376320</li>
        <li>Last Price Increase: 2024-01-24</li>
    </ul>
</details>

**Comment by unicorndev-727** [comment] 2023-12-27 23:45
## Proposal
from: @unicorndev-727
### Please re-state the problem that we are trying to solve in this issue.
Additional edit system messages are shown when request is created offline with edits
### What is the root cause of that problem?
The root cause is that we set all transaction data to be update here when we handle distance IOU edition here.
https://github.com/Expensify/App/blob/595bf4075988c0b64cb0db1e37694284637fbea2/src/libs/TransactionUtils.ts#L157
### What changes do you think we should make in order to solve the problem?
We need to update this line 
```
const updatedTransaction = {...transaction};
```
to
```
const updatedTransaction = {} as Transaction
```
### What alternative solutions did you explore? (Optional)
  N/A

**Comment by peterdbarkerUK** [comment] 2024-01-02 20:08
I'm not sure how to prioritise this, [internal discussion](https://expensify.slack.com/archives/C02MW39LT9N/p1704225987108489)

**Comment by kmbcook** [comment] 2024-01-09 17:42
## Please re-state the problem that we are trying to solve in this issue.
  Distance - Additional edit system messages are shown when request is created offline with edits.

## What is the root cause of that problem?
  New update distance request API is not yet finished. See https://github.com/Expensify/App/issues/28358. 

## What changes do you think we should make in order to solve the problem?
  Use the the new update distance request API, when it is ready.

**Comment by peterdbarkerUK** [comment] 2024-01-16 21:04
Apologies, this one slipped off my radar. 

I've got a DM going, will update tomorrow

**Comment by peterdbarkerUK** [comment] 2024-01-22 15:55
Dylan and I misunderstood something in our DM and he didn't get a chance to look at this. I've updated

**Comment by dylanexpensify** [comment] 2024-01-23 12:09
@neil-marcellini to confirm, but this looks like a bug to me

**Comment by neil-marcellini** [comment] 2024-01-23 17:50
I agree it's a bug. @peterdbarkerUK would you please search for similar issues to make sure it's not a duplicate? I recall something similar recently. Also, please assign me when it's time for an internal engineer proposal review 🙂

**Comment by mallenexpensify** [comment] 2024-01-24 03:38
@situchan reassigning, please take over as C+. If you don't have bandwidth, unassign yourself. Thanks

**Comment by situchan** [comment] 2024-01-24 16:21
I got this error after making online, so description is not updated actually

<img width="1156" alt="Screenshot 2024-01-24 at 10 20 22 PM" src="https://github.com/Expensify/App/assets/108292595/3a1551bb-2406-422d-8358-ac3622dcbcaa">

**Comment by situchan** [comment] 2024-01-24 16:25
https://github.com/Expensify/App/pull/33997 is supposed to fix this. It already reached production

**Comment by situchan** [comment] 2024-01-24 16:26
@kbecciv is this still reproducible on latest staging?

**Comment by kbecciv** [comment] 2024-01-25 20:36
@situchan Not reproducible v1.4.32-2

https://github.com/Expensify/App/assets/93399543/8303eabb-30df-4ba2-8cdb-aab26d6c2c01

**Comment by situchan** [comment] 2024-01-25 22:31
Thanks. Let's close this

**Comment by mvtglobally** [comment] 2024-01-30 04:54
Issue not reproducible during KI retests. (First week)

**Comment by peterdbarkerUK** [comment] 2024-01-31 14:45
Fixed and no longer reproducible

**Closed by peterdbarkerUK** 2024-01-31 14:45 UTC
Labels: External, Engineering, Daily, Help Wanted, Overdue, Bug
