### ISSUE TITLE
[HOLD for payment 2023-10-23][$250] Upgrade lottie-react-native to 6.3.1

### ISSUE THREAD

**Issue by roryabraham** [Expensify/App#28132] opened 2023-09-25 12:49 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

Slack convo: https://expensify.slack.com/archives/C04878MDF34/p1695304606676759

### Problem
There are breaking changes in lottie-react-native 6.0 and we're still using 5.1.6. There are E/App changes needed to complete https://github.com/Expensify/App/issues/26871

### Solution
Upgrade E/App to use lottie-react-native 6.3.1+

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~012d74e563bdfd8754</li>
        <li>Upwork Job ID: 1706290261133504512</li>
        <li>Last Price Increase: 2023-09-25</li>
<li>Automatic offers: </li>
<ul>
<li>ZhenjaHorbach | Contributor | 26874866</li>
<li>situchan | Contributor | 26992172</li>
</ul></li>
    </ul>
</details>

**Comment by b4s36t4** [comment] 2023-09-25 15:19
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
Upgrade lottie-react-native to 6.3.1
### What is the root cause of that problem?
NA RC
### What changes do you think we should make in order to solve the problem?

1. Upgrading from v5 to v6 has few breaking changes, and at this point there's nothing that we're using which causes any breaking changes. So we can easily upgrade to the `lottie-react-native` to latest verion.

2. Deprecate support for `react-native-web-lottie`, as mentioned in description we're moving with `.lottie` files so web-lottie is not required. (remove from package)

3. Install `@dotlottie/react-player` for web support.

Since we can not support webpack/babel alias support for this package we can create a cross-platform component Just as a layer for the platform specific packages.

Like inside components folder we would create `index.js/ts` and export a wrapper component with name as `Lottie` and `index.website.js` to create a wrapper component which uses `Lottie` from `@dotlottie/react-player` package.

> for `@dotlottie/react-player`  we should check that json animations are support or not, if we not first we should migrate all `.json` file to `.lottie` files then we should move ahead with this implementation



### What alternative solutions did you explore? (Optional)
NA

**Comment by b4s36t4** [comment] 2023-09-25 15:23
I think we have a draft PR ready with `lottie-react-native` so Just upgrading and removing the dependecy of `lottie-web-react-native` should complete the work.

**Comment by roryabraham** [comment] 2023-09-26 02:08
> Install @dotlottie/react-player for web support.

Definitely out-of-scope for this issue. We're working building web support directly into lottie-react-native in https://github.com/Expensify/App/issues/26871

**Comment by b4s36t4** [comment] 2023-09-26 03:11
> I think we have a draft PR ready with `lottie-react-native` for web support so Just upgrading and removing the dependecy of `lottie-web-react-native` should complete the work.

@roryabraham I have mentioned it here. 🥺

**Comment by dangrous** [comment] 2023-09-29 04:39
@mananjadhav @roryabraham I got assigned to review [the PR](https://github.com/Expensify/App/pull/28267) for this but I think y'all should probably grab it? If you don't want to let me know though. Thanks! cc @ZhenjaHorbach

**Comment by dylanexpensify** [comment] 2023-10-02 14:18
bump @mananjadhav @roryabraham on this ^

**Comment by mananjadhav** [comment] 2023-10-02 16:05
@dylanexpensify Can you please assign another C+, I am still catching up after OOO.

**Comment by roryabraham** [comment] 2023-10-23 16:37
@Christinadobrzyn @dylanexpensify this is ready for payment

**Comment by Christinadobrzyn** [comment] 2023-10-23 16:48
Gotcha!

Payment summary:

Bug reporter: NA
Contributor: $250 @ZhenjaHorbach (paid in Upwork)
Contributor+: $250 @situchan (paid in Upwork)

Bonus: N - based on https://github.com/Expensify/App/issues/28132#issuecomment-1757537983

Upwork job - https://www.upwork.com/jobs/~012d74e563bdfd8754

**Closed by Christinadobrzyn** 2023-10-23 16:48 UTC
Labels: External, Daily, NewFeature, Awaiting Payment
