### ISSUE TITLE
Android - Workspace - Workspace name is not fully displayed on Profile page

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#37548] opened 2024-02-29 18:12 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.45-0
**Reproducible in staging?:** Y
**Reproducible in production?:** N
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):** gocemate@gmail.com
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** Applause - Internal Team
**Slack conversation:**

## Action Performed:
1. Sign in with Gmail account
2. Go to Settings> Create new Workspace
3. Navigate to Profile

## Expected Result:
Workspace name should be fully displayed

## Actual Result:
Workspace name is not fully displayed

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [ ] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details> 

![Bug6397365_1709227933873!Capture](https://github.com/Expensify/App/assets/78819774/f039f48d-e540-4057-a6d0-13c6ef5592be)

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by lanitochka17** [comment] 2024-02-29 18:13
Production:


https://github.com/Expensify/App/assets/78819774/42e0bbe7-910c-4196-8c83-c4e3c6a6cf6c

**Comment by lanitochka17** [comment] 2024-02-29 18:14
@hayata-suenaga  FYI I haven't added the External label as I wasn't 100% sure about this issue. Please take a look and add the label if you agree it's a bug and can be handled by external contributors

**Comment by lanitochka17** [comment] 2024-02-29 18:14
We think that this bug might be related to #vip-vsp
CC @quinthar

**Comment by rushatgabhane** [comment] 2024-02-29 18:32
not a bug. looks like it's intentional

**Comment by hayata-suenaga** [comment] 2024-02-29 19:02
looking at this right now 👀

**Comment by hayata-suenaga** [comment] 2024-02-29 19:04
yep this clearly looks like intentional change.

@lanitochka17 did you have any TestRail case that specify that the workspace name should be fully displayed?

**Comment by hayata-suenaga** [comment] 2024-02-29 19:04
anyway, closing this for now

**Closed by hayata-suenaga** 2024-02-29 19:04 UTC
Labels: Engineering
