### ISSUE TITLE
[HOLD for payment 2022-11-02] [Bug] [$500] HTML formatted messages render incorrectly

### ISSUE THREAD

**Issue by mvtglobally** [Expensify/App#11320] opened 2022-09-27 04:22 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:

1. Create an html file with the content below and open it in the browser
    ```html
    <p dir="ltr">Here's what I recommend for new members. </p><br /><p dir="ltr"><strong>Demo and onboarding calls</strong></p><ul><li dir="ltr"><p dir="ltr"><a href="https://www.expensify.com/inbox?taskID=ConciergeWelcome&amp;calltaskid=ConciergeWelcome" target="_blank" rel="noreferrer noopener">Request a call</a> — our Guides team is standing by to provide live demos and onboarding assistance for new customers.</p></li></ul><p dir="ltr"><strong>Self-paced learning</strong></p><ul><li dir="ltr"><p dir="ltr"><a href="https://community.expensify.com/discussion/5694/deep-dive-admin-training-and-setup-resources/p1?new=1" target="_blank" rel="noreferrer noopener">Admin training and resources</a> — step-by-step guide covering the basics of expense reporting for Policy Admins.</p></li><li dir="ltr"><p dir="ltr"><a href="https://community.expensify.com/discussion/5922/deep-dive-day-1-with-expensify-for-submitters/p1?new=1" target="_blank" rel="noreferrer noopener">Day 1 for Submitters/Employees</a> — a guide for employees submitting expenses for the first time.</p></li><li dir="ltr"><p dir="ltr"><a href="https://community.expensify.com/discussion/6018/deep-dive-day-1-with-the-expensify-card" target="_blank" rel="noreferrer noopener">Day 1 with the Expensify Card</a> — getting started with your new Expensify Card.</p></li><li dir="ltr"><p dir="ltr"><a href="https://community.expensify.com/discussion/8629/employee-training-e-learning-programme/p1?new=1" target="_blank" rel="noreferrer noopener">Employee Training E-Learning Program</a> — an in-depth training programme for users who like a comprehensive step-by-step approach.</p></li><li dir="ltr"><p dir="ltr"><a href="https://community.expensify.com/" target="_blank" rel="noreferrer noopener">community.expensify.com</a> — searchable resources for best practices and troubleshooting. </p></li></ul><p dir="ltr"><strong>Training videos</strong></p><ul><li dir="ltr"><p dir="ltr"><a href="https://expensify.wistia.com/medias/1kx52dx68e" target="_blank" rel="noreferrer noopener">Admin Onboarding</a> — will help to increase your knowledge of Expensify setup and administration.</p></li></ul>If you have any specific questions, don't hesitate to reach back out though! That's what <a href="https://community.expensify.com/discussion/5515/deep-dive-meet-concierge/p1?new=1" target="_blank" rel="noreferrer noopener">I'm here for!</a>
    ```
3. Select all and copy
4. Paste it in an email body and send the email to `replies+<report_id>@expensify.com`. The `<report_id>` can be obtained from a URL of a chat between your account and some other account. The subject of the email can be any.
![image](https://user-images.githubusercontent.com/87341702/195175822-da13e920-2301-4165-aff2-47b248bae045.png)

Video of steps reproducing the bug:

https://user-images.githubusercontent.com/87341702/195175870-5d884026-3d0a-40c4-b54e-03b117b7bbd4.mov

## Expected Result:
Messages should be properly formatted

## Actual Result:
HTML formatted messages render incorrectly

## Workaround:
unknown 

## Platform:

Where is this issue occurring?

- Mobile Web and Web (haven't checked native)

**Version Number:** 1.2.12-0
**Reproducible in staging?:** Y
**Reproducible in production?:** Y 
**Email or phone of affected tester (no customers):** 
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation 

![Screenshot_20220913-121211](https://user-images.githubusercontent.com/43995119/192431207-966b0fbf-b41f-4345-8305-57acd3c14c7e.png)
![Screenshot_20220913-121003](https://user-images.githubusercontent.com/43995119/192431217-f45e37ce-6e6d-4c21-a76a-36fbb7eb324d.png)

**Expensify/Expensify Issue URL:** 
**Issue reported by:** @JmillsExpensify 
**Slack conversation:** https://expensify.slack.com/archives/C01GTK53T8Q/p1663173660551449

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by aldo-expensify** [comment] 2022-09-29 20:25
@mvtglobally can you detail a bit more what you mean by: "send some HTML messages", ideally providing some content we could copy paste to reproduce? I tried sending a message with HTML like `<div>hello</div>` and I just see the tags as plain text.

**Comment by aldo-expensify** [comment] 2022-10-03 22:31
Tested again in web mobile / web not mobile/ android and IOS, couldn't reproduce. Maybe it fails with some specific html layout. @mvtglobally do you know from where that html was copied from?

**Comment by JmillsExpensify** [comment] 2022-10-03 22:44
@aldo-expensify This is a Concierge message composed in the Concierge tool. (I just checked my messages in a test account and I wasn't able to find one like this).

**Comment by aldo-expensify** [comment] 2022-10-03 23:47
@JmillsExpensify thanks, I didn't consider that. I tested sending some copy/pasted html message from wikipedia, with links and lists, and the look fine.

<img width="200" alt="image" src="https://user-images.githubusercontent.com/87341702/193705344-6ca6af71-fc10-471a-88b0-283e8d6ce766.png">


I looked for some of the text we can see in the message from the screenshots of the GH issue, but I couldn't find it in the code.. so I supposed it is not an automatic Concierge message.

**Comment by JmillsExpensify** [comment] 2022-10-04 23:04
Yeah, I think this message came during one of our VIP projects. Hmm, maybe we should close then. I'm also not seeing this either.

**Comment by aldo-expensify** [comment] 2022-10-04 23:14
@JmillsExpensify  hehe i just noticed you reported this by looking at the slack conversation. Is it possible to you to get to this same conversation and check if now it is looking fine?

**Comment by JmillsExpensify** [comment] 2022-10-04 23:19
Yep! Sure thing, I'll go ahead and assign myself.

**Comment by aldo-expensify** [comment] 2022-10-04 23:21
thanks!

**Comment by JmillsExpensify** [comment] 2022-10-05 23:20
I didn't get a chance to test this so far, will come back soon.

**Comment by JmillsExpensify** [comment] 2022-10-06 19:16
Ok jumping back in to test this now.

**Comment by JmillsExpensify** [comment] 2022-10-06 20:05
Alright, I'm having the hardest time reproducing this. I sent myself a markdown formatted message via the company tool, I asked agents to send me HTML formatted text via the Concierge tool. Etc. etc. I'm still unable to produce on mobile web.

![IMG_8646705BA2BB-1](https://user-images.githubusercontent.com/1127863/194407707-4e08e372-3763-40dc-a66d-ea8846d46c85.jpeg)

**Comment by JmillsExpensify** [comment] 2022-10-06 20:05
My next move is to head back to the original thread and see if this is still visible for those that were participating there.

**Comment by JmillsExpensify** [comment] 2022-10-06 21:44
Ok I was able to reproduce this one. I just updated the OP. Screenshot of the issue on mWeb
![IMG_01821CEB4445-1](https://user-images.githubusercontent.com/1127863/194424249-2db85a3c-baf0-4b05-8d23-729aa98c80d4.jpeg)

**Comment by JmillsExpensify** [comment] 2022-10-06 21:46
@aldo-expensify You want to assign yourself again?

**Comment by aldo-expensify** [comment] 2022-10-06 22:42
I'm trying, but I can't reproduce it yet. I don't find that repeatable response, could it have been removed?

![image](https://user-images.githubusercontent.com/87341702/194431750-3473a873-38ba-4fc2-b82a-fe1501bffb05.png)

I tested with other responses, but they look fine in mWeb.

**Comment by aldo-expensify** [comment] 2022-10-06 22:45
it could be that that specific response had invalid html, and one browser was doing a better job than the other in fixing it. Can you reproduce this with any other pre-saved response (if we don't find the original one anymore)?

Thanks for updating the steps, it is much clearer now

**Comment by JmillsExpensify** [comment] 2022-10-06 23:27
Interestingly enough, I thought the same. I even deleted the old saved repeatable response and then manually created a new. But even the new, non-copy/pasted one I created still had the same problem. So it was just super super weird that it still happened despite that.

**Comment by aldo-expensify** [comment] 2022-10-06 23:30
Can you send me the response in an email or file? 🙏

**Comment by JmillsExpensify** [comment] 2022-10-10 02:49
Sure thing. I'll do that right now

**Comment by JmillsExpensify** [comment] 2022-10-10 02:55
Alright, I just sent to your aldo@expensifail.com account. Let me know if you're still not able to reproduce it on mWeb.

**Comment by aldo-expensify** [comment] 2022-10-11 18:57
![image](https://user-images.githubusercontent.com/87341702/195171307-dc5369e1-22a9-4498-abaf-92d497a648a7.png)
Thanks @JmillsExpensify !, it even looks broken in web (staging) for me

This can be reproduced by:

1. Open the html file in the browser
2. Select all and copy
3. Paste it in an email body and send the email to `replies+<report_id>@expensify.com`. The `<report_id>` can be obtained from a URL of a chat between your account and some other account. 
![image](https://user-images.githubusercontent.com/87341702/195175822-da13e920-2301-4165-aff2-47b248bae045.png)


Video of reproducing the bug:


https://user-images.githubusercontent.com/87341702/195175870-5d884026-3d0a-40c4-b54e-03b117b7bbd4.mov

**Comment by aldo-expensify** [comment] 2022-10-11 19:03
I checked if the HTML that causes the problem had syntax errors, but I didn't see any.

**Comment by JmillsExpensify** [comment] 2022-10-12 03:22
We're open for proposals. Please apply to the [Upwork job](https://www.upwork.com/jobs/~01521563b8fd74ea23) and note that I've increased the starting price to $500 given that this is tied to a roadmap priority.

**Comment by fedirjh** [comment] 2022-10-13 00:03
### Proposal

## Problem 
The RenderHTML add the flex property to some element `flex: 1 1 0%;` 

![Screenshot from 2022-10-13 00-54-16](https://user-images.githubusercontent.com/36869046/195468587-e518854f-b518-4340-af7a-b5f159ba346b.png)

## Solution
we can set an initial flex property to the config so the RenderHTML will use it instead of adding new one 

https://github.com/Expensify/App/blob/d0f0dd5ee7b88bf31d544f758ab7cfba88c6f0c0/src/components/HTMLEngineProvider/BaseHTMLEngineProvider.js#L44

```diff
-      const defaultViewProps = {style: [styles.alignItemsStart, styles.userSelectText]};
+      const defaultViewProps = {style: [styles.alignItemsStart, styles.userSelectText,styles.flexInherit]};
```

**then add the new `flexInherit` utility to Flex layout utility** 
https://github.com/Expensify/App/blob/d0f0dd5ee7b88bf31d544f758ab7cfba88c6f0c0/src/styles/utilities/flex.js#L6-L9

```diff
+    flexInherit:{
+      flex: 'inherit'
+    },
```

**Comment by JmillsExpensify** [comment] 2022-10-14 03:13
@parasharrajat thoughts on @fedirjh's proposal above?

**Comment by parasharrajat** [comment] 2022-10-14 15:38
This is happening on Chromium-based browsers.
Chrome
![image](https://user-images.githubusercontent.com/24370807/195886122-d659eff3-d7ef-4c15-a2e1-d33555240039.png)

Firefox
![image](https://user-images.githubusercontent.com/24370807/195886168-053fa141-7f21-47ae-be8b-251ab73a47d4.png)

**Comment by fedirjh** [comment] 2022-10-14 16:25
@parasharrajat Safari too

<img width="1332" alt="Untitled" src="https://user-images.githubusercontent.com/36869046/195894956-b2af432b-9782-4687-928a-c447dcf0ef84.png">

**Comment by parasharrajat** [comment] 2022-10-14 16:59
Yeah @fedirjh , Safari is chromium based browser.

I have a better proposal. This is happening due to `flex:1` https://github.com/Expensify/App/blob/7044ab2b96067081c8f67191e51fa859dba66d91/src/styles/styles.js#L79 

I traced back this change and it was added by me in https://github.com/Expensify/App/pull/5364. 

As I mentioned in the [proposal](https://github.com/Expensify/App/issues/5008#issuecomment-923212885) it was optional at that time. 

So I think we can just remove `flex: 1` and it will be fixed.

**Comment by parasharrajat** [comment] 2022-10-14 17:28
let me test this on IOS and safari web.

**Comment by parasharrajat** [comment] 2022-10-15 22:52
Looking good everywhere.

**Comment by JmillsExpensify** [comment] 2022-10-17 14:33
Ok so @aldo-expensify are we hiring @parasharrajat for this job? @chiragsalian are you good with this plan? As a reminder, the upwork job is here when we get there: https://www.upwork.com/jobs/~01521563b8fd74ea23.

**Comment by aldo-expensify** [comment] 2022-10-17 17:23
I vote for @parasharrajat 's solution, but leaving it up to @chiragsalian since he is the CME

**Comment by chiragsalian** [comment] 2022-10-17 19:04
Yes, I like @parasharrajat solution as well since its simple, and you've worked on this before and it seems to be working fine everywhere. Feel free to create the PR @parasharrajat.

**Comment by JmillsExpensify** [comment] 2022-10-26 17:16
Invited @parasharrajat to the Upwork job. Then as a more general update, the linked PR has been merged and should reach production in the next day or so. At that point we'll kick off the regression period hold before paying.

**Comment by JmillsExpensify** [comment] 2022-11-01 18:52
Don't see any regressions at this point, so I will circle back tomorrow for payment.

**Comment by JmillsExpensify** [comment] 2022-11-03 03:22
Waiting on @parasharrajat to accept the Upwork invite before job can be paid and issue closed.

**Comment by JmillsExpensify** [comment] 2022-11-03 18:46
@parasharrajat sent you an offer on Upwork. Will pay out as soon as you're able to accept.

**Comment by JmillsExpensify** [comment] 2022-11-03 20:24
Payment issued! Closing this one out.

**Closed by JmillsExpensify** 2022-11-03 20:24 UTC
Labels: Reviewing, External, Engineering, Daily, Help Wanted, Awaiting Payment, Bug
