### ISSUE TITLE
[$500] Web – Login – Possible to open 2 Login pages in two tabs and input magic code in both

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#29995] opened 2023-10-19 16:22 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:**1.3.87-1

**Reproducible in staging?:** Yes

**Reproducible in production?:** Yes

**If this was caught during regression testing, add the test name, ID and link from TestRail:**

**Email or phone of affected tester (no customers):**

**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Expensify/Expensify Issue URL:**

**Issue reported by:**  Applause - Internal Team

**Slack conversation:**

**Issue found when executing PR** https://github.com/Expensify/App/pull/29797
## Action Performed:
1. Go to https://staging.new.expensify.com/
2. Log out of app
3. Open app in two tabs/windows
4. In the first tab Enter your email address >> Continue

## Expected Result:
In the first tab, Verify that Another login page is open message appears. In the second tab, Enter your email address >> Continue. In the first tab, Verify that Another login page is open message still appear, without any login-related componens, such as magic code input, only the message itself

## Actual Result:
Possible to open 2 Login pages in two tabs and input magic code in both

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [x] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] Windows: Chrome 
- [ ] MacOS: Desktop

## Screenshots/Videos
<details>
<summary>Android: Native</summary>

</details>

<details>
<summary>Android: mWeb Chrome</summary>

</details>

<details>
<summary>iOS: Native</summary>

</details>

<details>
<summary>iOS: mWeb Safari</summary>

</details>

<details>
<summary: Windpws/ Chrome </summary>

 

https://github.com/Expensify/App/assets/78819774/e933ed02-5254-4bc0-93eb-f2595420d46b

</details>

<details>
<summary>MacOS: Desktop</summary>

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01ba4ae198898b7d83</li>
        <li>Upwork Job ID: 1715040738629197824</li>
        <li>Last Price Increase: 2023-10-19</li>
    </ul>
</details>

**Comment by Architn08** [comment] 2023-10-20 07:17
Seems like a dupe of https://github.com/Expensify/App/issues/29170 as the root cause is the same for both.

**Comment by robertKozik** [comment] 2023-10-20 07:59
Yeah agree, the same root cause as #29170. We can either hold it until #29170 will be resolved, or close this issue as it shares the same root cause. The later should be better

**Closed** 2023-10-20 10:48 UTC
Labels: External, Daily, Help Wanted, Bug
