### ISSUE TITLE
[$500] User can skip the initial step of "Assign task" without filling the title by changing the URL

### ISSUE THREAD

**Issue by kavimuru** [Expensify/App#28024] opened 2023-09-22 15:27 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1- click "Assign task"
2- Remove "/details" from the URL
## Expected Result: 
The app is redirecting the user to the next step
## Actual Result: 
The app should redirect the user back to the first step to fill in the title

## Workaround:
Can the user still use Expensify without this being fixed? Have you informed them of the workaround?

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [x] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 1.3.73-0
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/43996225/216c26ea-4b30-4550-ac99-2b00621486fe

[title-bypass (1).webm](https://github.com/Expensify/App/assets/43996225/4520f431-17ac-42db-8015-6bcacf0825bc)

**Expensify/Expensify Issue URL:**
**Issue reported by:** @hichamcc
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1695054621261049

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01d95237a153840f3b</li>
        <li>Upwork Job ID: 1705242414995161088</li>
        <li>Last Price Increase: 2023-10-10</li>
    </ul>
</details>

**Comment by abzokhattab** [comment] 2023-09-22 15:42
user is not rerouted to the titles page if no title is provided. 

so we should use `useEffect` and route to the title page if not title is provided.

**Comment by saranshbalyan-1234** [comment] 2023-09-22 15:52
## Proposal
### Please re-state the problem that we are trying to solve in this issue.
user is able to navigate to to assign task page by changing the url even without filling task details
### What is the root cause of that problem?
There is validation in this page for Title field. Even if title is not present, we are able to proceed further
https://github.com/Expensify/App/blob/main/src/pages/tasks/NewTaskPage.js
### What changes do you think we should make in order to solve the problem?
Add this line over here 
```javascript
        if (!props.task.title) return Navigation.goBack(ROUTES.NEW_TASK_DETAILS);
``` 
https://github.com/Expensify/App/blob/3d3e79199d16b85d737a5839bc8a4ffdd6fab511/src/pages/tasks/NewTaskPage.js#L74-L81
This would redirect to task details page again if title is not present (which is required field)
### What alternative solutions did you explore? (Optional)
N/A

**Comment by saranshbalyan-1234** [comment] 2023-09-22 18:05
@sonialiap is this allowed, by the time i pasted my proposal, the first proposal (@abzokhattab 's proposal) started editing, and edit several times. 
After checking history even the route on @abzokhattab proposal was different  i.e. ROUTES.TASK_TITLE

**Comment by abzokhattab** [comment] 2023-09-22 18:09
> @sonialiap is this allowed, by the time i pasted my proposal, the first proposal (@abzokhattab 's proposal) started editing, and edit several times.

was a typo, mate but the first one conveyed the idea I got to. In the end, our proposals are different. the reviewers will decide which one fits more

**Comment by situchan** [comment] 2023-09-22 18:14
@saranshbalyan-1234 we'll be reviewing them. Please refer to our [contributing guideline](https://github.com/Expensify/App/blob/main/contributingGuides/CONTRIBUTING.md#propose-a-solution-for-the-job).
If proposal is edited, please make sure to add new comment "Proposal updated" with original proposal link.
Minor things like typo, demo video can be updated without new comment as long as they don't significantly change original proposal.

**Comment by sonialiap** [comment] 2023-09-26 04:19
As @situchan mentioned, the guidelines around proposal editing are in the guidelines.

@situchan have you had a chance to review the existing proposals?

**Comment by situchan** [comment] 2023-09-26 04:22
> The app is redirecting the user to the next step

@sonialiap do you think this expected behavior is good?

**Comment by DylanDylann** [comment] 2023-09-26 11:37
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
- User can skip the initial step of "Assign task" without filling the title by changing the URL

### What is the root cause of that problem?
- Currently, we do not have the logic that checks if the prop.task.title is empty or not, and if true, back to the previous screen like other screens

### What changes do you think we should make in order to solve the problem?
- We can add the above logic. So the logic https://github.com/Expensify/App/blob/52c3f531d8b746e4e38a839ad8251ef6af857811/src/pages/tasks/NewTaskPage.js#L119-L122 can be updated to:
```
 if (!_.isUndefined(props.task.title)) {
            setTitle(props.task.title);
        } else {
            Navigation.goBack(ROUTES.NEW_TASK_DETAILS, true);
        }
```
- But if we just do like this, there is the case: user in ```/new/task/details``` screen, inputs the title and then clicks on next button, it will navigate user to ```/new/task``` and then navigate user to ```/new/task/details``` immediately. The RCA is that, in ```/new/task/details```, when user inputs the title and then clicks the next button
https://github.com/Expensify/App/blob/52c3f531d8b746e4e38a839ad8251ef6af857811/src/pages/tasks/NewTaskDetailsPage.js#L66-L68  it will navigate to the ```/new/task``` but the Onyx action is not successful. 
- So we need to make sure the data is updated successfully before navigating to the next screen, by update https://github.com/Expensify/App/blob/52c3f531d8b746e4e38a839ad8251ef6af857811/src/pages/tasks/NewTaskDetailsPage.js#L66-L68 to
```
  function onSubmit(values) {
        Task.setDetailsValue(values.taskTitle, values.taskDescription, ()=> Navigation.navigate(ROUTES.NEW_TASK));
    }
```
```
function setDetailsValue(title, description, onMerged) {
    // This is only needed for creation of a new task and so it should only be stored locally
    Onyx.merge(ONYXKEYS.TASK, {title: title.trim(), description: description.trim()}).then(() => onMerged());
}
```

### What alternative solutions did you explore? (Optional)
- NA

### Result
Solution:

[Screencast from 26-09-2023 18:32:24.webm](https://github.com/Expensify/App/assets/141406735/64b4eefd-546a-4038-b7d9-764123a43e57)

If we don't make sure that the title is updated successfully before navigate to /new/task screen:

[Screencast from 26-09-2023 18:36:24.webm](https://github.com/Expensify/App/assets/141406735/118fa279-e780-4128-ae73-2ce378bd5799)

**Comment by saranshbalyan-1234** [comment] 2023-09-26 13:42
Hi @sonialiap 
Can you please explain how thing goes here.
This issue is closed but proposal reviews still pending

**Comment by saranshbalyan-1234** [comment] 2023-09-30 19:21
hi @situchan, @sonialiap i think this issue is closed by mistake, please check once

**Comment by situchan** [comment] 2023-10-03 16:29
> there is the case: user in `/new/task/details` screen, inputs the title and then clicks on next button, it will navigate user to `/new/task` and then navigate user to `/new/task/details` immediately.

@DylanDylann I am not able to reproduce. Can you share video?

**Comment by DylanDylann** [comment] 2023-10-03 16:30
@situchan the video has been added in my proposal (section ### Result)

**Comment by saranshbalyan-1234** [comment] 2023-10-03 16:35
basically the issue is that https://staging.new.expensify.com/new/task this url is taking to the confirm page

**Comment by saranshbalyan-1234** [comment] 2023-10-03 16:35
and reproducable on sating as of now

**Comment by sonialiap** [comment] 2023-10-10 12:18
Reproducible, users can indeed skip the title assignment by deleting "details" from the URL. As a bonus, we also get a funny error, "missing translation" when trying to save the task without the two required fields (title, location). However, I'm not sure we need to prevent a user from going to `https://staging.new.expensify.com/new/task/`. From this page they can edit the title and add location which will create a viable task.

Steps:
1. Assign task
2. delete "details" from URL (i.e. go to https://staging.new.expensify.com/new/task/)
3. the right had nav correctly opens the task confirmation page (https://staging.new.expensify.com/new/task/). The Title field is blank, but that makes sense, the "next" button hadn't been pressed so the title hadn't been saved. From here you can edit the fields and create a viable task

https://github.com/Expensify/App/assets/17131195/3acc6f6e-791d-457c-946a-bbfd1e0d8088

**Comment by sonialiap** [comment] 2023-10-10 12:25
I reported the "missing translation" as a separate error https://expensify.slack.com/archives/C049HHMV9SM/p1696940644742429

**Comment by situchan** [comment] 2023-10-10 22:08
Agree do nothing as this doesn't block user create task flow.

**Comment by sonialiap** [comment] 2023-10-17 01:28
Sounds good, closing

**Closed by sonialiap** 2023-10-17 01:28 UTC
Labels: External, Engineering, Daily, Help Wanted, Overdue, Bug
