### ISSUE TITLE
[Ready for payment - $1000] mWeb- Chat- In secondary device, in real time, emoji selected is not updated in frequently used

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#23800] opened 2023-07-28 14:45 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
Pre- con: In 2 device, open same account, same conversation, open emoji picker
1. Go to https://staging.new.expensify.com/
2. Tap on a conversation as mentioned in one condition
3. Tap on emoji picker
4. Select emoji which is not in frequently used
5. Tap emoji picker again to see selected emoji in frequently used
6. Notice the same conversation and emoji picker opened in secondary device

## Expected Result:
In secondary device, in real time, emoji selected must be updated in frequently used list.

## Actual Result:
In secondary device, in real time, emoji selected is not updated in frequently used list.

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [x] Android / Chrome
- [ ] iOS / native
- [x] iOS / Safari
- [ ] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 1.3.47.3
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/93399543/38e9dc8d-fd26-4ec4-9109-cdf8e9cad22b

https://github.com/Expensify/App/assets/93399543/2c29dcbe-85b4-41f7-af79-e83dd7f497f8

**Expensify/Expensify Issue URL:**
**Issue reported by:** Applause - Internal Team
**Slack conversation:**

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~017543882e0e6eca1f</li>
        <li>Upwork Job ID: 1685003669049524224</li>
        <li>Last Price Increase: 2023-07-28</li>
    </ul>
</details>

**Comment by AdeemWaseem** [comment] 2023-07-28 22:20
Issue:

The issue is that the app crashes when navigating to the /details page directly from the /expenses page.

Proposal:

The following changes will be made to fix the issue:

The /details page will be made to load asynchronously. This will prevent the app from crashing if the page takes a long time to load.
The /details page will be made to check for the existence of the expense before loading. This will prevent the app from crashing if the expense does not exist.
The /details page will be made to handle errors more gracefully. This will prevent the app from crashing if an error occurs while loading the page.
Steps to implement the proposal:

Create a fork of the Expensify/App GitHub repo.
Create a branch on the fork and make the changes outlined in the proposal.
Test the changes on all platforms.
Create a pull request to merge the changes into the main repository.
Expected results:

The app will no longer crash when navigating to the /details page directly from the /expenses page.

**Comment by robertKozik** [comment] 2023-07-31 10:23
Hi! Thank you all for the proposals!

@AdeemWaseem I think you confused the issues as your proposal is not connected to the issue at all, also your comment does not follow the proposal template

@hoangzinh and @huzaifa-99  both of your proposals addressed the root cause of the problem correctly, as we are not listening to frequentlyUsedEmojis key at all. The solutions are also similar, so we would probably go with the faster proposal.

selected proposal: [Proposal](https://github.com/Expensify/App/issues/23800#issuecomment-1655976801)
author of proposal: @huzaifa-99 

🎀 👀 🎀 C+ reviewed

**Comment by robertKozik** [comment] 2023-07-31 11:56
Thank you for your insights. Indeed, I missed that there were only seconds between both proposals, but in such cases, we need to somehow choose between one and another.
I see your point, as I'm studying your RCA provides more insights on a problem but can be summed up to your last sentence there: When the frequentlyUsedEmojis is updated, we haven't had any logic to update states filteredEmojis and headerIndices yet, which is also stated in @huzaifa-99 RCA only without the specific methods/variables names.

In my eyes, your proposal is a more detailed version of the first one, so I'm not sure I can count this as a new proposal. But as we have now CME @puneetlath here, let's wait for his input on this.

@puneetlath, what do you think about this situation?

**Comment by puneetlath** [comment] 2023-07-31 19:42
Just catching up on the discussion, but I agree there's no clear answer and we have to make a decision in some way. @huzaifa-99 does have a more high-level proposal and @hoangzinh's is more detailed, but I think the concepts covered in the proposals are well-known, so the high-level proposal is enough to understand what will be done in this scenario. So I'm good with @robertKozik's decision to go with @huzaifa-99's proposal since it was first. 

Thanks for your contributions and proposals everyone!

**Comment by lschurr** [comment] 2023-08-21 23:29
Ah, yeah this looks like one where the automation didn't work correctly. Let me add the checklist.

**Comment by lschurr** [comment] 2023-08-21 23:31
@robertKozik could you work through the checklist to confirm whether we need a regression test here?

**Comment by lschurr** [comment] 2023-08-21 23:35
This should have been paid last week, so we can go ahead and issue payments.

Payment summary:

- Bug reporter: Applause - no payment
- Contributor: @hungvu193 $1500
- Contributor+: @robertKozik $1500

**Comment by lschurr** [comment] 2023-08-22 02:10
Ooops! Typed an h and let GH do it's thing. Fixing!

**Comment by lschurr** [comment] 2023-08-22 04:31
@robertKozik @huzaifa-99 - could you apply for the job? https://www.upwork.com/jobs/~017543882e0e6eca1f

**Comment by robertKozik** [comment] 2023-08-22 07:26
@lschurr Actually I'm from Software Mansion (expert agency) so I'm not eligible for payment

**Comment by robertKozik** [comment] 2023-08-22 07:58
> [@robertKozik] The PR that introduced the bug has been identified. Link to the PR: **I don't think that there is any one particular PR which introduced this**
 [@robertKozik] The offending PR has been commented on, pointing out the bug it caused and why, so the author and reviewers can learn from the mistake. Link to comment: **N/A**
 [@robertKozik] A discussion in #expensify-bugs has been started about whether any other steps should be taken (e.g. updating the PR review checklist) in order to catch this type of bug sooner. Link to discussion: **N/A**
 [@robertKozik] Determine if we should create a regression test for this bug. **I think it's worth to add the test for this as it can be often forgotten to test the interactions between two devices logged on the same account**
 [@robertKozik] If we decide to create a [regression test](https://github.com/Expensify/App/blob/main/contributingGuides/REGRESSION_TEST_BEST_PRACTICES.md) for the bug, please propose the regression test steps to ensure the same bug will not reach production again. **I propose to use the test case from the PR:**
> - **Log in to 2 devices with the same account (logout and then log in if you are already logged in)**
> - **In both devices, go to any chat and open the emoji picker**
> - **From device A select an emoji, and in device B verify the frequently used emojis change (the emoji you used most will be the first in the frequently used list - each emoji has a use counter)**
> - **Repeat step 3 but from device B and verify in device A - frequently used list should be updated correctly**

**Comment by lschurr** [comment] 2023-08-22 15:58
Great thanks @robertKozik - added a request for that regression test.

Sent offer in Upwork to @huzaifa-99

**Comment by lschurr** [comment] 2023-08-22 19:11
Payment sent to @huzaifa-99 in Upwork. Closing this one out :)

**Closed by lschurr** 2023-08-22 19:11 UTC
Labels: External, Daily, Awaiting Payment, Bug

**Comment by lanitochka17** [comment] 2023-09-05 21:23
Issue reproducible on Build 1.3.64-0

https://github.com/Expensify/App/assets/78819774/6811cdc7-0cfe-47a8-8dcf-67f5ac64eae8

Should I open a new issue or open this one?
