### ISSUE TITLE
[HOLD for payment 2024-06-20] [HOLD for payment 2024-06-18] [$500]  Distance - Distance request thumbnail is different in reports when created offline

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#37638] opened 2024-03-01 20:42 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.46-0
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** Applause - Internal Team
**Slack conversation:**

## Action Performed:
1. Go to staging.new.expensify.com
2. Go offline
3. Go to workspace chat
4. Create a distance request
5. Click on the expense preview
6. Click on the expense preview again

## Expected Result:
The receipt preview for the distance request should be consistent in the main chat, expense report and transaction thread

## Actual Result:
The receipt preview for the distance request is different in the main chat, expense report and transaction thread

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [x] Android: mWeb Chrome
- [x] iOS: Native
- [x] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details> 

https://github.com/Expensify/App/assets/78819774/578df682-6ffd-4460-8710-43177dd096e5

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01230fd2c4938cb72a</li>
        <li>Upwork Job ID: 1765104893993635840</li>
        <li>Last Price Increase: 2024-03-19</li>
<li>Automatic offers: </li>
<ul>
<li>mollfpr | Reviewer | 0</li>
<li>FitseTLT | Contributor | 0</li>
</ul></li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @garrettmknight</details>

**Comment by lanitochka17** [comment] 2024-03-01 20:43
@garrettmknight  FYI I haven't added the External label as I wasn't 100% sure about this issue. Please take a look and add the label if you agree it's a bug and can be handled by external contributors

**Comment by lanitochka17** [comment] 2024-03-01 20:44
We think that this bug might be related to #wave5
CC @dylanexpensify

**Comment by garrettmknight** [comment] 2024-03-05 19:59
Confirmed and added to a wave.

**Comment by shahinyan11** [comment] 2024-03-05 20:24
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
Distance - Distance request thumbnail is different in reports when created offline 
### What is the root cause of that problem?
We display another component [here](https://github.com/Expensify/App/blob/7a56d168d81ac015a694f3b50908a0b452779336/src/components/ReportActionItem/MoneyRequestPreview/MoneyRequestPreviewContent.tsx#L216C22-L216C36)
### What changes do you think we should make in order to solve the problem?
Add `&& !isOfline ` in [this](https://github.com/Expensify/App/blob/7a56d168d81ac015a694f3b50908a0b452779336/src/components/ReportActionItem/MoneyRequestPreview/MoneyRequestPreviewContent.tsx#L120) condition 

### What alternative solutions did you explore? (Optional)

**Comment by FitseTLT** [comment] 2024-03-05 20:29
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
Distance request thumbnail is different in reports when created offline

### What is the root cause of that problem?
We are using `ConfirmRoute` in money request preview and money request view
https://github.com/Expensify/App/blob/8262ebbb6dec7e6fa52073c7e09118ea2add4535/src/components/ReportActionItem/MoneyRequestPreview/MoneyRequestPreviewContent.tsx#L219-L220
https://github.com/Expensify/App/blob/8262ebbb6dec7e6fa52073c7e09118ea2add4535/src/components/ReportActionItem/MoneyRequestView.tsx#L257-L258
when the route is pending for a distance request and we do this to render the map same as in confirmation page instead of waiting until the server returns the map image and the default behaviour of this image when offline is to return `PendingMapView` which displays `EmptyStateRoutePending` Icon
### What changes do you think we should make in order to solve the problem?

To be consistent with ReportPreview as in here
https://github.com/Expensify/App/blob/8262ebbb6dec7e6fa52073c7e09118ea2add4535/src/components/ReportActionItem/ReportPreview.tsx#L266-L272
 we should display the `ReportActionItemImage` with the placeholder Receipt thumbnail instead of `ConfirmRoute` when we are offline as in that case the `ConfirmRoute` will display `EmptyStateRoutePending` icon that doesn't align with other pages
 https://github.com/Expensify/App/blob/8262ebbb6dec7e6fa52073c7e09118ea2add4535/src/components/ReportActionItem/MoneyRequestPreview/MoneyRequestPreviewContent.tsx#L121-L122
 https://github.com/Expensify/App/blob/8262ebbb6dec7e6fa52073c7e09118ea2add4535/src/components/ReportActionItem/MoneyRequestView.tsx#L114-L115
 ```
    const showMapAsImage = isDistanceRequest && hasPendingWaypoints && !isOffline;

```

### What alternative solutions did you explore? (Optional)

**Comment by garrettmknight** [comment] 2024-03-07 20:05
@mollfpr can you check these out?

**Comment by garrettmknight** [comment] 2024-03-11 11:56
Bumped in slack.

**Comment by shahinyan11** [comment] 2024-03-11 14:23
> @shahinyan11 I am talking about @FitseTLT's alternative solution.

Ok. Thanks for clarifying

**Comment by mollfpr** [comment] 2024-03-12 11:33
Thank you @shubham1206agra make this issue move along!

>The receipt preview for the distance request should be consistent in the main chat, expense report and transaction thread

@garrettmknight What image we should use Map pending image or the receipt generic image?

**Comment by garrettmknight** [comment] 2024-03-13 13:20
I think it should be the map pending image.

**Comment by mollfpr** [comment] 2024-03-14 03:31
Thanks @garrettmknight! I’m reviewing it now.

**Comment by garrettmknight** [comment] 2024-03-15 17:45
@mollfpr after reviewing, do we have an acceptable proposal?

**Comment by mollfpr** [comment] 2024-03-18 14:49
@rayane-djouah The solution might be working, but I don't think it's the correct solution. I'm looking to get align the thumbnail to use `ConfirmedRoute` instead the image when it's distance request.

@shahinyan11 I try your proposal but it's not working. It's showing nothing.

https://github.com/Expensify/App/assets/25520267/dba875cb-657e-4bfa-b78f-0b50df2953b1

@FitseTLT Could you detail your alternative solution? I try to create it by myself but I found the transaction data is not complete in `ReportActionItemImages`.

**Comment by FitseTLT** [comment] 2024-03-18 14:52
@mollfpr Will provide u a test branch 👍

**Comment by shahinyan11** [comment] 2024-03-18 15:20
@mollfpr Sorry . there is a spelling mistake. I mean the `isOffline` from `useNetwork`.
```
const {isOffline} = useNetwork();
```

**Comment by shahinyan11** [comment] 2024-03-18 15:23
## Proposal
[Updated](https://github.com/Expensify/App/issues/37638#issuecomment-1979577799). Fixed spelling error

**Comment by FitseTLT** [comment] 2024-03-20 12:11
@mollfpr here is a test [branch](https://github.com/FitseTLT/App/tree/fix-distance-request-thumbnail-mismatch)

**Comment by mollfpr** [comment] 2024-03-20 17:32
@shahinyan11 I think your proposal has the wrong result. It should be showing the map pending image instead of the receipt thumbnail.


https://github.com/Expensify/App/assets/25520267/4b4933bf-52ab-40f3-b267-dd76e80e7751

**Comment by mollfpr** [comment] 2024-03-20 17:37
I have tested the alternative solution from @FitseTLT and it's working well! The changes look good too. So I'm suggesting to go with their alternative proposal.

🎀 👀 🎀 C+ reviewed!

**Comment by shahinyan11** [comment] 2024-03-20 17:45
> @shahinyan11 I think your proposal has the wrong result. It should be showing the map pending image instead of the receipt thumbnail.

@mollfpr The expected result describes something else. I think my solution matches the expected result

**Comment by mollfpr** [comment] 2024-03-20 17:49
>The receipt preview for the distance request should be consistent in the main chat, expense report and transaction thread

The expected result is we need to make it consistent in 3 places and your result on the transaction thread is showing the map pending but the other page showing the thumbnail receipt.

I already clarified [here](https://github.com/Expensify/App/issues/37638#issuecomment-1994393035).

**Comment by chiragsalian** [comment] 2024-03-20 19:12
Proposal LGTM, feel free to create a PR @FitseTLT

**Comment by garrettmknight** [comment] 2024-03-22 19:04
@FitseTLT how's the PR coming?

**Comment by FitseTLT** [comment] 2024-03-22 19:05
PR will be ready for review beg of next week

**Comment by garrettmknight** [comment] 2024-04-23 18:05
Still working through the PR

**Comment by neil-marcellini** [comment] 2024-05-07 18:04
Chirag said I can take this over, so I will and I think we can get it merged in the next few days.

**Comment by neil-marcellini** [comment] 2024-05-21 19:39
We encountered various bugs in the PR and have had to determine if each is new or existing on main already. I'll set a reminder to review the PR again tomorrow, but we'll probably have to keep waiting for a bit due to the merge freeze.

**Comment by garrettmknight** [comment] 2024-06-20 17:30
**Payment Summary:**
- Contributor: @FitseTLT $250 paid via Upwork
- Reviewer: @mollfpr $250


@mollfpr can you finish the checklist when you get a chance?

**Comment by mollfpr** [comment] 2024-06-22 03:14
>[@mollfpr] The PR that introduced the bug has been identified. Link to the PR:
 [@mollfpr] The offending PR has been commented on, pointing out the bug it caused and why, so the author and reviewers can learn from the mistake. Link to comment:

Couldn't find the offending PR. We re-work the component to fix the issue and also replace the map pending thumbnail.

> [@mollfpr] A discussion in #expensify-bugs has been started about whether any other steps should be taken (e.g. updating the PR review checklist) in order to catch this type of bug sooner. Link to discussion:

No need to create a discussion on the channel, because it seems only a time bug.

> [@mollfpr] Determine if we should create a regression test for this bug.
 [@mollfpr] If we decide to create a regression test for the bug, please propose the [regression test](https://github.com/Expensify/App/blob/main/contributingGuides/REGRESSION_TEST_BEST_PRACTICES.md) steps to ensure the same bug will not reach production again.

1. Go to staging.new.expensify.com
2. Go offline
3. Go to workspace chat
4. Create a distance request
5. **Verify** on the report preview check that the pending map is displayed corresponding to the distance request created in (4) (instead of the receipt thumbnail)
6. Get back online and **verify** that the pending map is displayed (instead of the receipt thumbnail) until the map image from the server is returned
7. And once the map image is ready it should display the map image.
8. Create a distance request again
9. **Verify** on the report preview check a map is displayed corresponding to the distance request u created (instead of a receipt thumbnail)
10. 👍 or 👎

**Comment by JmillsExpensify** [comment] 2024-06-22 16:05
$500 approved for @mollfpr

**Comment by garrettmknight** [comment] 2024-06-24 19:31
All set here

**Closed by garrettmknight** 2024-06-24 19:31 UTC
Labels: External, Daily, Overdue, Awaiting Payment, Bug
