### ISSUE TITLE
 Search - The search result list does not display full.

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#53706] opened 2024-12-06 15:31 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 9.0.72-0
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**If this was caught on HybridApp, is this reproducible on New Expensify Standalone?:** N/A
**If this was caught during regression testing, add the test name, ID and link from TestRail:** Y
**Email or phone of affected tester (no customers):** spica8922@gmail.com
**Issue reported by:** Applause - Internal Team

## Action Performed:
1. Open the website https://staging.new.expensify.com/
2. Click on the search icon > sent
3. Set the date filter to after is None, before is today (27/11/2024)
4. Click the view result and scroll down to view the search result list (include Yesterday, Nov, and Otc month)
5. Change the date from 27 to 25 and view the result

## Expected Result:
The search result should display almost all messages of the results before 25/11 including Nov and Otc months

## Actual Result:
The search result list appears as 2 results for Nov month, when I try to scroll down and wait for loading but does not show more results

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Standalone
- [ ] Android: HybridApp
- [ ] Android: mWeb Chrome
- [ ] iOS: Standalone
- [ ] iOS: HybridApp
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

<details>
  <summary>Add any screenshot/video evidence</summary>

  
</details> 

https://github.com/user-attachments/assets/a09c68a7-bd19-46d5-a3a7-aa3cf12c7131

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by VictoriaExpensify** [comment] 2024-12-09 03:07
I haven't been able to reproduce this issue. I can't share my recording because the only account I have with enough chat history is my production account and that contains chats with customers.

But I tried reproducing by:
- Go to Search > Chats > Sent
- Set before date to today's date (9 Dec)
- Confirm I can see historical messages
- Set before date to two days prior (7 Dec)
- Confirm I can still see historical messages

**Comment by VictoriaExpensify** [comment] 2024-12-09 03:09
Asked QA to try and repro - https://expensify.slack.com/archives/C9YU7BX5M/p1733713757856799

**Comment by izarutskaya** [comment] 2024-12-09 14:28
Not reproduced for QA team


https://github.com/user-attachments/assets/103188bf-f4a9-476f-91ac-329f6d252fc7

**Comment by VictoriaExpensify** [comment] 2024-12-11 06:06
Closing as this is not longer producable

**Closed by VictoriaExpensify** 2024-12-11 06:06 UTC
Labels: Daily, Bug
