### ISSUE TITLE
[Awaiting payment] New Chat report is always created even after a chat report already exists

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#21184] opened 2023-06-21 10:50 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Click on the plus sign at the bottom of the screen.
2. Select "New Chat" and search for a new email.
3. Observe that the Concierge notification message appears in the new message.
4. Search for the same email again and enter it, and observe that the Concierge notification message disappears.

## Expected Result:
The Concierge notification should appear when we go to a new chat and when we search for the same email again.

## Actual Result:
The Concierge notification appears when we go to a new chat, but disappears when we search for the same email again.

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [x] MacOS / Chrome / Safari
- [x] MacOS / Desktop

**Version Number:** 1.3.30.0

**Reproducible in staging?:** yes

**Reproducible in production?:** no

**If this was caught during regression testing, add the test name, ID and link from TestRail:**

**Email or phone of affected tester (no customers):**

**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Notes/Photos/Videos:** Any additional supporting documentation

[screen-capture (33).webm](https://github.com/Expensify/App/assets/93399543/cbf48f31-f362-4d27-9d1d-9179cb56bdc9)

https://github.com/Expensify/App/assets/93399543/b157c0af-68ca-4680-a5c6-041de772efe3

**Expensify/Expensify Issue URL:**

**Issue reported by:** @tewodrosGirmaA

**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1687330135172719

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by mountiny** [comment] 2023-06-21 12:18
Cant get the concierge whisper message locally

**Comment by mountiny** [comment] 2023-06-21 14:04
Confirmed now that this issue seems to be related to Web changes, it works fine on main with production API and it breaks on main or staging API.

**Comment by mountiny** [comment] 2023-06-21 14:10
This is a response I am getting when creating the duplicate chat
```
{
    "jsonCode": 408,
    "title": "Session expired",
    "message": "The account you are trying to use is deleted.",
    "requestID": "U2NJcy",
    "onyxData": []
}
```

**Comment by mountiny** [comment] 2023-06-21 14:19
Alright so it seems like the issue is that staging and main API are only returning `accountID`, `displayName` and `avatar`

**Comment by luacmartins** [comment] 2023-06-22 00:53
I think this is fixed. Removing the blocker label.

**Comment by MonilBhavsar** [comment] 2023-07-03 13:56
This is fixed. Closing now

**Comment by tewodrosGirmaA** [comment] 2023-07-03 14:12
Hi@MonilBhavsar Am I eligible for payment?💰

**Comment by MonilBhavsar** [comment] 2023-07-03 15:20
Sorry, Yes, I think you're eligible for payment

**Comment by MonilBhavsar** [comment] 2023-07-03 15:20
@anmurali the issue is fixed internally and deployed.
Can we please pay @tewodrosGirmaA for reporting the issue. Thanks!

**Comment by tewodrosGirmaA** [comment] 2023-07-06 09:00
@anmurali , Hello , I think this is fixed 3 days ago internally

**Comment by MonilBhavsar** [comment] 2023-07-07 11:04
Awaiting payment here cc @anmurali

**Comment by tewodrosGirmaA** [comment] 2023-07-20 20:39
@anmurali @mountiny , still I didn't gate a payment

**Comment by anmurali** [comment] 2023-07-24 15:48
Offer is [here](https://www.upwork.com/nx/wm/offer/25721400)

**Comment by MonilBhavsar** [comment] 2023-07-31 13:08
@tewodrosGirmaA did you accept the offer?

**Comment by tewodrosGirmaA** [comment] 2023-07-31 13:24
Hello,@MonilBhavsar, yes , I accepted the offer , Thank you

**Comment by MonilBhavsar** [comment] 2023-08-01 06:20
Thanks! So we can close this one

**Closed by MonilBhavsar** 2023-08-01 06:20 UTC
Labels: Engineering, Daily, Awaiting Payment, Bug
