### ISSUE TITLE
[HOLD for payment 2023-06-13] [$2000] Fix auto-suggestion animation on Android

### ISSUE THREAD

**Issue by puneetlath** [Expensify/App#18974] opened 2023-05-15 19:41 UTC
The fix to the deploy blocker here broke animations for the auto-suggestion component on Android. 

@Pujan92 reported this issue and suggested [this fix](https://github.com/Expensify/App/issues/18793#issuecomment-1548411840). 
<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01dca0ae0bdca5d804</li>
        <li>Upwork Job ID: 1658195904748879872</li>
        <li>Last Price Increase: 2023-05-25</li>
    </ul>
</details>

**Comment by s77rt** [comment] 2023-05-15 20:25
@puneetlath Did you link the correct comment? I don't see any proposal :sweat_smile:

**Comment by Pujan92** [comment] 2023-05-15 20:28
@s77rt It was my fault as I deleted it bcoz it wasn't solving the app crash issue. https://github.com/Expensify/App/pull/18842#issuecomment-1548485024

**Comment by s77rt** [comment] 2023-05-15 20:32
@Pujan92 That's a fine of $5000 :grin:.

**Comment by s77rt** [comment] 2023-05-21 22:52
@allroundexperts Thanks for the proposal. Can you please explain the problem that we are trying to solve :sweat_smile:? The animation on Android seems to same as Web. Am I missing something?

**Comment by s77rt** [comment] 2023-05-22 10:38
@allroundexperts Thanks! That makes sense but the animations looks wrong. The whole view is moving when the suggestion list changes from displaying one item to displaying multiples. Check the video below and observe how the view get reset and starts the bottom.


https://github.com/Expensify/App/assets/16493223/88271285-6a8b-4d0c-b20e-0b82e7ef315e

**Comment by s77rt** [comment] 2023-05-22 11:22
@allroundexperts I'm not totally sure how should this be animated but probably not as it's now. It feels broken.

**Comment by puneetlath** [comment] 2023-05-22 19:29
Shawn is off this week, but I would think it should be similar to Slack/Discord where the Modal appears to be open the whole time, but animates to change size as things are typed.

**Comment by s77rt** [comment] 2023-05-24 23:52
Not overdue. Waiting for proposals...

**Comment by aswin-s** [comment] 2023-05-26 05:08
## Proposal

### Please re-state the problem that we are trying to solve in this issue.

Add animation for emoji & mention suggestions popup


### What is the root cause of that problem?

Previous animation using LayoutAnimation was breaking on Android device. So an alternative approach using `react-native-reanimated` is being pursued.



### What changes do you think we should make in order to solve the problem?


Implement a spring animation using react-native-reanimated to animate the suggestion popup height when suggestion changes.

Apply below changes to  [BaseAutoCompleteSuggestions.js
](https://github.com/Expensify/App/blob/main/src/components/AutoCompleteSuggestions/BaseAutoCompleteSuggestions.js)

1. Convert rowHeight to a shared variable

```tsx
const rowHeight = useSharedValue(0);
```

2. Modify rowHeight value in an effect, whenever suggestion length changes

```tsx
    useEffect(() => {
        rowHeight.value = withSpring(measureHeightOfSuggestionRows(props.suggestions.length, props.isSuggestionPickerLarge), {
            damping: 15,
            stiffness: 150,
        });
    }, [props.suggestions.length, props.isSuggestionPickerLarge, rowHeight]);
```

4. Compute animated styles for popup using useAnimatedStyles hook from reanimated

```tsx
    const animatedStyles = useAnimatedStyle(() => ({
        ...styles.autoCompleteSuggestionsContainer,
        ...StyleUtils.getAutoCompleteSuggestionContainerStyle(rowHeight.value, props.shouldIncludeReportRecipientLocalTimeHeight),
    }));
```

6. Finally replace View with `Animated.View` and apply the animated styles.

```tsx
    return (
        <Animated.View
            ref={props.forwardedRef}
            style={animatedStyles}
        >
            <FlatList
                keyboardShouldPersistTaps="handled"
                data={props.suggestions}
                renderItem={renderSuggestionMenuItem}
                keyExtractor={props.keyExtractor}
                removeClippedSubviews={false}
                style={{flex: 1}}
            />
        </Animated.View>
    );
```
7. The StyleUtilfunction `getAutoCompleteSuggestionContainerStyle` should be marked as a worklet to enable it to be executed from UI thread.

```tsx
function getAutoCompleteSuggestionContainerStyle(itemsHeight, shouldIncludeReportRecipientLocalTimeHeight) {
    'worklet';

    const optionalPadding = shouldIncludeReportRecipientLocalTimeHeight ? CONST.RECIPIENT_LOCAL_TIME_HEIGHT : 0;
    const padding = CONST.AUTO_COMPLETE_SUGGESTER.SUGGESTER_PADDING - optionalPadding;
    ...
}
```

Result 

**Android**

https://github.com/Expensify/App/assets/6880914/f9ddcf76-45da-444c-b201-6f633b41f220


**iOS**

https://github.com/Expensify/App/assets/6880914/1d45ca34-6a33-4cae-82a3-5bd641f44c18



**Web**

https://github.com/Expensify/App/assets/6880914/c1d0798e-912d-4c64-8933-9cc38e8e050b


### What alternative solutions did you explore? (Optional)

None

**Comment by s77rt** [comment] 2023-05-26 16:05
@aswin-s Thanks for the proposal. I wonder if you missed something :sweat_smile:. Your proposal looks similar to @allroundexperts's and I can reproduce the same unwanted behaviour i.e. the suggestion list appears from the bottom.


https://github.com/Expensify/App/assets/16493223/c6a8ed41-dcf2-474c-a218-987cdf0a1d28

**Comment by aswin-s** [comment] 2023-05-26 16:41
@s77rt Ah! my bad 😓 . I was working on top of [this PR](https://github.com/Expensify/App/pull/19621) which fixes another issue with suggestions popup. So I missed a couple of lines in the diff. That's why the unwanted behaviour is not seen in the videos shared.  I've updated my proposal now.

Changed bits.

1. Inline style for FlatList now uses `flex:1` so that it fills the animating parent container.
2. `getAutoCompleteSuggestionContainerStyle` now adds `height:itemHeight` in the returned style, so that the parent view height changes with spring animation.

**Comment by s77rt** [comment] 2023-05-26 21:30
@aswin-s Awesome! I'm not sure what type of animation we should use here (spring or other) but the proposal looks good to me.

:ribbon: :eyes: :ribbon: C+ reviewed

@puneetlath Let's hold for https://github.com/Expensify/App/pull/19621 then we can go with @aswin-s's proposal.

**Comment by puneetlath** [comment] 2023-05-27 04:23
Nice! Looks good. Though I agree, I don't think spring is the right animation. I don't think we want it to bounce and it feels slow in the video. What other options do we have?

**Comment by s77rt** [comment] 2023-05-29 12:03
Not overdue.

@aswin-s Any updates on the above ^ (animations options). It would be super helpful if you can compile some basic animations to choose from and discuss with the design team (please open a slack discussion for that).

**Comment by s77rt** [comment] 2023-05-29 21:18
Pretty close in getting this done

**Comment by aswin-s** [comment] 2023-05-30 03:42
Here is a version which uses timing animation. I've also reduced animation duration to 100ms, so that it feels faster. 

[animation4.webm](https://github.com/Expensify/App/assets/6880914/a1c98dae-e49a-41eb-bbae-eab37f3c9e0d)

**Comment by shawnborton** [comment] 2023-05-30 06:47
Do we use an animation for this menu on other platforms?

**Comment by shawnborton** [comment] 2023-05-30 16:37
Cool, as long as they feel like the same animation?

**Comment by aswin-s** [comment] 2023-05-30 17:10
@shawnborton Above proposal applies same animation on all three platforms (Web, iOS and Android). Here's a preview. 

https://github.com/Expensify/App/assets/6880914/08bed050-b80c-4809-9643-bf0da60e31c0

@s77rt @puneetlath [Related PR ](https://github.com/Expensify/App/pull/19621) is now merged to master.

**Comment by puneetlath** [comment] 2023-05-30 17:50
@shawnborton my understanding is that: 
1. right now we have animation on all platforms, but it doesn't work on android
2. If we were to replace with reanimated using @aswin-s solution, it would replace the animation on all platforms

**Comment by shawnborton** [comment] 2023-05-30 18:16
Okay cool, that works for me!

**Comment by shawnborton** [comment] 2023-05-30 18:17
What is the exact easing function we're using for the animation?

**Comment by aswin-s** [comment] 2023-05-31 02:24
What we've tried already is `Spring` animation and `easeOutCubic`. Here is a couple more.

**Spring** (stiffness: 500, damping: 40) 

https://github.com/Expensify/App/assets/6880914/3b6c0b9c-3cf8-409f-a939-d748153a765a

**easeOut**


https://github.com/Expensify/App/assets/6880914/54c1e6f3-34cc-47a4-8d76-54e771b9e4e4


**easeOutCubic**


https://github.com/Expensify/App/assets/6880914/a3cf69a6-abed-4bda-9c95-8b428fdd89be


**easeOutQuad**


https://github.com/Expensify/App/assets/6880914/fae9a496-d326-4971-b86a-4dabb7943c97


Animation duration has been set to 100ms so that it doesn't feel laggy. I think `easeOutCubic` or `easeOutQuad` feels better compared to others. Let me know if you would like to see any other variants or tweak the duration of animations.

**Comment by shawnborton** [comment] 2023-05-31 07:28
Do you have something like `easeInOut` to try as well? Otherwise I am digging `easeOutCubic`

**Comment by aswin-s** [comment] 2023-05-31 07:48
Here is `easeInOut`. 

https://github.com/Expensify/App/assets/6880914/e2ef5c0f-64d2-494b-9e82-2f6449bb36c9

**Comment by shawnborton** [comment] 2023-05-31 07:53
Nice, I think I like that the most. Thoughts?

**Comment by puneetlath** [comment] 2023-05-31 17:45
I like it too. @aswin-s let's do it 💪🏾

**Comment by aswin-s** [comment] 2023-06-01 03:34
[PR](https://github.com/Expensify/App/pull/19933) is ready for review.

**Comment by s77rt** [comment] 2023-06-06 22:35
- The PR that introduced the bug has been identified: https://github.com/Expensify/App/pull/18842
- The offending PR has been commented on: This was known already https://github.com/Expensify/App/pull/18842#issuecomment-1546638129
- A discussion in #expensify-bugs has been started: https://expensify.slack.com/archives/C049HHMV9SM/p1686090898635459
- Determine if we should create a regression test for this bug: No

**Comment by puneetlath** [comment] 2023-06-08 21:16
Upwork contracts sent. Checklist looks good to me. 

@michaelhaxhiu re-assigning to you for payment while I'm OOO next week.

**Comment by michaelhaxhiu** [comment] 2023-06-12 20:08
tomorrow is payday

**Comment by michaelhaxhiu** [comment] 2023-06-15 20:10
No speed bonus here

**Comment by michaelhaxhiu** [comment] 2023-06-15 20:20
all parties paid.

**Closed by michaelhaxhiu** 2023-06-15 20:20 UTC
Labels: External, Daily, Awaiting Payment, Bug
