### ISSUE TITLE
DEV - Language at Login page changes to English for a while, before becoming Spanish.

### ISSUE THREAD

**Issue by kavimuru** [Expensify/App#14253] opened 2023-01-12 21:52 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:

1. Open the web page, at the Login page, make sure you are at English setting.
2. Change the language to Spanish by clicking at the bottom dropdown.
3. Enter the validate email, press Enter, now Click on ¿Te has olvidado?, Click Vovler to go back Login page.
4. Notice that the language at Login page changes to English for a while before becoming Spanish.

## Expected Result:
The language should be Spanish at Login page.

## Actual Result:
The language at Login page changes to English for a while before becoming Spanish

## Workaround:
unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?

- [ ] MacOS / Chrome 

**Version Number:** v1.2.52-4
**Reproducible in staging?:** Occurs only in Dev
**Reproducible in production?:** Occurs only in Dev
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** 

https://user-images.githubusercontent.com/43996225/212188893-0685df81-061b-455c-b2ea-4d4ab02219c6.mov

**Expensify/Expensify Issue URL:**
**Issue reported by:** @hungvu193 
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1673508484626659

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by stephanieelliott** [comment] 2023-01-19 17:07
Issue is occurring in Dev, so I don't have the ability to try and reproduce. @hungvu193 are you seeing this occur consistently/are you able to repro it?

**Comment by luacmartins** [comment] 2023-01-20 22:09
@stephanieelliott this issue is locked to @hungvu193 won't be able to comment here.

I'm gonna close this issue since I'm unable to reproduce in dev and this issue wouldn't affect customers. Feel free to reopen if needed!

https://user-images.githubusercontent.com/22219519/213813803-af271fde-3772-402d-bf5a-afe0b63c5bd6.mov

**Closed by luacmartins** 2023-01-20 22:09 UTC
Labels: Daily, Needs Reproduction, Bug
