### ISSUE TITLE
[HOLD for payment 2024-06-06] [$250] Send invoice - Workspace switcher is reset to "Expensify" when sending invoice to the same WS

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#41575] opened 2024-05-03 13:46 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.70-0
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**If this was caught during regression testing, add the test name, ID and link from TestRail:** N/A
**Issue reported by:** Applause - Internal Team

## Action Performed:
1. Go to staging.new.expensify.com
2. Open workspace switcher
3. Select a workspace
4. Go to FAB > Send invoice
5. Enter amount and select participant
6. On confirmation page, select the same workspace in Step 3
7. Create the invoice

## Expected Result:
Workspace switcher should remain unchanged when sending the invoice to the same workspace

## Actual Result:
Workspace switcher is reset to "Expensify" when sending the invoice to the same workspace

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [x] Android: mWeb Chrome
- [x] iOS: Native
- [x] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details> 

https://github.com/Expensify/App/assets/78819774/d7e185b6-05cd-42a5-b1fa-31096cfc551e

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01038e8ff26d237540</li>
        <li>Upwork Job ID: 1787748015120437248</li>
        <li>Last Price Increase: 2024-05-14</li>
<li>Automatic offers: </li>
<ul>
<li>bernhardoj | Contributor | 0</li>
</ul></li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @laurenreidexpensify</details>

**Comment by bernhardoj** [comment] 2024-05-03 14:24
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
Workspace switcher is switched to Expensify when creating a new send invoice.

### What is the root cause of that problem?
When we complete the send invoice, it will call `dismissModal`.
https://github.com/Expensify/App/blob/da2cd90b594b92be06de29942e8d4f47a3f69c25/src/libs/actions/IOU.ts#L3379

`dismissModal` will call `dismissModalWithReport` if there is a reportID from `dismissModal` and decide whether to switch to the "Expensify" (all workspace).
https://github.com/Expensify/App/blob/da2cd90b594b92be06de29942e8d4f47a3f69c25/src/libs/Navigation/dismissModalWithReport.ts#L51

In `doesReportBelongToWorkspace`, it will compare the report `policyID` with the workspace `policyID`, but if `policyID` isn't available, it will compare the participants.
https://github.com/Expensify/App/blob/da2cd90b594b92be06de29942e8d4f47a3f69c25/src/libs/ReportUtils.ts#L1048

However, when we complete the send invoice, the report data is not available yet (not merged to the onyx yet). So, `doesReportBelongToWorkspace` will always return false.

### What changes do you think we should make in order to solve the problem?

Replace `Navigation.dismissModal` with `Navigation.dismissModalWithReport`.
https://github.com/Expensify/App/blob/da2cd90b594b92be06de29942e8d4f47a3f69c25/src/libs/actions/IOU.ts#L3379

Then, we pass the invoice room report instead of the ID. We need to return the report object from `getSendInvoiceInformation`

**Comment by laurenreidexpensify** [comment] 2024-05-13 09:36
@allroundexperts bump for review pls

**Comment by allroundexperts** [comment] 2024-05-14 17:49
Thanks for the proposals everyone. I don't see any issue with @bernhardoj's [proposal](https://github.com/Expensify/App/issues/41575#issuecomment-2093129242). @dragnoir's [proposal](https://github.com/Expensify/App/issues/41575#issuecomment-2097024998) seems a little risky to me. Since @bernhardoj proposed first, let's go with them.

🎀 👀 🎀 C+ reviewed

**Comment by allroundexperts** [comment] 2024-05-14 18:16
@dragnoir Did you do the following?

> Then, we pass the invoice room report instead of the ID. We need to return the report object from getSendInvoiceInformation

**Comment by bernhardoj** [comment] 2024-05-15 04:03
You can test it [here](https://github.com/bernhardoj/Expensify/tree/fix/41575-send-invoice-reset-workspace-switcher)

**Comment by bernhardoj** [comment] 2024-05-15 14:30
PR is ready

cc: @allroundexperts

**Comment by laurenreidexpensify** [comment] 2024-06-07 12:01
Payment Summary 

c+ $250 - @allroundexperts requires payment through NewDot Manual Requests
contributor @bernhardoj requires payment in upwrok (site currently being unstable will try again later)

**Comment by laurenreidexpensify** [comment] 2024-06-07 12:02
@allroundexperts pls complete checklist thanks

**Comment by laurenreidexpensify** [comment] 2024-06-10 10:43
Payment Summary

c+ $250 - @allroundexperts requires payment through NewDot Manual Requests
contributor $250 @bernhardoj paid in upwork

**Closed** 2024-06-13 10:24 UTC
Labels: External, Daily, Overdue, Awaiting Payment, Bug

**Comment by JmillsExpensify** [comment] 2024-07-09 22:57
$250 approved for @allroundexperts
