### ISSUE TITLE
[HOLD for payment 2023-07-24] [$1000] Deep link to Profile Page is not opening in the installed app

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#21969] opened 2023-06-30 17:46 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Navigate to Settings > Share Code > Copy URL
2. Paste the link in another app. ( Slack, Notes or Messages)
3. Try to open the link by tapping on it

## Expected Result:
 Profile page should get opened in the installed app (iOS & Android)

## Actual Result:
The link gets opened in mobile browser (Safari / Chrome)

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android / native
- [ ] Android / Chrome
- [x] iOS / native
- [ ] iOS / Safari
- [ ] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:**  1.3.32-5
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/93399543/dd72c933-7e30-4881-b802-6646c716931c

**Expensify/Expensify Issue URL:**
**Issue reported by:** @aswin-s
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1687876003386849

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~0143c4c287988aa719</li>
        <li>Upwork Job ID: 1676019935665750016</li>
        <li>Last Price Increase: 2023-07-04</li>
    </ul>
</details>

**Comment by aswin-s** [comment] 2023-06-30 17:48
## Proposal

### Please re-state the problem that we are trying to solve in this issue.

Deep link to profile page is not working on iOS & Android

### What is the root cause of that problem?

Profile page URL is of the format ‘/a/:accountID’. This URL prefix is not added to apple-app-site-association file and AndroidManifest. That’s the reason this URL is not recognized as a universal link by the app.

### What changes do you think we should make in order to solve the problem?

Add ‘/a’ URL prefix to both apple-app-site-association file and AndroidManifest.xml

*iOS*
https://github.com/Expensify/App/blob/main/.well-known/apple-app-site-association#L10
 { "/": "/a/*", "comment": "Profile Page" }, 

*Android*

Add below lines to AndroidManifest.xml https://github.com/Expensify/App/blob/main/android/app/src/main/AndroidManifest.xml#L57
 <data android:scheme="https" android:host="new.expensify.com" android:pathPrefix="/a"/> 
https://github.com/Expensify/App/blob/main/android/app/src/main/AndroidManifest.xml#L68
 <data android:scheme="https" android:host="staging.new.expensify.com" android:pathPrefix="/a"/> 

### What alternative solutions did you explore? (Optional)

None

**Comment by michaelhaxhiu** [comment] 2023-07-04 00:08
Agree with expected result 👍

**Comment by eVoloshchak** [comment] 2023-07-05 15:45
@aswin-s's [proposal](https://github.com/Expensify/App/issues/21969#issuecomment-1614981895) looks good to me, looks like this was simply missed during the initial implementation of `share profile link` flow

🎀👀🎀 C+ reviewed!

**Comment by aswin-s** [comment] 2023-07-07 03:47
@michaelhaxhiu @eVoloshchak This issue is not yet assigned to me. Is there another review pending?

**Comment by eVoloshchak** [comment] 2023-07-10 22:38
@michaelhaxhiu, @aswin-s's [proposal](https://github.com/Expensify/App/issues/21969#issuecomment-1614981895) looks good to me, could you take a look and assign @aswin-s to this issue if you agree?

**Comment by michaelhaxhiu** [comment] 2023-07-10 23:20
Sorry for blocking this, it's a new process for BZ to assign the contributor and I am a little behind.

**Comment by aswin-s** [comment] 2023-07-11 02:28
Contributor details
Your Expensify account email: mr.aswin@gmail.com
Upwork Profile Link: https://www.upwork.com/freelancers/~010b194c3e145d5456

**Comment by michaelhaxhiu** [comment] 2023-07-18 20:57
Nice, this will be due for payment in about 1 week. Next is the checklist above 🤙

**Comment by eVoloshchak** [comment] 2023-07-26 18:14
- The PR that introduced the bug has been identified. Link to the PR: https://github.com/Expensify/App/pull/20144
- The offending PR has been commented on, pointing out the bug it caused and why, so the author and reviewers can learn from the mistake. Link to comment: https://github.com/Expensify/App/pull/20144/files#r1275320393
- A discussion in #expensify-bugs has been started about whether any other steps should be taken (e.g. updating the PR review checklist) in order to catch this type of bug sooner. Link to discussion: https://expensify.slack.com/archives/C049HHMV9SM/p1690395182200269
- Determine if we should create a regression test for this bug.
Is it easy to test for this bug? Yes
Is the bug related to an important user flow? Yes
Is it an impactful bug? Yes

**Comment by eVoloshchak** [comment] 2023-07-26 18:16
**Regression Test Proposal**

1. Have an IOS or Android device with the native app installed
2. Navigate to Settings > Share Code > Copy URL
3. Paste the link in another app. ( Slack, Notes or Messages)
4. Try to open the link by tapping on it
5. Verify that profile page is opened in the installed app

**Do we agree 👍 or 👎**

**Comment by eVoloshchak** [comment] 2023-07-26 18:17
Requested the payment for this via NewDot

**Comment by michaelhaxhiu** [comment] 2023-07-26 19:20
Payouts:

- [ ] @aswin-s External issue reporter - $250
- [ ] @aswin-s Contributor that fixed the issue - $1500
- [ ] @eVoloshchak Contributor+ that helped on the issue and/or PR - $1500

**Comment by michaelhaxhiu** [comment] 2023-07-26 19:34
@aswin-s drop me a comment here when you've accepted the upwork job invite

**Comment by michaelhaxhiu** [comment] 2023-07-26 19:36
QA test is added here - https://github.com/Expensify/Expensify/issues/303310

**Comment by aswin-s** [comment] 2023-07-26 19:36
@michaelhaxhiu Accepted the offer

**Closed** 2023-07-26 19:44 UTC
Labels: External, Daily, Awaiting Payment, Bug

**Comment by JmillsExpensify** [comment] 2023-07-27 04:04
Reviewed details for @eVoloshchak. This is accurate and approved for payment in NewDot.
