### ISSUE TITLE
[HOLD for C+ payment via newdot] [HOLD Same root cause as #16923] [$2000] Hover background is stuck if we remove all reaction from message

### ISSUE THREAD

**Issue by kavimuru** [Expensify/App#18555] opened 2023-05-07 17:41 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:

1. Open the app
2. Open any report
3. On older message (preferably message before 2-3 latest messages), react with emote
4. Click on reacted emoji below message to remove it and observe that background color is stuck for that message

## Expected Result: 
App should remove hover background color from message if we hover out of that message
## Actual Result: 
Hover background color is stuck when we remove all reacted emojis from message

## Workaround:
Can the user still use Expensify without this being fixed? Have you informed them of the workaround?

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [x] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 1.3.11.2
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation

https://user-images.githubusercontent.com/43996225/236693575-ae14c71b-ed4c-405b-ba0a-db378fd4d2fa.mp4

https://user-images.githubusercontent.com/43996225/236693631-01b50de9-b0f3-4c94-85bf-a0f2fbd8cbd9.mp4

**Expensify/Expensify Issue URL:**
**Issue reported by:** @dhanashree-sawant
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1683367237994489

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~019548eceb851e8301</li>
        <li>Upwork Job ID: 1656396922593226752</li>
        <li>Last Price Increase: 2023-05-31</li>
    </ul>
</details>

**Comment by marcaaron** [comment] 2023-05-15 21:41
Looks like we are still waiting for proposals. @allroundexperts if you proposal would fix this then feel free to add it here so @thesahindia can review it.

**Comment by marcaaron** [comment] 2023-05-18 22:01
@thesahindia can you please engage with @allroundexperts and summarize how we should move forward on this one?

**Comment by kadiealexander** [comment] 2023-05-21 23:27
Thanks for the summary @thesahindia, have placed on hold.

**Comment by marcaaron** [comment] 2023-05-22 21:19
@thesahindia sounds great, thanks!

**Comment by s-alves10** [comment] 2023-05-23 18:58
As discussed here in [slack](https://expensify.slack.com/archives/C01GTK53T8Q/p1684188764288459), I think context isn't a good option for managing hovered elements. So I suggest to use parent state and keep `Hoverable` component simple.

**Comment by s-alves10** [comment] 2023-05-24 18:13
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
Two report action context menus are displayed at the same time.

### What is the root cause of that problem?

The root cause of this issue is the same as of issue 16923 [here](https://github.com/Expensify/App/issues/16923#issuecomment-1543676311)
The main reason: `mouseleave` event isn't fired when the element under cursor is removed. That's why the above scenario works as below.

### What changes do you think we should make in order to solve the problem?

We can solve the issue by managing the hovered state of `ReportActionItem` components in its parent: `ReportActionList`.

1. Add the state to the `ReportActionList` component here
https://github.com/Expensify/App/blob/52cacf603ad3389959fef0872efffefdbc648c80/src/pages/home/report/ReportActionsList.js#L87

```
     const [hoveredAction, setHoveredAction] = useState(null);
```

2. Add the following props here under line 135.
https://github.com/Expensify/App/blob/52cacf603ad3389959fef0872efffefdbc648c80/src/pages/home/report/ReportActionsList.js#L124-L136

```
    onHoverIn={() => {
        setHoveredAction(reportAction.reportActionID);
    }}
    onHoverOut={() => {
        if (hoveredAction && hoveredAction === reportAction.reportActionID) {
            setHoveredAction(null);
        }
    }}
    hovered={reportAction.reportActionID === hoveredAction}
```

And add `hoveredAction` to the dependency here
https://github.com/Expensify/App/blob/52cacf603ad3389959fef0872efffefdbc648c80/src/pages/home/report/ReportActionsList.js#L139

3. Add the following props to `ReportActionItem` component.
```
    /** hover callbacks */
    onHoverIn: PropTypes.func,
    onHoverOut: PropTypes.func,

    /** hovered state */
    hovered: PropTypes.bool,
```

4. Add the following changes here
https://github.com/Expensify/App/blob/52cacf603ad3389959fef0872efffefdbc648c80/src/pages/home/report/ReportActionItem.js#L366-L419

- Replace the first line with
```
            <Hoverable onHoverIn={props.onHoverIn} onHoverOut={props.onHoverOut}>
```

- Convert the function-type children of `Hoverable` component to regular component and replace hovered with `props.hovered` like below.
```
                <View accessibilityLabel={props.translate('accessibilityHints.chatMessage')}>
                    {props.shouldDisplayNewMarker && <UnreadActionIndicator reportActionID={props.action.reportActionID} />}
                    <MiniReportActionContextMenu
                        reportID={props.report.reportID}
                        reportAction={props.action}
                        isArchivedRoom={ReportUtils.isArchivedRoom(props.report)}
                        displayAsGroup={props.displayAsGroup}
                        isVisible={props.hovered && !props.draftMessage && !hasErrors}
                        draftMessage={props.draftMessage}
                        isChronosReport={ReportUtils.chatIncludesChronos(props.report)}
                    />
                    <View
                        style={StyleUtils.getReportActionItemStyle(
                            props.hovered || isWhisper || isContextMenuActive || props.draftMessage,
                            (props.network.isOffline && props.action.isLoading) || props.action.error,
                        )}
                    >
                        <OfflineWithFeedback
                            onClose={() => ReportActions.clearReportActionErrors(props.report.reportID, props.action)}
                            pendingAction={props.draftMessage ? null : props.action.pendingAction}
                            errors={props.action.errors}
                            errorRowStyles={[styles.ml10, styles.mr2]}
                            needsOffscreenAlphaCompositing={ReportActionsUtils.isMoneyRequestAction(props.action)}
                        >
                            {isWhisper && (
                                <View style={[styles.flexRow, styles.pl5, styles.pt2]}>
                                    <View style={[styles.pl6, styles.mr3]}>
                                        <Icon
                                            src={Expensicons.Eye}
                                            small
                                        />
                                    </View>
                                    <Text style={[styles.chatItemMessageHeaderTimestamp]}>
                                        {props.translate('reportActionContextMenu.onlyVisible')}
                                        &nbsp;
                                    </Text>
                                    <DisplayNames
                                        fullTitle={ReportUtils.getWhisperDisplayNames(whisperedTo)}
                                        displayNamesWithTooltips={displayNamesWithTooltips}
                                        tooltipEnabled
                                        numberOfLines={1}
                                        textStyles={[styles.chatItemMessageHeaderTimestamp]}
                                        shouldUseFullTitle={isWhisperOnlyVisibleByUser}
                                    />
                                </View>
                            )}
                            {renderReportActionItem(props.hovered, isWhisper)}
                        </OfflineWithFeedback>
                    </View>
                </View>
```

5. Add hovered props here
https://github.com/Expensify/App/blob/52cacf603ad3389959fef0872efffefdbc648c80/src/pages/home/report/ReportActionItem.js#L463
```
            prevProps.translate === nextProps.translate &&
            prevProps.hovered === nextProps.hovered,
```

6. Update the code here to call hover callbacks always.
https://github.com/Expensify/App/blob/52cacf603ad3389959fef0872efffefdbc648c80/src/components/Hoverable/index.js#L47-L49
```
        if (isHovered !== this.state.isHovered && !(isHovered && this.hoverDisabled)) {
            this.setState({isHovered});
        }

        if (isHovered && this.props.onHoverIn) {
            this.props.onHoverIn();
        } else if (!isHovered && this.props.onHoverOut) {
            this.props.onHoverOut();
        }
```

These fixes solved the issue perfectly.

<details>
    <summary>Result</summary>

https://github.com/Expensify/App/assets/126839717/51e31d31-6fdc-43a3-a538-ed56e7c633a3


</details>


### What alternative solutions did you explore? (Optional)
Another solution of this issue is to remove the reactions from `hoverable` wrapper. Then when we remove the reaction items, corresponding reportActionItem won't be hovered.

**Comment by kadiealexander** [comment] 2023-05-29 22:59
Not overdue!

**Comment by s-alves10** [comment] 2023-05-31 02:41
@parasharrajat 
Yes, my solution isn't able to fix the root cause. We need to use Javascript to imitate `hover`, but it looks impossible as long as we use `mouseenter` and `mouseleave`.

Anyway, my proposed solution is so flexible that we can control the hovered state as we want to

**Comment by wildan-m** [comment] 2023-06-02 01:02
## Proposal

### Please re-state the problem that we are trying to solve in this issue.

When sending text and image together, chat actions are displayed with both messages

### What is the root cause of that problem?

`onMouseLeave` event is not always triggered if we move the mouse fast or the DOM is dynamically added, especially if the hover event is inside an expensive tree.

Proof:

https://user-images.githubusercontent.com/11847279/230703132-6cf077ac-d79c-4be5-bdec-90b3cbe0099a.mp4


Proof link:
https://codesandbox.io/s/cool-grass-xm7v16?file=/src/App.js

### What changes do you think we should make in order to solve the problem?

In our [Hoverable](https://github.com/Expensify/App/blob/main/src/components/Hoverable/index.js) component, we add a `mouseover` event listener to the document object and check if the `mouseover` event target is contained by one of our elements. If not currently hovered and element contains event target, set isHovered true, and if currently hovered and the element does not contain event target, set isHovered false.

```
 checkHover = e => {
        if (this.wrapperView) {
          const { isHovered } = this.state;
          const mouseOver = this.wrapperView.contains(e.target);
          if (!isHovered && mouseOver) {
            this.setIsHovered(true);
          }
    
          if (isHovered && !mouseOver) {
            this.setIsHovered(false);
          }
        }
    };
```





### What alternative solutions did you explore? (Optional)
N/A

**Comment by s-alves10** [comment] 2023-06-02 05:53
## Proposal
[Updated](https://github.com/Expensify/App/issues/18555#issuecomment-1561722967)

New proposal tries to solve a root cause of the issue

**Comment by s-alves10** [comment] 2023-06-05 03:19
@parasharrajat 
`MousePositionProvider` simply listens the events `mousemove`, `mouseleave`, `touchmove`, `touchend` and stores the appropriate coordinates. 

> calling this.wrapperView.getBoundingClientRect() in componentDidUpdate is expensive.
Yes. we might need to reduce the cases that `getBoundingClientRect` is called.

**Comment by wildan-m** [comment] 2023-06-05 03:44
[Proposal Updated](https://github.com/Expensify/App/issues/18555#issuecomment-1572976974)

@parasharrajat sorry for the confusion, I've rephrased it and hope I explained it better.

**Comment by s-alves10** [comment] 2023-06-05 05:07
> How is it different from what we have in Hoverable?

@parasharrajat 
Those are for tracking mouse position and attached to `document`, not to specific element

**Comment by s-alves10** [comment] 2023-06-05 07:31
@parasharrajat 
Shall I share the code?

**Comment by aldo-expensify** [comment] 2023-06-05 18:16
👋 I think there is another form of this bug here:

https://user-images.githubusercontent.com/43996225/229311464-3186d02c-7383-4f86-ac47-037c6a8f29af.mp4

Coming from: https://github.com/Expensify/App/issues/16850#issuecomment-1572329332

Since it looks so closely related, would it be fine with you if we consider this other form of the bug as part of this issue?

**Comment by s-alves10** [comment] 2023-06-05 18:44
@parasharrajat @aldo-expensify 
The above [issue](https://github.com/Expensify/App/issues/16850#issuecomment-1572329332) seems to be fixed with my solution.

**Comment by marcaaron** [comment] 2023-06-07 21:00
Looks like there is no clear solution we can accept yet so as per [this comment](https://github.com/Expensify/App/issues/18555#issuecomment-1575695019) I guess I will have to look into this issue? 🥲

**Comment by s-alves10** [comment] 2023-06-07 21:03
@marcaaron 
Did you check my [proposal](https://github.com/Expensify/App/issues/18555#issuecomment-1561722967)? I think the solution would fix the root cause of the issue

**Comment by s-alves10** [comment] 2023-06-07 21:20
@marcaaron 
`Hoverable` is a general wrapper component that can wrap any component. 

> mouseleave event isn't fired when the element under cursor is removed
This is common for any elements

**Comment by marcaaron** [comment] 2023-06-09 02:40
Thanks, would you mind leaving any thoughts on the issue that was reopened? As mentioned elsewhere, I think we should limit the conversation to a single place and keep all the context on this "root cause" together.

**Comment by kadiealexander** [comment] 2023-06-13 03:15
Shifting to weekly while the other GH is worked on.

**Comment by kadiealexander** [comment] 2023-06-26 06:01
Same as above!

**Comment by kadiealexander** [comment] 2023-07-05 03:17
Still on hold.

**Comment by kadiealexander** [comment] 2023-07-28 05:49
Still on hold.

**Comment by kadiealexander** [comment] 2023-08-08 06:06
Still on hold.

**Comment by kadiealexander** [comment] 2023-08-22 06:11
Still on hold, shifting to monthly.

**Comment by kadiealexander** [comment] 2023-09-20 03:36
@parasharrajat are any payouts due here do you think? Doesn't seem like it

**Comment by dhanashree-sawant** [comment] 2023-09-20 05:43
Is it eligible for reporting bonus? In PR, 3 issues where marked in Fixed issue so not sure if this issue was helpful in the solution

**Comment by kadiealexander** [comment] 2023-09-21 00:25
@dhanashree-sawant we generally pay the reporting bonus to the person who first reported the bug that led to the fix, which would have been [this issue](https://github.com/Expensify/App/issues/16923).

**Comment by dhanashree-sawant** [comment] 2023-09-21 05:02
Got it, thanks

**Comment by kadiealexander** [comment] 2023-09-25 04:40
@parasharrajat any update?

**Comment by kadiealexander** [comment] 2023-09-26 05:22
Payouts due:

Contributor+: $500 @parasharrajat

Eligible for 50% #urgency bonus? No

**Comment by dhanashree-sawant** [comment] 2023-09-27 05:21
Hi @kadiealexander, can you once check @parasharrajat comments on #16923 before closing this?

**Comment by kadiealexander** [comment] 2023-09-27 05:45
I'll wait to see what @dylanexpensify agrees to.

**Comment by dylanexpensify** [comment] 2023-09-27 09:33
Yes, let's get that payment from the mentioned issue above paid out as well for @dhanashree-sawant @kadiealexander! 🙇‍♂️

**Comment by kadiealexander** [comment] 2023-10-06 03:32
Thanks Dylan! Updated the payment summary and sent an Upwork offer to you @dhanashree-sawant :)

**Comment by dhanashree-sawant** [comment] 2023-10-06 05:23
Thanks @kadiealexander, I have accepted the offer.

**Closed** 2023-10-09 20:44 UTC
Labels: Daily, Internal, Awaiting Payment, Bug
