### ISSUE TITLE
[HOLD for payment 2022-12-20] DEV: Add Debit Card Page Console Error Of Invalid Props Type

### ISSUE THREAD

**Issue by kavimuru** [Expensify/App#13068] opened 2022-11-27 16:58 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:

1. Close App
2. Open App Again
3. Click On Avatar
4. Click On Payments
5. Click On Add Payment Method
6. Select Debit Card

## Expected Result:
Console Error Shouldn't Appear

## Actual Result:
Console Error Of In Valid Prop Type Appears

## Workaround:
unknown

## Platform:

Where is this issue occurring?

- iOS
- Android

**Version Number:** 1.2.31-8
**Reproducible in staging?:** Need reproduction
**Reproducible in production?:** Need reproduction
**Email or phone of affected tester (no customers):** 
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** 

https://user-images.githubusercontent.com/43996225/204149235-a304c6ae-cf91-4430-bff4-09a5e9971066.mov

**Expensify/Expensify Issue URL:** 
**Issue reported by:** ~@syedsaroshfarrukhdot~ @aneequeahmad 
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1669477885177529
![Simulator Screen Shot - iPhone 13 Pro - 2022-11-26 at 20 51 05](https://user-images.githubusercontent.com/43996225/204149242-55c70e9e-290a-401d-bfea-e57072b0ac8b.png)

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by syedsaroshfarrukhdot** [comment] 2022-11-27 17:00
Proposal

It is straight forward fix we are using setupComplete: PropTypes.boolean which is invalid
we need to change it to setupComplete: PropTypes.bool

**Comment by slafortune** [comment] 2022-11-30 20:48
@syedsaroshfarrukhdot  I wasn't able to reproduce this in production.  On staging, I don't currently see the Debit Card option

Are you still able to reproduce this?

**Comment by syedsaroshfarrukhdot** [comment] 2022-11-30 21:02
@slafortune Yes, still able to reproduce it on **version** `1.2.34-1`


https://user-images.githubusercontent.com/81307212/204907236-c8da57b5-6399-48f8-94ed-01518326145c.mov

**Comment by syedsaroshfarrukhdot** [comment] 2022-12-01 20:21
@slafortune Were You Able To Reproduce On Development Build ?

**Comment by syedsaroshfarrukhdot** [comment] 2022-12-04 21:02
@slafortune Were You Able To Reproduce On Development Build ?

**Comment by luacmartins** [comment] 2022-12-05 21:54
I'll work on this one since it's a simple fix.

**Comment by luacmartins** [comment] 2022-12-05 21:55
Working on it today!

**Comment by syedsaroshfarrukhdot** [comment] 2022-12-05 22:02
> Working on it today!

@luacmartins Am i eligible for reporting bonus ?

**Comment by luacmartins** [comment] 2022-12-06 02:34
@syedsaroshfarrukhdot yes!

**Comment by slafortune** [comment] 2022-12-07 18:04
@syedsaroshfarrukhdot https://www.upwork.com/ab/applicants/1600549727321935872/job-details

**Comment by luacmartins** [comment] 2022-12-12 23:15
Seems like we are done here!

**Comment by syedsaroshfarrukhdot** [comment] 2022-12-12 23:49
I haven't been paid for the reporting bonus yet. Only got hired @luacmartins.

**Comment by syedsaroshfarrukhdot** [comment] 2022-12-13 00:19
Bumping for payment.

**Comment by aneequeahmad** [comment] 2022-12-13 17:53
I reported this bug on `August 24th` [here](https://expensify.slack.com/archives/C01GTK53T8Q/p1661313865197429) which wasn't logged on Github. I also mentioned again that it still exist in `dev`. 

I also could've proposed the solution if it was reported.

**Comment by michaelhaxhiu** [comment] 2022-12-13 21:54
Posted in #expensify-open-source [here](https://expensify.slack.com/archives/C01GTK53T8Q/p1670968370991619?thread_ts=1661313865.197429&cid=C01GTK53T8Q) to confirm if Aneeque is owed a bug reporting bonus. @slafortune can you help see it through from here? Holler if you need a bud check !

**Comment by michaelhaxhiu** [comment] 2022-12-14 19:58
Can we make a note that @aneequeahmad is owed compensation for the bug reporting bonus?

**Comment by slafortune** [comment] 2022-12-14 22:36
Hey @aneequeahmad  I just sent you an offer here - https://www.upwork.com/ab/applicants/1603156208534720512/offers

Let me know as soon as you can accept that 👍

**Comment by aneequeahmad** [comment] 2022-12-14 23:45
@slafortune I have accepted the offer. Thank you for mentioning

**Comment by mallenexpensify** [comment] 2022-12-24 01:31
It appears everyone has been paid, @slafortune you or I need to add a regression test then we can close

**Comment by luacmartins** [comment] 2023-01-09 17:29
@mallenexpensify I don't think regression tests are needed in this case. This is a prop-types console warning and only happens in dev, since they are removed from the staging/prod Apps. QA wouldn't be able to test this anyways. 

It also seems like we are no longer accepting this kind of "bug" report - https://expensify.slack.com/archives/C02NK2DQWUX/p1673201417498099

I'm gonna close this issue. Please reopen if needed!

**Closed by luacmartins** 2023-01-09 17:29 UTC
Labels: Reviewing, Engineering, Daily, Awaiting Payment, Bug
