### ISSUE TITLE
iOS - Distance - Unable to delete waypoint from 3-dot menu

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#46746] opened 2024-08-02 18:58 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 9.0.16-0
**Reproducible in staging?:** Y
**Reproducible in production?:** N
**If this was caught during regression testing, add the test name, ID and link from TestRail:** N/A
**Email or phone of affected tester (no customers):**
**Issue reported by:** Applause - Internal Team

## Action Performed:
1. Launch New Expensify app
2. Go to workspace chat
3. Submit a distance expense with three waypoints
4. Go to transaction thread
5. Tap Distance
6. Tap on waypoint
7. Tap on the three-dot menu
8. Tap Delete waypoint

## Expected Result:
App will show confirmation prompt to delete the waypoint

## Actual Result:
Nothing happens after tapping Delete waypoint from 3-dot menu
User is unable to delete waypoint from 3-dot menu option

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [x] iOS: Native
- [ ] iOS: mWeb Safari
- [ ] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details> 

https://github.com/user-attachments/assets/775b2a57-6cbd-4002-9cba-ac342f62e8f7

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by lanitochka17** [comment] 2024-08-02 18:59
We think that this bug might be related to #wave-collect - Release 1

**Comment by aldo-expensify** [comment] 2024-08-02 19:41
Investigating this now...

**Comment by aldo-expensify** [comment] 2024-08-02 20:05
Can't reproduce in Web:


https://github.com/user-attachments/assets/8d520375-e15f-4969-9434-b36e72d15314

so maybe it really happens only in IOS native... going to test in the IOS emulator

**Comment by aldo-expensify** [comment] 2024-08-02 21:02
just managed to have my IOS emulator working, I'll keep testing after lunch

**Comment by aldo-expensify** [comment] 2024-08-02 22:21
Reproduced in dev + emulator

**Comment by aldo-expensify** [comment] 2024-08-02 22:43
So far I see that `isDeleteStopModalOpen` is set to `true` correctly when I click `Delete waypoint` in the menu that appears from below. I'm looking into why the modal doesn't appear after.

https://github.com/Expensify/App/blob/df46bcd978906a54301d5fdc0a03ac4402ea5459/src/pages/iou/request/step/IOURequestStepWaypoint.tsx#L61

**Comment by roryabraham** [comment] 2024-08-02 22:45
Might I suggest retrying this offline? If reproducible offline I think we can remove the DeployBlocker label (not to be confused with DeployBlockerCash)

**Comment by aldo-expensify** [comment] 2024-08-02 22:47
I'll check, I didn't notice the `DeployBlocker`, I highly doubt this is backend related... just a sec

**Comment by aldo-expensify** [comment] 2024-08-02 22:48
Reproduced while offline

**Comment by aldo-expensify** [comment] 2024-08-02 22:51
I verified that this is not happening in the `production` branch, so I think it is a real `DeployBlockerCash`. I'll see if comparing the branches can give me a better idea of what went wrong.

**Comment by aldo-expensify** [comment] 2024-08-02 23:02
I think the bug is coming from this PR: https://github.com/Expensify/App/pull/45762
If I revert the changes in `PopoverMenu` the bug goes away

**Comment by aldo-expensify** [comment] 2024-08-02 23:27
oh, maybe we need to do something similar to this:

<img width="750" alt="image" src="https://github.com/user-attachments/assets/6c7f55db-7996-4ec7-a482-76e2b52e5557">

**Comment by aldo-expensify** [comment] 2024-08-02 23:56
PR up: https://github.com/Expensify/App/pull/46755

**Comment by zfurtak** [comment] 2024-08-05 08:06
@aldo-expensify 
hello 😊
In my PR I changed a bit the structure of `PopoverMenu` as it was causing a different bug. I checked all of the usages but apparently missed this one. Your PR is exactly how I would fix it!

**Comment by roryabraham** [comment] 2024-08-05 19:25
looks like this was fixed without external contribution. Closing this out

**Closed by roryabraham** 2024-08-05 19:25 UTC
Labels: Reviewing, DeployBlockerCash, Engineering, Weekly

**Comment by marcaaron** [comment] 2024-08-06 01:29
Sorry I think that there is still some problem [here](https://github.com/Expensify/App/issues/46764) can someone please look at this it's blocking the deploy and I'm not able to figure it out, thanks!
