### ISSUE TITLE
[HOLD for payment 2023-05-22] [$1000] App crashes when right clicking on a reaction once sender react to message with multiple emoji tone color, and recipient reacts to it

### ISSUE THREAD

**Issue by kavimuru** [Expensify/App#18552] opened 2023-05-07 17:08 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:

1. Open an existing group chat (account A)
2. Send a message
3. Hover over the message and react to the message with emoji
4. Change skin tone and add the same emoji reaction to the existing emoji reaction
5. On another window open the group chat with one of the group participants account (account B)
6. Add the same emoji reaction to the message (add same emoji)
7. Shift windows to account A , and right click on the reacted emoji

## Expected Result: 
System should display the list of user that has reacted with the emoji
## Actual Result: 
App crashes down

## Workaround:
Can the user still use Expensify without this being fixed? Have you informed them of the workaround?

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [x] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 1.3.11.2
**Reproducible in staging?:** y
**Reproducible in production?:** new feature
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation

https://user-images.githubusercontent.com/43996225/236692074-aa3d8df2-8db7-4513-b31d-aaae72452516.mp4

https://user-images.githubusercontent.com/43996225/236692080-ecf45542-0e84-4ae3-bec0-e68169f8cf90.mp4

**Expensify/Expensify Issue URL:**
**Issue reported by:** @natnael-guchima
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1683358345695579

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01262eda193a5f33e9</li>
        <li>Upwork Job ID: 1655595017535242240</li>
        <li>Last Price Increase: 2023-05-08</li>
    </ul>
</details>

**Comment by Natnael-Guchima** [comment] 2023-05-07 17:32
This bug seems to be related with this PR -> https://github.com/Expensify/App/pull/15685

**Comment by hungvu193** [comment] 2023-05-08 05:56
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
App crashes when right clicking on a reaction once sender react to message with multiple emoji tone color, and recipient reacts to it.
### What is the root cause of that problem?
We are calculating reaction users in this line:
```
 const reactionUsers = _.map(reaction.users, sender => sender.accountID.toString());
```

When user changed the skin stone and reacted to the message, the `reactionUsers` will have duplicate item in it.
For example: ` ['12736676', '12736676', '12736676', '12812778']`
Now, let take a look at the function we used to get the users from `reactionUsers` above:
https://github.com/Expensify/App/blob/d120f6a9aa13dc842e265202996f8fe32019faca/src/libs/PersonalDetailsUtils.js#L19-L37
Let take a look at line 34, right after we found the result we want, we break the loop. So when our array has duplicate item like my example, after the first one was found, the loop break and move to the next item, the next 2 duplicated will not be found. So the result array will look like this:
<img width="542" alt="Screenshot 2023-05-08 at 12 50 42" src="https://user-images.githubusercontent.com/16502320/236744306-c53cfe1b-b14f-47f0-9021-3afc73a12297.png">

```
firstime
undefined
undefined
thirditem
```
Because there were 2 items are undefined, the app will crash while user right click to open reaction list modal, because the list used the key extractor from the item, when item is undefined it will cause the crash.
```
const keyExtractor = (item, index) => `${item.login}+${index}`;
```
### What changes do you think we should make in order to solve the problem?
We have few solutions here:
1. Unique the `reactionUsers` list.
2. Update the `getPersonalDetailsByIDs`. Instead of assign the current index of the loop for the array, we should calculate the next index of the array.
```javascript
                const currentIndex = result.length === 0 ? 0 : result.length;
                if (shouldChangeUserDisplayName && currentAccountID.toString() === detail.accountID) {
                    result[currentIndex] = {
                        ...detail,
                        displayName: Localize.translateLocal('common.you'),
                    };
                } else {
                    result[currentIndex] = detail;
```

### What alternative solutions did you explore? (Optional)

**Comment by abekkala** [comment] 2023-05-17 20:11
@parasharrajat when you have a moment can you complete the checklist items above?

**Comment by abekkala** [comment] 2023-05-23 15:36
@parasharrajat once the checklist is done I can complete payments

**Comment by abekkala** [comment] 2023-05-23 20:00
### Payments to be made: 

Issue reported by: @Natnael-Guchima  [$250]
C+ Review:@parasharrajat [$1000] + [$500 Bonus]

**Comment by abekkala** [comment] 2023-05-23 20:25
@Natnael-Guchima payment made and contract ended. Thank you! 🎉

**Comment by abekkala** [comment] 2023-05-24 14:16
@parasharrajat yes, sorry about that. It looks like Upwork has been experiencing some site issues yesterday and this morning. 
I'll resend an offer and note this GH in the title.

**Comment by abekkala** [comment] 2023-05-24 14:19
I'll keep an eye on this. As soon as they're back up I'll resend the offer!
<img width="932" alt="Screenshot 2023-05-24 at 9 18 59 AM" src="https://github.com/Expensify/App/assets/11966460/5ebfa52a-133f-4ce3-a56d-b6f2c4362832">

**Comment by abekkala** [comment] 2023-05-24 15:11
@parasharrajat I sent another contract it's titled **[$1000] Payment for #18552 + [$500] Bonus**

**Comment by abekkala** [comment] 2023-05-24 17:53
@parasharrajat paid and contract ended! 🎉 thank you! 
Closing!

**Closed by abekkala** 2023-05-24 17:53 UTC
Labels: External, Daily, Awaiting Payment, Bug
