### ISSUE TITLE
[$1000] Web -  In Reply in thread of attachment, members option is not displayed first time on details page

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#23494] opened 2023-07-24 17:11 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Open the app
2. Open any report
3. Send any attachment
4. Hover and click on reply in thread
5. Click on [Attachment] in header to open details page
6. Observe that 'members' option is missing, revisit main thread and again click on reply in thread
7. Open details page by clicking on [Attachment] in header and observe that now members option is available on details page

## Expected Result:
App should display all the available option on details page of reply in thread whenever we visit the thread and open the details page

## Actual Result:
App does not display 'members' option on details page of reply in thread when we visit the thread for first time and open the details page

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [x] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 1.3.44-0
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/93399543/276dd3f3-a88b-4e3c-a537-5913c2d27cd7

https://github.com/Expensify/App/assets/93399543/1acd9bc0-03c5-4f35-a737-f46f22565d3a

**Expensify/Expensify Issue URL:**
**Issue reported by:** @dhanashree-sawant
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1690169551986479

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~0133838edb282aef6e</li>
        <li>Upwork Job ID: 1684171126687412224</li>
        <li>Last Price Increase: 2023-08-09</li>
    </ul>
</details>

**Comment by omarirfan68** [comment] 2023-07-24 19:11
Will I get paid if I fix this issue 23494

**Comment by omarirfan68** [comment] 2023-07-24 20:06
how to apply for proposal i got solution

**Comment by omarirfan68** [comment] 2023-07-24 20:47
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
In Reply in thread of attachment, members option is not displayed first time on details page

### What is the root cause of that problem?
The root cause of this problem is how members have been fetching data; it's asynchronous data loading.
And also, length is used twice, so it is causing errors, and also use lodashGet, which maybe is not working properly the first time for web.
https://github.com/Expensify/App/blob/main/src/pages/ReportDetailsPage.js

### What changes do you think we should make in order to solve the problem?

We should change the method of member fetching now to make it work properly in the file.
https://github.com/Expensify/App/blob/main/src/pages/ReportDetailsPage.js
The error might be coming from this line.
 const participants = useMemo(() => lodashGet(props.report, 'participantAccountIDs', []), [props.report]);


### What alternative solutions did you explore? (Optional)

**Reminder:** Please use plain English, be brief and avoid jargon. Feel free to use images, charts or pseudo-code if necessary. Do not post large multi-line diffs or write walls of text. Do not create PRs unless you have been hired for this job.

**Comment by NicMendonca** [comment] 2023-07-26 11:57
reproducible 👍

**Comment by StanislavLavrenchuk** [comment] 2023-07-27 02:31
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
In Reply in thread of attachment, members option is not displayed first time on details page
### What is the root cause of that problem?
In ReportScreen.js file props.report data is not rendering well.
Following code is the main point.

https://github.com/Expensify/App/blob/f8bb2b116439ab5210c80eb807a1b843ef37307d/src/pages/home/ReportScreen.js#L237-L242

### What changes do you think we should make in order to solve the problem?
this should be removed.
Because following code is working when submit new data.

https://github.com/Expensify/App/blob/f8bb2b116439ab5210c80eb807a1b843ef37307d/src/pages/home/ReportScreen.js#L211-L213

### What alternative solutions did you explore? (Optional)

**Comment by StanislavLavrenchuk** [comment] 2023-07-28 00:46
@ArekChr @NicMendonca  waiting review.

**Comment by ArekChr** [comment] 2023-07-31 12:03
> ### What changes do you think we should make in order to solve the problem?
> We should change the method of member fetching now to make it work properly in the file. https://github.com/Expensify/App/blob/main/src/pages/ReportDetailsPage.js The error might be coming from this line. const participants = useMemo(() => lodashGet(props.report, 'participantAccountIDs', []), [props.report]);

Hey @omarirfan68 This solution doesn't have a clear explanation of how to solve the issue

**Comment by ArekChr** [comment] 2023-07-31 12:13
@StanislavLavrenchuk removing `onSubmitComment` doesn't solve the problem, additionally, it introduces regression so new replies are not shown in threads.

**Comment by railway17** [comment] 2023-07-31 12:15
> @StanislavLavrenchuk removing `onSubmitComment` doesn't solve the problem, additionally, it introduces regression so new replies are not shown in threads.

Not sure but it could be a solution to change the API as I suggested?

**Comment by ArekChr** [comment] 2023-07-31 12:19
> Need to check why OpenReport API returns the values with empty `participantsAccountIDs`

@NicMendonca I think this might be a backend issue, not a frontend.

**Comment by StanislavLavrenchuk** [comment] 2023-07-31 13:05
> @StanislavLavrenchuk removing `onSubmitComment` doesn't solve the problem, additionally, it introduces regression so new replies are not shown in threads.

@ArekChr Sorry my uncleared proposal.
I meant we should remove following code or adding some condition.
https://github.com/Expensify/App/blob/f8bb2b116439ab5210c80eb807a1b843ef37307d/src/pages/home/ReportScreen.js#L237-L242
because `reportID` is added from here
https://github.com/Expensify/App/blob/f8bb2b116439ab5210c80eb807a1b843ef37307d/src/pages/home/ReportScreen.js#L211-L213

**Comment by madmax330** [comment] 2023-08-04 17:19
I'll try and reproduce it locally then I'll know for sure

**Comment by NicMendonca** [comment] 2023-08-07 20:00
Any update here? 👀

**Comment by ArekChr** [comment] 2023-08-09 08:03
@madmax330 Were you able to reproduce the issue locally? Do you have any updates on this?

**Comment by ShogunFire** [comment] 2023-08-09 16:48
I also think it is back end, As you can see on the screenshot thats @railway17 took the problem is actually that when we call openReport we get two times the report in the response, the first one with the list of account ids, the second one without account ids.  i don't think it's normal to have two times the report

![image](https://github.com/Expensify/App/assets/19537677/d29ee1c0-1824-4cc2-bae5-99ee035ca859)



When we do the request we actually send an empty accountIDList but I tried to send it and it didn't change anything

**Comment by ShogunFire** [comment] 2023-08-09 18:24
This is actually a duplicate issue: https://github.com/Expensify/App/issues/21600

**Comment by techievivek** [comment] 2023-08-10 10:39
Yes, this is a duplicate issue with same root cause as https://github.com/Expensify/App/issues/21600 so we can just close this out.

**Closed** 2023-08-10 10:40 UTC
Labels: External, Engineering, Daily, Help Wanted, Bug
