### ISSUE TITLE
[HOLD for payment 2023-08-28] Web - Request money - "Select a currency" tooltip is shown even if user is unable to do so

### ISSUE THREAD

**Issue by izarutskaya** [Expensify/App#24568] opened 2023-08-15 09:57 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Send a money request from account A to account B
2. Click on the IOU preview component to open the IOU report
3. Click on the currency to edit it
4. Hover over the currency

## Expected Result:
Since user is unable to change currency tooltip saying "Select a currency" should not be shown

## Actual Result:
"Select a currency" tooltip is shown even if user is unable to do so

## Workaround:
unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [x] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** v1.3.54-7

**Reproducible in staging?:** Y

**Reproducible in production?:** N

**If this was caught during regression testing, add the test name, ID and link from TestRail:**

**Email or phone of affected tester (no customers):**

**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/115492554/e3a5bd82-e29b-42eb-8cc1-d15c59f9424a

https://github.com/Expensify/App/assets/115492554/6f460c2b-01e8-4ba3-8399-c08aa59fefec

**Expensify/Expensify Issue URL:**

**Issue reported by:** @Nathan-Mulugeta

**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1692043293482609

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01b0a3053455828bfb</li>
        <li>Upwork Job ID: 1691413101275987968</li>
        <li>Last Price Increase: 2023-08-15</li>
    </ul>
</details>

**Comment by laurenreidexpensify** [comment] 2023-08-15 10:03
Just a heads up I am working 50% today and have just finished for the day, if there's anything that needs to be done on this from my side please ask in bug-zero Slakc thanks

**Comment by Gonals** [comment] 2023-08-15 10:06
On it!

**Comment by BhuvaneshPatil** [comment] 2023-08-15 11:03
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
Tooltip displays for currency when it's disabled

### What is the root cause of that problem?
We don't have any check while displaying tooltip for currency.
https://github.com/Expensify/App/blob/42757411e9d715ca77456242425677e47b522873/src/components/CurrencySymbolButton.js#L28-L37

### What changes do you think we should make in order to solve the problem?
There are few ways to handle this.
- Display different message in tooltip when it's disabled, eg - Can't change the currency
- Pass `null` as text when it's disabled. It hides the tooltip.
js
text={disabled ? null : translate('iOUCurrencySelection.selectCurrency')}

- We can modify `CurrencySymbolButton` to not render `Tooltip` component depending on value of prop `disabled`
```js
    if (disabled) {
        return (
            <PressableWithoutFeedback
                onPress={onCurrencyButtonPress}
                accessibilityLabel={translate('iOUCurrencySelection.selectCurrency')}
                accessibilityRole={CONST.ACCESSIBILITY_ROLE.BUTTON}
                disabled={disabled}
            >
                <Text style={styles.iouAmountText}>{currencySymbol}</Text>
            </PressableWithoutFeedback>
        );
    }
```

- We can modify `Tooltip` component to disable showing content by adding new prop - `disabled`

### What alternative solutions did you explore? (Optional)

**Comment by Gonals** [comment] 2023-08-15 11:35
Marking this as internal, as I already have a fix in place and it is a deploy blocker

**Comment by laurenreidexpensify** [comment] 2023-08-29 15:49
Payment Summary:

bug reporter @Nathan-Mulugeta $250 - offer sent in Upwork 
issue fix @Gonals $0 - Expensify internal
review @mountiny $0 - Expensify intenral

**Comment by Gonals** [comment] 2023-09-04 11:20
Filled checklist. This wasn't really a regression, just something introduced with the functionality itself, I'd say, so all good.

**Comment by laurenreidexpensify** [comment] 2023-09-04 14:07
Payment issued 👍 Closing

**Closed by laurenreidexpensify** 2023-09-04 14:07 UTC
Labels: Engineering, Daily, Internal, Awaiting Payment, Bug
