### ISSUE TITLE
Web - infinite loading on while opening Concierge profile details

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#21181] opened 2023-06-21 10:29 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
Action Performed:
1. Logout if you already logged in
2. Go to any public room ( https://staging.new.expensify.com/r/3222899886046357 )
3. Click on Concierge to see details

## Expected Result:
It should show Concierge details

## Actual Result:
Infinite loading on while opening Concierge profile details

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [x] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 1.3.27-6

**Reproducible in staging?:** n/a

**Reproducible in production?:** n/a
**If this was caught during regression testing, add the test name, ID and link from TestRail:**

**Email or phone of affected tester (no customers):**

**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/93399543/474a10be-bca1-4902-8b10-e6edc274006f

**Expensify/Expensify Issue URL:**

**Issue reported by:** @gadhiyamanan

**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1686751418637759

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by gadhiyamanan** [comment] 2023-06-24 08:30
I think it is fixed in the latest version, not able to reproduce

**Closed** 2023-06-26 16:05 UTC
Labels: Daily, Needs Reproduction, Overdue, Bug
