### ISSUE TITLE
[HOLD for payment 2023-09-06] [$1000] Chat - Second double tap on PDF file moves the view to the upper left corner of current page

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#24168] opened 2023-08-04 15:47 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
Pre-requisite: user must be logged in and have a chat in which have sent or received a PDF file.

1. Go to a chat that has a PDF file sent or received
2. Open the PDF file
3. Double tap anywhere on a page of the PDF file to zoom in
4. Double tap again

## Expected Result:
On second double tap, the view should zoom in more or zoom out

## Actual Result:
On second double tap, there's a visual issue and then the view moves to the upper left corner of current page

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [x] iOS / native
- [ ] iOS / Safari
- [ ] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 1.3.50.0

**Reproducible in staging?:** Yes

**Reproducible in production?:** Yes

**If this was caught during regression testing, add the test name, ID and link from TestRail:**

**Email or phone of affected tester (no customers):**

**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/78819774/96eec1aa-7bb8-457d-bcba-c7316042cd2c

**Expensify/Expensify Issue URL:**

**Issue reported by:** Applause - Internal Team

**Slack conversation:**

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~0197c69852f9c23b2c</li>
        <li>Upwork Job ID: 1689598442382041088</li>
        <li>Last Price Increase: 2023-08-10</li>
<li>Automatic offers: </li>
<ul>
<li>DrLoopFall | Contributor | 26302073</li>
</ul></li>
    </ul>
</details>

**Comment by DrLoopFall** [comment] 2023-08-04 15:57
## Proposal

### Please re-state the problem that we are trying to solve in this issue.

Second double tap on PDF file moves the view to the upper left corner of current page

### What is the root cause of that problem?

It's a bug from react-native-pdf v6.6.2

### What changes do you think we should make in order to solve the problem?
The issue has been fixed in upstream https://github.com/wonday/react-native-pdf/pull/730
So upgrading react-native-pdf to v6.7.1 would fix this issue.

**Comment by dylanexpensify** [comment] 2023-08-08 08:04
Reviewing this today to post update!

**Comment by meedwire** [comment] 2023-08-10 12:35
Contributor details
Your Expensify account email: [l.jeronimo12345@gmail.com](mailto:l.jeronimo12345@gmail.com)
Upwork Profile Link: (https://www.upwork.com/freelancers/~01ca86149987fc45fa)

The bug involves reviewing PDFView. In reviewing PDFView, the bug seems to be caused by an unwanted state update. When double-tapping, some states are being updated, resetting some states. Ideally, a complete review of PDFView and an update to a functional component should be done. I can include this in this update.

**Comment by meedwire** [comment] 2023-08-10 12:40
Contributor details
Your Expensify account email: [l.jeronimo12345@gmail.com](mailto:l.jeronimo12345@gmail.com)
Upwork Profile Link: [https://www.upwork.com/freelancers/leonardos24](https://www.upwork.com/freelancers/leonardos24)

The bug involves reviewing PDFView. In reviewing PDFView, the bug seems to be caused by an unwanted state update. When double-tapping, some states are being updated, resetting some states. Ideally, a complete review of PDFView and an update to a functional component should be done. I can include this in this update.

**Comment by meedwire** [comment] 2023-08-10 12:42
Contributor details
Your Expensify account email: [l.jeronimo12345@gmail.com](mailto:l.jeronimo12345@gmail.com)
Upwork Profile Link: https://www.upwork.com/freelancers/leonardos24

The bug involves reviewing PDFView. In reviewing PDFView, the bug seems to be caused by an unwanted state update. When double-tapping, some states are being updated, resetting some states. Ideally, a complete review of PDFView and an update to a functional component should be done. I can include this in this update.

**Comment by meedwire** [comment] 2023-08-10 12:44
Contributor details
Your Expensify account email: l.jeronimo12345@gmail.com
Upwork Profile Link: https://www.upwork.com/freelancers/leonardos24

The bug involves reviewing PDFView. In reviewing PDFView, the bug seems to be caused by an unwanted state update. When double-tapping, some states are being updated, resetting some states. Ideally, a complete review of PDFView and an update to a functional component should be done. I can include this in this update.

**Comment by meedwire** [comment] 2023-08-10 12:45
Contributor details
Your Expensify account email: l.jeronimo12345@gmail.com
Upwork Profile Link: https://www.upwork.com/freelancers/leonardos24

The bug involves reviewing PDFView. In reviewing PDFView, the bug seems to be caused by an unwanted state update. When double-tapping, some states are being updated, resetting some states. Ideally, a complete review of PDFView and an update to a functional component should be done. I can include this in this update.

**Comment by dylanexpensify** [comment] 2023-08-11 19:52
Didn't get an update today, will on Monday!

**Comment by mananjadhav** [comment] 2023-08-13 11:55
@DrLoopFall's proposal should work.

🎀 👀 🎀 C+ reviewed.

**Comment by dylanexpensify** [comment] 2023-08-15 17:22
reviewing

**Comment by mananjadhav** [comment] 2023-08-16 05:01
I'll check the error in the current version. If it exists in the current version, then I'll think we can still fix the view moving to the upper left corner, and treat the shake as separate issue? wdyt @joelbettner @dylanexpensify ?

**Comment by dylanexpensify** [comment] 2023-08-16 13:43
That sounds good to me, but @joelbettner for confirmation

**Comment by dylanexpensify** [comment] 2023-08-17 09:39
Bump @joelbettner

**Comment by dylanexpensify** [comment] 2023-08-21 08:42
reviewing today!

**Comment by dylanexpensify** [comment] 2023-08-21 10:25
@joelbettner bump again

**Comment by dylanexpensify** [comment] 2023-08-22 21:04
@mananjadhav let's go with breaking the issue out

**Comment by mananjadhav** [comment] 2023-08-23 17:17
Okay based on this comment, @DrLoopFall's proposal is good. We would still need to wait @joelbettner or you @dylanexpensify to assign them on this one.

**Comment by dylanexpensify** [comment] 2023-08-24 10:39
On it!

**Comment by dylanexpensify** [comment] 2023-08-24 10:40
@joelbettner please confirm when you can

**Comment by DrLoopFall** [comment] 2023-08-24 23:20
@dylanexpensify @mananjadhav @joelbettner
The PR #25907 is ready for review.

**Comment by dylanexpensify** [comment] 2023-08-25 11:27
Nice!

**Comment by mananjadhav** [comment] 2023-08-27 17:53
PR Reviewed, tests well. All on @joelbettner now.

**Comment by mananjadhav** [comment] 2023-09-07 18:59
This bug is primarily related to a third party dependency. I don't think we'll have this issue coming again soon, so I don't think we need a regression test.

**Comment by JmillsExpensify** [comment] 2023-09-10 11:40
Awaiting payment summary.

**Comment by dylanexpensify** [comment] 2023-09-11 10:20
Agree - payment summary incoming

**Comment by dylanexpensify** [comment] 2023-09-11 10:21
Payment summary:
- Contributor: @DrLoopFall $1,500
- Contributor+: @mananjadhav $1,500

[Upwork job](https://www.upwork.com/jobs/~0197c69852f9c23b2c)! Please apply!

**Comment by dylanexpensify** [comment] 2023-09-13 20:02
payments occurring

**Comment by dylanexpensify** [comment] 2023-09-13 20:03
Done!

**Closed** 2023-09-13 20:03 UTC
Labels: External, Daily, Awaiting Payment, Bug

**Comment by JmillsExpensify** [comment] 2023-09-21 09:14
$1,500 payment approved for @mananjadhav based on BZ summary.
