### ISSUE TITLE
[HOLD for payment 2024-01-17] [$500] Avatar - Default Avatar photo is not fully rendered

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#33616] opened 2023-12-26 19:05 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.17-1
**Reproducible in staging?:** y
**Reproducible in production?:** n
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** Applause - Internal Team
**Slack conversation:**

## Action Performed:
1. Navigate to staging.new.expensify.com
2. Create group chat ( one of the members should have default avatar image)
3. Tap on Header
4. Tap on member with default avatar

## Expected Result:
Avatar should be fully rendered

## Actual Result:
Default Avatar photo is not fully rendered.
It shows low quality image

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [ ] Android: mWeb Chrome
- [x] iOS: Native
- [ ] iOS: mWeb Safari
- [ ] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

https://github.com/Expensify/App/assets/93399543/a68abf4b-9e46-4aa6-b2bd-03e8146dec5a

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01cf187b06b1d900a9</li>
        <li>Upwork Job ID: 1739769092481089536</li>
        <li>Last Price Increase: 2023-12-26</li>
<li>Automatic offers: </li>
<ul>
<li>dukenv0307 | Contributor | 28072165</li>
</ul></li>
    </ul>
</details>

**Comment by robertjchen** [comment] 2023-12-26 22:04
Hm, can't seem to reproduce this locally

**Comment by mountiny** [comment] 2023-12-26 22:05
I do not think this is a blocker, this is not blocking user from any action.

@robertjchen This might require release build of the native app and its related to the expo-image PR so I am tagging @WojtekBoman @WoLewicki in case you could help handle this

**Comment by situchan** [comment] 2023-12-26 22:05
This is reproducible only on native (android/iOS)

**Comment by situchan** [comment] 2023-12-27 07:58
@dukenv0307's solution makes sense.
However, the [PR](https://github.com/Expensify/App/pull/31308) which introduced that formula was deployed to production already, while this was deploy blocker.
@dukenv0307 do you think expo image PR is offending one?

**Comment by mananjadhav** [comment] 2023-12-27 08:46
@dukenv0307's solution seems like would work.

@situchan Sorry I didn't understand your comment.

🎀 👀 🎀 C+ reviewed.

**Comment by situchan** [comment] 2023-12-27 09:36
@mananjadhav this is deploy blocker which means doesn't happen on production.
So still curious to know what the offending PR is. https://github.com/Expensify/App/pull/31308 is definitely not.

**Comment by shubham1206agra** [comment] 2023-12-27 10:14
@mananjadhav @situchan is right. This is stemming from another place. Let me put together a proposal so that you can review

**Comment by shubham1206agra** [comment] 2023-12-27 10:43
## Proposal
### Please re-state the problem that we are trying to solve in this issue

Avatar - Default Avatar photo is not fully rendered

### What is the root cause of that problem?

This is stemming from https://github.com/Expensify/App/pull/30905, as we changed the ImageRenderer Engine from FastImage to Expo Image, and so the properties https://github.com/Expensify/App/pull/30905/files?short_path=b5e8f8f#r1436919622

Plus, we have another problem. If we use default workspace avatar, the background color will be missing in this case. This is happening due to we are using `AttachmentViewImage` component to render this instead of `Icon` component.

### What changes do you think we should make in order to solve the problem?

I am not sure that we need `PixelRatio.get()`. Cause I am able to use the image correctly without this.
Asked here: https://github.com/Expensify/App/pull/31308/files#r1436925363

There are different solutions depending on the ideal behaviour

1. If we want to double tap zoom / pinch behaviour on native devices (which is doubtful given this is not present on web/mWeb), then we need to correct the width and height by removing `PixelRatio.get()` as it is not required, and pass fill color for workspace icons to the `AttachmentViewImage`, and then to `Image` component also.

2. If we do not want to double tap zoom / pinch behaviour on native devices (which is likely behaviour), then we can pass a prop through AttachmentModal to know the image is avatar and render that through `Icon` component instead of `AttachmentViewImage` for the default avatars.

### What alternative solutions did you explore? (Optional)

**Comment by aswin-s** [comment] 2023-12-27 17:32
## Proposal

### Please re-state the problem that we are trying to solve in this issue.

Default avatar looks pixelated on native devices

### What is the root cause of that problem?

We are using expo-image to render SVG images now. The logic for computing image dimension in Lightbox component considered only remote images. For sharper rendering of images on high dpi devices, it divided the native image dimension by device pixel density. 

https://github.com/Expensify/App/blob/d6f359fc010fe8120cf8a6761a4dac21c819e270/src/components/Lightbox.js#L185-L189

However for SVG images this logic is not required as SVGs are vectors and could easily be resized to required width. Right now default avatars have a native width and height of 80px and dividing that by device pixel ratio further reduce the size of rendered image. 

Also right now ImageView is throwing an error for local SVG images as its prop types expect only string types.
![image](https://github.com/Expensify/App/assets/6880914/f502ffa7-1c7c-467e-adc8-494f6736acbc)



### What changes do you think we should make in order to solve the problem?

Instead of reducing the SVG size further by dividing its native size by device pixel ratio, it should be resized either to the `DEFAULT_IMAGE_SIZE` of 200px or the `containerWidth` so that SVG gets resized as per device width.

```tsx
<Image
    source={{uri: source}}
    style={imageDimensions?.lightboxSize || {width: DEFAULT_IMAGE_SIZE, height: DEFAULT_IMAGE_SIZE}}
    isAuthTokenRequired={isAuthTokenRequired}
    onError={onError}
    onLoadEnd={() => setImageLoaded(true)}
    onLoad={(e) => {
        // For remote images use dpi adjusted size, for SVG resize it to fit container
        const width = typeof source === 'string' ? (e?.nativeEvent?.width || 0) / PixelRatio.get() : Math.max(e?.nativeEvent?.width || 0, DEFAULT_IMAGE_SIZE);
        const height = typeof source === 'string' ? (e?.nativeEvent?.height || 0) / PixelRatio.get() : Math.max(e?.nativeEvent?.height || 0, DEFAULT_IMAGE_SIZE);
        setImageDimensions({...imageDimensions, lightboxSize: {width, height}});
    }}
/>

```

Also local assets uri is going to be of type number. So to fix the prop type error, we need to modify the prop types of ImageView as below.

https://github.com/Expensify/App/blob/d6f359fc010fe8120cf8a6761a4dac21c819e270/src/components/ImageView/propTypes.js#L12

```ts
const imageViewPropTypes = {
     ..
    /** URL to full-sized image */
    url: PropTypes.oneOfType([PropTypes.string.isRequired, PropTypes.number.isRequired]),
```

### What alternative solutions did you explore? (Optional)
None (edited)

**Comment by chrispader** [comment] 2023-12-28 11:38
Ok everyone, thanks for pointing this out! :)

I just confirmed that we need to have `* PixelRatio.get()` instead of dividing. Also please add this to the fallback image's `onLoad` function:

```diff
{isFallbackVisible && (
                        <View
                            collapsable={false}
                            style={StyleUtils.getFullscreenCenteredContentStyles()}
                        >
                            <Image
                                source={{uri: source}}
                                resizeMode="contain"
                                style={fallbackSize}
                                isAuthTokenRequired={isAuthTokenRequired}
                                onLoadEnd={() => setFallbackLoaded(true)}
                                onLoad={(e) => {
-                                    const width = e.nativeEvent?.width || 0;
-                                    const height = e.nativeEvent?.height || 0;
+                                    const width = (e.nativeEvent?.width || 0) * PixelRatio.get();
+                                    const height = (e.nativeEvent?.height || 0) * PixelRatio.get();

                                    if (imageDimensions?.lightboxSize != null) {
                                        return;
                                    }

                                    setImageDimensions({...imageDimensions, fallbackSize: {width, height}});
                                }}
                            />
                        </View>
                    )}
```

**Comment by robertjchen** [comment] 2023-12-29 03:49
ok, let's move forward with @dukenv0307 's proposal 👍

**Comment by robertjchen** [comment] 2024-01-19 00:44
Awaiting completion of BZ checklist

**Comment by mananjadhav** [comment] 2024-01-19 04:40
The offending PR was already identified [here](https://github.com/Expensify/App/pull/31308/files#r1437577057) and the comment was added during investigation. I don't think we need a regression test for this.

This is ready for payout @kevinksullivan Can you please post the payout summary?

**Comment by kevinksullivan** [comment] 2024-01-24 23:31
Payment summary:
- C+: @mananjadhav $500
- Contributor: @dukenv0307 $500

**Comment by kevinksullivan** [comment] 2024-01-24 23:31
Paid @dukenv0307 , closing this one out and @mananjadhav can request in newdot.

**Closed by kevinksullivan** 2024-01-24 23:31 UTC
Labels: Reviewing, External, Engineering, Daily, Awaiting Payment

**Comment by JmillsExpensify** [comment] 2024-01-25 15:27
$500 approved for @mananjadhav based on summary above.
