### ISSUE TITLE
Sign up - App crashes when signing up with a new account via magic link

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#33354] opened 2023-12-20 13:05 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** v1.4.14-2
**Reproducible in staging?:** y
**Reproducible in production?:** n
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** Applause - Internal Team
**Slack conversation:**

## Action Performed:
Precondition: App must be freshly installed, or clear app data before running the steps below.

1. Launch New Expensify app.
2. Enter a new email account.
3. On magic code page, navigate to email and tap on the magic link.

## Expected Result:
App does not crash.

## Actual Result:
App crashes.

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [ ] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

https://github.com/Expensify/App/assets/93399543/5ea98185-3a29-4420-9b78-7137d1fb91bd

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by kbecciv** [comment] 2023-12-20 13:07
Not reproducible in production

https://github.com/Expensify/App/assets/93399543/6b6c4e1f-b8cf-416b-9656-d7ecfde329c1

**Comment by ikevin127** [comment] 2023-12-20 14:05
I can reproduce it with 100% success rate on local with latest main performing the following actions:

#### Precondition: App must be killed / closed (not opened in background) before running the steps below.

1. Launch New Expensify app.
2. Enter email account and tap Continue.
3. While on magic code page, navigate to your email and tap on the magic link.

Issue seems to be caused by the following line of code:

https://github.com/Expensify/App/blob/9ea6b39346131f49fae4b15a59c33995d4313c8d/src/libs/Navigation/linkTo.ts#L83

because the `rootState.routes` is `undefined` when attempting deep-link login first time the app is opened.

<details>
<summary>iOS: Native - Screenshot</summary>
<img width="380" alt="Screenshot 2023-12-20 at 15 17 24" src="https://github.com/Expensify/App/assets/56457735/66de2ae9-36b9-44a1-8981-f2a628103870">
</details>

The issue does not occur on subsequent trials if the app is not killed / closed and I think this is because subsequently the `rootState.routes` is not `undefined` anymore.

**Comment by WojtekBoman** [comment] 2023-12-20 16:21
Hello! Thank you for finding the cause of the problem :) I will add a fix in this PR which is also related to LHP https://github.com/Expensify/App/pull/33359

**Comment by jasperhuangg** [comment] 2023-12-21 01:44
Closing, fix was CP'd

**Closed by jasperhuangg** 2023-12-21 01:44 UTC
Labels: Engineering, Daily
