### ISSUE TITLE
[$250] Web - Connect Bank Account - User can proceed to Company Information page without clicking the checkmark "I accept the Expensify term of service"

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#12104] opened 2022-10-24 22:56 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Log in with a applause.expensifail account (that does not have any bank account already added)
2. Enable staging Web secure server in Account Preferences if disabled
3. Navigate to the add bank account modal (Workspace settings > Add bank account)
4. Verify the Add bank account modal is displayed with 2 options to add bank accounts (Log in and Manual)
5. Select the Connect with plaid method to add a bank account
6. On the bank account list select "Chase"
7. You'll be redirected to the "First Platypus Bank"
8. Enter the credentials "user_good / pass_good"
10. If a verification is prompted - select mobile and enter "credentials_good" as the verification mode
11. Checkmark the "Plaid Checking" and "Plaid Saving"
12. Checkmark the 2 options under "additional information you want to share"
13. Click on continue
14. Check the T&C and click "Connect account information"
15. Click on the last confirmation on the plaid modal
16. Verify you're redirected to the choose an account screen in NewDot
17. Select the bank account ending in 1111
18. Verify you're redirected to the enter back account details manually (this is a special case for the Chase bank account selection)
19 Enter routing number 011401533
20. Enter a incorrect bank account number (e.g 1111222233334444)
21. Verify there's an error for entering the wrong bank account and in which number should the bank account end with.
22. Enter the correct number - 1111222233331111
23. Verify you can proceed and the next step in the bank account flow is displayed
24. Close the modal
25. Go back to Setting - Workspace
26. Select Connect Bank Account
27. Verify you're redirected to the enter back account details manually
28. Do not select the checkmark "I accept the Expensify term of service"
29. Click Save and Continue

## Note:
mWeb - Using the Chase credentials does not work.
We are blocked to test the VBA flow in app, it directed to production.

## Expected Result:
User can not proceed to Company Information page without clicking the checkmark "I accept the Expensify term of service"

## Actual Result:
User can proceed to Company Information page without clicking the checkmark "I accept the Expensify term of service"

## Workaround:
Unknown

## Platform:

Where is this issue occurring?

- Web
- iOS - blocked
- Android - blocked
- Desktop App -n/a
- Mobile Web - blocked to 

**Version Number:** 1.2.18.10

**Reproducible in staging?:** Yes

**Reproducible in production?:** N/A

**Email or phone of affected tester (no customers):** 

**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Notes/Photos/Videos:** Any additional supporting documentation

https://user-images.githubusercontent.com/93399543/197649633-31b0327f-ab45-4a96-900e-d6020cebd4d9.mp4

**Expensify/Expensify Issue URL:** 

**Issue reported by:** Applause - Internal Team

**Slack conversation:** 

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by tgolen** [comment] 2022-10-27 14:41
Marking as external to start getting proposals

**Comment by mmjindal2555** [comment] 2022-10-31 11:52
Hi @kbecciv @tgolen, I tried reproducing the issue in my local environment. Instead of opening the 'First Platypus Bank' modal, it is getting redirected to this URL - https://secure04ea.chase.com/web/auth/thirdparty/authorize?...

Can you please help me understand what I am missing here?

Thanks.

**Comment by parasharrajat** [comment] 2022-10-31 12:35
No Takers.

**Comment by mmjindal2555** [comment] 2022-10-31 12:56
I tried reproducing the issue in my local system, but instead of opening the 'First Platypus Bank' modal, it is getting redirected to this URL - https://secure06ea.chase.com/web/auth/thirdparty/authorize?... 
I tried using user_good / pass_good credentials, but it throws an Unauthorized error -  "We can't find that username and password."

What I might be missing here? @kbecciv @parasharrajat 

<img width="1301" alt="Screenshot 2022-10-31 at 5 13 51 PM" src="https://user-images.githubusercontent.com/14273484/199012772-0748483b-9d78-47a3-9b97-49ce51bc87ad.png">

**Comment by parasharrajat** [comment] 2022-10-31 13:13
@mmjindal2555 Are you our Slack? If not, please request access and it would be a good question there.

**Comment by mmjindal2555** [comment] 2022-10-31 13:27
I have requested access, waiting for it.

**Comment by parasharrajat** [comment] 2022-10-31 13:45
Meanwhile, raised it here https://expensify.slack.com/archives/C01GTK53T8Q/p1667222549786869.

**Comment by mmjindal2555** [comment] 2022-11-01 20:55
Thank you @parasharrajat, I was able to redirect to the Sandbox webpage for the Bank verification. 
However, for me, the behavior seems to be as expected, i.e., I am getting the error prompt when the Terms checkbox is not selected on submitting. 

**Version Number** (Dev): 1.2.21-4 - working as expected
**Version Number** (Staging): 1.2.22-3 - working as expected

Another difference I noticed - 
Error raised on Wrong Account number in OP's video -
**And unexpected error occurred...**

Error raised in my iterations -
**Your account number should end with 1111**

@kbecciv @parasharrajat 

Recording - 
https://user-images.githubusercontent.com/14273484/199331539-01967bce-c356-409f-9b9a-4f3c6ab0ee57.mp4

**Comment by parasharrajat** [comment] 2022-11-01 21:36
It might have been fixed by now. @Expensify/applause Could you please retest this issue?

**Comment by mvtglobally** [comment] 2022-11-03 03:18
Issue not reproducible during KI retests. (First week)

**Comment by kavimuru** [comment] 2022-11-03 13:47
@parasharrajat Issue is fixed.

https://user-images.githubusercontent.com/43996225/199737606-5279d7a3-fb3f-4f7d-84a1-816918bd38a4.mp4

**Comment by parasharrajat** [comment] 2022-11-03 13:58
Good to close then.

**Comment by tgolen** [comment] 2022-11-07 15:24
Closing this out now.

**Closed by tgolen** 2022-11-07 15:24 UTC
Labels: External, Engineering, Daily, Help Wanted, Overdue
