### ISSUE TITLE
[Simplified Collect][Distance rates] Subcategory is displayed as indented instead of Parent: Child format

### ISSUE THREAD

**Issue by izarutskaya** [Expensify/App#38662] opened 2024-03-20 10:47 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

*Found when validating PR :* https://github.com/Expensify/App/pull/38060

**Version Number:** 1.4.55-0
**Reproducible in staging?:** Y
**Reproducible in production?:** N
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Issue reported by:** Applause-Internal team

## Action Performed:
Precondition:
- User is admin of Collect workspace.
- The Collect workspace has subcategories.

1. Go to staging.new.expensify.com.
2. Go to Profile > Workspaces > Collect workspace.
3. Go to Distance rates.
4. Click Settings.
5. Select a subcategory.

## Expected Result:
The selected subcategory in Default category row will be displayed in Parent: Child format.

## Actual Result:
The selected subcategory in Default category row is displayed as indented subcategory.

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [x] Android: mWeb Chrome
- [x] iOS: Native
- [x] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

https://github.com/Expensify/App/assets/115492554/0e5b36af-0413-4f00-9d3a-c2836cb97b76

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by izarutskaya** [comment] 2024-03-20 10:51
@garrettmknight I haven't added the External label as I wasn't 100% sure about this issue. Please take a look and add the label if you agree it's a bug and can be handled by external contributors.




We think this issue might be related to the #wave-control.

**Comment by MrMuzyk** [comment] 2024-03-20 14:56
I will fix this in the next PR that adds another screen to distance rates feature. Currently its in draft state https://github.com/Expensify/App/pull/38237

**Comment by trjExpensify** [comment] 2024-03-20 15:34
Discussed in the thread. The issue is that we aren't showing the parent category in the push row preview, only the indented child category. Here's the comparison with a category on an expense:

<img width="376" alt="image" src="https://github.com/Expensify/App/assets/16232057/91db8174-cf55-4127-abfa-307a0da26f69">
<img width="373" alt="image" src="https://github.com/Expensify/App/assets/16232057/b9bf274e-05ae-4fd4-b374-d8dec7068516">

**Comment by garrettmknight** [comment] 2024-03-27 20:33
Made it to prod today, will test tomo.

**Comment by garrettmknight** [comment] 2024-04-10 10:20
This is fixed, closing.

**Closed by garrettmknight** 2024-04-10 10:20 UTC
Labels: Reviewing, Engineering, Daily, Bug
