### ISSUE TITLE
[HOLD][$1000] Thread - Draft message is bolded in LHN for 1:1 DM but not bolded for thread in room

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#24485] opened 2023-08-12 13:42 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Go to staging.new.expensify.com

Chat:
2. Go to any chat
3. Send a message
4. Right click > choose Reply in thread don't type anything (notice chat is bold in LHN)

Room:
5. Go to any room
6. Send a message
7. Right click > choose Reply in thread don't type anything or send a message (notice the chat isn't bold in LHN)

## Expected Result:
If the thread message in LHN is meant to be bolded (or not), it should exhibit the same behavior regardless of the where the reply is made

## Actual Result:
In Step 4 (1:1 DM), the thread message is bolded in LHN
In Step 7 (room), the thread message is not bolded in LHN

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [x] Windows / Chrome 
- [ ] MacOS / Desktop

**Version Number:** 1.3.53.1

**Reproducible in staging?:** Yes

**Reproducible in production?:** Yes

**If this was caught during regression testing, add the test name, ID and link from TestRail:**

**Email or phone of affected tester (no customers):**

**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/78819774/1ef7d05e-c81e-4ac1-9bff-2c9223950567

**Expensify/Expensify Issue URL:**

**Issue reported by:** Applause -Internal Team

**Slack conversation:**

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01cd32b29d98720131</li>
        <li>Upwork Job ID: 1691535299004182528</li>
        <li>Last Price Increase: 2023-08-15</li>
    </ul>
</details>

**Comment by jeet-dhandha** [comment] 2023-08-12 22:33
Its a backend issue as lastReadTime is set in case of creating thread by "reply in thread" in rooms. But when doing same thing from a personal/group chat the lastReadTime is not set, thus showing the Bold Style.

**Comment by Christinadobrzyn** [comment] 2023-08-15 18:56
I can reproduce this 

For the chat - it seems like the message is bolded until you actually send a message and then it's no longer bold in the LHN. 

https://github.com/Expensify/App/assets/51066321/5ee04039-b01a-4b8d-83b8-6e8a271f7564


Asking how we want this to behave [here](https://expensify.slack.com/archives/C01SKUP7QR0/p1692125631097469)

**Comment by Christinadobrzyn** [comment] 2023-08-15 19:15
Okay so we'd want this to behave as [follows](https://expensify.slack.com/archives/C01SKUP7QR0/p1692125740721779?thread_ts=1692125631.097469&cid=C01SKUP7QR0): 

- Drafted messages are not bold in LHN (as bold indicates unread in the app) but they do show a pencil icon indicating they are a draft

**Comment by Christinadobrzyn** [comment] 2023-08-15 19:16
I think this is internal but let me know if it can be external!

**Comment by Christinadobrzyn** [comment] 2023-08-15 21:16
Sorry I added both labels and that assigned too many C+. Going to remove @narefyev91 as I believe this needs to be internal.

**Comment by burczu** [comment] 2023-08-17 09:07
@Christinadobrzyn Are we waiting here for proposal as it's internal issue?

**Comment by Christinadobrzyn** [comment] 2023-08-17 20:14
Ah sorry, I added the `engineering` label to assign an engineer to this job to move it forward. I this it will just be you and the engineer working on this - unless you think this can be `external` and we can accept proposals.

**Comment by burczu** [comment] 2023-08-18 06:43
@Christinadobrzyn yeah, that's what I thought so I was waiting for PR from some internal engineer, and was surprised that we received a proposal.

**Comment by Christinadobrzyn** [comment] 2023-08-18 20:51
Thanks @sarious - sorry for the confusion, that was my fault. I think this will be fixed internally with our engineer and @burczu.

**Comment by burczu** [comment] 2023-08-21 08:47
not overdue - waiting for PR from internal engineer

**Comment by Christinadobrzyn** [comment] 2023-08-23 15:41
Hi @cristipaval would you have an update on where we are with a PR?

**Comment by cristipaval** [comment] 2023-08-24 20:24
I would hold this issue because 
- @srikarparsi is working on hiding empty chats from LHN, which might not fix this issue
- @MonilBhavsar has a project that improves the way that the chats are marked as read

@srikarparsi @MonilBhavsar Do you think any of your project will fix this issue?

**Comment by Christinadobrzyn** [comment] 2023-09-12 21:19
On hold based on - https://github.com/Expensify/App/issues/24485#issuecomment-1692358334

**Comment by Christinadobrzyn** [comment] 2023-09-15 19:14
checking with @MonilBhavsar and @srikarparsi to see if you can help with this comment - https://github.com/Expensify/App/issues/24485#issuecomment-1692358334

**Comment by cristipaval** [comment] 2023-09-25 13:17
bump @MonilBhavsar and @srikarparsi!

**Comment by cristipaval** [comment] 2023-10-04 11:38
I wonder if this one is still reproducible in the latest staging. I know some work has been done lately.

**Comment by Christinadobrzyn** [comment] 2023-10-20 00:57
I'll investigate... this in just a moment..

**Comment by Christinadobrzyn** [comment] 2023-10-20 16:59
Thank you @kbecciv! I think we can close this, right @cristipaval?

**Comment by cristipaval** [comment] 2023-10-23 11:53
Yes @Christinadobrzyn, thank you! It also seems that no payment is needed here.

**Closed by cristipaval** 2023-10-23 11:53 UTC
Labels: Engineering, Weekly, Internal, Bug
