### ISSUE TITLE
Center align Workspace name on web and mobile web 

### ISSUE THREAD

**Issue by MitchExpensify** [Expensify/App#4860] opened 2021-08-26 17:52 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Click "+" in new.expensify.com
2. Click "Create Workspace"
3. Workspace name is not aligned in the left hand pane

## Expected Result:
I would expect the Workspace name to be center aligned under the workspace avatar

## Actual Result:
Workspace name is not center aligned under the workspace avatar

## Workaround:
Ignore

## Platform:

Where is this issue occurring?

- Web 
- Mobile Web

**Version Number:** v1.0.88-0
**Notes/Photos/Videos:** 
![image](https://user-images.githubusercontent.com/36425901/131010971-e4e46686-e8c5-4c5d-ad05-78d212b86c40.png)

![IMG_962ABCE3FF01-1](https://user-images.githubusercontent.com/36425901/131011592-f95484d7-24fd-4cd7-b858-7ee5cafea937.jpeg)

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by PrashantMangukiya** [comment] 2021-08-28 05:27
## Proposed Solution: 

As we can understand Text element wrapped within Tooltip, so we need to set styles.alignSelfCenter for Text element, so content within text element always remain in center irrespective of its parent style.  

Also there is no need styles.alignSelfCenter for Pressable component because there is no effect for that style at present.

Below are the code snipped from  /src/pages/workspace/WorkspaceSidebar.js  file.

      <Pressable
          style={[
              //styles.alignSelfCenter,   // Remove style from here as there is no effect
              styles.mt4,
              styles.mb6,
              styles.w100,
          ]}
          onPress={openEditor}
      >
          <Tooltip text={policy.name}>
              <Text
                  numberOfLines={1}
                  style={[
                      styles.displayName,
                      styles.alignSelfCenter    // Add this style so it will align Text element content to center
                  ]}
              >
                  {policy.name}
              </Text>
          </Tooltip>
      </Pressable>

I corrected code as per my suggestion above and tested on various devices. **In fact I notice that this issue is there for all platform (not just Web and Mobile Web).** So this solution corrects problem on all platform as shown screenshot below:

### Screenshots

#### Web - Large Window
<img width="1246" alt="4860-Web1" src="https://user-images.githubusercontent.com/7823358/131207046-681a3138-70d1-4d34-aebf-62ad6d0c510b.png">

#### Web - Small Window
<img width="612" alt="4860-Web2" src="https://user-images.githubusercontent.com/7823358/131207058-21058d80-129b-4fcc-b1e1-526a08acaf0a.png">

#### Mobile Web
<img width="612" alt="4860-MobileWeb1" src="https://user-images.githubusercontent.com/7823358/131207070-3c1f9eb2-9fea-45ca-852f-a93b5101c22f.png">

#### Desktop
<img width="1312" alt="4860-MacOS-Desktop1" src="https://user-images.githubusercontent.com/7823358/131207102-2bff59d1-5d83-494c-be32-a1fe6a7e26d2.png">

#### iOS
<img width="612" alt="4860-iOS1" src="https://user-images.githubusercontent.com/7823358/131207107-5b4aa9f0-f198-4452-a0ec-9e9b6b380ee8.png">

#### Android 7.1.1
<img width="612" alt="4860-Android1" src="https://user-images.githubusercontent.com/7823358/131207122-3fe4a70a-c933-42ff-a54d-3102b8286309.jpg">


If my solution considered then kindly accept my Upwork proposal.  Once my proposal accepted, I will do final testing and submit pull request within 2 days.

My Upwork profile: [https://www.upwork.com/freelancers/~01c718889ed7821f82](https://www.upwork.com/freelancers/~01c718889ed7821f82)

Best Regards, 
Prashant Mangukiya

**Comment by gregorjoshua** [comment] 2021-08-28 06:33
I think that this can be fixed by just changing
src\pages\workspace\WorkspaceSidebar.js line 133 from
`styles.alignSelfCenter,`
to 
`styles.alignItemsCenter,`

Orignal: 
![centering_og](https://user-images.githubusercontent.com/54114913/131208796-5ffce2d1-fc38-4708-8a2d-abf85326055f.png)

Fixed:
![centering_fixed](https://user-images.githubusercontent.com/54114913/131208799-1882369d-c398-430d-8a9c-c8ce8f5a4717.png)

**Comment by PrashantMangukiya** [comment] 2021-08-28 07:16
Hi @gregorjoshua   Thanks for the suggestion. But It is not good idea to set styles.alignItemsCenter at line 133 for Pressable componnet, because It is disturbing the Tooltip child component behaviour under it. i.e. when workspace name too long then text touches left and right side and it is not expected behaviour.  

See below screenshot that shows longs workspace name touched at left and right side when we set styles.alignItemsCenter to Pressable at line 133 , it is not expected behaviour.

<img width="1462" alt="Worksapcename-Disturb1" src="https://user-images.githubusercontent.com/7823358/131209890-50ecf9ce-e4d3-4411-ae09-1527459e4486.png">

When workspace name too long it should truncate text and show ellipses at the end (i.e. three dots ...).  I updated screenshot within my proposal, as you can see it shows expected behaviour when workspace name too long.

Thanks

**Comment by gregorjoshua** [comment] 2021-08-28 08:44
Thanks @PrashantMangukiya! This is my first time commenting/contributing so I appreciate any feedback. 


However, I think that the code that is in place already takes care of that (at least on Android). 
![Uploading centering_fixed_2.png…]()

I tried to test on Web, but when I run `npm run web` my localhost runs the https://www.expensify.com/ site, and not the https://new.expensify.com/ site so I haven't figured out how to test on web. 

Is your screenshot using the code that I suggested?

**Comment by PrashantMangukiya** [comment] 2021-08-28 11:28
> Is your screenshot using the code that I suggested?

Hi @gregorjoshua , Thanks for the message. Yes I set  styles.alignItemsCenter to Pressable component at line 133 and taken screenshot for web version that shows workspace name disturbed. 

Now I just fetched recent version of the app (1.0.88-2), compiled and tested. Strange result, It looks like now changing styles.alignSelfCenter to styles.alignItemsCenter at line 133 Pressable component also working proper as per your suggestion. I think there was some glitch in previous version.

Now both  solution i.e. changing styles.alignSelfCenter to  styles.alignItemsCenter at line 133 as you suggest,  and Other is to add styles.textAlignCenter to text component working as expected in all platform. 

In fact now my previously suggested solution to add styles.alignSelfCenter to text component is not working as expected in all platform. I will prefer to add styles.textAlignCenter to text component instead of Pressable component.

Thanks.

**Comment by shawnborton** [comment] 2021-08-29 09:41
So the workspace name was designed to be centered and I believe when it was
first implemented, it was centered. That means there was a regression some
where that’s causing this right? I think we should track down the
regression and have that contributor fix the issue we’re experiencing here.
Does anyone agree with that?

**Comment by akshayasalvi** [comment] 2021-08-29 12:45
@shawnborton I had recently worked on the workspace name tooltip. Let me see if it is my regression.

**Comment by shawnborton** [comment] 2021-08-30 07:47
Awesome, thank you!

**Comment by deetergp** [comment] 2021-08-30 17:38
@akshayasalvi thanks for owning up to the regression. Does that mean we are good to close this one?

**Comment by deetergp** [comment] 2021-08-30 22:07
I'm going with "yes" feel free to reopen if anyone disagrees.

**Closed by deetergp** 2021-08-30 22:07 UTC
Labels: Exported, Daily, Help Wanted
