### ISSUE TITLE
[HOLD for BE work] Workspace chats does not show  as bold for the new expense report requests

### ISSUE THREAD

**Issue by m-natarajan** [Expensify/App#38778] opened 2024-03-21 21:20 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.55-1
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** @puneetlath 
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1710776229802789

## Action Performed:
1. Send a money request to a workspace chat
2. Login as approver

## Expected Result:
Message should appear bold in LHN

## Actual Result:
Messages does not show in bold

## Workaround:
unknonw

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

https://github.com/Expensify/App/assets/38435837/b41c6c74-7246-4e20-aca3-ab89ebf52c81

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01ed3b85901af1a5cf</li>
        <li>Upwork Job ID: 1772295775561621504</li>
        <li>Last Price Increase: 2024-04-01</li>
    </ul>
</details>

**Comment by nkdengineer** [comment] 2024-03-22 04:05
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
- Workspace chats does not show as bold for the new expense report requests
### What is the root cause of that problem?
- We use [this](https://github.com/Expensify/App/blob/575d0ff04101e0690fec251abe75049727d8d8d9/src/libs/SidebarUtils.ts#L272) logic to check if the report is unread or not. In case the last message is ReportPreview, the ```!!report.lastActorAccountID``` is ```false```which leads to it does not show as bold.
### What changes do you think we should make in order to solve the problem?
- We can update [this](https://github.com/Expensify/App/blob/575d0ff04101e0690fec251abe75049727d8d8d9/src/libs/SidebarUtils.ts#L272) to:
```
    result.isUnread = ReportUtils.isUnread(report) && (ReportActionsUtils.isReportPreviewAction(last(visibleReportActionItems)) ? true : !!report.lastActorAccountID);
```

### What alternative solutions did you explore? (Optional)

- NA

**Comment by bernhardoj** [comment] 2024-03-22 05:56
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
The chat item in LHN doesn't show as bold for the workspace admin/approver when there is an expense preview

### What is the root cause of that problem?
https://github.com/Expensify/App/pull/36950 changes the unread logic a bit by checking whether the report has a `lastActorAccountID` or not.
https://github.com/Expensify/App/blob/4e6c52cad9f893a00e72d989caecdaf457a0ea02/src/libs/SidebarUtils.ts#L272

But in case the last action is a report preview, the last actor account ID is 0.
<img width="180" alt="image" src="https://github.com/Expensify/App/assets/50919443/2b3b3f67-5e1a-400a-bf52-5fead46ca1c6">

### What changes do you think we should make in order to solve the problem?

First of all, we should revert https://github.com/Expensify/App/pull/36950 as it doesn't fix the root cause of the issue. The issue that the PR is trying to fix is that when we delete the last message in a room from device A, the `lastVisibleActionCreated` property of the report isn't updated in device B, so the logic of unread, that is
https://github.com/Expensify/App/blob/4e6c52cad9f893a00e72d989caecdaf457a0ea02/src/libs/ReportUtils.ts#L4182

stays true. It will be updated once the device B opens the room. So, the problem is in the pusher that doesn't send the update to device B. Instead of patching up the issue, we should fix the pusher.

_fyi, when we delete the last message, we [set the `lastVisibleActionCreated` to empty optimistically](https://github.com/Expensify/App/blob/4e6c52cad9f893a00e72d989caecdaf457a0ea02/src/libs/actions/Report.ts#L1160-L1178), that's why the device A doesn't experience the issue. I think it should be set to the CREATED action `created` value, but I guess that's another topic to discuss_

**Comment by jayeshmangwani** [comment] 2024-03-27 15:01
Reviewing Proposals

**Comment by jayeshmangwani** [comment] 2024-03-28 11:13
Thanks for the proposals @nkdengineer @bernhardoj ,
@nkdengineer Your proposal will fix the issue but I also feel same what @bernhardoj mentioned [here](https://github.com/Expensify/App/issues/38778#:~:text=stays%20true.%20It%20will%20be%20updated%20once%20the%20device%20B%20opens%20the%20room.%20So%2C%20the%20problem%20is%20in%20the%20pusher%20that%20doesn%27t%20send%20the%20update%20to%20device%20B.%20Instead%20of%20patching%20up%20the%20issue%2C%20we%20should%20fix%20the%20pusher.) that we're patching up the issue not fixing the root cause, instead we should fix the pusher data where `lastVisibleActionCreated` is updated that is less then or equal to `lastReadTime`

@sakluger Here we have to do 2 things:

1. Assign an internal engineer to the issue so that they can investigate the Pusher issue in backend and fix that first
2. Once Pusher issue will be fixed from the backend then we can assign @bernhardoj, so that they can revert the code of this [PR](https://github.com/Expensify/App/pull/36950)

**Comment by jayeshmangwani** [comment] 2024-04-02 05:49
@bernhardoj's [Proposal](https://github.com/Expensify/App/issues/38778#issuecomment-2014409743) looks good to me. First, we have to revert the https://github.com/Expensify/App/pull/36950, And then we need to fix from the backend of lastVisibleActionCreated data for the #announce room and Workspace Chat

**Comment by jayeshmangwani** [comment] 2024-04-02 05:50
@bernhardoj's [Proposal](https://github.com/Expensify/App/issues/38778#issuecomment-2014409743) looks good to me. First, we have to revert the https://github.com/Expensify/App/pull/36950, And then we need to fix from the backend of lastVisibleActionCreated data for the #announce room and Workspace Chat


🎀 👀 🎀 C+ reviewed

**Comment by jayeshmangwani** [comment] 2024-04-02 05:59
@Julesssss , this is a [summary](https://github.com/Expensify/App/issues/38778#issuecomment-2024936566) of the selected [proposal](https://github.com/Expensify/App/issues/38778#issuecomment-2024936566); we have added this [code](https://github.com/Expensify/App/blob/a4d01a87b242eef06af37db965bd135745e342e5/src/libs/SidebarUtils.ts#L263-L264) in [this](https://github.com/Expensify/App/pull/36950) PR to fix this [issue](https://github.com/Expensify/App/issues/36013), https://github.com/Expensify/App/issues/36013 was causing because of lastVisibleActionCreated data does not update correctly from the backend; That [PR](https://github.com/Expensify/App/pull/36950) caused this issue; we should fix the lastVisibleActionCreated from the backend(Pusher) when we delete the message from the #announce room and workspace chat and should remove ` !!report.lastActorAccountID` condition from setting the `isUnread`

**Comment by Julesssss** [comment] 2024-04-02 11:49
Thanks. The plan sounds good. 

@sakluger FYI we'll need to get this attached to collect/control to keep this moving internally. It feels pretty minor and likely won't be in my list of priorities for a while

**Comment by sakluger** [comment] 2024-04-03 23:17
@Julesssss I added to wave-collect as polish. It seems appropriate for that wave because requesting money is a common collect action.

**Comment by sakluger** [comment] 2024-04-09 22:56
@Julesssss are you able to review the proposal that @jayeshmangwani selected and give it a 👍 or 👎? Even if it's minor, I'd like to keep it moving forward since we have a contributor ready to fix it.

**Comment by Julesssss** [comment] 2024-04-10 08:36
Hey @sakluger, @jayeshmangwani's plan is good, but I don't want to approve it yet. It could be a while before the backend fix is applied and by then the front-end solution might not be relevant. 

I will get to this eventually, but it could be a month. I'm also happy to unassign and we can find someone else with more time. but the backend work needs to be completed before we approve the proposal.

**Comment by sakluger** [comment] 2024-04-16 22:29
Ah, thanks for clarifying @Julesssss, I didn't understand that the proposal was held on BE work. I'll move this to Monthly priority for now.

**Comment by mvtglobally** [comment] 2024-04-18 16:03
Issue not reproducible during KI retests. (First week)

**Comment by sakluger** [comment] 2024-05-02 18:05
I asked in the original bug report thread if the bug is still occurring. If not, we can close.

**Comment by sakluger** [comment] 2024-05-02 18:47
@puneetlath (who reported the issue originally) says that this is still reproduceable. He said:

> It seems that if there is a chat message and you mark it as unread, then it does show up as bold, but if it's just a money request, and you mark that as unread, it doesn't show up as bold.

**Comment by sakluger** [comment] 2024-05-17 07:56
No update

**Comment by Julesssss** [comment] 2024-06-17 08:26
This is unlikely to get fixed for a while TBH. Too many internal high-priority projects

**Comment by mallenexpensify** [comment] 2024-07-08 23:43
Trying to find a volunteer in  #wave-collect
https://expensify.slack.com/archives/C036QM0SLJK/p1720482169207219

**Comment by mallenexpensify** [comment] 2024-07-17 00:12
Closing [per internal discussion](https://expensify.slack.com/archives/C036QM0SLJK/p1720482169207219), Puneet will reopen if the bugs reoccur

**Closed** 2024-07-17 00:14 UTC
Labels: External, Monthly, Bug
