### ISSUE TITLE
[HOLD for payment 2023-10-02] [HOLD for payment 2023-09-29] [$500] [mWeb] - Chat - Context menu doesn't close after user goes to the previous page

### ISSUE THREAD

**Issue by izarutskaya** [Expensify/App#26178] opened 2023-08-29 11:17 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Open a chat
2. Send a message
3. Reply in thread of the message sent
4. Hold on the last sent message inside the thread
5. Click on the back button

## Expected Result:
The context menu should close after user goes back to the previous page

## Actual Result:
The context menu remains open after user goes back to the previous page

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [x] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [ ] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** v1.3.58-1

**Reproducible in staging?:** Y

**Reproducible in production?:** N

**If this was caught during regression testing, add the test name, ID and link from TestRail:**

**Email or phone of affected tester (no customers):**

**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/115492554/37f6cf64-e8b2-4b10-bda1-8a3d4e881114

https://github.com/Expensify/App/assets/115492554/eb98169c-00af-43b3-937a-3c16f5ea66a1

**Expensify/Expensify Issue URL:**

**Issue reported by:** @Nathan-Mulugeta

**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1693298251936699

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01b3a9d92fe2b1c968</li>
        <li>Upwork Job ID: 1701151842381410304</li>
        <li>Last Price Increase: 2023-09-11</li>
<li>Automatic offers: </li>
<ul>
<li>tienifr | Contributor | 26629317</li>
<li>Nathan-Mulugeta | Reporter | 26629320</li>
<li>aimane-chnaif | Contributor | 26629407</li>
</ul></li>
    </ul>
</details>

**Comment by Nathan-Mulugeta** [comment] 2023-08-29 13:51
I don't think it is the same issue, this is found only on staging which means it has been introduced yesterday when the new release was pushed.

**Comment by youssef-lr** [comment] 2023-08-29 21:16
I think this might be the offending PR https://github.com/Expensify/App/pull/24515 cc @alitoshmatov

**Comment by alitoshmatov** [comment] 2023-08-29 21:19
I think you meant @allroundexperts

**Comment by youssef-lr** [comment] 2023-08-29 21:19
Yup sorry!

**Comment by luacmartins** [comment] 2023-08-29 23:20
Seems to be a regression from https://github.com/Expensify/App/pull/26045. Reverting that PR fixes this particular issue.

**Comment by luacmartins** [comment] 2023-08-29 23:28
Actually, I'm not sure anymore. I can't seem to reproduce the issue on main again.

**Comment by luacmartins** [comment] 2023-08-29 23:31
Anyway, I think this is small enough to be demoted to NAB.

**Comment by maddylewis** [comment] 2023-08-31 18:01
humm, i don't believe im able to repro this one either now.

**Comment by Nathan-Mulugeta** [comment] 2023-09-01 04:59
Hey @maddylewis I am still able to reproduce this, I think this is still an issue

**Comment by youssef-lr** [comment] 2023-09-05 12:11
I'm unable to get to this right now, will do after I'm done with higher priority issues.

**Comment by youssef-lr** [comment] 2023-09-11 08:32
I can still reproduce this, I think we can make this external.

**Comment by youssef-lr** [comment] 2023-09-12 11:06
Sounds good @tienifr, assigning you.

**Comment by Pujan92** [comment] 2023-09-19 15:37
I think regression https://github.com/Expensify/App/issues/27782 from this PR. @aimane-chnaif @tienifr can you plz check once?
Reproduction step is when the ReportActionsView is loading and opens RHN to unfocus the ReportActionsView

https://github.com/Expensify/App/assets/14358475/40e546df-8138-4bc0-8abe-94fc8933bd13

**Comment by maddylewis** [comment] 2023-10-02 13:37
## Payments:
- [ ] Reporting bonus: @Nathan-Mulugeta ($50 via Upwork)
- [ ] Contributor: @tienifr ($500 via Upwork)
- [ ] C+: @aimane-chnaif ($500 via Upwork)

**Comment by maddylewis** [comment] 2023-10-02 13:37
@aimane-chnaif - will you review this checklist when you have a chance? thanks https://github.com/Expensify/App/issues/26178#issuecomment-1733249477

**Comment by Nathan-Mulugeta** [comment] 2023-10-02 13:41
Hey @maddylewis this GH was created on Aug 29, thus prior to the bounty decrease announcement. The right amount for reporting bonus should be $250 not $50. Thanks :)

**Comment by maddylewis** [comment] 2023-10-04 20:29
updated reporting payment for @Nathan-Mulugeta - everyone is paid / closing

**Closed by maddylewis** 2023-10-04 20:29 UTC
Labels: External, Engineering, Daily, Awaiting Payment, Bug
