### ISSUE TITLE
[$500] Android - Empty space is created when selecting emojis and tapping on composer

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#27278] opened 2023-09-12 18:19 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Open any report
2. Select some emojis from emoji picker
3. Tap on composer
4. Observe empty spaces are created

## Expected Result:
Empty spaces should not be created.

## Actual Result:
 Empty spaces are created

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [ ] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 1.3.68.12
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/93399543/6b38197d-5087-4300-b0e0-8d82617952d3

https://github.com/Expensify/App/assets/93399543/9c3843aa-505c-478d-9855-0a723eff29fc

**Expensify/Expensify Issue URL:**
**Issue reported by:** @Krishna2323 
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1694275250333439

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~0154bce4673f2e002d</li>
        <li>Upwork Job ID: 1701661892127694848</li>
        <li>Last Price Increase: 2023-09-12</li>
    </ul>
</details>

**Comment by jliexpensify** [comment] 2023-09-12 22:47
I'm having issues reproducing on Android v.68-11 (one version behind). I do see a space but I think it depends on the emoji selected - e.g. the faces tend not to leave spaces, where the hands might (possibly due to spacing around the emoji?)

**Comment by pradeepmdk** [comment] 2023-09-13 07:07
i think this dub for this https://github.com/Expensify/App/issues/26709

**Comment by jliexpensify** [comment] 2023-09-13 07:34
Yep, you're right! The other GH was created on the 5th, whereas this one was reported on the 9th. Closing this as a dupe.

**Closed by jliexpensify** 2023-09-13 07:34 UTC
Labels: External, Daily, Help Wanted, Bug
