### ISSUE TITLE
[HOLD for payment 2024-11-11] [$250] Distance - Receipt disappears when dismissing distance editor after receipt is generated

### ISSUE THREAD

**Issue by izarutskaya** [Expensify/App#48630] opened 2024-09-05 10:39 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 9.0.29-0
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**If this was caught during regression testing, add the test name, ID and link from TestRail:** applausetester+kh010901@applause.expensifail.com
**Email or phone of affected tester (no customers):** applausetester+kh010901@applause.expensifail.com
**Issue reported by:** Applause-Internal team

## Action Performed:
1. Go to staging.new.expensify.com
2. Go to workspace chat.
3. Go offline.
4. Submit a distance expense.
5. Go to transaction thread.
6. Click Distance.
7. Go online.
8. After the receipt in the background is generated, dismiss the distance editor by clicking RHP back button.

## Expected Result:
The receipt in the transaction thread will remain generated.

## Actual Result:
The receipt in the transaction thread turns to placeholder thumbnail.
Sometimes, the map loads, but the map is not clickable (it is still in the loading state and not generating the actual receipt).

This issue also happens when opening distance editor right after the distance expense is submitted before the receipt is generated.

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [x] Android: mWeb Chrome
- [x] iOS: Native
- [x] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

https://github.com/user-attachments/assets/a07d59b4-5b40-41e4-809a-fd5156c25484

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~021832157502208534261</li>
        <li>Upwork Job ID: 1832157502208534261</li>
        <li>Last Price Increase: 2024-10-18</li>
<li>Automatic offers: </li>
<ul>
<li>ikevin127 | Reviewer | 104586775</li>
<li>wildan-m | Contributor | 104586777</li>
</ul></li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @isabelastisser</details>

**Comment by nkdengineer** [comment] 2024-09-05 11:31
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
The receipt in the transaction thread turns to placeholder thumbnail.
Sometimes, the map loads, but the map is not clickable (it is still in the loading state and not generating the actual receipt).

### What is the root cause of that problem?
When we update the waypoint, we pass transaction change as `waypoints` and `routes`

https://github.com/Expensify/App/blob/a6e6ae67e04b80b8a245503fbef945e48ceb53c4/src/libs/actions/IOU.ts#L3064-L3067

Then the error field contains `waypoints` and `routes` fields
https://github.com/Expensify/App/blob/a6e6ae67e04b80b8a245503fbef945e48ceb53c4/src/libs/actions/IOU.ts#L2456

After the API is complete, BE returns the error of `route` field and when we clear the error only `route` error is cleared

https://github.com/Expensify/App/blob/a6e6ae67e04b80b8a245503fbef945e48ceb53c4/src/libs/actions/Transaction.ts#L404

Then the receipt is displayed as the default image
https://github.com/Expensify/App/blob/a6e6ae67e04b80b8a245503fbef945e48ceb53c4/src/components/ReportActionItem/ReportActionItemImage.tsx#L84
### What changes do you think we should make in order to solve the problem?
We have some solutions to fix this issue

1. Update `hasError` in the same way we display the error in `MoneyRequestView` [here](https://github.com/Expensify/App/blob/a6e6ae67e04b80b8a245503fbef945e48ceb53c4/src/components/ReportActionItem/MoneyRequestView.tsx#L408-L410)

```
const hasErrors = !isEmptyObject(transaction?.errors) || !isEmptyObject(transaction?.errorFields.route);
```

https://github.com/Expensify/App/blob/a6e6ae67e04b80b8a245503fbef945e48ceb53c4/src/components/ReportActionItem/ReportActionItemImage.tsx#L83

2. When we clear the transaction error here we can also clear the `errorFields` of `routes` and `waypoints`

https://github.com/Expensify/App/blob/a6e6ae67e04b80b8a245503fbef945e48ceb53c4/src/libs/actions/Transaction.ts#L404

3. We can check if we update the waypoint here we will not update the `errorFields` in failure data because it will be returned from BE to do that we can check in `getUpdateMoneyRequestParams` and `getUpdateTrackExpenseParams` or add an extra param to decide to update the `errorFields` in failure data or not. or add the `route` errorFields if we edit the waypoint

https://github.com/Expensify/App/blob/a6e6ae67e04b80b8a245503fbef945e48ceb53c4/src/libs/actions/IOU.ts#L3064-L3067

### What alternative solutions did you explore? (Optional)

**Comment by ikevin127** [comment] 2024-09-07 05:26
♻️ Will start reviewing the proposal in ~12h.

**Comment by ikevin127** [comment] 2024-09-08 01:01
@nkdengineer Thanks for the proposal. I was able to reproduce the issue but I'm struggling with applying the solution, specifically the changes suggested at step 3 and without that the issue is still reproducible therefore I cannot verify the proposal.

Are you able to provide a testing branch with the working solution ? That would help verifying the solution and if the RCA matches the working solution then I would be able to finalize the proposal review. Thanks!

**Comment by nkdengineer** [comment] 2024-09-09 05:25
@ikevin127 Ahh, sorry I proposed another bug. [Updated](https://github.com/Expensify/App/issues/48630#issuecomment-2331285484) my proposal for the original bug.

**Comment by ikevin127** [comment] 2024-09-11 01:15
@nkdengineer Thanks for the update, I tested the solution and while it seems to fix the issue at first - the solution is not reliable because is breaking functionality that was working as expected before the change:
- check out the attached video where I show the discrepancy between local dev (proposed solution) vs current staging

<details>
<summary>Video</summary>

https://github.com/user-attachments/assets/51b3554d-ca20-4fad-952c-7310c683715f

</details>

Additionally, while going back online with the RHP open I had instances where the map receipt in the background report would show 404 not found:

<img width="1000" alt="Screenshot 2024-09-10 at 18 03 30" src="https://github.com/user-attachments/assets/e4e242ae-6e29-4764-a60f-52e737e4976c">

##

I think a solution that would be acceptable for this issue should not break functionality that currently works well.

In addition, if proposing changes to currently existing code logic, some steps should be included for the reviewers to verify that current functionality is not affected by the proposed changes.

**Comment by isabelastisser** [comment] 2024-09-13 17:16
Waiting for new proposals!

**Comment by ikevin127** [comment] 2024-09-14 02:51
💰 Looking for proposals! Please keep in mind the previous proposal's pitfalls detailed in https://github.com/Expensify/App/issues/48630#issuecomment-2342426929 review.

**Comment by isabelastisser** [comment] 2024-09-17 19:10
Still waiting for proposals.

**Comment by ikevin127** [comment] 2024-09-18 19:29
💰 Still looking for proposals! Please keep in mind the previous proposal's pitfalls detailed in https://github.com/Expensify/App/issues/48630#issuecomment-2342426929 review.

**Comment by wildan-m** [comment] 2024-09-21 07:00
## Proposal

### Please re-state the problem that we are trying to solve in this issue.

Receipt disappears when dismissing distance editor after it is generated.

### What is the root cause of that problem?

TransactionBackup routes are not being updated when online, causing the receipt route to disappear when the modal is dismissed.

### What changes do you think we should make in order to solve the problem?
This solution will require backend modifications.

Calculate transaction backup routes when there are pending waypoints, valid routes, and the system is online.

Create new API endpoint similar to `GET_ROUTE_FOR_DRAFT` but for backup.

```tsx
    GET_ROUTE_FOR_BACKUP: 'GetRouteForBackup',
```

Add new type to define transactionStates

```tsx
    TRANSACTION_STATE: {
        CURRENT: 'current',
        DRAFT: 'draft',
        BACKUP: 'backup',
    }
```

modify `useFetchRoute` to accept new parameter `transactionState`
```tsx
export default function useFetchRoute(transaction: OnyxEntry<Transaction>, waypoints: WaypointCollection | undefined, action: IOUAction, transactionState: TransactionState = CONST.TRANSACTION_STATE.CURRENT) {
...............
    useEffect(() => {
        if (isOffline || !shouldFetchRoute || !transaction?.transactionID) {
            return;
        }

        TransactionAction.getRoute(transaction.transactionID, validatedWaypoints, transactionState);
    }, [shouldFetchRoute, transaction?.transactionID, validatedWaypoints, isOffline, action]);
```

Modify `getOnyxDataForRouteRequest` and `getRoute` to accept new `transactionState` param
```tsx
function getOnyxDataForRouteRequest(transactionID: string, transactionState: TransactionState = CONST.TRANSACTION_STATE.CURRENT): OnyxData {
    let keyPrefix;
    switch (transactionState) {
        case CONST.TRANSACTION_STATE.DRAFT:
            keyPrefix = ONYXKEYS.COLLECTION.TRANSACTION_DRAFT;
            break;
        case CONST.TRANSACTION_STATE.BACKUP:
            keyPrefix = ONYXKEYS.COLLECTION.TRANSACTION_BACKUP;
            break;
        case CONST.TRANSACTION_STATE.CURRENT:
        default:
            keyPrefix = ONYXKEYS.COLLECTION.TRANSACTION;
            break;
    }


....


function getRoute(transactionID: string, waypoints: WaypointCollection, routeType: TransactionState = CONST.TRANSACTION_STATE.CURRENT) {
    if (routeType === CONST.TRANSACTION_STATE.BACKUP)
    {
        mockGetBackupRoute(transactionID);
    }

    const parameters: GetRouteParams = {
        transactionID,
        waypoints: JSON.stringify(waypoints),
    };

    let command;
    switch (routeType) {
        case 'draft':
            command = READ_COMMANDS.GET_ROUTE_FOR_DRAFT;
            break;
        case 'current':
            command = READ_COMMANDS.GET_ROUTE;
            break;
        case 'backup':
            command = READ_COMMANDS.GET_ROUTE_FOR_BACKUP;
            break;
        default:
            throw new Error('Invalid route type');
    }
.......
```

Adjust useFetchRoute usage:
src/pages/iou/request/step/IOURequestStepConfirmation.tsx
```tsx
    useFetchRoute(transaction, transaction?.comment?.waypoints, action, IOUUtils.shouldUseTransactionDraft(action) ? CONST.TRANSACTION_STATE.DRAFT : CONST.TRANSACTION_STATE.CURRENT);
```

call `useFetchRoute` for backup in addition to current fetch, we can't use current transaction waypoints since that waypoints can be modified while offline.
src/pages/iou/request/step/IOURequestStepDistance.tsx
```tsx
    const backupWaypoints = !!transactionBackup?.pendingFields?.waypoints ? transactionBackup?.comment?.waypoints : undefined;

    const { shouldFetchRoute, validatedWaypoints } = useFetchRoute(transaction, waypoints, action, IOUUtils.shouldUseTransactionDraft(action) ? CONST.TRANSACTION_STATE.DRAFT : CONST.TRANSACTION_STATE.CURRENT);
    useFetchRoute(transactionBackup, backupWaypoints, action, CONST.TRANSACTION_STATE.BACKUP);
```

[Branch for this solution](https://github.com/Expensify/App/compare/main...wildan-m:wildan/fix/48630-calculate-route-for-pending-trx-backup?expand=1)

### What alternative solutions did you explore? (Optional)
N/A

**Comment by ikevin127** [comment] 2024-09-21 21:40
♻️ Reviewing this and asking the team what's the procedure when proposals request BE changes - will get back with feedback next week.

**Comment by isabelastisser** [comment] 2024-09-26 13:42
Hey @ikevin127, can you please provide an update? Thanks!

**Comment by ikevin127** [comment] 2024-09-26 20:52
Sure, in the meantime I asked on **#contributor-plus** Slack channel [thread](https://expensify.slack.com/archives/C02NK2DQWUX/p1727383829101669) about how we should proceed in cases like the latest proposal given that it suggests BE changes.

♻️ Will get back with an answer by EOD (PST).

**Comment by ikevin127** [comment] 2024-09-26 22:53
Without actually testing it, since it's missing the BE part: based on reviewing the technical aspects of the proposal and based on the response received in the Slack thread mentioned above, @wildan-m's [proposal](https://github.com/Expensify/App/issues/48630#issuecomment-2365034676) looks good to me as the RCA makes sense and the proposed solution seems valid based on the fact that we do something similar for `GET_ROUTE_FOR_DRAFT`.

Therefore I'll defer this to the assigned CME for the BE part and further validation of the proposal.

cc 

🎀👀🎀 C+ reviewed

**Comment by Gonals** [comment] 2024-09-30 16:10
It'll be a few days until I get to the BE of this

**Comment by ikevin127** [comment] 2024-09-30 22:26
Not overdue, we're working on FE / BE pull requests.

**Comment by ikevin127** [comment] 2024-10-03 20:02
Not overdue, we're still working on FE / BE pull requests.

**Comment by ikevin127** [comment] 2024-10-07 20:02
I think we're still working on FE / BE pull requests. @Gonals Any updates from the BE side ?

**Comment by Gonals** [comment] 2024-10-09 08:07
> Any updates from the BE side ?

Travel stuff is taking priority, so it might still be a few days. Sorry!

**Comment by ikevin127** [comment] 2024-10-11 17:23
Not overdue, we're working on the PRs 👍

**Comment by ikevin127** [comment] 2024-10-14 20:02
Not overdue, still working on the PRs 👍

**Comment by isabelastisser** [comment] 2024-10-18 17:20
@ikevin127, can you please share an update? thanks!

**Comment by ikevin127** [comment] 2024-10-18 17:41
> Travel stuff is taking priority, so it might still be a few days. Sorry!

@Gonals Any updates on the BE side of this issue ? If not maybe we can put the issue on HOLD for **Gonals** so we can avoid `Overdue`.

**Comment by Gonals** [comment] 2024-10-21 10:34
Getting to it today!

**Comment by Gonals** [comment] 2024-10-21 10:51
@wildan-m, how will `GET_ROUTE_FOR_BACKUP` differ from `GET_ROUTE_FOR_DRAFT`? Do you expect to pass the same parameters and receive the same response? If so, why not calling `GET_ROUTE_FOR_DRAFT` in this flow?

**Comment by wildan-m** [comment] 2024-10-21 12:24
@Gonals the only difference is target onyx key from the server. it should target backup onyx key

**Comment by ikevin127** [comment] 2024-10-21 18:45
Not overdue, we're working on the BE side after which the FE pull request will follow.

**Comment by wildan-m** [comment] 2024-10-22 02:25
> If so, why not calling GET_ROUTE_FOR_DRAFT in this flow?

@Gonals calling that API will update the key for draft not for back up

**Comment by Gonals** [comment] 2024-10-24 09:45
Gotcha. Backend PR incoming

**Comment by Gonals** [comment] 2024-10-24 10:10
Backend PR in review

**Comment by ikevin127** [comment] 2024-10-24 22:06
Not overdue, BE pull request is in review after which the FE pull request will follow.

**Comment by Gonals** [comment] 2024-10-25 09:32
BE deployed to staging. FE can now test with it

**Comment by wildan-m** [comment] 2024-10-25 13:38
Re-testing && creating the PR....

**Comment by wildan-m** [comment] 2024-10-25 13:44
@Gonals what is the API name? is it `GetRouteForBackup` ?

**Comment by wildan-m** [comment] 2024-10-25 14:46
Ah, seems dev server doesn't have that API, the API exists after switch to staging

@ikevin127 @Gonals Please confirm that the scope of this issue is only to restore the map

If the user go back without save the transaction, some fields would still missing. (e.g. distance, amount)

The missing fields not come from `GetRoute` or `GetRouteForBackup` but it's come from `openReport` API

`openReport` API only update the transaction not its backup.

What can we do?
1. There should be a way to also update the transaction backup missing fields, maybe calling `GetRoute/GetRouteForBackup` should also update the missing fields? (Require other BE changes)
2. Continue creating the PR. scope this issue to only show map and resolve other missing fields in separate issue.


Which option we should choose?

<details><summary>Backup (Left) vs Current Transaction (Right)</summary>

![image](https://github.com/user-attachments/assets/8145e865-4b54-4f65-a4da-ae0a509f244d)

</details>

**Comment by ikevin127** [comment] 2024-10-25 18:21
> 2. Continue creating the PR. scope this issue to only show map and resolve other missing fields in separate issue.

This would be my choice since pushing more BE changes would only extend the duration of fixing this specific issue. Once @Gonals comes back with the details of the API pull request changes and you have the required data to move forward with the PR and implement the fix, we should be all good.

**Comment by wildan-m** [comment] 2024-10-26 09:42
@ikevin127 The PR is Ready https://github.com/Expensify/App/pull/51519

@Gonals The previous found issue https://github.com/Expensify/App/issues/48630#issuecomment-2438017630 can be resolved by calling `openReport(transaction?.reportID)` after the backup restored. This way we wouldn't need to change BE.

**Comment by ikevin127** [comment] 2024-10-31 17:32
We discussed the upcoming regression in the PR (https://github.com/Expensify/App/pull/51519#discussion_r1817955794) and we decided to ship it like this because the fix for it was out of scope for the issue.

Therefore even though this is technically a regression of our PR, we decided not to count it as regression when it comes to compensation.

**Comment by ikevin127** [comment] 2024-11-05 00:12
# BugZero Checklist:

- [ ] **[Contributor]** Classify the bug:

<details>
<summary>Bug classification</summary>


Source of bug:
  - [ ] 1a. Result of the original design (eg. a case wasn't considered)
  - [ ] 1b. Mistake during implementation
  - [ ] 1c. Backend bug
  - [ ] 1z. Other:

Where bug was reported:
  - [ ] 2a. Reported on production
  - [ ] 2b. Reported on staging (deploy blocker)
  - [ ] 2c. Reported on a PR
  - [ ] 2z. Other:

Who reported the bug:
  - [ ] 3a. Expensify user
  - [ ] 3b. Expensify employee
  - [ ] 3c. Contributor
  - [ ] 3d. QA
  - [ ] 3z. Other:

</details>

- [ ] **[Contributor]** The offending PR has been commented on, pointing out the bug it caused and why, so the author and reviewers can learn from the mistake.

    Link to comment:

- [ ] **[Contributor]** If the regression was CRITICAL (e.g. interrupts a core flow) A discussion in [#expensify-open-source](https://app.slack.com/client/E047TPA624F/C01GTK53T8Q) has been started about whether any other steps should be taken (e.g. updating the PR review checklist) in order to catch this type of bug sooner.

    Link to discussion:

- [ ] **[Contributor]** If it was decided to create a regression test for the bug, please propose the [regression test](https://github.com/Expensify/App/blob/main/contributingGuides/REGRESSION_TEST_BEST_PRACTICES.md) steps using the template below to ensure the same bug will not reach production again.

<details>
<summary>Regression Test Proposal Template</summary>


- [ ] **[BugZero Assignee]** Create a GH issue for creating/updating the regression test once above steps have been agreed upon.

    Link to issue:

## Regression Test Proposal
### Precondition:


-

### Test:


1.

Do we agree 👍 or 👎


</details>

**Comment by wildan-m** [comment] 2024-11-06 14:13
@Gonals for consistency and to avoid potential dev only bug, I think it's better if GET_ROUTE_FOR_BACKUP endpoint also deployed to BE dev server

**Comment by isabelastisser** [comment] 2024-11-11 16:11
@ikevin127 @wildan-m, the payments are processed in Upwork and the regression test issue is created. Is there an ongoing discussion here or can I close this issue now? Thanks!

**Comment by wildan-m** [comment] 2024-11-12 01:46
I think we can close it, the follow-up issue will be handled separately. https://github.com/Expensify/App/issues/51785

**Comment by isabelastisser** [comment] 2024-11-12 18:18
All set!

**Closed by isabelastisser** 2024-11-12 18:18 UTC
Labels: External, Weekly, Awaiting Payment, Bug
