### ISSUE TITLE
[HOLD for payment 2023-06-30] [$1000] iOS - The last colour remains green when scanning magic code

### ISSUE THREAD

**Issue by kavimuru** [Expensify/App#20675] opened 2023-06-13 13:10 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1 Open app sign in page
2 Long press the magic code section, then tap **Scan Code**
3.Scan an incorrect code

## Expected Result: 
the error is in red color

## Actual Result: 
the last color remains green

## Workaround:
Can the user still use Expensify without this being fixed? Have you informed them of the workaround?

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [x] iOS / native
- [ ] iOS / Safari
- [ ] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 1.3.25-1
**Reproducible in staging?:** needs reproduction ( My iOS version does not support this feature)
**Reproducible in production?:** needs reproduction 
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/43996225/7ecefed3-29ae-4d9e-8c6e-e82dac645862

**Expensify/Expensify Issue URL:**
**Issue reported by:** @narzullome
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1686151703526889

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01c3ea97d84a363810</li>
        <li>Upwork Job ID: 1669537009549963264</li>
        <li>Last Price Increase: 2023-06-16</li>
    </ul>
</details>

**Comment by muttmuure** [comment] 2023-06-16 02:45
![IMG_0211](https://github.com/Expensify/App/assets/46995600/d33ab259-7f40-4c39-879e-db7a23cdf24b)

Reproduced

**Comment by manjesh-yadav** [comment] 2023-06-16 04:26
## Proposal

### Please re-state the problem that we are trying to solve in this issue.

- Last input field of the magic code shows a green border even error occurred

### What is the root cause of that problem?

- This happens because the last input field is in focus mode and when the input box is in focus mode the border color is set to green

### What changes do you think we should make in order to solve the problem?

When focused on magic color of input of before apply green color we have to also check if has error or not

https://github.com/Expensify/App/blob/7b00c47ee7debf7137417ac768efe8d4c6b872d0/src/components/MagicCodeInput.js#L304C19-L312

changes

`focusedIndex === index && !props.hasError ? styles.borderColorFocus : {},`



### What alternative solutions did you explore? (Optional)
N/A

**Comment by manjesh-yadav** [comment] 2023-06-16 04:27
Contributor details
Your Expensify account email: manjesh.work@gmail.com
Upwork Profile Link: https://www.upwork.com/freelancers/~01e284c7f27db8fb99

**Comment by manjesh-yadav** [comment] 2023-06-20 15:26
@allroundexperts @Gonals any update, do I get assigned or waiting for another proposal?

**Comment by s77rt** [comment] 2023-06-20 16:55
Taking this as C+

**Comment by manjesh-yadav** [comment] 2023-06-21 08:34
Thanks, will submit pr today

**Comment by manjesh-yadav** [comment] 2023-06-21 13:22
Hi @Gonals @allroundexperts, PR is ready for review.

**Comment by muttmuure** [comment] 2023-07-03 13:50
Offers sent to @manjesh-yadav and @allroundexperts

**Comment by manjesh-yadav** [comment] 2023-07-03 13:57
Offer accepted @muttmuure

**Comment by muttmuure** [comment] 2023-07-06 09:28
@narzullome sorry about that! Invited

**Comment by narzullome** [comment] 2023-07-06 13:16
@muttmuure accepted

**Comment by muttmuure** [comment] 2023-07-11 16:59
@narzullome it looks like you withdrew your offer - mind reapplying?

**Comment by muttmuure** [comment] 2023-07-11 17:02
@allroundexperts paid

@narzullome feel free to ping me when you are ready to get paid for this in Upwork.

**Comment by narzullome** [comment] 2023-07-12 05:35
@muttmuure its on archived now 
I can not reapply for the same job 2 times 
can u send another offer 
![telegram-cloud-photo-size-2-5294539338811558929-y](https://github.com/Expensify/App/assets/134583481/d7eec4fc-c0a1-4317-9bef-9d1fbbb44913)

**Comment by narzullome** [comment] 2023-07-15 10:01
@muttmuure waiting new offer

**Comment by narzullome** [comment] 2023-07-18 08:49
@muttmuure friendly bump

**Comment by narzullome** [comment] 2023-07-22 00:18
@muttmuure accepted

**Comment by narzullome** [comment] 2023-07-23 05:22
@muttmuure friendly bump

**Comment by muttmuure** [comment] 2023-07-23 22:39
@narzullome paid, closing out

**Closed by muttmuure** 2023-07-23 22:39 UTC
Labels: External, Daily, Awaiting Payment, Bug
