### ISSUE TITLE
[HOLD #40412] Live MD - No top margin for only emojis inside the expanded compose box

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#40472] opened 2024-04-18 15:45 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.63-0
**Reproducible in staging?:** Y
**Reproducible in production?:** N
**If this was caught during regression testing, add the test name, ID and link from TestRail:** N/A
**Issue reported by:** Applause - Internal Team

## Action Performed:
1. Navigate to staging.new.expensify.com
2. Open any chat
3. Add an emoji only
4. Enter a new line
5. Expand the compose box

## Expected Result:
There is a margin between the emoji inside the compose box and the top border of the compose box

## Actual Result:
There is space between the emoji inside the compose box and the top border of the compose box

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [x] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details> 

https://github.com/Expensify/App/assets/78819774/30544018-b232-4e64-8e97-b58ef480ad7c

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by lanitochka17** [comment] 2024-04-18 15:50
@roryabraham  FYI I haven't added the External label as I wasn't 100% sure about this issue. Please take a look and add the label if you agree it's a bug and can be handled by external contributors

**Comment by MahmudjonToraqulov** [comment] 2024-04-18 15:53
This will be fixed with this [Proposal](https://github.com/Expensify/App/issues/40412#issuecomment-2063538025)

**Comment by MahmudjonToraqulov** [comment] 2024-04-18 15:56
### Result
![photo_2024-04-18_20-56-01](https://github.com/Expensify/App/assets/91727683/5d30abd8-660c-41b3-a2e1-8ce1998f8aef)

**Comment by roryabraham** [comment] 2024-04-18 18:46
calling this NAB and putting it on HOLD for https://github.com/Expensify/App/issues/40412 as it appears to share the same root cause.

**Comment by roryabraham** [comment] 2024-04-22 21:51
Still on HOLD - making this a weekly while we wait for https://github.com/Expensify/App/issues/40412 to land

**Comment by roryabraham** [comment] 2024-05-01 21:20
Still on HOLD

**Comment by roryabraham** [comment] 2024-05-11 17:36
Still on HOLD

**Comment by roryabraham** [comment] 2024-05-23 20:31
still on HOLD

**Comment by roryabraham** [comment] 2024-07-27 17:06
Verified that this is fixed

<img width="1201" alt="image" src="https://github.com/user-attachments/assets/9357eddc-e8bf-41d1-af60-6539adee290a">

**Closed by roryabraham** 2024-07-27 17:06 UTC
Labels: Engineering, Monthly, Overdue
