### ISSUE TITLE
[$500] Web - Video - Console error shows up when dismissing video preview after viewing full screen

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#36955] opened 2024-02-20 21:35 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.43-3
**Reproducible in staging?:** Y
**Reproducible in production?:** N
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** Applause - Internal Team
**Slack conversation:**

## Action Performed:
1. Go to staging.new.expensify.com
2. Go to any chat
3. Upload a video but do not send it
4. Click on the full screen icon
5. Click on the full screen icon again to return to normal view
6. Close the preview
7. Go to a different chat

## Expected Result:
No console error will show up

## Actual Result:
No console error will show up

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details> 

https://github.com/Expensify/App/assets/78819774/04cc9a7f-cd4d-4545-9283-c5f7561d920a

[log.txt](https://github.com/Expensify/App/files/14351353/log.txt)

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by lanitochka17** [comment] 2024-02-20 21:36
We think that this bug might be related to #vip-vsp
CC @quinthar

**Comment by francoisl** [comment] 2024-02-20 22:45
@puneetlath I think since it doesn't crash the app nor prevent from playing the videos or doing anything, this doesn't need to  be a blocker and can be a Daily instead?

**Comment by puneetlath** [comment] 2024-02-20 22:53
Sounds good.

**Comment by aneequeahmad** [comment] 2024-02-21 04:17
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
Console error appears that Video component has not loaded yet when dismissing video preview after viewing full screen
### What is the root cause of that problem?
### **unloadVideo() function called at start in resetVideoPlayerData()**
When the video preview is in full screen the video starts playing and then exit full screen and the preview is closed and some other chat is clicked the `currentReportID` changes and  `resetVideoPlayerData` function is invoked
 
 In `resetVideoPlayerData` function `unloadVideo()` is called right in start before setting `setCurrentlyPlayingURL(null), setSharedElement(null), setOriginalParent(null), currentVideoPlayerRef.current = null; ` which causes the console error that video component has not loaded.

https://github.com/Expensify/App/blob/ea0c07b7671bdcde20485c48f841212d7f1a925b/src/components/VideoPlayerContexts/PlaybackContext.js#L77-L84

### What changes do you think we should make in order to solve the problem?

We should put `unloadVideo()` code right after `setCurrentlyPlayingURL(null), setSharedElement(null), setOriginalParent(null), currentVideoPlayerRef.current = null;`

### What alternative solutions did you explore? (Optional)
N/A

**Comment by bernhardoj** [comment] 2024-02-21 05:18
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
Console error is shown when changing chat after closing an add video attachment preview.

### What is the root cause of that problem?
If we are trying to add a new video attachment and play it (toggling full screen plays the video), the video player ref will be set to the video player of the attachment preview modal. 
https://github.com/Expensify/App/blob/bbd40c751f04aadac144e4b09ac7097c66ce7978/src/components/VideoPlayer/VideoPlayerControls/index.js#L55-L56
https://github.com/Expensify/App/blob/bbd40c751f04aadac144e4b09ac7097c66ce7978/src/components/VideoPlayer/BaseVideoPlayer.js#L139-L143

If we close it, then the video player element doesn't exist anymore.

When the report/chat is changed, we try to clear the video data, including stopping and unloading the video from the memory.
https://github.com/Expensify/App/blob/bbd40c751f04aadac144e4b09ac7097c66ce7978/src/components/VideoPlayerContexts/PlaybackContext.js#L77-L91

But the error is thrown when we try to unload the video because the ref element doesn't exist anymore. Somehow the stop function doesn't throw an error, maybe it just ignores it/works differently.

### What changes do you think we should make in order to solve the problem?

We should clear the video player ref and other data, but not stop and unload it when the video player is unmounted, only if `shouldUseSharedVideoElement` is false.

_shouldUseSharedVideoElement is true in the carousel and large screen only_

In BaseVideoPlayer.js
```
useEffect(() => {
    shouldUseSharedVideoElementRef.current = shouldUseSharedVideoElement;
}, [shouldUseSharedVideoElement]);

useEffect(() => {
    return () => {
        if (!shouldUseSharedVideoElementRef.current) {
            resetVideoPlayerData(false);
        }
    }
    // we want to execute this when unmount
}, []);
```

`resetVideoPlayerData` data will be exposed from the PlaybackContext and accept a 2nd parameter whether to stop & unload the video or not.

This way, when the add attachment preview is closed, stop and unload won't happen because the ref is null.

**Comment by rushatgabhane** [comment] 2024-02-21 06:31
I like @bernhardoj's proposal https://github.com/Expensify/App/issues/36955#issuecomment-1955915574

🎀👀🎀

**Comment by kowczarz** [comment] 2024-02-21 17:55
I like https://github.com/Expensify/App/issues/36955#issuecomment-1955860630, but since `unloadVideo` uses `currentVideoPlayerRef` I would do it in that order.
```js
        stopVideo();
        setCurrentlyPlayingURL(null);
        setSharedElement(null);
        setOriginalParent(null);
        unloadVideo();
        currentVideoPlayerRef.current = null;
```

**Comment by puneetlath** [comment] 2024-02-21 18:43
Ok, let's go with @aneequeahmad's proposal then. Thanks everyone.

**Comment by bernhardoj** [comment] 2024-02-22 04:21
> That's true, but there is a case when we play a video in chat A, then navigate to chat B and the video from chat A still plays, because we can't determine when componentWillUnmount will be fired. That's why stopVideo and unloadVideo are necessary in resetVideoPlayerData.

The `stopVideo` and `unloadVideo` won't be called only if the component is unmounted. If the report is changed, both functions will still be called.

Changing the order like in this [comment](https://github.com/Expensify/App/issues/36955#issuecomment-1957523076) won't fix the issue.

**Comment by aneequeahmad** [comment] 2024-02-27 04:03
@puneetlath PR is raised [here](https://github.com/Expensify/App/pull/37259)

**Comment by aneequeahmad** [comment] 2024-03-15 10:38
@lanitochka17 Payment is due here.

**Comment by puneetlath** [comment] 2024-03-15 14:59
@aneequeahmad sent you a hiring offer. Ping me here once you've accepted.

**Comment by aneequeahmad** [comment] 2024-03-15 15:02
@puneetlath Accepted the offer. Thankyou for mentioning

**Comment by puneetlath** [comment] 2024-03-15 15:16
Payment summary: 
- @aneequeahmad - C - $500 - paid via Upwork
- @rushatgabhane - C+ - $500 - to be paid via NewDot

Please request on NewDot @rushatgabhane. 

Thanks everyone!

**Closed by puneetlath** 2024-03-15 15:16 UTC
Labels: Reviewing, External, Engineering, Weekly, Bug

**Comment by JmillsExpensify** [comment] 2024-03-18 15:42
$500 approved for @rushatgabhane based on summary.
