### ISSUE TITLE
[HOLD for payment 2024-03-07] [$500] Web - IOU - I can't navigate using the "Tab" key

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#36513] opened 2024-02-14 15:38 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.41.1
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** Applause - Internal Team
**Slack conversation:**

## Action Performed:
1. Open FAB > Request money
2. Select manual, enter a value and click "Next"
3. Select a workspace chat
4. Press the "Tab" key

## Expected Result:
I should be able to use it

## Actual Result:
I can't navigate using the "Tab" key. It works in task request flow

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details> 

https://github.com/Expensify/App/assets/78819774/535b5b04-4e69-4387-bca4-b81707f25393

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~0144e80c4837a63c84</li>
        <li>Upwork Job ID: 1757791324532207616</li>
        <li>Last Price Increase: 2024-02-14</li>
<li>Automatic offers: </li>
<ul>
<li>cubuspl42 | Reviewer | 0</li>
<li>bernhardoj | Contributor | 0</li>
</ul></li>
    </ul>
</details>

**Comment by lanitochka17** [comment] 2024-02-14 15:38
We think that this bug might be related to #vip-vsp
CC @quinthar

**Comment by bernhardoj** [comment] 2024-02-15 06:18
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
Can't navigate using the TAB key on the money request page.

### What is the root cause of that problem?
In https://github.com/Expensify/App/pull/35154, we intentionally disable the TAB to "fix" https://github.com/Expensify/App/issues/26326.
https://github.com/Expensify/App/blob/6914b1344ed1f8bd69037232a67e34ffea2581e4/src/pages/iou/request/IOURequestStartPage.js#L91-L102

But this affected all money request page, including participant and confirmation page.

### What changes do you think we should make in order to solve the problem?

We should unregister the tab listener when the screen is out focus. We can use `useFocusEffect` to achieve it.
```
useFocusEffect(
    useCallback(() => {
        const handler = (event) => {
            if (event.code !== CONST.KEYBOARD_SHORTCUTS.TAB.shortcutKey) {
                return;
            }
            event.preventDefault();
            event.stopPropagation();
        };
        KeyDownPressListener.addKeyDownPressListener(handler);

        return () => KeyDownPressListener.removeKeyDownPressListener(handler);
}, []));
```

### What alternative solutions did you explore? (Optional)
This isn't the best solution, but just in case. We can store the navigation focus state to a ref and return early if the page is not focused anymore.

**Comment by cubuspl42** [comment] 2024-02-15 08:41
@bernhardoj 

Just to confirm, does your solution keep https://github.com/Expensify/App/issues/26326 fixed?

**Comment by damadoko** [comment] 2024-02-15 17:13
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
Can not navigate by tab key in request money page.
### What is the root cause of that problem?
Since #35154 to fix #26326 
https://github.com/Expensify/App/blob/6914b1344ed1f8bd69037232a67e34ffea2581e4/src/pages/iou/request/IOURequestStartPage.js#L91-L102

This change disable all tab actions in request money page (which wrapped by `IOURequestStartPage` component)
### What changes do you think we should make in order to solve the problem?
1. Revert above code to get back normal behaviors.
2. Set css attribute: `visibility: hidden` to not-active `TopTab.Screen`, all focusable child of that element will not tab(able) anymore.
```js
<TopTab.Screen name={CONST.TAB_REQUEST.MANUAL}>
  {({navigation}) => {
    const state = navigation.getState();
    if (state?.index === 0) return <IOURequestStepAmount route={route} />;

    return (
        <View style={visibility.hidden}>
           <IOURequestStepAmount route={route} />;
         </View>
     );
}}
```

### What alternative solutions did you explore? (Optional)
Above solution need to change all `TopTab.Screen` implementation. I think about more generic solution which make changes in `OnyxTabNavigator`'s children:
```js
{React.Children.map(children, (child, i) => {
  if (!React.isValidElement(child) || child.type !== TopTab.Screen || !isFunction(child.props.children)) {
    return child;
  }

  return React.cloneElement(child, {
    children: (props) => {
      const state = props?.navigation?.getState();
      if (state.index === i) {
        return child.props.children(props);
      }
      return <View style={visibility.hidden}>{child.props.children(props)}</View>;
    },
  });
})}
```

**Comment by damadoko** [comment] 2024-02-15 17:16
Contributor details
Your Expensify account email: damadoko1@gmail.com
Upwork Profile Link: https://www.upwork.com/freelancers/~012cb272a7b7771f06

**Comment by bernhardoj** [comment] 2024-02-16 04:35
@cubuspl42 yes

**Comment by cubuspl42** [comment] 2024-02-16 10:22
@damadoko I'm confused by the behavior of the discussed tab component (`TopTab.Navigator`). Is the content of non-active tabs actually rendered to the DOM tree?

**Comment by damadoko** [comment] 2024-02-16 11:52
@cubuspl42 yes, it actually render non-active tabs to the DOM tree as  https://github.com/Expensify/App/issues/26326#issuecomment-1700290699 mentioned. This bug only happens with `TopTab.Navigator`.
The original https://github.com/Expensify/App/issues/26326 included 2 different issues:
1. When press tab, focus is moved, the whole tab navigator elements move too.
2. When press tab, focus can move out of RHP. (Seem like we try to address it here https://github.com/Expensify/App/issues/36476)

**Comment by cubuspl42** [comment] 2024-02-19 09:24
I decided to approve the proposal by @bernhardoj.

Both proposals suggested to keep the `useEffect` block introduced by https://github.com/Expensify/App/pull/35154. I believe it's cleaner to improve its behavior than to introduce another solution for dealing with the "Tab" key (namely CSS `visibility` property).

C+ reviewed 🎀 👀 🎀

**Comment by bernhardoj** [comment] 2024-02-20 07:26
PR is ready

cc: @cubuspl42

**Comment by alexpensify** [comment] 2024-02-28 00:33
Update: The PR is waiting for @mountiny's review.

**Comment by alexpensify** [comment] 2024-03-01 02:05
Awesome, looks like automation kicked in here. 

--- 

Heads up, I will be offline until Tuesday, March 5, 2024. I will not be actively watching over this GitHub during that period. If anything urgent is needed here, please ask for help in the Open Source Slack Room-- thanks!

**Comment by alexpensify** [comment] 2024-03-08 00:53
Alright, I've completed the payment summary here: 

https://github.com/Expensify/App/issues/36513#issuecomment-1972142123

For this Upwork Job: 

https://www.upwork.com/jobs/~0144e80c4837a63c84

--- 

Closing - Everyone has been paid via Upwork.

**Closed by alexpensify** 2024-03-08 00:53 UTC
Labels: Daily, Awaiting Payment, Bug
