### ISSUE TITLE
[$1000]  VBA - Connect to plaid button does not respond

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#14505] opened 2023-01-24 02:11 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Access staging.new.expensify.com
2. Sign into a valid account
3. Profile > Workspace > Connect bank account > Connect to Plaid

## Expected Result:
User expects the VBA flow to open and load

## Actual Result:
Nothing happens, the button does not respond

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [ ] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 1.2.58.2

**Reproducible in staging?:** Yes

**Reproducible in production?:** No

**If this was caught during regression testing, add the test name, ID and link from TestRail:**

**Email or phone of affected tester (no customers):**

**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Notes/Photos/Videos:** Any additional supporting documentation

https://user-images.githubusercontent.com/93399543/214198695-9f7c941a-531f-43b9-af7a-b47e345bf087.mp4

https://user-images.githubusercontent.com/93399543/214198735-7a10d86c-152b-4ae1-883d-fa2ce590f62d.mp4

![bae](https://user-images.githubusercontent.com/93399543/214198981-ae5cd0cc-8273-4875-b3da-bf87ac213639.jpg)

**Expensify/Expensify Issue URL:**

**Issue reported by:** Applause - Internal Team

**Slack conversation:**

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~0143e936a0b5cae24a</li>
        <li>Upwork Job ID: 1617826994065350656</li>
        <li>Last Price Increase: 2023-01-24</li>
    </ul>
</details>

**Comment by MariaHCD** [comment] 2023-01-24 07:56
Possibly related to: https://github.com/Expensify/App/pull/13236#issuecomment-1401432318

Although, I can't seem to reproduce this on dev 🤔

**Comment by nkuoch** [comment] 2023-01-24 10:10
@dylanexpensify can you remove the upwork job and unassign yourself? I didn't want to add the external label, it was a mistake.

**Comment by dylanexpensify** [comment] 2023-01-24 11:30
Unassigned, removed job posting!

**Comment by luacmartins** [comment] 2023-01-24 16:15
I'll close this issue since the PR fixing this blocker was tested in staging and it's a pass. Thanks for the quick turnaround @nkuoch!

**Closed by luacmartins** 2023-01-24 16:15 UTC
Labels: Reviewing, DeployBlockerCash, Engineering, Hourly, Help Wanted
