### ISSUE TITLE
[$1000] Closed accounts aren't removed from workspace members list

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#20264] opened 2023-06-06 13:42 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Invite new user (that doesn't have a NewDot account)
2. Valifdate this user, then login with this new user account in ND in private mode
3. Close this new user account
4. Switch to Desktop App with admin account and check members list

## Expected Result:
5. Closed account was removed from the members list

## Actual Result:
7. Closed accounts are still displayed in the members list

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android / native
- [x] Android / Chrome
- [x] iOS / native
- [x] iOS / Safari
- [x] MacOS / Chrome / Safari
- [x] MacOS / Desktop

**Version Number:** 1.3.24.4

**Reproducible in staging?:** Yes

**Reproducible in production?:** No

**If this was caught during regression testing, add the test name, ID and link from TestRail:**

**Email or phone of affected tester (no customers):**

**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Notes/Photos/Videos:** Any additional supporting documentation

**Closed account**

https://github.com/Expensify/App/assets/93399543/fcac9649-9868-4037-8518-65f9b43a2b48

**Member's list**

https://github.com/Expensify/App/assets/93399543/9812cb18-e5e7-450a-bfe6-361451425f29

**Expensify/Expensify Issue URL:**

**Issue reported by:** Applause - Internal Team

**Slack conversation:**

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~0190db70a7a3eb2f5b</li>
        <li>Upwork Job ID: 1672152459568193536</li>
        <li>Last Price Increase: 2023-06-30</li>
    </ul>
</details>

**Comment by Julesssss** [comment] 2023-06-06 14:52
Regardless it doesn't seem like a blocker. Testing locally now.

**Comment by Julesssss** [comment] 2023-06-06 14:57
It seems very weird that this only occurs on Desktop staging: 
- Desktop prod: ✅ 
- Desktop staging: ❌ -- I can reproduce
- Web staging: ✅ 
- Web prod: ✅ 

@Beamanator I doubt your changes would lead to this Desktop only issue, right?

**Comment by Beamanator** [comment] 2023-06-06 16:50
Ooh ya I have no idea how mu changes would only cause this on desktop....

**Comment by Julesssss** [comment] 2023-06-06 17:45
Yep, good call:

```
Web version: v1.3.24-4
Desktop version: v1.3.24-3
```

Definately not a blocker, but I'll keep this open until I can test against the Desktop build

**Comment by roryabraham** [comment] 2023-06-06 19:33
`1.3.24-4` successfully deployed on desktop. 5th time's the charm! Looks like this is NAB but let's retest and close if not reproducible.

**Comment by roryabraham** [comment] 2023-06-06 19:36
@kbecciv Can we please retest?

**Comment by Julesssss** [comment] 2023-06-07 08:51
I'm going to close this myself after desting Desktop on `v1.3.25-1`

**Comment by kbecciv** [comment] 2023-06-07 12:48
Hello @roryabraham! Do you want QA team to re-test this issue? Let me know

**Comment by Julesssss** [comment] 2023-06-07 15:11
Thanks @kbecciv, is that just Desktop or all platforms?

**Comment by Julesssss** [comment] 2023-06-07 16:01
Could you please test all platforms? I think it was only reported on Desktip due to the release missmatch.

**Comment by Julesssss** [comment] 2023-06-13 07:52
Hi again @kbecciv, could Applause please retest all platforms? Thanks

**Comment by kbecciv** [comment] 2023-06-15 17:31
Hi @Julesssss! Let me request it, we are currently running Regression, so it might be delay.

**Comment by Julesssss** [comment] 2023-06-19 07:44
Hey @kbecciv, was the team able to test this one? Thanks

**Comment by kbecciv** [comment] 2023-06-19 22:55
I posted on channel, but nobody tested yet! I will do it again today, thank you remind me.

**Comment by kbecciv** [comment] 2023-06-20 11:48
@Julesssss I asked Team to retest this issue in all Platform and we experienced crash in all environments, Issue reported here https://github.com/Expensify/App/issues/21112

**Comment by Julesssss** [comment] 2023-06-20 12:45
Okay, thanks. So we should re-test this once the linked issue is resolved/

**Comment by kbecciv** [comment] 2023-06-22 14:27
@Julesssss We retested the issue in two platforms ( IOS app and mWeb), both platforms have the issue - after closed a new account user needs to logout and login on Admin account, so that the account that was closed is not seen in members. 
Basically issue is not fixed for scenario 2

https://github.com/Expensify/App/assets/93399543/2da1776f-f014-4f9b-a676-b0b2737a81c1

**Comment by Julesssss** [comment] 2023-06-23 07:59
Okay I have updated the issue, lets solve the closed account problem

**Comment by twisterdotcom** [comment] 2023-06-23 09:08
This isn't overdue. It's waiting on proposals.

**Comment by BhuvaneshPatil** [comment] 2023-06-23 09:28
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
Closed accounts aren't removed from workspace members list

### What is the root cause of that problem?
To render the members list we use - `WorkSpaceMembersPage`
It uses the following method - 
https://github.com/Expensify/App/blob/6183609c577f2310928bb4e8ee23b52f6dd28e00/src/pages/workspace/WorkspaceMembersPage.js#L85-L87

Notice the method - 
`getClientPolicyMemberEmailsToAccountIDs()` has an API call - `OpenWorkspaceMembersPage`, if we have a deleted user account, it gives 404 error.

Also, `personalDetails` are not updated when some account is deleted unless the user logs in again.
the `personalDetails` not being updated is causing this issue.

### What changes do you think we should make in order to solve the problem?
We shall update the `personalDetails` when we close the account, by removing that `accountID` key of the closed account.
Example - if we update the avatar of one user that reflects the on the another user's session
I am looking in the code how that's achieved in the past, might need some help.

### What alternative solutions did you explore? (Optional)
Remove the user from all the workspaces manually when we close the account.

**Comment by twisterdotcom** [comment] 2023-06-26 10:14
@aimane-chnaif - what do you think of @BhuvaneshPatil's proposal?

**Comment by twisterdotcom** [comment] 2023-06-28 09:17
I am OOO! Adding another BZ for the week.

**Comment by Julesssss** [comment] 2023-06-29 11:12
Bumping @aimane-chnaif for a review of [this](https://github.com/Expensify/App/issues/20264#issuecomment-1604003040) proposal. Or let me know if I should reassign 👍

**Comment by BhuvaneshPatil** [comment] 2023-06-30 17:49
@aimane-chnaif 

My idea for implementing that is to modify the `closeAccount()` in `User.js`.
And make something similar to this - 
```
function closeAccount(message) {
    // Note: successData does not need to set isLoading to false because if the CloseAccount
    // command succeeds, a Pusher response will clear all Onyx data.
    API.write(
        'CloseAccount',
        {message},
        {
            optimisticData: [
                {
                    onyxMethod: Onyx.METHOD.MERGE,
                    key: ONYXKEYS.FORMS.CLOSE_ACCOUNT_FORM,
                    value: {isLoading: true},
                },
                {
                    onyxMethod: Onyx.METHOD.MERGE,
                    key: ONYXKEYS.PERSONAL_DETAILS_LIST,
                    value: {
                        [currentUserAccountID]: undefined,
                    },
                },
            ],
            successData: [
                {
                    onyxMethod: Onyx.METHOD.MERGE,
                    key: ONYXKEYS.PERSONAL_DETAILS_LIST,
                    value: {
                        [currentUserAccountID]: undefined,
                    },
                },
            ],
            failureData: [
                {
                    onyxMethod: Onyx.METHOD.MERGE,
                    key: ONYXKEYS.FORMS.CLOSE_ACCOUNT_FORM,
                    value: {isLoading: false},
                },
            ],
        },
    );
}
```

But I think there are some changes that need to be done on backend as well.

Because for update avatar - this is what response looks like
![image](https://github.com/Expensify/App/assets/27822551/d9220655-a8d0-457a-b236-69b16b054b11)


But for close account - 
![image](https://github.com/Expensify/App/assets/27822551/f35a3a6d-3855-4733-98b0-6818f18fa863)

The response doesn't contains `successData` or the key that we have changed.

My guess is that there are some changes that we need to do on backend(expensify team can confirm that), because there is something mentioned in the comments for `closeAccount()`.

What's your thought @aimane-chnaif

**Comment by muttmuure** [comment] 2023-07-03 13:33
@Julesssss do you mind confirming if @BhuvaneshPatil's theory about the backend changes is correct

@aimane-chnaif could you confirm if the front end fix proposal looks complete now

**Comment by Julesssss** [comment] 2023-07-04 08:14
> So when close account, need to remove from all workspaces and rooms where user had joined.

I agree, but as this would notify all accounts within a workspace/room and because close account is such a rare action I'm not even sure we should fix this. Leaning towards just closing it, what do you think @muttmuure?

**Comment by twisterdotcom** [comment] 2023-07-04 23:33
>but as this would notify all accounts within a workspace/room and because close account is such a rare action I'm not even sure we should fix this.

I disagree. Just because something is rare, does not mean we shouldn't fix it. Ideally, every case is polished, edge or not. If we think this does need to be `Internal` then we should make it that, and prioritise it accordingly. That sounds like what we'll do.

**Comment by Julesssss** [comment] 2023-07-05 12:11
Sure, but it's probably going to just sit in my backlog for the rest of the year tbh.

**Comment by mvtglobally** [comment] 2023-07-06 03:50
Issue not reproducible during KI retests. (First week)

**Comment by twisterdotcom** [comment] 2023-08-07 09:58
If this is not reproducible, can we close?

**Closed by twisterdotcom** 2023-08-07 09:58 UTC
Labels: Engineering, Monthly, Improvement, Internal, Overdue, Bug
