### ISSUE TITLE
[Awaiting Payment 26th Aug, 2024] [$250] Expense - Incorrect member count in report details after commenting or inviting another member

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#46660] opened 2024-08-01 12:36 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 9.0.15-0
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**If this was caught during regression testing, add the test name, ID and link from TestRail:** https://expensify.testrail.io/index.php?/tests/view/4784292
**Issue reported by:** Applause - Internal Team

## Action Performed:
1. Go to staging.new.expensify.com
2. Submit an expense to User B
3. Click on the expense preview in the main chat to go to expense report
4. Send a user mention containing User C
5. Click Invite from the whisper
6. Click on the report header
7. Click Members

## Expected Result:
In Step 6, the member count will update correctly

## Actual Result:
In Step 6, the member count shows 1 member, when there are three members in the report (Step 7)
This issue also happens when user comments on the expense report without inviting a third user

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [x] Android: mWeb Chrome
- [x] iOS: Native
- [x] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details> 

https://github.com/user-attachments/assets/4ebe914b-33cf-41d0-906b-3926e5887f31

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01ca5b97965eb72787</li>
        <li>Upwork Job ID: 1819133324859524397</li>
        <li>Last Price Increase: 2024-08-01</li>
<li>Automatic offers: </li>
<ul>
<li>suneox | Reviewer | 103398512</li>
<li>FitseTLT | Contributor | 103398514</li>
</ul></li>
    </ul>
</details>

**Comment by FitseTLT** [comment] 2024-08-01 12:53
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
 member count doesn't agree with the member list count
### What is the root cause of that problem?
The criteria to hide a hidden participant is not the same in details page
https://github.com/Expensify/App/blob/49f09589d33d37fa00425d2b8f3984b06e18e300/src/pages/ReportDetailsPage.tsx#L139-L140
and in participants page

https://github.com/Expensify/App/blob/49f09589d33d37fa00425d2b8f3984b06e18e300/src/pages/ReportParticipantsPage.tsx#L67-L68
### What changes do you think we should make in order to solve the problem?

We should make the criteria in both places the same. May be change the details page criteria to the participants one here
https://github.com/Expensify/App/blob/49f09589d33d37fa00425d2b8f3984b06e18e300/src/pages/ReportParticipantsPage.tsx#L67-L68

### What alternative solutions did you explore? (Optional)

**Comment by FitseTLT** [comment] 2024-08-01 13:08
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
 member count doesn't agree with the member list count
### What is the root cause of that problem?
The criteria to hide a hidden participant is not the same in details page
https://github.com/Expensify/App/blob/49f09589d33d37fa00425d2b8f3984b06e18e300/src/pages/ReportDetailsPage.tsx#L139-L140
and in participants page

https://github.com/Expensify/App/blob/49f09589d33d37fa00425d2b8f3984b06e18e300/src/pages/ReportParticipantsPage.tsx#L67-L68
### What changes do you think we should make in order to solve the problem?

The members menu item navigates to two page: participants and members page based on the report type as in here

https://github.com/Expensify/App/blob/49f09589d33d37fa00425d2b8f3984b06e18e300/src/pages/ReportDetailsPage.tsx#L309-L315
What we should do is the members menu count shown in the count should be the length of the members list shown in participants or members page so we should make those values agree.
1. In participants page the participants are filtered based on `shouldExcludeHiddenParticipants` value set here
https://github.com/Expensify/App/blob/49f09589d33d37fa00425d2b8f3984b06e18e300/src/pages/ReportDetailsPage.tsx#L139-L140

2. In members page the should ExcludeHidden is `true`
https://github.com/Expensify/App/blob/49f09589d33d37fa00425d2b8f3984b06e18e300/src/pages/RoomMembersPage.tsx#L172-L173
and also we filter out optimistic duplicate accountID here 
https://github.com/Expensify/App/blob/49f09589d33d37fa00425d2b8f3984b06e18e300/src/pages/RoomMembersPage.tsx#L180-L184

So we calculate the members count based on these conditions
### What alternative solutions did you explore? (Optional)

**Comment by FitseTLT** [comment] 2024-08-01 13:09
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
 member count doesn't agree with the member list count
### What is the root cause of that problem?
The criteria to hide a hidden participant is not the same in details page
https://github.com/Expensify/App/blob/49f09589d33d37fa00425d2b8f3984b06e18e300/src/pages/ReportDetailsPage.tsx#L139-L140
and in participants page

https://github.com/Expensify/App/blob/49f09589d33d37fa00425d2b8f3984b06e18e300/src/pages/ReportParticipantsPage.tsx#L67-L68
### What changes do you think we should make in order to solve the problem?

The members menu item navigates to two page: participants and members page based on the report type as in here

https://github.com/Expensify/App/blob/49f09589d33d37fa00425d2b8f3984b06e18e300/src/pages/ReportDetailsPage.tsx#L309-L315
What we should do is the members menu count shown in the count should be the length of the members list shown in participants or members page so we should make those values agree.
1. In participants page the participants are filtered based on `shouldExcludeHiddenParticipants` value set here

https://github.com/Expensify/App/blob/49f09589d33d37fa00425d2b8f3984b06e18e300/src/pages/ReportParticipantsPage.tsx#L67-L68

2. In members page the should ExcludeHidden is `true`
https://github.com/Expensify/App/blob/49f09589d33d37fa00425d2b8f3984b06e18e300/src/pages/RoomMembersPage.tsx#L172-L173
and also we filter out optimistic duplicate accountID here 
https://github.com/Expensify/App/blob/49f09589d33d37fa00425d2b8f3984b06e18e300/src/pages/RoomMembersPage.tsx#L180-L184

So we calculate the members count based on these conditions
### What alternative solutions did you explore? (Optional)

**Comment by FitseTLT** [comment] 2024-08-01 13:23
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
 member count doesn't agree with the member list count
### What is the root cause of that problem?
The criteria to hide a hidden participant is not the same in details page
https://github.com/Expensify/App/blob/49f09589d33d37fa00425d2b8f3984b06e18e300/src/pages/ReportDetailsPage.tsx#L139-L140
and in participants page

https://github.com/Expensify/App/blob/49f09589d33d37fa00425d2b8f3984b06e18e300/src/pages/ReportParticipantsPage.tsx#L67-L68
### What changes do you think we should make in order to solve the problem?

The members menu item navigates to two page: participants and members page based on the report type as in here

https://github.com/Expensify/App/blob/49f09589d33d37fa00425d2b8f3984b06e18e300/src/pages/ReportDetailsPage.tsx#L309-L315
What we should do is the members menu count shown in the count should be the length of the members list shown in participants or members page so we should make those values agree.
1. In participants page the participants are filtered based on `shouldExcludeHiddenParticipants` value set here

https://github.com/Expensify/App/blob/49f09589d33d37fa00425d2b8f3984b06e18e300/src/pages/ReportParticipantsPage.tsx#L67-L68
and if the detail doesn't exist
https://github.com/Expensify/App/blob/49f09589d33d37fa00425d2b8f3984b06e18e300/src/pages/ReportParticipantsPage.tsx#L71-L74
2. In members page the should ExcludeHidden is `true`
https://github.com/Expensify/App/blob/49f09589d33d37fa00425d2b8f3984b06e18e300/src/pages/RoomMembersPage.tsx#L172-L173
and also we filter out optimistic duplicate accountID or the detail doesn't exist here 
https://github.com/Expensify/App/blob/49f09589d33d37fa00425d2b8f3984b06e18e300/src/pages/RoomMembersPage.tsx#L180-L184

So we calculate the members count based on these conditions
So in ReportDetails Page we use this code
```
const participants = useMemo(() => {
        const shouldExcludeHiddenParticipants = isUserCreatedPolicyRoom || isChatThread || (isPolicyExpenseChat && isPolicyAdmin) ? true : !isGroupChat && !isIOUReport;
        return ReportUtils.getParticipantsAccountIDsForDisplay(report, shouldExcludeHiddenParticipants);
    }, [report, isGroupChat, isSystemChat]);
const activeChatMembers = participants.flatMap((accountID) => {
        const details = personalDetails?.[accountID];
        const isDuplicateOptimisticDetail = details?.isOptimisticPersonalDetail && participants.some((accID) => accID !== accountID && details.login === personalDetails?.[accID]?.login);

        const pendingMember = report?.pendingChatMembers?.findLast((member) => member.accountID === accountID.toString());
        return !!details && !isDuplicateOptimisticDetail && (!pendingMember || pendingMember.pendingAction !== CONST.RED_BRICK_ROAD_PENDING_ACTION.DELETE) ? accountID : [];
    });
```
_We can leave out the `pendingMember` condition to make it more compatible with list shown in members page and also we can use a new variable in place of `participants` we need to keep the previous variable_ 
### What alternative solutions did you explore? (Optional)

**Comment by trjExpensify** [comment] 2024-08-01 22:09
Sending external, but I'd like @puneetlath eyes on this as it's related to hidden members behaviour.

**Comment by FitseTLT** [comment] 2024-08-07 20:59
PR will be ready tomorrow 👍

**Comment by trjExpensify** [comment] 2024-08-26 09:14
PR hit prod 7 days ago, automation failed. 

Payment summary as follows: 

- $250 to @FitseTLT for the fix 
- $250 to @suneox for the C+ review 

Paid you both, closing!

**Closed by trjExpensify** 2024-08-26 09:14 UTC
Labels: Reviewing, External, Weekly, Bug
