### ISSUE TITLE
[$500] Workspace - WS default profile image flickers every time opened via settings

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#34019] opened 2024-01-05 12:14 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.22
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** Appause - Internal Team
**Slack conversation:**

## Action Performed:
1. Launch app
2. Tap profile icon
3. Tap Workspaces
4. Tap new Workspace
5. Tap settings and note profile image

## Expected Result:
Workspace default profile image must not flicker every time opened via settings

## Actual Result:
Workspace default profile image flickers every time opened via settings

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [ ] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details> 

https://github.com/Expensify/App/assets/78819774/69a694dd-8eef-4061-b3ac-7232d12fa522

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~0134c232e6ee21092a</li>
        <li>Upwork Job ID: 1743244606833586176</li>
        <li>Last Price Increase: 2024-01-05</li>
    </ul>
</details>

**Comment by aswin-s** [comment] 2024-01-05 12:54
## Proposal

### Please re-state the problem that we are trying to solve in this issue.

The default avatar on Workspace settings page flashes on load

### What is the root cause of that problem?

The `DefaultAvatar` prop passed to `AvatarWithImagePicker` component in Workspace settings page is an inline anonymous function. This forces the avatar component to rerender whenever the state of Workspace settings change.

https://github.com/Expensify/App/blob/7ae1ec7e74b908e6340bccaf7e42b0345d766711/src/pages/workspace/WorkspaceSettingsPage.js#L117-L127

### What changes do you think we should make in order to solve the problem?

Memoize the anonymous function using a useCallback hook. This makes sure that the defaultAvatar component gets rerendered only when one of its dependencies change.

```tsx
  const defaultAvatar= useCallback(()=>(
        <Avatar
       containerStyles={styles.avatarLarge}
       imageStyles={[styles.avatarLarge, styles.alignSelfCenter]}
       source={policy.avatar ? policy.avatar : ReportUtils.getDefaultWorkspaceAvatar(policyName)}
       fallbackIcon={Expensicons.FallbackWorkspaceAvatar}
       size={CONST.AVATAR_SIZE.LARGE}
       name={policyName}
       type={CONST.ICON_TYPE_WORKSPACE}
   />),[policy.avatar, policyName, styles.alignSelfCenter, styles.avatarLarge])

....

<AvatarWithImagePicker
  source={lodashGet(policy, 'avatar')}
  size={CONST.AVATAR_SIZE.LARGE}
  DefaultAvatar={ defaultAvatar}
  type={CONST.ICON_TYPE_WORKSPACE}
  fallbackIcon={Expensicons.FallbackWorkspaceAvatar}
  ...
/>
```

Result

https://github.com/Expensify/App/assets/6880914/6da5094c-800f-4773-9059-801d28b90f46


### What alternative solutions did you explore? (Optional)
None (edited)

**Comment by bernhardoj** [comment] 2024-01-05 13:18
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
The workspace settings image flickers multiple times.

### What is the root cause of that problem?
I think the other proposals already mention the root cause well.

In the workspace setting, we pass a DefaultAvatar that accepts a component.
https://github.com/Expensify/App/blob/7ae1ec7e74b908e6340bccaf7e42b0345d766711/src/pages/workspace/WorkspaceSettingsPage.js#L114-L127

DefaultAvatar will be used when the workspace doesn't have any custom avatar set. Because it's an anonymous function, the reference is not stable on each render.

### What changes do you think we should make in order to solve the problem?

There are multiple ways to pass a component as a prop, and the other way that is safer is to pass the component as it is, without any function.
```
DefaultAvatar={<Avatar .../>}
```

Then, in the AvatarWithImagePicker, instead of doing this,
https://github.com/Expensify/App/blob/7ae1ec7e74b908e6340bccaf7e42b0345d766711/src/components/AvatarWithImagePicker.js#L316-L318

we can just write `DefaultAvatar`.

**Comment by joekaufmanexpensify** [comment] 2024-01-05 20:49
I can't reproduce this. It's working as expected for me on web, iOS, and Android. The video above seems to be on Android, so I've included what I'm seeing there below: 

https://github.com/Expensify/App/assets/54866469/0898b997-f8fe-4c2a-942e-b32e512a63f8

Even if it was consistently reproducible, I'm not convinced this is worth prioritizing. This is barely noticeable/doesn't really impact the user experience at all. Closing for now.

**Closed by joekaufmanexpensify** 2024-01-05 20:49 UTC
Labels: External, Daily, Help Wanted, Bug
