### ISSUE TITLE
[BE Bug] Reports - General formulas appear by system messages when report is created

### ISSUE THREAD

**Issue by izarutskaya** [Expensify/App#45886] opened 2024-07-22 10:13 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** v9.0.10-2
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**Email or phone of affected tester (no customers):** applausetester+esraa111@applause.expensifail.com
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Issue reported by:** Applause-Internal team

## Action Performed:
1. Open NewDot app
2. Login to OldDot and go to Reports
3. Create a new Report and add an expense
4. Navigate to the report created in NewDot
5. Observe system message

## Expected Result:
System message to generally say "Report created with the name [selected name by the user]"

## Actual Result:
System message displaying the general formulate: You renamed this room from {report:type} {report:startdate} to Expense Report 2024-07-21. Knowing that the user did not rename the report yet.

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [x] Android: mWeb Chrome
- [x] iOS: Native
- [x] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

<img width="1710" alt="Bug6548585_1721558440312!Screenshot_2024-07-21_at_1 16 52_PM" src="https://github.com/user-attachments/assets/11565836-2f34-4aed-8875-64ad9f4013e8">

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

https://github.com/user-attachments/assets/b5a661f4-f042-4c8e-afed-cc46c9a49dc6

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~0147c8159ea717d6a8</li>
        <li>Upwork Job ID: 1815774664787907381</li>
        <li>Last Price Increase: 2024-07-30</li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @rojiphil</details>

**Comment by izarutskaya** [comment] 2024-07-22 10:13
We think this issue might be related to the #collect project.

**Comment by waynedevrepo** [comment] 2024-07-24 15:22
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
> System message displaying the general formulate: You renamed this room from {report:type} {report:startdate} to Expense Report 2024-07-21. Knowing that the user did not rename the report yet.
### What is the root cause of that problem?
After create new report, Front-end pull reports data from api (https://staging.expensify.com/api/OpenReport?).
In the api response, there are 2 report actions even just only created.
![Screenshot_1](https://github.com/user-attachments/assets/4a94baf2-080d-48d9-873a-99aa2d003069)
So, It shows us the renamed inform massage.
And `ReportActionItemCreated` component does not contains the code that shows the correct message for created report.
###  What changes do you think we should make in order to solve the problem?
I think both of backend and frontend side should be updated for this issue.
- In backend, while creating a new report, only one report action with type of "CREATED" should be created instead of two actions - CREATED and RENAMED.
- In frontend, have to show the correct message into `ReportActionItemContentCreated` or `ReportActionItemContentCreated` like in `RenameAction`:

https://github.com/Expensify/App/blob/c27d06d5837767f0e088ba14665c0e64c1787bbf/src/components/ReportActionItem/RenameAction.tsx#L28-L31

### What alternative solutions did you explore? (Optional)

**Comment by waynedevrepo** [comment] 2024-07-24 15:26
Contributor details
Your Expensify account email: lb0715.dev@gmail.com
Upwork Profile Link: https://www.upwork.com/freelancers/~01aa886e223fa320e7

**Comment by waynedevrepo** [comment] 2024-07-25 08:36
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
> System message displaying the general formulate: You renamed this room from {report:type} {report:startdate} to Expense Report 2024-07-21. Knowing that the user did not rename the report yet.
### What is the root cause of that problem?
After create new report, Front-end pull reports data from api (https://staging.expensify.com/api/OpenReport?).
In the api response, there are 2 report actions even just only created.
![Screenshot_1](https://github.com/user-attachments/assets/4a94baf2-080d-48d9-873a-99aa2d003069)
So, It shows us the renamed inform massage.
And `ReportActionItemCreated` component does not contains the code that shows the correct message for created report.
###  What changes do you think we should make in order to solve the problem?
I think both of backend and frontend side should be updated for this issue.
- In backend, while creating a new report, only one report action with type of "CREATED" should be created instead of two actions - CREATED and RENAMED.
- In frontend, have to show the correct message into `ReportActionItemContentCreated` or `ReportActionItemContentCreated` like in `RenameAction`:

https://github.com/Expensify/App/blob/c27d06d5837767f0e088ba14665c0e64c1787bbf/src/components/ReportActionItem/RenameAction.tsx#L28-L31

### What alternative solutions did you explore? (Optional)

**Comment by waynedevrepo** [comment] 2024-07-25 08:37
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
> System message displaying the general formulate: You renamed this room from {report:type} {report:startdate} to Expense Report 2024-07-21. Knowing that the user did not rename the report yet.
### What is the root cause of that problem?
After create new report, Front-end pull reports data from api (https://staging.expensify.com/api/OpenReport?).
In the api response, there are 2 report actions even just only created.
![Screenshot_1](https://github.com/user-attachments/assets/4a94baf2-080d-48d9-873a-99aa2d003069)
So, It shows us the renamed inform massage.
And `ReportActionItemCreated` component does not contains the code that shows the correct message for created report.
###  What changes do you think we should make in order to solve the problem?
I think both of backend and frontend side should be updated for this issue.
- In backend, while creating a new report, only one report action with type of "CREATED" should be created instead of two actions - CREATED and RENAMED.
- In frontend, have to show the correct message into `ReportActionItemContentCreated` or `ReportActionItemContentCreated` like in `RenameAction`:

https://github.com/Expensify/App/blob/c27d06d5837767f0e088ba14665c0e64c1787bbf/src/components/ReportActionItem/RenameAction.tsx#L28-L31

### What alternative solutions did you explore? (Optional)

**Comment by rojiphil** [comment] 2024-07-27 10:16
Thanks @waynedevrepo for the proposal. 
I think there are cases where it may be expected to receive `Renamed` action in FE but I think `oldName` must be properly formatted by BE. Instead, BE sends `oldName` as `{report:type} {report:startdate}` 
This looks like a BE issue to me.
Let me get an internal engineer to have a look at this.
 🎀👀🎀

![Screenshot 2024-07-27 at 3 36 36 PM](https://github.com/user-attachments/assets/b06722a3-8366-40ab-9173-8cd1e7778eb6)

**Comment by waynedevrepo** [comment] 2024-07-27 11:57
So, does that mean my suggestion is useless?

**Comment by waynedevrepo** [comment] 2024-08-01 03:35
I think you have to consider my proposal.

**Comment by grgia** [comment] 2024-08-02 11:00
I agree this is a BE issue @rojiphil 

Which ONYX key contains oldName ?

**Comment by rojiphil** [comment] 2024-08-02 13:44
> Which ONYX key contains oldName ?

`oldName` is present in `originalMessage` within `reportActions_xxReportIDxx` for action with `actionName`=`RENAMED`

**Comment by grgia** [comment] 2024-08-06 15:36
I haven't looked into this yet, focusing on card issues

**Comment by grgia** [comment] 2024-08-06 15:41
Unassigning and moving into HOT PICKS for now, feel free to reassign me if no one picks it up in a reasonable amount of time

**Comment by rojiphil** [comment] 2024-08-09 17:01
Unassigning myself as this is a BE issue. Please reassign if needed. Thanks.

**Comment by trjExpensify** [comment] 2024-08-09 20:29
@thienlnam this is the issue for report title formulas.

**Comment by sonialiap** [comment] 2024-08-13 11:32
Still looking for an internal engineer

**Comment by sonialiap** [comment] 2024-08-16 12:13
@lschurr I'm OOO Aug 19-30, adding leave buddy. 
Status: need an internal engineer

**Comment by tgolen** [comment] 2024-08-19 13:02
@neil-marcellini Do you know about this? I see you recently moved this report action to Auth in https://github.com/Expensify/Auth/pull/10464

**Comment by lschurr** [comment] 2024-08-19 16:30
Posted here: https://expensify.slack.com/archives/C036QM0SLJK/p1724084991089379

**Comment by mvtglobally** [comment] 2024-08-23 12:04
Issue not reproducible during KI retests. (First week)

**Comment by luacmartins** [comment] 2024-08-23 14:06
This is fixed. Closing.

**Closed by luacmartins** 2024-08-23 14:06 UTC
Labels: Reviewing, Daily, Internal, Bug
