### ISSUE TITLE
Invoices - Workspace chat and all individual invoice reports show GBR in LHN

### ISSUE THREAD

**Issue by IuliiaHerets** [Expensify/App#53310] opened 2024-11-29 10:54 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 9.0.68-2
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**If this was caught on HybridApp, is this reproducible on New Expensify Standalone?:** Y
**Email or phone of affected tester (no customers):** applausetester+232803@applause.expensifail.com
**Issue reported by:** Applause Internal Team

## Action Performed:
Precondition:
- Invoices are enabled.
- Bank account is not added in invoices settings.

1. Go to staging.new.expensify.com
2. [User A] Submit a few invoices to User B via FAB > Send invoice.
3. [User B] Open the invoice room.
4. [User B] Pay all the invoices.
5. [User A] Refresh the page.

## Expected Result:
Only the main workspace chat should show GBR in LHN (this is the behavior when employee is asked to add a bank account after admin pays the expense with Expensify).

## Actual Result:
Workspace chat and all individual invoice reports show GBR in LHN for the invoice sender.

## Workaround:
Unknown

## Platforms:

- [x] Android: Standalone
- [x] Android: HybridApp
- [x] Android: mWeb Chrome
- [x] iOS: Standalone
- [x] iOS: HybridApp
- [x] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

https://github.com/user-attachments/assets/363bce7f-2019-45cb-b916-a1359ffb6785
 
</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by RachCHopkins** [comment] 2024-12-02 05:54
Don't they all show GBR because they are waiting for a bank account?

![image](https://github.com/user-attachments/assets/1ed8a3e3-f7a6-47bb-baec-774b9d72dc08)

**Comment by RachCHopkins** [comment] 2024-12-02 05:56
@davidcardoza can you confirm, is this expected behaviour because we want the invoice payer to add a bank account to receive funds?

**Comment by RachCHopkins** [comment] 2024-12-04 22:44
Thank you! Closing. But I did find another bug in my testing.

**Closed** 2024-12-06 02:29 UTC
Labels: Daily, Bug
