### ISSUE TITLE
[$500] IOU - Double IOU are seen in IOU report screen

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#34260] opened 2024-01-10 16:25 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** v1.4.24-0
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** Applause - Internal Team
**Slack conversation:**

**Issue found when executing PR** https://github.com/Expensify/App/pull/32698

## Action Performed:
1. Go Offline
2. Add a money request in 1:1 DM chat Report
3. Go to IOU details page and send a comment
4. Delete the IOU from within the IOU details page
5. Go back to IOU report page and add another IOU request
6. Go to Parent chat report and go Online
7. Wait until you are fully online and Click on the IOU preview component
8. Scroll up (go back to parent chat report and go back in to IOU report if you don't see the bug at first)

## Expected Result:
There should be only one IOU component

## Actual Result:
Two IOU components are visible in IOU report page

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [x] Android: mWeb Chrome
- [ ] iOS: Native
- [x] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

https://github.com/Expensify/App/assets/93399543/87a363ca-f2ca-48c2-ae7f-e630221f68e9

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~013ced1698c9a376c1</li>
        <li>Upwork Job ID: 1745119819895382016</li>
        <li>Last Price Increase: 2024-01-31</li>
<li>Automatic offers: </li>
<ul>
<li>hoangzinh | Reviewer | 28133177</li>
</ul></li>
    </ul>
</details>

**Comment by CortneyOfstad** [comment] 2024-01-12 19:27
Not overdue

**Comment by CortneyOfstad** [comment] 2024-01-15 16:59
Still waiting on proposals 👍

**Comment by CortneyOfstad** [comment] 2024-01-17 18:47
Still waiting on proposals

**Comment by CortneyOfstad** [comment] 2024-01-22 15:19
Not overdue

**Comment by CortneyOfstad** [comment] 2024-01-29 14:52
@hoangzinh @kbecciv can we confirm if the issue is still happening/reproduceable?

**Comment by CortneyOfstad** [comment] 2024-01-31 18:47
Reached out to Call Stack to see if someone can take this one and get it over the finish line 👍 

Asked in Slack [here](https://expensify.enterprise.slack.com/archives/C03UK30EA1Z/p1706726810625299)

**Comment by teneeto** [comment] 2024-01-31 19:09
Hi, I'm Eto from Callstack - expert contributor group - and I would like to look into this issue.

**Comment by CortneyOfstad** [comment] 2024-02-05 14:07
@teneeto any update on the PR? Thanks!

**Comment by teneeto** [comment] 2024-02-06 18:45
Hi @CortneyOfstad I'm working on a proposal, will come back here by tomorrow.

**Comment by kameshwarnayak** [comment] 2024-02-10 04:14
@CortneyOfstad Is this still open for the external contributors to look into? I can try to find the root cause and give a proposal if it is open. This looks interesting

**Comment by teneeto** [comment] 2024-02-12 09:50
Hi @kameshwarnayak I'm glad to know you're interested in this issue. I'm currently looking into it at the moment.

**Comment by teneeto** [comment] 2024-02-12 10:12
@CortneyOfstad This issue seem to be somehow intermittent for some reasons i can't tell. I have been able to trace down specifically to where this issue is happening, but unfortunately i can't test further, I have only been able to reproduce it once and after a code update, I'm not able to reproduce this behaviour any longer. Can we confirm if this issue persists?

**Comment by kameshwarnayak** [comment] 2024-02-12 12:29
@teneeto  Sure. No worries :)

**Comment by CortneyOfstad** [comment] 2024-02-12 13:46
@kbecciv can you confirm the issue is still happening?

**Comment by CortneyOfstad** [comment] 2024-02-14 14:10
Bump @kbecciv ^^^ Thanks!

**Comment by kbecciv** [comment] 2024-02-14 16:17
Checking @CortneyOfstad

**Comment by kbecciv** [comment] 2024-02-14 18:28
issue is no longer reproducible!

https://github.com/Expensify/App/assets/93399543/b24b3115-072d-437c-a6a8-f2a33363bfd0

**Comment by CortneyOfstad** [comment] 2024-02-15 19:07
Thanks @kbecciv! Closing this out!

**Closed by CortneyOfstad** 2024-02-15 19:07 UTC
Labels: Engineering, Daily, Internal, Bug
