### ISSUE TITLE
Web – Request Money - "Report Not Found" Error expensify.com sign-in page opens by the Email link

### ISSUE THREAD

**Issue by izarutskaya** [Expensify/App#26938] opened 2023-09-07 10:09 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Click the green + icon and select request money
2. Enter an amount and click next
3. Enter the email address of a user that doesn't have an existing account and request $x to confirm and send the request.
4. Go to the email inbox of that user you just invited and make sure the email is received - it will look like this
![image](https://github.com/Expensify/App/assets/51066321/90e2bb5f-f934-4485-861e-d4af8b8a8089)

5. Click the "Expensify" hyperlink in the email

## Expected Result:
Navigated to the New Expensify sign-in page and not the expensify.com sign-in page.

## Actual Result:
Navigated to the expensify.com sign-in page with The Error message "Report not Found"

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [x] Windows / Chrome /
- [ ] MacOS / Desktop

**Version Number:** 1.3.65-0

**Reproducible in staging?:** Y

**Reproducible in production?:** Y

**If this was caught during regression testing, add the test name, ID and link from TestRail:**

**Email or phone of affected tester (no customers):**

**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/115492554/81f65c9c-2340-457a-be6a-d9515aa054eb

![Bug6190827_Split_Old](https://github.com/Expensify/App/assets/115492554/17eea387-e042-48ed-bb5b-f90249e79101)

**Expensify/Expensify Issue URL:**

**Issue reported by:** Applause - Internal Team

**Slack conversation:** @

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~013568bf585c519a67</li>
        <li>Upwork Job ID: 1699857983227707392</li>
        <li>Last Price Increase: 2023-09-07</li>
    </ul>
</details>

**Comment by Christinadobrzyn** [comment] 2023-09-07 18:51
I can reproduce this - I can't find any other reports of this. 
I think this needs to be `internal` but not quite sure...

**Comment by Christinadobrzyn** [comment] 2023-09-11 20:13
Hey @rushatgabhane can you confirm if this should be internal? I can add an engineering label if yes. Thanks!

**Comment by Christinadobrzyn** [comment] 2023-09-15 17:15
Hi @chiragsalian let me know if you have the bandwidth to take this job on and an update on a PR. thanks!

**Comment by chiragsalian** [comment] 2023-09-15 17:25
Hi Christina, im swamped. Could you find another engineer to tackle this or should i unassign and post in engg chat instead?
Also is this a daily. I'm wondering if it could be demoted to weekly instead.

**Comment by Christinadobrzyn** [comment] 2023-09-18 21:58
No worries @chiragsalian! I'll remove you and add another engineer. 

@marcochavezf let me know if you think this can be moved to `Weekly` based on https://github.com/Expensify/App/issues/26938#issuecomment-1721613523

**Comment by marcochavezf** [comment] 2023-09-22 04:10
I'm also swamped hehe, I think I can prioritize this after completing the implementation of collect approvers (ideally after the offshore). I'm going to move it to weekly meanwhile

**Comment by Christinadobrzyn** [comment] 2023-09-29 00:01
I don't think WAQ applies here because this is an internal issue and not customer-facing. But going to move this back to weekly. I wonder if this should be monthly even?

**Comment by Christinadobrzyn** [comment] 2023-10-05 15:19
I'm not sure what to do with this issue - maybe I should reach out in BZ room and see if someone else can take it? Seems like moving to monthly doesn't stop the WAQ messaging. 

Reached out to @marcochavezf to see if he has an idea

**Comment by marcochavezf** [comment] 2023-10-09 18:41
We're probably not setting the param `isChat` for this [condition](https://github.com/Expensify/Web-Expensify/blob/8b32861bf377015980b2a80fadfaf69d9c36d5b4/lib/Notification/Report/Comment.php#L186) when we call the API command `RequestMoney`.

**Comment by Christinadobrzyn** [comment] 2023-10-10 20:46
working on it Melvin!

**Comment by marcochavezf** [comment] 2023-10-11 20:52
Still wrapping up some priorities for wave7, no update atm

**Comment by marcochavezf** [comment] 2023-10-12 19:40
No update, tackling one issue by one

**Comment by marcochavezf** [comment] 2023-10-13 18:30
No update, focused on TU launch

**Comment by marcochavezf** [comment] 2023-10-16 20:39
No update

**Comment by Christinadobrzyn** [comment] 2023-10-17 23:29
Should I move this to weekly @marcochavezf?

**Comment by marcochavezf** [comment] 2023-10-18 02:30
Thanks for the suggestion @Christinadobrzyn, I already have a fix for it I will create a PR tomorrow, so I will leave it as daily atm since it can be experienced by real customers with the latest wave launches.

**Comment by marcochavezf** [comment] 2023-10-18 21:22
Oh noticed this is no longer an issue:

<img width="561" alt="Screenshot 2023-10-18 at 3 14 18 p m" src="https://github.com/Expensify/App/assets/6829422/4acceeb6-38c6-46a5-ba20-729f0040dbc5">

<img width="564" alt="Screenshot 2023-10-18 at 3 20 12 p m" src="https://github.com/Expensify/App/assets/6829422/8afd1253-6e9a-4aa1-9989-b845b41171cc">

@izarutskaya could you verify from your end too?

**Comment by marcochavezf** [comment] 2023-10-19 18:51
Closing it out because it's already fixed

**Closed by marcochavezf** 2023-10-19 18:51 UTC
Labels: Engineering, Daily, Internal, Bug
