### ISSUE TITLE
[$500] IOU - Total amount is not updated when change the different currency IOU in offline

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#35209] opened 2024-01-25 23:00 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.32-2
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** Applause - Internal Team
**Slack conversation:**

**Issue found when executing PR** https://github.com/Expensify/App/pull/34011
## Action Performed:
1. Go to staging.new.expensify.com.
2. Go offline
3. Click FAB > Request money > Manual.
4. Request money from a user that has no existing chat.
5. In 1:1 DM, click + > Request money.
6. Create another manual request in a different currency
7. Open the detail IOU page from second request
8. Change the currency into same as first IOU
9. Go to 1:1 conversation

## Expected Result:
Total from two IOS request should be present, since both requests are in same currency

## Actual Result:
Only amount of the first request is displayed in total

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [x] Android: mWeb Chrome
- [x] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details> 

https://github.com/Expensify/App/assets/78819774/d5be6625-2599-4e06-a964-2f26e2e624a2

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~0110932b60eddd10f4</li>
        <li>Upwork Job ID: 1750654949608632320</li>
        <li>Last Price Increase: 2024-01-25</li>
<li>Automatic offers: </li>
<ul>
<li>cubuspl42 | Reviewer | 28131429</li>
<li>dukenv0307 | Contributor | 28131430</li>
</ul></li>
    </ul>
</details>

**Comment by jacobkim9881** [comment] 2024-01-29 18:18
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
When money requests are being made with different currencies offline, amount total of report thread is not calculated based on each currency.

### What is the root cause of that problem?
The frontend app should wait for response with calculated amount total from server when currencies are different. If it is online then the server calculate amount total but if it is offline and then amount total is shown as un-calculated without any filter.

When offline the amount total is calculated but it is false calculation for different currencies to money request thread. [Technically the calculation is not from the server but frontend.](https://github.com/Expensify/App/blob/2c28a47c5213dff5162f33b010c9401ecbdf42fa/src/libs/actions/IOU.js#L1018) 

<details close>
  <summary>The un-matched amount total go through not only report preview but also report header, LHN, report setting page, share code page and browser notification.</summary>

![스크린샷 2024-01-29 오후 8 11 18](https://github.com/Expensify/App/assets/46774300/a6e81f3b-9600-439d-8dcc-44c903822022)

<img width="1440" alt="스크린샷 2024-01-29 오후 8 13 00" src="https://github.com/Expensify/App/assets/46774300/638f267e-f84c-43dc-b0db-52ff38d6c90f">


</details>

### What changes do you think we should make in order to solve the problem?
When it is offline and when the report thread with more than 2 reports has different currencies, total amount will be shown as 'TBD'. For this [`convertToDisplayString`](https://github.com/Expensify/App/blob/a44e80436248c8ec39a9e28d618364181a0df829/src/libs/CurrencyUtils.ts#L103
) function will be used for the solution. The functions gives 'TBD' when `amountInCents` is `0` and when `shouldFallbackToTbd` is `true`. 

If it has different currencies, as optimistic data `total` should be `0` for `amountInCents` should be `0` to show 'TBD' at `convertToDisplayString`. Because with server response, success data change `total` into calculated amount currently. To build this, total will be given `0` with the condition when deciding optimistic data.

To check offline, we should import default function from `src/hooks/useNetwork.ts` at `ReportUtils.getReportName` function and at `src/components/ReportActionItem/ReportPreview.js`.

On report preview page, `getDisplayAmount` is used to decide total. We use the same logic for the issue.

On such tags at LHN, money report header, `ReportUtils.getReportName` is used to decide total amount for showing. It has `convertToDisplayString` function and the same logic will be applied.

### What alternative solutions did you explore? (Optional)
Fetch currency information from web and use in frontend.

**Comment by cubuspl42** [comment] 2024-01-30 13:20
@jacobkim9881 So, effectively you're just suggesting to stop calculating any total sum while offline? This is not an acceptable behavior.

**Comment by cubuspl42** [comment] 2024-01-30 13:29
I approve the proposal by @dukenv0307

C+ reviewed 🎀 👀 🎀

**Comment by jacobkim9881** [comment] 2024-01-30 17:25
With my proposal, the PR will solve un-calculated total at report's name on LHN too. I hope your reconsideration.

**Comment by jacobkim9881** [comment] 2024-01-31 00:06
I want to say my proposal doesn't stop to calculate the amount. My proposal makes un-calculated amount total shown as `TBD`. The amount total can't be calculated same from the server's calculation response. If the amount should be calculated then it should be cared an internal issue as a new feature.

**Comment by cubuspl42** [comment] 2024-01-31 09:03
@jacobkim9881 Thanks for your proposal and the explanations. I understand what you're suggesting. Out of these two proposals, I decided that the other is a better way forward.

**Comment by jacobkim9881** [comment] 2024-01-31 09:21
@cubuspl42 I see and respect your decision. I hope the issue will be solved well.

**Comment by bfitzexpensify** [comment] 2024-02-02 21:11
How is this one going @dukenv0307?

**Comment by bfitzexpensify** [comment] 2024-02-05 22:24
Bump @dukenv0307, can you please provide an update?

**Comment by cubuspl42** [comment] 2024-02-21 08:44
This is officially a disaster. I believe we underestimated the impact of the change.

**Comment by tylerkaraszewski** [comment] 2024-03-14 20:30
I think all the deploy blockers related to this have been resolved now. Maybe we can close this out?

**Comment by cubuspl42** [comment] 2024-03-15 09:27
> I think we're ready for payment now.

For whatever is left of it, anyway 😅

**Comment by bfitzexpensify** [comment] 2024-03-28 22:11
OK, there was a lot to try and follow here. I'm going to bring the price down to $125 - it should be halved again (3 regressions in total), but $62.50 feels too low for the work put in. 

Payments complete.

**Closed by bfitzexpensify** 2024-03-28 22:11 UTC
Labels: Reviewing, External, Weekly, Bug
