### ISSUE TITLE
[$500] Pressing shift+enter in the comment composer does not enter a new line (nothing happens).

### ISSUE THREAD

**Issue by m-natarajan** [Expensify/App#34351] opened 2024-01-11 13:34 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.24-4
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** @tgolen 
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1704906612957569

## Action Performed:

1. In web staging, navigate to any chat
2. Type something (eg. Hello)
3. Press Shift+Return

##Expected Results:
Pressing Shift+Return should add a newline

## Actual Results:
Pressing Shift+Return does nothing
(Bug occurs inconsistently)

## Workaround:
unknown
## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

https://github.com/Expensify/App/assets/38435837/d182ec0d-b0c3-48ef-9066-bc32afc72009

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~013be96addddf82207</li>
        <li>Upwork Job ID: 1745439102766141440</li>
        <li>Last Price Increase: 2024-01-11</li>
    </ul>
</details>

**Comment by waterim** [comment] 2024-01-16 13:43
Im not able to reproduce it.
Read the slack conversation too.

**Comment by isabelastisser** [comment] 2024-01-16 20:55
Thanks @waterim! Closing.

**Closed by isabelastisser** 2024-01-16 20:55 UTC
Labels: External, Daily, Help Wanted, Overdue, Bug
