### ISSUE TITLE
[HOLD for payment 2024-06-20] [HOLD for payment 2024-06-18] [Details Revamp] Remove DetailsPage.tsx

### ISSUE THREAD

**Issue by grgia** [Expensify/App#42079] opened 2024-05-13 14:26 UTC
https://docs.google.com/document/d/1-xSZdSZZIuIl0fPO7yypkKfcbWEsnNFAs50ptgL3Gnw/edit#bookmark=id.azg8eofhvuhz

<details><summary>Issue Owner</summary>Current Issue Owner: @anmurali</details>

**Comment by kosmydel** [comment] 2024-05-20 08:47
Hey, I'm from SWM and I will work on this.

**Comment by trjExpensify** [comment] 2024-05-29 10:49
@kosmydel will this one effectively come last with the changes, or are we waiting on something else?

**Comment by kosmydel** [comment] 2024-05-29 10:57
> @kosmydel will this one effectively come last with the changes, or are we waiting on something else?

We are currently waiting for the PRs at https://github.com/Expensify/App/pull/42188 and https://github.com/Expensify/App/pull/41972 to be merged. I don't want to open this PR yet because there might be changes during the review process of the above PRs that could impact the review process of this one (as this PR is based on the above ones).

**Comment by trjExpensify** [comment] 2024-05-29 21:37
Nice, so #42188 to go!

**Comment by kosmydel** [comment] 2024-06-03 13:47
This one is waiting for https://github.com/Expensify/App/pull/42188, but I opened it for review anyway to speed up the process a bit (I've notified the C+ that it is not based on the main branch).

**Comment by kosmydel** [comment] 2024-06-05 06:26
We can take this issue off hold as the blocking PR was merged :)

**Comment by anmurali** [comment] 2024-06-21 01:45
@kosmydel - can you propose regression test steps?

**Comment by kosmydel** [comment] 2024-06-21 15:06
Hey @anmurali, I've never done something like this, but here you are:

1. Go to a report.
2. Mention a user that doesn't exist in the Onyx (e.g. @+3213972183, @[adsdds@asdassd.com](mailto:adsdds@asdassd.com))
3. Click the mention to open the Profile page. Verify that everything is displayed correctly and works.
4. Repeat the above steps for multiple accounts (phone numbers, emails, etc.).
5. Verify the above for invalid account IDs (e.g. https://staging.new.expensify.com/a/hellodsdsdsdsdsd)
6. Verify the above for random account IDs (e.g. https://staging.new.expensify.com/a/3213112)
7. Click the user profile picture to open the Profile page. Verify that everything is displayed correctly and works.

**Comment by anmurali** [comment] 2024-06-26 03:41
@grgia - do you agree with those regression steps. I would love a review since @kosmydel has not written one of these before.

**Comment by grgia** [comment] 2024-06-26 09:18
@anmurali @kosmydel 

Great work on these @kosmydel ! I made some minor tweaks, could you confirm my changes?

> 1. Go to a chat report.
> 2. Mention a user that you've never interacted with and doesn't exist in Onyx (e.g. @+3213972183, @[adsdds@asdassd.com](mailto:adsdds@asdassd.com))
> 3. Click on the mention to open the Profile page.
> ✅ Verify that everything is displayed correctly and works.
> 4. Repeat the above steps for multiple accounts (phone numbers, emails, etc.).
>  ✅  Verify that "page not found" is shown for invalid account IDs (e.g. https://staging.new.expensify.com/a/hellodsdsdsdsdsd)
>  ✅  Verify that personal details page loads for random account IDs (e.g. https://staging.new.expensify.com/a/3213112)
> 5. Click the user profile picture to open the Profile page.
> ✅  Verify that everything is displayed correctly and works.

**Comment by kosmydel** [comment] 2024-06-26 09:34
Looks great @grgia!

**Comment by shawnborton** [comment] 2024-07-01 06:18
Not overdue! Working out final details but we have this live in product.

**Comment by grgia** [comment] 2024-07-01 10:21
@anmurali I think we've got everything we need to close this one out

**Comment by shawnborton** [comment] 2024-07-08 07:17
@anmurali friendly bump

**Comment by anmurali** [comment] 2024-07-08 20:02
No payments needed. Regression test added.

**Closed by anmurali** 2024-07-08 20:02 UTC
Labels: Daily, NewFeature, Overdue, Awaiting Payment

**Comment by mallenexpensify** [comment] 2025-07-31 17:15
### Payment Summary 

Contributor+: @Ollyws due $250 via NewDot for [PR review](https://github.com/Expensify/App/pull/42385)

(I checked and their assignment date is after their eligibility date)
