### ISSUE TITLE
[$500]  Web - App Displays 0.00 in Preview and Blank Space in Amount Section

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#26912] opened 2023-09-06 21:00 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Click on the plus sign and select "Request Money"
2. Choose to scan and add blank photos
3. Wait for a minute and observe the IOU detail amount section. A red dot notification will appear, prompting the user to enter an amount. However, the preview displays 0.00

## Expected Result:
The preview amount should not display 0.00 until the user updates the amount. The preview should be consistent with the amount section.

## Actual Result:
The preview displays 0.00, but in the detail amount section, it displays a blank space prompting the user to enter an amount.

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [x] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 1.3.64.2
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation

[screen-capture - 2023-09-02T004855.127 (1).webm](https://github.com/Expensify/App/assets/93399543/50a43302-aeb8-4819-8600-259412401259)

https://github.com/Expensify/App/assets/93399543/933ada4a-5f02-4f32-baaa-1f8b9962170e

**Expensify/Expensify Issue URL:**
**Issue reported by:** @tewodrosGirmaA
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1693641038520799

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~018b1f94cf56fec7a5</li>
        <li>Upwork Job ID: 1700291001595150336</li>
        <li>Last Price Increase: 2023-09-08</li>
    </ul>
</details>

**Comment by greg-schroeder** [comment] 2023-09-08 23:35
Not overdue

**Comment by SheryarKhan6242** [comment] 2023-09-09 02:26
### Proposal

### Please re-state the problem that we are trying to solve in this issue.

App Displays 0.00 in Preview and Blank Space in Amount Section

### What is the root cause of that problem?

No validations to check if the uploaded image is actually a receipt and has the price/amount or not.

### What changes do you think we should make in order to solve the problem?

There are couple of techniques to solve this and depends.

1. If you're using OCR to scan the receipt for the price, you can run the OCR on the image and analyze the extracted text. If the OCR output contains no or minimal text (e.g., just gibberish), it's likely that the image is blank or invalid.

2. Check the dimensions of the uploaded image. If the image is too small (e.g., smaller than a minimum width or height), consider it invalid.
3. To check if the image is not blank or empty, you can perform image processing operations to analyze its content. One common approach is to calculate the average pixel value of the image. If the average pixel value is below a certain threshold, consider the image as blank.

Lastly, if the current system only has the ability to lets say validate pdf etc. Then add a validation for those mime types only  

For all the above points, the end result should show the validation message to the user to please enter a valid receipt.

**Comment by SheryarKhan6242** [comment] 2023-09-09 02:30
Contributor details
Your Expensify account email: sheryarkhan1995@outlook.com
Upwork Profile Link: https://www.upwork.com/freelancers/~019fc7434d26335772

**Comment by SheryarKhan6242** [comment] 2023-09-09 02:31
### Proposal

### Please re-state the problem that we are trying to solve in this issue.

App Displays 0.00 in Preview and Blank Space in Amount Section

### What is the root cause of that problem?

No validations to check if the uploaded image is actually a receipt and has the price/amount or not.

### What changes do you think we should make in order to solve the problem?

There are couple of techniques to solve this and depends.

1. If you're using OCR to scan the receipt for the price, you can run the OCR on the image and analyze the extracted text. If the OCR output contains no or minimal text (e.g., just gibberish), it's likely that the image is blank or invalid.

2. Check the dimensions of the uploaded image. If the image is too small (e.g., smaller than a minimum width or height), consider it invalid.
3. To check if the image is not blank or empty, you can perform image processing operations to analyze its content. One common approach is to calculate the average pixel value of the image. If the average pixel value is below a certain threshold, consider the image as blank.

Lastly, if the current system only has the ability to lets say validate pdf etc. Then add a validation for those mime types only  

For all the above points, the end result should show the validation message to the user to please enter a valid receipt.

**Comment by DylanDylann** [comment] 2023-09-09 03:51
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
App Displays 0.00 in Preview and Blank Space in Amount Section

### What is the root cause of that problem?
In the IOU report 
https://github.com/Expensify/App/blob/5c138163049ef0f036d46c4359c51fcde673066f/src/libs/TransactionUtils.js#L184-L205

We use 0 as the default amount. So, if the amount doesn't exist we will display 0

 But in the preview transaction
https://github.com/Expensify/App/blob/5c138163049ef0f036d46c4359c51fcde673066f/src/components/ReportActionItem/MoneyRequestView.js#L128
If there is an error and transactionAmount = 0, we will display "Enter an amount" with the error style

### What changes do you think we should make in order to solve the problem?
https://github.com/Expensify/App/blob/5c138163049ef0f036d46c4359c51fcde673066f/src/components/ReportActionItem/MoneyRequestPreview.js#L268

In here we should add condition to display the amount like this
```
<Text style={styles.textHeadline}>{hasFieldErrors && requestAmount=== 0 ? props.translate('common.error.enterAmount') : getDisplayAmountText()}</Text>

```


### Result
We can ask the design team about the style of message and update it 

<img width="919" alt="Screenshot 2023-09-09 at 10 50 36" src="https://github.com/Expensify/App/assets/141406735/56792b65-2fa2-4bb5-922e-71681a3627e5">

**Comment by greg-schroeder** [comment] 2023-09-11 13:56
Awaiting proposal review

**Comment by jjcoffee** [comment] 2023-09-11 14:32
@DylanDylann's [proposal](https://github.com/Expensify/App/issues/26912#issuecomment-1712404638) has the correct RCA and the solution seems like a good path forward. I think we probably also need to handle the LHN and title bar displays (`owes $x.xx` and `paid $x.xx` also seem wrong in this case). And yes, we most likely need eyes from the design team on this, as the result screenshot feels a bit off to me!

:ribbon::eyes::ribbon: C+ reviewed

**Comment by DylanDylann** [comment] 2023-09-12 10:09
@shawnborton Could you help to confirm what we should display on LHN (below text) in case the receipt request have error

<img width="919" alt="Screenshot 2023-09-09 at 10 50 36" src="https://github.com/Expensify/App/assets/141406735/56792b65-2fa2-4bb5-922e-71681a3627e5">

**Comment by greg-schroeder** [comment] 2023-09-12 14:28
Just awaiting @chiragsalian to confirm C assignment here :)

**Comment by chiragsalian** [comment] 2023-09-12 18:55
Did shawn confirm the copy change? 
Either way, it LGTM. Feel free to create the PR @DylanDylann.

**Comment by chiragsalian** [comment] 2023-09-12 18:57
> Could you help to confirm what we should display on LHN (below text) in case the receipt request have error

I think just "Enter an amount" with the red error circle should suffice. I don't think any additional text needs to be displayed there but that's my opinion.

**Comment by DylanDylann** [comment] 2023-09-13 05:43
@chiragsalian @shawnborton This is an overview of all the things that we will fix in the PR. Please help to confirm

When scanning receipt fails:
1. In the main chat (DM chat)

<img width="1440" alt="Screenshot 2023-09-13 at 12 36 39" src="https://github.com/Expensify/App/assets/141406735/0a5625db-146d-4487-857a-880fa8bece5e">


2. In the IOU chat

<img width="1028" alt="Screenshot 2023-09-13 at 12 39 54" src="https://github.com/Expensify/App/assets/141406735/f25d45e6-7562-44b7-9dd9-5b4d5239ad93">


3. In the transaction chat

<img width="1029" alt="Screenshot 2023-09-13 at 12 40 07" src="https://github.com/Expensify/App/assets/141406735/4f1073db-291e-4916-933b-3d2429a905b2">

# Update all to Enter a Mount (with translation)

**Comment by DylanDylann** [comment] 2023-09-13 10:19
@chiragsalian @shawnborton This is an overview of all the things that we will fix in the PR. Please help to confirm

When scanning receipt fails:


 In the IOU chat



<img width="1440" alt="Screenshot 2023-09-13 at 17 15 54" src="https://github.com/Expensify/App/assets/141406735/cfbb38fd-978e-4561-8eec-6efbe3493771">

**Comment by shawnborton** [comment] 2023-09-14 02:18
cc @JmillsExpensify @trjExpensify - if the scan fails, shouldn't we actually write something like "Scan failed" or something?

**Comment by trjExpensify** [comment] 2023-09-14 13:16
The LHN title of the request will be `Receipt missing details` with the RBR red dot, and it'll have the same title in the page header in the request view as per @Gonals's clean up [here](https://github.com/Expensify/App/issues/26832). 

I think this issue is just going to duplicate the work, so we can probably close it as these are known polish items that are in the process of being cleaned up.

**Comment by chiragsalian** [comment] 2023-09-14 17:27
@trjExpensify, to confirm are you saying to close this GH issue and instead revisit the bug mentioned here once alberto is done so as to not duplicate work?

**Comment by trjExpensify** [comment] 2023-09-14 17:43
Yeah, I think once Alberto is done it should look like this: 

![image](https://github.com/Expensify/App/assets/16232057/0a26ff05-d4e8-4a0c-a842-9bd445169e24)

**Comment by chiragsalian** [comment] 2023-09-14 19:14
Okay, sounds good to me. Looks like https://github.com/Expensify/App/issues/26832 was created before this issue too and the dupe wasn't caught by us. Sorry @DylanDylann but we're going to close out this issue for now. Once https://github.com/Expensify/App/issues/26832 is done we can revisit this issue and see if any other UI improvements around this need to be made.

**Closed by chiragsalian** 2023-09-14 19:14 UTC
Labels: External, Daily, Help Wanted, Bug
