### ISSUE TITLE
[$1000] Web - Admin not able to delete message that has a thread on public room (works well on direct message)

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#22162] opened 2023-07-04 10:48 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Go to staging dot on web chrome and login with user A
2. Create a new room in Public mode
3. Go to header of the room and copy the share code URL of the room
4. Go to another web chrome and login with User B. Paste the room URL so that User B can have access to the room
5. Make sure both User A and User B are on the room page
6. (Imp step)- From User B, send a message on the room.
7. Now from User A , try to delete the user B message and notice it works perfectly
8. But now, again send a message from User B on the room.
9. From same User B, Immediately then click on 'Reply thread' option on the recent message sent so that a new thread page opens up and send a message on the thread page.
10. Now from User A, delete the original message of User B sent on Step 8 and notice that on User A's side, it throws an error.

## Expected Result:
Error should not be shown

## Actual Result:
Admin not able to delete message that has a thread on public room (works well on direct message)

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [x] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 1.3.35-5
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/93399543/dd484190-8f48-4338-83c9-befd41a8a686

https://github.com/Expensify/App/assets/93399543/ecfbf5a7-a918-4c04-9cbd-89a5af648b07

**Expensify/Expensify Issue URL:**
**Issue reported by:** @priya-zha
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1688299950685649

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~0116af3ad4fe05588d</li>
        <li>Upwork Job ID: 1678896775357931520</li>
        <li>Last Price Increase: 2023-08-04</li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @madmax330</details>

**Comment by michaelhaxhiu** [comment] 2023-07-11 22:39
At first I thought this may be related to https://github.com/Expensify/App/issues/22128 but after testing, I don't think so anymore.

**Comment by michaelhaxhiu** [comment] 2023-07-11 22:39
But we may have a recurring theme of issues with "deleting a message in a public chat room" as I've seen a few flavors of this 🤔

**Comment by getusha** [comment] 2023-07-18 17:27
the expected/actual result is not clear 

>Admin not able to delete message that has a thread on public room (works well on direct message)

the admin is not able to delete message? or there is an error shown?

**Comment by Nikhil-Vats** [comment] 2023-07-18 17:43
@michaelhaxhiu this seems like a backend issue.

**Comment by michaelhaxhiu** [comment] 2023-07-18 17:43
@getusha did you watch the video in the GH body? There is an error. It shouldn't error, it should just work.

**Comment by michaelhaxhiu** [comment] 2023-07-18 17:44
@Nikhil-Vats oh really? @allroundexperts do you agree? I think these `Report no longer exists` errors have historically been backend / internal so I would not be super surprised.

**Comment by multijump** [comment] 2023-07-18 17:53
When called DeleteComment api, backend returned `Report no longer exists` error.
So I think it should be fixed by backend.

**Comment by michaelhaxhiu** [comment] 2023-07-24 12:40
going `Internal` per the discussion above

**Comment by michaelhaxhiu** [comment] 2023-07-26 20:39
Max was assigned 2 days ago, let's give this 1 or 2 more days

**Comment by madmax330** [comment] 2023-07-31 12:31
Sorry was OO and traveling, I'll look into it today

**Comment by madmax330** [comment] 2023-08-02 20:58
Hmm yeah, I think this should be internal
I can get a PR up next week

**Comment by michaelhaxhiu** [comment] 2023-08-04 15:04
Note: I'm preparing to go OOO for ~2 weeks and need a BZ buddy to watch over this in the meantime. 🙏 

Next steps:
- @madmax330 is going to complete the internal PR
- After that's done, we'll process payment to the C+ ($1000 for @allroundexperts) and Bug reporter ($250 for @priya-zha)

I'll take this over when I return if it's not complete. Thanks in advance @flaviadefaria

**Comment by flaviadefaria** [comment] 2023-08-07 11:23
This is not overdue, we're waiting for the PR.

**Comment by flaviadefaria** [comment] 2023-08-10 09:46
@madmax330 how's that PR going?

**Comment by madmax330** [comment] 2023-08-10 19:29
Haven't had a chance to make it yet, will prioritize it tomorrow

**Comment by flaviadefaria** [comment] 2023-08-14 13:48
@madmax330 do you have an update here?

**Comment by madmax330** [comment] 2023-08-15 11:47
Working on it today

**Comment by flaviadefaria** [comment] 2023-08-18 10:26
I'm heading OoO for 1 week, but since @hax is meant to come back next week I believe he'll just get this back from me.

**Comment by madmax330** [comment] 2023-08-21 11:11
Didn't get to finish the PR because I was out sick last week, back on it this week

**Comment by michaelhaxhiu** [comment] 2023-08-24 19:10
Sounds good @madmax330 - let's aim to get this done tomorrow or Monday if possible 🙏

**Comment by madmax330** [comment] 2023-08-28 11:39
Prioritizing this today

**Comment by madmax330** [comment] 2023-08-29 17:20
I was able to reproduce this. It looks like UpdateReportComment doesn't recursively delete the comments in a thread. Although I'm not sure what the expected behavior is. 
cc @chiragsalian since you did the threads implementation. Should we:

1. delete all the messages in the thread
2. Keep the messages in the thread and only show deleted on the first message

Should I bring this up in #product?

**Comment by chiragsalian** [comment] 2023-08-29 23:06
Oh interesting. Yeah we probably didn't account for an admin deleting a comment for threads.
Good question, i think option 2,
> Keep the messages in the thread and only show deleted on the first message

Because currently we never clear a child report just because the parent report action has been deleted. The functionality to delete all messages in the thread sounds like a completely new feature and that might need to be designed differently.

If you want you can confirm in product but IMO going with option 2 sounds good to me.

**Comment by madmax330** [comment] 2023-08-31 10:51
Ok cool, option 2 is already the behavior we just need to skip whatever is throwing the error message

**Comment by madmax330** [comment] 2023-09-04 18:18
Will get this done this week

**Comment by michaelhaxhiu** [comment] 2023-09-11 16:11
Awaiting update from @madmax330 when he has a moment.

**Comment by madmax330** [comment] 2023-09-13 15:43
@chiragsalian I looked more into it and it's throwing here: https://github.com/Expensify/Web-Expensify/blob/20a545c1a5f76ff8b7c2d1d38027b3e50ac5b69d/lib/ReportAPI.php#L708

When I look in my local db, the accountid on the child report is 0, I'm guessing that's not right? 
Because it throws from Auth here: https://github.com/Expensify/Auth/blob/fd40194cc7da2371c73757bc34c2ae6683c1cf27/auth/command/Get.cpp#L775

Which makes sense if the user is not the owner of the report...
Any ideas?

**Comment by chiragsalian** [comment] 2023-09-13 20:01
> the accountid on the child report is 0

For a workspace report i think all reports have accountID 0, regardless if its parent or child, regardless if its public, private, admin, announce etc.

From the video above i see an error for UserA but i don't see any RBR error for UserB on the parent report. So my first guess is that the comment is properly deleted but there is some error while building the onyx data for the parent.

My guess is that its failing [here](https://github.com/Expensify/Web-Expensify/blob/20a545c1a5f76ff8b7c2d1d38027b3e50ac5b69d/lib/ReportAPI.php#L708). If i had to guess again its because UserA authToken doesn't work to fetch userB report (i.e., the child report) because UserA doesn't have access to it.

If that's the case we would have to update auth to allow fetching child reports if the user is an admin on the parent report. I don't see any reason why an admin should not have access to fetch a child report.
Let me know if you need any more help ✌️

**Comment by madmax330** [comment] 2023-09-20 02:23
I'll probably get back to this next week, helping out with the gold wallets project rn.

**Comment by madmax330** [comment] 2023-09-26 11:58
Same, I will come back to this after offshore as I'm focused on higher priority stuff.

**Comment by michaelhaxhiu** [comment] 2023-09-28 12:53
I'm re-assigning this as part of my preparation for Sabbatical (starting tomorrow). **Next steps:**

- Max will prioritize this soon, as he had more pressing work ahead of this. 
- Check on this `weekly` to ensure it's not forgotten

**Comment by madmax330** [comment] 2023-10-11 06:30
Will look into this next week, this post offshore week was a bit hectic

**Comment by madmax330** [comment] 2023-11-01 08:29
Will put the PR up today, just working on some tests

**Comment by maddylewis** [comment] 2023-11-09 20:58
Max is working on the PR for this one

**Comment by maddylewis** [comment] 2023-11-13 17:21
@madmax330 - lmk the status of this one - ty!

**Comment by madmax330** [comment] 2023-11-22 07:45
Sorry had other higher priorities 🙃

**Comment by madmax330** [comment] 2023-12-07 18:24
Still punting this one since I'm working on EOY issues

**Comment by maddylewis** [comment] 2023-12-17 17:32
hiya - puneet, i left BZ a couple of months ago, but was hanging onto this one in case there was any immediate action. since this is internal + an edge case, there hasn't been a ton of movement on the issue over the last several weeks.

there's no immediate action on your end beyond monitoring the general progress of the internal issue - lmk if you have any questions, ty!

**Comment by puneetlath** [comment] 2023-12-19 20:40
I'm not able to reproduce this. I tried deleting a message that had been threaded as an admin in a public room and it worked fine. Feel free to comment or reopen if I missed something. 

<img width="368" alt="image" src="https://github.com/Expensify/App/assets/1371996/7fe6c91c-5dc2-4be6-8d94-4b45a7571042">

**Closed by puneetlath** 2023-12-19 20:40 UTC
Labels: Engineering, Monthly, Internal, Bug
