### ISSUE TITLE
[$1000] User detail disappears in ‘’share somewhere” field- Mobile number

### ISSUE THREAD

**Issue by kavimuru** [Expensify/App#22001] opened 2023-06-30 20:58 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
Prerequisite for testing:
No chat initiation or history between User A and User B (mobile number)
Test with multiple mobile numbers (both registered and unregistered)
Steps:
1. Login as User A and click on assign task
2. Fill title and description
3. Under assignee, search for a mobile number. Test with both registered and unregistered accounts. (Try this one if you do not have one : +918969862299 for unregistered )
4. Initially, the user profile is auto assigned to both assignees and share somewhere
5. Verify, if it disappears after a while
## Expected Result:
 It should not disappear. It should stay consistent for both email and mobile numbers.
## Actual Result: 
User profile disappears in case of mobile numbers
NOTE : Appears with new email as well
## Workaround:
Can the user still use Expensify without this being fixed? Have you informed them of the workaround?

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [x] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 1.3.35-3
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/43996225/4e575c63-083c-4d1e-a797-e4687823d3bb

https://github.com/Expensify/App/assets/43996225/b74e854f-c3d6-4106-95a5-886d4fd86b05

**Expensify/Expensify Issue URL:** 
**Issue reported by:** @avi-shek-jha
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1688102504428609

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~013f6360d77660af83</li>
        <li>Upwork Job ID: 1675941914951577600</li>
        <li>Last Price Increase: 2023-07-03</li>
    </ul>
</details>

**Comment by jeet-dhandha** [comment] 2023-07-01 05:44
### Proposal
### Please re-state the problem that we are trying to solve in this issue.
- When adding a mobile number for assignee, the profile is removed from the `Share somewhere` view.
### What is the root cause of that problem?
- The root cause lies in the `OpenReport` API. There is a difference in response of:
  - `"onyxMethod": "merge","key": "personalDetailsList",`, 
  - `"onyxMethod": "merge", "key": "report_2301476194518545",`
  - `"onyxMethod": "merge","key": "personalDetails",`.

Differences: 
- Left -> `Email` 
- Right -> `Number`

<img width="1233" alt="Screenshot 2023-07-01 at 11 11 03 AM" src="https://github.com/Expensify/App/assets/78416198/eceed3f2-85ab-4644-bde6-419521d62e00">
<img width="1250" alt="Screenshot 2023-07-01 at 11 11 50 AM" src="https://github.com/Expensify/App/assets/78416198/3fb56997-3c32-4aff-a8cc-029694f73afa">
<img width="1274" alt="Screenshot 2023-07-01 at 11 12 19 AM" src="https://github.com/Expensify/App/assets/78416198/96269d24-b079-42d7-ad0d-55dafda4154c">



### What changes do you think we should make in order to solve the problem?
- We need to fix `OpenReport` API such that it returns the consistent response for all the above mentioned keys.


### What alternative solutions did you explore? (Optional)
- N/A

**Comment by thienlnam** [comment] 2023-07-03 19:00
This looks similar to https://github.com/Expensify/Expensify/issues/294203 - being unable to assign a task to someone you haven't chatted with before. I think we can close this or atleast put a hold on it for the other issue

**Comment by jeet-dhandha** [comment] 2023-07-03 19:07
Not able to open link .

**Comment by flaviadefaria** [comment] 2023-07-03 19:18
I agree, let's close this.

**Closed by flaviadefaria** 2023-07-03 19:18 UTC
Labels: External, Daily, Help Wanted, Overdue, Bug
