### ISSUE TITLE
[$500] Tag - Extra padding above Recent section in Tag list

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#35423] opened 2024-01-30 18:15 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** v1.4.33-4
**Reproducible in staging?:** y
**Reproducible in production?:** n
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** Applause- Internal Team
**Slack conversation:**

## Action Performed:
Precondition:
- User is an employee of Collect workspace.
- The Collect workspace has categories and tags, each has more than 8 items in the list.
- There are recent list in Category and Tag.

1. Go to workspace chat.
2. Open manual request page.
3. Enter amount > Next > Show more.
4. Open Category and Tag list.

## Expected Result:
In Tag list, there will be no extra padding above Recent, just like the Category list.

## Actual Result:
There is extra padding above Recent in Tag list.

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [x] Android: mWeb Chrome
- [x] iOS: Native
- [x] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

![image](https://github.com/Expensify/App/assets/93399543/e6f4e0a4-398c-4726-a0aa-59901e9579a0)

https://github.com/Expensify/App/assets/93399543/09fbee5e-b01c-438a-ab5b-8f9e5955e500

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~019c2250ecc51e6cc7</li>
        <li>Upwork Job ID: 1752408936209432576</li>
        <li>Last Price Increase: 2024-01-30</li>
    </ul>
</details>

**Comment by kbecciv** [comment] 2024-01-30 18:16
We think that this bug might be related to #wave6-collect-submitters
CC @greg-schroeder

**Comment by francoisl** [comment] 2024-01-30 19:00
Here's production (left) vs. staging (right) side by side, it's a pretty minor gap so I'm thinking we can fix it later.

<img width="375" alt="image" src="https://github.com/Expensify/App/assets/2229301/a0ac6798-677e-4044-9487-2e0c005b51e3"> <img width="375" alt="image" src="https://github.com/Expensify/App/assets/2229301/d4f92431-28b5-48ad-aa98-5290df8d5024">

**Comment by FitseTLT** [comment] 2024-01-30 19:27
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
Extra padding above Recent section in Tag list

### What is the root cause of that problem?
We are including unnecessary empty section here
https://github.com/Expensify/App/blob/a44e80436248c8ec39a9e28d618364181a0df829/src/libs/OptionsListUtils.ts#L1097-L1104
### What changes do you think we should make in order to solve the problem?

We should not add empty section
```
if (selectedTagOptions.length)
            tagSections.push({
                // "Selected" section
                title: '',
                shouldShow: true,
                indexOffset,
                data: getTagsOptions(selectedTagOptions),
            });
```
### What alternative solutions did you explore? (Optional)

**Comment by FitseTLT** [comment] 2024-01-30 19:35
@aimane-chnaif Found the offending pr. Updated [proposal](https://github.com/Expensify/App/issues/35423#issuecomment-1917739655)

**Comment by FitseTLT** [comment] 2024-01-31 11:09
@francoisl @danieldoglas @DylanDylann The root cause is found and we can fix it ASAP. WDYT

**Comment by DylanDylann** [comment] 2024-01-31 15:07
@FitseTLT's [proposal](https://github.com/Expensify/App/issues/35423#issuecomment-1917739655) looks good to me
🎀 👀 🎀 C+ reviewed

**Comment by danieldoglas** [comment] 2024-01-31 19:29
Wait, if this was caused by a recent PR (less than 7 days of the regression period), the original author of that PR needs to fix it.

**Comment by danieldoglas** [comment] 2024-01-31 19:30
cc @kubabutkiewicz can you please take a look into this, since it's still part of the regression period?

**Comment by DylanDylann** [comment] 2024-01-31 19:31
@danieldoglas Thanks for pointing out that. I will note that for next issues

**Comment by kubabutkiewicz** [comment] 2024-02-01 08:15
Will create PR shortly

**Comment by kubabutkiewicz** [comment] 2024-02-01 09:00
PR ready: https://github.com/Expensify/App/pull/35541

**Comment by DylanDylann** [comment] 2024-02-20 14:01
@danieldoglas Let's close this one

**Closed** 2024-02-20 14:02 UTC
Labels: Reviewing, External, Engineering, Weekly, Help Wanted
