### ISSUE TITLE
[$500]  Start chat-Removed newly selected participants from search results in group chat flow

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#29971] opened 2023-10-19 13:15 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.3.87-1

**Reproducible in staging?:** Yes

**Reproducible in production?:** No

**If this was caught during regression testing, add the test name, ID and link from TestRail:**

**Email or phone of affected tester (no customers):**

**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Expensify/Expensify Issue URL:**

**Issue reported by:** Applause - Internal Team

**Slack conversation:**

**Issue found when executing PR** https://github.com/Expensify/App/pull/29903
## Action Performed:
1. Go to https://staging.new.expensify.com/
2. Log in with any Gmail account
3. From the FAB Start chat
4. On the participants selector, add a couple participants to the group Start searching for a user and verify the selected participants are gone
5. Search for a user that you have selected

## Expected Result:
The newly selected participants show up in the search results

## Actual Result:
Removed the newly selected participants from the search results in the group chat flow

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [x] Android: mWeb Chrome
- [x] iOS: Native
- [x] iOS: mWeb Safari
- [x] Windows: Chrome 
- [x] MacOS: Desktop

## Screenshots/Videos
<details>
<summary>Android: Native</summary>

</details>

<details>
<summary>Android: mWeb Chrome</summary>

</details>

<details>
<summary>iOS: Native</summary>

</details>

<details>
<summary>iOS: mWeb Safari</summary>

</details>

<details>
<summary>Windows: Chrome</summary>

 

https://github.com/Expensify/App/assets/78819774/2279bf96-014f-4901-b388-a196efa0808d

</details>

<details>
<summary>MacOS: Desktop</summary>

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~0134c731261cf5cd20</li>
        <li>Upwork Job ID: 1715033894384357376</li>
        <li>Last Price Increase: 2023-10-19</li>
    </ul>
</details>

**Comment by flodnv** [comment] 2023-10-19 15:55
I'm unable to reproduce 😕 Are you able to @conorpendergrast ? 

https://github.com/Expensify/App/assets/4164921/5e9a4659-a31f-4dcc-a9ae-fc0b564bbaac

**Comment by flodnv** [comment] 2023-10-19 15:55
Going to see if anyone External is able to reproduce this...

**Comment by yakupafsin** [comment] 2023-10-19 16:26
> @abdulrahuman5196 are you able to reproduce?

When you search the user who is not in your contacts and toggle it, it's not showing on the list when you search again.

**Comment by abdulrahuman5196** [comment] 2023-10-19 16:29
This was changed recently to show only the participants matching the search term recently. If the participants don't match the search term it won't be visible. 

Cc: @thienlnam

**Comment by yakupafsin** [comment] 2023-10-19 16:31
I almost fixed that. I'll open the proposal soon

**Comment by abdulrahuman5196** [comment] 2023-10-19 18:19
@flodnv  @lanitochka17  I am confused with the steps provided. 
I feel like this issue is similar to this - https://github.com/Expensify/App/issues/29917

Like when new user is selected it disappears from the list

**Comment by yakupafsin** [comment] 2023-10-19 20:17
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
The issue we are trying to address is related to the behavior when searching for users to add to a chat. When a user is not in our contacts list and is selected, they disappear from the search results. Even if we search for them again, they do not appear in the search list.


### What is the root cause of that problem?
This problem occurs because the new user is not returned in the getFilteredOptions function when they are selected. Consequently, they do not appear in the search results.


### What changes do you think we should make in order to solve the problem?
To solve this issue, we should implement a function that checks whether the user we are searching for is already in the selected user list. If the user is in the list, they should be displayed in the search results. The code to be added is as follows:

```javascript
const isOptionInList = _.some(selectedOptions, (selectedOption) => selectedOption.login === searchTerm);
        if (isOptionInList) {
            sectionsList.push({
                title: undefined,
                data: [_.find(selectedOptions, (selectedOption) => selectedOption.login === searchTerm)],
                shouldShow: !_.isEmpty(selectedOptions),
                indexOffset,
            });
            indexOffset += selectedOptions.length;
        }
```

This code should be integrated into the 'sections' section of the code, which can be found here: 

https://github.com/Expensify/App/blob/84be6705270da5d634bc57d6f7cf74c41469a5d5/src/pages/NewChatPage.js#L70


With these changes, even if the user we are searching for is not in our contacts list, they will remain in the search results until we delete the search text.


### What alternative solutions did you explore? (Optional)

An alternative solution would be to remove the following code block: 
https://github.com/Expensify/App/blob/84be6705270da5d634bc57d6f7cf74c41469a5d5/src/pages/NewChatPage.js#L74-L83
However, implementing this alternative solution would cause issues in the long term, as all users previously added to the chat would reappear in the search results, making it difficult to search for new users.

**Comment by thienlnam** [comment] 2023-10-19 21:38
This is a dupe of this bug report https://github.com/Expensify/App/issues/29917
Going to close and consolidate the efforts there

**Closed by thienlnam** 2023-10-19 21:38 UTC
Labels: DeployBlockerCash, External, Engineering, Hourly, Help Wanted, Bug
