### ISSUE TITLE
Task - Infinite skeleton loader when creating a task with a VOIP assignee

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#40103] opened 2024-04-11 11:59 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.62.0
**Reproducible in staging?:** y
**Reproducible in production?:** y
**Issue found when executing PR:** https://github.com/Expensify/App/pull/38730
**Issue reported by:** Applause - Internal Team

## Action Performed:
1. Create a new task with an assignee of +18183305299

## Expected Result:
The task does not get created, the error message is displayed.

## Actual Result:
Infinite skeleton loader when creating a task with a VOIP assignee.

## Workaround:
n/a

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [x] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

https://github.com/Expensify/App/assets/93399543/fabc7ca2-46dc-4c82-9629-c041d8b62552

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by kbecciv** [comment] 2024-04-11 11:59
We think that this bug might be related to #vip-vsb

**Comment by kbecciv** [comment] 2024-04-11 12:01
@laurenreidexpensify FYI I haven't added the External label as I wasn't 100% sure about this issue. Please take a look and add the label if you agree it's a bug and can be handled by external contributors

**Comment by nkdengineer** [comment] 2024-04-11 15:01
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
Infinite skeleton loader when creating a task with a VOIP assignee.

### What is the root cause of that problem?
We clear the report in `faliureData` here so when the task isn't created the report show skeleton.

https://github.com/Expensify/App/blob/7d19f827dcee2c9ffb69fdef5a5055ffcbf39b56/src/libs/ReportUtils.ts#L5145-L5150


### What changes do you think we should make in order to solve the problem?
1. We should generate an error for `createdChat` instead of clearing the chat report in `failureData`.

2. We also shouldn't clear the optimistic personal detail because now we keep the report data, the skeleton will display in header when the request is fail. We should keep the optimistic personal detail to fix this as well and then when we clear the report, we already have the logic to clear optimistic personal detail in `deleteReport` function.

https://github.com/Expensify/App/blob/7d19f827dcee2c9ffb69fdef5a5055ffcbf39b56/src/libs/ReportUtils.ts#L5145-L5159

### What alternative solutions did you explore? (Optional)
NA

**Comment by laurenreidexpensify** [comment] 2024-04-12 09:55
This doesn't seem a high value bug to fix given tasks + VOIP assignment are likely an edge case at this point in development. Am closing.

**Closed by laurenreidexpensify** 2024-04-12 09:55 UTC
Labels: Daily, Bug
