### ISSUE TITLE
[HOLD for payment 2023-08-07] [$1000] mWeb- Image is displayed larger then normal when we send vertical image with text on android chrome

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#22363] opened 2023-07-06 18:41 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Open the app
2. Open any report
3. Send any normal message
4. Type any normal message and click on plus
5. Click on add attachment
6. Select any vertical image and click on send
7. Observe that image is displayed larger then normal, to compare, send same image again normally without any text

## Expected Result:
App should display image in normal size if we send the image along with text

## Actual Result:
App displays image larger then normal if we send vertical image along with text

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [x] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [ ] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 1.3.37-2
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/93399543/cb9eacf9-3ab9-4506-9cb6-c6f373f76ff0

https://github.com/Expensify/App/assets/93399543/e273cfbd-bc34-47bb-a8b9-7be7712e69a2

**Expensify/Expensify Issue URL:**
**Issue reported by:** @dhanashree-sawant
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1688634116891079

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01d1b35099ea0fe207</li>
        <li>Upwork Job ID: 1678791252929392640</li>
        2023-07-18<li>Automatic offers: </li>
<ul>
<li> |  | 0</li>
<li>ginsuma | Contributor | 25679036</li>
<li>dhanashree-sawant | Reporter | 25679037</li>
</ul></li>
    </ul>
</details>

**Comment by sakluger** [comment] 2023-07-11 15:39
Good find, we should fix this.

**Comment by sarious** [comment] 2023-07-11 21:46
## Proposal

### Please re-state the problem that we are trying to solve in this issue.

Image is displayed larger then normal when we send vertical image with text on android chrome

### What is the root cause of that problem?

The root of the problem is that `this.props.windowHeight` returns window height that calculated on each dimension change. But in moment of attaching document the Virtual Keyboard is shown, and `this.props.windowHeight` return the value that equal to windowSize minus keyboardSize. So the calculations of `thumbnailScreenHeight` is incorrect. 

### What changes do you think we should make in order to solve the problem?

To fix the problem, we need to get window height without Virtual Keyboard. It will be real height of App view and it fix calculations of `thumbnailScreenHeight`, because the result will be consistant across same imageHeight and will be not depend on visibility of Virtual Keyboard.

So, to get initial window height without Virtual Keyboard we can invoke `Dimensions.get('window')` outside the class component. If we invoke it inside method or constructor it returns incorrect height (without Virtual Keyboard height)
<img width="334" alt="image" src="https://github.com/Expensify/App/assets/6162207/e5eb722b-e631-4fa4-a2e3-3e2c662bf0b5">

And use it instead of `this.props.windowHeight`:

<img width="622" alt="image" src="https://github.com/Expensify/App/assets/6162207/be7cb544-9ef8-492b-9597-fb6bf07c38c5">


### What alternative solutions did you explore? (Optional)
N/A

**Comment by rushatgabhane** [comment] 2023-07-13 05:49
reviewing today

**Comment by sakluger** [comment] 2023-07-17 21:20
@rushatgabhane were you able to review yet? If not, could you please prioritize this one?

**Comment by sakluger** [comment] 2023-07-20 22:36
Posted in #contributor-plus to make sure we can prioritize reviewing this issue.

**Comment by rushatgabhane** [comment] 2023-07-21 07:47
@sarious your proposal won't work when the window is resized on web

**Comment by rushatgabhane** [comment] 2023-07-21 08:14
I think we should go with @ginsuma's [proposal](https://github.com/Expensify/App/issues/22363#issuecomment-1631196759).

C+ reviewed 🎀 👀 🎀

**Comment by sarious** [comment] 2023-07-22 05:39
> @sarious your proposal won't work when the window is resized on web your root cause is correct tho

I see. We can improve my proposal, and use `dimensions.height` only if `canUseTouchScreen` returns `true`:

`const windowHeight = DeviceCapabilities.canUseTouchScreen() ?  dimensions.height : this.props.windowHeight;`

It looks similar to  @ginsuma's proposal, but it seems that it's better to use window height. In @ginsuma proposal height of screen was used. But Window Height not equal to Screen Height, so the thumbnail height will be differ from initial (before fix). 
Just wanted you know about this problem. If you are ok with that, you can continue with @ginsuma proposal.

**Comment by rushatgabhane** [comment] 2023-08-03 04:58
WIP ⚠️ 

1. The PR that introduced the bug has been identified. Link to the PR:

2. The offending PR has been commented on, pointing out the bug it caused and why, so the author and reviewers can learn from the mistake. Link to comment:

3. A discussion in #expensify-bugs has been started about whether any other steps should be taken (e.g. updating the PR review checklist) in order to catch this type of bug sooner. Link to discussion:

4. Determine if we should create a regression test for this bug.

5. If we decide to create a [regression test](https://github.com/Expensify/App/blob/main/contributingGuides/REGRESSION_TEST_BEST_PRACTICES.md) for the bug, please propose the regression test steps to ensure the same bug will not reach production again

**Comment by rushatgabhane** [comment] 2023-08-03 05:19
Created a manual request - https://staging.new.expensify.com/r/530127434800510

**Comment by sakluger** [comment] 2023-08-07 16:15
**Summarizing payouts for this issue:**

Bug reporter: @dhanashree-sawant $250 (hired and paid on Upwork)
Contributor: @ginsuma $1000 (hired on Upwork)
Contributor+: @ $1000 (payable via Manual Request after BZ checklist is completed)

Upwork job: https://www.upwork.com/jobs/~01d1b35099ea0fe207

**Comment by sakluger** [comment] 2023-08-07 16:20
Paid everyone through Upwork, @JmillsExpensify and @anmurali passing the issue to you for C+ payment to Rushat via manual request.

**Comment by rushatgabhane** [comment] 2023-08-07 17:02
@sakluger you can close this issue because the payment will be tracked on new dot

**Comment by sakluger** [comment] 2023-08-07 20:20
I believe that we need to wait until @JmillsExpensify or @anmurali comments that the payment is approved before we can close out the issue.

@rushatgabhane let me know if I missed an announcement, but I think that's still the current process.

**Comment by JmillsExpensify** [comment] 2023-08-08 03:37
Reviewed the details for @rushatgabhane. This is approved for payment on NewDot.

**Comment by sakluger** [comment] 2023-08-08 17:32
Thanks! We're all set here.

**Closed by sakluger** 2023-08-08 17:32 UTC
Labels: External, Daily, Awaiting Payment, Bug
