### ISSUE TITLE
Account switcher - App crashes when tapping on the currently active account

### ISSUE THREAD

**Issue by IuliiaHerets** [Expensify/App#48247] opened 2024-08-29 09:54 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** v9.0.26-1
**Reproducible in staging?:** Y
**Reproducible in production?:** N
**Email or phone of affected tester (no customers):** applausetester+kh050806@applause.expensifail.com
**Issue reported by:** Applause Internal Team

## Action Performed:
1. Go to staging.new.expensify.com
2. Log in as copilot.
3. Go to Account settings.
4. Tap on account switcher.
5. Tap on the current account.

## Expected Result:
App will not crash.

## Actual Result:
App crashes.

## Workaround:
Unknown

## Platforms:

- [x] Android: Native
- [ ] Android: mWeb Chrome
- [x] iOS: Native
- [ ] iOS: mWeb Safari
- [ ] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos
[2908.txt](https://github.com/user-attachments/files/16797141/2908.txt)

https://github.com/user-attachments/assets/0da77dac-c7e8-4057-ad00-409f45c4c746

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by puneetlath** [comment] 2024-08-29 14:15
I'm demoting this since Copilot is under beta. cc @rushatgabhane

**Comment by CyberAndrii** [comment] 2024-08-30 10:31
@IuliiaHerets can you still reproduce this crash? In my case on main the only issue is that the popover doesn't close automatically so I have to click outside to close it

https://github.com/user-attachments/assets/bfc200f5-9052-48c5-b981-a98b47d04c48

**Comment by IuliiaHerets** [comment] 2024-08-30 12:26
@CyberAndrii QA team still can repro the issue. Build - v9.0.26-4

https://github.com/user-attachments/assets/7692c61b-4943-40fb-8fd9-f547ec56c379

**Comment by rushatgabhane** [comment] 2024-08-30 12:28
please close this issue. it is a regression from #43656

**Closed** 2024-08-30 17:03 UTC
Labels: Engineering, Daily, Bug
