### ISSUE TITLE
[HOLD for payment 2024-07-24] [$500] Expense - Main chat and transaction thread with RBR are not dismissed after dismissing error

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#43481] opened 2024-06-11 14:13 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.81-8
**Reproducible in staging?:** Y
**Reproducible in production?:** Y 
**If this was caught during regression testing, add the test name, ID and link from TestRail:** https://expensify.testrail.io/index.php?/tests/view/4606839
**Issue reported by:** Applause - Internal Team

## Action Performed:
Precondition:
- User A and B have no chatted before
- Both accounts must be new
1. Go to staging.new.expensify.com
2. [User A] Go offline
3. [User A] Submit an expense to User B
4. [User B] Submit an expense with the same amount to User A
5. [User A] Go online
6. [User A] Go to the transaction thread with RBR
7. [User A] Dismiss the error in transaction thread

## Expected Result:
Both the main chat and transaction thread with RBR will be dismissed after dismissing the error in transaction thread

## Actual Result:
After dismissing the error in transaction thread, the transaction thread shows empty details. The main chat with RBR is not dismissed
When revisiting the transaction thread, the expense preview becomes skeleton

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [x] Android: mWeb Chrome
- [x] iOS: Native
- [x] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details> 

https://github.com/Expensify/App/assets/78819774/72d60228-e273-41a2-811a-a2659f4abd89

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01ab8ed867be0c34b8</li>
        <li>Upwork Job ID: 1800951566974761970</li>
        <li>Last Price Increase: 2024-06-26</li>
<li>Automatic offers: </li>
<ul>
<li>rojiphil | Reviewer | 102945559</li>
<li>bernhardoj | Contributor | 102945563</li>
</ul></li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @JmillsExpensify</details>

**Comment by lanitochka17** [comment] 2024-06-11 14:13
@laurenreidexpensify  FYI I haven't added the External label as I wasn't 100% sure about this issue. Please take a look and add the label if you agree it's a bug and can be handled by external contributors

**Comment by laurenreidexpensify** [comment] 2024-06-17 08:50
Waiting for proposals

**Comment by laurenreidexpensify** [comment] 2024-06-19 17:48
Increased bounty to see if we can get some proposals in

**Comment by laurenreidexpensify** [comment] 2024-06-19 17:48
Increased bounty to see if we can get some proposals in

**Comment by laurenreidexpensify** [comment] 2024-06-20 13:38
hey @JmillsExpensify handing this one over for my parental leave K2 clear out. we're still waiting to receive proposals on this one, equally you may consider closing out if you deem lower value than I have. Thanks!

**Comment by rojiphil** [comment] 2024-06-25 12:00
Not sure why there are no proposals yet here. 
Just posted in slack [here](https://expensify.slack.com/archives/C01GTK53T8Q/p1719316795682079) to get more eyes on this.

**Comment by bernhardoj** [comment] 2024-06-25 15:39
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
The RBR in main chat and transaction thread are not dismissed after clearing the transaction error.

### What is the root cause of that problem?
When we clear the error, we just clear the money request report action error and the transaction error.
https://github.com/Expensify/App/blob/67f92c6fbe5dce7aff7ddd82b196bbc306ab9bf8/src/components/ReportActionItem/MoneyRequestView.tsx#L403-L414

The transaction thread (or IOU report in this case) still has RBR because there is still 1 action left that has an error, that is CREATED action, but we don't show the error. So, we still have the IOU report and transaction thread report in the onyx data.

### What changes do you think we should make in order to solve the problem?

If you notice here, we delete the transaction which would also delete the IOU report and its thread when needed, but only if the error is a receipt error.
https://github.com/Expensify/App/blob/67f92c6fbe5dce7aff7ddd82b196bbc306ab9bf8/src/components/ReportActionItem/MoneyRequestView.tsx#L407-L412

We can expand this by removing the receipt error check so that any error will have the same behavior.

Applying this solution will delete the IOU report and transaction thread, so there will be no RBR for both of those reports, but the main chat will still show the RBR because the main chat also has an error in the CREATED action which is shown from this component.
https://github.com/Expensify/App/blob/67f92c6fbe5dce7aff7ddd82b196bbc306ab9bf8/src/pages/home/report/ReportActionItemCreated.tsx#L55-L61

I think it's fine because the main chat creation error and the transaction creation error are different, but in case we want to delete the main chat too, we can check whether the chat report failed to create or not, if yes, then we call `navigateToConciergeChatAndDeleteReport`.

```
if (transaction.pendingAction === 'add') {
    deleteTransaction(parentReport, parentReportAction);
    const chatReportID = parentReport?.parentReportID ?? '';
    if (ReportUtils.getAddWorkspaceRoomOrChatReportErrors(chatReportID)) {
        Report.navigateToConciergeChatAndDeleteReport(chatReportID);
    }
}
```

_we will need to update getAddWorkspaceRoomOrChatReportErrors to accept report or reportID_

https://github.com/Expensify/App/assets/50919443/5f7263f5-5274-44bf-878b-f9ba64573e87

**Comment by rojiphil** [comment] 2024-06-25 17:18
@bernhardoj Thanks for your proposal. 

> but in case we want to delete the main chat too, we can check whether the chat report failed to create or not, if yes, then we call navigateToConciergeChatAndDeleteReport.

This makes sense as it goes as per the expected behavior mentioned in OP. Also, this is how it behaves when the errors are cleared in main chat on creation failure. Can you propose an implementation for this? 
Wondering if we can identify whether the chat report has failed to create via `createChat` errorField. And then we call  `navigateToConciergeChatAndDeleteReport`. Would this not work?

**Comment by bernhardoj** [comment] 2024-06-26 03:06
I already provide a code for that in my proposal.

**Comment by rojiphil** [comment] 2024-06-26 05:43
@bernhardoj 
> I already provide a code for that in my proposal.

1. I don’t see any reason to touch the error handling of receipts unless there is a problem related to that. Do you see any problem here?
2. The issue here has to do with error handling due to failure of chat creation which also results in failure of the money request report. While clearing the error from `chat report` neatly removes all the reports using `navigateToConciergeChatAndDeleteReport`, clearing the error from money request view does not. This is what we are addressing here. With this context, is it not enough to call  `navigateToConciergeChatAndDeleteReport` when the `money request report` and `chat report` has `createChat` errorFields? Or do you see any problem here? Maybe we can add another utility to check if there is `createChat` errorField in a report.

**Comment by bernhardoj** [comment] 2024-06-26 05:54
> I don’t see any reason to touch the error handling of receipts unless there is a problem related to that. Do you see any problem here?

Well, the opposite, I don't see any reason to make an exception for receipt error. It doesn't matter what causes the error, as long as the pendingAction is add, then the transaction fails to be created.

> With this context, is it not enough to call navigateToConciergeChatAndDeleteReport when the money request report and chat report has createChat errorFields?

There are 3 reports, chat report, money request report, and transaction thread report. `navigateToConciergeChatAndDeleteReport` only deletes the report that we pass to the param.
https://github.com/Expensify/App/blob/9862fdbc01fe36bdb6dee9554023178d9f476bdb/src/libs/actions/Report.ts#L2158-L2163

Calling `deleteTransaction` and `navigateToConciergeChatAndDeleteReport` will delete all 3 reports from the onyx storage.

> Maybe we can add another utility to check if there is createChat errorField in a report.

That's what `ReportUtils.getAddWorkspaceRoomOrChatReportErrors` do.

**Comment by rojiphil** [comment] 2024-06-26 06:17
> > I don’t see any reason to touch the error handling of receipts unless there is a problem related to that. Do you see any problem here?
> 
> Well, the opposite, I don't see any reason to make an exception for receipt error. It doesn't matter what causes the error, as long as the pendingAction is add, then the transaction fails to be created.

Why is there a need to send a `DeleteMoneyRequest` to the BE when chat creation itself failed? Whereas it does make sense to do this when there is receipt error simply because money request report exists in BE.

**Comment by rojiphil** [comment] 2024-06-26 06:17
> navigateToConciergeChatAndDeleteReport only deletes the report that we pass to the param.

Can you please have a look at `deleteReport` utility and reconfirm on this?

**Comment by rojiphil** [comment] 2024-06-26 06:18
> > Maybe we can add another utility to check if there is createChat errorField in a report.
> 
> That's what `ReportUtils.getAddWorkspaceRoomOrChatReportErrors` do.

This we can address at the PR stage. Meanwhile, let’s come to a common page on the main logic.

**Comment by bernhardoj** [comment] 2024-06-26 06:53
> Why is there a need to send a DeleteMoneyRequest to the BE when chat creation itself failed?

That makes sense, it would be unnecessary. 

> Can you please have a look at deleteReport utility and reconfirm on this?

It does delete the IOU report, my bad. Which means the transaction thread is still left. Updated my [proposal](https://github.com/Expensify/App/issues/43481#issuecomment-2189292535) to include deleting the transaction thread.

**Comment by rojiphil** [comment] 2024-06-26 07:21
Thanks for the updated proposal.
Using `navigateToConciergeChatAndDeleteReport` to clear the reports when chat creation fails sounds good. Also, we need to update `navigateToConciergeChatAndDeleteReport` so that transaction thread reports are cleared too. 
@bernhardoj [proposal](https://github.com/Expensify/App/issues/43481#issuecomment-2189292535) LGTM
🎀👀🎀 C+ reviewed

**Comment by arosiclair** [comment] 2024-06-26 13:42
> I think it's fine because the main chat creation error and the transaction creation error are different, but in case we want to delete the main chat too, we can check whether the chat report failed to create or not, if yes, then we call navigateToConciergeChatAndDeleteReport.

Hm I'm not sure about this either. I think it might be beneficial to separate clearing the money request error and the chat error. For example, if you sent a money request with some messages while offline, you would see a money request error and clear it and then you'd see a chat error and clear your messages. If we combine the two steps, everything would get deleted with not that much transparency.

@JmillsExpensify you have any thoughts on this?

**Comment by rojiphil** [comment] 2024-06-27 20:16
> I think it might be beneficial to separate clearing the money request error and the chat error. For example, if you sent a money request with some messages while offline, you would see a money request error and clear it and then you'd see a chat error and clear your messages. If we combine the two steps, everything would get deleted with not that much transparency.

@arosiclair Just to clarify, this is exactly how it works in normal error cases i.e. both chat errors and money request errors are handled separately. 
However, this issue is a special case where both the chat report and dependent reports failed to get created in the first place. As such, even the BE has no reference to these reports. Here I think we need to clear these redundant reports in FE just like how it is done when we clear such an error message on chat report. This seems to be the correct thing to do. Or am I missing something here?

**Comment by arosiclair** [comment] 2024-07-01 14:23
Bumped @JmillsExpensify for a second opinion

**Comment by arosiclair** [comment] 2024-07-01 16:08
Alright lets delete both the money request and chat with the same error

**Comment by bernhardoj** [comment] 2024-07-02 14:17
So, I notice a problem with the current approach of deleting both main and money request reports. When we call `navigateToConciergeChatAndDeleteReport`, it will pop the current page, which is the money request report, but the main report is still in the nav stack, so going back will show a not found report page.

https://github.com/Expensify/App/assets/50919443/eba51830-afb5-4d26-8bc1-32f914cc44a8

[main chat report, money request report]

press close error message, money request report pops out

[main chat report (not found), concierge chat report]

I think we should revisit what @arosiclair suggested.

**Comment by arosiclair** [comment] 2024-07-03 13:01
> When we call navigateToConciergeChatAndDeleteReport, it will pop the current page, which is the money request report, but the main report is still in the nav stack, so going back will show a not found report page.

Does it cause any issues if we make `navigateToConciergeChatAndDeleteReport` always pop everything off the stack up to the LHN?

**Comment by rojiphil** [comment] 2024-07-03 13:21
>> When we call navigateToConciergeChatAndDeleteReport, it will pop the current page, which is the money request report, but the main report is still in the nav stack, so going back will show a not found report page.
>>
> Does it cause any issues if we make navigateToConciergeChatAndDeleteReport always pop everything off the stack up to the LHN?

That's interesting thought. But I think it may not be a good user experience to clear-off the nav stack as the user will lose the navigation history.  
Further, we also have a genuine problem where the deleted reports may be somewhere within the stack. In this case, handling deletion individually will also not help.
Another option is to selectively remove all references to the deleted report from the nav stack. Would this work?

**Comment by bernhardoj** [comment] 2024-07-03 13:41
> Another option is to selectively remove all references to the deleted report from the nav stack. Would this work?

Tried this multiple times before (when working on other issues) but never succeeds.

> Further, we also have a genuine problem where the deleted reports may be somewhere within the stack. In this case, handling deletion individually will also not help.

We can follow the same pattern of `deleteTransaction`. We will use `Navigation.goBack` to the main chat report when deleting the expense report, `goBack` will pop out any screen between the current screen and the target screen (fallbackRoute) (max. 5 screens).
https://github.com/Expensify/App/blob/00e7b1ed9486e5a21594177b089bd423a0dc2181/src/libs/Navigation/Navigation.ts#L237-L249

**Comment by arosiclair** [comment] 2024-07-03 15:01
>  That's interesting thought. But I think it may not be a good user experience to clear-off the nav stack as the user will lose the navigation history.

I think resetting the navigation pretty much the point of  `navigateToConciergeChatAndDeleteReport` - to delete the current report and "reset" back to the concierge chat. It sounds like a bug that it only pops one screen off the stack since we can have an infinite number of nested reports. In this case we should pop two screens: the money request and the parent chat.

**Comment by rojiphil** [comment] 2024-07-04 09:53
> I think resetting the navigation pretty much the point of navigateToConciergeChatAndDeleteReport - to delete the current report and "reset" back to the concierge chat.

Ah! That makes good sense. Let us also bring the design team in the loop and be triply sure of this since, unlike the current behavior, this would result in a loss of navigation history.

@Expensify/Design Here is a special case where the chat report and related expense reports are not created in BE. However, it remains in FE and is waiting to be removed via error clearing operation.  The video in OP neatly demonstrates this.
But the problem here is that there could be references to the deleted reports in the navigation stack which would bring up `It’s not here` page. 
To overcome this, we are inclining towards resetting the navigation stack to the home page. 
What are your thoughts on this?

**Comment by shawnborton** [comment] 2024-07-04 10:05
I think that makes sense to me, yeah. When you say "reset back to Concierge - why Concierge and not just the general Inbox/LHN?

**Comment by dannymcclain** [comment] 2024-07-04 13:33
Makes sense to me too.

>When you say "reset back to Concierge - why Concierge and not just the general Inbox/LHN?

I assume this is because on desktop at least, you can't really have no chat selected—so we'd have to pick _some_ chat to land them on, right? On mobile I agree it'd be way better to just drop them at the inbox/LHN screen.

**Comment by rojiphil** [comment] 2024-07-04 14:17
> I assume this is because on desktop at least, you can't really have no chat selected—so we'd have to pick _some_ chat to land them on, right?

Yes. That's right.

**Comment by arosiclair** [comment] 2024-07-04 20:08
Cool so @bernhardoj can you test [that approach](https://github.com/Expensify/App/issues/43481#issuecomment-2206025932)?

**Comment by bernhardoj** [comment] 2024-07-05 15:55
That works. PR is ready!

cc: @rojiphil

**Comment by rojiphil** [comment] 2024-07-25 06:37
* [x]  [@rojiphil] The PR that introduced the bug has been identified. Link to the PR: [Offending PR](https://github.com/Expensify/App/pull/34087)
* [x]  [@rojiphil] The offending PR has been commented on, pointing out the bug it caused and why, so the author and reviewers can learn from the mistake. Link to comment: [Added comment](https://github.com/Expensify/App/pull/34087/files#r1690876725)
* [x]  [@rojiphil] A discussion in #expensify-bugs has been started about whether any other steps should be taken (e.g. updating the PR review checklist) in order to catch this type of bug sooner. Link to discussion: Not Required. Existing checklist is good enough to capture such issues.
* [x]  [@rojiphil] Determine if we should create a regression test for this bug. :  I think we should create a regression test for this as this introduces the ux of navigation to concierge chat during error scenario of chat creation.
* [x]  [@rojiphil] If we decide to create a regression test for the bug, please propose the [regression test](https://github.com/Expensify/App/blob/main/contributingGuides/REGRESSION_TEST_BEST_PRACTICES.md) steps to ensure the same bug will not reach production again. 

Test Steps
1. Go offline
2. Submit an expense to a new user
3. From another device, send a message to the user from step 2
4. Back to the main device, go online. The chat report of the new user will have a RBR.
5. Open the chat report and press the money request preview
6. Clears the error message
7. Verify you are navigated to concierge chat
8. (small screen) Go back and verify you land on LHN
9. Verify the chat and transaction report is gone from LHN

**Comment by rojiphil** [comment] 2024-07-25 06:52
@JmillsExpensify Checklist is done. And I have also accepted the offer. 
Over to you for processing the payment. Thanks.

**Comment by JmillsExpensify** [comment] 2024-07-26 00:35
Payment summary: 

 - Contributor: @bernhardoj $250 
 - Reviewer: @rojiphil $250

**Comment by JmillsExpensify** [comment] 2024-07-26 00:38
Contributor paid via Upwork and regression test created. @mallenexpensify can you confirm the payment summary so I can approve in NewDot?

**Closed by JmillsExpensify** 2024-07-26 00:38 UTC
Labels: External, Daily, Awaiting Payment, Bug

**Comment by mallenexpensify** [comment] 2024-07-26 00:49
Contributor: @bernhardoj  due $500 via NewDot (assigned date was a few days after eligibility date). Upwork contract cancelled. 
Contributor+: @rojiphil paid $500 via Upwork.

**Comment by JmillsExpensify** [comment] 2024-07-26 00:54
$500 approved for @bernhardoj
