### ISSUE TITLE
[$250] Chat - Chat reloads when changing from #focus to Most recent mode

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#47412] opened 2024-08-14 12:29 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 9.0.20-0
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**If this was caught during regression testing, add the test name, ID and link from TestRail:** N/A
**Email or phone of affected tester (no customers):** applausetester+kh050806@applause.expensifail.com
**Issue reported by:** Applause - Internal Team

## Action Performed:
1. Go to staging.new.expensify.com
2. Trigger #focus modal pop up by pasting Onyx.set('focusModeNotification', true); in the console
3. Click Settings on the pop up
4. Select Most recent

## Expected Result:
Chat report will not reload

## Actual Result:
Chat report reloads when changing from #focus to Most recent mode
This issue also occurs on mobile environment when the pop up appears in chat and user changes to Most recent mode

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details> 

https://github.com/user-attachments/assets/69818983-f5c8-4506-907f-7cfc0e2a901d

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01e8e6bd741ebc762d</li>
        <li>Upwork Job ID: 1825661286720810919</li>
        <li>Last Price Increase: 2024-08-26</li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @jayeshmangwani</details>

**Comment by lanitochka17** [comment] 2024-08-14 12:30
We think that this bug might be related to #vip-vsp

**Comment by strepanier03** [comment] 2024-08-19 22:29
Repro just fine on staging v9.0.22-5.

**Comment by jayeshmangwani** [comment] 2024-08-21 09:39
> This issue also occurs on mobile environment when the pop up appears in chat and user changes to Most recent mode

@daledah You mentioned that this is only available in a mobile environment. Could you please help me understand why that is?

**Comment by jayeshmangwani** [comment] 2024-08-21 12:56
Thank you for the proposal @daledah , but your solution doesn't work for me in two scenarios:

1. Start a new chat with a user, send a few messages, then follow the steps from the description.
2. Go to any IOU report and follow the steps from the description.


I am attaching the video below. Please check it for reference.

https://github.com/user-attachments/assets/2b6873c0-816b-4f93-b5f8-63cfba65053f

**Comment by huult** [comment] 2024-08-24 16:52
## Proposal

### Please re-state the problem that we are trying to solve in this issue.

Chat reloads when changing from #focus to Most recent mode

### What is the root cause of that problem?

When changing from #focus mode to Most Recent mode, the function`updateChatPriorityMode` will execute
https://github.com/Expensify/App/blob/0c8455280c738a5db596f34409a0a3177e682e7f/src/libs/actions/User.ts#L733-L742
`nextPriorityMode` will be set to `default`, and `priorityMode` will be set to `GSD`. Then, `openApp` will execute, which causes the issue to occur.
https://github.com/Expensify/App/blob/0c8455280c738a5db596f34409a0a3177e682e7f/src/libs/actions/App.ts#L68-L78

### What changes do you think we should make in order to solve the problem?

As commented "When someone switches their priority mode we need to fetch all their chats because only #focus mode works with a subset of a user's chats. This is only possible via the OpenApp command." we need to call openApp to fetch subset of a user's chat.

I think this ticket is not a bug. To improve the user experience without showing a skeleton, some thing like that:
```diff
// src/libs/actions/App.ts#L74
- openApp();
+ openApp(false);

// src/libs/actions/App.ts#L247
- function openApp() {
+ function openApp(isLoading?: boolean) { 
    getPolicyParamsForOpenOrReconnect().then((policyParams: PolicyParamsForOpenOrReconnect) => {
        const params: OpenAppParams = {enablePriorityModeFilter: true, ...policyParams};
-        API.write(WRITE_COMMANDS.OPEN_APP, params, getOnyxDataForOpenOrReconnect(true));
+.      API.write(WRITE_COMMANDS.OPEN_APP, params, getOnyxDataForOpenOrReconnect(true, isLoading));
    });
}

// src/libs/actions/App.ts#L204
- function getOnyxDataForOpenOrReconnect(isOpenApp = false): OnyxData {
+ function getOnyxDataForOpenOrReconnect(isOpenApp = false, isLoading = true): OnyxData {
    const defaultData = {
        optimisticData: [
            {
                onyxMethod: Onyx.METHOD.MERGE,
                key: ONYXKEYS.IS_LOADING_REPORT_DATA,
                value: true,
            },
        ],
        finallyData: [
            {
                onyxMethod: Onyx.METHOD.MERGE,
                key: ONYXKEYS.IS_LOADING_REPORT_DATA,
                value: false,
            },
        ],
    };
    if (!isOpenApp) {
        return defaultData;
    }
    return {
        optimisticData: [
            ...defaultData.optimisticData,
            {
                onyxMethod: Onyx.METHOD.MERGE,
                key: ONYXKEYS.IS_LOADING_APP,
-                value: true,
+                value: isLoading,
            },
        ],
        finallyData: [
            ...defaultData.finallyData,
            {
                onyxMethod: Onyx.METHOD.MERGE,
                key: ONYXKEYS.IS_LOADING_APP,
                value: false,
            },
        ],
    };
}

```

### What alternative solutions did you explore? (Optional)

If we know the current report data is the latest, there's no need to call `openApp`. We just need to update the condition like this
```diff
// src/libs/actions/App.ts#L72
- if (nextPriorityMode === CONST.PRIORITY_MODE.DEFAULT && priorityMode === CONST.PRIORITY_MODE.GSD) {
+ if (nextPriorityMode === CONST.PRIORITY_MODE.DEFAULT && priorityMode === CONST.PRIORITY_MODE.GSD && !isNewestReportData) {

```

Note:`isNewestReportData` does not currently exist. This is just an example in the code

**Comment by jayeshmangwani** [comment] 2024-08-24 18:31
I asked on #[expensify-open-source](https://expensify.slack.com/archives/C01GTK53T8Q/p1724524103040449) whether we really need to fix this issue, considering that a chat reload should be expected when calling the openApp command.

**Comment by jayeshmangwani** [comment] 2024-08-28 07:57
@daledah Can you please clarify what 'isFirstTimeLoaded' refers to in your alternate proposal?

**Comment by jayeshmangwani** [comment] 2024-08-28 17:13
Tested the changes from the @huult 's [Proposal](https://github.com/Expensify/App/issues/47412#issuecomment-2308454622), and they do work. 
So, if we don't want to show the skeleton when changing the priority mode, we can go with the @huult 's [Proposal](https://github.com/Expensify/App/issues/47412#issuecomment-2308454622).

🎀 👀 🎀 C+ reviewed

**Comment by thienlnam** [comment] 2024-08-28 17:38
Hmm, I'm not entirely convinced we need to fix this - but if it's just a case of correctly determining when to update the loading then it's something we can do here

**Comment by jayeshmangwani** [comment] 2024-08-28 17:47
I was also feeling the same, opened a  Slack discussion https://github.com/Expensify/App/issues/47412#issuecomment-2308487342, but it seems not getting any eyes on it

**Comment by thienlnam** [comment] 2024-08-28 17:57
yeah, after another look at the proposal - I don't think we should add this by adding a loading parameter into openApp that is only used for this. Just going to close this

**Closed by thienlnam** 2024-08-28 17:57 UTC
Labels: External, Daily, Help Wanted, Bug
