### ISSUE TITLE
[HOLD for payment 2024-12-20] [$250] Screen briefly flashes Chase feed page after connecting Amex feed and back to expensify

### ISSUE THREAD

**Issue by m-natarajan** [Expensify/App#53510] opened 2024-12-04 02:19 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 
**Reproducible in staging?:**
**Reproducible in production?:**
**If this was caught on HybridApp, is this reproducible on New Expensify Standalone?:**
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** @joekaufmanexpensify 
**Slack conversation** (hyperlinked to channel name): [ts_external_expensify_expense](https://expensify.slack.com/archives/C06ML6X0W9L/p1733261930976759)

## Action Performed:

1. Enable company card in workspace
2. Click Add card and choose Amex bank
3. Connect to Amex using Direct feed
4. Click Return to Expensify

## Expected Result:
User returned to company cards page

## Actual Result:
Screen briefly flashes Chase feed page 

## Workaround:
Unknown
## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Standalone
- [ ] Android: HybridApp
- [ ] Android: mWeb Chrome
- [x] iOS: Standalone
- [x] iOS: HybridApp
- [ ] iOS: mWeb Safari
- [ ] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

<details>
  <summary>Add any screenshot/video evidence</summary>

  
</details>

https://github.com/user-attachments/assets/3db9e5e2-9170-42bd-9a80-d7a41dc0ebaf

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~021866127944349300492</li>
        <li>Upwork Job ID: 1866127944349300492</li>
        <li>Last Price Increase: 2024-12-09</li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @joekaufmanexpensify</details>

**Comment by joekaufmanexpensify** [comment] 2024-12-04 19:48
We're discussing in the thread that maybe this will be fixed elsewhere

**Comment by DylanDylann** [comment] 2024-12-06 16:50
@mountiny @joekaufmanexpensify I tried to reproduce this bug from my side. I used a mock response from [here](https://github.com/Expensify/App/pull/52016#issuecomment-2460185482). Let's see this video

https://github.com/user-attachments/assets/61aa81c5-8e2b-4be9-92a0-7e650f67608e

When clicking mock data (it means that when BE returns data) the App opens the bank connection URL again. The RCA of this problem:

https://github.com/Expensify/App/blob/96f7fdd08417975208a996301259eac6af76126c/src/pages/workspace/companyCards/addNew/BankConnection/index.tsx#L72-L92

When isNewFeedConnected is true, we close the connection URL and navigate to the company card page. But this `useEffect` is triggered again before navigating --> the URL is opened again. You guys can see my log on the above video for more detail 


I suspect that this was caused by [this PR](https://github.com/Expensify/App/pull/53122) 
cc @allgandalf @VickyStash

**Comment by VickyStash** [comment] 2024-12-06 17:46
Hi, I'm Viktoryia from Callstack - expert contributor group - and I would like to work on this issue.

**Comment by VickyStash** [comment] 2024-12-09 08:56
Not overdue, staring to work on this one.

**Comment by VickyStash** [comment] 2024-12-09 14:28
I was able to reproduce it on ios without even connecting to the banks, with the next steps:
1. start the feed setup -> select Chase bank -> wait for webview open -> go back
2. start the feed setup -> select Amex bank -> wait for webview open -> go back -> for a **ms** (really quickly, watch the attached video in slow motion) you will see the Chase login page

https://github.com/user-attachments/assets/3e0dc084-2aa4-4eab-b6b5-8cd821881af5

**Comment by VickyStash** [comment] 2024-12-09 15:30
I think I was able to get rid of the screen flashing if I replace `Modal` with `ScreenWrapper` here, but trying to know why we needed `Modal` here:
https://github.com/Expensify/App/blob/7180a376382033abe083baabc0ce4ea40763e7b6/src/pages/workspace/companyCards/addNew/BankConnection/index.native.tsx#L72-L77

**Comment by VickyStash** [comment] 2024-12-10 15:21
The [PR](https://github.com/Expensify/App/pull/53863) has been opened for the review!

**Comment by mountiny** [comment] 2024-12-13 17:58
No regression test is required imho, there was not a specific PR that would cause this issue its was a design fault. pyaments will be in total for the project

**Closed by mountiny** 2024-12-13 17:58 UTC
Labels: External, Weekly, Awaiting Payment, Bug
