### ISSUE TITLE
[$500] IOU - After an IOU SmartScan creation error, the file is not downloaded

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#31845] opened 2023-11-24 17:07 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.3.2
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** Applause - Internal Team
**Slack conversation:**

**Issue found when executing PR** https://github.com/Expensify/App/pull/29790

## Action Performed:
1. Open New Expensify app
2. Navigate to any conversation
3. Click + -> Request Money -> Scan
4. Download the file from the example
5. Complete the creation of the IOU
6. Open the Money Request report chat
7. Click on "Download the file" after the IOU creation error appears

## Expected Result:
After the error of creating an IOU SmartScan file(check), the user should be able to download the file by clicking on "Download the file".

## Actual Result:
After IOU SmartScan creation error, the file (receipt) is not downloaded, nothing happens when clicking on "Download the file".

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [x] Android: mWeb Chrome
- [x] iOS: Native
- [x] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

https://github.com/Expensify/App/assets/93399543/8db7ed03-ea42-4316-b46d-1a65c1924625

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01020d12092d3ed7d9</li>
        <li>Upwork Job ID: 1728098006096576512</li>
        <li>Last Price Increase: 2023-11-24</li>
    </ul>
</details>

**Comment by shubham1206agra** [comment] 2023-11-24 17:41
## Proposal
### Please re-state the problem that we are trying to solve in this issue

After an IOU SmartScan creation error, the file is not downloaded

### What is the root cause of that problem?

This is due to a missing filename (making it undefined) in `fileDownload`, which throws the error.
```
error TypeError: Cannot read properties of undefined (reading 'trim')
    at splitExtensionFromFileName (FileUtils.ts:103:1)
    at Module.appendTimeToFileName (FileUtils.ts:119:1)
    at eval (index.ts:33:35)
```

`fileDownload` didn't get the correct filename due to a bug in `getReceiptError` as this function expects the filename to be present in the `receipt` object, which is incorrect as we can check with the type.

### What changes do you think we should make in order to solve the problem?

Add argument for filename in getReceiptError function
```js
function getReceiptError(receipt, filename) {
    return _.isEmpty(receipt)
        ? ErrorUtils.getMicroSecondOnyxError('iou.error.genericCreateFailureMessage')
        : ErrorUtils.getMicroSecondOnyxErrorObject({error: CONST.IOU.RECEIPT_ERROR, source: receipt.source, filename});
}
```

### What alternative solutions did you explore? (Optional)

**Comment by shubham1206agra** [comment] 2023-11-24 18:37
For reference
This is the receipt type
```ts
type Receipt = {
    receiptID?: number;
    source?: string;
    state?: ValueOf<typeof CONST.IOU.RECEIPT_STATE>;
};
```

**Comment by shubham1206agra** [comment] 2023-11-25 06:33
Nope, I also checked from the backend. This is the structure I got. The confusion about receipt will be resolved when IOU.js gets migrated to TS.
```json
{
    "amount": 0,
    "billable": false,
    "cardID": 17621655,
    "category": "",
    "comment": {
        "comment": ""
    },
    "created": "2023-11-25",
    "currency": "INR",
    "filename": "w_2396d6280fa6bd05322c143e2810e745fe4e5d5f.jpg",
    "hasEReceipt": false,
    "merchant": "(none)",
    "modifiedAmount": 0,
    "modifiedCreated": "",
    "modifiedCurrency": "",
    "modifiedMerchant": "",
    "originalAmount": 0,
    "originalCurrency": "",
    "parentTransactionID": "",
    "receipt": {
        "receiptID": 675782569,
        "source": "https://staging.expensify.com/receipts/w_2396d6280fa6bd05322c143e2810e745fe4e5d5f.jpg",
        "state": "SCANREADY"
    },
    "reimbursable": true,
    "reportID": "2000492459104116",
    "status": "Posted",
    "tag": "",
    "transactionID": "7229659494596007058"
}
```

**Comment by situchan** [comment] 2023-11-25 20:37
The offending PR will be reverted [here](https://github.com/Expensify/App/pull/31854)

**Comment by garrettmknight** [comment] 2023-11-27 16:42
Looks like we're going to apply a fix for the separate issue the PR introduced instead of reverting the PR.  We do have another issue open for this here https://github.com/Expensify/App/issues/28884 so I'm going to close this one.

**Closed by garrettmknight** 2023-11-27 16:42 UTC
Labels: External, Daily, Help Wanted, Overdue, Bug
