### ISSUE TITLE
[HOLD for payment 2023-12-18] [$500] ReportUtils.shouldReportBeInOptionList will always be falsy for specific reports

### ISSUE THREAD

**Issue by kubabutkiewicz** [Expensify/App#30842] opened 2023-11-03 13:15 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

During Typescript migration I noticed that in `SidebarUtils` module in `getOrderedReportIDs` function we have `allReportActions` param which is typed as `Record<string, ReportAction[]>`. It's used in `ReportUtils.shouldReportBeInOptionList` function. If we go deeper inside `ReportUtils.shouldReportBeInOptionList` it will be used in `ReportUtils.canAccessReport` then there it will be used in `ReportActionsUtils.getParentReportAction` which expects that  `allReportActions` will be a collection of object no collection of arrays, which could lead into problems. There is no bug which I noticed yet, but I think its worth of checking. 

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [x] Android: mWeb Chrome
- [x] iOS: Native
- [x] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos
<img width="1014" alt="image" src="https://github.com/Expensify/App/assets/25230417/15df45ec-54f1-4c9d-b705-1f5542bc064f">
<img width="1012" alt="image" src="https://github.com/Expensify/App/assets/25230417/433a088a-ca14-477f-99cd-1477de52ae5d">

Add any screenshot/video evidence

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01e1c89ccf309fa85a</li>
        <li>Upwork Job ID: 1721662000620908544</li>
        <li>Last Price Increase: 2023-11-27</li>
    </ul>
</details>

**Comment by DylanDylann** [comment] 2023-11-03 15:18
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
During Typescript migration I noticed that in SidebarUtils module in getOrderedReportIDs function we have allReportActions param which is typed as Record<string, ReportAction[]>. It's used in ReportUtils.shouldReportBeInOptionList function. If we go deeper inside ReportUtils.shouldReportBeInOptionList it will be used in ReportUtils.canAccessReport then there it will be used in ReportActionsUtils.getParentReportAction which expects that allReportActions will be a collection of object no collection of arrays, which could lead into problems. There is no bug which I noticed yet, but I think its worth of checking.

### What is the root cause of that problem?
We use 2 different type for ReportAction field

### What changes do you think we should make in order to solve the problem?
Let's see this function
https://github.com/Expensify/App/blob/bc9cb8f8ca149c1f90dd09de9f19ae97bcaf07f0/src/libs/ReportUtils.js#L3245

I saw all places where use this function, It seems allReportActions param is redundant and we should remove this param. It also helps us to avoid conflict about type for this field


### What alternative solutions did you explore? (Optional)

**Comment by johncschuster** [comment] 2023-11-06 22:53
Triaging

**Comment by johncschuster** [comment] 2023-11-10 22:26
This was only triaged a few days ago. Not overdue (still looking for proposals)

**Comment by DylanDylann** [comment] 2023-11-13 06:48
@johncschuster What do you think about my proposal [here](https://github.com/Expensify/App/issues/30842#issuecomment-1792630088)

**Comment by johncschuster** [comment] 2023-11-22 22:14
@aimane-chnaif what are your thoughts on the proposals above? Are we good to move forward or should we put the call out for more proposals?

**Comment by johncschuster** [comment] 2023-11-29 01:27
Bumped in Slack

**Comment by kubabutkiewicz** [comment] 2023-11-30 07:17
@aimane-chnaif Its wrongly typed for purpose to satisfy TS for now and thats why I created this issue, becuase the value is comming in the type which you wrote but then in other functions its used like its would be a `OnyxCollection<ReportActions>` and here is the problem. We need to fix that is one or either way. And now for example 
https://github.com/Expensify/App/blob/090dc3acd7ce1b263854fc9f2a854a4406338a5e/src/libs/ReportActionsUtils.ts#L115-L127
will always return `{}`

**Comment by kubabutkiewicz** [comment] 2023-11-30 08:22
@aimane-chnaif sure I can work on this if we are ok with removing this parameter

**Comment by NikkiWines** [comment] 2023-12-02 00:01
Looks good 👍

**Comment by johncschuster** [comment] 2023-12-15 21:57
# Payment Summary

@aimane-chnaif - $500 to be requested manually after December 18

**Comment by johncschuster** [comment] 2023-12-15 21:58
I will be OOO starting Monday, December 18, and will return Tuesday, January 2.

**Current status:** 
Payment Summary is written. This just needs to be manually closed after the regression wait period has passed.

If this issue is open when I'm back from OOO, I'll take it back over. Thank you!

**Comment by Christinadobrzyn** [comment] 2023-12-18 22:40
Awesome! No regressions, so paying this out based on this [payment summary](https://github.com/Expensify/App/issues/30842#issuecomment-1858536549) 

Hey @aimane-chnaif can you accept the offer here - https://www.upwork.com/jobs/~011082a49292d1645e

**Comment by Christinadobrzyn** [comment] 2023-12-19 23:31
Awesome! Paid @aimane-chnaif in Upwork based on this payment summary - https://github.com/Expensify/App/issues/30842#issuecomment-1858536549

Closing!

**Closed by Christinadobrzyn** 2023-12-19 23:31 UTC
Labels: Engineering, Daily, Internal, Awaiting Payment, Bug
