### ISSUE TITLE
[Pay 29/4] [$250] HIGH: [Polish] Combine image attachment with the unsent composed message

### ISSUE THREAD

**Issue by quinthar** [Expensify/App#35977] opened 2024-02-07 01:37 UTC
Problem:
===
Today when you upload an image while a message is drafted in the compose window, it:

1. Sends whatever is drafted
2. Sends a 2nd message containing only the image

This means that even if the two are conceptually related (ie, the comment is describing the image), it will be forked into separate reactions, and have separate threads.

Solution
====
Rather than sending images as a totally separate message, combine the message and the attachment into a single message, such that it gets the same reactions and are part of the same thread.

<details><summary>Issue Owner</summary>Current Issue Owner: @bfitzexpensify</details>

**Comment by roryabraham** [comment] 2024-02-07 04:31
Personally I think this issue kind of "beats around the bush" – I would love to see our efforts spent towards building full support for inline images in messages, GitHub-style, with previews inlined in react-native-live-markdown.

**Comment by jeremy-croff** [comment] 2024-02-07 06:24
> Personally I think this issue kind of "beats around the bush" – I would love to see our efforts spent towards building full support for inline images in messages, GitHub-style, with image previews inlined in react-native-live-markdown.

Is this really how our customers would use it?
Slack for example does not have inline images in messages, cause it's just chat.

Jira and GitHub have inline messages, because it's used for steps and detailed information, it's like a whole mini text editor. I think those use cases are more prosumer, rather than consumer.

**Comment by roryabraham** [comment] 2024-02-07 09:20
My opinion is that the inline image support offered by GitHub and Jira is superior in every way to the way images are handled by Slack, WhatsApp, iMessage, etc...

Those platforms don't make it any easier to add images to a message. The only advantage over GitHub for example is that you don't have to switch to the `Preview` tab to see how the image looks in your final message. But that limitation won't apply in New Expensify.

I believe that the inline image experience I'm proposing would be better than any of the other platforms we've listed here and as such would be a differentiating factor in our chat platform.

**Comment by quinthar** [comment] 2024-02-27 01:51
I agree with @roryabraham -- this is just a step in that direction.  A more complete plan is here: https://expensify.slack.com/archives/C01GTK53T8Q/p1708849229702429?thread_ts=1707270017.261459&cid=C01GTK53T8Q

**Comment by quinthar** [comment] 2024-02-27 01:51
I think we should start with this to fix our current image support, but I agree we should add true inline image support -- and ultimately, large object support as well.  But that's a bigger project that probably warrants a design doc, this is more low hanging fruit.

**Comment by tgolen** [comment] 2024-02-27 20:15
I confirmed a few things via Slack, and it sounds like this is the detailed path to move forward on this issue:

- When a comment is made that has both an attachment and a text comment
- Upload the file as normal
- Retrieve it's URL
- Format the URL like the HTML that results from the Markdown code from https://github.com/Expensify/App/issues/37246
- Add that HTML at the end of the text comment instead of creating a separate report action

**Comment by quinthar** [comment] 2024-03-23 00:24
https://github.com/Expensify/App/issues/37246 is on staging; I'm taking this off hold!  @tgolen can you give an ETA for when you can take it up?

**Comment by tgolen** [comment] 2024-03-25 14:42
I'll bump this up to daily and will add an ETA once I finish catching up on my others issues today.

**Comment by tgolen** [comment] 2024-03-25 20:19
# Daily Update
- I haven't made any progress on this today

### Next Steps
- Write a PR
- Get the PR reviewed then deployed

#### ETA
- PR created tomorrow, March 25
- PR merged the day after on Wednesday, March 26
- PR deployed to production on Monday, April 1

**Comment by tgolen** [comment] 2024-03-26 17:36
I ran into a small snag with this today once I realized that the backend changes will require corresponding frontend changes to the optimistic data. [I posted in slack about this](https://expensify.slack.com/archives/C01GTK53T8Q/p1711474431211109?thread_ts=1707270017.261459&cid=C01GTK53T8Q) to discuss a possible solution.

**Comment by tgolen** [comment] 2024-03-26 22:06
# Daily Update
- I created a draft [Web-E PR](https://github.com/Expensify/Web-Expensify/pull/41449) that combines the attachments and text into a single message
- I created a draft [App PR](https://github.com/Expensify/App/pull/39007) that updates the optimistic data
- I started [a convo in Slack](https://expensify.slack.com/archives/C01GTK53T8Q/p1711474431211109?thread_ts=1707270017.261459&cid=C01GTK53T8Q) to discuss how to deploy this without breaking anything

### Next Steps
- @quinthar Could you please look at [the slack convo](https://expensify.slack.com/archives/C01GTK53T8Q/p1711474431211109?thread_ts=1707270017.261459&cid=C01GTK53T8Q) and see if the proposed solution is acceptable?
- Once that thread is resolved I will implement the new changes in the existing PRs and submit them for review

#### ETA
- Web-E change merged by Thursday, March 28
- App changed merged by Tuesday, April 2

**Comment by tgolen** [comment] 2024-03-27 19:23
The slack discussion was resolved and this will be the rollout plan to ensure nothing breaks:

Background context:
There are two API commands on the backend:
- `AddComment` - Used for creating text-only comments
- `AddAttachment` - Used for creating attachment comments and accepts an optional text param

**Problem:**
The backend changes to combine text and attachments into a single message also require corresponding frontend changes to support the proper creation of optimistic data. Without both frontend and backend changes being deployed at the same time, attachments will be broken until both changes are deployed (which could be several days or weeks).

**Solution:**
Create a third API command called `AddAttachmentAndText` which will implement the new combined text+attachment message, and leave the other two API commands alone. Once the new API command has been deployed on the server, then the frontend can be updated to handle the new optimistic data format and switch from calling `AddAttachment` to `AddAttachmentAndText`.

**Comment by tgolen** [comment] 2024-03-28 21:38
# Daily Update
- The [Web PR](https://github.com/Expensify/Web-Expensify/pull/41449) is out of draft and in full review
- The [App PR](https://github.com/Expensify/App/pull/39007) is on hold

### Next Steps
- Merge/deploy the Web-E PR
- I will test the App PR on all platforms, then remove the HOLD once the Web-E PR has been deployed

#### ETA
- Web-E PR merged by Tuesday, April 2
- App PR merged by Friday, April 5

**Comment by tgolen** [comment] 2024-03-29 18:52
# Daily Update
- The [Web PR](https://github.com/Expensify/Web-Expensify/pull/41449) is still waiting to be reviewed
- The [App PR](https://github.com/Expensify/App/pull/39007) is on hold and has had full platform testing done to it so that it's ready for review

### Next Steps
- Merge/deploy the Web-E PR
- Un-HOLD the App PR and get it reviewed/merged

#### ETA
- Web-E PR merged by Tuesday, April 2
- App PR merged by Friday, April 5

**Comment by tgolen** [comment] 2024-04-02 14:47
# Daily Update
- The [Web-E PR](https://github.com/Expensify/Web-Expensify/pull/41449) was reviewed
- The [App PR](https://github.com/Expensify/App/pull/39007) is still on HOLD

### Next Steps
- @tgolen respond to the review from @neil-marcellini and get the PR approved and merged
- Un-HOLD the App PR and get it reviewed/merged

#### ETA
- Web-E PR merged by Wednesday, April 3 (updated)
- App PR merged by Tuesday, April 9 (updated)

**Comment by tgolen** [comment] 2024-04-02 22:48
# Daily Update
- The [Web-E PR](https://github.com/Expensify/Web-Expensify/pull/41449) has been updated and is entering a second round of reviews
- The [App PR](https://github.com/Expensify/App/pull/39007) is still on HOLD

### Next Steps
- @tgolen get the Web-E PR approved and merged
- Un-HOLD the App PR and get it reviewed/merged

#### ETA
- Web-E PR merged by Wednesday, April 3 (updated)
- App PR merged by Tuesday, April 9 (updated)

**Comment by tgolen** [comment] 2024-04-03 21:00
# Daily Update
- The [Web-E PR](https://github.com/Expensify/Web-Expensify/pull/41449) has one approval and is in final review
- The [App PR](https://github.com/Expensify/App/pull/39007) is still on HOLD

### Next Steps
- @Julesssss approve and merge the Web-E PR
- @tgolen Un-HOLD the App PR and get it reviewed/merged

#### ETA
- Web-E PR merged by Thursday, April 4 (updated)
- App PR merged by Tuesday, April 9

**Comment by tgolen** [comment] 2024-04-04 16:48
# Daily Update
- The [Web-E PR](https://github.com/Expensify/Web-Expensify/pull/41449) has been merged
- The [App PR](https://github.com/Expensify/App/pull/39007) is now off HOLD

### Next Steps
- @tgolen get App PR reviewed and merged

#### ETA
- App PR merged by Tuesday, April 9

> [!NOTE]
> I'm going to be OOO tomorrow and Monday so the ETA might get off a little if there are actions required while I am gone

**Comment by tgolen** [comment] 2024-04-11 21:04
@rayane-djouah It won't let me assign this to you until you comment on it. Can you please add a comment here and then I'll assign it.

**Comment by tgolen** [comment] 2024-04-11 21:04
Wait... you just commented above me :D weird

**Comment by tgolen** [comment] 2024-04-11 21:05
@bfitzexpensify can you please ensure @rayane-djouah gets paid for a C+ review of [the PR](https://github.com/Expensify/App/pull/39007)?

**Comment by bfitzexpensify** [comment] 2024-04-15 15:33
PR was assigned for review (and the review began) before the price for a PR review was updated, so payment for @rayane-djouah is $500. Offer sent via Upwork. 

Looks like the PR is merged but not yet deployed. I've subscribed and will update the payment date here.

**Comment by bfitzexpensify** [comment] 2024-04-22 19:31
Deployed today, updated title.

**Comment by quinthar** [comment] 2024-04-27 19:25
Should this be tagged `Awaiting Payment`? Why wasn't it automatically?

**Comment by bfitzexpensify** [comment] 2024-04-30 19:01
All done here.

**Closed by bfitzexpensify** 2024-04-30 19:01 UTC
Labels: Reviewing, Engineering, Daily, Improvement, Bug
