### ISSUE TITLE
[HOLD for payment 2024-07-24] [Search v1] Improvements to grouped expenses on the Search page

### ISSUE THREAD

**Issue by shawnborton** [Expensify/App#44131] opened 2024-06-21 07:14 UTC
We're finding that the bold report title style and "X grouped expenses" feels a bit jarring when we show grouped expenses on the Search page. To help make this page feel more consistent, we'd like to make the following changes on Desktop Search for grouped expenses:

- don't use bold for the report title, use the same font as everywhere else
- remove the HR line that is above the expenses and below the title
- remove X grouped expenses text
- move the expense type icon to the left of the row
- use a more subtle style for view button
    - I think the best idea would be to add a 4th style to our buttons, basically a "link button" style ([inspo](https://getbootstrap.com/docs/4.0/components/buttons/) from Bootstrap). This would use the same height/font/sizing props as all other buttons, but they wouldn't have a BG color and would use our link color instead
- use combined RBR + button pattern when needed. Our buttons already support having an icon in them, we'd just pass the RBR icon plus a color 

That gives us something like this for desktop:
![image](https://github.com/Expensify/App/assets/2319350/84973576-c1f8-4c72-9fbc-0a26519438eb)

For mobile, we'll take a few similar approaches:
- remove the X grouped expenses text
- don't use bold for the title or amount
- use combined RBR button
![CleanShot 2024-06-21 at 09 13 37@2x](https://github.com/Expensify/App/assets/2319350/8d4119c0-50e8-4d05-9fea-c1f0f97333af)

Also note: we'll want to make sure this [PR](https://github.com/Expensify/App/pull/43733) gets merged first since it has some font changes we'll want here

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~0116b9010289ce564f</li>
        <li>Upwork Job ID: 1804172877990281426</li>
        <li>Last Price Increase: 2024-06-21</li>
<li>Automatic offers: </li>
<ul>
<li>dominictb | Contributor | 102873381</li>
</ul></li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @adelekennedy</details>

**Comment by shawnborton** [comment] 2024-06-24 10:43
> Maybe it is not implemented in staging, right? Now, all the button have "View" title.

Yeah, none of this is on staging. But what I meant by that comment was that our buttons have a prop where they can take an icon, so we get buttons that look like this:
![CleanShot 2024-06-24 at 12 43 11@2x](https://github.com/Expensify/App/assets/2319350/4d1c1905-59b0-48b1-8ed0-213c9a6bf05f)

So I'm saying we can pass in the "dot indicator" icon we have, but also pass in a color (danger red) for it, too.

**Comment by JmillsExpensify** [comment] 2024-06-25 00:16
@sobitneupane Do you mind prioritizing this one when you're online. These are important polish items we'd like to get in product and stress test as soon as we reasonably can.

**Comment by sobitneupane** [comment] 2024-06-25 10:05
Thanks for the proposal @dominictb 

Overall your [proposal](https://github.com/Expensify/App/issues/44131#issuecomment-2183951126) looks good to me. I think we should prioritize moving on to the PR, where we can address the minor details.

🎀 👀 🎀 C+ reviewed

**Comment by JmillsExpensify** [comment] 2024-06-27 01:25
Quick comment since we just started working on the PR. @shawnborton didn't we agree to remove tags on mobile, and in addition the folder icon for categories since only a category will appear on that line moving forward?

**Comment by shawnborton** [comment] 2024-06-27 05:28
Yup, but I think we should do that as a separate GH? Maybe even consider doing the Merchant/Description idea too where we show the Description in place of Merchant if no Merchant is available on mobile?

**Comment by JmillsExpensify** [comment] 2024-06-28 23:50
Cool, we can go that route too.

**Comment by sobitneupane** [comment] 2024-07-01 07:54
Any update on PR @dominictb?

**Comment by shawnborton** [comment] 2024-07-01 13:39
Ah, I guess we haven't implemented the red dots yet for violations so I think we can skip that part for now. @luacmartins does that sound right? When do we plan to add violations here?

**Comment by luacmartins** [comment] 2024-07-02 17:53
Violations are blocked on the migration to Auth, so whenever that project is ready.

**Comment by luacmartins** [comment] 2024-07-02 17:54
I agree that we don't need to worry about them in the meantime though

**Comment by adelekennedy** [comment] 2024-07-25 03:44
Payouts due:

- [ ] Contributor: $250 @dominictb (Upwork)
- [ ] Contributor+: $250 @sobitneupane (NewDot)

**Comment by adelekennedy** [comment] 2024-07-25 03:46
I don't think we need a regression test here so closing this one out (please reopen if I'm wrong!)

**Closed by adelekennedy** 2024-07-25 03:46 UTC
Labels: External, Daily, NewFeature, Awaiting Payment

**Comment by JmillsExpensify** [comment] 2024-07-29 22:28
$250 approved for @sobitneupane
