### ISSUE TITLE
[$1000] Help tab on settings page should have external link icon like Settings->about->View open jobs and not the current navigation icon

### ISSUE THREAD

**Issue by kavimuru** [Expensify/App#14693] opened 2023-01-31 15:56 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:

1. Open the app
2. Open settings
3. Click on any tab other then Help, it will have sub menu
4. Click on Help tab, it will open expensify help link in new tab
5. Observe that Help tab, even though being a link, has navigation icon

## Expected Result:
Help tab should have link icon similar to Settings->about->View open jobs, Settings->Workspaces->select any workspace->Pay bills-> View all bills
<img width="355" alt="image" src="https://user-images.githubusercontent.com/14225673/215896645-18f11dc1-0d4d-4b21-85ca-e8f1deb13e87.png">

## Actual Result:
Help tab has navigation icon which provides a impression that it has submenu and is inconsistent with all the link tabs throughout the application
<img width="364" alt="image" src="https://user-images.githubusercontent.com/14225673/215896737-fe3f1f04-edd9-4d8b-bab7-73e3f019dbd0.png">

## Workaround:
unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [x] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:**  v1.2.62-1
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** 
![image (3)](https://user-images.githubusercontent.com/43996225/215811225-5a29fc95-3697-42d9-bdcf-4294ea2689ba.png)
![image (4)](https://user-images.githubusercontent.com/43996225/215811255-31cf2c08-9edf-4c1c-a66e-2c080abbd27d.png)
![image (5)](https://user-images.githubusercontent.com/43996225/215811270-f26affbd-1678-4348-9db4-49f478de1bab.png)

https://user-images.githubusercontent.com/43996225/215811298-0d72d87c-a634-4dcb-ad92-142d9a9dcf0d.mp4

**Expensify/Expensify Issue URL:**
**Issue reported by:** @dhanashree-sawant
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1674552068263369

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01c4af5c2d37b31ee4</li>
        <li>Upwork Job ID: 1620547622358687744</li>
        <li>Last Price Increase: 2023-01-31</li>
    </ul>
</details>

**Comment by Tushu17** [comment] 2023-01-31 22:22
### Proposal

We need to pass `iconRight: Expensicons.NewWindow,` in Get assistance page :-
https://github.com/Expensify/App/blob/93854081336980a19b02138a271fead29b37e5d9/src/pages/GetAssistancePage.js#L41-L47

and settings page :-

https://github.com/Expensify/App/blob/93854081336980a19b02138a271fead29b37e5d9/src/pages/settings/InitialSettingsPage.js#L174-L178 

We also need to add pass `iconRight={item.iconRight}` in `MenuItem` :-
https://github.com/Expensify/App/blob/93854081336980a19b02138a271fead29b37e5d9/src/pages/settings/InitialSettingsPage.js#L197

**Comment by PrashantMangukiya** [comment] 2023-02-01 00:44
**Proposed Solution:**
We have to add iconRight props for the help menu as shown under

Within `src/pages/settings/InitialSettingsPage.js` file we have to add code as shown under:

```javascript
getDefaultMenuItems() {
    return ([
	…
        {
            translationKey: 'initialSettingsPage.help',
            icon: Expensicons.QuestionMark,
            iconRight: Expensicons.NewWindow, // Add this code
            action: () => { Link.openExternalLink(CONST.NEWHELP_URL); },
        },
    ]);
}

getMenuItem(item, index) {
    return (
        <MenuItem
           …
           floatRightAvatars={item.floatRightAvatars}
           shouldStackHorizontally={item.shouldStackHorizontally}
           iconRight={item.iconRight}  // Add this code
        />
    );
}
```

**Comment by situchan** [comment] 2023-02-01 00:56
### **Proposal**

There are 3 cases I found so far that don't have correct icon when go to external link on menu item click:
`Help` on Settings page, `Schedule a setup call`, `Explore help docs` on Get assistance page

- add `iconRight: Expensicons.NewWindow,` to these places:
https://github.com/Expensify/App/blob/be6dfe292e38d228c3583f16974c6056832bf695/src/pages/settings/InitialSettingsPage.js#L174-L178
https://github.com/Expensify/App/blob/be6dfe292e38d228c3583f16974c6056832bf695/src/pages/GetAssistancePage.js#L41-L47
https://github.com/Expensify/App/blob/be6dfe292e38d228c3583f16974c6056832bf695/src/pages/GetAssistancePage.js#L52-L58

- pass `iconRight` prop to `MenuItem` in `InitialSettingsPage`:
https://github.com/Expensify/App/blob/be6dfe292e38d228c3583f16974c6056832bf695/src/pages/settings/InitialSettingsPage.js#L197-L212
```diff
+               iconRight={item.iconRight}
```

**Comment by anmurali** [comment] 2023-02-02 22:52
@rushatgabhane @cristipaval thoughts on these proposals?

**Comment by cristipaval** [comment] 2023-02-04 05:40
Thanks @rushatgabhane !
Agree with you. Let's go with @situchan 's solution. cc @anmurali

**Comment by Tushu17** [comment] 2023-02-04 06:16
@cristipaval @rushatgabhane, The schedule call redirect was not in the scope of this issue (if I knew that it was, I would have added that to my solution), and I saw a few issues where the contributor who increased the scope of the issue is paid separately from the one who posted the solution first, like [here](https://github.com/Expensify/App/issues/13940#issuecomment-1372943100).

**Comment by cristipaval** [comment] 2023-02-06 08:14
Waiting for @situchan 's solution.

**Comment by situchan** [comment] 2023-02-06 09:44
We can close this issue. The solution was already merged into `main` during weekend from #14641.
It was already being done internally.

**Comment by cristipaval** [comment] 2023-02-06 10:44
Oh I see.. Thanks @situchan!

**Closed by cristipaval** 2023-02-06 10:44 UTC
Labels: External, Daily, Help Wanted, Overdue, Bug

**Comment by dhanashree-sawant** [comment] 2023-02-06 10:55
Hello @cristipaval , good to hear that bug is resolved. I am the reporter for this bug. I saw that it was being worked internally but when I saw the pull request, the steps seems to be exactly same as what I reported on slack. There is a slack link in pull request but I don't have access to it. By any chance, if they had referenced my bug report to start the internal issue, will I be compensated for reporting it? Can you once check and let me know?
Here is the link to my slack bug report:
https://app.slack.com/client/T03SC9DTT/threads/thread/C049HHMV9SM-1674552068.263369

**Comment by cristipaval** [comment] 2023-02-06 12:23
Hey @dhanashree-sawant ! Thanks for raising your concern. @anmurali is in charge with the payment, she will reply soon.

**Comment by dhanashree-sawant** [comment] 2023-02-11 08:54
Hi @anmurali , kindly let me know your thoughts on my above comment.

**Comment by anmurali** [comment] 2023-02-20 20:14
Paid.
