### ISSUE TITLE
[$500] IOU- In distance request, user unable to edit amount

### ISSUE THREAD

**Issue by izarutskaya** [Expensify/App#30331] opened 2023-10-25 09:36 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.3.90-1

**Reproducible in staging?:** Y

**Reproducible in production?:** Y

**If this was caught during regression testing, add the test name, ID and link from TestRail:**

**Email or phone of affected tester (no customers):**

**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Expensify/Expensify Issue URL:**

**Issue reported by:** Applause-Internal Team

**Slack conversation:** @

## Action Performed:
1. Launch app
2. Tap on a Workspace chat
3. Tap plus icon and select request money
4. Tap distance
5. Enter start and finish waypoints
6. Tap next
7. Tap on Amount

## Expected Result:
When user taps on amount, he must be able to edit amount.

## Actual Result:
When user taps on amount, it does not trigger any action and user unable to edit amount.

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [x] Android: mWeb Chrome
- [x] iOS: Native
- [x] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos
<details>
<summary>Android: Native</summary>

</details>

<details>
<summary>Android: mWeb Chrome</summary>

https://github.com/Expensify/App/assets/115492554/951a59e4-90e2-459a-99b4-3635f7a209e7

</details>

<details>
<summary>iOS: Native</summary>

</details>

<details>
<summary>iOS: mWeb Safari</summary>

</details>

<details>
<summary>MacOS: Chrome / Safari</summary>

</details>

<details>
<summary>MacOS: Desktop</summary>

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~0116de5be45e362471</li>
        <li>Upwork Job ID: 1717112900168441856</li>
        <li>Last Price Increase: 2023-10-25</li>
    </ul>
</details>

**Comment by brunovjk** [comment] 2023-10-25 12:41
@izarutskaya, @dukenv0307 Should the user be able to change the value manually or just using distance?

I believe that this value is automatically calculated according to the ratio and distance entered.
The issue here is that the value is calculated once, and then when changing the starting or ending points, the value is not recalculated. There is already an [issue ](https://github.com/Expensify/App/issues/27051) about this, but it was closed as a dupe of https://github.com/Expensify/App/issues/26946

Do you know anything about @cubuspl42?

**Closed** 2023-10-25 16:10 UTC
Labels: External, Daily, Help Wanted, Bug
