### ISSUE TITLE
[HOLD for payment 2023-08-07] [$1000] Chat - Extra line breaks added when pasting text from code editor

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#22890] opened 2023-07-14 12:51 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Navigate to staging.new.expensify.com
2. Copy the text from code editor: https://github.com/Expensify/App/blob/403fc28984e9d96f3127257a3dc3ac6e66a75cd6/src/components/TextInputFocusable/index.js#L263-L267
3. Paste the text in the compose box of a conversation in New Expensify

## Expected Result:
Pasted text should be correctly displayed with the expected line breaks in the compose box

## Actual Result:
Pasted text should be correctly displayed - extra line breaks added when pasting text from code editor

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [x] Windows / Chrome 
- [ ] MacOS / Desktop

**Version Number:** 1.3.40.5

**Reproducible in staging?:** Yes

**Reproducible in production?:** Yes

**If this was caught during regression testing, add the test name, ID and link from TestRail:**

**Email or phone of affected tester (no customers):**

**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/78819774/ab8c77a5-6699-4b4a-8c1b-690b253731c7

**Expensify/Expensify Issue URL:**

**Issue reported by:** Applause - Internal Team

**Slack conversation:**
<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01b57bc0495e0f6542</li>
        <li>Upwork Job ID: 1683569394738528256</li>
        2023-07-24<li>Automatic offers: </li>
<ul>
<li> |  | 0</li>
<li>s-alves10 | Contributor | 25757442</li>
</ul></li>
    </ul>
</details>

**Comment by s-alves10** [comment] 2023-07-14 15:04
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
Extra line breaks added when pasting text from code editor on windows

### What is the root cause of that problem?

End of line(EOL) is represented differently on various platforms. On Unix-like systems including Mac OS, `\n` is the code for EOL, and `\r\n` is the code for EOL on Windows.
We are using `\n` in the ExpensiMark now. When `addComment` API is called, we replace markdown with html elements and below rule is applied.
https://github.com/Expensify/App/blob/a2dc004c6342c3b2e1e9a61bdc40b99da4fb647c/src/libs/ReportUtils.js#L1308

So EOL(`\r\n` on Windows) is converted to `\r<br />` and `\n<br />` is returned from the backend.

This is the root cause

### What changes do you think we should make in order to solve the problem?

We need to handle `\r\n` or `\n` as EOL in parsing markdown

The current newline rule is as follows
```
            {
                name: 'newline',
                regex: /\n/g,
                replacement: '<br />',
            },
```

Replace this with
```
            {
                name: 'newline',
                regex: /\r?\n/g,
                replacement: '<br />',
            },
```

This works as expected.

<details>
    <summary>Result</summary>


</details>

### What alternative solutions did you explore? (Optional)

**Comment by anmurali** [comment] 2023-07-17 20:23
Cannot reproduce

**Comment by s-alves10** [comment] 2023-07-18 10:13
@anmurali 
I'm not sure why this issue was closed. This is still reproducible on staging

https://github.com/Expensify/App/assets/126839717/13df5bcb-1689-418d-a6fa-9010625f8eb0

**Comment by slafortune** [comment] 2023-07-24 20:06
Thanks for the reproduction!

**Comment by rushatgabhane** [comment] 2023-07-25 17:36
`\r?\n`
- matches `\r` 0 or 1 times 
- matches `\n`

**Comment by rushatgabhane** [comment] 2023-07-26 07:46
@s-alves10 you'll have to create a PR on Expensify common and mention Jules and me on it.

**Comment by s-alves10** [comment] 2023-07-26 07:49
@rushatgabhane 

Okay. Thank you. PR will be done in an hour or 2

**Comment by rushatgabhane** [comment] 2023-07-26 07:51
A friendly reminder to add a few tests too, thanks :)

**Comment by s-alves10** [comment] 2023-07-26 08:11
@rushatgabhane 

[PR](https://github.com/Expensify/expensify-common/pull/560) is ready for review.

**Comment by Julesssss** [comment] 2023-07-26 09:27
Okay, PR was merged. Can we now raise a PR in 'App' to [bump the commit hash](https://github.com/Expensify/expensify-common/pull/560) please?

**Comment by s-alves10** [comment] 2023-07-26 09:28
I'll do it in an hour or 2

**Comment by s-alves10** [comment] 2023-07-26 11:44
@rushatgabhane 

[PR](https://github.com/Expensify/App/pull/23628) is ready for review

**Comment by rushatgabhane** [comment] 2023-07-27 08:51
yayy, we merged everything in 24 hrs

**Comment by rushatgabhane** [comment] 2023-08-03 04:48
1. The PR that introduced the bug has been identified. Link to the PR: N.A. This bug was always present and won't happen again because of the unit tests in expensify-common.

2. The offending PR has been commented on, pointing out the bug it caused and why, so the author and reviewers can learn from the mistake. Link to comment: N.A.

3. A discussion in #expensify-bugs has been started about whether any other steps should be taken (e.g. updating the PR review checklist) in order to catch this type of bug sooner. Link to discussion: N.A.

4. Determine if we should create a regression test for this bug. No

5. If we decide to create a [regression test](https://github.com/Expensify/App/blob/main/contributingGuides/REGRESSION_TEST_BEST_PRACTICES.md) for the bug, please propose the regression test steps to ensure the same bug will not reach production again - N.A.

**Comment by rushatgabhane** [comment] 2023-08-03 04:50
Created a manual request - https://staging.new.expensify.com/r/7966456959101740

**Comment by Julesssss** [comment] 2023-08-07 10:51
Can we complete the checklists? Is that the only blocker here?

**Comment by JmillsExpensify** [comment] 2023-08-08 03:34
@slafortune Mind summarizing the appropriate payouts for everyone?

**Comment by JmillsExpensify** [comment] 2023-08-10 03:23
@slafortune Friendly bump on the payment summary.

**Comment by rushatgabhane** [comment] 2023-08-10 03:30
I think this qualifies for a bonus - https://github.com/Expensify/App/issues/22890#issuecomment-1653181727

**Closed** 2023-08-14 13:45 UTC
Labels: External, Daily, Overdue, Awaiting Payment, Bug

**Comment by JmillsExpensify** [comment] 2023-08-16 03:35
Reviewed the details for @rushatgabhane. Approved for payment in NewDot based on the above BZ summary.
