### ISSUE TITLE
Contact methods - 'expensify.cash-25ffc67..." is created after logging back into the account

### ISSUE THREAD

**Issue by izarutskaya** [Expensify/App#45266] opened 2024-07-11 12:35 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** v9.0.6-0
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**Email or phone of affected tester (no customers):** dave0123seife@gmail.com
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Issue reported by:** Applause-Internal team

## Action Performed:
1. Logout from any account
2. Log back in
3. Go to account settings > Profile > Contact methods

## Expected Result:
Ony added contact methods are displayed in contact methods

## Actual Result:
Ony added contact methods are displayed in contact methods

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [x] Android: mWeb Chrome
- [ ] iOS: Native
- [x] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

https://github.com/Expensify/App/assets/115492554/0827306f-b014-4d0d-a17d-547535b921d6

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by Julesssss** [comment] 2024-07-15 09:43
Hey @RachCHopkins. tagging you here as you [pointed out](https://github.com/Expensify/App/issues/45336#issuecomment-2227696280) that this is occurring for real customers.

**Comment by puneetlath** [comment] 2024-07-16 17:36
Going to raise in Slack to find out what the expected behavior is here.

**Comment by puneetlath** [comment] 2024-07-17 00:53
@nkuoch I see you added getting the loginlist in Auth a couple weeks ago here. 

It seems like that is most likely the cause of this issue as it seems like `Login::getList` is including these expensify.cash- logins. So we probably need to either filter them out after getting the results or write a different query that doesn't get these. What do you think?

**Comment by puneetlath** [comment] 2024-07-24 19:42
Looks like the fix for this was merged and deployed. And it looks like it's working correctly. Thanks @nkuoch! 

<img width="370" alt="image" src="https://github.com/user-attachments/assets/e6385b36-29ff-42de-b296-de0dc39bbe64">

**Closed by puneetlath** 2024-07-24 19:42 UTC
Labels: Reviewing, Daily, Internal, Bug
