### ISSUE TITLE
[HOLD #299672] [$1000] Report Recipient Local Time does not appear in sender

### ISSUE THREAD

**Issue by kavimuru** [Expensify/App#23836] opened 2023-07-28 22:34 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Open 2 accounts on 2 browsers and 2 account not has chat before
2.  A open chat with B and send any message
3. From B, the appearance of Recipient Local Time is observed but From A  does not appear
## Expected Result: 
Recipient Local Time Must appear in both user A and B
## Actual Result:
 Recipient Local Time appears only in recipients.

## Workaround:
Can the user still use Expensify without this being fixed? Have you informed them of the workaround?

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [x] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 1.3.47-3
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/43996225/3c989581-6ddf-4e93-b237-3cc309d7375b

https://github.com/Expensify/App/assets/43996225/b43ad22d-d952-47e4-b07a-d8638bb2dc8f

**Expensify/Expensify Issue URL:**
**Issue reported by:** @namhihi237 
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1690480211518189

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~0109b85d32df0f6e6f</li>
        <li>Upwork Job ID: 1686039411845201920</li>
        <li>Last Price Increase: 2023-07-31</li>
    </ul>
</details>

**Comment by s-alves10** [comment] 2023-07-29 03:15
The backend doesn't send full user info

**Comment by jeet-dhandha** [comment] 2023-07-31 16:34
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
- User is unable to see the Recipient Local Time.

### What is the root cause of that problem?
- Recipient Local Time is not being displayed as below condition is getting `false`:
https://github.com/Expensify/App/blob/b50948a930edf94eb2666790875c9b0332d76359/src/libs/ReportUtils.js#L750
- which is an expected behavior as we don't want to show the local time if the Recipient has not sent any message to the User.

### What changes do you think we should make in order to solve the problem?
- Here we need to decide on whether we want to show the local time or not if the Recipient has not sent any message to the User. Based on that above issue should be resolved.

### What alternative solutions did you explore? (Optional)
- N/A

**Comment by ArekChr** [comment] 2023-08-01 11:06
@CortneyOfstad I think this might be a backend issue

**Comment by CortneyOfstad** [comment] 2023-08-01 20:27
Okay, going to get engineering eyes on this, just in case. I'm heading OoO until 8/14 so reapply the BZ label as well to keep eyes on this while I'm out 👍

**Comment by PauloGasparSv** [comment] 2023-08-02 14:28
> NOTE: even after user B sent back the message there is no recipient time

I think this is where the fix should be (If the backend returns that info after the user is "known", didn't check) and not at the moment we start the report (not the `OpenReport` call, there are other user info we don't send there while the user is "unknown").

**Comment by PauloGasparSv** [comment] 2023-08-02 23:01
Hey I'm changing this to internal and will work on a solution+implement it myself this week.

**Comment by PauloGasparSv** [comment] 2023-08-04 13:44
Could not replicate this locally yet, after users send a message to each other and become known the timezone shows up for me.

Will check staging now

**Comment by PauloGasparSv** [comment] 2023-08-07 13:04
Not overdue, I worked on this Friday but couldn't think of a fix, will resume work on this ASAP

**Comment by pradeepmdk** [comment] 2023-08-08 10:54
> Could not replicate this locally, after users send a message to each other and become "known" the timezone shows up for me.
> 
> Will check staging now
> 
> Edit: Nevermind, replicated locally : ) I think I made an accidental call to `OpenReport` the first time I tested and the personal details data was returned there. I think this will be API related, checking the add comment logic when a user is made `known` here.

maybe  this will help you https://github.com/Expensify/App/issues/24228#issuecomment-1668571027

openreport API when` ownerEmail: "__fake__" ` in response data is coming correctly

**Comment by PauloGasparSv** [comment] 2023-08-08 23:19
Had no time to check the updates here but thanks in advance! Will try to pick this back up tomorrow, focused on WAQ and W/N issues Today

**Comment by PauloGasparSv** [comment] 2023-08-11 00:59
> Had no time to check the updates here but thanks in advance! Will try to pick this back up tomorrow, focused on WAQ and W/N issues Today

Hey same here so no updates! I made progress on the issues I was working on so I'll be able to return to this ASAP, sorry for the delay!

**Comment by PauloGasparSv** [comment] 2023-08-11 20:33
Thks for the help, I investigated this a bit further today.
I still think we'll need to fix this on the API for this to work!

Btw, Re-opening the report (triggering a call to `OpenReport`) after users are known make the recipient time appear.

I'll have to start a discussion on slack about this to get some help and also discuss wether or not this is worth fixing/changing!

**Comment by PauloGasparSv** [comment] 2023-08-11 22:54
Discussed [this with the team](https://expensify.slack.com/archives/C03TQ48KC/p1691792594150609) and since we may [implement a new NVP for checking known users](https://github.com/Expensify/Expensify/issues/299672#issuecomment-1671363566) I'm [putting this on HOLD](https://expensify.slack.com/archives/C03TQ48KC/p1691794364188489?thread_ts=1691792594.150609&cid=C03TQ48KC) for https://github.com/Expensify/Expensify/issues/299672!

**Comment by PauloGasparSv** [comment] 2023-08-14 13:04
Changing this to weekly, the issue we are holding had some updates but is still in progress.

**Comment by CortneyOfstad** [comment] 2023-08-14 13:10
Can take this back now that I'm back in office — thanks for holding down the fort @jliexpensify!

**Comment by PauloGasparSv** [comment] 2023-08-15 16:44
I'm starting to get confused with one thing, more than 1 proposal sent here mentioned IOU's and Tasks's specifically but I'm pretty sure this is happening for normal 1:1 chats as long as the user's are unknown to each other no?

That's why I think this fix should be done in the API and should be applied to all Chat Types.

Please LMK if I'm not understanding something here : )

**Comment by PauloGasparSv** [comment] 2023-08-15 17:03
Thks so much for explaining @huzaifa-99 that makes total sense

> I think we should reopen https://github.com/Expensify/App/issues/24228

They may be separate issues but I also think that fixing `OpenReport` might fix both problems. If that's not the case then I agree we should reopen that!

I think it's ok to keep that issue close for now and re-open it once this one is off HOLD in case the problem persists if that's ok : )

**Comment by CortneyOfstad** [comment] 2023-08-23 15:06
Reassigning engineering in replacement of Paulo 👍

**Comment by mountiny** [comment] 2023-08-23 16:29
> Btw, Re-opening the report (triggering a call to OpenReport) after users are known make the recipient time

I think this is actually the case, its expected that you dont see the timezone of unknown user, then when they message back, iI think its fine that we only show the time when you open the report again.

@CortneyOfstad @ArekChr I would close this issue as actually not a bug we need to fix. The time is correctly updated after another `OpenReport`. Let me know if you disagree or I misunderstood this

**Closed by mountiny** 2023-08-23 16:28 UTC
Labels: Engineering, Weekly, Internal, Bug
