### ISSUE TITLE
CRITICAL: [Track expense] Self DM `OpenReport` isn’t returning `transaction`

### ISSUE THREAD

**Issue by quinthar** [Expensify/App#42402] opened 2024-05-20 21:55 UTC
Problem:
====
When I create an unreported transaction in OldDot, it does not get returned in `OpenReport` of my self DM.  This causes the self DM to show a flashing skeleton instead of the expense. Steps:

1. Create an expense in OldDot, and it was auto-reported
2. Unreport it in OldDot

Extensive details in Slack here: https://expensify.slack.com/archives/C066HJM2CAZ/p1716188450154939?thread_ts=1716187933.546269&cid=C066HJM2CAZ

Solution:
====
Begin returning the `transaction` object.
<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01613eb2b89de2e9f0</li>
        <li>Upwork Job ID: 1792675637114478592</li>
        <li>Last Price Increase: 2024-05-20</li>
    </ul>
</details>

**Comment by kadiealexander** [comment] 2024-05-24 04:44
Still waiting on an engineer to pick this up.

**Comment by kadiealexander** [comment] 2024-05-28 02:14
We've offered @shubham1206agra a bounty for providing a thorough diagnosis and analysis of this issue [here](https://expensify.slack.com/archives/C066HJM2CAZ/p1716187933546269).

**Comment by thienlnam** [comment] 2024-05-28 22:10
This looks like a dupe of https://github.com/Expensify/App/issues/42587, so closing it so we can consolidate there

**Closed** 2024-05-31 03:33 UTC
Labels: Engineering, Daily, Internal, Overdue, Bug, Hot Pick
