### ISSUE TITLE
[Hold for #15212] Web -  New green line appears on receiver side and doesn't disappear after deleting a message if it is flagged

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#22238] opened 2023-07-05 01:23 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Send a message from account A to account B
2. From account B flag the last message as bullying
3. Go to account A and hover over the flagged message and click on unread
4. Hover over the message again and click on delete
5. Observe the green line on both account A and account B

## Expected Result:
Green line should disappear as soon as account A deletes the message and green line should not appear on the side of account B

## Actual Result:
 Green line doesn't disappear on account A after deleting the message and green line appears on account B even if it is account A which marked the message as unread.

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [x] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 1.3.36-2
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/93399543/27a048d1-045f-45cb-991a-300e12500c55

https://github.com/Expensify/App/assets/93399543/8cd98e92-98cc-4854-88f3-866bf20835f7

**Expensify/Expensify Issue URL:**
**Issue reported by:** @Nathan-Mulugeta
**Slack conversation:**  https://expensify.slack.com/archives/C049HHMV9SM/p1688458571326759

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by jeet-dhandha** [comment] 2023-07-05 05:05
Logically this is correct as user marked all the messages unread upto the marked message. So even if i delete the message which is just below the indicator then also rest messages should be seen as unread.

**Comment by Nathan-Mulugeta** [comment] 2023-07-05 05:16
There are two issues at hand, 1 is the new marker is present on the reciever side as well even if the sender is the one marking as unread, this doesn't happen anywhere on the app and by itself doesn't make sense. 2 is that  [this pr](https://github.com/Expensify/App/pull/21557) fixed to remove new indicator as soon as user deletes the message marked as unread but if user goes through with the flow reported then the new indicator fails to get removed even after comment gets deleted. What do you think of these notes?

**Comment by DanutGavrus** [comment] 2023-07-05 09:00
@Nathan-Mulugeta I've investigated the PR you mentioned. Here are my findings:
1. This reported bug happens if we remove all the changes introduced by the PR;
2. This reported bug does **not** happen if we introduce the changes proposed [here](https://github.com/Expensify/App/issues/21875#issuecomment-1613200013).

We were [thinking](https://github.com/Expensify/App/pull/21557#issuecomment-1614981455) and [decided](https://github.com/Expensify/App/issues/21875#issuecomment-1614996939) that the bug is out of scope of that PR.

Right now, *New Markers Issues* are on hold as I've found out from [this comment](https://github.com/Expensify/App/issues/21875#issuecomment-1618774447). Lately I've seen quite some issues arising from the **same root cause**, which is that the *New Markers do not get removed when report becomes read*. Maybe we want to make an exception to fix them all with [1 Proposal](https://github.com/Expensify/App/issues/21875#issuecomment-1613200013), or we'll keep them all on hold until the refactor is done.

**Comment by greg-schroeder** [comment] 2023-07-06 08:23
Held on https://github.com/Expensify/App/issues/15212

**Comment by greg-schroeder** [comment] 2023-07-11 03:07
Same as above

**Comment by greg-schroeder** [comment] 2023-07-19 22:58
""

**Comment by greg-schroeder** [comment] 2023-07-25 18:22
""

**Comment by greg-schroeder** [comment] 2023-07-31 14:13
Work on refactor continues

**Comment by greg-schroeder** [comment] 2023-08-09 23:06
""

**Comment by greg-schroeder** [comment] 2023-08-21 17:44
Remains on hold, this isn't overdue

**Comment by greg-schroeder** [comment] 2023-08-29 11:00
""

**Comment by greg-schroeder** [comment] 2023-09-11 13:52
No update

**Closed** 2023-09-22 01:52 UTC
Labels: Weekly, Overdue, Bug
