### ISSUE TITLE
Dev: Android - Unhandled promise rejection Error: File does not exist on Android

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#23199] opened 2023-07-19 21:11 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Open the Android app and Logout.
2. Login with a NEW account.
3. Once the Welcome Fab menu shows up, logout.
4. Repeat this 2-3 times, each time trying with a NEW account.

## Expected Result:
Logout should be done cleanly without any console warning.

## Actual Result:
Sometimes, on Android, a unhandled promise rejection occurs when signing out.

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [ ] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** Dev 1.3.42-21
**Reproducible in staging?:** n/a
**Reproducible in production?:** n/a
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation

![Screenshot 2023-07-19 at 3 52 47 AM](https://github.com/Expensify/App/assets/93399543/d672dba9-f4d1-4a01-bb30-c68f6391a556)

**Expensify/Expensify Issue URL:**
**Issue reported by:** Sibtain Ali
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1689721803279029

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by kbecciv** [comment] 2023-07-19 21:11
## Proposal
### Please re-state the problem that we are trying to solve in this issue.
`File does not exist` error occurs sometimes on Android when signing out with a new account.
### What is the root cause of that problem?
The root cause is that we are not checking if the caches directory exists [here](https://github.com/allroundexperts/Expensify/blob/d0e4dd0c1c39b84d0785ac4e7bcfede6d6833229/src/libs/actions/Session/clearCache/index.native.js#L5).
### What changes do you think we should make in order to solve the problem?

We should check if the caches directory exists before unlinking it [here](https://github.com/allroundexperts/Expensify/blob/d0e4dd0c1c39b84d0785ac4e7bcfede6d6833229/src/libs/actions/Session/clearCache/index.native.js#L5).
### What alternative solutions did you explore? (Optional)
We can also just wrap the `unlink` function inside a `try/catch` block [here](https://github.com/allroundexperts/Expensify/blob/d0e4dd0c1c39b84d0785ac4e7bcfede6d6833229/src/libs/actions/Session/clearCache/index.native.js#L5) and ignore the error.

**Comment by isabelastisser** [comment] 2023-07-21 16:54
https://stackoverflowteams.com/c/expensify/questions/14817

**Comment by isabelastisser** [comment] 2023-07-21 17:01
It's greyed out and won't let me test in BrowserStack:

<img width="705" alt="image" src="https://github.com/Expensify/App/assets/31258516/6dc95598-0422-4eaf-be99-f3be75af6e72">

**Comment by isabelastisser** [comment] 2023-07-21 17:12
https://stackoverflowteams.com/c/expensify/questions/15303

assigning an engineer to help with the reproduction.

**Comment by isabelastisser** [comment] 2023-07-24 17:39
Not overdue, I can't reproduce it. Waiting for engineering!

**Comment by yuwenmemon** [comment] 2023-07-27 12:32
> It's greyed out and won't let me test in BrowserStack:

@isabelastisser what do you mean exactly? Nothing will click?

**Comment by yuwenmemon** [comment] 2023-07-27 12:37
@isabelastisser are you sure you're clicking on "Uploaded Apps" to the left of the menu you posted a screenshot of
https://github.com/Expensify/App/assets/4741899/7d280956-5d45-4302-96b3-8bf691648f02

**Comment by isabelastisser** [comment] 2023-07-31 13:39
@yuwenmemon Yes, I tried to select one of the devices, but it didn't go through. I will try again later.

**Comment by isabelastisser** [comment] 2023-08-01 19:19
I'm unable to reproduce this behavior, closing!

@kbecciv are you still able to reproduce this? If yes, please let me know and I will reopen. Thanks!

**Closed by isabelastisser** 2023-08-01 19:19 UTC
Labels: Engineering, Daily, Needs Reproduction, Bug
