### ISSUE TITLE
 Profile - Address - Zip code verification does not work correctly

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#41531] opened 2024-05-02 19:38 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.70-0
**Reproducible in staging?:** Y
**Reproducible in production?:** N
**If this was caught during regression testing, add the test name, ID and link from TestRail:** https://expensify.testrail.io/index.php?/tests/view/4537799
**Email or phone of affected tester (no customers):** fischer9966+050224aa@gmail.com
**Issue reported by:** Applause - Internal Team

## Action Performed:
1. Open app or go to staging.new.expensify.com
2. Login with any account that does not have an address in Profile
3. Go to Settings > Profile > Address
4. Enter any US address with a numeric-only zip code and save it
5. Open address again and input any UK address with a zip code containing letters and numbers and save it
6. Do the same on the new account but first add the address in UK

## Expected Result:
User can replace the saved address with numeric zip code with address with letters-numeric zip code and vice versa

## Actual Result:
Zip code verification does not work correctly
User can NOT replace the saved address with numeric zip code with address with letters-numeric zip code and vice versa

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [ ] Android: mWeb Chrome
- [x] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details> 

https://github.com/Expensify/App/assets/78819774/3a066909-bad5-49e1-ba0a-6be40e4c33b5

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by lanitochka17** [comment] 2024-05-02 19:39
@srikarparsi  FYI I haven't added the External label as I wasn't 100% sure about this issue. Please take a look and add the label if you agree it's a bug and can be handled by external contributors

**Comment by srikarparsi** [comment] 2024-05-02 21:34
Not able to reproduce on the latest dev. Still looking.

**Comment by srikarparsi** [comment] 2024-05-02 21:40
https://github.com/Expensify/App/assets/48188732/d01d69a9-9225-4db3-b6ae-c4ff4d1e871d

Not able to reproduce with a new account. Building auth right now and will test with that. If it doesn't then it's a backend problem, if it doesn't, then a recent change might've fixed it and I can try finding that?

**Comment by francoisl** [comment] 2024-05-03 06:00
I'm able to repro on `main` – I had to rerun `npm i`, maybe you were missing that? Not 100% sure yet, but I think the issue comes from https://github.com/Expensify/App/pull/41056 that bumped the onyx-react-native version (which would also explain why you couldn't repro without running `npm i`)

**Comment by francoisl** [comment] 2024-05-03 06:08
Did some more digging, reverting `react-native-onyx` to `2.0.32` fixes the issue, and it starts appearing in `2.0.33`, which means it would have been introduced via (or as a side effect of) https://github.com/Expensify/react-native-onyx/pull/519.

<table>
<tr>
 <td>2.0.32
 <td>2.0.33
<tr>
 <td><video src="https://github.com/Expensify/App/assets/2229301/2f23f9e2-4b49-4790-95c1-ce8bf4551397" />
 <td><video src="https://github.com/Expensify/App/assets/2229301/9745dfd5-f450-4144-8f61-ee1c99eec305" />
</table>

cc @chrispader @tgolen if you have an idea

What's happening is that the country key doesn't get updated on the Address page, so we end up using the wrong [validation regex](https://github.com/Expensify/App/blob/ee8f9c661f269f405a5ae8ba47ea07f42a306c6c/src/CONST.ts#L2386) for the zip code when you try to save the changes.

**Comment by chrispader** [comment] 2024-05-13 14:20
Fixed in https://github.com/Expensify/App/pull/42057

**Closed** 2024-05-23 16:58 UTC
Labels: Reviewing, Engineering, Weekly

**Comment by ikevin127** [comment] 2024-06-15 19:38
⚠️ Automation failed here -> this should be on **[HOLD for Payment 2024-06-21]** according to yesterday’s production deploy of the 2nd PR (after revert) from https://github.com/Expensify/App/pull/42772#issuecomment-2168863017.

Additional issue attached to the PR **Fixed Issues** section:
- https://github.com/Expensify/App/issues/41895

@srikarparsi Could you please remove the previous HOLD from the issue's title and add the correct one and also add the `Bug` label to get a BZ team member assigned in order to handle payment here when it's due ?

##

cc @mountiny 
1. This onyx bump was a big PR which took lots of testing and given this, would you be cool with a $500 bounty for the C+ reviewers given the work involved in both reverted and currently merged PR ?
2. What are we going to do about current / possible regressions (if any) in the context of the bounty ? Asking if any existing regression will -50% the bounty or not.

**Comment by ikevin127** [comment] 2024-06-19 18:33
Based on this **#expensify-open-source** Slack [discussion](https://expensify.slack.com/archives/C05R2V5GM1S/p1718821637382649?thread_ts=1717193187.147939&cid=C05R2V5GM1S) **Vit** suggested to handle payment in issue:
- https://github.com/Expensify/App/issues/41895

Therefore this can be closed as completed.

cc @OfstadC @srikarparsi
