### ISSUE TITLE
[HOLD for payment 2023-09-12] [$500] [Distance] - App crashes while using distance feature

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#26558] opened 2023-09-02 15:11 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___
**Issue found when executing PR** https://github.com/Expensify/App/pull/25980
## Action Performed:
1. Launch app
2. Turn off mobile date
3. Tap fab
4. Tap Request money
5. Tap Distance
6. Enter Start address and save
7. Enter Finish address and save ([make sure you hit save](https://expensify.slack.com/archives/C01GTK53T8Q/p1693720205350129?thread_ts=1693667520.672399&cid=C01GTK53T8Q))
8. Turn on mobile data

## Expected Result:
The app must generate map for address entered

## Actual Result:
In online, the app crashes while using distance feature

## Workaround:

Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [ ] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 1.3.62-1

**Reproducible in staging?:** Yes

**Reproducible in production?:** No

**If this was caught during regression testing, add the test name, ID and link from TestRail:**

**Email or phone of affected tester (no customers):**

**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/78819774/0323640b-9463-442a-921a-6fd85f8ff28a

https://github.com/Expensify/App/assets/98560306/2d40580c-94bf-40e5-81bf-2a32102ee21a

**Expensify/Expensify Issue URL:**

**Issue reported by:** Applause - Internal Team

**Slack conversation:**

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~014a7eeceb0e8a9b8a</li>
        <li>Upwork Job ID: 1698183373609881600</li>
        <li>Last Price Increase: 2023-09-03</li>
<li>Automatic offers: </li>
<ul>
<li>fedirjh | Reviewer | 26478908</li>
<li>pradeepmdk | Contributor | 26478909</li>
</ul></li>
    </ul>
</details>

**Comment by b4s36t4** [comment] 2023-09-03 06:11
This issue only happens only when we click on `Save` button.  Because we've wrapped the `WaypointEditor` component with a `From` when we click on save only string get's saved.  No lat & lognitude is being saved.

If we're offline we save lat & lag as null which is causing the app to crash. We seems to handle the null values but not the app though.

So What I want to confirm is even if we go online because we've saved lat & lan as `null` or `0` route markers won't be pointed which results in no route paint on the map.

what shall we do here? when user become online fetch the lat & lng for the waypoints which have lat & lng null values??

if not doesn't that cause an issue itself??.

This save button also raises an issue flow follows this way

Open Requst Money
Select a waypoint from the autocomplete input
Select the same waypoint but now use the save button
Select finish address
Observe only one marker is showing in the app (Finish marker since we have lat & lng for the waypoint).

Whenever we click on `Save` there's no lat & lng.

Shall we just remove the save button?? That reduces the 90% of effort.

<img width="514" alt="Screenshot 2023-09-03 at 11 35 27 AM" src="https://github.com/Expensify/App/assets/59088937/a68269c5-85a8-4db5-a0e0-2ce9ad6cdbea">

**Comment by b4s36t4** [comment] 2023-09-03 06:13
https://developers.google.com/maps/documentation/places/web-service/search-text#:~:text=A%20Text%20Search%20returns%20information,bias%20that%20has%20been%20set. We can use this API if we're planning to refetch lat & lng once back online.

**Comment by shubham1206agra** [comment] 2023-09-03 06:25
> https://developers.google.com/maps/documentation/places/web-service/search-text#:~:text=A%20Text%20Search%20returns%20information,bias%20that%20has%20been%20set. We can use this API if we're planning to refetch lat & lng once back online.

This requires backend changes

**Comment by b4s36t4** [comment] 2023-09-03 06:26
I don't think so. Backend handles places API using in a proxy way.

**Comment by hayata-suenaga** [comment] 2023-09-03 06:26
okay I feel like the easy fix for now is to disable the save button when offline...

**Comment by b4s36t4** [comment] 2023-09-03 06:29
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
Distance - App crashes while using distance feature
### What is the root cause of that problem?
lat & lng being null causing the `MapBox` component in mobile to crash because user clicks on `Save` button which only saves waypoint not lat & lng
### What changes do you think we should make in order to solve the problem?

https://github.com/Expensify/App/blob/7217a18a78ec2b01a45267f476fd95ed0cde0fb0/src/pages/iou/WaypointEditor.js#L197

Setting false here will disable the save button in offline.
### What alternative solutions did you explore? (Optional)
NA

**Comment by b4s36t4** [comment] 2023-09-03 06:32
> :warning: Whole save button is causing the issue. But with a user perspective when he's online and typing he usually > select only from auto complete. At this point solving online issue not so important I feel.

**Comment by shubham1206agra** [comment] 2023-09-03 06:32
> okay I feel like the easy fix for now is to disable the save button when offline...

I have another fix
Requires hiding the 2 text input and updating the value of lat lng when selecting
Not sure rn

**Comment by shubham1206agra** [comment] 2023-09-03 06:34
But I think disable should work rn

**Comment by shubham1206agra** [comment] 2023-09-03 06:36
But I have another case in mind
What about some custom addresses when offline and we just want to save in draft??

**Comment by b4s36t4** [comment] 2023-09-03 06:42
@shubham1206agra we have to launch few things tmrw. Maybe you can come up with a plan which can by solved by EOD. please mind today is sunday for us, tmrw is sunday for them.

**Comment by shubham1206agra** [comment] 2023-09-03 06:57
I am proposing removing these lines.

https://github.com/Expensify/App/blob/7217a18a78ec2b01a45267f476fd95ed0cde0fb0/src/pages/iou/WaypointEditor.js#L129-L137

And add this logic in validate

```js
if (isOffline && waypointValue !== '') {
            errors[`waypoint${waypointIndex}`] = 'bankAccount.error.addressWhenOffline';
        }
```

**Comment by shubham1206agra** [comment] 2023-09-03 06:58
<img width="379" alt="Screenshot 2023-09-03 at 12 28 04 PM" src="https://github.com/Expensify/App/assets/58412969/903e5b51-2864-4fbc-9af9-eb1641a10f88">

It will look something like this

**Comment by shubham1206agra** [comment] 2023-09-03 07:22
<img width="379" alt="Screenshot 2023-09-03 at 12 51 51 PM" src="https://github.com/Expensify/App/assets/58412969/67fac072-d88f-46cb-951e-fa1db4bf881d">

Do you like this method more?

**Comment by shubham1206agra** [comment] 2023-09-03 07:26
I will also disable Next button

**Comment by pradeepmdk** [comment] 2023-09-03 10:58
i am not sure i am not able to reproduce this one. and also save lat and lng null don't have any problem here. because if both are null means api will handle it on `getRoute` that is also working correctly here waypoint 1 have null only but still backend return the waypointer.
<img width="728" alt="Screenshot 2023-09-03 at 4 25 14 PM" src="https://github.com/Expensify/App/assets/16595846/33227903-34f2-4931-978e-7d7864d9742b">
<img width="719" alt="Screenshot 2023-09-03 at 4 27 45 PM" src="https://github.com/Expensify/App/assets/16595846/a28e197a-ea53-4435-bf4b-320f22a32167">

**Comment by pradeepmdk** [comment] 2023-09-03 11:33
https://github.com/Expensify/App/blob/9661a4b446884177760940ea6c30a58de32eb716/src/components/DistanceRequest.js#L99 looks like problem is here 

lodashHas will key is there or not only not checking it has the real value.

we should update like this 
```javascript
if (!waypoint || !waypoint.lat || !waypoint.lng) {
                        return;
                    }
``` 

so that for null lat lng  ignore the marker component

**Comment by situchan** [comment] 2023-09-03 11:39
`!waypoint.lat || !waypoint.lng` is not perfect condition. There's super edge case where (0, 0) coordinate is selected.

**Comment by situchan** [comment] 2023-09-03 11:41
> Replace `lodashHas` with `lodashGet` instead.

No need `lodashGet`. As null safety is already checked in first condition: `!waypoint ||`

**Comment by pradeepmdk** [comment] 2023-09-03 11:42
@situchan we can use _.isNull from lodash

**Comment by hayata-suenaga** [comment] 2023-09-03 16:56
@pradeepmdk 

> because if both are null means api will handle it on getRoute that is also working correctly here waypoint 1 have null only but still backend return the waypointer.

I love this observation and that's correct. We actually have this PHP code in the backend

```php
// If the waypoints are missing lat/lng, fill them in
if ($shouldFillMissingData && self::isMissingLatLong($waypoints)) {
  $waypoints = Mapbox_API::geocodeAddresses($waypoints);
}
```

So when offline, we just ignore the waypoints that don't have lat and lng?

**Comment by pradeepmdk** [comment] 2023-09-03 16:59
@hayata-suenaga Yes we need ignore this waypoint markers https://github.com/Expensify/App/blob/9661a4b446884177760940ea6c30a58de32eb716/src/components/DistanceRequest.js#L99

**Comment by hayata-suenaga** [comment] 2023-09-03 17:09
@pradeepmdk let's do this 👍

**Comment by hayata-suenaga** [comment] 2023-09-03 20:08
@pradeepmdk please ping me on slack when the PR is ready 🙇

**Comment by hayata-suenaga** [comment] 2023-09-04 00:33
[I'm removing the deploy blocker label per this instruction](https://expensify.slack.com/archives/C01GTK53T8Q/p1693597411906209)

**Comment by mountiny** [comment] 2023-09-04 08:04
@fedirjh @pradeepmdk This is still happening in staging, right? https://github.com/Expensify/App/pull/26622 do we have to CP this PR to fix it?

**Comment by pradeepmdk** [comment] 2023-09-04 08:26
@mountiny I don't have access to this feature on staging. but I found it local and fixed that. This ticket also mentions coming from this https://github.com/Expensify/App/pull/25980

**Comment by mountiny** [comment] 2023-09-04 08:32
I am hesitatnt on this one but given this is still behind beta and will be probably until this hits production, I think we can just proceed with normal deploy process

**Comment by pradeepmdk** [comment] 2023-09-04 08:35
@mountiny i think we can go with normal process  @hayata-suenaga also removed this deploy blocker due to this [I'm removing the deploy blocker label per this instruction](https://expensify.slack.com/archives/C01GTK53T8Q/p1693597411906209)

**Comment by JmillsExpensify** [comment] 2023-09-13 08:15
I don't see the normal BZ checklist on this issue. @fedirjh Do you think we require any regression tests in light of the crash?

**Comment by JmillsExpensify** [comment] 2023-09-13 08:17
Payment summary:

 - Issue reporter: N/A
 - Contributor: @pradeepmdk $750 (incl. urgency bonus)
 - Contributor+: @fedirjh $750 (incl. urgency bonus)

Offers are out. Let me know when you've accepted and we'll get this kicked off.

**Comment by hayata-suenaga** [comment] 2023-09-21 08:15
do we have a regression test?

**Comment by pradeepmdk** [comment] 2023-09-22 15:13
@fedirjh here https://github.com/Expensify/App/issues/26589#issuecomment-1710175245 we are fixing here only the map is not loading when offline -> online on the web.

if we need a regression test here can we take care here itself?

**Comment by hayata-suenaga** [comment] 2023-09-25 07:15
The regression test proposal is above

**Comment by JmillsExpensify** [comment] 2023-09-25 07:45
Great thanks. I'll issue payouts now and get a regression test created.

**Comment by JmillsExpensify** [comment] 2023-09-25 07:49
All contributors paid out via Upwork. Regession test has also been created. Closing

**Closed by JmillsExpensify** 2023-09-25 07:49 UTC
Labels: External, Engineering, Daily, Awaiting Payment
