### ISSUE TITLE
[$1000] Connect bank account message page has no back button for phone number login

### ISSUE THREAD

**Issue by kavimuru** [Expensify/App#19708] opened 2023-05-27 00:02 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Open the app
2. login with phone number user
3. Open settings
4. Open Workspaces
5. Open any Workspace
6. Open connect bank account and observe that it has no back button (Similar page with just message is for default contact i.e. settings->profile->contact method->default contact and it has back button)
## Expected Result: 
App should have back button to navigate back to workspace settings options on connect bank account for phone number login as it has for similar message page in settings->profile->contact method->default contact
## Actual Result: 
App does not have back button to navigate back to workspace settings options on connect bank account for phone number login
## Workaround:
Can the user still use Expensify without this being fixed? Have you informed them of the workaround?

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android / native
- [x] Android / Chrome
- [x] iOS / native
- [x] iOS / Safari
- [x] MacOS / Chrome / Safari
- [x] MacOS / Desktop

**Version Number:** 1.3.19-2
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/43996225/13ec77f3-5f0b-4e6c-bef4-c6c27b4579ea

<img width="949" alt="Untitled" src="https://github.com/Expensify/App/assets/43996225/21200e93-d784-4971-92cf-ebd15735e048">

**Expensify/Expensify Issue URL:**
**Issue reported by:** @dhanashree-sawant
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1684939436710909

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~019cd2b61cfafbfc14</li>
        <li>Upwork Job ID: 1664304843005927424</li>
        <li>Last Price Increase: 2023-06-01</li>
    </ul>
</details>

**Comment by PrashantMangukiya** [comment] 2023-05-27 06:22
## Proposal

Posting proposal early as per new [guidelines](https://github.com/Expensify/App/blob/main/contributingGuides/CONTRIBUTING.md#propose-a-solution-for-the-job)

### Please re-state the problem that we are trying to solve in this issue.
Connect bank account error message page has no back button for phone number login.

### What is the root cause of that problem?
If user has phone which is primary account then it will fill up `errorComponent` via line 360 as shown below:
https://github.com/Expensify/App/blob/8b9738724d8511855cda04df09738834b33a71ca/src/pages/ReimbursementAccount/ReimbursementAccountPage.js#L359-L365

So due to `errorComponent` it will return `<ScreenWrapper>` code via line 378 block as shown below:
https://github.com/Expensify/App/blob/8b9738724d8511855cda04df09738834b33a71ca/src/pages/ReimbursementAccount/ReimbursementAccountPage.js#L376-L387

We can see, we are not passing  `shouldShowBackButton` and `onBackButtonPress` props within  `HeaderWithCloseButton` component at line 379, so it will not show back button while phone is primary account. This is the root cause of the problem.

### What changes do you think we should make in order to solve the problem?
Within `ReimbursementAccountPage.js` we have to pass `shouldShowBackButton` and `onBackButtonPress` props within  `HeaderWithCloseButton` component as shown in code below:

```javascript
if (errorComponent) {
    return (
        <ScreenWrapper>
            <HeaderWithCloseButton
                title={this.props.translate('workspace.common.connectBankAccount')}
                shouldShowBackButton                  // *** ADD THIS ***
                onBackButtonPress={Navigation.goBack} // *** ADD THIS ***
                onCloseButtonPress={Navigation.dismissModal}
                subtitle={policyName}
            />
            {errorComponent}
        </ScreenWrapper>
    );
}
``` 
So this will solve the issue and shows back button during error as shown in result video.

### What alternative solutions did you explore? (Optional)
None

<details>
<summary>Result</summary>

https://github.com/Expensify/App/assets/7823358/df2f9bd3-8176-4f6f-8494-6007ee2989ed

</details>

**Comment by muttmuure** [comment] 2023-06-01 16:16
Reproduced

**Comment by ashishsantikari** [comment] 2023-06-01 16:38
I am testing on the web(Chrome & Firefox) and didn't seem to reproduce the issue locally.
![NB-bank-account-back-button](https://github.com/Expensify/App/assets/8361838/b6bc9b73-321a-4667-95c6-ea8c26e630ff)

**Comment by ashishsantikari** [comment] 2023-06-01 16:44
Contributor details
Your Expensify account email: ashish@posteo.net
Upwork Profile Link: https://www.upwork.com/freelancers/~01da91c8e2b9866a20

**Comment by sobitneupane** [comment] 2023-06-05 14:57
Thanks for the proposal @PrashantMangukiya 

Proposal from @PrashantMangukiya looks good to me.

🎀👀🎀 C+ reviewed
cc: @arosiclair

**Comment by PrashantMangukiya** [comment] 2023-06-06 14:57
@arosiclair @sobitneupane Thank you. I will prepare and submit pr within two hours asap.

**Comment by PrashantMangukiya** [comment] 2023-06-06 16:10
@sobitneupane @arosiclair PR is ready for review.

**Comment by arosiclair** [comment] 2023-06-07 17:00
Looks like this was just fixed yesterday with https://github.com/Expensify/App/pull/19263 so I closed out the PR for this. I think we can close this out though not sure if there should still be a payment for the bug reporter @muttmuure

**Comment by muttmuure** [comment] 2023-06-12 23:42
Sorry for the delay, since it was a legit bug I agree that @dhanashree-sawant should get a reporting bonus. I've invited you to the job in Upwork!

**Comment by dhanashree-sawant** [comment] 2023-06-13 07:06
Thanks @muttmuure, I have applied to the invite.

**Comment by muttmuure** [comment] 2023-06-16 00:29
Offer sent

**Comment by dhanashree-sawant** [comment] 2023-06-17 03:29
Thanks I have accepted the offer.

**Comment by muttmuure** [comment] 2023-06-19 10:23
<img width="1512" alt="image" src="https://github.com/Expensify/App/assets/46995600/3827ca31-7b38-4b7f-8973-bc4180d0a8cc">

We have an open ticket with Upwork

**Closed** 2023-06-21 08:28 UTC
Labels: External, Engineering, Daily, Bug
