### ISSUE TITLE
[$500] [MEDIUM] Zoomed large image disappears from preview if triple tap on the bottom of the screen

### ISSUE THREAD

**Issue by kavimuru** [Expensify/App#35383] opened 2024-01-30 11:22 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** v1.4.33-3
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:** https://expensify.testrail.io/index.php?/tests/view/4253754
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** Applause internal team
**Slack conversation:**

## Action Performed:
1. Go to https://staging.new.expensify.com/
2. On a conversation, click on the + button in the compose box
3. Upload this long image to a conversation
4. Tap on the preview
5. Double tap image > Scroll down > Triple tap on the bottom
## Expected Result:
Zoomed large image has become smaller

## Actual Result:
Zoomed large image disappears from preview if triple tap on the bottom of the screen.

## Workaround:
Can the user still use Expensify without this being fixed? Have you informed them of the workaround?

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [ ] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

![Bug6360736_1706612036657!long_image](https://github.com/Expensify/App/assets/43996225/c4c3e291-aac0-4979-9d28-4b50963d41a3)

https://github.com/Expensify/App/assets/43996225/7e346ccc-d0b0-43d7-9b2d-2f2c0fbf0081

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~018c8406d6a29ea8b8</li>
        <li>Upwork Job ID: 1752291085958225920</li>
        <li>Last Price Increase: 2024-01-30</li>
<li>Automatic offers: </li>
<ul>
<li>andreasnw | Contributor | 28145607</li>
</ul></li>
    </ul>
</details>

**Comment by andreasnw** [comment] 2024-01-31 09:26
Contributor details
Your Expensify account email: andreasnw93@gmail.com
Upwork Profile Link: https://www.upwork.com/freelancers/~0111c6bff2681e8236

**Comment by dylanexpensify** [comment] 2024-01-31 09:47
hmm I think this is a dupe, cc @eVoloshchak can you confirm?

**Comment by andreasnw** [comment] 2024-01-31 09:57
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
Triple-clicking causes the image to zoom out, but it fails to reposition the image, leading it to move out of the visible area.

### What is the root cause of that problem?
Upon a double click by the user, the reset() function is triggered, animating the offsetY.value to 0 
https://github.com/Expensify/App/blob/49fbaa035150260033424bf284343a05c3213fb5/src/components/MultiGestureCanvas/index.tsx#L126-L133

while the one remaining click is captured by the pan gesture, and the single tap listener invokes the stopAnimation() method before offsetY.value successfully set to 0.

https://github.com/Expensify/App/blob/49fbaa035150260033424bf284343a05c3213fb5/src/components/MultiGestureCanvas/usePanGesture.ts#L114-L127

https://github.com/Expensify/App/blob/49fbaa035150260033424bf284343a05c3213fb5/src/components/MultiGestureCanvas/useTapGestures.ts#L131-L135 

### What changes do you think we should make in order to solve the problem?

Decrease spring duration to 0 on reset function, transforming offsetY.value before pan gesture, and the single tap listener invokes the stopAnimation() 

https://github.com/Expensify/App/blob/49fbaa035150260033424bf284343a05c3213fb5/src/components/MultiGestureCanvas/index.tsx#L126-L141

```
offsetY.value = withSpring(0, {...SPRING_CONFIG, duration: 0});
```

### What alternative solutions did you explore? (Optional)

**Comment by aswin-s** [comment] 2024-01-31 11:13
## Proposal

### Please re-state the problem that we are trying to solve in this issue.

Zoomed in extra long image disappear when tripple tapped at bottom of screen.

### What is the root cause of that problem?

Zoom, Pan & Pich gestures on the ImageView is handled by the MultiGestureCanvas component. It simultaneously listen to all three gestures and triggers the first one that is detected. 

https://github.com/Expensify/App/blob/49fbaa035150260033424bf284343a05c3213fb5/src/components/MultiGestureCanvas/index.tsx#L246

When user double taps on an image it gets zoomed in or gets zoomed back out based on the current state of the image.

https://github.com/Expensify/App/blob/49fbaa035150260033424bf284343a05c3213fb5/src/components/MultiGestureCanvas/useTapGestures.ts#L122-L128

If image is already zoomed, double tap gesture resets the zoomScale and translate offsets of the image.The give a smooth transition the values are reset to zero using `withSpring` animation. This interpolated the zoomScale and translate offsets gradually to zero.

https://github.com/Expensify/App/blob/49fbaa035150260033424bf284343a05c3213fb5/src/components/MultiGestureCanvas/index.tsx#L126-L141

When user triple taps on the screen, the first two taps trigger the doubleTapGesture and the third tap triggers a panGesture. To prevent race conditions, each gesture handler resets the animations before it gets invoked.

https://github.com/Expensify/App/blob/49fbaa035150260033424bf284343a05c3213fb5/src/components/MultiGestureCanvas/usePanGesture.ts#L127

But the reset method only cancels animations on translateX & translateY shared variables. And animationon zoomScale variable continues to run. 

https://github.com/Expensify/App/blob/49fbaa035150260033424bf284343a05c3213fb5/src/components/MultiGestureCanvas/index.tsx#L118-L121

Result is that zoom gets reset to zero, but translateX & translateY stop mid way. This results in the image getting hidden.


### What changes do you think we should make in order to solve the problem?

Along with translateX & translateY variables, reset the zoomScale shared variable as well. This makes sure that when the panGesture gets activated it will cancel out the doubleTap animation.


```tsx
const stopAnimation = useWorkletCallback(() => {
        cancelAnimation(offsetX);
        cancelAnimation(offsetY);
        // cancel animation on zoomScale as well
        cancelAnimation(zoomScale);
});
```

Result 

| Before | After |
|--|--|
| <video src="https://github.com/Expensify/App/assets/6880914/4faf9816-5083-4f99-8782-10cb62b6d65b" /> | <video src="https://github.com/Expensify/App/assets/6880914/37c688eb-917a-46fc-88b5-7fc5adce3204" /> | 



### What alternative solutions did you explore? (Optional)

None

**Comment by eVoloshchak** [comment] 2024-02-03 22:02
> hmm I think this is a dupe, cc @eVoloshchak can you confirm?

@dylanexpensify, cannot find a dupe of this issue. I remember seeing similar ones (this exact image was causing other issues), but not with triple-tapping

@andreasnw's [proposal](https://github.com/Expensify/App/issues/35383#issuecomment-1918766565) looks good to me. This is kind of an edge case, so we have to make sure we don't break the main functionality when testing the PR

🎀👀🎀 C+ reviewed!

**Comment by rlinoz** [comment] 2024-02-05 12:01
@dylanexpensify can you think of a wave to put this on?

**Comment by dylanexpensify** [comment] 2024-02-05 12:54
I'd say wave5 for now @rlinoz!

**Comment by rlinoz** [comment] 2024-02-06 11:59
Ok!

Let's go with @andreasnw's proposal and and take care to not break the main functionality as @eVoloshchak said.

**Comment by andreasnw** [comment] 2024-02-06 18:04
PR ready for review https://github.com/Expensify/App/pull/35931

**Comment by dylanexpensify** [comment] 2024-02-07 10:31
Nice!

**Comment by dylanexpensify** [comment] 2024-02-13 20:22
review in progress

**Comment by dylanexpensify** [comment] 2024-02-21 10:43
@eVoloshchak update?

**Comment by rlinoz** [comment] 2024-02-23 13:39
PR is merged!

**Comment by andreasnw** [comment] 2024-02-27 07:03
not a regression https://github.com/Expensify/App/issues/37248#issuecomment-1965808408

**Comment by dylanexpensify** [comment] 2024-02-28 08:56
Nice! Payout coming soon if no regression!

**Comment by dylanexpensify** [comment] 2024-03-06 11:14
ah, payment didn't autogenerate, but been 7 days, so will work on this now!

**Comment by andreasnw** [comment] 2024-03-06 12:01
appreciate your help, @dylanexpensify, thank you!

**Comment by andreasnw** [comment] 2024-03-13 03:43
hi @dylanexpensify any updates on this payment issue?

**Comment by andreasnw** [comment] 2024-03-13 10:40
How do i apply/ request @dylanexpensify ?

**Comment by dylanexpensify** [comment] 2024-03-13 10:40
Ah, that's for our records @andreasnw! You've now been paid! 🎉

**Comment by rlinoz** [comment] 2024-03-15 12:36
Since everyone has been paid we can close this one out.

**Closed by rlinoz** 2024-03-15 12:36 UTC
Labels: Reviewing, External, Weekly, Bug

**Comment by JmillsExpensify** [comment] 2024-03-22 21:50
$500 approved for @eVoloshchak based on summary.
