### ISSUE TITLE
[Landing page] use.expensify.com sign up with google is broken

### ISSUE THREAD

**Issue by m-natarajan** [Expensify/App#47665] opened 2024-08-19 20:23 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:**
**Reproducible in staging?:**
**Reproducible in production?:** Y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** @neil-marcellini 
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1723861150556149

## Action Performed:
1. Create a gmail account or pick one that you have never used with Expensify before
2. Go to use.expensify.com
3. Click sign up with google
4. Select the google account
## Expected Result:
You will be sign up and logged in to New Expensify with that google account
## Actual Result:
New Expensify opens to a page which says "Your session has expired. Please sign in again."
## Workaround:
Can the user still use Expensify without this being fixed? Have you informed them of the workaround?

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [x] Android: mWeb Chrome
- [x] iOS: Native
- [x] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

https://github.com/user-attachments/assets/e8dbd4dc-26de-4af9-8741-bc07a893a6a8

Add any screenshot/video evidence

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

https://github.com/user-attachments/assets/c1b4c0f4-bb43-4925-b80d-da69002b4eb2

<details><summary>Issue Owner</summary>Current Issue Owner: @neil-marcellini</details>

**Comment by isabelastisser** [comment] 2024-08-20 13:33
@neil-marcellini, is this internal?

**Comment by neil-marcellini** [comment] 2024-08-22 18:36
I think my strategy with this will be to write a rough plan about how to fix it, then post it for review in Slack engineering-chat and also ask if anyone can help me out. It's a bit daunting.

**Plan to fix UseDot sign up with google**

- As background, after a lot of digging around in the current flow I can't find any code that would actually create an account, it would only log into an existing account
- Modify the links on OldDot to set a URL param `authMethod=google`
- In the [oauth2 flow](https://github.com/Expensify/Web-Expensify/blob/b75aeeac0075bdc7f518ee78f958f39c1b4891f5/authentication/oauth2.php#L258), get the authMethod param and if it's non-empty set it in the extra state so it will be persisted in a cookie
- In the loginCallback pass the state's authMethod through to the [partnerSignin flow](https://github.com/Expensify/Web-Expensify/blob/b75aeeac0075bdc7f518ee78f958f39c1b4891f5/authentication/oauth2.php#L167)
- ...



Oh damn never mind, I finally found where we [create the account](https://github.com/Expensify/Web-Expensify/blob/566f76b3985a62ff9945d64ed11aaae07816182b/lib/Authentication.php#L197). It was a little buried in this wacky PHP code. Now that I found this I'll start playing around on dev and maybe looking at prod logs to see why we're not hitting this part.

**Comment by neil-marcellini** [comment] 2024-08-26 20:51
I'll work on this today

**Comment by neil-marcellini** [comment] 2024-08-27 16:21
I got sign up with google to create an account in my dev environment. The actual problem has something to do with the NewDot transition, which I guess I should have known. I'll need to figure out how to delete all traces of the account so I can test with the same one again (maybe with an operator script), and then focus in on why the transition isn't working.

**Comment by isabelastisser** [comment] 2024-08-29 20:41
Any updates here, @neil-marcellini ? Thanks!

**Comment by neil-marcellini** [comment] 2024-08-30 22:16
More struggles today (8/29), but I did get the operator command working to delete the google test account on dev. I think there's something specific about the transition flow after coming through this oauth flow that causes the error. This stack track shows that `needsCSRFToken` is trying to get the email from the short lived authToken, and that causes a 407.

```
2024-08-30T04:22:52.685587+00:00 expensidev2004 php-fpm: fJMBko /api.php  !ecash9.0.26-2! ?api? [info] Got an authorization error Expensify\Error\Auth\AuthTokenExpired - 9b953676-e64d-4262-bf74-1bf0ff888e4d ~~ command: 'SignInWithShortLivedAuthToken' exceptionJsonCode: '407' exceptionUserMessage: 'Your session has expired. Please sign in again.' exceptionMessage: '' exceptionFile: '/vagrant/Web-Expensify/lib/Auth.php' exceptionLine: '258' exceptionCode: '666'
2024-08-30T04:22:52.685608+00:00 expensidev2004 php-fpm: fJMBko /api.php  !ecash9.0.26-2! ?api? [info] [trace] StackTrace start
2024-08-30T04:22:52.685618+00:00 expensidev2004 php-fpm: fJMBko /api.php  !ecash9.0.26-2! ?api? [info] [trace] 0/8. file '/vagrant/Web-Expensify/lib/Auth.php' function '_parseRawResponse' line '515'
2024-08-30T04:22:52.685626+00:00 expensidev2004 php-fpm: fJMBko /api.php  !ecash9.0.26-2! ?api? [info] [trace] 1/8. file '/vagrant/Web-Expensify/lib/Auth.php' function 'call' line '599'
2024-08-30T04:22:52.685633+00:00 expensidev2004 php-fpm: fJMBko /api.php  !ecash9.0.26-2! ?api? [info] [trace] 2/8. file '/vagrant/Web-Expensify/lib/User/Store.php' function 'get' line '43'
2024-08-30T04:22:52.685641+00:00 expensidev2004 php-fpm: fJMBko /api.php  !ecash9.0.26-2! ?api? [info] [trace] 3/8. file '<no_file>' function 'load' line '<no_line>'
2024-08-30T04:22:52.685649+00:00 expensidev2004 php-fpm: fJMBko /api.php  !ecash9.0.26-2! ?api? [info] [trace] 4/8. file '/vagrant/Web-Expensify/lib/Auth/Store.php' function 'forward_static_call' line '39'
2024-08-30T04:22:52.685656+00:00 expensidev2004 php-fpm: fJMBko /api.php  !ecash9.0.26-2! ?api? [info] [trace] 5/8. file '/vagrant/Web-Expensify/lib/User/Store.php' function 'getByID' line '65'
2024-08-30T04:22:52.685664+00:00 expensidev2004 php-fpm: fJMBko /api.php  !ecash9.0.26-2! ?api? [info] [trace] 6/8. file '/vagrant/Web-Expensify/lib/Request.php' function 'get' line '323'
2024-08-30T04:22:52.685672+00:00 expensidev2004 php-fpm: fJMBko /api.php  !ecash9.0.26-2! ?api? [info] [trace] 7/8. file '/vagrant/Web-Expensify/lib/Request.php' function 'getEmailFromAuthToken' line '434'
2024-08-30T04:22:52.685680+00:00 expensidev2004 php-fpm: fJMBko /api.php  !ecash9.0.26-2! ?api? [info] [trace] 8/8. file '/vagrant/Web-Expensify/api.php' function 'needsCSRFToken' line '125'
2024-08-30T04:22:52.685687+00:00 expensidev2004 php-fpm: fJMBko /api.php  !ecash9.0.26-2! ?api? [info] [trace] StackTrace end
2024-08-30T04:22:52.685884+00:00 expensidev2004 php-fpm: YFueue /api.php  !ecash9.0.26-2! ?api? [info] Got an authorization error Expensify\Error\Auth\AuthTokenExpired - 9b953676-e64d-4262-bf74-1bf0ff888e4d ~~ command: 'SignInWithShortLivedAuthToken' exceptionJsonCode: '407' exceptionUserMessage: 'Your session has expired. Please sign in again.' exceptionMessage: '' exceptionFile: '/vagrant/Web-Expensify/lib/Auth.php' exceptionLine: '258' exceptionCode: '666'
```

**Comment by neil-marcellini** [comment] 2024-08-31 01:32
The root cause of the error is coming from [here in Auth](https://github.com/Expensify/Auth/blob/415e5a17d41f5ae10e174f6eaa71db44875f5429/auth/lib/AuthToken.cpp#L996-L1000)

```cpp
    // Password logins should be disabled for unvalidated partner=Expensify and infinite sessions.
    const bool isExpensifyPartnerOrInfiniteSession = SContains(list<int64_t>{Partner::PARTNER_ID_EXPENSIFY, Partner::PARTNER_ID_ANDROID, Partner::PARTNER_ID_IPHONE, Partner::PARTNER_ID_NEWDOT}, partnerID);
    if (authTokenType == AuthToken::TYPE_NORMAL && isExpensifyPartnerOrInfiniteSession && !authToken.test("isPasswordless") && authToken.test("isValidated")) {
        STHROW("407 Unauthorized - Passwordless Authentication Required");
    }
```

The command says password logins should be disabled for unvalidated cases, but the check is for validated cases. It looks like the code has been checking for validated for a while, so I think the comment is wrong. Is that correct @johnmlee101? In this flow we're signing in with google, then creating a short lived token, then getting the user's account with it. So the account created from the google sign in has an authToken that is not marked as a passwordless login, but I definitely think it should get an exception to this check. Or I guess a more sensible way to do it would be to generate the short lived token with the same partnerID as the existing auth token, which will be the google partnerID in this case. I think that should fix it. I'll test next time.

**Comment by johnmlee101** [comment] 2024-09-02 15:34
> password logins should be disabled for unvalidated cases

Ah bad comment. Should be disabled for any validated account

**Comment by johnmlee101** [comment] 2024-09-02 15:34
> So the account created from the google sign in has an authToken that is not marked as a passwordless login

Google sign ins should always be marked passwordless, so not sure how that happened :grim

**Comment by neil-marcellini** [comment] 2024-09-03 15:30
Awesome thanks John! I think setting it as passwordless was probably missed because UseDot sign up with google uses a different flow from OldDot and NewDot. I verified that fixes it, and I'll add an automated test soon, then put the PR up for review.

**Comment by neil-marcellini** [comment] 2024-09-04 23:29
Automated test is passing, fails without this change, and the PR is up for review 🚀.

I'm going to work on an SO for instructions about how to test UseDot Google sign up on dev so it's easier for the next person, and I'm also going to put up a PR for an operator command which I used to delete all traces of a given account which made it easy to test this repeatedly. I'll make sure it's possible to have that only runnable on dev.

**Comment by isabelastisser** [comment] 2024-09-11 20:06
@neil-marcellini, I see the PR was merged. I this all set?

**Comment by isabelastisser** [comment] 2024-09-13 17:23
@neil-marcellini, I am closing this because I see the PR was merged, and no external payments are required. Thanks!

**Closed by isabelastisser** 2024-09-13 17:23 UTC
Labels: Reviewing, Daily, Internal, Bug
