### ISSUE TITLE
[$500] IOU - Distance request with vague location created offline shows incorrect error online

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#36493] opened 2024-02-14 14:38 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.41
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**If this was caught during regression testing, add the test name, ID and link from TestRail:** https://expensify.testrail.io/index.php?/tests/view/4314136
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** Applause - Internal Team
**Slack conversation:**

## Action Performed:
1. Launch app
2.  Turn off mobile data
3.  Tap fab
4. Tap request money--- distance
5. Tap start
6. Enter SF and tap save
7. Tap finish
8. Enter LA and tap save
9. Tap next
10. Select a workspace
11. Tap request
12. Turn on mobile data

## Expected Result:
In offline, with vague location distance request created after turning online must show correct error message "Unable to find the location for this address. Please edit the address and try again. ”

## Actual Result:
In offline, with vague location distance request created after turning online shows incorrect error message "Unexpected error requesting money, please try again later" instead of "Unable to find the location for this address. Please edit the address and try again.”

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [x] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details>  

https://github.com/Expensify/App/assets/78819774/11fd4292-7e6c-47c4-9053-98b4de0dab8c

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~014b08208fbad4a9ac</li>
        <li>Upwork Job ID: 1757776229611659264</li>
        <li>Last Price Increase: 2024-02-21</li>
    </ul>
</details>

**Comment by lanitochka17** [comment] 2024-02-14 14:39
We think that this bug might be related to #wave5
CC @dylanexpensify

**Comment by jliexpensify** [comment] 2024-02-15 01:39
Asked Dylan here - https://expensify.slack.com/archives/C05DWUDHVK7/p1707961175788869

**Comment by brunovjk** [comment] 2024-02-19 20:05
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
Incorrect error message displayed in app for offline-created distance request when online.

### What is the root cause of that problem?
In `buildOnyxDataForMoneyRequest` we always use a `genericCreateFailureMessage` for transaction failure: https://github.com/Expensify/App/blob/935c44ae97f3dbe28b0bb4b237df4534ba594e86/src/libs/actions/IOU.ts#L612 https://github.com/Expensify/App/blob/935c44ae97f3dbe28b0bb4b237df4534ba594e86/src/languages/en.ts#L654

### What changes do you think we should make in order to solve the problem?
We need to add a _"Unable to find the location for this address. Please edit the address and try again."_ at `anguages/en.ts`, sometjhing like:
```
error: {
    // ... (existing error messages)
    invalidLocation: 'Unable to find the location for this address. Please edit the address and try again.',
    // ... (other error messages)
}
```
And properly use it when the request fails due to invalid waypoints.

### What alternative solutions did you explore? (Optional)

**Comment by c3024** [comment] 2024-02-20 09:08
@brunovjk 

Could you be more specific about which conditions (with variables) will wel add this `invalidLocation` error. Also, isn't this error sent by the backend?

**Comment by brunovjk** [comment] 2024-02-20 20:18
@c3024 With the same steps for reproduction, this [issue](https://github.com/Expensify/App/issues/31834) has a different Expected Result. I assume we're dealing with a kind of new feature here, is that correct?

> isn't this error sent by the backend?

Yes. But it sends a _"Please select a valid waypoint."_ message. While we can use this, it seems the message isn't yet expected for this particular issue.
<details>
<summary>invalid waypoint offline</summary>



![invalid waypoint offline](https://github.com/Expensify/App/assets/95647348/f8798c57-b1ca-4cdd-aed5-d067d9f42789)

</details>

If we repeat the steps for reproduction, but return Online in step 8, we see that we cannot proceed, and this error message above appears:
<details>
<summary>invalid waypoint online</summary>



![invalid waypoint online](https://github.com/Expensify/App/assets/95647348/ed5c9390-093d-4e33-8db9-e629ea30b8c5)

</details>

Should the behavior be similar in both reproductions above?

**Comment by brunovjk** [comment] 2024-02-20 20:20
@c3024 With the same steps for reproduction, this [issue](https://github.com/Expensify/App/issues/31834) has a different Expected Result. I assume we're dealing with a kind of new feature here, is that correct?

> isn't this error sent by the backend?

Yes. But it sends a _"Please select a valid waypoint."_ message. While we can use this, it seems the message isn't yet expected for this particular issue.
<details>
<summary>invalid waypoint offline</summary>



![invalid waypoint offline](https://github.com/Expensify/App/assets/95647348/f8798c57-b1ca-4cdd-aed5-d067d9f42789)

</details>

If we repeat the steps for reproduction, but `return to online` in step 8, we see that we cannot proceed, and this error message above appears:
<details>
<summary>invalid waypoint online</summary>



![invalid waypoint online](https://github.com/Expensify/App/assets/95647348/ed5c9390-093d-4e33-8db9-e629ea30b8c5)

</details>

Should the behavior be similar in both reproductions above?
Thank you :D

**Comment by jliexpensify** [comment] 2024-02-23 05:43
Bump @c3024

**Comment by brunovjk** [comment] 2024-02-23 11:55
I continue investigating and testing, I will update my proposal soon.

**Comment by brunovjk** [comment] 2024-02-25 18:13
I've been investigating and couldn't find a solution completely through the frontend. In addition to the new message _"Unable to find the location for this address. Please edit the address and try again."_, I believe there is a problem with the backend here, the _issue report video_ doesn't show it but the request appears to be deleted without even the user "dismissing the error".

**Comment by jliexpensify** [comment] 2024-02-25 21:16
Bump @c3024 - can you confirm if this is a `back-end` issue? Thanks!

**Comment by jliexpensify** [comment] 2024-02-25 22:29
Actually should be #wave6 - posted: https://expensify.slack.com/archives/C02MW39LT9N/p1708900139785349

**Comment by brunovjk** [comment] 2024-02-25 22:35
@jliexpensify external like me do not have access to this archive right?

**Comment by jliexpensify** [comment] 2024-02-25 23:09
@brunovjk - if it's a back-end issue, we'll apply the `Internal` label for an Expensify Engineer to pick up.

From that point on, the engineer can determine if we need help from Contributors.

**Comment by brunovjk** [comment] 2024-02-25 23:59
Very good @jliexpensify, thank you very much!

**Comment by c3024** [comment] 2024-02-26 04:41
@jliexpensify 

Yes, the validation happens on backend so backend sending the correct error message is appropriate. Please apply `Internal` label. Thanks.

**Comment by jliexpensify** [comment] 2024-02-26 20:47
Great, thanks for jumping in Neil. Closing (also requested by Greg)!

**Closed by jliexpensify** 2024-02-26 20:47 UTC
Labels: Daily, Internal, Bug
