### ISSUE TITLE
[HOLD for payment 2023-11-21] Nontification preferences - Mute option not seen in notification prefrences when immediately is selected

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#31192] opened 2023-11-10 17:51 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.3.98-0
**Reproducible in staging?:** Y
**Reproducible in production?:** N
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** Applause - Internal Team
**Slack conversation:**

## Action Performed:
1. Open the app
2. Navigate to any room or chat
3. Tap the header Settings > Notification prefrences

## Expected Result:
All the menu options "Mute", "Daily" and "Immediately" are visible

## Actual Result:
The "Mute" option is not visible when "Immediately" is selected

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [x] Android: mWeb Chrome
- [x] iOS: Native
- [x] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details> 

https://github.com/Expensify/App/assets/78819774/f51de853-e93e-4077-a156-1205a894aaad

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by esh-g** [comment] 2023-11-10 18:54
Regression from [#30972](vscode-file://vscode-app/Applications/Visual%20Studio%20Code.app/Contents/Resources/app/out/vs/code/electron-sandbox/workbench/workbench.html)

**Comment by situchan** [comment] 2023-11-12 20:35
Removing this line fixes this issue: (Not a real solution but just for testing purpose)
https://github.com/Expensify/App/blob/ffe1c63a57f80479450dcf0e5c2fa82509630c8f/src/components/SelectionList/BaseSelectionList.js#L441

So I can confirm that the root cause is related to combination of `getItemLayout` and `initialScrollIndex`.
When `initialScrollIndex` is set, previous items (index 0 - initialScrollIndex-2) are not rendered and thus `getItemLayout` callback is not called.
That's why this isn't noticeable when number of items are less than 3 (i.e. Language or Priority mode pages).

**Comment by situchan** [comment] 2023-11-12 20:44
Interesting if it's RN bug.
@ishpaul777 can you reproduce with minimal repro step in new RN project?

**Comment by sophiepintoraetz** [comment] 2023-11-12 21:14
This came in over my weekend - i'm able to reproduce. @cead22, I don't think this is deploy blocker worthy though?
![image](https://github.com/Expensify/App/assets/42940078/f80d431b-0a16-47c5-a248-dbded387bf7e)

**Comment by situchan** [comment] 2023-11-12 21:34
I think we should revert

**Comment by sophiepintoraetz** [comment] 2023-11-12 23:16
cc @deetergp @fedirjh @kubabutkiewicz

**Comment by sophiepintoraetz** [comment] 2023-11-14 20:22
Cool - is there a regression test we should include as a part of this - @fedirjh @roryabraham?

**Comment by sophiepintoraetz** [comment] 2023-11-15 01:52
All right, nothing further to do here, given it was a regression. Closing.

**Closed by sophiepintoraetz** 2023-11-15 01:52 UTC
Labels: Engineering, Weekly, Awaiting Payment, Bug
