### ISSUE TITLE
[$2000] Increasing the screen size breaks the UI  - Reported by @thesahindia

### ISSUE THREAD

**Issue by mvtglobally** [Expensify/App#9707] opened 2022-07-05 17:53 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/docs/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Open :expensify: on web/desktop
2. Decrease the screen size (make it mWeb sized)
3. Try increasing the screen size a little

## Expected Result:
It should resize

## Actual Result:
UI breaks at few breakpoints 

## Workaround:
unknown 

## Platform:

Where is this issue occurring?

- Desktop App

**Version Number:** 1.1.79-11
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**Email or phone of affected tester (no customers):** 
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation 

https://user-images.githubusercontent.com/43995119/177386947-1400990b-5c6d-40a4-9db2-4533729d45a1.mov

**Expensify/Expensify Issue URL:** 
**Issue reported by:** @thesahindia
**Slack conversation:** https://expensify.slack.com/archives/C01GTK53T8Q/p1655126933396099

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by bondydaa** [comment] 2022-07-05 22:48
this should be fine for a contributor to work on, i don't know that it's super valuable to fix since how often are users resizing a few pixels at a time?

**Comment by flodnv** [comment] 2022-07-07 10:06
@bondydaa I don't think you meant to unassign @kadiealexander, so I am reassigning.

**Comment by kadiealexander** [comment] 2022-07-11 04:57
https://www.upwork.com/ab/applicants/1546358052488585216/job-details
https://www.upwork.com/jobs/~0143bd5f816ba7431f

**Comment by harshayburadkar** [comment] 2022-07-11 10:53
Just FYI, I see it happening in a web browser as well. So it is not specific to Desktop App, therefore, Platforms in the original issue can be updated to have mWeb in addition to Desktop App.

**Comment by Santhosh-Sellavel** [comment] 2022-07-11 16:45
> Just FYI, I see it happening in a web browser as well. So it is not specific to Desktop App, therefore, Platforms in the original issue can be updated to have Web/mWeb in addition to Desktop App.

@mvtglobally Can you confirm this at your end and update the platforms in the issue description, thanks!

**Comment by kadiealexander** [comment] 2022-07-18 03:10
Price doubled!!

**Comment by Santhosh-Sellavel** [comment] 2022-07-26 18:21
Still reproducible wait for proposals!

**Comment by andrewlor** [comment] 2022-07-26 19:16
## Proposal

### Problem
It seems like a bug in `@react-navigation/drawer` where the `transform: translateX(...)` and `left` properties get messed up during resizing the window, possibly because they're animated.

Essentially when the drawer is open at a mobile screen width, the left and translateX proerties should be at the same absolute value.
![Screen Shot 2022-07-26 at 12 59 38 PM](https://user-images.githubusercontent.com/8475244/181090115-e830cff4-7b10-4fd1-943b-fdbd84244ad8.png)

However when resizing while the drawer is open, the translateX property is getting stuck at some random value.
![Screen Shot 2022-07-26 at 11 42 51 AM](https://user-images.githubusercontent.com/8475244/181090209-238bb951-c8ae-42eb-9c89-5f7f35c136f0.png)

### Solution
One work around I found is essentially force rerendering from `BaseDrawerNavigator` (the direct parent of `Drawer.Navigator`) at some regular cadence when the screen size is changing.
```
class BaseDrawerNavigator extends Component {
    constructor(props) {
        ...
        this.forceUpdateDebounced = _.debounce(() => this.forceUpdate(), 100);
    }

    componentDidUpdate() {
        this.forceUpdateDebounced();
    }
    ...
}
```

### Result
#### Before
To show I was able to reproduce the behaviour before my change.
https://user-images.githubusercontent.com/8475244/181092209-88f0fb5d-fec4-402c-b7ed-681f81dc5f7d.mov

##### After
You can still see the drawer out of position while resizing, but it always repositions itself correctly shortly after because of the rerender.
https://user-images.githubusercontent.com/8475244/181092253-639f0ea5-cdba-46c5-bc5b-dcc3a46315b7.mov

**Comment by Santhosh-Sellavel** [comment] 2022-07-27 17:14
Thanks for the proposal @andrewlor but we are looking for a permanent solution.

**Comment by andrewlor** [comment] 2022-08-02 21:59
@Santhosh-Sellavel Can you let me know what criteria my solution is not meeting to be permanent, so I can adjust it. Is there a specific way you're looking for this to be solved? Thanks.

**Comment by Santhosh-Sellavel** [comment] 2022-08-14 14:22
Sorry @andrewlor missed your comments.

As per your comments, problem seems to be in library, if so then fix should be in the library too right?

**Comment by mvtglobally** [comment] 2022-08-23 04:20
Issue not reproducible during KI retests. (First week)

**Comment by Beamanator** [comment] 2022-09-19 18:31
Not overdue, still not high priority 🤷

**Comment by Beamanator** [comment] 2022-10-24 09:24
@kadiealexander looks like a time to double the reward for this one?

**Comment by kadiealexander** [comment] 2022-10-25 00:37
Ah yes! Job doubled in price, and new job post because the last one closed:

https://www.upwork.com/ab/applicants/1584705464638095360/job-details
https://www.upwork.com/jobs/~01d8d0ffccc4a0f759

**Comment by mvtglobally** [comment] 2022-11-03 02:56
Issue not reproducible during KI retests. (Second week)

**Comment by kadiealexander** [comment] 2022-11-03 04:49
I also [wasn't able to reproduce this](https://expensify.slack.com/archives/C01GTK53T8Q/p1667450928096599?thread_ts=1655126933.396099&cid=C01GTK53T8Q), @thesahindia are you able to share reproduction steps using the latest app version?

**Comment by thesahindia** [comment] 2022-11-03 06:41
I wasn't able to repro as well, it got fixed.

**Comment by Beamanator** [comment] 2022-11-03 09:45
Ok seems like we can close this out

**Closed by Beamanator** 2022-11-03 09:45 UTC
Labels: External, Engineering, Weekly, Improvement, Help Wanted, Bug
