### ISSUE TITLE
Not Found view briefly appears on workspace members and invite pages

### ISSUE THREAD

**Issue by amyevans** [Expensify/App#19236] opened 2023-05-18 23:31 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

This is a follow up issue from https://github.com/Expensify/App/pull/17349#issuecomment-1537823597

## Action Performed:
Open workspace members or invite page from deep link

## Expected Result:
No flash of "Not Found" view

## Actual Result:
Flash of "Not Found" view

## Workaround:
Can the user still use Expensify without this being fixed? Have you informed them of the workaround?

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [ ] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:**
**Reproducible in staging?:**
**Reproducible in production?:**
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation

https://user-images.githubusercontent.com/96077027/236749707-e35006da-92e6-48e7-abfb-3b7c5e4f70a4.mov

https://user-images.githubusercontent.com/96077027/236749763-f88e9a37-e5e4-4ddb-bc9b-be83af3d38d9.mov

**Expensify/Expensify Issue URL:**
**Issue reported by:** @aimane-chnaif 
**Slack conversation:**

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~019ab8e5ee8dfc45ea</li>
        <li>Upwork Job ID: 1669436508157517824</li>
        <li>Last Price Increase: 2023-06-15</li>
    </ul>
</details>

**Comment by amyevans** [comment] 2023-05-18 23:31
@jczekalski please comment on the issue so I can assign you

**Comment by dukenv0307** [comment] 2023-05-19 08:23
This issue is fixed by this PR: https://github.com/Expensify/App/pull/18967

**Comment by dukenv0307** [comment] 2023-05-19 10:01
## Proposal

### Please re-state the problem that we are trying to solve in this issue.

Open workspace members or invite page from deep link and have flash of "Not Found" view

### What is the root cause of that problem?

In here https://github.com/Expensify/App/blob/b7391bca2fb4ae8298468ce31288ec391c3c6191/src/pages/workspace/WorkspaceInviteMessagePage.js#L151
We're showing Not Found page if the `this.props.policy` is empty. When we navigate to the Workspace Settings page by link and login, the `policy` wasn't loaded yet (using the `OpenApp` API), so it shows Not Found briefly until the `policy` is loaded.

### What changes do you think we should make in order to solve the problem?

Base on @aimane-chnaif's comment, we need to build `WorkspaceInvitePageSkeletonView` and `WorkspaceMembersPageSkeletonView` and check if the policy is empty and the report is loading, if yes that means the policy is not initially loaded yet, so we show a `WorkspaceInvitePageSkeletonView` or `WorkspaceMembersPageSkeletonView`
```
if (this.props.isLoadingReportData && _.isEmpty(this.props.policy)) {
    return <WorkspaceMembersPageSkeletonView />;
}
```

```
if (this.props.isLoadingReportData && _.isEmpty(this.props.policy)) {
    return <WorkspaceInvitePageSkeletonView />;
}
```

### What alternative solutions did you explore? (Optional)
NA

**Comment by jczekalski** [comment] 2023-05-19 10:26
I'm an expert contributor from Software Mansion and I'd like to investigate this issue (@amyevans).

**Comment by mallenexpensify** [comment] 2023-05-22 23:55
@jczekalski can you provide an update? Do you plan to post a proposal soon?

**Comment by jczekalski** [comment] 2023-05-25 14:12
@mallenexpensify Sorry for the delay, we decided to reassign this task to a new developer who just joined the team. They just started working on it today.

**Comment by kowczarz** [comment] 2023-05-25 14:39
Hey, I'm from Software Mansion, I'd like to work on this job.

**Comment by amyevans** [comment] 2023-05-25 14:54
@kowczarz Just a heads up I added you to our Upwork whitelist, so in a few days (once it deploys), Melvin should stop asking you for your Upwork details whenever you comment on a GH 😄

**Comment by amyevans** [comment] 2023-05-25 23:24
FYI: I'll be OOO tomorrow and Monday.

**Comment by mallenexpensify** [comment] 2023-05-30 22:00
@aimane-chnaif can you review @kowczarz 's proposal above plz?

**Comment by kowczarz** [comment] 2023-06-06 09:27
@aimane-chnaif this HOC wraps a whole screen, while the skeleton that blinks for a moment wraps only the users list (2 in the picture below), while the header with navigation (1 in the picture below) is already displayed, so if we add the optional skeleton to `withPolicyAndFullscreenLoading`, we would add unnecessary complexity to the component and the it would cause additional re-render which would lead to weird "flashing" behaviour.
<img width="440" alt="Screenshot 2023-06-06 at 11 21 15" src="https://github.com/Expensify/App/assets/91068263/25944e55-1229-49f8-b248-93e5b17f1859">

**Comment by mallenexpensify** [comment] 2023-06-09 00:22
@aimane-chnaif , do you agree with @kowczarz comment above?
>  if we add the optional skeleton to withPolicyAndFullscreenLoading, we would add unnecessary complexity to the component and the it would cause additional re-render which would lead to weird "flashing" behaviour.

**Comment by kowczarz** [comment] 2023-06-12 08:42
@aimane-chnaif do you have any thoughts on [this](https://github.com/Expensify/App/issues/19236#issuecomment-1578284215)?

**Comment by mallenexpensify** [comment] 2023-06-12 23:13
@aimane-chnaif can you please provide an update?

**Comment by kowczarz** [comment] 2023-06-15 12:09
@aimane-chnaif FIY I will be OOO for a couple of days and I will be back on Wednesday.

**Comment by amyevans** [comment] 2023-06-21 16:38
Okay sounds good, @kowczarz please start on a PR. Thanks!

**Comment by kowczarz** [comment] 2023-06-22 13:31
Sure, will start as soon as I will finish applying changes in another PR

**Comment by amyevans** [comment] 2023-06-30 22:43
Heads up I'm OOO Mon/Tue next week.

**Comment by mallenexpensify** [comment] 2023-07-04 17:42
@aimane-chnaif can you please review the PR, it's been waiting for review for a week :/ 
https://github.com/Expensify/App/pull/21387

**Comment by roryabraham** [comment] 2023-07-09 20:42
Hey we had a (maybe duplicate) issue created in https://github.com/Expensify/App/issues/21567, and I rejected a proposal to add a loading spinner, suggesting that instead we should create a skeleton UI. Looking at https://github.com/Expensify/App/pull/21387, it appears to just add a regular activity indicator. Should we instead add a skeleton UI?

**Comment by roryabraham** [comment] 2023-07-09 20:44
Also, according to the reproduction steps and videos in https://github.com/Expensify/App/issues/21567, it seems like `Not Found` is not flashing anymore, but just an empty space?

**Comment by mallenexpensify** [comment] 2023-07-18 18:18
PR is actively being worked and commented on. 
- https://github.com/Expensify/App/pull/21387#issuecomment-1627432736

**Comment by amyevans** [comment] 2023-08-04 20:22
@aimane-chnaif can you prioritize another review of the PR please? It'd be nice to get this over the line

**Comment by mallenexpensify** [comment] 2023-09-05 02:52
Removed `Reviewing` so this will now go overdue. 
@aimane-chnaif @amyevans who's due compensation here? I think it's $1k each to @aimane-chnaif and @kowczarz but wanna make sure. 

@sakluger  I'm off this week, can you please keep 👀 on this then I'll snag it back on Monday?  Thx

**Comment by amyevans** [comment] 2023-09-05 13:59
I think @aimane-chnaif is due reporter bonus here still, $250. @kowczarz is an agency contributor so not compensated via Upwork.

> But am I eligible for more compensation fixing another issue as well? - https://github.com/Expensify/App/issues/21567

Hmm I don't think so unless it dramatically increased the scope. There was no proposal review process or 2nd PR to review/test. We'd just compensate for the separate bug report there, which looks like that already happened on the GH.

**Comment by sakluger** [comment] 2023-09-05 18:44
I agree with @amyevans, if the two bugs had the same root cause and were fixed with one PR, then we would only pay for that fix once.

@amyevans since I'm just coming into this issue now, what payments are due here? Just the reporting bonus?

**Comment by amyevans** [comment] 2023-09-05 18:50
@sakluger yep, reporting bonus

**Comment by mallenexpensify** [comment] 2023-09-11 07:37
@aimane-chnaif can you please accept the job and reply here once you have? 
https://www.upwork.com/jobs/~01ab002e55737f23b6

**Comment by sakluger** [comment] 2023-09-11 16:06
All paid and done, thanks everyone!

**Closed by sakluger** 2023-09-11 16:06 UTC
Labels: Daily, Internal, Bug
