### ISSUE TITLE
[HOLD for payment 2024-11-29] [Held] [$250] Invoices - Workspace settings can be opened from "workspace" link when workspace is deleted

### ISSUE THREAD

**Issue by IuliiaHerets** [Expensify/App#49093] opened 2024-09-12 15:29 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 9.0.33-1
**Reproducible in staging?:** Y
**Reproducible in production?:** N/A - new feature, doesn't exist in prod
**Issue was found when executing this PR:** https://github.com/Expensify/App/pull/48275
**Email or phone of affected tester (no customers):** applausetester+kh010901@applause.expensifail.com
**Issue reported by:** Applause Internal Team

## Action Performed:
Precondition:
- User B has no workspace.

1. Go to staging.new.expensify.com
2. {User A] Send an invoice to User B.
3. [User B] Pay the invoice using Pay as a business option.
4. [User B] Delete the workspace.
5. {User B] Go to invoice chat.
6. [User B] Click on the "workspace" link in Expensify message.

## Expected Result:
The link should lead to not here page because workspace is deleted.

## Actual Result:
The link can open workspace settings page and Members tab leads to not here page.

## Workaround:
Unknown

## Platforms:

- [x] Android: Native
- [x] Android: mWeb Chrome
- [x] iOS: Native
- [x] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

https://github.com/user-attachments/assets/a1540862-f566-4c88-b999-caf2bdf3094f

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~021834598579747458653</li>
        <li>Upwork Job ID: 1834598579747458653</li>
        <li>Last Price Increase: 2024-09-13</li>
<li>Automatic offers: </li>
<ul>
<li>ishpaul777 | Contributor | 104008088</li>
<li>gijoe0295 | Contributor | 104027162</li>
</ul></li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @joekaufmanexpensify</details>

**Comment by IuliiaHerets** [comment] 2024-09-12 15:29
We think that this bug might be related to #vip-bills

**Comment by iwiznia** [comment] 2024-09-12 16:44
Removed blocker, see https://expensify.slack.com/archives/C9YU7BX5M/p1726158576447559

**Comment by luacmartins** [comment] 2024-09-12 17:31
@IuliiaHerets I think the uploaded video is incorrect. Can you please check?

**Comment by IuliiaHerets** [comment] 2024-09-12 17:40
@luacmartins fixed, sorry for this

**Comment by luacmartins** [comment] 2024-09-12 17:44
No problem. Thank you!

**Comment by luacmartins** [comment] 2024-09-12 17:47
This is also reproducible in prod if we just copy/paste the workspace link

**Comment by rlinoz** [comment] 2024-09-12 17:48
Just by having the workspace link in any chat the problem also happens in prod:

https://github.com/user-attachments/assets/778e2117-0eb4-47b8-9f49-6da855676b88

**Comment by IuliiaHerets** [comment] 2024-09-12 18:05
We can't pay the invoice using Pay as a business in prod, so I marked it as N/A - can't check on prod

**Comment by nkdengineer** [comment] 2024-09-16 04:20
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
The link can open the workspace settings page and Members tab leads to not here page.

### What is the root cause of that problem?
After the user deletes the workspace, the policy data still exists then the not found page doesn't display because this check doesn't cover full case like we did [here](https://github.com/Expensify/App/blob/b69577a55bc536a411d8c1e51fc47fc0fc00d389/src/pages/workspace/WorkspacesListPage.tsx#L316)

https://github.com/Expensify/App/blob/14b5ccc38534683a4d96460ee5266732a65f3b0a/src/pages/workspace/WorkspacePageWithSections.tsx#L164-L170


<img width="1512" alt="Screenshot 2024-09-16 at 11 05 10" src="https://github.com/user-attachments/assets/1c860a69-3e68-4622-9cc1-57419983cc06">

### What changes do you think we should make in order to solve the problem?

We should use the same check as we did [here](https://github.com/Expensify/App/blob/b69577a55bc536a411d8c1e51fc47fc0fc00d389/src/pages/workspace/WorkspacesListPage.tsx#L316) in `shouldShow` here then that can fix for all policy pages


```
const shouldShowPolicy = useMemo(() => {
    return PolicyUtils.shouldShowPolicy(policy, isOffline, session?.email);
}, [policy, isOffline, session?.email]);

const prevShouldShowPolicy = useMemo(() => {
    return PolicyUtils.shouldShowPolicy(prevPolicy, isOffline, session?.email);
}, [prevPolicy, isOffline, session?.email]);

const shouldShow = useMemo(() => {
    // If the policy object doesn't exist or contains only error data, we shouldn't display it.
    if (((isEmptyObject(policy) || (Object.keys(policy).length === 1 && !isEmptyObject(policy.errors))) && isEmptyObject(policyDraft)) || shouldShowNotFoundPage) {
        return true;
    }

    // We check isPendingDelete for both policy and prevPolicy to prevent the NotFound view from showing right after we delete the workspace
    return (!isEmptyObject(policy) && !PolicyUtils.isPolicyAdmin(policy) && !shouldShowNonAdmin) || (!shouldShowPolicy && !prevShouldShowPolicy);
    // eslint-disable-next-line react-compiler/react-compiler, react-hooks/exhaustive-deps
}, [policy, shouldShowNonAdmin, shouldShowPolicy, prevShouldShowPolicy]);
```
https://github.com/Expensify/App/blob/14b5ccc38534683a4d96460ee5266732a65f3b0a/src/pages/workspace/WorkspacePageWithSections.tsx#L164-L170

Then we can update the condition here like this to display the correct subtitle

```
shouldShowPolicy ?  'workspace.common.notAuthorized' : undefined
```
https://github.com/Expensify/App/blob/b69577a55bc536a411d8c1e51fc47fc0fc00d389/src/pages/workspace/WorkspacePageWithSections.tsx#L190

We can do the same fix for `WorkspaceInitialPage`
https://github.com/Expensify/App/blob/b69577a55bc536a411d8c1e51fc47fc0fc00d389/src/pages/workspace/WorkspaceInitialPage.tsx#L310
### What alternative solutions did you explore? (Optional)

We can fix this from BE side that will not return the data of deleted policy

**Comment by joekaufmanexpensify** [comment] 2024-09-17 13:40
@ntdiary can you review proposals here?

**Comment by joekaufmanexpensify** [comment] 2024-09-18 13:55
Pending @ishpaul777 review of proposals

**Comment by nkdengineer** [comment] 2024-09-18 15:19
> PolicyUtils.isPendingDeletePolicy(policy) && PolicyUtils.isPendingDeletePolicy(prevPolicy)

@ishpaul777 Here is the old condition and we should replace it with `shouldShowPolicy` function. That is why we have `prevShouldShowPolicy` variable. I create a new variable because we need to use `shouldShowPolicy` to display the correct subtitle.

>  subtitleKey={isEmptyObject(policy) ? undefined : 'workspace.common.notAuthorized'}

**Comment by joekaufmanexpensify** [comment] 2024-09-19 13:31
@gijoe0295 is there an ETA for PR here?

**Comment by joekaufmanexpensify** [comment] 2024-09-23 14:44
PR in review

**Comment by joekaufmanexpensify** [comment] 2024-10-07 14:58
Sounds good!

**Comment by joekaufmanexpensify** [comment] 2024-10-14 13:55
PR still in review

**Comment by joekaufmanexpensify** [comment] 2024-10-21 13:45
This one's now held for https://github.com/Expensify/react-native-onyx/pull/588 , we'll finish up the PR once that's out.

**Comment by joekaufmanexpensify** [comment] 2024-11-04 16:32
@ishpaul777 @srikarparsi I see the above PR was merged and published. Can we take this off hold now?

**Comment by joekaufmanexpensify** [comment] 2024-11-04 17:14
Great. TY!

**Comment by joekaufmanexpensify** [comment] 2024-11-11 15:37
@gijoe0295 Did you have a chance to do this?

**Comment by joekaufmanexpensify** [comment] 2024-11-18 16:58
Sounds good. TY!

**Comment by joekaufmanexpensify** [comment] 2024-11-25 16:31
@ishpaul777 could you handle the checklist here?

**Comment by joekaufmanexpensify** [comment] 2024-11-26 16:17
As an fyi, I am OOO the rest of the week after today. Assuming the checklist is done by then, I will handle payment on Monday!

**Comment by joekaufmanexpensify** [comment] 2024-12-02 15:00
Just back from OOO. Will handle remaining steps today!

**Comment by joekaufmanexpensify** [comment] 2024-12-02 15:54
Checklist is all set. We're good to pay.

**Comment by joekaufmanexpensify** [comment] 2024-12-02 15:54
We need to pay: 

- @gijoe0295 $250 for PR via Upwork. 
- @ishpaul777 $250 for C+ via NewDot.

**Comment by joekaufmanexpensify** [comment] 2024-12-02 15:55
@gijoe0295 $250 sent and contract ended!

**Comment by joekaufmanexpensify** [comment] 2024-12-02 15:56
@ishpaul777 $250 sent and contract ended!

**Comment by joekaufmanexpensify** [comment] 2024-12-02 15:56
Upwork job closed

**Comment by joekaufmanexpensify** [comment] 2024-12-02 15:56
All set, thanks everyone!

**Closed by joekaufmanexpensify** 2024-12-02 15:56 UTC
Labels: External, Engineering, Daily, Awaiting Payment, Bug
