### ISSUE TITLE
[$500]  [Distance] - Distance message changes from 'mile' to 'mi' on IOU detail page

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#27267] opened 2023-09-12 16:02 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Open request money
2. Change the tab to distance
3. Select start and finish location and click next
4. Select workspace and click next
5. Notice the Distance message and click request
6. Open the request in the workspace

## Expected Result:
The distance message on the IOU detail page should display 'mile' or 'miles' as the unit of measurement

## Actual Result:
The distance message on the IOU detail page displays 'mi' as the unit of measurement.

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [x] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 1.3.68.12
**Reproducible in staging?:** y 
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/93399543/e59fb75a-139a-47d1-8e5f-dd219ae2970d

https://github.com/Expensify/App/assets/93399543/f51f961c-e45a-458f-ba90-8593c3f8c691

**Expensify/Expensify Issue URL:**
**Issue reported by:** @jo-ui
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1694256759509979

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~017b6ff5aa114aa173</li>
        <li>Upwork Job ID: 1701627308540997632</li>
        <li>Last Price Increase: 2023-09-12</li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @marcochavezf</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @marcochavezf</details>

**Comment by studentofcoding** [comment] 2023-09-12 17:32
# Proposal

## Please re-state the problem that we are trying to solve in this issue

Distance message changes from 'mile' to 'mi' on IOU detail page

## What is the root cause of that problem?

The root cause of the problem is that the unit of measurement for distance is hardcoded as 'mi' in the `CONST.CUSTOM_UNITS.DISTANCE_UNIT_MILES`. This constant is defined as 'mi', not 'miles' or 'mili'.

https://github.com/Expensify/App/blob/3e506835eb7214ae15c3e36334484188c8ba50e3/src/CONST.ts#L1110C1-L1112C35

## What changes do you think we should make in order to solve the problem?

If we only want to use `miles` instead of `mili`, we just need to change the const into `miles`

## What alternative solutions did you explore? (Optional)

We can also keep the `mi` but change it to `miles` instead on Report Screen after the map is loading

**Comment by lcsvcn** [comment] 2023-09-12 18:32
# Proposal
## Please re-state the problem that we are trying to solve in this issue
Distance message changes from `mile` to `mi` on IOU detail page

## What is the root cause of that problem?
The root cause of the problem is located inside the function **getTransactionDetails** function located at [src/libs/ReportUtils.js](https://github.com/Expensify/App/blob/6188d7b06f50e34f19c6f6f1ea8f59b2a3f412a6/src/libs/ReportUtils.js#L1288)

```
function getTransactionDetails(transaction) {
    const report = getReport(transaction.reportID);
    return {
        created: TransactionUtils.getCreated(transaction),
        amount: TransactionUtils.getAmount(transaction, isExpenseReport(report)),
        currency: TransactionUtils.getCurrency(transaction),
        comment: TransactionUtils.getDescription(transaction),
        merchant: TransactionUtils.getMerchant(transaction),  // THE FORMAT ISSUE IS LOCATED HERE
    };
}
```

At field **merchant**, it is returning in this following format:
`2921.48 mi @ R$0.655 / mi`.

Since we want to display in this format below:
`2921.48 miles @ R$0.655 / mile`

In order to make it return in the expected format, we need to implement a way to parse `mi` to `miles` or `mile` (if singular) and same to `km` to `kilometers` or `kilometer` (if singular)


## What changes do you think we should make in order to solve the problem?
I need to implement a comparison like the below before assign to the field `merchant` at function `getTransactionDetails`. Solution is similar to how it is done at [getDistanceMerchant](https://github.com/Expensify/App/blob/6188d7b06f50e34f19c6f6f1ea8f59b2a3f412a6/src/libs/DistanceRequestUtils.js#L72)

That is why at IOU creation page (where we create the payment request) we see the expected format and at IOU detail page we don't see the same format, because it is using the default CONST.CUSTOM_UNITS.DISTANCE_UNIT_MILES.


```
const distanceUnit = unit === CONST.CUSTOM_UNITS.DISTANCE_UNIT_MILES ? translate('common.miles') : translate('common.kilometers');
const singularDistanceUnit = unit === CONST.CUSTOM_UNITS.DISTANCE_UNIT_MILES ? translate('common.mile') : translate('common.kilometer');
```


```
function getTransactionDetails(transaction) {
    const report = getReport(transaction.reportID);
    return {
        created: TransactionUtils.getCreated(transaction),
        amount: TransactionUtils.getAmount(transaction, isExpenseReport(report)),
        currency: TransactionUtils.getCurrency(transaction),
        comment: TransactionUtils.getDescription(transaction),
        merchant: TransactionUtils.getMerchant(transaction),  // HERE NEED TO CALL A FUNCTION TO CONVERT UNITS OR DO IT INSIDE getMerchant.
    };
}
```

## What alternative solutions did you explore? (Optional)

**Comment by lcsvcn** [comment] 2023-09-12 18:35
Contributor details
Your Expensify account email: lucas.nicolau.developer@gmail.com
Upwork Profile Link: https://www.upwork.com/freelancers/~01686d9f62c3ed0541

**Comment by ayazalavi** [comment] 2023-09-12 20:43
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
Distance money request has different subtitle for distance/amount text in chat details pages compared with while making a distance money request.

### What is the root cause of that problem?
Root cause of the problem is API syncing. While making a CreateDistanceRequest API call, code just sends transaction ID and remaining calculations are done at serverside. So basically format shown while making a new distance money request is client side calculation ONLY and when server sends back response, Onyx gets updated with server response below:

<img width="1440" alt="Screenshot 2023-09-13 at 1 11 34 AM" src="https://github.com/Expensify/App/assets/767439/27f2658d-317e-4670-b2d9-59dd4402e733">

So Basically this issue just happening in online mode. 
### What changes do you think we should make in order to solve the problem?
In ReportsPreview and MoneyRequestPreview we need to identify which chats are Money Requests chats and re-calculate subtitle instead of printing what server sent us. 

In ReportsPreview we need to update following section:

https://github.com/Expensify/App/blob/3fe7ab1c7d860f40eeb9a52b911f8d7bc4781dd5/src/components/ReportActionItem/ReportPreview.js#L128-L133

with 
1. Check if request is distance money request:     
        
`const isDistanceRequest = hasOnlyOneReceiptRequest && transactionsWithReceipts[0] && TransactionUtils.isDistanceRequest(transactionsWithReceipts[0]);`

2. Get the distance in meters:

`    const distanceInMeters = hasOnlyOneReceiptRequest && lodashGet(transactionsWithReceipts[0], 'routes.route0.distance', undefined);
`
3.  Get new subtitle
```
 const getUpdatedTransactionSubtitle= (distanceInMeters) => {        
        const { currency, rate } = props.mileageRate;
        return DistanceRequestUtils.getDistanceMerchant(distanceInMeters, CONST.CUSTOM_UNITS.DISTANCE_UNIT_MILES, rate, currency, props.translate)
    }
```
5. Update previewSubtitle to:
```

 const previewSubtitle = hasOnlyOneReceiptRequest
        ? (isDistanceRequest && distanceInMeters ? getUpdatedTransactionSubtitle(distanceInMeters) : TransactionUtils.getMerchant(transactionsWithReceipts[0]))
        : props.translate('iou.requestCount', {
              count: numberOfRequests,
              scanningReceipts: numberOfScanningReceipts,
        });
```

This will render it back in client side format.

In MoneyRequestPreview we need to update in similar fashion here:
https://github.com/Expensify/App/blob/3fe7ab1c7d860f40eeb9a52b911f8d7bc4781dd5/src/components/ReportActionItem/MoneyRequestPreview.js#L161
update requestMerchant using **`getUpdatedTransactionSubtitle`**  method in step 4 above.

Since **`getUpdatedTransactionSubtitle`** is generic we can add it in **`DistanceRequestUtils`** class and use it in both MoneyRequestPreview and the ReportsPreview. 

We also need to have mileageRates using:
**`DistanceRequestUtils.getDefaultMileageRate(ReportUtils.getPolicy(props.chatReport.policyID));`**
in **`getUpdatedTransactionSubtitle`** or just pass through props


### What alternative solutions did you explore? (Optional)
To synchronize with the backend, we can use the same format returned by the backend on the client side. Otherwise, we would need to recalculate subtitles for distance requests ONLY as describe above.

**Comment by flaviadefaria** [comment] 2023-09-14 18:42
@adelekennedy Looks like I was incorrectly double assigned here by the external label. We are discussing fixing this [here](https://expensify.slack.com/archives/C01SKUP7QR0/p1694513579526909). In the meantime, going to un-assign as this doesn't need two BZ assignees.

**Comment by ayazalavi** [comment] 2023-09-16 13:43
@mananjadhav any update regarding my proposal?

**Comment by mananjadhav** [comment] 2023-09-17 19:45
I think this should be fixed from the backend?

🎀 👀 🎀 C+ reviewed.

**Comment by ayazalavi** [comment] 2023-09-17 19:58
@mananjadhav yes you are right but if backend is getting overloaded then we can deploy this fix in the front end. What do you think?

**Comment by lcsvcn** [comment] 2023-09-18 12:28
@mananjadhav yes, it should be fixed in the backend. 

As per my proposal, I still think we are missing verification to validate the back-end consistency, so we should implement a way to log a warning for developers that if we spot that the format is coming in a wrong format, not exclusive for this issue, but for easy identification for further issues.

I also suggested a quick fix for now, if back-end fix would take a lot of time to complete.

What do you think of my proposal?

**Comment by adelekennedy** [comment] 2023-09-21 10:44
@mananjadhav @marcochavezf pending response on the above

**Comment by mananjadhav** [comment] 2023-09-21 11:21
I still feel the ideal fix will be on the backend.

**Comment by adelekennedy** [comment] 2023-09-25 07:36
@marcochavezf what are your thoughts should we move this internal?

**Comment by marcochavezf** [comment] 2023-09-28 03:19
Yup, moving it to internal. I have a few other high priorities on my plate I will check this out soon

**Comment by marcochavezf** [comment] 2023-09-29 05:24
No update

**Comment by adelekennedy** [comment] 2023-10-02 09:44
no updated

**Comment by marcochavezf** [comment] 2023-10-05 19:07
I'm swamped with other high-priority items, I will come back to this one after I finish the other pending items

**Comment by marcochavezf** [comment] 2023-10-09 14:41
No update, but I am prioritizing this one for this week

**Comment by marcochavezf** [comment] 2023-10-10 13:34
I will work on this one today

**Comment by marcochavezf** [comment] 2023-10-12 19:39
No update

**Comment by marcochavezf** [comment] 2023-10-13 18:30
No update, focused on TU launch

**Comment by adelekennedy** [comment] 2023-10-16 19:25
Small issue - deprioritizing

**Comment by adelekennedy** [comment] 2023-10-25 15:45
@marcochavezf should we make this monthly or will it just get lost?

**Comment by marcochavezf** [comment] 2023-11-06 19:13
Yup, monthly will be fine. It's a minor bug and I'm still wrapping up some other higher-priority items

**Comment by adelekennedy** [comment] 2023-12-11 19:03
@marcochavezf we're at the month mark here - is this still something you can get to or is this small enough we should close at this point?

**Comment by marcochavezf** [comment] 2023-12-11 19:31
I would like to check it out eventually, but given the critical priority of wave issues, I will come back to this one after wrapping up my pending tasks.

**Comment by adelekennedy** [comment] 2024-01-12 18:54
@marcochavezf with waves a little slower right now can this be worked on? Otherwise it's a small enough bug I wonder if we should close?

**Comment by marcochavezf** [comment] 2024-01-12 19:32
Yeah, it would be better to close it. I don't think the ROI is worth the effort to investigate and fix it given our priorities. We can re-open later if we think it's important or have more capacity.

**Closed by marcochavezf** 2024-01-12 19:32 UTC
Labels: Engineering, Monthly, Internal, Overdue, Bug
