### ISSUE TITLE
[LOW] [Splits] [$500] IOU - After request deletion, no. of request is not updated in receiver end

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#36084] opened 2024-02-07 21:36 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.38
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**  https://expensify.testrail.io/index.php?/tests/view/4289407https://expensify.testrail.io/index.php?/tests/view/4289407
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** Applause - Internal Team
**Slack conversation:**

## Action Performed:
1. Launch app
2. Tap on a 1:1 report with user B
3. In other device, login as user B
4. Open 1:1 report with user A
3. As user A, - Tap plus icon and request money ( create 3 money request)
4. As user B- Note 3 money request received from user A
5. As user A- After requesting money thrice, tap IOU to open IOU report page
6. In IOU report page, delete the last request created
7. As user B, in 1:1 page, note amount updated but number of request is not updated
8. Tap IOU and note in IOU report page, only 2 request displayed
9. Again navigate to 1:1 page and note 3 request shown

## Expected Result:
After deleting request, amount is updated similarly number of request must also be updated in receiver end

## Actual Result:
After deleting request, amount is updated but number of request is not updated in receiver end. For 2 request, it is shown 3 request in IOU preview

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [x] Android: mWeb Chrome
- [x] iOS: Native
- [x] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details> 

![image (18)](https://github.com/Expensify/App/assets/78819774/39216f77-899e-48c4-8c0b-702a2689e86b)

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01cb9fb0c0a6256318</li>
        <li>Upwork Job ID: 1755344895676690432</li>
        <li>Last Price Increase: 2024-02-21</li>
    </ul>
</details>

**Comment by lanitochka17** [comment] 2024-02-07 21:38
We think that this bug might be related to #vip-bills
CC @davidcardoza

**Comment by FitseTLT** [comment] 2024-02-07 21:53
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
After request deletion, no. of request is not updated in receiver end

### What is the root cause of that problem?
Memoization here
https://github.com/Expensify/App/blob/f6ba751301d6a6f4e5faa092e615d49fb02d2746/src/pages/home/report/ReportActionItem.js#L856-L857
### What changes do you think we should make in order to solve the problem?

Add
```
            prevProps.action.childMoneyRequestCount === nextProps.action.childMoneyRequestCount &&

```
### What alternative solutions did you explore? (Optional)

**Comment by davidcardoza** [comment] 2024-02-07 22:59
>We think that this bug might be related to #vip-bills

Why?

**Comment by CortneyOfstad** [comment] 2024-02-12 15:13
@lanitochka17 can you clarify further on why you think this may be related to VIP-Bills?

**Comment by CortneyOfstad** [comment] 2024-02-14 15:46
@lanitochka17 bump ^^^ thanks!

**Comment by CortneyOfstad** [comment] 2024-02-16 20:16
@lanitochka17 can you clarify as to why you think this would fit under VIP-Bills/Split?

**Comment by CortneyOfstad** [comment] 2024-02-21 16:02
@lanitochka17 bumping [this](https://github.com/Expensify/App/issues/36084#issuecomment-1949271008) comment. Can you please provide additional context by EOD? Thanks!

**Comment by CortneyOfstad** [comment] 2024-02-22 19:54
Bump @lanitochka17

**Comment by CortneyOfstad** [comment] 2024-02-26 14:07
Going to keep moving this forward, despite the lack of response, as we cannot sit on this any longer. 

This appears to fall into #Vip-Split. Posted it in the room [here](https://expensify.enterprise.slack.com/archives/C05RECHFBEW/p1708956442200749).

**Comment by CortneyOfstad** [comment] 2024-02-26 14:08
@fedirjh it looks like we have a proposal from @FitseTLT [here](https://github.com/Expensify/App/issues/36084#issuecomment-1933000136) (sorry for the delay in response). If you can provide any feedback by EOD today that will be great.

**Comment by FitseTLT** [comment] 2024-02-26 21:00
@fedirjh Yep this line was the one that confused me I think it can removed 
https://github.com/Expensify/App/blob/88a3ffe9440548d04c32bec2c889b8bb063a29b3/src/pages/home/report/ReportActionItem.js#L904

**Comment by CortneyOfstad** [comment] 2024-02-28 15:43
@fedirjh based on the comment [here](https://github.com/Expensify/App/issues/36084#issuecomment-1965259475), are we good to move forward with @FitseTLT's proposal?

**Comment by CortneyOfstad** [comment] 2024-02-28 17:38
Thank you for the clarification @fedirjh 👍

**Comment by CortneyOfstad** [comment] 2024-02-29 20:04
Hi @dylanexpensify! I am heading OoO and will be back March 11th, so reassigned to have someone keep this moving until I am back. At this stage, we're waiting for internal engineering to pick this up as it is a BE issue. Thanks!

**Comment by dylanexpensify** [comment] 2024-03-06 10:39
Apologies, I've been OOO sick, but am reviewing today!

**Comment by CortneyOfstad** [comment] 2024-03-11 17:30
Going to see if Callstack is willing to take this on 👍

**Comment by CortneyOfstad** [comment] 2024-03-11 17:33
Reach out to CS [here](https://expensify.enterprise.slack.com/archives/C03UK30EA1Z/p1710178405721889)

**Comment by dylanexpensify** [comment] 2024-03-13 10:09
nice!

**Comment by pac-guerreiro** [comment] 2024-03-13 12:22
I'm Pedro Guerreiro from Callstack - expert contributor group. I’d like to work on this task!

**Comment by pac-guerreiro** [comment] 2024-03-14 17:34
After some code review, I think the problem lies on the data that the backend sends after deleting a money request.

When user A deletes a money request, we save optimistic data locally that modifies the report action with `actionName === "REPORTPREVIEW"` to show the correct request count like this:

![Screenshot 2024-03-14 at 17 23 03](https://github.com/Expensify/App/assets/48553277/e89c3d80-0531-42bf-8490-19af16c170fc)

![Screenshot 2024-03-14 at 17 23 39](https://github.com/Expensify/App/assets/48553277/33e06283-cb6c-412f-8e79-211e5fd58434)

But the backend doesn't return this data on it's response to both users, as you can see here:

User A - which deleted the money request
![Screenshot 2024-03-14 at 17 26 53](https://github.com/Expensify/App/assets/48553277/7d19326d-7045-43dd-b021-4975e1fda511)

User B - which received the new updates through pusher
![Screenshot 2024-03-14 at 17 30 53](https://github.com/Expensify/App/assets/48553277/0d110284-3041-4b16-9ed0-a2fde0f81f60)

Only when the user B refreshes the page, he fetches the complete updated data:

![Screenshot 2024-03-14 at 17 29 11](https://github.com/Expensify/App/assets/48553277/4322be45-a816-4388-92b9-0ae771e7e230)

**Comment by CortneyOfstad** [comment] 2024-03-15 14:57
@pac-guerreiro thank you so much for confirming this! Going to keep this rolling and see if someone from engineering can take a deeper look.

**Comment by CortneyOfstad** [comment] 2024-03-18 14:54
still waiting on someone internally to pick this up. The priority is low, so going to adjust the tag to `weekly` 👍

**Comment by CortneyOfstad** [comment] 2024-04-01 14:03
Not overdue — still waiting for engineering to pick this up internally 👍

**Comment by CortneyOfstad** [comment] 2024-04-10 16:40
No update as we're still waiting for an engineer to pick this up

**Comment by CortneyOfstad** [comment] 2024-04-22 14:05
@lanitochka17 can we confirm if this is still reproducible?

**Comment by lanitochka17** [comment] 2024-04-24 13:06
@CortneyOfstad Issue is still reproducible 

https://github.com/Expensify/App/assets/78819774/7e1cb019-eaa4-4c32-8d27-eee1f14521c8

**Comment by CortneyOfstad** [comment] 2024-04-24 14:12
Okay, thank you @lanitochka17! Going to continue to keep this open to see if an engineer will pick it up internally 👍

**Comment by CortneyOfstad** [comment] 2024-05-01 15:31
Still waiting on this to be picked up 👍

**Comment by CortneyOfstad** [comment] 2024-05-10 14:38
Still a hot pick, but should see an uptick in these being picked up after the merge freeze for the May 1st release is done

**Comment by CortneyOfstad** [comment] 2024-05-15 17:38
Same as last week — still a hot pick waiting to be picked up

**Comment by CortneyOfstad** [comment] 2024-05-22 13:42
Still a hot-pick. With the 🔥 the past few weeks hopefully things will improve 🤞

**Comment by CortneyOfstad** [comment] 2024-06-03 13:33
Still no takers

**Comment by mvtglobally** [comment] 2024-07-03 14:34
Issue not reproducible during KI retests. (First week)

**Closed** 2024-07-09 14:35 UTC
Labels: Engineering, Monthly, Internal, Overdue, Bug, Hot Pick, retest-weekly
