### ISSUE TITLE
[$500] Workspace - User account closed is not removed in real-time in Workspace members page

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#26593] opened 2023-09-02 23:50 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Launch app
2. Tap profile
3. Tap workspaces
4. Select a Workspace
5. Tap members
6. Enter a new non existing user
7. Tap next
8. Tap invite
9. Open email link and validate the account(in other device or environment)
10. Open validated account(in other device or environment)
11. Tap profile
12. Tap security
13. Tap Close account
14. Enter email and confirm close account.
15. Note admin Workspace members page ie. 8th step(app)
16. Tap back button
17. Revisit Workspace members page

## Expected Result:
When invited user closes the account, user must not be shown in admin Workspace members page

## Actual Result:
When invited user closes the account, in real- time, user is not removed from admin Workspace members page. User has to navigate back from members page and revisit the page again to note the user of closed account to be removed from members list

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [ ] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 1.3.62-1

**Reproducible in staging?:** Yes

**Reproducible in production?:** yes

**If this was caught during regression testing, add the test name, ID and link from TestRail:**

**Email or phone of affected tester (no customers):**

**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/78819774/6f0c3188-ac42-4529-8138-e8bcdce8546f

**Expensify/Expensify Issue URL:**

**Issue reported by:** Applause - Internal Team

**Slack conversation:**

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01da2cae35a2022fcb</li>
        <li>Upwork Job ID: 1699326238020980736</li>
        <li>Last Price Increase: 2023-11-22</li>
    </ul>
</details>

**Comment by greg-schroeder** [comment] 2023-09-06 07:57
Applied External

**Comment by ayazalavi** [comment] 2023-09-08 01:30
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
Members list in workspace members page is not updated real time.

### What is the root cause of that problem?
As soon as the invited user closes their account, we have no way of subscribing to fetch the fresh members' list from the server.

### What changes do you think we should make in order to solve the problem?
Poll server for [getWorkspaceMembers](https://github.com/Expensify/App/blob/b119f9ab54e7cc7272702e270693896b352b61e0/src/pages/workspace/WorkspaceMembersPage.js#L82) method in [useeffect here](https://github.com/Expensify/App/blob/b119f9ab54e7cc7272702e270693896b352b61e0/src/pages/workspace/WorkspaceMembersPage.js#L102)

https://www.dropbox.com/scl/fi/z8tfxyydwjse24i92vqps/Screen-Recording-2023-09-08-at-6.22.58-AM.mov?rlkey=57lk0qgeoiodi4d4tqwdyt3g7&dl=0

### What alternative solutions did you explore? (Optional)
Use pusher and apply pub/sub model for members listing. But it s quite lengthy and requires lots of changes in code.

**Comment by ayazalavi** [comment] 2023-09-08 01:54
@sobitneupane what do you think?

**Comment by greg-schroeder** [comment] 2023-09-11 14:13
bump @sobitneupane

**Comment by ayazalavi** [comment] 2023-09-12 10:06
@sobitneupane any update?

**Comment by sobitneupane** [comment] 2023-09-12 15:14
will review the proposal shortly.

**Comment by sobitneupane** [comment] 2023-09-13 07:52
Thanks for the proposal @ayazalavi.

Can you please add more details to your proposal? Why is SetInterval required here? I don't think it's good idea to fetch members repeatedly.

**Comment by ayazalavi** [comment] 2023-09-13 18:47
### Proposal
[Updated](https://github.com/Expensify/App/issues/26593#issuecomment-1710954981)

**Comment by ayazalavi** [comment] 2023-09-15 19:17
### Proposal
[Updated](https://github.com/Expensify/App/issues/26593#issuecomment-1710954981)

**Comment by ayazalavi** [comment] 2023-09-16 13:53
Updating my proposal.

**Comment by sobitneupane** [comment] 2023-09-18 08:24
Thanks for the update @ayazalavi 

> Currently only admins are allowed to remove member but in order to notify admin that member does not exist anymore we need to allow users to remove themselves from the workspace.

I am not sure if I understand your proposal clearly. But we are definitely not willing to change any functionality. 

> Second way is to poll getWorkspaceMembers method in members list page for fetching fresh workspace members after every 4-5 seconds.

We cannot have this overhead. It is not feasible solution.

**Comment by ayazalavi** [comment] 2023-09-18 11:38
> Thanks for the update @ayazalavi
> 
> > Currently only admins are allowed to remove member but in order to notify admin that member does not exist anymore we need to allow users to remove themselves from the workspace.
> 
> I am not sure if I understand your proposal clearly. But we are definitely not willing to change any functionality.
> 
> > Second way is to poll getWorkspaceMembers method in members list page for fetching fresh workspace members after every 4-5 seconds.
> 
> We cannot have this overhead. It is not feasible solution.

I understand what you mean. Let me write down new proposal.

**Comment by sobitneupane** [comment] 2023-09-22 05:50
Waiting Proposal

**Comment by ayazalavi** [comment] 2023-09-23 15:12
@sobitneupane can you let me know how user can update his information on all relevant users side? Is there any way to pass custom data as well?

**Comment by ayazalavi** [comment] 2023-09-25 12:57
@greg-schroeder @sobitneupane look at my proposal

**Comment by sobitneupane** [comment] 2023-09-26 10:11
@ayazalavi What change are you suggesting and where will you make the change? Is `assigneeAccountID` relevant in this case? Please try to include more descriptions and details in your proposal.

**Comment by ayazalavi** [comment] 2023-09-26 16:04
Sure

**Comment by greg-schroeder** [comment] 2023-09-29 06:06
@ayazalavi is your updated proposal ready for review?

**Comment by ayazalavi** [comment] 2023-09-29 07:14
There are lots of issues in workspace members page. Trying to figure out the solution.

**Comment by ayazalavi** [comment] 2023-09-29 09:45
Can anyone check member is not getting removed from the list after he closes account?

**Comment by greg-schroeder** [comment] 2023-10-02 15:06
@ayazalavi can you clarify the backend problem you mentioned?

**Comment by greg-schroeder** [comment] 2023-10-04 16:06
@sobitneupane can you confirm backend issue?

**Comment by ayazalavi** [comment] 2023-10-06 01:27
Can we use USER_IS_LEAVING_ROOM pusher event to subscribe to workspace report changes?

**Comment by sobitneupane** [comment] 2023-10-09 11:42
Sorry for the delay.

I will try to review before EOD tomorrow (NPT).

**Comment by sobitneupane** [comment] 2023-10-10 09:04
> When invited user closes the account, in real- time, user is not removed from admin Workspace members page. User has to navigate back from members page and revisit the page again to note the user of closed account to be removed from members list

Nope. It's not a backend issue. As mentioned in actual result, when user revisits the page again, the closed account is removed from the members list.

**Comment by greg-schroeder** [comment] 2023-10-16 14:46
Got it. I guess we're waiting then!

**Comment by greg-schroeder** [comment] 2023-10-19 00:40
Pending proposals

**Comment by greg-schroeder** [comment] 2023-10-23 10:20
Same as above

**Comment by greg-schroeder** [comment] 2023-10-26 00:03
¯\_(ツ)_/¯ nothing to report here

**Comment by sobitneupane** [comment] 2023-11-01 04:00
Waiting for proposals.

**Comment by greg-schroeder** [comment] 2023-11-09 11:25
Awaiting proposals

**Comment by greg-schroeder** [comment] 2023-11-13 09:31
Same as above

**Comment by greg-schroeder** [comment] 2023-11-16 00:06
Posting in Callstack slack

**Comment by Piotrfj** [comment] 2023-11-17 02:19
Hey, I'm Piotr from Callstack - expert contributor group - I would like to help resolve this issue

**Comment by sobitneupane** [comment] 2023-11-20 12:12
@Piotrfj Could you kindly provide details on your approach to resolving the issue?

**Comment by greg-schroeder** [comment] 2023-11-26 19:59
Yes, @Piotrfj do you mind giving a breakdown of your approach here? Thanks!

**Comment by greg-schroeder** [comment] 2023-11-27 18:34
Okay then, guess we're closing

**Closed by greg-schroeder** 2023-11-27 18:34 UTC
Labels: External, Engineering, Daily, Bug
