### ISSUE TITLE
[HOLD for payment 2022-10-18] [$250] mWeb- request a setup call option not visible in landscape mode - Reported by @gadhiyamanan

### ISSUE THREAD

**Issue by mvtglobally** [Expensify/App#11315] opened 2022-09-27 04:02 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Rotate device to landscape mode
2. Go to any workspace
3. Click to on :question: icon

## Expected Result:
User should be able to scroll

## Actual Result:
Not able to scroll for click request a setup call option

## Workaround:
unknown 

## Platform:

Where is this issue occurring?

- Mobile Web

**Version Number:** 1.2.4-0
**Reproducible in staging?:** Y 
**Reproducible in production?:** Y 
**Email or phone of affected tester (no customers):** 
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation 

![Screenshot_20220909-215053_Chrome](https://user-images.githubusercontent.com/43995119/192429113-fba454e4-01d3-4e78-ae7e-ae9c9aef3346.jpg)

**Expensify/Expensify Issue URL:** 
**Issue reported by:** @gadhiyamanan
**Slack conversation:** https://expensify.slack.com/archives/C01GTK53T8Q/p1662740740529029

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by akshayasalvi** [comment] 2022-09-27 04:32
**Proposal**

This is a small fix because `GetAssistancePage` has a `Section` block and we just need to wrap with `ScrollView` over here

https://github.com/Expensify/App/blob/90a226b20f23eeb8a669664bf4474781125e196a/src/pages/GetAssistancePage.js#L29-L40

```
   <ScrollView>
        <Section
            ...>
   </ScrollView>
```


https://user-images.githubusercontent.com/57435789/192432612-bb97f7e0-f68e-4b2c-a473-d9dc28c20c77.mov

**Comment by sakluger** [comment] 2022-09-27 19:45
This is a real, unique issue with clear documentation. Assigning engineering to review the proposed solution.

**Comment by srikarparsi** [comment] 2022-09-27 20:41
the proposal looks good to me, marking the issue external so we can create the upwork job.

**Comment by jliexpensify** [comment] 2022-09-28 01:35
Posted:

Internal - https://www.upwork.com/ab/applicants/1574935136116920320/job-details
External - https://www.upwork.com/jobs/~01209a66fcedf3009b

Invited @rushatgabhane and Manan.

**Comment by jliexpensify** [comment] 2022-09-28 01:36
@srikarparsi - just confirming: good to hire @akshayasalvi ?

@akshayasalvi - can you edit your GH profile to include your full name, and link me your Upworks profile? Cheers!

**Comment by akshayasalvi** [comment] 2022-09-28 04:17
@jliexpensify Does this help https://www.upwork.com/freelancers/~0103406434c3fea888

**Comment by gadhiyamanan** [comment] 2022-09-28 04:26
@jliexpensify not getting any invite

**Comment by jliexpensify** [comment] 2022-09-28 04:29
You're invited @gadhiyamanan - try clicking here:  https://www.upwork.com/jobs/~01209a66fcedf3009b

![image](https://user-images.githubusercontent.com/30815269/192687708-62d8ae9c-ea64-4de0-b477-92921026b389.png)

**Comment by gadhiyamanan** [comment] 2022-09-28 04:36
@jliexpensify should i submit proposal?
![Screenshot 2022-09-28 at 10 03 11 AM](https://user-images.githubusercontent.com/54790231/192688176-c7fc6c9d-7355-4bde-91d0-3f12a4fbe46e.png)

**Comment by jliexpensify** [comment] 2022-09-28 04:38
@gadhiyamanan you'll be paid $250 for reporting the bug, so no need to submit a proper proposal. You could just write something like "I reported the bug and will be compensated" or something - I'll be the one paying everything once the PR is deployed.

**Comment by gadhiyamanan** [comment] 2022-09-28 04:46
@jliexpensify applied :)

**Comment by sobitneupane** [comment] 2022-09-28 18:17
I am taking over this issue as C+ since https://github.com/Expensify/App/issues/11339 issue will also be fixed by the PR raised here.
cc: @rushatgabhane @jliexpensify

**Comment by jliexpensify** [comment] 2022-09-28 21:36
Assigning to @sobitneupane due to a regression. Unassigning Rushat, as Sobit is taking over as C+

**Comment by sobitneupane** [comment] 2022-09-29 02:22
I am taking over this issue as C+ since https://github.com/Expensify/App/issues/11339 issue will also be fixed by the PR raised here.

This [proposal](https://github.com/Expensify/App/issues/11315#issuecomment-1258956305) from @akshayasalvi will solve this issue as well as https://github.com/Expensify/App/issues/11339 issue. 

@srikarparsi proposal from @akshayasalvi  looks good to me
🎀👀🎀  C+ reviewed

**Comment by jliexpensify** [comment] 2022-09-29 05:12
Invited @sobitneupane , cheers!

**Comment by akshayasalvi** [comment] 2022-09-30 04:05
@sobitneupane @srikarparsi Is there anything else required from my end?

**Comment by sobitneupane** [comment] 2022-09-30 05:01
> @sobitneupane @srikarparsi Is there anything else required from my end?

Once @srikarparsi approves your proposal, you can create PR.

**Comment by akshayasalvi** [comment] 2022-09-30 05:57
Thank you for the comment @sobitneupane

**Comment by jliexpensify** [comment] 2022-10-04 02:35
@srikarparsi bump - although i think he may have weighed in earlier?

**Comment by akshayasalvi** [comment] 2022-10-04 03:50
Yeah he kind off approved the proposal here in this https://github.com/Expensify/App/issues/11315#issuecomment-1260025543

@jliexpensify does this still wait or should I create the PR?

**Comment by jliexpensify** [comment] 2022-10-04 03:59
@akshayasalvi I'd say go ahead and create the PR: it looks like Srikar pre-approved it. I'll hire you in Upworks.

cc @sobitneupane

**Comment by akshayasalvi** [comment] 2022-10-04 05:51
@jliexpensify @srikarparsi @sobitneupane PR raised.

**Comment by srikarparsi** [comment] 2022-10-19 18:44
yup, we can pay and close the job. It did end up getting deployed to ios and android.

**Comment by jliexpensify** [comment] 2022-10-19 21:32
Everyone is paid and job removed from Upworks. Thanks!

**Closed by jliexpensify** 2022-10-19 21:32 UTC
Labels: External, Engineering, Daily, Improvement, Awaiting Payment, Bug
