### ISSUE TITLE
[WAITING ON SITU TO FINISH CHECKLIST] [LOW] [Splits] [$500] IOU - Tapping split button & selecting 2nd contact are not highlighted like 1st contact

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#35665] opened 2024-02-02 14:00 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.35.0
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:** https://expensify.testrail.io/index.php?/tests/view/4263802
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** Applause - Internal Team
**Slack conversation:**

## Action Performed:
1. Go to https://staging.new.expensify.com/
2. Tap fab --- request money --- Scan
3. Tap camera button and upload a picture
4. Note first contact is not highlighted in Resents
5. Now tap split and select the first contact from Resents
6. Note, the contact is shown highlighted with green tick mark after selecting it
7. Tap split button next to second contact and select it

## Expected Result:
When user taps split button (no matter first or second selection), the row isn't always highlighted but only green tick is shown

## Actual Result:
When user taps split button and select 2nd contact, only green tick shown, it is not highlighted like first contact after selection.

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [x] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

https://github.com/Expensify/App/assets/93399543/e848edfc-7fdb-4d41-b40b-43c2a2b2ad3b

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~010e869b36a20a1985</li>
        <li>Upwork Job ID: 1753418217201557504</li>
        <li>Last Price Increase: 2024-02-09</li>
<li>Automatic offers: </li>
<ul>
<li>situchan | Contributor | 0</li>
<li>Krishna2323 | Contributor | 0</li>
</ul></li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @situchan</details>

**Comment by kbecciv** [comment] 2024-02-02 14:02
We think that this bug might be related to #wave5-free-submitters
CC @dylanexpensify

**Comment by jliexpensify** [comment] 2024-02-05 01:24
Can repro, going to double-check with Dylan.

**Comment by jliexpensify** [comment] 2024-02-05 01:47
I think this should actually go in #vip-split: https://expensify.slack.com/archives/C05RECHFBEW/p1707097628668729

**Comment by Santhosh-Sellavel** [comment] 2024-02-06 20:36
> I think this is intended and not a bug, when on laptop, if we use keyboard down button then the same focus moves down the list.
cc: @Expensify/design can you confirm whether this issue is bug or not?

**Comment by dannymcclain** [comment] 2024-02-06 21:16
🤔 I do not know. I guess it's not a bug since we keep the first item of a list focused... but why do we keep the first item of a list focused? I think in this situation I would expect none of the list items to have focus. Anyone else?

> I think the bug is that when you select a second person, the first person is still highlighted. I agree that the focus should move down the list, but it should then highlight the 2nd person instead, as it's the most recently selected.

I guess if we definitely want to maintain focus inside the list (which I would still love to hear why we want to do that—could be something very obvious that I'm not understanding) then I would agree with Jason that the most recent person selected should be the one that gets focus.

**Comment by Santhosh-Sellavel** [comment] 2024-02-06 21:33
The behavior same in the other places too, I think this is designed this way, maybe @shawnborton help here as he was part of the selection list refactor 

https://github.com/Expensify/App/assets/85645967/ee9ca338-3418-4a1f-bd66-7a7c33eb8344

**Comment by jliexpensify** [comment] 2024-02-07 01:52
>but why do we keep the first item of a list focused? 

This is exactly the question I asked myself, and why I assumed it was a bug.

Here's my thought:

> The focus should move down the list, but it should then highlight the 2nd person instead, as it's the most recently selected.

**Comment by shawnborton** [comment] 2024-02-07 13:57
Yeah I guess this is technically not a bug but I do tend to agree with this one:

> but why do we keep the first item of a list focused? I think in this situation I would expect none of the list items to have focus. Anyone else?

It seems like maybe we have competing styles for list selection where selected items typically have a different BG color, but your keyboard focus also gets a darker BG color. 

So I wonder if it makes sense to not have the keyboard focus on any of the list items until you explicitly start using the down arrow/tab button to go down from the input? And then we might consider using an outline style for the focus style as opposed to a BG color?

**Comment by jliexpensify** [comment] 2024-02-10 04:36
@shawnborton I think you (and the Design Team) probably have the final say here! What do you recommend the solution should be?

- Focus on each new user? OR
- Don't focus initially and use an outline style for each new user?

**Comment by dannymcclain** [comment] 2024-02-12 14:31
Hmm that result video actually feels pretty good to me. But I think I'm still debating between that solution and not focusing any items in the list at all.

The main reason I'm not sure we should focus the list at all is because you can't really add someone to a split with your keyboard anyways. If you try to, it seems like what ends up happening is you're just advanced to regular manual request confirmation screen with a single participant (the person who you keyboarded to). So I'm not totally sure what value the focus is providing here. Would love to get @Expensify/design thoughts on each of these approaches.

**Comment by jliexpensify** [comment] 2024-02-12 23:15
Nice, ty everyone! @Santhosh-Sellavel - could I get you to review the updated proposals? Thanks!

**Comment by Santhosh-Sellavel** [comment] 2024-02-13 20:16
@Krishna2323  If we are no longer focusing on anything I think we might need some cleanup as well. 
@jliexpensify Unassigning as am planning for OOO, please assign a new C+ here

**Comment by situchan** [comment] 2024-02-13 20:27
I can take over.

----

> When user taps split button and select 2nd contact, it must be highlighted & green tick must be shown, just how it is shown for first contact after selection.

The expected result should be updated like this:

> When user taps split button (no matter first or second selection), the row isn't always highlighted but only green tick is shown

**Comment by jliexpensify** [comment] 2024-02-13 21:12
Assigned @situchan and updated `expected result`

**Comment by situchan** [comment] 2024-02-15 17:55
Not able to reproduce anymore on staging.
Looks like this was fixed in #34196

**Comment by situchan** [comment] 2024-02-15 18:12
@Krishna2323 can you please share video of that "bug" and share with design team if we wanna fix that behavior?

**Comment by shawnborton** [comment] 2024-02-16 14:07
That makes sense to me, in terms of not highlighting anything given that the keyboard controls don't work for split.

**Comment by jliexpensify** [comment] 2024-02-18 20:30
@situchan are you able to review? Thanks!

**Comment by situchan** [comment] 2024-02-21 21:25
@Krishna2323 mind sharing test branch?

**Comment by situchan** [comment] 2024-02-22 22:16
I will provide feedback by tomorrow

**Comment by jliexpensify** [comment] 2024-02-25 23:48
Bumping @situchan for feedback

**Comment by situchan** [comment] 2024-02-26 08:42
So the expected behavior is to clear highlight when any item is selected (by clicking Split button) / deselected (by clicking ✅ button).


@Krishna2323 what about this case?

When deselected the last remaining selected item, keeps highlight

https://github.com/Expensify/App/assets/108292595/d45fb5e2-e3c0-45c1-8fc8-7b4c9dc094e0

**Comment by jliexpensify** [comment] 2024-02-29 02:38
Bump @Krishna2323 do you have an updated proposal? Thanks!

**Comment by jliexpensify** [comment] 2024-03-03 23:18
Bump @situchan for a proposal review! Thanks.

**Comment by jliexpensify** [comment] 2024-03-07 04:24
DM-ed Situ in Slack

**Comment by situchan** [comment] 2024-03-12 21:30
sorry missed this. @Krishna2323 can you please update testing branch which covers that?

**Comment by situchan** [comment] 2024-03-15 20:17
Thanks

**Comment by situchan** [comment] 2024-03-18 21:19
Not overdue

**Comment by jliexpensify** [comment] 2024-03-19 07:44
Bump @situchan - can we push this along? Thanks!

**Comment by trjExpensify** [comment] 2024-03-19 11:30
Sounds good!

**Comment by trjExpensify** [comment] 2024-03-25 11:58
Oh sorry, I missed that we're waiting on @bondydaa for the secondary review of the proposal. Cool!

**Comment by jliexpensify** [comment] 2024-03-31 22:26
Back - thanks @trjExpensify for the assist. I'll unassign you!

**Comment by jliexpensify** [comment] 2024-04-29 03:53
Thanks! Bumping @situchan to accept so I can pay everyone at once + complete checklist.

**Comment by jliexpensify** [comment] 2024-04-30 04:46
Bumped @situchan again

**Comment by jliexpensify** [comment] 2024-05-02 03:34
@situchan seems to be on [leave](https://expensify.slack.com/archives/C02NK2DQWUX/p1714620845754129).

**Comment by jliexpensify** [comment] 2024-05-06 06:00
Was hoping to pay both together but seems like @situchan is still on vacation.

@Krishna2323 apologies for the delay, have paid you.

**Comment by jliexpensify** [comment] 2024-05-20 03:24
Bump @situchan - does the checklist need to be completed?

**Comment by situchan** [comment] 2024-05-20 04:26
Not able to find offending PR since this component was changed so many times.
This was caught during regression testing https://expensify.testrail.io/index.php?/tests/view/4263802 so no new regression test is needed.

**Closed** 2024-05-20 04:27 UTC
Labels: External, Engineering, Weekly, Bug
