### ISSUE TITLE
[HOLD for payment 2024-02-01] [$500] HIGH: Enable threading on all system messages

### ISSUE THREAD

**Issue by quinthar** [Expensify/App#33738] opened 2023-12-29 01:41 UTC
**Problem:**
Our chat-centric design is to allow you to chat on basically anything.  However, right now you can't thread up a response to a system message, for no clear reason.  One specific place this is a limitation is when there is a system message in the #admins room -- such as when someone adds an outsider to a room.  By not allowing threading, we disrupt the most natural place to discuss this with the employee.

**Solution:**
Enable threading on all system messages from a user, exactly as if they had manually posted that same message as a comment.  This means:

* Name the thread based on the parent comment that is being threaded
* Invite the author of the parent comment (in this case, the system message) to the thread _even if they don't have access to the parent room_.  (This can happen because users can cause system messages to posted "from" them to rooms they aren't in).

So far as I know this should be doable entirely on the client side without any back-end work.  However, if you determine that's not true (and if you need some back end help) please just let us know.

**Test:**
Verify:
1. Alice creates a workspace `Alice's Apples`
2. Alice invites Bob to the workspace
3. Bob creates a room `#bagel-lovers` that Alice is *not* in
4. Bob invites Cathy (who is *not* a member of the workspace) to `#bagel-lovers`
    * This cause Bob to post a system message to the #admins room of `Alice's Apples` saying: `Bob invited Cathy to #bagel-lovers`
5. Alice opens a thread on that system message
6. Alice posts "What up Bob, why did you invite Cathy?" in that thread
7. Confirm Bob is invited to that thread and sees Alice's message
<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~0143d329144a3feb35</li>
        <li>Upwork Job ID: 1740548696855482368</li>
        <li>Last Price Increase: 2024-01-05</li>
<li>Automatic offers: </li>
<ul>
<li>aimane-chnaif | Reviewer | 28088772</li>
</ul></li>
    </ul>
</details>

**Comment by quinthar** [comment] 2024-01-02 01:34
Actually reopening -- something seems weird about threads on system messages in the #admins room.  Specifically, do all the original steps, and then check the new step at the end:

1. Alice creates a workspace Alice's Apples
2. Alice invites Bob to the workspace
3. Bob creates a room #bagel-lovers that Alice is not in
4. Bob invites Cathy (who is not a member of the workspace) to #bagel-lovers
    - This cause Bob to post a system message to the #admins room of Alice's Apples saying: Bob invited Cathy to #bagel-lovers
6. Alice opens a thread on that system message
7. Alice posts "What up Bob, why did you invite Cathy?" in that thread
8. Confirm Bob is invited to that thread and sees Alice's message
9. **Mention `@cathy@croissants.com`
    - **What should happen:** Cathy should be added to the thread
    - **What actually happenes:** Cathy is not invited
10. **Click into the room header and go to `Members`
    - **What should happen:** It should be possible to add/remove members
    - **What actually happens:** It shows the member list but without any option to add/remove

It seems like the thread from the #admins room is somehow inheriting the invite restrictions of #admins.  Please remove this restriction and allow members of the thread to add/remove people at will, both via `@mentions` and the Add/Remove button in the Members list.

**Comment by quinthar** [comment] 2024-01-02 02:04
Actually it looks like this restriction is on all threads of system messages: for some reason you can't add people to the thread after created, either by mention or the Members page.

**Comment by quinthar** [comment] 2024-01-02 02:25
Ok, so ya things are really screwed up with threading on system messages.  There are multiple issues, I'll try to list them here.

1) Consider this #expensify-test-room, created by @nathanmetcalf:
![image](https://github.com/Expensify/App/assets/575186/f6884a91-3743-4609-849f-eb3f9b10effc)

2) Note how at the bottom it says `invited @nathan.d.metcalf@gmail.com`:
<img width="256" alt="image" src="https://github.com/Expensify/App/assets/575186/20321b83-bc61-47cf-826e-63db2c4fb1d2">

3) When Nathan clicks into it, he sees this:
![image](https://github.com/Expensify/App/assets/575186/e07f55ca-ec78-4ea2-a9ee-b9eacdfac3f2)

3) There are multiple problems.  First, note how the header (and LHN) just says `invited` -- it should show show `invited @nathan.d.metcalf@gmail.com`, just like the original comment:

<img width="260" alt="image" src="https://github.com/Expensify/App/assets/575186/60003db7-f4df-4700-bfbc-dc1d648636f9">
<img width="280" alt="image" src="https://github.com/Expensify/App/assets/575186/b1f69990-8d12-4327-8378-89bdad568677">

4) But when I click into it, I see this:
<img width="1440" alt="image" src="https://github.com/Expensify/App/assets/575186/0f297121-4a81-4a6c-a16f-9c9bb46a108e">

5) This has all the problems Nathan saw, but more.  Check how the first message in the chat, which shows the parent that is being threaded from, shows *some kind of phantom 6-reply thread* (it should not be showing any replies there):
<img width="355" alt="image" src="https://github.com/Expensify/App/assets/575186/5ece2b71-2fea-4329-95cf-4e55435a3bdd">

6) Needless to say, when I try to click into the phantom replies, it breaks:
<img width="1440" alt="image" src="https://github.com/Expensify/App/assets/575186/aad89879-61f2-48a2-8dae-fa7bf0a1ee49">

7) Finally, it's not letting me invite/remove members from this thread:
<img width="1440" alt="image" src="https://github.com/Expensify/App/assets/575186/0b46a52b-d5b6-45bb-afe7-269a48409c50">


Something seriously screwed up is happening, that is causing:

* The LHN and header says `invited` for *both* of us, rather than `invited @nathan.d.metcalf@gmail.com`
* His parent chat correctly shows `invited @nathan.d.metcalf@gmail.com`, but mine shows `invited @hidden`.  @puneetlath This is likely due to some kind of isKnown issue, can you investigate this?
* My parent chat also shows a bunch of phantom replies equal to the number of comments *I made to **this** thread*.
* I can't add/remove people to this thread from the Members page
* I can't @mention invite anyone to this thread either

Let's get some proposals for cleaning all this up.

**Comment by puneetlath** [comment] 2024-01-04 20:29
>His parent chat correctly shows invited @nathan.d.metcalf@gmail.com, but mine shows invited @hidden. @puneetlath This is likely due to some kind of isKnown issue, can you investigate this?

Agreed, it seems like this is because you don't "know" the user he invited. Though, hmm this is a worksapce room. So you should "know" all other room members. So it's more likely that it's that we aren't returning the personalDetails of the mentioned user when returning the reportAction.

**Comment by sonialiap** [comment] 2024-01-05 11:18
I've posted this issue in [expensify-bugs](https://expensify.slack.com/archives/C049HHMV9SM/p1704453342760419) and in [callstack](https://expensify.slack.com/archives/C03UK30EA1Z/p1704453477733539)

**Comment by narefyev91** [comment] 2024-01-08 12:35
Hi, I'm Nicolay from Callstack - expert contributor group - and I will try to help here.

**Comment by sonialiap** [comment] 2024-01-08 15:29
Thanks Nicolay!

**Comment by sonialiap** [comment] 2024-01-08 15:30
Thanks Nicolay! I'm going to assign you so that we can keep track who's working on this and to keep melvin-bot happy

**Comment by narefyev91** [comment] 2024-01-09 13:29
@quinthar @puneetlath @aimane-chnaif Hey guys!
Just some updates from my side:
Seems we need to have some work with BE team.
1. For this one "The LHN and header says invited for both of us, rather than invited @nathan.d.metcalf@gmail.com" - for this current place we just pick information which coming from API side - you can see on screenshot - that we have a lot of free space between `invited` and `to`. And just the same happened when we will invite 2 persons as well:

<img width="1721" alt="Screenshot 2024-01-08 at 19 53 35" src="https://github.com/Expensify/App/assets/28352309/6697637c-2763-4786-abcd-0237cd3465d1">


<img width="1683" alt="Screenshot 2024-01-08 at 19 44 14" src="https://github.com/Expensify/App/assets/28352309/d04a4037-36bf-4edb-baa1-fe80ae296a26">

2. For the case of @hidden instead of real user name - seems that it's expected - because we show hidden if mentioned user is not logged in inside the system (you can see on the first image - that one user is @hidden and one already has previously logged in the app)
3. For the rest of the issues - seems most of the points were fixed before - i could not reproduce problem with ghost replies - neither in code no in the app. And also i can invite any new member either with @ or inside right panel in settings
<img width="1728" alt="Screenshot 2024-01-09 at 13 30 31" src="https://github.com/Expensify/App/assets/28352309/a3bf8638-95bb-4c7c-aa00-8ca6e834356c">
<img width="1728" alt="Screenshot 2024-01-09 at 13 30 22" src="https://github.com/Expensify/App/assets/28352309/cb2d9594-95f7-47d2-8f98-aa73ab6b66f3">
<img width="1728" alt="Screenshot 2024-01-09 at 15 26 57" src="https://github.com/Expensify/App/assets/28352309/a37dd1a5-48ec-414b-acd4-1c180438d74e">

Let me know if any of those points makes sense!

**Comment by quinthar** [comment] 2024-01-10 22:05
Hi there, thanks for that!  I'm not 100% if you are waiting on answers.  If so, can you please ask the specific questions in a numbered list, and tag who you are asking the question to?  Thanks!

**Comment by quinthar** [comment] 2024-01-10 22:06
Also, can you give an ETA for completion? Can it be done by Monday?  Thanks!

**Comment by narefyev91** [comment] 2024-01-11 11:15
Hey @quinthar ! Yup i think we will be good to go here before Monday for sure.
Just need one clarification from @puneetlath - Is it fine that we will show @hidden because admin does not have any DMs/chats/etc with user?

**Comment by quinthar** [comment] 2024-01-17 01:29
Can you give a new ETA?   Can we get this merged today?

**Comment by narefyev91** [comment] 2024-01-17 08:31
> Can you give a new ETA? Can we get this merged today?

Hey! It's mostly depends when @aimane-chnaif will take a review - PR opened since last friday

**Comment by quinthar** [comment] 2024-01-18 01:59
@aimane-chnaif What's your ETA? Can we finish the review and merge today?

**Comment by quinthar** [comment] 2024-01-19 01:05
Did you complete yesterday? What's the update?

**Comment by quinthar** [comment] 2024-01-22 23:43
Ok, so what's next?  It's sat for 12 hours with no blockers, what is stopping us from merging it?

**Comment by blimpich** [comment] 2024-01-23 01:48
@quinthar after Aimane reviews the PR it passes on to the Contributor Manager Engineer (who is me in this case) for final review. Aimane finished her review in the wee hours of the morning PST time, so it sat there for 12 hours because I didn't  get to it till this morning. [Here is my review](https://github.com/Expensify/App/pull/34362#pullrequestreview-1837096307). I left some comments, so we are now waiting for those to be addressed, and then we can merge.

**Comment by blimpich** [comment] 2024-01-23 18:24
Merged ✅

**Comment by quinthar** [comment] 2024-01-23 22:21
Woohoooo!!!!!

**Comment by sonialiap** [comment] 2024-02-01 14:08
@aimane-chnaif $500 - paid ✔️ please complete the [checklist](https://github.com/Expensify/App/issues/33738#issuecomment-1909665422)

**Closed** 2024-02-06 13:49 UTC
Labels: External, Daily, Overdue, Awaiting Payment, Bug
