### ISSUE TITLE
[$500] Android - BA - Android App crashes when starting Onfido

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#35519] opened 2024-01-31 21:34 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.34-0
**Reproducible in staging?:** y
**Reproducible in production?:** not able to check production
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** Applause- Internal Team
**Slack conversation:**

## Action Performed:
1. Open Android App
2. Login with Expensifail account
3. Create workspace or go to existing one
4. Select 'Bank Account' > Connect with Plaid
5. Select Region Bank and follow the flow for Onfido (Company - Expensify, first name - First, last name - Last)

## Expected Result:
Onfido started after Personal Information page completed

## Actual Result:
Android App crashes when starting Onfido

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [ ] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

https://github.com/Expensify/App/assets/93399543/3671be9a-37c0-40cb-a452-758243fd4ae6

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01dccccca284d16c78</li>
        <li>Upwork Job ID: 1755346472180178944</li>
        <li>Last Price Increase: 2024-02-07</li>
<li>Automatic offers: </li>
<ul>
<li>mkhutornyi | Contributor | 0</li>
</ul></li>
    </ul>
</details>

**Comment by kbecciv** [comment] 2024-01-31 21:35
We think that this bug might be related to #wave6-collect-submitters
CC @greg-schroeder

**Comment by greg-schroeder** [comment] 2024-01-31 21:58
Hmm this might be handled by Callstack or should be - @mountiny can you confirm if this fits in the VBA refactor project or can be merged in?

**Comment by francoisl** [comment] 2024-01-31 22:08
Wondering if it has to do anything with https://github.com/Expensify/App/pull/35440, we merged that yesterday to fix another  crash on Android. Will try to troubleshoot.

**Comment by francoisl** [comment] 2024-01-31 22:31
I can reproduce the crash on the current production version, using the `VERIFYING` flow from https://stackoverflowteams.com/c/expensify/questions/342. Going to remove the blocker label and keep this open so we can look and fix.

cc @mkhutornyi if you have an idea how to fix.

**Comment by mountiny** [comment] 2024-02-01 12:11
@mkhutornyi what is the changelog for the onfido bump?

**Comment by mountiny** [comment] 2024-02-01 13:09
The android compile sdk looks the most dangerous but we are already on 34 https://github.com/Expensify/App/blob/b64b4080247db4e5e8fcd5dea6ada29f005ecaf7/android/build.gradle#L7 so maybe we should be good to upgrade this

@francoisl @hayata-suenaga what do you think?

**Comment by francoisl** [comment] 2024-02-02 00:03
Sounds good to me. The compile SDK version doesn't sound like a concern if we already target a higher version.

**Comment by mountiny** [comment] 2024-02-02 00:42
Sorry my comment meant to say: we should be good to upgrade `@onfido/react-native-sdk` since the compile sdk does not have to be bumped.

@hayata-suenaga would you like to make this external and assign @mkhutornyi if you happy with their proposal?

**Comment by mountiny** [comment] 2024-02-15 16:27
Thanks, put them all on hold. @mkhutornyi do you want to bringthe build issues to Slack? maybe we could get someone to help you

**Comment by hayata-suenaga** [comment] 2024-02-19 16:39
@mkhutornyi as Vit mentioned, I think the `expensify-opens-source` channel is the best place to ask help with [this type of issue](https://github.com/Expensify/App/issues/35519#issuecomment-1952846940)

I also rely on that channel for issues I can't handle myself 👍

**Comment by hayata-suenaga** [comment] 2024-02-19 17:45
[building...](https://github.com/Expensify/App/actions/runs/7963445729)

**Comment by hayata-suenaga** [comment] 2024-02-19 17:51
ahhhh this is the issue! not PR 😭

**Comment by hayata-suenaga** [comment] 2024-02-19 17:52
[building for real](https://github.com/Expensify/App/actions/runs/7963504965) 😭

**Comment by hayata-suenaga** [comment] 2024-03-13 19:49
The PR was [deployed to production two weeks ago](https://github.com/Expensify/App/pull/36783#issuecomment-1970129357).

Melvin forgot to remove the `reviewing` label so we missed this.

C+ payment for @allroundexperts and contributor payment for @mkhutornyi

**Comment by lschurr** [comment] 2024-03-13 19:56
Ah, got it!

@allroundexperts you're paid via newdot correct?

**Comment by lschurr** [comment] 2024-03-15 20:42
Payment summary:

- Contributor @mkhutornyi $500 (paid via Upwork)
- Contributor+ @allroundexperts (to be requested in newdot)

**Closed by lschurr** 2024-03-15 20:42 UTC
Labels: External, Engineering, Daily, Bug

**Comment by JmillsExpensify** [comment] 2024-04-01 18:13
$500 approved for @allroundexperts
