### ISSUE TITLE
[HOLD for payment 2023-07-20] [$1000] Search- Error message for invalid phone number format displayed if account id used

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#20952] opened 2023-06-16 23:27 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Open the test website https://staging.new.expensify.com/
2. Log in
3. Search by accountID in search sidebar results in the user being shown

## Expected Result:
User displayed without any error message

## Actual Result:
Please enter a valid phone number..... error message displayed with search result as we

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [x] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 1.3.29.0

**Reproducible in staging?:** Yes

**Reproducible in production?:** Yes

**If this was caught during regression testing, add the test name, ID and link from TestRail:**

**Email or phone of affected tester (no customers):**

**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Notes/Photos/Videos:** Any additional supporting documentation

![Bug6096149_20508_Desktop (1)](https://github.com/Expensify/App/assets/78819774/9da5b4d8-6498-4992-bed8-675f358a6fbb)

**Expensify/Expensify Issue URL:**

**Issue reported by:** Applause - Internal Team

**Slack conversation:**

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~018a635f2969cab81b</li>
        <li>Upwork Job ID: 1670866711485976576</li>
        <li>Last Price Increase: 2023-07-03</li>
    </ul>
</details>

**Comment by tjferriss** [comment] 2023-06-19 18:50
I'm able to reproduce this one.

<img width="392" alt="Screenshot 2023-06-19 at 11 50 05" src="https://github.com/Expensify/App/assets/8292562/171d1ff6-93c7-4dc3-9a12-6cce80be9649">

**Comment by flaviadefaria** [comment] 2023-06-19 19:21
@tjferriss should I have been assigned to this issue? I see that you were assigned when the bug label was added, but let me know if I'm missing something!

**Comment by tjferriss** [comment] 2023-06-19 19:46
@flaviadefaria no, I'm not sure what happened there.

**Comment by flaviadefaria** [comment] 2023-06-19 22:19
It might be that you applied the label while OoO, which would have caused this.

**Comment by tjferriss** [comment] 2023-06-22 05:10
@aimane-chnaif what do you think of @hungvu193 proposal?

**Comment by tjferriss** [comment] 2023-06-27 19:36
@aimane-chnaif same question as above. Can we review the latest proposal?

**Comment by Beamanator** [comment] 2023-07-03 13:59
@aimane-chnaif oohhhhhh that's interesting, I don't think this was "intended" as a "new feature" but could be useful maybe... I feel like we should bring this to slack to get an idea if this is a desired or not

cc @puneetlath do you know if we "want" to be able to search for users by accountID in the chat switcher? What about report participants / owners / whatever? I feel like we don't want to, but I don't know if this was ever formally discussed 😅

**Comment by puneetlath** [comment] 2023-07-03 23:04
>cc @puneetlath do you know if we "want" to be able to search for users by accountID in the chat switcher? What about report participants / owners / whatever? I feel like we don't want to, but I don't know if this was ever formally discussed 😅

Hm, yeah I agree. I don't _think_ we intended this. I'm not aware of it and I don't think we have a good reason to allow it right now.

**Comment by marcaaron** [comment] 2023-07-06 21:46
@aimane-chnaif Thanks for reviewing here.

>Search- Error message for invalid phone number format displayed if account id used

What does this mean? `accountID` used for what? 

@hoangzinh For reference purposes, can you update the Problem of your proposal so that it more clearly states the problem we are solving?

Can you also update your proposal so that the solution you are proposing is the alternative one that @aimane-chnaif has advised us to move forward with?

Thanks everyone!

**Comment by tjferriss** [comment] 2023-07-12 06:03
It looks like we're waiting for the PR to hit production at this point.

**Comment by tjferriss** [comment] 2023-07-14 18:49
@hoangzinh @aimane-chnaif are both hired in Upworks and have earned the speed bonus.

@aimane-chnaif can you get started on the checklist?

**Comment by tjferriss** [comment] 2023-07-21 03:13
Payments have been sent.

**Closed by tjferriss** 2023-07-21 03:13 UTC
Labels: External, Daily, Awaiting Payment, Bug
