### ISSUE TITLE
Chat - Tooltip for WS avatar is broken

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#30847] opened 2023-11-03 13:57 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.3.95.0
**Reproducible in staging?:** Y
**Reproducible in production?:** N
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:**Applause - Internal Team
**Slack conversation:**

## Action Performed:
1. Create a new workspace.
2. Go to workspace chat.
3. Click + > Request money
4. Create a manual request
5. Hover over WS avatar

## Expected Result:
Tooltip for WS avatar is not broken

## Actual Result:
Tooltip for WS avatar is broken

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] Windows: Chrome 
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details> 

![Bug6262310_1699019485092!image__17_ (1)](https://github.com/Expensify/App/assets/78819774/96d0bdcf-4f87-4528-9bf3-3ae6fd4a2a05)

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by pecanoro** [comment] 2023-11-03 14:19
@sakluger Can you reproduce this one? It's working just fine for me

**Comment by Beamanator** [comment] 2023-11-03 14:33
I see the incorrect workspace avatar background color

<img width="474" alt="Screenshot 2023-11-03 at 4 32 47 PM" src="https://github.com/Expensify/App/assets/3885503/cfb1fc65-0063-42d1-afb6-ec57edc99bed">

**Comment by s-alves10** [comment] 2023-11-03 14:43
Looks like a dupe of https://github.com/Expensify/App/issues/30846

**Comment by pecanoro** [comment] 2023-11-03 16:04
Still can't get the tooltip to look broken like the original screenshot (when it comes to the email I mean). Either way, we are fixing the background in the other one so closing this one

**Closed by pecanoro** 2023-11-03 16:04 UTC
Labels: DeployBlockerCash, Engineering, Hourly, Bug
