### ISSUE TITLE
Chat - Emoji not added/removed on single tap/click from the emoji popover

### ISSUE THREAD

**Issue by izarutskaya** [Expensify/App#26232] opened 2023-08-29 16:44 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Add a random emoji to a message
2. Now click on the +emoji button on the same message and add another emoji from the emoji popover ex: like emoji
3. Click again on the +emoji button and press the like emoji to remove it from the emoji popover.
4. Repeat steps 2 and 3 until you notice that it sometimes takes 2 press/clicks to add remove the emoji.

## Expected Result:
Emoji should be added/removed on single click from the emoji popover

## Actual Result:
It sometimes takes multiple clicks to add/remove an emoji from the emoji popover

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [x] iOS / Safari
- [ ] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:**  v1.3.58-1

**Reproducible in staging?:** Y

**Reproducible in production?:** Y

**If this was caught during regression testing, add the test name, ID and link from TestRail:**

**Email or phone of affected tester (no customers):**

**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/115492554/53438d96-7c46-4554-b931-d37fa6e2fac6

https://github.com/Expensify/App/assets/115492554/0a1ba950-8eb2-4493-a3e3-ed9d3c214bc3

**Expensify/Expensify Issue URL:**

**Issue reported by:** @huzaifa-99

**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1692698631606089

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by sonialiap** [comment] 2023-09-06 13:15
I'm on bad wifi right now and newdot isn't loading. I will triage this once I get to better wifi - most likely tomorrow

**Comment by sonialiap** [comment] 2023-09-12 06:45
Dupe of https://github.com/Expensify/App/issues/16506?

**Closed by sonialiap** 2023-09-12 06:45 UTC
Labels: Daily, Overdue, Bug
