### ISSUE TITLE
 Preferences - Mute all sounds from Expensify toggle does not update on secondary device

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#36487] opened 2024-02-14 14:22 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.41-2
**Reproducible in staging?:** Y
**Reproducible in production?:** No, new feature
**If this was caught during regression testing, add the test name, ID and link from TestRail:** https://expensify.testrail.io/index.php?/tests/view/4312305
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** Applause - Internal Team
**Slack conversation:**

## Action Performed:
1. Log in to New Expensify on two devices with the same account
2. Navigate to Preferences
3. [Main device] Use both toggles below Notifications to change their state

## Expected Result:
Toggles should update on secondary device to reflect changes made in main device

## Actual Result:
Contrary to the other toggle, the "Mute all sounds from Expensify" toggle does not update on secondary device.

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [ ] Android: mWeb Chrome
- [x] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details>  

https://github.com/Expensify/App/assets/78819774/f4b7ecef-e81e-4dc6-b76e-062d229c4574

 
[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by jayeshmangwani** [comment] 2024-02-14 14:33
@dangrous Seems like a backend issue, pusher data is not updated when toggle the sound preference

**Comment by dangrous** [comment] 2024-02-14 14:55
Let me see if this is intended or not, I feel like there was some discussion around it that I recall, and it might be expected behavior?

**Comment by dangrous** [comment] 2024-02-14 15:28
Either way this should definitely not be a deploy blocker, as the syncing never existed in the first place.

Primarily just trying to figure out if we should keep this issue open to have it call the BE or leave it and do nothing.

**Comment by dangrous** [comment] 2024-02-14 15:30
@Beamanator I see you're assigned to https://github.com/Expensify/App/issues/36455 - I think we only need one of these; which would you prefer to keep open?

**Comment by Beamanator** [comment] 2024-02-14 16:10
Haha good point!

I'd say the one I'm assigned to just cuz it's been opened longer? Maybe? Feel free to take over, I don't need an extra issue or anything hahaha

**Comment by m-natarajan** [comment] 2024-08-05 13:20
Reopening as this issue is reproducible as per this  https://expensify.slack.com/archives/C049HHMV9SM/p1722620957808589

**Closed** 2024-08-05 15:41 UTC
Labels: Engineering, Daily
