### ISSUE TITLE
Assign task - Workspace employee B has permission to edit title, description, reassign task

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#27059] opened 2023-09-08 20:46 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
Precondition: for the following tests prepare 3 accounts
• A workspace admin (workspace creator)
• A workspace employee A (task creator)
• A workspace employee B
All accounts should be added to the workspace of the workspace admin

1. Go to https://staging.new.expensify.com/
2. Login as the workspace employee A
3. Navigate to the workspace #Announce room
4. Create a task and Assign to yourself
5. Log out from the workspace employee A
6. Login as the workspace employee B
7. Navigate to the workspace 
8. Click on the task created by the workspace employee A

## Expected Result:
Workspace employee B has no permission to edit the title of the task, reassign the task, edit the description of the task. Only Workspace admins should have permission to edit and reassign tasks created by employees of the workspace

## Actual Result:
Workspace employee B has permission to edit the title of the task, reassign the task, edit the description of the task

Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android / native
- [x] Android / Chrome
- [x] iOS / native
- [x] iOS / Safari
- [x] Windows / Chrome 
- [x] MacOS / Desktop

**Version Number:** 1.3.66-3

**Reproducible in staging?:** Yes

**Reproducible in production?:** Yes

**If this was caught during regression testing, add the test name, ID and link from TestRail:**

**Email or phone of affected tester (no customers):**

**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/78819774/7b35b207-d0f5-4cbe-ae3e-9178110f08d0

**Expensify/Expensify Issue URL:**

**Issue reported by:** Applause - Internal Team

**Slack conversation:**

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by kevinksullivan** [comment] 2023-09-13 02:50
Closing as I believe this is by design.

**Closed by kevinksullivan** 2023-09-13 02:50 UTC
Labels: Daily, Overdue, Bug
