### ISSUE TITLE
[HOLD for payment 2024-02-07]  Private note - Private note opened from deeplink in offline shown empty

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#34270] opened 2024-01-10 17:32 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:**  1.4.24-0 
**Reproducible in staging?:** Y
**Reproducible in production?:** N
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** Applause - Internal Team
**Slack conversation:**

**Issue found when executing PR** https://github.com/Expensify/App/pull/31257
## Action Performed:
1. Open any chat and select a Contact to view their details.
2. Open a note and copy its link (URL) and paste and send to the chat
3. Log out and login again
4. Open the same chat and disconnect
5. Open the deeplink of the note in edit mode
6. Turn on the internet connection.

## Expected Result:
The note is opened in edit mode and can be seen fully

## Actual Result:
An empty note is opened in edit mode after the connection recovers

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [x] Android: mWeb Chrome
- [ ] iOS: Native
- [x] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details>  

https://github.com/Expensify/App/assets/78819774/36f1d36b-602c-4b21-9bb1-372109db0b1e

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by lanitochka17** [comment] 2024-01-10 17:33
Production: 

https://github.com/Expensify/App/assets/78819774/7a598159-1560-4791-aaa7-fb79d56b0779

**Comment by abzokhattab** [comment] 2024-01-10 19:11
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
when opening the deeplink in offline and connecting to the network .. an empty private note appear 
### What is the root cause of that problem?
the loader indicator is not shown in case the `isPrivateNotesFetchTriggered`  is `false`
 https://github.com/Expensify/App/blob/48ab68e8ee0a33b16f2f1bf706800e1a000e31b9/src/pages/home/report/withReportAndPrivateNotesOrNotFound.js#L79

here we can find the `isPrivateNotesFetchTriggered` var initialization: 
https://github.com/Expensify/App/blob/48ab68e8ee0a33b16f2f1bf706800e1a000e31b9/src/pages/home/report/withReportAndPrivateNotesOrNotFound.js#L63

as you can notice we only check the existence of the `report.isLoadingPrivateNotes` prop we dont check if the value is `true` or `false`

and since in the optimistic value we set the `report.isLoadingPrivateNotes` to true then the `isLoadingPrivateNotes` value will be defined and the `isPrivateNotesFetchTriggered` will be true in this case and thus the loader indicator disappears.

the issue here occurs because at the optimistic stage the data is not yet fetched from the database so the report data will not contain the privateNote 
this happens 
### What changes do you think we should make in order to solve the problem?

we should remove the loader indicator only when the `isLoadingPrivateNotes` is `false`

thus we can introduce this new variable: 

```js
            const isPrivateNotesFetchFinished = isPrivateNotesFetchTriggered && !report.isLoadingPrivateNotes;
```

and update the loader indicator to: 

```js
            const shouldShowFullScreenLoadingIndicator = !isPrivateNotesFetchFinished || (isPrivateNotesEmpty && (report.isLoadingPrivateNotes || !isOtherUserNote));
```

**Comment by thienlnam** [comment] 2024-01-11 04:29
I don't think this needs to be a blocker - since the PR was merged recently, @hungvu193 and @jjcoffee can address

**Comment by jjcoffee** [comment] 2024-01-12 15:34
@hungvu193 Are you able to look into this?

**Comment by abzokhattab** [comment] 2024-01-14 11:00
Let me know what you think about the proposal above ... the PR can be ready once assigned.

**Comment by hungvu193** [comment] 2024-01-15 02:38
> @hungvu193 Are you able to look into this?

let me take a look

**Comment by stitesExpensify** [comment] 2024-01-16 17:45
@hungvu193 any update?

**Comment by jjcoffee** [comment] 2024-01-18 08:03
@hungvu193 Friendly bump! Did you get a chance to look at this?

**Comment by hungvu193** [comment] 2024-01-21 14:04
> @hungvu193 Friendly bump! Did you get a chance to look at this?

Sorry for late response, I'll draft a PR today.

**Comment by stitesExpensify** [comment] 2024-02-12 15:34
Great, Thanks!

**Closed by stitesExpensify** 2024-02-12 15:34 UTC
Labels: Engineering, Daily, Overdue, Awaiting Payment
