### ISSUE TITLE
[$1000] Emoji picker becomes non responsive in group report on creating new group using deep link from that group chat

### ISSUE THREAD

**Issue by kavimuru** [Expensify/App#21471] opened 2023-06-23 22:37 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Open the app
2. Open any group chat
3. Click on green plus button and click on new group
4. Copy the URL and send it in the group
5. Click on link and create new group
6. Click on back button of browser
7. Click on emoji in compose box and observe that it does not open emoji picker
## Expected Result: 
App should open emoji picker on click on emoji in composer box
## Actual Result: 
App does not open emoji picker of group chat on click on emoji in composer box if we send new group link as message, click on it and create new group and click on back to again comeback to group chat

## Workaround:
Can the user still use Expensify without this being fixed? Have you informed them of the workaround?

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [x] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 1.3.32-1
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/43996225/f14c81e6-9aa9-4eb9-b61c-c29066073097

https://github.com/Expensify/App/assets/43996225/a5a5a300-23ab-4c9a-a458-36a159612387

**Expensify/Expensify Issue URL:**
**Issue reported by:** @dhanashree-sawant
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1687102188474459

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~017d56f9afbc42a751</li>
        <li>Upwork Job ID: 1673408638124220416</li>
        <li>Last Price Increase: 2023-07-03</li>
    </ul>
</details>

**Comment by jeet-dhandha** [comment] 2023-06-25 05:24
### Proposal
### Please re-state the problem that we are trying to solve in this issue.
* The issue is relatively easy to reproduce:
    * just open a chat in WEB
    * Now navigate to different Chat.
    * Now press back button to go back to the previous chat.
    * Now the emoji picker is not opening as previous ref is still set instead of the current one.

<details>
<summary>Reproduced:</summary>
    
https://github.com/Expensify/App/assets/78416198/8eb3e652-a328-45b0-8188-f19a4f67b1e1

</details>

### What is the root cause of that problem?
* The root cause is that the `ref` is not getting updated on previous chat screen when we navigate to that from different chat screen.

### What changes do you think we should make in order to solve the problem?
### Solution 
- We should set new ref when we navigate to previous chat screen.
File > `src/pages/home/ReportScreen.js`

```diff
-    <EmojiPicker ref={EmojiPickerAction.emojiPickerRef} />
+    <EmojiPicker ref={(ref) => EmojiPickerAction.emojiPickerRef.current = ref} />
```

<details>
<summary>Fixed:</summary>
    
https://github.com/Expensify/App/assets/78416198/70eb9995-96b4-4cf7-bcd2-2bedbce9678a

</details>

### What alternative solutions did you explore? (Optional)
N/A

**Comment by flaviadefaria** [comment] 2023-06-26 19:11
Added the external label

**Comment by Hamjeth68** [comment] 2023-06-26 22:34
Contributor details
Your Expensify account email: [hamjeth68@gmail.com](mailto:hamjeth68@gmail.com)
Upwork Profile Link: https://www.upwork.com/freelancers/~01d7f72bf70dc53b3d


Open the app: This refers to launching the application, presumably a chat application.

Open any group chat: Navigate to a group chat within the app. This involves selecting a specific chat group from a list or any other means provided by the app.

Click on the green plus button and click on "new group": Look for a green plus button, likely representing an action to create a new group. Clicking on it should open a menu or dialog with an option to create a new group. Select the "new group" option.

Copy the URL and send it in the group: After creating the new group, a URL is likely generated for the newly created group. Copy this URL and send it within the original group chat. This step ensures that other group members can join the new group by accessing the shared URL.

Click on the link and create a new group: In the original group chat, someone (other than the sender of the URL) clicks on the shared link. This action should open the URL in the app and present an option to create a new group based on that link.

Click on the back button of the browser: This step assumes that the app is being accessed through a web browser or a browser-like interface. Clicking on the back button should navigate back from the newly created group to the original group chat.

Click on the emoji in the compose box and observe that it does not open the emoji picker: In the original group chat, locate the compose box where messages can be typed. Click on the emoji button within the compose box, which should typically open an emoji picker allowing the selection of emojis. However, in this scenario, the emoji picker fails to open.

Expected Result:
The expected result is that when the emoji button is clicked in the compose box of the original group chat, the emoji picker should open, allowing the user to select emojis.

Actual Result:
The actual result is that the emoji picker does not open when the emoji button is clicked in the compose box of the original group chat, specifically after performing the steps of sending a new group link, creating a new group from the link, and navigating back from the new group to the original group chat.

This issue indicates a bug or unexpected behavior in the app, as it fails to open the emoji picker as intended. The expected behavior should be that the emoji picker consistently opens regardless of the previously performed actions.

**Comment by flaviadefaria** [comment] 2023-06-29 11:22
@allroundexperts any thoughts on the proposals above?

**Comment by flaviadefaria** [comment] 2023-07-03 17:22
Thanks @allroundexperts. Just tested and also can't reproduce it so closing this issue.

**Closed by flaviadefaria** 2023-07-03 17:22 UTC
Labels: External, Daily, Help Wanted, Overdue, Bug
