### ISSUE TITLE
[$250]  LHN - RBR stays for paid report

### ISSUE THREAD

**Issue by izarutskaya** [Expensify/App#48400] opened 2024-09-02 10:52 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** v9.0.27-0
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**If this was caught during regression testing, add the test name, ID and link from TestRail:** https://expensify.testrail.io/index.php?/cases/view/3266257
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Issue reported by:** Applause-Internal team

## Action Performed:
Precondition: control ws exist with enabled categories, Tags and Taxes. Enable toggle 'Members must categorize/tag all expenses'.

1. Employee: submit an expense with violation (without category and tag) in ws chat.
2. Admin: approve or pay the report with violation.

## Expected Result:
Employee: report doesn't have a RBR in the LHN and isn't pinned.

## Actual Result:
Employee: report still have a RBR in the LHN and isn't pinned.

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

https://github.com/user-attachments/assets/4ed69491-f663-4e83-b488-26731680c9d5

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~021832065922256660213</li>
        <li>Upwork Job ID: 1832065922256660213</li>
        <li>Last Price Increase: 2024-09-27</li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @mkhutornyi</details>

**Comment by izarutskaya** [comment] 2024-09-02 10:53
We think this issue might be related to the #wave-control

**Comment by FitseTLT** [comment] 2024-09-02 14:01
This should be fixed in BE. If you clear cache the RBR disappears so the BE should properly clear violation data on pay. Although we could do it optimistically for payer side the same clearing should be applied for other users too so it should be done in BE altogether.

**Comment by FitseTLT** [comment] 2024-09-02 20:13
## Proposal

### Please re-state the problem that we are trying to solve in this issue.

LHN - RBR stays for paid report

### What is the root cause of that problem?
In all MoneyRequestPreview, MoneyReportView and LHN RBR we are showing RBR whenever there is a report or transaction violations
https://github.com/Expensify/App/blob/e60b8210a1f5a2471d8aa9d84d0e461774b791d6/src/components/ReportActionItem/ReportPreview.tsx#L168-L170
https://github.com/Expensify/App/blob/e60b8210a1f5a2471d8aa9d84d0e461774b791d6/src/components/ReportActionItem/MoneyRequestPreview/MoneyRequestPreviewContent.tsx#L112
https://github.com/Expensify/App/blob/e60b8210a1f5a2471d8aa9d84d0e461774b791d6/src/components/LHNOptionsList/OptionRowLHNData.tsx#L40
### What changes do you think we should make in order to solve the problem?

We should only display RBR when violations exist if the iouReport is not settled (or not approved if we choose to do so).
Therefore, in all the cases listed above we need to add a condition of `!ReportUtils.isSettled(`. We can centralize the code by creating new functions to add these conditions or we can update all `TransactionUtils.hasViolation`, `ReportUtils.hasReportViolations` and `ReportUtils.hasViolations` to check for `isSettled` of the linked iou report.
### What alternative solutions did you explore? (Optional)

**Comment by trjExpensify** [comment] 2024-09-10 01:45
Hm, I'm curious for where this regressed as I'm sure it has been discussed before. CC: @JmillsExpensify @cead22 

Moving to #wave-control project anyway, as a violations bug.

**Comment by kevinksullivan** [comment] 2024-09-11 21:32
Looping in another BZ member as I am going OOO

**Comment by FitseTLT** [comment] 2024-09-13 17:52
[Here](https://github.com/FitseTLT/App/tree/fix-showing-rbr-for-violations-on-settled-report) is a test branch @mkhutornyi

**Comment by cead22** [comment] 2024-09-16 07:57
@FitseTLT from what I understand, the functions you mentioned in the proposal have never had code to check if a report is settled, so that check has to exist somewhere ele, and I think it works for some cases. Can you share where that check is, and why it works for some cases and not others?

**Comment by FitseTLT** [comment] 2024-09-16 12:07
>Can you share where that check is, and why it works for some cases and not others?

@cead22 the only FE check we are including is for transaction thread violations here
https://github.com/Expensify/App/blob/fc33ac1ac35248ecf888bb8d4e8e04b5e72cc56e/src/libs/ReportUtils.ts#L5897-L5899
But the inconsistency for other cases comes from the BE: sometimes the BE clears all the violations (transactionViolations and reportViolations) on payment and sometimes it doesn't.

**Comment by cead22** [comment] 2024-09-16 16:28
If the backend doesn't clear the violations, and they show when the report is settled, then we're going through a flow that doesn't go through the code you linked. What flow is that?

Can you share the flows for which the backend isn't updating violations correctly?

**Comment by FitseTLT** [comment] 2024-09-17 16:16
> If the backend doesn't clear the violations, and they show when the report is settled, then we're going through a flow that doesn't go through the code you linked. What flow is that?
> 
> Can you share the flows for which the backend isn't updating violations correctly?

Ok @cead22 the flow is here in report preview
https://github.com/Expensify/App/blob/e60b8210a1f5a2471d8aa9d84d0e461774b791d6/src/components/ReportActionItem/ReportPreview.tsx#L168-L170
and here in money request preview
https://github.com/Expensify/App/blob/e60b8210a1f5a2471d8aa9d84d0e461774b791d6/src/components/ReportActionItem/MoneyRequestPreview/MoneyRequestPreviewContent.tsx#L112
Here is a demo vid: after paying the RBR remains and when clearing cache the RBR will disappear from report preview but after opening the transactions the RBR reappears because the transactionViolations are fetched by then.

Uploading 2024-09-17 19-11-14.mp4…

**Comment by cead22** [comment] 2024-09-20 12:50
From @nkdengineer in https://github.com/Expensify/App/issues/48397#issuecomment-2362825011
> @cead22 I think we should clear the hold violation in optimistic data if we paid full instead of adding !isSettled condition.

**Comment by cead22** [comment] 2024-09-23 10:10
@FitseTLT thanks for that
- The red circle on showing on the report preview is working as intended, because the report has violations and we show that no matter what the state of the report is.
- The green circle on the LHN showing for that report might be working as intended, assuming we decided the green circle that is shown on reports with pending actions -- in this case paying, should take precedence over the red circle in the LHN that we show on reports with violations. Can you confirm @JmillsExpensify?
- After paying, the red circle should remain in the report preview, for the same reason as in the first bullet
- After clearing the cache, the report preview isn't showing the red circle, and after clicking on the preview, the transaction previews aren't showing the red circle. These are bugs because they should be showing for the same reason as in the first bullet

@JmillsExpensify did I get this right or has this changed from what I remember?

**Comment by marcochavezf** [comment] 2024-10-03 01:49
From this [comment](https://github.com/Expensify/App/issues/48400#issuecomment-2367773018), seems part of the behavior is expected. Closing it out for now, but we can re-open if it's reported again as an issue

**Closed by marcochavezf** 2024-10-03 01:49 UTC
Labels: External, Daily, Help Wanted, Overdue, Bug
