### ISSUE TITLE
Several `ReconnectApp` call displayed when accessing after sleep (Closing and opening lid of laptop)

### ISSUE THREAD

**Issue by m-natarajan** [Expensify/App#43667] opened 2024-06-13 15:20 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 
**Reproducible in staging?:** Needs reproduction
**Reproducible in production?:** Needs reproduction
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** @quinthar 
**Slack conversation:** https://expensify.slack.com/archives/C05LX9D6E07/p1718128174597309

## Action Performed:

1. Open NewDot on any random page
2. Open the Network console
3. Close your laptop lid
4. Wait for 10-15 seconds
5. Open the lid

## Expected Result:
No multiple `ReconnectApp` calls
## Actual Result:
Multiple `ReconnectApp` calls 
## Workaround:
Unknown
## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence
![image (2)](https://github.com/Expensify/App/assets/38435837/fde201ba-564f-4dab-97c0-412be1409f03)

![image (3)](https://github.com/Expensify/App/assets/38435837/d1e698b6-e44d-4811-b047-0ee2aa29273d)

![image (4)](https://github.com/Expensify/App/assets/38435837/e7917294-c5a3-4def-a763-d4e8c8f965a0)

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by muttmuure** [comment] 2024-06-13 15:39
Dupe of https://github.com/orgs/Expensify/projects/71/views/1?pane=issue&itemId=67267405

**Closed by muttmuure** 2024-06-13 15:39 UTC
Labels: Daily, Weekly, Bug, AutoAssignerNewDotQuality
