### ISSUE TITLE
[$125] Scroll bar is on the left side on Wallet page

### ISSUE THREAD

**Issue by m-natarajan** [Expensify/App#48769] opened 2024-09-08 15:22 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___
 
**Version Number:** 9.0.30-15
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** @mountiny 
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1725796844406159

## Action Performed:
1. Go to Wallet page on ios native
2. Scroll down
## Expected Result:
Scroll bar on right side
## Actual Result:
Scroll bar on left side
## Workaround:
Unknown
## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [x] iOS: Native
- [ ] iOS: mWeb Safari
- [ ] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

<img src="https://github.com/user-attachments/assets/9b12390e-e88e-4760-ba76-e570edc3e040" width="40%" height="40%">

<img src="https://github.com/user-attachments/assets/864f17f6-5d94-4a59-854d-fc134af802a9" width="40%" height="40%">

Add any screenshot/video evidence

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~021832849619299247163</li>
        <li>Upwork Job ID: 1832849619299247163</li>
        <li>Last Price Increase: 2024-09-08</li>
<li>Automatic offers: </li>
<ul>
<li>hoangzinh | Reviewer | 103885982</li>
</ul></li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @hoangzinh</details>

**Comment by Shahidullah-Muffakir** [comment] 2024-09-08 21:37
I tested the **Wallet page** on version **9.0.30-15** and the scroll bar appears correctly on the right side on the simulator. It’s possible that the scroll bar positioning issue might be related to specific device settings on the tester’s end

https://github.com/user-attachments/assets/6c3389ef-29b3-4223-aac7-e0066fd49553

**Comment by thezeeshanhassan** [comment] 2024-09-08 22:05
The scroll bar on the Wallet page is appearing on the left side instead of the right, which is not the expected behavior. This affects user experience, as most users expect the scroll bar to be on the right side of the screen.

**Root Causes:**
The issue is likely caused by incorrect layout or styling configurations, particularly with the direction property in the React Native code. It could be due to an unintended use of right-to-left (RTL) layout direction.

**Proposed Changes:**
Check for RTL Settings: Ensure that the layout direction is set to left-to-right (LTR). If any RTL setting is applied (e.g., via I18nManager), it should be disabled for this page.

`import { I18nManager } from 'react-native';

componentDidMount() {
    if (I18nManager.isRTL) {
        I18nManager.allowRTL(false);
    }
}
`
**Adjust Scroll Bar Styling:** 
Use platform-specific styling to ensure the scroll bar is rendered correctly on the right side on all platforms (iOS, Android, Web).

**Test Across Platforms:** 
After applying the changes, thoroughly test the Wallet page on iOS, Android, and Web to confirm the scroll bar behaves as expected.

**Alternative Solutions (Optional):**
Implement a CSS fix specifically for web platforms using ::-webkit-scrollbar to ensure the scroll bar appears correctly.
Looking Forward to your response.
Have a Great Day!!!

**Comment by mountiny** [comment] 2024-09-08 23:05
Ah right, I can see this only in the hybrid app 9.0.30-15 while the same version in NewDot is not repro
![IMG_6202](https://github.com/user-attachments/assets/33cb1ff0-15e9-4ba5-8181-6707557187e6)

Now it was even weirder

**Comment by war-in** [comment] 2024-09-09 15:59
Oh sorry for not updating you here 🤦

I'm Marcin from Software Mansion, an expert agency, and I'd be glad if you assigned me here 🙏

**Comment by thezeeshanhassan** [comment] 2024-09-09 16:13
> 📣 @thezeeshanhassan! 📣 Hey, it seems we don’t have your contributor details yet! You'll only have to do this once, and this is how we'll hire you on Upwork. Please follow these steps:
> 
> 1. Make sure you've read and understood the [contributing guidelines](https://github.com/Expensify/App/blob/main/contributingGuides/CONTRIBUTING.md).
> 2. Get the email address used to login to your Expensify account. If you don't already have an Expensify account, create one [here](https://new.expensify.com/). If you have multiple accounts (e.g. one for testing), please use your main account email.
> 3. Get the link to your Upwork profile. It's necessary because we only pay via Upwork. You can access it by logging in, and then clicking on your name. It'll look like [this](https://www.upwork.com/freelancers/~01ca8ad8ce36b9eceb). If you don't already have an account, sign up for one [here](https://www.upwork.com/nx/signup/?dest=home).
> 4. Copy the format below and paste it in a comment on this issue. Replace the placeholder text with your actual details.
>    ![Screen Shot 2022-11-16 at 4 42 54 PM](https://user-images.githubusercontent.com/30609178/231263719-a8a3b7d3-36a0-4d7f-8ad4-cebe1f560fa4.png)
>    Format:
> 
> ```
> Contributor details
> Your Expensify account email: <REPLACE EMAIL HERE>
> Upwork Profile Link: <REPLACE LINK HERE>
> ```

I am Added My account details

**Comment by mountiny** [comment] 2024-09-11 10:37
I think we can close this now, the pr was merged and nothing to pay or to make regression testing

**Closed by mountiny** 2024-09-11 10:37 UTC
Labels: Reviewing, External, Weekly, Bug
