### ISSUE TITLE
[C+ Checklist Needs Completion] [$500] Android - Task - Background image in task report appears cropped after cancelling the task

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#33922] opened 2024-01-04 01:12 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.21-2
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** Applause - Internal Team
**Slack conversation:**

## Action Performed:
1. Go to 1:1 DM > + > Assign task
2. Create a task
3. Open the task report
4. Tap 3-dot menu > Cancel
5. Cancel the task

## Expected Result:
The background image in task report will not appear cropped after cancelling the task

## Actual Result:
The background image in task report appears cropped after cancelling the task

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [ ] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details> 

https://github.com/Expensify/App/assets/78819774/a11df018-ef32-4d1c-b467-7bee1493c7e3

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01f32de82628d0256b</li>
        <li>Upwork Job ID: 1742715497820069888</li>
        <li>Last Price Increase: 2024-01-25</li>
<li>Automatic offers: </li>
<ul>
<li>aimane-chnaif | Contributor | 28124230</li>
<li>aswin-s | Contributor | 28143615</li>
</ul></li>
    </ul>
</details>

**Comment by aswin-s** [comment] 2024-01-04 02:53
## Proposal

### Please re-state the problem that we are trying to solve in this issue.

The EmptyStateBackground image on deleted task page looks clipped

### What is the root cause of that problem?

The AnimatedEmptyStateBackground component is wrapped inside a Fragment for TaskReport. This seems to cause the image to get clipped on small screen devices.

https://github.com/Expensify/App/blob/d4c3e63956e9c14838592172c7e0e8596b0814cf/src/pages/home/report/ReportActionItem.js#L586-L598

This causes edges of the image to get clipped when there is not enough height for the image container.

### What changes do you think we should make in order to solve the problem?

Replace empty fragment with a view

```tsx
<View >
  <AnimatedEmptyStateBackground />
  <View style={[StyleUtils.getReportWelcomeTopMarginStyle(props.isSmallScreenWidth)]}>
    <ReportActionItemSingle
      action={parentReportAction}
      showHeader={_.isUndefined(props.draftMessage)}
      report={props.report}
    >
        <RenderHTML html={`<comment>${props.translate('parentReportAction.deletedTask')}</comment>`} />
    </ReportActionItemSingle>
    <View style={styles.reportHorizontalRule} />
  </View>
</View
```

Result

Before

![Screenshot_1704336463](https://github.com/Expensify/App/assets/6880914/3b248c21-5057-40db-bf17-0f5b70298734)

After

![Screenshot_1704336747](https://github.com/Expensify/App/assets/6880914/7315837e-d3bd-43de-a665-a997e60d2be5)



### What alternative solutions did you explore? (Optional)
None (edited)

**Comment by aswin-s** [comment] 2024-01-04 03:45
Withdrawing my first proposal as it seems to break on web.

**Comment by aswin-s** [comment] 2024-01-04 03:47
## Proposal

### Please re-state the problem that we are trying to solve in this issue.

The EmptyStateBackground image on deleted task page looks clipped

### What is the root cause of that problem?

Animated background image used to be an SVG image. Recently that was replaced with a PNG. Earlier we used to set the container width to `200%` to make the SVG image appear covering the screen on small screens.

https://github.com/Expensify/App/blob/d4c3e63956e9c14838592172c7e0e8596b0814cf/src/styles/utils/index.ts#L704

Now this is not required as PNG images properly apply the resizeMode within the container.

### What changes do you think we should make in order to solve the problem?

Set BackgroundImage container width to 100%

```tsx
if (isSmallScreenWidth) {
        return {
            height: emptyStateBackground.SMALL_SCREEN.IMAGE_HEIGHT,
            width: '100%',
            position: 'absolute',
        };
}
```

Now the image translation logic needs to be adjusted as width is now set to 100%

https://github.com/Expensify/App/blob/d4c3e63956e9c14838592172c7e0e8596b0814cf/src/pages/home/report/AnimatedEmptyStateBackground.tsx#L16

to

```tsx
const IMAGE_OFFSET_X = 0;
```

**Result**

| Before | After |
|--|--|
| ![Screenshot_1704336463](https://github.com/Expensify/App/assets/6880914/3b248c21-5057-40db-bf17-0f5b70298734) | ![Screenshot_1704336747](https://github.com/Expensify/App/assets/6880914/7315837e-d3bd-43de-a665-a997e60d2be5) |

### What alternative solutions did you explore? (Optional)
None (edited)

**Comment by bernhardoj** [comment] 2024-01-04 14:43
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
The report background image is cut off on a canceled task report.

### What is the root cause of that problem?
In short, the view container height is smaller than the background height.

The image height is defined by `IMAGE_HEIGHT`.
https://github.com/Expensify/App/blob/d800d60c967e40cd73184a77cf59456100d7109c/src/CONST.ts#L134-L143

On a small screen, the height is `300`. When the task is canceled, we render a simple [Deleted task] message.
https://github.com/Expensify/App/blob/d800d60c967e40cd73184a77cf59456100d7109c/src/pages/home/report/ReportActionItem.js#L584-L599

The height is around 70 and we have a margin-top style from `getReportWelcomeTopMarginStyle`. It's defined by `VIEW_HEIGHT` above and the value is `185`. So, the total height is around 255 and it's smaller than 300.

### What changes do you think we should make in order to solve the problem?

1. Update the min-height (defined by `CONTAINER_MINHEIGHT`) at least to 300.
2. Then, we will update the task view in ReportActionItem by wrapping it with a View following the same pattern in ReportActionItemParentAction
https://github.com/Expensify/App/blob/6e5a5a22b3017d1550f21e4de60c1906ed2db413/src/pages/home/report/ReportActionItemParentAction.js#L65-L69

```
<View style={StyleUtils.getReportWelcomeContainerStyle(props.isSmallScreenWidth)}>
    <AnimatedEmptyStateBackground />
    <View style={[StyleUtils.getReportWelcomeTopMarginStyle(props.isSmallScreenWidth)]}/>
    <View>
        <ReportActionItemSingle
            action={parentReportAction}
            showHeader={_.isUndefined(props.draftMessage)}
            report={props.report}
        >
            <RenderHTML html={`<comment>${props.translate('parentReportAction.deletedTask')}</comment>`} />
        </ReportActionItemSingle>
        <View style={styles.reportHorizontalRule} />
    </View>
</View>
```

(do the same for non-canceled task)

**Comment by Pujan92** [comment] 2024-01-04 18:31
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
For android, an empty state image in the task report clipped and doesn't looks correct

### What is the root cause of that problem?
Currently, Parent of the absolute image have `flex-direction: column-reverse;` and due to that absolute position starting points will be incorrect. Due to that it overflows in the empty area which will be the unalloted area and in android it clipped to the boundary which creates this issue. 

Problem arises after this [PR](https://github.com/Expensify/App/pull/30815) where the parent `View` gets removed which we had earlier here.
https://github.com/Expensify/App/pull/30815/files#diff-e6bee90bf18ae0cad1bb445ed9a9c0d989476874f1005810c0f8e93f1f39b99cL635

<details>
<summary>Issue</summary>

https://github.com/Expensify/App/assets/14358475/fc010930-3892-4ddb-a0e1-b3936709a95c

</details>

### What changes do you think we should make in order to solve the problem?

We should re-add parent by replacing fragment with `View` below places which corrects the position of an absolute image.

https://github.com/Expensify/App/blob/1752bc58bfc93a9b6dbaef41072bdf2593cc4820/src/pages/home/report/ReportActionItem.js#L586-L587
https://github.com/Expensify/App/blob/1752bc58bfc93a9b6dbaef41072bdf2593cc4820/src/pages/home/report/ReportActionItem.js#L602-L603

**Comment by greg-schroeder** [comment] 2024-01-08 20:21
Awaiting proposal review @alitoshmatov

**Comment by alitoshmatov** [comment] 2024-01-09 08:48
Missed this one, working now

**Comment by Pujan92** [comment] 2024-01-10 11:08
Based on this [comment](https://github.com/Expensify/App/pull/30815/files#diff-e6bee90bf18ae0cad1bb445ed9a9c0d989476874f1005810c0f8e93f1f39b99cR573) the styles applied to that `View` is adjusted to other place, seems that is the reason they have removed the `View`.

**Comment by greg-schroeder** [comment] 2024-01-18 00:32
Thoughts on the above @alitoshmatov?

**Comment by greg-schroeder** [comment] 2024-01-22 16:53
Bump @alitoshmatov :)

**Comment by alitoshmatov** [comment] 2024-01-24 11:58
Sorry I was having trouble with android environment for a couple of days, don't know when exactly solve my problem. It would great if we could reassign this issue. Once again, sorry for inconvenience 

cc: @greg-schroeder

**Comment by greg-schroeder** [comment] 2024-01-26 18:51
Okay, grabbing a new C+

**Comment by greg-schroeder** [comment] 2024-01-26 18:55
Reassigning to @aimane-chnaif as new C+

**Comment by greg-schroeder** [comment] 2024-01-31 17:03
Still in review

**Comment by aswin-s** [comment] 2024-02-01 20:06
@aimane-chnaif [Updated my proposal](https://github.com/Expensify/App/issues/33922#issuecomment-1876269079) with RCA on android. 

On Android the Flatlist contentContainer clips anything that gets rendered outside its bounds. Even adding overflow: 'visible' doesn't help. So the absolutely positioned image gets clipped by the contentContainer bounds on Android.

**Comment by Pujan92** [comment] 2024-02-02 02:51
[ScrollView clips children even with overflow: 'visible'](https://github.com/facebook/react-native/issues/31218)

**Comment by aswin-s** [comment] 2024-02-05 10:11
> I have no issue with just wrapping with `<View />` which is @Pujan92's solution.
> 
> @aswin-s @bernhardoj can you explain your additional changes why they're needed?

@aimane-chnaif 

It breaks on web. Especially when you resize the window.

**Comment by aswin-s** [comment] 2024-02-07 02:52
@aimane-chnaif Looks like this got fixed for Android on main (PR https://github.com/Expensify/App/pull/35232). However it introduced the [regression here](https://github.com/Expensify/App/issues/33922#issuecomment-1926666211).  Also on web it still shows cropped image on some resolutions. Should I still proceed? @situchan FYI Since you reviewed the PR https://github.com/Expensify/App/pull/35232
<img width="300" src="https://github.com/Expensify/App/assets/6880914/d506a8a8-9f8c-4ded-bb03-61f98854a245" />

**Comment by deetergp** [comment] 2024-03-27 04:24
So it sounds like we've still got some issues to fix here?

**Comment by deetergp** [comment] 2024-03-27 04:34
> No, it's past comment. We're waiting for https://github.com/Expensify/App/pull/36261 to hit staging.

Perfect! Thanks for setting me straight @aimane-chnaif 👍

**Comment by greg-schroeder** [comment] 2024-04-05 19:21
C and C+ paid. Can you complete the checklist @aimane-chnaif? Thanks!

**Comment by deetergp** [comment] 2024-04-15 17:09
Bump @aimane-chnaif

**Comment by greg-schroeder** [comment] 2024-04-18 06:06
Friendly bump to get this checklist done @aimane-chnaif!

**Comment by greg-schroeder** [comment] 2024-04-26 19:29
@aimane-chnaif any chance we can knock this out?

**Comment by greg-schroeder** [comment] 2024-05-07 09:37
@aimane-chnaif please jump on this one so we can close it, thank you!

**Comment by greg-schroeder** [comment] 2024-05-09 05:08
Oh, Aimane is OOO. @aswin-s any chance you could step in for the checklist?

**Comment by greg-schroeder** [comment] 2024-05-15 08:56
Bump @aimane-chnaif or @aswin-s

**Comment by greg-schroeder** [comment] 2024-05-22 00:14
No sweat! Thanks @aimane-chnaif

**Closed by greg-schroeder** 2024-05-22 00:14 UTC
Labels: External, Weekly, Internal, Awaiting Payment, Bug
