### ISSUE TITLE
mWeb - Chat - `New message` line indicator is not displayed over the new messages when opening an unread conversation.

### ISSUE THREAD

**Issue by kavimuru** [Expensify/App#12448] opened 2022-11-03 19:54 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Go to https://staging.new.expensify.com/
2. Log in with any account
3. Navigate to any convo and disable the internet connection in the main testing device
4. Send some messages, while offline, to another account you have access
5. Go back online 
6. And go back to LHN
7. Log in to account B in another device and send some messages to main testing device account
8. Verify that the username on the left hand navigation is displayed bold and enter the conversation that has unread messages and Verify there is a "Greenline" indicating the New Messages.

## Expected Result:
When opening conversations with unread messages a new message line indicator should display over the new messages when opening an unread conversation.

## Actual Result:
New message line indicator is not displayed over the new messages when opening an unread conversation

## Workaround:
Unknown

## Platform:

Where is this issue occurring?

- Mobile Web - iOS Safari

**Version Number:** v1.2.23-7

**Reproducible in staging?:** y

**Reproducible in production?:** y

**Email or phone of affected tester (no customers):** 

**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Notes/Photos/Videos:** 

https://user-images.githubusercontent.com/43996225/199820990-d0015c86-da2f-40b9-be11-46a64e95863a.mp4

https://user-images.githubusercontent.com/43996225/199820999-6d92340c-c6a8-44b3-ac46-ff0f61ab6658.mp4

**Expensify/Expensify Issue URL:** 

**Issue reported by:** 
Applause internal team

**Slack conversation:** 

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by kadiealexander** [comment] 2022-11-08 06:20
@kakajann I just tried to replicate this in iOS Safari and wasn't able to replicate it. Could you please share updated replication steps if this is still occurring for you?

https://user-images.githubusercontent.com/59587260/200489482-3211a625-1395-4d7b-a2a5-ca4605591719.MP4

**Comment by kakajann** [comment] 2022-11-08 06:51
Sorry, how am I involved to this? :)

**Comment by kadiealexander** [comment] 2022-11-08 21:46
Apologies! I'm not sure why I got my wires crossed there. Please ignore @kakajann!!

@Expensify/applause please reopen with replication steps if this is still occurring.

**Comment by kbecciv** [comment] 2022-11-10 18:54
Issue is still reproduced with build 1.2.26.0

https://user-images.githubusercontent.com/93399543/201181863-a1f9acb9-6917-4ac8-a93e-9ac8f94261cb.mp4

**Comment by kadiealexander** [comment] 2022-11-15 04:59
@kbecciv the username was not bold in your most recent video, which is what this issue is about. Could you please share reproduction steps here and explain what is expected to happen?

**Comment by kbecciv** [comment] 2022-11-15 15:38
The reproduction steps the same - only issue with "Green line" doesn't appear. User is expecting when opening conversations with unread messages a new message line indicator should display over the new messages.

**Comment by kadiealexander** [comment] 2022-11-15 21:48
@kbecciv since the bug has changed, could you please update the original post and header to clarify what still needs to be fixed?

**Comment by kadiealexander** [comment] 2022-11-21 04:52
Thanks! Was able to reproduce:

https://user-images.githubusercontent.com/59587260/202967866-8b5d2d63-10ae-40bf-a37c-75959ff59b6e.MP4

BugZero Checklist:

- [x] The bug is a bug
- [ ] The bug is not a duplicate (It's very similar to [this](https://github.com/Expensify/App/issues/11083), checking to ensure it's different).
- [x] The bug is reproducible (see above)

**Comment by kadiealexander** [comment] 2022-11-24 03:36
Closing in favour of https://github.com/Expensify/App/issues/11083 as a duplicate, if this is still occurring once that issue is resolved please open the chat.

**Closed by kadiealexander** 2022-11-24 03:36 UTC
Labels: Daily, Needs Reproduction, Overdue, Bug
