### ISSUE TITLE
[HOLD for payment 2024-01-18] [HOLD for payment 2024-01-17]  IOU - Merchant editor does not close when removing merchant

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#34145] opened 2024-01-09 14:32 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.23-0
**Reproducible in staging?:** Y
**Reproducible in production?:** N
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** Applause - Internal Team
**Slack conversation:**

**Issue found when executing PR** https://github.com/Expensify/App/pull/33227
## Action Performed:
1. Go to 1:1 DM > + > Request money
2. Create a manual request without merchant
3. Open the request details page
4. Click Merchant
5. Add a merchant and save it
6. Click Merchant
7. Empty the merchant and save it
Note that merchant editor does not close

## Expected Result:
The merchant editor closes

## Actual Result:
The merchant editor does not close

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [x] Android: mWeb Chrome
- [x] iOS: Native
- [x] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details> 

https://github.com/Expensify/App/assets/78819774/d22d9e77-3816-4c39-aecb-b9c9894394d8

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by DylanDylann** [comment] 2024-01-09 14:40
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
The merchant editor does not close

### What is the root cause of that problem?
When newTrimmedMerchant is empty we update merchant but we don't dismiss modal
### What changes do you think we should make in order to solve the problem?
Should add `Navigation.dismissModal();` in this case

### What alternative solutions did you explore? (Optional)
NA

**Comment by luacmartins** [comment] 2024-01-09 15:48
This is a regression from my PR. I can work on a fix.

**Comment by dangrous** [comment] 2024-01-09 15:49
thanks @luacmartins !

**Comment by luacmartins** [comment] 2024-01-09 16:10
PR here https://github.com/Expensify/App/pull/34158

**Comment by luacmartins** [comment] 2024-01-22 20:27
Just pending payment

**Comment by anmurali** [comment] 2024-01-24 23:51
@0xmiroslav - offer is [here](https://www.upwork.com/nx/wm/offer/100607445)

**Comment by anmurali** [comment] 2024-01-29 23:29
Waiting on @0xmiroslav to accept the offer.

**Comment by luacmartins** [comment] 2024-02-05 22:12
Just pending payment

**Comment by anmurali** [comment] 2024-02-06 16:47
@0xmiroslav still has not accepted the offer https://github.com/Expensify/App/issues/34145#issuecomment-1909114783

**Comment by anmurali** [comment] 2024-02-14 00:50
Still not accepted. I am closing this GH. @0xmiroslav pls DM me directly on Slack when you accept and I can pay you.

**Closed by anmurali** 2024-02-14 00:50 UTC
Labels: Engineering, Daily, Overdue, Awaiting Payment, Bug
