### ISSUE TITLE
[$1000] Workspace - Can invite a user to workspace that is a contact method of an user in workspace

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#21574] opened 2023-06-26 14:28 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Login with account A
2. Create a workspace and invite user B that has an alternative contact method is B+
3. User A invites B+ vào workspace

## Ideal Result:
 When the added user is a secondary login of a previously added workspace member, surface a whisper for the admin that says "{secondary login} is already a workspace member under {primary login}" as discussed [here](https://expensify.slack.com/archives/C01GTK53T8Q/p1687975409953669) and [here](https://expensify.slack.com/archives/C01GTK53T8Q/p1690296029514519).

![image](https://github.com/Expensify/App/assets/59587260/df5a8b14-c2fa-498f-9e55-da6f9efcb24e)

## Current Result:
The invite appears to be successful but the policy members list doesn't change, causing confusion. 

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android / native
- [x] Android / Chrome
- [x] iOS / native
- [x] iOS / Safari
- [x] MacOS / Chrome / Safari
- [x] MacOS / Desktop

**Version Number:** 1.3.30-0
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation

[Screencast from 22-06-2023 17_06_33 (1).webm](https://github.com/Expensify/App/assets/93399543/3a8eb45f-ac14-4c0e-96e5-0e3d269fb95b)

https://github.com/Expensify/App/assets/93399543/7650d5e4-9f60-405e-b981-82295fd78ec3

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~013e19d88a3d7760c0</li>
        <li>Upwork Job ID: 1673560062990974976</li>
        <li>Last Price Increase: 2023-08-17</li>
    </ul>
</details>

**Comment by naji0329** [comment] 2023-06-27 08:35
To fix this issue, I think Validation should be done in the backend.
Not a RN problem.

**Comment by kadiealexander** [comment] 2023-07-04 05:50
Agreed, closing as not a bug.

**Comment by kadiealexander** [comment] 2023-07-05 20:49
As per the Slack discussion we are proceeding with this as a new feature instead of a bug.

**Comment by kadiealexander** [comment] 2023-07-20 05:57
Before we do, lets define how this should look. @shawnborton it was decided to implement a "whisper" [here](https://expensify.slack.com/archives/C01GTK53T8Q/p1687975409953669), could you please guide us on how this should look and behave?

**Comment by shawnborton** [comment] 2023-07-20 11:36
Whispers already exist on NewDot, so we should be able to reuse them. But they look something like this:

<img width="942" alt="image" src="https://github.com/Expensify/App/assets/2319350/f93cc369-7ab0-4a96-8373-d5da6c90aab4">

cc @pecanoro to confirm that it's a reusable component somewhere.

**Comment by kadiealexander** [comment] 2023-07-21 00:29
@parasharrajat the whisper should look like this, and show in the #admins room of the relevant workspace. 

![image](https://github.com/Expensify/App/assets/59587260/3cef5951-f9fb-4b56-af7e-1361250213ab)

**Comment by mountiny** [comment] 2023-07-21 10:45
I believe this change would have to be internal? You dont know the secondary logins of your contacts cc @pecanoro

**Comment by mountiny** [comment] 2023-07-21 11:51
@dukenv0307 Best to bring this to slack if its new feature

**Comment by kadiealexander** [comment] 2023-08-03 06:51
Discussion still happening in Slack.

**Comment by kadiealexander** [comment] 2023-08-14 08:11
Still working through it in Slack.

**Comment by kadiealexander** [comment] 2023-08-21 21:02
As discussed [here](https://expensify.slack.com/archives/C01GTK53T8Q/p1690296029514519) this will need to be done internally, as some of this information needs to be pulled from our back end.

**Comment by kadiealexander** [comment] 2023-08-31 06:47
@aldo-expensify any thoughts so far?

**Comment by aldo-expensify** [comment] 2023-08-31 17:26
No, I'll put it in my list of things to look at today!

**Comment by aldo-expensify** [comment] 2023-09-01 02:18
I started investigating this today. I think the place where we have to check if the invitation did a change or not and if it was a secondary login method is here:

https://github.com/Expensify/Web-Expensify/blob/c1d079ab69289bcf6e57d641178c1e692f079b8e/lib/PolicyAPI.php#L1094-L1107

I'll try to put up a PR tomorrow.

**Comment by aldo-expensify** [comment] 2023-09-01 19:52
@kadiealexander what about if you select multiple invitees that are skipped because they were secondary logins? Would you create a whisper for each one? or do a whisper including all of them?

If it is the later, how would the message look? something like:

```
xxx, yyy, zzz are already workspace members under xxx_primary, yyy_primary and zzz_primary
```
?

**Comment by aldo-expensify** [comment] 2023-09-01 20:55
Created a draft pull request. I'll finish once we decide the above case ^

**Comment by aldo-expensify** [comment] 2023-09-07 18:59
Bump @kadiealexander on https://github.com/Expensify/App/issues/21574#issuecomment-1703253418

**Comment by aldo-expensify** [comment] 2023-09-18 16:06
Friendly ping @kadiealexander

**Comment by kadiealexander** [comment] 2023-09-19 07:06
Apologies for the delay!!!! I like one whisper for all, personally, multiple whispers feel cluttering and unintuitive.

**Comment by shawnborton** [comment] 2023-09-28 03:39
What's the latest here?

**Comment by aldo-expensify** [comment] 2023-10-04 10:57
> What's the latest here?

I'm getting back to finish the implementation now

**Comment by aldo-expensify** [comment] 2023-10-04 16:07
PR https://github.com/Expensify/Web-Expensify/pull/38716 ready for review

**Comment by aldo-expensify** [comment] 2023-11-09 19:26
> @aldo-expensify What is next here?

Good question. Nothing I think, this was fixed in the backend by https://github.com/Expensify/Web-Expensify/pull/38716

Are there any payment to do? if there is none, then we can close

**Comment by kadiealexander** [comment] 2023-11-13 01:23
Payouts due:

- [ ] Contributor+: $250 @parasharrajat (via manual requests)

Eligible for 50% #urgency bonus? No

**Comment by JmillsExpensify** [comment] 2023-11-22 17:30
$250 payment approved for @parasharrajat based on comment above.

**Closed** 2023-12-20 02:31 UTC
Labels: Reviewing, Engineering, Monthly, Internal, NewFeature
