### ISSUE TITLE
Category not auto-added for second request with same Merchant as first.

### ISSUE THREAD

**Issue by izarutskaya** [Expensify/App#38560] opened 2024-03-19 09:19 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** v1.4.53-2
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**Email or phone of affected tester (no customers):** abebemiherat@gmail.com
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Issue reported by:** Applause-Internal team

## Action Performed:
1, Navigate to FAB > Request Money.
2, Enter the amount, select the user, and click "Add Split". Add Merchant and Category.
3, Proceed with splitting.
4, Again, navigate to FAB > Request Money. Enter the amount and select the same user as the first request. Click "Add Split" and add the same Merchant as before, but do not select Category. Split the bill.
5, Go to the IOU for the second request and observe that the Category is not automatically added.

## Expected Result:
When requesting money twice for the same user, if the first request includes the Merchant and Category, the second request with the same Merchant should automatically select the Category.

## Actual Result:
The Category is not automatically selected for the second request if the first request includes the Merchant and Category, but the second request lacks the Category selection.

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [x] Android: mWeb Chrome
- [ ] iOS: Native
- [x] iOS: mWeb Safari
- [ ] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

https://github.com/Expensify/App/assets/115492554/d8eb14fc-ab84-4abe-a513-0cc015e85a3c

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by izarutskaya** [comment] 2024-03-19 09:20
We think this issue might be related to the #vip-vsb.

**Comment by nkdengineer** [comment] 2024-03-19 15:19
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
- Category not auto-added for second request with same Merchant as first.
### What is the root cause of that problem?
- We do not have a logic that auto select the category in the second request.
### What changes do you think we should make in order to solve the problem?
- When we create a money request, there is a field ```recentlyUsedCategories``` which stores all the recently used category. We can implement the feature based on that fact.
- First, we need to subscribe the ```recentlyUsedCategories``` in [here](https://github.com/Expensify/App/blob/e34f10ec01a21ecddebc4b12c721705ba7bd514d/src/components/MoneyTemporaryForRefactorRequestConfirmationList.js#L988)
- Then, we can update [this](https://github.com/Expensify/App/blob/e34f10ec01a21ecddebc4b12c721705ba7bd514d/src/components/MoneyTemporaryForRefactorRequestConfirmationList.js#L496-L502) to:
```
    // Auto select the category if there is only one enabled category and it is required
    useEffect(() => {
        const enabledCategories = _.filter(policyCategories, (category) => category.enabled);
        if (iouCategory || !shouldShowCategories || (enabledCategories.length !== 1 && isEmpty(policyRecentlyUsedCategories)) || !isCategoryRequired) {
            return;
        }
        if (enabledCategories.length === 1) {
            IOU.setMoneyRequestCategory(transaction.transactionID, enabledCategories[0].name);
        } else {
            IOU.setMoneyRequestCategory(transaction.transactionID, last(enabledCategories).name);
        }
    }, [iouCategory, shouldShowCategories, policyCategories, transaction, isCategoryRequired, policyRecentlyUsedCategories]);
```

### What alternative solutions did you explore? (Optional)

**Reminder:** Please use plain English, be brief and avoid jargon. Feel free to use images, charts or pseudo-code if necessary. Do not post large multi-line diffs or write walls of text. Do not create PRs unless you have been hired for this job.

**Comment by zanyrenney** [comment] 2024-03-21 17:58
Nice, thank you @gijoe0295. Closing as behaviour is expected.

**Closed by zanyrenney** 2024-03-21 17:58 UTC
Labels: Daily, Bug
