### ISSUE TITLE
[$500] BA - When page is reloaded in any form page, "Open in app" banner turns dark mode

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#34154] opened 2024-01-09 15:26 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.23-0
**Reproducible in staging?:** Y
**Reproducible in production?:** Cannot test on prod
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** Applause - Internal Team
**Slack conversation:**

## Action Performed:
Pre-requisite: user must have New Expensify app installed and set light mode
1. Go to Settings > Workspace > Bank account
2. Start the add bank account flow
3. In any form page, reload the page

## Expected Result:
The "Open in app" banner should remain in light mode

## Actual Result:
The "Open in app" banner turns to dark mode

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [x] iOS: mWeb Safari
- [ ] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details> 

https://github.com/Expensify/App/assets/78819774/4dd2d912-db53-497c-88e1-5a52376b0147

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01b0434639aab4eb51</li>
        <li>Upwork Job ID: 1745355229456834560</li>
        <li>Last Price Increase: 2024-01-11</li>
<li>Automatic offers: </li>
<ul>
<li>ishpaul777 | Contributor | 28094255</li>
</ul></li>
    </ul>
</details>

**Comment by bondydaa** [comment] 2024-01-09 21:15
if this was caused by https://github.com/Expensify/App/pull/33200 then it's not a blocker b/c that was deployed to prod it looks like. 

I posted on on that issue to get @roryabraham and @situchan 's 👀 on it but going to remove the blocker for now.

**Comment by roryabraham** [comment] 2024-01-11 08:01
I think @ishpaul777's proposal looks good.

**Comment by bernhardoj** [comment] 2024-01-12 06:28
Pardon me, but I think there is a reason the condition is updated to

```
if (newStatusBarStyle !== statusBarStyle) { 
     updateStatusBarAppearance({statusBarStyle: newStatusBarStyle}); 
     setStatusBarStyle(newStatusBarStyle); 
 }
```

and it's because we handle the background color separately [here](https://github.com/Expensify/App/blob/b6a18b185f485cf17474c18add56359f4624b56a/src/components/CustomStatusBarAndBackground/index.tsx#L41-L52)

If we revert to prev condition, then the animation won't be visible because it will be updated immediately
(more explanation and solution below, is a bit long)

<details>

<summary>detail</summary>

The above condition is updated to only handle the `statusBarStyle` changes. For the status bar background color updates, it is handled in `useAnimatedReaction`
https://github.com/Expensify/App/blob/b6a18b185f485cf17474c18add56359f4624b56a/src/components/CustomStatusBarAndBackground/index.tsx#L41-L52

and will be triggered every time the current/prev page status bar background color is not `theme.appBG` (I guess the condition can be simplified as the prev != current). (below code runs on every navigation state change)
https://github.com/Expensify/App/blob/b6a18b185f485cf17474c18add56359f4624b56a/src/components/CustomStatusBarAndBackground/index.tsx#L91-L94

This works fine for some pages, but won't work correctly if we do a refresh in a report screen/page. The reason is that
1. The current page status bar background color for the report screen is the same as `theme.appBG`, that is `colors.productLight100`
2. The previous page status bar background color initial value is also `theme.appBG`.
https://github.com/Expensify/App/blob/b6a18b185f485cf17474c18add56359f4624b56a/src/components/CustomStatusBarAndBackground/index.tsx#L37

so the animation never runs (prev == current) and looks like the status bar background color adapts to the Splash Screen background color, which is dark (if I set the meta theme-color value in index.html, then it won't adapt to the splash background).

------
I think the real solution here is to make sure the status bar is updated at least once initially by updating both of these ref initial values to undefined.
https://github.com/Expensify/App/blob/b6a18b185f485cf17474c18add56359f4624b56a/src/components/CustomStatusBarAndBackground/index.tsx#L37-L38

So, when we check the current and previous values, it will be `undefined !== theme.anyColors` and the animation will be guaranteed to run at least once.
https://github.com/Expensify/App/blob/b6a18b185f485cf17474c18add56359f4624b56a/src/components/CustomStatusBarAndBackground/index.tsx#L88-L94

Also, add this code inside the `if` because the animation can't accept undefined values.
```
if (!prevStatusBarBackgroundColor.current) {
    prevStatusBarBackgroundColor.current = currentScreenBackgroundColor
}
```

And then guard the animation logic by returning early if it's undefined.
```
useAnimatedReaction(...,
    if (... || !prevStatusBarBackgroundColor.current || !statusBarBackgroundColor.current) return
```

However, after applying this fix, you will notice that there is an extra top space in Android and that's because on Android, the `useAnimatedReaction` always holds the initial value of the ref (undefined), so even after we update it, the value never changes inside `useAnimatedReaction`. So, `updateStatusBarAppearance` is never called. `updateStatusBarAppearance` is important for Android because it sets the status bar to translucent, so the page takes the whole height. 
https://github.com/Expensify/App/blob/b6a18b185f485cf17474c18add56359f4624b56a/src/components/CustomStatusBarAndBackground/updateStatusBarAppearance/index.android.ts#L5-L10

If you remember, the other place where `updateStatusBarAppearance` is called is when `statusBarStyle` is updated, but it suffers from the same issue, that is the initial value is the same as the new value which is handled [here](https://github.com/Expensify/App/issues/33674#issuecomment-1870717852), so it's never called.

We can wait for that issue or I personally think that setting the translucent status bar should be done separately when the component mounts because it doesn't depend on the `statusBarStyle` or `statusBarBackgroundColor`.

Thanks for reading!
</details>

**Comment by roryabraham** [comment] 2024-01-12 21:20
So after looking at the PR I decided to try and give the `CustomStatusBarAndBackground` component a more holistic review, and had some thoughts and questions. Thanks in advance for your patience as we work through this to get the component in a better state.

1. `isRootStatusBarDisabled` is a negated variable, which goes against our code style guidelines. We should change that to be `isRootStatusBarEnabled` instead.
1. `disableRootStatusBar` is a confusing function name because it can be used to either enable or disable the root status bar. We should change that to be `setRootStatusBarEnabled` instead.
1. I don't understand why `listenerCount` or `listenerId` are necessary. Can they be removed to simplify this component a bit? cc @chrispader 
1. I'm generally wary of any code like `const isFirstRender = useRef(true);`. In my experience this is usually a sign of some other problem, and is usually doesn't address the root cause. I'm not 100% sure I understand the root problem in this case, but I'd like to get to that point before addressing the solution.
1. Something @ishpaul777 said makes sense to me.

    > On initial render, we assume the prev. prevStatusBarBackgroundColor to be appBG, while, in reality, it may or may not match the expected color. For example, it could be the splash screen background color

    Could we fix this simply by updating the refs where they're declared to read the current status bar color and initialize them correctly?

**Comment by roryabraham** [comment] 2024-01-12 21:22
Removing the `Reviewing` label because I want to get these questions / thoughts sorted before proceeding further with reviews.

**Comment by chrispader** [comment] 2024-01-18 13:51
> So after looking at the PR I decided to try and give the `CustomStatusBarAndBackground` component a more holistic review, and had some thoughts and questions. Thanks in advance for your patience as we work through this to get the component in a better state.

Agree with all of the proposed changes.

> 4. I don't understand why `listenerCount` or `listenerId` are necessary. Can they be removed to simplify this component a bit? cc @chrispader

The reason for the extra `listenerId` count variable was, that the `react-navigation` library has a bug internally, where it can't keep track of the listeners, therefore, sometimes when the `useEffect` would re-render and we run `navigationRef.removeListener` the listener isn't removed and we end up with two or more. I added this `listenerId` variable which just increments each time the listener is updated.

If `listenerId` is `undefined`, it means, that `updateStatusBarStyle` was called from outside the navigation change effect, and therefore it should also execute. We removed that other occurrence, though i'd still keep this check...

**Comment by roryabraham** [comment] 2024-01-18 21:57
> Signin page has its seperate Statusbar

Let me guess – this is because we have a separate theme provider for the sign-in page... I still think that was such an unnecessary and overly-complicated decision just to force the sign-in page to always be in dark mode.

**Comment by roryabraham** [comment] 2024-01-22 22:27
Ok, I think I've lost track of the status of this issue. Reviewing my earlier comments:

> isRootStatusBarDisabled is a negated variable, which goes against our code style guidelines. We should change that to be isRootStatusBarEnabled instead.
> ...
> disableRootStatusBar is a confusing function name because it can be used to either enable or disable the root status bar. We should change that to be setRootStatusBarEnabled instead.

Seems like we have consensus on these changes, and @ishpaul777 will include it in his PR ✅ 

> Furthermore, I'm not sure I understand why we need the CustomStatusBarAndBackgroundContext at all.
> ...
> I don't understand why listenerCount or listenerId are necessary. Can they be removed to simplify this component a bit? cc @chrispader

Basically these are both needed for now. Maybe they wouldn't be if we:

- consolidated on a single theme provider
- fixed the upstream bug in react-navigation

and while both of those sound great to me, I think we should consider them out of scope for this issue ❌ 

---

So that leaves the remaining points:

> (@roryabraham) I'm generally wary of any code like const isFirstRender = useRef(true) ... Could we fix this simply by updating the refs where they're declared to read the current status bar color and initialize them correctly?
> ...
> (@ishpaul777) 

still we need to initialize the color with bootsplash color as they are assumed to be empty when initialized ... Lets just initialize the prev and current statusbarcolor refs with bootsplashcolor?

sure, sounds good. Or alternatively – initialize the status bars with `bootsplashcolor`, then initialize the refs with the current value?

I don't think it matters much - either way probably works.

let's be sure to leave comments to explain all of the points discussed here in the code. So @ishpaul777 I think it's back to you now to complete the PR:

- make the two variable name changes
- refactor the code to remove the `isFirstRender` ref
- improve comments
- anything else??

Thanks!

**Comment by chrispader** [comment] 2024-01-24 20:37
> [PR](https://github.com/Expensify/App/pull/34409) is open for review.

PR looks good to me!

**Comment by chrispader** [comment] 2024-01-24 20:41
> > Furthermore, I'm not sure I understand why we need the CustomStatusBarAndBackgroundContext at all.
> > ...
> > I don't understand why listenerCount or listenerId are necessary. Can they be removed to simplify this component a bit? cc @chrispader
> 
> Basically these are both needed for now. Maybe they wouldn't be if we:
> 
> * consolidated on a single theme provider
> * fixed the upstream bug in react-navigation
> 
> and while both of those sound great to me, I think we should consider them out of scope for this issue ❌

The reason for the additional (nested) `ThemeProvider` is, because we always want to display the `SignInPage` in dark mode, and therefore we also need to disable the "root" status bar and replace it with the nested one in dark mode.

We can definitely try to fix this bug upstream in `react-navigation`, but also considering this out-of-scope since the current solution works just fine. @roryabraham could you create a GH issue for this, so i can pick this up at some point in the future? Or have somebody from the library authors fix it... (i think we have Satya from Callstack in the project)

**Comment by roryabraham** [comment] 2024-02-16 07:35
Moving this to weekly as it's a less urgent one

**Comment by roryabraham** [comment] 2024-02-16 07:37
Looks like @parasharrajat will be back next week, and I think we can wait until then for this PR

**Comment by roryabraham** [comment] 2024-02-23 23:46
I see review activity in the last 12 hours, so review is ongoing

**Comment by roryabraham** [comment] 2024-02-26 20:42
PR merged 🚀

**Comment by abekkala** [comment] 2024-03-07 01:56
self-assigning to get payments sent now that regression period is over.

**Comment by abekkala** [comment] 2024-03-07 01:59
### PAYMENT SUMMARY: 

- Fix: @ishpaul777 [$500] [Offer Link](https://www.upwork.com/nx/wm/offer/28094255)
- PR Review: @parasharrajat [$500] - PAYMENT IN NEWDOT

**Comment by abekkala** [comment] 2024-03-07 02:00
@ishpaul777 payment sent and contract ended - thank you! 🎉

**Closed** 2024-03-07 14:12 UTC
Labels: External, Engineering, Daily, Weekly

**Comment by JmillsExpensify** [comment] 2024-05-31 03:41
$500 approved for @parasharrajat
