### ISSUE TITLE
[HOLD for payment 2023-07-12] [$1000] emojis are accepted in card name, debit card form field.

### ISSUE THREAD

**Issue by kavimuru** [Expensify/App#21255] opened 2023-06-21 19:48 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Go to settings  -> payments -> add debit card
2. Enter name with emojis on card name form field.
for eg : " John :heart::smile::smile:" .
3. Notice it doesn't throw any error.
## Expected Result:
 inconsistecny in "Legal Name" and "Card Name" form field.
i.e in legal name emojis and special characters aren't allowed. whereas card name form field doesn't check emojis.
## Actual Result:
Emojis are allowed in card name field.
## Workaround:
Can the user still use Expensify without this being fixed? Have you informed them of the workaround?

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [x] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 1.3.30-0
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation
![Screenshot 2023-06-15 at 4 35 23 PM](https://github.com/Expensify/App/assets/43996225/869e3245-b9d3-46b2-8491-4289dedb5f70)

https://github.com/Expensify/App/assets/43996225/3d01a5e5-328a-4283-a9b7-5c6a0bf9d5ec

https://github.com/Expensify/App/assets/43996225/4746dd73-b7e5-4140-bb16-957ef8bd9dd7

**Expensify/Expensify Issue URL:**
**Issue reported by:** @ashimsharma10
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1686827026457399

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~016b95ce0b884de115</li>
        <li>Upwork Job ID: 1671871155122483200</li>
        <li>Last Price Increase: 2023-06-22</li>
    </ul>
</details>

**Comment by Nikhil-Vats** [comment] 2023-06-21 20:35
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
Emojis are accepted for card name.

### What is the root cause of that problem?
We have two different functions for validating legal name and card name.

https://github.com/Expensify/App/blob/9e8a151b908447f3d79261ddb0f62d10c19b5c6e/src/libs/ValidationUtils.js#L148-L151

https://github.com/Expensify/App/blob/9e8a151b908447f3d79261ddb0f62d10c19b5c6e/src/libs/ValidationUtils.js#L376-L379

### What changes do you think we should make in order to solve the problem?
We should remove one of the functions and use the other function in both places.

### What alternative solutions did you explore? (Optional)
NA

**Comment by isabelastisser** [comment] 2023-06-23 19:53
I will be OOO until July 5, so assigning another team member. [SO](https://stackoverflowteams.com/c/expensify/questions/883) for reference.

**Comment by narefyev91** [comment] 2023-06-26 09:18
Proposal of @Nikhil-Vats looks good to me https://github.com/Expensify/App/issues/21255#issuecomment-1601634117
We should have same restriction for legal name and debit card name - and makes sense to have one regexp which will work in both areas
🎀 👀 🎀 C+ reviewed

**Comment by abekkala** [comment] 2023-06-29 15:06
@trjExpensify I'm leaving on Sabbatical and assigned as the _second person_ while Isa (Original BZ) is ooo until July 5. 

### CURRENT STATUS: 

- BZ assignee: @isabelastisser will be back on July 5 and will take this back for managing
- Issue reported by: @ashimsharma10
- C assigned to fix:  @Nikhil-Vats (just yesterday Jun 28)
- C+ to Review: @narefyev91 

Waiting on PR from nikhil-vats for narefev91 to review.

**Comment by PauloGasparSv** [comment] 2023-07-12 00:01
Not overdue, bump @narefyev91 @trjExpensify @isabelastisser

**Comment by trjExpensify** [comment] 2023-07-12 10:09
👋 @narefyev91 

>The PR that introduced the bug has been identified. Link to the PR: https://github.com/Expensify/App/pull/21880
>The offending PR has been commented on, pointing out the bug it caused and why, so the author and reviewers can learn from the mistake. Link to comment - no comments were addressed

That wasn't the PR that introduced the bug was it? 😕

**Comment by Nikhil-Vats** [comment] 2023-07-12 10:57
@narefyev91 @trjExpensify this is the [PR](https://github.com/Expensify/App/pull/6845) that introduced the bug.

**Comment by narefyev91** [comment] 2023-07-12 11:06
Yup already linked that https://github.com/Expensify/App/pull/6845

**Comment by trjExpensify** [comment] 2023-07-12 11:24
Okay cool, and did you comment on the PR for the benefit of its authors to close the feedback loop?

**Comment by trjExpensify** [comment] 2023-07-12 12:04
>A discussion in #expensify-bugs has been started about whether any other steps should be taken (e.g. updating the PR review checklist) in order to catch this type of bug sooner. Link to discussion - no discussions

On this one, I actually wonder if there's something we could be doing better to ensure emojis don't slip through the net on fields that have input restrictions. Did you consider that, such that we can potentially limit this type of bug report in the future perhaps?

>Determine if we should create a regression test for this bug - we are good with QA steps in current issue

As for this, I think we can modify the existing test script to accommodate a check for the name field in addition. I've gone ahead and created an issue for Applause for that edit. 

> **Error tests and add second debit card**
> 
> 1. Navigate to the add debit card page
> 2. Without entering any data, click on the save button
> 3. Verify all the required fields show an error informing the user of the required information
> 4. Verify all errors are related to the missing info
> 5. **On the Name field - enter an invalid name (e.g John 😄 ❤️ )**
> 6. **Verify there's an error indicating that the name can only include latin letters and numbers.**
> 7. On the Expiration date - enter a invalid date (e.g 1111)
> 8. Verify there's an error indicating the user to enter a valid date
> 9. Fill each field with random valid data
> 10. Verify the errors are removed after entering valid data on each field
> 11. Verify the error above the "Save" button is removed after fixing each field
> 12. Add a secondary debit card - For the debit card number, use any from this list [Sandbox Cards](https://rftdevportal.thebancorp.com/reference/test-sandbox-cards)

**Comment by isabelastisser** [comment] 2023-07-12 13:29
Offers sent in Upwork to @Nikhil-Vats and @ashimsharma10, please accept it and I will send the payment.

@narefyev91 I can't find you in Upwork, what's your profile?

**Comment by Nikhil-Vats** [comment] 2023-07-12 13:40
@isabelastisser offer accepted.

**Comment by isabelastisser** [comment] 2023-07-12 13:42
The payments are processed in Upwork, we should be all set!

**Closed by isabelastisser** 2023-07-12 13:42 UTC
Labels: External, Daily, Awaiting Payment, Bug
