### ISSUE TITLE
Split bill shows the amount that was written on the money request

### ISSUE THREAD

**Issue by mvtglobally** [Expensify/App#24190] opened 2023-08-07 02:52 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1-Click plus sign
2-Open Request money
3-Write a number and click Next button
4-Exit money request and click plus sign
5-Open Split bill

## Expected Result:
You must not show the amount written in the application money

## Actual Result:
show the amount written in the application money

## Workaround:
Can the user still use Expensify without this being fixed? Have you informed them of the workaround?

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [X] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 1.3.48-0
**Reproducible in staging?:** Y 
**Reproducible in production?:** Y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation 

https://github.com/Expensify/App/assets/43995119/f237741b-063f-457e-ad71-adb7613c083a

**Expensify/Expensify Issue URL:**
**Issue reported by:** @Mauri-salazar
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1690831967289789

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by mvtglobally** [comment] 2023-08-07 02:53
@johncschuster  Can you also check https://expensify.slack.com/archives/C049HHMV9SM/p1690833474135769 if this is same issue or is we should log separately

**Comment by Victor-Nyagudi** [comment] 2023-08-07 10:25
I can't reproduce this either despite even switching to the currency in the video and clicking on the same areas.

**Comment by johncschuster** [comment] 2023-08-08 20:52
@mvtglobally Thanks for flagging that. It looks like the same behavior to me.

**Comment by johncschuster** [comment] 2023-08-08 20:55
That said, it looks like @Mauri-salazar the behavior both times.

**Comment by johncschuster** [comment] 2023-08-14 22:01
@Mauri-salazar bump!

**Comment by johncschuster** [comment] 2023-08-14 22:01
I'm going to close this until we can reproduce it.

**Closed by johncschuster** 2023-08-14 22:01 UTC
Labels: Daily, Needs Reproduction, Bug
