### ISSUE TITLE
[HOLD for payment 2023-07-12] [$1000] Web - Chat - Flagged attachment are collapsed when reacted with emojis

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#20810] opened 2023-06-15 12:15 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Login with user A and go to a chat with user B
2. Send an attachment ( picture/pdf) to user B
3. On user B, first flag the attachment as bullying. Next, ( this is an important step) click on the reveal message. Now react with any emojis
4. Notice the attachment is now hidden.

## Expected Result:
Flagged attachment should not be  collapsed when reacted with emojis

## Actual Result:
Flagged attachments are collapsed when reacted with emojis

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [ ] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 1.3.27.6

**Reproducible in staging?:** yes

**Reproducible in production?:** yes

**If this was caught during regression testing, add the test name, ID and link from TestRail:**

**Email or phone of affected tester (no customers):**

**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/93399543/1e742059-34c7-4b9b-b07e-078c71cd06ce

https://github.com/Expensify/App/assets/93399543/83b083f8-5a9d-445f-939c-12f09f12c7f9

**Expensify/Expensify Issue URL:**

**Issue reported by:** @ashimsharma10

**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1686217468053799

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~0192768e5414216425</li>
        <li>Upwork Job ID: 1670794643847507968</li>
        <li>Last Price Increase: 2023-06-19</li>
    </ul>
</details>

**Comment by muttmuure** [comment] 2023-06-19 13:40
I've been trying to reproduce this but I'm seeing that the message isn't being hidden at all

**Comment by muttmuure** [comment] 2023-06-19 14:02
OK yep this is reproducible

**Comment by s-alves10** [comment] 2023-06-19 15:16
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
Flagged attachment is hidden when reacting with emojis

### What is the root cause of that problem?

When latest decision is `pendingHide`, we hide the action here
https://github.com/Expensify/App/blob/b997868d39d758edbbbc9eb799bf18fab471e2f4/src/pages/home/report/ReportActionItem.js#L146C46-L148

I think this should be fixed in the backend, but we can remove the `pendingHide` condition as follows

```
        if (latestDecision.decision === CONST.MODERATION.MODERATOR_DECISION_HIDDEN) {
            setIsHidden(true);
        }
```

This solves the issue.

### What changes do you think we should make in order to solve the problem?

Remove the `this.props.isSmallScreenWidth` checking

```
        if (!this.emojiSearchInput || this.props.isSmallScreenWidth) {
            return;
        }
```

This works as expected

### What alternative solutions did you explore? (Optional)

**Comment by mollfpr** [comment] 2023-06-20 13:55
Thanks for the proposal @s-alves10 

Could you elaborate on what backend should be fixed and the changes to solve this to remove the `pendingHide` and `this.props.isSmallScreenWidth` for the check?

Why `this.props.isSmallScreenWidth` fix this issue, while the issue is not only on the small screen?

**Comment by s-alves10** [comment] 2023-06-20 15:00
@mollfpr 

This issue was fixed by this commit https://github.com/Expensify/App/commit/e44d21194de4077cc161762d5cd173263d7fba90

**Comment by mollfpr** [comment] 2023-06-21 13:01
@s-alves10 I am still able to reproduce it in staging.



https://github.com/Expensify/App/assets/25520267/1604d81e-6c15-491b-8f76-1b32f0be92e4

**Comment by s-alves10** [comment] 2023-06-21 13:04
@mollfpr 

Please check it on main branch. Maybe it was not deployed yet

**Comment by s-alves10** [comment] 2023-06-21 13:35
Let me check. I'll update you soon

**Comment by s-alves10** [comment] 2023-06-21 16:11
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
Flagged attachment is hidden when reacting with emojis

### What is the root cause of that problem?

We're now setting `isHidden` flag when latest moderation decision is `pendingHide` or `hidden`. This is correct. The problem is when this effect is called.
https://github.com/Expensify/App/blob/0b7455fa832b53eccb99ca23c70e131b3464fb1d/src/pages/home/report/ReportActionItem.js#L163-L165

As you can see above, we now call the effect when `actionName` or `moderationDecisions` changes, but `moderationDecisions` is an array(reference) and can change anytime. So this effect is called even when no moderationDecisions is changed. This is the root cause

### What changes do you think we should make in order to solve the problem?

We're interested in the value of `moderationDecisions[0].decision`. We should change the dependency of the effect.
Change the `useEffect` code block as follows
```
    const latestDecision = _.get(props, ['action', 'message', 0, 'moderationDecisions', 0, 'decision'], '');
    useEffect(() => {
        if (!props.action.actionName === CONST.REPORT.ACTIONS.TYPE.ADDCOMMENT || _.isEmpty(latestDecision)) {
            return;
        }

        if (latestDecision === CONST.MODERATION.MODERATOR_DECISION_PENDING_HIDE || latestDecision === CONST.MODERATION.MODERATOR_DECISION_HIDDEN) {
            setIsHidden(true);
        }
        setModerationDecision(latestDecision);

    }, [latestDecision, props.action.actionName]);
```

This works as expected

### What alternative solutions did you explore? (Optional)

**Comment by mollfpr** [comment] 2023-06-23 13:48
Thanks @s-alves10 for the proposal. @muttmuure The proposal looks good to me 👍


🎀 👀 🎀 C+ reviewed!

**Comment by tylerkaraszewski** [comment] 2023-06-28 19:46
Assigned.

**Comment by s-alves10** [comment] 2023-06-28 20:26
@mollfpr 

[PR](https://github.com/Expensify/App/pull/21836) is ready for review

**Comment by tylerkaraszewski** [comment] 2023-06-30 16:06
PR is merged.

**Comment by tylerkaraszewski** [comment] 2023-06-30 16:57
@muttmuure - I am leaving on sabbatical today. I don't expect this issue to need any further engineering input, but if it does, please unassign me and re-apply the `Engineering` label to get a new engineer to finish this issue, as I'll be out until the end of August.

**Comment by muttmuure** [comment] 2023-07-03 13:54
Waiting for PR to push to prod

**Comment by ashimsharma10** [comment] 2023-07-12 10:26
Updates on this?

**Comment by mollfpr** [comment] 2023-07-12 15:50
> [@mollfpr] The PR that introduced the bug has been identified. Link to the PR:

https://github.com/Expensify/App/pull/19476

> [@mollfpr] The offending PR has been commented on, pointing out the bug it caused and why, so the author and reviewers can learn from the mistake. Link to comment:

https://github.com/Expensify/App/pull/19476/files#r1261372039

> [@mollfpr] A discussion in #expensify-bugs has been started about whether any other steps should be taken (e.g. updating the PR review checklist) in order to catch this type of bug sooner. Link to discussion:

I think the regression step should be enough. The reviewer will watch a `useEffect` dependency where it's already documented that we should reference the correct value for its change.

> [@mollfpr] Determine if we should create a regression test for this bug.
 [@mollfpr] If we decide to create a [regression test](https://github.com/Expensify/App/blob/main/contributingGuides/REGRESSION_TEST_BEST_PRACTICES.md) for the bug, please propose the regression test steps to ensure the same bug will not reach production again.

1. Login with users A and B on 2 devices
2. **A**: Send an attachment(picture or pdf) to user **B**
3. **B**: Flag the attachment as bullying
4. **B**: Click on the revealed message to see the attachment
5. **B**: React with any emojis
6. Verify that the attachment is not hidden
7. 👍 or 👎

**Comment by s-alves10** [comment] 2023-07-13 18:46
I'm sorry but I wasn't able to accept the offer.

**Comment by mollfpr** [comment] 2023-07-14 04:29
Friendly bump @muttmuure

**Comment by muttmuure** [comment] 2023-07-17 13:52
@mollfpr invited

@ashimsharma10 can you link your upwork profile, we have two Ashim S's in Upwork

**Comment by mollfpr** [comment] 2023-07-17 13:54
@muttmuure Applied, thank you!

**Comment by muttmuure** [comment] 2023-07-17 14:11
Offer sent

**Comment by ashimsharma10** [comment] 2023-07-17 16:46
@muttmuure  This is my upwork https://www.upwork.com/freelancers/~018a92cf13e1e88eed

**Comment by s-alves10** [comment] 2023-07-18 23:04
@muttmuure 

I'm contacting you to know when can I get paid for this issue

**Comment by mollfpr** [comment] 2023-07-20 13:37
Friendly bump @muttmuure

**Comment by muttmuure** [comment] 2023-07-20 17:16
@ashimsharma10 invited

**Comment by muttmuure** [comment] 2023-07-20 17:21
@mollfpr paid

**Comment by muttmuure** [comment] 2023-07-20 17:28
@s-alves10 paid

**Comment by ashimsharma10** [comment] 2023-07-21 08:23
@muttmuure Accepted invitation. waiting for payment

**Comment by muttmuure** [comment] 2023-07-21 10:51
Offer sent

**Comment by muttmuure** [comment] 2023-07-23 22:43
@ashimsharma10 paid, test rail proposal created.

**Closed by muttmuure** 2023-07-23 22:43 UTC
Labels: External, Daily, Overdue, Awaiting Payment, Bug
