### ISSUE TITLE
[$125] [Search v1.2] - Hold expense modal appears on the top left when expense is held in Search

### ISSUE THREAD

**Issue by IuliiaHerets** [Expensify/App#49275] opened 2024-09-16 14:37 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 9.0.35-0
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**Email or phone of affected tester (no customers):** applausetester+kh010901@applause.expensifail.com
**Issue reported by:** Applause Internal Team

## Action Performed:
1. Go to staging.new.expensify.com
2. Go to DM.
3. Submit two expenses.
4. Go to Search.
5. Click on the submitted expense.
6. Click on the header > Hold.
7. Enter reason and save it.

## Expected Result:
Hold expense modal will open as RHP.

## Actual Result:
Hold expense modal appears on the top left when expense is held in Search.

## Workaround:
Unknown

## Platforms:

- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos
<img width="1440" alt="Bug6604298_1726402698827!Screenshot_2024-09-15_at_20 14 25" src="https://github.com/user-attachments/assets/0256cd9b-89bf-4fdc-a713-37dfdaa0b7e4">

https://github.com/user-attachments/assets/bcaf246b-fb4c-40f8-89da-d4f12bc4be8f

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~021835782276333225172</li>
        <li>Upwork Job ID: 1835782276333225172</li>
        <li>Last Price Increase: 2024-09-23</li>
<li>Automatic offers: </li>
<ul>
<li>rojiphil | Reviewer | 104106001</li>
<li>Krishna2323 | Contributor | 104106003</li>
</ul></li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @rojiphil</details>

**Comment by IuliiaHerets** [comment] 2024-09-16 14:37
@sakluger  FYI I haven't added the External label as I wasn't 100% sure about this issue. Please take a look and add the label if you agree it's a bug and can be handled by external contributors

**Comment by nkdengineer** [comment] 2024-09-16 15:33
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
Hold expense modal appears on the top left when expense is held in Search.

### What is the root cause of that problem?

In [here](https://github.com/Expensify/App/blob/d860f2d0ffb31c478d9400bab1df18022a14a0b5/src/pages/home/ReportScreen.tsx#L359) we are passing down the prop `shouldUseNarrowLayout`, and in web screen, its value will be `true` when we are in RHP on the Search page [logic here](https://github.com/Expensify/App/blob/84793c85836be656255230985dc68e12e37d6268/src/hooks/useResponsiveLayout/index.ts#L68). As a result, it will show this popover instead of redirecting to the route `PROCESS_MONEY_REQUEST_HOLD`.

https://github.com/Expensify/App/blob/84793c85836be656255230985dc68e12e37d6268/src/components/MoneyReportHeader.tsx#L255-L262

### What changes do you think we should make in order to solve the problem?


We should pass `isSmallScreenWidth` instead of `shouldUseNarrowLayout` in this case like we did [here](https://github.com/Expensify/App/blob/8e3821c3508877ac0045b040ed6b0d595a693d68/src/components/PopoverMenu.tsx#L134-L135) and [here](https://github.com/Expensify/App/blob/8e3821c3508877ac0045b040ed6b0d595a693d68/src/components/ProcessMoneyReportHoldMenu.tsx#L59-L60). And do the same  with `MoneyRequestHeader`

```
          <MoneyReportHeader
              report={report}
              policy={policy}
              transactionThreadReportID={transactionThreadReportID}
              reportActions={reportActions}
              shouldUseNarrowLayout={isSmallScreenWidth}
              onBackButtonPress={onBackButtonPress}
          />
```

https://github.com/Expensify/App/blob/84793c85836be656255230985dc68e12e37d6268/src/hooks/useResponsiveLayout/index.ts#L68

### What alternative solutions did you explore? (Optional)
NA


https://github.com/user-attachments/assets/2f365f40-ad45-4d92-a88f-a286b77eb5c6

**Comment by sakluger** [comment] 2024-09-16 20:46
This feels like a fairly minor issue and change, so I will set the price at $125. Feel free to leave a note if you disagree.

**Comment by sakluger** [comment] 2024-09-19 16:31
@luacmartins will you be fixing this one yourself? If so, we can remove the help wanted and external labels.

**Comment by rojiphil** [comment] 2024-09-23 18:36
Thanks for the proposals.

@Krishna2323 I have a couple of questions for you:

> We also need to update the shouldUseNarrowLayout in the useEffect in both components.

What code changes are you suggesting here and what would be the benefit of making these changes?

>	•	In MoneyReportHeader & MoneyRequestHeader we should get isSmallScreenWidth from useResponsiveLayout hook and use that instead of shouldUseNarrowLayout.

> passing isSmallScreenWidth to shouldUseNarrowLayout will cause issues as it is being also used for showing back button and money request buttons according to the IOU report layout size.

Both the above statements seem to contradict to each other. Are you not suggesting to pass `isSmallScreenWidth` to `shouldUseNarrowLayout`?

**Comment by rojiphil** [comment] 2024-09-23 19:08
@Krishna2323 
> instead we should get `isSmallScreenWidth` from `useResponsiveLayout` hook directly in MoneyReportHeader`&`MoneyRequestHeader ` and use that to show the modal.

Hmm.. Isn’t this what @nkdengineer proposed earlier?

> You can check [this PR](https://github.com/Expensify/App/pull/46788/files), I think the author of the PR mistakenly replaced isSmallScreenWidth  with shouldUseNarrowLayout . We should also look for similar cases in these changed files.

Ah! I see. So, you are referring to replacing `shouldUseNarrowLayout` with `isSmallScreenWidth`. But what additional value does it bring since the proposal already includes assigning `isSmallScreenWidth` to `shouldUseNarrowLayout`?

**Comment by rojiphil** [comment] 2024-09-24 08:08
Thanks. I get what you are saying now. I also think it is better to use `isSmallScreenWidth` from `useResponsiveLayout` hook directly in `MoneyReportHeader` & `MoneyRequestHeader` and fix the navigation issue here. 
@Krishna2323 [proposal](https://github.com/Expensify/App/issues/49275#issuecomment-2353328107) LGTM.
🎀👀🎀 C+ reviewed

**Comment by sakluger** [comment] 2024-09-26 20:27
@Krishna2323 do you have a PR for this one yet?

**Comment by sakluger** [comment] 2024-09-27 16:39
Bump @Krishna2323.

**Comment by rojiphil** [comment] 2024-09-29 17:31
> this issue has been fixed in [this PR](https://github.com/Expensify/App/pull/47990)

Oh! Then, let's close this issue and move on. cc @sakluger

**Closed** 2024-09-30 14:30 UTC
Labels: External, Daily, Bug
