### ISSUE TITLE
New Group/1:1 Chat - No focus in the input field after create a new group

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#11521] opened 2022-10-02 18:07 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Open the App
2. Login with any account
3. Click on FAB button/New Group
4. Select 2 or more users -> Create Group
5. Check that you are redirected to the New Group page

## Expected Result:
The focus should be in the input field

## Actual Result:
No focus in the input field

## Workaround:
Unknown

## Platform:

Where is this issue occurring?

- Web
- iOS
- Android
- Desktop App
- Mobile Web

**Version Number:** 1.2.11.1

**Reproducible in staging?:** Yes

**Reproducible in production?:** Yes

**Email or phone of affected tester (no customers):** any

**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Notes/Photos/Videos:** Any additional supporting documentation

https://user-images.githubusercontent.com/93399543/193469108-d1bb7ee1-319a-4c10-b8b7-21326609b35e.mp4

**Expensify/Expensify Issue URL:** 

**Issue reported by:** Applause - Internal Team

**Slack conversation:** 

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by flodnv** [comment] 2022-10-03 11:48
@Christinadobrzyn does this make sense to you? I think maybe but I'm a bit indifferent.

**Comment by Christinadobrzyn** [comment] 2022-10-04 02:16
- I can't reproduce this on the web app

![2022-10-04_09-55-12 (2)](https://user-images.githubusercontent.com/51066321/193719117-c3381359-bcef-47f3-96cc-4ee14c05935f.gif)

- There are several open GHs about focus on the mobile app (although not this issue specifically) 

https://github.com/Expensify/App/issues/10414
https://github.com/Expensify/App/issues/11507

I think we can close this and come back to it if it still exists after some of these other updates?

**Closed** 2022-10-04 03:51 UTC
Labels: Engineering, Daily
