### ISSUE TITLE
[$500]  the announcement in  admin room in Account A doesn't update  if Default name Changed in Account B

### ISSUE THREAD

**Issue by kavimuru** [Expensify/App#26342] opened 2023-08-30 20:47 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Log in to Account A and navigate to Settings > Workspace to create a new workspace if one does not exist.
2. Go to Members and add Account B to the workspace.
3. Click on the three dots and select admin room.
4. Observe that the notification is displayed in the admin room.
5. Log in to Account B, go to Settings > Profile, and change the Default name.
6. Go back to Account A and observe that the name is updated in other rooms but not in the notification.
## Expected Result: 
The announcement in the admin room of Account A should update when the Default name is changed in Account B.
## Actual Result: 
The announcement in the admin room of Account A does not update when the Default name is changed in Account B.

## Workaround:
Can the user still use Expensify without this being fixed? Have you informed them of the workaround?

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [x] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 1.3.59-1
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/43996225/e3506ea7-10d1-45c8-8720-d36cc7ac0d02

https://github.com/Expensify/App/assets/43996225/0f7350a7-5734-42e6-a764-9a0ea026c8b8

**Expensify/Expensify Issue URL:**
**Issue reported by:** @tewodrosGirmaA
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1692626940962509

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~0154a6a27f53b9f820</li>
        <li>Upwork Job ID: 1697243756716425216</li>
        <li>Last Price Increase: 2023-09-07</li>
    </ul>
</details>

**Comment by laurenreidexpensify** [comment] 2023-09-04 10:12
bump for review @situchan ^^

**Comment by situchan** [comment] 2023-09-07 16:26
I don't think this is BE issue. Awaiting proposals

**Comment by paultsimura** [comment] 2023-09-08 10:12
## Proposal

Updated proposal https://github.com/Expensify/App/issues/26342#issuecomment-1701301448

**Comment by laurenreidexpensify** [comment] 2023-09-12 09:50
@situchan a few proposals to review above ^^

**Comment by situchan** [comment] 2023-09-14 10:50
@hoangzinh thanks for the proposal. We cannot use `originalMessage` data. It's not updated whenever user updates info.

**Comment by situchan** [comment] 2023-09-14 10:57
Now that we customize system message, we should support localization on both LHN last message and chat message, similar to [IOU preview message](https://github.com/Expensify/App/blob/6764fd1b0cc45469d102a22175b552e56f42e456/src/libs/ReportUtils.js#L1423).

Before moving forward, I'd like to confirm with engineer if this is worth fixing so that we don't waste time.
🎀 👀 🎀 C+ reviewed

**Comment by situchan** [comment] 2023-09-14 11:05
<img width="1264" alt="Screenshot 2023-09-14 at 4 59 37 PM" src="https://github.com/Expensify/App/assets/108292595/0772264e-8929-447d-a57a-c71357b7c056">

@yuwenmemon thanks for being assigned here.
Should we customize this system message in frontend so that it dynamically changes (also applies same to LHN last message) when
- invitee updates their display name
- user update language to Spanish?

So far system message customization is only applied to IOU preview messages, attachments and modified expense actions.
https://github.com/Expensify/App/blob/6764fd1b0cc45469d102a22175b552e56f42e456/src/libs/OptionsListUtils.js#L387

**Comment by yuwenmemon** [comment] 2023-09-14 16:46
Ah no that is by design. Essentially a log stays a "log" of what the data was at the time.

**Comment by situchan** [comment] 2023-09-14 16:47
> Ah no that is by design. Essentially a log stays a "log" of what the data was at the time.

Ah ok, what about localization?

**Comment by yuwenmemon** [comment] 2023-09-14 16:48
We're not going to support localization for change logs for now neither, no.

**Comment by situchan** [comment] 2023-09-14 16:49
oh ok, we can close this then

**Comment by yuwenmemon** [comment] 2023-09-14 16:49
AKA - we can close this issue 🙂

**Closed** 2023-09-14 16:49 UTC
Labels: External, Daily, Help Wanted, Bug
