### ISSUE TITLE
[HOLD for payment 2024-01-17] [$500] mWeb - Room - The invited users email id is not fully visible in room chat page

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#33305] opened 2023-12-19 17:17 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.14
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** Applause - Internal Team
**Slack conversation:**

## Action Performed:
1. Go to https://staging.new.expensify.com/
2. Tap on a room chat
3. Tap on room header
4. Tap on members---- Invite
5. Invite 2 members with long email id

## Expected Result:
The invited users email id must be fully visible in room chat page

## Actual Result:
The invited users email id is not fully visible in room chat page

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [x] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [ ] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details> 

https://github.com/Expensify/App/assets/78819774/88136130-22fa-4bd5-8b24-5404b6652bc0

https://github.com/Expensify/App/assets/78819774/90e2c610-7441-45ef-83ea-18f2fabf967c

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01118481c486c1f575</li>
        <li>Upwork Job ID: 1737160340105293824</li>
        <li>Last Price Increase: 2024-01-02</li>
<li>Automatic offers: </li>
<ul>
<li>jjcoffee | Reviewer | 28077803</li>
<li>bernhardoj | Contributor | 28077804</li>
</ul></li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @muttmuure</details>

**Comment by yh-0218** [comment] 2023-12-19 18:11
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
The long invited message is out of screen.
### What is the root cause of that problem?
We display text using `RenderCommentHTML` [here](https://github.com/Expensify/App/blob/aa1d87caddb6831061f3750bd78f77b42603e5e3/src/pages/home/report/comment/TextCommentFragment.js#L68)
### What changes do you think we should make in order to solve the problem?
I think we need same logic between "workspace added message" and "room invite message".
For this we need to remove codes.
https://github.com/Expensify/App/blob/aa1d87caddb6831061f3750bd78f77b42603e5e3/src/pages/home/report/ReportActionItemMessage.js#L44-L57


### What alternative solutions did you explore? (Optional)

**Comment by samilabud** [comment] 2023-12-19 18:25
It looks like this is intentional because this has a tooltip to view the entire mail:

<img width="375" alt="image" src="https://github.com/Expensify/App/assets/5216036/cb630dd9-7ca4-442f-b801-316e6394778d">

But if not, here is my proposal:

## Proposal

### Please re-state the problem that we are trying to solve in this issue.
mWeb - Room - The invited users email id is not fully visible in room chat page

### What is the root cause of that problem?
The content of the account/email text is shorter than the container and we are specifying the max line number of 1, the content will never break the line due to this [pre style](https://github.com/Expensify/App/blob/c0313c2246608ac095488d0916cd2a22ea5bd610/src/components/SelectionList/BaseListItem.js) and the next below:

https://github.com/Expensify/App/blob/ab4279b5459916416595ba305e04066a1ba64254/src/components/SelectionList/UserListItem.js#L40

### What changes do you think we should make in order to solve the problem?
We can switch the [numberOfLines](https://github.com/Expensify/App/blob/ab4279b5459916416595ba305e04066a1ba64254/src/components/SelectionList/UserListItem.js#L40) props to change it by 2 when the mouse enters and leave like:
```
const [alterTextNumberOfLines, setAlterTextNumberOfLines] = useState(1);
.
.
.
   <Text
        style={alternateTextStyles}
        numberOfLines={alterTextNumberOfLines}
        onMouseEnter={() => setAlterTextNumberOfLines(2)}
        onMouseLeave={() => setAlterTextNumberOfLines(1)}
    >
        {item.alternateText}
    </Text>
```
Also, we should remove the unnecessary prop in:
https://github.com/Expensify/App/blob/c0313c2246608ac095488d0916cd2a22ea5bd610/src/components/SelectionList/BaseListItem.js#L93

**Result:**


https://github.com/Expensify/App/assets/5216036/c5363828-3847-4760-8612-6a6ff5e7e6be

**Comment by jjcoffee** [comment] 2024-01-02 14:59
Reviewing today!

**Comment by jjcoffee** [comment] 2024-01-02 16:18
I'm inclined to go with @bernhardoj's [proposal](https://github.com/Expensify/App/issues/33305#issuecomment-1863198343) as the email is styled as a mention and we already wrap mentions in normal messages:

![image](https://github.com/Expensify/App/assets/27287420/791a2506-3b44-49a5-ada8-612bcce59c99)

I don't think in this case we would want to apply it as a general style for `BaseHTMLEngineProvider` as in @Krishna2323's [proposal](https://github.com/Expensify/App/issues/33305#issuecomment-1863285720), as it could cause unexpected results.

:ribbon::eyes::ribbon: C+ reviewed

**Comment by dangrous** [comment] 2024-01-02 20:28
Yeah I think that's fine! My only note would be to double check those other styles added in `chatItemMessage` don't change the display other than wrapping, but I don't think they will.

Assigning!

**Comment by bernhardoj** [comment] 2024-01-03 04:39
PR is ready

cc: @jjcoffee

**Comment by dangrous** [comment] 2024-01-17 16:20
@jjcoffee I think we're ready to get the checklist updated and close this out!

**Comment by jjcoffee** [comment] 2024-01-17 16:36
- The PR that introduced the bug has been identified. Link to the PR: https://github.com/Expensify/App/pull/30927/
- The offending PR has been commented on, pointing out the bug it caused and why, so the author and reviewers can learn from the mistake. Link to comment: https://github.com/Expensify/App/pull/30927/files#r1456022482
- A discussion in #expensify-bugs has been started about whether any other steps should be taken (e.g. updating the PR review checklist) in order to catch this type of bug sooner. Link to discussion: **N/A - just needed more thorough testing**
- Determine if we should create a regression test for this bug. **Yes**
- If we decide to create a [regression test](https://github.com/Expensify/App/blob/main/contributingGuides/REGRESSION_TEST_BEST_PRACTICES.md) for the bug, please propose the regression test steps to ensure the same bug will not reach production again.

**Regression Test Proposal**

1. Open any room chat
2. Invite 2 users with a very long email
3. Verify you can see the whole invited message and that the long email text wraps, rather than overflowing the screen

Do we agree 👍 or 👎

**Comment by dangrous** [comment] 2024-01-17 19:44
Looks good! One tiny edit, just for clarity:

2. Invite 2 users with very long email addresses (+50 characters)

**Comment by jjcoffee** [comment] 2024-01-25 09:49
@muttmuure Friendly bump for payment! :bow:

**Comment by muttmuure** [comment] 2024-01-26 14:13
Oops, sorry!

All paid up

**Closed by muttmuure** 2024-01-26 14:13 UTC
Labels: External, Daily, Awaiting Payment, Bug
