### ISSUE TITLE
[$250] NetSuite - Sometimes the "last synced" text is missing the actual time data

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#46228] opened 2024-07-25 20:11 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 9.0.12-0
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**If this was caught during regression testing, add the test name, ID and link from TestRail:** [N/A](https://expensify.testrail.io/index.php?/tests/view/4767874&group_by=cases:section_id&group_id=314239&group_order=asc)
**Issue reported by:** Applause - Internal Team

## Action Performed:
1. Navigate to https://staging.new.expensify.com/
2. Log in with a new expensifail account
3. Click on FAB - New workspace
4. Enable "Accounting" in the "More features" page.
5. Navigate to "Accounting"
6. Connect to NetSuite and upgrade the workspace to Control when asked
7. Wait for the sync to finish

## Expected Result:
It should be showing "Last synced X minutes ago"

## Actual Result:
Sometimes the "last synced" text is missing the actual time data. It can occur then the connection is made to NetSuite or if a setting is changed that forces a sync

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details> 

https://github.com/user-attachments/assets/bb28f1c5-ff5a-4ebb-bdd2-2dcc0e86eb78

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01e16d825f11c5924c</li>
        <li>Upwork Job ID: 1818663718833083769</li>
        <li>Last Price Increase: 2024-08-07</li>
    </ul>
</details>

**Comment by lanitochka17** [comment] 2024-07-25 20:12
@greg-schroeder  FYI I haven't added the External label as I wasn't 100% sure about this issue. Please take a look and add the label if you agree it's a bug and can be handled by external contributors

**Comment by NJ-2020** [comment] 2024-08-04 02:09
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
NetSuite - Sometimes the "last synced" text is missing the actual time data
### What is the root cause of that problem?
On PolicyAccountingPage, we do not handle the if we get an error
![image](https://github.com/user-attachments/assets/30a38844-9ff4-42c9-a979-962e4f34bcd6)
https://github.com/Expensify/App/blob/459759d55963091c708d7271c29e0f95f3add658/src/pages/workspace/accounting/PolicyAccountingPage.tsx#L214
https://github.com/Expensify/App/blob/459759d55963091c708d7271c29e0f95f3add658/src/pages/workspace/accounting/PolicyAccountingPage.tsx#L229-L232
https://github.com/Expensify/App/blob/459759d55963091c708d7271c29e0f95f3add658/src/pages/workspace/accounting/PolicyAccountingPage.tsx#L363-L364

### What changes do you think we should make in order to solve the problem?
We can create a new variable for lastSynced date if  response is error `.lastErrorSyncedData`, and use this variable if the connection is error and use the `successfulDate` variable if the connection is success

Or we can make it in one variable checking if error we can use the `lastErrorSyncedData` and if success we can use the `successfulDate` variable
### What alternative solutions did you explore? (Optional)

**Comment by greg-schroeder** [comment] 2024-08-05 13:46
Go away melvin

**Comment by alitoshmatov** [comment] 2024-08-09 03:20
Requested access to Netsuite in [slack](https://expensify.slack.com/archives/C02NK2DQWUX/p1723173622595259?thread_ts=1722928262.349749&cid=C02NK2DQWUX).

**Comment by greg-schroeder** [comment] 2024-08-13 16:13
Okay - adjusting to `Internal`

**Comment by NJ-2020** [comment] 2024-08-21 06:44
Is the issue has been fixed in BE?
The issue still reproducible if I provide with invalid credentials
![Screenshot 2024-08-20 at 23 43 12](https://github.com/user-attachments/assets/745b9656-0b57-4933-b94a-5301b029baa9)

cc: @greg-schroeder

**Comment by greg-schroeder** [comment] 2024-08-27 05:33
Hmm - @yuwenmemon I see [your PR ](https://github.com/Expensify/Integration-Server/pull/8059) was deployed and is due to resolve the phantom "last synced" issue. But that looks slightly different than what's been pointed out [here](https://github.com/Expensify/App/issues/46228#issuecomment-2301257607)... this has a failed connection instead of a successful one.

Would you consider that a separate issue?

**Comment by yuwenmemon** [comment] 2024-08-27 17:11
Yep, we're going to be tackling that here: https://github.com/Expensify/App/issues/47493

**Comment by mvtglobally** [comment] 2024-09-09 04:09
Issue not reproducible during KI retests. (First week)

**Comment by greg-schroeder** [comment] 2024-09-09 06:24
Okay, so the issue brought up in this issue was fixed, then, and the other thing that was mentioned is being fixed elsewhere. Closing then.

**Closed by greg-schroeder** 2024-09-09 06:24 UTC
Labels: Reviewing, Daily, Internal, Help Wanted, Bug
