### ISSUE TITLE
Chat - PDF preview is not displayed.

### ISSUE THREAD

**Issue by kavimuru** [Expensify/App#13665] opened 2022-12-16 18:06 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Open chat with other user
2. Click in + icon and select "Add attachment"
3. Select any PDF file and click in Open,

## Expected Result:
A preview of the PDF is displayed before uploading to the conversation.

## Actual Result:
Failed to load PDF file message occurs.

## Workaround:
unknown

## Platform:

Where is this issue occurring?

- Web
- mWeb

**Version Number:** 1.2.41-1
**Reproducible in staging?:** y
**Reproducible in production?:** n
**Email or phone of affected tester (no customers):** 
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** 
![Bug5866652_PDF_error](https://user-images.githubusercontent.com/43996225/208161112-26cc402a-7b94-49e2-a038-125dd4bd742b.png)

https://user-images.githubusercontent.com/43996225/208161113-41b624d6-592b-46ae-961a-c5bd5e526e53.mp4

**Expensify/Expensify Issue URL:** 
**Issue reported by:** Applasue internal team
**Slack conversation:** 

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by abekkala** [comment] 2022-12-16 19:34
@roryabraham Is there something from me (on the BZ team member side) that I need to do here?
I've never gotten a deploy blocker/hourly issue before

**Comment by roryabraham** [comment] 2022-12-17 06:04
Whoops, sorry I missed this.

> @roryabraham Is there something from me (on the BZ team member side) that I need to do here?

We'll need to complete the BugZero checklist when the issue is complete, but nothing else to do for now since DeployBlockers should not go external unless we consciously decide to make a special exception. By default DeployBlockers are internal.

**Comment by roryabraham** [comment] 2022-12-17 06:06
Seems like this problem is related to the CSP:

<img width="1792" alt="image" src="https://user-images.githubusercontent.com/47436092/208228009-8e4edc2e-9533-4336-a8c5-645367a1935e.png">

**Comment by roryabraham** [comment] 2022-12-17 06:14
This DeployBlocker was caused by https://github.com/Expensify/App/pull/13546, but in this case there's really no way @marcaaron or anyone else could've detected this on dev without having impressive foresight, because [the CloudFlare worker that defines our CSP cannot be tested on dev (yet)](https://expensify.slack.com/archives/CC7NECV4L/p1670264158167419).

Anyways, this should hopefully be pretty easy to sort out, but will not be possible to test locally.

**Comment by roryabraham** [comment] 2022-12-17 06:28
Okay, actually this is a bit of a can of worms. According to [this resource](https://www.w3.org/TR/CSP2/#source-list-guid-matching):

> special URL schemes that refer to specific pieces of unique content, such as ... "blob:" ... are excluded from matching a policy of * and must be explicitly listed. Policy authors should note that the content of such URLs is often derived from a response body or execution in a Document context, which may be unsafe. ... allowing "blob:" or "filesystem:" URLs is equivalent to unsafe-eval.

I'm reading this to mean that adding `worker-src: blob:` to the CSP to fix this problem would be unsafe, and we might need to figure out a more clever way to allow this in the CSP.

**Comment by roryabraham** [comment] 2022-12-17 06:52
I think technically the `blob:` represents raw binary data that exists on the user's machine in their browser's memory (i.e the PDF we want to view offline in this case). However, I don't know if it's safe to spawn a worker from that raw binary data or not. I haven't been able to find any clear guidance about this and I'm not sure what to do 😕

**Comment by marcaaron** [comment] 2022-12-19 21:31
Just updating this with the convo from [this thread](https://expensify.slack.com/archives/C01GTK53T8Q/p1671470284311359). The `blob:` in question comes from our own source and not provided by the user. I think for a plan of action we should:

- Revert the problematic PR
- Start a discussion with Group IB / Infra / whoever
- Fix the CSP (if we agree with that solution)
- Re-open the original PR

**Comment by yuwenmemon** [comment] 2022-12-19 22:28
Original PR is reverted, removing the deployblocker label

**Comment by abekkala** [comment] 2022-12-20 12:48
I'm now ooo and there is one task for the BZ being: 

> We'll need to complete the BugZero checklist

Reassigning label

**Comment by roryabraham** [comment] 2023-01-10 19:31
Closing this since the problem PR was reverted, discussion can continue in https://github.com/Expensify/App/issues/12512

**Closed by roryabraham** 2023-01-10 19:31 UTC
Labels: Reviewing, Engineering, Hourly, Bug
