### ISSUE TITLE
[$1000] popups remains open on web chrome and web safari when clicking browser back button

### ISSUE THREAD

**Issue by kavimuru** [Expensify/App#19483] opened 2023-05-23 19:43 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:

1. Open the app
2. Open any report
3. Navigate to different report
4. Right click on any message to open popup
5. Click on back

## Expected Result: 
App should close the popup first and then navigate back as it used to do before recent updates and as it does for other popups on report page
## Actual Result: 
App keeps the right click popup open on web interface when we navigation back

## Workaround:
Can the user still use Expensify without this being fixed? Have you informed them of the workaround?

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [x] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 1.3.17
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/43996225/c85d6af9-a9b7-4307-be80-c0a6b8a011ab

https://github.com/Expensify/App/assets/43996225/96d4df7c-8fe5-452f-8554-2bd6760111e0

**Expensify/Expensify Issue URL:**
**Issue reported by:** @dhanashree-sawant
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1684590241225039

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01bc6643ce8f26450e</li>
        <li>Upwork Job ID: 1663531394074820608</li>
        <li>Last Price Increase: 2023-06-19</li>
    </ul>
</details>

**Comment by hungvu193** [comment] 2023-05-24 10:59
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
Popups remains open on web chrome and web safari when clicking browser back button
### What is the root cause of that problem?
The `PopoverReportActionContextMenu` has same level with `NavigationRoot` component, because of that when the screen changed, the `PopoverReportActionContextMenu` was still there.
https://github.com/Expensify/App/blob/e9f6a373e70a75d49dda333233ff952ea65e7cb3/src/Expensify.js#L175-L199
### What changes do you think we should make in order to solve the problem?
1. We can hide the `PopoverReportActionContextMenu` when navigationStateChange.
```javascript
function parseAndLogRoute(state) {
    if (!state) {
        return;
    }

    const currentPath = getPathFromState(state, linkingConfig.config);

    // Don't log the route transitions from OldDot because they contain authTokens
    if (currentPath.includes('/transition')) {
        Log.info('Navigating from transition link from OldDot using short lived authToken');
    } else {
        Log.info('Navigating to route', false, {path: currentPath});
    }
   // hide the context menu when state change, we can also hide other popup if it's visible
    hideContextMenu(false);
    Navigation.setIsNavigationReady();
}
```
2. Listen for back action on browser and hide the `PopoverReportActionContextMenu`

### What alternative solutions did you explore? (Optional)
Do nothing.

**Comment by sonialiap** [comment] 2023-05-25 21:34
I cannot reproduce in Chrome

**Comment by sonialiap** [comment] 2023-05-29 12:06
@hungvu193 since you've added a proposal I assume that you were able to reproduce the issue, is that correct?

**Comment by hungvu193** [comment] 2023-05-29 13:28
@sonialiap Yeah I can reproduce this one

https://github.com/Expensify/App/assets/16502320/b10041f0-c9a9-425d-981a-0305834d3f1a

**Comment by sonialiap** [comment] 2023-05-30 13:02
Thanks 👍 Moving it to External

**Comment by sonialiap** [comment] 2023-06-02 07:50
@abdulrahuman5196 what do you think about [this proposal](https://github.com/Expensify/App/issues/19483#issuecomment-1560908311)?

**Comment by abdulrahuman5196** [comment] 2023-06-02 15:15
@srikarparsi  Given that navigation is going to be removed. Is this issue worth solving now? Maybe we could put this in hold for react-navigation migration

cc: @mountiny

**Comment by srikarparsi** [comment] 2023-06-02 16:16
I agree, this doesn't seem like something urgent. I think we can put a hold on it or even close this issue and reopen it if it's still reproducible after the migration. @mountiny what do you think?

**Comment by mountiny** [comment] 2023-06-05 11:43
We can put it on hold for the reboot, should be out this week

**Comment by srikarparsi** [comment] 2023-06-08 06:04
not overdue on hold

**Comment by mountiny** [comment] 2023-06-12 12:50
@sonialiap yes it has been rebooted, we will try to go through all the held issues with Jason this week

**Comment by mountiny** [comment] 2023-06-12 12:52
@sonialiap @srikarparsi I have confirmed this is not fixed now so we can continue with the normal process

@abdulrahuman5196 would you be able to review the proposals please?

**Comment by abdulrahuman5196** [comment] 2023-06-12 13:53
sure will work on review

**Comment by abdulrahuman5196** [comment] 2023-06-13 20:11
This issue was on hold till yesterday melvin.

**Comment by abdulrahuman5196** [comment] 2023-06-14 18:55
@hungvu193 proposal here https://github.com/Expensify/App/issues/19483#issuecomment-1567142296 works. But I am not aligned if navigation state change is the right place to make this change of hiding context menu. This will add an extra step on all navigation that happen across the app which should be avoid. Since the probability of this issue happening at every navigation is super less.
So I am keeping this issue open for more ideas.

**Comment by asadath1395** [comment] 2023-06-18 09:47
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
Popups remains open on web chrome and web safari when clicking browser back button

### What is the root cause of that problem?
The `PopoverReportActionContextMenu` is at the root level, so even when route changes the component doesn't get re-rendered, so it stays on the screen.

### What changes do you think we should make in order to solve the problem?
We can listen to the `popstate` event listener in `PopoverReportActionContextMenu` and close the Popup. The `popstate` event is triggered when the history's state object is changed which happens when browser back button is clicked. Ref: https://developer.mozilla.org/en-US/docs/Web/API/Window/popstate_event

### What alternative solutions did you explore? (Optional)
I haven't explored any other alternative solution

**Comment by asadath1395** [comment] 2023-06-18 09:48
Contributor details
Your Expensify account email: anwar.sadath1395@gmail.com
Upwork Profile Link: https://www.upwork.com/freelancers/anwars20

**Comment by abdulrahuman5196** [comment] 2023-06-18 16:30
@asadath1395 The popstate seems to be a listener on the window itself and it will be fired everytime when session history changes. It falls with the same drawback mentioned here.

**Comment by abdulrahuman5196** [comment] 2023-06-18 16:31
@sonialiap @srikarparsi Kindly check on this request to increase bounty since we had very few proposals and we are still looking out for solutions.

**Comment by abdulrahuman5196** [comment] 2023-06-18 16:39
> @abdulrahuman5196
> 
> > @asadath1395 The popstate seems to be a listener on the window itself and it will be fired everytime when session history changes. It falls with the same drawback mentioned here.
> 
> @abdulrahuman5196 what drawback are you talking about?

Sorry missed to add the link - https://github.com/Expensify/App/issues/19483#issuecomment-1591816393

**Comment by abdulrahuman5196** [comment] 2023-06-18 16:40
> I think we can use `popState` but only inside BaseModal for web to avoid crash on native devices, also we can handle all the case, not only for ReportActionMenu.

I am not sure if I am understanding this correctly. Could you kindly clarify this a bit more? @hungvu193

**Comment by abdulrahuman5196** [comment] 2023-06-18 17:07
Seems to be a valid point 🤔 . So I will do some testing/digging around it to validate if this is good. 

Meanwhile @asadath1395 could you kindly update your proposal, `where you want to add this listener?`, `will it be active during session history changes throughout the app?`

**Comment by asadath1395** [comment] 2023-06-18 17:53
@abdulrahuman5196 From the docs, it mentions it will not be triggered everytime the history changes it will only be triggered by browser button action, so this solves the problem which was mentioned in the other proposal. Hope it makes sense.
![IMG_4798](https://github.com/Expensify/App/assets/37188392/59a62fbb-031d-4e04-a051-1dc193c950ea)

Also I was thinking about implementing it the same way which @hungvu193 mentioned above

**Comment by asadath1395** [comment] 2023-06-19 05:33
@abdulrahuman5196 I have updated the proposal. Also i have validated that the `popstate` event is only triggered when browsers back/forward button is clicked and it doesn't get triggered when history/route changes.

**Comment by abdulrahuman5196** [comment] 2023-06-20 20:14
This issue was removed from hold after 3 weeks and is not 4 weeks old if we leave out the hold time.
One proposal is pending review here.

**Comment by abdulrahuman5196** [comment] 2023-06-20 20:20
And the proposal needs some dive deep. Will test it out and provide reviews tomorrow on that.

**Comment by asadath1395** [comment] 2023-06-22 05:32
Hi @abdulrahuman5196,
Were you able to deep dive into my proposal? Do you have any concern?

**Comment by abdulrahuman5196** [comment] 2023-06-22 15:18
@asadath1395  

>We can listen to the popstate event listener in a useEffect in index.web.js since this behaviour has to be consistent for all the Modals and close the Popup in the callback function

Which index.web.js file do you mention here? Could add the permalink of the file you are mentioning form the repository?
Or are you going to create new file? if so for what component?

**Comment by abdulrahuman5196** [comment] 2023-06-22 15:22
Reviewing this now

**Comment by asadath1395** [comment] 2023-06-22 16:04
@abdulrahuman5196 I apologize for not being clear on my part. I have added a screenshot and the exact diff required.

**Comment by asadath1395** [comment] 2023-06-22 17:11
@kavimuru I can't seem to reproduce this in staging now. Could you please test again?

cc @abdulrahuman5196

**Comment by abdulrahuman5196** [comment] 2023-06-26 15:15
And @asadath1395  I was testing your proposal, but it is brings some "Test preferences" modal to screen many times. It is providing some unexpected results. Anyways we can retest if the issue is actually reproducible.


https://github.com/Expensify/App/assets/46707890/6b052bfe-3e2f-4206-82b3-70245e717573

**Comment by sonialiap** [comment] 2023-06-29 09:31
I cannot reproduce the issue, the popup closes when I click the browser back button. Looks like nav refactors have fixed this. Closing :) 

https://github.com/Expensify/App/assets/17131195/76cabd31-a765-4416-8811-8a4c1e84e1ae

**Comment by sonialiap** [comment] 2023-07-03 17:40
I can also still reproduce the issue 🐛

**Comment by srikarparsi** [comment] 2023-07-05 21:57
Will take a look at this tomorrow, was OOO last two days and catching up.

**Comment by srikarparsi** [comment] 2023-07-07 19:21
I asked for help from Callstack [here](https://expensify.slack.com/archives/C03UK30EA1Z/p1688757053441489)

In summary, the issue is that the Context Menu Actions popup when you right click a link doesn’t close when you click back on web, but it does disappear when you right click a normal chat action and click back on web. We need to make sure the context menu actions popup for links disappears when you click back on web as well. The code for opening both report action menu popups are here [Report Actions](https://github.com/Expensify/App/blob/main/src/pages/home/report/ReportActionItem.js#L176) and [Links](https://github.com/Expensify/App/blob/main/src/components/AnchorForCommentsOnly/BaseAnchorForCommentsOnly.js#L63).

**Comment by koko57** [comment] 2023-07-10 10:45
Hi I'm Agata from Callstack - expert contributor group - maybe I could help with this one?

**Comment by srikarparsi** [comment] 2023-07-10 14:11
Hi Agata! That would be great, thank you! Assigning you to the issue :)

**Comment by koko57** [comment] 2023-07-11 14:06
Still investigating why the issue was fixed for the context menu popup and not the Copy URL to clipboard popup.

**Comment by koko57** [comment] 2023-07-11 14:40
So I've found out that the Context Menu for the whole message is being hidden [in this useEffect](https://github.com/Expensify/App/blob/e5b7e3a767fcf70498c894c9e5f0f4d190e91fb0/src/pages/home/report/ReportActionItem.js#L119-L133) exactly in this [line](https://github.com/Expensify/App/blob/e5b7e3a767fcf70498c894c9e5f0f4d190e91fb0/src/pages/home/report/ReportActionItem.js#L125). We don't have the same mechanism for the "Copy URL to clipboard" popup, because opening is handled by the [BaseAnchorForCommentsOnly](https://github.com/Expensify/App/blob/a047b88851917807b036f3c5b8564c5add9ea9d2/src/components/AnchorForCommentsOnly/BaseAnchorForCommentsOnly.js#L43). I'll think of a way a similar logic could be implemented here and if it can be simplified and unified for all the popups within a ReportAction

**Comment by koko57** [comment] 2023-07-12 13:19
Working on my proposal. Adding simple useEffect to the BaseAnchorForCommentsOnly can solve the issue here 
```
    useEffect(() => () => {
        ReportActionContextMenu.hideContextMenu()
    }, [])
``` 
but I'm looking for a better solution to control all the popups for one message inside ReportActionItem.

**Comment by koko57** [comment] 2023-07-13 12:56
## Proposal

### Please re-state the problem that we are trying to solve in this issue.

The “Copy URL to clipboard” popup is not closing when navigating back to the previously opened chat (with the browser’s back button).

### What is the root cause of that problem?

Context Menu for the whole message is being hidden [in this useEffect](https://github.com/Expensify/App/blob/e5b7e3a767fcf70498c894c9e5f0f4d190e91fb0/src/pages/home/report/ReportActionItem.js#L119-L133) exactly in this [line](https://github.com/Expensify/App/blob/e5b7e3a767fcf70498c894c9e5f0f4d190e91fb0/src/pages/home/report/ReportActionItem.js#L125). We don't have the same mechanism for the "Copy URL to clipboard" popup, because opening is handled by the [BaseAnchorForCommentsOnly](https://github.com/Expensify/App/blob/a047b88851917807b036f3c5b8564c5add9ea9d2/src/components/AnchorForCommentsOnly/BaseAnchorForCommentsOnly.js#L43).

### What changes do you think we should make in order to solve the problem?

1. The easiest solution I've mentioned before: put hideContextMenu() in a useEffect in [BaseAnchorForCommentsOnly](https://github.com/Expensify/App/blob/a047b88851917807b036f3c5b8564c5add9ea9d2/src/components/AnchorForCommentsOnly/BaseAnchorForCommentsOnly.js#L43) (as a cleanup function)

```
    useEffect(() => () => {
        ReportActionContextMenu.hideContextMenu()
    }, [])
```
or
2. We don’t have the access to the reportAction and reportID - as a result we cannot set the state in [PopoverReportActionContextMenu](https://github.com/Expensify/App/blob/451096b4828cf9a9bc1b5b7be95a6d52e79c392d/src/pages/home/report/ContextMenu/PopoverReportActionContextMenu.js#L18) the same way we’re setting it when opening the ContextMenu in [ReportActionItem](https://github.com/Expensify/App/blob/451096b4828cf9a9bc1b5b7be95a6d52e79c392d/src/pages/home/report/ReportActionItem.js#L188-L200) (here how it is done in [BaseAnchorForCommentsOnly](https://github.com/Expensify/App/blob/451096b4828cf9a9bc1b5b7be95a6d52e79c392d/src/components/AnchorForCommentsOnly/BaseAnchorForCommentsOnly.js#L59-L66)  . isActiveReportAction in this [useEffect](https://github.com/Expensify/App/blob/451096b4828cf9a9bc1b5b7be95a6d52e79c392d/src/pages/home/report/ReportActionItem.js#L119-L133) will always return false when the Copy URL to clipboard popup is open. Maybe we could create another function that checks for the contextMenu type that is currently open and if it’s true trigger hiding the modal in the ReportActionItem useEffect. [Diff here](https://github.com/Expensify/App/compare/main...koko57:App:fix/19483-popup-remains-open?expand=1).

Additional suggestion: showContextMenu function takes many params - maybe it would be better to refactor it to take a single object. 

### What alternative solutions did you explore? (Optional)

I also thought about wrapping ReportActionItem in a context to give all the children access to the necessary report/report action data to pass the proper data to showContextMenu, but I’m not really convinced with this solution.

**Comment by srikarparsi** [comment] 2023-07-17 07:37
Hi @koko57, thanks for the writeup and updates! I think the best approach would be option 1 with hiding the context menu manually inside BaseAnchorForCommentsOnly. I haven't had a chance to look at what other context menus are opened without the ReportActionItem useEffect but I think it would be good to hide the context menu in all these components to ensure the same behavior doesn't exist for a different context menu popup. This seems like the most straightforward solution that won't introduce extra bugs and most context menus will be handled with the ReportActionItem useEffect so I think it's fine to handle one offs in their own files.

**Comment by koko57** [comment] 2023-07-17 14:14
Thanks for the review! I'm currently finishing another PR, will take it right afterwards 🙂

**Comment by abdulrahuman5196** [comment] 2023-07-19 16:07
>I think the best approach would be option 1 with hiding the context menu manually inside BaseAnchorForCommentsOnly

@koko57 @srikarparsi Sorry for the delayed reply, I agree on the same.

**Comment by koko57** [comment] 2023-07-24 12:37
PR ready for review: https://github.com/Expensify/App/pull/23152

**Comment by srikarparsi** [comment] 2023-08-08 22:24
This has been deployed to production. Are there any payments to be made or is this good to close out?

**Comment by dhanashree-sawant** [comment] 2023-08-09 06:17
Hi @srikarparsi, reporting bonus is left

**Comment by srikarparsi** [comment] 2023-08-09 18:36
Thanks @dhanashree-sawant! @sonialiap do you think you could pay @dhanashree-sawant whenever you get a chance and I think we can close out this issue once thats done.

**Comment by abdulrahuman5196** [comment] 2023-08-12 18:36
@srikarparsi Curious question. Saw this issue now only, Why was this PR didn't use me as C+ since I did review initial proposals? Sorry if I had missed something, I didn't check if this issue got into PR state.

**Comment by sonialiap** [comment] 2023-09-19 07:46
@dhanashree-sawant offer sent for reporting the issue - $250

**Comment by dhanashree-sawant** [comment] 2023-09-20 06:07
Thanks @sonialiap, I have accepted the offer.

**Comment by sonialiap** [comment] 2023-09-22 05:56
Paid ✔️

**Closed by sonialiap** 2023-09-22 05:56 UTC
Labels: Reviewing, Daily, Internal, Bug
