### ISSUE TITLE
[$500] Notification – The recipient of the money request does not receive a notification.

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#38342] opened 2024-03-14 19:06 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** v1.4.52-0
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:** https://expensify.testrail.io/index.php?/tests/view/4426935
**Issue reported by:** Applause - Internal Team

## Action Performed:
1. Open New Expensify app.
2. Log in
3. In another device log in as the Secondary user and Create a scan money request
4. As the Secondary user - change the merchant of the money request
5. Watch for notifications on your mail device

## Expected Result:
The money request recipient receives a notification for the money request

## Actual Result:
The money request recipient not receives notification for the money request

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [ ] Android: mWeb Chrome
- [x] iOS: Native
- [ ] iOS: mWeb Safari
- [ ] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

https://github.com/Expensify/App/assets/93399543/9998ecb0-0155-448a-88a0-43aa009adc3d

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~0163d31ef973252352</li>
        <li>Upwork Job ID: 1770146700225720320</li>
        <li>Last Price Increase: 2024-03-26</li>
    </ul>
</details>

**Comment by nkdengineer** [comment] 2024-03-19 18:09
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
- Notification – The recipient of the money request does not receive a notification
### What is the root cause of that problem?
- In ```playSoundForMessageType```, we do not play sound if action is ```MODIFIEDEXPENSE```
### What changes do you think we should make in order to solve the problem?
- We should check if the action is ```MODIFIEDEXPENSE``` and play sound in that case

### What alternative solutions did you explore? (Optional)

**Reminder:** Please use plain English, be brief and avoid jargon. Feel free to use images, charts or pseudo-code if necessary. Do not post large multi-line diffs or write walls of text. Do not create PRs unless you have been hired for this job.

**Comment by nkdengineer** [comment] 2024-03-20 12:36
@sakluger Can you confirm this [one](https://github.com/Expensify/App/issues/38342#issuecomment-2008640504)? IMO, I think that, BE always pushes notification to mobile device, and our FE code will handle whether we should display that notification or no

**Comment by nkdengineer** [comment] 2024-03-25 16:20
@madmax330 Can you help check this [comment](https://github.com/Expensify/App/issues/38342#issuecomment-2009466994) once you have a chance. Thanks

**Comment by arosiclair** [comment] 2024-03-26 20:05
Not sure if this is a real bug or not.

This step should trigger a notification:
> 3. In another device log in as the Secondary user and Create a scan money request

This step should NOT trigger a notification since the recipient is not subscribed to that thread (they never commented)
> 4. As the Secondary user - change the merchant of the money request

Does step 3 not create a push notification?

**Comment by nkdengineer** [comment] 2024-03-26 20:28
I just checked and step 3 triggers a notification, but not in step 4

**Comment by arosiclair** [comment] 2024-03-26 20:55
> I just checked and step 3 triggers a notification, but not in step 4

That sounds like correct behavior then. Just to double check, you tested this on iOS/Android?

**Comment by nkdengineer** [comment] 2024-03-26 21:01
I tested on Android, prod version

**Comment by Julesssss** [comment] 2024-03-27 10:57
I think we can close this, I also don't think edits should trigger a push. Seperately, IOU notifications are slightly broken but being worked on [here](https://github.com/Expensify/App/issues/32656).

**Comment by sakluger** [comment] 2024-03-27 15:50
Got it, thanks for taking a closer look @Julesssss and @arosiclair.

**Closed by sakluger** 2024-03-27 15:50 UTC
Labels: External, Daily, Help Wanted, Overdue, Bug
