### ISSUE TITLE
[$250] Pay with business BA - System message is "paid x", while thread header is "paid x elsewhere"

### ISSUE THREAD

**Issue by IuliiaHerets** [Expensify/App#48560] opened 2024-09-04 14:07 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 9.0.29-0
**Reproducible in staging?:** Y
**Reproducible in production?:** N
**If this was caught during regression testing, add the test name, ID and link from TestRail:**  https://expensify.testrail.io/index.php?/tests/view/4921007
**Email or phone of affected tester (no customers):** applausetester+kh010901@applause.expensifail.com
**Issue reported by:** Applause Internal Team

## Action Performed:
Precondition:
- Admin and member are in the same workspace.
- Workspace has bank account set up.
- Member has personal bank account.

1. Go to staging.new.expensify.com
2. [Member] Go to workspace chat and submit an expense.
3. [Admin] Approve the expense.
4. [Admin] Go offline (because there is an error when paying with business bank account).
5. [Admin] Click Pay with business bank account.
6. [Admin] Right click on the paid system message > Reply in thread.

## Expected Result:
The thread header for paid system message should be the same as the system message.

## Actual Result:
The system message is "paid x", while the thread header shows "paid x elsewhere".

## Workaround:
Unknown

## Platforms:

- [x] Android: Native
- [x] Android: mWeb Chrome
- [x] iOS: Native
- [x] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

https://github.com/user-attachments/assets/ac922658-e485-498e-a10a-9e38468ee019

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~021831454888955451181</li>
        <li>Upwork Job ID: 1831454888955451181</li>
        <li>Last Price Increase: 2024-10-09</li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @</details>

**Comment by AndrewGable** [comment] 2024-09-04 18:40
Trying to figure out which PR introduced this since it doesn't happen on prod

**Comment by AndrewGable** [comment] 2024-09-04 18:46
@bondydaa / @MariaHCD - I am curious if you think this revert revert PR could possibly be related? https://github.com/Expensify/App/pull/48421

**Comment by AndrewGable** [comment] 2024-09-04 21:12
After discussion in Slack we think this is probably a regression from the linked PR, we are going to work with @bondydaa @brandonhenry @allroundexperts to fix this regression!

**Comment by bondydaa** [comment] 2024-09-04 22:11
also throwing the external label on here, ideally @brandonhenry can fix but if not no need to block for that either.

**Comment by jaydamani** [comment] 2024-09-05 09:27
## Proposal

### Please re-state the problem that we are trying to solve in this issue.

Thread title and orignal message are incosistent for payment action message

### What is the root cause of that problem?

Both strings come from different functions that are incosistent. 

The thread title comes from message field in reportAction which is added as part of optimistic data for [payMoneyRequest](https://github.com/Expensify/App/blob/8a35256bff4d66d0f0958fd9100e191a8fda404d/src/libs/actions/IOU.ts#L7392). The optimistic data gets this message from [getIOUReportActionMessage](https://github.com/Expensify/App/blob/8a35256bff4d66d0f0958fd9100e191a8fda404d/src/libs/ReportUtils.ts#L4601). The [getIOUReportActionMessage](https://github.com/Expensify/App/blob/8a35256bff4d66d0f0958fd9100e191a8fda404d/src/libs/ReportUtils.ts#L4467-L4475) function returns `Paid x elsewhere` by default.

The message content comes from [getIOUReportActionDisplayMessage](https://github.com/Expensify/App/blob/8a35256bff4d66d0f0958fd9100e191a8fda404d/src/pages/home/report/ReportActionItemMessage.tsx#L86). The [getIOUReportActionDisplayMessage](https://github.com/Expensify/App/blob/8a35256bff4d66d0f0958fd9100e191a8fda404d/src/libs/ReportUtils.ts#L6933-L6944) returns `Paid x` by default.

This causes inconsistency between thread title and the message content.

getIOUReportActionMessage:
https://github.com/Expensify/App/blob/8a35256bff4d66d0f0958fd9100e191a8fda404d/src/libs/ReportUtils.ts#L4467-L4475

getIOUReportActionDisplayMessage:
https://github.com/Expensify/App/blob/8a35256bff4d66d0f0958fd9100e191a8fda404d/src/libs/ReportUtils.ts#L6933-L6944

### What changes do you think we should make in order to solve the problem?


`Paid x` feels more right so, we can update [getIOUReportActionMessage](https://github.com/Expensify/App/blob/8a35256bff4d66d0f0958fd9100e191a8fda404d/src/libs/ReportUtils.ts#L4601) to return `Paid x` by default. This function also has some strings hardcoded in english so maybe we should also localize this.

### What alternative solutions did you explore? (Optional)
## Option 1
Update [getIOUReportActionDisplayMessage](https://github.com/Expensify/App/blob/8a35256bff4d66d0f0958fd9100e191a8fda404d/src/libs/ReportUtils.ts#L6933-L6944) to return `Paid x elsewhere`.
## Option 2
getIOUReportActionMessage is only used for building optmistic reports and for showing last message so maybe we can replace it with getIOUReportActionDisplayMessage.

**Comment by bondydaa** [comment] 2024-09-06 17:31
i'll be OOO next week so if we get proposals ready please ask for another engineer to review

**Comment by isabelastisser** [comment] 2024-09-06 17:53
@allroundexperts, can you please review the proposals above? Thanks!

**Comment by allroundexperts** [comment] 2024-09-08 20:00
Thanks for the proposal @jaydamani. I think with your proposal, we'll show `Paid x` even on the report messages as well, which seems incorrect to me. @bondydaa @isabelastisser Should we replace this message with `Paid x` everywhere?

**Comment by jaydamani** [comment] 2024-09-09 14:44
> Thanks for the proposal @jaydamani. I think with your proposal, we'll show `Paid x` even on the report messages as well, which seems incorrect to me. @bondydaa @isabelastisser Should we replace this message with `Paid x` everywhere?

`Paid x` felt more right since it was paid through expensify but if `Paid x elsewhere` is correct then we can apply option 1 in alternate solution.

**Comment by isabelastisser** [comment] 2024-09-09 18:43
Reassigning since Bondy is OOO.

**Comment by isabelastisser** [comment] 2024-09-09 18:44
@AndrewGable @MariaHCD, can you please weigh in since you were previously part of this discussion? Thanks!

**Comment by isabelastisser** [comment] 2024-09-11 19:15
Alright, I'm inclined to say that we should replace this message with` Paid x` everywhere, but I think I should ask @shawnbortonm what he thinks since this falls into a design change.

**Comment by isabelastisser** [comment] 2024-09-13 20:25
Bump @shawnborton, what do you think?

**Comment by shawnborton** [comment] 2024-09-14 06:47
This is a weird one. But my thoughts are that the chat header for the thread view should match the exact message that was threaded. So it's weird that the system message just says "Paid $XX.XX" but the thread header says "Paid $XX.XX with Expensify"

I'm not sure if the bug is that the system message actually needs to say "Paid $XX.XX with Expensify" or if the thread header needs to be updated to match the system message. cc @trjExpensify @Expensify/design @dangrous in case you have any thoughts here. 

But actually @bondydaa since this was a regression, can you explain what happened and what the expected behavior is?

**Comment by dubielzyk-expensify** [comment] 2024-09-16 00:56
Yeah I can agree with that. 

Alternative I'd say that the system message has more room so could actually contain more details of where it's paid, where the header has less space to use so we could stick with simply `Paid $XX.XX` and leave the details to the system message.

**Comment by dannymcclain** [comment] 2024-09-16 13:35
>But my thoughts are that the chat header for the thread view should match the exact message that was threaded.

I think I fall in this camp.

**Comment by isabelastisser** [comment] 2024-09-16 16:58
Thanks for discussing this, team!

**Comment by trjExpensify** [comment] 2024-09-16 23:37
>But my thoughts are that the chat header for the thread view should match the exact message that was threaded.

Agree with this, they should match. 

>I'm not sure if the bug is that the system message actually needs to say "Paid $XX.XX with Expensify" or if the thread header needs to be updated to match the system message.

I thought the former we historically expected for the system message to read:`Paid $x.xx with Expensify`. I could find [the PR](https://github.com/Expensify/App/pull/27006) where we updated it from "using Expensify" to "with Expensify" to match the button terminology in that regard, but can't see where/if we made a decision to drop "with Expensify" from the sys message for in-app payments along the way. 

I can see an argument for both really, I'm probably leaning towards only highlighting an alt payment method when it's outside of the app for brevity. I think the expectation is to be paid via the software you're using, so only highlighting when it's some place else seems okay. Especially if we start thinking about some additional variations that are coming into play like auto-reimbursement, which would otherwise make it:

>automatically paid $15.00 with Expensify via [workspace rules](www.linktohelparticle.com)

Instead of the below:

>automatically paid $20.00 via [workspace rules](www.linktohelparticle.com)

**Comment by shawnborton** [comment] 2024-09-17 05:29
> I think the expectation is to be paid via the software you're using, so only highlighting when it's some place else seems okay

Yeah, I totally agree with that.

**Comment by trjExpensify** [comment] 2024-09-17 11:29
Cool, cool! Let's make the thread header match the system message that's on prod then 👍

**Comment by isabelastisser** [comment] 2024-09-19 17:49
Not overdue.

**Comment by isabelastisser** [comment] 2024-09-23 16:28
@allroundexperts, can you please provide an update? Thanks!

**Comment by allroundexperts** [comment] 2024-09-24 18:06
Looking at this now.

**Comment by allroundexperts** [comment] 2024-09-24 19:37
@jaydamani can you please update your proposal to match the expected behaviour we decided above?

**Comment by isabelastisser** [comment] 2024-10-03 19:20
@allroundexperts, can you please provide an update? Thanks!

**Comment by allroundexperts** [comment] 2024-10-07 07:05
Since this is no longer reproducible, I think we can close this issue.

**Comment by isabelastisser** [comment] 2024-10-15 13:44
@allroundexperts, please provide an update! I will DM you for visibility, thanks!

**Comment by trjExpensify** [comment] 2024-10-16 10:09
>It shows "Paid x with expensify" for both header and message which seems correct.

Great, so this bug is resolved and we can close this.

**Closed by trjExpensify** 2024-10-16 10:09 UTC
Labels: External, Engineering, Daily, Help Wanted, Bug
