### ISSUE TITLE
Android - Request Money - Unable to select amount numbers on the Request Money page for Pixel device

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#36230] opened 2024-02-09 14:05 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.39.0
**Reproducible in staging?:** y
**Reproducible in production?:** n
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** Applause - Internal Team
**Slack conversation:**

**Issue found when executing PR** https://github.com/Expensify/App/pull/35875

## Action Performed:
Precondition: user should be Signed In
1. Open https://staging.new.expensify.com/
2. Tap on FAB > Request money
3. Write an amount
4. Try to select the amount numbers

## Expected Result:
User should be able to select the amount numbers on the Request Money page

## Actual Result:
It is unable to select the amount numbers on the Request Money page

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [ ] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

https://github.com/Expensify/App/assets/93399543/ae221b37-5e50-4be6-b77b-b3ddcaf9815e

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by kbecciv** [comment] 2024-02-09 14:05
Issue is not reproduce on Prod

https://github.com/Expensify/App/assets/93399543/3ddd6cc3-3ed5-4892-92c9-c071e85a0277

**Comment by pecanoro** [comment] 2024-02-09 16:00
Hmm, it seems to work on main on the emulator. Checking if it was reverted

**Comment by bernhardoj** [comment] 2024-02-09 16:12
I can't reproduce the issue (Pixel 6 Android 14, emulator). The code

https://github.com/Expensify/App/assets/50919443/7507eec5-e96b-4509-92b0-c6a26f1884d1

**Comment by pecanoro** [comment] 2024-02-09 17:58
Summary: [PR](https://github.com/Expensify/App/pull/35875#issuecomment-1936337124) is indeed causing the issue but it seems to working fine on emulators. Trying to check if it's broken in other Android devices.

**Comment by pecanoro** [comment] 2024-02-12 15:36
Issue got fixed, closing!

**Closed by pecanoro** 2024-02-12 15:36 UTC
Labels: Engineering, Hourly, Overdue
