### ISSUE TITLE
[$250] iOS Chat - Main composer instead of edit composer is focused when tapping Edit comment

### ISSUE THREAD

**Issue by izarutskaya** [Expensify/App#51464] opened 2024-10-25 12:19 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 9.0.54-0
**Reproducible in staging?:** Y
**Reproducible in production?:** N
**If this was caught on HybridApp, is this reproducible on New Expensify Standalone?:** Y
**Email or phone of affected tester (no customers):** applausetester+kh2010001@applause.expensifail.com
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Issue reported by:** Applause-Internal team

## Action Performed:
1. Launch ND app.
2. Go to DM.
3. Send a message.
4. Tap on the composer.
5. Long press on the message sent in Step 3.
6. Tap Edit comment.

## Expected Result:
The edit composer will be in focus.

## Actual Result:
The main composer is in focus.

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Standalone
- [ ] Android: HybridApp
- [ ] Android: mWeb Chrome
- [x] iOS: Standalone
- [x] iOS: HybridApp
- [ ] iOS: mWeb Safari
- [ ] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

https://github.com/user-attachments/assets/8cc267d0-519b-4714-91cc-f0cef279dc1b

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~021850882933004334828</li>
        <li>Upwork Job ID: 1850882933004334828</li>
        <li>Last Price Increase: 2024-11-11</li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @</details>

**Comment by izarutskaya** [comment] 2024-10-25 12:20
Production 

https://github.com/user-attachments/assets/fa14d7d0-bf80-45c0-9df2-7468da705a45

**Comment by mjasikowski** [comment] 2024-10-25 14:19
checking

**Comment by mjasikowski** [comment] 2024-10-25 15:13
Reverting https://github.com/Expensify/App/pull/51477 does alter the behavior

https://github.com/user-attachments/assets/1b7e5be9-ea77-4756-9d5a-3a0b330301d3

**Comment by Beamanator** [comment] 2024-10-28 07:40
@hungvu193 is helping look into reverting https://github.com/Expensify/App/pull/51309 in slack - https://expensify.slack.com/archives/C01GTK53T8Q/p1729858771902939

**Comment by Beamanator** [comment] 2024-10-28 12:50
Seems like the revert is not good enough - i'm trying to get my VM working to help debug iOS

**Comment by Beamanator** [comment] 2024-10-28 12:51
Hoping to get some help by making this external

**Comment by shahinyan11** [comment] 2024-10-28 14:21
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
iOS Chat - Main composer instead of edit composer is focused when tapping Edit comment
### What is the root cause of that problem?
We don't focus on editing input once it's opened.
### What changes do you think we should make in order to solve the problem?
Add `autoFocus={true}` prop to  [Composer](https://github.com/Expensify/App/blob/9f977340394a510adaf8b40c31ba7cc0eb09a9ca/src/pages/home/report/ReportActionItemMessageEdit.tsx#L506C26-L506C34) component

### What alternative solutions did you explore? (Optional)

**Comment by shahinyan11** [comment] 2024-10-28 15:50
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
iOS Chat - Main composer instead of edit composer is focused when tapping Edit comment
### What is the root cause of that problem?
[Here](https://github.com/Expensify/App/blob/9f977340394a510adaf8b40c31ba7cc0eb09a9ca/src/libs/focusComposerWithDelay/index.ts#L30C1-L38C12) is a functionality that in this case is responsible for focusing edit input. Here we use `isWindowReadyToFocus` to ensure that input focus will be called when window ready to focus. And so the `isWindowReadyToFocus` function works as expected only for android and for other platforms it resolveы Promise immediately.

[Here](https://github.com/Expensify/App/blob/9f977340394a510adaf8b40c31ba7cc0eb09a9ca/src/libs/focusComposerWithDelay/index.ts#L34C13-L34C31) the functional to focus input works faster than animation
### What changes do you think we should make in order to solve the problem?
Update [this](https://github.com/Expensify/App/blob/4aa19bf3dbc7a2656d4c0c7a93db83fce50674ed/src/libs/isWindowReadyToFocus/index.ts#L1) implementation to bellow
```
const isWindowReadyToFocus = () => new Promise(resolve => {
    setTimeout(resolve, 0);
});
```
### What alternative solutions did you explore? (Optional)
Wrap [this](https://github.com/Expensify/App/blob/9f977340394a510adaf8b40c31ba7cc0eb09a9ca/src/libs/focusComposerWithDelay/index.ts#L34C13-L34C31) call in `InteractionManager.runAfterInteractions` or in `setTimeout` when platform is IOS
```
InteractionManager.runAfterInteractions(()=>{
    textInput.focus();
})

OR

setTimeout(()=>{
    textInput.focus();
}, 0)
```
### What alternative solutions did you explore? (Optional)
Add `autoFocus={true}` prop to  [Composer](https://github.com/Expensify/App/blob/9f977340394a510adaf8b40c31ba7cc0eb09a9ca/src/pages/home/report/ReportActionItemMessageEdit.tsx#L506C26-L506C34) component

**Comment by 289Adam289** [comment] 2024-10-28 17:01
Hi! I am from SWM, an expert agency. I've looked at this issues and adding `autoFocus` prop seems to work but I will investigate root cause off the problem tomorrow.

**Comment by Beamanator** [comment] 2024-10-29 09:01
Discussed a bit in slack [here](https://expensify.slack.com/archives/C01GTK53T8Q/p1730191356461699?thread_ts=1729858771.902939&cid=C01GTK53T8Q), got some other opinions and overall agreed this isn't a big enough bug to block deploy

**Comment by Beamanator** [comment] 2024-10-29 09:01
Unassigning myself & @hungvu193 b/c I believe this will be investigated deeply by SWM

**Comment by 289Adam289** [comment] 2024-10-29 12:05
Hi! Fix proposed by @shahinyan11 with setTimeout seems to work well. Apparently ios native side needs more time to change focus and proposed code ensures the callback will be executed after event stack is cleared.

**Comment by yuwenmemon** [comment] 2024-10-30 05:42
@shahinyan11 does your solution also fix https://github.com/Expensify/App/issues/51482

**Comment by shahinyan11** [comment] 2024-10-30 12:06
> @shahinyan11 does your solution also fix #51482

No. My proposal doesn't fix this issue

**Comment by mjasikowski** [comment] 2024-11-04 08:20
@289Adam289 will you investigate this further or shall we consider the workaround good enough and close this one out?

**Comment by 289Adam289** [comment] 2024-11-04 11:27
I think the workaround is good enough.

**Comment by Jaeta01** [comment] 2024-11-11 12:45
## Proposal

### Please re-state the problem that we are trying to solve in this issue.

### What is the root cause of that problem?
We implemented the [isWindowReadyToFocus](https://github.com/Expensify/App/blob/4aa19bf3dbc7a2656d4c0c7a93db83fce50674ed/src/libs/isWindowReadyToFocus/index.ts#L1C7-L1C27) function differently for Android and other platforms. For other platforms, it resolves immediately.

### What changes do you think we should make in order to solve the problem?
Update [isWindowReadyToFocus](https://github.com/Expensify/App/blob/4aa19bf3dbc7a2656d4c0c7a93db83fce50674ed/src/libs/isWindowReadyToFocus/index.ts#L1C7-L1C27) to bellow
```
const isWindowReadyToFocus = () => new Promise(resolve => {
    setTimeout(resolve, 0);
});
```

### What alternative solutions did you explore? (Optional)

**Comment by Jaeta01** [comment] 2024-11-11 15:34
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
iOS Chat - Main composer instead of edit composer is focused when tapping Edit comment
### What is the root cause of that problem?
We implemented the [isWindowReadyToFocus](https://github.com/Expensify/App/blob/4aa19bf3dbc7a2656d4c0c7a93db83fce50674ed/src/libs/isWindowReadyToFocus/index.ts#L1C7-L1C27) function differently for Android and other platforms. For other platforms, it resolves immediately.

### What changes do you think we should make in order to solve the problem?
Update [isWindowReadyToFocus](https://github.com/Expensify/App/blob/4aa19bf3dbc7a2656d4c0c7a93db83fce50674ed/src/libs/isWindowReadyToFocus/index.ts#L1C7-L1C27) to bellow
```
const isWindowReadyToFocus = () => new Promise(resolve => {
    setTimeout(resolve, 0);
});
```

### What alternative solutions did you explore? (Optional)

**Comment by anmurali** [comment] 2024-11-12 01:27
@mjasikowski - based on https://github.com/Expensify/App/issues/51464#issuecomment-2454465347, should we be closing this issue? I am OOO for a week, so if yes - can you close it?

**Closed** 2024-11-12 08:06 UTC
Labels: External, Engineering, Daily, Help Wanted, Bug
