### ISSUE TITLE
[$500] Task is not archived when delete WS Offline

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#35174] opened 2024-01-25 19:06 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.32-2
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** Applause - Internal Team
**Slack conversation:**

**Issue found when executing PR** https://github.com/Expensify/App/pull/31900

## Action Performed:
1. Go to https://staging.new.expensify.com/
2. Log in
3. Create a new workspace
4. Open the workspace/policy expense chat
5. Create a thread
6. Turn off the internet connection
7. Delete the workspace

## Expected Result:
Thread is archived

## Actual Result:
Thread is not archived when delete WS Offline

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [x] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

https://github.com/Expensify/App/assets/93399543/b900a037-7316-473b-880a-698149600604

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~0148ea2ff5d6b35fdb</li>
        <li>Upwork Job ID: 1750595971529564160</li>
        <li>Last Price Increase: 2024-01-25</li>
<li>Automatic offers: </li>
<ul>
<li>aimane-chnaif | Reviewer | 28148967</li>
<li>mkhutornyi | Contributor | 28148968</li>
</ul></li>
    </ul>
</details>

**Comment by kbecciv** [comment] 2024-01-25 19:07
We think that this bug might be related to #vip-vsb
CC @quinthar

**Comment by Tony-MK** [comment] 2024-01-25 20:52
## Proposal

### Please re-state the problem that we are trying to solve in this issue.

Chat - The task does not display in LHN that it is archived

### What is the root cause of that problem?

We checked if the report is a `ReportUtils.isThread(report)` and removed it from the list of workspace reports that need to be archived. 

https://github.com/Expensify/App/blob/889051cf6c155c225a9c602c17d95ec40d740839/src/pages/workspace/WorkspaceInitialPage.js#L103-L105

Setting the reports attribute `statusNum` and `stateNum` in the `deleteWorkspace` function. 

### What changes do you think we should make in order to solve the problem?


Remove the condition `ReportUtils.isThread(report)` and leave the condition checking the report, which has an Id (`!report.reportID`).

**Comment by ra-md** [comment] 2024-01-26 04:38
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
The thread is not archived when we delete WS in Offline mode.

### What is the root cause of that problem?
The thread is actually archived, but we just don't add an "archived" indicator for threads in the LHN. [Here](https://github.com/Expensify/App/blob/main/src/libs/ReportUtils.ts#L2368-L2388), we don't check if the parent report is archived.

### What changes do you think we should make in order to solve the problem?
we can add a condition like [here](https://github.com/Expensify/App/blob/f6d2f61503f2ac9dd5d38a25ccf48e748ebad530/src/libs/ReportUtils.ts#L2406-L2407) to check if the parent report is archived and add ``Localize.translateLocal('common.archived')`` after ``parentReportActionMessage`` to show that the thread has been archived.

### What alternative solutions did you explore? (Optional)
N/A

**Comment by cristipaval** [comment] 2024-02-02 15:09
The following reports are archived when the workspace is deleted:

- admins room
- announce room
- workspace expense chats (the chats between each employee and the admins)
- workspace rooms (the rooms created on the workspace)

Threads created from workspace chats and rooms inherit the `chatType` from the parent report; thus, they are archived.
Tasks do NOT inherit the `chatType` from the parent report; thus, they are NOT archived. The thing is that I'm not sure if it is intentional like that in the BE. I'll open an internal discussion about it.

**Comment by cristipaval** [comment] 2024-02-02 15:18
[Here](https://expensify.slack.com/archives/C066HJM2CAZ/p1706887063270839)'s the link to the internal discussion for whoever comes here later.

**Comment by cristipaval** [comment] 2024-02-05 09:19
According to the internal discussion, we do not want to archive the task report and the IOU/expense reports. We only archive the workspace chats and rooms and their chat threads. 
@aimane-chnaif, @johncschuster, Could we confirm that the App behaves like this?

**Comment by cristipaval** [comment] 2024-02-07 15:52
Closing since we don't want to archive tasks.

**Comment by cristipaval** [comment] 2024-02-07 16:06
Ok then, I'll reopen for you to review the proposals

**Comment by johncschuster** [comment] 2024-03-19 15:34
Sorry for missing this! Payment has been issued!

**Closed by johncschuster** 2024-03-19 15:34 UTC
Labels: Reviewing, External, Weekly, Bug
