### ISSUE TITLE
[$500]  [Scan receipt] - RBR occurs if user changes Merchant field while receipt is being scanned

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#27083] opened 2023-09-09 11:32 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Click on FAB > Request money > Click on Scan tab
2. Select a receipt to be scanned
3. Select a user
4. Confirm the request
5. Quickly while receipt is being scanned click on the IOU preview component twice to open the transaction thread
6. Click on merchant
7. Type something and click save
8. Click on the header to go back to the IOU report page and then back to the report page

## Expected Result:
No RBR should occur and app should obtain the amount just as usual from the receipt

## Actual Result:
App fails to scan the amount from the receipt and an RBR occurs

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [x] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 1.3.66.3
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/93399543/a96a8b87-06c5-45e4-9b0f-174617b7c71c

https://github.com/Expensify/App/assets/93399543/233319fd-7c5a-422f-ac73-6940f5777ad1

**Expensify/Expensify Issue URL:**
**Issue reported by:** @Nathan-Mulugeta
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1693846750374259

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~014424c85f41e9fb80</li>
        <li>Upwork Job ID: 1700472278314864640</li>
        <li>Last Price Increase: 2023-09-09</li>
    </ul>
</details>

**Comment by Marcodev0505** [comment] 2023-09-09 15:11
please add cowork  potashvivian001@gmail.com on your slack. I am a web and mobile developer.

**Comment by Marcodev0505** [comment] 2023-09-09 15:15
Contributor details
Your Expensify account email: <madew60304@horsgit.com>
Upwork Profile Link: <https://www.upwork.com/freelancers/~01e1d95717895ff2c7>

**Comment by Marcodev0505** [comment] 2023-09-09 15:19
Contributor details
Your Expensify account email: [madew60304@horsgit.com](mailto:madew60304@horsgit.com)
Upwork Profile Link: https://www.upwork.com/freelancers/~01e1d95717895ff2c7

**Comment by Marcodev0505** [comment] 2023-09-09 15:20
Contributor details
Your Expensify account email: 
Upwork Profile Link: https://www.upwork.com/freelancers/~01e1d95717895ff2c7

**Comment by Marcodev0505** [comment] 2023-09-09 15:25
Contributor details
Your Expensify account email: mitetproda@gmail.com
Upwork Profile Link: https://www.upwork.com/freelancers/~014c386911af749818?referrer_url_path=%2Fab%2Fprofiles%2Fsearch%2Fdetails%2F~014c386911af749818%2Fprofile

**Comment by Christinadobrzyn** [comment] 2023-09-12 18:41
Is [this](https://github.com/Expensify/App/issues/27184) GH root related? Can these issues be combined?

**Comment by tjferriss** [comment] 2023-09-12 22:18
I think this is an intended behavior. We don't continue to SmartScan if you enter information manually. I'm not sure whether or not we want to change this feature.

**Comment by Nathan-Mulugeta** [comment] 2023-09-13 04:36
So is there a way to remove the RBR?

**Comment by mallenexpensify** [comment] 2023-09-14 07:18
I think I agree with TJ, once an edit has been made, we wouldn't keep SmartScanning, so going to close this.

**Closed by mallenexpensify** 2023-09-14 07:18 UTC
Labels: External, Daily, Help Wanted, Bug
