### ISSUE TITLE
[$500] mWeb - LHN - When LHN is loading, fab not displaying all menu options

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#41792] opened 2024-05-07 17:07 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.71
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**If this was caught during regression testing, add the test name, ID and link from TestRail:** N/A
**Issue reported by:** Applause - Internal Team

## Action Performed:
1. Go to https://staging.new.expensify.com/
2. Enter mail id and tap continue
3. Enter magic code and sign in
4. Note LHN is loading
5. When LHN is loading, tap fab and note fab options
6. Wait still LHN is loaded and reports in LHN are visible
7. Now note more fab options are displayed

## Expected Result:
When LHN is loading, fab must display all menu options

## Actual Result:
When LHN is loading, fab not displaying all menu options

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [x] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [ ] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details> 

https://github.com/Expensify/App/assets/78819774/c508a634-aab6-40f2-bd6e-61bd31f29e48

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01807feace10021d17</li>
        <li>Upwork Job ID: 1788661216079589376</li>
        <li>Last Price Increase: 2024-06-04</li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @laurenreidexpensify</details>

**Comment by lanitochka17** [comment] 2024-05-07 17:08
@bfitzexpensify  FYI I haven't added the External label as I wasn't 100% sure about this issue. Please take a look and add the label if you agree it's a bug and can be handled by external contributors

**Comment by lanitochka17** [comment] 2024-05-07 17:08
We think that this bug might be related to #vip-vsp

**Comment by bfitzexpensify** [comment] 2024-05-13 20:39
Waiting on proposals.

**Comment by james-tindal** [comment] 2024-05-14 15:12
It doesn't display the menu options until it has received the menu options from the server.
Possible solutions:
+ Server-side render the whole app
+ Split the server request so it gets the menu options before other data
+ Server-side render only the menu options state

**Comment by alitoshmatov** [comment] 2024-05-21 20:01
@james-tindal thank you for your proposal, unfortunately we can not change current api. Please consider doing more research on the project

**Comment by alitoshmatov** [comment] 2024-05-26 18:05
Waiting for a proposal

**Comment by bfitzexpensify** [comment] 2024-05-28 21:04
Not much action here, doubling the bounty.

**Comment by b4s36t4** [comment] 2024-05-28 21:15
I'm not sure what's the expected output here. There's no possible solution here because the actions which are shown after loading complete are depended on the API data which are available after getting all data which means they load only after the loading screen is done.

We can't defer the sections without any data available before which is what we wanted.

Maybe we can disable the `FAB` while data is loading?

**Comment by bfitzexpensify** [comment] 2024-05-30 17:09
Adding a second BZ member while I'm OOO until June 11th. 

@laurenreidexpensify current status:
- @b4s36t4 has pointed out that the ideal fix here isn't possible

I've raised this in #vip-vsb [here](https://expensify.slack.com/archives/C066HJM2CAZ/p1717088865200879) to get some other opinions. I think we either:
- close this as expected (in the sense that since the page isn't fully loaded, not all options might show)
- go with the alternative solution to disable FAB until the LHN is fully loaded (not sure this is better, tbh)

**Comment by ikevin127** [comment] 2024-06-02 01:05
# Proposal

### Please re-state the problem that we are trying to solve in this issue

While LHN is loading, FAB popover is not displaying all menu options.

### What is the root cause of that problem?

In [`FloatingActionButtonAndPopover`](https://github.com/Expensify/App/blob/041ffa5b198d15a53c5d1b88fad6399fc102b9bc/src/pages/home/sidebar/SidebarScreen/FloatingActionButtonAndPopover.tsx#L336-L466) we're conditionally rendering some of the menu options based on variables which are related to the same loading variable the LHN is related to.

### What changes do you think we should make in order to solve the problem?

Remove the variable and conditional rendering of the menu options and instead invert the variable boolean and pass it to the menu item's `disabled` prop. This way we see all the menu options from the beginning, but they are **grayed-out (disabled)** and the **user cannot click on them** until the data is actually loaded.

**Note:** When `offline` we keep the options disabled.

> [!important]
> 1. We skip doing this for the `Book travel` option since `canUseSpotnanaTravel` is based on permissions and there's no delay when it comes to what UI is shown based on permissions.
> 2. For the `Quick action` item we have to default the `getQuickActionIcon` to `Expensicons.MoneyCircle` and add the `Loading...` label instead of the quick action name, until the actual Quick action data is loaded.
> **Note:** ^ The `Quick action` disabled UI / label will be discussed with the design team.

### Video

<details>
<summary>MacOS: Chrome</summary>

https://github.com/Expensify/App/assets/56457735/e911e653-d4ef-440d-be66-67136bd6742e

</details>

### What alternative solutions did you explore? (Optional)

Disable the FAB button until the LHN is loaded and all options are available.

### Video

<details>
<summary>MacOS: Chrome</summary>

https://github.com/Expensify/App/assets/56457735/5c330cd9-7c04-47c1-bf75-72466ae58b4d

</details>

**Comment by ikevin127** [comment] 2024-06-02 01:07
# Proposal

### Please re-state the problem that we are trying to solve in this issue

While LHN is loading, FAB popover is not displaying all menu options.

### What is the root cause of that problem?

In [`FloatingActionButtonAndPopover`](https://github.com/Expensify/App/blob/041ffa5b198d15a53c5d1b88fad6399fc102b9bc/src/pages/home/sidebar/SidebarScreen/FloatingActionButtonAndPopover.tsx#L336-L466) we're conditionally rendering some of the menu options based on variables which are related to the same loading variable the LHN is related to.

### What changes do you think we should make in order to solve the problem?

Remove the variable and conditional rendering of the menu options and instead invert the variable boolean and pass it to the menu item's `disabled` prop. This way we see all the menu options from the beginning, but they are **grayed-out (disabled)** and the **user cannot click on them** until the data is actually loaded.

> [!important]
> 1. We skip doing this for the `Book travel` option since `canUseSpotnanaTravel` is based on permissions and there's no delay when it comes to what UI is shown based on permissions.
> 2. For the `Quick action` item we have to default the `getQuickActionIcon` to `Expensicons.MoneyCircle` and add the `Loading...` label instead of the quick action name, until the actual Quick action data is loaded.
> **Note:** ^ The `Quick action` disabled UI / label will be discussed with the design team.

### Video

<details>
<summary>MacOS: Chrome</summary>

https://github.com/Expensify/App/assets/56457735/e911e653-d4ef-440d-be66-67136bd6742e

</details>

### What alternative solutions did you explore? (Optional)

Disable the FAB button until the LHN is loaded and all options are available.

### Video

<details>
<summary>MacOS: Chrome</summary>

https://github.com/Expensify/App/assets/56457735/5c330cd9-7c04-47c1-bf75-72466ae58b4d

</details>

**Comment by alitoshmatov** [comment] 2024-06-02 19:21
@ikevin127 Thank you for your proposal I don't think disabling menu items is solving the direct problem of them not being usable till data is loaded. 

I agree with @b4s36t4's [take](https://github.com/Expensify/App/issues/41792#issuecomment-2136125395) here. I think we should close this issue since there is no direct solution for the issue

@laurenreidexpensify Can you share the outcome of the discussion here:
> I've raised this in #vip-vsb [here](https://expensify.slack.com/archives/C066HJM2CAZ/p1717088865200879) to get some other opinions. I think we either:

**Comment by ikevin127** [comment] 2024-06-02 20:14
> @ikevin127 Thank you for your proposal I don't think disabling menu items is solving the direct problem of them not being usable till data is loaded.

I'm a bit lost as to where does it state that the **expected result** is that the options have to be usable before the LHN is loaded 🤔

**Expected result states:**
> When LHN is loading, fab must display all menu options

This is why I proposed showing the options but disabling them until the data is available instead of not rendering them at all and having them pop when the data becomes available (bad UX).

In my view this **fulfils the expected result** from a UI/UX perspective while also keeping the FAB enabled for **access to the other options that don't depend on the data being loaded**.

I feel this is the **best compromise** in this situation, without restructuring BE.

##

I'm also curious what was the consensus of the discussion from the **#vip-vsb** slack thread.

**Comment by alitoshmatov** [comment] 2024-06-04 22:10
@ikevin127 Your take is completely valid. I just didn't accept your solution directly since expected result is not clear, and I disabling menu items cannot be directly derived from expected result pointed out in OP. Moreover, in my opinion, disabling menu items is major UI/UX change and we should move forward with this solution if internal team approves it.

Let's just wait for @laurenreidexpensify to check on [here](https://expensify.slack.com/archives/C066HJM2CAZ/p1717088865200879) and give us final result.

**Comment by laurenreidexpensify** [comment] 2024-06-06 11:01
@Expensify/design can you take a look at this one and confirm if it's something we want to fix?

**Comment by dannymcclain** [comment] 2024-06-06 14:24
Oof this is a tricky one. It seems like the _ideal_ fix is to make the app load faster so that the API request to get all the global create options doesn't take so long? But obviously that's not super actionable. I'm struggling to decide if I think it's better to disable global create (or add some kind of loading indicator to the menu while we're still loading) or just leave it as is. Curious for the rest of the design team's thoughts, but I think I'm leaning towards just leaving this as is for now.

**Comment by shawnborton** [comment] 2024-06-06 15:14
Yeah, I totally agree - the real solution here is to make the app faster! 

I don't really know that any alternatives or proposals feel that great... I'm basically on the same page as you, blocking the FAB feels bad and giving the FAB any kind of loading state also feels bad. So I think I would also just do nothing, unless we think there's anything from the BE side we can do to speed things up. Can we get an opinion from one of our engineers maybe?

**Comment by laurenreidexpensify** [comment] 2024-06-07 12:27
@thienlnam @quinthar @puneetlath @techievivek any thoughts on the above? Thanks

**Comment by laurenreidexpensify** [comment] 2024-06-07 12:28
@thienlnam @quinthar @puneetlath @techievivek any thoughts on the above? Thanks

**Comment by thienlnam** [comment] 2024-06-07 18:51
Agree on doing nothing - this is already something that is being worked on with #fast-apis and #newdot-performance, and so doesn't feel worth doing some intermediary step here

**Comment by puneetlath** [comment] 2024-06-09 20:25
I agree with do nothing. I'll close this, but feel free to reopen if you disagree.

**Closed by puneetlath** 2024-06-09 20:25 UTC
Labels: External, Daily, Help Wanted, Bug
