### ISSUE TITLE
[HOLD for payment 2022-09-16] [$250] Changing input field on Mobile App closes the keyboard - reported by @Tushu17

### ISSUE THREAD

**Issue by mvtglobally** [Expensify/App#9234] opened 2022-05-31 03:45 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Open mobile App(Ios/Android)
2. Go to settings > profile
3. Click/touch on First name
4. then touch on Last name

## Expected Result:
It should not close the keyboard.

## Actual Result:
Changing Input field closes the keyboard then user have to touch on the input field again to open the keyboard

## Workaround:
unknown 

## Platform:

Where is this issue occurring?

- iOS
- Android

**Version Number:** 1.1.68-0
**Reproducible in staging?:** Y 
**Reproducible in production?:** Y 
**Email or phone of affected tester (no customers):** 
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation 

https://user-images.githubusercontent.com/43995119/171088610-5d82c958-5770-4175-839a-23725bbdf8af.mov

**Expensify/Expensify Issue URL:** 
**Issue reported by:** @Tushu17
**Slack conversation:** https://expensify.slack.com/archives/C01GTK53T8Q/p1650919901688689

**Job Post** https://www.upwork.com/jobs/~01e74f3da7a543363a

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by kevinksullivan** [comment] 2022-05-31 16:31
@Tushu17 hired for reporting.

**Comment by jayeshmangwani** [comment] 2022-06-04 13:16
#### Proposal



Cause:

We are using a Text component in TextInputLabel and this issue is happening when we press on the Text labels, otherwise, it is working fine, and here we have to disable the touchable of the label so that textinput's touchable can work

Solution:

we can disable the touch events here by

https://github.com/Expensify/App/blob/50da22fa41944f42b7c36ba7a91f0ab737eb6cc6/src/components/TextInput/TextInputLabel/index.native.js#L17-L31

```diff
+pointerEvents="none"
```

**Comment by liyamahendra** [comment] 2022-06-05 12:41
# Proposal

### Problem

The issue is when either of Firstname or Lastname Input field is focused with keyboard visible, if you try to focus on the other input field, the keyboard which was visible becomes invisible.

### Solution

The Firstname and Lastname textfields are wrapped inside a `ScrollView`. The `ScrollView` has a props `keyboardShouldPersistTaps` which can be set to solve this issue.

Fix is to change the below line:
```
<ScrollView style={styles.flex1} contentContainerStyle={styles.p5}>
```

to

```
<ScrollView style={styles.flex1} contentContainerStyle={styles.p5} keyboardShouldPersistTaps='handled'>
```

Below is the screencast showing the fix:

https://user-images.githubusercontent.com/911879/172050949-c9e07b9d-b907-4704-8607-3cdb55094897.mp4

**Comment by rushatgabhane** [comment] 2022-06-06 00:58
Hmm, making the page compatible with Form should solve this issue too.
https://github.com/Expensify/App/blob/26956bb813f2c0ef9b256b06a3d90df10b82e5d2/src/components/Form.js#L184


@marcochavezf can you reproduce this issue? I could repro this issue 2 days ago, but now it seems to be fixed!

**Comment by rushatgabhane** [comment] 2022-06-08 20:13
App is crashing on `main` for me. I need some time to verify the proposal.
https://expensify.slack.com/archives/C01GTK53T8Q/p1654718949591419

**Comment by rushatgabhane** [comment] 2022-06-08 20:25
> please try to press on the label of the textinput you will see this issue 

@jayeshmangwani thanks for helping me reproduce this issue!

@marcochavezf I recommend @jayeshmangwani's [proposal](https://github.com/Expensify/App/issues/9234#issuecomment-1147807641).
🎀 👀 🎀 C+ reviewed

**Comment by liyamahendra** [comment] 2022-06-09 01:27
@rushatgabhane though @jayeshmangwani's solution fixes the issue, it doesn't address the root cause which is the ScrollView. The ScrollView will always cause this issue to happen unless the `keyboardShouldPersistTaps` prop is used.

Let's say you patch the code using @jayeshmangwani's solution now, and down the line a new custom composite control is used / added. Then this issue will again pop-up.

**Comment by rushatgabhane** [comment] 2022-06-09 09:30
> This issue is reproducible on all pages that aren't using forms yet. Can you please post an updated proposal to fix this issue for all pages. (a few egs: AddSecondaryLoginPage, NewRoomPage etc)

@liyamahendra I'm so sorry. This comment was meant for you. I forgot to tag you.

**Comment by liyamahendra** [comment] 2022-06-09 10:29
# Proposal (Updated)

Since ScrollView is used at multiple locations, I believe having a custom ScrollView Component which sets this prop's value by default will be a better solution.

- Create a new component inside `src/components` as below:

```
import React from 'react';
import PropTypes from 'prop-types';
import {ScrollView} from 'react-native';

const propTypes = {
    children: PropTypes.node.isRequired,
};

const ScrollViewWithTapPersist = React.forwardRef((props, ref) => (
    <ScrollView
        ref={ref}
        keyboardShouldPersistTaps="handled"
        // eslint-disable-next-line react/jsx-props-no-spreading
        {...props}
    >
        {props.children}
    </ScrollView>
));

ScrollViewWithTapPersist.propTypes = propTypes;
ScrollViewWithTapPersist.displayName = 'ScrollViewWithTapPersist';
export default ScrollViewWithTapPersist;
```

- Inside `src/pages/settings/Profile/ProfilePage.js`, `src/pages/settings/AddSecondaryLoginPage.js` and `src/pages/workspace/WorkspaceNewRoomPage.js` rather than using 

```
import {ScrollView} from 'react-native';
```

Use the custom component created above as below:

```
import ScrollViewWithTapPersist from '../../../components/ScrollViewWithTapPersist';
```

And then replace `ScrollView` with `ScrollViewWithTapPersist`.

@rushatgabhane please let me know your comments.

**Comment by rushatgabhane** [comment] 2022-06-09 15:26
@liyamahendra or how about we use [FormScrollView](https://github.com/Expensify/App/blob/main/src/components/FormScrollView.js)?

**Comment by liyamahendra** [comment] 2022-06-09 16:11
>@liyamahendra or how about we use [FormScrollView](https://github.com/Expensify/App/blob/main/src/components/FormScrollView.js)? It already has the keyboardShouldPersistTaps prop.

Yes, that should solve the issue as well! 👍

**Comment by luacmartins** [comment] 2022-06-09 18:59
@rushatgabhane yes, we will refactor it to use Form. We already have an example of a Form refactor [here](https://github.com/Expensify/App/pull/9056/files#diff-8dd7f82fff27e2deb9f848eadbc9d7c691c6f2c03a98c81ef6d1935b863c37cbL1). Let's just do it in this case as well.

**Comment by rushatgabhane** [comment] 2022-06-09 19:19
Thanks!!
@liyamahendra are you up for [this](https://github.com/Expensify/App/issues/9234#issuecomment-1151489135) task?

**Comment by liyamahendra** [comment] 2022-06-10 06:01
>@liyamahendra are you interested in taking up https://github.com/Expensify/App/issues/9234#issuecomment-1151489135 task?

@rushatgabhane Yes, I'm interested in taking up the task. Let me review the refactor link shared by @luacmartins and come back to you with the changes for refactoring the `ProfilePage` to use `Form`.

**Comment by rushatgabhane** [comment] 2022-06-10 07:44
@liyamahendra we also have a helpful FORM doc
https://github.com/Expensify/App/blob/main/FORMS.md

**Comment by liyamahendra** [comment] 2022-06-10 16:25
@rushatgabhane can you please review the changes below and comment:

Folllowing are the changes:

1. Imports
- Change `import { View, ScrollView } from 'react-native';` to `import { View } from 'react-native';`
- Add `import Form from '../../../components/Form';`
- Remove `import Button from '../../../components/Button';`, `import FixedFooter from '../../../components/FixedFooter';` and `import FullNameInputRow from '../../../components/FullNameInputRow';`

2. Delete 

```
// Disables button if none of the form values have changed
        const isButtonDisabled = (this.props.myPersonalDetails.firstName === this.state.firstName.trim())
            && (this.props.myPersonalDetails.lastName === this.state.lastName.trim())
            && (this.props.myPersonalDetails.timezone.selected === this.state.selectedTimezone)
            && (this.props.myPersonalDetails.timezone.automatic === this.state.isAutomaticTimezone)
            && (this.props.myPersonalDetails.pronouns === this.state.pronouns.trim())
            && (!this.state.isAvatarChanged || this.props.myPersonalDetails.avatarUploading);
```

3. Replace `<ScrollView style={styles.flex1} contentContainerStyle={styles.p5}>` with 
```
<Form
    style={[styles.flex1, styles.p5]}
    formID='profileForm'
    validate={this.validate}
    onSubmit={this.updatePersonalDetails}
    submitButtonText={this.props.translate('common.save')}
>
```

4. Add inputID to the controls
- `inputID='avatar'` to `<AvatarWithImagePicker`
- `inputID='pronounsPicker'` to Pronouns `Picker` and add `shouldSaveDraft` prop
- `inputID='pronounSelected'` to Pronouns TextInput
- `inputID='loginEmail'` to Email `LoginField` 
- `inputID='loginPhoneNumber'` to PhoneNumber `LoginField`
- `inputID='timezonePicker'` to Timezone `Picker` and add `shouldSaveDraft` prop
- `inputID='shouldSetTimezoneAutomatically'` to Set Automatic Timezone `CheckboxWithLabel`

5. Delete

```
 <FixedFooter>
    <Button
        success
        isDisabled={isButtonDisabled}
        onPress={this.updatePersonalDetails}
        style={[styles.w100]}
        text={this.props.translate('common.save')}
        pressOnEnter
    />
</FixedFooter>
```

6. Replace

```
<FullNameInputRow
    firstName={this.state.firstName}
    firstNameError={PersonalDetails.getMaxCharacterError(this.state.hasFirstNameError)}
    lastName={this.state.lastName}
    lastNameError={PersonalDetails.getMaxCharacterError(this.state.hasLastNameError)}
    onChangeFirstName={firstName => this.setState({firstName})}
    onChangeLastName={lastName => this.setState({lastName})}
    style={[styles.mt4, styles.mb4]}
/>
```

with two separate TextInput so that we can have inputID for Firstname and Lastname

```
<View style={[styles.flexRow, styles.mt4, styles.mb4]}>
    <View style={styles.flex1}>
        <TextInput
            inputID='firstname'
            name="fname"
            label={this.props.translate('common.firstName')}
            value={this.state.firstName}
            errorText={PersonalDetails.getMaxCharacterError(this.state.hasFirstNameError)}
            onChangeText={firstName => this.setState({ firstName })}
            placeholder={this.props.translate('profilePage.john')}
        />
    </View>
    <View style={[styles.flex1, styles.ml2]}>
        <TextInput
            inputID='lastname'
            name="lname"
            label={this.props.translate('common.lastName')}
            value={this.state.lastName}
            errorText={PersonalDetails.getMaxCharacterError(this.state.hasLastNameError)}
            onChangeText={lastName => this.setState({ lastName })}
            placeholder={this.props.translate('profilePage.doe')}
        />
    </View>
</View>
```

7. Add the validate method as below:

```
validate(values) {
    const errors = {};
    const [hasFirstNameError, hasLastNameError, hasPronounError] = ValidationUtils.doesFailCharacterLimit(
        50,
        [values.firstName.trim(), values.lastName.trim(), values.pronouns.trim()],
    );
    this.setState({
        hasFirstNameError,
        hasLastNameError,
        hasPronounError,
    });

    if(hasFirstNameError) {
        errors.hasFirstNameError = hasFirstNameError;
    }
    if(hasLastNameError) {
        errors.hasLastNameError = hasLastNameError;
    }
    if(hasPronounError) {
        errors.hasPronounError = hasPronounError;
    }

    this.setState({
        hasFirstNameError,
        hasLastNameError,
        hasPronounError,
    });

    return errors;
}
```

**Comment by rushatgabhane** [comment] 2022-06-10 19:18
@liyamahendra that seems fine but shouldn't we first refactor `FullNameInputRow` to use `Form`? 
And then come back to refactoring ProfilePage.

cc: @marcochavezf

**Comment by luacmartins** [comment] 2022-06-10 19:22
Is it possible to just get rid of `FullNameInputRow` and use a regular `TextInput` instead?

**Comment by rushatgabhane** [comment] 2022-06-10 19:27
@luacmartins yes, we could do that too.

**Comment by rushatgabhane** [comment] 2022-06-10 19:31
🎀 👀 🎀 C+ reviewed
@marcochavezf I like @liyamahendra's [proposal](https://github.com/Expensify/App/issues/9234#issuecomment-1152533613) to refactor ProfilePage to use Form to fix this issue.

This issue will be fixed for other pages once they're refactored eventually.

**Comment by luacmartins** [comment] 2022-06-10 19:40
>yes, let's get rid of it. Sounds like a better idea.

Let's do that. I don't see the point of having that input.

**Comment by liyamahendra** [comment] 2022-06-10 20:41
> @liyamahendra that seems fine but shouldn't we first refactor FullNameInputRow to use Form?
And then come back to refactoring ProfilePage.

I did propose changing ‘ FullNameInputRow’ to normal text input controls. Did you had a chance to notice my point 6? Or you were suggesting something else? @rushatgabhane

**Comment by rushatgabhane** [comment] 2022-06-10 20:44
@liyamahendra yep, was just asking questions to see if we can do better.

**Comment by liyamahendra** [comment] 2022-06-11 14:27
@rushatgabhane I've been doing the changes locally and testing them. I'm done with most of the testing.

Below are the changed files:

```
	modified:   src/ONYXKEYS.js
	modified:   src/languages/en.js
	modified:   src/languages/es.js
	modified:   src/libs/actions/PersonalDetails.js
	modified:   src/pages/settings/Profile/ProfilePage.js
```

I added a new error message when the saving of personal details fails:

- src/languages/en.js
```
genericFailureMessage: 'An error occurred while saving the personal details, please try again.',
```

- src/languages/es.js
```
genericFailureMessage: 'Hubo un error al guardar sus datos personales. Por favor, inténtalo de nuevo.',
```

Can you please review & comment about these text addition? I used google translate to add to es.js. Do we have a standard process to get the localised text?

The above text is used inside `src/libs/actions/PersonalDetails.js` as:

```
function setPersonalDetails(details, shouldGrowl) {
    DeprecatedAPI.PersonalDetails_Update({details: JSON.stringify(details)})
        .then((response) => {
            let serverErrorMessage = '';
            if (response.jsonCode === 200) {
                if (details.timezone) {
                    NameValuePair.set(CONST.NVP.TIMEZONE, details.timezone);
                }
                mergeLocalPersonalDetails(details);

                if (shouldGrowl) {
                    Growl.show(Localize.translateLocal('profilePage.growlMessageOnSave'), CONST.GROWL.SUCCESS, 3000);
                }
            } else if (response.jsonCode === 400) {
                Growl.error(Localize.translateLocal('personalDetails.error.firstNameLength'), 3000);
            } else if (response.jsonCode === 401) {
                Growl.error(Localize.translateLocal('personalDetails.error.lastNameLength'), 3000);
            } else {
                serverErrorMessage = response.message ? response.message : Localize.translateLocal('profilePage.genericFailureMessage');
                console.debug('Error while setting personal details', response);
            }

            Onyx.merge(ONYXKEYS.FORMS.PROFILE_FORM, {
                isSubmitting: false,
                serverErrorMessage,
            });
        });
}
```

**Comment by rushatgabhane** [comment] 2022-06-11 14:32
@liyamahendra this code is being refactored, you can skip adding the new error message.

**Comment by liyamahendra** [comment] 2022-06-11 14:38
@rushatgabhane thank you for the quick response! I'll remove setting of `serverErrorMessage` from `src/libs/actions/PersonalDetails.js`.

I'm having trouble setting the `errorText`. I debugged the code and it seems that the `errorText` doesn't get passed to the `BaseTextInput` control. Even when I set the `errorText` to a static value, it doesn't show up. Any insights on this please?

**Comment by rushatgabhane** [comment] 2022-06-11 14:46
> If your solution proposal is accepted by the Expensify engineer assigned to the issue, Expensify will hire you on Upwork and assign the GitHub issue to you. ([contributing.md](https://github.com/Expensify/App/blob/main/CONTRIBUTING.md#propose-a-solution-for-the-job))

@liyamahendra Hold on. It is recommened to start working on this issue only after you're assigned the issue.

**Comment by liyamahendra** [comment] 2022-06-11 14:49
Oh, okay! I've already submitted a proposal on Upwork for this job. My Upwork username is `devappsc`. Kindly let me know further process. Thank you!

**Comment by rushatgabhane** [comment] 2022-06-11 14:58
@liyamahendra an Expensify engineer (@marcochavezf in this case) will review your proposal and assign you the issue if all is good. (see [contributing.md](https://github.com/Expensify/App/blob/main/CONTRIBUTING.md#propose-a-solution-for-the-job)). You can then open a [pull request](https://github.com/Expensify/App/blob/main/CONTRIBUTING.md#begin-coding-your-solution-in-a-pull-request) when the code is ready for review.


Anyway, regarding your question for `errorText`. You don't need to pass it to TextInputs, passing the right validate function to Form should take care of `errorText`.

Please go through the example below, it'll help you in the refactor. 
https://github.com/Expensify/App/blob/6bac9af7294877114f8bf9532ff7b8c46146c90d/src/pages/settings/Payments/AddDebitCardPage.js#L100

**Comment by liyamahendra** [comment] 2022-06-12 11:59
@rushatgabhane I was able to fix the `errorText` issue by comparing my `validate` method with that inside `AddDebitCardPage` - the issue was I used the wrong keys while returning the error object from the `validate` method. All good now!

@marcochavezf I'm ready for doing the refactoring for `ProfilePage`. My proposal was reviewed initially by @rushatgabhane and he thinks it's good. Can you please review my proposal and comment. I've already placed a proposal for this job on Upwork.

Thank you!

**Comment by marcochavezf** [comment] 2022-06-13 21:03
Thank you for the review @rushatgabhane, I was OOO sorry for the delay here. Assigning @liyamahendra 👍🏽

**Comment by liyamahendra** [comment] 2022-06-14 09:17
@marcochavezf I've already applied for the job on Upwork. 

I've created [the PR](https://github.com/Expensify/App/pull/9441).

**Comment by kevinksullivan** [comment] 2022-06-16 20:03
@liyamahendra please apply to the job when you get a chance!

https://www.upwork.com/jobs/~01e74f3da7a543363a

**Comment by liyamahendra** [comment] 2022-06-16 21:15
@kevinksullivan I have already applied for this Upwork job. My name there Mahendra Liya and username is devappsc

**Comment by rushatgabhane** [comment] 2022-06-20 12:02
Waiting on https://github.com/Expensify/App/pull/9476 to merge

**Comment by marcochavezf** [comment] 2022-06-29 20:27
We're still waiting on https://github.com/Expensify/App/pull/9476

**Comment by marcochavezf** [comment] 2022-07-11 23:54
Applying the `Reviewing` label here since https://github.com/Expensify/App/pull/9476 was already merged

**Comment by mallenexpensify** [comment] 2022-09-05 23:54
PR is actively being worked on https://github.com/Expensify/App/pull/9441

**Comment by liyamahendra** [comment] 2022-09-06 08:44
I've already received payment for this issue as it got auto approved by Upwork - JFYI. 
Is there anything I need to do - asking as this is among the very first issues I've worked with Expensify.

**Comment by liyamahendra** [comment] 2022-09-06 08:45
@luacmartins @marcochavezf @kevinksullivan ^^

**Comment by kevinksullivan** [comment] 2022-09-12 18:52
Hm I'm not familiar with the auto approval feature but I do see it was paid. @mallenexpensify are you familiar with that?

**Comment by mallenexpensify** [comment] 2022-09-13 00:20
@kevinksullivan , It looks like it might have been because a milestone was created vs hiring for fixed price (I've played with this a bunch lately, it's def a semi-common issue). @liyamahendra 's contract in Upwork was ended too. 
<img width="621" alt="image" src="https://user-images.githubusercontent.com/22508304/189780144-99c7c2b9-2745-4785-bbc2-5b0a1bf8c5d3.png">

Looks like  @Tushu17 was paid today for reporting, I ended their contract. 
<img width="667" alt="image" src="https://user-images.githubusercontent.com/22508304/189780246-24ccdce0-4b34-43c4-94f0-42d5f9595841.png">

And... just paid @rushatgabhane and ended contract (to make this easier to manage going forward.  

Now, let's hope there are no regressions within the next three days 🤞 .  We can close this on 9/16 without taking more actions if no regressions

**Comment by liyamahendra** [comment] 2022-09-13 06:51
@mallenexpensify As a part of this issue, the Form refactor was done for which a bounty was agreed [here](https://github.com/Expensify/App/pull/9441#issuecomment-1205444809). Just a gentle reminder note about this please.

cc: @luacmartins

**Comment by mallenexpensify** [comment] 2022-09-13 17:23
@liyamahendra does that mean you're due another $250?  If so, @luacmartins or @rushatgabhane  can you confirm and I'll add the $250 to the job?

**Comment by liyamahendra** [comment] 2022-09-13 18:17
> @liyamahendra does that mean you're due another $250?

@mallenexpensify Yes, that's what I understood from @luacmartins' [comment](https://github.com/Expensify/App/pull/9441#issuecomment-1205444809).

**Comment by liyamahendra** [comment] 2022-09-13 18:25
@luacmartins can you please confirm?

**Comment by luacmartins** [comment] 2022-09-14 14:37
@liyamahendra @mallenexpensify The bounty for the issue is $250. If a $250 payment was already made, which seems to be the case, no further payments are due anymore.

**Comment by liyamahendra** [comment] 2022-09-14 15:28
@luacmartins did you mean **bounty** as in payment above the price for the actual issue?

**Comment by luacmartins** [comment] 2022-09-14 15:35
@liyamahendra No, the bounty is the price we pay for fixing the issue, $250 in this case. Sorry if this was not clear for you.

**Comment by liyamahendra** [comment] 2022-09-14 15:51
Well, I can just express my disappointment only then. Extremely disappointed!

**Comment by mallenexpensify** [comment] 2022-09-23 02:27
Yes, thanks all

**Closed by mallenexpensify** 2022-09-23 02:27 UTC
Labels: Reviewing, Exported, Daily, Awaiting Payment
