### ISSUE TITLE
[HOLD REFACTOR] [$250] Enlarged view of own avatar not getting updated after uploading new avatar - reported by @aswin-s

### ISSUE THREAD

**Issue by mvtglobally** [Expensify/App#9418] opened 2022-06-13 04:51 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Go to profile settings.
2. Upload a new profile picture and save. Wait for upload to finish.
3. Navigate to own profile details from an ongoing chat.
4. Tap on avatar to enlarge it.
5. Previous avatar is shown instead on new one.

## Expected Result:
Enlarged view of new profile image is shown.

## Actual Result:
Enlarged view of own avatar not getting updated after uploading new avatar

## Workaround:
unknown 

## Platform:

Where is this issue occurring?

- iOS

**Version Number:** 1.1.75-0
**Reproducible in staging?:** Y 
**Reproducible in production?:** Y
**Email or phone of affected tester (no customers):** 
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation 

https://user-images.githubusercontent.com/43995119/173281897-894ba1c6-c4f1-4b4c-854b-4c6ad04a9875.mp4

potentially related to https://github.com/Expensify/App/issues/9355

**Expensify/Expensify Issue URL:** 
**Issue reported by:** @aswin-s
**Slack conversation:** [
](https://expensify.slack.com/archives/C01GTK53T8Q/p1652979000589389) 
[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by flodnv** [comment] 2022-06-21 15:35
Not overdue -- let's send it to upwork!

**Comment by sobitneupane** [comment] 2022-06-28 10:08
**Proposal:**
We need to update `avatarHighResolution`, along with `avatar` in the following functions to solve the issue as `avatarHighResolution` is used in enlarged view.
https://github.com/Expensify/App/blob/a1be80db6cd1edface034d8e11cfabb3707ea2ea/src/libs/actions/PersonalDetails.js#L342-L359
```diff
function setAvatar(file) {
    setPersonalDetails({avatarUploading: true});
    DeprecatedAPI.User_UploadAvatar({file})
        .then((response) => {
            // Once we get the s3url back, update the personal details for the user with the new avatar URL
            if (response.jsonCode !== 200) {
                setPersonalDetails({avatarUploading: false});
                if (response.jsonCode === 405 || response.jsonCode === 502) {
                    Growl.show(Localize.translateLocal('profilePage.invalidFileMessage'), CONST.GROWL.ERROR, 3000);
                } else {
                    Growl.show(Localize.translateLocal('profilePage.avatarUploadFailureMessage'), CONST.GROWL.ERROR, 3000);
                }
                return;
            }
_            setPersonalDetails({avatar: response.s3url, avatarUploading: false});
+            setPersonalDetails({avatar: response.s3url, avatarUploading: false, avatarHighResolution:response.s3url});
        });
}
```
https://github.com/Expensify/App/blob/a1be80db6cd1edface034d8e11cfabb3707ea2ea/src/libs/actions/PersonalDetails.js#L364-L371
```diff
function deleteAvatar(defaultAvatarURL) {
    // We don't want to save the default avatar URL in the backend since we don't want to allow
    // users the option of removing the default avatar, instead we'll save an empty string
    DeprecatedAPI.PersonalDetails_Update({details: JSON.stringify({avatar: ''})});
-  mergeLocalPersonalDetails({avatar: defaultAvatarURL});
+  mergeLocalPersonalDetails({avatar: defaultAvatarURL, avatarHighResolution:defaultAvatarURL});
}
```

**Comment by kadiealexander** [comment] 2022-06-29 01:01
Posted to Upwork!

https://www.upwork.com/ab/applicants/1532271886227472384/job-details
https://www.upwork.com/jobs/~01b7fcbbd791dc6c42

**Comment by rushatgabhane** [comment] 2022-06-29 02:28
@flodnv any chance this issue will be solved by the ongoing refactor?

**Comment by rushatgabhane** [comment] 2022-06-29 02:34
@sobitneupane thanks for your proposal!

- `avatar: response.s3url`
- `avatarHighResolution: response.s3url`

If both high resolution and low resolution avatars are using the same url, why do we need `avatarHighResolution` in the first place?

**Comment by rushatgabhane** [comment] 2022-06-30 14:40
@sobitneupane do you have an updated proposal? Because your original proposal is hidden

**Comment by kadiealexander** [comment] 2022-07-01 01:21
I accidentally hid the proposal sorry @sobitneupane, I was taking screenshots of something and I followed a GitHub [step by step](https://docs.github.com/en/communities/moderating-comments-and-conversations/managing-disruptive-comments#unhiding-a-comment) that lied to me and said I was able to unhide the comment. Sorry about that team!

**Comment by rushatgabhane** [comment] 2022-07-05 15:25
🎀 👀 🎀 C+ Reviewed
@flodnv I like @sobitneupane's [proposal](https://github.com/Expensify/App/issues/9418#issuecomment-1168518507).

**Comment by rushatgabhane** [comment] 2022-07-05 15:57
> why do we have both avatarHighResolution and avatar? Can we not just have the high res one and always use that?

@flodnv the LHN and chat use the `128 x 128` avatar icons. Why? Because they're faster to download

**Comment by Beamanator** [comment] 2022-07-06 11:27
Thanks for pinging me @flodnv 

Personally I don't think we need to make this fix in this issue since - as you mentioned - I'm working on refactoring this one so I will include @sobitneupane 's fix -> And since his proposal was accepted and useful for me I think we should pay him out

**Comment by flodnv** [comment] 2022-07-06 12:52
Ok, thanks for your thoughts! Let's hold this on the refactor, and issue payment once the above assumptions are 100% confirmed 🙇

**Comment by kadiealexander** [comment] 2022-07-07 00:31
Sent you an offer @sobitneupane.

**Comment by sobitneupane** [comment] 2022-07-07 05:28
Hello @kadiealexander, I have received offer but for issue #9424 which is different from this issue (#9418).

**Comment by kadiealexander** [comment] 2022-07-07 07:12
Ahhh sorry @sobitneupane, it's the correct Upwork post I just got the ID wrong in the title. I'll change that now. Please still accept!

**Comment by kadiealexander** [comment] 2022-07-07 07:17
Great catch, sorry @sobitneupane! I've withdrawn that and issued an offer using the correct Upwork issue.

**Comment by kadiealexander** [comment] 2022-08-14 22:31
Still on hold.

**Comment by sobitneupane** [comment] 2022-09-17 03:23
It looks like the issue is already handled.

**Comment by flodnv** [comment] 2022-09-19 11:47
@Beamanator do you think this should be fixed now? If not, where's the refactor issue that could solve this?

**Comment by Beamanator** [comment] 2022-09-19 12:25
Yes this should have been solved! Will find & link the issue here: 👀

**Comment by flodnv** [comment] 2022-09-19 13:57
I test & can confirm this is fixed. @kadiealexander please issue payment to @aswin-s for reporting & @sobitneupane for helping us identify this issue in the code refactors that led to fix this.

**Comment by kadiealexander** [comment] 2022-09-20 19:45
@sobitneupane  - I've issued payment, thanks for your help here!
@aswin-s - have sent you a contract, please accept and I'll get it paid out.

**Comment by kadiealexander** [comment] 2022-09-21 00:52
Everyone is paid!! Thanks team.

**Closed by kadiealexander** 2022-09-21 00:52 UTC
Labels: Exported, External, Engineering, Daily, Improvement, Help Wanted
