### ISSUE TITLE
[$500] iOS -Members- The entered member in compose box is displayed twice and disappears

### ISSUE THREAD

**Issue by kavimuru** [Expensify/App#11863] opened 2022-10-14 18:29 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Open the app
2. Log in with expensifail account ([applausetester+0704sveta@applause.expensifail.com](mailto:applausetester+0704sveta@applause.expensifail.com)
pass: w323052760We)
3.  Navigate back to Workspace editor
4. Click on Manage Members
5. Click on the invite button
6.  Enter expensifail user ([applausetester+1310lsn@applause.expensifail.com](mailto:applausetester+1310lsn@applause.expensifail.com)

## Expected Result:
The member entered in compose box should be displayed once
## Actual Result:
The entered member in compose box is displayed twice and disappears

## Workaround:
unknown

## Platform:

Where is this issue occurring?

- iOS

**Version Number:** 1.2.15-2
**Reproducible in staging?:** y
**Reproducible in production?:** y
**Email or phone of affected tester (no customers):** 
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** 

https://user-images.githubusercontent.com/43996225/195916159-c9c85ef6-ecc1-42a9-8ae0-953290976499.mp4

**Expensify/Expensify Issue URL:** 
**Issue reported by:** applause internal team
**Slack conversation:** 

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

https://user-images.githubusercontent.com/43996225/195916174-04413578-1e32-44db-a88a-cddc795714a6.mp4

**Comment by joelbettner** [comment] 2022-10-14 19:25
Definitely a bug worth fixing. That is some weird auto complete behavior.

**Comment by strepanier03** [comment] 2022-10-15 00:13
Upwork job created:

Internal posting: https://www.upwork.com/ab/applicants/1581075597012160512/suggested
External posting: https://www.upwork.com/ab/applicants/1581075597012160512/job-details

**Comment by narayanaraoiosdev** [comment] 2022-10-15 16:40
Hi 
as of now API is calling on each every letter which is wrong (if we type characters fast there is no need of calling api for each and every letter)  so it creating issue so using de-bouncer we can reduce call and get proper data to display 

I have changed code using de-bouncer now its working fine.

**Comment by sobitneupane** [comment] 2022-10-17 05:38
Were you able to reproduce the issue in simulator @Uros787?

**Comment by sobitneupane** [comment] 2022-10-17 14:09
@Uros787 You have attached video of simulator After fix. Will be able to attach video of physical device before and after fix?

**Comment by sobitneupane** [comment] 2022-10-18 04:57
@Uros787 This issue mainly occurs in iOS physical device and not simulator. So, we should be able to attach video from physical device in the PR. I don't think we can go forward with your proposal if you will not be able to do so.

cc: @ctkochan22

**Comment by strepanier03** [comment] 2022-10-20 16:13
@narayanaraoiosdev - I'm sorry I missed your comment before. 

Please review [propose a solution and get hired for that job](https://github.com/Expensify/App/blob/main/contributingGuides/CONTRIBUTING.md#propose-a-solution-for-the-job) to understand how our hiring process works. 

In this case, a proposal needs to be submitted on the GH and if your proposal is selected you will then be hired in Upwork.

**Comment by strepanier03** [comment] 2022-10-21 17:55
Moved to weekly according to SO since the job exists but we haven't accepted a proposal yet.

**Comment by strepanier03** [comment] 2022-10-24 18:40
💰 Price doubles: [[$500] iOS -Members- The entered member in compose box is displayed twice and disappears](https://github.com/Expensify/App/issues/11863) 💰

**Comment by Uros787** [comment] 2022-10-24 21:28
@sobitneupane 
Here are the videos
After fix:
https://user-images.githubusercontent.com/70144379/197632455-2e7709ab-4433-4fcf-9fc1-2682a874a722.MP4
No more calls on every keystroke which is a massive upgrade than before

Before fix:
https://user-images.githubusercontent.com/70144379/197632486-606c9e77-9680-40b8-b2c8-9031c71c0b54.MP4
Calling on every keystroke, destroying the API client, and costing us API calls

You may notice that we have to wait for a few seconds after the fix. That is because my device is connected through a cable and there is a latency

**Comment by Uros787** [comment] 2022-10-25 14:42
let me know

**Comment by strepanier03** [comment] 2022-10-31 20:17
@sobitneupane - Can we can an update here? Are we accepting @Uros787's proposal?

**Comment by sobitneupane** [comment] 2022-11-01 13:30
Sorry I missed it last week.

I was able to reproduce this issue is IOS simulator with the account: applausetester+0704sveta@applause.expensifail.com, pass: w323052760We

@Uros787 You are proposing to make use of logic used in search page. But search page is almost unusable with the above account for me. It took a long time to update the search page.

**Comment by strepanier03** [comment] 2022-11-01 23:33
No worries @sobitneupane - Last week was a special and busy week for many. Thank you for the update. I'll continue to check daily so I can take any needed action.

**Comment by strepanier03** [comment] 2022-11-04 21:56
@Uros787 - Can you please take a look @sobitneupane question for you so we can keep this one moving forward?

**Comment by sobitneupane** [comment] 2022-11-07 04:19
Hello @Uros787, Thanks for the update.

> If we want to fix the Search page also we can get another issue and I can work on it, to see what is the problem

Since we are dealing with the Search functionality in both the pages, I believe it should be handled in same place. Moreover, we should reuse the same code to implement it not only in these two pages but other pages involving search functionality.

> I recommend that we go with 750ms now. Fixes the issue and isn't laggy anymore.

Tested it. It does not solve the issue.

https://user-images.githubusercontent.com/25876548/200225186-0a901e6d-0773-49b6-bef7-a84fd28e6e49.mov

**Comment by sobitneupane** [comment] 2022-11-07 04:23
@strepanier03 @ctkochan22 
I think we should update the issue title and description as showing entered members twice is not the issue. Those two search results are different. Delay in the functionality is the issue. Users have to wait after typing the users email in search bar for the result to reflect.

**Comment by strepanier03** [comment] 2022-11-08 00:32
@sobitneupane - I'll wait for your testing. It does seem like the search results is a different issue as this GH was specifically for the entered member in the compose box displaying twice before disappearing.

**Comment by sobitneupane** [comment] 2022-11-08 04:02
@strepanier03 
> specifically for the entered member in the compose box displaying twice before disappearing.

They are different members. You can notice in the following video that two users are displayed. But they are different.

https://user-images.githubusercontent.com/25876548/200471379-4ff1b615-3d7b-4b65-b4ab-f1d60ea5d630.mov

You can notice in the following frame that two users are displayed: one is "applausetester+1310lsn@applause.expensifail.com" and other is "applausetester+1310lsn@applause.ex". And it is the expected output. 

<img width="1440" alt="Screenshot 2022-11-08 at 09 39 52" src="https://user-images.githubusercontent.com/25876548/200472103-cdbe5984-0c82-41aa-8808-2d5ff41c1d85.png">

But in those accounts with large number of personal details of other users. The search functionality is so slow that they appear random. When user finishes typing "applausetester+1310lsn@applause.expensifail.com". The result is only reflecting search result for "applausetes". 

cc: @ctkochan22

**Comment by sobitneupane** [comment] 2022-11-08 12:16
I would like to hear from @ctkochan22 at first.

This issue exists in those accounts(account: applausetester+0704sveta@applause.expensifail.com,
pass: w323052760We) which have large number of accounts associated with it. Issue here is:

1. The search functionality is so slow that user have to wait for few seconds for search result to update. This exists in different form in native device and mWeb/Web/Desktop.

     A. In native device (IOS and android), when user types something, it is reflected in search input field but user have to wait for few seconds to see search result.
     Video: https://user-images.githubusercontent.com/43996225/195916159-c9c85ef6-ecc1-42a9-8ae0-953290976499.mp4
     
     B. In mWeb/Web/Desktop, when user types something, it takes some time to update both search input field and search result. As soon as search input field is updated, search result also reflects the change.
     Video: https://user-images.githubusercontent.com/25876548/200225186-0a901e6d-0773-49b6-bef7-a84fd28e6e49.mov

    Do we want to handle both above issues here? Or do you think them to be different issue?
2. This issue is reported for Invite Members page but it exists in Search functionality of other pages like Search Page as well. Do we want to handle this issue for all search functionalities in the app? I think if possible we should make use of same/common code for all search functionality throughout the app.
     
cc: @strepanier03

**Comment by strepanier03** [comment] 2022-11-08 23:40
@ctkochan22 - Eager to hear your opinion here but I feel like there are two issues here and we have a fix for one of them. The second issue is something we could make a separate bug report for which would have its own proposal and pay.

I'll hold on taking any action and check back in tomorrow.

**Comment by ctkochan22** [comment] 2022-11-09 05:08
Is there an issue for the SearchPage? Although they could be fixed as they seem like similar issues, they are ultimately in different places. Lets keep them separate and if this solution works here. We can just apply this change to SearchPage as well.

However, I want some other buy in to this solution.

**Comment by ctkochan22** [comment] 2022-11-09 05:25
In this [proposal](https://github.com/Expensify/App/issues/11863#issuecomment-1279816108), we are thinking about adding a debounce to limit the amount of api commands upon each key change, which is an issue when we have such large search options to get through.

We already do this in SearchPage it seems, and it seems its not working well there either. We already changed the times from 300 to 75 in this [PR](https://github.com/Expensify/App/issues/3822).

**Comment by strepanier03** [comment] 2022-11-10 00:24
Sounds like we're in agreement that fixes to the search page would be a separate issue. Perhaps you'd be willing to report this in [#expensify-open-source](https://expensify.slack.com/archives/C01GTK53T8Q/p1668039635171349) @Uros787 or @sobitneupane so that a bug GH can be made by someone with the ability to recreate and describe the behavior?

**Comment by strepanier03** [comment] 2022-11-11 01:35
Thank you @sobitneupane for reporting this. 

@ctkochan22 and @sobitneupane - Does this mean we are accepting the proposal from @Uros787?

I am out of the office tomorrow. If there is an urgent need on this GH from a BugZero team member, please post in #expensify-open-source for assistance.

**Comment by sobitneupane** [comment] 2022-11-11 01:41
Rather than increasing debounce time, we should optimize performance of search functionality and OptionList. Performance of OptionList is being optimized internally. It is being discussed [here](https://expensify.slack.com/archives/C049HHMV9SM/p1668110448762599).

Discussion: https://expensify.slack.com/archives/C049HHMV9SM/p1668110448762599
> I think [optimizing the performance of the OptionList](https://github.com/Expensify/Expensify/issues/228943), via an internal refactor, should be a WAQ performance issue. Tim Golen is currently assigned to it but hasn’t had time for it yet.

>I think I agree with you. It’s of the earlier issues to the current bug/performance push. Though I also don’t feel like this is the most pressing thing to tackle either from a priorities/roadmap perspective.

**Comment by sobitneupane** [comment] 2022-11-14 15:52
Not overdue. Discussion: https://expensify.slack.com/archives/C049HHMV9SM/p1668110448762599

**Comment by strepanier03** [comment] 2022-11-14 23:33
Following along with the discussion, it's still ongoing, and will check in tomorrow.

**Comment by strepanier03** [comment] 2022-11-18 23:11
We are going to close this in favor of https://github.com/Expensify/Expensify/issues/228943 and once that internal fix is out this should be resolved.

**Closed by strepanier03** 2022-11-18 23:11 UTC
Labels: External, Engineering, Daily, Help Wanted, Bug
