### ISSUE TITLE
 Error message on Add Phone number page is not changing to new selected language

### ISSUE THREAD

**Issue by kavimuru** [Expensify/App#14138] opened 2023-01-09 16:38 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:

1. Go to Settings - Profile - Phone number
2. Input any wrong phone number and password
3. Press Send Verification button, Observe error messages for input fields
4. Change language in another session
5. Observe error messages on Add Phone number page (everything else changed to new selected language)

## Expected Result: 
Error message on Add Phone number page should be changed to new selected language

## Actual Result: 
Error message on Add Phone number page is not changing to new selected language

## Workaround:
unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?

- [ ] MacOS / Chrome / Safari

**Version Number:** v1.2.50-14
**Reproducible in staging?:** y 
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:**  

https://user-images.githubusercontent.com/43996225/211359904-062a2533-0c25-42cc-8b87-1ead119b496c.mp4

https://user-images.githubusercontent.com/43996225/211359943-c272f50d-21a8-4519-9cb8-2a5b60697675.mov

**Expensify/Expensify Issue URL:**
**Issue reported by:** @varshamb 
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1673017112612729

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~0136e59b29ad333b3b</li>
        <li>Upwork Job ID: 1612874139970121728</li>
        <li>Last Price Increase: 2023-01-10</li>
    </ul>
</details>

**Comment by isabelastisser** [comment] 2023-01-10 17:57
Reviewing this now.

**Comment by isabelastisser** [comment] 2023-01-10 18:08
I'm unable to recreate this because I don't have the option to change the language in Echat.

![image](https://user-images.githubusercontent.com/31258516/211628855-2f77ab21-0f29-4c34-9b61-e022ffb78b3e.png)

**Comment by isabelastisser** [comment] 2023-01-10 18:09
@thesahindia or @MonilBhavsar , can you please let me know if you are able to reproduce this?

**Comment by varshamb** [comment] 2023-01-10 18:35
### Proposal

AddSecondaryLoginPage will require refactoring to use the Form.

I can do the refactoring.

**Comment by abdulrahuman5196** [comment] 2023-01-10 18:51
**Proposal**

**Root Cause**
When we get wrong data, we set the error string to be displayed on the validation page directly in the onyx - https://github.com/Expensify/App/blob/main/src/libs/actions/User.js#L152
But this translation only happens when the user presses submit. It won't happen at runtime similar to this bug.

**Solution**
Instead of setting the actual error string in Onyx, set the localize key in the onyx. And localize the error directly in the view.
I have added one sample for the error mentioned in the bug, this sample can be extended to other error strings in the phonenumber flow

```diff
diff --git a/src/libs/actions/User.js b/src/libs/actions/User.js
index 532e7bb04c..72946e3d41 100644
--- a/src/libs/actions/User.js
+++ b/src/libs/actions/User.js
@@ -149,7 +149,7 @@ function setSecondaryLoginAndNavigate(login, password) {
             error = 'This login already belongs to an existing Expensify account.';
         }
         if (error.includes('I couldn\'t validate the phone number')) {
-            error = Localize.translateLocal('common.error.phoneNumber');
+            error = 'common.error.phoneNumber';
         }
 
         Onyx.merge(ONYXKEYS.USER, {error});
diff --git a/src/pages/settings/AddSecondaryLoginPage.js b/src/pages/settings/AddSecondaryLoginPage.js
index 892a75153d..1522407305 100755
--- a/src/pages/settings/AddSecondaryLoginPage.js
+++ b/src/pages/settings/AddSecondaryLoginPage.js
@@ -140,7 +140,7 @@ class AddSecondaryLoginPage extends Component {
                     </View>
                     {!_.isEmpty(this.props.user.error) && (
                         <Text style={styles.formError}>
-                            {this.props.user.error}
+                            {this.props.translate(this.props.user.error)}
                         </Text>
                     )}
                 </ScrollView>

```

https://user-images.githubusercontent.com/46707890/211636598-16ff65eb-d60e-4ea1-8cfc-baa9c661fbba.mov

**Comment by Prince-Mendiratta** [comment] 2023-01-10 19:01
# Proposal
## RCA
The reason that the error message is not translated is because we are not using the standard Form.js for this component. Moreover, the error message isn't translated either.

# Solution 1
We can refactor the component to use Form.js, which will trigger the validation method when the component is re rendered on localization change.

# Solution 2
We can make use of the `componentDidUpdate()` to trigger the error message to be refreshed on localization change.

```diff
/**
diff --git a/src/libs/actions/User.js b/src/libs/actions/User.js
index 532e7bb04c..7d0ef74128 100644
--- a/src/libs/actions/User.js
+++ b/src/libs/actions/User.js
@@ -398,6 +398,11 @@ function clearUserErrorMessage() {
     Onyx.merge(ONYXKEYS.USER, {error: ''});
 }
 
+function setErrorMessage(key) {
+    const error = Localize.translateLocal(key);
+    Onyx.merge(ONYXKEYS.USER, {error});
+}
+
 /**
  * Clear the data about a screen share request from Onyx.
  */
@@ -471,4 +476,5 @@ export {
     deletePaypalMeAddress,
     addPaypalMeAddress,
     updateChatPriorityMode,
+    setErrorMessage,
 };
diff --git a/src/pages/settings/AddSecondaryLoginPage.js b/src/pages/settings/AddSecondaryLoginPage.js
index 892a75153d..3e5a4e980f 100755
--- a/src/pages/settings/AddSecondaryLoginPage.js
+++ b/src/pages/settings/AddSecondaryLoginPage.js
@@ -64,6 +65,16 @@ class AddSecondaryLoginPage extends Component {
         this.setState({login});
     }
 
+    componentDidUpdate(prevProps) {
+        if (prevProps.preferredLocale === this.props.preferredLocale) {
+            return;
+        }
+
+        User.setErrorMessage('common.error.phoneNumber');
+    }
+
```

https://user-images.githubusercontent.com/54077356/211638524-4dbb2318-a7a4-4e1d-9c45-a3b7c9dc1611.mp4

**Comment by marcochavezf** [comment] 2023-01-10 19:09
As mentioned [here](https://github.com/Expensify/App/pull/13810#issuecomment-1374485335), I think we might want to refactor AddSecondaryLoginPage to use Form, since we're already validating the form [here](https://github.com/Expensify/App/pull/13810/files) if the language changes in Form.

**Comment by thesahindia** [comment] 2023-01-10 19:59
This issue is a duplicate and it is present at multiple places, some instances were mentioned at https://github.com/Expensify/App/issues/8714. We haven't decided how we wanna approach these issues ([discussion](https://expensify.slack.com/archives/C01GTK53T8Q/p1650963741424669?thread_ts=1650386332.857569&cid=C01GTK53T8Q)) I think we will need to discuss it in slack first but as mentioned by @iwiznia, we are not trying to fully internationalize the app right now. So I think we should just close this and discuss this later.

**Comment by varshamb** [comment] 2023-01-10 20:29
@thesahindia Just in case you missed [this](https://github.com/Expensify/App/issues/14138#issuecomment-1377723920)

**Comment by iwiznia** [comment] 2023-01-10 22:40
Is that validation happening on the frontend or the server? If the former, I think this is a bug (though quite an obscure one that needs 2 tabs), but if the latter, I think we should close.

**Comment by thesahindia** [comment] 2023-01-11 07:50
Yeah, it's from the backend.

**Comment by MonilBhavsar** [comment] 2023-01-11 10:06
Hmm, this is workflow is still using Deprecated API and requires to be cleaned up. That will probably fix this issue. Going to make in `Internal`

**Comment by isabelastisser** [comment] 2023-01-19 18:54
not overdue.

**Comment by isabelastisser** [comment] 2023-01-30 18:41
Not overdue, on hold.

**Comment by MonilBhavsar** [comment] 2023-02-17 07:32
Still on hold

**Comment by MonilBhavsar** [comment] 2023-02-27 10:28
Still on hold

**Comment by MonilBhavsar** [comment] 2023-03-13 05:55
Still on hold

**Comment by isabelastisser** [comment] 2023-03-21 20:51
Still on hold - internal.

**Comment by MonilBhavsar** [comment] 2023-03-30 12:20
Still on hold

**Comment by isabelastisser** [comment] 2023-04-10 13:29
Not overdue, on hold!

**Comment by isabelastisser** [comment] 2023-04-19 13:51
Not overdue, on hold!

**Comment by isabelastisser** [comment] 2023-05-01 15:14
Not overdue.

**Comment by isabelastisser** [comment] 2023-05-10 23:41
Based on the latest comments, I'm closing this!

**Closed by isabelastisser** 2023-05-10 23:41 UTC
Labels: Weekly, Internal, Bug
