### ISSUE TITLE
Expense - The app crashes when the administrator opens the details of a paid expense

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#47940] opened 2024-08-23 18:07 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 9.0.24-0
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**If this was caught during regression testing, add the test name, ID and link from TestRail:** https://expensify.testrail.io/index.php?/tests/view/4888153
**Email or phone of affected tester (no customers):** sustinov@applausemail.com
**Issue reported by:** Applause - Internal Team

## Action Performed:
Create a new HT administrator account, create a new WS and invite a new HT employee account. For convenience, it is better to perform the steps in two tabs opened simultaneously.
Step:
1. Open https://staging.new.expensify.com/
2. Log in under the employee's account
3. Submit any manual expense in the WS room
4. Log in under the administrator account
5. Click on the expense payment button “Pay *amount* elsewhere”
6. Quickly click on the expense itself to open the details
7. Repeat steps 2-6 several times.

## Expected Result:
The details of the paid expense should be opened by the adminstrator without crashing the application

## Actual Result:
The app crashes when the administrator opens the details of a paid expense

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [ ] Android: mWeb Chrome
- [x] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details> 

https://github.com/user-attachments/assets/fbf1b57b-12d5-42d5-9b40-8a39f3787181

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by lanitochka17** [comment] 2024-08-23 18:08
@Christinadobrzyn  FYI I haven't added the External label as I wasn't 100% sure about this issue. Please take a look and add the label if you agree it's a bug and can be handled by external contributors

**Comment by lanitochka17** [comment] 2024-08-23 18:08
We think that this bug might be related to #wave-collect - Release 1

**Comment by FitseTLT** [comment] 2024-08-23 18:20
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
The app crashes when the administrator opens the details of a paid expense

### What is the root cause of that problem?
The root cause is `policyTagsList` has array elements which are not objects with `tag` prop so here
https://github.com/Expensify/App/blob/6488908562131e5e411275059bb73b578a2cf420/src/components/ReportActionItem/MoneyRequestView.tsx#L219-L220
`hasEnabledTags` expects all array elements to be in that structure so calls `Object.value` on `tag` prop of the array item here
https://github.com/Expensify/App/blob/6488908562131e5e411275059bb73b578a2cf420/src/libs/OptionsListUtils.ts#L1317
So TypeError `Cannot Conver null or undefined to object` occurs and the app crashes
### What changes do you think we should me in order to solve the problem?

We need to implement a safety so change it to
```
    const policyTagValueList = policyTagList.map(({tags}) => Object.values(tags ?? {})).flat();

```
### What alternative solutions did you explore? (Optional)

**Comment by FitseTLT** [comment] 2024-08-23 20:17
> I'm curious why the fallback values in this file are set to empty strings.
> 
> https://github.com/Expensify/App/blob/9f344833d6abb864d3dc0ccbd578ff4acb20f633/src/components/ReportActionItem/MoneyRequestView.tsx#L687-L698
> 
> 
> This change was introduced in [this PR](https://github.com/Expensify/App/pull/42571), so I'm tagging @kubabutkiewicz and @parasharrajat since they worked on it. Was this change intentional?

There is no way this could be intentional. They tried to give a string fallback in the PR but empty string means fetch the whole collection which is a mistake we often make.

**Comment by bernhardoj** [comment] 2024-08-24 02:24
Dupe of https://github.com/Expensify/App/issues/47542

**Closed** 2024-08-25 18:20 UTC
Labels: Daily, Bug
