### ISSUE TITLE
Android - PayPal - PayPal method is not deleted after deletion on another device

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#11470] opened 2022-09-30 13:52 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Login with account A on the main testing device and on another device (Android App and mWeb/Safari in my case)
2. In the main testing device, Navigate to Settings > Payments
3. Click/Tap on "Add Payment Method" and Click/Tap on "PayPal.me"
4. Enter any PayPal.me name, then click “Add PayPal account” - Verify the account is added
5. Go to another device and Verify the account is added also
6. Delete the PayPal account on the main testing device
7. Verify the account is deleted on another device

## Expected Result:
The PayPal method should be deleted on the another device immediately after deleting it on the main device

## Actual Result:
PayPal method disappears on the another device only after re-login

## Workaround:
Unknown

## Platform:

Where is this issue occurring?

- Web
- iOS
- Android
- Desktop App
- Mobile Web

**Version Number:** 1.2.10.0

**Reproducible in staging?:** Yes

**Reproducible in production?:** Yes

**Email or phone of affected tester (no customers):** any

**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Notes/Photos/Videos:** Any additional supporting documentation

https://user-images.githubusercontent.com/93399543/193284937-ba1e8fb4-7e32-4ab9-893d-814f077a205e.mp4

https://user-images.githubusercontent.com/93399543/193284942-58cef77d-97f8-4fbf-b000-a9c807f7f1d8.mp4

**Expensify/Expensify Issue URL:** 

**Issue reported by:** Applause - Internal Team

**Slack conversation:** 

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by PauloGasparSv** [comment] 2022-09-30 16:09
Reproduced it here, it looks like an Offline First Api problem so I'm keeping this with me!

**Comment by mvtglobally** [comment] 2022-10-18 11:28
Issue not reproducible during KI retests. (First week)

**Comment by mvtglobally** [comment] 2022-10-24 18:37
Issue not reproducible during KI retests. (Second week)

**Comment by mvtglobally** [comment] 2022-11-03 03:09
Issue not reproducible during KI retests. (Third week) Closing

**Closed by mvtglobally** 2022-11-03 03:09 UTC
Labels: Reviewing, Engineering, Monthly, Bug
