### ISSUE TITLE
[$500] LHN - All chats disappear if user is added to workspace while on setting page

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#12020] opened 2022-10-19 23:15 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Go to https://staging.new.expensify.com/ on 2 devices, web and mweb, login with different accounts
2. On mWeb device open Settings page
3. On Web invite the other user to workspace
4. On mWeb close Settings page

## Expected Result:
User on mWeb should see all previous chats and maybe new workspace chat/room

## Actual Result:
Empty chat page is displayed. It looks like all chats disappeared

## Workaround:
Unknown

## Platform:

Where is this issue occurring?

- Web
- iOS
- Android
- Desktop App
- Mobile Web

**Version Number:** 1.2.18.2

**Reproducible in staging?:** Yes

**Reproducible in production?:** Yes

**Email or phone of affected tester (no customers):** 

**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Notes/Photos/Videos:** Any additional supporting documentation

https://user-images.githubusercontent.com/93399543/196821735-e27585f6-7f7a-4a82-9e42-c9cea1d1a906.mp4

https://user-images.githubusercontent.com/93399543/196821736-0caa5293-a682-4d93-b771-83cc7260526b.mp4

**Expensify/Expensify Issue URL:** 

**Issue reported by:** Applause - Internal Team

**Slack conversation:** 

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by CortneyOfstad** [comment] 2022-10-25 12:31
Job Posting here — https://www.upwork.com/jobs/~016433cb5b74aa9b47

**Comment by mananjadhav** [comment] 2022-10-31 03:42
Waiting for proposals.

**Comment by mvtglobally** [comment] 2022-11-03 03:17
Issue not reproducible during KI retests. (First week)

**Comment by CortneyOfstad** [comment] 2022-11-03 11:50
Was pinged to double the price 👍

**Comment by mananjadhav** [comment] 2022-11-05 20:10
I can't reproduce this on the staging? Should we for another KI and close this?

@CortneyOfstad @srikarparsi Is one of you able to reproduce this?

**Comment by srikarparsi** [comment] 2022-11-07 13:27
hey @mananjadhav, tried it twice with two different accounts but wasn't able to reproduce either time. @CortneyOfstad I'm not entirely sure how the process works but I think we can pay @kbecciv for reporting and then close out the issue.

**Comment by mananjadhav** [comment] 2022-11-07 13:35
Okay yeah I thought so.

@kbecciv is from Applause QA, so I am guessing no payments here. We're good to close this.

**Comment by kbecciv** [comment] 2022-11-07 13:50
No payment

**Comment by CortneyOfstad** [comment] 2022-11-07 15:16
Alright, closing! Thanks!

**Closed by CortneyOfstad** 2022-11-07 15:16 UTC
Labels: External, Engineering, Weekly, Help Wanted
