### ISSUE TITLE
[HOLD for payment 2024-11-13] [$250] RBR isn't displayed when scanning failed

### ISSUE THREAD

**Issue by m-natarajan** [Expensify/App#50799] opened 2024-10-15 13:45 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 9.0.49-0
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** @DylanDylann 
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1728897430938149

## Action Performed:
1. Login to new account
2. Create new workspace
3. Create a manual request on the above workspace
4. Next, create a scan request with wrong image on the above workspace
5. Waiting for scanning
6. Go to transaction thread and see that there are no RBR on LHN

## Expected Result:
RBR is displayed when scanning failed
## Actual Result:
RBR isn't displayed when scanning failed
## Workaround:
unknown
## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

https://github.com/user-attachments/assets/2309fdba-f444-48eb-b3c0-59c4fd32cc31

https://github.com/user-attachments/assets/43506205-1a56-4e2c-921f-07be06813373

<details>
  <summary>Add any screenshot/video evidence</summary>

  
</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~021846286418177490016</li>
        <li>Upwork Job ID: 1846286418177490016</li>
        <li>Last Price Increase: 2024-10-22</li>
<li>Automatic offers: </li>
<ul>
<li>DylanDylann | Contributor | 104595958</li>
<li>daledah | Contributor | 104676254</li>
</ul></li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @isabelastisser</details>

**Comment by DylanDylann** [comment] 2024-10-15 16:32
@isabelastisser  I discovered this bug while reviewing [this PR](https://github.com/Expensify/App/pull/50468), when implementing PR to fix this issue, we also need to ensure that RBR in scanning failed works well for debug feature

**Comment by pac-guerreiro** [comment] 2024-10-15 18:51
I can apply the fix for this in https://github.com/Expensify/App/pull/50468 before it gets merged

**Comment by FitseTLT** [comment] 2024-10-15 19:00
@pac-guerreiro The issue is totally unrelated with the PR, it has nothing to do with `Debug` (it's just only linked because @DylanDylann found it coincedentally reviewing the pr) I don't see it logical to fix it there and, of course, as we have proposed appropriate fixes here.
@DylanDylann WDYT

**Comment by DylanDylann** [comment] 2024-10-16 04:39
@getusha Could I take over this from you? 

I think we should fix this issue on https://github.com/Expensify/App/pull/50468 to ensure RBR in scanning failed works well for the debug feature

cc @pac-guerreiro

**Comment by DylanDylann** [comment] 2024-10-16 04:55
If we consider this issue only, we should apply both proposals (@FitseTLT and @daledah) because we are using `hasErrors || hasViolations`. @daledah fixes the problem on hasViolations, @FitseTLT fixes the problem on hasErrors

**Comment by FitseTLT** [comment] 2024-10-16 11:04
> If we consider this issue only, we should apply both proposals (@FitseTLT and @daledah) because we are using `hasErrors || hasViolations`. @daledah fixes the problem on hasViolations, @FitseTLT fixes the problem on hasErrors

I disagree with this @DylanDylann because, firstly, we don't normally show rbr for warning type violations we only allowed that for hold as an exception. Secondly, we handle the missing smart scan fields via `hasMissingSmartscanFields ` in other places like for iouReport [here](https://github.com/Expensify/App/blob/8ff185a05937366c40898f8ab6510fbd765a8838/src/libs/OptionsListUtils.ts#L516) and for the current case of transactionThread report we already have the code here
https://github.com/Expensify/App/blob/8ff185a05937366c40898f8ab6510fbd765a8838/src/libs/OptionsListUtils.ts#L504-L512
The problem is we forgot `ONYXKEYS.COLLECTION.REPORT_ACTIONS` prefix as I have discussed in my proposal and that is the correct RCA.

**Comment by DylanDylann** [comment] 2024-10-16 11:06
> we don't normally show rbr for warning type violations 

@FitseTLT Wait wait, why do you think so?

**Comment by FitseTLT** [comment] 2024-10-16 11:41
>@FitseTLT Wait wait, why do you think so? Please correct me If I am missing anything

We are returning false if permission for dupe detection is off
https://github.com/Expensify/App/blob/8ff185a05937366c40898f8ab6510fbd765a8838/src/libs/TransactionUtils/index.ts#L749-L750
that clearly shows an intent to disable as long as we are on beta for dupe detection so will require separate discussion if we need to allow it. And regarding the current issue, missing scanning fields, there is a clear way to handle it, which checks for missing fields, that is used in all other places so in this case we need to only fix the problem I mentioned to make the already existing code to work.

**Comment by isabelastisser** [comment] 2024-10-22 17:23
@getusha, please provide an update, thanks! I will DM you for visibility.

**Comment by DylanDylann** [comment] 2024-10-22 17:30
@isabelastisser Could you please check this comment? I reported this bug and have more context here

**Comment by isabelastisser** [comment] 2024-10-22 18:10
@DylanDylann, are you referring to this comment: https://github.com/Expensify/App/issues/50799#issuecomment-2415715960?

@getusha, can you please review the discussion above and weigh in? Thanks!

**Comment by DylanDylann** [comment] 2024-10-23 01:54
@isabelastisser Ahh yes 😄

**Comment by DylanDylann** [comment] 2024-10-23 09:52
The RBR will be displayed if hasErrors is true or hasViolation is true, But both logics are incorrect. Although we only need to fix one of them to solve this issue, I still prefer to fix both problems in hasErrors and hasViolation

So I suggest applying both proposals and split compensation to both @daledah and @FitseTLT 

🎀 👀 🎀 C+ reviewed

**Comment by FitseTLT** [comment] 2024-10-23 10:06
I really have doubts whether we have to/ need to update the violations logic here and start showing RBR for all warning violations. @Julesssss I recommend you to see the discussion https://github.com/Expensify/App/issues/50799#issuecomment-2416480785 Thx

**Comment by DylanDylann** [comment] 2024-10-23 10:43
https://github.com/Expensify/App/blob/4f0ca943a51e340652885c3c1fa3dd4434b91e3f/src/libs/TransactionUtils/index.ts#L793-L796

I agree with @daledah at this point, `hasWarningTypeViolation` should return true in this case because it is correct with the definition of this function. 

@FitseTLT Could you give a reference or conversations to province that you say [here](https://github.com/Expensify/App/issues/50799#issuecomment-2416564625)

**Comment by FitseTLT** [comment] 2024-10-23 11:32
>it is correct with the definition of this function.

@DylanDylann Yes you are correct in terms of the name of the function `hasWarningTypeViolation`; it should have had a different name. I am only discussing the point of whether we are sure to start showing RBR for all warning type of violations. Currently, we are only showing RBR for dupe detection (which is under beta) and the RBR due to missing scanned fields is already being dealt with https://github.com/Expensify/App/blob/8ff185a05937366c40898f8ab6510fbd765a8838/src/libs/OptionsListUtils.ts#L504-L512 
the only problem being the bug I mentioned in my proposal.

**Comment by isabelastisser** [comment] 2024-10-25 19:48
@DylanDylann, please provide an update. Thanks!

**Comment by DylanDylann** [comment] 2024-10-28 07:06
@Julesssss This is [my review](https://github.com/Expensify/App/issues/50799#issuecomment-2431563705). All yours

**Comment by Julesssss** [comment] 2024-10-28 10:33
Hi @FitseTLT just to clarify, your point is that in the future _we might not_ choose to show warning for all warning types [here](https://github.com/Expensify/App/blob/4f0ca943a51e340652885c3c1fa3dd4434b91e3f/src/libs/TransactionUtils/index.ts#L796-L802)?

**Comment by FitseTLT** [comment] 2024-10-28 11:55
> Hi @FitseTLT just to clarify, your point is that in the future _we might not_ choose to show warning for all warning types [here](https://github.com/Expensify/App/blob/4f0ca943a51e340652885c3c1fa3dd4434b91e3f/src/libs/TransactionUtils/index.ts#L796-L802)?

Not about the future but currently it is obvious that we are only showing when dupe detection beta is on 
https://github.com/Expensify/App/blob/5103b4bd53ae74dcb301b8450f7046e82dc311d3/src/libs/TransactionUtils/index.ts#L829-L830
and focusing on the scanning missing fields in this issue it should be handled via `hasMissingSmartscanFields` as we are correctly doing for instance for combined report (that's why we can't reproduce this issue when only one transaction is present in an iou report) case here
https://github.com/Expensify/App/blob/8ff185a05937366c40898f8ab6510fbd765a8838/src/libs/OptionsListUtils.ts#L520
Only, the problem occurs for transaction thread case here
https://github.com/Expensify/App/blob/8ff185a05937366c40898f8ab6510fbd765a8838/src/libs/OptionsListUtils.ts#L506
For the reason I mentioned in my proposal. BTW has scanning missing fields is different from the warning type violation because although there is warning type violation for missing amount there is no violation for instance for missing merchant case but we are currently showing RBR for missing merchant field case and that is handled only via `hasMissingSmartscanFields` so in my opinion, with regard to this issue, I think it should be handled via hasMissingSmartscanFields and not sure we should allow showing RBR for warning type violation which we purposely disallowed(until dupe beta is done).

**Comment by Julesssss** [comment] 2024-10-28 12:33
Thanks for clairfying further. 

> I think it should be handled via `hasMissingSmartscanFields` and not sure we should allow showing RBR for warning type violation which we purposely disallowed(until dupe beta is done).

I'm going to see if I can find out more about our plans internally. But I do think we want to start showing RBR for all warning type of violations.

**Comment by Julesssss** [comment] 2024-10-28 16:32
Alright, so we do in fact want to show the RBR for all warnings.

**Comment by DylanDylann** [comment] 2024-10-29 02:46
@Julesssss What do you think about split compensation for both @daledah and @FitseTLT as per this [comment](https://github.com/Expensify/App/issues/50799#issuecomment-2431563705)

**Comment by DylanDylann** [comment] 2024-10-30 04:48
@MelvinBot No, we close to the implementation phase

**Comment by DylanDylann** [comment] 2024-10-30 04:49
@Julesssss Friendly bump

**Comment by Julesssss** [comment] 2024-10-31 10:14
> @Julesssss What do you think about split compensation for both @daledah and @FitseTLT as per this [comment](https://github.com/Expensify/App/issues/50799#issuecomment-2431563705)

We can. But who would like to implement?

**Comment by DylanDylann** [comment] 2024-10-31 10:17
@daledah @FitseTLT Who wants to implement PR? I think we can split 150$ for the implementer and 100$ for the rest one

**Comment by DylanDylann** [comment] 2024-10-31 10:29
Perfect

cc @Julesssss

**Comment by DylanDylann** [comment] 2024-11-06 03:40
# BugZero Checklist:

- [ ] **[Contributor]** Classify the bug:

<details>
<summary>Bug classification</summary>


Source of bug:
  - [ ] 1a. Result of the original design (eg. a case wasn't considered)
  - [ ] 1b. Mistake during implementation
  - [ ] 1c. Backend bug
  - [ ] 1z. Other:

Where bug was reported:
  - [ ] 2a. Reported on production
  - [ ] 2b. Reported on staging (deploy blocker)
  - [ ] 2c. Reported on a PR
  - [ ] 2z. Other:

Who reported the bug:
  - [ ] 3a. Expensify user
  - [ ] 3b. Expensify employee
  - [ ] 3c. Contributor
  - [ ] 3d. QA
  - [ ] 3z. Other:

</details>

- [ ] **[Contributor]** The offending PR has been commented on, pointing out the bug it caused and why, so the author and reviewers can learn from the mistake.

    Link to comment:

- [ ] **[Contributor]** If the regression was CRITICAL (e.g. interrupts a core flow) A discussion in [#expensify-open-source](https://app.slack.com/client/E047TPA624F/C01GTK53T8Q) has been started about whether any other steps should be taken (e.g. updating the PR review checklist) in order to catch this type of bug sooner.

    Link to discussion:

- [ ] **[Contributor]** If it was decided to create a regression test for the bug, please propose the [regression test](https://github.com/Expensify/App/blob/main/contributingGuides/REGRESSION_TEST_BEST_PRACTICES.md) steps using the template below to ensure the same bug will not reach production again.

<details>
<summary>Regression Test Proposal Template</summary>


- [ ] **[BugZero Assignee]** Create a GH issue for creating/updating the regression test once above steps have been agreed upon.

    Link to issue:

## Regression Test Proposal
### Precondition:


-

### Test:


1.

Do we agree 👍 or 👎


</details>

**Comment by FitseTLT** [comment] 2024-11-06 12:02
@isabelastisser It is to remind you the payment setup for this issue it's $100 for me and $150 for @daledah based on https://github.com/Expensify/App/issues/50799#issuecomment-2449505627 Thx!

**Closed** 2024-11-13 21:41 UTC
Labels: External, Daily, Awaiting Payment, Bug

**Comment by DylanDylann** [comment] 2024-11-14 03:20
@isabelastisser In this issue, we split the compensation to two contributors (@daledah and @FitseTLT). I am C+ on this issue and I should get paid 250$ for this work. Thanks

**Comment by isabelastisser** [comment] 2024-11-14 19:19
@DylanDylann, sorry for the confusion! I've processed your payment in Upwork now. Thanks!
