### ISSUE TITLE
[$1000] Set password - Error reappears in the password field on entering a character after clicking eye icon previously   reported by @thesahindia

### ISSUE THREAD

**Issue by kavimuru** [Expensify/App#11403] opened 2022-09-28 23:41 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Logout
2. Visit https://new.expensify.com/setpassword/12252246/NCSQXMADP
3. Type 123 and click on eye icon (you will see error)
4. Press backspace (error won't go away)
5. Delete all the chars (error will go away)
6. Enter a new character (error will show up again)

## Expected Result:
The error shouldn't be shown after tapping on eye icon and the error should go away after making a change

## Actual Result:
Error doesn't go away and it shows after tapping on eye icon

## Workaround:
Unknown

## Platform:

Where is this issue occurring?

- Web
- iOS
- Android
- Desktop App
- Mobile Web

**Version Number:** 1.2.9-0
**Reproducible in staging?:** y
**Reproducible in production?:** y
**Email or phone of affected tester (no customers):** 
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** 
**Expensify/Expensify Issue URL:** 
**Issue reported by:** @thesahindia 
**Slack conversation:** https://expensify.slack.com/archives/C01GTK53T8Q/p1663245529886089

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by greg-schroeder** [comment] 2022-09-29 23:25
https://user-images.githubusercontent.com/29386373/193159234-f9a4c138-0f17-462f-bbfe-719ca9a8b436.mov

**Comment by mallenexpensify** [comment] 2022-09-30 19:57
Posted https://www.upwork.com/jobs/~01e005c9122cfd5420 
@kevinksullivan auto-assigned to you, I'm going to be OOO for a month. Thx

**Comment by mallenexpensify** [comment] 2022-10-04 18:47
@kevinksullivan  assigned myself and unassigned you cuz I'm NOT going to be OOO the next month ¯\_(ツ)_/¯

**Comment by tienifr** [comment] 2022-10-05 10:28
**### Proposal**

**### Problem**
This issue is from `NewPasswordForm.js`
It has a state is `passwordHintError` which was defaultly set to false. When this state is true and the password entered by user not match the required structure the message below will change to red to alert the user

Now in our code the logic to set `passwordHintError` to true is located in onBlur function of text input. When we click to eye icon onBlur will be executed and it will turn red

Beside we not have a logic to set `passwordHintError` to false when we start to type password again so the message still red when user change the password

**### Solution**
I will move `onBlur` property of input text to the view which wrap the input + eye icon so that when we click outside the view component logic set `passwordHintError` will be implemented

In web when we "click" on eye icon it will auto unfocus the view and event onBlur of view will be executed and in mobile clic to eye icon will not be blur the view wrapping it. So we will seperate BaseTextInput to 2 version BaseTextInput.native.js use for mobile to use old logic and BaseTextInput.js use to fix this problem in web by fix the logic of onBlur function to check if we click the component outside the view, onBlur function will be executed.

Beside I will add some logic to onChange of text input to reset passwordHintError to false when user change the password entered

Code change : [tienifr/App: Pull Request 2](https://github.com/tienifr/App/pull/2)

**Comment by mananjadhav** [comment] 2022-10-05 19:00
Thanks for the proposal @tienifr. I am convinced with your cause of the issue, but not the implementation. Changing the `onBlur` for the `TextInput` doesn't sound right to me. This could impact a lot of components.

Can we cater this to `NewPasswordForm` please?

@tgolen What are your thoughts?

**Comment by tienifr** [comment] 2022-10-07 06:47
Thanks for the reiview @mananjadhav. I have new option to address this problem, please check it 

##Updated Proposal

###Solution

Cause this problem occur in web only, ( in mobile when we click eye icon the text input not be out focus ) so that I will fix logic of onBlur function in `NewPasswordForm.js`, will check if we click outside the component wrapping the input and eye icon, the state will be reset

Code change : [tienifr/App: Pull Request 4](https://github.com/tienifr/App/pull/4)

Change demo : 
https://user-images.githubusercontent.com/113963320/194043070-1e215913-ec84-4719-975e-1ea62c956594.mp4

**Comment by mananjadhav** [comment] 2022-10-07 09:21
@tienifr  Your updated proposal [here](https://github.com/Expensify/App/issues/11403#issuecomment-1271179269) looks good to me. But what here's what I would do, instead of changing the imports.

1. I'll move the `didClickOutsideInputField` to `src/libs/didClickOutsideInputField` with `index.js` (for the web and mweb part)  and `index.native.js` (which consists of your `return true`) logic.

2. I won't move `NewPasswordForm` to a new component and just import the above method in the existing component.

Let me know what you think about this?


@tgolen The above proposal with proposed changes looks good to me. 

🎀 👀 🎀 
C+ reviewed

**Comment by tienifr** [comment] 2022-10-10 07:52
@mananjadhav I think your implementation will be better. I have update code change to follow it 

## Updated Proposal

### Solution

Cause this problem occur in web only, ( in mobile when we click eye icon the text input not be out focus ) so that I will fix logic of onBlur function in `NewPasswordForm.js`, will check if we click outside the component wrapping the input and eye icon, the state will be reset

Code change : [tienifr/App: Pull Request 4](https://github.com/tienifr/App/pull/4) (changed)

**Comment by tienifr** [comment] 2022-10-10 08:27
@mananjadhav I think your implementation will be better. I have update code change to follow it, please check again

## Updated Proposal

### Solution

Cause this problem occur in web only, ( in mobile when we click eye icon the text input not be out focus ) so that I will fix logic of onBlur function in `NewPasswordForm.js`, will check if we click outside the component wrapping the input and eye icon, the state will be reset

Code change : [tienifr/App: Pull Request 4](https://github.com/tienifr/App/pull/4) (changed)

**Comment by mananjadhav** [comment] 2022-10-10 17:06
Thanks for the update @tienifr. We're now waiting for a comment from @tgolen.

**Comment by tgolen** [comment] 2022-10-10 20:30
OK, I looked at the proposal and I have a few questions.

1. I understand that the problem only happens on web, but is there any reason the same `didClickOutsideInputField()` logic can't be run on all platforms? Does it break native if that logic runs on native? Rather than just splitting the code based on the reason "it only affects one platform", we should always strive to keep the code as consistent across platforms as possible.
2. The logic added to `onChangeText` should be moved inside of a class method

> Now in our code the logic to set passwordHintError to true is located in onBlur function of text input

3. Is this the best place to have the logic to set `passwordHintError` to `true`? Is there a better place? What about as part of the form validation? It seems like that is a better place to have logic related to displaying errors

**Comment by tgolen** [comment] 2022-10-11 15:22
OK, thanks!

1. Thank you for explaining that. Is there any other work around you can think of which doesn't rely on `relatedTarget`? I just want to be sure that we're exhausting all possible options before choosing this solution.
2. Thanks for moving that!
3. OK, I think I am following that. I guess it's OK to leave it where it's at, but it just doesn't seem totally right to me

**Comment by tienifr** [comment] 2022-10-14 03:42
Hi @tgolen. I have some update about your question 

1. I have spent time to research a new approach for this issue but I can not see any way can work. So with me, current solution is the only way 
2. and 3. Thanks for your agreement please tell me if the 1. issue is approved

**Comment by mallenexpensify** [comment] 2022-10-14 19:09
Thanks @aimane-chnaif . Unable to reproduce. It appears https://github.com/Expensify/App/issues/10555 is the first reported bug so this report from @thesahindia doesn't appear to be eligible for compensation.  Sound right?  Anyone else due compensation? Double checking before closing

**Comment by mananjadhav** [comment] 2022-10-14 19:27
@mallenexpensify I had some query related to this. Asked [here](https://expensify.slack.com/archives/C02NK2DQWUX/p1665775098505089?thread_ts=1665770562.144299&cid=C02NK2DQWUX) and tagged you.

**Comment by thesahindia** [comment] 2022-10-14 22:21
The issue is not related to eye icon only, the validation gets triggered at onBlur so the error will be shown after clicking outside the input and the main issue here is that on clearing the whole input the error goes away but it shows again when you start typing.

I am on Mobile right now and it doesn't allow me to record screen at set password page, will attach the video from mac in the morning.

**Comment by tsa321** [comment] 2022-10-16 12:49
Maybe the expected behavior: 
Let's don't disable `Set password` button.
Red color message should be displayed only when user click or press `Set password`. 
If user start typing on `set password box` again, change red color into black again, even if typed password is not qualified as password yet. If user press `Set password` again and password is not qualified, then change back to red color message.

**Comment by mallenexpensify** [comment] 2022-10-18 22:18
@thesahindia @mananjadhav @tsa321 are you able to reproduce? If so, I'll double the price of the job

**Comment by tsa321** [comment] 2022-10-18 23:12
@mallenexpensify based on the title of this issue this issue triggered after clicking eye icon,
and actually it is not only triggered by clicking eye icon but triggered by actions, it is explained in @thesahindia [comment](https://github.com/Expensify/App/issues/11403#issuecomment-1279532017). 

For this particular eye icon click, the problem is solved but not for other actions.
So need designer User experience opinion on this issue and need expected behavior of actions related to password input. 
and I am proposing expected behavior [here](https://github.com/Expensify/App/issues/11403#issuecomment-1279963289).

**Comment by mallenexpensify** [comment] 2022-10-26 14:52
Thanks @tsa321 , I doubled the price to $500.   
https://www.upwork.com/jobs/~01e005c9122cfd5420

Regarding bugs and proposed fixes being similar, but _maybe_ not the same, if we're unsure, let's push forward to fix both then find out.  We'd rather move forward quickly and potentially pay multiple contributors for their work then have a known bug not get worked on.

**Comment by mallenexpensify** [comment] 2022-11-03 22:41
Price Doubled to $1000
https://www.upwork.com/jobs/~01e005c9122cfd5420

**Comment by huzaifa-99** [comment] 2022-11-04 02:10
> Maybe the expected behavior:
> Let's don't disable `Set password` button.
> Red color message should be displayed only when user click or press `Set password`.
> If user start typing on `set password box` again, change red color into black again, even if typed password is not qualified as password yet. If user press `Set password` again and password is not qualified, then change back to red color message.

If this is the expected behaviour

## Proposal
Just to rephrase the expected behaviour
1. `Set Password` button should not be disabled
2. When `Set Password` is clicked, the password should be validated and if invalid the message color should change to red and the form should not submit. 
3. When user starts typing again, the red color of the message should change to black (if its red) even with an invalid password

### For Point-1 (`Set Password` button should not be disabled)
We have to remove `isDisabled={!this.state.isFormValid}` from `SetPasswordPage` component
https://github.com/Expensify/App/blob/1dd71747ba2b0c8553d84d51d863d8ae4e12ef64/src/pages/SetPasswordPage.js#L111-L121

Now the button will be enabled always, but clicking on it at this point will cause submission error. This is taken care of in point 2

### For Point-2 (When `Set Password` is clicked, the password should be validated and if invalid the message color should change to red and the form should not submit. )
We have to move password validation from `NewPasswordForm` to `SetPasswordPage` (the `NewPasswordForm` is only used in `SetPasswordPage`)

**Why move the logic?** 
Because this way when we add proposed changes it will not involve extra state management in `NewPasswordForm` and  will also remove a lot of unnecessary complexity

First we will move `isValidPassword` method from `NewPasswordForm` to `SetPasswordPage`
https://github.com/Expensify/App/blob/1dd71747ba2b0c8553d84d51d863d8ae4e12ef64/src/pages/settings/NewPasswordForm.js#L53-L55 

Now we will remove `passwordHintError` from internal state of  `NewPasswordForm` and move it to component props.
The props look currently like this
https://github.com/Expensify/App/blob/1dd71747ba2b0c8553d84d51d863d8ae4e12ef64/src/pages/settings/NewPasswordForm.js#L13-L26
and we will add a new boolean prop `passwordHintError`
```js
/** Boolean to indicated the validity of password */
passwordHintError: PropTypes.bool.isRequired,
```
and remove `passwordHintError` that is inside `NewPasswordForm` and also its internal state references from `NewPasswordForm`. This would involve removing these methods
- `onBlurNewPassword` (we wont need it with the expected changes)
- `isInvalidPassword` (we wont need it with the expected changes)
- `isValidPassword` (we already moved it to `SetPasswordPage` in point 1)
https://github.com/Expensify/App/blob/1dd71747ba2b0c8553d84d51d863d8ae4e12ef64/src/pages/settings/NewPasswordForm.js#L44-L63
and these references
https://github.com/Expensify/App/blob/1dd71747ba2b0c8553d84d51d863d8ae4e12ef64/src/pages/settings/NewPasswordForm.js#L32-L34 https://github.com/Expensify/App/blob/1dd71747ba2b0c8553d84d51d863d8ae4e12ef64/src/pages/settings/NewPasswordForm.js#L80
and on line 87 we will replace `this.isInvalidPassword()` with `this.props.passwordHintError`
https://github.com/Expensify/App/blob/1dd71747ba2b0c8553d84d51d863d8ae4e12ef64/src/pages/settings/NewPasswordForm.js#L87

`isValidForm` is not used anywhere so optionally we can remove this too
https://github.com/Expensify/App/blob/1dd71747ba2b0c8553d84d51d863d8ae4e12ef64/src/pages/settings/NewPasswordForm.js#L65-L67

Now we will move to `SetPasswordPage` and handle the changes we did in `NewPasswordForm`.
We will add this method in `SetPasswordPage` that we just removed in `NewPasswordForm`
```js
isValidPassword() {
    return this.state.password.match(CONST.PASSWORD_COMPLEXITY_REGEX_STRING);
}
```
I will be renaming `isFormValid` to `isPasswordInvalid` (for better semantics)
https://github.com/Expensify/App/blob/1dd71747ba2b0c8553d84d51d863d8ae4e12ef64/src/pages/SetPasswordPage.js#L76

We will now add a check to the submit handler that will basically validate password and return if invalid password
```js
if (!this.isValidPassword()) {
    this.setState({isPasswordInvalid: true})
    return;
}
```
 Now we will pass the `isPasswordInvalid` state as a prop to `NewPasswordForm`
```js
passwordHintError={this.state.isPasswordInvalid}
```
between line 105-108
https://github.com/Expensify/App/blob/1dd71747ba2b0c8553d84d51d863d8ae4e12ef64/src/pages/SetPasswordPage.js#L104-L109
and just for this step remove `updateIsFormValid={isValid => this.setState({isFormValid: isValid})}`

### For Point-3 (When user starts typing again, the red color of the message should change to black (if its red) even with an invalid password)

We will rename `updateIsFormValid` to `onPasswordInputFocus`
https://github.com/Expensify/App/blob/1dd71747ba2b0c8553d84d51d863d8ae4e12ef64/src/pages/settings/NewPasswordForm.js#L21
remove `componentDidUpdate` (its not needed with expected changes)
https://github.com/Expensify/App/blob/1dd71747ba2b0c8553d84d51d863d8ae4e12ef64/src/pages/settings/NewPasswordForm.js#L37-L42
and add `onFocus` to `NewPasswordForm` (previously we removed `onBlur`)
```js
onFocus={this.props.onPasswordInputFocus}
```
somewhere between line 73 to 81
https://github.com/Expensify/App/blob/1dd71747ba2b0c8553d84d51d863d8ae4e12ef64/src/pages/settings/NewPasswordForm.js#L72-L82
and back in `SetPasswordPage` we pass this prop 
```js
onPasswordInputFocus={() => this.state.isPasswordInvalid && this.setState({isPasswordInvalid: false})}
```
between line 105 and 108
https://github.com/Expensify/App/blob/1dd71747ba2b0c8553d84d51d863d8ae4e12ef64/src/pages/SetPasswordPage.js#L104-L109

Now the expected changes would work.

### Demo with proposed solution

https://user-images.githubusercontent.com/68777211/199869249-a2f5ba9c-b890-40a7-bfae-cf51561f1b90.mp4

---

@tsa321 @mananjadhav @thesahindia Sry for making this too big. Please let me know your thoughts

**Comment by jayeshmangwani** [comment] 2022-11-04 06:33
# Proposal 

we can add a check on onChangeText that if the error is true when typing then clear the error message, below are the changes we have to do,


```diff
+  updatePassword(password) {
+    this.props.updatePassword(password);
+
+    if (!_.isEmpty(password) && this.state.passwordHintError) {
+      this.setState({passwordHintError: ''});
+    }
+  }
  ```
  
  https://github.com/Expensify/App/blob/533e63ce8b13e573024784836cef0bb7e859e937/src/pages/settings/NewPasswordForm.js#L72-L82
```diff
-          onChangeText={password => this.props.updatePassword(password)}
+          onChangeText={this.updatePassword}
```

# fix video

https://user-images.githubusercontent.com/35371050/199906960-384df9c1-8f65-40c5-8bcf-7f4fc2e0b16b.mov

**Comment by tienifr** [comment] 2022-11-04 10:43
@mananjadhav I created the proposal before: https://github.com/Expensify/App/issues/11403#issuecomment-1271179269, but there're some code changes that makes my proposal is not correct. I've created the PR: https://github.com/tienifr/App/pull/21 to change the logic show error in new password page as https://github.com/Expensify/App/issues/11403#issuecomment-1279963289. Pls help to check again. Thanks

https://user-images.githubusercontent.com/113963320/199953954-d5b0feab-d016-459a-a397-af14510ef032.mov

**Comment by mananjadhav** [comment] 2022-11-04 11:31
Thanks for the proposal. I'll need a few hours before I am in front of the computer to review these. Please bear with me till that time.

**Comment by puneetlath** [comment] 2022-11-04 17:58
I think we can likely close this due to #passwordless (cc @johnmlee101)

**Comment by johnmlee101** [comment] 2022-11-04 19:29
Yeah I think it makes sense with our current implementation that this wouldn't be a problem with #passwordless

**Comment by mananjadhav** [comment] 2022-11-05 19:35
@mallenexpensify @tgolen @johnmlee101 @puneetlath Should we hold/close this then?

**Comment by mananjadhav** [comment] 2022-11-08 04:58
> @mallenexpensify @tgolen @johnmlee101 @puneetlath Should we hold/close this then?

Quick bump!

**Comment by tgolen** [comment] 2022-11-08 14:29
Yeah, I think we should go ahead and close this. Reopen if anyone disagrees!

**Closed by tgolen** 2022-11-08 14:29 UTC
Labels: External, Engineering, Daily, Improvement, Help Wanted, Bug

**Comment by mallenexpensify** [comment] 2022-11-09 00:09
Compensated @mananjadhav for C+
