### ISSUE TITLE
iOS - Chat - Edit option does not appear when tap on links sent

### ISSUE THREAD

**Issue by kavimuru** [Expensify/App#9537] opened 2022-06-22 18:09 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___
Issue was found when executing #9471
## Action Performed:
1. Launch App
2. Go to any chat > sent Send following links::
google.com
[www.google.com](http://www.google.com/)
http://google.com/
https://google.com/
3. Edit above links

## Expected Result:
Edit should be appeared when tap on link message.

## Actual Result:
Edit isn't appeared when tap on link message.
Issue not occurred with text message and on mweb.

## Workaround:
Unknown

## Platform:

Where is this issue occurring?

- iOS

**Version Number:** v1.1.78-7

**Reproducible in staging?:** y

**Reproducible in production?:** y

**Email or phone of affected tester (no customers):** 

**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Notes/Photos/Videos:** 

https://user-images.githubusercontent.com/43996225/175107050-cb0e0f87-3b3c-49df-9d50-507e5ff5c65a.mp4

<img src="https://user-images.githubusercontent.com/43996225/175107245-c60f86b1-49ba-4ec5-b949-442807215a18.jpeg" width="40%" height="40%">

**Expensify/Expensify Issue URL:** 

**Issue reported by:** 
Applause internal team

**Slack conversation:** 

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by pecanoro** [comment] 2022-06-22 20:37
I can't reproduce the issue, I can edit it just fine.

**Comment by NikkiWines** [comment] 2022-06-22 21:56
I am unable to reproduce this on my iPhone (app version 1.1.78-7)

https://user-images.githubusercontent.com/16747822/175148706-a2e05872-d226-448b-bcc8-36b7111e84c6.MP4

**Comment by pecanoro** [comment] 2022-06-22 21:57
Let's close it since we can't reproduce it!

**Closed by pecanoro** 2022-06-22 21:57 UTC
Labels: Engineering, Daily
