### ISSUE TITLE
[$1000] Web - The timer to request new magic code resets every time we resize window

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#21616] opened 2023-06-26 19:11 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Sign out of the app
2. Enter any email address
3. On the next page, let the timer decrease
4. Re-size the page to cause a re-render

## Expected Result:
The timer to send a new code should remain the same

## Actual Result:
The timer resets to 30 seconds.

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [x] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 1.3.31-1
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/93399543/87f13321-00a9-4fef-8ca3-6506998b4109

https://github.com/Expensify/App/assets/93399543/4268a550-0a66-4418-9b0c-eac90d628ea3

**Expensify/Expensify Issue URL:**
**Issue reported by:** @esh-g
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1687453791389759

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~0142d30e6627815029</li>
        <li>Upwork Job ID: 1673706501459939328</li>
        <li>Last Price Increase: 2023-09-22</li>
    </ul>
</details>

**Comment by Nikhil-Vats** [comment] 2023-06-26 19:38
might be related to https://github.com/Expensify/App/issues/20404.
cc @mountiny

**Comment by bustermoon147** [comment] 2023-06-27 16:38
Contributor details
Your Expensify account email: bustermoon147@gmail.com
Upwork Profile Link: https://www.upwork.com/freelancers/~0182332d34e38a54c0

**Comment by s77rt** [comment] 2023-06-27 21:44
@hungvu193 Thanks for the proposal. I don't think your RCA is correct, even if the time is stored in a local state, I don't see why the timer is reset on resize. It seems like the component is unmounted and mounted again.

**Comment by Nikhil-Vats** [comment] 2023-06-28 05:54
@s77rt I think this would be solved in #20404.

**Comment by s77rt** [comment] 2023-06-28 20:09
@hungvu193 The timer is implemented to protect the user from themselves, i.e. preventing them from accidentally requesting the code too often and getting blocked. If the user insist to request the code I think that's fine.

**Comment by s77rt** [comment] 2023-06-28 20:12
@Nikhil-Vats I think the root cause is the same but I don't think the solution would be generic and based on https://github.com/Expensify/App/pull/16581#discussion_r1243593268 we may not have a clear solution yet

**Comment by s77rt** [comment] 2023-06-28 20:16
@Nodebrute The timer is client side only, you can always clear it even if we use Onyx.

**Comment by s77rt** [comment] 2023-06-28 20:17
@NikkiWines do you think we should fix this issue?

**Comment by NikkiWines** [comment] 2023-06-28 22:09
Hah, that is a bit odd for sure 😅  It looks like it only occurs when we move between the small screen to full screen views. 

I think we should probably fix this. IMO, it's a bit more understandable that the timer would restart after refreshing but having it restart if the window size changes feels pretty buggy. Fixing this would also align the behavior with that we have on www.expensify.com. 

I don't feel too strongly though, since this is just a small visual block and not supposed to be a fool-proof barrier to requesting a new code - we also have a throttle system in place if too many codes are requested in quick succession anyway. 

@shawnborton @johnmlee101 do you guys have thoughts on whether or not we should fix this?

**Comment by s77rt** [comment] 2023-06-28 23:17
I don't think we should fix this due to the nature of the root cause, it's unrelated to timer component. There is a [bug](https://github.com/Expensify/App/pull/16581#discussion_r1243168373) currently that effects the whole App, whenever the window is resized everything is unmounted and mounted again causing everything to appear that is just mounted thus the timer appears to be reset.

**Comment by NikkiWines** [comment] 2023-06-28 23:36
Discussion in slack about this [here](https://expensify.slack.com/archives/C01GTK53T8Q/p1687994616930989) (thanks for the ping there @s77rt 🙇)

**Comment by shawnborton** [comment] 2023-06-29 16:33
> but having it restart if the window size changes feels pretty buggy.

I agree, we should fix that!

**Comment by johnmlee101** [comment] 2023-06-29 17:19
also related to https://github.com/Expensify/App/issues/17246#issuecomment-1612043606

**Comment by lschurr** [comment] 2023-07-03 15:35
Where did we land on this one @s77rt?

**Comment by s77rt** [comment] 2023-07-03 15:52
@lschurr I think we should put this on hold for https://github.com/Expensify/App/issues/20404

**Comment by lazar-stamenkovic** [comment] 2023-07-04 18:48
@s77rt @lschurr @shawnborton @NikkiWines 
As I applied on various tickets, I gained a deep understanding of the project. As a web developer, I wholeheartedly agree with your perspective.

This issue has an impact on the entire project and requires updating the codebase to resolve it perfectly. One possible solution is to implement a new feature that saves all temporary data generated by user operations on certain pages before refreshing the page.

Although this may not be considered a bug, resizing from a desktop screen to a mobile screen does trigger a page reload. As a result, all temporary data gets reset, including input values in forms. To address this, we can introduce a new feature that utilizes local storage to save and restore temporary data.

Instead of addressing the page refresh issue on resize through codebase updates, opting for this alternative solution might be better.

For example, we can create a utility function that handles the saving and retrieval of temporary data on local storage. This function can be implemented across all affected pages to ensure that current timer values, user input, and other relevant data are preserved even after a page reload.

If you would like me to work on implementing this new feature, I am more than happy to do so.

**Comment by mountiny** [comment] 2023-07-04 19:21
Adding this on hold for #20404 where we will update how the navigation handles resize so no remount happens preventing bugs like this in its core

Sorry anyone who has spent time on proposals for this issue. The root cause is that the current navigation implementation is changing between two navigators when user resizes between the narrow and wide view causing remounting and that leads to various problems on resize.

We are addressing this holistically by only using one navigator and creating the layout with styles and expert agency SWM is working on this now. This is to avoid multiple workarounds and solutions which are only partial. Thanks for understanding and apologies for any inconveniences.

**Comment by lschurr** [comment] 2023-07-05 20:21
This is on hold.

**Comment by lschurr** [comment] 2023-07-14 20:28
Still on hold.

**Comment by mountiny** [comment] 2023-07-18 21:50
Still on hold

**Comment by lschurr** [comment] 2023-07-24 15:17
On hold.

**Comment by lschurr** [comment] 2023-08-02 20:31
Still on hold.

**Comment by s77rt** [comment] 2023-08-13 01:51
Still hold on https://github.com/Expensify/App/issues/20404

**Comment by lschurr** [comment] 2023-08-30 14:07
On hold.

**Comment by mountiny** [comment] 2023-08-31 12:02
This should be fixed in staging, can anyone confirm please?

**Comment by mountiny** [comment] 2023-08-31 12:02
@esh-g maybe

**Comment by esh-g** [comment] 2023-08-31 12:27
@mountiny Still seems to be occuring...

https://github.com/Expensify/App/assets/77237602/5c097ddf-4d1f-42cb-9190-a400813c452b

**Comment by mountiny** [comment] 2023-08-31 21:20
Thanks, must be some other root cause then, removing hold

**Comment by lschurr** [comment] 2023-09-08 16:11
Looks like this is no longer no hold.. Are there any valid proposals here @s77rt?

**Comment by s77rt** [comment] 2023-09-08 17:04
@lschurr We don't have any proposal that needs to be reviewed. Still looking for proposals...

**Comment by akamefi202** [comment] 2023-09-14 18:35
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
The timer to request new magic code resets every time we resize window.

### What is the root cause of that problem?
Exactly, the timer resets when we resize window between pc size and mobile size.
Currently, the app re-renders when the user resizes window between pc & mobile size.
And re-render calls hook functions again and the timer resets.

https://github.com/Expensify/App/blob/62b8e71105959aaa4392da20b251ca1fafd5ab3d/src/pages/signin/ValidateCodeForm/BaseValidateCodeForm.js#L79

### What changes do you think we should make in order to solve the problem?
We should save the value of `timeRemaining` in Session.
We can add a new key to OnyxData for this.
`ONYXKEYS.TIME_REMAINING`
And we should set value as 30 when we moves to Validate page or we resend the code.
`Onyx.set(ONYXKEYS.TIME_REMAINING, 30);`

Then we should start the timer using this onyx value.
As a result, the timer won't reset regardless of resize.

### What alternative solutions did you explore? (Optional)
N/A

**Comment by lschurr** [comment] 2023-09-14 19:34
Could you review the latest proposal @s77rt?

**Comment by s77rt** [comment] 2023-09-14 20:39
@akamefi202 Thanks for the proposal.

> Currently, the app re-renders when the user resizes window between pc & mobile size.

Can you link to the offending code? I thought we fixed this already here https://github.com/Expensify/App/pull/22437/files#diff-c3d3bf8bc4056d8f2e8ff15f6d72d7e81656cd36c30a202a084c50dda1dff582L120

**Comment by akamefi202** [comment] 2023-09-14 20:50
But I was still able to reproduce this issue and confirm re-rendering. Maybe style-based approach is not applied for `SignInPage`.

**Comment by s77rt** [comment] 2023-09-14 21:01
@akamefi202 Can you please check what exactly is causing the re-rendering?

**Comment by akamefi202** [comment] 2023-09-15 11:23
@s77rt 
https://github.com/Expensify/App/blob/144e932c2ea863bffafbd26e9cc7602e89b1e352/src/pages/signin/SignInPageLayout/index.js#L96-L97

The reason of re-rendering is `shouldShowSmallScreen` variable here.
`shouldShowSmallScreen` reflects current size of browser, whether it is pc size or mobile size.
Currently, `SignInPageLayout` component renders different content by `shouldShowSmallScreen` variable.

https://github.com/Expensify/App/blob/144e932c2ea863bffafbd26e9cc7602e89b1e352/src/pages/signin/SignInPage.js#L160-L167

And each content contains forms such as login form & validate code form.
As a result, the app re-renders the form whenever the user changes the size of browser between pc size & mobile size.

**Comment by s77rt** [comment] 2023-09-15 17:30
@akamefi202 Thanks for the update. Indeed `shouldShowSmallScreen` seems to be the root cause here, or to be exact the position of `<SignInPageContent />` being different is the root cause.
- First condition: View -> ScrollView -> SignInPageContent (1st child)
- Second condition: ScrollView -> View -> SignInPageContent (2nd child)


React preserves a component’s state for as long as it’s being rendered at its position in the UI tree. If it gets removed, or a different component gets rendered at the same position, React discards its state [^1].

The correct solution is to adjust the `SignInPageLayout` that we end up with `SignInPageContent` having the same position across the two if conditions.

[^1]: https://react.dev/learn/preserving-and-resetting-state

**Comment by akamefi202** [comment] 2023-09-16 03:57
@s77rt https://github.com/Expensify/App/issues/21616#issuecomment-1719951373
I updated the proposal and added new solution as alternative. Please review this.

**Comment by s77rt** [comment] 2023-09-16 22:01
@akamefi202 Thanks for the update. Your alternative solution would work but I don't think we can just _randomly_ add Views as this will cause a regression. Perhaps maintaining the component position is not the easiest solution, there may be other options to force react to not ignore the component state.


https://github.com/Expensify/App/assets/16493223/0a6e0190-f3c6-475d-a563-2562dc80bbf8

**Comment by akamefi202** [comment] 2023-09-17 07:08
@s77rt Thank you for your review. I agree with you. Adding unnecessary tags is not a perfect solution.
https://github.com/Expensify/App/issues/21616#issuecomment-1719951373
Then what do you think about my first solution? Is there any problem with it?

**Comment by s77rt** [comment] 2023-09-17 16:12
@akamefi202 I don't think using Onyx is a good solution, it's practically a workaround (we are not fixing the root cause).

**Comment by akamefi202** [comment] 2023-09-20 16:13
@s77rt In alternative solution, I was able to fix regression by adding styles to `<View>` tags.
Please review alternative solution again. Thanks.
https://github.com/Expensify/App/issues/21616#issuecomment-1719951373

**Comment by s77rt** [comment] 2023-09-20 22:56
@akamefi202 I have asked in Slack https://expensify.slack.com/archives/C01GTK53T8Q/p1695250534308479 if we should fix this issue as I'm not totally sure if it's worth it given the required change.

**Comment by akamefi202** [comment] 2023-09-22 10:32
@s77rt Could you please make a decision soon? I think we might ask @lschurr 's opinion.

**Comment by s77rt** [comment] 2023-09-22 13:19
Waiting for :eyes: on Slack thread

**Comment by lschurr** [comment] 2023-09-25 03:36
I bumped the Slack link and got another comment suggesting we close..

https://expensify.slack.com/archives/C01GTK53T8Q/p1695608512991419?thread_ts=1695250534.308479&cid=C01GTK53T8Q

Shall we close @s77rt?

**Comment by s77rt** [comment] 2023-09-25 03:48
@lschurr Yes, I think closing makes sense for this case.

**Comment by lschurr** [comment] 2023-09-25 03:51
Great, closing.

**Closed by lschurr** 2023-09-25 03:51 UTC
Labels: External, Daily, Help Wanted, Bug
