### ISSUE TITLE
[HOLD for payment 2024-07-10] [$250] Track expense - "Delete expense" option appears for paid tracked expense

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#43591] opened 2024-06-12 16:51 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.82-0
**Reproducible in staging?:** Y
**Reproducible in production?:** Y 
**If this was caught during regression testing, add the test name, ID and link from TestRail:** N/A
**Issue reported by:** Applause - Internal Team

## Action Performed:
1. Go to staging.new.expensify.com
2. Go to workspace chat
3. Submit an expense
4. Track an expense
5. Pay elsewhere the expense report
6. Go to transaction thread of tracked expense
7. Click 3-dot menu

## Expected Result:
"Delete expense" option will not appear for paid tracked expense

## Actual Result:
"Delete expense" option appears for paid tracked expense

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [x] Android: mWeb Chrome
- [x] iOS: Native
- [x] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details> 

https://github.com/Expensify/App/assets/78819774/8b2f5e72-80ba-45dc-a5b4-20aed1d77172

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01bb7f209695580cf5</li>
        <li>Upwork Job ID: 1802802568068548628</li>
        <li>Last Price Increase: 2024-06-17</li>
<li>Automatic offers: </li>
<ul>
<li>eh2077 | Reviewer | 102806652</li>
<li>bernhardoj | Contributor | 102806654</li>
</ul></li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @kevinksullivan</details>

**Comment by lanitochka17** [comment] 2024-06-12 16:51
@kevinksullivan  FYI I haven't added the External label as I wasn't 100% sure about this issue. Please take a look and add the label if you agree it's a bug and can be handled by external contributors

**Comment by bernhardoj** [comment] 2024-06-13 08:46
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
Delete expense option is shown for paid track expense.

### What is the root cause of that problem?
The delete option is always shown for track expense report.
https://github.com/Expensify/App/blob/a451de460c45611f64bcd06961afb78b4e2f3c9b/src/components/MoneyRequestHeader.tsx#L103

This is useful for self DM track expense report because the `moneyRequestReport` is the parent report which is self DM, 
https://github.com/Expensify/App/blob/a451de460c45611f64bcd06961afb78b4e2f3c9b/src/components/MoneyRequestHeader.tsx#L63

so `canAddOrDeleteTransactions` returns false for selfDM track expense. In a normal money request or workspace track expense, we have IOU/expense report and then the transaction thread.

chat report -> money request report -> transaction thread

But in self DM track expense, we only have the track expense report/transaction thread

self DM -> track expense report

### What changes do you think we should make in order to solve the problem?

We need to also check whether the track expense is a self DM track or not.
```
const isSelfDMTrack = ReportUtils.isTrackExpenseReport(report) && ReportUtils.isSelfDM(parentReport);
const moneyRequestReport = !isSelfDMTrack ? parentReport : undefined; <- optional, just so it's more predictable
const canDeleteRequest = ... && (ReportUtils.canAddOrDeleteTransactions(moneyRequestReport) || isSelfDMTrack) && ...
```

We also have the same condition in MoneyReportHeader that is shown in the money request report, but self DM track doesn't have money request report, so we can remove it (remove ReportUtils.isTrackExpenseReport(report))
https://github.com/Expensify/App/blob/a451de460c45611f64bcd06961afb78b4e2f3c9b/src/components/MoneyReportHeader.tsx#L81-L82

### What alternative solutions did you explore? (Optional)
In `canAddOrDeleteTransactions`, returns true if it's a self DM.
https://github.com/Expensify/App/blob/a451de460c45611f64bcd06961afb78b4e2f3c9b/src/libs/ReportUtils.ts#L1506-L1509
```
if (isSelfDM(moneyRequestReport)) return true
```

But I don't like this one because `canAddOrDeleteTransactions` is expected to work with a money request report.

Instead, we can add a new optional param to `canAddOrDeleteTransactions` called `transactionReport` and if `transactionReport` is a self DM track, then returns true.

**Comment by kevinksullivan** [comment] 2024-06-17 20:37
Moving to vip-vsb and making external. @eh2077 can you review the proposals above when you get a chance? Thanks!

**Comment by NikkiWines** [comment] 2024-06-20 07:50
Agreed @bernhardoj's proposal looks good 👍

**Comment by bernhardoj** [comment] 2024-06-20 09:46
PR is ready

cc: @eh2077

**Comment by eh2077** [comment] 2024-07-14 12:30
### Checklist

- [x] [@eh2077] The PR that introduced the bug has been identified. Link to the PR: _**I can't find the specific PR that is responsible for this bug. We missed this case when adding the track expense feature to workspace.**_
- [x] [@eh2077] The offending PR has been commented on, pointing out the bug it caused and why, so the author and reviewers can learn from the mistake. Link to comment: N/A
- [x] [@eh2077] A discussion in #expensify-bugs has been started about whether any other steps should be taken (e.g. updating the PR review checklist) in order to catch this type of bug sooner. Link to discussion: N/A
- [x] [@eh2077] Determine if we should create a regression test for this bug. Yes

#### Regression test

1. Open workspace chat
2. Submit 1 expense and track 1 expense
3. Open the expense report
4. Pay the expense
5. Open the track transaction thread
6. Press the 3-dot button
7. Verify there is no Delete expense option
8. Open a self DM
9. Track an expense
10. Open the track report
11. Press the 3-dot button
12. Verify there is a Delete expense option

Do we agree 👍 or 👎

**Comment by bernhardoj** [comment] 2024-07-14 14:40
I requested the payment in ND.

**Comment by kevinksullivan** [comment] 2024-07-15 23:12
Payment summary:
- @bernhardoj $250 (ND)
- @eh2077 $250

**Comment by kevinksullivan** [comment] 2024-07-15 23:13
All set paying @eh2077

**Closed by kevinksullivan** 2024-07-15 23:13 UTC
Labels: External, Daily, Awaiting Payment, Bug

**Comment by JmillsExpensify** [comment] 2024-07-16 04:49
$250 approved for @bernhardoj
