### ISSUE TITLE
[$500] Android - Opening deep link of request amount page, the amount is not shown

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#31329] opened 2023-11-15 00:52 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.3.99.0
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** Applause - Internal Team
**Slack conversation:**

**Issue found when executing PR** https://github.com/Expensify/App/pull/30704

## Action Performed:
Pre-condition: Open same account in mweb and android
1. Go to https://staging.new.expensify.com/
2. Tap fab--Request money
3. Enter an amount
4. Tap next
5. Select any user
6. Tap amount
7. Copy the link
8. Launch app and login as same user
9. Open any report
10. Paste the link and send the message
11. Tap on the link

## Expected Result:
The request money page must open and the selected amount must be shown.

## Actual Result:
The request money page is opened but the selected amount is not displayed.

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [ ] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

https://github.com/Expensify/App/assets/93399543/262058aa-6ab4-4e12-8a9d-7541aff1169e

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~019076fc738102f2ff</li>
        <li>Upwork Job ID: 1724591213359931392</li>
        <li>Last Price Increase: 2023-11-15</li>
    </ul>
</details>

**Comment by eh2077** [comment] 2023-11-15 01:19
This is not a bug as the intermediate IOU data is only saved in Browser.

**Comment by narefyev91** [comment] 2023-11-15 07:36
Agree with comment from @eh2077. @puneetlath i think we can close this one

**Comment by monochkov** [comment] 2023-11-15 10:03
You need to modify website URL dynamically and then pass amount along with URL to mobile.
What I mean:
1. Dynamically change URL to the next one: https://staging.new.expensify.com/request/new/amount?value=<value>. You can do that using JS. (https://stackoverflow.com/questions/11932869/how-to-dynamically-change-url-without-reloading)
2. Handle `value` in mobile using deep links: https://developer.android.com/training/app-links/deep-linking#handling-intents

**Comment by puneetlath** [comment] 2023-11-15 16:29
Agreed that this isn't a bug. Closing.

**Closed by puneetlath** 2023-11-15 16:29 UTC
Labels: External, Daily, Help Wanted, Bug
