### ISSUE TITLE
[Subscriptions] - Unable to disable auto renew as `Submit` button on RHP is unresponsive when clicked

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#43466] opened 2024-06-11 12:22 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.81-1
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**If this was caught during regression testing, add the test name, ID and link from TestRail:** N/A
**Issue reported by:** Applause - Internal Team
 
**Issue found when executing PR** https://github.com/Expensify/App/pull/42990
## Action Performed:
1. Log in with a new Gmail account
2. Create a workspace
3. Navigate to https://staging.new.expensify.com/settings/subscription
4. Click on the Auto-renew toggle
5. Select any reason
6. Click on the "Submit" button

## Expected Result:
When selecting a reason why to downgrade, they user should be able to successfully click "submit" and  should be able to disable auto renew.

## Actual Result:
Unable to disable auto renew. Nothing happens when I click on the "Submit" button

## Workaround:
Unknwon

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details> 

https://github.com/Expensify/App/assets/78819774/950a8200-a82f-479e-91cb-d3c2089b9472

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01222f7d2b76bc2922</li>
        <li>Upwork Job ID: 1800504690889509063</li>
        <li>Last Price Increase: 2024-06-11</li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @abdulrahuman5196</details>

**Comment by zanyrenney** [comment] 2024-06-11 12:25
agree this is a bug. let's resolve!

**Comment by zanyrenney** [comment] 2024-06-11 12:28
commented in the PR- but i think @MrMuzyk and @mollfpr will be responsible for fixing this one, so just hold on that for now @abdulrahuman5196

**Comment by MrMuzyk** [comment] 2024-06-11 12:43
I've left a comment explaining why it's not behaving correctly yet - https://github.com/Expensify/App/pull/42990#issuecomment-2160667142

This is expected at this stage of the feature. Submit action will be implemented later on.

**Comment by amyevans** [comment] 2024-06-11 13:24
Closing since this is expected behavior at this stage of the implementation

**Closed by amyevans** 2024-06-11 13:24 UTC
Labels: External, Daily, Help Wanted, Bug
