### ISSUE TITLE
[HOLD for Payment 2024-09-02] [$250] Send invoice - Individual workspace is in 'Send from' field

### ISSUE THREAD

**Issue by izarutskaya** [Expensify/App#46705] opened 2024-08-02 10:32 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** v9.0.16-0
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**If this was caught during regression testing, add the test name, ID and link from TestRail:** https://expensify.testrail.io/index.php?/cases/view/3073286
**Email or phone of affected tester (no customers):** applausetester+bp716@applause.expensifail.com
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Issue reported by:** Applause-Internal team

## Action Performed:
Precondition: account has Individual workspace as default and at least one existing group workspace.
1. FAB > Send invoice
2. Enter amount > Next
3. Choose a user

## Expected Result:
The 'Send from' default workspace is one of listed sender's existing default workspaces.

## Actual Result:
The 'Send from' default workspace is Individual workspace. When click on field, the list of sender's existing workspaces is displayed. But if you change the default workspace (one of group WS in OldDot), the individual WS is not displayed in the list.

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

https://github.com/user-attachments/assets/f316cc08-af8b-4698-b935-64019d404173

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~0107661f51eb3a2eee</li>
        <li>Upwork Job ID: 1821429613810291281</li>
        <li>Last Price Increase: 2024-08-08</li>
<li>Automatic offers: </li>
<ul>
<li>rojiphil | Reviewer | 103496757</li>
<li>nkdengineer | Contributor | 103496758</li>
</ul></li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @rojiphil</details>

**Comment by izarutskaya** [comment] 2024-08-02 10:43
We think this issue might be related to the #vip-bills.

**Comment by nkdengineer** [comment] 2024-08-02 16:24
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
The 'Send from' default workspace is Individual workspace. When click on field, the list of sender's existing workspaces is displayed. But if you change the default workspace (one of group WS in OldDot), the individual WS is not displayed in the list.

### What is the root cause of that problem?
We always set the default WS in the send invoice flow is the default WS if it exists without checking it is a personal WS or not

https://github.com/Expensify/App/blob/fefda46147f1b3389268dadb722fe5d37ec95c16/src/libs/actions/Policy/Policy.ts#L205-L209
### What changes do you think we should make in order to solve the problem?
Instead of getting `primaryPolicy` from `allPolicies`, we can get this policy from the `activeAdminWorkspaces` which already filtered the hidden policy 

```
function getPrimaryPolicy(activePolicyID?: OnyxEntry<string>): Policy | undefined {
    const activeAdminWorkspaces = PolicyUtils.getActiveAdminWorkspaces(allPolicies);
    const primaryPolicy: Policy | null | undefined = activeAdminWorkspaces.find((policy) => policy.id === activePolicyID);
    return primaryPolicy ?? activeAdminWorkspaces[0];
}
```
https://github.com/Expensify/App/blob/fefda46147f1b3389268dadb722fe5d37ec95c16/src/libs/actions/Policy/Policy.ts#L205-L209
### What alternative solutions did you explore? (Optional)

**Comment by adelekennedy** [comment] 2024-08-06 00:18
I can't seem to recreate this on v9.0.16-5 - @izarutskaya can you still reproduce this?

**Comment by rojiphil** [comment] 2024-08-11 18:26
@nkdengineer Is there any distinct advantage to your proposed solution compared to @nyomanjyotisa proposal [here](https://github.com/Expensify/App/issues/46705#issuecomment-2265138021)? 
It seems like you are the doing the same thing but in a different way.

**Comment by nkdengineer** [comment] 2024-08-12 04:53
@rojiphil `getActiveAdminWorkspaces` function also filters out the WS that is pending deletion. If the default WS is pending deletion we should not show it as default in the send invoice. The proposal from @nyomanjyotisa doesn't cover this case (see the video below). For this case, we should use `getActiveAdminWorkspaces` as I mentioned in my proposal or update `ONYXKEYS.NVP_ACTIVE_POLICY_ID` when we delete the default WS.


https://github.com/user-attachments/assets/be7d663d-a34e-4b9f-bb92-82e22326d441

**Comment by rojiphil** [comment] 2024-08-12 06:45
> `getActiveAdminWorkspaces` function also filters out the WS that is pending deletion

Thanks. Using `getActiveAdminWorkspaces` for filtering make sense as it has the additional advantage.
@nkdengineer [proposal](https://github.com/Expensify/App/issues/46705#issuecomment-2265744699) LGTM
🎀👀🎀 C+ reviewed

**Comment by nkdengineer** [comment] 2024-08-13 09:47
@rojiphil  this [PR](https://github.com/Expensify/App/pull/47288) is ready for review

**Comment by rojiphil** [comment] 2024-09-05 18:19
@adelekennedy Looks like the automation did not work here.
This issue is due for payment as the fix has been in production since the last 2 weeks as mentioned [here](https://github.com/Expensify/App/pull/47288#issuecomment-2296920535)

**Comment by adelekennedy** [comment] 2024-09-06 19:24
**Payouts due:**

Sorry about that! Updated title and moving forward with payments

- [ ] Contributor: $250 @nkdengineer 
- [ ] Contributor+: $250 @rojiphil, @rojiphil it looks like the offer is still pending in the [Upwork job ](https://www.upwork.com/jobs/~0107661f51eb3a2eee) am I looking at this wrong, does something need to be corrected or will you accept the offer?

Upwork job is [here](https://www.upwork.com/jobs/~0107661f51eb3a2eee).

**Comment by adelekennedy** [comment] 2024-09-06 19:26
**BugZero Checklist:** The PR fixing this issue has been merged! The following checklist ([instructions](https://stackoverflow.com/c/expensify/questions/14574)) will need to be completed before the issue can be closed:

- [ ] [@rojiphil ] The PR that introduced the bug has been identified. Link to the PR:
- [ ] [@rojiphil ] The offending PR has been commented on, pointing out the bug it caused and why, so the author and reviewers can learn from the mistake. Link to comment:
- [ ] [@rojiphil ] A discussion in #expensify-bugs has been started about whether any other steps should be taken (e.g. updating the PR review checklist) in order to catch this type of bug sooner. Link to discussion:
- [ ] [@rojiphil ] Determine if we should create a regression test for this bug.
- [ ] [@rojiphil  ] If we decide to create a regression test for the bug, please propose the [regression test](https://github.com/Expensify/App/blob/main/contributingGuides/REGRESSION_TEST_BEST_PRACTICES.md) steps to ensure the same bug will not reach production again.
- [ ] [@adelekennedy ] Link the GH issue for creating/updating the regression test once above steps have been agreed upon:

**Comment by rojiphil** [comment] 2024-09-10 17:48
* [x]  [@rojiphil] The PR that introduced the bug has been identified. Link to the PR: [Offending PR](https://github.com/Expensify/App/pull/40015)
* [x]  [@rojiphil] The offending PR has been commented on, pointing out the bug it caused and why, so the author and reviewers can learn from the mistake. Link to comment: [Added comment](https://github.com/Expensify/App/pull/40015/files#r1752411796)
* [x]  [@rojiphil] A discussion in #expensify-bugs has been started about whether any other steps should be taken (e.g. updating the PR review checklist) in order to catch this type of bug sooner. Link to discussion: Not Required. Existing checklist is good enough to capture such issues.
* [x]  [@rojiphil] Determine if we should create a regression test for this bug. : Yes. We can
* [x]  [@rojiphil] If we decide to create a regression test for the bug, please propose the [regression test](https://github.com/Expensify/App/blob/main/contributingGuides/REGRESSION_TEST_BEST_PRACTICES.md) steps to ensure the same bug will not reach production again. 


	1	FAB > Send invoice
	2	Enter amount > Next
	3	Choose a user
	4	Verify that: The 'Send from' default workspace is one of listed sender's existing default workspaces.
	5	Go offline
	6	Delete a workspace
	7	Repeat steps 1, 2, 3
	8	Verify that: the deleted workspace isn't in the list of workspaces

**Comment by rojiphil** [comment] 2024-09-10 17:51
> * $250 @rojiphil, @rojiphil it looks like the offer is still pending in the [Upwork job ](https://www.upwork.com/jobs/~0107661f51eb3a2eee) am I looking at this wrong, does something need to be corrected or will you accept the offer?

@adelekennedy Completed BZ checklist and accepted offer too. Awaiting payment. Thanks

**Comment by adelekennedy** [comment] 2024-09-16 23:43
https://github.com/Expensify/Expensify/issues/428716

**Closed by adelekennedy** 2024-09-16 23:43 UTC
Labels: Reviewing, External, Daily, Awaiting Payment, Bug
