### ISSUE TITLE
[Collect approvers] Desktop - Approver - Pay button in report shows up briefly when launching desktop app from web

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#36954] opened 2024-02-20 21:27 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** v1.4.43-3
**Reproducible in staging?:** y
**Reproducible in production?:** y
**Issue reported by:** Applause - Internal Team

## Action Performed:
Precondition:
- Approver and employee are part of Collect workspace.
- Desktop app is logged out.
1. [Employee] Request money from workspace chat and submit it.
2. [Approver] On web, go to expense report with Employee.
3. [Approver] Launch Desktop app from web.
4. Repeat Step 1 to 3 with Admin as approver.

## Expected Result:
Only approve button will appear when logging in.

## Actual Result:
Pay with Expensify button appears briefly when first logged in.

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [ ] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

https://github.com/Expensify/App/assets/93399543/999de4e9-4f3d-4958-ab09-10ae6e39d1d7

https://github.com/Expensify/App/assets/93399543/58ac08ae-3b17-41bf-a309-6f763f6e5932

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01a1e3e884b5798f29</li>
        <li>Upwork Job ID: 1760347765147852800</li>
        <li>Last Price Increase: 2024-02-21</li>
    </ul>
</details>

**Comment by kbecciv** [comment] 2024-02-20 21:27
@jliexpensify I haven't added the External label as I wasn't 100% sure about this issue. Please take a look and add the label if you agree it's a bug and can be handled by external contributors.

**Comment by kbecciv** [comment] 2024-02-20 21:28
We think that this bug might be related to #wave7-collect-approvers
@RachCHopkins

**Comment by jacobkim9881** [comment] 2024-02-21 10:05
I haven't see the code for the cause but I guess brief showing is from a delay while getting onyx data for checking which should show "Approve" or "Pay with Expensify" button. There should be a reason for showing "Pay with Expensify" button. Like a case "Approve" button isn't a default or other case "Pay with Expensify" button is a default. 

The issue could be uncommon because the user don't open web and desktop app both as UX. Only such condition cause the issue currently.

**Comment by marcochavezf** [comment] 2024-02-21 16:56
Assigning myself here, since it was reported from another PR. Seems the problem is that we're sending different onyx updates for the same report/reportAction and the UI changes everytime some of those onyx updates are applied causing the flickering. I think it would require a broader discussion about how we're applying the onyx values

**Comment by marcochavezf** [comment] 2024-02-23 03:03
No update, worked today on chores

**Comment by jliexpensify** [comment] 2024-02-23 04:44
@marcochavezf spoke to Rach, setting this as `high` as per her request!

**Comment by jliexpensify** [comment] 2024-02-27 03:25
Not overdue

**Comment by marcochavezf** [comment] 2024-02-27 18:30
No update in this once, focused on other critical and high priority wave tasks

**Comment by marcochavezf** [comment] 2024-03-01 19:55
No update yet, working on other higher priority items

**Comment by marcochavezf** [comment] 2024-03-04 17:28
Working on other high priority items but I will try to check it out today

**Comment by marcochavezf** [comment] 2024-03-07 00:45
No update, looking to hand it off [here](https://expensify.slack.com/archives/CC7NECV4L/p1709689123918609?thread_ts=1709668780.226539&cid=CC7NECV4L)

**Comment by marcochavezf** [comment] 2024-03-11 17:54
No update, focused on other high priority items

**Comment by jliexpensify** [comment] 2024-03-14 10:24
@marcochavezf so you want to change the priority if you're not focused on this?

**Comment by marcochavezf** [comment] 2024-03-14 16:37
Yeah I think that would work since it's a polish issue

**Comment by jliexpensify** [comment] 2024-03-20 00:31
Heads up: I am OOO 21st to 31st march but will keep this assigned to myself.

**Comment by marcochavezf** [comment] 2024-04-01 19:54
No update

**Comment by marcochavezf** [comment] 2024-04-11 02:47
Focused on other high priority bugs

**Comment by marcochavezf** [comment] 2024-04-22 18:00
No update, working on a hold request bug and awareness campaign

**Comment by marcochavezf** [comment] 2024-04-30 23:20
Applying retest-weekly since a bunch of changes have been applied

**Comment by mvtglobally** [comment] 2024-05-13 14:20
Issue not reproducible during KI retests. (First week)

**Comment by marcochavezf** [comment] 2024-05-13 22:55
Cool, thanks. I will close it out

**Closed by marcochavezf** 2024-05-13 22:55 UTC
Labels: Engineering, Weekly, Internal, Overdue, Bug, retest-weekly
