### ISSUE TITLE
[$500] Smartscan: Expense report preview in LHN shows 0.00 when PDF receipt is scanned successfully

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#34178] opened 2024-01-09 18:52 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.23-0
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** Applause - Internal Team
**Slack conversation:**

## Action Performed:
1. Go to workspace chat.
2. Create a Scan request with PDF file as receipt.
3. When the scanning is complete, open expense report.

## Expected Result:
Expense report preview in LHN shows the correct amount.

## Actual Result:
Expense report preview in LHN shows 0.00.
This issue is only reproducible when PDF receipt is used.

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [x] Android: mWeb Chrome
- [x] iOS: Native
- [x] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

![image](https://github.com/Expensify/App/assets/93399543/d365bc36-c854-44ac-be73-71c6b5bac29e)

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01e635178117bbd335</li>
        <li>Upwork Job ID: 1744794404061753344</li>
        <li>Last Price Increase: 2024-01-30</li>
    </ul>
</details>

**Comment by Tony-MK** [comment] 2024-01-09 21:28
I think this issue is related to https://github.com/Expensify/App/issues/34064

**Comment by Tony-MK** [comment] 2024-01-09 21:44
@s-alves10 In this https://github.com/Expensify/App/issues/34064#issuecomment-1883428112, Tim Golden instructed.

> The LHN and the preview should be using the same logic

If it is not related, then it should be fixed by https://github.com/Expensify/App/issues/34064.

What do you think? 🤔

**Comment by s-alves10** [comment] 2024-01-09 22:12
## Proposal

### Please re-state the problem that we are trying to solve in this issue.

LHN shows 0.00 for IOU report when receipt is scanned successfully

### What is the root cause of that problem?

Let's take a look at [getReportPreviewMessage](https://github.com/Expensify/App/blob/3acb14a49438b486e9e77ffa1c6f797cccfa2ea2/src/libs/ReportUtils.ts#L2051) function which is used for displaying second line of LHN

For money request, we get the preview message here
https://github.com/Expensify/App/blob/3acb14a49438b486e9e77ffa1c6f797cccfa2ea2/src/libs/ReportUtils.ts#L2140-L2148

We get the preview message from the original message amount and report currency.

This is the root cause

### What changes do you think we should make in order to solve the problem?

We should get the preview message from the transaction details

We are already doing this for split bill actions here
https://github.com/Expensify/App/blob/3acb14a49438b486e9e77ffa1c6f797cccfa2ea2/src/libs/ReportUtils.ts#L2067-L2087

Update the above code segments to
```
    if (isNotEmptyObject(reportAction) && reportAction && ReportActionsUtils.isMoneyRequestAction(reportAction)) {
        // This covers group chats where the last action is a split bill action
        const linkedTransaction = TransactionUtils.getLinkedTransaction(reportAction);
        if (isEmptyObject(linkedTransaction)) {
            return reportActionMessage;
        }

        if (isNotEmptyObject(linkedTransaction)) {
            if (TransactionUtils.isReceiptBeingScanned(linkedTransaction)) {
                return Localize.translateLocal('iou.receiptScanning');
            }

            if (TransactionUtils.hasMissingSmartscanFields(linkedTransaction)) {
                return Localize.translateLocal('iou.receiptMissingDetails');
            }

            const transactionDetails = getTransactionDetails(linkedTransaction);
            const formattedAmount = CurrencyUtils.convertToDisplayString(transactionDetails?.amount ?? 0, transactionDetails?.currency ?? '');
            if (!isIOUReport(report) && ReportActionsUtils.isSplitBillAction(reportAction)) {
                return Localize.translateLocal('iou.didSplitAmount', {formattedAmount, comment: transactionDetails?.comment ?? ''});
            } else {
                const lastActorID = reportAction?.actorAccountID;
                const requestorName = lastActorID && lastActorID !== currentUserAccountID ? getDisplayNameForParticipant(lastActorID, !isPreviewMessageForParentChatReport) : '';
                return `${requestorName ? `${requestorName}: ` : ''}${Localize.translateLocal('iou.requestedAmount', {formattedAmount})}`;
            }
        }
    }
```

This works great

<details>
    <summary>Result</summary>

![image](https://github.com/Expensify/App/assets/126839717/6d7f85e6-bdad-40d2-9d88-9fac6d866be9)

</details>

### What alternative solutions did you explore? (Optional)

**Comment by s-alves10** [comment] 2024-01-09 22:15
@Tony-MK 

https://github.com/Expensify/App/issues/34064 is related to IOU report preview in chat report and LHN for the report
This issue is related to money request in IOU report and LHN for the IOU report
They are different.

**Comment by kmbcook** [comment] 2024-01-12 20:15
## Proposal
### Please re-state the problem that we are trying to solve in this issue.
  Scan - Expense report preview in LHN shows 0.00 when PDF receipt is scanned successfully

### What is the root cause of that problem?
  libs/SidebarUtils.getOptionData sets alternateText incorrectly when last visible report action is an iou report action. 

  This root cause is the same root cause as https://github.com/Expensify/App/issues/33733. The changes proposed here fix both of these issues.

### What changes do you think we should make in order to solve the problem?
  In libs/SidebarUtils.getOptionData check to see if last visible report action is an iou. If so, set alternateText correctly, using the latest amount of the iou transaction. Otherwise, use existing logic to set alternateText.

**Comment by JmillsExpensify** [comment] 2024-01-14 09:13
@fedirjh Thoughts on these proposals?

**Comment by JmillsExpensify** [comment] 2024-01-31 17:25
Still need to re-test

**Comment by JmillsExpensify** [comment] 2024-02-07 16:31
Internal label is applied. I'll also float in Slack.

**Comment by JmillsExpensify** [comment] 2024-02-14 03:27
I went ahead and added to our internal project board!

**Comment by JmillsExpensify** [comment] 2024-02-14 03:28
Still no takers, though this is added to our internal project board.

**Comment by greg-schroeder** [comment] 2024-02-20 06:26
What's happening with this issue? Should it be marked as a `Hot Pick`? It seems it should be internal, but is it ready to be worked on or is there still consensus that needs to be reached? 

@fedirjh @JmillsExpensify

**Comment by greg-schroeder** [comment] 2024-02-21 02:56
Let me know if you can take this one @luacmartins - if not I'll set Hot Pick

**Comment by luacmartins** [comment] 2024-02-21 14:57
@greg-schroeder my plate is quite full atm, can we add the hot pick label?

**Comment by greg-schroeder** [comment] 2024-02-28 03:32
Added `Hot Pick`

**Comment by JmillsExpensify** [comment] 2024-03-06 04:36
@trjExpensify This one has been in hot picks, though never got picked up. Maybe we re-highlight in #wave-collect?

**Comment by trjExpensify** [comment] 2024-03-06 10:23
Will do!

**Comment by Gonals** [comment] 2024-03-07 14:53
I can take a look at this 😁

**Comment by trjExpensify** [comment] 2024-03-07 14:55
Niceee! Removing the `Hot picks` label and putting this in Release 1 as it's a bad bug to be scanning $0.00s

**Comment by Gonals** [comment] 2024-03-07 15:12
Actually, it seems I can't reproduce this. @kbecciv, could you give it another try and confirm you still see this issue?
<img width="822" alt="Screenshot 2024-03-07 at 4 11 56 PM" src="https://github.com/Expensify/App/assets/19366280/9d70cbc6-7daf-44de-afbf-483a9fe1380b">

cc @trjExpensify

**Comment by kbecciv** [comment] 2024-03-07 18:40
Checking

**Comment by Gonals** [comment] 2024-03-08 09:48
> Checking

Any news, @kbecciv?

**Comment by kbecciv** [comment] 2024-03-08 17:32
Issue is no longer reproduced
![Screenshot 2024-03-09 at 00 32 34](https://github.com/Expensify/App/assets/93399543/02e11dea-e97f-46dc-9076-2a50701f668a)
!

**Comment by Gonals** [comment] 2024-03-11 12:33
Closing, then!

**Comment by lanitochka17** [comment] 2024-08-08 13:00
Issue is still reproducible on the latest build 9.0.18-1

https://github.com/user-attachments/assets/90752845-7127-468d-a112-673bf31d3043

**Comment by JmillsExpensify** [comment] 2024-08-14 11:37
Can we create a fresh issue for this?

**Comment by Gonals** [comment] 2024-08-19 13:27
I can't seem to reproduce this (once again). Closing for now 🤷

**Closed by Gonals** 2024-08-19 13:27 UTC
Labels: Engineering, Daily, Internal, Overdue, Bug
