### ISSUE TITLE
[HOLD https://github.com/Expensify/App/issues/27672] [$500] Web - App becomes unresponsive on selecting and pasting same emoji in composer

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#28035] opened 2023-09-22 16:39 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Open the app
2. Open any report
3. From emoji picker, select any emoji eg: :doughnut:
4. Copy the emoji text of emoji used in step 3 eg: copy ':doughnut' and colon after doughnut (easy way to copy the text is react with that emoji on any message, right click on reaction and copy the text from popup)
5. Select the emoji in composer and paste the copied text, observe that now app becomes unresponsive

## Expected Result:
App should not become unresponsive by any action

## Actual Result:
App becomes unresponsive when we paste emoji text on same emoji selected in composer

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [ ] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 1.3.73.0
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/93399543/5d996f17-219a-48ef-a456-86eb30cf59ea

https://github.com/Expensify/App/assets/93399543/7cd56e98-44a6-45cf-8945-4c276f02aea3

**Expensify/Expensify Issue URL:**
**Issue reported by:** @dhanashree-sawant
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1695225569076869

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~018a748087cda69421</li>
        <li>Upwork Job ID: 1705260542736433152</li>
        <li>Last Price Increase: 2023-09-22</li>
    </ul>
</details>

**Comment by ahmedGaber93** [comment] 2023-09-22 16:39
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
App becomes unresponsive on selecting and pasting same emoji in composer
### What is the root cause of that problem?
When we get the cursor position here
https://github.com/Expensify/App/blob/a240941e2a6d5143177c2ce2cf0dfc8776c9c043/src/pages/home/report/ReportActionCompose/ComposerWithSuggestions.js#L193

This loop run infinite, because the two values are the same, and no break for this
https://github.com/Expensify/App/blob/a240941e2a6d5143177c2ce2cf0dfc8776c9c043/src/libs/ComposerUtils/index.js#L39-L42
### What changes do you think we should make in order to solve the problem?
we need to break the loop when comparison end by adding this condition to while `str1.length > i && str2.length > i && ` or simply `Math.min(str1.length, str2.length) > i`


### What alternative solutions did you explore? (Optional)
N/A

**Comment by ahmedGaber93** [comment] 2023-09-22 17:12
I think this issue may be will not be reproduced after fix https://github.com/Expensify/App/issues/27672

**Comment by rameshvoodi** [comment] 2023-09-22 17:16
Hello @kbecciv  can i work on these issues even if didnt submit proposal in upwork, is there any bounty paid?

**Comment by narefyev91** [comment] 2023-09-25 06:45
@Christinadobrzyn hey - can you please put on hold this one - to wait a potential fix from this issue https://github.com/Expensify/App/issues/27672

**Comment by bfitzexpensify** [comment] 2023-09-26 09:42
Updated the title to hold for https://github.com/Expensify/App/issues/27672

**Comment by bfitzexpensify** [comment] 2023-09-28 16:22
https://github.com/Expensify/App/issues/27672 has been merged, so we should hopefully be good to check back on this early next week

**Comment by bfitzexpensify** [comment] 2023-10-02 21:46
Waiting for https://github.com/Expensify/App/issues/27672 to be deployed.

**Comment by bfitzexpensify** [comment] 2023-10-03 16:26
https://github.com/Expensify/App/issues/27672 is live, and it makes copying the emoji (step 4 in the reproduction steps) no longer possible, so this isn't doesn't exist any more. 

It looks like the report for https://github.com/Expensify/App/issues/27672 was made prior to this, so I'm going to consider this closed out with no further action required.

**Closed by bfitzexpensify** 2023-10-03 16:26 UTC
Labels: External, Daily, Help Wanted, Bug
