### ISSUE TITLE
[SMARTSCAN] [$500] LOW: Request – Receipt is not added in real time to Admin if as employee Request money manually.

### ISSUE THREAD

**Issue by izarutskaya** [Expensify/App#31818] opened 2023-11-24 11:18 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** v1.4.3-2
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** Applause-Internal Team
**Slack conversation:** @

## Action Performed:
1. Go to https://staging.new.expensify.com/
2. Create a WS as Admin.
3. As employee in the workspace chat create a Manual request (i.e with no receipt)
4. Once created > navigate to the request conversation
5. Click on the three dot menu in the header > Add receipt
6. As Admin open the workspace chat

## Expected Result:
Manual expense has a receipt attached in Admin

## Actual Result:
Receipt is not added in real time to Admin when as employee Request money manually and add receipt later.

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [x] Android: mWeb Chrome
- [ ] iOS: Native
- [x] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

https://github.com/Expensify/App/assets/115492554/df89f751-8eaa-4104-ba10-937d83506b85

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01e49203e1cb4382fe</li>
        <li>Upwork Job ID: 1728010305943076864</li>
        <li>Last Price Increase: 2023-12-08</li>
    </ul>
</details>

**Comment by FFX3** [comment] 2023-11-24 18:38
Contributor details
Your Expensify account email: justinmcintyre42@gmail.com
Upwork Profile Link: [https://www.upwork.com/freelancers/~0135572cbf7cb54c48](https://www.upwork.com/freelancers/~0135572cbf7cb54c48)

I found two corrections that solved the issue

# First

in ``src/libs/TransactionUtils.ts``

The ``TransactionUtils.hasReceipt`` method checks for the existence of a status property on the receipt object if it doesn't exit it determines that there is no receipt and doesn't later check for the image.

By checking instead for the ``receiptID`` property we can Identify when there is a receipt.

# Second

in ``src/libs/ReceiptUtils.ts``

The ``ReceiptUtils.getThumbnailAndImageURIs`` method checks the ``filename`` property on the transaction object, if the string is empty the function determines that there is no image and defaults to a generic placeholder image.

By using the source property on the receipt object within the transaction object we can get the filename and successfully render the image.

**Comment by giltron** [comment] 2023-11-24 19:20
## Proposal

### Please re-state the problem that we are trying to solve in this issue.

The receipt image fails to display due to not detecting receipt image and rendering receipt image on update.

### What is the root cause of that problem?

There are two issues:

1. The data received from the update API through Pusher does not return *receipt.state* and so the check fails at [TransactionUtils.hasReceipt]](https://github.com/Expensify/App/blob/3363c35ea1be897cc13393c6c7f27d513ba605fb/src/libs/TransactionUtils.ts#L85)
```
return !!transaction?.receipt?.state || hasEReceipt(transaction);
```

Example Response received:
```
{
    "data": [
        {
            "key": "transactions_3824595210035866360",
            "onyxMethod": "merge",
            "value": {
                "receipt": {
                    "receiptID": 675734846,
                    "source": "https://www.expensify.com/receipts/w_11f24f07f240fa5aa7ca57ec9f7a630533de3ba4.jpg"
                }
            }
        }
    ],
    "eventType": "onyxApiUpdate"
}
```

2. The transaction object is missing attribute filename so when [ReceiptUtils.getThumbnailAndImageURIs](https://github.com/Expensify/App/blob/1e4c84b8c17a8e08321dfbe91ea7e6e4bbddd54f/src/libs/ReceiptUtils.ts#L31) is called from MoneyRequestPreview so even if 1) was fixed the image won't be shown.

```
    const receiptImages = hasReceipt ? [ReceiptUtils.getThumbnailAndImageURIs(props.transaction)] : [];
```


### What changes do you think we should make in order to solve the problem?

1.  Update transactions [TransactionUtils.hasReceipt]](https://github.com/Expensify/App/blob/3363c35ea1be897cc13393c6c7f27d513ba605fb/src/libs/TransactionUtils.ts#L85) to check for  receipt.source or receipt.reportID
```
return !!transaction?.receipt?.source || hasEReceipt(transaction)
```


2.  Update MoneyRequestPreview L177 to parse and pass in addition the *receiptPath* and *receiptFileName* from props.transaction.receipt.source when invoking ReceiptUtils.getThumbnailAndImageURIs

```
const receiptImages = hasReceipt ? [ReceiptUtils.getThumbnailAndImageURIs(props.transaction)] : [];
```


### What alternative solutions did you explore? (Optional)


Modify change 2) in the solution:

Update ReceiptUtils.getThumbnailAndImageURIs (instead of passing in receiptPath and receiptFileName) to also check for transaction.receipt.source

```
    const filename = transaction?.filename ?? transaction?.receipt?.souce ?? receiptFileName ?? '';
```






### Note: I also noticed that on initial creation that transaction.receipt is returned as an array from the API where it should be an object.

**Comment by burczu** [comment] 2023-11-27 11:54
@FFX3 Please update your proposal using our [Proposal template](https://github.com/Expensify/App/blob/main/contributingGuides/PROPOSAL_TEMPLATE.md) - more about proposing solutions [here](https://github.com/Expensify/App/blob/main/contributingGuides/CONTRIBUTING.md#propose-a-solution-for-the-job).

**Comment by FFX3** [comment] 2023-11-27 22:16
Thanks @burczu for pointing me to the template.

I've updated my proposal.

## Proposal
[Updated](https://github.com/Expensify/App/issues/31818#issuecomment-1825989006)

**Comment by burczu** [comment] 2023-11-28 09:22
@conorpendergrast I've tried to reproduce this issue on the latest main and it works as expected for me. Could you help confirming it?

**Comment by burczu** [comment] 2023-12-05 10:00
@conorpendergrast Did you try to reproduce it maybe? I think we need confirmation here. Thanks

**Comment by conorpendergrast** [comment] 2023-12-05 14:34
I've been able to reproduce this issue, yes. The second request in the screenshot below is showing the uploaded receipt for the requestor, but not for the admin (ie: not in realtime). When the admin refreshes the page or navigates between chats, the receipt is then shown


<img width="1279" alt="image" src="https://github.com/Expensify/App/assets/5802477/4ecffece-6684-40d6-ab07-49b648dc6101">

**Comment by conorpendergrast** [comment] 2023-12-11 12:01
@burczu did you try to reproduce again?

**Comment by conorpendergrast** [comment] 2023-12-11 12:42
Lovely, thanks!

**Comment by burczu** [comment] 2023-12-11 13:03
@conorpendergrast I've checked both proposals but I think they are more like workarounds - in my opinion this may be a BE bug actually. From what I see, when we call the `ReplaceReceipt` Onyx action, the optimistic data does not match the response data. The optimistic data contains the `filename` along with `receipt` object, also the `receipt` object should contain the `state` property. These properties are not returned in the response and I believe this is the root cause of the problem. Also, as @giltron pointed out:

> Note: I also noticed that on initial creation that transaction.receipt is returned as an array from the API where it should be an object.

This should also be fixed on the BE side.

That being said, I believe that maybe we should switch to `Internal` to gather an opinion from BE engineer. What do you think?

**Comment by conorpendergrast** [comment] 2023-12-11 20:47
Sounds great @burczu and @Victor-Nyagudi, thank you! 

@amyevans hello Amy! I'm looking for your confirmation that, based on [this summary](https://github.com/Expensify/App/issues/31818#issuecomment-1850040931), this should be an `Internal` issue. Please and thank you!

**Comment by amyevans** [comment] 2023-12-11 22:38
Yeah I agree with the assessment this should be internal, seems we're missing a pusher update somewhere to get the updated Onyx data to the admin. Think this fits wave 5 or is there a better wave for it?

**Comment by amyevans** [comment] 2023-12-15 14:33
Asked about it in wave5: https://expensify.slack.com/archives/C05DWUDHVK7/p1702650808231339

**Comment by amyevans** [comment] 2023-12-15 16:15
Moving it to Wave 7 per discussion in the thread!

**Comment by conorpendergrast** [comment] 2023-12-18 14:26
Cool cool, thanks!

**Comment by conorpendergrast** [comment] 2023-12-22 11:59
This is internal will get picked up as part of wave5, so is not *really* overdue

**Comment by burczu** [comment] 2023-12-22 13:40
Hey @conorpendergrast! I'll be OOO till January 6th, and right after that I'm leaving the C+ role and joining Waves. Could you please assign another C+ engineer to handle this issue from now on? Thanks.

**Comment by situchan** [comment] 2024-01-04 17:13
I am interested in reviewing this as C+

**Comment by youssef-lr** [comment] 2024-01-05 12:36
This is most likely going to require a backend change. I'll be working on it on Monday.

**Comment by youssef-lr** [comment] 2024-01-08 23:37
No update yet, working on it this week.

**Comment by youssef-lr** [comment] 2024-01-11 19:49
I should have a PR up before by EOD tomorrow.

**Comment by youssef-lr** [comment] 2024-01-12 04:49
PR's ready.

**Comment by dylanexpensify** [comment] 2024-01-18 19:50
PR on prod! What's next here? Reviewing proposals?

**Comment by conorpendergrast** [comment] 2024-01-18 20:14
@dylanexpensify If the PR is on production isn't this fixed? Or are there more changes to make that you can see?

**Comment by dylanexpensify** [comment] 2024-01-18 20:28
Nope should be good - just payout then!

**Comment by dylanexpensify** [comment] 2024-01-18 20:28
oh jk no C+! Time to close!

**Closed by dylanexpensify** 2024-01-18 20:28 UTC
Labels: Reviewing, Engineering, Daily, Internal, Bug, SmartScan
