### ISSUE TITLE
[HOLD for payment 2022-10-07] [$500] mWeb/Safari -Profile - Header is highlighted when long-pressing the Save button.

### ISSUE THREAD

**Issue by kavimuru** [Expensify/App#10973] opened 2022-09-13 19:19 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Go to URL https://staging.new.expensify.com/
2. Log in any account
3. Go to Settings ->Profile
3. Long press the Save button

## Expected Result:
When long pressing the Save button, the button text should be highlighted.

## Actual Result:
A blue banner is displayed when the Save button is long-pressed.

## Workaround:
Visual

## Platform:

Where is this issue occurring?

- Mobile Web

**Version Number:** 1.2.0-0
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**Email or phone of affected tester (no customers):** 
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** 
https://user-images.githubusercontent.com/43996225/189990542-f5587762-26f5-4393-a29f-780b15206549.mp4
**Expensify/Expensify Issue URL:** 
**Issue reported by:** Applause internal team
**Slack conversation:** 

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by marcochavezf** [comment] 2022-09-13 22:40
I can't reproduce the error on Chrome (Android)

https://user-images.githubusercontent.com/6829422/190021651-8bd3465a-f099-437d-9500-1c39cf638a30.mp4

**Comment by kbecciv** [comment] 2022-09-19 20:21
@marcochavezf Issue is reproduced in mWeb/safari. It happens in IOU page as well.

https://user-images.githubusercontent.com/93399543/191109229-e69039f0-8c82-4fd2-b274-f5ad07bc4842.MP4

**Comment by marcochavezf** [comment] 2022-09-19 21:59
Oh I see thanks for clarifying @kbecciv, I'm going to apply the `External`label, seems that the blue banner is the cursor selecting in some way the title of the modal.

**Comment by neil-marcellini** [comment] 2022-09-19 22:36
I couldn't reproduce this at first. Then I figured out that it only happens if you `long press` on the save button. If you long press in safari it will highlight the nearest text I believe. I think the only way to disable this is to prevent the text from being selectable at all, but I don't think we should do that. I would say this is user error and not a bug. What do you think @marcochavezf @mananjadhav? If you all agree then let's close this.

**Comment by mallenexpensify** [comment] 2022-09-19 23:56
Posted https://www.upwork.com/jobs/~01c7e042fc552a8fa1
Thanks for updating the title and deets @neil-marcellini

**Comment by mananjadhav** [comment] 2022-09-20 12:05
You're right @neil-marcellini about long-press but with safari it should've selected the text on the button. Attached is an example from another website.

![IMG_6910](https://user-images.githubusercontent.com/3069065/191252601-209141ec-2438-416b-9771-72d839d35758.jpg)

**Comment by neil-marcellini** [comment] 2022-09-20 15:38
@mananjadhav that's a good point that it should highlight the Save button text. There might be some case where the user wants to copy the text in a button and that should work correctly, so let's keep this open as a low priority issue. Maybe we need to pass an `onLongPress` prop to the form button?
https://github.com/Expensify/App/blob/334b2107fe9cfa06ac7bbd26841a55509bb34486/src/components/Button.js#L244-L249

**Comment by marcochavezf** [comment] 2022-09-20 17:29
Yup, I agree that text should be selectable but not all the button area which I think any user would perceive it as a bug.

**Comment by mananjadhav** [comment] 2022-09-25 05:26
Waiting for proposals.

**Comment by mallenexpensify** [comment] 2022-09-26 22:41
Price Doubled to $500
https://www.upwork.com/jobs/~01c7e042fc552a8fa1

**Comment by dhairyasenjaliya** [comment] 2022-09-27 04:44
**Proposal**

- we should add onLongPress event along with new props textSelectable

`onLongPress={(e) => {
                            e.preventDefault();
                        }}`
                        
`textSelectable`

https://github.com/Expensify/App/blob/90a226b20f23eeb8a669664bf4474781125e196a/src/pages/iou/steps/IOUAmountPage.js#L281-L288
<img width="975" alt="Screenshot 2022-09-27 at 10 12 47 AM" src="https://user-images.githubusercontent.com/47522946/192433947-37ed2dfd-bbf0-4488-88df-e65ffef740a6.png">


- and on the button component, we need to add textSelectable to `textComponent`

https://github.com/Expensify/App/blob/90a226b20f23eeb8a669664bf4474781125e196a/src/components/Button.js#L180-L194



<img width="1377" alt="Screenshot 2022-09-27 at 10 13 15 AM" src="https://user-images.githubusercontent.com/47522946/192433997-f945a2eb-13ae-4359-aacb-e19f902e87d6.png">

**Results**

https://user-images.githubusercontent.com/47522946/192434127-9269c515-ede6-4f47-a303-a9fce318de92.mp4

**Comment by mananjadhav** [comment] 2022-09-27 04:52
@dhairyasenjaliya I am fine with the `selectable` prop. I am not sure why we need to pass `onLongPress={(e) => { e.preventDefault(); }}`.

Instead of passing the prop and setting them manually in each component? why not set the prop and make it true by default?

cc - @neil-marcellini

**Comment by dhairyasenjaliya** [comment] 2022-09-27 04:52
ah yes we can I was just worried if some component has custom onLongPress event

**Comment by mananjadhav** [comment] 2022-09-27 05:08
There is. `BigNumberPad` on small screen devices uses `Button` for numbers. But again I don't think so with setting `selectable`, it should cause any issues there. So if you can update the proposal with only `selectable` prop handling I am good.

**Comment by dhairyasenjaliya** [comment] 2022-09-27 05:13
let's say we set by default to selectable to true that will apply to all buttons on long press it will show a copy tooltip is that fine !

**Comment by mananjadhav** [comment] 2022-09-27 05:17
> also selectable true will apply on the native platform as well so is that fine as well?

Any downsides?

**Comment by dhairyasenjaliya** [comment] 2022-09-27 05:18
nope no downside it will just show the copy 

<img src=https://user-images.githubusercontent.com/47522946/192438386-1533dd17-63be-489d-ac82-55666a2c969f.png  width=50%>

**Comment by mananjadhav** [comment] 2022-09-27 05:25
I am fine with this.

**Comment by dhairyasenjaliya** [comment] 2022-09-27 06:00
**Revised Proposal**

- we should set selectable true by default 

`selectable`
 
 https://github.com/Expensify/App/blob/90a226b20f23eeb8a669664bf4474781125e196a/src/components/Button.js#L180-L196
 
**Results** 

**M-Safari**

https://user-images.githubusercontent.com/47522946/192434842-3be0486f-2e97-44d0-a083-dfb424248453.mp4

**M-chrome**

<img src=https://user-images.githubusercontent.com/47522946/192444977-146fbe70-b6b1-437b-937e-d8e3a5ae2496.jpg  width=50%>

**iOS App**

<img src=https://user-images.githubusercontent.com/47522946/192440060-d9c29f02-bf7c-4d3b-a280-5691a4499356.png  width=50%>

**Android**
<img width="324" alt="android" src="https://user-images.githubusercontent.com/47522946/192444487-1b81b772-9a7d-47b1-8031-1d45f94e7812.png">

**Comment by mananjadhav** [comment] 2022-09-27 17:06
@dhairyasenjaliya Looks good, with the only thing is don't hardcode `true`, rather pass it as props `textSelectable` as per your original proposal.

**Comment by mallenexpensify** [comment] 2022-09-27 17:48
@dhairyasenjaliya and @mananjadhav , can you please apply for the job and confirm here once you have? https://www.upwork.com/jobs/~01c7e042fc552a8fa1

**Comment by dhairyasenjaliya** [comment] 2022-09-28 03:48
**Default Props as true**      

- We can define props and set them by default as true

`const propTypes = {
    textSelectable: PropTypes.bool,
}`
`const defaultProps = {
    textSelectable: true,
}`

**Global**

        const textComponent = (
            <Text
                selectable //always true
                style={[
                    this.props.isLoading && styles.opacity0,
                    styles.pointerEventsNone,
                    styles.buttonText,
                    this.props.small && styles.buttonSmallText,
                    this.props.medium && styles.buttonMediumText,
                    this.props.large && styles.buttonLargeText,
                    this.props.success && styles.buttonSuccessText,
                    this.props.danger && styles.buttonDangerText,
                    ...this.props.textStyles,
                ]}
            >
                {this.props.text}
            </Text>
        );
  
     
**Manually passing**    

- We can add new props and forward props as`textSelectable` 
- But here we manually need pass props in each and every pages 

@mananjadhav I think you are referring to "**Default Props as true**" let me know what do you think we should add here from above 3

**Comment by dhairyasenjaliya** [comment] 2022-09-28 03:52
> @dhairyasenjaliya and @mananjadhav , can you please apply for the job and confirm here once you have? https://www.upwork.com/jobs/~01c7e042fc552a8fa1

Applied

**Comment by mananjadhav** [comment] 2022-09-28 04:14
Yes I meant `Default props as true`.

**Comment by dhairyasenjaliya** [comment] 2022-09-28 04:24
alright will be adding PR soon

**Comment by dhairyasenjaliya** [comment] 2022-09-28 06:05
@mananjadhav PR is up and ready for review  :)

**Comment by mananjadhav** [comment] 2022-09-28 06:49
I've reviewed and left comment on the PR, @dhairyasenjaliya .

**Comment by mallenexpensify** [comment] 2022-09-28 20:15
Hired @dhairyasenjaliya and @mananjadhav in Upwork

**Comment by mananjadhav** [comment] 2022-09-29 02:21
@mallenexpensify I am unable to accept the offer.

<img width="995" alt="image" src="https://user-images.githubusercontent.com/3069065/192924037-d8c7ca53-6181-46e3-b8bc-384edcd56c63.png">

**Comment by mallenexpensify** [comment] 2022-09-30 00:26
Weird, not sure what happened. Please accept this one @mananjadhav https://www.upwork.com/jobs/~0107ea8eaa05b6b325

**Comment by Julesssss** [comment] 2022-10-04 09:45
FYI, I'm reverting this PR because it's not a bug. The button text should not be highlightable. Perhaps web lets you do this by default, but we should definitely be implementing logic for this, as it should not happen on mobile. 

We'll still pay out the UpWork contract though.

**Comment by Julesssss** [comment] 2022-10-04 09:51
Reassigning as Matt is out this week.

**Comment by mananjadhav** [comment] 2022-10-04 13:03
Thanks @Julesssss for the info. Any specific reason we don't want the text to be selectable?

**Comment by Julesssss** [comment] 2022-10-04 13:22
It's just bad mobile UX. The benefit of having selectable text is minimal, and the downside is that users will occasionally see a context menu if they hold the button when they simply want to press a button. 

Notice that almost no app lets you do this on mobile. It does seem common on web though

**Comment by mananjadhav** [comment] 2022-10-04 14:02
Thanks for the clarification.

**Comment by neil-marcellini** [comment] 2022-10-04 16:04
Sorry, I thought it made sense on mobile. Should it be on mobile web only? If we don't want to add it at all I'm fine with that too.

**Comment by Julesssss** [comment] 2022-10-04 17:27
Personally, i don't think it's worth doing because the solution will need to only touch web and seems complex for little gain, but don't let that stop you if you think otherwise 🙂

**Comment by dhairyasenjaliya** [comment] 2022-10-04 19:59
Hello team, thank you for the heads up, any next step from my side related to PR

**Comment by neil-marcellini** [comment] 2022-10-05 17:26
@trjExpensify we decided in Slack [here](https://expensify.slack.com/archives/C01SKUP7QR0/p1664990197796209) that since we made a mistake originally determining that this is a bug, and the contributor and C+ did their work properly, they should be compensated fully.

**Comment by trjExpensify** [comment] 2022-10-05 18:45
Cool, sounds good. I've settled both contracts. Thanks, everyone. 🎉

**Closed by trjExpensify** 2022-10-05 18:45 UTC
Labels: External, Engineering, Daily, Help Wanted, Awaiting Payment
