### ISSUE TITLE
[$500] Chat - Entire multiline message with line break not displayed in composer while editing comment

### ISSUE THREAD

**Issue by izarutskaya** [Expensify/App#33051] opened 2023-12-14 10:11 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** v1.4.12-0
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** Applause-Internal Team
**Slack conversation:** @

## Action Performed:
1. Launch Expensify app
2. Sign in with gmail account
3. Navigate to any 1:1 conversation
4. Send a multiline message with line break
5. Tap & hold on message to view the action menu

## Expected Result:
Complete multiline message with line break should be displayed in edit compose box while editing comment

## Actual Result:
Entire multiline message with line break not displayed in composer while editing comment

Note : Issue happens with device in both online & offline mode (Please check the videos attached)

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [x] Android: mWeb Chrome
- [x] iOS: Native
- [x] iOS: mWeb Safari
- [ ] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

https://github.com/Expensify/App/assets/115492554/ab0c07d3-5c2a-417e-b5c2-395ae00618c3

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~0165c8cce495cfeb70</li>
        <li>Upwork Job ID: 1735241044421496832</li>
        <li>Last Price Increase: 2023-12-28</li>
    </ul>
</details>

**Comment by samilabud** [comment] 2023-12-14 22:35
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
Chat - Entire multiline message with line break not displayed in composer while editing comment

### What is the root cause of that problem?
Using flex prop in the style of the composer is causing multiline messages with line breaks not displayed (IPhone only), this seems to be an IOS bug when using flexbox in an input text.

### What changes do you think we should make to solve the problem?
We should remove the styles.flex1 prop from the next line when the user is using IPhone:

https://github.com/Expensify/App/blob/9d2ea87f057f843a822f770aeafc7e10a00c13f9/src/pages/home/report/ReportActionItemMessageEdit.js#L420

**Tests:**
Before changes:

https://github.com/Expensify/App/assets/5216036/9606fda7-7630-4276-82a4-6fca5a6a1848


After changes:

https://github.com/Expensify/App/assets/5216036/a2e70c97-374a-4746-b233-e2d3e3edf0a0

**Comment by jliexpensify** [comment] 2023-12-15 02:57
Matt A and I can both repro this. Tagged DB in #vip-vsb

**Comment by alitoshmatov** [comment] 2023-12-20 08:34
Reviewing

**Comment by jliexpensify** [comment] 2023-12-27 21:52
Hi @alitoshmatov how did your review go?

**Comment by alitoshmatov** [comment] 2023-12-29 20:03
Sorry I think I forgot to update here.

Currently I am not able to reproduce this issue:

https://github.com/Expensify/App/assets/59907218/f8792db0-19ef-4e79-afa5-12090bb9421e

**Comment by jliexpensify** [comment] 2024-01-01 04:15
Hmm, this was like 8 versions ago haha. I can't seem to repro either. Going to close this!

**Closed by jliexpensify** 2024-01-01 04:15 UTC
Labels: External, Daily, Help Wanted, Bug
