### ISSUE TITLE
[$1000] UserB can see the "completed task" message when clicking on a task checkbox that is not clickable for them

### ISSUE THREAD

**Issue by kavimuru** [Expensify/App#22110] opened 2023-07-03 13:43 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Login with userA's account
2. Open UserB's chat
3. Go to the "Assign task" section
4. Enter a title and create the task
5. Open a different browser and login with userB's account
6. Open UserA's chat
7. Check the task checkbox
8. Open the task details
## Expected Result: 
When userB clicks on a task checkbox that is not clickable for them, the "completed task" message should not be displayed
## Actual Result: 
When userB clicks on a task checkbox that is not clickable for them, the "completed task" message is still displayed
## Workaround:
Can the user still use Expensify without this being fixed? Have you informed them of the workaround?

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [x] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 1.3.35-5
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/43996225/df2060d3-6e26-42af-aeda-18d1863c1a50

https://github.com/Expensify/App/assets/43996225/5857410d-83e1-4fb0-92ab-235d17b022c6

**Expensify/Expensify Issue URL:**
**Issue reported by:** @ayazhussain79 
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1688163900893629

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~0198bc8ef923284f84</li>
        <li>Upwork Job ID: 1677136833296736256</li>
        <li>Last Price Increase: 2023-07-07</li>
    </ul>
</details>

**Comment by adelekennedy** [comment] 2023-07-07 02:06
yeah let's make this more seamless

**Comment by b4s36t4** [comment] 2023-07-10 19:58
## Proposal

### Please re-state the problem that we are trying to solve in this issue.

UserB can see the "completed task" message when clicking on a task checkbox that is not clickable for them

### What is the root cause of that problem?

The issue is with logic behind the disabling checkbox. 

There are two places we should disable the checkbox

* Report Screen
* TaskView Screen

In these both of Screens only logic behind to disable the checkbox is if it's a cancelled task. We should also check for the permissions for the task as well like is the user is an aissgner or the creator of the task.

Places logic is broken:

https://github.com/Expensify/App/blob/f889c42cc9d85aa5da8545df0b9e93191ecffdea/src/components/ReportActionItem/TaskView.js#L78

https://github.com/Expensify/App/blob/417e5301ec319934483426c269399ed8eee9f0d2/src/components/ReportActionItem/TaskPreview.js#L86

### What changes do you think we should make in order to solve the problem?

We should derive a variable maybe called `isDisabled` which checks for the both conditions i.e Is the task cancelled or don't have the permissions and pass it as props to the checkbox components here.

https://github.com/Expensify/App/blob/f889c42cc9d85aa5da8545df0b9e93191ecffdea/src/components/ReportActionItem/TaskView.js#L78

https://github.com/Expensify/App/blob/417e5301ec319934483426c269399ed8eee9f0d2/src/components/ReportActionItem/TaskPreview.js#L86

Also in-order to check the permission we should also update the PropTypes and onyxKeys for `TaskView` Component here
https://github.com/Expensify/App/blob/f889c42cc9d85aa5da8545df0b9e93191ecffdea/src/components/ReportActionItem/TaskView.js#L148



### What alternative solutions did you explore? (Optional)
Maybe doesn't allow creating the task if there's no assign?.

**Comment by Santhosh-Sellavel** [comment] 2023-07-10 20:34
Sorry missed this will look into it shortly

**Comment by b4s36t4** [comment] 2023-07-12 19:11
@Santhosh-Sellavel have you been through the proposals?

**Comment by Santhosh-Sellavel** [comment] 2023-07-12 19:58
@thienlnam Is this a valid bug?

**Comment by Santhosh-Sellavel** [comment] 2023-07-12 20:01
It doesn't look like a valid bug, we clearly share the task with the user so they should be able to view changes. 
But does not allow to change the status of the task as there not assigned.

**Comment by thienlnam** [comment] 2023-07-12 23:21
We can close this - I'm updating the access paradigm in this internal issue https://github.com/Expensify/Expensify/issues/296932 which allows anyone that can read the task to modify it.  
Also we have another issue to add an error when you fail to complete a task - not sure where it is though

**Closed by thienlnam** 2023-07-12 23:21 UTC
Labels: External, Daily, Help Wanted, Bug
