### ISSUE TITLE
[$500] iOS - Conversation - Green line between the first and second new messages when returning online

### ISSUE THREAD

**Issue by izarutskaya** [Expensify/App#31617] opened 2023-11-21 11:43 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.1.7
**Reproducible in staging?:** Y
**Reproducible in production?:** N
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** Applause-Internal Team
**Slack conversation:** @

## Action Performed:
Precondition: user should be signed in as account A on the main testing device and as account B on the secondary
1. Open app
2. As user A navigate to conversation with user B
3. Kill the app and disable the internet
4. From the second device send two messages as user B to user A
5. Open app on main testing device
6. Navigate to conversation with user B
7. Enable the internet connection

## Expected Result:
Green line should be displayed above two new messages

## Actual Result:
Green line displayed between first and second messages

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [x] iOS: Native
- [ ] iOS: mWeb Safari
- [ ] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

https://github.com/Expensify/App/assets/115492554/e6fa9d77-5777-405e-8dc1-b85544bc223e

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01645ac5adbffdae76</li>
        <li>Upwork Job ID: 1726929269907804160</li>
        <li>Last Price Increase: 2023-11-28</li>
    </ul>
</details>

**Comment by izarutskaya** [comment] 2023-11-21 11:44
Not reproduce in production

![IMG_1460](https://github.com/Expensify/App/assets/115492554/7ceac918-4912-49bc-a369-5aa5eb2e1173)

**Comment by situchan** [comment] 2023-11-21 11:53
@Julesssss the offending PR should be related to unread marker. i.e. #25935

**Comment by shubham1206agra** [comment] 2023-11-21 12:21
@situchan The PR is not in staging yet.

**Comment by situchan** [comment] 2023-11-21 12:26
@shubham1206agra it hit staging. 
There was deploy automation issue recently and that's why bot didn't comment on the PR.

<img width="1035" alt="Screenshot 2023-11-21" src="https://github.com/Expensify/App/assets/108292595/1fdf5a48-e659-409d-ad0f-b9428e9455b5">

**Comment by rlinoz** [comment] 2023-11-21 14:04
I am removing the deploy blocker label since this doesn't seem as critical.

**Comment by rlinoz** [comment] 2023-11-24 16:36
waiting for proposals.

**Comment by rlinoz** [comment] 2023-11-27 13:44
Waiting for proposals.

**Comment by keisyrzk** [comment] 2023-11-29 07:59
Tried multiple times and in my case it is working as intended. I could not reproduce the issue.
<img width="355" alt="Zrzut ekranu 2023-11-29 o 08 48 41" src="https://
<img width="347" alt="Zrzut ekranu 2023-11-29 o 08 47 34" src="https://github.com/Expensify/App/assets/18525360/f9cd2e62-c095-48ed-ae3f-df9bd49cfe3a">
github.com/Expensify/App/assets/18525360/86419e66-5b11-4ac1-a3b7-9d7646a7639f">

**Comment by rlinoz** [comment] 2023-11-29 13:12
Confirmed it is not reproducable anymore.

Closing it.

**Closed by rlinoz** 2023-11-29 13:12 UTC
Labels: External, Engineering, Daily, Help Wanted, Bug
