### ISSUE TITLE
Web - Status - Emoji in custom status holder is not centered

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#51497] opened 2024-10-25 20:18 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 9.0.54-1
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**If this was caught on HybridApp, is this reproducible on New Expensify Standalone?:** N/A
**If this was caught during regression testing, add the test name, ID and link from TestRail:** N/A
**Issue reported by:** Applause - Internal Team

**Issue found when executing EDGE test case** https://github.com/Expensify/App/issues/35389
## Action Performed:
1. Go to Settings > Profile > Status
2. Select a square emoji and save it
3. Return to home page

## Expected Result:
The emoji in custom status holder should be centered

## Actual Result:
The emoji in custom status holder is not centered

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Standalone
- [ ] Android: HybridApp
- [ ] Android: mWeb Chrome
- [ ] iOS: Standalone
- [ ] iOS: HybridApp
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

<details>
  <summary>Add any screenshot/video evidence</summary>

  
</details> 

![Bug6615170_1727291556062!status](https://github.com/user-attachments/assets/bdc38b25-0085-4b18-9794-16841126ad8b)

https://github.com/user-attachments/assets/a93962b2-af2b-45d9-a768-001b613216e5

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by lanitochka17** [comment] 2024-10-25 20:18
@OfstadC  FYI I haven't added the External label as I wasn't 100% sure about this issue. Please take a look and add the label if you agree it's a bug and can be handled by external contributors

**Comment by shahinyan11** [comment] 2024-10-25 20:47
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
Web - Status - Emoji in custom status holder is not centered
### What is the root cause of that problem?
Here we set `transform: 'scale(.5)'` and `fontSize: 22`  in emoji styles which brakes UI
### What changes do you think we should make in order to solve the problem?
Avoid using `transform` and `fontSize` together. We can remove `transform` and set font size `12` or Remove font size and set `transform: 'scale(0.8)'`

### What alternative solutions did you explore? (Optional)

**Comment by OfstadC** [comment] 2024-10-28 19:15
Maybe me eyes are playing tricks on me 😅 - but I don't see anything wrong here

<img width="797" alt="image" src="https://github.com/user-attachments/assets/86ac5aba-7663-4cb4-ad82-1c27c3ea7fce">

**Comment by shahinyan11** [comment] 2024-10-28 19:33
@OfstadC You can try one of the emojis below, with them more visible to the eye

![Screenshot 2024-10-28 at 23 28 12](https://github.com/user-attachments/assets/ba122c76-60e6-4d4c-adbe-db04feba112e)
![Screenshot 2024-10-28 at 23 28 23](https://github.com/user-attachments/assets/aaf073c9-0199-4527-9fbe-f8e03517e764)

**Comment by OfstadC** [comment] 2024-10-30 12:58
Thanks! I'm not sure this is a priority - but let me sense check in Slack

**Comment by OfstadC** [comment] 2024-11-01 15:31
@Expensify/design Do we think this is worth fixing?

**Comment by dannymcclain** [comment] 2024-11-01 16:02
Oh lord not this again 😂

Sooo, I use circles a lot, and my circles are looking _pretty_ well centered. Might be a fraction of a pixel off in the bottom tab, but the account settings one looks pretty good.

![CleanShot 2024-11-01 at 10 58 04@2x](https://github.com/user-attachments/assets/7fa87ce2-1402-4a0f-a002-c5c4757a7d0f)

![CleanShot 2024-11-01 at 10 58 36@2x](https://github.com/user-attachments/assets/b364b56b-9e7f-41c1-9aec-8d42aea0ee4a)

I think I'd be ok with doing nothing here because we've fussed with this quite a bit and I think a lot of the alignment issues come from certain/specific emojis—and I don't know that I feel confident we can 100% absolutely nail it for every single possible emoji ever. I'm certainly not against trying some more tweaks, I just don't know if the juice is worth the squeeze. Definitely curious for the other designers' thoughts on this though.

**Comment by shawnborton** [comment] 2024-11-01 16:52
Totally agree with all of your sentiments Danny - I think we have this about as good as we can get it, and I don't think any more improvements really makes the experience any better for anyone. I say we close this too, we have more important things to focus on.

**Comment by dubielzyk-expensify** [comment] 2024-11-04 04:50
Agree with the rest of the design team. It feels like we're as close as we'll get it and I'm pretty happy with how it looks in the product today 👍

**Comment by dannymcclain** [comment] 2024-11-04 14:23
@OfstadC We can go ahead and close this one.

**Comment by OfstadC** [comment] 2024-11-04 15:21
Thanks Design Team ❤️

**Closed by OfstadC** 2024-11-04 15:21 UTC
Labels: Daily, Overdue, Bug
