### ISSUE TITLE
[HOLD for payment 2024-03-11] [$500] Workspace - The selection is smaller than member name row when navigating via keyboard

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#37293] opened 2024-02-27 14:06 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.44-0
**Reproducible in staging?:** Y
**Reproducible in production?:** N
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** Applause - Internal Team
**Slack conversation:**

## Action Performed:
1. Go to staging.new.expensify.com
2. Go to Workspace settings
3. Select a workspace
4. Go to Members
5. Navigate through Members list with up and down key

## Expected Result:
The selection that appears on the member is of the same size as the member name row

## Actual Result:
The selection that appears on the member is smaller in size than the member name row

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence
 
 

https://github.com/Expensify/App/assets/78819774/456b936d-b917-4182-9dcd-3a3f5647754e

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~010ded8f191a9831bf</li>
        <li>Upwork Job ID: 1762479227522260992</li>
        <li>Last Price Increase: 2024-02-27</li>
<li>Automatic offers: </li>
<ul>
<li>hoangzinh | Reviewer | 0</li>
<li>dukenv0307 | Contributor | 0</li>
</ul></li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @JmillsExpensify</details>

**Comment by lanitochka17** [comment] 2024-02-27 14:06
We think that this bug might be related to #wave5-free-submitters
CC @dylanexpensify

**Comment by pecanoro** [comment] 2024-02-27 16:06
Ideally, this should be fixed by the author of the PR that broke it but since you guys identified the problem and have a solution, let's do that. This doesn't need to be a blocker since it's super minor.

**Comment by trjExpensify** [comment] 2024-02-27 16:12
Ah, I think @burczu might be fixing this already here: https://github.com/Expensify/App/pull/37199

CC: @shawnborton

**Comment by pecanoro** [comment] 2024-03-18 14:52
@JmillsExpensify All yours!

**Comment by JmillsExpensify** [comment] 2024-03-19 00:06
Great thanks! Payment summary as follows:

 - Contributor: @dukenv0307 $500
 - Contributor+: @hoangzinh $500
 
 
 I'll process both of these now via Upwork.

**Comment by JmillsExpensify** [comment] 2024-03-19 00:12
No regression test needed and contributors paid out, so closing.

**Closed by JmillsExpensify** 2024-03-19 00:12 UTC
Labels: External, Engineering, Daily, Awaiting Payment
