### ISSUE TITLE
[$1000] NotFoundPage briefly showed when logging from LoungeAccess deeplink

### ISSUE THREAD

**Issue by kavimuru** [Expensify/App#23826] opened 2023-07-28 20:56 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Logout if you're already logged in.
2. Copy the url to the lounge access route and paste to the browser url.
3.  Login with any account that has loungeAccess permission.
4. Observer the LoungeAccessPage.
## Expected Result:
 NotFoundView shouldn't briefly show with account that has  loungeAccess permission.
## Actual Result:
 NotFoundPage briefly showed when logging from LoungeAccess deeplink

## Workaround:
Can the user still use Expensify without this being fixed? Have you informed them of the workaround?

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [x] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 1.3.47-2
**Reproducible in staging?:** y (for me not found page persists, could be due to HT account)
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/43996225/0e9d6131-e4cd-4bfe-9b88-65b5cf58a555

https://github.com/Expensify/App/assets/43996225/c47ad525-a5a0-4ef7-90aa-e94163205ead

**Expensify/Expensify Issue URL:**
**Issue reported by:** @hungvu193 
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1690468091455469

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~011d8f08286fc0714f</li>
        <li>Upwork Job ID: 1688745991933755392</li>
        <li>Last Price Increase: 2023-08-08</li>
<li>Automatic offers: </li>
<ul>
<li>mollfpr | Reviewer | 26037614</li>
<li>hungvu193 | Contributor | 26037616</li>
<li>hungvu193 | Reporter | 26037618</li>
</ul></li>
    </ul>
</details>

**Comment by kavimuru** [comment] 2023-07-28 20:57
## Proposal from @hungvu193 
from @hungvu193 
### Please re-state the problem that we are trying to solve in this issue.
NotFoundPage briefly showed when logging from LoungeAccess deeplink
### What is the root cause of that problem?
We're checking in here if user doesn't have the `hasLoungeAccess` then returns `FullPageNotFoundView`. But if we login from LoungeAccess deeplink, it will take sometimes for the `user` to be loaded from `OpenApp`, so `user` will be empty for a while, which caused the issue.
https://github.com/Expensify/App/blob/96c765d94a3af6111262654cb3f83ab272ec88a2/src/pages/settings/Profile/LoungeAccessPage.js#L41-L43
### What changes do you think we should make in order to solve the problem?
We can add a loading view while we're loading the report data.

```javascript
        if (isLoadingReportData ) {
            return <FullscreenLoadingIndicator />;
        }

```
or
```javascript
       // _.isEmpty(user) to prevent it showed loading view every time we reload the page.
        if (isLoadingReportData && _.isEmpty(user)) {
            return <FullscreenLoadingIndicator />;
        }
```
and the `isLoadingReportData`:
```javascript
        isLoadingReportData: {
            key: `${ONYXKEYS.IS_LOADING_REPORT_DATA}`,
        },
```

### What alternative solutions did you explore? (Optional)
N/A

**Comment by JmillsExpensify** [comment] 2023-08-02 04:06
I don't deny this is a bug, even if the flow is unlikely. That said, @yuwenmemon curious for your thoughts on this one before I triage?

**Comment by JmillsExpensify** [comment] 2023-08-08 02:56
Going to go ahead and triage. Not sure if Yuwen is OOO.

**Comment by mollfpr** [comment] 2023-08-09 13:32
Thanks @hungvu193; I didn't see that there's another response from `OpenApp` for the `user` data.

The [proposal](https://github.com/Expensify/App/issues/23826#issuecomment-1656327320) from @hungvu193 looks good to me! Let's use this `isLoadingReportData && _.isEmpty(user)` logic instead, removing unnecessary loading.

🎀 👀 🎀 C+ reviewed!

**Comment by marcaaron** [comment] 2023-08-09 21:36
Proposal looks good so I am assigning. But one small suggestion - do we need `isLoadingReportData` at all? Can we check only for the `_.isEmpty(user)`? If so, better to avoid the weird dependency when the page doesn't appear to actually require anything about the report.

**Comment by marcaaron** [comment] 2023-08-10 18:10
>user object is empty because of offline mode or interrupt internet connection

I'd like to understand this edge case better. Can you offer an explanation, preferably in a step-by-step breakdown, of how we'd end up with an empty user object?

**Comment by marcaaron** [comment] 2023-08-11 18:15
Unless it is clearly reproducible I'd rather have the code be logical than covering an edge case that is poorly understood. I still don't quite understand what bug you are referring to and the root cause is not well explained.

**Comment by mollfpr** [comment] 2023-08-22 11:42
We are still waiting for an account with `hasLoungeAccess` for testing purposes. @JmillsExpensify could you help with this? We have this [thread](https://expensify.slack.com/archives/C01GTK53T8Q/p1692066398984799) for that.

**Comment by mollfpr** [comment] 2023-09-12 11:52
@JmillsExpensify @marcaaron We still can't test the PR because it needs the account with `hasLoungeAccess`. The tricks that @hungvu193 did before seem not work for me.

According to Yuwen [here](https://expensify.slack.com/archives/C01GTK53T8Q/p1692638781726619?thread_ts=1692066398.984799&cid=C01GTK53T8Q), we need to add the account to a policy that the billing owner has a card on file.

Do we have a test policy for that?

**Comment by mollfpr** [comment] 2023-09-18 14:12
Friendly bump @JmillsExpensify @marcaaron ^

**Comment by marcaaron** [comment] 2023-09-19 03:25
I don't really have the answer sorry. I am not sure if we have a test policy available for this. @yuwenmemon do you understand what @mollfpr is asking?

**Comment by yuwenmemon** [comment] 2023-09-19 03:38
Most of our contributors don't have lounge access because they don't belong to a paying group policy. So we'd need to add them to one in order for them to be able to reproduce this. Can we add them to the same one the tester is using?

**Comment by JmillsExpensify** [comment] 2023-10-16 15:44
I'm not familiar with this implementation and @yuwenmemon is out on sabbatical. @sakluger do you?

**Comment by JmillsExpensify** [comment] 2023-10-24 18:04
@sakluger Do you know who can help answer the above question?

**Comment by hungvu193** [comment] 2023-11-20 09:53
can any internal engineer can help with the screenshot of the PR?

**Comment by marcaaron** [comment] 2023-11-21 23:40
The status of this page in general is unclear now that the lounge is closed. I am going to close this one out for focus. We can clean it up later.

**Comment by mollfpr** [comment] 2023-11-22 11:45
@JmillsExpensify Does this issue have a compensation since @hungvu193 already works on the PR, and we are stuck on testing it properly?

**Comment by hungvu193** [comment] 2023-12-11 03:53
Hey, can you answer @mollfpr concern? This issue was only stuck because of testing for months. @JmillsExpensify

**Comment by mallenexpensify** [comment] 2024-02-28 17:39
@mollfpr @hungvu193 , new here... it appears
- @hungvu193 [was hired](https://github.com/Expensify/App/issues/23826#event-10047037778)
- [PR was created](https://github.com/Expensify/App/pull/24354)
- Issue was closed by Expensify, per our discretion. 

If that's correct, you'd both be due compensation since you were hired and did work on the proposal and PR before it was closed.  I'll await comments then I can help with payment, if needed.

**Comment by hungvu193** [comment] 2024-02-29 02:43
> * @hungvu193 [was hired](https://github.com/Expensify/App/issues/23826#event-10047037778)
> * [PR was created](https://github.com/Expensify/App/pull/24354)
> * Issue was closed by Expensify, per our discretion.

Yes, that's correct.

**Comment by mallenexpensify** [comment] 2024-03-02 00:25
Contributor: @hungvu193 paid $1000 via Upwork
Contributor+: @mollfpr paid $1000 via Upwork

Thanks @hungvu193 , closing now. 



Thanks @hungvu193

**Closed by mallenexpensify** 2024-03-02 00:25 UTC
Labels: Reviewing, External, Monthly, Bug
