### ISSUE TITLE
[HOLD for payment 2024-02-07] [$500] Expense - Green dot does not appear in LHN when the request is created in workspace chat

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#32924] opened 2023-12-12 14:40 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** v1.4.11-13
**Reproducible in staging?:** y
**Reproducible in production?:** n
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** Applause - Internal Team
**Slack conversation:**

## Action Performed:
1. Go to staging.new.expensify.com.
2. Create a new workspace.
3. Click FAB > Request money > Manual.
4. Request money from a workspace chat.
5. Note that the green dot appears in the workspace chat in LHN after the request is created.
6. Create a new workspace.
7. Go to the workspace chat > + > Request money.
8. Create a manual expense in the workspace chat.
9. Click on the expense preview to open report page.
10. Return to the main chat.

## Expected Result:
In Step 8. the green dot will appear next to workspace chat in LHN.

## Actual Result:
In Step 8. the green dot does not appear next to the workspace chat in LHN, when the request is created in the workspace chat.
In Step 10, the green dot only appears after opening report page and returning to the main chat.

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [x] Android: mWeb Chrome
- [x] iOS: Native
- [x] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

https://github.com/Expensify/App/assets/93399543/8210448d-8e61-4e68-8b12-7cdf785c9b5f

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~013b75f81794691835</li>
        <li>Upwork Job ID: 1734657794835312640</li>
        <li>Last Price Increase: 2023-12-19</li>
<li>Automatic offers: </li>
<ul>
<li>getusha | Reviewer | 28066191</li>
<li>tienifr | Contributor | 28066192</li>
</ul></li>
    </ul>
</details>

**Comment by shubham1206agra** [comment] 2023-12-12 18:19
I am gonna investigate this one in the meantime

**Comment by shubham1206agra** [comment] 2023-12-12 19:10
I am unable to repro this. I am not seeing Green Dot Indicator in both cases

**Comment by luacmartins** [comment] 2023-12-12 19:21
I can't reproduce either, but I think that we should show the green dot. It shows up if you navigate to another report and then back to the workspace chat.

**Comment by shubham1206agra** [comment] 2023-12-12 19:27
True, but same behaviour is in prod I think. @kbecciv Can you confirm this?

**Comment by luacmartins** [comment] 2023-12-12 19:30
In prod the workspace chat just disappears from the LHN in focus mode lol

**Comment by luacmartins** [comment] 2023-12-12 19:32
I think we're missing `hasOutstandingChildRequest` in the chat report

**Comment by luacmartins** [comment] 2023-12-12 19:32
I'm gonna demote this to NAB since the prod behavior is also broken.

**Comment by dylanexpensify** [comment] 2023-12-13 08:50
@getusha can we review? 🙇‍♂️

**Comment by getusha** [comment] 2023-12-13 09:22
Reviewing

**Comment by getusha** [comment] 2023-12-13 09:26
@bernhardoj will there be any issues if we just set `hasOutstandingChildRequest` to true in `optimisticData`?

**Comment by shubham1206agra** [comment] 2023-12-13 09:52
@dylanexpensify I think https://github.com/Expensify/App/issues/32779 should handle this issue

**Comment by getusha** [comment] 2023-12-17 19:36
waiting for @yuwenmemon's input here https://github.com/Expensify/App/issues/32779#issuecomment-1853351011

**Comment by dylanexpensify** [comment] 2023-12-20 09:30
@nkuoch mind chiming in?

**Comment by getusha** [comment] 2023-12-20 09:32
@nkuoch We can proceed with @tienifr's [proposal](https://github.com/Expensify/App/issues/32924#issuecomment-1853168412)

**Comment by nkuoch** [comment] 2023-12-20 16:27
Actually, also ccing @amyevans as I'm confused about the right behavior to have, as this [back end PR](https://github.com/Expensify/Auth/commit/5b7c924b5aaf9b549fdfe65671a1a9e61a79f8de#diff-dccb44cf036f0d8f9ea7278bacf5670b5e6b5d1f11f48fc203644400c1806d15R1751) is stating we shouldn't show the green dot in this case as the requestor doesn't need to do anything.

**Comment by luacmartins** [comment] 2023-12-20 16:30
The LHN green dot should not show for the user who sent the request since there's no action for them to take. The dot should however be shown to the payer.

**Comment by nkuoch** [comment] 2023-12-21 10:48
@luacmartins I think the confusion here is that the user is sending the request to a workspace they are admin of.
So, on one side we tell not to show the green dot if user is the requestor, but on the other side we tell to show the green dot if they are admin of the workspace, who can actually act on the request I believe.

**Comment by luacmartins** [comment] 2023-12-21 10:53
Hmm in that case I believe being an admin should take precedence and we should show the green indicator, since the user/admin should act on the request.

**Comment by nkuoch** [comment] 2023-12-21 12:05
Back end PR in review: https://github.com/Expensify/Auth/pull/9514

**Comment by getusha** [comment] 2023-12-29 09:55
@nkuoch is the Backend PR merged?

**Comment by nkuoch** [comment] 2023-12-30 15:34
yes!

**Comment by dylanexpensify** [comment] 2024-01-08 09:09
Nice! @getusha what's left here?

**Comment by getusha** [comment] 2024-01-08 16:16
@dylanexpensify reviewing the PR, currently having an [issue](https://github.com/Expensify/App/issues/33560) while inviting other account to a workspace to test more cases.

**Comment by dylanexpensify** [comment] 2024-01-17 09:35
Got it - have we resolved this @getusha? 🙇‍♂️

**Comment by getusha** [comment] 2024-01-17 12:28
@dylanexpensify yes, i found a workaround for that issue. will complete the review today.

**Comment by dylanexpensify** [comment] 2024-01-23 13:23
pending payout next

**Comment by getusha** [comment] 2024-01-29 10:05
PR is merged, and pending to be deployed to staging.

**Comment by dylanexpensify** [comment] 2024-01-29 11:47
Nice!

**Comment by getusha** [comment] 2024-02-06 17:01
BugZero Checklist: The PR fixing this issue has been merged! The following checklist ([instructions](https://stackoverflow.com/c/expensify/questions/14574)) will need to be completed before the issue can be closed:

 [@getusha] The PR that introduced the bug has been identified. Link to the PR: N/a **looks like a case we missed that required Back-End changes.**
 [@getusha] The offending PR has been commented on, pointing out the bug it caused and why, so the author and reviewers can learn from the mistake. Link to comment: **N/a**
 [@getusha] A discussion in #expensify-bugs has been started about whether any other steps should be taken (e.g. updating the PR review checklist) in order to catch this type of bug sooner. Link to discussion: **N/a**
 [@getusha] Determine if we should create a regression test for this bug. **Yes**
 [@getusha] If we decide to create a [regression test](https://github.com/Expensify/App/blob/main/contributingGuides/REGRESSION_TEST_BEST_PRACTICES.md) for the bug, please propose the regression test steps to ensure the same bug will not reach production again.

### Regression Test Proposal

1. Create a workspace.
2. Open the workspace chat
3. Press + > Manual > Request Money from the workspace chat
4. Verify that the green dot appears next to workspace chat in LHN.

Do we agree 👍 or 👎

**Comment by dylanexpensify** [comment] 2024-02-07 10:37
today!

**Comment by dylanexpensify** [comment] 2024-02-12 10:29
Payment summary:
- Contributor: @tienifr $500
- Contributor+: @getusha $500

**Comment by dylanexpensify** [comment] 2024-02-12 10:35
done!

**Closed by dylanexpensify** 2024-02-12 10:35 UTC
Labels: External, Engineering, Daily, Awaiting Payment, Bug
