### ISSUE TITLE
[HOLD #35572] [$500] Chat - Keyboard not dismissed after tapping flag as offensive in thread

### ISSUE THREAD

**Issue by m-natarajan** [Expensify/App#36373] opened 2024-02-12 20:56 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.40-0
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** Applause internal team
**Slack conversation:**

## Action Performed:
1. Open the app and log in
2. Navigate to any chat
3. Long tap the other user's comment
4. Select "Reply in thread"
5. Send a message in the thread
6. Long tap the parent message
7. Select "Flag as offensive"

## Expected Result:
The keyboard is dismissed shortly after the Flag as offensive screen is opened

## Actual Result:
The keyboard is not dismissed

## Workaround:
unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [x] iOS: Native
- [ ] iOS: mWeb Safari
- [ ] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

https://github.com/Expensify/App/assets/38435837/20ce9df8-2aa6-45e6-bd08-6ce4893a19b5

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~019d72fa1fa48fb3a5</li>
        <li>Upwork Job ID: 1757146714590474240</li>
        <li>Last Price Increase: 2024-02-19</li>
    </ul>
</details>

**Comment by m-natarajan** [comment] 2024-02-12 20:57
We (Applause) think this might be related to #vip-vsb
cc @quinthar

**Comment by ikevin127** [comment] 2024-02-13 17:40
## Proposal

### Please re-state the problem that we are trying to solve in this issue.

The keyboard is not dismissed after tapping Flag as offensive from the thread context menu.

### What is the root cause of that problem?

This is a known issue of our modal implementation vs composer refocus / keyboard, more details can be found [here](https://github.com/Expensify/App/pull/29199#issue-1935625319).

Clicking "Flag as offensive" in the context menu calls navigate to the FlagCommentPage, but the composer regains focus when the menu closes, causing the keyboard to pop up and when navigate is called the keyboard will remain open once navigated to the FlagCommentPage (where we don't actually need a keyboard).

### What changes do you think we should make in order to solve the problem?

As I mentioned in another similar issue's proposal [here](https://github.com/Expensify/App/issues/35778#issuecomment-1926959311), a workaround would look something like this:
- create a `delayExecution` helper function which uses promise that resolves with a delay (we need the delay as calling composer blur immediately after the menu closes wouldn't work)
- use this function by calling composer blur (unfocus) after the menu closes with given delay
- in the 2nd `then` of the promise call the current navigate to the FlagCommentPage

<details>
<summary>Code spoiler</summary>

```js
// new util function w/ default 300ms delay
function delayExecution(timeout = CONST.ANIMATED_TRANSITION): Promise<void> {
    return new Promise((resolve) => {
        setTimeout(() => {
            resolve();
        }, timeout);
    });
}

// to be used like this in our case:
delayExecution().then(() => {
    ReportActionComposeFocusManager.composerRef.current?.blur();
}).then(() => {
    Navigation.navigate(ROUTES.FLAG_COMMENT.getRoute(reportID, reportAction?.reportActionID))
});
```

</details>

**Good thing about this solution**: composer refocuses / keyboard pops back up when going back from the FlagCommentPage to the thread or choosing one of the flag options which also returns the user back to the thread (see `After` video).

We can use this helper function within the onPress -> `hideContextMenu` of the "Flag as offensive" context menu action:

https://github.com/Expensify/App/blob/07d97efe708f6c609c52ed7b1740fc2a249a4947/src/pages/home/report/ContextMenu/ContextMenuActions.tsx#L459

just like demonstrated within the `Code spoiler` above.

This will ensure that the composer is blurred (unfocused) when the "Flag as offensive" context menu action is called and the keyboard will be dismissed before we are navigated to the FlagCommentPage.

### Videos

<details>
<summary>iOS: Native</summary>

| Before | After |
| ------------- | ------------- |
| <video src="https://github.com/Expensify/App/assets/56457735/641633a2-de9f-4591-aa0f-555e8a4a4812"> | <video src="https://github.com/Expensify/App/assets/56457735/9e31ee21-fd9a-4953-a408-8f46fde61eae"> |

</details>

### What alternative solutions did you explore? (Optional)

Put issue on hold and wait (indefinitely) for PR https://github.com/Expensify/App/pull/29199 to be merged as this will add better context menu actions / composer focus state management which will allow us to better handle these kind of composer focus / keyboard issues.

**Comment by bfitzexpensify** [comment] 2024-02-16 01:22
I'm able to reproduce:


https://github.com/Expensify/App/assets/38236554/93515c40-804f-4663-b8d0-3e3b38d55cbb

**Comment by strepanier03** [comment] 2024-02-16 01:25
Thank you @bfitzexpensify.

**Comment by ikevin127** [comment] 2024-02-21 15:02
More context regarding a possible resolve for the mentioned hold, in this Slack thread: https://expensify.slack.com/archives/C01GTK53T8Q/p1708525183773549

**Comment by strepanier03** [comment] 2024-02-21 23:12
Thanks, putting on hold.

**Comment by strepanier03** [comment] 2024-03-02 00:39
From the linked discussion it looks like we agreed to keep this on hold.

**Comment by strepanier03** [comment] 2024-03-13 22:46
Still on Hold.

**Comment by strepanier03** [comment] 2024-03-27 00:00
It looks like https://github.com/Expensify/App/pull/29199 is closed now so I retested and the behavior continues to occur.

**Comment by strepanier03** [comment] 2024-03-27 00:01
Aaah, the PR was closed, not deployed so we're still on hold. Updating that now.

**Comment by strepanier03** [comment] 2024-04-16 22:16
It is labeled for Low priority but that doesn't mean it can't be worked on, just that other higher-priority bugs/tasks exist that are considered more valuable to complete.

**Comment by strepanier03** [comment] 2024-05-03 23:00
Waiting for prioritization.

**Comment by strepanier03** [comment] 2024-06-19 02:57
Low status and on hold.

**Comment by strepanier03** [comment] 2024-07-24 18:16
Thanks @fedirjh for the ping, testing now.

**Comment by strepanier03** [comment] 2024-07-24 18:27
I asked for testing internally. I don't have a physical iOS device and browserstack isn't working for me atm.

**Comment by mallenexpensify** [comment] 2024-07-24 21:07
Swapping issues with Sheena since she's Android and I'm iOS

**Comment by mallenexpensify** [comment] 2024-07-29 22:48
I lose the option to flag as offensive for some reason. @fedirjh , any idea why this might be the case?


https://github.com/user-attachments/assets/8fcdb5c8-a8a9-4ae2-88bf-0853d71da31f

**Comment by mallenexpensify** [comment] 2024-07-30 23:54
Thanks @fedirjh , that was likely it (if only cuz I was able to reproduce when I selected another chat)
Unable to reproduce the bug.  Are you @fedirjh

**Comment by mallenexpensify** [comment] 2024-08-06 23:26
Thanks @fedirjh , closing!

**Closed by mallenexpensify** 2024-08-06 23:26 UTC
Labels: External, Weekly, Help Wanted, Bug
