### ISSUE TITLE
[HOLD for payment 2023-08-21] [$1000] Web - Close account button moves up when offline 

### ISSUE THREAD

**Issue by mvtglobally** [Expensify/App#24145] opened 2023-08-04 02:15 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Go to Settings
2. Go to Security
3. Go to Close account
4. Turn off internet connectivity
5. Observe that the 'Close account' button moves up

## Expected Result:
The 'Close account' button should not move up

## Actual Result:
The 'Close account' button moves up

## Workaround:
unknown 

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [X] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 1.3.47-5
**Reproducible in staging?:** Y 
**Reproducible in production?:**  Y 
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation 

https://github.com/Expensify/App/assets/43995119/9a114f88-f6a3-412c-9c64-29545230df9b

https://github.com/Expensify/App/assets/43995119/9c8d9667-143f-4e55-9211-4bcb611d3c4f

**Expensify/Expensify Issue URL:**
**Issue reported by:** @samh-nl
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1690808066297639 

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~014e4d7f9dee0bbcde</li>
        <li>Upwork Job ID: 1687508110295552000</li>
        <li>Last Price Increase: 2023-08-04</li>
<li>Automatic offers: </li>
<ul>
<li>samh-nl | Contributor | 26007987</li>
<li>samh-nl | Reporter | 26007989</li>
</ul></li>
    </ul>
</details>

**Comment by mvtglobally** [comment] 2023-08-04 02:16
proposal from @samh-nl '

## Proposal

### Please re-state the problem that we are trying to solve in this issue.
Close account button moves up when offline

### What is the root cause of that problem?
We add margin to the bottom of the button via `style={[styles.mb3]}` if the button is disabled due to being offline:

https://github.com/Expensify/App/blob/dc3270005e924e49a890028bd4b3ef094a939227/src/components/FormAlertWithSubmitButton.js#L74-L93

This margin was added in [this commit](https://github.com/Expensify/App/commit/420c1fcc3e2952e69b033168f7d5b9a77615bc08), with the intention of adding extra space to the offline indicator which was present underneath the button at the time. However, currently there is no such indicator. Instead, we optionally render `{props.footerContent}`, which is not defined here.


### What changes do you think we should make in order to solve the problem?
Option 1. If `props.footerContent` is defined, we apply this margin (regardless of being online/offline). This is the case for example on the Workspace invite message page, where a privacy policy link is at the bottom.
Option 2. We remove the margin from the offline button.

### What alternative solutions did you explore? (Optional)
N/A

**Comment by jeet-dhandha** [comment] 2023-08-04 02:59
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
- We get extra `marginBottom` in `Close Account` button of CloseAccountPage when we go offline.

### What is the root cause of that problem?
- We use `marginBottom` when user is offline. Thus, we get extra `marginBottom` in `Close Account` button.

https://github.com/Expensify/App/blob/dc3270005e924e49a890028bd4b3ef094a939227/src/components/FormAlertWithSubmitButton.js#L74-L81

### What changes do you think we should make in order to solve the problem?
- We can create a `offlineSubmitButtonStyle` prop in `Form.js` and also in `FormAlertWithSubmitButton.js` and use it when user is offline.
```
offlineSubmitButtonStyle={styles.mb0}
```

### What alternative solutions did you explore? (Optional)
- N/A

**Comment by joekaufmanexpensify** [comment] 2023-08-04 16:56
Okay, sounds like we do want to fix this, since it is ultimately a design inconsistency (even if it doesn't impact the user experience).

**Comment by sasikanth513** [comment] 2023-08-04 17:16
# Proposal

### Please re-state the problem that we are trying to solve in this issue.

Close button is shifting position(moving up) when user goes offline


### What is the root cause of that problem?

This issue happens because we have different styles when user is in offline vs when user is online

https://github.com/Expensify/App/blob/main/src/components/FormAlertWithSubmitButton.js#L74-L92


### What changes do you think we should make in order to solve the problem?

Button position should be consistent independent of users network status. Jumping ui when user is offline is bad ux.

we should remove `style={[styles.mb3]}` from this code

```js
{isOffline && !props.enabledWhenOffline ? (
    <Button
        success
        isDisabled
        text={props.buttonText}
        style={[styles.mb3]}
        danger={props.isSubmitActionDangerous}
    />
	) : (
	...
)}
```

because it affects the button position all over the app not only this screen whenever this component is used

### What alternative solutions did you explore? (Optional)

`N/A`

**Comment by sasikanth513** [comment] 2023-08-04 17:18
Contributor details
Your Expensify account email: sasi.kanth80@gmail.com
Upwork Profile Link: https://www.upwork.com/freelancers/~011c7d0fb80b85f8d6

**Comment by expertscoders** [comment] 2023-08-04 19:30
Contributor details
Your Expensify account email: anesdj51@gmail.com
Upwork Profile Link: https://www.upwork.com/freelancers/~016523f8c3559bc9a5

**Comment by expertscoders** [comment] 2023-08-04 19:31
Contributor details
Your Expensify account email: [anesdj51@gmail.com](mailto:anesdj51@gmail.com)
Upwork Profile Link: https://www.upwork.com/freelancers/~016523f8c3559bc9a5

**Comment by expertscoders** [comment] 2023-08-04 19:32
Contributor details
Your Expensify account email: anesdj51@gmail.com
Upwork Profile Link: https://www.upwork.com/freelancers/~016523f8c3559bc9a5

**Comment by saalimzafar** [comment] 2023-08-05 18:04
Anyone here who can help me to setup the project for local development.
After signing it leads me to the main website instead of remaining local.

After cloning what exact changes should I make?

**Comment by Abilashinamdar** [comment] 2023-08-07 03:33
Contributor details
Your Expensify account email: [abiinamdar9294@gmail.com](mailto:abiinamdar9294@gmail.com)
Upwork Profile Link: https://www.upwork.com/freelancers/~01b7197ac279c62500

**Comment by Abilashinamdar** [comment] 2023-08-07 03:38
Contributor details
Your Expensify account email: [abiinamdar9294@gmail.com](mailto:abiinamdar9294@gmail.com)
Upwork Profile Link: https://www.upwork.com/freelancers/~01b7197ac279c62500

**Comment by Abilashinamdar** [comment] 2023-08-07 03:43
Contributor details
Your Expensify account email: abiinamdar9294@gmail.com
Upwork Profile Link: https://www.upwork.com/freelancers/~01b7197ac279c62500

**Comment by narefyev91** [comment] 2023-08-07 06:42
Proposal from @samh-nl looks good to me https://github.com/Expensify/App/issues/24145#issuecomment-1664877031. In case we still have footerContent props - we should still give a room of margin if some content will be passed and offline will be switched on.
🎀 👀 🎀 C+ reviewed

**Comment by saalimzafar** [comment] 2023-08-07 08:25
Hi @narefyev91
I want to report a bug, but it got closed automatically after I created an issue.
Can you help me in this, as I'm unavailable to join slack channel, when I follow the link it says you are already signed in to this workspace, but I'm not.

**Comment by joekaufmanexpensify** [comment] 2023-08-07 19:39
Proposal pending internal review.

**Comment by joekaufmanexpensify** [comment] 2023-08-07 19:39
@saalimzafar if you're having issues joining the Slack channel, please reach out to contributors@expensify.com and our team will be happy to assist!

**Comment by saalimzafar** [comment] 2023-08-07 20:07
Thanks @jamesdeanexpensify, 
I already got the response from contributor and I have joined the channel.

**Comment by neil-marcellini** [comment] 2023-08-07 21:13
I also like @samh-nl's [proposal](https://github.com/Expensify/App/issues/24145#issuecomment-1664877031), I like option1 in the solution.

> Option 1. If `props.footerContent` is defined, we apply this margin (regardless of being online/offline). This is the case for example on the Workspace invite message page, where a privacy policy link is at the bottom.

**Comment by joekaufmanexpensify** [comment] 2023-08-07 21:28
It's because they haven't commented on the issue. @samh-nl could you please comment here so we can assign you?

**Comment by joekaufmanexpensify** [comment] 2023-08-18 21:16
@narefyev91 mind completing your portion of the BZ checklist here when you have a sec? Then, I'll prep to issue payment on Monday.

**Comment by joekaufmanexpensify** [comment] 2023-08-21 12:45
Checklist complete. All set to issue payment!

**Comment by joekaufmanexpensify** [comment] 2023-08-21 12:47
This bug qualified for [an urgency bonus](https://github.com/Expensify/App/issues/24145#issuecomment-1671939774), so we need to issue the following payments here: 

- @samh-nl - $1,500 (for PR and speed bonus). 
- @samh-nl - $250 (for bug reporting bonus). 
- @narefyev91 - no direct payment needed on issue, since they're with an agency.

**Comment by joekaufmanexpensify** [comment] 2023-08-21 12:47
@samh-nl since you were hired twice in Upwork for the two roles, going to send the payment for both separately.

**Comment by joekaufmanexpensify** [comment] 2023-08-21 12:49
@samh-nl $1,500 sent and contract ended!

**Comment by joekaufmanexpensify** [comment] 2023-08-21 12:50
@samh-nl $250 sent and contract ended!

**Comment by joekaufmanexpensify** [comment] 2023-08-21 12:50
Upwork job closed.

**Comment by joekaufmanexpensify** [comment] 2023-08-21 12:50
Bug is fixed, BZ checklist complete, and all payment issued. Closing as this is all set. Thanks everyone!

**Closed by joekaufmanexpensify** 2023-08-21 12:50 UTC
Labels: External, Daily, Awaiting Payment, Bug
