### ISSUE TITLE
IOU - Add stop button is not aligned in the center

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#38266] opened 2024-03-14 01:00 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.52
**Reproducible in staging?:** Y
**Reproducible in production?:** N
**If this was caught during regression testing, add the test name, ID and link from TestRail:** N/A
**Issue reported by:** Applause - Internal Team

## Action Performed:
1. Go to https://staging.new.expensify.com
2. Tap fab ---Request money--Distance
3. Enter start and stop point
4. Note Add stop button

## Expected Result:
Add stop button must be aligned in the center

## Actual Result:
Add stop button is not aligned in the center

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [x] Android: mWeb Chrome
- [x] iOS: Native
- [x] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details> 

![Bug6412954_1710376794645!Screenshot_2024-03-14-06-05-22-142_com android chrome-edit](https://github.com/Expensify/App/assets/78819774/a011c037-23ea-49f1-a430-7cee1dde4bd9)

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by lanitochka17** [comment] 2024-03-14 01:01
Production: 

![image](https://github.com/Expensify/App/assets/78819774/8f3bcd31-3c61-434b-a152-2bb4d331339c)

**Comment by lanitochka17** [comment] 2024-03-14 01:01
@marcaaron  FYI I haven't added the External label as I wasn't 100% sure about this issue. Please take a look and add the label if you agree it's a bug and can be handled by external contributors

**Comment by lanitochka17** [comment] 2024-03-14 01:01
We think that this bug might be related to #vip-vsp 
CC @quinthar

**Comment by marcaaron** [comment] 2024-03-14 03:23
cc @luacmartins

**Comment by narefyev91** [comment] 2024-03-14 07:36
will take a look

**Comment by ahmedGaber93** [comment] 2024-03-14 07:47
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
IOU - Add stop button is not aligned in the center

### What is the root cause of that problem?
react native paddingHorizontal not ovveride paddingLeft.
and we use in `getButtonStyleWithIcon` paddingLeft 12 and ovveride it with `innerStyles` have paddingHorizontal 40 here

https://github.com/Expensify/App/blob/b7a230ea75dbc4294f061c7627a24679e346641e/src/components/Button/index.tsx#L316

but react native not ovveride paddingLeft with paddingHorizontal
### What changes do you think we should make in order to solve the problem?
we can pass `styles.pl10, styles.pr10` instead of `ph10` [here](https://github.com/Expensify/App/blob/b7a230ea75dbc4294f061c7627a24679e346641e/src/components/Button/index.tsx#L316)

### What alternative solutions did you explore? (Optional)

**Comment by ahmedGaber93** [comment] 2024-03-14 07:49
@narefyev91 if you will fix this issue as regression and this will not go to external you can take alook in my proposal.

**Comment by luacmartins** [comment] 2024-03-14 18:14
This is fixed in staging
![Screenshot 2024-03-14 at 12 13 57 PM](https://github.com/Expensify/App/assets/22219519/e8271d65-a193-4fa8-b9c3-a1ab16d434a7)

**Closed by luacmartins** 2024-03-14 18:14 UTC
Labels: Reviewing, Engineering, Weekly
