### ISSUE TITLE
[HOLD for payment 2023-01-11] Web/Desktop - Emoji Picker - Space is added after the emoji in compose box

### ISSUE THREAD

**Issue by isagoico** [Expensify/App#13343] opened 2022-12-05 20:58 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. On Web/Desktop - Navigate to a conversation
2. Click on the emoji selector and click on any emoji

## Expected Result:
The emoji should be added in the compose box without any space after the emoji

## Actual Result:
Emoji is added with a space in the compose box. On desktop/web, no space should be added after adding a emoji in compose box.

## Workaround:
Can the user still use Expensify without this being fixed? Have you informed them of the workaround?

## Platform:

Where is this issue occurring?

- Web
- Desktop App

**Version Number:** v1.2.36-2

**Reproducible in staging?:** Yes 
**Reproducible in production?:** Yes

**Email or phone of affected tester (no customers):** N/A

**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Notes/Photos/Videos:** Any additional supporting documentation
![image](https://user-images.githubusercontent.com/44479856/205741347-0f1887d0-99e0-4f0c-803f-1015f76d5cd3.png)

**Expensify/Expensify Issue URL:** N/A

**Issue reported by:** Applause
**Slack conversation:** N/A

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by isagoico** [comment] 2022-12-05 20:59
Creating this issue coming from this comment - https://github.com/Expensify/Expensify/issues/245551#issuecomment-1337440659

**Comment by s77rt** [comment] 2022-12-05 23:28
Not a bug, this is actually intended.
https://github.com/Expensify/App/blob/2e69dac1a41bd35c8b68e0c08f1da462cd7cc49a/src/libs/EmojiUtils.js#L202-L206

**Comment by Puneet-here** [comment] 2022-12-06 09:16
### Proposal

If we don't want the space when choosing emoji from the picker we just have to make these changes -

At message composer
https://github.com/Expensify/App/blob/d7bc6501d6ee282de24850313c00fc7b41999fcf/src/pages/home/report/ReportActionCompose.js#L325
```diff
     addEmojiToTextBox(emoji) {
-        const emojiWithSpace = `${emoji} `;
         const newComment = this.comment.slice(0, this.state.selection.start)
-            + emojiWithSpace + this.comment.slice(this.state.selection.end, this.comment.length);
+            + emoji + this.comment.slice(this.state.selection.end, this.comment.length);
+        this.textInput.setNativeProps({
+            text: newComment,
+        });
         this.setState(prevState => ({
             selection: {
-                start: prevState.selection.start + emojiWithSpace.length,
-                end: prevState.selection.start + emojiWithSpace.length,
+                start: prevState.selection.start + emoji.length,
+                end: prevState.selection.start + emoji.length,
             },
```

At edit composer
https://github.com/Expensify/App/blob/d7bc6501d6ee282de24850313c00fc7b41999fcf/src/pages/home/report/ReportActionItemMessageEdit.js#L179
```diff
     addEmojiToTextBox(emoji) {
-        const emojiWithSpace = `${emoji} `;
         const newComment = this.state.draft.slice(0, this.state.selection.start)
-            + emojiWithSpace + this.state.draft.slice(this.state.selection.end, this.state.draft.length);
+            + emoji + this.state.draft.slice(this.state.selection.end, this.state.draft.length);
         this.setState(prevState => ({
             selection: {
-                start: prevState.selection.start + emojiWithSpace.length,
-                end: prevState.selection.start + emojiWithSpace.length,
+                start: prevState.selection.start + emoji.length,
+                end: prevState.selection.start + emoji.length,
             },
```

**Comment by allroundexperts** [comment] 2022-12-06 09:21
### Proposal
In order to add space just on mobile, we can make the following changes:

```diff
diff --git a/src/libs/EmojiUtils.js b/src/libs/EmojiUtils.js
index 617c624b2..bd2a76868 100644
--- a/src/libs/EmojiUtils.js
+++ b/src/libs/EmojiUtils.js
@@ -186,9 +186,10 @@ function addToFrequentlyUsedEmojis(frequentlyUsedEmojis, newEmoji) {
 /**
  * Replace any emoji name in a text with the emoji icon
  * @param {String} text
+ * @param {Boolean} addSpace
  * @returns {String}
  */
-function replaceEmojis(text) {
+function replaceEmojis(text, addSpace = true) {
     let newText = text;
     const emojiData = text.match(CONST.REGEX.EMOJI_NAME);
     if (!emojiData || emojiData.length === 0) {
@@ -201,7 +202,7 @@ function replaceEmojis(text) {
 
             // If this is the last emoji in the message and it's the end of the message so far,
             // add a space after it so the user can keep typing easily.
-            if (i === emojiData.length - 1 && text.endsWith(emojiData[i])) {
+            if (addSpace && i === emojiData.length - 1 && text.endsWith(emojiData[i])) {
                 emojiReplacement += ' ';
             }
             newText = newText.replace(emojiData[i], emojiReplacement);
diff --git a/src/pages/home/report/ReportActionCompose.js b/src/pages/home/report/ReportActionCompose.js
index 37e5602ca..d49b2464f 100644
--- a/src/pages/home/report/ReportActionCompose.js
+++ b/src/pages/home/report/ReportActionCompose.js
@@ -378,7 +378,7 @@ class ReportActionCompose extends React.Component {
      * @param {Boolean} shouldDebounceSaveComment
      */
     updateComment(comment, shouldDebounceSaveComment) {
-        const newComment = EmojiUtils.replaceEmojis(comment);
+        const newComment = EmojiUtils.replaceEmojis(comment, this.props.isSmallScreenWidth);
         this.setState((prevState) => {
             const newState = {
                 isCommentEmpty: !!newComment.match(/^(\s|`)*$/),

```

**Comment by s77rt** [comment] 2022-12-06 09:34
@dylanexpensify Why on mobile only?
Something does not make sense, IMO we should remove the extra space on all platform by removing those lines https://github.com/Expensify/App/blob/2e69dac1a41bd35c8b68e0c08f1da462cd7cc49a/src/libs/EmojiUtils.js#L202-L206

**Comment by dylanexpensify** [comment] 2022-12-06 11:45
to clarify, adding the space for mobile, but not desktop/web is an internal design decision we made @s77rt

**Comment by dylanexpensify** [comment] 2022-12-06 12:13
Hi @s77rt appreciate your concern, but we're going to move forward with the decision as it is.

**Comment by youssef-lr** [comment] 2022-12-08 16:52
@dylanexpensify @alexpensify I'll grab this.

**Comment by alexpensify** [comment] 2022-12-15 16:50
Thanks, @youssef-lr! Keep us posted if you need me to test when the fix is ready.

**Comment by alexpensify** [comment] 2022-12-21 20:01
@youssef-lr - I'm checking in to see how things are going here.

**Comment by alexpensify** [comment] 2022-12-23 18:10
No update yet, I'm going OOO until January 3 and will catch up then to identify if there is any movement here.

**Comment by JmillsExpensify** [comment] 2022-12-26 22:36
For anyone on this thread, this was the [Slack thread](https://expensify.slack.com/archives/C01GTK53T8Q/p1668009281985659?thread_ts=1667208968.300839&cid=C01GTK53T8Q) where we landed on this behavior. Please participate there if you disagree where we landed. This is also largely consistent with how Slack handles it.

**Comment by JmillsExpensify** [comment] 2022-12-26 22:38
In other news, given that this bug will hit the 30 day mark by next week, I'm going to take this over from @alexpensify so we can keep it moving this week and get ahead of this passing that mark. cc @youssef-lr

**Comment by JmillsExpensify** [comment] 2022-12-27 19:41
@youssef-lr I saw you weren't feeling well, and I believe that you're headed OOO soon. Will you be able to circle back on this one earlier next week? I'm mindful of staying ahead of the 30 day mark on this one. I'm happy to help find a volunteer if you're not around.

**Comment by youssef-lr** [comment] 2022-12-28 13:44
@JmillsExpensify I can take of this today!

**Comment by youssef-lr** [comment] 2022-12-28 17:16
@JmillsExpensify the solution here is a combination of both @Puneet-here's proposal and @allroundexperts's proposal. Which will enable us to only add emoji when we type `:emojiName:` on mobile.

I'm gonna raise a PR for this and I think compensation can be split here?

**Comment by JmillsExpensify** [comment] 2022-12-28 18:49
Ok great, a compensation split for the idea sounds fine, though I think the bonus would only apply to whoever raises the PR. For that reason, I still think it might be more equitable to take the issue internal, so this doesn't end up being a scenario where it's a competition of who replies first.

**Comment by Puneet-here** [comment] 2022-12-28 20:35
I am available now, let me know if I should raise the PR. 
@allroundexperts, I saw that you are also online, if you want you can grab this. 

cc @youssef-lr @JmillsExpensify

**Comment by JmillsExpensify** [comment] 2022-12-28 21:46
Go ahead and raise the PR in the interest of urgency. We can align on the bonus point I raised above later.

**Comment by Puneet-here** [comment] 2022-12-29 01:03
@youssef-lr, I thought of not going with @allroundexperts's original proposal because isSmallScreen will be true for desktop in decreased screen size and space will be added after the emoji, so I used  isKeyboardShown instead but `isKeyboardShown` is not working at mWeb. Can you please double check it, because I think it should work. Here's the [PR](https://github.com/Expensify/App/pull/13875)

**Comment by Puneet-here** [comment] 2022-12-29 18:51
NVM the above comment, actually the `Keyboard` listener only work for native. We will need to use the isSmallScreenWidth.

**Comment by youssef-lr** [comment] 2022-12-30 11:36
Left a few comment in the PR.

**Comment by JmillsExpensify** [comment] 2023-01-11 05:23
Huh, it looks like this issue was never updated automatically and the regression period has already past. Let's get this one squared away. Here's how I see this one shaking out. 

 - Issue reporter: N/A
 - Contributor: @Puneet-here $1,500 (includes 50% bonus for merging PR quickly)
 - Contributor: @allroundexperts $1,000 (for sharing an idea we ended up using)
 - Contributor+: N/A

**Comment by JmillsExpensify** [comment] 2023-01-11 05:27
Well that didn't work. I'll just create the Upwork job manually. Here it is: https://www.upwork.com/jobs/~01da97f6e1c8796152. Can both of you apply so we can get this paid out tomorrow?

**Comment by allroundexperts** [comment] 2023-01-11 10:40
@JmillsExpensify Applied.

**Comment by Puneet-here** [comment] 2023-01-11 13:00
Applied, thanks! @JmillsExpensify

**Comment by shinydev1108** [comment] 2023-01-11 13:09
Hello. Thanks for your job posting.

I am a full stack developer who has much experience with web development related emoji.

Please take a look at https://nolanlawson.github.io/emoji-picker-element. I think this project matches with your project very well.

I am ready your job. Hope my experience will be helpful for your project.
Please let me know if you have any questions.

Look forward to discussing more detail about this opportunity.
Thanks for your time and consideration.
(My skype id is live:.cid.a522c4881a36622d)

**Comment by JmillsExpensify** [comment] 2023-01-11 17:30
@allroundexperts @Puneet-here I've extended offers to both of you.

**Comment by JmillsExpensify** [comment] 2023-01-11 17:30
Also for clarity, this was technically a new feature in the name of consistency, so no regressions.

**Comment by allroundexperts** [comment] 2023-01-11 17:43
Accepted.

**Comment by shinydev1108** [comment] 2023-01-11 19:18
So I want to know your skype id or mail address. Can you send me them to shinydev1108@gmail.com?

**Comment by JmillsExpensify** [comment] 2023-01-11 20:17
Just waiting on @Puneet-here at this point and then I'll close out the issue.

**Comment by Puneet-here** [comment] 2023-01-12 03:18
Sorry for the delay. Accepted now!

**Comment by JmillsExpensify** [comment] 2023-01-12 04:31
Thanks @Puneet-here! You're all set now.

**Closed by JmillsExpensify** 2023-01-12 04:31 UTC
Labels: Reviewing, Engineering, Daily

**Comment by thesahindia** [comment] 2023-01-18 12:52
Hey @JmillsExpensify, sorry for the late comment but C+ compensation is due. ([Reviewed PR](https://github.com/Expensify/App/pull/13875))

**Comment by JmillsExpensify** [comment] 2023-01-18 16:54
Oh, thanks! We need a better process here, probably something you should bring up in C+ in Slack. One idea would be that C+ is responsible for commenting in the issue linked to the PR to ensure that they get assigned and paid. In any case, let's improve our process here, as I notice this keeps happening.

**Comment by JmillsExpensify** [comment] 2023-01-18 16:55
In any case, I invited you to the job as it's still open. Can you please accept? Appreciated!

**Comment by thesahindia** [comment] 2023-01-18 20:12
Applied, thanks @JmillsExpensify

**Comment by JmillsExpensify** [comment] 2023-01-18 20:31
Offer sent.

**Comment by JmillsExpensify** [comment] 2023-01-18 20:42
@thesahindia Before I issue payment, I wanted to clarify the payment. You were assigned as C+ to review this PR, though you didn't review any proposals in this issue. As a result, I think the most fair is to treat this like any other issue where you're just assigned to review a PR. That's $1,000. Does that make sense and do you agree?

**Comment by thesahindia** [comment] 2023-01-18 20:43
Yeah, it makes sense to me.
