### ISSUE TITLE
Track Expenses-The "To" field is not auto-filled with a new workspace

### ISSUE THREAD

**Issue by IuliiaHerets** [Expensify/App#53715] opened 2024-12-06 17:14 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 9.0.72-0
**Reproducible in staging?:** Yes
**Reproducible in production?:** Yes
**If this was caught on HybridApp, is this reproducible on New Expensify Standalone?:** N/A
**If this was caught during regression testing, add the test name, ID and link from TestRail:** https://expensify.testrail.io/index.php?/cases/view/2990404
**Email or phone of affected tester (no customers):** N/A
**Issue reported by:** Applause Internal Team

## Action Performed:
Steps:
1. Use a new expensifail account
2. Submit a track expense in the self DM
3. On the actionable whisper options of a track expense, click on "Share it with your accountant"
4. Create a new workspace
5. Go back to self DM and click on "Share it with your accountant"

## Expected Result:
The "To" field is auto-filled with a new workspace.

## Actual Result:
The "To" field is not auto-filled with a new workspace. Instead, a RHP is displayed to find a workspace when the user has no one.

## Workaround:
Unknown

## Platforms:
- [x] Android: Standalone
- [x] Android: HybridApp
- [x] Android: mWeb Chrome
- [ ] iOS: Standalone
- [ ] iOS: HybridApp
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

https://github.com/user-attachments/assets/09c92586-3f88-423b-821f-73e02073b58f

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by FitseTLT** [comment] 2024-12-06 17:19
From the OP I don't see any problem because the user has deleted the workspace immediately after they created it @IuliiaHerets please take a 👀 again

**Comment by Shahidullah-Muffakir** [comment] 2024-12-06 18:45
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
When user selects Share it with your accountant, the To field is not filled(Workspace is not selected)
### What is the root cause of that problem?
1. if user has a workspace then we are not creating a draft workspace
https://github.com/Expensify/App/blob/5f143b53347336728f22b1f860406a2a3bc332dc/src/libs/ReportUtils.ts#L8236

2. the issue is that when user deletes a workspace, it is still counted here 
https://github.com/Expensify/App/blob/5f143b53347336728f22b1f860406a2a3bc332dc/src/libs/ReportUtils.ts#L8215-L8217
the main issue is that we should filter out the archived workspace here
### What changes do you think we should make in order to solve the problem?
modify this: https://github.com/Expensify/App/blob/5f143b53347336728f22b1f860406a2a3bc332dc/src/libs/ReportUtils.ts#L8215-L8217
to remove the archived workspaces by using  `  !!PolicyUtils.getPolicyRole(policy, currentUserLogin) &&`
as:
```
  const filteredPolicies = Object.values(allPolicies ?? {}).filter(
        (policy) =>
            policy &&
            !!PolicyUtils.getPolicyRole(policy, currentUserLogin) &&
            policy.type !== CONST.POLICY.TYPE.PERSONAL &&
            policy.pendingAction !== CONST.RED_BRICK_ROAD_PENDING_ACTION.DELETE,
    );
```

**Comment by Tony-MK** [comment] 2024-12-07 22:17
This issue has the same RCA as https://github.com/Expensify/App/issues/53659 and should be solved.

**Comment by jjcoffee** [comment] 2024-12-09 11:24
This will be fixed in https://github.com/Expensify/App/issues/53659.

**Comment by stephanieelliott** [comment] 2024-12-11 00:11
Closing based on [this discussion](https://expensify.slack.com/archives/C01SKUP7QR0/p1729782920352609?thread_ts=1729721728.427419&cid=C01SKUP7QR0) -- we're not prioritizing non-onboarding Track bugs. But it sounds like this will be resolved soon anyway as part of https://github.com/Expensify/App/issues/53659

**Closed by stephanieelliott** 2024-12-11 00:11 UTC
Labels: Daily, Overdue, Bug
