### ISSUE TITLE
[$500] Unchecked users persist as checked when inviting others

### ISSUE THREAD

**Issue by m-natarajan** [Expensify/App#36350] opened 2024-02-12 16:44 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** v1.4.40-0
**Reproducible in staging?:** yes
**Reproducible in production?:** yes
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** applause internal team
**Slack conversation:**

## Action Performed:
1. Go to settings -> workspaces -> select any workspace -> members -> invite
2. Search users and select them
3. Click on Next
4. Then click back button and remove search text and uncheck user
5. Search same users

## Expected Result:
Unchecked users should not persist as checked when inviting users

## Actual Result:
Unchecked users persist as checked when inviting others

## Workaround:
unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [x] Android: mWeb Chrome
- [x] iOS: Native
- [x] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

https://github.com/Expensify/App/assets/38435837/8d21323e-ed54-45d1-a172-ef142bcc5676

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01023d96d9e3244fc5</li>
        <li>Upwork Job ID: 1757083252891254784</li>
        <li>Last Price Increase: 2024-03-11</li>
    </ul>
</details>

**Comment by s101d1** [comment] 2024-02-12 19:02
## Proposal

### Please re-state the problem that we are trying to solve in this issue.

Unchecked users persist as checked when inviting others.

### What is the root cause of that problem?

In `WorkspaceInvitePage` component, the selected/checked members data is always loaded from the `invitedEmailsToAccountIDsDraft` Onyx data in the `useEffect` hook. Initially, the `invitedEmailsToAccountIDsDraft` data is empty, and then when user clicked the Next button, the `invitedEmailsToAccountIDsDraft` will be set to the current selected/checked members data. The `invitedEmailsToAccountIDsDraft` data is persistent, so when user clicked Back button from the next screen, the `invitedEmailsToAccountIDsDraft` data will still refer to the current selected members data.

Now the main issue is the `toggleOption` function (which is executed when user toggled the checkbox) doesn't synchronize or update the `invitedEmailsToAccountIDsDraft` data from the current selected/unselected members state.

https://github.com/Expensify/App/blob/1.4.40-0/src/pages/workspace/WorkspaceInvitePage.tsx#L223-L236

That's why when user unchecked a member, that same member data in `invitedEmailsToAccountIDsDraft` is still in checked state, and thus the previosuly unchecked member would get re-checked again when the react component gets re-rendered, because the `invitedEmailsToAccountIDsDraft` data will overwrite the `selectedOptions` state data (which reflects the current selected members state) in the `useEffect` hook.

### What changes do you think we should make in order to solve the problem?

The `toggleOption` function should also synchronize the `invitedEmailsToAccountIDsDraft` data from the current selected members data.

### What alternative solutions did you explore? (Optional)
N/A

**Comment by s101d1** [comment] 2024-02-12 19:12
Contributor details
Your Expensify account email: zepbrondy@protonmail.com
Upwork Profile Link: https://www.upwork.com/freelancers/~01183037294ebd302d

**Comment by kmbcook** [comment] 2024-02-13 17:27
## Proposal
### Please re-state the problem that we are trying to solve in this issue.
Unchecked users persist as checked when inviting others.

### What is the root cause of that problem?
See the invite members page: pages/workspace/WorkspaceInvitePage.tsx. Currently selected members are stored in state `selectedOptions`. Search text is stored in `searchTerm`.

When user changes search text, `invitedEmailsToAccountIDsDraft` is used to set selected members. 

### What changes do you think we should make in order to solve the problem?
It is not necessary to set selected members when the user changes search text. Selected members are already set in `toggleOption`, and that is sufficient.

`invitedEmailsToAccountIDsDraft` is useful for transferring information from the invite new members page to the invite message page, but that information is no longer needed after the user presses the back button on the invite message page. The invite members page does not need to connect to `invitedEmailsToAccountIDsDraft`.

**Comment by bernhardoj** [comment] 2024-02-13 19:08
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
The unchecked user is re-selected when searching.

### What is the root cause of that problem?
When we select users and press next, they are saved to members draft onyx.
https://github.com/Expensify/App/blob/f438cb7901c4405e7ec2bbb22aaa904bb5b8fb66/src/pages/workspace/WorkspaceInvitePage.tsx#L262

We have a `useEffect` that will be triggered every time the search is changed and it will re-add the saved selected members from the onyx to the selected member state.
https://github.com/Expensify/App/blob/f438cb7901c4405e7ec2bbb22aaa904bb5b8fb66/src/pages/workspace/WorkspaceInvitePage.tsx#L123-L128
https://github.com/Expensify/App/blob/f438cb7901c4405e7ec2bbb22aaa904bb5b8fb66/src/pages/workspace/WorkspaceInvitePage.tsx#L162

This was added in this PR https://github.com/Expensify/App/pull/34028 where the intention is to re-add it when the component is mounted/initialized.

### What changes do you think we should make in order to solve the problem?

We should stick to the initial intention which is to add the saved members from Onyx to the state only when the component is initialized, either in `useState` initial value or in a `useEffect` with empty deps.

```
const [selectedOptions, setSelectedOptions] = useState<MemberForList[]>(() => Object.values(invitedEmailsToAccountIDsDraft ?? {})
    .filter((accountID) => personalDetailsProp?.[accountID])
    .map((accountID) => ({...OptionsListUtils.formatMemberForList(personalDetailsProp[accountID]), isSelected: true}))
);
```

**Comment by JmillsExpensify** [comment] 2024-02-21 01:54
Are proposals still in review?

**Comment by situchan** [comment] 2024-02-23 20:42
yes, I will provide update on Monday

**Comment by situchan** [comment] 2024-02-28 13:03
All proposed solutions are vague or incorrect. Still waiting for better proposals

**Comment by kmbcook** [comment] 2024-02-29 21:28
## Proposal
### Please re-state the problem that we are trying to solve in this issue.
Unchecked users persist as checked when inviting others.

### What is the root cause of that problem?
See the invite members page: pages/workspace/WorkspaceInvitePage.tsx. Currently selected members are stored in state `selectedOptions`. Search text is stored in `searchTerm`.

When user changes search text, `invitedEmailsToAccountIDsDraft` is used to set selected members. 

### What changes do you think we should make in order to solve the problem?
It is not necessary to set selected members when the user changes search text. Selected members are already set in `toggleOption`, and that is sufficient.

`invitedEmailsToAccountIDsDraft` is useful for transferring information from the invite new members page to the invite message page, but that information is no longer needed after the user presses the back button on the invite message page. The invite members page does not need to connect to `invitedEmailsToAccountIDsDraft`.

Not setting selected members when the user changes search text solves this problem. This can be done by removing the call to setSelectedOptions from the effect which is used when searchTerm changes. After that call is removed there will be other code which is no longer used, which can also be removed.

**Comment by s101d1** [comment] 2024-03-01 06:21
## Proposal
[Updated](https://github.com/Expensify/App/issues/36350#issuecomment-1939356643)

**Comment by situchan** [comment] 2024-03-04 21:00
Still discussing / awaiting proposals

**Comment by situchan** [comment] 2024-03-07 23:50
Same

**Comment by JmillsExpensify** [comment] 2024-03-13 04:37
Still working through proposals

**Comment by situchan** [comment] 2024-03-15 21:00
Not overdue

**Comment by situchan** [comment] 2024-03-18 21:19
Not overdue

**Comment by situchan** [comment] 2024-03-22 13:30
@bernhardoj's [proposal](https://github.com/Expensify/App/issues/36350#issuecomment-1942208390) looks good to me.
All other proposals cause regressions.
🎀 👀 🎀 C+ reviewed

**Comment by bernhardoj** [comment] 2024-03-23 13:58
PR is ready

cc: @situchan

**Comment by situchan** [comment] 2024-05-17 00:45
Automation seems broken. Payment is remaining

**Comment by JmillsExpensify** [comment] 2024-05-19 17:51
Payment summary: 

 - Contributor: @bernhardoj $500 
 - Contributor+: @situchan $500

@situchan can you please complete the BZ checklist?

**Comment by JmillsExpensify** [comment] 2024-05-19 17:54
Upwork offers sent.

**Comment by JmillsExpensify** [comment] 2024-05-20 15:15
Contributor paid out. @situchan quick reminder on the BZ checklist and then I'll make sure you're Upwork contract is paid.

**Comment by JmillsExpensify** [comment] 2024-05-20 17:10
Test request added, so I'm closing this out.

**Closed by JmillsExpensify** 2024-05-20 17:10 UTC
Labels: Reviewing, Engineering, Monthly, Internal, Bug
