### ISSUE TITLE
mWeb - Group chat - After removing member, admin leaving group chat app crashes

### ISSUE THREAD

**Issue by IuliiaHerets** [Expensify/App#48072] opened 2024-08-27 10:53 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** v9.0.25-1
**Reproducible in staging?:**  Y 
**Reproducible in production?:** N 
**If this was caught during regression testing, add the test name, ID and link from TestRail:** https://expensify.testrail.io/index.php?/tests/view/4895730
**Issue reported by:** Applause Internal Team 

## Action Performed:
1. Go to https://staging.new.expensify.com/home
2. Tap fab -- start chat
3. Select a user and create a group
4. Tap header -- members
5. Long press the members and select "remove" member
6. Navigate back to "details" page and tap "Leave"

## Expected Result:
After removing member, admin leaving group chat app must not crash.

## Actual Result:
After removing member, admin leaving group chat app crashes.

## Workaround:
Unknown

## Platforms:

- [ ] Android: Native
- [x] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [ ] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

[2708_2.txt](https://github.com/user-attachments/files/16761010/2708_2.txt)

https://github.com/user-attachments/assets/834d34ac-dc42-4084-bda1-4a0a65c1a6d1

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by bernhardoj** [comment] 2024-08-27 12:08
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
App crashes when leaving a group chat as the last member.

### What is the root cause of that problem?
The error comes when we try to extract the emoji from the draft message here because the `draftMessage` is an empty object instead of a string, so `{}.match` will crash.
https://github.com/Expensify/App/blob/9ddca5c4ac8168ad36da570192a6e4ef10820e67/src/pages/home/report/ReportActionItemMessageEdit.tsx#L103-L106
https://github.com/Expensify/App/blob/9ddca5c4ac8168ad36da570192a6e4ef10820e67/src/libs/EmojiUtils.ts#L282-L288

The reason it's an empty object is that after we leave the group, the report is deleted, and `report.reportID` becomes an empty string because we default it to an empty string,
https://github.com/Expensify/App/blob/9ddca5c4ac8168ad36da570192a6e4ef10820e67/src/pages/home/ReportScreen.tsx#L169-L172

so, when we try to fetch the draft, it fetches the onyx collection (reportActionsDrafts_) which is an empty object because we don't have any draft.
https://github.com/Expensify/App/blob/9ddca5c4ac8168ad36da570192a6e4ef10820e67/src/pages/home/report/ReportActionItem.tsx#L181-L187

### What changes do you think we should make in order to solve the problem?

Use `||` instead of `??` so it will fallback to -1 if it's an empty string.
https://github.com/Expensify/App/blob/9ddca5c4ac8168ad36da570192a6e4ef10820e67/src/pages/home/report/ReportActionItem.tsx#L181-L182

OR

Don't default to an empty string
https://github.com/Expensify/App/blob/9ddca5c4ac8168ad36da570192a6e4ef10820e67/src/pages/home/ReportScreen.tsx#L169-L172

**Comment by cristipaval** [comment] 2024-08-27 14:15
@bernhardoj could you also find the offending PR?

**Comment by bernhardoj** [comment] 2024-08-27 14:40
It happens after https://github.com/Expensify/App/pull/47866

**Comment by bernhardoj** [comment] 2024-08-27 14:40
PR is ready!

**Comment by puneetlath** [comment] 2024-08-27 17:13
@cristipaval confirmed it's fixed on staging. Demoting.

**Comment by puneetlath** [comment] 2024-09-19 21:20
Does anyone need to be paid out here?

**Comment by bernhardoj** [comment] 2024-09-20 04:08
Yes, I think it's only me

**Comment by puneetlath** [comment] 2024-09-21 22:55
Is it this PR? https://github.com/Expensify/App/pull/48096

Looks like @hungvu193 reviewed that?

**Comment by hungvu193** [comment] 2024-09-21 23:25
> Is it this PR? https://github.com/Expensify/App/pull/48096
> 
> 
> 
> Looks like @hungvu193 reviewed that? 

Ah yes but it's regression so no payment needed for me

**Comment by puneetlath** [comment] 2024-09-22 19:23
Ok thanks for the clarifications. 

Payment summary: 
- $250 - C - @bernhardoj - to be paid via NewDot

**Closed by puneetlath** 2024-09-22 19:23 UTC
Labels: Reviewing, Engineering, Monthly, Bug

**Comment by bernhardoj** [comment] 2024-09-23 04:25
Requested in ND

**Comment by JmillsExpensify** [comment] 2024-09-23 07:11
$250 approved for @bernhardoj
