### ISSUE TITLE
[$500] Request Money - The previous button is missing and the Next button is not functioning properly for pictures added in IOU when requesting money in scan mode

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#28718] opened 2023-10-03 13:07 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Click on FAB and select Request Money.
2. Choose scan mode and add recipient bill photo.
3. Add email or workspace and request money.
4. Double-click twice to go to IOU and add a picture.
5. Observe that there are two unexpected behaviors: the first one is the absence of the previous button, and the Next button is not working for the picture added in IOU.

## Expected Result:
 If two photos appear in IOU, the first image should have a Next button, and the second image should have a Previous button. If this is by design, the Next button in the second image should perform some action.

## Actual Result:
There is no previous button, and the Next button is not functioning correctly for pictures added in IOU.

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android / native
- [x] Android / Chrome
- [x] iOS / native
- [x] iOS / Safari
- [x] MacOS / Chrome / Safari
- [x] MacOS / Desktop

**Version Number:** v1.3.75-8
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/93399543/f839e51e-d1bd-4df1-a2ee-6511765a5286

https://github.com/Expensify/App/assets/93399543/f67691f7-c296-4bdb-bb8f-260db4900e64

https://github.com/Expensify/App/assets/93399543/a272a884-4c47-476c-9aec-cca9709d53c3

https://github.com/Expensify/App/assets/93399543/09b7f36e-be50-40a1-ba0d-dafe0b75d9f6

https://github.com/Expensify/App/assets/93399543/8f38bffd-fa25-4f1d-83bf-11953a5bbdc9

https://github.com/Expensify/App/assets/93399543/fc177cc6-e40d-4387-9c99-a5ed57718798

https://github.com/Expensify/App/assets/93399543/d8e478e5-5cbd-4b0e-b1a2-ce3595bacd88

**Expensify/Expensify Issue URL:**
**Issue reported by:** @tewodrosGirmaA
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1696225666195509

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~016e647a00541e7e5d</li>
        <li>Upwork Job ID: 1709193472808792064</li>
        <li>Last Price Increase: 2023-11-15</li>
    </ul>
</details>

**Comment by ahmedGaber93** [comment] 2023-10-03 13:07
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
When add attachment in receipt and open it:
 - The opened attachment is always the receipt image.
 - The AttachmentCarousel previous button is missing. 
 - The AttachmentCarousel next button is appeared not functioning while it is the last image.
 
### What is the root cause of that problem?
When we fix issue https://github.com/Expensify/App/issues/26828 in PR https://github.com/Expensify/App/pull/27426 we use a new method to get the index of the preview image, and it works fine for the case that it was designed for it.
https://github.com/Expensify/App/blob/09e3d0d44fa8b21134386d52e1afa33ea83b0428/src/components/Attachments/AttachmentCarousel/index.js#L41-L51
https://github.com/Expensify/App/blob/09e3d0d44fa8b21134386d52e1afa33ea83b0428/src/components/Attachments/AttachmentCarousel/index.js#L56-L59

But when we add attachment in the receipt report as a normal message.
The `compareImage` always return the receipt attachment, because the first item in `attachments` array will return true in `if (attachment.isReceipt)` and  `initialPage` will always be 0 which make the AttachmentCarousel next and previous buttons not work correctly
### What changes do you think we should make in order to solve the problem?

1. revert this PR https://github.com/Expensify/App/pull/27426 will fix the current issue.
2. and for https://github.com/Expensify/App/issues/26828 we can use this to prevent dismiss the modal when file is locally 
```javascript
const isLocalFile = source.startsWith('blob:') || source.startsWith('file:');
// Dismiss the modal when deleting an attachment during its display in preview.
if (initialPage === -1 && _.find(attachments, (a) => a.source === source)) {
    if (!isLocalFile) Navigation.dismissModal();
} else {
   ...
}
```

### What alternative solutions did you explore? (Optional)
N/A

**Comment by tewodrosGirmaA** [comment] 2023-10-03 13:44
I don't think so , it have different root couses

**Comment by tewodrosGirmaA** [comment] 2023-10-03 13:44
I don't think so , it have different root couses

**Comment by laurenreidexpensify** [comment] 2023-10-05 10:20
@robertKozik do you think this one is a dupe of https://github.com/Expensify/App/issues/27824?

**Comment by robertKozik** [comment] 2023-10-05 10:40
@laurenreidexpensify, I'm not entirely certain if this is a duplicate or not. However, I've checked the PR for #27824 and it appears to address this issue as well. Since that PR is already in the review process, my suggestion would be to put our issue on hold until it gets merged. Afterward, we can retest to see if the problem persists, and then take appropriate action based on the outcome.

**Comment by laurenreidexpensify** [comment] 2023-10-09 09:31
Holding on https://github.com/Expensify/App/issues/27824

**Comment by laurenreidexpensify** [comment] 2023-10-18 11:41
Holding on https://github.com/Expensify/App/issues/27824

**Comment by laurenreidexpensify** [comment] 2023-10-31 11:27
Holding on https://github.com/Expensify/App/issues/27824

**Comment by laurenreidexpensify** [comment] 2023-11-08 12:20
Holding on https://github.com/Expensify/App/issues/27824

**Comment by laurenreidexpensify** [comment] 2023-11-15 11:12
@kbecciv @robertKozik can we test to see if this is still reproducible now that https://github.com/Expensify/App/issues/27824 has been deployed to prod? Thanks

**Comment by kbecciv** [comment] 2023-11-18 16:02
Unable to reproduce it

https://github.com/Expensify/App/assets/93399543/977a2165-ed31-4ebf-bf54-bd90c21b2701

**Closed** 2023-11-20 10:36 UTC
Labels: External, Daily, Help Wanted, Overdue, Bug
