### ISSUE TITLE
[HOLD for payment 2023-09-18] [$500]  Deeplinks - Not found page for concierge chat link after sign in

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#26314] opened 2023-08-30 18:16 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:

1. Go to staging.new.expensify.com and sign out if needed
2. Go to staging.new.expensify.com/concierge
3. Sign in

## Expected Result:
The concierge chat is displayed

## Actual Result:
A not found page is displayed

## Workaround:
Go home and re-open the concierge chat

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [x] Android / Chrome
- [ ] iOS / native
- [x] iOS / Safari
- [x] MacOS / Chrome / Safari
- [ ] MacOS / Desktop
 
**Version Number:** 1.3.59

**Reproducible in staging?:** Yes

**Reproducible in production?:** Yes

**If this was caught during regression testing, add the test name, ID and link from TestRail:**

**Email or phone of affected tester (no customers):**

**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/78819774/0648b177-71e3-4309-8a42-74b5757be7ad

<img width="408" alt="Bug6182942_screenshot" src="https://github.com/Expensify/App/assets/78819774/b2cdf6b5-0826-4c7c-99ac-b277c6b6f348">

**Expensify/Expensify Issue URL:**

**Issue reported by:** Applause - Internal Team

**Slack conversation:**

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01732ad142820a35d9</li>
        <li>Upwork Job ID: 1697400392903643136</li>
        <li>Last Price Increase: 2023-09-01</li>
<li>Automatic offers: </li>
<ul>
<li>fedirjh | Reviewer | 26535484</li>
<li>Talha345 | Contributor | 26535485</li>
</ul></li>
    </ul>
</details>

**Comment by neil-marcellini** [comment] 2023-08-30 18:47
This is reproducible on prod with the following steps, so it's not a deploy blocker. I think it's also reproducible on all web platforms.

1. Go to new.expensify.com and sign out if needed
2. Go to new.expensify.com/concierge
3. Sign in

Actual result: A not found page is displayed
Expected result: The concierge chat is displayed

**Comment by neil-marcellini** [comment] 2023-08-30 18:49
@lanitochka17 please try to use the most simple reproduction steps possible, check if it affects all platforms, and check if it is reproducible on production before creating a deploy blocker.

**Comment by neil-marcellini** [comment] 2023-08-30 18:52
@joekaufmanexpensify I bet this can be fixed externally

**Comment by neil-marcellini** [comment] 2023-08-30 18:53
Un-assigning since engineering is no longer needed until a C+ approves a proposal.

**Comment by Talha345** [comment] 2023-08-30 20:48
## Proposal

### Please re-state the problem that we are trying to solve in this issue.

Visiting the concierge using deep link when logged out shows the not found page upon login.

### What is the root cause of that problem?

The RC of this problem is the following if clause in the [navigateToConciergeChat](https://github.com/Expensify/App/blob/main/src/libs/actions/Report.js#L1295-L1314) method which does not make any sense.

```
// In order not to delay the report life cycle, we first navigate to the unknown report
if (!Navigation.getTopmostReportId()) {
            Navigation.navigate(ROUTES.REPORT);
}
```

The if clause means that if the `reportID` returned by `getTopmostReportId` is `undefined`, it navigates to `ROUTES.REPORT` which is equals to `'r'` and therefore we get the not found page.

I did some digging to find out why this if clause was actually introduced, and found that it was introduced in https://github.com/Expensify/App/pull/19294. Also it is worth noting that the comment on top of the if clause does not make any sense and an engineer also commented the same thing [here](https://github.com/Expensify/App/pull/19294/files#r1264203727) on the PR.

It seems to me that while testing the PR, the reviewer found 2 regressions which he mentioned here https://github.com/Expensify/App/pull/19294#issuecomment-1559320226 .The PR author then provided a solution to the regressions here https://github.com/Expensify/App/pull/19294#issuecomment-1559625131 by adding this if clause as a workaround to just prevent the delay being caused which resulted in a full screen loader instead of the skeleton view loaders at that time.The workaround sucks IMO because it does not make any sense logically and just causes an extra redirect to first the undefined report and then the original report.

### What changes do you think we should make in order to solve the problem?

We should just remove the if clause mentioned above to fix this issue.I have tested this and it works like a charm for an existing account as well as new account and does not cause any regressions that were mentioned above as in the original PR.



### What alternative solutions did you explore? (Optional)

N/A

**Comment by joekaufmanexpensify** [comment] 2023-09-01 00:05
Reproduced.

**Comment by joekaufmanexpensify** [comment] 2023-09-01 19:57
Pending review of proposals

**Comment by joekaufmanexpensify** [comment] 2023-09-04 17:47
@fedirjh could you take a look at the proposal here when you have a sec? TY!

**Comment by Talha345** [comment] 2023-09-06 08:40
Hi @deetergp, any update on task assignment?

**Comment by joekaufmanexpensify** [comment] 2023-09-06 13:41
Pending internal review

**Comment by deetergp** [comment] 2023-09-06 21:46
Just reproduced this locally then tested out @Talha345's suggestion and it does indeed work like a champ. Let's go with it 🚀

**Comment by Talha345** [comment] 2023-09-06 22:04
> Just reproduced this locally then tested out @Talha345's suggestion and it does indeed work like a champ. Let's go with it 🚀

@deetergp Can you please assign the task to me?

**Comment by Talha345** [comment] 2023-09-07 00:06
@fedirjh @deetergp @joekaufmanexpensify PR is ready for review!

**Comment by joekaufmanexpensify** [comment] 2023-09-11 13:38
@fedirjh mind handling the BZ checklist this week so we can prep to issue payment?

**Comment by joekaufmanexpensify** [comment] 2023-09-17 08:35
Great, thanks! I'll finish up the checklist asap.

**Comment by Talha345** [comment] 2023-09-18 18:18
@joekaufmanexpensify Payment is due!

**Comment by joekaufmanexpensify** [comment] 2023-09-19 03:11
This bug is actually already covered by the regression test listed above, so no action is needed for the test here. I expect that's how we caught this in the first place.

**Comment by joekaufmanexpensify** [comment] 2023-09-19 03:13
All set to issue payment here. This one qualifies for a speed bonus, so we need to issue the following payments:

- @Talha345 - $750 ($500 for PR and $250 speed bonus). Paid via Upwork. 
- @fedirjh - $750 ($500 for C+ and $250 speed bonus). Paid via Upwork.

**Comment by joekaufmanexpensify** [comment] 2023-09-19 03:16
@Talha345 $750 sent and contract ended!

**Comment by joekaufmanexpensify** [comment] 2023-09-19 03:17
@fedirjh $750 sent and contract ended!

**Comment by joekaufmanexpensify** [comment] 2023-09-19 03:17
Upwork job closed.

**Comment by joekaufmanexpensify** [comment] 2023-09-19 03:18
Bug is fixed, BZ checklist is complete, and all payment issued. Closing as this is all set, thanks everyone!

**Closed by joekaufmanexpensify** 2023-09-19 03:18 UTC
Labels: External, Daily, Awaiting Payment, Bug
