### ISSUE TITLE
[$1000] Web – The message remains permanently highlighted when the checkbox is unchecked.

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#22159] opened 2023-07-04 10:29 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Open any chat containing assigned task messages.
2. Check the checkbox and then uncheck it.
3. Notice that the unchecked message remains highlighted permanently until the cursor is moved above that specific message.

## Expected Result:
Upon unchecking the checkbox, the message should not remain highlighted permanently.

## Actual Result:
Upon unchecking the checkbox, the message remains highlighted permanently.

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [x] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 1.3.35-5
**Reproducible in staging?:** n.a
**Reproducible in production?:** n/a
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/93399543/b3605c7d-ffc1-48f3-8e6a-5db68c04f42d

**Expensify/Expensify Issue URL:**
**Issue reported by:** @usmantariq96
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1688288921624429

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01944afe0484b35912</li>
        <li>Upwork Job ID: 1676494645159591936</li>
        <li>Last Price Increase: 2023-07-26</li>
    </ul>
</details>

**Comment by abrehamgezahegn** [comment] 2023-07-05 14:32
Hello! Is this reproducible on production?

**Comment by ygshbht** [comment] 2023-07-05 14:45
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
The problem we're trying to solve is an issue where a message in the chat remains permanently highlighted when its checkbox is unchecked. This behavior persists until the cursor hovers over that specific message again, causing an inconsistent and potentially confusing user experience.

### What is the root cause of that problem?
The root cause of this problem lies in the way the 'Hoverable' component handles mouse events. When the checkbox is unchecked, the component rerenders. If the mouse is moved out of the component during this rerendering, the 'mouseleave' event might not get fired. This prevents the 'Hoverable' component's state from being updated, which in turn causes the message to remain highlighted.

### What changes do you think we should make in order to solve the problem?
In order to solve this issue, we could reconsider the approach of handling the mouse events in the 'Hoverable' component. Instead of attaching the event to the child component, we can attach it to the document itself. Using the 'mousemove' event, we can check if the mouse is inside the component. This can be done by utilizing the 'getBoundingClientRect' method on the component element. Based on the result, we can then set the state of the 'Hoverable' component, ensuring that the highlighting is removed when the checkbox is unchecked, irrespective of whether the mouse is moved out during the rerender.

https://github.com/Expensify/App/assets/65986357/2c7d09e7-3b49-4abd-98cc-0a19c90789ba

**Comment by joh42** [comment] 2023-07-06 17:17
I was thinking that we'd have add a check to `Hoverable` when the component mounts to see if the cursor is above said component. After looking around a bit I saw that @s-alves10 had come to a similar conclusion for issue [16923](https://github.com/Expensify/App/issues/16923), specifically in this [proposal](https://github.com/Expensify/App/issues/16923#issuecomment-1608049316). As such it seems like this issue is a duplicate, as both issues involve problems with `Hoverable` not noticing that a component is not actually hovered, and if implemented the proposal by @s-alves10 will likely solve this issue as well

**Comment by ygshbht** [comment] 2023-07-06 17:32
@joh42 I appreciate your perspective and the reference to the similar issue that's being addressed. Indeed, it appears that the root causes might be interconnected. However, I'd like to point out that a solution based on componentDidUpdate in the parent (Hoverable) might not be triggered when only the child component updates. This is due to the lifecycle of React components where a child's update doesn't necessarily cause the parent's componentDidUpdate to fire.

On the other hand, the solution I proposed does address this particular issue effectively. I've attached a video demonstrating this. By addressing the root cause directly, it ensures that we solve the issue at hand, and don't rely on a potential overlap with another issue.

**Comment by ygshbht** [comment] 2023-07-06 17:39
@s-alves10 's solution might work for #16923 but i'm afraid it won't for this specific issue

**Comment by abdulrahuman5196** [comment] 2023-07-08 10:09
I am unable to reproduce this even if i had multiple tasks @laurenreidexpensify

**Comment by ygshbht** [comment] 2023-07-08 10:14
@abdulrahuman5196 Try to move out your mouse fast after unchecking

**Comment by joh42** [comment] 2023-07-10 09:30
I was able to reproduce this issue

**Comment by laurenreidexpensify** [comment] 2023-07-12 13:09
I'm really struggling to reproduce this one too now. [@usman](https://github.com/usmantariq96) is there anything additional the in the reproduction steps you can break down for us to help?

**Comment by ygshbht** [comment] 2023-07-12 14:08
Hi @laurenreidexpensify  You need to move out your mouse fast after unchecking

**Comment by abdulrahuman5196** [comment] 2023-07-12 20:27
>You need to move out your mouse fast after unchecking


If this is the way to reproduce, I would question if we should even consider it a bug?

**Comment by ygshbht** [comment] 2023-07-12 20:36
@abdulrahuman5196 Thank you for your feedback. I understand that the scenario seems highly specific and not likely to occur under **typical use**. However, the **user experience** is the highest priority when it comes to the design and functionality of any application, striving to ensure it is as **bug-free** as possible, even in the edge cases.

While the probability of this issue occurring in normal use might be low, it could still **impact the perception** of the software's quality and usability. A user who encounters this issue might find it confusing or irritating, something we would want to avoid.

Moreover, considering the diverse range of user interaction patterns, it is important to recognize that we can't always predict how users will interact with the application. Some users may interact quickly or in unexpected ways, which could make this issue more common for them.

Rectifying such small nuances will only serve to **polish the product**. By fixing such edge cases, we not only improve the overall user experience but also demonstrate a **commitment to providing a high-quality product**.

Addressing this issue doesn't seem to present any downsides. It could be argued that improving the code to handle this edge case makes the codebase **more robust** and less prone to other, potentially related, issues in the future.

If you have further questions or if anything remains unclear, please feel free to ask.

**Comment by ygshbht** [comment] 2023-07-12 20:37
@abdulrahuman5196 Thank you for your feedback. I understand that the scenario seems a bit specific and not likely to occur under **typical use**. However, the **user experience** is the highest priority when it comes to the design and functionality of any application, striving to ensure it is as **bug-free** as possible, even in the edge cases.

While the probability of this issue occurring in normal use might be low, it could still **impact the perception** of the software's quality and usability. A user who encounters this issue might find it confusing or irritating, something we would want to avoid.

Moreover, considering the diverse range of user interaction patterns, it is important to recognize that we can't always predict how users will interact with the application. Some users may interact quickly or in unexpected ways, which could make this issue more common for them.

Rectifying such small nuances will only serve to **polish the product**. By fixing such edge cases, we not only improve the overall user experience but also demonstrate a **commitment to providing a high-quality product**.

Addressing this issue doesn't seem to present any downsides. It could be argued that improving the code to handle this edge case makes the codebase **more robust** and less prone to other, potentially related, issues in the future.

If you have further questions or if anything remains unclear, please feel free to ask.

**Comment by abdulrahuman5196** [comment] 2023-07-15 19:54
@laurenreidexpensify Kindly check on this https://github.com/Expensify/App/issues/22159#issuecomment-1633166927

**Comment by laurenreidexpensify** [comment] 2023-07-18 09:36
@abdulrahuman5196 I totally hear your perspective here, and I have felt that way too about many bugs, but I agree with the points that @ygshbht has raised about this being about maintaining the standard everywhere on the product. 

If @ygshbht's fix addresses this adequately, I think let's go for it?

**Comment by abdulrahuman5196** [comment] 2023-07-18 09:38
Got it @laurenreidexpensify . Will try to repro the issue and review the proposal.

**Comment by s-alves10** [comment] 2023-07-18 09:44
I think we need to handle this issue with https://github.com/Expensify/App/issues/16923.

**Comment by abdulrahuman5196** [comment] 2023-07-19 20:10
@ygshbht 

>In order to solve this issue, we could reconsider the approach of handling the mouse events in the Hoverable component. Instead of attaching the event to the child component, we can attach it to the document itself. Using the mousemove event, we can check if the mouse is inside the component

In which component you plan to add this?

>This can be done by utilizing the getBoundingClientRect method on the component element

Based on the above the followup question on this would be to , how do you plan to implement this.


For proposals, it is good to link expensify code base references to mention where and how you plan to make the changes proposed,

**Comment by ygshbht** [comment] 2023-07-19 20:45
Thanks for your question, @abdulrahuman5196 . My proposed solution revolves around creating a new context provider similar to `KeyboardStateProvider `and `WindowDimensionsProvider`. In this case, however, our new provider, which we can call `MousemoveProvider`, will listen to the mousemove event and execute the function that its child components provide.

To illustrate, the `Hoverable `component will subscribe to the mousemove event via this `MousemoveProvider`. Using `getBoundingClientRect`, `Hoverable `can then determine if the mouse is hovering over it and adjust its state accordingly. This approach ensures that mouse movements are accurately tracked across the document and provides a more consistent user experience.

https://github.com/Expensify/App/blob/e9fa9a902fe6c533be43519297e459bea01a5330/src/components/Hoverable/index.js#L22-L55

In `componentDidMount`, we can subscribe to the event using something like mousemovecontext.register(this.onMouseMove) and in componentWillUnmount, we can do this.mousemovecontext.unregister(this.onMouseMove)

onMouseMove can be like:
onMouseMove(e){

}

**Comment by ygshbht** [comment] 2023-07-19 20:52
Thank you for your question, @abdulrahuman5196. In my proposal, I recommend creating a new context provider, akin to `KeyboardStateProvider `and `WindowDimensionsProvider`. This new provider, which we could name `MousemoveProvider`, would be responsible for listening to the `mousemove `event and executing functions provided by its child components.

For instance, the `Hoverable `component would subscribe to the `mousemove `event via our `MousemoveProvider`. Using `getBoundingClientRect`, `Hoverable `can then determine whether the mouse is hovering over it and adjust its state accordingly. This approach aims to ensure that mouse movements are accurately tracked across the entire document, leading to a more consistent user experience.

https://github.com/Expensify/App/blob/e9fa9a902fe6c533be43519297e459bea01a5330/src/components/Hoverable/index.js#L22-L55

In the `componentDidMount `method, we can subscribe to the event with something like `mousemovecontext.register(this.onMouseMove)`, and in `componentWillUnmount`, we can unregister the event with `this.mousemovecontext.unregister(this.onMouseMove`).

The `onMouseMove `function could look something like this:
```
/** e = mouseEvent */
onMouseMove(e) {
    if (this.wrapperView) {
        const rect = this.wrapperView.getBoundingClientRect();
        const isHovered = rect.left <= e.clientX && e.clientX <= rect.right &&
            rect.top <= e.clientY && e.clientY <= rect.bottom;
        
        this.setIsHovered(isHovered);
    }
}
```

**Comment by laurenreidexpensify** [comment] 2023-07-24 10:26
@abdulrahuman5196 thoughts on the above? Thanks

**Comment by mvtglobally** [comment] 2023-07-25 04:43
Issue not reproducible during KI retests. (First week)

**Comment by ygshbht** [comment] 2023-07-25 05:08
@mvtglobally Always happy to help
**Steps:**
1. Uncheck the task
2. Shortly move the mouse out while its rerendering


https://github.com/Expensify/App/assets/65986357/6e614116-3737-4b36-b9fd-b1d7f6539828

**Comment by laurenreidexpensify** [comment] 2023-07-26 19:10
As this wasn't reproducible during KI tests https://github.com/Expensify/App/issues/22159#issuecomment-1649116012 I think we shoudl consider closing @abdulrahuman5196 ?

**Comment by abdulrahuman5196** [comment] 2023-07-26 19:16
> As this wasn't reproducible during KI tests https://github.com/Expensify/App/issues/22159#issuecomment-1649116012 I think we shoudl consider closing @abdulrahuman5196 ?

Yes. Could you kindly check once, if still not reproducible we can close this.

**Comment by usmantariq96** [comment] 2023-07-27 03:32
@abdulrahuman5196  It is still reproducible  at my end. Please find attached video for your reference. 

https://github.com/Expensify/App/assets/127622389/5ebf617f-c852-41be-a8b9-7d1f1785eb6f

**Comment by laurenreidexpensify** [comment] 2023-07-28 13:40
@usmantariq96 as you were able to reproduce, do you have a proposal to fix this bug? thanks!

**Comment by usmantariq96** [comment] 2023-07-28 15:22
@laurenreidexpensify  No I don't know how to solve it.
Thanks

**Comment by laurenreidexpensify** [comment] 2023-07-31 09:56
I am going to close this one as it is not reliably reproducible in KI testing. Let's reopen if we can reliably reproduce.

**Closed by laurenreidexpensify** 2023-07-31 09:56 UTC
Labels: External, Engineering, Daily, Needs Reproduction, Help Wanted, Overdue, Bug
