### ISSUE TITLE
[HOLD for payment 2024-05-22] Tax - Unable to save valid tax rate amount when changing currency for the first time

### ISSUE THREAD

**Issue by izarutskaya** [Expensify/App#42047] opened 2024-05-13 11:49 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.73-0
**Reproducible in staging?:** Y
**Reproducible in production?:** N
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Issue reported by:** Applause-internal team

## Action Performed:
Precondition:
- Workspace has enabled tax rate.
- Workspace currency default is tax exempt (0%).
- Foreign currency default have different tax rate (non-zero rate).

1. Go to staging.new.expensify.com
2. Go to workspace chat.
3. Go to + > Submit expense.
4. Enter amount (maintain local currency) > Next.
5. On confirmation page, click Tax amount.
6. Change the currency to any foreign currency.
7. After changing to foreign currency, the tax rate will automatically adjust to the non-zero tax rate (Foreign currency default).
8. Enter a valid tax amount (now that the rate is no longer 0%).
9. Save it.

## Expected Result:
User will be able to save the tax amount as long as the tax amount falls within the limit of the new rate (Foreign currency default).

## Actual Result:
When saving a valid tax amount, error shows up. The maximum rate amount in the error message still follows the previous tax rate (Workspace currency default). User will need to save 0 tax amount and return to Tax amount after saving to save the new tax amount.

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [x] Android: mWeb Chrome
- [x] iOS: Native
- [x] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

https://github.com/Expensify/App/assets/115492554/ff9c40a2-b457-4ccf-bcb3-7baade482511

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by izarutskaya** [comment] 2024-05-13 11:49
@abekkala I haven't added the External label as I wasn't 100% sure about this issue. Please take a look and add the label if you agree it's a bug and can be handled by external contributors.

**Comment by izarutskaya** [comment] 2024-05-13 11:50
We think this issue might be related to the #collect project.

**Comment by izarutskaya** [comment] 2024-05-13 11:50
Production 


https://github.com/Expensify/App/assets/115492554/65d88ea9-fc3d-4803-b9e9-63d91279ebc2

**Comment by allroundexperts** [comment] 2024-05-13 13:11
@ShridharGoel's [proposal](https://github.com/Expensify/App/issues/42047#issuecomment-2107476499) works good. The RCA seems to be correct as well. We are always taking into account the transaction currency rather than the selected currency.

🎀 👀 🎀 C+ reviewed

**Comment by cristipaval** [comment] 2024-05-13 13:14
[This one](https://github.com/Expensify/App/pull/40443) seems to be the offending PR. @MonilBhavsar could you please have a look at this deploy blocker?

**Comment by cristipaval** [comment] 2024-05-13 13:15
ah, sorry @lakchote , it seems you were on it already 🙇 
Unassigning myself.

**Comment by lakchote** [comment] 2024-05-13 13:15
@ShridharGoel feel free to raise a PR whenever you can so we can test it timely and fix the blocker.

**Comment by lakchote** [comment] 2024-05-13 13:17
> ah, sorry @lakchote , it seems you were on it already 🙇 Unassigning myself.

Haha, we were in sync 😄

Decided to go with following the contributor's proposal [as we can't really revert the offending PR](https://github.com/Expensify/App/pull/40443#issuecomment-2107304267), and the proposal explains the RCA clearly.

**Comment by lakchote** [comment] 2024-05-14 04:51
PR merged. Asked for a CP [here](https://expensify.slack.com/archives/C07J32337/p1715661511636709).

**Comment by Beamanator** [comment] 2024-05-14 08:24
PR CP'd, @lakchote confirmed it's fixed on staging so marking NAB!

**Comment by strepanier03** [comment] 2024-05-23 01:02
I hired your in Upwork @ShridharGoel, I'll check tomorrow to see if I can pay it out. 

@allroundexperts - I'll finish up the payment summary once the checklist is done, thanks!

**Comment by allroundexperts** [comment] 2024-05-26 17:19
## Checklist
1. https://github.com/Expensify/App/pull/40443
2. N/A since this was a regression
3. N/A
4. A regression test would be helpful. The test steps look simple enough to me!

**Comment by strepanier03** [comment] 2024-05-28 23:27
### Payment Summary

- @allroundexperts owed $250 via Manual Requests in NewDot
- @ShridharGoel paid $250 via Upwork ([LINK](https://www.upwork.com/nx/wm/offer/102427922)) - Pending acceptance

@JmillsExpensify - Payment request incoming.

**Comment by strepanier03** [comment] 2024-06-02 16:29
@ShridharGoel - Please accept the Upwork job so it can be paid?

**Comment by strepanier03** [comment] 2024-06-02 16:30
I am out of the office from June 3-10 - If you need BZ action in that time please reach out in Slack to ask for an assist.

**Comment by JmillsExpensify** [comment] 2024-06-05 05:29
Contributor paid out. @allroundexperts going to close this issue and see you again when I receive the payment request.

**Closed by JmillsExpensify** 2024-06-05 05:29 UTC
Labels: Engineering, Daily, Overdue, Awaiting Payment, Bug

**Comment by JmillsExpensify** [comment] 2024-07-09 23:07
$250 approved for @allroundexperts
