### ISSUE TITLE
iPhone 14 Pro - Cannot close full screen attachment modal 

### ISSUE THREAD

**Issue by kavimuru** [Expensify/App#12867] opened 2022-11-18 16:17 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:

1. Go to any chat
2. Upload an image
3. Tap on it to view in full screen

## Expected Result:
Able to close the modal

## Actual Result:
Tapping X does nothing

## Workaround:
unknown

## Platform:

Where is this issue occurring?

- iOS - iPhone 14 Pro

**Version Number:** 1.2.29-2
**Reproducible in staging?:** Need reproduction
**Reproducible in production?:** Need reproduction
**Email or phone of affected tester (no customers):** 
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** 
<img src="https://user-images.githubusercontent.com/43996225/202751078-997571dd-0f36-438f-a284-b3eb4e0bc905.jpg" width="40%" height="40%">
**Expensify/Expensify Issue URL:** 
**Issue reported by:** @roryabraham 
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1668707540056339

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by neil-marcellini** [comment] 2022-11-18 17:44
I'm not able to reproduce this on staging:

https://user-images.githubusercontent.com/26260477/202768494-d537d2f7-66f0-4a95-b990-0be5e6e9e828.MP4

**Comment by davidcardoza** [comment] 2022-11-18 19:18
I cannot reproduce on staging in an iPhone 13 pro iOS 16.1

https://user-images.githubusercontent.com/6643649/202785014-9d22a5a3-b8d5-4fe7-8531-c9e3c0ef9699.MP4

**Comment by davidcardoza** [comment] 2022-11-23 01:46
Since this can't be reproduced I am going to close this out.

**Closed by davidcardoza** 2022-11-23 01:46 UTC
Labels: Daily, Needs Reproduction, Overdue, Bug

**Comment by roryabraham** [comment] 2022-11-29 08:46
I'm no longer able to reproduce this either 👍🏼
