### ISSUE TITLE
[$500] Request Money -Scan - Scan report allows protected PDF upload

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#26713] opened 2023-09-04 19:38 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Open the app
2. Click on plus and click request money
3. Click on scan and upload password protected PDF
4. Complete the process
5. Observe that it causes unexpected error

## Expected Result:
Error message "Password protected and cannot be read" displayed immediately after a password protected PDF is selected.

## Actual Result:
Scan report allows password protected PDF upload and causes unexpected error after the process

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android / native
- [x] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [x] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 1.3.63.0
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/93399543/2928efc3-8abf-4a0e-96e9-1d970d9db01e

https://github.com/Expensify/App/assets/93399543/4d09fdbc-ba0e-4000-a053-71f510c6a4f7

**Expensify/Expensify Issue URL:**
**Issue reported by:** @dhanashree-sawant
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1693417461660059

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~019e1ea506f5c204cc</li>
        <li>Upwork Job ID: 1700171947455168512</li>
        <li>Last Price Increase: 2023-09-08</li>
    </ul>
</details>

**Comment by michaelhaxhiu** [comment] 2023-09-08 15:39
I think we need to hammer out the `Expected Result` a little more. Like would it be better to show an error immediately after a password protected PDF is selected (saying it's "Password protected and cannot be read")?

**Comment by michaelhaxhiu** [comment] 2023-09-08 15:39
Let's get some C+ eyes on this!

**Comment by michaelhaxhiu** [comment] 2023-09-08 15:43
Also @kbecciv why does this have `[Distance]` in the title? Am I spacing on something?

**Comment by ishpaul777** [comment] 2023-09-08 16:14
## Proposal
### Please re-state the problem that we are trying to solve in this issue.
Scan report allows protected PDF upload 

### What is the root cause of that problem?
Pdf File is not validated for encryption while validation of file 

### What changes do you think we should make in order to solve the problem?
Validate file for encryption.
```
const { fileExtension } = FileUtils.splitExtensionFromFileName(lodashGet(file, 'name', ''));

    // if file extexnsion is pdf validate if it is not password protected
    if (fileExtension.toLowerCase() === "pdf") {
        const reader = new FileReader();
        reader.readAsArrayBuffer(file);
        reader.onload = function () {
            let files = new Blob([reader.result], { type: 'application/pdf' });
            files.text().then(x => {
                if (x.includes('/Encrypt')) {
                    Receipt.setUploadReceiptError(true, Localize.translateLocal('attachmentPicker.wrongFileType'), Localize.translateLocal('attachmentPicker.notAllowedExtension'));
                    return false;
                }
            });
        };
    }
```

https://github.com/Expensify/App/assets/104348397/e14e717b-38fe-440b-8bd7-f049755b3077

**Comment by b4s36t4** [comment] 2023-09-08 16:34
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
 Request Money -Scan - Scan report allows protected PDF upload
### What is the root cause of that problem?

We're not checking the PDF is weather encrypted or not, we're just processing the PDF without verifying.

### What changes do you think we should make in order to solve the problem?

We could use `pdfJs` from `react-pdf` and load the document before moving on to next step.

We can validate if the selected is pdf or not, then we load the pdf using `pdfJS` which raises error if it's a protected file.

> We're not passing any `onPassword` callback which is the reason to raise the error.

We need to update this function https://github.com/Expensify/App/blob/636b0657602b990b663bbeb0a5b44c9f3e7ae1f7/src/pages/iou/ReceiptSelector/index.js#L79

By using the following we can also catch the exception of invalid PDF. (maybe selected file is not pdf but extension is `.pdf`?)

```jsx
// code

const isPdf = pdfjs.isPdfFile(file.name);

const filePath = URL.createObjectURL(file);
if (isPdf) {
    pdfjs
        .getDocument(filePath)
        .promise.then(() => {
            // PDF loaded correctly
            IOU.setMoneyRequestReceipt(filePath, file.name);
            IOU.navigateToNextPage(iou, iouType, reportID, report);
        })
        .catch((error) => {
            // PDF is asking for password
            if (error.code === CONST.PDF_PASSWORD_FORM.REACT_PDF_PASSWORD_RESPONSES.NEED_PASSWORD) {
                Receipt.setUploadReceiptError(true, translate('attachmentPicker.wrongFileType'), translate('attachmentPicker.notAllowedExtension'));
                return;
            }
            Receipt.setUploadReceiptError(true, translate('attachmentPicker.attachmentError'), translate('attachmentPicker.errorWhileSelectingAttachment'));
        });
    return;
}
IOU.setMoneyRequestReceipt(filePath, file.name);
IOU.navigateToNextPage(iou, iouType, reportID, report);

//code

```



### What alternative solutions did you explore? (Optional)
NA

### Result

https://github.com/Expensify/App/assets/59088937/a4f9b6eb-4426-4053-b8ed-664b145843fe

**Comment by Santhosh-Sellavel** [comment] 2023-09-08 16:59
@michaelhaxhiu Unassigned due to low bandwidth can you get a new C+ here by re-applying the external label again, thanks!

**Comment by situchan** [comment] 2023-09-08 17:07
@michaelhaxhiu I am interested in reviewing this.

Currently, I see that any file types (not only image, pdf but also txt, dmg, etc) are acceptable in scan upload as long as its size is within 240bytes-24MB. Even folder is able to drag & drop.
Should this be fixed here? If so, what file format should only be allowed?

**Comment by ishpaul777** [comment] 2023-09-08 17:10
>  I see that any file types (not only image, pdf but also txt, dmg, etc) 
@situchan I reported this a while ago - https://app.slack.com/client/T03SC9DTT/C049HHMV9SM/thread/C049HHMV9SM-1692815288.242469

**Comment by situchan** [comment] 2023-09-08 17:16
I see that restriction is removed in https://github.com/Expensify/App/pull/21285. But it's general, i.e. in composer.
I still think we should add restriction to scan receipt file type.

**Comment by ishpaul777** [comment] 2023-09-08 17:18
Agreed, thats why I propose the option tion validation in my propsal linked to thread

**Comment by ishpaul777** [comment] 2023-09-08 17:23
There is Also one more issue if we dont validate the file type in composer or  scan receipt. User add a app to to composer. App does nothing and next time the add attachment option won't even work.

https://github.com/Expensify/App/assets/104348397/0cdc5c0b-ebb1-40bb-8574-6b75800ca6c1

**Comment by michaelhaxhiu** [comment] 2023-09-11 16:09
Re-assigned label to get a new C+ assigned, per Santhosh's comment above.

**Comment by akinwale** [comment] 2023-09-11 16:46
> @michaelhaxhiu I am interested in reviewing this.
> 
> Currently, I see that any file types (not only image, pdf but also txt, dmg, etc) are acceptable in scan upload as long as its size is within 240bytes-24MB. Even folder is able to drag & drop. Should this be fixed here? If so, what file format should only be allowed?

Folder drag and drop was raised in https://github.com/Expensify/App/issues/26892 but closed as wontfix due to the platform (Windows). If we intend to get that sorted, then it makes sense to reopen the issue.

**Comment by situchan** [comment] 2023-09-11 16:49
@michaelhaxhiu we should confirm the expected behavior first. Which option?
- limit file types (i.e. image only) as this is scan receipt
- allow pdf but do frontend validation if it's password protected

**Comment by michaelhaxhiu** [comment] 2023-09-11 17:44
After brewing, this is seeming more like a feature request than a bug report. We already show an error when you try to upload this file type, so I am leaning toward this behaving as expected.

You could argue we need a more specific error message - but that's where this venture into feature request territory in my mind. I'm going to close this for now as I think it's more of a `new feature` than `bug`. If you disagree feel free to make your case in the Slack thread!

**Closed by michaelhaxhiu** 2023-09-11 17:44 UTC
Labels: External, Daily, Help Wanted, Bug
