### ISSUE TITLE
IOU - No loading state when click `cancel` in the money request details page and page closes abruptly

### ISSUE THREAD

**Issue by kavimuru** [Expensify/App#12569] opened 2022-11-08 20:29 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Go to URL https://staging.new.expensify.com/
2. Log in with any account
3. Click FAB button -> Request money
4. Enter an amount -> Request (3 times)
2. Open Details
3. Click Cancel one money request

## Expected Result:
When hit `cancel` should see a loading state and details page should not close abruptly

## Actual Result:
After canceling the money request, the details page closes abruptly.

## Workaround:
unknown

## Platform:

Where is this issue occurring?

- Web
- iOS
- Android
- Desktop App
- Mobile Web

**Version Number:** 1.2.25-0
**Reproducible in staging?:** y
**Reproducible in production?:** n
**Email or phone of affected tester (no customers):** 
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** 

https://user-images.githubusercontent.com/43996225/200668598-1bdc423c-155a-4417-bed5-193e72e63bdc.mp4

**Expensify/Expensify Issue URL:** 
**Issue reported by:** Applause internal team
**Slack conversation:** 

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by luacmartins** [comment] 2022-11-08 21:01
This is the expected behavior since cancel/decline money requests are now optimistic! See https://github.com/Expensify/App/pull/11720. Closing this issue!

**Closed by luacmartins** 2022-11-08 21:01 UTC
Labels: DeployBlockerCash, Engineering, Hourly, Bug
