### ISSUE TITLE
[HOLD for payment 2023-10-13] [$250] Migrate SidebarLinks.js to function component

### ISSUE THREAD

**Issue by marcaaron** [Expensify/App#16271] opened 2023-03-20 15:35 UTC
### Filenames
- [ ] [src/pages/home/sidebar/SidebarLinks.js](https://github.com/Expensify/App/blob/main/src/pages/home/sidebar/SidebarLinks.js)
    - **type:** `React.Component`
    - **has state values:** false
    - **has refs:** false
    - **has context:** false
    - **lifecycle methods:** none

### Task
- We currently have some class components in our codebase that we would like to refactor to a function component.
- Here's a link with some general advice on how to refactor a class component to a function component: https://react.dev/reference/react/Component#alternatives
- If you need additional guidance, please ask in [#expensify-open-source](https://expensify.slack.com/archives/C01GTK53T8Q)
- Test for any regressions and verify that there are no breaking changes

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~016d13c3beda918356</li>
        <li>Upwork Job ID: 1673399360666615808</li>
        2023-06-26<li>Automatic offers: </li>
<ul>
<li> |  | 0</li>
<li> |  | 0</li>
</ul></li>
    </ul>
</details>

**Comment by marcaaron** [comment] 2023-04-13 21:39
Heads up! The pricing for this issue has been adjusted based on the scope of the work and the fact that no complex bug investigations or proposal are required.

**Comment by muxriddinmuqimov77** [comment] 2023-06-06 05:51
I'd like to work on this issue

**Comment by olexyt** [comment] 2023-06-26 19:02
I love to work on this.

**Comment by chiragsalian** [comment] 2023-06-26 20:03
Yup, i agree. Updating title so its on HOLD

**Comment by slafortune** [comment] 2023-06-29 16:24
Updating this to weekly until it's off hold.

**Comment by vdem0115** [comment] 2023-07-04 15:16
Can I work on this issue?

**Comment by to-ai** [comment] 2023-07-11 21:24
I am able to work on this task.

**Comment by cloudpresser** [comment] 2023-07-20 21:01
> Holding [PR](https://github.com/Expensify/App/pull/21406) is still in review

It's been merged now, accepting proposals?

**Comment by cloudpresser** [comment] 2023-07-20 21:01
## Proposal
### Please re-state the problem that we are trying to solve in this issue.
Migrate [SidebarLinks.js](https://github.com/Expensify/App/blob/main/src/pages/home/sidebar/SidebarLinks.js) to function component
 
### What is the root cause of that problem?
Component was written as a class component
 
### What changes do you think we should make in order to solve the problem?
Convert it to a functional component following https://react.dev/reference/react/Component#alternatives

**Comment by shubham1206agra** [comment] 2023-07-24 16:14
## Proposal
### Please re-state the problem that we are trying to solve in this issue.

Migrate SidebarLinks.js to function component.

### What is the root cause of that problem?

The component was written as a class component and is now being migrated to a functional component.

BONUS
There is a bug in ComponentDidMount function which also will be fixed.

### What changes do you think we should make in order to solve the problem?

Fix the bug and convert it to a functional component with the same functionality.

**Comment by slafortune** [comment] 2023-07-24 19:31
Yes - accepting proposals now!  Thanks @cloudpresser 👍

**Comment by thienlnam** [comment] 2023-07-24 21:17
Site is down so our automations are also down - will have to re-assign once our site is back up

**Comment by cloudpresser** [comment] 2023-07-25 21:02
Writing the PR now, will be up in the next few minutes

**Comment by slafortune** [comment] 2023-08-22 21:05
Looks like this is close to complete, will this be done by the EOW @cloudpresser @allroundexperts ?

**Comment by slafortune** [comment] 2023-09-08 20:03
Do you have an update @allroundexperts @cloudpresser ?

reassigning a BZ member, I am out on sabbatical.

**Comment by marcaaron** [comment] 2023-09-08 20:30
@allroundexperts can you clarify the following:

>its been some time

Since what?

>do you think we should re-assign to someone else?

Which assignment are you referring to? Who are you proposing we assign?

**Comment by thienlnam** [comment] 2023-09-11 08:08
@shubham1206agra Are you still available to work on this?

**Comment by shubham1206agra** [comment] 2023-09-11 08:10
Yeah

**Comment by joekaufmanexpensify** [comment] 2023-09-12 18:55
@shubham1206agra is the PR for this up yet?

**Comment by shubham1206agra** [comment] 2023-09-13 06:34
@joekaufmanexpensify PR will be up today

**Comment by shubham1206agra** [comment] 2023-09-13 06:37
@allroundexperts, I have one minor question while going through code.
Can you confirm which PR removed `isCreateMenuOpen` from `BaseSidebarScreen`?
It looks like this is affecting the prop in `SidebarLinks`.

**Comment by joekaufmanexpensify** [comment] 2023-09-14 19:13
@shubham1206agra are you still looking for insight on this?

**Comment by shubham1206agra** [comment] 2023-09-15 02:26
Yes

**Comment by joekaufmanexpensify** [comment] 2023-09-17 08:21
Got it. @allroundexperts mind following up on the above question?

**Comment by joekaufmanexpensify** [comment] 2023-09-18 08:04
Still pending further follow up

**Comment by joekaufmanexpensify** [comment] 2023-09-20 08:01
@shubham1206agra checking in to see if a PR will be up here soon?

**Comment by shubham1206agra** [comment] 2023-09-20 11:56
PR is up

**Comment by joekaufmanexpensify** [comment] 2023-10-02 21:16
Pending review from @thienlnam

**Comment by joekaufmanexpensify** [comment] 2023-10-09 15:13
Payment pending this week

**Comment by joekaufmanexpensify** [comment] 2023-10-12 17:46
[Bumped BZ checklist](https://expensify.slack.com/archives/C02NK2DQWUX/p1697132773443099)

**Comment by joekaufmanexpensify** [comment] 2023-10-13 17:34
Pending completion of BZ checklist before we issue payment

**Comment by joekaufmanexpensify** [comment] 2023-10-16 14:31
Cool cool. TY! I will take care of next steps today then.

**Comment by joekaufmanexpensify** [comment] 2023-10-16 18:30
All set to issue payment here. @shubham1206agra was assigned to this issue on 2023-09-11, and this PR merged on 2023-10-02. This is longer than 9 business days, so there is a 50% reduction in payment here. This means payment will be: 

- @shubham1206agra - $125 for PR, paid via Upwork. 
- @allroundexperts - $125 for C+ review, paid via NewDot.

**Comment by joekaufmanexpensify** [comment] 2023-10-16 18:34
Original upwork job is closed. New one is[ here. ](https://www.upwork.com/jobs/~011ece8253c45422be)

**Comment by joekaufmanexpensify** [comment] 2023-10-16 18:36
@allroundexperts could you please request $125 via NewDot and comment here once that's complete?

**Comment by joekaufmanexpensify** [comment] 2023-10-16 18:40
Is there somewhere you see that confirmed? As of a few months ago, I'm seeing an internal discussion that advises penalty applies to these. I agree on bonuses not applying though. That has been my understanding.

**Comment by joekaufmanexpensify** [comment] 2023-10-16 18:47
Ah, I meant I am seeing an internal discussion that confirms that the penalty applies for these migration issues. Is there anywhere you've seen that says these do not apply?

**Comment by joekaufmanexpensify** [comment] 2023-10-17 12:40
I [asked again](https://expensify.slack.com/archives/C01SKUP7QR0/p1697546401818119?thread_ts=1689946708.603589&cid=C01SKUP7QR0) internally to confirm.

**Comment by joekaufmanexpensify** [comment] 2023-10-17 12:46
Yep, confirmed penalty applies here. So payment is $125!

**Comment by joekaufmanexpensify** [comment] 2023-10-17 19:54
@shubham1206agra $125 sent and contract ended!

**Comment by joekaufmanexpensify** [comment] 2023-10-17 19:54
Once @allroundexperts submits their request in NewDot, we are good to close this

**Comment by joekaufmanexpensify** [comment] 2023-10-17 20:24
TY! Payment summary is [here](https://github.com/Expensify/App/issues/16271#issuecomment-1765061444) for the individual paying the request.

**Closed by joekaufmanexpensify** 2023-10-17 20:24 UTC
Labels: External, Daily, Improvement, NewFeature, Awaiting Payment

**Comment by JmillsExpensify** [comment] 2023-10-18 18:13
$125 payment approved for @allroundexperts based on BZ summary above.
