### ISSUE TITLE
[$1000] Email mentions recommendations are shown even for invalid emails

### ISSUE THREAD

**Issue by kavimuru** [Expensify/App#18855] opened 2023-05-12 17:45 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:

1. Go to staging dot
2. Go to new chat
3. Type in invalid email
4. Now go to some other chat and try to use the mention of the invalid email
5. Result: See that the invalid email is also shown on the recommendation

## Expected Result: 
Email mentions recommendations should not be shown for invalid emails
## Actual Result:  
Email mentions recommendations are shown even for invalid emails

## Workaround:
Can the user still use Expensify without this being fixed? Have you informed them of the workaround?

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [x] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 1.3.13
**Reproducible in staging?:** y
**Reproducible in production?:**
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/43996225/a3a3b476-2b84-435b-bc3e-0486b26e4c0d

https://github.com/Expensify/App/assets/43996225/11051d63-9639-40ac-b25a-bae252cada98

**Expensify/Expensify Issue URL:**
**Issue reported by:** @avi-shek-jha
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1683804715330119

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01d807498aa87fdd19</li>
        <li>Upwork Job ID: 1657109574155763712</li>
        <li>Last Price Increase: 2023-05-12</li>
    </ul>
</details>

**Comment by strepanier03** [comment] 2023-05-12 19:25
Able to recreate this easily while testing:

<img width="1440" alt="2023-05-12_12-22-40" src="https://github.com/Expensify/App/assets/10925636/ed7920fc-902c-4765-8326-6f27b7750f69">
<img width="1449" alt="2023-05-12_12-22-55" src="https://github.com/Expensify/App/assets/10925636/3d5f7880-270f-4b71-b874-2e9e4448458e">

**Comment by jayeshmangwani** [comment] 2023-05-12 20:59
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
An invalid email address can be visible in the mentions auto-suggestion.

### What is the root cause of that problem?
This specific email(kkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkk@gmail.com) is valid from the Str.isValidEmail(), and We haven't added any logic for hiding the suggestions when the server sends the error for that specific report of an invalid email.

### What changes do you think we should make in order to solve the problem?

There can be two possibilities to solve this bug.

1. We should update the Str.isValidEmail function like the backend, so that Str.isValidEmail return false for the mentioned email and we will not show it in the suggestion

2. We can add a check in suggestions, if the report has any server errors and pendinAction for the report is of type add then no need to show email in the suggestions


We can achieve this by adding the following code here

https://github.com/Expensify/App/blob/3d78d911a4832b752ba1255adfc9bef7499fe2c9/src/pages/home/report/ReportActionCompose.js#L555

```
const suggestions = _.filter([...options.recentReports, options.userToInvite], (x) => {
    if (x && !_.isEmpty(x.allReportErrors) && x.pendingAction === 'add') {
        return false;
    }
    return !!x;
});
```

<details>
  <summary>Result</summary>

**Before**

https://github.com/Expensify/App/assets/35371050/d43c8f2a-a2e5-4126-acb0-7b4ad15de011



**After**  
  
  

https://github.com/Expensify/App/assets/35371050/e6de6a77-2c45-4191-9751-9995a11db051


</details>



### What alternative solutions did you explore? (Optional)
N/A

**Comment by strepanier03** [comment] 2023-05-13 22:50
Thank you both @aimane-chnaif and @fedirjh 🙌

**Comment by robertjchen** [comment] 2023-05-15 02:38
Thanks for the clarification, closing this out.

**Closed by robertjchen** 2023-05-15 02:38 UTC
Labels: External, Daily, Help Wanted, Bug
