### ISSUE TITLE
[HOLD for payment 2024-10-11] [$250] [Instant Submit] Retain the option to Pay elsewhere on processing/submitted reports when payments get disabled.

### ISSUE THREAD

**Issue by blimpich** [Expensify/App#49874] opened 2024-09-27 22:24 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Email or phone of affected tester (no customers):**
**Expensify/Expensify Issue URL:** https://github.com/Expensify/Expensify/issues/378376
**Issue reported by:** @garrettmknight 
**Slack conversation:** https://expensify.slack.com/archives/C036QM0SLJK/p1709825435599569

## Action Performed:
1. Create two new users, A and B
2. Have user A create a workspace and invite user B to the workspace as an employee
3. As user B, create an expense on the workspace
4. As user A, confirm that you can see the expense that user B made but that there is no "Pay with Expensify" and/or "Pay elsewhere" button for the expense
5. As user A, go to Settings > Workspaces > your_workspace > More features and turn on "Workflows"
6. Go to Workflows tab and turn on "Make or track payments"
7. As user B submit an expense to your_workspace
8. As user A, confirm that you can see the recently made expense and that it says "Pay with Expensify" and/or "Pay elsewhere" 
9. As user A go to Workflows tab and turn off "Make or track payments"
10. As user A navigate to the newly submitted expense

## Expected Result:
There should be an option to "Pay Elsewhere" on the expense for user A.

## Actual Result:
There is not option to "Pay Elsewhere".

## Workaround:
Turn on payments again, pay the expenses, then turn it off.

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~021839794267146442929</li>
        <li>Upwork Job ID: 1839794267146442929</li>
        <li>Last Price Increase: 2024-09-27</li>
<li>Automatic offers: </li>
<ul>
<li>ZhenjaHorbach | Reviewer | 104203098</li>
<li>truph01 | Contributor | 104203100</li>
</ul></li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @garrettmknight</details>

**Comment by blimpich** [comment] 2024-09-27 22:27
I don't think this needs design input, its sort of a new feature but more of a work around since we don't have a "mark as close" in new dot feature. Also unassigning @JmillsExpensify since @garrettmknight [created the original issue for this](https://github.com/Expensify/Expensify/issues/378376) so I think it'd be best to keep him as the BZ member on this since he has context.

**Comment by blimpich** [comment] 2024-09-27 22:32
Note to contributors, I think this should be straightforward, the data for what state a report is in should be in its onyx data. The psuedocode logic we want here is basically this:
```
if(!policy.settings.shouldAllowPayments && report.statusNum === STATUS_NUM.SUBMITTED) {
	showPaymentElsewhereOption();
}
```

Please see our [constants code](https://github.com/Expensify/App/blob/71db3f19691069182447b6b1b9fff62ec93be86c/src/CONST.ts#L980-L992) for what numbers correspond to what status the report is in.

**Comment by blimpich** [comment] 2024-09-27 22:34
And remember, we still want reports that are in the "closed" state, aka expenses that are created while the workspace setting "allow payments" is false, should _not_ show "Pay elsewhere". Its only expenses that are created while "allow payments" is turned on, and then once its turned off we should allow those expenses that are still in the submitted/processing state should be able to paid elsewhere.

**Comment by truph01** [comment] 2024-09-28 03:17
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
There is not option to "Pay Elsewhere".

### What is the root cause of that problem?
- We don't display the settle button if the ```policy?.reimbursementChoice``` is ```reimburseNo```:
https://github.com/Expensify/App/blob/71db3f19691069182447b6b1b9fff62ec93be86c/src/libs/actions/IOU.ts#L6941-L6943

### What changes do you think we should make in order to solve the problem?
- Based on suggestion [there](https://github.com/Expensify/App/issues/49874#issuecomment-2380234368), we can update logic:

https://github.com/Expensify/App/blob/71db3f19691069182447b6b1b9fff62ec93be86c/src/libs/actions/IOU.ts#L6941-L6943


```
    if (policy?.reimbursementChoice === CONST.POLICY.REIMBURSEMENT_CHOICES.REIMBURSEMENT_NO) {
        if (!shouldForceShowOnlyPayElsewhere) {
            return false;
        }
        if (iouReport?.statusNum !== CONST.REPORT.STATUS_NUM.SUBMITTED) {
            return false;
        }
    }
```
I introduced new ```shouldForceShowOnlyPayElsewhere``` param, default value is ```false```.
- In [there](https://github.com/Expensify/App/blob/71db3f19691069182447b6b1b9fff62ec93be86c/src/components/ReportActionItem/ReportPreview.tsx#L108), use above function to check should we display only pay else where button:

```
    const forceShowOnlyPayElsewhere = useMemo(
        () => isPaidAnimationRunning || IOU.canIOUBePaid(iouReport, chatReport, policy, allTransactions, true),
        [isPaidAnimationRunning, iouReport, chatReport, policy, allTransactions],
    );
```


- Use the above variable in:

https://github.com/Expensify/App/blob/71db3f19691069182447b6b1b9fff62ec93be86c/src/components/ReportActionItem/ReportPreview.tsx#L519-L520

```
                                {(shouldShowSettlementButton || forceShowOnlyPayElsewhere) && (
                                    <AnimatedSettlementButton
                                        forceShowOnlyPayElsewhere={forceShowOnlyPayElsewhere}
```

Now, the AnimatedSettlementButton button can be displayed even if the ```shouldShowSettlementButton``` is ```false```. And we pass down ```forceShowOnlyPayElsewhere``` to the AnimatedSettlementButton as well.


- In [there](https://github.com/Expensify/App/blob/71db3f19691069182447b6b1b9fff62ec93be86c/src/components/SettlementButton/index.tsx#L104), use the above ```forceShowOnlyPayElsewhere``` to only display pay elsewhere button:

```
        if (forceShowOnlyPayElsewhere) {
            return [paymentMethods[CONST.IOU.PAYMENT_TYPE.EXPENSIFY]];
        }
```


- The same logic should be applied to [MoneyReportHeader](https://github.com/Expensify/App/blob/main/src/components/MoneyReportHeader.tsx) component.
### What alternative solutions did you explore? (Optional)

**Comment by truph01** [comment] 2024-09-28 11:36
### [Proposal updated](https://github.com/Expensify/App/issues/49874#issuecomment-2380383002)

**Comment by truph01** [comment] 2024-09-30 06:53
### [Proposal updated](https://github.com/Expensify/App/issues/49874#issuecomment-2380383002)

**Comment by truph01** [comment] 2024-10-01 09:23
[PR](https://github.com/Expensify/App/pull/49967) is ready

**Comment by garrettmknight** [comment] 2024-10-11 18:23
**Payment Summary:**
- Contributor: @truph01 $250 via Upwork
- Reviewer: @ZhenjaHorbach $250

**Comment by garrettmknight** [comment] 2024-10-11 18:23
@ZhenjaHorbach please propose the regression test and I'll pay out your contract.

**Comment by garrettmknight** [comment] 2024-10-15 00:53
Paid, closing!

**Closed by garrettmknight** 2024-10-15 00:53 UTC
Labels: External, Daily, NewFeature, Overdue, Awaiting Payment
