### ISSUE TITLE
[HOLD for payment 2024-03-07] [HOLD for payment 2024-03-06] [$500] Android - Chat - Unable to upload pdf file

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#37240] opened 2024-02-26 22:53 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.44-0
**Reproducible in staging?:** y
**Reproducible in production?:** n

**Issue reported by:**

## Action Performed:
1. Open the app and log in
2. Open any chat
3. Tap the "+" button > Add attachment > Choose document
4. Select a pdf file

## Expected Result:
The preview of the PDF is displayed

## Actual Result:
User is returned to the chat, the preview of the PDF is not displayed

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [ ] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

https://github.com/Expensify/App/assets/93399543/7a2a01c4-c409-49a2-83b8-5ff0b67547fb

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Issue Owner</summary>Current Issue Owner: @parasharrajat</details>

**Comment by kbecciv** [comment] 2024-02-26 22:53
We think that this bug might be related to #vip-bills
@davidcardoza

**Comment by NikkiWines** [comment] 2024-02-26 22:58
Confirmed that this isn't reproducible on iOS staging (1.4.44-0), will test on Android dev to see if it's reproducible there. 

@davidcardoza do you know of any PRs related to PDFs that were recently merged/deployed?

**Comment by NikkiWines** [comment] 2024-02-27 07:36
Hmm, I'm unable to reproduce on dev so far and don't have an android device to confirm that it's not reproducible on prod.

I don't see any changes to the `AddAttachment` logic that's still on staging and would be a culprit for this. 

@kbecciv what account did you use to send the attachment, I'll check the logs to see if there's anything suspcious

**Comment by bernhardoj** [comment] 2024-02-27 12:10
Looks like it's coming from https://github.com/Expensify/App/pull/35164 where we are trying to get image size even though it's a PDF.

**Comment by kbecciv** [comment] 2024-02-27 14:48
@NikkiWines Tester's account - [applausetester+0119pm1e@applause.expensifail.com](mailto:applausetester+0119pm1e@applause.expensifail.com)

**Comment by NikkiWines** [comment] 2024-02-27 17:44
Oh yeah missed this since that PR was created back in January 😅 does indeed look like that's the likely culprit

**Comment by NikkiWines** [comment] 2024-02-27 20:53
this is fixed now! 🎊 thanks @dukenv0307 @parasharrajat

**Comment by NikkiWines** [comment] 2024-02-27 21:18
Adding a CME to see if there's any payment to be handled here 🙇

**Comment by DylanDylann** [comment] 2024-02-28 05:10
@parasharrajat Thank you for helping review this PR, I am not available at that time

**Comment by garrettmknight** [comment] 2024-02-28 20:40
Will pay out @parasharrajat for the review here. @dukenv0307 will get paid on the original issue.

**Closed** 2024-03-19 20:10 UTC
Labels: External, Engineering, Weekly, Awaiting Payment, Bug

**Comment by JmillsExpensify** [comment] 2024-06-11 18:40
$500 approved for @parasharrajat
