### ISSUE TITLE
[$500]  [Distance] - Distance editor menu in IOU report shows Merchant instead of Distance

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#26559] opened 2023-09-02 15:15 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___
**Issue found when executing PR** https://github.com/Expensify/App/pull/25707
## Action Performed:
1. Go to staging.new.expensify.com
2. Create a distance request in workspace chat
3. Open IOU report
4. Click Distance

## Expected Result:
The right hand menu shows Distance as the header

## Actual Result:
The right hand menu shows Merchant as the header. The title of the edit field also shows Merchant

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android / native
- [x] Android / Chrome
- [x] iOS / native
- [x] iOS / Safari
- [x] MacOS / Chrome / Safari
- [x] MacOS / Desktop

**Version Number:** 1.3.62-1

**Reproducible in staging?:** Yes

**Reproducible in production?:** No

**If this was caught during regression testing, add the test name, ID and link from TestRail:**

**Email or phone of affected tester (no customers):**

**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/78819774/3e2f7860-189d-4e39-81f9-4343ca21c14d

**Expensify/Expensify Issue URL:**

**Issue reported by:** Applause - Internal Team

**Slack conversation:**

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01c148f42c5bc47bd3</li>
        <li>Upwork Job ID: 1698180072419635200</li>
        <li>Last Price Increase: 2023-09-03</li>
    </ul>
</details>

**Comment by ShogunFire** [comment] 2023-09-02 15:39
## Proposal

### Please re-state the problem that we are trying to solve in this issue.

The text of the header and of the input are "Merchant" instead of Distance

### What is the root cause of that problem?

In MoneyRequestView here: 
https://github.com/Expensify/App/blob/9701fbe5ec24bf5031da390075b2a9fb125b3ce3/src/components/ReportActionItem/MoneyRequestView.js#L154-L164
We have only one MenuItemWithTopDescription for both Merchant and Distance and we navigate to the same page for both.

The page we navigate to is https://github.com/Expensify/App/blob/main/src/pages/EditRequestMerchantPage.js

In this page we display Merchant and never Distance

### What changes do you think we should make in order to solve the problem?

I think we should do a page specific for Distance because currently when we submit we actually save the distance in the merchant field here: https://github.com/Expensify/App/blob/9701fbe5ec24bf5031da390075b2a9fb125b3ce3/src/pages/EditRequestPage.js#L159-L166

So here are the changes I suggest:
In MoneyRequestView, add a specific MenuItemWithTopDescription  for Distance

Add CONST.EDIT_REQUEST_FIELD.DISTANCE in the const file

In EditRequestPage add a condition to test if the field is distance and navigate to the new page EditRequestDistancePage that will look like EditRequestMerchantPage but with the right text


### What alternative solutions did you explore? (Optional)

**Comment by situchan** [comment] 2023-09-02 16:36
This will be fixed in Edit distance request [PR](https://github.com/Expensify/App/pull/26141)

**Comment by hayata-suenaga** [comment] 2023-09-03 03:45
I'm so bad at assigning labels 😭

**Comment by b4s36t4** [comment] 2023-09-03 04:29
Hey, as @situchan mentioned is in't going taken care at some other PR? is this up for proposals?

**Comment by hayata-suenaga** [comment] 2023-09-03 04:39
@b4s36t4 I need to confirm with that PR author but probably will be fixed in that PR

I gonna keep this issue open but will removed help wanted label

**Comment by b4s36t4** [comment] 2023-09-03 04:40
Ok understood.

**Comment by zanyrenney** [comment] 2023-09-05 14:38
Hey @hayata-suenaga I'm a little lost on this one with the labels.

I think Anu is assigned as the BZ manager:
> Triggered auto assignment to @anmurali (External), see https://stackoverflow.com/c/expensify/questions/8582 for more details.

But then it looks like you unassigned her and then  the external label again which has also now assigned me... 

> [hayata-suenaga](https://github.com/hayata-suenaga) assigned [hayata-suenaga](https://github.com/hayata-suenaga) and unassigned [anmurali](https://github.com/anmurali) [2 days ago](https://github.com/Expensify/App/issues/26559#event-10265224286)

Can you confirm what's happening here please? Thanks!

**Comment by hayata-suenaga** [comment] 2023-09-05 17:22
<img width="300" alt="Screenshot 2023-09-05 at 10 19 32 AM" src="https://github.com/Expensify/App/assets/98560306/c69f5574-bbac-4d18-9452-a01939f2e907">

😓 this is probably the fault of my late-night brain... I constantly click wrong buttons 🔘 

Anyway, [this PR](https://github.com/Expensify/App/pull/26141) is going to fix the issue. I gonna close this issue for now

**Closed by hayata-suenaga** 2023-09-05 17:22 UTC
Labels: External, Engineering, Daily
