### ISSUE TITLE
[$500] Expense - "Pay with Expensify" button is grayed out briefly after requesting money

### ISSUE THREAD

**Issue by izarutskaya** [Expensify/App#35894] opened 2024-02-06 11:30 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** v.1.4-37.0
**Reproducible in staging?:** Y
**Reproducible in production?:** N
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** Applause-Internal Team
**Slack conversation:**

## Action Performed:
Precondition: User is a member of workspace in which the currency is different from the local currency.

1. Go to staging.new.expensify.com
2. Go to workspace chat.
3. Create a manual request.
4. Create another manual request.

## Expected Result:
"Pay with Expensify" button in the main chat will not gray out.

## Actual Result:
"Pay with Expensify" button is grayed out briefly after requesting money.

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [x] Android: mWeb Chrome
- [x] iOS: Native
- [x] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

https://github.com/Expensify/App/assets/115492554/8befebaf-5b25-4226-9bb8-499cf5d916a2

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01b74cf4a81b61a7fd</li>
        <li>Upwork Job ID: 1754829907209736192</li>
        <li>Last Price Increase: 2024-02-13</li>
    </ul>
</details>

**Comment by izarutskaya** [comment] 2024-02-06 11:32
We think that this bug might be related to #wave5-free-submitters
CC @dylanexpensify

**Comment by izarutskaya** [comment] 2024-02-06 11:33
Not repro in prod 

https://github.com/Expensify/App/assets/115492554/ed7a926a-1807-4d51-adca-a2f8f6a05615

**Comment by danieldoglas** [comment] 2024-02-06 11:37
Hm, I don't think this needs to be a deploy blocker. But if it's not happening in production, we need to find the offending PR. @aimane-chnaif , can you please help out with that?

**Comment by danieldoglas** [comment] 2024-02-06 11:48
I do agree that this sounds like an improvement, but if it doesn't happen in production, we need to find out what changed this and if it was intentional

**Comment by BartoszGrajdek** [comment] 2024-02-06 12:49
Hi! I'm the author of https://github.com/Expensify/App/pull/35062 which is the root cause of this. 

I have recently found a new bug happening whenever there was a money report with currencies different than the money report itself. User could add money requests with various currencies to the money report while being offline and click "Pay elsewhere" immediately, this is a bug because the total amount wouldn't be updated in the meantime (it can only come from the backend after we convert currencies, so the user needs to be online for that to happen), since the total amount isn't updated user can't be actually certain on what amount he should pay.

Now my solution was to add a condition whenever there are both transactions with pending fields and there's a transaction using currency different than the money report itself to prevent the user from paying for money report until everything gets updated.

I'm not sure how you would like to proceed from here, I agree that we could add some UX improvements, but I don't think that it's a bug.

**Comment by BartoszGrajdek** [comment] 2024-02-06 12:57
I think that an alternative solution would be to change the opacity of the total amount on the report preview as well signifying that it's being calculated, this would be consistent with how we handled it inside the money report itself

**Comment by danieldoglas** [comment] 2024-02-06 13:45
Thanks for the context @BartoszGrajdek and @aimane-chnaif 

@johnmlee101 @pecanoro looks like you were both assigned to review the original PR. I'm happy to leave this as is - though we may need to update the message. What do you think?

**Comment by pecanoro** [comment] 2024-02-06 15:14
@johnmlee101 has better context, I simply left a comment in the PR but I wasn't assigned so I don't have an opinion about what we should do.

**Comment by johnmlee101** [comment] 2024-02-06 16:49
Does the delay change based off of network speeds?

**Comment by johnmlee101** [comment] 2024-02-07 16:01
Yeah I think the pattern is _fine_ for now then. If we find that its causing confusion in the future then we can bring this back to think about UX improvements

**Comment by garrettmknight** [comment] 2024-02-08 15:05
@tienifr that sounds like a different problem altogether. I was just testing it and it looks like the buttons are greyed out when offline, but I was able to submit and expense/approve it on a Collect workspace + pay one on a Free workspace.

**Comment by danieldoglas** [comment] 2024-02-12 09:44
@garrettmknight so you think we should leave this as is for now, or still change the text?

**Comment by garrettmknight** [comment] 2024-02-23 18:35
Holding on https://github.com/Expensify/App/issues/36440

**Comment by danieldoglas** [comment] 2024-03-04 12:07
still on hold

**Comment by garrettmknight** [comment] 2024-03-05 20:10
Holding on https://github.com/Expensify/App/issues/36440

**Comment by garrettmknight** [comment] 2024-03-14 21:30
Moving to dailty to test tomorrow.

**Comment by garrettmknight** [comment] 2024-03-14 21:34
Tested, still getting the greyed out part happening.

**Comment by garrettmknight** [comment] 2024-03-14 21:39
@tienifr does your prososal still stand?

**Closed** 2024-03-15 12:51 UTC
Labels: External, Engineering, Daily, Help Wanted, Bug
