### ISSUE TITLE
[$1000] Workspace - No workspace available when signing in from a user with only one workspace

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#28564] opened 2023-10-01 17:01 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:

1. Create a very new account
2. Create a workspace
3. Signout and signin again
4. Observe that workspace is not displayed.

~1. Open App and login using the Apple ID (tap the Apple icon)~
~2. Click Continue for all the prompts~
~3. Navigate to Settings -> Workspaces (Make a few workspaces)~
~4. Sign out~
~5. Sign in with Apple ID and Navigate to Settings -> Workspaces (notice a workspace is deleted)~

~Note: WS is gone~

~6. Close the app (put app into background)~
~7. Open app again~

~Note: WS is visible.~

## Expected Result:
List of workspaces should appear if available

## Actual Result:
List of workspaces does not appear

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android / native
- [x] Android / Chrome
- [x] iOS / native
- [x] iOS / Safari
- [x] MacOS / Chrome / Safari
- [x] MacOS / Desktop

**Version Number:** 1.3.75.8
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/93399543/7f06b51b-a535-4f16-aa83-8c3bf92eca81

https://github.com/Expensify/App/assets/93399543/de13a5b4-2192-46fc-bb93-aee941eb985e

https://github.com/Expensify/App/assets/93399543/468f1e4e-6391-4d59-98f4-141995bc261b

https://github.com/Expensify/App/assets/93399543/d67b189b-96ef-436d-b80f-2b6a1a22a1b1

https://github.com/Expensify/App/assets/93399543/ffa1fbda-932c-4583-874e-e7ce69a8a3cc

https://github.com/Expensify/App/assets/93399543/fddcc2eb-3f9b-411a-9015-12e08380847e

![Image from iOS (1) (1)](https://github.com/Expensify/App/assets/93399543/7ceda54c-c226-46c6-9e72-47e50d37d524)

**Expensify/Expensify Issue URL:**
**Issue reported by:** @ufumerfarooq
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1696001301025309

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01f132917068b6c5f3</li>
        <li>Upwork Job ID: 1708527646262095872</li>
        <li>Last Price Increase: 2023-10-12</li>
    </ul>
</details>

**Comment by Christinadobrzyn** [comment] 2023-10-02 17:44
i can reproduce - this might need to be Internal since it's related to Apple. What do you think @0xmiroslav (internal or external)?

**Comment by MonilBhavsar** [comment] 2023-10-04 13:41
Hmm, I'm not able to reproduce this issue. I might be missing something here?

**Comment by ufumerfarooq** [comment] 2023-10-04 13:55
@MonilBhavsar you need to use "Apple Signin" because it's still reproducible

**Comment by ufumerfarooq** [comment] 2023-10-04 14:12
@MonilBhavsar  Retested these 2 scenarios:
**Scenario 1: Tested using old account**
Note: Email was hidden by "Hide my email" apple feature and it's reproducible.

**Scenario 2: Create a new account**
 Note: Hide my email was disabled for this account and the issue is still reproducible

My views: This issue is not with the "Hide my email" feature. It's something else
Videos are attached in Slack conversation: https://expensify.slack.com/archives/C049HHMV9SM/p1696001301025309

**Comment by MonilBhavsar** [comment] 2023-10-04 14:19
Still no dice for me.
Had a look at the logs and nothing sus.
@Christinadobrzyn could you please retest and confirm

**Comment by Christinadobrzyn** [comment] 2023-10-04 15:19
I'm not able to reproduce anymore either. Following the steps in the OP - I signed in through Apple ID > created a workspace > signed out > signed back in and the workspace exists. 


![2023-10-04_09-10-09 (3)](https://github.com/Expensify/App/assets/51066321/dcadde09-fb0b-4522-bb2e-ae72f76a122b)

This also seems to be the same behaviour as in this video in slack - https://expensify.slack.com/archives/C049HHMV9SM/p1696430345182549?thread_ts=1696001301.025309&cid=C049HHMV9SM

So if there's something else happening, I think that is a new bug report - this bug report doesn't seem to be happening anymore.

**Comment by MonilBhavsar** [comment] 2023-10-04 15:36
Thanks for confirming! @kbecciv is QA team able to reproduce this?
We need to update bug report if we're missing something or we can close this if we're not able to reproduce

**Comment by Christinadobrzyn** [comment] 2023-10-04 15:43
I'll ask QA to test, good thinking!

**Comment by kbecciv** [comment] 2023-10-04 15:58
@Christinadobrzyn  Workspace is unavailable after re-logging, but it reappears after close and reopen the app. Please check video. Thank you


https://github.com/Expensify/App/assets/93399543/21da7717-15c5-48e1-8f6b-bb57fbc8c2cb

**Comment by Christinadobrzyn** [comment] 2023-10-05 20:44
Yes, this is still happening @MonilBhavsar. Seems to only be happening on IOS. I updated the steps in the OP to reproduce. can you try to reproduce again?

**Comment by MonilBhavsar** [comment] 2023-10-06 05:52
I will try on iOS, thanks!

**Comment by MonilBhavsar** [comment] 2023-10-06 12:34
Okay, I captured the occurrence and most probably the issue...

**Comment by MonilBhavsar** [comment] 2023-10-06 13:18
This is issue in general, and not related to Apple signin at all. Will update the title

**Comment by MonilBhavsar** [comment] 2023-10-06 14:00
This issue can be worked externally!
The server returns required data in server response when calling `OpenApp`.
1. A collection of policies - `mergeCollection` Onyx method
2. An activate policy update - `merge` Onyx method
 
 
 Looks like we're somehow not applying the first Onyx update in the storage and only apply the second update.
 We'll need to investigate if it's issue with Onyx. The code lies in react-native-onyx repo https://github.com/Expensify/react-native-onyx/

**Comment by Christinadobrzyn** [comment] 2023-10-06 17:47
Thank you so much for all the testing @MonilBhavsar!

**Comment by MonilBhavsar** [comment] 2023-10-09 08:21
Disagree to above message from Melvin since External label was applied on Friday! cc @Christinadobrzyn 
Waiting on proposals...

**Comment by MonilBhavsar** [comment] 2023-10-09 09:39
Melvin, I updated above 😕

**Comment by Christinadobrzyn** [comment] 2023-10-10 18:15
waiting on proposals!

**Comment by Christinadobrzyn** [comment] 2023-10-12 20:20
increase the price to get some proposals

**Comment by MonilBhavsar** [comment] 2023-10-13 08:16
I'll post in expert contributors group considering a critical issue and might be affecting other flows of the app

**Comment by paultsimura** [comment] 2023-10-13 08:39
Seems like the RCA is the same as here: https://github.com/Expensify/App/issues/28737

In the `OpenApp` API response, we have 2 operations related to the newly created collection:
```json
{
            "onyxMethod": "mergecollection",
            "key": "policy_",
            "value": {
                "policy_7D84B7F95450B5C8": {
                    "isFromFullPolicy": false,
                    "id": "7D84B7F95450B5C8",
                    "name": "Paultsimura+ws5's Workspace",
                    "role": "admin",
                    "type": "free",
                    "owner": "paultsimura+ws5@gmail.com",
                    "outputCurrency": "PLN",
                    "avatar": "",
                    "employeeList": [],
                    "isPolicyExpenseChatEnabled": true,
                    "areChatRoomsEnabled": true,
                    "lastModified": 1697185648456091
                },
            }
        },
        {
            "onyxMethod": "merge",
            "key": "policy_7D84B7F95450B5C8",
            "value": {
                "autoReporting": true,
                "autoReportingFrequency": "immediate",
                "defaultBillable": false,
                "disabledFields": {
                    "defaultBillable": true,
                    "reimbursable": false
                }
            }
        },
```

After this response is processed, in Onyx the policy contains only the data from the `merge` operation, the `mergecollection` is neglected:

<img width="1398" alt="image" src="https://github.com/Expensify/App/assets/12595293/2cf83891-bff4-4c35-905f-e8a55adb0457">

@Julesssss @ospfranco you might be interested ☝️

**Comment by MonilBhavsar** [comment] 2023-10-13 08:47
Looks like this is fixed now. I am not able to reproduce

**Comment by paultsimura** [comment] 2023-10-13 08:52
@MonilBhavsar reproduced just now:
<img width="1512" alt="image" src="https://github.com/Expensify/App/assets/12595293/95ad75b1-b731-497d-9d22-95ddeb13d431">

**Comment by MonilBhavsar** [comment] 2023-10-13 09:26
I'm not able to reproduce on latest main either 🤔

**Comment by MonilBhavsar** [comment] 2023-10-16 05:46
@Christinadobrzyn are you still able to reproduce this issue? I am not able to reproduce. I believe it's fixed. cc @0xmiroslav

**Comment by mvtglobally** [comment] 2023-10-17 15:17
Issue not reproducible during KI retests. (First week)

**Closed** 2023-10-18 15:01 UTC
Labels: External, Engineering, Daily, Help Wanted, Overdue, Bug
