### ISSUE TITLE
[$2000]  Scan IOU - Unable to upload attachments in the app once Scan IOU is created

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#26700] opened 2023-09-04 17:51 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Launch New Expensify app
2. Upload an attachment in any DM
3. Create a money request via Scan in the same DM
4. Upload the same attachment (as step 2) in the same DM

## Expected Result:
Attachment is uploaded successfully in each step

## Actual Result:
Once a money request via Scan is made, the app is unable to upload attachments. It shows 'Uploading attachment' infinitely

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [ ] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 1.3.63-0

**Reproducible in staging?:** Yes

**Reproducible in production?:** Yes

**If this was caught during regression testing, add the test name, ID and link from TestRail:**

**Email or phone of affected tester (no customers):**

**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/78819774/dfc227cc-bf4c-40dd-9100-d182de324877

**Expensify/Expensify Issue URL:**

**Issue reported by:** Applause - Internal Team

**Slack conversation:**

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01a6040e44a9465938</li>
        <li>Upwork Job ID: 1699001560239366144</li>
        <li>Last Price Increase: 2023-09-27</li>
    </ul>
</details>

**Comment by conorpendergrast** [comment] 2023-09-11 08:23
I'm on parental leave; re-assigning! This has been triaged and is waiting for proposals.

**Comment by michaelhaxhiu** [comment] 2023-09-20 16:02
Doubled 👍

**Comment by michaelhaxhiu** [comment] 2023-09-27 14:40
This isn't getting much attention, and it's close to breaking WAQ goals. I'm doubling price again!

**Comment by michaelhaxhiu** [comment] 2023-09-27 14:41
I'm also re-assigning to another BZ as I'm preparing for sabbatical this Friday. In terms of **next steps**:

- Price was just doubled, so this should hopefully get more attention.
- If no interest still, I recommend posting in #bug-zero or #product to get input from an engineer on how to best guide it forward.

**Comment by s-alves10** [comment] 2023-09-28 11:23
## Proposal

### Please re-state the problem that we are trying to solve in this issue.

Unable to upload attachment after money request with receipt is sent

### What is the root cause of that problem?

We send money request using [requestMoney](https://github.com/Expensify/App/blob/67d4a7acebf613dc8fac9fd1423a7a23d1583e59/src/libs/actions/IOU.js#L818) function. This function takes `receipt` parameter and this parameter has `File` object value when scan IOU request is sent

We get this `File` object using `readFileAsync` function as you can see below
https://github.com/Expensify/App/blob/67d4a7acebf613dc8fac9fd1423a7a23d1583e59/src/pages/iou/steps/MoneyRequestConfirmPage.js#L220-L224

But this function returns the data like below on Android
```
    {
        "_data": {
            "blobId": "82595bbe-aa9c-46a2-8e9d-24e26b2a7138",
            "offset": 0,
            "size": 129506,
            "type": "",
            "lastModified": 1695789767569,
            "__collector": {},
            "name": "rn_image_picker_lib_temp_a411b1cf-b723-4015-8a82-cb64f5322f65.png"
        },
        "source": "file:///data/user/0/com.expensify.chat.dev/cache/rn_image_picker_lib_temp_a411b1cf-b723-4015-8a82-cb64f5322f65.png",
        "uri": "file:///data/user/0/com.expensify.chat.dev/cache/rn_image_picker_lib_temp_a411b1cf-b723-4015-8a82-cb64f5322f65.png",
        "state": "SCANREADY"
    }
```

As you can see, we don't set `type` of the image. This looks working on other platforms, but doesn't work on Android. Please refer below links
https://github.com/jaydenseric/apollo-upload-client/issues/109#issuecomment-546930120
https://github.com/jaydenseric/apollo-upload-client/issues/109#issuecomment-645787227

This makes the `requestMoney` API call fail

This is the root cause

### What changes do you think we should make in order to solve the problem?

We need to set correct mime type for the image
Replace the below code
https://github.com/Expensify/App/blob/632de144dd97255da24b673087c3c38c9a4065d4/src/libs/fileDownload/FileUtils.js#L160

with 
```
        const file = new File([blob], cleanFileName(fileName), {type: blob.type});
```

This works as expected

**Note**: This would solve several issues because they have the same root cause
https://github.com/Expensify/App/issues/27048


<details>
    <summary>Result</summary>


https://github.com/Expensify/App/assets/126839717/f5d1bb8b-9834-497b-bc65-f28b03cb0f46


</details>


### What alternative solutions did you explore? (Optional)

**Comment by alexpensify** [comment] 2023-09-29 06:13
@aimane-chnaif - can you please review if this proposal will resolve this issue? Thanks!

**Comment by pradeepmdk** [comment] 2023-09-30 13:43
I think same RCA and solution opened the PR here 
https://github.com/Expensify/App/issues/26940#issuecomment-1740445802
https://github.com/Expensify/App/pull/28533/files

**Comment by shubham1206agra** [comment] 2023-09-30 14:02
> I think same RCA and solution opened the PR here [#26940 (comment)](https://github.com/Expensify/App/issues/26940#issuecomment-1740445802) https://github.com/Expensify/App/pull/28533/files

Oh
This problem is more widespread than I thought.
@pradeepmdk Thanks for pointing out

**Comment by s-alves10** [comment] 2023-10-02 07:15
@pradeepmdk @s77rt @shubham1206agra 

I posted the proposal before @shubham1206agra 's posting. It has the same root cause and have exactly the same solution.
I'm not sure why this was assigned to other contributor. I spent a lot of time to solve the issue as you can see from my proposal

I hope the clear procedure to find the proper contributor for an issue. Do I need to open a slack discussion?

cc @aimane-chnaif

**Comment by shubham1206agra** [comment] 2023-10-02 07:24
> @pradeepmdk @s77rt @shubham1206agra
> 
> I posted the proposal before @shubham1206agra 's posting. It has the same root cause and have exactly the same solution. I'm not sure why this was assigned to other contributor. I spent a lot of time to solve the issue as you can see from my proposal
> 
> I hope the clear procedure to find the proper contributor for an issue. Do I need to open a slack discussion?
> 
> cc @aimane-chnaif

That's happened because neither @s77rt nor I knew this proposal before @pradeepmdk mentioned it. But that's after I got assigned the issue (which is a different one) and completed my end of work on the PR. If anyone had mentioned the duplicity of the RCA and solution, yours would be preferred, and I wouldn't posted that solution (which I also worked with a lot of time).

As the procedure says, that first come, first serve on the same issue. If I had been assigned this issue, I think your complaint would be valid. However, since I have no prior knowledge of this issue, I don't know what to say.

But the PR is now merged.

I hope you understand.

**Comment by shubham1206agra** [comment] 2023-10-02 09:03
> This is edge case. As the PR was merged already, it shouldn't affect bounty for @shubham1206agra. This is what I suggest: @shubham1206agra will get paid full amount (1k + 0.5k speed bonus) in the [linked issue](https://github.com/Expensify/App/issues/26940) which is issue price. And this one has doubled bounty so apply equal payment here (1.5k). This way, total amount will keep the same.

This works for me.

But I think we should have a defining procedure for this case for future reference. Can you open a slack discussion of the same?

**Comment by s-alves10** [comment] 2023-10-02 14:44
I agree with @aimane-chnaif

**Comment by s-alves10** [comment] 2023-10-03 01:17
@aimane-chnaif 

What should I do here?

**Comment by madmax330** [comment] 2023-10-03 12:08
I brought this up internally, we decided that we should just close this one. It is unfortunate that there were duplicate RCAs for both issues, but since both @shubham1206agra and @s77rt didn't about your proposal they solved their issue following the process it would be unfair to revoke anything from them. 
Ideally we would have caught the duplicate and seen your proposal, but since they solved their issue which coincidentally solved this one, there's nothing left to do on this issue.

**Closed by madmax330** 2023-10-03 12:08 UTC
Labels: Engineering, Daily, Internal, Bug
