### ISSUE TITLE
[HOLD for payment 2024-06-11] [$250] [Uneven Splits] [Polish] Android - Split amount input does not animate smoothly

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#41751] opened 2024-05-07 12:28 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.71-0
**Reproducible in staging?:** Y
**Reproducible in production?:** N
**If this was caught during regression testing, add the test name, ID and link from TestRail:** N/A
**Issue reported by:** Applause - Internal Team

## Action Performed:
1. Launch New Expensify app
2. Go to FAB > Split expense
3. Enter amount > Next
4. Select a few users > Next

## Expected Result:
The amount input with currency will animate smoothly

## Actual Result:
The amount input with currency does not animate smoothly. It appears digit by digit

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [ ] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details> 

https://github.com/Expensify/App/assets/78819774/cd6b5712-cda8-4172-bde0-6c07624f1764

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~0166f91b00117784b4</li>
        <li>Upwork Job ID: 1787910960853864448</li>
        <li>Last Price Increase: 2024-05-14</li>
<li>Automatic offers: </li>
<ul>
<li>abdulrahuman5196 | Reviewer | 0</li>
<li>bernhardoj | Contributor | 0</li>
</ul></li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @CortneyOfstad</details>

**Comment by lanitochka17** [comment] 2024-05-07 12:29
@dangrous  FYI I haven't added the External label as I wasn't 100% sure about this issue. Please take a look and add the label if you agree it's a bug and can be handled by external contributors

**Comment by dangrous** [comment] 2024-05-07 15:02
Hm actually, I'm not able to replicate this on local, or on staging - it seems fine to me? Do you mind testing this one more time, when you have a moment? It might have been a temporary thing.

**Comment by marcaaron** [comment] 2024-05-07 17:37
This looks pretty minor. Maybe we can just remove the blocker and assign it to @youssef-lr?

**Comment by marcaaron** [comment] 2024-05-07 17:37
Seems related to https://github.com/Expensify/App/pull/40386

**Comment by youssef-lr** [comment] 2024-05-07 18:22
Yes we were aware of this and decided to work on it past release. We can open this up for contributors.

**Comment by CortneyOfstad** [comment] 2024-05-07 18:38
Working with @slafortune to retest this as she has an Android 👍

**Comment by bernhardoj** [comment] 2024-05-08 04:58
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
The split amount in the confirmation page shows the input part by part.

### What is the root cause of that problem?
The amount input has `autoGrow` on. `autoGrow` will set the width based on the `textInputWidth` state. As you can see the initial value is 0.
https://github.com/Expensify/App/blob/55c56bffbee8afd2fb5f5b2abfe30a92487bab52/src/components/TextInput/BaseTextInput/index.native.tsx#L89
https://github.com/Expensify/App/blob/55c56bffbee8afd2fb5f5b2abfe30a92487bab52/src/components/TextInput/BaseTextInput/index.native.tsx#L254

And it will be updated here.
https://github.com/Expensify/App/blob/55c56bffbee8afd2fb5f5b2abfe30a92487bab52/src/components/TextInput/BaseTextInput/index.native.tsx#L431-L435

So, it takes time to get the correct width. It happens on iOS too, just faster.

If we read the confirmation page amount code, we can see that we want to have a fixed width for the input.
https://github.com/Expensify/App/blob/55c56bffbee8afd2fb5f5b2abfe30a92487bab52/src/components/MoneyRequestConfirmationList.tsx#L488-L500

However, it won't work correctly because
1. `autoGrow` is still on.
2. We didn't pass the container style that contains the container width to the input
https://github.com/Expensify/App/blob/55c56bffbee8afd2fb5f5b2abfe30a92487bab52/src/components/OptionRow.tsx#L267-L271

### What changes do you think we should make in order to solve the problem?

Pass `autoGrow` as `false` to MoneyRequestAmountInput > TextInputWithCurrencySymbol > AmountTextInput. Then, pass the container style here.
https://github.com/Expensify/App/blob/55c56bffbee8afd2fb5f5b2abfe30a92487bab52/src/components/OptionRow.tsx#L267

```
containerStyle={[styles.textInputContainer, option.amountInputProps.containerStyle]}
```

### What alternative solutions did you explore? (Optional)
Pass a new prop called `initialInputWidth` and set it as the initial value of `textInputWidth`. 
https://github.com/Expensify/App/blob/55c56bffbee8afd2fb5f5b2abfe30a92487bab52/src/components/TextInput/BaseTextInput/index.native.tsx#L89

The `initialInputWidth` value will be the `amountWidth` here.
https://github.com/Expensify/App/blob/55c56bffbee8afd2fb5f5b2abfe30a92487bab52/src/components/MoneyRequestConfirmationList.tsx#L489

**Comment by youssef-lr** [comment] 2024-05-08 05:51
@bernhardoj any chance we can remove the fixed width implementation AND use autogrow without any flickers? ideally we want something like this that works smoothly in native:

https://github.com/Expensify/App/assets/9680864/35897f3d-9b02-4109-a186-5d7fb11a512c

I've had the implementation above before but it doesn't look good on native https://github.com/Expensify/App/pull/40386#issuecomment-2082402549

**Comment by CortneyOfstad** [comment] 2024-05-10 15:55
@bernhardoj update on @youssef-lr's question above ^^^ Thanks!

**Comment by bernhardoj** [comment] 2024-05-11 03:03
Let me try it.

**Comment by bernhardoj** [comment] 2024-05-13 07:30
@youssef-lr I can't find a way to remove the flickers. The amount text is updated before the input width state is updated from this invisible text.
https://github.com/Expensify/App/blob/2e6e8ca5160d928d59b77f9482f1418253634dce/src/components/TextInput/BaseTextInput/index.native.tsx#L424-L436

1. Type something
2. The text doesn't fit into the current width
3. The invisible text onLayout is triggered to update the new text width

The best that I could come up with is to add an extra width. But still, it won't work well if we type many amount quickly.

https://github.com/Expensify/App/assets/50919443/7dd11096-06b4-4d1b-a6f7-363d6cbc6ab2

**Comment by youssef-lr** [comment] 2024-05-15 01:50
Yup I tried as well with no luck, I think it's a limitation of RN.

**Comment by youssef-lr** [comment] 2024-05-15 01:52
Woops I didn't realize this isn't C+ approved yet. @abdulrahuman5196 can you check the proposal please? For me it makes sense.

**Comment by youssef-lr** [comment] 2024-05-15 18:04
@bernhardoj feel free to raise a PR

**Comment by bernhardoj** [comment] 2024-05-16 06:06
PR is ready

cc: @abdulrahuman5196

**Comment by CortneyOfstad** [comment] 2024-05-20 15:25
We're in a merge freeze until Wednesday, so this will be delayed 👍

**Comment by CortneyOfstad** [comment] 2024-05-22 15:17
Merge freeze is planned to end today 🤞

**Comment by marcaaron** [comment] 2024-05-23 00:44
[This post](https://expensify.slack.com/archives/C03SC9DVD/p1716401628660839) has the current merge freeze info. I believe we are still only merging PRs with discretion.

**Comment by CortneyOfstad** [comment] 2024-06-05 16:59
@abdulrahuman5196 can you complete the checklist when you have a chance so there is no delay in payment? Thanks!

**Comment by CortneyOfstad** [comment] 2024-06-10 14:43
@abdulrahuman5196 can you please provide an update on the checklist by EOD? Thanks!

**Comment by abdulrahuman5196** [comment] 2024-06-10 15:25
>The PR that introduced the bug has been identified. Link to the PR:
The offending PR has been commented on, pointing out the bug it caused and why, so the author and reviewers can learn from the mistake. Link to comment:
A discussion in #expensify-bugs has been started about whether any other steps should be taken (e.g. updating the PR review checklist) in order to catch this type of bug sooner. Link to discussion:

https://github.com/Expensify/App/pull/40386#issuecomment-2158651223

>Determine if we should create a regression test for this bug.

Yes.

>If we decide to create a regression test for the bug, please propose the regression test steps to ensure the same bug will not reach production again.

1) Open split bill from FAB and enter any amount
2) Select any user participant and press next
3) In the confirm page, verify the split input shows without delay

@CortneyOfstad

**Closed** 2024-06-11 15:40 UTC
Labels: External, Engineering, Daily, Awaiting Payment, Bug
