### ISSUE TITLE
[HOLD for payment 2023-08-03] [$1000] mWeb - Cannot set focus on draft message on iOS safari

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#23451] opened 2023-07-23 20:55 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Login with any account and go to any chat
2. Send two messages A and B
3. Edit message A(don't save or close)
4. Edit message B(don't save or close)
5. Touch on draft A

## Expected Result:
A should be focused

## Actual Result:
Nothing happens

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [x] iOS / Safari
- [ ] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 1.3.44-0
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/93399543/23c5bc5a-9658-4d98-83a2-6dba900a68fd

https://github.com/Expensify/App/assets/93399543/2f522131-dc0e-4a0e-bce9-92c4b782a01f

**Expensify/Expensify Issue URL:**
**Issue reported by:** @s-alves10 
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1689976646500919

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01b263c9f210b550ff</li>
        <li>Upwork Job ID: 1683590098125062144</li>
        <li>Last Price Increase: 2023-07-24</li>
<li>Automatic offers: </li>
<ul>
<li>s-alves10 | Reporter | 25908943</li>
</ul></li>
    </ul>
</details>

**Comment by s-alves10** [comment] 2023-07-24 03:14
This issue is a regression of this [PR](https://github.com/Expensify/App/pull/22443)

**Comment by joekaufmanexpensify** [comment] 2023-07-24 21:28
Reproduced on my end.

**Comment by joekaufmanexpensify** [comment] 2023-07-24 21:29
cc @Santhosh-Sellavel @thesahindia curious if you agree this is a regression?

**Comment by Santhosh-Sellavel** [comment] 2023-07-24 21:43
@joekaufmanexpensify Yes reverting [that](https://github.com/Expensify/App/pull/22443) fixes the issue, it's a regression!

**Comment by joekaufmanexpensify** [comment] 2023-07-24 21:47
Got it. And this would be the second regression from that issue, right?

**Comment by Santhosh-Sellavel** [comment] 2023-07-24 21:57
Yes

**Comment by Santhosh-Sellavel** [comment] 2023-07-24 21:57
Let's remove help wanted here @joekaufmanexpensify

**Comment by joekaufmanexpensify** [comment] 2023-07-24 22:02
Done! Commented in the other issue as well.

**Comment by joekaufmanexpensify** [comment] 2023-07-31 13:26
@Santhosh-Sellavel Could you please complete your portion of the BZ checklist here when you have a sec?

**Comment by Santhosh-Sellavel** [comment] 2023-08-02 17:07
@thesahindia please take care as this is a regression from this https://github.com/Expensify/App/pull/22443

**Comment by aldo-expensify** [comment] 2023-08-02 17:19
oops, @thesahindia is not a contributor, I'm adding him to take care of the bug-zero checklist: https://github.com/Expensify/App/issues/23451#issuecomment-1654611771

**Comment by Santhosh-Sellavel** [comment] 2023-08-02 17:27
As it says in the message for reporting the  bug!

**Comment by aldo-expensify** [comment] 2023-08-02 17:50
> As it says in the message for reporting the bug!

Oh, I missed that, my bad :P

**Comment by joekaufmanexpensify** [comment] 2023-08-03 21:49
@thesahindia could you please complete the rest of the BZ checklist here when you have a sec? Thanks!

**Comment by joekaufmanexpensify** [comment] 2023-08-03 21:51
Since this was just reverting a regression, I think all we need to do is pay the $250 reporting bonus. 

cc @Santhosh-Sellavel I don't see that you reviewed anything here, so thinking no payment is due, but LMK if that is different than your expectation!

**Comment by Santhosh-Sellavel** [comment] 2023-08-03 21:57
Right only reporting bonus!

**Comment by joekaufmanexpensify** [comment] 2023-08-03 22:01
Cool cool, ty!

**Comment by s-alves10** [comment] 2023-08-04 16:26
@joekaufmanexpensify 

Can I get paid as a reporter?

**Comment by joekaufmanexpensify** [comment] 2023-08-04 19:05
@s-alves10 We need to make sure the BZ checklist is complete before issuing payment. As soon as it is, I'll issue your payment!

**Comment by joekaufmanexpensify** [comment] 2023-08-07 12:46
All set to issue payment.

**Comment by joekaufmanexpensify** [comment] 2023-08-07 12:46
@s-alves10 $250 sent and contract ended!

**Comment by joekaufmanexpensify** [comment] 2023-08-07 12:47
Upwork job closed.

**Comment by joekaufmanexpensify** [comment] 2023-08-07 12:47
Bug is fixed, BZ checklist complete, and all payment issued. Closing as this is all set. Thanks everyone!

**Closed by joekaufmanexpensify** 2023-08-07 12:47 UTC
Labels: External, Daily, Awaiting Payment, Bug
