### ISSUE TITLE
[$125] mWeb - Chat - Text selection on chat, can still be seen through context menu

### ISSUE THREAD

**Issue by IuliiaHerets** [Expensify/App#53353] opened 2024-12-01 10:44 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 9.0.69-1
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**Email or phone of affected tester (no customers):** ibellicotest+57@gmail.com
**Issue reported by:** Applause Internal Team

## Action Performed:
1. Open the staging.new.expensify.com website.
2. Open any chat.
3. Long tap on any word on chat description to select it.
4. Long tap on the first message of chat.
5. Verify that context menu is opened and that the selection can´t be seen through it.

## Expected Result:
Selection made in chat, shouldn´t be visible when context menu is opened.

## Actual Result:
When context menu is opened after selecting text in chat, the selection can still be seen through it.

## Workaround:
Unknown

## Platforms:

- [ ] Android: Standalone
- [ ] Android: HybridApp
- [x] Android: mWeb Chrome
- [ ] iOS: Standalone
- [ ] iOS: HybridApp
- [ ] iOS: mWeb Safari
- [ ] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

https://github.com/user-attachments/assets/3eb239de-02d9-4659-b8e0-a43a767cd776
  
</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~021864114795126521666</li>
        <li>Upwork Job ID: 1864114795126521666</li>
        <li>Last Price Increase: 2024-12-11</li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @sobitneupane</details>

**Comment by twisterdotcom** [comment] 2024-12-04 01:09
Very niche.

**Comment by sobitneupane** [comment] 2024-12-05 12:02
Thanks for the [proposal](https://github.com/Expensify/App/issues/53353#issuecomment-2510671607), @daledah.

I believe the issue is not limited to the specific case mentioned in the report; it can be reproduced throughout the app. However, it is not something that users frequently or easily encounter.

We previously attempted to address a [similar issue](https://github.com/Expensify/App/issues/41197) in a similar manner but ended up closing it due to regressions and the niche nature of the problem.

I don’t think implementing the suggested change is a good idea, as there may be scenarios where retaining the selection is necessary. Moreover, the proposed change seems prone to regression.

**Comment by twisterdotcom** [comment] 2024-12-17 17:58
This has been open for 2 weeks with no good proposal. Given how niche it is, I'm gonna close.

**Closed** 2024-12-17 17:58 UTC
Labels: External, Weekly, Help Wanted, Overdue, Not a priority, Bug
