### ISSUE TITLE
[$250]  Request money - Scan report detail screen is not scrollable on small screen

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#29555] opened 2023-10-13 12:38 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.3.83.10

**Reproducible in staging?:** Yes

**Reproducible in production?:** No

**If this was caught during regression testing, add the test name, ID and link from TestRail:**

**Email or phone of affected tester (no customers):**

**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Expensify/Expensify Issue URL:**

**Issue reported by:** Applause - Internal Team / @aman-atg 

**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1697145768795909

## Action Performed:
Precondition: Use small screen iPhone device (iPhone 6s)
1. Login to New Expensify app
2. Tap FAB
3. Select Request money > Scan tab
4. Split Bill with two accounts
5. Tap Split button on confirmation page
6. Tap on created IOU report
7. Try to scroll through the page

## Expected Result:
Detail IOU report fiields should be scrollable so user can navigate to Description, Date and Merchant sections

## Actual Result:
Scan report detail screen is not scrollable on small screen
This bug occurs when Receipt scan is in progress and also when completed

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [ ] Android: mWeb Chrome
- [x] iOS: Native
- [ ] iOS: mWeb Safari
- [ ] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos
<details>
<summary>Android: Native</summary>

</details>

<details>
<summary>Android: mWeb Chrome</summary>

</details>

<details>
<summary>iOS: Native</summary>

 

https://github.com/Expensify/App/assets/78819774/5c7a9f3f-bacf-4e8e-93ee-916b84b65df3

</details>

<details>
<summary>iOS: mWeb Safari</summary>

</details>

<details>
<summary>MacOS: Chrome / Safari</summary>

</details>

<details>
<summary>MacOS: Desktop</summary>

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01d54d1098c90181f8</li>
        <li>Upwork Job ID: 1712827802614779904</li>
        <li>Last Price Increase: 2023-10-20</li>
    </ul>
</details>

**Comment by Julesssss** [comment] 2023-10-13 13:46
I can reproduce this on Android too. However, I don't think it's bad enough to block the deploy so I'm going to remove the label.

**Comment by Julesssss** [comment] 2023-10-13 13:48
Android 

https://github.com/Expensify/App/assets/10736861/aede2cea-ec2e-4536-8be6-4e18a81cbbfa

**Comment by FitseTLT** [comment] 2023-10-13 22:35
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
Split bill detail page is not scrollable.
### What is the root cause of that problem?
The problem is that `MoneyRequestConfirmationList` inside `SplitBillDetailsPage` component is not inside a `ScrollView` which should have been as in `MoneyRequestConfirmPage` as indicated below.
https://github.com/Expensify/App/blob/6251e6584e4482d6616251a8193f554485d7ccba/src/pages/iou/steps/MoneyRequestConfirmPage.js#L340-L348
### What changes do you think we should make in order to solve the problem?

We need to insert `MoneyRequestConfirmationList` in `SplitBillDetailsPage` component inside a `ScrollView` as in `MoneyRequestConfirmPage`.
Change
https://github.com/Expensify/App/blob/6251e6584e4482d6616251a8193f554485d7ccba/src/pages/iou/SplitBillDetailsPage.js#L120-L123
to

`
  <ScrollView contentContainerStyle={[styles.flexGrow1]}>
                        {isScanning && <MoneyRequestHeaderStatusBar />}
                        {Boolean(participants.length) && (
                            <MoneyRequestConfirmationList
                                hasMultipleParticipants
`
Result:

https://github.com/Expensify/App/assets/38649957/239ea015-e6f2-4040-b24e-b111f6bd5574


### What alternative solutions did you explore? (Optional)

**Comment by FitseTLT** [comment] 2023-10-16 14:00
@Ollyws I don't think it is a regression because on the same `SplitBillDetailPage` scroll is not working with new.expensify.com. I mean, does it not mean the production?

https://github.com/Expensify/App/assets/38649957/a9a575df-8946-45fc-b043-8457f9103cc3

**Comment by FitseTLT** [comment] 2023-10-16 14:42
I checked out to a random commit (67f4f4c1537f409c54f304a6c291fde2b6ef2a33) from the production branch created on Oct 12 before the creation of this issue but the scroll still doesn't work.

**Comment by FitseTLT** [comment] 2023-10-17 13:42
Checked this bug on version 1.3.83.10 but it is reproducible. I think it is incorrect that it says No to `Reproducible in production` at that version.

**Comment by dylanexpensify** [comment] 2023-10-18 08:27
@Ollyws thoughts ^

**Comment by FitseTLT** [comment] 2023-10-18 11:10
> I can no longer reproduce this on the lastest main, @FitseTLT can you still reproduce this?

Yep it is fixed now.

**Comment by Julesssss** [comment] 2023-10-23 07:50
Closing as resolved

**Closed by Julesssss** 2023-10-23 07:50 UTC
Labels: External, Engineering, Daily, Help Wanted, Overdue, Bug
