### ISSUE TITLE
[$1000] Dev - Console log error displayed on clicking 'Select a workspace' dropdown value

### ISSUE THREAD

**Issue by kavimuru** [Expensify/App#23818] opened 2023-07-28 19:22 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
Precondition: account should have only one active workspace
1. Create a workspace & make sure you have only one active workspace
2. Click on 'FAB' menu ion
3. Click on 'New room'
4, Click on 'Workspace' dropdown menu
5. Click on 'Select a workspace' option
## Expected Result: 
There should be no console log error
## Actual Result: 
Console log error displayed [Cannot update a component (`Form`) while rendering a different component (`SafeAreaInsetsContext.Consumer`).]

## Workaround:
Can the user still use Expensify without this being fixed? Have you informed them of the workaround?

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [x] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** Dev
**Reproducible in staging?:** needs reproduction
**Reproducible in production?:** needs reproduction
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/43996225/ea483520-b7b6-4ede-8e92-5bd320ed3940

**Expensify/Expensify Issue URL:**
**Issue reported by:** @natnael-guchima
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1690464572048079

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01c6e4120bf877ce30</li>
        <li>Upwork Job ID: 1685980808192278528</li>
        2023-07-31<li>Automatic offers: </li>
<ul>
<li>natnael-guchima | Reporter | 25857396</li>
</ul></li>
    </ul>
</details>

**Comment by ygshbht** [comment] 2023-07-30 12:50
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
The issue at hand involves a console log error that appears when the 'Select a workspace' option in the 'Workspace' dropdown menu is clicked. This happens under the precondition that the account has only one active workspace. The expected outcome is that no console log error should be displayed during this process.

### What is the root cause of that problem?
Upon reviewing the console error and the associated code, the root cause of the problem appears to be tied to a state update operation that occurs during the rendering of a component. More specifically, the function that iterates over `inputRefs.current` and conditionally calls `setInputValues` is invoked during rendering, which leads to this error. This operation attempts to delete a reference and update the state while a component is rendering, which violates the rules of Hooks in React.

https://github.com/Expensify/App/blob/eb020063789091eb2e3086b5b54af3ead8436645/src/components/Form.js#L348-L362

### What changes do you think we should make in order to solve the problem?
To resolve this issue, the state update operation needs to be moved out of the rendering process. We can accomplish this by wrapping the operation in a `useEffect `hook. This hook ensures that the state update operation is invoked as a side effect after the component render, rather than during the render itself.

Here is how we can modify the function:

```
useEffect(() => {
    _.each(inputRefs.current, (inputRef, inputID) => {
        if (inputRef) {
            return;
        }

        setInputValues((prevState) => {
            const copyPrevState = _.clone(prevState);

            delete copyPrevState[inputID];

            return copyPrevState;
        });
    });
}, [/* same dependencies as the childrenWrapperWithProps function */]);
```


By making this modification, we should be able to eliminate the console log error.

Additionally, it may be possible to slightly optimize this code by moving the setInputValues function call outside of the _.each loop. However, this would require further investigation to ensure it doesn't introduce new issues or unexpected behavior.

**Comment by s-alves10** [comment] 2023-07-31 08:42
## Proposal

### Please re-state the problem that we are trying to solve in this issue.

Console error displayed When select `Select a workspace` in `New Room` page

### What is the root cause of that problem?

When we select `Select a workspace`, `Who can post` text input disappears and the following code is run
```
        setInputValues((prevState) => {
            const copyPrevState = _.clone(prevState);

            delete copyPrevState[inputID];

            return copyPrevState;
        });
```

This code is called during the render process. Setting state during the rendering should be avoided and leads to an unexpected result. In addition, calling the set function of another component during rendering is an error as described [here](https://react.dev/reference/react/useState#storing-information-from-previous-renders)

This is the root cause

### What changes do you think we should make in order to solve the problem?

In order to avoid this pattern, we can use `useEffect`. `useEffect` is the perfect location we can change state
Move the above code into the useEffect

```
    useEffect(() => {
        _.each(inputRefs.current, (inputRef, inputID) => {
            if (inputRef) {
                return;
            }

            delete inputRefs.current[inputID];

            setInputValues((prevState) => {
                const copyPrevState = _.clone(prevState);

                delete copyPrevState[inputID];

                return copyPrevState;
            });
        });

    }, [childrenWrapperWithProps]);
```
This works great

### What alternative solutions did you explore? (Optional)

**Comment by trjExpensify** [comment] 2023-07-31 11:48
Moving on `external` for input from C+ as a dev bug report.

**Comment by rezkiy37** [comment] 2023-07-31 12:32
Hi, I’m Michael (Mykhailo) from Callstack and I would like to work in this issue, because I am the author of the https://github.com/Expensify/App/pull/21950.

**Comment by Natnael-Guchima** [comment] 2023-07-31 13:51
Accepted the offer. Thanks.

**Comment by ygshbht** [comment] 2023-07-31 13:53
Hi, so a call stack member can propose anytime and they'll get the job?

**Comment by trjExpensify** [comment] 2023-07-31 14:20
My understanding is that it's specifically addressing a regression from the PR author that introduced it, and so it makes sense to "fix your work" in this case.

**Comment by ygshbht** [comment] 2023-07-31 14:22
So is he not going to get paid?

**Comment by trjExpensify** [comment] 2023-07-31 14:25
I don't think Expensify's financial arrangement with agencies we partner with are in scope of the discussion we're having here, Yogesh.

**Comment by ygshbht** [comment] 2023-07-31 14:36
Oh... makes sense. Apologies for the misunderstanding earlier

**Comment by rezkiy37** [comment] 2023-08-04 18:09
https://github.com/Expensify/App/pull/23919 was merged.

**Comment by rushatgabhane** [comment] 2023-08-14 18:47
created a manual request - https://staging.new.expensify.com/r/2106109152629952

**Comment by rushatgabhane** [comment] 2023-08-14 18:48
this issue can be closed i guess

**Comment by trjExpensify** [comment] 2023-08-15 12:03
We need to pay @Natnael-Guchima for the bug report right?

**Comment by trjExpensify** [comment] 2023-08-23 11:18
Okay, confirming payments: 

- $250 to @Natnael-Guchima for the bug report (paid)
- $1000 to @rushatgabhane for the c+ review (he wasn't the reviewer of the PR that caused the regression)

Closing this out!

**Closed by trjExpensify** 2023-08-23 11:18 UTC
Labels: Reviewing, External, Weekly, Bug

**Comment by JmillsExpensify** [comment] 2023-08-24 05:03
Reviewed the details for @rushatgabhane. Approved for $1k payment in NewDot based on the BZ confirmation summary above.
