### ISSUE TITLE
Workspace - Skeleton loader not displayed in workspace member page

### ISSUE THREAD

**Issue by izarutskaya** [Expensify/App#44604] opened 2024-06-28 10:29 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** v9.0.3-1
**Reproducible in staging?:** Y
**Reproducible in production?:** N
**Found when validating PR :** https://github.com/Expensify/App/pull/43893
**Email or phone of affected tester (no customers):** dave0123seife+stest@gmail.com
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Issue reported by:** Applause-Internal team

## Action Performed:
1. Open app.
2. Go to Account settings > workspace > member page
Notice that Skeleton loader is not displayed in workspace member page when data is loading

## Expected Result:
Skeleton loader is displayed in workspace member page when data is loading

## Actual Result:
Skeleton loader is not displayed in workspace member page when data is loading

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [x] Android: mWeb Chrome
- [ ] iOS: Native
- [x] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

https://github.com/Expensify/App/assets/115492554/21cfb55f-336a-4b5f-9854-943bbdde3361

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by izarutskaya** [comment] 2024-06-28 10:29
@jliexpensify I haven't added the External label as I wasn't 100% sure about this issue. Please take a look and add the label if you agree it's a bug and can be handled by external contributors.

**Comment by izarutskaya** [comment] 2024-06-28 10:30
Difference between stg and prod

https://github.com/Expensify/App/assets/115492554/bf2a2d65-dda7-427c-875c-e76208df8f29

**Comment by MariaHCD** [comment] 2024-06-28 11:57
Hmmm, so the skeleton view is implemented in https://github.com/Expensify/App/pull/43893

But it doesn't look like the PR is deployed to staging yet?

cc: @truph01 @jjcoffee @blimpich

**Comment by truph01** [comment] 2024-06-28 12:05
- I see that the [PR](https://github.com/Expensify/App/pull/43893) is not deployed to staging.

**Comment by MariaHCD** [comment] 2024-06-28 12:43
@izarutskaya did we test the [PR](https://github.com/Expensify/App/pull/43893) prematurely? 🤔

**Comment by Pujan92** [comment] 2024-06-28 13:39
It seems to be an automation issue bcoz the changes of that PR are reflected in the staging branch code.

<img width="1133" alt="Screenshot 2024-06-28 at 19 09 31" src="https://github.com/Expensify/App/assets/14358475/4443ff20-f928-4687-b4ef-4ca02060cafa">

**Comment by jjcoffee** [comment] 2024-06-28 14:15
Hmm so from my testing there is no issue on staging. The loader shows when the connection speed is throttled enough for it to show, exactly the same as on production. @izarutskaya Do you mind retesting with a throttled connection?

**Comment by blimpich** [comment] 2024-06-28 16:44
asked for retest [here](https://expensify.slack.com/archives/C9YU7BX5M/p1719593034708599)

**Comment by blimpich** [comment] 2024-06-28 16:44
Also I don't think this should block the deploy.

**Comment by jliexpensify** [comment] 2024-07-01 09:55
Hi, just moving to a Daily (I assume that's ok?)

**Comment by kbecciv** [comment] 2024-07-01 21:58
Issue is not reproduced on a slow network

https://github.com/Expensify/App/assets/93399543/8e45f475-b60b-490d-9ead-88f4912358cf

**Comment by blimpich** [comment] 2024-07-01 22:17
Great lets close this then.

**Closed by blimpich** 2024-07-01 22:17 UTC
Labels: Engineering, Daily, Bug
