### ISSUE TITLE
[HOLD for payment March 4th][HOLD for payment 2024-02-15] [$500] Search - "Invite a friend" banner do not move up when input field is focused in search page

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#35182] opened 2024-01-25 20:07 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.32-2
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:**  Applause - Internal Team
**Slack conversation:**
**Issue found when executing PR** https://github.com/Expensify/App/pull/33925
## Action Performed:
1. Navigate to staging.new.expensify.com & log in
2. Tap search icon
3. Click on input field to get focused

## Expected Result:
"Invite a friend, get $250" banner should move up (above the keypad) once the input field is focused

## Actual Result:
"Invite a friend" banner do not move up when input field is focused in search page. The banner still pinned below, hidden behind the keypad

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [x] iOS: mWeb Safari
- [ ] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details> 

https://github.com/Expensify/App/assets/78819774/dd772bac-9860-48c2-ad9d-d06a911ff141

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by FitseTLT** [comment] 2024-01-25 20:19
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
"Invite a friend" banner do not move up when input field is focused in search page

### What is the root cause of that problem?
We are not using `KeyboardAvoidingView` same as we did for `New ChatPage`
### What changes do you think we should make in order to solve the problem?

We should use  `KeyboardAvoidingView` same as we did for `New ChatPage` here
https://github.com/Expensify/App/blob/83a7535cf5b691fc8965607327d651d10a283bd8/src/pages/NewChatPage.js#L249-L256
### What alternative solutions did you explore? (Optional)

**Comment by c3024** [comment] 2024-01-26 04:52
Once the keyboard appears there is barely any space left to see the user details/reports. Perhaps not pushing the banner up when there is onscreen keyboard is intended. 

cc: @Expensify/design @slafortune

**Comment by shawnborton** [comment] 2024-01-26 11:11
Hmm I could have sworn this was intentional, because if the banner moves up, we'll have virtually no space left on the screen? cc @Expensify/design for thoughts there, I can't remember where we landed. 

cc @jamesdeanexpensify in case you remember, too.

**Comment by dannymcclain** [comment] 2024-01-26 14:07
@shawnborton As far as I remember, we made the banner dismissible so that we could keep it above the keyboard but still allow people to get it out of the way when searching. A lot of these screens auto-focus the keyboard upon arrival, so if we leave it stuck to the bottom even when the keyboard is open, a lot of users will never see it at all.

Here's the issue where we talked about and decided that: https://github.com/Expensify/App/issues/32499 (if you want to slog through all the comments 😬)

**Comment by shawnborton** [comment] 2024-01-26 14:08
Ah okay cool! Thanks for confirming, so sounds like this is a bug then.

**Comment by jamesdeanexpensify** [comment] 2024-01-26 17:37
Also, just an update on making the banners **permanently** dismissible, that's being worked on [here](https://github.com/Expensify/App/issues/34387).

**Comment by c3024** [comment] 2024-01-29 08:18
[Proposal here](https://github.com/Expensify/App/issues/35182#issuecomment-1911088881) by @Amarparab2024 looks good to me.

🎀 👀 🎀 C+ Reviewed

**Comment by c3024** [comment] 2024-01-30 08:17
Automation fails sometimes. You may work on the PR. An offer will be sent in the meantime.

**Comment by stitesExpensify** [comment] 2024-02-15 20:06
Hey @slafortune could you help @Amarparab2024 out please? :)

**Comment by slafortune** [comment] 2024-02-15 21:01
@stitesExpensify @Amarparab2024 definitely!  Payment is due today 👍

**Comment by slafortune** [comment] 2024-02-15 21:02
@c3024 can you please complete the checklist?

**Comment by slafortune** [comment] 2024-02-15 21:25
Offer sent [here](https://www.upwork.com/nx/wm/offer/100931347) @Amarparab2024  
Offer sent [here](https://www.upwork.com/nx/wm/offer/100931455) @c3024

**Comment by slafortune** [comment] 2024-02-19 16:57
@c3024 will you be able to complete the checklist in the next day or two?

**Comment by c3024** [comment] 2024-02-20 05:14
Unfortunately 😞 , the file `SearchPage.js` in which we fixed this has been deleted from the repo. It has been replaced with [`SearchPage/index.js`](https://github.com/Expensify/App/blob/main/src/pages/SearchPage/index.js).

The changes made in this PR are not reflected in this `index.js` file so the bug still exists.

https://github.com/Expensify/App/assets/102477862/8532e690-fda7-4821-a6e3-bd20f814a3eb

Could you raise a PR adding this prop in `SearchPage/index.js`? Thanks. @Amarparab2024 

cc: @slafortune @stitesExpensify

**Comment by slafortune** [comment] 2024-02-23 16:18
Will update the payment date once PR is deployed

**Comment by slafortune** [comment] 2024-02-28 16:33
Looks like the automation isn't working - I've updated the title.

When you have a chance @c3024 can you complete the checklist?

1. The PR that introduced the bug has been identified. Link to the PR:

2. The offending PR has been commented on, pointing out the bug it caused and why, so the author and reviewers can learn from the mistake. Link to comment:

3. A discussion in #expensify-bugs has been started about whether any other steps should be taken (e.g. updating the PR review checklist) in order to catch this type of bug sooner. Link to discussion:

4. Determine if we should create a regression test for this bug.

5. If we decide to create a [regression test](https://github.com/Expensify/App/blob/main/contributingGuides/REGRESSION_TEST_BEST_PRACTICES.md) for the bug, please propose the regression test steps to ensure the same bug will not reach production again

**Comment by c3024** [comment] 2024-03-01 14:31
1. The PR that introduced the bug has been identified. Link to the PR: #30372 
 2. The offending PR has been commented on, pointing out the bug it caused and why, so the author and reviewers can learn from the mistake. Link to comment: https://github.com/Expensify/App/pull/30372/files#r1509085869
 3. A discussion in #expensify-bugs has been started about whether any other steps should be taken (e.g. updating the PR review checklist) in order to catch this type of bug sooner. Link to discussion: No discussion was started. This is an edge case and not something that is serious so such discussion does not appear useful.
 4. Determine if we should create a regression test for this bug: No. This is about the referral program banner which foes behind the on screen keyboard on mWeb. This is not a serious enough bug to warrant a regression test.
 5. If we decide to create a [regression test](https://github.com/Expensify/App/blob/main/contributingGuides/REGRESSION_TEST_BEST_PRACTICES.md) for the bug, please propose the regression test steps to ensure the same bug will not reach production again: NA

**Comment by slafortune** [comment] 2024-03-06 15:15
Paid 👍

**Closed by slafortune** 2024-03-06 15:15 UTC
Labels: Reviewing, External, Weekly, Awaiting Payment, Bug
