### ISSUE TITLE
[$250] Mark down - Mention suggestion list does not show up when typing @

### ISSUE THREAD

**Issue by m-natarajan** [Expensify/App#43310] opened 2024-06-07 18:45 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.80-14
**Reproducible in staging?:** y
**Reproducible in production?:** n
**If this was caught during regression testing, add the test name, ID and link from TestRail:** n/a
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** Applause internal team
**Slack conversation:**

## Action Performed:
1. Go to staging.new.expensify.com
2. Go to chat.
3. Type @.

## Expected Result:
Mention suggestion list will show up.

## Actual Result:
Mention suggestion list does not show up.
The same issue happens with emoji suggestion list.

## Workaround:
unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [x] Android: mWeb Chrome
- [ ] iOS: Native
- [x] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

https://github.com/Expensify/App/assets/38435837/76d3064a-87d6-46ab-b454-43766c073a66

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01d317959e4f5df92e</li>
        <li>Upwork Job ID: 1799815579588250941</li>
        <li>Last Price Increase: 2024-06-09</li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @rojiphil</details>

**Comment by m-natarajan** [comment] 2024-06-07 18:45
@miljakljajic  FYI I haven't added the External label as I wasn't 100% sure about this issue. Please take a look and add the label if you agree it's a bug and can be handled by external contributors

**Comment by m-natarajan** [comment] 2024-06-07 18:46
We think that this bug might be related to #vip-vsb

**Comment by roryabraham** [comment] 2024-06-07 20:37
Pretty certain this is front-end.

**Comment by roryabraham** [comment] 2024-06-07 20:37
I notice if you refresh the page with a report open then it works as expected

**Comment by roryabraham** [comment] 2024-06-07 20:58
Confirmed that `textInputRef.current.isFocused()` is returning false [here](https://github.com/Expensify/App/blob/4c86fbfb8ca08ad0b4f726823e3d71af7ec38be9/src/pages/home/report/ReportActionCompose/ComposerWithSuggestions/ComposerWithSuggestions.tsx#L784). There's `textInputRef.current` is a live markdown ref, but I want to confirm that it's been correctly updated to the live markdown component for the current report.

**Comment by roryabraham** [comment] 2024-06-07 21:21
Looks like there's some kind of focus toggling going on:

<img width="1315" alt="image" src="https://github.com/Expensify/App/assets/47436092/0ff3a7c7-2c52-4e90-8be3-385434a3f4a0">

Maybe we've got some bad memoization causing the live markdown component to unmount and remount a few times?

**Comment by luacmartins** [comment] 2024-06-07 21:33
That also seems to be the cause for https://github.com/Expensify/App/issues/43312. We're not triggering `onSelectionChange` with each new input

**Comment by roryabraham** [comment] 2024-06-07 21:42
Ruling out other components unmounting and remounting in the tree:

- ComposerWithSuggestions ❌ 

    <img width="1359" alt="image" src="https://github.com/Expensify/App/assets/47436092/5709e83a-8a10-456c-8129-c1312e684a20">

- Composer ❌ 

    <img width="1348" alt="image" src="https://github.com/Expensify/App/assets/47436092/94415ac0-055a-4802-b558-7b22672277bd">

**Comment by mountiny** [comment] 2024-06-09 19:56
Reverting the offending PR within the live-markdown https://github.com/Expensify/react-native-live-markdown/pull/377

**Comment by mountiny** [comment] 2024-06-09 21:25
<img width="289" alt="image" src="https://github.com/Expensify/App/assets/36083550/eeb6b723-c95a-440c-9646-6038e2bbe0ba">
fixed in the -17 version

**Comment by roryabraham** [comment] 2024-06-10 15:52
Payments are being handled in https://github.com/Expensify/App/issues/43332, closing this out

**Closed by roryabraham** 2024-06-10 15:52 UTC
Labels: Reviewing, External, Engineering, Weekly, Bug
