### ISSUE TITLE
[$250]  iOS - LHN - Unable to open Concierge chat in LHN after creating new account

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#40604] opened 2024-04-19 18:39 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** .1.4.63-9
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**If this was caught during regression testing, add the test name, ID and link from TestRail:** N/A
**Issue reported by:** Applause - Internal Team

## Action Performed:
1. Launch New Expensify app
2. Log in with a new GMAIL account
3. Tap on Concierge chat

## Expected Result:
Concierge chat opens

## Actual Result:
Nothing happens when tapping on Concierge chat

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [x] iOS: Native
- [ ] iOS: mWeb Safari
- [ ] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details> 

https://github.com/Expensify/App/assets/78819774/389256a6-8738-4fc8-8668-b6164f5aac55

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~016a973a840d55da5c</li>
        <li>Upwork Job ID: 1781405725012254720</li>
        <li>Last Price Increase: 2024-04-26</li>
    </ul>
</details>

**Comment by lanitochka17** [comment] 2024-04-19 18:40
@joekaufmanexpensify  FYI I haven't added the External label as I wasn't 100% sure about this issue. Please take a look and add the label if you agree it's a bug and can be handled by external contributors

**Comment by lanitochka17** [comment] 2024-04-19 18:40
We think that this bug might be related to #vip-vsp

**Comment by joekaufmanexpensify** [comment] 2024-04-19 19:33
Interesting. I can reproduce, and only on a new gmail/public domain account. 


https://github.com/Expensify/App/assets/54866469/7c73b9ae-d96e-4f0e-ac9f-6816d42c88a9

**Comment by shahinyan11** [comment] 2024-04-20 12:21
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
iOS - LHN - Unable to open Concierge chat in LHN after creating new account
### What is the root cause of that problem?
It doesn't matter there if the user is new or not the bug related with count of items in list. The bug exists if there is one item in list. 
It is a bug from package `@shopify/flash-list`, currently we use `1.6.3`. I tried to update to last `1.6.4` version and the Concierge chat become clickable but there appears a read overlay on item with some message. See below attachment  
### What changes do you think we should make in order to solve the problem?
Add `disableAutoLayout={true}` prop for [FlashList](https://github.com/Expensify/App/blob/1e510b52a5c65a2c812e74feb686debea6e0b040/src/components/LHNOptionsList/LHNOptionsList.tsx#L227C18-L227C27) component
 
### What alternative solutions did you explore? (Optional)

**Comment by sword1202** [comment] 2024-04-22 04:47
Contributor details
Your Expensify account email: [payoneermap1202@gmail.com](mailto:payoneermap1202@gmail.com)
Upwork Profile Link: https://www.upwork.com/freelancers/~0194d962e1f9098218
I would like to join to slack channel.

**Comment by joekaufmanexpensify** [comment] 2024-04-22 18:26
Sounds good. Will do!

**Comment by joekaufmanexpensify** [comment] 2024-04-23 14:06
Pending review from @ahmedGaber93

**Comment by ahmedGaber93** [comment] 2024-04-23 16:19
@joekaufmanexpensify @shahinyan11 
I can't reproduce in simulator (iOS 17.2) with the latest main, is anyone still able to reproduce?
Also, after create a new account, I can see two chats in chat list (slefDM and Concierge).


https://github.com/Expensify/App/assets/41129870/0b2d3588-21aa-495a-b00f-384a09590475

**Comment by shahinyan11** [comment] 2024-04-23 16:25
> @joekaufmanexpensify @shahinyan11 I can't reproduce in simulator (iOS 17.2) with the latest main, is anyone still able to reproduce? Also, after create a new account, I can see two chats in chat list (slefDM and Concierge).

@ahmedGaber93 I mentioned in my proposal that it reproducible only if there is one chat in . So It can't be reproducible with multiple chats

**Comment by ahmedGaber93** [comment] 2024-04-23 19:06
Another cases for this issue (`Flashlist` item not clickable).
1. Login with new account (important to limit the result in step 3).
2. Open selfDM chat.
3. In composer type `@`, the mention suggestion displays 3 items (here, concierge, you).

Issue 1: if you click on the last item, the last item not clickable.
Issue 2: sometimes last item jumps to the previous item and last item space appear as empty space.
Issue 3: if you type `@yourEmail` and `Flashlist` displays only one item (you). The item is not clickable.


https://github.com/Expensify/App/assets/41129870/5bf659cf-586a-48e7-aa32-7b5c6f9bc234

**Comment by ahmedGaber93** [comment] 2024-04-23 19:25
@shahinyan11 Thanks for the proposal, your proposal works in this issue case, but not works for a similar cases here https://github.com/Expensify/App/issues/40604#issuecomment-2073217907, also I think it is workaround as the issue seem related to `Flashlist` with new arch.

After applied your fix.


https://github.com/Expensify/App/assets/41129870/408e7d08-fb96-4b3a-9a94-8e228fadc2e2

**Comment by ahmedGaber93** [comment] 2024-04-23 19:49
I think this issue is related to https://github.com/Expensify/App/pull/13767, and have similar root cause of
- https://github.com/Expensify/App/issues/40077
- https://github.com/Expensify/App/issues/40048
- https://github.com/Expensify/App/issues/40108


Because I see @WoLewicki and @roryabraham work here https://github.com/Expensify/App/pull/40191 (this PR is reverted) to fix `Flashlist` issues, I tagged you here to confirm you are aware of this issue.

Thanks!

**Comment by shahinyan11** [comment] 2024-04-23 20:27
>  also I think it is workaround as the issue seem related to `Flashlist` with new arch.

@ahmedGaber93 Why a workaround. I mentioned an article in the official documentation where it is suggested to use `disableAutoLayout={true}`

**Comment by ahmedGaber93** [comment] 2024-04-23 20:42
> Are you tried to add disableAutoLayout={true} form mentions FlashList ?

Yes, add here the result https://github.com/Expensify/App/issues/40604#issuecomment-2073248425

**Comment by joekaufmanexpensify** [comment] 2024-04-25 13:49
@ahmedGaber93 are we close to selecting a proposal here?

**Comment by ahmedGaber93** [comment] 2024-04-25 14:05
@joekaufmanexpensify Unfortunately, the above proposal does not fix the issue.
We are still waiting for proposals.

**Comment by joekaufmanexpensify** [comment] 2024-04-26 13:58
Got it, sounds good!

**Comment by joekaufmanexpensify** [comment] 2024-04-29 14:14
Awaiting proposals

**Comment by joekaufmanexpensify** [comment] 2024-04-30 14:24
Still awaiting proposals

**Comment by mvtglobally** [comment] 2024-05-01 14:02
Issue not reproducible during KI retests. (First week)

**Comment by joekaufmanexpensify** [comment] 2024-05-01 15:30
Yep, this is working fine for me too now. Closing as whatever the issue was, it seems to have been fixed!

**Closed by joekaufmanexpensify** 2024-05-01 15:30 UTC
Labels: External, Daily, Help Wanted, Bug
