### ISSUE TITLE
FAB - Save the world - After leaving the room " Expensify dot org/ Teacher's unite", option " I am a teacher should reappear

### ISSUE THREAD

**Issue by izarutskaya** [Expensify/App#26691] opened 2023-09-04 16:40 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Fab -> save the world -> I am a teacher
2. Enter Name and email
3. now it should redirect to room "[Expensify.org/](http://expensify.org/) Teacher's unite"
4. go to details of the room and leave the room.
5. Go to Fab button again -> save the world . Notice this time " I am a teacher " option is not shown.

## Expected Result:
user might leave the room ( [Expensify.org/](http://expensify.org/) Teacher's unite) accidentally. Thus, " I am a teacher" option should be shown in save the world page. So that one can join the room again.

## Actual Result:
After leaving room [Expensify.org/](http://expensify.org/) Teacher's unite , " I am a teacher option " disappears

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [x] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 1.3.62-4

**Reproducible in staging?:** Y

**Reproducible in production?:** N

**If this was caught during regression testing, add the test name, ID and link from TestRail:**

**Email or phone of affected tester (no customers):**

**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/115492554/152c29e8-1444-4981-8ec5-55289357218e

https://github.com/Expensify/App/assets/115492554/f28801e3-850f-4811-b49f-99bcb51ed720

**Expensify/Expensify Issue URL:**

**Issue reported by:** @ashimsharma10

**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p16934030597274790

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by izarutskaya** [comment] 2023-09-04 16:41
Issue is not reproducible in Production

https://github.com/Expensify/App/assets/115492554/862e45ab-79c1-4406-98ea-e0a629702fe2

**Comment by ashimsharma10** [comment] 2023-09-04 21:00
> Issue is not reproducible in Production
> 
>  Recording.1433.mp4

@izarutskaya you have not done step 4 from above. In this production video.

**Comment by izarutskaya** [comment] 2023-09-04 21:37
@ashimsharma10 Sorry, I can't reproduce this issue anymore in build v1.3.63-0. Production the same. 

https://github.com/Expensify/App/assets/115492554/1a1c7c71-d053-4ffe-9e0c-2651aa5b9848

https://github.com/Expensify/App/assets/115492554/62966848-1f79-46f9-8e5b-b542b43646e6

**Comment by youssef-lr** [comment] 2023-09-05 00:12
I can't reproduce this issue either. But we do hide the "I am a teacher" button once the teacher has joined the policy. Closing!

**Closed by youssef-lr** 2023-09-05 00:12 UTC
Labels: DeployBlockerCash, Engineering, Hourly, Bug

**Comment by ashimsharma10** [comment] 2023-09-05 02:50
> @ashimsharma10 Sorry, I can't reproduce this issue anymore in build v1.3.63-0. Production the same.
> 
>  Recording.1441.mp4 
> 
>  Recording.1440.mp4

@izarutskaya This time step 1 is done incorrectly. reproducible step is: First fill in' I am a teacher' and then leave the room. In your videos, you did ' I know a teacher'. 


asking in #open-source, if its a intended behaviour.

**Comment by izarutskaya** [comment] 2023-09-05 09:17
@ashimsharma10 I can't leave the room 

https://github.com/Expensify/App/assets/115492554/85aafea3-eb66-4879-97f9-e6550cf2a9b6

**Comment by ashimsharma10** [comment] 2023-09-05 09:49
leaving room option is at, #teacher-unite room.

Apologies for the trouble. I think I didn't write the Action steps properly before.
Let me explain again. 

( Rather than Bug, I guess it might be feature request)

 I'm saying is that once you leave the 'teacher-unite policy' room, there is no feature to again join the community as 'I am a teacher'. I mean if someone leaves room accidentally, then he can't do ' I am teacher ' again.


1. fab button -> save the world -> 'I KNOW A TEACHER' -> fill the form -> lets do this
2. Now , fab button -> save the world -> 'I Am A TEACHER' -> fill the form -> lets do this
3.  go to # teacher-unite -> settings-> leave room.
4.  Now go to fab button -> save the world
5. Notice that after leaving the room, option ' I am a teacher' doesn't reappear.

I think someone from internal better see this. And its not a deploy blocker. 
@izarutskaya Thank you for looking again.
<img width="1435" alt="Screenshot 2023-09-05 at 3 08 00 PM" src="https://github.com/Expensify/App/assets/43598308/9903185e-a279-4d0b-a565-579ab26a5c99">

**Comment by youssef-lr** [comment] 2023-09-05 10:50
>Reproducible step is: First fill in' I am a teacher' and then leave the room

Steps from "I am a teacher" will allow you to join the policy, once you join, we remove the "I am a teacher" button to prevent trying to join the policy multiple times. Leaving the public room has no effect on the "I am a teacher" button.
