### ISSUE TITLE
Web - Timezone - Console error appears when come back online after changing Timezone offline 

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#13311] opened 2022-12-03 16:35 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Issue found when executing PR** https://github.com/Expensify/App/pull/12201

## Action Performed:
1. Go to https://staging.new.expensify.com/
and login
2. Change URL to ".....staging.new.expensify.com/settings/profile/timezone"
3. Go offline
4. Change Timezone
5. Back online

## Expected Result:
No Console error appears when come back online after changing Timezone offline 

## Actual Result:
Console error appears when come back online after changing Timezone offline 

## Workaround:
Unknown

## Platform:

Where is this issue occurring?

- Web

**Version Number:** 1.2.36.0

**Reproducible in staging?:** Yes

**Reproducible in production?:** new feature

**Email or phone of affected tester (no customers):** 

**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Notes/Photos/Videos:** Any additional supporting documentation

https://user-images.githubusercontent.com/93399543/205451403-1b73f086-c5ff-425d-ab90-45129e1abb56.mp4

**Expensify/Expensify Issue URL:** 

**Issue reported by:** Applause - Internal Team
 
**Slack conversation:** 

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by aldo-expensify** [comment] 2022-12-06 00:00
I think this is not related to the timezone page, I have seen this happening when you disable the connection in your computer/mac, but the app has not yet updated the offline/online state. Since there is no internet connection, but the App thinks there is, it tries to send the requests in a retry loop and all of them fail. You can see that this is the case because if the App had detected correctly that you were offline, you would have seen the message "You appear to be offline":

![image](https://user-images.githubusercontent.com/87341702/205772297-9857b4f2-12fa-4df7-9441-5bc65ffe6ba9.png)

**Comment by aldo-expensify** [comment] 2022-12-06 00:01
Maybe we should create a new GH issue that describes the problem [above](https://github.com/Expensify/App/issues/13311#issuecomment-1338385203), the small details it that I don't think we have a reliable way of reproducing it.

**Comment by marcaaron** [comment] 2022-12-06 00:53
also maybe the site was just down when this happened? It went down at some point today IIRC.

**Comment by marcaaron** [comment] 2022-12-06 00:54
>Reproducible in production?: new feature

What about this is a new feature?

**Comment by marcaaron** [comment] 2022-12-06 00:57
Oh, I see, it's a new page just for timezones.

**Comment by marcaaron** [comment] 2022-12-06 00:59
Can't reproduce this one. Gonna close it since we don't have a good lead on what happened for tester. Feel free to reopen if anyone disagrees.

**Closed by marcaaron** 2022-12-06 00:59 UTC
Labels: Daily, Overdue, Bug

**Comment by aldo-expensify** [comment] 2022-12-06 01:07
> also maybe the site was just down when this happened? It went down at some point today IIRC.

I don't think so, the video was taken 2 days ago, also you can see in the video that they disconnected the wifi to go offline, but the App didn't react to it.

**Comment by marcaaron** [comment] 2022-12-06 01:36
Got it, thanks. Should we reopen then? Maybe with the `Needs Reproduction` label?

**Comment by aldo-expensify** [comment] 2022-12-06 01:56
Nah, this GH issue description/title will be misleading of the actual cause.  I'll create a new GH issue describing the connection state not reacting to an offline connection and add the `Needs Reproduction`.
