### ISSUE TITLE
[HOLD for payment 2023-10-02] [$500] Settings - Help -User can not scroll to to the bottom of the page.

### ISSUE THREAD

**Issue by izarutskaya** [Expensify/App#27365] opened 2023-09-13 15:23 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1.Login and then open Settings.
2. open help.
3. tap on search icon.
4. type in the search field. I have entered "other" in it,
5. When the search list shows up try to scroll down , it stuck after a little scroll, User can not go though the whole list.

## Expected Result:
User should see through whole list.

## Actual Result:
User gets stuck while scrolling the list.

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [x] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [ ] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** v1.3.69-0

**Reproducible in staging?:** Y

**Reproducible in production?:** Y

**If this was caught during regression testing, add the test name, ID and link from TestRail:**

**Email or phone of affected tester (no customers):**

**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/115492554/7a7ea8c3-deed-4f99-a49d-523923a935cd

https://github.com/Expensify/App/assets/115492554/06ac4df2-f763-4d5e-acbc-29cbb26d5f6b

**Expensify/Expensify Issue URL:**

**Issue reported by:** @Harshizonnet

**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1693664400580059

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01a29391c5d4456b92</li>
        <li>Upwork Job ID: 1701980015607357440</li>
        <li>Last Price Increase: 2023-09-13</li>
<li>Automatic offers: </li>
<ul>
<li>ntdiary | Reviewer | 26722324</li>
<li>Harshizonnet | Reporter | 26722326</li>
</ul></li>
    </ul>
</details>

**Comment by imranaalam** [comment] 2023-09-13 15:57
---

**Problem Statement:**  
Upon logging in and navigating to Settings, when a user accesses the help section and initiates a search (for instance, by entering "other"), the resulting search list becomes unresponsive after a brief scroll. This behavior prevents users from viewing the entirety of the search results. The expected behavior is for users to be able to seamlessly scroll through the full list without any hindrance. As of now, there is no known workaround for this issue.

---

**Root Cause:**  
On the Android platform, the last item in the search list is partially obscured by the bottom bar, leading users to believe the list is truncated. Verification on Windows Chrome has confirmed that the last item displayed on Android is the final list entry, but it's not fully visible.

![image](https://github.com/Expensify/App/assets/17583722/efccc162-c28a-4dc0-acd6-294680f341df)

**Proposed Solution:**  
Introduce additional padding at the end of the search list specifically for the Android platform to ensure that the last item is fully visible above the Android bottom bar.

**Alternative Solution:**  
Re-evaluate the mobile-responsive design elements of the search list on Android. Consider adjusting the overall layout to ensure all items, including the last one, are fully visible.

---

**Comment by imranaalam** [comment] 2023-09-13 16:06
---

**Problem Statement:**  
On Android devices, when users access the search functionality and try to view the results, the last item in the list is partially obscured by the Android bottom navigation bar. This behavior makes it appear as though the list is truncated and prevents users from viewing the entire content.

**Root Cause:**  
The web content is rendered in such a way that the total height of the content, including the search results, extends to the bottom edge of the viewport. As a result, the Android bottom navigation bar overlaps with the final items, obscuring them from view.

**Proposed Solution:**  
Adjust the padding or margin at the bottom of the content container (or the search results container) to account for the height of the Android bottom bar. This additional spacing will ensure the last item in the list is fully visible above the Android bottom bar.

```css
#content-area {
    padding-bottom: 60px; /* or an appropriate value based on the average height of the Android bottom bar */
}
```

**Alternative Solutions:**  

1. **Use a Sticky Footer**:  
Design the footer to always stick to the bottom, pushing the content upwards. This ensures that even if users scroll down, the content remains above the bottom bar.

2. **Dynamic Resizing with Event Listeners**:  
Attach a resize event listener to the window. If the height changes without a corresponding change in width (indicating the appearance or disappearance of the navigation bar), adjust the content's bottom padding.

3. **Progressive Web App (PWA) Approach**:  
If this is a Progressive Web App, consider using a `display: standalone` or `display: fullscreen` property in the web app manifest. This ensures the content is displayed in a standalone or fullscreen mode, respectively, reducing browser UI obstructions.

4. **Mobile-specific Styles**:  
Use media queries to apply specific styles for mobile devices, ensuring that the content is always above the bottom bar:

```css
@media (max-width: 600px) { /* or other breakpoint for mobile devices */
    #content-area {
        padding-bottom: 60px;
    }
}
```

5. **Feedback-driven UI Adjustment**:  
Integrate a feedback mechanism where users can report UI issues. Use this feedback to gather data on devices where the problem persists and fine-tune the solution for those specific devices.

6. **Test with Different Mobile Browsers**:  
The issue might not be consistent across all mobile browsers. Testing on different browsers (like Firefox, Samsung Internet, etc.) can provide insights into whether the problem is browser-specific and if certain browsers have built-in solutions.

---

**Comment by imranaalam** [comment] 2023-09-14 08:38
---

**Problem Statement:**  
On certain devices, especially Android, users are unable to scroll to the bottom of the search results page in the Expensify Help section. The content is hidden, resulting in a truncated list.

**Root Cause:**  
The `max-height` for the search page content is set to a static value of `80vh`. On some devices, particularly those with prominent browser UI elements or navigation bars, this causes content to overflow and be obscured.

**Proposed Solution:**  
1. **Flexible Container Height with CSS Variables**: 
   
   Use CSS variables (custom properties) to dynamically adjust the height based on device characteristics.
   
   ```css
   :root {
       --dynamic-max-height: calc(100vh - 150px);
       --tablet-max-height: calc(100vh - 220px);
   }
   
   #sidebar-search {
       max-height: var(--dynamic-max-height);
       overflow-y: scroll;
   }

   @media only screen and (max-width: $breakpoint-tablet) {
       #sidebar-search {
           max-height: var(--tablet-max-height);
       }
   }
   ```

**Alternative Solution:**

1. **JavaScript-based Dynamic Adjustment**: Detect the presence of an Android navigation bar or any other UI elements and adjust the `max-height` accordingly.

   ```javascript
   const searchBar = document.getElementById('sidebar-search');
   const navBarHeight = getAndroidNavBarHeight();  // This function detects the nav bar height

   if (navBarHeight) {
       const adjustedHeight = `calc(100vh - ${navBarHeight}px)`;
       searchBar.style.maxHeight = adjustedHeight;
   }
   ```

2. **Viewport Units with Fallback**: Utilize a combination of viewport units (`vh` and `vw`) along with pixel units for better compatibility.

   ```css
   #sidebar-search {
       max-height: calc(100vh - 150px);
       max-height: calc(100% - 150px);
       overflow-y: scroll;
   }
   ```

3. **User Feedback Mechanism**: Implement a system for users to report display issues, and use this feedback to fine-tune the solution.

---

**Comment by tgolen** [comment] 2023-10-02 15:09
@JmillsExpensify It looks like this issue is waiting on you. I assume you've been traveling the last couple of days, so I am hopeful this will be addressed soon.

**Comment by JmillsExpensify** [comment] 2023-10-07 21:44
Thanks @ntdiary for completing the BZ checklist! 

Payment summary: 
 - Issue reporter: @Harshizonnet $50
 - Contributor: @suneox $1,000 (incl. urgency bonus)
 - Contributor+: @ntdiary $1,000 (incl. urgency bonus)

**Comment by JmillsExpensify** [comment] 2023-10-07 21:48
Payments sent to issue reporter and contributor+. Offer sent to contributor. Once that is complete, we'll close this issue out.

**Comment by JmillsExpensify** [comment] 2023-10-08 13:58
Great catch! Yes, you're right. Updated above

**Closed** 2023-10-08 14:05 UTC
Labels: External, Daily, Awaiting Payment, Bug
