### ISSUE TITLE
[HOLD for payment 2023-10-24] [$500] iOS -  Receipt replace popup camera click button is overlapping with home bar

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#28145] opened 2023-09-25 14:28 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Create a request by scanning a receipt.
2. Go to created receipt.
3. Open the receipt details report.
4. Click on receipt image.
5. Click 3 dots menu icon and click replace.

## Expected Result:
Camera click button should not overlap with native home bar.

## Actual Result:
home button interfering with UI.

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [ ] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 1.3.73.0
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/93399543/c4af3581-3380-44b1-a37e-4d60200afa7e

https://github.com/Expensify/App/assets/93399543/df659a1e-85df-4b30-89dc-b246d623466c

**Expensify/Expensify Issue URL:**
**Issue reported by:** @parasharrajat
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1695376096559109

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~0191bee1b0a882677e</li>
        <li>Upwork Job ID: 1706314684003328000</li>
        <li>Last Price Increase: 2023-10-09</li>
<li>Automatic offers: </li>
<ul>
<li>ahmedGaber93 | Contributor | 27178584</li>
</ul></li>
    </ul>
</details>

**Comment by ahmedGaber93** [comment] 2023-09-25 14:28
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
iOS: Receipt replace popup camera click button is overlapping with home bar
### What is the root cause of that problem?
We don't include safe area padding bottom to this screen
https://github.com/Expensify/App/blob/5aa7f6da94ddb1c8ca55a6cce714555f819c1dd0/src/pages/EditRequestReceiptPage.js#L31-L32
### What changes do you think we should make in order to solve the problem?
We need to include safe area padding bottom by one of: 
1. surround `DragAndDropProvider` content with `<View style={[styles.flex1, safeAreaPaddingBottomStyle]}>` like money request page do [here](https://github.com/Expensify/App/blob/5aa7f6da94ddb1c8ca55a6cce714555f819c1dd0/src/pages/iou/MoneyRequestSelectorPage.js#L93) to ensure `DragAndDropProvider` work fine in full screen height 
```javascript
<ScreenWrapper
    includeSafeAreaPaddingBottom={false}
>
    {({safeAreaPaddingBottomStyle}) => (
        <>
            <HeaderWithBackButton/>
            <DragAndDropProvider>
                <View style={[styles.flex1, safeAreaPaddingBottomStyle]}>
                    <ReceiptSelector/>
                </View>
            </DragAndDropProvider>
        </>
    )}
</ScreenWrapper>
```
2. Alternative simply remove prop `includeSafeAreaPaddingBottom={false}`
### What alternative solutions did you explore? (Optional)
remove prop `includeSafeAreaPaddingBottom={false}`

**Comment by ahmedGaber93** [comment] 2023-09-27 12:19
drag and drop not cover the header will fix here https://github.com/Expensify/App/issues/28014

**Comment by laurenreidexpensify** [comment] 2023-09-28 03:30
@mananjadhav do you agree? ^^

**Comment by ahmedGaber93** [comment] 2023-10-02 17:42
@laurenreidexpensify @mananjadhav 
Why we will close this issue, I think it should fix.

**Comment by ahmedGaber93** [comment] 2023-10-02 19:04
> drag and drop not cover the header will fix here https://github.com/Expensify/App/issues/28014

I am replying here to esh-g's [proposal](https://github.com/Expensify/App/issues/28145#issuecomment-1733826062), not saying this issue will fix in other.

Sorry for not being clear.

**Comment by ahmedGaber93** [comment] 2023-10-03 10:25
@laurenreidexpensify 
It would be great if you answered me here https://github.com/Expensify/App/issues/28145#issuecomment-1743468494
Thanks!

**Comment by ahmedGaber93** [comment] 2023-10-05 17:05
@laurenreidexpensify 
This issue need to reopen again because it is different issue, and
https://github.com/Expensify/App/issues/28014 is already merged, but it is not including any fix for this issue.

**Comment by ahmedGaber93** [comment] 2023-10-11 10:52
@mananjadhav friendly bump.

**Comment by mananjadhav** [comment] 2023-10-11 12:24
Apologies for the confusion on closing the ticket. I was expecting the linked issue will resolve this change as well.

@ahmedGaber93's proposal looks good to me.

🎀 👀 🎀 C+ reviewed.

**Comment by laurenreidexpensify** [comment] 2023-10-13 11:36
@NikkiWines bump please review and assign thanks

**Comment by NikkiWines** [comment] 2023-10-13 11:44
Agreed, @ahmedGaber93's proposal looks good!!

**Comment by ahmedGaber93** [comment] 2023-10-14 16:58
@mananjadhav PR https://github.com/Expensify/App/pull/29617 is ready for review.

**Comment by laurenreidexpensify** [comment] 2023-10-24 11:36
Payment Summary: 

- C+ @mananjadhav does not require payment in Upwork ($500) (Eligible for Manual Requests)
- Code Fix - @ahmedGaber93 payment in upwork ($500) 
- Bug report - @parasharrajat  does not require payment in Upwork ($50) (Eligible for Manual Requests)

**Comment by mananjadhav** [comment] 2023-10-24 18:21
Agreed @laurenreidexpensify. This is eligible for the urgency bonus.

**Comment by JmillsExpensify** [comment] 2023-10-25 17:02
$750 payment approved for @mananjadhav based on BZ summary.

**Comment by laurenreidexpensify** [comment] 2023-10-26 10:45
@mananjadhav please complete checklist so we can close, thanks

**Comment by mananjadhav** [comment] 2023-10-27 07:25
We added `EditRequestReceiptPage` in this [commit](https://github.com/Expensify/App/commit/84ef3bd16151bc1cedb4cf01155f1688980808af) in this [PR](https://github.com/Expensify/App/pull/26508).

I've added a comment [here](https://github.com/Expensify/App/commit/84ef3bd16151bc1cedb4cf01155f1688980808af#r131049998). I don't think we need a regression test for this one.

**Closed** 2023-10-27 12:37 UTC
Labels: External, Daily, Awaiting Payment, Bug

**Comment by JmillsExpensify** [comment] 2024-04-08 03:01
$50 approved for @parasharrajat
