### ISSUE TITLE
[Payment due 03-04][$500] Menu - Pin & Delete request appear on Receipt image when quickly tap on receipt and 3-Dot menu

### ISSUE THREAD

**Issue by izarutskaya** [Expensify/App#33541] opened 2023-12-23 11:19 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.16-3
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** Applause-Internal Team
**Slack conversation:** @

## Action Performed:
1. Navigate to New dot app as Employee
2. Go to workspace chat> create Scan request
3. On detail page tap receipt and 3-Dot menu in a quick manner

## Expected Result:
The receipt should be open and no 3-Dot menu should be open

## Actual Result:
3-Dot menu (Pin & Delete request) from detail page appear on Receipt image when quickly tap on receipt and 3-Dot menu

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

https://github.com/Expensify/App/assets/115492554/75e058b7-68dd-4ab6-94e7-bc978c6122ea

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01ea7a6ca457ab8814</li>
        <li>Upwork Job ID: 1738519644108128256</li>
        <li>Last Price Increase: 2024-01-06</li>
<li>Automatic offers: </li>
<ul>
<li>c3024 | Contributor | 28106449</li>
</ul></li>
    </ul>
</details>

**Comment by shahinyan11** [comment] 2023-12-23 15:04
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
Menu - Pin & Delete request appear on Receipt image when quickly tap on receipt and 3-Dot menu 
### What is the root cause of that problem?
The root cause is that  the Receipt image view and 3-dot menu are modals. The modals always open on top of screen in react native and the last opened modal will be on top
### What changes do you think we should make in order to solve the problem?
I think would be better if we use one component for displaying any modals in root of project . But in this case, we can  fix the problem with the following steps.
1. Add new key (e.g `IS_MODAL_OPENING: 'isModalOpening`) in Onyx data and set it  `true` on opening Receipt image modal and ten set it `false` in `onModalShow` callback.
2. Prevent displaying 3-Dot menu when `isModalOpening === true`  

### What alternative solutions did you explore? (Optional)

**Comment by c3024** [comment] 2023-12-25 06:28
I find this extremely difficult to reproduce on my device and emulator. I am not able to quickly press the three dot menu after pressing on the receipt. Any tips to consistently reproduce this?

**Comment by c3024** [comment] 2023-12-28 04:04
Reviewing

**Comment by c3024** [comment] 2023-12-31 04:04
Is there a similar case anywhere else where an undesired three dot menu modal appears over another modal so that a global fix is warranted?

**Comment by shahinyan11** [comment] 2024-01-01 10:39
@c3024 I think a global fix should be made around a new feature, not around bug. Because AttachmentModal is not associated with other modals and works separately .

**Comment by Christinadobrzyn** [comment] 2024-01-03 00:39
looks like we're reviewing this, @c3024 let me know if you need any help from me!

**Comment by c3024** [comment] 2024-01-06 03:46
I have not been able to reproduce this anywhere else. Could you post a video of it?

**Comment by Christinadobrzyn** [comment] 2024-01-08 00:18
I can't reproduce this either - @tienifr are you able to take a video of what you see?

I'm going ooo next week so going to assign a buddy to monitor this for me

status - we're trying to reproduce this (and probably update the OP with the correct steps)

**Comment by mvtglobally** [comment] 2024-01-11 06:00
Issue not reproducible during KI retests. (First week)

**Comment by shahinyan11** [comment] 2024-01-11 07:30
The bug is still reproducible

https://github.com/Expensify/App/assets/46921547/961a682e-8faa-4a15-97e7-2e641fcc5150

**Comment by c3024** [comment] 2024-01-11 15:25
Thank you all for your proposals.

`willAlertModalBecomeVisible ` is largely modified in the base components. 

So, I think the approach of not showing the popover when the three dot menu is behind a modal is the better way of fixing this than changing the `willAlertModalBecomeVisible` values in the `AttachmentModal`. This approach also fixes all possible cases where the three dot menu can be behind any modal.

[Proposal here](https://github.com/Expensify/App/issues/33541#issuecomment-1868327812) by @tienifr looks good to me.

🎀 👀 🎀 C+ Reviewed

**Comment by puneetlath** [comment] 2024-01-17 17:34
Ok, plan sounds good to me.

**Comment by Christinadobrzyn** [comment] 2024-02-07 00:29
working on PR - https://github.com/Expensify/App/pull/34720

**Comment by Christinadobrzyn** [comment] 2024-02-27 01:05
Ooh boy! https://github.com/Expensify/App/pull/34720 Hit production today! 

I'll add the payment timeframe in the Title.

**Comment by Christinadobrzyn** [comment] 2024-03-07 06:40
Payouts due:

Contributor: $500 @tienifr 
Contributor+: $500 @c3024 (paid in Upwork - https://www.upwork.com/nx/wm/workroom/36050068/overview)

Upwork job is [here](https://www.upwork.com/jobs/~01ea7a6ca457ab8814) (it's closed).

@tienifr are you paid in upwork or newDot? 

@c3024 do we need a regression test for this?

**Comment by c3024** [comment] 2024-03-08 06:55
### Regression Test Proposal

1. Login ND as an employee of a Workspace
2. Navigate to the Workspace Chat > Create Scan Request and complete the request
3. Navigate to this money request details page
4. On this details page press on the receipt and then on the 3-Dot menu of this details page quickly
5. Verify that only the receipt is opened with no 3-Dot menu of the details page opened

👍 or 👎

**Comment by Christinadobrzyn** [comment] 2024-03-08 23:18
Awesome! Thank you @c3024 and @tienifr!

Both of you are paid based on this payment summary https://github.com/Expensify/App/issues/33541#issuecomment-1982581423

I'll submit the regression test on Monday

**Comment by Christinadobrzyn** [comment] 2024-03-13 04:53
submitted regression test - https://github.com/Expensify/Expensify/issues/378295

closing!

**Closed by Christinadobrzyn** 2024-03-13 04:53 UTC
Labels: Reviewing, External, Engineering, Weekly, Bug
