### ISSUE TITLE
[$1000] Task - Avatar for the same new user is different in Assignee and Share somewhere fields

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#24078] opened 2023-08-02 20:22 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Go to staging.new.expensify.com
2. Click + > Assign task.
3. Enter title > Next.
4. Enter an email that does not have a NewDot account

## Expected Result:
Avatar for the same new user is the same in Assignee and Share somewhere fields

## Actual Result:
Avatar for the same new user is different in Assignee and Share somewhere fields

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [x] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [x] Windows / Chrome 
- [ ] MacOS / Desktop

**Version Number:** 1.3.49.1

**Reproducible in staging?:** Yes

**Reproducible in production?:** Yes

**If this was caught during regression testing, add the test name, ID and link from TestRail:**

**Email or phone of affected tester (no customers):**

**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/78819774/3159f058-98bc-4200-96ca-a1b605619a82

**Expensify/Expensify Issue URL:**

**Issue reported by:** Applause - Internal Team

**Slack conversation:**

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~013ee9160400af123a</li>
        <li>Upwork Job ID: 1687218399795974144</li>
        <li>Last Price Increase: 2023-09-22</li>
    </ul>
</details>

**Comment by s-alves10** [comment] 2023-08-03 02:16
## Proposal

### Please re-state the problem that we are trying to solve in this issue.

Avatar for the same new user is different in assignee and share destination fields

### What is the root cause of that problem?

When task is created with a new user, new chat is created with the new user and set the new `reportID` to the `shareDestination`.
https://github.com/Expensify/App/blob/2f750ad9fad7be1b1e4095a778385ea5a2f06f3b/src/libs/actions/Task.js#L530-L543
Please note `openReport` is called

To get display information of the assignee, `Task.getAssignee` is called and you'll get the icons by `ReportUtils.getIconsForParticipants`
https://github.com/Expensify/App/blob/2f750ad9fad7be1b1e4095a778385ea5a2f06f3b/src/libs/actions/Task.js#L584-L588

To get display information of the shareDestination, `Task.getShareDestination` is called and you'll get the icons by `getIconsForParticipants` function.

That is, you'll get the icons for the `assignee` and `shareDestination` with the same function and same parameters(`[participantAccountIDs]`, `personalDetails`).

The main problem is accountID. When open the new chat with new account, `OpenReport` API returns new `personalDetails` data and new `[participantAccountIDs]`. So we use old optimistic accountID for assignee(from onyx store), and use new `accountID` for `shareDestination`(from report). That's why `shareDestination` and assignee has the same icon for a while, and has different icon after that.

This is the root cause.

### What changes do you think we should make in order to solve the problem?

When open new report with new account, `OpenReport` API returns new `personalDetails` data and new `[participantAccountIDs]`. So `personalDetails` has two account information for the same user, one is optimistic data, the other is one returned from the API.

1. Remove the old one when API successes. Add the following code [here](https://github.com/Expensify/App/blob/2f750ad9fad7be1b1e4095a778385ea5a2f06f3b/src/libs/actions/Report.js#L488)
```
        onyxData.successData.push({
            onyxMethod: Onyx.METHOD.MERGE,
            key: ONYXKEYS.PERSONAL_DETAILS_LIST,
            value: failurePersonalDetails,
        });
```

2. When call `Task.getAssignee`, add additional parameter `props.task.assignee`(this is an assignee login)
```
        const displayDetails = Task.getAssignee(props.task.assigneeAccountID, props.task.assignee, props.personalDetails);
```

To find the new accountID, add the following code in `getAssignee` function in Task.js
```
    if (!details) {
        details = _.find(personalDetails, (detail) => lodashGet(detail, 'login', lodashGet(detail, 'displayName', '')) === assigneeLogin);
    }
```

This way we can synchronize the `assignee` and `shareDestination`

<details>
    <summary>Result</summary>

https://github.com/Expensify/App/assets/126839717/60b02a4c-8966-4ee7-8fef-cba2f7b958c8

</details>

### What alternative solutions did you explore? (Optional)

**Comment by s-alves10** [comment] 2023-08-03 05:42
@spcheema 

This is the case for the new account. I'm afraid I didn't catch you. 
Will you explain in more detail?

**Comment by twisterdotcom** [comment] 2023-08-03 21:46
From @s-alves10:

>Remove the old one when API successes.

From @dukenv0307:

>After the server returns the accountID we should re-set assigneeAccountID to this accountID. With this approach, we only have one accountID for new assignee.

I _think_ this makes sense, but let's get an expert opinion. I'm not sure how these differ, but it sounds like they're basically both solving the optimistic extra accountID in different ways. Regardless, this is a bug.

**Comment by twisterdotcom** [comment] 2023-08-03 21:47
@aimane-chnaif please shed some light on this and let's get somebody assigned.

**Comment by StevenKKC** [comment] 2023-08-04 08:59
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
Avatar for the same new user is different in Assignee and Share somewhere fields.

### What is the root cause of that problem?
When select a new assignee in confirm task page, `Task.setAssigneeValue` is called.
In this function, app generates new account id and new chat report and sends `OpenReport` API.
https://github.com/Expensify/App/blob/c3bafa67302f5de421c260f3688b5fca656cdc06/src/libs/actions/Task.js#L550
https://github.com/Expensify/App/blob/c3bafa67302f5de421c260f3688b5fca656cdc06/src/libs/actions/Task.js#L556
https://github.com/Expensify/App/blob/c3bafa67302f5de421c260f3688b5fca656cdc06/src/libs/actions/Task.js#L564
After `OpenReport API` success, BE responds with the valid id for new account and chat report information that have a valid account id in `participantAccountIDs` field.
![Screenshot 2023-08-04 045722](https://github.com/Expensify/App/assets/131836113/cdeb73db-93f3-4271-80aa-1837c8338b11)

As a result, there are two account information in `Onyx`.
Since report's `participantAccountIDs` field contains the correct account id (i.e. the id BE returns), `Share somewhere` field is updated as well.
However, the assignee id is stored in the `task` `onyx` data, which is left with the invalid account id (i.e. the id generated by the app), so the `Assignee field` remains unchanged.

Therefore, avatars are different in `Assignee` and `Share somewhere` fields.
### What changes do you think we should make in order to solve the problem?

Removing invalid generated account information will be fixed in [this issue] (https://github.com/Expensify/App/issues/21706).

We should update the `task` `assigneeAccountID` to valid id (i.e. the account id in `participantAccountIDs` field of the task report) as below.
```js
    useEffect(() => {
        ...
        if (props.task.shareDestination) {
-           setParentReport(lodashGet(props.reports, `report_${props.task.shareDestination}`, {}));
+           const report = lodashGet(props.reports, `report_${props.task.shareDestination}`, {});
+           setParentReport(report);
            const displayDetails = Task.getShareDestination(props.task.shareDestination, props.reports, props.personalDetails);
            setShareDestination(displayDetails);

+           const participants = lodashGet(report, 'participants', {});
+           const participantAccountIDs = lodashGet(report, 'participantAccountIDs', {});

+            if (participants.length === 1 && participants[0] === props.task.assignee && participantAccountIDs !== props.task.assigneeAccountID) {
+                Task.setAssigneeAccountID(participantAccountIDs[0]);
            }
        }
    }, [props]);
```

And add a utility function in `Task.js`.
```js
    function setAssigneeAccountID(assigneeAccountID) {
        Onyx.merge(ONYXKEYS.TASK, {assigneeAccountID});
    }
```
### What alternative solutions did you explore? (Optional)
None.

**Comment by twisterdotcom** [comment] 2023-08-07 10:02
bump @aimane-chnaif.

**Comment by twisterdotcom** [comment] 2023-08-10 10:57
Bump again. Messaged in Slack too.

**Comment by twisterdotcom** [comment] 2023-08-18 10:07
Apologies but I am finally going on Parental Leave. I am reassigning to another member of the team.

**Comment by sakluger** [comment] 2023-09-15 02:06
Okay, removing hold and moving back to daily.

**Comment by sakluger** [comment] 2023-09-18 07:51
@aimane-chnaif what's the next step here? Do we need brand new proposals?

**Comment by sakluger** [comment] 2023-09-25 15:40
@s-alves10 @dukenv0307 @StevenKKC would you like to submit an updated proposal?

**Comment by sakluger** [comment] 2023-09-29 04:26
Ah okay, I'll close it.

**Closed by sakluger** 2023-09-29 04:26 UTC
Labels: External, Daily, Help Wanted, Overdue, Bug
