### ISSUE TITLE
[$500] Web - Total Split amount is not displayed on participant LHN

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#35679] opened 2024-02-02 17:24 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.36-0
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**If this was caught during regression testing, add the test name, ID and link from TestRail:** https://expensify.testrail.io/index.php?/tests/view/4263495
**Email or phone of affected tester (no customers):** gocemate@gmail.com
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** Applause - Internal Team
**Slack conversation:**

## Action Performed:Precondition:
User A and User B (gmail accounts) does not have previous conversation
1. User A creates group chat with User B and User C
2. User A creates Split bill
3. Take a look at User's B LHN

## Expected Result:
Total Split bill amount should be present on User's B LHN

## Actual Result:
Only shared Split bill amount is present on User's B LHN. Total can only be seen in Search results list

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details> 

https://github.com/Expensify/App/assets/78819774/b5249080-d02a-4ee8-984a-e3f8f551a393

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01b4ee716715d2a5b2</li>
        <li>Upwork Job ID: 1753469336800477184</li>
        <li>Last Price Increase: 2024-02-02</li>
    </ul>
</details>

**Comment by lanitochka17** [comment] 2024-02-02 17:25
We think that this bug might be related to [#vip-split-p2p-chat-groups](https://expensify.enterprise.slack.com/archives/C05RECHFBEW)

**Comment by cjoshi-zeals** [comment] 2024-02-02 17:35
What is expected out of it it should show the total amount only. and not the requested amount?

**Comment by promisingcoder** [comment] 2024-02-02 19:19
solution : 
In IOU.js, ensure that the total amount is correctly calculated and included in the splitData:
javascript
const totalAmount = calculateTotalAmount(participants, amount);
const {splitData, splits, onyxData} = createSplitsAndOnyxData(participants, currentUserLogin, currentUserAccountID, totalAmount, comment, currency, category, existingSplitChatReportID);

In MoneyRequestPreview.js, update the component to display the total amount:
javascript
const totalAmount = props.iouReport.totalAmount || '';
// ...
<Text style={styles.totalAmount}>{totalAmount}</Text>

**Comment by s77rt** [comment] 2024-02-02 19:47
@cjoshi-zeals Both reports should be in LHN

**Comment by s77rt** [comment] 2024-02-02 19:48
@promisingcoder Please follow the proposal template (check [contributing guide](https://github.com/Expensify/App/blob/main/contributingGuides/CONTRIBUTING.md))

**Comment by cjoshi-zeals** [comment] 2024-02-03 04:16
Like this? 

![Screenshot 2024-02-03 at 9 45 24 AM](https://github.com/Expensify/App/assets/91712307/a40fa91d-ea45-47e0-a782-25155ff5a2cd)

**Comment by s77rt** [comment] 2024-02-03 19:31
@cjoshi-zeals No, there should be two reports in the LHN: the 1:1 report with the requester showing your due amount and the group report showing the total split amount.

**Comment by Tony-MK** [comment] 2024-02-03 22:16
## Proposal

### Please re-state the problem that we are trying to solve in this issue.

### What is the root cause of that problem?

`accountIDs` is taken from the `report.visibleChatMemberAccountIDs` array.

https://github.com/Expensify/App/blob/3ab4e6e12d9ff38e69493321f0d31f032481b373/src/libs/OptionsListUtils.ts#L1457

When computing the value of `result.tooltipText` using the `ReportUtils.getReportParticipantsTitle` function, `report.visibleChatMemberAccountIDs` is also used.

https://github.com/Expensify/App/blob/3ab4e6e12d9ff38e69493321f0d31f032481b373/src/libs/OptionsListUtils.ts#L663

This conversation on [Slack](https://expensify.slack.com/archives/C01GTK53T8Q/p1705943996381799?thread_ts=1705943340.999379&cid=C01GTK53T8Q) explains that when `notificationPreference=hidden` is present, which this true in this case, `report.visibleChatMemberAccountIDs` should empty because the user didn't actively join yet.

![Onyx Report Record](https://github.com/Expensify/App/assets/22982173/d04e1870-1cbf-46b7-9a75-16888f7f7f76)

Therefore the `item.accountID` will be `NaN`.

### What changes do you think we should make in order to solve the problem?


Instead of using `report.visibleChatMemberAccountIDs` for `accountIDs` over [here](https://github.com/Expensify/App/blob/3ab4e6e12d9ff38e69493321f0d31f032481b373/src/libs/OptionsListUtils.ts#L1457) and [here](https://github.com/Expensify/App/blob/3ab4e6e12d9ff38e69493321f0d31f032481b373/src/libs/OptionsListUtils.ts#L663), we should use the `ReportUtils.getParticipantsIDs` function.

For consistency, this solution borrows from the `LHNOptionsList` component displayed below.

https://github.com/Expensify/App/blob/3ab4e6e12d9ff38e69493321f0d31f032481b373/src/components/LHNOptionsList/LHNOptionsList.tsx#L65

**Comment by s77rt** [comment] 2024-02-04 23:14
@Tony-MK Thanks for the proposal. Your RCA makes sense but the use of `visibleChatMemberAccountIDs` is actually [intended](https://github.com/Expensify/App/pull/30863).

🎀 👀 🎀 This seems internal.

When creating a group, all participants should be visible. cc @rlinoz

**Comment by getusha** [comment] 2024-02-05 03:21
Looks like this is a dupe of https://github.com/Expensify/App/issues/35537, if it is internal it can be handled here.

**Comment by cristipaval** [comment] 2024-02-07 15:53
haven't had the chance to look at this one yet.

**Comment by cristipaval** [comment] 2024-02-07 16:09
Melv?

**Comment by stephanieelliott** [comment] 2024-02-13 07:16
Hey Cristi, will you have a chance to look at this one this week?

**Comment by cristipaval** [comment] 2024-02-14 22:04
I can't reproduce this one. It has been fixed. Could you confirm?

**Comment by stephanieelliott** [comment] 2024-02-16 06:41
Yep, no longer able to repro. Closing!

**Closed by stephanieelliott** 2024-02-16 06:41 UTC
Labels: External, Daily, Help Wanted, Bug
