### ISSUE TITLE
[HOLD for payment 2022-11-09] [$1,000] Android - add attachment drawer animation is janky 

### ISSUE THREAD

**Issue by mvtglobally** [Expensify/App#11059] opened 2022-09-16 15:10 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Navigate to any chat 
2. Click on the "+" in the compose box 
3. try to add attachment 

## Expected Result:
Transition should be smooth 

## Actual Result:
1. When you tap the + button in the compose box
4. The gray overlay flashes, leaving some space at the bottom that isn't covered by the overlay
5. The tray showing up in two "steps" instead of a smooth slide up

## Workaround:
unknown

## Platform:

Where is this issue occurring?

- Android

**Version Number:** 1.2.0-0
**Reproducible in staging?:** Y 
**Reproducible in production?:** needs repro 
**Email or phone of affected tester (no customers):** 
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation 

https://user-images.githubusercontent.com/43995119/190671691-54019588-d8a0-4211-a549-556eea7c39da.mp4

**Expensify/Expensify Issue URL:** 
**Issue reported by:** @alex-mechler @cead22 
**Slack conversation:** https://expensify.slack.com/archives/C01GTK53T8Q/p1662396446776909

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by Gonals** [comment] 2022-09-20 14:08
Good candidate for external!

**Comment by NicMendonca** [comment] 2022-09-20 21:08
Job posting: https://www.upwork.com/jobs/~0199b6f2d618d1d175

**Comment by Smart133594** [comment] 2022-09-20 21:12
May I fix this issue?
I have no upwork account so I cannot make proposal but I can fix this

**Comment by NicMendonca** [comment] 2022-09-21 21:18
@Smart133594 because we issue payment via Upwork, an Upwork account is required.

**Comment by NicMendonca** [comment] 2022-10-03 11:59
doubled price: https://www.upwork.com/jobs/~0199b6f2d618d1d175

**Comment by JmillsExpensify** [comment] 2022-10-05 22:36
@NicMendonca Mind double the price again? Reasoning is that this is tied up with a roadmap item, so I want to ensure that the price is in line with our internal priority for it as well. Thanks!

**Comment by Uros787** [comment] 2022-10-10 11:18
### Proposal
The issue here is with timing and easing of the transition for backdrop and bottom modal.
You see, the default value for speed according to [docs](https://www.npmjs.com/package/react-native-modal) is 300

With that in mind we have two options, we either slow down the backdrop fade in appearing, or we speed up the bottom modal appearing.
For me personally, slowing down could give a bit of a feel that app is slower
So I would choose we go with speeding up the modal appearance. 

How can we do that:
We would need to pass a property called animationInTiming from [popover menu](https://github.com/Expensify/App/blob/6551eb9d07f54c222bd6cb7411b7613f3ccd03b4/src/pages/home/report/ReportActionCompose.js)(where this Is called) to [Base Modal component](https://github.com/Expensify/App/blob/e7c44da13bd4b8f270868073e8d3d0c7ddcb276c/src/components/Modal/BaseModal.js)
I'd recommend that we go with value of 100, because it gives a nice feel that animation is not too fast and satisfies our needs 

Here is a video

https://user-images.githubusercontent.com/70144379/194364229-e91903b4-fbcd-4528-8d73-60ea3a0694cf.mov

**Comment by NicMendonca** [comment] 2022-10-10 13:50
doubled price: https://www.upwork.com/jobs/~0199b6f2d618d1d175

bump @mananjadhav on the proposal above ☝️

**Comment by mananjadhav** [comment] 2022-10-10 16:45
@Uros787 Are you able to reproduce this at your end? And can you confirm that after your fix it is working fine?

Also I am not able to figure out what parts are you going to change. I can see you've linked two files `ReportActionCompose` and `BaseModal`, but can you post which lines of code will change and what props will be updated?

**Comment by Uros787** [comment] 2022-10-10 17:56
Yes sir, I was able to reproduce it on Android and the solution is working smoothly.

The solution consists of changes in 4 files since we are going to send a prop down from ReportActionCompose to BasePopoverMenu.
And also we would need to change popoverPropTypes, and popoverMenuPropTypes

**Comment by NicMendonca** [comment] 2022-10-13 20:12
@mananjadhav any feedback on @Uros787 [update](https://github.com/Expensify/App/issues/11059#issuecomment-1273648200)?

**Comment by mananjadhav** [comment] 2022-10-14 22:27
Thanks for the bump @NicMendonca . 

@Uros787 I am fine with the animation going as fast as 100ms. 

Let's get an input from @Expensify/design to see what they think about this.

**Comment by michelle-thompson** [comment] 2022-10-14 22:46
Looks good, but I'm curious how this compares with other drawer speeds (e.g. opening up the menu from the big green plus)?

**Comment by NicMendonca** [comment] 2022-10-18 12:25
@mananjadhav ☝️

**Comment by mananjadhav** [comment] 2022-10-18 18:24
Thanks for the bump @michelle-thompson. Sorry I didn't get a notification.  Other drawers should be at 300 with the default value, and the Skeleton UI animation is at 100.

**Comment by shawnborton** [comment] 2022-10-18 18:47
Cool, I think what we have in the video above would be good to go then.

**Comment by mananjadhav** [comment] 2022-10-18 19:26
Okay thanks for the comment @shawnborton. @Uros787 Your proposal here https://github.com/Expensify/App/issues/11059#issuecomment-1273160490 looks fine. While it is missing some details on the actual changes, the expected behavior looks good and we can work out the kinks in the PR.

@shawnborton You being the CME, I guess you'll have to assign the job.

🎀 👀 🎀 
C+ reviewed

**Comment by shawnborton** [comment] 2022-10-18 19:27
@NicMendonca all you!

**Comment by NicMendonca** [comment] 2022-10-21 12:42
@Uros787 the job posting is [here](https://www.upwork.com/jobs/~0199b6f2d618d1d175), thanks!

**Comment by Smart133594** [comment] 2022-10-21 13:43
Hi, only upwork is possible for your job?
Directly hire impossible?

**Comment by mananjadhav** [comment] 2022-10-21 13:50
@Smart133594 Thanks for the comment, but we make our Payments via Upwork. So while the proposal review, and PR etc. is all done via Github, the payment happens only via Upwork only! Please check the our [contributing guidelines](https://github.com/Expensify/App/blob/main/contributingGuides/CONTRIBUTING.md) here

**Comment by Smart133594** [comment] 2022-10-21 14:03
Thanks but if I have no upwork account and I want also work on this.
How can I? May I use other man's account?

**Comment by NicMendonca** [comment] 2022-10-24 13:20
@Uros787 hired on upwork 😊

**Comment by Smart133594** [comment] 2022-10-24 13:28
If you have other tasks, could you contact me?

**Comment by mananjadhav** [comment] 2022-10-24 20:54
I'll do the second round of review by tomorrow.

**Comment by NicMendonca** [comment] 2022-10-27 13:00
@mananjadhav any updates here? Thanks!

**Comment by mananjadhav** [comment] 2022-10-27 13:21
Sorry for the delay here, travelling due to festive week. But I'll posted a comment on the PR. Once done I'll test the changes.

**Comment by mananjadhav** [comment] 2022-10-31 07:38
PR is merged. I am not sure what needs to be done for the BugZero Checklist. @NicMendonca @shawnborton  ?

**Comment by NicMendonca** [comment] 2022-11-02 12:54
@mananjadhav we're discussing internally[ here,](https://expensify.slack.com/archives/C01SKUP7QR0/p1667247285616069) so I'll come back with more info asap!

**Comment by mananjadhav** [comment] 2022-11-10 13:26
@NicMendonca  @miljakljajic  This is due payment but I am not sure what happened here with the tags and reassignment?

**Comment by miljakljajic** [comment] 2022-11-10 13:43
Thank you, Manan. Uros was already hired for the job, so he has been paid. Awaiting your approval of the offer and I'll pay you for your contribution immediately.

**Comment by mananjadhav** [comment] 2022-11-10 14:06
Applied @miljakljajic. Any action pending from my side here @miljakljajic?

**Comment by miljakljajic** [comment] 2022-11-10 14:17
Thank you - job is now closed, both of you have been paid.

**Closed by miljakljajic** 2022-11-10 14:17 UTC
Labels: External, Engineering, Daily, Improvement, Help Wanted, Awaiting Payment, Bug
