### ISSUE TITLE
[HOLD for payment 2023-10-09] [$500] Web - Task preview -  phone number contact is displayed @expensify.sms

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#27330] opened 2023-09-13 11:43 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Login with new account
2. Create a WS
3. Invite user phone number account (user B) into WS
4. Open the announce rom
3. Click + on composer
4. Click assign task
5. Input title and click next
6. Assign above account B
7. Click confirm
8. Click From.... on header, Observe that on the task preview , the phone number contact is displayed with @expensify.sms in the end

## Expected Result:
App should display phone number or the display name

## Actual Result:
App display phone number with @expensify.sms in the end

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [x] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 1.3.67.13
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/93399543/0fc81565-aeb9-42e2-b77b-d65ee2e96500

https://github.com/Expensify/App/assets/93399543/bd075017-3d7e-40cb-b087-bbb4111f754c

**Expensify/Expensify Issue URL:**
**Issue reported by:** @namhihi237
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1694333604061429

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by flaviadefaria** [comment] 2023-09-14 18:43
@sonialiap I was about to unassign you, since you seem to have been assigned in duplicity, but since I'm going OoO for 1 week I'll leave you assigned to it so that you can move this forward while I'm OoO. I'll then take it back once I'm online again.

**Comment by sonialiap** [comment] 2023-09-18 09:06
@cubuspl42 what do you think of the above proposal?

**Comment by cubuspl42** [comment] 2023-09-18 10:20
@kbecciv How did you conclude the expected behavior?

I also started [an internal thread](https://expensify.slack.com/archives/C02NK2DQWUX/p1695032298690209) to figure out the external behavior.

**Comment by kbecciv** [comment] 2023-09-20 18:34
@cubuspl42 The expected result are correct. @expensify.sms should NOT be visible anywhere in the app.

**Comment by sonialiap** [comment] 2023-09-21 04:09
not overdue

**Comment by cubuspl42** [comment] 2023-09-21 07:57
> @cubuspl42 The expected result are correct. @expensify.sms should NOT be visible anywhere in the app.

You're probably right, but I still have a feeling that just replacing it with a raw number itself (keeping the "@") might not be appropriate either. Maybe this component was designed without taking phone numbers into consideration?... I'll try to figure that out, I'll let you know what I find out.

**Comment by cubuspl42** [comment] 2023-09-22 08:37
Assuming that the described expected result is actually expected here, the solution by @namhihi237 makes sense.

C+ reviewed 🎀 👀 🎀

**Comment by cubuspl42** [comment] 2023-09-22 08:38
@Julesssss Please let me know if you agree with the described expected result. I tried to get clarification [in this thread](https://expensify.slack.com/archives/C02NK2DQWUX/p1695032298690209), but got no responses.

**Comment by Julesssss** [comment] 2023-09-26 02:28
Sorry @cubuspl42 I missed these comments somehow... 

I agree the ordering of the `contact|email` condition should be reversed. But in addition, we need to avoid showing `@expensify.sms` in the app as Sonia mentioned above. 

We usually do this on the backend, but given that this can happen optimistically we might need to introduce a function to newdot to strip out `CONST.SMS.DOMAIN` when displaying contacts. 

That's the solution we should be looking for.

**Comment by Julesssss** [comment] 2023-09-26 05:24
Ahhh, it's in the Str library... That explains why I couldn't find it existing anywhere already 😖 

@namhihi237 your proposal seems good, but maybe we can also flip this condition? So that way we are using the display name by default. 

`const taskAssignee = LocalePhoneNumber.formatPhoneNumber(assigneeLogin) || assigneeDisplayName;`

**Comment by Julesssss** [comment] 2023-09-26 05:38
Yep, looks good to me.

**Comment by cubuspl42** [comment] 2023-09-26 08:50
@namhihi237 Just for clarity, the C+ review is followed by the internal engineer verification, and they could decide not to assign the contributor, even if the proposal got the C+ recommendation.

I'm just ensuring the process is clear here. You are assigned, so we can proceed to work on the PR.

**Comment by cubuspl42** [comment] 2023-10-06 11:22
- The PR that introduced the bug has been identified. Link to the PR:
    -  It seems that the bug was present in the relevant components since they were created
- The offending PR has been commented on, pointing out the bug it caused and why, so the author and reviewers can learn from the mistake. Link to comment:
    - N/A
- A discussion in #expensify-bugs has been started about whether any other steps should be taken (e.g. updating the PR review checklist) in order to catch this type of bug sooner. Link to discussion:
    - No need for additional discussion
- Determine if we should create a regression test for this bug.
    - Up to the QA team
- If we decide to create a regression test for the bug, please propose the regression test steps to ensure the same bug will not reach production again.
  - Create a new workspace
  - Invite a user, using their phone number account, into the workspace (for example: +84989402048)
  - Access the #announce room
  - Click the '+' symbol on the composer
  - Select the 'Assign Task' option
  - Enter the desired title and click 'Next'
  - Assign this task to the aforementioned user B
  - Confirm your actions by clicking 'Confirm'
  - Click on the header to go back to the parent report, and verify if the preview of the task does not include '@expensify.sms'

**Comment by flaviadefaria** [comment] 2023-10-09 10:18
Switching this to daily so that I can issue payment this week.

**Comment by flaviadefaria** [comment] 2023-10-11 09:40
Payment summary:

@cubuspl42 - $500 + 50% bonus = $750
@namhihi237 - $500 + 50% bonus + $50 (reporting) = $800

**Comment by flaviadefaria** [comment] 2023-10-11 09:47
@cubuspl42 @namhihi237 offers sent!

**Comment by flaviadefaria** [comment] 2023-10-11 10:05
@namhihi237 - paid!

**Comment by flaviadefaria** [comment] 2023-10-11 18:33
@cubuspl42 please accept the offer so that I can pay you!

**Comment by cubuspl42** [comment] 2023-10-12 08:42
@flaviadefaria Done ✅

**Comment by flaviadefaria** [comment] 2023-10-12 10:56
Everyone has been paid so closing.

**Closed by flaviadefaria** 2023-10-12 10:56 UTC
Labels: External, Daily, Awaiting Payment, Bug
