### ISSUE TITLE
[$250]  `Hold` is not displayed in the preview for the expense which is held

### ISSUE THREAD

**Issue by m-natarajan** [Expensify/App#46158] opened 2024-07-25 01:51 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 9.0.11-5
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** @puneetlath 
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1721848036803009

## Action Performed:
1. Submit a report with 2 expenses and with a violation
2. Sign in as  a approver
3. Open the report 
4. Put the expense on Hold which has violation
5. Look at the expense preview
## Expected Result:
Preview should show "Hold"
## Actual Result:
Violation error only appears. Hold should take higher priority
## Workaround:
unknown
## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

https://github.com/user-attachments/assets/8db49622-ab29-4d1e-a196-bdd5c15c970c

![image (8)](https://github.com/user-attachments/assets/e22e7fdb-347d-4ade-b327-f76948727fd8)

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01081754863788f760</li>
        <li>Upwork Job ID: 1819385736069367085</li>
        <li>Last Price Increase: 2024-08-16</li>
<li>Automatic offers: </li>
<ul>
<li>shubham1206agra | Reviewer | 103593386</li>
</ul></li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @dylanexpensify</details>

**Comment by bernhardoj** [comment] 2024-07-25 09:39
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
Hold error message isn't prioritized to be displayed.

### What is the root cause of that problem?
This is actually the same issue as https://github.com/Expensify/App/issues/44509. However, the selected solution doesn't prioritize hold, but prioritize violation type of violation. I also posted a proposal there to prioritize the hold, so I'm gonna copy and update it here a little bit since we also want to prioritize hold over review required when there is too many violations.

When showing the violation, we only take the first violation.
https://github.com/Expensify/App/blob/b0f810df06c3df866b7fdbed4959f8f1fef803ed/src/components/ReportActionItem/MoneyRequestPreview/MoneyRequestPreviewContent.tsx#L196-L207

We previously prioritized hold in this [PR](https://github.com/Expensify/App/pull/40153), but was [reverted](https://github.com/Expensify/App/pull/43446) because it caused [double Hold to show up](https://github.com/Expensify/App/issues/43440). It's because we append the violation message (that contains hold) with another hold text. But it's not guaranteed that the hold violation is always at the first item of the violations.

### What changes do you think we should make in order to solve the problem?

If we want the hold to be prioritized over other violations, including Review required, then we can move this condition higher in the block.
https://github.com/Expensify/App/blob/b0f810df06c3df866b7fdbed4959f8f1fef803ed/src/components/ReportActionItem/MoneyRequestPreview/MoneyRequestPreviewContent.tsx#L220-L222
```
if (shouldShowHoldMessage) return hold message
if (violations[0]) ...
...
```

Last, we can "revert" https://github.com/Expensify/App/pull/45325 because we fix it differently here.

**Comment by bernhardoj** [comment] 2024-08-07 15:05
> Last, we can "revert" https://github.com/Expensify/App/pull/45325 because we fix it differently here.

> @bernhardoj Can you give a proper solution here?

Sorry, I don't get what do you mean by proper solution of the revert. Can you clarify it?

**Comment by bernhardoj** [comment] 2024-08-07 15:12
This one
<img width="890" alt="image" src="https://github.com/user-attachments/assets/71a7597d-fcd4-422c-a1d7-5e3a0b1b0974">

The current condition looks like this:
https://github.com/Expensify/App/blob/0a33186c80eb821d67d75b44bca527640204852c/src/components/ReportActionItem/MoneyRequestPreview/MoneyRequestPreviewContent.tsx#L194-L216

The solution will update it to:
```
if (shouldShowHoldMessage) return `${message} ${CONST.DOT_SEPARATOR} ${translate('violations.hold')}`;
if (violations[0]) ...
if (hasFieldErrors) ...
```

**Comment by dylanexpensify** [comment] 2024-08-21 10:19
Woot!

**Comment by dylanexpensify** [comment] 2024-08-28 10:48
merged!

**Comment by dylanexpensify** [comment] 2024-09-10 20:00
pending prod deploy

**Comment by roryabraham** [comment] 2024-09-13 07:45
Sorry for the confusion @dylanexpensify. I can confirm this was deployed to prod on 2024-08-28

**Comment by dylanexpensify** [comment] 2024-09-18 10:10
Payment summary:

Contributor: @bernhardoj $250 
Contributor+: @shubham1206agra $250 

Please apply/request!

**Comment by dylanexpensify** [comment] 2024-09-18 10:11
@shubham1206agra please accept offer! 🙇‍♂️

**Comment by dylanexpensify** [comment] 2024-09-18 10:11
@bernhardoj please apply to job! 🙇‍♂️

**Comment by bernhardoj** [comment] 2024-09-18 15:33
Requested in ND.

**Comment by JmillsExpensify** [comment] 2024-09-18 16:12
$250 approved for @bernhardoj

**Comment by dylanexpensify** [comment] 2024-09-23 17:54
done!

**Closed by dylanexpensify** 2024-09-23 17:54 UTC
Labels: External, Daily, Overdue, Awaiting Payment, Bug
