### ISSUE TITLE
[$500] Login - Expensify logo is too close to the top of the screen

### ISSUE THREAD

**Issue by izarutskaya** [Expensify/App#36575] opened 2024-02-15 12:56 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** v1.4.42-0
**Reproducible in staging?:** Y
**Reproducible in production?:** N
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** Applause-Internal team
**Slack conversation:**

## Action Performed:
1. Launch New Expensify app.
2. Log out if logged in.

## Expected Result:
There will be adequate spacing between Expensify logo and the top of the screen.

## Actual Result:
Expensify logo is too close to the top of the screen.

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [ ] Android: mWeb Chrome
- [x] iOS: Native
- [ ] iOS: mWeb Safari
- [ ] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

![Bug6380631_1708001287225!Production](https://github.com/Expensify/App/assets/115492554/234051c7-1ffd-4268-a5d8-555ae223af8e)
![Bug6380631_1708001287207!Staging](https://github.com/Expensify/App/assets/115492554/afc84d1e-4a09-4ef8-9f80-47aecc3e95bc)

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01f5aa21ec0e08e780</li>
        <li>Upwork Job ID: 1758113096034033664</li>
        <li>Last Price Increase: 2024-02-15</li>
<li>Automatic offers: </li>
<ul>
<li>getusha | Contributor | 0</li>
<li>rayane-djouah | Contributor | 0</li>
</ul></li>
    </ul>
</details>

**Comment by izarutskaya** [comment] 2024-02-15 12:57
We think that this bug might be related to #vip-vsb
CC @quinthar

**Comment by jjcoffee** [comment] 2024-02-15 14:27
@ZhenjaHorbach's proposal LGTM! I agree this is a regression from https://github.com/Expensify/App/pull/34837, so depending on urgency we may want to let @rayane-djouah take a stab at fixing this first.

:ribbon::eyes::ribbon: C+ reviewed

**Comment by Beamanator** [comment] 2024-02-15 14:50
I agree this should be fixed (& probably by the originating PR author) but not needed to fix asap as a deploy blocker

**Comment by situchan** [comment] 2024-02-15 15:14
@rayane-djouah and @getusha may handle this

**Comment by groovedevelopers** [comment] 2024-02-15 15:28
### Proposal
### Please re-state the problem that we are trying to solve in this issue.
Login - Expensify logo is too close to the top of the screen
### What is the root cause of that problem?
The position of the logo is not set well
### What changes do you think we should make in order to solve the problem?
set position to absolute and set the appropriate values for top, left

**Comment by groovedevelopers** [comment] 2024-02-15 15:30
Contributor details
Your Expensify account email: groovytee01@gmail.com
Upwork Profile Link: https://www.upwork.com/freelancers/~01565b0a8934c1826a

**Comment by jjcoffee** [comment] 2024-02-16 10:43
Unassigning as @getusha will be handling this. cc @puneetlath

**Comment by puneetlath** [comment] 2024-02-16 18:36
@rayane-djouah mind commenting here so I can assign you?

**Comment by puneetlath** [comment] 2024-02-19 22:18
@rayane-djouah @getusha how's this going?

**Closed** 2024-03-13 23:23 UTC
Labels: Reviewing, External, Engineering, Weekly, Bug
