### ISSUE TITLE
[Request money, Split bill] Wrong payment value after pay elsewhere then relogin

### ISSUE THREAD

**Issue by kavimuru** [Expensify/App#24051] opened 2023-08-02 10:57 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Account 1 send a request money or split bill to account 2
2. Account 2 confirm "Pay elsewhere"
3. Account 1 or Account 2 logout and login again
4. Observer payment value
## Expected Result: 
the value should be the same value after logout
## Actual Result: 
the value always dive 1000, after view detail and go back the value is correct

## Workaround:
Can the user still use Expensify without this being fixed? Have you informed them of the workaround?

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [x] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:**
**Reproducible in staging?:** needs reproduction requires VPN 
**Reproducible in production?:** needs reproduction 
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation

[New-Expensify.webm](https://github.com/Expensify/App/assets/43996225/7c1578ac-59ad-40ec-a7d1-13b23414d3fb)

**Expensify/Expensify Issue URL:**
**Issue reported by:** @suneox
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1690736985842159

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by suneox** [comment] 2023-08-02 13:01
Hi @kavimuru, production still happen in Japan

https://github.com/Expensify/App/assets/11959869/f80f4108-b4fd-4f19-b75e-aa06edded7e1

**Comment by kadiealexander** [comment] 2023-08-03 06:49
Closing as a dupe of https://github.com/Expensify/App/issues/22946

**Closed by kadiealexander** 2023-08-03 06:49 UTC
Labels: Daily, Needs Reproduction, Bug

**Comment by suneox** [comment] 2023-08-03 09:22
@kadiealexander an issue #22946 maybe has fixed and cannot re-produce with usd follow description, this issue still happens with currency decimal is 0 . Are you trying to vpn to japan and using new account? So for me this is valid bug because my description in slack channel is detail to verify this bug
