### ISSUE TITLE
[HOLD for payment 2023-08-02] [$1000] App does not focus on compose box on mark as read/unread when we visit other profile and get back

### ISSUE THREAD

**Issue by kavimuru** [Expensify/App#21739] opened 2023-06-27 19:44 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Open the app
2. Open any group report
3. Right click on group report in LHN and click on mark as read/unread to observe that it focuses on compose box
4. Now open group details page by clicking on group avatar, click on any user and click on message
5. Use browser back button to get back to group chat, right click on group chat in LHN and click on mark as unread
6. Observe the it does not focus on compose box
## Expected Result: 
App should focus on compose box on click of mark as unread/read for any chat from LHN
## Actual Result: 
App does not focus on compose box on click of mark as unread/read for group chat from LHN if we open group details, click on any user, click message and click on browser back to come back to group chat

## Workaround:
Can the user still use Expensify without this being fixed? Have you informed them of the workaround?

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [x] MacOS / Chrome / Safari
- [x] MacOS / Desktop

**Version Number:** 1.3.33-4
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/43996225/04a8c119-789d-453f-adf9-0da4a6593b03

https://github.com/Expensify/App/assets/43996225/5899072b-fcb4-40df-928c-fb3fc7566561

**Expensify/Expensify Issue URL:**
**Issue reported by:** @dhanashree-sawant
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1687606178130269

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~012eff16d4d91d5c21</li>
        <li>Upwork Job ID: 1673981095886499840</li>
        <li>Last Price Increase: 2023-07-12</li>
    </ul>
</details>

**Comment by conorpendergrast** [comment] 2023-06-28 09:06
Reproduced on OSX desktop app too

**Comment by bernhardoj** [comment] 2023-06-28 11:38
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
After going back from another chat, the composer won't focus after pressing Mark as read/unread. To be clearer, the composer focus manager doesn't work.

### What is the root cause of that problem?
We have a composer focus manager that will listen to any call of `ReportActionComposeFocusManager.focus()`.
https://github.com/Expensify/App/blob/94e265653f83505e581e99ac0ec0d3ea30e23998/src/pages/home/report/ReportActionCompose.js#L229-L237

When we open chat A, a listener is added.
https://github.com/Expensify/App/blob/94e265653f83505e581e99ac0ec0d3ea30e23998/src/libs/ReportActionComposeFocusManager.js#L7-L15

Navigating to chat B will replace the A listener with B. When we press back from B, B will unmount and the listener is cleared.
https://github.com/Expensify/App/blob/94e265653f83505e581e99ac0ec0d3ea30e23998/src/pages/home/report/ReportActionCompose.js#L275-L277

### What changes do you think we should make in order to solve the problem?

Initialize the listener on both mount and update. On update, only add the listener if the screen becomes focused, i.e.
```
if (!prevProps.isFocused && this.props.isFocused) { focusManager.onComposerFocus() }
```

### What alternative solutions did you explore? (Optional)
Currently, we only store the latest callback. Instead, 

1. We can change it to an array and push a new callback every time a new listener is added.
2. Return a function to unsubscribe it instead of using `clear`.
3. When calling `focus`, iterate over the array and invoke the callback

<details>
<summary>snippet</summary>

```
function onComposerFocus(callback) {
    const prevCallbacks = [...focusCallback];
    focusCallback.push(callback);
    return () => {
        focusCallback = prevCallbacks;
    }
}
function focus() {
    _.each(focusCallback, (callback) => {
        if (!_.isFunction(callback)) {
            return;
        }

        callback();
    });
}
```

</details>

**Comment by conorpendergrast** [comment] 2023-07-06 10:51
@aimane-chnaif Do any of these proposals look promising?

**Comment by conorpendergrast** [comment] 2023-07-11 14:53
@aimane-chnaif Still nothing?

**Comment by conorpendergrast** [comment] 2023-07-26 08:28
@bernhardoj A reminder to [apply to the Upwork job please](https://www.upwork.com/jobs/~012eff16d4d91d5c21)!

**Comment by conorpendergrast** [comment] 2023-08-02 16:17
Payouts due:

- [ ] Issue Reporter: $250 @dhanashree-sawant
- [ ] Contributor: $1000 + 50% urgency bonus = $15000 @bernhardoj 
- [ ] Contributor+: $1000 + 50% urgency bonus = $15000 @aimane-chnaif 

Eligible for 50% #urgency bonus? Y

Upwork job is [here](https://www.upwork.com/ab/applicants/1673981095886499840/job-details)

**Comment by conorpendergrast** [comment] 2023-08-02 18:58
Everyone paid. @aimane-chnaif C+ checklist, please, and then I'll do a regression test (if necessary) and we can close this out

**Comment by conorpendergrast** [comment] 2023-08-03 12:13
Alright, then we're all done. Thank you!

**Closed by conorpendergrast** 2023-08-03 12:13 UTC
Labels: External, Engineering, Daily, Awaiting Payment, Bug
