### ISSUE TITLE
[HOLD for payment 2024-08-01] [$125] Workspace - Avatar for a deleted workspace is empty when viewed full screen

### ISSUE THREAD

**Issue by m-natarajan** [Expensify/App#45842] opened 2024-07-20 15:18 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 9.0.10-2
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:** n/a
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:**  Applause internal team
**Slack conversation:** 

## Action Performed:
1. Go to staging.new.expensify.com
2. Create a new workspace.
3. Go to workspace chat.
4. Click on the chat header.
5. Click workspace avatar.
6. Note that it opens avatar in full screen.
7. Delete the workspace.
8. Go to workspace chat.
9. Click on the chat header.
10. Click workspace avatar.

## Expected Result:
Avatar for a deleted workspace will still display when viewed full screen.
## Actual Result:
Avatar for a deleted workspace is empty when viewed full screen.
## Workaround:
unknown
## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [x] Android: mWeb Chrome
- [x] iOS: Native
- [x] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

https://github.com/user-attachments/assets/cdd6e957-91ff-4080-a44c-c4e743323082

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01e8484784facf391c</li>
        <li>Upwork Job ID: 1814778937726286060</li>
        <li>Last Price Increase: 2024-07-20</li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @dylanexpensify</details>

**Comment by mountiny** [comment] 2024-07-20 20:17
@mollfpr @b4s36t4 This one seems related to your PR https://github.com/Expensify/App/pull/44702 can you please confirm if revert fixes it?

**Comment by mountiny** [comment] 2024-07-20 21:46
Not fixed with the revert

**Comment by mountiny** [comment] 2024-07-20 21:47
Exporting, but also I would say we can demote if we cannot find a fix soon before the deploy is ready as its minor ux issue

**Comment by Ahmed-Abdella** [comment] 2024-07-21 01:32
Not completely sure, but I think it comes from this PR #41586

**Comment by jaydamani** [comment] 2024-07-21 05:02
This issue stopped reproducing in the middle of investigation. Can you please confirm from your end if it works now?

**Comment by NJ-2020** [comment] 2024-07-21 14:13
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
The avatar for a deleted workspace is empty when viewed in full-screen
### What is the root cause of that problem?
When we delete the workspace, we delete the policy data, so when we check below if there is policy data we will use getWorkspaceAvatar else returns the report.avatarURL value, but we didn't have any avatarURL for this report so it will return undefined
https://github.com/Expensify/App/blob/f3a8f736208166286e6f7da3562f1503d5ef2a3d/src/pages/ReportAvatar.tsx#L44
Also same for the fileName here, we're checking if there is policy data we will return one of these:
`policy?.originalFileName ?? policy?.id ?? report?.policyID` else we will return `report?.avatarFileName` but the `report?.policyID` value is exist but it only run when there is a policy data, so it will return undefined
https://github.com/Expensify/App/blob/f3a8f736208166286e6f7da3562f1503d5ef2a3d/src/pages/ReportAvatar.tsx#L46
### What changes do you think we should make in order to solve the problem?
For the avatarURL, we can use the `ReportUtils.getWorkspaceAvatar(report)` method if the policy value exists or policy data is empty and report.avatarUrl is empty, else we will return the report.avatarURL
And for fileName, we can add `report?.policyID` to the else condition

### Here's the code:
```ts
if (policy || (!policy && !report.avatarUrl)) {
    avatarURL = ReportUtils.getWorkspaceAvatar(report);
} else {
    avatarURL = report.avatarUrl;
}
// In the case of default workspace avatar, originalFileName prop takes policyID as value to get the color of the avatar
fileName = policy ? policy?.originalFileName ?? policy?.id ?? report?.policyID : report?.policyID ?? report?.avatarFileName;
title = policy ? ReportUtils.getPolicyName(report, false, policy) : ReportUtils.getReportName(report);
shouldShowNotFoundPage = !isLoadingApp && !report?.reportID;
```
### What alternative solutions did you explore? (Optional)

**Comment by m-natarajan** [comment] 2024-07-21 14:47
@mountiny we have the same issue with rooms avatar as well. Should we create a separate GH.

https://github.com/user-attachments/assets/b7c45840-f9f7-4309-badb-6e649ca071e0

**Comment by mountiny** [comment] 2024-07-21 20:18
@m-natarajan I think you can add it to this one

**Comment by mountiny** [comment] 2024-07-21 20:24
@s77rt @nexarvo are you able to have a look, if not, there is a revert PR ready if we need to unblock the deploy

**Comment by abdulrahuman5196** [comment] 2024-07-24 08:22
@mountiny Seems there is a revert PR, should I need to do anything here?

**Comment by dylanexpensify** [comment] 2024-07-25 08:48
@VictoriaExpensify I'm heading OOO starting this afternoon, so reassigning for payment! TY!

**Comment by mountiny** [comment] 2024-07-25 23:19
This can be close as there was no c+ review on the revert

**Closed by mountiny** 2024-07-25 23:19 UTC
Labels: External, Engineering, Daily, Awaiting Payment, Bug
