### ISSUE TITLE
[$250] Desktop - Distance - Opens "Hmm it's not here" when you open the "Start" menu a second time

### ISSUE THREAD

**Issue by IuliiaHerets** [Expensify/App#47422] opened 2024-08-14 13:38 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** v9.0.20-0
**Reproducible in staging?:** Y
**Reproducible in production?:** N
**If this was caught during regression testing, add the test name, ID and link from TestRail:** https://expensify.testrail.io/index.php?/tests/view/4857130
**Email or phone of affected tester (no customers):** sustinov@applausemail.com
**Issue reported by:** Applause Internal Team

## Action Performed:
1. Open New Expensify app
2. Log in with a new HT account
3. Create a WS
4. Navigate to the WS room
5. Navigate + Menu - Submit expense - Distance - Start
6. Close the RHP by clicking outside the field
7. Navigate + Menu - Submit expense - Distance - Start

## Expected Result:
When you open the "Start" menu a second time, a waypoint entry field should appear

## Actual Result:
Opens "Hmm it's not here" when you open the "Start" menu a second time

## Workaround:
Unknown

## Platforms:

- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [ ] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

https://github.com/user-attachments/assets/574707b6-cd71-47c2-9f31-13b005eccf02

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~015866c373fa1fa23d</li>
        <li>Upwork Job ID: 1823829918353045323</li>
        <li>Last Price Increase: 2024-08-21</li>
<li>Automatic offers: </li>
<ul>
<li>rayane-djouah | Contributor | 103694978</li>
</ul></li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @jayeshmangwani</details>

**Comment by IuliiaHerets** [comment] 2024-08-14 13:38
We think that this bug might be related to #wave-collect - Release 1

**Comment by Beamanator** [comment] 2024-08-14 19:03
Hmm couldn't reproduce in `v9.0.20-5` in Web, will try desktop next

**Comment by Beamanator** [comment] 2024-08-14 21:06
oh ya def reproducible

console error:

```
Url.ts:48 Error parsing URLs: TypeError: Failed to construct 'URL': Invalid URL
```

**Comment by Beamanator** [comment] 2024-08-14 21:11
Though I donn't know if I'd reeeeeeally consider this a blocker blocker 🤷  maybe we can keep it open till someone can maybe help, but if it becomes the last blocker open we can NAB it

**Comment by NJ-2020** [comment] 2024-08-15 07:39
## Proposal

### Please re-state the problem that we are trying to solve in this issue.

### What is the root cause of that problem?
When we click the submit expense we initialize the money request by invoking the `IOU.initMoneyRequest` function.

Inside the `initMoneyRequest` function we check if the `currentTransaction.iouRequestType` is equal to selected current `iouRequestType` then we only need to update only few values of the draftTransaction and exit from the function
https://github.com/Expensify/App/blob/57ef25c998748332864ae98a43579989d6529c22/src/libs/actions/IOU.ts#L327-L337
And also every we click the submit expense we also invoke the `startMoneyRequest` and `clearMoneyRequest` function, and after clicking the start waypoint page and go back and click again the  submit expense button and go to start waypoint page again, the currentTransaction(draftTransaction) doesn't get clear because the `clearMoneyRequest` take a little bit longer than the web browser, but it got cleared after the initMoneyRequest if condition run

If we do on web browser we can see more faster action for the Onyx that the draft transaction is got cleared before the if statement run, and the comment.waypoint doesn't set with the correctly because inside the if statement we return (exit from the function)

But in web browser the if statement doesn't run because the draftTransaction got cleared first before the if condition run

https://github.com/Expensify/App/blob/57ef25c998748332864ae98a43579989d6529c22/src/libs/actions/IOU.ts#L381-L387

### What changes do you think we should make in order to solve the problem?
On `clearMoneyRequest` function we can return the Onyx.set for the transaction draft
https://github.com/Expensify/App/blob/57ef25c998748332864ae98a43579989d6529c22/src/libs/actions/IOU.ts#L381-L384
And we can use the `.then` method inside the `startMoneyRequest` function to wait until we clear the draftTransaction

https://github.com/Expensify/App/blob/57ef25c998748332864ae98a43579989d6529c22/src/libs/actions/IOU.ts#L386C10-L388

### Result:

https://github.com/user-attachments/assets/aed1acc5-afd9-497f-95e7-45cdde98403d

### What alternative solutions did you explore? (Optional)
We can use promise resolve, and resolve when the Onyx completed

**Comment by jayeshmangwani** [comment] 2024-08-15 12:52
@NJ-2020 Thanks for the proposal, but I'm unclear on a few points. Let me break it down below:

> But in web browser the if statement doesn't run because the draftTransaction got cleared first before the if condition run

Why is this happening only on desktop, and only on this page? If the desktop doesn't update data synchronously, it should be happening in other places too.



> we can use the .then method inside the startMoneyRequest function to wait until we clear the draftTransaction

I haven't noticed this pattern in any Onyx updates on the app. Could you please provide some examples if we're supposed to follow this pattern?

**Comment by jayeshmangwani** [comment] 2024-08-15 12:56
I was checking logs and noticed that the transaction data is incorrect on the desktop platform.





<details>
  <summary>It should be like this:</summary>
  
  
  ```js
  {
    "amount": 0,
    "comment": {
        "waypoints": {
            "waypoint0": {
                "keyForList": "start_waypoint"
            },
            "waypoint1": {
                "keyForList": "stop_waypoint"
            }
        },
        "customUnit": {
            "customUnitRateID": "3C14F0F0D0778"
        }
    },
    "created": "2024-08-15",
    "currency": "INR",
    "iouRequestType": "distance",
    "reportID": "4585884576347998",
    "transactionID": "1",
    "isFromGlobalCreate": false,
    "merchant": "(none)",
    "splitPayerAccountIDs": [
        18152125
    ]
}
  ```
</details>





<details>
  <summary>But instead, it's like this (no comment waypoints data is included):</summary>
  
  
  ```js
  {
    "amount": 0,
    "comment": {},
    "created": "2024-08-15",
    "currency": "INR",
    "iouRequestType": "manual",
    "reportID": "4585884576347998",
    "transactionID": "1",
    "isFromGlobalCreate": false,
    "merchant": "(none)",
    "splitPayerAccountIDs": [
        18152125
    ]
}
  ```
</details>

**Comment by jayeshmangwani** [comment] 2024-08-15 13:03
@puneetlath @Beamanator Though it's an hourly issue, I still believe we should avoid adding the promise for the Onyx set until we identify the root cause, as this issue is specific to the desktop platform.

**Comment by NJ-2020** [comment] 2024-08-15 14:07
> Why is this happening only on desktop, and only on this page? If the desktop doesn't update data synchronously, it should be happening in other places too.

@jayeshmangwani I don't know, but I think because Electron maybe, I've tried to console log inside browser and desktop and  I see that the log for clearing the transaction in browser came first before the if condition run, and the draftTransaction got empty before the if condition run

But on desktop side the clear function took a little bit more longer and I tried to console log, and the if condition runs before the draftTransaction got cleared, and after the if statement run, the draft transaction got cleared

> I was checking logs and noticed that the transaction data is incorrect on the desktop platform.

Yes i know this, I see on browser why it works as expected and try to console the draftTransaction and showing undefined value for the 2 second time opening the start way point which make the if condition do not run 

Thanks.

**Comment by NJ-2020** [comment] 2024-08-15 14:17
We can also add return statement to Onyx.set method and use `.then` method when the Onyx complete

**Comment by puneetlath** [comment] 2024-08-15 15:35
Do we know why this is happening on staging but not production?

**Comment by puneetlath** [comment] 2024-08-15 17:16
@jayeshmangwani I agree with you that let's make sure we understand the root cause before we go forward with a solution.

**Comment by jayeshmangwani** [comment] 2024-08-16 12:53
> Do we know why this is happening on staging but not production?

I'm trying to figure this out. I can confirm that the issue is coming from this PR https://github.com/Expensify/App/pull/45982. I reverted the changes locally, and the issue disappeared. I'm still working on pinpointing the exact line of code that's causing this

@puneetlath Other Issue still in the regression period should we assign the author and C+ of that PR to tackle this issue?

**Comment by puneetlath** [comment] 2024-08-16 14:34
That sounds good to me yes. @dominictb can you please look into this? 

cc @rayane-djouah @tgolen

**Comment by jayeshmangwani** [comment] 2024-08-21 06:32
Not Overdue;
PR will be raised by @dominictb  and reviewed by @rayane-djouah, as this issue stems from their previous PR."

**Comment by jayeshmangwani** [comment] 2024-08-22 09:41
I am unassigning myself from the Issue. @puneetlath / @RachCHopkins  Please assign the issue to @rayane-djouah  and @dominictb

**Comment by NJ-2020** [comment] 2024-08-22 12:14
@dominictb You can use desktop instead of browser

**Comment by NJ-2020** [comment] 2024-08-22 12:19
Same here, I cannot reproduce the issue

**Comment by jayeshmangwani** [comment] 2024-08-22 12:31
Issue seems to be resolved now. I am also no longer able to reproduce it.

**Comment by RachCHopkins** [comment] 2024-08-27 01:39
@rayane-djouah can you please see if you can still reproduce this?

**Comment by puneetlath** [comment] 2024-08-28 21:31
@RachCHopkins should we just close it then?

**Closed** 2024-09-03 18:15 UTC
Labels: External, Engineering, Daily, Overdue, Bug
