### ISSUE TITLE
Any expenses visible to you (i.e. SmartScanning) on Android don’t reflect on Chrome Staging

### ISSUE THREAD

**Issue by m-natarajan** [Expensify/App#45071] opened 2024-07-09 13:19 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:**
**Reproducible in staging?:** Needs reproduction
**Reproducible in production?:** Needs reproduction
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** @jliexpensify 
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1720478723447669

## Action Performed:

1. SmartScan expense on Android
2. See that it shows as visible to you
3. Open Chrome (staging) and login with same account

Additional steps:

1. Remove an expense with an error
2. SmartScan same expense
3. Verify that it doesn’t show on Chrome (staging) with the visible to you whisper

## Expected Result:
The expense would reflect in Chrome as well
## Actual Result:
The expenses don’t exist in chrome.
Logged out of the Android app and back in and only 2 of the 5 receipts from the last week got added. The other 3 are missing, and the 2 that got added were added to an Old.Dot Workspace.

## Workaround:
Unknown
## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [X] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

<img src="https://github.com/Expensify/App/assets/38435837/879a34ea-dfa8-427b-a282-5155069926d4" width="40%" height="40%">

<img src="https://github.com/Expensify/App/assets/38435837/f418c0a6-7ff0-4221-88ba-2923c6ccc693" width="40%" height="40%">
</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by VictoriaExpensify** [comment] 2024-07-11 22:16
@jliexpensify I haven't been able to reproduce this issue on my side - the expenses created on Android are showing in Chrome. Can you please give me the specific steps you are taking to create the expense on your Android?

**Comment by jliexpensify** [comment] 2024-07-11 22:25
@VictoriaExpensify hmm so this happened at the start of last week across multiple days, but testing the app this week, it's a lot better. I haven't come across this behaviour again since an update (I'm on 9.0.5-13) so lets close this one for now.

**Closed by jliexpensify** 2024-07-11 22:25 UTC
Labels: Daily, Needs Reproduction, Bug
