### ISSUE TITLE
[HOLD for payment 2024-07-24] [$250] Submitting Expense from Self DM Results in Duplicate Submissions

### ISSUE THREAD

**Issue by m-natarajan** [Expensify/App#42795] opened 2024-05-29 20:13 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.77-0
**Reproducible in staging?:** y
**Reproducible in production?:** n
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** applause internal team
**Slack conversation:**

## Action Performed:
1. Go to Self DM and click the plus sign.
2. Select "Track Expense" > "Distance," add start and stop points, and complete the flow.
3. Open the details of the tracked expense and change the date or any field that triggers a notification.
4. When the notification (whisper message) appears, click the "Submit Expense to Someone" button and add an email.
5. Notice that two expenses are submitted, and the UI covers the first expense.

## Expected Result:
Only one expense should be submitted, and the UI should not cover the notification

## Actual Result:
Submitting an expense from Self DM results in two expenses being submitted, with the first one being covered by the app's UI.

## Workaround:
Can the user still use Expensify without this being fixed? Have you informed them of the workaround?

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [x] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

https://github.com/Expensify/App/assets/38435837/3173c3b6-4078-4f24-a4cf-4aa98cb89a6e

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01f00d596f8de27d6c</li>
        <li>Upwork Job ID: 1796208453265444864</li>
        <li>Last Price Increase: 2024-06-13</li>
<li>Automatic offers: </li>
<ul>
<li>c3024 | Contributor | 102762962</li>
<li>dominictb | Contributor | 102962999</li>
</ul></li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @adelekennedy</details>

**Comment by m-natarajan** [comment] 2024-05-29 20:14
@stitesExpensify  FYI I haven't added the External label as I wasn't 100% sure about this issue. Please take a look and add the label if you agree it's a bug and can be handled by external contributors

**Comment by luacmartins** [comment] 2024-05-30 15:36
This seems to affect only the UI. Gonna remove the web `DeployBlocker` label.

**Comment by stitesExpensify** [comment] 2024-05-30 17:34
@getusha are you able to repro this? I cannot test on staging because my selfDM broke on staging, and it seems to be working on main locally...

**Comment by stitesExpensify** [comment] 2024-05-30 17:48
Looks like there is more than one issue here, I'm calling `openReport` a ton of times too

https://github.com/Expensify/App/assets/42391420/13b07de7-da9b-4f02-9fe9-11886ac7167e

**Comment by stitesExpensify** [comment] 2024-05-30 18:01
Regular expense submissions seem to just disappear in the UI too until a refresh

https://github.com/Expensify/App/assets/42391420/d1f46b5f-02e6-41cd-9750-b7099d0ff98c

**Comment by adelekennedy** [comment] 2024-05-30 18:34
@stitesExpensify if we need urgency here should we ask one of our vendors to step in? Callstack/SWM?

**Comment by stitesExpensify** [comment] 2024-05-30 18:53
It looks like there are 2 separate problems here.

1. The UI is covering the expense (caused by [this pr](https://github.com/Expensify/App/pull/38449))
2. We are displaying a single expense twice in the report for some reason (still investigating)

**Comment by stitesExpensify** [comment] 2024-05-31 13:01
Thank you for that analysis @dominictb! While looking into this, did you happen to find a specific blame that created this issue? While testing yesterday it was happening on staging but not production, which means something from [this list](https://github.com/Expensify/App/issues/42741) likely caused the issue

**Comment by stitesExpensify** [comment] 2024-05-31 18:12
It's happening on production too because we deployed while it was broken on staging 😄 

There are 2 reasons I want the blame:
1. We need to mark the offending PR from yesterday's deploy as a regression
2. There may be a simpler solution due since this was clearly broken in one PR

**Comment by stitesExpensify** [comment] 2024-06-04 21:30
@getusha what do you think?

**Comment by stitesExpensify** [comment] 2024-06-04 23:34
not overdue I just posted

**Comment by adelekennedy** [comment] 2024-06-10 04:40
@dominictb checking in here - any luck?

**Comment by getusha** [comment] 2024-06-11 12:05
Trying to reproduce the issue

**Comment by stitesExpensify** [comment] 2024-06-11 22:34
No update from my end

**Comment by stitesExpensify** [comment] 2024-06-12 18:27
@getusha were you able to reproduce?

**Comment by getusha** [comment] 2024-06-13 08:52
Not able to pass the `Submit it to someone` part. it's not showing any of my contacts.

https://github.com/Expensify/App/assets/75031127/76399a02-7ecc-4317-9ac3-1e388e1729c8

**Comment by stitesExpensify** [comment] 2024-06-13 15:59
@getusha that's super weird.... you should be able to type literally any email address there and it will be allowed. I'm not sure what to suggest besides just trying again 😅

**Comment by getusha** [comment] 2024-06-14 04:18
> @getusha that's super weird.... you should be able to type literally any email address there and it will be allowed. I'm not sure what to suggest besides just trying again 😅

I tried with multiple accounts, still no luck. i even asked for another c+ to reproduce. i'll try again

**Comment by c3024** [comment] 2024-06-14 07:24
@getusha I am able to reproduce the bug. I would like to take this over if you want to pass over.

**Comment by c3024** [comment] 2024-06-14 07:25
@getusha I am able to reproduce the bug. I would like to take this over if you want to pass over.

**Comment by c3024** [comment] 2024-06-16 04:22
@rayane-djouah 

I think I see what the issue is with your tries. You and @getusha might not have enabled the `canUseP2PDistanceRequests` beta.

**Comment by getusha** [comment] 2024-06-17 10:53
@c3024 you can take over, thanks!

**Comment by c3024** [comment] 2024-06-18 07:47
@dominictb 

Thanks for your proposal. Your RCA makes sense but that swap you suggested in your primary solution is deliberately done [here](https://github.com/Expensify/App/pull/14213). Changing that order also failed two tests. So, I think we might want to avoid that.

One way I see to fix this is filter and remove the other `CREATED` action between these
https://github.com/Expensify/App/blob/9ec57c03f64e56271b2b507064fa72323463c560/src/pages/home/report/ReportActionsView.tsx#L478-L479
before pushing the optimistic created action so that only one `CREATED` action exists in the `actions` array after pushing the optimistic created action and it seems to fix the issue.

>When moving expense to a report (ie. by Submit Expense to Someone), in the optimistic report, makes sure to backdate the created value to before the creation date of the expense itself, this will make it before any modified-expense report action's created date and will help avoid the issue.

I think this suggestion in your alternative solution might be better because it addresses the issue at the beginning of the movement itself. Can you give more details and specifics about the changes required for this solution?

**Comment by c3024** [comment] 2024-06-20 04:28
@dominictb 

Would you like to comment on [this](https://github.com/Expensify/App/issues/42795#issuecomment-2175426568)?

**Comment by adelekennedy** [comment] 2024-06-20 20:16
thanks @dominictb looking forward to your update!

**Comment by c3024** [comment] 2024-06-27 05:58
Thanks for the update.

Alternative solution 2 of retaining the older of the `CREATED` actions in @dominictb's [proposal here](https://github.com/Expensify/App/issues/42795#issuecomment-2141249108) looks good to me.

🎀 👀 🎀 C+ Reviewed

**Comment by adelekennedy** [comment] 2024-07-01 21:37
@stitesExpensify I think it's back to you for the final approval!

**Comment by stitesExpensify** [comment] 2024-07-02 18:47
I agree with @c3024 let's go with @dominictb solution 2

**Comment by adelekennedy** [comment] 2024-07-08 22:07
@dominictb how is the PR coming along? I see it's in progress, do you need any additional support?

**Comment by adelekennedy** [comment] 2024-07-25 03:56
payments made! @c3024 will you complete the checklist?

**Comment by adelekennedy** [comment] 2024-07-28 19:01
bump @c3024

**Comment by c3024** [comment] 2024-07-29 03:34
**BugZero Checklist:** The PR fixing this issue has been merged! The following checklist ([instructions](https://stackoverflow.com/c/expensify/questions/14574)) will need to be completed before the issue can be closed:
 
* [x]  [@c3024] The PR that introduced the bug has been identified. Link to the PR: #39472 
* [x]  [@c3024] The offending PR has been commented on, pointing out the bug it caused and why, so the author and reviewers can learn from the mistake. Link to comment: https://github.com/dominictb/epsf-app/commit/2e030d9709cf90a886f386c63324b92108e62ea3#r144740854
* [x]  [@c3024] A discussion in #expensify-bugs has been started about whether any other steps should be taken (e.g. updating the PR review checklist) in order to catch this type of bug sooner. Link to discussion: No discussion was started because it could not have been caught earlier.
* [x]  [@c3024] Determine if we should create a regression test for this bug. Yes

**Comment by c3024** [comment] 2024-07-29 03:43
### Regression Test Proposal

1. Track a Distance Expense in Self DM
2. Open this tracked expense report and change the date. This triggers a notification `changed the date to <new date> previously <old date>`
3. Go back to Self DM
4. On the whisper received for the tracked expense in Step 1, click on `Submit Expense to Someone` > Select a user A and complete the flow
5. Go to the DM with user A > click on this expense preview > go to this expense report
6. Verify that there are no duplicates for either the date change notification or the expense details

**Comment by adelekennedy** [comment] 2024-07-31 20:22
https://github.com/Expensify/Expensify/issues/416847

**Closed by adelekennedy** 2024-07-31 20:22 UTC
Labels: External, Engineering, Daily, Overdue, Awaiting Payment, Bug
