### ISSUE TITLE
[HOLD for payment 2024-11-14] [HOLD for payment 2024-11-13] [$250] Bank account - App crashes when connecting to bank account

### ISSUE THREAD

**Issue by IuliiaHerets** [Expensify/App#51961] opened 2024-11-04 16:03 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 9.0.57-0
**Reproducible in staging?:** Y
**Reproducible in production?:** N
**Email or phone of affected tester (no customers):** applausetester+kh22100010ad@applause.expensifail.com
**Issue reported by:** Applause Internal Team

## Action Performed:
1. Go to staging.new.expensify.com
2. Go to Workspace settings > Workflows.
3. Click Connect bank account.
4. Click Update to USD.

## Expected Result:
App will not crash when connecting to bank account.

## Actual Result:
App crashes when connecting to bank account.

## Workaround:
Unknown

## Platforms:

- [ ] Android: Standalone
- [ ] Android: HybridApp
- [x] Android: mWeb Chrome
- [ ] iOS: Standalone
- [ ] iOS: HybridApp
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

[0411_2.txt](https://github.com/user-attachments/files/17620757/0411_2.txt)

https://github.com/user-attachments/assets/8a9f0e30-a382-412f-acf0-7b1adacdc431

 
</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~021853501012094691283</li>
        <li>Upwork Job ID: 1853501012094691283</li>
        <li>Last Price Increase: 2024-11-04</li>
<li>Automatic offers: </li>
<ul>
<li>DylanDylann | Reviewer | 104737674</li>
<li>CyberAndrii | Contributor | 104737676</li>
</ul></li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @muttmuure</details>

**Comment by nkdengineer** [comment] 2024-11-04 16:10
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
App crashes when connecting to bank account.

### What is the root cause of that problem?

we have this error `Cannot access 'hasInProgressVBBA' before initialization`

### What changes do you think we should make in order to solve the problem?


We should move function `hasInProgressVBBA` to above place where we define the state `shouldShowContinueSetupButton`

### What alternative solutions did you explore? (Optional)

**Comment by CyberAndrii** [comment] 2024-11-04 16:24
## Proposal

### Please re-state the problem that we are trying to solve in this issue.

Bank account - App crashes when connecting to bank account

### What is the root cause of that problem?

Offending commit is likely https://github.com/Expensify/App/commit/98b1256be20fd2e43b4afa1426e885b0628b185f. It moved the call to `getShouldShowContinueSetupButtonInitialValue()` above the place where the function is defined.

This issue was fixed in https://github.com/Expensify/App/pull/51315 but it recently got reverted by https://github.com/Expensify/App/pull/51857

### What changes do you think we should make in order to solve the problem?

Move this functions a few lines up before the call to `getShouldShowContinueSetupButtonInitialValue()`

https://github.com/Expensify/App/blob/657531f56427e51d377b642af6ef65faf30605d9/src/pages/ReimbursementAccount/ReimbursementAccountPage.tsx#L183-L206

Also wrap them in `useCallback`

**Comment by DylanDylann** [comment] 2024-11-04 16:32
I also see this bug today. But I don't understand why this bug happens after reverting https://github.com/Expensify/App/pull/51315. TBH, https://github.com/Expensify/App/pull/51315 fix another bug and we already reverted by https://github.com/Expensify/App/pull/51857. Anyone help to investigate why this bug doesn't happen before merging https://github.com/Expensify/App/pull/51315

**Comment by nkdengineer** [comment] 2024-11-04 18:14
> Move this functions a few lines up before the call to getShouldShowContinueSetupButtonInitialValue()

@CyberAndrii I see your solution is no different from the solution I proposed before.

**Comment by blimpich** [comment] 2024-11-04 18:15
@ahmedGaber93 please ignore the ping, assigning @DylanDylann here since they have context

**Comment by ahmedGaber93** [comment] 2024-11-04 18:26
> please ignore the ping, assigning @DylanDylann here since they have context

Ok, no problem, I also faced this problem yesterday and can help. It is a pretty straightforward JS issue and not requires any context.

**Comment by blimpich** [comment] 2024-11-04 18:28
@ahmedGaber93 thank you! We'll stick with @DylanDylann as the C+ for now but will let you know if we need help 🙂

**Comment by blimpich** [comment] 2024-11-04 18:28
@nkdengineer hello there is definitely similarity with the proposals. I preemptively assigned @CyberAndrii since they were active in the Slack chat I opened up about this. My priority is to fix this quickly so I weighed their responsiveness in Slack heavily when assigning 👍

**Comment by nkdengineer** [comment] 2024-11-04 18:30
@blimpich thanks for explaining, i understand

**Comment by blimpich** [comment] 2024-11-04 23:40
**Update:** PR is up, waiting for @DylanDylann to come back online to review. I'm about to log off for the day, will check back in in the evening to see if PR is ready to merge and CP to staging.

**Comment by Julesssss** [comment] 2024-11-05 11:18
Thanks all. @blimpich, the changes looked good, so I have merged them to unblock the deploy.

**Comment by Julesssss** [comment] 2024-11-05 13:43
Checked off

**Comment by muttmuure** [comment] 2024-11-14 11:31
# BugZero Checklist:

- [ ] **[Contributor]** Classify the bug:

<details>
<summary>Bug classification</summary>


Source of bug:
  - [ ] 1a. Result of the original design (eg. a case wasn't considered)
  - [ ] 1b. Mistake during implementation
  - [ ] 1c. Backend bug
  - [ ] 1z. Other:

Where bug was reported:
  - [ ] 2a. Reported on production
  - [ ] 2b. Reported on staging (deploy blocker)
  - [ ] 2c. Reported on both staging and production
  - [ ] 2d. Reported on a PR
  - [ ] 2z. Other:

Who reported the bug:
  - [ ] 3a. Expensify user
  - [ ] 3b. Expensify employee
  - [ ] 3c. Contributor
  - [ ] 3d. QA
  - [ ] 3z. Other:

</details>

- [ ] **[Contributor]** The offending PR has been commented on, pointing out the bug it caused and why, so the author and reviewers can learn from the mistake.

    Link to comment:

- [ ] **[Contributor]** If the regression was CRITICAL (e.g. interrupts a core flow) A discussion in [#expensify-open-source](https://app.slack.com/client/E047TPA624F/C01GTK53T8Q) has been started about whether any other steps should be taken (e.g. updating the PR review checklist) in order to catch this type of bug sooner.

    Link to discussion:

- [ ] **[Contributor]** If it was decided to create a regression test for the bug, please propose the [regression test](https://github.com/Expensify/App/blob/main/contributingGuides/REGRESSION_TEST_BEST_PRACTICES.md) steps using the template below to ensure the same bug will not reach production again.

<details>
<summary>Regression Test Proposal Template</summary>


- [ ] **[BugZero Assignee]** Create a GH issue for creating/updating the regression test once above steps have been agreed upon.

    Link to issue:

## Regression Test Proposal
### Precondition:


-

### Test:


1.

Do we agree 👍 or 👎


</details>

**Comment by DylanDylann** [comment] 2024-11-19 02:58
# BugZero Checklist:

- [ ] **[Contributor]** Classify the bug:

<details>
<summary>Bug classification</summary>


Source of bug:
  - [ ] 1a. Result of the original design (eg. a case wasn't considered)
  - [ ] 1b. Mistake during implementation
  - [ ] 1c. Backend bug
  - [ ] 1z. Other:

Where bug was reported:
  - [ ] 2a. Reported on production
  - [ ] 2b. Reported on staging (deploy blocker)
  - [ ] 2c. Reported on both staging and production
  - [ ] 2d. Reported on a PR
  - [ ] 2z. Other:

Who reported the bug:
  - [ ] 3a. Expensify user
  - [ ] 3b. Expensify employee
  - [ ] 3c. Contributor
  - [ ] 3d. QA
  - [ ] 3z. Other:

</details>

- [ ] **[Contributor]** The offending PR has been commented on, pointing out the bug it caused and why, so the author and reviewers can learn from the mistake.

    Link to comment:

- [ ] **[Contributor]** If the regression was CRITICAL (e.g. interrupts a core flow) A discussion in [#expensify-open-source](https://app.slack.com/client/E047TPA624F/C01GTK53T8Q) has been started about whether any other steps should be taken (e.g. updating the PR review checklist) in order to catch this type of bug sooner.

    Link to discussion:

- [ ] **[Contributor]** If it was decided to create a regression test for the bug, please propose the [regression test](https://github.com/Expensify/App/blob/main/contributingGuides/REGRESSION_TEST_BEST_PRACTICES.md) steps using the template below to ensure the same bug will not reach production again.

<details>
<summary>Regression Test Proposal Template</summary>


- [ ] **[BugZero Assignee]** Create a GH issue for creating/updating the regression test once above steps have been agreed upon.

    Link to issue:

## Regression Test Proposal
### Precondition:


-

### Test:


1.

Do we agree 👍 or 👎


</details>

**Comment by DylanDylann** [comment] 2024-11-19 03:00
# BugZero Checklist:

- [ ] **[Contributor]** Classify the bug:

<details>
<summary>Bug classification</summary>


Source of bug:
  - [ ] 1a. Result of the original design (eg. a case wasn't considered)
  - [ ] 1b. Mistake during implementation
  - [ ] 1c. Backend bug
  - [ ] 1z. Other:

Where bug was reported:
  - [ ] 2a. Reported on production
  - [ ] 2b. Reported on staging (deploy blocker)
  - [ ] 2c. Reported on both staging and production
  - [ ] 2d. Reported on a PR
  - [ ] 2z. Other:

Who reported the bug:
  - [ ] 3a. Expensify user
  - [ ] 3b. Expensify employee
  - [ ] 3c. Contributor
  - [ ] 3d. QA
  - [ ] 3z. Other:

</details>

- [ ] **[Contributor]** The offending PR has been commented on, pointing out the bug it caused and why, so the author and reviewers can learn from the mistake.

    Link to comment:

- [ ] **[Contributor]** If the regression was CRITICAL (e.g. interrupts a core flow) A discussion in [#expensify-open-source](https://app.slack.com/client/E047TPA624F/C01GTK53T8Q) has been started about whether any other steps should be taken (e.g. updating the PR review checklist) in order to catch this type of bug sooner.

    Link to discussion:

- [ ] **[Contributor]** If it was decided to create a regression test for the bug, please propose the [regression test](https://github.com/Expensify/App/blob/main/contributingGuides/REGRESSION_TEST_BEST_PRACTICES.md) steps using the template below to ensure the same bug will not reach production again.

<details>
<summary>Regression Test Proposal Template</summary>


- [ ] **[BugZero Assignee]** Create a GH issue for creating/updating the regression test once above steps have been agreed upon.

    Link to issue:

## Regression Test Proposal
### Precondition:


-

### Test:


1.

Do we agree 👍 or 👎


</details>

**Comment by muttmuure** [comment] 2024-11-20 17:09
@CyberAndrii - $250 for C
@DylanDylann - $250 for C+

**Comment by muttmuure** [comment] 2024-11-26 17:52
This is paid up and regression test created

**Closed by muttmuure** 2024-11-26 17:52 UTC
Labels: External, Engineering, Daily, Overdue, Awaiting Payment, Bug
