### ISSUE TITLE
[HOLD for payment 2024-08-07] [$250] Workspace - Not here page displayed when navigate to workspace via join link

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#44845] opened 2024-07-04 15:39 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 9.0.4.0
**Reproducible in staging?:** Y
**Reproducible in production?:** Y 
**If this was caught during regression testing, add the test name, ID and link from TestRail:** N/A
**Issue reported by:** Applause - internal Team

**Issue found when executing PR** https://github.com/Expensify/App/pull/44716
## Action Performed:
precondition: as user A copy a join link of a workspace where user B is not a member
1. Open the app and log in as user B
2. Tap the copied workspace join link, e.g. https://staging.new.expensify.com/settings/workspaces/D047C9A2ABF7DFA3/join?email=applausetester+0703pm@applause.expensifail.com
3. Tap the back icon

## Expected Result:
User is navigated to the workspace and after taping the back icon is returned to the report where the link was shared

## Actual Result:
The "Hmm, not here page " is displayed when tapping the workspace join link and when go back to the report

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [x] iOS: Native
- [ ] iOS: mWeb Safari
- [ ] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details> 

https://github.com/Expensify/App/assets/78819774/b6d5aff1-41bd-48e3-8e74-2d770915e062

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01221d40e5d9c13c1e</li>
        <li>Upwork Job ID: 1815532155728537565</li>
        <li>Last Price Increase: 2024-07-22</li>
<li>Automatic offers: </li>
<ul>
<li>akinwale | Reviewer | 103229470</li>
</ul></li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @alexpensify</details>

**Comment by bernhardoj** [comment] 2024-07-05 15:01
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
Not found page is shown when going back from workspace list page after navigate to the workspace join link.

### What is the root cause of that problem?
When we open the join link page, we call `navigateAfterJoinRequest` which navigates to ROUTES.ALL_SETTINGS and ROUTES.SETTINGS_WORKSPACES
https://github.com/Expensify/App/blob/ce5ae736eccd5180f50e47e21db047dd33b90a43/src/libs/navigateAfterJoinRequest/index.ts#L4-L8

However, ROUTES.ALL_SETTINGS isn't being used anymore. It's the old route name for the settings page, so there will be a not found page in the nav stack.

[ROUTES.ALL_SETTINGS (not found), ROUTES.SETTINGS_WORKSPACES]

Going back from the workspace list page will shows the not found page.

### What changes do you think we should make in order to solve the problem?

Change the route to ROUTES.SETTINGS and remove ROUTES.ALL_SETTINGS const. Doing this, the user will be navigated to the settings bottom tab page and then to the workspace list page.

OR

We can just remove the navigation to the Settings page.

**Comment by c3024** [comment] 2024-07-11 10:16
@lanitochka17 No BZ member assigned here. Please re-add `Bug` label.

**Comment by lanitochka17** [comment] 2024-07-11 17:40
@alexpensify  FYI I haven't added the External label as I wasn't 100% sure about this issue. Please take a look and add the label if you agree it's a bug and can be handled by external contributors

**Comment by alexpensify** [comment] 2024-07-15 18:39
Ok, I'll add it to my testing list.

**Comment by alexpensify** [comment] 2024-07-17 23:11
Other GHs have been a priority, I'll review soon

**Comment by alexpensify** [comment] 2024-07-22 23:40
@akinwale -  can you review if this proposals will fix this problem? Thanks!

**Comment by michaelbankole** [comment] 2024-07-23 06:17
**Proposal to Fix Issue #44845: "Not Here Page Displayed When Navigating to Workspace via Join Link"**

Proposed Solution:

Investigate Routing and Authentication:

I will examine the routing logic and authentication processes in the React Native codebase to identify any potential issues with the join link handling.
Update the Codebase:

Fix Routing Issue: I will modify the routing logic to ensure that users are correctly navigated to the workspace. This may involve updating the navigation configuration or handling of join links.
Handle Join Links: I will ensure that join links are processed correctly and that appropriate checks are performed to verify user authentication and workspace access.
Test the Changes:

I will write unit tests to cover the updated logic and conduct manual testing across all supported platforms (iOS and Android) to verify that the issue is resolved and no new issues are introduced.

Technical Details:

I will focus on the routing logic within the NavigationService.js file and review the join link handling in WorkspaceJoin.js.

Updates may include modifying the navigation configuration and adding checks for user authentication and workspace validity.
Testing and Validation:

Unit tests will be written to ensure that routing and join link handling functions as expected.
I will perform manual testing on iOS and Android to confirm that the fix works across all platforms.
Conclusion:

I am confident that my proposed solution will address the issue effectively. I am available to start working on this immediately and will keep you updated throughout the process. Please let me know if you need any additional information.

**Comment by akinwale** [comment] 2024-07-23 10:13
We can move forward with @bernhardoj's [proposal](https://github.com/Expensify/App/issues/44845#issuecomment-2211031360) here.

🎀👀🎀 C+ reviewed.

**Comment by Julesssss** [comment] 2024-07-23 10:24
LGTM

**Comment by bernhardoj** [comment] 2024-07-23 14:05
PR is ready

cc: @akinwale

**Comment by alexpensify** [comment] 2024-07-29 18:52
Awesome, this PR is moving along, and we are waiting for it to go to production.

**Comment by akinwale** [comment] 2024-08-03 08:30
> * [x]  [@akinwale] The PR that introduced the bug has been identified. Link to the PR:
> * [x]  [@akinwale] The offending PR has been commented on, pointing out the bug it caused and why, so the author and reviewers can learn from the mistake. Link to comment:
> * [x]  [@akinwale] A discussion in #expensify-bugs has been started about whether any other steps should be taken (e.g. updating the PR review checklist) in order to catch this type of bug sooner. Link to discussion:

Not a regression.

> * [x]  [@akinwale] Determine if we should create a regression test for this bug.
> * [x]  [@akinwale] If we decide to create a regression test for the bug, please propose the [regression test](https://github.com/Expensify/App/blob/main/contributingGuides/REGRESSION_TEST_BEST_PRACTICES.md) steps to ensure the same bug will not reach production again.

**Regression Test Steps**
1. Launch Expensify as user A
2. Copy the join link of a workspace where user B is not a member
3. Launch Expensify as user B
4. As user B, attempt to open the copied workspace join link
5. Navigate back using the back button
6. Verify that the not found page is not displayed after navigating back

Do we agree 👍 or 👎?

**Comment by alexpensify** [comment] 2024-08-07 20:29
Payouts due: August 7, 2024

- [ ] Contributor: $250 @bernhardoj - Please submit a request in Chat  
- [x] Contributor+: $250 @akinwale  - I completed the process in Upwork 

Upwork job is [here](https://www.upwork.com/jobs/~0114cd4bde59962aa8).

Closing - I completed the payment process in Upwork. I'll revisit this GH for the regression test process.

**Closed by alexpensify** 2024-08-07 20:29 UTC
Labels: External, Daily, Overdue, Awaiting Payment, Bug

**Comment by bernhardoj** [comment] 2024-08-08 02:53
Requested in ND.

**Comment by JmillsExpensify** [comment] 2024-08-08 23:19
$250 approved for @bernhardoj
