### ISSUE TITLE
[PAID] [$250] Chat - Manually copied and pasted user mention turns into user profile hyperlink

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#41798] opened 2024-05-07 18:31 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.71-0
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**If this was caught during regression testing, add the test name, ID and link from TestRail:** N/A
**Issue reported by:** Applause - Internal Team

## Action Performed:
1. Log in to New Expensify
2. Navigate to any chat
3. Manually select, copy and paste the message
4. Send the message

## Expected Result:
Copied user mention should remain a mention

## Actual Result:
Manually copied and pasted user mention turns in to hyperlink leading to the user profile

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details> 

https://github.com/Expensify/App/assets/78819774/9826abeb-1c8e-4b1e-ad03-ff03209d6497

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01cc954368da0c91d3</li>
        <li>Upwork Job ID: 1788782724202225664</li>
        <li>Last Price Increase: 2024-05-10</li>
<li>Automatic offers: </li>
<ul>
<li>c3024 | Reviewer | 0</li>
<li>bernhardoj | Contributor | 0</li>
</ul></li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @strepanier03</details>

**Comment by lanitochka17** [comment] 2024-05-07 18:32
@sakluger  FYI I haven't added the External label as I wasn't 100% sure about this issue. Please take a look and add the label if you agree it's a bug and can be handled by external contributors

**Comment by bernhardoj** [comment] 2024-05-08 09:58
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
Copying a user mention and paste it turns the text into a link markdown.

### What is the root cause of that problem?
The mention text is rendered as an anchor tag.
https://github.com/Expensify/App/blob/e0b6a06d2f34f35cda96ccc4d05252ede111c732/src/components/HTMLEngineProvider/HTMLRenderers/MentionUserRenderer.tsx#L103-L110
<img width="214" alt="image" src="https://github.com/Expensify/App/assets/50919443/7e965a96-c7aa-462d-8ab6-671cd21419bf">

So, when we copy it, it will be copied as a link. This was previously fixed in https://github.com/Expensify/App/issues/20814 by adding a testID of span because previously, if an element has a testID, the element name will be renamed to the testID, in this case span.

But in my PR [here](https://github.com/Expensify/App/pull/30476), I update the logic so that it replaces the element name only if the testID is a valid markdown name. In this case, span is not a valid markdown. It's to fix another issue [here](https://github.com/Expensify/App/issues/29921).

### What changes do you think we should make in order to solve the problem?

Instead of setting the testID to span here,
https://github.com/Expensify/App/blob/e0b6a06d2f34f35cda96ccc4d05252ede111c732/src/components/HTMLEngineProvider/HTMLRenderers/MentionUserRenderer.tsx#L108

we can set it to `mention-user`. Then, add `mention-user` to the valid markdown list here
https://github.com/Expensify/App/blob/e0b6a06d2f34f35cda96ccc4d05252ede111c732/src/libs/SelectionScraper/index.ts#L9

_or simply add span to the valid markdown list above, but not preferable_

**Comment by c3024** [comment] 2024-05-10 04:54
@bernhardoj 's [proposal here](https://github.com/Expensify/App/issues/41798#issuecomment-2100212725) looks good to me.

🎀 👀 🎀 C+ Reviewed

**Comment by bernhardoj** [comment] 2024-05-11 04:51
PR is ready

cc: @c3024

**Comment by sakluger** [comment] 2024-05-16 18:53
@alexpensify I'm OOO for two weeks. Can you please help with the payment if it's due before I'm back? The PR was deployed to Staging yesterday, so it will probably be deployed to prod early next week.

**Comment by alexpensify** [comment] 2024-05-16 20:22
@strepanier03 - It looks like we are playing the assignment merry-go-round here. I, too, will be OOO next week and will not return until Tuesday, May 28. I'm reassigning now to get @sakluger help with the payment process. Thanks! 

BZ Discussion Here: https://expensify.slack.com/archives/C01SKUP7QR0/p1715886524903119?thread_ts=1715873747.589919&cid=C01SKUP7QR0

**Comment by strepanier03** [comment] 2024-05-21 23:37
PR on staging so we're waiting for the 7-day hold to start.

**Comment by c3024** [comment] 2024-05-23 15:41
PR deployed to production but automation failed here.

**Comment by strepanier03** [comment] 2024-05-23 18:37
Deployed to production 2024-05-22, 7-days later is 2024-05-29. Updating title.

**Comment by strepanier03** [comment] 2024-05-30 00:03
Jobs are paid and contracts closed, thanks all!

**Closed by strepanier03** 2024-05-30 00:03 UTC
Labels: Reviewing, External, Daily, Bug
