### ISSUE TITLE
 Messages sent in iOS app aren't showing on Desktop

### ISSUE THREAD

**Issue by kavimuru** [Expensify/App#22858] opened 2023-07-14 02:14 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Send 3 messages in a group chat on iOS app
2. Open the chat in Desktop

## Expected Result: 
Those three messages to show on Desktop

## Actual Result: 
Message is not shown even after hard refresh

## Workaround:
Can the user still use Expensify without this being fixed? Have you informed them of the workaround?

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [x] iOS / native
- [x] iOS / Safari
- [ ] MacOS / Chrome / Safari
- [x] MacOS / Desktop

**Version Number:** 1.3.39.5
**Reproducible in staging?:** needs reproduction
**Reproducible in production?:** needs reproduction
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation

**Expensify/Expensify Issue URL:**
**Issue reported by:** @mallenexpensify 
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1689197376536879

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by Christinadobrzyn** [comment] 2023-07-14 16:42
I'm not able to reproduce this but the Slack convo says to assign to Matt so going to do that.

**Comment by mallenexpensify** [comment] 2023-07-14 23:59
Thanks @Christinadobrzyn , I'm going to to try to reproduce..

**Comment by mallenexpensify** [comment] 2023-07-26 01:15
iOS app won't load for me now so can't test 😿

**Comment by mallenexpensify** [comment] 2023-09-26 05:58
Closing because we have the below that has more action
- https://github.com/Expensify/App/issues/27962

**Closed by mallenexpensify** 2023-09-26 05:58 UTC
Labels: Monthly, Needs Reproduction, Overdue
