### ISSUE TITLE
[HOLD for Payment 2024-09-25] [$125] [Search v2.1] Open reports show __fake__ in To column

### ISSUE THREAD

**Issue by luacmartins** [Expensify/App#48582] opened 2024-09-04 17:39 UTC
### Problem
Coming from [here](https://expensify.slack.com/archives/C049HHMV9SM/p1725454490800639), open reports show `__Fake__` in the `To` column because they don't have a managerID. 

### Solution
We should just display an empty column in that case.
<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~021831386678971022108</li>
        <li>Upwork Job ID: 1831386678971022108</li>
        <li>Last Price Increase: 2024-09-04</li>
<li>Automatic offers: </li>
<ul>
<li>ikevin127 | Contributor | 103817750</li>
</ul></li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @bfitzexpensify</details>

**Comment by nkdengineer** [comment] 2024-09-04 18:43
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
Open reports show __fake__ in To column

### What is the root cause of that problem?
The `formattedTo` can be `_fake_` if we don't have a mangerID and we don't display empty string in this case.

https://github.com/Expensify/App/blob/62e6f636e54062888409091290427a7683ea3308/src/components/SelectionList/Search/TransactionListItemRow.tsx#L391-L395
### What changes do you think we should make in order to solve the problem?
We should fix the core function that returns the transaction item [here](https://github.com/Expensify/App/blob/65c8db539450437d4db2ca7f73e9a3d8b2d24f13/src/libs/SearchUtils.ts#L72) then the bug can be fixed in all places that we used this item. 

OPTIONAL: We can do the same check for `formattedFrom` but I think this will always exist

```
formattedTo: formattedTo === CONST.REPORT.OWNER_EMAIL_FAKE ? '' : formattedTo
```
 
https://github.com/Expensify/App/blob/65c8db539450437d4db2ca7f73e9a3d8b2d24f13/src/libs/SearchUtils.ts#L72
### What alternative solutions did you explore? (Optional)

**Comment by ikevin127** [comment] 2024-09-05 21:52
@luacmartins Should we have one of the Contributors work on this based on proposals or will this be handled by a Contractor as most of the Search v2.1 issues ?

**Comment by luacmartins** [comment] 2024-09-05 22:56
@ikevin127 yes, we can open this to other contributors

**Comment by ikevin127** [comment] 2024-09-05 23:31
In that case, @Krishna2323's updated [proposal ](https://github.com/Expensify/App/issues/48582#issuecomment-2329649318) LGTM, being the first to point out the root cause and suggest a working solution.

🎀👀🎀 C+ reviewed

**Comment by luacmartins** [comment] 2024-09-05 23:34
Hmm we shouldn't render the avatar either. I think if item.managerID = 0 we should just avoid rendering the UserInfoCell data

**Comment by ikevin127** [comment] 2024-09-05 23:46
@luacmartins What do you think, should we strictly avoid rendering the UserInfoCell data where this component is located as mentioned in [proposal 1](https://github.com/Expensify/App/issues/48582#issuecomment-2329649318) or do this from [`getTransactionItemCommonFormattedPropertie`]() as suggested by the other proposal ?

Either way, both proposals need to be updated to comply with:

> if item.managerID = 0 we should just avoid rendering the UserInfoCell data

and early return instead when `managerID = 0`.

**Comment by bfitzexpensify** [comment] 2024-09-06 14:30
I am heading out of office until September 21st, so assigning a buddy to watch over this in my absence. 

Current status: working through proposals

**Comment by ikevin127** [comment] 2024-09-07 04:58
♻️ Will review the updates in ~12h, starting with @Nodebrute since they were first to update according to the new expected result.

**Comment by ikevin127** [comment] 2024-09-08 00:06
@luacmartins Unfortunately I am not able to reproduce the `managerID = 0` and `__fake__`  in the way it was reproduced in the Slack [report](https://expensify.slack.com/archives/C049HHMV9SM/p1725454490800639), meaning it happened without having to set any onyx data locally or hardcoding values. 

Given this, to even begin to have proper proposals I think we first need to be able to reproduce the issue since without that I don't know the conditions in which the `__fake__` would appear, it can be **only** if `managerID = 0` or we can get it in other cases as well (❓) - which will dictate the proposal's root cause and solution.

**I think there's two ways to to get this issue fixed:**
1. Make it `Internal` since it would be easier for an Expensify engineer to both reproduce and fix the issue.
2. If issue remains `External`, we need steps to reproduce the issue as shown in the Slack report in order to be able to get complete proposals that Contributors can come up by actually reproducing the issue instead of improvising.

**Comment by greg-schroeder** [comment] 2024-09-09 06:33
What do you think on the above @luacmartins?

**Comment by ikevin127** [comment] 2024-09-11 01:39
@luacmartins Unfortunately I cannot reproduce, when I follow the steps you provided - the transaction I get in ND **does** have a `managerID`. Not sure what to do in this case, I'm happy to pass the issue to another C+ if they can reproduce this.

**Comment by luacmartins** [comment] 2024-09-11 15:17
@ikevin127 hmm it seems like the report in the OP had a pending card transaction, maybe that could be related. I'll try to reproduce this on my end and report back.

**Comment by Kicu** [comment] 2024-09-12 07:03
Are we still accepting proposals from contributors? If not I can work on this if you assign me. 
At this moment we're in the polishing phase for v2.1 and v2.2 so I have some free time on my hands for smaller bugs.

**Comment by luacmartins** [comment] 2024-09-12 14:07
All yours @Kicu!

**Comment by greg-schroeder** [comment] 2024-09-17 01:00
PR merged! Awaiting deploy to staging -> prod

**Comment by ikevin127** [comment] 2024-09-18 23:25
⚠️ Automation failed here -> this should be on **[HOLD for Payment 2024-09-25]** according to today's production deploy from [Deploy Checklist: New Expensify 2024-09-17](https://github.com/Expensify/App/issues/49356#top) which was shipped to production today.

cc @greg-schroeder

**Comment by greg-schroeder** [comment] 2024-09-18 23:37
Updated

**Comment by greg-schroeder** [comment] 2024-09-23 16:43
@bfitzexpensify gonna leave this one back in your capable hands now that you're back - should be set to go for 9/25!

**Comment by bfitzexpensify** [comment] 2024-09-26 14:06
Offer sent @ikevin127

**Comment by ikevin127** [comment] 2024-09-26 16:57
@bfitzexpensify Accepted, thank you!

**Closed** 2024-09-27 09:40 UTC
Labels: External, Daily, Awaiting Payment, Bug
