### ISSUE TITLE
[$500] IOU - Padding below total increases for unread messages on mobile devices

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#30360] opened 2023-10-25 16:13 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.3.90.2
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** @dhanashree-sawant
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1698067716752699

## Action Performed:
1. Open the app and login with user A
2. Open the app with any other device and login with user B
3. From user B, send request money to user A
4. Open user B request money in user A and mark message as unread
4.  Observe the padding between 'total' and 'New' line
5. Revisit the request money untill 'New' line disappears and now observe the padding between 'total' and line below total

## Expected Result:
 App should have equal padding below total irrespective of presence of 'New' line

## Actual Result:
On mobile devices, padding between total and 'New' line is way more then padding when there is no 'New' line

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [x] Android: mWeb Chrome
- [x] iOS: Native
- [x] iOS: mWeb Safari
- [ ] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos
<details>
<summary>Android: Native</summary>

 

https://github.com/Expensify/App/assets/93399543/c423cdbb-3ac1-4eb8-af75-498b0d6250c3

</details>

<details>
<summary>Android: mWeb Chrome</summary>

 

https://github.com/Expensify/App/assets/93399543/b03f0f45-7820-4581-8c90-c39e124f339f

</details>

<details>
<summary>iOS: Native</summary>

 

https://github.com/Expensify/App/assets/93399543/6f525245-97fc-464d-a2db-70024be49c34

</details>

<details>
<summary>iOS: mWeb Safari</summary>

 

https://github.com/Expensify/App/assets/93399543/803f2b51-f810-4412-8294-b9ac20b7a894

</details>

<details>
<summary>MacOS: Chrome / Safari</summary>

</details>

<details>
<summary>MacOS: Desktop</summary>

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~0158fbfd6d89166dba</li>
        <li>Upwork Job ID: 1717212733665116160</li>
        <li>Last Price Increase: 2023-10-25</li>
<li>Automatic offers: </li>
<ul>
<li>situchan | Contributor | 27456744</li>
<li>dhanashree-sawant | Reporter | 27456747</li>
<li>DylanDylann | Contributor | 0</li>
</ul></li>
    </ul>
</details>

**Comment by Nathan-Mulugeta** [comment] 2023-10-25 16:53
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
Padding below total increases for unread messages on mobile devices

### What is the root cause of that problem?
The root cause of this problem is found in here: 
https://github.com/Expensify/App/blob/cc3c51c1d58ce013e444b59bd06c87e4b750e550/src/CONST.ts#L126-L131
The size of the `CONTAINER_MINHEIGHT` for `SMALL_SCREEN` is the same as the size of `CONTAINER_MINHEIGHT` for `WIDE_SCREEN`.

### What changes do you think we should make in order to solve the problem?
We need to decrease the size of the `CONTAINER_MINHEIGHT` from `280` to `200` for `SMALL_SCREEN` sizes. Which is the same as the `CONTAINER_MINHEIGHT` for reports which are not `MONEY_REPORT`
The changes should look like this: 
```javascript
  SMALL_SCREEN: {
                IMAGE_HEIGHT: 300,
                CONTAINER_MINHEIGHT: 200, // Update this line 
                VIEW_HEIGHT: 220,
            },
```

### What alternative solutions did you explore? (Optional)
NA

**Comment by ArekChr** [comment] 2023-10-26 10:55
@tienifr, I’ve gone through your proposal, and it seems good overall. Regarding the second solution, my only concern is negative spacing. Generally, avoiding such styles is a good idea as they can lead to inconsistency in the future. What are your thoughts on fixing this issue by avoiding negative spacing?

**Comment by alexpensify** [comment] 2023-10-30 23:53
@ArekChr - can you review the responses when you get a chance? Thanks!

**Comment by ArekChr** [comment] 2023-10-31 12:03
@garrettmknight Hello, I am wrapping up some urgent matters today, and I will be OOO from tomorrow to Monday. Can we assign another C+ here so as not to block the task?

**Comment by situchan** [comment] 2023-10-31 12:15
I can take over

**Comment by alexpensify** [comment] 2023-10-31 14:57
Thank you @ArekChr for this update! 

@situchan you are assigned now. Let's keep this one moving forward.

**Comment by situchan** [comment] 2023-10-31 16:21
@tienifr does your solution also fix web as well?


https://github.com/Expensify/App/assets/108292595/150b26c7-e929-4b4b-8a32-c5a9096f12cc

**Comment by Nathan-Mulugeta** [comment] 2023-11-01 03:04
Hey @situchan ,have you got the chance to check my [proposal](https://github.com/Expensify/App/issues/30360#issuecomment-1779682019). I would love to get a feedback on it please.

**Comment by situchan** [comment] 2023-11-01 03:18
@Nathan-Mulugeta your proposal doesn't make sense to me. The diff is not 80px

**Comment by situchan** [comment] 2023-11-02 10:55
@Nathan-Mulugeta please share 4 screenshots on web/native before/after fix

**Comment by Nathan-Mulugeta** [comment] 2023-11-02 13:49
Here you go @situchan:

<details>
<summary>Native - Before</summary>
![Native-before](https://github.com/Expensify/App/assets/111440031/9cca1efb-7ba5-4fc3-bfe2-a582ff9033a5)
</details>

<details>
<summary>Native - After</summary>
![Native-after](https://github.com/Expensify/App/assets/111440031/5dfbf52f-bf87-4c73-a2d6-fc87a1325b87)


</details>

<details>
<summary>Web - Before</summary>
<img width="430" alt="web-before" src="https://github.com/Expensify/App/assets/111440031/30579d1d-ac79-403f-848d-6a0f87c1265b">


</details>

<details>
<summary>Web - After</summary>
<img width="430" alt="Web-after" src="https://github.com/Expensify/App/assets/111440031/f988344b-bd6b-47cd-a2e0-2aa9bb88e33e">


</details>

**Comment by alexpensify** [comment] 2023-11-07 00:28
@situchan when you get a chance, can you share feedback here for the next steps? Thanks!

**Comment by situchan** [comment] 2023-11-08 14:04
@Nathan-Mulugeta I meant desktop web

**Comment by situchan** [comment] 2023-11-08 14:05
Wanna check the padding of unread indicator vs separator line

**Comment by Nathan-Mulugeta** [comment] 2023-11-08 15:04
Ow I see @situchan , here you go then:

<details>
<summary>Desktop web - Before</summary>
<img width="430" alt="web-before" src="https://github.com/Expensify/App/assets/111440031/16613ad1-9e0f-4c37-a41e-18d59b349702">

</details>

<details>
<summary>Desktop web - After</summary>
<img width="430" alt="web-after" src="https://github.com/Expensify/App/assets/111440031/77cbfecb-5be7-4559-92aa-7ba4fee7a410">
</details>

The desktop web padding remains unchanged before and after the change.

**Comment by alexpensify** [comment] 2023-11-09 00:56
Reassigning another 🐛  team member, I'm going OOO until Tuesday, November 14, and will take it back if it's still open by my return date.

@puneetlath  - Required action from the team: 

Please keep an eye out that this one is moving forward and we find a proposal, thanks!

**Comment by situchan** [comment] 2023-11-13 21:18
What I wanna confirm is that if positions of unread marker and separator should exactly match on every platform.

**Comment by Nathan-Mulugeta** [comment] 2023-11-14 10:44
Upon further exploration, it became evident to me that the issue has extended beyond mobile devices and now affects the web interface as well. Consequently, I've updated my proposal to address this bug.
## Proposal
[Updated](https://github.com/Expensify/App/issues/30360#issuecomment-1779682019)

**Comment by alexpensify** [comment] 2023-11-15 01:35
I'm back and unassigning my buddy. 

@situchan - can you review the updated proposal? Thanks!

**Comment by situchan** [comment] 2023-11-16 20:20
I will provide update shortly. I think we need to get confirmation from design team about the expected behavior on https://github.com/Expensify/App/issues/30360#issuecomment-1809139211

**Comment by alexpensify** [comment] 2023-11-16 20:41
@situchan do you have a thread in the Open Source slack room and we can add the link here? If no, I can start one.

**Comment by situchan** [comment] 2023-11-16 20:44
I don't have thread yet. You can start new one. Thanks

**Comment by alexpensify** [comment] 2023-11-19 16:53
Reassigning another team member, I'm going OOO until Monday, November 27, and will take it back if it's still open by my return date.

@sonialiap  - Required action from the team:

I didn't get a chance to start the discussion in the Open Source room and get the design to chime in. Can you please start one and keep this one moving forward? Thanks!

**Comment by sonialiap** [comment] 2023-11-22 11:45
posted a comment for design on the original bug report 

https://expensify.slack.com/archives/C049HHMV9SM/p1700653488344659?thread_ts=1698067716.752699&cid=C049HHMV9SM

**Comment by sonialiap** [comment] 2023-11-22 13:58
@situchan 

Shawn responded with
>Yeah, I thought the idea was that the unread marker would replace the exact position of the current horizontal rule that separates the total and the first message

**Comment by alexpensify** [comment] 2023-11-27 17:57
I'm going to remove my buddy and take this one back. 

@situchan - based on the feedback received last week, can we continue forward here? If not, can you share why and we can find the answers? Thanks!

**Comment by alexpensify** [comment] 2023-11-29 19:41
@situchan any update here?

**Comment by situchan** [comment] 2023-11-29 19:42
I will provide feedback on proposals by tomorrow

**Comment by alexpensify** [comment] 2023-12-01 18:09
@situchan will any of the proposals work?

**Comment by alexpensify** [comment] 2023-12-04 21:38
@situchan any news?

**Comment by alexpensify** [comment] 2023-12-06 18:49
@situchan - any update here?

**Comment by situchan** [comment] 2023-12-08 17:37
> the unread marker would replace the exact position of the current horizontal rule that separates the total and the first message

Here's feedback from design team.
Based on this, I don't think anyone proposed right solution to meet the expected behavior on all platforms.

**Comment by alexpensify** [comment] 2023-12-08 17:38
Ok, thanks, we need more proposals here then or someone to update their proposal.

**Comment by alexpensify** [comment] 2023-12-11 18:47
@situchan can you review the feedback that @tienifr shared here? Thanks!

**Comment by alexpensify** [comment] 2023-12-13 22:00
@situchan - any update for @tienifr? Thanks!

**Comment by alexpensify** [comment] 2023-12-18 23:48
@situchan can you please review @tienifr's latest reply? Thanks!

**Comment by alexpensify** [comment] 2023-12-20 23:58
No update, still waiting on feedback here.

**Comment by situchan** [comment] 2023-12-20 23:58
I will provide update by tomorrow

**Comment by alexpensify** [comment] 2023-12-21 00:03
Thank you!

**Comment by alexpensify** [comment] 2023-12-23 18:30
**Heads up, I will be offline from Friday, December 22, to Thursday, January 4, 2024. I will not be actively watching over this GitHub during this period. If anything urgent is needed here, please ask for help in the #expensify-open-source Slack Room-- thanks!**

**Comment by alexpensify** [comment] 2024-01-04 19:11
@situchan any update here regarding the feedback for @tienifr?

**Comment by situchan** [comment] 2024-01-05 17:45
sorry for delay here. I am evaluating again

**Comment by dragnoir** [comment] 2024-01-08 09:01
@situchan is this still open for proposals?

**Comment by situchan** [comment] 2024-01-08 09:02
> @situchan is this still open for proposals?

yes, if we have another approach than previous proposals

**Comment by dragnoir** [comment] 2024-01-08 18:15
## Proposal

### Please re-state the problem that we are trying to solve in this issue.

Padding below total change when thread is on unred state.

### What is the root cause of that problem?
This issue is related to the padding adjustment when threads transition from an unread to a read state. This issue is observed in three distinct views:
 - MoneyReportView
 - TaskView
 - MoneyRequestView

<details>
<summary>MoneyReportView</summary>

https://github.com/Expensify/App/assets/12425932/ca7e84c2-35d9-46bc-9776-e9187cec3a45

</details>

<details>
<summary>TaskView</summary>

https://github.com/Expensify/App/assets/12425932/ec20ba57-345e-48a1-9750-be143313679b

</details>

<details>
<summary>MoneyRequestView</summary>

https://github.com/Expensify/App/assets/12425932/be9a6411-8c0d-4c09-8d04-1d9f114fe081

</details>

Each of these views exhibit a padding inconsistency when displaying thread status changes.

These views are integrated within the `ReportActionItem` component, using the property `shouldShowHorizontalRule={!props.shouldHideThreadDividerLine}`.

https://github.com/Expensify/App/blob/b9c2514294d64e969f1eb07a4b75989340ffd06c/src/pages/home/report/ReportActionItem.js#L615-L618

The core of this issue lies in the styling discrepancy between the "New" (green) and (grey) thread divider lines. The `shouldHideThreadDividerLine` property toggles the visibility of the grey line based on the presence of the green "New" indicator.
`shouldHideThreadDividerLine` check if the 1st report under the grey line has the green line of the "New" unread.
If there's a green line, then `shouldHideThreadDividerLine` is true and the the grey line is hidden.

https://github.com/Expensify/App/blob/b9c2514294d64e969f1eb07a4b75989340ffd06c/src/pages/home/report/ReportActionsList.js#L337-L340

The problem arises due to the different styling attributes of these lines, resulting in a noticeable shift in padding when the green line replaces the grey one.

### What changes do you think we should make in order to solve the problem?

We need to change the style of the green line "New" only for the 1st report under the green line.
1- On ReportActionItem when the green line component is called [here](https://github.com/Expensify/App/blob/b9c2514294d64e969f1eb07a4b75989340ffd06c/src/pages/home/report/ReportActionItem.js#L678), we need to pass a new props `shouldHideThreadDividerLine`
```jsx
<UnreadActionIndicator
  reportActionID={props.action.reportActionID}
  shouldHideThreadDividerLine={props.shouldHideThreadDividerLine}
/>
```
We will inform the component `UnreadActionIndicator` that represent the green line in the UI, if it's associated with the first report and if it's replacing the green line. Now the component of the green line (New) will be aware if it will replace the grey line (seperator)

2- Update `UnreadActionIndicator` component [here](https://github.com/Expensify/App/blob/b9c2514294d64e969f1eb07a4b75989340ffd06c/src/components/UnreadActionIndicator.tsx#L20) to have a new style when it's replacing the grey line.
```jsx
<View
style={[shouldHideThreadDividerLine ? styles.unreadIndicatorContainerFirst : styles.unreadIndicatorContainer, styles.userSelectNone, styles.pointerEventsNone]}
>
```
if `shouldHideThreadDividerLine`, then the grey line is hidden and if it's for the 1st report under the grey line, then we will display the green line with the new style I named here `unreadIndicatorContainerFirst` 

We can notice that the green line had an absolute position, so it will not take space, we have to change this to relative position with margin adjustment to have the same space in the UI as the grey line.
```js
unreadIndicatorContainerFirst: {
  position:  'relative',
  top:  0,
  left:  0,
  marginBottom:  8,
  // other part of the style
},
```
When the grey line is removed it happens with an animation, we can adjust this in PR process if needed.

> the unread marker would replace the exact position of the current horizontal rule that separates the total and the first message

As the design team mentioned, this solution will make the grenn line (New) replace the exact position of the grey line (separator).

POC videos:
I am using a virtual rule to make it easu to noyice tha Total is always in same place.

<details>
<summary>Mobile</summary>

https://github.com/Expensify/App/assets/12425932/3f3026f6-5c0e-4f05-8d7d-d8e49ead31e3

</details>

<details>
<summary>Web</summary>

https://github.com/Expensify/App/assets/12425932/25783b18-7d65-4b38-bc8e-37dd8340479f

</details>

**Comment by alexpensify** [comment] 2024-01-10 18:39
@situchan any feedback for the proposals here? Thanks!

**Comment by situchan** [comment] 2024-01-11 17:13
@dragnoir thanks for the proposal. Do you mind sharing test branch for testing purpose?

**Comment by dragnoir** [comment] 2024-01-12 08:30
@situchan this is the one I used for the video DEMO in my proposal: https://github.com/dragnoir/App/tree/30360-mos-test
Let me know if you need any additional editing.

**Comment by situchan** [comment] 2024-01-12 11:18
Checking

**Comment by situchan** [comment] 2024-01-15 17:08
@dragnoir I don't think your solution works on both web and native based on my testing

**Comment by dragnoir** [comment] 2024-01-15 17:13
@situchan I think native issues can be handled throw PR. What part do you think is not working on native? 
I think the main idea here is to catch the reason behinf the issue, describe a solution. Making the solution perfect and tested, can be done throw PR.

I can work more on the solution if you want.

**Comment by dragnoir** [comment] 2024-01-16 07:00
@situchan bump ^

**Comment by alexpensify** [comment] 2024-01-17 18:31
@situchan any update here? Thanks!

**Comment by dragnoir** [comment] 2024-01-18 06:58
@situchan I am updating my code to effect only windows OS, I will post new link in few hours with screenshots from different OS.

**Comment by situchan** [comment] 2024-01-18 06:59
@dragnoir I am confused. This is not Windows only issue

**Comment by dragnoir** [comment] 2024-01-18 07:00
@situchan yah sorry, mistake, I just updates my comment. I am sending new updates in few hours with demo from mobile.

**Comment by alexpensify** [comment] 2024-01-19 19:49
Waiting for he new examples from @dragnoir

**Comment by dragnoir** [comment] 2024-01-22 13:38
@situchan I tested the code on native phone and on the Emulator from xcode and it's working, below 2 videos POC


https://github.com/Expensify/App/assets/12425932/1470330e-4d69-4a91-939b-7e61300c27d8


https://github.com/Expensify/App/assets/12425932/a0ff4d39-87b6-45a1-abf1-9945cbc6f3c9

**Comment by dragnoir** [comment] 2024-01-23 09:15
@situchan let me know if you need more details.

**Comment by situchan** [comment] 2024-01-23 21:34
Thanks for demo. I will provide feedback asap

**Comment by alexpensify** [comment] 2024-01-26 18:42
No update yet, waiting for feedback.

**Comment by situchan** [comment] 2024-01-26 18:42
eta Monday

**Comment by dragnoir** [comment] 2024-01-29 19:13
@situchan friendly bump ^

**Comment by situchan** [comment] 2024-01-29 19:14
updating by eod

**Comment by situchan** [comment] 2024-01-30 08:17
@dragnoir I don't see any improvement in your solution. As you see, indicator still flickers


https://github.com/Expensify/App/assets/108292595/d3d346a1-8a1c-46a0-8bcb-cd9ab1193cd8

**Comment by dragnoir** [comment] 2024-01-30 08:20
@situchan the issue is not about flickers. The main issue is that the change make an extra padding. My solution solve this.

The flickers effect is due to the animation. Please check QA flow again.

**Comment by situchan** [comment] 2024-01-30 08:21
@dragnoir do you think the video above is acceptable? This looks even worse than production behavior

**Comment by dragnoir** [comment] 2024-01-30 08:24
@situchan 

> Expected Result:
App should have equal padding below total irrespective of presence of 'New' line

my solution is a fix for this. I can solve the flickers effect on PR.

**Comment by situchan** [comment] 2024-01-30 08:52
@dragnoir unread indicator should not move


https://github.com/Expensify/App/assets/108292595/0f6c5063-ae1a-496e-8b4d-7087a03aa170

**Comment by situchan** [comment] 2024-01-30 09:35
@tienifr can you please update your proposal? No marginBottom logic anymore in ReportActionItem

**Comment by dragnoir** [comment] 2024-01-30 20:25
@situchan Please check the video below, I fixed the flikkering effect (local dev).

https://github.com/Expensify/App/assets/12425932/df44df46-6111-4e51-a711-f650f39d7fd2

The idea is to display the green line is place of the grey on the same area. This solve the issue because boath lines green and grey will be displayed on the same x, y.

Please let me know if you need to see more adjustments.

**Comment by situchan** [comment] 2024-02-02 15:08
@dragnoir thanks. That matches the expected behavior (Option 1) we recently [discussed](https://expensify.slack.com/archives/C049HHMV9SM/p1706627107285609?thread_ts=1698067716.752699&cid=C049HHMV9SM):

Option 1. 8px space between separator and first report action

pros: no design change when no unread indicator (current version)
cons: unread indicator (8px space) has different spacing than other report actions (no space)

~Option 2. no space between separator and first report action
pros: unread indicator positions are consistent between all report actions (current version)
cons: design change when no unread indicator~


Everyone, please update proposals accordingly

**Comment by dragnoir** [comment] 2024-02-05 10:14
@situchan I updated my a new [alternative solution](https://github.com/Expensify/App/issues/30360#issuecomment-1881594766)

I can't access to the link you mentioned 

> we recently [discussed](https://expensify.slack.com/archives/C049HHMV9SM/p1706627107285609?thread_ts=1698067716.752699&cid=C049HHMV9SM):

Can you please elaborate more on what the Option 1 means, de we need to keep spaces??  Thank you

**Comment by situchan** [comment] 2024-02-05 10:52
So your video [here](https://github.com/Expensify/App/issues/30360#issuecomment-1917832133) looks correct

**Comment by alexpensify** [comment] 2024-02-07 23:52
No update

**Comment by situchan** [comment] 2024-02-08 15:42
still waiting for updated proposals based on latest discussion
Meanwhile, I will evaluate @dragnoir's updated solution

**Comment by alexpensify** [comment] 2024-02-09 18:04
Thanks for the update!

**Comment by situchan** [comment] 2024-02-12 15:57
Seems like no one (except @dragnoir) is following [my request](https://github.com/Expensify/App/issues/30360#issuecomment-1924068192).
@dragnoir would you mind sharing your test branch?

**Comment by dragnoir** [comment] 2024-02-13 07:57
@situchan I will share a test branch by the end of the day.

**Comment by alexpensify** [comment] 2024-02-14 19:24
Thanks!

**Comment by dragnoir** [comment] 2024-02-16 15:02
I have some conflicts to solve and I will share the bransh ASAP.

**Comment by situchan** [comment] 2024-02-19 15:27
Not overdue

**Comment by dragnoir** [comment] 2024-02-19 17:48
@situchan sorry for the delay, here the main changes https://github.com/dragnoir/App/tree/30360-fix

**Comment by dragnoir** [comment] 2024-02-22 09:38
@situchan I created a video DEMO for the last updates

https://github.com/Expensify/App/assets/12425932/2604181b-0d6a-402a-8b1e-083934de635c

**Comment by alexpensify** [comment] 2024-02-23 00:12
@situchan, keep us posted if this demo is helpful to keep moving forward here. Thanks!

**Comment by situchan** [comment] 2024-02-23 17:08
@dragnoir thanks. I am still checking any possible regressions. I will provide feedback on Monday

**Comment by situchan** [comment] 2024-02-26 14:53
@dragnoir I checked your branch. Still not considered all cases. And that solution doesn't seem ideal to me.
It should be responsive to all types of reports - task view, money report view, money request view, normal thread.

**Comment by dragnoir** [comment] 2024-02-26 16:11
@situchan I added support foir all types of reports - task view, money report view, money request view, normal thread. You can check the branch again.



> Here's bug to fix in normal thread:
> 
> <img alt="Screenshot 2024-02-26 at 8 55 33 PM" width="773" src="https://private-user-images.githubusercontent.com/108292595/307837293-8b8c9e50-644e-4573-9768-5c5b4e8eb844.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDg5NjMxNzEsIm5iZiI6MTcwODk2Mjg3MSwicGF0aCI6Ii8xMDgyOTI1OTUvMzA3ODM3MjkzLThiOGM5ZTUwLTY0NGUtNDU3My05NzY4LTVjNWI0ZThlYjg0NC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMjI2JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDIyNlQxNTU0MzFaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT00OWEyYjlkMWQwZGNiNDU3OWI3MjE3YTcwMzQ2Y2E0ZDM3ZWI3YzE2MTVhOWNjNmI3MGQ3NDg1NjQ3ZjZhOTllJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.MWCOgqqyICLVsxdboXqk-OuAB5GMQilmjiWaHuedeLk">

How can I reproduce this bug? I don't have it on my side.

![image](https://github.com/Expensify/App/assets/12425932/956d23cc-5b06-4dd9-b5be-c542eba48ae3)

**Comment by dragnoir** [comment] 2024-02-28 19:28
@situchan pls!

**Comment by situchan** [comment] 2024-02-28 19:30
> that solution doesn't seem ideal to me.

Still same feedback ^

**Comment by dragnoir** [comment] 2024-02-28 19:41
@situchan pls explain why!!! You were asking for DEMOs, updates and branches and when it's perfectly working, you just don't like it!!!

**Comment by situchan** [comment] 2024-02-28 19:44
@dragnoir how about trying to add `SpacerView` in `ReportActionItem` instead of all other components case by case?

**Comment by situchan** [comment] 2024-02-28 19:48
So we can pick up better approach

**Comment by dragnoir** [comment] 2024-02-28 19:51
@situchan thanks for your feedback, but sorry I will not do more updates or branches for demo. The idea is clear، I can enhance in PR if you like the main concept.

**Comment by dragnoir** [comment] 2024-02-28 20:06
@situchan you have every thing to decide. Thanks for your time

**Comment by alexpensify** [comment] 2024-03-01 02:05
Heads up, I will be offline until Tuesday, March 5, 2024. I will not be actively watching over this GitHub during that period. If anything urgent is needed here, please ask for help in the Open Source Slack Room-- thanks!

**Comment by situchan** [comment] 2024-03-05 15:15
As I haven't heard from @dragnoir for a week, I think this can be open for new proposals.

**Comment by dragnoir** [comment] 2024-03-05 15:19
@situchan, could you please clarify your request?

You inquired about the following:

> how about trying to add SpacerView in ReportActionItem instead of all other components case by case?

To which I responded affirmatively, acknowledging that this approach aligns with the workflow I had proposed. Initially, I was integrating the solution into each component individually. However, I concur that centralizing the implementation within ReportActionItem is feasible and I can undertake this adjustment during the PR (Pull Request) review process.

**Comment by situchan** [comment] 2024-03-05 15:22
> To which I responded affirmatively, acknowledging that this approach aligns with the workflow I had proposed. Initially, I was integrating the solution into each component individually. However, I concur that centralizing the implementation within ReportActionItem is feasible and I can undertake this adjustment during the PR (Pull Request) review process.

https://github.com/Expensify/App/compare/main...dragnoir:App:30360-fix
@dragnoir is this your latest branch? I am not seeing this

**Comment by alexpensify** [comment] 2024-03-08 18:52
We are still open for proposals here.

**Comment by alexpensify** [comment] 2024-03-08 19:38
We are still open for proposals here.

**Comment by alexpensify** [comment] 2024-03-11 23:23
Still open for proposals.

**Comment by dragnoir** [comment] 2024-03-12 07:41
@situchan 

[Alternative solution](https://github.com/Expensify/App/issues/30360#issuecomment-1881594766) updates as per your recommendation.

> @dragnoir how about trying to add SpacerView in ReportActionItem instead of all other components case by case?

**Comment by alexpensify** [comment] 2024-03-13 17:44
@situchan can you please review the new alternative here? Thanks!

**Comment by situchan** [comment] 2024-03-15 20:57
@dragnoir's [proposal](https://github.com/Expensify/App/issues/30360#issuecomment-1881594766) looks good to me. I prefer alternative solution.
🎀 👀 🎀 C+ reviewed

**Comment by alexpensify** [comment] 2024-03-20 23:56
The PR is in the works

**Comment by alexpensify** [comment] 2024-03-22 19:28
@dragnoir - is there a PR? I checked the status and don't see one linked yet. Thanks!

**Comment by alexpensify** [comment] 2024-03-26 00:34
Thanks! Regressions are always a priority.

**Comment by alexpensify** [comment] 2024-03-27 20:04
No update here

**Comment by alexpensify** [comment] 2024-03-29 17:37
The PR is in a draft-- making progress

**Comment by alexpensify** [comment] 2024-04-05 22:37
Update: The PR is waiting for @Beamanator to review it.

**Comment by alexpensify** [comment] 2024-04-12 23:31
Update: The PR is moving forward

**Comment by alexpensify** [comment] 2024-04-16 23:10
Weekly Update: The PR is going through some polish updates to help the design.

**Comment by Beamanator** [comment] 2024-04-23 07:37
FYI I'm assigning @DylanDylann as C+ to review - but I haven't unassigned @situchan since they also did a review a bit ago.

**Comment by alexpensify** [comment] 2024-04-30 22:35
Weekly Update: Looks like the PR is going through a final review.

**Comment by alexpensify** [comment] 2024-05-07 21:58
@DylanDylann - can we get an update if this Deploy Blocker is accurate or an error? Thanks!

**Comment by DylanDylann** [comment] 2024-05-08 02:40
@alexpensify Yeah, It is a regression

**Comment by alexpensify** [comment] 2024-05-14 22:17
Thank you for this context! It looks like the automation failed here and payment is due for this one. I'll work on that process.

**Comment by alexpensify** [comment] 2024-05-14 22:40
Ok, flagging this notice: https://github.com/Expensify/App/issues/30360#issuecomment-2071630087

@dragnoir, @DylanDylann, and @situchan - can you please apply to the job here: https://www.upwork.com/jobs/~0104d969f5990f36bd

After, I can carry on with the payment process. Thanks!

**Comment by alexpensify** [comment] 2024-05-14 22:44
Please disregard the last comment. 

Ok, flagging this notice: https://github.com/Expensify/App/issues/30360#issuecomment-2071630087

@dragnoir please apply here: https://www.upwork.com/jobs/~0104d969f5990f36bd

Everyone else will be paid via this link: https://www.upwork.com/jobs/~0158fbfd6d89166dba

After, I can carry on with the payment process. Thanks!

**Comment by alexpensify** [comment] 2024-05-15 22:45
Payouts due: 2024-05-13 - delayed due to automation failure 

- [ ] Reported by: $50 @dhanashree-sawant
- [ ] Contributor: $500 @dragnoir 
- [ ] Contributor+: $250 for the partial review @situchan 
- [ ] Contributor+: $500 @DylanDylann 

Upwork job is [here](https://www.upwork.com/jobs/~0158fbfd6d89166dba). The PR was submitted before the payment changes in April. Also, this issue was created in 2023, so that's why there is a reporter bonus.

**Comment by alexpensify** [comment] 2024-05-15 22:46
@dragnoir - I sent you an offer in Upwork. Please accept, and I can complete the payment process.

**Comment by alexpensify** [comment] 2024-05-17 15:38
All set, everyone has been paid via Upwork! 

## Heads up, I will be offline until Tuesday, May 28, 2024, and will not actively watch over this GitHub during that period.

If anything urgent is needed here, please ask for help in the #expensify-open-source Slack Room-- thanks!

**Closed by alexpensify** 2024-05-17 15:38 UTC
Labels: Reviewing, External, Weekly, Bug
