### ISSUE TITLE
Expense - Expense preview in the main chat shows Merchant when the request has a receipt

### ISSUE THREAD

**Issue by izarutskaya** [Expensify/App#37140] opened 2024-02-23 14:53 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** v1.4.43-12
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** Applause-Internal team
**Slack conversation:**

## Action Performed:
1. Go to staging.new.expensify.com.
2. Go to workspace chat.
3. Create a manual request with Merchant and without receipt.
4. Note that the expense preview in the main chat does not show Merchant.
5. Go to request details page.
6. Add a receipt to the request.
7. Return to workspace chat.

## Expected Result:
The expense preview in the main chat will not show Merchant.

## Actual Result:
The expense preview in the main chat shows Merchant when the request has a receipt.

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [x] Android: mWeb Chrome
- [x] iOS: Native
- [x] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

https://github.com/Expensify/App/assets/115492554/77c8939f-0a7d-4350-b182-8f98d0beabe6

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by izarutskaya** [comment] 2024-02-23 14:54
I haven't added the External label as I wasn't 100% sure about this issue. Please take a look and add the label if you agree it's a bug and can be handled by external contributors.


We think that this bug might be related to #wave5-free-submitters
CC @dylanexpensify

**Comment by bi-kash** [comment] 2024-02-23 16:35
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
Expense Preview message shows a merchant when the request has a reciept added later without a smart scan

### What is the root cause of that problem?
Currently function reportPreview: https://github.com/Expensify/App/blob/c71387c6dc3d2baf052d02701db650cebc397d86/src/components/ReportActionItem/ReportPreview.tsx#L86 follows following condition to show a subtitle in Expense preview message

Show subtitle if at least one of the money requests is not being smart scanned, and either:
- There is more than one money request – in this case, the "X requests, Y scanning" subtitle is shown;
- There is only one money request, it has a receipt and is not being smart scanned – in this case, the request merchant is shown;
```javascript
let formattedMerchant = numberOfRequests === 1 && hasReceipts ? TransactionUtils.getMerchant(transactionsWithReceipts[0]) : null;
if (TransactionUtils.isPartialMerchant(formattedMerchant ?? '')) {
    formattedMerchant = null;
}
const previewSubtitle =
    // Formatted merchant can be an empty string
    // eslint-disable-next-line @typescript-eslint/prefer-nullish-coalescing
    formattedMerchant ||
    translate('iou.requestCount', {
        count: numberOfRequests - numberOfScanningReceipts,
        scanningReceipts: numberOfScanningReceipts,
    });
//Remaininng part of the code
const shouldShowSingleRequestMerchant = numberOfRequests === 1 && !!formattedMerchant && !(hasOnlyTransactionsWithPendingRoutes && !totalDisplaySpend);
const shouldShowSubtitle = !isScanning && (shouldShowSingleRequestMerchant || numberOfRequests > 1);      
```

### What changes do you think we should make in order to solve the problem?
We simply change the condition in these part of code:
```javascript
const previewSubtitle =
    translate('iou.requestCount', {
        count: numberOfRequests - numberOfScanningReceipts,
        scanningReceipts: numberOfScanningReceipts,
    });

//Remaininng part of the code

const shouldShowSubtitle = !isScanning && (numberOfRequests > 1);      
```

We can use above code roughly to solve this problem. Please give me if there is any condition we require merchant to be shown in subtitle.


### What alternative solutions did you explore? (Optional)
NA

**Comment by joekaufmanexpensify** [comment] 2024-02-23 16:45
Hm, I don't think this is a bug. It feels correct that we would show the merchant if the receipt is added, since that's what we do when a user creates a receipt scan request. Closing for now, but LMK if anyone disagrees!

**Closed by joekaufmanexpensify** 2024-02-23 16:45 UTC
Labels: Daily, Bug
