### ISSUE TITLE
[$500] [MEDIUM] IOU - Splitting money (Scan) in the group shows different messages in the user chat

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#34913] opened 2024-01-22 19:21 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:**1.4.29-1
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**If this was caught during regression testing, add the test name, ID and link from TestRail:** https://expensify.testrail.io/index.php?/runs/view/19702&group_by=cases:section_id&group_order=asc&group_id=229063
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** Applause - Internal Team
**Slack conversation:**

## Action Performed:
1. Log in with User A and open User B's chat
2. Go to the group chat
3. Navigate to Split > Scan
4. Select a receipt and send it
5. Repeat the Split > Scan process and complete the flow
6. Log in with User B from another browser and open User A's chat
7. Observe the chat there are 2 requests with different messages

## Expected Result:
Scan requests should be displayed in one message, indicating (2 requests)

## Actual Result:
Splitting money (Scan) in the group shows different messages in the user chat

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [x] Android: mWeb Chrome
- [ ] iOS: Native
- [x] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details> 

https://github.com/Expensify/App/assets/78819774/24b39575-da8b-4c52-9eba-d25decd812d5

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~010afa9e21239fc269</li>
        <li>Upwork Job ID: 1749512680448118784</li>
        <li>Last Price Increase: 2024-02-20</li>
    </ul>
</details>

**Comment by lanitochka17** [comment] 2024-01-22 19:23
We think that this bug might be related to #wave5. 
CC @DylanDylann

**Comment by jjcoffee** [comment] 2024-01-24 16:04
@neonbhai Sorry, I'm not sure how your proposal relates to this issue. As I understand it, this issue relates to multiple scan requests not being folded into one. Is that right @lanitochka17? 

Also, you've tagged the wrong Dylan, I think you meant @dylanexpensify :smile:

**Comment by jjcoffee** [comment] 2024-01-25 07:50
Hehe no worries, it happens more often than you'd think!

**Comment by jjcoffee** [comment] 2024-01-30 12:30
No proposals yet!

**Comment by dylanexpensify** [comment] 2024-01-30 12:56
Moved to wave5!

**Comment by jjcoffee** [comment] 2024-02-06 12:52
@lanitochka17 Can you recheck this? I can't reproduce the issue anymore.

**Comment by slafortune** [comment] 2024-02-12 16:10
I've added the retest label so that this will get picked up to be retested.

**Comment by jjcoffee** [comment] 2024-02-14 09:22
@lanitochka17 Friendly bump to retest this, please!

**Comment by greg-schroeder** [comment] 2024-02-20 06:10
There's no BZ on this issue, so re-assigning `Bug` label and `External`

**Comment by jjcoffee** [comment] 2024-02-20 16:16
@isabelastisser I'm a bit unsure on the expected behaviour here, are you able to double check if this is definitely incorrect?

**Comment by isabelastisser** [comment] 2024-02-22 15:53
@jjcoffee, I agree; I'm pretty sure this is the correct flow and that we expect different views from user A splitting the expense and user B viewing the split in chat. I am closing this.

**Closed by isabelastisser** 2024-02-22 15:53 UTC
Labels: External, Engineering, Daily, Help Wanted, Bug
