### ISSUE TITLE
[PAY HUZAIFA][HOLD ON #15212] [$1000] The 'new messages' floating indicator doesnt go away after clicking it

### ISSUE THREAD

**Issue by kavimuru** [Expensify/App#21288] opened 2023-06-22 00:05 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Open a chat with more than 50 messages (just so we can scroll 2-3 times page height)
2. Go to a message in the middle of the chat
3. Mark it as unread
4. Now click on the 'New Messages' floating button that should not be visible, it will scroll to bottom on click
5. Now scroll to top
6. Notice the 'New Messages' button is still there.
## Expected Result: 
The floating 'new messages' button should disappear after it is pressed and user is scrolled to bottom
## Actual Result: 
The floating 'new messages' button remains visible

## Workaround:
Can the user still use Expensify without this being fixed? Have you informed them of the workaround?

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android / native
- [x] Android / Chrome
- [x] iOS / native
- [x] iOS / Safari
- [x] MacOS / Chrome / Safari
- [x] MacOS / Desktop

**Version Number:** 1.3.30-5
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/43996225/11ae8d7b-253a-49f6-b571-c26450e9fcf5

https://github.com/Expensify/App/assets/43996225/5f5177f1-65b2-4add-9795-00bd1cfcc619

**Expensify/Expensify Issue URL:**
**Issue reported by:** @huzaifa-99 
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1686833432496709

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01b010060f9e3fbd46</li>
        <li>Upwork Job ID: 1671682043008094208</li>
        <li>Last Price Increase: 2023-06-22</li>
    </ul>
</details>

**Comment by jliexpensify** [comment] 2023-06-22 00:49
Weird one - I can repro on v1.3.30-5.

**Comment by jeet-dhandha** [comment] 2023-06-22 00:57
## Proposal
### Please re-state the problem that we are trying to solve in this issue.
- The problem is that when we press on New Messages button it takes us to the latest message but doesn't mark it as read.
- Also when we scroll manually down to the latest message it doesn't mark it as read too.

### What is root cause of that problem?
- The root cause of this problem is that we are not setting `newMarkerReportActionID` as empty string when we are pressing on `New Messages`` button or when we are scrolling manually down to the latest message.

### What Changes do you think we should make in order to solve the problem?
Affected File Code: 

- We should set `newMarkerReportActionID` as empty string when we are pressing on `New Messages` button.
https://github.com/Expensify/App/blob/e6c4b4e2f0bf9f42e57bebdd7720ee776ab6c93a/src/pages/home/report/ReportActionsView.js

```diff
    scrollToBottomAndMarkReportAsRead() {
        ReportScrollManager.scrollToBottom();
        Report.readNewestAction(this.props.report.reportID);
+       this.setState({newMarkerReportActionID: ''});
    }
```

- And also call same function `scrollToBottomAndMarkReportAsRead` when we are scrolling manually down to the latest message.
https://github.com/Expensify/App/blob/e6c4b4e2f0bf9f42e57bebdd7720ee776ab6c93a/src/pages/home/report/ReportActionsView.js#L311-L314

```diff
    trackScroll({nativeEvent}) {
        this.currentScrollOffset = -nativeEvent.contentOffset.y;
        
+       // If the user scrolls to the top of the list, we want to mark the report as read
+       if(nativeEvent.contentOffset.y === 0 ) {
+           this.scrollToBottomAndMarkReportAsRead();
+       }

        this.toggleFloatingMessageCounter();
    }
```

Fixed:

https://github.com/Expensify/App/assets/78416198/8a857416-cfcf-4752-abb0-8bdd29053e33



### What alternative solutions did you explore? (Optional)
- N/A

**Comment by thehamzaasif** [comment] 2023-06-22 04:12
In ReportActionsView.js (line 8), initialize the state property newMarkerReportActionID to an empty string:



constructor(props) {
    super(props);
    this.state = {
        newMarkerReportActionID: ''
    };
}

Inside the scrollToBottomAndMarkReportAsRead function (line 12), set newMarkerReportActionID to an empty string:


scrollToBottomAndMarkReportAsRead() {
    ReportScrollManager.scrollToBottom();
    Report.readNewestAction(this.props.report.reportID);
    this.setState({ newMarkerReportActionID: '' });
}

In the trackScroll function (lines 20-24), check if the user has scrolled to the top of the list, and if so, call scrollToBottomAndMarkReportAsRead:


trackScroll({ nativeEvent }) {
    this.currentScrollOffset = -nativeEvent.contentOffset.y;
    
    // If the user scrolls to the top of the list, we want to mark the report as read
    if (nativeEvent.contentOffset.y === 0) {
        this.scrollToBottomAndMarkReportAsRead();
    }
    
    this.toggleFloatingMessageCounter();
}



By making these modifications, when the user presses the "New Messages" button or manually scrolls to the top of the list, the scrollToBottomAndMarkReportAsRead function will be called, and the newMarkerReportActionID state will be set to an empty string, achieving the desired behavior.

**Comment by wildan-m** [comment] 2023-06-22 04:16
@thehamzaasif please use [this template](https://github.com/Expensify/App/blob/main/contributingGuides/PROPOSAL_TEMPLATE.md) for your proposal. More info about contributing guide can be [read here](https://github.com/Expensify/App/blob/main/contributingGuides/CONTRIBUTING.md).

**Comment by thehamzaasif** [comment] 2023-06-22 04:26
Please re-state the problem that we are trying to solve in this issue.

The problem we are trying to solve is that when the user presses the "New Messages" button or manually scrolls down to the latest message in the Expensify application, the message is not marked as read. This behavior is undesirable as it can lead to confusion and difficulty in tracking unread messages.

What is the root cause of that problem?
The root cause of this problem is that the current code does not include the necessary logic to mark the message as read when the user performs these actions.

Changes:

Instead of relying on the newMarkerReportActionID state, we can modify the code to directly mark the message as read when the user triggers the "New Messages" button or manually scrolls down to the latest message. Here's an alternative approach:

In the scrollToBottomAndMarkReportAsRead function (ReportActionsView.js):

Remove the line this.setState({ newMarkerReportActionID: '' }); as we won't be using the newMarkerReportActionID state.
In the trackScroll function (ReportActionsView.js):

Remove the check for nativeEvent.contentOffset.y === 0 and the call to this.scrollToBottomAndMarkReportAsRead();.
Update the onClick handler for the "New Messages" button:

Locate the code that handles the "New Messages" button click event and add the following line after scrolling to the latest message:




Report.readNewestAction(this.props.report.reportID);

Update the code that handles manual scrolling to the latest message:

Locate the code that handles the manual scrolling event to the latest message (e.g., in a scroll event listener).
After scrolling to the latest message, add the following line:

Report.readNewestAction(this.props.report.reportID);

By making these alternative changes, the message will be marked as read directly when the user triggers the "New Messages" button or manually scrolls down to the latest message. This approach bypasses the need for the newMarkerReportActionID state and ensures that the message is correctly marked as read, addressing the problem effectively.

**Comment by wildan-m** [comment] 2023-06-22 07:00
## Proposal

### Please re-state the problem that we are trying to solve in this issue.

The 'new messages' floating indicator doesn't go away after clicking it and the scroll reaches the bottom

### What is the root cause of that problem?

We are not adding `isUnread` check here

https://github.com/Expensify/App/blob/e6c4b4e2f0bf9f42e57bebdd7720ee776ab6c93a/src/pages/home/report/ReportActionsView.js#L343-L344

Also when the scroll reaches the bottom, we are not removing the marker and reading the newest action.

### What changes do you think we should make in order to solve the problem?
We can add `ReportUtils.isUnread(this.props.report)` check here

https://github.com/Expensify/App/blob/e6c4b4e2f0bf9f42e57bebdd7720ee776ab6c93a/src/pages/home/report/ReportActionsView.js#L343-L344

and modify the `trackScroll` function to
```
    trackScroll({nativeEvent}) {
        this.currentScrollOffset = -nativeEvent.contentOffset.y;

        if (this.currentScrollOffset === 0) {
            Report.readNewestAction(this.props.report.reportID);
            this.setState({newMarkerReportActionID: ''});
            return;
        }

        this.toggleFloatingMessageCounter();
    }
```

according to this comment:



### What alternative solutions did you explore? (Optional)
N/A

**Comment by mgotz607** [comment] 2023-06-22 18:48
# Proposal
## Please re-state the problem that we are trying to solve in this issue.
Once unread message is checked, the 'New Messages' indicator won't be disappeared.

## What is the root cause of that problem?
The current code does not update the state - newMarkerReportActionID after unread message is checked.

## What changes do you think we should make in order to solve the problem?
We can update this state - newMarkerReportActionID to check the message is checked or not.

```
    scrollToBottomAndMarkReportAsRead() {
        ReportScrollManager.scrollToBottom();
        Report.readNewestAction(this.props.report.reportID);
        // should update state
        this.setState({newMarkerReportActionID: ''});
    }
```

If the user scrolls to the top of the list, we want to mark the report as read
```
    trackScroll({nativeEvent}) {
        this.currentScrollOffset = -nativeEvent.contentOffset.y;
        if(nativeEvent.contentOffset.y === 0 ) {
            this.scrollToBottomAndMarkReportAsRead();
        }
        this.toggleFloatingMessageCounter();
    }

```

## What alternative solutions did you explore? (Optional)

**Comment by jliexpensify** [comment] 2023-06-24 04:22
@fedirjh got a few proposals, could you take a look? Cheers!

**Comment by jliexpensify** [comment] 2023-06-25 22:32
Thanks for surfacing this one @fedirjh - I'll add this one to the master issue and add HOLD onto this label. I actually think I'm assigned another tracking indicator GH, and the consensus was to HOLD to see if the master issue resolved things.

**Comment by jliexpensify** [comment] 2023-06-30 01:21
On hold.

**Comment by jliexpensify** [comment] 2023-07-20 07:11
On Hold

**Comment by jliexpensify** [comment] 2023-08-22 06:01
Oh hold

**Comment by jliexpensify** [comment] 2023-09-01 07:19
Still on hold

**Comment by jliexpensify** [comment] 2023-09-11 11:40
On hold

**Comment by jliexpensify** [comment] 2023-09-21 23:42
On hold

**Comment by jliexpensify** [comment] 2023-10-24 04:33
On hold!

**Comment by MonilBhavsar** [comment] 2023-11-21 16:55
This should be fixed! We can retest and close this.
Here the expected result is 
- The unread marker is and floating button is visible unless user leaves the chat

**Comment by jliexpensify** [comment] 2023-11-23 00:42
Awesome stuff!

It looks like @huzaifa-99 needs to be paid as the bug reporter. I'll spin up a job and pay him $250. Thanks everyone!

**Comment by jliexpensify** [comment] 2023-11-23 01:00
@huzaifa-99 Upworks is error-ing out on me. Can you please apply here? https://www.upwork.com/jobs/~0114cf334b1532eb43

Thanks!

**Comment by jliexpensify** [comment] 2023-11-23 23:18
Offer sent, thanks @huzaifa-99

**Comment by jliexpensify** [comment] 2023-11-24 03:54
All paid and job closed!

**Closed by jliexpensify** 2023-11-24 03:54 UTC
Labels: External, Monthly, Help Wanted, Bug
