### ISSUE TITLE
[HOLD for payment 2024-12-20] [HOLD for payment 2024-12-11] [$250] Move onboarding tasks into the #admins room for admins

### ISSUE THREAD

**Issue by zsgreenwald** [Expensify/App#51443] opened 2024-10-24 22:18 UTC
### Problem 

By placing onboarding steps in a Concierge DM, it limits the assigned onboarding specialist's ability to collaborate with the customer directly. 

### Solution

When a user selects `Manage my team's expenses` as their onboarding intent, let's update the assigned setup specialists' message to include onboarding Tasks, and post them in the #admins room. See below:

![image](https://github.com/user-attachments/assets/00f411aa-e3ee-4456-a9c7-957da061de18)

1) Since the assigned onboarding specialist's message will get sent first, we'll provide onboarding steps in that same message so it doesn't seem disjointed. 
2) Let's update the assigned onboarding specialist's message to:

> Hey there :wave: I'm your dedicated setup specialist. I look forward to helping you explore and configure Expensify. You can chat with me here anytime if you have any questions, or **book a call** with me directly at your convenience. I've shared some onboarding steps to help you get started below:
> 
> - [ ] task 1
> - [ ] task 2
> - [ ] ....

3) Let's keep the same GIF from the Concierge message and use it in the #admins post 
4) Let's move the `Start your free trial` tooltip over to the #admins row in LHN 
5) Let's keep the welcome message from Concierge, but not have it be pinned in LHN

## Issue Checklist
- [x] https://github.com/Expensify/Expensify/issues/442581
- [x] https://github.com/Expensify/App/issues/52219
- [x] https://github.com/Expensify/App/issues/52220

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~021851283917795612465</li>
        <li>Upwork Job ID: 1851283917795612465</li>
        <li>Last Price Increase: 2024-11-05</li>
<li>Automatic offers: </li>
<ul>
<li>c3024 | Contributor | 104646441</li>
</ul></li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @OfstadC</details>

**Comment by zsgreenwald** [comment] 2024-10-29 15:09
Updated the mock in the OP

**Comment by yuwenmemon** [comment] 2024-11-04 19:53
I'll be handling the internal end here.

**Comment by yuwenmemon** [comment] 2024-11-05 23:42
Discussing this at a planning level here: https://expensify.slack.com/archives/C07HPDRELLD/p1730844663049119?thread_ts=1730777288.450589&cid=C07HPDRELLD

Curious for @deetergp @MonilBhavsar and @francoisl 's take on things as they have worked on this feature in the past.

**Comment by yuwenmemon** [comment] 2024-11-11 20:22
My apologies, this is not open to proposals! @c3024 is going to be working on the front-end portion of this.

Removing the label. It wasn't supposed to be there - sorry about that.

**Comment by yuwenmemon** [comment] 2024-11-14 21:30
Back-end portions for this are in - but @c3024 we should talk about how the Guide messaging logic will work.

**Comment by c3024** [comment] 2024-11-15 03:20
Backend seems to reject posting the messages and tasks to #admins room from frontend with `CompleteGuidedSetup`.


https://github.com/user-attachments/assets/4d550245-2769-45dc-909d-72488dda59f6




They get posted in the #admins room fine offline.

It was working well before.

**Comment by yuwenmemon** [comment] 2024-11-15 04:44
@c3024 What test account are you using?

**Comment by c3024** [comment] 2024-11-15 05:15
@yuwenmemon 

I can repro this on all gmail IDs. These are two emails on which I just reproduced it.

expensifytest729+adminroomtasks3@gmail.com


https://github.com/user-attachments/assets/91541f7e-079a-4b94-97c9-420e4fcd4e5e



expensifytest729+adminroomtasks4@gmail.com

expensifytest729+adminroomtasks5@gmail.com


https://github.com/user-attachments/assets/3948faa6-fcfe-4d55-9693-2371bcd7e3c7

**Comment by yuwenmemon** [comment] 2024-11-15 16:33
Hmmmm... I wasn't able to reproduce it when checking out your branch. Odd.

**Comment by yuwenmemon** [comment] 2024-11-15 16:45
@c3024 From the logs I see that you're trying to create a task from an accountID that doesn't seem to exist 🤔 I would guess it has something to do with you still trying to use the hardcoded QA Account Guide in your code here: https://github.com/Expensify/App/pull/52314/files#diff-ce6bb391d0654bf99a360da7d25fd73b85bb120211c8b4c2432ef7c7d8c708f3R3496

```
8e2cb634288c4af8-HYD	db1.sjc	2024-11-15 05:06:24 589	expensifytest729+adminroomtasks4@gmail.com	Trying to create action (reportID 1653526330306475, requestingAccountID: 500068347245, actionAccountID: 500068347245, action: ADDCOMMENT, reportActionID: 8212635028226681013)
8e2cb634288c4af8-HYD	db1.sjc	2024-11-15 05:06:24 589	expensifytest729+adminroomtasks4@gmail.com	Account writing to chat/task report without permission.
8e2cb634288c4af8-HYD	db1.sjc	2024-11-15 05:06:24 590	expensifytest729+adminroomtasks4@gmail.com	User does not have access to this report (requestingAccountID: 500068347245, reportID: 1653526330306475)
```

As we [discussed](https://expensify.slack.com/archives/C07HPDRELLD/p1731439612037729?thread_ts=1730777288.450589&cid=C07HPDRELLD), the backend is handling the logic for which account will be sending the tasks. You should not be sending it.

Also, once https://github.com/Expensify/Auth/pull/13080 is deployed you will only need to send the tasks. The Guide intro message will be sent from the back-end.

**Comment by c3024** [comment] 2024-11-15 16:53
@yuwenmemon 

Oh, it seemed to work well before.

But, an account ID is required for the sender to create the report actions for tasks in the report.
I think CreateWorkspace called from onboarding intent might need to include `qa.guide` as a participant in #admins. Otherwise, I think there will only be the user in the #admins and the task sender should be the user themself.

**Comment by yuwenmemon** [comment] 2024-11-15 16:58
@c3024, the QA Guide account is merely a test account. It's not going to be the only guide assigned to each user in production. We have different guide accounts that will already be added as participants part of `CreateWorkspace`. This logic is already in place.

What you need to do is pull the guide that is assigned to the user as a part of CreateWorkspace and have _that_ account be the account creating the tasks. Does that make sense?

**Comment by c3024** [comment] 2024-11-15 17:25
@yuwenmemon 

CreateWorkspace does not seem to be returning the personal detail of the guide. 

https://github.com/user-attachments/assets/f4474ee7-d0de-4e4c-b952-9c4a7de5f570

The guide's message in admins room comes a bit later and then the guide's details are available.

https://github.com/user-attachments/assets/a58ca637-cdc0-4815-997c-d2c16a69740f

<img width="1434" alt="Screenshot 2024-11-15 at 10 50 14 PM" src="https://github.com/user-attachments/assets/fe57a4f2-abcb-4c4f-9994-02b320e9bf87">

>We have different guide accounts that will already be added as participants part of CreateWorkspace

Is this already on staging server? I do not see the guide as a participant for the workspace or admins room. Can you please help me with what I am missing? Thanks!

**Comment by yuwenmemon** [comment] 2024-11-15 17:43
> CreateWorkspace does not seem to be returning the personal detail of the guide.

Yes, that will happen when https://github.com/Expensify/Auth/pull/13080 is deployed. What is changing is that the guide message used to be sent via a delayed job, so the message from the guide came a bit later in the flow. Now, the guide message will immediately be in the #admins room upon the workspace's creation.

_However_, that doesn't seem to be necessary for the tasks from the guide to come through successfully when I test on your branch. Have you verified that the hardcoded QA email/account in your PR is not causing your error?

**Comment by c3024** [comment] 2024-11-18 06:01
Could you check for this email why backend is rejecting the report action creation in the admins room?

expensifytest729+202411181126@gmail.com

I changed the actor for the tasks to `currentUserAccountID` so there should be no problem with backend accepting the report actions because current user is already as a member of the admins room. I tried with actor as Concierge too with this email [expensifytest729+202411181107@gmail.com](mailto:expensifytest729+202411181107@gmail.com) but backend rejects for that too.

**Comment by yuwenmemon** [comment] 2024-11-18 21:37
I see the same error you recieved last week
```
8e45b67af9b6f3bd-BOM	db1.sjc	2024-11-18 05:55:39 569	expensifytest729+202411181126@gmail.com	Account writing to chat/task report without permission.
8e45b67af9b6f3bd-BOM	db1.sjc	2024-11-18 05:55:39 569	expensifytest729+202411181126@gmail.com	User does not have access to this report (requestingAccountID: 500068347245, reportID: 293350425599161)
8e45b67af9b6f3bd-BOM	db1.sjc	2024-11-18 05:55:39 569	expensifytest729+202411181126@gmail.com	Throwing exception with message: '404 Report not found' from auth/lib/Report.cpp:772
```

In fact, it's the same non-existent accountID from before: `500068347245`

Can you relay what accountID you are expecting that to correspond to locally?

**Comment by yuwenmemon** [comment] 2024-11-18 21:38
The reportID there is the `#admins` room of policy `273496EC1141128F`

**Comment by jjcoffee** [comment] 2024-11-19 13:50
@yuwenmemon Please can you assign me here as C+ for the PR review? Thanks!

**Comment by IuliiaHerets** [comment] 2024-12-03 12:46
This PR is failing because of issue #53450

**Comment by jjcoffee** [comment] 2024-12-03 12:54
@IuliiaHerets Please retest with an email that doesn't contain a `+`, as the behaviour is different for `+` emails (we don't assign guides in that case, so it doesn't make sense to move the tasks to the `#admins` room). Thanks!

**Comment by IuliiaHerets** [comment] 2024-12-04 08:17
@jjcoffee Issue is not happens with an email that doesn't contain a +

https://github.com/user-attachments/assets/a19243fa-8cc5-4ae8-95b3-4a79c411ed48

**Comment by trjExpensify** [comment] 2024-12-04 19:18
@jjcoffee @yuwenmemon @c3024 we're seeing a few strange things with our FS session reviews, that I think might point to these changes. 

Duplicate tasks in both #admins and the DM with the Guide:

<img width="918" alt="image" src="https://github.com/user-attachments/assets/42d5bdb1-82fe-408b-b948-ceb1962cf06e">

A strange preview of a report action for assignment, that nobody can understand where that's come from:

<img width="357" alt="image" src="https://github.com/user-attachments/assets/1ef33022-1c72-43d2-a8fe-734b81102dd6">

Can ya'll help us investigate?

**Comment by trjExpensify** [comment] 2024-12-04 19:52
Here's another example with both bugs. 

<img width="1132" alt="image" src="https://github.com/user-attachments/assets/65460ed7-23c9-401c-b769-b785d8ea42c1">

At this point, I think we should revert this PR and look into it.

**Comment by yuwenmemon** [comment] 2024-12-05 20:10
@c3024 Did you end up creating a revert of the revert?

**Comment by c3024** [comment] 2024-12-05 21:53
@yuwenmemon  Opened the PR here #53661.

**Comment by OfstadC** [comment] 2024-12-11 16:14
@yuwenmemon Sorry for my confusion but I see this is still being worked on. 

Do we still need to issue payment today and if so, is [this accurate](https://github.com/Expensify/App/issues/51443#issuecomment-2515934945)?

**Comment by yuwenmemon** [comment] 2024-12-11 19:50
@OfstadC You'll want to follow the progress of this PR instead: https://github.com/Expensify/App/pull/53661

**Comment by jjcoffee** [comment] 2024-12-19 10:31
I guess no checklist is needed here as this is a feature addition.

## Regression Test Proposal
### Precondition:


- Have an email that doesn't have a '+' in it.

### Test:


1. Logon to ND with a new email without a '+' in it.
2. Click on "Manage my team's expenses" on the onboarding flow and complete the onboarding.
3. Verify that the onboarding tasks show up in the #admins room.

Do we agree 👍 or 👎

**Comment by OfstadC** [comment] 2024-12-20 14:24
## Payment Summary

- @jjcoffee due $250 via manual NewExpensify Request
- @c3024 [paid $250](https://www.upwork.com/nx/wm/workroom/38838233/overview) via Upwork

**Closed** 2024-12-20 14:24 UTC
Labels: External, Weekly, Internal, Awaiting Payment, Hot Pick

**Comment by garrettmknight** [comment] 2024-12-21 14:04
$250 approved for @jjcoffee
