### ISSUE TITLE
mWeb - When an attachment is long-pressed, the context menu remains behind the attachment until it disappears

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#21908] opened 2023-06-29 21:27 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Login to ND
2. Go to any chat > Send an attachment
3. Long press on an image

## Expected Result:
The attachment disappears and context menu is opened

## Actual Result:
Context menu is opened behind the attachment until it disappears

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [x] iOS / Safari
- [ ] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 1.3.34-1
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/93399543/072ecee8-b7cf-4ae7-b243-0131c8cb386a

https://github.com/Expensify/App/assets/93399543/56489add-a32e-4108-a1e9-ebc830175776

**Expensify/Expensify Issue URL:**
**Issue reported by:** @aman-atg
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1687986710540839

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by s-alves10** [comment] 2023-06-29 21:31
I think this is a dupe of https://github.com/Expensify/App/issues/21344

**Comment by sonialiap** [comment] 2023-07-03 16:10
Agreed, this looks like a dupe of https://github.com/Expensify/App/issues/21344

**Closed by sonialiap** 2023-07-03 16:10 UTC
Labels: Daily, Overdue, Bug
