### ISSUE TITLE
[HOLD for Payment 2024-09-09][$250] Mention - Mention list takes 2-3 seconds to remove after sending a message

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#45485] opened 2024-07-16 14:06 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 9.0.7-4
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**If this was caught during regression testing, add the test name, ID and link from TestRail:** https://expensify.testrail.io/index.php?/runs/view/22744&group_by=cases:section_id&group_order=asc&group_id=306201
**Email or phone of affected tester (no customers):** shussain+andmob2@applausemail.com
**Issue reported by:** Applause - Internal Team

## Action Performed:
1. Open a chat
2. Mention a user by entering their username/email
3. Send the message without selecting the user from the list

## Expected Result:
After sending the message without selecting the user from the list, the mention list should be immediately removed

## Actual Result:
Mention list takes 2-3 seconds to remove after sending a message

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [ ] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details> 

https://github.com/user-attachments/assets/541b09e1-df5b-4e40-9002-5e08c6f605c3

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~012c64667ec4d95daf</li>
        <li>Upwork Job ID: 1813327338752177204</li>
        <li>Last Price Increase: 2024-07-30</li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @ishpaul777</details>

**Comment by lanitochka17** [comment] 2024-07-16 14:06
We think that this bug might be related to #vip-vsp

**Comment by lanitochka17** [comment] 2024-07-16 14:07
@sakluger  FYI I haven't added the External label as I wasn't 100% sure about this issue. Please take a look and add the label if you agree it's a bug and can be handled by external contributors

**Comment by sakluger** [comment] 2024-07-22 23:37
Still no proposals.

**Comment by fabOnReact** [comment] 2024-07-26 08:21
## Proposal

### Please re-state the problem that we are trying to solve in this issue.

The mention list is not removed immediately after sending a message. The mention list is removed after 2-3 seconds on Android.

### What is the root cause of that problem?

- The function `handleSendMessage` runs in a `worklet` and the logic is wrapped in `runOnJS` which calls an asynchronously callback on the UI thread. 
- `setNativeProps` is used to update immediately the text of the native Android ReactEditText (on iOS UITextView), without a delay of 2-3 seconds. 

### What changes do you think we should make in order to solve the problem?

https://github.com/Expensify/App/blob/1084706b35c2157656ca747374b766083c910061/src/pages/home/report/ReportActionCompose/ReportActionCompose.tsx#L369

In the video below you can see how the mention list disappears with 2-3 seconds of delay, while the RNMarkdownTextInput text disappears immediately.

https://gist.github.com/user-attachments/assets/361eb56e-91ed-40b0-80e1-4ca0eece806d

After commeting setNativeProps, the TextInput text/value and the suggestions disappear together after a delay of 2-3 seconds.

https://gist.github.com/user-attachments/assets/713e99b5-fa35-47b5-9671-4363d0f94712

The solution is using `setNativeProps` to hide the native View responsible for displaying the suggestions on Android/iOS, as it is already done to clear the textinput value/text.

**Comment by fabOnReact** [comment] 2024-07-26 11:14
## Proposal
[Updated](https://github.com/Expensify/App/issues/45485#issuecomment-2252225411)

- added clear implementation steps for the solution
- added information about alternative solutions

**Comment by fabOnReact** [comment] 2024-07-31 02:01
not-overdue @melvin-bot I already have a working solution https://github.com/fabriziobertoglio1987/App/commit/9c473efc9f531b572548bf217a71b16e3a72e2ae.
I'm refactoring the solution to use `React.forwardRef` and `useImperativeHandle`. 

I'll publish the final solution in 1-2 days. Thanks

**Comment by fabOnReact** [comment] 2024-08-01 06:42
I recorded the following tests on Android. I tested web, iOS and did not detect any issues.

- Discard a user mention and send the message (the text `@fab` mention for user `Fabrizio Bertoglio`). 

| Before    | After |
| ----------- | ----------- |
| <img src="https://github.com/user-attachments/assets/38054910-3309-4706-8b58-aaa9b3c5299a" width="350" />      | <img src="https://github.com/user-attachments/assets/225018cf-850c-4f7f-8f0e-05941c885f6e" width="350" />       |

- Discard an emoji and send the message

| Before    | After |
| ----------- | ----------- |
| <img src="https://github.com/user-attachments/assets/8458bcda-eba0-496a-a4df-7900f28e7aa2" width="350" />      | <img src="https://github.com/user-attachments/assets/1c1082f6-9777-4e7f-b551-15e642d99c99" width="350" />       |

**Comment by sakluger** [comment] 2024-08-01 17:07
Not overdue - next step is for @ishpaul777 to test on the test branch.

**Comment by fabOnReact** [comment] 2024-08-02 05:46
> The branch is available [here](https://github.com/Expensify/App/compare/main...fabOnReact:mention-list-slow-to-hide?expand=1). There have been some minor changes with handleSendMessage in the last couple of days.
> 
>     * they started introducing changes to this functionality with commit [0c7af9a](https://github.com/Expensify/App/commit/0c7af9a7bb590560dc41963d54713c2f79bb8d86)
> 
>     * later the changes were reverted (commit [0370382](https://github.com/Expensify/App/commit/0370382b611b3f292e7fa25d7d831550d038a044))
> 
>     * the changes landed again with [60af307](https://github.com/Expensify/App/commit/60af307f768228fd9b95fc406cd5e43b804c0ffd)

The changes have been [reverted](https://github.com/Expensify/App/commit/dc0860655ba44b4e31bddb80278cba02c1226d8a#diff-5c57abefc92160fb4c5d4c7295bb73378c1b61dde425cf0f63b91c5705ea9264R367-R370) again last night.
So there are no changes in the main branch. I rebased the branch based on the latest main, pushed and tested again. Thanks


| Before    | After |
| ----------- | ----------- |
| <video src="https://github.com/user-attachments/assets/6b68c3db-8864-4fcb-8f9c-1d67a504ca31" width="350" />      | <video src="https://github.com/user-attachments/assets/25a65390-7af2-40ac-bf49-9d2a43301118" width="350" />       |

**Comment by sakluger** [comment] 2024-08-07 17:53
Hey @ishpaul777 - based on the Slack thread and [the PR](https://github.com/Expensify/App/pull/45076#issuecomment-2227992831) it's based on, we changed the behavior so that clicking outside the mention list (including clicking on the Send button) will only close the mention list. I tested this in NewDot Web - opening the mention list, and then clicking on the Send button closes the mention list but does not send the message.

It seems like maybe Android wasn't tested for that PR - In the Screenshots/Videos section of the top comment, Android has no screenshots (mWeb Safari is also missing). I think we should definitely align the behavior to that PR. In this scenario, would we ask the original PR author to handle fixing for Android?

**Comment by sakluger** [comment] 2024-08-14 18:50
The PR author (@perunt) is on vacation until Monday. Setting to weekly to keep Melvin happy.

**Comment by perunt** [comment] 2024-08-19 08:44
Hey guys, I'm back. I'll add this to my list and start working on this soon. 
So, I'll take care of the suggestion box disappearing immediately

**Comment by mvtglobally** [comment] 2024-08-23 12:04
Issue not reproducible during KI retests. (First week)

**Comment by perunt** [comment] 2024-08-26 11:19
@ishpaul777  the original issue was that the suggestion didn't hide immediately. However, we later agreed that this was expected behavior. Now, the actual issue is the inconsistent behavior between platforms. Is my understanding correct?
If yes, then I have a fix for that.

**Comment by perunt** [comment] 2024-08-26 14:09
Nice! I made kind of a one-line fix for that. The problem was that the gesture handler was checking if the view was translucent, so to avoid it, I added a transparent color to that view

**Comment by mvtglobally** [comment] 2024-09-09 04:08
Issue not reproducible during KI retests. (Second week)

**Comment by sakluger** [comment] 2024-09-10 21:20
Sorry for the delay in handling payment. @ishpaul777 as far as payment goes, I could use your advice.

While I do think that you (@ishpaul777) are due payment for your review, I don't think any other payment is due here. Android should have been tested and included on the original PR, so I don't think we should pay for the follow-up PR that was created to align the behavior. What do you think?

**Comment by sakluger** [comment] 2024-09-10 22:37
Ah, good call. @ishpaul777 here is the Upwork offer for you: https://www.upwork.com/nx/wm/offer/103906016

**Comment by sakluger** [comment] 2024-09-12 15:58
@ishpaul777 can you let me know once you've accepted the offer?

**Comment by sakluger** [comment] 2024-09-12 18:47
Thanks! All paid.

We already have a regression test for this which is how this was caught. So I think we're fine to close the issue.

**Closed by sakluger** 2024-09-12 18:47 UTC
Labels: External, Daily, Help Wanted, Awaiting Payment, Bug
