### ISSUE TITLE
[C+ Checklist Needs Completion] [$500] Money Request - Deleted IOU in offline mode appears when User switch to online

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#26511] opened 2023-09-01 18:44 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Disable the internet connection on the device
2. Create a money request in a 1:1 conversation
3. Open the IOU details and DELETE the IOU request
4. Enable the internet connection on the device
5. Refresh the app

## Expected Result:
The request should be deleted and the message should be still grayed out in offline mode.
When user switch to online mode the request should remain deleted

## Actual Result:
When user delete the request in offline mode the request should be grayed out, in this case the request disappear
Deleted IOU in offline mode appears when User switch to online

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android / native
- [x] Android / Chrome
- [x] iOS / native
- [x] iOS / Safari
- [x] Windows / Chrome 
- [x] MacOS / Desktop

**Version Number:** 1.3.61-1

**Reproducible in staging?:** Yes

**Reproducible in production?:** Yes

**If this was caught during regression testing, add the test name, ID and link from TestRail:**

**Email or phone of affected tester (no customers):**

**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/78819774/df5a8606-3bc5-4e74-b10c-61ef552cac75

**Expensify/Expensify Issue URL:**

**Issue reported by:** Applause - Internal team

**Slack conversation:**

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01bb43036fdffd3721</li>
        <li>Upwork Job ID: 1698671002276990976</li>
        <li>Last Price Increase: 2023-12-04</li>
<li>Automatic offers: </li>
<ul>
<li>fedirjh | Reviewer | 27991248</li>
<li>rojiphil | Contributor | 27991249</li>
</ul></li>
    </ul>
</details>

**Comment by rojiphil** [comment] 2023-09-02 07:53
I reported this issue in [slack here](https://expensify.slack.com/archives/C049HHMV9SM/p1693399731169779). Can someone please confirm which one was earlier? Thanks.

**Comment by rojiphil** [comment] 2023-09-04 02:24
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
There are two problems that we are trying to solve here. 1) In offline mode, the grayed-out ReportPreview is not shown. 2) When online, the ReportPreview should not be shown.

### What is the root cause of that problem?
The problem occurs because we are not clearing the Report Preview on the deletion of the IOU Report. . Further, `pendingAction` is not set for ReportPreview for Offline support. 

### What changes do you think we should make in order to solve the problem?
1) This can be solved by clearing up the Report Preview when IOU Report is deleted [at this location](https://github.com/Expensify/App/blob/91ff78db32f0284a73db13b2e2372583d71cb27f/src/libs/actions/IOU.js#L1213) within `successData` of `deleteMoneyRequest` method

The changes can be as follows:
```
        ...(shouldDeleteIOUReport
            ? [
                {
                    onyxMethod: Onyx.METHOD.MERGE,
                    key: `${ONYXKEYS.COLLECTION.REPORT_ACTIONS}${chatReport.reportID}`,
                    value: {
                        [reportPreviewAction.reportActionID]: {
                            pendingAction: null,
                            message: [
                                {
                                    type: 'COMMENT',
                                    html: '',
                                    text: '',
                                    isEdited: true,
                                },
                            ],
                            errors: null,
                        },
                    },
                },
              ]
            : []),        
```
2) In addition, we need to support offline mode. For this, we can add the `pendingAction` to `DELETE` as follows [here](https://github.com/Expensify/App/blob/4676492705a96d766fd1f0f1d2e2401cfd5bc566/src/libs/actions/IOU.js#L1120)

```
    let updatedReportPreviewAction = {...reportPreviewAction};
    if(shouldDeleteIOUReport)
    {
        updatedReportPreviewAction.pendingAction = CONST.RED_BRICK_ROAD_PENDING_ACTION.DELETE;
        updatedReportPreviewAction.errors = null;
    }
```

### What alternative solutions did you explore? (Optional)

**Comment by greg-schroeder** [comment] 2023-09-04 12:14
Reviewing

**Comment by rojiphil** [comment] 2023-09-07 16:44
## Proposal

[Updated](https://github.com/Expensify/App/issues/26511#issuecomment-1704524022) with more clarity on root cause. 
@fedirjh Hope the explanation is better now. Please let me know.

**Comment by rojiphil** [comment] 2023-09-11 10:21
> @rojiphil Could you provide more details about problem 1? How does problem 1 relate to the current bug?

@fedirjh I do not think this is dupe as this issue specifically aims to handle the offline case. Please give me some time. I will upload a video to explain this.

**Comment by rojiphil** [comment] 2023-09-11 11:00
a) 
> I noticed you posted the same proposal in the other issue.

Yes, I posted in the other issue as well as both these issues were related although they do not have the same Root Cause. May be, that adds to the confusion too.
Regarding this issue, this is what I think,
Problem 1: Current issue
Problem 2: Partly handled by #26627 which is fixed via Onyx PR fix.

b) 
> Please make sure to include the code for the root cause as well.

Regarding this, I think, the [proposal here](https://github.com/Expensify/App/issues/26511#issuecomment-1704524022) covers the code aspect as well.  Or am I missing something there? Or may be, I should have additionally mentioned that Offline support is currently not there for Report Preview in Chat Report. That is what we are resolving here. 

c) Here is an attached video of solution in offline mode. When offline, we still need to show the Report Preview Action until it becomes online. This is Problem 1.

https://github.com/Expensify/App/assets/3004659/bb3aee70-714e-4bf6-aaed-1c1099e51285

**Comment by greg-schroeder** [comment] 2023-09-12 14:26
Okay. I'm going to put a hold on this for the Onyx [PR](https://github.com/Expensify/react-native-onyx/pull/333) which itself is on hold for https://github.com/Expensify/react-native-onyx/pull/334

**Comment by greg-schroeder** [comment] 2023-10-03 13:40
Same as above

**Comment by greg-schroeder** [comment] 2023-10-12 16:58
""

**Comment by greg-schroeder** [comment] 2023-10-12 17:00
No update yet

**Comment by greg-schroeder** [comment] 2023-10-19 00:40
""

**Comment by rojiphil** [comment] 2023-10-20 08:35
## Proposal

[Updated](https://github.com/Expensify/App/issues/26511#issuecomment-1704524022)

@greg-schroeder  @fedirjh 

The dependent issue #26627 is resolved and closed.
The original proposal is also updated accordingly. 
Also, the problem could be reproduced with the latest main.
Can we take this forward now?

**Comment by greg-schroeder** [comment] 2023-10-23 10:19
Removing hold, ready for @fedirjh to review updated proposals

**Comment by rojiphil** [comment] 2023-10-24 16:56
@fedirjh 
Thanks for sharing the test video. That helped me to understand why you could not reproduce.
In your test, I notice that you already had an existing money request (i.e. of TND 5.00) because of which the IOU Report will not get deleted. 
We will get this problem when a) All the previous money requests are settled & b) There is only one money request left. Now, if we delete the one and only money request, Money Request Preview action in Chat Report will disappear. It is expected to disappear when online. But, when offline, it should show graded out until it comes online. This is the problem.

Here is a test video of the problem. 
<details>
<summary>Staging</summary>

https://github.com/Expensify/App/assets/3004659/3d7affb8-fa27-4956-939a-54a9f7ebc32e

</details>

<details>
<summary>v1.3.90-0.</summary>

https://github.com/Expensify/App/assets/3004659/7555eb6f-ecf3-481a-9efa-2cdde78767c4

</details>

Does this help in reproducing this problem?

**Comment by rojiphil** [comment] 2023-10-24 17:28
> When all the money requests are removed from the IOU report, the report is removed, and it redirects to the parent report. I guess that's expected no?

@fedirjh 
Did you mean `online` or `offline` or `both`?
When `online`, the report preview should disappear which is happening as expected. However, I think the issue mentioned here is that when `offline`, the report preview should not disappear until it comes online.

**Comment by rojiphil** [comment] 2023-10-25 10:46
> I think the mentioned bug is that the preview re-appears after switching online, and that seems to be fixed.

I think that is just one part of the mentioned problem. But, I agree that it is fixed. 

> ## Expected Result:
> The request should be deleted and the message should be still grayed out in offline mode.mode.

However, the other expected result in this issue (as mentioned above) is the one with offline scenario. When offline, I think the pattern is to display some message until it comes online. For example, when a task is canceled, we display `Deleted task` like this

![Screenshot 2023-10-25 at 4 11 24 PM](https://github.com/Expensify/App/assets/3004659/308529c6-97c8-473a-a12b-102ff640fbb3)

> I think addressing the offline feedback style will require a lot of work. Do we really want that?

Not sure what you meant by lot of work. But, one thing I notice is that, with the proposed fix, it was earlier looking like the [test video here](https://github.com/Expensify/App/issues/26511#issuecomment-1713652604). But, now, it looks like this as shown below. Looks like something is broken.

https://github.com/Expensify/App/assets/3004659/18f38a90-8f66-476f-a1ee-23139b157ab3

**Comment by rojiphil** [comment] 2023-10-25 11:37
i.e. Earlier, I use to get this with the proposed fix:
![Screenshot 2023-10-25 at 5 04 49 PM](https://github.com/Expensify/App/assets/3004659/abbcf204-86c0-44ff-97fd-d1085ce79dc0)

But, now, I see this:
![Screenshot 2023-10-25 at 5 03 41 PM](https://github.com/Expensify/App/assets/3004659/b0e3af1d-d5cb-49d4-9130-fa75f4b6353b)

**Comment by rojiphil** [comment] 2023-10-26 13:35
> I think the mentioned bug is that the preview re-appears after switching online, and that seems to be fixed.

I think that is just one part of the mentioned problem. But, I agree that it is fixed. 

>  Expected Result:
> The request should be deleted and the message should be still grayed out in offline mode.

However, the other expected result in this issue (as mentioned above) is the one with the offline scenario. 

When offline, I think the pattern is to display some message until it comes online. For example, when a task is canceled, we display [Deleted task] like this. But, I think, the need for this is not just restricted to offline scenario. Whether online or offline, I think there is another strong reason to display such [Deleted task] as there could be visible actions within the deleted task. In such scenarios, we need to display the [Deleted task] action in chat report with `reply` counts. 
I think the same reasoning applies also for deleted IOU reports.

> I think addressing the offline feedback style will require a lot of work. Do we really want that?

Meanwhile, I do agree that this requires some additional work. 
The work can be broken up like this
1) Implementing the offline support
2) Implementing the [Deleted request] support in the Report Preview
Apart from this, there are improvements required on the LHN side as well which we can take separately or add as improvements here. 

@fedirjh 
But, first, we have to come to a common ground. 
Let me know your thoughts on the above and we can take it up from there.

**Comment by rojiphil** [comment] 2023-10-27 10:42
## Proposal

[Updated](https://github.com/Expensify/App/issues/26511#issuecomment-1704524022) 

@fedirjh 
The proposal is updated based on the comments [here](https://github.com/Expensify/App/issues/26511#issuecomment-1781141610).
Would this be good enough to take this forward?

**Comment by greg-schroeder** [comment] 2023-10-27 16:50
awaiting updating proposal review

**Comment by rojiphil** [comment] 2023-10-30 06:40
> I still think addressing this issue on the front end will require some work

@fedirjh 
Thanks for your detailed feedback. And, you are right. This needs more thinking.
Also, I agree with your concerns between the current and the proposed approach.  
Maybe there is a need to revisit our approach here and there are already existing issues (mentioned in other GH issues) related to current approach. 
Opened up a discussion on slack [here](https://expensify.slack.com/archives/C01GTK53T8Q/p1698647063242239) to know thoughts on related issues as well from a wider audience.

**Comment by greg-schroeder** [comment] 2023-11-01 11:04
Waiting for outcome of slack discussion

**Comment by rojiphil** [comment] 2023-11-02 14:44
@fedirjh 

In the offline scenario here, the concern you mentioned in your [comment here](https://github.com/Expensify/App/issues/26511#issuecomment-1783485227) will not happen as `iouReportID` is set to null during `deleteMoneyRequest` [here](https://github.com/Expensify/App/blob/8088a7bb669162e9004ffd7ad96f0b44ae870742/src/libs/actions/IOU.js#L2106). Further, once all the money requests are deleted, new money requests will not get merged with deleted IOU report. It will create a new IOU report as can be seen [here](https://github.com/Expensify/App/blob/8088a7bb669162e9004ffd7ad96f0b44ae870742/src/libs/actions/IOU.js#L452). Sorry for overlooking the finer details of this.

Regarding inconsistencies revolving around merging money requests, @luacmartins's thoughts are that the inconsistencies will be handled in the BE such that BE will generate a new money request and send it to FE. That way, there will not be any jarring experience in FE. So, if there are any issues arising out of inconsistencies due to the offline scenario, that will get ironed out by BE.   

If there are no more concerns, I think we are good to go here. 
Let me know your thoughts or if you want me to check any other special scenarios I can do that too with my POC here.

@luacmartins Would love to have your inputs here too.

Here is a test video of how it will look after the fix here + the fix of the related [issue here](https://github.com/Expensify/App/issues/30219#issuecomment-1782638616)

https://github.com/Expensify/App/assets/3004659/7a7a885f-7a70-4a3e-979a-c74a388ba2c2

**Comment by luacmartins** [comment] 2023-11-08 17:05
That summary sounds correct to me.

**Comment by greg-schroeder** [comment] 2023-11-09 11:25
Okay got it, thanks @rojiphil - can you confirm you agree @fedirjh?

**Comment by greg-schroeder** [comment] 2023-11-13 09:31
Bump @fedirjh

**Comment by rojiphil** [comment] 2023-11-13 17:16
> What if we send a message inside the IOU report after deleting all the requests inside it ? how the App should behave in that case ? will it display `[Deleted Request]` along with replies count like this one ?

Yes @fedirjh. It behaves like tasks. 
Please have a look at the attached test video that demonstrates this.

https://github.com/Expensify/App/assets/3004659/9ffd0450-7566-42d7-9bd2-dd1d67e75d36

**Comment by rojiphil** [comment] 2023-11-13 17:21
> If So what will happen if we navigate to the "deleted" IOU report and add a new money request inside it ?

Interesting... I just checked it. The BE and FE works like a charm.  
Here is a test video demonstrating that. 
Hopefully, this is what you meant.

https://github.com/Expensify/App/assets/3004659/3735ce30-2915-41db-96c9-97917ba321f8

**Comment by greg-schroeder** [comment] 2023-11-14 19:25
Tricky. I am asking the team to weigh in because it's not obvious to me what we should do

**Comment by trjExpensify** [comment] 2023-11-14 21:19
With "Offline- Pattern B" a UI element that is pending to be deleted should show as a strikethrough until the user comes online. At that point, it gets deleted from the UI or an error message and the RBR gets added if for some reason we couldn't complete the action. 

So there are a few aspects of "Offline Pattern B” to highlight here:

1. Pending create, which shows the UI element greyed out while it’s pending to be created
2. Pending delete, that shows the UI element with a strikethrough while it’s pending to be deleted.
3. When you come back online, if successful, it should be created or deleted depending on the action you took.

**KNOWN IMPROVEMENT:** When you _create something then delete that same thing all while offline_ it can cause a “replay effect" where it disappears, gets re-added, and disappears again as the queued create/delete actions run sequentially. It’s a bit of a downside of the offline design in this edge case, but [there’s an issue for it with other cases](https://github.com/Expensify/App/issues/12775) we’ve seen it. As such, I think that aspect of this issue is out of scope and we should mention it on the main issue looking into that holistically. 

So coming back to what bug we should address here to bring this in-line with Pattern B. I think we should do the following:

**Deleting an existing request offline**
1. Online, create a request
2. Go offline
3. Delete the request
4. The request preview component on the expense/iouReport should show as a strikethrough 
5. It should no longer be clickable to be able to re-access the request details to modify the details while it's pending to be deleted
6. Go online
7. The request preview component on the expense/iouReport should; 
7.a disappear if there are no comments in the request thread to preserve
7.b update and remain in the `[Deleted request]` state if there are comments in the request thread to preserve

**Comment by trjExpensify** [comment] 2023-11-14 22:05
>It describes the money request preview inside the IOU/Expense

Right, it describes the preview of the thing you're deleting. 

>The money request preview works as expected and is similar to how you described it.

Want to show me? It doesn't work as expected in [the steps](https://github.com/Expensify/App/issues/26511#issuecomment-1811328790) on staging:

https://github.com/Expensify/App/assets/16232057/c6fd2d1c-2ea3-4b51-9a7f-50eddec247b5

**Comment by trjExpensify** [comment] 2023-11-14 23:11
Where did this "owes TBD" pattern thing come from for this case? I'd like to read more about that. 

I agree that even if it's the last or only request on an iou/report report, the request preview component inside that report should still show as a strikethrough while it's pending to be deleted. We shouldn't disappear it from the UI until you come back online and that action to delete the request is successful. Equally, the iou/expenseReport preview in the parent report that is now pending to be deleted as well because it's empty should show as a strikethrough as well.

**Comment by trjExpensify** [comment] 2023-11-15 00:29
Yeah, Carlos is out atm, but I think it might just be some kind of cross-polluting with distance requests where the amount can't be calculated yet (perhaps from [here](https://github.com/Expensify/App/pull/29892)) because the distance travelled hasn't been obtained from the server yet until coming back online. 

I don't think we want or should have extended that pattern to "empty" iou/expenseReports at large to display as "X owes TBD". (CC: @JmillsExpensify @mountiny pretty sure this will impact drafts if we don't fix it). 

So I think with your remaining steps should be:

> Go online
> - Delete the report preview without a trace if there are no comments in the iou/expense report to preserve
> - If there are comments on the iou/expense report to preserve, the preview remains as a $0.00 report. (There aren't any other changes to the report view in this case, except for the total(s) showing $0).

**Comment by rojiphil** [comment] 2023-11-15 07:46
Interesting discussion... Thanks for taking this forward. 
Let me try to summarize the problems

**Comment by rojiphil** [comment] 2023-11-15 07:48
Problem 1: When Offline, deleting Money Request in IOU Report removes the money request
1. Go Offline
2. Add Money Request in Chat Report.
3. Go to IOU Report for the Money Request
4. Delete Money Request

**Actual Result**: When offline, Money Request get’s removed in IOU Report. Also, report preview is removed from parent Chat Report 
**Expected Result**: When offline, Money Request should be shown with striked-out amount in IOU Report. Also, Report Preview should be shown


https://github.com/Expensify/App/assets/3004659/2c5181fb-469f-45eb-be97-03b331bac59e

**Comment by rojiphil** [comment] 2023-11-15 07:54
Additionally, I notice one more problem as below.
This also needs to be fixed. Is this correct?

**Problem 3**: When Offline, Report Preview does not update amount when a new Money Request is added
1. Go Offline
2. Add Money Request in Chat Report
3. Go to IOU Report for Money Request
4. Add a message in IOU Report
5. Delete the only Money Request in IOU Report (created in Step 2)
6. Go to parent Chat Report. Verify that Amount 0 is shown.
7. Go to IOU Report again and add a new Money Request
8. Go to parent Chat Report and review Report Preview amount.

**Actual Result**: Report Preview amount is not updated with money request amount of step 7
**Expected Result**: Report Preview amount should be updated with money request amount of step 7


https://github.com/Expensify/App/assets/3004659/46813702-8630-4448-8aed-759a2daa7a4c

**Comment by rojiphil** [comment] 2023-11-15 07:56
@fedirjh 
Can we say that the above three problems form the scope of this issue?

**Comment by rojiphil** [comment] 2023-11-16 13:03
## Proposal

[Updated](https://github.com/Expensify/App/issues/26511#issuecomment-1704524022)

> @rojiphil, could you please provide a new proposal including all the relevant details, along with the analysis of the root cause and proposed solutions for each problem?

@fedirjh 
One more additional issue was noticed while testing. So, that makes it 4 in total.
I have updated the proposal to address each one of the issues as per your comment
Kindly have a look.

**Comment by rojiphil** [comment] 2023-11-21 07:59
> For the second issue, I think we should fix the root cause of the bug. Your proposed solution looks like a patch rather than fixing the root cause. I think it would be better to revise the implementation that was done in #29892 and either fix the root cause of the bug or implement a new one.

@fedirjh 
Agree. Maybe a revised implementation within `TransactionUtils` could help here. I have added Solution 2 for Issue 2 to the [proposal](https://github.com/Expensify/App/issues/26511#issuecomment-1704524022). 
Please have a look at this too when you review the remaining issues.

**Comment by mvtglobally** [comment] 2023-11-23 05:24
Issue not reproducible during KI retests. (First week)

**Comment by greg-schroeder** [comment] 2023-11-26 19:58
can you take a look at the updated proposal @fedirjh? thanks!

**Comment by mvtglobally** [comment] 2023-11-30 06:05
Issue not reproducible during KI retests. (Second week)

**Comment by rojiphil** [comment] 2023-12-01 02:12
@luacmartins @greg-schroeder @mvtglobally 
Based on the comment [here](https://github.com/Expensify/App/issues/26511#issuecomment-1811511971) and [here](https://github.com/Expensify/App/issues/26511#issuecomment-1811608380), I think the issue is still open.
Also, as mentioned [here](https://github.com/Expensify/App/issues/26511#issuecomment-1819266010), @fedirjh has partially reviewed the proposal. 
Currently, we are just waiting for the completion of [proposal](https://github.com/Expensify/App/issues/26511#issuecomment-1704524022) review.

**Comment by luacmartins** [comment] 2023-12-01 16:38
Ah thanks for reminding me of that haha! Reopening!

**Comment by rojiphil** [comment] 2023-12-05 18:01
> For the third issue, I was unable to reproduce it, neither on the development nor staging environments. Could you please attempt to reproduce it on staging ?

@fedirjh 
Thanks for sending the recording as that helped here. The problem only occurs for 1:1 DM Chat Report and not for the Workspace Chat Report. I think, the description of Issue 3  should have covered this aspect. I have updated Issue 3 of the [proposal](https://github.com/Expensify/App/issues/26511#issuecomment-1704524022) to reflect these changes. 
Also, here is the reproduction test video of Issue 3 on staging.

https://github.com/Expensify/App/assets/3004659/2b52b4ed-f26f-4baa-8bfa-8a19a2c754b4

**Comment by rojiphil** [comment] 2023-12-05 19:23
> Regarding the fourth issue, I have successfully reproduced it. Upon investigating the root cause, it appears that we can navigate to the child report from the preview, but clicking on the reply count does not yield the expected result. Could you please provide an explanation as to why it works for the money report preview but not for the reply count?

@fedirjh 
Navigating to the child report from the preview is via `linkedReportID` in Report Preview action which is optimistically set. However, navigating to the child report from reply count is via `childReportID` which is not optimistically set. This is the difference between both of them.  
I have updated Issue 4 in [proposal](https://github.com/Expensify/App/issues/26511#issuecomment-1704524022) to reflect this. 
Please do have a look.

**Comment by blimpich** [comment] 2023-12-07 00:33
Assigned you @rojiphil. Great job on the proposal. It is very detailed and thoughtful. I look forward to reviewing the PR!

**Comment by rojiphil** [comment] 2023-12-09 17:40
@fedirjh 
[PR](https://github.com/Expensify/App/pull/32698) is ready for review.

**Comment by greg-schroeder** [comment] 2023-12-19 01:34
Review still working on the linked PR - @fedirjh thoughts on when you can get that completed?

**Comment by blimpich** [comment] 2023-12-20 21:37
@fedirjh do you have the bandwidth to review the PR?

**Comment by greg-schroeder** [comment] 2024-01-03 20:24
Review continues on linked PR

**Comment by greg-schroeder** [comment] 2024-01-18 10:11
Hmm. Tricky, because this PR was [linked to a deploy blocker](https://github.com/Expensify/App/issues/26511#issuecomment-1885874048), no? So if we did increase the bounty, it would be halved as a result.

**Comment by situchan** [comment] 2024-01-18 10:21
Seems like they're going to get reward for fixing https://github.com/Expensify/App/issues/34263 as separate issue.
So neither increasing bounty nor applying penalty makes sense here.

**Comment by rojiphil** [comment] 2024-01-18 11:28
> because this PR was [linked to a deploy blocker](https://github.com/Expensify/App/issues/26511#issuecomment-1885874048), no?

@greg-schroeder 

That issue was considered a separate issue. Also, we have not discussed any reward there yet. 
So, I have included that too in my comment [here](https://github.com/Expensify/App/issues/26511#issuecomment-1898099565). 
If we want to consider that issue separately, then we have solved 4 issues as part of this issue. 
I think @blimpich can take a call on how to consider this issue.

Regarding the issue itself, I am not sure if we can consider it as a regression because offline support for money requests was introduced only here. It is sort of a new feature. 
Also, the fix for this issue involved code changes due to recent changes in a separate unrelated PR [here](https://github.com/Expensify/App/pull/33041) whereas the code changes as part of this issue stayed the same. 
@fedirjh , @blimpich, please correct me if I am wrong here.

**Comment by greg-schroeder** [comment] 2024-01-18 17:09
Okay. I mean what is the proposed bounty increase in the first place? Someone suggested we raise it at some point in the past but I don't think we ever got to a number.

**Comment by blimpich** [comment] 2024-01-18 18:20
Lets do $1000 for the whole thing, including https://github.com/Expensify/App/issues/34263, and not apply any penalty to this issue. @rojiphil I really appreciate the attention to detail and professionalism, and I agree this deserves more of a reward than a normal issue 🙂. And in the future we can make sure we increase the bounty before you put up your PR, so that you can know what you're going to get paid before working on an issue.

**Comment by greg-schroeder** [comment] 2024-01-18 18:25
Paid $1k to both C and C+

**Comment by greg-schroeder** [comment] 2024-01-18 18:25
@fedirjh just need to complete the checklist above and we're good to go!

**Comment by greg-schroeder** [comment] 2024-01-22 16:49
Bump @fedirjh :)

**Comment by greg-schroeder** [comment] 2024-01-25 20:19
Thanks! Added regression test and closing.

**Closed by greg-schroeder** 2024-01-25 20:19 UTC
Labels: External, Daily, Bug
