### ISSUE TITLE
[HOLD for payment 2024-01-17] [$500]  Android - Request money - Currency list flashes briefly when opening currency list

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#29780] opened 2023-10-17 14:28 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.3.85-0

**Reproducible in staging?:** Yes

**Reproducible in production?:** Yes

**If this was caught during regression testing, add the test name, ID and link from TestRail:**

**Email or phone of affected tester (no customers):**

**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Expensify/Expensify Issue URL:**

**Issue reported by:** Applause - Internal Team

**Slack conversation:**

## Action Performed:
1. Go to staging.new.expensify.com
2. Go to + > Request money > Manual
3. Tap on the currency

## Expected Result:
The currency list will not flash

## Actual Result:
The currency list flashes briefly

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [ ] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos
<details>
<summary>Android: Native</summary>

 

https://github.com/Expensify/App/assets/78819774/583c5ad7-b5de-49ef-a380-5b9956c4fdc9

</details>

<details>
<summary>Android: mWeb Chrome</summary>

</details>

<details>
<summary>iOS: Native</summary>

</details>

<details>
<summary>iOS: mWeb Safari</summary>

</details>

<details>
<summary>MacOS: Chrome / Safari</summary>

</details>

<details>
<summary>MacOS: Desktop</summary>

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01937182f6afc52c43</li>
        <li>Upwork Job ID: 1714287345950720000</li>
        <li>Last Price Increase: 2023-10-31</li>
<li>Automatic offers: </li>
<ul>
<li>fedirjh | Reviewer | 27488223</li>
</ul></li>
    </ul>
</details>

**Comment by abekkala** [comment] 2023-10-20 19:52
I'll give this another day-2 for proposals and I'll bring to CS or SWM

**Comment by vladimir-8** [comment] 2023-10-23 23:16
I cannot reproduce it on the latest build from `main` on Android 13. @lanitochka17 Which phone/android version did you test it with?
https://github.com/Expensify/App/assets/70273239/6fedb940-b3eb-4b1c-8dcd-d927c5d4951b

**Comment by vladimir-8** [comment] 2023-10-23 23:25
Contributor details
Your Expensify account email: vladim8r@gmail.com
Upwork Profile Link: https://www.upwork.com/freelancers/~013f725105078cfc87

**Comment by lanitochka17** [comment] 2023-10-26 16:19
Issue reproducible on build 1.3.91-6
Samsung Galaxy A50/Android11


https://github.com/Expensify/App/assets/78819774/bc0af38c-9513-468b-87b9-d48503a1d699

**Comment by abekkala** [comment] 2023-10-31 16:09
https://expensify.slack.com/archives/C03UK30EA1Z/p1698768517241339
Reached out for someone to take this one on

**Comment by barttom** [comment] 2023-11-02 11:17
Hi! I'm Bartek from Callstack and would to work on it. I'm gonna debug that and back to You with the proposal when ASAP :)

**Comment by barttom** [comment] 2023-11-03 13:31
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
After navigating to the currency selection screen, we can see a visible blinking of the list of currencies.
### What is the root cause of that problem?
This issue occurs when we have selected currency not from the first 12 results (this is an initial number of rendered elements). It happens, because of the specific of SelectionList.
We use that component in https://github.com/Expensify/App/blob/main/src/components/SelectionList/BaseSelectionList.js#L437
It flashes because those results haven't been loaded yet
### What changes do you think we should make in order to solve the problem?

Add prop to the SectionList that init selected index
`initialScrollIndex={focusedIndex}`
### What alternative solutions did you explore? (Optional)
N/A

**Comment by barttom** [comment] 2023-11-06 09:34
@fedirjh This is not implementing a new prop, this is just using one of property from SectionList, an RN component; it's a part of `VirtualizedListWithoutRenderItemProps` interface.

Looks like we don't need to implement scrolling on the initial render because we can use this build prop.
Thanks for bringing my attention this callback, looks like we can remove it and use the SelectionList prop.

`Also in the root cause you mentioned that results haven't been loaded yet, how will we calculate initialScrollIndex if we don't have any data yet?`
SectionList renders only visible elements, so I think the blink is because it needs to unmount the first elements and mount a group with a particular index. 
The `scrollToLocation` method needs the index to scroll to, and it requires a defined `getItemLayout` - so that's how it works and recognize scroll posittion
By 'loaded' I meant rendered, not if data exists.


What do You think now, can I go with this solution?

**Comment by barttom** [comment] 2023-11-06 09:40
[Proposal](https://github.com/Expensify/App/issues/29780#issuecomment-1792442802) updated

**Comment by deetergp** [comment] 2023-11-08 21:49
Apologies for the late review, I've still catching up from being ooo. We're a little premature on submitting the PR before it's approved 😅 Fortunately, I agree with @fedirjh that @barttom's proposal is good 👍

**Comment by barttom** [comment] 2023-11-15 07:12
@fedirjh Sure, I Will try to check this today, at least tomorrow. Should I send a  proposal here on in regrsions issue?

**Comment by barttom** [comment] 2023-11-16 17:45
I still working on it. 
Looks like this is the standard behavior of FlatList when we pass the initial scroll index for a short list. 
I'm looking for the best solution for this.

**Comment by abekkala** [comment] 2023-11-21 18:20
Not deployed to Prod yet
https://github.com/Expensify/App/pull/31262#issuecomment-1813263512

**Comment by barttom** [comment] 2023-11-21 18:31
yup, this was reverted couse regression. Working on new solution

**Comment by abekkala** [comment] 2023-11-22 21:47
I'm heading out for the Thanksgiving holiday and will be back bright and early Monday morning.

**Comment by barttom** [comment] 2023-11-23 07:22
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
After navigating to the currency selection screen, we can see a visible blinking of the list of currencies.
### What is the root cause of that problem?
This issue occurs when we have selected currency not from the first 12 results (this is an initial number of rendered elements). It happens, because of specific of SelectionList. We use that component in https://github.com/Expensify/App/blob/main/src/components/SelectionList/BaseSelectionList.js#L439 It flashes, because those results weren’t yet loaded .

SectionList renders only visible elements, so it needs to unmount the first elements and mount a group with a particular index.
### What changes do you think we should make in order to solve the problem?

Hide render until we scroll to the focused element while first rendering by style.

https://github.com/Expensify/App/blob/main/src/components/SelectionList/BaseSelectionList.js#L381

1. Create s state flag that has been changed after first render, e.g. `isInitialRender`
2. Use this flag to set the opacity for the whole container <br>
`<View style={[styles.flex1, {opacity: isInitialRender ? 0 : 1}, !isKeyboardShown && safeAreaPaddingBottomStyle]}>`

This solution allows to rendering list and trigger `scrollToLocation` for SectionList instance and hides blinking effect.
### What alternative solutions did you explore? (Optional)
Remove implementation of `scrollToFocusedIndexOnFirstRender` and use a build prop in the SectionList that init selected index.

`<SectionList
initialScrollIndex={focusedIndex}
/>`

HOWEVER, implementing that can be more complicated as I thought.
Using this prop triggers scrolling also on short lists that items fit to the screen, what can generate issues like https://github.com/Expensify/App/issues/31192

To avoid that, we need to calculate if items fit to the screen, then in positive case set `initialScrollIndex` as undefined.

That requires refactoring and probably split render `SectionList` from `BseSelectionList`component. Still not sure if any other corner cases didn’t shows.<br><br><br>

**Comment by barttom** [comment] 2023-11-29 07:43
So do You want to keep both solutions? 
I think when we use `initialScrollIndex` also have a blank screen for a while in case when we initiate an index besides first 12 items.
I think it can be confusing for developers why sometimes we use a `initialScrollIndex` and sometimes we scroll when onLayout recent has been triggered. I know it looks hacky, but sometimes solutions like that are needed. Just hide the screen and allow render view with some calculations on the background

Looks like both solutions are kinda of tradeoffs :) Let me know which one do You prefer and I'll implement it

**Comment by barttom** [comment] 2023-11-30 07:25
@fedirjh please take a look on my previous comment :)

**Comment by deetergp** [comment] 2023-12-07 00:42
@fedirjh The delay seems acceptable to me, If you agree, then we will go with @barttom's [proposal](https://github.com/Expensify/App/issues/29780#issuecomment-1823910887).

**Comment by abekkala** [comment] 2023-12-19 20:46
@conorpendergrast 

### STATUS:
I'm going ooo 

PR was merged to prod 5 days ago (Dec 14)
Payment date will be **Dec 21**


- Issue reported by: Applause - Internal Team
- Fix: @barttom [$500, if no regressions]
- PR Review: @fedirjh [$500, if no regressions]

**Comment by conorpendergrast** [comment] 2023-12-19 20:48
Love the write-up April, merry Christmas and happy new year

**Comment by situchan** [comment] 2023-12-19 20:56
Coming from https://github.com/Expensify/App/issues/22508#issuecomment-1858871846:

> The issue with the skeleton loader not showing is the recent regression from https://github.com/Expensify/App/issues/29780.

@bernhardoj is this correct?

**Comment by situchan** [comment] 2023-12-20 10:51
I think we should handle [this regression](https://github.com/Expensify/App/pull/32777#issuecomment-1858873147) here as it's still within regression period.
cc: @barttom

**Comment by barttom** [comment] 2023-12-20 13:32
Sorry, didn't notice messages before. I'll try to investigate it tomorrow.

**Comment by barttom** [comment] 2023-12-21 14:20
So the problem is that `isInitialRender` will be changed after SectionList will be rendered. When we don't have date - we stick with opacity set to zero.


https://github.com/Expensify/App/assets/7682108/4068cd57-249a-45e9-a5c9-0b2aafe96986



Because of That, I propose wrapping only SectionList in the view and passing prepared styles there. In the 
current wrapper we have another conditional rendered components that weren't a part of the issue.



@fedirjh what do you think?

**Comment by abekkala** [comment] 2024-01-17 19:09
**Issue reported by:** Applause - Internal Team
**Fix:** @barttom does not require payment (Callstack)
**PR Review:** @fedirjh [offer](https://www.upwork.com/nx/wm/offer/27488223) 

@fedirjh can you complete the checklist above, I can then process payment in Upwork

**Comment by abekkala** [comment] 2024-01-24 13:38
@fedirjh payment sent and contract ended - thank you! 🎉

**Closed** 2024-01-24 13:38 UTC
Labels: External, Engineering, Weekly, Awaiting Payment, Bug
