### ISSUE TITLE
[HOLD] [$1000] Display name changes to email in 'owes you' message after changing default contact method

### ISSUE THREAD

**Issue by kavimuru** [Expensify/App#19316] opened 2023-05-19 20:10 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:

1. Open account A on new dot and make sure that account A has a display name
2. Go to settings > Profile > Contact method > New contact method
3. Add the new contact method and verify it
4. Change the default contact method to the newly added contact method
5. Notice the change in LHN

## Expected Result:
The message "[account A's display name] owes you ... " should not change and should still use the display name in the message. The avatar of account B should not change to default avatar.
## Actual Result:
The display name changes to an email in the "owes you" message. And the avatar of account B changes to default avatar.

## Workaround:
Can the user still use Expensify without this being fixed? Have you informed them of the workaround?

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [x] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 1.3.16.5
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/43996225/beb13a2b-7368-4af9-b95d-7fccffe45dc4

https://github.com/Expensify/App/assets/43996225/50bbfa03-9403-45ea-9c8e-a2f2bb12d011

**Expensify/Expensify Issue URL:**
**Issue reported by:** @nathan-mulugeta
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1684314699362689

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~0185aedfcd8cb74cf6</li>
        <li>Upwork Job ID: 1661420571303399424</li>
        <li>Last Price Increase: 2023-06-07</li>
    </ul>
</details>

**Comment by dukenv0307** [comment] 2023-05-23 09:24
## Proposal

### Please re-state the problem that we are trying to solve in this issue.

After change the default contact method to the newly added contact method, the message "[account A's display name] owes you ... " should not change and should still use the display name in the message. The avatar of account B should not change to default avatar.


### What is the root cause of that problem?

If you change the default contact, api `SetContactMethodAsDefault` will be called and set `personalDetails` in `ONYX` with new default email. But `report.login` haven't been updated yet and in `ReportUtils.js` function `getPersonalDetailsForLogin` will return default case.

https://github.com/Expensify/App/blob/6946beb6219c87df11cc8f81bb6c31ed8e732373/src/libs/ReportUtils.js#L915-L927


### What changes do you think we should make in order to solve the problem?

Here is my suggestion to do it:
1. In `ReportUtils.js` subscribe `loginList` from ONYX
2. In function `getPersonalDetailsForLogin`, we can change personalDetails if `allPersonalDetails` not include `report.login` and `loginList` include `report.login`
```
    let personalDetails;
    if(loginList[login] && !allPersonalDetails[login]){
        _.keys(loginList).forEach((temp)=>{
            if(allPersonalDetails && _.keys(allPersonalDetails).includes(temp))  personalDetails = allPersonalDetails[temp]; 
     })
    return personalDetails;
    }
```


### What alternative solutions did you explore? (Optional)

**Comment by stephanieelliott** [comment] 2023-05-24 17:16
Looks like we already have a proposal for review @0xmiroslav

**Comment by abekkala** [comment] 2023-05-24 17:19
@stephanieelliott do I need stay assigned here? looks like I'm the second one due to the external label??

**Comment by stephanieelliott** [comment] 2023-05-24 17:25
No, I don't think so @abekkala. Not sure what happened there, I thought "did April become an engineer???". Anyway, I will remove your assignment!

**Comment by joelbettner** [comment] 2023-05-29 16:30
@0xmiroslav Have you had a chance to look at the proposal?

**Comment by stephanieelliott** [comment] 2023-05-30 19:13
Bump @0xmiroslav, can you give [this proposal](https://github.com/Expensify/App/issues/19316#issuecomment-1558893907) a review?

**Comment by stephanieelliott** [comment] 2023-06-01 18:41
> I think @Beamanator has more context on this type of bug after changing default contact method.
Is there any upcoming plan or should we fix this issue here?

Hm, good question -- hey @Beamanator do you know anything about this bug, or are we're fixing it elsewhere?

**Comment by stephanieelliott** [comment] 2023-06-05 18:39
I think this _might_ belong under https://github.com/Expensify/App/issues/16666? Bumped @Beamanator in DM to be sure

**Comment by Beamanator** [comment] 2023-06-06 20:46
Sorry for the delay, was focusing on some other priorities :D

Hmm this does seem like a back-end issue (I could be wrong) but I bet the personal detail showing in the LHN isn't coming directly from `personalDetails` but maybe from the reportAction or something? In that case i believeeee we may need to be updating the backend for this change.

Anyway, "is this being updated elsewhere"? I thinkkkkk this is the same problem as https://github.com/Expensify/App/issues/18575 but haven't done any investigation on exactly the root cause of this issue

**Comment by stephanieelliott** [comment] 2023-06-07 15:53
Oh, yeah it seems likely that the two are related. On the status of https://github.com/Expensify/App/issues/18575:

> We're going to keep this issue ON HOLD until https://github.com/Expensify/Expensify/issues/280523 moves forward, because in that project we plan to hide a lot of personal contact info in the App so you can't scrape it, and we'll re-key personal details by accountID. So this should help us solve this issue 👍

Shall we put this one on hold as well, and see if https://github.com/Expensify/App/issues/18575 fixes it? This display name issue seems like it could cause minor confusion at worst... given that we're planning to make changes to personal contact info in the app anyway it doesn't make a lot of sense to implement what may be a temporary solution.

**Comment by stephanieelliott** [comment] 2023-06-10 01:30
Putting this on a hold per https://github.com/Expensify/App/issues/19316#issuecomment-1581107053.

**Comment by stephanieelliott** [comment] 2023-07-05 19:53
Master issue still on hold, added this to the list of followup issues there

**Comment by stephanieelliott** [comment] 2023-08-04 06:15
Master issue still on hold

**Comment by stephanieelliott** [comment] 2023-08-22 15:41
Master issue still on hold

**Comment by joelbettner** [comment] 2023-09-28 03:21
@stephanieelliott @0xmiroslav @kavimuru does this bug still exist? I know there have been a lot of updates made recently.

**Comment by Nathan-Mulugeta** [comment] 2023-09-28 06:10
I just retested this and this issue is no longer reproducible.

**Comment by stephanieelliott** [comment] 2023-10-11 04:43
I'm not able to repro either, closing!

**Closed by stephanieelliott** 2023-10-11 04:43 UTC
Labels: External, Monthly, Help Wanted, Bug
