### ISSUE TITLE
Chat - After marking a message as unread, sending a new message causes the chat to scroll up

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#42100] opened 2024-05-13 19:10 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.73-1
**Reproducible in staging?:** Y
**Reproducible in production?:** N
**If this was caught during regression testing, add the test name, ID and link from TestRail:** https://expensify.testrail.io/index.php?/tests/view/4555724&group_by=cases:section_id&group_order=asc&group_id=296775
**Email or phone of affected tester (no customers):** shussain+safari1@applausemail.com
**Issue reported by:** Applause - Internal Team

## Action Performed:
1. Open a chat
2. Mark a message as Unread
3. Send a message

## Expected Result:
After marking a message as unread, sending a new message should not cause the chat to scroll up it should maintain the current position

## Actual Result:
After marking a message as unread, sending a new message causes the chat to scroll up

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details> 

https://github.com/Expensify/App/assets/78819774/f4f92185-2d27-46b8-bbaf-9fac19c34047

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by lanitochka17** [comment] 2024-05-13 19:11
@tylerkaraszewski  FYI I haven't added the External label as I wasn't 100% sure about this issue. Please take a look and add the label if you agree it's a bug and can be handled by external contributors

**Comment by lanitochka17** [comment] 2024-05-13 19:12
We think that this bug might be related to #vip-vsp

**Comment by bondydaa** [comment] 2024-05-14 18:36
sounds like this is not related to the API so removing the web deploy blocker label, this should also hep us figure out if it was your PR (or another app PR) or not.

**Comment by ikevin127** [comment] 2024-05-14 18:43
I confirm it's caused by my PR. Will open a follow-up PR today with the fix.

**Comment by Beamanator** [comment] 2024-05-14 19:36
Revert PR merged, requesting CP 🙏

**Comment by tylerkaraszewski** [comment] 2024-05-14 21:55
I don't see a CP request in #deployer @Beamanator ?

**Comment by yuwenmemon** [comment] 2024-05-14 22:10
This has been fixed here: https://github.com/Expensify/App/pull/42167#issuecomment-2111203635

**Comment by Beamanator** [comment] 2024-05-15 09:43
Fixed, so closing 👍  This issue has been linked in https://github.com/Expensify/App/issues/35011, the original implementation PR, so we know to fix this bug in the next PR 👍

**Closed by Beamanator** 2024-05-15 09:43 UTC
Labels: Reviewing, Engineering, Weekly
