### ISSUE TITLE
#wave-collect - [Hold on 378314][Held requests] Confirmation to pay is still shown after approving all the requests

### ISSUE THREAD

**Issue by izarutskaya** [Expensify/App#39336] opened 2024-03-31 20:44 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.58-4
**Reproducible in staging?:** Y
**Reproducible in production?:** N
**Found when validating PR:** https://github.com/Expensify/App/pull/33124
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Issue reported by:** Applause-Internal team

## Action Performed:
Precondition:
- Admin and employee are in the Collect workspace.

1. [Employee] Request money from the workspace chat.
2. [Employee] Create two money requests.
3. [Employee] Hold one of the requests and leave the other one unheld.
4. [Admin] Go to expense report.
5. [Admin] Click Approve button.
5. [Admin] Approve all the request.
6. [Admin] Click Pay with Expensify.
7. [Admin] Click on the preview of the request that was previously held.
8. [Admin] Return to expense report.
9. [Admin] Click Pay with Expensify.

## Expected Result:
In Step 6, after approving all the requests, and when the request on hold is unheld, paying with Expensify will not show confirmation prompt.

## Actual Result:
In Step 6, after approving all the requests, and when the request on hold is unheld, paying with Expensify shows confirmation prompt, with both options showing the same total amount.
When admin visits transaction thread and returns to expense report, clicking on Pay with Expensify button does not show the prompt anymore.

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [x] Android: mWeb Chrome
- [x] iOS: Native
- [x] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

https://github.com/Expensify/App/assets/115492554/843fc13d-568d-4fb6-aa6c-1dd129b511a5

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by izarutskaya** [comment] 2024-03-31 20:44
@sakluger I haven't added the External label as I wasn't 100% sure about this issue. Please take a look and add the label if you agree it's a bug and can be handled by external contributors.

**Comment by izarutskaya** [comment] 2024-03-31 20:44
We think this issue might be related to the #collect project.

**Comment by izarutskaya** [comment] 2024-03-31 20:45
Production 

![image (6)](https://github.com/Expensify/App/assets/115492554/6a44331b-b9ba-46ca-b823-5a57436249b5)

**Comment by tgolen** [comment] 2024-04-01 15:58
@BartoszGrajdek Is this a regression of https://github.com/Expensify/App/pull/33124 ?

**Comment by robertjchen** [comment] 2024-04-01 18:14
It's related to the changes there: https://github.com/Expensify/App/pull/33124 and we'll be addressing it. Not a deploy blocker per the [sentiments](https://expensify.slack.com/archives/C036QM0SLJK/p1711507708986889?thread_ts=1711403751.963269&cid=C036QM0SLJK) here 👍

**Comment by marcaaron** [comment] 2024-04-01 21:00
Removing the blocker.

**Comment by tgolen** [comment] 2024-04-03 14:40
@robertjchen I'm going to assign this to you since you are watching over the PR and handling the regressions. Thank you!

**Comment by robertjchen** [comment] 2024-04-08 06:39
Held, pending further fixes in https://github.com/Expensify/Expensify/issues/378314

**Comment by sakluger** [comment] 2024-04-15 16:27
I'm going to switch this to weekly until that other issue is deployed.

**Comment by robertjchen** [comment] 2024-04-26 02:42
More related fixes went out, going to re-test

**Comment by trjExpensify** [comment] 2024-05-07 12:46
Did you re-test, @robertjchen?

**Comment by sakluger** [comment] 2024-05-08 00:26
@robertjchen friendly bump.

**Comment by robertjchen** [comment] 2024-05-08 17:46
Haven't had the chance given ongoing priorities. Let me tag with `retest-weekly` to get an additional assist.

**Comment by sakluger** [comment] 2024-05-16 20:20
@jliexpensify assigning you to help watch this issue while I'm OOO through May 31. Please handle payment if needed. I'll take back over if it's still open when I return. Nothing much to do on this one.

**Comment by mvtglobally** [comment] 2024-05-17 12:24
Issue is not reproducible during KI retests (First week) 
https://github.com/Expensify/App/assets/43995119/4d5f5e67-642b-43e7-8ef3-45cf84e0cc57

**Comment by mvtglobally** [comment] 2024-05-22 04:41
Issue not reproducible during KI retests. (Second week)

**Comment by robertjchen** [comment] 2024-05-22 05:48
Thanks, we can close this one out 👍

**Closed by robertjchen** 2024-05-22 05:48 UTC
Labels: Engineering, Weekly, Bug, retest-weekly
