### ISSUE TITLE
[HOLD][$500] Chat - Latest chat user is not showing in recent on Start chat screen

### ISSUE THREAD

**Issue by izarutskaya** [Expensify/App#31397] opened 2023-11-15 18:37 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.3.99-0
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** Applause-Internal Team
**Slack conversation:** @

## Action Performed:
1. Navigate to staging.new.expensify.com
2. Go to FAB> Start chat
3. Add e-mail and send a message to conversation
4. Go back to home page
5. Go to FAB> Start chat

## Expected Result:
Latest chat should appear on the top of suggestion list

## Actual Result:
Latest chat with user is not showing in recent on Start chat screen

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [x] Android: mWeb Chrome
- [x] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

https://github.com/Expensify/App/assets/115492554/d58bbc6f-0e91-4ccc-890c-0ed9ff903469

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~019fd53c186025d25b</li>
        <li>Upwork Job ID: 1724859146766970880</li>
        <li>Last Price Increase: 2023-11-15</li>
<li>Automatic offers: </li>
<ul>
<li>DylanDylann | Contributor | 27775244</li>
</ul></li>
    </ul>
</details>

**Comment by manlaig** [comment] 2023-11-15 19:44
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
Latest chat user is not visible under chat suggestions

### What is the root cause of that problem?

The `reportOption.login` field is null or undefined on some users, those users are skipped along with workspaces in this condition:

https://github.com/Expensify/App/blob/1ca499cd0da6ef02270b91f0a4bc02d46a0a5e34/src/libs/OptionsListUtils.js#L1229-L1231

### What changes do you think we should make in order to solve the problem?

Need to change the above condition to check for `reportOption.accountID` field instead of checking for `reportOption.login` to filter users.
So, the above condition would change to:
```
if (!isCurrentUserOwnedPolicyExpenseChatThatCouldShow && !includeMultipleParticipantReports && !reportOption.accountID)
{
       continue;
}
```

This happened to one of my accounts and making this change fixed the issue for me.

### What alternative solutions did you explore? (Optional)

**Comment by manlaig** [comment] 2023-11-15 19:53
Updated [proposal](https://github.com/Expensify/App/issues/31397#issuecomment-1813159797) to include a screen recording

**Comment by manlaig** [comment] 2023-11-15 19:59
Updated [proposal](https://github.com/Expensify/App/issues/31397#issuecomment-1813159797) to make small adjustments to the wording.

**Comment by manlaig** [comment] 2023-11-15 20:11
Updated [proposal](https://github.com/Expensify/App/issues/31397#issuecomment-1813159797) to add an example of the bug.

**Comment by paultsimura** [comment] 2023-11-16 08:53
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
Some users are missing from the "Recents" section when starting a chat.

### What is the root cause of that problem?
When building the options list, we filter out the reports where the account has missing `login`:

https://github.com/Expensify/App/blob/629c6de7f2d23e49b6ff6c460c7bf8f87f68b70a/src/libs/OptionsListUtils.js#L1228-L1231

Some users from 1:1 chats have missing login data, so they are filtered out here as well, even though they are 1:1 chats, not multiple ones.

### What changes do you think we should make in order to solve the problem?

**First,** we should change this condition to use `accountID` instead of `login`:

```js
            if (!isCurrentUserOwnedPolicyExpenseChatThatCouldShow && !includeMultipleParticipantReports && !(reportOption.accountID || reportOption.login)) {
                continue;
            }
```

**Second**, if we change only this condition, the options will appear in the list, but they will **navigate to incorrect reports** because we use the following logic when clicking on the option:

https://github.com/Expensify/App/blob/1f3eca319dd5565504784fd462e42f3794b34a54/src/pages/NewChatPage.js#L158-L166

Therefore, we should change this logic to the following:

```js
    function createChat(option) {
        if (!option.login) {
            Report.navigateToAndOpenReportWithAccountIDs([option.accountID]);
        }

        Report.navigateToAndOpenReport([option.login]);
    }
```

### What alternative solutions did you explore? (Optional)

**Comment by DylanDylann** [comment] 2023-11-20 08:55
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
Chat - Latest chat user is not showing in recent on Start chat screen

### What is the root cause of that problem?
When A starts a new chat with B (The account B doesn't already exist), the login field in personal detail will be null. Only when account B is created and replies to a new message to account A, personal details in account A will be updated. It makes account B isn't displayed on the Start chat Page because this logic
https://github.com/Expensify/App/blob/629c6de7f2d23e49b6ff6c460c7bf8f87f68b70a/src/libs/OptionsListUtils.js#L1229


### What changes do you think we should make in order to solve the problem?
https://github.com/Expensify/App/blob/629c6de7f2d23e49b6ff6c460c7bf8f87f68b70a/src/libs/OptionsListUtils.js#L1229
Here we should update to use accountID field instead of login field because in the multiple participant chat accountID always be '0'

When doing that, we accept to display options that don't have a login field on Start Chat Page. So that we also update some logics in Start Chat Page

https://github.com/Expensify/App/blob/ff4c947da6d5a710bb6c55b973284c13be306f75/src/pages/NewChatPage.js#L119
In this function we should use accountID instead of login field to check condition

IN here
https://github.com/Expensify/App/blob/ff4c947da6d5a710bb6c55b973284c13be306f75/src/pages/NewChatPage.js#L165


we should check to use`Navigation.dismissModal(option.reportID);` field instead of login field like we did in Search Page 
https://github.com/Expensify/App/blob/ff4c947da6d5a710bb6c55b973284c13be306f75/src/pages/SearchPage.js#L161-L171


One more place 
https://github.com/Expensify/App/blob/ff4c947da6d5a710bb6c55b973284c13be306f75/src/pages/NewChatPage.js#L173
We should check if login is null/underfined we can use option.text or using accountIDs instead of
### What alternative solutions did you explore? (Optional)

**Comment by amyevans** [comment] 2023-11-21 20:39
Just a heads up I'll be OOO the remainder of the week, if a PR is ready before then, I'll review it next Monday or Tuesday. Thanks!

**Comment by DylanDylann** [comment] 2023-11-23 08:50
<img width="1440" alt="Screenshot 2023-11-23 at 15 47 15" src="https://github.com/Expensify/App/assets/141406735/70ba7500-71af-4972-a017-32982527fc1f">

One more thing, we will display "Hidden" as display name as decision [here](
https://github.com/Expensify/App/issues/27393)

**Comment by allroundexperts** [comment] 2023-11-26 20:30
I guess @amyevans would answer [this](https://github.com/Expensify/App/issues/31397#issuecomment-1824000045) better.

**Comment by amyevans** [comment] 2023-11-27 17:32
> As expected in OP, when A starts a new chat with B (The account B doesn't already exist), we will display the user B on the Start Chat Page. Do you want do the same thing in the other page (that don't include multipe participant chat) like RoomInvitePage, WorkSpaceInvitePage, TaskAssigneeSelectorModal, MoneyRequestParticipantsSelector

Hmm, to be honest I'm not sure of expected behavior on this one, and also given that `Hidden` will be displayed per your comment [here](https://github.com/Expensify/App/issues/31397#issuecomment-1824009217) I am second guessing if it makes sense to display User B in the Start Chat Page either, as I think it's potentially confusing for User A.

I know the logic that goes into which users are "known" is complex, so wondering if these questions have already been discussed or if @puneetlath has an opinion here on expected behavior.

**Comment by DylanDylann** [comment] 2023-11-29 09:35
@puneetlath Could you help to check above comment: https://github.com/Expensify/App/issues/31397#issuecomment-1828306858 ?

**Comment by amyevans** [comment] 2023-12-06 02:31
Coming back to this, I think that because `Hidden` will be displayed, it really is not adding any value, so we shouldn't ship this change yet.

There's been some internal discussion though to consider accountA as knowing accountB if accountA invited accountB (https://github.com/Expensify/Expensify/issues/342920), so let's wait until that's implemented and then we can move forward here.

**Comment by amyevans** [comment] 2023-12-15 15:05
https://github.com/Expensify/Expensify/issues/342920 is closed so I retested and can no longer repro:

https://github.com/Expensify/App/assets/7277067/9f01a251-5683-4515-a33f-4e4d87d46518

I think we can close this but feel free to reopen if you disagree @muttmuure

**Closed by amyevans** 2023-12-15 15:05 UTC
Labels: External, Weekly, Overdue, Bug

**Comment by DylanDylann** [comment] 2023-12-18 07:34
@amyevans @muttmuure Should we process payment for this issue? Since this issue already been assigned to contributors and we spent lots of effort on this issue to propose a solution and create a draft PR

**Comment by DylanDylann** [comment] 2024-01-09 04:39
@amyevans @muttmuure Could you help to check the above comment?

**Comment by muttmuure** [comment] 2024-01-11 11:21
Yeah I think that sounds fair enough

**Comment by muttmuure** [comment] 2024-01-11 11:28
@DylanDylann I've sent you an offer on Upwork

**Comment by muttmuure** [comment] 2024-01-11 11:28
$500 - @allroundexperts for C+

**Comment by DylanDylann** [comment] 2024-01-11 11:59
@muttmuure Thanks, I accepted

**Comment by JmillsExpensify** [comment] 2024-01-30 22:18
$500 payment approved for @allroundexperts based on [this comment](https://github.com/Expensify/App/issues/31397#issuecomment-1886940901).
