### ISSUE TITLE
[Ready for payment][$250] No response when clicking back button and link on not found page

### ISSUE THREAD

**Issue by m-natarajan** [Expensify/App#48761] opened 2024-09-07 11:15 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 9.0.30-15
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** @dukenv0307 
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1725706526160129

## Action Performed:
1. Create a new workspace
2. Navigate to Workspace Settings > More Features > Enable Report Field.
3. In Report Field, add a field, name it, choose a type, and save.
4. Go to Workspace Chat > Click the plus sign > Submit Expense > Add amount, merchant, and submit.
5. In Expense report, click on the custom report fields
6. Edit field id on router and press enter
7. Notice that page not found is displayed
8. Try to click back button and link on this page
## Expected Result:
Can click the back button and link to go back.
## Actual Result:
Can't click the back button and link to go back.
## Workaround:
Unknown
## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

https://github.com/user-attachments/assets/7df94954-4c6f-4e80-8333-a18c023baab5

https://github.com/user-attachments/assets/a6c99ba3-db1c-4854-b7f5-40d3842e9ec0

Add any screenshot/video evidence

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~021832973509277607149</li>
        <li>Upwork Job ID: 1832973509277607149</li>
        <li>Last Price Increase: 2024-09-09</li>
<li>Automatic offers: </li>
<ul>
<li>DylanDylann | Reviewer | 103901827</li>
<li>nkdengineer | Contributor | 103901829</li>
</ul></li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @kadiealexander</details>

**Comment by nkdengineer** [comment] 2024-09-07 11:18
## Proposal

### Please re-state the problem that we are trying to solve in this issue.

No response when clicking back button and link on not found page

### What is the root cause of that problem?

Currently, we are setting 2 functions `onBackButtonPress` and `onLinkPress` which are empty [here](https://github.com/Expensify/App/blob/4af620b439636f714ff72a26320ed57f9d2faac3/src/pages/EditReportFieldPage.tsx#L70-L71)

https://github.com/Expensify/App/blob/4af620b439636f714ff72a26320ed57f9d2faac3/src/pages/EditReportFieldPage.tsx#L70-L71

### What changes do you think we should make in order to solve the problem?


We just need to remove the 2 props `onBackButtonPress` and `onLinkPress` because we already have the default values [here](https://github.com/Expensify/App/blob/4af620b439636f714ff72a26320ed57f9d2faac3/src/components/BlockingViews/FullPageNotFoundView.tsx#L52-L55)

https://github.com/Expensify/App/blob/4af620b439636f714ff72a26320ed57f9d2faac3/src/components/BlockingViews/FullPageNotFoundView.tsx#L52-L55

### What alternative solutions did you explore? (Optional)

**Comment by trjExpensify** [comment] 2024-09-10 01:34
Report field config was added in #wave-control, moving this to that project.

**Comment by DylanDylann** [comment] 2024-09-10 04:52
@cretadn22 Your improvement looks good. But I think the main fix already be mentioned in @nkdengineer's [proposal](https://github.com/Expensify/App/issues/48761#issuecomment-2335156315)

Let's go with @nkdengineer's [proposal](https://github.com/Expensify/App/issues/48761#issuecomment-2335156315) because they go first 

🎀 👀 🎀 C+ reviewed

**Comment by DylanDylann** [comment] 2024-10-01 15:17
@kadiealexander This issue is ready for payment

**Comment by kadiealexander** [comment] 2024-10-02 06:02
**BugZero Checklist:** The PR fixing this issue has been merged! The following checklist ([instructions](https://stackoverflow.com/c/expensify/questions/14574)) will need to be completed before the issue can be closed:

- [ ] [@DylanDylann] The PR that introduced the bug has been identified. Link to the PR:
- [ ] [@DylanDylann] The offending PR has been commented on, pointing out the bug it caused and why, so the author and reviewers can learn from the mistake. Link to comment:
- [ ] [@DylanDylann] A discussion in #expensify-bugs has been started about whether any other steps should be taken (e.g. updating the PR review checklist) in order to catch this type of bug sooner. Link to discussion:
- [ ] [@DylanDylann] Determine if we should create a regression test for this bug.
- [ ] [@DylanDylann] If we decide to create a regression test for the bug, please propose the [regression test](https://github.com/Expensify/App/blob/main/contributingGuides/REGRESSION_TEST_BEST_PRACTICES.md) steps to ensure the same bug will not reach production again.
- [ ] [@kadiealexander] Link the GH issue for creating/updating the regression test once above steps have been agreed upon:

**Comment by kadiealexander** [comment] 2024-10-02 06:07
Payouts due:

- [ ] Contributor: $250 @nkdengineer 
- [ ] Contributor+: $250 @DylanDylann

Upwork job is [here](https://www.upwork.com/jobs/~021832973509277607149).

**Comment by DylanDylann** [comment] 2024-10-02 17:58
BugZero Checklist: The PR fixing this issue has been merged! The following checklist ([instructions](https://stackoverflow.com/c/expensify/questions/14574)) will need to be completed before the issue can be closed:

 [@DylanDylann] The PR that introduced the bug has been identified. Link to the PR: **NA**
 [@DylanDylann] The offending PR has been commented on, pointing out the bug it caused and why, so the author and reviewers can learn from the mistake. Link to comment: **NA**
 [@DylanDylann] A discussion in #expensify-bugs has been started about whether any other steps should be taken (e.g. updating the PR review checklist) in order to catch this type of bug sooner. Link to discussion: **NA**
 [@DylanDylann] Determine if we should create a regression test for this bug. **Yes**
 [@DylanDylann] If we decide to create a [regression test](https://github.com/Expensify/App/blob/main/contributingGuides/REGRESSION_TEST_BEST_PRACTICES.md) for the bug, please propose the regression test steps to ensure the same bug will not reach production again.


Regression Test Proposal
1. Create a new workspace
2. Navigate to Workspace Settings > More Features > Enable Report Field.
3. In Report Field, add a field, name it, choose a type, and save.
4. Go to Workspace Chat > Click the plus sign > Submit Expense > Add amount, merchant, and submit.
5. In the Expense report, click on the custom report fields
6. Edit field ID on router and press enter
7. Notice that page not found is displayed
8. Try to click the back button and link on this page
9. Verify that we can click the back button and link to go back.


Do we agree 👍 or 👎

**Comment by kadiealexander** [comment] 2024-10-02 22:00
https://github.com/Expensify/Expensify/issues/432947

**Closed** 2024-10-02 22:04 UTC
Labels: Reviewing, External, Weekly, Bug
