### ISSUE TITLE
[$500] [MEDIUM] IOU - In IOU Distance, when using a location, the GPS data latitude longitude is specified

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#37302] opened 2024-02-27 14:30 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.44-0
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**If this was caught during regression testing, add the test name, ID and link from TestRail:** https://expensify.testrail.io/index.php?/tests/view/4343474
**Email or phone of affected tester (no customers):** sustinov@applausemail.com
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** Applause - Internal Team
**Slack conversation:**

## Action Performed:
Preconditions:
Set up an OldDot administrator account, create a group policy, invite an employee, allow geolocation in the browser
https://sites.google.com/applausemail.com/applause-expensifyproject/wiki-guides/newdot-categories?authuser=0
1. Open https://staging.new.expensify.com/
2. Log in with the employee's login
3. Click on FAB
4. Select "Request money" - "Distance"
5. Click on the Start field.
6. Select the Use current location option.
7. Set another waypoint at a location close to your location to create a "real" trip
8. Complete the IOU
9. Go to the expense details
10. Click on the created check

## Expected Result:
IOU Distance must include the street name and house number when using a location

## Actual Result:
In IOU Distance, when using a location, the GPS data latitude longitude is specified, not the street name and house number

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [x] Android: mWeb Chrome
- [x] iOS: Native
- [x] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details> 

https://github.com/Expensify/App/assets/78819774/93864d30-66bd-4e82-b7c5-79f26ca01113

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~0130040ba5789f4f77</li>
        <li>Upwork Job ID: 1763726513761701888</li>
        <li>Last Price Increase: 2024-03-16</li>
    </ul>
</details>

**Comment by lanitochka17** [comment] 2024-02-27 14:32
We think that this bug might be related to #wave5
CC @dylanexpensify

**Comment by lanitochka17** [comment] 2024-02-27 14:33
@greg-schroeder  FYI I haven't added the External label as I wasn't 100% sure about this issue. Please take a look and add the label if you agree it's a bug and can be handled by external contributors

**Comment by greg-schroeder** [comment] 2024-03-02 00:37
Looking

**Comment by Tony-MK** [comment] 2024-03-02 05:23
I am unsure about the expected result because the backend returns the response below with `waypoint.address` already set as the GPS coordinates.

![Screenshot 2024-03-02 at 08 16 39](https://github.com/Expensify/App/assets/22982173/706ac900-602e-4e80-8b73-cf86ca8e8db5)

**Comment by ijmalik** [comment] 2024-03-04 09:17
This seems to be a duplicate and possibly related to Issue #34233, "[HOLD for payment 2024-02-07] [$500] [MEDIUM] Your location does not show full address in Distance expense."

@Ollyws, @dylanexpensify, could you please verify?

**Comment by greg-schroeder** [comment] 2024-03-05 18:12
It could be similar but not sure ... let's see if it's still a problem? Can anyone reproduce?

**Comment by ijmalik** [comment] 2024-03-06 02:21
@greg-schroeder @trjExpensify 
It is still problem.

https://github.com/Expensify/App/assets/2220885/4893f0f9-8b4c-41fd-830e-0d09ed9d7d96

**Comment by trjExpensify** [comment] 2024-03-07 12:19
Can you try on staging? I can't reproduce following the exact steps in the OP on Chrome: 

<img width="1509" alt="image" src="https://github.com/Expensify/App/assets/16232057/eaacdf82-77e8-4dee-9a09-bff001bed8f2">

**Comment by Tony-MK** [comment] 2024-03-07 20:59
@trjExpensify, The issue is still reproducible on staging.

![Screenshot 2024-03-07 at 23 56 01](https://github.com/Expensify/App/assets/22982173/f83fcf27-9860-4436-a5c6-d6b5048e019a)

From your [screenshot](https://github.com/Expensify/App/issues/37302#issuecomment-1983394501), I assume the trouble exists in step 6.

> 6. Select the Use current location option.

**Comment by trjExpensify** [comment] 2024-03-08 12:21
I did select "use current location" for the start address. :)

**Comment by trjExpensify** [comment] 2024-03-08 12:22
>If this is not the case, then perhaps, use the current location option when it is on the side of the closest road.

I don't know what you mean by this, but if the steps are wrong and it's something specific about the location, let's surface that -- because "use current location" is working on staging fine for me in my current location. :)

**Comment by Tony-MK** [comment] 2024-03-08 22:36
Yes, it is a location-specific bug. 

I think it depends on whether the map provider (backend) can find the road closest to the GPS coordinates to send back the address.

When the address can't be found, it will show the exact GPS Coordinates.

I don't know if the backend team is aware, but I believe this issue will likely have incorrect distance and fare calculations.

**Comment by greg-schroeder** [comment] 2024-03-09 02:17
Hmm. But that seems kind of expected, no? If we can't find a location w/ a specific address even with the "use current location" option, what are we supposed to show instead of this?

**Comment by greg-schroeder** [comment] 2024-03-13 10:53
What do you think @trjExpensify?  https://github.com/Expensify/App/issues/37302#issuecomment-1986695525

**Comment by trjExpensify** [comment] 2024-03-13 14:35
>If we can't find a location w/ a specific address even with the "use current location" option, what are we supposed to show instead of this?

It's a good question. @neil-marcellini @hayata-suenaga might have some insight, but falling back on the GPS coordinate seems reasonable.

**Comment by hayata-suenaga** [comment] 2024-03-13 19:31
I agree with @trjExpensify let's keep the current behavior 👍 

@greg-schroeder, I think we can close the issue

**Comment by hayata-suenaga** [comment] 2024-03-16 16:54
closing the issue 😄

**Closed by hayata-suenaga** 2024-03-16 16:54 UTC
Labels: External, Daily, Help Wanted, Overdue, Bug
