### ISSUE TITLE
[PAY RUSHAT 14TH JUL] Search  - App crashed after click on Search option for specific account

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#9487] opened 2022-06-17 18:02 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Launch App and login with andreylazutkinutest@gmail.com/w323052760We
2. Click Search

## Expected Result:
The search result is visible after click on search

## Actual Result:
App crashed after click on Search option

## Workaround:
Unknown 

## Platform:

Where is this issue occurring?

- Web
- iOS
- Android
- Desktop App
- Mobile Web

**Version Number:** 1.1.78.0

**Reproducible in staging?:** Yes

**Reproducible in production?:** No

**Email or phone of affected tester (no customers):** andreylazutkinutest@gmail.com/w323052760We

**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Notes/Photos/Videos:** Any additional supporting documentation

https://user-images.githubusercontent.com/93399543/174353330-747ed56f-135e-47e3-9350-dc34ca82c196.mp4

![Crash](https://user-images.githubusercontent.com/93399543/174353198-4f56784b-3504-4ae2-813f-58f481b30d36.jpg)

**Expensify/Expensify Issue URL:** 

**Issue reported by:** Applause - Internal Team

**Slack conversation:** 

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by kbecciv** [comment] 2022-06-17 18:05
This issue is reproduced only with 1 tester, credentials: andreylazutkinutest@gmail.com/w323052760We

**Comment by rushatgabhane** [comment] 2022-06-17 18:36
@pecanoro `ReportUtils.getChatRoomSubtitle()` is returning a `Number`.


https://github.com/Expensify/App/blob/5b0cd481c87e89772f7d21fdbad6bf815b495b15/src/libs/ReportUtils.js#L234

Which we're spreading over here.

https://github.com/Expensify/App/blob/5b0cd481c87e89772f7d21fdbad6bf815b495b15/src/libs/OptionsListUtils.js#L186-L187

We should either convert it to a string or make sure that it isn't a string in the first place!

**Comment by michaelhaxhiu** [comment] 2022-06-21 23:22
I'm OOO starting tomorrow, going to re-assign to another CM 🙏

**Comment by jliexpensify** [comment] 2022-06-22 23:34
@rushatgabhane I won't apply the exported label here, as it looks like we're just paying you $250 right? Please tag me in the Gh when you've accepted and I'll sort this out.

**Comment by MehmetFaahem** [comment] 2022-06-23 10:56
<h1>Hey, I can solve your issue. Your Issue:  button component passing an wrong parameter or cannot passing a string. It might be solved by me</h1>

**Comment by rushatgabhane** [comment] 2022-06-23 17:56
Apologies for the delay! Working on it.

**Comment by rushatgabhane** [comment] 2022-06-23 21:09
@jliexpensify yes, sounds good! Accepted the offer.

Note that we might fix it at the backend

**Comment by rushatgabhane** [comment] 2022-06-23 21:40
@jliexpensify yeah, after that's resolved, we'll know if this needs to be fixed internally or externally.

I'll ping you once that's resolved.

**Comment by jliexpensify** [comment] 2022-06-23 21:58
@rushatgabhane - great, let me know! I'll hold off on payment for now until we work out what needs to be done and how much we need to pay you.

**Comment by rushatgabhane** [comment] 2022-06-29 04:30
@jliexpensify we're fixing this issue both on frontend and backend https://github.com/Expensify/App/pull/9554#issuecomment-1165842774

The [PR](https://github.com/Expensify/App/pull/9554) is on staging. $250 after the regression period sounds great!

**Comment by pecanoro** [comment] 2022-07-07 21:36
Not overdue, PR was merged 9 days ago!

**Comment by jliexpensify** [comment] 2022-07-07 23:32
Heh, my bad: I hired you in preparation to pay you haha.

**Comment by mvtglobally** [comment] 2022-07-12 04:42
Issue not reproducible during KI retests. (First week)

**Comment by jliexpensify** [comment] 2022-07-14 03:08
@rushatgabhane - confirming that PR is deployed to production and I can pay you tomorrow?

**Comment by rushatgabhane** [comment] 2022-07-14 03:12
@jliexpensify yep!

**Comment by jliexpensify** [comment] 2022-07-15 02:20
Paid, and closed!

**Closed by jliexpensify** 2022-07-15 02:20 UTC
Labels: Reviewing, External, Engineering, Weekly, Improvement
