### ISSUE TITLE
[HOLD 26590] [$500] Web - After deleting IOUTransaction, clicking on back button in IOUReport does not navigate to chatReport

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#27436] opened 2023-09-14 12:58 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Go to any chat report that has IOU
2. Clicking on IOU action to open IOU report screen
3. Clicking on any report to open IOU details screen
4. Clicking on top right button to open menu
5. Clicking on delete to delete this request, it will redirect to the IOU report screen
6. Clicking on back button

## Expected Result:
It should navigate to the chat report screen

## Actual Result:
It does not navigate to the chat report screen. Need to click on back button again to navigate

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [x] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [x] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 1.3.70.2
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation

[Screencast from 11-09-2023 23_10_00.webm](https://github.com/Expensify/App/assets/93399543/a2090b2d-555b-4bb8-9684-82c1e80c1e6a)

https://github.com/Expensify/App/assets/93399543/84361aa6-d38d-4d6e-b355-a9b17ee708dc

**Expensify/Expensify Issue URL:**
**Issue reported by:** @DylanDylann
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1694448490097079

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01f1d2ea47889edcf4</li>
        <li>Upwork Job ID: 1702305916330889216</li>
        <li>Last Price Increase: 2023-09-21</li>
    </ul>
</details>

**Comment by kbecciv** [comment] 2023-09-14 13:00
Proposal by: @DylanDylann
Slack conversation: https://expensify.slack.com/archives/C049HHMV9SM/p1694448490097079

## Proposal
### Please re-state the problem that we are trying to solve in this issue.
- After deleting IOU Request, clicking on back button in IOUReport does not navigate to chatReport
### What is the root cause of that problem?
- Currently, after deleting the IOU request, it will do like below:
https://github.com/Expensify/App/blob/00ad8cf0e8ff2012140a4445ff8573a629af8483/src/libs/actions/IOU.js#L1279-L1286
- Firstly, ```Navigation.goBack()``` will navigate to the previous screen - that is IOUReport.
- Then the Navigation.navigate(ROUTES.getReportRoute(iouReport.reportID)) is called, will add the new IOUReportScreen to the stack.
- So currently, our stack has 2 IOUReport screen, which leads to the above bug and we need to clicking back buton two times to navigate to chatReport screen
### What changes do you think we should make in order to solve the problem?
- We need to make sure that there is one IOUReport screen in our stack after deleting IOURequest like below:
```
 // STEP 7: Navigate the user depending on which page they are on and which resources were deleted
    if (isSingleTransactionView && shouldDeleteTransactionThread && !shouldDeleteIOUReport) {
        // Pop the deleted report screen before navigating. This prevents navigating to the Concierge chat due to the missing report.
        Navigation.goBack();
        Navigation.navigate(ROUTES.getReportRoute(iouReport.reportID), CONST.NAVIGATION.TYPE.FORCED_UP);
        return;
    }
```
- Adding type:  CONST.NAVIGATION.TYPE.FORCED_UP to the Navigation.navigate function to use the REPLACE navigation action rather than PUSH
### Result
[Screencast from 11-09-2023 23:44:34.webm](https://github.com/Expensify/App/assets/141406735/dbb8e631-18eb-43d1-a7f8-926a0b0c8163)

**Comment by akamefi202** [comment] 2023-09-14 13:35
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
After deleting IOUTransaction, clicking on back button in IOUReport does not navigate to chatReport. It navigates to chatReport on second try.

### What is the root cause of that problem?
https://github.com/Expensify/App/blob/00ad8cf0e8ff2012140a4445ff8573a629af8483/src/libs/actions/IOU.js#L1280-L1285

After deleting IOUTransaction, the app navigates back to IOUReport and moves to IOUReport again.
So two IOUReports are stacked in navigation history. That's why it navigates to chatReport after clicking `Back` button twice.

### What changes do you think we should make in order to solve the problem?
I think we should only call `Navigation.goBack();` for this. It navigates back to IOUReport.

### What alternative solutions did you explore? (Optional)
N/A

**Comment by s-alves10** [comment] 2023-09-14 14:11
## Proposal

### Please re-state the problem that we are trying to solve in this issue.

Clicking back button in IOU report doesn't navigate to chat report after deleting IOU transaction

### What is the root cause of that problem?

https://github.com/Expensify/App/blob/95c9e4743f44ca42ece2c6ac56259b911d5feafc/src/libs/actions/IOU.js#L1382-L1394

As you can see, we go back(pop transaction) and again navigate to the iou report. So two iou report would exist in the navigation stack.

We can say the same for the case `shouldDeleteIOUReport` is true. We pop transaction and go to chat thread. So there would be chat report, iou report, and chat report again in the navigation stack. This causes similar bug

This is the root cause

### What changes do you think we should make in order to solve the problem?

We need to consider the case the navigation stack is empty(by refreshing the browser) as well
We can replace the above code(step 7) with the following
```
    // STEP 7: Navigate the user depending on which page they are on and which resources were deleted
    if (isSingleTransactionView && shouldDeleteTransactionThread) {
        // Pop the deleted report screen before navigating. This prevents navigating to the Concierge chat due to the missing report.
        Navigation.goBack(ROUTES.getReportRoute(iouReport.reportID));
        if (shouldDeleteIOUReport) {
            Navigation.navigate(ROUTES.getReportRoute(iouReport.chatReportID));
        }
    }
```

This works as expected
<details>
    <summary>Result</summary>


https://github.com/Expensify/App/assets/126839717/dba9519c-f162-4268-b369-a0338ff0a51d


</details>


### What alternative solutions did you explore? (Optional)

**Comment by M-Jawad338211** [comment] 2023-09-14 16:27
### **Proposal**

**Please re-state the problem that we are trying to solve in this issue.**
Clicking back button in IOU report doesn't navigate to chat report after deleting IOU transaction

**What is the root cause of that problem?**
So what I noticed is that the route changes when you delete the amount and when clicking on the back button it takes you back to previous route and so on. 

**What changes do you think we should make in order to solve the problem?**
We can control the routing or either clear the stack so that it doesn't take us back to the previous route after deleting the amount. 

**What alternative solutions did you explore? (Optional)**
None

**Comment by M-Jawad338211** [comment] 2023-09-14 16:31
> 📣 @M-Jawad338211! 📣 Hey, it seems we don’t have your contributor details yet! You'll only have to do this once, and this is how we'll hire you on Upwork. Please follow these steps:
> 
> 1. Get the email address used to login to your Expensify account. If you don't already have an Expensify account, create one [here](https://new.expensify.com/). If you have multiple accounts (e.g. one for testing), please use your main account email.
> 2. Get the link to your Upwork profile. It's necessary because we only pay via Upwork. You can access it by logging in, and then clicking on your name. It'll look like [this](https://www.upwork.com/freelancers/~01ca8ad8ce36b9eceb). If you don't already have an account, sign up for one [here](https://www.upwork.com/nx/signup/?dest=home).
> 3. Copy the format below and paste it in a comment on this issue. Replace the placeholder text with your actual details.
>    ![Screen Shot 2022-11-16 at 4 42 54 PM](https://user-images.githubusercontent.com/30609178/231263719-a8a3b7d3-36a0-4d7f-8ad4-cebe1f560fa4.png)
>    Format:
> 
> ```
> Contributor details
> Your Expensify account email: <REPLACE EMAIL HERE>
> Upwork Profile Link: <REPLACE LINK HERE>
> ```

Contributor details
Your Expensify account email: jawad338211@gmail.com
Upwork Profile Link: https://www.upwork.com/freelancers/~0141b79d3870905998

**Comment by rojiphil** [comment] 2023-09-19 12:12
I think, this issue may get resolved with PR #26498

**Comment by dylanexpensify** [comment] 2023-09-19 17:52
@robertKozik can you confirm ^ 🙇‍♂️

**Comment by robertKozik** [comment] 2023-09-19 19:13
@dylanexpensify Yeah, I think that too. Can we put this issue on hold until #26498 gets merged? After that, we could test this scenario and be sure that it's resolved.

**Comment by dylanexpensify** [comment] 2023-09-22 14:44
@robertKozik done!

**Comment by dylanexpensify** [comment] 2023-10-02 14:11
On hold still

**Comment by dylanexpensify** [comment] 2023-10-10 11:11
same status

**Comment by dylanexpensify** [comment] 2023-10-18 13:37
holding pattern

**Comment by dylanexpensify** [comment] 2023-10-24 22:53
same

**Comment by dylanexpensify** [comment] 2023-10-30 11:54
hold

**Comment by dylanexpensify** [comment] 2023-11-07 10:15
hold

**Comment by dylanexpensify** [comment] 2023-11-14 10:14
same

**Comment by dylanexpensify** [comment] 2023-11-22 09:38
Holing

**Comment by robertKozik** [comment] 2023-11-27 21:54
Cannot reproduce this either, I think we can close this one.
CC. @dylanexpensify

**Closed** 2023-12-05 19:44 UTC
Labels: External, Weekly, Help Wanted, Bug
