### ISSUE TITLE
Web - Receipt page tries load when an attachment is present

### ISSUE THREAD

**Issue by izarutskaya** [Expensify/App#25784] opened 2023-08-23 16:12 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Click on FAB
2. Click on request money
3. Enter amount and click next
4. Select new account
5. Open the request that you have sent
6. Set a description
7. Upload an image
8. Open the image
9. Click on previous arrow
10. Click on Download

## Expected Result:
The receipt image should not load with the attachment image

## Actual Result:
 The receipt image tries to load and when you hit download button it redirects to 404 page

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [x] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** v1.3.56-18

**Reproducible in staging?:** Y

**Reproducible in production?:** N

**If this was caught during regression testing, add the test name, ID and link from TestRail:**

**Email or phone of affected tester (no customers):**

**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/115492554/b0df542c-cc42-47c0-921a-def437d25f90

https://github.com/Expensify/App/assets/115492554/c5058844-dea5-4dcf-9f1a-fa43fb866a5f

**Expensify/Expensify Issue URL:**

**Issue reported by:** @jo-ui

**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1692782659149089

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01533b81d3403a95b1</li>
        <li>Upwork Job ID: 1694767523202289664</li>
        <li>Last Price Increase: 2023-08-24</li>
    </ul>
</details>

**Comment by thienlnam** [comment] 2023-08-23 17:49
cc @mountiny / @luacmartins Do you know if this is intended?

**Comment by luacmartins** [comment] 2023-08-23 18:10
This is not intended. There was no receipt attached in this case. Why is `TransactionUtils.hasReceipt(transaction)` returning true?

**Comment by luacmartins** [comment] 2023-08-23 18:30
@thienlnam I'll take this over as part of wave4

**Comment by StevenKKC** [comment] 2023-08-23 18:30
`EditMoneyRequest` API returns `receipt` field.
![Screenshot 2023-08-23 142712](https://github.com/Expensify/App/assets/131836113/a067179f-709d-4a6f-95e0-43a0c6f797f6)

**Comment by luacmartins** [comment] 2023-08-23 19:06
That doesn't seem to be the case anymore in our dev API. I think this has been fixed. I'll keep the issue open until we can confirm though

**Comment by jo-ui** [comment] 2023-08-23 19:09
@luacmartins This issue is still reproducible on the latest main (v1.3.56-20).

**Comment by jo-ui** [comment] 2023-08-23 19:09
https://github.com/Expensify/App/assets/57154082/b229fd25-ae83-4c55-87a5-7eb0556edaa9

**Comment by mountiny** [comment] 2023-08-23 23:47
@luacmartins this should be fixed now

**Comment by mountiny** [comment] 2023-08-23 23:47
@jo-ui could you confirm on the latest main

**Comment by jo-ui** [comment] 2023-08-24 05:51
@vit on the latest main(v1.3.57-0) receipt image appears and then disappears after editing the merchant on mweb but not on web, is this a new issue or it can be fixed with this #25784 issue

**Comment by jo-ui** [comment] 2023-08-24 05:58
https://github.com/Expensify/App/assets/57154082/464c56c8-a102-4f45-b8c5-fb281bc1d47d

**Comment by jo-ui** [comment] 2023-08-24 13:47
It is also reproducible on webhttps://github.com/Expensify/App/assets/57154082/f6398b77-deef-4fdd-8df8-e7381d4f4077

**Comment by jo-ui** [comment] 2023-08-24 13:54
It is also reproducible on web 
https://github.com/Expensify/App/assets/57154082/d830380a-3892-48d3-a3ee-cfd2b8e6e4b2

**Comment by jo-ui** [comment] 2023-08-24 14:05
@mountiny the above issue is also reproducible on web👆👆

**Comment by jo-ui** [comment] 2023-08-24 14:12
https://github.com/Expensify/App/assets/57154082/5ac0411a-17de-428b-84c8-847c6bb7bdcf

**Comment by jo-ui** [comment] 2023-08-29 06:53
@mountiny fix is live now and can't reproduce this anymore.

**Comment by luacmartins** [comment] 2023-09-05 15:47
No updates. Focused on other wave 4 issues.

**Comment by jo-ui** [comment] 2023-09-06 18:00
@adelekennedy This issue has been 13 days since the PR was merged to production

**Comment by adelekennedy** [comment] 2023-09-06 22:05
@luacmartins @mountiny what's the deal for payments here - just the reporting bonus?

**Comment by luacmartins** [comment] 2023-09-07 08:37
Yes, just reporting bonus. The fix and reviews were all internal.

**Comment by jo-ui** [comment] 2023-09-11 06:09
@adelekennedy Should I apply for the upwork job [above](https://github.com/Expensify/App/issues/25784#issuecomment-1692153580) for the reporting bonus?

**Comment by jo-ui** [comment] 2023-09-14 02:05
@adelekennedy any updates?

**Comment by adelekennedy** [comment] 2023-09-14 07:01
@jo-ui yes please!

**Comment by adelekennedy** [comment] 2023-09-14 07:02
### Payouts due:

Issue Reporter: $250 @jo-ui 



Upwork job is [here](https://www.upwork.com/jobs/~01533b81d3403a95b1).

**Comment by jo-ui** [comment] 2023-09-14 07:27
@adelekennedy can you please send me an offer it is saying " The job is private"

**Comment by adelekennedy** [comment] 2023-09-19 03:51
whoops - [this link](https://www.upwork.com/jobs/~01533b81d3403a95b1) @jo-ui

**Comment by jo-ui** [comment] 2023-09-19 04:03
@adelekennedy I've applied for the job

**Comment by adelekennedy** [comment] 2023-09-19 04:25
paid!

**Comment by luacmartins** [comment] 2023-09-27 01:24
Seems like everyone is paid out and we're good to close. Thanks everyone!

**Closed by luacmartins** 2023-09-27 01:24 UTC
Labels: Reviewing, Engineering, Daily, Internal, Bug
