### ISSUE TITLE
[HOLD for payment 2022-12-15] [$250] BUG: Web - Console error when comment in a report is right clicked and context menu is opened - reported by @aneequeahmad

### ISSUE THREAD

**Issue by mvtglobally** [Expensify/App#11903] opened 2022-10-17 09:38 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:

1. Launch web app.
2. Click on any report having links in comments in LHN
3. Hover on any comment and right click to open context menu

## Expected Result:
no console errors should display 

## Actual Result:
Console error: Failed prop type: Invalid prop `anchor` supplied to `BaseReportActionContextMenu`, expected a ReactNode at BaseReportActionContextMenu 

## Workaround:
Can the user still use Expensify without this being fixed? Have you informed them of the workaround?

## Platform:

Where is this issue occurring?

- Web

**Version Number:** 1.2.12-3
**Reproducible in staging?:** need repro
**Reproducible in production?:** need repro
**Email or phone of affected tester (no customers):** 
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation 

https://user-images.githubusercontent.com/43995119/196144255-575ad966-bfcf-49d6-b6c1-9931c29b18d5.mov

**Expensify/Expensify Issue URL:** 
**Issue reported by:** @aneequeahmad
**Slack conversation:** https://expensify.slack.com/archives/C01GTK53T8Q/p1664421573647289

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by muttmuure** [comment] 2022-10-19 12:51
I'm not able to reproduce this

**Comment by tjferriss** [comment] 2022-11-04 22:01
I was not able to reproduce the issue following the steps outlined. @mvtglobally are you still seeing this issue? If so, can you clarify the steps to reproduce.

https://user-images.githubusercontent.com/8292562/200081258-68a898ec-6ce2-40b5-a8d8-92302f051b8e.mov

**Comment by aneequeahmad** [comment] 2022-11-06 19:18
@tjferriss This issue is still reproducible on latest dev built. Please right click on a `comment that is a link`.

**Comment by aneequeahmad** [comment] 2022-11-14 03:50
### PROPOSAL

**Problem:**

The type of anchor is defined as `node` but it's a reference to the DOM node. 

https://github.com/Expensify/App/blob/92eff7267aa7be67463873cdb431f5cd79c22b59/src/pages/home/report/ContextMenu/BaseReportActionContextMenu.js#L20-L22

**Solution**

The type of this DOM node should be object as it's a reference to DOM node not any `children/component` passed in props.  The code will change to the following

```

    /** Target node which is the target of ContentMenu and its object as it is reference to DOM node */
    anchor: PropTypes.object
    
```

**Comment by tjferriss** [comment] 2022-11-15 21:00
Job posting is live on Upworks: https://www.upwork.com/ab/applicants/1592623364413255680/job-details

**Comment by tjferriss** [comment] 2022-11-15 21:01
@dangrous @aimane-chnaif can you both please review @aneequeahmad's proposal?

**Comment by AhmadbinZahid** [comment] 2022-11-16 00:17
**PROPOSAL**

**Solution** 

Either we need to make sure that anchor is getting the same type of value in each case (i.e native & web) or we can do something like this to handle both cases: 
`anchor: PropTypes.oneOfType([PropTypes.number, PropTypes.object]),`

**Comment by aneequeahmad** [comment] 2022-11-17 06:36
@aimane-chnaif I think my [proposal](https://github.com/Expensify/App/issues/11903#:~:text=anchor%3A%20PropTypes.object) is working as expected on native platforms.

 The error you said [above](https://github.com/Expensify/App/issues/11903#:~:text=your%20solution%20in%20this%20proposal%20causes%20regression%20on%20native%20which%20is%20already%20working.) is happening on native platform since it is given the `type number` and it is expecting an object.
 
   
<img width="948" alt="Screenshot 2022-11-17 at 11 24 00 AM" src="https://user-images.githubusercontent.com/36359331/202372652-8ce6c42a-f4de-4f3d-abaa-03f9924400b4.png">


Am i missing something ? Please review again if what i said above makes sense. Thanks

**Comment by aneequeahmad** [comment] 2022-11-17 07:23
@aimane-chnaif I'm not sure what you're talking about. Please see the `Actual result` of the reported [bug](https://github.com/Expensify/App/issues/11903#:~:text=Console%20error%3A%20Failed%20prop%20type%3A%20Invalid%20prop%20anchor%20supplied%20to%20BaseReportActionContextMenu%2C%20expected%20a%20ReactNode%20at%20BaseReportActionContextMenu).

> this is what anchor is set to

This is never set to number please see the code of file `BaseReportActionContextMenu` in latest main branch on Github. 

https://github.com/Expensify/App/blob/92eff7267aa7be67463873cdb431f5cd79c22b59/src/pages/home/report/ContextMenu/BaseReportActionContextMenu.js#L20-L22

**Comment by marcaaron** [comment] 2022-11-22 00:12
This feels low priority to me as it's not directly tied to anything broken in the app. Not saying we shouldn't fix it. But maybe should be on HOLD for #focus.

**Comment by aneequeahmad** [comment] 2022-11-22 03:09
The screenshots/Videos are:

### WEB:

<img width="1440" alt="Screenshot 2022-11-22 at 8 02 45 AM" src="https://user-images.githubusercontent.com/36359331/203210984-de529dbd-3171-4e82-b251-08189acc872c.png">

### IOS:

<img width="937" alt="Screenshot 2022-11-22 at 8 03 40 AM" src="https://user-images.githubusercontent.com/36359331/203211087-fb18b14a-e4bf-4e0b-9e59-31d5e7651bf8.png">

@aimane-chnaif  You're right what you said [here](https://github.com/Expensify/App/issues/11903#:~:text=your%20solution%20in%20this%20proposal%20causes%20regression%20on%20native%20which%20is%20already%20working.) It was working fine on IOS as the proptype is actually node on IOS (like the official doc says [here](https://reactnative.dev/docs/react-node#:~:text=A%20React%20Node,a%20nested%20one))

**Comment by aneequeahmad** [comment] 2022-11-22 03:11
### UPDATED PROPOSAL:

Solution: 

Need to update the existing code 

**From:**

https://github.com/Expensify/App/blob/34f53dd8020e0224c392e767a910fa7ddee3aee1/src/pages/home/report/ContextMenu/BaseReportActionContextMenu.js#L21-L22

**To:**

```
/** Target node which is the target of ContentMenu */
    anchor: PropTypes.oneOfType([PropTypes.node, PropTypes.object]),
    
```

cc: @aimane-chnaif

**Comment by mvtglobally** [comment] 2022-11-22 21:21
Issue not reproducible during KI retests. (First week)

**Comment by aneequeahmad** [comment] 2022-11-22 21:39
@aimane-chnaif, I would also like to mention that the official doc says that `React Node is one of the following` it means it is expected that the React node is is one of number and strings. like the doc says.

_**A React Node is one of the following types:**_

- Boolean (which is ignored)
- null or undefined (which is ignored)
- Number
- String
- A React element (result of JSX)
- An array of any of the above, possibly a nested one

So it does make sense when proptype of DOM reference is node as it can be a string, number or React element and this is bullet proof solution cuz DOM element can be of type Node (which has further types defined).

**Comment by aneequeahmad** [comment] 2022-11-22 21:47
@aimane-chnaif yes except for web since It's not an html value. It is a reference to the DOM node. Browser probably using  to.String before showing it on console. Type of this value is Object as discussed on [slack](https://expensify.slack.com/archives/C01GTK53T8Q/p1668322339402579?thread_ts=1668235962.022259&cid=C01GTK53T8Q)

**Comment by AhmadbinZahid** [comment] 2022-11-22 22:07
Can anyone confirm what is the typeof anchor in case of android?

**Comment by AhmadbinZahid** [comment] 2022-11-22 22:12
As far as I've learned, looking at every target event type from:
`node_modules/@types/react-native/index.d.ts`
Native target event type, is a number.

**Comment by aneequeahmad** [comment] 2022-11-22 22:39
> object cannot be DOM node

That's right, its not DOM node  It is actually a reference to the DOM node.

**Comment by tjferriss** [comment] 2022-11-23 18:29
Reviewing the issue based on the [weekly bug update chore](https://stackoverflow.com/c/expensify/questions/8208):

@robertjchen this is one of the oldest issues in the /App repo. To help us clear out the large backlog of bugs, can you:
- Decide whether any proposals currently meet our guidelines and can be approved as-is
- For any that can't, please take this issue internal and treat it as one of your highest priorities
- If you have any questions, don't hesitate to start a discussion in #bug-zero

**Comment by robertjchen** [comment] 2022-11-23 23:57
Update: This one appears to be close, awaiting clarification on the above question.

**Comment by trjExpensify** [comment] 2022-11-24 16:47
👋 @AhmadbinZahid just a quick bump on [this question](https://github.com/Expensify/App/issues/11903#issuecomment-1325319603), please.

**Comment by AhmadbinZahid** [comment] 2022-11-24 17:34
> > As far as I've learned, looking at every event target type from: `node_modules/@types/react-native/index.d.ts` Native event target type, is a number.
> 
> @AhmadbinZahid can you specify which line exactly indicates it's a number?

Line 357 for `NativeTouchEvent` 
 - Line 391 inside the interface, target's type is NodeHandle, which is equal to number.
 
 If you want to look at other places 
 `TargetedEvent` interface is defined at line 1636 that is also used & extended at multiple other types
 which also has the target value set to number

**Comment by AhmadbinZahid** [comment] 2022-11-24 17:50
@aimane-chnaif  Do you have the value for anchor in case of android? I need to confirm.

**Comment by AhmadbinZahid** [comment] 2022-11-24 18:11
@aimane-chnaif typeof(null) is also object 
so it is coming true for this case as well
anchor: PropTypes.oneOfType([PropTypes.number, PropTypes.object])

**Comment by AhmadbinZahid** [comment] 2022-11-24 18:23
I'm not saying don't got with this solution or any other, I'm just confused, the idea behind typescript is to define as precise types as possible to handle the cases better.
If we've not seen the undefined and any other case than this, what possibility is there that there is, & if so, it is undefined?
Might as well go with type `any` in terms of being generic.

**Comment by aneequeahmad** [comment] 2022-11-28 09:17
Should i raise the PR ? @aimane-chnaif

**Comment by robertjchen** [comment] 2022-11-28 09:44
Thanks for all the detailed discussion here! After reviewing it, I think we should proceed- please move forward with the PR @aneequeahmad 👍

**Comment by trjExpensify** [comment] 2022-11-29 10:13
Niceee, assigning this issue to @aneequeahmad.

**Comment by trjExpensify** [comment] 2022-11-29 10:13
Oh wow, it just updated for me haha. Ignore!

**Comment by tjferriss** [comment] 2022-11-29 18:48
@aneequeahmad and @aimane-chnaif can you both please apply to the job in Upworks? https://www.upwork.com/jobs/~0128135a88a5516b95

**Comment by JmillsExpensify** [comment] 2022-11-29 21:11
@aneequeahmad We have two days to merge the PR for the 50% bonus to apply. Can we expect the PR tomorrow?

**Comment by mvtglobally** [comment] 2022-11-30 05:08
Issue not reproducible during KI retests. (First week)

**Comment by aneequeahmad** [comment] 2022-11-30 09:19
I'll be raising the PR today. 

cc: @JmillsExpensify, @aimane-chnaif, @tjferriss

**Comment by dangrous** [comment] 2022-12-01 23:07
Merged! Awaiting deployment.

**Comment by dangrous** [comment] 2022-12-05 17:57
Not overdue; was [deployed to prod on 12/2](https://github.com/Expensify/App/pull/13248#issuecomment-1335742608) so we're in our 7 day waiting period! Not sure why the bot didn't say anything.

**Comment by dangrous** [comment] 2022-12-08 17:16
So the PR that introduced this bug is definitely [this one](https://github.com/Expensify/App/pull/9955) - none of the related code has been touched since then, and that's when the `anchor` prop was created. However it's also the PR that created the functionality in the first place, I believe, so this was less of a regression and more that testers must not have checked for the console errors?

Let me know if you agree @aimane-chnaif and @robertjchen

**Comment by dangrous** [comment] 2022-12-08 21:19
Okay great - I'll comment on that PR, and start (and end) a discussion in #expensify-bugs about it. I think since our existing process should have caught this, I'm guessing it's just user error.

**Comment by dangrous** [comment] 2022-12-13 14:45
@tjferriss How's the regression test checkbox looking? Let me know if I can help - seeing if we can close this out soon

**Comment by tjferriss** [comment] 2022-12-13 20:08
@dangrous thanks for the reminder. I'm actually wondering whether a regression test is necessary here. Would we have testers check the JS console to see issues like this?

**Comment by dangrous** [comment] 2022-12-13 21:57
Yeah I'm not sure how that works for testing. I know that reviewers/contributors should check the console to make sure there aren't errors in places the PR directly affects... So that would have caught this in this specific case. Although actually I'm pretty sure QA has their console up while checking things. So if right clicking the context menu is part of their flow, it should be caught already? Not 100% on that...

**Comment by tjferriss** [comment] 2022-12-14 21:59
I tend to agree. It looks like we have testing for reviewing and editing messages so I think we're covered.

@aneequeahmad has been paid for reporting and fixing the issue plus the 50% bonus for merging the PR in three days.

@aimane-chnaif once you accept the offer in UpWorks I can pay you out for the contributor plus role.

**Comment by tjferriss** [comment] 2022-12-14 22:10
Sorry, I just invited you.
<img width="1059" alt="Screen Shot 2022-12-14 at 2 10 32 PM" src="https://user-images.githubusercontent.com/8292562/207725998-5c781394-a019-4f73-993e-c1050b0212b1.png">

**Comment by dangrous** [comment] 2022-12-19 18:13
Are we all set on the payment now? If so I think we can close this!

**Comment by tjferriss** [comment] 2022-12-20 19:57
Payment has been sent.

**Closed by tjferriss** 2022-12-20 19:57 UTC
Labels: External, Daily, Awaiting Payment, Bug
