### ISSUE TITLE
[HOLD for payment 2023-07-24] [$1000] Correct chat is not opened by tapping chat link

### ISSUE THREAD

**Issue by kavimuru** [Expensify/App#20624] opened 2023-06-12 21:12 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___
This issue was found when retesting #19914
## Action Performed:
1. Using Android m/Web, login to NewDot with account A and open any DM. Copy the report url from the address bar (like https://staging.new.expensify.com/r/1242891003534332
)
2. Paste it in any external app (Slack or Telegram)
3. Log in with same account (account A) in android app
4. In the android app, open any other chat (not the one you opened in step 1)
5. Go back to the external app and tap link you pasted in external app
## Expected Result:
Chat from step 1 should be opened without any visual issues.

## Actual Result:
Chat from step 4 stays on the screen

## Workaround:
Can the user still use Expensify without this being fixed? Have you informed them of the workaround?

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [ ] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 1.3.26-3
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/43996225/9c212204-3947-4e65-bc38-353800806187

**Expensify/Expensify Issue URL:**
**Issue reported by:** applause internal team
**Slack conversation:**

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01b971875418ce264c</li>
        <li>Upwork Job ID: 1668776814229225472</li>
        <li>Last Price Increase: 2023-07-05</li>
    </ul>
</details>

**Comment by DanutGavrus** [comment] 2023-06-13 21:03
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
Correct chat is not opened by tapping chat link.

### What is the root cause of that problem?
This is what happens now if the app is opened in background and we try to open a chat from a deep link:
1) In `Expensify.js` we call `Linking.addEventListener('url', (state) => Report.openReportFromDeepLink(state.url, isAuthenticated));`;
2) In `Report.js` we call `Navigation.navigate(ROUTES.getReportRoute(reportID));`;
3) In `Navigation.js` we call `linkTo(navigationRef.current, route, type);`;
4) In `linkTo.js` we call:
```
if (action.payload.name === NAVIGATORS.CENTRAL_PANE_NAVIGATOR && getTopmostReportId(root.getState()) !== getTopmostReportId(state)) {
            action.type = 'PUSH';
```
##### Now, here is the problem  
Both `getTopmostReportId(root.getState())` and `getTopmostReportId(state)` return the __same report id__, so we never set `action.type = 'PUSH'`, so we never navigate to the new report.  
##### Why does this happen?  
`getTopmostReportId(state)` returns the reportId from the URL, which is the new report ID where we need to navigate to. But, when coming from a deep link, the `NavigationContainer` has the _new state inserted automatically_ as this is it's default behavior(one may check this as `onStateChange` callback is automatically triggered when the app gets reopened from the deep link), so `getTopmostReportId(root.getState())` returns the new report id, even if we did not navigate there yet.

### What changes do you think we should make in order to solve the problem?
1) As everything starts from `openReportFromDeepLink`, we may pass an optional parameter set to false by default, in order to let `linkTo` know when we come from a deep link.
2) We know `getTopmostReportId(root.getState())` will return the same reportId when coming from a deep link, so we need another way to get the last visible reportId. I have some options in mind such as:
2.1. Either, when `onStateChange` gets called for the `NavigationContainer`, in `updateSavedNavigationStateAndLogRoute` we may also save the `previousState`;
2.2. Or, add an event listener for when app goes to background on native, same as we already have the one from when it comes back active. Inside it, save `lastReportId` which is going to be the current opened report id if any, or null/undefined otherwise.
2.3 Or, I may think of other ways to get the topmost report id inside `linkTo` if previous 2 are not the best, let me know.
3) Now, inside `linkTo`, we may update the `if`, such that when coming from a deep link, will use the other way to get the topmost report id instead of `getTopmostReportId(root.getState())`.

### What alternative solutions did you explore?
__I__. If we don't want to add and pass a new parameter when coming from a deep link, we may completely move from using `getTopmostReportId(root.getState())` to always saving a report id in a context when opening a report, and resetting it when closing one, which will be used here. `linkTo.js` would look like:
```
const topmostReportId = the one from where we saved it;
if (action.payload.name === NAVIGATORS.CENTRAL_PANE_NAVIGATOR && topmostReportId !== getTopmostReportId(state)) {
            action.type = 'PUSH';
```
__II__. If we don't want to save the topmost report id, we may also just pass when coming from a deep link, and set `action.type = 'REPLACE'`, thus we'll replace the current report with the one from the deep link every time, but this will mess the back navigation as the previous screen was replaced with this one.

**Comment by bernhardoj** [comment] 2023-06-14 10:37
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
Unable to open a different chat by deeplink

### What is the root cause of that problem?
Currently, we have a deep link handler specifically for report screen introduced in this [PR](https://github.com/Expensify/App/pull/14669)
https://github.com/Expensify/App/blob/862955c2f15bce3c68d87c549b7af0e27a0eb526/src/Expensify.js#L163-L167

Why we have it for report screen only? The best guess I have is, before the navigation reboot, we use a drawer navigator for LHN and report screen, so we need a custom handler for report screen that will handle whether to close or open the drawer. Below is the screenshot of the old `Navigation.navigate`. If it's a drawer route, which is true for report screen, it will do a custom action.

<img width="655" alt="image" src="https://github.com/Expensify/App/assets/50919443/2c77c9e0-ded8-455a-aeb8-28820570589d">

Now, we have completely moved to stack navigator and the `navigate` implementation is updated. When we navigate to a report screen, it will compare the current report screen id and the report id we want to navigate (both id is taken from navigation state). If it's different, we want to push it to the stack. This works well when we just doing a simple navigation, but not with deeplink.
https://github.com/Expensify/App/blob/862955c2f15bce3c68d87c549b7af0e27a0eb526/src/libs/Navigation/linkTo.js#L26-L30

When we are doing a deeplink, rn-navigation will navigate to the target report id, even without the custom deeplink handler we have. So, when we deeplink to report B, the root navigation state is already updated with the report B id, so when the custom handler runs, both current report screen id and target report id is the same, thus the navigation action type stays as NAVIGATE instead of PUSH.

NAVIGATE action won't push the new screen if it's already exist in the stack, that's why I believe we have this [commit](https://github.com/Expensify/App/commit/9ce4817e11bce589085ac3fbf418476dffa67128) that will change the type to PUSH if the report id is different.

### What changes do you think we should make in order to solve the problem?

As the intention is to push the new report screen to stack if the report ID is different, I think the better way to handle it is by adding `getId` props to report screen here:
https://github.com/Expensify/App/blob/862955c2f15bce3c68d87c549b7af0e27a0eb526/src/libs/Navigation/AppNavigator/Navigators/CentralPaneNavigator.js#L18-L30

`getId` will return report id.
```
getId={({params}) => params.reportID}
```

This will always push the new report screen if the report ID is not in the stack yet. Also, we don't need this logic anymore.
https://github.com/Expensify/App/blob/862955c2f15bce3c68d87c549b7af0e27a0eb526/src/libs/Navigation/linkTo.js#L28-L31

Or is there any clear reason we are doing it that way?

**Comment by pecanoro** [comment] 2023-06-19 14:01
@rushatgabhane There are a few proposals for you to review! 🤗

**Comment by pecanoro** [comment] 2023-06-23 20:54
@rushatgabhane It's been 3 days since your last message, can you please prioritize taking a look here? Thank you!!

**Comment by DanutGavrus** [comment] 2023-06-26 16:30
@rushatgabhane
> @DanutGavrus your https://github.com/Expensify/App/issues/20624#issuecomment-1590023343 is well explained too. But I like @bernhardoj's solution more because it's fixing the root cause and it's simple.  

I agree! That was the `ID` I was looking for, but missed 😁

**Comment by bernhardoj** [comment] 2023-06-26 16:43
Before continue with my proposal, can we have a review from the SWM team that did the navigation reboot?

> Or is there any clear reason we are doing it that way?

I think we also need the answer of this. That would be great if we can have the confirmation from them.

**Comment by bernhardoj** [comment] 2023-06-27 04:19
@rushatgabhane I see on other navigation-related issues ([example](https://github.com/Expensify/App/issues/20908#issuecomment-1604345560)), sometimes we tag the SWM team to have an additional review of the proposal, so I think we can do the same here?

**Comment by maddylewis** [comment] 2023-06-27 17:14
i reached out to SWM here - https://expensify.slack.com/archives/C04878MDF34/p1687886035526329

i asked if someone had availability to review the proposal. if so, they will comment on this issue 👍

**Comment by bernhardoj** [comment] 2023-06-28 10:29
@WoLewicki yes. Either by deeplink or navigating normally to the same report won't push the exact same report to the stack.

**Comment by bernhardoj** [comment] 2023-06-28 12:04
The snippet is on my proposal, but here is the diff to be clearer:
<details>
<summary>diff</summary>

```diff
diff --git a/src/libs/Navigation/AppNavigator/Navigators/CentralPaneNavigator.js b/src/libs/Navigation/AppNavigator/Navigators/CentralPaneNavigator.js
index 64eadcbe06..2c57e42771 100644
--- a/src/libs/Navigation/AppNavigator/Navigators/CentralPaneNavigator.js
+++ b/src/libs/Navigation/AppNavigator/Navigators/CentralPaneNavigator.js
@@ -27,6 +27,7 @@ function CentralPaneNavigator() {
                         cardStyle: styles.cardStyleNavigator,
                     }}
                     component={ReportScreenWrapper}
+                    getId={({params}) => params.reportID}
                 />
             </Stack.Navigator>
         </FreezeWrapper>
diff --git a/src/libs/Navigation/linkTo.js b/src/libs/Navigation/linkTo.js
index 1d219c450e..602e0a0642 100644
--- a/src/libs/Navigation/linkTo.js
+++ b/src/libs/Navigation/linkTo.js
@@ -25,13 +25,9 @@ export default function linkTo(navigation, path, type) {
 
     // If action type is different than NAVIGATE we can't change it to the PUSH safely
     if (action.type === 'NAVIGATE') {
-        // If this action is navigating to the report screen and the top most navigator is different from the one we want to navigate - PUSH
-        if (action.payload.name === NAVIGATORS.CENTRAL_PANE_NAVIGATOR && getTopmostReportId(root.getState()) !== getTopmostReportId(state)) {
-            action.type = 'PUSH';
-
-            // If this action is navigating to the RightModalNavigator and the last route on the root navigator is also RightModalNavigator
-            // then we want to replace the current RHP state with new one
-        } else if (type === 'UP') {
+        // If this action is navigating to the RightModalNavigator and the last route on the root navigator is also RightModalNavigator
+        // then we want to replace the current RHP state with new one
+        if (type === 'UP') {
             action.type = 'REPLACE';
 
             // If this action is navigating to the RightModalNavigator and the last route on the root navigator is not RightModalNavigator then push

```

</details>

**Comment by WoLewicki** [comment] 2023-06-28 12:30
Hmm looking at https://reactnavigation.org/docs/screen/#getid, what about deeplinking to a report that is already somewhere deeper in the stack? Won't it navigate back then? We want the new reports to be always pushed on top, even if we have already been on that report earlier.
![image](https://github.com/Expensify/App/assets/32481228/37c0a9ff-456e-422b-9510-8ba74848a0df)

**Comment by WoLewicki** [comment] 2023-06-28 12:35
We would probably have to add some unique id to each of those ids and then cut it when using in the component, but it should be rather easy. Or am I missing something @bernhardoj ?

**Comment by bernhardoj** [comment] 2023-06-28 13:16
> Won't it navigate back then?

Yes.

> We want the new reports to be always pushed on top, even if we have already been on that report earlier.

If this is the case, then my proposal won't work as expected.

> We would probably have to add some unique id to each of those ids

`getId` only has `params` that contains `reportID` only. I actually have no idea what kind of unique ID we can append to `reportID` 😅.

**Comment by WoLewicki** [comment] 2023-06-29 10:47
@bernhardoj you can change the `getId` method to append some suffix to the `reportID`, e.g. the index of the screen you are at now so it is unique. Is it ok?

**Comment by bernhardoj** [comment] 2023-06-29 12:16
@WoLewicki 
> the index of the screen you are at now

I'm assuming we want the screen index of the report screen, which means the logic will be similar to `getTopmostReportId`. I tried to append it with `getTopmostReportId` but it doesn't work. `getTopmostReportId` will always return the report ID we "want" to navigate. I think this would be the same with `index` because route state is already updated before `getId` is called.

**Comment by bernhardoj** [comment] 2023-06-29 16:06
> shouldn't it be applied to the RootStack screen with name={NAVIGATORS.CENTRAL_PANE_NAVIGATOR}

I just realized that navigating to the report will push CENTRAL_PANE_NAVIGATOR to the stack. I thought we would only have one CENTRAL_PANE_NAVIGATOR and a new report will be pushed to CENTRAL_PANE_NAVIGATOR. But adding the `getId` to `name={SCREENS.REPORT}` somehow works (I guess it checks the screen name?).

**Comment by WoLewicki** [comment] 2023-06-30 08:50
What do you mean by works? It still pushes it without setting it to `PUSH` in `linkTo.js` ?

**Comment by WoLewicki** [comment] 2023-06-30 09:26
Hmm it seems weird, but maybe it is how `react-navigation` works under the hood. Still, we need to handle the case of trying to navigate to the same report via deeplink.

**Comment by maddylewis** [comment] 2023-06-30 14:10
@WoLewicki and @bernhardoj are working this out and will potentially review other proposals.

**Comment by maddylewis** [comment] 2023-07-05 13:13
@rushatgabhane - will you review @hungvu193's comment [here](https://github.com/Expensify/App/issues/20624#issuecomment-1617125332) and provide an update on how you think we should move forward? thanks!

**Comment by mvtglobally** [comment] 2023-07-06 03:49
Issue not reproducible during KI retests. (First week)

**Comment by pecanoro** [comment] 2023-07-06 17:16
I tried to reproduce it again. It does work if you are in the LHN menu, but still I can reproduce it if I have another chat opened.

**Comment by pecanoro** [comment] 2023-07-07 18:29
Melvin got confused with the assignment haha

**Comment by WoLewicki** [comment] 2023-07-10 13:25
If @hungvu193 solution does not destroy the navigation history (the back buttons lead to correct pages) and also browser history (if it is reproducible on web, then clicking browser back button should also lead to correct page), then I think it can be the best option.

**Comment by DanutGavrus** [comment] 2023-07-11 08:54
@WoLewicki @allroundexperts 
From [my Proposal](https://github.com/Expensify/App/issues/20624#issuecomment-1590023343) on June 14th:
> II. If we don't want to save the topmost report id, we may also just pass when coming from a deep link, and set action.type = 'REPLACE', thus we'll replace the current report with the one from the deep link every time, but this will mess the back navigation as the previous screen was replaced with this one.  

This is what I meant with **"we may also just pass when coming from a deep link"**(parameter for the method) and with **"set action.type"**(implicit effect):
https://github.com/Expensify/App/blob/a23d1614c0e60f99dd51cf6f4fd08f65248203d1/src/libs/Navigation/linkTo.js#L34-L35

Then, isn't [@hungvu193 solution](https://github.com/Expensify/App/issues/20624#issuecomment-1617125332) a dupe?  

Also:
> If @hungvu193 solution does not destroy the navigation history (the back buttons lead to correct pages) and also browser history (if it is reproducible on web, then clicking browser back button should also lead to correct page).  

The only thing which messes with the back navigation is the previous report which won't be there when going back, as it was replaced with the opened one as I've said back then:
> [...] but this will mess the back navigation as the previous screen was replaced with this one.

What this means is that if I'm on a chat with friend A and then click on a link to a chat with friend B, chat A will get replaced with chat B, so pressing back will get us 1 screen before chat with friend A.

**Comment by WoLewicki** [comment] 2023-07-11 12:38
I think we can go with the `replace` solution since deeplinking to an app from external source can be seen as creating the new navigation flow in it.

**Comment by DanutGavrus** [comment] 2023-07-11 12:47
@allroundexperts @WoLewicki 
Not sure if this would work & actually be a better alternative, but thought to point it out. What if:
1. When app goes in background in native, save `lastVisibleReportID` in Onyx if it leaves from an opened report, null/undefined otherwise. We already have an *app become visible callback* implemented, and the *app went to background callback* will be very similar;
2. Then, instead of using `getTopmostReportId(root.getState()) !== getTopmostReportId(state)`, we'll compare `getTopmostReportId` with the saved `lastVisibleReportID`?

**Comment by pecanoro** [comment] 2023-07-11 16:43
Sounds good! Thank you everyone!

**Comment by DanutGavrus** [comment] 2023-07-12 12:34
@allroundexperts 
PR ready for review: [PR22740](https://github.com/Expensify/App/pull/22740)

**Comment by DanutGavrus** [comment] 2023-07-24 16:09
@allroundexperts 
Yes, I'll look into this tomorrow!

**Comment by DanutGavrus** [comment] 2023-07-25 10:16
I have some PRs in progress which I need to take care of, I'll come to this right after!

**Comment by maddylewis** [comment] 2023-07-26 00:36
updated amounts! 

@allroundexperts - i'll let you clarify the other details that @DanutGavrus is asking about!

**Comment by DanutGavrus** [comment] 2023-07-26 14:38
@maddylewis 
> updated amounts!  

The Upwork job seems to have the same amount.

@bernhardoj
> react-navigation linking has a [subscribe](https://reactnavigation.org/docs/navigation-container/#linkingsubscribe) function to override the default deep link handler by react-navigation. It may help.

Couldn't figure it out with that approach.

@bernhardoj @allroundexperts @WoLewicki 
I think I've eventually found a fix. This is our current `openReportFromDeepLink` implementation:
https://github.com/Expensify/App/blob/3d22f591054e5ace31afa58d965e382768e309d4/src/libs/actions/Report.js#L1694-L1722
And this is a potential fix:
```js
function openReportFromDeepLink(url, isAuthenticated) {
  const activeRoute = Navigation.getActiveRoute();
  const {reportID: activeReportID} = ROUTES.parseReportRouteParams(activeRoute);
  const route = ReportUtils.getRouteFromLink(url);
  const reportID = ReportUtils.getReportIDFromLink(url);

  [...]

    SidebarUtils.isSidebarLoadedReady().then(() => {
      // Navigate to the new report only if one is already opened. Otherwise, the NavigationRoot navigates automatically.
      if (activeReportID && reportID && activeReportID != reportID) {
          Navigation.navigate(ROUTES.getReportRoute(reportID), 'UP');
      }
```

1. Deeplink opening a report from **any** screen which is not a report(*Home*, *Settings Page*, etc) does *not* open that report twice(as in the new issue) *anymore*;
2. Deeplink opening the *same* report which we are on does *not* replace it *anymore*.

[OPTIONAL CHANGE] On a side note, I think this may be extended as to remove `'UP'` and pass a new `activeReportID` optional parameter to the `navigate` method and then to the `linkTo` method. Inside it, if an `activeReportID` was passed, we compare `activeReportID != getTopmostReportId(state)` where `state = getStateFromPath(path)`, if not, we keep `getTopmostReportId(root.getState()) !== getTopmostReportId(state)`. This would fix:  

3. [OPTIONAL FIX] Deeplink opening a report replaces the actual one and back navigation does not bring us to previous report(The small problem we agreed may remain with that solution).

Let me know your thoughts about this! 👀

**Comment by maddylewis** [comment] 2023-07-27 12:33
### Payments:
- [x] no reporting bonus
- [ ] @allroundexperts ($1500 - paid via NewDot)
- [ ] @DanutGavrus ($1500 - paid via Upwork)

**Comment by maddylewis** [comment] 2023-07-29 11:58
requested refund of $1k from @DanutGavrus in Upwork (could not request refund for $1500 since the total invoice amount was $1k.

**Comment by DanutGavrus** [comment] 2023-07-31 07:40
@maddylewis $1k refunded!

**Comment by WoLewicki** [comment] 2023-07-31 15:58
>  @WoLewicki Did this issue exist before or does any new navigation change caused this? Also, do you have any idea about the direction in which we should look for a solution here?

I believe the shouldn't be any other new changes that could have caused it, so probably it was an untested flow. I haven't got too much context of it since I did not take part in implementing the deeplinking support. What about the solution proposed in the issue: https://github.com/Expensify/App/issues/23441#issuecomment-1656725230 ? Can you see any drawbacks of it @DanutGavrus ?

**Comment by pecanoro** [comment] 2023-08-04 15:51
Sorry, I missed this. I even checked the videos from the original PR and it seems it was working just fine back the, so something was introduced in between. Does this happen only on iOS? So I can test it as well.

**Comment by DanutGavrus** [comment] 2023-08-04 16:09
@pecanoro It happens on Android too.

**Comment by pecanoro** [comment] 2023-08-07 10:06
I can't reproduce it on Android on my phone, it's working well.

**Comment by pecanoro** [comment] 2023-08-07 10:08
@maddylewis Are you able to reproduce the potential regression on your iOS phone? It's working well for me on 1.3.50-2

**Comment by maddylewis** [comment] 2023-08-09 15:56
i am OOO until ~Aug 14. i can try to repro once i return or we can re-assign the bug label to have someone else try!

**Comment by abdulrahuman5196** [comment] 2023-08-13 13:25
I think it is a regression actually - https://github.com/Expensify/App/issues/23441#issuecomment-1676360013

**Comment by pecanoro** [comment] 2023-08-15 08:44
@abdulrahuman5196  Got it! It seems a contributor on the other issue found the root cause and a better solution for this issue and the regression. Are we having them fix it? If they confirmed the regression, we have to cut the payment for this one in half.

**Comment by DanutGavrus** [comment] 2023-08-15 09:56
@abdulrahuman5196 If the other contributor said in the [alternative Proposal](https://github.com/Expensify/App/issues/23441#issuecomment-1656725230) that removing only the change from that PR does not cause the original issue anymore, can't it be that something has changed meanwhile(which fixed the original Issue under the hood and created the new one), thus not being a regression? 🤷

**Comment by pecanoro** [comment] 2023-08-15 11:49
The PR still caused a regression since once the PR is reverted, the new bug disappears. However, if you can find me the PR that introduced those changes that might have broken your PR, I will reconsider it. So far that has been a theory but we have yet to find such PR.

**Comment by pecanoro** [comment] 2023-08-21 10:43
@maddylewis It's all yours for payment now!

**Comment by maddylewis** [comment] 2023-08-21 15:41
### Payments:
- [x] no reporting bonus
- [ ] @allroundexperts ($1500 - paid via NewDot)
- [ ] @DanutGavrus ($1000 - paid via Upwork - I originally paid $1500 and requested a $1k refund due to the regression, so @DanutGavrus is owed $1k at this point)

**Comment by DanutGavrus** [comment] 2023-08-21 15:42
@pecanoro 
> once the PR is reverted, the new bug disappears  

For some reason, same does the old bug.

> So far that has been a theory but we have yet to find such PR.

Sorry, I wanted to try that sooner, but I was not able to run the app on Android for some time until now. So, I've gathered these facts:
1. The old issue was that: If chat A is opened, chat B _won't_ get opened *at all* by deeplinking;
2. The new issue is that: If no chat is opened, chat B gets opened _twice_;
3. _Reverting_ the PR fixes both old & new issues.

These facts give the impression that what made **3.** possible, also added **one** extra navigation, thus it fixed **1.** by navigating _once_ instead of _not at all_, and created **2.** which navigates _twice_ instead of _once_ now.

> if you can find me the PR that introduced those changes that might have broken your PR, I will reconsider it  

What is bothering me is that I couldn't find the PR which fixed the original issue neither, and we know there must be something.  

Is anyone able to identify the change which fixed the old issue? I'd like to investigate if that is related to the new bug. Thanks!  

@allroundexperts What would be your opinion about these?
@pecanoro If this remains a regression, I 100% accept it! Just wanted to express why I'm unsure. Thank you!

**Comment by maddylewis** [comment] 2023-08-21 15:44
ahhh, thank you @allroundexperts! I needed some clarification on the status of payments for this one. 

I'll let @pecanoro respond to @DanutGavrus' comment before closing this one!

**Comment by maddylewis** [comment] 2023-08-24 18:11
@allroundexperts - i will trust your call on this one. double-checking that no payment should be issued to @DanutGavrus after they outlined these details - https://github.com/Expensify/App/issues/20624#issuecomment-1686573606

**Closed** 2023-08-25 19:41 UTC
Labels: External, Engineering, Daily, Awaiting Payment, Bug

**Comment by JmillsExpensify** [comment] 2023-08-30 04:49
Reviewed the details for @allroundexperts. $500 approved for payment via NewDot based on BZ summary.
