### ISSUE TITLE
IOU - Cursor appears at the random place in search contact page @aneequeahmad

### ISSUE THREAD

**Issue by kavimuru** [Expensify/App#11404] opened 2022-09-28 23:52 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:

1. Open app on IOS Chrome.
2. Tap + icon at the bottom right.
3. Tap split bill > enter amount > next.

## Expected Result:
Cursor is at the start of text input field when focused.

## Actual Result:
Cursor is at random place of text input when focused

## Workaround:
Unknown

## Platform:

Where is this issue occurring?

- Mobile Web - iOS chrome

**Version Number:** 1.2.9-0
**Reproducible in staging?:** Need reproduction
**Reproducible in production?:** Need reproduction
**Email or phone of affected tester (no customers):** 
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** 

https://user-images.githubusercontent.com/43996225/192908012-dd2b2f64-c830-4c86-85ef-58775035a436.MP4

**Expensify/Expensify Issue URL:** 
**Issue reported by:** @aneequeahmad
**Slack conversation:** https://expensify.slack.com/archives/C01GTK53T8Q/p1663244075830439

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by mnosov622** [comment] 2022-10-08 15:46
Hello !

I would love to work on this issue. Could you assign it to me, please ?

**Comment by slafortune** [comment] 2022-10-19 20:17
Unable to reproduce this on iOS16 - and latest version of Chrome -  

https://user-images.githubusercontent.com/11725910/196794915-82cd27ef-fa95-43e0-bb30-7df812296f1e.MP4

**Closed by slafortune** 2022-10-19 20:17 UTC
Labels: Daily, Needs Reproduction, Overdue

**Comment by aneequeahmad** [comment] 2022-10-26 20:22
**NOTE:** 

- I have checked that bug still exist in `v1.2.15-1`.

Video: 


https://user-images.githubusercontent.com/36359331/198128910-a20131b0-9ab7-4ce6-8859-df46b2fa3544.mov


- This bug is fixed in version `v1.2.15-2` in commit no `4dfd52af5`

Video: 


https://user-images.githubusercontent.com/36359331/198129028-4b11bc97-176d-4945-a721-02eeba055455.mov


Having said that I think i'm eligible for reporting bonus.

cc: @slafortune

**Comment by aneequeahmad** [comment] 2022-11-09 03:04
Reminder: @slafortune
