### ISSUE TITLE
[HOLD for payment 2024-08-27] [$250] Web - Split - Enter and CMD+Enter open user profile instead of splitting expense

### ISSUE THREAD

**Issue by m-natarajan** [Expensify/App#41848] opened 2024-05-08 13:59 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.71-4
**Reproducible in staging?:** Yes
**Reproducible in production?:** No
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** Applause Internal Team
**Slack conversation:**

## Action Performed:
1.Go to staging.new.expensify.com
2. Go to group chat.
3. Go to + > Split expense.
4. Enter amount > Next.
5. On confirmation page, hit Enter or CMD+Enter.

____

> [!NOTE] 
> In the same flow also from any of the amounts clicking Enter should confirm the split

## Expected Result:
Enter or CMD+Enter will split the expense.

## Actual Result:
Enter or CMD+Enter opens the profile of the last user under "Split amounts" list.

## Workaround:
Unknown
## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [X] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

https://github.com/Expensify/App/assets/38435837/4b36d5ff-8063-4d79-b6f8-4055e396ec0b

Add any screenshot/video evidence

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~010103e80036688f64</li>
        <li>Upwork Job ID: 1788212648413052928</li>
        <li>Last Price Increase: 2024-08-27</li>
<li>Automatic offers: </li>
<ul>
<li>abzokhattab | Contributor | 0</li>
<li>Krishna2323 | Contributor | 102703476</li>
</ul></li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @CortneyOfstad</details>

**Comment by mountiny** [comment] 2024-05-08 14:43
@Krishna2323 Thanks, which PR is this coming from?

**Comment by abzokhattab** [comment] 2024-05-08 14:54
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
 Split - Enter and CMD+Enter open user profile instead of splitting expense


### What is the root cause of that problem?
Two problems here: 
1. **pressing on enter doesn't confirm the split:**


we are intentionally making the priority of the settlement button as `1` [here](https://github.com/Expensify/App/blob/0b8aa3dfd3762a7baeacf4a6b6e203116869b2d1/src/components/MoneyRequestConfirmationList.tsx#L739-L752) which is not needed after [this PR](https://github.com/Expensify/App/pull/40386)

2. pressing ctrl + enter doesn't confirm: 
the ctrl + enter is enabled by the `OptionsSelector`, so on order to confirm instead of opening the user details 
we need to pass the `canSelectMultipleOptions ` as true [here](https://github.com/Expensify/App/blob/0b8aa3dfd3762a7baeacf4a6b6e203116869b2d1/src/components/MoneyRequestConfirmationList.tsx#L1088-L1103) ... the offending PR is [this](https://github.com/Expensify/App/pull/40386) 

https://github.com/Expensify/App/blob/e0b6a06d2f34f35cda96ccc4d05252ede111c732/src/components/OptionsSelector/BaseOptionsSelector.js#L325-L328

### What changes do you think we should make in order to solve the problem?
1. remove the `enterKeyEventListenerPriority={1}` prop [here](https://github.com/Expensify/App/blob/0b8aa3dfd3762a7baeacf4a6b6e203116869b2d1/src/components/MoneyRequestConfirmationList.tsx#L1088-L1103)
2. add the `canSelectMultipleOptions` prop to the `OptionsSelector` [here](https://github.com/Expensify/App/blob/0b8aa3dfd3762a7baeacf4a6b6e203116869b2d1/src/components/MoneyRequestConfirmationList.tsx#L1088-L1103)

**Comment by mountiny** [comment] 2024-05-08 14:58
I was just looking into that PR, I dont think we can revert it, we should look into a fix

**Comment by mountiny** [comment] 2024-05-08 15:00
@abzokhattab I like your proposal and explanation, can you please raise a fix PR?

**Comment by abzokhattab** [comment] 2024-05-08 15:02
Thanks, the PR would be ready in 30 mins

**Comment by abzokhattab** [comment] 2024-05-08 15:05
@Krishna2323 i agree we can check for the `onConfirmSelection` but this wont solve the `enter` key behavior

**Comment by mountiny** [comment] 2024-05-08 15:37
@Krishna2323 I have checked the code you have linked before and the latest change was couple months old, how could the condition be wrong and cause a deploy blocker? Could you highlight real root cause for the deploy blocker if you think the selected solution is incorrect? Thanks

I believe @abzokhattab is on a good path to resolve this

**Comment by mountiny** [comment] 2024-05-08 21:11
>  navigating to amount input using tab and pressing enter still navigates to user profile page and the PR is already using my solution for CMD+ENTER.

Actually not sure if this is a bug as its not clear what action should happen when pressing enter on the amount input and opening the details page seems like the most obvious one

> the PR is already using my solution for CMD+ENTER.

@Krishna2323 please rest assured that if your solution has been used, you will get compensated too.

Can you please collaborate with @abzokhattab to find the best solution for all the flows? thanks

**Comment by youssef-lr** [comment] 2024-05-08 21:13
@mountiny I think it's fine to demote this and take it to slack to figure out what to do when enter is pressed while an input is focused. What do you think?

**Comment by mountiny** [comment] 2024-05-08 21:23
@youssef-lr I dont think that is the main problem here, I agree that would not be a blocker.

I believe the OP behaviour though should remain a blocker as it breaks the possibility of getting through the request flow with Enter. When you are on the confirmation page, the Enter opens the account details page instead of continuing in the flow. What do you think?

**Comment by mountiny** [comment] 2024-05-08 21:26
But started a thread about the input field [here](https://expensify.slack.com/archives/C05RECHFBEW/p1715203534337909)

**Comment by abzokhattab** [comment] 2024-05-08 21:36
Please let me know about the expected behavior for the text field behavior when clicking on `enter` as. i think its another requirement.
1. should the focus move to the next input field? 
2. or should it create the split on enter?

 I lean towards the first point.

**Comment by youssef-lr** [comment] 2024-05-09 19:58
Update: we landed on pressing 'Enter' should just confirm the whole split

**Comment by mountiny** [comment] 2024-05-13 09:58
@abzokhattab @mananjadhav can you please confirm this is what you have implemented?

**Comment by CortneyOfstad** [comment] 2024-05-15 18:26
@abzokhattab any update on this?

**Comment by mananjadhav** [comment] 2024-05-19 17:25
@abzokhattab any updates on this one?

**Comment by abzokhattab** [comment] 2024-05-20 01:29
I spent some time trying to implement the additional request but couldn't achieve the desired outcome, for some reason it always selects the last participant when i press on the tab then press on enter without changing the amount, however if i change the amount, then press enter it confirms the split, do you have any idea how to fix it?@mananjadhav  



https://github.com/Expensify/App/assets/59809993/cf4456e7-3cc6-4f7a-834c-7c50e4f0d7d5

**Comment by CortneyOfstad** [comment] 2024-05-22 15:22
Bump @mananjadhav on the comment/question above ^^^ Thanks!

**Comment by mananjadhav** [comment] 2024-05-22 20:03
I'll take a look today. I'll need time to check this one.

**Comment by mananjadhav** [comment] 2024-06-04 10:54
> however if i change the amount, then press enter it confirms the split, do you have any idea how to fix it

I spent an hour or something on this and I didn't find a solution. I think if we don't have a proper solution covering the expected behavior, then we should open up for proposals. wdyt @mountiny ?

**Comment by mountiny** [comment] 2024-06-04 16:05
Updated

**Comment by b4s36t4** [comment] 2024-06-04 17:39
I also tried to replicated this, but I wasn't able to. The expense got created but there's a new issue I found i.e `CMD + Enter` is not working while `CTRL+Enter` is working. Anyone can replicateD?

**Comment by mananjadhav** [comment] 2024-06-05 14:48
I tried reproducing this on two profiles and different devices. `Enter` did submit the Split Expense. It didn't open the profile of the last user.

`CMD+Enter` didn't do anything, is that expected?

https://github.com/Expensify/App/assets/3069065/32477192-ad93-46a0-a00f-4bbafdd4e022


https://github.com/Expensify/App/assets/3069065/ecae7d05-ca8f-4654-91d4-4ba6ce4f13f1

**Comment by wildan-m** [comment] 2024-06-07 02:03
## Proposal

### Please re-state the problem that we are trying to solve in this issue.

Web - Split - Enter and CMD+Enter open user profile instead of splitting expense

### What is the root cause of that problem?

There is a keyboard shortcut conflict between `SelectionList` and `KeyboardShortcutComponent`. When we press tab and point to one of the `selectionItem`'s amount input, it triggers `selectRow` instead of submitting the form.

### What changes do you think we should make in order to solve the problem?

If we only wish to use Enter as a shortcut key, adding the `disableKeyboardShortcuts` prop to `SelectionList` in `MoneyRequestConfirmationList` is sufficient. 

However, if we also want to include CMD+Enter, we can add the `ctrl_enter` key in `src/components/Button/index.tsx`. (This can be activated by feature flag if required).

Add:

```
    useKeyboardShortcut(CONST.KEYBOARD_SHORTCUTS.CTRL_ENTER, keyboardShortcutCallback, config);
```

[Branch to test.](https://github.com/Expensify/App/compare/main...wildan-m:App:wildan/fix/41848-enter-shortcut-key-for-split-bill?expand=1)

### What alternative solutions did you explore? (Optional)

**Comment by mountiny** [comment] 2024-06-10 09:08
@mananjadhav how are the proposals lookin

**Comment by mananjadhav** [comment] 2024-06-10 10:18
> @mananjadhav how are the proposals lookin

Can you or @CortneyOfstad help confirm [this](https://github.com/Expensify/App/issues/41848#issuecomment-2150257692)?

**Comment by mountiny** [comment] 2024-06-10 10:24
@mananjadhav I think the CMD+ Enter should still split the expense too

**Comment by mananjadhav** [comment] 2024-06-10 10:27
Cool. I'll check both the proposals again.

@wildan-m @Krishna2323 Do you have the info on why it works on Enter but not for Cmd+Enter?

**Comment by mananjadhav** [comment] 2024-06-11 22:16
@Krishna2323's [proposal](https://github.com/Expensify/App/issues/41848#issuecomment-2148079251) looks good to me. The only thing is if there's a way for us to avoid unnecessary props like `useKeyboardShortcuts`.

🎀 👀 🎀 C+ reviewed.

**Comment by wildan-m** [comment] 2024-06-11 23:08
@mananjadhav what's your opinion about [my proposal](https://github.com/Expensify/App/issues/41848#issuecomment-2153722026)?

**Comment by mananjadhav** [comment] 2024-06-12 17:56
> @mananjadhav what's your opinion about [my proposal](https://github.com/Expensify/App/issues/41848#issuecomment-2153722026)?

@wildan-m The proposal was on the similar lines to the one accepted and I don't think we should be updating the core Button.tsx.

**Comment by mountiny** [comment] 2024-06-14 22:03
@Krishna2323 when could we expect the PR? Thanks!

**Comment by wildan-m** [comment] 2024-06-18 05:56
> I don't think we should be updating the core Button.tsx.

@mananjadhav why? we can add `shouldEnableCtrlCmd` prop if don't want to use it in other places.

**Comment by CortneyOfstad** [comment] 2024-06-25 13:57
@Krishna2323 any update on the PR?

Also, @mananjadhav any update on the comment/question [here](https://github.com/Expensify/App/issues/41848#issuecomment-2175073294)?

**Comment by mananjadhav** [comment] 2024-06-26 22:18
I'll need a day to review the questions.

**Comment by CortneyOfstad** [comment] 2024-07-03 14:23
@mananjadhav an update on the responses to @Krishna2323's questions?

**Comment by mananjadhav** [comment] 2024-07-07 22:34
I haven't got chance to get to this. I was finishing some development. I'll have it prioritized for tomorrow.

**Comment by mountiny** [comment] 2024-07-22 21:30
Oof we had to revert the PR. Lets try to look into some simplification here

**Comment by wildan-m** [comment] 2024-07-23 02:05
@mananjadhav @mountiny Would you mind to re-consider [my proposal](https://github.com/Expensify/App/issues/41848#issuecomment-2153722026)? my proposal will not cause [this issue](https://github.com/Expensify/App/pull/43794#issuecomment-2243769779), we can have `shouldEnableCtrlEnterShortcut` if it will only apply for specific buttons.

**Comment by lschurr** [comment] 2024-08-04 20:11
New PR is still open: https://github.com/Expensify/App/pull/46278

**Comment by mountiny** [comment] 2024-08-08 23:08
PR was merged

**Comment by mananjadhav** [comment] 2024-08-20 21:10
I think this is ready for payout, but we've had regression on this one. 

cc - @CortneyOfstad @mountiny

**Comment by mananjadhav** [comment] 2024-08-26 17:20
@CortneyOfstad @mountiny quick bump if you missed.

**Comment by mountiny** [comment] 2024-08-27 00:03
@lschurr @CortneyOfstad This is ready to be paid. This was originally for $500, but there was a regression so we are cutting the price in half. 

$250 to @mananjadhav and to @Krishna2323 please

**Comment by lschurr** [comment] 2024-08-27 15:57
Payment summary:

- Contributor: $250 @Krishna2323 ([Paid in Upwork](https://www.upwork.com/nx/wm/workroom/37536361/overview?nav_dir=pop))
- Reviewer: $250 @mananjadhav (Please request via NewDot)

**Comment by CortneyOfstad** [comment] 2024-08-27 18:14
Thank you @lschurr!!

**Closed by CortneyOfstad** 2024-08-27 18:14 UTC
Labels: External, Engineering, Daily, Overdue, Awaiting Payment, Bug

**Comment by garrettmknight** [comment] 2024-08-29 13:34
$250 approved for @mananjadhav
