### ISSUE TITLE
 iOS Hybrid - App crashes when switching to Expensify Classic after logging in to a new account

### ISSUE THREAD

**Issue by IuliiaHerets** [Expensify/App#54169] opened 2024-12-15 19:37 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 9.0.76-6
**Reproducible in staging?:** Yes
**Reproducible in production?:** No
**If this was caught on HybridApp, is this reproducible on New Expensify Standalone?:** No, reproducible on hybrid only
**If this was caught during regression testing, add the test name, ID and link from TestRail:** Exp
**Email or phone of affected tester (no customers):** applausetester+23082038203a2@applause.expensifail.com
**Issue reported by:** Applause Internal Team
**Device used:** iPhone 15 Pro Max / iOS 18.2
**App Component:** Other

## Action Performed:
Precondition:
- Hybrid app must be logged out from ND app, not OD.

1. Go to staging.expensify.com
2. Select "Manage expenses for a small team".
3. Enter a new account and sign up.
4. After web app redirects to ND, launch iOS hybrid app and log in to the same account.
5. On iOS hybrid app, go to account settings.
6. Tap Switch to Expensify Classic.

## Expected Result:
App will not crash.

## Actual Result:
App crashes when switching to Expensify Classic after logging in to a new account.

## Workaround:
Unknown

## Platforms:
- [ ] Android: Standalone
- [ ] Android: HybridApp
- [ ] Android: mWeb Chrome
- [ ] iOS: Standalone
- [x] iOS: HybridApp
- [ ] iOS: mWeb Safari
- [ ] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos
[Bug6694850_1734270273609!Expensify-2024-12-15-212502.txt](https://github.com/user-attachments/files/18141814/Bug6694850_1734270273609.Expensify-2024-12-15-212502.txt)

https://github.com/user-attachments/assets/c57a18ee-8cc1-4498-9dda-6f3f07b6b4bd

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by mallenexpensify** [comment] 2024-12-16 16:46
@luacmartins , is this being addressed in the fireroom? 
[#fireroom-2024-12-15-android-hybridapp-crashing](https://expensify.enterprise.slack.com/archives/C08571R1CBU)

**Comment by michaelkwardrop** [comment] 2024-12-16 17:21
This issue is being discussed [here](https://expensify.slack.com/archives/C01GTK53T8Q/p1734291476481179)

**Comment by luacmartins** [comment] 2024-12-16 19:39
@IuliiaHerets I'm unable to reproduce the crash. Could you please ask for a re-test?

**Comment by luacmartins** [comment] 2024-12-16 19:57
I'm currently stuck trying to run hybrid app locally. Discussing it [here](https://expensify.slack.com/archives/C03TQ48KC/p1734020907310509). Additionally:

1. I cannot reproduce the issue on my physical device with the staging App version on testflight
2. I asked Applause for a retest [here](https://github.com/Expensify/App/issues/54169#issuecomment-2546530104)
3. I[ asked the open source community](https://expensify.slack.com/archives/C01GTK53T8Q/p1734378164472369) to try to reproduce the issue too
4. I asked SWM for help with the blocker [here](https://expensify.slack.com/archives/C04878MDF34/p1734376440778899)

**Comment by grgia** [comment] 2024-12-16 20:09
I'm also unable to reproduce on my phone on testflight

**Comment by IuliiaHerets** [comment] 2024-12-16 20:40
@luacmartins Tester still can repro the issue, build - 76-6

https://github.com/user-attachments/assets/2ad7c0f3-78b4-45a4-85bb-b4e5c6a0c0cd

**Comment by IuliiaHerets** [comment] 2024-12-16 21:06
I can reproduce this crash on my device too, iPhone XR/iOS 17.3

https://github.com/user-attachments/assets/8ccaa884-6bad-415a-a9e9-1bb8dcff6966

**Comment by luacmartins** [comment] 2024-12-16 22:09
We're still discussing this issue [here](https://expensify.slack.com/archives/C01GTK53T8Q/p1734291476481179), but we can't rule out the API side of things yet either since we can't really reproduce it internally and don't really know what's causing the issue.

**Comment by rafecolton** [comment] 2024-12-17 02:41
What's the latest on this?

**Comment by luacmartins** [comment] 2024-12-17 02:50
No meaningful progress yet. We haven't been able to reproduce the issue internally. Additionally:

1. We can't find any logs for Applause's crash in Firebase, nor the [JS dashboard](https://www.expensify.com/?exitTo=_support%2Fmobile%2F%3Fpage%3DcrashTypes&email=cmartins%40expensify.com)
2. Looking at the diff, this is the only PR that kind of stands out, but we can't confirm since we can't reproduce the issue - https://github.com/Expensify/App/pull/53374

**Comment by staszekscp** [comment] 2024-12-17 07:51
I also tried to reproduce the issue, but I was unable to do that. Maybe it's an issue with a specific account type?

**Comment by mjasikowski** [comment] 2024-12-17 11:19
I can reproduce this consistently.
Tried with [michal+54169@expensifail.com](mailto:michal+54169@expensifail.com) and [michal+54169+1@expensifail.com](mailto:michal+54169+1@expensifail.com), both crashed.

**Comment by staszekscp** [comment] 2024-12-17 11:22
Could you get logs so we can see the stacktrace? It seems like it may be affecting the `expensifail.com` domain 🤔

**Comment by Julesssss** [comment] 2024-12-17 11:46
I can also reproduce on @expensifail, but how can I export logs when the device has crashed? I don't see the share button when the app re-opens 😕 

![Screenshot 2024-12-17 at 11 45 47](https://github.com/user-attachments/assets/768d7d8a-fe2a-42a9-9c6f-dba8a92c9619)

**Comment by staszekscp** [comment] 2024-12-17 11:58
Thanks a lot @mjasikowski! Unfortunately it seems like we'll need some assist to press a verification link and send us a magic code from an expensifail.com domain to get better logs on a local build. Could you do that for us?

**Comment by Julesssss** [comment] 2024-12-17 11:59
I verified that this was introduced by `9.0.76-6` and I'm reverting some Prs to test further. 

if anyone wants to reproduce, sign into `jules+374634` and ask me for the magic code

**Comment by staszekscp** [comment] 2024-12-17 12:00
@Julesssss Is it constantly reproducible every time you try to switch on this account?

**Comment by Julesssss** [comment] 2024-12-17 12:07
> @Julesssss Is it constantly reproducible every time you try to switch on this account?

Yeah it is reproducable from first authentication repeatedly until you re-authenticate. I created an account for you, and will share magic code via dm.

**Comment by grgia** [comment] 2024-12-17 12:21
@Julesssss when you reopen after the crash, what do you see? Im unable to log out of the account I create to test this yesterday on mobile staging.expensify.com

**Comment by Julesssss** [comment] 2024-12-17 12:23
> Im unable to log out of the account I create to test this yesterday on mobile staging.expensify.com

So you can't sign out from mobile app? Or mWeb?

To clarify I created the account on staging web. Didn't unauthenticate. Then signed into HybridApp iOS

**Comment by grgia** [comment] 2024-12-17 12:28
Yesterday I did it all from my phone (so Classic MWeb is borked rn), I might have authenticated it? I'm not sure

**Comment by Julesssss** [comment] 2024-12-17 12:29
Ughh, with a new test user it only crashes on first switch... frustrating because previously it reproduced on every switch. @grgia when I reopened the app after crash I land in OldApp experience, then had to switch twice to reproduce crash.

**Comment by grgia** [comment] 2024-12-17 12:35
Wait... how did you manage to not authenticate?

I just tried from mobile web `production` and encountered this screen. Is this missing for expensifail now on `staging`?

![IMG_2001](https://github.com/user-attachments/assets/decec8ae-b4f2-4808-ae8c-ea9c56a3a815)

**Comment by grgia** [comment] 2024-12-17 12:36
Even clearing my phone's cache doesn't fix it. Staging is broken for me on wMeb 🙃

**Comment by Julesssss** [comment] 2024-12-17 12:38
I don't see any step that requires mWeb for testing this flow, am I missing it?

**Comment by grgia** [comment] 2024-12-17 12:38
> After web app redirects to ND
no you're right I think I misinterpretted this one @Julesssss

**Comment by Julesssss** [comment] 2024-12-17 12:41
If you guys have been using mWeb, then perhaps a critical step for reproduction is to use this flow?

![Screenshot 2024-12-17 at 12 41 09](https://github.com/user-attachments/assets/74943c23-5227-4e81-aafb-ea7f82d61102)

**Comment by Julesssss** [comment] 2024-12-17 12:45
The sign-out case sounds slightly different, but yeah that's the post-crash Modal I was seeing.

**Comment by grgia** [comment] 2024-12-17 12:47
Wait okay, this is "Production?" but the last 60 min Im seeing a lot of crashes
<img width="941" alt="image" src="https://github.com/user-attachments/assets/3031106f-6924-44ef-b246-af85ea81737a" />

**Comment by Julesssss** [comment] 2024-12-17 12:49
@grgia that's Android crashes, you need to switch to iOS HybridApp release, but it's useless. This version code isn't even available in the filter in Crashlitics, as it detected zero crashes.

**Comment by Julesssss** [comment] 2024-12-17 12:56
I see a couple of crashes in the iOS Firebase console after removing the top level `Type=Crash` filter and it's possible the crash is being reported this way due to yapl...

![Screenshot 2024-12-17 at 12 54 04](https://github.com/user-attachments/assets/b3ae45b5-7ecb-4364-9017-293befbfb03c)
![Screenshot 2024-12-17 at 12 52 20](https://github.com/user-attachments/assets/50523621-e210-4257-a522-36c02a3f9248)

Still though, nothing is reported against version `9.0.76-6` 😠😠 They are also very generic and often have the same stack trace for many different issues. Worth taking a look at though as there is a spike: 

```

```

**Comment by grgia** [comment] 2024-12-17 13:01
Have we confirmed if this is only impacting `expensifail` or if it impacts other domains?

**Comment by luacmartins** [comment] 2024-12-17 14:08
@grgia those logs go to App store connect, you can (usually) see them here - https://appstoreconnect.apple.com/teams/69a6de6e-91ff-47e3-e053-5b8c7c11a4d1/apps/1530278510/testflight/crashes?appPlatform=IOS&preReleaseVersionId=2d71a0f1-d5cd-4089-8879-76e7bbc30d76&sort=-timestamp

**Comment by grgia** [comment] 2024-12-17 14:09
@luacmartins my version is `v9.0.76.7`

**Comment by luacmartins** [comment] 2024-12-17 14:14
Yea, there's nothing for 9.0.76.X. The last report I see is from Nov 29 😂

**Comment by luacmartins** [comment] 2024-12-17 16:22
We have a fireroom for this one https://expensify.enterprise.slack.com/archives/C085GD1ET8A

**Comment by rafecolton** [comment] 2024-12-17 17:34
Going to remove the web deploy blocker label per discussion [here](https://expensify.slack.com/archives/C085GD1ET8A/p1734456808965239?thread_ts=1734456715.036019&cid=C085GD1ET8A)

**Comment by luacmartins** [comment] 2024-12-17 21:25
@mvtglobally was this crash found during regular regression tests?

**Comment by mvtglobally** [comment] 2024-12-17 21:40
@luacmartins this is not linked to a particular TC steps but rather found while running regression as an exploratory issue.

**Comment by luacmartins** [comment] 2024-12-17 21:43
@mvtglobally can you test the latest build? I think we fixed it.

**Comment by IuliiaHerets** [comment] 2024-12-17 22:14
I cannot reproduce on the latest build, yesterday in my device it was repro (iPhone XR/iOS 17.3)

https://github.com/user-attachments/assets/5ac7f34c-60ea-471e-8242-c551b34e73dc

**Comment by luacmartins** [comment] 2024-12-17 22:22
Thanks for confirming! This issue is fixed. Closing.

**Closed by luacmartins** 2024-12-17 22:22 UTC
Labels: Reviewing, DeployBlockerCash, Engineering, Weekly, Bug
