### ISSUE TITLE
Session not expired properly

### ISSUE THREAD

**Issue by mvtglobally** [Expensify/App#24087] opened 2023-08-03 04:01 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Login app with any email.
2. Then open second day after 24 hours. 
3. Try to do any thing like chat or payment the you will redirect login.

## Expected Result:
If session expired then you automatically moved to login page not the Dashboard.

## Actual Result:
Session not expired without doing any action for 24hrs.

## Workaround:
unknown 
## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [X] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 
**Reproducible in staging?:** needs repro
**Reproducible in production?:** needs repro 
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation 

https://github.com/Expensify/App/assets/43995119/7113971a-523f-41bd-a9ec-e7c658270ff0

https://github.com/Expensify/App/assets/43995119/2e2eb8fd-e6c6-455d-8e5b-168b637f3c87

**Expensify/Expensify Issue URL:**
**Issue reported by:** [snsaqib777@gmail.com](mailto:snsaqib777@gmail.com)
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1690814791798619

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by mvtglobally** [comment] 2023-08-03 04:02
Not sure on the expected behavior, nor able to keep off account open for 24hrs to validate 
Please double check if this is valid

**Comment by pac-guerreiro** [comment] 2023-08-03 11:19
From my understanding of the current code, every time there's a request with an invalid auth token, the token gets revalidated and the user remains authenticated 😄

**Comment by michaelhaxhiu** [comment] 2023-08-03 21:38
Closing this bug report as their seems to be a core misunderstanding on how session length and timeouts work. Please make sure to refresh on the Expected behavior and clarify the nature of the bug here.

**Closed by michaelhaxhiu** 2023-08-03 21:38 UTC
Labels: Daily, Needs Reproduction, Bug
