### ISSUE TITLE
[$1000] Incorrect SMS validation message received for phone account 

### ISSUE THREAD

**Issue by kavimuru** [Expensify/App#19929] opened 2023-06-01 03:09 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Create a new phone account
2. Verify the validation SMS received

## Expected Result:
Validation sms should be 
```
Hi David, please tap this magic link to sign in to Expensify:

https://www.expensify.com/v/8821761/586223

Alternatively, enter this magic code manually:

586223
```

See you soon!
## Actual Result:
```
https://www.expensify.com/v/8821761/586223

Or you can enter the following magic code: 586223
```
## Workaround:
unknown
## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [ ] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation

**Expensify/Expensify Issue URL:**
**Issue reported by:** ~@quinthar~ @dhanashree-sawant https://github.com/Expensify/App/issues/19760#issuecomment-1572290634
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1685350929001069

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~015d44c5e789650d6e</li>
        <li>Upwork Job ID: 1668626933189160960</li>
        <li>Last Price Increase: 2023-06-13</li>
    </ul>
</details>

**Comment by flodnv** [comment] 2023-06-01 14:43
Duplicate of https://github.com/Expensify/Expensify/issues/242614#issuecomment-1557797706

**Comment by michaelhaxhiu** [comment] 2023-06-01 16:39
<img width="394" alt="image" src="https://github.com/Expensify/App/assets/13206896/4f2c6b26-19d1-4241-bf4d-2e2fce7a3edb">

**Comment by michaelhaxhiu** [comment] 2023-06-01 16:41
reminder that we will pay bug reporting bonus to @dhanashree-sawant

**Comment by flodnv** [comment] 2023-06-01 19:45
PR sent

**Comment by flodnv** [comment] 2023-06-12 22:20
this is fixed

**Comment by dhanashree-sawant** [comment] 2023-06-13 07:32
Hi @flodnv, reporting bonus is left. Can you have a look once?

**Comment by michaelhaxhiu** [comment] 2023-06-13 14:29
Gotta leave the GH open until payment is processed, otherwise the BZ will not know 🙇

**Comment by michaelhaxhiu** [comment] 2023-06-13 14:30
labelling external so the automation makes the upwork job for me

**Comment by michaelhaxhiu** [comment] 2023-06-13 14:34
paid.

**Closed by michaelhaxhiu** 2023-06-13 14:34 UTC
Labels: Daily, Bug
