### ISSUE TITLE
 iOS - App is slow and device heats up easily when performing basic functions

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#41534] opened 2024-05-02 20:17 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.70-0
**Reproducible in staging?:** Y
**Reproducible in production?:** N
**If this was caught during regression testing, add the test name, ID and link from TestRail:** N/A
**Issue reported by:** Applause - Internal Team

## Action Performed:
1. Launch New Expensify app
2. Log in to account that have some reports
3. Open the report
4. Perform a few basic actions such as closing the report while it is loading, submitting expense, opening expense report etc

## Expected Result:
App will not slow down and heat up while performing basic functions

## Actual Result:
App slows down and heats up easily while performing basic functions. It is very laggy compared to production app.
Sometimes when closing report that is still loading, it reopens

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [x] Android: mWeb Chrome
- [x] iOS: Native
- [x] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details> 

https://github.com/Expensify/App/assets/78819774/dd5e8beb-308a-4faf-8400-d3a3d9a4a883

[Bug6469319_1714679828436!Profile_trace_for_1.4.70-0.cpuprofile](https://github.com/Expensify/App/files/15193508/Bug6469319_1714679828436.Profile_trace_for_1.4.70-0.cpuprofile)

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by lanitochka17** [comment] 2024-05-02 20:18
@deetergp  FYI I haven't added the External label as I wasn't 100% sure about this issue. Please take a look and add the label if you agree it's a bug and can be handled by external contributors

**Comment by lanitochka17** [comment] 2024-05-02 20:20
Production:

https://github.com/Expensify/App/assets/78819774/9141727d-82b6-4552-b6f1-7fcf72c42f7e

**Comment by francoisl** [comment] 2024-05-03 01:40
Checked our logs to see if there was any noticeable increase in the perf measurements we did recently. We don't log the app versions so I had to group by date instead, here's the data:

<details>
<summary>Details</summary>

Internal log search: `blob:"SendPerformanceTiming API Request" AND blob:ios.staging.new.expensify*`


```json
{
    "ios.staging.new.expensify.switch_report.warm": {
        "2024-05-03": {
            "avgMs": 755.71,
            "dataPointsCount": 21
        },
        "2024-05-02": {
            "avgMs": 838.05,
            "dataPointsCount": 361
        },
        "2024-05-01": {
            "avgMs": 1102.53,
            "dataPointsCount": 350
        },
        "2024-04-30": {
            "avgMs": 251.1,
            "dataPointsCount": 418
        }
    },
    "ios.staging.new.expensify.chat_render": {
        "2024-05-03": {
            "avgMs": 416.8,
            "dataPointsCount": 41
        },
        "2024-05-02": {
            "avgMs": 293.47,
            "dataPointsCount": 833
        },
        "2024-05-01": {
            "avgMs": 76.67,
            "dataPointsCount": 899
        },
        "2024-04-30": {
            "avgMs": 84.61,
            "dataPointsCount": 1124
        }
    },
    "ios.staging.new.expensify.trie_initialization": {
        "2024-05-03": {
            "avgMs": 193,
            "dataPointsCount": 10
        },
        "2024-05-02": {
            "avgMs": 197.47,
            "dataPointsCount": 161
        },
        "2024-05-01": {
            "avgMs": 175.2,
            "dataPointsCount": 161
        },
        "2024-04-30": {
            "avgMs": 192.06,
            "dataPointsCount": 141
        }
    },
    "ios.staging.new.expensify.calc_most_recent_last_modified_action": {
        "2024-05-03": {
            "avgMs": 3.22,
            "dataPointsCount": 94
        },
        "2024-05-02": {
            "avgMs": 208.54,
            "dataPointsCount": 1229
        },
        "2024-05-01": {
            "avgMs": 83.99,
            "dataPointsCount": 1351
        },
        "2024-04-30": {
            "avgMs": 4598.3,
            "dataPointsCount": 1180
        }
    },
    "ios.staging.new.expensify.homepage_initial_render": {
        "2024-05-03": {
            "avgMs": 181.06,
            "dataPointsCount": 17
        },
        "2024-05-02": {
            "avgMs": 117.65,
            "dataPointsCount": 235
        },
        "2024-05-01": {
            "avgMs": 7206.46,
            "dataPointsCount": 233
        },
        "2024-04-30": {
            "avgMs": 76.06,
            "dataPointsCount": 250
        }
    },
    "ios.staging.new.expensify.search_render": {
        "2024-05-03": {
            "avgMs": 1875,
            "dataPointsCount": 1
        },
        "2024-05-02": {
            "avgMs": 701.85,
            "dataPointsCount": 48
        },
        "2024-05-01": {
            "avgMs": 441.14,
            "dataPointsCount": 37
        },
        "2024-04-30": {
            "avgMs": 393.02,
            "dataPointsCount": 58
        }
    },
    "ios.staging.new.expensify.load_search_options": {
        "2024-05-03": {
            "avgMs": 215,
            "dataPointsCount": 1
        },
        "2024-05-02": {
            "avgMs": 402.35,
            "dataPointsCount": 65
        },
        "2024-05-01": {
            "avgMs": 227.45,
            "dataPointsCount": 69
        },
        "2024-04-30": {
            "avgMs": 244.49,
            "dataPointsCount": 144
        }
    },
    "ios.staging.new.expensify.switch_report.cold": {
        "2024-05-03": {
            "avgMs": 5090,
            "dataPointsCount": 1
        },
        "2024-05-02": {
            "avgMs": 7534.63,
            "dataPointsCount": 43
        },
        "2024-05-01": {
            "avgMs": 2269.1,
            "dataPointsCount": 39
        },
        "2024-04-30": {
            "avgMs": 1051.89,
            "dataPointsCount": 73
        }
    }
}
```

</details>

There are significant increases for `ios.staging.new.expensify.chat_render` and `ios.staging.new.expensify.load_search_options`, but they're based on fewer measurements (especially the latter, only 1)

Looking at all the logs for `ios.staging.new.expensify.chat_render`, there are few outlier values for the account `applausetester+vd_ios050224@applause.expensifail.com` today that make the average go up, but other than that nothing out of the ordinary 🤔

I don't have a physical iPhone and don't see anything weird on a simulator, @deetergp any chance you can try with a HT account on browserstack (or a physical iphone if you have one)

**Comment by deetergp** [comment] 2024-05-03 15:43
I've spent the last 20 minutes in the latest iOS staging build on my iPhone 13 Pro and did not notice any additional heat coming from the device. I did enable profiling and local logging for some of it but have little idea of what to make of any of it 😅 

[logs-2024-05-03 15_36_23.782.txt](https://github.com/Expensify/App/files/15202075/logs-2024-05-03.15_36_23.782.txt)
[App_Info_1.4.70-0.json](https://github.com/Expensify/App/files/15202076/App_Info_1.4.70-0.json)
[Profile_trace_for_1.4.70-0.cpuprofile](https://github.com/Expensify/App/files/15202077/Profile_trace_for_1.4.70-0.cpuprofile)

**Comment by mallenexpensify** [comment] 2024-05-03 16:50
My iOS app is wonky, chat's not loading or sending.  It might be heating up, it also appears to be sucking battery life, dropped 3 or 4 percentage points in less than 5 mins (which could be from excessive loading?)

**Comment by francoisl** [comment] 2024-05-03 20:27
@mallenexpensify any chance you could try [with this ad-hoc build](https://github.com/Expensify/App/pull/41612#issuecomment-2093705387)? It's kind of a shot in the dark, but there was a known issue with a recent update for react-native-onyx, and I'm wondering if it could also explain the performance changes you've been seeing.

**Comment by marcaaron** [comment] 2024-05-06 23:12
Just a heads up I downloaded the latest TestFlight and gave it a spin. I'm not experiencing any of the issues described here. Some `OpenReport` calls are still slow, but nothing obvious like a hot phone, jank, or battery dropping rapidly.

Waiting for @mallenexpensify to test as well.

**Comment by marcaaron** [comment] 2024-05-07 00:37
Realizing I was not on the latest 😄 Testing on the latest now... @mallenexpensify maybe you can do the same.

**Comment by marcaaron** [comment] 2024-05-07 00:57
Ok same result - the app seems fine (APIs are a bit slow but that's expected). This is now our last blocker. If nobody can reproduce any noticeable performance difference between staging and production I would motion to take off the blocker label. But will wait a bit to give QA and @mallenexpensify a chance to test.

**Comment by marcaaron** [comment] 2024-05-07 01:26
Making a judgment call here and choosing to not block the deploy on this one. We had Matt test on the latest staging compared to production and both are pretty slow right now.

**Comment by deetergp** [comment] 2024-05-08 14:48
Has anyone actually been able to recreate this or is it a red herring?

**Comment by mallenexpensify** [comment] 2024-05-09 18:05
On 1.4.72 on iOS, just tested again, was at 94% at 10:56. did a bunch of stuff and it's 91% at 11:04 and the phone is warmer than when started. BUT... I _feel_ like it's better?  App feels a lil faster

**Comment by deetergp** [comment] 2024-05-10 16:25
I am going to close this. We've deployed a few times since this issue was created and nobody seems to be complaining about it.

**Closed by deetergp** 2024-05-10 16:25 UTC
Labels: Engineering, Daily

**Comment by mallenexpensify** [comment] 2024-05-12 19:52
Do you think it's _worth_ it to post in #newdot-performance in case others want to review or reopen? I'm on fence, mainly cuz this issue is hella vague
