### ISSUE TITLE
[$500] The first character of room name gets removed for Task rooms/reports

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#30011] opened 2023-10-19 18:01 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.3.87.0
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** @aman-atg
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1697722321664739

## Action Performed:
1. Go to staging
2. Go to any workspace room (#admins/#announce,etc)
3. Click on Actions > Assign task
4. Enter a title in the input field (e.g., 'test') > Next > Confirm task.
5. Click on the header > Details > Settings > Room name.
6. Observe that only 'est' is visible and a "#" is added

## Expected Result:
The complete value should be shown

## Actual Result:
The first character is removed automatically and a “#” is added

## Workaround:
Unknown 

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [x] Android: mWeb Chrome
- [x] iOS: Native
- [x] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos
<details>
<summary>Android: Native</summary>

 

https://github.com/Expensify/App/assets/93399543/c1c644f2-c4a6-4329-99b3-63bc989a648e

</details>

<details>
<summary>Android: mWeb Chrome</summary>

 

https://github.com/Expensify/App/assets/93399543/5fd508fb-1cb0-4ec8-987a-226f64126596

</details>

<details>
<summary>iOS: Native</summary>

 

https://github.com/Expensify/App/assets/93399543/47dc0a2c-2c59-4fa5-afd8-f46c95ab48df

</details>

<details>
<summary>iOS: mWeb Safari</summary>

 

https://github.com/Expensify/App/assets/93399543/37519b92-efe5-4c6d-87f4-ac29af657741

</details>

<details>
<summary>MacOS: Chrome / Safari</summary>

 

https://github.com/Expensify/App/assets/93399543/092eeee6-f9bf-4cb3-a438-e1398b48ec5b

</details>

<details>
<summary>MacOS: Desktop</summary>

 

https://github.com/Expensify/App/assets/93399543/64242e54-11a5-42d6-9b79-547085d6a2a2

</details> requested

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~0136afa321dd7291bc</li>
        <li>Upwork Job ID: 1715065744541163520</li>
        <li>Last Price Increase: 2023-10-19</li>
    </ul>
</details>

**Comment by kbecciv** [comment] 2023-10-19 20:00
@aman-atg Reported the issue first here https://expensify.slack.com/archives/C049HHMV9SM/p1697722321664739

**Comment by esh-g** [comment] 2023-10-20 01:29
# Proposal

## Please re-state the problem
Task - Room name option is shown for task report settings and task name is replaced with # 

## What is the root cause of the problem?
For a normal task, we show the room name but don't allow it to be edited as it is same as task title.
<img width="373" alt="Screenshot 2023-10-19 at 10 52 03 PM" src="https://github.com/Expensify/App/assets/77237602/b8b8b67d-a7df-43d7-bc31-4b00e43fb8a5">

But this is what the settings show for a task with a policy room as its parent:
<img width="379" alt="Screenshot 2023-10-20 at 12 31 50 AM" src="https://github.com/Expensify/App/assets/77237602/dd1bdb9c-c871-4130-8b6f-0e963bfc1b3b">

We are able to edit the 'who can post' and 'room name' field but we should not be able to do so.

This is decided the by this method:
https://github.com/Expensify/App/blob/302cebf14c4e0fcd6570ac66e9d85a1ca0212ae6/src/libs/ReportUtils.js#L3739-L3748

Since a normal task has no `policy`, this function returns true and we are unable to edit it.

But when we create a task in a policy room, this `policy` is defined and this function does not return true, leading to this issue.

## What changes should be made to fix this?
We should change this condition here:
https://github.com/Expensify/App/blob/302cebf14c4e0fcd6570ac66e9d85a1ca0212ae6/src/libs/ReportUtils.js#L3740

**Option 1**
We can change the `isChatThread(report)` to `isThread(report)`. This will exclude all tasks as well...

**Option 2**
We can change the condition to include `|| isTaskReport(report)`

This will make sure that we are not able to edit the room name even by using deeplink as the `RoomNamePage` also uses this method to show the not found page:
https://github.com/Expensify/App/blob/302cebf14c4e0fcd6570ac66e9d85a1ca0212ae6/src/pages/settings/Report/RoomNamePage.js#L88

**We should also make sure that `who can post` item is also guarded properly like this:**

1. We should create a function for `writeCapability` like we have for renaming in `ReportUtils` like this:
```js
function canEditWriteCapability(report, policy) {
    return PolicyUtils.isPolicyAdmin(policy) && !isAdminRoom(report) && !isArchivedRoom(report) && !isThread(report);
}
```
2. We can modify the condition here:
https://github.com/Expensify/App/blob/302cebf14c4e0fcd6570ac66e9d85a1ca0212ae6/src/pages/settings/Report/ReportSettingsPage.js#L76
```js
    const shouldAllowWriteCapabilityEditing = useMemo(() => !ReportUtils.canEditWriteCapability(report, linkedWorkspace), [report, linkedWorkspace]);
```

3. We should change the condition in `ReportUtils.js` here:
https://github.com/Expensify/App/blob/18acd82f40153fc1e5091aea3217c532142e500e/src/pages/settings/Report/WriteCapabilityPage.js#L41
```js
    const isAbleToEdit = ReportUtils.canEditWriteCapability(props.report, props.policy);
```

## What other alternative did you explore?
If we want to hide the room name field for all tasks altogether, whether policy or non-policy, then we can perform the following changes in addition to the fore-mentioned changes as well:
We can set the `shouldShowRoomName` property to exclude the tasks here:
https://github.com/Expensify/App/blob/302cebf14c4e0fcd6570ac66e9d85a1ca0212ae6/src/pages/settings/Report/ReportSettingsPage.js#L68
By either changing `!ReportUtils.isChatThread(report)` to `!ReportUtils.isThread(report)

**Comment by abekkala** [comment] 2023-10-20 14:07
Correct, this is a dupe as the other was created first
closing

**Closed by abekkala** 2023-10-20 14:07 UTC
Labels: External, Daily, Help Wanted, Bug
