### ISSUE TITLE
[$250] mWeb - Tag - Without parent, if child category is entered it is displayed after lot of space

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#45845] opened 2024-07-20 16:05 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 9.0.10
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**If this was caught during regression testing, add the test name, ID and link from TestRail:** N/A 
**Issue reported by:** Applause - Internal Team

## Action Performed:
1. Go to https://staging.new.expensify.com/
2. Tap profile icon - workspaces - workspace
3. Tap category -- add a category
4. Enter : 3 and save it
5. Navigate to LHN
6. Tap workspace chat
7. Tap plus icon - submit expense
8. Enter an amount and tap next
9. Tap show more
10. Tap category

## Expected Result:
Without parent, if child category is entered it should not be displayed after lot of space in dropdown

## Actual Result:
Without parent, if child category is entered it is displayed after lot of space in dropdown

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [x] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [ ] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details> 

https://github.com/user-attachments/assets/24fbdcf9-31ad-4ed3-b643-d6721b8dbb1a

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01bb005751f09bf94d</li>
        <li>Upwork Job ID: 1815493111766091276</li>
        <li>Last Price Increase: 2024-08-05</li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @hoangzinh</details>

**Comment by lanitochka17** [comment] 2024-07-20 16:06
@VictoriaExpensify  FYI I haven't added the External label as I wasn't 100% sure about this issue. Please take a look and add the label if you agree it's a bug and can be handled by external contributors

**Comment by lanitochka17** [comment] 2024-07-20 16:06
We think that this bug might be related to #vip-vsp

**Comment by BhuvaneshPatil** [comment] 2024-07-20 19:26
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
If we have colon (:) in the name but not text before colon, example - ` : category` we are getting extra space in categories list

### What is the root cause of that problem?
We are using `getCategoryOptionTree` function to build the category tree. This function uses `colon` as separator between parent and child.
It uses split method to distinguish between child and parent, 
Example - `Parent : children`.
If we give string - `: children` it will take empty string as parent and a hierarchy as well. This results in empty space.

https://github.com/Expensify/App/blob/fa738c641e7d2b289850da7b4be11369c33b96d6/src/libs/OptionsListUtils.ts#L1109-L1130

### What changes do you think we should make in order to solve the problem?
We shall add check for valid parent in the same function.
Similar to this -> 
```ts
...
 option.name.split(CONST.PARENT_CHILD_SEPARATOR).filter(optionName => optionName.trim().length > 0).forEach((optionName, index, array) => {
...
```

We will filter out all empty strings and only get correct nodes in the tree.
This solution works for multiple empty colons.

https://github.com/user-attachments/assets/bf9d85dc-4f88-47b9-a046-610fa9d9468a

There is one question from my end - 
- If we have something - `Parent: : : : : children` then what should be considered?

### What alternative solutions did you explore? (Optional)

**Comment by truph01** [comment] 2024-07-21 17:20
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
- Without parent, if child category is entered it is displayed after lot of space in dropdown

### What is the root cause of that problem?
- When we has a category named ```: child```, this function:
https://github.com/Expensify/App/blob/f3a8f736208166286e6f7da3562f1503d5ef2a3d/src/libs/OptionsListUtils.ts#L1088
will return something like:
```
[
   {
      "text":""
   },
   {
      "text":"    child"
   }
]
```
- So in category picker, there is a option with empty name as the behavior of this bug.
### What changes do you think we should make in order to solve the problem?
- In OldDot, we do not display the category option if its name is empty:
![image](https://github.com/user-attachments/assets/fe8ac2c7-1f0c-4c63-9536-f37570309973)

- We should do it in NewDot by updating this:
https://github.com/Expensify/App/blob/f3a8f736208166286e6f7da3562f1503d5ef2a3d/src/libs/OptionsListUtils.ts#L1132

### What alternative solutions did you explore? (Optional)

**Comment by bernhardoj** [comment] 2024-07-22 10:54
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
Category with parent:child pattern but the parent is empty is still shown as a parent-child structure in the categories page which shows an empty row and an indented child.

### What is the root cause of that problem?
The current code simply splits the name with a colon (:), so if we split (:child), the result will be ['', 'child'] and the empty string will be the parent of 'child'.
https://github.com/Expensify/App/blob/e3ebeffb55c2a20ee890061f23e3e0f37d32290e/src/libs/OptionsListUtils.ts#L1109-L1129

### What changes do you think we should make in order to solve the problem?

We can use a non-regex or a regex solution.

Non-regex solution:
For non-regex solution, we split the name with a colon first. Then, we check if there is an empty string from the split result. If there is an empty string, then we process the category name as it is without creating the parent-child structure. Otherwise, we use the split-ted result.
```
const optionNames = option.name.split(CONST.PARENT_CHILD_SEPARATOR);
const names = optionNames.some(optionName => !optionName) ? [option.name] : optionNames;
names.forEach((optionName, index, array) => {
```

Regex solution:
For regex solution, we test the category name first whether it follows the parent:child pattern or not. If yes, then we split it, otherwise, we use the full category name.
```
const optionNames = /^[^:\s]+([^:]*:[^:]*[^:\s]+)+$/g.test(option.name) ? option.name.split(CONST.PARENT_CHILD_SEPARATOR) : [option.name];
optionNames.forEach((optionName, index, array) => {
```

This is harder to understand because of the regex. The regex will match if the first few characters are anything other than colon or whitespace. Then, followed by a colon which the before and after colon can be anything other than a colon. Ends with anything other than colon or whitespace.

**Comment by VictoriaExpensify** [comment] 2024-07-29 22:39
Yeah I think that's how we should move forward - the indent to show it's a child-category, but remove the spacing from the top.

Happy to consider alternatives if you have any in mind.

**Comment by BhuvaneshPatil** [comment] 2024-07-30 04:53
Extension to my [proposal](https://github.com/Expensify/App/issues/45845#issuecomment-2241268703) above
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
If we have colon (:) in the name but not text before colon, example -  : category we are getting extra space in categories list

What is the root cause of that problem?
We are using getCategoryOptionTree function to build the category tree. This function uses colon as separator between parent and child.
It uses split method to distinguish between child and parent,
Example - Parent : children.
If we give string - : children it will take empty string as parent and a hierarchy as well. This results in empty space.

### What changes do you think we should make in order to solve the problem?
as @VictoriaExpensify Mentioned that we want to have space to indicate that it's a child. We can add following logic -
```ts
        const track = option.name
            .split(CONST.PARENT_CHILD_SEPARATOR)
            .reduce(
                (acc, child) => {
                    if (child.trim().length === 0) {
                        acc.emptyCount += 1;
                        return acc;
                    }
                    const addSpace = acc.emptyCount > 0;
                    const effectiveChild = addSpace ? `${CONST.INDENTS}${child.trim()}` : child.trim();
                    acc.vals.push(effectiveChild);
                    acc.emptyCount = 0;
                    return acc;
                },
                { emptyCount: 0, vals: [] },
            )
```
also if we want to show the indent we will need to make change here as well - 
https://github.com/Expensify/App/blob/df69c80229acdc510064d2671e2fdde8095a93a7/src/components/SelectionList/RadioListItem.tsx#L25

remove the check for `isMultilineSupported`
If we have empty string between colons, that will count for adding indent.

https://github.com/user-attachments/assets/3795e9b3-9eb8-458b-8538-1b6d183fdc4d

@VictoriaExpensify @hoangzinh But there's a catch with adding indent approach,
in case of sorting, if our category comes below the category with parent: child, it will look as child of another parent.
example - 

In the shared picture, child is different category but it's showing as child of 1->2.

<img width="860" alt="Screenshot 2024-07-30 at 10 20 58 AM" src="https://github.com/user-attachments/assets/11e55de0-2268-4e02-8532-ab55f810202d">


### What alternative solutions did you explore? (Optional)

**Comment by trjExpensify** [comment] 2024-08-08 23:12
Decided we'd do nothing here, closing.

**Closed by trjExpensify** 2024-08-08 23:12 UTC
Labels: External, Daily, Help Wanted, Bug
