### ISSUE TITLE
Bank account - Incorrect error when invalid character is inserted in legal name fields

### ISSUE THREAD

**Issue by mvtglobally** [Expensify/App#51776] opened 2024-10-31 08:17 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 9.0.55-9
**Reproducible in staging?:** Y 
**Reproducible in production?:** N
**If this was caught on HybridApp, is this reproducible on New Expensify Standalone?:**
**If this was caught during regression testing, add the test name, ID and link from TestRail:** 
**Email or phone of affected tester (no customers):** applausetester+kh1610015@applause.expensifail.com
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**  
**Issue reported by:** Applause Internal team 
**Slack conversation** (hyperlinked to channel name):  
Found when executing PR https://github.com/Expensify/App/pull/51231 

## Action Performed:
1. Go to staging.new.expensify.com
2. Go to workspace settings > Expensify Card.
3. Click Issue new card.
4. Click Connect manually.
5. Enter account numbers > Next.
6. On "What's your legal name" step, enter number on the fields.
7. Click Next.

## Expected Result:
The error message for invalid name should be "Please enter a valid first name." and "Please enter a valid last name." (production behavior).

## Actual Result:
The error message for invalid name should be "This field is required".
The field labels are also different from production. It shows "First name" instead of "Legal first name".

## Workaround:
unknown 

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Standalone
- [ ] Android: HybridApp
- [ ] Android: mWeb Chrome
- [ ] iOS: Standalone
- [ ] iOS: HybridApp
- [ ] iOS: mWeb Safari
- [X] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

<details>
  <summary>Add any screenshot/video evidence</summary>
  

https://github.com/user-attachments/assets/be00e49d-1473-4297-965b-ec7e554e11fc

https://github.com/user-attachments/assets/2b1f4b47-6a84-45de-beec-0f83fe0fb220

  
</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by Beamanator** [comment] 2024-10-31 08:21
Sorry, puneet must have been assigned as bugzero so sorry for removing you 😅

**Comment by Beamanator** [comment] 2024-10-31 08:22
@burczu @hungvu193 this def looks related to https://github.com/Expensify/App/pull/51231 yeah?

Especially because the field labels are also different from production. It shows "First name" instead of "Legal first name" & same for last name

**Comment by hungvu193** [comment] 2024-10-31 08:29
Checking 👀

**Comment by hungvu193** [comment] 2024-10-31 08:55
Thanks @NJ-2020, I'm preparing a PR already.

**Comment by ikevin127** [comment] 2024-10-31 09:39
I got auto-assigned as reviewer for the PR, I will be able to review it in ~ 8 hours.

If it's more urgent then feel free to re-assign reviewer!

**Comment by Beamanator** [comment] 2024-10-31 09:59
Thanks for the heads up @ikevin127 , I think we will move forward w/out your review since this is a deploy blocker 🙏

**Comment by Beamanator** [comment] 2024-10-31 10:57
confirmed fixed in staging, no payment needed here 👍

**Closed by Beamanator** 2024-10-31 10:57 UTC
Labels: Reviewing, Engineering, Weekly, Bug
