### ISSUE TITLE
[$500]  mWeb - Chat - Sometimes the cursor is placed before the emoji

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#35400] opened 2024-01-30 13:37 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.33.0
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** Applause - Internal Team
**Slack conversation:**

## Action Performed:
1. Open a chat
2. Type a single emoji to the composer with emoji picker (don't send it)
3. Tap away so the composer loses focus
4. Tap inside the composer again
5. Repeat steps 2-4 until the bug appears

## Expected Result:
The cursor should always be after the emoji.

## Actual Result:
Sometimes the cursor is placed before the emoji

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details> 

https://github.com/Expensify/App/assets/78819774/64d148df-03dd-4e6e-bbc6-9600fd500f43

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~0166536b4c825bb51e</li>
        <li>Upwork Job ID: 1752325119743647744</li>
        <li>Last Price Increase: 2024-02-13</li>
    </ul>
</details>

**Comment by lanitochka17** [comment] 2024-01-30 13:38
We think that this bug might be related to #vip-vsp
CC @quinthar

**Comment by ayoung19** [comment] 2024-01-31 10:25
I found a more consistent way to reproduce this bug which may not have to do with the emoji picker:

1) Type anything, text or emojis.
2) Click inside the textarea (not padding).
3) Click on the padding of the textarea.

https://github.com/Expensify/App/assets/18640252/87c69137-4227-4253-b304-3372ea1d5f58

This will cause the cursor to jump to the beginning of the textarea, at least on Chrome/MacOS. It seems like this behavior is dictated by the browser. Here are some stackoverflow posts describing the same issue:

https://stackoverflow.com/questions/64874384/how-do-i-avoid-cursor-jump-to-beginning-of-the-input-when-clicking-near-its-edge

https://stackoverflow.com/questions/58732887/clicking-on-the-padding-of-an-input-field-sets-the-cursor-at-the-beginning-of-th

**Comment by ayoung19** [comment] 2024-01-31 10:30
Contributor details
Your Expensify account email: andyluyoung@gmail.com
Upwork Profile Link: https://www.upwork.com/freelancers/~01b17d36b6311f055a

**Comment by alexpensify** [comment] 2024-01-31 20:29
@thesahindia - when you get a chance, can you review the proposal? Thanks!

**Comment by alexpensify** [comment] 2024-02-02 22:15
@thesahindia any update here?

**Comment by ayoung19** [comment] 2024-02-04 23:23
I didn't create a proposal because I don't think this is actually a bug.

**Comment by alexpensify** [comment] 2024-02-06 00:32
Whoops, I mixed up the feedback as a proposal.

**Comment by alexpensify** [comment] 2024-02-07 23:50
No update, still open for proposals here.

**Comment by jeremy-croff** [comment] 2024-02-08 00:56
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
Sometimes when we click into the composer from the end, the caret starts at the beginning

### What is the root cause of that problem?
As @ayoung19 identified, it's when the customer presses on the padding instead of the text input. The browser gives a cursor event with start and end of 0, so that's why the cursor goes to the start in this scenario. It's like tabbing into the Composer. This seems common in browsers.


### What changes do you think we should make in order to solve the problem?

We have to remove the vertical padding, and add it to the line-height if we want to increase the clickable text input area, with the correct cursor position. 

### What alternative solutions did you explore? (Optional)
We can use margin instead of padding, and make the area not clickable. forcing them to press the center.

**Comment by jeremy-croff** [comment] 2024-02-08 01:17
I could implement exact CSS but the goal outcome is to maintain the same layout and either increase the clickable area with the correct cursor position, or to disable the click ability of the padding.

Alternative solutions are to move up the padding to the wrapper of the component, and to increase the height of the input to negate the padding.

**Comment by alexpensify** [comment] 2024-02-09 18:00
@thesahindia - when you get a chance, can you review this new proposal? Thanks!

**Comment by alexpensify** [comment] 2024-02-12 16:31
@thesahindia any update here?

**Comment by alexpensify** [comment] 2024-02-14 19:23
@thesahindia - please keep us posted if you are unable to review and we will find a replacement. Thanks!

**Comment by alexpensify** [comment] 2024-02-14 20:33
Thanks for the feedback! Closing!

**Closed by alexpensify** 2024-02-14 20:33 UTC
Labels: External, Daily, Help Wanted, Bug
