### ISSUE TITLE
Web - Green line appears with "New" after request/cancel money

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#11216] opened 2022-09-22 18:31 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Go to staging.new.expensify.com
2. Log in with any account
3. Select any user
4. Click on plus button - Request Money
5. Select "View" detail and click Cancel

## Expected Result:
Green line should not be appear with "New" after request/cancel money

## Actual Result:
Green line appears with "New" after request/cancel money

## Workaround:
Unknown

## Platform:

Where is this issue occurring?

- Web

**Version Number:** 1.2.5.0

**Reproducible in staging?:** Yes

**Reproducible in production?:** No

**Email or phone of affected tester (no customers):** applausetester+0901abb@applause.expensifail.com

**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Notes/Photos/Videos:** Any additional supporting documentation

https://user-images.githubusercontent.com/93399543/191824207-264f0f9b-1a61-44cb-aa1e-e5411ccc256d.mp4

**Expensify/Expensify Issue URL:** 

**Issue reported by:** @thesahindia & Applause - Internal Team

**Slack conversation:** https://expensify.slack.com/archives/C01GTK53T8Q/p1662998620350799

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by bondydaa** [comment] 2022-09-22 22:19
cannot reproduce this on `Version 1.2.5-0 (1.2.5-0)` with the staging or production server backend.

**Comment by marcaaron** [comment] 2022-09-22 22:23
Gonna add this to my watch list but without a reproduction it's hard to know what is causing this. Probably we will need to capture logs or add more logs if we don't have any ones that can help identify the root cause.

**Comment by bondydaa** [comment] 2022-09-22 22:41
oh also confirming I tested directly on staging.new.expensify.com as well and couldn't reproduce either

**Comment by kbecciv** [comment] 2022-09-22 23:23
@bondydaa @marcaaron I just check the issue again and noticed that its reproduced for the first attempt to request money .

https://user-images.githubusercontent.com/93399543/191868076-0d0f6b00-43c3-4163-886a-706d49de3174.mp4

**Comment by bondydaa** [comment] 2022-09-22 23:35
hmm strange, i wonder if this is platform specific b/c even testing sending to accounts I've never requested money from i can't reproduce 🤔 very very weird.

**Comment by bondydaa** [comment] 2022-09-23 16:19
<img width="1214" alt="image" src="https://user-images.githubusercontent.com/4073354/192005300-97bc6cd9-3de6-4f1f-8630-a2e2f4320ecb.png">

ooh boy i just reproduced this! but now I can't again with what I thought was the key...

I think it has to do with switching from a different chat to the 1:1 chat with the person you're requesting money. IIRC I started out with a group chat loaded I think between Nikki and Marc or maybe Marc and Tim and then requested the money and when it switched to the 1:1 chat between me and Nikki to show the IOU the new was there. 

Maybe it does need to be the first time you request money from that user and you start with a different chat loaded?

**Comment by bondydaa** [comment] 2022-09-23 16:20
though my screenshot suggests otherwise since there are other IOUs shown there and dismissed 🤔

**Comment by mvtglobally** [comment] 2022-09-27 05:16
Issue not reproducible during KI retests. (First week)

**Comment by mvtglobally** [comment] 2022-10-03 20:23
Issue not reproducible during KI retests. (Second week)

**Comment by mvtglobally** [comment] 2022-10-18 11:26
Issue not reproducible during KI retests. (Third week) Closing

**Closed by mvtglobally** 2022-10-18 11:26 UTC
Labels: Engineering, Monthly, Needs Reproduction
