### ISSUE TITLE
[HOLD for payment 2023-07-21] [HOLD for payment 2023-07-20] [$1000] Login(email) overflows out of tooltip

### ISSUE THREAD

**Issue by MonilBhavsar** [Expensify/App#20839] opened 2023-06-15 16:52 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:

1. sign in with an email address of length 50-60 characters (ex: [c.dobrzyn+19238120974634763783398130974189813097418972987@expensifail.com](mailto:c.dobrzyn+19238120974634763783398130974189813097418972987@expensifail.com))
2. Click Settings > Profile
3. Set your display First name as "AB"
4. Send a chat to someone
5. Hover over your name in the chat

## Expected Result:

Email is adjusted in tooltip

## Actual Result:
Email overflows out of tooltip

## Workaround:
Can the user still use Expensify without this being fixed? Have you informed them of the workaround?
None
## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [X] Android / native
- [X] Android / Chrome
- [X] iOS / native
- [X] iOS / Safari
- [x] MacOS / Chrome / Safari
- [X] MacOS / Desktop

<img width="1061" alt="Screenshot 2023-06-15 at 10 18 49 PM" src="https://github.com/Expensify/App/assets/32012005/136c8628-4707-4ccb-a462-f6d7f85677fc">

<img width="1436" alt="image" src="https://github.com/Expensify/App/assets/51066321/ea082b1c-914d-475b-a8d7-685c9828538f">

**Version Number:**
**Reproducible in staging?:**
**Reproducible in production?:**
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation
**Expensify/Expensify Issue URL:**
**Issue reported by:** @chiragxarora 
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1686835382299919

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01f55d161999b817c3</li>
        <li>Upwork Job ID: 1675966053218746368</li>
        <li>Last Price Increase: 2023-07-10</li>
    </ul>
</details>

**Comment by MonilBhavsar** [comment] 2023-06-15 16:57
Should be fixed by https://github.com/Expensify/App/pull/20818

**Comment by ahmedGaber93** [comment] 2023-06-15 17:03
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
Login(email) overflows out of tooltip
### What is the root cause of that problem?
There is no Ellipsis effect on text.
### What changes do you think we should make in order to solve the problem?
Add prop `numberOfLines={1}`  here
https://github.com/Expensify/App/blob/9727956e9395f08aac72237891f8db9c280c85c6/src/components/UserDetailsTooltip/index.js#L26
### What alternative solutions did you explore? (Optional)

**Comment by arielgreen** [comment] 2023-06-16 02:53
Reassigning, team change

**Comment by Christinadobrzyn** [comment] 2023-06-16 17:30
Tracking https://github.com/Expensify/App/pull/20818 for fix

**Comment by luacmartins** [comment] 2023-06-19 18:38
I could not reproduce this in staging nor production.

**Comment by chiragsalian** [comment] 2023-06-19 19:21
Same, i think it might be some style caching issue. Can anyone reproduce after clearing cache?

**Comment by Christinadobrzyn** [comment] 2023-06-27 21:38
Hi @chiragxarora sorry, can you clarify, are you saying this issue isn't related to https://github.com/Expensify/App/pull/20818?

**Comment by chiragsalian** [comment] 2023-06-27 22:43
Hey @chiragxarora, just a tiny suggestion, when writing test steps share the test values to make it a bit easier 🙂 
okay so it looks like you used `abcabcabababa@nsut.om.om.om.om.om.m.om.om.com.m.om.om.com.com.com.om.om.om.om.in.m.cm.om` 

I tried setting that as my first name and it looked fine for me locally and on staging,
![image](https://github.com/Expensify/App/assets/14356145/79b344db-6bfd-4ed3-a8f4-9bc060c8f37f)

![image](https://github.com/Expensify/App/assets/14356145/90357477-630d-4ea1-9683-f051572da903)

If possible can you share proper test steps with values for email and name. Without values I'm unsure if you meant for the email to be long or display name.

**Comment by Christinadobrzyn** [comment] 2023-06-30 18:37
Sorry, I'm a little lost about where we are with this issue. 

- Sounds like this isn't related to https://github.com/Expensify/App/issues/20822#issuecomment-1593180839 (which is closed now)
- It sounds like we're waiting on an update to the OP to reproduce the issue?
- Then we need a proposal to fix this as it's own issue, correct?

**Comment by Christinadobrzyn** [comment] 2023-07-03 17:25
I don't understand @chiragxarora the steps here https://github.com/Expensify/App/issues/20839#issuecomment-1615095858 are completely different than the steps in the OP. 

Are you reporting a different issue? I feel like this https://github.com/Expensify/App/issues/20839#issuecomment-1615095858 needs to be a different Bug report as what is in the original OP is now fixed.

**Comment by Christinadobrzyn** [comment] 2023-07-03 17:33
Thanks for providing those steps @chiragxarora - It looks like this GH is still in a needs reproduction state so a C+/engineer hasn't been assigned. 

@chiragsalian was providing feedback based only because they are working on the other GH. 

Trying to reproduce this by following these steps: 

1. sign in with an email address of length 50-60 characters
2. Set your display name as "AB"
3. hover over your tooltip from LHN/main chat/ header etc 

I tried to create an Expensify account for email "c.dobrzyn+192380182309812093810928309180938109471985798127498712938712983712098321098312098123097129847981472987234091237901379813798170139813097418972987@expensifail.com" and I'm getting this error "Given Email is not valid".

<img width="457" alt="image" src="https://github.com/Expensify/App/assets/51066321/e8f56d76-6ef5-4db6-980d-ace3b27e5cf8">

Can you confirm what email you tested on so I can try and reproduce it?

**Comment by Christinadobrzyn** [comment] 2023-07-03 17:42
I've a question, when you use emails like this by adding +111111111, are you able to receive magic code in order to complete sign in?

Yes, I'll get a magic code to my @expensifail.com inbox when I use this email: c.dobrzyn+192380182309812093810928309180938109471985798127498712938712983712098321098312098123097129847981472987234091237901379813798170139813097418972987@expensifail.com

**Comment by Christinadobrzyn** [comment] 2023-07-03 18:48
Awesome! I can reproduce following these steps:

1. sign in with an email address of length 50-60 characters (ex: c.dobrzyn+19238120974634763783398130974189813097418972987@expensifail.com)
2. Click Settings > Profile
3. Set your display First name as "AB"
4. Send a chat to someone
5. Hover over your name in the chat

Notice the full email overflows

<img width="1436" alt="image" src="https://github.com/Expensify/App/assets/51066321/ae0c60f8-f668-44a2-b8a8-cc7fbf482468">

Does this look right @chiragxarora? If yes, I think this is a different bug than what was originally reported in this GH. I think this should be a different GH so you get credit as the reporter. I would report this in #expensify-Bug-source. Let me know if I'm missing a reason to keep it related to this GH.

**Comment by Christinadobrzyn** [comment] 2023-07-03 20:34
Okay sounds good, I updated the OP to the steps reproduced here https://github.com/Expensify/App/issues/20839#issuecomment-1619002720

Added external label

**Comment by Christinadobrzyn** [comment] 2023-07-06 20:09
nudge to @mananjadhav - thanks!

**Comment by mvtglobally** [comment] 2023-07-08 04:11
related? https://github.com/Expensify/App/issues/21100

**Comment by mananjadhav** [comment] 2023-07-10 16:26
Hi Team,
Apologies for the delay here. I couldn't update the comments on OOO. @Christinadobrzyn do we for sure know the expected output? I can see both the proposals with correct RCA, but not sure of the expected output. Based on what I see so far, I think @chiragxarora's proposal [here](https://github.com/Expensify/App/issues/20839#issuecomment-1609561984) looks good, as we don't trim any content. I am also tagging an internal engineer here to second the opinion.

@shawnborton In this case do we want to trim the tooltip content with ellipses? or do we want the content to spillover multiple lines?

🎀 👀 🎀 C+ reviewed.

**Comment by stitesExpensify** [comment] 2023-07-10 16:37
Reading through the thread that @chiragxarora posted, it does in fact seem like we just want spillover to be broken, so their proposal looks good to me!

**Comment by mananjadhav** [comment] 2023-07-11 15:29
Thanks

**Comment by Christinadobrzyn** [comment] 2023-07-14 19:39
I'm going to be ooo until August 31st so going to unassign and assign a new teammate. 

At this time, we're reviewing the PR and waiting for payment. 

@mananjadhav do we need a regression test on this?

**Comment by mananjadhav** [comment] 2023-07-17 20:23
Not sure why added an `Overdue` label, this is deployed to production. Waiting for the regression period.

**Comment by mananjadhav** [comment] 2023-07-20 15:26
We first added the styling and actual login to the Tooltip in this [PR](https://github.com/Expensify/App/pull/20276). I've posted about a comment on the PR [here](https://github.com/Expensify/App/pull/20276#discussion_r1269629698).

I think cases for these are very rare. I had earlier thought about adding an item in the checklist for preWrap check for using `Text` component. But I am not sure if it is something we want do frequently? @stitesExpensify do you have any thoughts on this?

Also I don't think we need a regression test here.

**Comment by isabelastisser** [comment] 2023-07-21 16:38
Thanks @mananjadhav! I will process the other payment in Upwork now.

All set.

**Closed by isabelastisser** 2023-07-21 16:38 UTC
Labels: External, Engineering, Daily, Awaiting Payment, Bug

**Comment by anmurali** [comment] 2023-07-21 19:09
Approved 1500 based on https://github.com/Expensify/App/issues/20839#issuecomment-1644135006 and Isa agreeing above.
