### ISSUE TITLE
[$500] [distance] Distance - Stop waypoint is filled with Finish address

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#26725] opened 2023-09-04 21:19 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___
**Issue found when executing PR** https://github.com/Expensify/App/pull/26591
## Action Performed:
1. Go to staging.new.expensify.com
2. Go to + > Request money > Distance
3. Add addresses in start and finish waypoint
4. Click Add stop
5. Click on the Stop field and clear it and save
6. Click Add stop again
7. Click Finish and add an address and save it

## Expected Result:
The Stop field is not populated

## Actual Result:
The address selected for Finish waypoint is now also populated in Stop waypoint

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android / native
- [x] Android / Chrome
- [x] iOS / native
- [x] iOS / Safari
- [x] MacOS / Chrome
- [x] MacOS / Desktop

**Version Number:** 1.3.63-0

**Reproducible in staging?:**  Yes

**Reproducible in production?:** No

**If this was caught during regression testing, add the test name, ID and link from TestRail:**

**Email or phone of affected tester (no customers):**

**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/78819774/12ecc282-aa36-4734-8fd2-2ae3489cd2ad

**Expensify/Expensify Issue URL:**

**Issue reported by:** Applause - Internal Team

**Slack conversation:**

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~0126bac11a54e11305</li>
        <li>Upwork Job ID: 1698813869209538560</li>
        <li>Last Price Increase: 2023-09-04</li>
    </ul>
</details>

**Comment by neil-marcellini** [comment] 2023-09-04 21:39
Looks like a legit bug

**Comment by Pujan92** [comment] 2023-09-04 21:44
@neil-marcellini it seems a backend issue https://expensify.slack.com/archives/C049HHMV9SM/p1693855330395669

**Comment by neil-marcellini** [comment] 2023-09-04 21:46
Ah right nice, we just merged a fix for that, it will be deployed soon so this is not a blocker.

**Comment by bondydaa** [comment] 2023-09-04 21:48
ah thanks @Pujan92!

**Comment by neil-marcellini** [comment] 2023-09-04 21:49
Here's the merged [backend PR](https://github.com/Expensify/Web-Expensify/pull/38735) that fixes this, but we need to CP it.

**Comment by bondydaa** [comment] 2023-09-04 22:57
@lanitochka17 can you retest against staging API, we CP'd a PR that should have fixed this.

**Comment by napster125** [comment] 2023-09-04 23:45
I can't reproduce it now.

**Comment by DylanDylann** [comment] 2023-09-05 04:03
@bondydaa  I still can reproduce on staging now

**Comment by DylanDylann** [comment] 2023-09-05 04:58
@neil-marcellini @bondydaa This is another bug and can be fixed from FE

## Proposal

### Please re-state the problem that we are trying to solve in this issue.
Distance - Stop waypoint is filled with Finish address

### What is the root cause of that problem?
https://github.com/Expensify/App/blob/f67bf9f88c08fe2cebe16202d1244299a9640ea3/src/libs/actions/Transaction.js#L52-L57

Currently, in the beginning, waypoint1 will be the start point, waypoint2 will be the finish point. When creating a new stop point, start and finish point will remain. The stop point will be waypoint3.

https://github.com/Expensify/App/blob/f67bf9f88c08fe2cebe16202d1244299a9640ea3/src/components/DistanceRequest.js#L187-L196

But while displaying, the finish point is the last point (in this context, last point is waypoint3). It caused this bug 
### What changes do you think we should make in order to solve the problem?
When adding a new stop point we should change the index of the finish point to the last point. In this context, when adding new stop point, this stop point will be waypoint2 and the finish point will move to waypoint3. 

https://github.com/Expensify/App/blob/f67bf9f88c08fe2cebe16202d1244299a9640ea3/src/libs/actions/Transaction.js#L52-L57

```
[`waypoint${newLastIndex-1}`]: null,
[`waypoint${newLastIndex}`]: lodashGet(existingWaypoints, `waypoint${newLastIndex-1}`, {})
```

### What alternative solutions did you explore? (Optional)
 NA

### Result

**Comment by lanitochka17** [comment] 2023-09-05 18:56
The issue does not reproduce in build 1.3.64-0.


https://github.com/Expensify/App/assets/78819774/b5eab7cf-a5a0-4d47-8404-f597461dee8e

**Comment by bondydaa** [comment] 2023-09-05 20:01
okay thanks for confirming @lanitochka17 .

@DylanDylann please follow the process https://github.com/Expensify/App/blob/main/contributingGuides/CONTRIBUTING.md#raising-jobs-and-bugs for reporting new bugs instead of adding it to an existing different bug. 

I'm going to close this out.

**Closed by bondydaa** 2023-09-05 20:01 UTC
Labels: Engineering, Daily
