### ISSUE TITLE
Navigation sliding issues in profile settings troubleshoot pages

### ISSUE THREAD

**Issue by m-natarajan** [Expensify/App#38154] opened 2024-03-12 17:26 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.50-2
**Reproducible in staging?:** y 
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** @quinthar 
**Slack conversation:**  https://expensify.slack.com/archives/C049HHMV9SM/p1710208564341909

## Action Performed:
1. Tap on the avatar to open the `account settings`
2. Tap `about`
3. Tap `troubleshoot`
4. Then Tap `<`until you reach `LHN`
5. Observe the sliding behavior

## Expected Result:
Opening each page `account settings, about and troubleshoot`should slige from the right overtop of the previous page and When pressing `<` button the page should slide away to the right 

## Actual Result:
When pressing back button Troubleshoot page, About page slides in from the right, again, overtop Troubleshoot
Similarly pressing back button again,  Profile slides in from the right
Finally, pressing back button, Account Settings slides away to the right  which is the correct behavior

## Workaround:
unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [ ] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

https://github.com/Expensify/App/assets/38435837/59f201a3-55db-47b3-bfe7-782c5b6dd393

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by mountiny** [comment] 2024-03-12 21:24
This is basically a duplicate of https://github.com/Expensify/App/issues/37359 @GandalfGwaihir Can you post the proposal there instead?

**Closed by mountiny** 2024-03-12 21:24 UTC
Labels: Daily, Bug
