### ISSUE TITLE
[HOLD for payment 2024-03-06] [$500] [MEDIUM] Distance - Map doesn't load and TBD remains when creating request and editing amount offline

### ISSUE THREAD

**Issue by izarutskaya** [Expensify/App#32263] opened 2023-11-30 12:24 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** v1.4.5-7
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** Applause-Internal Tean
**Slack conversation:** @

## Action Performed:
1. Navigate to staging.new.expensify.com
2. Go offline.
3. Go to workspace chat > + > Request money.
4. Create a distance request.
5. Open distance request details page > Amount.
6. Enter amount and save it.
7. Go online.

## Expected Result:
The map will load and the fields with TBD will load data when the network connection is regained.

## Actual Result:
The map never loads and all the details remain TBD.

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [x] Android: mWeb Chrome
- [x] iOS: Native
- [x] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

https://github.com/Expensify/App/assets/93399543/d3381472-7e36-4b5b-b544-5979d999605b

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01a40cd0507a4b7824</li>
        <li>Upwork Job ID: 1730201171282763776</li>
        <li>Last Price Increase: 2024-02-16</li>
<li>Automatic offers: </li>
<ul>
<li>Ollyws | Reviewer | 0</li>
<li>paultsimura | Contributor | 0</li>
</ul></li>
    </ul>
</details>

**Comment by paultsimura** [comment] 2023-11-30 13:04
## Proposal

### Please re-state the problem that we are trying to solve in this issue.


### What is the root cause of that problem?
There is a race condition of optimistic update of the transaction's pendingFields.

### What changes do you think we should make in order to solve the problem?
We shouldn't rely on the `hasPendingWaypoints`, but rather the `transaction.isLoading` state in `MoneyRequestView` to display TBD:

```js
const isLoading = lodashGet(transaction, 'isLoading', false);
```

https://github.com/Expensify/App/blob/12eb47feca5463cce5b2f5bb156d67777506ec94/src/components/ReportActionItem/MoneyRequestView.js#L102

### What alternative solutions did you explore? (Optional)

**Comment by kbecciv** [comment] 2023-12-08 22:05
@dukenv0307 Uploaded a video

**Comment by greg-schroeder** [comment] 2023-12-11 10:00
Let's get to this one ASAP this week!

**Comment by kmbcook** [comment] 2023-12-14 16:02
Oh, I just finished writing my first proposal! I guess it is too late. Here it is anyway.

Please re-state the problem that we are trying to solve in this issue.
  Map doesn't load and TBD amount remains after going offline, creating a workspace distance, editing its amount, and then returning online.

What is the root cause of that problem?
  When the first waypoint is saved, the transaction includes a pendingFields entry of waypoints:add. When the user confirms the distance request that entry should be promptly removed, but it isn't.

What changes do you think we should make in order to solve the problem?
  When the user confirms the distance request, remove waypoints:add from pendingFields of the optimistic transaction built by libs/actions/IOU.getMoneyRequestInformation. This can be accomplished by replacing the call in that function to get the existing transaction, libs/TransactionUtils.getTransaction, with a call to a new function which ensures that waypoints:add is not included.
  If this new function is placed in libs/actions/Transaction it will be in the same file in which waypoints:add was added in the first place (by a call to libs/actions/Transaction.saveWaypoint). Placing the code both to add and to remove waypoints:add in the same file will improve modularity. I suggest naming this new function getWhenFinishedAddingWaypoints.
  The new function libs/actions/Transaction.getWhenFinishedAddingWaypoints will receive the id of the existing transaction, use that id to get the transaction from allTransactions, check for waypoints:add and if it exists replace it with waypoints:null, and then return the transaction. This new function will be called in libs/actions/IOU.getMoneyRequestInformation, instead of calling libs/TransactionUtils.getTransaction (which has been deprecated).
  This change will ensure that the optimistic transaction built in libs/actions/IOU.getMoneyRequestInformation does not contain a waypoints:add entry in its pendingFields, which will eliminate the root cause of the problem.

**Comment by kmbcook** [comment] 2023-12-14 16:09
Contributor details
Your Expensify account email: kevincook13@gmail.com
Upwork Profile Link: https://www.upwork.com/freelancers/~0114fff72015409904

**Comment by kbecciv** [comment] 2024-02-16 12:40
Issue is reproducible on build 1.4.42.0

https://github.com/Expensify/App/assets/93399543/b152d033-bf9f-404c-b86e-de35761ed3cb

**Comment by DylanDylann** [comment] 2024-02-19 17:42
@Ollyws But It seems we can't edit amount in offline

**Comment by paultsimura** [comment] 2024-02-20 08:36
Hi @Ollyws, I've re-checked [my proposal](https://github.com/Expensify/App/issues/32263#issuecomment-1833750246), and it's still relevant – fixes the issue correctly:


https://github.com/Expensify/App/assets/12595293/97de9637-35c8-4911-9e1a-16c616b2af48

Could you please give it a try?

**Comment by paultsimura** [comment] 2024-02-20 08:47
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
When creating & modifying a Distance request offline, the TBD state is stuck.

### What is the root cause of that problem?
There is a race condition of onSuccess update of the transaction's `pendingFields`.

When creating the request, the `successData` contains the following update for the transaction:
```js
"pendingFields": null
```
https://github.com/Expensify/App/blob/31617474a7e09fe9873f7442278caa696f2c73e5/src/libs/actions/IOU.ts#L534-L541

And when modifying the amount:
```js
"pendingFields": {
    "amount": null,
    "currency": null
},
```
https://github.com/Expensify/App/blob/a56c5cb00c79d340a37fef3171268cade46e9819/src/libs/actions/IOU.js#L799

As a result, when coming back online, both operations execute, and the `"pendingFields": null` is ignored (I believe, this is an in-Onyx bug, probably because the operations with `null` get stacked incorrectly), and the optimistically added `"waypoints": "add"` is not removed on successful response.

### What changes do you think we should make in order to solve the problem?
We should reset the `pendingFields` while creating a money request not fully: `pendingFields: null`, but only the pending fields which were set optimistically, similar to the editing scenario – in our case, it would look like this:

```js
"pendingFields": {
    "waypoints": null
},
```

To do this, make the following changes:

```js
        {
            onyxMethod: Onyx.METHOD.MERGE,
            key: `${ONYXKEYS.COLLECTION.TRANSACTION}${transaction.transactionID}`,
            value: {
                pendingAction: null,
                pendingFields: mapValues(transaction.pendingFields, () => null),
            },
        },
```

#### Result:
https://github.com/Expensify/App/assets/12595293/97de9637-35c8-4911-9e1a-16c616b2af48

### What alternative solutions did you explore? (Optional)

**Comment by tgolen** [comment] 2024-02-20 21:00
LGTM!

**Comment by kmbcook** [comment] 2024-02-21 12:10
The root cause is that the optimistic data is incorrect. If that root cause is eliminated, there is no concern with success data. As soon as the user confirms the distance request waypoints:add can be removed from pendingFields of the optimistic transaction. There is no need to wait for the API call to return successfully.

**Comment by paultsimura** [comment] 2024-02-21 14:12
> The root cause is that the optimistic data is incorrect. If that root cause is eliminated, there is no concern with success data. As soon as the user confirms the distance request waypoints:add can be removed from pendingFields of the optimistic transaction. There is no need to wait for the API call to return successfully.

This is incorrect. The waypoints are marked as pending intentionally, and they should remain pending until the `CreateDistanceRequest` API response comes from the server.

**Comment by kmbcook** [comment] 2024-02-21 15:17
> > The root cause is that the optimistic data is incorrect. If that root cause is eliminated, there is no concern with success data. As soon as the user confirms the distance request waypoints:add can be removed from pendingFields of the optimistic transaction. There is no need to wait for the API call to return successfully.
> 
> This is incorrect. The waypoints are marked as pending intentionally, and they should remain pending until the `CreateDistanceRequest` API response comes from the server.

Actually, I believe that as soon as the user confirms the choice of waypoints, they are no longer "pending" in the user's mind. Pending waypoints are useful up until the time that the user confirms them to be correct and complete, which happens prior to the CreateDistanceRequest API call.

**Comment by paultsimura** [comment] 2024-02-21 17:12
Thanks. The PR is ready for review: https://github.com/Expensify/App/pull/37009

**Comment by greg-schroeder** [comment] 2024-03-02 00:10
This was deployed to prod 2/28

**Comment by greg-schroeder** [comment] 2024-03-07 01:35
Hmm. The upwork job was closed for some reason, even though there was recent activity. I don't know. I'll probably have to create a new one...

**Comment by paultsimura** [comment] 2024-03-07 18:26
@greg-schroeder it's weird because the offer is still active for me on Upwork 🤔

**Comment by greg-schroeder** [comment] 2024-03-08 16:31
Apologies, I was out yesterday, but I'll generate a new job today and get this done

**Comment by greg-schroeder** [comment] 2024-03-09 02:13
Doing

**Comment by greg-schroeder** [comment] 2024-03-09 02:16
@paultsimura paid! @Ollyws can you accept the offer we sent you? I'll pay you as soon as you accept

**Comment by greg-schroeder** [comment] 2024-03-09 09:52
cool, paid

**Closed by greg-schroeder** 2024-03-09 09:52 UTC
Labels: Reviewing, External, Daily, Awaiting Payment, Bug
