### ISSUE TITLE
[$250] BUG - Create room - Workspace is not selected by default if one workspace only available in the account

### ISSUE THREAD

**Issue by kavimuru** [Expensify/App#11650] opened 2022-10-06 21:28 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Launch the app and login
2. Click global fab button and select "New Room"
3. Observe the workspace field

## Expected Result:
When creating a new room, if you have only one workspace, it should be selected by default

## Actual Result:
Select a workspace is shown as default and Showing an error telling the user to select a value from the list when there's only one value

## Workaround:
Unknown

## Platform:

Where is this issue occurring?

- Web
- iOS
- Android
- Desktop App
- Mobile Web

**Version Number:** 1.2.12-1
**Reproducible in staging?:** y
**Reproducible in production?:** y
**Email or phone of affected tester (no customers):** 
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** 
<img width="390" alt="image (1)" src="https://user-images.githubusercontent.com/43996225/194421926-7a547179-4749-48dd-8726-c2691af4f588.png">
<img width="393" alt="image" src="https://user-images.githubusercontent.com/43996225/194421927-64a7920f-1865-484e-a7a1-e648950de6fa.png">

https://user-images.githubusercontent.com/43996225/194421943-580fa9c0-9d20-48b0-a939-472a92ddf488.mp4

**Expensify/Expensify Issue URL:** 
**Issue reported by:** @iwiznia 
**Slack conversation:** https://expensify.slack.com/archives/C01GTK53T8Q/p1665065274983609

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by tgolen** [comment] 2022-10-10 16:29
LGTM 👍 🟢

**Comment by sobitneupane** [comment] 2022-10-11 06:05
@rushatgabhane Your proposal will change value in the dropdown or the picker but the changed value is not passed to the parent component.

@aimane-chnaif Soluion 2 from above [proposal](https://github.com/Expensify/App/issues/11650#issuecomment-1273736055) looks good to me. His proposal is to apply the change to a general component `Picker`. @aimane-chnaif Please do test all the components using Picker to make sure it doesn't cause any regression and output is as expected while creating PR.

cc: @tgolen 

🎀👀🎀 C+ reviewed

**Comment by tgolen** [comment] 2022-10-11 15:09
Yeah, I like the proposal for applying it to all pickers 👍 🟢

**Comment by tgolen** [comment] 2022-10-13 17:52
I think @isabelastisser needs to create an upwork job and assign it to you next. But, I think you're OK to start on a PR and we'll get they payments and job figured out in the meantime.

**Comment by tgolen** [comment] 2022-10-13 17:58
Cool, I'll do the GH assignment for you.

**Comment by isabelastisser** [comment] 2022-10-19 11:54
Hey @tgolen , I'm still getting familiar with this process, so do I still need to create an Upwork job and assign it to @aimane-chnaif ? It looks like this has been done [here](https://github.com/Expensify/App/issues/11650#issuecomment-1277979149), but I wanted to confirm. Thanks!

**Comment by tgolen** [comment] 2022-10-23 13:50
I honestly don't really know. Can you check SO to see what the current process is supposed to be? It's constantly evolving.

**Comment by alexpensify** [comment] 2022-10-23 13:54
@isabelastisser - I was confused too. On Friday, I asked [here](https://expensify.slack.com/archives/C01SKUP7QR0/p1666383995622829) and confirmed that I did need to create a job for the GH that I was tagged as `external`. I think that's the next step here.

**Comment by isabelastisser** [comment] 2022-10-25 11:56
Hi @aimane-chnaif, can you please let me know if you were already assigned this job in Upwork? If not, I will create one today. Thanks!

**Comment by isabelastisser** [comment] 2022-10-26 11:55
Internal job posting: https://www.upwork.com/ab/applicants/1585237928058978304/job-details

External job posting: https://www.upwork.com/jobs/~01a510b944f147220c

**Comment by cokacode** [comment] 2022-11-01 18:42
don't you guys have something to close these issues? its already solved, why is this still open?

**Comment by tgolen** [comment] 2022-11-02 14:31
Ack, very sorry about that! I have merged it now. So sorry!

**Comment by sobitneupane** [comment] 2022-11-14 04:08
Waiting payment. PR was deployed to production 9 days ago.
<img width="991" alt="Screenshot 2022-11-14 at 09 51 46" src="https://user-images.githubusercontent.com/25876548/201573159-982a7ff9-48fa-4703-ad4c-fc294807beed.png">
cc: @isabelastisser

**Comment by isabelastisser** [comment] 2022-11-14 14:28
The Contributor and Contributor+ have been paid, the contract has been completed, and the Upwork post has been closed.

**Closed by isabelastisser** 2022-11-14 14:28 UTC
Labels: External, Engineering, Weekly, Bug
