### ISSUE TITLE
[HOLD for payment 2023-07-17] [$1000] Dev: Console error appears when opening Workspace Members Page

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#21840] opened 2023-06-28 20:35 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:

1. Go to Settings -> Workspaces
2. Select any workspace -> Members
3. Refresh the app

Note: without refresh also it can be reproducible.

## Expected Result:
No console error

## Actual Result:
 Error appearing: Warning: Failed prop type: Invalid prop `option.keyForList` of type `number` supplied to `OptionRow`, expected `string`.

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [x] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** n/a
**Reproducible in staging?:** n/a
**Reproducible in production?:** n/a
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation

[Console error on invite member.webm](https://github.com/Expensify/App/assets/93399543/38c6e8c8-a67f-42da-beee-5b4bf7408337)

**Expensify/Expensify Issue URL:**
**Issue reported by:** @daordonez11
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1687887087153099

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~013423b04ca2e860f4</li>
        <li>Upwork Job ID: 1674868972150136832</li>
        <li>Last Price Increase: 2023-06-30</li>
    </ul>
</details>

**Comment by jfquevedol2198** [comment] 2023-06-28 21:27
## Proposal
### Please re-state the problem that we are trying to solve in this issue.
Dev: Console error appears when opening Workspace Members Page

### What is the root cause of that problem?
https://github.com/Expensify/App/blob/53e4154143052649ed7b2b8df302cd1744f31f67/src/pages/workspace/WorkspaceMembersPage.js#L336

Here, `item.accountID` type is number. 
But
https://github.com/Expensify/App/blob/53e4154143052649ed7b2b8df302cd1744f31f67/src/components/optionPropTypes.js#L32

`keyForList` type should be string.

### What changes do you think we should make in order to solve the problem?
Convert `item.accountID` to string type.
https://github.com/Expensify/App/blob/53e4154143052649ed7b2b8df302cd1744f31f67/src/pages/workspace/WorkspaceMembersPage.js#L336

After change:
```javascript
keyForList: `${item.accountID}`
```

### What alternative solutions did you explore? (Optional)
N/A

**Comment by Pujan92** [comment] 2023-06-29 07:01
Dupe of https://github.com/Expensify/App/issues/21611

**Comment by Pujan92** [comment] 2023-07-01 00:42
@Santhosh-Sellavel @maddylewis plz check this 
[comment ](https://github.com/Expensify/App/issues/21611#issuecomment-1615310692)  once.

**Comment by Santhosh-Sellavel** [comment] 2023-07-02 21:01
@Pujan92 I've checked your comment and @maddylewis's too [here](https://github.com/Expensify/App/issues/21611#issuecomment-1615131751). As it's triaged, made external, and ready to move forward let's handle it here.

@maddylewis We need to award reporting bonus to @Pujan92 only as they reported it first!

**Comment by Santhosh-Sellavel** [comment] 2023-07-02 21:14
Considering the proposal from the other issue as well

@Pujan92's [proposal](https://github.com/Expensify/App/issues/21611#issuecomment-1608068363) LGTM! 

C+ Reviewed
🎀 👀 🎀

**Comment by Santhosh-Sellavel** [comment] 2023-07-02 21:15
This is a straightforward issue. A couple of proposals suggest making the passed prop with different ways to make it a string So I went selecting the first one and @allroundexperts suggests adding another type to the number of the `propTypes` That's a good option too, but I don't see any necessity here. Preferably the type `String` should be good enough for now.

I'll let you take the final call here @Li357, thanks!

**Comment by Li357** [comment] 2023-07-03 15:19
Agree we should stick with just a string proptype, and I prefer an explicit coercion with `String` than string interpolation. @Pujan92 all yours!

**Comment by daordonez11** [comment] 2023-07-03 16:26
Someone should review this offer! @Pujan92 should get the report offer as well! Mine was later.

**Comment by Santhosh-Sellavel** [comment] 2023-07-03 16:36
@daordonez11 Yes it was sent accidentally, sorry for the confusion. Please reject as the offer was made in error.

cc: @maddylewis Update @Pujan92 as reported, thanks!

**Comment by Pujan92** [comment] 2023-07-04 17:35
@Santhosh-Sellavel @Li357 [PR](https://github.com/Expensify/App/pull/22203) is ready for review!

**Comment by Santhosh-Sellavel** [comment] 2023-07-17 17:14
> **BugZero Checklist:** The PR fixing this issue has been merged! The following checklist ([instructions](https://stackoverflow.com/c/expensify/questions/14574)) will need to be completed before the issue can be closed:
> 
> * [x]  [@Santhosh-Sellavel] The PR that introduced the bug has been identified. Link to the PR:
> * [x]  [@Santhosh-Sellavel] The offending PR has been commented on, pointing out the bug it caused and why, so the author and reviewers can learn from the mistake. Link to comment: https://github.com/Expensify/App/pull/21237/files#r1265665581
> * [x]  [@Santhosh-Sellavel] A discussion in #expensify-bugs has been started about whether any other steps should be taken (e.g. updating the PR review checklist) in order to catch this type of bug sooner. Link to discussion: Should be caught based on checklist
> * [x]  [@Santhosh-Sellavel] Determine if we should create a regression test for this bug. N/A
> * [x]  [@Santhosh-Sellavel] If we decide to create a regression test for the bug, please propose the [regression test](https://github.com/Expensify/App/blob/main/contributingGuides/REGRESSION_TEST_BEST_PRACTICES.md) steps to ensure the same bug will not reach production again. N/A
> * [x]  [@maddylewis] Link the GH issue for creating/updating the regression test once above steps have been agreed upon:

We don't need a separate regression test here, as we used to look for console errors normally!

cc: @Li357 Let me know if differ on any of the above, thanks!

**Comment by Santhosh-Sellavel** [comment] 2023-07-17 17:15
Requested payment on ND!

**Comment by anmurali** [comment] 2023-07-18 18:08
Approved 1500 for Santhosh on ND

**Comment by maddylewis** [comment] 2023-07-19 20:49
is someone able to confirm the following payments were processed: 
- @Santhosh-Sellavel ($1500 paid via NewDot)
- @Pujan92 ($1500 auto payment via Upwork)
- @daordonez11 ($250 reporting bonus auto payment via Upwork) 

once those are all set i believe we can close this issue - thanks!

**Comment by daordonez11** [comment] 2023-07-19 21:09
@maddylewis  I rejected reporting, finally @Pujan92 himself did the first report as well.

**Comment by maddylewis** [comment] 2023-07-19 21:10
So, @Pujan92 is owed an additional $250?

**Comment by daordonez11** [comment] 2023-07-19 21:19
Yeah! I think @Pujan92 total is 1750. He has a bonus for urgency and reporting!

**Comment by Pujan92** [comment] 2023-07-20 16:54
> * @Pujan92 ($1500 auto payment via Upwork)

@maddylewis I think I am yet to receive this. Could you plz check once on it?

**Comment by maddylewis** [comment] 2023-07-21 16:52
- [ ] Sent $1500 offer to @Pujan92 
- [ ] Sent $250 offer to @daordonez11

**Comment by daordonez11** [comment] 2023-07-21 17:22
@maddylewis Ill reject the 250! Remember it is 1750 for @Pujan92

**Comment by maddylewis** [comment] 2023-07-21 17:26
oh, i see. i thought you were both getting reporting bonuses for this one. I've sent $1750 to @Pujan92 - so i think we're all set here!

**Closed by maddylewis** 2023-07-21 17:26 UTC
Labels: External, Daily, Awaiting Payment, Bug

**Comment by daordonez11** [comment] 2023-07-21 17:33
Yup it's all clear! I always wanna keep things straight 🫡
