### ISSUE TITLE
[$500] Web -  Address 'No results found' styling is inconsistent

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#28037] opened 2023-09-22 16:57 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Open the app
2. Open settings->profile->personal details->Home address
3. In 'Address line 1', type text which will trigger 'No results found' eg: ffff
4. Observe the styling of 'No results found' text
5. Remove text and type anything that will trigger results eg: USA
6. Observe the styling of results is way more bold with bigger font
7. Now close the RHN and open search
8. Type in any text to trigger 'No results found' and observe that here and everywhere in the app, 'No results found' has similar styling as label of the field

## Expected Result:
 App should either style 'No results found' similar to address results or style is similar to label styling as we have kept throughout the app

## Actual Result:
Address 'No result found' styling is inconsistent with similar text throughout the app as well as address results

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [x] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 1.3.73.0
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/93399543/c4c4a2bd-784c-4bb0-aecc-1bae40af23dd

https://github.com/Expensify/App/assets/93399543/3a82d3ae-5270-42fa-be99-a3c9dd929909

**Expensify/Expensify Issue URL:**
**Issue reported by:** @dhanashree-sawant
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1695227570896609

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~0180e8f16f29c76851</li>
        <li>Upwork Job ID: 1705265115126829056</li>
        <li>Last Price Increase: 2023-09-22</li>
    </ul>
</details>

**Comment by b4s36t4** [comment] 2023-09-22 17:01
I don't think this as bug, as Address field is a self-searchable component whereas other places it is option search. The layout and search places are entirely different. maybe it's a design question.

**Comment by jliexpensify** [comment] 2023-09-22 23:06
Removing myself as the second B0 assigned

**Comment by abdel-h66** [comment] 2023-09-22 23:10
## Proposal

### Please re-state the problem that we are trying to solve in this issue.

Not found results looks different for all the Address field.

### What is the root cause of that problem?
This is not particually a bug, but if we want to have the same experience accross all autocomplete fields we will have to update `react-native-google-places-autocomplete` package 

### What changes do you think we should make in order to solve the problem?

the not found result display can be handled here 
https://github.com/Expensify/react-native-google-places-autocomplete/blob/cef3ac29d9501091453136e1219e24c4ec9f9d76/GooglePlacesAutocomplete.js#L769-L791

We can use a text display instead of using `ListEmptyComponent` of the `FlatList` we can leave the prop passed to `GooglePlacesAutocomplete` as is or we can style it to better match the rest of the application. 

The changes will look something like this 

        <FlatList
          nativeID='result-list-id'
          scrollEnabled={!props.disableScroll}
          style={[
            props.suppressDefaultStyles ? {} : defaultStyles.listView,
            props.styles.listView,
          ]}
          data={dataSource}
          keyExtractor={keyGenerator}
          extraData={[dataSource, props]}
          ItemSeparatorComponent={_renderSeparator}
          renderItem={({ item, index }) => _renderRow(item, index)}
          ListHeaderComponent={
            props.renderHeaderComponent &&
            props.renderHeaderComponent(stateText)
          }
          ListFooterComponent={_renderPoweredLogo}
          {...props}
        />
      <ListEmptyComponent />
      );

### What alternative solutions did you explore? (Optional)

N/A

**Comment by Ambaza** [comment] 2023-09-23 11:59
I can provide you with an updated version of the GooglePlacesAutocomplete.js file based on the proposed changes to handle the "Not found" message differently and style it consistently with the rest of the application. Here's the updated code:


/* eslint-disable react-native/no-inline-styles */
import debounce from 'lodash.debounce';
import PropTypes from 'prop-types';
import Qs from 'qs';
import React, {
  forwardRef,
  useMemo,
  useEffect,
  useImperativeHandle,
  useRef,
  useState,
} from 'react';
import {
  ActivityIndicator,
  FlatList,
  Image,
  Keyboard,
  Platform,
  Pressable,
  ScrollView,
  StyleSheet,
  Text,
  TextInput,
  View,
} from 'react-native';

const defaultStyles = {
  // ... (existing default styles)
};

export const GooglePlacesAutocomplete = forwardRef((props, ref) => {
  // ... (existing code)

  const _renderNoResults = () => {
    if (dataSource.length === 0 && stateText.length >= props.minLength) {
      return (
        <Text style={[
          props.suppressDefaultStyles ? {} : defaultStyles.description,
          props.styles.description,
          { color: 'red' } // Add your custom styling for "Not found" message here
        ]}>
          No results found
        </Text>
      );
    }

    return null;
  };

  // ... (existing code)

  return (
    <View
      style={[
        props.suppressDefaultStyles ? {} : defaultStyles.container,
        props.styles.container,
      ]}
      pointerEvents='box-none'
    >
      {!props.textInputHide && (
        <View
          style={[
            props.suppressDefaultStyles ? {} : defaultStyles.textInputContainer,
            props.styles.textInputContainer,
          ]}
        >
          {_renderLeftButton()}
          <TextInputComp
            ref={inputRef}
            style={[
              props.suppressDefaultStyles ? {} : defaultStyles.textInput,
              props.styles.textInput,
            ]}
            value={stateText}
            placeholder={props.placeholder}
            onFocus={
              onFocus
                ? (e) => {
                    _onFocus();
                    onFocus(e);
                  }
                : _onFocus
            }
            onBlur={
              onBlur
                ? (e) => {
                    _onBlur(e);
                    onBlur(e);
                  }
                : _onBlur
            }
            clearButtonMode={clearButtonMode || 'while-editing'}
            onChangeText={_handleChangeText}
            {...userProps}
          />
          {_renderRightButton()}
        </View>
      )}
      {props.inbetweenCompo}
      {_renderNoResults()} {/* Display "Not found" message */}
      {_getFlatList()}
      {props.children}
    </View>
  );
});

// ... (existing PropTypes and defaultProps)

export default { GooglePlacesAutocomplete };

**Comment by Ambaza** [comment] 2023-09-23 12:10
Contributor details
Your Expensify account email: <ambazaarmand@gmail.com>
Upwork Profile Link: <https://www.upwork.com/freelancers/~017abcad715d84ce3a>

**Comment by Ambaza** [comment] 2023-09-25 07:27
Contributor details
Your Expensify account email: <ambazaarmand@gmail.com>
Upwork Profile Link: <https://www.upwork.com/freelancers/~017abcad715d84ce3a>

**Comment by Ambaza** [comment] 2023-09-25 07:42
Contributor details
Your Expensify account email: <ambazaarmand@gmail.com>
Upwork Profile Link: <https://www.upwork.com/freelancers/~017abcad715d84ce3a>

**Comment by maddylewis** [comment] 2023-09-27 21:15
noted - thanks for that breakdown. i will give this a closer look before EOW and give a recommendation on next steps!

**Comment by maddylewis** [comment] 2023-09-28 17:23
reviewing this again, this design choice looks intentional. closing.

**Closed by maddylewis** 2023-09-28 17:23 UTC
Labels: External, Daily, Help Wanted, Bug
