### ISSUE TITLE
[HOLD for payment 2023-09-18] [$1000] Chat - Content shifts up and down for a few pixels while adding new line in expanded composer

### ISSUE THREAD

**Issue by izarutskaya** [Expensify/App#26222] opened 2023-08-29 15:40 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Click inside the composer
2. Create new lines multiple times until you see the arrow to expand the composer
3. Click on the expand arrow to expand the composer
4. Clear any content from the composer
5. Type something and click shift + enter to create a new line
6. Do step 5 three times and focus on the contents you are typing

## Expected Result:
No shifting up and down should happen

## Actual Result:
Content shifts up and down for a few pixels while creating the first three new lines

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [x] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** v1.3.57-5

**Reproducible in staging?:** Y

**Reproducible in production?:** Y

**If this was caught during regression testing, add the test name, ID and link from TestRail:**

**Email or phone of affected tester (no customers):**

**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/115492554/b7a27d2d-32eb-4768-89a3-e2fe15ea1192

https://github.com/Expensify/App/assets/115492554/dfc51e92-877c-4b8d-b791-ab2d5ab241cd

**Expensify/Expensify Issue URL:** 

**Issue reported by:** @Nathan-Mulugeta

**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1692694002161089

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~019f45bad3127cfc1e</li>
        <li>Upwork Job ID: 1696681622074855424</li>
        <li>Last Price Increase: 2023-08-30</li>
<li>Automatic offers: </li>
<ul>
<li>mollfpr | Reviewer | 26535658</li>
<li>jscardona12 | Contributor | 26535659</li>
<li>Nathan-Mulugeta | Reporter | 26535660</li>
</ul></li>
    </ul>
</details>

**Comment by jscardona12** [comment] 2023-08-29 15:59
## Proposal
### Please re-state the problem that we are trying to solve in this issue.
Chat - Content shifts up and down for a few pixels while adding new line in expanded composer
### What is the root cause of that problem?
Te root cause is that in the function `getComposeTextAreaPadding` on the file [StylesUtils.js](https://github.com/Expensify/App/blob/17025aa62b1a8c40bb451a97000d3f4605c7bdae/src/components/StylesUtils.js#L1240) it puts a condition  `if (numberOfLines === 3) paddingValue = 8;` but when is more that 3 lines it jumps again to `paddingValue = 5`

### What changes do you think we should make in order to solve the problem?
we should change the condition to  `if (numberOfLines >= 3) paddingValue = 8;

### Without fix

### Solution Working

https://github.com/Expensify/App/assets/16781411/a454171d-70f5-43ed-957a-340479c251a8


https://github.com/Expensify/App/assets/16781411/4b504e23-9a8d-410b-9472-bdc83984fac2



### What alternative solutions did you explore? (Optional)
N/A

**Comment by strepanier03** [comment] 2023-08-30 00:29
Able to repro following the steps very easily. 

![2023-08-29_17-28-32 (1)](https://github.com/Expensify/App/assets/10925636/199695e1-7f68-4a69-b3ab-0162722ba896)

**Comment by AJV009** [comment] 2023-08-30 01:23
Proposal (for the Upwork job):

I understand the issue completely; I just did the setup and tested it. (You can see my registration mail on your server: jaimonalphons@gmail.com)

I will have to write a snip to detect the textarea full-size expansion inside the `getComposeTextAreaPadding` or its parent `inputStyleMemo` and then adjust the 8px padding accordingly. 'line count' dependency has to be removed.

You have few functions and values in your index.js about the composer window that I would like to explore for the solution
```js
    /** Whether the full composer can be opened */
    isFullComposerAvailable: PropTypes.bool,

    /** Allow the full composer to be opened */
    setIsFullComposerAvailable: PropTypes.func,

    /** Should we calculate the caret position */
    shouldCalculateCaretPosition: PropTypes.bool,

    /** Function to check whether composer is covered up or not */
    checkComposerVisibility: PropTypes.func,

    /** Whether this is the report action compose */
    isReportActionCompose: PropTypes.bool,
```

I can guarantee a PR by today and at max tomorrow.

**Comment by AJV009** [comment] 2023-08-30 01:32
Contributor details
Your Expensify account email: jaimonalphons@gmail.com
Upwork Profile Link: https://www.upwork.com/freelancers/~019157463492c3abf7

**Comment by AJV009** [comment] 2023-08-30 04:45
Looking forward to the approval of the previously submitted proposal here https://github.com/Expensify/App/issues/26222#issuecomment-1698354441 :)
Since the Upwork job said "not required to submit the final solution or code in the proposal"

**Comment by mollfpr** [comment] 2023-08-30 17:26
Will review the proposals in the morning, thanks!

**Comment by mollfpr** [comment] 2023-08-31 14:05
@jscardona12 I don't think we want the padding 8px for the default; it should be 5px. 

> In case numberOfLines = 3, there will be a Expand Icon appearing at the top left, so it has to be recalculated so that the textArea can be full height

The result should be similar to this.

https://github.com/Expensify/App/assets/25520267/3fab812e-c0b1-430e-bbc5-2db6d42f7b28


@AJV009 Is your solution to not call `StyleUtils.getComposeTextAreaPadding(numberOfLinesProp)` is some condition? 

That means we don't have any padding in the composer, right? It doesn't look good.
![Screenshot 2023-08-31 at 21 03 40](https://github.com/Expensify/App/assets/25520267/28408e33-ae99-4fe3-82da-ed84eb23b66e)

**Comment by jscardona12** [comment] 2023-08-31 14:18
@mollfpr i set up padding 8px because of the condition that says that if 3 lines then padding 8px. the Error will be fixed if we delete the condition `if(numberOfLines === 3) paddingValue = 8;` because it just jumps when the lines are 3.

**Comment by mollfpr** [comment] 2023-08-31 14:23
It's a regression from https://github.com/Expensify/App/pull/19516. Before that, we depend on `styles.textInputComposeSpacing` for the padding and the value is 5px.

So I don't think your proposal is the correct solution.

**Comment by mollfpr** [comment] 2023-08-31 14:47
@jscardona12 Could you elaborate what the reason deleting `if(numberOfLines === 3) paddingValue = 8;`? Do we not need that line anymore? Have you checked if that will make the issue https://github.com/Expensify/App/issues/19358 resurface or not?

**Comment by jscardona12** [comment] 2023-08-31 15:06
@mollfpr as an alternative solution, we can also determine that those conditions just apply when `isComposerFullSize` = false. and if is true always send padding=5. that way we stay on the scope of this specifi bug, [Propasal](https://github.com/Expensify/App/issues/26222#issuecomment-1697734099) updated.

**Comment by mollfpr** [comment] 2023-08-31 15:47
Thanks @jscardona12 

I agree with the latest [proposal](https://github.com/Expensify/App/issues/26222#issuecomment-1697734099) of @jscardona12. We shouldn't change the padding value when the composer is full-size and keep the padding as 5px. This issue is a regression from https://github.com/Expensify/App/pull/19516, but the [issue](https://github.com/Expensify/App/issues/19358) has already passed the regression period. Let's fix it here.

🎀 👀 🎀 C+ reviewed!

**Comment by AJV009** [comment] 2023-08-31 18:33
Awesome :+1: 
Yeah, I was kind of suggesting depending on numberoflines was a bad idea. I meant we find another way to detect if the composer is open or not. Like the existing flags used to hide/show the icon could be reused inside getComposeTextAreaPadding to alter the padding from 5 to 8 and vice versa

But yeah cool @jscardona12 fixing on 5px looks fine I guess :+1:

**Comment by mollfpr** [comment] 2023-09-04 17:33
Friendly bump @deetergp

**Comment by deetergp** [comment] 2023-09-06 22:23
I've recreated the issue locally and tested @jscardona12's proposal and it does do the job of preventing the jumping around. Let's do it!

**Comment by jscardona12** [comment] 2023-09-07 07:20
Hi @mollfpr, @deetergp  [PR](https://github.com/Expensify/App/pull/26926) ready!

**Comment by Nathan-Mulugeta** [comment] 2023-09-18 13:08
Hey team, melvin sent an offer of 50 usd on upwork, but it should be 250 as this issue was created prior to the bounty decrease announcement on Aug 30. Also payment date is due. @strepanier03

**Comment by strepanier03** [comment] 2023-09-18 20:05
@Nathan-Mulugeta - I work PST hours so handle these when I'm online. I'll be taking care of this today so no worries there. I will also confirm the date and payment amount so you'll get the proper amount as well, but thanks for the heads up 👍

**Comment by strepanier03** [comment] 2023-09-18 20:30
### Payment Summary

- [x] External issue reporter - @Nathan-Mulugeta - $250 paid via Upwork
- [x] Contributor that fixed the issue - @jscardona12 - $1000 + $500 (speed bonus) = $1500 paid via Upwork
- [ ] Contributor+ that helped on the issue and/or PR - @mollfpr - $1000 + $500 (speed bonus) = $1500 paid via Upwork

Speed bonus assessment: @jscardona12 got assigned: 2023-09-06 / PR got merged: 2023-09-09 = 3 days [Eligible]

**Comment by strepanier03** [comment] 2023-09-18 20:31
@Nathan-Mulugeta and @jscardona12 - I've paid you both via Upwork and closed the contracts, thanks for working with us!

@mollfpr - Please go ahead and finish off the checklist here and then ping me so I can finish up the reg test step if needed and pay you out. Thanks!

**Comment by mollfpr** [comment] 2023-09-19 16:17
Sorry for the delay @strepanier03 

> [@mollfpr] The PR that introduced the bug has been identified. Link to the PR:

https://github.com/Expensify/App/pull/19516

> [@mollfpr] The offending PR has been commented on, pointing out the bug it caused and why, so the author and reviewers can learn from the mistake. Link to comment:

https://github.com/Expensify/App/pull/19516/files#r1330386926

> [@mollfpr] A discussion in #expensify-bugs has been started about whether any other steps should be taken (e.g. updating the PR review checklist) in order to catch this type of bug sooner. Link to discussion:

The regression step should be enough.

>[@mollfpr] Determine if we should create a regression test for this bug.
 [@mollfpr] If we decide to create a [regression test](https://github.com/Expensify/App/blob/main/contributingGuides/REGRESSION_TEST_BEST_PRACTICES.md) for the bug, please propose the regression test steps to ensure the same bug will not reach production again.

1. Open a report
2. In the composer, add a 3-line message
3. Click on the expand button
4. Delete all the lines
5. Add line-by-line
6. Verify that in full size, the composer doesn't jump
7. 👍 or 👎

**Comment by strepanier03** [comment] 2023-09-21 01:11
No worries @mollfpr thanks for the ping. I'll get working on this and update shortly.

**Comment by strepanier03** [comment] 2023-09-21 01:24
Reg test GH is made and I've finished paying everyone and closing contracts. 

Thanks again all, glad to have you as part of the community 🙌

**Closed by strepanier03** 2023-09-21 01:24 UTC
Labels: External, Daily, Awaiting Payment, Bug
