### ISSUE TITLE
Web – Chat – Grey image appears when edit text with image

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#47226] opened 2024-08-12 12:28 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 9.0.19-0
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**If this was caught during regression testing, add the test name, ID and link from TestRail:** N/A
**Email or phone of affected tester (no customers):** applausetester+jp_e_category_2@applause.expensifail.com
**Issue reported by:** Applause - Internal Team

## Action Performed:
1. Go to https://staging.new.expensify.com/
2. Log in
3. Navigate to any chat
4. Write something in the compose box
5. Send an attachment to a conversation while there is text in compose box
6. Edit a text message in a sent message

## Expected Result:
Image with edited text appears

## Actual Result:
Grey image with edited text appears

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details> 

https://github.com/user-attachments/assets/55aad284-4a1f-4207-bad2-e7cb6ee12a0b

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by lanitochka17** [comment] 2024-08-12 12:29
We think that this bug might be related to #vip-vsp

**Comment by codewaseem** [comment] 2024-08-12 14:42
I could not reproduce this bug.

**Comment by JmillsExpensify** [comment] 2024-08-21 12:37
We're not prioritizing vip-vsb bugs at this time so closing.

**Closed by JmillsExpensify** 2024-08-21 12:37 UTC
Labels: Daily, Overdue, Bug
