### ISSUE TITLE
[$500]  Deeplinks - Infinite loading displayed when user navigated on non-existing chat deeplink

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#33638] opened 2023-12-27 01:37 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.17.1
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** Applause - Internal Team
**Slack conversation:**

## Action Performed:
Precondition: app should be killed
1. Open app
2. Open any existing coversation
3. Hide the app
4. Open non-existing coversation deeplink https://staging.new.expensify.com/r/1234

## Expected Result:
User should be navigated on "You don't have access to this chat" page

## Actual Result:
Infinite loading displayed

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [ ] Android: mWeb Chrome
- [x] iOS: Native
- [ ] iOS: mWeb Safari
- [ ] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details> 

https://github.com/Expensify/App/assets/78819774/2a20e9b5-0832-46f8-875a-aa9907ffdca2

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01bad93f473888207b</li>
        <li>Upwork Job ID: 1739822788800614400</li>
        <li>Last Price Increase: 2024-01-24</li>
<li>Automatic offers: </li>
<ul>
<li>tienifr | Contributor | 28121883</li>
</ul></li>
    </ul>
</details>

**Comment by wildan-m** [comment] 2023-12-27 08:21
## Proposal

### Please re-state the problem that we are trying to solve in this issue.

Deeplinks - Infinite loading displayed when user navigated on non-existing chat deeplink

### What is the root cause of that problem?

Page not found page in ReportScreen doesn't have a check when the report id is not valid

### What changes do you think we should make in order to solve the problem?

Make `!report.reportID` check is first one to check before other checks.

change 

https://github.com/Expensify/App/blob/6365aebb9cdb3dd4a66e77117afd0fb1b1fa8957/src/pages/home/ReportScreen.js#L418-L429

to

```
    // eslint-disable-next-line rulesdir/no-negated-variables
    const shouldShowNotFoundPage = useMemo(
        () =>
            !report.reportID
            || (!wasReportAccessibleRef.current &&
                !firstRenderRef.current &&
                !isOptimisticDelete &&
                !reportMetadata.isLoadingInitialReportActions &&
                !isLoading &&
                !userLeavingStatus) ||
            shouldHideReport
            [report, reportMetadata, isLoading, shouldHideReport, isOptimisticDelete, userLeavingStatus],
    );
```

### What alternative solutions did you explore? (Optional)

**Comment by garrettmknight** [comment] 2023-12-29 16:12
@sobitneupane any thoughts on these proposals?

**Comment by wildan-m** [comment] 2024-01-02 00:50
[My proposal updated](https://github.com/Expensify/App/issues/33638#issuecomment-1870064103) with better solution

**Comment by garrettmknight** [comment] 2024-01-02 18:46
@sobitneupane can you give this one a look?

**Comment by sobitneupane** [comment] 2024-01-03 16:13
Sorry for the delay. I will review proposals shortly.

**Comment by sobitneupane** [comment] 2024-01-05 09:00
Thanks for the proposal @tienifr and @wildan-m 

Both of the proposal solves the issue.

@wildan-m In your [proposal](https://github.com/Expensify/App/issues/33638#issuecomment-1870064103), I don't think we need to set `isLoadingInitialReportActions` in onyx as the reportID is invalid and most probably we don't store metadata for invalid report.

Can we add `wasReportAccessibleRef.current = false;` [here](https://github.com/Expensify/App/blob/fe49e4f7fb9677a5834b53cb776f79fb20f893ce/src/pages/home/ReportScreen.js#L205) before returning? That will probably solve the issue.

https://github.com/Expensify/App/blob/fe49e4f7fb9677a5834b53cb776f79fb20f893ce/src/pages/home/ReportScreen.js#L203-L208

**Comment by wildan-m** [comment] 2024-01-05 09:27
@sobitneupane I've tried that, but it will cause not found page on previously accessible report. 

1. Open a report A
2. go to home. minimize the app (without exit)
3. Open a new deeplink with invalid report ID
4. It should show not found page
5. Press back header button, it will show not found page once more where the expected page should be report A

I think @tienifr proposal to add key to the ReportScreen is the best solution.

**Comment by garrettmknight** [comment] 2024-01-08 20:07
@sobitneupane good to assign @tienfr here then?

**Comment by sobitneupane** [comment] 2024-01-09 09:17
Thanks for the update @wildan-m. I would prefer getting it solved in `ReportScreen` page. I could not reproduce [this issue](https://github.com/Expensify/App/issues/33638#issuecomment-1878368834) constantly.
Regarding [this](https://github.com/Expensify/App/issues/33638#issuecomment-1878370540), this is most probably because the report is still loading. Can we check report metadata like isLoading(or something) to get rid of the issue?

**Comment by garrettmknight** [comment] 2024-01-15 20:30
@sobitneupane bump on this one, please!

**Comment by sobitneupane** [comment] 2024-01-16 06:19
Sorry for the delay. I will try to get to it before tomorrow EOD.

**Comment by sobitneupane** [comment] 2024-01-18 11:36
@tienifr Have you tested cases like https://github.com/Expensify/App/issues/33638#issuecomment-1878368834 and https://github.com/Expensify/App/issues/33638#issuecomment-1878370540 for your alternative proposal?

**Comment by garrettmknight** [comment] 2024-01-22 21:31
@sobitneupane with that in mind, do you have any further requests or will @tienifr 's solution be suitable?

**Comment by sobitneupane** [comment] 2024-01-24 02:34
Thanks for the update @tienifr.

As we are handling the change in reportID from `ReportScreen`. Let's go with the alternative proposal from @tienifr. But Let's make sure to test it as much as possible.

🎀👀🎀 C+ reviewed

**Comment by marcochavezf** [comment] 2024-01-25 16:52
Sounds good, thanks @sobitneupane for the review, assigning @tienifr 🚀

**Comment by sobitneupane** [comment] 2024-02-20 06:02
I am expecting updates from @tienifr in the PR.

**Comment by sobitneupane** [comment] 2024-03-05 09:16
The issue was resolved by https://github.com/Expensify/App/pull/36477 PR. So, we are going to close the PR https://github.com/Expensify/App/pull/35228 created for this issue.

**Comment by marcochavezf** [comment] 2024-03-05 17:16
Oh then the issue is no longer reproducible in main, correct?

**Comment by garrettmknight** [comment] 2024-03-08 19:14
Gotcha, gonna close in that case.

**Comment by garrettmknight** [comment] 2024-03-14 14:29
Hey @tienifr - missed the first comment. I think half payment is fair. I'll process now.

**Summary of Payments:**
- Contributor: @tienifr $250 paid via Upwork
- Reviewer: @sobitneupane $250

**Comment by garrettmknight** [comment] 2024-03-14 14:30
@sobitneupane can you request payment when you get a chance?

**Closed by garrettmknight** 2024-03-14 14:30 UTC
Labels: Reviewing, External, Engineering, Weekly, Bug

**Comment by JmillsExpensify** [comment] 2024-03-22 21:23
$250 approved for @sobitneupane based on summary.
