### ISSUE TITLE
[$250] Share code - For split expense, share code is showing E logo in center of QR code.

### ISSUE THREAD

**Issue by izarutskaya** [Expensify/App#40546] opened 2024-04-19 10:13 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.63-0
**Reproducible in staging?:** Y
**Reproducible in production?:** N
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Issue reported by:** Applause-Internal team

## Action Performed:
1. Launch app
2. Tap on a report
3. Tap plus icon -- split expense--manual
4. Enter an amount and tap split
5. Open the iou preview
6. Tap on header --- share code

## Expected Result:
On split expense, in iou details page, share code must show avatar in center of QR code and must not show E logo.

## Actual Result:
On split expense, in iou details page, share code is not showing avatar in center of QR code instead showing E logo.

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [x] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

https://github.com/Expensify/App/assets/115492554/3550deb8-6de1-4d03-a890-de62bceae65f

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01d4d48d347af843c9</li>
        <li>Upwork Job ID: 1781311072111943680</li>
        <li>Last Price Increase: 2024-04-19</li>
    </ul>
</details>

**Comment by izarutskaya** [comment] 2024-04-19 10:14
@strepanier03 I haven't added the External label as I wasn't 100% sure about this issue. Please take a look and add the label if you agree it's a bug and can be handled by external contributors.

**Comment by izarutskaya** [comment] 2024-04-19 10:15
Production 


https://github.com/Expensify/App/assets/115492554/06bebcb9-0361-4716-aff1-dae28eb70476

**Comment by shahinyan11** [comment] 2024-04-19 11:27
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
Share code - For split expense, share code is showing E logo in center of QR code.
### What is the root cause of that problem?
[Here](https://github.com/Expensify/App/blob/305f12c52ef228e7ed4845735a1794942a2b8d87/src/pages/ShareCodePage.tsx#L88) we always show  the Expensify icon if report exists
### What changes do you think we should make in order to solve the problem?
There not information  when we should show Expensify icon and wen user avatar but I suggest update [this](https://github.com/Expensify/App/blob/305f12c52ef228e7ed4845735a1794942a2b8d87/src/pages/ShareCodePage.tsx#L88C31-L88C39) condition as follows: `isReport && report.type !== CONST.REPORT.TYPE.IOU`

### What alternative solutions did you explore? (Optional)

**Comment by grgia** [comment] 2024-04-19 13:17
Not a deploy blocker, though I'm not actually sure if this is technically a bug

**Comment by shahinyan11** [comment] 2024-04-19 13:18
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
Share code - For split expense, share code is showing E logo in center of QR code.
### What is the root cause of that problem?
[Here](https://github.com/Expensify/App/blob/305f12c52ef228e7ed4845735a1794942a2b8d87/src/pages/ShareCodePage.tsx#L88) we always show  the Expensify icon if report exists
### What changes do you think we should make in order to solve the problem?
There is no exact information in which cases the Expensify icon should be displayed and in which user avatar. But i suggest to make below changes.

1. Since in there is not enough information whether the current `report` is split expenses or not we should try to get the required information from `parentReportAction`. But in this case, `paentReportAction` is a preview for the previous `reportAction` and also does not contain this information. And that's why we have to get the previous `reportAction` from the current report's `parrentReportAction` to get the information we need.  
To do that we can add below lines [here](https://github.com/Expensify/App/blob/305f12c52ef228e7ed4845735a1794942a2b8d87/src/pages/ShareCodePage.tsx#L42). ( We can also move below cod to new function in `ReportUtils.ts )
```
const parentAction = ReportActionsUtils.getReportAction(report?.parentReportID, report?.parentReportActionID)
const prevActionOfParentAction = ReportActionsUtils.getReportAction(parentAction?.reportID, parentAction?.previousReportActionID)
const isPrevActionOfParentActionSplit = ReportActionsUtils.isSplitBillAction(prevActionOfParentAction)
const shouldDisplayLogo = isReport && parentAction?.actionName !== CONST.REPORT.ACTIONS.TYPE.REPORT_PREVIEW && !isPrevActionOfParentActionSplit
```

2. Update [this](https://github.com/Expensify/App/blob/305f12c52ef228e7ed4845735a1794942a2b8d87/src/pages/ShareCodePage.tsx#L88C31-L88C39) condition as follows: `shouldDisplayLogo ?`

### What alternative solutions did you explore? (Optional)
`BE` should add needed information in current report  and we can use this info in [this](https://github.com/Expensify/App/blob/305f12c52ef228e7ed4845735a1794942a2b8d87/src/pages/ShareCodePage.tsx#L88C31-L88C39) condition

**Comment by DmitrievichLevin** [comment] 2024-04-19 17:09
## Proposal

### Please re-state the problem that we are trying to solve in this issue.

For Split Expense ShareCodeQR is showing E logo.

### What is the root cause of that problem?

- ShareCode Logo is determined by boolean isReport
- There are four report types in CONST.ts thus creating ambiguity

### What changes do you think we should make in order to solve the problem?

#### Short-Term: 
introduce another bool for whether report === CONST.REPORT.TYPE.IOU

#### Long-Term: 
Encapsulate logo ternary, would move to switch case to handle different report types with the default being expensifyLogo which is scalable.

### Demo

https://github.com/Expensify/App/assets/85088766/8a5bc00c-11b5-4d25-ac77-add2b4a19cf2



**Reminder:** Please use plain English, be brief and avoid jargon. Feel free to use images, charts or pseudo-code if necessary. Do not post large multi-line diffs or write walls of text. Do not create PRs unless you have been hired for this job.

**Comment by DmitrievichLevin** [comment] 2024-04-19 17:20
Contributor details
Your Expensify account email: jhowar39@emich.edu
Upwork Profile Link: https://www.upwork.com/freelancers/~01b18edd2e975b1033

**Comment by allroundexperts** [comment] 2024-04-21 21:54
Taking over!

**Comment by strepanier03** [comment] 2024-04-25 00:34
Confirming some expected behavior [here](https://expensify.slack.com/archives/C03U7DCU4/p1714005162987309).

**Comment by shahinyan11** [comment] 2024-04-25 07:01
> Confirming some expected behavior [here](https://expensify.slack.com/archives/C03U7DCU4/p1714005162987309).

We do not have access to this link

**Comment by strepanier03** [comment] 2024-04-25 15:59
We've decided to close this and do nothing, make no changes.

**Closed by strepanier03** 2024-04-25 15:59 UTC
Labels: External, Engineering, Daily, Help Wanted, Bug
