### ISSUE TITLE
[HOLD for payment 2023-10-18] [$500] Chat - No loading animation when scrolling through chat history offline

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#28466] opened 2023-09-29 11:52 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Open Desktop App or go to staging.new.expensify.com
2. Login to any account
3. Open chat with long history
4. Go Offline
5. Scroll chat history that has been cached

## Expected Result:
Loading animation will be shown when the cached part of the chat ends

## Actual Result:
Loading animation is not shown

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [x] MacOS / Chrome / Safari
- [x] MacOS / Desktop

**Version Number:** 1.3.75-0

**Reproducible in staging?:** Yes

**Reproducible in production?:** No

**If this was caught during regression testing, add the test name, ID and link from TestRail:**

**Email or phone of affected tester (no customers):**

**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/78819774/6e8e96e2-2e7c-4135-a110-248a2968d085

![Bug6218642_1695966451107!Production-loading-animation](https://github.com/Expensify/App/assets/78819774/7b2b09c9-e188-4ce4-bb28-8f33762520e5)

**Expensify/Expensify Issue URL:**

**Issue reported by:** Applause - Internal Team

**Slack conversation:**

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~0115f790294bf26093</li>
        <li>Upwork Job ID: 1708780525432848384</li>
        <li>Last Price Increase: 2023-10-02</li>
<li>Automatic offers: </li>
<ul>
<li>situchan | Reviewer | 27034754</li>
<li>bernhardoj | Contributor | 27034757</li>
</ul></li>
    </ul>
</details>

**Comment by kbecciv** [comment] 2023-09-29 17:55
Reproduced  with build 1.3.75-3

https://github.com/Expensify/App/assets/93399543/6b7e775c-9619-4f8b-b111-f2693bdfc268

**Comment by cristipaval** [comment] 2023-09-29 19:13
I think this regression was introduced by [this PR](https://github.com/Expensify/App/pull/26772), but I would revert it because it's a big one and brings performance optimizations. I will remove the deploy blocker and fix this as a regular issue. It's a minor UI bug reproducible in a corner(ish) use case.

**Comment by cristipaval** [comment] 2023-10-02 09:46
I think we can make this one `External`

**Comment by cristipaval** [comment] 2023-10-04 18:18
@situchan Are we waiting for more proposals on this one?

**Comment by situchan** [comment] 2023-10-04 18:49
@bernhardoj thanks for the proposal. The root cause is correct.
Can you share demo videos? (before fix and after fix)

**Comment by situchan** [comment] 2023-10-05 09:43
[Proposal](https://github.com/Expensify/App/issues/28466#issuecomment-1742481716) from @bernhardoj LGTM!
🎀 👀 🎀 C+ reviewed

**Comment by JmillsExpensify** [comment] 2023-10-17 20:49
Payment summary:

 - Issuer reporter: N/A
 - Contributor: @bernhardoj $750
 - Contributor+: @situchan $750

**Comment by JmillsExpensify** [comment] 2023-10-17 20:49
@situchan Do you mind completing the BZ checklist above?

**Comment by cristipaval** [comment] 2023-10-23 15:15
bump @situchan

**Comment by situchan** [comment] 2023-10-23 15:25
I was not able to find offending PR.
Recent PR should have reverted the changes made in https://github.com/Expensify/App/pull/26772 but git blame shows nothing. @bernhardoj it would be great if you can help finding.

As this was caught by Applause team, no need another regression test.

**Comment by JmillsExpensify** [comment] 2023-10-23 18:58
Thanks for that. Payment issued. Closing since we're also covered on regression tests.

**Closed by JmillsExpensify** 2023-10-23 18:58 UTC
Labels: External, Engineering, Daily, Awaiting Payment, Bug
