### ISSUE TITLE
[HOLD] [$1000] Web - Workspace details tab leades right to left

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#22537] opened 2023-07-09 20:28 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Open any workspace
2. Click on the workspace name
3. Click settings
4. Click on the first option "Notify me"
5. Click on the back arrow
6. Click on the back arrow again

## Expected Result:
The details tab should slides left to right

## Actual Result:
The details tab should slides right to left, and this happens only if the user clicks on 'Notify me' option, if the user click for example on welcome message option and then clicks back arrow, the details tab slides left to right

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [x] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 1.3.38-3
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/93399543/7939dcf9-048c-4169-ba81-d295fccd514a

https://github.com/Expensify/App/assets/93399543/d747687a-9e83-4214-b5de-987f17e67a97

**Expensify/Expensify Issue URL:**
**Issue reported by:** @mejed-alkoutaini
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1688909729731159

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~0179249bd90ea7ad90</li>
        <li>Upwork Job ID: 1678513905772654592</li>
        <li>Last Price Increase: 2023-07-10</li>
    </ul>
</details>

**Comment by b4s36t4** [comment] 2023-07-09 23:51
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
Web - Workspace details tab leades right to left
### What is the root cause of that problem?

RCA for this issue that how we handled routing altogether. If we observe the pattern for creating StackNavigator we placed every route related to a single section places in one navigator. Like for `InitialSettings` Screen all the screens are placed into one single Navigator.

But for the `RoomSettings` We have created two navigators `ReportDetailsModalStackNavigator`
`ReportSettingsModalStackNavigator` even though both of them are rendering on RHP

We can view the navigators here 

https://github.com/Expensify/App/blob/60f48175c9e3342ef192d878218820e5ed5a76cd/src/libs/Navigation/AppNavigator/ModalStackNavigators.js#L148

https://github.com/Expensify/App/blob/60f48175c9e3342ef192d878218820e5ed5a76cd/src/libs/Navigation/AppNavigator/ModalStackNavigators.js#L131

Because of this whenever we're Moving back from `NotificationScreen` -> `SettingsScreen` Here because of the different navigator we're getting initalIndex as `0`

https://github.com/Expensify/App/blob/60f48175c9e3342ef192d878218820e5ed5a76cd/src/libs/Navigation/Navigation.js#L54

Which is handled here -> https://github.com/Expensify/App/blob/60f48175c9e3342ef192d878218820e5ed5a76cd/src/libs/Navigation/Navigation.js#L118 pushing the `Details` Screen instead of poping (going back).

If we observe the bug report, Details page is navigated 2 times.
* One from Settings to Details
* One from Details to Details (weird)
 
### What changes do you think we should make in order to solve the problem?


We should merge these two navigators mentioned here.

https://github.com/Expensify/App/blob/60f48175c9e3342ef192d878218820e5ed5a76cd/src/libs/Navigation/AppNavigator/ModalStackNavigators.js#L131C1-L177

Working Demo (Fixed):
[op.webm](https://github.com/Expensify/App/assets/59088937/810c7475-826f-401b-a017-153978922d9d)

### What alternative solutions did you explore? (Optional)

**Comment by syedsaroshfarrukhdot** [comment] 2023-07-10 00:53
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
Web - Workspace details tab leades right to left

### What is the root cause of that problem?

If we check closely details page is being rendered twice.

- Settings to Details
- Details to Details 

As for the RoomSettings We have created two navigators ReportDetailsModalStackNavigator and ReportSettingsModalStackNavigator 

So when are using goBack callback it pushes the Details Screen instead of poping because it is already in the stack.
https://github.com/Expensify/App/blob/60f48175c9e3342ef192d878218820e5ed5a76cd/src/pages/settings/Report/ReportSettingsPage.js#L112



### What changes do you think we should make in order to solve the problem?


To fix this issue instead of using goBack call back we should use the following onBackButtonPress

           Navigation.navigate(ROUTES.getReportDetailsRoute(this.props.report.reportID))}

### What alternative solutions did you explore? (Optional)

**Comment by maddylewis** [comment] 2023-07-10 21:19
ah, i manually assigned you to this issue based on this comment - https://github.com/Expensify/App/issues/22537#issuecomment-1627968101

but lmk if you don't want to work on this one, @hungvu193

**Comment by b4s36t4** [comment] 2023-07-10 21:25
@maddylewis is this ready to pick? I think for the navigation part there's some discussion going on. Does it?

**Comment by maddylewis** [comment] 2023-07-14 00:17
okay, that makes sense to me @hungvu193. let's focus on `#21839` and i will put this one on hold for now.

**Comment by maddylewis** [comment] 2023-08-02 19:36
holding for - https://github.com/Expensify/App/issues/21839

**Comment by maddylewis** [comment] 2023-08-15 15:54
this one (https://github.com/Expensify/App/issues/21839) was likely fixed by this one (https://github.com/Expensify/App/pull/23007). 

@hungvu193 - what are your thoughts? is this one still outstanding? or did a proposal from https://github.com/Expensify/App/issues/21839 end up fixing this?

**Closed** 2023-08-21 15:07 UTC
Labels: External, Weekly, Bug
