### ISSUE TITLE
[HOLD for payment 2024-11-01] [$250] Search - Selection persists after the expense is deleted and no expense is selected

### ISSUE THREAD

**Issue by IuliiaHerets** [Expensify/App#50021] opened 2024-10-01 20:08 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 9.0.42-0
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**Email or phone of affected tester (no customers):** applausetester+kh010901@applause.expensifail.com
**Issue reported by:** Applause Internal Team

## Action Performed:
1. Go to staging.new.expensify.com
2. Submit an expense to any user.
3. Go to Search.
4. Select the submitted expense via checkbox.
5. Go back to Inbox.
6. Delete the expense in Step 2.
7. Go to Search.

## Expected Result:
The selection should reset because the expense is deleted.

## Actual Result:
The dropdown button remains as "1 selected" when the expense is deleted and no expense is selected.

## Workaround:
Unknown

## Platforms:

- [x] Android: Native
- [x] Android: mWeb Chrome
- [x] iOS: Native
- [x] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

https://github.com/user-attachments/assets/d6313f1e-e3ac-481d-bab0-ecb48d9b75c2

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~021842230940180729212</li>
        <li>Upwork Job ID: 1842230940180729212</li>
        <li>Last Price Increase: 2024-10-11</li>
<li>Automatic offers: </li>
<ul>
<li>Krishna2323 | Contributor | 104426385</li>
</ul></li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @OfstadC</details>

**Comment by IuliiaHerets** [comment] 2024-10-01 20:09
We think that this bug might be related to #wave-control

**Comment by IuliiaHerets** [comment] 2024-10-01 20:09
@OfstadC  FYI I haven't added the External label as I wasn't 100% sure about this issue. Please take a look and add the label if you agree it's a bug and can be handled by external contributors

**Comment by huult** [comment] 2024-10-02 10:43
## Proposal

### Please re-state the problem that we are trying to solve in this issue.

Selection persists after the expense is deleted and no expense is selected

### What is the root cause of that problem?

We do not update `selectedTransactionsData` when deleting one or multiple expenses.

### What changes do you think we should make in order to solve the problem?

We should update selectedTransactionsData when deleting an expense to keep it up to date, something like this:
```diff
// add function to update `selectedTransactionsData`
// .src/components/Search/SearchContext.tsx#L56
+    const updateSelectedTransactions = useCallback((selectedTransactions: SelectedTransactions) => {
+        setSearchContextData((prevState) => ({
+            ...prevState,
+            selectedTransactions,
+        }));
+    }, []);

// .src/components/Search/SearchContext.tsx#L56
 const searchContext = useMemo<SearchContext>(
        () => ({
        ...
+     updateSelectedTransactions
```

```diff
// Update function delete expense
// .src/pages/ReportDetailsPage.tsx#L718
+  const {selectedTransactions, updateSelectedTransactions, clearSelectedTransactions} = useSearchContext();

// .src/pages/ReportDetailsPage.tsx#L734
const deleteTransaction = useCallback(() => {
...
+        const updateSelectedTransactionsData = Object.keys(selectedTransactions)
+                .filter((key) => String(key) !== String(iouTransactionID)) // Ensure both are strings for comparison
+                .reduce((obj, key) => {
+                    obj[key] = selectedTransactions[key];
+                    return obj;
+                }, {});

+            if (!Object.keys(updateSelectedTransactionsData).length) {
+                clearSelectedTransactions();
+            } else {
+               updateSelectedTransactions(updateSelectedTransactionsData);
+            }
       navigateBackToAfterDelete.current = IOU.deleteMoneyRequest(iouTransactionID, requestParentReportAction, 
       isSingleTransactionView);

```
We will create this logic to handle updating `selectedTransactions` in a common way and find where an expense is deleted to call it, so we can update other components like `MoneyReportHeader`.

Note: We can optimize updateSelectedTransactions by passing `iouTransactionID` as a parameter to handle the update logic, and the component can simply call it and send the parameters. For example:

```diff
    // ReportDetailsPage.tsx or MoneyReportHeader.tsx
    updateSelectedTransactions(iouTransactionID);
    // SearchContext.tsx
    const updateSelectedTransactions = useCallback((iouTransactionID: string) => {
        const updateSelectedTransactionsData = Object.keys(searchContextData.selectedTransactions)
            .filter((key) => String(key) !== String(iouTransactionID)) // Ensure both are strings for comparison
            .reduce((obj, key) => {
                obj[key] = searchContext.selectedTransactions[key];
                return obj;
            }, {});

        setSearchContextData((prevState) => ({
            ...prevState,
            selectedTransactions: updateSelectedTransactionsData,
        }));
    }, []);

```

<summary>
<details>POC

https://github.com/user-attachments/assets/971e95ed-eefd-4e87-9d2e-bafaa3da6e03

</details>
</summary>

**Comment by MarioExpensify** [comment] 2024-10-08 18:48
@OfstadC Can you give us your input regarding @Krishna2323's comment? I'm not sure what would be our preferred behavior regarding this issue.

**Comment by MarioExpensify** [comment] 2024-10-11 18:13
@dylanexpensify hey Dylan, looks like we have divergent opinions on how to handle the filter selection when the user navigates out of search. Do you mind giving us your perspective on this?

**Comment by MarioExpensify** [comment] 2024-10-11 20:16
During the internal discussions on what would be the desired behavior and how to fix this bug in [this thread](https://expensify.slack.com/archives/C06ML6X0W9L/p1728056412575949), we agreed upon the solution that **every time the user leaves the Search tab the selected items should be reset** (meaning whenever the user comes back to Expenses Search, no expenses will be selected). This way we should not see the header with "non-existent" items being displayed as selected (which is the source of the original issue anyway).

@abzokhattab @Krishna2323 @huult feel free to review/submit new proposals for this desired behavior. @Ollyws we will need a re-review of the proposals keeping this change of behavior in mind.

Thank you everybody.

**Comment by MarioExpensify** [comment] 2024-10-14 11:27
@abzokhattab yes, I agree with this behavior. While navigating within the Search Expenses page we should keep the selection (including when opening/closing anything related to RHP/LHP). Let's clear only when navigating out of the page.

**Comment by MarioExpensify** [comment] 2024-10-15 11:43
Let's move forward with @Krishna2323 proposal with the option to keep the selection while the user does not leave the page. Thank you @Ollyws.

**Comment by OfstadC** [comment] 2024-10-28 18:37
@Ollyws please complete the BZ checklist by Thursday EOD so I can issue payment on Friday 😃 Thanks!

**Closed** 2024-11-01 15:21 UTC
Labels: External, Daily, Awaiting Payment, Bug

**Comment by garrettmknight** [comment] 2024-11-06 11:59
$250 approved for @Ollyws
