### ISSUE TITLE
Web - Upon leaving a thread message, the composer does not focus as expected

### ISSUE THREAD

**Issue by izarutskaya** [Expensify/App#25765] opened 2023-08-23 13:01 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Open a chat.
2. Send a message and click on "Reply in thread."
3. Navigate to the thread message detail.
4. Click on "Leave Thread."
5. Open any chat.
6. Observe that the composer does not retain focus

## Expected Result:
The composer should maintain focus even after leaving a thread message

## Actual Result:
Upon leaving a thread message, the composer does not focus as expected.

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [x] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** v1.3.56-18

**Reproducible in staging?:** Y

**Reproducible in production?:** Y

**If this was caught during regression testing, add the test name, ID and link from TestRail:**

**Email or phone of affected tester (no customers):**

**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/115492554/015c6b84-d71f-4ca8-9c17-63b97d5e9685

https://github.com/Expensify/App/assets/115492554/e40d2b0e-347d-4d67-9610-c42889620261

**Expensify/Expensify Issue URL:**

**Issue reported by:** @ayazhussain79

**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1691707567542429

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by ShogunFire** [comment] 2023-08-26 16:18
## Proposal

### Please re-state the problem that we are trying to solve in this issue.

The composer isn't refocus after clicking on Leave thread

### What is the root cause of that problem?

When we open a report, we verify that the modal is not visible before refocusing ther composer here:
https://github.com/Expensify/App/blob/c16995257c738761206ea07645e863ee717ecbc0/src/pages/home/report/ReportActionCompose/ReportActionCompose.js#L121-L124

To do that we verify the value in onyx, that value is updated to false when we call hideModal here:
https://github.com/Expensify/App/blob/c16995257c738761206ea07645e863ee717ecbc0/src/components/Modal/BaseModal.js#L64


In some cases like for example when we click on Leave thread we don't call hideModal but the method navigate, I have found other cases: 
- AboutPage > Report a bug
- Workspace > Go to admins

### What changes do you think we should make in order to solve the problem?

We can call hideModal each time we call navigate 

Otherwise I think a more general solution would be to update the value in onyx in the linkTo method here: https://github.com/Expensify/App/blob/c16995257c738761206ea07645e863ee717ecbc0/src/libs/Navigation/linkTo.js#L44 
we can do it if we are leaving the RHP

### What alternative solutions did you explore? (Optional)

**Comment by ayazhussain79** [comment] 2023-08-29 15:54
@conorpendergrast I have also not been able to reproduce, might be a PR created and fixed this issue as well after i reported

**Comment by conorpendergrast** [comment] 2023-08-29 16:10
Maybe! I have spent some time looking and couldn't find another issue for this. I'll close this as not-reproducible for now

**Closed by conorpendergrast** 2023-08-29 16:10 UTC
Labels: Daily, Needs Reproduction, Bug
