### ISSUE TITLE
[Awaiting checklist] [$250] Composer - Cursor Position Resets to Start of Message on Page Refresh

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#44259] opened 2024-06-24 12:59 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 9.0.1-0
**Reproducible in staging?:** Y
**Reproducible in production?:**  Y 
**If this was caught during regression testing, add the test name, ID and link from TestRail:** https://expensify.testrail.io/index.php?/tests/view/4661747&group_by=cases:section_id&group_order=asc&group_id=296775
**Email or phone of affected tester (no customers):** shussain+chrome1@applausemail.com
**Issue reported by:** Applause - Internal Team

## Action Performed:
1. Open a chat
2. Write text in composer box
3. Refresh the page

## Expected Result:
Cursor Position Should Not Resets to Start of Message on Page Refresh

## Actual Result:
Cursor Position Resets to Start of Message on Page Refresh

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details> 

https://github.com/Expensify/App/assets/78819774/a21da9ff-ec11-4db3-859a-bcdf76d3330e

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~0121d7a8303e8c6df6</li>
        <li>Upwork Job ID: 1805917059078868913</li>
        <li>Last Price Increase: 2024-07-03</li>
<li>Automatic offers: </li>
<ul>
<li>hoangzinh | Reviewer | 103037350</li>
</ul></li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @hoangzinh</details>

**Comment by lanitochka17** [comment] 2024-06-24 13:00
@twisterdotcom  FYI I haven't added the External label as I wasn't 100% sure about this issue. Please take a look and add the label if you agree it's a bug and can be handled by external contributors

**Comment by lanitochka17** [comment] 2024-06-24 13:00
We think that this bug might be related to #vip-vsp

**Comment by BartoszGrajdek** [comment] 2024-06-25 12:01
This issue is possibly related to live markdown, please add it to the project 🙏🏻  cc @thienlnam

**Comment by BartoszGrajdek** [comment] 2024-06-26 09:51
@twisterdotcom I believe this issue could be resolved by external contributors. can we open it up for proposals?

**Comment by grogou** [comment] 2024-06-27 07:58
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
Cursor position reverts to the beginning of the message when the page is refreshed.
### What is the root cause of that problem?
The root cause is that the input field’s state, including the `selection` state for cursor position, resets on page refresh. Without explicit management using setSelection, the cursor defaults to the beginning.
### What changes do you think we should make in order to solve the problem?

We need to check if value exist at first render and move cursor to the end
```js
if (value && value.length > 0) {
    setSelection({
         start: value.length,
         end: value.length
    });
}
```
Here we can add this
https://github.com/Expensify/App/blob/4ee43a3a9d7de39535f519cb1e636dd121a7e011/src/components/Composer/index.tsx#L235-L250

Contributor details
Your Expensify account email: erik.novembit@gmail.com
Upwork Profile Link: https://www.upwork.com/freelancers/~01631ccf59d885b1c2

**Comment by iCodePrograms** [comment] 2024-06-27 14:12
### Proposal
**Please re-state the problem that we are trying to solve in this issue.**
The position of the caret(vertical blinking line which determines position of text) needs to move to the end of the text when the page refreshes

**What is the root cause of that problem?**
The position of the caret is determined by the browser which happens before, after which the text is added in the input box, this results in cursor position to be in the beginning rather than the end.

**What changes do you think we should make in order to solve the problem?**
In order to solve this problem, we would have to set the position of the cursor dynamically to the end of the text whichever is added later(if it exists) for which we can use the Selection API and trigger this in one of the useEffects already in place which handles page load functionalities. 

`Selection.collapseToEnd()`

this will ensure that the caret is always placed in the end of the text. There would no need to add another useEffect or store the position of the caret everytime when the data changes in the page.

**Comment by bernhardoj** [comment] 2024-06-29 12:01
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
Cursor/selection position resets to the start of the message when refreshing.

### What is the root cause of that problem?
When the composer mounts, we already call a function to set the selection based on the text length.
https://github.com/Expensify/App/blob/4622e19c1da5137bc7b227f5b65bf3d83f96a909/src/pages/home/report/ReportActionCompose/ComposerWithSuggestions/ComposerWithSuggestions.tsx#L708-L712
https://github.com/Expensify/App/blob/4622e19c1da5137bc7b227f5b65bf3d83f96a909/src/libs/updateMultilineInputRange/index.ts#L17-L24

However, `setSelectionRange` is missing. The function doesn't exist in live markdown input.

### What changes do you think we should make in order to solve the problem?

Add `setSelectionRange` to the live markdown. We can add it when setting up the ref [here](https://github.com/Expensify/react-native-live-markdown/blob/6dd53453cc10d808835bc709349c71f2a5fa3f37/src/MarkdownTextInput.web.tsx#L535-L548).

```
r.setSelectionRange = (start, end) => {
  const newSelection = {start, end};
  contentSelection.current = newSelection;
  updateRefSelectionVariables(newSelection);
  CursorUtils.setCursorPosition(currentRef, newSelection.start, newSelection.end);
}
```

The code that we will add is actually the same as [this one](https://github.com/Expensify/react-native-live-markdown/blob/6dd53453cc10d808835bc709349c71f2a5fa3f37/src/MarkdownTextInput.web.tsx#L608-L617), but I just simplify it for testing purpose. I think we can create a new function for that to make it reusable.

But this isn't enough because there is a problem with the app composer code. There is a `useEffect` that runs every time the composer selection prop is updated. It's basically to sync the selection prop and the selection state.
https://github.com/Expensify/App/blob/4622e19c1da5137bc7b227f5b65bf3d83f96a909/src/components/Composer/index.tsx#L117-L124

The `selectionProp` is initially both 0 (start and end), but the `prevSelection` already contains the updated selection from `setSelectionRange` even though we initialize the selection state with the `selectionProp`, so the selection will be updated to the selection prop which is 0.
https://github.com/Expensify/App/blob/4622e19c1da5137bc7b227f5b65bf3d83f96a909/src/components/Composer/index.tsx#L90-L101

Based on the react doc, using a set state function updater, [the updater will be queued](https://react.dev/reference/react/useState#:~:text=If%20you%20pass%20a%20function%20as%20nextState,the%20previous%20state.%20See%20an%20example%20below.). Instead of doing that, we can just do it like this:
```
useEffect(() => {
    if (!!selection && selectionProp.start === selection.start && selectionProp.end === selection.end) {
        return;
    }
    setSelection(selectionProp);
}, [selectionProp]);
```

**Comment by twisterdotcom** [comment] 2024-07-03 09:01
One more proposal from @bernhardoj here @hoangzinh.

**Comment by bernhardoj** [comment] 2024-07-04 14:03
> but why selectionProp is initially both 0?

Because we set the initial state of the selection of the parent component (ComposerWithSuggestions) to 0.
https://github.com/Expensify/App/blob/27847125200c0b69d3371b75bc85923f4fcf6705/src/pages/home/report/ReportActionCompose/ComposerWithSuggestions/ComposerWithSuggestions.tsx#L302

It's coming from https://github.com/Expensify/App/pull/32168 to fix a safari-only issue, so we need to handle the selection manually, but the safari issue is already fixed and the workaround is removed in https://github.com/Expensify/App/pull/40295.

> Moreover, if I only apply your solution related to useEffect, it works without define setSelectionRange to the live markdown input

Oh, you're right. I found that the `onSelectionChange` of live-markdown is triggered on focus which updates the selection state. Not sure if that's expected or not, but if it's, then I think we only need to fix the `useEffect` since the safari workaround isn't needed anymore too.

**Comment by bernhardoj** [comment] 2024-07-08 15:47
Oh sorry, the `useEffect` that I meant is this one which is already in my proposal.
<img width="878" alt="image" src="https://github.com/Expensify/App/assets/50919443/16609e89-cd2d-49e3-b526-f15f7317117b">

**Comment by bernhardoj** [comment] 2024-07-09 09:49
PR is ready

cc: @hoangzinh

**Comment by mallenexpensify** [comment] 2024-07-22 21:24
Have another 'cursor position isn't in right place issue`.  If it's related to this or, or if this might fix it, plz comment on the issue
- https://github.com/Expensify/App/issues/45885

**Comment by bernhardoj** [comment] 2024-07-23 03:24
@mallenexpensify I don't think it's related because the components being used are different (the PR for this issue is already merged too)

**Comment by twisterdotcom** [comment] 2024-07-24 14:53
Payment Summary:

- @hoangzinh paid $250 [here](https://www.upwork.com/nx/wm/offer/103037350) (Reviewer)
- @bernhardoj paid $250 via NewDot Manual Request

**Comment by bernhardoj** [comment] 2024-07-24 15:09
Requested in ND.

**Comment by JmillsExpensify** [comment] 2024-07-26 00:39
$250 approved for @bernhardoj

**Comment by twisterdotcom** [comment] 2024-07-26 14:28
>please propose the [regression test](https://github.com/Expensify/App/blob/main/contributingGuides/REGRESSION_TEST_BEST_PRACTICES.md?rgh-link-date=2024-07-17T00%3A16%3A56Z) steps to ensure the same bug will not reach production again.

**Comment by mallenexpensify** [comment] 2024-07-26 22:39
Test case created
- https://github.com/Expensify/Expensify/issues/415746

**Closed by mallenexpensify** 2024-07-26 22:39 UTC
Labels: External, Daily, Bug

**Comment by perunt** [comment] 2024-07-29 07:39
Hey folks!

I came from this [PR](https://github.com/Expensify/App/pull/45052) as I was mentioned [here](https://github.com/Expensify/App/pull/23359#discussion_r1692999112).

I tested this before the fix on dev(and also on staging, but today, it potentially already has those changes) and noticed that the focus was at the end of the text input. 
 After the fix, I tested it again and found that after a refresh, the focus always moves to the end. I'm just curious if an option to preserve the cursor position has been discussed rather than moving it to the end @lanitochka17? If not, what do you think about implementing this feature? @hoangzinh
