### ISSUE TITLE
[$1000] Assign task- Only on multiple tap, "confirm task" button works

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#25695] opened 2023-08-22 15:49 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Launch app
2. Tap fab
3. Tap assign task
4. Enter title
5. Tap next
6. Select any contact for assignee
7. Tap confirm task

## Expected Result:
On single tap, " Confirm task" button must work and allow user to complete the task

## Actual Result:
Only on multiple tap, "confirm task" button works

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [ ] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 1.3.56-2

**Reproducible in staging?:** Yes

**Reproducible in production?:** Yes

**If this was caught during regression testing, add the test name, ID and link from TestRail:**

**Email or phone of affected tester (no customers):**

**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/78819774/d55d2cc1-b6e9-43d7-97f8-5e1d737eaed7

**Expensify/Expensify Issue URL:**

**Issue reported by:** Applause - Internal Team

**Slack conversation:**

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~016637cf721a90bde2</li>
        <li>Upwork Job ID: 1694056630083760128</li>
        <li>Last Price Increase: 2023-08-22</li>
    </ul>
</details>

**Comment by puneetlath** [comment] 2023-08-22 18:39
Seems like a bug. Making external. cc @thienlnam

**Comment by saalimzafar** [comment] 2023-08-22 20:23
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
The "confirm task" button functions only after being tapped multiple times to complete the task assignment.
### What is the root cause of that problem?
The root cause of this problem lies in the improper event handling approach being used. The usage of `onSubmit={() => onSubmit()} ` inside `NewTaskPage.js` creates unnecessary function instances during each render, leading to performance degradation and unreliable button behavior.
### What changes do you think we should make in order to solve the problem?
Replace the existing `onSubmit={() => onSubmit()}` syntax with the more efficient `onSubmit={onSubmit}`. By directly assigning the onSubmit 
### What alternative solutions did you explore? (Optional)
NA

**Comment by parteekcoder** [comment] 2023-08-22 20:54
## Proposal
 
### Please re-state the problem that we are trying to solve in this issue
The `confirm task ` button runs after clicking it multiple times

### What is the root cause of that problem?
In the `onSubmit` we are calling createTask function but in the createTask function, we are making API calls to the backend to store the task. Of course, the API call will take some time depending on server availability, load, and network.

```
 function onSubmit() {
         //code
         Task.createTaskAndNavigate(parentReport.reportID, props.task.title, props.task.description, props.task.assignee, props.task.assigneeAccountID, props.task.assigneeChatReport);
    }
```

```
function createTaskAndNavigate(args) {
    // code
    // API Call                  // consuming time
    Navigation.dismissModal(optimisticTaskReport.reportID);
}
```

So API call took time and hence creates delay in running `dismissModal` after ti. Also, it seems that the `confirm task` button not working but this is not the case, it depends upon the API call we are making. 

### What changes do you think we should make in order to solve the problem?
As the time taken by API call depends upon many factors so we should inform the user to wait by doing this.
After clicking `confirm task` , there should be a `loading screen` which informs the user that the app processing his/her request and going smoothly. 


### What alternative solutions did you explore? (Optional)
NA

**Comment by joh42** [comment] 2023-08-22 23:43
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
The user has no idea that task creation is in progress after clicking confirm task. The actual task creation is working as intended though. 
### What is the root cause of that problem?
There is no visual indication to the user that task creation is in progress. 
### What changes do you think we should make in order to solve the problem?

I suggest we start tracking the loading state of the task creation in the createTaskAndNavigate action
https://github.com/Expensify/App/blob/51d55de5fd22c10a3de44ce6cb36d8f36715df37/src/pages/tasks/NewTaskPage.js#L129
https://github.com/Expensify/App/blob/51d55de5fd22c10a3de44ce6cb36d8f36715df37/src/libs/actions/Task.js#L62

This could be done like it is during signin:
https://github.com/Expensify/App/blob/51d55de5fd22c10a3de44ce6cb36d8f36715df37/src/libs/actions/Session/index.js#L183

IE in the optimistic data we add isLoading with a value of true. This is then set to false in both the successData and the failureData.

To add the actual loading indication, we pass props.task.isLoading as isLoading to the submit button:
https://github.com/Expensify/App/blob/eaccec9ecc1136663242f06d8da65d2c0877af03/src/components/FormAlertWithSubmitButton.js#L24

In addition, we might want to prevent new submits while task creation is in progress. This could be done by either checking props.task.isLoading in the onSubmit function:
https://github.com/Expensify/App/blob/51d55de5fd22c10a3de44ce6cb36d8f36715df37/src/pages/tasks/NewTaskPage.js#L112

Or by disabling the submit button while creation is in progress. 

We may even want to disable the menu options (title, description etc) while task creation is in progress. This could easily be done with `disabled={props.task.isLoading}`

### What alternative solutions did you explore? (Optional)

**Comment by Pluto0104** [comment] 2023-08-22 23:46
I couldn't reproduce it on android emulator. Maybe it only appears on real device?

**Comment by parteekcoder** [comment] 2023-08-23 02:42
> I couldn't reproduce it on android emulator. Maybe it only appears on real device?

It may or may not reproduce depending on the internet you have, server loads etc. Hence it will reproduce only in certain conditions when API response delays

**Comment by Santhosh-Sellavel** [comment] 2023-08-25 18:23
I can reproduce this on a real device

**Comment by Santhosh-Sellavel** [comment] 2023-08-25 18:35
@joh42's [Proposal](https://github.com/Expensify/App/issues/25695#issuecomment-1689062136) looks good to me!
RC is clear, the proposed solution seems straightforward to me.

C+ Reviewed
🎀 👀 🎀

**Comment by Santhosh-Sellavel** [comment] 2023-08-25 18:40
@parteekcoder FullScreenLoading seems off as we can easily show the loading on the button to show the progress.

>   To do this we can maintain loading that will be set to true when user has triggered onSubmit button. We will show loading screen until loading state is true. When API call is over we will set loading to false which will remove loading screen from the screen and user smoothly move ahead.

Implementation details could be clearer, but how the loading state is maintained is unclear. Please try to provide at least an overview of the implementation, thanks!

**Comment by parteekcoder** [comment] 2023-08-25 18:43
> 

yeah sure, I will share implementation details also. Yes you are right we can go with either way first one we can show loading screen or else just show loading on the button.

I will update my proposal and let you know, thanks for  pointing out

**Comment by Santhosh-Sellavel** [comment] 2023-08-25 18:45
FullScreenLoading seems like a good option as we might need to disable other fields if we go with showing just loading on the button.

@aldo-expensify Let us know your thoughts, thanks!

**Comment by parteekcoder** [comment] 2023-08-25 18:47
> 

yes this is the advantage we get with loading screen so that user don't click other fields

**Comment by parteekcoder** [comment] 2023-08-26 03:10
@Santhosh-Sellavel I will go with the same approach as @joh42

**Comment by puneetlath** [comment] 2023-08-28 15:36
Just for my clarification. Is this happening because we are waiting for the server to respond? Because I would think that we use the optimistic without feedback design pattern here, so we'd just optimistically create the task and assume it will succeed. 

Or are we doing that and the problem is just that it takes some time and there is no UI indication that something is happening?

**Comment by parteekcoder** [comment] 2023-08-28 15:45
> 

yes @puneetlath you are right see https://github.com/Expensify/App/issues/25695#issuecomment-1688918296

**Comment by puneetlath** [comment] 2023-08-28 15:47
Ok got it. In that case, @thienlnam @aldo-expensify do you agree we should use the optimistic without feedback pattern here?

**Comment by Santhosh-Sellavel** [comment] 2023-08-28 16:09
> Ok got it. In that case, @thienlnam @aldo-expensify do you agree we should use the optimistic without feedback pattern here? 

Sounds 👍

**Comment by parteekcoder** [comment] 2023-08-28 16:36
@Santhosh-Sellavel I will go with this same approach here to maintain consistency also stated by @joh42 

https://github.com/Expensify/App/blob/main/src/pages/home/sidebar/SidebarLinks.js

**Comment by joh42** [comment] 2023-08-28 16:47
@Santhosh-Sellavel / @puneetlath Now that I look into it, it seems like we're already creating the task optimistically. So we're not waiting for the API, but the user is redirected to a task before the server has responded. Here you can see that I'm redirected before the CreateTask request has finished:


https://github.com/Expensify/App/assets/138504087/0c27d5b6-f938-4b5c-a557-af95def5c428



What takes time is the actual [createTaskAndNavigate action](https://github.com/Expensify/App/blob/51d55de5fd22c10a3de44ce6cb36d8f36715df37/src/libs/actions/Task.js#L62), but there is no UI indication showing that something is happening. As such the approach I proposed/that was adopted by another contributor will not work.

Rather, I suggest we maintain a state in the NewTaskPage, perhaps called `isWaitingForAction`. Right before we initiate the [createTaskAndNavigate action](https://github.com/Expensify/App/blob/51d55de5fd22c10a3de44ce6cb36d8f36715df37/src/libs/actions/Task.js#L62) in onSubmit, we set the state to true, and then we pass it as `isLoading={isWaitingForAction}` to the FormAlertWithSubmitButton.

**Comment by joh42** [comment] 2023-08-28 17:10
Also it's worth noting that just setting `isWaitingForAction` to true before calling the [createTaskAndNavigate action](https://github.com/Expensify/App/blob/51d55de5fd22c10a3de44ce6cb36d8f36715df37/src/libs/actions/Task.js#L62) will not actually do anything, since the component will not rerender before the action starts. I suggest we wrap the [createTaskAndNavigate action](https://github.com/Expensify/App/blob/51d55de5fd22c10a3de44ce6cb36d8f36715df37/src/libs/actions/Task.js#L62) in an empty setTimeout so the loading indication can start showing before the action begins. The result would be something like this:

https://github.com/Expensify/App/assets/138504087/68930001-baac-4756-b266-103c9b28abd3

The new implementation steps would be:
1. Add a new state called something like `isWaitingForAction` to the [NewTaskPage](https://github.com/Expensify/App/blob/main/src/pages/tasks/NewTaskPage.js)
2. Set `isWaitingForAction` to true right before we call the [createTaskAndNavigate action](https://github.com/Expensify/App/blob/51d55de5fd22c10a3de44ce6cb36d8f36715df37/src/libs/actions/Task.js#L62)
3. Wrap the call to the [createTaskAndNavigate action](https://github.com/Expensify/App/blob/51d55de5fd22c10a3de44ce6cb36d8f36715df37/src/libs/actions/Task.js#L62) in an instant setTimeout to make sure the component rerenders with the button loading
4. Pass it as isLoading={isWaitingForAction} to the FormAlertWithSubmitButton.

**Comment by saalimzafar** [comment] 2023-08-28 17:15
Anyone who can answer my question.
Why it's still an issue when the latest version is different than the one reported.
What if the simple update will fix the issue?

**Comment by thienlnam** [comment] 2023-08-28 18:29
> Anyone who can answer my question.
Why it's still an issue when the latest version is different than the one reported.
What if the simple update will fix the issue?

**Comment by thienlnam** [comment] 2023-08-28 18:31
> Why it's still an issue when the latest version is different than the one reported.
What if the simple update will fix the issue?

Because the issue still exists in this new version? If the issue doesn't exist in a new version then we don't need to address it but it doesn't seem like the case here - though let me know if that's an incorrect assumption


> Ok got it. In that case, @thienlnam @aldo-expensify do you agree we should use the optimistic without feedback pattern here?

I believe the pattern is correct, but we are not navigating to the task until the API call responds which is something we can fix here

**Comment by joh42** [comment] 2023-08-28 18:33
I think we are though @thienlnam?

https://github.com/Expensify/App/assets/138504087/0c27d5b6-f938-4b5c-a557-af95def5c428

**Comment by saalimzafar** [comment] 2023-08-28 18:38
Version Number: 1.3.56-2 is mentioned in the issue above

And currently the version available on the play store is v1.3.57-6

And I don't know what pattern is followed in version update 
Just the earlier one was v1.3.56-24   [56-24] >>> [57-6]??

**Comment by thienlnam** [comment] 2023-08-28 18:40
Hmm, why is createTaskAndNavigate taking so long then - maybe we can figure out how to optimize that so it doesn't take so long to execute?

**Comment by saalimzafar** [comment] 2023-08-28 18:47
The very first thing that needs to be checked is the version.
If it's on the latest version only then further processing should take place.
Technically it looks pointless to solve an issue which is on older version. Then what's the point of updating??
Users are often advised to keep the latest version of the application for a reason.

**Comment by joh42** [comment] 2023-08-28 18:56
I agree, it might not be the most high-value bug. On my mid-tier 2018 Android it's taking slightly over a second which is okay IMO.

Regarding the version number, the bug still exists, but it is dependent on the speed of your device.

**Comment by thienlnam** [comment] 2023-08-28 19:00
Yeah agreed, will leave it up to @puneetlath / @aldo-expensify 

Seems like this bug only exists on older android devices and is a result of the `[createTaskAndNavigate action](https://github.com/Expensify/App/blob/51d55de5fd22c10a3de44ce6cb36d8f36715df37/src/libs/actions/Task.js#L62)` taking a while to run which causes a delay in the navigation call to run right away. 

We can either
1. Figure out how to speed up the method (not sure how much we can speed this up since there are a lot of things being added 
2. Close the issue since it only really impacts slow android devices (but still works fine)
3. Some other solution mentioned above

**Comment by Santhosh-Sellavel** [comment] 2023-08-28 20:28
I can reproduce the issue on the Samsung S23 Ultra running Android 13

**Comment by saalimzafar** [comment] 2023-08-28 21:03
I can't because I recently updated the app!

**Comment by puneetlath** [comment] 2023-08-31 23:11
Ok, I think the best course of action is to close this then. The solutions don't really feel ideal to me as they are more workarounds. Also, we have some discussion going in this internal channel [here](https://expensify.slack.com/archives/C02MW39LT9N/p1693430610192649) about whether the ideal flow is to navigate to the task or to leave the user in the current context. So rather than add more logic, I think we should just accept the current behavior on slower devices.

**Closed by puneetlath** 2023-08-31 23:11 UTC
Labels: External, Daily, Help Wanted, Overdue, Bug
