### ISSUE TITLE
Compose Box - After create a group task user is not redirected to task conversation

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#51047] opened 2024-10-17 18:22 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 9.0.50
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**If this was caught on HybridApp, is this reproducible on New Expensify Standalone?:** N/A
**If this was caught during regression testing, add the test name, ID and link from TestRail:** https://expensify.testrail.io/index.php?/tests/view/5083366&group_by=cases:section_id&group_order=asc&group_id=291936
**Email or phone of affected tester (no customers):** aatweq+22222223@gmail.com
**Issue reported by:** Applause - Internal Team

## Action Performed:
1. Loggin on macOS app
2. Navigate to a Group Chat
3. Click on the + in the compose box and select "Assign task"
4. Enter a Title and a Description
5. Do not assign any group member
6. Create the task

## Expected Result:
After the user creates a task he/she should be redirected to the task conversation

## Actual Result:
After the user creates a task he/she is redirected to the group conversation

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Standalone
- [ ] Android: HybridApp
- [ ] Android: mWeb Chrome
- [ ] iOS: Standalone
- [ ] iOS: HybridApp
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

<details>
  <summary>Add any screenshot/video evidence</summary>

  
</details> 

https://github.com/user-attachments/assets/346b1e17-dc0c-4331-b9ff-917ac3e42141

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by shahinyan11** [comment] 2024-10-17 18:34
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
Compose Box - After create a group task user is not redirected to task conversation
### What is the root cause of that problem?
[Here](https://github.com/Expensify/App/blob/f95b99baddd8ac8a99499d5cad73029231cbcac8/src/libs/actions/Task.ts#L317C9-L317C49)  we navigate to parent report screen.
### What changes do you think we should make in order to solve the problem?
Update the `parentReportID` to `optimisticTaskReport.reportID` 

### What alternative solutions did you explore? (Optional)

**Comment by jaydamani** [comment] 2024-10-17 18:39
## Proposal

### Please re-state the problem that we are trying to solve in this issue.

After create a group task user is not redirected to task conversation

### What is the root cause of that problem?

When we create task, we only dismiss the modal and there is no other navigation logic.

### What changes do you think we should make in order to solve the problem?

In CreateTaskAndNavigate, Check if task has no assignee and is in group report then navigate user to the taskReport else do the current logic (dismiss modal). The condition for group report and no assignee is assumption based on steps in issue and can be changed if the requirement is different.

We need to update below portion in CreateTaskAndNavigate:
https://github.com/Expensify/App/blob/f95b99baddd8ac8a99499d5cad73029231cbcac8/src/libs/actions/Task.ts#L315-L318

**Comment by huult** [comment] 2024-10-17 19:13
## Proposal

### Please re-state the problem that we are trying to solve in this issue.

After create a group task user is not redirected to task conversation

### What is the root cause of that problem?

This issue happened because of [this ticket](https://github.com/Expensify/App/issues/30883), which states that after creating an IOU or task, the user should be redirected to the DM

https://github.com/Expensify/App/blob/f95b99baddd8ac8a99499d5cad73029231cbcac8/src/libs/actions/Task.ts#L317 

### What changes do you think we should make in order to solve the problem?
When creating a task, we have `shareDestination` and `assignee`. If the `assignee` exists, we need to redirect the user to the share destination; otherwise, redirect to the task report

```diff
//.src/libs/actions/Task.ts#L304
-  Navigation.dismissModal(parentReportID);
+ Navigation.dismissModal(assigneeAccountID ? parentReportID : optimisticTaskReport.reportID);
```
<details><summary>

https://github.com/user-attachments/assets/520d1514-713d-447a-8ad2-7dff2fe2a2e9

</summary></details>

**Comment by OfstadC** [comment] 2024-10-22 18:14
Asking about expected behavior [here](https://expensify.slack.com/archives/C05LX9D6E07/p1729620879897129)

**Comment by OfstadC** [comment] 2024-10-22 19:11
Confirmed this is expected behavior. 

We don't drop you in the expense you submitted either, you stay in the chat. So it should be the same for a task. Closing

**Closed by OfstadC** 2024-10-22 19:11 UTC
Labels: Daily, Bug
