### ISSUE TITLE
[$500] Chat - 3-Dot menu is grayed out but still active when create chat in offline mode

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#33686] opened 2023-12-28 00:56 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.18-1
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** Applause - Internal Team
**Slack conversation:**

## Action Performed:
1. Disable the internet connection
2. Search for a user that you have not opened a conversation with
3. Navigate to the header of the conversation
4. Take a note of 3-Dot menu and click on it

## Expected Result:
In offline mode 3-Dot menu is grayed out and should be not clickable

## Actual Result:
3-Dot menu is grayed out but still active when create chat in offline mode.
User can pin this conversation

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details> 

https://github.com/Expensify/App/assets/78819774/2c53d9d1-3828-4d13-b3ae-e43ca46e83ce

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by namhihi237** [comment] 2023-12-28 01:54
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
3 Dot menu is clickable in offline mode with new report
### What is the root cause of that problem?
we do not disable the threedot when the report has pendingAction is add and isOffline is true
### What changes do you think we should make in order to solve the problem?
We should add prop disabled when `pendingFields.createChat === 'add' && isOffline`
Or I think we can only disable when `pendingFields.createChat === 'add`

### What alternative solutions did you explore? (Optional)
N/A

**Comment by Tony-MK** [comment] 2023-12-28 02:43
## Proposal

### Please re-state the problem that we are trying to solve in this issue.

### What is the root cause of that problem?

When the user is offline, the `HeaderView` is dimmed if [`addWorkspaceRoomOrChatPendingAction`](https://github.com/Expensify/App/blob/376bb9563618502906032a970b09c0075c40a5d5/src/pages/home/ReportScreen.js#L179) is `true`. Hence by default, the [`ThreeDotsMenu`](https://github.com/Expensify/App/blob/376bb9563618502906032a970b09c0075c40a5d5/src/pages/home/HeaderView.js#L289-L292) component is enabled. The `HeaderView` only uses `shouldShowThreeDotsButton` to check if it can display it. 

https://github.com/Expensify/App/blob/376bb9563618502906032a970b09c0075c40a5d5/src/pages/home/HeaderView.js#L288-L292

### What changes do you think we should make in order to solve the problem?


We use the same condition, [`addWorkspaceRoomOrChatPendingAction`](https://github.com/Expensify/App/blob/376bb9563618502906032a970b09c0075c40a5d5/src/pages/home/ReportScreen.js#L179) from `ReportUtils.getReportOfflinePendingActionAndErrors`, as the `ReportScreen` component and set it as the value for the disabled prop in the [`ThreeDotsMenu`](https://github.com/Expensify/App/blob/376bb9563618502906032a970b09c0075c40a5d5/src/pages/home/HeaderView.js#L289-L292) component.
```
...
disabled={addWorkspaceRoomOrChatPendingAction}
...
```

**Comment by yh-0218** [comment] 2023-12-28 06:54
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
3 Dot menu is clickable in offline mode with new report
### What is the root cause of that problem?
https://github.com/Expensify/App/blob/376bb9563618502906032a970b09c0075c40a5d5/src/pages/home/HeaderView.js#L288-L288
we don't have disable here.
I think we don't need to disable.
We need pin and something on off-line.
### What changes do you think we should make in order to solve the problem?
We need to add `&& !isOffline` here
https://github.com/Expensify/App/blob/9e81447833a4b9f9ea34a91f01185b0687ddb66a/src/pages/home/HeaderView.js#L173
### What alternative solutions did you explore? (Optional)

<img width="607" alt="Screenshot 2023-12-28 at 8 54 30 AM" src="https://github.com/Expensify/App/assets/65789015/5dc1d63d-dedf-4126-85ec-6a3412f2b6c1">

**Comment by techienaren** [comment] 2023-12-28 11:10
This behavior aligns with the 'Optimistic WITH Feedback Pattern'. In offline mode, actions like the 3-Dot menu are greyed out to show they're queued but not yet processed. I think this isn't a bug, but intended functionality.

**Comment by abdulrahuman5196** [comment] 2023-12-28 17:40
I am not sure if this is a bug. @garrettmknight Can you clarify?

**Comment by garrettmknight** [comment] 2023-12-29 16:08
I'd agree that this is intended. @lanitochka17 can you point me to the test this came from?

**Comment by techienaren** [comment] 2023-12-29 16:39
Hi @garrettmknight I'd like to contribute to the project. I'm trying to set up the project and need a Mapbox token as instructed. But I can't access the Slack thread for help because I don't have Slack access yet. I've already requested a Slack invite as instructed. Could someone help me with the Mapbox setup or grant me access to the Slack channel? Thanks

**Comment by garrettmknight** [comment] 2024-01-02 18:34
@lanitochka17 going to close this one, but let me know the test you found this on when you see this.

**Closed by garrettmknight** 2024-01-02 18:34 UTC
Labels: Daily, Overdue, Bug

**Comment by lanitochka17** [comment] 2024-01-03 22:50
@garrettmknight  Hello 
An issue was encountered while executing these steps:
https://expensify.testrail.io/index.php?/tests/view/4092459

**Comment by garrettmknight** [comment] 2024-01-05 14:01
Got it, we can optimistically work with all the 3 dot menu stuff so I think this is expected.
