### ISSUE TITLE
Taxes - Tax amount input in transaction thread is not auto-focused

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#39601] opened 2024-04-04 13:24 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.60-1
**Reproducible in staging?:** y
**Reproducible in production?:** n
**Issue reported by:** Applause - Internal Team

## Action Performed:
Precondition:
- User is an employee of Collect workspace that has taxes.
1. Go to staging.new.expensify.com
2. Go to workspace chat.
3. Start manual request flow.
4. In confirmation page, click Show more > Tax amount.
5. Note that Tax amount input is auto focused.
6. Create the request with tax.
7. Go to transaction thread.
8. Click Tax amount.

## Expected Result:
Tax amount input in transaction thread will be auto focused.

## Actual Result:
Tax amount input in transaction thread is not auto focused.

## Workaround:
n/a

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [x] Android: mWeb Chrome
- [x] iOS: Native
- [x] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

https://github.com/Expensify/App/assets/93399543/8b75a419-04d4-4c0f-88d7-185bf18f4508

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by kbecciv** [comment] 2024-04-04 13:25
We think that this bug might be related to #wave-collect - Release 1

**Comment by rlinoz** [comment] 2024-04-04 14:13
I think this is related to this PR https://github.com/Expensify/App/pull/33927 since it is a new feature.

cc: @alitoshmatov @rezkiy37

**Comment by rlinoz** [comment] 2024-04-04 14:13
But we don't have to block on this, so removing the label.

**Comment by MonilBhavsar** [comment] 2024-04-04 14:56
We'll be fixing this as a regression

**Comment by MonilBhavsar** [comment] 2024-04-05 05:44
PR is merged!

**Comment by rlinoz** [comment] 2024-04-12 11:37
Deployed to production: https://github.com/Expensify/App/pull/39675#issuecomment-2048099244

So I am closing this one.

**Closed by rlinoz** 2024-04-12 11:37 UTC
Labels: Reviewing, Engineering, Weekly
