### ISSUE TITLE
mweb - OlDdot - User gets infinite loading when opening a WS from old dot app

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#10271] opened 2022-08-05 18:34 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:1. Open the Old dot Prod app
Precondition: signed out of NewDot on mobile web
1. Open the Old dot Prod app
2. Sign into a valid account (Expensifail)
3. Tap on the "Get started" on the inbox task that says "Would you like to get started with our free plan?".

## Expected Result:
User is redirected to NewDot on mWeb with the workspace settings page open.

## Actual Result:
The user is redirected to mweb, however the page never loads and the new workspace is never created. The user is faced with infinite loading.

## Workaround:
Unknown

## Platform:

Where is this issue occurring?

- Web
- iOS
- Android
- Desktop App
- Mobile Web

**Version Number:** 1.1.88.1

**Reproducible in staging?:** Yes

**Reproducible in production?:** Yes

**Email or phone of affected tester (no customers):** applausetester+emilio456@applause.expensifail.com/Emilio98

**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Notes/Photos/Videos:** Any additional supporting documentation

https://user-images.githubusercontent.com/93399543/183139971-5d977343-a751-4069-b405-34b0692e3c69.mp4

**Expensify/Expensify Issue URL:** 

**Issue reported by:** Applause - Internal Team

**Slack conversation:** 

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by madmax330** [comment] 2022-08-08 10:48
Will try to repro this today

**Comment by madmax330** [comment] 2022-08-11 07:21
Focused on Global reimbursements now, will drop this back in the pool

**Comment by tgolen** [comment] 2022-08-17 21:57
I was able to reproduce this locally. The page on NewDot sits at a spinner forever. If I refresh the page, then the workspace is created properly and everything continues as expected.

Debugging further to see what's going on.

**Comment by tgolen** [comment] 2022-08-17 22:12
@neil-marcellini Can you help me with this? I traced the code to [this](https://github.com/Expensify/App/blob/2dc22a47089033663b46ab3aaa6901e2c15553da/src/pages/LogOutPreviousUserPage.js#L25) and found that `isLoggingInAsNewUser` is `false`, so in effect, nothing is happening and the user stays on that page just looking at the spinner.

This happens every time I try it after I've logged off of NewDot before going from OldDot > NewDot.

It's `false` because my session email (which is a valid email, the same I signed into OldDot with) is the same as the email in the URL.

If that's the case, and the emails are the same, shouldn't we call `Session.signInWithShortLivedToken(email, shortLivedToken);`?

**Comment by tgolen** [comment] 2022-08-17 22:24
Actually, maybe that's not it. I'm now digging into `setUpPoliciesAndNavigate()` because I think it's something to do with that.

**Comment by tgolen** [comment] 2022-08-17 22:26
@arosiclair It might be related to your recent PR? https://github.com/Expensify/App/pull/10122

**Comment by arosiclair** [comment] 2022-08-18 16:05
> @arosiclair It might be related to your recent PR? #10122

Possibly. Just gave it a few tries in dev with OldDot Web and NewDot Web and the transition worked even when Newdot was signed out. Which platforms can you repro with?

**Comment by tgolen** [comment] 2022-08-18 16:13
I'm just doing it on web. I can repro it every time. I will try to get a video of it for you just to make sure we are doing the same things

**Comment by tgolen** [comment] 2022-08-18 16:22
Haha, of course. When I try to record it, it works perfectly fine the first time. 

I made sure I was on the latest version of `main` for both repos and made sure to ran `npm i` in both repos and `composer install` for web-e.

Maybe that had something to do with it. I'm going to close this since neither of us can reproduce it now.

**Comment by isagoico** [comment] 2022-08-24 15:34
@tgolen I'm able to reproduce this issue on build 1.1.89-0 when transitioning from OldDot mWeb to NewDot when logged in with a different account in NewDot
1. Log in to NewDot with account A
2. Navigate to OldDot and log in with account B 
3. Select the option to "Set up your company for free" 
4. Infinite loading displayed, after a little while a empty error is shown (sometimes) 

https://user-images.githubusercontent.com/44479856/186458655-1d22f72c-a5f7-46b5-9a63-feedac36734e.mp4

**Comment by tgolen** [comment] 2022-08-24 16:46
OK, thanks for letting me know. @arosiclair is working on a little refactor to that code in this PR: https://github.com/Expensify/App/pull/10494 so once that is deployed, let's re-evaluate if this still happens or not.

**Comment by tgolen** [comment] 2022-09-13 15:45
This kind of broke again, but @arosiclair is continuing to dig into this so I'm going to reassign this issue to him.

**Closed** 2022-09-22 17:00 UTC
Labels: Reviewing, Engineering, Weekly, Improvement
