### ISSUE TITLE
Able to by pass the legal name errors

### ISSUE THREAD

**Issue by kavimuru** [Expensify/App#19778] opened 2023-05-29 22:10 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Go to staging dot on web chrome
2. Go to profile > personal details > Legal name
3. Try to remove last name and click on save and notice that it throws an error stating all the fields are required
4. But now use any Spanish language and try to add that Spanish word on the last name and click on save.
5. If you click again on the legal name, the last name will be empty as it didn't count the Spanish word and we're able to bypass the legal name
## Expected Result: 
The legal name should have thrown error to prevent having an empty first/last name
## Actual Result: 
Able to by pass the legal name errors
## Workaround:
Can the user still use Expensify without this being fixed? Have you informed them of the workaround?

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [x] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 1.3.19-6
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/43996225/3401d3c0-99c7-4bc5-a2a0-1fcf27966547

https://github.com/Expensify/App/assets/43996225/a2cb1616-a8e0-4850-8f51-ec09cc2ddb40

**Expensify/Expensify Issue URL:**
**Issue reported by:** @priya-zha
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1685090896330549

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by jliexpensify** [comment] 2023-05-30 00:16
I can repro on v1.3.20-0, but this a dupe of https://github.com/Expensify/App/issues/17628

**Closed** 2023-05-30 00:16 UTC
Labels: Daily, Bug
