### ISSUE TITLE
[Workspace Feeds] Web - Card - Added bank account isn't showing for Expensify Card

### ISSUE THREAD

**Issue by IuliiaHerets** [Expensify/App#47239] opened 2024-08-12 15:00 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 9.0.19-0
**Reproducible in staging?:** Y
**Reproducible in production?:** Can't check
Issue was found when executing this PR https://github.com/Expensify/App/pull/46860
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:**
**Slack conversation:**

## Action Performed:
1. Navigate to https://staging.new.expensify.com/
2. Log in with a new Expensifail account
3. Create a workspace
4. Navigate to Workspace settings - More features
5. Enable "Expensify Card"
6. Enable "Workflows"
7. Navigate to Workflows - Connect bank account
8. Add Regions bank with plaid
9. Navigate to Workspace settings - Expensify Card
10. Click on the "Issue new card" button

## Expected Result:
I should be able to see and choose the existing bank account.

## Actual Result:
Added bank account isn't showing for Expensify Card. I can add the missing bank account if I go a step further and click on "Add a new bank account". The bank account also shows up after a relog.

## Workaround:
Unknown

## Platforms:

- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

https://github.com/user-attachments/assets/c13b8fa0-1d09-4ced-8a79-2baa8918e1ce

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by IuliiaHerets** [comment] 2024-08-12 15:00
We think that this bug might be related to #wave-collect - Release 2

**Comment by mountiny** [comment] 2024-08-12 23:26
@IuliiaHerets Can you please check if this is reliably repro by other testers or across platforms? 

cc @koko57 @VickyStash for viz

**Comment by mountiny** [comment] 2024-08-12 23:27
Happy to take over Robert if you want

**Comment by IuliiaHerets** [comment] 2024-08-13 04:38
@mountiny As soon as the team has checked, I'll get back to you with an answer

**Comment by koko57** [comment] 2024-08-13 08:16
looks like the same root cause like in this one: https://github.com/Expensify/App/issues/45729
so either we don't receive a properly formatted data or the account is not eligible (but in the second case we should be redirected to VBBA, it should have been fixed by my last merged PR https://github.com/Expensify/App/pull/46564)

**Comment by IuliiaHerets** [comment] 2024-08-13 11:55
@mountiny QA Team still can reproduce the issue on different platforms (Web, iOS app, Android app). Build - v9.0.19-9

https://github.com/user-attachments/assets/7fa29e98-7a0b-4762-9256-cd2a9e596005


https://github.com/user-attachments/assets/805a71bd-3a9a-4e28-9f90-299e30a1fdaa


https://github.com/user-attachments/assets/c438afb9-6171-4495-b3a4-4e0c136c9a0d

**Comment by koko57** [comment] 2024-08-13 13:51
The problem is definitely with the format we get from AcceptACHContractForBankAccount and OpenPaymentsPage API calls  - we don't get a bank account with `type` and `allowDebit` properties - that's why we get an empty list. Before we've filtered out eligible bank account we had the problem described in this issue https://github.com/Expensify/App/issues/45729

here's how we get the data for AcceptACHContractForBankAccount
<img width="454" alt="Screenshot 2024-08-13 at 15 16 44" src="https://github.com/user-attachments/assets/b852c4b9-6199-465c-949f-1869d4bcf530">
<img width="435" alt="Screenshot 2024-08-13 at 15 16 33" src="https://github.com/user-attachments/assets/e4ce7892-70a8-45ab-8e2e-25e6dc75ead9">

and for OpenPaymentsPage
<img width="426" alt="Screenshot 2024-08-13 at 15 36 32" src="https://github.com/user-attachments/assets/a0a74c3a-c8b2-4f6b-9f03-23f67396e7e7">
<img width="578" alt="Screenshot 2024-08-13 at 15 17 40" src="https://github.com/user-attachments/assets/f750104e-efd4-40d3-9801-a70adb8ff4c8">

We could possibly call OpenPaymentsPage when we click Issue New Card, but it would be much better to unify how the data is sent from the backend and maybe change the onyx method in the OpenPaymentsPage from set to merge

**Comment by mountiny** [comment] 2024-08-13 15:16
I will have a look thanks!

**Comment by mountiny** [comment] 2024-08-14 14:32
PR  is up here https://github.com/Expensify/Auth/pull/12043 that should start returning these properties

**Comment by mountiny** [comment] 2024-08-15 10:31
@koko57 @DylanDylann @allgandalf could you please retest this? Now the `AcceptACHContractForBankAccount` should return the bank account with the type and allowDebit too

**Comment by koko57** [comment] 2024-08-20 08:02
I will retest it today

**Comment by koko57** [comment] 2024-08-20 13:15
@mountiny 
So this issue is solved - we get `type` and `allowDebit`  and the account is showing in the account list.
<img width="534" alt="Screenshot 2024-08-20 at 14 40 33" src="https://github.com/user-attachments/assets/daffd8c0-3b61-43ec-bfea-e6d8eab94433">

<img width="538" alt="Screenshot 2024-08-20 at 15 08 35" src="https://github.com/user-attachments/assets/11231f69-2dd4-4e47-9ff8-215274c21248">

We still have the https://github.com/Expensify/App/issues/45729 problem, because we still don't get `accountNumber` in the `AcceptACHContractForBankAccount`. But this can be solved by using `mask` property from `additionalData`. 

cc @s77rt

**Comment by mountiny** [comment] 2024-08-26 23:45
@koko57 The backend changes for this are deployed now, can you check if you can still repro your issue?

**Comment by koko57** [comment] 2024-08-27 13:40
@mountiny accountNumber is sent now but not the same way it is sent in `OpenPaymentsPage` - we get this in accountData in `OpenPaymentsPage` when in `AcceptACHContractForBankAccount` in the bankAccount object
<img width="479" alt="Screenshot 2024-08-27 at 15 35 12" src="https://github.com/user-attachments/assets/2384ab1a-5ce2-4c81-b037-5db5f2253dda">
<img width="322" alt="Screenshot 2024-08-27 at 15 32 47" src="https://github.com/user-attachments/assets/077b9d74-e872-4598-91c8-c8c66fcaabe7">

**Comment by mountiny** [comment] 2024-08-27 22:31
@koko57 damn ok updating this, I must have mixed it up in the previous screenshots.

**Comment by koko57** [comment] 2024-08-29 09:01
@mountiny please let me know when it's ready to retest

**Comment by mountiny** [comment] 2024-09-02 11:13
@koko57 This is ready to test, can you please have a look?

**Comment by koko57** [comment] 2024-09-02 12:05
<img width="1357" alt="Screenshot 2024-09-02 at 14 05 12" src="https://github.com/user-attachments/assets/273bc0e6-433b-4560-817d-ae1b5c3fa777">

Confirming it's working - bank account is showing after adding it.

**Comment by mountiny** [comment] 2024-09-02 12:09
So I believe we can close this one now, thank you for confirming

**Closed by mountiny** 2024-09-02 12:09 UTC
Labels: Reviewing, Engineering, Daily, Bug
