### ISSUE TITLE
[HOLD for payment 2024-05-09] [$500]  Hold Request - "Hold" banner is aligned to the top when there is scan request message

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#37536] opened 2024-02-29 17:44 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.45-1
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** Applause - Internal Team
**Slack conversation:**

## Action Performed:
1. Go to staging.new.expensify.com
2. Go to 1:1 DM
3. Create a scan request
4. Go to request details page
5. Click 3-dot menu > Hold request
6. Add a reason and save it

## Expected Result:
The "Hold" banner will be aligned in the middle of the given space

## Actual Result:
The "Hold" banner is aligned to the top of the given space when there is scan request message

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [x] Android: mWeb Chrome
- [x] iOS: Native
- [x] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details> 

https://github.com/Expensify/App/assets/78819774/ac162ac6-0f68-43c6-86b4-ee2d786feebe

<img width="1440" alt="Bug6397350_1709227408781!Screenshot_2024-03-01_at_01 12 12" src="https://github.com/Expensify/App/assets/78819774/313ee2d7-1d5d-4bb4-84dc-ea9063f2294f">

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01dd5d1b7c81a77704</li>
        <li>Upwork Job ID: 1763306586849918976</li>
        <li>Last Price Increase: 2024-03-07</li>
<li>Automatic offers: </li>
<ul>
<li>neonbhai | Contributor | 0</li>
</ul></li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @isabelastisser</details>

**Comment by lanitochka17** [comment] 2024-02-29 17:45
@isabelastisser  I haven't added the External label as I wasn't 100% sure about this issue. Please take a look and add the label if you agree it's a bug and can be handled by external contributors

**Comment by isabelastisser** [comment] 2024-02-29 20:54
I confirmed this can be handled externally. @Santhosh-Sellavel to review the proposals above. Thanks!

**Comment by godofoutcasts94** [comment] 2024-02-29 21:15
This is my [proposal](https://github.com/Expensify/App/issues/37536#issuecomment-1971791690).

**Comment by godofoutcasts94** [comment] 2024-03-01 04:47
Updated [Proposal](https://github.com/Expensify/App/issues/37536#issuecomment-1971791690)

**Comment by askavyblr** [comment] 2024-03-01 05:51
### Proposal
**Please re-state the problem that we are trying to solve in this issue.**

Hold Request - "Hold" banner is aligned to the top when there is a scan request message

**What is the root cause of that problem?**

Missing top padding styles.pt3

What changes do you think we should make in order to solve the problem?

Need to add top padding styles.pt3

https://github.com/Expensify/App/blob/48657b48505e40fecc7c6f43da903aadb12d549a/src/components/HoldBanner.tsx#L13

What alternative solutions did you explore? (Optional)

N/A

![Padding issue](https://github.com/Expensify/App/assets/125897912/2ec232c5-56f1-4af7-b94c-b795457f3dbd)

**Comment by dragnoir** [comment] 2024-03-01 16:10
## Proposal

### Please re-state the problem that we are trying to solve in this issue.

A seperator botween Scanning and HOLD

### What is the root cause of that problem?

The component MoneyRequestHeaderStatusBar for Scanning is showing the border bottom when HOLD is diplayed

https://github.com/Expensify/App/blob/de3a9e12083963d1b36b4d081364484f8cf98b57/src/components/MoneyRequestHeader.tsx#L180-L194


### What changes do you think we should make in order to solve the problem?

Disable the border on the bottom from the Scanning part when the HOLD is diplayed
```diff
{!isScanning && (
  <MoneyRequestHeaderStatusBar
    title={translate('iou.receiptStatusTitle')}
    description={translate('iou.receiptStatusText')}
-     shouldShowBorderBottom
+     shouldShowBorderBottom={!isOnHold}
  />
)}
```

POC:
![image](https://github.com/Expensify/App/assets/12425932/641c8de0-9543-40c3-a4a3-c0f718d18dd9)

### What alternative solutions did you explore? (Optional)

**Comment by Santhosh-Sellavel** [comment] 2024-03-04 18:08
I've been OOO, will check this in a day

**Comment by shawnborton** [comment] 2024-03-04 18:36
Whoa! I would think that we only ever show one of these banners at once. cc @trjExpensify @JmillsExpensify 

Also, why are the banner styles so different? The font colors and font sizes are way different across the badge and the message next to it. cc @robertjchen - any context there?

**Comment by JmillsExpensify** [comment] 2024-03-04 18:46
Yeah you shouldn't be able to hold a scanning request. That feels like the solution in my opinion.

**Comment by shawnborton** [comment] 2024-03-04 18:50
@robertjchen are we addressing the general styles of the hold banner anywhere? Also, we should take a look at those styles alongside the updated next steps banner styles that I think @dannymcclain is working on?

**Comment by dubielzyk-expensify** [comment] 2024-03-05 23:32
> Yeah you shouldn't be able to hold a scanning request. That feels like the solution in my opinion.

That makes sense to me too.

**Comment by shawnborton** [comment] 2024-03-06 13:51
I also think whatever proposal we accept here should try to align the styles of the hold banner to look just like the Pending/Scanning banner, but instead of a gray BG for the badge, we can just use danger red. 
![CleanShot 2024-03-06 at 08 50 06@2x](https://github.com/Expensify/App/assets/2319350/70196141-cf99-4fb8-aaba-3f58bf15edc1)

Though I realize this might change with Danny's next steps banner project, but let's at least align them in the meantime.

**Comment by godofoutcasts94** [comment] 2024-03-06 14:16
Updated [Proposal](https://github.com/Expensify/App/issues/37536#issuecomment-1971791690)

**Comment by dragnoir** [comment] 2024-03-06 15:10
New update with the last design feedback on [my proposal](https://github.com/Expensify/App/issues/37536#issuecomment-1973464572)

**Comment by robertjchen** [comment] 2024-03-07 04:50
> @robertjchen are we addressing the general styles of the hold banner anywhere? Also, we should take a look at those styles alongside the updated next steps banner styles that I think @dannymcclain is working on?

Definitely! I think this is the only banner involved and we can address it in this PR 👍

**Comment by isabelastisser** [comment] 2024-03-07 21:02
Not overdue.

**Comment by isabelastisser** [comment] 2024-03-11 13:36
It looks like we're waiting for [PR.](https://github.com/Expensify/App/issues/37536#issuecomment-1982342352)

**Comment by isabelastisser** [comment] 2024-03-11 13:41
@Santhosh-Sellavel, can you please provide an update?

**Comment by godofoutcasts94** [comment] 2024-03-11 18:21
@Santhosh-Sellavel How about mine https://github.com/Expensify/App/issues/37536#issuecomment-1971791690 ?

**Comment by Santhosh-Sellavel** [comment] 2024-03-11 18:32
Check our guidelines [here](https://github.com/Expensify/App/blob/main/contributingGuides/CONTRIBUTING.md#propose-a-solution-for-the-job)
> If you want to make an entirely new proposal or update an existing proposal, please go back and edit your original proposal, then post a new comment to the issue in this format to alert everyone that it has been updated:

You've made numerous edits but didn't notify the updates every time. As I your edit history, edits were made after a new proposal or updates from someone else.

**Comment by godofoutcasts94** [comment] 2024-03-11 18:38
@Santhosh-Sellavel Its not like that for every every new proposal I have edits in my proposal. It was more like if I have forgot to include something like the working video or something that was really necessary for the issue. Also, one more thing I am extremely apologetic for not updating about all the updates that I have made to my proposal. I will keep that in mind in future.

**Comment by godofoutcasts94** [comment] 2024-03-11 18:40
Edited [Comment](https://github.com/Expensify/App/issues/37536#issuecomment-1989182140)

**Comment by Santhosh-Sellavel** [comment] 2024-03-11 18:40
> > Yeah you shouldn't be able to hold a scanning request. That feels like the solution in my opinion.
> 
> Aligning with this @neonbhai's [proposal](https://github.com/Expensify/App/issues/37536#issuecomment-1979995972) looks good & straightforward on that part.
> 
> @neonbhai How would you achieve this [requirement](https://github.com/Expensify/App/issues/37536#issuecomment-1980921467)?

I like @dragnoir's idea from [here](https://github.com/Expensify/App/issues/37536#issuecomment-1973464572) for updating the styles for this [requirement](https://github.com/Expensify/App/issues/37536#issuecomment-1980921467)?

> We can use the same component MoneyRequestHeaderStatusBar instead of HoldBanner adding a new prop for style (backgroundColor to danger).

So let's hire both @neonbhai & @dragnoir here and split the job fee!

**Comment by Santhosh-Sellavel** [comment] 2024-03-11 18:46
@godofoutcasts94 Anyways, please refrain from doing the same in future jobs. Mistakes are bound to happen when we rush into submitting proposals, especially on simple issues like this, thanks!

**Comment by godofoutcasts94** [comment] 2024-03-11 18:48
> @godofoutcasts94 Anyways, please refrain from doing the same in future jobs. Mistakes are bound to happen when we rush into submitting proposals, especially on simple issues like this, thanks!

okay thanks for updating. Can you please review my proposal and give me one chance? @Santhosh-Sellavel

**Comment by Santhosh-Sellavel** [comment] 2024-03-11 18:50
> > Yeah you shouldn't be able to hold a scanning request. That feels like the solution in my opinion.
> 
> Aligning with this @neonbhai's [proposal](https://github.com/Expensify/App/issues/37536#issuecomment-1979995972) looks good & straightforward on that part.
> 
> @neonbhai How would you achieve this [requirement](https://github.com/Expensify/App/issues/37536#issuecomment-1980921467)?

I like @dragnoir's idea from [here](https://github.com/Expensify/App/issues/37536#issuecomment-1973464572) for updating the styles for this [requirement](https://github.com/Expensify/App/issues/37536#issuecomment-1980921467)?

> We can use the same component MoneyRequestHeaderStatusBar instead of HoldBanner adding a new prop for style (backgroundColor to danger).

So let's hire both @neonbhai & @dragnoir here and split the job fee!
 
 C+ Reviewed
 🎀 👀 🎀

**Comment by Santhosh-Sellavel** [comment] 2024-03-14 17:03
bump @francoisl

**Comment by francoisl** [comment] 2024-03-14 18:41
Ok, I think it's fine to split the bounty, but to clarify, who would be submitting the PR then?

**Comment by isabelastisser** [comment] 2024-04-11 20:18
@dragnoir, can you please provide an update? Thanks!

**Comment by shawnborton** [comment] 2024-04-22 12:26
For payment, @isabelastisser can we consider increasing the pay out to @dragnoir given that they went beyond the original bug scope and did a badge refactor that I asked for? Thanks!

**Comment by isabelastisser** [comment] 2024-04-24 18:48
Hey @shawnborton, can you please bring this for discussion in bug-zero in Slack? Thanks!

**Comment by isabelastisser** [comment] 2024-05-08 21:34
Not overdue. 

@Santhosh-Sellavel, please complete the BZ list above before I can process the payments in Upwork and close the issue. Thanks!

**Comment by isabelastisser** [comment] 2024-05-13 17:11
It looks like @Santhosh-Sellavel is OOO until May 15. I've sent them a DM for visibility.

**Comment by isabelastisser** [comment] 2024-05-16 17:20
Bump @Santhosh-Sellavel

**Comment by francoisl** [comment] 2024-05-16 22:20
Works for me. @isabelastisser feel free to process the payments and close the issue. Thanks!

**Comment by neonbhai** [comment] 2024-05-16 22:27
Noting that the PR was reviewed by me [here](https://github.com/Expensify/App/pull/38471#issuecomment-2078292841) but seems like the automation didn't mention it. Please take a look :bow:

cc: @isabelastisser

**Comment by isabelastisser** [comment] 2024-05-17 20:06
Based on @shawnborton's comment [here](https://github.com/Expensify/App/issues/37536#issuecomment-2069266968), I'm increasing the payment to @dragnoir to $750.

Payments summary:

@dragnoir requires payment $750 (manual offer https://www.upwork.com/nx/wm/offer/102358820)
@neonbhai requires payment [automatic offer](https://www.upwork.com/nx/wm/offer/0) (Contributor) $500
@Santhosh-Sellavel requires payment through NewDot Manual Requests $500 `PENDING`

**Comment by isabelastisser** [comment] 2024-05-17 20:06
All set!

**Closed by isabelastisser** 2024-05-17 20:06 UTC
Labels: External, Daily, Awaiting Payment, Bug

**Comment by neonbhai** [comment] 2024-05-17 20:13
@isabelastisser hi, the original job was split with me and @dragnoir. As noted here https://github.com/Expensify/App/issues/37536#issuecomment-1989185436 

I also ended up reviewing one of the linked PRs, so the payout would be $250 + $500 for me! Please take a look :bow:

**Comment by Santhosh-Sellavel** [comment] 2024-05-22 18:14
Requested on ND

**Comment by JmillsExpensify** [comment] 2024-05-31 04:32
$500 approved for @Santhosh-Sellavel
