### ISSUE TITLE
[$250] Split- 'Guest' is counted twice in Public room 

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#43290] opened 2024-06-07 13:55 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.80-9
**Reproducible in staging?:**Y
**Reproducible in production?:** Y
**If this was caught during regression testing, add the test name, ID and link from TestRail:** https://expensify.testrail.io/index.php?/tests/view/4605118
**Issue reported by:** Applause - Internal Team

## Action Performed:

Admin (User A):
- go to https://staging.new.expensify.com/
- Click FAB > Chat > Create a public room
- Invite multiple Members to the room
- As the admin of the room > click on the room chat >  '+' > Split Expense
- Copy and paste the URL (it will be something like https://staging.new.expensify.com/create/split/start/1/2824600098008267/manual)
- Continue the Split Expense process 
- Copy and Paste the URL BEFORE YOU CREATE the split expense (it will be something like https://staging.new.expensify.com/create/split/confirmation/1/2824600098008267)
- Create the Split Expense
- After the Split Expense is created, copy the room URL

'Guest' (User B):

- Go to an incognito window
- paste the room URL
- DO NOT SIGN IN
- Click the URLs in the chat
- Verify you need to sign in when you interact with the room

Admin (User A): 

- Check the Room Members to see that there's a Guest

'Guest' (User B):

- Sign in to the room through the incognito window

Admin (user A):
 
- refresh the browser 
- Notice there is still a 'Guest' in addition to the new user

## Expected Result:
The 'guest' should be removed as a member of the room since the new user is signed in

## Actual Result:
Both the 'guest' and the new user show as members

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [x] Android: mWeb Chrome
- [x] iOS: Native
- [x] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details> 

https://github.com/Expensify/App/assets/51066321/ff79c19e-966d-4fb0-8b64-f58a4fe7f5d5

https://github.com/Expensify/App/assets/43996225/74aa8597-1aff-4f7d-b47e-a1d8021ae1b5

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~0175e97fd87039315b</li>
        <li>Upwork Job ID: 1800039533475604449</li>
        <li>Last Price Increase: 2024-07-01</li>
    </ul>
</details>

**Comment by lanitochka17** [comment] 2024-06-07 13:57
@Christinadobrzyn  FYI I haven't added the External label as I wasn't 100% sure about this issue. Please take a look and add the label if you agree it's a bug and can be handled by external contributors

**Comment by lanitochka17** [comment] 2024-06-07 13:57
We think that this bug might be related to #vip-split

**Comment by Christinadobrzyn** [comment] 2024-06-10 05:38
When should "guest" be used and not the email address? I'm a little confused on when we name a member "Guest" in a public room. @allroundexperts let me know if that's important for this and if you know (or I should ask)

**Comment by Christinadobrzyn** [comment] 2024-06-11 06:06
hi @allroundexperts can you check these proposals when you have a moment?

**Comment by Christinadobrzyn** [comment] 2024-06-12 07:13
Just a heads up - I'm going to be ooo until June 24th so going to assign a teammate to watch this while I'm away

@twisterdotcom proposals are being reviewed 

cc @allroundexperts

**Comment by allroundexperts** [comment] 2024-06-12 08:24
Reviewing today!

**Comment by allroundexperts** [comment] 2024-06-12 08:34
> When should "guest" be used and not the email address? I'm a little confused on when we name a member "Guest" in a public room. @allroundexperts let me know if that's important for this and if you know (or I should ask)

My understanding is that we show the name as `guest` until the guest sends a message in the channel. Once the message is there, we show the user name. @twisterdotcom can you confirm this for us? Thanks!

**Comment by Christinadobrzyn** [comment] 2024-06-13 02:59
I will ask @allroundexperts I'm not 100% sure either. Asking in our project channel - https://expensify.slack.com/archives/C05RECHFBEW/p1718247545080749

@twisterdotcom could you keep an eye on a response and add it here? TY!

**Comment by twisterdotcom** [comment] 2024-06-19 23:03
Okay, I will test this tomorrow including signing out and in.

**Comment by twisterdotcom** [comment] 2024-06-19 23:12
Okay, I will test this tomorrow including signing out and in.

**Comment by allroundexperts** [comment] 2024-06-22 23:40
@twisterdotcom Any update here? Thanks!

**Comment by twisterdotcom** [comment] 2024-06-24 12:47
Hey sorry, I got sick. I think the current behavior is super odd - I can't really recreate this, just some other bugs:

https://github.com/Expensify/App/assets/9133401/c7eec176-1bf9-4c4b-8021-a0fbf1daff0f


1. Go to staging.new.expensify.com
2. Create a public room and add another user
3. copy the URL of the public room
4. paste the URL into a new browser and sign in as another user (not the room creator)
5. After logging in, split an expense in the public room
6. See an error
7. Refresh the page
8. Split an expense
9. See another error
10. Refresh the page to find no split expense
11. Review the members from the room creators perspective and see a list which is 1 fewer than the count says.

<img width="398" alt="image" src="https://github.com/Expensify/App/assets/9133401/e7b427c9-b6ca-4c9e-806c-d6a281f623e8">

<img width="409" alt="image" src="https://github.com/Expensify/App/assets/9133401/39ab6532-111d-4ee8-9e0a-8661d9e3f73d">

So... I'm not sure this exists in the same way now (it's been 2 weeks), but there's still a bug here that I can't find in /app. The user doesn't show up in the split anymore, but they clearly show up in the _count_ of users, right?

So... did we do this but not completely?

>However, when the user logs in as a real user, we're not clearing those anonymous client-side only data from Onyx in successData, so the anonymous user still shows up in the split.

**Comment by Christinadobrzyn** [comment] 2024-06-24 20:09
I can see the same as Ted when retesting - https://github.com/Expensify/App/issues/43290#issuecomment-2186500794

- @dominictb I can't reproduce what you are [saying](https://github.com/Expensify/App/issues/43290#issuecomment-2168486041) about a guest

- An error when creating a split expense is "Unexpected error submitting this expense. Please try again later." which is documented here - https://github.com/Expensify/App/issues/42562

- all users in a room are 'hidden' - that's being worked on here https://github.com/Expensify/App/issues/44041
<img width="1706" alt="image" src="https://github.com/Expensify/App/assets/51066321/17807ee5-93fa-4ddf-923d-45481ab00287">

- I think it's still unclear when a person is no longer a "guest" I would assume when they split an expense in a public room they are no longer a guest? Asking the [team again](https://expensify.slack.com/archives/C05RECHFBEW/p1719259054813949)

Based on the results of this [discussion](https://expensify.slack.com/archives/C05RECHFBEW/p1719259054813949) about when a user is a 'guest', I'm thinking we should either put this on hold for the above issues or close it and come back to it once the other issues are resolved. I think there are too many other bugs to clearly see what is going on here. Let me know your thoughts!

**Comment by Christinadobrzyn** [comment] 2024-06-24 20:17
@jasperhuangg based on this Slack convo, https://expensify.slack.com/archives/C05RECHFBEW/p1719259054813949

Can you confirm if a user should be a 'Guest' in a public room? from what I can test - there aren't any guests in a public room.

**Comment by jasperhuangg** [comment] 2024-06-25 16:35
I didn't really have context on the question, but we're discussing [here](https://expensify.slack.com/archives/C05RECHFBEW/p1719259054813949) with some other engineers who have context.

**Comment by Christinadobrzyn** [comment] 2024-06-26 15:19
still discussing but it sounds like the conclusion will be that once you sign into an account you are no longer a 'guest'. 'Guests' don't really exist as a term in NewDot - you are anonymous until you sign into an account. 

So I think the only remaining bug on this is going to be fixing the member count. Once we have a definitive conclusion I'll update the OP.

**Comment by Christinadobrzyn** [comment] 2024-06-26 18:23
Okay here's the conclusion of the team [convo](https://expensify.slack.com/archives/C05RECHFBEW/p1719259054813949). 

### Expected behaviour: 

Anonymous user (aka 'guest' - which isn't a word used in the product): 

1. Go to staging.new.expensify.com
2. Create a public room and add a few users
3. copy the URL of the public room
5. paste the URL into an incognito browser - do not sign in into NewDot
6. You are anonymous and can't split expense
7. This user isn't counted as a member until they Sign in

This is happening as expected: 

https://github.com/Expensify/App/assets/51066321/34b5c41f-964b-4413-9796-0bcd93d992a0

Non-Anonymous user: 

1. Go to staging.new.expensify.com
2. Create a public room and add a few users
3. copy the URL of the public room
4. paste the URL into a new browser and _sign in_ as another user (not the room creator)
5. After logging in, split an expense in the public room
6. You should be counted as a member - (this is the bug)

**Comment by Christinadobrzyn** [comment] 2024-06-26 18:33
And now... testing this again... this appears to be fixed!



https://github.com/Expensify/App/assets/51066321/b63227a8-fe5a-42bf-b1d5-f71d13114c4c

I'll ask QA to test again -

**Comment by kavimuru** [comment] 2024-06-26 20:27
https://github.com/Expensify/App/issues/43290#issuecomment-2192375105

Anonymous user (aka 'guest') - Anonymous user is counted as a member (guest) when not logged in.
When logged in, member is counted in addition to guest

Non-Anonymous user - working as expected.

**Comment by kavimuru** [comment] 2024-06-26 20:28
https://github.com/Expensify/App/issues/43290#issuecomment-2192391746 is fixed.

**Comment by Christinadobrzyn** [comment] 2024-06-26 20:51
okay thanks @kavimuru - we should fix

> Anonymous user (aka 'guest') - Anonymous user is counted as a member (guest) when not logged in.
> When logged in, member is counted in addition to guest

I'll update the steps in the OP and clean up this Gh a bit.

**Comment by Christinadobrzyn** [comment] 2024-06-26 21:10
Hey @allroundexperts I tried to clean this up a bit to focus on what we need to fix. I updated the OP. 

@devguest07 @dominictb  - based on the revised [OP](https://github.com/Expensify/App/issues/43290#issue-2340529710) can you double-check that your proposal is still applicable?

**Comment by Christinadobrzyn** [comment] 2024-06-27 18:48
@allroundexperts would you be able to take a peek at @devguest07's [proposal](https://github.com/Expensify/App/issues/43290#issuecomment-2156458526)? 

Maybe also checking out [this one](https://github.com/Expensify/App/issues/43290#issuecomment-2157583236) too to see if it will work with the changed objective

**Comment by allroundexperts** [comment] 2024-06-28 10:52
@devguest07 I don't think your proposal would work. You're suggesting to filtering out the guest from the split money expense participant list. In reality, we don't want to show the guest even in the members page of the room (once the guest signs in).

I think this requires a fix from the backend.

**Comment by Christinadobrzyn** [comment] 2024-06-28 19:33
> I think this requires a fix from the backend.

@allroundexperts let me know if you think this needs to be an internal label.

**Comment by allroundexperts** [comment] 2024-06-30 12:44
> @allroundexperts The issue with guest in the members page of the room has been fixed in the latest main branch. However, there is still a problem with the split functionality, where you will find a guest among the possible split members.

Even so, filtering shouldn't be the solution here. We should remove the guest entirely once he signs in.

**Comment by allroundexperts** [comment] 2024-06-30 12:45
> @allroundexperts let me know if you think this needs to be an internal label.

I think that is the best course here.

**Comment by Christinadobrzyn** [comment] 2024-07-01 18:12
Sounds good @allroundexperts - I added the Internal label and I'll work on finding a volunteer.

**Comment by Christinadobrzyn** [comment] 2024-07-02 17:17
waiting for a volunteer

**Comment by Christinadobrzyn** [comment] 2024-07-03 19:25
Looking for a volunteer

**Comment by Christinadobrzyn** [comment] 2024-07-08 21:53
still looking for a volunteer - https://expensify.slack.com/archives/C05RECHFBEW/p1720475518788529?thread_ts=1719259054.813949&cid=C05RECHFBEW

**Comment by Christinadobrzyn** [comment] 2024-07-09 23:51
still looking for a volunteer - https://expensify.slack.com/archives/C05RECHFBEW/p1720475518788529?thread_ts=1719259054.813949&cid=C05RECHFBEW

**Comment by mvtglobally** [comment] 2024-07-11 03:53
Issue not reproducible during KI retests. (First week)

**Comment by Christinadobrzyn** [comment] 2024-07-15 18:23
I'll try to retest this today to see if it's still happening unless you have time to do that @allroundexperts

**Comment by Christinadobrzyn** [comment] 2024-07-16 00:26
I'm not going to get to this retest today, I will do it tomorrow

**Comment by Christinadobrzyn** [comment] 2024-07-16 23:11
Testing again - I think this is resolved - @allroundexperts would be able to check and see if you're still setting a Guest? I'm not seeing a guest anymore.

**Comment by Christinadobrzyn** [comment] 2024-07-17 18:32
I'm going to ask QA if they can retest - https://expensify.slack.com/archives/C9YU7BX5M/p1721241144696699

**Comment by mvtglobally** [comment] 2024-07-17 19:39
Issue not reproducible during KI retests. (Second week)

https://github.com/user-attachments/assets/edc008ee-9f7d-4fc6-8e2a-fee91b93154c

**Comment by Christinadobrzyn** [comment] 2024-07-17 21:40
Let's close this - the issue seems to be resolved.

**Closed by Christinadobrzyn** 2024-07-17 21:40 UTC
Labels: Daily, Internal, Help Wanted, Bug, Hot Pick
