### ISSUE TITLE
[$500] Request –Red dot is not displayed in LHN as Admin if upload image of blurry receipt as employee

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#32524] opened 2023-12-05 20:26 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.8-0
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** Applause - Internal Team
**Slack conversation:**

## Action Performed:
1. Go to https://staging.new.expensify.com/
2. Log in
3. As the employee, navigate to the workspace chat
4. Select Request money > Scan
5. Upload a image of a blurry receipt
6. Complete the money request
7. After the scanned receipt shows a failure
8. Login as the workspace admin
9. Navigate to the workspace chat with the employee
10. Click on the preview to navigate to the report conversation

## Expected Result:
Red dot is displayed in LHN as Admin if upload image of blurry receipt as employee

## Actual Result:
Red dot is not displayed in LHN as Admin if upload image of blurry receipt as employee

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [x] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details> 

https://github.com/Expensify/App/assets/78819774/a7b90eae-259b-4d1d-a908-375d282166d7

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~012df105c35490c2a4</li>
        <li>Upwork Job ID: 1732134376158715904</li>
        <li>Last Price Increase: 2023-12-05</li>
    </ul>
</details>

**Comment by erichasinternet** [comment] 2023-12-05 23:39
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
When logged in as a workspace admin, a red dot is not displayed in LHN if an employee uploads a blurry/invalid receipt.

### What is the root cause of that problem?
Existing LHN code does not include logic to check for missing smartscan fields. 
We check for brickroad errors [here](https://github.com/Expensify/App/blob/e4586d06685485bf2c908c82fd8d759701232775/src/components/LHNOptionsList/OptionRowLHN.js#L118), which is why we see a red dot in the employee LHN view and not the workspace admin view.

### What changes do you think we should make in order to solve the problem?

In the video @lanitochka17 shared we can see that the red dot is displayed in the workspace admin's report preview, as expected. We check for missing smartscan fields in the report preview, but not the LHN.

To address this issue, we can integrate the existing `hasMissingSmartscanFields` check into the [LHN code](https://github.com/Expensify/App/blob/e4586d06685485bf2c908c82fd8d759701232775/src/components/LHNOptionsList/OptionRowLHN.js#L118-L120).

```
    const hasBrickError = hasFieldErrors || optionItem.brickRoadIndicator === CONST.BRICK_ROAD_INDICATOR_STATUS.ERROR;
    const hasFieldErrors = ReportUtils.hasMissingSmartscanFields(props.reportID);
    const hasErrors = hasBrickError || hasFieldErrors;
```

We can ensure that the red dot is appropriately displayed by adding `hasFieldErrors` and `hasErrors`, then replacing `hasBrickError` in the react code with the more comprehensive `hasErrors`. 


### Screenshot showing bugfix:
![Screenshot 2023-12-05 at 4 30 59 PM](https://github.com/Expensify/App/assets/33706686/f1e9c15f-0cf5-40ad-92bc-a99fe3b0f6a8)

**Comment by alexpensify** [comment] 2023-12-06 18:58
@c3024 when you get a chance, can you review the proposal? Thanks!

**Comment by alexpensify** [comment] 2023-12-11 18:49
@c3024 are you suggesting that we close this issue because it's expected behaviour?

**Comment by c3024** [comment] 2023-12-12 02:26
Sorry for being not clear. Yes, I am suggesting that we close this issue because it's expected behaviour.

**Comment by alexpensify** [comment] 2023-12-12 15:36
All good, I wanted to make sure. Based on this feedback, I'm going to close this one.

**Closed by alexpensify** 2023-12-12 15:36 UTC
Labels: External, Daily, Help Wanted, Bug
