### ISSUE TITLE
[$1000] mentions work in multi-line codeblock but not in inline codeblock

### ISSUE THREAD

**Issue by kavimuru** [Expensify/App#18893] opened 2023-05-13 16:55 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:

1. open a chat
2. send mention in inline codeblock
3. send mention in multiline codeblock

## Expected results: 
consistency should be there (either both or none type)
## Actual results: 
no consistency

## Workaround:
Can the user still use Expensify without this being fixed? Have you informed them of the workaround?

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [x] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 1.3.13.3
**Reproducible in staging?:** y
**Reproducible in production?:** 
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/43996225/8c9a619a-0909-481c-861b-98718a88596d

<img width="955" alt="1" src="https://github.com/Expensify/App/assets/43996225/909565db-4174-4c4f-9f77-80ad8feea8cb">

**Expensify/Expensify Issue URL:**
**Issue reported by:** @chiragxarora
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1683924632116069

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01e59c8d897b36b7df</li>
        <li>Upwork Job ID: 1659110347894513664</li>
        <li>Last Price Increase: 2023-05-18</li>
    </ul>
</details>

**Comment by payal-lathidadiya** [comment] 2023-05-15 11:16
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
User mention doesn't work in inline codeblock

### What is the root cause of that problem?
The logic which triggers suggested mentions checks for regular expression is [here](https://github.com/Expensify/App/blob/main/src/pages/home/report/ReportActionCompose.js#L523)
- The current regex checks for newline or whitespace before the `@` to show suggested mentions which fails for inline code block as it's missing `back quote` in regex

For inline codeblock when user types in `back quote` and puts `@` to mention user in message, it doesn't show suggested mentions because this regular expression doesn't match and from subsequent string parts check, output of `this.isMentionCode(lastWord)` evaluates to false [here](https://github.com/Expensify/App/blob/main/src/pages/home/report/ReportActionCompose.js#L552)

### What changes do you think we should make in order to solve the problem?

Update regular expression definition [here](https://github.com/Expensify/App/blob/main/src/CONST.js#L1022) to add `back quote` character.

### What alternative solutions did you explore? (Optional)
None

**Comment by alexpensify** [comment] 2023-05-15 22:21
I'll try to test soon.

**Comment by alexpensify** [comment] 2023-05-17 17:36
@dylanexpensify - I've run out of time to continue looking into this one. I'm OOO until Wednesday, May 24, and following the [new process](https://expensify.slack.com/archives/CK49UADB9/p1684182291511799). I'm reassigning the Bug label to identify if this is a bug and continue the process to avoid stalling it. Thank you!

**Comment by dylanexpensify** [comment] 2023-05-18 08:12
Testing this now to triage!

**Comment by dylanexpensify** [comment] 2023-05-18 08:14
Can repro, no dupe!

**Comment by Thanos30** [comment] 2023-05-18 11:50
This is solved on the PR that handles this issue: https://github.com/Expensify/App/issues/18983

**Comment by dylanexpensify** [comment] 2023-05-18 11:52
Oh nice, Idk how I missed that when searching. Cheers, @Thanos30 !

**Closed by dylanexpensify** 2023-05-18 11:52 UTC
Labels: External, Daily, Help Wanted, Bug

**Comment by chiragxarora** [comment] 2023-05-18 13:32
Hey all, I shall be eligible for the reporting bonus since my issue came first right?
This one is 5 days old and @puneetlath one is 3 days old

**Comment by dylanexpensify** [comment] 2023-05-18 13:34
That checks out, @chiragxarora apply at the link above!

**Comment by chiragxarora** [comment] 2023-05-18 13:35
Could you send me an offer instead?
I don't have much connects
Thankyou

**Comment by chiragxarora** [comment] 2023-05-18 13:37
My upwork profile
https://www.upwork.com/freelancers/~014a1b566a7d8ee0c5

**Comment by chiragxarora** [comment] 2023-05-18 13:47
accepted!

**Comment by dylanexpensify** [comment] 2023-05-18 13:49
Payment sent! Thanks @chiragxarora!

**Comment by chiragxarora** [comment] 2023-05-18 13:50
Thankyou!
