### ISSUE TITLE
Sign in- Two different warning messages displayed when tap Set Password

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#11114] opened 2022-09-19 18:38 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Launch the app
2. Put you new email address in Sign in page
3. Tap Continue
4. Tap a couple times on Resent Link button
5. Go back to you email and find email from Expensify Concierge
6. Should arrived a several emails due to hitting Resent link several times
7. Tap on first one, which is invalid already
8. Change the link to staging
9. Type password
10. Hit Set Password several times

## Expected Result:
One warning messages displayed when tap Set Password several times

## Actual Result:
Two different warning messages displayed when tap Set Password several times

## Workaround:
Unknown

## Platform:

Where is this issue occurring?

- Web
- iOS
- Android
- Desktop App
- Mobile Web

**Version Number:** 1.2.2.0

**Reproducible in staging?:** Yes

**Reproducible in production?:** Yes

**Email or phone of affected tester (no customers):** any

**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Notes/Photos/Videos:** Any additional supporting documentation

https://user-images.githubusercontent.com/93399543/191090834-c456c354-bc26-4a11-be03-7bf4aaee69ae.mp4

**Expensify/Expensify Issue URL:** 

**Issue reported by:** Applause - Internal Team

**Slack conversation:** 

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by sobitneupane** [comment] 2022-09-20 06:28
**Proposal:**
**Reason:** Two errors being shown are returned by `ErrorUtils.getLatestErrorMessage(this.props.session);` (say error1) and `ErrorUtils.getLatestErrorMessage(this.props.account);` (say error2). When the button is loading, "error1" is undefined. So, during that period, 'error2' is being displayed.

My proposal is to show error message only when button is not loading.
https://github.com/Expensify/App/blob/50d42954276ca93d2cc0c9aaec5d0b2bd740f6f4/src/pages/SetPasswordPage.js#L122
```diff
<FormAlertWithSubmitButton
    buttonText={buttonText}
    isLoading={this.props.account.isLoading}
    onSubmit={this.validateAndSubmitForm}
    containerStyles={[styles.mb2, styles.mh0]}
    message={error}
-   isAlertVisible={!_.isEmpty(error)}
+   isAlertVisible={!this.props.account.isLoading && !_.isEmpty(error)}
    isDisabled={!this.state.isFormValid}
/>
```
Output:

https://user-images.githubusercontent.com/25876548/191181912-be2b00e2-5aa5-462f-b950-b471119d453a.mov

**Comment by Puneet-here** [comment] 2022-09-20 07:36
cc: @MonilBhavsar

**Comment by MonilBhavsar** [comment] 2022-09-20 07:46
Thanks for the ping! Looks like a bug from code refactoring. Looking into it

**Comment by MonilBhavsar** [comment] 2022-09-20 14:40
Handling internally as it was caused because of refactoring. The refactor code is deployed and we want to push this fix asap.

**Comment by MonilBhavsar** [comment] 2022-09-21 13:05
PR is merged. Waiting for deploy

**Comment by mvtglobally** [comment] 2022-09-27 05:15
Issue not reproducible during KI retests. (First week)

**Closed** 2022-10-10 11:06 UTC
Labels: Reviewing, Engineering, Daily, Improvement, Internal
