### ISSUE TITLE
Stuck in "Launching Expensify" screen and unable to come out of the screen

### ISSUE THREAD

**Issue by m-natarajan** [Expensify/App#37115] opened 2024-02-23 00:24 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:**
**Reproducible in staging?:** needs reproduction
**Reproducible in production?:** needs reproduction
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** @ryanschaffer 
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1708631036916519

## Action Performed:
NOTE: There are no exact reproduction steps. The following could be the reason
1. Open http://exfy.com/roadmap in web
2. Will prompt to switch to the desktop app
3. Somehow user gets signed out
4. Close the desktop app and reopen

## Expected Result:
User is able to sign in and able to use the app

## Actual Result:

- When  exit and reopen the app, got the loading screen for a bit and then the `Launching Expensify` screen appears. 
- The hyperlink to sign back in doesn’t work. Nothing happens when clicked on it and stuck in this page

## Workaround:
unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [ ] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

![2024-02-22_11-40-18](https://github.com/Expensify/App/assets/38435837/fe95d2e9-fccb-4e3b-8e4b-806058665888)

![2024-02-22_14-13-20](https://github.com/Expensify/App/assets/38435837/cb83c8b6-6b62-4b3a-b443-8a315db6d88b)

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01b6cff1077d8a87dd</li>
        <li>Upwork Job ID: 1762232427563544576</li>
        <li>Last Price Increase: 2024-02-26</li>
    </ul>
</details>

**Comment by muttmuure** [comment] 2024-02-23 18:35
I think this one got resolved maybe?

**Comment by mallenexpensify** [comment] 2024-02-26 21:47
Still happening for @ryanschaffer .  [link](https://expensify.slack.com/archives/C049HHMV9SM/p1708983266158829?thread_ts=1708631036.916519&cid=C049HHMV9SM)
> I uninstalled and reinstalled and it is still happening. It goes straight to the Your sessions expired. Please sign in again with the that link being broken. I am effectively locked out of using the desktop app and I’m web only at this point

Added `Internal` to assign a C+.  @eh2077 and @muttmuure , are you able to reproduce? If not, Matt, can you drop it in #qa and tag the team handles bookmarked at the top and ask them to try to repro? 

@ryanschaffer what version are you on?

**Comment by eh2077** [comment] 2024-02-27 14:16
@mallenexpensify I can't reproduce this. I'm able to click the hyperlink to open the sign in page.

**Comment by mallenexpensify** [comment] 2024-02-27 22:24
Ryan was able to fix by following the steps below. 
Desktop
1. open desktop then cmd+option+i
2. click Application on top bar (might have to click >> to see it)
3. Then Local Storage on left then right click/double tap app:// and click Clear

Since it's possible other users could get permanently bricked in this situation, I was thinking we should consider allowing a way to clear local storage (or similar). Non-employees wouldn't know of the console option.  We likely have a few options, inc allowing clearing local storage:

1. A link to click on the error screen
2. When click "Please sign again"
3. When uninstall app. 

@eh2077 @muttmuure , what cha think?

**Comment by eh2077** [comment] 2024-02-28 15:35
@mallenexpensify I think it makes sense to clear up data in local storage similar to what we do when logout from web browser. Ideally I think we should reproduce this issue to better understand it, which will make us more confident about the fix. Let me take some more time to find the reproduction steps.

**Comment by mallenexpensify** [comment] 2024-03-02 00:08
Good luck @eh2077 .  Ryan was the only one who experienced so I'm guessing it'll be tough to reproduce.

**Comment by eh2077** [comment] 2024-03-04 15:23
@mallenexpensify Hmm, I tried several times but no luck. Should we make this external to seek potential findings from contributors?

**Comment by mallenexpensify** [comment] 2024-03-10 23:39
Bumped back to weekly, removed bug for now so it won't keep bumping back to daily.  If we can't reproduce, I don't think daily is useful.  I add it to an internal tracking list for 'needs reproduction' issues
- https://github.com/Expensify/Expensify/issues/377295

**Comment by mallenexpensify** [comment] 2024-04-07 21:43
Added to a doc I'm building for 'needs reproduction' issues[ here](https://docs.google.com/document/d/1fEXM066MuslHVu-AODm7o2Gza2mgfYpqQwLl5UZJ6hk/edit?usp=sharing).  Keeping weekly for now

**Comment by mallenexpensify** [comment] 2024-05-21 23:40
Gonna close this out. It's a few months old and we haven't been able to reproduce yet. Also. this _might have_ fixed it. Repro steps were the same at here
- https://github.com/Expensify/App/issues/41132 

Also... for future Needs Repro issues, I'm working an new process for finding repro steps
- https://github.com/Expensify/Expensify/issues/398280

**Closed by mallenexpensify** 2024-05-21 23:40 UTC
Labels: Monthly, Internal, Needs Reproduction
