### ISSUE TITLE
Web / Firefox: Chat Details Modal Wont Close After Starting A New Chat With Someone From The Groups Members List

### ISSUE THREAD

**Issue by kavimuru** [Expensify/App#12892] opened 2022-11-21 16:32 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:

1. Go to a group chat or create one
2. Go to the members list (displayed in the right side modal)
3. Select a member you don't already have a 1-1 chat with
4. Start a 1-1 chat with that member
5. Notice the chat is started but the right side details modal is not closed

## Expected Result: 
The details modal should close when a chat is started

## Actual Result: 
The details modal stays open after the chat is started

## Workaround:
unknown

## Platform:

Where is this issue occurring?

- Web - Firefox

**Version Number:** 1.2.29-6
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**Email or phone of affected tester (no customers):** 
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** 

https://user-images.githubusercontent.com/43996225/203109044-ec539a0c-6887-475d-aa7f-4ebe675972be.mp4

https://user-images.githubusercontent.com/43996225/203109222-afc95141-f1c4-4144-8bbc-03b78a861fa8.mp4

**Expensify/Expensify Issue URL:** 
**Issue reported by:** @huzaifa-99
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1668904372819609

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by aldo-expensify** [comment] 2022-11-21 23:58
Reproduced in firefox / mac

**Comment by aldo-expensify** [comment] 2022-11-22 00:00
@JmillsExpensify this seems to happen only in Firefox and the working around is just to click outside the personal details modal to close it, this doesn't block the user from using the App. Does this mean that the issue is valid and remains open, but it is not WAQ?

I found this slack discussion: https://expensify.slack.com/archives/C01GTK53T8Q/p1668730285445209, but wasn't clear to me where we landed

**Comment by bfitzexpensify** [comment] 2022-11-22 17:21
I also reproduced this. I agree the user isn't blocked from using the app — clicking elsewhere is very likely the next action a user would take. So I think this can be closed. Opened a discussion in Slack [here](https://expensify.slack.com/archives/C01GTK53T8Q/p1669137681128919)

**Comment by bfitzexpensify** [comment] 2022-11-23 21:15
OK, no pushback, closing.

**Closed by bfitzexpensify** 2022-11-23 21:15 UTC
Labels: Daily, Bug

**Comment by JmillsExpensify** [comment] 2022-11-26 22:13
+1 to closing given that this happens on Firefox and that's not an officially supported browser.
