### ISSUE TITLE
[HOLD for payment 2023-11-22] [HOLD for payment 2023-11-21] [HOLD] [$1000] Web - Workspace allows to add only invisible characters as name

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#23297] opened 2023-07-20 18:57 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Open the app
2. Open settings
3. Open workspaces
4. Open any workspace
5. Copy invisible characters from https://www.editpad.org/tool/invisible-character and observe that workspace allows to save the name

## Expected Result:
 App should not allow to save workspace name if we only use invisible characters for name

## Actual Result:
App allows to save workspace name even if we only use invisible characters for name

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [x] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 1.3.43-2
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/93399543/7830b844-398d-4be2-b368-0a0cbadf85df

**Expensify/Expensify Issue URL:**
**Issue reported by:** @dhanashree-sawant
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1689878993909189

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01560ace6dc872a8c8</li>
        <li>Upwork Job ID: 1683861747204747264</li>
        <li>Last Price Increase: 2023-09-12</li>
<li>Automatic offers: </li>
<ul>
<li>situchan | Reviewer | 26645014</li>
<li>dhanashree-sawant | Reporter | 26645016</li>
</ul></li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @peterdbarkerUK</details>

**Comment by ayazhussain79** [comment] 2023-07-20 19:14
you can also create task with invisible characters


<img width="1425" alt="Screenshot 2023-07-21 at 12 12 42 AM" src="https://github.com/Expensify/App/assets/56740856/48cf9e23-25b9-4ab5-ba38-dcfe54eebc88">

**Comment by alexpensify** [comment] 2023-07-22 15:40
I ran out of time yesterday, I'll review soon.

**Comment by alexpensify** [comment] 2023-07-24 22:05
@stitesExpensify - I've assigned the engineering label to identify if we think this will be a common problem. Let me know if I should start a discussion with the full Slack room instead, but I'm looking for feedback here. Thanks!

**Comment by stitesExpensify** [comment] 2023-07-25 15:27
Yeah, I think this is worth fixing. I think that it will look like a bug on our end if people have empty names because it will look weird to display nothing next to other people's names in things like reactions for example.

**Comment by alexpensify** [comment] 2023-07-25 21:46
Thank you @stitesExpensify for the update! I'll remove you now to avoid confusion as we accept proposals.

**Comment by alexpensify** [comment] 2023-07-27 21:52
@situchan when you get a chance, can you please review the submitted proposals to see if they will work to resolve this one? Thanks!

**Comment by alexpensify** [comment] 2023-07-29 19:54
@situchan any update here on the proposals?

**Comment by situchan** [comment] 2023-07-31 12:00
I think we should find general solution to fix this weird issue.
This happens on every place that has text input.

https://github.com/Expensify/App/assets/108292595/433a2de0-5438-4424-abe6-38931b7b9f42


No satisfactory proposals yet

**Comment by situchan** [comment] 2023-08-02 19:06
@samh-nl what about inputs which are not inside Form?

**Comment by situchan** [comment] 2023-08-02 19:06
> @situchan were you able to review the updated proposal? Thank you for the update!

Still awaiting proposals

**Comment by situchan** [comment] 2023-08-04 08:53
Still waiting for complete proposal with general solution

**Comment by alexpensify** [comment] 2023-08-07 23:03
@situchan - when you get a chance, can you please review @samh-nl's latest comment? Thank you!

**Comment by alexpensify** [comment] 2023-08-09 19:49
@situchan - any update to the @samh-nl comment? Thanks!

**Comment by situchan** [comment] 2023-08-10 08:12
> 
> > @samh-nl what about inputs which are not inside Form?
> 
> Could you please name an example where this is the case?

I couldn't find an example.

But still `isRequiredFulfilled` is not the correct place to apply solution.
Many text inputs are not mandatory, i.e. DisplayNamePage

**Comment by situchan** [comment] 2023-08-10 08:21
I'd like to confirm the expected behavior:

Option 1: replace invisible characters with empty string and then trim and validate
Option 2: invalidate only when text is full of invisible characters. if any visible character exists, then keep invisible characters (don't replace them with empty string)

@alexpensify which one do you think is better?
Option 1 force overwrite user input, while Option 2 respects user input no matter it's weird character

**Comment by alexpensify** [comment] 2023-08-12 16:22
On Monday, I'll start a discussion with this feedback.

**Comment by alexpensify** [comment] 2023-08-14 22:04
I started a discussion here:

https://expensify.slack.com/archives/C049HHMV9SM/p1692050650579589?thread_ts=1689878993.909189&cid=C049HHMV9SM

**Comment by alexpensify** [comment] 2023-08-16 23:50
@situchan - the feedback in that thread is summarized by this quote: 

>I agree that option 1 is the way to go. There is no real use case for invisible characters, so we should just get rid of them.

Do you have everything you need to carry on with the reviews or do you need more feedback? If you need to chat more, please do so in the thread to get more ideas. Thanks!

**Comment by alexpensify** [comment] 2023-08-18 21:17
@situchan can you confirm we can continue with the reviews? Thanks!

**Comment by situchan** [comment] 2023-08-18 21:20
No satisfactory proposals yet to meet the expected behavior we landed on

**Comment by alexpensify** [comment] 2023-08-21 17:44
@situchan when you get a chance, can you review the latest responses and proposal? Thanks!

**Comment by alexpensify** [comment] 2023-08-24 03:50
@situchan any update here?

**Comment by alexpensify** [comment] 2023-08-28 23:06
@situchan - I'm catching up from being OOO. Were you able to review the latest proposal? Thanks for the update!

**Comment by situchan** [comment] 2023-08-29 16:12
@kosmydel thanks for your proposal.
Can you please confirm that regex in https://stackoverflow.com/a/11598864 involves all invisible characters in the world?

**Comment by alexpensify** [comment] 2023-08-31 23:50
@kosmydel - when you get a chance, can you please reply to @situchan's comment? Thanks!

**Comment by kosmydel** [comment] 2023-09-01 06:50
> @kosmydel - when you get a chance, can you please reply to @situchan's comment? Thanks!

I will be able to reply next week, as I have internal training at Software Mansion and I'm also prioritizing [this issue](https://github.com/Expensify/App/pull/26307).

Sorry for the inconvenience.

**Comment by alexpensify** [comment] 2023-09-04 15:27
Still accepting proposals here

**Comment by alexpensify** [comment] 2023-09-06 21:13
@situchan can you please review the proposal and identify if we can move forward here? Thanks!

**Comment by situchan** [comment] 2023-09-06 23:01
We continued discussing in [slack thread](https://expensify.slack.com/archives/C049HHMV9SM/p1693993467092569?thread_ts=1689878993.909189&cid=C049HHMV9SM)

@kosmydel please post here updated solution

**Comment by kosmydel** [comment] 2023-09-07 08:03
> We continued discussing in [slack thread](https://expensify.slack.com/archives/C049HHMV9SM/p1693993467092569?thread_ts=1689878993.909189&cid=C049HHMV9SM)
> 
> @kosmydel please post here updated solution

I've updated [the proposal](https://github.com/Expensify/App/issues/23297#issuecomment-1686128116).

The new approach focuses on this issue. I added additional steps if we want to follow the ideas from Slack.

**Comment by alexpensify** [comment] 2023-09-08 23:43
@situchan can you please review the updated proposal? Thanks!

**Comment by alexpensify** [comment] 2023-09-11 22:19
@situchan any update here regarding your thoughts on the solution here?

**Comment by situchan** [comment] 2023-09-12 16:38
@kosmydel's [proposal](https://github.com/Expensify/App/issues/23297#issuecomment-1686128116) looks good to me.

Note for assigned engineer: there was [slack discussion](https://expensify.slack.com/archives/C049HHMV9SM/p1692050650579589?thread_ts=1689878993.909189&cid=C049HHMV9SM) about the expected behavior

🎀 👀 🎀 C+ reviewed

**Comment by hayata-suenaga** [comment] 2023-09-13 04:53
> This should have both a front-end and back-end fix so that people can't maliciously change their names on the API, and they get notified on the front end when the name is invalid

Is any internal engineer working on this backend change? (although seems like a very low priority)

**Comment by situchan** [comment] 2023-09-13 04:58
> Is any internal engineer working on this backend change?

No one is working yet

**Comment by hayata-suenaga** [comment] 2023-09-13 05:11
memo for myself: https://expensify.slack.com/archives/C03TQ48KC/p1694581849765449

**Comment by hayata-suenaga** [comment] 2023-09-13 05:32
@situchan could you tell me which commands needs invisible character check on the backend side?

**Comment by hayata-suenaga** [comment] 2023-09-13 05:32
memo for myself: https://github.com/Expensify/Expensify/issues/316332

**Comment by situchan** [comment] 2023-09-13 05:36
> @situchan could you tell me which commands needs invisible character check on the backend side?

I think all commands related to name updates - workspace, room name, first/last name etc.

Backend fix is low priority. Let's see in app PR what api commands will be to update

**Comment by dhanashree-sawant** [comment] 2023-09-13 06:05
Hi @alexpensify, the following issue is raised on 21st july but melvin bot has provided me with 50$ offer, can you have a look once  you are available?

**Comment by situchan** [comment] 2023-09-13 06:47
> Hi @alexpensify, the following issue is raised on 21st july but melvin bot has provided me with 50$ offer, can you have a look once you are available?

@dhanashree-sawant nvm, you can still accept the offer. The remaining ($200) will be issued as bonus.

**Comment by alexpensify** [comment] 2023-09-18 18:26
@situchan - the PR is ready for review. Please let me know if you are unable to help here. Thanks!

**Comment by situchan** [comment] 2023-09-18 18:33
Review is in progress

**Comment by alexpensify** [comment] 2023-09-21 18:21
Thanks for the update!

**Comment by alexpensify** [comment] 2023-09-28 07:18
@situchan is the server back up to test the PR again?

**Comment by situchan** [comment] 2023-09-28 13:48
yes, I will checklist one conflict is fixed

**Comment by alexpensify** [comment] 2023-09-29 06:11
Perfect, looks like there is a conflict but we are back on track. Thank you!

**Comment by alexpensify** [comment] 2023-10-04 22:23
Update: The PR is still active

**Comment by hayata-suenaga** [comment] 2023-10-05 05:59
HOLD was placed to the PR

**Comment by alexpensify** [comment] 2023-10-11 20:44
@hayata-suenaga should we move this GH to be on HOLD too?

**Comment by alexpensify** [comment] 2023-10-18 00:09
Weekly update: PR looks to be moving again

**Comment by hayata-suenaga** [comment] 2023-10-18 13:45
waiting for C+'s review (because the server was down and they couldn't review it)

**Comment by alexpensify** [comment] 2023-10-24 23:31
@situchan can you please review the PR again? Thanks!

**Comment by alexpensify** [comment] 2023-11-01 00:59
@situchan any update here?

**Comment by situchan** [comment] 2023-11-01 02:59
waiting for @kosmydel to fix conflict - https://github.com/Expensify/App/pull/27414#issuecomment-1783940276

**Comment by alexpensify** [comment] 2023-11-01 18:12
Thanks for the update!

**Comment by alexpensify** [comment] 2023-11-08 00:26
Weekly Update: PR is in review

**Comment by alexpensify** [comment] 2023-11-16 16:13
I'm OOO next week, @peterdbarkerUK is going to step in and handle the payment process. 

@situchan - before the payment date, please complete the checklist. Thanks!

**Comment by peterdbarkerUK** [comment] 2023-11-21 16:03
@situchan could you take a swing at the PR checklist?

**Comment by situchan** [comment] 2023-11-21 16:44
@peterdbarkerUK I assume you meant BZ checklist

There's no offending PR which caused this regression as issue itself is edge case.
We already added enough unit test cases in automated test so no need regression test.

**Comment by peterdbarkerUK** [comment] 2023-11-21 20:27
Well shoot, you caught me lazily copying Al instead of re-reading the whole issue. Busted.

Agreed, will complete payout tomorrow

**Comment by peterdbarkerUK** [comment] 2023-11-22 10:57
[$1000] paid to @situchan (C+ review)
[$50] offer sent to @dhanashree-sawant (please bump me once you've accepted!)

**Comment by dhanashree-sawant** [comment] 2023-11-24 07:25
Hi @peterdbarkerUK, the issue was raised before 30 August, can you update the offer to 250$?

**Comment by peterdbarkerUK** [comment] 2023-11-24 14:27
Right you are, updated and sent!

**Comment by dhanashree-sawant** [comment] 2023-11-24 14:43
Thanks, I have accepted the offer.

**Comment by peterdbarkerUK** [comment] 2023-11-24 14:48
Done, thanks everyone!

**Closed by peterdbarkerUK** 2023-11-24 14:48 UTC
Labels: External, Engineering, Daily, Awaiting Payment, Bug

**Comment by alexpensify** [comment] 2023-11-27 19:44
Thanks for your help @peterdbarkerUK to complete the payment process.
