### ISSUE TITLE
[PAID] [$67.50] Chat - There is no closing question mark on delete comment confirmation modal in Spanish

### ISSUE THREAD

**Issue by IuliiaHerets** [Expensify/App#50290] opened 2024-10-05 15:49 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** v9.0.45-2
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**If this was caught during regression testing, add the test name, ID and link from TestRail:** https://expensify.testrail.io/index.php?/tests/view/5045504
**Email or phone of affected tester (no customers):** applausetester+vd_web100424@applause.expensifail.com
**Issue reported by:** Applause Internal Team

## Action Performed:
Pre-requisite: the user must have set the language preference to Spanish.

1. Go to any chat.
2. Right click on any message (send a message is there is none).
3. Click on "Eliminar comentario".

## Expected Result:
Text on confirmation modal should say: ¿Estás seguro de que quieres eliminar este comentario?

## Actual Result:
Text on confirmation modal says: ¿Estás seguro de que quieres eliminar este comentario

## Workaround:
Unknown

## Platforms:

- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [x] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos
![Bug6624989_1728085104424!Screenshot_1](https://github.com/user-attachments/assets/e2d87f4d-48a5-477d-a9f6-556b9d8efc77)

  
</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~021843383751880246894</li>
        <li>Upwork Job ID: 1843383751880246894</li>
        <li>Last Price Increase: 2024-10-07</li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @eh2077</details>

**Comment by IuliiaHerets** [comment] 2024-10-05 15:49
@strepanier03  FYI I haven't added the External label as I wasn't 100% sure about this issue. Please take a look and add the label if you agree it's a bug and can be handled by external contributors

**Comment by MuaazArshad** [comment] 2024-10-05 15:51
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
Chat - There is no closing question mark on delete comment confirmation modal in Spanish
### What is the root cause of that problem?
We are not adding ?  here
https://github.com/Expensify/App/blob/99f280b0edae75ff59614a1c5e98c47b39800aa5/src/languages/es.ts#L636
### What changes do you think we should make in order to solve the problem?

We should add it like this 
### What alternative solutions did you explore? (Optional)

**Comment by strepanier03** [comment] 2024-10-07 20:16
Updated the job post and the title as this change is very simple and small, and we agreed to lower the price on this one.

**Comment by parotax** [comment] 2024-10-07 21:19
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
We are missing a "?" at the end of delete comment confirmation modal's spanish text.

### What is the root cause of that problem?
In the ```src/languages/es.ts``` file we ask for delete confirmation without the "?":
```typescript
deleteConfirmation: ({action}: DeleteConfirmationParams) =>
            `¿Estás seguro de que quieres eliminar este ${action?.actionName === CONST.REPORT.ACTIONS.TYPE.IOU ? 'gasto' : 'comentario'}`,
```

### What changes do you think we should make in order to solve the problem?
Add the missing "?" in the end of the string in the translation file.

**Comment by strepanier03** [comment] 2024-10-07 21:20
This might be a dupe of https://github.com/Expensify/App/issues/49893, going to check and if so close this out.

**Comment by parotax** [comment] 2024-10-07 21:21
Contributor details
Your Expensify account email: luukas.k.lehtinen@gmail.com
Upwork Profile Link: https://www.upwork.com/freelancers/~01f29577390fed6ca6

**Comment by parotax** [comment] 2024-10-07 21:35
> This might be a dupe of #49893, going to check and if so close this out.

@strepanier03 To me it doesn't seem to be a duplicate. It is just a similar issue in the "Download attachment" modal. This is in "Delete message" modal.

**Comment by eh2077** [comment] 2024-10-09 13:45
Thank you for your speedy proposals!

This one is really straightforward. I think we should go with @MuaazArshad 's [proposal](https://github.com/Expensify/App/issues/50290#issuecomment-2395099322) as they're the first to point the root cause.

@MuaazArshad posted at `2024-10-05T15:51:45Z` while @abzokhattab posted at `2024-10-05T15:54:03Z`

🎀👀🎀 C+ reviewed

**Comment by neil-marcellini** [comment] 2024-10-09 17:29
> Thank you for your speedy proposals!
> 
> This one is really straightforward. I think we should go with @MuaazArshad 's [proposal](https://github.com/Expensify/App/issues/50290#issuecomment-2395099322) as they're the first to point the root cause.

I agree, sounds good. @strepanier03 this one is so simple that I would suggest we pay $0 for it, or at least next time we have a similar copy change. No C+ is really needed either.

**Comment by strepanier03** [comment] 2024-10-15 23:21
# HOLD FOR 2024-10-22

### Payment Summary

- [ ] @MuaazArshad - $67.50 via Upwork ([offer](https://www.upwork.com/nx/wm/offer/104437334))
- [ ] @eh2077 - $67.50 via NewDot Manual Requests

**Comment by strepanier03** [comment] 2024-10-21 19:35
comes off payment hold tomorrow.

**Comment by strepanier03** [comment] 2024-10-23 00:15
@MuaazArshad I've paid and closed the contract. @eh2077 - payment summary is above and you can request in New Expensify. Closing out now 👋

**Comment by eh2077** [comment] 2024-10-23 00:23
Requested in NewDot

**Comment by JmillsExpensify** [comment] 2024-10-23 11:08
$67.50 approved for @eh2077

**Comment by tgolen** [comment] 2024-10-23 21:49
Reopening for @eh2077 and @strepanier03 to fill out the regression checklist

**Comment by strepanier03** [comment] 2024-10-24 00:16
Ah dang, I must have mixed this up with another one that didn't have a reg test needed, thanks for catching @tgolen. @eh2077 please finish up the checklist and I'll make the reg test.

**Comment by eh2077** [comment] 2024-10-24 15:34
I put this on my todo list and will complete it by tmr, thanks!

**Comment by eh2077** [comment] 2024-10-25 12:20
### Checklist

- [x] [@eh2077] The PR that introduced the bug has been identified. Link to the PR: https://github.com/Expensify/App/pull/17348
- [x] [@eh2077] The offending PR has been commented on, pointing out the bug it caused and why, so the author and reviewers can learn from the mistake. Link to comment: https://github.com/Expensify/App/pull/17348/files#r1816579385
- [x] [@eh2077] A discussion in #expensify-bugs has been started about whether any other steps should be taken (e.g. updating the PR review checklist) in order to catch this type of bug sooner. Link to discussion: N/A
- [x] [@eh2077] Determine if we should create a regression test for this bug. **_No_**

**Comment by eh2077** [comment] 2024-10-29 00:42
Not overdue, checklist completed

**Comment by strepanier03** [comment] 2024-10-30 20:11
Thanks @eh2077 I'll close this now that the checklist is done, no reg test is needed, and they job is paid.

**Closed by strepanier03** 2024-10-30 20:11 UTC
Labels: External, Daily, Awaiting Payment, Bug
