### ISSUE TITLE
[$250] Web - Attachment - Attached long image can be briefly opened in full resolution

### ISSUE THREAD

**Issue by IuliiaHerets** [Expensify/App#47646] opened 2024-08-19 16:49 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** v9.0.22-0
**Reproducible in staging?:** Y
**Reproducible in production?:** Y 
**Issue reported by:** Applause Internal Team

## Action Performed:
1. Navigate to https://staging.new.expensify.com/
2. Log in with any account
3. Open any 1:1 chat
4. Send the attached long image to the chat
5. Quickly open it after it appeared in the chat
6. Zoom in
7. Open the image again after it's closed

## Expected Result:
The low resolution image should open for the first time.

## Actual Result:
Attached long image can be briefly opened in full resolution.

## Workaround:
Unknown

## Platforms:

- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

https://github.com/user-attachments/assets/0adc937f-cecd-493e-be1d-9462bdeb0bbb

![Bug6575727_1724046927643!bigggg (1)](https://github.com/user-attachments/assets/eef2ce3b-b944-4929-9cec-d6cd09696339)

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~013a2a8877c3c4d06c</li>
        <li>Upwork Job ID: 1826367055440708714</li>
        <li>Last Price Increase: 2024-08-28</li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @Ollyws</details>

**Comment by IuliiaHerets** [comment] 2024-08-19 16:49
We think that this bug might be related to #vip-vsb

**Comment by IuliiaHerets** [comment] 2024-08-19 16:50
@greg-schroeder  FYI I haven't added the External label as I wasn't 100% sure about this issue. Please take a look and add the label if you agree it's a bug and can be handled by external contributors

**Comment by bernhardoj** [comment] 2024-08-20 14:13
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
We can preview the high res image in its full size.

### What is the root cause of that problem?
When we first trying to upload the hi-res image, the image preview modal will only show the image icon, file name, and a message that preview is disabled when uploading hi-res image.

https://github.com/Expensify/App/blob/d519981587b065ce96f73ab341d84f9eb17a864c/src/components/Attachments/AttachmentView/index.tsx#L232-L249

After we send the image and open the image preview, this time, `isUploaded` is true. Before the image is uploaded to the BE, `isHighResolution` is always false because the file resolution here somehow 0.
https://github.com/Expensify/App/blob/d519981587b065ce96f73ab341d84f9eb17a864c/src/components/Attachments/AttachmentView/index.tsx#L126-L127

But we won't focus on that issue because even if `isHighResolution` is true, the preview source of the local image is the original source of the image.
https://github.com/Expensify/App/blob/d519981587b065ce96f73ab341d84f9eb17a864c/src/components/Attachments/AttachmentView/index.tsx#L249

So, the image is shown at its full resolution. Only after the image is uploaded to the BE, the BE returns the preview source that contains a smaller resolution of the file.

### What changes do you think we should make in order to solve the problem?

We can disable previewing the image before it gets uploaded to the BE. To do that, we need to add `data-expensify-preview-modal-disabled="true"` to the optimistic img tag,
https://github.com/Expensify/App/blob/de9cb1f0b33579c143638eba3e4ab5e9af864808/src/libs/ReportUtils.ts#L4038-L4040

which will disable the preview.
https://github.com/Expensify/App/blob/de9cb1f0b33579c143638eba3e4ab5e9af864808/src/components/HTMLEngineProvider/HTMLRenderers/ImageRenderer.tsx#L62

**Comment by bernhardoj** [comment] 2024-08-26 13:29
Hmm, since we want to make it consistent by viewing the smaller resolution of the file before and after upload, the alternative is to compress it locally before uploading it which is not reliable as pointed out [here](https://github.com/Expensify/App/issues/38180#issuecomment-2188346525).

The other alternative is to allow the user to open the preview, but shows the regular attachment view just like the preview before sending the image (without the send button).
<img width="1705" alt="image" src="https://github.com/user-attachments/assets/54992e7f-c967-4bae-81ab-7a2e16658a2a">

But I don't think it helps that much because the user still can't preview the real image.

**Comment by dannymcclain** [comment] 2024-08-28 18:41
Keen for other designer's thoughts, but I _think_ I might be leaning towards just not letting them click on it until we receive the correctly sized image.

I almost thought that letting them open it and showing them this screen again (without the upload button) 
![image](https://github.com/user-attachments/assets/a1d2827e-0390-4ac3-89a1-ec1118e48fc4)
would make sense since it seems like the image is still kind of uploading in a way, but it's such a pointless thing to look at it might make more sense just to not let them click on the thumbnail until they can actually see something.

**Comment by shawnborton** [comment] 2024-08-28 20:08
I don't feel strongly, I see what you are saying about using the same "You can't see this" modal while we still wait for it to properly upload. I think that feels like it would be the most consistent.

**Comment by dubielzyk-expensify** [comment] 2024-08-28 23:32
I don't have any strong feelings here. Maybe slightly leaning towards what Danny is suggesting here:

> but it's such a pointless thing to look at it might make more sense just to not let them click on the thumbnail until they can actually see something.

**Comment by srikarparsi** [comment] 2024-08-29 05:57
Sounds good, assigning @bernhardoj

**Comment by roryabraham** [comment] 2024-09-02 23:45
Whoa, I think we took the solution much too far for this edge-case issue by disabling all local/offline image previews we spent _years_ building in https://github.com/Expensify/App/pull/44889.

I know we tagged design in here on this big decision, but I feel pretty strongly that we should revert [this](https://github.com/Expensify/App/pull/48241) and go back to the drawing board on solutions.

Brought this up with the team in slack [here](https://expensify.slack.com/archives/C03U7DCU4/p1725320474731139)

**Comment by greg-schroeder** [comment] 2024-09-09 06:31
Pending discussion above

**Comment by greg-schroeder** [comment] 2024-09-17 00:56
@roryabraham can you help summarize where that discussion landed? I admit I'm a bit unfamiliar with this specific space in the product

**Comment by greg-schroeder** [comment] 2024-09-19 01:09
Ah, word, yeah I see that now

**Comment by greg-schroeder** [comment] 2024-09-19 01:13
Payment summary:

Contributor: @bernhardoj - $250 - You can make a manual request via ND
C+: @Ollyws - $250 - You  can make a manual request via ND

This was reverted, but not because of a bug or anything like that - we just decided not to go this route after saying we wanted to originally.

**Closed by greg-schroeder** 2024-09-19 01:13 UTC
Labels: Reviewing, External, Weekly, Bug

**Comment by bernhardoj** [comment] 2024-09-19 04:05
Requested in ND.

**Comment by JmillsExpensify** [comment] 2024-09-19 10:03
$250 approved for @bernhardoj

**Comment by garrettmknight** [comment] 2024-09-24 07:51
$250 approved for @Ollyws
