### ISSUE TITLE
[$1000] Pin/Unpin Offline - Chat returns to previous status when returning online after reload

### ISSUE THREAD

**Issue by mvtglobally** [Expensify/App#19154] opened 2023-05-17 23:05 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
Pinned Offline

1. Navigate to a conversation that is not near the top on the LHN list
2. Disable the internet connection
3. Click/tap on the pin icon on the top right
4. Verify the conversation is now pinned to the top of LHN
5. Refresh the page or Refresh the page or force-kill and relaunch the app
6. Enable the internet connection and refresh the page in Web

Unpin Offline

1. Disable the internet connection
2. Unpin the conversation
3. Refresh the page or Refresh the page or force-kill and relaunch the app
4. Enable the internet connection and refresh the page in Web

## Expected Result:
Pinned Offline - Conversation is still pinned to the top of LHN
Unpin Offline - Conversation is still unpinned and in it's original location in LHN

## Actual Result:
Pinned Offline - Conversation returns to its previous status - Unpinned in it's original location
Unpin Offline - Conversation returns to its previous status - Pinned to the top of LHN

## Workaround:
unknown 

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [x] iOS / native (IPAD)
- [ ] iOS / Safari
- [x] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 1.3.15-6
**Reproducible in staging?:** Y 
**Reproducible in production?:** N 
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation 

https://github.com/Expensify/App/assets/43995119/3e7ac33f-fae8-4b0f-bf3b-2c47ddd897f5
https://github.com/Expensify/App/assets/43995119/4df3a72f-9be7-436e-98dd-570c2a270b10

**Expensify/Expensify Issue URL:**
**Issue reported by:** Applause Internal Team 
**Slack conversation:**

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~013d665287b7e170b5</li>
        <li>Upwork Job ID: 1659704964409548800</li>
        <li>Last Price Increase: 2023-06-14</li>
    </ul>
</details>

**Comment by yuwenmemon** [comment] 2023-05-18 00:28
Not a blocker: https://expensify.slack.com/archives/C07J32337/p1684368975366959

**Comment by marcaaron** [comment] 2023-05-18 00:31
@mvtglobally Can we retest this one? I am not seeing this issue at all on the first two platforms I tried...

Are the test steps correct or could anything be more specific?

**Comment by mvtglobally** [comment] 2023-05-18 01:44
@marcaaron The issue is quite inconsistent. repro on Mac/Chrome/Safari 
I will ask to re-test

**Comment by marcaaron** [comment] 2023-05-22 21:10
@slafortune I'm going OOO this week. Could you please do me a favor and sometime tomorrow:

1. Unassign me from this issue
2. Re-add the Engineering label so a new assignee is picked
3. Assign me again
4. If we don't figure it out by the time I get back I'll unassign whoever got assigned

Thanks!

**Comment by Gonals** [comment] 2023-05-29 13:23
> @marcaaron The issue is quite inconsistent. repro on Mac/Chrome/Safari I will ask to re-test

Were you able to reproduce this again? I'm not seeing it either

**Comment by marcaaron** [comment] 2023-05-31 21:13
I'm gonna close this until we have a more reliable reproduction. Doesn't seem like anyone else has reported this and it's been a couple of weeks now.

**Comment by kbecciv** [comment] 2023-06-13 19:45
Issue is reproduced on build 1.3.27.2

https://github.com/Expensify/App/assets/93399543/767e3c48-05dd-4e0c-9a02-4765caf97161

**Comment by marcaaron** [comment] 2023-06-16 01:14
@kbecciv @aimane-chnaif is it consistently reproducible or not?

**Comment by BeeMargarida** [comment] 2023-06-23 12:18
I can't reproduce this (running in the main branch)

**Comment by marcaaron** [comment] 2023-07-06 23:05
Closing again. Unless we have a reliable reproduction I don't think this is worth prioritizing.

**Closed by marcaaron** 2023-07-06 23:05 UTC
Labels: Engineering, Monthly, Internal, Bug
