### ISSUE TITLE
 Split bill - IOU preview in 1:1 DM is blank with undefined username when bill is split offline

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#27467] opened 2023-09-14 19:08 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Go to staging.new.expensify.com and log in with a new Expensifail account
2. Go offline
3. Create a split bill with users that have no chat history
4. Return to LHN
5. Click on the search icon
6. Click on the newly created 1:1 DM

## Expected Result:
The IOU preview shows the requested details

## Actual Result:
The IOU preview is blank. The usernames above IOU preview shows undefined

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android / native
- [x] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [x] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 1.3.70-2

**Reproducible in staging?:** Yes

**Reproducible in production?:** No

**If this was caught during regression testing, add the test name, ID and link from TestRail:**

**Email or phone of affected tester (no customers):**

**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/78819774/4547b924-e4d6-4c54-8f53-c3fc932d0c84

**Expensify/Expensify Issue URL:**

**Issue reported by:** Applause - Internal Team

**Slack conversation:**

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by francoisl** [comment] 2023-09-14 20:32
Can reproduce on staging and not production, trying to identify the issue now.

**Comment by s-alves10** [comment] 2023-09-14 22:20
I wasn't able to reproduce on staging and on dev

**Comment by francoisl** [comment] 2023-09-15 00:09
This might have to do with betas as it's not reproducible on accounts that are on public domains. It also doesn't prevent from creating the IOU when the user comes back online, so I'll remove the blocker label for now and we can keep investigating later.

**Comment by francoisl** [comment] 2023-09-25 08:54
I just tried this again in dev environment and can no longer reproduce the issue, any chance you can confirm @lanitochka17 please?

**Comment by lanitochka17** [comment] 2023-09-25 18:21
Issue is not reproducible on Build 1.3.74-0


https://github.com/Expensify/App/assets/78819774/8ec0a0b9-d436-4785-95b0-270f65491813

**Comment by francoisl** [comment] 2023-10-03 23:43
Still can't reproduce on 1.3.77-2, closing!

**Comment by lanitochka17** [comment] 2023-10-26 12:39
@francoisl Issue is still  reproduce this by using Expensify account to create split bill with gmail accounts in offline mode.


https://github.com/Expensify/App/assets/78819774/37a30dc5-a4f5-4cfc-bc2a-37c34f4a3eb0

**Comment by francoisl** [comment] 2023-10-27 01:06
Still can't reproduce on v1.3.92-0 😕 I'll demote to weekly for now and try again later

**Comment by francoisl** [comment] 2023-11-11 01:04
Can't reproduce, closing.

**Closed by francoisl** 2023-11-11 01:04 UTC
Labels: Engineering, Weekly, Overdue
