### ISSUE TITLE
[$500] Request money - The transition between tabs is not smooth after changing the merchant

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#31193] opened 2023-11-10 17:58 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.3.98-0
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** Applause - Internal Team
**Slack conversation:**

**Issue found when executing PR** https://github.com/Expensify/App/pull/30420
## Action Performed:
1. Go to URL https://staging.new.expensify.com/
2. Login with any account
3. Go to FAB button -> Request
4. Enter an amount -> Choose an user
5. Click Show More -> Merchant -> Enter the new data -> Save

## Expected Result:
The transition between tabs is smooth

## Actual Result:
The transition between tabs is not smooth

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [x] Android: mWeb Chrome
- [ ] iOS: Native
- [x] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details> 

https://github.com/Expensify/App/assets/78819774/325fb490-9bcd-4eac-9c9c-7c3f1bafa5e6

![Bug6271549_1699637835909!image__174_](https://github.com/Expensify/App/assets/78819774/49965562-8332-4782-85af-cca7dd1dd760)

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~0122f38a619454be7f</li>
        <li>Upwork Job ID: 1723037447965073408</li>
        <li>Last Price Increase: 2023-12-01</li>
    </ul>
</details>

**Comment by AmjedNazzal** [comment] 2023-11-11 10:58
I don't understand this one, So the transition is not smooth when changing merchant, it seem not smooth for me when changing description or anything else as well, probably because changing these results in onyx merge which would cause a bit of lag.

**Comment by beodw** [comment] 2023-11-11 14:14
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
The navigation after saving the merchant page form is not smooth when creating a new manual money request.

### What is the root cause of that problem?
The problem is caused by having to set the new merchant name in onyx using onyx.merge which takes a few milliseconds to set the data and so the animation after the form is saved is interrupted. The updateMerchant calls navigateBack without waiting for the state update to finish.

` function updateMerchant(value) {
        IOU.setMoneyRequestMerchant(value.moneyRequestMerchant, navigateBack);
        navigateBack();
    }`

### What changes do you think we should make in order to solve the problem?
We can instead pass the navigate back method to the action that sets the onyx state and wait for the data to be merged. This can be done by adding a .then clause to the onyx merge call to invoke the navigate back function as a call back. Since setting the onyx state happens quickly , in milliseconds, the user will not see any delay before the navigation starts. The code can be modified to remove the navigateBack call as follows.

` function updateMerchant(value) {
        IOU.setMoneyRequestMerchant(value.moneyRequestMerchant, navigateBack);
    }`
    
   And the action that updates onyx can take this as a callback and start the navigation after the state update is complete.
   
   `function setMoneyRequestMerchant(merchant, callback) {
    Onyx.merge(ONYXKEYS.IOU, {merchant: merchant.trim()})
                          .then((v) => callback());
}`

You can see a video of the functionality with the fix implemented below.

https://github.com/Expensify/App/assets/48998844/92739b04-df3b-478e-98b9-72d4bd03947c


### What alternative solutions did you explore? (Optional)
Alternatively, we could try subscribing to an event for when onyx is done updating its state but this would require an update to its low level pub/sub library so subscribers are notified.

**Comment by beodw** [comment] 2023-11-11 14:25
Contributor details
Your Expensify account email: beodwilson@gmail.com
Upwork Profile Link: https://www.upwork.com/freelancers/~01e23e52119b3f90d6

**Comment by sonialiap** [comment] 2023-11-14 20:54
@fedirjh a new proposal, what do you think?

**Comment by sonialiap** [comment] 2023-11-22 14:23
@beodw bumping [Fedi's question above](https://github.com/Expensify/App/issues/31193#issuecomment-1819018534)

**Comment by sonialiap** [comment] 2023-12-04 13:12
I've shared this issue with the SWM team to see if they're able to pick it up
https://expensify.slack.com/archives/C04878MDF34/p1701695511194639

**Comment by sonialiap** [comment] 2023-12-07 14:57
Taras from Margelo said they can take a look after they finish their current tasks. I've asked today for an ETA so that we can keep melvin peaceful

**Comment by sonialiap** [comment] 2023-12-11 13:18
Bumped them again

**Comment by sonialiap** [comment] 2023-12-14 11:36
We can possibly have them take a look at this next week

**Comment by sonialiap** [comment] 2024-01-05 15:24
The delay is minimal but I can still reproduce it. Bumping margelo

**Comment by chrispader** [comment] 2024-01-08 12:05
Hey everyone i'm Chris from Margelo :)

### Outcomes from my investigation

Just looked at this issue and i'm (only) able to reproduce it with a high-traffic account with 6x CPU throttling as suggested before, though the high-traffic doesn't seem to make any difference.

I agree with what was said before, that this is mainly caused due to a `Onyx.merge` (or really any big onyx operation) happening at the same time as the navigation. Both are triggered simultaneously and then the JS engine schedules the work somehow, so that it causes the navigation to lag...

I noticed this also during my work on the theme switching project, where the UI lags (on web) when you change the theme in the preferences. Imo, this is a somewhat expected effect on web-based platforms with just the JS thread doing all the work.

### Possible solution

You experience this problem in many cases where we navigate at the same time as storing something to Onyx. Especially when throttling the CPU (like 6x in this case) this occurs to me on basically any other page in the settings.

Therefore i think the scope of this is way bigger than just this single flow.

As suggested before, the most straightforward solution to fix this is to just delay the navigation until after the data has been stored to Onyx.

**Comment by dylanexpensify** [comment] 2024-01-15 11:25
Hmm, I couldn't reproduce. I vote close

**Comment by sonialiap** [comment] 2024-01-15 11:35
I'm still seeing a delay, but it's not as bad in my account as in Fedi's comment https://github.com/Expensify/App/issues/31193#issuecomment-1819018534. Most of our ND users probably won't become high-traffic accounts so I we probably won't hear about this from them any time soon. If this is a wider behavior as suspected by Chris, then it will likely crop up in a flow that's used more than updating a merchant name and will become a higher priority for being fixed. I'm going to close this issue for now since it sounds like it requires a larger update then it's worth atm

**Closed by sonialiap** 2024-01-15 11:35 UTC
Labels: Engineering, Weekly, Internal, Overdue, Bug
