### ISSUE TITLE
[NO PAYMENT NEEDED] Desktop - Unable to move click>dragging the header in desktop app

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#23298] opened 2023-07-20 19:03 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Clicked on the header in the desktop app, held it and tried to move the window by dragging it.

## Expected Result:
App to move around like other windows

## Actual Result:
App doesn't move around, or only moves around if you click above LHN (I've experienced it both ways)

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [ ] MacOS / Chrome / Safari
- [x] MacOS / Desktop

**Version Number:** 1.3.42-18
**Reproducible in staging?:** y 
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/93399543/9b4ac195-262c-4e76-9eb4-ed15700389dd

**Expensify/Expensify Issue URL:**
**Issue reported by:** @mallenexpensify 
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1689713770804419

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by jliexpensify** [comment] 2023-07-20 22:49
Nice, thanks for the inpiut @allroundexperts ! @Skalakid and @Santhosh-Sellavel - going to assign this issue to you as it's a regression (?) cc @conorpendergrast in case you need to adjust payments and @roryabraham as the Engineer who was assigned.

**Comment by Santhosh-Sellavel** [comment] 2023-07-24 20:11
@Skalakid Can you take care of this please, thanks!

**Comment by roryabraham** [comment] 2023-07-25 00:02
Spent a bit of time on this. Electron changed so that pressables must have the `webkit-no-drag` class, and I'm not sure there's a straightforward way to address this.

I'm not sure this is really a bug worth fixing, since you can drag anywhere near the top, just not over any pressable items in the header. For example, the whole red area is not draggable:

<img width="755" alt="image" src="https://github.com/Expensify/App/assets/47436092/872861eb-3357-4627-b263-78e0fe352106">

Overall I think the best solution for this problem would be to change `HeaderView` like so:

https://github.com/Expensify/App/assets/47436092/c14ebb74-5133-4d9f-8019-3aba57b7f56c

Where the white area is a regular view where the current `<PressableWithoutFeedback>` is with the same styles, and each individual pressable item is wrapped with a `PressableWithoutFeedback` w/o any styles, such that you have to actually tap on or near the name or avatar to open the profile page, but if you click anywhere else you can drag the window.

**Comment by roryabraham** [comment] 2023-07-25 00:13
hmmm ok, well there may be another alternative:

1. Listen to `mousemove` in `BaseGenericPressable`
1. If the mouse moves while the pressable is in a pressed state, then we'll want to "manually" adjust the position of the window accordingly.
1. Keep track of the window's current position using electron's [`win.getPosition` API](https://www.electronjs.org/docs/latest/api/browser-window#wingetposition)
1. Adjust the window according to the change in mouse position using [`win.setPosition` API](https://www.electronjs.org/docs/latest/api/browser-window#winsetpositionx-y-animate).

Note that the browserWindow APIs are in the main process, so we'll need to use IPC + send events across the context bridge from the renderer process, so I'm skeptical that we'll be able to do in a performant way / without jankiness in the drag gestures.

**Comment by jliexpensify** [comment] 2023-07-28 00:38
Not overdue!

**Comment by Santhosh-Sellavel** [comment] 2023-07-28 22:53
@Skalakid Bump

**Comment by Skalakid** [comment] 2023-07-31 06:45
@Santhosh-Sellavel sorry for the delay, I missed notification about this issue. I'll get into that

**Comment by Skalakid** [comment] 2023-07-31 09:50
According to [Electron documentation](https://www.electronjs.org/pt/docs/latest/api/frameless-window), only the buttons in the draggable area should be marked ad no-draggable:

> And note that if you have made the whole window draggable, you must also mark buttons as non-draggable, otherwise it would be impossible for users to click on them

So I think there is no need to put `no-drag` on all buttons. I propose setting the `nativeID='no-drag-area'` only for the Pressables inside the draggable area, which are:
- HeaderView
- SidebarLinks
- BaseVideoChatButtonAndMenu
- ThreeDotsMenu
- PinButton

After these changes, there should not be problems with dragging the desktop app widow. What do you think about it @Santhosh-Sellavel @roryabraham?

**Comment by roryabraham** [comment] 2023-07-31 16:49
Makes sense to me @Skalakid 👍🏼

Alternatively, since this is very browser-specific we could maybe just use a css selector to apply the style to any pressable that's a descendent of a draggable div. That way this gotcha wouldn't need to be managed as much by developers in the future

**Comment by Skalakid** [comment] 2023-08-02 09:34
@roryabraham that's a good idea. In this case, we should tag all pressable components with some kind of label to access them from CSS. For example, we can set data-id or data-tag to be equal to `pressable`, and then access it by adding  
`#drag-area [data-tag="pressable"]`. Alternatively, we can add something like that:

```css
  #drag-area {
      -webkit-app-region: drag;
  }
  #no-drag-area, #drag-area [class*="touchAction"] {
      -webkit-app-region: no-drag;
  }
```

**Comment by jliexpensify** [comment] 2023-08-03 01:34
Not overdue!

**Comment by Santhosh-Sellavel** [comment] 2023-08-28 19:23
We are close to merging the PR!

**Comment by roryabraham** [comment] 2023-08-28 20:23
Merged

**Comment by jliexpensify** [comment] 2023-09-06 04:45
Payment summary:

- C+: @Santhosh-Sellavel $1000 (reuqest on New.Dot)

Please complete the checklist!

**Comment by Santhosh-Sellavel** [comment] 2023-09-06 20:27
@jliexpensify No payment due here as this is a regression!

**Comment by Santhosh-Sellavel** [comment] 2023-09-06 20:30
@roryabraham I think we can skip the checklist, as all parties are aware of mistakes. I think we don't need a regression test for this one. Should we start a discussion about it?

**Comment by roryabraham** [comment] 2023-09-11 03:45
Sounds good to me. This was really a one-off issue that stemmed from breaking changes in Electron, so not much to learn here other than "oops we missed that in testing"

**Closed by roryabraham** 2023-09-11 03:45 UTC
Labels: Weekly, Needs Reproduction, Awaiting Payment, Bug
