### ISSUE TITLE
[HOLD #10894] Windows - Chat -Photo preview screen disappears after resizing window to full screen

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#20522] opened 2023-06-09 15:02 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___
**Issue found when executing PR** https://github.com/Expensify/App/pull/20440
## Action Performed:
1. Go to https://staging.new.expensify.com/
2. Resize the window to a smaller window
3. Drag and drop a photo to the chat
4. On photo preview screen, resize the window to full screen

## Expected Result:
Photo preview screen does not disappear

## Actual Result:
Photo preview screen disappears

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [x]  Chrome 
- [ ] MacOS / Desktop

**Version Number:** 1.3.26.1

**Reproducible in staging?:** Yes

**Reproducible in production?:** Yes

**If this was caught during regression testing, add the test name, ID and link from TestRail:**

**Email or phone of affected tester (no customers):**

**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/78819774/8de36471-45dd-4d7a-adcc-61589b2625d5

**Expensify/Expensify Issue URL:**

**Issue reported by:** Applause Internal Team

**Slack conversation:**

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by s-alves10** [comment] 2023-06-11 22:29
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
Image preview screen disappears after resizing window from small to full screen or vice versa

### What is the root cause of that problem?

For responsiveness, we use withWindowDimensions HOC in the project. 
`AttachModal` component is remounted when `isSmallScreenWidth` props(from withWindowDimensions) is changed due to the following code lines.

https://github.com/Expensify/App/blob/035783a7984e0214677b5364d9351c968887bf58/src/libs/Navigation/NavigationRoot.js#L66

https://github.com/Expensify/App/blob/035783a7984e0214677b5364d9351c968887bf58/src/libs/Navigation/AppNavigator/createResponsiveStackNavigator/index.js#L36-L56

This is the root cause of this issue.


### What changes do you think we should make in order to solve the problem?

We store draft comments in Oynx store. Similarly, we can store the attachment in Oynx store and load attachment info when page refreshing or remounting.
In order to do this
1. Add Oynx key for storing pending attachment
2. Store the attachment in Oynx store when picked file is valid
3. Load the attachment info from Oynx store when mounting


<details>
    <summary>Result</summary>

https://github.com/Expensify/App/assets/126839717/3f69d0a2-7ec1-4412-a38d-797c740a2066

</details>

### What alternative solutions did you explore? (Optional)

**Comment by roryabraham** [comment] 2023-06-12 22:56
> Similarly, we can store the attachment in Oynx store and load attachment info when page refreshing or remounting

I like the idea, but I don't think we have a straightforward way to do that for now. I believe that this should be on HOLD for something in https://github.com/Expensify/App/issues/10894. @Beamanator can you confirm / help find the specific issue this should be on HOLD for that will enable us to support offline image caching?

**Comment by JmillsExpensify** [comment] 2023-06-14 06:03
Yes, I agree. Doing that now, in fact.

**Comment by JmillsExpensify** [comment] 2023-06-21 04:42
Still on hold. Updating this one to weekly given the hold. Should have done that earlier, in fact.

**Comment by JmillsExpensify** [comment] 2023-07-05 12:52
Still on hold.

**Comment by JmillsExpensify** [comment] 2023-07-19 13:48
Still on hold.

**Comment by JmillsExpensify** [comment] 2023-08-02 04:45
Hold

**Comment by JmillsExpensify** [comment] 2023-08-16 13:52
Hold

**Comment by JmillsExpensify** [comment] 2023-08-30 05:44
Same

**Comment by JmillsExpensify** [comment] 2023-09-13 07:50
Same

**Comment by JmillsExpensify** [comment] 2023-10-12 19:48
Still on hold for the image improvements.

**Comment by JmillsExpensify** [comment] 2023-10-24 18:01
Still held on image improvements

**Comment by JmillsExpensify** [comment] 2023-11-24 16:51
Holding for image initiative.

**Comment by JmillsExpensify** [comment] 2023-12-13 05:09
Same

**Comment by JmillsExpensify** [comment] 2024-01-24 02:39
Closing this issue in line with our decision to not prioritize resizing issues anytime soon.

**Closed by JmillsExpensify** 2024-01-24 02:39 UTC
Labels: Monthly, Overdue, Bug
