### ISSUE TITLE
[$500] Android - Log-Unable to share log as tapping on conversation does not trigger any action

### ISSUE THREAD

**Issue by izarutskaya** [Expensify/App#38209] opened 2024-03-13 10:28 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.51
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**If this was caught during regression testing, add the test name, ID and link from TestRail:** https://expensify.testrail.io/index.php?/tests/view/4422072
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Issue reported by:** Applause-Internal team

## Action Performed:
1. Launch app
2. Login with a new account
3. Tap profile --- about --- troubleshoot
4. Enable client side logging
5. Tap view debug console
6. Note logs are displayed in real-time
7. Enter 5+5
8. Tap execute
9. Tap save log
10. Close the successfully downloaded modal
11. Tap " Share log"
12. In search page, tap on a conversation

## Expected Result:
In search page, tapping on a conversation user must be directed to conversation page and logs must be sent as an attachment.

## Actual Result:
In search page, tapping on a conversation does not trigger any action. User is not navigated to conversation page showing logs sent as an attachment.

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [ ] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

https://github.com/Expensify/App/assets/115492554/8dd8df53-34aa-4e6f-aeec-048f2aa659eb

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01c66f93b0f705d0fa</li>
        <li>Upwork Job ID: 1768329032101048320</li>
        <li>Last Price Increase: 2024-03-14</li>
    </ul>
</details>

**Comment by izarutskaya** [comment] 2024-03-13 10:29
@stephanieelliott I haven't added the External label as I wasn't 100% sure about this issue. Please take a look and add the label if you agree it's a bug and can be handled by external contributors.

**Comment by shahinyan11** [comment] 2024-03-13 11:25
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
Log-Unable to share log as tapping on conversation does not trigger any action
### What is the root cause of that problem?
[Here](https://github.com/Expensify/App/blob/f52bb0239f4f9aa6666a95d7140937e439760f35/src/pages/settings/AboutPage/ShareLogList/BaseShareLogList.tsx#L107C13-L107C29) we return early if `reportID` is not exist. And this can happen if users have not had conversation before
### What changes do you think we should make in order to solve the problem?
Create new report if there is not exist old one. To do that we can do below steps
1. Remove [this](https://github.com/Expensify/App/blob/f52bb0239f4f9aa6666a95d7140937e439760f35/src/pages/settings/AboutPage/ShareLogList/BaseShareLogList.tsx#L107C1-L109C10) code .
2. Add new optional `callback` param for [navigateToAndOpenReport](https://github.com/Expensify/App/blob/f52bb0239f4f9aa6666a95d7140937e439760f35/src/libs/actions/Report.ts#L771C10-L771C33) function. And add following code `callback?.(report.reportID)` after [this](https://github.com/Expensify/App/blob/f52bb0239f4f9aa6666a95d7140937e439760f35/src/libs/actions/Report.ts#L783C5-L783C15) line
3. Update [this](https://github.com/Expensify/App/blob/f52bb0239f4f9aa6666a95d7140937e439760f35/src/pages/settings/AboutPage/ShareLogList/index.tsx#L10C1-L22C7) function with below 
```
    const onAttachLogToReport = (option, filename: string) => {
        function sendAttachment (reportID: string){
            FileUtils.readFileAsync(
                logSource,
                filename,
                (file) => {
                    Report.addAttachment(reportID, file);

                    const routeToNavigate = ROUTES.REPORT_WITH_ID.getRoute(reportID);
                    Navigation.navigate(routeToNavigate);
                },
                () => {},
            );
        }


        if (!option.reportID) {
            Report.navigateToAndOpenReport([option.login], false, sendAttachment );
            return
        }

        sendAttachment(option.reportID)
    };
```
### What alternative solutions did you explore? (Optional)

**Comment by stephanieelliott** [comment] 2024-03-14 17:31
Yea I think this may be a BR issue -- @situchan can you help me confirm?

**Comment by situchan** [comment] 2024-03-14 18:23
This is frontend issue

**Comment by situchan** [comment] 2024-03-14 18:23
@shahinyan11 does this happen only on android or all platforms?

**Comment by shahinyan11** [comment] 2024-03-14 21:00
> @shahinyan11 does this happen only on android or all platforms?

On all platforms

**Comment by Eros472** [comment] 2024-03-15 02:38
```
// Assuming this is within an Adapter for a RecyclerView
@Override
public void onBindViewHolder(@NonNull ViewHolder holder, int position) {
    Conversation conversation = conversations.get(position);

    holder.itemView.setOnClickListener(v -> {
        Intent intent = new Intent(context, ConversationActivity.class);
        intent.putExtra("logData", logData); // Assume logData is a String or serializable object
        context.startActivity(intent);
    });
}
```
In your ConversationActivity, you would then retrieve the log data:


@Override

```
protected void onCreate(Bundle savedInstanceState) {
    super.onCreate(savedInstanceState);
    setContentView(R.layout.activity_conversation);

    // Retrieve the log data
    String logData = getIntent().getStringExtra("logData");
    // Now you can use logData, e.g., display it or attach it to a message
}
```

**Comment by situchan** [comment] 2024-03-18 21:24
Not overdue

**Comment by stephanieelliott** [comment] 2024-03-19 01:07
Closing this based on the [updated guidance](https://github.com/Expensify/Expensify/issues/378661), I think this is somewhat low ROI and can be fixed later when we move to the polish phase.

**Closed by stephanieelliott** 2024-03-19 01:07 UTC
Labels: External, Daily, Bug
