### ISSUE TITLE
[$250] Workspace - Selection for cancellation reason resets after page refresh

### ISSUE THREAD

**Issue by izarutskaya** [Expensify/App#47005] opened 2024-08-07 21:25 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 9.0.17-4
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**Email or phone of affected tester (no customers):** bezawitgebremichael+s1@gmail.com
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Issue reported by:** Applause-Internal team

## Action Performed:
1. Navigate to staging.new.expensify.com
2. Click on settings and navigate to workspace
3. Create a new workspace
4. Go back and navigate to subscription page
5. Click on "Request early cancellation"
6. Select one of the radio buttons
7. Refresh the page

## Expected Result:
Selection is retained even after a refresh since this is the behavior in other places of the app

## Actual Result:
Selection resets after page is refreshed

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

https://github.com/user-attachments/assets/c941ffd6-bf23-4f29-99f7-675eda3a0313

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01284e186343122886</li>
        <li>Upwork Job ID: 1821489506725093881</li>
        <li>Last Price Increase: 2024-08-08</li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @</details>

**Comment by mkzie2** [comment] 2024-08-08 10:02
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
Selection resets after page is refreshed

### What is the root cause of that problem?

The feedback survey component doesn't use `FormProvider` to save the draft value of the form.

The reason and note have the default state as empty then these values are reset every time this component is mounted
https://github.com/Expensify/App/blob/53eee53ac8bfbdfd4d8eeaf16940e3b165483373/src/components/FeedbackSurvey.tsx#L57-58
### What changes do you think we should make in order to solve the problem?
We should use `FormProvider` in `FeedbackSurvey` with `shouldSaveDraft` as `true` for each `InputWrapper`. Keep all `Text` components, only change the reason selector and the note input to `InputWrapper`.

- For the reason selector, we're using `SingleOptionSelector`, we can replace this with `RadioButtons` as we do [here](https://github.com/Expensify/App/blob/53eee53ac8bfbdfd4d8eeaf16940e3b165483373/src/pages/settings/ExitSurvey/ExitSurveyReasonPage.tsx#L84) or we can config to accept `SingleOptionSelector` as a valid `InputComponent` of `InputWrapper`

https://github.com/Expensify/App/blob/53eee53ac8bfbdfd4d8eeaf16940e3b165483373/src/components/FeedbackSurvey.tsx#L88

- For the note field, simply use `InputWrapper` with `InputComponent` as `TextInput`
https://github.com/Expensify/App/blob/53eee53ac8bfbdfd4d8eeaf16940e3b165483373/src/components/FeedbackSurvey.tsx#L98

- This form has a `footerText` before the submit button so we can keep the component here and pass `isSubmitButtonVisible` as `false` to hide the default submit button of `FormProvider`
https://github.com/Expensify/App/blob/53eee53ac8bfbdfd4d8eeaf16940e3b165483373/src/components/FeedbackSurvey.tsx#L108-L109

- Because `FeedbackSurvey` form is used in many places, we should accept a new prop `formID` in this component. Then for each page, we can pass a unique `formID` to store the draft value individually

https://github.com/Expensify/App/blob/53eee53ac8bfbdfd4d8eeaf16940e3b165483373/src/pages/settings/Subscription/RequestEarlyCancellationPage/index.tsx#L100

https://github.com/Expensify/App/blob/53eee53ac8bfbdfd4d8eeaf16940e3b165483373/src/pages/settings/Subscription/DisableAutoRenewSurveyPage/index.tsx#L33
### What alternative solutions did you explore? (Optional)
NA

**Comment by VictoriaExpensify** [comment] 2024-08-08 10:11
Agree this is a bug that should be fixed

**Comment by mkzie2** [comment] 2024-08-08 10:26
I can create a branch for this issue with my proposal if we need the implementation details.

**Comment by mkzie2** [comment] 2024-08-09 07:51
Contributor details
Your Expensify account email: mkzie2@gmail.com
Upwork Profile Link: https://www.upwork.com/freelancers/~019f73367b03c6d784

**Comment by mkzie2** [comment] 2024-08-09 07:54
Thanks for your kind review @ntdiary 🙇

**Comment by mkzie2** [comment] 2024-08-12 17:54
@stitesExpensify Can you approve workflows for https://github.com/Expensify/App/pull/47223?

**Comment by stitesExpensify** [comment] 2024-08-12 21:42
Done

**Comment by mkzie2** [comment] 2024-08-31 04:44
@VictoriaExpensify Can you handle payment for this?

**Comment by VictoriaExpensify** [comment] 2024-09-10 07:20
Hi @mkzie2 - I'm having trouble finding your Upwork profile to send you a job offer. Could you please either accept the job offer we've shared [here](https://github.com/Expensify/App/issues/47005#issuecomment-2278737983) or share your Upwork profile here?

**Comment by VictoriaExpensify** [comment] 2024-09-10 07:23
Payment summary:
**Contributor:** @mkzie2 waiting for them to apply to the [Upwork job](https://github.com/Expensify/App/issues/47005#issuecomment-2278737983)
**Contributor+:** @ntdiary owed $250 via NewDot

**Comment by mkzie2** [comment] 2024-09-10 07:27
@VictoriaExpensify My profile is https://www.upwork.com/freelancers/~019f73367b03c6d784

**Comment by JmillsExpensify** [comment] 2024-09-10 09:39
$250 approved for @ntdiary

**Comment by VictoriaExpensify** [comment] 2024-09-11 03:32
Thanks @mkzie2 . Please accept the offer so I can finalise your payment  - https://www.upwork.com/nx/wm/offer/103908147

**Comment by mkzie2** [comment] 2024-09-11 03:55
@VictoriaExpensify All done

**Comment by VictoriaExpensify** [comment] 2024-09-12 06:59
Payment summary:
Contributor: @mkzie2 paid $250 via [Upwork](https://www.upwork.com/freelancers/~019f73367b03c6d784)

Thanks for your work on this @mkzie2 and @ntdiary

**Closed by VictoriaExpensify** 2024-09-12 06:59 UTC
Labels: Reviewing, External, Daily, Help Wanted, Bug
