### ISSUE TITLE
[HOLD for payment 2023-07-20] [$1000] In offline mode, 'Resend magic code' link is not disabled on 'Contact methods' section, but it is disabled on sign in page

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#21104] opened 2023-06-20 10:56 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Click on 'Profile' avatar
2. Click on 'Profile' link
3. Click on 'Contact methods' link
4. Click on 'New contact method' button
5. Enter email & click on 'Add' button
6. Open the newly added email
7. Open dev tools > open networks tab > change network option to 'offline' mode

## Expected Result:
'Resend magic code' link should be disabled in consistent manner to sign-in page

## Actual Result:
 'Resend magic code' is not disabled

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [x] MacOS / Chrome / Safari
- [x] MacOS / Desktop

**Version Number:** 1.3.29-3

**Reproducible in staging?:** y

**Reproducible in production?:** y

**If this was caught during regression testing, add the test name, ID and link from TestRail:**

**Email or phone of affected tester (no customers):**

**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/93399543/0f56935b-48b9-4783-b90f-b928a7eef7be

https://github.com/Expensify/App/assets/93399543/3738dbb3-3550-461c-b117-e851debda9fc

**Expensify/Expensify Issue URL:**

**Issue reported by:** @Natnael-guchima

**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1686647248813089

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01e3866f1b903f767b</li>
        <li>Upwork Job ID: 1671235847945801728</li>
        <li>Last Price Increase: 2023-07-04</li>
    </ul>
</details>

**Comment by alitoshmatov** [comment] 2023-06-20 11:15
Duplicate - https://github.com/Expensify/App/issues/17836

**Comment by Natnael-Guchima** [comment] 2023-06-20 15:24
@alitoshmatov it seems like both issues are different. On the GH you linked the issue is that spinner spins without end when clicking on 'Resend magic code ' while being offline. On the latest build, user is not able to click on resend magic code link while in offline mode for the link is disabled. This issue address that the same logic of disabling the link applied on sign-in page is not applied on the contact methods section.

**Comment by alitoshmatov** [comment] 2023-06-20 15:26
@Natnael-Guchima We agreed to fix this as well in that issue

**Comment by Natnael-Guchima** [comment] 2023-06-20 15:27
You are right. I just saw that now @alitoshmatov

**Comment by umairabbas786** [comment] 2023-06-20 19:31
I will use javascript to get the status of Internet connectivity and after that using states I will disable the resend magic code link.
I have sent you the proposal on Upwork as well

**Comment by umairabbas786** [comment] 2023-06-20 19:35
Contributor details
Your Expensify account email: umairabbass786@gmail.com
Upwork Profile Link: https://www.upwork.com/freelancers/~011a5022ffea818674

**Comment by kaushiktd** [comment] 2023-06-21 09:41
### Please re-state the problem that we are trying to solve in this issue.
In offline mode, 'Resend magic code' link is not disabled on 'Contact methods' section, but it is disabled on sign in page

### What is the root cause of that problem?
On `BaseValidateCodeForm.js` for a contact method, here `OfflineWithFeedback` component is used and it has no disabled parameters but on the sign in page `PressableWithFeedback` component is used which has disabled parameters. 
So the magic link is not disabled on the contact method page when offline.

### What changes do you think we should make in order to solve the problem?
We need to include network: `networkPropTypes.isRequired`, in `propTypes` and make the below changes to the existing `OfflineWithFeedback` component on `BaseValidateCodeForm.js` file

```
import file at the start of the function
import networkPropTypes from '../../../../../components/networkPropTypes';
import { withNetwork } from '../../../../../components/OnyxProvider';
```

Replace the below mentioned code on selected lines,
https://github.com/Expensify/App/blob/main/src/pages/settings/Profile/Contacts/ValidateCodeForm/BaseValidateCodeForm.js#L178-L183

```
export default compose(
    withLocalize,
    withOnyx({
        account: { key: ONYXKEYS.ACCOUNT },
    }),
    withNetwork(),
)(BaseValidateCodeForm);
```


Add style to `OfflineWithFeedback` component to reduce opacity when it is offline,

`style={props.network.isOffline ? [styles.mt2, styles.buttonOpacityDisabled] : styles.mt2}`


Check the network before triggering `resendValidateCode` function on the below line,
https://github.com/Expensify/App/blob/main/src/pages/settings/Profile/Contacts/ValidateCodeForm/BaseValidateCodeForm.js#L143

`onPress={!props.network.isOffline && resendValidateCode}`

Add `isDisabled` params to the Button to make it disabled,
https://github.com/Expensify/App/blob/main/src/pages/settings/Profile/Contacts/ValidateCodeForm/BaseValidateCodeForm.js#L162

`isDisabled={props.network.isOffline}`


### What alternative solutions did you explore? (Optional)
We should update it to similar to Signin page, by wrapping it with `PressableWithFeedback`,

### Video File:
https://drive.google.com/file/d/1OCWIL11Za-QWMcaiRYbU33JclKENv5Zh/view?usp=sharing

**Comment by Natnael-Guchima** [comment] 2023-06-22 20:40
@lschurr on the latest build, this issue seems to be already fixed by this PR https://github.com/Expensify/App/pull/19409

![image](https://github.com/Expensify/App/assets/57330233/553765a8-fa1a-4f8d-877e-ebadfd0248b5)

**Comment by lschurr** [comment] 2023-06-22 21:01
@0xmiroslav - I was basing that off of the next comment that stated we should fix this as well. Should we close this?

**Comment by alitoshmatov** [comment] 2023-06-23 07:27
@0xmiroslav 
We had the same discussion earlier with @rushatgabhane and we found out that, Contact methods has offline indicator in mobile only(I am not sure why yours is not showing it, but it appears at the bottom). Unlike sign in page where offline indicator put manually, in Contact methods page offline indicator is places in `ScreenWrapper` component which is parent component for every modal screen. 
https://github.com/Expensify/App/blob/6183609c577f2310928bb4e8ee23b52f6dd28e00/src/components/ScreenWrapper/index.js#L124
As you can see it is showing offline indicator only in mobile. The reason I think if we are in desktop we already see offline indicator below composer.

<img width="1440" alt="Screenshot 2023-06-23 at 12 25 27 PM" src="https://github.com/Expensify/App/assets/59907218/cbf9d418-9680-48f9-af8e-d4d049369605">

**Comment by kaushiktd** [comment] 2023-06-23 08:13
@lschurr @0xmiroslav I have just updated my proposal. Please check.

**Comment by kaushiktd** [comment] 2023-06-23 08:47
@0xmiroslav Proposal updated again.

**Comment by lschurr** [comment] 2023-06-26 17:29
Assigning an Engineer for more eyes. Could you review this and help us determine what we should be fixing @francoisl?

**Comment by francoisl** [comment] 2023-06-27 20:40
Yep so to recap:

1. Offline indicator is not shown in the Contact page (discussed in [this comment](https://github.com/Expensify/App/issues/21104#issuecomment-1603751909) and the one directly below)
    - I'm pretty sure what @alitoshmatov explained is correct - the offline indicator already appears below the composer in the page below the modal. Plus, if you resize your browser, the offline indicator appears once the layout changes to the "small size" mode
      <img width="500" alt="image" src="https://github.com/Expensify/App/assets/2229301/2ab19df5-b854-4b22-b50b-61e71ca6cc9b"/>
   So there's nothing to do for this ✅ 

2. There is no 30 second timer to request a new validation code from the contact page
    - I'm checking internally now, but I'd say that this is probably an oversight and we should also add a timer there

3. "Didn't receive a magic code?" vs "Resend magic code" language - this will depend on what we decide for 2) so holding off for now.

**Comment by kaushiktd** [comment] 2023-06-28 02:18
@francoisl What do you think about my proposal?

**Comment by lschurr** [comment] 2023-06-30 20:55
Any update on how we should move forward here @francoisl @0xmiroslav?

**Comment by francoisl** [comment] 2023-07-04 01:02
Getting back to each point to discuss:

> 2. There is no 30 second timer to request a new validation code from the contact page

🚫 I checked internally, it's not necessary to change this for now. The timer was implemented to prevent users from throttling themselves when they didn't receive the code after a few seconds and spammed the button to get a new code. We're not seeing the same thing happen from the Contacts page. There was also a similar discussion here recently: https://github.com/Expensify/App/issues/21619#issuecomment-1608279497

> 3. "Didn't receive a magic code?" vs "Resend magic code" language

✅  Let's fix this inconsistency (good catch btw @0xmiroslav) by using the same language everywhere. We should use the new copy `Didn't receive a magic code?` on the Contacts Methods page.
Can y'all update your proposals please? Should be pretty straightforward 😄

**Comment by kaushiktd** [comment] 2023-07-04 03:35
> Getting back to each point to discuss:
> 
> > 2. There is no 30 second timer to request a new validation code from the contact page
> 
> 🚫 I checked internally, it's not necessary to change this for now. The timer was implemented to prevent users from throttling themselves when they didn't receive the code after a few seconds and spammed the button to get a new code. We're not seeing the same thing happen from the Contacts page. There was also a similar discussion here recently: [#21619 (comment)](https://github.com/Expensify/App/issues/21619#issuecomment-1608279497)
> 
> > 3. "Didn't receive a magic code?" vs "Resend magic code" language
> 
> ✅ Let's fix this inconsistency (good catch btw @0xmiroslav) by using the same language everywhere. We should use the new copy `Didn't receive a magic code?` on the Contacts Methods page. Can y'all update your proposals please? Should be pretty straightforward 😄

@francoisl My proposal already is updated as per this and I have also tried to get some questions cleared over the past few weeks.

**Comment by kaushiktd** [comment] 2023-07-05 04:28
> @kaushiktd can you update your proposal based on latest discussion?
> 
> * remove all unnecessary changes
> * avoid code diff but use plain English
> 
> @hungvu193 thanks for updated proposal but @kaushiktd followed every time I raised questions so was faster to meet the expectations.

@0xmiroslav @francoisl Proposal updated.

**Comment by kaushiktd** [comment] 2023-07-05 04:51
In offline mode, the 'Resend magic code' link is not disabled on the 'Contact methods' section, but it is disabled on the sign in page #21104

Natnael-Guchima commented on this - this issue seems to be already fixed by this PR #19409
see: https://github.com/Expensify/App/issues/21104#issuecomment-1603287597

Then you @0xmiroslav, found another inconsistency issue, and asked to add an offline indicator on the contact page. You can see the comment
https://github.com/Expensify/App/issues/21104#issuecomment-1603751909

I have updated our proposal after that. Again after you @0xmiroslav asked to add a new feature (timer), see the comment
https://github.com/Expensify/App/issues/21104#issuecomment-1603909349

So you see it is coming along as it was requested. 🙂

Hope this is making sense and is enough to answer your last question. If you still need something cleared, I am here and happy to answer.

**Comment by kaushiktd** [comment] 2023-07-05 05:20
Hmm, let me explain even more simply. Following was my initial proposal. NOTE that this proposal was given first by me and when you requested to update them, hungvu193 updated the same, but it is already fixed here by another PR,
https://github.com/Expensify/App/blob/main/src/pages/settings/Profile/Contacts/ValidateCodeForm/BaseValidateCodeForm.js#L145-L156

### Please re-state the problem that we are trying to solve in this issue.
In offline mode, the 'Resend magic code' link is not disabled on 'Contact methods' section, but it is disabled on sign in page

### What is the root cause of that problem?
On BaseValidateCodeForm.js for a contact method, here OfflineWithFeedback component is used and it has no disabled parameters but on the sign in page PressableWithFeedback component is used which has disabled parameters.
So the magic link is not disabled on the contact method page when offline.

### What changes do you think we should make in order to solve the problem?
We should update it to be similar to SigninPage by adding the PressableWithFeedback component as well as changing the text to "Didn't receive a magic code?".

```
<PressableWithFeedback
    disabled={props.network.isOffline}
    style={[styles.mr1]}
    onPress={resendValidateCode}
    underlayColor={themeColors.componentBG}
    hoverDimmingValue={1}
    pressDimmingValue={0.2}
    accessibilityRole="button"
    accessibilityLabel={props.translate('validateCodeForm.magicCodeNotReceived')}
>
    <Text style={[StyleUtils.getDisabledLinkStyles(props.network.isOffline)]}>{props.translate('validateCodeForm.magicCodeNotReceived')}</Text>
</PressableWithFeedback>
```


In `BaseValidateCodeForm.js`, the `OfflineWithFeedback` component is used previously but this is ALREADY fixed by this PR #19409, 
So when you will compare our proposal you will not find the `OfflineWithFeedback` component.

**Comment by kaushiktd** [comment] 2023-07-05 05:39
I am glad I was able to clear your concern and questions! 👍🏻

**Comment by kaushiktd** [comment] 2023-07-06 02:29
@francoisl @0xmiroslav I have applied on the job on Upwork. Should I start working now OR after you award the job to me on Upwork?

**Comment by kaushiktd** [comment] 2023-07-07 03:51
@0xmiroslav PR is raised

**Comment by lschurr** [comment] 2023-07-18 19:21
@Natnael-Guchima please apply for the job in Upwork: https://www.upwork.com/jobs/~01e3866f1b903f767b

**Comment by Natnael-Guchima** [comment] 2023-07-18 19:26
@ischurr I have applied to the job. Thanks.

**Comment by lschurr** [comment] 2023-07-19 20:10
@0xmiroslav - I invited you to the job in Upwork - could you accept and apply?

**Comment by lschurr** [comment] 2023-07-20 15:36
Paid @Natnael-Guchima and @kaushiktd.

**Comment by lschurr** [comment] 2023-07-20 15:37
Also @0xmiroslav - do we need a regression test?

**Closed** 2023-07-20 18:44 UTC
Labels: External, Engineering, Daily, Awaiting Payment, Bug
