### ISSUE TITLE
[HOLD for payment 2023-07-03] [$1000] The current report is not showing in the LHN when using #focus mode

### ISSUE THREAD

**Issue by kavimuru** [Expensify/App#20703] opened 2023-06-13 18:16 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Log in to NewDot
2. Set preference to #focus mode
3. Open a new chat or search for any account to start a chat
## Expected Result:
Current chat report should be shown in LHN
## Actual Result:
Current chat is not showing in the LHN
## Workaround:
Can the user still use Expensify without this being fixed? Have you informed them of the workaround?

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [x] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 1.3.27-2
**Reproducible in staging?:** Needs reproduction ( I can see the report in LHN)
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation

![image (4)](https://github.com/Expensify/App/assets/43996225/2c556693-8599-4fb6-b10b-233e08deea83)
![image (3)](https://github.com/Expensify/App/assets/43996225/33751186-ded4-46eb-b10d-d66e68e77039)

**Expensify/Expensify Issue URL:**
**Issue reported by:** @quinthar 
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1686164246609519

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01347498877cf1755d</li>
        <li>Upwork Job ID: 1669118311685169152</li>
        <li>Last Price Increase: 2023-06-14</li>
    </ul>
</details>

**Comment by StevenKKC** [comment] 2023-06-14 15:14
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
The current report is not displayed in LHN when #focus mode is set.

### What is the root cause of that problem?
The LHN options are filtered in the `ReportUtils.shouldReportBeInOptionList` function, and if it is the current report, it should be displayed in the LHN.
https://github.com/Expensify/App/blob/b20f917f35ca4a2337a667489d2e3a018ae11909/src/libs/ReportUtils.js#LL1859-L1864

But the `this.props.reportIDFromRoute` parameter in the following code is empty and there is no setting.
https://github.com/Expensify/App/blob/b20f917f35ca4a2337a667489d2e3a018ae11909/src/pages/home/sidebar/SidebarLinks.js#LL151

So the current report is not displayed in LHN.
### What changes do you think we should make in order to solve the problem?

We should set a valid parameter to the `SidebarUtils.getOrderedReportIDs`.
```
const optionListItems = SidebarUtils.getOrderedReportIDs(this.props.currentReportId);
```
### What alternative solutions did you explore? (Optional)
None.

**Comment by arielgreen** [comment] 2023-06-14 23:01
Reproduced:
<img width="2056" alt="image" src="https://github.com/Expensify/App/assets/37308300/10edaab9-ee9f-4d4b-989d-ad7b76913a70">

**Comment by s77rt** [comment] 2023-06-15 17:35
@StevenKKC Thanks for the proposal. You RCA is correct and the fix makes sense :+1:.

:ribbon: :eyes: :ribbon: C+ reviewed

cc @joelbettner

**Comment by s77rt** [comment] 2023-06-15 17:38
@Victor-Nyagudi The current opened report should also be visible in the LHN to know which report you are looking at. This is also commented on the code as linked in @StevenKKC above proposal.

**Comment by arielgreen** [comment] 2023-06-16 02:53
Reassigning, team change

**Comment by Christinadobrzyn** [comment] 2023-06-17 19:14
Hi @joelbettner can you just double-check you're good with this and I'll hire?

https://github.com/Expensify/App/issues/20703#issuecomment-1593480133

**Comment by StevenKKC** [comment] 2023-06-18 08:40
@s77rt Could you please confirm what is the current report on mobile?

**Comment by s77rt** [comment] 2023-06-19 10:13
@StevenKKC I'm not sure what you are asking for exactly, the current report on mobile should be the same as the current report on desktop. Is there something more specific that you are looking for here?

**Comment by StevenKKC** [comment] 2023-06-19 10:30
@s77rt My proposal does not work on mobile because the report is not displayed and only LHN is displayed on mobile. So I guess I have to update my proposal. 
I think the current report is just the last read report on mobile.

**Comment by StevenKKC** [comment] 2023-06-19 10:53
@s77rt Could you please confirm that the current report is just the last read report on mobile?

**Comment by s77rt** [comment] 2023-06-19 11:09
The current report is actually the current report not the last read one. On mobile after going to LHN, the current report will be `undefined` (no report is open).
I think this issue is only for web/desktop, as on small screens we don't seem to highlight any option.

**Comment by joelbettner** [comment] 2023-06-20 17:45
> Hi @joelbettner can you just double-check you're good with this and I'll hire?

@Christinadobrzyn yep, this looks good to me! Sorry for the delay. I was OOO on Friday and yesterday.

**Comment by Christinadobrzyn** [comment] 2023-06-20 18:04
Hired in Upwork - 
Internal job- https://www.upwork.com/ab/applicants/1669118311685169152/job-details
External job- https://www.upwork.com/jobs/~01347498877cf1755d

- C+ - @s77rt 
- Contributor - @StevenKKC

**Comment by s77rt** [comment] 2023-06-20 18:34
@joelbettner Can you please assign @StevenKKC

**Comment by StevenKKC** [comment] 2023-06-20 20:40
I hired in Upwork, so can I create the PR? Or should I wait until @joelbettner assign me?

**Comment by s77rt** [comment] 2023-06-20 22:23
@StevenKKC I think you can create the PR. Please make sure to remove the outdated `reportIDFromRoute` prop across the App.

**Comment by StevenKKC** [comment] 2023-06-21 05:57
@s77rt @joelbettner @Christinadobrzyn PR(https://github.com/Expensify/App/pull/21176) is ready for review.

**Comment by s77rt** [comment] 2023-06-26 23:34
- The PR that introduced the bug has been identified: https://github.com/Expensify/App/pull/16581
- The offending PR has been commented on: https://github.com/Expensify/App/pull/16581#discussion_r1242912615
- A discussion in #expensify-bugs has been started: The bug was just due not replacing an old prop with the new one. `Replace All` operation could have prevented this bug. So I don't think we have anything to discuss here.
- Determine if we should create a regression test for this bug: Yes

___

**Regression Test Proposal**

For some reason we have two test cases that are the same https://expensify.testrail.io/index.php?/cases/view/2616981 and https://expensify.testrail.io/index.php?/cases/view/1971042. 

13. Navigate to the unread conversation (conv 3)  and open it so it's marked as unread
14. **Verify** conversation 3 is still displayed in LHN

**Comment by StevenKKC** [comment] 2023-06-27 16:57
@s77rt Is regressions arised? `MainDrawerNavigator.js` seems deleted previously.

**Comment by s77rt** [comment] 2023-06-27 21:46
@StevenKKC No, I'm filling in the checklist explaining the source of the bug. The current solution didn't introduce any regressions AFAIK.

**Comment by Christinadobrzyn** [comment] 2023-07-05 21:11
Ready to be paid! 

- Looks like this gets a speed bonus (PR created June 20th - merged June 22nd)
- Paying in upwork based on https://github.com/Expensify/App/issues/20703#issuecomment-1599266439
- Closed job in upwork and this GH

**Closed by Christinadobrzyn** 2023-07-05 21:11 UTC
Labels: External, Daily, Overdue, Awaiting Payment, Bug

**Comment by s77rt** [comment] 2023-07-05 22:06
@joelbettner or @Christinadobrzyn can you please assign @StevenKKC

**Comment by s77rt** [comment] 2023-07-10 17:50
@StevenKKC You still need to be assigned here for stats related.

**Comment by s77rt** [comment] 2023-07-18 23:06
@joelbettner or @Christinadobrzyn ^

**Comment by s77rt** [comment] 2023-07-27 21:38
@joelbettner @Christinadobrzyn can you please assign @StevenKKC

**Comment by Christinadobrzyn** [comment] 2023-08-01 21:37
sorry for the delay! Just assigned @StevenKKC to this issue. Let me know if you need anything else!
