### ISSUE TITLE
[$500] Web - Unread threads showing in OldDot Inbox but not in NewDot

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#27714] opened 2023-09-18 21:00 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Join a thread but do not say anything in the thread
2. Someone else posts a message in the thread
3. Your NewDot shows unread without any message to be seen (even via focus mode)
4. You log into expensify.com and see an unread thread

## Expected Result:
 Expect to not have an unread message indicator OR see the unread thread to be shown in LHN
 
## Actual Result:
Unread message indicator is shown

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [x] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 1.3.70.5
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation

![Screenshot 2023-09-18 at 10 22 49 AM](https://github.com/Expensify/App/assets/93399543/3e33fa29-1ed6-4e45-8183-c6d22f9ff4a9)
![Screenshot 2023-09-18 at 10 22 57 AM](https://github.com/Expensify/App/assets/93399543/da6d25c9-fda5-4c1d-9258-ad60c249dc50)
![Screenshot 2023-09-18 at 10 23 06 AM](https://github.com/Expensify/App/assets/93399543/87a28e74-8991-4067-8837-92523f411128)

**Expensify/Expensify Issue URL:**
**Issue reported by:** @AndrewGable 
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1695003756788459

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by AndrewGable** [comment] 2023-09-19 01:16
I'm not 100% sure this is external, I would imagine this is back end related.

**Comment by AndrewGable** [comment] 2023-09-19 02:43
Dupe of https://github.com/Expensify/App/issues/27512

**Closed by AndrewGable** 2023-09-19 02:43 UTC
Labels: External, Daily, Help Wanted, Bug
