### ISSUE TITLE
Unable to change my contact method because there is no option for set to default for other contact methods.

### ISSUE THREAD

**Issue by kavimuru** [Expensify/App#18458] opened 2023-05-04 23:00 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:

1. Login to an account which has multiple Contact methods. Or add multiple contact methods if it doesn’t have multiple
2. Go to Settings -> Profile -> Contact Method.
3. Click on default contact method. Notice the text on the screen it is
 `This is your current default contact method. You will not be able to delete this contact method until you set an alternative default by selecting another contact method and pressing "Set as default".`

4. Now go back and click on some other contact method. Notice there is no option of `Set as default`  in the second contact method.
## Expected behavior: 
1. Remove You will not be able to delete this contact method until you set an alternative default by selecting another contact method and pressing "Set as default". this line from default contact method.
OR
2. Add Set as default button in non default contact methods.
## Actual result:
 there is no option of Set as default  in the second contact method.
## Workaround:
Can the user still use Expensify without this being fixed? Have you informed them of the workaround?

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android / native
- [x] Android / Chrome
- [x] iOS / native
- [x] iOS / Safari
- [x] MacOS / Chrome / Safari
- [x] MacOS / Desktop

**Version Number:** 1.3.10-4
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation

https://user-images.githubusercontent.com/43996225/236347821-141e363b-2708-4c84-89b6-63c2febe722f.mov

https://user-images.githubusercontent.com/43996225/236347836-17c7e1ca-633a-43e3-9c33-20c886992904.mp4

**Expensify/Expensify Issue URL:**
**Issue reported by:** @hasebsiddiqui 
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1683232562214179

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by hasebsiddiqui** [comment] 2023-05-04 23:19
# Proposal
## Please re-state the problem that we are trying to solve in this issue.
Unable to change default contact method.

## What is the root cause of that problem?
The problem is because of below line in screen of default contact method. We should remove this line to make the text consistent with the flow.
```
This is your current default contact method. You will not be able to delete this contact method until you set an alternative default by selecting another contact method and pressing "Set as default".
```

## What changes do you think we should make in order to solve the problem?

We need to update [this](https://github.com/Expensify/App/blob/5f649d5045762177c6a6db08265d2d82655bce71/src/languages/en.js#L384) line to below to make text consistent with the already present flow.
```
yourDefaultContactMethod: 'This is your current default contact method.'
```

## What alternative solutions did you explore? (Optional)
NA

**Comment by isabelastisser** [comment] 2023-05-05 10:18
I'm OOO, reassigning!

**Comment by Natnael-Guchima** [comment] 2023-05-05 11:51
I think this issue is being addressed here > https://github.com/Expensify/App/issues/16747

**Comment by bfitzexpensify** [comment] 2023-05-08 12:45
Agreed @Natnael-Guchima - closing this one out.

**Closed by bfitzexpensify** 2023-05-08 12:45 UTC
Labels: Daily, Overdue, Bug
