### ISSUE TITLE
Android - Chat - Avatar and welcome message disappear after creating a new not existing account

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#20994] opened 2023-06-18 16:04 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Open the App
2. Login with any account
3. Go to FAB -> New chat
4. Enter any email for new NOT existing user -> Put on it

## Expected Result:
Chat with new user created and NOT dissapears

## Actual Result:
Avatar and welcome message disappear after creating a new not existing account. Chat with this new account also disappears and appears only after some time

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android / native
- [x] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [ ] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 1.3.29.0

**Reproducible in staging?:** Yes

**Reproducible in production?:** No

**If this was caught during regression testing, add the test name, ID and link from TestRail:**

**Email or phone of affected tester (no customers):**

**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/78819774/2ac5680a-4162-4a63-95a9-d7dff19c8456

**Expensify/Expensify Issue URL:**

**Issue reported by:** Applause - Internal Tream

**Slack conversation:**

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by cead22** [comment] 2023-06-19 22:36
@lanitochka17 I was unable to reproduce, can you try again and share very detailed steps if you can reproduce reliably? Thanks!

On Android simulator in local dev environment
![](http://g.recordit.co/HxVZRaWEz3.gif)

On browserstack, Pixel 3a, on version 1.3.29.0
https://github.com/Expensify/App/assets/165133/25ff3584-b7c6-4925-a4de-e58e1d425114

**Comment by lanitochka17** [comment] 2023-06-19 23:09
@cead22 Issue is reproducible.
Detailed steps: 
1. Open the App
2. Login with any expensify account
3. Put on FAB -> New chat
4.Quickly enter several random symbols + @gmail.com, e.g. dfgsdf@gmail.com 


https://github.com/Expensify/App/assets/78819774/01ae2fae-d9ac-4c30-acf0-cfd7f65c6fbc

**Comment by cead22** [comment] 2023-06-20 20:59
@lanitochka17 I'm still unable to reproduce, what phone are you using?

![](http://recordit.co/vvBG1Tj0sM.gif)

**Comment by lanitochka17** [comment] 2023-06-20 21:29
@cead22 Realme6/Android11

**Comment by Nikhil-Vats** [comment] 2023-06-30 16:16
@cead22 i was able to repro this only with a phone number. It works fine for me when I use an email.

**Comment by cead22** [comment] 2023-06-30 16:31
Thank you, I'll give that a try. I've been focused on other things that came up this week, that's why I haven't provided an update here

**Comment by Nikhil-Vats** [comment] 2023-06-30 16:57
Also, this happens on all platforms for me.

**Comment by cead22** [comment] 2023-07-28 22:41
It looks like I lost access to test android apps in browserstack, so I requested it

**Comment by cead22** [comment] 2023-07-28 23:28
I got access, but I still couldn't reproduce. It looks like we don't have v1.3.29-3 available to test on android on browserstack, so I used the most recent version available, but still no luck so I'm going to close this. 

If you can still somehow reproduce, don't hesitate to reopen

https://github.com/Expensify/App/assets/165133/c129c8ba-7204-4c86-9e42-6931b8e258fa

**Closed by cead22** 2023-07-28 23:28 UTC
Labels: Engineering, Weekly, Needs Reproduction
