### ISSUE TITLE
[$1000] Web- Contact methods - Settings page appears for a moment when clicking Esc button twice

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#20398] opened 2023-06-07 17:39 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Go to URL https://staging.new.expensify.com/
2. Login with any account
3. Go to Settings -> Profile -> Contact methods -> Open verified contact method -> Remove
4. Click the Esc button twice

## Expected Result:
App redirected to LHN

## Actual Result:
The settings page appears for a moment

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [x] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 1.3.25.2

**Reproducible in staging?:**  Yes 

**Reproducible in production?:** No

**If this was caught during regression testing, add the test name, ID and link from TestRail:**

**Email or phone of affected tester (no customers):**

**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/78819774/9fbcd9ff-df3c-4b76-ac55-f4429b82fd10

https://github.com/Expensify/App/assets/78819774/c705d534-cf82-44d1-bf4e-a112b6b9fcce

**Expensify/Expensify Issue URL:**

**Issue reported by:** Aplause - Internal Team

**Slack conversation:**

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~017f44c655a73ebc60</li>
        <li>Upwork Job ID: 1666574571521617920</li>
        <li>Last Price Increase: 2023-06-14</li>
    </ul>
</details>

**Comment by roryabraham** [comment] 2023-06-07 20:39
Interesting. I think that `ESC` should only close one "level" of modals. i.e: pressing escape with the confirm delete modal open should bring the user to the page they were in before the confirm delete modal was opened. Pressing it again should close the RHP and bring them back home.

I think this is a legitimate bug but imo not a deploy blocker because it's an edge case. Going to make this a regular bug.

**Comment by mountiny** [comment] 2023-06-07 20:39
This is related to navigation refactor and i dont think this is a blocker but a polish bug we should handle as a follow up, removing rhe label

**Comment by joekaufmanexpensify** [comment] 2023-06-08 12:16
@alexpensify assigning back to you as you were [the original BZ assignee ](https://github.com/Expensify/App/issues/20398#issuecomment-1581476574), not sure why the external label assigned someone else

**Comment by mountiny** [comment] 2023-06-08 19:27
@MrJithil I think your videos did not load correctly

**Comment by MrJithil** [comment] 2023-06-08 19:54
> @MrJithil I think your videos did not load correctly

Could you please check now. In case still if you didn't find it working, here is the url to the fixed url [please check](https://github.com/Expensify/App/assets/26359740/866e1d89-4754-4c8a-991b-91288a0d41ab)

**Comment by narefyev91** [comment] 2023-06-09 07:56
@MrJithil proposal looks good to me, but i agree with @mountiny that your videos is not working inside proposal - can you please fix them, good that you add link to video in additional comment, but we should follow the standard approach - let's fix that. Thanks!

**Comment by MrJithil** [comment] 2023-06-09 08:20
I have re uploaded the video by omitting formatting and table layout. Please check the updated proposal. 

@narefyev91 @mountiny

**Comment by narefyev91** [comment] 2023-06-09 08:58
<img width="274" alt="Screenshot 2023-06-09 at 11 57 47" src="https://github.com/Expensify/App/assets/28352309/61cf60c5-14a1-48cb-9b92-798ada4f868d">
@MrJithil can you please remove this / please

**Comment by MrJithil** [comment] 2023-06-09 09:04
> <img alt="Screenshot 2023-06-09 at 11 57 47" width="274" src="https://user-images.githubusercontent.com/28352309/244645224-61cf60c5-14a1-48cb-9b92-798ada4f868d.png"> @MrJithil can you please remove this / please

Done. Sorry for that.

**Comment by MrJithil** [comment] 2023-06-09 11:42
@narefyev91 should I wait for more reviews? Or can I go ahead with PR?

**Comment by narefyev91** [comment] 2023-06-09 13:09
> @narefyev91 should I wait for more reviews? Or can I go ahead with PR?

I think it's fine - we need only some one to assign this ticket to you - to start working on PR - @alexpensify @mountiny

**Comment by alexpensify** [comment] 2023-06-09 15:03
All set @MrJithil - the issue has been assigned over. Thank you @narefyev91 for the reviews here.

**Comment by MrJithil** [comment] 2023-06-09 15:04
> All set @MrJithil - the issue has been assigned over. Thank you @narefyev91 for the reviews here. 

Thank You so much. Happy to look forward with this.

**Comment by MrJithil** [comment] 2023-06-09 15:29
I have submitted an application on Upwork with the accepted GH proposal. The code modification required for this task is minimal, and I can prepare the pull request within a short timeframe.

However, as this is going to be my first contribution to Expensify/App, I need to train myself with all the necessary steps involved in our contribution process, including testing on various platforms, linting, and CLA signing.

Therefore, I aim to have the pull request ready for review on or before Monday, June 12th, 2023. This deadline will provide me with ample time to familiarize myself with the required steps and ensure their accurate completion.

**Comment by MrJithil** [comment] 2023-06-10 07:21
PR raised. Please check: https://github.com/Expensify/App/pull/20534

CC: @narefyev91

**Comment by mountiny** [comment] 2023-06-12 13:27
@adamgrzybowski @WoLewicki noted this might not be a good solution as it will most likely remove the navigation browser history in the stack

**Comment by mountiny** [comment] 2023-06-12 14:39
@MrJithil sorry for the confusion here, even if you wont fix this, I think we should pay you 25% of the reward so $250 for your efforts. 

Looking for new proposals

**Comment by MrJithil** [comment] 2023-06-12 15:16
No problem. I will also, investigate some possible ways to handle and submit proposals again.

**Comment by alexpensify** [comment] 2023-06-14 16:23
Not overdue, we are still taking proposals.

**Comment by alexpensify** [comment] 2023-06-17 17:09
Not overdue, this one is open and taking proposals.

**Comment by bernhardoj** [comment] 2023-06-18 13:51
I think this issue is fixed by https://github.com/Expensify/App/pull/20815?

**Comment by alexpensify** [comment] 2023-06-18 15:36
Thanks for flagging - @mountiny and @narefyev91 do you agree that we should close this one?

**Comment by narefyev91** [comment] 2023-06-19 07:39
> Thanks for flagging - @mountiny and @narefyev91 do you agree that we should close this one?

Seems so - we should close this one

**Comment by mountiny** [comment] 2023-06-19 11:17
The PR is in staging, can we confirm it has been fixed?

**Comment by narefyev91** [comment] 2023-06-19 11:37
> The PR is in staging, can we confirm it has been fixed?

I already checked in the morning - issue is not reproduced

**Closed** 2023-06-19 14:39 UTC
Labels: External, Engineering, Daily, Bug

**Comment by alexpensify** [comment] 2023-06-20 21:44
Thank you!
