### ISSUE TITLE
[HOLD for payment 2023-02-01] [$1000] align center the tooltip positions for Action, Expand & Collapse icon in the composer

### ISSUE THREAD

**Issue by kavimuru** [Expensify/App#14231] opened 2023-01-12 00:58 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Open NewDot
2. Go to any chat
3. Hover on the action icon in composer

## Expected Result:
tooltip should be in center

## Actual Result:
tooltip is a bit left due to margin

## Workaround:
unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?

- [ ] MacOS / Chrome / Safari

**Version Number:** v1.2.52-4
**Reproducible in staging?:**  y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** 

https://user-images.githubusercontent.com/43996225/211950504-1c2d1121-4f83-4252-a830-62a96b21fe85.mp4

**Expensify/Expensify Issue URL:**
**Issue reported by:** @Pujan92 
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1673451314939289

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~011b242d650b4831ce</li>
        <li>Upwork Job ID: 1613553625941708800</li>
        <li>Last Price Increase: 2023-01-12</li>
    </ul>
</details>

**Comment by bondydaa** [comment] 2023-01-12 15:08
assigning Eugene and myself again since it's coming from this previous one https://github.com/Expensify/App/issues/14043#issuecomment-1376821502

**Comment by Pujan92** [comment] 2023-01-12 15:10
**Proposal**

Apply left margin to `View` and update the icons style to center the tooltip.

```diff
diff --git a/src/pages/home/report/ReportActionCompose.js b/src/pages/home/report/ReportActionCompose.js
index acd262d2e..be14c741e 100644
--- a/src/pages/home/report/ReportActionCompose.js
+++ b/src/pages/home/report/ReportActionCompose.js
@@ -560,7 +560,7 @@ class ReportActionCompose extends React.Component {
                                     {({openPicker}) => (
                                         <>
                                             <View style={[
-                                                styles.dFlex, styles.flexColumn,
+                                                styles.ml1, styles.dFlex, styles.flexColumn,
                                                 (this.state.isFullComposerAvailable || this.props.isComposerFullSize) ? styles
.justifyContentBetween : styles.justifyContentEnd,
                                             ]}
                                             >
diff --git a/src/styles/styles.js b/src/styles/styles.js
index 3719a37e0..eb65886cd 100644
--- a/src/styles/styles.js
+++ b/src/styles/styles.js
@@ -1547,13 +1547,11 @@ const styles = {
         width: 32,
         marginBottom: 4,
         marginTop: 4,
-        marginLeft: 4,
         justifyContent: 'center',
     },
 
     composerSizeButton: {
         alignItems: 'center',
-        alignSelf: 'flex-end',
         height: 26,
         marginBottom: 6,
         marginTop: 6,
```

**Comment by bondydaa** [comment] 2023-01-12 15:10
taking off help wanted bc we're just waiting for @Pujan92 to post their proposal I linked above so we can assign them.

**Comment by abekkala** [comment] 2023-01-12 15:27
Not sure why it assigned both Greg and I as the BZ team member. I'll take this one and unassign Greg

**Comment by abekkala** [comment] 2023-01-12 15:34
@Pujan92 I invited you to the job in Upwork

**Comment by Pujan92** [comment] 2023-01-12 15:57
Thanks @bondydaa and @abekkala. I applied for the job.

**Comment by Pujan92** [comment] 2023-01-12 17:09
PR is ready for review

**Comment by eVoloshchak** [comment] 2023-01-19 18:30
Not overdue, PR is in review

**Comment by bondydaa** [comment] 2023-01-23 15:57
merged the PR 🎉 this is the first time I've had a contrib PR go a little long but I don't think there should be anything outside of the "normal" pay flows. 

PR got delayed b/c we had to figure out why a regression popped up and figure out how best to get it fixed https://github.com/Expensify/App/issues/13940#issuecomment-1398735531

**Comment by bondydaa** [comment] 2023-01-30 16:33
not overdue, awaiting payment.

**Comment by abekkala** [comment] 2023-01-31 14:21
@bondydaa do you know what prompts the checklist to be posted from melvin?

**Comment by abekkala** [comment] 2023-02-01 18:58
- Contributor who reported the issue - @Pujan92 - $250
- Contributor who completed the job - @Pujan92 - $1000 
- Contributor+ who reviewed PR - @eVoloshchak - $500 (Not $1000 due to regression, 50% penalty)



@bondydaa can I have you verify that above?

**Comment by abekkala** [comment] 2023-02-01 19:09
The App PR was deployed to production. I'm not sure why the checklist didn't post automatically so here it is.

**BugZero Checklist**: The PR fixing this issue has been merged! 

The following checklist ([instructions](https://stackoverflow.com/c/expensify/questions/14574)) will need to be completed before the issue can be closed:

- [ ]  [@bondydaa  / @eVoloshchak ] The PR that introduced the bug has been identified. Link to the PR:

- [ ]  [@bondydaa / @eVoloshchak ] The offending PR has been commented on, pointing out the bug it caused and why, so the author and reviewers can learn from the mistake. Link to comment:

- [ ]  [@bondydaa  / @eVoloshchak ] A discussion in #expensify-bugs has been started about whether any other steps should be taken (e.g. updating the PR review checklist) in order to catch this type of bug sooner. Link to discussion in Slack 

- [ ]  [@abekkala] A [regression test](https://expensify.testrail.io/index.php?/dashboard) has been added or updated so that the same bug will not reach production again. Link to the GH issue for creating the test here:

**Comment by gadhiyamanan** [comment] 2023-02-02 04:34
tooltip still not in the center 
cc @bondydaa @eVoloshchak @Pujan92 
![Screenshot 2023-02-02 at 10 01 17 AM](https://user-images.githubusercontent.com/54790231/216232356-3b0b0af5-361b-4c57-9e7a-0be6f7e4cec8.png)

**Comment by Pujan92** [comment] 2023-02-02 06:33
> tooltip still not in the center cc @bondydaa @eVoloshchak @Pujan92 ![Screenshot 2023-02-02 at 10 01 17 AM](https://user-images.githubusercontent.com/54790231/216232356-3b0b0af5-361b-4c57-9e7a-0be6f7e4cec8.png)

<img width="1438" alt="Screenshot 2023-02-02 at 11 57 33 AM" src="https://user-images.githubusercontent.com/14358475/216248558-5d021c0c-7f79-4370-b0b4-1c185dde93e7.png">

<img width="573" alt="Screenshot 2023-02-02 at 12 02 31 PM" src="https://user-images.githubusercontent.com/14358475/216249317-f0afbf8e-2246-43f2-9410-05c4cac7883d.png">

As I checked in the code 1px right border is also considered for the tooltip which might have 0.5px difference but in my system, it seems unnoticeable.

**Comment by gadhiyamanan** [comment] 2023-02-02 06:40
@Pujan92 above screenshot is of web not mweb

**Comment by Pujan92** [comment] 2023-02-02 06:44
> @Pujan92 above screenshot is of web not mweb

Ok, lets @eVoloshchak & @bondydaa check once.

**Comment by eVoloshchak** [comment] 2023-02-02 15:14
Can confirm, it's slightly off to the right if you zoom really closely
<img width="438" alt="Screenshot 2023-02-02 at 17 12 23" src="https://user-images.githubusercontent.com/9059945/216363557-15daa95f-9795-4a45-9e49-484bdb4ceb8d.png">
@gadhiyamanan, thanks for noticing this!
@Pujan92, could you please look into what might have caused this?

**Comment by Pujan92** [comment] 2023-02-02 15:29
> Can confirm, it's slightly off to the right if you zoom really closely <img alt="Screenshot 2023-02-02 at 17 12 23" width="438" src="https://user-images.githubusercontent.com/9059945/216363557-15daa95f-9795-4a45-9e49-484bdb4ceb8d.png"> @gadhiyamanan, thanks for noticing this! @Pujan92, could you please look into what might have caused this?

@eVoloshchak Yes, It is right by 0.5px due to the current tooltip considering the right green border of 1 px which I missed while testing. Only wondering why for @gadhiyamanan it's showing very far on the right side. @gadhiyamanan your shared screenshot is without zoom?

**Comment by bondydaa** [comment] 2023-02-02 22:56
when you say "zoom"ing you are zooming in on the browser? or just zooming in on the screenshot in an image editing software?

**Comment by eVoloshchak** [comment] 2023-02-02 23:03
Yes, zooming in on the browser
<img width="1512" alt="Screenshot 2023-02-03 at 01 02 26" src="https://user-images.githubusercontent.com/9059945/216470808-2b948cd0-6140-42e1-b03f-32dfd5e6164e.png">

**Comment by bondydaa** [comment] 2023-02-02 23:06
okay, I'm not sure we should worry too much with zooming in on the browser with this one (or other things as well).

**Comment by bondydaa** [comment] 2023-02-03 00:07
hmm
 
>    Contributor who reported the issue - @Pujan92 - $250
>    Contributor who completed the job - @Pujan92 - $1000
>    Contributor+ who reviewed PR - @eVoloshchak - $500 (Not $1000 due to regression, 50% penalty)

The regression wasn't exactly anyone's fault or something that got missed in the review so I think the $1000 is fine. The regression surfaced be believe b/c of a bad merge conflict in a different PR from an internal employee.

**Comment by eVoloshchak** [comment] 2023-02-06 13:19
Not overdue, awaiting for payment

**Comment by abekkala** [comment] 2023-02-06 16:53
@bondydaa does this require a regression test for test rail since it was more visual than operational?

**Comment by abekkala** [comment] 2023-02-06 16:54
I assume that's also why the other checklist items above mine haven't/weren't completed?

**Comment by eVoloshchak** [comment] 2023-02-07 11:37
I can take care of the first three checklist items in a couple of hours

**Comment by abekkala** [comment] 2023-02-07 16:21
Contributor who reported the issue - @Pujan92 - $250 + $250 bonus (reporting and fix)
Contributor who completed the job - @Pujan92 - $1000
Contributor+ who reviewed PR - @eVoloshchak - $1000

**Comment by abekkala** [comment] 2023-02-07 16:23
@Pujan92 I have submitted your payment in Upwork for $1,500

**Comment by Pujan92** [comment] 2023-02-07 16:24
> @Pujan92 I have submitted your payment in Upwork for $1,500

Received, Thanks!

**Comment by abekkala** [comment] 2023-02-07 16:41
@eVoloshchak  I have submitted your payment in Upwork for $1,000

**Comment by abekkala** [comment] 2023-02-07 16:47
Both payments have been sent, the contract has been completed, and the Upwork job post has been closed.

**Comment by eVoloshchak** [comment] 2023-02-07 16:54
I think the first 3 checklist items should be the same as in https://github.com/Expensify/App/issues/14043#issuecomment-1400588736, tooltips were added to all icon buttons in a single PR

**Closed** 2023-02-10 15:43 UTC
Labels: External, Daily, Awaiting Payment, Bug
