### ISSUE TITLE
[$500] Split Bill - Amount turns to grayed out when User press Ctrl+Enter in Group conversation IOU

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#27043] opened 2023-09-08 16:20 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Navigate to staging.new.expensify.com
2. Click the '+' button in a Group conversation
3. Select Split Bill option
4. Enter an amount and press Next
5. Deselect all the participants of the list by using the arrow keys and ENTER
6. Press Ctrl+Enter

## Expected Result:
Nothing should happens when user press Ctrl+Enter

## Actual Result:
Amount field turns to grayed out

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [x] Windows / Chrome 
- [ ] MacOS / Desktop

**Version Number:** 1.3.66-1

**Reproducible in staging?:** Yes

**Reproducible in production?:** Yes

**If this was caught during regression testing, add the test name, ID and link from TestRail:**

**Email or phone of affected tester (no customers):**

**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/78819774/081e3911-1db9-45a0-814b-f67fbe78a220

**Expensify/Expensify Issue URL:**

**Issue reported by:** Applause - Internal team

**Slack conversation:**

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~0138924214c461038e</li>
        <li>Upwork Job ID: 1701240648855633920</li>
        <li>Last Price Increase: 2023-09-18</li>
    </ul>
</details>

**Comment by maddylewis** [comment] 2023-09-11 14:26
adding external label to review proposal

**Comment by ArekChr** [comment] 2023-09-13 09:42
It looks like I can't even select and unselect participants by mouse

https://github.com/Expensify/App/assets/24796318/8994e88e-b163-44ab-a1b3-7c1f76827c7d

**Comment by ArekChr** [comment] 2023-09-13 09:44
> Set the didConfirm state to true if there is some selected participant.

@bernhardoj Where exactly do you suggest this change?

**Comment by ArekChr** [comment] 2023-09-14 08:38
I think we should put this issue on hold until regression with selecting participants will be fixed

**Comment by maddylewis** [comment] 2023-09-14 18:48
@ArekChr - will you link the fix that you're suggesting we hold for?

**Comment by maddylewis** [comment] 2023-09-18 18:20
@ArekChr will you confirm -- was issue #27043 totally fixed by a separate issue (https://github.com/Expensify/App/pull/27350)? 

are we good to close this one out without any further action?

**Comment by ArekChr** [comment] 2023-09-19 08:41
@maddylewis Confirming that issue has been fixed

**Comment by maddylewis** [comment] 2023-09-22 15:26
thank you for confirming!

**Closed by maddylewis** 2023-09-22 15:26 UTC
Labels: External, Daily, Help Wanted, Overdue, Bug
