### ISSUE TITLE
[LOW] [Splits] [$500] Chat - Green line is not present correctly on the first unread system message

### ISSUE THREAD

**Issue by izarutskaya** [Expensify/App#36399] opened 2024-02-13 10:13 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.40-0
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**Issue reported by:** Applause-Internal team

## Action Performed:
1. User A request money from User B
2. User B open chat with user A
3. User A edit the amount, description, merchant and date
4. User B open the detail IOU page

## Expected Result:
New green line should be present above changed amount system message

## Actual Result:
New green line is present above Merchant edit system message

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [x] Android: mWeb Chrome
- [x] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

https://github.com/Expensify/App/assets/115492554/0640fbea-a869-4680-a165-c6953516e34d

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~0117ea985dcf52297d</li>
        <li>Upwork Job ID: 1757347204057006080</li>
        <li>Last Price Increase: 2024-03-22</li>
<li>Automatic offers: </li>
<ul>
<li>ikevin127 | Contributor | 0</li>
</ul></li>
    </ul>
</details>

**Comment by ikevin127** [comment] 2024-02-13 14:36
# Proposal

### Please re-state the problem that we are trying to solve in this issue

New unread system message green line is present above the latest modified expense report action instead of the first unread one.

### What is the root cause of that problem?

New logic introduced by this PR https://github.com/Expensify/App/pull/29314 within a useEffect:

https://github.com/Expensify/App/blob/a3943ace4c70470d38a469ed62ab430c92c0e966/src/pages/home/report/ReportActionsList.js#L401-L404

makes it such that the new unread system message green line is always set above the **latest modified expense report action**, this decision is made by comparing `report.lastReadTime` (parent report) with `reportAction.created` to determine if `isCurrentMessageUnread` within the `shouldDisplayNewMarker` function.

### What changes do you think we should make in order to solve the problem?

Within the useEffect introduced by the mentioned PR we should add the following logic:
- use a util function to get the **first modified expense report action** by comparing `report.lastReadTime` (parent report) date with the `reportAction.created` date (in our case the first action would be -> amount change)
- below in the existing code set `cacheUnreadMarkers.set` and `setCurrentUnreadMarker` to the **first modified expense report action** ID instead of the latest `reportAction.reportActionID` (current implementation)

<details>
<summary>Code changes</summary>

```diff
// add to util functions
function getFirstModifiedExpenseAction(mainReportLastReadTime, reportActions) {
    const mainDate = new Date(mainReportLastReadTime);
    return _.reduce(reportActions, (firstAction, currentAction) => {
        const currentDiff = Math.abs(new Date(currentAction.created) - mainDate);
        const firstDiff = Math.abs(new Date(firstAction.created) - mainDate);
        return currentDiff > firstDiff ? currentAction : firstAction;
    }, reportActions[0]);
}

// within the useEffect:
const firstModifiedExpenseAction = getFirstModifiedExpenseAction(report.lastReadTime, _.filter(sortedVisibleReportActions, ReportActionsUtils.isModifiedExpenseAction));

- cacheUnreadMarkers.set(report.reportID, reportAction.reportActionID));
+ cacheUnreadMarkers.set(report.reportID, _.get(firstModifiedExpenseAction, 'reportActionID', reportAction.reportActionID));
- setCurrentUnreadMarker(reportAction.reportActionID));
+ setCurrentUnreadMarker(_.get(firstModifiedExpenseAction, 'reportActionID', reportAction.reportActionID));
```

</details>

### Videos

<details>
<summary>MacOS: Chrome / Safari</summary>

| Before | After |
| ------------- | ------------- |
| <video src="https://github.com/Expensify/App/assets/56457735/f9d57b4d-819a-4598-a038-ea0c16a846f7"> | <video src="https://github.com/Expensify/App/assets/56457735/aae048c3-4e07-4575-a66c-bd436db65548"> |

</details>

**Comment by abekkala** [comment] 2024-02-15 18:05
@arielgreen added to your project board for vip-split

**Comment by eVoloshchak** [comment] 2024-02-15 20:02
@ikevin127's [proposal](https://github.com/Expensify/App/issues/36399#issuecomment-1941652858) looks good to me!
@ikevin127, when creating the PR, please also include tests from https://github.com/Expensify/App/pull/29314 for us and the QA to test

🎀👀🎀 C+ reviewed!

**Comment by abekkala** [comment] 2024-02-19 19:00
@ikevin127 do you have a PR ready for this one?

**Comment by ikevin127** [comment] 2024-02-19 19:15
@abekkala I have the code ready and can create a PR in 1 hour after assignment 🚀

**Comment by ikevin127** [comment] 2024-02-22 13:16
PR https://github.com/Expensify/App/pull/37082 ready for review! 🚀

> [!note]
> 1. Included testing steps from [#29314](https://github.com/Expensify/App/pull/29314) as well which can also be observed in the PR testing videos.
> 2. **Important:** the new green line doesn't show up on **Simulator** of iOS: Native at all (this happens currently on latest main, without any changes from this PR), not sure why is this, probably something to do with the Simulator internal clock since `isCurrentMessageUnread` always returns `false` even though on all other platforms it returns `true` when it should.
> 3. **To overcome this:** I built the iOS: Native app on a real device in order to record the testing video.
> If you need help with this let me know!

cc @eVoloshchak

**Comment by ikevin127** [comment] 2024-02-29 01:34
## Updated [proposal](https://github.com/Expensify/App/issues/36399#issuecomment-1941652858)
- changed RCA / solution because of [unreliable implementation logic](https://github.com/Expensify/App/pull/37082#issuecomment-1969252347) caught during PR review

The PR is on track w/ new solution applied and we're in the final steps of the reviewing process! 🤓

**Comment by ikevin127** [comment] 2024-03-13 15:41
After thorough testing during PR https://github.com/Expensify/App/pull/37082 by C+ and me, I came to the conclusion that none of my proposed solutions work in actually fixing the issue, also I was not able to find any other solution - I'm out of ideas 🤕

The context here and within the PR can be used by other Contributors which would like to take on the issue.
I closed the PR and ended the Upwork contract. I guess the issue can get back to looking for proposals!

cc @abekkala

**Comment by abekkala** [comment] 2024-03-13 15:51
@cead22 - Do you agree that the selected proposal and PR above will not work as the fix? 

@ikevin127 @eVoloshchak Is there a reason you weren't able to come to a solution for the fix, is it something that you're not able to resolve externally, does this require an internal fix?

**Comment by ikevin127** [comment] 2024-03-13 16:08
I would for sure get some eyes from the BE side to look at this and maybe give some insight as to how the **expected result** functionality should work from a BE point of view when it comes to the report's new unread marker functionality.

More details as to where we encountered problems with the proposed solution and what is happening on the FE side can be found within the closed PR https://github.com/Expensify/App/pull/37082, specifically this https://github.com/Expensify/App/pull/37082#issuecomment-1981437190.

Also somobody that is familiar / worked on the FE side of the report's new unread marker functionality could help big time in foguring this one out.

Considering these unknown variables I tend to think that this being handled internally would have a higher chance of success compared to external contributors for which direct access to this information is more limited.

**Comment by cead22** [comment] 2024-03-14 17:33
Yeah that proposal makes sense, but it seems to use 2 workarounds: the first one to compare the fields that changed, and the second to call OpenReport when we're not opening the report, so I actually think it's good we didn't get that PR merged

I think what we should be doing is updating `lastReadTime` optimistically and pass `lastReadTime` to the api commands that we call from the money request view to update the different fields, eg, UpdateMoneyRequestTag, UpdateMoneyRequestCategory, etc

@marcaaron I think you're pretty familiar with the new messages indicator. If that's the case, what do you think of this approach?

**Comment by marcaaron** [comment] 2024-03-14 18:10
I am not really sure. I would love if someone could upload a video that shows how a REAL user would end up in this situation. 

I am confused by the original bug report. It looks like someone is sharing money with themselves (can you actually do this?) and that the expectation is for "lastReadTime" to be specific to two different clients? It's not. There is just one "lastReadTime".

**Comment by MonilBhavsar** [comment] 2024-03-15 11:40
> Also I think maybe OpenReport should not be marking the report as read anymore? It should be in ReadNewestAction.

Yes correct 👍 
Unless client has updated time than server. It's pretty rare case though and happens when previous ReadNewestAction failed to write to DB

**Comment by MonilBhavsar** [comment] 2024-03-15 12:35
> I am not really sure. I would love if someone could upload a video that shows how a REAL user would end up in this situation.


The video in GH description seems to be correct. It happens when requesting money from another user

---

I think this is very specific to system messages? Do we know the root cause?

**Comment by abekkala** [comment] 2024-03-22 19:10
@joekaufmanexpensify  I'm ooo until April 08 - I'll be taking back any issues still Open once I return

___

### CURRENT STATUS:
Looking for proposals. There is some discussion between @MonilBhavsar  and @marcaaron

**Comment by joekaufmanexpensify** [comment] 2024-03-25 14:12
Sounds good!

**Comment by joekaufmanexpensify** [comment] 2024-03-29 12:57
Sweet. Let's do it!

**Comment by joekaufmanexpensify** [comment] 2024-04-01 14:57
@gedu have you had a chance to look into this yet?

**Comment by gedu** [comment] 2024-04-02 08:01
Hey hey, I was OOO, today I will start looking into it

**Comment by joekaufmanexpensify** [comment] 2024-04-03 13:51
It sounds like then for issue 1, we can do nothing, right? For issue 2, do you mind clarifying how you reproduce that so I can try?

**Comment by gedu** [comment] 2024-04-03 14:17
For issue 1, yes, do nothing.
issue 2: will be doing the same steps but faster. You will see in the next video that all the messages are there already but the green line is placed at the top


https://github.com/Expensify/App/assets/1676818/21075bd2-3f17-46b3-a3ee-153b50e6faa3

**Comment by gedu** [comment] 2024-04-04 13:30
@joekaufmanexpensify could you reproduce it?

**Comment by joekaufmanexpensify** [comment] 2024-04-04 15:11
Is the bug there only because you had the two windows open enabling you to do this more quickly? And if you were doing it in one window, timing wise, it would not happen? 

If so, I'm not convinced it's worth doing anything to change that. It doesn't feel super likely to be that many/anyone will be doing that.

**Comment by gedu** [comment] 2024-04-04 15:57
> Is the bug there only because you had the two windows open enabling you to do this more quickly?
I think yes, I couldn't reproduce it using the app in a normal way

**Comment by abekkala** [comment] 2024-04-08 13:29
Tbanks for handling this one while I was ooo @joekaufmanexpensify 

Closing this one based on above

**Closed by abekkala** 2024-04-08 13:29 UTC
Labels: External, Daily, Overdue, Bug
