### ISSUE TITLE
[Pay meow][$250] Workspace - Workspace type name is not showing in correct column

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#40524] opened 2024-04-19 00:35 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.63-0
**Reproducible in staging?:** Y
**Reproducible in production?:** N
**If this was caught during regression testing, add the test name, ID and link from TestRail:** N/A
**Email or phone of affected tester (no customers):** shussain+test@applausemail.com
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:**
**Slack conversation:**

**Issue found when executing PR** https://github.com/Expensify/App/pull/39991
## Action Performed:
1. Open a workspace join link that we aren't a member of this (workspace from gmail account)
2. Check the workspace type name

## Expected Result:
Workspace type name should not displayed with "requested" lable

## Actual Result:
Workspace type name is not showing in correct column

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [x] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details>  

https://github.com/Expensify/App/assets/78819774/7aa55778-636c-4b22-b53f-7c713f44a488

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01740751b07e243f13</li>
        <li>Upwork Job ID: 1781233221316165632</li>
        <li>Last Price Increase: 2024-04-19</li>
<li>Automatic offers: </li>
<ul>
<li>cubuspl42 | Reviewer | 0</li>
</ul></li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @mallenexpensify</details>

**Comment by lanitochka17** [comment] 2024-04-19 00:36
@marcaaron  FYI I haven't added the External label as I wasn't 100% sure about this issue. Please take a look and add the label if you agree it's a bug and can be handled by external contributors

**Comment by lanitochka17** [comment] 2024-04-19 00:37
We think that this bug might be related to #wave-collect - Release 1

**Comment by marcaaron** [comment] 2024-04-19 01:54
Looks kinda bad so probably should be a blocker?

![2024-04-18_15-51-53](https://github.com/Expensify/App/assets/32969087/3bb333ac-8cd4-4ba4-8464-b788f83089f9)

Got assigned this towards the end of my day and have not investigated yet.

@luacmartins is this related to Simplified Collect?

**Comment by shahinyan11** [comment] 2024-04-19 08:21
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
Workspace - Workspace type name is not showing in correct column
### What is the root cause of that problem?
Wi  do not set `styles.flex1` for  join request rows
### What changes do you think we should make in order to solve the problem?
Remove [!isJoinRequestPending ](https://github.com/Expensify/App/blob/9b2c5187e2203d83bba50bfa66936691788cbd18/src/pages/workspace/WorkspacesListRow.tsx#L184C57-L184C78) from here and add `isJoinRequestPending && styles.justifyContentCenter`

### What alternative solutions did you explore? (Optional)

**Comment by mountiny** [comment] 2024-04-19 08:33
I can take over now to help push it forwards 

The columns should be aligned, I can see that even in the original PR, there is a misalignment on the workspace type column
<img width="805" alt="image" src="https://github.com/Expensify/App/assets/36083550/5a98be10-e254-4ae6-95da-2917ecbff442">

**Comment by mountiny** [comment] 2024-04-19 08:33
@shahinyan11 will your proposal ensure the columns are aligned?

**Comment by mountiny** [comment] 2024-04-19 08:48
@dragnoir Nice! Can you also check how it looks like with a mix of requested and workspaces you are already member of?

**Comment by shahinyan11** [comment] 2024-04-19 08:48
> @shahinyan11 will your proposal ensure the columns are aligned?

No It doesn't look perfect yet, I'm still working on it

**Comment by cubuspl42** [comment] 2024-04-19 10:58
I think that the proposal by @dragnoir is good enough. I understand that the @tienifr built on top of it with some improvements, but I don't think they're significant enough to assign them.

So I'd recommend assigning @dragnoir and focusing on testing all corner cases during the PR testing

C+ reviewed 🎀 👀 🎀

**Comment by mountiny** [comment] 2024-04-19 15:23
Thanks for the review!

@dragnoir can you please raise the PR promptly?

**Comment by mountiny** [comment] 2024-04-22 13:01
$250 to @dragnoir and @allroundexperts once the time comes up.

@dragnoir since this is quite simple PR, could you please also address the follow up from @shawnborton mentioned on the PR to update the style of the three dots padding?

**Comment by mallenexpensify** [comment] 2024-05-03 01:52
Automation failed, payment's due. 
@dragnoir , can you please accept the job and reply here once you have? 
https://www.upwork.com/jobs/~01740751b07e243f13

**Comment by mallenexpensify** [comment] 2024-05-03 17:05
Contributor: @dragnoir paid $250 via Upwork
Contributor+: @allroundexperts owed $250 via NewDot

**Closed by mallenexpensify** 2024-05-03 17:05 UTC
Labels: External, Engineering, Daily, Awaiting Payment, Bug

**Comment by JmillsExpensify** [comment] 2024-06-17 19:50
$250 approved for @allroundexperts
