### ISSUE TITLE
[$250] Chat - Info message appears and disappear when open workspace chat

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#50012] opened 2024-10-01 17:15 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 9.0.42-0
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**If this was caught during regression testing, add the test name, ID and link from TestRail:** N/A
**Email or phone of affected tester (no customers):** gocemate+a2353@gmail.com
**Issue reported by:** Applause - Internal Team

## Action Performed:
1. Create Workspace> Invite few members
2. Go to Inbox
3. Open a workspace chat with member

## Expected Result:
Workspace chat should show the info message "You can also the + button to split the expense..."

## Actual Result:
Info message "You can also the + button to split the expense..." appears and disappear when open workspace chat

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details> 

https://github.com/user-attachments/assets/4110e0ff-c28e-4c8c-89b1-9587e147f10f

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~021841944469734843123</li>
        <li>Upwork Job ID: 1841944469734843123</li>
        <li>Last Price Increase: 2024-10-10</li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @s77rt</details>

**Comment by lanitochka17** [comment] 2024-10-01 17:16
@johncschuster  FYI I haven't added the External label as I wasn't 100% sure about this issue. Please take a look and add the label if you agree it's a bug and can be handled by external contributors

**Comment by koko57** [comment] 2024-10-04 09:46
hey, I'm Agata from Callstack, maybe I can help with this issue?

**Comment by koko57** [comment] 2024-10-04 12:10
Not sure yet what exactly causes that, but after the response from open report we get empty array of moneyRequestOptions

<img width="676" alt="Screenshot 2024-10-04 at 19 01 42" src="https://github.com/user-attachments/assets/7136ccc7-a2d5-4977-8815-da4d123a640a">

-> and as it's empty the text is not displayed because of this condition
https://github.com/Expensify/App/blob/cefe27408ab8d06be3304b4aab3f1b5e352de233/src/components/ReportWelcomeText.tsx#L182

so probably the BE response has changed. But to be 100% sure I need to check getMoneyRequestOptions function if all the conditions are correct.

However for old chats of this type I don't see this problem - the text is displayed

**Comment by s77rt** [comment] 2024-10-05 10:04
@johncschuster Please assign @koko57

**Comment by koko57** [comment] 2024-10-07 13:40
changes were introduced in https://github.com/Expensify/App/pull/49919

**Comment by s77rt** [comment] 2024-10-07 17:02
Asked in PR about the recent change https://github.com/Expensify/App/pull/49919#discussion_r1790584189

**Comment by s77rt** [comment] 2024-10-07 18:16
@johncschuster Let's close this as it's no longer reproducible

**Comment by s77rt** [comment] 2024-10-10 23:59
To be closed cc @johncschuster

**Comment by s77rt** [comment] 2024-10-14 18:45
@johncschuster Let's close this one

**Closed** 2024-10-15 11:10 UTC
Labels: External, Daily, Help Wanted, Bug
