### ISSUE TITLE
[HOLD for payment 2024-06-05] [$250] mWeb - Expense - Url shown in truncated form with dots in merchant field after expense paid

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#41925] opened 2024-05-09 15:35 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.72
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**If this was caught during regression testing, add the test name, ID and link from TestRail:** https://expensify.testrail.io/index.php?/tests/view/4548777
**Issue reported by:** Applause - Internal Team

## Action Performed:
1. Go to https://staging.new.expensify.com/
2. Tap Workspace chat
3. Tap plus icon -- submit expense
4. Enter amount and tap next
5. Paste description with long url eg: https://staging.new.expensify.com/r/575
354256634947/165034783536884819
6. Tap submit
7. Tap submit & pay elsewhere
8. Open the expense and note merchant field

## Expected Result:
Full url user must able to see after expense paid

## Actual Result:
After expense paid, no option to see entire url entered in merchant field. Url can be seen only in truncated form with dots in merchant field and full url cannot be seen after expense paid

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [x] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [ ] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details> 

https://github.com/Expensify/App/assets/78819774/6ded5b15-b1e9-4934-87a3-48ab9d0d0aee

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~017cd1c2d060b6d92c</li>
        <li>Upwork Job ID: 1789744372946083840</li>
        <li>Last Price Increase: 2024-05-12</li>
<li>Automatic offers: </li>
<ul>
<li>Ollyws | Reviewer | 0</li>
<li>bernhardoj | Contributor | 0</li>
</ul></li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @mallenexpensify</details>

**Comment by lanitochka17** [comment] 2024-05-09 15:36
We think that this bug might be related to #vip-vsp

**Comment by lanitochka17** [comment] 2024-05-09 15:36
@mallenexpensify  FYI I haven't added the External label as I wasn't 100% sure about this issue. Please take a look and add the label if you agree it's a bug and can be handled by external contributors

**Comment by bernhardoj** [comment] 2024-05-09 15:57
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
Merchant text in transaction view is only single line and truncated and if it's paid, we can't open the edit merchant page anymore, so it's impossible to see the full text.

### What is the root cause of that problem?
The component used (MenuItem) by default only limited to 1 line.
https://github.com/Expensify/App/blob/807c945ef8edabe86cc62f16c866aa754db8750b/src/components/MenuItem.tsx#L287

So if the text is too long, the text is truncated.

### What changes do you think we should make in order to solve the problem?

Set `numberOfLinesTitle` of merchant to 0 to not limit or any number that the team agrees. Then, we need to set the wrapper style of the menu item of break-word. We can borrow the style from `styles.taskDescriptionMenuItem` that already has the break-word style.
```
wrapperStyle={[styles.taskDescriptionMenuItem]}
```

We use it for description too.
https://github.com/Expensify/App/blob/807c945ef8edabe86cc62f16c866aa754db8750b/src/components/ReportActionItem/MoneyRequestView.tsx#L420-L421

**Comment by mallenexpensify** [comment] 2024-05-09 18:55
@dannymcclain do you have a preference on how this _looks_?   ie. 
1. Use `...` then hyperlink using full link
2. Show full link and hyperlink it all, it. https://staging.new.expensify.com/r/575354256634947/165034783536884819 
3. Something else? 

My preference is #2 because people mind want to copy/paste the link for some reason and/or , if it's sent to accounting software, the hyperlink could be broken or not visible or .. _something_.

**Comment by dannymcclain** [comment] 2024-05-09 19:46
Would we accomplish `#2` by letting the URL wrap onto multiple lines (or any other merchant value for that matter)? 

Basically it would look like the description I've entered here:

![Screenshot 2024-05-09 at 2 43 45 PM](https://github.com/Expensify/App/assets/7516624/e8f7ea23-f592-4a15-ac80-60a27a9ea885)

I'd be fine with that—seems like it's already an established pattern for description so I think it would be fine to extend that to merchant as well.

cc @Expensify/design for viz.

**Comment by dubielzyk-expensify** [comment] 2024-05-10 00:36
Yeah, this seems like a edge case anyways, but I agree that I don't see why we wouldn't have the same behavior for merchant and description. Is it because Merchant is just a single text field and description is a text area which then get our rich markdown editor?

**Comment by mallenexpensify** [comment] 2024-05-12 19:49
> Would we accomplish #2 by letting the URL wrap onto multiple lines (or any other merchant value for that matter)?

Yes, I think wrapping is the best and (maybe/hopefully) easiest option, if we're reusing an existing behaviour/pattern.  Assuming we all agree, @Ollyws , can you review @dragnoir 's proposal above? Thx.

**Comment by bernhardoj** [comment] 2024-05-14 07:23
PR is ready

cc: @Ollyws

**Comment by mallenexpensify** [comment] 2024-06-06 01:04
Contributor: @bernhardoj paid $250 via Upwork
Contributor+: @Ollyws owed $250 via NewDot  

@Ollyws , can you fill out the BZ checklist plz?

Sidenote: the above says `@Ollyws requires payment [automatic offer](https://www.upwork.com/nx/wm/offer/0) (Reviewer)` even though the PR hit production to update them to ND payments.  I found [another instance](https://github.com/Expensify/App/issues/42530#issuecomment-2147593895) where the correct text was added to an issue so I'm hoping/assuming it's working correctly and there was just a delay for some reason.

**Comment by srikarparsi** [comment] 2024-06-10 22:45
@mallenexpensify, are we good to close this out?

**Comment by mallenexpensify** [comment] 2024-06-10 23:08
We are now!  TestRail issue created
- https://github.com/Expensify/Expensify/issues/403644

**Closed by mallenexpensify** 2024-06-10 23:08 UTC
Labels: External, Daily, Design, Overdue, Awaiting Payment, Bug

**Comment by JmillsExpensify** [comment] 2024-06-11 18:25
$250 approved for @Ollyws
