### ISSUE TITLE
[Hold for payment] [$500] DEV: Web - Input focus is not working properly while coming from directly from WS

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#26470] opened 2023-09-01 11:35 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. go to any chat
2. send some messages
3. observe focus is working fine
4. no go to any workspace(create if not have -(Profile setting->workspace))
5. then select three dots which is top most right
6. go to #announce
7. write some text
8. observe the focus

## Expected Result:
Focus is should work properly.

## Actual Result:
Focus is not working properly.

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [x] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** Dev 1.3.61.0
**Reproducible in staging?:** no
**Reproducible in production?:** n/a
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/93399543/e9005a5f-f6a1-456d-a01b-0d2a4e536ab2

**Expensify/Expensify Issue URL:**
**Issue reported by:** @niravkakadiya25
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1693198540165839

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~010c732ec5612bddc7</li>
        <li>Upwork Job ID: 1699143706130157568</li>
        <li>Last Price Increase: 2023-09-05</li>
<li>Automatic offers: </li>
<ul>
<li>niravkakadiya25 | Reporter | 26624150</li>
</ul></li>
    </ul>
</details>

**Comment by slafortune** [comment] 2023-09-05 19:32
applying the external label

**Comment by DylanDylann** [comment] 2023-09-06 06:03
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
- Input focus is not working properly while coming from directly from WS

### What is the root cause of that problem?
- Currently, When opening RHN modal, it will set the isVisible in ONYXKEYS.MODAL to true. Then clicking on the "Go to #announce room" button, will navigate to the chat report screen but does not set the isVisible to false.
- The isVisible used to check if we should run the function ```focus``` like bellow:
https://github.com/Expensify/App/blob/1bdc5acc12f982b4f6e37bfadf9060ac3d2d3b3c/src/pages/home/report/ReportActionCompose/ComposerWithSuggestions.js#L421-L434
- Because the isVisible is always false, the ```focus``` is not run in this case

### What changes do you think we should make in order to solve the problem?
- When clicking on "Go to #announce room" button or other similar buttons, we should set the ```isVisible``` to false using the ```setModalVisibility``` function like below:
```
  const goToRoom = useCallback(
        (type) => {
            setModalVisibility(false);
            const room = _.find(props.reports, (report) => report && report.policyID === policy.id && report.chatType === type && !ReportUtils.isThread(report));
            Navigation.navigate(ROUTES.getReportRoute(room.reportID));
        },
        [props.reports, policy],
    );
```

### What alternative solutions did you explore? (Optional)
- NA

### Result
[Screencast from 06-09-2023 13:01:43.webm](https://github.com/Expensify/App/assets/141406735/91e252b3-04d4-4580-9274-a0ded18462f9)

**Comment by slafortune** [comment] 2023-09-08 17:21
@sobitneupane what do you think of the proposal presented by @DylanDylann ?

Assigning a new BZ member, I am out on sabbatical.

**Comment by DylanDylann** [comment] 2023-09-08 18:24
@slafortune Just updated Proposal https://github.com/Expensify/App/issues/26470#issuecomment-1707723170 - What alternative solutions did you explore? (Optional) section. Please help check. Thanks

**Comment by sobitneupane** [comment] 2023-09-11 10:23
Thanks for the [proposal](https://github.com/Expensify/App/issues/26470#issuecomment-1707723170) @DylanDylann

[Proposal](https://github.com/Expensify/App/issues/26470#issuecomment-1707723170) from @DylanDylann looks good to me.

🎀 👀 🎀 C+ reviewed

**Comment by niravkakadiya25** [comment] 2023-09-12 06:09
offer accepted

**Comment by DylanDylann** [comment] 2023-09-12 13:10
@sobitneupane PR https://github.com/Expensify/App/pull/27219 is ready for review

**Comment by DylanDylann** [comment] 2023-10-19 04:45
@sakluger Could you help to check [this comment](https://github.com/Expensify/App/issues/26470#issuecomment-1750485083)?

**Comment by sakluger** [comment] 2023-10-23 20:14
Sorry, yes. I think in this case, since the PR was fully written and approved, we can payout the full $500.

I've sent offers to @DylanDylann and @sobitneupane, please let me know once you've accepted. Thanks!

**Comment by DylanDylann** [comment] 2023-10-24 13:05
@sakluger Thanks, accepted

**Comment by sobitneupane** [comment] 2023-10-30 08:05
@sakluger Accepted the offer.

**Comment by DylanDylann** [comment] 2023-11-15 04:41
@sakluger Could you help to move forward this issue?

**Comment by sakluger** [comment] 2023-12-12 08:29
Sorry for the long wait everyone, I usually rely on issues getting the "Hold for payment" added to the title and then moved back to daily when it's ready for payment - I should have made those changes when I sent the offer.

**Comment by sakluger** [comment] 2023-12-12 08:30
I've paid out @DylanDylann via Upwork. @sobitneupane I canceled your Upwork contract so you can request through NewDot (summary below). Please comment when it's okay for me to close the issue.

**Summarizing payouts for this issue:**

Contributor: @DylanDylann $500 (paid via Upwork)
Contributor+: @sobitneupane $500 (payable via Manual Request)

**Comment by sobitneupane** [comment] 2023-12-15 09:47
https://github.com/Expensify/App/issues/26470#issuecomment-1851524695

Requested payment on newDot.

**Comment by JmillsExpensify** [comment] 2023-12-15 23:13
$500 payment approved for @sobitneupane based on summary above.

**Comment by Beamanator** [comment] 2023-12-22 15:26
I guess we can close this now, right?

**Comment by sakluger** [comment] 2023-12-23 07:19
Yep! Thanks everyone.

**Closed by sakluger** 2023-12-23 07:19 UTC
Labels: Reviewing, External, Daily, Bug

**Comment by niravkakadiya25** [comment] 2024-04-06 09:36
Hello @sakluger @Beamanator 
I have not received my reporting bonus in upwork. Can you please check on this?
