### ISSUE TITLE
Chat - Composer flickers when using header markdown

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#39258] opened 2024-03-29 16:32 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.58-0
**Reproducible in staging?:** Y
**Reproducible in production?:** N
**If this was caught during regression testing, add the test name, ID and link from TestRail:** N/A
**Issue reported by:** Applause - Internal Team

## Action Performed:
1. Open a chat
2. Start typing # followed by any letter (Preferebly upper case letter)

## Expected Result:
Composer should not flicker

## Actual Result:
Composer flickers for a second while typing the letter followed by #

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details> 

https://github.com/Expensify/App/assets/78819774/00061c4f-1f22-4764-953d-95f048432916

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by lanitochka17** [comment] 2024-03-29 16:32
@pecanoro  FYI I haven't added the External label as I wasn't 100% sure about this issue. Please take a look and add the label if you agree it's a bug and can be handled by external contributors

**Comment by thienlnam** [comment] 2024-03-29 18:18
Not a blocker, added to the main tracking issue

**Comment by pecanoro** [comment] 2024-04-01 14:22
@thienlnam Even if not a deploy blocker, who is fixing this anyhow? And why unassigning me?

**Comment by thienlnam** [comment] 2024-04-02 16:41
SWM is fixing these in order of priority of the tracking issue - I unassigned since this came from the live-markdown PR we just merged and since this is lower on the priority list it might be a while until we get to this

**Comment by pecanoro** [comment] 2024-04-16 10:06
Still no update, agency is working on higher priority issues for markdown

**Comment by pecanoro** [comment] 2024-04-25 10:36
Still no update, agency is working on higher priority issues for markdown

**Comment by pecanoro** [comment] 2024-05-06 10:17
Still no update, agency is working on higher priority issues for markdown

**Comment by thienlnam** [comment] 2024-05-06 20:02
@BartoszGrajdek Do you think you could add this one to your list?

**Comment by BartoszGrajdek** [comment] 2024-05-07 11:44
I believe @Skalakid was working on this 👀

**Comment by BartoszGrajdek** [comment] 2024-05-07 11:45
But I can't reproduce it anymore, are you sure this bug is still happening? @thienlnam

**Comment by pecanoro** [comment] 2024-05-08 08:24
Same, closing!

**Closed by pecanoro** 2024-05-08 08:24 UTC
Labels: Engineering, Weekly

**Comment by Skalakid** [comment] 2024-05-09 07:20
I've already fixed that in https://github.com/Expensify/App/pull/40128 in similar issue
