### ISSUE TITLE
 When pressing send the send button gets deactivates, then activated, and finally deactivated causing a flashing

### ISSUE THREAD

**Issue by m-natarajan** [Expensify/App#46328] opened 2024-07-26 20:12 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 9.0.13-3
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** @hannojg 
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1721898827637189

## Action Performed:
1. Launch the app
2. Initiate a DM to any user 
3. Compose message and tap `Send` button

## Expected Result:
Message send without any issues
## Actual Result:
When pressing send the send button gets deactivates, then activated, and finally deactivated causing a flashing
## Workaround:
Unknown
## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [x] iOS: Native
- [ ] iOS: mWeb Safari
- [ ] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

https://github.com/user-attachments/assets/43d1c752-933f-41e8-af8f-a90b30855884

https://github.com/user-attachments/assets/c7f835a7-2737-47d2-90ab-4f7b9dc8b15b

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by hannojg** [comment] 2024-07-29 06:53
I reported this bug while working on the composer in this issue:

- https://github.com/Expensify/App/issues/37896

I am Hanno from Margelo, an expert agency, and I'd like to work on this issue (feel free to assign me) 😊

**Comment by zanyrenney** [comment] 2024-07-29 13:43
thanks @hannojg

**Comment by hannojg** [comment] 2024-07-31 12:44
Thank you, I was waiting for this composer PR to get merged first:

- https://github.com/Expensify/App/pull/46091

now that its merged I will look into that issue today and provide updates along the way! 😊

**Comment by zanyrenney** [comment] 2024-08-01 11:07
Let me try and test quickly.

**Comment by zanyrenney** [comment] 2024-08-01 11:12
Also can't reproduce so probably yes fixed with your latest PR @hannojg - nice! Thank you!

**Closed by zanyrenney** 2024-08-01 11:12 UTC
Labels: Daily, Internal, Bug
