### ISSUE TITLE
[HOLD for payment 2024-04-09] [$500] Login – Login mode is broken when open public room as anon user, start sign in and reload page

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#38059] opened 2024-03-11 16:14 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.50-2
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**If this was caught during regression testing, add the test name, ID and link from TestRail:** https://expensify.testrail.io/index.php?/tests/view/4412979
**Issue reported by:** Applause - Internal Team

## Action Performed:
1. Go to https://staging.new.expensify.com/
2. Log out
3. Navigate via link as public room anon user (room link https://staging.new.expensify.com/r/8661824749067368
)
4. Click on Signin
5. Enter an email and Continue
6. Reload page some times

## Expected Result:
Login page refreshes/loads normally

## Actual Result:
Login page doesn't fully load and is broken

<img width="1727" alt="image" src="https://github.com/Expensify/App/assets/51066321/e731bca7-88c5-4445-9215-bc8c9bd60fcf">

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details> 

https://github.com/Expensify/App/assets/78819774/c13ca964-7b71-4abe-a65f-f018b5f2ea7b

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01a1d4033f00182021</li>
        <li>Upwork Job ID: 1767362783828492288</li>
        <li>Last Price Increase: 2024-03-19</li>
<li>Automatic offers: </li>
<ul>
<li>situchan | Reviewer | 0</li>
<li>tienifr | Contributor | 0</li>
</ul></li>
    </ul>
</details>

**Comment by lanitochka17** [comment] 2024-03-11 16:15
@Christinadobrzyn  FYI I haven't added the External label as I wasn't 100% sure about this issue. Please take a look and add the label if you agree it's a bug and can be handled by external contributors

**Comment by Christinadobrzyn** [comment] 2024-03-12 01:31
I believe this can be external - we'll have an engineer check and I think this can be part of wave-collect (to alleviate all of the BZ GHs in vip-vsb).

**Comment by Dansatch** [comment] 2024-03-12 06:40
### Title: Visual Breakage of Login Modal Upon Multiple Reloads

**Issue Summary:**
Our React application features a login modal that breaks visually when reloaded multiple times.

**Steps to Reproduce:**
Navigate to the login page.
Reload the login page modal multiple times.
Observe the visual glitches or breakage in the modal's appearance.

**Expected Behavior:**
The login modal should maintain its visual integrity and functionality regardless of the number of reloads.

**Actual Behavior:**
Upon multiple reloads, the login page modal exhibits visual glitches or breakage, rendering it unusable.

**Proposed Solution:**
1. Conduct a thorough code review to identify any potential issues or patterns related to 
- [ ] State management, 
- [ ] Component lifecycle methods,
- [ ] CSS styling,
- [ ] event handling,
- [ ] memory leaks,
- [ ] third-party library integration.

2. Implement fixes or optimizations as needed to address the root cause of the visual breakage in the login modal.
3. Test the proposed solution rigorously across different browsers and environments to ensure its effectiveness and compatibility.
4. Document the changes made and update relevant documentation or comments in the codebase for future reference.

**Additional Information:**
- We have observed this issue consistently across different browsers and environments, indicating that it is not specific to a particular setup.
- We have observed the number of reloads before breakage is variable.
- We have observed the breakage doesn't occur on mobile screens.

**Comment by Dansatch** [comment] 2024-03-12 06:47
Contributor details
Your Expensify account email: dansatch98@gmail.com
Upwork Profile Link: https://www.upwork.com/freelancers/~016d739b03ec228c37

**Comment by shahinyan11** [comment] 2024-03-12 09:31
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
Login – Login mode is broken when open public room as anon user, start sign in and reload page
### What is the root cause of that problem?
The [izIModal](https://github.com/Expensify/App/blob/da7697734c1f759786eba0a643a062b4e39a47ad/src/hooks/useResponsiveLayout.ts#L18C11-L18C20) will be incorrect every time this code is run before the navigation is ready.  And for this reason [shouldUseNarrowLayout](https://github.com/Expensify/App/blob/da7697734c1f759786eba0a643a062b4e39a47ad/src/hooks/useResponsiveLayout.ts#L19C11-L19C32) will sometimes be incorrect which causes the UI to break.
### What changes do you think we should make in order to solve the problem?
1. Add new function in [Navigation.ts](https://github.com/Expensify/App/blob/da7697734c1f759786eba0a643a062b4e39a47ad/src/libs/Navigation/Navigation.ts#L349) which receive current route name and check if this name exists in [here](https://github.com/Expensify/App/blob/da7697734c1f759786eba0a643a062b4e39a47ad/src/libs/Navigation/linkingConfig/config.ts#L84) or [here](https://github.com/Expensify/App/blob/da7697734c1f759786eba0a643a062b4e39a47ad/src/libs/Navigation/linkingConfig/config.ts#L100)
```
function isInModal (routeName: string){
    function findRoute(obj, keyToCheck: string) {
        if (obj && typeof obj === 'object') {
            if (keyToCheck in obj) {
                return true;
            }

            for (const prop in obj) {
                if (obj.hasOwnProperty(prop) && findRoute(obj[prop], keyToCheck)) {
                    return true;
                }
            }
        }

        return false;
    }


    const isInLeftModal = findRoute(config?.screens[NAVIGATORS.LEFT_MODAL_NAVIGATOR], routeName)
    const isInRightModal = findRoute(config?.screens[NAVIGATORS.RIGHT_MODAL_NAVIGATOR], routeName)

    return isInLeftModal || isInRightModal
}
```
2. Replace these [lines](https://github.com/Expensify/App/blob/da7697734c1f759786eba0a643a062b4e39a47ad/src/hooks/useResponsiveLayout.ts#L15C1-L18C127) with the code below.
```
const routeName = useRoute().name
const isInModal = Navigation.isInModal(routeName)
```

### What alternative solutions did you explore? (Optional)

**Comment by trjExpensify** [comment] 2024-03-12 12:25
>and I think this can be part of wave-collect (to alleviate all of the BZ GHs in vip-vsb).

@Christinadobrzyn public rooms isn't a focus of #wave-collect, so please add this one to vip-vsb!

**Comment by Christinadobrzyn** [comment] 2024-03-13 02:03
Ah thanks for the review @trjExpensify  - moved to vip-vsb. 

@situchan we have some proposals if you have a chance to review!

**Comment by situchan** [comment] 2024-03-15 21:01
Reviewing proposals

**Comment by situchan** [comment] 2024-03-18 21:24
Not overdue

**Comment by Christinadobrzyn** [comment] 2024-03-20 06:21
Thanks @situchan!

**Comment by Christinadobrzyn** [comment] 2024-03-22 04:22
Let us know if any of the proposals look good @situchan!

**Comment by situchan** [comment] 2024-03-22 07:56
@tienifr @shahinyan11 thanks for the proposals.
The root cause is correct.
While both proposed working solution, I prefer @tienifr's [proposal (main solution)](https://github.com/Expensify/App/issues/38059#issuecomment-1989852137) since it fixes the root cause.
🎀 👀 🎀 C+ reviewed

**Comment by situchan** [comment] 2024-03-22 07:58
I am also open to thoughts from navigation experts.
cc: @adamgrzybowski

**Comment by adamgrzybowski** [comment] 2024-03-22 14:06
@situchan @tienifr's proposal makes sense to me

**Comment by arosiclair** [comment] 2024-03-25 14:09
Waiting on @tienifr's PR

**Comment by Christinadobrzyn** [comment] 2024-04-02 09:25
Awesome! Thank you @tienifr! cc @situchan https://github.com/Expensify/App/issues/38059#issuecomment-2018303942

**Comment by Christinadobrzyn** [comment] 2024-04-08 06:23
Payouts due: 

- [ ] Contributor: $500 @tienifr (Upwork offer here - https://www.upwork.com/nx/wm/workroom/36752604/overview)
- [ ] Contributor+: $X @situchan (Upwork offer here - https://www.upwork.com/nx/wm/workroom/36830224/overview)

Upwork job is [here](https://www.upwork.com/jobs/~01a1d4033f00182021)

@tienifr / @situchan Do we need a regression test?

**Comment by Christinadobrzyn** [comment] 2024-04-11 02:49
nudged @tienifr in slack about the regression test

**Comment by Christinadobrzyn** [comment] 2024-04-11 02:58
Sorry the regression test needs to come from @situchan since they are the C+. Reaching out to them! Sorry @tienifr!

**Comment by Christinadobrzyn** [comment] 2024-04-15 08:28
waiting on a regression test - gonna move this to weekly since @situchan is ooo at the moment.

**Comment by Christinadobrzyn** [comment] 2024-04-24 07:54
holding for @situchan

**Comment by Christinadobrzyn** [comment] 2024-05-03 03:47
DMs @situchan to see if they are back.

**Comment by Christinadobrzyn** [comment] 2024-05-08 09:01
I'm just going to create a regression test based on the steps in the PR so we can close this. 

regression test -https://github.com/Expensify/Expensify/issues/394191

Closing!

**Closed by Christinadobrzyn** 2024-05-08 09:01 UTC
Labels: External, Weekly, Awaiting Payment, Bug
