### ISSUE TITLE
[$500] Expensify comment to enter the details for the deleted expense request

### ISSUE THREAD

**Issue by m-natarajan** [Expensify/App#35861] opened 2024-02-06 00:54 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.36-5
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** @danieldoglas 
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1707168112041529

## Action Performed:
1. smartscan invalid receipts and wait for to fail
2. Delete th requests

## Expected Result:
No message saying that Receipt scanning failed. Enter the details manually.
## Actual Result:
hey now had a comment from Expensify saying that Receipt scanning failed. Enter the details manually. . Because of those comments, the expense policy chat is now always showing as a GBR, when it shouldn't show anything since I can't act on it.
## Workaround:
unknown
## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence
![image (4)](https://github.com/Expensify/App/assets/38435837/7fbec19c-3b09-4f56-9c78-088ab07917ed)
![image (3)](https://github.com/Expensify/App/assets/38435837/299e5dac-9bc3-4ddc-8397-bee954321690)
![image (2)](https://github.com/Expensify/App/assets/38435837/30a655d5-646a-4fbb-8604-a13c9331830a)
![image (1)](https://github.com/Expensify/App/assets/38435837/db90e39a-6db4-49ad-b052-c0afb2b79e83)

https://github.com/Expensify/App/assets/38435837/203bc721-8ab8-4650-8b02-c7cc9f729e6c

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~018bc064bf2f244ac3</li>
        <li>Upwork Job ID: 1754669805080993792</li>
        <li>Last Price Increase: 2024-02-27</li>
    </ul>
</details>

**Comment by CortneyOfstad** [comment] 2024-02-08 16:41
@abdulrahuman5196 thoughts on the proposal above?

**Comment by abdulrahuman5196** [comment] 2024-02-08 19:59
Hi, Will review the proposal in my morning

**Comment by abdulrahuman5196** [comment] 2024-02-09 15:03
Reviewing now

**Comment by abdulrahuman5196** [comment] 2024-02-09 15:40
@CortneyOfstad Could you kindly confirm the expectation here?

Should we not show the failure message or not show the whole request itself? I am not sure what we should expect here.

**Comment by CortneyOfstad** [comment] 2024-02-09 16:03
@danieldoglas since you reported the issue, I would love your input here. I'm leaning towards not showing the whole request, but wondered if you had a preference. Thanks!

**Comment by danieldoglas** [comment] 2024-02-09 16:36
We should dismiss the GBR or RBR if we cancel the request. There's nothing else to do there, so it doesn't make sense to keep it alerting.

**Comment by CortneyOfstad** [comment] 2024-02-09 16:53
Sounds good @danieldoglas! Does that make sense for you @abdulrahuman5196?

**Comment by CortneyOfstad** [comment] 2024-02-12 14:51
Bump @abdulrahuman5196 ^^^

**Comment by CortneyOfstad** [comment] 2024-02-14 15:23
Bump @abdulrahuman5196 on the comment [here](https://github.com/Expensify/App/issues/35861#issuecomment-1936240514)  — thanks!

**Comment by abdulrahuman5196** [comment] 2024-02-14 18:40
Hi, @CortneyOfstad  sorry for the delay. Will check on the review in my morning.

**Comment by abdulrahuman5196** [comment] 2024-02-15 18:27
Reviewing now

**Comment by abdulrahuman5196** [comment] 2024-02-15 19:13
This is the expected from @danieldoglas comment

>We should dismiss the GBR or RBR if we cancel the request. There's nothing else to do there, so it doesn't make sense to keep it alerting.


@dukenv0307 proposal targets to delete the request in case of it only having expensify notifications. But the expectation here is to not show the green indicator alone. So the proposal is invalid at this point.


@danieldoglas Do correct me if misunderstood the proposal in any way.

**Comment by abdulrahuman5196** [comment] 2024-02-19 09:07
No new proposals to review.

**Comment by danieldoglas** [comment] 2024-02-19 11:29
The problem with deleting everything is in case we have messages that are not related. Let's say for example that you add a comment in a money request, then delete the money request. The comment will still be there, and we need to show it as available. 

What's happening here is that we're not removing the GBG or RBR if we delete the money request. 

> We already do the same (remove the request completely)

Those are different types of reportActions though - we can't delete those messages specifically because they're not currently considered system messages.

**Comment by CortneyOfstad** [comment] 2024-02-21 16:01
@danieldoglas Just checking to see if you had a follow-up to @dukenv0307's comment [here](https://github.com/Expensify/App/issues/35861#issuecomment-1952905230)?

I agree with @dukenv0307's line of thinking that if there is a comment, the request should remain (or at least a message indicating the request was deleted/removed), but interested to hear your thoughts! Thanks!

**Comment by danieldoglas** [comment] 2024-02-21 18:28
Ok, I agree with that as well. Thanks @dukenv0307

**Comment by abdulrahuman5196** [comment] 2024-02-22 14:26
One edge I see here, currently as of this issue only expensify notification comment is Receipt scan failed notification. But what if in future we started having different kind of expensify notification itself and we don't want to delete the request even if it had those notification(for eg: like some bank related notification from coincerge, just think out load)

Is there a property to just say if the expensify notification comment is the Receipt scan failed one? and we can only delete the report if only had the specific expensify notification comments like receipt failed?
@dukenv0307

**Comment by abdulrahuman5196** [comment] 2024-02-26 12:06
> Ok, I agree with that as well. Thanks @dukenv0307

Hi @danieldoglas , Wanted to confirm again, since the last decision seems to have changed.

With the recent discussion we are fine with proceeding in the expectation mentioned by @dukenv0307 - https://github.com/Expensify/App/issues/35861#issuecomment-1928662194, that is to `delete the request if we only have expensify notification messages.`

I think the proposal is technically reasonable, so if we confirm on the above, I can go ahead with the next steps.

**Comment by danieldoglas** [comment] 2024-02-27 13:39
I agree with that, let's move forward

**Comment by CortneyOfstad** [comment] 2024-02-28 15:39
@abdulrahuman5196 to confirm, are we moving forward with @dukenv0307's proposal? Thanks!

**Comment by CortneyOfstad** [comment] 2024-02-29 15:17
@abdulrahuman5196 bump on the above and if so, we should have @dukenv0307 restate their proposal with any feedback implemented 👍

**Comment by abdulrahuman5196** [comment] 2024-02-29 15:18
Hi, @CortneyOfstad Will check and update today

**Comment by CortneyOfstad** [comment] 2024-02-29 15:42
Thank you!

**Comment by CortneyOfstad** [comment] 2024-02-29 20:01
Hi @sonialiap! I am heading OoO and will be back March 11th, so reassigned to have someone keep this moving until I am back. At this stage, we're waiting for @abdulrahuman5196 to review the proposal of @dukenv0307 to see if it needs to be restated with the feedback provided. Thanks!

**Comment by abdulrahuman5196** [comment] 2024-03-01 11:03
@dukenv0307 I was trying out the proposal here https://github.com/Expensify/App/issues/35861#issuecomment-1928662194

Just updating here https://github.com/Expensify/App/blob/d7f87c5663096798e5bb959a713aa209215d39a8/src/libs/actions/IOU.ts#L2579 doesn't actually delete the request.

And even after i tweaked the code and delete the request, the green indicator is not removed.

<img width="1512" alt="Screenshot 2024-03-01 at 4 30 20 PM" src="https://github.com/Expensify/App/assets/46707890/096b7530-31cc-4e92-9304-ed06fa1f0f4e">

**Comment by abdulrahuman5196** [comment] 2024-03-04 09:17
@dukenv0307 Bump on the above

**Comment by sonialiap** [comment] 2024-03-07 11:48
@abdulrahuman5196 bumping [Duke's question](https://github.com/Expensify/App/issues/35861#issuecomment-1979184141) :)

**Comment by sonialiap** [comment] 2024-03-11 12:35
@abdulrahuman5196 bumping!

**Comment by sonialiap** [comment] 2024-03-11 12:35
Cortney, you're back today so I'm unassigning myself

**Comment by CortneyOfstad** [comment] 2024-03-11 17:22
Thanks @sonialiap! 

@abdulrahuman5196 can you please provide an update by EOD on where we're at with [this](https://github.com/Expensify/App/issues/35861#issuecomment-1983344035)? Thanks!

**Comment by abdulrahuman5196** [comment] 2024-03-11 17:25
Hi, I have to provide video on my claim that the proposal was not working. Will check on it in my morning

**Comment by CortneyOfstad** [comment] 2024-03-13 16:40
@dukenv0307 bump on the comment above ^^^ Can you follow up by EOD? Thanks!

**Comment by CortneyOfstad** [comment] 2024-03-14 15:12
Thanks @dukenv0307!

**Comment by CortneyOfstad** [comment] 2024-03-15 14:39
@abdulrahuman5196 any thoughts on the update [here](https://github.com/Expensify/App/issues/35861#issuecomment-1995037949)? Thanks!

**Comment by abdulrahuman5196** [comment] 2024-03-15 14:46
> Sure thing CortneyOfstad 
> 
> > It removes the green indicator for while, but it comes back. If you have any specific code I have to try out, do share the same with me.
> 
> @abdulrahuman5196 Here's the [test branch](https://github.com/dukenv0307/App/tree/fix/35861). It works fine for me.
> 
> > It removes the green indicator for while, but it comes back.
> 
> I was able to reproduce now this with a scan in a workspace, this is because we didn't make the change in back-end so it sends back Pusher data with `hasOutstandingChildRequest: true`. Once we made the adjustment in the back-end, the green dot will no longer show.
> 
> > We might want to fix the back-end to follow the same logic too.


Got @dukenv0307 . I suspected backend since it came after a while. 

What do you think @danieldoglas ?
I think we might also need backend changes. If possible can we confirm on backend changes. 
Or we can proceed to make frontend changes and have a follow-up on backend changes?

**Comment by CortneyOfstad** [comment] 2024-03-18 14:53
> What do you think @danieldoglas ?
> I think we might also need backend changes. If possible can we confirm on backend changes.
> Or we can proceed to make frontend changes and have a follow-up on backend changes?

@danieldoglas do you agree with this strictly being BE or do you think they can make the FE changes for now to keep this rolling? This issue is low-priority, but I am in the camp of keeping this moving wherever possible. 

My only concern with doing the FE pieces now is the potential of creating more work on the BE side later. Do you see that happening, or is that not the case? Thanks!

**Comment by CortneyOfstad** [comment] 2024-03-22 13:45
@danieldoglas bump on the above ^^^ TIA!

**Comment by CortneyOfstad** [comment] 2024-03-25 14:12
Bump @danieldoglas ^^^ Thanks!

**Comment by danieldoglas** [comment] 2024-03-25 14:32
my bad, started a conversation here: https://expensify.slack.com/archives/C03TQ48KC/p1711377098976279

**Comment by CortneyOfstad** [comment] 2024-04-01 14:00
@danieldoglas any update? From what I could gather on the chat thread, it appears that we want to remove the violation as a message, but wanted to hear your thoughts on the best plan forward 👍

**Comment by danieldoglas** [comment] 2024-04-02 09:31
working on the PRs to work on this internally!

**Comment by CortneyOfstad** [comment] 2024-04-03 14:50
Sorry @dukenv0307 — there is a PR request ([here](https://github.com/Expensify/Auth/pull/10342)) to remove the message 👍

**Comment by danieldoglas** [comment] 2024-04-04 06:38
@dukenv0307 - Since we now have violations, the comment for smartscan failed won't be added anymore. So if you delete the request, since it won't have any comments, this will work automatically.

**Comment by mvtglobally** [comment] 2024-04-18 16:06
Issue not reproducible during KI retests. (First week)

**Comment by danieldoglas** [comment] 2024-04-18 22:12
Great, closing this!

**Closed by danieldoglas** 2024-04-18 22:12 UTC
Labels: Reviewing, Engineering, Weekly, Internal, Bug, retest-weekly
