### ISSUE TITLE
[$250] Chat - Unable to send manually copied and pasted code block and compose box not expanded

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#40033] opened 2024-04-10 19:37 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.62-0
**Reproducible in staging?:** Y
**Reproducible in production?:** N
**If this was caught during regression testing, add the test name, ID and link from TestRail:** https://expensify.testrail.io/index.php?/tests/view/4486095
**Issue reported by:** Applause - Internal Team

## Action Performed:
1. Log in to New Expensify
2. Navigate to any chat
3. Send a message with code block
4. Highlight the code block and manually copy it by ctrl + c
5. Paste the copied message in compose box

## Expected Result:
The message should be correctly pasted, the compose should be expanded to show entire message and the Send button should be enabled

## Actual Result:
The Send button is disabled after pasting manually copied code block, and the compose box is not auto enlarged to show whole message

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details>  

https://github.com/Expensify/App/assets/78819774/5b0fc765-085d-4e87-ae5e-31c25aa7e16d

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01fcf3941c43468e44</li>
        <li>Upwork Job ID: 1779707520000811008</li>
        <li>Last Price Increase: 2024-08-21</li>
    </ul>
</details>

**Comment by lanitochka17** [comment] 2024-04-10 19:38
@greg-schroeder  FYI I haven't added the External label as I wasn't 100% sure about this issue. Please take a look and add the label if you agree it's a bug and can be handled by external contributors

**Comment by lanitochka17** [comment] 2024-04-10 19:38
We think that this bug might be related to #vip-vsp

**Comment by greg-schroeder** [comment] 2024-04-15 03:04
Hmmm.

**Comment by roitman-g** [comment] 2024-04-15 14:56
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
Whenever the user pastes a copied code block in the chat input box the cursor is in the beginning and the box is not expanded. This happens every time the user pastes anything with the new line in the end, so if you were to triple click something copy and paste, the same issue would appear.

### What is the root cause of that problem?
The root problem is that in "insertAtCaret" function in useHTMLPaste hook the selection range start and end index is determined incorrectly in cases there is a new line in the end of the insertion. 

### What changes do you think we should make in order to solve the problem?
I suggest using document.execCommand('insertHTML', false, text); instead of insertAtCaret. Method execCommand is being deprecated, however it is already being used in insertByCommand function as well as "copy" functionality and it does not seem like there is a [valid alternative right now](https://stackoverflow.com/questions/60581285/execcommand-is-now-obsolete-whats-the-alternative).

### What alternative solutions did you explore? (Optional)
N/A

**Comment by giorgi17** [comment] 2024-04-15 15:07
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
After copying the code that was already sent in the chat, the input doesn't expand and it's not being sent.


### What is the root cause of that problem?
The issue was in the library logic being used - `node_modules/@expensify/react-native-live-markdown/lib/module/web/cursorUtils.js`. This caused an error in the terminal as well. The logic for positioning the caret was flawed in case of code copy.

### What changes do you think we should make in order to solve the problem?
Correct that logic inside the library, I'm guessing it's your library, that's where I changed it too.
Here's the footage of finished and fixed issue: [Footage](https://nimb.ws/5T4sOWt)

### What alternative solutions did you explore? (Optional)
You could manipulate the input being set there, but I think it's better to change the logic inside the library, so that it'll work on any such case in the future. Only adjusting it for the code input would not be a great idea as we don't know what other problems the issue inside the library will cause in the future with other types of inputs.

**Comment by brkdavis** [comment] 2024-04-15 18:58
## Proposal

Issue looks to be duplicate or same root cause of the linked ones above.
Detailed proposal linked here.
 
https://github.com/Expensify/App/issues/39971#issuecomment-2053860349

**Comment by eh2077** [comment] 2024-04-16 15:26
@brkdavis Thanks for your input! Yeah, they may share same root cause.

@greg-schroeder I think we can put this on hold for https://github.com/Expensify/App/issues/39971

**Comment by eh2077** [comment] 2024-04-19 00:35
> @greg-schroeder I think we can put this on hold for #39971

@greg-schroeder Friendly bump!

**Comment by giorgi17** [comment] 2024-04-22 16:03
> 📣 It's been a week! Do we have any satisfactory proposals yet? Do we need to adjust the bounty for this issue? 💸

Yes, you do. [Here](https://github.com/Expensify/App/issues/40033#issuecomment-2057090708), but nobody notices it. Even got the video footage of it working. No need to adjust the bounty.

**Comment by eh2077** [comment] 2024-04-22 16:11
> @greg-schroeder I think we can put this on hold for https://github.com/Expensify/App/issues/39971

Not overdue, same^ 
cc @greg-schroeder

**Comment by greg-schroeder** [comment] 2024-04-24 20:48
Putting on hold, sorry

**Comment by greg-schroeder** [comment] 2024-05-01 22:06
Held

**Comment by greg-schroeder** [comment] 2024-05-09 05:36
Same as above

**Comment by greg-schroeder** [comment] 2024-05-13 12:21
""

**Comment by greg-schroeder** [comment] 2024-05-15 22:35
""

**Comment by greg-schroeder** [comment] 2024-05-22 00:20
[#399971](https://github.com/Expensify/App/issues/39971) this is still held

**Comment by greg-schroeder** [comment] 2024-05-31 07:48
Held

**Comment by greg-schroeder** [comment] 2024-06-11 01:50
This remains held

**Comment by eh2077** [comment] 2024-06-20 02:13
still on hold

**Comment by BartoszGrajdek** [comment] 2024-06-25 10:08
@thienlnam can we add it to live markdown project? 🙏🏻

**Comment by greg-schroeder** [comment] 2024-06-28 09:23
Held

**Comment by greg-schroeder** [comment] 2024-07-08 12:41
Held

**Comment by greg-schroeder** [comment] 2024-07-16 21:42
Held

**Comment by greg-schroeder** [comment] 2024-07-25 10:50
Held

**Comment by greg-schroeder** [comment] 2024-08-05 13:48
Same

**Comment by greg-schroeder** [comment] 2024-08-14 10:27
#39971 is merged/deployed

**Comment by eh2077** [comment] 2024-08-21 16:04
@greg-schroeder Should we ask QA for a re-test to see if this issue is still reproducible?

**Comment by mvtglobally** [comment] 2024-08-23 12:06
Issue not reproducible during KI retests. (First week)

**Comment by greg-schroeder** [comment] 2024-08-27 05:24
Seems we're not able to reproduce now, so #39971 likely did actually fix this. Closing for now, but please reopen if you disagree.

**Closed by greg-schroeder** 2024-08-27 05:24 UTC
Labels: External, Weekly, Help Wanted, Bug
