### ISSUE TITLE
[HOLD for payment 2024-07-26] [Free trial] Update/Remove the Free banner when a payment card is added during a trial or after a trial has ended

### ISSUE THREAD

**Issue by MitchExpensify** [Expensify/App#45503] opened 2024-07-16 17:19 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** v9.0.7-4
**Reproducible in staging?:** yes
**Reproducible in production?:** 
**If this was caught during regression testing, add the test name, ID and link from TestRail:** 
**Email or phone of affected tester (no customers):** wardmi@tcd.ie
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** @MitchExpensify 
**Slack conversation:** Internal: https://expensify.slack.com/archives/C036QM0SLJK/p1721148411167389

## Action Performed:

**Adding a payment card after the free trial has ended:**
1. Add a payment card on an account that has ended its trial
2. Go to https://staging.new.expensify.com/settings/subscription

**Adding a payment card during a free trial:** 
1. Create a workspace on a new account
2. Go to https://staging.new.expensify.com/settings/subscription

## Expected Result:

**Adding a payment card after the free trial has ended:**
- The free trial banner should be completely removed.

<img width="898" alt="image" src="https://github.com/user-attachments/assets/de68f879-8ce0-49e1-92af-a3667726f333">

**Adding a card during a free trial:** 
- Remove the subtitle in the banner
- Make sure the copy under “Payment” is updated to the one used when a payment card is on file. 

<img width="802" alt="image" src="https://github.com/user-attachments/assets/39b5a09a-6a81-41bc-9921-e9b77d1cabd9">

## Actual Result:

**Adding a payment card after the free trial has ended:**
- There is a free banner with "add payment card" prompt showing to users who've added a payment card already. 

**Adding a card during a free trial:** 
- The subtitle still appears prompting people to add a payment card when they already have. 

## Workaround:
Ignore the messaging :) 

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

<img width="1100" alt="Screenshot 2024-07-16 at 10 17 26 AM" src="https://github.com/user-attachments/assets/a0f51a47-db69-4ab3-bb13-edcc1e23c9b4">

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Issue Owner</summary>Current Issue Owner: @trjExpensify</details>

**Comment by trjExpensify** [comment] 2024-07-16 18:10
Thanks for volunteering, Sibtain! We'd love to get this PR up today if we can, @Krishna2323. Thanks!

**Comment by allroundexperts** [comment] 2024-07-16 18:32
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
Banner with `add payment card` shows up for users with a payment card already saved.

### What is the root cause of that problem?
We're showing the banner regardless of the fact that if the user has added a card or not. This can be verified [here](https://github.com/Expensify/App/blob/64c574a2b81475d6e83266220d45ef5506723b0a/src/pages/settings/Subscription/CardSection/CardSection.tsx#L80).

### What changes do you think we should make in order to solve the problem?


We need to change the condition [here](https://github.com/Expensify/App/blob/64c574a2b81475d6e83266220d45ef5506723b0a/src/pages/settings/Subscription/CardSection/CardSection.tsx#L80) to:

```
 else if (SubscriptionUtils.hasUserFreeTrialEnded() && !SubscriptionUtils.doesUserHavePaymentCardAdded()) {
```

For the case where the trial is still in progress and the card is added already, we can change the copy [here](https://github.com/Expensify/App/blob/9ada1dcacd3b31829284ffd7c067e64f8e0ff610/src/languages/en.ts#L3998) and show the card details of the user like we do in the subscription page.

### What alternative solutions did you explore? (Optional)
None

**Comment by trjExpensify** [comment] 2024-07-16 18:39
I don't know why Melv added Marc, but Chirag is on this one already. 👍

**Comment by chiragsalian** [comment] 2024-07-16 18:51
@allroundexperts proposal LGTM, feel free to create the PR.
For QA testing remember to mention to use onyx.merge to insert the necessary values so QA can test. For QA it'll only be testable on web and desktop for now.

**Comment by trjExpensify** [comment] 2024-07-18 16:10
Nice work getting this to staging!

**Comment by trjExpensify** [comment] 2024-07-26 18:11
👋 checklist time!

**Comment by trjExpensify** [comment] 2024-07-30 01:47
Makes sense to me! Payment summary as follows:

- $250 to @allroundexperts for the fix
- $250 to @aimane-chnaif for the C+ review

Feel free to request. Closing!

**Comment by JmillsExpensify** [comment] 2024-10-04 11:09
$250 approved for @allroundexperts

**Comment by trjExpensify** [comment] 2024-10-04 19:30
Offer sent to @aimane-chnaif.

**Comment by trjExpensify** [comment] 2024-10-07 22:15
Waiting on Aimane to accept the [offer](https://www.upwork.com/nx/wm/offer/104271015), Melvin.

**Comment by trjExpensify** [comment] 2024-10-08 22:05
Paid Aimane, closing.

**Closed by trjExpensify** 2024-10-08 22:05 UTC
Labels: External, Daily, Awaiting Payment, Bug
