### ISSUE TITLE
[$500] scroll bar on enable wallet page is in the middle of the screen on mobile

### ISSUE THREAD

**Issue by m-natarajan** [Expensify/App#33526] opened 2023-12-22 20:25 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 
**Reproducible in staging?:** needs reproduction
**Reproducible in production?:** needs reproduction
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** @grgia 
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1703194885001139

## Action Performed:
1. Open app
2. Go to settings
3. Tap wallet
4. Tap "enable wallet"

## Expected Result:
Scrollbar should not appear in the middle

## Actual Result:
scroll bar on enable wallet page is in the middle of the screen on mobile. Additionally three of the values read N/A and it’s unclear if that’s intentional.

## Workaround:
unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [x] iOS: Native
- [ ] iOS: mWeb Safari
- [ ] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

https://github.com/Expensify/App/assets/38435837/b54ac84c-09a5-47cf-b92d-ffd8d1c29b70

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~019e6f43e90acfc383</li>
        <li>Upwork Job ID: 1739090412690550784</li>
        <li>Last Price Increase: 2024-01-01</li>
    </ul>
</details>

**Comment by bfitzexpensify** [comment] 2023-12-25 01:07
I can't reproduce because I don't have a gold wallet, but sending this one external

**Comment by Santhosh-Sellavel** [comment] 2023-12-25 18:10
Unassigning  this one due to low bandwidth please assign a new C+ here @bfitzexpensify

**Comment by bfitzexpensify** [comment] 2023-12-28 15:19
How do these proposals look @sobitneupane?

**Comment by mvtglobally** [comment] 2023-12-31 06:12
Issue not reproducible during KI retests. (First week)

**Comment by bfitzexpensify** [comment] 2024-01-01 20:43
Let's close this as not reproducible.

**Closed by bfitzexpensify** 2024-01-01 20:43 UTC
Labels: External, Daily, Needs Reproduction, Help Wanted, Overdue, Bug
