### ISSUE TITLE
Long press to update assignee makes the 'mark as done' button change color.

### ISSUE THREAD

**Issue by kavimuru** [Expensify/App#22483] opened 2023-07-08 16:47 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Create a workspace
2. Open announce room
2. Create a task and assign my self
3. Long press into avatar assignee of task detail, observed button 'Mark as one' is discolored
## Expected Result: 
When long press on user B's avatar to update assignee, the "Mark as done" button does not change color
## Actual Result: 
Long press into avatar of user B of task detail, observed button 'Mark as one' is discolored

## Workaround:
Can the user still use Expensify without this being fixed? Have you informed them of the workaround?

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [x] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 1.3.38-3
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/43996225/1ab63ca1-f58c-4ad5-bd9d-46b9df28569e

https://github.com/Expensify/App/assets/43996225/1a979c3e-2b95-4202-932a-69930938d126

**Expensify/Expensify Issue URL:**
**Issue reported by:** @namhihi237 
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1688790088728529

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by ygshbht** [comment] 2023-07-08 17:29
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
The issue pertains to an unexpected UI behavior where the 'Mark as done' button changes color when a long press action is performed on the avatar of an assignee in a task detail view.

### What is the root cause of that problem?
This behavior arises due to the way UI elements are nested within the application's codebase. Specifically, the 'Mark as done' button is nested within the 'PressableWithFeedback' component in 'TaskHeader.js'. When a long press action is performed, it's unintentionally impacting the nested 'Mark as done' button causing it to change color.

### What changes do you think we should make in order to solve the problem?

### What alternative solutions did you explore? (Optional)
The problem originates from the 'Mark as done' button being nested within 'PressableWithFeedback'. A potential resolution is to adjust the layout to place this button outside 'PressableWithFeedback'. The presented code illustrates this concept, although it may require some additional adjustments for full integration.

<details><summary>Code</summary>```
<View style={[styles.flexRow, styles.alignItemsCenter, styles.justifyContentBetween, styles.pv3]}>
                        <PressableWithFeedback
                            onPress={() => Navigation.navigate(ROUTES.getTaskReportAssigneeRoute(props.report.reportID))}
                            disabled={!isOpen}
                            accessibilityRole={CONST.ACCESSIBILITY_ROLE.BUTTON}
                            accessibilityLabel={props.translate('newTaskPage.assignee')}
                            hoverDimmingValue={1}
                            pressDimmingValue={0.2}
                        >
                            <View style={[styles.flexRow, styles.alignItemsCenter, styles.justifyContentBetween]}>
                                {assigneeAccountID && assigneeAccountID > 0 && (
                                    <>
                                        <Avatar
                                            source={assigneeAvatar}
                                            type={CONST.ICON_TYPE_AVATAR}
                                            name={assigneeName}
                                            size={CONST.AVATAR_SIZE.HEADER}
                                        />
                                        <View style={[styles.flexColumn, styles.ml3]}>
                                            <Text
                                                style={[styles.headerText, styles.pre]}
                                                numberOfLines={1}
                                            >
                                                {assigneeName}
                                            </Text>
                                        </View>
                                    </>
                                )}
                            </View>
                        </PressableWithFeedback>
                        <View style={[styles.flexRow]}>
                            {isCompleted ? (
                                <>
                                    <Text>{props.translate('task.completed')}</Text>
                                    <View style={styles.defaultCheckmarkWrapper}>
                                        <Icon
                                            src={Expensicons.Checkmark}
                                            fill={themeColors.iconSuccessFill}
                                        />
                                    </View>
                                </>
                            ) : (
                                <Button
                                    success
                                    isDisabled={TaskUtils.isTaskCanceled(props.report) || !TaskUtils.isTaskAssigneeOrTaskOwner(props.report, props.session.accountID)}
                                    medium
                                    text={props.translate('newTaskPage.markAsDone')}
                                    onPress={() => TaskUtils.completeTask(props.report.reportID, title)}
                                />
                            )}
                        </View>
                    </View>
```</detaills>

**Comment by jasperhuangg** [comment] 2023-07-10 20:58
Don't think we need to fix this, closing. We might even potentially remove the header being used to select the assignee, which means we won't need to fix this anymore.

**Closed by jasperhuangg** 2023-07-10 20:58 UTC
Labels: Daily, Overdue, Bug
