### ISSUE TITLE
[HOLD for payment 2023-09-27] [$500] IOS - Mention list open again after requesting money

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#26534] opened 2023-09-01 21:28 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Go to any report, type @
2. Go back to LHN, click Plus button and choose request money, request any amount to the above report.
3. Repeat above steps few times.
4. Notice that mention list is opened even composer is not focused.

## Expected Result:
 If composer is not focused, mention list shouldn't be opened.

## Actual Result:
Mention list is opened even when composer is not focused.

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [x] Android / Chrome
- [x] iOS / native
- [ ] iOS / Safari
- [ ] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 1.3.61.0
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/93399543/3c0bb510-cdc5-4d24-baf8-54e9adffa118

https://github.com/Expensify/App/assets/93399543/06c8fadb-aed4-4a54-82a4-1aa8fd6f172b

**Expensify/Expensify Issue URL:**
**Issue reported by:** @hungvu193
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1693194595071649

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~014c468cc852a95d2d</li>
        <li>Upwork Job ID: 1699131259631747072</li>
        <li>Last Price Increase: 2023-09-05</li>
<li>Automatic offers: </li>
<ul>
<li>cubuspl42 | Reviewer | 26637784</li>
<li>akinwale | Contributor | 26637787</li>
<li>hungvu193 | Reporter | 26637788</li>
</ul></li>
    </ul>
</details>

**Comment by akinwale** [comment] 2023-09-01 22:05
## Proposal

### Please re-state the problem that we are trying to solve in this issue.

### What is the root cause of that problem?
The `Suggestions` component in `ComposerWithSuggestions` is not conditionally rendered based on the composer's current focus state.

### What changes do you think we should make in order to solve the problem?


### What alternative solutions did you explore? (Optional)
None.

**Comment by tjferriss** [comment] 2023-09-05 18:44
I was able to reproduce the bug on staging.

**Comment by jeet-dhandha** [comment] 2023-09-05 19:46
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
- After leaving a `@` in Composer of a chat and then if we request money from FAB to same chat then after requesting money when we redirect to that chat then Suggetions are shown in composer.

### What is the root cause of that problem?
- The root cause of this problem is that `onSelectionChange` is getting called in `ComposerWithSuggestions` component.

### What changes do you think we should make in order to solve the problem?
- We can check if the composer is focued or not in `onSelectionChange` function of `Suggestions.js`. And early return if composer is not focued. For this we can use `ReportActionComposeFocusManager.isFocused()` function.

### What alternative solutions did you explore? (Optional)
- N/A

**Comment by cubuspl42** [comment] 2023-09-06 08:25
@jeet-dhandha Could you sum up the differences between your proposal and [the earlier one](https://github.com/Expensify/App/issues/26534#issuecomment-1703371958)?

I know it was edited, but I'm referring to the state 1 minute before your comment was submitted. It's quite possible that you weren't familiar with that edit when you started investigating.

**Comment by jeet-dhandha** [comment] 2023-09-06 08:49
I started investing and saw that onSelectionChange is getting called even when composer was not focused so the only solution came to my mind was to disable further execution of `onSelectionChange ` from Sugesstions.js as suggestions have a bug here and not the composer.
 I don’t know about proposal but the last time i saw it was to hide the whole Suggestion component. And getting the same solution at same time looks odd.

**Comment by cubuspl42** [comment] 2023-09-06 14:21
@jeet-dhandha It may be odd, but the timestaps suggest it happened. It looks that the proposal by @akinwale from 2023-09-05T19:45:10Z and your proposal from 2023-09-05T19:46:46Z are essentially the same.

@akinwale Did you write down the "Solution 1" after getting familiar with [this comment](https://github.com/Expensify/App/issues/26534#issuecomment-1707217742), which would suggest a glitch in GitHub timestamps, or before?

**Comment by akinwale** [comment] 2023-09-06 14:26
> @jeet-dhandha It may be odd, but the timestaps suggest it happened. It looks that the proposal by @akinwale from 2023-09-05T19:45:10Z and your proposal from 2023-09-05T19:46:46Z are essentially the same.
> 
> @akinwale Did you write down the "Solution 1" after getting familiar with [this comment](https://github.com/Expensify/App/issues/26534#issuecomment-1707217742), which would suggest a glitch in GitHub timestamps, or before?

That's a weird coincidence. I decided to take another look at the issue to find a root cause after the Help Wanted label was assigned as I was trying to cover all my bases, which led me to the onSelectionChange implementation.

My edit with the onSelectionChange solution looks to be about a minute and a half earlier than the other proposal, so there's no way I could've been able to see the other comment beforehand.

**Comment by jeet-dhandha** [comment] 2023-09-06 20:11
Its upto @cubuspl42 now 🙌

**Comment by cubuspl42** [comment] 2023-09-12 09:23
I say we go with @akinwale ("Solution 1"). While @jeet-dhandha proposed essentially the same solution nearly at the same time, timestamps say that the edit by @akinwale happened slightly earlier.

C+ reviewed 🎀 👀 🎀

**Comment by akinwale** [comment] 2023-09-12 19:58
@cubuspl42 My [PR](https://github.com/Expensify/App/pull/27287) is ready for review. Thanks.

**Comment by cubuspl42** [comment] 2023-09-21 08:30
- The PR that introduced the bug has been identified. Link to the PR:
    -  https://github.com/Expensify/App/pull/25758
- The offending PR has been commented on, pointing out the bug it caused and why, so the author and reviewers can learn from the mistake. Link to comment:
    - https://github.com/Expensify/App/pull/25758/files#r1332681272
- A discussion in #expensify-bugs has been started about whether any other steps should be taken (e.g. updating the PR review checklist) in order to catch this type of bug sooner. Link to discussion:
    - No need for additional discussion
- Determine if we should create a regression test for this bug.
    - No need for a new regression test
- If we decide to create a regression test for the bug, please propose the regression test steps to ensure the same bug will not reach production again.
    - N/A

**Comment by tjferriss** [comment] 2023-09-25 06:56
Payment Summary:

- Reporter: @hungvu193 $250
- Contributor: @akinwale $750
- Contributor+: @cubuspl42  $750

Eligible for the 50% speed bonus

**Comment by tjferriss** [comment] 2023-09-29 04:38
Everyone has been paid out via Upworks. Closing!

**Closed by tjferriss** 2023-09-29 04:38 UTC
Labels: External, Daily, Overdue, Awaiting Payment, Bug
