### ISSUE TITLE
[HOLD for payment 2024-07-25] [$250] Expense - Tapping back button after deleting expense leads to not here page

### ISSUE THREAD

**Issue by m-natarajan** [Expensify/App#44199] opened 2024-06-22 13:08 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 9.0.1-0
**Reproducible in staging?:** y 
**Reproducible in production?:** n
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** applause internal team
**Slack conversation:**

## Action Performed:
1. Launch New Expensify app.
2. Submit two manual expenses to any user.
3. Go to transaction thread of any expenses.
4. Tap on the report header.
5. Tap Delete expense.
6. Delete the expense.
7. Tap on the back button on the top left.

## Expected Result:
App will return to the main page.

## Actual Result:
App shows long skeleton loading and then not here page loads.

## Workaround:
unknown
## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [x] Android: mWeb Chrome
- [x] iOS: Native
- [ ] iOS: mWeb Safari
- [ ] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

https://github.com/Expensify/App/assets/38435837/19324436-532e-4869-99f7-aee4e247de92

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~0149255b2b8a3385dc</li>
        <li>Upwork Job ID: 1805204830810844307</li>
        <li>Last Price Increase: 2024-06-24</li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @CortneyOfstad</details>

**Comment by m-natarajan** [comment] 2024-06-22 13:10
@CortneyOfstad FYI I haven't added the External label as I wasn't 100% sure about this issue. Please take a look and add the label if you agree it's a bug and can be handled by external contributors

**Comment by m-natarajan** [comment] 2024-06-22 13:10
We think that this bug might be related to #wave-collect - Release 1

**Comment by mountiny** [comment] 2024-06-25 12:35
@bernhardoj is your fix going to work here too?

**Comment by mountiny** [comment] 2024-06-25 12:35
I think we can demote this issue at this point. Its not blocking the user from using the app further, its quite specific edge case too

**Comment by mountiny** [comment] 2024-06-25 12:41
Asked @cdOut to look into this as he worked on the details revamp

**Comment by bernhardoj** [comment] 2024-06-25 13:02
@mountiny sorry, which one?

**Comment by yassinezaanouni** [comment] 2024-06-25 13:06
I fixed the issue. I came from Upwork. Should I submit the proposal, or is there no need to now?

**Comment by yassinezaanouni** [comment] 2024-06-25 13:08
Contributor details
Your Expensify account email: yassinezaanouni@gmail.com
Upwork Profile Link: [<REPLACE LINK HERE>](https://www.upwork.com/freelancers/~01b7c13603c181bfe7)

**Comment by yassinezaanouni** [comment] 2024-06-25 13:38
@mountiny I fixed the issue. I came from Upwork. Should I submit the proposal, or is there no need to now?

**Comment by yassinezaanouni** [comment] 2024-06-25 14:26
I submitted a proposal on Upwork outlining how to fix this. I have already fixed it locally and included a video in the proposal showcasing the app working as expected.

**Comment by kosmydel** [comment] 2024-06-25 15:36
Hey, I'm from SWM. I've found a possible solution. I need to consult it with navigation colleagues. I will update you tomorrow as they are already OOO.

**Comment by yassinezaanouni** [comment] 2024-06-25 17:29
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
When a user deletes a Transaction and subsequently presses the back button, the app shows "page is not here" error.

### What is the root cause of that problem?
When the user deletes a Transaction, they are navigated to the page of the deleted item, resulting in a "page is not here" error.

### What changes do you think we should make in order to solve the problem?
We will remove the deleted Transaction's page from the routes stack list.

𝗜𝘁𝗲𝗺 𝗗𝗲𝗹𝗲𝘁𝗶𝗼𝗻:
Make the necessary changes for transaction deletion.

𝗔𝗰𝗰𝗲𝘀𝘀 𝗡𝗮𝘃𝗶𝗴𝗮𝘁𝗶𝗼𝗻 𝗦𝘁𝗮𝗰𝗸:
Utilize the navigation library's API to access and manipulate the navigation stack.

𝗥𝗲𝗺𝗼𝘃𝗲 𝗗𝗲𝗹𝗲𝘁𝗲𝗱 𝗣𝗮𝗴𝗲 𝗳𝗿𝗼𝗺 𝗦𝘁𝗮𝗰𝗸:
Identify and remove the page corresponding to the deleted item from the navigation stack.

𝗨𝗽𝗱𝗮𝘁𝗲 𝗡𝗮𝘃𝗶𝗴𝗮𝘁𝗶𝗼𝗻 𝗦𝘁𝗮𝘁𝗲:
Apply the updated navigation stack state using the navigation library's state management functions to ensure the deleted page is no longer accessible.

**Comment by kosmydel** [comment] 2024-06-26 14:00
I've found a possible fix similar to [this one](https://github.com/Expensify/App/issues/44212).
But after a discussion with @WojtekBoman we've concluded that it might require changes in the `goBack` function of Navigation. 

@mountiny what is the priority of it? If needed, I can instantly prepare a fix; later, the navigation team will prepare a more generic solution.

**Comment by mountiny** [comment] 2024-06-26 22:27
Depends on what other tasks you have lined up, I think it would be great to get a PR merged for this by EOW

**Comment by yassinezaanouni** [comment] 2024-06-27 09:07
> Depends on what other tasks you have lined up, I think it would be great to get a PR merged for this by EOW

Hey I'd like to know why my proposal is not getting considered?

**Comment by kosmydel** [comment] 2024-06-27 09:32
> the updated navigation stack state using the navigation library's state management functions to ensure the deleted page is no longer accessible.

Hey @yassinezaanouni, initially I with @cdOut was working on [this change](https://github.com/Expensify/App/pull/43251) which caused this bug. That's why we are investigating it.

Moreover, your proposal is IMO too general and doesn't mention the detailed root cause and solution.

**Comment by yassinezaanouni** [comment] 2024-06-27 11:08
@kosmydel Ok thank you, next time I'll try to be more specific.

**Comment by kosmydel** [comment] 2024-06-27 13:29
@mountiny I've prepared a fix as the navigation team (Adam & Wojtek) is busy now, but they will probably need to fix it using a more general approach as a follow-up (fixing the `goBack` function), as I don't have enough context here.

**Comment by mountiny** [comment] 2024-06-27 21:47
Nice, thanks @kosmydel! Can you please write more description for the fix and prepare the PR body/ checklist?

**Comment by kosmydel** [comment] 2024-06-28 06:33
> Nice, thanks @kosmydel! Can you please write more description for the fix and prepare the PR body/ checklist?

I've added more details in the PR, and filled in the checklist

**Comment by iwiznia** [comment] 2024-07-17 11:56
This has been re-reported here https://github.com/Expensify/App/issues/45576 so it seems the PR did not fix the issue or broke some very similar case. Going to mark this issue as blocker and close the other one

**Comment by iwiznia** [comment] 2024-07-17 11:56
@allgandalf posted a proposal [here](https://github.com/Expensify/App/issues/45576#issuecomment-2233093947)

**Comment by iwiznia** [comment] 2024-07-17 12:30
Did you try reverting the PR in this issue and see if it fixes the new problem? Seems quite suspicious that this PR was deployed on staging and the issue started happening.

But also, it is certainly related, no? Like it's the same problem in a slightly different flow?

**Comment by kosmydel** [comment] 2024-07-17 13:05
> If I am understanding this correctly, it seems to me that they are basically the same problem and the fix applied here was incomplete. Your proposal is even in the same line as the PR in this issue changed and it's in the same flow.

This is not the same. 

Previously, we were redirected to the page that was not found. Now, it briefly shows the not found page, when closing the RHP (but finally we are on the correct chat, previously we landed on not found). I'm not sure how we missed it during the testing and review. The [RCA](https://github.com/Expensify/App/issues/45576#issuecomment-2233212003) here sounds correct.

I can have a look at this, but I will probably have some results tomorrow, as I'm finishing my work for today soon.

**Comment by thienlnam** [comment] 2024-07-17 21:15
Demoting again from this [convo](https://expensify.slack.com/archives/C07J32337/p1721250103672039)

**Comment by CortneyOfstad** [comment] 2024-07-24 19:32
@allroundexperts can you have the checklist completed before EOD tomorrow? This will help avoid any delay in payment — thank you!

**Comment by CortneyOfstad** [comment] 2024-07-25 18:08
@allroundexperts please complete the check list at your earliest convenience! Thank you!

**Comment by cdOut** [comment] 2024-07-29 08:02
Hi, I just wanted to confirm, has this issue been properly fixed by this or another issue PR or are there still problems as pointed in [this previous comment](https://github.com/Expensify/App/issues/44199#issuecomment-2233138733)?

**Comment by allroundexperts** [comment] 2024-07-29 08:04
> Hi, I just wanted to confirm, has this issue been properly fixed by this or another issue PR or are there still problems as pointed in [this previous comment](https://github.com/Expensify/App/issues/44199#issuecomment-2233138733)?

The other issue was closed and fix was added here.

**Comment by allroundexperts** [comment] 2024-07-29 08:45
## Checklist
1. https://github.com/Expensify/App/pull/43251
2. The author is aware of the issue and helped to review the fix in this issue.
3. N/A
4. A regression test would be helpful here.

### Regression test
1. Open the app and submit two manual expenses to any user.
2. Go to transaction thread of any expenses.
3. Tap on the report header and select Delete expense.
4. Delete the expense.
5. Tap on the back button on the top left.

Verify that the app returns to the main page.

Do we 👍 or 👎 ?

**Closed** 2024-07-29 17:50 UTC
Labels: External, Engineering, Daily, Help Wanted, Overdue, Awaiting Payment, Bug

**Comment by JmillsExpensify** [comment] 2024-10-04 11:07
$250 approved for @allroundexperts
