### ISSUE TITLE
[HOLD for payment March 4th - $500] IOU - After creating a manual split bill, the date is not saved

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#34526] opened 2024-01-15 18:56 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.25-1
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** Applause -Internal Team
**Slack conversation:**

## Action Performed:
1. Open https://staging.new.expensify.com/
2. Navigate to or create a Workspace room
3. In Compose Box, in the action menu, click split bill
4. Complete the Split Bill by filling in any data(except for the current date) in the Date fields
5. Navigate to the description of the created IOU

## Expected Result:
After creating a manual split bill, the selected date should be saved

## Actual Result:
After creating a manual split bill, the date is not saved

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [x] Android: mWeb Chrome
- [x] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details> 

https://github.com/Expensify/App/assets/78819774/d605f90f-6e9b-4a09-9407-bde35dc1b2be

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01d923151568647762</li>
        <li>Upwork Job ID: 1746969528531050496</li>
        <li>Last Price Increase: 2024-01-22</li>
<li>Automatic offers: </li>
<ul>
<li>c3024 | Reviewer | 28117809</li>
<li>s-alves10 | Contributor | 28117810</li>
</ul></li>
    </ul>
</details>

**Comment by s-alves10** [comment] 2024-01-15 19:15
## Proposal

### Please re-state the problem that we are trying to solve in this issue.

When creating a manual split bill, the date is not saved

### What is the root cause of that problem?

We're creating a split bill request here
https://github.com/Expensify/App/blob/a459786d08dd279a4b386690c06c2cb1f18c0575/src/pages/iou/request/step/IOURequestStepConfirmation.js#L236-L266

As you can see above, we're not passing `transaction.created` to the `splitBill` and `splitBillAndOpenReport` function.
[splitBill](https://github.com/Expensify/App/blob/a459786d08dd279a4b386690c06c2cb1f18c0575/src/libs/actions/IOU.js#L1669) and [splitBillAndOpenReport](https://github.com/Expensify/App/blob/a459786d08dd279a4b386690c06c2cb1f18c0575/src/libs/actions/IOU.js#L1717) functions don't add `created` value to the request body as well

This is the root cause

### What changes do you think we should make in order to solve the problem?

1. Add `created` argument to the above two functions(`splitBill` and `splitBillAndOpenReport`) functions and [createSplitsAndOnyxData](https://github.com/Expensify/App/blob/a459786d08dd279a4b386690c06c2cb1f18c0575/src/libs/actions/IOU.js#L1326) function. In the `splitBill` and `splitBillAndOpenReport` functions, pass `created` to `createSplitsAndOnyxData` function and API request body
2. Backend should be updated. It looks like adding `created` to the request body doesn't work for now.


### What alternative solutions did you explore? (Optional)

**Comment by DylanDylann** [comment] 2024-01-16 02:25
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
After creating a manual split bill, the date is not saved

### What is the root cause of that problem?
We don't pass `created` param to `splitBill`, `splitBillAndOpenReport` and `startSplitBill` function, so that  pass `created` param also isn't added to these APIs

https://github.com/Expensify/App/blob/d5f0f6f5057430998b107d63e372dec35c8e57f4/src/pages/iou/request/step/IOURequestStepConfirmation.js#L221-L263

### What changes do you think we should make in order to solve the problem?

1. We need to pass created params to `splitBill`, `splitBillAndOpenReport` and `startSplitBill` function 
2. **Adding created field into optimisticData (the above proposal is missed)**
3. Adding created field into body request of APIs

Note: in `startSplitBill` case we don't display `date` field because this logic
https://github.com/Expensify/App/blob/d5f0f6f5057430998b107d63e372dec35c8e57f4/src/pages/iou/request/step/IOURequestStepConfirmation.js#L373
So that we can only need to apply above change for `splitBill` and `splitBillAndOpenReport`. But I still recommend we should update all for consistency
### What alternative solutions did you explore? (Optional)
NA

**Comment by shahinyan11** [comment] 2024-01-16 08:48
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
 IOU - After creating a manual split bill, the date is not saved 
### What is the root cause of that problem?
The two proposals above describe the correct root cause. The changes to solve the problem also reasonable , but I think but I have two solutions and lack specificity.
### What changes do you think we should make in order to solve the problem?
1. We need to add the ability to get one more parameter ( `created` ) for the `splitBill` and `splitBillAndOpenReport` functions. And pass `transaction.created` as a param to [splitBill](https://github.com/Expensify/App/blob/8e2fb675389bb84deee4b8e001a536252883e72f/src/pages/iou/request/step/IOURequestStepConfirmation.js#L237) and [splitBillAndOpenReport](https://github.com/Expensify/App/blob/8e2fb675389bb84deee4b8e001a536252883e72f/src/pages/iou/request/step/IOURequestStepConfirmation.js#L237) functions ( As described in above two proposal )
2. Pass `created` to [createSplitsAndOnyxData](https://github.com/Expensify/App/blob/8e2fb675389bb84deee4b8e001a536252883e72f/src/libs/actions/IOU.js#L1685C43-L1685C66) function as a param and add it to optimistic data by changing this [line](https://github.com/Expensify/App/blob/8e2fb675389bb84deee4b8e001a536252883e72f/src/libs/actions/IOU.js#L1356) with `created` from function params. **(** There is a mention of this in the @DylanDylann's proposal but not specified specifically where and what change needs to be added  the `created` in optimistic data **)**
3. Add `created` in Api params [here](https://github.com/Expensify/App/blob/8e2fb675389bb84deee4b8e001a536252883e72f/src/libs/actions/IOU.js#L1697) ( As described in above two proposal )
### What alternative solutions did you explore? (Optional)

**Comment by slafortune** [comment] 2024-01-18 22:04
@c3024 can you please review the proposals?

**Comment by c3024** [comment] 2024-01-19 11:12
This needs backend changes so needs to be internal.

**Comment by s-alves10** [comment] 2024-01-19 11:16
@c3024 

Yes, this needs backend changes, but frontend should be updated as well, I think

**Comment by slafortune** [comment] 2024-01-22 20:38
Getting some engineering eyes related to the BE changes needed.

**Comment by aldo-expensify** [comment] 2024-01-22 20:50
Yes, the backend doesn't seem to have implemented to take `created` as a parameter. @c3024 I think we can review a frontend proposal assuming that a `created` parameter will be accepted by the commands related to split bill `SplitBill` and `SplitBillAndOpenReport` (not sure if there is another to look at)

**Comment by c3024** [comment] 2024-01-23 14:58
Thank you all for your proposals.

Each proposal improved upon the previous proposal.

I think @s-alves10 [proposal here](https://github.com/Expensify/App/issues/34526#issuecomment-1892667210) being first should be considered.

🎀 👀 🎀 C+ Reviewed

**Comment by c3024** [comment] 2024-01-23 15:01
> Thank you all for your proposals.
> 
> Each proposal improved upon the previous proposal.
> 
> I think @s-alves10 [proposal here](https://github.com/Expensify/App/issues/34526#issuecomment-1892667210) is detailed enough. Their proposal being first should be considered.
> 
> 🎀 👀 🎀 C+ Reviewed

**Comment by s-alves10** [comment] 2024-01-24 05:54
@c3024 @aldo-expensify 
This issue need backend updates as well. Can you please tell me when I can expect backend update?

**Comment by aldo-expensify** [comment] 2024-01-24 14:44
I would say it will at least take a week or a bit more considering that I haven't started coding, then we will have to wait for review, merge and deploy.

I'm guessing you can still do the App PR thinking like the commands will accepts a parameter `created`. It will be useful to have it early so I can test the work done in the backend too.

**Comment by s-alves10** [comment] 2024-01-25 11:09
The draft PR is created for testing: https://github.com/Expensify/App/pull/35141

**Comment by aldo-expensify** [comment] 2024-01-30 01:15
Thanks @s-alves10 I'm going to start working on the backend soon

**Comment by aldo-expensify** [comment] 2024-02-01 20:03
Working on this today

**Comment by aldo-expensify** [comment] 2024-02-02 02:46
Backend PRs ready for review:

- https://github.com/Expensify/Auth/pull/9821
- https://github.com/Expensify/Web-Expensify/pull/40765

**Comment by aldo-expensify** [comment] 2024-02-05 18:59
No overdue, backend PRs are under review

**Comment by aldo-expensify** [comment] 2024-02-12 19:37
One PR was deployed, the other one was just merged. We can expect to have this in staging later today or tomorrow.

**Comment by aldo-expensify** [comment] 2024-02-13 23:18
@c3024 the last backend PR hit staging, you can proceed with making https://github.com/Expensify/App/pull/35141 ready for review

**Comment by s-alves10** [comment] 2024-02-14 00:23
I've merged the PR with the latest main but it still looks not working

**Comment by s-alves10** [comment] 2024-02-26 23:26
Automation looks not working. Pay day would be 4th, Mar here

**Comment by slafortune** [comment] 2024-02-28 16:25
Yep - Thanks for noticing that @s-alves10 
@c3024 can you complete the checklist as well - 

1. The PR that introduced the bug has been identified. Link to the PR:

2. The offending PR has been commented on, pointing out the bug it caused and why, so the author and reviewers can learn from the mistake. Link to comment:

3. A discussion in #expensify-bugs has been started about whether any other steps should be taken (e.g. updating the PR review checklist) in order to catch this type of bug sooner. Link to discussion:

4. Determine if we should create a regression test for this bug.

5. If we decide to create a [regression test](https://github.com/Expensify/App/blob/main/contributingGuides/REGRESSION_TEST_BEST_PRACTICES.md) for the bug, please propose the regression test steps to ensure the same bug will not reach production again

**Comment by c3024** [comment] 2024-03-01 16:09
1. The PR that introduced the bug has been identified. Link to the PR: The required changes were not implemented on backend so the frontend changes were not implemented so no specific PR can be held responsible.
 2. The offending PR has been commented on, pointing out the bug it caused and why, so the author and reviewers can learn from the mistake. Link to comment: NA
 3. A discussion in #expensify-bugs has been started about whether any other steps should be taken (e.g. updating the PR review checklist) in order to catch this type of bug sooner. Link to discussion: No because this issue happened because frontend changes were not done since the `created` field was not implemented on backend
 4. Determine if we should create a regression test for this bug. Yes
 5. If we decide to create a [regression test](https://github.com/Expensify/App/blob/main/contributingGuides/REGRESSION_TEST_BEST_PRACTICES.md) for the bug, please propose the regression test steps to ensure the same bug will not reach production again

### Regression Test Proposal
1. Open ND and log in with any account
2. Navigate to workspace chat
3. Tap "+" button near the composer and select "Split bill"
4. Enter any amount in manual tab and tap "Next"
5. Change the date (except the current date) and tap "Split" button
6. Tap the created IOU to open split bill details page
7. Verify that the modified date was saved exactly

👍 or 👎

**Comment by slafortune** [comment] 2024-03-06 15:11
test rail - https://github.com/Expensify/Expensify/issues/376012

paid 👍

**Closed** 2024-03-06 15:12 UTC
Labels: Reviewing, External, Engineering, Weekly, Bug
