### ISSUE TITLE
[$500] Contact Method - Red dot error message appears and then goes away

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#32681] opened 2023-12-07 16:04 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.9.1
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** Applause - Internal Team
**Slack conversation:**

## Action Performed:
1. Access staging.new.expensify.com
2. Sign into a valid account
3. Click on Profile > Contact Method > Add any contact method
4. After adding the contact method, go to the Verify page and enter any random code (To get the error message)
5. Tap "Back" and then reenter the contact method page

## Expected Result:
User expects that if the red dot is showing on the main contact method page, that an error message should be shown when reentering the page OR if no error message is to be shown, then no red dot message on the main contact page

## Actual Result:
The red dot is shown on the main contact page but as soon as the user opens the verify code page once more, there is no sign of any error

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [x] Android: mWeb Chrome
- [ ] iOS: Native
- [x] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

https://github.com/Expensify/App/assets/93399543/5c35f570-370e-44d4-8250-4fcbff7b2432

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01c2adce8aa36e2400</li>
        <li>Upwork Job ID: 1732793152607379456</li>
        <li>Last Price Increase: 2023-12-07</li>
    </ul>
</details>

**Comment by ZhenjaHorbach** [comment] 2023-12-07 16:19
# Proposal
## Please re-state the problem that we are trying to solve in this issue.

Contact Method - Red dot error message appears and then goes away

## What is the root cause of that problem?

When we get an error
We store this value in ONYX

## What changes do you think we should make in order to solve the problem?

I think the best way to fix this is
Use `useEffect` or `navigation event` when we leave the screen like 

```
    useEffect(
        () => () => {
            User.clearContactMethodErrors(props.contactMethod, 'validateLogin');
        },
        [],
    );
```

https://github.com/Expensify/App/blob/8fa65ec4de74f22f7c700eb78b4ee83eda96de58/src/pages/settings/Profile/Contacts/ValidateCodeForm/BaseValidateCodeForm.js#L157

## What alternative solutions did you explore? (Optional)
NA

**Comment by ikevin127** [comment] 2023-12-07 16:30
# Proposal

## Please re-state the problem that we are trying to solve in this issue

The red dot is shown on the main contact page but as soon as the user opens the verify code page once more, there is no sign of any error.

## What is the root cause of that problem?

What causes the described behaviour is this code block which clears the error when the component that contains the magic code input is mounted:

https://github.com/Expensify/App/blob/8fa65ec4de74f22f7c700eb78b4ee83eda96de58/src/pages/settings/Profile/Contacts/ValidateCodeForm/BaseValidateCodeForm.js#L121-L129

## What changes do you think we should make in order to solve the problem?

We have two options here, as mentioned in **Expected Result**:
1. Remove the code that clears the error on component mount and have the error persist.
2. Remove the red dot from the Contacts Method page item in case we want to keep the logic that clears the error.

 ### Videos

<details>
<summary>MacOS: Chrome (Option 1 - Option 2)</summary>

- Option 1

https://github.com/Expensify/App/assets/56457735/72dafa97-23e1-424f-8b6e-631c1419c75f

- Option 2

https://github.com/Expensify/App/assets/56457735/5c4bcdad-5c11-4f13-8b28-5657268c9ecc

</details>

**Comment by cubuspl42** [comment] 2023-12-11 13:13
Thanks, everyone, for the proposals! I'm reviewing them

**Comment by namhihi237** [comment] 2023-12-12 02:41
@cubuspl42 with the login page we have other BaseValidateCodeForm https://github.com/Expensify/App/blob/main/src/pages/signin/ValidateCodeForm/BaseValidateCodeForm.js

**Comment by cubuspl42** [comment] 2023-12-12 10:24
> @cubuspl42 with the login page we have other BaseValidateCodeForm https://github.com/Expensify/App/blob/main/src/pages/signin/ValidateCodeForm/BaseValidateCodeForm.js

Oh, that is slightly confusing naming.

**Comment by cubuspl42** [comment] 2023-12-12 10:32
Summing up the proposals:

- @namhihi237 & @ZhenjaHorbach: reasonable proposals, similar. Both edited multiple times, unless you want to start some edit timestamp investigation, I'll assume the one by @namhihi237 has precedence here as it was originally posted earlier
- @ikevin127 Thanks for your proposal. It's well written, but the solution seems less direct than the ones I mentioned above

**Comment by ikevin127** [comment] 2023-12-12 10:53
Understood!

> the solution seems less direct

That's funny if we look at the first 2 proposals edit timestamps.

Anyways, to explain the reasons why I posted a proposal after the first 2 were already posted:
- the first 2 proposals were posted 2-5 minutes after the issue was opened were vague on 3 fronts: RCA, the way they were written and solution wise
- none of the initial proposals already posted (without later edits) took into consideration both ways to fix the bug mentioned in Expected result

I suppose some contributors use this practice where they post something very vague just to get their first in first then do a dozen edits subsequently.

Perhaps this should be brought up on Slack because it seems unfair, especially for new contributors, which have 0 chance to get their first proposals in with these kind of practices from more experienced contributors 😂

**Comment by cubuspl42** [comment] 2023-12-12 11:03
Yeah, I also don't like these edit wars.

> Perhaps this should be brought up on Slack because it seems unfair, especially for new contributors, which have 0 chance to get their first proposals in with these kind of practices from more experienced contributors 😂

It's not as bad as you suggest.

Proposals are selected based on their content. Only in case of a "draw", the order of filing is taken into consideration (which is still quite often in case of the relatively simple issues).

If you had a well-written, ready proposal at a time when a proposal posted earlier was barely a stub, you can respectfully point that in the discussion, so this information is available to the C+. Don't start any kind of struggle with the contributors, though, it's about stating facts.

**Comment by namhihi237** [comment] 2023-12-12 11:55
Yeah i think when we edit it can only make the original proposal clearer, not when posting the proposal for the first time it will be different from after editing

**Comment by cubuspl42** [comment] 2023-12-13 10:18
I approve the proposal by @namhihi237

C+ reviewed 🎀 👀 🎀

**Comment by Beamanator** [comment] 2023-12-15 13:44
Sorry for the delay, @cubuspl42 - do you mind reviewing the last proposal & letting me know if your decision still stands?

**Comment by cubuspl42** [comment] 2023-12-18 11:03
@dukenv0307 

Just so we're on the same page, would you share a video presenting the glitch you observed with the other solution?

**Comment by cubuspl42** [comment] 2023-12-18 11:29
@dukenv0307 

A I see it, it's a minor delay. Seems related to the navigation, but I'm not 100% sure. It's important to note that this is also a corner case; typically, when the user is informed that they provided an invalid code, they would just fix the typo.

@Beamanator 

Unless you think that this delay is worth addressing, I think we're fine with @namhihi237 proposal. Clearing the error during component unmounting feels like a reasonable solution to me.

**Comment by cubuspl42** [comment] 2023-12-20 12:04
@dukenv0307 I hear your concerns, and I partially agree with them. You mention corner cases, though.

The error should be handled locally on the page that displays the mentioned error, while we process it globally instead.

A fix by @namhihi237 is local and brings much value with a small and relatively clean change, which moves the place where we clear the error.

Your fix brings slightly more value in corner cases but is less clean, in my opinion, as it focuses on "ignoring" the error (filtering it out) based on a specific condition.

A significantly better proposal would refactor the handling of the mentioned error to be fundamentally local, but I'm not sure whether it can be done with a reasonable amount of code.

 @Beamanator I think it comes down to whether we treat @dukenv0307's observations as more than corner cases.

**Comment by slafortune** [comment] 2023-12-21 17:36
I think let's focus for higher-level GHs and let's close this one since the proposal really isn't the best option.  this is really a pretty minor issue.

**Closed by slafortune** 2023-12-21 17:36 UTC
Labels: External, Daily, Help Wanted, Overdue, Bug

**Comment by cubuspl42** [comment] 2023-12-22 09:08
@slafortune

It seems like your actions are based mostly on the issue's impact. If so, you could've closed this issue 2 weeks ago, as the impact has been known from the beginning.

It was now in the post-proposal selection phase. It's quite late for a call like this.
