### ISSUE TITLE
mWeb/safari- Transition is not smooth when search page opened

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#27457] opened 2023-09-14 16:46 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___
**Issue found when executing PR**  https://github.com/Expensify/App/pull/24316
## Action Performed:
1. Launch the Url and login
2. Open the search panel

## Expected Result:
The transition is smooth

## Actual Result:
Transition is not smooth when search page opened

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [x] iOS / Safari
- [ ] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 1.3.70-2

**Reproducible in staging?:** Yes

**Reproducible in production?:** No

**If this was caught during regression testing, add the test name, ID and link from TestRail:**

**Email or phone of affected tester (no customers):**

**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/78819774/00e9184c-441f-4de5-93cf-df75ac1d6287

**Expensify/Expensify Issue URL:**

**Issue reported by:** Applause - Internal Team

**Slack conversation:**

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by amyevans** [comment] 2023-09-14 17:59
Hmm things seem pretty snappy on dev on a sim:

https://github.com/Expensify/App/assets/7277067/88585d01-7754-45e6-928c-2746fa37cf70

I'll try to reproduce on staging

**Comment by amyevans** [comment] 2023-09-14 18:03
Looks good to me there too:

https://github.com/Expensify/App/assets/7277067/e3512519-6295-4194-a50d-fc9e262a0e20

@lanitochka17 is this reproducible for you in any account or only a specific one?

**Comment by lanitochka17** [comment] 2023-09-14 18:18
@amyevans This happens only in expensifail account

**Comment by amyevans** [comment] 2023-09-14 18:56
Okay thanks! I can reproduce with Expensifail

**Comment by amyevans** [comment] 2023-09-14 19:15
Looks like we refactored the Search Page in https://github.com/Expensify/App/pull/23076 which just deployed to staging so that seems like a possible cause (original GH for it: https://github.com/Expensify/App/issues/16251). Mind taking a closer look @Piotrfj?

**Comment by francoisl** [comment] 2023-09-14 22:27
Here's a side-by-side comparison between the current `main` and with https://github.com/Expensify/App/pull/23076 reverted. It looks a little smoother indeed after reverting.

<table>
<tr>
 <td>On `main`
 <td>With PR 23076 reverted
<tr>
 <td><video src="https://github.com/Expensify/App/assets/2229301/45d9dbc2-6032-416d-9a06-36b11cde777e"/>
 <td><video src="https://github.com/Expensify/App/assets/2229301/d6d89ea1-acd5-4a33-a366-93d6d64868fa"/>
</table>

**Comment by amyevans** [comment] 2023-09-14 22:57
Thanks! We're going to just revert: https://github.com/Expensify/App/pull/27476

**Comment by amyevans** [comment] 2023-09-18 02:34
Revert PR is being cherry picked, so closing this out.

**Closed by amyevans** 2023-09-18 02:34 UTC
Labels: Reviewing, DeployBlockerCash, Engineering, Weekly
