### ISSUE TITLE
[$250] mWeb/Chrome - New Chat - Never-ending loading circle upon New chat / New Group page refresh

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#11808] opened 2022-10-13 15:51 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Go to https://staging.new.expensify.com/
2. Login with applausetester+pd1005@applause.expensifail.com/ Password1 (I could also repro for applausetester+0901abb@applause.expensifail.com/ Feya86Katya
3. Tap "+"
4. Tap "New Room" or "New Group"
5. Pull the screen down so page is refreshed

## Expected Result:
User can continue creating new chat or group

## Actual Result:
Never-ending loading circle is displayed.

## Additional Information:
Repro with Chrome and Edge. Not repro in Firefox, as page is not refreshed there upon pulling down the screen.
Not repro in Web and mWeb iOS / Safari

## Workaround:
Unknown

## Platform:

Where is this issue occurring?

- Mobile Web/Chrome and Edge

**Version Number:** 1.2.14.0

**Reproducible in staging?:** Yes

**Reproducible in production?:** Yes

**Email or phone of affected tester (no customers):** HT accounts

**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Notes/Photos/Videos:** Any additional supporting documentation

https://user-images.githubusercontent.com/93399543/195644797-2aa28232-151b-43f4-a5b4-f6386f8a2b48.mp4

**Expensify/Expensify Issue URL:** 

**Issue reported by:** Applause - Internal Team

**Slack conversation:** 

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by ctkochan22** [comment] 2022-10-17 22:26
Interesting. @kbecciv  can we reproduce this in a fresh account? Or this is specific to these users / `applause.expensifail.com`?

**Comment by kbecciv** [comment] 2022-10-18 14:44
@ctkochan22 Checking with Team, will update you shortly

**Comment by kbecciv** [comment] 2022-10-18 17:22
@ctkochan22 Team can not reproduce this in a fresh expensifail and gmail accounts
 -applausetester+101822abb@applause.expensifail.com)/Feya86Katya

But still repro with both below accounts which listed in bug report:
applausetester+pd1005@applause.expensifail.com
applausetester+0901abb@applause.expensifail.com
applausetester+1014pronin@applause.expensifail.com/Pronin1234

https://user-images.githubusercontent.com/93399543/196501123-a94dbcf6-cc97-4d1c-be69-d4aa87a6cbe8.mp4


https://user-images.githubusercontent.com/93399543/196501135-829fee16-e8a7-41ef-b0a5-2f15a2658218.mp4

**Comment by ctkochan22** [comment] 2022-10-20 23:46
This might have to be internal. As the best way to go about fixing this would be to point your env to prod and debug directly within these accounts

**Comment by mallenexpensify** [comment] 2022-10-21 19:56
@zanyrenney auto-assigned as BZ, please review the[ main chore SO](https://stackoverflow.com/c/expensify/questions/14418) if you have any questions.

**Comment by zanyrenney** [comment] 2022-10-24 09:27
I'm OOO today reassigning.

**Comment by maddylewis** [comment] 2022-10-24 12:35
ill get this reviewed shortly

**Comment by maddylewis** [comment] 2022-10-24 19:36
@zanyrenney i have quite a few bugs assigned to me rn and i wont be able to get to this one today. im reassigning to you so that you can review tomorrow AM.

**Comment by zanyrenney** [comment] 2022-10-25 18:07
@ctkochan22 should this still be internal? What's the latest here?

**Comment by ctkochan22** [comment] 2022-10-26 04:43
My plate is full so I unassigned. I placed internal label because it's happening specifically in the expensifail test account. Let me ask in slack

**Comment by ctkochan22** [comment] 2022-10-27 23:51
https://expensify.slack.com/archives/C03TQ48KC/p1666760050198099

I can ask again. If contributors can log into expensifail QA accounts, then we can make external

**Comment by zanyrenney** [comment] 2022-10-31 10:50
bumped: https://expensify.slack.com/archives/C03TQ48KC/p1667213438730109?thread_ts=1666760050.198099&cid=C03TQ48KC

**Comment by zanyrenney** [comment] 2022-11-03 12:58
Still haven't heard back @ctkochan22 any ideas how we can get an swer to this? Could you ask some engineers 1:1 please?

**Comment by zanyrenney** [comment] 2022-11-07 09:54
@parasharrajat - please can you let me know if you don't have the correct access for this one. I [asked our internal engineering team](https://expensify.slack.com/archives/C03TQ48KC/p1666760050198099) to confirm but they didn't get back to me.

**Comment by iwiznia** [comment] 2022-11-10 16:44
Is this only reproducible from that one account?? If so, we would need to make this internal.

**Comment by iwiznia** [comment] 2022-11-14 16:57
> Is this only reproducible from that one account?? If so, we would need to make this internal.

**Comment by parasharrajat** [comment] 2022-11-15 23:40
I will try to test it when I get time.

**Comment by zanyrenney** [comment] 2022-11-18 08:49
@parasharrajat any update here?

**Comment by parasharrajat** [comment] 2022-11-18 11:15
No proposals.

**Comment by iwiznia** [comment] 2022-11-21 10:29
This seems related to navigation, but not sure why it is reproducible on some accounts only. Anyway, still waiting for proposals.

**Comment by mvtglobally** [comment] 2022-11-22 21:09
Issue not reproducible during KI retests. (First week)

**Comment by zanyrenney** [comment] 2022-11-24 17:31
Woo, great news 🎉

**Comment by iwiznia** [comment] 2022-11-28 14:34
It does not seem anyone can reproduce this. Going to close.

**Closed by iwiznia** 2022-11-28 14:34 UTC
Labels: External, Engineering, Daily, Internal, Overdue, Bug
