### ISSUE TITLE
Thread - Parent message with reply is highlighted in main chat after returning from thread

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#39250] opened 2024-03-29 15:40 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.58-0
**Reproducible in staging?:** Y
**Reproducible in production?:** N
**If this was caught during regression testing, add the test name, ID and link from TestRail:** N/A
**Issue reported by:** Applause - Internal Team

## Action Performed:
1. Go to staging.new.expensify.com
2. Go to any chat
3. Send a message
4. Right click on the message > Reply in thread
5. Send a reply in thread
6. Click on the header subtitle to return to main chat

## Expected Result:
The parent message with reply in the main chat will not be highlighted permanently

## Actual Result:
The parent message with reply in the main chat is highlighted permanently, until user opens another chat

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [x] Android: mWeb Chrome
- [x] iOS: Native
- [x] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details> 

https://github.com/Expensify/App/assets/78819774/6b84c901-2ba9-4982-9c51-7ed459ff7750

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by lanitochka17** [comment] 2024-03-29 15:41
@blimpich  FYI I haven't added the External label as I wasn't 100% sure about this issue. Please take a look and add the label if you agree it's a bug and can be handled by external contributors

**Comment by lanitochka17** [comment] 2024-03-29 15:41
We think that this bug might be related to #vip-vsp

**Comment by blimpich** [comment] 2024-03-29 16:19
Demoting as this isn't a real blocker.

**Comment by blimpich** [comment] 2024-03-29 16:21
@gijoe0295 I think the issue isn't that it is highlighting but that it is highlighted permanently. Do you think it's expected to be highlight permanently? I'm not sure.

**Comment by blimpich** [comment] 2024-03-29 16:25
@roryabraham @perunt do you know if this is intended behavior with comment linking?

**Comment by roryabraham** [comment] 2024-04-01 17:22
keeping the highlight permanently is indeed [expected for now][(https://github.com/Expensify/App/issues/38851#issuecomment-2016237096), and we're updating the color [here](https://github.com/Expensify/App/issues/38851).

We didn't discuss this edge case, but it makes sense to me that, when linking back to a parent thread, we would highlight the linked message just like we would when deep-linking to any other comment. I think this especially would make sense / feel more right if the thread was not at the end of the comment history but further back.

As such, I think we can close this as expected for now then maybe loop back in the future if we have a problem statement we feel confident about.

**Closed by roryabraham** 2024-04-01 17:22 UTC
Labels: Engineering, Daily, Overdue
