### ISSUE TITLE
Push notification is showing as the recipient's account sent the message

### ISSUE THREAD

**Issue by kavimuru** [Expensify/App#18871] opened 2023-05-12 21:09 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___
Similar issue with Chronos is closed https://github.com/Expensify/Expensify/issues/238676 
## Action Performed:

1. Have notifications enabled on iOS
2. Lock your phone, so you'll receive push notifications on your home screen if you get any new messages from your dearest colleagues
3. Ask someone to send messages to you (or use another device/account)
4. Occasionally, see the bug where the messages they send to you appear as though you sent them in the notification.

In this issue example, that's a message **Jason sent** to John.

## Expected Result:
The notifications should display as coming from the sender, not from the recipient's account

## Actual Result:
Push notifications occasionally display as though the recipient was the one to send the message. 

## Workaround:
Can the user still use Expensify without this being fixed? Have you informed them of the workaround?

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [x] iOS / native
- [ ] iOS / Safari
- [ ] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 1.3.13.0
**Reproducible in staging?:** Y 
**Reproducible in production?:** 
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation
![IMG_7365](https://github.com/Expensify/App/assets/43996225/61d52905-0f1b-4c70-bea0-4fd1eb1ca7f6)

**Expensify/Expensify Issue URL:**
**Issue reported by:** @johnmlee101 
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1683837386890729

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01ed3c8661b8becc2e</li>
        <li>Upwork Job ID: 1658054999475965952</li>
        <li>Last Price Increase: 2023-05-15</li>
    </ul>
</details>

**Comment by johncschuster** [comment] 2023-05-12 21:44
I am going OOO so re-assigning a new coach to oversee this

**Comment by trjExpensify** [comment] 2023-05-13 14:57
Looking at the slack thread, @arosiclair @Julesssss adding this to [your tracker](https://github.com/Expensify/Expensify/issues/255265) as requested. Does this need to stay `internal`? 

Also a clue from the thread: 
>[Offending request logs](https://www.expensify.com/_devportal/tools/logSearch/#query=request_id%3A(%227c5d2e9feaf9b6df-SJC%22)%20AND%20timestamp%3A%5B2023-05-11T19%3A30%3A51.313Z%20TO%202023-05-11T21%3A30%3A51.313Z%5D&index=_all). Looks like we might be passing the wrong report action to sendReportCommentNotifications for some reason. The reportActionID in the onyxData is 4888172597293257641. I’m guessing this is probably the last message John sent

**Comment by trjExpensify** [comment] 2023-05-15 10:21
Cool, adding `internal`.

**Comment by Julesssss** [comment] 2023-05-15 16:48
> Hmmmmmm, how can a backend issue be iOS only?

I don't know for certain that it is only iOS, but we use native code to build and display mobile notifications, so it is at least possible...

**Comment by Julesssss** [comment] 2023-05-15 16:49
I think that was the only checked box because we don't have reproducible steps, and Applause was not able to verify other platforms. 

Having said that, in this case it probably does affect Android too.

**Comment by iwiznia** [comment] 2023-05-15 17:05
So, it is a race condition apparently...


> You basically just need to turn on iOS notifications, receive a bunch of notifications and hope you see the bug where the notification shows from yourself.

Can you be more specific please?

**Comment by trjExpensify** [comment] 2023-05-15 17:14
1. Have notifications enabled on iOS 
2. Lock your phone, so you'll receive push notifications on your home screen if you get any new messages from your dearest colleagues
3. Ask said dearest colleagues to send messages to you
4. Occasionally, see the bug where the messages they send to you appear as though you sent them in the notification: 

In this example, that's a message **Jason sent** to John: 

<img width="803" alt="image" src="https://github.com/Expensify/App/assets/16232057/d7799168-9cb3-43cb-9f10-d306cb589d1c">

**Comment by trjExpensify** [comment] 2023-05-18 00:03
Does that clear it up for you, Ioni?

**Comment by iwiznia** [comment] 2023-05-18 14:51
I am going to try to reproduce it, but given the steps are "just try till it breaks" not sure if I will be able to

**Comment by trjExpensify** [comment] 2023-05-22 16:22
Sounds good! Any luck?

**Comment by trjExpensify** [comment] 2023-05-22 16:24
>[Offending request logs](https://www.expensify.com/_devportal/tools/logSearch/#query=request_id%3A(%227c5d2e9feaf9b6df-SJC%22)%20AND%20timestamp%3A%5B2023-05-11T19%3A30%3A51.313Z%20TO%202023-05-11T21%3A30%3A51.313Z%5D&index=_all). Looks like we might be passing the wrong report action to sendReportCommentNotifications for some reason. The reportActionID in the onyxData is 4888172597293257641. I’m guessing this is probably the last message John sent

Was this a dead end?

**Comment by Julesssss** [comment] 2023-05-26 09:39
Unfortunately, I don't have much context here. I don't believe this is something we've touched with our changes.

**Comment by iwiznia** [comment] 2023-05-26 20:28
I don't think I will be able to solve this as I can't reproduce. Not sure where to take it from here.

**Comment by iwiznia** [comment] 2023-05-29 18:57
Demoting to weekly so I don't have to add no update every day... but maybe we should close this?

**Comment by iwiznia** [comment] 2023-05-30 18:33
Thanks @arosiclair!

OHHHHH! I think I figured it out! `notifyParticipants` is broken! 99% this was broken in this PR https://github.com/Expensify/Web-Expensify/pull/36730/files#diff-226c5d32da881d917aecc36ba4f92b77971699b9ed01f2962c14f05995b939d8R1956 (cc @tgolen).
What we are doing is:
- Call notifyParticipants, passing the reportID and comment
- notifyParticipants clears the cache and re-loads the report
- It gets the newest visible action, which is not ensured to be the action that was just added, since between when we created the action and when we reloaded the report passed time and some other action could have been added in the meantime

So not sure why we are looking for the newest action there... I need to ensure we are not adding another regression by changing this... Will come back again with either a proposal or a PR 🤔

**Comment by iwiznia** [comment] 2023-05-30 22:01
Conversation about this here https://expensify.slack.com/archives/C03TQ48KC/p1685475316281769

**Comment by iwiznia** [comment] 2023-05-30 23:19
I am going to hash out a plan, because I checked and this is used in 36 places, all of them different usages and I have no idea how much work will it be to update all of them. I might start by just migrating some flows and leaving the rest broken... though I really want to get rid of the notifyParticipants method, since it is wrong by design

**Comment by Julesssss** [comment] 2023-05-31 07:57
Nice! Following the thread discussion.

**Comment by iwiznia** [comment] 2023-05-31 19:07
PR sent.

**Comment by iwiznia** [comment] 2023-06-09 20:18
PR not yet deployed, leave me alone melvin

**Comment by trjExpensify** [comment] 2023-06-20 01:10
This hit prod 4 days ago. Given that it was reported internally and it's a web-PR (so no C+ review), I think we can close this out. 

@iwiznia if I missed anything feel free to reopen.

**Closed by trjExpensify** 2023-06-20 01:10 UTC
Labels: Reviewing, Engineering, Daily, Internal, Bug

**Comment by iwiznia** [comment] 2023-06-20 16:45
Oh, PRs with links to App issues don't auto close... :thu\
