### ISSUE TITLE
[PAYMENT DUE] [$500]  mWeb - Device back button with emoji picker opened leads to LHN instead of closing picker

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#35756] opened 2024-02-03 15:37 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.36-0
**Reproducible in staging?:** Y
**Reproducible in production?:**Y
**If this was caught during regression testing, add the test name, ID and link from TestRail:** https://expensify.testrail.io/index.php?/tests/view/4279504
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** Applause - Internal Team
**Slack conversation:**

## Action Performed:
1. Log in to New Expensify
2. Navigate to any chat
3. Open emoji picker
4. Use device back button (twice if keyboard is opened)

## Expected Result:
Emoji picker should be closed, user should remain in chat history

## Actual Result:
User is redirected back to LHN

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [x] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [ ] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details> 

https://github.com/Expensify/App/assets/78819774/31c26028-7122-47f2-abe4-66363db68835

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~0156cc7a92d86433bd</li>
        <li>Upwork Job ID: 1753804975067238400</li>
        <li>Last Price Increase: 2024-02-24</li>
    </ul>
</details>

**Comment by lanitochka17** [comment] 2024-02-03 15:38
We think that this bug might be related to #vip-vsp
CC @quinthar

**Comment by jeremy-croff** [comment] 2024-02-03 20:59
Well opening up an emoji picker is not a navigation action.

Naturally clicking the back button would navigate back to the previous screen.

This is working as intended.

The only thing I see is that the background has a disabled state. We could improve the user experience if desired to disable all clicks and only close the emoji picker when clicking outside of it. But this is not what the Issue is asking for.

**Comment by hayata-suenaga** [comment] 2024-02-04 05:10
This issue should be handled in [this issue](https://github.com/Expensify/App/issues/35626)

Thank you everyone for your proposals, but we're closing this issue 🙇

**Comment by adamgrzybowski** [comment] 2024-02-07 14:52
Hey @hayata-suenaga I agree with @jeremy-croff. It's not related to the goBack function and opening the emoji picker is not a navigation action. 

If you want to implement this anyway, then this ticket should be separated form the goBack issue.

Not sure how the presented proposal will work on native platforms and how it interferes with web history though.

Personally I like the improvement mentioned by @jeremy-croff 
>The only thing I see is that the background has a disabled state. We could improve the user experience if desired to disable all clicks and only close the emoji picker when clicking outside of it. But this is not what the Issue is asking for.

**Comment by hayata-suenaga** [comment] 2024-02-12 15:32
[re-posted](https://expensify.slack.com/archives/C01GTK53T8Q/p1707751893515849) about this issue in the #expensify-open-source channel

@sobitneupane please review the proposals when you have time 🙇

**Comment by adamgrzybowski** [comment] 2024-02-13 16:09
hey @suneox do you have a draft branch? I would like to test a few things

**Comment by zanyrenney** [comment] 2024-02-14 11:57
@sobitneupane it seems like Adam has reviewed the proposals above. Can you formally respond as to who we should be selecting here? If you do not have capacity as C+, please let me know and I will reassign the issue.

**Comment by kosmydel** [comment] 2024-02-14 16:22
@adamgrzybowski is OOO and I will try to help.

@suneox I have quickly checked it, and for now, I have found one bigger issue in this PR:
1. Go to the Profile (must have avatar uploaded).
2. Press the Edit button on the Avatar.
3. Press "View photo"
4. It doesn't work.

I'm leaving also some notes:
1. What would happen in nested modals? I think it might break the back button behavior.
2. `addEventListener` should probably be in the `useEffect` as well.
3. We shouldn't add event listeners on non mobile devices.

Are you also 100% sure, it won't break the `@react-navigation` history as those changes are not synced with this library?

**Comment by kosmydel** [comment] 2024-02-15 09:00
> This issue is not related to "view photo" it isn't using Popover, and the tested branch cover for Popover to handle this issue

I'm not sure I understand. 

The Popover is using Modal (which modifies the browser history), and this branch affects it. The problem described above doesn't occur on the main/staging.

**Comment by zanyrenney** [comment] 2024-02-16 18:44
what do you think @sobitneupane ?

**Comment by kosmydel** [comment] 2024-02-19 12:33
@suneox Personally, I don't like this new change. I think we should find a way, to solve this problem application-wide (to support nested popovers).

For instance, your initial solution worked also in this case (mWeb Android):
- Go to any report.
- Long press on any message.
- Press the android back button.

After your change, we are only covering one case from many. We should find a general solution.

---

Overall, the high-level concept makes sense to me. But we should wait for @WojtekBoman (coming back on Wednesday) or @adamgrzybowski to get another confirmation if it doesn't break the navigation.

**Comment by zanyrenney** [comment] 2024-02-19 15:15
thanks so much for the detailed review @kosmydel

**Comment by zanyrenney** [comment] 2024-02-21 15:55
we're waiting on ^^

**Comment by WojtekBoman** [comment] 2024-02-26 17:02
In my opinion, if we want to quickly fix the error, we can change the scope of this issue. However, it's definitely a good idea to create a follow-up to fix the error globally in the app. From our perspective, the fix seems ok, but I think that Adam's opinion is relevant in this case.

**Comment by zanyrenney** [comment] 2024-02-26 17:08
thanks so much @WojtekBoman @adamgrzybowski curious for your thoughts too please!

**Comment by kosmydel** [comment] 2024-02-29 17:06
@adamgrzybowski is OOO. He should be back next week.

**Comment by zanyrenney** [comment] 2024-03-04 13:45
Thanks for the update @kosmydel

**Comment by zanyrenney** [comment] 2024-03-04 13:45
@adamgrzybowski when you're back from OOO, please let us know your thoughts here.

**Comment by zanyrenney** [comment] 2024-03-06 15:28
@adamgrzybowski could you review the proposal or @kosmydel ?

**Comment by zanyrenney** [comment] 2024-03-11 11:43
bump @adamgrzybowski @kosmydel

**Comment by adamgrzybowski** [comment] 2024-03-11 16:48
@suneox  Should this also cover the desktop browser with narrow layout? I am testings this branch https://github.com/suneox/ExpensifyApp/tree/35756-close-emoji-when-navigation-back and can't make it work.

But maybe I am doing something wrong.

**Comment by adamgrzybowski** [comment] 2024-03-11 17:41
@suneox Isn't this an inconsistency between platforms? For mobile web the back action will hide the emoji picker but for the narrow desktop web (which looks similar) it will go back to the previous screen. 

I am not a UX expert but we may want to consider if we want to introduce such a difference between platforms. Maybe implementing it in both cases would be better. @zanyrenney might know who to ask about that.

**Comment by zanyrenney** [comment] 2024-03-14 11:13
going to tag the design team for another look at this one!

**Comment by zanyrenney** [comment] 2024-03-14 11:14
Hey @shawnborton - I'm heeding the advice you mentioned in Slack. please could you take a look at this one as we aren't sure about the inconsistencies in the UX? Thank you!

**Comment by shawnborton** [comment] 2024-03-14 13:07
At first glance, this does seem like a bug and it does seem like the proposal [here](https://github.com/Expensify/App/issues/35756#issuecomment-1925392413) would solve it. 

cc @Julesssss for a second opinion since this is an Android related issue. The tldr; is that if you are viewing the chats list, then you open up a chat, and then open the emoji picker, the device back button doesn't close the emoji picker and send you back to the chat but rather it takes you back to the chats list.

**Comment by Julesssss** [comment] 2024-03-14 13:18
Thanks for the TLDR, yeah after viewing the video I agree the back button should first close the emoji picker.

**Comment by adamgrzybowski** [comment] 2024-03-14 14:16
@Julesssss Just as a reminder. One of the questions is if we want the same behavior for narrow layout web on desktop and mobile web.

**Comment by Julesssss** [comment] 2024-03-14 14:52
> One of the questions is if we want the same behavior for narrow layout web on desktop and mobile web.

For all platforms I would not expect the `<` button to close the emoji picker, just like WhatsApp. The `<` action is different to the Android OS back action.

For the Android `back` action on mWeb I could go either way... As an Android user I would like for the emoji picker to close when back is pressed, just as the native keyboard does. But there is no consistency across mWeb apps, so I would also understand if mWeb behaves differently. What do you think @shawnborton?

**Comment by Julesssss** [comment] 2024-03-14 16:57
mWeb working like Android feels the better of the two options, so I'd also be happy with that.

**Comment by zanyrenney** [comment] 2024-03-18 11:57
thanks @Julesssss and @shawnborton - super helpful!

**Comment by zanyrenney** [comment] 2024-03-18 11:58
@sobitneupane can you C+ full review of this - https://github.com/Expensify/App/issues/35756#issuecomment-1925392413 so we can assign @suneox to the issue to work on it if so?

**Comment by sobitneupane** [comment] 2024-03-18 12:14
Sure @zanyrenney. I will review the proposal asap.

**Comment by sobitneupane** [comment] 2024-03-19 07:12
Thanks for the [proposal](https://github.com/Expensify/App/issues/35756#issuecomment-1925392413) @suneox 

Proposal from @suneox looks good to me. 

🎀 👀 🎀 C+ reviewed

**Comment by sobitneupane** [comment] 2024-04-10 08:25
@zanyrenney This is ready for payment.

**Comment by Julesssss** [comment] 2024-04-10 08:26
Yah, Zany has been OOO but will be back soon 🙂

**Comment by Julesssss** [comment] 2024-04-29 07:10
Hey @zanyrenney, just wanted to check you've seen this payment request?

**Comment by zanyrenney** [comment] 2024-05-07 11:25
on it, didn't see this with the lack of date automation.

**Comment by zanyrenney** [comment] 2024-05-07 11:30
payment summary

@sobitneupane owed $500 - needs to request through NewDot (manual requests)
@suneox needs $500 from upwork.

**Comment by zanyrenney** [comment] 2024-05-07 11:31
@suneox I can't find you on upwork. 
![2024-05-07_12-30-36](https://github.com/Expensify/App/assets/56830058/ecefcc51-cf28-4fef-b560-efc6f57ddcfd)

![2024-05-07_12-30-52](https://github.com/Expensify/App/assets/56830058/5326cfdc-5b64-4d6a-8979-938065f5c7fd)

Please can you manually apply to the job? https://www.upwork.com/jobs/~01386bcc6b2c6f0fdf

Feel free to DM me in slack when you have and i'll process the payment ASAP.

**Comment by zanyrenney** [comment] 2024-05-07 11:37
Invited, please accept !

**Comment by zanyrenney** [comment] 2024-05-07 14:01
payment summary

@sobitneupane owed $500 - needs to request through NewDot (manual requests)
@suneox PAID $500 from upwork.

**Closed by zanyrenney** 2024-05-07 14:01 UTC
Labels: Engineering, Daily, Internal, Design, Bug

**Comment by JmillsExpensify** [comment] 2024-05-12 19:04
$500 approved for @sobitneupane
