### ISSUE TITLE
[$1000] Web -  Account B's reactions on tasks assigned to self by account A are not dynamically updating on account A

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#22594] opened 2023-07-10 21:38 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. On account A  go inside chat with account B
2. Click on Plus inside composer > assign task > give a title > click next
3. Click on assignee and select self (Account A) > create task
4. Go back to the chat with account B page
5. On account B hover over the last created task and react on it
6. Observe if the reactions are showing up on account A

## Expected Result:
Reactions from account B should show up on account A as well without any further actions

## Actual Result:
Reactions from account B are not being dynamically visible on account A. The reactions appear if only account A reloads the page, switches chat and comes back or reacts on the task.

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [x] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 1.3.37-2
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/93399543/975a230d-8729-4d43-9cfa-e69ef5ec99b7

https://github.com/Expensify/App/assets/93399543/a2c9207e-ab81-4d28-89d3-378d43b30256

**Expensify/Expensify Issue URL:**
**Issue reported by:** @Nathan-Mulugeta
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1688629159314669

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~016254cf6ea7a843f1</li>
        <li>Upwork Job ID: 1678554889064214528</li>
        <li>Last Price Increase: 2023-07-11</li>
    </ul>
</details>

**Comment by StevenKKC** [comment] 2023-07-11 07:27
This seems to be the BE issue. BE does not push events.

And there is another BE issue.
If react on the task preview message, BE responds as below. But reaction is added successfully.
![Screenshot 2023-07-11 014709](https://github.com/Expensify/App/assets/131836113/75e9dcdd-7a7d-410b-b885-d8fa6f97abb4)

**Comment by adelekennedy** [comment] 2023-07-14 19:32
@allroundexperts I just tested and I still have to refresh on account A to see the reaction, moving to internal (I'm betting this is a known issue)

**Comment by adelekennedy** [comment] 2023-07-17 20:37
@allroundexperts I made this internal - but I think this must be related to something larger (but i can't easily find an exact issue or project) should we keep open or close for now?

**Comment by adelekennedy** [comment] 2023-07-24 02:34
@allroundexperts do you have an idea what larger issue this might be related to?

**Comment by adelekennedy** [comment] 2023-07-27 03:49
This is still a problem but @allroundexperts but if we think the root cause is being worked on else where can we close?

**Closed** 2023-07-31 21:51 UTC
Labels: Engineering, Daily, Internal, Overdue, Bug
