### ISSUE TITLE
[HOLD for payment 2024-07-02] Web - Book travel - There is hover effect on "Save money on ..." and "Get realtime updates.."

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#44211] opened 2024-06-22 14:43 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 9.0.1-0
**Reproducible in staging?:** Y
**Reproducible in production?:** N 
**If this was caught during regression testing, add the test name, ID and link from TestRail:** https://expensify.testrail.io/index.php?/tests/view/4661870
**Issue reported by:** Applause - Internal Team

## Action Performed:
1. Go to staging.new.expensify.com
2. Go to FAB > Book travel
3. Hover over "Save money on your bookings" and "Get realtime updates and alerts"

## Expected Result:
There will be no hover effect on "Save money on your bookings" and "Get realtime updates and alerts" (production behavior)

## Actual Result:
There is hover effect on "Save money on your bookings" and "Get realtime updates and alerts"

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details> 

https://github.com/Expensify/App/assets/78819774/655bed1e-4483-416b-b9ae-12f251bcfcee

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by rojiphil** [comment] 2024-06-23 17:09
Thanks all for the help here by tagging the offending PR and sharing the insights on the issue. 
Fixing this issue here at #44219 since this is a regression from #43987 
cc @MonilBhavsar

**Comment by luacmartins** [comment] 2024-07-02 19:35
Payment will be handled in https://github.com/Expensify/App/issues/41901. Closing.

**Closed by luacmartins** 2024-07-02 19:35 UTC
Labels: Engineering, Daily, Awaiting Payment
