### ISSUE TITLE
When video is received/sent LHN shows weirdly with video name and poor formatting

### ISSUE THREAD

**Issue by m-natarajan** [Expensify/App#40611] opened 2024-04-19 20:02 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.63-11
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** @flodnv 
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1713551402236749

## Action Performed:
1. Send a video attachment from A to B
2. Look at the LHN as account B

## Expected Result:
LHN should say "Attachment" 
## Actual Result:
`[Attachment] videofilename </video>`
## Workaround:
unknown
## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence
![Screen Shot 2024-04-19 at 3 57 24 PM](https://github.com/Expensify/App/assets/38435837/abf22a52-d709-4499-beb5-6b3462fdcc79)

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~018cfc601c7773bc90</li>
        <li>Upwork Job ID: 1782396509672038400</li>
        <li>Last Price Increase: 2024-04-22</li>
    </ul>
</details>

**Comment by ahmedGaber93** [comment] 2024-04-20 10:12
I think this is a backend issue.
`api/AddAttachment` return `"lastMessageText": "[Attachment]video.mp4<\/video>"`
![Screenshot 2024-04-20 at 12 08 13 PM](https://github.com/Expensify/App/assets/41129870/291f747f-0351-43a5-a7e1-72708b02458c)

**Comment by tgolen** [comment] 2024-04-22 15:26
I think I know where this can be fixed and I might be able to get to it this week.

**Comment by tgolen** [comment] 2024-04-22 18:57
# Daily Update
- I found quite a few unit tests on the backend that are covering `<video>` tags, so I'm not quite sure what the cause of this bug is.

### Next Steps
- @tgolen Dig into the problem more to understand what's happening

#### ETA
- Have a fix deployed by Friday, May 3

**Comment by tgolen** [comment] 2024-04-24 11:31
# Weekly Update
- I submitted an [Auth PR](https://github.com/Expensify/Auth/pull/10650) with a fix for this

### Next Steps
- @techievivek will review and merge the PR
- PR will get deployed

#### ETA
- PR merged and deployed by Friday, April 26

**Comment by tgolen** [comment] 2024-05-03 13:54
This is fixed and this issue can be closed.

**Closed by tgolen** 2024-05-03 13:54 UTC
Labels: Reviewing, Weekly, Internal, Bug
