### ISSUE TITLE
[$500] Task – Deleted task in a Room not disappears from 1:1 DM and Task name is visible in LHN.

### ISSUE THREAD

**Issue by izarutskaya** [Expensify/App#33749] opened 2023-12-29 11:22 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.19-0
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** Applause-Internal Team
**Slack conversation:** @

## Action Performed:
1. Go to https://staging.new.expensify.com/
2. Log in with any account.
3. Create a task in the Room
4. Log is as another participant of the Room
5. Open the Task in the Room and canceled it
6. Navigate to the 1:1 DM with Task creator

## Expected Result:
Deleted task in a Room disappears from 1:1 DM and Task name is not visible in LHN when Canceled Task as Room user

## Actual Result:
Deleted task in a Room not disappears from 1:1 DM and Task name is visible in LHN when Canceled Task as Room user

## Workaround:
Can the user still use Expensify without this being fixed? Have you informed them of the workaround?

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [x] Android: mWeb Chrome
- [x] iOS: Native
- [x] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

https://github.com/Expensify/App/assets/115492554/3610a08b-b53a-4fe7-b928-12afbd14cb64

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~015bc9d71fb41f159d</li>
        <li>Upwork Job ID: 1740694664378986496</li>
        <li>Last Price Increase: 2024-01-05</li>
    </ul>
</details>

**Comment by FitseTLT** [comment] 2023-12-29 11:37
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
 Deleted task in a Room not disappears from 1:1 DM and Task name is visible in LHN.

### What is the root cause of that problem?
We are currently setting the lastMessage to the last message of the parent report here
https://github.com/Expensify/App/blob/7d1b0f8b99616c48aedb975dd73fc3086c9f20e3/src/libs/actions/Task.js#L757-L758
### What changes do you think we should make in order to solve the problem?

There is a backend job required but for the optimistic data. We should change lastMessage  to `task deleted task title`

https://github.com/Expensify/App/blob/7d1b0f8b99616c48aedb975dd73fc3086c9f20e3/src/libs/actions/Task.js#L757-L758
to 
```
lastMessageText: message
```
as we did here
https://github.com/Expensify/App/blob/7d1b0f8b99616c48aedb975dd73fc3086c9f20e3/src/libs/actions/Task.js#L748-L749
### What alternative solutions did you explore? (Optional)

**Comment by skydragon0324** [comment] 2023-12-29 14:53
I just read your issue
I think this issue is very simple
If you click cancel button, this action dispatch the event that the status of task would changed as delected
And on frontend  side, it doesn't display tasks that the status is delected, so, If you want to see the deleted tasks, you can change code so that shows delete tasks.

**Comment by namhihi237** [comment] 2023-12-29 16:16
I think backend issue, we do not push delete the message in the reportAction.

**Comment by MitchExpensify** [comment] 2023-12-31 01:55
Is this #vip-split worthy @GabiHExpensify ?

**Comment by MitchExpensify** [comment] 2024-01-04 21:38
Friendly bump @GabiHExpensify 🙇

**Comment by MitchExpensify** [comment] 2024-01-08 23:42
Closing as non-urgent and not clearly tied to a wave at this point

**Closed by MitchExpensify** 2024-01-08 23:42 UTC
Labels: External, Daily, Help Wanted, Overdue, Bug
