### ISSUE TITLE
[HOLD for payment 2023-09-27] [$500] Web - Request Money – The user proceeds to next section on clicking in empty space next to container.

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#26582] opened 2023-09-02 21:10 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Click FAB (Plus sign).
2. Select the "Request Money" option.
3. Enter the desired amount and click on the "Next" button.
4. Choose the user with whom the money request will be made.
5. Click on the "Request" button.
6. This action will cause an IOU container to appear in the relevant chat.
7. It can be observed that clicking on the empty space on the right side of the container also triggers the user to proceed to the next section.

## Expected Result:
The user should only be able to proceed to the next section after clicking directly on the container.

## Actual Result:
The user is able to proceed to the next section by clicking on the empty space next to the container.

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [x] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 1.3.62.0
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/93399543/80e8fb5d-2aad-4384-b6f4-82cd76d9ef9f

https://github.com/Expensify/App/assets/93399543/be6b7648-7150-402b-95f7-197aaadf5fc6

**Expensify/Expensify Issue URL:**
**Issue reported by:** @usmantariq96
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1693281334993079

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~0186657d1865495449</li>
        <li>Upwork Job ID: 1699022151071711232</li>
        <li>Last Price Increase: 2023-09-12</li>
<li>Automatic offers: </li>
<ul>
<li>getusha | Contributor | 26635253</li>
</ul></li>
    </ul>
</details>

**Comment by eVoloshchak** [comment] 2023-09-10 15:13
I think we can proceed with @getusha's [proposal](https://github.com/Expensify/App/issues/26582#issuecomment-1706501770), the fix is straignt-forward and tests well

🎀👀🎀 C+ reviewed!

**Comment by grgia** [comment] 2023-09-12 16:51
Assigned, thank you!

**Comment by getusha** [comment] 2023-09-12 20:06
@eVoloshchak based on [this](https://github.com/Expensify/App/issues/26582#issuecomment-1706501770) comment i think we also have to fix it for any defined container, which makes us apply the fix on `ReportPreview` too, it will work fine on `MoneyRequestPreview`, but noticed weird bug on iOS native where the contents inside the container won't appear. so i updated my [proposal](https://github.com/Expensify/App/issues/26582#issuecomment-1706501770) which applies for all defined containers (Solution 2). what do you think?

**Comment by getusha** [comment] 2023-09-14 18:44
@eVoloshchak @grgia raised the [PR](https://github.com/Expensify/App/pull/27465)!

**Comment by getusha** [comment] 2023-09-18 17:12
@eVoloshchak @grgia i raise a PR fixing the above regression https://github.com/Expensify/App/issues/27684

**Comment by MitchExpensify** [comment] 2023-09-20 23:42
Set a reminder to pay on 09/27. Based on [this regression](https://github.com/Expensify/App/issues/26582#issuecomment-1723625762), I believe this to be the payment summary but let me know if I'm mistaken:

**Payment summary:**

Reporter: $250 Upwork @usmantariq96
C: $500 Upwork @getusha 
C+: 500 NewDot @eVoloshchak

**Comment by eVoloshchak** [comment] 2023-09-21 10:56
@MitchExpensify, wasn't this originally $500? In that case regression would knock it down to $250

**Comment by MitchExpensify** [comment] 2023-09-21 18:57
Ah yes! The fairly recent change in pricing caught me. Thanks for the assist @eVoloshchak

**Comment by getusha** [comment] 2023-09-21 19:21
>If a PR causes a regression at any point within the regression period (starting when the code is merged and ending 168 hours (that's 7 days) after being deployed to production):

@MitchExpensify Based on the guidelines will the penalty apply to regressions before being deployed to production?

**Comment by MitchExpensify** [comment] 2023-09-21 19:23
Looks like its after being deployed to production based on the Guidelines you've shared @getusha

**Comment by MitchExpensify** [comment] 2023-09-21 19:24
Yes it appears so based on the Guidelines you shared

**Comment by eVoloshchak** [comment] 2023-09-28 11:37
- The PR that introduced the bug has been identified. Link to the PR: I'm unable to pinpoint the exact PR that caused this. _Looks like_  that's how it was implemented initially in https://github.com/Expensify/App/pull/3541, but the PR is over 2 years old, I can't verify that 
- The offending PR has been commented on, pointing out the bug it caused and why, so the author and reviewers can learn from the mistake. Link to comment: N/A
- A discussion in #expensify-bugs has been started about whether any other steps should be taken (e.g. updating the PR review checklist) in order to catch this type of bug sooner. Link to discussion: It's a fairly simple bug, I don't think an additional discussion is needed
- Determine if we should create a regression test for this bug.
Is it easy to test for this bug? Yes
Is the bug related to an important user flow? No
Is it an impactful bug? No
The bug has a very low impact, doesn't prevent user from using the app, I don't think a regression test is needed here

**Comment by MitchExpensify** [comment] 2023-09-29 05:26
**Payment summary**:

Reporter: $250 Upwork @usmantariq96 - Please accept the Upwork off I just sent, thank you! 
C: $250 Upwork @getusha - PAID 
C+: $250 NewDot @eVoloshchak

**Comment by usmantariq96** [comment] 2023-09-29 05:30
@MitchExpensify offer accepted
Thanks

**Comment by MitchExpensify** [comment] 2023-09-29 07:13
Paid and contract ended! Closing out as @eVoloshchak will receive payment via NewDot money request

**Closed by MitchExpensify** 2023-09-29 07:13 UTC
Labels: External, Daily, Awaiting Payment, Bug

**Comment by JmillsExpensify** [comment] 2023-10-01 02:14
$250 payment for @eVoloshchak approved based on BZ summary.
