### ISSUE TITLE
Marked as unread line appears at the just above textinput

### ISSUE THREAD

**Issue by kavimuru** [Expensify/App#20645] opened 2023-06-13 01:44 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Open a chat
2. Send a message
3. Mark it as unread
4. Delete it
## Expected Result: 
The deleted message should be removed entirely
## Actual Result: 
The message disappears but a line with 'New' appears

## Workaround:
Can the user still use Expensify without this being fixed? Have you informed them of the workaround?

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [x] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 1.3.26-4
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation
[Deleted message unread complexity.webm](https://github.com/Expensify/App/assets/43996225/747c06c2-853d-4a79-ace0-bcc0d8626bd2)

https://github.com/Expensify/App/assets/43996225/f073d5a0-631c-431d-adc1-f9e5621d2581

**Expensify/Expensify Issue URL:**
**Issue reported by:** @Habtamu-Asefa
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1686161175554749

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by ahmedGaber93** [comment] 2023-06-13 06:26
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
Marked as unread line appears at the just above textinput
### What is the root cause of that problem?
There is no case to hide `UnreadActionIndicator` when item deleted.
### What changes do you think we should make in order to solve the problem?
Hide `UnreadActionIndicator` when item deleted
```javascript
const isDeleted = lodashGet(props.action, 'message.isDeletedParentAction', false);


{!isDeleted && props.shouldDisplayNewMarker && <UnreadActionIndicator reportActionID={props.action.reportActionID} />}
```


### What alternative solutions did you explore? (Optional)

**Comment by NicMendonca** [comment] 2023-06-13 13:48
Thank you @dukenv0307 for your input! I agree this doesn't stand out as a bug to me.

**Closed by NicMendonca** 2023-06-13 13:48 UTC
Labels: Daily, Bug
