### ISSUE TITLE
[$500] [Wave 6: Tags] Expense - Selected subcategory shows different view in Tag & Category

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#32489] opened 2023-12-05 15:35 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.8-0
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** Applause - Internal Team
**Slack conversation:**

## Action Performed:
Precondition: The workspace chat has some tags in Parent: Child format
1. Go to workspace chat
2. Click + > Request money > Manual
3. Enter amount > Continue
4. Click Show more > Tag
5. Select a subcategory
6. Click Tag
7. Repeat Step 1 to 6 with Category

## Expected Result:
The selected subcategory will show the same view in Tag and Category

## Actual Result:
The selected subcategory does not show the same view in Tag and Category
For Tag, the selected subcategory is in hierarchy order
For Category, the selected subcategory is in Parent: Child format

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [x] Android: mWeb Chrome
- [x] iOS: Native
- [x] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details> 

https://github.com/Expensify/App/assets/78819774/fa328d78-6a86-4d1d-98f3-d454a5bb69d7

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~019f4d74182e84937e</li>
        <li>Upwork Job ID: 1732061052657393664</li>
        <li>Last Price Increase: 2023-12-12</li>
    </ul>
</details>

**Comment by happy-devs** [comment] 2023-12-05 15:53
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
When requesting money manually, the list options for Tags and Categories do use a uniform format for displaying selected subcategories.

### What is the root cause of that problem?
The file `OptionsListUtils` has to be changed to fix the rendering of child and parent for tags.

### What changes do you think we should make in order to solve the problem?

Update the `OptionsListUtils` functions to ensure that both Tags and Categories use the same format. 

### What alternative solutions did you explore? (Optional)

**Reminder:** Please use plain English, be brief and avoid jargon. Feel free to use images, charts or pseudo-code if necessary. Do not post large multi-line diffs or write walls of text. Do not create PRs unless you have been hired for this job.

**Comment by c3024** [comment] 2023-12-05 15:55
## Proposal
### Please re-state the problem that we are trying to solve in this issue.
Selected subcateogry shows differently in Category and Tag.
### What is the root cause of that problem?
We are passing `true` here for `isOneLine`
https://github.com/Expensify/App/blob/d77121b39c2a4c4f70e4293248cd98f115cc125a/src/libs/OptionsListUtils.js#L840
so it is shown in one line whereas for tags we use no flag so the default flag is `false`

### What changes do you think we should make in order to solve the problem?
We should remove the flag for `isOneLine` here if we want to show it in hierarchical view
https://github.com/Expensify/App/blob/d77121b39c2a4c4f70e4293248cd98f115cc125a/src/libs/OptionsListUtils.js#L840
### What alternative solutions did you explore? (Optional)
<details>
<summary>Result</summary>



</details>

**Comment by shahinyan11** [comment] 2023-12-05 16:07
@lanitochka17 I don't see anything after the category. Could you tell me what I did wrong?
![Screenshot 2023-12-05 at 20 04 53](https://github.com/Expensify/App/assets/46921547/f0b34188-768c-4b4c-a09e-4a9225d96799)

**Comment by shahinyan11** [comment] 2023-12-05 16:11
@lanitochka17 @c3024 @tienifr @happy-devs I don't see anything after the category. Could you tell me what I did wrong?
![Screenshot 2023-12-05 at 20 04 53](https://github.com/Expensify/App/assets/46921547/f8156189-53d8-4adf-960a-5af50b720833)

**Comment by happy-devs** [comment] 2023-12-05 16:11
@shahinyan11 looks like this is only in the dev environment, not the https://new.expensify.com portal

**Comment by c3024** [comment] 2023-12-05 16:13
Please follow [this](https://github.com/Expensify/App/pull/28151#issuecomment-1736543304).

**Comment by FitseTLT** [comment] 2023-12-06 09:10
already [fixed](https://github.com/Expensify/App/pull/32337)

**Comment by CortneyOfstad** [comment] 2023-12-08 16:27
@thesahindia can you confirm if this was fixed via the linked PR above? TIA!

**Comment by CortneyOfstad** [comment] 2023-12-11 15:58
Bump @thesahindia ^^^ Thanks!

**Comment by kbecciv** [comment] 2023-12-14 14:00
@CortneyOfstad Issue is still reproducible

https://github.com/Expensify/App/assets/93399543/64984879-21a2-4cdf-a03d-3e04d3cf6c2a

**Comment by CortneyOfstad** [comment] 2023-12-14 17:21
Thanks @kbecciv! Will keep this open while we wait for proposals!

**Comment by rezkiy37** [comment] 2023-12-19 13:42
Hi, I’m Michael (Mykhailo) from Callstack and I would like to work on this issue.

**Comment by CortneyOfstad** [comment] 2023-12-19 13:57
confirmed here that the features are actually working as designed. The tags do not interact the same as the categories in this instance, so the issue can be closed 👍

**Closed by CortneyOfstad** 2023-12-19 13:57 UTC
Labels: External, Daily, Help Wanted, Overdue, Bug
