### ISSUE TITLE
[$250] Track expense - App shows skeleton when saving track expense edit for the second time onward

### ISSUE THREAD

**Issue by izarutskaya** [Expensify/App#40862] opened 2024-04-24 10:37 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.65-0
**Reproducible in staging?:** Y
**Reproducible in production?:** N
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Issue reported by:** Applause-Internal team

## Action Performed:
1. Go to staging.new.expensify.com
2. Go to FAB > Track expense.
3. Track a manual expense to self.
4. Go to transaction thread.
5. Click Amount.
6. Edit the amount and save it.
7. Click Amount.
8. Edit the amount and save it.

## Expected Result:
App will not show skeleton when saving track expense edit for the second time.

## Actual Result:
App shows skeleton when saving track expense edit for the second time onward.

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

https://github.com/Expensify/App/assets/115492554/f16ac6b0-17e1-4aa1-8e0f-e1b630a066e0

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01072100fbd6058c80</li>
        <li>Upwork Job ID: 1783235013921456128</li>
        <li>Last Price Increase: 2024-05-01</li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @thienlnam</details>

**Comment by izarutskaya** [comment] 2024-04-24 10:38
@bfitzexpensify I haven't added the External label as I wasn't 100% sure about this issue. Please take a look and add the label if you agree it's a bug and can be handled by external contributors.

**Comment by izarutskaya** [comment] 2024-04-24 10:38
We think this issue might be related to the #vip-vsb.

**Comment by izarutskaya** [comment] 2024-04-24 10:38
Production 


https://github.com/Expensify/App/assets/115492554/89e37075-95e2-4aaf-8d10-fb74d9551886

**Comment by mountiny** [comment] 2024-04-24 10:48
Removing a blocker label as it does the work and user is not blocker and this is mainly ui issue cc @thienlnam

**Comment by mountiny** [comment] 2024-04-24 10:49
https://github.com/Expensify/App/pull/39956

**Comment by mountiny** [comment] 2024-04-24 10:49
@allroundexperts @shubham1206agra @s77rt this might be related to https://github.com/Expensify/App/pull/39956 your PR

**Comment by allroundexperts** [comment] 2024-04-24 11:14
This was a known issue that we discussed during PR review as well. @shubham1206agra mentioned that it was happening on prod as well.

**Comment by thienlnam** [comment] 2024-04-24 20:42
Yeah, we're not entirely sure why this is happening - going to open up externally so someone can investigate

**Comment by nkdengineer** [comment] 2024-04-25 06:33
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
App shows skeleton when saving track expense edit for the second time onward.

### What is the root cause of that problem?
When building the modified expense report action [here](https://github.com/Expensify/App/blob/d8e6990103092d241d582984302731905c6a5e8f/src/libs/ReportUtils.ts#L3896), we're not setting optimistic `previousReportActionID` to the `reportActionID` of the latest report action.

So when we get the continuous report action list [here](https://github.com/Expensify/App/blob/d8e6990103092d241d582984302731905c6a5e8f/src/libs/ReportActionsUtils.ts#L333), it fails to navigate further because `previousReportActionID` is empty and is not equal to the next report action.

So in [here](https://github.com/Expensify/App/blob/d8e6990103092d241d582984302731905c6a5e8f/src/pages/home/ReportScreen.tsx#L257) we're able to get only 1 report action which is the newly added modified expense, so `hasCreatedAction` [here](https://github.com/Expensify/App/blob/d8e6990103092d241d582984302731905c6a5e8f/src/pages/home/report/ReportActionsView.tsx#L238) will be false (even though we do have the created report action).

In [here](https://github.com/Expensify/App/blob/d8e6990103092d241d582984302731905c6a5e8f/src/pages/home/report/ReportActionsView.tsx#L320), we're checking `hasCreatedAction` in order to avoid calling `getOlderActions` unnecessarily. In this case `hasCreatedAction` is `false` so it will still trigger `getOlderActions`, leading to the Skeleton loading.

### What changes do you think we should make in order to solve the problem?

When building the modified expense report action [here](https://github.com/Expensify/App/blob/d8e6990103092d241d582984302731905c6a5e8f/src/libs/ReportUtils.ts#L3896), set the optimistic `previousReportActionID` to the `reportActionID` of the latest report action.

### What alternative solutions did you explore? (Optional)
NA

**Comment by nkdengineer** [comment] 2024-04-25 06:37
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
App shows skeleton when saving track expense edit for the second time onward.

### What is the root cause of that problem?
When building the modified expense report action [here](https://github.com/Expensify/App/blob/d8e6990103092d241d582984302731905c6a5e8f/src/libs/ReportUtils.ts#L3896), we're not setting optimistic `previousReportActionID` to the `reportActionID` of the latest report action.

So when we get the continuous report action list [here](https://github.com/Expensify/App/blob/d8e6990103092d241d582984302731905c6a5e8f/src/libs/ReportActionsUtils.ts#L333), it fails to navigate further because `previousReportActionID` is empty and is not equal to the next report action.

So in [here](https://github.com/Expensify/App/blob/d8e6990103092d241d582984302731905c6a5e8f/src/pages/home/ReportScreen.tsx#L257) we're able to get only 1 report action which is the newly added modified expense, so `hasCreatedAction` [here](https://github.com/Expensify/App/blob/d8e6990103092d241d582984302731905c6a5e8f/src/pages/home/report/ReportActionsView.tsx#L238) will be false (even though we do have the created report action).

In [here](https://github.com/Expensify/App/blob/d8e6990103092d241d582984302731905c6a5e8f/src/pages/home/report/ReportActionsView.tsx#L320), we're checking `hasCreatedAction` in order to avoid calling `getOlderActions` unnecessarily. In this case `hasCreatedAction` is `false` so it will still trigger `getOlderActions`, leading to the Skeleton loading.

### What changes do you think we should make in order to solve the problem?

When building the modified expense report action [here](https://github.com/Expensify/App/blob/d8e6990103092d241d582984302731905c6a5e8f/src/libs/ReportUtils.ts#L3896), set the optimistic `previousReportActionID` to the `reportActionID` of the latest report action.

### What alternative solutions did you explore? (Optional)
Above, we can optionally check other modified expense/system report action case to make sure the same issue doesn't happen.

Another solution:
[Here](https://github.com/Expensify/App/blob/d8e6990103092d241d582984302731905c6a5e8f/src/libs/ReportActionsUtils.ts#L308), early return the `sortedReportActions` if `id` is not provided. I think the continuous report action list retrieval is only relevant for linked comment case (where `id` will be provided). If it's not linked comment like in this case, we can just use the `sortedReportActions`.
```
if (!id) {
   return sortedReportActions;
}
```

**Comment by nkdengineer** [comment] 2024-04-26 16:19
IMO we should set it, optimistic data should be consistent with BE data, it's simple and fixes this issue well

**Comment by mananjadhav** [comment] 2024-04-27 17:44
> @thienlnam Maybe this is a BE issue, as we don't set previousReportActionID anywhere in FE.

@thienlnam Can you confirm this? Do we still fix this from FE.

**Comment by thienlnam** [comment] 2024-04-28 22:27
Yeah right now we don't modify previousReportActionID anywhere in the FE. I'm guessing this is because an optimistic and actual reportActionID do not correspond so we're always trying to load a previous reportActionID that doesn't exist.

 We should have a larger discussion about adding this in the FE to solve issues like this. We've talked about it briefly. This is also something that might not be a problem if we handled this correctly in the BE

**Comment by thienlnam** [comment] 2024-05-01 19:15
Going to make this internal now, unless we have a strong reason to start adding the previousReportActionID in the FE

**Comment by bfitzexpensify** [comment] 2024-05-07 15:34
@thienlnam is this one you're planning to handle yourself?

**Comment by thienlnam** [comment] 2024-05-08 19:31
Yeah though I'm currently working on some other track issues currently so going to demote this once since it's not blocking functionality or anything

**Comment by thienlnam** [comment] 2024-05-18 01:22
Same ^

**Comment by thienlnam** [comment] 2024-05-28 21:45
Just came back from OOO, this is lower on the list of priorities so probably not this week

**Comment by thienlnam** [comment] 2024-06-13 21:15
Same - not a priority at this time

**Comment by thienlnam** [comment] 2024-06-24 21:35
vip-vsb is paused, going to close this since we are reprioritizing

**Closed by thienlnam** 2024-06-24 21:35 UTC
Labels: Engineering, Weekly, Internal, Overdue, Bug

**Comment by nkdengineer** [comment] 2024-06-25 14:15
@thienlnam We have [a good solution](https://github.com/Expensify/App/issues/40862#issuecomment-2076472278) to fix in front-end, and we can do it now if you think it's acceptable.
