### ISSUE TITLE
[HOLD for payment 2024-11-01] [$500] Tags - Background report changes to Tags page after clicking Custom tag name in RHP

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#49883] opened 2024-09-28 14:38 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 9.0.41-2
**Reproducible in staging?:** Y
**Reproducible in production?:** N/A Unable to check
**If this was caught during regression testing, add the test name, ID and link from TestRail:** N/A
**Email or phone of affected tester (no customers):** applausetester+kh010901@applause.expensifail.com
**Issue reported by:** Applause - Internal Team

## Action Performed:
Precondition:
- User is logged in to two devices
- Workspace has tags
1. Go to staging.new.expensify.com
2. [Device A] Go to workspace chat
3. [Device A] Click + > Submit expense > Manual
4. [Device A] Proceed to confirmation page and click Tag
5. [Device B] Go to workspace settings > Tags
6. [Device B] Disable all tags
7. [Device A] Click Edit tags
8. [Device A] Click Settings > Custom tag name

## Expected Result:
The report in the background will remain after clicking Custom tag name

## Actual Result:
The report in the background changes to Tags page after clicking Custom tag name

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details> 

https://github.com/user-attachments/assets/ffdcd5fd-95ab-47fb-a28b-89238ffd7c5c

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~021840631550279932147</li>
        <li>Upwork Job ID: 1840631550279932147</li>
        <li>Last Price Increase: 2024-10-10</li>
<li>Automatic offers: </li>
<ul>
<li>paultsimura | Reviewer | 104272735</li>
</ul></li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @Christinadobrzyn</details>

**Comment by roryabraham** [comment] 2024-09-29 00:52
Looks pretty NAB to me

**Comment by NJ-2020** [comment] 2024-09-29 05:59
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
Tags - Background report changes to Tags page after clicking Custom tag name in RHP
### What is the root cause of that problem?
We're not passing the `backTo` param when navigating to the Custom tag name page
https://github.com/Expensify/App/blob/3047c1baa21f47825f5c1ffd652184341dd22256/src/pages/workspace/tags/WorkspaceTagsSettingsPage.tsx#L85
https://github.com/Expensify/App/blob/3047c1baa21f47825f5c1ffd652184341dd22256/src/ROUTES.ts#L847-L850
And same when navigating to the Settings page
https://github.com/Expensify/App/blob/3047c1baa21f47825f5c1ffd652184341dd22256/src/pages/workspace/tags/WorkspaceTagsPage.tsx#L174-L176
https://github.com/Expensify/App/blob/3047c1baa21f47825f5c1ffd652184341dd22256/src/ROUTES.ts#L843-L846
### What changes do you think we should make in order to solve the problem?
We can add the `backTo` param inside the getRoute function and pass the backTo param by using `route.params.backTo`
```tsx
WORKSPACE_TAGS_SETTINGS: {
    route: 'settings/workspaces/:policyID/tags/settings',
    getRoute: (policyID: string, backTo?: string) => getUrlWithBackToParam(`settings/workspaces/${policyID}/tags/settings` as const, backTo),
},
WORKSPACE_EDIT_TAGS: {
    route: 'settings/workspaces/:policyID/tags/:orderWeight/edit',
    getRoute: (policyID: string, orderWeight: number, backTo?: string) => getUrlWithBackToParam(`settings/workspaces/${policyID}/tags/${orderWeight}/edit` as const, backTo),
},
```
WorkspaceTagsPage.tsx when navigating to Settings page
```tsx
const backTo = route.params.backTo;
const navigateToTagsSettings = () => {
    Navigation.navigate(ROUTES.WORKSPACE_TAGS_SETTINGS.getRoute(policyID, backTo));
};

// ...types for route.params
[SCREENS.WORKSPACE.TAGS]: {
    policyID: string;
    backTo?: Routes;
};
```

And same for WorkspaceTagsSettingsPage when navigating to Custom tag name page
```tsx
<MenuItemWithTopDescription
    title={policyTagLists[0]?.name}
    description={translate(`workspace.tags.customTagName`)}
    onPress={() => Navigation.navigate(ROUTES.WORKSPACE_EDIT_TAGS.getRoute(policyID, policyTagLists[0].orderWeight, backTo))}
    shouldShowRightIcon
/>
```

### Result

https://github.com/user-attachments/assets/ace8973c-9aed-4812-93d5-a3b78291568b

### What alternative solutions did you explore? (Optional)

**Comment by Christinadobrzyn** [comment] 2024-09-30 02:57
What does `NAB` mean? I assume this is internal? @stitesExpensify

**Comment by NJ-2020** [comment] 2024-09-30 03:06
@Christinadobrzyn `NAB` stands for Not a blocker

**Comment by truph01** [comment] 2024-09-30 05:26
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
The report in the background changes to Tags page after clicking Custom tag name

### What is the root cause of that problem?
- We have logic to push a new full screen navigator to the stacks if the RHN is in FULL_SCREEN_TO_RHP_MAPPING list:

https://github.com/Expensify/App/blob/d18766580c7e35e439ff933f3097366e36c6ceca/src/libs/Navigation/linkingConfig/getAdaptedStateFromPath.ts#L146-L153

- When we click on "Custom tag name", the custom tag name screen is in FULL_SCREEN_TO_RHP_MAPPING:

https://github.com/Expensify/App/blob/d18766580c7e35e439ff933f3097366e36c6ceca/src/libs/Navigation/linkingConfig/FULL_SCREEN_TO_RHP_MAPPING.ts#L134

hence we push a new full screen navigator to stacks.
### What changes do you think we should make in order to solve the problem?
- In general, we should add a backTo param to the route when we click "Custom tag name". With this, in:

https://github.com/Expensify/App/blob/d18766580c7e35e439ff933f3097366e36c6ceca/src/libs/Navigation/linkingConfig/getAdaptedStateFromPath.ts#L112

logic:


https://github.com/Expensify/App/blob/d18766580c7e35e439ff933f3097366e36c6ceca/src/libs/Navigation/linkingConfig/getAdaptedStateFromPath.ts#L113-L114

is called instead of pushing a new full screen navigator to stacks:

https://github.com/Expensify/App/blob/d18766580c7e35e439ff933f3097366e36c6ceca/src/libs/Navigation/linkingConfig/getAdaptedStateFromPath.ts#L146-L147


- In detail:

- First, update the getRoute function so that it can receive the additional backTo param:

https://github.com/Expensify/App/blob/d18766580c7e35e439ff933f3097366e36c6ceca/src/ROUTES.ts#L843-L850

- Then, update:

https://github.com/Expensify/App/blob/d18766580c7e35e439ff933f3097366e36c6ceca/src/pages/workspace/tags/WorkspaceTagsPage.tsx#L175

```
    const navigateToTagsSettings = () => {
        Navigation.navigate(ROUTES.WORKSPACE_TAGS_SETTINGS.getRoute(policyID, Navigation.getActiveRoute()));
    };
```

and:

https://github.com/Expensify/App/blob/d18766580c7e35e439ff933f3097366e36c6ceca/src/pages/workspace/tags/WorkspaceTagsSettingsPage.tsx#L85

```
                        onPress={() => Navigation.navigate(ROUTES.WORKSPACE_EDIT_TAGS.getRoute(policyID, policyTagLists[0].orderWeight, Navigation.getActiveRoute()))}
```

It will add new backTo param to the route when we click "Custom tag name"


### What alternative solutions did you explore? (Optional)

**Comment by Christinadobrzyn** [comment] 2024-09-30 05:55
Ah thanks @NJ-2020! That makes sense. Given that, I think this can be external so adding the label.

**Comment by Christinadobrzyn** [comment] 2024-10-01 01:16
@paultsimura can you check out the proposals when you have a moment? TY!

**Comment by Christinadobrzyn** [comment] 2024-10-02 03:12
Thanks @paultsimura! Note for Melvin - we're reviewing proposals.

**Comment by stitesExpensify** [comment] 2024-10-10 17:37
Doubling bounty because we are fixing 2 extra bugs

**Comment by Christinadobrzyn** [comment] 2024-10-15 08:45
Just an update for melvin that we're working on the PRs

**Comment by Christinadobrzyn** [comment] 2024-10-22 06:16
PR in the works! https://github.com/Expensify/App/pull/50416

**Comment by Christinadobrzyn** [comment] 2024-11-01 02:07
@paultsimura Do we need a regression for this?

Payouts due:

- [ ] Contributor: $500 @twilight2294 (feel free to send a request to NewDot)
- [ ] Reviewer: $500 @paultsimura (Upwork offer - https://www.upwork.com/nx/wm/offer/104272735)

**Comment by Christinadobrzyn** [comment] 2024-11-01 05:31
Ah thanks for letting me know @twilight2294 - can you please accept the offer [here](https://www.upwork.com/nx/wm/offer/104689344)

**Comment by Christinadobrzyn** [comment] 2024-11-04 02:38
Regression test - https://github.com/Expensify/Expensify/issues/441268

Paid out based on payment summary - https://github.com/Expensify/App/issues/49883#issuecomment-2451158106

But I just checked and there was discussion after the PR went to production- is there a regression that we need to track for this? @twilight2294 @paultsimura

**Comment by Christinadobrzyn** [comment] 2024-11-05 03:04
hi @paultsimura thank you for the additional information. I think it sounds fair to keep the [payment as is](https://github.com/Expensify/App/issues/49883#issuecomment-2451158106). 

Closing this as complete!

**Closed by Christinadobrzyn** 2024-11-05 03:04 UTC
Labels: External, Engineering, Daily, Awaiting Payment, Bug
