### ISSUE TITLE
[HOLD for payment 2023-09-07] [$1000] Form Data Doesn't Save on Web Window Resize

### ISSUE THREAD

**Issue by kavimuru** [Expensify/App#20404] opened 2023-06-07 18:43 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:

Happens in multiple Form flows, but here is one for example

1. Go to Profile > Display Name
2. Change your name but don't save
3. Resize the window (either go from small to large or large to small)
## Expected Result: 

Information typed in any kind of From in the App should stay

## Actual Result: 

The input fields revert to how they were before you changed them.

## Workaround:
Can the user still use Expensify without this being fixed? Have you informed them of the workaround?

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [x] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 1.3.25-3
**Reproducible in staging?:** y
**Reproducible in production?:** n
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/43996225/a3368067-f706-4429-920f-a5817328ee5f

https://github.com/Expensify/App/assets/43996225/5d99ca7a-35d1-4c8b-81c8-3e06637d2731

**Expensify/Expensify Issue URL:**
**Issue reported by:** @dangrous 
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1686161807163249

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01119cc6f3de38a706</li>
        <li>Upwork Job ID: 1666786232588369920</li>
        <li>Last Price Increase: 2023-06-15</li>
    </ul>
</details>

**Comment by Pujan92** [comment] 2023-06-07 19:19
Seems [this line](https://github.com/Expensify/App/pull/16581/files#diff-c3d3bf8bc4056d8f2e8ff15f6d72d7e81656cd36c30a202a084c50dda1dff582R68) is causing this issue, bcoz when the `screenWidth` gets changed the `key` gets updated and it rerenders the component which eventually remounts `AuthScreens` component which calls `openApp` again and that is the problem.

**Comment by roryabraham** [comment] 2023-06-07 19:27
Interesting find @Pujan92

**Comment by roryabraham** [comment] 2023-06-07 21:59
Going to look into this.

**Comment by roryabraham** [comment] 2023-06-07 22:38
Got a fix for this one ready: https://github.com/Expensify/App/pull/20415

**Comment by roryabraham** [comment] 2023-06-07 22:43
Ok, so my fix works for one instance of the problem, but it would be nice to come up with a generalized solution that works everywhere.

**Comment by roryabraham** [comment] 2023-06-07 23:02
Chatted with @mountiny [in slack](https://expensify.slack.com/archives/C01GTK53T8Q/p1686163896688609) and we decided to slow down on this. Because it's an edge case we're going to take the time to fix it right w/ a generalized solution and not block deploys on it.

**Comment by mountiny** [comment] 2023-06-08 12:38
Made the External and updated the title and test cases to make it clear this does not happen only on one form.

The ideal solution should have some general approach to keeping the draft as the screen re-mount when we resize.

Its an edge case so I think we can take our time to find a good solution.

**Comment by mountiny** [comment] 2023-06-12 13:38
cc @adamgrzybowski @WoLewicki This is probably going to be a bigger discussion but important change after the refactor.

**Comment by adamgrzybowski** [comment] 2023-06-12 14:14
If I remember correctly were aware of the problem with the component state persistency with this architecture, but I can't find any threads where that was mentioned

I guess that the solution would be context above the navigation but it's a good idea to take our time and prepare possibly the least annoying solution for the people implementing new forms.

**Comment by mountiny** [comment] 2023-06-12 16:12
> If I remember correctly were aware of the problem with the component state persistency with this architecture, but I can't find any threads where that was mentioned

I know, I remember this as well, but it has been a while and it was mainly not a blocker for the v1 implementation but it does not mean we want to leave it like this.

> I guess that the solution would be context above the navigation but it's a good idea to take our time and prepare possibly the least annoying solution for the people implementing new forms.

Yep lets find some generalized solution which we can use in other pages without issues.

**Comment by mountiny** [comment] 2023-06-12 16:13
Assigning Adam to help Manan with proposals or to fix this himself before anyone created a good proposal, I will also update the issue OP to make sure we capture the more general aspect of the issue.

**Comment by roryabraham** [comment] 2023-06-13 02:53
Sorry for the lack of update from me. Looks like we're making this external and will start fielding proposals for a generic solution to maintain form state when the component unmounts + remounts, even for those forms where we don't want to save drafts if the form is intentionally closed + reopened.

**Comment by michaelhaxhiu** [comment] 2023-06-15 00:38
Yo @Nikhil-Vats called out a similarity and I agree. Should we fold #20529 into this job?

**Comment by Swor71** [comment] 2023-06-15 13:30
Hey, I'm Marcin from Callstack - expert contributor group - I would like to take a look at this issue

**Comment by mountiny** [comment] 2023-06-15 16:45
Hey @Swor71 Excited for your proposal. Please feel free to discuss it in Slack with us too and @WoLewicki

**Comment by adelekennedy** [comment] 2023-06-16 03:46
@Swor71 will you apply to the job [here](https://www.upwork.com/jobs/~01119cc6f3de38a706)?

**Comment by Swor71** [comment] 2023-06-16 08:04
> @Swor71 will you apply to the job [here](https://www.upwork.com/jobs/~01119cc6f3de38a706)?

hey, to my understanding this is not applicable to Callstack contributors

**Comment by mountiny** [comment] 2023-06-16 10:44
Correct, this is outside of Upwork

**Comment by Swor71** [comment] 2023-06-16 14:44
as for the daily update I can only say for now that I am currently investigating the issue and previous leads, trying to get more familiar with the app at the same time

**Comment by roryabraham** [comment] 2023-06-21 20:38
> We could reverse the logic so that it always saves the draft values per form but we'd have to invalidate the draft at some point, ideally on deliberate 'move away from the screen' action / pressing back (not sure if all the forms would fit that behaviour), since we cannot do it on unmount for the arch reasons

Yes, that's a more generalized version of the approach I was taking in https://github.com/Expensify/App/pull/20415 so sounds good to me 👍🏼

**Comment by Swor71** [comment] 2023-06-22 11:08
The main culprit behind this behaviour is the stack swap in `ResponsiveStackNavigator`, which to my mind should not really happen on the web, i.e. ideally this would be handled by proper styling and media queries. I've observed additional, potentially problematic area that this architecture poses as you can see in the vid:

https://github.com/Expensify/App/assets/32240132/59a51ed3-4c34-445d-a18b-57f8ad07da4f

So far I have been experimenting with various solutions but all of them feel very hacky due to the above. Even when inverting the logic and saving the draft values in Onyx the challenge is when to remove them. 
The easiest way would be to delegate this to the on back button press, however this is not handled in the `Form` component but rather the parent level. On the other hand to have this contained in the `Form` component would necessitate removing draft values on unmount, which coupled with checking for `touchedInputs` might be one way but due to the remount and the refs resetting it only works for one resize. I am currently checking if this could be handled on the url change somehow, again this is very hacky.

Out of curiosity, were there any talks of possibly redoing the arch decisions? I know this is beyond this ticket and in general is a massive undertaking but might prove beneficial in the long run.

**Comment by Swor71** [comment] 2023-06-23 12:37
daily update: I might've found a solution, currently in an internal proposal.

**Comment by mountiny** [comment] 2023-06-23 15:17
> Out of curiosity, were there any talks of possibly redoing the arch decisions? I know this is beyond this ticket and in general is a massive undertaking but might prove beneficial in the long run.

cc @WoLewicki @adamgrzybowski we have just went through a long project to implement this architecture. We might explore this in future, but not sure if now is the right time for it.

Curious to see your guys pov :D

**Comment by Swor71** [comment] 2023-06-26 11:12
## Proposal

### Please re-state the problem that we are trying to solve in this issue.

On the web, when entering a Form, filling in a field and resizing the window without saving the changes, the values disappear.

### What is the root cause of that problem?
The root of the problem is the stack swap in `ResponsiveStackNavigator`, which triggers on `isSmallScreenWidth` prop change. This causes the component to unmount and remount, effectively wiping the entered values. This arch decision has additional drawbacks like extra api calls, which you can observe in the vid provided in the comment [here](https://github.com/Expensify/App/issues/20404#issuecomment-1602452383). Ideally, this should be handled by proper styling and media queries.

### What changes do you think we should make in order to solve the problem?

The main change I suggest is to temporarily save the draft values to Onyx, per form, on input change, possibly debounced, and removing them in two instances - on submit form and pressing the back button / moving away from the screen, which essentially is unmounting the `Form` component. As simple as it sounds, one needs to remember that the ask is to contain this behaviour within Form component and the back button (`HeaderWithBackButton`) is usually the sibling of the `Form` component, which would delegate this to the parent component. 
Secondly, the stack swap on resizing the app is essentially an unmount, therefore to achieve the removal of draft values from Onyx only on deliberate ‘move-away-from-the-screen’ action I suggest adding an event listener to navigation, namely `beforeRemove`, which triggers on the screen change but the draft values will remain in Onyx between unmount → mount phases.

### What alternative solutions did you explore? (Optional)

I have tried various other approaches e.g. to remove the draft values based on `touchedInputs` refs, comparing the currently entered value with the saved one for the form and else. The remounted `Form` component had its default values and refs reset, which resulted in only one resize having its unsaved values in place.

**Reminder:** Please use plain English, be brief and avoid jargon. Feel free to use images, charts or pseudo-code if necessary. Do not post large multi-line diffs or write walls of text. Do not create PRs unless you have been hired for this job.

**Comment by esh-g** [comment] 2023-06-27 15:26
Here are some other issues that I think might be related to this:
- https://expensify.slack.com/archives/C049HHMV9SM/p1687867309909039
- https://github.com/Expensify/App/issues/21616

I think this is a major issue that needs to be fixed. Because components are getting remounted on resizing which really shouldn't happen and this can cause many unexpected issues in the future as well.

**Comment by situchan** [comment] 2023-06-27 15:28
@esh-g https://github.com/Expensify/App/pull/16581#discussion_r1243593268

**Comment by mananjadhav** [comment] 2023-06-27 15:48
@Swor71 I understand the need for storing these values in Onyx.  I wonder if we should be focusing on the form inputs here?  or also cases like [these](https://github.com/Expensify/App/issues/21616)

> temporarily save the draft values to Onyx, per form, on input change, possibly debounced, and removing them in two instances - on submit form and pressing the back button / moving away from the screen

Another clarification, if you could elaborate, are we expecting this change to be common and only restricted in `Form` or we also have some additional changes to be done in the components using the `Form`. Would the `beforeRemove` triggers be helpful when do we refreshes on the Forms?

**Comment by esh-g** [comment] 2023-06-27 16:22
> @esh-g https://github.com/Expensify/App/pull/16581#discussion_r1243593268

So I guess all solutions will have to work around the fact of the remounting, right? @situchan

**Comment by situchan** [comment] 2023-06-27 16:44
> > @esh-g [#16581 (comment)](https://github.com/Expensify/App/pull/16581#discussion_r1243593268)
> 
> So I guess all solutions will have to work around the fact of the remounting, right? @situchan

There seems no other solution for now given that these issues are less critical than bugs occur without remounting.

**Comment by Swor71** [comment] 2023-06-28 08:55
> @Swor71 I understand the need for storing these values in Onyx. I wonder if we should be focusing on the form inputs here? or also cases like [these](https://github.com/Expensify/App/issues/21616)
> 
> > temporarily save the draft values to Onyx, per form, on input change, possibly debounced, and removing them in two instances - on submit form and pressing the back button / moving away from the screen
> 
> Another clarification, if you could elaborate, are we expecting this change to be common and only restricted in `Form` or we also have some additional changes to be done in the components using the `Form`. Would the `beforeRemove` triggers be helpful when do we refreshes on the Forms?

@mananjadhav hey, I focused on solving the issue for the `Form` component because that is the ask of this issue. I do agree that it might be the case for other places in the app, however as shown in my research and what I documented in the comments above it is a much bigger problem that stems from architecture decisions. I believe that the solution I proposed can be a good place to start and we can move on from there but I'd like to separate the concerns even though they are somewhat related.

As to your second question, I aimed at keeping this behaviour contained within `Form` component and `onInputChange`. It's up to a discussion, if `shouldSaveDraft` prop should be removed altogether due to this change. I am not sure what you mean about `refreshes on the Forms`, could you elaborate please?

**Comment by Swor71** [comment] 2023-06-28 11:51
@roryabraham hey, tagging you as you've had a look at this issue previously and liked the initial idea, would you mind having a look at the proposal and giving your thoughts? thanks

**Comment by s77rt** [comment] 2023-06-28 20:18
Do we have a Slack thread for this one? Should we ignore similar issues for now?

**Comment by roryabraham** [comment] 2023-06-28 23:16
> Should we ignore similar issues for now?

Yes, I believe so.

**Comment by roryabraham** [comment] 2023-06-28 23:23
Posted in slack: https://expensify.slack.com/archives/C01GTK53T8Q/p1687994616930989

**Comment by WoLewicki** [comment] 2023-06-29 15:26
Commenting

**Comment by abdulrahuman5196** [comment] 2023-06-29 15:51
I think this is also one of the issue with same root cause - https://github.com/Expensify/App/issues/20929
What should we do on this? Should we close it or put in hold? I assume we are targeting a app wide solution.

**Comment by adelekennedy** [comment] 2023-07-05 20:19
On hold

**Comment by mountiny** [comment] 2023-07-07 18:54
PR for not remounting during resize is up in draft, exciting 🎉

**Comment by mountiny** [comment] 2023-08-06 17:55
The PR is sitll going through small issues found such as differences in css styles in various browsers as we need to use styles for the layout if we use only one navigator

**Comment by mountiny** [comment] 2023-08-31 21:07
Should be fixed on staging

**Comment by mananjadhav** [comment] 2023-09-07 18:43
@mountiny how do we handle the payout here? We've had multiple C+ reviewers.

**Comment by mountiny** [comment] 2023-09-08 09:02
@mananjadhav all of those who did full review should be paid here

**Comment by mananjadhav** [comment] 2023-09-08 09:39
Thanks for the confirmation @mountiny. @adelekennedy Can you post the payment summary here? @allroundexperts @aimane-chnaif are the other C+ members eligible for the payout.

**Comment by JmillsExpensify** [comment] 2023-09-10 11:45
Awaiting payment summary.

**Comment by adelekennedy** [comment] 2023-09-11 07:31
### Payouts due:

Issue Reporter: N/A
Contributor: N/A
Contributor+: $1000 @mananjadhav @allroundexperts @aimane-chnaif (NewDot) 

Eligible for 50% #urgency bonus? N

**Comment by JmillsExpensify** [comment] 2023-09-21 09:15
$1,000 payment approved for @mananjadhav based on BZ summary.

**Comment by mountiny** [comment] 2023-10-04 14:09
$100 to @aimane-chnaif in Upwork is that correct?

**Comment by JmillsExpensify** [comment] 2023-10-05 13:13
$1,000 payment approved for @allroundexperts based on BZ summary.

**Comment by adelekennedy** [comment] 2023-10-05 13:38
@aimane-chnaif - created payment issue [here](https://www.upwork.com/jobs/~0177b7b798a9062395)

**Comment by adelekennedy** [comment] 2023-10-09 04:01
payment made!

**Closed by adelekennedy** 2023-10-09 04:01 UTC
Labels: Reviewing, Engineering, Daily, Internal, Awaiting Payment, Bug
