### ISSUE TITLE
[TS migration] Create a `prefer-type-fest` ESLint rule

### ISSUE THREAD

**Issue by fabioh8010** [Expensify/App#41991] opened 2024-05-10 17:33 UTC
# Summary

Create a prefer-type-fest TS lint rule that identifies places where code can be made more readable by using type-fest utility types.

Context: https://expensify.slack.com/archives/C0593T50UHG/p1715356357600679

# Details

Example:

```tsx
/** Example: TupleToUnion */
const STUFF = ['a', 'b', 'c'] as const;

// BAD
type Bad = (typeof STUFF)[number];

// GOOD
type Good = TupleToUnion<typeof STUFF>;

/** Example: ValueOf */
const COLORS = {
    GREEN: 'green',
    BLUE: 'blue',
} as const;

// BAD
type Bad = (typeof COLORS)[keyof COLORS];

// GOOD
type Good = ValueOf<typeof COLORS>;
```

Let's brainstorm and check which patterns are most used in the App and could be replaced with `type-fest` types, and then create the rule covering those situations. @roryabraham @blazejkustra

**Comment by roryabraham** [comment] 2024-05-10 17:34
Making this a monthly as it's lower-priority. It's also not a bug but a new feature

**Comment by roryabraham** [comment] 2024-05-10 17:37
For now I'd propose just starting with these two:

- `ValueOf` because it's by far the most common one we use
- `TupleToUnion` because the vanilla TS syntax with `(typeof myArray)[number]` is just confusing (imo)

**Comment by roryabraham** [comment] 2024-05-29 22:22
@fabioh8010 you've got a few other things on your plate. Do you want to drop this one and open it up for the community?

**Comment by blazejkustra** [comment] 2024-06-03 09:06
I briefly discussed it with Fabio, and we would prefer to handle this internally so we can complete it quicker. Past TS follow-ups have shown that issues like this typically take longer when left to external contributors.

I should have some availability this week. @roryabraham please reassign the issue to me, and I'll begin working on it tomorrow.

**Comment by blazejkustra** [comment] 2024-06-05 18:04
Update: Today I had to wrap up my other PRs, I'm going to start this tomorrow.

**Comment by blazejkustra** [comment] 2024-06-06 16:34
Update: Rule is almost finished - [here](https://github.com/Expensify/eslint-config-expensify/pull/100) is a draft PR. There is one last edge case that I need to cover, should be ready tomorrow.

**Comment by blazejkustra** [comment] 2024-06-07 15:01
@roryabraham @fabioh8010 PR is ready for review

**Comment by roryabraham** [comment] 2024-06-07 18:06
reviewed, requested that we cover 1 missing case

**Comment by roryabraham** [comment] 2024-06-26 01:23
This is done. Thanks all!

**Closed by roryabraham** 2024-06-26 01:23 UTC
Labels: Reviewing, Weekly, NewFeature
