### ISSUE TITLE
[$500]  Room invite email coming from the workspace owner, not the user sending the invite

### ISSUE THREAD

**Issue by m-natarajan** [Expensify/App#32071] opened 2023-11-27 20:06 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.4-0
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** @MitchExpensify 
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1701114268200809

## Action Performed:

1. Create a free workspace with account A ([zach@expensify.com](mailto:zach@expensify.com))
2. Invite account B ([mitch@expensify.com](mailto:mitch@expensify.com)) to the free workspace
3. As account B, create a room tied to the workspace
4. As account B, Invite account C ([wardmi@tcd.ie](mailto:wardmi@tcd.ie)) to the workspace room via the room's Members pane

## Expected Result:
Email notification of the room invite should come from the person inviting (Account B in this example)

## Actual Result:
Email notification of the room invite comes from the workspace admin / owner (Account A in this example)

## Workaround:
unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

https://github.com/Expensify/App/assets/38435837/1e939fe2-adf8-4c50-bb05-7ead19faaba5

![image (3)](https://github.com/Expensify/App/assets/38435837/a46e00d4-c6e4-47dd-b195-f3c482aa21a9)

![image (2)](https://github.com/Expensify/App/assets/38435837/2b043827-5939-4d7f-b5d0-0f9f81478e92)

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01d60f5aaf2ad05081</li>
        <li>Upwork Job ID: 1729230219790970880</li>
        <li>Last Price Increase: 2023-11-27</li>
    </ul>
</details>

**Comment by david-richards-tech** [comment] 2023-11-27 21:35
IDEA: Use `userId` for the requesting user instead of group owner.

**Comment by david-richards-tech** [comment] 2023-11-27 21:38
Contributor details
Your Expensify account email: david.richards.tech@gmail.com
Upwork Profile Link: https://www.upwork.com/freelancers/~0130267f27102ba5b8

**Comment by Sergio16T** [comment] 2023-11-27 21:47
Proposal
Please re-state the problem that we are trying to solve in this issue.
Email notification of the room invite comes from the workspace admin / owner (Account A in this example)

**What is the root cause of that problem?**
Investigated the payload for   https://dev.new.expensify.com:8082/api?command=InviteToRoom

I verified the `actorAccountID` and the `lastActorAccountID` are the Account B in the example/the user sending the invitation. 
"actionName": "INVITETOROOM",
 "actorAccountID": 16067392,
 
 I also verified that that the recipient and member ID's included were correct for the payload. 
      
I verified the account ID via the signIn call to get the accountID. 

It appears that this is a backend bug.
   
What changes do you think we should make in order to solve the problem?
 Backend dev should construct email to show the FROM email based on the actorAccountID instead of the workspace account holder.

**Comment by alex-mcfadden** [comment] 2023-11-27 22:14
This is a backend issue - it needs to be changed so that the sender address is pulled from the actor, and not the owner. This repo is the incorrect repo to fix this issue.

**Comment by alex-mcfadden** [comment] 2023-11-27 22:15
Contributor details
Your Expensify account email: alexander.mcfadden@gmail.com
Upwork Profile Link: https://www.upwork.com/freelancers/~016eed7df5fd3d25d0

**Comment by kadiealexander** [comment] 2023-12-07 05:33
Posted about whether we should fix this here. https://expensify.slack.com/archives/C01SKUP7QR0/p1701927181913129?thread_ts=1701921998.495289&cid=C01SKUP7QR0

**Comment by kadiealexander** [comment] 2023-12-10 19:58
Closing as a dupe of https://github.com/Expensify/App/issues/30919, as discussed here. https://expensify.slack.com/archives/C066HJM2CAZ/p1702237889252039?thread_ts=1702005653.812799&cid=C066HJM2CAZ

**Closed by kadiealexander** 2023-12-10 19:58 UTC
Labels: Daily, Internal, Help Wanted, Bug
