### ISSUE TITLE
[$250] Chat – “Hmm... ” page appears briefly when navigate to IOU link while logout

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#45899] opened 2024-07-22 12:13 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 9.0.10-2
**Reproducible in staging?:** Y
**Reproducible in production?:** N
**If this was caught during regression testing, add the test name, ID and link from TestRail:** https://expensify.testrail.io/index.php?/tests/view/4751670
**Email or phone of affected tester (no customers):** ponikarchuks+920724@gmail.com
**Issue reported by:** Applause - Internal Team

## Action Performed:
Precondition: use slow 3G network
1. Go to https://staging.new.expensify.com/
2. Log in with Gmail account
3. Create a IOU in a conversation
4. Navigate to the IOU report (conversation)
5. Copy the URL
6. Log out of the app
7. Navigate to the IOU URL
8. Log in with the same account

## Expected Result:
You're redirected to the correct IOU report after login

## Actual Result:
“Hmm... it's not here” page appears briefly then IOU report opens

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details> 

https://github.com/user-attachments/assets/4caaef22-4376-48c7-9139-dede2ca9471e

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~0145c59ed1d52e3830</li>
        <li>Upwork Job ID: 1815367593322000546</li>
        <li>Last Price Increase: 2024-07-22</li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @abdulrahuman5196</details>

**Comment by lanitochka17** [comment] 2024-07-22 12:17
We think that this bug might be related to #vip-vsp

**Comment by mountiny** [comment] 2024-07-22 12:35
This seems to be a minor UX issue not blocking the user from using the app so I have demoted it.

Maybe its related to this navigation change https://github.com/Expensify/App/pull/44531 @Kicu in case you could look

**Comment by WojtekBoman** [comment] 2024-07-22 13:13
Hey! I’m Wojtek from Software Mansion, an expert agency, and I’d like to work on this issue.

**Comment by WojtekBoman** [comment] 2024-07-23 14:40
I took a look at it and I found a root cause of this issue.
I checked an old commit before merging [this PR](https://github.com/Expensify/App/pull/44531) and this issue still occured. It's connected with changes introduced in [this one](https://github.com/Expensify/App/pull/43307):

https://github.com/Expensify/App/blob/main/src/pages/home/ReportScreen.tsx#L449-L451

```
  const shouldShowNotFoundPage = useMemo((): boolean => {
        // Wait until we're sure the app is done loading (needs to be a strict equality check since it's undefined initially)
        if (isLoadingApp !== false) {
            return false;
        }

        // If we just finished loading the app, we still need to try fetching the report. Wait until that's done before
        // showing the Not Found page
        if (finishedLoadingApp) {
            return false;
        }

        if (!wasReportAccessibleRef.current && !firstRenderRef.current && !report.reportID && !isOptimisticDelete && !reportMetadata?.isLoadingInitialReportActions && !userLeavingStatus) {
            return true;
        }

        if (shouldHideReport) {
            return true;
        }
        return !!currentReportIDFormRoute && !ReportUtils.isValidReportIDFromPath(currentReportIDFormRoute);
    }, [isLoadingApp, finishedLoadingApp, report.reportID, isOptimisticDelete, reportMetadata?.isLoadingInitialReportActions, userLeavingStatus, shouldHideReport, currentReportIDFormRoute]);
```

This check returns true which causes showing the not found page:
```
        if (!wasReportAccessibleRef.current && !firstRenderRef.current && !report.reportID && !isOptimisticDelete && !reportMetadata?.isLoadingInitialReportActions && !userLeavingStatus) {
            return true;
        }
```

I'd like to make sure why it works this way. @arosiclair Could you take a look at it?

https://github.com/user-attachments/assets/11d0fc91-e613-4761-97b8-184a1d30652f

**Comment by arosiclair** [comment] 2024-07-23 18:25
> I'd like to make sure why it works this way. @arosiclair Could you take a look at it?

Unfortunately I don't really know what those checks are for I just moved them 😅. From what I can guess, it is checking if `report` is empty but with many caveats like if the report is being loaded for the first time (`reportMetadata?.isLoadingInitialReportActions`).

**Comment by mvtglobally** [comment] 2024-08-23 12:06
Issue not reproducible during KI retests. (First week)

**Comment by abdulrahuman5196** [comment] 2024-09-02 19:35
@madmax330 I think we can close this issue.
Reference: https://github.com/Expensify/App/pull/46112#issuecomment-2270697233
>This issue should already be resolved, I see that Report Screen has been migrated to use useOnyx in this https://github.com/Expensify/App/pull/45711. If this error no longer appears, I'll close this PR. Could you check if it works for you on the main branch?

And issue is not reproducible anymore.

**Comment by mvtglobally** [comment] 2024-09-09 04:10
Issue not reproducible during KI retests. (Second week)

**Comment by mvtglobally** [comment] 2024-09-13 16:38
Issue not reproducible during KI retests. (Third week)

**Comment by mvtglobally** [comment] 2024-09-21 04:24
Issue not reproducible during KI retests. (4th week)

**Comment by abdulrahuman5196** [comment] 2024-09-23 16:21
@madmax330 I think we can close this issue

**Comment by mallenexpensify** [comment] 2024-10-03 18:30
Thanks for posting in #contributor-plus @abdulrahuman5196 , closing

**Closed by mallenexpensify** 2024-10-03 18:30 UTC
Labels: Reviewing, External, Engineering, Monthly, Help Wanted
