### ISSUE TITLE
[HOLD for payment 2023-07-26] dev: There is no consistency between the input field to enter task title and edit task title

### ISSUE THREAD

**Issue by kavimuru** [Expensify/App#22495] opened 2023-07-08 18:46 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Open a chat
2. Click + in composer => assign task
3. Input title, Observe that it is not possible to enter multiple lines here
4. Next => Confirm
5. Click on task title
6. Edit title, Observe that multiple lines can be entered here
## Expected Result: 
There must be consistency between the creation and editing of the input task title box
## Actual Result: 
no consistency between the input field to enter task title and edit task title

## Workaround:
Can the user still use Expensify without this being fixed? Have you informed them of the workaround?

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [x] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** dev only
**Reproducible in staging?:** n/a
**Reproducible in production?:** n/a
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/43996225/9608b703-0433-441b-a025-c5950caf7754

**Expensify/Expensify Issue URL:**
**Issue reported by:** @namhihi237 
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1688814642406699

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~0118c6f4fd728fc15b</li>
        <li>Upwork Job ID: 1678580224333312000</li>
        <li>Last Price Increase: 2023-07-11</li>
    </ul>
</details>

**Comment by kavimuru** [comment] 2023-07-08 18:46
## Proposal
### Please re-state the problem that we are trying to solve in this issue.
There must be consistency between the creation and editing of the input task title box
### What is the root cause of that problem?
Here we have the difference between input title at create task and edit title:
Create:
https://github.com/Expensify/App/blob/60f48175c9e3342ef192d878218820e5ed5a76cd/src/pages/tasks/NewTaskDetailsPage.js#L93-L100
Edit:
https://github.com/Expensify/App/blob/60f48175c9e3342ef192d878218820e5ed5a76cd/src/pages/tasks/TaskTitlePage.js#L77-L86
Easy to see the difference here is the screen `TaskTitlePage` we allow `autoGrowHeight`.
### What changes do you think we should make in order to solve the problem?
We should remove `autoGrow Height` from `autoGrowHeight`
```javascript
                    <TextInput
                        inputID="title"
                        name="title"
                        textAlignVertical="top"
                        label={props.translate('task.title')}
                        defaultValue={(props.report && props.report.reportName) || ''}
                        ref={(el) => (inputRef.current = el)}
                    />
```
### What alternative solutions did you explore? (Optional)

**Comment by gadhiyamanan** [comment] 2023-07-08 18:46
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
title filed is multiline filed while editing title
### What is the root cause of that problem?
Tilte filed is multiline filed
### What changes do you think we should make in order to solve the problem?
remove the `autoGrowHeight` prop from `TaskTitlePage.js` also remove unnecessary prop `textAlignVertical="top”` https://github.com/Expensify/App/blob/60f48175c9e3342ef192d878218820e5ed5a76cd/src/pages/tasks/TaskTitlePage.js#L77-L86

**Comment by ahmedGaber93** [comment] 2023-07-08 19:50
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
There are two 2 issues in the video above.
1. the edited input is `autoGrowHeight` and there is no `submitOnEnter`.
2. (optional) the edited input autofocus make the cursor at the beginning.

### What is the root cause of that problem?
1. the edited input has prop `autoGrowHeight` and no prop `submitOnEnter` while is the only input on the screen.
2. (optional) the autofoucs make the cursor at the beginning, it is a known issue in react-native, and similar issue in fixed in task description input.
### What changes do you think we should make in order to solve the problem?
1. remove prop `autoGrowHeight` and prop `submitOnEnter` here.
https://github.com/Expensify/App/blob/60f48175c9e3342ef192d878218820e5ed5a76cd/src/pages/tasks/TaskTitlePage.js#L77

2. (optional) fix cursor issue in the video
```javascript
onEntryTransitionEnd={() => {
    if(inputRef.current){
        inputRef.current.focus();
        if (inputRef.current.value && inputRef.current.setSelectionRange) {
            const length = inputRef.current.value.length;
            inputRef.current.setSelectionRange(length, length);
        }
    }
}}
```
### What alternative solutions did you explore? (Optional)

**Comment by jasperhuangg** [comment] 2023-07-10 20:58
Happy to investigate/fix this. Thanks for the ping

**Comment by jasperhuangg** [comment] 2023-07-10 21:16
Tackling this internally

**Comment by gadhiyamanan** [comment] 2023-07-11 08:16
@laurenreidexpensify applied, thanks!

**Comment by stephanieelliott** [comment] 2023-07-19 08:17
PR was deployed to staging 👏

**Comment by stephanieelliott** [comment] 2023-07-28 21:35
@0xmiroslav can you please complete the BZ checklist? Once completed I can go on and issue payment.

**Comment by stephanieelliott** [comment] 2023-08-01 17:22
Thanks @namhihi237, I sent you the offer on Upwork! 
@0xmiroslav bump to complete the BZ checklist

**Comment by stephanieelliott** [comment] 2023-08-03 07:57
Summarizing payment on this issue: 
 - Issue reporter: @namhihi237 $250, paid via Upwork 
 - Contributor: N/A
 - Contributor+: @0xmiroslav $1000, to be paid via Upwork  - Held on completing BZ checklist 
 
 Upwork job is [here](https://www.upwork.com/jobs/~0118c6f4fd728fc15b), no bonus as this was an internal PR

**Comment by Santhosh-Sellavel** [comment] 2023-08-03 22:57
@stephanieelliott We can skip the checklist here and close this issue after paying reporting bonus.

cc: @jasperhuangg

**Comment by stephanieelliott** [comment] 2023-08-04 06:19
Thanks guys! Ok, updated the [payment summary](https://github.com/Expensify/App/issues/22495#issuecomment-1663473141), reporting bonus was paid out already so this one is all set

**Closed by stephanieelliott** 2023-08-04 06:19 UTC
Labels: Engineering, Daily, Internal, Awaiting Payment, Bug
