### ISSUE TITLE
 IOS- IOU- New IOU action is not added to the 1:1 DMs and No green badge  for any of the users

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#14590] opened 2023-01-26 14:01 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Issue found when executing PR** https://github.com/Expensify/App/pull/13118

## Action Performed:
1. Launch the app
2. Log i with new expensifail account
3. Split a bill with a group you've never created before.
4. Check if a new group chat is created with a CREATED action, an IOU action and the ADDCOMMENT action.
5. Check a new IOU action is added to the 1:1 DMs with each member of the group.

## Expected Result:
A new IOU action is added to the 1:1 DMs with each member of the group. And green badge is present for any of the users

## Actual Result:
New IOU action is not added to the 1:1 DM. No green badge for any of the user

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?

- [ ] iOS / native

**Version Number:** 1.2.59.1

**Reproducible in staging?:** Yes

**Reproducible in production?:** No

**If this was caught during regression testing, add the test name, ID and link from TestRail:**

**Email or phone of affected tester (no customers):**

**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Notes/Photos/Videos:** Any additional supporting documentation

https://user-images.githubusercontent.com/93399543/214854744-c0105849-a58e-499d-9241-1a26c10da222.mp4

**Expensify/Expensify Issue URL:**

**Issue reported by:** Applause - Internal Team

**Slack conversation:**

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by kbecciv** [comment] 2023-01-26 14:38
The same issue when Split Bill Offline .

**Comment by luacmartins** [comment] 2023-01-26 16:24
I'm not able to reproduce on dev.

**Comment by luacmartins** [comment] 2023-01-26 17:09
Creating the SplitBill request offline adds the summary and badge. It's when we go back online that they disappear. I see this in the [logs](https://www.expensify.com/_devportal/tools/logSearch/#query=request_id:(%2278fa9602abfc96cc-SJC%22)+AND+timestamp:%5B2023-01-26T15:22:12.567Z+TO+2023-01-26T17:22:12.567Z%5D&index=logs_expensify-020608) just now, which seems to be a problem with our API.

```
[OOPS!] API threw TypeError - 50450b563520aa892c003839a3ccaeac ~~ exceptionMessage: 'ReportUtils::notifyParticipants(): Argument #4 ($clientID) must be of type string, null given, called in /git/releases/expensify.com/b96822d/lib/ReportAPI.php on line 3975' exceptionFile: '/git/releases/expensify.com/b96822d/lib/ReportUtils.php' exceptionLine: '1939' exceptionCode: '0'
```

**Comment by luacmartins** [comment] 2023-01-26 17:47
More context [here](https://expensify.slack.com/archives/C04DC6LU2UB/p1674751976531329), but the issue happens because the fix is still in the staging API. It should be fixed after the next API deploy. Closing!

**Closed by luacmartins** 2023-01-26 17:47 UTC
Labels: Daily, Bug
