### ISSUE TITLE
[HOLD for payment 2024-02-07] [$500] Thread - Thread header in room shows skeleton loading when replying in thread offline

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#35090] opened 2024-01-24 18:57 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.31-2
**Reproducible in staging?:** Y
**Reproducible in production?:** N
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** Applause - Internal Team
**Slack conversation:**

## Action Performed:
1. Go offline
2. Go to a room like #admin room
3. Send a message
4. Right click on the message > Reply in thread
5. Repeat Step 1 to 4 with workspace chat

## Expected Result:
The thread header will not show skeleton loading

## Actual Result:
The thread header shows skeleton loading in room thread, but it displays fine in workspace chat thread

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [x] Android: mWeb Chrome
- [x] iOS: Native
- [x] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details> 

https://github.com/Expensify/App/assets/78819774/a4d85717-bde8-4bfe-8457-31e138a06583

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01bbe476f1c4e71160</li>
        <li>Upwork Job ID: 1750326687010930688</li>
        <li>Last Price Increase: 2024-01-25</li>
<li>Automatic offers: </li>
<ul>
<li>situchan | Contributor | 28120619</li>
<li>s-alves10 | Contributor | 28120622</li>
</ul></li>
    </ul>
</details>

**Comment by lanitochka17** [comment] 2024-01-24 19:00
We think that this bug might be related to #vip-vsp
CC @quintar

**Comment by s-alves10** [comment] 2024-01-24 20:19
## Proposal

### Please re-state the problem that we are trying to solve in this issue.

Thread header in room shows skeleton when replying in thread offline

### What is the root cause of that problem?

This issue looks like a regression of this PR https://github.com/Expensify/App/pull/34362
We get report name for policy rooms by `getAdminRoomInvitedParticipants` function
https://github.com/Expensify/App/blob/30aa432b44a2be3d0a6d2ab64968f972ab155912/src/libs/ReportUtils.ts#L2467-L2469

In this function, we return empty if `parentReportAction.originalMessage` is empty
https://github.com/Expensify/App/blob/30aa432b44a2be3d0a6d2ab64968f972ab155912/src/libs/ReportUtils.ts#L2420-L2422

Noting that this value is empty in offline, we get empty string though `parentReportActionMessage` is not empty

This makes the value of `isLoading` true
https://github.com/Expensify/App/blob/30aa432b44a2be3d0a6d2ab64968f972ab155912/src/pages/home/HeaderView.js#L220

This is the root cause

### What changes do you think we should make in order to solve the problem?

When original message is empty, we should return `parentReportActionMessage`

This works as expected


### What alternative solutions did you explore? (Optional)

**Comment by situchan** [comment] 2024-01-24 20:30
Agree with @s-alves10 
I prefer fallback to https://github.com/Expensify/App/blob/30aa432b44a2be3d0a6d2ab64968f972ab155912/src/libs/ReportUtils.ts#L2470

In case `parentReportActionMessage` is also empty, keep `[Deleted message]` which is production behavior.

**Comment by s-alves10** [comment] 2024-01-25 06:20
@situchan 
PR is ready for review https://github.com/Expensify/App/pull/35128

**Comment by JmillsExpensify** [comment] 2024-02-07 15:06
@situchan I'm not seeing a BZ checklist for this issue. Should we have one? I'm particularly interested in your perspective on the need for a regression test.

**Comment by situchan** [comment] 2024-02-07 15:08
This was deploy blocker. QA team caught this during staging regression testing.
So no need another regression test.

**Comment by JmillsExpensify** [comment] 2024-02-08 23:08
Ok cool! Thanks, I'll handle payments now.

**Comment by JmillsExpensify** [comment] 2024-02-08 23:10
Everyone paid out via automatic offers. Closing this issue!

**Closed by JmillsExpensify** 2024-02-08 23:10 UTC
Labels: External, Engineering, Daily, Awaiting Payment
