### ISSUE TITLE
deleting thread header is not dynamic

### ISSUE THREAD

**Issue by kavimuru** [Expensify/App#21203] opened 2023-06-21 13:44 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. open a chat with a message
2. reply in its thread
3. go to that thread and delete the header
4. observe LHN (thread is gone at this point)
5. now delete the same header again and again and observe the LHN
## Expected Result: 
If once a header is deleted, it should not appear again in LHN on clicking delete again
## Actual Result: 
If once a header is deleted, it is appearing again in LHN on clicking delete again

## Workaround:
Can the user still use Expensify without this being fixed? Have you informed them of the workaround?

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [x] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 1.2.30-0
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/43996225/bbe305ac-deb5-4521-9701-810361b77bf9

https://github.com/Expensify/App/assets/43996225/0422f29e-3a5e-454b-bba9-682556238582

**Expensify/Expensify Issue URL:**
**Issue reported by:** @chiragxarora 
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1686812414756769
 
[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by eh2077** [comment] 2023-06-22 09:02
This is a dupe of https://github.com/Expensify/App/issues/19363

**Closed** 2023-06-22 18:57 UTC
Labels: Daily, Bug
