### ISSUE TITLE
CRITICAL: [Track Expense] [$500] Track Expense sometimes opens the participant selector 

### ISSUE THREAD

**Issue by thienlnam** [Expensify/App#40257] opened 2024-04-15 22:06 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:**
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:**
**Slack conversation:**

## Action Performed:
1. Create a new account
2. Track Expense
3. After entering an amount, click 'Next'

## Expected Result:
You should see a final confirmation page, instead of seeing a participant selector page

## Actual Result:
You see a participant selector page

## Workaround:
Can the user still use Expensify without this being fixed? Have you informed them of the workaround?
None - usually fixes itself by opening up the selfDM 

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01184eaa749eca16a8</li>
        <li>Upwork Job ID: 1780001858353557504</li>
        <li>Last Price Increase: 2024-04-19</li>
<li>Automatic offers: </li>
<ul>
<li>hungvu193 | Contributor | 0</li>
<li>nkdengineer | Contributor | 0</li>
</ul></li>
    </ul>
</details>

**Comment by nkdengineer** [comment] 2024-04-15 22:43
## Proposal

### Please re-state the problem that we are trying to solve in this issue.

### What is the root cause of that problem?
- In [here](https://github.com/Expensify/App/blob/76ca7814304e143c86d4a2031c69af8aba8e17a9/src/pages/home/sidebar/SidebarScreen/FloatingActionButtonAndPopover.tsx#L277) we generate a new reportID if we cannot find a seftDM from ```ReportUtils.findSelfDMReportID```
- Then in [here](https://github.com/Expensify/App/blob/76ca7814304e143c86d4a2031c69af8aba8e17a9/src/pages/iou/request/step/IOURequestStepAmount.tsx#L120) we have a logic to navigate user to participants page if ```report.reportID``` is ```undefined```. In the case of the bug, ```report?.reportID``` is ```undefined``` 
### What changes do you think we should make in order to solve the problem?
- We need to add the check if the ```iouType``` is ```track-expense``` as well

### What alternative solutions did you explore? (Optional)
- NA

**Comment by hungvu193** [comment] 2024-04-16 14:53
Taking over this issue as C+ per this discussion: https://expensify.slack.com/archives/C02NK2DQWUX/p1713272014981619
cc @ntdiary

**Comment by hungvu193** [comment] 2024-04-17 05:19
I couldn't reproduce on latest main.

https://github.com/Expensify/App/assets/16502320/947b8d90-e777-4d4d-a7da-1e5889181e49

**Comment by nkdengineer** [comment] 2024-04-17 05:26
@hungvu193 You can reproduce it by:
1. Sign out if sign in
2. Open low network mode
3. Sign in
4. Right after sign in, choose "Track expense" in FAB
5. Enter the amount
6. Verify user is navigate to participant page

https://github.com/Expensify/App/assets/161821005/58599e19-5e8f-4232-b92c-89c1f6145ceb

**Comment by hungvu193** [comment] 2024-04-17 05:28
> @hungvu193 You can reproduce it by:
> 
> 1. Sign out if sign in
> 2. Open low network mode
> 3. Sign in
> 4. Right after sign in, choose "Track expense" in FAB
> 5. Enter the amount
> 6. Verify user is navigate to participant page
> 
>  output.mp4

Thanks! I can reproduce with your steps 👍

**Comment by hungvu193** [comment] 2024-04-17 07:46
I assume that [these steps](https://github.com/Expensify/App/issues/40257#issuecomment-2060379630) are the correct way to reproduce this issue, given the information. I'm aligned with @nkdengineer's [proposal here](https://github.com/Expensify/App/issues/40257#issuecomment-2057934941).
Thanks @ZhenjaHorbach, your solution didn't work when we were loading report data while creating Track expense.

🎀 👀 🎀  C+ reviewed

**Comment by nkdengineer** [comment] 2024-04-18 09:49
@hungvu193 PR https://github.com/Expensify/App/pull/40409 is ready

**Comment by thienlnam** [comment] 2024-04-19 00:31
@nkdengineer @hungvu193 Increased the bounty since this is a high priority item. We're aiming to fit this before the next App deploy - please prioritize this issue!

**Comment by hungvu193** [comment] 2024-04-19 00:32
> @nkdengineer @hungvu193 Increased the bounty since this is a high priority item. We're aiming to fit this before the next App deploy - please prioritize this issue!

Sure. I'm waiting for @nkdengineer response in the PR

**Comment by quinthar** [comment] 2024-04-21 22:27
@hungvu193 are you still blocked?  Can you link to exactly what you are waiting for an answer on?

**Comment by quinthar** [comment] 2024-04-21 22:28
oh nm, looks like it's merged and we are waiting for deploy, nice! https://github.com/Expensify/App/pull/40409#issuecomment-2067186525

**Comment by hungvu193** [comment] 2024-05-03 09:25
@isabelastisser This issue is ready for payment I believe 😄

**Comment by isabelastisser** [comment] 2024-05-03 15:46
The payments were processed in Upwork. All set!

**Closed by isabelastisser** 2024-05-03 15:46 UTC
Labels: Reviewing, External, Weekly, Awaiting Payment, Bug

**Comment by hungvu193** [comment] 2024-05-03 15:48
> The payments were processed in Upwork. All set!

@isabelastisser I think the amount should be 500$
https://github.com/Expensify/App/issues/40257#issuecomment-2065535904

**Comment by isabelastisser** [comment] 2024-05-03 15:53
@hungvu193 The issue was created on April 15, after the price change, right? So it should be $250.

**Comment by hungvu193** [comment] 2024-05-03 15:55
> @hungvu193 The issue was created on April 15, after the price change, right? So it should be $250.

It was 250$ issue, but the price was double price to 500$ since this is a high priority item

**Comment by thienlnam** [comment] 2024-05-03 18:23
Yeah to confirm I adjusted this to $500 since it was urgent

**Comment by isabelastisser** [comment] 2024-05-03 19:20
Got it, thanks for the context! I will correct the payment amounts in Upwork now.
