### ISSUE TITLE
Web - Workspace - "More" tooltip is displayed when hovering over the three dots after clicking on them

### ISSUE THREAD

**Issue by izarutskaya** [Expensify/App#24300] opened 2023-08-08 21:09 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Go to settings and click on "Create workspace"
2. Click on the three dots in the top right corner to open the details
3. Hover over the three dots again
4. Notice that the "More" tooltip  is displayed again

## Expected Result:
After opening the details, hovering over the three dots should not display the "More" tooltip again and the Cursor should be Changed

## Actual Result:
After opening the details, hovering over the three dots displays the "More" tooltip again.

## Workaround:
Can the user still use Expensify without this being fixed? Have you informed them of the workaround?

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [x] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** v1.3.51-2
**Reproducible in staging?:** Y
**Reproducible in production?:** N
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/115492554/88808078-9ec2-4095-81d7-4253e21cf966

https://github.com/Expensify/App/assets/43995119/4bb2aa27-2d43-45f3-ab85-2ae8465d5b6e

**Expensify/Expensify Issue URL:**
**Issue reported by:** @tewodrosGirmaA
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1691501020584879

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by AndrewGable** [comment] 2023-08-08 21:16
Confirmed I can only reproduce this on staging

**Comment by puneetlath** [comment] 2023-08-08 22:10
I don't think this needs to be a deploy blocker. It also seems similar to https://github.com/Expensify/App/issues/24284

**Comment by puneetlath** [comment] 2023-08-08 22:11
I think the fact that it still show the tooltip when you re-hover is fine. The FAB also does that. I think instead the problem is that re-clicking on it doesn't do anything.

**Comment by samueltuyizere** [comment] 2023-08-08 23:45
I agree @puneetlath , may be clicking on it again should hide the dropdown.

**Comment by samueltuyizere** [comment] 2023-08-08 23:52
Contributor details
Your Expensify account email: samueltuyizere0@gmail.com
Upwork Profile Link: https://www.upwork.com/freelancers/~0143489d2cddff3bbd

**Comment by tewodrosGirmaA** [comment] 2023-08-09 05:13
@aimane-chnaif, I would like to bring to your attention that I have previously reported an issue regarding confusion in creating GitHub issues. Kindly refer to the following Slack conversation for further details: https://expensify.slack.com/archives/C049HHMV9SM/p1691501020584879."

**Comment by tewodrosGirmaA** [comment] 2023-08-09 05:30
@aimane-chnaif , this is not fair , just without any reason, I reported first

**Comment by tewodrosGirmaA** [comment] 2023-08-09 06:06
> > @aimane-chnaif , this is not fair , just without any reason, I reported first
> 
> Huh? How come you can report bug even if PR was not merged yet?

That is my magic hhhh , I mean I reported first before this https://github.com/Expensify/App/issues/24296,

**Comment by tewodrosGirmaA** [comment] 2023-08-09 06:15
> planned

Thank you 😊  by the way for replying

**Comment by AndrewGable** [comment] 2023-08-09 15:49
Closing as dupe

**Closed by AndrewGable** 2023-08-09 15:49 UTC
Labels: Engineering, Daily, Bug
