### ISSUE TITLE
[$500] IOU-In offline, green thumbnail is not displayed for distance request created.

### ISSUE THREAD

**Issue by izarutskaya** [Expensify/App#33060] opened 2023-12-14 12:17 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.12
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** Applause-Internal Team
**Slack conversation:** @

## Action Performed:
Pre-conditions: 
1. Create new workspace
2. Select and save 2 waypoints for making distance request

1. Go to https://staging.new.expensify.com/
2. Tap profile icon
3. Tap preferences
4. Toggle on forced offline
5. Navigate to LHN
6. Tap fab
7. Tap request money ---- Distance
8. Enter start and finish waypoints from suggestions
9. Tap next
10. Select a Workspace ( use new workspace)
11. Tap request

## Expected Result:
In offline, green thumbnail must be displayed for distance request created.

## Actual Result:
In offline, green thumbnail is not displayed for distance request created.

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [x] Android: mWeb Chrome
- [x] iOS: Native
- [x] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

https://github.com/Expensify/App/assets/115492554/8a274822-b214-4def-9ef5-26fe25ccb1ab

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~0118764c639595457a</li>
        <li>Upwork Job ID: 1735272932191092736</li>
        <li>Last Price Increase: 2023-12-14</li>
    </ul>
</details>

**Comment by paultsimura** [comment] 2023-12-14 12:27
## Proposal

### Please re-state the problem that we are trying to solve in this issue.


### What is the root cause of that problem?
While creating an optimistic Distance request, we set `transaction.reportID` to the chat report.

### What changes do you think we should make in order to solve the problem?
We should set `transaction.reportID` to the newly created IOU report.



### What alternative solutions did you explore? (Optional)

**Comment by DylanDylann** [comment] 2023-12-15 06:50
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
In offline, green thumbnail is not displayed for distance request created.

### What is the root cause of that problem?
When creating a new distance request, we will initialize `transactionDraft_1.reportID` as the **`reportID` of the root report**. But when creating optimistic data for request money API, `transaction.reportID` is **the reportID of IOU report**

https://github.com/Expensify/App/blob/3a44f772e2c381b1cdb025f845551c5f0985bad5/src/libs/actions/IOU.js#L674-L679

So that, existingTransaction.reportID (**It is `reportID` of the root report**) will overwrite optimisticTransaction.reportID (**it is `reportID` of IOU report**)

### What changes do you think we should make in order to solve the problem?
Note that, In our codebase, we are using `transaction.reportID` as `reportID` of the IOU report. So that we shouldn't save **`reportID` of the root report** to this field.


To clarify the meaning of the fields, I suggest when creating a new distance request we should save **`reportID` of the root report** to `transactionDraft_1.parentReportID` instead of `transactionDraft_1.reportID` and use 
 `transactionDraft_1.parentReportID` for the purpose of identifying participants of money request 
### What alternative solutions did you explore? (Optional)
NA

**Comment by kmbcook** [comment] 2023-12-16 17:32
## Please re-state the problem that we are trying to solve in this issue.

When creating a distance request offline, the green receipt placeholder is not displayed (in place of a map thumbnail) in the report preview. 

## What is the root cause of that problem?

When the user confirms a new distance request, the optimistic transaction is not being built correctly, probably because the code for building it is not as clear as is needed.

## What changes do you think we should make in order to solve the problem?

I suggest writing a new function called buildOptimisticDistanceRequestTransaction in libs/TransactionUtils, and writing it so that it is easier to understand exactly how the transaction is built.

I also suggest fixing another problem while writing that same function. This problem is that the optimistic transaction includes pendingFields.waypoints:add, which is not correct. See issue 32263 for my (belated) proposed solution to this other problem.

**Comment by bfitzexpensify** [comment] 2023-12-17 15:36
I believe it's intentional for us to show a placeholder image when offline - https://expensify.slack.com/archives/C03TME82F/p1695781672838349?thread_ts=1695148441.990019&cid=C03TME82F. Closing this out.

**Comment by paultsimura** [comment] 2023-12-17 15:39
@bfitzexpensify please re-check the issue description. We don't show any placeholder when offline atm. The issue's intended exactly to fix that.

**Comment by bfitzexpensify** [comment] 2023-12-17 21:52
Thanks for the heads up @paultsimura. I was looking at the placeholder once the distance request had been opened, which is as expected. 

I think we can still leave this closed, however - I'm not sure this is a high-value issue to fix, and I'm not spotting an obvious wave or VIP project that we've identified internally to attach it to. It's an edge flow and the lack of a receipt placeholder image doesn't influence the experience at all. We'll eventually want to update that image to something map-specific rather than the receipt image, and I think that would be a more appropriate time to make sure it's appearing as we'd expect offline when a distance request is created.

**Comment by paultsimura** [comment] 2023-12-18 08:20
Thanks @bfitzexpensify, I understand your point, however, the root cause here is still worth fixing, not for the sake of the preview placeholder alone:
Setting an incorrect `transaction.reportID` on the Distance request offline can result in other incorrect behaviors, as we use `TransactionUtils.getAllReportTransactions` in several other places.

For example, `createWorkspaceFromIOUPayment`:
> This flow is used for bottom up flow converting IOU report to an expense report. When user takes this action,
we create a Collect type workspace when the person taking the action becomes an owner and an admin, while we
add a new member to the workspace as an employee and convert the IOU report passed as a param into an expense report.

It uses the same function `TransactionUtils.getAllReportTransactions(iouReportID)` to collect the transactions for building the new Collect type workspace, and if we do it with an offline-created Distance request in the IOU Report, this Distance request will be missed:

https://github.com/Expensify/App/blob/ca63857cc5da5537b42e227d91fe5f72552d0eb0/src/libs/actions/Policy.js#L1787-L1801

**Comment by DylanDylann** [comment] 2023-12-18 09:11
I agree with @paultsimura's point, The root cause relates to the new refactor on request money flow. We are having a confusion about the meaning of `transactionDraft_1.reportID` as expained in [my proposal](https://github.com/Expensify/App/issues/33060#issuecomment-1857365867)

**Comment by bfitzexpensify** [comment] 2023-12-19 18:55
Just reopening this so that I take action on it later on today.

**Comment by bfitzexpensify** [comment] 2023-12-20 13:42
Thanks for the extra detail @paultsimura. Just to clarify, what would happen right now with the conversion to a workspace made by changing an IOU to an expense report? Would the workspace still be created, but the distance request would be missing?

**Comment by paultsimura** [comment] 2023-12-20 13:58
@bfitzexpensify 
Yes, if we perform it offline (with the optimistic Distance request), the workspace will be created, but without that distance request

**Comment by bfitzexpensify** [comment] 2023-12-21 15:38
OK, we chatted about this internally - we don't support IOU distance requests as it stands, and this is being addressed via https://github.com/Expensify/App/issues/23291. So we will leave this closed.

**Closed by bfitzexpensify** 2023-12-21 15:38 UTC
Labels: External, Daily, Help Wanted, Bug
