### ISSUE TITLE
[Hold for Payment] [$500] Distance - For selected Invalid address, error displayed but showing previously selected waypoint

### ISSUE THREAD

**Issue by izarutskaya** [Expensify/App#30837] opened 2023-11-03 12:06 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.3.95-0
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** Applause-Internal Team
**Slack conversation:** @

## Action Performed:
Pre-condition: In offline, create and save 2 vague locations (eg-WT)for making distance request
1.Go to https://staging.new.expensify.com/
2.Tap employee WS
3.Tap plus--request money-- distance
4.Enter start and finish point with any valid address
5.Tap stop point and enter invalid address
6.Note incorrect error
(Issues with map provider, try again)shown
7.Tap that waypoint and change to valid address
8. Again tap and select same address
9.Now select any invalid address

## Expected Result:
When Invalid address is selected, the selected address and correct error message should be displayed.

## Actual Result:
When Invalid address is selected, error is displayed but showing previously selected waypoint.

Incorrect error message - ( Issues with map provider, try again) is shown

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [x] Android: mWeb Chrome
- [x] iOS: Native
- [x] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

https://github.com/Expensify/App/assets/115492554/7c0384ce-a451-4bd9-96c9-015258c8e019

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~0116f74087ff38a9d5</li>
        <li>Upwork Job ID: 1720412223318081536</li>
        <li>Last Price Increase: 2023-11-10</li>
<li>Automatic offers: </li>
<ul>
<li>DylanDylann | Contributor | 27799860</li>
</ul></li>
    </ul>
</details>

**Comment by FitseTLT** [comment] 2023-11-03 13:28
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
If we input an invalid address on a address field which previously had a valid address the name will still display the previous inserted valid address
### What is the root cause of that problem?
When we select an invalid address `Transaction.saveWaypoint` is called here with `waypoint.name` value as undefined because it is not a valid address
https://github.com/FitseTLT/App/blob/c0657fa0b2c3cc5a88659c3f4d21ee37439a2fdc/src/pages/iou/WaypointEditor.js#L163-L172

So in `Transaction.saveWaypoint` here below onyx merge is called with waypoint.name as undefined but that is understood by onyx that name prop is not to be merged or changed
https://github.com/FitseTLT/App/blob/c0657fa0b2c3cc5a88659c3f4d21ee37439a2fdc/src/libs/actions/Transaction.ts#L59-L73
### What changes do you think we should make in order to solve the problem?

We need to change 
https://github.com/FitseTLT/App/blob/c0657fa0b2c3cc5a88659c3f4d21ee37439a2fdc/src/pages/iou/WaypointEditor.js#L163-L172
to 
```
 const selectWaypoint = (values) => {
        const waypoint = {
            lat: values.lat,
            lng: values.lng,
            address: values.address,
            name: values.name || null,
        };
        Transaction.saveWaypoint(transactionID, waypointIndex, waypoint, isEditingWaypoint);
```
so that in invalid addresses case the name field will be reset in onyx merge 👍 
POC:

https://github.com/Expensify/App/assets/38649957/361e5145-d47a-4ebf-a2b8-11a6906c0c33



### What alternative solutions did you explore? (Optional)

**Comment by DylanDylann** [comment] 2023-11-03 18:12
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
We have 2 bugs here:
Bug 1. Select a waypoint (name field exists) then select another waypoint (name field doesn't exist) --> the old name still be displayed
Bug 2. Select a waypoint (name field exists) then go offline and update waypoint with any name --> the old name still be displayed



### What is the root cause of that problem?
We don't remove old name value
Bug 1: In here
https://github.com/Expensify/App/blob/aa30ef2ea44279637eebb2517b4e08ce88f90e7b/src/pages/iou/WaypointEditor.js#L164-L169

Because values.name is undefined, when using MERGE method ONYX won't overwrite old waypoint.name 

Bug 2: In here
https://github.com/Expensify/App/blob/aa30ef2ea44279637eebb2517b4e08ce88f90e7b/src/pages/iou/WaypointEditor.js#L146-L150
We don't reset values.name
### What changes do you think we should make in order to solve the problem?
Bug 1: In here
https://github.com/Expensify/App/blob/aa30ef2ea44279637eebb2517b4e08ce88f90e7b/src/pages/iou/WaypointEditor.js#L164-L169

We should update like this `name: values.name || null`

Bug 2: In here
https://github.com/Expensify/App/blob/aa30ef2ea44279637eebb2517b4e08ce88f90e7b/src/pages/iou/WaypointEditor.js#L146-L150
We should add `name: waypointValue`  or `name: null` 

### What alternative solutions did you explore? (Optional)
We can consider combine old data and update data and then using SET method instead of MERGE method

**Comment by NicMendonca** [comment] 2023-11-06 15:44
@allroundexperts proposals for you! ^

**Comment by DylanDylann** [comment] 2023-11-21 02:58
@Beamanator Could you help to review my proposal? Thanks so much

**Comment by Beamanator** [comment] 2023-11-23 09:24
I'm officially back from vacayyyy! reviewing now

**Comment by Beamanator** [comment] 2023-11-24 13:01
@DylanDylann when do you think we can get a PR here?

**Comment by DylanDylann** [comment] 2023-11-24 13:07
The PR will be ready in tomorrow

**Comment by DylanDylann** [comment] 2023-11-27 08:51
@allroundexperts The PR is ready for reviewing

**Comment by DylanDylann** [comment] 2023-12-20 16:22
@NicMendonca The PR is merged and deployed to production, could you help to move forward with this issue?

**Comment by DylanDylann** [comment] 2024-01-02 06:07
@NicMendonca Bump again

**Comment by NicMendonca** [comment] 2024-01-09 18:24
omg, so sorry, I don't know why this didn't bump to a daily

**Comment by NicMendonca** [comment] 2024-01-09 18:26
BZ payment summary: 

Contributor: @DylanDylann - $500 - paid via Upwork
C+:  @allroundexperts  - $500 - paid via Expensify

**Comment by NicMendonca** [comment] 2024-01-09 18:27
@DylanDylann you've been paid!

@allroundexperts don't forget to request payment via Expensify!

**Closed by NicMendonca** 2024-01-09 18:27 UTC
Labels: Reviewing, External, Engineering, Daily, Bug, Distance

**Comment by JmillsExpensify** [comment] 2024-01-30 18:43
$500 approved for @allroundexperts based on summary above.
