### ISSUE TITLE
[$500] Web - Chat - Reply message is seen at the top of the chat before it's sent

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#33669] opened 2023-12-27 21:15 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.18.1
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** Applause - Internal team
**Slack conversation:**

## Action Performed:
1. Navigate to https://staging.new.expensify.com/
2. Create a chat with any member
3. Send a message
4. Reply to the message with a text

## Expected Result:
Reply message shouldn't be showing there.

## Actual Result:
Reply message is seen at the top of the chat before it's sent. Sometimes it affects the first normal message in a chat.

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

https://github.com/Expensify/App/assets/93399543/a449b954-02b7-4322-bf15-92d7be9cb0b3

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~019c786219650c66b0</li>
        <li>Upwork Job ID: 1740119156955164672</li>
        <li>Last Price Increase: 2024-01-03</li>
    </ul>
</details>

**Comment by sonialiap** [comment] 2024-01-05 11:09
I also cannot reproduce. Closing

**Closed by sonialiap** 2024-01-05 11:09 UTC
Labels: External, Daily, Help Wanted, Overdue, Bug
