### ISSUE TITLE
mWeb - Global Unread Indicator - Global Unread Indicator doesn't decreases

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#10828] opened 2022-09-05 23:56 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Issue found when executing PR** https://github.com/Expensify/App/pull/10739

## Action Performed:
1. Go to URL https://staging.new.expensify.com/
2. Login with any account (User A), ensure User A is not looking at the chat
3. Start a chat between User A and User B
4. Leave a comment on the chat as User B
5. Leave another comment

## Expected Result:
The global indicator decreases

## Actual Result:
Global Unread Indicator doesn't decreases

## Workaround:
Unknown

## Platform:

Where is this issue occurring?

- Mobile Web

**Version Number:** 1.1.97.2

**Reproducible in staging?:** Yes

**Reproducible in production?:** No

**Email or phone of affected tester (no customers):** any

**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Notes/Photos/Videos:** Any additional supporting documentation

https://user-images.githubusercontent.com/93399543/188521931-2ff8a85a-65a7-4c43-a9e8-70708737537b.mp4

**Expensify/Expensify Issue URL:** 

**Issue reported by:** Applause - Internal Team

**Slack conversation:** 

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by neil-marcellini** [comment] 2022-09-06 09:10
I'm removing my assignment for #focus.

**Comment by marcaaron** [comment] 2022-09-06 09:13
This is most likely reproducible on production. And I am pretty sure it is a Chrome browser bug. Gonna remove the Deploy Blocker since it isn't something that needs to block the deploy.

**Comment by stitesExpensify** [comment] 2022-09-06 10:28
I agree with @marcaaron assessment. Additionally, this is probably the same bug we have on desktop and will be fixed with the new reportActionIDs

**Comment by marcaaron** [comment] 2022-09-21 06:00
Gonna close this one as it's a duplicate of https://github.com/Expensify/App/issues/8005

Though I do not have much faith this will e fixed with the `reportActionID` changes. It's a Chrome bug or something.

**Closed by marcaaron** 2022-09-21 06:00 UTC
Labels: Engineering, Weekly, Improvement, Internal
