### ISSUE TITLE
[HOLD for payment 2022-09-16] [$250] When you copy text that has an apostrophe (eg, don't) and then "paste without formatting", it pastes don&rsquo;t

### ISSUE THREAD

**Issue by mvtglobally** [Expensify/App#10446] opened 2022-08-18 13:29 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Send a message with a ' in it
2. Copy it (Command+C)
3. Paste it in newDot (Shift+Command+V)

## Expected Result:
Text should be pasted without html 

## Actual Result:
When you copy text from NewDot on Chrome desktop that has an apostrophe (eg, don't) and then "paste without formatting" (ie, Shift+Command+V), it pastes in a weird way: don&rsquo;t.  Incidentally, it pastes that way everywhere (ie, it did just now into Slack), so the problem must be at the time of copy -- it's putting it onto the clipboard in a weird way.  Also interesting, if I paste normally (ie, Command+V) into Slack, it pastes wrong: don&rsquo;t, but if I paste normally into NewDot it pasts right.  I think it has something to do with us trying to preserve HTML formatting and transform it back to Markdown, or something

## Workaround:
unknown 

## Platform:

Where is this issue occurring?

- Desktop App

**Version Number:** 1.1.88-4
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**Email or phone of affected tester (no customers):** 
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation 

<img width="402" alt="image - 2022-08-18T092750 563" src="https://user-images.githubusercontent.com/43995119/185406767-08b7220f-1880-45c7-baba-9b5b4fbf9985.png">

<img width="890" alt="image - 2022-08-18T093707 909" src="https://user-images.githubusercontent.com/43995119/185410165-bdff5f8d-a192-4b68-bdf3-8914af9987ba.png">

**Expensify/Expensify Issue URL:** 
**Issue reported by:** @quinthar @iwiznia 
**Slack conversation:** https://expensify.slack.com/archives/C01GTK53T8Q/p1660824818440579 https://expensify.slack.com/archives/C01GTK53T8Q/p1660298688922279

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by chiragsalian** [comment] 2022-08-18 18:00
Looks like a straightforward external issue. Adding the labels.

**Comment by kadiealexander** [comment] 2022-08-22 14:16
https://www.upwork.com/jobs/~011945cb0d4454fc97
https://www.upwork.com/ab/applicants/1561713563518566400/job-details

**Comment by mollfpr** [comment] 2022-08-28 06:27
### Proposal

We need to decode the text from the clipboard if it's not `text/html`. We can use the `Str.hmltDecode` from `expensify-common` to decode the text.
https://github.com/Expensify/App/blob/e21736d87cc1ed95c1f64a54040ce242ced7ebc0/src/components/Composer/index.js#L311-L312
```diff
+            return;
        }

+        event.preventDefault();
+        const plainText = event.clipboardData.getData('text/plain');
+        try {
+            document.execCommand('insertText', false, Str.htmlDecode(plainText));
+            this.updateNumberOfLines();

+            this.textInput.blur();
+            this.textInput.focus();
+        } catch (e) {}
```

For growl notification showing when pasting the text, we can add more checks on the `img` tag with `embeddedImages[0].src`. When pasting the text with `CMD+V`, the text has an empty `img` tag.
https://github.com/Expensify/App/blob/e21736d87cc1ed95c1f64a54040ce242ced7ebc0/src/components/Composer/index.js#L281
```diff
+  if (embeddedImages.length > 0 && embeddedImages[0].src) {
```

#### Result

https://user-images.githubusercontent.com/25520267/187060703-087046f0-8901-4d6c-abdf-107c1b83e268.mov

**Comment by kadiealexander** [comment] 2022-08-30 13:59
@mananjadhav any thoughts on the above?

**Comment by mananjadhav** [comment] 2022-08-30 14:12
Please allow me a day to check.

**Comment by kadiealexander** [comment] 2022-09-01 13:41
@mananjadhav how are you getting on with this one?

**Comment by mananjadhav** [comment] 2022-09-01 18:12
Thanks for the being @kadiealexander, I was catching up on the slack conversation.

@mvtglobally Do we have any reproduction steps for the growl error message? I am able to reproduce this for encoded string but no growl message.

Meanwhile @chiragsalian, I checked @mollfpr's proposal here and it looks good to me.

**Comment by mvtglobally** [comment] 2022-09-02 04:30
@mananjadhav team is planning to move away from growls soon. 
Don't have the steps to trigger it currently

**Comment by chiragsalian** [comment] 2022-09-02 20:46
Correct yes, no need to worry about the growl for now. 

The proposal looks good to me too. I would like to offer some suggestions to the proposal.
1. Create a method called `paste(text)` that contains,
```
try {
    document.execCommand('insertText', false, text);
    this.updateNumberOfLines();

    // Pointer will go out of sight when a large paragraph is pasted on the web. Refocusing the input keeps the cursor in view.
    this.textInput.blur();
    this.textInput.focus();
// eslint-disable-next-line no-empty
} catch (e) {}
```
2. Then have your block call paste(Str.htmlDecode(plainText)) at the end.
3. Replace the same block in handlePaste to call `paste(markdownText)`.

This way the same 8 lines of execCommand logic is not duplicated.

Rest LGTM, feel free to create the PR @mollfpr.

**Comment by mollfpr** [comment] 2022-09-02 23:28
Thanks @chiragsalian

**Comment by kadiealexander** [comment] 2022-09-12 06:53
Reassigning as I'm ooo for the next 9 days.

**Comment by mollfpr** [comment] 2022-09-16 02:58
@trjExpensify I just applied to the Upwork job, thanks!

**Comment by trjExpensify** [comment] 2022-09-16 10:20
Cool, offers are sent out to both you and @mananjadhav to accept! 👍

**Comment by trjExpensify** [comment] 2022-09-16 10:21
Haha, @mananjadhav, do you have a script running? Instant accepted! ;) Settled up!

**Comment by trjExpensify** [comment] 2022-09-16 10:24
Cool, @mollfpr also settled. We're done here - thanks everyone! 🎉

**Closed by trjExpensify** 2022-09-16 10:24 UTC
Labels: Exported, External, Engineering, Daily, Awaiting Payment

**Comment by mananjadhav** [comment] 2022-09-16 10:30
@trjExpensify  🤑
