### ISSUE TITLE
[HOLD for sobit] [$1000] Able to by pass 'Admins only' functionality using :emoji in multiple lines

### ISSUE THREAD

**Issue by kavimuru** [Expensify/App#20827] opened 2023-06-15 13:54 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Go to staging dot on web chrome and login with User A
2. Create a new workspace and invite User B
3. Login with User B on another web chrome (to reproduce the bug, place the windows side by side)
4. From User A and User B, go to announce channel
5. From User A, go to top header, go to 'Who can post' (Please do not click any option now)
6. From User B, type any short message (do not click on send).
7. From user A, select 'Admins Only'  and see that on The User B side, the chat composer disappears
8. But now, again select the 'All members' on User A side. Whereas on User B side, type in `:smile:` (first colon and emoji name), and then copy the "`:smile:`"
9. Then, hold cmd+V to automatically paste it multiple times in a row back-to-back, until you have 5+ rows of the emoji pasted.
9. Do **not** click Send
11. From User A, again select 'Admins Only' and notice that on User B side, the chat composer doesn't disappear and we are able to send other messages too. 

## Expected Result: 
A user should not be able to type in the workspace after 'Admins only' is selected. 

## Actual Result: 
A user is able to type in the workspace chat after the 'Admins only' setting is selected, by using ":emoji:" pasted in succession for multiple rows. This introduces so type of lag that allows the user to keep typing

## Workaround:
Can the user still use Expensify without this being fixed? Have you informed them of the workaround?

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [x] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 1.3.28-3
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/43996225/97d3b265-df94-462c-b633-3ebbe5115dbf

https://github.com/Expensify/App/assets/43996225/ca2b48df-1fa1-43c3-8e89-5567769417d5

**Expensify/Expensify Issue URL:**
**Issue reported by:** @priya-zha
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1685972438902859

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by DanutGavrus** [comment] 2023-06-15 13:55
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
Able to by pass 'Admins only' functionality using :emoji in multiple lines

### What is the root cause of that problem?
Inside `ReportActionCompose.js`, we call `updateFrequentlyUsedEmojis` each time we edit the message, each starting a network call. The back-end sends a notification back to the current user for each emoji added, and the notification that _the room has changed to admins only comes with a __delay___. Thus, adding more emojis in chat => easier to reproduce the bug.

### What changes do you think we should make in order to solve the problem?
We should __debounce__ the `updateFrequentlyUsedEmojis` method same as we do with other methods inside `ReportActionCompose.js`. With these changes:  

![image](https://github.com/Expensify/App/assets/56603839/22f6881c-33dc-4307-82bf-535536f4d26e)  

the bug is no longer reproducible, no matter _how many emojis_ are added in chat.

**Comment by DanutGavrus** [comment] 2023-06-15 14:08
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
Able to by pass 'Admins only' functionality using :emoji in multiple lines

### What is the root cause of that problem?
Inside `ReportActionCompose.js`, we call `updateFrequentlyUsedEmojis` each time we edit the message, each starting a network call. The back-end sends a notification back to the current user for each emoji added, and the notification that _the room has changed to admins only comes with a __delay___. Thus, adding more emojis in chat => easier to reproduce the bug.

### What changes do you think we should make in order to solve the problem?
We should __debounce__ the `updateFrequentlyUsedEmojis` method same as we do with other methods inside `ReportActionCompose.js`. With these changes:  

![image](https://github.com/Expensify/App/assets/56603839/22f6881c-33dc-4307-82bf-535536f4d26e)  

the bug is no longer reproducible, no matter _how many emojis_ are added in chat.

**Comment by DanutGavrus** [comment] 2023-06-15 14:08
If you can't reproduce this bug from the first try, you may also try this:
1. CTRL+C smile:
2. Keep CTRL+V until 6-7 rows are filled in chat on userB
3. Quickly change to "only admins" from userA
4. Come back and start writing other messages on userB  

More rows at step 2 = increased delay for the "only admins" change to take effect = easier to reproduce

**Comment by michaelhaxhiu** [comment] 2023-06-20 17:16
looking!

**Comment by michaelhaxhiu** [comment] 2023-06-20 18:16
Hm this isn't working for me and I'm not sure why

![not working for me yo](https://github.com/Expensify/App/assets/13206896/af36c325-34a1-4e72-ae81-cbc3ff99dccc)


tried this `:smile :smile :smile`.... format too and no luck

<img width="746" alt="image" src="https://github.com/Expensify/App/assets/13206896/62f344fd-7135-4ec3-92d4-0768631d61bc">

**Comment by DanutGavrus** [comment] 2023-06-20 18:43
@michaelhaxhiu if you do not input enough rows of smile: the time window in which you are able to by-pass admins-only is short. Have a look at this:

https://github.com/Expensify/App/assets/56603839/e726bb46-db30-4acb-a6ef-503bde840fea

**Comment by DanutGavrus** [comment] 2023-06-20 19:51
Something like that. Each `smile:` adds a small delay of lets say `x`. 10 `smile:` would be `10x`, and so on. Thus, 6 rows grant a _very large time window_. If usersB changes his room to __admins only__ while `x` time has __not__ passed, the change does __not__ take effect for you(userA), so you may keep typing other messages.  

The back-end however, knows about the __admins-only__, so the messages will not appear to other members, but as I see, no error appears when sending them, and they will remain in _your chat_ afterwards. I still have the messages I've sent in the video in _#announce_ and for me, they appear like they were sent, still no error message appears.

Other small problem is that back-end will still let _all other users_ see when you are _typing_ even if it knows about the __admins only__, as you may see in the video.

**Comment by DanutGavrus** [comment] 2023-06-20 20:27
I think that the _last try_ may look like this:  

Have 2 apps opened side by side like in your previous video. On left I see you have the administrator user(userA let's say) and on right you have a user which is not an admin(userB):
1. Copy this text `smile:` as is;
2. While you have the Settings opened on userA with the current selection of "All members", go to userB, _clear_ the text input,  then just keep the paste shortcut pressed for some time(CTRL+V on Windows) until 7-8 rows are filled on right;
3. _Right after_ letting go of the paste shortcut, _rapidly_ change from 'All members' to 'Admins only' on left in userA;
4. _Right after_ changing to 'Admins only', _rapidly_ clear the text input and _start typing&sending_ other messages on right for userB.

**Comment by michaelhaxhiu** [comment] 2023-06-20 20:39
Yes I have tried this again just now step by step. I still can't reproduce. 

Check it out - https://recordit.co/mU1Br5A7hM

**Comment by DanutGavrus** [comment] 2023-06-20 20:49
@michaelhaxhiu I see that you have white spaces in the video, maybe `smile: ` got copied instead of `smile:`? I think that if you do the exact same thing, but without the white space, it might actually work this time.

**Comment by DanutGavrus** [comment] 2023-06-20 21:29
@michaelhaxhiu Glad I was able to help you reproduce.  

I was not aware of those error messages, I will check again tomorrow as it's 0:30am here, and come back to you with a reply.

From what I remember, the fact that the chat was updated to `Admins only` comes as a notification from the back end to the app. But, each written emoji in the app, makes a call to the back end, which also triggers a notification back to the app, thus creating a queue of notifications which the app has to process one by one. `Admins only` notification comes at the end of the queue, thus the app does not have the time to process it.

Maybe you could also look above at my proposal when you have the time?

**Comment by michaelhaxhiu** [comment] 2023-06-20 21:45
No problem! Talk tomorrow :) And yes your proposal is first to be reviewed :). Thanks for your continued involvement here.

**Comment by DanutGavrus** [comment] 2023-06-21 09:08
@tienifr
1. Here is a [commit](https://github.com/DanutGavrus/App/commit/42a5bc63ed9fead8dbd0ba6fba967647e5ac13be) with only a `debounce` of `75`. The bug from this issue is not reproducible, and the frequently used emojis seem to work as intended in practice. Could you please checkout this branch and make a short screen recording with the bug you think remains in the app?
2. I think there's a risk of a `race` condition, as you are calling `this.insertedEmojis = [...this.insertedEmojis, ...emojis]` while the user types, and `this.insertedEmojis = []` in the `debounced` method.

@michaelhaxhiu
1. I confirm that the errors for each message appears, but, only if the `x` time for the `updateFrequentlyUsedEmojis` passes. If you rapidly send 3 messages and _refresh the page_, the messages remain in your chat with no error as if they were actually sent. I refreshed the page in the screen recording, so that's why I got no errors.
2. > I guess the root bug here is that we should block the chat input more quickly (e.g. instantly after the settings change from Members -> Admins)? Is that right?  

Yes! And for that, we should get rid of the delay caused by the queue `updateFrequentlyUsedEmojis` calls. Using `debounce` will get rid of this `back-end spamming` and with a small value will work as before for users using the app.

**Comment by DanutGavrus** [comment] 2023-06-22 10:10
@tienifr  
> yes I tried the same approach. Please check the API response, you'll see that the count added is wrong. If you send 10 :smile:, it will only count as 1 after the "simple" debounce, while it should actually count as 10.

It works as intended on [this branch](https://github.com/DanutGavrus/App/tree/fix/20827-able-to-by-pass-admins-only). See this video:

https://github.com/Expensify/App/assets/56603839/ca57e764-e7c0-4023-9133-11710bdb12ed

There's a `debounce` of 75ms. In the second part of the video I've tried to click a button twice as fast as I could, and my best time was 100+ ms, I don't think it is humanly possible to insert 2 emojis in under 75ms, as it also takes longer than a double click. So, we could even go with a `debounce` of 100ms. This would be only a small change, enough to prevent this bug from happening while keeping the same functionality.

> @DanutGavrus there won't be any race condition since JS is single threaded, if you're able to reproduce any, I'd love to know :smile:.

Even if it's single threaded, from what I've read race conditions still exist.  

>I also provided an alternate debounceReduce implementation for the same, that one will not have any race condition as well.  

An interesting alternative to think of. I think that the native behavior(Samsung Keyboard for example) is to update recent emojis right as they are inserted. Don't know if we want to keep the same, or if it would be better off to move from it.

**Comment by sobitneupane** [comment] 2023-06-26 08:19
> Another way to do the above without adding a new variable is to add an implementation of a debounceReduce function like https://github.com/jashkenas/underscore/issues/310#issuecomment-429499335 that implements the debounce but also merge all the params of the functions called during the debounce.

@tienifr Can you explain about it in detail. How will you implement it in our case?

**Comment by sobitneupane** [comment] 2023-06-29 14:34
> Anw, I prefer the first approach where we introduce a new variable, since it's short, clear and easy to understand.

I am okay with it.

[Proposal](https://github.com/Expensify/App/issues/20827#issuecomment-1599959158) from @tienifr looks good to me.

🎀 👀 🎀 C+ reviewed

**Comment by grgia** [comment] 2023-06-29 15:32
Proposal looks good to me, all yours @tienifr

**Comment by grgia** [comment] 2023-06-29 15:48
@tienifr 
<img width="966" alt="image" src="https://github.com/Expensify/App/assets/38015950/c10ab48a-1738-4632-ae98-7cab77ae4dbd">

**Comment by grgia** [comment] 2023-07-17 13:59
@sobitneupane @michaelhaxhiu bump on BZ checklist / payment here

**Comment by michaelhaxhiu** [comment] 2023-07-18 23:58
Sorry for delay, payment is as follows:

- [ ] @priya-zha External issue reporter $250 
- [ ] @tienifr Contributor that fixed the issue $1000
- [ ] @sobitneupane Contributor+ that helped on the issue and/or PR $1000

**Comment by michaelhaxhiu** [comment] 2023-07-19 00:01
@sobitneupane are you via Upwork or newDot?

**Comment by michaelhaxhiu** [comment] 2023-07-19 00:01
Invited Priya & Tien to the job in Upwork

**Comment by sobitneupane** [comment] 2023-07-19 05:43
@michaelhaxhiu I will request payment via newDot.

**Comment by michaelhaxhiu** [comment] 2023-07-19 18:15
Update: Contributor & bug reporter are paid. Just waiting for sobit to confirm payment was made and complete the checklist.

**Comment by sobitneupane** [comment] 2023-07-24 13:24
> **BugZero Checklist:** The PR fixing this issue has been merged! The following checklist ([instructions](https://stackoverflow.com/c/expensify/questions/14574)) will need to be completed before the issue can be closed:
> 
> * [ ]  [@sobitneupane] The PR that introduced the bug has been identified. Link to the PR:

https://github.com/Expensify/App/pull/6498 
> * [ ]  [@sobitneupane] The offending PR has been commented on, pointing out the bug it caused and why, so the author and reviewers can learn from the mistake. Link to comment:

The issue was introduced while adding the functionality of frequently used emojis 2 years back.

> * [ ]  [@sobitneupane] A discussion in #expensify-bugs has been started about whether any other steps should be taken (e.g. updating the PR review checklist) in order to catch this type of bug sooner. Link to discussion:

It's an edge case and very difficult to reproduce. 
> * [ ]  [@sobitneupane] Determine if we should create a regression test for this bug. 

No. It is an edge case and might be difficult to test.

**Comment by sobitneupane** [comment] 2023-07-24 16:26
Requested payment on newDot.

**Comment by michaelhaxhiu** [comment] 2023-07-26 19:31
cool, all set - closing.

**Closed by michaelhaxhiu** 2023-07-26 19:31 UTC
Labels: External, Daily, Overdue, Awaiting Payment, Bug

**Comment by JmillsExpensify** [comment] 2023-07-27 23:42
Reviewed details for @sobitneupane. This is accurate based on summary from Business Reviewer and approved for payment in NewDot.
