### ISSUE TITLE
[HOLD for payment 2023-10-09] 🟡 [$500] [Distance] - Hide the map scale control on Android

### ISSUE THREAD

**Issue by kavimuru** [Expensify/App#27620] opened 2023-09-17 15:12 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Open request money
2. Change the tab to distance
3. Select a start or finish distance
## Expected Result: 
The map should show the scale control as in the android app or it should be removed from the android too
## Actual Result: 
The scale control is hidden on the map of the web and mweb

## Workaround:
Can the user still use Expensify without this being fixed? Have you informed them of the workaround?

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [x] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [x] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 1.3.70-5
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation

<img src="https://github.com/Expensify/App/assets/43996225/cfd47ab2-eda3-4129-9d1d-1a3dc10e49ee" width="40%" height="40%">

![scale control web](https://github.com/Expensify/App/assets/43996225/2249288b-d82b-4c29-9bb9-38f148632303)

![Snip - New Expensify - Google Chrome (7)](https://github.com/Expensify/App/assets/43996225/353d74a8-a108-4bfc-87d1-f31fb3b3c0ec)

**Expensify/Expensify Issue URL:**
**Issue reported by:** @jo-ui
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1694616305506719

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~010c8a9994720dfe80</li>
        <li>Upwork Job ID: 1703426646592622592</li>
        <li>Last Price Increase: 2023-09-17</li>
<li>Automatic offers: </li>
<ul>
<li>ZhenjaHorbach | Contributor | 26813126</li>
<li>jo-ui | Reporter | 26813129</li>
</ul></li>
    </ul>
</details>

**Comment by desirekaleba** [comment] 2023-09-17 15:42
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
The problem we are trying to solve is the absence of a scale control on the Mapbox map displayed within the MapView component in a React Native application using the react-map-gl library. A scale control is a useful feature for users to understand the map's scale and distance between points, enhancing the user experience and providing valuable geographical context.

### What is the root cause of that problem?
The root cause of this problem is that the ScaleControl component was not integrated into the existing codebase for the MapView component. The absence of this component is the reason why the scale control is missing from the map.

### What changes do you think we should make in order to solve the problem?

To solve this problem, we propose the following changes:

1. Import the ScaleControl component from the react-map-gl library at the beginning of the MapView component file.
2. Insert the ScaleControl component within the Map component, allowing it to be displayed on the map.
3. Customize the appearance of the scale control by setting the `maxWidth`, `unit`, and the `position` props according to the desired design and unit preference.

These changes will add a scale control to the Mapbox map within the `MapView` component under `src/components/MapView/MapView.web.tsx`

### What alternative solutions did you explore? (Optional)

**Reminder:** Please use plain English, be brief and avoid jargon. Feel free to use images, charts or pseudo-code if necessary. Do not post large multi-line diffs or write walls of text. Do not create PRs unless you have been hired for this job.

**Comment by desirekaleba** [comment] 2023-09-17 15:48
Contributor details
Your Expensify account email: desirekaleba@gmail.com
Upwork Profile Link: [Upwork link](https://www.upwork.com/freelancers/~0112ace296ad18280c)

**Comment by desirekaleba** [comment] 2023-09-17 16:18
Contributor details
Your Expensify account email: desirekaleba@gmail.com
Upwork Profile Link: https://www.upwork.com/freelancers/~0112ace296ad18280c

**Comment by PiyushChandra17** [comment] 2023-09-17 16:25
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
The scale control is hidden on the map of the web and mweb

### What is the root cause of that problem?
We are not rendering any `ScaleControl` component here in `Map`

https://github.com/Expensify/App/blob/c77814fd5e643cba78e8c8294370d78f633a59c5/src/components/MapView/MapView.web.tsx#L67

Hence this is the root cause

### What changes do you think we should make in order to solve the problem?
We need to apply following changes:

1. import ScaleControl from 'react-map-gl'
2. Render this ScaleControl component anywhere in `<Map />`
3. We need to add position: "top-left", whereas maxWidth: "100" and unit: "metric" is set by default options 

### What alternative solutions did you explore? (Optional)
NA

## Result:
<img width="344" alt="Screenshot 2023-09-17 at 9 45 18 PM" src="https://github.com/Expensify/App/assets/47579287/7b11df4d-fdfb-4d76-824f-95173dcd4c13">
![Screenshot_1694967815](https://github.com/Expensify/App/assets/47579287/03d3a619-3578-4030-91da-916aee69146f)

**Comment by sakluger** [comment] 2023-09-18 07:59
I posted in the Wave5 slack channel since this is related to distance requests.

**Comment by arosiclair** [comment] 2023-09-20 04:34
Need to get these proposals reviewed ASAP assigning a new C+

**Comment by arosiclair** [comment] 2023-09-20 04:35
@sobitneupane do you have time to review these proposals?

**Comment by sobitneupane** [comment] 2023-09-21 07:55
[Proposal](https://github.com/Expensify/App/issues/27620#issuecomment-1722499948) from @ZhenjaHorbach looks good to me.

@ZhenjaHorbach I believe we should enhance its appearance to make it more attractive using style prop in Scalecontrol. 

🎀 👀 🎀 C+ reviewed

**Comment by tgolen** [comment] 2023-09-22 07:24
Hi, I'm jumping in here from the project team. For this issue, the correct solution is to remove it from all platforms. We didn't intend for it to be shown anywhere, so the bug is only that it's appearing on android, and so all we need to do is remove it there.

That was one of the alternatives in the original proposal, so I think we are fine to keep moving forward with @ZhenjaHorbach.

**Comment by arosiclair** [comment] 2023-09-22 09:08
Sounds good let's go with @ZhenjaHorbach's alternate proposal

**Comment by sobitneupane** [comment] 2023-10-09 08:09
> **BugZero Checklist:** The PR fixing this issue has been merged! The following checklist ([instructions](https://stackoverflow.com/c/expensify/questions/14574)) will need to be completed before the issue can be closed:
> 
> * [ ]  [@sobitneupane] The PR that introduced the bug has been identified. Link to the PR:

https://github.com/Expensify/App/pull/25161
> * [ ]  [@sobitneupane] The offending PR has been commented on, pointing out the bug it caused and why, so the author and reviewers can learn from the mistake. Link to comment:

This is a small UI inconsistency.
> * [ ]  [@sobitneupane] A discussion in #expensify-bugs has been started about whether any other steps should be taken (e.g. updating the PR review checklist) in order to catch this type of bug sooner. Link to discussion:

N/A
> * [ ]  [@sobitneupane] Determine if we should create a regression test for this bug.

Yes.
> * [ ]  [@sobitneupane] If we decide to create a regression test for the bug, please propose the [regression test](https://github.com/Expensify/App/blob/main/contributingGuides/REGRESSION_TEST_BEST_PRACTICES.md) steps to ensure the same bug will not reach production again.

**Comment by sobitneupane** [comment] 2023-10-09 08:10
**Regression Test Proposal**

1. Open request money
2. Change the tab to distance
3. Verify that scale control is not displayed in top left corner of the map.

Do we agree 👍 or 👎

**Comment by arosiclair** [comment] 2023-10-11 13:09
No need for a regression test for a small cosmetic change IMO

**Comment by sakluger** [comment] 2023-10-12 06:03
Yeah we probably don't need a regression test for this.

**Summarizing payouts for this issue:**

Reporter: @jo-ui $50 (paid via Upwork)
Contributor: @ZhenjaHorbach $750 (paid via Upwork)
Contributor+: @sobitneupane $750 (payable via Manual Request)

Above payments include efficiency bonus 🎉 
Upwork job: https://www.upwork.com/jobs/~010c8a9994720dfe80

**Comment by sakluger** [comment] 2023-10-12 06:04
@sobitneupane can you let me know once you've submitted the manual request? I'll close the issue once that's done.

**Comment by sakluger** [comment] 2023-10-16 17:32
@sobitneupane can you let me know if you need this to remain open, or if you are tracking outside of Expensify?

Switching this to a weekly for now to clean up my tasks list.

**Closed** 2023-10-19 17:43 UTC
Labels: External, Weekly, Awaiting Payment, Bug

**Comment by sobitneupane** [comment] 2023-10-30 14:02
https://github.com/Expensify/App/issues/27620#issuecomment-1758961749

Requested payment on newDot.

**Comment by JmillsExpensify** [comment] 2023-11-03 22:21
$750 payment approved for @sobitneupane based on [this comment](https://github.com/Expensify/App/issues/27620#issuecomment-1758961749).
