### ISSUE TITLE
[HOLD for payment 2023-09-04] [$1000] App changes focus from edit message composer to send message composer when mark as unread

### ISSUE THREAD

**Issue by kavimuru** [Expensify/App#23898] opened 2023-07-30 20:40 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Open any report
2. Send any message
3. Hover message and click edit
4. Right click on report on LHN => mark as unread
5. Observe that the app loses focus on edit composer and switches to focus send message composer
## Expected Result: 
App still keeps focus on the message being edited
## Actual Result: 
App loses focus on edit composer and switches to focus send message composer

## Workaround:
Can the user still use Expensify without this being fixed? Have you informed them of the workaround?

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [x] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 1.3.47-2
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/43996225/b6ed92a9-4f01-42d6-bcf9-5b2b3c53809f

https://github.com/Expensify/App/assets/43996225/717d0da9-2af3-48d5-a1ab-0babe3ad37c2

**Expensify/Expensify Issue URL:**
**Issue reported by:** @namhihi237 
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1690700101909109

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~012c0c567372dabdf6</li>
        <li>Upwork Job ID: 1686829305551839232</li>
        <li>Last Price Increase: 2023-08-09</li>
<li>Automatic offers: </li>
<ul>
<li>Ollyws | Reviewer | 26050166</li>
<li>tienifr | Contributor | 26050168</li>
<li>namhihi237 | Reporter | 26050169</li>
</ul></li>
    </ul>
</details>

**Comment by s-alves10** [comment] 2023-07-30 22:15
## Proposal

### Please re-state the problem that we are trying to solve in this issue.

App changes focus from edit message composer to main composer when mark as unread in LHN

### What is the root cause of that problem?

When pressing `mark as unread`, `ReportActionComposeFocusManager.focus` function is called as you can see here.
https://github.com/Expensify/App/blob/eb020063789091eb2e3086b5b54af3ead8436645/src/pages/home/report/ContextMenu/ContextMenuActions.js#L247

We set this callback function when we open any chat
https://github.com/Expensify/App/blob/eb020063789091eb2e3086b5b54af3ead8436645/src/pages/home/report/ReportActionCompose.js#L248-L253

But we setup focus callback only on main composer. So the `focus` function of the main composer would be called regardless of which is focused at the time menu is selected.

The root cause of this issue is that we only setup focus callback only for the main composer.

### What changes do you think we should make in order to solve the problem?

The focus manager should be setup for any composer with focus. This is reasonable and consistent to manager's purpose

We can solve this issue by setup focus callback when any composer gets focused
1. Move the `setupComposeFocusManager` definition from [ReportActionCompose](https://github.com/Expensify/App/blob/main/src/pages/home/report/ReportActionCompose.js) to [Composer](https://github.com/Expensify/App/blob/main/src/components/Composer/index.js) and remove all call of it.

https://github.com/Expensify/App/blob/eb020063789091eb2e3086b5b54af3ead8436645/src/pages/home/report/ReportActionCompose.js#L312-L322

2. Add onFocus event handler to the Composer's RNTextInput
```
        onFocus={(e) => {
            this.setUpComposeFocusManager();
            if (this.props.onFocus) {
                this.props.onFocus(e);
            }
        }}
```

This works as expected


<details>
    <summary>Result</summary>

https://github.com/Expensify/App/assets/126839717/48bb63a4-3f01-4206-8af0-216debab44e1

</details>

### What alternative solutions did you explore? (Optional)

**Comment by maddylewis** [comment] 2023-08-02 20:00
added external label so that C+ can review existing proposals

**Comment by s-alves10** [comment] 2023-08-03 13:52
## Proposal
[Updated](https://github.com/Expensify/App/issues/23898#issuecomment-1657278576)

**Comment by maddylewis** [comment] 2023-08-06 19:21
hiya @alexpensify - i am OOO until ~Aug 20. 

- A C+ has already been assigned to the issue and is reviewing proposals
- This is the latest update - https://github.com/Expensify/App/issues/23898#issuecomment-1666804701
- Once we decide on a proposal, the C+ will hire the contributor and this will be like any other BZ issue 👍

**Comment by s-alves10** [comment] 2023-08-09 11:50
@Ollyws 

I'm not suggesting to add callbacks for every `reportActionID`.
I suggested to add a callback with its `reportActionID`. On unmount, we need to clear the callback but we don't need to clear the callback if the message in edit mode isn't focused. So we need to check if the current message has focus by comparing its `reportActionID` and the one stored with callback. 

@tienifr suggested to clear the callback on `deleteDraft` method, but this is not true. Assuming two messages are in edit mode. What if the message we're deleting hasn't focus? Then the focus was moved to main composer unexpectedly. Because of this, we need to verify if the current message is focused. 

In addition, we need to add `clear` logic to unmount handler because the message in edit mode can be deleted for some reasons.

We're using similar logic for `EmojiPicker` already and I'm very familiar with that because I was the contributor for similar issues.
It looks like @tienifr didn't care about these exceptions.

**Comment by s-alves10** [comment] 2023-08-10 03:03
Yeah. When two message are in edit mode, if one message is deleted, the focus was moved to the main composer though the other message was focused

@tienifr 
Do you think this is an expected behavior? Or should we create a GH issue for that?

> As long as the approach is solid, I think it's ok for other minor details to be addressed in the PR.

I've proposed a solution with basic idea at first, but didn't consider some exceptions. This is my fault. We need to provide concrete solution, I think

**Comment by robertjchen** [comment] 2023-08-10 13:42
Thanks for the discussion here! Having considered all of the above, I'd say we move forward with @tienifr 's proposal on this one.

> I think it's expected since when clicking outside, the composers should be blurred

As for this, let's stick with maintaining existing behavior for now but definitely discuss this on Slack as a potential improvement to be made. 👍

**Comment by maddylewis** [comment] 2023-09-05 13:53
@namhihi237 / @tienifr are paid. offer sent to @Ollyws.

**Comment by maddylewis** [comment] 2023-09-05 21:53
everyone is paid - closing!

**Closed by maddylewis** 2023-09-05 21:53 UTC
Labels: External, Daily, Awaiting Payment, Bug
