### ISSUE TITLE
mWeb - Extra margin above country textbox in country selection screen

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#23761] opened 2023-07-27 20:47 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Click on settings -> Click profile
2. Click on Personal details -> Click Home address
3. Click country

## Expected Result:
There should regular margin above country textfield

## Actual Result:
Shows extra margin above country textfield

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [x] iOS / Safari
- [ ] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 1.3.46-0
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/93399543/beb6e804-d4d2-49d1-9bd5-7c263b82a06e

![IMG_6568](https://github.com/Expensify/App/assets/93399543/edcb2800-aee3-4eae-9d10-da64bf72b7e1)

**Expensify/Expensify Issue URL:**
**Issue reported by:** @DinalJivani
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1690402755216219

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by daordonez11** [comment] 2023-07-27 21:02
Same RCA than https://github.com/Expensify/App/issues/22560  it is  fixed with https://github.com/Expensify/App/pull/23538

**Comment by johncschuster** [comment] 2023-07-30 16:52
Thanks for calling that out, @daordonez11!

**Comment by DanutGavrus** [comment] 2023-07-31 10:11
@daordonez11 @johncschuster
PR has been deployed to **staging**. This reported issue seems fixed by it now. Could you confirm?

**Comment by johncschuster** [comment] 2023-08-01 22:17
@kbecciv, can you try reproducing the behavior on staging to see if it persists?

**Comment by johncschuster** [comment] 2023-08-02 23:33
@kbecciv bump!

**Comment by johncschuster** [comment] 2023-08-07 21:22
Bump!

**Comment by DinalJivani** [comment] 2023-08-07 21:30
@johncschuster 
@kbecciv isn’t available from last few days. 

I tested this issue and I see it has been fixed with other PR.

**Comment by johncschuster** [comment] 2023-08-08 20:56
Thanks @DinalJivani. Are you able to locate the PR that fixed this behavior?

**Comment by DanutGavrus** [comment] 2023-08-09 07:08
@johncschuster I think it's this one https://github.com/Expensify/App/pull/23538 as it reduced the bottom margin which fixed https://github.com/Expensify/App/issues/22560 and removed the top margin which fixed this issue https://github.com/Expensify/App/issues/23761 in advance.

**Comment by DinalJivani** [comment] 2023-08-09 08:37
> Same RCA than #22560 it is fixed with #23538
> cc @cead22 who approved fixing PR

as mentioned here I think above PR resolved this issue

**Comment by johncschuster** [comment] 2023-08-14 22:02
Ok! It looks like this behavior is no longer reproducible. Closing!

**Closed by johncschuster** 2023-08-14 22:02 UTC
Labels: Daily, Overdue, Bug
