### ISSUE TITLE
[$250] RHP - Notification preference panel shows different behavior when opening

### ISSUE THREAD

**Issue by kavimuru** [Expensify/App#40550] opened 2024-04-19 10:33 UTC
Held on https://github.com/Expensify/App/issues/40538

If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.63-0
**Reproducible in staging?:** y
**Reproducible in production?:** no
**If this was caught during regression testing, add the test name, ID and link from TestRail:** https://expensify.testrail.io/index.php?/tests/view/4494295
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** applause internal team
**Slack conversation:**

## Action Performed:
1. Navigate to staging.new.expensify.com
2. Click on the search icon
3. Search for a user with a Gmail account which you didn't have prior conversation with and open the report
4. Click on the header
5. If Notification preference settings doesn't show up click on "Message ..." button and click on header again
6. Click on Notification preference "Notify me about new messages" button

## Expected Result:
The RHP should slide in smoothly same as production behavior

## Actual Result:
The RHP jumps in from the left in a different manner than prod behavior or any other RHP sliding behavior

## Workaround:
unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

https://github.com/Expensify/App/assets/43996225/3016ec9c-7604-42fe-9830-39edf1656c56

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01764a9f063358f182</li>
        <li>Upwork Job ID: 1781290424777859072</li>
        <li>Last Price Increase: 2024-05-10</li>
    </ul>
</details>

**Comment by kavimuru** [comment] 2024-04-19 10:46
We think this bug might be related to #vip-vsb

**Comment by garrettmknight** [comment] 2024-04-19 11:55
Confirmed the error, opening it up.

**Comment by bernhardoj** [comment] 2024-04-21 09:47
Same root cause as https://github.com/Expensify/App/issues/40538

**Comment by cristipaval** [comment] 2024-04-22 08:16
> Same root cause as #40538

Should we hold this one on it?

**Comment by cristipaval** [comment] 2024-04-30 21:01
Still on hold

**Comment by cristipaval** [comment] 2024-05-10 09:18
The hold is now removed. We need to retest to see if it's still reproducible.

**Comment by garrettmknight** [comment] 2024-05-10 17:57
Weird, now when I follow these steps:

1. Navigate to staging.new.expensify.com
2. Click on the search icon
3. Search for a user with a Gmail account which you didn't have a prior conversation with and open the report
4. Click on the header
5. If Notification preference settings doesn't show up click on "Message ..." button and click on header again

I don't actually get the option for notifications preferences as an option:

https://github.com/Expensify/App/assets/1529980/ca4aa140-6e45-4274-b661-7e3d724ebdfa

[Taking this to #expensify-bugs](https://expensify.slack.com/archives/C049HHMV9SM/p1715363574011669) 

Will hold this issue on that since I can't reproduce if the line disappears.

**Comment by cristipaval** [comment] 2024-05-13 12:17
It seems to be reproducible in [certain conditions ](https://expensify.slack.com/archives/C049HHMV9SM/p1715468517956209?thread_ts=1715363574.011669&cid=C049HHMV9SM)

**Comment by mvtglobally** [comment] 2024-05-13 14:18
Issue not reproducible during KI retests. (First week)

**Comment by garrettmknight** [comment] 2024-05-13 15:01
Can't reproduce anymore, closing.

**Closed by garrettmknight** 2024-05-13 15:01 UTC
Labels: External, Daily, Help Wanted, Bug
