### ISSUE TITLE
[HOLD for payment 2023-10-12] [HOLD for payment 2023-10-10] [$250] Settings - Green dot appears even though there is no Contact methods

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#28643] opened 2023-10-02 18:47 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Go to Settings > Profile >Contact methods

## Expected Result:
Green dot should not show

## Actual Result:
Green dot appears even though there is no Contact methods

## Workaround:
Unknown 

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android / native
- [x] Android / Chrome
- [x] iOS / native
- [x] iOS / Safari
- [x] MacOS / Chrome / Safari
- [x] MacOS / Desktop

**Version Number:** 1.3.76.0 
**Reproducible in staging?:** y
**Reproducible in production?:** n
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/93399543/ab49182a-4820-434c-8b5e-75eeac60c7b1

https://github.com/Expensify/App/assets/93399543/e87063fd-4d36-4ede-a90f-ebdd3f10cb62

https://github.com/Expensify/App/assets/93399543/3ab93ad7-de44-4315-a0f3-b1c4b6506b7b

https://github.com/Expensify/App/assets/93399543/3b3e9865-d02e-4a2d-80e1-8e134325981f

https://github.com/Expensify/App/assets/93399543/4ac1b02f-c22e-449e-bdb1-2031489287d2

https://github.com/Expensify/App/assets/93399543/1de6d0b9-f729-4c04-bdc5-fcf250b69d51

https://github.com/Expensify/App/assets/93399543/338bcf41-b6ad-4b11-9352-03d413b10430

**Expensify/Expensify Issue URL:**
**Issue reported by:** @gadhiyamanan
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1696244310530339

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01932d440331606ba1</li>
        <li>Upwork Job ID: 1709131206782132224</li>
        <li>Last Price Increase: 2023-10-03</li>
<li>Automatic offers: </li>
<ul>
<li>situchan | Contributor | 26995000</li>
<li>gadhiyamanan | Reporter | 26995001</li>
</ul></li>
    </ul>
</details>

**Comment by saranshbalyan-1234** [comment] 2023-10-02 19:21
## Proposal
### Please re-state the problem that we are trying to solve in this issue.
Getting green dot even there is no contact method.
### What is the root cause of that problem?
https://github.com/Expensify/App/blob/42e22474aff3b929d98cf176876d43b14d4476c2/src/libs/UserUtils.ts#L44-L46
In this function we are checking for validatedDate although loginList is a list (array), so the property is not directly accessible which results to undefined and ultimately return true due to !
### What changes do you think we should make in order to solve the problem?
We can return this instead of loginList.validatedDate;
```javascript
   return !Object.values(loginList).every((field) => field.validatedDate);
``` 
### What alternative solutions did you explore? (Optional)
N/A

**Comment by mountiny** [comment] 2023-10-02 19:43
@saranshbalyan-1234 reminder for any deploy blockers, always link the offending PR. Thanks

**Comment by marcaaron** [comment] 2023-10-02 20:14
I currently cannot sign into staging to verify this. Probably related to the site instability. I will try again in a bit.

**Comment by marcaaron** [comment] 2023-10-02 20:20
Though it looks like this is the PR where it was introduced: 

https://github.com/Expensify/App/pull/27778/files

![2023-10-02_10-20-20](https://github.com/Expensify/App/assets/32969087/6fb9f27e-f0f1-4e94-a8a0-df146fde44ef)

**Comment by marcaaron** [comment] 2023-10-02 20:28
cc @blazejkustra - but I'm guessing we did not intend to change the signature here and just got tripped up by the wrong type.

**Comment by mountiny** [comment] 2023-10-02 22:42
Blazej wont get online for next probably 8-10 hours, can we proactively revert the PR if we confirm this fixes the blocker? @marcaaron thanks!

**Comment by marcaaron** [comment] 2023-10-03 00:35
it's probably easier to just fix it. but you are the deployer so lmk how you want to proceed.

**Comment by marcaaron** [comment] 2023-10-03 00:37
Oh I see you meant just for TESTING haha I have a branch here. ✈️ LAG

**Comment by marcaaron** [comment] 2023-10-03 00:37
https://github.com/Expensify/App/pull/28668

**Comment by marcaaron** [comment] 2023-10-03 00:39
Yes it's that PR.

**Comment by aldo-expensify** [comment] 2023-10-03 04:20
@mountiny @marcaaron I see that a [revert](https://github.com/Expensify/App/pull/28668) was created, but not merged yet. I'm starting my day. Do you want to continue with the revert? I can also work on quick  fix if we think it is better than reverting.

**Comment by aldo-expensify** [comment] 2023-10-03 05:57
Left a PR here in case we want to fix instead of revert: https://github.com/Expensify/App/pull/28686

**Comment by mountiny** [comment] 2023-10-03 07:45
If we got fix that is better, thank you everyone ❤️ going to review

**Comment by mountiny** [comment] 2023-10-03 09:01
@trjExpensify the payments here are $250 to @situchan for deploy blocker PR review and $50 to @gadhiyamanan for reporting

**Comment by trjExpensify** [comment] 2023-10-03 12:42
Sounds good! 👍

**Comment by marcaaron** [comment] 2023-10-10 18:19
@situchan I think we are waiting for the checklist items to be completed here

**Comment by situchan** [comment] 2023-10-10 18:27
- [x] The PR that introduced the bug has been identified. Link to the PR: https://github.com/Expensify/App/pull/27778
- [x] The offending PR has been commented on, pointing out the bug it caused and why, so the author and reviewers can learn from the mistake. Link to comment: https://github.com/Expensify/App/pull/27778/files#r1343470914
- [x] A discussion in #expensify-bugs has been started about whether any other steps should be taken (e.g. updating the PR review checklist) in order to catch this type of bug sooner. Link to discussion: N/A
- [x] Determine if we should create a regression test for this bug.
- [x] If we decide to create a [regression test](https://github.com/Expensify/App/blob/main/contributingGuides/REGRESSION_TEST_BEST_PRACTICES.md) for the bug, please propose the regression test steps to ensure the same bug will not reach production again.

This bug should have been caught earlier during PR review if they fully tested their code changes.
Now that C+ is able to review TS migration PRs, there will be less chance of having this kind of regression.
As such, I don't propose regression test.

**Comment by trjExpensify** [comment] 2023-10-11 10:56
Nice, thanks! Confirming payments as follows from [here](https://github.com/Expensify/App/issues/28643#issuecomment-1744538356). 

@situchan $250 for the DB PR review
@gadhiyamanan $50 for the bug report. 

Settled up, and closing!

**Closed by trjExpensify** 2023-10-11 10:56 UTC
Labels: External, Engineering, Daily, Awaiting Payment, Bug
