### ISSUE TITLE
[$1000] Can't open DM chat with workspace admin after a money request has been done

### ISSUE THREAD

**Issue by kavimuru** [Expensify/App#23335] opened 2023-07-21 04:20 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:

1. Create 2 accounts. In the video, [6060@expensifail.com](mailto:6060@expensifail.com) is the workspace owner and [6061@expensifail.com](mailto:6061@expensifail.com) is an invited member
2. [6061@expensifail.com](mailto:6061@expensifail.com) requests money in their workspace chat
3. [6061@expensifail.com](mailto:6061@expensifail.com) logs out and logs back in
4. [6061@expensifail.com](mailto:6061@expensifail.com) tries to start a DM chat with [6060@expensifail.com](mailto:6060@expensifail.com) using the search

## Expected result: 
An option should appear to start a conversation with [6060@expensifail.com](mailto:6060@expensifail.com) outside of the workspace
## Actual result: 
The search results only show the workspace chat and the expense report

Note: The option in the search to open a direct chat with [6060@expensifail.com](mailto:6060@expensifail.com) did appear before logging out and logging back in.

## Workaround:
Can the user still use Expensify without this being fixed? Have you informed them of the workaround?

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [x] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** v1.3.46-1
**Reproducible in staging?:** yes
**Reproducible in production?:** haven't tested
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/43996225/55d08c51-d349-4222-adbb-534b5625f0f9

**Expensify/Expensify Issue URL:**
**Issue reported by:** @aldo-expensify 
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1689791751171199

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01b95a04b132cfe269</li>
        <li>Upwork Job ID: 1684644869847134208</li>
        <li>Last Price Increase: 2023-07-27</li>
    </ul>
</details>

**Comment by michaelhaxhiu** [comment] 2023-07-27 12:59
cc @aldo-expensify do you think this needs to be `Internal` or `External` for the fix?

**Comment by aldo-expensify** [comment] 2023-07-27 19:14
I haven't really investigated the source so I can't really tell you, for sure, but I lean toward `External`.

I tested this in staging and it can be reproduced there too, so I updated the issue's title and description.
<img width="451" alt="image" src="https://github.com/Expensify/App/assets/87341702/8b55226d-2bc2-4aa3-9963-4e7e6557b9be">

**Comment by michaelhaxhiu** [comment] 2023-07-27 19:19
Bless you 🙏

**Comment by michaelhaxhiu** [comment] 2023-07-27 19:20
Let's try for external and see if this is resolvable by our contributors :)

**Comment by michaelhaxhiu** [comment] 2023-07-31 13:23
Awaiting proposals still

**Comment by Victor-Nyagudi** [comment] 2023-08-01 12:13
I'm not sure how to reproduce this as a contributor. 

When a workspace is created in staging, the only rooms that appear are `#announce` and `#admins`. 

Unless I'm missing something, the actual workspace i.e. "Expensifail's Workspace" above (the chat with a square image and a small circular one for the invited member) only works in DEV for me after enabling the use of all betas in `Permissions.js`. Even then, I can only interact with it after forcing offline, otherwise the workspace disappears when I click it. 

In addition, both the workspace owner and the invitee will need to have access to the workspace, but I'm not sure I can log into two different accounts in DEV to access the same workspace. 

If any of you have some more information on how I can reproduce this, that would be appreciated.

**Comment by aldo-expensify** [comment] 2023-08-01 17:52
Thanks for @Victor-Nyagudi for investigating

> Unless I'm missing something, the actual workspace i.e. "Expensifail's Workspace" above (the chat with a square image and a small circular one for the invited member) only works in DEV for me after enabling the use of all betas in Permissions.js. Even then, I can only interact with it after forcing offline, otherwise the workspace disappears when I click it.

I'm not 100% familiarized for which accounts a workspace's expense chants are enabled, but you may be right about it being behind a beta. The feature being behind a beta would explain why it works while offline when you tweak `Permissions.js`, but then the chat goes away because the backend knows you are not in such beta.

I'll remove the `Help Wanted` for now since it may not be reproducible for contributors.

I'm trying to confirm here if contributors can get backend beta access: https://expensify.slack.com/archives/C02NK2DQWUX/p1690912347652629?thread_ts=1685539652.381539&cid=C02NK2DQWUX

**Comment by michaelhaxhiu** [comment] 2023-08-03 16:30
Let's go `Internal` since the discussion from your post @aldo-expensify suggests we can't open the Beta just yet.

**Comment by michaelhaxhiu** [comment] 2023-08-03 16:32
flo is OOO, un-assigning & re-assigning

**Comment by michaelhaxhiu** [comment] 2023-08-04 15:53
Note: I'm preparing to go OOO for ~2 weeks and need a BZ buddy to watch over this in the meantime. 🙏

Next step: Please ensure that we push this forward from an `Internal` perspective.

Thanks in advance @kevinksullivan, I can take this back when I get back if it's not complete before then.

**Comment by kevinksullivan** [comment] 2023-08-04 22:27
I am also going ooo for the week so I am making my rounds doing the same 😅 . Reapplying bug label.

**Comment by arosiclair** [comment] 2023-08-07 16:30
Not able to reproduce on `main`. The workspace admin appears as an option and you can open a DM with them. Trying again on staging

**Comment by arosiclair** [comment] 2023-08-07 16:53
Yeah cannot reproduce on staging **v1.3.50-3** either:

![Screenshot 2023-08-07 at 12 51 41 PM](https://github.com/Expensify/App/assets/6833644/e3642e9e-db02-41ad-9ae8-0a58183601e1)

This looks to be fixed so closing out

**Closed by arosiclair** 2023-08-07 16:53 UTC
Labels: Engineering, Daily, Internal, Bug
