### ISSUE TITLE
[$250] IOU - On creating manual request, "receipt required over" error displayed under thumbnail

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#34511] opened 2024-01-15 16:24 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.25.1
**Reproducible in staging?:**Y
**Reproducible in production?:** N
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** Applause - Internal Team
**Slack conversation:**

## Action Performed:
1. Go to https://staging.new.expensify.com/
2. Tap fab ---- request money --- Manual
3. Enter an amount and tap next
4. Select a user
5. Tap request money
6. Tap in newly created request to open IOU detail page
7. Note "receipt required over" error message displayed under thumbnail.
8. Tap plus on thumbnail and upload an image
9. Note even after receipt added error is displayed

## Expected Result:
On creating manual request, "receipt required over" error message must not be displayed under thumbnail

## Actual Result:
On creating manual request, "receipt required over" error message displayed under thumbnail. Even after adding receipt, error is shown

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [x] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details> 

https://github.com/Expensify/App/assets/78819774/e99d1b22-f1eb-4e7b-9ca0-a5da2a4c9828

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~0166535ae538f22ce3</li>
        <li>Upwork Job ID: 1746942190539268096</li>
        <li>Last Price Increase: 2024-01-15</li>
    </ul>
</details>

**Comment by mountiny** [comment] 2024-01-16 09:45
I cannot reproduce this

**Comment by cead22** [comment] 2024-01-16 19:22
You have to be in the violations beta to see the violations, and I added several email addresses that belong to Situ to the beta. 

This will all improve as we continue implementing violations, so I'm closing this for now

**Closed by cead22** 2024-01-16 19:22 UTC
Labels: External, Engineering, Daily, Help Wanted
