### ISSUE TITLE
 Send invoice - Invoice disappears after created

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#43134] opened 2024-06-05 17:28 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.79-8
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**If this was caught during regression testing, add the test name, ID and link from TestRail:** N/A
**Issue reported by:** Applause - Internal Team

**Issue found when executing PR** https://github.com/Expensify/App/pull/43095
## Action Performed:
1. Open the App
2. Tap FAB -> Send invoice
3. Enter an amount and tap Next
4. Select a user
5. Send an invoice

## Expected Result:
The invoice was created, and there are no errors from the server

## Actual Result:
Invoice disappears after created

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details> 

https://github.com/Expensify/App/assets/78819774/ab564b42-e2cd-4d34-9da9-aa0f1e40bb1a

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by lanitochka17** [comment] 2024-06-05 17:29
@adelekennedy  FYI I haven't added the External label as I wasn't 100% sure about this issue. Please take a look and add the label if you agree it's a bug and can be handled by external contributors

**Comment by VickyStash** [comment] 2024-06-06 10:17
@lanitochka17 I wasn't able to reproduce the issue. Does it still exist for you?

https://github.com/Expensify/App/assets/23176449/5b3a6193-d499-4d24-9a35-e990af79cde5

cc @cristipaval

**Comment by VickyStash** [comment] 2024-06-07 13:34
@cristipaval I've tried several times and I can't reproduce the issue

**Comment by cristipaval** [comment] 2024-06-10 14:35
I'll close it out.

**Comment by cristipaval** [comment] 2024-06-10 14:36
@lanitochka17 feel free to reopen if you still can reproduce

**Closed by cristipaval** 2024-06-10 14:35 UTC
Labels: Daily, Overdue, Bug
