### ISSUE TITLE
[$1000] IOS -  Tap on email opens task assignee view

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#22012] opened 2023-07-01 12:00 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Assign task
2. Fill in fields
3. Click next
4. Select an assignee
5. Click on confirm task
6. On new chat tap on email or name
7. Assignee view is displayed

## Expected Result:
Tap on email opens email profile view

## Actual Result:
Tap on email opens task assignee view

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [x] iOS / native
- [ ] iOS / Safari
- [ ] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 1.3.34-1
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/93399543/7328977f-7cdc-41e7-b220-1e92be73c5ad

https://github.com/Expensify/App/assets/93399543/564b6b0a-bee2-40f1-af93-046ed47d1cd3

**Expensify/Expensify Issue URL:**
**Issue reported by:** @eusalazar
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1688091412727329

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01d91bc7a8fe318635</li>
        <li>Upwork Job ID: 1676164085917446144</li>
        <li>Last Price Increase: 2023-07-04</li>
    </ul>
</details>

**Comment by jeet-dhandha** [comment] 2023-07-01 17:18
## Proposal
### Please re-state the problem that we are trying to solve in this issue.
- Back Press of Assignee Change screen is navigating to `NEW_TASK` route instead of previous route.

### What is the root cause of that problem?
- Root cause is the default path NEW_TASK in `Navigation.goBack` function.
```js
<HeaderWithBackButton
    title={props.translate('newTaskPage.assignee')}
    onBackButtonPress={() =>  Navigation.goBack(ROUTES.NEW_TASK)}
/>
```

### What changes do you think we should make in order to solve the problem?
- If we are navigating from edit task then we should pass `null` as argument in `Navigation.goBack`  function, which will navigate it back to previous path.

```js
const isEditing = props.task.report.reportID === props.route.params.reportID;

...rest code

<HeaderWithBackButton
    title={props.translate('newTaskPage.assignee')}
    onBackButtonPress={() =>  Navigation.goBack(isEditing ? null : ROUTES.NEW_TASK)}
/>
```

### What alternative solutions did you explore? (Optional)
- N/A

**Comment by laurenreidexpensify** [comment] 2023-07-04 09:40
Revuewed, not overdue

**Comment by jeet-dhandha** [comment] 2023-07-04 17:08
Yes but on pressing back on the screen instead of taking to task its redirecting to Empty New Task View.

**Comment by jeet-dhandha** [comment] 2023-07-04 17:10
Close this one then.

**Comment by jeet-dhandha** [comment] 2023-07-05 03:38
Whenever anyone get's time please close this.

**Closed** 2023-07-06 07:16 UTC
Labels: External, Daily, Help Wanted, Bug
