### ISSUE TITLE
[$500] Web - Assigned task title doesn't update when copying after changing it

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#26571] opened 2023-09-02 18:09 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Click the plus sign and select "Assign Task."
2. Add a title, share it somewhere, and assign it to someone.
3. Change the title of the assigned task.
4. Go to the parent thread, hover over the title, Copy it, and paste it into the chat compose box.

## Expected Result:
The copied title should reflect the updated title when changes are made to the assigned task title.

## Actual Result:
The app continues to copy the original title even after the user has updated it for the assigned task.

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [x] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 1.3.62.0
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/93399543/613225db-c48c-4d2f-af89-996806b0c085

https://github.com/Expensify/App/assets/93399543/7009ce36-1067-4708-8dc7-bb4fb5444554

**Expensify/Expensify Issue URL:**
**Issue reported by:** @oleksandr-pantsyr
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1693227344359139

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~0156e96662dd576f73</li>
        <li>Upwork Job ID: 1699481737103171584</li>
        <li>Last Price Increase: 2023-09-06</li>
    </ul>
</details>

**Comment by ahmedGaber93** [comment] 2023-09-02 18:09
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
Assigned task title not updated when copying after changing title
### What is the root cause of that problem?
Inconsistent between two text, the displayed text is the translated for actionName + task title, but the copied text is the originalMessage html
### What changes do you think we should make in order to solve the problem?
We need to copy **the translated for actionName + task title** instead of originalMessage html 





```javascript
function getTaskStatusMessageText(actionName, reportID) {
    let taskStatusText = '';
    switch (actionName) {
        case CONST.REPORT.ACTIONS.TYPE.TASKCOMPLETED:
            taskStatusText = Localize.translateLocal('task.messages.completed');
            break;
        case CONST.REPORT.ACTIONS.TYPE.TASKCANCELLED:
            taskStatusText = Localize.translateLocal('task.messages.canceled');
            break;
        case CONST.REPORT.ACTIONS.TYPE.TASKREOPENED:
            taskStatusText = Localize.translateLocal('task.messages.reopened');
            break;
        default:
            taskStatusText = Localize.translateLocal('task.task');
    }

    return `${taskStatusText} ${allReports[reportID].reportName}`;
}
```


and use it [here](https://github.com/Expensify/App/blob/b226893b81f1e160bef4a6821cee19c8a03bcd24/src/pages/home/report/ContextMenu/ContextMenuActions.js#L190)
```javascript

onPress: (closePopover, {reportAction, selection, reportID}) => {
  // const messageHtml = isTaskAction ? lodashGet(originalMessage, 'html', '') : lodashGet(message, 'html', '');
  const messageHtml = isTaskAction ? ReportActionsUtils.getTaskStatusMessageText(reportAction.actionName, reportID) : lodashGet(message, 'html', '');
```

The function can use also in TaskAction.js
### What alternative solutions did you explore? (Optional)
we can use `reportAction.childReportName`  for task title and create a function in `ReportActionsUtils.js` to get translated value for actionName like the above (taskStatusText part).

**Comment by anmurali** [comment] 2023-09-06 00:44
I am really swamped right now and have to prep for Saastr keynote day after at some point. So going to rotate this.

**Comment by kbecciv** [comment] 2023-09-06 21:53
Updated already

**Comment by BhuvaneshPatil** [comment] 2023-09-11 10:48
original proposal - https://github.com/Expensify/App/issues/26664#issuecomment-1710460642

## Proposal

### Please re-state the problem that we are trying to solve in this issue.
The updated amount is not copied to clipboard

### What is the root cause of that problem?
We are getting the copied text from `html` property but if we debug that, html property shows the previous value
<img width="1169" alt="Screenshot 2023-09-07 at 9 55 17 PM" src="https://github.com/Expensify/App/assets/27822551/ba181aaa-618f-4883-8c31-b36ddbf79662">

That's why we are not getting updated value.

### What changes do you think we should make in order to solve the problem?
To get the value of text correctly we should notice how it's being done in `MoneyRequestPreview`.
We use `getTransactionDetails()` method for getting required fields.
- amount 
- currency
- comment
- merchant
from `transaction`. We have transactionId from `originalMessage`
<img width="380" alt="Screenshot 2023-09-07 at 9 59 56 PM" src="https://github.com/Expensify/App/assets/27822551/06b8f6c4-b861-43a1-a1ae-1953f564baaa">


We can add new check for checking if the action is IOU or not (which is in case of money request preview)
And handle that separately.

More concisely - 
- Create a new method that will give us final string in case of IOU in `ContextMenuAction`

There is another caveat to this, handling in case of description is present.

We need confirmation from expensify how to handle that, current behaviour is `requested ₹343.00 for abdasd`

function will look something like this (needs some polishing)
```js
function getTransactionMessage(reportAction) {
    const originalMessage = _.get(reportAction, 'originalMessage', {});
    // get transactionId
    const transactionId = _.get(originalMessage, 'IOUTransactionID', 0);
    const transaction = getTransaction(transactionId);
    const reportID = _.get(transaction, 'reportID');
    const report = lodashGet(allReports, `${ONYXKEYS.COLLECTION.REPORT}${reportID}`, {}) || {};
    const details = {
        created: getCreated(transaction),
        amount: getAmount(transaction, lodashGet(report, 'type') === CONST.REPORT.TYPE.EXPENSE),
        currency: getCurrency(transaction),
        comment: getDescription(transaction),
        merchant: getMerchant(transaction),
    };

    return `requested ${CurrencyUtils.convertToDisplayString(details.amount, details.currency)}${details.comment && ` for ${details.comment}`}`;
}
```

```js
else if (isIOUAction && _.get(originalMessage, 'type', '') === CONST.IOU.REPORT_ACTION_TYPE.CREATE) {
                    const str = TransactionUtils.getTransactionMessage(reportAction);
                    Clipboard.setString(str);
                }
```

result - 

https://github.com/Expensify/App/assets/27822551/2ca39082-f75e-4bdc-b51d-c8cfb3c5c0d8

 
### What alternative solutions did you explore? (Optional)

**Comment by lschurr** [comment] 2023-09-11 15:15
@parasharrajat could you review this one?

**Comment by BhuvaneshPatil** [comment] 2023-09-11 17:03
- dupe of - https://github.com/Expensify/App/issues/26753

Same RCA and solution, might solve this one. Right, @parasharrajat

**Comment by pecanoro** [comment] 2023-09-12 04:57
Closing since we decided to fix it here: https://github.com/Expensify/App/issues/26753

**Closed by pecanoro** 2023-09-12 04:57 UTC
Labels: External, Daily, Help Wanted, Bug
