### ISSUE TITLE
[HOLD for payment 2023-07-05] [$1000] unlink button appears as disable but able to click for second time

### ISSUE THREAD

**Issue by kavimuru** [Expensify/App#20983] opened 2023-06-18 13:41 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. go to Settings > Profile > Contact methods
2. click on New contact method button
3. add userB as New contact method
4. try to login with userB in other tab
3. click on unlink button
4. try to click on disable unlink button
## Expected Result: 
user should not be able to click the unlink button
## Actual Result: 
user able to click disable button

## Workaround:
Can the user still use Expensify without this being fixed? Have you informed them of the workaround?

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [x] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 1.3.29-0
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/43996225/8e2cad70-39e7-44bc-8922-d4a91f8b96a0

https://github.com/Expensify/App/assets/43996225/6c29b112-81b8-4171-8949-b569347cc241

**Expensify/Expensify Issue URL:**
**Issue reported by:** @gadhiyamanan 
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1686314130397609
[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01343ca85e7226e7d6</li>
        <li>Upwork Job ID: 1671681149798367232</li>
        <li>Last Price Increase: 2023-06-22</li>
    </ul>
</details>

**Comment by AmjedNazzal** [comment] 2023-06-18 13:41
## Proposal

### Please re-state the problem that we are trying to solve in this issue.

unlink button appears as disable but able to click for second time

### What is the root cause of that problem?

The problem is related to the timing of the evaluation and the values being used for the disabled prop. upon logging in the children components it seem like the disabled value keeps changing between true and false depending on the value of isLoading and even when flipping isDisabled and isLoading the behaviour is still inconsistent possibly due to the use of the OR || operator in this case.
https://github.com/Expensify/App/blob/862955c2f15bce3c68d87c549b7af0e27a0eb526/src/components/Button/index.js#L276

### What changes do you think we should make in order to solve the problem?

We can change the approach to using a function with a more custom and better performing behaviour thus elemenating the unexpected behaviour of the OR || operator
```javascript
disabled={() => {
    if(this.props.isDisabled){
        return true;
    }
    if(this.props.isLoading){
        return true;
    } 
}}
```
Uppon logging and testing with this approach the isLoading seem to disable the button when there's actually loading and isDisabled is disabling the button whenever it's true.

### Result

https://github.com/Expensify/App/assets/74202751/70c6021c-bc68-44ca-a171-e8c34189946f

**Comment by bernhardoj** [comment] 2023-06-18 17:30
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
We can still press once more a "disabled" Unlink button

### What is the root cause of that problem?
The button use a disabled style but not actually disabled.

The Unlink button uses a Button component that internally uses PressableWithFeedback. Unlink button will be disabled when we either offline or a message exists (in this case the Link sent message).
https://github.com/Expensify/App/blob/bee8fd3e1634fa11761435ef405a3d3efd654b07/src/pages/signin/UnlinkLoginForm.js#L87-L93

And in Button, it will be disabled if either `isLoading` or `isDisabled` is true.
https://github.com/Expensify/App/blob/bee8fd3e1634fa11761435ef405a3d3efd654b07/src/components/Button/index.js#L276

Everything works fine here. The problem is in PressableWithFeedback. In PressableWithFeedback, we have a logic to disable the button until the onPress (if a Promise) is done. This is done to solve multiple press issue like this https://github.com/Expensify/App/issues/14572
https://github.com/Expensify/App/blob/bee8fd3e1634fa11761435ef405a3d3efd654b07/src/components/Pressable/PressableWithFeedback.js#L56-L68

As soon as we press a button, it will set the `disabled` state to true. When it's done, it will set back the `disabled` state with`props.disabled`. The issue is, every value reference in a function is captured and will never change. So, when either `runAfterInteractions` or the promise is done, it will call `setDisabled` with the value of `props.disabled` that is captured when `onPress` is called. This could potentially having an old value of `props.disabled`, which what happen in our case.

Also, we have a `useEffect` that will run every time `props.disabled` changes
https://github.com/Expensify/App/blob/bee8fd3e1634fa11761435ef405a3d3efd654b07/src/components/Pressable/PressableWithFeedback.js#L45-L47

But this doesn't help.

This is the scenario in our case:
`props.disabled` initial value is false, so `disabled` is also false
1. User press Unlink. `onPress` captures `props.disabled` current value which is `false`.
2. `setDisabled` is called with true. 
`props.disabled`: false, `disabled`: true
3. The unlink request loading happen
`props.disabled`: true, `disabled`: true
4. `runAfterInteractions` is done, `setDisabled` is called with the captured `props.disabled` which is `false`. 
`props.disabled`: true, `disabled`: false
5. Unlink request is done with the Link sent message.
`props.disabled`: true, `disabled`: false

### What changes do you think we should make in order to solve the problem?

I think the current code is kinda confusing, so I propose to modify it a little bit. 
1. Rename `disabled` state to `isPressed`
2. Add a new variable called `disabled` that use `useMemo`. It will return `props.disabled || isPressed`.
`const disabled = useMemo(() => props.disabled || isPressed, [props.disabled, isPressed]);`
3. When `onPress` is called, we will still call `setPressed` to `true`, but when it's done, we will simply call `setPressed` with `false`.

The new `disabled` is now a value that depends on both `prop.disabled` and `isPressed`. In the current implementation, we have a single state that handle both props and the press logic thing.

**Comment by trjExpensify** [comment] 2023-06-20 01:07
This is reproducible. Though the expected result in the OP is a bit ambiguous as written:

>user should not be able to click unlink button or button should not be show as disable

@gadhiyamanan I think it's better to confirm expected behaviour for your bug reports versus state them as "either or" to cover bases. 

@mananjadhav @s77rt @roryabraham I feel like you guys have some context on this PressableWithFeedback stuff from https://github.com/Expensify/App/issues/14572 as well. In this scenario, I presume the button **should not** be able to be clicked. Can you confirm, and then I'll update the OP and move it on.

**Comment by trjExpensify** [comment] 2023-06-21 22:59
^^ bump on the above please guys so we can keep this moving :)

**Comment by s77rt** [comment] 2023-06-22 00:14
@trjExpensify Oops, so sorry didn't see this until now. Feel free to DM or tag me in Slack next time. For the expected behaviour, yes you are right the button should not be clickable. For the RCA, I think both @namhihi237 and @bernhardoj provided the correct RCA. But not sure what solution to go with yet. Also I think this bug exists on `OptionRow` too since that logic is brought from there, so let's make sure we fix that as well.

**Comment by trjExpensify** [comment] 2023-06-22 00:29
Okay, excellent. I'm going to update the OP's expected behaviour and apply the label. You want to be C+ on this one given you're here already 😂?

**Comment by s77rt** [comment] 2023-06-22 00:32
That would be great :grin:

**Comment by s77rt** [comment] 2023-06-22 02:03
@AmjedNazzal Thanks for the proposal. I don't think your RCA is correct. I don't see how the OR operator is the issue here.

**Comment by s77rt** [comment] 2023-06-22 02:13
@namhihi237 Thanks for the proposal. Your RCA is correct. I like the first alternative solution (use of `disabledRef`) since it's based on the current working `useEffect` that relies on `props.disabled`. Do you think we can optimise this more or make it more clear?

**Comment by s77rt** [comment] 2023-06-22 02:15
@hungvu193 Thanks for the proposal. I don't think you RCA is correct. This kind of early return is already implemented in `GenericPressable`.

**Comment by s77rt** [comment] 2023-06-22 02:48
@bernhardoj Thanks for the proposal. Your RCA is correct. I like the proposed solution and the clean up. Can you please apply https://github.com/Expensify/App/pull/20838#discussion_r1237874928 and your solution and confirm that https://github.com/Expensify/App/issues/14572 is still fixed (especially on Android)

**Comment by s77rt** [comment] 2023-06-22 02:50
BTW, the issue in not reproducible on `main` due to another unwanted change. More info https://github.com/Expensify/App/pull/20838#discussion_r1237874928. Once this is resolved the bug would be reproducible again and we can go ahead with a proposal.

**Comment by s77rt** [comment] 2023-06-22 02:51
@namhihi237 Thanks for the quick follow up. For now I think we need to wait on @bernhardoj confirmation on his proposed solution then we can see how to move forward.

**Comment by bernhardoj** [comment] 2023-06-22 03:39
Yes, applying the changes from https://github.com/Expensify/App/pull/20838#discussion_r1237874928 will make the issue reproducible again, and applying my fix still works. But I see we already have `isPressed` state, maybe we can rename it to `isPressedIn`?

**Comment by s77rt** [comment] 2023-06-22 19:44
Alright https://github.com/Expensify/App/pull/21310 is merged now.

**Comment by s77rt** [comment] 2023-06-22 19:45
Let's go with @bernhardoj's proposal https://github.com/Expensify/App/issues/20983#issuecomment-1596217685 (reviewed on https://github.com/Expensify/App/issues/20983#issuecomment-1601942243)

:ribbon: :eyes: :ribbon: C+ reviewed

**Comment by johnmlee101** [comment] 2023-06-22 19:51
makes sense 👍

**Comment by bernhardoj** [comment] 2023-06-23 04:48
PR is ready

cc: @s77rt

**Comment by s77rt** [comment] 2023-06-29 12:34
- The PR that introduced the bug has been identified: https://github.com/Expensify/App/pull/18122
- The offending PR has been commented on: https://github.com/Expensify/App/pull/18122#discussion_r1246506016
- A discussion in #expensify-bugs has been started: https://expensify.slack.com/archives/C049HHMV9SM/p1688042057261969
- Determine if we should create a regression test for this bug: No

**Comment by trjExpensify** [comment] 2023-07-05 17:27
Thanks, @s77rt! 

Ignoring [this timeline recap](https://github.com/Expensify/App/issues/20983#issuecomment-1607731120), it didn't account for the weekend.

Following offers have been sent: 

- $1,500 to @s77rt for C+ review
- $1,500 to @bernhardoj for the fix
- $250 to @gadhiyamanan for the bug report.

**Comment by s77rt** [comment] 2023-07-05 17:41
@trjExpensify Accepted! Thanks!

BTW, the timeline seems correct, isn't it?

**Comment by trjExpensify** [comment] 2023-07-05 18:08
Ah, my eyes are playing tricks on me.. I read it as not being eligible. 😂  I'd applied the bonus anyhow. 

Also, settled up with you after accepting - thanks!

**Comment by trjExpensify** [comment] 2023-07-06 13:59
Paid @bernhardoj, waiting on @gadhiyamanan to accept the offer.

**Comment by trjExpensify** [comment] 2023-07-10 09:38
Paid @gadhiyamanan, closing!

**Closed by trjExpensify** 2023-07-10 09:38 UTC
Labels: External, Daily, Overdue, Awaiting Payment, Bug
