### ISSUE TITLE
[HOLD for payment 2024-11-29] [$250] Group chat - New member is displayed with offline profile avatar

### ISSUE THREAD

**Issue by IuliiaHerets** [Expensify/App#52639] opened 2024-11-15 17:48 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** v9.0.63-1
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**If this was caught during regression testing, add the test name, ID and link from TestRail:** https://expensify.testrail.io/index.php?/tests/view/5229966&group_by=cases:section_id&group_id=296760&group_order=asc
**Email or phone of affected tester (no customers):** gocemate+a2862@gmail.com
**Issue reported by:** Applause Internal Team

## Action Performed:
1. Create group conversation with few members
2. Click on header> Members> Invite new member
3. Enter email address and take a look at user's avatar

## Expected Result:
User should have default or custom profile avatar

## Actual Result:
User is displayed with offline profile avatar when invite it in existing group chat

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Standalone
- [ ] Android: HybridApp
- [x] Android: mWeb Chrome
- [ ] iOS: Standalone
- [ ] iOS: HybridApp
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

https://github.com/user-attachments/assets/960c7f37-ca6f-4151-9804-eb5ce6428d4c

  </details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~021858590656610669336</li>
        <li>Upwork Job ID: 1858590656610669336</li>
        <li>Last Price Increase: 2024-11-18</li>
<li>Automatic offers: </li>
<ul>
<li>brunovjk | Reviewer | 104980522</li>
<li>gijoe0295 | Contributor | 104980525</li>
</ul></li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @garrettmknight</details>

**Comment by brunovjk** [comment] 2024-11-19 11:44
RCA seems correct to me, the solution make sense and works well in a quick test:

https://github.com/user-attachments/assets/75c8b2e2-6642-450e-99b4-1360b5edd3bb

I think we can go with @gijoe0295's [proposal](https://github.com/Expensify/App/issues/52639#issuecomment-2479643403).

🎀👀🎀 C+ reviewed

**Comment by brunovjk** [comment] 2024-11-20 10:05
@gijoe0295 Do you have an Estimated Time of Arrival for the PR? Thank you.

**Comment by brunovjk** [comment] 2024-11-21 22:13
> Regression is at 44% completed.
> 
> Unchecked PRs: [#52844](https://github.com/Expensify/App/pull/52844) - Failing in Desktop and iOS with original KI [#52639](https://github.com/Expensify/App/issues/52639)

I tested again and everything seems good to me:

**Screenshots/Videos**
<details>
<summary>Android: Native</summary>



https://github.com/user-attachments/assets/87ad56ed-cdb0-4135-b7a1-d123aac39f57


</details>

<details>
<summary>Android: mWeb Chrome</summary>



https://github.com/user-attachments/assets/51152ce5-460a-4054-9445-018134c6f357


</details>

<details>
<summary>iOS: Native</summary>



https://github.com/user-attachments/assets/16cc0147-0985-4898-a798-c78d15073e43


</details>

<details>
<summary>iOS: mWeb Safari</summary>



https://github.com/user-attachments/assets/f2304ea3-0675-464f-86d3-875c19095ccb


</details>

<details>
<summary>MacOS: Chrome / Safari</summary>



https://github.com/user-attachments/assets/267574dc-6bb5-4c53-bdee-5f545bcf0f28


</details>

<details>
<summary>MacOS: Desktop</summary>



https://github.com/user-attachments/assets/43eaf08d-e34e-4b77-8a16-92f7c9e72f61


</details>

I can "reproduce" the "User is displayed with offline profile avatar" if we try to add a non-existent account that has never been logged in and no default avatar has been assigne. Do you see anything different @gijoe0295? Thanks.

**Comment by brunovjk** [comment] 2024-11-22 14:09
Coming from the [conversation on deploy checklist](https://github.com/Expensify/App/issues/52862#issuecomment-2493779935):

> @izarutskaya I think it's due to the capitalized I at the beginning. Only happen on iOS because it automatically capitalizes the first character. The SearchForReports API is case-sensitive so izarutskachat1 and Izarutskachat1 (capital i) are different. The correct result is returned if you searched for the exact email ([izarutskachat1@gmail.com](mailto:izarutskachat1@gmail.com)).

I can replicate that. It actually seems to be related to the server response rather than our PR:

https://github.com/user-attachments/assets/bc853118-e8a5-4891-8720-76d0a2252457

cc: @izarutskaya @deetergp @gijoe0295

**Comment by brunovjk** [comment] 2024-11-28 13:49
# BugZero Checklist:

- [x] **[Contributor]** Classify the bug:

<details>
<summary>Bug classification</summary>


Source of bug:
  - [ ] 1a. Result of the original design (eg. a case wasn't considered)
  - [x] 1b. Mistake during implementation
  - [ ] 1c. Backend bug
  - [ ] 1z. Other:

Where bug was reported:
  - [ ] 2a. Reported on production
  - [ ] 2b. Reported on staging (deploy blocker)
  - [x] 2c. Reported on both staging and production
  - [ ] 2d. Reported on a PR
  - [ ] 2z. Other:

Who reported the bug:
  - [ ] 3a. Expensify user
  - [ ] 3b. Expensify employee
  - [ ] 3c. Contributor
  - [ ] 3d. QA
  - [x] 3z. Other: Applause Internal Team

</details>

- [x] **[Contributor]** The offending PR has been commented on, pointing out the bug it caused and why, so the author and reviewers can learn from the mistake.

    Link to comment: No PR directly added the bug, there was a detail missed during the implementation of the page.

- [ ] **[Contributor]** If the regression was CRITICAL (e.g. interrupts a core flow) A discussion in [#expensify-open-source](https://app.slack.com/client/E047TPA624F/C01GTK53T8Q) has been started about whether any other steps should be taken (e.g. updating the PR review checklist) in order to catch this type of bug sooner.

    Link to discussion:

- [x] **[Contributor]** If it was decided to create a regression test for the bug, please propose the [regression test](https://github.com/Expensify/App/blob/main/contributingGuides/REGRESSION_TEST_BEST_PRACTICES.md) steps using the template below to ensure the same bug will not reach production again.

## Regression Test Proposal
### Precondition: Must be online.

### Test:

1. Go to a group chat
2. Click on header > Members > Invite new member
3. Enter an email that hasn't been chatted with but should already exist
4. Verify his contact not show fallback avatar (it can show fallback avatar briefly while it's fetching data)


Do we agree 👍 or 👎

**Comment by garrettmknight** [comment] 2024-12-02 18:54
All paid out, closing!

**Closed by garrettmknight** 2024-12-02 18:54 UTC
Labels: External, Daily, Overdue, Awaiting Payment, Bug
