### ISSUE TITLE
[HOLD for payment 2024-01-17] [$1000] Workspace - Expensify download link in the welcome message is not hyperlinked

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#27290] opened 2023-09-12 19:57 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Go to staging.new.expensify.com
2. Invite a member to the workspace
3. Navigate to the workspace chat with the invited member

## Expected Result:
https://use.expensify.com/download
link in the welcome message is hyperlinked

## Actual Result:
https://use.expensify.com/download
link in the welcome message is not hyperlinked, unless the message is edited and saved

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android / native
- [x] Android / Chrome
- [x] iOS / native
- [x] iOS / Safari
- [x] MacOS / Chrome / Safari
- [x] MacOS / Desktop

**Version Number:** 1.3.68-15

**Reproducible in staging?:** Yes

**Reproducible in production?:** Yes

**If this was caught during regression testing, add the test name, ID and link from TestRail:**

**Email or phone of affected tester (no customers):**

**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/78819774/8f6b3662-3e57-43e3-890e-742ae9c25dc0

**Expensify/Expensify Issue URL:**

**Issue reported by:** @alitoshmatov

**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1694444208170039

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~0130840f78177f0f3f</li>
        <li>Upwork Job ID: 1702073199412563968</li>
        <li>Last Price Increase: 2023-10-06</li>
    </ul>
</details>

**Comment by alitoshmatov** [comment] 2023-09-14 06:12
I have reported this issue before https://expensify.slack.com/archives/C049HHMV9SM/p1694444208170039 . Can someone check and confirm if I indeed reported it earlier?

**Comment by Christinadobrzyn** [comment] 2023-09-14 20:55
It does look like the same report as this one - I will add you as the reporter to this job @alitoshmatov!

**Comment by Christinadobrzyn** [comment] 2023-09-15 16:24
@situchan can you check this proposal https://github.com/Expensify/App/issues/27290#issuecomment-1717183104

It looks like we're still collecting proposals!

**Comment by Christinadobrzyn** [comment] 2023-09-18 21:56
@situchan can you check this proposal https://github.com/Expensify/App/issues/27290#issuecomment-1717183104 

Let me know if you'd like to see more proposals

**Comment by situchan** [comment] 2023-09-18 22:00
> @situchan can you check this proposal [#27290 (comment)](https://github.com/Expensify/App/issues/27290#issuecomment-1717183104)
> 
> Let me know if you'd like to see more proposals

@Christinadobrzyn I'd like to see more proposals. @Krishna2323's solution doesn't seem ideal to me.

**Comment by situchan** [comment] 2023-09-20 04:13
I don't think we should alter data to send to backend.

**Comment by situchan** [comment] 2023-09-20 04:18
Won't this break showing all existing invite messages so far? Also, note that email/sms is sent for that invite message in backend. I am afraid that will cause regression of unexpected escaping/unescaping html.

**Comment by situchan** [comment] 2023-09-20 04:19
@Krishna2323 make sure that your proposal is thoroughly tested in all possible cases before claiming.

**Comment by Christinadobrzyn** [comment] 2023-09-20 19:56
@situchan let me know if you want to see more proposals!

**Comment by situchan** [comment] 2023-09-20 21:10
> @situchan let me know if you want to see more proposals!

yes, no satisfactory proposals yet

**Comment by Pluto0104** [comment] 2023-09-22 20:52
It seems to be backend issue. we should update welcome message on backend side. Of course, we can handle this on frontend side but it's not efficient.

**Comment by cng008** [comment] 2023-09-23 01:23
Agree, the root cause is how the invite message is being saved to the backend: `props.action.message[0].html` is the same as `props.action.message[0].text` even when it contains a link:
```
{
  "html": "You have been invited to User's Workspace! Download the Expensify mobile app at use.expensify.com/download to start tracking your expenses.",
  "text": "You have been invited to User's Workspace! Download the Expensify mobile app at use.expensify.com/download to start tracking your expenses.",
}
```

When the member invite form is submitted, it should save as:
```
{
  "html": "You have been invited to User's Workspace! Download the Expensify mobile app at <a href=\"https://use.expensify.com/download\" target=\"_blank\" rel=\"noreferrer noopener\">use.expensify.com/download</a> to start tracking your expenses.",
  "text": "You have been invited to User's Workspace! Download the Expensify mobile app at use.expensify.com/download to start tracking your expenses.",
}
```

The welcome message doesn't need to be modified, however, there should be a check in the backend to check for links in invite messages.

**Comment by cng008** [comment] 2023-09-23 01:25
Contributor details
Your Expensify account email: hello+expensify@christienng.com
Upwork Profile Link: https://www.upwork.com/freelancers/~01706570198b5c97c9?s=1110580755107926016

**Comment by Pluto0104** [comment] 2023-09-23 01:34
hey, @cng008 

> The welcome message doesn't need to be modified.

What do you mean? The welcome message should be modified to include a download link on backend side. I can't understand you. Can you clarify this?

**Comment by cng008** [comment] 2023-09-23 02:34
@Pluto0104 Now I'm not sure what you mean by "download link on backend side". I mentioned that the welcome message doesn't need to be modified [since it's also being used for email/text](https://github.com/Expensify/App/issues/27290#issuecomment-1726941029). I suppose I could have left that out of my comment
Sorry for any confusion! I'm just starting off my web dev career

**Comment by Pluto0104** [comment] 2023-09-23 02:43
@cng008 Ah, I understand you now. I initially thought that the welcome message was generated by the frontend, then relayed to the backend and sent to invited members. However, it appears that the backend doesn't handle any links or emails during the process of sending the welcome message. Therefore, we'll need to adjust this logic.

**Comment by pradeepmdk** [comment] 2023-09-23 02:45
### Proposal
### Please re-state the problem that we are trying to solve in this issue.

Expensify download link in the welcome message is not hyperlinked 
### What is the root cause of that problem?
html is not formated for link 

### What changes do you think we should make in order to solve the problem?
1) fix in the backend 
2) we need pass an html
```javascript
    sendInvitation() {
        Keyboard.dismiss();
        const parser = new ExpensiMark();
        const parsedWelcomeNote = _.unescape(parser.replace(this.state.welcomeNote));
``` 
we need pass unescape char to backend 
https://github.com/Expensify/App/pull/21912/files 

### Result
email

https://github.com/Expensify/App/assets/16595846/ed28f63c-27ed-4b5e-89cd-ab677b1c3a59

phone

https://github.com/Expensify/App/assets/16595846/74a11e38-29b1-48af-a9d1-a9ddba757ba6


@situchan verified the invite scenario

Note: when we send `use.expensify.com/download` string to mail/sms that will be automatically converted to link. so backend nothing to convert as link here.

**Comment by Pluto0104** [comment] 2023-09-23 02:49
@pradeepmdk did you see [this PR](https://github.com/Expensify/App/issues/20081)?

**Comment by pradeepmdk** [comment] 2023-09-23 02:58
@Pluto0104 Yes i verified that that more about escape  HTML special chars and include my proposal as well

**Comment by Pluto0104** [comment] 2023-09-23 03:27
@pradeepmdk how do you think about [this](https://github.com/Expensify/App/issues/27290#issuecomment-1726930504)?

**Comment by pradeepmdk** [comment] 2023-09-23 03:47
on edit time we are only sending the html data to the backend.  so I am not sure that is up to @situchan  and the internal team.  

currently backend side whatever we are sending from the client side they are using.. see the example here when I am sending escape char they storing same way.
![Screenshot 2023-09-23 at 9 12 31 AM](https://github.com/Expensify/App/assets/16595846/ce1a8c65-62f5-45f3-8e69-f813949588ea)
so we can able to fix this on the client side and no regression.

**Comment by Christinadobrzyn** [comment] 2023-09-26 00:05
reviewing proposals

**Comment by situchan** [comment] 2023-09-26 11:27
> 1. fix in the backend

@pradeepmdk can you please clarify what to fix in backend?

**Comment by pradeepmdk** [comment] 2023-09-26 11:37
@situchan Before storing in the they need converted HTML. 
but as per my understanding backend not doing such a flow in any other place. always client side we are doing parsing as an HTML. so we can go with the second one.

**Comment by situchan** [comment] 2023-09-26 11:58
@pradeepmdk If I send `&amp;`, it's unescaped as `&`

**Comment by pradeepmdk** [comment] 2023-09-26 12:11
@situchan that is the expected one right? because now also when you send this `&amp;` mobile you can get same as this. but in the mail, it will unescaped to `&`

**Comment by situchan** [comment] 2023-09-26 12:11
@pradeepmdk you mean this already happens on production app?

**Comment by pradeepmdk** [comment] 2023-09-26 12:15
yes @situchan  when you invite mail its will convert `&amp; -> &` but mobile sms `&amp; -> &amp;`

**Comment by situchan** [comment] 2023-09-26 12:16
can you list again all the cases (chat, email, sms) before-fix and after-fix when send `&amp;`?

**Comment by situchan** [comment] 2023-09-26 13:09
@pradeepmdk more cases:
- web notification
- android push notification
- ios push notification

**Comment by pradeepmdk** [comment] 2023-09-26 14:33
@situchan Android and ios working fine.. but not sure how to test the web because in the web i am not receiving any notification. do you have any steps for that?


https://github.com/Expensify/App/assets/16595846/6c8a2189-dbb8-4171-810d-11a7acedc356

**Comment by pradeepmdk** [comment] 2023-09-29 17:58
@situchan web notification also tested 

https://github.com/Expensify/App/assets/16595846/e716f55e-9996-4f89-a648-994334558d7b

**Comment by pradeepmdk** [comment] 2023-09-30 14:00
@situchan bump;

**Comment by Christinadobrzyn** [comment] 2023-10-03 18:24
Let me know what you think of the proposal @situchan or if you'd like to see more!

**Comment by situchan** [comment] 2023-10-06 16:13
I'd like to get engineer's thought whether to fix in backend or frontend
🎀 👀 🎀

**Comment by hayata-suenaga** [comment] 2023-10-09 01:10
Let's fix this on the backend since that is [apparently](https://github.com/Expensify/App/blob/main/src/libs/actions/Policy.js#L397-L409) how we do it.

Unfortunately, I don't have time to work on this right now. I gonna unassign myself and assign `internal` label.

**Comment by hayata-suenaga** [comment] 2023-10-09 01:12
okay... I think melvin didn't assign an engineer because I added the `internal` label

@Christinadobrzyn could you reapply the `internal` label so that someone from the engineering team is auto assigned?

**Comment by situchan** [comment] 2023-10-09 01:13
@hayata-suenaga `Internal` may not help You can remove and re-add `Engineering` label

**Comment by situchan** [comment] 2023-10-09 01:18
🎀 👀 🎀 to pull up engineer

**Comment by hayata-suenaga** [comment] 2023-10-09 01:53
@Beamanator let me know if you don't have time to work on this. I can find someone else

**Comment by Beamanator** [comment] 2023-10-09 06:29
@hayata-suenaga that would be great if you could find someone else, but if this is super high priority for any of your projects I can work on it

**Comment by hayata-suenaga** [comment] 2023-10-09 06:44
asking for a volunteer [here](https://expensify.slack.com/archives/C03TQ48KC/p1696833843301289)

**Comment by pradeepmdk** [comment] 2023-10-09 08:48
@situchan @hayata-suenaga 
what about this different behavior 
> Current one:
```
mail: &amp; -> &
sms: &amp; -> &amp;
chat: &amp; -> &
```
as per this if we send an escape character we have issues with the mobile SMS box
https://github.com/Expensify/App/blob/main/src/libs/actions/Policy.js#L397-L409

previous code:
` welcomeNote: _.escape(welcomeNote),`
here we are escaping the `& -> &amp;`. when we remove the escape it will send as it is. 
but still, we can send escape characters manually. so at the time in sms box will have `&amp;`

frontend: 
but we can use Unescape to cover both cases. https://github.com/Expensify/App/issues/27290#issuecomment-1732189422

**Comment by situchan** [comment] 2023-10-09 10:18
cc: @cristipaval as you already fixed SMS [issue](https://github.com/Expensify/App/issues/20081) in backend

**Comment by cristipaval** [comment] 2023-10-09 10:54
Thanks for cc'ing me @situchan!

At first glance, this issue isn't a regression after the fix I worked on. But I can take this one over. It doesn't have a high priority, so it's OK to investigate it later this week. @hayata-suenaga, would this approach work?

**Comment by hayata-suenaga** [comment] 2023-10-10 01:44
@cristipaval yes I assigned you to this issue. Thank you so much for taking this over 🙇

**Comment by Christinadobrzyn** [comment] 2023-10-10 21:36
I think we're working on a PR

**Comment by Christinadobrzyn** [comment] 2023-10-12 21:14
hi @cristipaval or @situchan would you happen to know a status here... do we have a PR?

**Comment by situchan** [comment] 2023-10-12 21:24
No PR yet. I think we're waiting for next step from @cristipaval after priority work

**Comment by Christinadobrzyn** [comment] 2023-10-13 22:05
Do you think I can move this to weekly?

**Comment by cristipaval** [comment] 2023-10-13 22:45
yes @Christinadobrzyn , thanks for the idea. It also is a low priority IMO, so it can wait a bit and I'll work on it when I have free cycles between some issues with higher priorities.

**Comment by Christinadobrzyn** [comment] 2023-10-23 22:01
not overdue - working on the PR

**Comment by cristipaval** [comment] 2023-11-02 14:34
Hoping to get some time tomorrow for this one.

**Comment by Christinadobrzyn** [comment] 2023-11-10 23:57
Thanks @cristipaval feel free to send an update when you can!

**Comment by Christinadobrzyn** [comment] 2023-11-18 01:33
I'm going ooo until Monday Nov 27th so going to assign another BZ teammate to monitor this until I'm back. Thanks!

Status: working on a PR!

**Comment by Christinadobrzyn** [comment] 2023-11-27 23:11
back from ooo moving this back to daily!

**Comment by Christinadobrzyn** [comment] 2023-12-06 01:46
hum... @situchan or @cristipaval do you have an update here. I'm a little lost 😅

**Comment by cristipaval** [comment] 2023-12-06 10:43
No update because I haven't had time to work on this 😢

**Comment by Christinadobrzyn** [comment] 2023-12-12 23:38
Still working on this!

**Comment by cristipaval** [comment] 2023-12-21 23:28
[Web-E PR](https://github.com/Expensify/Web-Expensify/pull/40266) in review. Once it gets merged and deployed to production, the [App PR](https://github.com/Expensify/App/pull/33468) will be ready for review,

**Comment by cristipaval** [comment] 2024-01-02 11:45
[Web-E PR](https://github.com/Expensify/Web-Expensify/pull/40266) is deployed. I'll make the App PR ready soon.

**Comment by cristipaval** [comment] 2024-01-05 21:52
App PR is ready for review, @situchan

**Comment by cristipaval** [comment] 2024-01-19 12:36
@Christinadobrzyn is OOO until Monday.

**Comment by Christinadobrzyn** [comment] 2024-01-23 20:46
I'm back! sorry for the delay - the old Upwork job expired so I created a new one. @alitoshmatov and @situchan can you review the payment summary [here](https://github.com/Expensify/App/issues/27290#issuecomment-1896239478) and let me know if I'm missing anything? 

if that is good please accept my offer in [Upwork](https://www.upwork.com/jobs/~012ab0625a680cb100) so I can pay you.

**Comment by alitoshmatov** [comment] 2024-01-24 11:20
Accepted the offer.

**Comment by situchan** [comment] 2024-01-24 11:26
yes summary looks correct.
Accepted offer. Thanks

**Comment by Christinadobrzyn** [comment] 2024-01-26 00:03
Awesome! Paid out based on this payment summary https://github.com/Expensify/App/issues/27290#issuecomment-1896239478

Closing this as complete! Thanks everyone!

**Closed by Christinadobrzyn** 2024-01-26 00:03 UTC
Labels: Engineering, Daily, Internal, Awaiting Payment, Bug
