### ISSUE TITLE
[$250] Finder - Concierge chat preview is displayed with code in chat finder

### ISSUE THREAD

**Issue by IuliiaHerets** [Expensify/App#50350] opened 2024-10-07 19:06 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 9.0.45-0
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**Issue reported by:** Applause Internal Team

## Action Performed:
1. Open the staging.new.expensify.com website.
2. Sign in with any account.
3. Tap on the search icon on LHN.
4. Verify the preview of Concierge chat is displayed without any code or content issue.

## Expected Result:
The preview of the Cocnierge chat in chat finder, should display the beggining of the last message without any difference with the message in chat.

## Actual Result:
The preview of Concierge chat in chat finder, displays the beggining of the last message, with "<h1> >/h1>" code in the middle of it.

## Workaround:
Unknown

## Platforms:

- [x] Android: Native
- [x] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

https://github.com/user-attachments/assets/616d3b8a-7120-4931-85a0-29ca52bd7a96

 
</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~021845626651629289152</li>
        <li>Upwork Job ID: 1845626651629289152</li>
        <li>Last Price Increase: 2024-11-11</li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @rojiphil</details>

**Comment by IuliiaHerets** [comment] 2024-10-07 19:06
We think that this bug might be related to #wave-collect - Release 1

**Comment by IuliiaHerets** [comment] 2024-10-07 19:06
@VictoriaExpensify  FYI I haven't added the External label as I wasn't 100% sure about this issue. Please take a look and add the label if you agree it's a bug and can be handled by external contributors

**Comment by VictoriaExpensify** [comment] 2024-10-09 07:30
Unable to reproduce this, posted in #QA - https://expensify.slack.com/archives/C9YU7BX5M/p1728458635539589

**Comment by kavimuru** [comment] 2024-10-09 12:39
The issue is reproducible when the concierge chat updates with new information.

https://github.com/user-attachments/assets/4ab9047a-c7da-43c1-a3ee-2f6db518ee00

**Comment by VictoriaExpensify** [comment] 2024-10-14 00:44
Yup we should fix this!

**Comment by huult** [comment] 2024-10-14 06:24
Can we still reproduce this issue on version `9.0.48-0`?

**Comment by huult** [comment] 2024-10-14 08:49
## Proposal

### Please re-state the problem that we are trying to solve in this issue.

Finder - Concierge chat preview is displayed with code in chat finder

### What is the root cause of that problem?

The `alternateText` is returned as an HTML string in the report data.
```diff
Example: item.alternateText: "<h1>Let's scan your first receipt</h1>"
```

When rendering `alternateText` in the chat finder, it only removes the SMS domain but does not parse the HTML into plain text. As a result, this issue occurs for report items where the `alternateText` contains an HTML string.
https://github.com/Expensify/App/blob/4a3f2daecb8aa57cac94b04aa7f414fa00a724fb/src/components/SelectionList/UserListItem.tsx#L141-L147

### What changes do you think we should make in order to solve the problem?

To resolve this case, we should parse `alternateText` from an HTML string to text before removing the SMS domain. We will use `Parser.htmlToText`, which is used in other places to parse alternateText. The code change will look like this:

```diff
//.src/components/SelectionList/UserListItem.tsx#L144
- text={Str.removeSMSDomain(item.alternateText ?? '')}
+ text={Str.removeSMSDomain(Parser.htmlToText(item.alternateText) ?? '')}
```

Optional: If we don't want to use whitespace characters around newline characters in HTML, then we will replace the text after parsing HTML to text.

- <img width="927" alt="Screenshot 2024-10-14 at 15 47 03" src="https://github.com/user-attachments/assets/5059d340-6f0e-4097-bb53-e251fc886e11">

To update this case the code will be: 

```diff
//.src/components/SelectionList/UserListItem.tsx#L144
- text={Str.removeSMSDomain(item.alternateText ?? '')}
+ text={Str.removeSMSDomain(Parser.htmlToText(item.alternateText) ?? '').replace(/\s*\n\s*/g, ' ')}
```

- <img width="927" alt="Screenshot 2024-10-14 at 15 48 40" src="https://github.com/user-attachments/assets/5bed2196-b265-4863-adcd-0f0ff161ed18">


<summary>
<details>POC

<img width="1512" alt="Screenshot 2024-10-14 at 15 31 11" src="https://github.com/user-attachments/assets/93ee4df5-3165-4481-9f32-c09f2fde6550">

</details>
</summary>

**Comment by VictoriaExpensify** [comment] 2024-10-18 03:29
@rojiphil - can you please review @huult's proposal when you have the chance?

**Comment by rojiphil** [comment] 2024-10-21 16:44
Sorry for the delay here. I will review this my day tomorrow and update.

**Comment by rojiphil** [comment] 2024-10-22 10:12
> The issue is reproducible when the concierge chat updates with new information.

I am unable to reproduce the problem. 
@kavimuru How can we make the concierge chat to send this new information?

**Comment by rojiphil** [comment] 2024-10-22 10:13
> The alternateText is returned as an HTML string in the report data.

@huult While I figure out a way to reproduce this, can you please investigate why the `alternateText` is populated with HTML string instead of text? 
In my test as demonstrated below, it is showing correctly.

https://github.com/user-attachments/assets/f9011785-73ff-4790-870e-746bc1fbbc9a

**Comment by huult** [comment] 2024-10-22 11:20
@rojiphil Maybe this issue was resolved by another [pull request](https://github.com/Expensify/App/pull/50399). Can you ask @kavimuru if she can reproduce the issue? If not, we can close it

**Comment by rojiphil** [comment] 2024-10-22 11:29
> Maybe this issue was resolved by another [pull request](https://github.com/Expensify/App/pull/50399). Can you ask @kavimuru if she can reproduce the issue? If not, we can close it

Thanks @huult. That makes sense. 
@kavimuru Can you please try to reproduce this again? It looks like this should be fixed in production.

**Comment by rojiphil** [comment] 2024-10-24 08:36
@VictoriaExpensify Can you please apply the `Retest Weekly` label for Applause to check this? Thanks

**Comment by VictoriaExpensify** [comment] 2024-10-29 10:07
Applied the retest label

**Comment by mvtglobally** [comment] 2024-10-30 09:44
Issue not reproducible during KI retests. (First week)

**Comment by rojiphil** [comment] 2024-11-08 06:43
@VictoriaExpensify I think we can close this issue as this is not reproducible as mentioned [here](https://github.com/Expensify/App/issues/50350#issuecomment-2446357999)

**Comment by mvtglobally** [comment] 2024-11-08 15:25
Issue not reproducible during KI retests. (Second week)

**Comment by rojiphil** [comment] 2024-11-12 04:48
@VictoriaExpensify, I think we can close this issue as it is not reproducible for the [second week](https://github.com/Expensify/App/issues/50350#issuecomment-2465035666) also. 
What do you think?

**Comment by VictoriaExpensify** [comment] 2024-11-13 10:29
I agree with you @rojiphil - let's close it out!

**Closed by VictoriaExpensify** 2024-11-13 10:29 UTC
Labels: External, Daily, Help Wanted, Bug, retest-weekly
