### ISSUE TITLE
After create Contact method can not click

### ISSUE THREAD

**Issue by kavimuru** [Expensify/App#23823] opened 2023-07-28 20:36 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Go to Contact methods page
2. Create a contract
3. Click above contract and input wrong code
4. Copy url and open new tab
5. Click back button
6. Click new contract method
7. Input the new contracts => add
8. observed, can't click on the newly created contract
## Expected Result: 
can click on the newly created contract
## Actual Result: 
can't click on the newly created contract

## Workaround:
Can the user still use Expensify without this being fixed? Have you informed them of the workaround?

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [x] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 1.3.47-2
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/43996225/030f749c-f7ac-42f7-b55c-faab3b2b43c0

https://github.com/Expensify/App/assets/43996225/454bad5c-910d-47ce-b799-64aa4b1299d3

**Expensify/Expensify Issue URL:**
**Issue reported by:** @namhihi237 
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1690467252562249
 
[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by DarshanDixit05** [comment] 2023-07-28 20:49
Hey , i wanted to work on this issue . Can you please assign it to me ?

**Comment by joekaufmanexpensify** [comment] 2023-07-31 13:04
@DarshanDixit05 Thanks for your interest! If you'd like to work on this, you'll want to submit a proposal (per our [contributing guidelines](https://github.com/Expensify/App/blob/main/contributingGuides/CONTRIBUTING.md)). Please note, we have not triaged this bug report yet, so there is no guarantee we will fix this. Though, you're welcome to submit a proposal before we triage it.

**Comment by DarshanDixit05** [comment] 2023-07-31 18:05
Sure @joekaufmanexpensify 👍

**Comment by joekaufmanexpensify** [comment] 2023-07-31 20:39
Unable to reproduce on Staging web v1.3.48-0. This is working fine for me now.

https://github.com/Expensify/App/assets/54866469/6e276f5a-3bf2-4138-a337-62d6dbd05d70

**Comment by joekaufmanexpensify** [comment] 2023-07-31 20:40
Closing as this doesn't seem to be an issue on the newest build!

**Closed by joekaufmanexpensify** 2023-07-31 20:40 UTC
Labels: Daily, Bug
