### ISSUE TITLE
[HOLD for payment 2024-02-07] Focus mode modal can show incorrectly when signing up for a new account after logging out of an existing account.

### ISSUE THREAD

**Issue by marcaaron** [Expensify/App#34778] opened 2024-01-19 03:12 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:**
**Reproducible in staging?:**
**Reproducible in production?:**
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:**
**Slack conversation:**

## Action Performed:
1. Signed up for [expensify.com](http://expensify.com/) using a gmail account
1. Get directed to [new.expensify.com](http://new.expensify.com/) (good :white_check_mark: )

## Expected Result:

We should only show this modal for users who have more than 30 chats. 

## Actual Result:

Saw [the focus mode] modal first (bad :x:)
This was a brand new account and I had only one chat.

## Workaround:

👍 

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [ ] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

![image](https://github.com/Expensify/App/assets/32969087/98f1fe19-ae98-4ebe-981f-eb68b942bc96)

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~014e891ac070cbe788</li>
        <li>Upwork Job ID: 1748181663725543424</li>
        <li>Last Price Increase: 2024-01-19</li>
    </ul>
</details>

**Comment by sophiepintoraetz** [comment] 2024-01-19 03:29
I'm guessing I'm here for the C+ payment of the review?

**Comment by marcaaron** [comment] 2024-01-19 03:39
Yes. I've got a PR in the works already.

**Comment by sobitneupane** [comment] 2024-02-01 09:51
@c3024 reviewed the associated PR.

**Comment by c3024** [comment] 2024-02-04 16:20
**BugZero Checklist:** The PR fixing this issue has been merged! The following checklist ([instructions](https://stackoverflow.com/c/expensify/questions/14574)) will need to be completed before the issue can be closed:

* [x]  [@c3024] The PR that introduced the bug has been identified. Link to the PR: #30664 
* [x]  [@c3024] The offending PR has been commented on, pointing out the bug it caused and why, so the author and reviewers can learn from the mistake. Link to comment: The present fix is made by the same PR author so not commented.
* [x]  [@c3024] A discussion in #expensify-bugs has been started about whether any other steps should be taken (e.g. updating the PR review checklist) in order to catch this type of bug sooner. Link to discussion: Not started because this could not have been caught earlier.
* [x]  [@c3024] Determine if we should create a regression test for this bug. Yes
* [x]  [@c3024] If we decide to create a regression test for the bug, please propose the [regression test](https://github.com/Expensify/App/blob/main/contributingGuides/REGRESSION_TEST_BEST_PRACTICES.md) steps to ensure the same bug will not reach production again.

### Regression Test Proposal
Tests [here](https://github.com/Expensify/App/pull/34624#issue-2085276216) are suitable regression tests.
>### Tests
>#### Verify focus mode switch still works and there are no regressions
>1. Ensure signed out of both OldDot and NewDot
>2. Sign into a NewDot account that has 30+ chats (must be a new account)
>3. Verify the focus mode alert still works correctly
>#### Verify focus mode modal is not incorrectly showed for brand new account after signing out of large account
>1. Ensure signed out of both OldDot and NewDot
>2. Sign into an account that has many hundreds of chats in NewDot
>3. Sign out
>4. Create new account on a public domain in OldDot
>5. Verify you are redirected to NewDot
>6. Verify the Focus mode modal does not show incorrectly

👍 or 👎

**Comment by bfitzexpensify** [comment] 2024-02-05 22:11
Regression steps look good, proposed they be added in https://github.com/Expensify/Expensify/issues/366901. 

Payment due on Wednesday.

**Comment by bfitzexpensify** [comment] 2024-02-07 03:03
Payment summary:

C+: @c3024 to be paid $500 via manual request.

**Comment by bfitzexpensify** [comment] 2024-02-07 03:03
We're all done here, closing this one out.

**Comment by c3024** [comment] 2024-02-07 03:04
I'm not eligible for manual requests yet. I can only be paid on Upwork. @bfitzexpensify

**Comment by bfitzexpensify** [comment] 2024-02-07 06:17
Gotcha - I've just made the Upwork [job](https://www.upwork.com/jobs/~014e891ac070cbe788) public, can you apply to it and let me know when you've done so?

**Comment by c3024** [comment] 2024-02-07 06:24
Thanks. Applied. Here is my Upwork profile as well.

https://www.upwork.com/freelancers/~0105555e2f227dbf47

**Comment by bfitzexpensify** [comment] 2024-02-07 07:02
Thanks, all paid out - _now_ we're done

**Closed by bfitzexpensify** 2024-02-07 07:02 UTC
Labels: Daily, Internal, Awaiting Payment, Bug
