### ISSUE TITLE
[Track Tax] Tax options do not come back after disabling and reenabling them

### ISSUE THREAD

**Issue by izarutskaya** [Expensify/App#37416] opened 2024-02-28 12:05 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Found when validating PR :** https://github.com/Expensify/App/pull/36784

**Version Number:** v1.4.44-7
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** Applause-Internal Team
**Slack conversation:**

## Action Performed:
Precondition:
- User is an employee of Collect workspace.
- The Collect workspace has some tax options.

1. [Employee] Go to workspace chat.
2. [Employee] Open request money page > Manual > Confirmation page.
3. [Employee] Click Show more > Tax rate.
4. [Admin] Disable all the tax options.
5. [Admin] Enable all the tax options.

## Expected Result:
The tax options will be showing for Employee when re-enabled.

## Actual Result:
The tax options are not showing for Employee when re-enabled. The options only show up after relogin.

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [x] Android: mWeb Chrome
- [x] iOS: Native
- [x] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

https://github.com/Expensify/App/assets/115492554/e5b4b206-67d0-4511-9b5b-73c92fb7f369

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by izarutskaya** [comment] 2024-02-28 12:05
@jliexpensify I haven't added the External label as I wasn't 100% sure about this issue. Please take a look and add the label if you agree it's a bug and can be handled by external contributors.

**Comment by izarutskaya** [comment] 2024-02-28 12:06
We think that this bug might be related to #wave6-collect-submitters
CC @greg-schroeder

**Comment by MonilBhavsar** [comment] 2024-02-28 18:49
Feature is WIP, so we can put this HOLD until we finish the implementation as it is being rolled out in phases https://github.com/Expensify/Expensify/issues/305057

**Comment by jliexpensify** [comment] 2024-02-28 22:20
@MonilBhavsar do you want to be assigned this issue?

**Comment by jliexpensify** [comment] 2024-03-08 00:47
@MonilBhavsar just moving to `weekly` so we're not pinged, feel free to change the priority.

**Comment by jliexpensify** [comment] 2024-03-18 08:58
Oh hold

**Comment by jliexpensify** [comment] 2024-04-01 02:23
@MonilBhavsar moved this to the Collect project as that deals with Taxes, right?

**Comment by jliexpensify** [comment] 2024-04-10 02:57
Still on hold

**Comment by MonilBhavsar** [comment] 2024-04-10 05:52
This is related to a pusher update. I'll work on the fix now

**Comment by MonilBhavsar** [comment] 2024-04-12 12:04
This is not a bug anymore. @izarutskaya you we please retest and confirm. Thank you!

Uploading Screen Recording 2024-04-12 at 5.18.40 PM.mov…

**Comment by MonilBhavsar** [comment] 2024-04-19 15:08
I'm closing this. Feel free to reopen if this happens and I'll take a look

**Closed by MonilBhavsar** 2024-04-19 15:08 UTC
Labels: Weekly, Bug, retest-weekly
