### ISSUE TITLE
[$500] Missing fields still shows error message even after selecting required fields

### ISSUE THREAD

**Issue by kavimuru** [Expensify/App#34945] opened 2024-01-23 05:21 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.30-0
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** @luacmartins 
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1705808628895589

## Action Performed:
Precondition : Have some violation rules for the expenses in the OD

1. Create an expense report
2. Open the receipt to view the details
3. enter the required fields values (in this case category and tag fields)

## Expected Result:
Error message should go away

## Actual Result:
Error message still appears

## Workaround:
Can the user still use Expensify without this being fixed? Have you informed them of the workaround?

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [x] Android: mWeb Chrome
- [x] iOS: Native
- [x] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

<img src="https://github.com/Expensify/App/assets/43996225/fdb72e64-5f82-4fa8-97c4-360f05d74516" width="40%" height="40%">
</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01724bf6068307f162</li>
        <li>Upwork Job ID: 1749663634886561792</li>
        <li>Last Price Increase: 2024-01-23</li>
    </ul>
</details>

**Comment by wildan-m** [comment] 2024-01-23 05:52
How can we add a violation rule in OD? this is how OD workspace setting looks like in my account

![Uploading Screenshot 2024-01-23 at 12.51.30.png…]()

**Comment by wildan-m** [comment] 2024-01-23 06:09
## Proposal

### Please re-state the problem that we are trying to solve in this issue.

Missing fields still shows error message even after selecting required fields

### What is the root cause of that problem?

We are not adding category/tag value to the message condition (rightLabel)

### What changes do you think we should make in order to solve the problem?


We can add it to rightLabel props: 

```
                    {shouldShowCategories && (
                        <MenuItemWithTopDescription
                            shouldShowRightIcon={!isReadOnly}
                            title={iouCategory}
                            description={translate('common.category')}
                            numberOfLinesTitle={2}
                            onPress={() =>
                                Navigation.navigate(ROUTES.MONEY_REQUEST_STEP_CATEGORY.getRoute(iouType, transaction.transactionID, reportID, Navigation.getActiveRouteWithoutParams()))
                            }
                            style={[styles.moneyRequestMenuItem]}
                            titleStyle={styles.flex1}
                            disabled={didConfirm}
                            interactive={!isReadOnly}
                            rightLabel={iouCategory && canUseViolations && Boolean(policy.requiresCategory) ? translate('common.required') : ''}
                        />
                    )}
                    {shouldShowTags && (
                        <MenuItemWithTopDescription
                            shouldShowRightIcon={!isReadOnly}
                            title={PolicyUtils.getCleanedTagName(iouTag)}
                            description={policyTagListName}
                            numberOfLinesTitle={2}
                            onPress={() =>
                                Navigation.navigate(ROUTES.MONEY_REQUEST_STEP_TAG.getRoute(iouType, transaction.transactionID, reportID, Navigation.getActiveRouteWithoutParams()))
                            }
                            style={[styles.moneyRequestMenuItem]}
                            disabled={didConfirm}
                            interactive={!isReadOnly}
                            rightLabel={iouTag && canUseViolations && Boolean(policy.requiresTag) ? translate('common.required') : ''}
                        />
                    )}
```

### What alternative solutions did you explore? (Optional)

**Comment by situchan** [comment] 2024-01-23 06:11
cc: @cead22 as violation related

**Comment by wildan-m** [comment] 2024-01-23 06:31
[Proposal Updated](https://github.com/Expensify/App/issues/34945#issuecomment-1905352682)

Mention the related files, add `PolicyUtils.getCleanedTagName` for tag

**Comment by wildan-m** [comment] 2024-01-23 06:56
[Proposal Updated](https://github.com/Expensify/App/issues/34945#issuecomment-1905352682)

Fix props, not rightLabel, but error props

**Comment by paultsimura** [comment] 2024-01-23 08:10
This is basically a dupe of https://github.com/Expensify/App/issues/34541, and if it is decided to be fixed Externally, [my proposal](https://github.com/Expensify/App/issues/34541#issuecomment-1893429580) is the first in the queue 👀

**Comment by luacmartins** [comment] 2024-01-23 16:15
Thanks for pointing that out @paultsimura! I think we can close this issue in favor of https://github.com/Expensify/App/issues/34541. Thanks for the proposals everyone!

**Closed by luacmartins** 2024-01-23 16:15 UTC
Labels: External, Daily, Help Wanted, Bug
