### ISSUE TITLE
Log in - Footer Login can hover and click on empty space to open link

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#22084] opened 2023-07-02 22:52 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Go to Login page
2. Scroll down
3. Move the mouse to the right of the affiliate links, Notice we can hover and click to open the link from the space

## Expected Result:
Can only hover and click open link from text

## Actual Result:
Can hover and click to open the link from the space

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [x] iOS / native
- [ ] iOS / Safari
- [x] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 1.3.35-5
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/93399543/95b16c90-0439-4520-9ac3-c26994ec795f

https://github.com/Expensify/App/assets/93399543/44e44fbd-f8d8-4332-8fc8-0a4b3242dc81

**Expensify/Expensify Issue URL:**
**Issue reported by:** @namhihi237
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1688231565265009

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by kbecciv** [comment] 2023-07-02 22:53
## Proposal
### Please re-state the problem that we are trying to solve in this issue.
### What is the root cause of that problem?
In this case, the child element takes up the full width of the parent element [here](https://github.com/Expensify/App/blob/c0ece67e0edcb725d8f72cf57cd40d98854c552c/src/pages/signin/SignInPageLayout/Footer.js#L177C1-L193C1)
### What changes do you think we should make in order to solve the problem?
We need to update the child element only to equal the length of the text
```javascript
<View style={[styles.footerRow,styles.alignItemsStart]}>
 {_.map(column.rows, (row) => (
 ...
```
### What alternative solutions did you explore? (Optional)
N/A

**Comment by gadhiyamanan** [comment] 2023-07-03 03:39
This is dupe of https://github.com/Expensify/App/issues/15783 , i think wevcan close it

**Comment by sakluger** [comment] 2023-07-03 18:33
Thanks @gadhiyamanan, you're right - this is a dupe and expected behavior.

**Closed by sakluger** 2023-07-03 18:33 UTC
Labels: Daily, Bug
