### ISSUE TITLE
[$500] Login - Pasting magic codes doesn’t seem to work

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#27606] opened 2023-09-16 20:41 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Start sign in
1. Copy magic code from email
1. Paste into box

## Expected Result:
Code is pasted

## Actual Result:
 Code does not paste at all

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [x] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 1.3.70-5

**Reproducible in staging?:** Yes

**Reproducible in production?:** Yes

**If this was caught during regression testing, add the test name, ID and link from TestRail:**

**Email or phone of affected tester (no customers):**

**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/78819774/9654353d-70fb-4b6f-9baa-e071f6cd0eaf

**Expensify/Expensify Issue URL:**

**Issue reported by:** @marcaaron

**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1694810414900189

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01a62231ee12aa601d</li>
        <li>Upwork Job ID: 1703147034962661376</li>
        <li>Last Price Increase: 2023-09-16</li>
    </ul>
</details>

**Comment by Talha345** [comment] 2023-09-17 13:32
Unable to reproduce on STG!

**Comment by narefyev91** [comment] 2023-09-18 08:09
Niether I

https://github.com/Expensify/App/assets/28352309/126508b0-be1a-444e-b77f-b41a0c017841


https://github.com/Expensify/App/assets/28352309/2c606ce3-2926-4cd2-a2f4-ffdc6fb9f432

**Comment by trjExpensify** [comment] 2023-09-18 11:14
Me neither. I've tagged @marcaaron in the [slack thread](https://expensify.slack.com/archives/C049HHMV9SM/p1694810414900189) just to confirm, but I think we'll probably close this out.

**Comment by trjExpensify** [comment] 2023-09-19 05:59
Alright, Marc can't reproduce either. Closing!

**Closed by trjExpensify** 2023-09-19 05:59 UTC
Labels: External, Daily, Needs Reproduction, Help Wanted, Bug
