### ISSUE TITLE
Validate our regression tests for anonymous accounts

### ISSUE THREAD

**Issue by roryabraham** [Expensify/App#37107] opened 2024-02-22 21:03 UTC
### Problem

We recently noticed a severe bug in production that only happened for anonymous accounts:

- Open any public room with more than 50 chats in an incognito window (not signed in)
- Scroll up
- See an infinite loop of flashing madness 💥 

### Solution
Add regression tests to cover this case, along with a number of other basic chat smoke tests for public rooms with anonymous accounts.

- Sending messages
- Uploading attachments
- Editing messages
- Reacting to messages
- etc...

**Comment by isagoico** [comment] 2024-02-26 16:06
@roryabraham while working on updating and integrating these steps to the regression run I found this issue https://github.com/Expensify/App/issues/37211 
TCs are almost done, will update here with the changes

**Comment by isagoico** [comment] 2024-02-26 19:19
TestRail is not having a good day 😅 I lost some work because the site is not stable. 
I manage to get these added tho: 
- [Public Rooms - Anon user can view real-time actions](https://expensify.testrail.io/index.php?/cases/view/2950431)
- [Public Rooms - Anon user can scroll to the top of the conversation]{https://expensify.testrail.io/index.php?/cases/view/2950433)

In these 2 we cover that the anon user sees real time actions and changes, can view attachments and that they can scroll to the top of the conversation. 

Let me know if these look good and we can close this issue out.

**Comment by roryabraham** [comment] 2024-02-26 21:07
Can we add more to verify that they can:

- send messages
- upload attachments
- react to messages

**Comment by isagoico** [comment] 2024-02-27 14:30
@roryabraham I don't think that anonymous users have the option to do those actions as they are prompted to sign in when, reacting to messages, Starting a thread, Click on settings, and other actions that require an account. 
Anon users also don't have access to the compose box so they would be unable to send messages. 
![image](https://github.com/Expensify/App/assets/44479856/c41d2457-0d68-4f87-9b61-80e434ce0b8c)

**Comment by roryabraham** [comment] 2024-02-28 01:08
Gotcha, thanks!

I think we can close this then if you agree

**Closed** 2024-02-28 01:13 UTC
Labels: Weekly, Task
