### ISSUE TITLE
[$500] Workspace - "Added with primary logins" message remains when removing members offline

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#30610] opened 2023-10-30 20:28 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.3.93-0
**Reproducible in staging?:** Y
**Reproducible in production?:** N
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** Applause - Internal Team
**Slack conversation:**

**Issue found when executing PR** https://github.com/Expensify/App/pull/23702
## Action Performed:
1. Go to staging.new.expensify.com
2. Go to workspace settings
3. Go to Members > Invite
4. Invite two users by their secondary login method
5. After the message 'added with primary logins' shows up, go offline
6. Remove one of the members
7. Remove another one
8. Go online
Note that

## Expected Result:
The message 'added with primary logins' will disappear

## Actual Result:
The message 'added with primary logins' does not disappear.
This issue only happens when the invited members are removed one by one in offline mode

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [x] Android: mWeb Chrome
- [x] iOS: Native
- [x] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos
<details>
<summary>Android: Native</summary>

</details>

<details>
<summary>Android: mWeb Chrome</summary>

</details>

<details>
<summary>iOS: Native</summary>

</details>

<details>
<summary>iOS: mWeb Safari</summary>

</details>

<details>
<summary>MacOS: Chrome / Safari</summary>

 

https://github.com/Expensify/App/assets/78819774/41f1053a-336f-468a-97f0-ed8a2f73a7a3

</details>

<details>
<summary>MacOS: Desktop</summary>

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01238d6e48e25c8436</li>
        <li>Upwork Job ID: 1719218200638939136</li>
        <li>Last Price Increase: 2023-11-21</li>
    </ul>
</details>

**Comment by marcaaron** [comment] 2023-10-30 20:36
@neil-marcellini are you looking into this one already?

**Comment by neil-marcellini** [comment] 2023-10-30 21:43
I'm just looking now. Yes that PR introduced this "issue". I don't think we should block the deploy on it because it's an extreme edge case, and the simple work around is to click the X button to dismiss the messages.

**Comment by abdulrahuman5196** [comment] 2023-11-02 16:35
Reviewing now

**Comment by abdulrahuman5196** [comment] 2023-11-02 17:06
@tienifr I am not sure if the root cause is correct. Root cause mentions the issue could occur only when there are multiple members invited and removed one by one. But I am able to reproduce the issue with even only one member.

**Comment by abdulrahuman5196** [comment] 2023-11-06 14:10
Checking again

**Comment by abdulrahuman5196** [comment] 2023-11-09 05:28
Thank you for the information @tienifr > let me check on this

**Comment by akamefi202** [comment] 2023-11-09 08:13
@abdulrahuman5196 I figured out same RCA with @tienifr already.
But I think that we can fix this issue by updating `successData`. https://github.com/Expensify/App/issues/30610#issuecomment-1802334460

**Comment by abdulrahuman5196** [comment] 2023-11-13 08:53
Hi, Will review again today, just back from weekend

**Comment by abdulrahuman5196** [comment] 2023-11-13 16:44
I think melvin went rogue here

**Comment by abdulrahuman5196** [comment] 2023-11-21 15:01
Sorry missed my radar. Will close out review today.

**Comment by abdulrahuman5196** [comment] 2023-11-21 17:46
Reviewing now.

**Comment by kadiealexander** [comment] 2023-11-27 03:16
@abdulrahuman5196 any updates on your review?

**Comment by abdulrahuman5196** [comment] 2023-11-27 11:33
@kadiealexander I think we should start the fix/investigation from backend since the ReconnectApp API is providing wrong information. More information here https://github.com/Expensify/App/issues/30610#issuecomment-1802334460 and here https://github.com/Expensify/App/issues/30610#issuecomment-1803177088

Can we involve an internal engineer?

**Comment by akamefi202** [comment] 2023-11-27 12:30
@abdulrahuman5196 
Thank you for your review. I think you misunderstood my solution because due to lack of explanation. I'm sorry.
```
successData.push({
    onyxMethod: Onyx.METHOD.MERGE,
    key: `${ONYXKEYS.COLLECTION.POLICY}${policyID}`,
    value: {
        primaryLoginsInvited: null,
    },
});
```
My solution is about adding above code inside the below conditional code block.
So only if no remaining members exist that were invited by a secondary login, `primaryLoginsInvited: null` will be added to `optimisticData` and `successData`.
There couldn't be other members added via secondary login, if `primaryLoginsInvited: null` is added to `optimisticData` or `successData`.
https://github.com/Expensify/App/blob/dc493ddfa94b9eacc2c015ae4aee090987360beb/src/libs/actions/Policy.js#L361-L370

In my opinion, I think we should fix this issue in `FE`.
Because the backend only sends the data in the database as it is, when Reconnect API is called.
The data of the backend couldn't be updated because the user created request while offline.
So it is not appropriate to say that the backend sends wrong information.

**Comment by abdulrahuman5196** [comment] 2023-11-29 17:05
FE changes would be beneficial. But I think the issue could be resolved by BE changes since ReconnectApp is providing wrong information.

But anyways, I think we should start with Backend investigation and fix, And after that if required we can make Front End fix.


@kadiealexander

**Comment by kadiealexander** [comment] 2023-12-03 23:34
Have asked an expert contributor agency to help with the back-end changes [here](https://expensify.slack.com/archives/C03UK30EA1Z/p1701646451410469).

**Comment by kadiealexander** [comment] 2023-12-06 05:21
@neil-marcellini is this something you think you could take on?

**Comment by kadiealexander** [comment] 2023-12-11 05:50
This is pretty minor and I don't think it fits a wave so I'm going to close it. Please reopen if you disagree!

**Closed by kadiealexander** 2023-12-11 05:50 UTC
Labels: Engineering, Daily, Internal, Overdue, Bug
