### ISSUE TITLE
[Create Money Request] Update iouReport optimistically 

### ISSUE THREAD

**Issue by grgia** [Expensify/App#49717] opened 2024-09-25 14:49 UTC
# Context 

Follow up to https://github.com/Expensify/App/pull/49172

Reported here: https://github.com/Expensify/App/pull/49172#issuecomment-2374163798

## Steps Taken
**MULTI TRANSACTIONS FROM DIFFERENT USERS (IOU) AVATAR CASE**

1. Log into user B in a separate session
2. Send a money request from user B
3. Verify that report preview avatar is both avatars, user A and B
4. Verify that report preview title is <name of user A> & <name of user B>
5. Both preview avatar and title are incorrect.

**Expected Result:**
Report preview avatar is both avatars, user A and B

**Actual Result:**
Report preview avatar is still only user A until refresh

## Video

https://github.com/user-attachments/assets/077ef9ff-1a99-484b-95bc-6322990c18e3

 
https://github.com/user-attachments/assets/c948febf-3340-4c57-a297-065681d62588

## Solution

I think this is probably an issue with updating the iouReport data optimistically when the IOU is made. 
https://github.com/Expensify/App/blob/main/src/libs/actions/IOU.ts#L1998

**Comment by mallenexpensify** [comment] 2024-09-27 18:23
Checking to see if this is same/similar to what Cole reported
https://expensify.slack.com/archives/C01SKUP7QR0/p1727461394841889?thread_ts=1727360298.835599&cid=C01SKUP7QR0

**Comment by mallenexpensify** [comment] 2024-10-01 23:24
Throwing on #wave-collect cuz the other avatar-related issue was on the same.  And.. the bug affects collect users. 
@grgia is working on avatars, few issues for 'em out there, bumping to weekly.

**Comment by grgia** [comment] 2024-10-14 04:54
not overdue, this is polish

**Comment by mallenexpensify** [comment] 2024-10-22 23:28
@grgia is working on. Gonna drop in Quality project for now

**Comment by grgia** [comment] 2024-11-01 10:18
I haven't jumped back into this as I was working on some higher priority quality issues, but still planning to look into a solution here

**Comment by mallenexpensify** [comment] 2024-11-07 00:30
I'm back from OOO on Nov 14th, not assigning another BZ because it's working being worked on internally and payment won't be due til after I'm back.  If one is needed please add or post in #contributor-plus to ask for one to be added, thx.

**Comment by mallenexpensify** [comment] 2024-11-19 00:49
@grgia , this needs to be Internal, right?  It looks like it's `Medium` for #quality so it might fall into the bucket of _not highest priority_ for you and others.  It's not `AutoAssignerNewDotQuality` so you can unassign if you don't think it's valuable to fix

**Comment by mallenexpensify** [comment] 2024-12-03 23:57
Waiting to get picked up internally.

**Comment by mallenexpensify** [comment] 2024-12-14 01:19
I _feel_ like this can be a `Hot Pick` so I added the label.

**Comment by mallenexpensify** [comment] 2024-12-23 19:54
Trying to get offline for xmas break, will update next week and answer the 'hot picks' questions.  I need to revisit the Slack thread too, re: redundancy of questions.

**Comment by mvtglobally** [comment] 2024-12-30 04:57
Issue not reproducible during KI retests. (First week)

**Comment by mallenexpensify** [comment] 2024-12-30 23:14
Also unable to reproduce. @eh2077 can you attempt and report back? 

<img width="503" alt="image" src="https://github.com/user-attachments/assets/8a4daf21-2f5f-464e-a7f2-9ae6b0dd23a5" />

**Comment by eh2077** [comment] 2024-12-31 00:41
@mallenexpensify It's also not reproducible from my end, so I think we can close it.

<img width="1728" alt="image" src="https://github.com/user-attachments/assets/f9686728-5b31-4ebf-a8c6-ccb749d7570b" />

**Comment by mallenexpensify** [comment] 2024-12-31 22:46
Wonderful, thanks for testing @eh2077 .

**Closed by mallenexpensify** 2024-12-31 22:46 UTC
Labels: Weekly, Internal, Bug, Hot Pick
