### ISSUE TITLE
[HOLD for payment 2024-08-05] [$125] Fix flakey SubscriptionUtils test

### ISSUE THREAD

**Issue by mountiny** [Expensify/App#45801] opened 2024-07-19 22:26 UTC
### Problem

It seems like the SubscriptionUtils tests are flaky:

```
Summary of all failing tests
FAIL tests/unit/SubscriptionUtilsTest.ts (32.87 s)
  ● SubscriptionUtils › getSubscriptionStatus › should return POLICY_OWNER_WITH_AMOUNT_OWED status

    expect(received).toEqual(expected) // deep equality

    - Expected  - 2
    + Received  + 1

      Object {
    -   "isError": true,
    -   "status": "policy_owner_with_amount_owed",
    +   "status": "policy_owner_with_amount_owed_overdue",
      }

      337 |             });
      338 |
    > 339 |             expect(SubscriptionUtils.getSubscriptionStatus()).toEqual({
          |                                                               ^
      340 |                 status: PAYMENT_STATUS.POLICY_OWNER_WITH_AMOUNT_OWED,
      341 |                 isError: true,
      342 |             });

      at Object.toEqual (tests/unit/SubscriptionUtilsTest.ts:339:63)
      at asyncGeneratorStep (node_modules/@babel/runtime/helpers/asyncToGenerator.js:3:24)
      at asyncGeneratorStep (node_modules/@babel/runtime/helpers/asyncToGenerator.js:22:9)

  ● SubscriptionUtils › getSubscriptionStatus › should return OWNER_OF_POLICY_UNDER_INVOICING status

    expect(received).toEqual(expected) // deep equality

    - Expected  - 1
    + Received  + 1

      Object {
    -   "status": "owner_of_policy_under_invoicing",
    +   "status": "owner_of_policy_under_invoicing_overdue",
      }

      370 |             });
      371 |
    > 372 |             expect(SubscriptionUtils.getSubscriptionStatus()).toEqual({
          |                                                               ^
      373 |                 status: PAYMENT_STATUS.OWNER_OF_POLICY_UNDER_INVOICING,
      374 |             });
      375 |         });

      at Object.toEqual (tests/unit/SubscriptionUtilsTest.ts:372:63)
      at asyncGeneratorStep (node_modules/@babel/runtime/helpers/asyncToGenerator.js:3:24)
      at asyncGeneratorStep (node_modules/@babel/runtime/helpers/asyncToGenerator.js:22:9)

```

Here is a [run](https://github.com/Expensify/App/actions/runs/10014812670/job/27685214273)

### Solution

Fix the flakiness cc @JKobrynski @blimpich @mananjadhav coming from https://github.com/Expensify/App/pull/44072

<details><summary>Issue Owner</summary>Current Issue Owner: @</details>
<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01fc7c3dad62f3576b</li>
        <li>Upwork Job ID: 1816873686533642172</li>
        <li>Last Price Increase: 2024-07-26</li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @twisterdotcom</details>

**Comment by mountiny** [comment] 2024-07-19 22:27
Or maybe this is fixed in main

**Comment by jaydamani** [comment] 2024-07-20 16:15
## Proposal

### Please re-state the problem that we are trying to solve in this issue.

tests for [SubscriptionUtils.getSubscriptionStatus](https://github.com/Expensify/App/blob/fa738c641e7d2b289850da7b4be11369c33b96d6/tests/unit/SubscriptionUtilsTest.ts#L314) are flakey

### What is the root cause of that problem?

The [GRACE_PERIOD_DATE](https://github.com/Expensify/App/blob/fa738c641e7d2b289850da7b4be11369c33b96d6/tests/unit/SubscriptionUtilsTest.ts#L14C7-L14C24) is declared at the beginning and is 1 second + current time so if the other tests take more than 1 second time in total, [SubscriptionUtils.getSubscriptionStatus](https://github.com/Expensify/App/blob/fa738c641e7d2b289850da7b4be11369c33b96d6/src/libs/SubscriptionUtils.ts#L256C10-L256C31) will return overdue status instead of non-overdue.

### What changes do you think we should make in order to solve the problem?

Update the 1 second added in [GRACE_PERIOD_DATE](https://github.com/Expensify/App/blob/fa738c641e7d2b289850da7b4be11369c33b96d6/tests/unit/SubscriptionUtilsTest.ts#L14C7-L14C24) to be a larger value like 1 hour.

### What alternative solutions did you explore? (Optional)
Instead of using just a constant at the beginning, we could update the [GRACE_PERIOD_DATE](https://github.com/Expensify/App/blob/fa738c641e7d2b289850da7b4be11369c33b96d6/tests/unit/SubscriptionUtilsTest.ts#L14C7-L14C24) to be now + 1 second before each test or we could also just use a function that returns now + 1 second


**Reminder:** Please use plain English, be brief and avoid jargon. Feel free to use images, charts or pseudo-code if necessary. Do not post large multi-line diffs or write walls of text. Do not create PRs unless you have been hired for this job.

**Comment by mountiny** [comment] 2024-07-22 17:39
@rojiphil can you please review the proposal?

**Comment by rojiphil** [comment] 2024-07-22 18:43
RCA of @jaydamani [proposal](https://github.com/Expensify/App/issues/45801#issuecomment-2241196206) makes sense as 1 second is too tight to check. The current time can become greater than the set time when the tests are executed to cause this flaky behavior. 
I think we can safely increase to 1 hour as proposed.
🎀👀🎀 C+ reviewed

**Comment by mountiny** [comment] 2024-07-22 21:10
Assigned @jaydamani as this flakiness is causing some headaches so hopefully we can get rid of it sooner than later

**Comment by mountiny** [comment] 2024-07-23 10:31
@jaydamani What is your ETA for the PR? THanks

**Comment by jaydamani** [comment] 2024-07-23 10:37
@mountiny will do this tonight (IST time)

**Comment by jaydamani** [comment] 2024-07-23 16:22
Created [this PR](https://github.com/Expensify/App/pull/46050) 
Also @mountiny , not sure if you are the correct person but can you please share/create the Upwork Job for this.
Thanks

**Comment by mountiny** [comment] 2024-07-25 23:42
@twisterdotcom will handle that part 🙌

**Comment by twisterdotcom** [comment] 2024-07-26 16:30
Man that was way simpler than creating a job manually!

**Comment by twisterdotcom** [comment] 2024-08-06 13:52
Updated summary above. Closing as we don't need regression for this.

**Closed by twisterdotcom** 2024-08-06 13:52 UTC
Labels: External, Daily, Overdue, Awaiting Payment, Bug
